### ISSUE TITLE
[BUG/TRINKET] - Nevermelting Ice Crystal 

### ISSUE THREAD

**Issue by imahood** [TrinityCore/TrinityCore#10026]
This trinket is from Pit Of Saron (Heroic) dropped by Scourgelord Tyrannus. 
When you use the trinket, it gives 5 stacks, which are supposed to decrease on non-dot spell crits. 

1. The bug: auto-attack (physical) critical strikes are removing stacks.
2. To reproduce this bug, equip a melee weapon and nothing else but the trinket. Use the trinket. auto-attack.

version 3.3.5a
revision f8d9a8d2e91b+
DBR 335.51

**Comment by Killyana** [comment]
``` sql
UPDATE `spell_proc_event` SET `SchoolMask`=126 WHERE `entry`=71564;
