### ISSUE TITLE
[QUEST] The Plume of Alystros

### ISSUE THREAD

**Issue by bazgrim** [TrinityCore/TrinityCore#10046]
I half this quest half way figured out, but just can't seem to think of a fully functioning way to fix it.

Essentially... The unit Alystros the Verdant Keeper (27249) is an unattackable statue. Upon using Skytalon Molts (37881) it makes the bird attackable and the NPC starts flying towards the player. What I've found out is that Skytalon Molts (37881) uses the spell 49566 which calls for the event 18223. However, there is no event 18223. It does not exist.

Any ideas?

f8d9a8d2e91b 2013-06-08

**Comment by fvicaria** [comment]
Confirmed on rev d1f2e1f4b696+
and latest db.
