### ISSUE TITLE
ModifyMoney screws gossip

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#10053]
For some reason `ModifyMoney` causes action and sender to be 0 on the next menu sent on every option added.
I tested with a basic gossip script also and it bugged, so it is not in my code.

I tried some and it seems that https://github.com/TrinityCore/TrinityCore/commit/2df1908c2933c88f1442dbde52658b3c5499a849
does have everything working well, but when I try any commit from 3 months or less, using `ModifyMoney` buggs the menu, for example https://github.com/TrinityCore/TrinityCore/commit/cecbb79a392c42511b739acc092ee7da99072ec3

When an option is clicked once and then any option is clicked again, action and sender should be printed as 0, even though they clearly should not be:

```cpp
#include "ScriptPCH.h"

class test : public CreatureScript
{
public:

    test() : CreatureScript("test")
    {
    }

    bool OnGossipHello(Player* player, Creature* creature) override
    {
        player->ADD_GOSSIP_ITEM_EXTENDED(0, "test1", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1, "", 1, false); // does not matter if cost here or not
        player->ADD_GOSSIP_ITEM(0, "test2", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
        player->SEND_GOSSIP_MENU(DEFAULT_GOSSIP_MESSAGE, creature->GetGUID());
        return true;
    }

    bool OnGossipSelect(Player* player, Creature* creature, uint32 sender, uint32 action) override
    {
        player->PlayerTalkClass->ClearMenus();
        printf("s: %u, a: %u\n", sender, action); // prints s: 0, a: 0 on second click
        player->ModifyMoney(-1); // try commenting this out and test
        OnGossipHello(player, creature);
        return true;
    }
};

void ADDSCASD()
{
    new test;
}
```

**Comment by Rochet2** [comment]
Experienced this again now on https://github.com/TrinityCore/TrinityCore/commit/3761d241196827c5d12f2af0ce1c124d9172fc82
but when testing on latest (https://github.com/TrinityCore/TrinityCore/commit/1df3ca82b7dcc0ff0ebe150ee7bc8c65208e40ea) with the test script it didnt happen.

**Comment by Rochet2** [comment]
https://github.com/Rochet2/TrinityCore/issues/3#issuecomment-115921790
Seems the issue has appeared yet again.

**Comment by Keader** [comment]
any news?
still happen sometimes in current revs e.e

**Comment by Rochet2** [comment]
@Keader Was that a question if it happens on current revs or a statement that it does happen on current revs?

If you know a (recent) rev it happens on, do post it : )
I am not sure even still if it was a bug in the compiling process, the core or something else.

I myself have not noticed this recently, but on the other hand I have not used scripts ingame for .. quite a while.
Someone did report having this within the last 6 months, but he couldnt/wouldnt give the version so it could have been any old version of TC.

**Comment by Keader** [comment]
"Current" rev, last time i checked with a TC Hash: 42028a18421f672a3292733cac73840c4e766089
I dont see any commit that should fix it.

**Comment by Rochet2** [comment]
Experienced this just now with https://github.com/TrinityCore/TrinityCore/commit/cf8380a3a77d2585f13945a53b7579a1d2fb8468
Easy way to test if the bug exists is to go to any town guard and talk to them. Then use .modify money 1 and then click one option in the guard's menu. If nothing happens then you have the issue.

To fix it I tested to clean solution and clean cache. Neither worked.
The only real fix is to send the gossip menu after the modify money update packet has been sent.

The issue with this is however that the update is not being sent directly. It is being sent on next player update. This means that we need to delay the sending of the gossip menu. However a normal timed event is not enough since timed events are processed before the updates are sent. This means that you would actually need two timed events in succession to guarantee that the update is sent before the menu. Also I am just guessing here that the update packets are indeed ALWAYS being on first update call after changing money, since otherwise the menu would bug again.

A possibly simpler solution could be to change the modify money update to be sent directly instead of on next player update. This would allow to fix the issue without changing existing scripts.

Would be nice to know if the second solution could be made and if not, then if the updates are indeed being sent always on first update call to the player since issuing a change.
Im not quite sure how to go about making the update instant.

**Comment by ariel-** [comment]
The problem is here:

https://github.com/TrinityCore/TrinityCore/blob/4a0e51ad7a9c564cf84f61567ca4d0b4a52d78fc/src/server/game/Entities/Player/Player.cpp#L16009
Triggered by client sending CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, thus calling SendQuestGiverStatusMultiple which in turn calls GetQuestDialogStatus and it clears the menues.

On f913f3bb8977c127d200d5d4a608ab434b21bbcd I merely moved the code which was already here:
https://github.com/TrinityCore/TrinityCore/blob/e4481c016a86fe7db0b83a434ea08eb7ba50174f/src/server/game/Scripting/ScriptMgr.cpp#L1632

Now why do we clear gossip menues when requesting quest status data? Should only quest menues be cleared?

**Comment by Rochet2** [comment]
I have been wondering why we clear anything at all too. The code seems to date years back.

If this causes the issue, I would remove the clear completely if no one knows why it really is there. I see no benefit in clearing the menu on "get dialog status", the menu is cleared anyways when the users talk to a questgiver.

**Comment by Shauren** [comment]
That does not answer anything, `void PlayerMenu::ClearMenus()` only clears them serverside - there is no packet sent to client but both `menuId` and `gossipListId` are sent by client and passed directly to the script hook

**Comment by Rochet2** [comment]
@Shauren The reason it buggs out is that:
- We open a gossip menu (there are options in the PlayerMenu)
- We modify money on clicking a gossip option (asynchronous packets are being sent back and forth)
- We open a gossip menu after the gossip option click to continue the dialog with the NPC (there are options in the PlayerMenu)
- Now the packets sent by modify money are received by client, which then sends packets to server
- The server receives the packets and calls `Player::GetQuestDialogStatus` in the process, which calls `PlayerTalkClass->ClearMenus();`
- Now that the player clicks an option, the data is not found from the player menu and 0 is returned for action and sender in `player->PlayerTalkClass->GetGossipOptionAction(gossipListId);

The client seems to send around the correct information, just the server side code cannot find the option data anymore after the clear when an option is clicked which is the problem.
`

**Comment by ariel-** [comment]
> Now that the player clicks an option, the data is not found on gossip select from the player menu and 0 is returned for action and sender in player->PlayerTalkClass->GetGossipOptionAction(gossipListId);

Not even, since the menues are completely empty, the check present in packet handler prevents the code from executing further.

```cpp
if (!_player->PlayerTalkClass->GetGossipMenu().GetItem(gossipListId))
```

> That does not answer anything, void PlayerMenu::ClearMenus() only clears them serverside 

Which is precisely the root cause of the issue

**Comment by Rochet2** [comment]
> Not even, since the menues are completely empty, the check present in packet handler prevents the code from executing further.

Ah yes. That is the current situation.
Original issue worked the way I described as that check did not exist at that time.

**Comment by ariel-** [comment]
Fun stuff: you added that check in #11567 :P

**Comment by Rochet2** [comment]
Resolved through the PR mentioned earlier.

**Comment by tkrokli** [comment]
For reference: commit https://github.com/TrinityCore/TrinityCore/commit/6e3a48c873079cc33655b48777c5a0c86ba70bb2
