### ISSUE TITLE
[6.x] Can't swim underwater with flying mount

### ISSUE THREAD

**Issue by vendethiel** [TrinityCore/TrinityCore#10097]
rev 180cd5c

you're supposed to be able to swim underwater with a flying mount under 6.x.
currently, trying to go underwater will only make waves

**Comment by vendethiel** [comment]
should this be closed now that 4.3.4 dev was abandoned?

**Comment by tkrokli** [comment]
The flying mount needs to be walking first to be able to enter the water. If already flying, you will be bouncing off the water and just make a speed trail wave, just like with **.gm fly on** . You have to land first.

**Comment by funjoker** [comment]
@Shauren did this maybe got fixed due to your vmap etc stuff?

**Comment by Killyana** [comment]
The flying mode is activated when the transition between ground and water happen,  you must press X to go under water. I tested with rev. f67b3993f1dd 2018-04-06 so this issue is maybe fixed with the last commit related to maps/vmaps/mmaps

**Comment by vendethiel** [comment]
idk if this still happens but it's in my Issues list
