### ISSUE TITLE
[6.x] quitting arena doesn't force rogue vanish state reset

### ISSUE THREAD

**Issue by vendethiel** [TrinityCore/TrinityCore#10096]
rev 180cd5cf6eb3b08e39d0bbff2f9762724a8a2ce3

how to reproduce : 
- mount up
- fly
- enter arena
- vanish
- quit arena during vanish "safe time" (2s)

you're flying in stealth.
##

**Comment by vendethiel** [comment]
this should also probably be retagged 6.0?

**Comment by Frytiks** [comment]
Stealth not working.

**Comment by tkrokli** [comment]
@vendethiel : It is recommended to verify if this issue exists in the same form in 6.x as it did in 4.3.4.

**Comment by vendethiel** [comment]
Yeah, but I'm not going to do it. I stopped working on 4.3.4 back then, and there's no way I'm gonna do 6.0 :).

**Comment by Killyana** [comment]
Fixed
