### ISSUE TITLE
Players can not be queued for Battlegrounds and Arenas at the same time

### ISSUE THREAD

**Issue by Bezo** [TrinityCore/TrinityCore#10105]
how it work:
now you can que only for bg or arena. 

how it should work:
"Players can now be queued for battlegrounds and arenas at the same time."
as from patch 3.3.3
link to source : http://www.wowwiki.com/Patch_3.3.3_%28undocumented_changes%29
under UI section.
##

**Comment by Gooyeth** [comment]
It is currently implemented

**Comment by tkrokli** [comment]
Ref. #3752, #21487, #21491

**Comment by Killyana** [comment]
Not fixed, you still get a message that tels you cannot queue fo BG or arena.

**Comment by Gooyeth** [comment]
Yes it is working, however, there is a limitation on random. The note talks about "Battlegrounds", but does not mention the random mode.

**Comment by Killyana** [comment]
Random or not the player must be able to tag in both queue.

**Comment by Jildor** [comment]
If you are in BG queue, you can't join to arena

**Comment by Killyana** [comment]
One issue remains, but I'm not sure if it's an issue or how it must work:
If you queue into a battleground as party (party leader), then you leave the queue, only your char will leave the queue, other players will remains tagged.

**Comment by Jildor** [comment]
Another issue is: (I'm not sure if it's an issue or how it must work)

When you join to bg queue and arena queue, when you get called to enter (bg or arena), you should be removed from another queue?

by example:
I'm in arena queue and bg queue, call to enter arena, I should be removed from bg queue??

**Comment by Gooyeth** [comment]
@Jildor: I'm not sure, but vice versa does not happen, you can also be on a battleground and be called to arenas.
