### ISSUE TITLE
[4.3.4] SPELL_AURA_INTERFERE_TARGETTING(322)

### ISSUE THREAD

**Issue by trinity-user** [TrinityCore/TrinityCore#10101]
Does not work...

rev. https://github.com/TrinityCore/TrinityCore/commit/52c7146682c977e239866ee7492f62cbbc0fc188
##

**Comment by Aokromes** [comment]
This bug is still valid on 6.x?

**Comment by Aokromes** [comment]
no answer over a a year, closing. if this bug is still valid open a new ticket filling all data properly.
