### ISSUE TITLE
[Encounter/Raid] Naxxaramas Thaddius

### ISSUE THREAD

**Issue by PlanetJupiter** [TrinityCore/TrinityCore#10126]
Hello Everyone

I have encountered a problem with the Naxxarams Encounter Thaddius

The spellPolarity Shift is bugged:
 when the boss casts it, he assigns to people a debuff at random, out of these two: http://www.wowhead.com/spell=28059 or http://www.wowhead.com/spell=28084

The damage part of the Debuff works fine, but the damage incress does not occour.

http://www.wowwiki.com/Thaddius

Sincerely yours,
Jupiter

Creature ID - 15928

DB - latest
Hash - d967162
Linux SQL

**Comment by Exodius** [comment]
@Aokromes Close as per #15523?
