### ISSUE TITLE
[Encounter/Raid] Naxxaramas Kel'Thuzad

### ISSUE THREAD

**Issue by PlanetJupiter** [TrinityCore/TrinityCore#10127]
Hello Everyone

I have encountered a problem with the Naxxarams Encounter Kel'Thuzad

In the encounter once Kel'Thuzad gets to 45% Health Points he summon adds: 

Guardian of Icecrown - These have as much HP as Kel'Thuzad (each) with the ability: Blood Tap, which is a self buff that does +15% all damage, + 10% size, and can stack up to 99 times. The Guardians will flee when Kel'Thuzad dies. Immune to CC. The Guardians stack Blood Tap every ~15 seconds, and it hits their aggro target for ~4,500. They hit for ~4,000 on plate to start but this increases rapidly over time.

Two bugs occour, the adds do not recieve the buff, and they are not immune to CC. In addition if they recieve Fear, they will get out of the map and will not appear again.

http://www.wowisrael.co.il/project.php?issueid=6856

Sincerely yours,
Jupiter

Creature ID - 16441

DB - latest
Hash - d967162
Linux SQL

**Comment by danlapps** [comment]
@Killyana Is this a SAI problem ?

**Comment by Killyana** [comment]
Kel'thuzad is scripted with cpp like all other boss, @Nyeriah made some changed on this boss months ago, I don't know if this issue is fixed.

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/12037
