### ISSUE TITLE
[Arena Bug] Ring of Valor 

### ISSUE THREAD

**Issue by PlanetJupiter** [TrinityCore/TrinityCore#10123]
Hello everyone.

I have encountered a problem with the Ring of Valor Arena. After you start the match and the elevators take you to the top, it seems that the elevators go back down again, creating spell LoS bug. Among those bugs specifially:
Warlock Demonic Circle, if it was placed on the Elevator it will teleport you to beneath the arena.
Hunter's trap's and flare will not be activated as they are place beneath the Arena aswell.

Sincerely yours,
Jupiter

DB - latest
Hash - d967162
Linux SQL

**Comment by Aokromes** [comment]
No answer for over 6 months, closing, if this bug is still valid open a new ticket.
