### ISSUE TITLE
{Combat}Pvp Combat Time.

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10159]
Hello every one,
I noticed that in pvp u leave combat after 5 seconds instid of 6 seconds.
When u hit or gettin hit by a target u leave combat after 5 seconds and its suppose to be 6 seconds.

Wowwiki quote: In PvP, a player will leave combat if they have not attacked or been attacked for 6 seconds, or all the enemy characters that have attacked you are killed.

Wowwiki Combat : http://www.wowwiki.com/Combat

TBD: 335.51
Hash:  d967162
Linux, SQL.

Thx for help,
Avichay.

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by Shauren** [comment]
Wowwiki is incorrect - looking at page history it was some guy left a comment "it's definitely longer than 5 seconds" which is not a proof (and it was 5 seconds before that)
