### ISSUE TITLE
{Achievement}Extinguishing Eastern Kingdoms (Horde Side)

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10168]
Hello every one.
The achievement "Extinguishing Eastern Kingdoms" isnt working completly good.
The objective in that achievement is to complete the quests "Desecrate this Fire!"
in several places.
When u complete the quest "Desecrate this Fire!" in Westfall it isn't giving u the credit for completing it.

Extinguishing Eastern Kingdoms - http://www.wowhead.com/achievement=1031/extinguishing-eastern-kingdoms - ID 1031
Desecrate this Fire! - http://www.wowhead.com/quest=11581 - ID 11581
Alliance Bonfire - http://www.wowhead.com/object=187564 - ID 187564

TBD: 335.51
Hash: d967162
Linux,SQL.
Thx for help,
Avichay.

**Comment by Killyana** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/1517

**Comment by sirikfoll** [comment]
da101732f99d9397634bbc92962aa959d4a476b5 fix this too.
