### ISSUE TITLE
{Item}Valor Medal of the First War

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10183]
Hello every one.
I noticed that the item " Valor Medal of the First War " He's Proc isnt suffering from diminishing returns.
The item's  " Valor Medal of the First War "  Proc is suppose to give u additional 335 Dodge raiting, But this dodge raiting isnt suffer from Diminishing returns (the more u gain the less u get).

Valor Medal of the First War - http://www.wowhead.com/item=40683/valor-medal-of-the-first-war - ID: 40683 
Valor medal of the First War Buff - http://www.wowhead.com/spell=60054 - ID 40683

TBD: 335.51
Hash : d967162
Linux,SQL.
Thx for help,
Avichay.

**Comment by Killyana** [comment]
The 335 dodge pts are added correctly, after that the core calculate the Diminishing returns for the hole dodge score, it works as intended.
