### ISSUE TITLE
{Boss/Spell}Arcane Breath - interupt able - Eye of eternity.

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10185]
Hello every one,
I have noticed that the spell "Arcane Breath" is interuptable.
The boss Malygos in Eye of Eternity cast the spell "Arcane Breath" this spell can be interupted by any kind of interupting spell.

Malygos : http://www.wowhead.com/npc=28859/malygos - ID 28859
Arcane Breath 10Men : http://www.wowhead.com/spell=56272 - ID 56272
Arcane Breath 25Men : http://www.wowhead.com/spell=60072 ID 60072

TBD : 335.51
Hash: d967162
Linux,SQL.
Thx for help,
Avichay.

**Comment by Aokromes** [comment]
Generic bug  #12020
