### ISSUE TITLE
{Spell/Boss} Malygos - Vortex

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10181]
Hello every one.
The boss Malygos in Eye of Eternity raid have a problem with the Vortex spell.
The boss fly in the air but nothing else happen.
U can see the Vortex spell but the players arent affecting from it.
What is suppose to happen is that when the boss start the Vortex spell he fly in the air and all the players will fly either and suffer damage but it isnt working.

Vortex Spell : http://www.wowhead.com/spell=56105 - ID 56105
Malygos : http://www.wowhead.com/npc=28859/ - ID 28859

U can see in this video how its suppose to work: http://www.youtube.com/watch?v=ToC0BwWlv1Q
Minute : 0:50

TBD: 335.51
Hash: d967162
Linux,SQL.
Thx for help,
Avichay.
##

**Comment by Aokromes** [comment]
still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
