### ISSUE TITLE
{RDF queue} last player request

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10191]
hello everyone, there is a problem about the queue for RDF's.
the problem shows to the "bugged" players that the RDF queue system request healer/dps/tank
and when they queue or tell to their friends to queue  they are not getting any thing or queue for ready check to the RDF.
and if they get any queue,at the ready check for the RDF the last dps cant accept the queue.
WoWWiKi link-http://www.wowwiki.com/Dungeon_Finder 
that gaming site link-http://www.thatgamingsite.com/id278-Guide-Using-the-Random-Dungeon-Finder-tool-in-World-of-Warcraft.html
wow insider link-http://wow.joystiq.com/tag/dungeon-finder/ 
wowpedia link-http://www.wowpedia.org/Dungeon_Finder
TBD : 335.51
Hash: d967162
Linux, SQL.
Thx for help.

**Comment by jackpoz** [comment]
Please enable Info level for log entities.player.character and lfg to get when players logged in/out https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L3162

**Comment by jackpoz** [comment]
some more details at #14039

**Comment by Frytiks** [comment]
http://prntscr.com/6bakih Player are in queue, but group not beign created. In LOGS is nothing.

**Comment by jackpoz** [comment]
That screenshot doesn't show locked dungeons and roles for each player so it's kind of useless. As asked many times before, set lfg logs to debug in your worldserver.conf

**Comment by Frytiks** [comment]
I have set to debug. There is no problems showed.

**Comment by Frytiks** [comment]
Hope, you should fix it fast :) tommorow i will look at it

**Comment by Frytiks** [comment]
@jackpoz My suggestion is we need something like something sLFGMgr->SetState(LFG_STATE_NONE) and call it on leave group or on kick

**Comment by jackpoz** [comment]
nope, the Vote Kick handling has to be taken out from LFG_STATE like it was at https://github.com/TrinityCore/TrinityCore/commit/e621f5fe98ac7f0c488ffb00b0d7844b7f4e27fd#diff-6ae6849306f43de0471d7f1fb42359f2L1977

**Comment by boom8866** [comment]
There are still problems

**Comment by tkrokli** [comment]
Please open a new issue ticket with full description of the problem.
Remember to _keep_ the full issue template and fill in all the required info.

**Comment by Aokromes** [comment]
there is already a ticket for it.

**Comment by boom8866** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16241
Yes, I'm just saying there's a problem
