### ISSUE TITLE
[3.3.5a]Clamlette Magnifique

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10193]
Clamlette Magnifique restores health and gives the attack and intellect buffs, but does not regen mana. http://thottbot.com/item=33004

0b9a8ccef5c4ae8971f097f464e4fbb31a38f279
Using World DB: TDB 335.52

**Comment by Rushor** [comment]
The triggered drink spell of this: http://wotlk.openwow.com/spell=72623

**Comment by Killyana** [comment]
Fixed
rev. 5dba91fb0e38
