### ISSUE TITLE
[Worgen] Two forms and attack

### ISSUE THREAD

**Issue by tagar22** [TrinityCore/TrinityCore#10192]
Forgive my problem is that the racial spell = 68996 does not appear in the spell book. They also say that when attacked is not transformed

wild gallop but if it works and transforms the human into werewolf
##

**Comment by Killyana** [comment]
This spell= 6899 is a reward from http://www.wowhead.com/quest=24593/neither-human-nor-beast
All other issues cannot be reproduced.
