### ISSUE TITLE
[Quest bug] Blightbeats be Damned!

### ISSUE THREAD

**Issue by novos** [TrinityCore/TrinityCore#10203]
Hello everyone,

I have encountered a problem with the quest Blightbeasts be Damned!
The quest provides a flare which summons a rideable mount and with the mount you suppose to kill 25 mobs.

What happens is the flare summons a mount but you cannot move with the mount or fly with it.
Also, sometimes you can move with it to a certain point in the area and it dismounts you. Trying to mount dismounts you again.
http://www.wowhead.com/quest=12072/blightbeasts-be-damned

DB - 335.51
Hash: 0e4cebf
Linux SQL

**Comment by Killyana** [comment]
If you are over the water or you summon the npc on the water you will be dismounted or cannot ride the vehicle, it's a bug from retail.
``` sql
UPDATE `creature_template` SET `InhabitType`=5, `npcflag`=16777216 WHERE `entry`=26813;
DELETE FROM `creature_template_addon` WHERE `entry`=26813;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES 
(26813, 0, 0, 33554432, 0, 0, '55971');

**Comment by zaphod77** [comment]
If this bug is in fact present in retail (I can't verify this) then the issue needs to be closed. :)

**Comment by Killyana** [comment]
There's many comments talking about that, any way the vehicle must be scripted as above.
http://www.wowhead.com/quest=12072/blightbeasts-be-damned#comments:id=988309

**Comment by Rushor** [comment]
there some videos which show that the vehicle can fly over the water:
https://www.youtube.com/watch?feature=player_detailpage&v=KoSP-CRj-J0#t=105
https://www.youtube.com/watch?feature=player_detailpage&v=vEdnCOptCcE#t=235

**Comment by StormBytePP** [comment]
Confirmed still present in rev 9b285d260e1cad66ce6e2b05948c5b4fb2850466

**Comment by Rushor** [comment]
@StormBytePP please open up a new issue for this :)
