### ISSUE TITLE
{Zone/Encounter} Quest: Find the Ancient Hero

### ISSUE THREAD

**Issue by novos** [TrinityCore/TrinityCore#10216]
Hello everyone,

I have encountered a problem in the quest Find the Ancient Hero.
It seems like the script works fine, the npc follows you like it should but in some point in the way the npc cant get off a ledge in the north side of the cave facing the questgiver and it makes him stuck and you cant complete the quest.

what should happen is the npc follows you untill you get to the questgiver and completes the quest.

NPC - http://www.wowhead.com/npc=30884/iskalder
Quest - http://www.wowhead.com/quest=13133/find-the-ancient-hero

DB - 335.51
Hash: 0e4cebf
Linux SQL

Thanks!

**Comment by Killyana** [comment]
Old issue with mmaps, fixed long time ago.
rev. 5dba91fb0e38
