### ISSUE TITLE
[Bugged Quest] An Undead's Best Friend

### ISSUE THREAD

**Issue by novos** [TrinityCore/TrinityCore#10210]
Hello everyone,

I have encountered a problem in the quest An Undead's Best Friend.

The shade's skills are entirely bugged. And he can't get into combat.
His first skill, used to assassinate the restless lookouts, doesn't get the shade into combat, therefore making it restore health constantly because he can't get into combat.

Banish Scourge Crystal - doesn't banish the crystal. does the effect w/o doing anything

Quest - http://www.wowhead.com/quest=13169/an-undeads-best-friend
abilities - http://www.wowhead.com/npc=31110#abilities

Reference to https://github.com/TrinityCore/TrinityCore/issues/6526?source=cc
but its closed without any progress.

DB - 335.51
Hash: 0e4cebf
Linux SQL

Thanks!

**Comment by Killyana** [comment]
All this issues are fixed.
rev. 5dba91fb0e38

**Comment by tkrokli** [comment]
Good job checking this out, @Killyana ! :+1:
