### ISSUE TITLE
[Hunter] Feign Death + Freezing Arrow bug

### ISSUE THREAD

**Issue by dingalinger** [TrinityCore/TrinityCore#10218]
using feign death and casting freezing arrow after,causes the target to be trapped instantly.(can use it without using Scattershot)its an annoying pvp bug & Hunters are abusing it.
https://github.com/TrinityCore/TrinityCore/commit/447ddceabad28a3a4ed1ed3bdece632d2d072246
##

**Comment by robinsch** [comment]
Can't find sources but I'm 100% sure that arming timer was / 2 when out of combat (when using Feign Death)
```diff
diff --git a/src/server/game/Entities/GameObject/GameObject.cpp b/src/server/game/Entities/GameObject/GameObject.cpp
index a4b140b..e8fcbf2 100644
--- a/src/server/game/Entities/GameObject/GameObject.cpp
+++ b/src/server/game/Entities/GameObject/GameObject.cpp
@@ -313,8 +313,10 @@ void GameObject::Update(uint32 diff)
                         // Hardcoded tooltip value
                         m_cooldownTime = time(NULL) + 10;
                     else if (Unit* owner = GetOwner())
-                        if (owner->IsInCombat())
-                            m_cooldownTime = time(NULL) + goInfo->trap.startDelay;
+                    {
+                        time_t trapDelayTime = time(NULL) + goInfo->trap.startDelay;
+                        m_cooldownTime = owner->IsInCombat() ? trapDelayTime : (trapDelayTime / 2);
+                    }
 
                     SetLootState(GO_READY);
                     break;
```

**Comment by Runico** [comment]
@robinsch, afaik that m_cooldownTime check every second, so 0.5 count as 1 sec

**Comment by robinsch** [comment]
@Runico: No it's updated on GameObject::Update.

**Comment by Shauren** [comment]
@robinsch but time(NULL) has only seconds precision

**Comment by Naios** [comment]
We are living in the times of C++11 & (14) where we got an amazing `std::chrono` implementation...

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by Keader** [comment]
Any news on this @robinsch ?

**Comment by ariel-** [comment]
7567cafec84080d26ea513242a1f540a823b8f9d

**Comment by Keader** [comment]
Why we fix it without any retail confirmation?!
How it should work? 1 sec in combat and out of combat? instant in out of combat? 0,5 sec out of combat?
