### ISSUE TITLE
{Quest Bug} Scouting the Sinkholes

### ISSUE THREAD

**Issue by novos** [TrinityCore/TrinityCore#10225]
Hello everyone,

I have encountered a problem in the quest Scouting the Sinkholes.
the Issue is : when you try to mark the sinkholes you get the message "You must be closer to a sinkhole to use your map".

Quest item does not use the correct ranges and does not count the rest of the sinkholes as a place for the quest item to be used in, while still, in the first sinkhole, if you survey it with the quest item, it still does not count towards the quest.

Quest - http://www.wowhead.com/quest=11713/scouting-the-sinkholes
Quest Item - http://www.wowhead.com/item=34920

reference to - https://github.com/TrinityCore/TrinityCore/issues/2028?source=cc
Still not working, and has no progress its closed.

DB - 335.51
Hash: 0e4cebf
Linux SQL

Thanks!

**Comment by Killyana** [comment]
You have just to stay near the Sinkholes (not inside it) and use the item.
