### ISSUE TITLE
{quest}The Honored Dead

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10229]
hello everyone,
at this quest you suppose to use Ragefist's Torch to burn any combination of 10 Dead Carvan Guards and Workers.
but When you 'talk' to the corpses it counts towards the quest and not when you use the quest item torch.
WoWWiKi quest link-http://www.wowwiki.com/Quest:The_Honored_Dead
wowhead quest item link-http://www.wowhead.com/item=37464
TBD : 335.51
Hash: d967162
Linux, SQL.
Thx for help.

**Comment by Killyana** [comment]
Fixed
rev. 5dba91fb0e38
