### ISSUE TITLE
Fishing turn in quests don't stops when someone won quests

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10238]
hello everyone,
Turn in does not disappear even after someone already won the event.
WoWWiKi link to quest-http://www.wowwiki.com/Quest:Kalu%27ak_Fishing_Derby
WoWWiKi link to NPc-http://www.wowwiki.com/Elder_Clearwater
TBD : 335.51
Hash: 0e4cebf
Linux, SQL.
Thx for help.
##

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25776
