### ISSUE TITLE
{quest} Unfit for Death

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10234]
hello everyone,
Traps can kill you sometimes. It requires you to stand on the trap and plant the fake fur. But sometimes it recognizes you as a trapper and tried to kill you. It succeeds..
WoWWiKi quest link-http://www.wowwiki.com/Quest:Unfit_for_Death
WoWWiKi link to quest item-http://www.wowwiki.com/Pile_of_Fake_Furs
TBD : 335.51
Hash: d967162
Linux, SQL.
Thx for help.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=46104;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,46104,0,0,31,1,3,25835,0,0,0,0,'','Nesingwary Trapper can be killed by the Trapped!');

**Comment by danlapps** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14393

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f723b18164b07378ba4d149590ab87504fb14dc4
