### ISSUE TITLE
[NPC] ICC NERUB'AR BROODKEEPER

### ISSUE THREAD

**Issue by tippythop** [TrinityCore/TrinityCore#10255]
I have TrinityCore rev. 4ba3c2e and DB 335.51_2013_02_14 with updates up to 2013_07_17_04_world_spell_script_names

Current issue with these guys is that when you come in combat with the three guys on the ground floor the broodkeepers spin down their web to the floor but don't actually start walking around on the floor instead they seem to still be suspended by their web but somehow moving around on the floor upside down not to mention there doesn't even seem to be a web they are hanging from just air lol. These guys just have alot of random issues, sometimes they wont come down at all and leave you in combat or when you kill them they fly back up there web to the ceiling and you cant loot them. 

There is one other npc in this area that I am not sure if I should create a separate ticket for or not. But the Deathbound Ward mob that sleeps until awoken by stepping on a trap seems to awaken when you enter the staging area and Tirion starts talking with the Lich King. The ebon champions in the area seem to be getting hit by something when this happens.

**Comment by Expecto** [comment]
Keep my fix

Script: http://paste.org.ru/?ml116d
SQL: http://paste.org.ru/?2vpnte

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/15247
