### ISSUE TITLE
SPELLMOD_DURATION Application Order

### ISSUE THREAD

**Issue by mweinelt** [TrinityCore/TrinityCore#10250]
I found this using Commanding Shout, which hase a base duration of two minutes. By the means of Booming Voice and Glyph of Command the duration can be increased but they are being increased in the wrong order resulting in a minute lost, when both are being used.

Commanding Shout 2m
Commanding Shout + Booming Voice 2/2 3m
Commanding Shout + Glyph of Command 4m
Commanding Shout + Booming Voice 2/2 + Glyph of Command 5m (instead of 6m)

This is probably because Booming Voice is applied before the glyph, resulting in
2m * 1,5 + 2m = 5m
while it should be
(2m + 2m) * 1,5 = 6m

>  Glyph of Command increases the duration of your Commanding Shout by 1 minute. With Booming Voice, this 2 minutes is further increase by 1 minute, leading to a Commanding Shout duration of 6 minutes. This helps using less rage and fewer GCDs for refreshing this buff.

http://elitistjerks.com/f47/t37804-warrior_fury_compendium/#Minor_Glyphs

Same goes for Battle Shout.

Tested on
f97cf4a1d8fe0601be70f70723efa4e0c8437b26

**Comment by Runico** [comment]
confirm

**Comment by ariel-** [comment]
This bug also seems to affect SPELLMOD_CASTING_TIME too, Bane (spellID 17792) is reducing cast time after mods, making for an unreal fast casting speed, when it should only modify base cast time.

**Comment by SQLfix** [comment]
confirm
