### ISSUE TITLE
[3.3.5] PvP Trinket Problem.

### ISSUE THREAD

**Issue by dingalinger** [TrinityCore/TrinityCore#10341]
Using PvP Trinket or Human racial when you are feared or deathcoiled causes losing control on the toon & walking for a few secs.
EDIT:Same goes for using trinket on Fear + Chains of Ice.
https://github.com/TrinityCore/TrinityCore/commit/3d6b88f5aad984ff1f35bc6bc2f67bf72c74b14e

**Comment by Aokromes** [comment]
#5995
