### ISSUE TITLE
[Bug]Nether Drake

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10372]
Bug:
The Nether Drakes always fly near ground and very rarely interract with the terrain. It seems as if they fly through it most of the time instead of starting to walk while near it.

Links:
http://www.wowhead.com/npc=18877
http://i.imgur.com/DtqyCPE.jpg

Core revision: Trinity Core ce79e3a078e6+
Database revision: TDB 335.52
Addons: Anticheat1

**Comment by Killyana** [comment]
It's a general issue, when the npc use the inhabittype 5, even if he's too close to the ground he keep flying instead of walking.
This will just made the movements  a little bit better:
``` sql
UPDATE `creature` SET `movementtype`=1, `spawndist`= 15 WHERE `id`=18877;

**Comment by Kittnz** [comment]
This is more of a core problem.

**Comment by Killyana** [comment]
Yes creature using inhabittype 4 must walk when they touch the ground instead of flying, it's a general issue like here: https://github.com/TrinityCore/TrinityCore/issues/10255

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/15247
