### ISSUE TITLE
{Visual/Bug}Traps are suppose to be Invisible

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10376]
Hello everyone,
I have noticed that hunter traps are visible.
Hunter traps are suppose to be invisible but every 1 can see them.
Only rogue is suppose to be able to see traps.

Detect traps : http://www.wowhead.com/spell=2836/detect-traps - ID 2836

TBD:335.51
hash: 55338ff
Linux,SQL.
Thx for help,
Avichay.

**Comment by w5860363** [comment]
core:https://github.com/TrinityCore/TrinityCore/commit/ba6f0d064a9ea712979c03baa9c2861a113d2e92
DB:TDB.59
Patch:https://github.com/TrinityCore/TrinityCore/pull/4726

The problem was solved, but there was no more careful testing.
