### ISSUE TITLE
{Achievement}Eye of Eternity Achievements.

### ISSUE THREAD

**Issue by TheAvichay** [TrinityCore/TrinityCore#10378]
Hello everyone,
I have noticed a problem with the achievement in Eye of Eternity.
If the player dead in the end of the raid he isn't getting the achievements he deserve.
There are several achievements in EOE but if the player dead in the end of the raid he wont get any.
The spellweaver's downfall (25) - http://www.wowhead.com/achievement=623 - ID 623
The Spellweaver's Downfall (10) - http://www.wowhead.com/achievement=622 - ID 622
You Don't Have an Eternity (25) - http://www.wowhead.com/achievement=1875 - ID 1875
ou Don't Have an Eternity (10) - http://www.wowhead.com/achievement=1874 - ID 1874
Realm First! Magic Seeker - http://www.wowhead.com/achievement=1400 - ID 1400
Poke in the Eye (25) - http://www.wowhead.com/achievement=1870
Poke in the Eye (10) - http://www.wowhead.com/achievement=1869
Eye of Eternity Achievement list - http://www.wowhead.com/zone=4500/the-eye-of-eternity#achievements

TBD: 335.51
Hash: 55338ff
Linux,SQL.
Thx for help,
Avichay.

**Comment by Aokromes** [comment]
#7075
