### ISSUE TITLE
{Quest}New Recruit

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#10399]
Greetings,
I have encountered a problem while trying to complete this quest.
I tried to fulfill the quest objective by using the item "Sigil of the Ebon Blade" on a weakened "Lithe Stalker" but the effect on the npc was wrong.
The effect of the item was supposed to subjugate the npc and allow the player to lead it to the targeted area.
The only event which happened is that the npc "Lithe Stalker" remained in the place it was charmed by the "Sigil of the "Ebon Blade" and became friendly for 60 seconds.
The effect(spell) of the item is called:"Subdued Lithe Stalker"
If this quest would have been working properly, a weakened "Lithe Stalker" could been subjugated by the player and lead to the appropriate zone for quest completion without any movement issues.

Thanks in advance :)

Oldwowhead quest link: http://www.wowhead.com/quest=13143
Oldwowhead "Subdued Lithe Stalker" spell link: http://www.wowhead.com/spell=58151
Oldwowhead Sigil of the Ebon Blade item link: http://www.wowhead.com/item=43315
Oldwowhead Lithe Stalker npc link: http://old.wowhead.com/npc=30894

I have checked this quest on two different hashes,TDB and operating system.
The results were the same.
1. Hash: 55338ff
TDB:335.51
On Linux
2. Hash: 4ba3c2e51df0
TDB: 335.52
On Win

**Comment by Killyana** [comment]
It works correctly, I cannot reproduce the issue.
