### ISSUE TITLE
[4.3.4] [BUG GOSSIP] Aldwin Laughlin and Rebecca Laughlin (Stormwind guild npc's)

### ISSUE THREAD

**Issue by dermovate** [TrinityCore/TrinityCore#10419]
Stormwind guild npc's
Aldwin Laughlin and Rebecca Laughlin's
www.wowhead.com/npc=4974/aldwin-laughlin
www.wowhead.com/npc=5193/rebecca-laughlin

BUG: Gossips are not showing, there are no choices.

These choices should appear
"How do I form a guild?"
"I want to create a guild crest"

rev. 1bb3c4a2b4e3e974f09c0df478245f8daa3a677c
##

**Comment by Aokromes** [comment]
note to self, sniff this on ptr

**Comment by Aokromes** [comment]
this was fixed few weeks ago.
