### ISSUE TITLE
{item}A Letter from the Admiral

### ISSUE THREAD

**Issue by BlackVortex** [TrinityCore/TrinityCore#10429]
hello everyone,

I got A Letter from the Admiral in the mail, but when I click on it to start the quest (The Bloodcurse Legacy) I get this error: "You don't meet the requirements for that quest".
Note: I'm playing a female Draenei Shaman (alliance side).
link to A Letter from the Admiral item- http://www.wowhead.com/item=24132
TBD : 335.51
Hash: 0e4cebf
Linux, SQL.
Thx for help.

**Comment by Killyana** [comment]
Create a new character add the quest 9602 complete it than go to the Messenger Hermesius and complete the quest 9671 (Urgent Delivery) you will receive the letter and you can start the quest.

**Comment by MrSmite** [comment]
What it boils down to is the quest The Bloodcurse Legacy (9751) can be obtained directly by talking to Odysseus. The other version (9672) is obtained by the letter. If you can't *use* the letter then you either have 9751 in your quest log or you already completed it and forgot ;)
