### ISSUE TITLE
[Bug]Shade of Akama encounter

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10430]
Bugs:

- [ ] 1. After killing Shade of Akama the option to do the encounter is still there. The text remains the same as well. If you press on the gossip option the raid gets trapped in the little room with no way out.

- [ ] 2. Only the 1st wave of mobs go after Akama.

- [ ] 3. Only Ashtongue Defender attacks Akama once he is in range. Other mobs who spawn stand still when they reach Akama.

- [ ] 4. When you clean the room and talk to akama he starts to move. When he starts the "duel-energy"
mobs are spawned and start attacking akama, exactly:

Ashtongue Defender(id:23216)
Ashtongue Rogue(id:23216)
Ashtongue Elementalist(id:23523)
Ashtongue Spiritbinder(id:23524)

Ashtongue Defender are targeteable and can be killed but the other 3 cant be killed. Evading all the time. If you defeat shade of akama, akama stay in combat and cant move.

Links:
Shade of Akama - http://www.wowhead.com/npc=22841
Akama - http://www.wowhead.com/npc=23191
1st bug - http://i.imgur.com/Pfgk3Zo.jpg

Core revision: Trinity Core 659535bac120
Database revision: TDB 335.52
Addons: Anticheat1

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1413078-bug-shade-of-akama-encounter?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plu

**Comment by Aokromes** [comment]
@Nyeriah can you give love to this? :)

**Comment by Nyeriah** [comment]
I have no idea why they refuse to attack him as the code is exactly the same as the others. I suppose it might be related to the spell used to summon them, but that's a weak guess. The condition I can do.

**Comment by Nyeriah** [comment]
Reseting in case of wipe is also sort of bugged, but I haven't looked into it

**Comment by Rushor** [comment]
the script even needs more love again xD

**Comment by susumakusu** [comment]
Can you reopen https://github.com/TrinityCore/TrinityCore/issues/16563 ?

https://github.com/Aokromes close it because I confused rev. and put eluna brach, sorry.

**Comment by Rushor** [comment]
why should we?, i added you issues to the todolist

**Comment by susumakusu** [comment]
@Rushor ok sorry.

**Comment by Keader** [comment]
Please test: #17540

**Comment by Keader** [comment]
Test with #17567
I need feedbacks :dart:

**Comment by Keader** [comment]
closed by afaaedad2def50ef32ed76ce390efa9523cb80ba
