### ISSUE TITLE
[4.3.4] Character intros get cut off early

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#10450]
__Rev:__ All
__OS:__ XP Sp3

__Bug:__

The character intros don't play through to the end

__Details:__

If you extract "Humannaratation.mp3" from speech-enUS.MPQ and play it, the last few words at the end are: "uphold the honor of humanity"

When you roll a Human and let the intro play, it cuts off part of "humanity" so it says "uphold the honor of huma".

This also happens for most of the other races. It would seem whatever timer is set in the server is too short and doesn't let the cinematic play all the way through.

Another possibility is that at the end of the cinematic the camera lands behind the player and I'm not sure if it is sending a packet at that time but the narration has not finished. Perhaps the server needs to wait an additional 10 seconds if it is receiving the packet too early.

**Comment by Aokromes** [comment]
This is valid on 6.x?

**Comment by tkrokli** [comment]
Just rolled a human hunter on rev. 9baebb1b5d6d 2016-06-14 13:28:53 +0300 (6.x branch) (Win64, Release), the end phrase ` It now falls to you to defend the kingdom and uphold the honor of humanity.` is said out loud and clear, not cut off at all. I don't see why it should be different on the other races.
