### ISSUE TITLE
Q The mist isn't listening

### ISSUE THREAD

**Issue by RedSonja** [TrinityCore/TrinityCore#10462]
Trinity Revision: a54244fb2d36+ Database Version: TDB 335.51
http://www.wowhead.com/quest=12538

Problem is when a player is killing them and has to log out, it resets their (at war) to not at war, and they can not change it back.  This makes the npcs unattackable and cannot complete the quest. Even with reputation of hated.  

Tried leaving the zone and coming back but nothing...
Did find, however that when you summon zepik and use consecration for example he will sometimes attack them putting you back (at war) with them.  This also seems to be on some kind of timer from the way it acts, but it does not always work.

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/9469 , many quest are affected.
