### ISSUE TITLE
Missing meeting stone at Vault of Archavon.

### ISSUE THREAD

**Issue by rondjb** [TrinityCore/TrinityCore#10502]
Core revision: 5164caa9ffb4
db version: TDB 335.52

I saw Issue #9747 was closed, but I also can't find the meeting stone at Vault of Archavon.
The area is allie controlled, but when my human warrior stands in the room before the entrance. Nowhere in that room is a meeting stone.
Also as GM i can't see the stone.

**Comment by Trisjdc** [comment]
@Aokromes: That's the Frozen Halls summoning stone

**Comment by Aokromes** [comment]
No, it's not:

http://i.imgur.com/70oJHyN.png

**Comment by Trisjdc** [comment]
Brain fart, was looking at the first set of coordinates

**Comment by Killyana** [comment]
You can see the meeting stone here: https://youtu.be/wJt8Km2-q4E?t=1m4s
It's around X: 5476.297363 Y: 2859.079346 Z: 418.674805 Orientation: 3.320670

**Comment by Killyana** [comment]
I found some  sniffs:
``` sql
SET @OGUID=164445;
DELETE FROM `gameobject` WHERE `id` IN (195013);
INSERT INTO `gameobject` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`position_x`,`position_y`,`position_z`,`orientation`, `rotation3`,`spawntimesecs`,`animprogress`,`state`) VALUES
(@OGUID,195013,571,1,65,5476.19,2861.76,418.675,0,1,300,255,1);

**Comment by Aokromes** [comment]
Yes, those are the one i posted 1 year ago, but, again, i don't known if core must spawn it or must be perm spawned.

**Comment by Killyana** [comment]
The faction who doesn't have the wintergasp cannot access to this area, also after the battle players from the faction which loose are teleported outside. I think it's a perma spawn.

**Comment by Aokromes** [comment]
Ok, checked retail, it's perm spawned, and door open if out of combat soon.
