### ISSUE TITLE
[TALENT] Master of Elements not properly working

### ISSUE THREAD

**Issue by bazgrim** [TrinityCore/TrinityCore#10518]
The talent Master of Elements is not working for me.
http://wotlk.openwow.com/spell=29077

Can anyone else confirm this?

33f8c3ead4da+ 2013-08-07

**Comment by Killyana** [comment]
It works for me: Sorry it's in french
With 1 fireball (cost 620 mana, I get 217)  with 3 pts on the talent Master of Elements (tested with 1 and 2 pts the gain is correct)

[Mageit] dit : Recount - Mageit : mana gagné: Maître des éléments
[Mageit] dit : 1. Mageit 217 (100%)
