### ISSUE TITLE
3.3.5a Hunter Freezing Trap Arming Time

### ISSUE THREAD

**Issue by dingalinger** [TrinityCore/TrinityCore#10530]
Hunter Freezing Trap Arming time should be 1 second but it's 2 seconds & the range is bugged also.
https://github.com/TrinityCore/TrinityCore/commit/de27cfd10243e266bc2dd275c6d1653258ebd6fb
##

**Comment by ariel-** [comment]
7567cafec84080d26ea513242a1f540a823b8f9d
