### ISSUE TITLE
DBErrors

### ISSUE THREAD

**Issue by Maxxgold** [TrinityCore/TrinityCore#10537]
TrinityCore rev. de27cfd+ 2013-08-12 01:54:15 +0200 (master branch) (Win32, Release)

SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(2, 10, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '10' for key 'PRIMARY'
SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(2, 6, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '6' for key 'PRIMARY'

**Comment by Aokromes** [comment]
Fixed few weeks ago.

**Comment by SQLfix** [comment]
commit link please

**Comment by tkrokli** [comment]
Why did not this issue originally get closed and the OP told to use a proper SQL script with matching `DELETE FROM` and `INSERT INTO` lines, removing the existing primary (unique) keys in the `memberGuid` column before inserting lines with the values 10 and 6 again? The error text clearly says that those entries existed already.

This is what a working SQL script should have looked like to avoid the errors in the OP:
```sql
DELETE FROM `group_member` WHERE `memberGuid` IN (6, 10);
INSERT INTO `group_member` (`guid`, `memberGuid`, `memberFlags`, `subgroup`, `roles`) VALUES
(2, 6, 0, 0, 0),
(2, 10, 0, 0, 0);
