### ISSUE TITLE
[Bug]Morridune does not spawn

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10577]
Bug:
After killing Aku'mai in Blackfathom Deeps Morridune does not spawn.

Note: Morridune should only spawn for the members of the Alliance.

Links:
Morridune - http://www.wowhead.com/npc=6729
Aku'mai - http://www.wowhead.com/npc=4829

Core revision: Trinity Core 740ab1816a2f
Database revision: TDB 335.52
Addons: Anticheat1

**Comment by Killyana** [comment]
Now he spawn he says (Morridune dit : Parlez-moi pour écouter mon histoire.) and he can teleport the player to Darnassus.
