### ISSUE TITLE
Problems with Smart Action 33 -SMART_ACTION_CALL_KILLEDMONSTER

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#10576]
Ok since recent updates this action seems no longer fully functional, I have already came across some quests which are now bugged eg http://www.wowhead.com/quest=12996/the-warm-up, http://www.wowhead.com/quest=12668/foundation-for-revenge.

These both use kill credits, and are no longer giving them I seen for a foundation or revenge spell 52222 Soul Font Void is a condition which must be on npc for sai to execute, and when dragged npc to soul font and confirmed aura was present but still no credit given

With the warm-up when Kirgaraat is meant to give credit he does not, it does not matter if you use vehicle or not he does not give credit and theres no condition on this one.

I have been testing with Kirgaraat and the conclusion I have came to is that smart action 33 will no longer work in a timed action list even if it is triggered by a event with a invoker
It will no give killcredit if action is triggered by an event which does not exactly have a invoker ie 2 - SMART_EVENT_HEALT_PCT, 3 - SMART_EVENT_MANA_PCT but will trigger from a event which does have a invoker ie 6 - SMART_EVENT_DEATH or 4 - SMART_EVENT_AGGRO
##

**Comment by Aokromes** [comment]
This is still valid?

**Comment by tkrokli** [comment]
Looks like I'll have to run the K3 Quest Line starting with "They Took Our Men" and see how it goes.

**Comment by dr-j** [comment]
Believe this is no longer a issue will confirm soon. know foundation for revenge uses stored target now instead of invoker

**Comment by Killyana** [comment]
``` sql
-- Sigrid Iceborn - BETWEEN 0-1% Health - Quest Credit 'Eliminate the Competition'
SELECT * FROM `smart_scripts` WHERE `event_type`=2 AND action_type=33;
```
It doesn't work if the player is on a vehicle, for other scripts there's no issue.
