### ISSUE TITLE
spellrank's bug

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#10570]
Rev:https://github.com/TrinityCore/TrinityCore/commit/fa0aaa5fa4ed93992e54cce411944e41d1fd831d
DB:TDB

if I learn the spell [Journeyman Riding] http://www.wowhead.com/spell=33391 
then I get a message "You learned the [Apprentice Riding]" http://www.wowhead.com/spell=33388
 so, when I learn the spell [Master Riding] http://www.wowhead.com/spell=90265 
I will get a message "You learned the [Artisan Riding]" http://www.wowhead.com/spell=34091

If I delete the rank chain from the db  "DELETE FROM spell_ranks WHERE (first_spell_id='33388')"  it will be ok ..

**Comment by Aokromes** [comment]
Maybe this is the reason of 6.x branch having disabled learn higher level ridings?

**Comment by tkrokli** [comment]
Thanks, going to check that out on commit 9baebb1 now.

**Comment by Aokromes** [comment]
Test after 5da217877be7f22db3bfc8ee06ca1ffad172d281

**Comment by tkrokli** [comment]
Thanks, I'm compiling it now. Going to report back after checking it out.

**Comment by Aokromes** [comment]
It works better, but still bugged.

**Comment by tkrokli** [comment]
TrinityCore rev. f6637439f484 2016-06-18 16:23:55 +0200 (6.x branch) (Win64, Release, Static)
Mostly the same as before, from what I have seen. Can not tell what has improved, if anything.

**Comment by Aokromes** [comment]
Test again after 688635ff9280ebece98d74ded5ed1f3c618718c0 old characters needs manual fix.

**Comment by tkrokli** [comment]
TrinityCore rev. 22d29ce0494c 2016-07-10 11:27:38 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_07_05_02_world.sql`

All riding trainer spells are now working as intended, including correct spell names when learnt.
This issue can be closed, just like #17304.
