### ISSUE TITLE
Core/Quest: Required items that are not tagued quest item are not checked correcly to change quest status to complete

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10586]
TrinityCore rev. d74b8f0+ 2013-08-20 00:46:56 +0200 (master branch) (Win32, Release)

Quest I.D 2583  I have all the Items and the Question Mark shows up but I can not turn in the quest.

Quest I.D 2585 Has the same issue.

Edit by Aokromes, changed title to a generic one.

**Comment by Killyana** [comment]
This issue still happen when the required items are not tagged "quest item".
To reproduce it take the 2 quests from https://woehead.way-of-elendil.fr/?npc=7506
Add the required items for both quests and notice both are completed (don't validate any quest) but one of them will have a gray quest mark and cannot be completed.

This also happen with http://www.wowhead.com/quest=24545/the-sacred-and-the-corrupt
and any other quest that requires item(s) that are not tagged quest item.

To reproduce the issue with other quests like the-sacred-and-the-corrupt you must keep the quest in you journal for many days.
