### ISSUE TITLE
Item "Instant Statue Pedestal" not working

### ISSUE THREAD

**Issue by dermovate** [TrinityCore/TrinityCore#10599]
TDB 335.52
Rev. 97a9b7695a

**Comment by lainimer** [comment]
confirm

**Comment by Killyana** [comment]
related spells:
http://wotlk.openwow.com/spell=75731
http://wotlk.openwow.com/spell=75055
Also 40246 must have a vehicleid.

**Comment by tkrokli** [comment]
OK, so 40246 = http://wotlk.openwow.com/npc=40246 (NPC ID)
Instant Statue Pedestal: http://wotlk.openwow.com/item=54212
Instant Statue: http://wotlk.openwow.com/spell=74890
The spells 75055 and 75731 are listed under "See also" for spell 74890.

**Comment by Frytiks** [comment]
Its simply to fix, just set vehicle id, spell_linked_spell and dismount and on use spell.

**Comment by Killyana** [comment]
Well seems little bit more complicated as impossible to find the vehicleid, also unit flag not_selectable and disable_movement doesn't affect guardians.
``` sql
UPDATE `creature_template` SET `VehicleId`=224, `unit_flags`=33554436 WHERE `Entry`=40246; -- 224
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (-75731, 74890) AND `spell_effect` IN (-75055, 75055, -74890);
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(74890, 75055, 0, 'Instant Statue'),
(-75731, -75055, 0, 'Instant Statue'),
(-75731, -74890, 0, 'Instant Statue');
