### ISSUE TITLE
[Bug]Durnan Furcutter

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10596]
Bug:
After turning in **Scalding Mornbrew Delivery** Durnan Furcutter says **There's nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!** twice.

How it should work:
1. Turn in **Scalding Mornbrew Delivery**
2. Durnan Furcutter should say **There's nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!** and after a short period of time **Oooooo hot hot hot! If that won''t put spring in your step, I don''t know what will!**.

Links:
Scalding Mornbrew Delivery - http://www.wowhead.com/quest=3364
Durnan Furcutter - http://www.wowhead.com/npc=836
Second text taken from here - https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/blob/master/old/updates_02/174_2012_12_15_02_world_sai.sql

Core revision: Trinity Core 740ab1816a2f
Database revision: TDB 335.52
Addons: Anticheat1

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/780010084e33f72a909f0268c9cbaeeff2ee82a8
