### ISSUE TITLE
[Bug]Words of Delivery level conditions

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10608]
Bug:
There are no level conditions for Words of Delivery(25500).

How it should work:
If level 75 and above - Words of Delivery(25286) should be given.
If level 74 and below - Words of Delivery(25500) should be given.

How it works now:
If level 75 and above - Words of Delivery(25286) is given.
If level 80 and below - Words of Delivery(25500) is given.

Note: It is likely that there is an additional condition needed for quest Words of Delivery(25286) which would need the player to not have Words of Delivery(25500). Otherwise if the player already has Words of Delivery(25500) and reaches level 75 he can take Words of Delivery(25286) and have both quests at the same time.

Links:
Words of Delivery(75-80) - http://www.wowhead.com/quest=25286
Words for Delivery(1-74) - http://www.wowhead.com/quest=25500

Core revision: Trinity Core 740ab1816a2f
Database revision: TDB 335.52
Addons: Anticheat1
##

**Comment by offl** [comment]
Try with this:
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceGroup` IN (25286, 25500);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19, 0, 25286, 0, 0, 27, 0, 75, 3, 0, 0, 0, 0, "", "Quest 'Words of Delivery' requires level 75 or higher"),
(19, 0, 25500, 0, 0, 27, 0, 74, 4, 0, 0, 0, 0, "", "Quest 'Words of Delivery' requires level 74 or lower");
```

**Comment by tkrokli** [comment]
Thank you for the contribution, @offl 👍
Nice to see the old issues getting closed.
