### ISSUE TITLE
[Bug]Bitter Rivals, Guarded Thunderbrew Barrel & Distracting Jarven

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10626]
How it should work:
1. Buy a "Thunder Ale" from the innkeeper and complete "Distracting Jarven", the "Unguarded Thunder Ale Barrel" will appear and "Guarded Thunder Ale Barrel" will disappear. If Jarven comes back, the "Unguarded Thunder Ale Barrel" will disappear and the "Guarded Thunder Ale Barrel" will reappear. If the "Guarded Thunder Ale Barrel" reappears, the player needs to redo "Distracting Jarven".
2. Turn in "Bitter Rivals" to the "Unguarded Thunder Ale Barrel". After the turn in, "Distracting Jarven" will no longer be available.

Bugs:
1. "Guarded Thunderbrew Barrel" should not be available.
2. When "Distracting Jarven" is completed, the "Guarded Thunder Ale Barrel" doesn't despawn, instead, only the "Unguarded Thunder Ale Barrel" spawns and then despawns when Jarven comes back.
3. "Jarven Thunderbrew" runs after completing "Distracting Jarven"
4. "Jarven Thunderbrew's" 1st text seems to be screwed up. Sometimes he will say his 1st line, sometimes not. If he does say it, it is empty.
5. "Distracting Jarven" is still available after completing "Bitter Rivals".
6. "Unguarded Thunder Ale Barrel" has wrong spawn coordinates. It is supposed to be a replica of "Guarded Thunder Ale Barrel" and thus they should share the same spawn.

Links:
Guarded Thunderbrew Barrel - http://www.wowhead.com/quest=403
Guarded Thunder Ale Barrel - http://www.wowhead.com/object=26
Unguarded Thunder Ale Barrel - http://www.wowhead.com/object=270
Bitter Rivals - http://www.wowhead.com/quest=310
Distracting Jarven - http://www.wowhead.com/quest=308
Jarven Thunderbrew - http://www.wowhead.com/npc=1373

Core revision: Trinity Core 740ab1816a2f
Database revision: TDB 335.52
Addons: Anticheat1
##

**Comment by TerrorBringer** [comment]
Quest simply does not work now, the guarded barrel does nothing

**Comment by tkrokli** [comment]
TrinityCore rev. 10d7ae488e32 2017-04-13 19:43:21 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB 335.62 plus updates up to and including `2017_04_30_09_world.sql`

Confirmed. Neither "Guarded Thunderbrew Barrel" nor "Distracting Jarven" can be picked up as quests. I wonder if parts of https://github.com/TrinityCore/TrinityCore/commit/16fa58176820a458eae0f7a2be1e527a33dd1d6b have been removed, there are only 3 of 6 conditions in the DB now from that solution. (You may want to test how much you need to reapply from that commit to make it work again.)

BTW, this is a continuation of several repeatable classic quests no longer working because of recent changes in quest handling.

**Comment by TerrorBringer** [comment]
I've applied https://github.com/TrinityCore/TrinityCore/commit/16fa58176820a458eae0f7a2be1e527a33dd1d6b and it still doesn't work. I also tried removing the conditions for "Guarded Thunderbrew Barrel" and "Distracting Jarven" and they still don't appear.

**Comment by TerrorBringer** [comment]
I've found the problem, Guarded Thunderbrew Barrel - http://www.wowhead.com/quest=403 and Distracting Jarven - http://www.wowhead.com/quest=308 have Bitter Rivals - http://www.wowhead.com/quest=310 as "PrevQuesId" in the "quest_template_addon", removing that and with 16fa581 applied it works.

**Comment by TerrorBringer** [comment]
```sql
-- Fix for "Guarded Thunderbrew Barrel" and "Distracting Jarven"
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `id` in (308,403);
```
I don't know if this is a workaround.

**Comment by TecDian** [comment]
Neither 308 nor 403 are typical "quests in a quest" for which a negative PrevQuestID would be required. The whole thing is controlled by conditions now, rather than simple quest chaining - and this is blizzlike. Therefore the fix seems OK to me and is no workaround.

**Comment by Killyana** [comment]
This can be pushed.
