### ISSUE TITLE
[Bug]Arcatraz Sentinel & Destroyed Sentinel

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#10647]
Bugs(The Arcatraz: Normal and Heroic):
1. There are 5 spawns of Destroyed Sentinels in The Arcatraz, there should be none. Instead, they should spawn inside an Arcatraz Sentinel when Arcatraz Sentinel dies. Destroyed Sentinels should likely despawn after Arcatraz Sentinel's body disappears or after a shorter period of time.
2. Destroyed Sentinels are targetable.
3. Arcatraz Sentinel isn't dead when he spawns. Before he is aggroed, he should be dead and once engaged, he should have ~40% health.
4. Arcatraz Sentinel doesn't cast any abilities. He should have a buff **Energy Discharge** which should be maintained until he actually dies and also **Explode** which he should use at around 5% health. When **Explode** is used, Arcatraz Sentinel should stop attacking and moving, when it detonates, the Sentinel should die.
5. There are too many spawns of Arcatraz Sentinels. There should only be 5.

Links:
Destroyed Sentinel - http://www.wowhead.com/npc=21761
Arcatraz Sentinel - http://www.wowhead.com/npc=20869
Arcatraz Sentinel - http://www.wowwiki.com/Arcatraz_Sentinel
Arcatraz video 1 part 1(7:00) - http://www.youtube.com/watch?v=ZNZTFS66SXM
Arcatraz video 1 part 2(1:30; 6:00) - http://www.youtube.com/watch?v=Al3Qyici4LA
Arcatraz video 2(2:15; 3:30; 5:45) - http://www.youtube.com/watch?v=8lB9vCxUSq4

Core revision: Trinity Core 740ab1816a2f
Database revision: TDB 335.52
Addons: Anticheat1
##

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Rushor** [comment]
hm yep, i'm on it

**Comment by Aokromes** [comment]
note to self, sniff this.

**Comment by Aokromes** [comment]
confirmed no destroyed sentinel named sentinels but feing dead "arcatraz sentinels"

**Comment by jerbookins** [comment]
60fadb3b9618

this is still broken. the arcatraz sentinels do not engage in combat and they do not gain 40% health when engaged.

**Comment by tkrokli** [comment]
Ideally, open a new issue ticket (if there is not one open already) and reference this issue if needed.
