### ISSUE TITLE
naxxanar teleport error with horde characters

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#10651]
Hi, Inside of naxxanar in borean tundre have teleport, this teleport shoulbe diferents teleport locations alliance or horde.
Players alliance are send upper of naxxanar and this work fine
Players horde are send upper of naxxanar and shouldbe send to lower of naxxanar for kill this npc http://www.wowhead.com/npc=25601

teleport: http://es.wowhead.com/object=194025 name  purple teleport

rev: https://github.com/TrinityCore/TrinityCore/commit/7135abf3a0a2bd302774535ea53d50b2fbdde301
##

**Comment by Killyana** [comment]
The area_trigger 5340 is used to handle both alliance an horde teleportation and it works correctly for both faction (depending on the quest you have): https://github.com/TrinityCore/TrinityCore/blob/7d00ae40458fe4399ca414c79a9b0a88b863267a/src/server/scripts/World/areatrigger_scripts.cpp#L198
