### ISSUE TITLE
corrupted asbringer have wrong faction

### ISSUE THREAD

**Issue by milotic** [TrinityCore/TrinityCore#10677]
hi, if player have http://es.wowhead.com/spell=28282/ should be force faction friendly with scarlet crusade but this buff cause hostil with all neutral flighmaster and still hostil with npc in scarlet monastery.

rev: https://github.com/TrinityCore/TrinityCore/commit/56886a8990a8441dbe9559988f872c0057855c87
##

**Comment by danlapps** [comment]
DB has spellid_2 as 28414

I think spell should be http://www.wowhead.com/spell=28441/

Can someone confirm its only a typo ?  If so here is proposed update
```SQL
UPDATE `item_template` SET `spellid_2`=28441 WHERE `entry`=22691;

**Comment by Killyana** [comment]
28441 is triggered by http://www.wowhead.com/spell=28282

**Comment by danlapps** [comment]
yes, but i cannot find instance of the spell 28414 listed in database as of now

thus why im wondering if its a typo or a spell removed from wowhead.

**Comment by Killyana** [comment]
The spell exists http://wotlk.openwow.com/spell=28414, the problem in this case is the spell 28442 must be linked to 28282, also 28442 is not affecting the reputation correctly (visible on gm only)

**Comment by Kittnz** [comment]
I am guessing this needs a spell CPP script.

**Comment by Keader** [comment]
Removing initial agro in Spellmgr fix this issue...

**Comment by Aokromes** [comment]
#12666 better ticket.
