### ISSUE TITLE
Quest phasing done on complete, not turn-in

### ISSUE THREAD

**Issue by wkoot** [TrinityCore/TrinityCore#10725]
It seems that quest phase changes are done on completing quests, instead of when turning them in to the questgiver.

Examples: 
The Last Line Of Defense - http://www.wowhead.com/quest=13086
The Battle For Crusaders' Pinnacle - http://www.wowhead.com/quest=13141

Especially in the case of The Last Line Of Defense, you get phased out of the phase that holds the npc to turn the quest in. Thus getting stuck ;-)

revision: f5f3ea0797fbeeef887513aae69b56f40495279a

**Comment by tkrokli** [comment]
The Battle For Crusaders' Pinnacle (http://www.wowhead.com/quest=13141) - see new issue #14125

**Comment by ccrs** [comment]
Just as #14125 evrything can be solved by setting the correct mission and status.

**Comment by tkrokli** [comment]
Mob evade issue still present on the cannon turret quest, but I suppose that is a different issue.
Phasing issue in #14125 is solved and could be used if the NPC Siegemaster Fezzik still has this issue.
(I forgot to check this time around, I was so focused on #14125 and The Battle For Crusaders' Pinnacle that I forgot to notice which issues are present and which are not on Fezzik. I _think_ I remember that he still does that fading depending on whether you move inside the hut or not. Read #14125 for more info regarding running the entire questline in the Argent Vanguard / Crusaders' Pinnacle.

**Comment by ccrs** [comment]
Problem with Fezzik seems to be that spell_area fails/gets unnecessary update on entering the hut. Looks like its the same area but "zone" changes as can be seen on minimap (just random guess).

**Comment by Killyana** [comment]
The Phasing is broken once the player takes http://www.wowhead.com/quest=13070/a-cold-front-approaches

**Comment by ccrs** [comment]
Not really, just get in and out the hut.

**Comment by tkrokli** [comment]
@ccrs : I think Killyana is referring to more issues than just NPC Siegemaster Fezzik - like the cannon tower - as well as the fact that the phase threshold in that hut should not be there if your character is in the right phase. (Correct me if I have misunderstood it.)

**Comment by wkoot** [comment]
No, what I'm saying is that the moment of phase change is wrong. Those two quests are examples.
Instead of COMPLETE > CHANGE PHASE > TURN IN, it should be COMPLETE > TURN IN > CHANGE PHASE.

**Comment by ccrs** [comment]
@wkoot seems like it can be corrected in spell_area

**Comment by Killyana** [comment]
Looks to be a core issue, I will try to explain how the phasing works for this 2 quests (13070, 13141)

Phase 1: Set by the spell 57673, starts= none, ends= quest 13070 Rewarded
Phase 2: Set by the spell 57569, starts= quest 13070 Rewards, ends= quest 13086 Rewarded

Notice: The condition "quest 13070 Rewarded" is used to remove the aura 57673 and set the aura 57569, the problem here is the cast of 57569 fails. Looks like the spell is casted before the state of the quest changes.

To understand the issue enter the area, .quest add 13070 then .cast 57569 , you will get the message "you're in the wrong area" actually the area is not wrong but the condition to cast the spell is not met, and I think this happen when the quest 13086 is rewarded, as it tries to cast the spell before the quest status changes for the player.

**Comment by SnapperRy** [comment]
@Killyana: as it is working right now, the area "Chapter I" (57673) is removed when you accept "A Cold Front Approaches". This makes the questgiver and other npcs vanish in the instant you accept the quest.

It should instead stay until you complete "A Cold Front Approaches, which is when the aura "Chapter II" is added and the nerubians/frostwyrm/cannons appear. [Here's a video about it](https://youtu.be/iV_ToRxg7WY?t=728).

I have been unable to get this working with quest_end = 13070 and quest_end_status = 64 (rewarded). This should make the aura 57673 vanish when the quest 13070 is rewarded. Instead, it prevents the aura from ever being cast to player. An uneducated guess of mine would be that any quest_end_status value different than 1 (quest not taken) is ignored when the quest_start is set to 0. I'll try to dig deeper.

In the meanwhile, can you test this?
```sql
UPDATE `spell_area` SET `quest_end_status`=1, `quest_end`=13086 WHERE `spell`=57673 AND `area` IN (4504, 4501);
```
