### ISSUE TITLE
3.3.5 Battle of Hillsbrad quest linking issue

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#10743]
Ok first of all the last quest for this chain was meant to have been changed from quest 550 to 13451 in patch 3.3, when player turns in quest 541 seems nextquestchainid still points to quest 550 even though this quest is in disables as depreciated quest, which results in player been offered quest 550 when they turn in quest 541 but not being able to accept it as its disabled.

I know nextquestchainid is wdb field but seems this is still pointing to quest which was last quest prior to patch 3.3, this quest does appear to be wdb verified but sure it should not be pointing to depreciated quest.

**Comment by danlapps** [comment]
All seems ok in DB.
ready to close ?
