### ISSUE TITLE
More Skinning Work

### ISSUE THREAD

**Issue by ZxBiohazardZx** [TrinityCore/TrinityCore#10744]
As always its WIP. if you are bored and want to help out then by all means, go ahead and find the master templates in the mess that is named skinning_loot_template

```SQL
-- --------------------------------------------------------------------------------------
-- -- Skinning Loot Revamp by ZxBiohazardZx
-- --------------------------------------------------------------------------------------
SET @var := 100000; -- Set this to the reference value, gap is 10 minimum, more ofc later (10<00X>)?
-- Var+15
UPDATE `creature_template` SET `skinloot`=@var+15 WHERE `skinloot` IN (740,741)
DELETE FROM `skinning_loot_template` WHERE `entry` IN (740,741)
-- Var+16
UPDATE `creature_template` SET `skinloot`=@var+16 WHERE `skinloot` IN (742,743,744,745,746)
DELETE FROM `skinning_loot_template` WHERE `entry` IN (742,743,744,745,746)
-- Var+17
UPDATE `creature_template` SET `skinloot`=@var+17 WHERE `skinloot` IN (5277,5280,8283,8319,8497,8319,8497)
DELETE FROM `skinning_loot_template` WHERE `entry` IN (5277,5280,8283,8319,8497,8319,8497)
-- Var+18
UPDATE `creature_template` SET `skinloot`=@var+18 WHERE `skinloot` IN (10442,10447,10814)
DELETE FROM `skinning_loot_template` WHERE `entry` IN (10442,10447,10814)

-- --------------------------------------------------------------------------------------
-- -- Add the new profiles
-- --------------------------------------------------------------------------------------
DELETE FROM `skinning_loot_template` WHERE `entry` BETWEEN @var+16 AND xxx;
INSERT INTO `skinning_loot_template` (`entry`,`item`,`ChanceOrQuestChance`,`lootmode`,`groupid`,`mincountOrRef`,`maxcount`) VALUES
-- Var+15
(@var+15,4234,40,1,1,1,1), -- Heavy Leather
(@var+15,2319,33,1,1,1,1), -- Medium Leather
(@var+15,7392,20,1,1,1,1), -- Green Whelp Scale
(@var+15,4232, 4,1,1,1,1), -- Medium Hide
(@var+15,4235, 3,1,1,1,1); -- Heavy Hide
-- @Var+16 
(@var+16, 4304,45,1,1,1,2), -- Thick Leather
(@var+16, 4234,25,1,1,1,2), -- Heavy Leather
(@var+16,15412,15,1,1,1,1), -- Green Dragonscale
(@var+16, 4235, 5,1,1,1,1), -- Heavy Hide
(@var+16, 8165, 5,1,1,1,2), -- Worn Dragonscale
(@var+16, 8169, 5,1,1,1,1), -- Thick Hide
-- Var+17
(@var+17, 4304,50,1,1,1,2), -- Thick Leather
(@var+17,15412,25,1,1,1,1), -- Green Dragonscale
(@var+17, 8170,15,1,1,1,2), -- Rugged Leather
(@var+17, 8165, 6,1,1,1,2), -- Worn Dragonscale
(@var+17, 8169, 4,1,1,1,1), -- Thick Hide
-- Var+18
(@var+18, 8170,50,1,1,1,1), -- Rugged Leather
(@var+18, 8165, 7,1,1,1,1), -- Worn Dragonscale
(@var+18, 4304, 5,1,1,1,2), -- Thick Leather
(@var+18, 8171, 5,1,1,1,1), -- Rugged Hide
(@var+18,15412, 0,1,1,1,1), -- Green Dragonscale
(@var+18,15414, 0,1,1,1,1), -- Red Dragonscale
(@var+18,15415, 0,1,1,1,1), -- Blue Dragonscale
(@var+18,15416, 0,1,1,1,1), -- Black Dragonscale
-- @Var+19
(1045,1046,1047,1048,1049,1050)
(@var+19, 8170,55,1,1,1,2), -- Rugged Leather
(@var+19,15414,25,1,1,1,2), -- Rugged Leather
(@var+19, 8165,10,1,1,1,1), -- Worn Dragonscale
(@var+19, 8171, 5,1,1,1,1), -- Rugged Hide
(@var+19, 4304, 5,1,1,1,2), -- Thick Leather

/* TODO more */
```

**Comment by tkrokli** [comment]
Just out of curiosity, since I got a question from a fellow TC core user, as well as observing it myself: The level 1-3 beasts in the starter areas drop leather items meant to drop from beasts level 11+, like Medium Leather, Medium Hide, Black Whelp Scale and Red Whelp Scale. Will this issue cover that scenario so I don't need to open a separate issue for that kind of feedback? Is there some way I could help out without knowing very much about the database structure and inner workings? :-)

**Comment by Rushor** [comment]
the skinning_loot_template which causes this is: 100008.

The question is:
Should the loot_template from 100008 be modified  or:
should the skinng loot_entry in the creature_template be modified?

Current records of 100008:
http://pokit.org/get/?62573cf3c010972698e4e20718ba2a17.jpg

**Comment by tkrokli** [comment]
Good point, good question. According to openwow.com, these 2 leather items should not drop from beasts below level 11 (I would have listed the wowhead.com lists, but they are tuned to MoP or WoD) :

Medium Leather: http://wotlk.openwow.com/item=2319#skinned-from:0+2-8+1 - Skinned from (263)
Medium Hide: http://wotlk.openwow.com/item=4232#skinned-from:0+2-8+1 - Skinned from (263)

**The Light Leather/Ruined Leather Scraps pages don't show "Mottled Boar" or  Scorpid Worker:**
Light Leather http://wotlk.openwow.com/item=2318#skinned-from:0+2-8+1 - Skinned from (302)
Ruined Leather Scraps: http://wotlk.openwow.com/item=2934#skinned-from:0+2-8+1 (147)

Unfortunately, none of the comments from before Cata 4.0.6 mention skinning, as well as there being no skinning tables for the creatures "Mottled Boar" and Scorpid Worker:
http://www.wowhead.com/npc=3098/mottled-boar#comments
http://www.wowhead.com/npc=3124/scorpid-worker#comments

What the comments from 4.0.6 and later **do** mention instead, is that the skinning does not produce any loot at all. That makes me think "perhaps these mobs were not skinnable at all during WOTLK?

**Comment by tkrokli** [comment]
Going to open a new issue to update the creature_template `skinloot` column using template 100008.
Only 3 of the creatures currently using template 100008 are correct:
- Red Whelp, https://web.archive.org/web/20110630024429/http://www.wowhead.com/npc=1042#skinning:0-14+13+2-16+1
- Lost Whelp, https://web.archive.org/web/20110803210946/http://www.wowhead.com/npc=1043 (no skinning info)
- Crimson Whelp, https://web.archive.org/web/20110706000224/http://www.wowhead.com/npc=1069#skinning:0-14-16+1

The Flamesnorting Whelp (https://web.archive.org/web/20110705092819/http://www.wowhead.com/npc=1044#skinning:0-13-15+1) uses its own `skinning_loot_template` 1044 containing Heavy Leather + Heavy Hide (as opposed to the other 3 with Light Leather + Light Hide in 100008).

The remaining 67 creatures currently using template 100008 incorrectly are:
- 36 Non-Combat Pets `type 12` (vanity pets used in pet collections etc.)
- 27 Beast creatures `type 1` summoned/quest/mechanical/unused/friendly/kittens/chickens/snakes
- 4 "Not specified" `type 10` triggers & invisible bunnies (only visible with `.gm on`)
```sql
SELECT `entry`,`name`,`minlevel`,`maxlevel`,`faction`,`npcflag`,`unit_class`,`unit_flags`,`unit_flags2`,`family`,`type`,`lootid`,`skinloot`,`AIName`,`MovementType`,`InhabitType`,`flags_extra`,`VerifiedBuild`
FROM `creature_template` WHERE `skinloot` = 100008;
```

**Comment by Aokromes** [comment]
This is still needed?

**Comment by tkrokli** [comment]
Not really. We need a rework on the `skinning_loot_template`s anyway, but I don't see much help here, only the bits about reference table values. Not sure if that is helpful unless someone want to redo it.
