### ISSUE TITLE
Return to Angrathar 3.3.5

### ISSUE THREAD

**Issue by Maxxgold** [TrinityCore/TrinityCore#10750]
TrinityCore rev. 79307bc884e6+ 2013-09-08 18:10:08 +0200 (master branch) (Win32, Release)

Return to angrathar is completable but doesn't start the wrathgate quest, nor does it change the area, and it doesnt start "Darkness stirs" like it should.

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/commit/598908b2aa058452e395b0445753f41a634dc831

**Comment by Rushor** [comment]
the movie should be played also on reward https://youtu.be/2whrNZz2USM?t=72

i will open a new issue for that
