### ISSUE TITLE
[4.3.4] Guardian Spirit

### ISSUE THREAD

**Issue by rodrigoalv** [TrinityCore/TrinityCore#10772]
hi:

The talents:

http://www.wowhead.com/spell=47788

Calls upon a guardian spirit to watch over the friendly target. The spirit increases the healing received by the target by 60%, and also prevents the target from dying by sacrificing itself.  This sacrifice terminates the effect but heals the target of 50% of their maximum health. Lasts 10 sec.  Castable while stunned.

Dont prevents the target from dying by sacrificing itself

Greetings
##

**Comment by Aokromes** [comment]
no answer over a 3 years, closing. if this bug is still valid open a new ticket filling all data properly.
