### ISSUE TITLE
immune spells

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#10799]
https://github.com/TrinityCore/TrinityCore/commit/bd8d0cfbce9a38e0f2fc8b6903434c3553faf143

DK spells  [Chains of Ice] immune but can see ice on npc

**Comment by Aokromes** [comment]
This was fixed months ago no?

**Comment by Aokromes** [comment]
No answer after more than 1 year. if this bug is still valid open a new ticket with one updated core.
