### ISSUE TITLE
Boss Cast Directions - Anub'arak and Ingvar

### ISSUE THREAD

**Issue by drpepper2** [TrinityCore/TrinityCore#10803]
Core: 458f5b9502da
DB: 335.52

So this is weird, not really sure how to categorize this:

Two bosses I can think of in particular do this: 

Ingvar the Plunderer with his Smash and Dark Smash, and Anub'arak in Azjol Nerub.

How it's supposed to work: He is supposed to cast smash/dark smash/pound, and if the tank stays in front of him, takes a bunch of damage, but if the tank moves (usual path was to run through them), then they don't take this damage.

What happens: The boss stays facing the correct direction while casting, but then immediately turns and hits the tank, no matter what, making this damage unavoidable.

NPCs
Ingvar - http://www.wowhead.com/npc=23954
Anub'arak - http://www.wowhead.com/npc=29120

Abilities
Smash - http://www.wowhead.com/spell=59706
Dark Smash - http://www.wowhead.com/spell=42723
Pound - http://www.wowhead.com/spell=59433

**Comment by Treeston** [comment]
Still happening as of 0cdf3b7a73d8, see referenced issue.

**Comment by Exodius** [comment]
@Treeston close this as per f481ae1048aac32ba3a40491f0304d0317234295?
