### ISSUE TITLE
[3.3.5] Core/Spells: Sacred Shield on Pets

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#10840]
Spell: http://wotlk.openwow.com/spell=53601
Effect: http://wotlk.openwow.com/spell=58597

All works well with this spell except when you cast it in pets, if you cast http://wotlk.openwow.com/spell=53601 in pets, the effect http://wotlk.openwow.com/spell=58597 doesnt have internal CD, maybe it has easy fix in spell_paladin.cpp in

```
void HandleEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
        {
            if(Unit* pCaster = GetCaster())
                if(pCaster->ToPlayer())
                    pCaster->ToPlayer()->AddSpellCooldown(PALADIN_SPELL_SACRED_SHIELD_EFFECT, 0, time(NULL) + 6);
        }
``` 
If you add  pCaster->ToCreature()->_AddCreatureSpellCooldown it doesnt work.
It its very abusable if paladin with warlock partner cast sacred shield on pet, the pet is immortal because everytime it has the shield.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14454 fixed this issue? i cannot test it currently

**Comment by Keader** [comment]
@Aokromes  can you re-open this?
Still bugged on Rev 6904073c9cf2d6d1291bf976b8efff55edae74bc

**Comment by Raydor** [comment]
Any news on this? someone found a fix for this?

**Comment by Golrag** [comment]
Proc cooldown is only added for players in ```Unit::ProcDamageAndSpellFor``` for some reason. Got a small fix, will PR it soon :)
