### ISSUE TITLE
[Core / Pet] [Patch] Pets at rest are too far away

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#10865]
__Rev:__ All

__Bug:__

When pets are idle, they are too far away from their owner

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by MrSmite** [comment]
> If the fix here is valid, plz open a PR.

A PR was created in 2013 (see entry below OP) and the topic was already labeled "feedback-patchfix"

**Comment by tkrokli** [comment]
Are you saying that this issue could have been closed in 2013, or did you close your PR because it did not get merged? (sorry, it is a bit confusing when I don't see if anything got added to the source)

**Comment by MrSmite** [comment]
No, I pushed the wrong branch and messed up my PR. Immediately below that (see above) I pushed https://github.com/TrinityCore/TrinityCore/commit/d1e6b603394357f3772e81779ff2741c6fdb6e8f which is still open.

Then, as you note, https://github.com/TrinityCore/TrinityCore/commit/831b4048fd91982afa40e0b1d098cd104fba8944 was merged (see above) but appears not to exist in the core.

**Comment by Aokromes** [comment]
I don't see that PR on PR lists.
