### ISSUE TITLE
[Quest] The Not-So-Friendly Skies... 3.3.5

### ISSUE THREAD

**Issue by Maxxgold** [TrinityCore/TrinityCore#10862]
TrinityCore rev. cd3ac1e4da51+ 2013-09-17 14:46:20 -0400 (master branch) (Win32, Release)

http://www.wowhead.com/quest=11035/the-not-so-friendly-skies

Fly to the shattered islands of the Dragonmaw Skyway and ambush the transporters that use the route. Recover our stolen relics! 

The problem is there are not enough transporters that you can kill to finish this quest.

**Comment by Killyana** [comment]
@Kittnz is working on the event that spawn those npcs.

**Comment by Kittnz** [comment]
Actually, you did the work! I'll try to finish, but i'm not sure if about the set active tho.

**Comment by Killyana** [comment]
Remove the set Active.

**Comment by Kittnz** [comment]
Not such a good idea because if the grid map gets inactive they will stack up and you will have 100 npcs at the same location. Not really blizzlike.

**Comment by Killyana** [comment]
Fixed here: https://github.com/TrinityCore/TrinityCore/commit/d3ebb79d78b9d914c1c782e3824060d4fdb91893
