### ISSUE TITLE
[3.3.5] Core/Quest: That's Abominable! (13288)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10876]
TrinityCore rev. cd3ac1e4da51+ 2013-09-17 14:46:20 -0400 (master branch) (Win32, Release)

http://www.wowhead.com/quest=13288/thats-abominable

Thassarian on the Skybreaker wants you to use the Abomination Reanimation Kit to create a Reanimated Abomination, which you are to use to kill 15 Icy Ghouls, 15 Vicious Geists, and 15 Risen Alliance Soldiers.

The Abomination spawns for you but you can't control it and it will not give you credit for kills. It will attack mobs but it barely does any damage.
##

**Comment by RedSonja** [comment]
Any news on this quest?

**Comment by Killyana** [comment]
If someone know how to show the pet bar, it will be fixed, I tried (type_flags= 8192	is using pet bar), but it don't works.

**Comment by sirikfoll** [comment]
I haven't researched a lot, but looking at SummonProperties.dbc, seems that this is the only entry that has SUMMON_CATEGORY_PET and SUMMON_TYPE_WILD2, 
and current core doesn't allow pet bar for SUMMON_TYPE_WILD2.
I think that the changes bellow won't break anything(leave it to the experts), and they will  make the the pet bar appear.
```diff
diff --git a/src/server/game/Entities/Creature/TemporarySummon.cpp b/src/server/game/Entities/Creature/TemporarySummon.cpp
index 12e3af3..183b789 100644
--- a/src/server/game/Entities/Creature/TemporarySummon.cpp
+++ b/src/server/game/Entities/Creature/TemporarySummon.cpp
@@ -324,7 +324,7 @@ Guardian::Guardian(SummonPropertiesEntry const* properties, Unit* owner, bool is
 {
     memset(m_statFromOwner, 0, sizeof(float)*MAX_STATS);
     m_unitTypeMask |= UNIT_MASK_GUARDIAN;
-    if (properties && properties->Type == SUMMON_TYPE_PET)
+    if (properties && (properties->Type == SUMMON_TYPE_PET || properties->Type ==  SUMMON_TYPE_WILD2))
     {
         m_unitTypeMask |= UNIT_MASK_CONTROLABLE_GUARDIAN;
         InitCharmInfo();

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a pr.

**Comment by Tauriella** [comment]
Any News for this Ancient Bug?

**Comment by tkrokli** [comment]
@Tauriella : you could start by telling us how the quest works after commit https://github.com/TrinityCore/TrinityCore/commit/025002b90789e3f506e072e68cfa68c90eef296a from September 15.

**Comment by Tauriella** [comment]
We missing in the Petbar the explusion button
https://www.youtube.com/watch?v=ndj4jIvUXOw

**Comment by tkrokli** [comment]
Sounds like an improvement to me. Minor work to add the missing button when the task bar is there.

**Comment by jerbookins** [comment]
1f834d3cd195

The Reanimated Abomination is alive for the correct amount of time, it follows you and you can use the pet bar to tell it to attack and follow, but it does not have the special abilities required to complete the quest.

**Comment by offl** [comment]
```sql
--
UPDATE `creature_template` SET `spell1`=59564, `spell2`=59576 WHERE `entry`=31692;
```
I'm pretty sure these spells should have conditions and also 'Burst at the Seams' spell isn't scripted.
