### ISSUE TITLE
[Quest]The Hunt is On!

### ISSUE THREAD

**Issue by drpepper2** [TrinityCore/TrinityCore#10906]
Build: 458f5b9502da
TDB: 335.52

Quest: The Hunt Is On (http://www.wowhead.com/quest=11794)

What's supposed to happen: Use the item and it makes the cultists shrouded in dark magic or something so you can see them.

What happens: NPC that you're supposed to kill becomes attackable, but there's no animation or change in appearance. 

Probably a low priority.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/16133
