### ISSUE TITLE
Spells aimed at back 

### ISSUE THREAD

**Issue by dafaca** [TrinityCore/TrinityCore#10916]
There are some spells like http://www.wowhead.com/spell=68867 are sopposed to deal damage at all targets in a cone behind the caster.

Actually on trinitycore they do nothing at all or in the best of the cases they deal damage to targets in front of the caster.

This is making the dragon fights almost pointless for example.

Trinity core revision: 2b9b2a7388703c6424aa8a9f00b10bffbc5fdc96
TDB revision: TDB 335.51

**Comment by Killyana** [comment]
This spell can be casted only by Onyxia on player, and it works fine.
rev. 5dba91fb0e38
