### ISSUE TITLE
[3.3.5] Arena Logout

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#10910]
So, if you logout while you are on arena or battleground, you don't get kicked from it. It's not important for battleground, but when someone exits game in arena battle, it brings some problems.

If both players or one player, when another is killed, get out of the gamе (ALT + F4, for example), arena battle doesn't ends. It means that winner's team doesn't get their win for some time and it is annoying for players.
##

**Comment by Killyana** [comment]
I'm not sure if this issue is valid.

**Comment by Jildor** [comment]
The issue is not valid, because when you press Alt+F4 the player still online, the only way to logout is #19926
