### ISSUE TITLE
Algalon keeps going out of combat when tank takes 5 stacks of phase punch and shifts into another phase

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#10921]
Seems like there's problem with threat, Algalon goes out of combat when main tank takes 5 stacks of phase punch and shifts into another phase, so his HP gets full which is hard to kill. Other spells and abilities works perfect.

Revision: 56b3e52f067f5f5d671559e6f8ce28506afce635
Database: TDB.335.52 (with updates)
##

**Comment by Keader** [comment]
Still bugged on rev b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by Keader** [comment]
Has a hackfix changing algalon faction...
Add ```me->setFaction(14);``` in ```EnterCombat``` function.

**Comment by ariel-** [comment]
https://github.com/TrinityCore/TrinityCore/commit/69fd6245dc41dca658cadb4e99c1ee6593fe000b
