### ISSUE TITLE
[Creature]Thistleshrub Rootshaper

### ISSUE THREAD

**Issue by drpepper2** [TrinityCore/TrinityCore#10944]
Build: 20d070172bae
TDB: 335.52

Creature: Thistleshrub Rootshaper (http://www.wowhead.com/npc=5485)

What's wrong: He spawns an Earthgrab Totem (Entry 6066, http://www.wowhead.com/npc=6066) which is supposed to apply Earthgrab (http://www.wowhead.com/spell=8377), but instead it slides across the ground and attacks you.
##

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Killyana** [comment]
Yes same issue as almost all totems summoned by npcs.

**Comment by offl** [comment]
Actually http://www.wowhead.com/spell=8378/earthgrab-totem should be in c_t_a -_-

**Comment by tkrokli** [comment]
Thistleshrub Rootshaper (http://www.wowhead.com/npc=5485/thistleshrub-rootshaper) was removed in patch 4.0.3 , but is the totem issue also valid for Legion?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 6e0df9fce1e1
