### ISSUE TITLE
[4.3.4] Steady Shot Quest

### ISSUE THREAD

**Issue by NexenTUS** [TrinityCore/TrinityCore#10969]
http://www.wowhead.com/quest=25139

Simply dont work on 3611d82e628cbdf8537fe96bd362ca14281682c3
Learning spell Steady Shot gives complete but use of Steady Shot dont increase number and quest can't be completed.
##

**Comment by tkrokli** [comment]
This issue is no longer up to date. Current problem on master (7.x) is that hunters don't even get the spell.
