### ISSUE TITLE
[Quest] Examples to be made 3.3.5a

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10991]
TrinityCore rev. 13e3abd06aff+ 2013-10-03 08:56:55 -0400 (master branch) (Win32, Release)

http://www.wowhead.com/quest=12907/examples-to-be-made

Mildred the Cruel at the Forlorn Mine wants you to slay Garhal. 

the guards are killing it before you can get agro therefor you dont get credit for itthe real problem is that there is only supposed to be one overseer there is currently 3 of them there
##

**Comment by Aokromes** [comment]
Note to self, sniff this.

**Comment by Aokromes** [comment]
They don't attack him.

**Comment by Killyana** [comment]
Blizzlike http://www.wowhead.com/npc=30147/garhal#comments:id=647539:reply=97356
