### ISSUE TITLE
[Quest] Argent Dawn Commission quest  3.3.5a

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10998]
TrinityCore rev. 682c6eac09f7+ 2013-10-04 08:49:16 -0400 (master branch) (Win32, Release)

http://www.wowhead.com/quest=5503/argent-dawn-commission

you can continuously complete the Argent Dawn Commission quest from Argent Quartermaster Lightspark to gain  reputation over and over again as long as you keep deleting the Argent Dawn Commission trinket.
##

**Comment by offl** [comment]
[This video](https://youtu.be/jKPDoC8EraY?t=28) shows the first interraction with NPC. Unfortunately she didn't clicked on quest-giver in second time. So we can't see what happens when you turn-in Argent Dawn Commission quest and what quest becomes available as repeatable(blue question mark).

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/77fc52b1b6f2900e5c4b809bd34d02d31bfdf4b1
This 3 quests are no longer repeatable.

**Comment by offl** [comment]
Oh, I saw the commit but didn't know that ExclusiveGroup makes quests non-repeatable.

**Comment by Killyana** [comment]
No the quest 5503 was flagged as repeatable  on quest_template_addon (SpecialFlags=1)
