### ISSUE TITLE
(SPELL_ATTR3_UNK13)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#10992]
This a result of my researchments:
SPELL_ATTR3_UNK13  should prevent channeled spells from being canceled if another spell gets casted while the spell is channeled.

so an example:
you have a ticking aura  with spell attr. 
SPELL_ATTR1_CHANNELED_1 and
SPELL_ATTR3_UNK13 should continue to channel if another spell gets casted.

**Comment by Aokromes** [comment]
@Shauren this is valid?

**Comment by Shauren** [comment]
No,
`SPELL_ATTR3_DONT_DISPLAY_CHANNEL_BAR         = 0x00002000, // 13 Clientside attribute - will not display channeling bar`
