### ISSUE TITLE
[NPC] Caladis Brightspear <wip>

### ISSUE THREAD

**Issue by drpepper2** [TrinityCore/TrinityCore#11015]
Build 6cef507
TDB 335.52

NPC Caladis Brightspear (DB GUID 54430) isn't visible to players, but he is visible to GM characters. He is supposed to be, so that people can turn in the Battered Hilt quest right after getting out of the Frozen Halls.

**Comment by Rushor** [comment]
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1001
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 19 (SPELL_AURA_MOD_INVISIBILITY_DETECT), value = 1001, misc = 8 (8), miscB = 0, periodic = 0

seems to have no influence to gameobjects

**Comment by Aokromes** [comment]
After 9d59d038f8b09ed036448e755cb0b102396a4ca1 this can be fixed.

**Comment by Killyana** [comment]
Fixed here https://github.com/TrinityCore/TrinityCore/issues/15014
