### ISSUE TITLE
(SPELL_AURA_361)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#11011]
Another researchment result:
spell aura SPELL_AURA_361 is always used to trigger a spell, btw it replaces melee attacks with those triggered spells.

example:
- the creature gets such an aura and should trigger a spell that casts and aoe splash
- the melee damage is 0 and on each melee hit the spell is triggered instead.
##

**Comment by Aokromes** [comment]
This is still needed?

**Comment by Aokromes** [comment]
no answer over a year, closing. if this bug is still valid open a new ticket filling all data properly.
