### ISSUE TITLE
Required Money for Quest

### ISSUE THREAD

**Issue by drpepper2** [TrinityCore/TrinityCore#11027]
6cef507
DB: TDB 335.52

Problem: Basically, if you accept a quest that requires money, and you do not have that money, you can't turn it in. You have to abandon the quest and re-acquire it after you have the required money in order for it to be completed.

Shouldn't it work where the quest is completeable as soon as I acquire enough money?

**Comment by Killyana** [comment]
Works as intended:
1- remove all golds
2- .add quest 13846 (the quest is not completed at this level)
3-  .mod mon 100000 (the message quest completed will appear and the quest will be completed and you can turn it)
4- .mod mon 10000 (1gold will be removed and the quest will turn not completed)
