### ISSUE TITLE
Creatures don't chase/follow pure Z axis moves while swimming

### ISSUE THREAD

**Issue by bele** [TrinityCore/TrinityCore#11060]
For ba1a4cd0ce51a0a6389317199c66fd85deffac02

Steps to reproduce: attack a creature in a body of deep water, and make sure you're right in the same place as them. Then swim directly down or up. When you move out of their combat range, they'll stop being able to attack, and will not follow you. (This also happens with hunter pets; or at least the ones for which swimming isn't broken.)

Expected behavior: They follow you to continue the attack.

The problem seems to be in TargetedMovementGenerator.cpp, in DoUpdate. Creatures which can't fly won't register that the target (i.e., the player attacking them) has moved away if the movement is entirely up/down, because non-flying creatures use IsWithinDist2d to check that.

I don't know if this should just be switched to always use IsWithinDist3d, or if a check should be added to see if the creature which is moving is in the water.
##

**Comment by Killyana** [comment]
You can also see this issue when you summon a creature in the water, it will fall to the bottom.
