### ISSUE TITLE
[Spell] Blessings are removed from living NPCs after combat

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#11111]
__Rev:__ f6f102c70b

__Bug:__

When an NPC that has a Paladin blessing on it exits combat, the blessing is removed even if there is still time left

__Expected:__

Paladin Blessings should persist until the timer expires or the NPC is killed.

__Details:__

This example uses Protector Korelor (GUID 89538) in Westfall:

Take a low level Paladin (eg: level 7) into Westfall. Cast Blessing of Might on Protector Korelor, aggro a hostile mob and let Korelor kill the creature. Once combat is over and he resumes pathing, the blessing is removed from him.

__Notes:__

* GPS coordinates not provided because the NPC patrols between Duskwood and Sentinel Hill so the data would be irrelevant.
* Low level Paladin suggested for testing because you can proximity aggro the mob which allows Korelor to take aggro easier.
* Not tested on NPCs that were not patrolling (eg: no waypoints). Not sure if this has anything to do with the waypoint system or not.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/14347

**Comment by MrSmite** [comment]
> Dup #14347

Actually this is the older report thereby making #14347 the duplicate...
