### ISSUE TITLE
DB/Quest: What Is Going On? (3982) - no mobs spawn

### ISSUE THREAD

**Issue by mogudy** [TrinityCore/TrinityCore#11115]
Core revision: 0177d1c4d4267836c55c0294aa359e131a5680fd
DB version:    3.3.5.52

No mobs coming in after Gor'shak's words.
http://www.wowhead.com/quest=3982
##

**Comment by tkrokli** [comment]
TrinityCore rev. ad74638 2016-08-01 19:56:46 -0300 (3.3.5 branch) (Win64, Release, Static) / TDB 335.61

Confirmed. Still not scripted as of today. Does anyone have an idea of how many NPCs should be involved in the ambush? I can't find any info about this quest event in the usual sources (wowhead, wowpedia, wowwiki or YouTube). Maybe the quest should be set to Auto Complete until a solution is found?

**Comment by offl** [comment]
https://github.com/cmangos/classic-db/commit/16ab4f191963fb48b651092c2d87686db0ed687a

**Comment by sirikfoll** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/a48ca214ed40f2ffde1fd13d50b0e464a209c5da

**Comment by illfated** [comment]
Nice. Thanks for closing this old issue
(should have been noted in **[DB/Quest: What Is Going On?](https://github.com/TrinityCore/TrinityCore/issues/22569) #22569**).
