### ISSUE TITLE
[Item] Bobbing apple does not give well fed buff

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#11142]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/f6f102c70b
__DB:__ TDB_full_335.11.46_2012_02_13 + updates

__Bug:__

[Bobbing apple](http://www.wowwiki.com/Bobbing_Apple) does not give the *well fed* buff as noted in the tooltip.

__Notes:__

The description on wowhead is for the 4.0.x version which has the *unique* tag removed as well as the stamina buff. The wowwiki link provided above matches the one in Trinity.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (-24869, -61874, -71074, -71068, -71073, -71071)  AND `spell_effect` = 24870, ;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(-24869, 24870, 0, 'Bobbing Apple, Bread of the Dead, Winter Veil Cookie'),
(-61874, 24870, 0, 'Noblegarden Chocolate'),
(-71074, 24870, 0, 'Buttermilk Delight'),
(-71068, 24870, 0, 'Sweet Surprise'),
(-71073, 24870, 0, 'Dark Desire'),
(-71071, 24870, 0, 'Very Berry Cream');
