### ISSUE TITLE
Quest 11471 The Jig is Up, NPC not flee

### ISSUE THREAD

**Issue by mogudy** [TrinityCore/TrinityCore#11157]
Core rev. 3d5a317b755f4b6eb2d9a29fd7d9291415dfa6eb 
DB ver. 335.52 -> 2013_10_28_00_world_sai

http://www.wowhead.com/quest=11471

Quoted from wowhead, "at 30% hp he'll run from you and jump through a whole in the gate and he'll get eaten by the big o'l bear down there. Kill the bear (who has like NO hp as of right now) and you'll loot the head."

The fact is, this guy is too brave and never flee to the hole. 

[Update] You can directly kill the bear to get the scope. however, it's just illogical to find it in a bear without seeing it eating anything.
##

**Comment by Killyana** [comment]
The Actual script is correct but as there's an evade action in the action_list the npc reset and don't finish the script, the evade mechanism somehow screwed up everything.

**Comment by offl** [comment]
#16580
