### ISSUE TITLE
End Time [Instance]

### ISSUE THREAD

**Issue by Pictu** [TrinityCore/TrinityCore#11178]
End Time don't work. There is no teleport list in go or npc.
REv. - https://github.com/TrinityCore/TrinityCore/commit/184fe092c3a7d37eb3983ec11e3f5d3a9f6640fa
TDB - Latest + Updates
##

**Comment by BahDumbBugs** [comment]
Wishing I could get rid of rude comments like the second poster. While End Time Instance is not fully working, as of commit 8b2e071, the Instance is open and enter-able. Teleport at the beginning still does not. (Not asking for rush on this either, nor do I care. LOL)

**Comment by Killyana** [comment]
Raid not scripted https://github.com/TrinityCore/TrinityCore/issues/13179
