### ISSUE TITLE
Skinning - Icehowl & Anub'Arak

### ISSUE THREAD

**Issue by Ric101** [TrinityCore/TrinityCore#11182]
For Trial of the Crusader bosses, namely Icehowl and Anub'Arak, you cannot skin them after completely looting them.

This is caused by the fact that all ToCr bosses generate 2 versions of loot - Alliance and Horde. They are never really 'fully looted' (for obvious reasons), and thus UNIT_DYNFLAG_LOOTABLE is not removed. Without UNIT_DYNFLAG_LOOTABLE removed, skinning cannot be performed.

This is a generalized issue for any creature with conditional loot.

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/12086
