### ISSUE TITLE
On crash players lose xp, rep but quests can't be redone (15$ bounty)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#11187]
**Rev:** All
**DB:** N/A

**Bug:**

When the server crashes between player updates, players lose XP and rep but quests that have been completed are still marked as rewarded which means they cannot be done again to regain the XP and rep.

**Details:**

Quests that are completed are marked rewarded instantly but nothing else is saved until the player save interval has passed. To remedy the bug above, the following should be saved along with quest completion status
- Player's current XP
- Player's current Rep (all factions)
- Player's current level and unspent talents
- Player's inventory (to save quest rewards and items otherwise unobtainable)

By saving those items when a quest is marked completed, the player has minimal loss at crash since these all depend on being able to redo a quest which givent he current coding is not possible.

**[See my other suggestion below about QUEST_STATUS_PENDING](https://github.com/TrinityCore/TrinityCore/issues/11187#issuecomment-27929031)**

**Notes:**

Consider when a player completes several quests, earning several thousand XP, a level, a talent point and rep with a faction which cannot be gained via mob kills (ie: some factions like Argent Dawn can be gained by dungeon runs but most can't).

Having a GM grant the level and unspent talent would be simple enough but figuring out which quests were completed, how much xp, which factions gained rep (including "spill over" to other factions) and calculating that rep, and giving the player back quest rewards would be time consuming at best.
##

**Comment by Aokromes** [comment]
15$ bounty added here.

**Comment by jackpoz** [comment]
imo all the db updates related to a Player should be queued to the Player itself and executed asynchronously on next Player save, the issue here is caused by mixing sync and async updates

**Comment by MrSmite** [comment]
> Imo all the db updates related to a Player should be queued to the Player itself and executed asynchronously on next Player save, the issue here is caused by mixing sync and async updates.

Agree, that's kind of what I was suggesting with QUEST_PENDING as a status though that may not be necessary if everything is queued to the Player.

> If this means allowing to receive the quest item multiple times in case of a crash, then that's a lower priority issue.

If done properly, this shouldn't be an issue. If the quest had been turned in (eg: marked REWARDED) but *Player::Save()* was not called before a crash, at next login the player would have the quest ready for turn in (eg: marked COMPLETED) and the previous reward would be gone, and all necessary items to facilitate the turn in would be back in the inventory.
