### ISSUE TITLE
[6.x][Warrior] Blood Craze

### ISSUE THREAD

**Issue by SunnyTheCool** [TrinityCore/TrinityCore#11215]
Actually, Blood Craze doesnt heal 4% in 5secs, but 4% every sec in 5 sec, so 20%. 
##

**Comment by Jenkyins** [comment]
i have a problem with this talents too. It seems that it doesn't work with priest's Devouring plague initial critic and with every critic of mind flay.
b1d0855624d1c83850fc36f5242437d7f7c1336b
