### ISSUE TITLE
[ITEM] Magic Dust

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#11234]
Item: http://www.wowhead.com/item=2091

Problem: It's not supposed to work at all on lvl 80's. It should have 100% malfunction chance. It is, however, always working currently making it incredibly overpowered. It's not usable in arena (Tested), but it can be used in Battlegrounds.

TDB 52 + Repo updates
Revision: 055af93145a636913e2592993aa87e828ee00a66

**Comment by Rushor** [comment]
some more items mentioned in this: https://www.worldofcorecraft.com/content/using-cool-items-pvp

leveldependend calculaion would be nice :D

**Comment by Aokromes** [comment]
#7789
