### ISSUE TITLE
[NPC] Defenders at Bloodmyst Isle (Blood Watch)

### ISSUE THREAD

**Issue by Voy80** [TrinityCore/TrinityCore#11243]
Few defenders are overlapping, one of them is quest giver*. Here is list:
Defender Auston with Defender Katroi;
Defender Kadithuul with Defender Kranos;
Defender Zaibach with *Defender Sorli;
Defender Ursi with Defender Ashoon;

Rev: 1bec9466a6fd

http://www.wowhead.com/npc=18025
http://www.wowhead.com/npc=18034

http://www.wowhead.com/npc=18027
http://www.wowhead.com/npc=18023

http://www.wowhead.com/npc=18031
http://www.wowhead.com/npc=18024

http://www.wowhead.com/npc=18022
http://www.wowhead.com/npc=18032

**Comment by Killyana** [comment]
``` sql
UPDATE `creature` SET `position_x`=-2063.806396, `position_y`=-11865.276367, `position_z`=49.418633, `orientation`= 0.563756 WHERE `guid`=84397;
UPDATE `creature` SET `position_x`=-1903.960938, `position_y`=-11887.980469, `position_z`=41.457340, `orientation`= 1.451245 WHERE `guid`=84395;
UPDATE `creature` SET `position_x`=-1905.073120, `position_y`=-11871.288086, `position_z`=41.075207, `orientation`= 4.769557 WHERE `guid`=84396;
UPDATE `creature` SET `position_x`=-2025.857300, `position_y`=-11840.670898, `position_z`=47.815887, `orientation`= 4.198586 WHERE `guid`=84428;
