### ISSUE TITLE
{3.3.5a} [Quest] No Mere Dream

### ISSUE THREAD

**Issue by Exodius** [TrinityCore/TrinityCore#11252]
Related Issue Report: #8689

Quest: [No Mere Dream](http://www.wowhead.com/quest=10965)
QuestGiver: [Clintar Dreamwalker](http://www.wowhead.com/npc=22834)
Related: [Clintar Dreamwalker's Spirit](http://www.wowhead.com/npc=22916)

Problem: From what I've seen, you can complete the quest only once per session.
In every next case Clintar's spirit becomes either
* Invisible, making it impossible to track unless turn GM status
* Invisible, making it impossible to track even if you DO have GM status
* Turns into a ghost [Like this but green in color](http://wow.zamimg.com/uploads/screenshots/normal/89933.jpg)
* Turns into a cat (critter cat model).

I don't know what model he should have but I think it should be one of Druid's Cat forms.
In majority of these cases, quest does not get rewarded for completion when you help him.

Revision: 055af93145a636913e2592993aa87e828ee00a66
TDB 52 + Repo updates

**Comment by SQLfix** [comment]
Just Try This  :D
I dont know why use modelid2 [ not in core ] but work fine . . .
```sql
UPDATE `creature_template` SET `modelid2` = 16622 WHERE `entry` = 22916;
```

**Comment by Aokromes** [comment]
swaping modelid without sniff is hack, and sniff over you show it's hack.

**Comment by SQLfix** [comment]
i know is hack . just i want help someones to fix [hack] Quest 
Online server need to fixed Quest Hack or Not 
if anyone want use it . if u want delete IT 
No problem

**Comment by SQLfix** [comment]
I Deleted My Hack fix [ for me work fine ]
tanks Aokromes

**Comment by Ryosan23** [comment]
Tested @Rushor fix and still bug.

No way to see npc without gm mode

**Comment by Killyana** [comment]
This will fix all the issues, maybe some parts as unitflag not selectable and flags_extra=128 must be removed by the cpp one th npc spawn, also the model 16622 can be forced on spawn
``` sql
UPDATE creature_template SET `flags_extra`=0, `unit_flags`=36864 `modelid2`=0 WHERE `entry`=22916;
UPDATE `smart_scripts` SET `event_phase_mask`=0 WHERE `entryorguid`=22834 AND `source_type`=0 AND `id`=1 AND `link`=2;
UPDATE `smart_scripts` SET `event_phase_mask`=0 WHERE `entryorguid`=22834 AND `source_type`=0 AND `id`=2 AND `link`=0;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry` IN (22834) AND `SourceId`=0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(22,2,22834,0,0,1,0,39601,1,0,1,0,'','Event SAI triggred only if the player don''t have the aura 39601');

**Comment by L30m4nc3r** [comment]
still bugged.
