### ISSUE TITLE
[Quest] Ending the Bloodcurse

### ISSUE THREAD

**Issue by Voy80** [TrinityCore/TrinityCore#11253]
Quest works fine while not in the group. If you are in group every member has to destroy object and for each new boss is summoned. (This actually applies to most quests when taken by group, as far as I've seen)

Rev: 1bec946

http://www.wowhead.com/quest=9683

Edit: Solution?: Forbid triggering quest until target destroyed, and if in group all get finished after target destroyed. (all this types of quest)

"'Tree's Company" is example of other quest where it happens, (no fight this time but you see multiple npcs and conversations)

http://www.wowhead.com/quest=9531

**Comment by Killyana** [comment]
I tested both quests in party and  I get credit for both characters. Seems like party credit is fixed.
rev. 5dba91fb0e38
