### ISSUE TITLE
[Loot] Only one type of fishable loot in Eversong Woods

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#11251]
**Core (335a):** 1bec946
**DB:** TDB_full_335.11.46_2012_02_13 + Updates

**Bug:**

While fishing in Eversong Woods, the only thing you can catch is Raw Slitherskin Mackerel. If I am interpreting the wiki properly, this is all that's listed in `fishing_loot_template`:

``` SQL
SELECT * FROM fishing_loot_template WHERE `entry`=3430;

-- Result: item=11001, chance=100, group=1, mincountOrRef=-11001
```

According to [this](http://www.elsanglin.com/fish/eversong_woods.html) and [this](http://www.wowhead.com/zone=3430/#fishing) the fishable loot should include many other fish and items

**Notes:**

According to the wiki when group > 0 and mincountOrRef < 0

> Group reference asks core to process another loot template (having entry equal to "-mincountOrRef")

but neither of these turn up any records:

``` SQL
SELECT * FROM fishing_loot_template WHERE `entry`=-11001;
SELECT * FROM fishing_loot_template WHERE `entry`=11001;
```

So, while there is only one item fishable in Eversong Woods, the template description isn't clear as to how this loot is even arrived at given that the "other template" doesn't seem to exist.
##

**Comment by Killyana** [comment]
After 50 fish in Eversong Woods and 50 in Elwynn Forest I get only Raw Brilliant Smallfish and Raw Longjaw Mud Snapper looks like the FISH_JUNK_GROUP is not in the drop list for some areas: https://github.com/phoenixfight/TrinityCore/commit/ae46affe4e8d69219a28df7b5557a323a2b1f248

**Comment by MrSmite** [comment]
@Killyana The PR you linked takes care of junk loot but it still doesn't address the other fish / items that you should get such as potions, armor, etc.

http://www.wowhead.com/zone=3430/eversong-woods#fishing
