### ISSUE TITLE
[ICC] Valithria Dreamwalker 10 Heroic

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#11265]
I will try to explain the problem. The boss works well only the first time you try it. If you wipe, the moobs continue spawning and the event doesn't restart. It only happens in heroic mode. In normal mode it works ok.

commit: d2065b0e502265e9b9127b1e4391b47b62a46b84
##

**Comment by SQLfix** [comment]
any news/.? 
@Rushor  Dont work event dont start
@Demonid  Dont work some time spawn dont stop with this code too

**Comment by Adonai** [comment]
Maybe the real problem is in
`void Reset() override
            {
                _events.Reset();
                _events.ScheduleEvent(EVENT_GLUTTONOUS_ABOMINATION_SUMMONER, 5000);
                _events.ScheduleEvent(EVENT_SUPPRESSER_SUMMONER, 10000);
                _events.ScheduleEvent(EVENT_BLISTERING_ZOMBIE_SUMMONER, 15000);
                _events.ScheduleEvent(EVENT_RISEN_ARCHMAGE_SUMMONER, 20000);
                _events.ScheduleEvent(EVENT_BLAZING_SKELETON_SUMMONER, 30000);
                me->SetReactState(REACT_PASSIVE);
            }`

?

**Comment by Nikectory** [comment]
Confirmed 

https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by Keader** [comment]
@Nikectory  try https://github.com/TrinityCore/TrinityCore/issues/11265#issuecomment-47885363, work realy fine for me

**Comment by Aokromes** [comment]
If anything here is valid, plz open a pr for it.

**Comment by Rushor** [comment]
note: the fix from https://github.com/TrinityCore/TrinityCore/issues/11265#issuecomment-47885363 will cause some infight bugs after the encounter was cleared

**Comment by Keader** [comment]
In clean TC, i cant reproduce it anymore
still valid?

**Comment by Killyana** [comment]
I cannot reproduce it on rev. 684a5fd3f189
