### ISSUE TITLE
Boss Kalecgos in SWP

### ISSUE THREAD

**Issue by jobbais** [TrinityCore/TrinityCore#11276]
revision: 3b8d38d3eae622748b73293ed1602cb844edf4b5
database: TDB 52.
Addons: None

This is/might be a duplicate bug report i was not able to make anything out of other bug reports, so i took the time to test this boss once more and to make a better bug report.

here it is:

Npc: Kalecgos
WowheadID: 24850
Problem: Portals don't spawn. So unable to verify if Sathrovar work properly in the other phase. In addition the boss goes immune at 1% instead of a despawn of the boss. By kalecgos another problem occurs. With him being immune, you wont be able to kill him. This means you're stuck in combat and the area is locked down.
How to reproduce: Without the other phase working in which you need to kill the adds, you're unable to kill Kalecgos. 
How it should work: During the encounter the group takes portals to go to a different phase to kill "Sathrovar" before the boss reaches 1%. After that kalecgos is killable. IF the group fails and gets the boss at 1% Kalecgos should despawn instead of go completely immune. so the raidgroup is out of combat and able to re-enter the instance. 

Other relevant information:  He is also immune to gm spells!  :cry: Even after removing the immune aura.

**Comment by sirikfoll** [comment]
The portals don't spawn with `type=1`, but works fine if changed to 0.
```sql
UPDATE `spell_linked_spell` SET `type`=0 WHERE `spell_trigger`=44869 AND `spell_effect`=44866 AND `type`=1;
```
When enter the portal, Sathrovarr is friendly, this will make him become hostile.
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=46021 AND `spell_effect`=44852;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES 
(46021,44852,0,'Transported to the spectral realm turn Sathrovarr Hostile');
```

**Comment by Killyana** [comment]
Nice catch.
