### ISSUE TITLE
[3.3.5a]Shambling Horror Lich King

### ISSUE THREAD

**Issue by Theveloper** [TrinityCore/TrinityCore#11284]
Hi guys i tested shambling horror in icecrown citadel. when lich king spawn him an offtank must taunt him. The problem is the taunt icon appear at his buffs but the creature doesn't go to that offtank.

Rev: https://github.com/TrinityCore/TrinityCore/commit/a868ee1b46918bbd52340b0d0d566dc27a107697
##

**Comment by sirikfoll** [comment]
I don't this this is valid, at least not anymore
