### ISSUE TITLE
Temp. bans on account don't wear off.

### ISSUE THREAD

**Issue by jobbais** [TrinityCore/TrinityCore#11305]
rev: 8920994045d2774e3b76c003adb01e35f779392a
database: TDB 52

problem: When you ban a player for example 3 days by command .ban account <accountname> 3d testing

after the 3 day ban, the ban does not wear off but continues in a negative value.

when you check ingame the account with .pinfo
you get to see something like this.
Banned: (Type: None, Reason: testing, Time: 213503982334599d11h38m41s, By: rubberenrobbie)

and the account stays banned then, you must then do .unban account <accountname> to unban the account
##

**Comment by Killyana** [comment]
Cannot reproduce any issue on rev. 4bd2d28119
