### ISSUE TITLE
[335] Freezing Circle Spell doesn't work

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#11312]
Core: https://github.com/TrinityCore/TrinityCore/commit/4ca63412c85c55c6174a360b9e12840ab5edc9dc

Database - Last TDB 335

Commit: Learn Freezing Circle Spell http://www.wowhead.com/spell=34787
Try use it - nothing happend
This Spell needs for Bloodscale Enchantress http://www.wowhead.com/npc=18088
##

**Comment by Killyana** [comment]
The spell 34787 summon the NPCtrigger=20061, this npc cast these spells when he change orientation:
http://www.wowhead.com/spell=34779/freezing-circle
http://www.wowhead.com/spell=34740
http://www.wowhead.com/spell=34746

**Comment by Killyana** [comment]
@Keader I need a spell_script on effect_2 of 34779 to scale the basepoint according to the level of the npc and maybe the dungeon difficulty.

According to wowhead comments: 64 level npc will cause 2k damage point: 2k/64=31.25
https://www.wowhead.com/spell=34779/freezing-circle#comments:id=202613

It's used also by https://www.wowhead.com/npc=36842/wrathbone-coldwraith#abilities
In 3.3.5 sniffs (Pit of Saron heroic)  I get Damage: 10625 and Damage: 10518 (without any resistance or absorb)    :  10625/80=132.8125

**Comment by Killyana** [comment]
Masterv version 
``` diff
enum FreezingCircleMisc
{
    SPELL_FREEZING_CIRCLE_PIT_OF_SARON_NORMAL = 69574,
    SPELL_FREEZING_CIRCLE_PIT_OF_SARON_HEROIC = 70276,
    SPELL_FREEZING_CIRCLE                     = 34787,
    SPELL_FREEZING_CIRCLE_MOP                 = 141383,
    MOP_MAPID                                 = 1130
};

class spell_freezing_circle : public SpellScript
{
    PrepareSpellScript(spell_freezing_circle);

    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return ValidateSpellInfo(
            {
                SPELL_FREEZING_CIRCLE_PIT_OF_SARON_NORMAL,
                SPELL_FREEZING_CIRCLE_PIT_OF_SARON_HEROIC,
                SPELL_FREEZING_CIRCLE,
                SPELL_FREEZING_CIRCLE_MOP
            });
    }

    void HandleDamage(SpellEffIndex /*effIndex*/)
    {
        Unit* caster = GetCaster();
        uint32 spellId = 0;
        Map* map = caster->GetMap();

        if (map->IsDungeon())
            spellId = map->IsHeroic() ? SPELL_FREEZING_CIRCLE_PIT_OF_SARON_HEROIC : SPELL_FREEZING_CIRCLE_PIT_OF_SARON_NORMAL;
        else
            spellId = map->GetId() == MOP_MAPID ? SPELL_FREEZING_CIRCLE_MOP : SPELL_FREEZING_CIRCLE;

        if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId))
            SetHitDamage(spellInfo->Effects[EFFECT_0].CalcValue());
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_freezing_circle::HandleDamage, EFFECT_1, SPELL_EFFECT_SCHOOL_DAMAGE);
    }
};

**Comment by Keader** [comment]
About https://github.com/TrinityCore/TrinityCore/issues/11312#issuecomment-468949598
Some master dev, check 141383 in spellwork. Idk how master handle with HEROIC_CENARIO stuff

**Comment by Shauren** [comment]
It doesn't matter. Spell system will handle it by itself, script above is fine
