### ISSUE TITLE
[4.3.4] Object rope ladder 203152 bug

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#11324]
https://github.com/TrinityCore/TrinityCore/commit/f7aedaef3303b38d2e54faaad6ff80b66aaea074

Object rope ladder 203152 bug
when click on this object and other like this object u must tp in ship
but dont work 
##

**Comment by Killyana** [comment]
Works correctly on https://gitlab.com/trinitycore/TrinityCore_434/commit/61038943f8d7642d6d8b89cea56741c57efc6f95
