### ISSUE TITLE
Dreaming Glory BUFF

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#11328]
https://github.com/TrinityCore/TrinityCore/commit/e5f7beecf5fabefa13fbe2645cc7d7ca707e46e8

when herb Dreaming Glory obj:181271  u must buffed spell:28694
but bug
http://www.wowhead.com/object=181271#comments
##

**Comment by Killyana** [comment]
The object 181272 must be spawned in the same position as all 181271, actually there's only 41 spawned so 253 are missing. I will try to this.

**Comment by RedSonja** [comment]
I am getting this error and wondering if anyone has any ideas as to why? I cannot find a faction in GameObject at all for type 6.

2018-12-01_13:06:56 ERROR [entities] GameObject (template id: 181272) has invalid faction (faction template id) #0
