### ISSUE TITLE
[4.3.4] Creature Reputation BUG

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#11346]
when KIll a Creature u give +1000 REP .when rep Rate is 1x
https://github.com/TrinityCore/TrinityCore/commit/52a5213e462b754079475bad1f4d4edb22b04a2a
I search for problem
i see in creature_onkill_reward in tab rewardonkillfaction1 - rewardonkillfaction2 if value is 1378 when kill creature u give 1378 Rep of faction
dont give rewardonkillvalue1 - rewardonkillvalue2 .

with kill 4-5 npc u give exalted :D

(please chek and help)
sry for bad englsih 
More info
http://forums.arkania.net/threads/creature-reptation-bug.9359/
##

**Comment by Aokromes** [comment]
#11322
