### ISSUE TITLE
[4.3.4] Quest: Ways of the Light

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#11366]
Rev: 52a5213
DB: TDB Full 4.3.4 v5 + updates

Quest: http://www.wowhead.com/quest=10069
RequiredNpcOrGo1: http://www.wowhead.com/npc=44175 x1
RequiredNpcOrGo2: http://www.wowhead.com/npc=44420 x1
Objectives: Learn Judgement and Seal of Righteousness from Jesthenis Sunstriker. Cast Seal of Righteousness on yourself, then locate a Training Dummy outside the Sunspire and use Judgement.

Problem1: Training Dummy already has npc_training_dummy ScriptedAI which override any other AI (I'm talking about - spellhit event cant be checked by smart_scripts).
Problem2: Player should learn Judgement spell (20271), but cant find any solution - how to check when player learn spell from trainer and have quest accepted (CONDITION_SOURCE_TYPE_QUEST_ACCEPT - checks just after accept)?

**Comment by killradio** [comment]
@MENZ411 this should be used by __any__ training dummy, cuz with ur smartai script they just become normal monsters, which can be killed by players.

**Comment by MENZ411** [comment]
@killradio they should be killed by players 
```
(@NPC_TRAINING, 0, 0, 0, 6, 0, 100, 0, 0, 0, 0, 0, 41, 1000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Training Dummy - On Death - Force Despawn'),
(@NPC_TRAINING, 0, 1, 0, 36, 0, 100, 0, 0, 0, 0, 0, 70, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Training Dummy - On Despawn - Respawn'),
```

**Comment by emptyus** [comment]
Yes, they die and despawn right after death than quickly respawn.

**Comment by killradio** [comment]
@MENZ411 in ur dreams mb they should, but here - in real world - they should act like training dummys, not mobs. Have fun with videos: http://www.youtube.com/results?search_query=Quest+Ways+of+the+Light

**Comment by MENZ411** [comment]
@killradio http://youtu.be/Nnz1ZRc86Dk

**Comment by Aokromes** [comment]
Indeed, the lvl 3 training dummies can die and instant respawn.

**Comment by Rushor** [comment]
and that was even with 4.3.4 like that?

**Comment by MENZ411** [comment]
yes, cata, mop, wod

**Comment by killradio** [comment]
@MENZ411 u create human in wod to check be's quest from cata? :+1:  
http://www.youtube.com/watch?v=RqQ1PB3P0gQ
http://www.youtube.com/watch?v=iSyBFckw4oU

**Comment by emptyus** [comment]
Those videos prove nothing... Those starting dummies die quick and die regardless of if you r on a class quest or not. These videos you linked dont pay attention to dummy (1st one doesnt bring dummy to 1hp at all, the 2nd one just makes it 1hp and moves on not waiting to see if it dies/despawns/respawns...), where MENZ411's video shows nicely how it should and does behave on retail.

**Comment by killradio** [comment]
@emptyus hi there! Watch videos again plz and u will see difference between __despawning__ mob and training dummy left with 1 hp without dying etc. if u will "pay attention to dummy" instead video's author. Once again http://www.youtube.com/watch?v=RqQ1PB3P0gQ#t=20s with __wod__ mechanic guy at the left can hit it like this. But video http://www.youtube.com/watch?v=iSyBFckw4oU has full hd quality (hope ur eyes can handle this) and if u watch it with "pay attention to dummy" u will see, that dummy's frame not disappearing as mob itself. So... ur comment has no sense.
P.S. Ofc his video shows how it works on retail now with absolutely different quest and game version LOL ... u stupid.

**Comment by killradio** [comment]
BTW happy birthday issue!

**Comment by killradio** [comment]
BTW happy birthday issue!

**Comment by emptyus** [comment]
Both videos prove nothing, and the reason for that, is they dont focus the dummy long enough. At retail there is an delay for death of an unit, when it reaches 1hp some time takes for it to die. In this manner, I think we didnt saw enough of focus on dummy so we can say it wont die or desapear. I mean, idk why you argue so hard with video, when you can check this easly by going on live servers? If this was 4.3.4. video, than argue would be good, thisway- waste of time.

**Comment by Aokromes** [comment]
You missed this part: https://github.com/TrinityCore/TrinityCore/issues/11366#issuecomment-69744167

**Comment by killradio** [comment]
All this videos prove nothing, cuz they created in versions > 4.3.4. In this manner we have nothing to prove except online retail server with version 4.3.4 and be paladin. So, all this issue is waste time - no one cant prove how it should work.

> I mean, idk why you argue so hard with video, when you can check this easly by going on live servers?

ok, boss!
> If this was 4.3.4. video, than argue would be good, thisway- waste of time.

Wait a sec. Video from 6.x is ok for u and prove everything?

**Comment by MENZ411** [comment]
cata Training Dummy mechanic = mop and wod Training Dummy mechanic

i play on the official server
