### ISSUE TITLE
Mob AI

### ISSUE THREAD

**Issue by miraco** [TrinityCore/TrinityCore#11371]
Normal: NPCs who get pulled LoS and be "Caster-NPCs" should switch in Range Mode when they are in LoS to cast. 
Bug: When they are LoS to Cast they cast and always try to run in Melee Range.

Normal: When you have a Caster or a Hunter NPC they should always Check if they can go in Melee or in Range Mode. 
Bug: When they where one time in Melee Range they always be in melee Range.

Normal: When you have a Caster or a Hunter NPC and they cast Spells like Trap, Scatter or Entagle on the Tank they should try to run in Range mode. (Example Lady Vashj p1+3 when getting entagled)
Bug: They use the spell and stand in melee range.

A video for this:
http://www.youtube.com/watch?v=gXn7HRgYe1c
1. LoS Pulling: 0:28-1:03
2. Ranged and Melee Switching: 1:04-1:50
   3.Scatter and Run, Trap and Run.  3:44-4.40

DB: TDB_full_335.52_2013_07_17 + updates
Core (335a) Rev: 6304c8d

Sorry, i am german and my english is bad.
##

**Comment by Killyana** [comment]
This is not an issue but the result of bad scripts.
