### ISSUE TITLE
Morogrim Tidewalker

### ISSUE THREAD

**Issue by miraco** [TrinityCore/TrinityCore#11388]
DB: TDB_full_335.52_2013_07_17 + updates
Core (335a) Rev: 6304c8d
Script: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_morogrim_tidewalker.cpp

Boss Morogrimm in Coilfang Resevoir, in Phase 1 when you get into the Water globules you should explode after 5seconds.

**Comment by Killyana** [comment]
You're talking about "Watery Grave" and  not The Water Globule, anyway for all http://wotlk.openwow.com/?search=Watery+Grave#spells the explosion is triggred when the aura is removed and it works correctly for all spells, same for Water Globules when they touch the player they explode deal damage and freez the player.
