### ISSUE TITLE
4.3.4 Shaman Quest 14011, 25143, 26969, 27027 - Primal Strike Not being recognised when cast

### ISSUE THREAD

**Issue by biocatalyst** [TrinityCore/TrinityCore#11407]
A bug or issue has occurred when in gameplay as a Shaman on the 4.3.4 build. The Quest named Primal Strike at the beginning of the game requires the Shaman to practice their spell named Primal Strike on a practice dummy.

The problem is that practice is not counted within the quest.

I have only tested on Draenai race at the moment, so am unaware if the issue exists on the other races.

If more information is required, please let me know.

Core Revision: 52a5213e462b754079475bad1f4d4edb22b04a2a
Database: TDB 4.3.4 5
Modifications: None - Stock Standard Build

**Comment by Rushor** [comment]
moved to the todolist from https://github.com/TrinityCore/TrinityCore/issues/15814
