### ISSUE TITLE
[4.3.4] Quest: Do the Right Thing

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#11410]
Rev: 52a5213
DB: TDB Full 4.3.4 v5 + updates

Quest: http://www.wowhead.com/quest=28189
RequiredNpcOrGo1: http://www.wowhead.com/npc=47872 x15
SourceItemId: http://www.wowhead.com/item=63150
Objectives: "Save" 15 Human Seedlings.

Video: http://www.youtube.com/watch?v=G3pTZ7NGDRs

According to this: http://www.wowhead.com/quest=28189#comments:id=1202825 you have to do ~6 quests before take this quest.

Problem0: You cant take quest, cant iteract with questgiver, cuz GO(questgiver) has flags = GO_FLAG_INTERACT_COND (Untargetable, cannot interact). + Quest flags should also be changed, imo (QUEST_FLAGS_AUTOCOMPLETE - is for quests like this one?).
Problem1: NPCs fall under ground just after added to world.
Problem2: Quest item + rewarded item (http://www.wowhead.com/item=65667) spell:89089 kill everything, not only npc:47872.
Problem3: Human Seedling npc:47872 should be spellclick (npcflag = 16777216) -> spellclick not scripted (part with this can be found on video).
Problem4: After completing all objectives should appear special button (on video) in quest tracker, which give you possibility to complete and chose reward - NYI?

Misc: Is it just me or.. when start to cast Shovel, animation breaks approxx at the middle. From SpellWork - CastingTime (Id 3) = 0.50 - seems like animation lasts a bit longer?
##

**Comment by KarrokDC** [comment]
In TrinityCore rev. 52758c1a0b8e 2016-02-12 20:40:43 using the shovel in this quest instantly killed me.

**Comment by Aokromes** [comment]
very likely conditions are needed here no @Killyana ?

**Comment by Killyana** [comment]
Quest chaining required.

**Comment by Killyana** [comment]
General issue for cata+ quests
