### ISSUE TITLE
[4.3.4] Fix Vengeance

### ISSUE THREAD

**Issue by carlos93** [TrinityCore/TrinityCore#11496]
Dont know how to do a pull request -.-, so i place the commit here. 
https://github.com/carlos93/TrinityCore/commit/ebeaa20a1dfe31a6853d09d8b26941d0169a79d4

Without the Ability Power fix (https://github.com/TrinityCore/TrinityCore/pull/9922) (http://paste2.org/cpCWd0I1) the Vengeance buff won't increase AP but still works. Sorry for my bad english.

Thank you

**Comment by DDuarte** [comment]
404s on the commits :/

**Comment by tkrokli** [comment]
Maybe that is because @carlos93 have no public repositories. Anyway, he needs to update this issue.

**Comment by Shauren** [comment]
Vengeance mechanic was removed in 6.0

**Comment by tkrokli** [comment]
Might as well just close this issue for good then, since 4.3.4 is archived and no longer supported.

**Comment by DDuarte** [comment]
Yes, it's already closed.
