### ISSUE TITLE
Lunar Festival - Greater Moonlight Bug

### ISSUE THREAD

**Issue by Zeenjayli** [TrinityCore/TrinityCore#11518]
TrinityCore rev. 0b3ae6730d61+ 2014-01-27 07:48:17 +0100 (master branch) (Unix, Release)
TDB 335.52

Lunar Festival - Greater Moonlight
The Greater Moonlight (I'll assume in every town, but at least in Orgrimmar), does not accept  Lunar Festival Invitation (http://www.wowhead.com/item=21711/lunar-festival-invitation), It's suppose to teleport you to, Moonglade upon right click when standing in the Greater Moonlight (http://www.wowhead.com/spell=26373) But says your not standing in it also the moonlight is pulsing in a weird manner and making some odd sound that I think should only be made when you first walk up to it's visual range
![screenshot_5](https://f.cloud.github.com/assets/1750708/2005797/4bf50c82-86fb-11e3-8a2b-dc0baa1677fb.png)
![screenshot_6](https://f.cloud.github.com/assets/1750708/2005800/640c9ec0-86fb-11e3-9053-c0e28c14b9ea.png)
![screenshot_7](https://f.cloud.github.com/assets/1750708/2005803/7f247250-86fb-11e3-859d-3393ac38bc1a.png)

Also When using the Cluster Launchers in Moonglade to summon Omen only his minions spawn

(http://www.wowhead.com/npc=15467)

Manually Spawned Omen .npc add 15467
upon killing him you receive Elunes Blessing Correctly for quest Elunes Blessing(http://www.wowhead.com/quest=8868)
##

**Comment by Killyana** [comment]
This spells ( Teleport Units ) must be added to `spell_target_position`
http://wotlk.openwow.com/?search=Lunar+teleport

**Comment by Killyana** [comment]
Still same work must be done:
``` sql
DELETE FROM `spell_target_position` WHERE `ID` IN (26450, 26452, 26453, 26454, 26455, 26456);
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES
(26450, 0, 1, 10150.1, 2602, 1330.83, 4.80894, 0),
(26452, 0, 0, -4663, -955.663, 500.377, 0.722862, 0),
(26453, 0, 1, 1982.9, -4255.62, 31.6692, 3.31984, 0),
(26454, 0, 0, -8748.48, 1073.61, 90.4898, 5.03789, 0),
(26455, 0, 1, -1031.45, -230.867, 160.14, 3.28358, 0),
(26456, 0, 0, 1642.01, 239.002, 62.5918, 3.02316, 0);

**Comment by Kittnz** [comment]
When you use the invitation scroll to teleport to moonglade the 3 lunar festival guys around the spotlight cast a spell or some sort. Seems these druids may activate (have it sniffed but didn't look at it yet) the spell of teleportation.

**Comment by Killyana** [comment]
I can't understand how this spells are supposed to be used (26450, 26452, 26453, 26454, 26455, 26456)

**Comment by Kittnz** [comment]
@Killyana iv got a sniff for the dalaran one, irc :)

**Comment by Killyana** [comment]
For Dalaran there's no return spell

**Comment by offl** [comment]
https://github.com/cmangos/tbc-db/commit/9e50619a88b17f35799e5af10c20bca462db55d1
