### ISSUE TITLE
Instance lock reset incorrectly show if reset under 1h

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#11519]
For example:

Your instance lock for Utgarde Pinnacle (5 Player (Heroic)) will expire in 0 hours.

Your instance lock for Utgarde Pinnacle (5 Player (Heroic)) will expire in 0 minutes.

Valid on al TrinityCore revisions up to 96ae4caf6258.

**Comment by jackpoz** [comment]
what's the current behavior when the reset warning is sent to players inside the instance ? is it always "0 minutes" even if there are hours left ?

**Comment by jackpoz** [comment]
caused by https://github.com/TrinityCore/TrinityCore/commit/4193806dba4de81f0e24c94bc470faaaa0e717cf#diff-7e351c764288e7846cfacbd21d141c95R587
