### ISSUE TITLE
death grip bug

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#11531]
https://github.com/TrinityCore/TrinityCore/commit/1b48c7b977b19f990b7f1389f48a0a45cdde9784

death grip causes the target to suddenly appear near the death knight rather than being able to see the person being gripped to you
(however this is only a visual bug that occurs to everyone except the death knight and the target)

**Comment by Killyana** [comment]
This issue is still valid?

**Comment by Raydor** [comment]
Confirmed, also happens with charge and fear has a similar visual bug.

**Comment by Demonid** [comment]
@Killyana Confirmed on 1161295f4f933661ea9738e0c57049a1e38ec8f2

**Comment by Frytiks** [comment]
Raydor, true.

**Comment by tkrokli** [comment]
A variant of this issue is slightly mentioned in  [**Deathgrip ("Missle Speed")**](https://github.com/TrinityCore/TrinityCore/issues/565) #565 :
`... and often times disappear briefly before reaching final destination.`

**Comment by Killyana** [comment]
Cannot reproduce on rev. b274c4b5c346
