### ISSUE TITLE
[3.3.5][6.x] Spell Catapult IoC

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#11543]
https://github.com/TrinityCore/TrinityCore/commit/68d48ecbd1654fc2f1311e966c41654d265f368b
Spell launch 66218 Dont work
Catapult spell
when click on spell Throws player to select location next come back to cataput and need to again enter vehicle
##

**Comment by Aokromes** [comment]
still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
