### ISSUE TITLE
[NPC] Freya

### ISSUE THREAD

**Issue by Fateswhisper** [TrinityCore/TrinityCore#11550]
After the death of Freya in Hard Mode, all creatures (and other boss) in the dungeon get buff from ancient:
http://www.wowhead.com/spell=62385
http://www.wowhead.com/spell=65586
rev: https://github.com/TrinityCore/TrinityCore/commit/8f29fb9aee3ab53efa59502c02c739ab435e2610

**Comment by Killyana** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/9942
