### ISSUE TITLE
Spell visuals shouldn't fade with corpse

### ISSUE THREAD

**Issue by NorthStrider** [TrinityCore/TrinityCore#11606]
Usually if a npc despawns the aura shouldn't fade out with the body. the aura should fade out like if it is expired.
It's more an visual flaw than an mechanic problem. I guess the remove type is handled wrong somewhere.

so: at the moment: npc despawns with aura at the same time

as it should be: npc dies and the aura should expire with the correct fade out effect.

rev.: b72273014f2f290f9524a3f9b1596528773da9fb

**Comment by Killyana** [comment]
Almost the same issue: https://github.com/TrinityCore/TrinityCore/issues/13137
