### ISSUE TITLE
Sindragosa possible bug

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#11615]
I'll try to explain the problem. I'm not sure if it's a bug of the official wow or only from trinitycore.
Start to fight with Sindragosa. When Sindragosa flies and throw the ice tomb, freeze all the raid. Then when Sindragosa lands, all the ice tombs dissapear like a failed try but Sindragosa takes 2 or 3 second to restore its life so the tank can hit again and the raid can continue.

commit 96c50c424c8ff1152f548199f4d9ec683f525f75

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6991
