### ISSUE TITLE
Boss kill credit.

### ISSUE THREAD

**Issue by Sqruel** [TrinityCore/TrinityCore#11638]
Sorry if I doubled an issue but searching for: "boss kill credit", "kill credit", "loot credit" didn't find anything related to the issue I would want to report.

Rev: not an old one, e.g. latest (21.02.2014) one. 

Issue: It started to happen not so long ago but it's quite annoying, what I'm saying is that people who die on Lich King while beeing dropped from the edge by Val'kyrs don't get the Achivement nor the Loot at all. I'm aware that it's an issue related instance wide not only to Lich King encounter but such situations happen at Lich King most often. Ofc it can happen somewhere else e.g. Malygos encounter - you die, you fall down, you are to far, you don't get the Kill Credit for the Boss. Same thing when you get dc/relog and get back into game while the fight is still on, naturally you'll be ported to the Starting Location but again you won't get the Kill Credit/Loot/Achivement. If somone could look into this ASAP it would be very appreciated.

**Comment by Aokromes** [comment]
#7075
