### ISSUE TITLE
Aura Stuck

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#11644]
By simultaneously pressing two used trinkets and replacing them with other trinkets, buff them not disappear. In the original buff from the thing that is not on the character should not be (buff should disappear in a moment of change trinket).

4k+ spd and unreal DPS.

http://4put.ru/pictures/max/862/2648718.jpg <- 2 trinkets (use)
http://4put.ru/pictures/max/862/2648722.jpg <- change trinket and 4 auras.

/use Maghia's Misguided Quill
/equipslot 14 Charred Twilight Scale

/use Talisman of Resurgence
/equipslot 13 Phylactery of the Nameless Lich

Need skill to use 2 trinket before the fight at the together, without training can use only one of them because of GCD.

rev: https://github.com/TrinityCore/TrinityCore/commit/f7bc86a17cc0dd1c59c338539c1a7f1d7d6e5f64
##

**Comment by Frytiks** [comment]
Confirmed !

**Comment by Frytiks** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8210

**Comment by Xxxhackerxxx** [comment]
Confirmed !

**Comment by Keader** [comment]
Still Bugged on 170ba68e63c46323f8624ecff24e6de1d38bd97b

**Comment by D4R4** [comment]
as I said in my own report of the issue it is most likely due to this function not doing it's job correctly: Player::ApplyEquipSpell()

part of it's job is to remove auras related to items when they get unequiped

**Comment by sirikfoll** [comment]
use/change or use/unequip, by macro or manually(if pretty fast),
makes the same call on the function  `Player::ApplyEquipSpell()` but the aura gets stuck.

**Comment by Keader** [comment]
Problem occurring with trinkets "active" and "passive": https://youtu.be/vJIb3rkxCKA

**Comment by sirikfoll** [comment]
The Aura get stuck exactly in this piece of the code, this line

`for (AuraApplicationMap::iterator iter = m_appliedAuras.lower_bound(spellId); iter != m_appliedAuras.upper_bound(spellId);)` (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L3864)

isn't executed.
```cpp
void Unit::RemoveAurasDueToItemSpell(uint32 spellId, ObjectGuid castItemGuid)
{
    for (AuraApplicationMap::iterator iter = m_appliedAuras.lower_bound(spellId); iter != m_appliedAuras.upper_bound(spellId);)

**Comment by Keader** [comment]
@jackpoz Please have to check this? Quite old and 'abusable' it

**Comment by Re3os** [comment]
any news?

**Comment by L30m4nc3r** [comment]
``` 
void WorldSession::HandleEquipmentSetUse(WorldPacket& recvData)
 {
-    if (_player->IsInCombat())
-        return;
-
    TC_LOG_DEBUG("network", "CMSG_EQUIPMENT_SET_USE");
 
    for (uint32 i = 0; i < EQUIPMENT_SLOT_END; ++i)
@@ -1709,6 +1706,10 @@
         if (itemGuid == 1)
             continue;
 
+        // Only equip weapons in combat
+        if (_player->isInCombat() && i != EQUIPMENT_SLOT_MAINHAND && i != EQUIPMENT_SLOT_OFFHAND && i != EQUIPMENT_SLOT_RANGED)
+            continue;
+
        Item* item = _player->GetItemByGuid(itemGuid);

        uint16 dstpos = i | (INVENTORY_SLOT_BAG_0 << 8);
```

**Comment by Shauren** [comment]
@L30m4nc3r why are you suggesting changes that are in TC codebase for almost two years? c431f463a1f718c5c12de9e1343a5dc71e7e1280 added that.
You using some custom hidden fork that is several years old does not help anyone at all.

**Comment by L30m4nc3r** [comment]
ye sorry my code very old.
i will merge with last trinitycore in the near time.

**Comment by Keader** [comment]
@L30m4nc3r you tested your code in current TC Rev?!

**Comment by sirikfoll** [comment]
A little more info on that,
This is the order in which some key functions get called when you reproduce the bug
```
1. Player::CastItemUseSpell
2. Spell::CheckItems() (check if we have the item equipped, we still have. All ok, continue)
3. Unit::RemoveAurasDueToItemSpell (this one is responsible for removing the aura, checking for it 
 in m_appliedAuras, and will FAIL because the aura isn't registered in m_appliedAuras yet)
4. Spell::cast
5. Spell::handle_immediate
6. Spell::DoAllEffectOnTarget
7. Spell::DoSpellHitOnUnit
8. Unit::_CreateAuraApplication (here we register the aura in m_appliedAuras)
```
Basicly the core start the cast of the spell, perform the check if we have the item equipped to allow the cast,
then handle the remove of the item, tried to remove the aura, which is still in process to be added to the player, 
I have absolutely no idea on how to fix that :/

**Comment by Xxxhackerxxx** [comment]
still bugged .
