### ISSUE TITLE
DB/Quest: Proving Pit - Darkspear Jailor does not react

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#11706]
The quest Proving Pit (http://wowhead.com/quest=24762 or for any class) does not work. 
When you speak with Darkspear Jailor (http://wowhead.com/npc=39062), it does nothing. It should go at the cage where Captive Spitescale Scout (http://wowhead.com/npc=38142) is locked, unlock the cage, and the Captive Spitescale Scout needs to come out, then you need to kill him, but, you can't attack him. 

Basically, the base core, didn't changed core code.

I'm running the 4.3.4 branch of TrinityCore, rev: adc4b3b46b0d
DB: TDB 335.52, but the 4.3.4 alpha db file.
##

**Comment by davidox92** [comment]
Same problem here.

Core: e6cc39258d1b
DB: TDB 434.09

**Comment by Rushor** [comment]
http://www.trinitycore.org/f/topic/9285-npc-captive-spitescale-scout-not-attacking-on-aggro/

**Comment by Keldo** [comment]
Issues from way back in 3.3.5 and NEVER got fixed... Doesnt pay to rush large projects....

**Comment by Aokromes** [comment]
Sooo... what's your point?

**Comment by StormBytePP** [comment]
@Keldo really?
commit ac2845ee77d0f3e838267ad424fbcf4894040333
Author: StormBytePP <stormbyte@gmail.com>
Date:   Sat Aug 29 00:40:05 2015 +0200

    Core/Vehicles: Fix CanEnterOrExit by implying that if a vehicle seat have anim for enter/ride means it can be entered/exited even in cases where it lacks VEHICLE_SEAT_FLAG_CAN_ENTER_OR_EXIT flag
    
    Fixes issues #13298, #8195, #7468, #1290

**Comment by BahDumbBugs** [comment]
Bug still outstanding. Confirming.

TrinityCore rev. bc94bacce404 2016-01-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by tkrokli** [comment]
TrinityCore rev. f6637439f484 2016-06-18 16:23:55 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_17_01_world.sql`

Confirmed.
This quest is stuck at "no action performed when clicking the Darkspear Jailor's gossip option".
- http://www.wowhead.com/npc=39062/darkspear-jailor
- http://www.wowhead.com/quest=24762/proving-pit

**Comment by Keldo** [comment]
November 15, 2016, 5 months later, any new status on this issue?

**Comment by tkrokli** [comment]
Like mmorganj mentioned in #18368 , `Received not handled opcode [CMSG_CLOSE_INTERACTION [...]]` pops up in the Worldserver console when you try to do the quest. Does it affect this issue, that it needs the opcode to be handled before this quest issue can be solved (and maybe labeling this issue [Comp-Core])?

**Comment by nubqt** [comment]
I did some research on this issue and it seems there is no script in the TDB for this quest (someone else please corroborate my findings).

Furthermore, after researching this quest on wowhead, it seems the quest was added on patch 4.0.3.x which leads me to believe that the script can be accomplished by using `conditions` and `event_scripts` rather than `smart_scripts`. `conditions` provides for checking if a Player selected a particular gossip, **but I'm not sure how to 'catch' that action for `event_scripts`**. That's where I'm stuck. Once I can figure out how to catch that a Player selected that gossip, everything else can be done easily with `event_scripts` (give kill credit, tell the NPC to move to the cage, tell the NPC to say a text, open the cage, etc.)

Any other ideas or suggestions?

**Comment by tkrokli** [comment]
I don't know if you read the wiki `*_scripts` page, but I would like to mention this bit:
- https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130258/scripts
> **id**:
For **event_scripts**, it is the event ID. There doesn't exist currently a full list of events. In any case, the event IDs are taken directly from gameobject WDB data or spell effect data. If both a gameobject and a spell activate the same event, the IDs will match.
For **waypoint_scripts**, it is the [action](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130114/waypoint_data#waypoint_data-action) ID.

**Comment by BahDumbBugs** [comment]
Commit a16d320 - still outstanding.

**Comment by Aussiewoolf** [comment]
To help out i got this working with a rewrite to current master core, i will not take credit but it works for me and tested many times.
anybody would like to do a PR you are welcome to it.

`## npc_jailor
######*/

enum ejailor
{
    GO_CAGE = 201968,
    NPC_NAGA = 38142
};

float fNodeJailorPosition[2][3][3] =
{
    {
        { -1132.875366f, -5425.658203f, 13.308554f },
        { -1134.783813f, -5416.551270f, 13.269002f },
        { -1132.472046f, -5424.702637f, 13.225397f },
    },
    {
        { -1159.829956f, -5519.570313f, 12.126601f },
        { -1153.379028f, -5518.994629f, 11.996062f },
        { -1159.829956f, -5519.570313f, 12.126601f },
    },
};

float fNodeNagaPosition[2][3] =
{
    { -1146.220581f, -5417.623047f, 10.597669f },
    { -1150.114380f, -5527.809082f, 8.105021f },
};

#define GOSSIP_HELLO_PIT "I'm ready to face my challenge."

class npc_jailor : public CreatureScript
{
public: npc_jailor() : CreatureScript("npc_jailor") { }

    bool OnGossipHello(Player* pPlayer, Creature* pCreature)
    {
        if (CAST_AI(npc_jailor::npc_jailorAI, pCreature->AI())->uiStart == false)
        {
            if (pPlayer->GetQuestStatus(24774) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(26276) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24754) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24762) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24786) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24642) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24768) == QUEST_STATUS_INCOMPLETE ||
                pPlayer->GetQuestStatus(24780) == QUEST_STATUS_INCOMPLETE)
            {
                AddGossipItemFor(pPlayer, GOSSIP_ICON_CHAT, GOSSIP_HELLO_PIT, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
            }
        }

        SendGossipMenuFor(pPlayer, pPlayer->GetGossipTextId(pCreature), pCreature->GetGUID());

        return true;
    }

    bool OnGossipSelect(Player* pPlayer, Creature* pCreature, uint32 uiSender, uint32 uiAction)
    {
        pPlayer->PlayerTalkClass->ClearMenus();
        if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
        {
            uint8 Phase = 1;
            if (pCreature->GetDistance(-1143.18f, -5429.95f, 13.97f) < 20)
                Phase = 0;

            CAST_AI(npc_jailor::npc_jailorAI, pCreature->AI())->Phase = Phase;
            pCreature->Say("Get in the pit and show us your stuff, $N", LANG_UNIVERSAL);

            pPlayer->KilledMonsterCredit(pCreature->GetEntry());
            CloseGossipMenuFor(pPlayer);
        }
        return true;
    }

    CreatureAI* GetAI(Creature* pCreature) const
    {
        return new npc_jailorAI(pCreature);
    }

    /*npc_jailor*/

    struct npc_jailorAI : public ScriptedAI
    {
        npc_jailorAI(Creature* pCreature) : ScriptedAI(pCreature) {}

        uint8 Phase;
        uint8 uiNode;
        uint32 uiTimer;
        bool uiStart;

        void Reset()
        {
            GameObject* pCage = me->FindNearestGameObject(GO_CAGE, 20.0f);
            pCage->Respawn();
            pCage->SetGoState(GO_STATE_READY);
            Phase = 5;
            uiNode = 0;
            uiTimer = 2000;
            uiStart = false;
        }

        void UpdateAI(uint32 uiDiff) override
        {
            if (me->IsInCombat())
                return;

            if (Phase != 5)
            {
                uiStart = true;
                if (uiTimer <= uiDiff)
                {
                    GoToTheNextNode();
                    uiTimer = 2500;
                    switch (uiNode)
                    {
                    case 1:
                        uiTimer = 5000;
                        uiNode++;
                        break;
                    case 3:
                        uiTimer = 120000;
                        uiNode++;
                        break;
                    case 4:
                        if (Creature* pNaga = me->FindNearestCreature(NPC_NAGA, 30.0f))
                        {
                            pNaga->SetReactState(REACT_PASSIVE);
                            pNaga->setFaction(634);
                            pNaga->GetMotionMaster()->MoveTargetedHome();
                        }
                        uiTimer = 4000;
                        uiNode++;
                        break;
                    case 5:
                        if (GameObject*pCage = me->FindNearestGameObject(GO_CAGE, 30.0f))
                        {
                            pCage->Respawn();
                            pCage->SetGoState(GO_STATE_READY);
                        }
                        uiNode = 0;
                        Phase = 5;
                        uiStart = false;
                        uiTimer = 2000;
                    default:
                        uiNode++;
                        break;
                    }
                }
                else
                    uiTimer -= uiDiff;
            }
        }

        void GoToTheNextNode()
        {
            if (uiNode >= 3)
                me->GetMotionMaster()->MoveTargetedHome();
            else
                me->GetMotionMaster()->MoveCharge(fNodeJailorPosition[Phase][uiNode][0], fNodeJailorPosition[Phase][uiNode][1], fNodeJailorPosition[Phase][uiNode][2], 5);
        }

        void MovementInform(uint32 uiType, uint32 uiPointId)
        {
            if (uiType != POINT_MOTION_TYPE)
                return;

            if (uiNode == 2)
            {
                if (GameObject*pCage = me->FindNearestGameObject(GO_CAGE, 15.0f))
                {
                    pCage->SetGoType(GAMEOBJECT_TYPE_BUTTON);
                    pCage->UseDoorOrButton();
                }
                if (Creature* pNaga = me->FindNearestCreature(NPC_NAGA, 15.0f))
                {
                    pNaga->SetReactState(REACT_AGGRESSIVE);
                    pNaga->setFaction(14);
                    pNaga->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NOT_ATTACKABLE_1 | UNIT_FLAG_NON_ATTACKABLE);
                    pNaga->Say("They sssend you to your death, youngling.", LANG_UNIVERSAL, NULL);
                    pNaga->GetMotionMaster()->MoveCharge(fNodeNagaPosition[Phase][0], fNodeNagaPosition[Phase][1], fNodeNagaPosition[Phase][2], 5);
                }
            }
        }
    };
};`

Just remember to add to the bottom 
new npc_jailor();

**Comment by tkrokli** [comment]
To anyone who wants to use the above script sample as basis for a PR to solve this issue, please remember to use DB gossip instead of hardcoded text by keeping the `#define` text (deprecated).

**Comment by offl** [comment]
#23838
