### ISSUE TITLE
[ Quest ]  Protect Kanati Greycloud

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11728]
It starts the quest but doesn't add npc's for the quest to protect him from

http://wotlk.openwow.com/quest=4966

Core 6c64fa8

TDB 335.52 + updates

**Comment by Aokromes** [comment]
This is valid? Or it needs c++ to remove flags?

**Comment by Rushor** [comment]
c++ is better in this case i think, it's only a flag, pr inc.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/7501
