### ISSUE TITLE
Elemental Slave 

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11742]
in the Darlaran Crater / Alterac Mountains
Elemental Slave  spams in world / chat saying Elemental Stave  is reduced to rubble, but still continues to fight and Elemental Stave  begins to crack and break apart.

http://wotlk.openwow.com/npc=2359

Core 6c64fa8

patch Ahbot

TDB 335.52 + updates

**Comment by Killyana** [comment]
The exclusive group must be pushed:
``` sql
DELETE FROM `spell_group` WHERE `id`=1121;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1121,3671),
(1121,3672),
(1121,3673);

DELETE FROM `spell_group_stack_rules` WHERE `group_id`=1121;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES
(1121,1);
