### ISSUE TITLE
[3.3.5] DB/Gameobject - Mining nods - Missing Pooling (5$ bounty)

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11743]
In Ghostlands,around  tranquillen town area most of the mining nods have 2 plus mods on each other like copper tine and iron in the one spot 

Core 6c64fa8

patch Ahbot

TDB 335.52 + updates
##

**Comment by DDuarte** [comment]
A bounty of 5$ has been posted by velinath on https://www.bountysource.com/issues/1617667-mining-nods.

**Comment by mvelasco93** [comment]
Can i have the GUID of those tines? Pool is needed

**Comment by Killyana** [comment]
Pooling is missing.
example:
75045 (Entry: 1731) - [Copper Vein X:7084.870117 Y:-7166.419922 Z:51.452499 MapId:530] 
75046 (Entry: 1732) - [Tin Vein        X:7084.870117 Y:-7166.419922 Z:51.452499 MapId:530] 
75047 (Entry: 1733) - [Silver Vein    X:7084.870117 Y:-7166.419922 Z:51.452499 MapId:530] 

To fix this you have to find the original commit that added this spawns.

**Comment by tkrokli** [comment]
@mvelasco93 : I think you can find the GUIDs in the DB, unless I have misunderstood what you are looking for. I am guessing that this depends on if you are looking for the static GUIDs used on creation of the default nodes or if you need the GUIDs created when new nodes spawn after some of the default nodes have been mined. Try using this query on the `world` database (I have only tested this on TDB335.60) :
```sql
SELECT * FROM `pool_gameobject` WHERE `description` LIKE '%Tin%';
```
While I can't guarantee that this is the result or solution you are looking for, it looks like this:
```
  guid  pool_entry  chance  description
------  ----------  ------  ---------------------------
 68602        3200      15  Spawn Point 1 - Tin
 68608        3201      15  Spawn Point 2 - Tin
 68614        3202      15  Spawn Point 3 - Tin
 68620        3203      15  Spawn Point 4 - Tin
 68626        3204      15  Spawn Point 5 - Tin
 68632        3205      15  Spawn Point 6 - Tin
 68638        3206      15  Spawn Point 7 - Tin
 68644        3207      15  Spawn Point 8 - Tin
 68650        3208      15  Spawn Point 9 - Tin
 68656        3209      15  Spawn Point 10 - Tin
 68662        3200      15  Spawn Point 11 - Tin
 68668        3211      15  Spawn Point 12 - Tin
 .
 .
 .
```
Not sure about this, but perhaps you could look in the `pool_pool` table and see if there is any useful information, filtered by this query:
```sql
SELECT * FROM `pool_pool` WHERE `description` LIKE '%Spawn Point%';

**Comment by mvelasco93** [comment]
I currently use a reordered BD so the guids won´t be the same

https://github.com/mvelasco93/pool_gen

I currently use that to create pools. It have some bugs but it can be useful.

**Comment by offl** [comment]
Hello, I too use a different DB, but if objects are spawned in this diapason, my fix is correct.
SELECT * FROM `gameobject` WHERE `guid` BETWEEN 75000 AND 75119;

I made it without pool_pool(guess that it is not needed here).

http://pastebin.com/7d0epZHT

**Comment by offl** [comment]
Yes, I checked currect TC guids(TDB60 without changes) and guess this can be pushed :)
