### ISSUE TITLE
[3.3.5] [Quest]  The Right Piece of Lord Valthalak's Amulet

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#11752]
TrinityCore rev. 014040b66214 2014-03-17 15:02:58 -0400 (master branch)

http://www.wowhead.com/quest=8989/the-right-piece-of-lord-valthalaks-amulet
16044 Mor Grayhoof Trigger
16080 Mor Grayhoof
16083 Mor Grayhoof Transformaion Visual

Use the Brazier of Beckoning to summon forth the spirit of Mor Grayhoof and slay him. Return to Bodley inside Blackrock Mountain with the recombined Lord Valthalak's Amulet and the Brazier of Beckoning

You place the Brazier of Beckoning and nothing happens
##

**Comment by Jinnaix** [comment]
Can be closed, works at fb227be9eb53581863a45002a3878566b3c1e22c

![image](https://user-images.githubusercontent.com/37972361/91426517-ea137380-e85c-11ea-9c92-953fa5c95580.png)

![image](https://user-images.githubusercontent.com/37972361/91426561-f697cc00-e85c-11ea-9b08-d41595b5044a.png)
