### ISSUE TITLE
[3.3.5][NPC/Vehicle] Freed Proto Drake

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#11754]
This NPC/vehicle Freed Proto Drake: http://www.wowhead.com/npc=29709
summoned from this spell: Summon Freed Proto Drake www.wowhead.com/spell=55028
from this quest: Cold Hearted http://www.wowhead.com/quest=12856

- should not be allowed to fly over to places like Dalaran
- should not be allowed to cast his icy spell(Ice Shard http://www.wowhead.com/spell=55046) on other players 
- and should not be allowed to fly INDOOR like the two Dalaran Banks or the Underbelly

I used added the spell to Disables in Dalaran Area, pure hack, other than that no idea how to fix this,

Core Rev: 5221bd8c1099+
DB Rev: TDB_full_335.52
##

**Comment by Killyana** [comment]
The cpp script brooks some mechanisms for vehicles (like the SAI) this conditions are working only if the script is removed.
``` sql
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId`=16 AND `SourceEntry`=29709);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(16,0,29709,0,0,23,0,4422,0,0,0,0,'','Dismount player when not in intended zone'),
(16,0,29709,0,1,23,0,4535,0,0,0,0,'','Dismount player when not in intended zone'),
(16,0,29709,0,2,23,0,4437,0,0,0,0,'','Dismount player when not in intended zone'),
(16,0,29709,0,2,23,0,4438,0,0,0,0,'','Dismount player when not in intended zone');

**Comment by Killyana** [comment]
Related to the script: https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/src/server/scripts/Northrend/zone_storm_peaks.cpp#L255
Conditions works correctly if the script is removed.
