### ISSUE TITLE
[4.3.4] - [Dungeon] - Countdown For Leave party or Raid in Dungeon

### ISSUE THREAD

**Issue by Farouche** [TrinityCore/TrinityCore#11778]
When a Player in the party or raid leave or removed. player have 60 sec countdown timer to teleport out of dungeon.
i will change countdown timer for leavers to 1 sec. when a player leave or removed = instant Teleport. >.<
How i can cut teleport time ? (60 sec to 1 Sec) need full description guys. i use trinitycore 4.3.4
in my server when player use macro :
/kick Playername
/kick Playername
/kick Playername
...
/invite playername
/invite playername
/invite playername
...instance bugs and Player will not save :| player can reset instances 5hc 25..
Sorry for my bad english. <3

**Comment by Killyana** [comment]
Use the forum or IRC for this kind of questions.
