### ISSUE TITLE
Quest 10557: Test Flight: The Zephyrium Capacitorium

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#11813]
What is supposed to happen:
Speak with Rally Zapnabber and use the Zephyrium Capacitorium. 
Test Tally's Experiment

The entirety of this quest happens in Blade's Edge Mountains

Doesn't work.  you don't get transported anywhere.

**Comment by Killyana** [comment]
Works correctly in rev. cc4f86cc2bf4
