### ISSUE TITLE
[Quest/Item] Shadowfrost Shard

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#11811]
It drops and it can't be picked up if no one has the quest (in raid group). 
More info at #11740 

Opening a new ticket as the old one is closed and no one is watching it.

DB: TDB_full_335.53_2014_03_28_01 + updates
Core (335a) Rev: 96b3df24cd285deab9b0b424c07ea3aab5992420

**Comment by Killyana** [comment]
The Shadowfrost Shard can be seen by all players but only ones having the quest can rand it or loot it, I will not add conditions as in the case if the raid lead distribute loots he will not see the shard and it will be a problem. Actually there's no error shown if someone want loot it and don't have the quest, He just can't.
rev. 5b5c093
