### ISSUE TITLE
[Boss/Spell] Halion 25 Heroic "Meteor Strike"

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#11829]
The Spell: "Meteor Strike" spell=75879 casted by Halion in 25Hc mode is supposed to do this:
Orb decending and when it reaches the ground:
1. Doing a huge load of damage
2. Making X or + shaped flame lines
3. Spawning a "Living Inferno"
4. Spawning a bunch of "Living Embers"

The problem: Currently it only does the first 3, the 4th part is not there. No Living Embers.

Source: http://www.wowwiki.com/Halion
https://www.youtube.com/watch?v=Msh_bdYanIM

Core Rev: 5221bd8c1099+
DB Rev: TDB_full_335.52

**Comment by Warpten** [comment]
1447875cac0fefd58ae3ad27e6b3fa2134a714c0
