### ISSUE TITLE
[Spell][fix] few important Spells that should be Uninterruptible

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#11835]
Here are a few spell that should NOT be interrupted, these are pretty important spells:

Professor Putricide's Gas Cloud(npc=37562)'s Gaseous Bloat(spell=70672)
Professor Putricide's Volatile Ooze(npc=37697)'s Volatile Ooze Adhesive(spell=70447)
Ruby Sanctum's Saviana Ragefire(npc=39747)'s Flame Breath(spell=74403)
Fire Phase Halion(npc=39863)'s Flame Breath(spell=74525)
Shadow Phase Halion(npc=40142)'s Dark Breath(spell=74806)

**Comment by danlapps** [comment]
Is this a valid fix ?

**Comment by Aokromes** [comment]
No, it's not, interruptible spells is handled by dbcs using mechanic_immune_mask over the boss will make legit interruptible spells non-interruptible.

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/12020
