### ISSUE TITLE
[Raid][Ruby Sanctum] Trash Mobs

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#11832]
Hi,The Trash Mobs in the Ruby Sanctum are missing AI, They currently cast no spells/auras and I also think their white attacks are way off the Retail values.

There are 3 Types of mobs walking around the instance and another kind guarding the entry to Zarithrian's hill,

Charscale Commander (40423-40424)
Charscale Invoker (40417-40418)
Charscale Assulter (40419-40420)
running around in packs or 5 or 3.

and Charscale Elties (40421-40422) guarding the entry to Zarithrian's hill,

In the video below you can find a tiny peak of what they should do:
Source: https://www.youtube.com/watch?v=DjT57-w377Y

Sadly I don't know the exact list of spells/auras/white attack damage of them. just reporting the problem atm.

Core Rev: 5221bd8c1099+
DB Rev: TDB_full_335.52

**Comment by Keader** [comment]
Missing scripts part already fixed by: https://github.com/TrinityCore/TrinityCore/commit/ef7a91d1938becb53fc9201275f0b5f02248765c

About white damage, has another issue about it: #11834, Maybe can be merged for a generic one.

**Comment by tkrokli** [comment]
Yes, Ruby Sanctum white damage issues can be handled in #11834 .
