### ISSUE TITLE
Bloodprince LOOT Bug

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#11884]
https://github.com/TrinityCore/TrinityCore/commit/ba61ec085dd3e0c954609c8af952ca2c694ae246

Players CAN Pull Boss 1x 1x And Kill
Players Pull Taldaram with (rouge - Druid - Warlock And ...) Example: Warlock creat  [Demonic Circle: Summon] in Back > GO And Cast Spell On Any of Boss Fast Teleport to Circle . Just 1x Boss pulled And 2x Other stay
Players kill 1x Boss (more time "Taldaram") loot 3x item . next Go and Kill 2x Other boss Again Loot 3x Item :package:

**Comment by Aokromes** [comment]
Anyone can create a PR for this?

**Comment by Keader** [comment]
No needed, I think issue dont valid anymore
Treeston change default dist ( 50.0f -> 250.0f ) in b7f2c87d37ad20e9fd39c6f0523f6b5edb9d4a66
i dont tested, but should fix the problem :+1:
