### ISSUE TITLE
[crash] Aura::UpdateOwner

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#11887]
Server crashed with following log:
http://www.trinitycore.org/f/pastebin/1f0oi0bf02r8t/

Revision: b36e7c0211aa263835732e37cec0ac14906557b2
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by xjose93** [comment]
More than 6 months without this crash, seems fixed.
