### ISSUE TITLE
[ Quest ] Test at Sea

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11880]
North Fleet Reservists seem to spawn dead... odd.  You can't bomb them to get quest completion.

http://www.wowhead.com/quest=11170

Core - 7b9b0ed+
TDB 335.53 + updates
Addons - Ahbot

**Comment by pete318** [comment]
If anyone hasn't yet used one of the non-sanctioned solutions for this. Please try the core change here: https://github.com/TrinityCore/TrinityCore/pull/14235

Thanks.
