### ISSUE TITLE
[4.3.4] quest related npc auras

### ISSUE THREAD

**Issue by NorthStrider** [TrinityCore/TrinityCore#11900]
In some cases npc's have quest related auras which the player can only see if he has quest xxxx.

This appears in another form at the undead starting zone where you have to talk with several npc's which have a "Hit me" point over their head.

rev.: 6131e4d722156be55c79311c7030d76f7b065884

**Comment by Killyana** [comment]
the whole Tirisfal area is scripted and also invisibility quest auras are scripted and working correctly, If you have an example of this issue with questID and AuraID, I will reopen it.
