### ISSUE TITLE
AI Reset and JustRespawned hooks

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#11927]
Reset hook comment says it is used on death and evade, but it is called on alive state when initial spawn occurs, on JustRespawned and on evade. Cant see if its called on death somewhere.
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/ScriptedAI/ScriptedCreature.h#L187
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/CoreAI/UnitAI.h#L129
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/CreatureAI.h#L124

JustRespawned hook comment says it is called on spawn and respawn, but it is just called on respawn, not on the initial spawn.
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/CreatureAI.h#L123

What is intended? Fix comments to the way it should be?
##

**Comment by Killyana** [comment]
Lot of changes were made on SAI, probably this issue was fixed.

**Comment by Killyana** [comment]
@Rochet2 this issue is still valid ?

**Comment by Rochet2** [comment]
Dont know, need to check, cant check now.
