### ISSUE TITLE
[4.3.4] Crash Entrapment http://www.wowhead.com/spell=64803

### ISSUE THREAD

**Issue by burnham** [TrinityCore/TrinityCore#11931]
Hi community, this is my crash log about hunter class with Entrapment:

http://pastebin.com/y6Mvdr4Q
TC rev: aa6ae2773f439ec5b41509e591f723163ca2bb0b

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
