### ISSUE TITLE
RBAC issue with GM accounts

### ISSUE THREAD

**Issue by aletson** [TrinityCore/TrinityCore#11933]
I discovered this one in 0b6efe4, but I'm not sure how long I've had the issue as I didn't really test on the previous patch.

I'm having issues running GM commands from one account on the server. The account has gmlevel 3 in the old system, which should grant permissions set 192 in the RBAC system unless I'm mistaken. I ran  .rbac account list {accountname} and got this back:

```
TC> .rbac account list <accountname>
Account 5 (<accountname>) granted permissions:
- 192 (Role: Sec Level Administrator)
Account 5 (<accountname>) denied permissions:
Empty List
Account 5 (<accountname>) denied permissions:
- 192 (Role: Sec Level Administrator)
```

I've read the documentation and can't find a solution. I checked the rbac_account_permissions table and it was empty. The rbac_default_permissions table DOES have the link between secId 3 and permissionId 192.  I did try to run ".rbac account revoke {accountname} 192 -1" per the documentation. It said the permission was revoked, but did not change the list of permissions when I checked with .rbac account list {accountname} again. 

Can anyone shed some light on this situation?

Thanks for your time.
##

**Comment by tkrokli** [comment]
This is likely related to why you need to set specific permissions for gmlevel 3 accounts individually to also have the RBAC permission for `.account create` when using some NPC manager like jackpoz' BotFarm.

**Comment by Killyana** [comment]
This is no longer valid as impossible to reproduce in a fresh sever.
