### ISSUE TITLE
[crash] Spell::prepare

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#11970]
Server crashed with following log:
http://www.trinitycore.org/f/pastebin/ofe3k0hq1rrf/

Revision: ba61ec085dd3e0c954609c8af952ca2c694ae246
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
