### ISSUE TITLE
[crash] Player::UnbindInstance

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#11971]
Server crashed with following log:
http://www.trinitycore.org/f/pastebin/15wgtidvxvdc7/

Revision: dc58ec0d6c4d33e04b74a5ca43340941bcab331c
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by digz6666** [comment]
This issue is fixed. Maybe since instance unbind fix.
