### ISSUE TITLE
[crash] AuraApplication::BuildUpdatePacket

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#11972]
Server crashed with following log:
http://www.trinitycore.org/f/pastebin/ofe3k0hq3ak4/

Revision: abb97bac18d4d38feacad37a3f60e79dd3b9606c
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
