### ISSUE TITLE
Group loot system

### ISSUE THREAD

**Issue by Fateswhisper** [TrinityCore/TrinityCore#11982]
rev https://github.com/TrinityCore/TrinityCore/commit/dc8a7a6fa5a3afb8f95958db2bdc0888361e56f8
Party group: 2 player
Loot: group loot
Kill boss
Player №1 need item №1
Player №1 logout
Player №2 greed item №1
Player №1 won item №1
Player №1 enter the world
Item №1  did not get to the player №1
Players №1 can not take item №1
Set loot: free for all
Players №1 and №2 can not take item №1

Is that correct?
##

**Comment by Killyana** [comment]
This is fixed, if the player disconnect before the roll ends he will not receive the item other players even if they greed the item will get it, and then could trade the item back.
