### ISSUE TITLE
Gundrak  Slad'ran

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11989]
adds dont come out until near the very end even on heroic

https://www.youtube.com/watch?v=GbWTQ-n_ZWI

http://www.wowhead.com/npc=29304/sladran

Core - 0c8df80+

addons npcbots and ahbot

TDB 335.53

**Comment by Killyana** [comment]
He start summoning his snakes at 30% and 25% for the green ones.
rev. f020f6f51974
``` cpp
            if (uiPhase == 0 && HealthBelowPct(30))
            {
                Talk(SAY_SUMMON_SNAKES);
                uiPhase = 1;
            }

            if (uiPhase == 1 && HealthBelowPct(25))
            {
                Talk(SAY_SUMMON_CONSTRICTORS);
                uiPhase = 2;
            }
