### ISSUE TITLE
violet hold - xevozz

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11994]
Xevozz should 

Tactics
(Heroic)
He summons two spheres following the group (or maybe the boss) these spheres are cannot get killed they deal very hight damage and you can be killed easy and fast,to avoid them you need to pulling the boss with singly steps away from the spheres to do not get damage,since he doesnt have high health like the other boss try to dps him as much you can.And one last tip,the whole group must moving to avoid spheres not only the tank.The whole group must moving to avoid the spheres.

(Normal)
In Difference from Heroic he summons one sphere instead of two from heroic and you will have to follow the tactics from heroic.
https://www.youtube.com/watch?v=H15EVk9isqI
https://www.youtube.com/watch?v=Eox4_ni--HU
Core - 0c8df80+

addons npcbots and ahbot

TDB 335.53

**Comment by Killyana** [comment]
He summon his spheres and they are visible like in the videos and he get buffed if they are near him.
rev. f020f6f51974
