### ISSUE TITLE
Gundrak  Gal'darah

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#11993]
Gal'darah should do 

Stampede: Summons Rhinos that targets a Party Member and knocks them back 

Transform: Transforms into a Rhino. During this form he uses a buff that increases Melee Attack speed  and also Impales Party Members dealing periodic damage per second while impaled
Stomp: This attack occurs when Gal'Darah is transformed and is an area attack where it will knock back anyone within it's radius.

https://www.youtube.com/watch?v=rrp32LH-ZLU

Core - 0c8df80+

addons npcbots and ahbot

TDB 335.53

**Comment by Killyana** [comment]
The boss is scripted correctly.
rev. f020f6f51974

**Comment by tkrokli** [comment]
To be honest, I never understood what kind of issue the OP tried to report here.
