### ISSUE TITLE
[Instances Bug] The Old Kingdom  Herald_Volazj

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#12016]
https://www.youtube.com/watch?v=7rGiqUQwPUY
http://www.wowwiki.com/Herald_Volazj
doesn't do 

Insanity - At around 66 and 33 percent health, Herald Volazj becomes invulnerable and applies a debuff to the entire party. Similar in nature to phasing, each individual member sees hostile copies of their original party. Clones have about 4k hp each and must all be killed. Once an individual player's copies are dead, you lose the Insanity debuff and can begin assisting other members to kill their own hostile clones. In heroic, your copies have 12k hp.

Mind Flay - Only targets the main tank and inflicts shadow damage.

Shadow Bolt Volley - Used every few seconds, deals roughly 350 shadow damage to the entire party.

Core - b48879a+
addons - ahbot - npcbot
TDB 335.53

**Comment by DDuarte** [comment]
4e0fb54a41e69e6839f58154abd09bfc609f92f2
