### ISSUE TITLE
[Quest : An End To All Things...] 

### ISSUE THREAD

**Issue by Galaxis78** [TrinityCore/TrinityCore#12022]
In "Breche death", the Lich King falls off the platform and found
hidden inside the little quest validate this when even behind
the platform at the edge of the cliff 53.68-37.05.
Coordinates with DMinCoors

DBC : 3.3.5.53

TrinityCore Rev. ca5dafe6afd9 2014-05-02 01:55:06 +0200 (master branch) (Win32, Release)
Update Time diff: 51.
UTC +1 Europe/Paris
Sorry for my wrote, i newbie for posting here...

**Comment by Killyana** [comment]
Cannot reproduce.
