### ISSUE TITLE
Core/Spells: Behavior of TARGET_UNIT_NEARBY_ENTRY

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#12027]
I think TARGET_UNIT_NEARBY_ENTRY should by default ignore line of sight when seeking targets. There are many spells on disables with flag 64 just to ignore LoS, and many of them have TARGET_UNIT_NEARBY_ENTRY

Among them:
48188 Flask of Blight
69922 Temper Quel'Delar
53038 Didgeridoo of Contemplation
52227 Dilute Blight Cauldron
46171 Scuttle Wrecked Flying Machine
45949 Release Aberration
38729 Rod of Purification
32205 Place Mag'har Battle Standard
32979 Ignite Horde Siege Engine
16378 Temperature Reading
##

**Comment by Aokromes** [comment]
Trisjdc code it! :P

**Comment by tkrokli** [comment]
TrinityCore rev. 0c1e485e13d0 2018-03-07 04:19:06 -0300 (3.3.5 branch) (Win64, Release, Static)

Is this still the right place to report that the spells
- http://www.wowhead.com/spell=38736/rod-of-purification
- http://www.wowhead.com/spell=38729/rod-of-purification
are unable to complete the quest
- http://www.wowhead.com/quest=10839/veil-skith-darkstone-of-terokk
when using
- http://www.wowhead.com/item=31610/rod-of-purification
?

Spell 38736 (on item 31610 use) just channels visually and does not seem to do anything else.
Spell 38729 (main Effect) gives the error "**You have no target.**" (and matching error voice).

I have browsed through
- https://github.com/TrinityCore/TrinityCore/search?q=darkstone+of+terokk&utf8=✓
- https://github.com/TrinityCore/TrinityCore/issues/1972 ( **[Quest] Veil Skith: Darkstone of Terokk** )
- commit https://github.com/TrinityCore/TrinityCore/commit/8c7db6cc8d0f979fd808c9fde36a646eb413e653 from issue 1972
- https://github.com/TrinityCore/TrinityCore/pull/10348 ( **Db/Quest: Veil Skith: Darkstone of Terokk** )
- https://github.com/TrinityCore/TrinityCore/pull/17599 ( **Core/GameObjects DeSpawn GAMEOBJECT_TYPE_SPELL_FOCUS at Use** )

but I can't seem to find anything looking like a real solution yet.
Are we still waiting for a general spell focus gameobject solution?

**Comment by Killyana** [comment]
Something weird about the condition here, the spell 38729 has condition on effect 1 and 4 (`SourceGroup`=5)
But if I update the condition to apply only on effect 1 I get the credit quest. @ariel- any idea why?
``` sql
UPDATE `conditions` SET `SourceGroup`=1 WHERE `SourceEntry` IN (38729) AND `SourceTypeOrReferenceId`=13;

**Comment by tkrokli** [comment]
Well, when I compare
- https://woehead.way-of-elendil.fr/?spell=38736
and
- http://www.wowhead.com/spell=38736/rod-of-purification

it looks like there is only supposed to be 1 effect of the spell.
Maybe we need to check SpellWork to see if there is something odd about the spell?

**Comment by Killyana** [comment]
No I'm talking about https://woehead.way-of-elendil.fr/?spell=38729
```
Effect 0: Id 86 (SPELL_EFFECT_ACTIVATE_OBJECT)
BasePoints = 1
Targets (40, 0) (TARGET_GAMEOBJECT_NEARBY_ENTRY, NO_TARGET)
EffectMiscValueA = 15

Effect 1: Id 16 (SPELL_EFFECT_QUEST_COMPLETE)
BasePoints = 1
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
EffectMiscValueA = 10839

Effect 2: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT)
BasePoints = 1
Targets (38, 0) (TARGET_UNIT_NEARBY_ENTRY, NO_TARGET)

**Comment by Killyana** [comment]
Actually the condition was wrong effect must target a npc and not a gob, here the fix with the gob activation effect:
``` sql
UPDATE `creature` SET `MovementType`=0, `spawndist`=0 WHERE `guid`=65930;
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry` IN (22288);
DELETE FROM `disables` WHERE `sourceType`=0 AND `entry` IN (38729,38736);
UPDATE `conditions` SET `SourceGroup`=1 WHERE `SourceEntry` IN (38729) AND `SourceTypeOrReferenceId`=13 AND `ConditionValue2`=185191;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN (38729) AND `ConditionValue2`=22288;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13,4,38729,0,0, 31,0,3,22288,0,0,0,'','');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN (38736) AND `ConditionValue1`=185191;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13,1,38736,0,0, 30,0,185191,15,0,0,0,'','');

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=22288;
DELETE FROM `smart_scripts` WHERE (`entryorguid`=22288 AND `source_type`=0);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(22288, 0, 0, 0, 8, 0, 100, 0, 38729, 0, 5000, 5000, 41, 0, 30, 0, 0, 0, 0, 20, 185191, 5, 0, 0, 0, 0, 0, "Terokk target - on spellhit - despawn gob");
