### ISSUE TITLE
[3.3.5][Walock][Succubus] Lash of Pain

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12029]
rev: 5e4083b // Newest DB // 3.3.5a

Conditions:
1. get a warlock
2. skill Demonic Power (http://wotlk.openwow.com/spell=18127) twice
3. get a Succubus
4. Use 'Lash of Pain' http://wotlk.openwow.com/spell=7814 on victim
5. watch cooldown of 'Lash of Pain'

What happens:
The cooldown of 'Lash of Pain' will be reduced to 6 sec. If u use the skill of the pet, the ability seems to be ready and usable after 6 sec, but if you want to use ist after the cooldown fades away, you must wait further 6 sec., until you can use the spell again.

What should happen instead:
After the cooldown of 6 sec. fades, you will be able to use the spell again.

**Comment by Rushor** [comment]
well this issue is present on 3.3.5

**Comment by ariel-** [comment]
Issue no longer present in HEAD.
