### ISSUE TITLE
[3.3.5] DBC Interrupt Check for Spells

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#12020]
Since these commits 3d9d76f31c22d19b680db3ad0332e1640efd830e 68601bb286e7235b2381d70afa3bac29d32ae8ee, Server is now checking DBC for Interrupt flags on spells, but there are some spells that are not getting the Interrupt Flag from the DBC so players can use spells like Mind Freeze, Kick, etc to stop those spell cast.

Examples:

Pungent Blight - http://www.wowhead.com/spell=69195
Slime Spray - http://www.wowhead.com/spell=69508
Flame Breath - http://www.wowhead.com/spell=74525
Dark Breath - http://www.wowhead.com/spell=74806

This has been reported before, but not as a generic issue:

https://github.com/TrinityCore/TrinityCore/issues/5223

Rev: 3751d547c0610681e2ae239b98ab72a61d577993
##

**Comment by mik1893** [comment]
Taking the first as example ( 69195 )
---------------------------------------------------------------------------------------------------------------------------
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx3: 0x00040100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS, SPELL_ATTR3_IGNORE_HIT_RESULT)
---------------------------------------------------------------------------------------------------------------------------
interrupt flag is 0x00000009

so SPELL_INTERRUPT_FLAG_MOVEMENT + SPELL_INTERRUPT_FLAG_INTERRUPT
that means spells get interrupted on movement + spell is interruptible!

So speaking from DBC perspective there is no issue for those spells. Also, the 4 spells dont have an attribute in common (so no general rule is applicable).

Solution is to set for those spells interruptflags = 0x00000000 in spellmgr.cpp

**Comment by pete318** [comment]
I would suggest the solution is to add a flag to spell_custom_attr in the database. Add handling for checking this flag and then set the flag on these spells (and then any others that are encountered in future).

**Comment by mik1893** [comment]
Let's go for the custom attribute then

**Comment by pete318** [comment]
Are you planning to do the change? I don't want to duplicate effort here.

**Comment by mik1893** [comment]
Yes i will

**Comment by ccrs** [comment]
isnt this closed by https://github.com/TrinityCore/TrinityCore/commit/efad3a3123aee9347f2aaa3034550cd0b0543e60 ?

**Comment by pete318** [comment]
My understanding, based on an IRC chat earlier is that no. This enforces UI indication of immune spell casts, still using DBC as a source for that data. In this case, DBC data is wrong, and needs to be overridden in some sensible way.

**Comment by Aokromes** [comment]
@pete318 something like https://github.com/TrinityCore/TrinityCore/pull/14235 can be added to allow add interrupt invulnerability for some spells?

**Comment by ccrs** [comment]
that was the original idea, at least. Seems like mik1893 didnt finish the job :P

**Comment by Golrag** [comment]
Looked at this issue today, looks like we are missing cast-immunities :/
Little sidenote: There is no "shield" around the icon in TrinityCore that tells you that you can't interrupt the spell while on retail there is one.

6.2.3 retail sniff:
```
ServerToClient: SMSG_SPELL_START (0x1077) Length: 108 ConnIdx: 1
(Cast) CasterGUID: Creature Map: 631 Entry: 36627
(Cast) CasterUnit: Creature Map: 631 Entry: 36627
(Cast) CastID: 0
(Cast) SpellID: 69508 (69508)
(Cast) SpellXSpellVisualID: 35165
(Cast) CastFlags: 67108874
(Cast) CastTime: 1500
(Cast) HitTargetsCount: 0
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) (Target) Flags: Self (0)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(Cast) (Target) Name: 
(Cast) RemainingPowerCount: 0
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) (Ammo) DisplayID: 0
(Cast) (Ammo) InventoryType: NonEquip (0)
(Cast) DestLocSpellCastIndex: 0
(Cast) TargetPointsCount: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 3
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) CastFlagsEx: 0
(Cast) HasRuneData: False
```

3.3.5a TrinityCore:
```
ServerToClient: SMSG_SPELL_START (0x0131) Length: 37 ConnIdx: 0
Caster GUID: Full: 0xF130008F1300008C Type: Creature Entry: 36627 Low: 140
Caster Unit GUID: Full: 0xF130008F1300008C Type: Creature Entry: 36627 Low: 140
Cast Count: 0
Spell ID: 69508 (69508)
Cast Flags: HasTrajectory (2)
Time: 1500
Target Flags: Self (0)
```

**Comment by Aokromes** [comment]
Not sure if the shield thing was present on 3.3.5a.

**Comment by Runico** [comment]
@Aokromes I have seen spells those have irony style in border of the current cast progress in 3.3.5a

**Comment by Aokromes** [comment]
3.3.5a sniff
ServerToClient: SMSG_SPELL_START (0x0131) Length: 39 ConnIdx: 0 Time: 07/22/2010 18:52:39.000 Number: 437534
Caster GUID: Full: 0000000 Type: Creature Entry: 36627 Low: 32169
Caster Unit GUID: Full: 0000000 Type: Creature Entry: 36627 Low: 32169
Cast Count: 0
Spell ID: 69508 (69508)
Cast Flags: HasTrajectory, Unknown3, Immunity (67108874)
Time: 1500
Target Flags: Self (0)
CastSchoolImmunities: 0
CastImmunities: 67109376

**Comment by Treeston** [comment]
@mik1893 update on this?

**Comment by Keader** [comment]
More example: 34797 Icehowl Artic Breath

**Comment by ariel-** [comment]
The solution is quite simple: missing interrupt immune on the npcs casting those spells (mechanic immunity is sent on spell cast packet, allowing the client to display the shield around the castbar)

```sql
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask`|33554432 WHERE `entry` IN
(36626,37504,37505,37506, -- Festergut
39863,39864,39944,39945,  -- Halion (normal)
40142,40143,40144,40145, -- Halion (twilight)
34797,35447,35448,35449); -- Icehowl
```

**Comment by Keader** [comment]
if i remember right has bosses that some spells can be interrupted and others not.
what happens in this case? add / remove interrupt mechanic in cpp?

**Comment by ariel-** [comment]
In that case yes it should be added, but only for spells that show a cast bar with a shield (means the cast packet has immunity flag)

**Comment by ccrs** [comment]
maybe add a parameter on Cast to specify whether a it should be inmune or not?

**Comment by ariel-** [comment]
Ir's not an issue of the spell itself but of the caster (as incorrectly stated by title). I can see how it makes sense to add a flag to CastSpell; but on the other hand it requires adding yet another parameter to it, and extra state on the Spell class to know if it should be sent with immunity flag.

IMO we should stick to mechanic immunity, with the occasional script that requires otherwise

**Comment by Golrag** [comment]
IIRC lady deathwhisper is immune to interrupts (like warrior pummel) but you can still interrupt the frost bolt.. you get the immune when you cast pummel while she's not casting a spell

**Comment by ccrs** [comment]
also I remember reading shauren about some missing dbc reading or data or we
it was ages ago so, dunnow

**Comment by Shauren** [comment]
@Golrag thats actually a pretty interesting observation

**Comment by Golrag** [comment]
Went testing it on retail to be sure and it appears it's only immune when in her shield, once she's out of it and you cast pummel while she's not casting you don't get a message, and Details tells me my pummel was cast but did not hit (not sure if it that means it's a miss/immune/did not interrupt anything). Combatlog doesnt show me anything about pummel sadly.
