### ISSUE TITLE
crash  _RegisterAuraEffect , _UnapplyAura

### ISSUE THREAD

**Issue by siley** [TrinityCore/TrinityCore#12041]
logs:http://212.37.80.144/paste/view/4f9212a5
http://212.37.80.144/paste/view/139ccd18
http://212.37.80.144/paste/view/539c6cc5

rev: https://github.com/TrinityCore/TrinityCore/commit/111bbb3620093f7db9bb94c37fcbc97c0a45c4c3

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
