### ISSUE TITLE
 bug antipersonnel cannon

### ISSUE THREAD

**Issue by desder** [TrinityCore/TrinityCore#12040]
http://www.wowhead.com/npc=27894
Have a flag disable move, first player enter and cannon not move, first player exit and enter distinct second player and cannon move, this issue repeat in all similar npc, example http://wowhead.com/npc=28366 
I use: 
Revision: TrinityCore rev. dc4cc63180a3+ 2014-04-29 07:31:07 -0500 (master branch) (Win64, RelWithDebInfo)
*** Hardware ***
Processor: AMD Opteron(TM) Processor 6272                 
Number Of Processors: 32
Physical Memory: 25163000 KB (Available: 7405528 KB)
Commit Charge Limit: 50324136 KB

*** Operation System ***
Windows Server 2008 R2 Server 4.0 Service Pack 1 (Version 6.1, Build 7601)

Non custom script.

**Comment by Aokromes** [comment]
#8736
