### ISSUE TITLE
Mount with a transformation

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#12042]
This commit: e51976e17a29bd2a318dc84e42cc24d3e9c877ae , or at least thats what I think, broke this mission http://wowhead.com/quest=12856 as you cant get into mounts with the brunnhildar transformation (http://wowhead.com/spell=55012 that triggers http://wowhead.com/spell=72914).

Maybe http://www.wowhead.com/quest=12851 isnt doable too but I havent tested it yet.

What happens is that you get unbuffed from the disguise spell, and therefore return to normal form, just in the moment you take the mision.

Here is a picture trying to mount with aura applied:

![image](https://cloud.githubusercontent.com/assets/4329612/2932147/2ff4ef64-d7ac-11e3-8535-685f0d0e9897.png)

And here I post one of the retail pictures with people riding mounts with this transformation:

![image](https://cloud.githubusercontent.com/assets/4329612/2932281/5a981aaa-d7ae-11e3-8389-8aa995cd33fc.png)

rev: 71795bf9776183429455d5742125b069836810e4

**Comment by danlapps** [comment]
Is the code valid to fix this ?

**Comment by nyds** [comment]
Issue still present in current build.

**Comment by danlapps** [comment]
This code was never pushed i think.  @jackpoz Is this valid enough to be turned into a PR ?

**Comment by Aokromes** [comment]
Make PR then it can be blamed xD

**Comment by danlapps** [comment]
LOL Thank you Aok, very reassuring :P

**Comment by Treeston** [comment]
Since nobody else could be bothered to do it.
