### ISSUE TITLE
Not mounted

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#12043]
these creatures should be mounted on their lovely bears <3

da bear: http://wowhead.com/npc=30174
da bitch: http://wowhead.com/npc=30175

dunnow if its wrong addon or anything else, but if they are spawned I guess its not vehicle accessory.

the generous and overmighty Sniff should show our path LOL

selfie:
![wowscrnshot_050914_213050](https://cloud.githubusercontent.com/assets/4329612/2932460/45200c34-d7b1-11e3-83ca-b931626500e9.jpg)

rev: 71795bf9776183429455d5742125b069836810e4

**Comment by Killyana** [comment]
``` sql
DELETE FROM `creature` WHERE id = 29498;
DELETE FROM `vehicle_template_accessory` WHERE `entry` IN (29500) AND `accessory_entry` IN (29498);
INSERT INTO `vehicle_template_accessory` (`entry`,`accessory_entry`,`seat_id`,`minion`,`description`,`summontype`,`summontimer`)VALUES
(29500,29498,0,1,'Brunnhildar Warbear',8,0);
