### ISSUE TITLE
fix on  Charge warrior

### ISSUE THREAD

**Issue by bwshood** [TrinityCore/TrinityCore#12075]
i think some on needs 

Edit by Aokromes: hackfix

``` sql
INSERT INTO `spell_linked_spell` VALUES (100, 96273, 0, 'Charge Stun');
```
##

**Comment by Keader** [comment]
Still valid?!
On 3.3.5 branch works

**Comment by Rushor** [comment]
originally it was for 4.x only - now we need to test if this is still bugged on 6.x :)

**Comment by tkrokli** [comment]
Added to #14825 (List of missing spell scripts) - closing.
