### ISSUE TITLE
Core/Loot: Conditional loot

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#12086]
If a creature you are looting has conditional loot that you cannot see or anyone else in the group cannot see remaining, you cannot skin the creature

Additionally, even though the loot window is _empty_ for your character, you can still try to open it. It immediately closes afterwards (since there's no loot)

One example is Anub'Arak, another example would be any creature with the Frostweave Cloth loot reference for tailors, without you having that particular tailor spell
##

**Comment by Killyana** [comment]
http://wowwiki.wikia.com/wiki/Skinning

    All the items from a corpse must be looted before it can be skinned.
    Any skinnable mobs will say "Skinnable" in their tooltip after they are dead and completely looted.
    If you're trying to skin something that is lootable by another player, that player must take all loot from the corpse, or you won't be able to skin it.
    In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item. This usually happens when killing several mobs at once before looting and skinning them. There is no way to skin such a corpse other than to drop at least one of the quest items so you can then loot the item one more time. Due to game mechanics, random drops from mobs are almost always determined at the time of looting, rather at some previous time. And almost all looted items required for quests can be acquired beyond the quota for the quest. Rarely, this can happen with bosses who are supposed to drop a single quest item that respawn before their previous corpse has been looted, such as Combat 15 Princess.
    If you possess a Unique item somewhere in your inventory (bags/bank), and the mob has dropped that exact same item as lootable, you will be unable to loot it because you can only have one of any Unique item. As such, you will be unable to skin that mob.

So the npc must be flagged skinnable only when everything is looted.
For TOC10/25 Conditions must be done to drop only items for the correct faction, same for Frostweave Cloth loot reference for tailors.
