### ISSUE TITLE
[core] GetClosePoint use (x,y) 2D Dist calc

### ISSUE THREAD

**Issue by phoenixfight** [TrinityCore/TrinityCore#12094]
in the core, there a 2D calc dist point function, in object.h 

``` c++
void GetClosePoint(float &x, float &y, float &z, float size, float distance2d = 0, float angle = 0) const;
```

This function is called more than 30 times.may cause some error.
a classic error like fishing:
1. You can place very, very high fishing, fishing insofar as (x, y) 2D range.
2. When you fishing only calculated (x, y) in the 2D range, but when the fish hook, you can't open the bait , becase is calculated (x, y, z) range of 3D, click no response. 
I think if  diff Z is greater than 4.5,some times you can't open fishnode.

Debug information is as follows:

```
2014-05-19_23:11:56 WORLD: Recvd CMSG_GAMEOBJ_USE Message [guid=164630]
2014-05-19_23:11:56 IsWithinDistInMap:obj=15, IsInMap=1,InSamePhase=1,_IsWithinDist=0
```

cast spell fishing:

``` c++
        case TARGET_DEST_CASTER_FISHING:
        {
            float minDist = m_spellInfo->GetMinRange(true);
            float maxDist = m_spellInfo->GetMaxRange(true);
            float dist = frand(minDist, maxDist);
            float x, y, z;
            float angle = float(rand_norm()) * static_cast<float>(M_PI * 35.0f / 180.0f) - static_cast<float>(M_PI * 17.5f / 180.0f);
            m_caster->GetClosePoint(x, y, z, DEFAULT_WORLD_OBJECT_SIZE, dist, angle);
```

the code in: HandleGameObjectUseOpcode

``` c++

    if (GameObject* obj = GetPlayer()->GetMap()->GetGameObject(guid))
    {
        if (!obj->IsWithinDistInMap(GetPlayer(), obj->GetInteractionDistance()))
            return;
```

may be need change this function ,or need a new function.
 someone have a idea to fix it ?
##

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7
