### ISSUE TITLE
Combat bug due to HostileReferences out of range

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#12100]
Whenever a player is in combat with a creature, and the creature later falls to an inactive grid, the combat persists and the reference never fades until the grid is active once more

One way to reproduce is by having a creature attack you, with no active objects/other players around, and then teleporting far away from area

The hostile reference never fades, and if you re-enter combat, you will stay in combat

Hostile references should probably be removed when the creature is not within a grid activation range of any active object
##

**Comment by Keader** [comment]
Should be fixed by a40d855337bd29f55d898fb5213af92abd5b43a1
But in current revs, Computer (from Mimiron - Ulduar) still stuck combat with you ,even if you is in other map.

**Comment by Aokromes** [comment]
The late #6756
