### ISSUE TITLE
[crash] Aura::GetType

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12125]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/1ndjjgrdkv1qx/
Full crash log: http://www.mediafire.com/download/7m3w2jwe2aybc3j/Crashes_aura_getauratype_7228bd3664d9fa6a808e338a2fb2f519a6370672.rar

Revision: 7228bd3664d9fa6a808e338a2fb2f519a6370672
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
