### ISSUE TITLE
[DB/Creature] Vartrus the Ancient

### ISSUE THREAD

**Issue by MitchesD** [TrinityCore/TrinityCore#12122]
Rev.: 8f42dd3fabe28e6a652d983025bc20e76e3f989e
TDB: 335.53 + updates

http://wowhead.com/npc=14524

This NPC isn't spawned but should be I think (but my information are from 3.2.x, not sure about 3.3.5a). On cata/mop is being removed. 

Can anyone confirm or deny?

**Comment by Aokromes** [comment]
Fixed.

**Comment by D4R4** [comment]
Can someone check to see if this is wroking properly? I can't get the damn tree to spawn :|

**Comment by tkrokli** [comment]
OK, I wanted to check it anyway. Just need to go buy some food first, then get back and test properly.

**Comment by tkrokli** [comment]
TrinityCore rev. 9948e633abaf 2015-03-11 20:59:21 +0100 (3.3.5 branch) (Win64, Release)
Tested today all the way from .char level 70, equip with [Gronnstalker Armor/itemset 669](http://wotlk.openwow.com/itemset=669) (for better damage protection) and some level 70 weapons, entering Molten Core to looting [Cache of the Firelord](http://www.wowhead.com/object=179703/cache-of-the-firelord), picking up [Ancient Petrified Leaf](http://www.wowhead.com/item=18703/ancient-petrified-leaf) and taking the quest [The Ancient Leaf](http://www.wowhead.com/quest=7632/the-ancient-leaf).

Left Molten Core and teleported to Felwood, rode to [Irontree Woods](http://www.wowwiki.com/Irontree_Woods) and killed the hostile mobs around the pond and its little island. Sure enough, the 3 ancients appeared the very moment I set foot on top of the stone hill. Coordinates: **48.6 , 23.8** (coordinates from Carbonite minimap).

![Vartrus the Ancient](http://i.imgur.com/QoOfKdd.png "Vartrus the Ancient")

Useful comments on wowhead regarding [Vartrus the ancient](http://www.wowwiki.com/Vartrus_the_Ancient) :
http://www.wowhead.com/npc=14524/vartrus-the-ancient#comments:id=413412

**Comment by danlapps** [comment]
Short version, fix works :p

**Comment by D4R4** [comment]
@tkrokli Thank you very much mate

**Comment by Rushor** [comment]
.go trigger 3587 --  for the ones who don't have this coord-thing

**Comment by tkrokli** [comment]
> Short version, fix works :p

@danlapps : not really a fix, just confirming what Aokromes already said, "Fixed."
It must have been fixed some time ago, but we just don't know when or how. :smirk_cat:

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9eea348d8256633a0f333dd7d6eb256b4c25ec06
