### ISSUE TITLE
[3.3.5][GameObject]The Trap Object 181584 do not despawn after cast

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12139]
core: latest
db: up-to-date

The gameobject 181584 (it's a trap, type 6, cast spell 29420) do not despawn after cast,
even I have changed it data4 = 1 in database.

Do I miss something? Or Is it a bug?
##

**Comment by Killyana** [comment]
Gameobject type 6 (trap) must spawn and despawn with the linked object generally a chest or a gobber, proof: https://youtu.be/lhGYyIs8mUs?t=1m

**Comment by tkrokli** [comment]
TrinityCore rev. f020f6f51974 2015-05-16 11:52:01 +0100 (3.3.5 branch) (Win64, Release)

The column of light still remains after looting the crate & the crate despawns.

**Comment by HeartWell** [comment]
The column of light still remains after looting the crate & the crate despawns.

**Comment by tkrokli** [comment]
@HeartWell : please state your TC core rev. hash & TDB version to validate your claim.
(I will test this myself, but we prefer that any claims like that contain rev. hash & TDB version for tracking.)

**Comment by tkrokli** [comment]
TrinityCore rev. 697147a59651 2016-10-30 15:20:54 -0300 (3.3.5 branch) (Win64, Release, Static)
- http://wotlk.openwow.com/quest=8463/unstable-mana-crystals
- http://wotlk.openwow.com/object=180600/unstable-mana-crystal-crate
- http://wotlk.openwow.com/object=181584/battered-crate-trap

The column of light (Battered Crate Trap) still remains after looting the crate & the crate despawns.

**Comment by SnapperRy** [comment]
Fixed by 5d9d25d and a38c094.
