### ISSUE TITLE
[crash] Aura::UpdateTargetMap

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12154]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/19p80puzq9fxu/
Full crash log: http://www.mediafire.com/download/y9827hnyqtn2hy8/crash_2014_05_28_aura_UpdateTargetMap.rar

Revision: acc9f1575ad9df1266b44fae51ef76563c30a02a
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
