### ISSUE TITLE
[3.3.5] Arcane Missiles

### ISSUE THREAD

**Issue by Firerfan** [TrinityCore/TrinityCore#12152]
Mage's Arcane Missiles cause very low damage to low-level enemies (Level 7 about 32 damage). Tested it with rank 1 and the last, no matter what i choose.

**Comment by ariel-** [comment]
Funny, I found the cause for this while trying to fix #15186. Luckily I was fighting some low level mobs, and I wondered why the breakpoint (with conditions to only trigger on cast of rank 13) wasn't triggering.
