### ISSUE TITLE
[Quest][Sholazar Basin] The Bones of Nozronn

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12168]
rev c06dc7d // newest DB

Quest works fine, but there are missing some visualls.
proof: https://www.youtube.com/watch?v=g6LTAsDJlyc&hd=1

Missing:
1) If you use the item the eyes of Nozronn should get a blue visuall. probably spawned by npc 28230.
2) after the triggernpc is spawned there should be a little earthquake (do we have a related spell with that effect?)
3) there should spawn some blue visual orbs which starts chasing the player and despawns after a while.
4) in the spellfocusgo should spawn another go http://de.wowhead.com/item=38519#screenshots:id=98401

I tried to fix it, but i cannot find the given spells/npcs for the event. :(
##

**Comment by dr-j** [comment]
I suspect the things that chase player are http://www.wowhead.com/npc=28279/sholazar-witch-light as several of these are  spawned in the same packet that spawns http://www.wowhead.com/npc=28256/voice-of-nozronn

Also in same packet there are also multiple http://www.wowhead.com/npc=28230/nozronns-eye spawned in total 24 units are spawned in same packet between 28230 and 28279

http://legion.wowhead.com/spell=39983/internal-shake-camera is cast by http://www.wowhead.com/npc=28256/voice-of-nozronn on spawn

http://www.wowhead.com/spell=46679/cosmetic-low-poly-blue-fire is cast by http://www.wowhead.com/npc=28230/nozronns-eye on spawn

http://www.wowhead.com/spell=32566/purple-banish-state ,http://www.wowhead.com/spell=35709/white-banish-state and http://www.wowhead.com/spell=33343/red-banish-state are  used by http://www.wowhead.com/npc=28279/sholazar-witch-light i seems random

This is only object spawned during this event http://wotlk.openwow.com/object=188443 wowhead does not think that object exists

**Comment by dr-j** [comment]
Rushor you should find my sniff of this quest on ftp its the one titled sholazar all but oracles and frenzyheart or something like that.

**Comment by Rushor** [comment]
kk
