### ISSUE TITLE
[3.3.5a][Instance][Violet Hold] Zuramat the Obliterator - Void Sentry

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12175]
core: 8d539ee
db: up to date

How it should be:
The Boss Zuramat (http://www.wowhead.com/npc=29314/zuramat-the-obliterator) casts spell: Summon Void Sentry (http://www.wowhead.com/spell=54369). In order to this the npc Void Sentry (http://wowhead.com/npc=29364#.) spawn.

After the spawn the npc should cast spell 54342 on hisself and change phase to 17.
The reason for that is that the npc 'Void Sentry' should only be attackable by someone who is affected by the debuff http://wowhead.com/spell=54343 which is applied by spell 54361 from the Boss Zuramat.

How it is acctually:
After the spawn of the npc Void Sentry, the npc starts attacking player and can be killed by everyone. The condition, that the npc will only be attackable by someone with the debuff of spell=54343 and the change of the phasemask, is not given.

These issues makes the achievement_void_dance a little bit harder.

proofs:
https://www.youtube.com/watch?feature=player_detailpage&v=rGmx6wxajbU#t=42
https://www.youtube.com/watch?feature=player_detailpage&v=8Z3rHcSvmKc#t=14

and for all german guys :D  
http://www.hordeguides.de/Instanz/WotLK/Boss/29314/Zuramat-der-Vernichter/index.htm

**Comment by Aokromes** [comment]
Anything of this can be pushed? if it's c++, plz create a PR.

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f6656d7536161758793ef72baa992d694aee5335
