### ISSUE TITLE
[Bug]Thousand Needle's Silithid missing friendly aggro pull.

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12177]
Bug:
"Silithid Hive Drone" and "Silithid Invader" upon aggroing and upon reaching low health should aggro nearby silithid mobs.

Note: "Silithid Searcher" should not behave in the same way.

Links:
Silithid Invader - http://www.wowwiki.com/Silithid_Invader
Silithid Hive Drone - http://www.wowwiki.com/Silithid_Hive_Drone

Core revision: 524152b5bf94
Database version: TDB 335.53
Addons: Anticheat1

**Comment by DDuarte** [comment]
ad350edd6844de96f331e1b565fe75903acf39cd
