### ISSUE TITLE
[3.3.5a][DB/GO] Saronite Rock - Forgemaster Garfrost

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12185]
core: 8d539ee
db: up to date

Forgemaster Garfrost http://www.wowhead.com/npc=36494 uses the spell http://www.wowhead.com/spell=68789 to summon Object: 196485 "Saronite Rock"
Player can hide behind the GO and everything works fine.
But there is one problem:

You can position the boss before the GO so that he will no longer attack the player.
The boss should ignore the GOs and walk through the rocks instead.

http://www.pic-upload.de/view-23386675/WoWScrnShot_053114_185851.jpg.html

proof:
http://www.youtube.com/watch?v=WrSFaEmYMak&feature=youtu.be&t=33s
##

**Comment by Killyana** [comment]
Cannot reproduce on TrinityCore rev. 9614f9d8cf29
