### ISSUE TITLE
[crash] Unit::RemoveOwnedAura

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12196]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/4o9gh5to4cae/
Full crash log: http://www.mediafire.com/download/a1c2as9hzb319d2/f7ac5a794677%2B_worldserver.exe_%5B30-5_9-51-18%5D.rar

Revision: acc9f1575ad9df1266b44fae51ef76563c30a02a
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
