### ISSUE TITLE
[crash] Unit::BuildValuesUpdate

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12197]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/211v27nsya00g/
Full crash log: http://www.mediafire.com/download/x0b12p5oxl8888i/f7ac5a794677%2B_worldserver.exe_%5B29-5_17-50-36%5D.rar

Revision: acc9f1575ad9df1266b44fae51ef76563c30a02a
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
