### ISSUE TITLE
[crash] BIH::intersectRay

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12194]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/1sp00r808lgdm/
Full crash log: http://www.mediafire.com/download/0rcxwcxie2j9g15/f7ac5a794677%2B_worldserver.exe_%5B31-5_10-3-16%5D.rar

Revision: acc9f1575ad9df1266b44fae51ef76563c30a02a
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.

**Comment by diavolb** [comment]
http://pastebin.com/vigrt3nf
+
flood vmapmanager2: could not load

3.3.5a
51c9bc75aa20f21bbbb0ff3e7eb73d3ae455704b
