### ISSUE TITLE
[crash] ScriptMgr::OnPacketSend

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#12195]
Server crashed with following log: http://www.trinitycore.org/f/pastebin/1o4w6i97hjay5/
Full crash log: http://www.mediafire.com/download/9rabwq3bt65tgqq/f7ac5a794677%2B_worldserver.exe_%5B30-5_23-46-25%5D.rar

Revision: acc9f1575ad9df1266b44fae51ef76563c30a02a
Database: TDB.335.53 (with updates)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Shauren** [comment]
Networking code has undergone major changes since this crash was reported, please open a new issue if this crash still occurs.
