### ISSUE TITLE
[3.3.5][Quest]Quest 9180 (JOURNEY TO UNDERCITY) bugged.

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12199]
core 26370223a0b9ab7b9542a6a727347063397f0fa7
db up-to-date

quest link  http://www.wowhead.com/quest=9180 

The bug is:
when you reward the quest,  npc 21641 will be summoned, and it will cast spell 34432.
Trace the cpp code  [zone_undercity.cpp] you'll understand what I say.
In offical:
1.you can not see creature 21641 
2.you can see spell 34432

but in trinitycore
you can not see both two of them

**Comment by Nyeriah** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8b7dabab2196794fe07236ae3e9dd893a745fb47
