### ISSUE TITLE
[Bug]Nothing But The Truth

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12213]
How it's supposed to work:
After delivering the quest to "Infiltrator Marksen", he is supposed to say some stuff then gain "Zombie Form" , say some more stuff and die.

Bugs:
1. He is always in zombie form.
2. He doesn't die after completing the quest.
3. He never says anything.

Links:
Quotes - http://www.wowwiki.com/Infiltrator_Marksen
Nothing But The Truth - http://www.wowhead.com/quest=1391
Infiltrator Marksen - http://www.wowhead.com/npc=5416

Core revision: 524152b5bf94
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Rushor** [comment]
works on current rev https://github.com/TrinityCore/TrinityCore/commit/89a7026898af8da7a24486795cbbbf6eb9777693

transform takes place, no startup errors and no runtimeerrors
