### ISSUE TITLE
[3.3.5a][Rogue][Spell] Master Poisoner

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12221]
core: 8d539ee

What sould happen:
Description of the talent:
If you have skilled http://wotlk.openwow.com/spell=31226 // http://wotlk.openwow.com/spell=31227// http://wotlk.openwow.com/spell=58410 (rank1/2/3) as a rogue you should have the ability to apply a debuff on the taget which increase the chance for critical strikes for the whole raidgroup by 1-3%.
 The debuff which should be applied:
http://wotlk.openwow.com/spell=45176

Note:
The deduff itself should not be visible as icon on the target:
By Aarondil (142 – 1) on 2008/11/23 (Patch 3.0.3)
I was seriously wondering if this is applied to all attackers, since Savage Combat (http://www.wowhead.com/?spell=58413) puts a debuff on the target telling it increases physical damage taken, while Master Poisoner does not.

rank 3 of the talent contains these informations:
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 3
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 231 (SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE), value = 3, misc = 23 (23), miscB = 0, periodic = 0
SpellClassMask = 00000000 00080000 00000000
    - 2818 - Tödliches Gift (Rang 1)
(...)
Trigger spell (45176) Not found, Chance = 100

What happens instead:
The debuff is not applied on the target, the spell is missing, there is no extra critical strike for the group.

**Comment by ariel-** [comment]
Actually the talent never worked. Fixing...
