### ISSUE TITLE
[Bug]Curgle Cranklehop missing gossips

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12249]
Bug:
Curgle Cranklehop is missing gossips. The current option to "Please tell me more about the hippogryphs." and "Please tell me more about the Gordunni ogres." doesn't work.

Found some code from arcemu which seems to be related to her.

Links:
Curgle Cranklehop - http://www.wowhead.com/npc=7763/curgle-cranklehop
The Code - https://www.assembla.com/code/Sakar/subversion/nodes/Arcemu/src/scripts/src/GossipScripts/Gossip_Tanaris.cpp?rev=30

Core revision: ea279da42505
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
UPDATE `gossip_menu_option` SET `action_menu_id`=943 WHERE `menu_id`=942 AND `id`=0;
UPDATE `gossip_menu_option` SET `action_menu_id`=944 WHERE `menu_id`=942 AND `id`=1;
DELETE FROM `gossip_menu` WHERE `entry` IN (944,943);
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (943,1521),(944,1646);
