### ISSUE TITLE
[Bug]Overlord Runthak

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12257]
How it should work:
If you right click "Overlord Runthak" he should say "I am he that carries out the Warchief's commands without question. I am Horde.". When you complete "The Lord of Blackrock" he should then say "Look to this fallen dragon, [race]. The might of the Horde is unquestionable!".

Bug:
He always says "Look to this fallen dragon, [race]. The might of the Horde is unquestionable!"

Links:
Overlord Runthak - http://www.wowwiki.com/Overlord_Runthak

Core revision: ea279da42505
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
DELETE FROM `gossip_menu` WHERE `entry`=6024 AND `text_id`=6935;
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (6024, 6935);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14) AND `SourceGroup`=6024;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`ErrorTextId`,`ScriptName`,`Comment`, `NegativeCondition`) VALUES
(14, 6024, 7176, 0, 8, 7783, 0, 0, 0, '', 'Show gossip text if player get the quest The Lord of Blackrockreward', 0),
(14, 6024, 6935, 0, 8, 7783, 0, 0, 0, '', 'Show gossip text if te quest The Lord of Blackrock is not rewarded', 1);
