### ISSUE TITLE
[Bug]Missing Quest - The Journey Has Just Begun

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12253]
Bug:
"The Journey Has Just Begun" isn't offered after "A Most Puzzling Circumstance" has been completed for both horde and alliance. This quest also requires the player to have at least 300 skill in Leatherworking.

Links:
A Most Puzzling Circumstance(Alliance) - http://www.wowhead.com/quest=24428
A Most Puzzling Circumstance(Horde) - http://www.wowhead.com/quest=24429
The Journey Has Just Begun(Alliance) - http://www.wowhead.com/quest=7497
The Journey Has Just Begun(Horde) - http://www.wowhead.com/quest=7493

Core revision: ea279da42505
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
The 300 skill required in Leather working is already set.
``` sql
UPDATE `quest_template` SET `PrevQuestId`=24429 WHERE `Id`=7493;
UPDATE `quest_template` SET `PrevQuestId`=24428 WHERE `Id`=7497;
