### ISSUE TITLE
[Bug]Jailor Eston missing abilities

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12261]
Bug:
"Jailor Eston" seems to be missing his "Enslave" ability.

Links:
Jailor Eston - http://wotlk.openwow.com/npc=2427
Enslave - http://wotlk.openwow.com/spell=3442

Core revision: ea279da42505
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
As explained by Rushor, 2 players must be on the threat list.
