### ISSUE TITLE
[3.3.5] DB/Quest: Locked ball and chain missing final event

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12260]
Bug:
"Locked ball and chain" requires nothing to activate. It should require a player to have a "Dull Iron Key".

Links:
Dull Iron Key - http://www.wowhead.com/item=3467
Locked ball and chain - http://www.wowhead.com/object=1721

Core revision: ea279da42505
Database version: TDB 335.53
Addons: Anticheat1
##

**Comment by offl** [comment]
Wasn't it fixed after https://github.com/TrinityCore/TrinityCore/commit/e112c3248fb5c23ed42a4221f3b08299ca8ca0c7?

And the event is missing.
Event: https://github.com/cmangos/classic-db/commit/e3714b3705dc4d78422db8e4c95e16499ea3813d
Texts: https://github.com/cmangos/classic-db/commit/5145b02ceb84c73a7e01e17c05c8ce455fcfcd86
```sql
SELECT * FROM `broadcast_text` WHERE `ID` BETWEEN 592 AND 595;
```

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `broadcast_text` WHERE `ID` BETWEEN 592 AND 595;
```
```
 ID  Language  MaleText                                                                                                       FemaleText  EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
---  --------  -------------------------------------------------------------------------------------------------------------  ----------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  -------------
592         1  Ah, it is good to be free of my bonds! Have you freed Tog'thar yet? The humans split us up after our capture.                     0         0         0            0            0            0        0       0       1          18019
593         1  Have you freed Drull yet? I don't know where he's being held.                                                                     0         0         0            0            0            0        0       0       1          18019
594         1  Go on ahead without me! I will make my own way to Tarren Mill.                                                                    0         0         0            0            0            0        0       0       1          18019
595         1  I will only slow you down, but no pink-skinned humans will keep me from freedom!                                                  0         0         0            0            0            0        0       0       1          18019
```

**Comment by offl** [comment]
> GAMEOBJECT_TYPE_GOOBER = 10
data1: questID (Required active quest_template.id to work)

What means -1 value in this column?

**Comment by Killyana** [comment]
It means not used, quest required is handle somewhere else and it works correctly.
The issue here comes from the dbc: https://imgur.com/a/j0UQ8
For the gob 1722 it works correctly but for 1721 the requirement is skipped, and I don't see any way to fix it on db side.

**Comment by offl** [comment]
I remember changing Data1 to 498(quest id) + e112c3248fb5c23ed42a4221f3b08299ca8ca0c7 fixes this issue, but changing Data1 is hack.

**Comment by Killyana** [comment]
No it changes nothing.

**Comment by offl** [comment]
Override Lock.dbc values is required :D

**Comment by offl** [comment]
Event added in https://github.com/TrinityCore/TrinityCore/commit/de592697c1cc1ca0ee4f515d1670c3aac5d99a33

**Comment by tkrokli** [comment]
OK, so is the issue solved, or is there still something to fix here?

**Comment by offl** [comment]
The main problem isn't solved

**Comment by ariel-** [comment]
Core doesn't correctly emulate client behaviour (client sends a cast spell packet, spell 68398), which passes lock checks and allows player to open the lock without proper key

**Comment by ariel-** [comment]
68398 Opening is autolearn spell, all characters have it. The problem is being an open lock effect looks like client automatically tries to cast it whenever ordered to interact with a locked GO. This is not the first time this happens:

https://github.com/TrinityCore/TrinityCore/blob/1904016ce090d54cbaf60e6270b9e02d16602a73/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp#L999-L1017

The script is trying to workaround this one core bug, (Planetarium access uses spell id 3366 shared by many keys, Dull Iron Key being one of them)

**Comment by ariel-** [comment]
Meh, Lock.DBC has garbage data in one of the locks
