### ISSUE TITLE
[Item] The Flag of Ownership 38578

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#12265]
Hi, this item should spawn a flag over the corpse of an enemy killed. It doesn't work. The cooldown starts but the flag doesn't appear.

http://www.wowhead.com/item=38578

commit e55555ed8c17e62822768050446bdd448ad74e20

**Comment by Killyana** [comment]
Still need condition to be used only if there's a dead player around.
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 51640 AND `spell_effect` = 51657;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(51640, 51657, 0, 'The Flag of Ownership');
