### ISSUE TITLE
[Bug]Tome of Mel'Thandris event missing

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12287]
How it should work:
1. Accept "The Howling Vale".
2. Use "Tome of Mel'Thandris".
3. "Velinde Starsong" will appear and say:
"The numbers of my companions dwindles, goddess, and my own power shall soon be insufficient to hold back the demons of Felwood."
"Goddess, grant me the power to overcome my enemies! Hear me, please, my need is desperate and my cause is just!"
"What... what is this? Could this be the answer to my prayers? Elune has granted me a weapon -- this scythe -- to defeat the demons."

Bug:
"Velinde Starsong" never appears.

Links:
The Howling Vale - http://www.wowwiki.com/Quest:The_Howling_Vale
Velinde Starsong - http://www.wowhead.com/npc=3946
Tome of Mel'Thandris - http://www.wowhead.com/object=19027

Core revision: d943b1d67980
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Rushor** [comment]
well then: the npc spawns now with SAI for this GO:

```sql
-- Tome of Mel'Thandris SAI
SET @ENTRY := 19027;
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,1,0,0,70,0,100,0,2,0,0,0,12,3946,2,40000,0,0,0,8,0,0,0,3169.15,-1211.71,216.95,4.59,"Tome of Mel'Thandris - On Gameobject State Changed - Summon Creature 'Velinde Starsong'");
```

tested and works:

http://pokit.org/get/?11c73df81101d033249029ce7ce1117c.jpg

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a19cc68496912b527eb6f3ff550f88cd5b2c4dab
