### ISSUE TITLE
[Bug]Gordunni Proxy

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12297]
Bugs:
1. They are trackable as Humanoids
2. Their weapons are visible to players.

Links:
Gordunni Proxy - http://www.wowhead.com/npc=23450
Gm on - http://i.imgur.com/e1QARIY.jpg
Gm off - http://i.imgur.com/lD7HJDC.jpg

Core revision: 0f0cea104dcceb029fc74e12f60f913e55d267fc
Database version: TDB 335.53
Addons: Anticheat1

**Comment by dr-j** [comment]
also some other things to point out are these npcs even meant to be spawned in Feralas since 

1) These are now level 71-72 these used to always be level 1 when I seen before
2) These npcs are marked as credit npc for http://www.wowhead.com/quest=11096 which is tbc quest.

**Comment by tkrokli** [comment]
Well documented solution compared to the code needed to remove those NPCs from Feralas. :smirk_cat:
Looking back at the OP, it made me remember the invisible blood elf NPC in Sanctum of the Stars, SMV. That NPC was also invisible while his 2H axe was visible. Anyway, that's just a digression. GJ :+1:
