### ISSUE TITLE
[RS] Halion damage multipliers

### ISSUE THREAD

**Issue by Tangol** [TrinityCore/TrinityCore#12309]
As Warpten said (https://github.com/TrinityCore/TrinityCore/pull/8066 & https://github.com/TrinityCore/TrinityCore/pull/7913), some of Halion's damage multipliers are missing. 
This results in low melee damage.

In the DB we have:
```
UPDATE `creature_template` SET `dmg_multiplier`=50 WHERE `entry`=39944;
UPDATE `creature_template` SET `dmg_multiplier`=85 WHERE `entry`=39945;
```
&
```
UPDATE `creature_template` SET `faction_A`=14,`faction_H`=14,`exp`=2,`mindmg`=509,`maxdmg`=683,`attackpower`=805,`dmg_multiplier`=35 WHERE `entry`=40143; -- 40143 - Halion (1) - The Twilight Destroyer
UPDATE `creature_template` SET `faction_A`=14,`faction_H`=14,`exp`=2,`mindmg`=509,`maxdmg`=683,`attackpower`=805,`dmg_multiplier`=50 WHERE `entry`=40144; -- 40144 - Halion (2) - The Twilight Destroyer
UPDATE `creature_template` SET `faction_A`=14,`faction_H`=14,`exp`=2,`mindmg`=509,`maxdmg`=683,`attackpower`=805,`dmg_multiplier`=85 WHERE `entry`=40145; -- 40145 - Halion (3) - The Twilight Destroyer
```

After checking various sources online (including retail videos*), i've found that it's damage should be like this:
10N: Damage: ~6k -> Should be ~10k
25N: Damage: ~7k -> Should be ~20k
10H: Damage: ~10k -> Should be ~17k
25H: Damage: ~15k -> Should be ~35k

Approximate fix:
```
UPDATE `creature_template` SET `dmg_multiplier`=65 WHERE `entry`=39863; -- 39863 - Halion (10n)
UPDATE `creature_template` SET `dmg_multiplier`=65 WHERE `entry`=40142; -- 40142 - Halion in Twilight Realm (10n)

UPDATE `creature_template` SET `dmg_multiplier`=110 WHERE `entry`=39864; -- 39864 - Halion (25n)
UPDATE `creature_template` SET `dmg_multiplier`=110 WHERE `entry`=40143; -- 40143 - Halion in Twilight Realm (25n)

UPDATE `creature_template` SET `dmg_multiplier`=90 WHERE `entry`=39944; -- 39944 - Halion (10h)
UPDATE `creature_template` SET `dmg_multiplier`=90 WHERE `entry`=40144; -- 40144 - Halion in Twilight Realm (10h)

UPDATE `creature_template` SET `dmg_multiplier`=200 WHERE `entry`=39945; -- 39945 - Halion (25h)
UPDATE `creature_template` SET `dmg_multiplier`=200 WHERE `entry`=40145; -- 40145 - Halion in Twilight Realm (25h)
```

*Sources:
https://www.youtube.com/watch?v=r3-RKsccF6E (25N)
https://www.youtube.com/watch?v=tVoMx6tq4x8 & https://www.youtube.com/watch?v=Gr-VfarlWFQ (10H)
https://www.youtube.com/watch?v=VAR1olGzApI & https://www.youtube.com/watch?v=MTPb4C2gLZk (25H)

**Tested on a warr with 22k armor, in Battle Stance and with no talents.
Rev: https://github.com/TrinityCore/TrinityCore/commit/232eaae69cd774fb2ce4014c61c77d6a5c685b01

**Comment by Aokromes** [comment]
Test http://pastebin.com/y3QS7Bgv

**Comment by danlapps** [comment]
I can go kill Halion on 10 10H 25 25 H if needs be for sniffs, but as a lvl 100 full plate not sure data are easy to get

**Comment by Aokromes** [comment]
#11834
