### ISSUE TITLE
[Crash] InstanceSaveManager::AddInstanceSave()

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#12317]
I have new crashlog:

http://pastebin.com/F8mM89MC

commit 232eaae69cd774fb2ce4014c61c77d6a5c685b01

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Pirricli** [comment]
Without crash since the last notified.

**Comment by Pirricli** [comment]
http://pastebin.com/JAEXf7VA

c7bc73c1677dfcd031f615b7c1d56be2ca736b78

It came back.

**Comment by Runico** [comment]
Rev: c544e88437106fb79dba14bbf8469deadb679e8a
http://pastebin.com/SFxZSVt8

**Comment by jackpoz** [comment]
what has your crash to do with this crash ?

**Comment by Runico** [comment]
@jackpoz, I didn't get your means ...

**Comment by jackpoz** [comment]
Is your crash report related to the original issue ? To me it looks totally unrelated, that's why I'm asking you what your crashlog has to do with this GitHub issue

**Comment by Runico** [comment]
i saw the first line was std::_Hashtable so i decide it belong to here :D, anyway ill create new issue

**Comment by Runico** [comment]
http://paste.ubuntu.com/12267156/

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
2 months without answer, if this bug is still valid open a new ticket.
