### ISSUE TITLE
[Bug]Sah'rhee missing text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12316]
Bug:
When you talk to "Sah'rhee" he should say "Thank you, little [race]!", however, at the moment he says "Greetings, [name]."

Links:
Sah'rhee - http://www.wowhead.com/npc=8767
Video(4:20) - https://www.youtube.com/watch?v=VBgatvgNKCA

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
DELETE FROM `gossip_menu` WHERE `entry`=1483 AND `text_id`=2155;
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES (1483, 2155);
UPDATE `creature_template` SET `gossip_menu_id`=1483 WHERE `entry`=8767;
