### ISSUE TITLE
Defias Smuggler Bugged

### ISSUE THREAD

**Issue by Sidious78** [TrinityCore/TrinityCore#12318]
The Defias Smugglers in Westfall are quite bugged.

creature_template entry #95

They will stay rooted when entering combat, only to become mobile when their health is critical.

Also: They will attack the player when sheeped, as sheep.

Edit (pardon, I'm a newbie):
Using DB: 335_53_2014_03_29
Core: e5bd194 2014-06-09 10:11:56 +0200 (master branch)

**Comment by Killyana** [comment]
Cannot reproduce on rev. f020f6f51974
