### ISSUE TITLE
[Bug]Tooga's Quest

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12322]
Bugs:
1.Currently "Tooga" only says "I'm thirsty." and "Torta must be so worried." while travelling. He should say either of these 7 quotes:

Torta must be so worried.
I keep getting sand stuck in my toes.
I'm thirsty.
I wish you could just pick me up and carry me.
Do we have much further to go?
Are we there yet?
Have you heard the one about the ogre, the goblin, and the pit lord?

2.The quest instantly completes.

Links:
Tooga's Quest - http://www.wowwiki.com/Quest:Tooga's_Quest
Video of quest - https://www.youtube.com/watch?v=egTuW63-FVg

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
All texts are already on the DB with broadcast, just the `SpecialFlags`=2 must set for the quest.
``` sql
UPDATE `quest_template` SET `SpecialFlags`=2 WHERE  `Id`=1560;

**Comment by Hobbilis** [comment]
As of https://github.com/TrinityCore/TrinityCore/commit/04e9d25b3e51ebb7a2f84118cbcf86a24cd43e64 Tooga is still bugged.
After engaging hostile NPC and killing him, Tooga stays in the spot indefinitely.

**Comment by illfated** [comment]
@Hobbilis : Probably a waypoint issue (haven't tested it).
It may be better if you open a new issue ticket and fill in the requested issue template information.
This issue page was closed with a working solution back in 2015, so a lot of things have changed.
