### ISSUE TITLE
[Bug]Witch Doctor Zum'rah emotes

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12335]
Bug:
1 When "Witch Doctor Zum'rah" yells "T'eif godehsi wha!" for trolls it doesn't read as "Sands consume you!".

2 When "Witch Doctor Zum'rah" yells "T'eif godehsi wha!", a sound should play which should say "Sands consume you!".

Links:
Video(0:06) - https://www.youtube.com/watch?v=l_4Qf-6tvFU
Witch Doctor Zum'rah - http://wowpedia.org/Witch_Doctor_Zum'rah

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_text` SET `text`='Sands consume you!', `BroadcastTextId`=6221, `sound`=5872 WHERE `entry`=7271 AND `GroupId`=1;
UPDATE `creature_text` SET `sound`=5872 WHERE `entry`=7271 AND `GroupId`=2 AND `id`=2;
UPDATE `creature_text` SET `sound`=5873 WHERE `entry`=7271 AND `GroupId`=2 AND `id`=3;
