### ISSUE TITLE
[Bug]Cyrus Therepentous 2nd text.

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12337]
Bug:
After completing "A Taste of Flame(4023 or 4022)", "Cyrus Therepentous" flavor text should change. Deducing from eWoWProject and a another site, it seems to be "Only a fool would dare disturb me in my lair."

Links:
eWoWProject - http://subversion.assembla.com/svn/eWoWProject/eWoW.Scripts/scripts/npctext.scp
The site - http://www.zam.com/users/Lecie#Recent_Posts
A Taste of Flame - http://www.wowhead.com/quest=4022
A Taste of Flame - http://www.wowhead.com/quest=4023
Cyrus Therepentous - http://www.wowhead.com/npc=9459

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Rushor** [comment]
```sql
DELETE FROM `gossip_menu` WHERE `entry`=40060;
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES 
(40060, 2494),
(40060, 2493);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=40060 AND `SourceEntry` IN (2494, 2493);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `Comment`) VALUES
(14, 40060, 2494, 0, 0, 8, 0, 4023, 0, 0, 1, 0, 0, 'Show gossip text if player do not has quest 4023 completed'),
(14, 40060, 2493, 0, 1, 8, 0, 4022, 0, 0, 1, 0, 0, 'Show gossip text if player do not has quest 4022 completed');
```

self tested and works with the fix. after turning in the quest, the stuff changes to: http://pokit.org/get/?6a0d08d8df7d2dedef2f4199b8cf6d29.jpg
