### ISSUE TITLE
[3.3.5a][Icecrown Citadel/Professor Putricide] Volatile Oooze - Ooze Eruption

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12336]
http://www.wowhead.com/npc=37697 casts Volatile Ooze Adhesive (http://www.wowhead.com/spell=70447) on the choosen player. If the ooze reaches the player the ooze casts http://www.wowhead.com/spell=70492 and knocks back all enemys in the near of the player.

Problem: The choosen player itself does not gets knockbacked and stays at its place.

Proove, thet the choosen player also should get a knockback:
https://www.youtube.com/watch?feature=player_detailpage&v=uVHr9aZx5O0#t=280

Probably an issue in the spellscript?
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L1042
There muust be something like:
GetCaster()->CastSpell(GetHitUnit(), SPELL_KNOCKBACK???, true);

https://www.youtube.com/watch?v=wAgbqm6sqbo&feature=player_detailpage#t=192
There one can see, that the ooze itself casts the knockbackspell, probabaly we should change, that the ooze will cast the spell http://www.wowhead.com/spell=70492 on hisself, if he arrives the player with the aura spell=70447.

**Comment by tkrokli** [comment]
@Rushor @ManuFe : looking at the source, I suppose these 2 are the lines you mentioned in 2014:
https://github.com/TrinityCore/TrinityCore/blob/16b6eb3ee9a85c2d3140f089feb168752e732134/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L1063-L1064
```cpp
                    GetCaster()->CastSpell(GetHitUnit(), SPELL_OOZE_ERUPTION, true);
                    GetHitUnit()->RemoveAurasDueToSpell(adhesiveId, GetCaster()->GetGUID(), 0, AURA_REMOVE_BY_ENEMY_SPELL);
```
And if I don't misunderstand your description, they should look like this instead (swapped order) :
```cpp
                    GetHitUnit()->RemoveAurasDueToSpell(adhesiveId, GetCaster()->GetGUID(), 0, AURA_REMOVE_BY_ENEMY_SPELL);
                    GetCaster()->CastSpell(GetHitUnit(), SPELL_OOZE_ERUPTION, true);
```
If you prefer a diff of it, this is how it looks like in a diff from the 3.3.5 source:
```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
index 6308280..d7a5808 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
@@ -1060,8 +1060,8 @@ class spell_putricide_ooze_eruption_searcher : public SpellScriptLoader
                 uint32 adhesiveId = sSpellMgr->GetSpellIdForDifficulty(SPELL_VOLATILE_OOZE_ADHESIVE, GetCaster());
                 if (GetHitUnit()->HasAura(adhesiveId))
                 {
-                    GetCaster()->CastSpell(GetHitUnit(), SPELL_OOZE_ERUPTION, true);
                     GetHitUnit()->RemoveAurasDueToSpell(adhesiveId, GetCaster()->GetGUID(), 0, AURA_REMOVE_BY_ENEMY_SPELL);
+                    GetCaster()->CastSpell(GetHitUnit(), SPELL_OOZE_ERUPTION, true);
                 }
             }
```
Is it still of interest to make a PR on this, or can one of the main developers write up a direct commit?

**Comment by Rushor** [comment]
pr cuz everyone is lazy 
if you create a pr, we will have an new issue and the pressure and motivation to close the issue

**Comment by tkrokli** [comment]
@ManuFe & @Rushor :Thanks for the work on this issue, I am happy to see it closed with your fix. :+1:
