### ISSUE TITLE
[Quest The test of Righteousness/Whitestone oak lumber] possible by-design

### ISSUE THREAD

**Issue by ragmanii** [TrinityCore/TrinityCore#12377]
TrinityCore rev. 77c4ff292389+ 2014-06-25 14:47:07 +0200 (master branch) (Win64, Release)
Once the goblin woodcarver is downed any body that has the "whitestone oak lumber" item on them will not disappear, after you have already looted one of the aforementioned items. The wood cannot be picked up more than once. This may be by-design but was confusing to me as it leaves the bodies around with the sparkle on them, so I wanted to add a searchable thread that addressed this "feature".

**Comment by Killyana** [comment]
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=1 AND `SourceEntry`=6994;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`Scriptname`,`Comment`) VALUES
(1,641,6994,0,0,2,0,51315,1,1,1,0 ,'' , 'whitestone oak lumber drop only if the player doesn''t have it already');
