### ISSUE TITLE
Priest bug

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#12394]
Hi, i found something wrong. The Inner Will says:
"...You can only have Inner Will or Inner Fire active at a time." 
(http://www.wowhead.com/spell=73413)

http://kepfeltoltes.hu/140629/bug_www.kepfeltoltes.hu_.png

TrinityCore rev. 1ed38faeac83+ 2014-06-24 00:00:58 +0200 (4.3.4 branch) (Win32, Release)

**Comment by Keader** [comment]
spell removed from retail in 7.x no?

**Comment by tkrokli** [comment]
http://wow.gamepedia.com/Inner_Will :

- WoD Patch 6.0.2 (2014-10-14): Removed.
- Hotfix (2013-12-11): 
  - "Priest's Inner Fire and Inner Will should no longer be removed at the start of an arena match."
- Cataclysm Patch 4.1.0 (2011-04-26): Now last until canceled.
- Cataclysm Patch 4.0.1 (2010-10-12): Added.

[Inner Fire](http://wow.gamepedia.com/Inner_Fire) was also removed in Patch 6.0.2 (2014-10-14)
