### ISSUE TITLE
Surge of Light (Priest talent)

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#12396]
Hi, after Surge of Light is proccing, you can spamm the Flash Heal with no cost mana till that Surge of Light doesn't expires (10 sec). And the Surge of Light spell proccs with Penance spell too!
http://kepfeltoltes.hu/140629/surge_www.kepfeltoltes.hu_.png

Surge of Light (rank1 spell ID) : 88687
Surge of Light (rank2 spell ID) : 88690
Flash Heal (spell ID) : 2061

TrinityCore rev. 1ed38faeac83+ 2014-06-24 00:00:58 +0200 (4.3.4 branch) (Win32, Release)

**Comment by timh52280** [comment]
Surge of Light is a Holy talented priest and Pennance is a Discipline Priest how can Penance spell procs Surge of Light if this is a spell from a different tree of talents?

**Comment by timh52280** [comment]
Fix:

DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 101062;
INSERT INTO `spell_linked_spell` VALUES (101062,-88688,0,'Flash Light must remove Surge of Light aura');

DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 24 AND `SourceEntry` = 88687);
INSERT INTO `conditions` VALUES 
(24,0,-88687,0,0,1,0,88688,0,0,1,0,0,'','Surge of light R1 must not be proc if we already have the aura'),

DELETE FROM `spell_proc_event` WHERE `entry` = 88687;

INSERT INTO `spell_proc_event` VALUES
(-88687,0,6,7296,4,0,0,0,0,0,0); -- Surge of light

**Comment by Aokromes** [comment]
This is needed for 6.x?

**Comment by P-Kito** [comment]
No. You can have more than 1 stack of "Surge of Light" in 6.x.
