### ISSUE TITLE
[Bug]The Deeprun - Naga Siren

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12429]
Bug:
Naga Siren has no movement.

Links:
Naga Siren - http://www.wowhead.com/npc=10956
Video(6:00) - https://www.youtube.com/watch?v=oSJg5LXf9BI

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
UPDATE `creature` SET `MovementType`=1, `spawndist`=10  WHERE `id`IN (10956); 
UPDATE `creature_template` SET `InhabitType`=2 WHERE `entry`=10956;
