### ISSUE TITLE
[Crash]StopCastingCharm

### ISSUE THREAD

**Issue by darte631** [TrinityCore/TrinityCore#12435]
Good day ladies and gentlemen

Crashlog:
http://pastebin.com/Gb62DazA

Rev - 95f864f - TDB Full + updates 53

Custom - Transmogrification by Rochet2, Duel Reset

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated crashlog.
