### ISSUE TITLE
[Bug]The Deeprun - Nessy

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12431]
Bugs:
1. She doesn't move.
2. She is invisible, however, she can still be seen while noclipping.
3. Nessy should either become invisible after some time or teleport to another part of deeprun. Considering that there are sightings of her on both deeprun sides, she should probably teleport.

Links:
Nessy - http://www.wowhead.com/npc=10942
Camera huggin the wall - http://i.imgur.com/zf8k7Ph.jpg
Camera in water - http://i.imgur.com/xq5j47U.jpg
Camera noclipping - http://i.imgur.com/aXXmFBh.jpg
Video - https://www.youtube.com/watch?v=zVAMm2xsTQM
Video - https://www.youtube.com/watch?v=l10ALRGc7y0
Video(2:00) - https://www.youtube.com/watch?v=pEEVRdhaNFI

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
UPDATE `creature` SET `MovementType`=1, `spawndist`=8, `position_x`=-93.361, `position_y`=1246.15, `position_z`=-123.506 WHERE `guid`=48268;
