### ISSUE TITLE
[Bug]The Deeprun - Deeprun Diver

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12432]
Bug:
The 2 "Deeprun Divers" are missing waypoints. According to a comment on alakhazam, they should also open up the "Deeprun Chest" along their way.

"i like walking the water part in deeprun. i read here about a deeprun chest and i finally found it its by the north tube between the naga and the sunken boat. and for some reason the diver walks up to it and opens it and then walks off"

Links:
Comment - http://wow.allakhazam.com/forum.html?forum=21&mid=1153366217288487995
Deeprun Diver - http://www.wowhead.com/npc=14121
Deeprun Chest - http://wotlk.openwow.com/object=179345
Video(1:12) - https://www.youtube.com/watch?v=pEEVRdhaNFI

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
The action 9 crashs the server.
``` sql
DELETE FROM `waypoints` WHERE `entry` IN (1412100);
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES
(14121, 1, 44.334, 1180.138, -121.573, 'Deeprun Diver'),
(14121, 2, 33.919, 1141.767, -122.757, 'Deeprun Diver'),
(14121, 3, 45.891, 1193.066, -121.714, 'Deeprun Diver'),
(14121, 4, 55.744, 1206.163, -121.63, 'Deeprun Diver');


UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (14121);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (-53790) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(-53790, 0, 0, 0, 1, 0, 100, 1, 1, 1, 0, 0, 53, 0, 14121, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Deeprun Diver - ooc no repeat - Start wp'),
(-53790, 0, 1, 2, 58, 0, 100, 0, 0, 0, 0, 0, 55, 10000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Deeprun Diver - On wp ended - pause wp'),
(-53790, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 20, 179345, 10, 0, 0, 0, 0,0,'Deeprun Diver - On wp ended - activate object');

**Comment by Frytiks** [comment]
Have you crashlog ?

**Comment by Killyana** [comment]
No nothing.

**Comment by tkrokli** [comment]
TrinityCore rev. 0148832b322b 2015-05-21 16:42:18 +0200 (3.3.5 branch) (Win64, Debug)
DBErrors.log :
```
Spell (Id: 63137, effIndex: 0) listed in `spell_target_position` does not have target TARGET_DEST_DB (17).
```
MSVC Debug dialogue :
```
Unhandled exception at 0x00007FF6B2674BC7 in worldserver.exe: 0xC0000005: 
Access violation writing location 0x0000007298C10000.

First-chance exception at 0x00007FF6B2674BC7 in worldserver.exe: 0xC0000005:
Access violation writing location 0x0000007298C10000.
```
Which logs would you like me to post?

**Comment by Frytiks** [comment]
This is absolutly uselles crashlog. @killyana with your sql fix core crashing ? I can test it and fix it.

**Comment by tkrokli** [comment]
I never said that I posted any crash logs. I want to know how to find the crash logs. Do you want the binary .DMP file or where do I look for the crash log? Do I need to change all the .logger settings in Worldserver.conf to produce the needed logs? Do I use something called valgrind? How do I proceed?

**Comment by Killyana** [comment]
You can reproduce the crash:
- Use the script
- .go crea 53790
- Wait until the npc move near the chest to open it (when the activate object is called the crash will happen)

**Comment by tkrokli** [comment]
Yes, I did that. I confirmed that action_type 9 crashes the Worldserver.exe . That is when I got the onscreen messages above. But those messages are not crash logs, they are just what I could see on my screen when the crashes happened. I crashed the world server 7 times in a row and I can continue doing it as many times as I want. Should I try crashing it 20 times or is it enough to crash it 10 times? But I think you want some log files, like crash logs of some kind. Where can I find those logs you want? Is there a wiki page with the file names to look for?

**Comment by jackpoz** [comment]
does anything appear on the console when it crashes ?

**Comment by jackpoz** [comment]
It's an infinite loop triggered by SAI https://gist.github.com/jackpoz/7f44456582a833710a32

**Comment by Killyana** [comment]
Confirm, with SMART_EVENT_WAYPOINT_REACHED it doesn't cash.
``` sql
DELETE FROM `waypoints` WHERE `entry` IN (14121);
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES
(14121, 1, 44.334, 1180.138, -121.573, 'Deeprun Diver'),
(14121, 2, 33.919, 1141.767, -122.757, 'Deeprun Diver'),
(14121, 3, 45.891, 1193.066, -121.714, 'Deeprun Diver'),
(14121, 4, 55.744, 1206.163, -121.63, 'Deeprun Diver');
UPDATE `creature` SET `MovementType`=0, `spawndist`=0 WHERE `guid`=53790;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (14121);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (-53790) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(-53790, 0, 0, 0, 1, 0, 100, 1, 1, 1, 0, 0, 53, 0, 14121, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Deeprun Diver - ooc no repeat - Start wp'),
(-53790, 0, 1, 2, 40, 0, 100, 0, 4, 14121, 0, 0, 54, 10000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Deeprun Diver - On wp reached - pause wp'),
(-53790, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 20, 179345, 10, 0, 0, 0, 0,0,'Deeprun Diver - On wp reached - activate object');

**Comment by Aokromes** [comment]
Still i think core must be safe of crashing because bad db data.
