### ISSUE TITLE
[335] Skinning Error: Creature Must Be Looted First

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12457]
__Core:__ latest (j/k) c28345e279f31af2fa32df2411325ccfabe06fc8
__DB:__ TDB_full_335.52 + updates

__Bug:__

When trying to skin a creature that has no loot you sometimes get an error saying the creature must be looted first

__Details:__

Creature: [Nightsaber - Teldrassil](http://www.wowhead.com/npc=2042), [Princess - Elwynn Forest](http://www.wowhead.com/npc=330)

Sometimes when skinnable creatures die they display the skinning icon (if you have skinning) but will error saying the creature must be looted first.

__Notes:__

This doesn't seem to be a loot lag issue because they never display the loot icon and logging out / back in does not fix the issue.

I also tried on a newer core: https://github.com/TrinityCore/TrinityCore/commit/a8b05db however due to the randomness it's difficult to duplicate, I was only able to play about 10 minutes on this core.

**Comment by Aokromes** [comment]
A lot of months since feedback request, closing. If this bug is still valid open a new ticket.
