### ISSUE TITLE
[FIX][3.3.5][SAI] Movement/Casting issue with creature's SAI vs. Waypointmovement/Randommovement

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12476]
DB: up-to-date
Core: 29e676588589244c6d59996299d078dd67912e80 
If a creature's movement is 1 or 2 and it has a smart ai which 
event_type is 0
action_type is 11
action_param2 is 64
you'll find that the creature cann't move any more (just like movement is 0) out of combat.
This issue is very similar as 
https://github.com/TrinityCore/TrinityCore/issues/12206

These issues cause MAGE creature don't action correctly out of combat.
##

**Comment by jackpoz** [comment]
any clear detailed How To Reproduce steps ?

**Comment by Killyana** [comment]
To reproduce it:
- Activate gm on
- .go c 82542 (you will notice the npc has random movements with sawndist=5)
- Disable gm mode to aggro the npc, once in combat activate gm on.
- You will notice after evade the npc is not moving (random movements)

**Comment by velinath** [comment]
Might as well throw in my 2 cents for effects of this bug as well. Below follow a couple of examples. As far as repro steps, just teleport to the GUID and aggro the mob from range.

Savage Hill Scavengers (NPC 29404, example GUID 117091) do not run towards the player between casts of Bone Toss.

Working off of @Killyana's comment above with creature GUID 82542 led to the same issue.

If you try this with a mob that doesn't match the SAI conditions noted in this issue - one example would be GUID 123997, a Malefic Necromancer in Icecrown) - the cast / run to player stuff works as it does on retail.

**Comment by Killyana** [comment]
SMARTCAST_COMBAT_MOVE:  64 Prevent combat movement on cast, allow on fail range, mana, LOS must disable movements during the cast of the spell only, actually movements stay disabled event after the combat.

**Comment by tkrokli** [comment]
https://trinitycore.atlassian.net/wiki/display/tc/smart_scripts#smart_scripts-CastFlags
So if the creature does not reset properly after `SMARTCAST_COMBAT_MOVE` (64) (0x40),
maybe all scripts using that action need to have a line added with `SMART_EVENT_RESET` (25)
until this issue is solved in the C++ source for SmartAI?

**Comment by Killyana** [comment]
This must be tested, probably fixed

**Comment by Killyana** [comment]
Cannot reproduce on rev. 1acfefb97389
