### ISSUE TITLE
[335] Innkeeper Keldamyr Has Repeating Gossip Option

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12474]
__Core:__ c28345e279f31af2fa32df2411325ccfabe06fc8
__DBL:__ TDB_full_335.52 + updates

__Bug:__

Inkeeper Keldamyr has double "I want to browse your goods" option.

__Details:__

```SQL
SELECT * FROM `gossip_menu_option` WHERE `menu_id`=(SELECT `gossip_menu_id` FROM `creature_template` WHERE entry=6736);
```
__Fix:__

```SQL
DELETE IGNORE FROM `gossip_menu_option` WHERE `menu_id`=1293 AND `id`=3;
```
__Notes:__

* Players may need to delete their *creaturecache.wdb* to see the change
* This bug did not exist in earlier versions (around 2013-12-01) of the core though I did not look to see which commit actually caused the issue.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `gossip_menu_option` WHERE `menu_id`=1293 AND `id`=3;

**Comment by MrSmite** [comment]
> DELETE FROM `gossip_menu_option` WHERE `menu_id`=1293 AND `id`=3;

Right, I had that in my OP but used *IGNORE*, do we not use that command?

**Comment by Killyana** [comment]
No if there's an error in the sql it must not be ignored.
