### ISSUE TITLE
[335] Hunter pets should not have 0 focus at login

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12487]
**Core:** c28345e279f31af2fa32df2411325ccfabe06fc8
**DB:** TDB_full_335.52 + updates

**BUG:**

When you log in or change zones, Hunter pet focus gets set to 0 and slowly recharges back to 100% even if the pet already had 100%.

**Expected:**

When you log in or change zones a pet should have 100% focus if it had 100% focus when you logged out or initiated the zone change.
##

**Comment by Rushor** [comment]
what happens if you resummon the pet?
the focus of the pet also starts with 0 on summon?

**Comment by tkrokli** [comment]
TrinityCore rev. 20ce8cbbc24b 2015-09-14 23:38:21 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates

Both upon login, dismiss + recall (summon) pet and zone change,
the pet needs 12-15 seconds to get focus back from 0% to 100%.

**Comment by Rushor** [comment]
k thx for testing

the last change concerning anything with pet regeneration was in https://github.com/Mack36/NoPalevoCore/commit/db48f90b8b8345a2efa318a1dc09dfafba92c5da

maybe related, maybe not. i'm shure @MrSmite can give more analysis on this, because he knows everything about the pet code :D

**Comment by MrSmite** [comment]
> maybe related, maybe not. i'm shure @MrSmite can give more analysis on this, because he knows everything about the pet code :D

Time to dust off my beer stein, crack my knuckles and code myself into a sweat. Hope my [Iceclaw Bear](http://www.wowhead.com/npc=1196/ice-claw-bear) doesn't mind me mucking around in her AI again.

I'll look into it after I finish breaking the AHBot ;)

**Comment by Rushor** [comment]
kay i tried this, i works, not shure if it's the right position and i'm not shure if it breaks something

```c++
diff --git a/src/server/game/Entities/Pet/Pet.cpp b/src/server/game/Entities/Pet/Pet.cpp
index da745d2..7609d6f 100644
--- a/src/server/game/Entities/Pet/Pet.cpp
+++ b/src/server/game/Entities/Pet/Pet.cpp
@@ -262,6 +262,9 @@ bool Pet::LoadPetFromDB(Player* owner, uint32 petEntry, uint32 petnumber, bool c
     SetReactState(ReactStates(fields[6].GetUInt8()));
     SetCanModifyStats(true);
 
+    if (getPetType() == HUNTER_PET)              
+        SetPower(POWER_FOCUS, GetMaxPower(POWER_FOCUS));
+
     if (getPetType() == SUMMON_PET && !current)              //all (?) summon pets come with full health when called, but not when they are current
         SetPower(POWER_MANA, GetMaxPower(POWER_MANA));
     else
```

**Comment by tkrokli** [comment]
diff on core rev. hash c5cc7cca3e29 is ever so slightly different in line numbers:
```diff
diff --git a/src/server/game/Entities/Pet/Pet.cpp b/src/server/game/Entities/Pet/Pet.cpp
index c9b9c72..28f4123 100644
--- a/src/server/game/Entities/Pet/Pet.cpp
+++ b/src/server/game/Entities/Pet/Pet.cpp
@@ -255,6 +255,9 @@ bool Pet::LoadPetFromDB(Player* owner, uint32 petEntry, uint32 petnumber, bool c
     SetReactState(ReactStates(fields[6].GetUInt8()));
     SetCanModifyStats(true);
 
+    if (getPetType() == HUNTER_PET)              
+        SetPower(POWER_FOCUS, GetMaxPower(POWER_FOCUS));
+
     if (getPetType() == SUMMON_PET && !current)              //all (?) summon pets come with full health when called, but not when they are current
         SetPower(POWER_MANA, GetMaxPower(POWER_MANA));
     else
```
Testing it this weekend, just to confirm that it works, but not sure how to provoke something to break.

**Comment by MrSmite** [comment]
This won't fix the problem when zoning though, the pet is not saved / loaded when you zone.

**Comment by tkrokli** [comment]
OK, so how about making a change in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L3003 like this, either in addition to, or instead of the example above ?
```diff
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 91eb733..7929009 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -2998,11 +2998,11 @@ void Spell::EffectSummonPet(SpellEffIndex effIndex)
     Pet* OldSummon = owner->GetPet();
 
     // if pet requested type already exist
     if (OldSummon)
     {
-        if (petentry == 0 || OldSummon->GetEntry() == petentry)
+        if ((petentry == 0 || OldSummon->GetEntry() == petentry) && OldSummon->getPetType() == HUNTER_PET)
         {
             // pet in corpse state can't be summoned
             if (OldSummon->isDead())
                 return;

**Comment by MrSmite** [comment]
@tkrokli 

In the past I was able to fix this by modifying calls to SetPower(). However there don't appear to be any direct calls to *SetPower()* other than from *setPowerType()* which is called when the pet is loaded.

```C++
SetPower(POWER_FOCUS, uint32(std::ceil(GetCreatePowers(POWER_FOCUS) * powerMultiplier));
```

Everything else calls things like *Regenerate()* and *ModifyPower()*.

**Comment by tkrokli** [comment]
@Mihapro :
👍 Thank you! Finally we get to summon pets without having to wait for 100% power! 😄
```
TC>server debug
TrinityCore rev. 0c1e485e13d0 2018-03-07 04:19:06 -0300 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
TC>_
```
