### ISSUE TITLE
[335] Player takes melee damage while outside melee range (video)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12491]
**Core:** c28345e279f31af2fa32df2411325ccfabe06fc8 (though it's been around for a couple years as I reported in #7545)
**DB:** TDB_full_335.52 + updates
**OS:** Win7

**BUG:**

While at 20 yard+ range, players can still be hit with melee damage from NPCs.

**Details:**

[Hunter Takes Melee Damage At Range (YouTube)](https://www.youtube.com/watch?v=8JzP4ovN6zQ)
- First example is at approx. 11 seconds
- Second example is at approx 35 seconds

I reported this bug back in 2012 (see issue link above at _core_) where I initially thought this might be due to the slow from Concussive Shot. Since the original report is extremely old, I've updated my core, updated my OS and have a video, I'm creating this new report showing it is not related to movement impairing effects at all.

**Notes:**
- It doesn't hapen all the time
- So far I've only had it happen with Humanoid NPCs
- It happens most often with the Gnolls seen in the video though Orcs (Lakeshire) and Defias (Westfall) can also do it
- Although not shown in the video, NPCs can also do this if a pet kills them while they're fleeing, you will take one last hit as they die
- Each time it happens the player gets hit twice. Note that the Gnolls in the video do not have a "double attack" special or any ranged ability, it's basic melee hitting twice.
- This also happens to Warlocks
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 0725f60
