### ISSUE TITLE
[3.3.5]Problem: creature has team aura doesn't effect other creatures

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12490]
db : up-to-date
core : 9506fd77fcb560c2f6aeb6830fb7e32e6c813027

If a creature which can offer the team Aura. The Aura only effect himself, not the other creatures around with the same faction.

For example
If I insert smart_scripts somedata to let creature 1665 to cast 8258 when it respawn or out of combat,
the spell doesn't affect the creature 1660 (just near the creature 1665).

If I am wrong, what do I miss? Put the creature's guid in some database table? CreatureFormation or what?
Thanks for the help
##

**Comment by Killyana** [comment]
Works correctly on rev. 95d298780010
