### ISSUE TITLE
[Quest] Elekks Are Serious Business [$15]

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#12518]
you can collect quest and the quest asks you to speak with Vorkhan the Elekk Herder and you go to him and he has a grey ? mark but can't hand in quest and no gossip either.
 
http://www.youtube.com/watch?v=0wQhUDeNAfI

http://wotlk.openwow.com/quest=9625

![wowscrnshot_071614_160327](https://cloud.githubusercontent.com/assets/5343324/3595130/bd9cb2d8-0caf-11e4-8c9e-9e9cd2040544.jpg)
![wowscrnshot_071614_160339](https://cloud.githubusercontent.com/assets/5343324/3595133/c7de7916-0caf-11e4-9398-54252815c95f.jpg)

Core 9506fd77fcb560c2f6aeb6830fb7e32e6c813027

DB  335.54_2014_07_05 

Addons -- ahbot

**Comment by Pirricli** [comment]
@dr-j, Why your fix is not pushed?

**Comment by djbeauchamp** [comment]
@dr-j It would be nice to see this change pushed to the core, and there's a bounty to collect.

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=17584;
DELETE FROM `smart_scripts` WHERE `entryorguid`=17584 AND `source_type`=0 AND `id`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(17584, 0, 0, 0, 19, 0, 100, 0, 9625, 0, 0, 0, 11, 30781, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Torallius the Pack Handler - On Quest Accept - Cast credit spell 30781');
