### ISSUE TITLE
[Bug]The offerrewardemote in quest_template don't work when creature_addon byte1 is 7 

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12517]
db up to date
core e373f75ceb0651f1a17316369d3be6710eb6431c

As the title says, the offerrewardemote in quest_template don't work when creature_addon byte1 is 7 (when reward the quest, nothing happens, the npc will not play any action or emote).

Naturally, we try to fix this in smart_scripts. But you'll find The npc still do nothing when event_type is 20, and action_type is 5. So we must remove the byte1 (value is 7) temp, and set the value back again soon in smart_scripts. It's strange, the npc will standup instant, do something, and be killed again...

If we fix this problem, we can just fill the rigth value into offerrewardemote (in table quest_template) instead of write a lot of complex smart scripts for the creature. SAI is great, but I think we shouldn't use it everywhere, It effects the server's performance.
#12511 this issue is closed, but not fix correctly

proof   https://www.youtube.com/watch?v=0ZRoyrI1p9I&feature=player_detailpage#t=316  (Thanks @Rushor)

I'm very sorry for my harsh , and sorry for my description in #12551 is not correct. And this fix is not complete right. the npc should kneel for a few second and lay down again( not die again... the action should be simalar as you input /sleep in game, not be killed)

Another quest like this is 9148, when accept the quest, the npc should stand for a while and lay down again.

By the way, at the moment, a lot of quest has EmoteOnComplete in quest_template table, but in fact, the emote should set to OfferRewardEmote. I'll fix them one by one, but It need much time. : )
##

**Comment by tkrokli** [comment]
@kldxzzhc2 : did you ever test @dr-j 's script in #12511 (script copy below) ?
```sql
UPDATE `creature_template` SET AIName='SmartAI' WHERE `entry`=3287;
DELETE FROM `smart_scripts` WHERE (`entryorguid`=3287 AND `source_type`=0);

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(3287, 0, 0, 1, 20, 0, 100, 0, 790, 0, 0, 0, 91, 7, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Quest reward Sarkoth  - Set Bytes 1'),
(3287, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Quest reward Sarkoth  - Store Targetlist'),
(3287, 0, 2, 3, 61, 0, 100, 0, 0, 0, 0, 0, 66, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Quest reward Sarkoth  - Face Player'),
(3287, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 22, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Quest reward Sarkoth  - Set Phase 1'),
(3287, 0, 4, 5, 1, 1, 100, 0, 1000, 1000, 1000, 1000, 90, 8, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - OOC (Phase 1)  - Set Bytes 1'),
(3287, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 1, 0, 60000, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 'Hana zua - OOC (Phase 1)  - Set Say Line 0'),
(3287, 0, 6, 0, 61, 0, 100, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - OOC (Phase 1)  - Set Phase 0'),
(3287, 0, 7, 8, 52, 0, 100, 0, 0, 3287, 0, 0, 91, 8, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Text Over Line 0  - Set Bytes 1'),
(3287, 0, 8, 0, 61, 0, 100, 0, 0, 0, 0, 0, 90, 7, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Hana zua - On Text Over Line 0  - Set Bytes 1');

DELETE FROM `creature_text` WHERE `entry`=3287;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) VALUES 
(3287, 0, 0, 'Go swiftly, $n. My fate is in your hands.', 12, 1, 100, 0, 0, 0, 'Hana zua', 1341);
```
Not sure why Rushor added the MaNGOS script underneath it in the other issue.

**Comment by offl** [comment]
> proof https://www.youtube.com/watch?v=0ZRoyrI1p9I&feature=player_detailpage#t=316

It is not a proof. Everything you can see in this movie is scripted event. It is not offer reward emotes or something from quest templates.

> Another quest like this is 9148, when accept the quest, the npc should stand for a while and lay down again.

Again, it is an event.

It is not a bug. Most of creatures with bytes1=7 are dead, so they can't play any emote. Other too doesn't play emotes from quest templates.

**Comment by Killyana** [comment]
So this could be closed?

**Comment by offl** [comment]
Yep.
