### ISSUE TITLE
Creatures under textures

### ISSUE THREAD

**Issue by H4D3S** [TrinityCore/TrinityCore#12525]
After last update, we have found some npc under textures Stormwind, the vmaps and mmaps were generated a week ago :/

https://imageshack.com/i/ip53a52fj
https://imageshack.com/i/knd12f64j
https://imageshack.com/i/pcb2d261j
https://imageshack.com/i/p56d38a7j
https://imageshack.com/i/pc4028fcj

hash: 3249986ba8d49108cc3b58a2db092ab940480ebf
mmaps and vmaps ON

**Comment by Killyana** [comment]
Cannot reproduce on rev. 0148832b322b
.go -8649.382813, 760.658691, 59.455872 And I cannot see any npc around.

**Comment by MrSmite** [comment]
> Sewer Beast: 3581

Not really a good example since there are multiple spawns which in itself is incorrect. The Sewer Beast is supposed to be a "rare elite" that spawns randomly in the canal and swims around.

**Comment by Rushor** [comment]
so anyone can post other examples in order to reproduce the bug?

**Comment by Rushor** [comment]
> Cannot reproduce on rev. 0148832b322b

some on https://github.com/TrinityCore/TrinityCore/commit/6ca400b35eb44ed1392fdab093f521ee4787a63b
