### ISSUE TITLE
[Bug]Surveyor Candress

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12528]
Bugs:
1. She doesn't cast the cosmetic spell upon "Red Crystal Bunny".
2. The spell which "Red Crystal Bunny" casts upon "Surveyor Candress" isn't visible unless you are a gm, kill the bunny and respawn it.
3. The red crystal doesn't disappear after you engage with her.
4. Surveyor Candress doesn't go after you after casting her first "Fireball", unless you actually go near her. Her fireball should also be delayed for at least 3 seconds after you engage with her.

Cosmetic spells used unknown.

Links:
Surveyor Candress - http://www.wowhead.com/npc=16522
Red Crystal Bunny - http://www.wowhead.com/npc=17947
Vid 1. - https://www.youtube.com/watch?v=Jc4BiOBMAsw
Vid 2. - https://www.youtube.com/watch?v=Zazznzjq3m4

Core revision: 0f0cea1

**Comment by Killyana** [comment]
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=16522 AND `id`=12;
UPDATE `smart_scripts` SET `action_param1`=1 WHERE `entryorguid`=16522 AND `id`=0;
UPDATE `smart_scripts` SET `event_phase_mask`=1 WHERE entryorguid=16522 AND `id`=5;
UPDATE `smart_scripts` SET `event_phase_mask`=0, `event_flags`=0 WHERE `entryorguid`=16522 AND `id`=6;
UPDATE `smart_scripts` SET `event_phase_mask`=0 WHERE `entryorguid`=16522 AND `id`=7;
UPDATE `smart_scripts` SET `event_phase_mask`=2 WHERE `entryorguid`=16522 AND `id`=11;
UPDATE `smart_scripts` SET `event_phase_mask`=1, `action_param1`=1 WHERE entryorguid=16522 AND `id`=9;
UPDATE `smart_scripts` SET `event_flags`=1 WHERE `entryorguid`=16522 AND `id`=2;
UPDATE `creature_template` SET `InhabitType`=4 WHERE `Entry`=17947;
