### ISSUE TITLE
[Bug] Unable to loot nodes/chests

### ISSUE THREAD

**Issue by Sidious78** [TrinityCore/TrinityCore#12539]
This bug is easy to replicate, and applies to at least treasure chests and mining nodes:

If you farm a node or a chest from the maximum allowable distance, the node or chest will state that "This item is already being used.", and you will be unable to loot those chests/nodes.

Core: 8edecb0
DB: 335_54
##

**Comment by Rushor** [comment]
reduce INTERACTION_DISTANCE to 3.0f will fix most of the issues

**Comment by Aokromes** [comment]
Blizzlike bug, but on retail they self fix after few seconds.

**Comment by Rushor** [comment]
another way to reproduce this is following:
- get in combat with a creatue
- start looting a chest
- get hit by creature while the chest bar is casting

 result:
"This item is already being used.", and you will be unable to loot those chests/nodes.

**Comment by dobrMAN** [comment]
> get hit by creature while the chest bar is casting
It is other bug.

> reduce INTERACTION_DISTANCE to 3.0f will fix most of the issues
It is don't fix, for fix you need **increase** INTERACTION_DISTANCE defenition. For chests it can be 5.2f enough,  but for larger GOs may require the value of 10.0 or more. In this, I proposed to take into range calculation scale of objects.

**Comment by Killyana** [comment]
Fixed with https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7
