### ISSUE TITLE
Zeppelin from Orgrimmar to Thunderbluff

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#12530]
Rev: 524cc6c2d93edfff6262aa4f6c1abadd9ab26e9d (fresh compile)
DB: TDB Full 4.3.4 v6 + updates
- Take a fly from Orgrimmar to Thunderbluff by Zeppelin
- Wait till airship arrives to Mulgore
- Just after that, loading screen appears and you got ported to higher point (X: -934.514282 Y: 494.619263 Z: 294.134277 Orientation: 5.027783)
- You fall down & die.
##

**Comment by tomm7** [comment]
This seems to work fine in 6.xx

**Comment by malcrom** [comment]
I just got teleported to Ghostlands from the goblin airship in twilight highlands.

**Comment by Golrag** [comment]
Tried: https://github.com/TrinityCore/TrinityCore/commit/935c93e099f534f701ff8787204ce19be2ed2df2
got teleported in the zeppelin: http://puu.sh/kSIwf/05926e263b.jpg

**Comment by Shauren** [comment]
@Golrag 935c93e099f534f701ff8787204ce19be2ed2df2 only fixes the cases like @malcrom reported, not this issue.

**Comment by Aokromes** [comment]
463b943
