### ISSUE TITLE
[Bug]Sten Stoutarm missing flavour text.

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12541]
Bug:
Upon talking to "Sten Stoutarm", he doesn't say "Ah, well aren't you a sturdy-looking one! Perhaps you can assist me with a thing or two. Not much help around here except for green apprentices, and they've other things to worry about."

Links:
Sten Stoutarm - www.wowhead.com/npc=658
Vid(3:00) - https://www.youtube.com/watch?v=Gv-QkC6_HiI

Core revision: 0f0cea1

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET npcflag=3, `gossip_menu_id`=4047 WHERE `entry`=658;
DELETE FROM `gossip_menu` WHERE `entry`=4047;
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (4047, 4937);
