### ISSUE TITLE
locales Gossip 

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#12546]
The gossip menu option 'I wish to know about Dual Talent Specialization.' is never shown in a localized language.

Even not if there is a valid record in the locales_gossip_menu_option table.

Examples: Horde npc 3042 / Alli npc 912

**Comment by danlapps** [comment]
Is this an "issue" of TC or just localization strings missing ?

**Comment by tkrokli** [comment]
@danlapps : notice that Aokromes correctly renamed the issue like this:
> **Aokromes** changed the title from **[3.3.5a]Gossip Dual Talent Spec** to **locales Gossip** on 6 Oct 2014

As I understand it, this should mean that the issue is still valid because it has to do with the `locales_gossip_menu_option` for the `npc_pet_trainer` like Killyana also commented above.

**Comment by Killyana** [comment]
WIP
```
UPDATE gossip_menu_option SET optionBroadcastTextId=33762 WHERE menu_id IN (4007, 4534, 4092, 4621, 4694, 4826, 4674) AND  id=2;

**Comment by Killyana** [comment]
Moved to https://github.com/TrinityCore/TrinityCore/issues/14716 as related.
