### ISSUE TITLE
[Bug]Talin Keeneye missing flavour text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12553]
Bug:
Talin Keeneye doesn't say "Greetings, %c! Fine day for hunting, wouldn't you say? I've been having more than a little luck with boars, myself. Perhaps you'd like a shot?" upon talking to him.

Links:
Talin Keeneye - http://www.wowhead.com/npc=714
Vid 1(1:45) - https://www.youtube.com/watch?v=qzbzSv-j7oo
Vid 2(0:55) - https://www.youtube.com/watch?v=fdfMeIlvn_o

Core revision: 0f0cea1

**Comment by Killyana** [comment]
No gossip or npc_text for this npc, also the npc_flag=2.
rev. 35f2f5530abc
