### ISSUE TITLE
[Bug]Grelin Whitebeard flavour text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12554]
Bug:
Upon talking to Grelin Whitebeard he doesn't say "Greetings, lad/lass. I'm Grelin Whitebeard. I'm here to examine the threat posed by the growing numbers of trolls in Coldridge Valley. What have I found? It's a bit troubling..."

Links:
Grelin Whitebeard - www.wowhead.com/npc=786
Vid(2:40) - https://www.youtube.com/watch?v=qzbzSv-j7oo

Core revision: 0f0cea1

**Comment by Killyana** [comment]
The actual text is: "The trolls are acting strangely, $n.  I don't like it.  I don't like it one bit."
Probably changed by blizz.
