### ISSUE TITLE
[Quest]Problem about quest [Investigate the Alchemist shop]  

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12561]
DB up-to-date
Core fbccc58f4a7272abe7a4aff33f3eef8ede813fd5

At the moment, this quest is fixed in #9717. Thanks @dr-j and @Rushor 's great job.
But I think there still 3 problems:

1.The spell 9082 can only cast when near creature 6492, and the creature has aura 9032 (stun)
2.The spell 9082 should only cast to creature 6492 which has aura 9032 
3.The creature 6492 has aura 9032 exist time too short, the smart_scripts comment says exists 30 second, but in fact, only 8 seconds. This maybe because creature enter evade mode.

Can someone confirm it? :)

PS: I didn't finish the quest in offcial server, so this is just my guess

this sql resolves problem 2

``` sql
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES (13,1,9082,0,0,1,0,9032,0,0,0,0,0,'',NULL);
```

I cann't fix problem 1 by using conditions, cause SourceTypeOrReferenceId 17 only effect the target selected by player, but the creature 9032 not selectable when stun.
##

**Comment by danlapps** [comment]
Aok or Rushor, Is this a valid fix or a hack ? Cause issue name labeled as "fixed" but still open.

**Comment by Rushor** [comment]
like dr-j said:

```sql


the only real issue is you can use the crate if mana rift is not stunned, the spell duration is 30 seconds but player must stay in combat for duration of this otherwise npc evades.

And you do know theres a missing trap object which is needed to fix this quest properly namely object 103575 type 6 trap which is set as data3 (linked trap) on the containment coffer object but does not exist in db.
```

nothing else has to be changed, a using c++ for a quest is always a bad idea since sai has been improved to perfection

**Comment by Killyana** [comment]
Dup
