### ISSUE TITLE
[Bug 434] hunter pet without correct icon

### ISSUE THREAD

**Issue by gpn39f** [TrinityCore/TrinityCore#12572]
core:  abe8dd7
DB:    TDB_full_434.06_2014_07_05 + core updates
OS:    Win 7 64 bit

i startet fresh compile core today, insert boost, loaded last db from Vincent-Michael, imported core updates.. 
I started new player as human hunter but my pet has a wrong icon..
##

**Comment by Killyana** [comment]
Cannot reproduce.
