### ISSUE TITLE
[Bug]Shadra'Alor Altar

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12571]
Bug:
Shadra'Alor Altar is visible, it should be invisible.

Links:
Shadra'Alor Altar - http://wotlk.openwow.com/object=142716
Vid 1 - https://www.youtube.com/watch?v=qBByxsQQcOQ
Vid 2 - https://www.youtube.com/watch?v=VxFBzIGgvD8

Core revision: 1866d8c

**Comment by danlapps** [comment]
Would changing the phasemask to 0 fix the problem ?

**Comment by Killyana** [comment]
I don't understand what must be invisible here.

**Comment by danlapps** [comment]
me neither GO not listed anywhere, just going with the issue ...

**Comment by Rushor** [comment]
http://pokit.org/get/?55833a47cf4547fa34e4612933087a62.jpg nothing is visible here

.go object 99875 - u cannot see anything
.gobj add temp 142716 - u cannot see anything

closing for now
