### ISSUE TITLE
TALENT Bloodworms DeathKnight

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#12589]
Bloodworms hits to low 30 between 150

Talent Rank 1 49027
Talent Rank 2 49542
Talent Rank 3 49543

Rev: 2b88b4906292b5d51515e1b84a98ccbcf7603449
##

**Comment by Keader** [comment]
Ticket without good informations.
If still valid, please someone open a new ticket with information about it.
Thanks.
