### ISSUE TITLE
Hunter Pet HP

### ISSUE THREAD

**Issue by sextonolsen** [TrinityCore/TrinityCore#12593]
The Hunter pet talent "Wild Hunt" changes the pet HP, but in order for me to see it, I must take my armor all the way and put it back on. Should I mount or change zones, my pet HP goes back to normal as if the talent were not in place.

Core: 29e6765
DB: TDB_full_335.54_2014_07_05.7z

**Comment by Keader** [comment]
Try This: https://github.com/TrinityCore/TrinityCore/issues/6709#issuecomment-147274010

work for me

**Comment by Rushor** [comment]
already reported in https://github.com/TrinityCore/TrinityCore/issues/6709#issuecomment-147274010 and https://github.com/TrinityCore/TrinityCore/issues/873
