### ISSUE TITLE
[335] NPC Pets should not have instant aggro at unlimited range

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12594]
**Core:** https://github.com/TrinityCore/TrinityCore/commit/c28345e279f31af2fa32df2411325ccfabe06fc8
**DB:** TDB_full_335.52 + updates

**Bug:**

When you initiate combat on an NPC with a pet from ranged using "pet attack" the NPC's pet will aggro instantly even though the NPC does not.

**Details:**

NPC pets should be the same as Hunter pets. They should not aggro as soon as you click "pet attack" but rather only when you or your pet get within aggro range.

**Notes:**

To reproduce:
- Go to Longshore in Westfall
- Stand 50 yards away from a [Murloc Hunter](http://www.wowhead.com/npc=458)
- Click your "pet attack" button
- Notice the Murloc's Crab pet aggros instantly (the Murloc does not)

These pets should not aggro until your pet gets withing aggro radius.
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 0725f608a
