### ISSUE TITLE
[335] 'Slow' effects seem to be ignored by swimming mobs

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12595]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/c28345e279f31af2fa32df2411325ccfabe06fc8
__DB:__ TDB_full_335.52 + updates

__Bug:__

When you cast a slowing effect on a swimming mob, the mob's speed is not changed

__Details:__

After casting [Concussive Shot](http://www.wowhead.com/spell=5116) on a [Murloc Warrior](http://www.wowhead.com/npc=171) that was fleeing in the water, the slow effect from Concussive shot did not actually have any effect on the NPC's swim speed.

**Comment by Aokromes** [comment]
b0e7b45

**Comment by MrSmite** [comment]
> b0e7b45

@Aokromes  I don't think that PR is relevant. Concussive Shot is a slow, not a root or stun. In the case in my OP, the mob was already fleeing and I cast a slow. The slow has no effect when fleeing in water (eg: swimm speed), it only seems to work on land (eg: run speed).
