### ISSUE TITLE
[Bug]Tannok Frosthammer missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12612]
Bug:
While turning in "Supplies to Tannok" to "Tannok Frosthammer", he says "Greetings name". Correct text is unknown.

Links:
Supplies to Tannok - http://www.wowhead.com/quest=2160
Tannok Frosthammer - http://www.wowhead.com/npc=6806

Core revision: 1866d8c

**Comment by Killyana** [comment]
The npcflag is 2 so no gossip.
