### ISSUE TITLE
[Bug]Gnome Engineer missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12619]
Bug:
Gnome Engineers are missing their flavor text.

Links:
Gnome Engineer - http://www.wowhead.com/npc=13000

Core revision: 1866d8c

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `gossip_menu_id`=21212 WHERE `entry`=13000;

**Comment by Grz3s** [comment]
hey @Killyana :
is that `gossip_menu_id`=21212 a sniffed id? or it is TDB?
thx

**Comment by Killyana** [comment]
The gossip menu 21212  is used by 4430, but as the npc_text is the same for the Gnome Engineers I updated also for them.
