### ISSUE TITLE
[Bug]Loslor Rudge missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12614]
Bug:
This little dwarf only greets me upon talking to him and not having accepted "Ammo for Rumbleshot".

Links:
Loslor Rudge - www.wowhead.com/npc=1694
Ammo for Rumbleshot - http://www.wowhead.com/quest=5541

Core revision: 1866d8c

**Comment by Rushor** [comment]
no longer sniffable, because on retail he instantly shows this vendorstuff, the quest was removed, so the gossip was removed.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `gossip_menu` WHERE `entry`=3501 AND `text_id`=4253; 
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (3501,4253);
UPDATE `creature_template` SET `gossip_menu_id`=3501 WHERE `entry`=1694;
