### ISSUE TITLE
[Bug]Dun Morogh Mountaineer missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12620]
Bug:
Dun Morogh Mountaineers are missing flavor text.

Links:
Dun Morogh Mountaineer - http://www.wowhead.com/npc=13076

Core revision: 1866d8c

**Comment by Killyana** [comment]
Wrong npcflag:
``` sql
UPDATE `creature_template` SET `npcflag`=0 WHERE `entry`=13076;
