### ISSUE TITLE
[Bug]The Farstrider Lodge flavor texts

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12623]
Bug:
Few flavor texts don't change from Marek Ironheart and Vyrin Swiftwind after a few quests in Farstrider Lodge are completed.

Npc_text 3522, 3523, 3525 belong to Vyrin Swiftwind.

3523 is used correctly.
3522 unknown condition, probably, "Vyrin's Revenge(271)" needs to be completed.
3525 should be offered after "Vyrin's Revenge(531)" is completed.

Npc_text 3494, 3495 belong to "Marek Ironheart"

3494 is used correctly
3495 unknown conditions, probably, "Vyrin's Revenge(531)" and "Crocolisk Hunting" need to be completed.

Npc_text 3493 is used by an unknown npc, though probably "Marek Ironheart" after "A Hunter's Challenge" and "Crocolisk Hunting" are completed.

Links:
Crocolisk Hunting - http://www.wowhead.com/quest=385
A Hunter's Challenge - http://www.wowhead.com/quest=258
Vyrin's Revenge - http://www.wowhead.com/quest=271
Vyrin's Revenge - http://www.wowhead.com/quest=531
Marek Ironheart - http://www.wowhead.com/npc=1154
Vyrin Swiftwind - http://www.wowhead.com/npc=1156

Core revision: 1866d8c

**Comment by Rushor** [comment]
working on current rev:

```sql
DELETE FROM `gossip_menu` WHERE `text_id` IN (3522, 3525, 3495);
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES 
(2831, 3522),
(2831, 3525),
(2801, 3495);

--
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceEntry` IN (3522, 3525, 3495) AND `ConditionTypeOrReference`=8;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(14, 2831, 3522, 0, 0, 8, 0, 271, 0, 0, 0, 0, 0, '', 'Show gossip text if player has quest 271 completed'),
(14, 2831, 3525, 0, 0, 8, 0, 9305, 0, 0, 0, 0, 0, '', 'Show gossip text if player has quest 531 completed'),
(14, 2801, 3495, 0, 0, 8, 0, 531, 0, 0, 0, 0, 0, '', 'Show gossip text if player has quest 9305 completed');
```

we will no longer get informations to the other stuff so..
