### ISSUE TITLE
[VEHICLE] Jotunheim Rapid-Fire Harpoon

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1263]
this vehicle spells don't work.
http://www.wowhead.com/npc=30337

spell1=56585
spell2=56570

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Rushor** [comment]
there is already an issue for this: https://github.com/TrinityCore/TrinityCore/issues/4207

current situation:
http://pokit.org/get/?e9047fdd566ff4a950806be03093eb8b.jpg - if i spammklick  ability 2, i can kill myself and the vehicle

http://pokit.org/get/?b0b7de427bd0d32095c06aeac9118ebf.jpg sometimes the npcs will be hittet by the dmg of the spell, but the npcs instantly regenerate health (with gm mod off)

**Comment by Aokromes** [comment]
Closing this then because more updated situation on #4207
