### ISSUE TITLE
[Bug]Rejold Barleybrew missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12648]
Bug:
Rejold Barleybrew is missing flavor text.

Links:
Rejold Barleybrew - http://www.wowhead.com/npc=1374
Vid(9:50) - https://www.youtube.com/watch?v=VTqaqFsQzcw

Core revision: 1866d8c

**Comment by Killyana** [comment]
On sniffs the npc don't have a gossip menu.
