### ISSUE TITLE
[Bug]Guarded Thunder Ale Barrel missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12649]
Bug:
"Guarded Thunder Ale Barrel" is missing flavor text. "This barrel of ale is guarded by Jarven Thunderbrew.  As long as he's in the basement, no barrels may be disturbed."

Links:
Guarded Thunder Ale Barrel - http://www.wowhead.com/object=269

Core revision: 1866d8c

**Comment by Killyana** [comment]
``` sql 
DELETE FROM `gossip_menu` WHERE `entry`=9027 AND `text_id` IN (12198); 
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (9027,12198);
