### ISSUE TITLE
[Trinket] Flare of the Heavens does not procc off Mind Flay

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1266]
The Trinket (item 45518) does not procc Flame of the Heavens (spell 64714) through Mind Flay (shadow priest, channeling).

This makes it totally useless as Mind Blast and SW:D are the only spell casts it is currently able to proc off.

Core: 11190
TDB 335.11.36
##

**Comment by ariel-** [comment]
Is the issue valid? https://github.com/TrinityCore/TrinityCore/issues/1266#issuecomment-3563094

**Comment by Keader** [comment]
No answers... so closing.
