### ISSUE TITLE
[Core/Duel] Companion pet can be killed by player

### ISSUE THREAD

**Issue by MitchesD** [TrinityCore/TrinityCore#12665]
Rev.: 30e1342048028ee07d5241e5a20f516eceb7210e
TDB 335.54 + updates

During the duel, you are able to kill companion pet of your enemy

**How to reproduce:**
During the duel, use some AOE ability/spell, NPC becomes the enemy and you can kill him. Tested with Death and Decay (Death Knight), Bladestorm (Warrior)
##

**Comment by click** [comment]
Copied from @Eliminationzx's pastebin in case it disappears:
'''
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 0ee494d..125e5f7 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -2290,7 +2290,8 @@ void Spell::EffectSummonType(SpellEffIndex effIndex)
                     summon->SelectLevel();       // some summoned creaters have different from 1 DB data for level/hp
                     summon->SetUInt32Value(UNIT_NPC_FLAGS, summon->GetCreatureTemplate()->npcflag);
 
-                    summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
+                    //summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
+                    summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
 
                     summon->AI()->EnterEvadeMode();
                     break;
'''

**Comment by Aokromes** [comment]
If it's valid, anyone can create apr for this?

**Comment by SnapperRy** [comment]
Can't reproduce, tried various companion pets and AoE spells, wasn't able to kill the companion pet.

Anyone knows a valid combination, or was this already fixed?

**Comment by tkrokli** [comment]
Maybe there has been some `unit_flag` updates to `creature_template` during the last year or in 2015.

**Comment by Wyrserth** [comment]
Can't reproduce, tried AOE spells as well as Killing Spree on duels with characters from the same faction and from different factions. Result is all the same, can't kill the companion pet.
