### ISSUE TITLE
[Item/49278] Goblin Rocket Pack

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#12678]
The item http://www.wowhead.com/item=49278 must be removed outside of ICC

Rev: 2b88b49
##

**Comment by Aokromes** [comment]
Conditions can fix this?

**Comment by Killyana** [comment]
No we cannot remove items via conditions.

**Comment by Aokromes** [comment]
Na, not remove, instead don't allow to use.

**Comment by Killyana** [comment]
It's already the case.

**Comment by Kittnz** [comment]
An item script would resolve the issue.

**Comment by Rushor** [comment]
someone know how this behaves on retail?

if the item must be removed if the player leaves the instance, it will be the same mechanic like special items in ZA

**Comment by Kittnz** [comment]
Special items in ZA?

**Comment by Rushor** [comment]
that one http://de.wowhead.com/item=33865/hexerstecken-der-amani

In order to release the frogs from their curse, you need to gather Amani Hex Sticks from the trash mobs inside the instance. These Amani Hex Sticks will revert the frogs back to humanoid form. You must use the Amani Hex Sticks before you die or leave the instance. If you die, leave, or logout all of your Amani Hex Sticks will dissapear. So use them as you get them to be safe.
http://coldsgoldfactory.blogspot.de/2010/10/sealed-scroll-case-from-zulaman.html

**Comment by Kittnz** [comment]
Well it won't disapear on death or logout.

**Comment by Rushor** [comment]
for specific instances we could also add a OnPlayerRemoved script similar to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Instances/InstanceScript.h#L186

```c++
void OnPlayerRemove(Player* player) 
{
      player->RemoveAura(73077); // Goblin Rocket Pack
      player->DestroyItemCount(49278, 1, true); // Goblin Rocket Pack
}
```

and add this peace of code in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp#L184

**Comment by Kittnz** [comment]
Sounds like a plan, add it! :+1:

**Comment by offl** [comment]
> but there should be a condition .. if player died he and runs in he should still have the pack. so
if(hasaura(deathaura))
{..} bla bla

1 Talk to Spirit Healer
2 Ressurect
3 The item is still in your inventory

What about these spells?
http://www.wowhead.com/spell=70713/remove-rocket-packs
http://www.wowhead.com/spell=70348/rocket-pack-useable

**Comment by Killyana** [comment]
(70348,'spell_igb_rocket_pack_useable'), scripted and works correctly.
http://www.wowhead.com/spell=70713/remove-rocket-packs has: Script Effect - Value: 49278=Goblin Rocket Pack, so it's the one that must be used to remove the item if the map ID is not ICC.

**Comment by CraftedRO** [comment]
b7471244adb08f112214634b27d7daf2da19aa0f Somehow still valid but in my tests this doesn't give any stats or benefits while out of ICC so probably only cosmetic, still need a test on retail if it's removed or not when die or logout or whatever.

**Comment by Aokromes** [comment]
it can't even used outside ship, at least after killing it.

**Comment by Aokromes** [comment]
also, at least on ptr aint removed on exit from instance.

![Y0CxuSU 1](https://github.com/user-attachments/assets/6603e871-020e-4efd-b737-109d4d8a3403)
