### ISSUE TITLE
[Raid][The frozen throne] Infinite fall

### ISSUE THREAD

**Issue by bonny1992** [TrinityCore/TrinityCore#12698]
- Revision: a15c8af
- DB: TDB 335.54+
- Boost: 1.55.0
- Operating System: Windows 8.1 Pro

Issue:
Simply if the Lich King makes you fall from the tower, you keep falling forever.

I have made a video showing the fall (LK already killed):
https://www.youtube.com/watch?v=TkBzJrO-DbI&list=UU5mHcvTSwt8d95Ac2G_K1ug
The rest of the raid works like a charm.
I don't know if it's meant to go this way, but I had to open up server window and then "unstuck" me.

**Comment by Zedron** [comment]
correct me if I'm wrong, but i believe on blizz if you fall below a certain point (on all maps), it will kill you.. This currently doesn't work on TC. Eye of the Storm is another example of where this happens in blizz but doesn't happen on TC.

**Comment by bonny1992** [comment]
Yeah, that's correct, it should kill you, but instead you keep falling 
Il 17/mar/2015 17:21 Zedron <notifications@github.com> ha scritto:correct me if I'm wrong, but i believe on blizz if you fall below a certain point (on all maps), it will kill you.. This currently doesn't work on TC. Eye of the Storm is another example of where this happens in blizz but doesn't happen on TC.

**Comment by lendan** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/MovementHandler.cpp#L385

**Comment by lainimer** [comment]
any news?

**Comment by Aokromes** [comment]
No.

**Comment by Demonid** [comment]
Still bugged on 56b27711a4db7b56c5e6246426c89cd99e8c8cd4

On retail it works like this: https://www.youtube.com/watch?v=G3OUjUDH9Vg

**Comment by Shauren** [comment]
Fixed in 4f78efd4633f79285f176b61367a067b2cd90e2b - soon in 3.3.5

**Comment by Demonid** [comment]
@Shauren Gj :+1:
