### ISSUE TITLE
Core/Spell: Hex of Jammal'an

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12705]
rev 74d11ca

http://de.wowhead.com/spell=12479
http://www.wowhead.com/spell=12480#screenshots

npc=5710 sometimes casts spell 12479.
First problem:

if this spell(12479) is removed, the player should cast 12480 on hisself.
His could be handeled with spell_linked_spell.

Second problem:
if you have the spell/aura 12480 you should be charmed and become friendly towards npc=5710. this charmeffect does not work. moreover u are still hostile towards npc=5710.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (12479, 12480, -12480)  AND `spell_effect` IN (12480, 530, -530);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`)  VALUES 
(12479, 12480, 0, 'Hex of Jammal''an'),
(12480, 530, 0, 'Hex of Jammal''an'),
(-12480, -530, 0, 'Hex of Jammal''an');

UPDATE `smart_scripts` SET `event_type`=0, `Comment`= "Jammal'an the Prophet - In combat - Cast 'Hex of Jammal'an' (Phase 1)" WHERE `entryorguid`=5710 AND `source_Type`=0 AND `id`=5;
