### ISSUE TITLE
[Bug]Tharek Blackstone missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12710]
Bug:
Tharek Blackstone is missing flavor text.

Links:
Tharek Blackstone - www.wowhead.com/npc=1872
Pic - http://i.imgur.com/8ANL2c8.jpg

Core rev: b5f0b85b485e0309a952150265b5349124070b59

**Comment by Killyana** [comment]
No gossip menu for this npc on sniffs.

**Comment by danlapps** [comment]
Unable to sniff since quest is now removed from game.

Is there a pre-existing sniff ?

**Comment by Kittnz** [comment]
It's just gossip text that is missing.

**Comment by danlapps** [comment]
I mean since he doesnt give quest, I cannot right click to talk to him at all.  He is like any random NPC, no more right-clickable on retail

**Comment by Killyana** [comment]
npcflag=2 so no gossip for this npc.
