### ISSUE TITLE
[3.3.5][SAI]Fix SAI about creature 16924 and 16916

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12727]
core: 4f9b57eddfdb12219b338848a4393171a5d383ef
db:up-to-date

Now they can really speak to each other. :)

```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`='16924' OR `entryorguid`='16916'
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(16916,0,0,0,1,0,100,0,2000,2000,10000,10000,5,20,0,0,0,0,0,1,0,0,0,0,0,0,0,'Wretched Captive - Out of Combat - Play Emote 20 (No Repeat)'),
(16916,0,1,2,38,0,100,0,1,1,0,0,5,18,0,0,0,0,0,1,0,0,0,0,0,0,0,'Wretched Captive - On Data 1/1 Set - Play Emote 18'),
(16916,0,2,0,61,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Wretched Captive - Out of Combat - Say Line 0'),
(16924,0,0,0,1,0,100,0,24000,24000,24000,24000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Sergeant Kan''ren - Out of Combat - Say Line 0'),
(16924,0,1,0,1,0,100,0,28000,28000,24000,24000,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Sergeant Kan''ren - Out of Combat - Say Line 1'),
(16924,0,2,0,1,0,100,0,26000,26000,24000,24000,45,1,1,0,0,0,0,19,16916,40,0,0,0,0,0,'Set 16916 Data 1/1');
```

**Comment by durotar** [comment]
same problem with npc 67880

**Comment by tkrokli** [comment]
@durotar : post a new issue on it, since http://www.wowhead.com/npc=67880/blood-guard-grotash is a 6.x-only NPC (Added in patch 5.1.0) and not present in 3.3.5 or 4.3.4.

**Comment by durotar** [comment]
my bad: http://www.wowhead.com/npc=18907/innkeeper-coryth-stoktron

**Comment by tkrokli** [comment]
Check if it is related to [Innkeeper Coryth Stoktron](12099) #12099 and [{Npc}Amisi Azuregaze / neutral innkeepers](4210) #4210 (both issues closed), then see if you can dig up enough material to post a separate issue about the problem you have encountered. This issue is already closed, so it makes more sense to create a new issue post (as long as you have got the necessary documentation for it).
Just remember to start your issue with your core revision hash. :-)

**Comment by durotar** [comment]
Tkrokli, this is not related with neutral innkeepers but the orientation.

**Comment by tkrokli** [comment]
Very well, just open the new issue then. I think everyone else are done with this page.

**Comment by durotar** [comment]
Believe me ... I'm too lazy to create a new issue
