### ISSUE TITLE
[Bug]Monty and Nipsy missing flavor text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12743]
Bug:
Monty and Nipsy are missing flavor text.

Broadcast Id:
Monty: 8463 - "Monty be me name an'' rats be me game."
Nipsy: 8475 - "You''ll find no finer rat kabob this side of Khaz Modan!"

Links:
Monty - www.wowhead.com/npc=12997
Nipsy - www.wowhead.com/npc=13018
Vid 1(1:10) - https://www.youtube.com/watch?v=U11BArF432g
Vid 2(1:00) - https://www.youtube.com/watch?v=m1o1nGxQQLc
Pic 1 - http://i.imgur.com/6qcyTNs.jpg
Pic 2 - http://i.imgur.com/Gleh8J9.jpg

Core rev: b5f0b85

**Comment by Killyana** [comment]
``` sql
DELETE FROM `gossip_menu` WHERE `entry`=4841 AND `text_id`=5894;
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (4841,5894);
UPDATE `creature_template` SET `gossip_menu_id`=4841 WHERE `entry`=12997;

DELETE FROM `gossip_menu` WHERE `entry`=4845 AND `text_id`=5920;
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (4845,5920);
UPDATE `creature_template` SET `gossip_menu_id`=4845 WHERE `entry`=13018;
