### ISSUE TITLE
Profession Daily Quest Pools

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12749]
<a href="https://github.com/Mogale"><img src="https://avatars.githubusercontent.com/u/2308389?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Mogale](https://github.com/Mogale)**
_Monday Oct 29, 2012 at 01:52 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/37_

---

These querys add quest pools to all the cataclysm profession daily quests.

There are 2 kind of Problems these querys can't fix:
1. Trolls should get Quest 26234 instead of 26233 like all other Horde races (I don't know if it could be done currently in core). So if daily quest 26233 is choosen by pooling system, Troll Players should see 26234.
2. Patch 4.1.0 added "Major City Profession Daily Quests" for Cooking and Fishing. This means in the 3 Main Cities (Orgrimmar, Thunder Bluff and Undercity for Horde / Stormwind, Darnassus, Ironforge for Alliance) are Daily Quests availible. 5 different Quests for every City, but per day you could only see one. If you take one of the 3 quests, you can't get any other quest from another City. So the pools has to be linked together. I don't think this is currently possible with current pooling system. Correct me if i'm wrong. Perhaps this feature should be availible in future. :)

Source: Sniffs, Wowhead
##

**Comment by Kelpiesklubhouse** [comment]
I know this is an old issue, but I've started fixing daily quests one by one starting with a new sql patch here https://github.com/TrinityCore/TrinityCore/issues/29451. Anyways, after doing some experiments with quest pools, I have a (probably very hacky) solution to the issue about pooled quests being different depending on race. (it also less elegantly helps with the other problem of 'master pools'.) 

Basically, if you assign the same index value in a pool to multiple quests, when that index is selected, all of the quests with the same index will be available. If they have individual requirements (like race) that will automatically filter them so you should only see the one that corresponds to your race. 

In the case of master pools, I found that you can get less desirable but okay results if you assign all quests of a specific type (like major city cooking dailies) to the same pool, then assign the indexes as 0-4 for each city's quests. The result of this is that if you take a quest from one city, the quests from the other cities will no longer be available. The only drawback to this solution (and the reason it's clearly a hack) is that when a specific quest is available in one city (say Ironforge), the quest with the corresponding index in Stormwind will always be the available quest. (This reduces the amount of randomness and is clearly non-blizzlike behavior).

**Comment by Kelpiesklubhouse** [comment]
So, apparently as Aokromes mentioned, exclusivegroup is how to handle the issue with the Major City Profession pools (bullet point 2). Which leaves my solution as still a simpler solution to the thing with trolls (bullet point 1). I'm interested if anyone else sees a problem with that solution. I'm putting any further daily quest fixing on hold until I figure out what direction the team would rather go with it.
