### ISSUE TITLE
DB/Misc: Collision gameobjects for stormwind currency vendors

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12757]
<a href="https://github.com/NorthStrider"><img src="https://avatars.githubusercontent.com/u/1472908?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [NorthStrider](https://github.com/NorthStrider)**
_Sunday Jul 21, 2013 at 21:57 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/286_

---

well here are the missing stormwind collision gameobjects i didnt add to stormwind cuz they were marked as tempoary spawn by the parser. but they should be always there.

Edit by Aokromes: Removed hack.
##

**Comment by Aokromes** [comment]
a738c72
https://gitlab.com/trinitycore/TrinityCore_434/commit/03fe6feb4560c025e0cc0290d272bc27abc6f163
