### ISSUE TITLE
Revert ZA 3.3.5 changes

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12758]
<a href="https://github.com/DDuarte"><img src="https://avatars.githubusercontent.com/u/530940?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DDuarte](https://github.com/DDuarte)**
_Monday Jul 29, 2013 at 15:40 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/289_

---

https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/blob/df124ad18a283bdc5960dd52f43d6a0ba60a3358/updates/067_2013_03_29_01_world_misc.sql
- [ ] TODO
##

**Comment by Aokromes** [comment]
This is still needed?

**Comment by Aokromes** [comment]
@DDuarte
