### ISSUE TITLE
Starting area creatures giving quests

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12752]
<a href="https://github.com/DDuarte"><img src="https://avatars.githubusercontent.com/u/530940?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DDuarte](https://github.com/DDuarte)**
_Sunday Jan 20, 2013 at 03:27 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/91_

----

From https://github.com/TrinityCore/TrinityCore/issues/9004, by @akira6968:

> Whole server freshly compiled (and DB) on 32bit Windows7 VMware
> MySQL 5.1.51
> Visual Studio C++ 2008
> OpenSSL 1.0.1c
> 
> Issue:
> Starting area creatures have quests (every creature lol)
> Once accepted, the creatures (being the ones that are the object of the quests) are yellow (neutral).
> 
> Versions:
> TrinityCore rev. 2013-01-19 18:36:39 +0100 (a5e7936) (Win32, Release)
> TDB_full_434.02_2012_08_30 + Updates_02 (thru 211_creature.sql) + src/sql/updates/world/ (2013_01_19_00 thru 2013_01_19_06 which were just committed a few hours ago and not in the Updates_02 repo)
> 
> Server.log:
> Unknown action type 48
> Creature (GUID: 138202 Entry: 44614) has wrong spell 0 defined in auras field.
> Creature (GUID: 138203 Entry: 44614) has wrong spell 0 defined in auras field.
> (several more of these)
> 
> Sorry....can't see a way to add the 4.3.4 tag...

**Comment by msoky** [comment]
This NPCs should't be quest starters, but they are...
http://www.wowhead.com/npc=706
http://www.wowhead.com/npc=808
http://www.wowhead.com/npc=3102
http://www.wowhead.com/npc=10556
http://www.wowhead.com/npc=15274
http://www.wowhead.com/npc=37070
http://www.wowhead.com/npc=37073
http://www.wowhead.com/npc=37112
http://www.wowhead.com/npc=39317
http://www.wowhead.com/npc=42223

this npcs is in start locations
revision: d418ae5

fix:
DELETE FROM creature_queststarter WHERE id IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);
UPDATE creature_template SET npcflag=0 WHERE entry IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12752#issuecomment-53974740

**Comment by msoky** [comment]
but they dont give out quests when you kill them

**Comment by Killyana** [comment]
This npcs doesn't start any quest when you kill them, they are just neutral + objective of a quest (Auto Accept) example of quest: http://www.wowhead.com/quest=182/the-troll-menace, it looks like the parser consider this kind of npc as a quest giver.

Of course there's some npcs that start a quest when their are killed like http://www.wowhead.com/npc=2372/mudsnout-gnoll , they start http://www.wowhead.com/quest=28355/terrible-little-creatures

**Comment by msoky** [comment]
how we can fix it?

**Comment by DDuarte** [comment]
Remove quest giver flag and the row from creature_questgiver

**Comment by msoky** [comment]
so, this can be pushed:
DELETE FROM creature_queststarter WHERE id IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);
UPDATE creature_template SET npcflag=0 WHERE entry IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);

**Comment by DDuarte** [comment]
```sql
`npcflag`=`npcflag` &~ 3
```

**Comment by tkrokli** [comment]
@msoky : I believe DDuarte suggests that your SQL should look like this:
```sql
DELETE FROM `creature_queststarter` WHERE `id` IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);
UPDATE `creature_template` SET `npcflag`=`npcflag` &~ 2 WHERE `entry` IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);
```
Notice also the use of back ticks ( ` ) around the names of table and column names.

**Comment by msoky** [comment]
thx :+1:
