### ISSUE TITLE
[4.3.4][QUEST] "Woodland protector"

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12759]
<a href="https://github.com/DepaMarco"><img src="https://avatars.githubusercontent.com/u/1042550?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DepaMarco](https://github.com/DepaMarco)**
_Monday Aug 05, 2013 at 10:20 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/291_

----

[4.3.4] - rev. 7794492 2013-07-26 07:27:42 +0200 (4.3.4 branch)
Night Elf, Hunter

The quest NPC (end) "Tarindrella" doesn't exist... So, you can't commit the quest...

**Comment by Aokromes** [comment]
This creature was spawned long time ago.
