### ISSUE TITLE
Kezahn - NPC / Creature Hot Rod

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#12764]
<a href="https://github.com/InfiniumWoW"><img src="https://avatars.githubusercontent.com/u/4131451?v=1" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [InfiniumWoW](https://github.com/InfiniumWoW)**
_Wednesday Aug 28, 2013 at 16:18 GMT_
_Originally opened as https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/issues/302_

---

System: Windows 7 Ultimate
Core: https://github.com/TrinityCore/TrinityCore/commit/14d80d269dd7f9624983bc5a610e511f31ed33f0
Ram: 16GB DDR3 16000

The Quest : Keys to the Hot Rod (http://www.wowhead.com/quest=28607)
The Creature : Hot Rod (http://www.wowhead.com/npc=34840)
The Spell : Rolling with my Homies: Summon Hot Rod (http://www.wowhead.com/spell=66393)

Screen : http://abload.de/img/wowscrnshot_082813_18b4svo.jpg

If i use the Key, i dont get in the Hot Rod but the Hot Rod spawn as a Pet and follow me ... 

Sry for Bad english but german Stuff xD 
##

**Comment by Killyana** [comment]
The area is not scripted yet.
