### ISSUE TITLE
[Bug]<Take the letter>

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12775]
Bugs:
1. The "<Take the letter>" gossip option is available to everyone at any level, however it should only be available to rogues at level 24 or above. 
2. The gossip itself is only given by Keryn Sylvius, however, it should be offered by any rogue trainer
3. The gossip doesn't work. It should grant players an "Elegant Letter".

Note: There should probably additional conditions for the gossip to not appear if player has "Elegant letter" in possession or is on quest "The Manor, Ravenholdt" or has completed "The Manor, Ravenholdt".

Links:
The Manor, Ravenholdt - http://www.wowhead.com/quest=6681
Elegant Letter - http://www.wowhead.com/item=17126
Keryn Sylvius - http://www.wowhead.com/npc=917
Code related to issue - https://github.com/benoit934/scriptdev2/blob/master/scripts/npc/npcs_special.cpp
Pic - http://i.imgur.com/pUCVWs1.jpg

Core rev: b5f0b85

**Comment by Rushor** [comment]
try this:

```sql
-- Keryn Sylvius SAI
SET @ENTRY := 917;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,62,0,100,0,381,4,0,0,11,21100,0,0,0,0,0,7,0,0,0,0,0,0,0,"Keryn Sylvius - On Gossip Option 4 Selected - Cast 'Conjure Elegant Letter'");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=381 AND `SourceEntry`=4;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(15, 381, 4, 0, 0, 15, 0, 8, 0, 0, 0, 0, 0, '', 'Show gossip text if player is a rogue'),
(15, 381, 4, 0, 0, 27, 0, 24, 3, 0, 0, 0, 0, '', 'Show gossip text if level >= 24'),
(15, 381, 4, 0, 0, 2, 0, 17126, 1, 0, 1, 0, 0, '', 'Show gossip option if player does not have Elegant Letter');
```
result: 
level 23: http://pokit.org/get/?2a5bbe92f2399627a27b95927361d79a.jpg
level 24 without letter: http://pokit.org/get/?ef7f7854536542d6969d1837a269d397.jpg
lecvel 24 with letter: http://pokit.org/get/?1993202ae71a52cebc481840cc6a9bff.jpg

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/efaf50c9405ca11b4cd80fa8808227e116398064
