### ISSUE TITLE
[Bug]Harlan Needs a Resupply

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#12777]
Bug:
After turning in "Harlan Needs a Resupply", no event between "Rema Schneider", "Corbett Schneider", "Harlan Bagley" and "Elaine Trias" happens.

**Version 1(By Gadoink4):**
Rema Schneider says: Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage.
Corbett Schneider says: Business must be good down at the bazaar. I'll get him resupplied right away!
_Corbett walks outside, and begins walking over to Lionheart Armory_
Corbett Schneider says: I should have a few extra coins from this sale. Maybe I'll buy myself some lunch...
_Corbett walks into Lionheart Armory_
Corbett Schneider says: Oomph! Here's another load of supplies, Harlan. It must be selling fast!
Harlan Bagley says: Ah yes, and promptly delivered. As always, it's a pleasure doing business with you, Corbett.
Corbett Schneider says: Well, I'm off then. Take care, Harlan.
_Corbett walks outside, and begins walking over to Trias' Cheese_
Corbett Schneider says: Now for that snack...
_Corbett walks into Trias' Cheese_
Corbett Schneider says: Hullo, Trias clan! A ball of your smoked mozzerella, if you please!
Elaine Trias says: Good day, Corbett. Here's your cheese, fresh made this morning! And how are things at your shop?
Corbett Schneider says: Yes ma'am, business is brisk!
Corbett Schneider says: Thank you kindly!
_Corbett walks outside, and begins walking over to Canal Tailor and Fit Shop_
Corbett Schneider says: Time to get back to the shop...
_Corbett walks into Canal Tailor and Fit Shop_
Corbett Schneider says: I'm back!
_Corbett walks upstairs and despawns_

**Version 2(By spottedtauren):**
(1) Upon completion of Harlan Needs a Resupply, Corbett will spawn, and the following will occur:
Rema Schneider says: Corbett, dear, Harlan needs a load of knitted shirts and pants as soon as we can manage.
Corbett Schneider says: My pleasure, sugar drop. I'll be back soon...

(2) Corbett walks outside, and begins walking over to Lionheart Armory
Corbett Schneider says: Hm... after dropping this off, I think I'll head to that cheese shop for a snack

(3) Corbett walks into Lionheart Armory
Corbett Schneider says: Oomph! Here's another load of supplies, Harlan. It must be selling fast!
Harlan Bagley says: Ah yes, and promptly delivered. As always, it's a pleasure doing business with you, Corbett.
Corbett Schneider says: Glad to see you're doing so well, Harlan. And I hope to see you again soon...

(4) Corbett walks outside, and begins walking over to Trias' Cheese
Corbett Schneider says: Now for that snack...

(5) Corbett walks into Trias' Cheese
Corbett Schneider says: Good day, Elling! Hullo Elaine! Let me have a wheel of bleu cheese, eh?
Elaine Trias says: Hi Corbett! Here, you go! I trust business is faring well at your clotheir shop...?
Corbett Schneider says: Yes ma'mm, business is brisk!
Corbett Schneider says: Thank you kindly!

(6) Corbett walks outside, and begins walking over to Canal Tailor and Fit Shop
Corbett Schneider says: I should get back before Rema starts to worry...

(7) Corbett walks into Canal Tailor and Fit Shop
Corbett Schneider says: I'm back!

(8) Corbett walks upstairs and despawns

Comparing these versions, either some texts were changed at some point in cataclysm or there a many texts in many pools which are picked randomly.

Links:
Rema Schneider - http://www.wowhead.com/npc=1428
Corbett Schneider - http://www.wowhead.com/npc=1433
Harlan Bagley - http://www.wowhead.com/npc=1427
Elaine Trias - http://www.wowhead.com/npc=483

Core rev: b5f0b85
##

**Comment by Rushor** [comment]
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/02d22d04c1dcf7a90c127e4996c9b13f7ebc3f44
