### ISSUE TITLE
[NPC] Stonesplinter Scout no melee attack, no ranged animation

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12796]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/48b94c3bebc86985097a59c12a4785df496a0026
__DB:__ TDB_full_335.52 + Updates

__Bug:__

The [Stonesplinter Scout](http://www.wowhead.com/npc=1162) has no ranged attack animation and no melee attack

__Details:__

When you aggro these, they move within range and stand there. You will see purple damage numbers over your character indicating they are throwing something at you. If you move to melee range they completely stop attacking and stand there doing nothing.

**Comment by malcrom** [comment]
`-- Stonesplinter Scout SAI
SET @ENTRY := 1162;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,4,0,10,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - On Aggro - Say Line 0 (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,0,0,2800,4800,11,10277,64,0,0,0,0,2,0,0,0,0,0,0,0,"Stonesplinter Scout - Combat CMC - Cast 'Throw'"),
(@ENTRY,0,2,0,9,0,100,0,0,5,1000,1000,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - Within 0-5 Range - Set Sheath Melee"),
(@ENTRY,0,3,0,9,0,100,0,5,30,1000,1000,40,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - Within 5-30 Range - Set Sheath Ranged"),
(@ENTRY,0,4,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stonesplinter Scout - Between 0-15% Health - Flee For Assist (No Repeat)"),
(@ENTRY,0,5,0,7,0,100,0,0,0,0,0,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - On Evade - Set Sheath Melee");`

**Comment by malcrom** [comment]
-- Stonesplinter Scout SAI
SET @ENTRY := 1162;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,4,0,10,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - On Aggro - Say Line 0 (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,0,0,2800,4800,11,10277,64,0,0,0,0,2,0,0,0,0,0,0,0,"Stonesplinter Scout - Combat CMC - Cast 'Throw'"),
(@ENTRY,0,2,0,9,0,100,0,0,5,1000,1000,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - Within 0-5 Range - Set Sheath Melee"),
(@ENTRY,0,3,0,9,0,100,0,5,30,1000,1000,40,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - Within 5-30 Range - Set Sheath Ranged"),
(@ENTRY,0,4,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stonesplinter Scout - Between 0-15% Health - Flee For Assist (No Repeat)"),
(@ENTRY,0,5,0,7,0,100,0,0,0,0,0,40,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stonesplinter Scout - On Evade - Set Sheath Melee");

**Comment by tkrokli** [comment]
Using the SQL from **malcrom**, I found the following during simple test with a dwarf hunter level 9 (but with overpowered armor):
- only very few of the Stonesplinter Scouts say their aggro Say line (is it possible to increase chance to be something like 50% instead of the perceived 10% (or less)?
- the ranged throw is performed, but without thrown object animation (maybe not addressed)
- Flee for assist at low health works, but none of those I aggroed were in range of another mob
- the only animation the Stonesplinter Scout uses is a "swing" animation for ranged attack

**Comment by Aokromes** [comment]
Maybe it lacks equipment?

**Comment by tkrokli** [comment]
```sql
SELECT `guid`,`id`,`equipment_id` FROM `creature` WHERE `id`= 1162 ORDER BY `guid`;
```
```
  guid      id  equipment_id
------  ------  ------------
288391    1162             1
288392    1162             1
288394    1162             1
288490    1162             1
288491    1162             1
288492    1162             1
288498    1162             1
288500    1162             1
288502    1162             1
288506    1162             1
288514    1162             1
288634    1162             1
288646    1162             1
288659    1162             1
288662    1162             1
288672    1162             1
```
```sql
SELECT * FROM `creature_equip_template` WHERE `CreatureID`= 1162;
```
```
CreatureID      ID  ItemID1  ItemID2  ItemID3  VerifiedBuild
----------  ------  -------  -------  -------  -------------
      1162       1     1906        0        0          18019
```
I thought this looks right, but maybe it needs both melee & ranged (ItemID2 / ItemID3) to use ranged?

**Comment by MrSmite** [comment]
> Not sure which item should be placed there, though.

It's an axe of some sort.

http://vignette1.wikia.nocookie.net/wowwiki/images/f/ff/Stonesplinter_Scout.jpg/revision/latest?cb=20100324153203
