### ISSUE TITLE
[DB/Quest] Thrusting Hodir's Spear 

### ISSUE THREAD

**Issue by cr4st** [TrinityCore/TrinityCore#12808]
Revision: https://github.com/TrinityCore/TrinityCore/commit/936db9d50dcb98ec20077bc2d2b3d74ceeb0ccff

Quest was not yet written! You could use the quest item and nothing happened.

I tried to complete the quest but i have issues:
- Waypoints needed.
- Alternative Vehicle? Player can quit vehicle in phase 2 and death fall.
- Player is not in his mouth in phase 2.
- Flight animation does not sometimes.

I would not create a pull request and hope someone can help me or can finish.

Thrusting Hodir's Spear (Quest):
https://github.com/cr4st/TrinityCore/commit/19f6ecf9e31a4e876b9fd84f6bdffa4f47e07870
##

**Comment by Killyana** [comment]
The npc 30275 dont have the script 'npc_wild_wyrm' if I added it: "ScriptName 'npc_wild_wyrm' exists in database, but no core script found!" I think it was reverted.

**Comment by Treeston** [comment]
Still an issue as of 3f3ff8b36b05

**Comment by Killyana** [comment]
Try the script provided by cr4st, I remember it works with some issues.

**Comment by Treeston** [comment]
Not possible - script uses member `_AddCreatureSpellCooldown` of the `Creature` class that doesn't exist on latest TC.

**Comment by Kittnz** [comment]
what would that function do? still missing

**Comment by Rushor** [comment]
https://github.com/cr4st/TrinityCore/commit/19f6ecf9e31a4e876b9fd84f6bdffa4f47e07870 - no longer active, pls update

**Comment by Aokromes** [comment]
Fix link no longer valid.

**Comment by Tauriella** [comment]
Any News ?

**Comment by Noryad** [comment]
Confirmed in f6dc66e
