### ISSUE TITLE
[Core/Movement] MovementType 1 & 2 creatures casting non-movement spells

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12823]
db : up-to-date
core : 14cb6e4235ebb84ad41d6ceb4eaf56c0b55d9238

When a creature has movementType 1 (random move), when it goes into combat, and cast a spell (which needs cast time, and the spell can not cast when move), you will find the creature can cast when move (until it reach the random move point).

**Comment by Rushor** [comment]
i will add a video to demonstarte this and everyone can see what happens

**Comment by Rushor** [comment]
kay here we go: https://youtu.be/8L91vTq8eRI

**Comment by robinsch** [comment]
Untested:

```diff
diff --git a/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp b/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
index 86f0e6e..7d03eeb 100644
--- a/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
+++ b/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
@@ -145,7 +145,7 @@ void RandomMovementGenerator<Creature>::DoFinalize(Creature* creature)
 template<>
 bool RandomMovementGenerator<Creature>::DoUpdate(Creature* creature, const uint32 diff)
 {
-    if (creature->HasUnitState(UNIT_STATE_ROOT | UNIT_STATE_STUNNED | UNIT_STATE_DISTRACTED))
+    if (creature->HasUnitState(UNIT_STATE_ROOT | UNIT_STATE_STUNNED | UNIT_STATE_DISTRACTED | UNIT_STATE_CASTING))
     {
         i_nextMoveTime.Reset(0);  // Expire the timer
         creature->ClearUnitState(UNIT_STATE_ROAMING_MOVE);
```

**Comment by Rushor** [comment]
yeah this solves the issue - but i'm not shure if we created a new issue with that 
problem i saw now:
after resetting the creature never ever start ROAMING_MOVE again

how to reproduce:
- pull it
- kill yourself
- creature resets > and never starts rndmmovement again

**Comment by Rushor** [comment]
kay just tested it again and yes sadly this fix causes the creatures to stop ROAMING_MOVE - after a reset, they never start rndmmoveing again

maybe the sai for these ones causes the issue?
```sql
(@ENTRY,0,0,0,1,0,100,0,1000,1000,1800000,1800000,11,12544,0,0,0,0,0,1,0,0,0,0,0,0,0,"Defias Pillager - Out of Combat - Cast 'Frost Armor'"),
```

**Comment by robinsch** [comment]
This bug was existing before.

**Comment by Rushor** [comment]
kay then - sry :/

**Comment by Rushor** [comment]
okay tested both partial fixes, 
on my one year old core from 2014 the fix works fine, on current cleantc (2015) is changes nothing, maybe i did sth wrong while testing - would be nice if someone else could test this

**Comment by tkrokli** [comment]
I intend to test it, need to wait until tomorrow though. Leaving my comment here as a "note to self".
Also just suggesting an issue title alternative, since I'm already here:
**[Core/Movement] movementType 1 or 2 creatures casting non-movement spells**

**Comment by Aokromes** [comment]
Anything here is valid?

**Comment by SnapperRy** [comment]
Tested robinsch's fix, doesn't work as of current TC.
