### ISSUE TITLE
Flightpath Exodar > Blood Watch broken [$15]

### ISSUE THREAD

**Issue by llars** [TrinityCore/TrinityCore#12832]
Not sure how long this has been around, but I noticed it a couple of weeks ago. Using flight masters in Exodar and Blood Watch results in "You don't know any flight locations connected to this one."

**Comment by ikir83** [comment]
I can confirm this is still exist, so the bounty is open :-P

**Comment by Aokromes** [comment]
Maybe this commit can help to fix it?

https://github.com/mangos/mangos/commit/47bc4bece7362a0be19b77fd5341927f67f69423

**Comment by Killyana** [comment]
Spells: (if you stay near the fly master and cast the spell you will get the fly.)
29376: from blood Watch to Exodar 
29377: from Exodar to blood Watch
The problem is that this 2 Fly-masters (17555, 17554)  shows this map: http://i.imgur.com/DwHTj1k.jpg

**Comment by Frytiks** [comment]
Can someone re-try ?

**Comment by Aokromes** [comment]
You can test https://github.com/TrinityCore/TrinityCore/issues/15219
