### ISSUE TITLE
[335] Dragonmaw Scout Does Not Attack

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12831]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/c28345e279f31af2fa32df2411325ccfabe06fc8
__DB:__ TDB_full_335.52 + updates

__Bug:__

[Dragonmaw Scout](http://www.wowhead.com/npc=2103) does not attack (melee or ranged)

__Details:__

At player level 10 these are ?? level but you can walk right up to them and they will aggro but not attack. One odd thing is if you also aggro a [Dragonmaw Grunt](http://www.wowhead.com/npc=2102), the Scout you initially aggro'd will begin attacking you. If you die and revive, the process starts over again.

I looked at the smart_scripts and it looks like it might be a phase issue? All event_phase_mask are SMART_EVENT_PHASE_1 but all the descriptions say (Phase 2). There are fields missing from the wiki so I don't know what event_param1-4 is or if it's even relevent.

**Comment by Killyana** [comment]
There's no event_phase used for this npcs and they attacks normally.
rev. 0148832b322b
