### ISSUE TITLE
[3.3.5][BUG] Ruby Sanctum: Halion's Soul Consumption

### ISSUE THREAD

**Issue by Funkeln** [TrinityCore/TrinityCore#12835]
rev https://github.com/TrinityCore/TrinityCore/commit/07158af425419c631a87656bc7b936b31a74eafd

Twilight Halion doesn't cast his Soul Consumption spell at any moment. From some testing, apparently his eventmap is never updated so the event is never executed.

And no, I wasn't alone testing it, had 4 people with me (aware that it shouldn't be cast on the main target).

http://www.wowhead.com/spell=74792/soul-consumption

**Comment by Warpten** [comment]
Closing since PR fixed that, reopen if still broken

**Comment by Warpten** [comment]
tfw github showed this as open

**Comment by jackpoz** [comment]
+1 Warning point to @Warpten for necroposting :)
