### ISSUE TITLE
[Core/AH] Auction House "Sort by" Option

### ISSUE THREAD

**Issue by XJIOP** [TrinityCore/TrinityCore#12864]
TrinityCore rev. 07158af42541

incorrect sorting by level, at turning next page you can see it.
http://i58.tinypic.com/2n7ku0.png
http://i61.tinypic.com/2rp5yf8.png

**Comment by Rushor** [comment]
concerns all "sort by xx" options. only the first page is sorted correctly.

**Comment by Rushor** [comment]
a more general and better description in https://github.com/TrinityCore/TrinityCore/issues/15648
