### ISSUE TITLE
[3.3.5][Priest] Core/Spell: Glyph of pain suspression

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#12886]
rev: d15bbc63de8aca43262917966bf9c1c8651cb497
when you are in trap you must be able to  cast pain suspression but you cant :)
http://www.wowhead.com/spell=33206/pain-suppression
http://wotlk.openwow.com/item=45760

**Comment by lashia** [comment]
this issue is still i found solution for  trap and stun effects
change this
`// Glyph of Pain Suppression
    // there is no other way to handle it
    if (m_spellInfo->Id == 33206 && !m_caster->HasAura(63248))
        usableInStun = false;`
with:
`    // Glyph of Pain Suppression
    // there is no other way to handle it
	if (m_spellInfo->Id == 33206 && !m_caster->HasAura(63248) || m_caster->HasAura(60210) || m_caster->HasAura(61635) || m_caster->HasAura(61634))
		usableInStun = true;

	if (m_caster->HasAura(60210) || m_caster->HasAura(61635) || m_caster->HasAura(61634))
		return SPELL_CAST_OK;`
but it must be castable in polymorph... @Rushor @Aokromes @Kinzcool

**Comment by Keader** [comment]
@lashia https://gist.github.com/Keader/df2914b6a5e51ce2f30d#file-painfix-diff-L12-L13

if polymorph is valid, only add another || m_caster->HasAura(PolyAuraHere)

but this is hack xD

**Comment by tkrokli** [comment]
Like Rushor said in another issue where a hackfix was posted: "the problem with hackfixes is that everyone will copy it to their server and so they solved their problem. but noone will actually look into this issue anymore to find the real reason for it :( "

**Comment by lashia** [comment]
@Keader where can i find polymorph aura id

**Comment by Keader** [comment]
Spellid in game, .list aura, .lookup spell, wotlk database, etc
Anyway, polymorph id is   118 (rank1) ,  12824 (rank 2) ,  12825(rank 3), 12826 (rank4)

**Comment by Demonid** [comment]
Why the title has Warlock instead of Priest Oo?

**Comment by Keader** [comment]
Warlock? o.O

**Comment by Treeston** [comment]
"My friend thinks it works this way" is not considered valid proof. The glyph states that it works _while stunned_, not while feared or trapped or whatever.

Working as intended unless further proof is provided.

**Comment by Treeston** [comment]
SpellWork says Freezing Trap has `SPELL_AURA_MOD_STUN`, so should allow PSup to be cast.

**Comment by P-Kito** [comment]
I am playing Disc priest on current patch and I can cast it in trap and AFAIK they moved the glyph into the spell, not more not less.

**Comment by lashia** [comment]
no must work on trap and polymorph too there was video proof someone posted i cant find

**Comment by Treeston** [comment]
Polymorph is a confuse effect.

**Comment by Treeston** [comment]
Goddamn it, wrong button.

**Comment by lashia** [comment]
https://wow.freakz.ro/spells.php?spell=33206&name=pain-suppression
- Not usable while shapeshifted/polymorphed
- Usable while stunned

**Comment by Treeston** [comment]
>Not usable while shapeshifted/polymorphed

**Comment by lashia** [comment]
yes but on trap and stun it doesnt work

**Comment by Eliminationzx** [comment]
Need a special mechanic mask I guess.

**Comment by Treeston** [comment]
No, just SPELL_MOD_STUN is fine. I don't think it relates to mechanic at all.

**Comment by P-Kito** [comment]
I think you can use it while sapped too, needs check tho.
