### ISSUE TITLE
[Threads] DB Threads being forcibly closed at shutdown

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#12891]
__Rev:__ https://github.com/TrinityCore/TrinityCore/commit/7cb72c2aacbb3c2502bd5d25a52a6e96fe2b9cc8
__OS:__ Win 7

__Bug:__

DB Threads don't seem to be released properly when the core is shutdown which causes MySQL to have to forcibly close them when it itself is shutdown

__Details:__

* I have all the various DB *threads* settings set to 3 in the config.
* I have the DB on one Win 7 machine and the core on a separate Win 7 machine.

After starting the core and then shutting it down (immediately or after some time) and then going to the other machine and shutting down the MySQL server, the MySQL console will say that there are several threads open that need to be forcibly closed.

There shouldn't be any threads left open because both the gameserver and authserver have completed their shutdown process. It also doesn't seem to matter wether I've actually logged into the game or not.

**Comment by danlapps** [comment]
Is this still an issue ? No one else seemed to have this problem.

**Comment by tkrokli** [comment]
@danlapps : it is likely not a live issue. From what I can understand, @MrSmite's issue is only provoked when increasing the DB threads settings in Worldserver.conf to higher values than default, like 3 or more.
In that regard, this issue is more of academic interest (preventive planning) than actually occurring live.

**Comment by MrSmite** [comment]
I completely forgot about this issue since I changed my threads back to 1.

**Comment by MrSmite** [comment]
Going to close this for now since Github still allows discussion in closed topics. If it pops up again or I get more details I can always reopen it.
