### ISSUE TITLE
[3.3.5][BUG]Creature should allow combat move when silenced or be casted counterspell

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#12908]
DB : up-to-date
Core : a8ff0c990b68eda2bf3c22bbf4d72331bc8842b9

In Smart AI system, Creature should allow combat move when silenced or be casted counterspell. How to know a creature is be silenced in code? I'll fix it.
##

**Comment by offl** [comment]
#20222?
