### ISSUE TITLE
Core/Spell: Bael'Gar's Fiery Essence

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#12909]
DB : up-to-date
Core : a8ff0c9

In order to complete the quest: http://www.wowhead.com/quest=4024
you must go to npc: http://www.wowhead.com/npc=9016 and kill him.
After that you should use the item: http://www.wowhead.com/item=11231 on the corpse of him

itemspell: http://www.wowhead.com/spell=13982

How it should be: 
you can only use the item, if the npc is dead

How it is:
You can use the item everywhere even there is no npc=9016 

Conditions are already given in the db:
```sql
INSERT INTO `conditions` VALUES (13, 1, 13982, 0, 0, 31, 0, 3, 9016, 0, 0, 0, 0, '', NULL);
INSERT INTO `conditions` VALUES (13, 1, 13982, 0, 0, 36, 0, 0, 0, 0, 1, 0, 0, '', NULL);
```
but this does not solve the problem.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/12803

**Comment by Killyana** [comment]
This cannot be fixed by a DB condition, it requires a spell script.

**Comment by sirikfoll** [comment]
@Rushor @Killyana This is wrong? It works.
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(13,17) AND `SourceEntry`=13982;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13,1,13982,0,0,31,0,3,9016,0,0,0,0,'',"Spell 'Bael'Gar's Fiery Essence targets Bael'Gar's'"),
(17,0,13982,0,0,29,0,9016,10,1,0,0,0,'',"Spell 'Bael'Gar's Fiery Essence' requires Bael'Gar's corpse");
