### ISSUE TITLE
Core/Spell: Misdirection, Tricks of the Trade, Shadowform stuck

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#12913]
Hi all

I've opened this issue as I can´t find any other regarding this ability: http://www.wowhead.com/spell=34477

The problem here seems to be with its cooldown, or the way it's handled.

Sometimes, randmly (i cant find a pattern or an explanation) it gets stuck in the first "phase".

This first "phase" is when u click and the button is grey colored. When ur meant to attack a creature to start the Misdirection.

The spell gets stuck there and players cant cast it again (this persist even after dead)

hash: a8ff0c990b68eda2bf3c22bbf4d72331bc8842b9

**Comment by Keader** [comment]
This usually occurs when trying to use MD on target far, or try to use the spell multiple times quickly.

**Comment by joshwhedon** [comment]
This is most likely due to SPELL_ATTR0_DISABLED_WHILE_ACTIVE
It can also happen to Stealth and Shadowform.

**Comment by joshwhedon** [comment]
It seems that this bug is a blizzlike bug : http://us.battle.net/wow/en/forum/topic/16646164602
I think it may be a client side issue.

**Comment by Rushor** [comment]
@joshwhedon well we need some proof that the bug was even there with 3.3.5 in 2010

**Comment by tkrokli** [comment]
(Google search for wow+hunter+Misdirection+bug between 2009/12/08 and 2010/10/10)
https://www.google.com/search?q=wow+hunter+Misdirection+bug&newwindow=1&source=lnt&tbs=cdr%3A1%2Ccd_min%3A12%2F8%2F2009%2Ccd_max%3A10%2F10%2F2010&tbm=

**Comment by ariel-** [comment]
http://pastebin.com/LstU8722

This hackfix solves the problem for Misdirection, Tricks of the Trade and Shadowform, however I'm unsure how to handle this and/or what the root cause is.

**Comment by Nawuko** [comment]
I think that spells with the Attribute SPELL_ATTR0_DISABLED_WHILE_ACTIVE are not handled correctly. Maybe someone can look into it. The SPELL_ATTR0_DISABLED_WHILE_ACTIVE is maybe the root cause.

**Comment by Aokromes** [comment]
I am using https://github.com/TrinityCore/TrinityCore/issues/657#issuecomment-8433390 for shadowform for years.

**Comment by nyhmii** [comment]
I have done A LOT of testing, the bugg is produced by macro's or by spamming Shadowform while in/out of form. THE ACTUAL bug happends when shadowform is on 0.01% of cooldown finish WHILE being spammed. so when the cooldown is nearly "completed" it basically buggs when "clicked/activated".

**Comment by Midnaa** [comment]
https://gyazo.com/86bd04d06027ba411faba83235d822cc It is only when you go out of form and press it right before the gcd finishes

**Comment by tkrokli** [comment]
@Midnaa : if you can document your issue, it will be better if you open a new issue ticket and use all the provided template sections (please search for related spell/GCD issues in this tracker first). The issue on this page is quite old (more than a year ago), so just link this issue if you decide to open a new issue ticket.
