### ISSUE TITLE
[6.X] Hunter Call pet [$5]

### ISSUE THREAD

**Issue by msoky** [TrinityCore/TrinityCore#12974]
When i click `Call pet` in action bar, he didnt roll up menu with buttons Call pet 1,2,3,4,5...only when i move Call pet 1,2,3,4,5 from spell book in action bar, then buttons work...but when i have 2 or more pets, `Call pet` is still calls last pet...where is others pets (cat in video) i dont know...they is lost
core rev: https://github.com/TrinityCore/TrinityCore/commit/ddcc0352d00b7fa3e77d2c7d4cbf6bc92edf9995
DB: 6.0.2
video: https://www.youtube.com/watch?v=0t1xFkL0Y40&list=UUBreIFENIhG-4ENp_iN4NCQ
at start, i have Cat...second pet is Dragonhawk...and i cant call back cat after tame dragonhawk...all addons is off
##

**Comment by killradio** [comment]
Funny, is this action working on 6.x branch? Can someone test?

**Comment by msoky** [comment]
on 6.x still persist this problem

**Comment by killradio** [comment]
@msoky Can you plz post your rev and db here, so title and tag can be changed?

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ddcc0352d00b7fa3e77d2c7d4cbf6bc92edf9995 and DB 6.0.2

**Comment by msoky** [comment]
anything new?

**Comment by msoky** [comment]
any news?

**Comment by aquadeus** [comment]
im going to test that

**Comment by Nyr97** [comment]
What's the state of this issue? TC has recently pushed changes to how Pet Stable and slot system works, so this issue might not be valid anymore.

**Comment by Shauren** [comment]
Fixed in 950db60435e7e513633ff5b22ad7f0ed8b1147e4
