### ISSUE TITLE
King Frostmourne phase Wicked Spirit

### ISSUE THREAD

**Issue by alein** [TrinityCore/TrinityCore#13019]
Hi guys.
I have some problem with targeting some [Wicked Spirit](http://www.wowhead.com/npc=39190) during frostmourne phase.

I tested on clean core and db. [79b954a](https://github.com/TrinityCore/TrinityCore/commit/79b954a349a61802cc2bda56f943e9e6e01adf44)

Please advise/help.
Thanks.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/8335
