### ISSUE TITLE
Wrong healing application for triggered-on-damage heals

### ISSUE THREAD

**Issue by mik1893** [TrinityCore/TrinityCore#13025]
I found this barely mentioned in other issues where it was offtopic, so I open it to get a clear discussion.

rev. e648250

heals triggered from damage have some issues in the way the healing is applied. 
The spells I found with this behaviour atm are:
- living seed
- prayer of mending
- earth shield

What happens: when proc happens, the healing amount is calculated and "stored". Then damage which determines this proc is applied, and then the heal effect is applied.

The issue is is the fact that healing and overhealing are calculated on the wrong amount of target current health:
- target is missing 200 health 
- target suffer 5000 damage, triggered heal procs before damage applies and calculates 200 healing and 1800 overhealing on a 2000 heal
- target life goes down of 5000
- target is healed for that 200 and 1800 is overhealing , even if he's missing 5200 life so he should get the whole 2000 heal.

I want to fix this,  I would like to know any ideas or best practices in the how to. 
I mean: should damage be applied before the proc? Or should overheal be calculated after proc just for triggered spells like this?
##

**Comment by joshwhedon** [comment]
By the look of it, SPELL_ATTR7_UNK30 is supposed to be used if to determine if the spell has to proc pre or post effect.

**Comment by mik1893** [comment]
just a note: new proc system should fix this
