### ISSUE TITLE
Instance/Spell: Icy Blast - Rimefang/Tyrannus

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13023]
TrinityCore rev. cba59eb
fresh db

Issue concerns spell: http://www.wowhead.com/spell=69238#comments
Original fixed in https://github.com/TrinityCore/TrinityCore/issues/632

Current Problem:
After the summon of the white area effect, only player will be slowed by the spell.
If Tyrannus walks over the white areaeffect, Tyrannus will not be slowed.

How it should be:
Player an Tyrannus must be slowed, if they walk over the white areaeffect.

Reason:
The icy-Blast trigger: 36731 summons the white area-affect. But the trigger has faction 14.
So this trigger is hostile towards player, but friendly towards Tyrannus.

Possible Solution:

```
-- Icy Blast SAI
SET @ENTRY := 36731;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,54,0,100,0,0,0,0,0,2,MISSING_FACTION,0,0,0,0,0,1,0,0,0,0,0,0,0,"Icy Blast - On Just Summoned - Set Faction 36"),
(@ENTRY,0,1,0,61,0,100,0,0,0,0,0,11,69238,2,0,0,0,0,1,0,0,0,0,0,0,0,"Icy Blast - On Just Summoned - Cast 'Icy Blast'");
```

As you can see, we need a faction which is hostile towards alliance+hordeplayers and tyrannus(faction 14)

Resume:
Need correct faction for hackfix :D 
##

**Comment by Aokromes** [comment]
This bug is the same as ToC mobs don't slowing if they walk over ice no?

**Comment by CraftedRO** [comment]
593721ff1fc7 Seems no longer valid:


https://user-images.githubusercontent.com/24683355/213511549-331803ac-9f7f-4dbd-853d-febff92340bb.mp4
