### ISSUE TITLE
[Bug]Magistrate Bluntnose is missing gossip text

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#13031]
Bug:
Magistrate Bluntnose is missing gossip text.

Links:
Magistrate Bluntnose - http://www.wowhead.com/npc=1139
Pic - http://i.imgur.com/NBRC4uF.jpg

Core revision: 6e9d7486fe84f899fe24bfa3e47d71eae7947110

**Comment by tkrokli** [comment]
This would be an easy issue to solve if we just had the correct gossip / `npc_text` for this NPC.
None of the regular sites have got useful info about his gossip, nor could I find any videos or images of him with the gossip, except the linked image above (still missing, obviously). Sniffs are needed, I guess.

**Comment by tkrokli** [comment]
Heh. I was sort of miffed to see that he doesn't have any NPC specific text. The only visible difference is that the new text he uses includes a comma before $n:
```sql
SELECT `entry`,`name`,`gossip_menu_id`,`npcflag`,`VerifiedBuild` FROM `creature_template`
WHERE `entry`= 1139;
```
```
 entry  name                  gossip_menu_id  npcflag  VerifiedBuild
------  --------------------  --------------  -------  ---------------
  1139  Magistrate Bluntnose             140        3          12340
```
```sql
SELECT * FROM `gossip_menu` WHERE `entry` = 140;
```
```
 entry  text_id
------  ---------
   140       68
```
```sql
SELECT `ID`,`text0_0`,`text0_1`,`BroadcastTextID0` FROM `npc_text` WHERE `ID` = 68;
```
```
    ID  text0_0         text0_1         BroadcastTextID0
------  --------------  --------------  ------------------
    68  Greetings, $n.  Greetings, $n.             50429
```
I am not trying to say that anything is wrong. I just imagined that the NPC would have more text to say.
