### ISSUE TITLE
[Bug]Rumsey Rum Light

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#13036]
Bugs:
1. After using "Rumsey Rum Light" you get an error "Spell is not ready yet.". Nevertheless, as it should, the stamina increase buff is given.
2. "Rumsey Rum Light" spell effect doesn't count as "well fed" and thus will not replace any well fed buffs or be replaced by well fed buffs.

Wowwwiki:
"In addition to getting you drunk, Rumsey Rums provide a "well fed" stamina bonus. The Stamina bonus will replace any "well fed" aura."

Wowhead comment:
By TwistingPlanets (6,463 – 1·9·34) on 2008/04/16 (Patch 2.4.1)
This buff will cancel any food buffs you have and vice versa.

Links:
Rumsey Rum Light - http://www.wowhead.com/item=20709
Rumsey Rum Light - http://www.wowhead.com/spell=25037

Core revision: 6e9d748

**Comment by Killyana** [comment]
I cannot find why the message "Spell is not ready yet"  is shown, any way it's just visual.
This will fix the aura stacks for all  Rumsey  alcohols.
``` sql
DELETE FROM `spell_group` WHERE `id`=1001 AND `spell_id` IN (45694, 20875, 25804, 25722, 25037);
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES (1001, 45694), (1001, 20875), (1001, 25804), (1001, 25722), (1001, 25037);

**Comment by Rushor** [comment]
more source for this:
By clavarnway (16,135 – 2·19·152) on 2008/02/17 (Patch 2.3.3)		
"PTR 2.1 patch notes.: “Rumsey Rum”, “Rumsey Rum Light”, “Rumsey Rum Dark”, “Rumsey Rum Black Label”, “Halaani Whiskey”, “Gordok Green Grog”, “Raptor Punch”, “Stormstout”, “Trogg Ale”, and “Thunderbrew Lager”: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods."

**Comment by tkrokli** [comment]
Yes, and from what I can remember in TBC and WoTLK, the [Rumsey Rum Light] stamina buff had a separate buff icon just like the item icon. I don't remember what the other drink buff icons were, though.
