### ISSUE TITLE
[3.3.5a][OpenPvP][Halaa] First Spawn of NPCs

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13044]
TrinityCore rev. cba59eb
fresh db

The spawn of the Halaa-NPCs does not seems to work perfectly.

How to reproduce:
a) Restart Server
b) create alliance or horde character
c) fly with one of the characters to halaa
d) acivate pvp and take controle of halaa
=> Only an amount of <=15 npcs will spawn. Sometimes 11 npcs spawn after serverrestart, sometimes 9.

Note:
if the alliance is the first one which take controle, only 9 guards will spawn.
if the horde is the first one which take controle, only 11 guards will spawn.

However, after the other faction captured halaa all npcs (15/15) will spawn and everything goes on perfectly.

How it should be:
After the first faction after serverrestart captured halaa, 15 npcs should spawn ALWAYS.

**Comment by Killyana** [comment]
On rev. 5b5c0938da0f all npc are spawned the first time, if someone can confirm also maybe related to Visibility.Distance.Continents set to 170 on my local server

**Comment by tkrokli** [comment]
TrinityCore rev. 3e588acfe9ec 2015-04-25 09:15:27 +0200 (3.3.5 branch) (Win64, Release)

Well, I tested this now with an orc hunter (gmlevel 3, gm off) vs nightelf hunter (gmlevel 0).
Test 1: entered with orc, 10/15 horde guards spawned immediately. left the area to level up the normal character via the gmlevel 3 character. Came back with nightelf + orc, guards are now 15/15. Need to test again with the normal character after server restart. Not sure how the last 5 appeared.  :suspect:

**Comment by Killyana** [comment]
After more testes I got sometimes 2 ou 3 missing spawns.

**Comment by tkrokli** [comment]
Yes, I also tested after adding your Halaa bomb :bomb: visuals SQL from the other issue. When testing again after a fresh server restart, the guard number was 15/15 for a fraction of a second, then it dropped to 10/15.
Weird. It is just as if the script changed its mind the same second as it has spawned the NPCs... :smirk_cat:

**Comment by Rushor** [comment]
this issue (the issue that there are missing some creatures sometimes) also concerns the spawn of the cannons in wintergrasp. maybe the tempsummons despawn because of the inactive gridcell.

maybe this can be fixed if the spawn is handled with a triggercreature which sets the envolved creature active on spawn (hack)

**Comment by Rushor** [comment]
i cannot see the issue in this script, everything seems to be fine
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp#L95

**Comment by Kodekc** [comment]
I watch the NPC on a live server. Not enough waypoints, each bridge is two guards and one is constantly walking the circular route. In my opinion NPC need to move is database

**Comment by Rushor** [comment]
there is no pathing because the creatures are only tempspawns

**Comment by Kodekc** [comment]
@Rushor, I propose to transfer them to the database. The Nexus has a similar mechanic to call NPS different factions can somehow use it here?

**Comment by Kodekc** [comment]
```sql
-- Alliance Halaani Guard
SET @CGUID := XXXXX; -- selected by TC team
DELETE FROM `creature` WHERE id = 18256;
UPDATE `creature_template_addon` SET `bytes2`='257' WHERE  `entry`=18256;
INSERT INTO `creature` (`id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES 
('@CGUID', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1651.934, 8000.096, -26.30284, 3.316126, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+1', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1498.482, 7916.274, -19.01937, 5.585053, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+2', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1584.384, 7996.057, -23.25455, 4.729842, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+3', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1651.538, 7988.559, -26.52891, 2.984513, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+4', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1602.46, 7866.434, -22.11768, 4.747295, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+5', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1591.222, 7875.292, -22.35359, 4.34587, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+6', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1549.201, 7947.229, -21.26053, 3.804818, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+7', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1567.305, 7901.481, -21.98275, 1.919862, 120, 10, 0, 0, 0, 1, 0, 0, 0, 0), -- (possible waypoints or random movement)
('@CGUID+8', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1560.244, 7927.3, -21.68859, 2.572838, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
('@CGUID+9', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1543.458, 7991.201, -20.17463, 0.9599311, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+10', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1606.892, 7938.02, -25.65071, 2.770728, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+11', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1560.894, 7983.841, -21.78858, 0.6457718, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+12', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1619.652, 7962.751, -27.85839, 0.6097964, 120, 10, 0, 0, 0, 1, 0, 0, 0, 0), -- (possible waypoints or random movement)
('@CGUID+13', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1497.87, 7907.144, -18.77001, 5.689773, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),
('@CGUID+14', 18256, 530, 0, 0, 1, 1, 0, 0, 0, -1587.229, 7932.512, -24.86185, 1.012291, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0),

**Comment by Rushor** [comment]
well then the whole despawn/respawn mechanic depending on the ownerteam must be changed :/

**Comment by Kodekc** [comment]
[20886_2016-03-12_19-10-11_01D90131_parsed.txt](https://github.com/TrinityCore/TrinityCore/files/170540/20886_2016-03-12_19-10-11_01D90131_parsed.txt)
Perhaps, too, will come in handy

**Comment by Kodekc** [comment]
@Rushor, I thought maybe the error associated with the time of capture territory? Now it does not work properly.

As should be:

Sign capture territory should reach almost to the end and only after that comes the revival of factional guards, which carried out the seizure.

**Comment by Aokromes** [comment]
Test https://github.com/joschiwald/TrinityCore/tree/halaa

**Comment by Aokromes** [comment]
#8597
