### ISSUE TITLE
[Spell] Touch of Zanzil - Able to go in stealth

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13053]
TrinityCore rev. cba59eb
fresh db

How it should be:
If you get this debuff http://www.wowhead.com/spell=9991 you should not be able to go in stealth.

How it is:
If you have the debuff, you are still able to go in stealth with your rogue.

proof, that you should not be able to go in stealth:
http://www.wowhead.com/spell=9991#comments:id=249905

By Novawolf (10,860 – 2·11·87) on 2008/03/08 (Patch 2.3.3)      

> Before a recent patch (Not sure when this was implemented), this poison would completely annihilate your effective stealth level, allowing mobs to see you in stealth from a mile away, as if you weren't even stealthed.
> 
> Now, however, you can't stealth at all.
##

**Comment by Rushor** [comment]
adding this:

case 6950: // Faerie Fire
case 9991: // Touch of Zanzil
case 35331: // Black Blood
        return AURA_STATE_FAERIE_FIRE;

in src/server/game/Spells/SpellInfo.cpp would solve the problem. i don't know if it would be a hack :/ 
probably a attribute is missing here, but i saw that there is also a hack currently implemented for the fearie fire auras.

**Comment by danlapps** [comment]
Need @DDuarte , @joschiwald  or @Shauren I guess to confirm if this is valid or hack.

**Comment by xjose93** [comment]
Not sure if more than those spells should be added to the list:

ID | Name | Description | Aura description
------------ | ------------- | ------------- | -------------
770 | Faerie Fire | Decrease the armor of the target by $s1% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s1%.  Cannot stealth or turn invisible.
6950 | Faerie Fire | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
9806 | Phantom Strike | Decrease the armor of the target by $s1 for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s1.  Cannot stealth or turn invisible.
9991 | Touch of Zanzil |  | Agility reduced by $s1.  Cannot stealth or turn invisible.
13424 | Faerie Fire | Decrease the armor of the target by $s1 for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s1.  Cannot stealth or turn invisible.
13752 | Faerie Fire | Decrease the armor of the target by $s1 for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s1.  Cannot stealth or turn invisible.
16432 | Plague Mist |  | $s1 Nature damage every $t1 seconds. Cannot use stealth or invisibility.
16498 | Faerie Fire | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
16857 | Faerie Fire (Feral) | Decrease the armor of the target by $16857s1% for $16857d.  While affected, the target cannot stealth or turn invisible.  Deals ${$AP*0.15+1} damage and additional threat when used in Bear Form or Dire Bear Form. | Decreases armor by $s1%.  Cannot stealth or turn invisible.
20656 | Faerie Fire | Reduces an enemy's armor for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
21670 | Faerie Fire | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
25602 | Faerie Fire | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
32129 | Faerie Fire | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Armor reduced by $s1. Cannot use stealth or invisibility.
35325 | Glowing Blood | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Cannot use stealth or invisibility. Chance to dodge reduced by $s2%. Agility increased by $s3%.
35328 | Lambent Blood | While affected, the target cannot use stealth or invisibility. | Cannot use stealth or invisibility. Damage taken increased by $s2%. Strength increased by $s3%.
35329 | Vibrant Blood | While affected, the target cannot use stealth or invisibility. | Cannot use stealth or invisibility. Spell casting time increased by $s2%. Damage done by magical spells and effects increased by $s3%.
35331 | Black Blood | Reduces an enemy's armor by $s1 for $d. While affected, the target cannot use stealth or invisibility. | Cannot use stealth or invisibility. All stats decreased by $s3%. Damage taken reduced by $s2%.
56626 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
56627 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
56628 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
56629 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
56630 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
56631 | Sting | Your wasp stings for $s1 Nature damage, and decreases the armor of the target by $s2% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s2%.  Cannot stealth or turn invisible.
60089 | Faerie Fire (Feral) | Decrease the armor of the target by $16857s1% for $16857d.  While affected, the target cannot stealth or turn invisible.  Deals ${$AP*0.05+1} damage and additional threat when used in Bear Form or Dire Bear Form. | 
65863 | Faerie Fire | Decrease the armor of the target by $s1% for $d.  While affected, the target cannot stealth or turn invisible. | Decreases armor by $s1%.  Cannot stealth or turn invisible.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
