### ISSUE TITLE
[DB|NPC] Vhel'kur - Missing Waypoints

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13054]
http://de.wowhead.com/npc=21801

As you can see, this npc should have some waypoints and 'flys' in a circle.

If someoone profide some sniffs for this creature, i would copypaste it.

**Comment by danlapps** [comment]
Do we need more data gathering on this or is this an issue of Scripting for those who have access to sniffs ?

**Comment by Rushor** [comment]
we need someone who has this http://www.wowhead.com/item=30719 and is willing to run the full path of this npc :) 

kittnz said once, that he lost the glasses, i don't have them too, so... :/

**Comment by tkrokli** [comment]
Forgive my ignorance, but are you saying that we need to get sniffs from NPC 21801 (Vhel'kur) on a live Blizzard server by flying the same path as the NPC while wearing the [Spectrecles](http://www.wowhead.com/item=30719) (item 30719) to get the waypoints? I thought perhaps it was possible to get the spectrecles again from [Chief Apothecary Hildagard](http://www.wowhead.com/npc=21772/chief-apothecary-hildagard) (NPC ID 21772) even after the quest is completed, but I may remember it wrong because I haven't done this quest myself on Blizzard's servers. (I don't currently have any high-level character on a live realm.)

**Comment by Kittnz** [comment]
I can try to sniff it if he gives the goggles again.

**Comment by tkrokli** [comment]
> I can try to sniff it if he gives the goggles again.

Hildagard is a "she", but yeah. I hope you will be able to convince her to give you a new pair. ;-)

**Comment by danlapps** [comment]
for horde, i htink for alliance its solasomething, my toon is there but need to pre-quest.  will continue when i have some time

**Comment by Rushor** [comment]
we will wait for the sniff then:)

**Comment by tkrokli** [comment]
@danlapps : http://www.wowhead.com/item=30719/spectrecles#comments:id=34550

and for the alliance: Zorus the Judicator (NPC 21774)

**Comment by danlapps** [comment]
@tkrokli yup yup i saw ! but since i never did quest in that area I cannot just buy them back :S

**Comment by danlapps** [comment]
Part of path, was in a rush, will do some couple path tonight

```SQL
-- Pathing for  Entry: Entry: 21801 (Vhel'kur)
SET @NPC := 21801;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=-5140.628,`position_y`=537.6068,`position_z`=225.5867 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-5140.628,537.6068,225.5867,0,0,0,0,100,0),
(@PATH,2,-5047.682,660.9525,148.8644,0,0,0,0,100,0),
(@PATH,3,-5011.98,674.3496,148.8644,0,0,0,0,100,0),
(@PATH,4,-4981.461,669.827,148.8644,0,0,0,0,100,0),
(@PATH,5,-4959.014,632.2751,148.8644,0,0,0,0,100,0),
(@PATH,6,-4943.981,608.1472,148.8644,0,0,0,0,100,0),
(@PATH,7,-4929.495,593.4562,148.8644,0,0,0,0,100,0),
(@PATH,8,-4910.322,557.0013,148.8644,0,0,0,0,100,0),
(@PATH,9,-4886.5,522.941,148.8644,0,0,0,0,100,0),
(@PATH,10,-4860.481,492.9438,148.8644,0,0,0,0,100,0),
(@PATH,11,-4853.529,472.7724,148.8644,0,0,0,0,100,0),
(@PATH,12,-4853.905,449.3954,148.8644,0,0,0,0,100,0),
(@PATH,13,-4862.35,417.3469,148.8644,0,0,0,0,100,0),
(@PATH,14,-4904.073,347.1447,148.8644,0,0,0,0,100,0),
(@PATH,15,-4938.952,289.3222,148.8644,0,0,0,0,100,0),
(@PATH,16,-4959.224,247.5302,148.8644,0,0,0,0,100,0),
(@PATH,17,-4971.73,201.8298,148.8644,0,0,0,0,100,0),
(@PATH,18,-4979.256,156.9421,148.8644,0,0,0,0,100,0),
(@PATH,19,-4987.867,132.5271,148.8644,0,0,0,0,100,0),
(@PATH,20,-4998.63,107.5142,148.8644,0,0,0,0,100,0),
(@PATH,21,-5020.076,73.21224,148.8644,0,0,0,0,100,0),
(@PATH,22,-5061.159,55.51009,148.8644,0,0,0,0,100,0),
(@PATH,23,-5077.839,49.82715,148.8644,0,0,0,0,100,0),
(@PATH,24,-5112.819,49.43273,148.8644,0,0,0,0,100,0),
(@PATH,25,-5175.664,65.2347,163.3922,0,0,0,0,100,0),
(@PATH,26,-5198.992,107.9043,173.1977,0,0,0,0,100,0),
(@PATH,27,-5165.273,219.0713,198.2255,0,0,0,0,100,0),
(@PATH,28,-5113.013,300.7207,198.2255,0,0,0,0,100,0),
(@PATH,29,-5109.759,353.3949,226.7533,0,0,0,0,100,0),
(@PATH,30,-5113.028,378.9975,240.6144,0,0,0,0,100,0),
(@PATH,31,-5122.197,411.4973,243.2811,0,0,0,0,100,0),
(@PATH,32,-5140.628,537.6068,225.5867,0,0,0,0,100,0),
(@PATH,33,-5047.682,660.9525,148.8644,0,0,0,0,100,0),
(@PATH,34,-5011.98,674.3496,148.8644,0,0,0,0,100,0);
-- 0x1C39A84240154A4000002100000AE735 .go -5140.628 537.6068 225.5867
```

**Comment by danlapps** [comment]
This still should be a full run since 32 is repeat of 1.  

@Rushor Should I remove 33+ in that case ?

**Comment by Kittnz** [comment]
What else needs to be added?

**Comment by Rushor** [comment]
malcrom mentioned something with an event :/
