### ISSUE TITLE
BG/SOA GameObjects not clickable

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13091]
In Strand of the ancients BG, some times you can't touch the relic or the flags. You clic but nothing happens and the mouse pointer doesn't change aspect when you put over the object. Also, I tried to target object with the GM and It's imposible, a message saying: nothing was found appears. I don't know how to reproduce, because it doesn't happen always.

890790475765af0712cecb72caa24b086514fe82

**Comment by Nexus-WoW** [comment]
Does someone figured out which ID i need for the Titan Relic?

**Comment by Aokromes** [comment]
Maybe core needs to remove flags after battle started.

**Comment by ccrs** [comment]
same problem with harpoon launchers on Razorscale

**Comment by ANARCHO-PUNK** [comment]
It seems the problem is unloading grid. With the flag 32 and GridUnload = 0 relic works fine.

**Comment by Runico** [comment]
@Killyana, I think relic should be clickable after main door destroyed

**Comment by sirikfoll** [comment]
Any news?

**Comment by Aokromes** [comment]
No.

**Comment by sirikfoll** [comment]
I think that the Relic doesn't need to have the ``GO_FLAG_NOT_SELECTABLE`` since the cpp https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp#L854 handles when the relic use should have effect. This fix the problem:
```sql
UPDATE `gameobject_template` SET `flags`=32 WHERE `entry`=192834;

**Comment by Frytiks** [comment]
I think that flag is set from sniff and it's because cheater maybe, just set when last gate is destroyed go-RemoveFlag(......flags);

**Comment by Aokromes** [comment]
Core needs to remove flags during runtime.
After beach door is broken the flags between the beach walls and next walls must be allowed to be selected.
The same for the next gos.

**Comment by joschiwald** [comment]
https://gist.github.com/joschiwald/ae12a892b4cdb128a666
