### ISSUE TITLE
[AV|NPC] Bossadds Mindcontrole

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13105]
TrinityCore rev. cba59eb
fresh db

All Adds from all MainBosses in Alteracvalley can be mindcontolled.
I don't know if this is blizzlike. 
Probably someone find some proofs for this(or against it).
Generally the most Bosses are immune against MC.

http://wotlk.openwow.com/npc=14765
http://wotlk.openwow.com/npc=14773
http://wotlk.openwow.com/npc=14777
http://wotlk.openwow.com/npc=14772
##

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
