### ISSUE TITLE
[crash] Crossfactionbg + Wintergrasp

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13118]
I have these crashes in less than 20 min and a loot of latency.

http://pastebin.com/CQG4k52N
http://pastebin.com/CQG4k52N

d7b0ee7c0366bf78e09f4eca5f93e65361c5a2b6
Ubuntu 14.04
passive antihack patch, pvpranks, and Transmogrification from Rochet2

**Comment by jackpoz** [comment]
did you disable wintergrasp to check if it was the cause of the issue ?

**Comment by Pirricli** [comment]
No, I didn't, But I haven't had the problem since a long time.

**Comment by jackpoz** [comment]
Even if this issue is closed, crossfactionbg patch should handle this case in a clean way without any chance of crash

**Comment by Pirricli** [comment]
Yesterday, but it's several months since this crash have appeared.

http://pastebin.com/

8a54cc043b018ff8f3c849a48d347862cd03f3fc

**Comment by Runico** [comment]
http://pastebin.com/CKR2KXHq this crash relate to this issue?

**Comment by jackpoz** [comment]
@Runico please follow the instructions https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md before posting a crash report.

Let me bold the part of interest
>**Add which revision of Trinitycore you're running on (this is the CORE revision, not your client version)**

>**Add a list of which modifications that has been done to the core (if any) if those modifications aren't public available you must share the code if you/we see that they can be reason of bug, if you don't use a clean core and you don't share the code if it afects the bug or the files of the bug (crash) the ticket will be closed.**

**Comment by Runico** [comment]
@jackpoz Sorry, Rev: 6a637f6b1c186eb15373fce443d729dcc74e5361

**Comment by jackpoz** [comment]
Your crash looks unrelated to this issue, what's your max freeze time setting in worldconf ?

**Comment by Runico** [comment]
@jackpoz 60Secs, this crash happened on 06:00 AM with 5 players and 2 days uptime

**Comment by Pirricli** [comment]
I don't know if it's related or not.

http://pastebin.com/MjEuNeRq

0b9cd22a6b5a0cca6e3c07dd5ae077ddbdfc3992

**Comment by jackpoz** [comment]
it's still the same crash, as suggested before disable wintergrasp or remove the crossfactionbg or fix the crash added by that custom patch.

**Comment by jackpoz** [comment]
Remove crossfactionbg patch or ask the author to fix it

**Comment by ryoting** [comment]
can fix Crossfaction Battlegrounds in latest rev of TC? TDB61.

**Comment by Aokromes** [comment]
That request don't belongs here.

**Comment by irgc** [comment]
confirm 
Crossfaction Battlegrounds for tdb 63

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13118#issuecomment-115344762
