### ISSUE TITLE
[4.3.4] Choosing battleground wtih H button

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#13129]
When pressing H to sign up for a battleground, it sometimes selects a random battleground?

Like when i click warsong gulch sometimes it goes to warsong, other times it wants to queue me up for Arathi, Alterac etc. 

Can anyone confirm?

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Shauren** [comment]
hell no, this was about bad packet structure and got invalidated the second we changed supported client version
