### ISSUE TITLE
A little problem about creature's model when it died

### ISSUE THREAD

**Issue by kldxzzhc2** [TrinityCore/TrinityCore#13137]
DB up-to-date
CORE 961aaf5b9d7b449b107e25e621e133eeeb0ca049

For example, creature 3840, when in combat, it will cast 8041 (the aura will change creature's model), when player kill it when it has aura 8041, you'll find the creature changes to default model and lay on the ground directly, looks very strange. I think it should remove the aura first, and then play the die action.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/13441
May be this can be closed.

**Comment by tkrokli** [comment]
I agree, this issue can be closed. The issue presented in #13441 is not NPC specific, it is about all Units.
