### ISSUE TITLE
[6.x] Some missing 434 creature_loot_template

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#13146]
Revision: https://github.com/TrinityCore/TrinityCore_4.3.4_DB_Alpha/commit/64a14594cbf91bee5c89de92fc8d9922ff121571

Following creature_loot_template are missing, but used as loot id in DB (cause of startup errors).

39946 (also used as lootid for creature_template: 39746, 39805)
39947 (also used as lootid for creature_template: 39751, 39920)
39948 (also used as lootid for creature_template: 39747, 39823)
48518

http://www.wowhead.com/npc=39946
http://www.wowhead.com/npc=39947
http://www.wowhead.com/npc=39948
http://www.wowhead.com/npc=48518

**Comment by Rushor** [comment]
```sql
select * from creature_template where entry IN (39946, 39947, 39948, 48518);
```

no lootid assigned - no startup error
