### ISSUE TITLE
[3.3.5][6.x][Core|Spell] Animal Blood

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13162]
core 961aaf5
db up to date

If you have the aura http://www.wowhead.com/spell=46221 and if you walk into water, you will cast this spell: SPELL_SPAWN_BLOOD_POOL = 63471 in order to create the Blood-GO.

Problem:
The GO: http://de.wowhead.com/object=194479 should always be direktly on the water. Right now the go is summoned sometimes over the water and sometimes under the water - if i walked into the water.

http://www.pic-upload.de/view-24643579/WoWScrnShot_091814_112738.jpg.html
https://github.com/TrinityCore/TrinityCore/blob/7d1d55124c1e289748d2afefae896c97f710e57b/src/server/scripts/Spells/spell_generic.cpp#L195

prio: low
##

**Comment by Aokromes** [comment]
maybe this needs vmaps checking?

**Comment by Killyana** [comment]
The issue is the spell is not caste when the aura is removed https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L190-L195
If you cast the spell manually it will spawn the gob correctly

**Comment by sirikfoll** [comment]
Summon position is still wrong.
For the missing spell cast:
```diff
diff --git a/src/server/scripts/Spells/spell_generic.cpp b/src/server/scripts/Spells/spell_generic.cpp
index e8c1b3438f..91c4ffe302 100644
--- a/src/server/scripts/Spells/spell_generic.cpp
+++ b/src/server/scripts/Spells/spell_generic.cpp
@@ -189,9 +189,11 @@ class spell_gen_animal_blood : public AuraScript
 
     void OnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
     {
+        if (GetTargetApplication()->GetRemoveMode() == AURA_REMOVE_BY_EXPIRE)
+            return;
+
         if (Unit* owner = GetUnitOwner())
-            if (owner->IsInWater())
-                owner->CastSpell(owner, SPELL_SPAWN_BLOOD_POOL, true);
+            owner->CastSpell(owner, SPELL_SPAWN_BLOOD_POOL, true);
     }
 
     void Register() override
```

**Comment by Killyana** [comment]
Remaining issue here https://github.com/TrinityCore/TrinityCore/issues/23091
