### ISSUE TITLE
[3.3.5][6.x] Idea for new condition for NPC Flags

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#13174]
There are a number of npcs on retail where when player first comes into contact with npc they offer quest only and do not give gossip, then once a certain requirement is met ie a quest rewarded then after that displays gossip

On tc these npcs show gossip right from start as there is no way of conditioning properly since if you remove flags then player who may be entitled to see that gossip wont see it either.

Idea is for a new condition for flags, where for condition just specifies npc entry and mask of flags on that npc for which condition must be met for those flags to be available then unless condition is met those flags are not shown to player who does not meet requirement.
##

**Comment by offl** [comment]
#26039
