### ISSUE TITLE
[3.3.5] Fishing bobber interrupts mana regen triggering 5 second rule

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13204]
**Core:** https://github.com/TrinityCore/TrinityCore/commit/4c25454b77dcf86a890169232d2719792f817949
**DB:** TDB_full_335.52+2013_07_17 + updates

**Bug:**

When you cast your fishing bobber it interrupts mana regen causing the player to have to wait the "5 second rule" after every cast.

**Details:**

You can observe the behavior by taking a mid-level character with low spirit such as a level 16 Hunter, spending most of its mana in combat and then fishing immediately afterward. Each time you cast the bobber the mana regen stops and starts 5 seconds later.

Fishing bobber cast should not be counted as a spell in terms of mana regen. This is especially problematic fishing in high-aggro zones. You end up in combat with low mana most of the time.
##

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by MrSmite** [comment]
> this issue is still valid?

Not sure on this one.

I haven't compiled a core recently for my new machine but on my old box, this server is running and fishing still pauses mana regen. The interesting thing though is when the regen resumes it jumps.

I had nothing applied to increase mana regen. I spent all my mana using "Mend Pet" and waited for the regen to start. It was counting up b 1: 100...101...102...103 and when I cast fishing it paused but when the 5 second rule ended, instead of starting at 104, it immeditately jumped to 108.

rev 2db9269 (from Jun 10, 2016)

**Comment by illfated** [comment]
Is there another way to check the mana regen progression (from empty to full) besides watching the player character portraits in the GUI? Even when comparing the main character portrait with yourself (select using F1 or by clicking), the progress will look different, one counts up evenly while the other one jumps. I am guessing that it could show up in a log of some kind, but I am not sure where to look.

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
