### ISSUE TITLE
[3.3.5][6.x] Magisters' Terrace - Kalecgos spawn bug

### ISSUE THREAD

**Issue by XJIOP** [TrinityCore/TrinityCore#13208]
TrinityCore rev. 4c25454b77dc

http://wowhead.com/npc=24850

Magisters' Terrace on the balcony after every watching video spawns Kalecgos. ie if watched 5 players in one group then spawns 5 npc.

and one player can spam many npc)

**Comment by Rushor** [comment]
just researched this on retail -> the npc should only be spawned once by clicking on the go

http://pokit.org/get/?485b8c886892b98eda833cee7f2f515c.jpg

**Comment by Nyeriah** [comment]
Yeah, he flies down while  you're watching a movie, it's delayed, and usually takes long for him to show up. The problem with this is that it's handled by event sent by the GO I think, and we can't condition that (event_scripts too rusty)

**Comment by Rushor** [comment]
http://collab.kpsn.org/display/tc/gameobject_template
btw : 
GAMEOBJECT_TYPE_CAMERA = 13

    data0: open (LockId from Lock.dbc)
    data1: camera (Cinematic entry from CinematicCamera.dbc)


probably someone can add :  
data2: event_scripts

this was confusing :/

**Comment by Rushor** [comment]
okay irgore the c++ part.

only stuff which is needed here:

```sql
DELETE FROM `event_scripts` WHERE `id`=16547;
-- Scrying Orb SAI
SET @ENTRY := 187578;
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,1,0,0,64,0,100,1,0,0,0,0,12,24844,2,300000,0,0,0,8,0,0,0,209.912,-318.697,14.005,1.181,"Scrying Orb - On Gossip Hello - Summon Creature 'Kalecgos' (No Repeat)");
```

thx 2 nyeriah for this event_script note
thx 2 dr-j for the sai propose

**Comment by Nyeriah** [comment]
I'm not sure if SAI is the answer. The event is sent so in my opinion it should be handled, SAI ignores it, so in my opinion, hack :PP

**Comment by Rushor** [comment]
> so in my opinion, hack :PP
but event_script itself is nor properly implemented

**Comment by Nyeriah** [comment]
Honestly, the only reason I haven't touched this is because there are missing parts of the event. Like, the dragon flying from out of the balcony (in other words, waypoints) and turning into human. There's also supposed to be a (quite long, so to speak) delay before Kalecgos actually spawns. I suppose it's timed with the movie. I'll PR something for it soon anyway.
