### ISSUE TITLE
[335] Mixology does not extend Elixir of Water Breathing

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13205]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/4c25454b77dcf86a890169232d2719792f817949
__DB:__ TDB_full_335.52+2013_07_17 + updates

__Bug:__

[Mixology](http://www.wowhead.com/spell=53042) does not extend the length of [Elixir of Water Breathing.](http://www.wowhead.com/item=5996)

__Details:__

Mixology is supposed to extend the duration and effect of Elixirs and Flasks that *you* can make. I mixed one and drank it but it still had a 30 minute duration.

__Note:__

#2172 mentions that Mixology also does not increase the effect of elixirs and flasks so it is somewhat related in that it involves the same spell, just a different component.

**Comment by Aokromes** [comment]
No answer after months, closing, if this bug is still valid open a new ticket.
