### ISSUE TITLE
[335] Elixir of Minor Accuracy can be used with other battle elixirs

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13206]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/4c25454b77dcf86a890169232d2719792f817949
__DB:__ TDB_full_335.52+2013_07_17 + updates

__Bug:__

[Elixir of Minor Accuracy](http://www.wowhead.com/item=45621/elixir-of-minor-accuracy) should not be able to be used with other battle elixirs since it is not a flask.

__Details:__

For example you can use one at the same time as [Elixir of Minor Agility](http://www.wowhead.com/item=2457)

**Comment by Killyana** [comment]
Yes it fix the issue:
``` sql
DELETE FROM `spell_group` WHERE `id`=1 AND `spell_id`=63729;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES 
(1, 63729);
