### ISSUE TITLE
[3.3.5][6.x]Spell Mana Usage

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#13218]
Spells are using way more mana than on offi.

For example:

Twilight Dark Shaman http://www.wowhead.com/npc=5860
Spell: Lightning Bolt http://www.wowhead.com/spell=34345

This spell should use 90 mana but instead uses 254 mana on TC. Creatures are running out of mana far faster than they do in offi.
##

**Comment by Rushor** [comment]
this issue is also present on 6.x?

**Comment by Kittnz** [comment]
confirmed, after a few seconds in combat you mana regen really quick like you were drinking out of combat. this is broken, it stops regening when you cast a spell, but after a few seconds it regens again like maniac

54424aff3051bdc2a05d44cbd56adf6f47b98229

**Comment by jackpoz** [comment]
> Spells are using way more mana than on offi.

> confirmed, after a few seconds in combat you mana regen really quick

your confirm seems unrelated to this issue

**Comment by Kittnz** [comment]
apparently, maybe more of a comment on what @NorthStrider said

**Comment by greenbagels** [comment]
TrinityCore rev. c2a36c9e89c7 2017-01-30 17:22:01 +0100 (3.3.5 branch) (Unix, Release, Static)
Using TDB 355.62_2016_10_07
I can't get [Twilight Dark Shaman](http://www.wowhead.com/npc=5860) to actually cast anything, which could be what @jackpoz was mentioning. Could this be a new issue (or perhaps this issue stems from a mob-specific problem?)

**Comment by Killyana** [comment]
https://woehead.way-of-elendil.fr/?spell=34345
Cost : 90 Mana   /   School Damage: Value: 64 to 86
With the npc http://www.wowhead.com/npc=5860
Cost : 236 Mana   /   School Damage: Value: 176 to 212

https://woehead.way-of-elendil.fr/?spell=9613
Cost | 90 Mana  /  School Damage: Value: 64 to 86
With the npc https://www.wowhead.com/npc=19411
Cost : 406 Mana   /   School Damage: Value: 287 to 365

Looking to the npc level and the damage that must be done the scaling is correct.
Also I checked some videos where the npc https://www.wowhead.com/npc=19411 is casting the shadow bolt and the mana cost looks correct.
So the scaling is correctly calculated for the damage and mana cost.
