### ISSUE TITLE
[3.3.5][Spell][Hunter] Roar of Sacrifice - Damage Copie

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13211]
core 961aaf5 
db up to date
http://wotlk.openwow.com/spell=53480
Hunterability.

How it should work:
-create hunter
-find ally mate
-summon pet
-cast spell: Roar of Sacrifice on ally
-ally will no longer get critical hits AND:
20% of the damage that gos to the ally should be magically copied to the hunter's pet.

How it works:
-the critdamage reductions works(sometimes, see the other linked issue for futher infos), but the 20% dmg will not be copied to the pet.

(Already closed issue in https://github.com/TrinityCore/TrinityCore/issues/705,
shitty dumbassreport in https://github.com/TrinityCore/TrinityCore/issues/7882)

I already tried this:
```diff
case 53480: // Roar of Sacrifice Split damage
                spellInfo->Effect[EFFECT_1] = SPELL_EFFECT_APPLY_AURA;
                spellInfo->EffectApplyAuraName[EFFECT_1] = SPELL_AURA_SPLIT_DAMAGE_PCT;
                spellInfo->EffectMiscValue[EFFECT_1] = SPELL_SCHOOL_MASK_ALL;
                spellInfo->AttributesEx2 |= SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS;
                spellInfo->EffectBasePoints[EFFECT_1] = 20;
                spellInfo->EffectImplicitTargetA[EFFECT_1] = TARGET_UNIT_TARGET_ALLY;
                spellInfo->EffectImplicitTargetB[EFFECT_1] = 0;
                spellInfo->EffectValueMultiplier[EFFECT_1] = 1;
                break;
```
but this changed nothing. I tried to copy the function from the spell: http://de.wowhead.com/spell=6940

could someone give me some hints for this? I think i could be an easy fix, because we have already a spell, where it works perfectly.

**Comment by Rushor** [comment]
still preset on current core https://github.com/TrinityCore/TrinityCore/commit/b2575a04ce076aaaa0d0cb38737950b202127132 the damage will not be transfered to the pet

**Comment by robinsch** [comment]
not tested https://gist.githubusercontent.com/robinsch/13218e5f672db9b09096/raw/83026afcf8f47f0ecd167e90eab8c53e126b3d47/gistfile1.txt

**Comment by Rushor** [comment]
some related stuff

```c++
// 53480 - Roar of Sacrifice
class spell_hun_roar_of_sacrifice : public SpellScriptLoader
{
    public:
        spell_hun_roar_of_sacrifice() : SpellScriptLoader("spell_hun_roar_of_sacrifice") { }

        class spell_hun_roar_of_sacrifice_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_hun_roar_of_sacrifice_AuraScript);

            bool Validate(SpellInfo const* /*spellInfo*/)
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_HUNTER_SPELL_ROAR_OF_SACRIFICE_DMG))
                    return false;
                return true;
            }

            void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
            {
                PreventDefaultAction();
                if (eventInfo.GetDamageInfo())
                {
                    int32 damage = CalculatePct(eventInfo.GetDamageInfo()->GetDamage(), 20);
                    GetTarget()->CastCustomSpell(SPELL_HUNTER_SPELL_ROAR_OF_SACRIFICE_DMG, SPELLVALUE_BASE_POINT0, damage, GetCaster(), true, NULL, aurEff);
                }
           }

            void Register()
            {
                OnEffectProc += AuraEffectProcFn(spell_hun_roar_of_sacrifice_AuraScript::HandleProc, EFFECT_0, SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_hun_roar_of_sacrifice_AuraScript();
        }
};
```

**Comment by pak3935** [comment]
working ?

**Comment by Rushor** [comment]
the spellscript does not work actually, someone needs to test the patch from robinsch

**Comment by pak3935** [comment]
> not tested https://gist.githubusercontent.com/robinsch/13218e5f672db9b09096/raw/83026afcf8f47f0ecd167e90eab8c53e126b3d47/gistfile1.txt

does not work

**Comment by Greymane** [comment]
Proc trigger will fail on

                // If not trigger by default and spellProcEvent == NULL - skip
                if (!isTriggerAura[aurEff->GetAuraType()] && triggerData.spellProcEvent == NULL)
                    continue;

SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE is not set as a trigger aura, need simple spell_proc_event entry just with entry and procFlags.

**Comment by pak3935** [comment]
`case 53480:
				spellInfo->Effects[EFFECT_1].Effect = SPELL_EFFECT_APPLY_AURA;
				spellInfo->Effects[EFFECT_1].ApplyAuraName = SPELL_AURA_SPLIT_DAMAGE_PCT;
				spellInfo->Effects[EFFECT_1].TargetA = TARGET_UNIT_TARGET_ALLY;
				spellInfo->Effects[EFFECT_1].DieSides = 1;
				spellInfo->Effects[EFFECT_1].BasePoints = 19;
				spellInfo->Effects[EFFECT_1].MiscValue = 127; // all schools
				break;`

**Comment by pak3935** [comment]
case 53480:
				spellInfo->Effects[EFFECT_1].Effect = SPELL_EFFECT_APPLY_AURA;
				spellInfo->Effects[EFFECT_1].ApplyAuraName = SPELL_AURA_SPLIT_DAMAGE_PCT;
				spellInfo->Effects[EFFECT_1].TargetA = TARGET_UNIT_TARGET_ALLY;
				spellInfo->Effects[EFFECT_1].DieSides = 1;
				spellInfo->Effects[EFFECT_1].BasePoints = 19;
				spellInfo->Effects[EFFECT_1].MiscValue = 127; // all schools
				break;

**Comment by Rushor** [comment]
@pak3935: well with this update the damage will be redirected to the hunter, not to the pet :D

**Comment by robinsch** [comment]
Use my diff and https://github.com/TrinityCore/TrinityCore/issues/13211#issuecomment-189573023

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.
