### ISSUE TITLE
[434] Phasing system is broken [$20]

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#13212]
Remember Subv to write here what's broken to fix worgen start zone.

Subv: keep this in mind please, phases without spells, multiple terrain swaps per phase, multiple worldmapswaps with / withouts spells, conditions for phases

Long talk about this:
http://pastebin.com/twFWuum1

**Comment by gonzo1247** [comment]
The phase system works down to one thing. If uses phase groups, the creature is set to the phases of the phase groups but also in phase 0, but should as far as I can not judge that to be so.

**Comment by Aokromes** [comment]
No feedback after 3 months, closing.
If this bug is still valid open a new ticket.
