### ISSUE TITLE
[3.3.5] [authserver] Unused variable in AuthSession

### ISSUE THREAD

**Issue by Nefarion** [TrinityCore/TrinityCore#13217]
bool [AuthSession._isAuthenticated](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/authserver/Server/AuthSession.h#L74) (authserver project) is only written to, but never read from, so i wanted to know if it is really necessary to have it there.

It is used twice:
[AuthSession::HandleLogonProof():574](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/authserver/Server/AuthSession.cpp#L574)
[AuthSession::HandleReconnectProof():725](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/authserver/Server/AuthSession.cpp#L725)

**Comment by tkrokli** [comment]
Interesting. What would the advantage be of removing https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/authserver/Server/AuthSession.h#L74 if it is proven to be unused?
