### ISSUE TITLE
[3.3.5a] unknown TriggerSpell

### ISSUE THREAD

**Issue by SoS-Trinity** [TrinityCore/TrinityCore#13222]
DB - TDB 56 + Updates
Revision - https://github.com/TrinityCore/TrinityCore/commit/999863137254e426ccb48fb510d482a1f34c8bab

Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 64440 (effIndex: 1) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 59237 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 31226 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 54775 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 48876 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
##

**Comment by Frytiks** [comment]
Yeah, confirmed. I have too so much spam.

**Comment by tkrokli** [comment]
Compile last week, TrinityCore rev. 058457dda922 2015-03-27 21:38:23 +0100 (3.3.5 branch) (Win32, Release) : 
```
Removed GameObject (GUID: 164569 Entry: 31442 SpellId: 818 LinkedGO: 0) that just lost any reference to the owner (GUID Full: 0x0000000000000002 Type: Player Low: 2) GO list
Removed GameObject (GUID: 164568 Entry: 29784 SpellId: 818 LinkedGO: 31442) that just lost any reference to the owner (GUID Full: 0x0000000000000002 Type: Player Low: 2) GO list
Removed GameObject (GUID: 164550 Entry: 31442 SpellId: 818 LinkedGO: 0) that just lost any reference to the owner (GUID Full: 0x0000000000000009 Type: Player Low: 9) GO list
Removed GameObject (GUID: 164549 Entry: 29784 SpellId: 818 LinkedGO: 31442) that just lost any reference to the owner (GUID Full: 0x0000000000000009 Type: Player Low: 9) GO list

**Comment by selenir** [comment]
Is there any option that this crashes the server? 

Last lines of worldserver:

 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Could not load MMAP name:Northrend, id:571, x:26, y:26 (mmap rep.: x:26, y:26)
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?
Segmentation fault

**Comment by DDuarte** [comment]
Hard to say with the info you provided. Get a debug mode crash log and open a new issue.

**Comment by diavolb** [comment]
It does not crash.
But there is a terrible flood.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13222#issuecomment-64203417

**Comment by Killyana** [comment]
Only remaining error:
``` 
Spell::EffectTriggerSpell spell 47568 tried to trigger unknown spell 53258
Spell::EffectTriggerSpell spell 61077 tried to trigger unknown spell 47805
Spell::EffectTriggerSpell spell 7405 tried to trigger unknown spell 58568
Spell::EffectTriggerSpell spell 44286 tried to trigger unknown spell 19229
