### ISSUE TITLE
[3.3.5][6.x] Naxxramas teleports do not work

### ISSUE THREAD

**Issue by XJIOP** [TrinityCore/TrinityCore#13255]
TrinityCore rev. c23c66f7193e
Last Updated TDB

in each quarter at the last boss has teleports, and they do not work.
http://i59.tinypic.com/25056vk.jpg

**Comment by ariel-** [comment]
@Nyeriah 
> Okay, so everything that is needed for them to work has got pushed, yet, I still have no ideas why do they despawn after being used, or how to solve it without hacks.

See ```c++ GameObject::Use ```

```c++
            SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
            SetLootState(GO_ACTIVATED, user);

            // this appear to be ok, however others exist in addition to this that should have custom (ex: 190510, 188692, 187389)
            if (info->goober.customAnim)
                SendCustomAnim(GetGoAnimProgress());
            else
                SetGoState(GO_STATE_ACTIVE);
```

**Comment by jackpoz** [comment]
@Nyeriah still no clue about those despawning gameobjects ?

**Comment by Nyeriah** [comment]
Nope, and I also didn't look further into this

**Comment by lainimer** [comment]
Confirm bag https://github.com/TrinityCore/TrinityCore/commit/e142c3b87397a84a9169c25bc211c80ce917d508

**Comment by Nyeriah** [comment]
Please don't post into issues if you don't have anything to add to them. It does not help to confirm an issue that is already confirmed.

**Comment by lainimer** [comment]
I fix it.

**Comment by Keader** [comment]
still valid @Treeston ?

**Comment by Treeston** [comment]
no idea, didn't touch them

**Comment by Killyana** [comment]
The remaining issue is generic, the gob despawn one the first player use it.
