### ISSUE TITLE
[3.3.5] Tightly Sealed Trunk Is Sometimes Empty

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13261]
**Core:** https://github.com/TrinityCore/TrinityCore/commit/c3805aa5123a58c5c5778652d80b119c2cbc630c
**DB:** TDB_full_335.52_2013_07_17 + updates

**Bug:**

Sometimes when you open a [Tightly Sealed Trunk](http://www.wowhead.com/item=20708) for the first time, it will be empty.

**Notes:**

I haven't fished up any of the other lootable objects (eg: [Watertight Trunk](http://www.wowhead.com/item=21113)) so I can't say if this applies to all lootable items but it sounds like an issue with the loot tables. There shouldn't be a circumstance when these are completely empty.

These lootable items from fishing are the primary source for the [Weather-Beaten Journal](http://www.wowhead.com/item=34109#comments)
##

**Comment by offl** [comment]
Drop shouldn't be guaranteed https://youtu.be/QMNpj3NmIss?t=140

**Comment by offl** [comment]
Can be closed -_-

**Comment by tkrokli** [comment]
Closing this as a non-issue.
