### ISSUE TITLE
Faerie Fire - two bugs

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1326]
the first bug related to this ticket - http://www.trinitycore.org/t/trinitycore/ticket/1099
in the beginningi thougth the bug is with Cyclone but it appears that only faerie fire can go 
through it.

== server info ==
our server work on Linux
TrinityCore Rev: 11721+
we just update to e023a32 not long ago.

**Comment by danlapps** [comment]
Is this still valid issue after last listed merge ?
