### ISSUE TITLE
[3.3.5][6.x] Bank [count item stack, only visual bug]

### ISSUE THREAD

**Issue by XJIOP** [TrinityCore/TrinityCore#13271]
TrinityCore rev. b33695a2efe9

When you shift item in bank, on some items appears fake size of stack.
It only visually and not so is critical.

https://www.youtube.com/watch?v=AqKFMgODdKs
##

**Comment by DDuarte** [comment]
By @MrSmite in #14571:

> __Rev:__ https://github.com/TrinityCore/TrinityCore/commit/5b5c0938da0faa5d3fcf4fd062fa712a448a67ff
> __DB:__ TDB_full_335.57_2014_10_19 + updates
> 
> __Bug:__
> 
> When you place (or move) a Silvermoon Armor (random enchant) in the guild bank, it changes the item count of the item below it to 2803.
> 
> __Details:__
> 
> Happened with both [Silvermoon Armor of the Sun](http://www.wowhead.com/item=31256/silvermoon-armor) and [Silvermoon Tunic of the Wild](http://www.wowhead.com/item=31263/silvermoon-tunic). When the character that originally looted it placed it in the guild bank, it changed the item count of [The 1 Ring](http://www.wowhead.com/item=8350/the-1-ring) below it to 2803. When a different character moved it to a different slot, it changed the item count of [Strong Fishing Pole](http://www.wowhead.com/item=6365/strong-fishing-pole) to 2803. Also had the same effect on [Holy Protection Potion](http://www.wowhead.com/item=6051/holy-protection-potion).
> 
> __Notes:__
> 
> > * Player class does not appear to be the issue, happend on a Hunter, Paladin and Warlock (Alliance)
> > * __Did not__ test on Horde (but most likely is irrelevant)
> > * It does not hapen in player bank or inventory
> > * The item with the wrong count does reset if removed from the guild bank
> > * The item with the wrong count does reset if moved to a different slot in the guild bank
> > * Player __can not__ withdraw any of the extra items, only what the original count was
> > * Placing an item in the bank under one of the Silvermoon items __does not__ increase the count

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
can't reproduce on 965b1455b100
