### ISSUE TITLE
[3.3.5][6.x][Core/Spells] Damage multiplier inherited from target instead of caster

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#13287]
Commit: c17d148992b9c5d5d8afab73e26fa2404f727392
DB: 335.56
Custom Patches: none.

This problem is noticeable with Harvest Soul (ID=73655), cast by The Lich King before Frostmourne phase, this spell teleports player to Frostmourne and applies a damage aura.

Now it seems that player active damage multipliers are calculated for the DoT part of the spell, making it do much more damage than it is supposed to.

Base Damage should be 2000 shadow (according to Spell.DBC) now in ICC you have 30% damage buff, plus any damage buff your class gets through talents/spells, so instead of 2000 you get (2000 \* 130%) = 2600
##

**Comment by wowcamper** [comment]
"Another bug is with wicked spirits inside the room, they appear later than they should and the spirit bombs are dropped from them, now if the players enter the room, they explode even there are no wicked spirits - bug".

This temp fix solve bombs too?

**Comment by ariel-** [comment]
164af391c9662732dfc9cfe677c48bd3f927c2be has same problem as Harvest Soul. maybe we should skip adding done mods when the spell is a negative self cast?
