### ISSUE TITLE
[3.3.5][6.x] Master Loot BUG

### ISSUE THREAD

**Issue by ryancheung** [TrinityCore/TrinityCore#13300]
If the Master Looter get disconnect before loot the boss, when he get back online, he can't distribute the items of the boss.

Hash https://github.com/TrinityCore/TrinityCore/commit/3f5e3a877a3a26948a607214730342159100f8f0
DB: Latest

**Comment by jackpoz** [comment]
Any update on this ?

**Comment by Frytiks** [comment]
It's still done. Just log out when u kill boss, and u can't loot him. It's not high priority bug. But sometimes when you kill boss, like a deathbringer saufrang, and u must loot from gameobject. U click and window with loot doesn't apper, u must re-log or change raid leader to someone, who can loot it.

**Comment by jackpoz** [comment]
so it's not about getting disconnected but logging out ? can you post the npc entry of a boss where this always happens ?

**Comment by Frytiks** [comment]
Players says, mostly in ICC all bosses, but i think its global bug for all bosses.

**Comment by jackpoz** [comment]
did you personally experienced this bug or it's just a report from other players ?

**Comment by Frytiks** [comment]
Personally, and from players too

**Comment by SQLfix** [comment]
Confirm

**Comment by jackpoz** [comment]
could someone try reproducing this bug again and posting clear 100% working detailed how to reproduce steps ?

**Comment by Runico** [comment]
@jackpoz, I haven't experienced this bug since 3 months ago

**Comment by jackpoz** [comment]
what's the current status of this issue ?

**Comment by innermous** [comment]
I am working on this issue currently, and I must state one thing.
It's **NOT** caused by ML disconnect BUT leader of the group. This happens with ML staying connected accurate in 60sec after leader relog (i.e. when leader disappears).

**Comment by innermous** [comment]
Update: issue can be reproduced with *all* types of loot distribution systems.
So, issue is a little bit deeper now  :cyclone:

**Comment by tkrokli** [comment]
In your video example, after the PL/ML DC'ed or logged out and you killed the next 2 mobs, it looks like you got the gray "not within range" color on your loot cursor icon. Have you tried relogging after the video example situation, to see if there is a distance glitch between corpse and your player character?

**Comment by innermous** [comment]
@tkrokli i think that's not an issue, as guys said before - this can be undone via changing master looter, for example. So it has something to do with group parameters changes, don't know. 
Simple relog on second char doesn't help, unfortunately.

**Comment by jackpoz** [comment]
I reproduced once the behavior with the ML case, with the loot icon being black/dark grey instead of the usual brownish and not CMSG_LOOT opcode received by worldserver.
Reproducing it again with Group Loot, creature->GetLootRecipient() returned NULL with the guid set to the offline Group Leader.

**Comment by jackpoz** [comment]
loot cases to handle:
- [ ] player in group kills a creature, dcs, team loots -> let team loot
- [ ] player not in group kills a creature, joins a group, both loot -> player can loot, group cannot
- [ ] player in group kills a creature, leaves the group, both loot -> player cannot loot, group can

**Comment by jackpoz** [comment]
thanks @innermous for the How To Reproduce steps
