### ISSUE TITLE
[4.3.4] Resurrection in different phase than one.

### ISSUE THREAD

**Issue by burnham** [TrinityCore/TrinityCore#13326]
When player died in another diferect phase that phase 1 and try resurrect is not possible.
Normal case:
* Create new player, player is in phase one.
* use command .Die
* Go back to your corpse.
* Player can be resurrect with out problem.

HERE is the main problem:
* Same player, cast spell 65141 (phase two).
* Player die
* Go back to your corpse and there is not corpse, because corpse is in phase one and player is in phase two
* Player still have the option to resurrect, but is not possible.

Testing with spell_area and ussing command .cast to give me the phase.

Using TrinityCore branch 4.3.4 rev. https://github.com/TrinityCore/TrinityCore/commit/42f5017261b577691e1d728cd209f8e51cde2f0b with out patches.

**Comment by Aokromes** [comment]
Try again on head.
