### ISSUE TITLE
[3.3.5][6.x] Taunt effects interrupting channeled spells

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#13335]
players easily can escape phases with taunt spells
for example, while rotface cast slime spray another player taunt him
then rotface will leave channeling and start attacking who taunt him
so phase escaped

this bug works almost for every channeling spell, like lord marrowgar ... etc

revision 7449231ce1f7c4ffadabbcb480ae2f28e766c068

**Comment by shorden** [comment]
any news ?

**Comment by Aokromes** [comment]
No.

**Comment by shorden** [comment]
@Greymane can you test this ?
        // switch target
	if (!HasUnitState(UNIT_STATE_CASTING))
        InterruptSpell(CURRENT_MELEE_SPELL);
        if (!meleeAttack)
            ClearUnitState(UNIT_STATE_MELEE_ATTACKING);

**Comment by SQLfix** [comment]
confirm . Need New News ! tnx

**Comment by Aokromes** [comment]
The new is no news.

**Comment by Runico** [comment]
LoL :dancer:

**Comment by Treeston** [comment]
@Greymane CURRENT_MELEE_SPELL is auto attack and similar, not channels.

**Comment by Aokromes** [comment]
@Runico @SQLfix @shorden test if https://github.com/TrinityCore/TrinityCore/pull/15641 fixes it

**Comment by Treeston** [comment]
@Runico aforementioned PR #15641 was just merged into 3.3.5 base, please build latest and see if it persists.

**Comment by Runico** [comment]
@Treeston, Okay, I will test it in next 2 days

**Comment by Nikectory** [comment]
Confirmed on https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

**Comment by Aokromes** [comment]
Test after 17f924a031e5ebbbc07a54acd61e738bf234867a any lower version "confirm" will be ignored.

**Comment by Nikectory** [comment]
@Aokromes ok, thanks

**Comment by Keader** [comment]
Test after 2ae85d86d3d1c6a465f9382ec31f6649afa4326c

**Comment by Aokromes** [comment]
No answer after 23d closing. If this bug is still valid open a new ticket, don't post here.
