### ISSUE TITLE
[Vehicle System] Evade when enter vehicles during combat

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1340]
Sometimes when you start combat with creatures and during combat enter vehicle, creatures go into evade mode + you lost combat mode. Dunno if this happens with all vehicles, mb its spell from npc_spellclick problem, but problem exists.

Database: TDB 335.11.39
Rev: aa91187e97d3bc44f0b2
##

**Comment by Voidx** [comment]
still

**Comment by Killyana** [comment]
On rev. cc4f86cc2bf4 creatures continue attacking the player inside the vehicle instead of the vehicle.

**Comment by Killyana** [comment]
This still happen after https://github.com/TrinityCore/TrinityCore/pull/19930
