### ISSUE TITLE
[4.3.4] Players get talent reset when they log in

### ISSUE THREAD

**Issue by eilwin** [TrinityCore/TrinityCore#13426]
When a player log into his account, he automatically get the reset flag "at_login", and when he log in server world his talents and spells get bugged. This seems to be only visual cause in DB spells still there.

OS: Win 32 & 64 bits
hash: 0fb9ba4f2848cf5a7e263e1b9d58cf101d063e85
branch: 4.3.4

**Comment by danlapps** [comment]
Can this be closed since it seems to be very rare incident and most likely local problems ?
