### ISSUE TITLE
[3.3.5][6.x] Melee spells activation in range

### ISSUE THREAD

**Issue by Doodlezero** [TrinityCore/TrinityCore#13461]
All melee spells and auto-attack have buggy attack in range.
On TC you can attack people with melee spells and auto-attack from about 4-5 yards and that's unreal... As you can see on model animation.

On retail you need to be closer to your target to attack him with some melee spell or auto -attack. (about 1-2 yards)

Picture:
http://prntscr.com/4zkpab
As you can see on picture I'm 3-4y away from dummy and my melee spells are still useable

a3192b1

Sorry for bad english, but I hope that you understood me.

**Comment by Aknunx** [comment]
Confirmed on https://github.com/TrinityCore/TrinityCore/commit/4519be74a263acd17242fb4558b2bb3194c151a6

Any updates?

**Comment by Shauren** [comment]
e6a52d4aae9e8facc46c3b05e0560d540a928d73
