### ISSUE TITLE
[3.3.5] Glyph of Charge

### ISSUE THREAD

**Issue by DoodleZero** [TrinityCore/TrinityCore#13490]
How it should work: "Increases maximum range for charge by 5 yards which makes charge usable from 8 to 30 yards."

Problem: Though the tooltips say that the range has been increased, charge can't be used on targets that are further than 25 yards.
Ability icon becomes 'usable' when you get into 30 yd range, but you're still 'too far away'.

Additional Informations:
Glyph of Charge: http://wotlk.openwow.com/item=43397
Charge: http://wotlk.openwow.com/spell=100

a3192b1
##

**Comment by Langerz82** [comment]
Related: https://github.com/TrinityCore/TrinityCore/issues/18707

**Comment by Killyana** [comment]
Confirm the Glyph works correctly on rev.db5c9867e2ffde3657f53bc155b474c5d46884dd
