### ISSUE TITLE
[3.3.5] Pain Supression - Castable while morphed

### ISSUE THREAD

**Issue by DoodleZero** [TrinityCore/TrinityCore#13491]
Pain supression seems to be castable while polimorphed (http://youtu.be/xTjyqti3ngs?t=5m53s). This seems to be because the priest is still stunned (glyph) while casting Pain Supression even though he is already sheeped.
I tested it and it is bugged, being stunned first and then sheeped allows you to still cast Pain Supression while you are still stunned(the two cc being overlapped).

a3192b1
##

**Comment by Keader** [comment]
@ariel- still valid? :)

**Comment by Aokromes** [comment]
no answer after > 4 years, closing, if this bug is still valid open a new ticket with updated core.
