### ISSUE TITLE
[6.x] Quest Cutting Teeth broken

### ISSUE THREAD

**Issue by naahmi** [TrinityCore/TrinityCore#13492]
Version: TrinityCore rev. a8b7bda 2014-10-27 16:13:49 +0000 (4.3.4 branch) (Unix, Release)

http://www.wowhead.com/quest=25126

You can only kill the Mottled Boar with skills and not with right click

**Comment by Rushor** [comment]
moved to a more general issue in https://github.com/TrinityCore/TrinityCore/issues/15963

**Comment by BahDumbBugs** [comment]
As of commit e0fb444 - This quest cannot be turned in. Quest giver Gornek receives your attempt but "Complete Quest" button cannot be clicked for completion. 

http://i.imgur.com/RTiaeEo.jpg

New issue or duplicate?

**Comment by BahDumbBugs** [comment]
Disregard my previous comment. I tried it on a brand new toon instead of my GM toon. Works as intended; turned in successfully. Carry on.
