### ISSUE TITLE
[6.x] Pet Dk Raise Dead  not spawning

### ISSUE THREAD

**Issue by daniel0** [TrinityCore/TrinityCore#13502]
Pet Dk not spawning with spell Raise Dead

http://www.wowhead.com/spell=46584/Raise-Dead

TrinityCore rev. 89d4bf4b08  (4.3.4 branch) (Unix, Release)
DB: TDB_full_434.05_2013_07_17 + 4.3.4 DB_alpha

**Comment by Rushor** [comment]
no speltrigger, moved to the check and todolist from https://github.com/TrinityCore/TrinityCore/issues/14825
