### ISSUE TITLE
[3.3.5][6.x] Obsidian Sanctum's Twilight Portals

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#13538]
http://www.wowhead.com/object=193988
rev https://github.com/TrinityCore/TrinityCore/commits/3.3.5
tdb 335/57

These portals simply disappeared from database at some point... I can't find the commit that removed them so I guess it has been a long while ago. This is what I found on a very, very, very old database

``` mysql
insert into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values
('300117','193988','615','3','1','3246.47','515.266','58.6196','1.54789','0','0','0.698963','0.715158','-300','0','1');
insert into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('300118','193988','615','3','1','3154.78','515.889','90.9767','3.18872','0','0','0.999722','-0.0235612','-300','0','1');
insert into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('300119','193988','615','3','1','3216.13','648.325','87.0783','0.693027','0','0','0.339621','0.940562','-300','0','1');
insert into `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) values('300120','193988','615','3','1','3383.81','532.522','96.971','3.43866','0','0','0.988989','-0.147986','-300','0','1');
```

Currently, no portals are "opened" during Shadron's encounter

**Comment by b44rt** [comment]
Will the query mentioned here make the portals spawn during the encounter ? This bug makes Shadron immune to damage as soon as he casts Gift of Twilight

**Comment by Nyeriah** [comment]
I don't know. Why don't you try it?

**Comment by b44rt** [comment]
Ofcourse I will try it, but since the queries are out there I figured maybe someone has tried it. 
Im running 003d67708b9a with DB TDB 335.57 

Ill comment when I tried it.

**Comment by danlapps** [comment]
Data from retail
(@OGUID+0, 193988, 615, 3, 1, '', 3355.911, 515.2172, 99.09382, 5.515242, 0, 0, 0, 1, 7200, 255, 1), -- Twilight Portal (Area: -Unknown-)

**Comment by danlapps** [comment]
I also get this from parser, not sure if its related to the issue :
```SQL
UPDATE `gameobject_template` SET `Data26`=1, `VerifiedBuild`=19702 WHERE `entry` IN (193988 /*Twilight Portal*/, 193989 /*Normal Portal*/);
```

**Comment by b44rt** [comment]
I can confirm that these queries will make the instance work. Minor thing: The portals are always visible, then when you start the encounter they dissapear until the minibosses casts his special ability.

**Comment by w5860363** [comment]
@Nyeriah core https://github.com/TrinityCore/TrinityCore/commit/1019649f93ae8f45f0d15a9eeeb803901c3c15cf Leave Vesperon the Twilight Portals Trigger Sartharion Dragon pattern All monsters Will to here Please excuse my English.

**Comment by Espionage724** [comment]
Is there anything else holding up this issue?

Currently (build https://github.com/TrinityCore/TrinityCore/commit/b5c12bd36f6d2e99ba4a94a1ba00de951a365f06), during the raid, no portals are spawned. Running the 4 SQL queries at the top seems to allow the dragons to spawn Twilight Portals, and they seem to function properly too:

- Right-click spawned portal
- Change phase and you enter twilight zone
- You have DoT
- Enemy appears in the zone and you can kill it
- Upon killing the enemy, you switch phases back to normal

**Comment by Kittnz** [comment]
@Nyeriah Where did you get theres values?

**Comment by tkrokli** [comment]
In case Nyeriah's example can be used, here is a transcript converted to TC code style:
```sql
-- Obsidian Sanctum's Twilight Portals, gameobjects with GUIDs and settings
-- (@OGUID set by TC when verified, unverified GUID values range: 300117 - 300120)
SET @OGUID := XXXXXX
DELETE FROM `gameobject` WHERE `guid` IN (@OGUID+0,@OGUID+1,@OGUID+2,@OGUID+3);
INSERT INTO `gameobject` (`guid`,`id`,`map`,`spawnMask`,`phaseMask`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecs`,`animprogress`,`state`) VALUES
(@OGUID+0,193988,615,3,1,3246.47,515.266,58.6196,1.54789,0,0,0.698963,0.715158,-300,0,1),
(@OGUID+1,193988,615,3,1,3154.78,515.889,90.9767,3.18872,0,0,0.999722,-0.0235612,-300,0,1),
(@OGUID+2,193988,615,3,1,3216.13,648.325,87.0783,0.693027,0,0,0.339621,0.940562,-300,0,1),
(@OGUID+3,193988,615,3,1,3383.81,532.522,96.971,3.43866,0,0,0.988989,-0.147986,-300,0,1);
```
(I just posted this to simplify the work if it will be used later. Feel free to rewrite if needed.)

**Comment by Aokromes** [comment]
To high guids for 3.3.5a spawns.

**Comment by tkrokli** [comment]
Yes, I see that now. 164 444 seems to be the highest current GUID in the `gameobject` table,
but I suppose we need to use the "Unused GUID" tool to find the free GUIDs.

**Comment by Nyeriah** [comment]
> @Nyeriah Where did you get theres values? Are these sniffed?

These values were in TDB before someone deleted them. I don't know if they're sniffed. As I said previously, the instance expects them to be already spawned. Seems like whoever removed them had little care as to whether things would still work or not. Might have even been removed by mistake, or whatever.
