### ISSUE TITLE
[CRASH] VMAP::StaticMapTree::getObjectHitPos

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#13534]
Rev. 799bdc17105c566a705cb93b4f1d1813c23f2ba2
Linux x64
Very often.

- http://pastebin.com/DV7nmXNQ
- http://pastebin.com/uC6n3dDu
- http://pastebin.com/F1zyhC6z
- http://pastebin.com/TkFpJULU

Thank you.

**Comment by Aokromes** [comment]
Pastes expired, closing.
