### ISSUE TITLE
Core/SAI: Creatures does not store Cooldown after Counterspell

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13559]
Rev: All revisions since mangos

Problem: 
Creatures scriptet with SAI will ignore Counterspells.

Reproduction: 
Choose an creature, scripted with SAI, which casts spells and repeats them all 2 seconds. Use counterspell on them, while they cast a spell.
- > You wil see that the creature ignores the counterspell and instantly repeats the spellcast after the counterspell

How it should be:
After you counterspelled the creature, the creature should not be able to repeat the spell for 5 seconds

Notes:
I know this is a general issue, because cooldown for creatures is not implementet yet and this issue affects also creatures scriptet with escortAI or scriptedAI and so on, but i think if we could realise a 5 sec cooldown for all creatures using sai it would be a great success.

**Comment by Aokromes** [comment]
This was fixed already no?

**Comment by Trisjdc** [comment]
No

**Comment by Shauren** [comment]
Fixed in 6.x branch

**Comment by Frytiks** [comment]
Will u port this to 3.3.5 ?

**Comment by Kittnz** [comment]
I hope someone will :)

**Comment by Shauren** [comment]
I will not. 3.3.5a branch is dead to me

**Comment by P-Kito** [comment]
Alot of people using it still. Wouldn't be a waste ;-P

**Comment by P-Kito** [comment]
Can someone port this to 3.3.5a? :/

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/f4c1a8fb2d6aff13f67dd2494dc18b481c548af9
