### ISSUE TITLE
[3.3.5][6.x][Quest] To Legion Hold (10563)

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#13572]
This quest used to work, but now it doesnt :P

Nothing happens when spell http://www.wowhead.com/spell=37097 of item http://www.wowhead.com/item=30638 is used near the Legion Communication Device.

Also the spell transform player into an imp, not a box

http://www.wowhead.com/quest=10563

5e95a0fd8105766f2b51a9919e16a73539afa446

**Comment by Aokromes** [comment]
Anything here is valid? imho dr-j's sugestion of move spellfocus is correct.

**Comment by Aokromes** [comment]
Areatrigger of Legion Hold:
4548 530 -3300.379883 2927.280029 170.938004 0.00 10.00 10.00 10.00 0.00

**Comment by xerkoss** [comment]
I still think you should not be able to move and it's triggered by event.  You are thinking  "If mahoma doesn't go to the mountain.. the mountain will go to mahoma", and that was no sense.

**Comment by Aokromes** [comment]
I am not moving the mountain (areatrigger) instead mahoma (spellfocus) :P

**Comment by ccrs** [comment]
why trying to change data if the other fix was valid and blizzlike?

**Comment by Aokromes** [comment]
Because spell focus can't be sniffed and it was spawned on different coordinates to area trigger.

**Comment by Killyana** [comment]
The problem is not the position of the spell focus or the dbcspell 37492, but that the event (Smart Trigger - On Trigger - Set Data to GO) will not trigger if the player is not moving with the disguise, maybe related to this issue: https://github.com/TrinityCore/TrinityCore/issues/1031

**Comment by ccrs** [comment]
EXACTLY xD

There is no refresh or update option in areatriggers, so scripts will only trigger at player enter

**Comment by Jenkyins** [comment]
confirmed on b1d0855624d1c83850fc36f5242437d7f7c1336b
