### ISSUE TITLE
[3.3.5][6.x] ICC - Frost Freeze Trap npcs are in wall

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#13600]
The event after Deathbringer, the Frost Freeze Trap npcs are in wall
so they doesn't do damage just two of them do

Include MAPS - VMAPS - MMAPS enabled
Revision: f5676d16c7eb5795a18d8eb76c8e42d02b1b5134

anyone confirm this issue?

**Comment by Keader** [comment]
Dup? #13608

**Comment by Golrag** [comment]
Try https://github.com/TrinityCore/TrinityCore/pull/15807
Note: I'm still looking at this PR, but I don't have much time right now
