### ISSUE TITLE
[3.3.5] Frost freeze traps don't damage players in ICC

### ISSUE THREAD

**Issue by mdaomega** [TrinityCore/TrinityCore#13608]
TrinityCore rev. e75534301d70 2014-11-20 16:09:42 -0200 (3.3.5 branch) (Unix, Release) 

[Frost freeze trap]s doesn't reduce health of any players. I mean they do not damage players. they can walk through them with no harm.

![wowscrnshot_112114_115002](https://cloud.githubusercontent.com/assets/2923173/5148514/93ca031e-7174-11e4-9917-0389d660f221.jpg)

**Comment by Rushor** [comment]
MitchesD: still isnt fixed

```sql
DELETE FROM disables WHERE sourceType=0 AND entry=70460;
INSERT INTO disables (sourceType, entry, flags, params_0, params_1, comment) VALUES(0, 70460, 64, '', '', 'Ignore LOS for Coldflame Jets');
```

**Comment by SlowLogicBoy** [comment]
worked for me

**Comment by P-Kito** [comment]
This should actually fix it. Removing LOS on disables table was added 1 year ago. Make sure you have that patched!

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/13600
