### ISSUE TITLE
mmaps crash

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#13618]
Revision: c2a69e748e243c9c08050c3bca854be3c0dc2130

http://pastebin.com/ZdZE3xiH

Only seen 1 time.

**Comment by Demonid** [comment]
@jackpoz Im getting this crashlog since i enable Mmaps on my server:

http://pastebin.com/pfjgMqJc

Could this be related?

**Comment by jackpoz** [comment]
that crash is in Release mode and has very little for anyone to work on

**Comment by Aokromes** [comment]
Also, totaly unrelated to this ticket, your crashlog don't have a single reference to mmaps.

**Comment by planee** [comment]
http://pastebin.com/rytgCuJd       
yeah, i got it too! only seen 1 time too.

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
