### ISSUE TITLE
[3.3.5][6.x] AHbot Selling prices

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#13632]
Can't adjust selling price for individual items like purples, Blues , Greens ETC 
 the old one we patched in we can set pricing 

http://www.trinitycore.org/f/topic/10690-auctionhousebot-prices/?hl=ahbot#entry70353

Core 898ecf7

DB 335.57

addons - NONE

**Comment by Aokromes** [comment]
Check again on head, a lot of new settings where added to ahbot.

**Comment by Aokromes** [comment]
13d without answer, if this bug is still valid open a new ticket.
