### ISSUE TITLE
[6.x] Bnet server | Feature request

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/TrinityCore#13634]
Would it be at all possible to emulate the auth module generation process used by retail - or to allow clients without modules in their Blizzard Entertainment cache to still enter the game (as can happen on the retail servers)?

Currently, the only way to obtain those modules is to be lucky enough to have them downloaded from the live servers. I have a retail account and through experimentation I have found that I am able to download the modules only after logging into my retail account. Logging into a trial account (which many of your followers have) has not yielded the authentication modules yet.

Completely clearing the battle net cache still allows me to enter the live servers, but attempting to enter TrinityCore causes a 114 response. It then becomes impossible to access TrinityCore locally until the correct modules are once again created via logging into a retail account - and it takes a few tries to get them.

Let me know if the above is a plausible future feature or not.

Thank you.

**Comment by Aokromes** [comment]
This is still needed?

**Comment by Shauren** [comment]
no, modules are not used since 6.2.4
