### ISSUE TITLE
Bug with death state or propably with 1 hp

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13639]
Today on server i got report from testers.

What is bugged ? - They testing a Ruby Sanctum and Ulduar:
- In Ruby Sanctum creature Living Ember after killing get bug with 1 HP, can't attack or kill him, but he still killing players. Here is screenshot: http://prntscr.com/59fn74

- Also this bug can be tested in Ulduar, where creature have state dead, but still attacking and casting spell on players: http://prntscr.com/5agsew

I'm using core with some changes - no changes in creature system, also confirmed from clean core.
Revision : https://github.com/TrinityCore/TrinityCore/commit/c73474305320c926c7d81cd8ae576d5c3a72f1c9
OS: Windows 7 - 64-bit

**Comment by Frytiks** [comment]
@joschiwald Maybe your patch bug prince in ICC ? They can't move, but after wipe and again pull they moving.

**Comment by Killyana** [comment]
Closed here https://github.com/TrinityCore/TrinityCore/commit/6d87f96e21f515b1500ecdd10576517d23b30cd4

**Comment by Strazhnik** [comment]
@Killyana i see this is bug in Ulduar on last rev (http://www.wowhead.com/npc=33572/steelforged-defender)

**Comment by joschiwald** [comment]
that is because of shitty sai

**Comment by Rushor** [comment]
fix for the last ones reported: https://github.com/Rushor/TrinityCore/commit/656e6707dfb849519526d119ce3e850d2a28f1e8
