### ISSUE TITLE
Lil' K.T support

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1364]
well i notice its not work. but this Companion have some script that dont have at all. 

he use to kill critters around him with max 15 yard and say stupid thing when he use the ice block spell

more info:
[http://www.wowhead.com/item=49693 Lil' Phylactery] - item, 49693
[http://www.wowhead.com/spell=69677 Lil' K.T.] - spell, 69677 (summon spell)
[http://www.wowhead.com/npc=36979 Lil' K.T.] - Npc, 36979 (the Companion)

spells the npc have:
[http://www.wowhead.com/spell=69681 Lil' Frost Blast] - spell, 69681
[http://www.wowhead.com/spell=69682 Lil' K.T. Focus] - spell, 69682
[http://www.wowhead.com/spell=69683 Lil' K.T. Passive] - spell, 69683

things he say by wowwiki/wowhead:

```
I'm Kel' Thuzad, Lich Lord of the Plaguelands.
```

```
You may have seen me in such instances as Naxxramas, Old Hillsbrad Foothills, and... Naxxramas again.
```

```
As a member of the K.T. Fan Club, now you too can have a little piece of everyone's favorite Archlich.
```

```
Enjoy! ...OR I WILL FREEZE THE BLOOD IN YOUR VEINS.
```
##

**Comment by danlapps** [comment]
What would be needed to close this ?  More retail sniffs or more coding ?

**Comment by Kitzunu** [comment]
Here is a video of K.T. killing a critter.
https://www.youtube.com/watch?v=ZzUfm7SFwFM

I also found that when you purchased this pet you would get this mail, which shows that the pet never says any of the lines above, but it is in the letter from Kel'Thuzad
![image](https://user-images.githubusercontent.com/24550914/73639069-eecbcc80-466b-11ea-923b-ea691f98103e.png)
seen here https://www.youtube.com/watch?v=uci_BcX1MQM 
More proof here https://wow.gamepedia.com/Lil%27_Phylactery
I don't know if that would be something that could be added for example as when the item is added to the player, send mail.

**Comment by Killyana** [comment]
To do: when the pet is summoned the player get the aura 69732 (the aura is added and removed by "Lich Pet Aura Remove"=69736 and "Lich Pet OnSummon"=69735)
The spell 69732 has the proc flag= 2 (0x2) - "Kill that yields experience or honor"  when it procs it must trigger a cast of 69731 on/from the pet

**Comment by Sorikoff** [comment]
This seems to be similar to that Soul Trader pet, isn't it?

**Comment by Killyana** [comment]
yes
