### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by Vissaben** [TrinityCore/TrinityCore#13647]
Was doing quest http://www.wowhead.com/quest=6/bounty-on-garrick-padfoot
Then noticed the npc was not loading. world server had crashed.

TrinityCore rev. b8560bceb0d0 2014-11-29 19:50:24 +0000 (3.3.5 branch) (Win64, Debug) (worldserver-daemon)

TDB 335.57

Crash Log(Debug):
http://sebsauvage.net/paste/?1a412c4e206e53e6#JDcSKd+nD7HhxGmYrUd5CjeKLJ9hXudwpB3U8igW4yo=

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Frytiks** [comment]
No
