### ISSUE TITLE
[6.x](?) Spell Darkflight [WORGEN]

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#13652]
Hello, When worgen classes are  changing faction to   horde , darkflight didnt removing from the spel book

http://www.wowhead.com/spell=68992/darkflight

Regards,

**Comment by VeraDev** [comment]
Depends if you want it the hacky way or not, but it's hacky fixable by adding something like this;
if getRace != worgen... & HasSpell (spellId), removeSpell...
You get the logic behind it, now if you want to do it the hacky way, you must do the rest yourself.

**Comment by Rushor** [comment]
table player_faction_change_spells will help you here - and check if the issue is still preent on 6.x

**Comment by Aokromes** [comment]
No answer after more than 4 months, closing.
