### ISSUE TITLE
Crash on MMAP::MMapData::AddSwap

### ISSUE THREAD

**Issue by H4D3S** [TrinityCore/TrinityCore#13651]
Branch; Phases
Hash: 323f80c801032f62814ce4cbdf086d35176b6ff9

Crash Log: http://paste2.org/bPyBGWnH

**Comment by H4D3S** [comment]
confirmed Hash: e6cc392

**Comment by Aokromes** [comment]
Must be fixed after 037fd1b1bb1b180b698782ec0525347eeeb93490
