### ISSUE TITLE
Human priest chain quests: can't heal Guard Roberts [$15]

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#13676]
I've found this:
https://github.com/TrinityCore/TrinityCore/issues/4598

It seems that also Guard Roberts NPC 12423 have this issue

Easy to test, it is the first priest quest in goldshire (about level 5)

**Comment by djbeauchamp** [comment]
Can we have the fix added to the core?

**Comment by Ladrek** [comment]
I'm new to GitHub how do I add my fix?

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Ladrek** [comment]
REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `RacialLeader`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES (12423, 0, 0, 0, 0, 0, 3258, 0, 0, 0, 'Guard Roberts', '', '(NULL)', 0, 7, 7, 0, 1, 1, 1.14286, 1, 0, 0, 2000, 2000, 1, 32768, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 32768, '');

**Comment by Aokromes** [comment]
we don't use replace into, and we don't delete creature_templates.

**Comment by Ladrek** [comment]
oh this fix should work but I didn't know that.

**Comment by Killyana** [comment]
Only the unit_fags must be changed: (it already the case for Sentinel Shaya)
``` sql
UPDATE `creature` SET `unit_flags`=4104 WHERE `id`=12423;
