### ISSUE TITLE
[6.x](?) Priest Lightwell like a cube

### ISSUE THREAD

**Issue by Aszune** [TrinityCore/TrinityCore#13685]
Core: https://github.com/TrinityCore/TrinityCore/commit/de44a3250cbbf4d97ae0555d9df48bd903cc6106
DB: [Legacy] TDB Full 4.3.4 09

Priest Spell "Lightwell" when it spawns, looks like a cube.

Spell: http://es.wowhead.com/spell=724

Screenshot:
![wowscrnshot_121314_095900](https://cloud.githubusercontent.com/assets/4223661/5423201/799d9ebe-82af-11e4-96ed-3874b3b62baa.jpg)

Edit: Corrected commit.

**Comment by Rushor** [comment]
@Aszune check if this issue also happens on 6.x

**Comment by Aokromes** [comment]
No answer after more than 4 months, closing.
