### ISSUE TITLE
[3.3.5]Pets are walking at the same place

### ISSUE THREAD

**Issue by DoodleZero** [TrinityCore/TrinityCore#13686]
Pets are walking at the same place, like they are moving but they aren't. It's hard to explain but I hope that someone can to reproduce it.

I didn't had time to make video of it but you can see it in picture, I'm staying in place with my hunter and my pet have "walk" animation.

Pictures:
- http://prntscr.com/5gblen
- http://prntscr.com/5gblkx

Core: f5676d1
##

**Comment by Rushor** [comment]
also happens to some creatures and players sometimes

**Comment by Treeston** [comment]
2a84562
