### ISSUE TITLE
[3.3.5] SPELL_FAILED_AURA_BOUNCED (not stacking auras) is not working.

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13695]
I think this commit https://github.com/TrinityCore/TrinityCore/commit/6098a5e43ad52e016ff6e2b263db6d92a0718995 fixed this issue long time ago, I wasn't there to test it, the thing is now, it's bugged again.

When you cast for example the first Polymorph (that lasts 10 seconds) and then, before it gets to 5 seconds duration, you cast Polymorph again, the second polymorph shouldn't cast correctly because the enemy already has Polymorph aura "stronger" than the newest one you are trying to apply.

SPELL_FAILED_AURA_BOUNCED sends a message with "A more powerful spell is already active".

**Comment by Raydor** [comment]
Still not implemented in https://github.com/TrinityCore/TrinityCore/commit/c210b935942f8f2202f1436f2cf73821614c041d, summoning @ariel-

**Comment by ariel-** [comment]
For polymorph and dr auras, does it show the error before or after the cast?

**Comment by Raydor** [comment]
Im not exactly sure when it should show the message, someone with retail access can test it? I think it should show when the spell is casted just before the effect is applied but not 100% sure.

**Comment by tkrokli** [comment]
The intention would be to stop the spell from being cast, but you should check to see if that is what it happens. The spell cast should stop with a fade or fizzle, at the same moment as it would otherwise have been cast, along with the error message being displayed, if the code works as intended. The game client  should play a spell fail sound too, like when your target is not in LoS.

**Comment by Shauren** [comment]
Tested - after the cast

**Comment by ariel-** [comment]
Does it show a miss result?

**Comment by Shauren** [comment]
Yes, this one "A more powerful spell is already active"

**Comment by ariel-** [comment]
I mean the little indicators "Immune" "Deflect" etc that show on the target

**Comment by Shauren** [comment]
None, its a regular cast failure (there is no SPELL_GO)

**Comment by Maadguy** [comment]
This bug is still a thing, it's a gamebreaker in PVP, it causes spells like nature's grasp (druid) to proc 3 times in a row upon being hit, cancelling its own DR, and other mechanics like this.
