### ISSUE TITLE
Quest 219 bugged (Missing in Action)

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#13711]
Hi all, quest 219 seems bugged. The NPC Corporal Keeshan didn't attack enemies, it seems to start attack the return in place. Also just one of 3 players got the quest as completed.
http://www.wowhead.com/quest=219/missing-in-action

**Comment by ikir83** [comment]
So it is fixed now? :)

**Comment by Aokromes** [comment]
Can you create a PR for this?
