### ISSUE TITLE
DB/Quest: Fuel for the Fire

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13729]
rev: https://github.com/TrinityCore/TrinityCore/commit/1b9aca10c798c1665e89f339629b73f841c72535
DB: 11.57

From reference video: abomination should follow you, but when i get combat, abomination just dissapear.

Quest: www.wowhead.com/quest=12690
##

**Comment by DarkBrain2580** [comment]
When i make the spell Burst at the Seams it will give me no credit for the Drakkari Skullcrushers.

**Comment by ccrs** [comment]
missing second part: 	Drakkari Chieftain Lured (3)
https://www.youtube.com/watch?v=tQxN16FRQLk

**Comment by Rushor** [comment]
this follow part is already fixed?
