### ISSUE TITLE
A Hearty Thanks!

### ISSUE THREAD

**Issue by djbeauchamp** [TrinityCore/TrinityCore#13738]
Rev. 0043a5dd221
A Hearty Thanks!
http://www.wowhead.com/quest=9612

Required Spell:
http://www.wowhead.com/spell=28880

Bug description:
Draenei Youngling gives quest without "saving" his life. You're supposed to help him kill a beast he's fighting before he gives you the quest. Currently he will give you the quest without having to kill anything.

How it should be:
You must be a Draenei that find a Draenei Youngling. Get them to engage in combat, either by them naturally pathing into an aggressive creature, or by dragging one to them. (Non-aggressive) will not work. They must take damage, if you brought a creature to them you must let them pull aggro. Use Gift of the Naaru on the Draenei Youngling. Kill the creature, when the Draenei Youngling resets they will offer this quest.

Bounty:
https://www.bountysource.com/issues/7196542-a-hearty-thanks

**Comment by Killyana** [comment]
@Rushor Can you test this please to add the missing text: there's maybe some issues with the event phase.

``` sql
SET @ENTRY := 17372;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0 AND `id` IN (11 AND 15);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values
(@ENTRY, 0, 11, 0, 26, 0, 100, 0, 1, 15, 60000, 60000, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Draenei Youngling - IC_LOS - TALK'),
(@ENTRY, 0, 12, 0, 53, 0, 100, 0, 1, 200000, 20000, 20000, 1, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Draenei Youngling - RECEIVE_HEAL - TALK'),
(@ENTRY, 0, 13, 0, 5, 0, 100, 0, 30000, 30000, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Draenei Youngling - KILL - TALK'),
(@ENTRY, 0, 14, 0, 1, 0, 100, 0, 60000, 60000, 60000, 60000, 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Draenei Youngling - OOC - TALK'),
(@ENTRY, 0, 15, 0, 4, 0, 100, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Draenei Youngling - AGGRO - TALK');

**Comment by Rushor** [comment]
hmm you mean 17587? okay testing inc

**Comment by Rushor** [comment]
http://pokit.org/get/?6432db6cfda3d558854f182fe98760e6.jpg texts are working, nice. but yeah this phaseissue is strange :o

**Comment by Killyana** [comment]
I made some correction on the text their fine now, but for me the problem is that the Draenei never attack  the npc 17372  (I must change the faction of the Draenei to see the result) maybe because I'm using a 4.3.4 server.

**Comment by djbeauchamp** [comment]
https://www.bountysource.com/issues/3676503-flightpath-exodar-blood-watch-broken-15

**Comment by leszkowiak** [comment]
I know I deserve a golden shovel. but currently you just need to change the value of "pvpflags" in creature_template_addon from 16 to 1 in the enrty "17587", and that's it. The quest starts without any problems, of course, first of all you need to heal the npc during his fight with the mob.

**Comment by CraftedRO** [comment]
This had to be the four quest I know broken by bytes to pvpflag conversion, now I'm really wondering if we need to set pvpflag 1 where 16 for each creature because that "default" 16 value seems wrong in any case.

**Comment by Shauren** [comment]
> This had to be the four quest I know broken by bytes to pvpflag conversion, now I'm really wondering if we need to set pvpflag 1 where 16 for each creature because that "default" 16 value seems wrong in any case.

It wasn't broken by the conversion - if it got 16 in pvpflags, it means that it already had 16 encoded in bytes field (there was no altering of actual data, it was only split into separate fields)

**Comment by CraftedRO** [comment]
but this doesn't explain for me why all 4 quests worked before

**Comment by Shauren** [comment]
And yes, 16 is a suspicious in the field - in older versions (vanilla, tbc). that part of bytes was occupied by debuff limit
Which means the data in database is ancient (and that storing bytes directly was a design mistake)

**Comment by Shauren** [comment]
> but this doesn't explain for me why all 4 quests worked before

They didn't (at least not on that commit), I just double checked the commit, it didn't change the behavior at all
