### ISSUE TITLE
Tree's Company

### ISSUE THREAD

**Issue by djbeauchamp** [TrinityCore/TrinityCore#13736]
Rev. 0043a5dd221
Tree's Company
http://www.wowhead.com/quest=9531

Tree Disguise Kit:
http://www.wowhead.com/item=23792

Bug description:
When walking up to the cove where the flag is, the scripted actions start before the disguise is used, then when the disguise is used it initiates the scripted actions a second time, overlapping the first.

How it should be:
Go to the designated cove and look for a naga flag. Use the disguise kit when you see the flag and wait. Eventually the traitor will show up. Let the meeting finish to get credit for completion.

Bounty:
https://www.bountysource.com/issues/7196053-tree-s-company

**Comment by Rushor** [comment]
hmm this really fixes the issue :D no double spawns with:

```sql
DELETE FROM creature WHERE guid=85587 AND `id`=17318;
```

**Comment by GnaXi** [comment]
in 6.x and rev 5c74ce2e2760, this is still not working correctly.
When using the Tree Disguise Kit, you transform into a tree and Geezle is spawned in the distance, but that's as far as the event goes. After 2 minutes the tree debuff expires and Geezle despawn.

**Comment by djbeauchamp** [comment]
Would a sniff of the retail wow provide the proper data for both 3.3.5a and 6.x cores?

**Comment by Nawuko** [comment]
Just checked the quest, its working fine without any issue, no double spawn. Use the disguise watch the event -> quest completed. on 335 https://github.com/TrinityCore/TrinityCore/commit/d82534a7bbd401f4b672786749f10f5a95f6e76c
