### ISSUE TITLE
Prince in ICC

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13734]
https://github.com/TrinityCore/TrinityCore/commit/1b9aca10c798c1665e89f339629b73f841c72535
DB: 11.57

Hi, last 4 days was prince work's good, but after i pull new fixes from TC, prince stop moving. They just do combat, but they are just staying and casting spells.

http://www.wowhead.com/npc=37970/prince-valanar

BTW: The same bug is at hodir.

**Comment by Frytiks** [comment]
Anyone know how to fix this bug ? Is so annoying. Unit flags are normal, don't seems to be UNIT_FLAG_DISABLE_MOVE. Also with turned mmaps off still not working.

I found when i first time pull prince and i die, they go back, and when i respawn and i try again, they moving normally.

**Comment by Frytiks** [comment]
Any news about it ?

**Comment by DDuarte** [comment]
Did this get fixed?...

**Comment by Nyeriah** [comment]
Never came across this bug, so don't know if it was even a problem to start with tbf... but definitely not seen the past months

**Comment by Nyeriah** [comment]
I don't reckon seeing this bug as he describes it but there were times they stay dead (but still casting spells) but it hasn't happened to me in a very long while

**Comment by Frytiks** [comment]
@Nyeriah i was have the samé problem, but now prince works normally.
