### ISSUE TITLE
[Object] Reinforced Fel Iron Chest

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13747]
Hi, this object http://www.wowhead.com/object=185168/ (normal) http://www.wowhead.com/object=185169/ (heroic) spawns after kill Nazan and Vazruden but you can't clic on the chest to open it.

I have seen the normal version flag of the chest and it's 16 while in hero mode is 6553616.
It doesn`t work either nomal or heroic mode.

161d688d936b2ba49083711c1e7eae001101ed16

**Comment by Nyeriah** [comment]
The fight has several issues that need to be addressed before pushing this as otherwise it will just simply not work. I'll rewrite him soon and push it while around this.

**Comment by ariel-** [comment]
```c++
                        if (GetBossState(DATA_VAZRUDEN) == DONE && GetBossState(DATA_NAZAN) == DONE)
                            if (GameObject* chest = instance->GetGameObject(felIronChestGUID))
                                chest->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
```

This is not working, apparently, as I did a instance getbossstate and both where in state 3 (DONE), however the GameObject still had the not selectable flag.

**Comment by ariel-** [comment]
Got it! missing _Reset() in Nazan AI Script::Reset() method (as it was never reset it's state was TO_BE_DECIDED), then when calling Instance::SetBossState it returns false, the overrided script also returns false, and it never executes the check to remove the GO flag.

**Comment by Nyeriah** [comment]
Note: on retail there's like a five seconds delay before the chests actually can be interacted with. There's probably an timed event to check if both bosses are dead to then conclude the encounter. But currently at TC and the way the encounter is implemented it won't work that way.
