### ISSUE TITLE
[Locales/3.3.5] locales_item has some Cataclysm translations.

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#13750]
DB: 335.57 w/ updates up to 161d688d936b2ba49083711c1e7eae001101ed16

The problem looks like some script has been used to mine data from WoWHead, but was mined in a newer patch, where some names changed, like Gem colors and glyphs.

Some examples to illustrate:

entry: 43350
item name: Glyph of Mend Pet
name_loc6: Glifo de Aliviar Mascota (Glyph of Mend Pet) CORRECT
name_loc7: Glifo de Tamaño Inferior (Glyph of Lesser Proportion) WRONG, Cata item.

entry: 43357
item name: Glyph of Fire Ward
name_loc7: Glifo carbonizado (Charred Glyph)

entry: 40162
item name: Accurate Ametrine
description: Matches a Red or Yellow Socket.
name_loc2: Amétrine de précision (I know no french, but judging from the looks of it, seems correct)
name_loc6 & name_loc7: Piedra de terror de precisión (Accurate DREADSTONE), color changed with Cataclysm.

desc_loc6: Encaja en una ranura de color rojo o amarillo. (fits red or yellow, correct)
desc_loc7: Encaja en una ranura de color rojo o azul. (fits red or blue, wrong)

Funny that the name_loc6 is wrong in this case but the description was correct.

**Comment by Aokromes** [comment]
We don't use replace into.

**Comment by ariel-** [comment]
@Aokromes: http://pastebin.com/J7JKpLU0
