### ISSUE TITLE
[4.3.4]DB/Quest: Recruitment

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13754]
TrinityCore rev. ad71d227d3e6 2014-12-19 23:32:40 +0000 (4.3.4 branch) (Win64, RelWithDebInfo)
http://www.wowhead.com/quest=26800/recruitment
https://www.youtube.com/watch?v=f62iwshEwGQ

[02:29:14]Entry: 49340.
http://www.wowhead.com/npc=49425/darnell

This Quest is unscripted.

Usually you should be able to spellsclick on the corps. After the spellclick, darnell comes close to the player, takes the corpse and gives a killcredit.

Dunno if this is a solo-database issue. some corespellscript-support is probably needed.

**Comment by Aokromes** [comment]
What part of this is needed? all, 1st, 2nd?

**Comment by Rushor** [comment]
still working in progress, because the questcredit is wrong :/

**Comment by Killyana** [comment]
There's only one part, my first post.
