### ISSUE TITLE
4.3.4 DB/Quest: The Wakening

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13753]
TrinityCore rev. ad71d22 2014-12-19 23:32:40 +0000 (4.3.4 branch) (Win64, RelWithDebInfo)
https://www.youtube.com/watch?v=hoO7D_SDsm0

http://www.wowhead.com/quest=24960/the-wakening

Quest is unskripted.

some starting work:

```sql
bullshit

```

texts on gossip select missing - will add this tomorrow

**Comment by Aokromes** [comment]
What part of this is needed? also if both parts are needed plz use GUID to set guids.

**Comment by Killyana** [comment]
Push my version because npcs must be spawned by spells  + stand emotes + broadcast + and events when the player talk with the npcs.
