### ISSUE TITLE
4.3.4 [DB/NPC] Darnell spawn

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13761]
TrinityCore rev. ad71d227d3e6 2014-12-19 23:32:40 +0000 (4.3.4 branch) (Win64, RelWithDebInfo)
Phasing Issue, still like to note that, because the npc is not spawned.

The questendernpc for http://www.wowhead.com/quest=24970/no-better-than-the-zombies
http://www.wowhead.com/npc=49425 is not on the map.

**Comment by Killyana** [comment]
I have some difficulties to understand the quest_start, quest_end, quest_start_status, quest_end_status, in this case the player must get the aura if the quest 24970 is complete or rewarded, and once the quest 24971 is rewarded he will no longer get the aura. Any one can help on this?

``` sql 
DELETE FROM `spell_area` WHERE spell=49417 AND AREA=154;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `racemask`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES
(49417, 154, 24970, 24971, 16, 1, 66, 11);
