### ISSUE TITLE
4.3.4. DB/Quest: WIP - Tirisfal - Questchains

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#13789]
TrinityCore rev. ad71d227d3e6+ 2014-12-19 23:32:40 +0000 (4.3.4 branch) (Win64, RelWithDebInfo)

Ellesar1 on 2012/02/18 (Patch 4.3.2)
It actually becomes available if you abandon Escaped From Gilneas.

http://www.wowhead.com/quest=25039/have-you-seen-anything-weird-out-there

problem:
this one needs the prequest: http://www.wowhead.com/quest=24992, which is not set atm actually.

fix:
```sql
UPDATE `quest_template` SET `PrevQuestId`=24992 WHERE  `Id`=25039;
```

http://www.wowhead.com/quest=24991/garrens-haunt
http://www.wowhead.com/quest=24996/hollands-experiment

```sql
UPDATE `quest_template` SET `PrevQuestId`=24996 WHERE  `Id`=24991;
```

**Comment by danlapps** [comment]
From what I can read, you can ONLY get 25039 if you ABANDON 24992, not if you complete it

http://www.wowhead.com/quest=25039/have-you-seen-anything-weird-out-there (bottom comments)

**Comment by danlapps** [comment]
all first line seems ok, im not sure about nextquestid starting at the class specific quest, like warrior (3095) one pointing to nextquestid of the hunter quest (24964), but i dont know if it's normal, so if someone can tell me how it should look i can keep working on them !

**Comment by Rushor** [comment]
at least the list from http://www.wowhead.com/quest=24959/fresh-out-of-the-grave is correct.

**Comment by Rushor** [comment]
okay the missing two:

```sql
UPDATE `quest_template` SET `PrevQuestId`=24971 WHERE  `Id`=24972;
UPDATE `quest_template` SET `PrevQuestId`=25038 WHERE  `Id`=24990;
```
rest seems fine for me

**Comment by Aokromes** [comment]
What of all this is needed?

**Comment by Rushor** [comment]
everything

complete list:

```sql
UPDATE `quest_template` SET `PrevQuestId`=24971 WHERE  `Id`=24972;
UPDATE `quest_template` SET `PrevQuestId`=25038 WHERE  `Id`=24990;
UPDATE `quest_template` SET `PrevQuestId`=24996 WHERE  `Id`=24991;
UPDATE `quest_template` SET `PrevQuestId`=24992 WHERE  `Id`=25039;
```
