### ISSUE TITLE
[6.x] bnetserver

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#13782]
The connection is closed when you wait more 10 seconds on the account select (when you have multiple accounts in the same email).
hash revision: https://github.com/TrinityCore/TrinityCore/commit/f05c68b4324a254c3bc51d2ac63d4f4194751b52

Screenshot : http://puu.sh/dKBzE/c7039fd6f2.png & http://puu.sh/dKBBr/90438c3e2e.png

**Comment by Aokromes** [comment]
Soon (TM) :trollface:
