### ISSUE TITLE
3.3.5a - Item use: Bubbling Brightbrew Charm

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#13785]
Item: Bubbling Brightbrew Charm Use: Summon the Brewmaiden, whose very presence bolsters a party's vigor. Wave at her for Brewfest Brew! (10 Min Cooldown).

Bug: The brewmaiden spawns, follows you. But does not give a brewfest brew when you wave at her (needs scripting). She also doesn't heal the master.

Info:
Item: 49118
http://www.wowhead.com/item=49118/bubbling-brightbrew-charm

Core: 3747f99d4f76a149d215745780703b2623c59425

**Comment by Frytiks** [comment]
Sometime get bugged, and is not removed.

**Comment by Rushor** [comment]
probably if the player is more than 100 yards away from the npc?

**Comment by Frytiks** [comment]
Maybe ,i got report. Aura sometimes bug and stays and healing raid.

**Comment by Frytiks** [comment]
+ these spell stacking with spell power, it's healing for 10K

**Comment by Rushor** [comment]
the bonus can be removed if you add it to spell_bonus_data with value 0 in the bonuses

**Comment by Frytiks** [comment]
@Rushor Easy to bug. U just use trinket, and go through portal (LIke ICC entrace) = AURA STAY

**Comment by joschiwald** [comment]
aura must applied on the brewmaiden and not on each player

**Comment by Rushor** [comment]
okay well the npcs adds hisself the aura and every player who come closer to it gets the buff for teh time, the player is near the npc. should it be like that?

**Comment by Frytiks** [comment]
yes

**Comment by joschiwald** [comment]
try this
```sql
-- The Brewmaiden SAI
SET @ENTRY := 36021;

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=@ENTRY;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY*100 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,22,0,100,0,101,0,0,0,11,48249,1,0,0,0,0,7,0,0,0,0,0,0,0,'The Brewmaiden - Received Emote 101 - Cast ''Brewfest Brew Toss''');

DELETE FROM `creature_template_addon` WHERE `entry`=@ENTRY;
INSERT INTO `creature_template_addon` (`entry`,`bytes2`,`auras`) VALUES
(@ENTRY,0x1,'68269');
```

**Comment by Frytiks** [comment]
Works, thanks

**Comment by joschiwald** [comment]
45b7477344ccc1b33159d8d6bdefc091418cb2a0
