### ISSUE TITLE
[DEV] 3.3.5 / 4.3.4 -> 6.x cherry-picks

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#13792]
This is the list of https://github.com/TrinityCore/TrinityCore/commits/3.3.5 to be merged into https://github.com/TrinityCore/TrinityCore/commits/6.x
- [x] https://github.com/TrinityCore/TrinityCore/commit/9ea93eae33dcf776537a41e9c9ff33a31d6e3e19 AuraRemoveMode assert
- [x] https://github.com/TrinityCore/TrinityCore/commit/6390e6a4cc2d657e7fa49e80c5be32007df56ee1 Core/Dep: Remove unneeded recast files
- [x] e8955cf6ddddd6953340c2ceeb3b5b4a98d57c90 + bb002803bc0cd0283db0873e9a12db43a82ca30b + 77887ab32ff4d703dbc618b5cab364f02582c5e7 death grip dk spell (9d1e64159f4cc5ac418f9fb2cac5aeb29435586e)

335 commits not found in 6.x branch comparing commit log, sorted by most recent
- [x] 42f1a0b - DB/Creature: Toc binding must start at Icehowl not at Gormok
- [x] cc00321 - DB/Creature: Fix some startup errors
- [x] 747e72f - DB/Creature: Icecrown/Wrathgate - 1
- [x] 4d2c35e DB/Creature: Fix for Bleeding Hallow Dark Shaman without waypoint data
- [x] b7bacea DB/Creature: Hellfire Peninsula - Waypoints - 5
- [x] d443a76 DB/Misc: Fix Mog dorg the Wizened quest linking issues
- [x] 286fab5 + 561fc77 DB/Item: Bubbling Brightbrew Charm
- [x] 0ca936d Update 2014_12_27_09_world.sql
- [x] f16cb5b Coding standards.
- [x] 20af358 DB/Creature: Spawns and waypoints on Storm Peaks
- [x] 65364af DB/Creature: Add 4 missing spawns
- [x] e583777 DB/Waypoint: Edrick Killian & Mattie Alred
- [x] 92d42e3 DB/Creature: Deathbound Ward
- [x] 5719fe9 DB/Creature: Hellfire Peninsula - Waypoints - 2
- [x] 495c64b DB/Creature: Hellfire Peninsula - Waypoints - 4
- [x] 60f4c7d DB/Creature: Hellfire Peninsula - Waypoints - 3
- [x] 3747f99 DB/Spells: Bizuri's Totem of Shattered Ice / Idol of the Crying Moon
- [x] 7523d60 DB/Quest: Heart of Hakkar
- [x] 2dc0ffe DB/Creature: Dalaran Citizen and Great Hexer Ohodo
- [x] 161d688 DB/Gossip: some missing gossip menu ids, menus and menu options)
- [x] 7b9bcbe SQL: Sync auth database
- [x] 1b9aca1 Merge pull request https://github.com/TrinityCore/TrinityCore/pull/13650
- [x] cbb1f7c DB/Creature: Fix Lesser Nether Drake unit_flags
- [x] 629c6d2 Fix screwup I made when adding broadcast text
- [x] c385e53 DB/SAI: Ulduar Scripts
- [x] 446cd48 + e82b78a Update 2014_12_14_02_world.sql
- [x] 46828c4 DB/Creature: Archmage Pentarus Flying Machine
- [x] 9feabd1 DB/Creature: Ruul the Darkener
- [x] 6627a44 DB/Quest: Post-Partum Aggression
- [x] 1175ba7 DB/Spell: Fix Venomhide Poison staking with spell power
- [x] a455b47 DB/Misc: Misc fixes
- [x] c136e4c DB/Misc: Missing spell targets/conditions
- [x] 4265f7e DB/Gameobject: Update Archivum Console Scripts (Ulduar)
- [x] f5c2fa8 Remove Alexstrasza the Life-Binder CPP
- [x] 2c0b3de DB/Quest: Swift Discipline
- [x] bf0a546 DB/Misc: Wrathgate Again
- [x] 598908b DB/Misc: Wrathgate Stuff
- [x] 2e757f8 Remove Blackhoof Cage CPP
- [x] 4bc96bf DB/Quest: Prisoners of the Grimtotems
- [x] f80a9f9 Tidying up cpp - zone_icecrown.cpp
- [x] e79521d DB/Quest: The Flesh Giant Champion
- [x] 19967a6 Removing CPP for "Stinky" Ignatz
- [x] 153be1a DB/Quest: Stinky's Escape
- [x] 9bcfc12 Rename previous commit
- [x] bef81c9 DB/Quest: What the Soul sees
- [x] 0b3b5d6 Some Cleanup of CPP I forgot to remove
- [x] 068999f DB/Event: Perry Gatner
- [x] 9f3efff Update 2014_11_28_00_world.sql
- [x] b8560bc DB/Misc: More Perry Gatner Texts
- [x] 2f56fdb DB/Misc: Kill warnings
- [x] 13f205a DB/Misc: Cosmetic Fixes
- [x] 463aeb6 DB/Misc: Traveler's Tundra Mammoth
- [x] e536922 DB/Misc: Updates
- [x] a209e53 DB/Quest: Further Conversations
- [x] c734743 DB/Misc: Various Updates
- [x] 4387bc3 DB/Creature: Vacillating Voidcaller
- [x] fff2aff DB/Creature: Harbinger of the Raven
- [x] fe31f10 DB/Achievement: Pilgrim's Peril
- [x] 5e5b8e2 DB/Quest: We Strike!
- [x] 0411157 DB/Creature: Fix Void Conduit InhabitType
- [x] 84d1ac2 DB/Achievement: Now We're Cookin
- [x] a5c90b4 DB/Conditions: Gossip conditions for AT Valiants and Champions.
- [x] b1ab1bb DB/Creature: Misc updates for AT Valiants and Champions.
- [x] 5a30c00 DB/Creature: Fix class of Water Terror
- [x] 3236f16 DB/Creature: Fix  Wyrmrest Skytalon class
- [x] b604292 DB/Misc: Getry (Again)
- [x] e60656e DB/Quest: Changes to script for Foolish Endeavors
- [x] ef6772b DB/Misc: Misc fixes 2
- [x] 92ddfd3 DB/Quest: Misc Fixes
- [x] 3b1acea DB/Misc: Deviate Ravager
- [x] dd87d74 DB/Misc: Fix typo in .titles current helptext
- [x] 1dba02c DB/Misc: Fix typo
- [x] 75decfc DB/SAI: Fix 3 startup errors
- [x] e209a73 Remove uneeded script
- [x] 6f58467 DB/Misc: Quest linking
- [x] 849e7a6 DB/Quest: Of keys and cages
- [x] 898ecf7 DB/Misc: Misc Fixes
- [x] 5e95a0f DB/Quest: Flight of the Wintergarde Defender
- [x] 251a347 DB/Quest: Blending In
- [x] 0527800 DB/Quest: Sniffing Out the Perpetrator (Alliance)
- [x] 502a7e6 DB/Spells: Cleaned playercreateinfo_spell_custom table and added WoTLK class spells only
- [x] 971f486 DB/Quest: All Hail Roanauk!
- [x] ff18a6e DB/Quest: Return of the High Chief
- [x] 3e4b83b DB/Misc: Rescue from Town Square
- [x] f1e7052 Rename 2014_XX_XX_XX_world.sql to 2014_11_05_00_world.sql
- [x] 3530b93 Codestyle
- [x] 11e192c DB/SAI: Clear param2 for Remove Aura
- [x] dd1e9ec DB/Misc: Put right fieldnae in delete clause which was causing error on apply
- [x] d0ae507 DB/Misc: Eye of Dominion gossip conditions
- [x] 0872174 DB/Misc: Lithe Stalker Quests
- [x] 820e3eb DB/Quest: A Undead's Best Friend / Eidolan Watcher
- [x] 0ef518f Scripts/ToC: Misc forgotten clean ups
- [x] 141cf75 DB/Quest: The Vile Hold
- [x] 5dd9901 DB/Quest: New Recruit
- [x] 9ad5dce SQL: Update /dev/world_database.sql
- [x] aac03a8 DB/Item: Northrend Mystery Gem Pouch (3.3.5)
- [x] 0d286f8 Update 2014_10_24_00_world.sql
- [x] 499cf73 DB/Misc: Fix 2 startup errors
- [x] 39b7ab2 DB/Pathing: Mattie Alred
- [x] 5085375 DB/Quest: Sniffing Out the Perpetrator (Horde Only)
- [x] d680e82 DB/Misc: Hellfire Peninsula Pathing
- [x] 8274cae DB/Creature: Fix 2 startup errors
- [x] 3965ee3 forgot to copy and paste line to set guid
- [x] ee623a4 DB/Gameobject: Everfrost Chip

**Comment by dr-j** [comment]
- [x] https://github.com/TrinityCore/TrinityCore/commit/6ad8f4b3403f86bfe93eebe2487a98a48768eba6
- [x] https://github.com/TrinityCore/TrinityCore/commit/fb1b7f66a5d959e4b080a8b25cd697c9764a098f
- [x] https://github.com/TrinityCore/TrinityCore/commit/97d415d1b2a429557f667f9c30e8577ab89e6434
- [x] https://github.com/TrinityCore/TrinityCore/commit/e0d1070851389b2699a731ac109bc5f4cd293d1c
- [x] https://github.com/TrinityCore/TrinityCore/commit/4874c9fc7892d1c9596ab6de12d40e55b5d65355
- [x] https://github.com/TrinityCore/TrinityCore/commit/4a6d169e4f4b800d51f12ec282ed4c33b1d14093

**Comment by jackpoz** [comment]
cherry-picked some commits and removed from the ToDo list some already merged in the past or not applicable to 6.x

**Comment by Shauren** [comment]
[ ] 6d70acbbd66959f7b6896a19ce3f2a25ccf94f2e  Core/Spells: Renamed SPELL_ATTR4_TRIGGERED to SPELL_ATTR4_CAN_CAST_WH…

…ILE_CASTING

**Comment by DDuarte** [comment]
Everything done. Please post new commits after the following, do **not edit** previous posts.

------------------

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d4db0c15c7e59f7139619720be3c26a48e6ff259

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/b69fd4ac682347b8b735ac7116ada25d79698933 ahbot stuff, merge commit has additional changes to the merged pr

**Comment by Aokromes** [comment]
-[ ] DB/Misc: Fix a runtime error cb3fcea

**Comment by Aokromes** [comment]
- [ ] DB/Misc: Remove Eternal Might from NR Alchemy Research b31391d
- [ ] DB/Creature: Magmoth Shaman / Totem 0e4db89
- [ ] DB/Creature: Beryl Treasure Hunter 2449baf
- [ ] DB/Creature: Kvaldir Mist Lord 926df37
- [ ] DB/Creature: Fireguard Destroyer a61b2be
- [ ] DB/Quest: Mission: Plague This d8c67f3
- [ ] DB/Creature: Borean Tundra pathing ad58fd5
- [ ] DB/Creature: Lunchbox b4a62e0

**Comment by Aokromes** [comment]
- [ ] DB/Creature: Fix startup and runtime errors a218ce4
- [ ] DB/Quest: Fix Aces High! 73709e7
- [ ] DB/Creature: Scavenge-bot 004-A8 e25336a
- [ ] DB/Creature: Stonebreaker - Waypoints and Keb'ezil's tweak 61b116e
- [ ] DB/Creature: Terokkar waypoints 1 244c09d

**Comment by DDuarte** [comment]
- [ ] Fix Cooldown for Raise Dead (Ghoul) 1d627ca1ea2e5bc15907ab9b81bf3f03f9effb36

**Comment by Aokromes** [comment]
- [ ] c25ad02 - DB/Creature: Fix SAI target_type for Scarlet Peasant

**Comment by Aokromes** [comment]
4.3.4
- [ ] DB/Quest: A Little Oomph 538b364  
- [ ] DB/Quest: A Daughter's Embrace 94671b8  
- [ ] DB/Quest: Variety is the Spice of Death c95510e  
- [ ] DB/Quest: Take to the Skies 7886d3a  
- [ ] DB/Quest: The Grasp Weakens a4db55e  
- [ ] DB/Quest: Planting the Seed of Fear 5fd36a6  
- [ ] DB/Quest: Quest: Holland's Experiment 0a27c13  
- [ ] DB/Quest: Johaan's Experiment b398c0a  
- [ ] DB/Creature: Risen Recruit 15ad27a  
- [ ] DB/Quest: The Shadow Grave 51b0fbf  
- [ ] DB/Quest: Tirisfal - Item-Quest-Drops dccf39a

**Comment by Aokromes** [comment]
3.3.5a

- [ ] 94a9797 - DB/Quest: The Black Knight's Fall

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/62001360dd1d08b2f33fba0f20425867b1b0a069 sql deadlock handling

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/2eee1b349f599f92f78c58418d128f386ef3b86d ahbot bidder

**Comment by Aokromes** [comment]
- [ ] 5403658 - DB/Misc: Fix startup errors

**Comment by Aokromes** [comment]
4.3.4
- [ ] db2ada8 - DB/Creature: Maxx Avalanche

**Comment by Aokromes** [comment]
-[ ] f180bc2 - DB/Creature: Hellfire Peninsula - Waypoints 5
-[ ] 664de1e - DB/Creature: Darnassian Scouts
-[ ] 7691d47 - DB/Creature: Nexus-King Salhadaar
-[ ] 164c12c - DB/Creature: Plagueborn Horror

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/9582b32d22ef9c842349a5be012bdcae4674d6c9 LFG stuff

**Comment by Aokromes** [comment]
3.3.5a
- [ ] cfc5fb2 - DB/Misc: Fix a few startup errors from recent Updates
- [ ] 7800100 - DB/SAI: Durnan Furcutter
- [ ] 6c7cfcc - DB/Misc: Fix startup error
- [ ] 0651b82 - DB/Gameobject: Add 2 missing gameobjects

**Comment by Aokromes** [comment]
3.3.5a.
- [ ] 890d1fe - DB/Misc: Luna Festival (Commoner texts & Gossip)
- [ ] 1967dfc - DB/Creature: Hai'shulud, Mature Bone Sifter and Tunneler

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/56186319bdd41dd26b6cc14f84e6e41eef5d953b cooldown stuff by shauren, some code changes required for 335 tho

**Comment by Aokromes** [comment]
- [ ] DB/Creature: Mug'gok

**Comment by Rushor** [comment]
3.3.5a

- [ ] https://github.com/TrinityCore/TrinityCore/commit/7fbf08d644b6e973e37ed8c81f4866ef15c66271 - DB/Creature: Complete Borean Tundra Movement

**Comment by Aokromes** [comment]
3.3.5a
- [ ] 3820d80 - DB/Misc: Fix startup errors

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/b89f3be8d52f6b13bf1008bcbfe45b9e0f9d3ae0 force a config to Enabled

**Comment by DDuarte** [comment]
- [ ] 4999864c4a85f49513fe9ef7e091f308c0343952 Core/Logs: Throw a little more sensible textoutput when missing maps/…
- [ ] abee9046a6d92e2f0ba9de9c97ce6304c2fcb883 Core/Achievements: check db criteria data for all achievements
- [ ] 8c8ca2ab8de4ced62b1bc9205c8bc72c9b3c8012 Core/Log: Change periodic spell notificiations to DEBUG-level and set…
- [ ] cffef1e80d853ca55887f19b94380b47e45b039e Core/Log: Move a few PetHandler INFO-notifications over to DEBUG-level

**Comment by Aokromes** [comment]
- [ ] 092e61c - DB/Creature: Skettis Waypoints 1

**Comment by Aokromes** [comment]
- [ ] a89cfb1 - DB/Creature: The Vortex Pinnacle trash SAI

**Comment by dr-j** [comment]
- [x] https://github.com/TrinityCore/TrinityCore/commit/b6e3640fce9e19c04c9f3662c86a3cc5a1f19395	DB/Item: The Egg of Mortal Essence 
- [x] https://github.com/TrinityCore/TrinityCore/commit/a0e5f5a37621465cb20680a2869c9cdb1a86eeb0 DB/Spell: Elixir of Minor Accuracy
- [x] https://github.com/TrinityCore/TrinityCore/commit/90899e7395d278e3db113af874e80aeede84fc84 DB/Quest: Wanted: Murkdeep!   (???)
- [x] https://github.com/TrinityCore/TrinityCore/commit/dc8fabe9e6d60167185d9561c55dbf4e9f434b8e DB/Achievement: Flirt with Disaster (Faction change issue)
- [x] https://github.com/TrinityCore/TrinityCore/commit/73f74ffcabc68738d279f740cdea21cca8cb42ad DB/Quest: Krolmir, Hammer of Storms
- [x] https://github.com/TrinityCore/TrinityCore/commit/1124daab36cdd9a8febb3f980adc15e78d72c602 DB/Misc: Crusader's Pinnacle Phasing
- [x] https://github.com/TrinityCore/TrinityCore/commit/98f7094119f622d2e0246818a9622abd088fe001 DB/Creature: Northsea Kraken
- [x] https://github.com/TrinityCore/TrinityCore/commit/a7bd64a4a640d219afd205d841c7e93638cad240 DB/Item: Bountiful Feast
- [x] https://github.com/TrinityCore/TrinityCore/commit/879678e50f71666646b2489ee2f86336e21a28a0 DB/Quest: A Distraction for Akama

**Comment by Aokromes** [comment]
3.3.5a
- [ ] 37298bb - DB/Creature: Add some missing gossips

**Comment by Aokromes** [comment]
3.3.5a
- [ ] 50a9424 - DB/Creature: Conditions for king jokkum
- [ ] 2676d56 - DB/Quest: Basic Chemistry
- [ ] 5469b4c - DB/Quest: A Rough Ride

**Comment by jackpoz** [comment]
- [ ] Core/CrashHandler: Fix char[] without '\0' handling https://github.com/TrinityCore/TrinityCore/commit/fd844e3d7e18212d6e8dd6531eac1f198527926b

**Comment by Aokromes** [comment]
- [ ] fa7663a - DB/Conditions: Fix Taking of Mind Tricks for Alliance Players 
- [ ] 32b7929 - DB/Quest: On Nethery Wings

**Comment by Aokromes** [comment]
4.3.4
- [ ] a266077 - DB/Quest: Demonic Thieves item can be looted without quest

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/003d67708b9a279da3d37e5ef06eb32ceab53964 Shared/Logs: Improve log performances

**Comment by click** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/db302c28c24a5bc9f77463555453bb09ca4b094a

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/22403121fe9c762c82dc32913aeba46a7e76a004 Core/Dungeon Finder: Fix Vote Kick breaking LFG queue

**Comment by Aokromes** [comment]
3.3.5a
- [ ] 3fbd10d - DB/Creature: Fix 2 factions and 1 spawn coords

**Comment by Aokromes** [comment]
4.3.4
- [ ] 9ffa421 - DB/QUEST - Ride to the Undercity

**Comment by jackpoz** [comment]
- [ ] https://github.com/TrinityCore/TrinityCore/commit/f1ae2c7b73f3fbc665acac8fd70ce325f20e1194 Revert "*Do not allow players to use vehicles to go further than 1st …
…boss in Ulduar."

**Comment by Rushor** [comment]
3.3.5
- [ ] https://github.com/TrinityCore/TrinityCore/commit/9927bb241d3e0ef075944dbfdb0c8481d06204cb - DB/Quest: The Escape + Collecting Kelp
- [ ] https://github.com/TrinityCore/TrinityCore/commit/0014a9d1fc308e679438353c58626a76502d7970 - DB/SAI: Tortured Skeleton 
- [ ] https://github.com/TrinityCore/TrinityCore/commit/00f97e3ca8e8362ad74396eb8d3c738d76e21240 - DB/Creature: Dread Tactician 
- [ ] https://github.com/TrinityCore/TrinityCore/commit/7af2a49e635000c5abd68ed2ae99d9075d55dfbf - DB/Quest: Disrupt Their Reinforcements 
- [ ] https://github.com/TrinityCore/TrinityCore/commit/810b998e773f5cb9d8f83c1089b534900fcee84b - DB/Creature: Expedition Warden
- [ ] https://github.com/TrinityCore/TrinityCore/commit/ca174e4239b4801996da22adfdf9d82919852eb1 - DB/Creature: Susan Tillinghast 
- [ ] https://github.com/TrinityCore/TrinityCore/commit/1d8f98d988171fab895b23c2d0ca2d2fb39d352f - DB/Object: Stone of Remembrance
- [ ] https://github.com/TrinityCore/TrinityCore/commit/04e1f35043f95969e4600901fa22171a90c8afee - DB/SAI: Scarlet Initiate

**Comment by DDuarte** [comment]
- [ ] cf14e9051d15e33ca9fa87be3287d2a628faedef Core: Move FillCirclePath function to MotionMaster

**Comment by Aokromes** [comment]
3.3.5a
- [ ] d3a2080 - DB/Misc: Fix startup errors
- [ ] 125ab57 - DB/Creature: Misc SAI updates
- [ ] e1f75fe - DB/Creature: Misc SAI updates
- [ ] 222c49a - DB/Creature: Misc SAI updates
- [ ] 66aead3 - DB/Creature: Misc SAI updates 
- [ ] 9ac83f8 - DB/Creature: Misc SAI updates 
- [ ] 7fa1f95 - DB/Creature: Misc SAI updates 
- [ ] d3a2080 - DB/Misc: Fix startup errors

**Comment by MitchesD** [comment]
Everything done

------------------
