### ISSUE TITLE
[SmartAI] Set Run action bugged

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#13802]
Bug: Set Run On/Off doesn't make the npc run. It will always walk.

For example:
```SQL
-- SAI Set Run On is bugged, if fixed this will work.
-- Honor Hold Cavalryman SAI
SET @ENTRY := 16843;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,11,0,100,0,0,0,0,0,59,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Honor Hold Cavalryman - On Respawn - Set Run On");
```

Core: 411e04811a7f9d8e51ebfc2752f96ec5f4c355dc

**Comment by jackpoz** [comment]
as @Killyana said SAI movement mode has nothing to do with a creature moving through a waypoint path, you have to set the movement mode on the path node:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp#L164

Your example script will affect the creature when it will enter combat and it will move to the enemy running https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/AI/SmartScripts/SmartAI.cpp#L579

There is currently no "override waypoint node movement mode" SAI action.
