### ISSUE TITLE
[3.3.5] Possible bad calculation for Earth Shield

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#13808]
In src/server/scripts/Spells/spell_shaman.cpp
class spell_sha_earth_shield : public SpellScriptLoader

Lines 322-327
```c++
//! WORKAROUND
// If target is affected by healing reduction, modifier is guaranteed to be negative
// value (e.g. -50). To revert the effect, multiply amount with reciprocal of relative value:
// (100 / ((-1) * modifier)) * 100 = (-1) * 100 * 100 / modifier = -10000 / modifier
if (int32 modifier = GetUnitOwner()->GetMaxNegativeAuraModifier(SPELL_AURA_MOD_HEALING_PCT))
ApplyPct(amount, -10000.0f / float(modifier));
```

As the comment says, the modifier is guaranteed to be negative, so doing -10000/mod yields a positive number bigger than what was intended.

ie Healing reduction 10%, mod is -10
-10000/-10  = 1000
After the call to ApplyPct, amount is 1000% it's original value (ie, was increased by 900%)

The correct call should be:
```c++
ApplyPct(amount, 100.0f + float(modifier));
```

**Comment by Unholychick** [comment]
so that workaround is even more faulty than the hack it tries to cover up. should just remove it entirely and hope that one day we can properly redefine how bonuses of spells with SPELL_DAMAGE_CLASS_NONE are calculated

**Comment by Frytiks** [comment]
I'm using @ariel- "fix", works pretty well. Cause with old calculation players reported, heal on Valithiria was 85k, with ariel fix works now good.

**Comment by ariel-** [comment]
@Unholychick mind elaborating why? As evidenced by the screenshots, it's obvious the original code is wrong too, a reduction should never become an increase.

**Comment by Unholychick** [comment]
@ariel- i think you misunderstood my comment. the "workaround" that you are removing is the really faulty one. addng another hack however, wont solve anything. 
keep in mind that it is not only negative healing % done that is applied twice, positive is aswell.
with or without those hacks(workarounds if you will) earth shield will get double benefit whenever there is not a mortal strike effect on target.

**Comment by Rushor** [comment]
hack will be hacked by another hack - removing patchfix lable for now

**Comment by Keader** [comment]
I´m using Ariel fix, and working xD

**Comment by Runico** [comment]
Weqwe's Earth Shield heals Weqwe for 1210.(8050 Overhealed)
Weqwe's Earth Shield heals Weqwe for 3944.(5316 Overhealed)
