### ISSUE TITLE
[3.3.5] Bug autoattack doesn't cancel when get out of PvP Areas like Gurubashi Arena

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13815]
If you are autoattacking an enemy in, for example, Gurubashi Arena (Battle Ring) and then the enemy and you get out of it, you will continue autoattacking the enemy until he dies/you stop autoattacking/you swap or cancel the target.

This is a very old bug but it isn't fixed yet, players can abuse this very easily.

Using lastest rev https://github.com/TrinityCore/TrinityCore/commit/cc00321409707e50da0826b758bcd1242d7fcec7
##

**Comment by Frytiks** [comment]
This issue still exist ?

**Comment by tkrokli** [comment]
In the above quote from TakenBacon, does he mean something like these sections?
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L7611
and
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.h#L1710

I also found the keyword `UpdatePvPState` in this file,
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L4852
but I somehow doubt that it is directly related to the suggested way of fixing it.

@Frytiks : I don't know, I haven't tested if the issue still exists or not.

**Comment by Killyana** [comment]
Still valid on rev. 0148832b322b
