### ISSUE TITLE
[6.x] Creature_classlevelstats (ArmorCalculation)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#13818]
We've investigated, that the mitigation of creatures are calculated as followed:

TotalArmor/(TotalArmor+K) = Mitigation

TotalArmor must be something like BaseArmor*ArmorMod

K is defined in gtArmorMitigationByLevel.dbc
K is set by the Attacker!!!!!!!!!

Id
0  (Level 1)
1  (Level 2)
...

We also found out that the formula: 
TotalArmor/(TotalArmor+K) = Mitigation

Is also correct for calculation of character mitigation:

Example on Retail:
Level: 92 Shaman
Armor: 326
Migitation in Tooltip: 19,54% (Shows Migitation for Level Attacker = Level Target)
=> Level Attacker = 92
K: 1342 (Row 91 = Level 92) (Attacker)

Calculation:
TotalArmor/(TotalArmor+K) = Mitigation
326/(326+1342) = Mitigation
326/1668 = Mitigation
0,1954 = Mitigation=> 19,54%

Mitigation in Tooltip = Mitigation calculated! PROOF

After that we've found a Bluepost (Battlenet Developer) with Base Armor by Level and Class.
http://www.wowhead.com/bluetracker?topic=13087818929

Armor Values for Warlords Creatures
Level, Armor for Paladin/Warrior/Rogue Creatures, Armor for Mage Creatures
90      445         356
91      504         403
92      571         457
93      646         517
94      731         585
95      827         662
96      936         749
97      1059       847
98      1199       959
99      1357      1086
100    1536      1229
101    1670      1336
102    1804      1443
103    1938      1550

101-103 there is no Attacker = Target with Level 101-103
Last combinations would be Attacker 100 -> 103 Target
OR
Attacker 103 (Boss) -> Target 100 (Player)

After calculating the Base migitation of all these daata (warrior only)

There is as constant mitigation at 29,84% (seems correct from Level 90-100)
for Attacker Level = Target Level
http://abload.de/img/unbenanntnnsad.png
(Mitigation not migitation sorry)

This gave us a formula to calculate other BaseArmors:
BaseArmor = 0,42533498*K
(Not sure if this is correct for creature under 90)

Level	BaseArmor
1	67
2	71
3	75
4	80
5	84
6	88
7	92
8	97
9	101
10	105
....

If we calculate the BaseMitigation with our calculated BaseArmors for Level 85 it would be:

BaseArmor/(BaseArmor+K) = BaseMitigation
424/(424+3610)  = BaseMitigation
424/4034 = BaseMitigation
0,1051 = BaseMitigation => 10,51% BaseMitigation

But this doesn't explain why we hit these creatures with 100-200k damage.
There is a calculation for creatures under MoP Expansion.
If your Level difference is higher than 10 your dmg is multiplicated with 16,5.
So the Attack which normaly deals 10k at Level 100 Creatures will deal 160k at level 85 creatures.
Like described here: http://us.battle.net/wow/en/forum/topic/13087818929?page=2#37

**Comment by funjoker** [comment]
https://gist.github.com/funjoker/2c0b63bf3aa4258241f9

**Comment by funjoker** [comment]
#13842

**Comment by funjoker** [comment]
Or the level 1-10 got armor mod 0,5

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/pull/13833

**Comment by msoky** [comment]
please retest after https://github.com/TrinityCore/TrinityCore/commit/a4d03a5ed1fb94e763559b45522196262fdd1b2c

**Comment by funjoker** [comment]
is the formula implemented in the core?
otherwise it's unimportant to test armor mitigation :D

**Comment by soulfrost** [comment]
any ideas about how to calc baseDamage?

**Comment by funjoker** [comment]
KFactor has been changed due to Legion. Calculation seems right but the Samples are wrong now

**Comment by funjoker** [comment]
https://github.com/Ovahlord/TrinityCore/commit/e06a313478f9df115b911aca2c738db85436bfea
https://github.com/Ovahlord/TrinityCore/commit/01f2d4ba619b8c48e9009e6096563fb2c8e1eb67
https://github.com/Ovahlord/TrinityCore/commit/6d39d3c9f13414d226519b7c4244f8e9f47453e0
https://github.com/Ovahlord/TrinityCore/commit/18cfd6b8e15c41e346e75631d21c48d5761408af

Just check this pls.

**Comment by Shauren** [comment]
If KFactor changed but is still in gametable extracted from client then its not an issue

**Comment by funjoker** [comment]
Yeah sure. But i couldnt make a proper pullrequest.
So i updated this issue.

**Comment by funjoker** [comment]
I will provide a new file for legion. 
This will include all datas.
