### ISSUE TITLE
4.3.4 DK Spell dont work...

### ISSUE THREAD

**Issue by Samuel1984** [TrinityCore/TrinityCore#13824]
Hello, i have 4.3.4 Core rev. 9a941ae125c8  and have Error on sturtup..

>> Loaded 2462 C++ scripts in 71 ms
Validating spell scripts...
Spell `43265` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_dk_death_and_decay` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
Spell `45204` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `46584` Effect `Index: EFFECT_1 Name: 77` of script `spell_dk_raise_dead` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `46584` Effect `Index: EFFECT_2 Name: 3` of script `spell_dk_raise_dead` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `46584` Effect `Index: EFFECT_1 Target: 8` of script `spell_dk_raise_dead` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `46584` Effect `Index: EFFECT_2 Target: 1` of script `spell_dk_raise_dead` did not match dbc effect data - handler bound to hook `OnObjectTargetSelect` of SpellScript won't be executed
Spell `46584` did not pass Validate() function of script `spell_dk_raise_dead` - script will be not added to the spell
Spell `50842` did not pass Validate() function of script `spell_dk_pestilence` - script will be not added to the spell
Spell `61782` Effect `Index: EFFECT_ALL Target: 56` of script `spell_gen_replenishment` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed

i hope one can help me...

Great Samuel84

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/new
