### ISSUE TITLE
[6.x] playercreateinfo_action doesn't work as it should....

### ISSUE THREAD

**Issue by vegax87** [TrinityCore/TrinityCore#13827]
I noticed 2 problems with playercreateinfo_action: 
1)  needs to be updated with new starting spells
2) I tried to add FrostFire Bolt (id: 44614) to every mage using this query
INSERT INTO playercreateinfo_action(race, class, button, action, type) VALUES
(1,8,0,44614,0),
(2,8,0,44614,0),
(3,8,0,44614,0),
(4,8,0,44614,0),
(5,8,0,44614,0),
(7,8,0,44614,0),
(8,8,0,44614,0),
(9,8,0,44614,0),
(10,8,0,44614,0),
(11,8,0,44614,0),
(22,8,0,44614,0),
(24,8,0,44614,0);

but after I created a new mage, it doesn't show FrostFire Bolt in the 1st hotkey
I don't understand what's wrong....

**Comment by mhubregtse** [comment]
In 7.0.3 its changed to Flurry (Spell id: 44614)
