### ISSUE TITLE
[Crash] ObjectMgr::GenerateLowGuid

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13845]
Since last week I have 5 or 6 crashes a day.

http://pastebin.com/iKkgaFJz
http://pastebin.com/SKP8QmsS
http://pastebin.com/MT2ZFNfE
http://pastebin.com/6irhhmBV

51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by Shauren** [comment]
Creature guid overflow.

User problem, reguid your `creature` table

**Comment by Pirricli** [comment]
Any help? How to reguid the table? Or What could be the begining of the problem to go back?
