### ISSUE TITLE
[6.x] creature_classlevelstats WoD and MoP (HP+Armor)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#13842]
Update for Creature_classlevelstats Mop + WoD

TDB6

https://gist.github.com/funjoker/938d644e6abb1b76f49d

**Comment by Orphus** [comment]
You got any source or how did you calculated this?

**Comment by msoky** [comment]
what about https://github.com/TrinityCore/TrinityCore/issues/13823 ???

**Comment by NorthStrider** [comment]
@Orphus the love of magic and mathematics by calculating the stuff :P

**Comment by Orphus** [comment]
@NorthStrider Of course, i know that it can be calculated from wowhead health / hpmod in template
yet what I wanted to know is whether he also checked pre-mop stats, I think those may have changed too. Also it misses dmg calculations. Any idea how to calculate them? i cant catch malcrom so he could explain :)

**Comment by funjoker** [comment]
Inside sniffdata is MAXHEALTH and healtmulti set. You can calculate them easyly.
I know that they changed in Cata too. But there are several expansions combined together.
Classic and Cata. I need to check them first.
This file will not but pulled until it's needed. But you can test this fix (PS: Armor is correct only the calculation inside core is outdated). You can test these values and give a feedback.

**Comment by funjoker** [comment]
Here is your formula @Orphus :

MaxHealth/HpMulti = BaseHP :O

ArmorValues for Level 90-103 are posted by Celestalon.
Calculation of armor is easy if you've got the formula of mitigation.

**Comment by funjoker** [comment]
Okay. Things changed.
HP is now read out of DBC.
But armor ?

**Comment by msoky** [comment]
armor? i dont know...but mana dont have DBC :(

**Comment by msoky** [comment]
what about level 104 and 105? specially http://www.wowhead.com/npc=15371/sunstrider-guardian have level 105

**Comment by Orphus** [comment]
@funjoker have you possibly cheked whether blizz dev hadnt posted some data about attack power/base damage? or havent you done some research about it?

**Comment by msoky** [comment]
please retest after https://github.com/TrinityCore/TrinityCore/commit/a4d03a5ed1fb94e763559b45522196262fdd1b2c

**Comment by Kinzcool** [comment]
@funjoker repopen an issue with the armor only as most of the fix is now already implemented on the form of DBC loading.

**Comment by funjoker** [comment]
https://gist.github.com/funjoker/938d644e6abb1b76f49d

Just updated it.
Sorry for being soooooo late xD

**Comment by humaniti** [comment]
@funjoker I can only see BaseMana and Armor, where is the HP?:D

**Comment by msoky** [comment]
@humaniti could you say which NPC have bad HP? :) HP is directly take from dbc files...so every NPC have blizzlike HP without set in creature_template...this change made 1 or 2 years ago
