### ISSUE TITLE
[6.x] WorldServer: Error creating bnet and game accounts

### ISSUE THREAD

**Issue by Luhzinha** [TrinityCore/TrinityCore#13840]
When i try to create a battle net account by using the world server console with the command

```
bnet create [login] [password]
```

I get the error in the auth.battlenet_accounts that say im using an incorrect value "0000-00-00 00:00:00"

```
SQL(p): INSERT INTO battlenet_accounts (`email`,`sha_pass_hash`) VALUES ('LUHZINHA@', 'D15AFA22536DF9E16FDFAD2D0EDEFC23A4D525A41B2E82856C8C5723730B0738')
 [ERROR]: [1292] Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_login' at row 1
Unhandled MySQL errno 1292. Unexpected behaviour possible.
```

To fix that i used this SQL Script to update the last_login column from the battlenet_accounts and accounts.

``` sql
ALTER TABLE `battlenet_accounts`
MODIFY COLUMN `last_login`  TIMESTAMP NULL DEFAULT NULL AFTER `lock_country`;
ALTER TABLE `account`
MODIFY COLUMN `last_login`  TIMESTAMP NULL DEFAULT NULL AFTER `lock_country`;
```

Making the default value of the last_login column to be (Null) the error are fixed, after you login on the game, the last_login column works normally, registering the timestamp of when you have logged in.
##

**Comment by Aokromes** [comment]
Better

```sql
ALTER TABLE `battlenet_accounts`
MODIFY COLUMN `last_login` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' AFTER `lock_country`;
ALTER TABLE `account`
MODIFY COLUMN `last_login` timestamp NOT NULL DEFAULT '2000-01-01 00:00:00' AFTER `lock_country`;

**Comment by Aokromes** [comment]
Even better

```sql
ALTER TABLE `battlenet_accounts`
MODIFY COLUMN `last_login` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `lock_country`;
ALTER TABLE `account`
MODIFY COLUMN `last_login` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `lock_country`;

**Comment by Luhzinha** [comment]
I had think about put the current_timestamp, but this is the Last Login time, if the player has created the account and haven't logged in the game yet, the last login is supposedly to be empty, that's why i had put (Null) by default.

**Comment by juanjose96** [comment]
Hi, I have an error when creating users from the web, here I put the code example.

The error is that when trying to enter from the game, I get that information is incorrect.

I think the code is incorrect.

Here's the code:

include_once 'db_connect.php';
include_once 'psl-config.php';

$error_msg = "";

if (isset($_POST['username'], $_POST['email'], $_POST['p'])) {
    // Sanitize and validate the data passed in
    $username = filter_input(INPUT_POST, 'username', FILTER_SANITIZE_STRING);
    $email = filter_input(INPUT_POST, 'email', FILTER_SANITIZE_EMAIL);
    $email = filter_var($email, FILTER_VALIDATE_EMAIL);
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        // Not a valid email
        $error_msg .= '<p class="error">The email address you entered is not valid</p>';
    }
    
    $password = filter_input(INPUT_POST, 'p', FILTER_SANITIZE_STRING);
    if (strlen($password) != 128) {
        // The hashed pwd should be 128 characters long.
        // If it's not, something really odd has happened
        $error_msg .= '<p class="error">Invalid password configuration.</p>';
    }

    // Username validity and password validity have been checked client side.
    // This should should be adequate as nobody gains any advantage from
    // breaking these rules.
    //
    
    $prep_stmt = "SELECT id FROM auth.account WHERE email = ? LIMIT 1";
    $stmt = $mysqli->prepare($prep_stmt);
    
    if ($stmt) {
        $stmt->bind_param('s', $email);
        $stmt->execute();
        $stmt->store_result();
        
        if ($stmt->num_rows == 1) {
            // A user with this email address already exists
            $error_msg .= '<p class="error">A user with this email address already exists.</p>';
        }
    } else {
        $error_msg .= '<p class="error">Database error</p>';
    }
    
    // TODO: 
    // We'll also have to account for the situation where the user doesn't have
    // rights to do registration, by checking what type of user is attempting to
    // perform the operation.

    if (empty($error_msg)) {
        // Create a random salt
        $random_salt = hash('sha512', uniqid(openssl_random_pseudo_bytes(16), TRUE));

        // Create salted password 
        $pass_word = hash('sha512', $password . $random_salt);
        
		$sha_pass_hash= sha1(strtoupper($username) . ":" . strtoupper($password));
		
		$sha256_pass_hash = strtoupper(bin2hex(strrev(hex2bin(strtoupper(hash("sha256",hash("sha256", strtoupper($email)).":".strtoupper($password)))))));
		
        // Insert the new user into the database 
	
$insert2_stmt = $mysqli->prepare("INSERT INTO auth.battlenet_accounts (email, sha_pass_hash) VALUES (?, ?)");
		$insert2_stmt->bind_param('ss', $email, $sha256_pass_hash);
		  
		$ids = mysqli_insert_id();
		
		$code01 = "".$ids."#1";
		$bnt_inx = "1";
        if ($insert_stmt = $mysqli->prepare("INSERT INTO auth.account (username, email, sha_pass_hash, password, salt, battlenet_account, battlenet_index) VALUES (?, ?, ?, ?, ?, ?, ?)")) {
            $insert_stmt->bind_param('sssssss', $code01, $email, $sha_pass_hash, $pass_word, $random_salt, $ids, $bnt_inx);
			
			
			
            // Execute the prepared query.
            if (! $insert_stmt->execute() | ! $insert2_stmt->execute()) {
                header('Location: ../error.php?err=Registration failure: INSERT');
                exit();
            }
        }
        header('Location: ./register_success.php');
        exit();
    }
}

This code contains three different encodings, one with sha1, sha256(sha_pass_hash) and another is + salt (for the web, does not affect gameplay) that goes to the accounts table(password), finally we sha256 coding that goes to the table battlenet_accounts(sha_pass_hash).

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c2aead1da5b6cb9a3a69e276b3f12a2c76b9ab86
