### ISSUE TITLE
[6.x](?)Voidwalker dont have Spells

### ISSUE THREAD

**Issue by davidox92** [TrinityCore/TrinityCore#13843]
The Voidwalker dont have this two spells ...

http://www.wowhead.com/spell=17735
http://www.wowhead.com/spell=3716
(tested by Bloodelf Warlock)

Core: e6cc39258d1b
DB: TDB 434.09

**Comment by timh52280** [comment]
The voidwalker does have this spells when is created, just right now I confirmed this on TrinityCore rev. a89cfb16576e 2015-02-23 11:45:04 +0100 (4.3.4 branch) (Win32, Release), TDB 434.09

**Comment by Rushor** [comment]
pls recheck if this issue also happens on 6.x

**Comment by Aokromes** [comment]
No answer after more than 4 months, closing.
