### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13848]
Greetings, today i run Static Code Analysis in Visual Studio, and i get this 

        UpdateMask(UpdateMask const& right) : _bits(NULL)
        {
            SetCount(right.GetCount());
            memcpy(_bits, right._bits, sizeof(uint8) * _blockCount * 32);
        }

C6387	Invalid parameter value	'_bits' could be '0':  this does not adhere to the specification for the function 'memcpy'. 	collision	updatemask.h	42
		'_bits' should not be NULL, because this is not consistent with the SAL annotation on 'memcpy'			42

Core rev: https://github.com/TrinityCore/TrinityCore/commit/51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by Intel** [comment]
I don't see how this possibly could leak memory.
It is probably complaining about *_bits(NULL)* which is not needed here

**Comment by Frytiks** [comment]
@Intel There in core i'm getting so much types like "Memory Safety" http://prntscr.com/5o02jn

**Comment by Intel** [comment]
Also: https://github.com/TrinityCore/TrinityCore/issues/13805#issuecomment-68247608

**Comment by Frytiks** [comment]
I just run it, cause the server now with 1 player online have 50 time diff, and with 500 players online have 120-150 diff, but in Alterac Valley where is so much spell casted at same time is 700-1200diff and server lagging so hard.
