### ISSUE TITLE
NPC Plague Scientist 37023

### ISSUE THREAD

**Issue by Servas** [TrinityCore/TrinityCore#13841]
NPC Plague Scientist http://www.wowhead.com/npc=37023 should cast the spell 71103 http://www.wowhead.com/spell=71103.

In this moment the npc don´t cast the spell.

51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by Killyana** [comment]
There's already an issue for Icecrown Citadel Trash Script: https://github.com/TrinityCore/TrinityCore/issues/8853
You can get the SAI for this npc here: http://www.trinitycore.org/f/topic/4988-icc-trash-compendium/

**Comment by Servas** [comment]
thank you, I go to check this information.
