### ISSUE TITLE
Missing Throne of Thunder areatrigger. WOD branch 6.0.3

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#13846]
Happy New Year!
TDB 6.0.0
Map 1098, area 6622.
Areatrigger.dbc number
``` CODE
8848, 8870, 8881, 8888, 8896, 8897, 8898, 8910, 8911, 8912, 8913, 8930, 8931, 8932, 8933, 8934, 8935, 8936, 8937, 8940, 8943, 8944
```
When you use the .go trigger, swears on Valid. In short, I can not get there.
Command .go xyz also swears on Valid coordinates.

**Comment by AriDEV** [comment]
because Mist of Pandaria raid instances arent added right now

**Comment by Ulduar** [comment]
It Is A Pity. If I could get inside, I would command .tele add would add and posted coordinates.
@AriDEV  thanks for answer.

**Comment by Ulduar** [comment]
Can it is useful to someone.
``` SQL
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) values
('2022','5710.84','4094.3','156.463','3.88393','1098','Lei Shen'),
('2023','5525.29','4654.03','-2.47721','3.1433','1098','Ra-den Room');

```
