### ISSUE TITLE
[crash] Unit::RemoveAurasByType

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13851]
I recently get this crash.

http://pastebin.com/nZRMrkm8

51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by avengerweb** [comment]
Confirm

**Comment by jackpoz** [comment]
any "confirm" is useless without a crashlog

**Comment by Eldro** [comment]
http://pastebin.com/b7w3ZB0e
Confirm

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/wiki

**Comment by Frytiks** [comment]
I can confirm this crash too, but it`s so rare.

**Comment by tkrokli** [comment]
jackpoz commented on 7 Mar :
> any "confirm" is useless without a crashlog

**Comment by Xxxhackerxxx** [comment]
Confirm

**Comment by Voidx** [comment]
http://pastebin.com/3zrEHrLg
so much crash.

**Comment by jackpoz** [comment]
@Voidx https://github.com/TrinityCore/TrinityCore/wiki , your crash report is incomplete

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.

**Comment by zanzark** [comment]
Still crashing today.

**Comment by tkrokli** [comment]
@zanzark : there is a new issue posted for this kind of crash. Post your comment & crash log there:
**[[3.3.5][Crash]Unit::RemoveAurasByType](17063) #17063**

**Comment by jackpoz** [comment]
> Still crashing today.

This message is totally useless and doesn't provide anything useful to move towards a fix. Take your time to read how to properly report a crash.
