### ISSUE TITLE
[6.x] CascLib

### ISSUE THREAD

**Issue by Saylance** [TrinityCore/TrinityCore#13859]
Merge last https://github.com/ladislav-zezula/CascLib commits.
To fix map extractor errors. Becouse, it didnt work.

TDB 6.0.0
Thanks !

**Comment by Shauren** [comment]
It will be done in due time.

**Comment by Saylance** [comment]
https://github.com/ladislav-zezula/CascLib/commit/3e9c00b536b2379becfec139244c9da12ac9fde9

Ok

**Comment by DDuarte** [comment]
@Saylance: that check was ninja-fixed in our sources: https://github.com/TrinityCore/TrinityCore/blob/6.x/dep/CascLib/src/CascOpenStorage.cpp#L536

**Comment by Saylance** [comment]
So fast
So ninja
wow

Doctor Who ?

**Comment by Saylance** [comment]
Ouuppsss....

Thanks.
