### ISSUE TITLE
[3.3.5] Reflected Death Grip doesn't do the effect on the DK

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13852]
Death Grip is reflected but nothing happens after that, its supposed to move the DK to the warrior but it only shows "Reflect".

![](http://puu.sh/e1B71/e72973ea27.jpg)

![](http://puu.sh/e1B7N/5c81cca4c2.jpg)

On 3.3.5 branch lastest rev https://github.com/TrinityCore/TrinityCore/commit/51f5ce1b7364b730cb0bdabcfd6ad18794213f95

**Comment by tkrokli** [comment]
Isn't this problem covered by the spell reflect issue in #9745 ?
It used to be handled in #5954 , but that issue got closed 11 weeks ago (Legacy).

**Comment by Raydor** [comment]
Hmmm maybe, in #9745 they talk about dispell magic which is not fixed at all, but death grip got fixed only because you can reflect it but it does not do any effect on the DK, with Dispell Magic you just can't reflect it.

**Comment by tkrokli** [comment]
OK, I see. If you are able to document the difference between the other issue and yours, you may be able to get this issue reopened, but you need to document it well to convince the other developers here that you do have a different issue which merits a separate issue here on TrinityCore.
