### ISSUE TITLE
Server ignoring Z axis?

### ISSUE THREAD

**Issue by Sharisek** [TrinityCore/TrinityCore#13854]
Ok, here's the thing. 
On our server, everything is ignoring Z axis (examples: you create waypoint in the air, but the npc just fall down on the ground, when you .app at someone, you fall on the ground even if you have fly on.)
Well, it bothers me because you can't make waypoints in spawned gameobjects (NPC's falling on the ground). 
Also, when you turn off gm fly in the air, you simply stay in the air and can fly further. (Don't know if it have something in common.) Of course, I can set for npc inhabitan type 4 (only air) in DB, but that's not solving the problem with fly etc.
Any ideas? :/ (branch 4.3.4)

**Comment by MitchesD** [comment]
not a valid ticket

we need to know your core hash revision

**Comment by Sharisek** [comment]
Sorry, first time trying to solve problems here. :D Core hash revision is
commit 9ab74b39109bb611c0deb5228640b92f22c83089
Author: Shauren <shauren.trinity@gmail.com>
Date:   Sat Sep 6 22:58:29 2014 +0200

**Comment by Aokromes** [comment]
1st law before reporting bug, update core to head.

**Comment by Sharisek** [comment]
Okay, I lived in lie that we have updated core. Hmpf.
Ok then, thanks and sorry ^_^

**Comment by Sharisek** [comment]
Ok, we updated core to the last revision -

commit 7cb72c2aacbb3c2502bd5d25a52a6e96fe2b9cc8
Author: Shauren <shauren.trinity@gmail.com>
Date:   Sat Aug 16 01:43:42 2014 +0200

But, server is still ignoring Z axis, as I wrote in first post. Some ideas? ^^"

**Comment by MitchesD** [comment]
for me "the last revison" is https://github.com/TrinityCore/TrinityCore/commit/7bf8c98746e6fa69eed1b4706765ae2acd3a6492 (for 4.3.4)

you have still some old revision

**Comment by Eridias-cz** [comment]
Hello,
we used badly command for extract data. Now finally we give true code. 
Updating 7bf8c98..7b67984 
But the problem is still the same as in first post.
