### ISSUE TITLE
[3.3.5] Empty file

### ISSUE THREAD

**Issue by zwj-2014** [TrinityCore/TrinityCore#13869]
Like：

\src\server\scripts\EasternKingdoms\zone_burning_steppes.cpp && 
zone_ironforge.cpp && 
zone_loch_modan.cpp &&
zone_redridge_mountains.cpp &&
zone_stormwind_city.cpp &&
zone_swamp_of_sorrows.cpp &&
zone_tirisfal_glades.cpp &&  Others

These files need it ?

Ver：https://github.com/TrinityCore/TrinityCore/commit/42f1a0babfaacf64df31a934288979f8edfec940

**Comment by DDuarte** [comment]
[zone_burning_steppes.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/zone_burning_steppes.cpp) is not empty
zone_ironforge.cpp does note exist
zone_loch_modan.cpp is not empty
zone_stormwind_city.cpp is not empty
zone_swamp_of_sorrows.cpp is not empty
zone_tirisfal_glades.cpp is not empty

what the actual fuck?..

**Comment by zwj-2014** [comment]
in 6.x .

Sorry!!!!

**Comment by DDuarte** [comment]
6.x is under active development, it does not matter if those placeholder files actually contain any scripts
