### ISSUE TITLE
[6][QUEST] Your Place In The World

### ISSUE THREAD

**Issue by timsar2** [TrinityCore/TrinityCore#13864]
Gornek should Complete Quest but did not response
Core rev. 02bdd542a1c5
TDB :6.00  updated to 2014_12_30_00_world

[Your Place In The World]   (quest=25152)  should complete by Gornek but he will not response on click.

**Comment by timsar2** [comment]
i fixed it.
problem is questGiver has 2 autoaccept quest 1 withouth race permission and the other without prvQuest requairment

DELETE FROM `world`.`quest_template_addon` WHERE  `ID`=25172;
INSERT INTO `world`.`quest_template_addon` (`ID`, `PrevQuestID`) VALUES (25172, 25126);
UPDATE `world`.`quest_template` SET `AllowableRaces`=-1 WHERE  `ID`=25126;
DELETE FROM `world`.`creature_queststarter` WHERE  `id`=39317 AND `quest`=25172;
DELETE FROM `world`.`creature_queststarter` WHERE  `id`=3098 AND `quest`=25126;

**Comment by Gooyeth** [comment]
@timsar2: why has closed issue?

**Comment by timsar2** [comment]
excuse me, i think it was attached to DB and no needed to be open
i'm not clearly with tracker

**Comment by Gooyeth** [comment]
For SQL needs to be created a ticket to be included in TrinityCore (More info: https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md)

This fix also is for 4.3.4 branch.

**Comment by Aokromes** [comment]
@Gooyeth can you create 4.3.4 version of fix?

**Comment by Gooyeth** [comment]
@Aokromes: Would be the same, does not change anything.

**Comment by Aokromes** [comment]
There is no "quest_template_addon" on 4.3.4 :)

**Comment by Gooyeth** [comment]
Oh right! hahaha

```sql
UPDATE `quest_template` SET `PrevQuestId`=25126 WHERE `Id`=25172;
DELETE FROM `creature_queststarter` WHERE `id` IN (3098, 39317);
UPDATE `creature_template` SET `npcflag`=`npcflag` &~2 WHERE `entry` IN (3098, 39317);
```
