### ISSUE TITLE
[6.x] Cannot Connect To World Database

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13861]
I'm not sure if the devs are compiling the source around these new updates;
 something is blocking the Worldserver to connect to the world DB forcing me to use a more stable commit version of the 6.x main but i would like to test the newest revision seeing that they fixed the option to buy items now

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.0o 15 Oct 2014 (library: OpenSSL 1.0.0o 15 Oct 2014)
Using Boost version: 1.57.0
DatabasePool w NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors. Read wiki at http://collab.kpsn.org/display/tc/TrinityCore+Home
Cannot connect to world database 127.0.0.1;3306;root;root;w

**Comment by Gooyeth** [comment]
The user or password in config is wrong, verifies if are correct.

**Comment by dejonxavier** [comment]
my user name and password are correct though.

root
root

**Comment by dejonxavier** [comment]
fixed

**Comment by Rushor** [comment]
you can close the issue for yourself with the 'comment and close' button

**Comment by aikidev** [comment]
> 
> 
> fixed

how you solved it ?

**Comment by illfated** [comment]
Most likely a user configuration problem (i.e. difference between content in bnetserver.conf versus worldserver.conf - default setting is that bnetserver.conf doesn't load any SQL files (`Updates.EnableDatabases = 0`), whereas worldserver.conf does (`Updates.EnableDatabases = 15`) - I doubt that the OP remembers his changes 3 years ago). Anyway, it is a user configuration problem and not a TrinityCore source code issue. Use the TC Forum help pages (or the IRC channel #trinity on irc.rizon.net if you need faster replies) for configuration problems like this.

**Comment by PREngineer** [comment]
> fixed

What did you change in your DB configuration?
