### ISSUE TITLE
Worldserver crash,  player_levelstats need update

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#13876]
Image: http://i61.tinypic.com/ouyv7s.jpg

By adding this commit sql: https://github.com/TrinityCore/TrinityCore/commit/f4047d5b31b4c0413476c726fa710c863e06e9eb the emulator fails, the error is in player_levelstats need updating. 

Db error: http://pastebin.com/bQudLPph

i have fixed this crash, please check out 

http://cloud.tecnolatin.com/public.php?service=files&t=af4a8805e5a993150ec49cb204b0c4eb

**Comment by xerkoss** [comment]
Where did you get those values?

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13842
https://github.com/TrinityCore/TrinityCore/issues/13818

**Comment by tctwod** [comment]
msoky dat commits are added on official branch?

**Comment by msoky** [comment]
not yet

**Comment by tctwod** [comment]
but works or need update for add on trinity branch

**Comment by tctwod** [comment]
thanks vincent

**Comment by DDuarte** [comment]
Dupe of #13823
