### ISSUE TITLE
Connection problem after update (Draenor)

### ISSUE THREAD

**Issue by Rumpelstilts** [TrinityCore/TrinityCore#13874]
After core update 10.01.2015  i cant enter the game because the  loading stops at 90% of loading screen / http://prntscr.com/5qon3x

**Comment by Sergey996** [comment]
port 8086 open? (InstanceServerPort)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
