### ISSUE TITLE
[3.3.5] AFK Message Spam

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13877]
If you are in a duel or somewhere where you can't log out, if you go AFK and left wow in background, after like 10 minutes (I don´t know the exact time) you get a message saying "You have been inactive for some time and will be logged out of the game. If you wish to remain logged in, hit the cancel button." and a notification that says "You can't logout now". 
This repeats constantly (maybe infinite until you open your wow?), and I think it's because the server is trying to kick you but it can't because you can't logout cause you are in a duel.

With many players, they can abuse this and maybe it's bad for the perfomance.

I coulnd't catch the "You can't logout now" notification in the screenshot but anyways this fits perfectly the issue:

![](http://puu.sh/ekAdJ/e77503d151.jpg)

Rev: https://github.com/TrinityCore/TrinityCore/commit/db849e7fccd1545435dacbc94f5e42142c8b6ced

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by msoky** [comment]
core? database?

**Comment by jackpoz** [comment]
what's the supposed behavior ?

**Comment by Rushor** [comment]
http://us.battle.net/wow/en/forum/topic/1207760865
blike :D

**Comment by Raydor** [comment]
@jackpoz @Rushor Wow I didn't know this was bugged in blizzard too O.o, the supposed behavior maybe is that the server kick you for being afk instead of spam you a message that does nothing every 0.03 sec (with lot of people, it might cause performance problems).

If you are AFK but you can logout, the server automatically kicks you for being AFK a long time, but if you can't logout (aka being in a duel), it doesn't kick you.

Yeah, is blizzlike but maybe we want it fixed just in case.

**Comment by Shauren** [comment]
Working as "intended" - blizzlike

**Comment by msoky** [comment]
:D its not bug, its feature :D
