### ISSUE TITLE
Spell infest ( lich king ) not work

### ISSUE THREAD

**Issue by Xxxhackerxxx** [TrinityCore/TrinityCore#13887]
hi all my friends
i think after add stack rules by Trisjdc spell infest does not work true
this spell after each hit must get stack
i think code for this spell true 

		void OnPeriodic(AuraEffect const* /*aurEff*/)
		{
			if (GetUnitOwner()->HealthAbovePct(90))
			{
				PreventDefaultAction();
				Remove(AURA_REMOVE_BY_ENEMY_SPELL);
			}
		}

		void OnUpdate(AuraEffect* aurEff)
		{
			// multiply, starting from 2nd tick
			if (aurEff->GetTickNumber() == 1)
				return;
			aurEff->SetAmount(int32(aurEff->GetAmount() * 1.15f));
		}

		void Register() override
		{
			OnEffectPeriodic += AuraEffectPeriodicFn(spell_the_lich_king_infest_AuraScript::OnPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
			OnEffectUpdatePeriodic += AuraEffectUpdatePeriodicFn(spell_the_lich_king_infest_AuraScript::OnUpdate, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
		} 

but not worked my rev : 1ed339547b575b87832c89194b426824bb16831e

Thank you for your efforts.

**Comment by Aokromes** [comment]
1st law, update your core before report bugs.

**Comment by Shauren** [comment]
Infest never had stacks, aren't you confusing it with Necrotic Plague?

**Comment by Xxxhackerxxx** [comment]
https://github.com/Shauren you say true its amount
but after increase amount damage does not increase

**Comment by Unholychick** [comment]
are you sure that the script is assigned in spell_script_names table?

**Comment by Xxxhackerxxx** [comment]
yes
when i get .list aura this effect amount increase but damage does not increased
Maybe my problem is from dbc ?

**Comment by Shauren** [comment]
Broken by d4bbc26261d7ce1e01292470f77390ab3c2f5e98
