### ISSUE TITLE
[3.3.5]Core/Instance The Lurker below Cannot activate

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#13883]
from [boss_lurker_below.cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp)

http://www.wowhead.com/npc=21217 
spell http://wotlk.openwow.com/spell=54587 
achievement http://www.wowhead.com/achievement=144 
Fishing The Lurker below spawn And achievement But then BOSS disappeared
##

**Comment by Kittnz** [comment]
@w5860363 Is this still the case on current build?

**Comment by Nyeriah** [comment]
To me he's never disappeared but he'd always be found at bottom of his pool.

**Comment by Kittnz** [comment]
And he can be activated with fishing?

**Comment by Nyeriah** [comment]
Vmaps suck in that cave so last time I checked yes it could but on very specific spots

**Comment by w5860363** [comment]
@Kittnz Fishing can be activated

**Comment by dr-j** [comment]
Its still the case as of today ie can be fished, gives ach but does not attack and just disappears

**Comment by Rushor** [comment]
changing the inhabittype to 4 will make it appear near the player instead of dropping down to the buttom

**Comment by Rushor** [comment]
this prevents him from faling to teh ground

```sql
UPDATE `creature_template` SET `InhabitType`=4 WHERE  `entry`=21217;
```

but it still disappears

**Comment by w5860363** [comment]
BOSS will automatically disappear after a few seconds. I think it is a XYZ problem

**Comment by mayaren888** [comment]
confirm

**Comment by Rushor** [comment]
yep upon aggro he instantly despawns once someone was in the water

**Comment by Rushor** [comment]
this will fix him

```
UPDATE `creature_template_movement` SET `Flight`='1' WHERE  `CreatureId`=21217;
```

**Comment by CraftedRO** [comment]
@w5860363 have you tried Rushor movement fix ?

**Comment by w5860363** [comment]
@CraftedRO Yes, this was valid in the then current version of TDB，But that was in 2016.

**Comment by CraftedRO** [comment]
well updated version is the one with flight , il try it right now

**Comment by CraftedRO** [comment]
6e07acbbdeb5 atm it does keep resetting:

https://user-images.githubusercontent.com/24683355/140284622-c7eaf8f3-b0df-4c5b-9167-8f19ad7c8517.mp4

But indeed https://github.com/TrinityCore/TrinityCore/issues/13883#issuecomment-854499193 does fix it :


https://user-images.githubusercontent.com/24683355/140284710-9fefe4c6-5441-41cf-9870-d7b580052685.mp4

I suggest so we can commit that.

**Comment by w5860363** [comment]
@CraftedRO @CraftedRO 
update code It is possible to solve the problem without changing the TDB, and this data comes from the old MANGOS SD2, but I later put the matter

float AddPos[9][3] =
{
    // MOVE_AMBUSHER_1 X, Y, Z
    {2.8553810f, -459.823914f, -19.182686f},
    {12.458420f, -466.042267f, -19.182686f},
    {51.366653f, -460.836060f, -19.182686f},
    {62.597980f, -457.433044f, -19.182686f},
    {77.607452f, -384.302765f, -19.182686f},
    {63.897900f, -378.984924f, -19.182686f},
    {34.447250f, -387.333618f, -19.182686f},
    {14.388216f, -423.468018f, -19.625271f},
    {42.471519f, -445.115295f, -19.769423f}
};

**Comment by CraftedRO** [comment]
I don't think it will solve the (evade) problem.
You can spawn it most likely on the bridge but it will still evade because of creature_template_movement but this is only my guess.

**Comment by CraftedRO** [comment]
And it seems the boss will still not be able to leave water even if the fix it does allow to fly.
So it feels blizzlike idk.

![WoWScrnShot_110421_113409](https://user-images.githubusercontent.com/24683355/140291043-01f1ff87-3e8a-4387-b988-02d3a2976d48.jpg)

**Comment by w5860363** [comment]
@Rushor Can you draw a conclusion on this question

**Comment by offl** [comment]
Try swim=0, flight=1, rooted=1
Those are its default original values
If swim=0 breaks something, change it back to 1

**Comment by CraftedRO** [comment]
![movement](https://user-images.githubusercontent.com/24683355/140324166-ec071fe7-c3d0-4c91-979c-68781c014e82.png)

Seems fine , the trick is flight.

https://user-images.githubusercontent.com/24683355/140324201-c555e9d5-9993-48c1-8fb9-4f03c994d4a7.mp4

**Comment by w5860363** [comment]
@offl  21217 not found creature_movement_override(branch 3.3.5)
and template sql MovementType  =0(TDB not changed)

**Comment by CraftedRO** [comment]
lol not override dude , that's mangos if im not wrong :))

**Comment by CraftedRO** [comment]
however if I .die myself (leaving combat) it does despawn but I guess this is the correct behave , and need to be hooked again.

**Comment by w5860363** [comment]
@CraftedRO But I'm talking about Trinity tdb3.3.35
spawnid 93838 bug creature_movement_override not data

**Comment by CraftedRO** [comment]
we are talking about creature_TEMPLATE_movement not creature_movement_override

**Comment by w5860363** [comment]
@offl branch 3.3.5 tdb default original value
@CraftedRO 
![1](https://user-images.githubusercontent.com/1938163/140328953-ca0e9022-40b7-42c8-ae55-29a86192cfaf.png)

If it is as you say, then this data is wrong [TDB vension](https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.21101)
![2](https://user-images.githubusercontent.com/1938163/140330818-24623ba6-23c4-462d-8d20-ed535e2a4da5.png)

**Comment by CraftedRO** [comment]
yeap , actual data is wrong and will be changed with something like :
```sql
UPDATE `creature_template_movement` SET `Swim` = 0, `Flight` = 1, `Rooted` = 1 WHERE `CreatureId` = 21217;
```

**Comment by CraftedRO** [comment]
off topic now , did u really open the whole 3.3.5 database in notepad++ :D ?

**Comment by w5860363** [comment]
@CraftedRO Yes, I opened the sql in notepad++ and I thought I had a problem with update.sql, like the navicat error before, but the raw data is what it is.

So, we can close this issue now?

**Comment by CraftedRO** [comment]
well we can't because it hasn't yet commited
