### ISSUE TITLE
DB/Waypoint: Update several npc's move_type for running npc's

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#13888]
```SQL
UPDATE `waypoint_data` SET `move_type`=1 WHERE  `id` IN (579650,1112180,992280,992270,992300);
```

credits: Aokromes

related to https://github.com/TrinityCore/TrinityCore/commit/747e72fc1c56384ccda5ea6972ece0c06f9fc832 & https://github.com/TrinityCore/TrinityCore/commit/b7bacea940514fd3e03503ff433930733e99ebf5

core: 97d415d1b2a429557f667f9c30e8577ab89e6434

**Comment by Rushor** [comment]
I see that these entries are already in the DB, could it be upldated to something like:

```sql
UPDATE `waypoint_data` SET `move_type`=1 WHERE  `id`=579650;
```

:)

**Comment by Kittnz** [comment]
I have to redo my database.. everytime i need a new guid it's already in use..

**Comment by Kittnz** [comment]
Updated
