### ISSUE TITLE
[3.3.5] Unable to locate Mage "Shatter" talent (Frost Tree), not adding crit properly

### ISSUE THREAD

**Issue by Vaserius** [TrinityCore/TrinityCore#13885]
f1b163793d14+
11 06 2014

Tested a few hundred spell casts with different people on frozen targets both PvP targets and PvE targets with and without resilience. Shatter doesn't seem to be adding any crit chance at all. Does anybody have any idea what could be causing this? 
 
Upon further investigation there doesn't seem to be any reference to any ranks of shatter anywhere I can see in either the Core or the Source. How is this talent handled?

**Comment by MrSmite** [comment]
It's probably handled by the aura system so there won't be any direct reference to the spell in the core.

**Comment by Vaserius** [comment]
Any idea where? All the other 'Auras' are handled by the spells, such as procs (Brain Freeze), Arcane Potency, etc.

**Comment by Aokromes** [comment]
To start, before report a bug update your core.

**Comment by Vaserius** [comment]
Sorry Aokromes; the problem is I see the same issue with the current Trinity; I don't see where Shatter is handled other than as a talentUI object to put points into.

**Comment by Frytiks** [comment]
This is bugged after vicent-michal commit. Use that http://pastebin.com/iEbZwPKn
