### ISSUE TITLE
[6.x] Error While Compiling Branch 6x

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#13886]
OS: Ubuntu 14.04
and im installed all required packages.
i got the following error in 36%:
>Linking CXX executable bnetserver
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libmariadbclient_r.a(client_plugin.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/bnetserver/bnetserver] Error 1
make[1]: *** [src/server/bnetserver/CMakeFiles/bnetserver.dir/all] Error 2
make: *** [all] Error 2

What is going wrong ?

**Comment by Aokromes** [comment]
Try to re-run cmake.

**Comment by tje3d** [comment]
Just removed the build folder and cmake it again, but... same error :(
>[ 38%] Building CXX object src/server/bnetserver/CMakeFiles/bnetserver.dir/PrecompiledHeaders/bnetPCH.cpp.o
Linking CXX executable bnetserver
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libmariadbclient_r.a(client_plugin.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/bnetserver/bnetserver] Error 1
make[1]: *** [src/server/bnetserver/CMakeFiles/bnetserver.dir/all] Error 2
make: *** [all] Error 2

**Comment by DDuarte** [comment]
Try using stock mysql instead of mariadb

**Comment by tje3d** [comment]
Hmm, i guess you right, but when i want to install libmysql++-dev, its install mariadb as default instead of mysql:
> tje3d@Moein-PC:~/Desktop/trinity/TrinityCore$ sudo apt-get install libmysql++-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libmariadbclient-dev libmariadbclient18 mariadb-common
Suggested packages:
  libmysql++-doc
The following NEW packages will be installed:
  libmariadbclient-dev libmariadbclient18 libmysql++-dev mariadb-common
0 upgraded, 4 newly installed, 0 to remove and 42 not upgraded.
Need to get 0 B/2,157 kB of archives.
After this operation, 13.2 MB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by funjoker** [comment]
use the mysql described in the TC HowTo

**Comment by tje3d** [comment]
The problem was solved. thanks.

This is what i did:
1- Remove libmysql++-dev
2- Remove all mariadb packages
3- Install libmysqlclient-dev from: http://packages.ubuntu.com/trusty/libmysqlclient-dev
4- Install libmysql++-dev from: http://packages.ubuntu.com/trusty/devel/libmysql++-dev

:+1:

**Comment by DDuarte** [comment]
@tje3d: You would be very welcome if you could write a small Troubleshooting Article in our wiki (http://collab.kpsn.org/display/tc/Troubleshooting+articles) with the problem (your first post) and the solution (with the steps that you just wrote). Thanks!
