### ISSUE TITLE
Armor Calculation - Huge Bug

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#13880]
Today i provide test with armor from items.

core rev: https://github.com/TrinityCore/TrinityCore/commit/9d56c9a1049fb15394831279bfb68e7acb9c28cd

TDB 11.57

I created a paladin.
Base Armor with level 80 - 180 armor. 
I added item wotlk.openwow.com/item=53125. It increase armor - 1858 Armor. 
On paladin i got 2038 armor. It's okay. 
Then i learn talent http://wotlk.openwow.com/spell=20143. 
It should add 2% bonus armor from items.

From base armor with item 2038 - 1% = 20.38. It should add 2% 2x 20.38 = 40.76. I will should have 2078.76 

But i have only 2075 armor. 

On rank 2 it should add 4% - 81.52 + 2038 = 2119.52 
But i have only 2112.

http://prntscr.com/5quv32

**Comment by DDuarte** [comment]
2078.76 vs 2075
2119.52  vs 2112

That's not 'huge', please edit the misleading title. Thanks.

**Comment by Frytiks** [comment]
You really this it's not huge ? With more items it's more different. On server i have player, he lose around 1000 armor.

**Comment by Frytiks** [comment]
Rank 5 2241 vs 2223

**Comment by Exodius** [comment]
I am not defending DDuarte but, difference in provided numbers is not "huge". In first case, difference is 3.76 while in second 7.52. Looking directly at numbers that you provided, the difference is not huge.

Now, if you had provided numbers related to fully geared character and the number goes up, THAT can be considered as Huge.
So, you should have provided the numbers that lead to the 1000 armor loss for this to be really seen as Huge bug.

**Comment by Frytiks** [comment]
Okay look there. We have item on druid. http://wotlk.openwow.com/item=50466

Basicly i have 1801 armor

It should add 737 Armor 737 armoru, 1% = 7,37

On druid get talents 
http://wotlk.openwow.com/spell=9634 - 370% bonus armor
http://wotlk.openwow.com/spell=16931 - 10% bonus armor
http://wotlk.openwow.com/spell=33856 - 33% talent

=  413% armoru from cloth a leather items

737/100*413 = 3043,81 armor i must get.

But ingame 3043 - 1801 = 1242 is armor lower than it should add.

http://prntscr.com/5qx5vh
http://prntscr.com/5qx61s

Then just dont say is priority low bug. If on full geared druid u get 1242 armor less.

**Comment by Exodius** [comment]
Now that's the way to properly explain things. Now you can say that it's a huge problem :)

**Comment by Aokromes** [comment]
That's not the way bear armor is calculated.

**Comment by Frytiks** [comment]
@Aokromes maybe 2nd calc not, but first yes. There you can see it's really bugged.

**Comment by digz6666** [comment]
Why include base armor in calculation? The talent says it increase armor 2% from items only.
So 180 + 1858*1.02 = 2075

**Comment by Frytiks** [comment]
Than it can be different if you have armor with green ?

**Comment by ariel-** [comment]
Yes, green (bonus) armor is not supposed to be included in calculation, so the calc should be:

(BaseArmor * Mult) + BonusArmor
Items with bonus armor have base armor, however not visible ingame, see item_template.
