### ISSUE TITLE
[6.x] Some required *.dbc files (6 from 145) not found or not compatible

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13884]
after compiling it now says my dbc files are not compatible

Some required *.dbc files (6 from 145) not found or not compatible:
./dbc/gtNpcTotalHp.dbc
./dbc/gtNpcTotalHpExp1.dbc
./dbc/gtNpcTotalHpExp2.dbc
./dbc/gtNpcTotalHpExp3.dbc
./dbc/gtNpcTotalHpExp4.dbc
./dbc/gtNpcTotalHpExp5.dbc

**Comment by Aokromes** [comment]
read the comment of previous commit.

**Comment by Vincent-Michael** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4d033eaa896db856878b4a39ff0f5082960b201b#commitcomment-9231547
