### ISSUE TITLE
Map doesn't recognize the locales

### ISSUE THREAD

**Issue by Dokman** [TrinityCore/TrinityCore#13889]
![image](https://cloud.githubusercontent.com/assets/2290904/5697486/730534fe-99f2-11e4-939f-2204690cf3ac.png)

**Comment by Dokman** [comment]
is installed with esES

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by DDuarte** [comment]
Use #13763
