### ISSUE TITLE
[3.3.5] Suggestion (disable add spell) command

### ISSUE THREAD

**Issue by Asandru** [TrinityCore/TrinityCore#13881]
After adding a spell to disabled you must reload database manually.

I  suggest updating within the command (disable add spell).

Branch: 3.3.5
rev: db849e7fccd1545435dacbc94f5e42142c8b6ced
TDB: 335.57

**Comment by ariel-** [comment]
If you wish to remove more than one spell you would be loading unnecesarily the DB. Better to disable as much as you need then .reload disables

**Comment by Asandru** [comment]
@ariel- gotta agree with that, alright just was a suggestion :)
