### ISSUE TITLE
smsg_questgiver_list disabled 

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#13897]
Need enable this for quest system 

when try to complete the quest have this error message

http://i61.tinypic.com/2wlsmcm.png

**Comment by Gooyeth** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Naxxmare** [comment]
https://github.com/TrinityCore/TrinityCore/commit/053d5f24eecd5785b09283d33cac6c4a9754c93a
TDB 6.00 updated
Try to update opcodes, but my client crashed with 132 error...
SMSG_QUESTGIVER_LIST
CMSG_BUY_ITEM
SMSG_POWER_UPDATE
are important in game play, waiting for fix :(

**Comment by Aokromes** [comment]
#14216
