### ISSUE TITLE
Character_action need update

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#13896]
Issue: http://i62.tinypic.com/15o7brr.png

when I try to create a character simply creates nothing and have to repeat several times until it manages to create the character.

character_action think needs to be updated.

**Comment by Gooyeth** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by timsar2** [comment]
It's fixed.
just get new core and DB
Core rev. f9088da+
TDB :6.00 updated to 2015_01_12_00_world

**Comment by tctwod** [comment]
not fixed i have all time the latest revisions

**Comment by Shandu** [comment]
Can't confirm, working well with the newest Rev. and a updated DB.
