### ISSUE TITLE
[6.x] 0xc000007b

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13895]
http://puu.sh/er9iZ/3882a4ed10.png

complied in 64x

**Comment by DDuarte** [comment]
Do not mix 32 bit dlls with 64 bit ones.

**Comment by dejonxavier** [comment]
does anyone have 64x libs?

**Comment by DDuarte** [comment]
You can download them all. The links are at the wiki.

**Comment by dejonxavier** [comment]
i have downloaded every thing OpenSSL Microsoft c++ ect i still get this error

**Comment by DDuarte** [comment]
Don't forget OpenSSL (2 dlls) and ZMQ.

**Comment by dejonxavier** [comment]
done and done still got the error

does the libmysql.dll has to be 64x?

**Comment by dejonxavier** [comment]
i have mysql_libs and none of them are working 32 and or 64

**Comment by DDuarte** [comment]
See if http://collab.kpsn.org/pages/viewpage.action?pageId=12714399 helps.

**Comment by dejonxavier** [comment]
http://puu.sh/erpzp/ca7bbf9727.png

could i try someone''s 64 bit libs

**Comment by dejonxavier** [comment]
http://puu.sh/ervnz/c69d2dfaff.png
