### ISSUE TITLE
[6.x] 16 Errors Compiling Bnetserver

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13899]
Error	41	error LNK2001: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z)	C:\TrinityCore-6.x\build\src\server\bnetserver\shared.lib(Util.obj)	bnetserver

ive heard that this has to do with BOOST; whats the issue i just tried compiling on windows 64x i have boost installed 64x BOOST_ROOT 

http://puu.sh/es1nT/055cb7052a.png

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by dejonxavier** [comment]
damn bro help me out

**Comment by msoky** [comment]
uninstall all and do it again http://collab.kpsn.org/display/tc/Requirements
somewhere you are mistaken
