### ISSUE TITLE
[6.x]Problems creating a new character

### ISSUE THREAD

**Issue by Dokman** [TrinityCore/TrinityCore#13890]
![image](https://cloud.githubusercontent.com/assets/2290904/5698013/9d1f10ec-9a02-11e4-85e6-b8fd1b716f43.png)

**Comment by Dokman** [comment]
for now the same problem

**Comment by Aokromes** [comment]
No revision at all, read: https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Dokman** [comment]
sorry revision: https://github.com/TrinityCore/TrinityCore/commit/590693eb91261ad1758b80f614cb0375a97caae2

**Comment by msoky** [comment]
after this? https://github.com/TrinityCore/TrinityCore/commit/3519f14b237bc155891485e98b21e80a72ace6eb

**Comment by Dokman** [comment]
after the last it works correctly
