### ISSUE TITLE
player can't release to Graveyard .

### ISSUE THREAD

**Issue by timsar2** [TrinityCore/TrinityCore#13900]
after a payer die,release spirit button to graveyard not work .
but if you wait a few minutes it'll happen and your spirit will be move to graveyard.

Core rev. f9088da715d5+
TDB :6.00 updated to 2015_01_12_00_world

**Comment by AriDEV** [comment]
CEMETARY packetio is not done.

**Comment by Rushor** [comment]
http://www.wowwiki.com/Ironman_leveling try this :D

**Comment by AriDEV** [comment]
should be fixed in https://github.com/TrinityCore/TrinityCore/commit/c2722959a97648f3331290c55d014f314fa0e1bf

**Comment by timsar2** [comment]
Now spirit Healer didn't response
and graveyard is too far.
