### ISSUE TITLE
[6.x]Error when building the core

### ISSUE THREAD

**Issue by Rumpelstilts** [TrinityCore/TrinityCore#13902]
Hi everyone. I have some problem after acepting the commit https://github.com/TrinityCore/TrinityCore/commit/aff40d7#diff-3a912d08e1fdcfa7a92a0bdd3a5883c6R38  When i compile the core i got this http://pastebin.com/RYJj3DMc , i tried to fix it by myself , but it was fail, please can you help me with an advise ?

**Comment by Gooyeth** [comment]
The error is here:
https://github.com/TrinityCore/TrinityCore/commit/aff40d741ebe03d0ddf0cc82486d14c8961fb40a#diff-3a912d08e1fdcfa7a92a0bdd3a5883c6R38

**Comment by Rumpelstilts** [comment]
Yes it's here, is there any fix for this mistake

**Comment by DDuarte** [comment]
Mistake? The only mistake there is in the boost sources.

**Comment by Rumpelstilts** [comment]
I tried to reinstall Boost , from the beggining but nothing works . Also i tried to rebuild the core but this was unsuccessful

**Comment by DDuarte** [comment]
This is not an issue with your setup, @Rumpelstilts. You'll need to wait for a fix.

**Comment by Rumpelstilts** [comment]
Oh thanks , i will wait for it .  By the way , how can i contact you ?

**Comment by DDuarte** [comment]
Uhhh.... I have an email in my Github profile.

**Comment by DDuarte** [comment]
Fixed in 062efd94ddb5cec2369904c011376976f89a865d
