### ISSUE TITLE
Add MapExtrator  dbc file

### ISSUE THREAD

**Issue by brecky** [TrinityCore/TrinityCore#13904]
src\tools\map_extractor\loadlib\DBFilesClientList.h  

  "DBFilesClient\\gtNpcTotalHp.dbc",     //19445
    "DBFilesClient\\gtNpcTotalHpExp1.dbc", //19445
    "DBFilesClient\\gtNpcTotalHpExp2.dbc", //19445
    "DBFilesClient\\gtNpcTotalHpExp3.dbc", //19445
    "DBFilesClient\\gtNpcTotalHpExp4.dbc", //19445
    "DBFilesClient\\gtNpcTotalHpExp5.dbc", //19445

**Comment by DDuarte** [comment]
http://collab.kpsn.org/pages/viewpage.action?pageId=12714394
