### ISSUE TITLE
[6.0.3] Mac .app patched by connection_patcher only works first time [$5]

### ISSUE THREAD

**Issue by Walkum** [TrinityCore/TrinityCore#13903]
Rev. https://github.com/TrinityCore/TrinityCore/commit/e23d95c4c6dfd3cbeadc807bc402b543b7b7b6a4

How to reproduce:

1. Patch World of Warcraft.app as normal time (Login with a retail account, change Config.WTF, patch, etc).
2. Try login on your own server. Works.
3. The next time if you try login, get error 114.
4. You need to delete Cache folder of /Users/Shared/Blizzard/, and World of Warcraft Patched.app
5. Go again to point 1 and re-do the next points.

I opened again this issue because I was afk last month and my last issue was closed (https://github.com/TrinityCore/TrinityCore/issues/13602), this issue DOESN'T HAPPENS ON WINDOWS, ONLY MAC.

**Comment by bloerwald** [comment]
I wouldn't have a direct fix. You may try ```chown```ing them to a different user so WoW can no longer modify them. ```chown root:root ….auth``` for example.

**Comment by Walkum** [comment]
@bloerwald  Don't works.

**Comment by bloerwald** [comment]
So you ```chown```ed it to root and it still gets deleted?

**Comment by Walkum** [comment]
Yes, but is not deleted, I see that are new folders added into it / some modified, and maybe these is the cause because I need delete all and re-do again.

**Comment by bloerwald** [comment]
So, content of cache directory does not change when logging in and still a second login is not possible?

**Comment by Walkum** [comment]
I think that change only in that 2 o 3 new folders appear, but not more. Second login not possible.

**Comment by bloerwald** [comment]
I'm sorry, but I don't quite follow. Please

* clear cache
* start client, login to live (not via launcher), close client
* run patcher
* chown cache recursively to root, remove ```w``` for every user.
* ensure that owner and permissions are correct with ```find . -type f -ls```, save list to file (```find . -type f -ls > before```
* run client, login to emu
* ensure that owner and permissions are correct with ```find . -type f -ls```, save list to file (```find . -type f -ls > before```
* run client, login to emu
* ensure that owner and permissions are correct with ```find . -type f -ls```, save list to file (```find . -type f -ls > before```

Thanks.

**Comment by Walkum** [comment]
Works at last, is not a chown issue, is chmod.

I try put this: chmod -R 755 Cache/

And now works. Last question, the patcher would be put automatically these permission to the Cache folder? I will left the issue opened for you can answer me.

Thanks @bloerwald :)

**Comment by bloerwald** [comment]
The patcher already removes ```w``` for every group. The ```chown``` did a thing: The client is the owner of the file, thus can delete it no matter if it has ```w``` or not. After ```chown```ing it to root, that's no longer possible.

**Comment by JanSimek** [comment]
I have the same issue on OS X with the latest revision 291d23e5f51b42479f0aacfb8149bc47db8cabf4. Whoever fixes it can have a beer on me: [![Bountysource](https://www.bountysource.com/badge/issue?issue_id=7711459)](https://www.bountysource.com/issues/7711459-6-0-3-mac-app-patched-by-connection_patcher-only-works-first-time-5?utm_source=7711459&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by ShinDarth** [comment]
I can confirm this.

Meanwhile, all Mac OS X users can use win32 binaries and wine to run the game:

1) if you haven't Home Brew installed, install it: http://brew.sh/

2) use homebrew to install latest wine:
```
brew install wine --devel
```
3) download and unzip this archive into your World of Warcraft client directory: http://usefulness.altervista.org/share/win32wow.zip

4) open a terminal, go in your World of Warcraft client directory and type:
```
wine connection_patcher.exe
```

it will generate the Wow_Patched.exe that you can use to run the client using:
```
wine Wow_Patched.exe
```

**Comment by bloerwald** [comment]
I'm deeply sorry, that this is still an issue. Please do not resort to using a windows version, though!

As a "proper" hack fix, please do

* `cd /Users/Shared/Blizzard/Battle.net/Cache`
* `rm -rf *`
* do the connection patcher thing
* `sudo chown -R root *`
* `sudo chmod -R -w *`

Last time I tried that, it worked. If it still doesn't, I'm even more sorry.

Sorry.

**Comment by Gacko** [comment]
Not valid anymore. At least I just patched my binaries and it still works after several client restarts.

**Comment by Gacko** [comment]
Oh, and before I forget:
```
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42
```
```
Client version: 6.2.3
```

**Comment by Gacko** [comment]
I just talked to @Carbenium and remembered some minor changes I did to my client on installation:

```
cd /Applications
sudo chown -R <user>:admin "World of Warcraft" "Battle.net.app"
chmod og-w "World of Warcraft" "Battle.net.app"
```

**Comment by ikir83** [comment]
So it is still an issue with 6.2.4? I'm getting crazy trying to run 6.x, my clients can't connect.

**Comment by Shauren** [comment]
No, this is not an issue anymore, files in /Users/Shared/Blizzard/ (login modules) are not used anymore.
