### ISSUE TITLE
Lord Marrowgar Coldflame

### ISSUE THREAD

**Issue by Skyepup** [TrinityCore/TrinityCore#13901]
When testing Lord Marrowgar the Coldflame goes on a slant then straight up?

http://i.gyazo.com/d26ee56cb8ff641b68f781244bb9c1f7.jpg

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/new

**Comment by Skyepup** [comment]
I answered my own question the coldflame npc just had the wrong inhabit type.
