### ISSUE TITLE
[6.x] Quests, NPC's and Graveyard (in spirit form)

### ISSUE THREAD

**Issue by sciasfreelancer** [TrinityCore/TrinityCore#13918]
Quests are not found.
When you login to the game you drop from the sky.
Incorrect spawn places and new character creation places.
NPC's don't stand where they should.
When clicking graveyard nothing happens( Fixed it on my own), after presing return to graveyard it return me to village instead.

**Comment by Aokromes** [comment]
Duplicate and no following posting rules.
