### ISSUE TITLE
[Quest] Respite for a Tormented Soul raid 25 (24880)

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#13912]
http://wotlk.openwow.com/search=Respite+for+a+Tormented+Soul
This quest has 10 and 25 mode. In 25 mode, the quest ender doesn't work.
In 10 mode the npc was changed at the end of this commit https://github.com/TrinityCore/TrinityCore/commit/272bcdb292f632ded7f3dfbbd45bd33d8ae926bb
In 25 mode it wasn't changed and it should be the same.
I have tested it and it works perfect now.
```mysql
UPDATE `creature_questender` SET `id` =38017 WHERE `quest` =24880;
```
8197da743cd5a9a2c4df73e53b9f9dc44cbec1d5

**Comment by DDuarte** [comment]
4179c35eb25a69c33f9236f61e67985f2ff26c13
