### ISSUE TITLE
[335] wpgps prints wrong coordinates

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#13914]
__Core:__ 42f1a0babfaacf64df31a934288979f8edfec940
__DB:__ N/A

__Bug:__

The XYZ coordinates printed by __wpgps__ do not match the DB

__Details:__

For creature with GUID 80263 (entry 1423), *wpgps* on *point 1* prints:

> -9128.101563, -88.742104, 77.376297

However the coordinates in the DB for that point are:

> -9135.58, -91.7557, 76.0991

Edit: It appears it is printing the GPS of the player, not the selected waypoint as the command suggests.

**Comment by Aokromes** [comment]
wpgps is waypoint gps, not gps witch will give current coords.

**Comment by MrSmite** [comment]
> wpgps is waypoint gps, not gps witch will give current coords.

Right, that's what my bug report is for. It is printing the GPS of the player, not the selected waypoint.

**Comment by MrSmite** [comment]
Are you saying the command "waypoint GPS" isn't for getting the GPS of the selected waypoint?

**Comment by Shauren** [comment]
Correct, that is not the purpose of that commad, it exists to output current player coordinates in SQL query format to help with waypoint development (notice how it is placed in cs_debug, not cs_wp)
