### ISSUE TITLE
Thieves' Tools

### ISSUE THREAD

**Issue by Rohlik** [TrinityCore/TrinityCore#13929]
Hi,
on TDB 335.54
item Thieves' Tools - http://wotlk.openwow.com/item=5060#sold-by isn´t in vendors.

**Comment by Aokromes** [comment]
They where removed with WOTLK release.

**Comment by msoky** [comment]
This item will not be required anymore in WotLK.
From the first Beta patch notes:
Pick Lock and Disarm Trap no longer require Thieves' Tools.
----> removed in WOTLK

**Comment by msoky** [comment]
close?

**Comment by Rohlik** [comment]
Okey, my bad. Thanks ;-)
