### ISSUE TITLE
NPC interraction (banker, auction, blackmarket ect...)

### ISSUE THREAD

**Issue by ProjectcoreDevs** [TrinityCore/TrinityCore#13922]
Hi all, i think you have a problem with the interaction (or addons) for the npc banker, auction, blackmarket.
I have implemented the opcodes and structures for auctionner, blackmarket, and banker. I'm sure for the structure but the banker not show the window, the auction house show the auction is closed and blackmarket send the opcode and receive the smsg, but without interaction.

note: You want PR for this opcode update?

**Comment by DDuarte** [comment]
If you changed code, create a PR.
