### ISSUE TITLE
[ITEM][6x] can not use item and gameobject like Portal

### ISSUE THREAD

**Issue by timsar2** [TrinityCore/TrinityCore#13927]
Not happened After click on Portal,POTION and etc.
Core rev. 0425ab204733+
TDB :6.00 updated to 2015_01_16_00_world

item=58090 (earthen-potion) and other item not useable.

**Comment by Aokromes** [comment]
Don't report multibple bugs on a single ticket, as for portals: #14114

**Comment by timsar2** [comment]
#14114 was open 6 days ago
