### ISSUE TITLE
BuildPlayerLevelInfo does not have any data for Death Knights

### ISSUE THREAD

**Issue by Grimton1337** [TrinityCore/TrinityCore#13925]
void ObjectMgr::BuildPlayerLevelInfo(uint8 race, uint8 _class, uint8 level, PlayerLevelInfo* info) const
ObjectMgr 3820 line

Is this intended or we don't have any information on them yet? Or am I missing something else here?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
