### ISSUE TITLE
[6.x] Segmentation fault (core dumped) - worldserver

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#13934]
I recieve the following error when i try to run worldserver:

> Loading Player Create Level Stats Data...
Race 1 Class 1 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 1 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 1 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 1 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 1 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 1 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 1 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 1 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 1 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 1 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 1 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 1 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 1 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 1 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 1 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 2 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 2 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 2 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 2 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 2 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 2 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 2 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 2 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 2 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 2 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 2 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 2 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 2 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 2 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 2 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 3 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 3 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 3 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 3 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 3 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 3 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 3 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 3 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 3 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 3 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 3 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 3 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 3 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 3 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 3 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 4 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 4 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 4 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 4 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 4 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 4 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 4 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 4 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 4 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 4 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 4 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 4 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 4 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 4 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 4 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 5 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 5 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 5 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 5 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 5 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 5 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 5 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 5 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 5 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 5 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 5 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 5 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 5 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 5 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 5 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 6 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 6 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 6 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 6 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 6 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 6 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 6 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 6 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 6 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 6 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 6 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 6 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 6 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 6 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 6 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 8 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 8 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 8 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 8 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 8 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 8 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 8 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 8 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 8 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 8 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 8 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 8 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 8 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 8 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 8 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 9 Level 86 does not have stats data. Using stats data of level 85.
Race 1 Class 9 Level 87 does not have stats data. Using stats data of level 86.
Race 1 Class 9 Level 88 does not have stats data. Using stats data of level 87.
Race 1 Class 9 Level 89 does not have stats data. Using stats data of level 88.
Race 1 Class 9 Level 90 does not have stats data. Using stats data of level 89.
Race 1 Class 9 Level 91 does not have stats data. Using stats data of level 90.
Race 1 Class 9 Level 92 does not have stats data. Using stats data of level 91.
Race 1 Class 9 Level 93 does not have stats data. Using stats data of level 92.
Race 1 Class 9 Level 94 does not have stats data. Using stats data of level 93.
Race 1 Class 9 Level 95 does not have stats data. Using stats data of level 94.
Race 1 Class 9 Level 96 does not have stats data. Using stats data of level 95.
Race 1 Class 9 Level 97 does not have stats data. Using stats data of level 96.
Race 1 Class 9 Level 98 does not have stats data. Using stats data of level 97.
Race 1 Class 9 Level 99 does not have stats data. Using stats data of level 98.
Race 1 Class 9 Level 100 does not have stats data. Using stats data of level 99.
Race 1 Class 10 Level 1 does not have stats data!
Segmentation fault (core dumped)

**Comment by Aokromes** [comment]
Update your core and database.

**Comment by emptyus** [comment]
You recieve your db and revision perhaps? :)
