### ISSUE TITLE
[3.3.5] Mind control on feared targets

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#13932]
Rev: https://github.com/TrinityCore/TrinityCore/commit/48fa7fa992c02d7c17c39c08cb78c6457d034f49

When you cast mind control on feared targets, you are supposed to control them until MC ends (MC prioritices movement over fear).

Right now, when you cast MC on a feared target, it gets interrupted automatically by the fear movement.

![](http://puu.sh/eHdIR/5e79003918.jpg)

![](http://puu.sh/eHdKp/1555621836.jpg)

**Comment by Raydor** [comment]
Any news? It's an important bug in PvP.

**Comment by Raydor** [comment]
I think the bug is in
> void Player::SetViewpoint(WorldObject* target, bool apply)

Because deleting 
 >if (!AddGuidValue(PLAYER_FARSIGHT, target->GetGUID()))
{
    TC_LOG_FATAL("entities.player", "Player::CreateViewpoint: Player %s cannot add new viewpoint!", GetName().c_str());
    return;
}

Makes the priest to doesn't control the enemy, but the spell doesn't get interrupted (which is what we want). Searching everything in HandleModPosses and SetCharmedBy, that was the only thing that didn't make the spell to be cancelled.

**Comment by lainimer** [comment]
Any news?confirm

**Comment by Raydor** [comment]
Still not fixed on https://github.com/TrinityCore/TrinityCore/commit/f5530c719b71309bd476aff528b0d3e1220ca49b

It's a critical PvP bug.

**Comment by Ofinka** [comment]
Cant confirm problem you described, can u make a video or more detailed bug reproduction?

**Comment by Raydor** [comment]
@Ofinka can't confirm? O.o
Just use mind control on an enemy just when the enemy is feared, polymorphed or some CC that makes the enemy move randomly.

**Comment by Ofinka** [comment]
Using 1a7a9619d87e95ecdc75fe012e0099a3f184b17b and i had tried various situations with fear or polymorph, but still the interrupt/cancel didnt occur.

**Comment by Raydor** [comment]
My bad, was a bug with AC2 (forgot to disable it when I was testing the bug).
