### ISSUE TITLE
[3.3.5a] High overlord Saurfang Floating

### ISSUE THREAD

**Issue by Skyepup** [TrinityCore/TrinityCore#13936]
When you start your fight with High Overlord Saurfang, and start attacking him he will float above your head.

I am running revision [db849e7](https://github.com/TrinityCore/TrinityCore/commit/f94cfc65771f53cd2b693779ecd00705cd66593a)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by ccrs** [comment]
confirm 9bd7b0e5714475d05d74c15bad500e0a59768edd LOL

**Comment by Killyana** [comment]
Is it possible to provide at least the npc id? I cannot find any attackable "High Overlord Saurfang".
rev. 0148832b322b
