### ISSUE TITLE
[6.x] No autheserver file and Miss some requried DBC files

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#13933]
After a good compile and extracting maps, vmaps... When i try to run the worldserver binary file, i got the following error:

> Some required *.dbc files (6 from 145) not found or not compatible:
/PATH/server/data/dbc/gtNpcTotalHp.dbc
/PATH/server/data/dbc/gtNpcTotalHpExp1.dbc
/PATH/server/data/dbc/gtNpcTotalHpExp2.dbc
/PATH/server/data/dbc/gtNpcTotalHpExp3.dbc
/PATH/server/data/dbc/gtNpcTotalHpExp4.dbc
/PATH/server/data/dbc/gtNpcTotalHpExp5.dbc

Also i cmaked with this command:
> cmake ../ -DPREFIX=/PATH/server -DTOOLS=1 -DSERVERS=1

But there is no file named authserver in bin folder!

Also i like to know if there is dbc, maps, mmaps and vmaps for 6x to Download.

**Comment by Aokromes** [comment]
6.x branch don't have authserver. for the files, read wiki.

**Comment by Vincent-Michael** [comment]
http://collab.kpsn.org/pages/viewpage.action?pageId=12714394
