### ISSUE TITLE
[Crash] FreezeDetectorHandler

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#13937]
Im reopening this as im having still this totally random crashes...

The original issue #13504

Some crashlogs:

http://www.trinitycore.org/f/pastebin/1yr6fbpur0f4k/
http://www.trinitycore.org/f/pastebin/xiz2ahnxveq3/

Ive solved the hash issue, so next time it crashes ill upload a new one
(ive just uploaded the relwithdebinfo version)

Today it crashed when i used ".tele naxxramas" from gm island.

Dont now if its related to the fact that my cpu is virtual, like once @Aokromes suggested on IRC
Dont now if its something i did wrong on .conf 
(like more pool threads or map threads or smthg like that... right now evrthg is on default)

Also, my core and db are CLEAN versions. Just wanted to point that out :)

hash: 9bd7b0e5714475d05d74c15bad500e0a59768edd

**Comment by ccrs** [comment]
Is there any "optimal" configuration for worldserver.conf?

**Comment by jackpoz** [comment]
you could increase the maxstucktime in the config and see if it's just a slow environment or if it's really stuck

**Comment by ccrs** [comment]
right now I have maxstucktime at 10, should I increase it to 30?
those are full crashlogs, I only edited those two lines.

**Comment by jackpoz** [comment]
it's supposed to display the callstack of each thread, not just the asserting one

**Comment by ccrs** [comment]
well, thats evrything i get at least on 4:11:2014

I uploaded the relwithdebinfo version two hours ago, its a matter of time to have a new crashlog :P

**Comment by ccrs** [comment]
bump http://www.trinitycore.org/f/pastebin/1i1gceuk6ysuk/

Server crashed again after several hours when I used tele to an area without any other player.
I had cpu usage monitored and it never went higher than 2%.
Also, had enough free ram as u can see in the crashlog.

**Comment by ccrs** [comment]
conf file:
http://www.trinitycore.org/f/pastebin/1232wjgrk8tpw/
http://www.trinitycore.org/f/pastebin/nneqr2kii5g6/
