### ISSUE TITLE
Cmake policy problems

### ISSUE THREAD

**Issue by avengerweb** [TrinityCore/TrinityCore#13942]
CLion IDE and cmake policy problems.
https://youtrack.jetbrains.com/issue/CPP-2049

using: https://github.com/TrinityCore/TrinityCore/commit/9bd7b0e5714475d05d74c15bad500e0a59768edd

**Comment by DDuarte** [comment]
http://www.cmake.org/cmake/help/v3.0/policy/CMP0005.html

**Comment by click** [comment]
Not going to fix something that isn't really broken - the IDE does something weird (actually, it's not even really supported).

**Comment by mat0thew** [comment]
@click needed configure

**Comment by avengerweb** [comment]
that problem fixed in clion 1.1+

**Comment by mat0thew** [comment]
@avengerweb srsly? i am ran project and clion dont scan this shit

**Comment by mat0thew** [comment]
@avengerweb first CMakeLists.txt

**Comment by avengerweb** [comment]
Which version you use?

**Comment by avengerweb** [comment]
http://postimg.org/delete/cperi4mja/ 
U can try to change here OLD -> NEW

**Comment by mat0thew** [comment]
@avengerweb  Ох, ну посмотрю позже. Весь проект сканирует?

**Comment by tkrokli** [comment]
@mat0thew & @avengerweb : Please use the Forums (https://community.trinitycore.org/)
unless what you talk about is in English and useful, shareable information about this issue.
