### ISSUE TITLE
WorldSocket

### ISSUE THREAD

**Issue by M0ra** [TrinityCore/TrinityCore#13943]
hi.
when I go into the game world , almost immediately an error http://pastebin.com/Ey0LpJNC

compiled kernel in debug mode , no errors
the latest revision DB 57.
expecting that the problem is in the client used the repair, everything is okay

here is what the console:
2015-01-20 15:01:54 WorldSocket::handle_input: Peer error closing connection errno = Connection reset by peer

sorry for my bad english

**Comment by Aokromes** [comment]
There is no such thing as "latest revision", also i can login without problems.

**Comment by M0ra** [comment]
9bd7b0e5714475d05d74c15bad500e0a59768edd rev
thinking and problem mmaps vmaps. drew them again , the exact same problem .

**Comment by F03SD** [comment]
in line 30
SET locale "ruRU"
SET realmList "logon.wowby.ru"

WE DO NOT CARE ABOUT YOUR PRIVATE PROJECT.

**Comment by digz6666** [comment]
Client used the repair tool? If he use repair tool it will patch the wow to the latest patch.
