### ISSUE TITLE
[3.3.5a][Battleground] SOTA, Siege weapons, Flags and last Relic

### ISSUE THREAD

**Issue by alein** [TrinityCore/TrinityCore#13945]
Hi.
In the last 2 updates of my server I noticed a few new and unpleasant bugs in SOTA.
Two months ago these problems were gone and the battle zone was more or less playable.

Now it isn't at all.

Here are my observations:
1. The siege weapons have more HP that should have.
2. The siege weapons should not done so high damage to players.
3. Guns over each wall should not be able to moved around.
4. Guns over each wall should not done so high damage to players.
5. The flags should be possible to be captured and with that action graveyards with them.
6. LOS should be removed after the one gate is destroyed. (for each one). For example - healer or caster can not cast if the player is form the other side of the wall, even if the gate is destroyed.
7. The Relic after the last gate is immune to whatever you try to do and the battle ends when the time is over.

Trinity Branch: 3.3.5
commit: 97d415d1b2a429557f667f9c30e8577ab89e6434
Database: TDB_full_335.57_2014_10_19 + trinity updates.
OS: Ubuntu Server 14.0.4 LTS

I would be extremely glad, to see this bugs in the past.
Thank you.
P.

**Comment by Pirricli** [comment]
related to #13091

**Comment by Mack36** [comment]
commit: https://github.com/TrinityCore/TrinityCore/commit/3747f99d4f76a149d215745780703b2623c59425 
Confirmed. 
Recently noticed same problem too. Flags are not active, so you can't even click on them (even if you're in gm mod), And the same is with the titan relic, It's not clickable. Destroying walls doesn't change anything. This happens every SOTA battleground, but not with all flags. one of them is clickable, and it works as intended.
Now it's clear that problem has appeared after some commit(s) were done a month or two ago.

**Comment by silvermcd123** [comment]
Confirmed

**Comment by Aokromes** [comment]
1,2,4 prof?
3, 5,6,7 duplicate, 
never post multiple issues on one ticket.

**Comment by silvermcd123** [comment]
at least link the duplicate!

**Comment by Rushor** [comment]
no searching already reported issues is much easier, git shows open and closed one seperated.
