### ISSUE TITLE
[3.3.5] Core/Entities: Sometimes unable to loot skinnable mobs

### ISSUE THREAD

**Issue by Whynar** [TrinityCore/TrinityCore#13940]
Hash: https://github.com/TrinityCore/TrinityCore/commit/9bd7b0e5714475d05d74c15bad500e0a59768edd

This is easily noticeable with creatures that can be skinned.
- Get Skinning
- Kill creatures
- Atleast one in every hundred will be both unlootable and impossible to skin (will say that the corpse has not been looted).

Point is, sometimes mobs drop loot that is not lootable. No sparkles around the corpse, but unable to skin them (which means that loot is actually there).

Also happens with creatures that always drop a certain item: even if the drop chance is 100%, sometimes one of the creatures will be unlootable.

Seems that every mob in game is affected by this.
##

**Comment by Mihapro** [comment]
If you were in a party, other members might have quest items in there

**Comment by Whynar** [comment]
Not in party - talking about normal gameplay, as in outside groups/raids/anything that might affect the behavior.

**Comment by unholy** [comment]
believe it or not (not saying its coded) but this happens on retail a lot, some mobs are lootable and or skinnable and sometimes their next of kin is not... seems to be a random thing. bears in particular on azuremyst come to mind as i am currently playing that area on a freebie acct and i noticed a lot of the bears are not lootable and skinnable and yet some of the same kind are... its random.

**Comment by Skyepup** [comment]
There is a chance a mob will drop loot.. Doesn't that mean there is a chance it wont?

**Comment by danlapps** [comment]
Is this a TC issue or a retail client issue ?  Seems like only one person had the problem

**Comment by Whynar** [comment]
Have been experiencing said issue on TC, but I have yet to find a way to reproduce it in a consistent way. It happens, but rarely and hard to notice/debug. Not sure what to think.

**Comment by Rushor** [comment]
> If you were in a party, other members might have quest items in there
someone knows if this issue is blizzlike?

**Comment by dr-j** [comment]
Can you give an example of a npc where this occurs please, I maybe wrong but wonder if conditional loot could be to blame,

Like you always get this error if you try and skin Icehowl after first encounter in toc, apparently this is because it drops loot for both factions but is conditional on faction, maybe wrong.

**Comment by Killyana** [comment]
http://wowwiki.wikia.com/wiki/Skinning

    All the items from a corpse must be looted before it can be skinned.
    Any skinnable mobs will say "Skinnable" in their tooltip after they are dead and completely looted.
    If you're trying to skin something that is lootable by another player, that player must take all loot from the corpse, or you won't be able to skin it.
    In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item. This usually happens when killing several mobs at once before looting and skinning them. There is no way to skin such a corpse other than to drop at least one of the quest items so you can then loot the item one more time. Due to game mechanics, random drops from mobs are almost always determined at the time of looting, rather at some previous time. And almost all looted items required for quests can be acquired beyond the quota for the quest. Rarely, this can happen with bosses who are supposed to drop a single quest item that respawn before their previous corpse has been looted, such as Combat 15 Princess.
    If you possess a Unique item somewhere in your inventory (bags/bank), and the mob has dropped that exact same item as lootable, you will be unable to loot it because you can only have one of any Unique item. As such, you will be unable to skin that mob.

So the npc must be flagged skinnable only when everything is looted.
