### ISSUE TITLE
[3.3.5a] Death Knight Pets

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#13948]
rev: https://github.com/TrinityCore/TrinityCore/tree/3.3.5

Problem:
After death knight pets die you can't summon them again, the spell is in cooldown allways.

**Comment by Aokromes** [comment]
duplicate.

**Comment by silvermcd123** [comment]
duplicate of WHAT?! -.-

**Comment by silvermcd123** [comment]
link me the duplicate!

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/13941 and others.
