### ISSUE TITLE
[6.x] AutoLearnSpells arent working anymore

### ISSUE THREAD

**Issue by Shandu** [TrinityCore/TrinityCore#13959]
I dont know what u guys changed, but AutoLearnSpells arent working anymore.

example:
- Created Nightelf Druid
- in-Game no Spells (Wrath...)

Core Revision Number: b8b30799174eea9ef706f26721a64660363ada6f

greetZ
- Shandu

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/be8311c80c2fd2acf8f5ab03ecb87643972679d8 related?

**Comment by Shandu** [comment]
Changed description, Revision Number is: CORE revision number :b8b30799174eea9ef706f26721a64660363ada6f

and yes I was looking for this commit I already saw it time ago, that should be the problem.

**Comment by Shauren** [comment]
The person who wrote that autolearning code was an idiot (looking at you skyfire devs)
It will be fixed but for now - deal with it.

**Comment by Shandu** [comment]
:100: % :) , anyway for everyone who wants AutoLearnSpells again should take a look on be8311c80c2fd2acf8f5ab03ecb87643972679d8 .

- Thanks

**Comment by Shauren** [comment]
ABSOLUTELY NOT. That code corrupts your characters (for example by giving rogue spells to shamans) - these spells are then permanently saved to database!

**Comment by Shandu** [comment]
because of:

-uint32 GetClassBySkillId(uint32 skillId);
-uint32 GetSkillIdByClass(uint32 classId);

 ?

**Comment by Shauren** [comment]
3f28fd304d833eadefff8d343ab45caf8d0575c2
