### ISSUE TITLE
Mage Mirror Image

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#13955]
Core : 7bf8c98746e6fa69eed1b4706765ae2acd3a6492
System : Linux Debian 64 !
Bugname : Mage Subspell Mirror Image & Mage Core Mainscript

The Mirror Image Casts only a Spell if i do a meele attack on my Target ! 

```c++
enum MageSpells
{
    SPELL_MAGE_BURNOUT                           = 29077,
    SPELL_MAGE_COLD_SNAP                         = 11958,
    SPELL_MAGE_FOCUS_MAGIC_PROC                  = 54648,
    SPELL_MAGE_FROST_WARDING_R1                  = 11189,
    SPELL_MAGE_FROST_WARDING_TRIGGERED           = 57776,
    SPELL_MAGE_INCANTERS_ABSORBTION_R1           = 44394,
    SPELL_MAGE_INCANTERS_ABSORBTION_TRIGGERED    = 44413,
    SPELL_MAGE_IGNITE                            = 12654,
    SPELL_MAGE_MASTER_OF_ELEMENTS_ENERGIZE       = 29077,
    SPELL_MAGE_SQUIRREL_FORM                     = 32813,
    SPELL_MAGE_GIRAFFE_FORM                      = 32816,
    SPELL_MAGE_SERPENT_FORM                      = 32817,
    SPELL_MAGE_DRAGONHAWK_FORM                   = 32818,
    //SPELL_MAGE_WORGEN_FORM                       = 32819, // WTF ... -.-^^
    SPELL_MAGE_SHEEP_FORM                        = 32820,
    SPELL_MAGE_GLYPH_OF_ETERNAL_WATER            = 70937,
    SPELL_MAGE_SUMMON_WATER_ELEMENTAL_PERMANENT  = 70908,
    SPELL_MAGE_SUMMON_WATER_ELEMENTAL_TEMPORARY  = 70907,
    SPELL_MAGE_GLYPH_OF_BLAST_WAVE               = 62126,
};
```

Spell Worgen is a new Year joke ?!

**Comment by DDuarte** [comment]
The 4.3.4 branch has been discontinued. If the bug exists in the 6.x re-open this ticket.

**Comment by Xunil1337** [comment]
What the Fuck... it is in Brance 3.3.5 and why not fix it ? OMG !

**Comment by DDuarte** [comment]
Calm down.

You did not explicitly wrote any branch and the commit you linked is from the 4.3.4 branch.

**Comment by Xunil1337** [comment]
Okay .. Updated !

**Comment by DDuarte** [comment]
Did you actually confirm the bug at that commit or you just picked the last 3.3.5 hash?

**Comment by Xunil1337** [comment]
I use and i test it on my actual core ... and i confirm it, i can make an video !

**Comment by DDuarte** [comment]
Off-topic: The spell `SPELL_MAGE_WORGEN_FORM` is used in `spell_mage_polymorph_cast_visual`, a spell cast by [Eldoran](http://www.wowhead.com/npc=18743/elrodan) at [Aurosalia](http://www.wowhead.com/npc=18744/aurosalia) in Silvermoon City. I don't know what is so surprising about it.

**Comment by Xunil1337** [comment]
Yes, but we spoke here from a mage script for player characters and not npc's ?

**Comment by DDuarte** [comment]
Off-topic (cont):

It says right there in the code that it is not a mage spell.

```c++

/// @todo move out of here and rename - not a mage spell
// 32826 - Polymorph (Visual)
class spell_mage_polymorph_cast_visual : public SpellScriptLoader

```

**Comment by DDuarte** [comment]
Since this is issue is full of not related info, open a new one. See http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

> Did I explain what is wrong and what is the expected behavior/output?

**Comment by Aokromes** [comment]
cannot reproduce on 9bd7b0e57144

**Comment by Xunil1337** [comment]
https://www.youtube.com/watch?v=KP6VPdD2eWI

Checkout this Video... It is what i mean !

**Comment by Aokromes** [comment]
Still, cannot reproduce.

**Comment by Xunil1337** [comment]
Check my Video... it is a reproduced version of the bug, why tc used an issue tracker, but dont check the spells on a own server... what is the problem... if compiler say no error you mean all ok ? Lolz ?!

**Comment by Aokromes** [comment]
http://i.imgur.com/fmGSe48.jpg

**Comment by DDuarte** [comment]
The issue you reported does not happen on stock TrinityCore. You messed up something on the code or DB; do not edit it if you do not know what it does.

>   Also, for each author's protection and ours, we want to make certain
that everyone understands that there is no warranty for this free
software.  If the software is modified by someone else and passed on, we
want its recipients to know that what they have is not the original, so
that any problems introduced by others will not reflect on the original
authors' reputations.

See https://github.com/TrinityCore/TrinityCore/blob/3.3.5/COPYING
