### ISSUE TITLE
Character template 

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#13952]
The feature "Character template" is missing (http://i.imgur.com/Zvn1F.jpg).
Packet: SMSG_AUTH_RESPONSE (templatecount) 

Rev: https://github.com/TrinityCore/TrinityCore/commit/9aa170a085cd125a1bf0d3a8ad097141c5d2f95a

**Comment by DDuarte** [comment]
Read http://collab.kpsn.org/display/tc/The+Issuetracker+and+You and complete your issue report.

**Comment by DDuarte** [comment]
Is this a PTR feature?

**Comment by Nelidon** [comment]
Yes, but the packet is the same, it will be interresting for test server. It allows creating predefined characters.

**Comment by AriDEV** [comment]
yes it is on PTR feature where u can set your char level

**Comment by VirusEntertainment** [comment]
This could be implemented maybe with some settings in the config file

**Comment by AriDEV** [comment]
it could be implemented only for GM accounts but its not important i think for now ^^
