### ISSUE TITLE
[3.3.5][Quest] The Drakkensryd

### ISSUE THREAD

**Issue by octon** [TrinityCore/TrinityCore#13956]
Core rev. https://github.com/TrinityCore/TrinityCore/commit/48fa7fa992c02d7c17c39c08cb78c6457d034f49

Quest http://www.wowhead.com/quest=12886

How it should look like:
https://www.youtube.com/watch?v=0M2y0bJRBn4

Bugs:
Proto-drake (which flies to the Temple) doesnt work.
Hyldsmeet Drakerider (http://www.wowhead.com/npc=29694) always "out of range".
Column Ornament (http://www.wowhead.com/npc=29754) falls on the floor.

Cosmetic: 
Thorim (http://www.wowhead.com/npc=29445) sits a little incorrectly.

**Comment by Aokromes** [comment]
Search for Drakkensryd.
1st match before the exiting of this: #1350 Duplicate.
