### ISSUE TITLE
[3.3.5a] You can't mount while you're morphed

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#13951]
You are unable to mount if you are morphed into something, for example, 

noggerfogger elixir

https://github.com/TrinityCore/TrinityCore/commit/9aa170a085cd125a1bf0d3a8ad097141c5d2f95a

**Comment by Aokromes** [comment]
duplicate again, and not about

**Comment by silvermcd123** [comment]
where is the duplicate?

**Comment by Aokromes** [comment]
I told it's not a bug.

**Comment by Takenbacon** [comment]
Aokromes is correct, this is not a bug.
