### ISSUE TITLE
[3.3.5a] Fel Armor only heals player 2 point, not 2 percent

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#13962]
I tested ed158c9c1b6eeb77b93155524e677324135a33ec, I found the warlock spell Fel Armor only heals player 2 point, not 2 percent.

**Comment by ariel-** [comment]
```diff
 @@ -1721,14 +1715,8 @@ void Aura::HandleAuraSpecificPeriodics
- aurEff->SetDonePct(caster->SpellDamagePctDone(target, m_spellInfo, DOT)); // Calculate done percentage first!
- aurEff->SetDamage(caster->SpellDamageBonusDone(target, m_spellInfo, damage, DOT, GetStackAmount()) * aurEff->GetDonePct());
+ aurEff->SetDonePct(caster->SpellDamagePctDone(target, m_spellInfo, DOT));
+ aurEff->SetBonusAmount(caster->SpellDamageBonusDone(target, m_spellInfo, 0, DOT, GetStackAmount()));
```

Maybe missing * aurEff->GetDonePct() ?
Not useful to SetDonePct then not using it.

**Comment by Unholychick** [comment]
@ariel- GetDonePct() is added to the damage in the spellauraeffects.cpp.

I have noticed this issue, but have yet to receive any confirmation

**Comment by Nyeriah** [comment]
```
Vyndrian gains 0 Health from Vyndrian's Fel Armor.(164 Overhealed)
```

Can't confirm @ https://github.com/TrinityCore/TrinityCore/commit/ccdc100d10143285bc058d968f0472ea4d073120

**Comment by ANARCHO-PUNK** [comment]
Can't confirm @ ccdc100 [2]

**Comment by ariel-** [comment]
@Unholychick sorry for not reading all the code
@shenhuyong Cannot reproduce either, are you using custom code?
