### ISSUE TITLE
[6.x] Linux DBC not Found files (1 from 147)

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#13966]
Os: Debian 7
Ived used three different DBC

Some required *.dbc files (1 from 147) not found or not compatible:
/opt/wod/data/dbc/BattlemasterList.dbc

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Demigodess** [comment]
Find that DBC and rename it to "BattlemasterList". Extractors extract this with small captures.

**Comment by Xunil1337** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/tools/map_extractor/loadlib/DBFilesClientList.h#L63

Wrong Name Plate ... Fix it !

**Comment by Kinzcool** [comment]
Meh, blizzard always mess up with this DBC's name, including all the "Lfg" ones being sometimes "LFG".

**Comment by Xunil1337** [comment]
I can send you my DBC Files, but totly files are 517

http://abload.de/img/unbenanntd2xjn.png || Image

**Comment by msoky** [comment]
@Xunil1337 fix it? because you say?...no ! every developer have own life...and they dont have button "FIX IT!"

**Comment by Xunil1337** [comment]
I have link the error and mean dejonxavier

-.-^^

**Comment by Shauren** [comment]
"FIX IT!" HOW ABOUT NO?

**Comment by dejonxavier** [comment]
"Find that DBC and rename it to "BattleMasterList" you have extract "BattlemasterList". Extractors extract this with small captures."

This worked, thanks!

**Comment by Aokromes** [comment]
Linux expects dbc/BattlemasterList.dbc and it works as intended.
