### ISSUE TITLE
New file extension .tex ?

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#13969]
When I searched the Mapextractor system, I've found that this extension is not mentioned anywhere! Is that intentional? I think that's for the textures!

Screen : http://abload.de/img/newtexendingq4c07.png

Programname not present !

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by Xunil1337** [comment]
http://www.trinitycore.org/f/topic/10995-new-file-extension-tex/

Okay !
