### ISSUE TITLE
[6.x] Bnetserver - security

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#13975]
_accountSecurityLevel in Session.cpp is always on 0 (SEC_PLAYER)

Rev: https://github.com/TrinityCore/TrinityCore/commit/a93c40143f4e79577ac8e0a3faee92b1effbcd89

**Comment by DDuarte** [comment]
Don't you mean bnetserver?

**Comment by Nelidon** [comment]
Yeah

**Comment by Carbenium** [comment]
685a3101
