### ISSUE TITLE
.playall command don't work

### ISSUE THREAD

**Issue by ladiszlai** [TrinityCore/TrinityCore#13970]
Please enable the sounds in 6.x source

(.playall command don't work)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by DDuarte** [comment]
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by ladiszlai** [comment]
What?
