### ISSUE TITLE
[6_x] .lookup language

### ISSUE THREAD

**Issue by Shandu** [TrinityCore/TrinityCore#13974]
Hi,

In this case when I for example use ".lookup gamemaster" he shows me all found items with "gamemaster" name, but he show me them on german instead english got enUS (dbc) Setup.

Revision: 802725817bcdab6a838e2b86a22bbe10b03370d4

greetZ
- Shandu

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by ijustwantedtosayhi** [comment]
I don't mean to be a dick, but it's kinda funny when @Aokromes does things like that. Maybe he does not know C++ and just wanted to report a bug. You don't have to tell him to contribute, that's his contribution. If he would've known C++ I'm sure he would've opened a PR, and not an issue.

**Comment by DDuarte** [comment]
You are being a dick because you assumed that contributing is only doing code. It's not. In the file that are links to guidelines on how to properly do a bug report (which is also contributing).

**Comment by Shandu** [comment]
Yes I forgot to include rev. Aokromes were right, and I would defenetly create a PR If i would have some C++ knowledge..

**Comment by Shauren** [comment]
DBC language extraction fixed in 7b5e7e08981838c06db08812c7ab6261e146ecd1
