### ISSUE TITLE
[6_x] INTERACT_GOSSIP - DB/Opcode Issue?

### ISSUE THREAD

**Issue by Shandu** [TrinityCore/TrinityCore#13972]
Hello,

I noticed for example in Human Start Area most of the NPCs are talk-able (quest-accept-able) but If you create for example a Goblin u can't talk to anyone (except vendors). Is it because OPCodes arent fully scripted or because of DB?

Revision: 802725817bcdab6a838e2b86a22bbe10b03370d4

greetZ
- Shandu

**Comment by scorched-wow** [comment]
It's Opcodes but Opcodes isnt finish to add yet.

**Comment by Shandu** [comment]
Yea I were just wondering because, some of them are talk-able and most of them not.
Sadly I have no C++ Knowledge too handle such things :(

**Comment by scorched-wow** [comment]
6.0.3 will get better by time by time! :+1:

**Comment by Shandu** [comment]
I know buddy :+1:

**Comment by Aokromes** [comment]
#14216
