### ISSUE TITLE
[6.x] race teleport problem

### ISSUE THREAD

**Issue by ivin** [TrinityCore/TrinityCore#13981]
if Race = 7 or 3
teleport player to any where
the client Error# 132

revision of Trinitycore SHA: b9e435631db3ec4770bd7a61916e14f3e6267a1b

**Comment by ivin** [comment]
do you have this problem ?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by ivin** [comment]
@Aokromes 
is like this? sory i'm novice

**Comment by Shandu** [comment]
better, but I dont really understand your problem more details would be good.

**Comment by ivin** [comment]
@Shandu
create Gnome or Dwarf
use command teleport the player to any where ,will happen 132error,client close.
but orther race don't happen it.
may be some opcode problem?

**Comment by Aokromes** [comment]
Try after b2746dd19c984c195a11c320b834ffdc4d5beb8d

**Comment by Aokromes** [comment]
No answer after near 1 month, closing, if this bug is still valid, open a new ticket.
