### ISSUE TITLE
[6.xx] bnetserver.exe crash

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#13980]
Hi to all, i"ve install all trinitycore stuff , install TDB 6.00 and update it.
After extracting and compiling maps/core I create bnetaccount and start login.

There is error log, bnetserver crashes after the client try to login on the server.

Cant upload all log, and dont understand what i do wrong, early all was working fine, after update - that thing

http://pastebin.com/Sv0dA8Te - crash log

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
Use pastebin or other paste service.

**Comment by Naxxmare** [comment]
thx,  i correct issue.

**Comment by digz6666** [comment]
Specify the revision

**Comment by Naxxmare** [comment]
https://github.com/TrinityCore/TrinityCore/commit/3e466db36534676ea4df32351f7bfdb3a6f2da04
just from yesterday, i re-instal windows on my pc. re-install all soft from instalation guide , re-compile all and thet crash

**Comment by Naxxmare** [comment]
close issue ive fix problem.

**Comment by DDuarte** [comment]
What was the issue?
