### ISSUE TITLE
[6_x] DB : The Wandering Isle Spawn

### ISSUE THREAD

**Issue by Shandu** [TrinityCore/TrinityCore#13982]
How I promised, I share you Gameobject & Creature Spawns from my Sniff (6.0.3)

http://pastebin.com/iZaM4eDr

TDB 6.00
Rev:  3e466db36534676ea4df32351f7bfdb3a6f2da04

greetZ
- Shandu

**Comment by Kittnz** [comment]
Isn't it better to share your sniff on the forums instead?

**Comment by DarkBrain2580** [comment]
Many Spawns are Double

**Comment by Shandu** [comment]
Beware that Phase system is currently not working, many of spawns are caused by different phases.
It is just a fill up for working with it later.

greetZ
- Shandu

**Comment by DarkBrain2580** [comment]
ah sorry i have forget this^^

**Comment by Shandu** [comment]
- update: removed syntax error

**Comment by DarkBrain2580** [comment]
now it works nice thx

**Comment by Shandu** [comment]
:+1:  freut mich ^^ sind paar wirkliche double spawns z.B die trainings dummys am anfang. Aber geht ja schnel mit einem .npc del makro ;)

**Comment by DarkBrain2580** [comment]
Richtig die dummis meinte ich und ein paar npc`s aber nichts schlimmes die kann man in laufe der zeit entfernen. Danke trotzdem sieht wirklich Super aus.

**Comment by DarkBrain2580** [comment]
Kann man dich irgendwie erreichen über Skype oder so? Hätte da ne frage die hier nicht hin gehört.

**Comment by Aokromes** [comment]
Plz english only on tracker.

**Comment by Shandu** [comment]
@DarkBrain2580 skype: benhancedde

**Comment by msoky** [comment]
DELETE FROM `gameobject` WHERE `guid` BETWEEN @GUID AND @GUID + 1050;
but GO spawns is only 781...why 1050? did you miss some?

**Comment by DarkBrain2580** [comment]
All NPC has a name. By it works very nice.

**Comment by msoky** [comment]
hmmm...then i make mistake anywhere...

**Comment by Shandu** [comment]
- changed

Thanks, but It didnt really matter 400000 is a custom GUID they will be replaced anyway when it will be official released with other GUIDs. I cant tell you why your NPC names are unkown.

Working fine, which DB and Rev u are using?

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8fd7f80b6b20071227e849365709ab3f6403efb4
maybe relog solve this problem...i will test it

**Comment by msoky** [comment]
yup, its working, but there is no quests from NPCs...

**Comment by DarkBrain2580** [comment]
yes the quests are not finish to import.

**Comment by msoky** [comment]
we can fill creature_queststarter and creature_questender probably...and some work on quest_template prevquest and nextquestid...its easy

**Comment by Carbenium** [comment]
Closed by 449ae2b00edc45aa3ed98277a9cb8f897ea55a1c
