### ISSUE TITLE
Rediscovering Your Roots

### ISSUE THREAD

**Issue by darrian12** [TrinityCore/TrinityCore#13999]
http://www.wowhead.com/quest=11521/rediscovering-your-roots

The spell "Expose Razorthorn Root" Doesn't work.

**Comment by Aokromes** [comment]
Read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md and fix your ticket.

**Comment by Aokromes** [comment]
#4777
