### ISSUE TITLE
[DEV] stat system

### ISSUE THREAD

**Issue by soulfrost** [TrinityCore/TrinityCore#13992]
some information for helping :cactus: 

some new wod stats now based on char spec - it can be easy done :+1: 
![trinitycore - microsoft visual studio 2015-01-31 02 32 15](https://cloud.githubusercontent.com/assets/2207154/5985290/3933befe-a8f1-11e4-80bb-7ef2290071dc.png)

![trinitycore - microsoft visual studio 2015-01-31 02 28 50](https://cloud.githubusercontent.com/assets/2207154/5985237/c65f6720-a8f0-11e4-8f1f-32f09e3afe12.png)

i dont have good idea about PrimaryStatOrder[0] - unused ?

**Comment by Sovak** [comment]
This will not work because its wrong :P

**Comment by soulfrost** [comment]
why ? :C 
seems like it's working for me

![world of warcraft 2015-01-31 02 46 18](https://cloud.githubusercontent.com/assets/2207154/5985446/5b8046f6-a8f3-11e4-8a68-51e95a59ae13.png)

**Comment by Sovak** [comment]
Then you clearly changed the variable over time, because what is in the DBC isnt equal to the stat enum

**Comment by soulfrost** [comment]
oh shit... thanks for information

**Comment by DDuarte** [comment]
If you two got code to share please do it in a pull request. Thanks.

**Comment by soulfrost** [comment]
= playerClass->PrimaryStat;

we dont have this oO - ur code wrong too ? :D

public class ChrClasses
{
    int ID;
    int DisplayPower;
    string PetNameToken;
    string NameLang;
    string NameFemaleLang;
    string NameMaleLang;
    string Filename;
    int SpellClassSet;
    int Flags;
    int CinematicSequenceID;
    int AttackPowerPerStrength;
    int AttackPowerPerAgility;
    int RangedAttackPowerPerAgility;
    int DefaultSpec;
    int CreateScreenFileDataID;
    int SelectScreenFileDataID;
    int LowResScreenFileDataID;
    int IconFileDataID;
}

**Comment by carlos93** [comment]
"<b>int8 </b> dSpec" should be "int32", some specs are above id 127
