### ISSUE TITLE
[Quest] If He Cannot be turned

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#13998]
The Leaper doesnt enter in combat with the General Lightsbane.

http://www.wowhead.com/quest=12897
hash: f90decb08d1e5277ac97994b64de25c834737d42

**Comment by Rushor** [comment]
```sql
UPDATE `rg_master_world`.`smart_scripts` SET `target_param2`=50 WHERE  `entryorguid`=29859 AND `source_type`=0 AND `id`=4 AND `link`=0;
```
could you try it with this limitation of the aggroradius?

**Comment by dr-j** [comment]
Cannot reproduce on https://github.com/TrinityCore/TrinityCore/commit/f90decb08d1e5277ac97994b64de25c834737d42 works as intended and all 3 summoned creatures attack general lightsbane,

Which core version are you using?

**Comment by ccrs** [comment]
The same one as you xD

Maybe this is a problem of reputation, npcs not helping as their neutral...
But its strange as the other two do enter in combat...

http://www.wowhead.com/quest=13125/the-air-stands-still
In this one the Ebon champion that helps you goes in and out of combat several times (sometimes a lot of times) before actually begin to attack the npcs. Maybe its all related as also this one is an ebon champion and also was neutral to me at the time I was testing it.

**Comment by Killyana** [comment]
Cannot reproduce, the 3 npc attack the General Lightsbane even if the player is neutral.
