### ISSUE TITLE
Vanish Fade Delay 3.3.5

### ISSUE THREAD

**Issue by Pro100Hens** [TrinityCore/TrinityCore#13993]
http://www.youtube.com/watch?v=SCJSGBYGobk
any ideas?

**Comment by Gooyeth** [comment]
Read: https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by kvipka** [comment]
like this? https://www.youtube.com/watch?v=Elnr6PAw4IY&feature=youtu.be
