### ISSUE TITLE
[6.x] fly speed problems

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14008]
Rev. https://github.com/TrinityCore/TrinityCore/commit/68d026709b92197123a1b9ada71c30f4eda88073
Tested GM speeds and mount speeds, opcodes:
CMSG_MOVE_SET_FLY
CMSG_MOVE_CAN_FLY
spams errors
On grounf speed are working fine, but if try flying - speed is very slow, even GM commands doesnt helps. Only if teleporting in other location - then works only gm - speed

P.S Sorry for my bad English.

**Comment by DarkBrain2580** [comment]
confirm

**Comment by Naxxmare** [comment]
I activated SMSG_MOVE_SET_FLIGHT_SPEED from https://github.com/ProjectcoreDevs/TrinityCore/commit/2ad6c2430e39c9f8467b8d5b590062a5ac73c6fb
works fine thx
