### ISSUE TITLE
visual studio build error

### ISSUE THREAD

**Issue by sergenturkoz** [TrinityCore/TrinityCore#14006]
12>Main.obj : error LNK2019: unresolved external symbol _mysql_server_init@12 referenced in function "public: static void __cdecl MySQL::Library_Init(void)" (?Library_Init@MySQL@@SAXXZ)
12>Main.obj : error LNK2019: unresolved external symbol _mysql_server_end@0 referenced in function "public: static void __cdecl MySQL::Library_End(void)" (?Library_End@MySQL@@SAXXZ)
12>Main.obj : error LNK2019: unresolved external symbol _mysql_ping@4 referenced in function "private: virtual bool __thiscall PingOperation::Execute(void)" (?Execute@PingOperation@@EAE_NXZ)
12>Main.obj : error LNK2019: unresolved external symbol _mysql_get_client_version@0 referenced in function "public: __thiscall DatabaseWorkerPool<class LoginDatabaseConnection>::DatabaseWorkerPool<class LoginDatabaseConnection>(void)" (??0?$DatabaseWorkerPool@VLoginDatabaseConnection@@@@QAE@XZ)
12>Main.obj : error LNK2019: unresolved external symbol _mysql_get_server_version@4 referenced in function "private: bool __thiscall DatabaseWorkerPool<class LoginDatabaseConnection>::OpenConnections(enum DatabaseWorkerPool<class LoginDatabaseConnection>::InternalIndex,unsigned char)" (?OpenConnections@?$DatabaseWorkerPool@VLoginDatabaseConnection@@@@AAE_NW4InternalIndex@1@E@Z)
12>Main.obj : error LNK2019: unresolved external symbol _mysql_thread_safe@0 referenced in function "public: __thiscall DatabaseWorkerPool<class LoginDatabaseConnection>::DatabaseWorkerPool<class LoginDatabaseConnection>(void)" (??0?$DatabaseWorkerPool@VLoginDatabaseConnection@@@@QAE@XZ)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_free_result@4 referenced in function "public: __thiscall ResultSet::~ResultSet(void)" (??1ResultSet@@QAE@XZ)
12>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_free_result@4
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_fetch_row@4 referenced in function "public: bool __thiscall ResultSet::NextRow(void)" (?NextRow@ResultSet@@QAE_NXZ)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_fetch_field@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_fetch@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_store_result@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_bind_result@8 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_free_result@4 referenced in function "private: void __thiscall PreparedResultSet::CleanUp(void)" (?CleanUp@PreparedResultSet@@AAEXXZ)
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_error@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_stmt_error@4
12>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_num_rows@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_stmt_num_rows@4
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_fetch_fields@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_field_count@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_affected_rows@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_errno@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_error@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(char const *)" (?Execute@MySQLConnection@@QAE_NPBD@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_thread_id@4 referenced in function "private: bool __thiscall MySQLConnection::_HandleMySQLErrno(unsigned int)" (?_HandleMySQLErrno@MySQLConnection@@AAE_NI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_set_character_set@8 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_init@4 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_real_connect@32 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_query@8 referenced in function "public: bool __thiscall MySQLConnection::Execute(char const *)" (?Execute@MySQLConnection@@QAE_NPBD@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_store_result@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_get_server_info@4 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_get_client_info@0 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_options@12 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_init@4 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_prepare@12 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_execute@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_bind_param@8 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_close@4 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
12>shared.lib(PreparedStatement.obj) : error LNK2001: unresolved external symbol _mysql_stmt_close@4
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_result_metadata@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(class PreparedStatement *,struct st_mysql_res * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPAVPreparedStatement@@PAPAUst_mysql_res@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_field_count@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(class PreparedStatement *,struct st_mysql_res * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPAVPreparedStatement@@PAPAUst_mysql_res@@PA_KPAI@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_autocommit@8 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_more_results@4 referenced in function "public: class PreparedResultSet * __thiscall MySQLConnection::Query(class PreparedStatement *)" (?Query@MySQLConnection@@QAEPAVPreparedResultSet@@PAVPreparedStatement@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_next_result@4 referenced in function "public: class PreparedResultSet * __thiscall MySQLConnection::Query(class PreparedStatement *)" (?Query@MySQLConnection@@QAEPAVPreparedResultSet@@PAVPreparedStatement@@@Z)
12>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_close@4 referenced in function "public: virtual __thiscall MySQLConnection::~MySQLConnection(void)" (??1MySQLConnection@@UAE@XZ)
12>shared.lib(PreparedStatement.obj) : error LNK2019: unresolved external symbol _mysql_stmt_param_count@4 referenced in function "public: __thiscall MySQLPreparedStatement::MySQLPreparedStatement(struct st_mysql_stmt *)" (??0MySQLPreparedStatement@@QAE@PAUst_mysql_stmt@@@Z)
12>shared.lib(PreparedStatement.obj) : error LNK2019: unresolved external symbol _mysql_stmt_attr_set@12 referenced in function "public: __thiscall MySQLPreparedStatement::MySQLPreparedStatement(struct st_mysql_stmt *)" (??0MySQLPreparedStatement@@QAE@PAUst_mysql_stmt@@@Z)
12>C:\Users\s93\Desktop\bb\bin\Release\authserver.exe : fatal error LNK1120: 42 unresolved externals
13>  CliRunnable.cpp
13>  RASession.cpp
13>  TCSoap.cpp
13>  Main.cpp
13>  WheatyExceptionReport.cpp
13>Main.obj : error LNK2019: unresolved external symbol _mysql_server_init@12 referenced in function "public: static void __cdecl MySQL::Library_Init(void)" (?Library_Init@MySQL@@SAXXZ)
13>Main.obj : error LNK2019: unresolved external symbol _mysql_server_end@0 referenced in function "public: static void __cdecl MySQL::Library_End(void)" (?Library_End@MySQL@@SAXXZ)
13>Main.obj : error LNK2019: unresolved external symbol _mysql_get_client_version@0 referenced in function "public: __thiscall DatabaseWorkerPool<class CharacterDatabaseConnection>::DatabaseWorkerPool<class CharacterDatabaseConnection>(void)" (??0?$DatabaseWorkerPool@VCharacterDatabaseConnection@@@@QAE@XZ)
13>Main.obj : error LNK2019: unresolved external symbol _mysql_get_server_version@4 referenced in function "private: bool __thiscall DatabaseWorkerPool<class CharacterDatabaseConnection>::OpenConnections(enum DatabaseWorkerPool<class CharacterDatabaseConnection>::InternalIndex,unsigned char)" (?OpenConnections@?$DatabaseWorkerPool@VCharacterDatabaseConnection@@@@AAE_NW4InternalIndex@1@E@Z)
13>Main.obj : error LNK2019: unresolved external symbol _mysql_thread_safe@0 referenced in function "public: __thiscall DatabaseWorkerPool<class CharacterDatabaseConnection>::DatabaseWorkerPool<class CharacterDatabaseConnection>(void)" (??0?$DatabaseWorkerPool@VCharacterDatabaseConnection@@@@QAE@XZ)
13>game.lib(World.obj) : error LNK2019: unresolved external symbol _mysql_ping@4 referenced in function "private: virtual bool __thiscall PingOperation::Execute(void)" (?Execute@PingOperation@@EAE_NXZ)
13>scripts.lib(cs_misc.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>scripts.lib(cs_wp.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>game.lib(PlayerDump.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>scripts.lib(cs_ban.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>scripts.lib(cs_go.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>scripts.lib(cs_gobject.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>game.lib(CharacterHandler.obj) : error LNK2019: unresolved external symbol _mysql_real_escape_string@16 referenced in function "private: unsigned long __thiscall DatabaseWorkerPool<class CharacterDatabaseConnection>::EscapeString(char *,char const *,unsigned long)" (?EscapeString@?$DatabaseWorkerPool@VCharacterDatabaseConnection@@@@AAEKPADPBDK@Z)
13>game.lib(Pet.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>game.lib(PetitionsHandler.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>game.lib(GroupHandler.obj) : error LNK2001: unresolved external symbol _mysql_real_escape_string@16
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_free_result@4 referenced in function "public: __thiscall ResultSet::~ResultSet(void)" (??1ResultSet@@QAE@XZ)
13>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_free_result@4
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_fetch_row@4 referenced in function "public: bool __thiscall ResultSet::NextRow(void)" (?NextRow@ResultSet@@QAE_NXZ)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_fetch_field@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_fetch@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_store_result@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_bind_result@8 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_free_result@4 referenced in function "private: void __thiscall PreparedResultSet::CleanUp(void)" (?CleanUp@PreparedResultSet@@AAEXXZ)
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_error@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_stmt_error@4
13>shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol _mysql_stmt_num_rows@4 referenced in function "public: __thiscall PreparedResultSet::PreparedResultSet(struct st_mysql_stmt *,struct st_mysql_res *,unsigned __int64,unsigned int)" (??0PreparedResultSet@@QAE@PAUst_mysql_stmt@@PAUst_mysql_res@@_KI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2001: unresolved external symbol _mysql_stmt_num_rows@4
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_fetch_fields@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_field_count@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_affected_rows@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_errno@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
13>shared.lib(Transaction.obj) : error LNK2001: unresolved external symbol _mysql_errno@4
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_error@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(char const *)" (?Execute@MySQLConnection@@QAE_NPBD@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_thread_id@4 referenced in function "private: bool __thiscall MySQLConnection::_HandleMySQLErrno(unsigned int)" (?_HandleMySQLErrno@MySQLConnection@@AAE_NI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_set_character_set@8 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_init@4 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_real_connect@32 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_query@8 referenced in function "public: bool __thiscall MySQLConnection::Execute(char const *)" (?Execute@MySQLConnection@@QAE_NPBD@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_store_result@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(char const *,struct st_mysql_res * *,struct st_mysql_field * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPBDPAPAUst_mysql_res@@PAPAUst_mysql_field@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_get_server_info@4 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_get_client_info@0 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_options@12 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_init@4 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_prepare@12 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_execute@4 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_bind_param@8 referenced in function "public: bool __thiscall MySQLConnection::Execute(class PreparedStatement *)" (?Execute@MySQLConnection@@QAE_NPAVPreparedStatement@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_close@4 referenced in function "protected: void __thiscall MySQLConnection::PrepareStatement(unsigned int,char const *,enum ConnectionFlags)" (?PrepareStatement@MySQLConnection@@IAEXIPBDW4ConnectionFlags@@@Z)
13>shared.lib(PreparedStatement.obj) : error LNK2001: unresolved external symbol _mysql_stmt_close@4
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_result_metadata@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(class PreparedStatement *,struct st_mysql_res * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPAVPreparedStatement@@PAPAUst_mysql_res@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_stmt_field_count@4 referenced in function "public: bool __thiscall MySQLConnection::_Query(class PreparedStatement *,struct st_mysql_res * *,unsigned __int64 *,unsigned int *)" (?_Query@MySQLConnection@@QAE_NPAVPreparedStatement@@PAPAUst_mysql_res@@PA_KPAI@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_autocommit@8 referenced in function "public: virtual bool __thiscall MySQLConnection::Open(void)" (?Open@MySQLConnection@@UAE_NXZ)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_more_results@4 referenced in function "public: class PreparedResultSet * __thiscall MySQLConnection::Query(class PreparedStatement *)" (?Query@MySQLConnection@@QAEPAVPreparedResultSet@@PAVPreparedStatement@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_next_result@4 referenced in function "public: class PreparedResultSet * __thiscall MySQLConnection::Query(class PreparedStatement *)" (?Query@MySQLConnection@@QAEPAVPreparedResultSet@@PAVPreparedStatement@@@Z)
13>shared.lib(MySQLConnection.obj) : error LNK2019: unresolved external symbol _mysql_close@4 referenced in function "public: virtual __thiscall MySQLConnection::~MySQLConnection(void)" (??1MySQLConnection@@UAE@XZ)
13>shared.lib(PreparedStatement.obj) : error LNK2019: unresolved external symbol _mysql_stmt_param_count@4 referenced in function "public: __thiscall MySQLPreparedStatement::MySQLPreparedStatement(struct st_mysql_stmt *)" (??0MySQLPreparedStatement@@QAE@PAUst_mysql_stmt@@@Z)
13>shared.lib(PreparedStatement.obj) : error LNK2019: unresolved external symbol _mysql_stmt_attr_set@12 referenced in function "public: __thiscall MySQLPreparedStatement::MySQLPreparedStatement(struct st_mysql_stmt *)" (??0MySQLPreparedStatement@@QAE@PAUst_mysql_stmt@@@Z)
13>C:\Users\s93\Desktop\bb\bin\Release\worldserver.exe : fatal error LNK1120: 43 unresolved externals
14>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
14>  Building Custom Rule C:/Users/s93/Desktop/TrinityCore/CMakeLists.txt
14>  CMake does not need to re-run because C:\Users\s93\Desktop\bb\CMakeFiles\generate.stamp is up-to-date.
15>------ Skipped Build: Project: INSTALL, Configuration: Release Win32 ------
15>Project not selected to build for this solution configuration 
========== Build: 12 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========

**Comment by DDuarte** [comment]
You are linking with the wrong libmysql.lib.
You need to change MYSQL_LIBRARY in CMake.

Wait a bit until I finish writing http://collab.kpsn.org/pages/viewpage.action?pageId=12714432

**Comment by DDuarte** [comment]
Wiki page finished, tell me if everything is clear and you can resolve the issue by following the steps described on the page I linked.
