### ISSUE TITLE
[6.x] Quest system, gossips (client crash)

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14009]
Rev. https://github.com/TrinityCore/TrinityCore/commit/68d026709b92197123a1b9ada71c30f4eda88073
TDB 6.00 - updated
Many of quests and gossip's crashed game client with error#132
Maybe need re-work all DB tables(quest,gossip), or i'm wrong, and enabled huge part of opcodes, i known how its hard, but cant help now.

P.S Need update TDB 6.00 - with auth, characters, world correct bases/tables,my friends dev. had many problems with installation.

**Comment by Aokromes** [comment]
auth and character base tables are already updated. as for the rest, following wiki does the job.

**Comment by Aokromes** [comment]
Also #13972

**Comment by DDuarte** [comment]
Crash was fixed in dd4973ab23706aa9372baf99e6ad752da818d6e1
