### ISSUE TITLE
[6.x] Wholist & Friendlist

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14018]
Rev. https://github.com/TrinityCore/TrinityCore/commit/ba312088c7a343f61705ba90eecf0abe9a520084
Cant add friends whatever you write on.
Update wholist dont show who is online
Opcodes errors:
CMSG_SEND_CONTACT_LIST
~~CMSG_WHO~~
CMSG_ADD_FRIEND

**Comment by joschiwald** [comment]
be6b1f52516be0feb2b64f3bdbe1899cf5576777 e01bb918875f88ede211fc13ff3908e30249de33
