### ISSUE TITLE
[6.x] Party & Raid

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14019]
Rev. https://github.com/TrinityCore/TrinityCore/commit/ba312088c7a343f61705ba90eecf0abe9a520084
Cant invite players, party or raid
Opcode error:
CMSG_PARTY_INVITE

P.S I dont find main issue with to-do list, so if duplicate pls close.

**Comment by Killyana** [comment]
It's already on the [6.x] [Dev] Short-term roadmap (Groups (invite, kick, set assistant, make raid, etc)) https://github.com/TrinityCore/TrinityCore/issues/13553
