### ISSUE TITLE
[6.x] Crash

### ISSUE THREAD

**Issue by Rezer954** [TrinityCore/TrinityCore#14011]
Crash worldserver:
http://pastebin.com/9WAS9x4D

rev. https://github.com/TrinityCore/TrinityCore/commit/68d026709b92197123a1b9ada71c30f4eda88073

**Comment by msoky** [comment]
did this solve problem? https://github.com/TrinityCore/TrinityCore/commit/dd4973ab23706aa9372baf99e6ad752da818d6e1

**Comment by jackpoz** [comment]
the first line of the crash log should contain the revision, see https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/shared/Debugging/WheatyExceptionReport.cpp#L426 .
where did it go ?
