### ISSUE TITLE
[3.3.5][Warrior] Core/Spell: Bladestorm disarm

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#14016]
When disarm while warrior's doing bladestorm, warrior loses weapon but it don't stop the bladestorm itself.

Revision: 6ef97aa9429bd6730394465536e291747435e884
Database: TDB.335.57
##

**Comment by Kittnz** [comment]
isn't this always been like that?

**Comment by ccrs** [comment]
i think thats blizzlike

**Comment by joschiwald** [comment]
broken by https://github.com/TrinityCore/TrinityCore/commit/a46d2017230f10348a138af49aec784d28fde391

**Comment by ccrs** [comment]
srly?

**Comment by gabryatfendor** [comment]
As this say http://www.wowwiki.com/Bladestorm from patch 3.3.3 Bladestorm can be disarmed.
I don't know if this guy is right: https://www.youtube.com/watch?v=xuXhiU88tHY
but at 2:15 he explain that when you are disarmed, you simply stop. I will look for other evidence but it seems hard to find them, cause in later patch Bladestorm was heavily changed

**Comment by digz6666** [comment]
@gabryatfendor Exactly, it must stop when disarm on patch 3.3.5a

**Comment by Shauren** [comment]
a46d2017230f10348a138af49aec784d28fde391 is indeed the commit that broke it, however this revealed that the periodic damage spell gets full trigger mask passed to spell cast (which is the case for all triggered spells) and it needs to be fixed somewhere else

**Comment by itslovelol** [comment]
http://codepad.org/BhMXXIkR

**Comment by digz6666** [comment]
@itslovelol Any side effects?

**Comment by ariel-** [comment]
I think it's too broad, there's a hundred of spells with SPELL_ATTR3_MAIN_HAND

**Comment by itslovelol** [comment]
Only Bladestorm is is triggered (SPELL_AURA_PERIODIC_TRIGGER_x) and has SPELL_ATTR3_MAIN_HAND. It should not break any other things nor have side effects.

**Comment by ariel-** [comment]
I see now, checked with SpellWork, but in that case you should nest the ifs, or you'll be doing two different checks.

Like so:
```c++
if (attr4 & cast_while_casting)
{
    if (attr3 & main_hand)
        _triggerFlags = fullmask - ignore;
    else
        // original code
}

**Comment by itslovelol** [comment]
I rather prefer the "hack", since if we do it with triggerFlags the aura isn't removed until next trigger spell call.

**Comment by Frytiks** [comment]
http://codepad.org/BhMXXIkR i test this, all races have full energy, rage and other ... and spell no cost any energy and other ...

**Comment by ariel-** [comment]
Because as I said the patch author didn't nest the ifs, so any spell with MAIN_HAND will automatically have full trigger flags (sinister strike for example has MAIN_HAND attr set)

In stead the only spells with both att4_cast_while_casting (ex-att4_triggered) AND main_hand are Bladestorm and Whirlwhind triggered part.

**Comment by Frytiks** [comment]
Any news ?

**Comment by itslovelol** [comment]
http://codepad.org/cS566FUu - Also think this is a valid fix!

For example disarm should not break all triggered spells which require a main hand:
https://www.youtube.com/watch?v=U13KFaxcrQM

**Comment by Keader** [comment]
Working @robinsch.

**Comment by ShinDarth** [comment]
works for me too, good job @robinsch 
(tested on 302623a1516e487ad64f2028aec287b99372e33a)

**Comment by Keader** [comment]
@robinsch can you pr your fix?

**Comment by tkrokli** [comment]
If he does not have time to do it himself, I volunteer to PR the fix with @robinsch as author. Waiting for robinsch to answer first, because it is best if the original author can do it.

**Comment by Shauren** [comment]
That is wrong, it always checks for mainhand attribute but you can disarm other slots too (ranged and offhand)

**Comment by Noryad** [comment]
I can not reproduce it in 5f901d3 obsolete for me.
