### ISSUE TITLE
[3.3.5] Rescue OOX-09/HL seems bugged

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14021]
Quest in Hinterlands
http://www.wowhead.com/quest=836/rescue-oox-09-hl

After a while during the escort, 3 Owl spawn and attack, the issue is this happens endless, i've killed like 12 of them, but they continue to spawn and the robot chicken didn't advance.

I'm running version rev. f3e86d3 2015/01/01 so i'm few updates behind.

**Comment by Rushor** [comment]
the chicken seems to reset to the last waypoint and continues spawing them :D

**Comment by Rushor** [comment]
and btw dublikate from https://github.com/TrinityCore/TrinityCore/issues/12313
