### ISSUE TITLE
[6.x] Buy items, graveyards, trainers table

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14026]
Rev. https://github.com/TrinityCore/TrinityCore/commit/663052dd7202b3ef118f7c68c7ba183889508d19
TDB 6.00 - updated
Cant buy any item
Graveyards not correctly works in many places, teleporting to another continent or another location.

P.S If duplicate - close or refer.

**Comment by carlos93** [comment]
Class spells are not learnt from trainers in WoD. They are "auto-learned" at levelup ;)

**Comment by Naxxmare** [comment]
oh, thx I dont known. All NPC-trainers are been deleted soon? Exept profession-trainers?

**Comment by DDuarte** [comment]
They will not be deleted, they are still spawned in the world however they do not teach class spells.

Not sure what you mean in the first post, npc_trainer table was not removed from TDB 6.00

**Comment by Naxxmare** [comment]
Sorry for my bad English, i repair my problem, miss couple of updates. Thx for answering.

**Comment by Aokromes** [comment]
Don't report multiple bugs on a single ticket.
As for graveyards refer at #14089

**Comment by DDuarte** [comment]
Buying fixed in f68473a
