### ISSUE TITLE
[6.x.x] Building with -DWITH_COREDBUG=1

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14029]
i have Centos 7 running with MariaDB (not mysql!)

Rev: https://github.com/TrinityCore/TrinityCore/commit/7148d1d86fe59450c739da6a2e184edb3f33f89f

i'm building with -DWITH_COREDBUG=1 to be able to debug the core

Normal building works fine

at the end of the build, this is what happens

http://pastebin.com/hc8dqJQa

**Comment by DDuarte** [comment]
MariaDB is known to work with TC however it is not supported by us.
