### ISSUE TITLE
[6.x] Account-wide mounts

### ISSUE THREAD

**Issue by VirusEntertainment** [TrinityCore/TrinityCore#14034]
I found this on the internet, don't know if it can help the development 

https://gist.github.com/Lillecarl/4c0c78e0650c6d4f35f9

**Comment by DDuarte** [comment]
Why is this a player script and done on login?

**Comment by VirusEntertainment** [comment]
i didn't script this so i don't know the reason of this choice

**Comment by DDuarte** [comment]
> 14:27:27 \<LilleCarl\> Yeah that's 3.3.5 "account mounts" :P

**Comment by DDuarte** [comment]
@VirusEntertainment: if you would like to turn this ticket into an issue (broken account mounts) edit the first post and re-open it.
