### ISSUE TITLE
[6.x] Transmogrifier

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14032]
Rev. https://github.com/TrinityCore/TrinityCore/commit/1d894f1b9d3bce2b8f900c294f16ce6666de2901
TDB 6.00 - updated
Gossip window correct, all actions correct, even gold cost and personal items.  But if push *apply* - nothing change.
P.S Not important thing, but need to be implemented. Like on 4.3.4 branch.

**Comment by Aokromes** [comment]
#14216
