### ISSUE TITLE
[6.x] [Crash] Crash at Player::GetCastSpellInfo:L27163

### ISSUE THREAD

**Issue by Naios** [TrinityCore/TrinityCore#14030]
Rev. 7148d1d86

When casting mout Spells (or any Spell) the server crashes.

Maybe someone can provide a crashlog for this obvious crash. (My debug build is broken...)

**Comment by carlos93** [comment]
Confirm it. This is maybe the cause. https://github.com/TrinityCore/TrinityCore/commit/663052dd7202b3ef118f7c68c7ba183889508d19

**Comment by silvermcd123** [comment]
Confirm

**Comment by Epicurus4** [comment]
Compile in RelWithDebInfo shows that the crash occurs at ```Player::GetCastSpellInfo```

```for (uint32 spellId : overrides->second)``` to be precise
