### ISSUE TITLE
trial of champion bug

### ISSUE THREAD

**Issue by cshaaa** [TrinityCore/TrinityCore#14038]
hello，i want to know how to fix the bug in trial of champion,van you help me.

**Comment by DDuarte** [comment]
This is not a bug report.

**Comment by cshaaa** [comment]
sorry,but the instance can not be defeated

**Comment by DDuarte** [comment]
Do a proper bug report.
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by Aokromes** [comment]
Also, it's duplicate.

**Comment by cshaaa** [comment]
thank you。anyone have some hackmeans？

**Comment by Rushor** [comment]
No, he means that you have to give us following infomations:

A) your current revision: 
http://pokit.org/get/?81a4f7a3bef47ecc052be0f50032407b.jpg in the world database
http://pokit.org/get/?df67e0b8348874aa00297fabafddf686.jpg
Simply copy the version into the report (note my one is only an example)

B) you have to create a better bugreports. What exactly is bugged? currently your post is like :" Hey, please save the world and kill all terrorist", what is actually impossible.

C) If you still want help, open a new ticket with the information given in A), B) and 
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by Aokromes** [comment]
No, he don't have to open a new ticket, like i said, this is duplicate (even more)
