### ISSUE TITLE
[6.x] Spell system is still a bit wonky

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/TrinityCore#14037]
Refer to this screen shot:
http://i.imgur.com/7EzmPaT.png

Also, many spells are not triggering the correct ```SpellAuraEffects``` as found in the DB2s. One example is spell ID 109132.

**Comment by carlos93** [comment]
Damage is correct, the bug is just visual (only with weapon damages, SP and AP bonus damage is shown correct)
