### ISSUE TITLE
[3.3.5] Warrior Engage & Deathwish

### ISSUE THREAD

**Issue by Skyepup** [TrinityCore/TrinityCore#14035]
Currently if you use Death Wish then Enrage it will cancel Death Wish... 
And Vise Versa...

Currently 8b50c14

**Comment by Frytiks** [comment]
Confirmed

**Comment by itslovelol** [comment]
They should not stack according to patch 2.1

**Comment by Aokromes** [comment]
So, incorrect report?

**Comment by Skyepup** [comment]
He is correct as of patch 2.1 they are not apposed to stack!
Awsome, sorry for the confusion...
http://www.wowwiki.com/Patch_2.1.0

**Comment by fat4l** [comment]
yep, he is correct. these effects are not supposed to stack.
Also, the "stronger" enrage, in this case its [Death Wish] should override [Enrage] but enrage should not override death wish. 
There is more spells like this:

Should not stack: Hysteria, Tricks of the Trade, Enrage, Wrecking Crew, Death Wish, Arcane Power, Owlkin Frenzy, Beast Within, and Avenging Wrath.

http://us.battle.net/wow/en/game/patch-notes/3-1-0
Hysteria, Tricks of the Trade, Enrage, Wrecking Crew, Death Wish, Arcane Power, Owlkin Frenzy, Beast Within, and Avenging Wrath damage bonuses no longer stack together.
