### ISSUE TITLE
[6.x] Interface & Panels config saving.

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14041]
Rev.https://github.com/TrinityCore/TrinityCore/commit/9db2e6dbbe216be9c87867e1412bb8b1b980bfdb
TDB 6.00 - updated
After re-loggining on server or after teleporting all client interface configs reset.
P.S Tested more, even in game you choise configs what you need, mark or unmark they, push ok...and if open interface config again all marks again default
specific groups of config reset :
- image (helms, cloaks)

**Comment by MitchesD** [comment]
should be fixed, if not, create a new ticket
