### ISSUE TITLE
[Quest] Will of the Titans

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14040]
http://www.wowhead.com/quest=12705/will-of-the-titans#comments

Two problems with this one:
1- Vehicle summoned by http://www.wowhead.com/item=39266/tainted-crystal has no habilities
2- When u try to do the mision without the vehicle (just as some wowhead comments sugest) NPCs http://www.wowhead.com/npc=28078 and http://www.wowhead.com/npc=28079 are not attackble even though u are hated by The Oracles. Combat starts when u are near their aggroradius but they can only be damaged by areas.

hash: 8b50c142cbf72a51141e7b25c2e0111af6315ce2

**Comment by ccrs** [comment]
None of them has any flag which makes them unattackble

**Comment by dr-j** [comment]
if you add the spells to the vehicle you still cant attack the npcs unless you have turned in a quest which causes a change in rep then you can attack them with both direct damage spells and using vehicle but only as long as you dont leave zone or relog.

Ie only way to complete the dailys where you have to kill the other factions mobs (oracles & frenzyheart) if you dont have aoe abilities which will damage these mobs anyway is to turn in one of the other dailys which dont involve killing those mobs first then you will be able to kill them.

There is already an open issue about this somewhere.

**Comment by dr-j** [comment]
See https://github.com/TrinityCore/TrinityCore/issues/9469

**Comment by ccrs** [comment]
I dont get it, right now im hated by the oracles. I should be able to attack them, shouldnt i?

**Comment by Rushor** [comment]
read what Dr-J said ^^. Every time u change the area or relog, you get the FORCE_FRIENDLY flag in ya face even if you are hated with that faction. so you cannot attack them. after you modified your rep. by 1 into negative, they are attackable again.

**Comment by ccrs** [comment]
meh, then the only valid part here is to add the habilities to the vehicle.

**Comment by Rushor** [comment]
```sql
UPDATE `creature_template` SET `spell1`=52331, `spell2`=52358,`spell3`=53032, `spell4`=52327, `spell5`=52321 WHERE `entry`=28115;
```

spells added from wowhead
