### ISSUE TITLE
[3.3.5] Sample Satisfaction

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#14047]
Core rev: 4adf31ce0ac5e41e80a61c107fd2c8cee64985eb
Spell: [Sample Satisfaction] (http://www.wowhead.com/spell=69438)
Quests:  [A Perfect Puff of Perfume] (http://www.wowhead.com/quest=24629), [A Cloudlet of Classy Cologne] (http://www.wowhead.com/quest=24635) and [Bonbon Blitz] (http://www.wowhead.com/quest=24636)

The spell Sample satisfaction enter in combat with [Kruban Darkblade]  (http://www.wowhead.com/npc=14843) and players in pvp off, and never apply Sample satisfaction aura.

1. Login with a Horde
2. Take any of the 3 quests.
3. Go .go creature 54395
4. Use item quest.

**Comment by Rushor** [comment]
seems to be a afaction problem :/

**Comment by Gooyeth** [comment]
Yes, however the spell has Attributes SPELL_ATTR0_NEGATIVE_1 and SPELL_ATTR1_NO_THREAT.

 SPELL_ATTR1_NO_THREAT should not allow the attack, but SPELL_ATTR0_NEGATIVE_1 allows.

**Comment by Exodius** [comment]
Close this one? #14083
