### ISSUE TITLE
[6.x] Crash - dk talent

### ISSUE THREAD

**Issue by ivin** [TrinityCore/TrinityCore#14055]
ver: 74f577e444da5983c8dac9a715241ab282e5d9c1

DEATH KING learn the Blood talent will Crash .

gdb:
Unit.cpp
         Unit::IsHighestExclusiveAura
                  AuraEffect const* existingAurEff = (*itr);  <-------here,error reading variable itr (Cannot access memory at address 0x8)

**Comment by DDuarte** [comment]
Post a crashlog.

**Comment by ivin** [comment]
@DDuarte 
http://pastebin.com/kfP2uEp2

**Comment by Goatform** [comment]
Hmm I have similar issue on my 5.4.8 core. So, I disabled Improved Blood Presence spell and it didn't crashed anymore. My suggestion is to try same thing.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
No answer after 25d, closing. If this bug is still valid open a new ticket with updated crashlog.
