### ISSUE TITLE
[6.x ] Initial equip no weps

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14057]
Core 04ad137304e818c3403e335336da2b77526bc36a

Rogue night elf start with a dagger and a sword but can't equip the sword
Hunter doesn't have a gun / bow
Deathknight doesn't have sword
Pandaren  monk  has the staff but can't equip
Blood elf monk has the staff but can't equip 
human monk has the staff but can't equip
Rogue dwarf start with a dagger and a mace but can't equip the mace
dwarf monk has the staff but can't equip

Warrior, Mage, Warlock,  Paladin, Shaman looks like they start with there weps

There could be others but these was the ones i tried 

![dk](https://cloud.githubusercontent.com/assets/5343324/6090727/b6ceac4a-aed0-11e4-9dc1-306b78702dc3.png)
![hunter](https://cloud.githubusercontent.com/assets/5343324/6090728/b6d0937a-aed0-11e4-923f-dde8ecd742dc.png)
![rogue 1](https://cloud.githubusercontent.com/assets/5343324/6090729/b6d3e868-aed0-11e4-92b6-fdf9bb80d451.png)
![pana](https://cloud.githubusercontent.com/assets/5343324/6090739/e66e1df0-aed0-11e4-9088-d1371db2fc9d.png)

**Comment by NorthStrider** [comment]
death knights get their weapon during the initial quest line...

**Comment by iceyman** [comment]
Sorry thought i removed that line

**Comment by unholy** [comment]
" Pandaren monk has the staff but can't equip" if he started with it its wrong.

all panderians on retail are not created with weapons because their 1st quest is to pick them from weapon rack and equip them to get quest credit, thats when they get their weapons..

**Comment by iceyman** [comment]
but you can't do Pandaren monk quests without NPC's

**Comment by carlos93** [comment]
For sure, just wait for sniffs or sniff yourself the initial panda zone ;)

**Comment by dsultanr** [comment]
is that confirmed? I also cant equip a trainees staff (73029) with panda monk. 
tried: 
quest add 30027
quest complete 30027
quest reward 30027

also tried to learn staff specialization, not helped, staff's are red

any thoughts?

**Comment by dsultanr** [comment]
should be learned 227 spell

**Comment by Shauren** [comment]
Old.
