### ISSUE TITLE
6.x.x - Crash on character login in Stormwind

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14056]
Rev: https://github.com/TrinityCore/TrinityCore/commit/04ad137304e818c3403e335336da2b77526bc36a
Crashlog: http://pastebin.com/PLc3D2E9

That's right i'm not on debug mode, so is not full detailed crashlog but it can be read where the crash occurs

**Comment by Carbenium** [comment]
This isn't really useful if I'm not mistaken, since we have no idea on which object this happens.

**Comment by silvermcd123** [comment]
even if i could reproduce the full crashlog i'm not sure if you could see exaclty wich object is.

**Comment by DDuarte** [comment]
Put a break point in that line and see what line it is.

**Comment by silvermcd123** [comment]
unfortunaly i'm running this on linux and because of that this is the much i can get. :(

**Comment by Carbenium** [comment]
Try to enable your "misc" logger. Maybe we get a useful index error.

**Comment by silvermcd123** [comment]
well, i just commented that line and now runs fine... but i'm pretty sure that's the wrong way.

**Comment by DDuarte** [comment]
You sure? =D

**Comment by silvermcd123** [comment]
yes

**Comment by Carbenium** [comment]
Readd the line please and activate the "misc" logger for the "error" level at least. Let's see if we get a useful error log.

**Comment by DDuarte** [comment]
Re-open this issue with a proper crashlog and instructions to reproduce the crash.
