### ISSUE TITLE
[Instance/HoL] Volkhan - Missing Visual Spell

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14066]
http://de.wowhead.com/npc=28587/volkhan

This guy should cast every 15 sec. this spell:
ID - 52654

on his forge.

DoCastAOE() and DoCast() does not seem to work for this spell.

Currently this Visual is missing.

**Comment by joschiwald** [comment]
missing conditions and maybe more, script is very outdate

**Comment by Rushor** [comment]
okay the conditionpart:

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND  `SourceGroup`=1 AND `SourceEntry`=52654;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(13, 1, 52654, 0, 0, 31, 0, 3, 28823, 0, 0, 0, 0, '', 'Temper only target Forge');
```

rest missing :/

**Comment by NorthStrider** [comment]
Targets (38, 0) (TARGET_UNIT_NEARBY_ENTRY, NO_TARGET)  so it hits a nearby dummy unit as Rushor said already. So you need a DoCast(me, SPELL_FORGE_VISUAL); and the condition posted above me. define 52654 as SPELL_FORGE_VISUAL = 52654,

**Comment by Rushor** [comment]
```sql
-- Volkhan SAI
SET @ENTRY := 28587;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,0,2000,2000,0,0,11,52654,0,0,0,0,0,1,0,0,0,0,0,0,0,"Volkhan - Out of Combat - Cast 'Temper'");
```

cool at least for sai this is working, currently searching for a ooc method for the c++ script :D

**Comment by Nyeriah** [comment]
Anything above the usual "if (!UpdateVictim()) return" will be executed regardless of it being in combat or not but as joschi said the script is outdated

**Comment by Rushor** [comment]
an issue with an pr is open, this issue is no longer needed.
