### ISSUE TITLE
6.x.x - Wrong Hp Stats

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14067]
Rev: https://github.com/TrinityCore/TrinityCore/commit/8fd7f80b6b20071227e849365709ab3f6403efb4

The issue: Wrong hp stats for players

For example if you create a orc level 1 you have 12 hp, that's less hp than the level 1 mobs

**Comment by DDuarte** [comment]
How much should it be?

**Comment by danlapps** [comment]
168hp on retail

**Comment by AriDEV** [comment]
![wowscrnshot_020815_025808](https://cloud.githubusercontent.com/assets/972273/6094853/5ab6c370-af3e-11e4-9b36-03dfc09caa9c.jpg)

**Comment by carlos93** [comment]
Base HP is removed in WoD, should be removed from core and just take HP from stamina. Then calculate HP from every Stamina point from DBCs.

**Comment by Shauren** [comment]
@carlos93 no, it should not be removed (what blizzard did is simply set base hp to 0 in gtOCTBaseHPByClass.dbc - we read these 0s and then just add hp from stamina, all good here)

**Comment by AriDEV** [comment]
the problem is not the basehp the problem is the calculation from 12 stamina into 168hp

**Comment by danlapps** [comment]
14hp per stamina ? should this be the value ?

**Comment by carlos93** [comment]
Correct I was wrong. 1 point of stamina grants 14HP. This value changed in WoD I think, in Cata was 12HP - 1sta.

**Comment by msoky** [comment]
try this...if its okay, please merge it in repo...this is very important https://github.com/TrinityCore/TrinityCore/issues/13931

**Comment by Shandu** [comment]
do https://github.com/TrinityCore/TrinityCore/issues/13931 solve this problem?
I guess it's just because stamina calculator isnt just implented.

**Comment by silvermcd123** [comment]
http://wow.joystiq.com/2013/12/02/warlords-of-draenor-all-health-will-come-from-stamina/

"Currently, characters have base HP and base stamina. A level one brand new naked alt in the start zone has 22 base stamina, increasing base health by 40, 1.8 health per stamina. Of their total health of 123, 83 is base health. At level 90, same class, same race, base stamina is 164, but that gives 2036 health. This is around 12.4 health per stamina. Level 90 health for a naked restoration shaman is 148,699, so of that, 146,663 is health."

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14097

**Comment by DDuarte** [comment]
7257c81b162c4f776c59f9d8dba692f699020f23
