### ISSUE TITLE
6.x.x - Some gossips don't work

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14069]
Rev: https://github.com/TrinityCore/TrinityCore/commit/e6eadc1f3b979ecb1ecf12533cef48112a11722f

The issue: When you try to talk to some NPC , specially when you're going to turn in quests , they don't open the gossip ,also, other gossips open but for example the innkeeper doesnt let you save the place as your home, guards don't show locations too.

**Comment by Killyana** [comment]
Already notified here: https://github.com/TrinityCore/TrinityCore/issues/13972
