### ISSUE TITLE
[Quest] Aces High!

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14090]
http://www.wowhead.com/quest=13413

When summoned http://www.wowhead.com/npc=32535/wyrmrest-skytalon doesnt have energy and also doesnt regenerate it, which makes this quest impossible to finish.

hash: b31391d463e7e0362bb5c60aae53c8ae9c85d894

**Comment by Rushor** [comment]
confirmed, i always thought this was caused by https://github.com/TrinityCore/TrinityCore/issues/12292 but that was not true, probably the creature has the wrong ressource.

**Comment by Aokromes** [comment]
Maybe incorrect class.

**Comment by Rushor** [comment]
that's it :D  
```sql
UPDATE `creature_template` SET `unit_class`=4 WHERE  `entry`=32535;
```

**Comment by M0ra** [comment]
Aokromes said long ago that this hack

**Comment by Aokromes** [comment]
For sure i said "change class without sniff is hack"
