### ISSUE TITLE
3.3.5a DBErrors

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14093]
Core : a218ce4d2210

DB : 335.57

Creature (Entry: 26608) has SPELL_AURA_CONTROL_VEHICLE aura 47020 defined in `auras` field in `creature_template_addon`.
Creature (Entry: 31306) has SPELL_AURA_CONTROL_VEHICLE aura 58949 defined in `auras` field in `creature_template_addon`.
Table `creature` has creature (GUID: 122545 Entry: 25707) with `MovementType`=0 (idle) have `spawndist`<>0, set to 0.
Table `creature` has creature (GUID: 122824 Entry: 25728) with `MovementType`=0 (idle) have `spawndist`<>0, set to 0.
Table `creature_queststarter` has creature entry (17587) for quest 9612, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
npc_spellclick_spells: Creature template 35427 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
Spell (Id: 50859, effIndex: 0) listed in `spell_target_position` does not have target TARGET_DEST_DB (17).
Spell 73023 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 73022 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 71224 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 69674 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 43770 Effect: 43789 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 49889 Effect: 41055 listed in `spell_linked_spell` has same bp1 like effect (possible hack)
Spell 49889 Effect: 45206 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 53099 Effect: 53098 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 54640 Effect: 54643 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 55288 Effect: 55289 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
[Condition SourceType: 1 (Creature Loot), SourceGroup: 23286, SourceEntry: 32726, ConditionType: 9 (Quest Taken)] has useless data in ConditionValue2 (1)!
[Condition SourceType: 1 (Creature Loot), SourceGroup: 23324, SourceEntry: 32726, ConditionType: 9 (Quest Taken)] has useless data in ConditionValue2 (1)!
[Condition SourceType: 17 (Spell Expl. Target), SourceEntry: 70586, ConditionType: 18 (Title)] has useless data in ConditionValue2 (37852)!
SourceEntry 36546 SourceGroup 1 in `condition` table - spell 36546 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 0, SourceGroup needs correction, ignoring.
SourceEntry 58118 SourceGroup 1 in `condition` table - spell 58118 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 0, SourceGroup needs correction, ignoring.
[Condition SourceType: 17 (Spell Expl. Target), SourceEntry: 48397, ConditionType: 29 (Near Creature)] has useless data in ConditionValue3 (1)!
[Condition SourceType: 17 (Spell Expl. Target), SourceEntry: 48397, ConditionType: 29 (Near Creature)] has useless data in ConditionValue3 (1)!
SourceEntry 48397 SourceGroup 2 in `condition` table - spell 48397 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 1, SourceGroup needs correction, ignoring.
[Condition SourceType: 17 (Spell Expl. Target), SourceEntry: 48363, ConditionType: 29 (Near Creature)] has useless data in ConditionValue3 (1)!
[Condition SourceType: 17 (Spell Expl. Target), SourceEntry: 48363, ConditionType: 29 (Near Creature)] has useless data in ConditionValue3 (1)!
[Condition SourceType: 13 (Spell Impl. Target), SourceGroup: 0, SourceEntry: 56727] in `condition` table, has incorrect SourceGroup (spell effectMask) set, ignoring.
SourceEntry 44997 SourceGroup 1 in `condition` table - spell 44997 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 0, SourceGroup needs correction, ignoring.
SourceEntry 70529 SourceGroup 1 in `condition` table - spell 70529 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 0, SourceGroup needs correction, ignoring.
SourceEntry 71310 SourceGroup 3 in `condition` table - spell 71310 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 1, SourceGroup needs correction, ignoring.
SourceEntry 70471 SourceGroup 3 in `condition` table - spell 70471 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 1, SourceGroup needs correction, ignoring.
ScriptName 'at_eye_of_eternity_improvised_floor' exists in database, but no core script found!
ScriptName 'at_madrigosa' exists in database, but no core script found!
ScriptName 'at_twiggy_flathead' exists in database, but no core script found!
ScriptName 'boss_gazakroth' exists in database, but no core script found!
ScriptName 'do_nothing' exists in database, but no core script found!
ScriptName 'go_defias_cannon' exists in database, but no core script found!
ScriptName 'go_door_lever_dm' exists in database, but no core script found!
ScriptName 'go_kael_orb' exists in database, but no core script found!
ScriptName 'go_movie_orb' exists in database, but no core script found!
ScriptName 'internalitemhandler' exists in database, but no core script found!
ScriptName 'npc_aran_blizzard' exists in database, but no core script found!
ScriptName 'npc_bladespire_ogre' exists in database, but no core script found!
ScriptName 'npc_blaze' exists in database, but no core script found!
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!
ScriptName 'npc_crystalline_tangler' exists in database, but no core script found!
ScriptName 'npc_demon_fire' exists in database, but no core script found!
ScriptName 'npc_flame_crash' exists in database, but no core script found!
ScriptName 'npc_generic_harpoon_cannon' exists in database, but no core script found!
ScriptName 'npc_homunculus' exists in database, but no core script found!
ScriptName 'npc_invis_legion_teleporter' exists in database, but no core script found!
ScriptName 'npc_magnetic_core' exists in database, but no core script found!
ScriptName 'npc_mindless_skeleton' exists in database, but no core script found!
ScriptName 'npc_nether_vapor' exists in database, but no core script found!
ScriptName 'npc_novos_minion' exists in database, but no core script found!
ScriptName 'npc_sliver' exists in database, but no core script found!
ScriptName 'npc_thuzadin_acolyte' exists in database, but no core script found!
ScriptName 'npc_tracy_proudwell' exists in database, but no core script found!
ScriptName 'npc_vereth_the_cunning' exists in database, but no core script found!
ScriptName 'npc_void_zone' exists in database, but no core script found!
ScriptName 'npc_yauj_brood' exists in database, but no core script found!
ScriptName 'spell_ex_463' exists in database, but no core script found!
ScriptName 'spell_ex_5581' exists in database, but no core script found!
ScriptName 'spell_ex_66244' exists in database, but no core script found!
ScriptName 'spell_ex_absorb_aura' exists in database, but no core script found!
ScriptName 'spell_mimiron_flame_suppressant' exists in database, but no core script found!
SmartAIMgr: Entry 1535 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 2719 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 4484 SourceType 0 Event 24 Action 1 using non-existent Text id 5, skipped.
SmartAIMgr: Entry 13601 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 14508 SourceType 0 Event 3 Action 50 gameobject summon: There is a summon spell for gameobject entry 179697 (SpellId: 23176, effect: 0)
SmartAIMgr: Entry 15324 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 15526 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 17397 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 18554 SourceType 0 Event 9 Action 1 using non-existent Text id 4, skipped.
SmartAIMgr: Entry 18554 SourceType 0 Event 13 Action 1 using non-existent Text id 7, skipped.
SmartAIMgr: Entry 18554 SourceType 0 Event 14 Action 1 using non-existent Text id 8, skipped.
SmartAIMgr: Entry 18938 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 19354 SourceType 0 Event 4 Action 1 using non-existent Text id 1, skipped.
SmartAIMgr: Entry 19937 SourceType 0 Event 1 Action 12 creature summon: There is a summon spell for creature entry 20117 (SpellId: 38162, effect: 0)
SmartAIMgr: Entry 19937 SourceType 0 Event 3 Action 12 creature summon: There is a summon spell for creature entry 20117 (SpellId: 38162, effect: 0)
SmartAIMgr: Entry 19937 SourceType 0 Event 12 Action 12 creature summon: There is a summon spell for creature entry 20117 (SpellId: 38162, effect: 0)
SmartAIMgr: Entry 23669 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 24198 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
SmartAIMgr: Entry 24290 SourceType 0 Event 0 Action 33 Kill Credit: There is a killcredit spell for creatureEntry 24290 (SpellId: 43419 effect: 0)
SmartAIMgr: Entry 24999 SourceType 0 Event 2 Action 33 uses non-existent Creature entry 0, skipped.
SmartAIMgr: Entry 25002 SourceType 0 Event 0 Action 33 uses non-existent Creature entry 0, skipped.
SmartAIMgr: Entry 29903 SourceType 0 Event 6 Action 33 Kill Credit: There is a killcredit spell for creatureEntry 29677 (SpellId: 55036 effect: 1)
SmartAIMgr: Entry 30894 SourceType 0 Event 2 Action 33 Kill Credit: There is a killcredit spell for creatureEntry 31049 (SpellId: 58190 effect: 0)
SmartAIMgr: Entry 30945 SourceType 0 Event 9 Action 1 using non-existent Text id 3, skipped.
SmartAIMgr: Entry 37826 SourceType 0 Event 0 Action 12 creature summon: There is a summon spell for creature entry 37952 (SpellId: 70606, effect: 0)
SmartAIMgr: Entry 177490 SourceType 1 Event 0 Action 50 has abs(`target.o` = 104.370003) > 2*PI (orientation is expressed in radians)
SmartAIMgr: Entry 177490 SourceType 1 Event 2 Action 50 has abs(`target.o` = 104.370003) > 2*PI (orientation is expressed in radians)
SmartAIMgr: Entry 2749200 SourceType 9 Event 5 Action 12 has abs(`target.o` = 11.654100) > 2*PI (orientation is expressed in radians)
SmartAIMgr::LoadSmartAIFromDB: Entry 37120 SourceType 0, Event 3, Link Event 7 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 27987 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 25359 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 25335 SourceType 0, Event 6, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 25335 SourceType 0, Event 10, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 26787 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 18938 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 18903 SourceType 0, Event 23, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 19354 SourceType 0, Event 2, Link Event 4 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 4484 SourceType 0, Event 25, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 26670 SourceType 0, Event 18, Link Event 19 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 27788 SourceType 0, Event 11, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 15324 SourceType 0, Event 2, Link Event 3 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 37952 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 26701 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 15526 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 12236 SourceType 0, Event 9, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 4880 SourceType 0, Event 20, Link Event 21 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 4880 SourceType 0, Event 24, Link Event 26 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 4880 SourceType 0, Event 25, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 24035 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 28006 SourceType 0, Event 5, Link Event 7 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 28006 SourceType 0, Event 6, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 9450 SourceType 0, Event 3, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 24198 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 13196 SourceType 0, Event 9, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 17892 SourceType 0, Event 7, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 17892 SourceType 0, Event 20, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 20438 SourceType 0, Event 13, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 28122 SourceType 0, Event 16, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 15146 SourceType 0, Event 3, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 31279 SourceType 0, Event 16, Link Source Event not found or invalid. Event will never trigger.

**Comment by Aokromes** [comment]
#13707
