### ISSUE TITLE
Channel.RestrictedLfg not working properly

### ISSUE THREAD

**Issue by VictorQueiroz** [TrinityCore/TrinityCore#14091]
I already set up the option Channel.RestrictedLfg to 0 and even after that the players aren't joining automatically in chat, and the option to see both factions are not present in worldserver.conf anymore. Someone can give me a hand with that, please?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by VictorQueiroz** [comment]
All the three things are bugs? I'll see what I can do.

**Comment by tkrokli** [comment]
Please document your core rev. hash, TDB version and overall scenario (including OS) in your OP.

**Comment by DDuarte** [comment]
Re-open this issue with the requested info.

Some worldserver configs were moved to RBAC (https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Accounts/RBAC.h#L51, http://collab.kpsn.org/display/tc/RBAC%3A+Role+based+Access+Control).
