### ISSUE TITLE
[Event quest] Crushing the Crown

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14105]
https://github.com/TrinityCore/TrinityCore/commit/244c09db86c171ebd17930ff340074e51a9a0c86
http://www.wowhead.com/quest=24638/crushing-the-crown ( and others)
Currently bugs around, because the spell requires LOS which actually should ignore it.

Fix:
```sql
DELETE FROM `disables` WHERE `sourceType` =0 AND `entry` IN (71599, 71024) AND `flags`=64;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES 
(0, 71599, 64, '', '', 'Ignore LOS for Cosmetic - Explosion (Chemical Wagon)'),
(0, 71024, 64, '', '', 'Ignore LOS for Throw Bomb');
```

See also:
https://github.com/TrinityCore/TrinityCore/issues/5100

**Comment by jobbais** [comment]
confirmed to be working as Rushor is mentioning..
