### ISSUE TITLE
[3.3.5] The Clutches of Evil

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14101]
rev: https://github.com/TrinityCore/TrinityCore/commit/73709e7c1334521189d8882ab1ba33fe259a12dc
DB: 11.57

This quest http://www.wowhead.com/quest=11157 should be in npc www.wowhead.com/npc=23749 , but there is no that quest. In DB "creature_queststarter" is values 23749	11157 . But i don't see this quest in NPC.

**Comment by Rushor** [comment]
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (23749, 11157);

**Comment by Frytiks** [comment]
@Rushor This values are in DB

**Comment by Frytiks** [comment]
Npc have "npcflag = 3"

**Comment by Rushor** [comment]
you first need to complete http://www.wowhead.com/quest=11501/news-from-the-east

feedback: cannot reproduce

**Comment by Frytiks** [comment]
Thanks for letting me correct way :)
