### ISSUE TITLE
6.x.x - Most Spell Effects not working

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14109]
Rev: https://github.com/TrinityCore/TrinityCore/commit/c4d81aa42d4918fa6a9b86bfea017f36192155ed

The issue: Most of the spell effects are not working, for example heal spells, you can use them but they do not heal, any of them. 

Other damage spells like icy touch from death knights, i think it's all the same issue.

**Comment by DDuarte** [comment]
Please be objective when reporting bugs.
Report specific spells (spell name + spell id), what they should do and what they do currently.

**Comment by silvermcd123** [comment]
Specific? None of the spells are working to be more specific. no spell effect, nothing.

**Comment by DDuarte** [comment]
As you wish.
