### ISSUE TITLE
6.x.x - Hearthstone and Inkeepers

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14115]
Rev: https://github.com/TrinityCore/TrinityCore/commit/f4b74f8f1fecc313514375979de627326fc613f6
The issue: Hearthstone does not work , you click it and it stays casting forever
Inkeepers do not set your hearthstone to the place you are.

**Comment by carlos93** [comment]
SMSG_USE_ITEM is not implemented, so hearthstone will not work
