### ISSUE TITLE
Quest system

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14118]
Quest system not added 100% 

only works take quest but cant complete.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by DDuarte** [comment]
I tested some quests and they were completable.

If you found a broken quest, do an **objective** report and write down what exactly happens (quest name, quest id, what should happen, what happens instead).
