### ISSUE TITLE
Opcode - Battlefield (Maybe Work) 6.X

### ISSUE THREAD

**Issue by scorched-wow** [TrinityCore/TrinityCore#14116]
Line 190 to 199  in Opcodes.cpp

STATUS_UNHANDLED 
to
STATUS_NEVER

i have done that in my core and restart it's seems working after level 15 and dungeon finder appeared. 

(Dont know if it work for you but try it?)

(Never mind, its dont effect any different :-1:  )

**Comment by DDuarte** [comment]
Opcodes will be enabled once they are converted and updated to the new structure (e.g 6678635cc7e4df00a265d19653dbbfc2ef5c8eec)

**Comment by scorched-wow** [comment]
Oh cool :)
