### ISSUE TITLE
[The Lich King] Defile should Grow when Grabbed Player is inside?

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#14119]
If yes then it is working fine, 
But doesn't seem like it should.. if not here is the fix (not tested but should work just fine)

https://gist.github.com/D4R4/853f9521c7c1bf95614b

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by D4R4** [comment]
Not sure if it's valid, after confirmation I sure will

**Comment by Rushor** [comment]
yes that's true, on retail, if player move over this devile if they are in a valkyr, they will not get the damage.

neverthess add the hash and so on for better documentation as aokromes already said ^^

**Comment by Kittnz** [comment]
Yeah, defile should only grow if a player is in it. If player is grabbed in the air he shouldn't touch devile at all so it won't grow.

**Comment by Shauren** [comment]
omg tabs

**Comment by joschiwald** [comment]
ceea37c9e3304ea2b387b7d3f6ea201b43c2615d

**Comment by D4R4** [comment]
yay, first time seeing my name on an official TC commit, thx guys
