### ISSUE TITLE
[6.x.x] Auth database: battlenet_accounts AUTO_INCREMENT

### ISSUE THREAD

**Issue by oneluiz** [TrinityCore/TrinityCore#14110]
Rev.: c4d81aa42d4918fa6a9b86bfea017f36192155ed

Would not it have the same "id" table "account"?
```
ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='Account System';
```
https://github.com/TrinityCore/TrinityCore/blob/6.x/sql/base/auth_database.sql#L222
not affected at all in the game ... but to create web applications maybe if affected.
Is it necessary "AUTO_INCREMENT = 7"?

**Comment by Shauren** [comment]
AUTO_INCREMENT only specifies the initial value - 7 being here is just a mistake of not erasing it from my database dump

**Comment by oneluiz** [comment]
thanks @Shauren

**Comment by DDuarte** [comment]
Removed in cbfe638fa50ecd553358bc7b38b57e0293d5cf0f
