### ISSUE TITLE
[3.3.5] AHbot Buyer AH types mismatched

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#14124]
b1a4a8f435d2ba03e45f3a579c6ec48baf2a7cfb

I have been placing items into the Stormwind AH and then checking the ahbot.log to see if items are being bid on. 

Stormind is an alliance AH, (ah type: 0) but the ahbot.log shows the items going into AH type: 1 which is horde. I also created a horde character and went to Orgrimmar's AH and placed 3 items in it's AH then checked the ahbot.log and see that it went to ah type: 2, Neutral AH. 

I have set the chance ratio to 500% so it has been bidding on the items and winning, but I get the items back, not the money.

Here is a sample of when I placed items in Stormwind's AH (ah type: 0).
2015-02-12_09:21:04 AHBot: Alliance buying ...
2015-02-12_09:21:04 AHBot: 0 items added to buyable/biddable vector for ah type: 0
2015-02-12_09:21:04 AHBot: SameItemInfo size = 9206
2015-02-12_09:21:05 AHBot: Horde buying ...
2015-02-12_09:21:05 AHBot: 1 items added to buyable/biddable vector for ah type: 1
2015-02-12_09:21:05 AHBot: SameItemInfo size = 10058
2015-02-12_09:21:05 AHBot: EligibleItems size = 1
2015-02-12_09:21:05 AHBot: Rolling for AHentry 604253:
2015-02-12_09:21:05 AHBot: Bid average: 1088.2 biddable item count: 15
2015-02-12_09:21:05 AHBot: WIN BID! chance = 368.00, price = 1750, bidprice = 1875.
2015-02-12_09:21:05 AHBot: Bid placed to entry 604253, 3.75g
2015-02-12_09:21:06 AHBot: Neutral buying ...
2015-02-12_09:21:06 AHBot: 0 items added to buyable/biddable vector for ah type: 2
2015-02-12_09:21:06 AHBot: SameItemInfo size = 11076
2015-02-12_09:21:07 AHBot: Alliance selling ...

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Aokromes** [comment]
You have wait 1h to get the email?

**Comment by Younguns** [comment]
No, I have the mail set to be delivered immediately.

I get the message that a buyer has been found, and then go to the mailbox to check, and it's the item that I had placed into the AH instead of the money.

**Comment by Aokromes** [comment]
You get 2 emails one of the auction is acepted and the 2nd with the money.

**Comment by jackpoz** [comment]
do you have AllowTwoSide.Interaction.Auction enabled or disabled ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/AuctionHouseBot/AuctionHouseBot.h#L42
wrong enum values order

**Comment by Younguns** [comment]
Thanks jackpoz, I hope it is an easy fix.

**Comment by DarkBrain2580** [comment]
what for a ratio you has set on 500%?
You has set here: AuctionHouseBot.Buyer.ChanceMultiplier.QUALITY on 500 or by a other?
Sorry my Englisch is very bad.

**Comment by Younguns** [comment]
At 500% the AHbot seems to bid on EVERYTHING I put into the AH.

This is my settings for that:
#    AuctionHouseBot.Buyer.ChanceMultiplier.QUALITY
#       Description: Multipliers for the buy/bid chances for each quality. 100 means the chance is 100% of the original,
#                    1 would mean 1 % of the original and 200 would mean 200% of the original chance.
#       Defaults:    Gray   100
#                    White  100
#                    Green  100
#                    Blue   100
#                    Purple 100
#                    Orange 100
#                    Yellow 100

AuctionHouseBot.Buyer.ChanceMultiplier.Gray = 500
AuctionHouseBot.Buyer.ChanceMultiplier.White = 500
AuctionHouseBot.Buyer.ChanceMultiplier.Green = 500
AuctionHouseBot.Buyer.ChanceMultiplier.Blue = 500
AuctionHouseBot.Buyer.ChanceMultiplier.Purple = 500
AuctionHouseBot.Buyer.ChanceMultiplier.Orange = 500
AuctionHouseBot.Buyer.ChanceMultiplier.Yellow = 500

**Comment by DarkBrain2580** [comment]
Ok thx my friend

**Comment by Younguns** [comment]
No problem. :)
