### ISSUE TITLE
[4.3.4] Fix build

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#14123]
Core rev: d0cc938950c3d7493b962714af88ed3b3e3e106e

Rename sql:
**2014_12_30_04_world.sql** --> **2014_12_30_03_world.sql**
**2014_12_30_05_world.sql** --> **2014_12_30_04_world.sql**

**Comment by Aokromes** [comment]
Nope, that won't fix

**Comment by Gooyeth** [comment]
Yes, should fix.

**Comment by Gooyeth** [comment]
you are right, fuck eyes haha

**Comment by Gooyeth** [comment]
@Aokromes:
**2014_12_30_02_world.sql** --> **2014_12_30_04_world.sql**
**2014_12_30_01_world.sql** --> **2014_12_30_03_world.sql**
**2014_12_30_05_world.sql** --> **2014_12_30_02_world.sql**
**2014_12_30_00_world.sql** --> **2014_12_30_01_world.sql**
**2014_12_30_04_world.sql** --> **2014_12_30_00_world.sql**

**Comment by jackpoz** [comment]
Make a PR so the build can be tested ?

**Comment by Aokromes** [comment]
Done.
