### ISSUE TITLE
Chain phase fail on Crusaders Pinnacle

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14125]
Just when complete http://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle on http://www.wowhead.com/npc=30683 phase for player changes and cant take the last quest http://www.wowhead.com/quest=13157

I think it lacks only one condition for this last quest, doesn't it?

hash: c5dac48436c8a00d40640af9aecaaa71d549135a

**Comment by ccrs** [comment]
Possible fix:
````sql
UPDATE `spell_area` SET `quest_end`='13157' WHERE `spell`='57674' and`area`='4504' and`quest_start`='13086' and`aura_spell`='0' and`racemask`='0' and`gender`='2';
````

**Comment by tkrokli** [comment]
I am about to test this, before and after adding that to DB. Would you say that it is enough just to create a new character, push him up to level 78 or 79, outfit him with suitable armor + weapons and .teleport to the Argent Vanguard to pick up the quests and confirm that the issue still is like you say in your 1st post?

**Comment by ccrs** [comment]
it'd be the pefect test... but u can also mod your hp to 1000M :P

**Comment by tkrokli** [comment]
OK, need some sleep first, been awake 20 hours. Trying to test this in about 6 hours time.

**Comment by ccrs** [comment]
Edit: Fix tested and working.

**Comment by tkrokli** [comment]
Sounds good, I'm going to test "before and after" now. :+1:

**Comment by tkrokli** [comment]
OK, I just handed in the quest http://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle to Father Gustav, when he just faded instantly out of phase from my view. (I have gone through all the Argent Vanguard quests up to this point.) I am just going to try the quest from "A Tale of Valor" (http://www.wowhead.com/quest=13068/a-tale-of-valor) from Tirion Fordring and see if that leads anywhere.

**Comment by tkrokli** [comment]
Update: The "Crusader Bridenbrad" questline did nothing to help making Father Gustav visible again. Adding Fix in https://github.com/TrinityCore/TrinityCore/issues/14125#issuecomment-74117152 to my DB and logging in again now. BTW: core hash rev.: https://github.com/TrinityCore/TrinityCore/commit/c5dac48436c8a00d40640af9aecaaa71d549135a

**Comment by tkrokli** [comment]
Core Hash Rev.: https://github.com/TrinityCore/TrinityCore/commit/c5dac48436c8a00d40640af9aecaaa71d549135a
TDB 335.57 + updates including 2015_02_12_06

Confirmed: Fix in https://github.com/TrinityCore/TrinityCore/issues/14125#issuecomment-74117152 works as intended, Father Gustav becomes available with quest http://www.wowhead.com/quest=13157/the-crusaders-pinnacle and fades after quest is accepted.
Just to emphasize (or reiterate), the SQL fix (same as above) is this:
```sql
UPDATE `spell_area` SET `quest_end`='13157', `quest_end_status`='1' WHERE `spell`='57674' and `area`='4504' and `quest_start`='13086' and `aura_spell`='0' and `racemask`='0' and `gender`='2';
```
Note: added 1 space after each 'and' operator in my copy of the SQL query, for visual purposes.
