### ISSUE TITLE
NPC 6776 Magrin Rivermane: vendor items missing

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14121]
TrinityCore rev. c5dac48436c8 2015-02-12 08:21:18 +0100 (3.3.5 branch) (Win32, Release)
TDB 335.57 + updates including 2015_02_12_06

![wowscrnshot_021215_150853](https://cloud.githubusercontent.com/assets/4903600/6168885/8128b250-b2c9-11e4-92d1-8edd6efd249a.jpg)
NPC 6776 Magrin Rivermane does not have any vendor items. He is supposed to have this list of items in his vendor box: http://wotlk.openwow.com/npc=6776#sells

http://www.wowhead.com/npc=6776/magrin-rivermane (unfortunately no relevant info on wowhead)
http://wotlk.openwow.com/npc=6776 (openwow.com was recently resurrected, some images missing)

**Comment by Rushor** [comment]
nope it should be no vendor at all:

**Comment by tkrokli** [comment]
OK, I see. Listed in the section "Other" on WowWiki: http://www.wowwiki.com/Bloodhoof_Village#Other
This means he is not a merchant: http://www.wowwiki.com/Bloodhoof_Village#Merchants

So I guess you are right, we need to remove his vendor flag (even if he would be useful vendor).
