### ISSUE TITLE
6.x.x - Rogue Stealth

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14132]
Rev : https://github.com/TrinityCore/TrinityCore/commit/40dcc170d943dafbb2330ca1fc8c005ed7a61a56
The issue: Stealth doesnt work, you should be invisible but you stay visible even with the aura active

spellid : http://www.wowhead.com/spell=1784/stealth

**Comment by Boomper** [comment]
It's missing SPELL_EFFECT_APPLY_AURA with SPELL_AURA_MOD_STEALTH or triggered spell.

**Comment by fvicaria** [comment]
Any suggestion of where that may be applied?

**Comment by Boomper** [comment]
From what I know rogues have more versions of stealth (depending on spec or talent choice) so maybe add aurascript on apply of this spell and then apply the spells through that.

I sadly don't have access to a rogue on retail so I can't provide any sniffed data.

**Comment by Rushor** [comment]
already reported in https://github.com/TrinityCore/TrinityCore/issues/14825

and pr'd in https://github.com/TrinityCore/TrinityCore/pull/15779
