### ISSUE TITLE
6.x.x - Warrior heroic leap #14134

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14134]
Rev : 40dcc17

The issue: Heroic leap doesnt work, you can´t jump

Spell: http://www.wowhead.com/spell=6544/heroic-leap

**Comment by DDuarte** [comment]
Revision/hash?... http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by tctwod** [comment]
Rev : 40dcc17
