### ISSUE TITLE
6.x.x - Summoning or Calling pets causes client crash

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14135]
Rev: https://github.com/TrinityCore/TrinityCore/commit/f68473aeff08920196115bab56ee47802abd2582

The issue: For example if you create a warlock it starts with an imp (also another bug is that his name is unknown and you cant dismiss it), i used .level 89 to level 90 and then tried to summon other pet for example voidwalker (the issue is not with the void walker or warlock, is with pets globally because hunters happens too) client crashes with some wierd error.

screenshots:
http://postimg.org/image/6hje2v76j/
http://postimg.org/image/8qahypotn/

the first one is very wierd

crashlog:
http://pastebin.com/c7MF9i3m

**Comment by Naxxmare** [comment]
confirmed, even with tallent for more powerful pets, client crash 132...and if any other player will be close to you - his client crash too.

**Comment by DDuarte** [comment]
The crash happens because of https://github.com/TrinityCore/TrinityCore/blob/e6f26cfb1f75d21a166cc3fd371f9c5f1641625e/src/server/game/Entities/Pet/Pet.cpp#L300-L308

Warpten is working on rewriting and correcting the code.

**Comment by DDuarte** [comment]
Ninja fixed in b66d2da2c735569be8ab5208660beef6a4facd33
