### ISSUE TITLE
[Quest] Root Samples

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14137]
Loot for plants is not handled correctly for this quest.
http://www.wowhead.com/quest=866/root-samples

According to documentation http://collab.kpsn.org/display/tc/loot_template#loot_template-lootmode
gob type 3 gets its loot id from data1 field.
Plants are these type of gobjects, and have their data1 filled. Examles:
* Silverleaf(1617, 3725)
* Earthroot(1619)

Gameobject loot for those data1 entries:
* 1414 for Earthroot(1619) hasnt quest item on it.
* 1416 for Silverleaf(1617) has the quest item on it.
* 2511 for Silverleaf(3725) hasnt quest item on it.

Appart from  the lack of loot entries for the quest item (there are many types of plants who should drop it) the only one who has it doesnt drop it.
Also I tried to change the loot for Earthroot to make this quest completable, but same results: no item drop.

hash: 46280a1bb7dcb8cbf508ec8b334cc1b05103c826

**Comment by ccrs** [comment]
![image](https://cloud.githubusercontent.com/assets/4329612/6184764/3e4c04c6-b366-11e4-909c-f9d157f26a2e.png)
![image](https://cloud.githubusercontent.com/assets/4329612/6184767/5009ed2c-b366-11e4-9131-e5669522b2d7.png)

**Comment by ccrs** [comment]
Also, of my 3 examples only Silverleaf(3725) is tracked by the quest and all 3 of them shuld be tracked.

**Comment by Rushor** [comment]
```sql
DELETE FROM `gameobject_loot_template` WHERE `entry`IN (1414,1415,1417,1418,1419,1420,1421,1733,1734,2513) AND `item`=5056;
INSERT INTO `gameobject_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES 
(1414, 5056, -100, 1, 0, 1, 1),
(1415, 5056, -100, 1, 0, 1, 1),
(1417, 5056, -100, 1, 0, 1, 1),
(1418, 5056, -100, 1, 0, 1, 1),
(1419, 5056, -100, 1, 0, 1, 1),
(1420, 5056, -100, 1, 0, 1, 1),
(1421, 5056, -100, 1, 0, 1, 1),
(1733, 5056, -100, 1, 0, 1, 1),
(1734, 5056, -100, 1, 0, 1, 1),
(2513, 5056, -100, 1, 0, 1, 1);
```

loot for all startzone-gos

**Comment by ccrs** [comment]
I hope it works, as i said they didnt seem to drop
