### ISSUE TITLE
[6.x] Guilds crash

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14140]
Rev. https://github.com/TrinityCore/TrinityCore/commit/2b60b7e07dd9934eec42f974f3f29abf8c02bf39
 - crash if create a guild. (restart worldserver - guild is exist but only GM inside, other who signed petition without guild)

crashlog http://pastebin.com/fsvagA95

**Comment by Aokromes** [comment]
There is no guild xp on wod.
http://wow.gamepedia.com/Guild_advancement
Don't report multiple bugs on a single ticket.

**Comment by Naxxmare** [comment]
sorry corrected

**Comment by joschiwald** [comment]
post the crashlog pls

**Comment by jackpoz** [comment]
Issue will be reopened once it will contain all the required informations (being a crashreport a crashlog is a must, http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/ provides steps to get the craslog)

**Comment by Naxxmare** [comment]
edit issue, add crashlog

**Comment by jackpoz** [comment]
@Naxxmare did you manually delete the first line if the crashlog ?
