### ISSUE TITLE
6.x.x - Server Crash

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#14141]
Rev: https://github.com/TrinityCore/TrinityCore/commit/2b60b7e07dd9934eec42f974f3f29abf8c02bf39

log:

http://pastebin.com/TbB7Qxv2

**Comment by Aokromes** [comment]
Plz compile on debug mode, release mode crashlogs are useless.

**Comment by silvermcd123** [comment]
okay i will try
