### ISSUE TITLE
[6.x] Guild invite error

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14142]
Rev. https://github.com/TrinityCore/TrinityCore/commit/2b60b7e07dd9934eec42f974f3f29abf8c02bf39
 - when you invite players to sign guild, slight delay and opcode error
Prevented sending disabled opcode [SMSG_PETITION_SIGN_RESULTS 0x11E9 (4585)]
signed only if invite again with open petition on both players

**Comment by Aokromes** [comment]
#14216
