### ISSUE TITLE
Dungeon finder

### ISSUE THREAD

**Issue by M0ra** [TrinityCore/TrinityCore#14152]
rev. 0844b16bb04fdec9f278ef9c0bfd8149e45aeee2
DB 57
<a href="http://fotohost.by/image/DKb"><img src="http://fotohost.by/images/2015/02/14/1183b7.th.jpg" border="0"></a>
<a href="http://fotohost.by/image/DKh"><img src="http://fotohost.by/images/2015/02/14/2fcbf2.th.jpg" border="0"></a>
<a href="http://fotohost.by/image/DK6"><img src="http://fotohost.by/images/2015/02/14/3fa3a8.md.jpg" border="0"></a>

wtf?

patch: Transmogrification, AC3, PvPrank

**Comment by Aokromes** [comment]
We can't read russian, and DF is working as intended on head.

**Comment by w5860363** [comment]
@Aokromes test from https://github.com/TrinityCore/TrinityCore/commit/fb9099a97c4a03fcbcc14bd7ad2f5159a9537e9a
Test when all copies lock will not be able to join the queue which I think is a BUG

**Comment by Aokromes** [comment]
That's not what that guy reported, he can't queue on any instance normal or heroic, and he got only one save.

**Comment by w5860363** [comment]
This is the same problem, when saved after each instance will be unable to join the instance of the queue
All the lock will not be able to join the queue
