### ISSUE TITLE
3.3.5 the scarlet apocalypse 

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14154]
Quest http://www.wowhead.com/quest=12778/the-scarlet-apocalypse

When you go down the hand in quest u die where the Scourge gryphon are and even walking to The lich King and handing in the quest and accepting a new one 

this shouldn't happen and also instant in combat

https://www.youtube.com/watch?v=Upu3lETGHMg

Core https://github.com/TrinityCore/TrinityCore/commit/164c12cab0cc3c4226738a12bf24a55437679047

DB : 335.57

**Comment by Rushor** [comment]
rev?

**Comment by iceyman** [comment]
Core 164c12cab0cc3c4226738a12bf24a55437679047

DB : 335.57

**Comment by Killyana** [comment]
Cannot reproduce on rev. 68c4ea314443

**Comment by danlapps** [comment]
No feedback since almost a month.  Close ?
