### ISSUE TITLE
[4.3.4]DB/NPC: Mount Hyjal - Complete Creature spawn

### ISSUE THREAD

**Issue by Creedem** [TrinityCore/TrinityCore#14161]
CoreRev.: ced21b733f4c+
Database: TDB 434.09
Tested Query: Yes

Hello trinity team, 

I use your packetparser and sniffer to try to spawn the mount hyjal area. It's my first issues and I try to do the right things. Its not all from the sniffs files but I think a nice have to start.

Some more words for my sql file.
- Not included are:
 - zoneId (only 0)
 - areaId (only 0)
 - phaseId (only 0)
 - phasegroup (only 0)
- Some double spawn but maybe the reason is the phasing in hyjal (I dont know)
- This creatures are only spawning in the mount hyjal area and do nothing else.

https://gist.github.com/Creedem/a65b74ba37bb40745b2b

**Comment by DDuarte** [comment]
I appreciate your help (A LOT!) however I could also load tons of .pkts to our WowPacketParser and copy-paste the .sql produced.

For spawn fixes I expect a little bit more: emotes, waypoints, auras, template updates, addons and related updates.

**Comment by Alastyr** [comment]
Hi Creedem. TC Database doesn't have any spawnarli of Mount Hyjal's creatures. You're done a great work! Can I ask you if you will add gameobjects' spawns? It would be great!

**Comment by Creedem** [comment]
https://gist.github.com/Creedem/d8947e53d9dfd294d19f

Gameobject spawn need some more time, but here is my creature_template_addon.

**Comment by msoky** [comment]
any news?

**Comment by Rushor** [comment]
bumb @Creedem :P

**Comment by Aokromes** [comment]
This adds shitloads of 
Table `creature` has creature (GUID: 371068 Entry: 38952) with abs(`orientation`) > 2*PI (orientation is expressed in radians), normalized.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/455df6e498791b27c789918f0cd92434b835fb7f

vendors, addons, sai, gameobjects done
phasing, movement, quests needs to be done - move your booty and start contributing
