### ISSUE TITLE
Not complete quest in Group

### ISSUE THREAD

**Issue by PaulHellCore** [TrinityCore/TrinityCore#14164]
Core [ 6c7cfcc](https://github.com/TrinityCore/TrinityCore/commit/0651b82de9ebfb9d12f7635063fc3f345745929e)

DB : 335.57

When being in the group not to run quests and any achievements, as soon as you leave the group to become correct. Sorry for my English

**Comment by Rushor** [comment]
that depends on the mechanic, who the questcredit is given. it's not a a general problem. can you list the quests which should grant group credits?

**Comment by PaulHellCore** [comment]
Basically quests, dungeons, Forge of souls, OC, Halls of reflection and so on. And of course all possible achievements in these dungeons

**Comment by Aokromes** [comment]
Very likely you are on raid mode.
