### ISSUE TITLE
[6.x] Remove Guild user have crash

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14165]
Rev: 6c7cfcc

[6.x]  Remove Guild user have crash

error: when you remove a player from your guild, WorldServer stops responding

**Comment by DDuarte** [comment]
Issue will be reopened once it will contain all the required informations (being a crashreport a crashlog is a must, http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/ provides steps to get the crashlog)

**Comment by tctwod** [comment]
ok next i add a crashlog
