### ISSUE TITLE
cmsg_open_item received not handled opcode

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14178]
Rev: 2d40d36
Branch: 6.x

Can´t open items

Error: http://i57.tinypic.com/fnty01.png

**Comment by jackpoz** [comment]
Every opcode handled with DEFINE_OPCODE_HANDLER_OLD below https://github.com/TrinityCore/TrinityCore/blob/56186319bdd41dd26b6cc14f84e6e41eef5d953b/src/server/game/Server/Protocol/Opcodes.cpp#L144 is not handled, there's no need to report them
