### ISSUE TITLE
6.x.x - Flight paths dont work

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/TrinityCore#14183]
Rev. 9db2e6d
TDB 6.00 - updated
When you click npc to speak whith him, he shows a window of text whith "accept button only". You click accept and nothing happens. You try to speak whith him again, and neither the window show up so.
The npc doesnt tell you that you have learned a new flyght path too.
Checked in differents flight paths, stormwind city path and others...

**Comment by tkrokli** [comment]
Sorry for being picky, but could you correct "flyght" to __flight__ / __Flight__ so it looks like a normal word?
(Mostly important in the title, if this issue somehow in the future gets used as basis for a PR or write-up.)

**Comment by Aokromes** [comment]
#14216
