### ISSUE TITLE
[3.3.5][6.x] Global immunity on spells.

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14185]
There is problem with death knight diseases in TBC dungeons.
*Example* 
There is a lot of npc's but for example, these 3 npcs.
http://www.wowhead.com/npc=22884
http://www.wowhead.com/npc=22873
http://www.wowhead.com/npc=22887

With these spells u can't apply diseases on this creatures.
http://www.wowhead.com/spell=55095/frost-fever
http://www.wowhead.com/spell=55078
http://www.wowhead.com/spell=50536

*What is in output ?*
Nothing is in Combat Logs. U do damage with these spell, but diseases are not applied.

**Comment by Runico** [comment]
confirm, Dk's Diseases aren't apply on most of TBC npcs

**Comment by Aokromes** [comment]
Yeah, TBC trashmobs have to much incorrect immunities.

**Comment by Rushor** [comment]
i will remove the desease immunity on them
