### ISSUE TITLE
3.3.5 wing commander gryphongar

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14182]
Core d991f03

DB 335.57

Question mark on head isn't yellow also no gossip so you can't complete quest 

![wowscrnshot_021915_135617](https://cloud.githubusercontent.com/assets/5343324/6261700/3edc145c-b83f-11e4-8635-f939007ec744.jpg)

http://www.wowhead.com/quest=10344/wing-commander-gryphongar 

This is a part of a 12 quest chain which you can start by talking to Force Commander Danath Trollbane in Honor Hold. Here is the whole chain.

¤ The Legion Reborn
¤ The Path of Anguish
¤ Expedition Point
¤ Disrupt Their Reinforcements
¤ Mission: The Murketh and Shaadraz Gateways
¤ Shatter Point
» Wing Commander Gryphongar
¤ Mission: The Abyssal Shelf
¤ Go to the Front
¤ Disruption - Forge Camp: Mageddon
¤ Enemy of my Enemy...
¤ Invasion Point: Annihilator

**Comment by M0ra** [comment]
Confirmed
Rev. d991f03d137ce06dffba59ca735124ef9aacfe61

**Comment by Killyana** [comment]
A spell_script or an Event_script must be done to cast the spell 35237 on the player when he take the quest 10344.

Here a temporary fix:
``` sql 
DELETE FROM `smart_scripts` WHERE `entryorguid`=20234 AND `source_type`=0 AND `id`=3;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(20234,0,3,0,19,0,100,0,10344,0,0,0,11,35237,0,0,0,0,0,7,0,0,0,0,0,0,0,"Runetog Wildhammer - On Quest accept - Cast spell");

**Comment by Killyana** [comment]
One of the 2 solutions can be used.
``` sql
UPDATE `quest_template` SET `SpecialFlags`=0 WHERE `Id`=10344;
