### ISSUE TITLE
3.3.5 Love in the Air event

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14180]
Event love in the air event should of finished but mine seems to be still going and the luna event should of started but hasn't 

 Core d991f03d137c

DB 335.57

**Comment by Aokromes** [comment]
luna event and love is in air started and finished with 3.3.5a calendar not with wod calendar.

**Comment by Frytiks** [comment]
@Aokromes He is talking about 3.3.5 rev. I can't confirm, on my server event started. But IDK why after 2 days.

**Comment by Aokromes** [comment]
I know he is talking about 3.3.5a, you must read again what i wrote.

**Comment by Kittnz** [comment]
So this isn't really a bug. It's just a date problem.
