### ISSUE TITLE
[3.3.5] Spell - Icy Touch Threat

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14191]
Tooltip: From 3.3.5
Chills the target for 227 to 227 Frost damage and infects them with Frost Fever, a disease that deals periodic damage and reduces melee and ranged attack speed by 14% for 15 sec. Very high threat when in Frost Presence.

As wowikki says. It should have aggro - Icy Touch   x7 damage
http://www.wowwiki.com/Threat

In spell_threat is no record for icy touch.
##

**Comment by DDuarte** [comment]
Did this get fixed?...

**Comment by Frytiks** [comment]
I hackfixed it in spell_threath

**Comment by DDuarte** [comment]
Feel free to post the hack fix but do not close the issue... it was not fixed on TC.

**Comment by xiledra** [comment]
In fact, this is only while frost presence is up and is applied by aura 61261 and it works just fine

Id: 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 600
Targets (1, 0) (TARGET_SELF, NO_TARGET)
Aura Id 108 (SPELL_AURA_ADD_PCT_MODIFIER), value = 600, misc = 2 (SPELLMOD_THREAT), miscB = 0, periodic = 0
SpellClassMask = 00000000 00000000 00000002
+ 45477 - Icy Touch (Rank 1)
+ 49896 - Icy Touch (Rank 2)
+ 49903 - Icy Touch (Rank 3)
+ 49904 - Icy Touch (Rank 4)
+ 49909 - Icy Touch (Rank 5)
+ 50880 - Icy Talons (Rank 1)
+ 50884 - Icy Talons (Rank 2)
+ 50885 - Icy Talons (Rank 3)
+ 50886 - Icy Talons (Rank 4)
+ 50887 - Icy Talons (Rank 5)
+ 52372 - Icy Touch (Rank 1)
- 52789 - Visual Dummy
- 53549 - Icy Touch (Rank 1)
- 59131 - Icy Touch (Rank 1)

**Comment by Rushor** [comment]
@Frytiks: post your stuff from spell_threat here

**Comment by offl** [comment]
```sql
INSERT INTO `spell_threat` (`entry`, `flatMod`, `pctMod`, `apPctMod`) VALUES 
(52372, 0, 7, 0);
```
https://github.com/search?q=52372+spell_threat&type=Code&utf8=%E2%9C%93

**Comment by ariel-** [comment]
As @Xiledria said, this is handled by a Spell Modifier, and 61261 is a trigger cast when you activate frost presence.

Related code: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_dk.cpp#L1799
