### ISSUE TITLE
[3.3.5] Problema use spells at high speed

### ISSUE THREAD

**Issue by PaulHellCore** [TrinityCore/TrinityCore#14198]
CORE revision number [ 6c7cfcc](https://github.com/TrinityCore/TrinityCore/commit/b89f3be8d52f6b13bf1008bcbfe45b9e0f9d3ae0)

TDB : 335.57

Sorry for my English. I'm using the latest version of TC and met with the problem of the speed of pronunciation spells. Example: Mind Flay use spells should be 3 stacks for 3 seconds (1 stack every second), but if the spec is pronounced 2.8 seconds then, too, there must be 3 stacks, and place 3 only 2 and so with all spells are spoken with stack so it is with Confession and so forth. I understand the problem in speed?

**Comment by Aokromes** [comment]
Read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
