### ISSUE TITLE
[3.3.5] Uldaman Archaedas fight bugged

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14195]
Hi all, Archaedas fight is bugged, no adds join the fight instead the entire room soon or later should attack the party.

Teste on  cb3fcea 2015-02-05

**Comment by dmegahan** [comment]
Tested on 833a0d2ea52009ea302fedda02882a3e9bd86286 2015-06-04
Seems to be working. All adds joined by the end of the fight, in the correct order.

**Comment by Killyana** [comment]
Confirm, all the adds join the battle as intended.
rev. 35f2f5530abc
