### ISSUE TITLE
Movement problems after charm

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#14206]
When using creature (Unit) spells like charm (Mind Contol and and other) Player has problem with motion. Latter moves to the same place.

Old bug...

I apologize for the translation, badly I know English.

Screen1: http://i67.fastpic.ru/big/2015/0221/7e/06ecfaee44405baeb72d2216994f067e.jpg
Screen2: http://i59.fastpic.ru/big/2015/0221/e7/43d9945dc1f232cd1345134c78d1cae7.jpg

Hash: c5a29004f3662e85157c8641cff663629d6d3d6c
TDB Last rev for 3.3.5a

**Comment by Aokromes** [comment]
I am quite sure this ticket is duplicated.

**Comment by Expecto** [comment]
My old issue is lost ...

**Comment by Aokromes** [comment]
#4723
