### ISSUE TITLE
[6.x] QuestSystem : Taking Quest

### ISSUE THREAD

**Issue by Saamsaam** [TrinityCore/TrinityCore#14209]
rev:  https://github.com/TrinityCore/TrinityCore/commit/ea9eccae8596d440c372b0d9709d4def4b46e648

TDB 6.00 - updated

When you take a quest, it will appear in your Quest Log and in the interractive window.
The problem right now is that it will work for one quest, then if you take another one it won't be show in the interractive window and in your QuestLog event if your delete the visible one

**Comment by gegge** [comment]
I can't even take quests without adding them manually (.quest add ID)
Also if you do .quest complete you can't complete it to the quest giver 'cause complete button doesn't work

**Comment by danlapps** [comment]
Did https://github.com/TrinityCore/TrinityCore/commit/1f9855b7397ff280795a4d171937fc7218f264d9 fix that ?

**Comment by Keany** [comment]
@danlapps nope

**Comment by Aokromes** [comment]
This is working now.
