### ISSUE TITLE
[3.3.5] Objective Completed

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#14205]
Last TC https://github.com/TrinityCore/TrinityCore/commit/b89f3be8d52f6b13bf1008bcbfe45b9e0f9d3ae0

Last TDB

Problem: When you completed any Quest you have a note - "Objective Completed" On offy we don't need it.

**Comment by SQLfix** [comment]
Confirm

**Comment by tkrokli** [comment]
I sort of see your point, but is there any documentation available that proves this was the case also back in 2010 in the days when 3.3.5a (12340) was live on retail? If this feature were to be removed in the source, it would solve the issue of text being displayed twice in many quests, but I don't know if this is the correct way to change it before we have got more background info. Sniffs from 2010 or older would be nice, but I guess other forms of documentation could be used too, like old retail videos on YouTube.

**Comment by cooler-SAI** [comment]
Here we go
http://www.youtube.com/watch?v=E163-oR9UnY
on 2:04 Quest completed, Official Beta WotLK

**Comment by Kittnz** [comment]
Then we have to search for the commit where this was solved.

**Comment by tkrokli** [comment]
I think "Objective Completed" comes from when `AreaExploredOrEventHappens` is used in scripts.

**Comment by cooler-SAI** [comment]
this can help  think
https://github.com/mangos/mangos/commit/5da6d23ce0591e73a530965fdcc4ae35023b2a5c

**Comment by Aokromes** [comment]
Fixed few days ago.
