### ISSUE TITLE
client connect but hang at around 80% (90% it is a bar so ...)

### ISSUE THREAD

**Issue by firelook** [TrinityCore/TrinityCore#14214]
I manage to login to my server, choose a character when I try to connect to the world, it stops ar around 80%

same for french client or english client.
Connection log:
2/22 07:03:25.375  Login program=WoW platform=Wn64 locale=enUS
2/22 07:03:25.641  Component WoW.Wn64.19342
2/22 07:03:25.800  Component WoW.base.19057
2/22 07:03:25.878  Battle.net is Component Bnet.Wn64.37165
2/22 07:03:26.066  LOGIN: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/22 07:03:26.175  Connecting to 82.237.79.179:1119
2/22 07:03:26.441  LOGIN: state: LOGIN_STATE_AUTHENTICATED result: LOGIN_OK 
2/22 07:03:26.534  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
2/22 07:03:26.613  LOGIN: state: RESPONSE_CONNECTED result: LOGIN_OK 
2/22 07:03:27.925  ClientConnection Completed: COP_CONNECT code=RESPONSE_FAILED_TO_CONNECT result=FALSE
2/22 07:03:28.659  ClientConnection Initiating: COP_GET_REALMS code=REALM_LIST_IN_PROGRESS 
2/22 07:03:29.034  ClientConnection Completed: COP_GET_REALMS code=REALM_LIST_SUCCESS result=TRUE
2/22 07:03:31.396  ClientConnection Completed: COP_GET_REALMS code=RESPONSE_CANCELLED result=FALSE
2/22 07:03:31.599  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
2/22 07:03:32.974  ClientConnection Completed: COP_CONNECT code=RESPONSE_FAILED_TO_CONNECT result=FALSE
2/22 07:03:33.146  ClientConnection Initiating: COP_GET_REALMS code=REALM_LIST_IN_PROGRESS 
2/22 07:03:33.224  ClientConnection Completed: COP_GET_REALMS code=REALM_LIST_SUCCESS result=TRUE
2/22 07:03:35.258  ClientConnection Completed: COP_GET_REALMS code=RESPONSE_CANCELLED result=FALSE
2/22 07:03:35.414  ClientConnection Initiating: COP_CONNECT code=CSTATUS_CONNECTING 
2/22 07:03:35.680  ClientConnection Completed: COP_CONNECT code=RESPONSE_CONNECTED result=TRUE
2/22 07:03:35.914  ClientConnection Initiating: COP_AUTHENTICATE code=CSTATUS_AUTHENTICATING 
2/22 07:03:36.242  ClientConnection Completed: COP_AUTHENTICATE code=AUTH_OK result=TRUE
2/22 07:03:37.839  ClientConnection Initiating: COP_GET_CHARACTERS code=43 
2/22 07:03:38.042  ClientConnection Completed: COP_GET_CHARACTERS code=44 result=TRUE
2/22 07:03:46.063  ClientConnection Initiating: COP_LOGIN_CHARACTER code=78 

server.log
World initialized in 1 minutes 32 seconds
TC>Opening muxer thread from inproc://bnetmgr to tcp://192.168.137.85:1118
TrinityCore rev. 6ff1764084d9 2015-02-20 14:31:50 +0100 (6.x branch) (Win64, Rel
WithDebInfo) (worldserver-daemon) ready...
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST_QUERY 0x120C (462
0)] from [Player: <none> (Account: 8)]
No defined handler for opcode [UNKNOWN OPCODE 0x0301 (769)] sent by [Player: <no
ne> (Account: 8)]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST_QUERY 0x120C (462
0)] from [Player: <none> (Account: 8)]
Received not allowed opcode [CMSG_KEEP_ALIVE 0x0981 (2433)] from [Player: <none>
 (Account: 8)]
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1672791226
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1377377290
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1672791226
Received not handled opcode [CMSG_CONNECT_TO_FAILED 0x0135 (309)] from [Player:
<none> (Account: 8)]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST_QUERY 0x120C (462
0)] from [Player: <none> (Account: 8)]
No defined handler for opcode [UNKNOWN OPCODE 0x0301 (769)] sent by [Player: <no
ne> (Account: 8)]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST_QUERY 0x120C (462
0)] from [Player: <none> (Account: 8)]
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1672791226
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1377377290
CMSG_DB_QUERY_BULK: Received unknown hotfix type: 1672791226

**Comment by danlapps** [comment]
Im having same issue.  Any suggestions ?

**Comment by Aaron126** [comment]
try opening your instance & world ports

**Comment by firelook** [comment]
thanks for your suggestion, but already done and double check

**Comment by Aaron126** [comment]
a sniff of you trying to login, or a log of the packets sent / recieved by the worldserver would be helpful

**Comment by firelook** [comment]
have you got a suggestion for a tool, or just give you all the logs produce by the server would be helpfull

**Comment by Aaron126** [comment]
http://www.trinitycore.org/f/topic/9849-trinity-cores-sniffer-for-wow-60319342/
or
https://github.com/Konctantin/SzimatSzatyor

both work, but id prefer if you made a temporary core mod to log the opcodes tbh, cause sniffs wont show some opcodes (mainly SMSG_REDIRECT_CLIENT)
https://gist.github.com/Aaron126/19447c169cf0e08800b7

**Comment by Aaron126** [comment]
> I have a version 5 of Wow with the same port (I start /stop to switch to 6) => allow me to check they are open

fyi you need to have both the instanceport and the worldport open, not just 1

**Comment by firelook** [comment]
all the ports are open => check with no firewall, and on the same pc as the client
