### ISSUE TITLE
Blackrock worg vs Stormwind infantry not scripted in Northshire

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14215]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

Blackrock worgs and Stromwind Infantry should be attacking each other, doing 0 to 1 damage to each other.

**Comment by duayres** [comment]
Should be also some mounted stormwind patrols patrolling the roads in that area. 
Same rev.

**Comment by Rushor** [comment]
dunlicate of https://github.com/TrinityCore/TrinityCore/issues/13258 and a geneal problem

post the wp issue in an other ticket plx :)
