### ISSUE TITLE
Blackrock worg loot in Northshire

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14218]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

There is no loot dropped from Blackrock Worg's when you kill them.

**Comment by danlapps** [comment]
Try with this @Gecko60 
```SQL
UPDATE `creature_template` SET `lootid`=49871 WHERE `entry`=49871;
DELETE FROM `creature_loot_template` WHERE `entry`=49871;
INSERT INTO `creature_loot_template` (`entry`,`item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(49871, 62328, 0, 75, 0, 1, 0, 1, 1, 'Shed Fur'),
(49871, 3300, 0, 25, 0, 1, 0, 1, 1, 'Rabbit's Foot'),
(49871, 5572, 0, 0.5, 0, 1, 0, 1, 1, 'Small Green Pouch'),
(49871, 5571, 0, 0.5, 0, 1, 0, 1, 1, 'Small Black Pouch'),
(49871, 828, 0, 0.5, 0, 1, 0, 1, 1, 'Small Blue Pouch'),
(49871, 805, 0, 0.5, 0, 1, 0, 1, 1, 'Small Red Pouch'),
(49871, 2589, 0, 0.5, 0, 1, 0, 1, 1, 'Linen Cloth');
```

**Comment by Gecko60** [comment]
Thanks danlapps, that worked! :)

**Comment by Gecko60** [comment]
I've updated this though, you were missing a couple drops, and the correct rates.

--Blackrock Worg Drops with correct rates from wiki

UPDATE `creature_template` SET `lootid`=49871 WHERE `entry`=49871;
DELETE FROM `creature_loot_template` WHERE `entry`=49871;
INSERT INTO `creature_loot_template` (`entry`,`item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(49871, 62328, 0, 76, 0, 1, 0, 1, 1, 'Shed Fur'),
(49871, 3300, 0, 24, 0, 1, 0, 1, 1, 'Rabbit Foot'),
(49871, 5572, 0, 0.5, 0, 1, 0, 1, 1, 'Small Green Pouch'),
(49871, 5571, 0, 0.12, 0, 1, 0, 1, 1, 'Small Black Pouch'),
(49871, 828, 0, 0.09, 0, 1, 0, 1, 1, 'Small Blue Pouch'),
(49871, 805, 0, 0.1, 0, 1, 0, 1, 1, 'Small Red Pouch'),
(49871, 4496, 0, 0.12, 0, 1, 0, 1, 1, 'Small Brown Pouch');
(49871, 2589, 0, 0.02, 0, 1, 0, 1, 1, 'Linen Cloth');
(49871, 117, 0, 0.01, 0, 1, 0, 1, 1, 'Tough Jerky');
