### ISSUE TITLE
Brother Paxton Northshire

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14219]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

Brother Paxton should be walking around randomly in Northshire while staying close to the camp site near Sergeant Willem

**Comment by Rushor** [comment]
probably one ticket for all rndmmovement creatures in that zone would be enough?

**Comment by Gecko60** [comment]
Ok, I was told to keep think separate. My mistake.

**Comment by Aokromes** [comment]
Core problem, don't report them.
