### ISSUE TITLE
[6.x] Quest localization

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14225]
Rev. https://github.com/TrinityCore/TrinityCore/commit/9fa57479ca85d01e027c87341ca49ffee6d2acf8
If taken quest, there some text problems...I use ruRU client, all quest_req and rewards list fine, but quest text has problem.
Screenshots:
![wowscrnshot_022215_135054](https://cloud.githubusercontent.com/assets/7688791/6318433/ed8153e8-ba9a-11e4-85d2-cc8c132b7481.jpg)
![wowscrnshot_022215_135108](https://cloud.githubusercontent.com/assets/7688791/6318432/ed8085e4-ba9a-11e4-884c-e998ed66999c.jpg)

**Comment by Aokromes** [comment]
Read wiki about how to properly import database.

**Comment by DDuarte** [comment]
What Aokromes means is you should use `mysql --default-character-set=utf8` when importing files.
