### ISSUE TITLE
Extinguishing Hope Northshire

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14228]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

Extinguishing Hope does not show up in the quest tracker, and also the Extinguisher does not Extinguish fires like it should.

**Comment by Alastyr** [comment]
This quest works perfectly in 434. It's curious.

**Comment by DDuarte** [comment]
Probably just another case of missing opcodes.

**Comment by Dreadii** [comment]
or a broken spellinfo notifier due to the most recent spell updates which seem not to be fully working yet. (there was a report about broken spelleffects somewhere)

**Comment by Epicurus4** [comment]
I don't believe this one is an opcode issue. I agree with Dreadii's assessment and believe this could be related to another issue:
https://github.com/TrinityCore/TrinityCore/issues/14133

**Comment by Aokromes** [comment]
#14209
