### ISSUE TITLE
Spirit Healer

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14221]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

Spirit healers will not talk to you after you die if you try to res with them. Also when you die in northshire you release dead all the way in westfall. You should release by the abbey in Northshire when you die in Northshire.

**Comment by Aokromes** [comment]
#14089
