### ISSUE TITLE
[6.x] Attack Icon Cursor on yellow targets

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14222]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

When hovering your cursor over a blackrock spy or blackrock worg the cursor does not change, it should change to a sword.

**Comment by Aokromes** [comment]
This was fixed long time ago.
