### ISSUE TITLE
Clean up bags Icon in inventory

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14227]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132 2015-02-19 17:12:18 +0100 (6.x branch) (Win64, Release)

When you click clean up bags, a noise is heard however nothing in your inventory moves, instead everything just turns grey.

**Comment by joschiwald** [comment]
does any error message appear in console?

**Comment by Gecko60** [comment]
I have this in my log: Received not handled opcode [CMSG_SORT_BAGS 0x0AE6 (2790)] from [Player: Galihan (GUID Full: 0x0000000000000001

**Comment by blindspell** [comment]
when ur initial bag is full items dont go to other bags if u have any

**Comment by Aokromes** [comment]
Every opcode handled with DEFINE_OPCODE_HANDLER_OLD below https://github.com/TrinityCore/TrinityCore/blob/56186319bdd41dd26b6cc14f84e6e41eef5d953b/src/server/game/Server/Protocol/Opcodes.cpp#L144 is not handled, there's no need to report them

**Comment by Aokromes** [comment]
#13825
