### ISSUE TITLE
[6.x] Can't interact with some NPCs

### ISSUE THREAD

**Issue by gegge** [TrinityCore/TrinityCore#14224]
I tested this in orgrimmar and in dalaran, i can't understand how to reproduce this bug..
When you speak with orgrimmar's grunt the gossip doesn't open, and in the console appears this message:
received not handled opcode [CMSG_CLOSE_INTERACTION 0x1B19 (6937)]

the .npc info has the message "has gossip" to that npc.

Now, i did a test with the npc that open correctly a gossip.
It opens the gossip and return the same message when i close it

Why there is this problem? 

I suggest to try with these npcs: 49750 AND 14990 

try also this problem with these npc ( .go xyz 5907.089 675.224 643.495 571 )

![wowscrnshot_022215_121612](https://cloud.githubusercontent.com/assets/3052434/6318330/a63ec316-ba8c-11e4-9cd9-3c2d6cfd31ff.jpg)
---------
Also, .npc info doesn't return the correct creature_template id

**Comment by Killyana** [comment]
Already notified here https://github.com/TrinityCore/TrinityCore/issues/13972
