### ISSUE TITLE
[3.3.5] Paladin Seal of Righteousness 

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14239]
In the spell book there are two Seal of Righteousness 

![wowscrnshot_022515_074401](https://cloud.githubusercontent.com/assets/5343324/6359938/1c427da0-bcc2-11e4-8a49-a40b4a5c9d45.jpg)
![wowscrnshot_022515_074352](https://cloud.githubusercontent.com/assets/5343324/6359939/1c432c28-bcc2-11e4-9c3f-059535e67c3a.jpg)
![wowscrnshot_022515_074357](https://cloud.githubusercontent.com/assets/5343324/6359940/1c43eb2c-bcc2-11e4-9116-923b2429d8ef.jpg)

Core 869bc4e0f7b07e6fe268b56b531fadde8cf15649

DB 335.57
##

**Comment by pete318** [comment]
It does indeed happen from level 1. From what I can see, one of them is what you're mean to have. 21084 seems to be the one to keep.

**Comment by pete318** [comment]
I actually had a cursory look, down to the level where I could see where it was added to the spell book. But, I can't quite see from what source it decides it should be there from level 1. I must admit I didn't spend too much time on it though.

**Comment by tkrokli** [comment]
TrinityCore rev. 3aa177410010 2015-06-04 17:01:17 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.58 + all updates including 2015_06_04_01_world.sql . No addons.

Confirmed, the spellbook (P) still shows 2 entries/icons for Seal of Righteousness from level 1.
I suspect that this may be something wrong in the database, reflected in this page:
http://wotlk.openwow.com/spells=7.2.594#0+3+16+1

Both the spells **20154** (http://wotlk.openwow.com/spell=20154) and **21084** (http://wotlk.openwow.com/spell=21084) are there, but I think only one of them should be listed and that the other entry is false.

In 6.x, the spell ID 20154 has been moved to a level 42 spell :
http://www.wowhead.com/spell=20154/seal-of-righteousness
The other DB entries with the same name are moved to other spell IDs and have become NPC abilities.

**Comment by Shauren** [comment]
Ok I found out whats the deal with these two spells, 20154 is the previous rank for 21084 with the difference that you don't learn rank 2 directly, you get it together when you learn Judgement

**Comment by fvicaria** [comment]
Just as an informational complement, when looking at wowhead it seems to recognize only the 20154 as a Seal of Righteousness spell. 21084 is not there at all.

**Comment by Shauren** [comment]
wowhead does not have 3.3.5a data anymore.

**Comment by fvicaria** [comment]
SHould we remove one of the entries from db or is it a matter of finding where they are being added to the spell book?

**Comment by Kittnz** [comment]
@Shauren but this spell should be removed if he does know any judgement spell, so need to find a way to remove them if it is learned

**Comment by tkrokli** [comment]
Would it be enough to have 1 or 2 conditions in the DB for those 2 spells, or does it need core change?

**Comment by Eliminationzx** [comment]
Hack fix, also for [Primal Fury](http://wotlk.openwow.com/spell=16961) and [Blood Frenzy](http://wotlk.openwow.com/spell=16954)
 ```diff
src/server/game/Entities/Player/Player.cpp | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 8ce78f8..5a3bf77 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -3382,6 +3382,12 @@ bool Player::AddSpell(uint32 spellId, bool active, bool learning, bool dependent
                 }
             }
         }
+        // Primal Fury(feral) / Seal of Righteousness / Blood Frenzy Don't learn low ranks and remove low rank spell if present
+        else if (spellId == 16954 || spellId == 16961 || spellId == 21084)
+        {
+            if (uint32 prev_spell = sSpellMgr->GetPrevSpellInChain(spellId))
+                RemoveSpell(prev_spell, false, false);
+        }
 ```

**Comment by Rushor** [comment]
the problem with hackfixes are, that everyone will copy it to their server and so they solved their problem. but noone will actually look into this issue anymore to find the real reason for it :D

**Comment by c9240709-b07d-4439-9212-94f05f7a3212** [comment]
![wowscrnshot_021516_152917](https://cloud.githubusercontent.com/assets/14331434/13053484/68ddf460-d40d-11e5-83f0-65e95db36b1a.jpg)

**Some observations:**
- By default, spell no. **21084** is **already set on the action bar** while spell no. **20154** is **not**, so this suggests that spell no. **20154** is an **intruder**.
- By default, spell no. **21084** has in addition that "**Unleashing this Seal's energy will cause**" which is needed for the **Judgements spells** as they **unleashes the Seal's energy**, every time (**The all other Seals has that specifications too**) while spell no. **20154 doesn't** and **Judgements spells** "**unleashes**" **weird damage** (so it must not be in the spells book as you leaned at least one of the Judgements spells).
- As @Shauren said, spell no. **21084** is **used when a Judgement spell is learned** while spell no. **20154** is used when a character has **not yet learned a any Judgement spell**.

**Conclusion:**
- In spell book, as of character creation, only spell no. **20154** must be present. It should be **replaced** with spell no. **21084** when **at least one of Judgements spells is learned**.
