### ISSUE TITLE
Is it hard to setup

### ISSUE THREAD

**Issue by Goten87** [TrinityCore/TrinityCore#14232]
Is THE program hard to setup in Ubuntu or is it eazy 
Also can i play this with WoW 6.1 that Will come out next week
And do you have garrisons working in the server or are you working on that

**Comment by Aokromes** [comment]
this is not a forum.

**Comment by Goten87** [comment]
Well @Aokromes i poster it here sins i cannot find a forum

**Comment by DDuarte** [comment]
http://www.trinitycore.org/f ...?
