### ISSUE TITLE
[6.x] Segmentation fault: DB2Store.h | bool HasRecord

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/TrinityCore#14237]
rev aa3b05c312
```O.S. Ubuntu 14.04```

```WorldSession::HandleDBQueryBulk``` causes a segmentation fault when checking if the hotfix datastore has a record (```store->HasRecord(rec.RecordID)```).

    bool HasRecord(uint32 id) const override { return id < _indexTableSize && _indexTable.AsT[id] != nullptr; }

Fault occurs here: ```_indexTable.AsT[id] != nullptr```

Issue presented after refactoring done in revision 5c4fd7a. Previous method which used ```CheckEntry(*this, id);``` worked without segfault.

**Comment by Aokromes** [comment]
Plz post a crashlog.

**Comment by Epicurus4** [comment]
My apologies. I am unable to compile in debug mode at the moment due to issues with my scriptPCH. I can provide a backtrace using gdb on a non-debug compile if that will help. Let me know if that's something you'd like me to post.

**Comment by Aokromes** [comment]
I sugest you to use:

```
declare -x CFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"
declare -x CXXFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"
cmake ../ -DPREFIX=/change/path/to/trinity -DCMAKE_BUILD_TYPE=None
```

to compile on debug mode.

**Comment by DDuarte** [comment]
Fixed in 4282ec57f3cffbae381ed9cb40ab3a3c56dc906e I guess

**Comment by Epicurus4** [comment]
I haven't been able to test it. I still am unable to enter world in 6.1.0 and no longer have access to 603.

**Comment by Epicurus4** [comment]
Fixed.
