### ISSUE TITLE
[3.3.5] Mind Control purge

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#14231]
Core rev: https://github.com/TrinityCore/TrinityCore/commit/092e61cd3d66bde739d98974ca64b3aace7f099b

Steps to reproduce:
- A priest casts Mind Control onto a player (for example a warlock)
- Shaman purges Mind Control aura from the priest
- Priest lose Mind Control aura but can still control the warlock because warlock still have the Mind Control Aura

It's supposed that if you purge (or dispel) Mind Control from the priest, Mind Control should cancel so both players can free move.

**Comment by Grimton1337** [comment]
Indeed, it deserves attention. :/

**Comment by Raydor** [comment]
@robinsch Do you have a fix for this :$?

**Comment by robinsch** [comment]
There should be a friendly fix that has a continue in it, you need to check there for charmer and vice vera.

**Comment by Natureknight** [comment]
Confirm

**Comment by Raydor** [comment]
Still bugged in https://github.com/TrinityCore/TrinityCore/commit/c210b935942f8f2202f1436f2cf73821614c041d, summoning @ariel-

**Comment by robinsch** [comment]
iirc mind control has a dummy aura if this gets removed from caster you need to stop charm. You can simply create a spell script for this, can't create diff currently.

**Comment by Aokromes** [comment]
```
[11:03:45] <Guest21503> Dont open it Aokromes, its fixed
[11:04:19] <Guest21503> Robinsch script is not needed
[11:04:32] <Aokromes> that's what you get when someone posts a c++ code and someone closes without write why :)
