### ISSUE TITLE
[6.1] update wow build 19678

### ISSUE THREAD

**Issue by xerkoss** [TrinityCore/TrinityCore#14243]
UPDATE `battlenet_components` SET `Build`=19678 WHERE `Build`=19342;
UPDATE `battlenet_components` SET `Build`=19634 WHERE `Build`=19057;
UPDATE `realmlist` SET `gamebuild`=19634 WHERE `gamebuild`=19057;

auth opcodes changed in 6.1?
World initialized in 0 minutes 39 seconds
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, RelWithDebInfo) (worldserver-daemon) ready...
ProcessIncoming: Client not authed opcode = 5170

**Comment by Shauren** [comment]
NOPE.
