### ISSUE TITLE
Crusader Strike - Paladin [6.x]

### ISSUE THREAD

**Issue by blindspell** [TrinityCore/TrinityCore#14245]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132

Using this spell as an example: most spells that benefit from attack power do not deal any damage.

**Comment by Skiopz** [comment]
You mean it doesn't show anything, right?
Because there's the same situation for healing spells.

**Comment by blindspell** [comment]
yes missing opcode handlers it just shows the animation no dmg no text for the used spell etc

**Comment by Aokromes** [comment]
#14216
