### ISSUE TITLE
[Quest] Basic Chemistry

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14249]
http://www.wowhead.com/quest=13279/basic-chemistry

Scripts seem to be ok, but no killcredit is received.

37298bbc2f71a928c89e9e7f3b982b6afd8cdc0f

**Comment by Mihapro** [comment]
Kill credit spell: [59876](http://www.wowhead.com/spell=59876/kill-credit)

**Comment by Killyana** [comment]
Targets (27, 0) (TARGET_UNIT_MASTER, NO_TARGET)
``` sql
Update `smart_scripts` SET`action_type`=85, `target_type`=7 WHERE `entryorguid`= 3177300 AND `source_type`=9 AND `id`=0;
Update `smart_scripts` set `action_type`=85, `target_type`=7 WHERE `entryorguid`= 3244200 AND `source_type`=9 AND `id`=0;

**Comment by tkrokli** [comment]
@Killyana : Sorry for making it look like spam (or ignorance), but is the first line of your post just a reference and not needed in the actual commit? (I'm just curious, don't know the code well enough.)
```cpp
Targets (27, 0) (TARGET_UNIT_MASTER, NO_TARGET)

**Comment by Killyana** [comment]
It's just an information, It means the target of the spell must be a master, so the caster must be a summoned unit, You can get this informations from "SpellWork".

**Comment by tkrokli** [comment]
Thanks for clarifying. I'm not quite "there" yet (as in knowing what happens), but I think I see the logic. :+1:
