### ISSUE TITLE
Monks - Chi [6.x]

### ISSUE THREAD

**Issue by blindspell** [TrinityCore/TrinityCore#14246]
Warlords of Draenor
Core 6.0.3 (19342) Release X64

TrinityCore rev. 1cb5132

Monks currently cant gain any Chi since there is nothing regarding it.

**Comment by gearsofdeath** [comment]
I've noticed that there is no spell_monk.cpp in the core

**Comment by AwkwardDev** [comment]
Say what. Missing combat mechanics aren't new, I don't think Trinity development reached this phase in 6.0.3 development.

**Comment by Runico** [comment]
Be patient.

**Comment by Aokromes** [comment]
#13825
