### ISSUE TITLE
[DB/QUEST] [A Rough Ride]

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14248]
Hi, quest A rough Ride is bugged. http://www.wowhead.com/quest=12536/a-rough-ride

U should maybe get spell [51258 ] for ride, but when you press gossip, nothing happends

When i try to .cast 51258 i get on crocodile and i get to last waypoint, but credit i don't get credit.

DB: 11.57
Core: https://github.com/TrinityCore/TrinityCore/commit/61ba5e4f34211c2f0f286e70d8ace37714ca3c56

**Comment by Killyana** [comment]
This will fix the two issues:
``` sql
UPDATE `smart_scripts` SET `action_type`=85 WHERE `entryorguid`=28298 AND `sourceType`=0 AND `id` =0;

**Comment by Frytiks** [comment]
Correction, 

UPDATE `smart_scripts` SET `action_type`=85 WHERE `entryorguid`=28298 AND `source_type`=0 AND `id` =0;
