### ISSUE TITLE
3.3.5 Paladin - The Tome of Divinity

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14240]
So i went and did this quest http://www.wowhead.com/quest=1789/the-symbol-of-life and returned to Muiredon Battleforge to complete the quest on completion of the quest he gave me redemption and then i had to speak with Tiza battleforge again and came up with this  and u can still get symbol of life from her as she is still flagged as repeatable or blue question mark.

![wowscrnshot_022515_105256](https://cloud.githubusercontent.com/assets/5343324/6362858/f4d739ac-bcdc-11e4-8f60-fd0108c4ff59.jpg)

it should be like this video near end

https://www.youtube.com/watch?v=VKXoTRDmarY

Core 869bc4e

DB 335.57

**Comment by Killyana** [comment]
This will make the quest visible only if the player has the quest 1789 taken. The rest is already fixed.
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=20 AND `SourceEntry`=1789;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(20, 0, 1789, 0, 9, 1783, 0, 0, 0, '', 'Show the quest if 1789 is taken');
