### ISSUE TITLE
3.3.5 vmaps crash server Win64 in 

### ISSUE THREAD

**Issue by darkteam1995** [TrinityCore/TrinityCore#14255]
about an entrance in instance Onyxia's Lair
Crash log
http://dv-star.ru/language/overrides/crash.txt

Commit rev
https://github.com/TrinityCore/TrinityCore/commit/b911356bad9a2e37498ab15b638069739a7a4d26 AND TDB335.57 + last update in sql for source

**Comment by jackpoz** [comment]
strange that the first line is
>Revision: TrinityCore rev.  (Win64, Debug)

**Comment by darkteam1995** [comment]
I'm used last rev source code. Not custom mode .

**Comment by Aokromes** [comment]
G3D::Vector3 iPos
float x = 22303.357422
float y = 21481.597656
invalid coords?

**Comment by jackpoz** [comment]
this is an array overflow in https://github.com/TrinityCore/TrinityCore/blob/b911356bad9a2e37498ab15b638069739a7a4d26/src/server/collision/Maps/MapTree.cpp#L396
>referencedVal = 0x1D023
iNTreeValues = 0x19E3E
