### ISSUE TITLE
[3.3.5] Stealth enemies floating

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14252]
Tested on cb3fcea 2015-02-05

Invisible enemies are often walking a feet over terrain

**Comment by Aokromes** [comment]
Don't report multiple bugs on a single ticket, provide guids of invisible enemiges.

**Comment by ccrs** [comment]
Members of the same group/raid cannot attack each other.

**Comment by ikir83** [comment]
@Aokromes 
Sorry for this i edit the thread to talk about first issue only

@ccrs 
Thanks so much. Yeah i supposed it was reported by everyone eh eh. You're right we were in party: it is simple and logical... our fault.

**Comment by Aokromes** [comment]
```sql
SELECT * FROM `creature_addon` WHERE `guid` IN (SELECT guid FROM `creature` WHERE `id` = 2586);
```

It looks it can be converted into creature_template_addon.

**Comment by Killyana** [comment]
We need to find all the npcs affected

``` sql
DELETE FROM `creature_addon` WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id` = 2586);

DELETE FROM `creature_template_addon` WHERE `entry`=2586;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(2586, 0, 0, 0, 4097, 0, "");

**Comment by Crysicle** [comment]
Few creatures with same issue prior.

https://github.com/TrinityCore/TrinityCore/issues/12237
