### ISSUE TITLE
[3.3.5] Any new account is able to create Heroic character as the first one

### ISSUE THREAD

**Issue by kamran185** [TrinityCore/TrinityCore#14259]
Any new account is able to create Heroic if he just created the account and do the first login to the system. 
Here is the Trinity Core data:
 TrinityCore rev. a3bc75b7b969 2015-02-11 18:40:03 +0000 (3.3.5 branch) (Unix, Release) | a3bc75b7b969  | TDB 335.57 |       57 |

**Comment by danlapps** [comment]
can you post your worldserver.conf since its there you set minumum level for heroic character

**Comment by tkrokli** [comment]
@kamran185 : in particular, post the contents of this section from your Worldserver.conf file:
```
#    CharacterCreating.MinLevelForHeroicCharacter
#        Description: Limit creating heroic characters only for account with another
#                     character of specific level (ignored for GM accounts).
#        Default:     55 - (Enabled, Requires at least another level 55 character)
#                     0  - (Disabled)
#                     1  - (Enabled, Requires at least another level 1 character)

CharacterCreating.MinLevelForHeroicCharacter =

**Comment by kamran185** [comment]
Here it is: 
CharacterCreating.MinLevelForHeroicCharacter = 55

**Comment by tkrokli** [comment]
> Here it is:
CharacterCreating.MinLevelForHeroicCharacter = 55

Hmm. This needs to be confirmed by more than 1, preferably with a recent core. I'll give it a shot. BBL.

**Comment by kamran185** [comment]
If you need something from my side, just tell me.

**Comment by tkrokli** [comment]
@kamran185 : confirm if the account that made a DK as first char is a normal account, gmlevel = 0 .

**Comment by Aokromes** [comment]
http://i.imgur.com/hQwUABi.jpg

**Comment by kamran185** [comment]
@tkrokli 
Simple user created with command "account create". Checked within the game, no GM rights.
Can give few accounts on server to check...

**Comment by kamran185** [comment]
@Aokromes 
Why the case is closed if no solution given? (Sorry, I'm new to this system)

**Comment by Aokromes** [comment]
Because the tracker is for trinitycore BUGS and there is no such bug.

**Comment by kamran185** [comment]
I'm sorry, but what kind of bug is this and where to report then?
On the forum I've been advices to open the ticket (http://www.trinitycore.org/f/topic/11081-335-charactercreatingminlevelforheroiccharacter/)

**Comment by Aokromes** [comment]
Since you are the only having this problem, it's not trinitycore bug, instead user bug.

**Comment by kamran185** [comment]
Maybe no one pays attention to it as the servers are full of chars and no one control the creation of the new accounts and their chars?

**Comment by Aokromes** [comment]
I have show you one screenshot of myself trying to create one dk on one account without lvl 55 or higher char inside.

**Comment by kamran185** [comment]
The problem is not about DK without the char of level 55. 
The problem appears when you create absolutelly new account and enter the game for the first time. Then you can create DK. Let me create small video for you.

**Comment by Aokromes** [comment]
Still, the same.

**Comment by kamran185** [comment]
Here is the link to the video: http://youtu.be/2Fmi3nhtcRM

**Comment by danlapps** [comment]
The DK is confirmed AFTER name selection, everyone can do the part in your video

**Comment by DDuarte** [comment]
At the end of your video you dont actually create a DK. If that is not a GM account by default and config is correct you should get an error message like Aokromes posted above.

**Comment by tkrokli** [comment]
@kamran185 : looks like DDuarte pointed out what you have misunderstood. Anyone can view the DK character selection screen, but not actually create a DK. You need to prove that a newly created account can actually **create** a DK character, not just **view** the **DK selection screen** (which is available to all).

**Comment by kamran185** [comment]
Yeah, my fault... Tried with GM first, and haven't tried to actually create character with the simple user. Sorry for that... No bug with the trinity core, only myself.

**Comment by danlapps** [comment]
No problem, thank you for actually confirming this is not a bug and not letting this un-answered.
