### ISSUE TITLE
3.3.5 The Iron Colossus

### ISSUE THREAD

**Issue by Nexus-WoW** [TrinityCore/TrinityCore#14263]
Hello,

the Quest The Iron Colossus is not working.
You have the use the Controllpanel in the near of the Jormungarworm, to Controll the Worm but it`s not working. If you Controll the Worm in Gm Mode the Worm has no Spells.
You have to controll the Worm couse u can`t kill the Iron Colossus for an normal Player.

Newst TC 3.3.5a
Rev: 3035a42

**Comment by Aokromes** [comment]
#4974
