### ISSUE TITLE
[3.3.5][Core/Spell] Lock and Load - Procc 

### ISSUE THREAD

**Issue by Nexus-WoW** [TrinityCore/TrinityCore#14261]
Hello Folks,

the Hunter Procc "Lock and Load" is working on a Frosttrap and on the Icecoldtrap but its not Proccing for 100% at the Icecoldarrow and its not working for 6% at the Immolation Trap, Black Arrow and Explosive Trap.

Newest TC
3.3.5a
rev: 3035a42

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Nexus-WoW** [comment]
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
Not working.

**Comment by Nexus-WoW** [comment]
Sorry first time on Github...

**Comment by Frytiks** [comment]
Confirmed.

**Comment by Keader** [comment]
Still dont work on rev 1b0f475e9593560224b9f8db84422ed89145a30d

**Comment by Rushor** [comment]
```sql
UPDATE `spell_proc_event` SET `SchoolMask`='0', `SpellFamilyName`='9', `SpellFamilyMask0`='0', `SpellFamilyMask1`='0', `SpellFamilyMask2`='0', `procFlags`='2430272', `procEx`='0', `ppmRate`='0', `CustomChance`='0', `Cooldown`='22' WHERE (`entry`='-56342');
```

by @Frytiks
