### ISSUE TITLE
[Possibly all branches] ID - 58410 Master Poisoner (Rank 3)

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14268]
Greetings. 
This spell spamming Server.log as hell. All time getting spam Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?

In SpellWork i found

Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 3
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 231 (SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE), value = 3, misc = 23 (23), miscB = 0, periodic = 0
SpellClassMask = 00000000 00080000 00000000
	- 2818 - Deadly Poison (Rank 1)
	- 2819 - Deadly Poison II (Rank 2)
	- 3409 - Crippling Poison
	- 5760 - Mind-numbing Poison
	- 11353 - Deadly Poison III (Rank 3)
	- 11354 - Deadly Poison IV (Rank 4)
	- 13218 - Wound Poison (Rank 1)
	- 13222 - Wound Poison II (Rank 2)
	- 13223 - Wound Poison III (Rank 3)
	- 13224 - Wound Poison IV (Rank 4)
	- 25349 - Deadly Poison V (Rank 5)
	- 26968 - Deadly Poison VI (Rank 6)
	- 27187 - Deadly Poison VII (Rank 7)
	- 27189 - Wound Poison V (Rank 5)
	- 57969 - Deadly Poison VIII (Rank 8)
	- 57970 - Deadly Poison IX (Rank 9)
	- 57974 - Wound Poison VI (Rank 6)
	- 57975 - Wound Poison VII (Rank 7)
Trigger spell (45176) Not found, Chance = 100

This spell not found.

rev: https://github.com/TrinityCore/TrinityCore/commit/3035a4218bddb4362efa81a12c6bafb3c1b727bf
TDB: 335.57

**Comment by tkrokli** [comment]
I think you mean to say "TDB: 335.57" since the commit you are using is 3.3.5. Label: [Branch-3.3.5a]

**Comment by danlapps** [comment]
Found this one : https://github.com/TrinityCore/TrinityCore/issues/12221

```SQL
DELETE FROM `spell_proc_event` WHERE `entry`=58410;
INSERT INTO `spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES
('58410','0','8','0','524288','0','0','0','0','0','0'); -- Master Poisoner (Rank 3)
```

**Comment by tkrokli** [comment]
I am also compiling my own 3.3.5 servers, but I am unable to find either 58410 or 45176. My current core is on rev. b911356bad9a at the moment, but I am about to compile a new one today to check. Can you post a bit from your "spam", exactly like it is shown in your Server.log ? Put 3 grave accent characters ( ``` ) on the line over, to make your paste looks like this:
```
Spell 73023 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 73022 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 71224 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 69674 Effect: 69706 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 43770 Effect: 43789 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 49889 Effect: 41055 listed in `spell_linked_spell` has same bp1 like effect (possible hack)
Spell 49889 Effect: 45206 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 53099 Effect: 53098 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 54640 Effect: 54643 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 55288 Effect: 55289 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Script named 'npc_king_jokkum_vehicle' does not have a script name assigned in database.
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!
```
(this is the only regular DBErrors I get, unless I do something wrong in-game and provoke errors manually)

**Comment by Aokromes** [comment]
It's runtime error.

**Comment by tkrokli** [comment]
> It's runtime error.

OK, then I would like to know how to reproduce the issue (e.g. if it happens only when playing a rogue).

**Comment by danlapps** [comment]
same problem as https://github.com/TrinityCore/TrinityCore/issues/12221 ?

**Comment by danlapps** [comment]
Can this be any use ?
```SQL
INSERT INTO `spell_dbc` (`Id`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `Stances`, `StancesNot`, `Targets`, `CastingTimeIndex`, `AuraInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaxLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `RangeIndex`, `StackAmount`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectMiscValueB1`, `EffectMiscValueB2`, `EffectMiscValueB3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectSpellClassMaskA1`, `EffectSpellClassMaskA2`, `EffectSpellClassMaskA3`, `EffectSpellClassMaskB1`, `EffectSpellClassMaskB2`, `EffectSpellClassMaskB3`, `EffectSpellClassMaskC1`, `EffectSpellClassMaskC2`, `EffectSpellClassMaskC3`, `MaxTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags1`, `SpellFamilyFlags2`, `SpellFamilyFlags3`, `MaxAffectedTargets`, `DmgClass`, `PreventionType`, `DmgMultiplier1`, `DmgMultiplier2`, `DmgMultiplier3`, `AreaGroupId`, `SchoolMask`, `Comment`) VALUES


3.('45176','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','1','1','1','0','1','0','-1','0','0','3','0','0','0','0','0','0','0','0','0','0','0','0','0','0','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','8','0','0','0','0','0','0','0','0','0','0','1','Master Poisoner Trigger (SERVERSIDE)');
```
Not sure what it's Worth, was in the other issue pastebin

**Comment by danlapps** [comment]
So far trying to get the errors without applying fix, and unable to reproduce

**Comment by tkrokli** [comment]
> So far trying to get the errors without applying fix, and unable to reproduce

We need more feedback from the OP with steps on how to reproduce this issue.

**Comment by Aokromes** [comment]
#13222
