### ISSUE TITLE
Received not handled opcode

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#14266]
Core : https://github.com/TrinityCore/TrinityCore/commit/a89cfb16576e9e921ee29e26abba3bac3a603570
OS : Windows

Received not handled opcode [CMSG_MOVE_FALL_RESET 0x310A (12554)] from [Player:
Admin (GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1)]
Not received CMSG_TIME_SYNC_RESP for over 30 seconds from player 1 (Admin), poss
ible cheater
Received not handled opcode [CMSG_QUERY_BATTLEFIELD_STATE 0x7202 (29186)] from [
Player: Admin (GUID Full: 0x0000000000000001 Type: Player Low: 1, Account: 1)]

I have Coredebug on ... i do not know is that an bug or not !

**Comment by DDuarte** [comment]
All the `STATUS_UNHANDLED` at https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp#L145 will throw that error, no need to report them.

**Comment by Xunil1337** [comment]
Pls Check first Core Version, than Close that issue, it is for 4.3.4 ! For what i should post core hash -.-^^

**Comment by DDuarte** [comment]
Replace 6.x by 4.3.4 in the link above, it's still valid.

**Comment by Xunil1337** [comment]
Okay, and what should we do ? Wait for an official update or !? Is it not possible to fix it ?!

**Comment by DDuarte** [comment]
It's possible to fix the issue by handling those opcodes. Unless someone fixes it and proposes a Pull Request that issue on the branch 4.3.4 will likely not be fixed. The 4.3.4 branch has been deprecated.

**Comment by Xunil1337** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13224

I can not understand it. Is that hard to fix ?! Why other opcode handlers are fixxed but not that ?! :(

**Comment by click** [comment]
We're not actively working on 4.3.4 - for fixes, get the code that fixes it and create a pullrequest. - as Nayd said.
