### ISSUE TITLE
can't create characters

### ISSUE THREAD

**Issue by tomm7** [TrinityCore/TrinityCore#14267]
Core: TrinityCore rev. e98a098b51a5
DB: TDB 6 Full

can't create characters. Core and database are clean.

Received not handled opcode [CMSG_CHAR_CREATE 0x133A (4922)] from [Player: <none> (Account: 1)]

**Comment by Aokromes** [comment]
Fixed on e4797c4765d16b4af80b138d81581a1b84aa6a68
