### ISSUE TITLE
[Patch 4.3.4 Kezahn] Defiant Troll Refixxed !

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#14272]
```sql
UPDATE `creature_text` set `type`=12 where `entry`=34830;
```
The trolls do not yell, they say the text.

http://collab.kpsn.org/display/tc/creature_text#creature_text-type

**Comment by Killyana** [comment]
The type is already 12 on the DB, also broadcast_text must be added. And it's better to do this with scripts involving this npc.

**Comment by Xunil1337** [comment]
Is not

**Comment by danlapps** [comment]
To avoid the "misunderstanding" we had on IRC, usually start issue with : 
What is happenning now : XXXXXX

What should happen : YYYYY

Proposed fix : ZZZZZ

**Comment by Killyana** [comment]
Update your DB: https://github.com/TrinityCore/TrinityCore/blob/98ca9a77491196ef501093572867236712d74938/sql/old/4.3.4/TDB5_to_TDB6_updates/world/093_2014_03_03_00_world_quest_14069.sql

**Comment by Xunil1337** [comment]
OMG ! Use Smart_Script for that ?! ... But this is Bugged !

**Comment by Aokromes** [comment]
Clean TDB 4.3.4-09.


mysql> SELECT * FROM `creature_text` WHERE `entry` = '34830' LIMIT 0, 1000;
+-------+---------+----+--------------------------------------------------------------------+------+----------+-------------+-------+----------+-------+-----------------+-----------+---------------+
| entry | groupid | id | text                                                               | type | language | probability | emote | duration | sound | BroadcastTextId | TextRange | comment       |
+-------+---------+----+--------------------------------------------------------------------+------+----------+-------------+-------+----------+-------+-----------------+-----------+---------------+
| 34830 |       0 |  0 | Don't tase me, mon!                                                |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  1 | I report you to HR!                                                |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  2 | I'm going. I'm going!                                              |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  3 | Oops, break's over.                                                |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  4 | Sorry, mon. It won't happen again.                                 |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  5 | What I doin' wrong? Don't I get a lunch and two breaks a day, mon? |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
| 34830 |       0 |  6 | Work was bettah in da Undermine!                                   |   12 |        0 |         100 |     0 |        0 |     0 |               0 |         0 | Defiant Troll |
+-------+---------+----+--------------------------------------------------------------------+------+----------+-------------+-------+----------+-------+-----------------+-----------+---------------+
