### ISSUE TITLE
[6.1] Cant delete character

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14279]
Rev. https://github.com/TrinityCore/TrinityCore/commit/7665c9ee555fde5e327d4f3bae95b1c3f030b83b
TDB 6.xx full updated
Cant deleted character from character list window

**Comment by Aokromes** [comment]
All the `STATUS_UNHANDLED` at https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp#L145 will throw that error, no need to report them.
