### ISSUE TITLE
6.x DBC Extractor failing to extract 4 DBC

### ISSUE THREAD

**Issue by biocatalyst** [TrinityCore/TrinityCore#14278]
Fresh load and data extractor process of the 19702 Compatible Core
REV: 7665c9ee555f

Server Log:
TrinityCore rev. 7665c9ee555f 2015-03-01 16:21:15 -0500 (master branch) (Win32, Release) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.0.1l 15 Jan 2015 (library: OpenSSL 1.0.1l 15 Jan 2015)
Using Boost version: 1.57.0
Realm running as realm ID 3 region 2 battlegroup 3
Using World DB: TDB 6.00
Using enUS DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir C:/WoWServer/Warlords/Data/
WORLD: MMap data directory is: C:/WoWServer/Warlords/Data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: C:/WoWServer/Warlords/Data/vmaps
Loading Trinity strings...
>> Loaded 1036 trinity strings in 8 ms
Initialize data stores...
Some required *.dbc files (4 from 147) not found or not compatible:
C:/WoWServer/Warlords/Data/dbc/AreaGroup.dbc
C:/WoWServer/Warlords/Data/dbc/CurrencyTypes.dbc
C:/WoWServer/Warlords/Data/dbc/SoundEntries.dbc
C:/WoWServer/Warlords/Data/dbc/gtOCTClassCombatRatingScalar.dbc

**Comment by jackpoz** [comment]
19702 is the new 6.1 that just came out ? Is 6.x on 6.0.3, 6.1 or neither of the 2 ?

**Comment by DDuarte** [comment]
6.x is on 19702 atm. DBCs were not updated yet.

**Comment by Aokromes** [comment]
Try again after 3db001e897de9f8b3bc307c42d1e1200f2169503
