### ISSUE TITLE
[4.3.4][DB] Access to a gameobject without quest

### ISSUE THREAD

**Issue by galathil-feanor** [TrinityCore/TrinityCore#14271]
Hi,

You can access to some gameobject without the require quest...
For example this quest : http://fr.wowhead.com/quest=28715/les-demons-voleurs
It require to open some bag to retrieve require items for the quest. But a player who hasn't the quest can open the bag too.. It's not blizzlike and the gameobject despawn after use inthe two cases..

I used the last rev of branch 4.3.4 with database up to date.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by danlapps** [comment]
Taking for granted 4.3.4 DB struct is same as 6X since i dont have access to one

```SQL
UPDATE `gameobject_loot_template` SET `QuestRequired`=1 WHERE `entry`=27260 AND `item`=46700;
```

**Comment by tkrokli** [comment]
@galathil-feanor : Add your core revision hash and TDB version in your existing post. It is required info.

**Comment by galathil-feanor** [comment]
It works, thank you
