### ISSUE TITLE
[4.3.4] DB/QUEST - Ride to the Undercity

### ISSUE THREAD

**Issue by winterbreeze** [TrinityCore/TrinityCore#14277]
Hi everyone,

I have encountered a problem in the quest [Ride to the Undercity]

The NPC - Bat Handler Anette Williams does nothing when you try to talk to her to request for a Bat Ride from Brill to Undercity

NPC - http://www.wowhead.com/npc=43124/anette-williams
Quest - http://www.wowhead.com/quest=6323/ride-to-the-undercity

DB: 434.09
Hash: a266077eed6a+
Windows 7 64 Bit

![bat handler](https://cloud.githubusercontent.com/assets/11058171/6436363/25f86dac-c0e9-11e4-97e0-58123b1dd14f.jpg)

Regards!~

**Comment by Rushor** [comment]
usually the normal option with flypoint nodes appears if you talk to these starting-zones.flymasters.

do you tried to talk at first first with the flymaster in undercity and later with anette williams?

i know that's not the blike way, but it would be nice to see, if the npc in general has the flymaster-options.

**Comment by Killyana** [comment]
The flymaster of Undercity must be discover once the player take the quest according to this: http://youtu.be/wSJWefnLZvg

**Comment by winterbreeze** [comment]
Hi. When I tried to talk to the Undercity's Michael Garrett Bat Handler, it says that "You don't know any flight locations connected to this one", then I went back to Anette Williams in Brill and it still doesn't show any location to fly to.

![michaelbat](https://cloud.githubusercontent.com/assets/11058171/6454281/aa366558-c182-11e4-9d91-40be83dc5b5d.jpg)

**Comment by Alastyr** [comment]
Try to execute this query:

<blackquote>UPDATE gossip_menu_option SET option_id=4, npc_option_npcflag=8192 WHERE menu_id=6944;</blackquote>

**Comment by winterbreeze** [comment]
Hi. Thanks for the help. The Flight Path is discovered for Anette Williams but nothing happens when I tried to click on the Flight Destination. I went back to Undercity and tried to Fly back to Brill through the Bat Handler Michael Garrett but the same problem, nothing happens when you click on the Flight Destination.

**Comment by danlapps** [comment]
Do you get any error message in console ?

**Comment by Killyana** [comment]
The fix from Alastyr can be pushed, the fly to Undercity is automatically discovered, and the player can take the fly without any problem (from and to Undercity)
