### ISSUE TITLE
Re-Logging any class with a pet causes a Fatal Exception error

### ISSUE THREAD

**Issue by tomm7** [TrinityCore/TrinityCore#14275]
rev. 9f27296bd226 +
DB: TDB 6.00
Re-Logging any class with a pet causes a Fatal Exception error in the client.  World server stays up, I have added the root log with everything after logging one of these classes.
http://pastebin.com/ZZk8UMWq
http://pastebin.com/YrWGjYHZ

**Comment by DDuarte** [comment]
That commit rev does not exist.

Duplicate of #14135
