### ISSUE TITLE
[6.1] playercreate_info doesnt load

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14281]
Rev.https://github.com/TrinityCore/TrinityCore/commit/7665c9ee555fde5e327d4f3bae95b1c3f030b83b
TDB 6.xx full updated
Character basic spells for 1lvl doesnt learned
![wowscrnshot_030215_130648](https://cloud.githubusercontent.com/assets/7688791/6439624/101092be-c0dd-11e4-8574-f51b105327e8.jpg)

**Comment by Aokromes** [comment]
All the `STATUS_UNHANDLED` at https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp#L145 will throw that error, no need to report them.
