### ISSUE TITLE
Assistance please - Mob Drop Rates

### ISSUE THREAD

**Issue by Jailin** [TrinityCore/TrinityCore#14286]
Can someone please assist me?

I want to set the drop rates of all mobs and bosses to drop all possible Rare, Epic, Legendary, Artifact and Referenced in their loot tables and ignore all Poor, Normal and Uncommon items. 

My current worldserv.conf is 

Rate.Drop.Item.Poor             = 0
Rate.Drop.Item.Normal           = 0
Rate.Drop.Item.Uncommon         = 0
Rate.Drop.Item.Rare             = 100
Rate.Drop.Item.Epic             = 100
Rate.Drop.Item.Legendary        = 100
Rate.Drop.Item.Artifact         = 100
Rate.Drop.Item.Referenced       = 100
Rate.Drop.Money                 = 10

and 

Rate.Drop.Item.ReferencedAmount = 2

but still do not get the correct drops. Mobs still drop poor quality items and not showing any greens or above.

Do i have to remove the poor items from the creature loot table?
Are there better settings?

Can some one please advise

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by pete318** [comment]
This http://www.trinitycore.org/f/forum is a forum though. Post the question there. :)
