### ISSUE TITLE
[6.1] Display names

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14280]
Rev.https://github.com/TrinityCore/TrinityCore/commit/7665c9ee555fde5e327d4f3bae95b1c3f030b83b
TDB 6.xx full updated
Character names are *unknown*
![wowscrnshot_030215_130305](https://cloud.githubusercontent.com/assets/7688791/6439565/8e18f490-c0dc-11e4-9105-933da46e1829.jpg)

**Comment by Aokromes** [comment]
All the `STATUS_UNHANDLED` at https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp#L145 will throw that error, no need to report them.
