### ISSUE TITLE
[3.3.5] [Quest: 13216] Battle at Valhalas: The Return of Sigrid Iceborn

### ISSUE THREAD

**Issue by alein** [TrinityCore/TrinityCore#14287]
Hello again.

I just tested this quest an appear to be not working.
When you accept the quest, the required [Sigrid Iceborn](http://www.wowhead.com/npc=31242) doesn't spawn and you can't finish the quest.

Quest Giver: [Geirrvif](http://www.wowhead.com/npc=31135)
Quest: [Battle at Valhalas: The Return of Sigrid Iceborn](http://www.wowhead.com/quest=13216)

TrinityCore rev. 517ad446e973 2015-02-09 08:32:35 +0100 (3.3.5 branch) (Unix, Release)
Database: TDB_full_335.57_2014_10_19 + updates to the core above.

Regards.

**Comment by alein** [comment]
Actually they're spawned but outside of the arena and are can not be target.

**Comment by Rushor** [comment]
once fixed in https://github.com/TrinityCore/TrinityCore/blob/98f98fa17fde4a1294b3e9227973ce5df70fbd6b/sql/old/3.3.5a/TDB52_to_TDB53_updates/world/2013_09_20_01_world_sai.sql - probably something was deleted

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `vehicleid`=60 WHERE `entry`=30159;
UPDATE `smart_scripts` SET `action_param2`=0 WHERE `entryorguid`=31242 AND `source_type`=0 AND `id`=14;

**Comment by alein** [comment]
I updated my core to:
TrinityCore rev. 003d67708b9a 2015-03-02 22:32:36 +0100 (3.3.5 branch) (Unix, Release)
Added all DB updates + fix from your comment and the while chain works fine ;)

Thanks.
