### ISSUE TITLE
[3.3.5] [Quest: 13663] The Black Knight's Orders

### ISSUE THREAD

**Issue by alein** [TrinityCore/TrinityCore#14288]
Hello again.
I just tested this quest an appear to be not working. I sow lots of closed tickets but they're very old not sure where to comment.
Quest Giver: [Crusader Rhydalla](http://www.wowhead.com/npc=33417)
Quest: [The Black Knight's Orders](http://www.wowhead.com/quest=13663)

The problems are several I think.
When you accept the quest, the quest giver doesn't provide you [Enchanted Bridle](http://www.wowhead.com/item=45083)
I try to add the item into my inventory (just for the test). When I use it, Black Knight's Gryphon are spawned (there is another one spawned there too), but no one of the both can be mounted.
Not sure how to test feature bugs in the quest.

Here is video too. Its from Cata but the quest I think is the same: https://www.youtube.com/watch?v=RJrwFyvhNbY

TrinityCore rev. 517ad446e973 2015-02-09 08:32:35 +0100 (3.3.5 branch) (Unix, Release)
Database: TDB_full_335.57_2014_10_19 + updates to the core above.

Regards.

**Comment by M0ra** [comment]
Confirmed
Rev. https://github.com/TrinityCore/TrinityCore/commit/003d67708b9a279da3d37e5ef06eb32ceab53964

DB 57

**Comment by Killyana** [comment]
General issue for some Vehicle ID https://github.com/TrinityCore/TrinityCore/issues/8195 This will probably never be fixed, you can use a different Vehicleid as a hackfix:
``` sql
UPDATE `creature_template` SET `vehicleid`=60 WHERE `entry`=33519;

**Comment by alein** [comment]
When I add this patch the Black Knight's Gryphon are spawned and I'm auto mauned on it.
He took me to near location and just drop me into the sea, but I don't get credit for taking the Black Knight's Gryphon.

What about quest item Enchanted Bridle. The quest giver doesn't provide the item.
Also the gameobjects that I need to loot are targetable only in gm mod (I try it to loot them in GM mod but they're empty)

**Comment by Killyana** [comment]
I don't have this issues, I just completed the quest without any problem, except the Gryphon who droped me on the sea.

**Comment by alein** [comment]
From where did you get the quest item? I didn't add the quest with command, I go to the npc and accept the quest.
And you can loot the game objects?

**Comment by Killyana** [comment]
The quest is "The Black Knight's Orders" NOT "The Black Knight of Westfall?"

**Comment by alein** [comment]
Omg, I'm blind idiot. I apologize.

**Comment by alein** [comment]
Its work just fine. Tested with this "hack-fix" ;)
