### ISSUE TITLE
3.3.5 Many NPC's with feet ankle deep in ground

### ISSUE THREAD

**Issue by Ajaxhore** [TrinityCore/TrinityCore#14283]
Rev. 194fda8a4ed47d968fc3d436ac9b7c8f436eb5b2
(Doesent matter, it happens in all revs. of 3.3.5 for me.)
Clean fresh build with no addons or anything.

Ive had this problem for a long time.
Many NPC's are standing with their feet ankle deep in the ground.
This is a problem in all clean 3.3.5 builds for me for a long time.
Ive tried remaking all maps without luck.
Ive tried the hard way of possesing jumping and unpossesing NPC's to make them stand correctly on the ground.
But if they die, they respawn with feet in the ground Again :(
Is there an easy fix for this problem?
Is it the client i extract maps from thats something wrong with, or is this a general problem?

**Comment by Aokromes** [comment]
#8500

**Comment by tkrokli** [comment]
@Ajaxhore : as you see, this issue already exists and is confirmed & still not fixed. You can add a "confirm" comment (add your core revision hash) in the existing issue, if you like.
