### ISSUE TITLE
[3.3.5][Quest][Bug] Take Down Tethyr! (autocompleted)

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14294]
TrinityCore rev. 5e7d4a44e0d6 2015-03-03 23:09:42 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.57 + all updates. No addons. Test character is new and the only character on this core.
Windows 10 Enterprise Technical Preview, Build 9926.

Level up an alliance character to level 35, go to Theramore Isle and get the quest http://www.wowwiki.com/Quest:This_Old_Lighthouse from Sergeant Amelyn (http://www.wowhead.com/npc=23835/sergeant-amelyn), go to the east side of the docks and swim east to the lighthouse. Follow the quest chain to Pat Nagle at Pat's Landing and back again to the Theramore docks, hand in the Q "Oh, It's Real" to Major Mills (http://www.wowhead.com/npc=23905/major-mills). Now this quest should be available to you:

**Take Down Tethyr!** (http://www.wowhead.com/quest=11198/deprecated-take-down-tethyr) (3.3.5a version)

How it is supposed to work: The event should start. See also the YouTube video below:

[![Take Down Tethyr! - Quest - World of Warcraft](http://img.youtube.com/vi/9bouANygWgs/0.jpg)](http://www.youtube.com/watch?v=9bouANygWgs)

What happens instead: Quest autocompletes on Major Mills the same second as you take the quest.

The only source reference related to this quest is the old update TDB49 to TDB50 by @LeGuyBrush:
https://github.com/TrinityCore/TrinityCore/blob/98f98fa17fde4a1294b3e9227973ce5df70fbd6b/sql/old/3.3.5a/TDB49_to_TDB50_updates/world/2012_11_24_04_world_sai.sql :
```sql
-- Add creature_text entry for the shout
DELETE FROM `creature_text` WHERE `entry`=23905;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`comment`) VALUES
(23905,0,0,'Keep Moving!',14,7,100,0,0,0, 'Major Mills');
-- Add Smart AI for the quest.
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (23905) AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2390500) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(23905,0,0,0,19,1,100,0,11198,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'Major Mills - On Quest Accept - Say text'),
(23905,0,1,0,19,1,100,0,11198,0,0,0,80,2390500,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Major Mills: On quest accept call main script'),
-- After 5 seconds: Summon Guards
(2390500,9,0,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3904.77,-4635.09,9.62735,5.49334, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,1,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3856.59,-4622.45,9.24753,3.87856, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,2,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3917.6,-4648.53,9.32604,5.56795, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,3,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3890.48,-4620.7,9.55527,4.99383, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,4,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3865.94,-4617.2,9.26262,4.16523, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,5,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3834.8,-4645.41,9.25827,3.61152, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,6,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3826.61,-4655.32,9.21484,3.13243, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,7,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3830.76,-4673.74,9.50962,2.70832, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,8,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3843.65,-4687.59,9.6436,2.43735, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,9,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3858.49,-4703.49,9.17411,2.33525, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,10,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3851.97,-4697.24,9.36834,2.33525, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,11,0,1,0,100,0,5000,5000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3924.35,-4656.55,9.15409,5.80749, 'Take Down Tethyr: Summon Theramore Marksman'),
-- After 8 seconds Summon Tethyr
(2390500,9,12,0,1,0,100,0,8000,8000,0,0,12,23900,1,900000,0,0,0,8,0,0,0,-3891.03,-4671.17,-1.52,0.74, 'Take Down Tethyr: Summon Tethyr');
```
I hardly ever play alliance characters myself, so I have no idea of how long this quest and the event has been disabled. I only notice issues like this when asked to test by other players. (Thanks to Spearwolf for informing me about this issue.)

**Comment by danlapps** [comment]
Could probably be hack fixed using special flag 2 as temp fix.

No idea how to implement those however.

**Comment by tkrokli** [comment]
> Could probably be hack fixed using special flag 2 as temp fix.

OK, I may need a tip from someone on how to check that, perhaps the event is not scripted.

**Comment by Rushor** [comment]
https://github.com/scriptdev2/scriptdev2/blob/master/scripts/kalimdor/dustwallow_marsh.cpp#L822

**Comment by Kittnz** [comment]
This can be implemented.

**Comment by tkrokli** [comment]
Oh, OK. I see. So the event exists in scriptdev2, but not in TC source yet, if I understand it correctly?

**Comment by Rushor** [comment]
completely different code, just a note for the one, who will convert ist to an sai-script :D

**Comment by tkrokli** [comment]
OK, so SAI is still the way to go (I should have known). Will it be necessary to use sniffs for waypoints?

**Comment by dr-j** [comment]
to remove auto complete you add special flags 2 which marks quest as only been completable via a external event (this is needed if quest has no requirednpcsorgos or requireditems to complete quest as otherwise such quests are completed as soon as taken)

then in the sai at point where quest needs to be completed use action 15 (callareaexploredoreventhappens) with param1 the id of the quest to be completed (this quest) and target player either using invoker if action will be called by an event which requires player interaction or stored target otherwise.

About waypoints sniffs should be used, even though orignal quest was removed have previously found most of northern (at least) dustwallow marsh is mostly unchanged still on retail there is still a version of this quest available on retail and it is possible that wp from retail are still valid for this on 3.3.5 as are for other quests in northern dustwallow.

**Comment by dr-j** [comment]
https://www.youtube.com/watch?v=U1Q-ScilcZ0
https://www.youtube.com/watch?v=vSd2RgWqPBg

**Comment by Killyana** [comment]
WIP
```
ET @Cannon:= 186432;
SET @Tethyr:=23899;
SET @Marksman:=23900; -- 42579
SET @Triggger:=23907;
SET @Blast:=42578;

UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry` IN (@Tethyr, 23905, @Marksman, @Triggger);
UPDATE `creature_template` SET `InhabitType`=2 WHERE `entry` IN (@Tethyr);
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry`=@Cannon;

DELETE FROM `creature_text` WHERE `entry`=23905;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`comment`, `BroadcastTextID`) VALUES
(23905,0,0,'Marksmen, form up and take your positions!',14,0,100,0,0,0, 'Major Mills', 22447),
(23905,1,0,'Prepare to fire upon my command! Ready, aim...',14,0,100,0,0,0, 'Major Mills', 22448),
(23905,2,0,'FIRE AT WILL!',14,0,100,0,0,0, 'Major Mills', 22449),
(23905,3,0,'We did it! We''ve defeated Tethyr!',14,0,100,0,0,0, 'Major Mills', 22633);

DELETE FROM `waypoints` WHERE `entry`=@Tethyr;
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
(@Tethyr,1, -3882.588379,-4670.275391,-1.823548,'Tethyr');
UPDATE `quest_template` SET `SpecialFlags`=2 WHERE `Id`=11198;

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Cannon) AND `source_type`=1;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Marksman) AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (23905) AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2390500) AND `source_type`=9;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Triggger*100) AND `source_type`=9;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Tethyr) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(23905,0,0,0,19,0,100,0,11198,0,0,0,80,2390500,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Major Mills: On quest accept call main script'),
(2390500,9,0,0,0,0,100,0,2000,2000,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Take Down Tethyr: Talk'),
(2390500,9,1,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3904.77,-4635.09,9.62735,5.49334, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,2,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3856.59,-4622.45,9.24753,3.87856, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,3,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3917.6,-4648.53,9.32604,5.56795, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,4,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3890.48,-4620.7,9.55527,4.99383, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,5,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3865.94,-4617.2,9.26262,4.16523, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,6,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3834.8,-4645.41,9.25827,3.61152, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,7,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3826.61,-4655.32,9.21484,3.13243, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,8,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3830.76,-4673.74,9.50962,2.70832, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,9,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3843.65,-4687.59,9.6436,2.43735, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,10,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3858.49,-4703.49,9.17411,2.33525, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,11,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3851.97,-4697.24,9.36834,2.33525, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,12,0,0,0,100,0,0,0,0,0,12,@Marksman,1,900000,0,0,0,8,0,0,0,-3924.35,-4656.55,9.15409,5.80749, 'Take Down Tethyr: Summon Theramore Marksman'),
(2390500,9,13,0,0,0,100,0,0,0,0,0,12,@Tethyr,1,900000,0,0,0,8,0,0,0,-3897.365479, -4750.632813, -1.719010, 1.791049, 'Take Down Tethyr: Summon Tethyr'),
(2390500,9,14,0,0,0,100,0,4000,4000,0,0,106,16,0,0,0,0,0,14,10824,@Cannon,0,0, 0, 0, 0, 'Take Down Tethyr: Remove Flag from GO'),
(2390500,9,15,0,0,0,100,0,0,0,0,0,106,16,0,0,0,0,0,14,10227,@Cannon,0,0, 0, 0, 0, 'Take Down Tethyr: Remove Flag from GO'),
(2390500,9,16,0,0,0,100,0,0,0,0,0,106,16,0,0,0,0,0,14,11186,@Cannon,0,0, 0, 0, 0, 'Take Down Tethyr: Remove Flag from GO'),
(2390500,9,17,0,0,0,100,0,2000,2000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Take Down Tethyr: Talk'),
(2390500,9,18,0,0,0,100,0,4000,4000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Take Down Tethyr: Talk'),

(@Tethyr,0,0,0,25,0,100,0,0,0,0,0,53,0,@Tethyr,0,0,0,0,1,0,0,0,0,0,0,0,'Tethyr - Just Summoned - Start wp'),
(@Tethyr,0,1,0,40,0,100,0,1,@Tethyr,0,0,101,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Tethyr - Waypoint reached - Set home position'),
(@Tethyr,0,2,0,0,0,100,0,7000,7000,8000,8000,11,42584,0,0,0,0,0,5,0,0,0,0,0,0,0,'Tethyr - Occ - Cast'),
(@Tethyr,0,3,0,0,0,100,0,9000,9000,6000,6000,11,42574,0,0,0,0,0,5,0,0,0,0,0,0,0,'Tethyr - Occ - Cast'),

(@Marksman,0,0,0,25,0,100,0,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Marksman - Just Summoned - React passif'),
(@Marksman,0,1,0,1,0,100,0,15000,15000,3000,3000,11,42579,0,0,0,0,0,19,@Tethyr,50,0,0,0,0,0,'Tethyr - Occ - Cast'),
(@Marksman,0,2,0,0,0,100,0,3000,3000,3000,3000,11,42579,0,0,0,0,0,19,@Tethyr,50,0,0,0,0,0,'Tethyr - IC - Cast'),

(@Cannon,1,0,0,73,0,100,0,0,0,0,0,80,@Triggger*100,0,0,0,0,0,19,@Triggger,10,0,0,0,0,0, 'Cannon - On spell click - actionlist'),
(@Triggger*100,9,0,0,0,0,100,0,0,0,0,0,11,@Blast,0,0,0,0,0,19,@Tethyr,50,0,0,0,0,0, '@Triggger - Action list - cast');

**Comment by Killyana** [comment]
I need sniffs for wowhead.com/spell=42578 and the spell used to complete the quest, impossible to complete the script without this.

**Comment by tkrokli** [comment]
OK, I guess that since  www.wowhead.com/spell=42578 has got the flag "Cannot be used while shapeshifted" it will not work as intended if people used to be able to trigger the spell while shapeshifted. Then again, maybe it is different that the cannon uses the spell than if characters had got the spell. @Killyana , minor detail: add the missing 'S' at the top of the script (I guess you know it already) :smirk_cat:

**Comment by Rushor** [comment]
the current quest on retail if someone wants to sniff: http://www.wowhead.com/quest=27222/take-down-tethyr

**Comment by Killyana** [comment]
Script Updated, only quest credit is missing.

**Comment by tkrokli** [comment]
> Script Updated, only quest credit is missing.

Awesome! Excellent progress! :+1:

**Comment by Killyana** [comment]
Script Updated: Final version fro me, quest credit added, and player have 3 min to kill Tethyr before the quest fail.

**Comment by tkrokli** [comment]
Hm, sounds like I should test it, then. :smirk_cat: :game_die: :video_game: :computer:

**Comment by tkrokli** [comment]
TrinityCore rev. 356f3b6bc583 2015-03-08 07:47:17 +0100 (3.3.5 branch) (Win64, Release)

So... I have tested this event 5 times now with a level 33 human rogue character. At the first try, Tethyr didn't seem to move into the harbor to be within firing range, only stayed at the end of the pier and killed off the nearest marksman (woman). The following 2 attempts ended in me running out of time because I didn't use any speed buffs to move quickly enough between the cannons. (I also had to test switching between lowest graphics setting and highest graphic settings to find out if the first unsuccessful attempt had anything to do with very low sight range (shortest range/lowest game settings).

To be able to finish this quest, I had to learn a level 40 mount, then mount instantly (assign attack button 1 to mount) and ride on each time I had right-clicked (fired) a cannon. Even so, it felt like the Theramore Marksmen did most of the job. (Maybe it had something to do with the low impact of the visuals from firing the 3 fixed cannons, I don't know.) I could also wish for real ship cannon GOs instead of mortars, but I suspect the GOs are the ones Blizzard chose to use, so I'm on my own if I want different weapon visuals.

I just barely managed to finish off Tethyr in time, but at least I did it, even if cheating by using a DK mount or setting the character speed to 4x. Maybe it is because I'm not a good player, since even with the 4x speed I barely finished it in 2 minutes 50 seconds (even less time left when using the level 40 mount). I can understand why someone in #trinity would say that TC source is like Blizzard on hard mode. It certainly felt that difficult to me. I don't know if the marksmen should fade so quickly at the end of the event. Maybe someone who has actually done the quest online on a live Blizzard server can tell me.

Conclusion:
**This script works, even if you may have to restart it a couple of times in case of bugged visuals.**

**Comment by danlapps** [comment]
I have a sniff of the retail quest if someone needs it for some confirmation

**Comment by Nyeriah** [comment]
Did you manage to get around the worldstate updates too? I think whenever a guard dies the counter goes down, it's sent to every player in the area (regardless of their quest status)

**Comment by tkrokli** [comment]
@Nyeriah : is your question directed to @Killyana, @danlapps or me?

**Comment by Nyeriah** [comment]
Killyana

**Comment by Killyana** [comment]
@danlapps Yes please post your sniffs here http://www.trinitycore.org/f/forum/13-wdbadbsniffs/ I need them to make the script blizzlike.
@tkrokli I changed the timer for 6 min, 3min seems too short.
@Nyeriah I cannot find any Sai mechanism to count the number of killed npcs (in this case if the 12 Marksmans dies the quest fail on retail)

**Comment by tkrokli** [comment]
> I changed the timer for 6 min, 3min seems too short, and for me Tethyr never fail to start his waypoint.

Sounds good, I think the quest was nerfed sometime between 2.3.0 and 3.3.5 according to comments.

**Comment by danlapps** [comment]
At work for 4 more hours. Will post sniff when I get home :)

**Comment by Killyana** [comment]
Script updated: Chrono removed and replaced by a counter, when 5 Marksmans dies the quest fail, the player have a lot of time to do the quest as in retail. Also every player having the quest
on the shore is affected by the battle, if the quest fails it will fail for all the players and the same thing if the quest is completed.

**Comment by tkrokli** [comment]
>  [ .. ] if the quest fails it will fail for all the players and the same thing if the quest is completed.

I suppose you mean "and the quest will _complete_ for all the players when the quest is completed.", but OK. Looks like you have improved on the code, so I should test it when I'm done testing 3 other issues. :smirk_cat:

**Comment by tkrokli** [comment]
I tested the script https://github.com/TrinityCore/TrinityCore/issues/14294#issuecomment-77602284 again just now and it works completely OK. I can't say for sure if I had to restart the server and the game client because of issues in my own software setup, but on my second quest attempt, Tethyr entered the harbor basin so he could be fired upon by all 3 cannons on the piers.

There were no important issues during the event, some of the effect visuals did not show every time on my screen, but that could be caused by my addons or software setup.

The event proceeded as expected, so I don't see any reason to postpone committing the script to the main TC source, except for that it would have been nice to have a few more users testing this script and write a feedback on their experiences.

**Comment by Maxxgold** [comment]
TrinityCore rev. f6aca899d2ed 2015-09-19 01:32:07 -0400 (3.3.5 branch) (Win64, Release) (worldserver-daemon)

This quest does not work. I just tested it and after killing Tethyr no credit was given. It did take a while because Tethyr doesn't move in far enough in to the harbor to target him with the middle cannon.

After abandoning the quest from the quest log it could not be taken again unless you use gm and add quest.

**Comment by Killyana** [comment]
The only problem is that the npc spawn a little bit far in an inactive grid, for this reason it will take time to reach the last wp, and if the npc is damaged before that it will not continue the wp, but still the quest can be done, and the quest giver reset the npcflag correctly, If you want you can make the kraken active on spawn to fix this issue..
