### ISSUE TITLE
6.1.0 map extractor on US client

### ISSUE THREAD

**Issue by firelook** [TrinityCore/TrinityCore#14295]
I have some few problems only with dbc:
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive fo
r locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for l
ocale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive
for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for local
e enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale enUS: FIL
E_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale enUS:
 FILE_NOT_FOUND
Extracted 514 files

=> at the end I have at least problems with
Some required *.db2 files (2 from 29) not found or not compatible:
./Data/dbc/ItemExtendedCost.db2 exists, and has 29 field(s) (expected 30). Extracted file might be from wrong client version.
./Data/dbc/TaxiNodes.db2 exists, and has 13 field(s) (expected 12). Extracted file might be from wrong client version.
=> I have tryed to use 6.0 dbc files (in case of ;) )

**Comment by tkrokli** [comment]
Solution: Look in your newly created DBC folder, there should be a folder named 'enUS'.
Move all the files in that folder up a level to your DBC folder and it will work again.

**Comment by DDuarte** [comment]
You need  6.1 dbcs, you can ignore file_not_found errors of the extractor.

**Comment by firelook** [comment]
thanks, I take your suggestion for next time ;) (hope not)
I tryed to bypass these 4 files missing : 
Some required *.dbc files (4 from 147) not found or not compatible:
./Data/dbc/AreaGroup.dbc
./Data/dbc/CurrencyTypes.dbc
./Data/dbc/SoundEntries.dbc
./Data/dbc/gtOCTClassCombatRatingScalar.dbc

**Comment by tkrokli** [comment]
1. Make sure your game client is updated. 2. Update your source, compile again with new tools. 3. Run Mapextractor.exe again to create new DBC (ignore the maps folder).

**Comment by firelook** [comment]
Thanks
1/ I can connect to an official server
2/ As of today (this morning)
3/ done => but not enough some files are missing
(same as 6.0 => some people put the files missing, I have request on the official web server to see if I am the only one)
