### ISSUE TITLE
Map & DBC Extractor

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#14293]
Map & DBC Extractor
===================
opened casc storage 'F:/Program Files (x86)\World of Warcraft\Data'
Locale none not installed.
Detected client build 19634 for locale enUS

Extracting dbc/db2 files...
Unable to open file DBFilesClient\DeclinedWord in the archive for locale enUS: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale enUS:
FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale enUS: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive fo
r locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for l
ocale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive
for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for local
e enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale enUS: FIL
E_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale enUS:
 FILE_NOT_FOUND
Extracted 514 files

Locale koKR not installed.
Locale unknown not installed.
Locale frFR not installed.
Detected client build 19634 for locale deDE

Extracting dbc/db2 files...
Unable to open file DBFilesClient\DeclinedWord in the archive for locale deDE: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases in the archive for locale de
DE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale deDE:
FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale deDE:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale d
eDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for
 locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for
 locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for
 locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for
 locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for
 locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale d
eDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale
 deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale deDE: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale d
eDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale d
eDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive fo
r locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale deDE
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale deD
E: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale deD
E: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale de
DE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for loc
ale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for l
ocale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive
for locale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for loc
ale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for lo
cale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale deD
E: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale deDE:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale deDE
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale de
DE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale deDE:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale deDE
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale deD
E: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for local
e deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale d
eDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale
deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale
 deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale deDE: FIL
E_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale deDE
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for loc
ale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for loca
le deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for lo
cale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for lo
cale deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale
 deDE: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale deDE:
 FILE_NOT_FOUND
Extracted 514 files

The Detected Build is INVALID i use 19702 !!!!! https://github.com/TrinityCore/TrinityCore/commit/3db001e897de9f8b3bc307c42d1e1200f2169503 2 houres before updated but not fixxed o0 ... Nice man !

**Comment by Shauren** [comment]
Not a bug. This is all working as intended

**Comment by Xunil1337** [comment]
hmmm working jup... i see error my eyes are blind ?! .... clear your work ...

**Comment by AlbertoMMI** [comment]
GitExtensions report:
"C:\Program Files (x86)\Git\bin\git.exe" pull --progress "origin" +refs/heads/6.x:refs/remotes/origin/6.x
remote: Total 700 (delta 428), reused 225 (delta 225), pack-reused 196[K
From https://github.com/TrinityCore/TrinityCore
   9747036..ebf9b59  6.x        -> origin/6.x
Updating 9747036..ebf9b59

CMake report:
Detected 32-bit platform
MSVC: Enabled large address awareness
MSVC: Enabled SSE2 support
MSVC: Disabled Safe Exception Handlers for debug builds
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files (x86)/MySQL/MySQL Server 5.6/lib/libmysql.lib
Found MySQL headers: C:/Program Files (x86)/MySQL/MySQL Server 5.6/include
Found MySQL executable: C:/Program Files (x86)/MySQL/MySQL Server 5.6/bin/mysql.exe
Found git binary : C:/Program Files (x86)/Git/cmd/git.exe
* TrinityCore revision   : ebf9b59aaeeb 2016-04-02 20:54:06 +0200 (6.x branch)
* Install core to        : C:/Program Files (x86)/CMake
* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : Yes
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes - "hierarchical"
* Use GIT revision hash  : Yes
Boost version: 1.59.0
Found the following Boost libraries:
  system
  filesystem
  thread
  program_options
  iostreams
  regex
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Found OpenSSL library: optimized;C:/OpenSSL-Win32/lib/VC/ssleay32MD.lib;C:/OpenSSL-Win32/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win32/lib/VC/ssleay32MDd.lib;C:/OpenSSL-Win32/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win32/include
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: OutdoorPvP
  -> Prepared: EasternKingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Maelstrom
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE
Configuring done
Generating done

MapExtractor report:
D:\World of Warcraft>mapextractor
Map & DBC Extractor
===================
error opening casc storage 'D:/World of Warcraft\Data' locale enUS: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale koKR: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale frFR: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale deDE: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale zhCN: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale zhTW: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale esES: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale esMX: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale ruRU: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale ptBR: BAD_FORMAT
error opening casc storage 'D:/World of Warcraft\Data' locale itIT: BAD_FORMAT
No locales detected

WoW 6.2.4.21355 enUS, esES, sources updated today, cmake 3.0.0, boost c++ 1.5.9, VS express 2010, 2012, 2013, 2015 updated, W7 x64 SP1 updated, client starter edition 100% downloaded from battle.net desktop program... why don't work? what's wrong?

**Comment by tkrokli** [comment]
@AlbertoMMI : One of the Windows requirements you have not met is this one: `CMake ≥ 3.3.2`
Make sure that your CMake version is at least version **3.3.2**
Current available version on https://cmake.org/download/ is **3.5.1**

**Comment by Vincent-Michael** [comment]
Fixed in 77761e819506075b28c1b4eaf3fb295cc544c838 @AlbertoMMI

**Comment by AlbertoMMI** [comment]
Thank you @tkrokli.
@Vicent-Michael, how can i put these files in my sources? ... sorry for my english, i'm spanish :s
