### ISSUE TITLE
[3.3.5]Gyll Gryphon Master bug.

### ISSUE THREAD

**Issue by Alanzindh** [TrinityCore/TrinityCore#14290]
Gyll gryphon master is not an NPC but a mob and is attacking.

TrinityCore rev. 5e7d4a44e0d6b92da8ba68a00be00c530a72c873  (3.3.5 branch) (Windowns, Release)
Database: TDB_full_335.57_2014_10_19 + all updates to the core above.

**Comment by Aokromes** [comment]
your engrish is broken as you ticket is.

**Comment by DJScias** [comment]
NPC and Mob are synonyms of each other.

**Comment by Alanzindh** [comment]
Sorry my bad English

**Comment by DDuarte** [comment]
Read http://collab.kpsn.org/display/tc/The+Issuetracker+and+You and edit your ticket.

**Comment by Alanzindh** [comment]
updated

**Comment by DDuarte** [comment]
You didn't read it. You do not describe the bug nor how it should be.

> Did I include the steps to reproduce the problem?
> Did I explain what is wrong and what is the expected behavior/output?

**Comment by Alanzindh** [comment]
updated

**Comment by Aokromes** [comment]
I am sure you are trying to use opposite faction taxi master.

**Comment by danlapps** [comment]
Lets try with example

Gyll Gryphon Master, http://www.wowhead.com/npc=2859/gyll seems bugged.

What should happens : He should be a friendly flight master

What is happenning now : He is hostile and attack players.

**Comment by Aokromes** [comment]
http://i.imgur.com/Lj0nBzV.jpg
