### ISSUE TITLE
crash auction

### ISSUE THREAD

**Issue by denkka77** [TrinityCore/TrinityCore#14296]
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  002295E8 01:000E85E8 D:\Debug Realm\worldserver.exe

Registers:
EAX:00000003
EBX:22E2F6A0
ECX:4616CFA8
EDX:DDDDDDDD
ESI:318CE4C0
EDI:318CE270
CS:EIP:0023:002295E8
SS:ESP:002B:318CD254  EBP:318CE270
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010293

Call stack:
Address   Frame     Function      SourceFile
002295E8  00000000  Object::GetUInt32Value+F8
00228698  00000000  Object::GetEntry+18
00ACF7F6  00000000  Item::GetTemplate+16
00B17DCA  00000000  Spell::TakeCastItem+5A
00B1BDB5  00000000  Spell::handle_immediate+265
00B16C60  00000000  Spell::cast+5F0
00B162BB  00000000  Spell::update+1FB
00B28FF5  00000000  SpellEvent::Execute+45
00CE9C7F  00000000  EventProcessor::Update+1CF
0095ABC2  00000000  Unit::Update+42
0024DE46  00000000  Player::Update+236
009D81C3  00000000  Map::Update+1D3
00C0394B  00000000  MapUpdateRequest::call+2B
00CEEE84  00000000  DelayExecutor::svc+74
6CD18F07  00000000  ACE_Task_Base::svc_run+47
6CD1A10D  00000000  ACE_Thread_Adapter::invoke_i+DD
6CD19F73  00000000  ACE_Thread_Adapter::invoke+D3
6CC0FAFA  00000000  ace_thread_adapter+2A
6CE8B811  00000000  _beginthreadex+1A1
6CE8B9E1  00000000  _endthreadex+171
753D336A  00000000  BaseThreadInitThunk+12
77909F72  00000000  RtlInitializeExceptionChain+63
77909F45  00000000  RtlInitializeExceptionChain+36

--------------------------------------------------

this	0x4616cfa8 {m_objectType=56797 m_objectTypeId=-572662307 m_updateFlag=56797 ...}	Object *

**Comment by danlapps** [comment]
Who does what doing what with whom and where ?

How to reproduce ?

**Comment by Aokromes** [comment]
6CD18F07 00000000 ACE_Task_Base::svc_run+47
6CD1A10D 00000000 ACE_Thread_Adapter::invoke_i+DD
6CD19F73 00000000 ACE_Thread_Adapter::invoke+D3
