### ISSUE TITLE
[6.1] Fly

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14308]
Rev. https://github.com/TrinityCore/TrinityCore/commit/38ba7ab08ede208f60c51759f5e107359f01d148
TDB 6.00 - full updated

Cant fly anywhere, all learned. All mounts only runs on ground.

**Comment by gigatotem** [comment]
When you mean 'can't fly anywhere' do you mean you can't fly anywhere in Draenor or Azeroth/Northrend/Outland/Pandaria also?

If Draenor, We can't even fly ourselves on retail WoW in Draenor.

**Comment by Aokromes** [comment]
I vote missing opcodes.

**Comment by F03SD** [comment]
yeah , it opcode CMSG_MOVE_SET_FLY and etc.

**Comment by Aokromes** [comment]
Every opcode handled with DEFINE_OPCODE_HANDLER_OLD below https://github.com/TrinityCore/TrinityCore/blob/56186319bdd41dd26b6cc14f84e6e41eef5d953b/src/server/game/Server/Protocol/Opcodes.cpp#L144 is not handled, there's no need to report them
