### ISSUE TITLE
[335] [DB] Missing update - King Jotum Vehicule

### ISSUE THREAD

**Issue by danlapps** [TrinityCore/TrinityCore#14301]
runtime error Script named 'npc_king_jokkum_vehicle' does not have a script name assigned in database.

Fix :present in some old file, seems to have been left out of new base file.
```SQL
UPDATE `creature_template` SET `ScriptName`="npc_king_jokkum_vehicle" WHERE `entry`=30331;
```

**Comment by Aokromes** [comment]
Nope, c++ needs to be removed. also duplicate of #13707
