### ISSUE TITLE
[6.1] Teleporting

### ISSUE THREAD

**Issue by Naxxmare** [TrinityCore/TrinityCore#14307]
Rev. https://github.com/TrinityCore/TrinityCore/commit/38ba7ab08ede208f60c51759f5e107359f01d148
TDB 6.00 - full updated

.tele works fine, but when load screen have dead character and stuck client, only alt-f4 helps.
Loading screen have first location picture of your race, whatever you are teleporting
Only after reloggin - screen and character is on correct place
![wowscrnshot_030715_211648](https://cloud.githubusercontent.com/assets/7688791/6542869/eacd79e0-c50f-11e4-9e40-3000d17c715b.jpg)

**Comment by MitchesD** [comment]
missing teleport packets

**Comment by Aokromes** [comment]
Every opcode handled with DEFINE_OPCODE_HANDLER_OLD below https://github.com/TrinityCore/TrinityCore/blob/56186319bdd41dd26b6cc14f84e6e41eef5d953b/src/server/game/Server/Protocol/Opcodes.cpp#L144 is not handled, there's no need to report them
