### ISSUE TITLE
[Instance] Sindragosa Ice Tomb AOE Damage

### ISSUE THREAD

**Issue by D4R4** [TrinityCore/TrinityCore#14304]
This is an attempt to revive an old issue which was closed by mistake and still persists,
the original issue being here: #7808 

a short discription is: when struck the Beaconed target should deal AOE damage in 10 yards to other players (and other beaconed targets) but atm the damage is only dealt to the player (spell has IGNORE_LOS flag)

this tiny issue causes the entire phase two of the Sindragosa encounter to be completly different from retail with Beaconed targets stacking on each other and making the encouter real easy,

rev. 7694c917f8b6858845bc5a8f854331b9327c5c9e
DB: Latest TDB

**Comment by Aokromes** [comment]
#7808 is still open.
