### ISSUE TITLE
[3.3.5] Generic bug of vehicles

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14310]
Core: https://github.com/TrinityCore/TrinityCore/commit/5e7d4a44e0d6b92da8ba68a00be00c530a72c873
DB: TDB 11.57

For etc: Battleground Demolisher in sota, u can sit like passenger into vechicle and attack players from there

Bug: Other player can't target player as passenger. When the hunter sit as passenger slot he is doing so much damage, and no one can stop him

http://prntscr.com/6dy7sa

http://prntscr.com/6dy8ax
##

**Comment by D4R4** [comment]
should passangers be able to attack players or not? how is it like in Retail?

**Comment by dr-j** [comment]
On retail passengers can not mount demolishers since the passenger seats where removed from these vehicles when Catacylsm came out.

Also  http://www.wowwiki.com/Strand_of_the_Ancients says 'It can hold up to 3 passengers, including the driver. Passengers are exposed and can be targeted individually. However, the side passengers can cast while the vehicle is moving if they're in it. '

**Comment by Kittnz** [comment]
That is correct!

**Comment by Mack36** [comment]
Problem is that passengers are not selectable to enemies, so enemies can't hurt them. Also, passengers have vehicle gear scale aura so their dmg and hp are increased. Don't know if it's a bug or intended.

**Comment by Frytiks** [comment]
@Mack36 ye scaling aura is problem too. High bug cause arcane mage with scaling doing on 1 spell 15k damage

**Comment by Mack36** [comment]
Here's a temp & hacky solution)
https://gist.github.com/Mack36/60020c6b583d2499b4c6

**Comment by Frytiks** [comment]
Thanks, i will try

**Comment by Frytiks** [comment]
I try it, now i can target but when i try to grab player, nothing is done.

**Comment by D4R4** [comment]
@Frytiks should they be grabbed out of their seats?

**Comment by Frytiks** [comment]
Ye i think seat players yes, but driver no

**Comment by Aokromes** [comment]
Ofc you can't grab driver from vehicle.

**Comment by sirikfoll** [comment]
any ideas on this Gear Scaling issue?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
