### ISSUE TITLE
6.0.3 SMSG_REDIRECT_CLIENT

### ISSUE THREAD

**Issue by brecky** [TrinityCore/TrinityCore#14314]
Compile Core 6.0.3
Pached Client
Start Client 6.0.3 19342
Login the server

After Client send packet CMSG_PLAYER_LOGIN end server send SMSG_REDIRECT_CLIENT, Client disconeckt,
What is problem, where look data strukture use IDA?

sorry my bad english

**Comment by DDuarte** [comment]
We are not 6.0.3 version.
