### ISSUE TITLE
Mobs Fail

### ISSUE THREAD

**Issue by TheSinglePlayer** [TrinityCore/TrinityCore#14318]
Today i updated my core and now when you attack mob in icecrown they falls through the ground
can someone help me to fix this? ;;)

**Comment by Killyana** [comment]
You're core revision, and the npc id are required.

**Comment by TheSinglePlayer** [comment]
a tutorial somewhere I can find? I do not really understand :(

**Comment by Killyana** [comment]
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
And the npcs concerned by this issue.

**Comment by TheSinglePlayer** [comment]
tnks i will try :D

**Comment by tkrokli** [comment]
We are trying to help you, but we need you to post important information. Read and follow these instructions: **http://collab.kpsn.org/display/tc/The+Issuetracker+and+You**

**Comment by TheSinglePlayer** [comment]
version database: TDB 335.57 version core: TrinityCore rev. 5e7d4a44e0d6 2015-03-03 23:09:42 +0100 (3.3.5 branch) (Unix, Release) operating system: Ubuntu 12.04 x64

**Comment by TheSinglePlayer** [comment]
Today i updated my core and now when attack mob in icecrown they falls through the ground can someone help me to fix this? ;;) i change all sql dates reinstalll server and whenever I enter the instance or outside it, give atack and they disappear

**Comment by Killyana** [comment]
Which mobs give some examples.

**Comment by TheSinglePlayer** [comment]
instances and raid bosses  all and mobs of people besides

**Comment by TheSinglePlayer** [comment]
you have messenger ? or facebook ? for help !! pls :P   yahoo : the_config and fb https://www.facebook.com/constantin.bogdan.77 for talk :D tnks !!!!

**Comment by TheSinglePlayer** [comment]
I do not know much, except to play;) :(

**Comment by Frytiks** [comment]
In worldserver.conf have you vmaps on ?

**Comment by TheSinglePlayer** [comment]
vmap.enableLOS    = 0
vmap.enableHeight = 0
vmap.enableIndoorCheck = 0

all is Disabled

**Comment by Aokromes** [comment]
Enable all.

**Comment by TheSinglePlayer** [comment]
Now go, thanks so much help, I struggled for 2 weeks to do this thing mobi not to fall under the map
