### ISSUE TITLE
no syntax checking

### ISSUE THREAD

**Issue by M0ra** [TrinityCore/TrinityCore#14311]
when you enter the game world and the password is set for example: qwerQWER
if you enter: qwerqwer, you just enter the game world

no syntax checking

DB 57 + updates
rev. 999a5ffa642c27dc3566664cf0e5b44dffafb1b7 3.3.5

sorry for bad english

**Comment by Rochet2** [comment]
pass is saved like
SHA1(uppercase(accname+":"+password))
so both account name and password can be any case and they will always match.

**Comment by danlapps** [comment]
Blizzard set it so no case sensitive.  Try on retail, you basically cannot have an uppercasein password, even on retail

**Comment by Aokromes** [comment]
It's blizzlike.
