### ISSUE TITLE
[WIP] Diremaul North - Respawn/WPs/Emotes

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14315]
Most of the NPCs are wrong spawned or spawns are missing

ToDO:
- Add some missing SAI
 WPs for these guys: 
http://pokit.org/get/?e9e7280b624217e015a386384c41c25e.jpg
http://pokit.org/get/?9129b9f130c7c5db787d35b19ff21cff.jpg

- Random say emotes for:
http://pokit.org/get/?e9e7280b624217e015a386384c41c25e.jpg say
http://pokit.org/get/?9cacca02c752123b8632b53e062fb9dc.jpg say
http://pokit.org/get/?ee36a4129fac8a8bb5363c9918bc86e2.jpg say
http://pokit.org/get/?47005c8048427bea138cbb954e419333.jpg say
http://pokit.org/get/?3ae1a581300ca97c15c6cd6e1713c784.jpg laugh
http://pokit.org/get/?d7d5c0fa9dd5317814749d89e0ed07f3.jpg laugh

sleep emote for kreeg

**Comment by Kittnz** [comment]
I guess this can be sniffed still on retail?

**Comment by Rushor** [comment]
yeah shure :)

**Comment by dr-j** [comment]
well heres what I have on these 


ServerToClient: SMSG_EMOTE (0x0FC0) Length: 19 ConnIdx: 1 Time: 03/28/2015 21:08:11.813 Number: 27
GUID: Full: 0x1C309835A00B2D00005BBE00051717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11444 Low: 85399489
Emote ID: OneShotApplaud (21)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 19 ConnIdx: 1 Time: 03/28/2015 21:08:11.813 Number: 28
GUID: Full: 0x1C309835A00B2D00005BBE00059717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11444 Low: 93788097
Emote ID: OneShotApplaud (21)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:11.813 Number: 29
GUID: Full: 0x1C309835A00B2C40005BBE00041717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 68622273
Emote ID: OneShotApplaud (21)


ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:24.328 Number: 510
GUID: Full: 0x1C309835A00B2C40005BBE00021717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 35067842
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:24.328 Number: 511
GUID: Full: 0x1C309835A00B2C40005BBE00029717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 43456450
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:12.219 Number: 47
GUID: Full: 0x1C309835A00B2C40005BBE00029717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 43456450
Emote ID: OneShotApplaud (21)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:12.625 Number: 53
GUID: Full: 0x1C309835A00B2C40005BBE00071717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 118953922
Emote ID: OneShotApplaud (21)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 19 ConnIdx: 1 Time: 03/28/2015 21:08:13.031 Number: 59
GUID: Full: 0x1C309835A00B2C40005BBE00009717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 9902017
Emote ID: OneShotTalk (1)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 19 ConnIdx: 1 Time: 03/28/2015 21:08:13.422 Number: 73
GUID: Full: 0x1C309835A00B2D00005BBE00041717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11444 Low: 68622274
Emote ID: OneShotKneel (16)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:15.047 Number: 118
GUID: Full: 0x1C309835A00B2C40005BBE00051717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 85399490
Emote ID: OneShotPoint (25)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:18.281 Number: 252
GUID: Full: 0x1C309835A00B2C40005BBE00029717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 43456450
Emote ID: OneShotTalk (1)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:18.281 Number: 253
GUID: Full: 0x1C309835A00B2C40005BBE00031717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 51845058
Emote ID: OneShotQuestion (6)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:18.672 Number: 257
GUID: Full: 0x1C309835A00B2C40005BBE00041717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 68622274
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:19.078 Number: 281
GUID: Full: 0x1C309835A00B2C40005BBE00029717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 43456449
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:19.078 Number: 282
GUID: Full: 0x1C309835A00B2C40005BBE00031717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 51845057
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 19 ConnIdx: 1 Time: 03/28/2015 21:08:19.078 Number: 283
GUID: Full: 0x1C309835A00B2D00005BBE00039717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11444 Low: 60233665
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:22.297 Number: 409
GUID: Full: 0x1C309835A00B2C40005BBE00069717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 110565314
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 20 ConnIdx: 1 Time: 03/28/2015 21:08:22.297 Number: 410
GUID: Full: 0x1C309835A00B2C40005BBE00071717C2 Creature/0 R3110/S23486 Map: 429 Entry: 11441 Low: 118953922
Emote ID: OneShotLaugh (11)

ServerToClient: SMSG_EMOTE (0x0FC0) Length: 18 ConnIdx: 1 Time: 03/28/2015 21:08:23.922 Number: 481
GUID: Full: 0x1C309835A00B2D00005BBE00001717C1 Creature/0 R3110/S23486 Map: 429 Entry: 11444 Low: 1513409
Emote ID: OneShotQuestion (6)

Note how in sniff multiple npcs (usually 2-3) will play exact same emote at exact same timestamp

**Comment by Killyana** [comment]
Related: https://github.com/TrinityCore/TrinityCore/issues/6429

**Comment by Rushor** [comment]
currently the ogres cannot play emote id: 25

**Comment by Rushor** [comment]
on 3.3.5 one of the ogreentries is not able to perform one of the emotes (on 6.x it is able to perform the emote) i need to research which one was missing
