### ISSUE TITLE
6.x Core startup

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14313]
Hash "3db001e897de"
Rev https://github.com/TrinityCore/TrinityCore/commit/0ba2e0d5ee416a2daf89d53877984fb0cf27ca9b

error

http://gyazo.com/ad6614b09296c5abde4aed9de50e4766

**Comment by Aokromes** [comment]
Useless "crashlog"

**Comment by gearsofdeath** [comment]
Thats all i gets, just this on worldserver before crash, and db errors has nothing

**Comment by DJScias** [comment]
Well, that's an assert introduced in ce35bfe113159c9600f96c4e37ce461735650627, you might be missing something?

**Comment by gearsofdeath** [comment]
i did pull that commit yet yes

**Comment by Zedron** [comment]
corrupt dbc maybe? try re-extracting

**Comment by Shauren** [comment]
Your TaxiNodes.db2 failed to load, fix that instead.
