### ISSUE TITLE
[3.3.5] [Ulduar] Vehicles crash

### ISSUE THREAD

**Issue by Mack36** [TrinityCore/TrinityCore#14316]
1. Go to Ulduar (10 or 25 raid mode)
2. Activate secondary defensive systems by clicking gossip on Lore Keeper.
3. Sit on any of just summoned vehicles.
4. Go straightly to Flame Leviathan's gates, kill 2 big guys standing there to open the gates.
5. When FL goes out, move into his initial place. Your vehicle gets destroyed and you'll get a worldserver crash (sometimes you need to repeat several times to crash).

This happens only with summoned vehicles, and doesn't with those which usually stay there by default.
Debug mode in VS showed that the last call was from Vehicle::RelocatePassengers() after updating zone. Seems like smth wrong with seats, because for example, on a summoned Salvaged Demolisher 
there's an extra npc-like (don't know how it is called) passenger seat - Salvaged Demolisher Mechanic Seat. But one staying there by default doesn't or it's not shown.

rev.:https://github.com/TrinityCore/TrinityCore/commit/9bd7b0e5714475d05d74c15bad500e0a59768edd
DB: TDB 11.57

Oops, my bad, I was looking for crashlogs in debug folder, but for some reason they were not created in it. Here's one from Release build http://pastebin.com/MHGdVKJm
Screenshot http://prntscr.com/6enwsr
Locals http://prntscr.com/6eo01c
Autos http://prntscr.com/6eo0mq

**Comment by Aokromes** [comment]
Cannot confirm, anyway crashlog plz.

**Comment by Mack36** [comment]
No crashlogs are created, worldserver just stops and windows offers to close or to debug.

**Comment by tkrokli** [comment]
Then you need to compile in Debug instead of Release and produce the crash logs.

**Comment by jackpoz** [comment]
the window "close or debug" should pop up after the crash log has been created, it should also show in the console what happened.
since you opened it in VS, you could post locals/autos/callstack and even save a minidump in case we need more data.

**Comment by NorthStrider** [comment]
relwithdebuginfo   does also serve this purpose when the worldserver is compiled on the same machine.

**Comment by jackpoz** [comment]
I'm looking forward for the crash info to be able to fix it, or could someone else try to reproduce the crash and get a crashlog ?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 68c4ea314443
Concerning:
5- When FL goes out, move into his initial place. Your vehicle gets destroyed and you'll get a worldserver crash

The vehicle is killed or just despawn? Because when you pass the gate with the vehicle it despawn to avoid using it on an other boss encounters. (may be the crash happen in this level)

**Comment by pete318** [comment]
Not commenting on the reproduction possibilities. But, wasn't it the case that the vehicles didn't despawn based on location? I thought there was a physical door/object preventing passage past FL until you defeat him. Once he's defeated you were ejected from the vehicles and then they were destroyed.

At least, that's my memory of it.

**Comment by Aokromes** [comment]
FL is really bugged, but never seen a crash because it on the last year.

**Comment by jackpoz** [comment]
@Mack36 are you available to reproduce the issue on another realm to get the crash log ? Could someone provide him an account ready for Ulduar ?

**Comment by Aokromes** [comment]
Also, i sugest you to update core before reporting bugs.

**Comment by Mack36** [comment]
@jackpoz  yes, I'll try to do that. Btw I've updated the first post, so there are some screenshots and a crashlog, could you please check it?
@Killyana It's killed (there are fragments of vehicle left after that) to avoid using it somewhere else as you said.
If no one has managed to reproduce it, maybe it's some kinda local problem. I'll update the core and try it again. Thanks.

**Comment by Aokromes** [comment]
Also, you use any custom script for flame leviathan?

**Comment by jackpoz** [comment]
can you post local and autos from the Vehicle::RelocatePassengers() frame ? Just double-click on that line in the callstack window.
I see you also got a crashlog in Release, any chance to get it in Debug ?

**Comment by Frytiks** [comment]
Cant confirm

**Comment by Aokromes** [comment]
I tried 3 times on 2 diferent machines with clean FL and no crash.

**Comment by Mack36** [comment]
@Aokromes, no, all Ulduar scripts I use are clean, but a little old.
@jackpoz, for some strange reason no crashlogs were created in Debug so far.
Here are locals and autos from Vehicle::RelocatePassengers()
locals - http://pastebin.com/YMGHBQkD
autos - http://pastebin.com/JFahytZQ

**Comment by Aokromes** [comment]
You are using old scripts and new core?

**Comment by Mack36** [comment]
@Aokromes no, I mean both core and scripts are not very fresh, they were updated on Jan 18, 2015 last time. I've just updated the core, I'm gonna test it and make a report later.

**Comment by ariel-** [comment]
Confirmed in 147a959f51ca68d28d7ad298af9982ccc8d90101

Easy reproduce:
.die collossi and leviathan
.npc add temp 33109 (salvaged demolisher)
mount and go through the destroyed door, demolisher despawns and then server crashes.

**Comment by ariel-** [comment]
@Aokromes my crashlog: http://pastebin.com/A8xa8vFs

**Comment by jackpoz** [comment]
@ariel- can you post a crashlog with worldserver built in Debug mode instead of RelWithDebInfo ?

**Comment by ariel-** [comment]
@jackpoz it's all yours, I reimported TDB full 335.57 with all updates to make it as fresh as possible:

https://gist.github.com/ariel-/0ba0205a12ddb48865b2

**Comment by ariel-** [comment]
Player::UpdateAreaDependentAuras causes the despawn

```c++
    if (newArea == 4273 && GetVehicleCreatureBase() && GetPositionX() > 400) // Ulduar
    {
        switch (GetVehicleBase()->GetEntry())
        {
            case 33062:
            case 33109:
            case 33060:
                GetVehicleCreatureBase()->DespawnOrUnsummon();
                break;
        }
    }
```

as the demolisher was created via .npc add temp it is a TempSummon and DespawnOrUnsummon() calls Unsummon; the same will happen for the spawned demolishers that are created after Lore Keeper of Norgannon gossip; as they aren't in DB and created at runtime.

if the demolisher were one pre-spawned, you get the call to ForceDespawn instead

**Comment by ariel-** [comment]
Apparently the Map Update tries to move the removed object, should call Removefrommovelist first to avoid that

**Comment by jackpoz** [comment]
try after https://github.com/TrinityCore/TrinityCore/commit/f1ae2c7b73f3fbc665acac8fd70ce325f20e1194

**Comment by ariel-** [comment]
No crash, but now you can go with vehicles past FL.

**Comment by Rushor** [comment]
are there fitting conditions for the usage of the vehicles in the db?

**Comment by pete318** [comment]
I don't think it's about usage. The vehicles should be destroyed at the end of the FL fight. There shouldn't be any vehicles left to take past him.

If anything it's this aspect that needs fixing.
