### ISSUE TITLE
Learning Specialization 6.x

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14326]
Hash "3db001e897de"
Rev https://github.com/TrinityCore/TrinityCore/commit/47517b21288bfba1584453e20b2e022fd4288e32

When you click on learn then you click yes nothing happens

**Comment by MitchesD** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/47517b21288bfba1584453e20b2e022fd4288e32
