### ISSUE TITLE
Broken WheatyExceptionReport (in Windows 8.1)

### ISSUE THREAD

**Issue by Naios** [TrinityCore/TrinityCore#14329]
Rev. 47517b212

WheatyExceptionReport  is broken, stracktraces are not shown of toplevel exceptions.

You can reproduce this by adding this line:

``` c++
throw std::exception("test exception");
```
to your worldserver mainImpl.
The stacktrace isn't shown then as the image shows:

![screenshot_1](https://cloud.githubusercontent.com/assets/1146834/6580833/6db1ed4c-c753-11e4-95fc-d625e7b12e99.png)

I'm not sure but its possible that Windows 8.1 broke it.

Issue created on request by @jackpoz .

**Comment by jackpoz** [comment]
I'm on Windows 8.1 Update 1 and I developed quite few changes while on this OS with no issues.
The issue is most likely related to exceptions thrown with "throw" keyword, I'll look into it.

**Comment by jackpoz** [comment]
http://pastebin.com/4kCVTPWX is what I got adding a throw exception at line 136 of authserver, the callstack starts only at authserver\main.cpp line 152. do you get the same ?

**Comment by Naios** [comment]
I don't get a callstack, i commented the try ... catch ... block out as well and its still exiting with std::abort () with
```c++
throw std::exception("test");
```
in bnetserver main:L141

**Comment by jackpoz** [comment]
the solution is to revert https://github.com/TrinityCore/TrinityCore/commit/e68ca82d4d039a401d03de145111b0a738bb9dd7 (and surrender to Coverity issues about exception thrown not being caught)

**Comment by Naios** [comment]
Thats the sense of an "UncaughtExceptionHandler". Or you unregister the handler and handle the exception manual in the try ... catch ... clause.

**Comment by jackpoz** [comment]
well the idea was to handle any possible unhandled exception by cleanly close the application instead of crashing , check the return 1 at https://github.com/TrinityCore/TrinityCore/commit/e68ca82d4d039a401d03de145111b0a738bb9dd7#diff-8ef687a9b845fdf84a9d29df368d7611R172 .
it doesn't mean these exceptions shouldn't be handled closer to where they are thrown
