### ISSUE TITLE
Resurrection NPC

### ISSUE THREAD

**Issue by sextonolsen** [TrinityCore/TrinityCore#14322]
I'm trying to make a zone a 30 second resurrection area like in a battleground, but spawning the NPC in a different area has no affect. I was also unable to find anything in the .sln. What should I do?

**Comment by Aokromes** [comment]
this is not place for custom code.

**Comment by sextonolsen** [comment]
So adding a 30 second res NPC for Gurubashi Arena, Diremaul Arena, and any other arenas is a no go?

**Comment by tkrokli** [comment]
Ask your question in the TrinityCore Forum **www.trinitycore.org/f/** to get answers or suggestions.
