### ISSUE TITLE
6.x Tools doesn't extract every thing

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#14321]
CORE - 337bb8cb67dfd3ebaa130555d4ee28b4d4699d15

D:\Games\World of Warcraft>mapextractor.exe
Map & DBC Extractor
===================
opened casc storage 'D:/Games\World of Warcraft\Data'
Locale none not installed.
Detected client build 19634 for locale enUS

Extracting dbc/db2 files...
Unable to open file DBFilesClient\DeclinedWord in the archive for locale enUS: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPower in the archive for locale enUS:
FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAttackPowerRanged in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtAvoidanceDim in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToDodgeBase in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtChanceToParryBase in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtItemLevelByLevel in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp1 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp2 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp3 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp4 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNPCExpectedResistPhysExp5 in the archive for
 locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClass in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp1 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp2 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp3 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp4 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcDamageByClassExp5 in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcGuildExperience in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtNpcTotalMp in the archive for locale enUS: F
ILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToDodge in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTChanceToParry in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassCombatRatingScalar in the archive fo
r locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTClassStats in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTHPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPFromItems in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTMPPerIntellect in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCDpsScaler in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedAgility in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedIntellect in the archive for l
ocale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedResistPhysical in the archive
for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedSpirit in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStamina in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCExpectedStrength in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTNPCHPScaler in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtOCTRaceStats in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseAgility in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseIntellect in the archive for locale en
US: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseSpirit in the archive for locale enUS:
 FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStamina in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCBaseStrength in the archive for locale enU
S: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedAgility in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedIntellect in the archive for local
e enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedSpirit in the archive for locale e
nUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStamina in the archive for locale
enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPCExpectedStrength in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtPVPRanks in the archive for locale enUS: FIL
E_NOT_FOUND
Unable to open file DBFilesClient\gtRageGenScaler in the archive for locale enUS
: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFire in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateFrost in the archive for loc
ale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateHoly in the archive for loca
le enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateNature in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtResistanceInnateShadow in the archive for lo
cale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtShieldBlockRegular in the archive for locale
 enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\gtXPGroupBonus in the archive for locale enUS:
 FILE_NOT_FOUND
Extracted 514 files

Locale koKR not installed.
Locale unknown not installed.
Locale frFR not installed.
Locale deDE not installed.
Locale zhCN not installed.
Locale esES not installed.
Locale zhTW not installed.
Locale enGB not installed.
Locale enCN not installed.
Locale enTW not installed.
Locale esMX not installed.
Locale ruRU not installed.
Locale ptBR not installed.
Locale itIT not installed.
Locale ptPT not installed.
Using locale: enUS
Extracting maps...
Read Map.dbc file... Done! (532 maps loaded)
Read AreaTable.dbc file...Done! (4623 areas loaded)
Read LiquidType.dbc file...Done! (74 LiqTypes loaded)
Convert map files
Extract Azeroth (1/532)
Processing........................57%

                                                 VMAPS BELOW 

[################################################################]
Can't open World\Maps\Transport181645\Transport181645.wdt, err=2!
Can't open World\Maps\Transport177233\Transport177233.wdt, err=2!
Can't open World\Maps\Transport176310\Transport176310.wdt, err=2!
Can't open World\Maps\Transport175080\Transport175080.wdt, err=2!
Can't open World\Maps\Transport176495\Transport176495.wdt, err=2!
Can't open World\Maps\Transport164871\Transport164871.wdt, err=2!
Can't open World\Maps\Transport186238\Transport186238.wdt, err=2!
Can't open World\Maps\Transport20808\Transport20808.wdt, err=2!
Can't open World\Maps\Transport187038\Transport187038.wdt, err=2!
Processing Map 595
[################################################################]
Can't open World\Maps\Transport187263\Transport187263.wdt, err=2!
Can't open World\Maps\CraigTest\CraigTest.wdt, err=2!
Can't open World\Maps\Sunwell5Man\Sunwell5Man.wdt, err=2!
Processing Map 599
[################################################################]

Processing Map 604
[################################################################]
Can't open World\Maps\development_nonweighted\development_nonweighted.wdt, err=2
!
Can't open World\Maps\QA_DVD\QA_DVD.wdt, err=2!
Processing Map 607
[################################################################]
Processing Map 608
[################################################################]
Processing Map 609
[################################################################]
Can't open World\Maps\Transport_Tirisfal _Vengeance_Landing\Transport_Tirisfal _
Vengeance_Landing.wdt, err=2!
Can't open World\Maps\Transport_Menethil_Valgarde\Transport_Menethil_Valgarde.wd
t, err=2!
Can't open World\Maps\Transport_Orgrimmar_Warsong_Hold\Transport_Orgrimmar_Warso
ng_Hold.wdt, err=2!
Can't open World\Maps\Transport_Stormwind_Valiance_Keep\Transport_Stormwind_Vali
ance_Keep.wdt, err=2!
Processing Map 615
[################################################################]

Processing Map 619
[################################################################]
Can't open World\Maps\Transport_Moa'ki_Unu'pe\Transport_Moa'ki_Unu'pe.wdt, err=2
!
Can't open World\Maps\Transport_Moa'ki_Kamagua\Transport_Moa'ki_Kamagua.wdt, err
=2!
Can't open World\Maps\Transport192241\Transport192241.wdt, err=2!
Can't open World\Maps\Transport192242\Transport192242.wdt, err=2!
Processing Map 624
[################################################################]
Can't open World\Maps\unused\unused.wdt, err=2!
Processing Map 628
[################################################################]

Processing Map 638
[################################################################]
Can't open World\Maps\Transport_AllianceAirshipBG\Transport_AllianceAirshipBG.wd
t, err=2!
Can't open World\Maps\Transport_HordeAirshipBG\Transport_HordeAirshipBG.wdt, err
=2!
Processing Map 643
[################################################################]

Processing Map 646
[################################################################]
Can't open World\Maps\Transport_Orgrimmar_to_Thunderbluff\Transport_Orgrimmar_to
_Thunderbluff.wdt, err=2!
Processing Map 648
[################################################################]
Processing Map 649
[################################################################]
Processing Map 650
[################################################################]
Can't open World\Maps\ElevatorSpawnTest\ElevatorSpawnTest.wdt, err=2!
Processing Map 654
[################################################################]

Processing Map 659
[################################################################]
Can't open World\Maps\Deephomeceiling\Deephomeceiling.wdt, err=2!
Processing Map 661
[################################################################]
Can't open World\Maps\Transport197195\Transport197195.wdt, err=2!
Processing Map 668
[################################################################]
Processing Map 669
[################################################################]
Processing Map 670
[################################################################]
Processing Map 671
[################################################################]
Can't open World\Maps\Transport197347\Transport197347.wdt, err=2!
Can't open World\Maps\Transport197348\Transport197348.wdt, err=2!
Can't open World\Maps\Transport197349-2\Transport197349-2.wdt, err=2!
Can't open World\Maps\Transport197349\Transport197349.wdt, err=2!
Can't open World\Maps\Transport197350\Transport197350.wdt, err=2!
Can't open World\Maps\Transport201834\Transport201834.wdt, err=2!
Processing Map 719
[################################################################]

Processing Map 727
[################################################################]
Can't open World\Maps\TheBattleforGilneas\TheBattleforGilneas.wdt, err=2!
Processing Map 730
[################################################################]

Processing Map 736
[################################################################]
Can't open World\Maps\Transport200100\Transport200100.wdt, err=2!
Can't open World\Maps\Transport200101\Transport200101.wdt, err=2!
Can't open World\Maps\Transport200102\Transport200102.wdt, err=2!
Can't open World\Maps\Transport200103\Transport200103.wdt, err=2!
Can't open World\Maps\Transport203729\Transport203729.wdt, err=2!
Can't open World\Maps\Transport203730\Transport203730.wdt, err=2!
Processing Map 746
[################################################################]
Can't open World\Maps\Transport 203732\Transport 203732.wdt, err=2!
Can't open World\Maps\Transport203858\Transport203858.wdt, err=2!
Can't open World\Maps\Transport203859\Transport203859.wdt, err=2!
Can't open World\Maps\Transport203860\Transport203860.wdt, err=2!
Processing Map 751
[################################################################]

Processing Map 760
[################################################################]
Processing Map 761
[################################################################]
Can't open World\Maps\Transport 203861\Transport 203861.wdt, err=2!
Can't open World\Maps\Transport 203862\Transport 203862.wdt, err=2!
Processing Map 764
[################################################################]
Can't open World\Maps\Transport203863\Transport203863.wdt, err=2!
Can't open World\Maps\Transport 2033864\Transport 2033864.wdt, err=2!
Can't open World\Maps\Transport 2033865\Transport 2033865.wdt, err=2!
Processing Map 859
[################################################################]

Processing Map 727
[################################################################]
Can't open World\Maps\TheBattleforGilneas\TheBattleforGilneas.wdt, err=2!
Processing Map 730
[################################################################]

Processing Map 736
[################################################################]
Can't open World\Maps\Transport200100\Transport200100.wdt, err=2!
Can't open World\Maps\Transport200101\Transport200101.wdt, err=2!
Can't open World\Maps\Transport200102\Transport200102.wdt, err=2!
Can't open World\Maps\Transport200103\Transport200103.wdt, err=2!
Can't open World\Maps\Transport203729\Transport203729.wdt, err=2!
Can't open World\Maps\Transport203730\Transport203730.wdt, err=2!
Processing Map 746
[################################################################]
Can't open World\Maps\Transport 203732\Transport 203732.wdt, err=2!
Can't open World\Maps\Transport203858\Transport203858.wdt, err=2!
Can't open World\Maps\Transport203859\Transport203859.wdt, err=2!
Can't open World\Maps\Transport203860\Transport203860.wdt, err=2!
Processing Map 751
[################################################################]

Processing Map 761
[################################################################]
Can't open World\Maps\Transport 203861\Transport 203861.wdt, err=2!
Can't open World\Maps\Transport 203862\Transport 203862.wdt, err=2!
Processing Map 764
[################################################################]
Can't open World\Maps\Transport203863\Transport203863.wdt, err=2!
Can't open World\Maps\Transport 2033864\Transport 2033864.wdt, err=2!
Can't open World\Maps\Transport 2033865\Transport 2033865.wdt, err=2!
Processing Map 859
[################################################################]

Processing Map 1009
[################################################################]
Can't open World\Maps\MistsCTF3\MistsCTF3.wdt, err=2!
Processing Map 1011
[################################################################]

Processing Map 1051
[################################################################]
Can't open World\Maps\LevelDesignLand-DevOnly\LevelDesignLand-DevOnly.wdt, err=2
!
Processing Map 1061
[################################################################]

Processing Map 1112
[################################################################]
Can't open World\Maps\DarkmoonCarousel\DarkmoonCarousel.wdt, err=2!
Processing Map 1116
[################################################################]

Processing Map 1124
[#####################

Processing Map 1130
[################################################################]
Processing Map 1131
[################################################################]
Can't open World\Maps\Transport218599\Transport218599.wdt, err=2!
Can't open World\Maps\Transport218600\Transport218600.wdt, err=2!
Processing Map 1134

Processing Map 1171
[################################################################]
Can't open World\Maps\Transport_Siege_of_Orgrimmar_Alliance\Transport_Siege_of_O
rgrimmar_Alliance.wdt, err=2!
Can't open World\Maps\Transport_Siege_of_Orgrimmar_Horde\Transport_Siege_of_Orgr
immar_Horde.wdt, err=2!
Processing Map 1175
[################################################################]
Processing Map 1176

Processing Map 1191
[################################################################]
Can't open World\Maps\Transport_Iron_Horde_Gorgrond_Train\Transport_Iron_Horde_G
orgrond_Train.wdt, err=2!
Processing Map 1195
[################################################################]
Processing Map 1200

**Comment by DJScias** [comment]
Probably related to #14293.

As Shauren states:
`Not a bug. This is all working as intended`

**Comment by iceyman** [comment]
ok cool but files seem to be missing from dbc that say they can't be found..

**Comment by Aokromes** [comment]
Some files exist only on some locales, the warning must be fixed to stop people creating incorrect reports.
