### ISSUE TITLE
[3.3.5] Core/LootMgr: Master Loot in VOA

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#14328]
When Use Master Loot In Instance [ VOA ] 
1 - Boss Dead
2- Player Check Boss Loot [ See item 1 is usable For he ] [ item 2 In not Usable [Red] ]
3- Master Looter Check Boss Loot to Send Item for Playrs
4- Item 1 Buged [ cannot loot ] Item 2 Send secces
( if All player check loot Boss and See Items and item avalable for them (example : pala Set pala) this item is Buged and master looter cannot loot )
Boss loot buged and cannot loot on any mode [ free for all ] and other . Cannot loot
<<>> I test it jsut occured On VOA . ICC is OK <<>>>
sry for bad english

https://github.com/TrinityCore/TrinityCore/commit/b6e27a0144aebc3bfe9ba1339c4cec59574609c5
Last
##

**Comment by duayres** [comment]
Bugged on every dg/raid or area you have seem or it's a isolated case?

**Comment by SQLfix** [comment]
i just see this bug in VOA . for pvp items [ maybe ]

**Comment by D4R4** [comment]
PVP items are not any different from any other kind of items, maybe one or two flags here and there but they are considered the same in LootMgr, the Instance and the Boss too,, all normal, can you check to make sure the problem only occurs in VoA?

**Comment by SQLfix** [comment]
yes check it . I sure its just in instance VOA

**Comment by fvicaria** [comment]
Confirmed. 
TDB 358.58 + updates

**Comment by selenir** [comment]
Confirming, also happens on ICC sometimes.

**Comment by Keader** [comment]
Still bugged on 170ba68e63c46323f8624ecff24e6de1d38bd97b

**Comment by ryoting** [comment]
confirming,TDB 335.60
HOW TO solve it

**Comment by Rushor** [comment]
maybe related https://github.com/TrinityCore/TrinityCore/issues/13300

**Comment by ryoting** [comment]
how to sovle it

**Comment by tkrokli** [comment]
@MitchesD : could this be related to DB/`reference_loot_template`/`conditions`, or is it definitely core?
See comments from **dr-j** in #17768 for details on why I am asking. :-)

**Comment by Aokromes** [comment]
f5d3343
