### ISSUE TITLE
Leatherworking skill display issue. 3.3.5

### ISSUE THREAD

**Issue by Diskmaster** [TrinityCore/TrinityCore#14337]
build rev 0b768f53bd4e, db last applied sql update was 2015_03_10_01

So, in Shattrath, the trainer offers this skill training layout, which is fine:
http://puu.sh/gvFyz/594ec28f57.jpg

Now, when I go to Dalaran's Leatherworking trainer, I get this weird inconsistency, as shouldn't Journeyman Leatherworking be above the recipes in that list to match the other trainer npc lists?
http://puu.sh/gvFsc/b8daed73b9.jpg

**Comment by Aokromes** [comment]
Try:

```sql
UPDATE `npc_trainer` SET `spell`=2154 WHERE `entry`=201029 AND `spell`=3104;

**Comment by Diskmaster** [comment]
Confirmed working.
