### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by Goten87** [TrinityCore/TrinityCore#14330]
``Using configuration file /home/wow/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.1f 6 Jan 2014 (library: OpenSSL 1.0.1f 6 Jan 2014)
Using Boost version: 1.54.0
DatabasePool wow_world NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors. Read wiki at http://collab.kpsn.org/display/tc/TrinityCore+Home
Cannot connect to world database localhost;3306;goten87;Reallove23;wow_world``

i runned http://www.trinitycore.org/f/files/file/19-tdb-6-full/ on my server and its not starting up what did i wrong

**Comment by Aokromes** [comment]
Read wiki
