### ISSUE TITLE
Valiance rifleman don´t shot

### ISSUE THREAD

**Issue by Warrior94** [TrinityCore/TrinityCore#14339]
Hi there! Riflemen dwarves who defend the Valiance Keep fighting the Nerubians not shoot. They are quiet!

In GM mode, I can see invisible imps in the area. I guess those "invisible" imps used to be shooted by the dwarves. Am I wrong?

**Comment by danlapps** [comment]
Branch, core rev ?

**Comment by DJScias** [comment]
Hello there,

I should probably forward you to read [this page about how to create a proper issue](http://collab.kpsn.org/display/tc/The+Issuetracker+and+You).

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by tkrokli** [comment]
We are trying to help you, but we need you to post important information. Read and follow these instructions: **http://collab.kpsn.org/display/tc/The+Issuetracker+and+You**

**Comment by Rushor** [comment]
the dwarves are actually attacking near nerubiannpcs, but if these nerubian npcs are dead, teh dwarves are doing nothing.

http://www.wowhead.com/npc=25311/valiance-keep-rifleman

**Comment by Rushor** [comment]
okay try this:

```sql
-- Valiance Keep Rifleman SAI
SET @ENTRY := 25311;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,0,1000,1000,6000,6000,11,45761,0,0,0,0,0,19,24921,50,0,0,0,0,0,"Valiance Keep Rifleman - Out of Combat - Cast 'Shoot Gun'");
```

**Comment by tkrokli** [comment]
OK, so the script makes the Valiance Keep Riflemen emote shooting :gun: when out of combat. :smiling_imp:
I have to :ballot_box_with_check: check this, got my test lvl 70 dwarf hunter placed there now, but I'm completely new to Valiance Keep :european_castle: (as well as anything above level 60 on Alliance side in-game). :smirk:

**Comment by Rushor** [comment]
too slow tested :p 
https://github.com/TrinityCore/TrinityCore/commit/0df5cb972d8204e9b5058c8734efc26a520fd869
