### ISSUE TITLE
DB/Quest: Into the Pit / Back to the Pit

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14345]
A hack faction was introduced to avoid npcs killing each other on the pit, but this made the bears killable without the mount, this fix will just disable combat between npcs until the requested future (combat between npcs without damage) is implemented.
``` sql
UPDATE `smart_scripts` SET `action_type`=18, `action_param1`=512, `comment`='Hyldsmeet Warbear - Out of Combat - Set Unit_flag immune to npc (No Repeat)' WHERE `entryorguid`=30174 AND `id`=0;
```

**Comment by tkrokli** [comment]
... and for those of you who would like some extra details from the area and the quests, here you are:

Area: [The Storm Peaks](http://www.wowwiki.com/The_Storm_Peaks) , [Brunnhildar_Village](http://www.wowwiki.com/Brunnhildar_Village)
Quest: Into the Pit: ([WowWiki](http://www.wowwiki.com/Quest:Into_the_Pit)) / ([Wowhead](http://www.wowhead.com/quest=12997/into-the-pit))
Quest:Back to the Pit: ([WowWiki](http://www.wowwiki.com/Quest:Back_to_the_Pit)) / ([Wowhead](http://www.wowhead.com/quest=13424/back-to-the-pit)) (Daily Quest)
Questgiver Gretta the Arbiter: ([WowWiki](http://www.wowwiki.com/Gretta_the_Arbiter)) / ([Wowhead](http://www.wowhead.com/npc=29796/gretta-the-arbiter))
Hyldsmeet Warbear (ID 30174):  http://www.wowhead.com/npc=30174/hyldsmeet-warbear
Player's mount: Warbear Matriarch ([WowWiki](http://www.wowwiki.com/Warbear_Matriarch)) / ([Wowhead](http://www.wowhead.com/npc=29918/warbear-matriarch))
Reins of the Warbear Matriarch, mount provided for quest: [Into the Pit](http://www.wowhead.com/item=42481/reins-of-the-warbear-matriarch) / [Back to the Pit](http://www.wowhead.com/item=42499/reins-of-the-warbear-matriarch)

Player's path to the Hyldsmeet sparked by: http://www.wowhead.com/quest=12970/the-hyldsmeet
Previous quest chain started from K3: http://www.wowhead.com/quest=12843/they-took-our-men
Full list of quests in the related chains: http://www.wowwiki.com/Quest:Into_the_Pit#Quest_progression
