### ISSUE TITLE
Mobs Fail

### ISSUE THREAD

**Issue by TheSinglePlayer** [TrinityCore/TrinityCore#14340]
Today i updated my core and now when attack mob in icecrown they falls through the ground
can someone help me to fix this? ;;) 
i change all sql dates 
reinstalll server
and whenever I enter the instance or outside it, give atack and they disappear

tnks

**Comment by DJScias** [comment]
Hello there,

Please try to fix your issue to include [the necessary information](http://collab.kpsn.org/display/tc/The+Issuetracker+and+You).

**Comment by Aokromes** [comment]
Don't repost your own issues.

**Comment by tkrokli** [comment]
Update your issue #14318 ("Mobs Fail") instead of making a new one.
