### ISSUE TITLE
[6.x] Read emote persists after closing map screen

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#14353]
Created per @DDuarte's request.

**Issue**
Issue came to light in 5dddfbdb7b4619d5f65aa0e009dbe14b5c6a2a3f.

**How to reproduce**
Press 'M' to open map and then close map again. The "Read" emote will persist even if you talk until you move your character. (Trinity 6.x)

**What should actually happen**
Press 'M' to open map and then close map again. "Read" emote will automatically stop once the map screen is closed. (Retail 6.1)

**Comment by Carbenium** [comment]
Closed by c68449f49ea539116f8a45db107b8120f60715eb
