### ISSUE TITLE
Scarlet Initiate SAI

### ISSUE THREAD

**Issue by pete318** [TrinityCore/TrinityCore#14355]
3.3.5 latest core.

```SQL
-- Scarlet Initiate SAI
SET @ENTRY := 1507;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,7,0,0,0,100,0,0,0,3500,5000,11,20793,64,0,0,0,0,2,0,0,0,0,0,0,0,"Scarlet Initiate - In Combat - Cast 'Fireball'"),
(@ENTRY,0,10,0,23,0,100,0,12544,0,5000,10000,11,12544,0,0,0,0,0,1,0,0,0,0,0,0,0,"Scarlet Initiate - On Has Aura 'Frost Armor' - Cast 'Frost Armor'");
```

The creature_addon for all GUIDs that are attached to entry 1507 can have the aura removed too. Since this will make it self cast.

Nothing flash, will self buff, cast fireball on enemies until 15% mana, then move into range to melee until mana is available again.

**Comment by joschiwald** [comment]
do you need the 15% mana thing?

**Comment by pete318** [comment]
Well, without the allow combat move, he just stood still and looked gormless unless I moved into melee range.

I'm not sure if I need to turn on the autoattack though. I didn't try without.

**Comment by Aokromes** [comment]
Use CMC system for casters.

**Comment by pete318** [comment]
Updated. Not sure if the aura refresh works... 22 mins to wait to find out... :P

**Comment by Rushor** [comment]
u can use: SMART_EVENT_FRIENDLY_MISSING_BUFF 16

**Comment by pete318** [comment]
I tried with that and it seemed to ignore it.. Maybe I missed something. I tried AURA and MISSING BUFF.

**Comment by pete318** [comment]
Actually, made it work with aura check. (I looked at the code for friendly missing buff, it searches a radius, as such it could buff the wrong creature in theory).

It works against what the SAI editor says.. -aura didn't work. Aura, count 0 seems to though.. But, there you go.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/04e1f35043f95969e4600901fa22171a90c8afee
