### ISSUE TITLE
Eluna Trinity Wotlk Or Only Trinitycore ?

### ISSUE THREAD

**Issue by Javadfun** [TrinityCore/TrinityCore#14354]
Hello.I Want Make Server Normal for 3.3.5. If i want make it which source is better ?
i want go to work by eluna trinity. this source is good ?Have Database fix ?and bosses fix ?
or use only trinitycore ?
so i like lua and trinity both of them.

**Comment by Aokromes** [comment]
This is not eluna tracker. nor a forum.
