### ISSUE TITLE
Anub'arak Trial

### ISSUE THREAD

**Issue by Hardbitten** [TrinityCore/TrinityCore#14351]
Hi.
phase2 ( underground phase ) Anub'arak Trial It does not work well ! :cry: 
to wit Once Spike Follow Target And Everything is good, The second time Server Crash
I Finde The reason this crash, But i cant FiX Them :(
reason crash :
___________________
case PHASE_NO_MOVEMENT:
DoCast(me, SPELL_SPIKE_SPEED1);
DoCast(me, SPELL_SPIKE_TRAIL);
_phase = PHASE_IMPALE_NORMAL;

>If (Unit* target = >SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, >true))
>{
>StartChase(target);
>Talk(EMOTE_SPIKE, target);
>}
________________

Last Version
TDB 335.58

Who Can Help me ? 
Sry for my Bad writing...

**Comment by Frytiks** [comment]
For real what is that ? Unit* target = >SelectTarget

**Comment by NorthStrider** [comment]
If (Unit* target = >SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, >true))

why   ">"  at true ? seems like the evil one

**Comment by Aokromes** [comment]
Can't confirm, i kill anubarak every week.

**Comment by Hardbitten** [comment]
TDB 335.58

**Comment by Hardbitten** [comment]
Last Version
TDB 335.58

**Comment by Aokromes** [comment]
There is no such thing as "last revision", nor TDB 58.

**Comment by Hardbitten** [comment]
i Test in DeathCoreProject :
https://github.com/NoffearrDeathProjecT/DeathCore_3.3.5
issuse this project not Awnser Me
Can You GiVE ME a Source like this ?
Version in not important.

**Comment by DJScias** [comment]
If you have an issue with this "DeathCore" then I suggest you go to this "DeathCore" with your issue good sir.

They -might- be able to fix it.

**Comment by danlapps** [comment]
ask DeathCoreProject then ?

Not a TC issue, thus invalid

**Comment by jackpoz** [comment]
@Hardbitten I suggest you to stop using that "fake" TrinityCore project and use the original one, you'll get better support for any issue (and some of them have already been fixed)

**Comment by Aokromes** [comment]
If properly documented.
