### ISSUE TITLE
Ulduar-Thorim

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#14365]
http://www.wowhead.com/npc=32865/thorim needs to be scripted.
Currently he doesn't do anything.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/7651 - dublicate

**Comment by tkrokli** [comment]
Open issue: #7651 - close your issue. Read more about how to report issues here:

**http://collab.kpsn.org/display/tc/The+Issuetracker+and+You**
