### ISSUE TITLE
DB/Object: Stone of Remembrance

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#14363]
Bug: No gossip on use.

http://www.wowhead.com/object=20923/stone-of-remembrance

```sql
DELETE FROM `gossip_menu` WHERE `entry`=5004;
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES (5004, 6062);
```

by Rushor

f1ae2c7b73f3fbc665acac8fd70ce325f20e1194

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/1d8f98d988171fab895b23c2d0ca2d2fb39d352f
