### ISSUE TITLE
[6.x] Instanced maps provoking a crash

### ISSUE THREAD

**Issue by vvizard100** [TrinityCore/TrinityCore#14366]
rev : c68449f49ea539116f8a45db107b8120f60715eb
db : last available

Hi guys, I recently saw that accessing to instanced maps is causing a server crash (can be Vanilla map or WoD, it's the same -> accessing via .go or via the entrance directly is not changing anything, the result is the same).  
I've tried with a gm on/gm off, the two factions, still not working. I looked up in map.cpp but found nothing, can't figure out what's wrong :/

Since debugger is angry with me (not working), I can't give you any logs :(
The only thing I know is that this bug was not present in your first releases (talking 6.0.3 here), this bug came up in latests 6.0.3 revs!

Hope you guys will know !
ps : sorry for the english :3

**Comment by Aokromes** [comment]
suply gdb crashlogs.

**Comment by vvizard100** [comment]
I don't have gdb but now compilation in debug mode is working, so here's the crashlog !
http://pastebin.com/dsS4BTsB

**Comment by Regigicas** [comment]
Confirmed using rev https://github.com/TrinityCore/TrinityCore/commit/a80bce124a84be59283e4734016f0c10c17a1e4d: http://paste2.org/zZ1KmwmB
Seems like `worldServerInfo.InstanceGroupSize.Set(GetMap()->GetMapDifficulty()->MaxPlayers);` GetMapDifficulty() can be null?

**Comment by Regigicas** [comment]
Properly debug crashlog
http://paste2.org/3yUdBf5b
