### ISSUE TITLE
Crash in Phase 2 Anubarak Trial

### ISSUE THREAD

**Issue by Javadfun** [TrinityCore/TrinityCore#14362]
Hello. i use Trinitycore Lastest Version 2015 https://github.com/TrinityCore/TrinityCore/archive/3.3.5.zip
And use Full TDB 57 http://www.trinitycore.org/f/files/file/5-tdb-335-full/
But in phase 2 boss_anubarak_trial when Boss Find Target 2 And use Spell Impale server Crashed.

if (Unit* target2 = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
                                {
                                    StartChase(target2);
                                    Talk(EMOTE_SPIKE, target2);
                                }

i say otherone this problme.and they use this source and this db but no have this problme.just me have this problme.
i think this problme is from Maps o vmasp ?my think is true ?

(Sorry bad English)

**Comment by Aokromes** [comment]
There is no such thing has "lastest revision", also i killed anubarak yesterday 2 times with 2 diferent groups of players without crash.

**Comment by Javadfun** [comment]
Can you give me Link Lastest Version Trinitycore And Database and vmaps and masp ?
