### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by q725922** [TrinityCore/TrinityCore#14385]
when i created an account zxb@btnet.com psw:test and try to logging,but my breakpoint stop at 
 TC_LOG_DEBUG("session", "[Battlenet::LogonRequest] Account '%s' is not locked to ip", _accountName.c_str());

whats wrong with my core?

**Comment by DDuarte** [comment]
how did you create the account?

**Comment by q725922** [comment]
by .account create zxb@btnet.com test
any length limit with account or password?

**Comment by thomas33** [comment]
.bnetaccount create account password

**Comment by q725922** [comment]
thanks!I'll try this night.

**Comment by q725922** [comment]
>< another problem ,password or account error,and this error alse troubled me before

**Comment by q725922** [comment]
thanks i finally entered game
