### ISSUE TITLE
[DB/Creature] for best move fly  best boss_sindragosa & boss_saviana_ragefire

### ISSUE THREAD

**Issue by DeActiveDev** [TrinityCore/TrinityCore#14380]
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry` IN (36853, 38265, 38266, 38267);
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry` IN (39747, 39823);

**Comment by danlapps** [comment]
1- http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

2- Code should be like 
```SQL
UPDATE `creature_template` SET `InhabitType` =4 WHERE `entry` IN (36853, 38265, 38266, 38267);
UPDATE `creature_template` SET `InhabitType` =4 WHERE `entry` IN (39747, 39823);
```

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8786
