### ISSUE TITLE
[6.x] death knight specialization crashes

### ISSUE THREAD

**Issue by looreman** [TrinityCore/TrinityCore#14394]
revision: fe971b9048afc694ecad4ecfbd3446db54fab08a

choose any death knight specialization crashes the server.

http://pastebin.com/3iS4xz9M
http://pastebin.com/RLaubhiA
http://pastebin.com/fxpNVZxM

**Comment by streetrat** [comment]
should be fixed since i added the new spell/aura effects for 6.1
