### ISSUE TITLE
[6.x] Stuck in loading screen if you teleport "cross continental"

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14390]
Client hangs while porting from one continent to another, teleports on the same continent do fine
rev: bb1f61bb1f6c9568a9bfaaf32dd133733a54e0a2

**Comment by danlapps** [comment]
Are you using a pure Trinity core or a modified one ?

**Comment by streetrat** [comment]
same here, clean core

**Comment by MitchesD** [comment]
I think it's due to missing opcode CMSG_WORLD_TELEPORT

**Comment by streetrat** [comment]
the teleport_ack isnt handled? then thats the problem, core doesnt know you have finished loading

**Comment by Aokromes** [comment]
Every opcode handled with DEFINE_OPCODE_HANDLER_OLD below https://github.com/TrinityCore/TrinityCore/blob/56186319bdd41dd26b6cc14f84e6e41eef5d953b/src/server/game/Server/Protocol/Opcodes.cpp#L144 is not handled, there's no need to report them

**Comment by DDuarte** [comment]
Fixed in 791cf47d0b0e403f15d8a1a3af3691b418281ae8
