### ISSUE TITLE
DB/Quest: Navarax's Gambit 

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14392]
Source Build:  c51c623

Sql: sql/updates/world/2015_03_16_10_world.sql

Error occured at:2015-03-16 22:04:57
Line no.:14
Error Code: 1146 - Table 'world.broadcast_text' doesn't exist

**Comment by Rushor** [comment]
ye me sry, vm fixed it :)
https://github.com/TrinityCore/TrinityCore/commit/846467423695a73bb1e7687421c8e44de1f0d692

**Comment by tctwod** [comment]
thanks so much
