### ISSUE TITLE
[6.x] Client connection hangs at ~80% [$10]

### ISSUE THREAD

**Issue by JanSimek** [TrinityCore/TrinityCore#14401]
Revision 8464674

Client (version 6.1.0.19702) is able to login and create a character, but then the game is stuck at ~80% of the loading process.

[worldserver-daemon output and connection.log](http://pastebin.com/D5JAnd9d) are on pastebin.

[Link to forum discussion](http://www.trinitycore.org/f/topic/11031-client-connection-hang-at-around-80/) of this issue.

**Comment by Aokromes** [comment]
I wonder if related:
http://www.trinitycore.org/f/topic/11349-error-received-not-handled-opcode/

**Comment by Aokromes** [comment]
@JanSimek can you try to open port 8086?

**Comment by JanSimek** [comment]
I am pretty sure the firewall was down when I ran TC, but I will try it again with port 8086 opened. Unfortunately, I won't be able to try it out until the end of June.

**Comment by Shauren** [comment]
This is a Mac spefiic issue caused by old zlib library installed systemwide
> Can't compress packet opcode (zlib: deflate) Error code: -2 (stream error, msg: (null))

To my knowledge version 1.2.5 is installed on macs but you need 1.2.7 to use 6.x branch
More info in #14689 (its about compiling but also has discussion about zlib)

**Comment by jaredjones** [comment]
@JanSimek 
Install Homebrew from it's website, then run these commands in terminal so that you can get an update zlib.

1) brew tap homebrew/dupes
2) brew update
3) brew install zlib
4) brew link zlib --force
5) Delete CMake caches, reopen CMake and recompile.

This will fix the logging in issue however you won't be able to compile the core with SCRIPTS due to another error. #14689 However these instructions will at least let you into the game.

**Comment by ShinDarth** [comment]
I can confirm.

OS: Mac OS X Yosemite
Rev: https://github.com/TrinityCore/TrinityCore/commit/d4ad3843e9203ba6fabe4ea4177d5eba5e7e563f
Build: Release

After I choose a character and try to enter to world I get:
```
Wrong format occurred (string pointer is null) at /Users/Shin/sources/TrinityCore/src/server/game/Server/WorldSocket.cpp:457.
```
I'm unable to enter in game.

zlib version: ```1.2.8```
cmake param: ```-DZLIB_ROOT=/usr/local/Cellar/zlib/1.2.8```

**Comment by ShinDarth** [comment]
Tested both http://paste.ubuntu.com/11692899/ (as @Shauren suggested) and @jaredjones fix but they don't work :(
