### ISSUE TITLE
[3.3.5]Compil error

### ISSUE THREAD

**Issue by bobkhan** [TrinityCore/TrinityCore#14408]
Compil error 

game.lib(WorldSocketMgr.obj) : error LNK2005: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) already defined in RASession.obj
14>game.lib(ObjectMgr.obj) : error LNK2005: "public: static int const ReputationMgr::Reputation_Cap" (?Reputation_Cap@ReputationMgr@@2HB) already defined in game.lib(ConditionMgr.obj)

Tc rev 5a8cc94
VC - 2012
boost_1_57_0
OpenSSL 1.0.1

**Comment by Aokromes** [comment]
TC needs vs 2013.

**Comment by bobkhan** [comment]
Sorry VC-2013

**Comment by bobkhan** [comment]
Compil error after dfe5e1e 
non Addons

WorldSocket.obj : warning LNK4006: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) already defined in WorldSocketMgr.obj; second definition ignored
7>WorldSession.obj : warning LNK4006: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) already defined in WorldSocketMgr.obj; second definition ignored
7>ObjectMgr.obj : warning LNK4006: "public: static int const ReputationMgr::Reputation_Cap" (?Reputation_Cap@ReputationMgr@@2HB) already defined in SpellEffects.obj; second definition ignored

**Comment by DDuarte** [comment]
Neither Travis (https://travis-ci.org/TrinityCore/TrinityCore/builds/54998449 Linux/Clang), our Buildbot (Linux/GCC) nor my own computer (Windows/VS 2013) have that compiler error.

Try to clear your compile folder and rebuild.

**Comment by Aokromes** [comment]
Also check that you have Visual Studio 2013 update 4 installed.

**Comment by Killyana** [comment]
@bobkhan I get the same errors, any update on this?

**Comment by danlapps** [comment]
all ok on VS 2013 ultimate update 4

**Comment by Nyeriah** [comment]
Updating visual studio fixes it

**Comment by tkrokli** [comment]
No compile errors for me on straight TC 3.3.5 source, with or without tools, for the last month. Have compiled new updates with only 1 or 2 days between each compile, sometimes each day for a week.

6.x and 4.3.4 compiled a couple of times, only a few warnings, no errors. VS2013 Community Update 4.

**Comment by DDuarte** [comment]
Update Visual Studio to [Update 4](http://www.microsoft.com/en-us/download/details.aspx?id=44921)
