### ISSUE TITLE
[6.x] crash on start casting spell

### ISSUE THREAD

**Issue by xTurinx** [TrinityCore/TrinityCore#14406]
I'm currently working on Blood Slag Mines Dungeon and got a crash when I let cast a npc spellid 153735. This spell should summon another npc (the summon npc exists in database).

Backtrace: http://www.trinitycore.org/f/pastebin/a0mdqxofhgfr
Spell Details from SpellWork: http://www.trinitycore.org/f/pastebin/1qfujm1v2v7fy/
OS: Ubuntu 14.04 x64
Compiler: GCC
Revision: c4499cf35d8551bcfd718ea0709dcc3bb902731e

Regards

**Comment by Shauren** [comment]
Target type 138 is not implemented

**Comment by xTurinx** [comment]
Alright. Thanks for your quick answer!

**Comment by DDuarte** [comment]
ee3a111756799c54a2d9f983c4e0a587c5add72a
