### ISSUE TITLE
[6.x] Undetectable AreaTriggers, possible phase issue

### ISSUE THREAD

**Issue by Walkum** [TrinityCore/TrinityCore#14417]
Some AreaTriggers are undetectable reaching it with debug areatrigger on. Checking on DBC I discovered that undetectable areatriggers have value "0" on column #5 (These column is commented on DBCStructure.h, is the "PhaseUseFlags" cell), you can see only areatriggers with value "1".

Rev. https://github.com/TrinityCore/TrinityCore/commit/1f7f9feafc3f5017d617634ae993d2cdf4430920

**Comment by NorthStrider** [comment]
caused by terrainswapmaps.

**Comment by Aokromes** [comment]
Try again on head.

**Comment by Walkum** [comment]
Not work yet, one AreaTrigger for test it for example would be Ragefire Chasm entrance trigger.

**Comment by Walkum** [comment]
Works correctly, caused due bad sending phaseshift opcode.
