### ISSUE TITLE
[Branch: All][Spell] Dreadsteed - Flame visual

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14413]
ref: https://github.com/TrinityCore/TrinityCore/commit/ea78bce592b66c72230b63871024e83536b693b7

Spells:
http://www.wowhead.com/spell=23161/dreadsteed
http://www.wowhead.com/spell=5784/felsteed

How it should be:
If you cast this spell, you should actual see a flame visual after the cast. (should be something like the 'Flamestrike'-spell from mages)

How it is:

There is no flame vsual

proof:
http://wow.zamimg.com/uploads/screenshots/resized/4449.jpg
https://www.youtube.com/watch?feature=player_detailpage&v=SG45Dlj_Miw#t=28

**Comment by Aokromes** [comment]
Can you show one screenshot of what you see? because i see the same as the wowhead screenshot.

**Comment by Killyana** [comment]
This will add the missing visual.
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 23161;
INSERT INTO `spell_linked_spell` VALUES (23161, 31725, 0, 'Summon Nightmare');

DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 5784;
INSERT INTO `spell_linked_spell` VALUES (5784, 31725, 0, 'Summon felsteed');

**Comment by P-Kito** [comment]
Works ty
