### ISSUE TITLE
There's a lot of error with TDB3.3.5.58

### ISSUE THREAD

**Issue by cqqjjf** [TrinityCore/TrinityCore#14425]
Creature (Entry: 34935, faction 1735) has different `faction` in difficulty 1 mode (Entry: 35427, faction 1665).
 Creature (Entry: 34935, class 1) has different `unit_class` in difficulty 1 mode (Entry: 35427, class 4).

FIX:
UPDATE `creature_template` SET `faction`=1735,`unit_class`=1 WHERE `entry`=35427;

There's no problem on 3.3.5.57.
_____________________________________________________________
 Table `achievement_criteria_data` does not have expected data for criteria (Entry: 6626 Type: 41) for achievement 1785.
 Table `achievement_criteria_data` does not have expected data for criteria (Entry: 6627 Type: 41) for achievement 1785.
 Table `achievement_criteria_data` does not have expected data for criteria (Entry: 6628 Type: 41) for achievement 1785.
 Table `achievement_criteria_data` does not have expected data for criteria (Entry: 6629 Type: 41) for achievement 1785.
 Table `achievement_criteria_data` does not have expected data for criteria (Entry: 6630 Type: 41) for achievement 1785.
________________________________________________

Script named 'spell_dk_death_grip_initial' does not have a script name assigned in database.
 Script named 'spell_q12414_hand_over_reins' does not have a script name assigned in database.
 Script named 'spell_archimonde_drain_world_tree_dummy' does not have a script name assigned in database.
 Script named 'at_ancient_leaf' does not have a script name assigned in database.
 Script named 'boss_nexus_commanders' does not have a script name assigned in database.
 Script named 'achievement_bronjahm_soul_power' does not have a script name assigned in database.
 Script named 'at_hor_uther_quel_delar_start' does not have a script name assigned in database.
 Script named 'npc_uther_quel_delar' does not have a script name assigned in database.
 Script named 'npc_quel_delar_sword' does not have a script name assigned in database.
______________________________these script need core scripts ↓___________
 ScriptName '423' exists in database, but no core script found!
 ScriptName 'at_eye_of_eternity_improvised_floor' exists in database, but no core script found!
 ScriptName 'at_madrigosa' exists in database, but no core script found!
 ScriptName 'at_twiggy_flathead' exists in database, but no core script found!
 ScriptName 'do_nothing' exists in database, but no core script found!
 ScriptName 'go_blackhoof_cage' exists in database, but no core script found!
 ScriptName 'go_defias_cannon' exists in database, but no core script found!
 ScriptName 'go_door_lever_dm' exists in database, but no core script found!
 ScriptName 'go_gjalerbron_cage' exists in database, but no core script found!
 ScriptName 'go_kael_orb' exists in database, but no core script found!
 ScriptName 'go_large_gjalerbron_cage' exists in database, but no core script found!
 ScriptName 'go_movie_orb' exists in database, but no core script found!
 ScriptName 'internalitemhandler' exists in database, but no core script found!
 ScriptName 'npc_alexstrasza_wr_gate' exists in database, but no core script found!
 ScriptName 'npc_aran_blizzard' exists in database, but no core script found!
 ScriptName 'npc_bladespire_ogre' exists in database, but no core script found!
 ScriptName 'npc_blaze' exists in database, but no core script found!
 ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!
 ScriptName 'npc_crystalline_tangler' exists in database, but no core script found!
 ScriptName 'npc_demon_fire' exists in database, but no core script found!
 ScriptName 'npc_flame_crash' exists in database, but no core script found!
 ScriptName 'npc_generic_harpoon_cannon' exists in database, but no core script found!
 ScriptName 'npc_homunculus' exists in database, but no core script found!
 ScriptName 'npc_invis_legion_teleporter' exists in database, but no core script found!
 ScriptName 'npc_keristrasza' exists in database, but no core script found!
 ScriptName 'npc_king_jokkum_vehicle' exists in database, but no core script found!
 ScriptName 'npc_kyle_frenzied' exists in database, but no core script found!
 ScriptName 'npc_magnetic_core' exists in database, but no core script found!
 ScriptName 'npc_margrave_dhakar' exists in database, but no core script found!
 ScriptName 'npc_mindless_skeleton' exists in database, but no core script found!
 ScriptName 'npc_morbidus' exists in database, but no core script found!
 ScriptName 'npc_nether_vapor' exists in database, but no core script found!
 ScriptName 'npc_novos_minion' exists in database, but no core script found!
 ScriptName 'npc_plains_vision' exists in database, but no core script found!
 ScriptName 'npc_risen_husk_spirit' exists in database, but no core script found!
 ScriptName 'npc_sliver' exists in database, but no core script found!
 ScriptName 'npc_snufflenose_gopher' exists in database, but no core script found!
 ScriptName 'npc_stinky' exists in database, but no core script found!
 ScriptName 'npc_thuzadin_acolyte' exists in database, but no core script found!
 ScriptName 'npc_tracy_proudwell' exists in database, but no core script found!
 ScriptName 'npc_vereth_the_cunning' exists in database, but no core script found!
 ScriptName 'npc_void_zone' exists in database, but no core script found!
 ScriptName 'npc_yauj_brood' exists in database, but no core script found!
 ScriptName 'spell_cultist_dark_martyrdrom' exists in database, but no core script found!
 ScriptName 'spell_ex_463' exists in database, but no core script found!
 ScriptName 'spell_ex_5581' exists in database, but no core script found!
 ScriptName 'spell_ex_66244' exists in database, but no core script found!
 ScriptName 'spell_ex_absorb_aura' exists in database, but no core script found!
 ScriptName 'spell_mimiron_flame_suppressant' exists in database, but no core script found!
 ScriptName 'spell_snufflenose_command' exists in database, but no core script found!
_________________________smart ai error below__________________________
 SmartAIMgr: Entry 1535 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 2719 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 4484 SourceType 0 Event 24 Action 1 using non-existent Text id 5, skipped.
 SmartAIMgr: Entry 13601 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 15324 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 15526 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 17397 SourceType 0 Event 0 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 18554 SourceType 0 Event 9 Action 1 using non-existent Text id 4, skipped.
 SmartAIMgr: Entry 18554 SourceType 0 Event 13 Action 1 using non-existent Text id 7, skipped.
 SmartAIMgr: Entry 18554 SourceType 0 Event 14 Action 1 using non-existent Text id 8, skipped.
 SmartAIMgr: Entry 18938 SourceType 0 Event 2 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 19354 SourceType 0 Event 4 Action 1 using non-existent Text id 1, skipped.
 SmartAIMgr: Entry 23669 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 24198 SourceType 0 Event 3 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 25730 SourceType 0 Event 5 Action 1 using non-existent Text id 0, skipped.
 SmartAIMgr: Entry 25730 SourceType 0 Event 7 Action 1 using non-existent Text id 1, skipped.
 SmartAIMgr: Entry 25730 SourceType 0 Event 9 Action 1 using non-existent Text id 2, skipped.
 SmartAIMgr: Entry 25730 SourceType 0 Event 15 Action 1 using non-existent Text id 5, skipped.
 SmartAIMgr: Entry 25730 SourceType 0 Event 23 Action 1 using non-existent Text id 7, skipped.
 SmartAIMgr: EntryOrGuid 26670 SourceType 0, Event 18, Event is linking self (infinite loop), skipped.
 SmartAIMgr: Entry 30945 SourceType 0 Event 9 Action 1 using non-existent Text id 3, skipped.
 SmartAIMgr: Entry 177490 SourceType 1 Event 0 Action 50 has abs(`target.o` = 104.370003) > 2*PI (orientation is expressed in radians)
 SmartAIMgr: Entry 177490 SourceType 1 Event 2 Action 50 has abs(`target.o` = 104.370003) > 2*PI (orientation is expressed in radians)
 SmartAIMgr: Entry 2749200 SourceType 9 Event 5 Action 12 has abs(`target.o` = 11.654100) > 2*PI (orientation is expressed in radians)
 SmartAIMgr::LoadSmartAIFromDB: Entry 4484 SourceType 0, Event 25, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 15526 SourceType 0, Event 1, Link Event 2 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 19354 SourceType 0, Event 2, Link Event 4 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 28122 SourceType 0, Event 16, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 31279 SourceType 0, Event 16, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 15324 SourceType 0, Event 2, Link Event 3 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 9450 SourceType 0, Event 3, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 13196 SourceType 0, Event 9, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 12236 SourceType 0, Event 9, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 18938 SourceType 0, Event 1, Link Event 2 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 15146 SourceType 0, Event 3, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 26787 SourceType 0, Event 0, Link Event 1 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 17892 SourceType 0, Event 7, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 17892 SourceType 0, Event 20, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 26670 SourceType 0, Event 17, Link Event 18 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 18903 SourceType 0, Event 23, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 20438 SourceType 0, Event 13, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 25730 SourceType 0, Event 14, Link Event 15 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 24198 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 26701 SourceType 0, Event 0, Link Event 1 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 27788 SourceType 0, Event 11, Link Source Event not found or invalid. Event will never trigger.
 SmartAIMgr::LoadSmartAIFromDB: Entry 28006 SourceType 0, Event 5, Link Event 7 not found or invalid.
 SmartAIMgr::LoadSmartAIFromDB: Entry 28006 SourceType 0, Event 6, Link Source Event not found or invalid. Event will never trigger.

**Comment by Aokromes** [comment]
cannot confirm.

**Comment by tkrokli** [comment]
@cqqjjf : are you able to add ``` (3 back ticks) on a blank single line before and after each error section?
It will make the error text lines use only 1 line each (turn off word wrap).

**Comment by DDuarte** [comment]
I'm not quite sure what happened. Anyway, I've repacked TDB 335.58 and re-uploaded it to https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.58.
Sorry about the trouble.

**Comment by DDuarte** [comment]
*Summons @Naios* 

Could it be possible that the DB updater 'corrupts' the db? Screenshot from @Vincent-Michael comparing previous released TDB and new one: http://i.imgur.com/KKIMgWI.png

In the new one I didn't use the DB updater to import the SQLs.

**Comment by tkrokli** [comment]
Thanks for repacking and uploading TDB335.58 again. It looks a lot more normal now.

**Comment by Naios** [comment]
@DDuarte can't imagine that because currently just `mysql -u... DB < FILENAME` is invoked. No content that is used for hashing is sent to mysql.
