### ISSUE TITLE
 [Branch: All][Spell] Paladin Mounts - Holy visual

### ISSUE THREAD

**Issue by itslovelol** [TrinityCore/TrinityCore#14427]
Same as https://github.com/TrinityCore/TrinityCore/issues/14413

```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (23214, 13819);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `comment`) VALUES
(23214, 31726, 'Summon Charger'),
(13819, 31726, 'Summon Warhorse');
```

**Comment by tkrokli** [comment]
Just a friendly tip: when posting SQL code, put the code ```sql on an empty line above your code.

If you need to add regular text below, add a line with the 3 back ticks ``` on its own line below the code, then continue writing beneath it.

**Comment by P-Kito** [comment]
Working, thanks

**Comment by Nyeriah** [comment]
What about blood elves? :'(

**Comment by itslovelol** [comment]
They should have the same visual effect. So your fix is correct.

4:05
https://www.youtube.com/watch?v=KoSfRDcON8A
