### ISSUE TITLE
[3.3.5] Priest Talent - Blessed Recovery

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#14423]
https://github.com/TrinityCore/TrinityCore/commit/236e43443c644a9a50cb48ff7300950c928d336c

Priest with talent [Blessed Recovery] dont recovery Heal on crit damages
dont work talent
##

**Comment by SQLfix** [comment]
Edited [wrong revision selected] from 6.x
i use Mar 21, 2015   3.3.5

**Comment by Rushor** [comment]
http://wotlk.openwow.com/?search=Blessed+Recovery

**Comment by Keader** [comment]
Working cfafca7517a9239d3a137679f1e536910f374a8f
