### ISSUE TITLE
Blackrock Spy Loot with correct Drop Rates

### ISSUE THREAD

**Issue by Gecko60** [TrinityCore/TrinityCore#14432]
```sql
-- Northshire Blackrock Spy Loot With Correct Drop Rate

UPDATE `creature_template` SET `lootid`=49874 WHERE `entry`=49874;
DELETE FROM `creature_loot_template` WHERE `entry`=49874;
INSERT INTO `creature_loot_template` (`entry`,`item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(49874, 62328, 0, 0.06, 0, 1, 0, 1, 1, 'Shed Fur'),
(49874, 5572, 0, 0.9, 0, 1, 0, 1, 1, 'Small Green Pouch'),
(49874, 5571, 0, 1.1, 0, 1, 0, 1, 1, 'Small Black Pouch'),
(49874, 828, 0, 1.4, 0, 1, 0, 1, 1, 'Small Blue Pouch'),
(49874, 805, 0, 1.2, 0, 1, 0, 1, 1, 'Small Red Pouch'),
(49874, 4496, 0, 1.1, 0, 1, 0, 1, 1, 'Small Brown Pouch'),
(49874, 2589, 0, 0.3, 0, 1, 0, 1, 1, 'Linen Cloth');
```

**Comment by danlapps** [comment]
Your "correct" drop rate seems taken from wowhead.  Those are mostly wrong values, since wolves or any human or animals shouldnt drop ''Inert Elemental pieces' those should come mostly from killing elementals.

**Comment by Gecko60** [comment]
Isn't wowhead a reliable source?

**Comment by Nyeriah** [comment]
When it comes to loot it's hard to say so, also, these should be using referenced loot along with the other starting are mobs that drop the same set of items

**Comment by danlapps** [comment]
Keep first 7 entries, trash the rest.

Wowhead gets messed up in case of AOE looting, it will add the looted item to either all the monster in the AOE, or in the one you have targetted at the moment.

Check mining node for example, some have potions listed as loot, i never saw a potion while gathering copper ore.

**Comment by Gecko60** [comment]
I see what you're saying. So it was reliable till the AOE looting was introduced. So what would you suggest as a reliable source for loot tables?

**Comment by Gecko60** [comment]
Updated this as well.

**Comment by Rushor** [comment]
well i tried to update the automated loot generation which was once made in an other loot ticket.

if contains some refernces and the loot from wowhead, the droppchances are a bit increased for special items.

it's a start, but however this will never be accepted as blikeloot

http://www.file-upload.net/download-10461287/loot.sql.html
http://www.file-upload.net/
(all loot for cata)

**Comment by msoky** [comment]
look at http://eu.battle.net/wow/en/item/2589 and set % from this table which is used by trinitycore :
Guaranteed = 100%
Very High = 90%
High = 75%
Medium 50%
Low = 25%
Very Low = 10 or 5%
Rare = 1% or lower
