### ISSUE TITLE
Lost MySQL Connection

### ISSUE THREAD

**Issue by et65** [TrinityCore/TrinityCore#14430]
Since https://github.com/TrinityCore/TrinityCore/commit/352012e53173372ebc82898e1b6854c983b01b25, few minutes after worldserver or bnetserver start, all queries failed with error :

`
[ERROR]: [0] Lost connection to MySQL server during query
Unhandled MySQL errno 0. Unexpected behaviour possible.
`

All rework after a server restart. It seems that the MySQL connection is lost after a short time.

**Comment by et65** [comment]
What details do you need more? I don't have skills to say why it bugs, but i've tested to revert this commit and all work correctly.

**Comment by DDuarte** [comment]
The details we need is how to reproduce this issue on our servers/computers.

**Comment by Naios** [comment]
Which revision, mysql server (distribution/ version) compiler and os are you using?

**Comment by DDuarte** [comment]
Also it might help if you enable full debug logs and post them here.

**Comment by et65** [comment]
So :
- I use 6.x branch.
- To reproduce the bug it's quite simple, let the server started and wait few minutes, all sql queries will failed with the error I gave before.
- I use last TC rev and a Debian 7 server.

Thanks you for your work ;) !

**Comment by et65** [comment]
I forgot, I use MariaDB 10.0.17

**Comment by Nyeriah** [comment]
I can actually confirm this in the 335 branch as well, I'll fill in more information tomorrow if @W1shtol1ve doesn't stop by

**Comment by leak** [comment]
Increase `max_allowed_packet` and those various timeout options mysql/mariadb has.

**Comment by DDuarte** [comment]
Does this issue happen with the DBUpdater turned or or off?

**Comment by Naios** [comment]
`--max-allowed-packet=1GB` is used by the dbupdater so the packet size shoudn't be the problem.
It would be nice if you provide more logs, (Log with Logger.sql.driver enabled and your mysql log).

**Comment by et65** [comment]
@DDuarte : it also happen with DBUpdater disabled.

**Comment by Nyeriah** [comment]
Blame boost, updating it solves it

**Comment by w1sht0l1v3** [comment]
what @Nyeriah said...at least for us it worked with updating boost from 1.49 to 1.57

**Comment by w1sht0l1v3** [comment]
or not...

**Comment by Expecto** [comment]
Change Mysql wait timer to
wait_timeout = 6000

**Comment by Nyeriah** [comment]
wait_timeout is set to 28800, so definitely it's not that, max_allowed_packets is set to 1gb. MySQL 5.5

I can't reproduce this issue on a small environment, but somehow when using a larger database and more players connected to it the queries start getting bottlenecked. 

Current database settings are, 2 threads for auth & world, 6 for characters. Tried lowering threads and it didn't work either.

http://pastebin.com/eRRY97Th

**Comment by Naios** [comment]
Did you try it with an earlier revision, 127d8a2bcc5 for example? I can't imagine that it broke something there because as i said before only the connection loading was touched.

**Comment by et65** [comment]
@Naios: Yes I tried to use exactly this revision and it works.

**Comment by Pirricli** [comment]
@Naios, I have the same problem in 3.3.5, but for me It's a little bit differente. It happens after my server crashes. I run worldserver again but characters on accounts don't appear. I have the same error message. To solve my problem I have to shut down worldserver again and again till the characters appear.

```2015-03-26_03:38:27Unhandled MySQL errno 0. Unexpected behaviour possible.
2015-03-26_03:38:27SQL(p): DELETE FROM .... ```

**Comment by Nyeriah** [comment]
I have tried this further and indeed you cannot reproduce this issue without at least 50 players online at 335, that's when the queries start getting bottlenecked. Reverting it to the revision before the db changes brought in by the updater seems to help... maybe you guys can reproduce it with jackpoz's bot farm?

**Comment by et65** [comment]
For my part I have the problem only with 1 or 2 players online.

**Comment by Pirricli** [comment]
I have it only when the server starts and not always. The characters don't appear when you log in and it have happened.

**Comment by et65** [comment]
@Pirricli : I'm not sure you have the same problem, for me, when the issue happen it's impossible to login because all sql queries failed.

**Comment by Naios** [comment]
As i said before, you need to provide sql driver and mysql logs. To post  the same error message over and over doesn't help.

**Comment by et65** [comment]
Full debug logs for one SQL query:

```
2015-03-27_14:40:33ERRORSQL(p): SELECT id, sessionkey, last_ip, locked, expansion, mutetime, locale, recruiter, os FROM account WHERE username = 'et65'
 [ERROR]: [2006] Lost connection to MySQL server during query
2015-03-27_14:40:33INFO Connected to MySQL database at 127.0.0.1
2015-03-27_14:40:36ERRORUnhandled MySQL errno 0. Unexpected behaviour possible.
```

PS: I've tested to update Boost to 1.57 version but no effect.

**Comment by Naios** [comment]
Could you provide your mysql error log please?

**Comment by et65** [comment]
Nothing suspect in mysql logs, or I didn't enable its correctly (i set log_warnings to 2).

**Comment by Naios** [comment]
Ah ok, got it. Statements are not prepared after reconnect.

**Comment by et65** [comment]
Nice, good luck ! :)

**Comment by Naios** [comment]
Tell me if this solved it for you, i guess it did.

**Comment by et65** [comment]
I'll try, thanks you :)

**Comment by et65** [comment]
It works fine! Thanks you very much! :)
