### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Aestorn** [TrinityCore/TrinityCore#14431]
Error    6    error LNK1169: one or more multiply defined symbols found    C:\Users\devel_000\Desktop\\bin\Release\worldserver.exe    worldserver

 Error    5    error LNK2005: "public: static int const ReputationMgr::Reputation_Cap" (?Reputation_Cap@ReputationMgr@@2HB) already defined in game.lib(ConditionMgr.obj)    C:\Users\devel_000\Desktop\\src\server\worldserver\game.lib(ObjectMgr.obj)    worldserver

Error    4    error LNK2005: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) already defined in RASession.obj    C:\Users\devel_000\Desktop\\src\server\worldserver\game.lib(WorldSocketMgr.obj)    worldserver

Warrning : 

Warning    2    warning LNK4006: "public: static int const boost::asio::socket_base::max_connections" (?max_connections@socket_base@asio@boost@@2HB) already defined in WorldSocketMgr.obj; second definition ignored    C:\Users\devel_000\Desktop\\src\server\game\WorldSession.obj    game

Warning    3    warning LNK4006: "public: static int const ReputationMgr::Reputation_Cap" (?Reputation_Cap@ReputationMgr@@2HB) already defined in SpellEffects.obj; second definition ignored    C:\Users\devel_000\Desktop\PvpZONE011\src\server\game\ObjectMgr.obj    game

Please Check..........

**Comment by Naios** [comment]
Duplicated #14408
