### ISSUE TITLE
Wintergrasp

### ISSUE THREAD

**Issue by oelsaid** [TrinityCore/TrinityCore#14440]
Sorry I am not familiar with reporting bugs

http://i.imgur.com/DQQ3IQY.jpg
http://i.imgur.com/MPmTsA1.jpg

http://forum.wowpandora.com.br/index.php?/topic/46-bug-ta-winter/#entry196

**Comment by Aokromes** [comment]
1) duplicate
2) https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by oelsaid** [comment]
Sorry posted wrong should have posted on 3.3.5

Ally're only gaining 1x and 3x horde

**Comment by DDuarte** [comment]
> Sorry I am not familiar with reporting bugs
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

Feel free to open a new one with proper details.
