### ISSUE TITLE
Vehicles: Cannot turn invisible or not selectable

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14445]
Any npc with flags_extra 128 is supposed to be invisible and not selectable, but if this npc is a vehicle he will be visible and selectable (unit_flag 33554432 don't have any affect neither)
Exemple: 34146, 34150, 34151
rev. 7ee61140bf72

**Comment by Nyeriah** [comment]
Not true, there are many not selectable vehicles (Sota, IoC). I'm unsure about invisibilty and that flags_extra in special but I don't see why wouldn't it work on them

**Comment by joschiwald** [comment]
In many cases, this issue is caused by an visual aura, try without the aura

**Comment by Killyana** [comment]
To reproduce the bug with one of these npcs(34146, 34150, 34151)
* .go crea 136426 (you will see all the trigger in this area are visible)
* Close the world and (update creature_template set vehicleid=0 where entry=34151;) -- default 396
* .go crea 136426 (you will see now that npcs 34151 are not visible or selectable)
Of course this was tested without any script or aura for this npcs

**Comment by NorthStrider** [comment]
npc's with flags extra 128 are suposed to have a 2nd display id which is responsible for the invisibility. Also there are some unit flags that are common to that behavior

**Comment by cr4st** [comment]
Try it without GM mode:
* Outside of the instance
* .gm off
* Create a raid
* .go c 136426

Or simply change: (Works for me better :v: )
```diff
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index a68640f..ae55ac7 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -22660,7 +22660,7 @@ void Player::UpdateTriggerVisibility()
     WorldPacket packet;
     for (auto itr = m_clientGUIDs.begin(); itr != m_clientGUIDs.end(); ++itr)
     {
-        if (itr->IsCreature())
+        if (itr->IsCreatureOrVehicle())
         {
             Creature* creature = GetMap()->GetCreature(*itr);
             // Update fields of triggers, transformed units or unselectable units (values dependent on GM state)

**Comment by joschiwald** [comment]
yeah, that looks perfect
