### ISSUE TITLE
lua GetQuestsCompleted for daily quests

### ISSUE THREAD

**Issue by iTob191** [TrinityCore/TrinityCore#14448]
Branch: 3.3.5 | rev following..

In the result of the GetQuestsCompleted() lua function provided by the WoW API a daily quest that was not completed that day should be marked as incompleted even if it has already been completed on a previous day. Currently, a daily quest is always marked completed if it was completed once before.

As the data is received from the server (after QueryQuestsCompleted() was called) I think this is a server-side bug, but I'm not sure here.

Source: http://wow.gamepedia.com/API_GetQuestsCompleted:
"Daily quests appear completed only if they have been completed that day."

**Comment by DDuarte** [comment]
Branch and hash revision, pretty please.

http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by iTob191** [comment]
Sorry for that. I have added the branch. For the revision I have to do some testing as I tested it on a public server running with TC..

**Comment by Shauren** [comment]
Note: not the case on 6.x, handling of completed quests for client was changed there

**Comment by danlapps** [comment]
Quote :  tested it on a public server running with TC

Since no one can know for sure if this pserver modified code or not, this issue will most likely be invalid.

**Comment by Rushor** [comment]
well get started with the installation on http://collab.kpsn.org/display/tc/Core+Installation an retest it @iTob191 :D

**Comment by iTob191** [comment]
I know, gonna test it on my local server soon..

**Comment by MrSmite** [comment]
> Since no one can know for sure if this pserver modified code or not, this issue will most likely be invalid.

I don't think so, I took a look at 42f1a0babfaacf64df and this actually appears to be a design flaw, not a bug (since a bug is when code doesn't do as expected).

*Player::GetQuestRewardStatus()* has a comment: *repeatable quests: rewarded field is set after first reward only to prevent getting XP more than once*. This is stored in and read from *m_RewardedQuests* so the core as it is written always returns dailys as rewarded.

**Comment by danlapps** [comment]
@MrSmite now those are some clear explanations :)

**Comment by iTob191** [comment]
Still need some testing or was MrSmites response enough? :p

**Comment by Rushor** [comment]
the ticketcreator should care about everything in his/her issue und should actually test everything on a fresh clean tccore

**Comment by Rushor** [comment]
test it yourself on current tc rev, give feedback, then we will reopen the issue
