### ISSUE TITLE
3.3.5a Quest 12326 - Steamtank Surprise

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#14444]
You can not mount any of the tanks to do the quest.

TrinityCore rev. 769acfbd02a0 2015-03-17 12:42:35 +0000 (3.3.5 branch) (Win64, Release) (worldserver-daemon)

**Comment by Aokromes** [comment]
#1866

**Comment by tkrokli** [comment]
Post your confirmation on the existing issue if you want.
