### ISSUE TITLE
how can mac connect tc 

### ISSUE THREAD

**Issue by DrYaling** [TrinityCore/TrinityCore#14455]
how can mac connect tc  server?my mac can only log to public server but I don't know how to connect to trinity core server

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by DrYaling** [comment]
but  I can not run .exe patcher on mac and while run battlenet its goes to public link,or you mean I replace my wow.exe/wow-64.exe with patched one?

**Comment by Aokromes** [comment]
You need to use mac patcher and mac wow.

**Comment by DrYaling** [comment]
thanks Aokromes!
