### ISSUE TITLE
patch 19802 can't connect

### ISSUE THREAD

**Issue by DrYaling** [TrinityCore/TrinityCore#14450]
as title:
today I updated my client to 19802 and problem occur.I can't connect  to my server 6.x with game build 19634.any fix for this?

**Comment by tctwod** [comment]
Because we have 19702, need update soon..

**Comment by DrYaling** [comment]
do you know how to update tc server?

**Comment by xerkoss** [comment]
I synchronized with the parser, and stay hanged on the loading screen. new base its 19793.

**Comment by DDuarte** [comment]
TC will be updated to 6.1.2 Soon™ (today or tomorrow)
