### ISSUE TITLE
Fear doesn't work properly

### ISSUE THREAD

**Issue by immvp** [TrinityCore/TrinityCore#14458]
If player fears a target, the target will stand still for a few seconds and then blink somewhere.

From the targets POV everything is normal. 

How to reproduce:

1. Get feared / Fear someone
2. See results

**Comment by Nyeriah** [comment]
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

Also, this isn't something new, might be a duplicate

**Comment by immvp** [comment]
Yeah, it isn't something new. It's been posted about since 2011 I believe. And still hasn't been fixed. :)

**Comment by Aokromes** [comment]
It's duplicate.

**Comment by immvp** [comment]
Dublicate of which issue? Do you mind linking? :)

**Comment by Rushor** [comment]
chose for yourself in the 'search'field :)))

**Comment by Aokromes** [comment]
Nor to say no hash at all.
