### ISSUE TITLE
[3.3.5][Auto Shoot] As a hunter breaks on LOS

### ISSUE THREAD

**Issue by immvp** [TrinityCore/TrinityCore#14460]
As the title says, auto shoot breaks on LOS, but not properly. The client / server still tries to auto attack, as the auto shoot icon "blinks" red, as if it was functioning properly.

How to recreate the issue:
1. Auto attack a player
2. Player runs in LoS
3. Player runs out of LoS
4. Look at your auto shoot spell. It should still blink red, as if it was functioning properly, but you won't be throwing any attacks at the enemy. You'll just stand still.

Rev: latest.
##

**Comment by Aokromes** [comment]
There is no such thing as "latest".

**Comment by immvp** [comment]
#eccecc05066c8bcd678d1245a5638652c74c0e77

**Comment by Frytiks** [comment]
confirmed !

**Comment by MrSmite** [comment]
Couple notes:

* This is a similar issue to #13595
* This happens on older core: 42f1a0babfaac but not on even older: c28345e279f3 though I didn't look to see what's different
* This happens even with the Blizzard UI setting "Auto attack when in range" enabled

I noticed while playing on 42f1a0babfaac that whenever a mob would "run away in fear", my autoshot will get stuck if they run out of range and then back in range. I have to manually cancel attacking and start it again.

**Comment by Frytiks** [comment]
confirmed

**Comment by Roelv** [comment]
confirmed

**Comment by Rushor** [comment]
@immvp: test pr https://github.com/TrinityCore/TrinityCore/pull/14889 and the suggestion from the comments
