### ISSUE TITLE
client not working

### ISSUE THREAD

**Issue by Goten87** [TrinityCore/TrinityCore#14462]
i have wow 6.1.2 and its not working anymore with trinitycore server
when will the update happen for the new client

**Comment by Aokromes** [comment]
Yesterday.

**Comment by Goten87** [comment]
well i updated my server today so why cant i login then ?

**Comment by Nyeriah** [comment]
Repatch your client (log retain, repatch) and update your database

**Comment by Aokromes** [comment]
Also this is not a forum.
