### ISSUE TITLE
[3.3.5] Crash

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14469]
After 8 days i merge core, and all 15 minutes getting crash http://pastebin.com/TMdULZ03

Rev: https://github.com/TrinityCore/TrinityCore/commit/832234c47b90ad43b15451fcc0823822e2cebe57

DB: TDB11.58

**Comment by jackpoz** [comment]
if it's so easy to reproduce the crash (every 15 minutes), then please build in Debug and post a crashlog in Debug mode

**Comment by richard2012uk** [comment]
11.AnathemaCore rev. 2b7e40bc886f 2015-03-26 01:59:59 +0100 (master branch) (Unix, Release) (worldserver-daemon)

really ?

440.Loaded name data for 143931 characters  !!

Private servers are not supported 

Your core debug does not support your clamed version Rev: 832234c

please recompile and submit a proper debug if this issue does indeed exists

**Comment by jackpoz** [comment]
@Frytiks how did you fix the issue ?

**Comment by Frytiks** [comment]
It was my fault, i try to use this fix https://github.com/TrinityCore/TrinityCore/pull/14199, but its crashing.

**Comment by jackpoz** [comment]
ah ok, closing the issue then
