### ISSUE TITLE
Heirlooms Logging in

### ISSUE THREAD

**Issue by halcyon5** [TrinityCore/TrinityCore#14476]
I've tried and tried to find out what could be causing the Heirloom problem for over a month now. 
Heirlooms Login
![heirlooms login](https://cloud.githubusercontent.com/assets/11718731/6895374/165ca486-d6a5-11e4-9f34-38f31404a325.png)
Heirlooms Login Unequip After
![heirlooms login unequip after](https://cloud.githubusercontent.com/assets/11718731/6895383/2aedcc54-d6a5-11e4-925f-8a6994e15a56.png)
No Heirlooms Login
![no heirlooms login](https://cloud.githubusercontent.com/assets/11718731/6895392/4884eaea-d6a5-11e4-958e-fa95d65438ae.png)
Heirlooms Equipped after logging in without any items on.
![heirlooms equipped after logging in without any items](https://cloud.githubusercontent.com/assets/11718731/6895365/fd92aacc-d6a4-11e4-9457-34d7a6a6d68f.png)

As you can see from the photos this draws a large problem of incorrect stats, I cannot pinpoint what's causing it, or where to look at all now. If there is someone out there that may have this fixed or can direct me in the right location that would be great.

**Comment by Kittnz** [comment]
What branch and commit?

**Comment by halcyon5** [comment]
6.x branch, https://github.com/TrinityCore/TrinityCore/commit/58805427a319dbb9113e01de17c72e5d190a6d74

**Comment by Epicurus4** [comment]
Also see:
https://github.com/TrinityCore/TrinityCore/issues/14196

**Comment by halcyon5** [comment]
I'm glad you brought this up, but as you have stated it isn't producing results for some reason. Anyone else able to chime in with some knowledge as to why it wouldn't be updating properly?
