### ISSUE TITLE
3.3.5 crashes windows x64

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14479]
from https://github.com/TrinityCore/TrinityCore/commit/8bbe0114ddbc8ea8a70ee8b8c0baeb6d6fc4bd12
use command .modify sp .gps 

Exception code: E06D7363 
Fault address:  000007FEFD73A49D 01:000000000000949D C:\Windows\system32\KERNELBASE.dll

**Comment by tkrokli** [comment]
TrinityCore rev. 8bbe0114ddbc 2015-03-31 12:12:02 +0200 (Kodo_Roundup branch) (Win64, Release)

Unable to reproduce. The command only outputs: `Incorrect values.`

Possible cause: your database is not updated or aligned with the core. Your issue can be reproduced on a build where the DB is not up to date or out of sync with the core.

**Comment by w5860363** [comment]
@tkrokli  thanks
