### ISSUE TITLE
6.x.x. Character Changefaction Bug

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14472]
Build: 61ffd310789cc60d285abbabe505ac7f16243526

first Preview: http://i58.tinypic.com/2qd3cwm.jpg 

Second Preview: http://i58.tinypic.com/29vkt1v.jpg

**Comment by Vincent-Michael** [comment]
i check this tomorrow

**Comment by tctwod** [comment]
thanks vincent ;)

**Comment by Vincent-Michael** [comment]
a65007f55f8b274a45573133fda422a65844239d
