### ISSUE TITLE
[BUG] Extractor tools not work.

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#14487]
Rev. 7d3eb2077731e7a668dd87333d5c7e9ccb312f9e
Win 8.1 x64

Is not possible to extract DBC or Maps:

"No Locales Detected".

I try to remove all the locales and let only enUS, enGB, esES, changing off course the config.wtf.

From clean recent compiled extractor tools.

Thank you very much.

**Comment by DDuarte** [comment]
@n4ndo: make sure you are running the correct version of the extractors.
Running 3.3.5's mapextractor in a 6.x folder yields the error "No locales detected"
