### ISSUE TITLE
[4.3.4][6.x.x]Vehicle dissapear 

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#14498]
When you use a Vehicle that is controlled by server, they dissapear random of his way. That gives no direct place where this happens. You ride a line and one random point of this line you are dissmountet. 
This was testet with branch 4.3.4 https://github.com/TrinityCore/TrinityCore/commit/9ed21eb5b176986dd73c2a467e665fe449499155 but they same problem can in branch 6.x.x

**Comment by DDuarte** [comment]
4.3.4 branch is not being actively developed. Feel free to open an issue if you can verify it on the 6.x branches. Guesses and random shots are not enough.
