### ISSUE TITLE
[3.3.5] Trade issue

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14499]
Hi. Im using rev. 87ab218faab5e60af7910b72cde031e9dd46e639 TDB: 11.58

There is problem with Trade if you have enabled double side trade. 

How to do it?

1. Enable double side trade in config and in rbac

2. Get ali char with 30000 gold and horde char with 6 primordial saronite

3. Start trade 

4. Ali char in trade just add 10000 gold and horde char place into trade 6x primordial saronite

5. Acept trade. Look at your gold on ali. It's still same value. Maybe u need to try it more times

**Comment by mthsena** [comment]
Any custom script? because I tried and it works fine.

**Comment by Frytiks** [comment]
Thank you :+1:

**Comment by Frytiks** [comment]
How u can't reproduce ? @mthsena make a fix, and his fix work's very well.
