### ISSUE TITLE
[3.3.5a] L70 ETC Concert

### ISSUE THREAD

**Issue by Foldor** [TrinityCore/TrinityCore#14492]
4 of the 5 band members  spam the flare effect, when it should only be casted once when they spawn and once when the despawn.

```sql
UPDATE `smart_scripts` SET `event_flags`=1 WHERE  `entryorguid` IN (23625,23626,23624,23623) AND `source_type`=0 AND `id`=1 AND `link`=0;
````

**Comment by Kittnz** [comment]
@Foldor i don't see it happen when they despawn: https://www.youtube.com/watch?v=Z6LGdT3s47E
