### ISSUE TITLE
the last trinitycore and tdb give me a dberror at start

### ISSUE THREAD

**Issue by lwyjdgv** [TrinityCore/TrinityCore#14501]
Spell 43770 Effect: 43789 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 53099 Effect: 53098 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 54640 Effect: 54643 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 55288 Effect: 55289 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!
SmartAIMgr::LoadSmartAIFromDB: Entry 20349 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 20345 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 20346 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 20347 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 20348 SourceType 0, Event 0, Link Event 1 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 4498 SourceType 2, Event 4, Link Event 5 not found or invalid.

**Comment by Aokromes** [comment]
duplicate.

**Comment by Aokromes** [comment]
#13707
