### ISSUE TITLE
6.x compile

### ISSUE THREAD

**Issue by Dude100** [TrinityCore/TrinityCore#14504]
compile fail:3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[ 15%] Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o
In file included from /home/dude/servers/TrinityCore/src/server/game/Globals/ObjectMgr.h:27:0,
                 from /home/dude/servers/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.h:10,
                 from /home/dude/servers/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.cpp:1:
/home/dude/servers/TrinityCore/src/server/game/Entities/GameObject/GameObject.h:804:22: error: declaration of ‘InvisibilityType GameObjectAddon::InvisibilityType’ [-fpermissive]
     InvisibilityType InvisibilityType;
                      ^
In file included from /home/dude/servers/TrinityCore/src/server/game/Maps/Map.h:28:0,
                 from /home/dude/servers/TrinityCore/src/server/game/Entities/Object/Object.h:26,
                 from /home/dude/servers/TrinityCore/src/server/game/Maps/MapManager.h:22,
                 from /home/dude/servers/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.h:4,
                 from /home/dude/servers/TrinityCore/src/server/game/PrecompiledHeaders/gamePCH.cpp:1:
/home/dude/servers/TrinityCore/src/server/game/Miscellaneous/SharedDefines.h:1692:6: error: changes meaning of ‘InvisibilityType’ from ‘enum InvisibilityType’ [-fpermissive]
 enum InvisibilityType
      ^
make[2]: *** [src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o] Error 1
make[1]: *** [src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/all] Error 2
make: *** [all] Error 2

**Comment by DDuarte** [comment]
@streetrat: ^ error + typo at https://github.com/TrinityCore/TrinityCore/commit/9d59d038f8b09ed036448e755cb0b102396a4ca1#diff-1596ecd5424665946209f97259f1dba8R1114

**Comment by Dude100** [comment]
Ty

**Comment by DDuarte** [comment]
Fixed in 23e8a3ce2928458649d94408d5deffb67339b1d6 and c5bbc9287d1e8ae9335598780ebd7db47b522fb2
