### ISSUE TITLE
[3.3.5] The Obsidian Sanctum (Magma)

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#14506]
Class(es) involved: All the classes with pets.

Steps taken in order for bug to occur: at the Obsidian Sanctum instance, go to the lava with your pet, and dismiss it or let it die.

Expected output: Your pet will have the magma aura on it, even if resummoned,killed, or character relogged.

Additional information: The Only way to remove it, is by going back to the lava at the Obsidian sanctum and then out of it or .unaura

http://www.wowhead.com/spell=57634/magma

Rev: 1184e98da1690f1a12e5939d29fec2f03bef4710

**Comment by Demonid** [comment]
Fixed, i'll make a PullRequest once i know how...

**Comment by jackpoz** [comment]
can this be closed now ?

**Comment by Demonid** [comment]
@jackpoz If the PR is accepted i guess yes, if not, it still an issue.

**Comment by Rushor** [comment]
merged with https://github.com/TrinityCore/TrinityCore/issues/16480 to a more general issue. thx for the fixtry @Demonid  anyway :)

**Comment by L30m4nc3r** [comment]
@Rushor reopen issue, pull request closed TC Community.

**Comment by Aokromes** [comment]
merged with #16480

**Comment by Rushor** [comment]
> merged with #16480 to a more general issue. thx for the fixtry @Demonid anyway :)

no need to reopen

**Comment by L30m4nc3r** [comment]
ah ye, thanks subscribe.
