### ISSUE TITLE
Got this from sniffing but not sure if this any good for 6.X 

### ISSUE THREAD

**Issue by scorched-wow** [TrinityCore/TrinityCore#14503]
DELETE FROM `quest_objectives` WHERE `Id` IN (276338, 273559, 275257, 275258, 275259, 276374, 275260, 276376, 275262, 275263, 276379, 276380, 276382, 276385, 276386, 274717, 274718, 274719, 276391, 276392, 274721, 276393, 276394, 274723, 276395, 274724, 275945, 275946, 275408, 274300, 275431, 275432, 275436, 275439, 277669, 277670, 277671, 277672, 277673, 276021, 275472, 277730, 277190, 277197, 274979, 276673, 274456, 274458, 274462, 274463, 274464, 274465, 273928, 275621, 276758, 276759, 275682, 256191, 256192, 276252, 276253, 276254, 276255, 276264, 276266, 276267, 276268);
INSERT INTO `quest_objectives` (`Id`, `QuestId`, `Type`, `StorageIndex`, `ObjectID`, `Amount`, `Flags`, `UnkFloat`, `Description`, `VerifiedBuild`) VALUES
(276338, 36070, 0, 1, 88960, 1000, 92, 0.1, '', 19831), -- 276338
(273559, 34794, 0, 0, 81563, 1, 28, 0, 'Flight taken', 19831), -- 273559
(275257, 36819, 15, -1, 0, 1, 0, 0, 'Disrupt the Warsong', 19831), -- 275257
(275258, 36819, 0, 0, 86955, 100, 92, 1, 'Defeat Minus Enemies', 19831), -- 275258
(275259, 36819, 0, 1, 86957, 34, 92, 3, 'Defeat Tier 1 Enemies', 19831), -- 275259
(276374, 36070, 0, 2, 83990, 4, 92, 30, '', 19831), -- 276374
(275260, 36819, 0, 2, 86958, 13, 92, 8, 'Defeat - Elite', 19831), -- 275260
(276376, 36070, 0, 4, 83975, 25, 92, 4, '', 19831), -- 276376
(275262, 36819, 0, 3, 87574, 7, 92, 15, 'Defeat Rare Elites', 19831), -- 275262
(275263, 36819, 0, 4, 86960, 5, 92, 20, 'Defeat - 5-man Miniboss', 19831), -- 275263
(276379, 36070, 0, 7, 83980, 25, 92, 4, '', 19831), -- 276379
(276380, 36070, 0, 8, 83983, 25, 92, 4, '', 19831), -- 276380
(276382, 36070, 0, 10, 83976, 34, 92, 3, '', 19831), -- 276382
(276385, 36070, 0, 13, 83982, 34, 92, 3, '', 19831), -- 276385
(276386, 36070, 0, 14, 83984, 9, 92, 12, '', 19831), -- 276386
(274717, 35641, 0, 0, 85260, 500, 92, 0.2, 'Slay Minus Mobs', 19831), -- 274717
(274718, 35641, 0, 1, 85261, 100, 92, 1, 'Slay Normal Mobs', 19831), -- 274718
(274719, 35641, 0, 2, 85265, 50, 92, 2, 'Collect/Interact (Minor)', 19831), -- 274719
(276391, 36070, 3, 15, 89076, 100000, 92, 0, '', 19831), -- 276391
(276392, 36070, 2, 16, 233824, 100000, 92, 0, '', 19831), -- 276392
(274721, 35641, 0, 4, 82531, 34, 92, 3, 'Slay High HP Mobs', 19831), -- 274721
(276393, 36070, 2, 17, 233791, 100000, 92, 0, '', 19831), -- 276393
(276394, 36070, 2, 18, 233803, 100000, 92, 0, '', 19831), -- 276394
(274723, 35641, 0, 6, 85262, 13, 92, 8, 'Slay Elite Mobs', 19831), -- 274723
(276395, 36070, 2, 19, 233805, 100000, 92, 0, '', 19831), -- 276395
(274724, 35641, 0, 7, 85263, 5, 92, 20, 'Slay Rare Elites/Events/Minibosses', 19831), -- 274724
(275945, 36819, 2, 10, 237263, 100000, 92, 0, 'Tracking interact Chest', 19831), -- 275945
(275946, 36819, 2, 11, 237264, 100000, 92, 0, 'Tracking interact Chest', 19831), -- 275946
(275408, 36921, 0, 0, 86721, 500, 0, 0, 'Human Players slain', 19831), -- 275408
(274300, 36070, 15, -1, 0, 1, 0, 0, 'Arakkoa Forces Thwarted', 19831), -- 274300
(275431, 36819, 0, 5, 86992, 17, 92, 6, 'Burn Wolf Den', 19831), -- 275431
(275432, 36819, 0, 6, 86947, 50, 92, 2, 'Recover Stolen Goods', 19831), -- 275432
(275436, 36819, 0, 7, 87017, 17, 92, 6, 'Burn Barracks', 19831), -- 275436
(275439, 36819, 0, 8, 87024, 17, 92, 6, 'Burn Tavern', 19831), -- 275439
(277669, 37961, 1, 0, 122565, 1, 0, 0, 'Bass Blaster', 19831), -- 277669
(277670, 37961, 1, 1, 122566, 1, 0, 0, 'Laz-Tron Disc Reader', 19831), -- 277670
(277671, 37961, 1, 2, 122567, 1, 0, 0, '', 19831), -- 277671
(277672, 37961, 1, 3, 122568, 1, 0, 0, '', 19831), -- 277672
(277673, 37961, 1, 4, 122569, 1, 0, 0, '', 19831), -- 277673
(276021, 36070, 0, 0, 84010, 100, 92, 1, 'Arakkoa Forces Thwarted', 19831), -- 276021
(275472, 36614, 16, 1, 824, 2000, 4, 0, 'Garrison resources gathered', 19831), -- 275472
(277730, 38346, 1, 1, 122618, 5, 0, 0, '', 19831), -- 277730
(277190, 37164, 0, 0, 76407, 1, 0, 0, '', 19831), -- 277190
(277197, 37165, 0, 0, 83846, 1, 0, 0, '', 19831), -- 277197
(274979, 36614, 14, 0, 38531, 1, 0, 0, 'Upgrade your garrison to Tier 3', 19831), -- 274979
(276673, 35641, 0, 3, 89160, 1, 12, 0, 'Give Shackle Key', 19831), -- 276673
(274456, 36228, 1, 1, 114241, 1, 0, 0, '', 19831), -- 274456
(274458, 36226, 14, 0, 37564, 1, 0, 0, 'Explore The Molten Quarry', 19831), -- 274458
(274462, 36226, 14, 1, 37582, 1, 0, 0, 'Explore The Road of Glory', 19831), -- 274462
(274463, 36226, 14, 2, 37584, 1, 0, 0, 'Explore Brute''s Rise', 19831), -- 274463
(274464, 36226, 14, 3, 37586, 1, 0, 0, 'Explore Ashmaul Burial Grounds', 19831), -- 274464
(274465, 36226, 14, 4, 37588, 1, 0, 0, 'Explore The Amphitheater Of Annihilation', 19831), -- 274465
(273928, 35641, 15, -1, 0, 1, 0, 0, 'Bloodmaul Stronghold Assaulted', 19831), -- 273928
(275621, 36819, 0, 9, 87264, 50, 92, 2, 'Destroy Warsong totem', 19831), -- 275621
(276758, 36070, 3, 3, 89063, 100000, 92, 0, '', 19831), -- 276758
(276759, 36070, 3, 5, 89061, 100000, 92, 0, '', 19831), -- 276759
(275682, 37165, 1, 3, 118627, 1, 0, 0, '', 19831), -- 275682
(256191, 1689, 0, 0, 5676, 1, 0, 0, '', 19831), -- 256191
(256192, 1689, 1, 1, 6928, 1, 0, 0, '', 19831), -- 256192
(276252, 37475, 0, 2, 84483, 1, 0, 0, 'Gronnling Breaker slain', 19831), -- 276252
(276253, 37475, 0, 0, 78936, 3, 0, 0, 'Goren Iron-eater slain', 19831), -- 276253
(276254, 37475, 0, 1, 78557, 5, 0, 0, 'Goren Hatchling slain', 19831), -- 276254
(276255, 37475, 0, 3, 78935, 3, 0, 0, 'Rubyspike Goren slain', 19831), -- 276255
(276264, 37478, 0, 2, 84837, 3, 0, 0, 'Marsh Creature slain', 19831), -- 276264
(276266, 37478, 0, 1, 84350, 6, 0, 0, 'Podling Poker slain', 19831), -- 276266
(276267, 37478, 0, 3, 83720, 3, 0, 0, 'Sporebat Darter slain', 19831), -- 276267
(276268, 37478, 0, 4, 84349, 1, 0, 0, 'Marsh Monstrosity slain', 19831); -- 276268

**Comment by Rushor** [comment]
dat title xD

**Comment by DDuarte** [comment]
@scorched-wow: put your sniffs in http://www.trinitycore.org/f/forum/13-wdbadbsniffs/ and we'll take care of extracting data from them. Thanks.

**Comment by scorched-wow** [comment]
Alright, but how does i upload files on their? or i have to upload to upload site?

**Comment by DDuarte** [comment]
You can use our own upload service like https://mega.co.nz/ or https://www.mediafire.com/

**Comment by scorched-wow** [comment]
ok thank
