### ISSUE TITLE
SAI: SMART_EVENT_OOC_LOS first trigger

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14516]
rev. 8d58bb93c903
This event has CooldownMin CooldownMax as params, the problem is for the first time the event must be triggered without a delay, but actually the (CooldownMin CooldownMax) is applied also for the first time trigger. In same cases as an event which must be repeated every 10min the first player must wait 10min before the event starts.

**Comment by dr-j** [comment]
confirmed,

**Comment by Killyana** [comment]
If someone can have a look at this issue, it's pretty annoying for the first player to wait sometimes 10 min before the event starts.

**Comment by robinsch** [comment]
Try to remove case SMART_EVENT_OOC_LOS: from SmartScript::InitTimer.

**Comment by Killyana** [comment]
Yes it fix the issue, this also must be done for SMART_EVENT_IC_LOS, can you open a PR?
