### ISSUE TITLE
[6.x] Procs without a triggered spell need a own hook.

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14513]
Rev.: a3a7d65c20cd92466309ee122c6d5032a869f0ab
Branches: 4.3.4 and 6.0.x

Since Cataclysm there are some procs present that are using a proc chance to trigger a proc but the proc itself doesnt trigger any spell. In this case the current proc hooks doesn't sense the proc as procced. Right now only the  CheckProc hook is working for that kind of spells.

Example spell id: ID - 74976 Disorienting Roar
This spell mechanic is suposed to proc on any successful casted spell to remove the proc aura from the target. So the proc itself only checks the proc event for a cast for a scripted event to remove that aura.
##

**Comment by joschiwald** [comment]
you need to enable proc for this aura type in `InitTriggerAuraData()` in Unit.cpp

**Comment by matanshukry** [comment]
The spell doesn't require it any more, and a mechanic for procing without a trigger spell already exist, with hooks in spell scripts.

**Comment by offl** [comment]
Can be closed?

**Comment by matanshukry** [comment]
yup
