### ISSUE TITLE
3.3.5a Quest 12291 - The Forgotten Tale

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#14514]
The required NPC's are not completing their part of the quest.
TrinityCore rev. 79696e08718e 2015-04-07 06:12:37 +0200 (3.3.5 branch) (Win64, Release)

**Comment by Killyana** [comment]
For the credit action the comments says "InvokerCast" but the action is 11 (https://github.com/TrinityCore/TrinityCore/blob/98f98fa17fde4a1294b3e9227973ce5df70fbd6b/sql/old/3.3.5a/TDB40_to_TDB41_updates/world/2011_05_18_07_world_sai.sql) also there's this commit (https://github.com/TrinityCore/TrinityCore/blob/98ca9a77491196ef501093572867236712d74938/sql/old/4.3.4/TDB5_to_TDB6_updates/world/138_2014_07_01_01_world_misc.sql)
Anyway this will fx the issue:
``` sql
UPDATE `smart_scripts` SET `action_type`=85 WHERE `entryorguid` IN (27226, 27224, 27225, 27229) AND `source_type`=0 AND `id`=0;

**Comment by Younguns** [comment]
Thanks, that done the trick.

**Comment by DDuarte** [comment]
Don't close the issue, it was not fixed in the repo...

**Comment by Younguns** [comment]
Sorry

**Comment by dr-j** [comment]
hmm Déjà vu

I remember fixing this same way looks like never pushed to tc though xd
