### ISSUE TITLE
[dk][Talent/Spell] Death Knight (Dancing Rune Weapon) 

### ISSUE THREAD

**Issue by Gonzywow** [TrinityCore/TrinityCore#14517]
dancing rune weapon no work, please fix

**Comment by Aokromes** [comment]
reading skills no work, please fix https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6192
