### ISSUE TITLE
Arcane Missiles 4.3.4 

### ISSUE THREAD

**Issue by Sirief** [TrinityCore/TrinityCore#14510]
Hi, 

The spell "Arcane Missiles"  (http://www.wowhead.com/spell=5143/arcane-missiles) doesn't work on 4.3.4 (Core compiled on March 29). Tested with gobelin and Troll.
Any idea ?

Thanks

**Comment by Aokromes** [comment]
Fill requirements at https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Aokromes** [comment]
No answer after 3 days, closing.
