### ISSUE TITLE
6.x: Error while choosing a quest reward

### ISSUE THREAD

**Issue by vegax87** [TrinityCore/TrinityCore#14518]
In every quest with 4 reward choices, it appears an error like this one:

Error in CMSG_QUESTGIVER_CHOOSE_REWARD: player Sage (GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1) tried to get invalid reward (57389) (possible packet-hacking detected)

and the quest cannot be completed without reward.

**Comment by Aokromes** [comment]
Fill requierements https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by vegax87** [comment]
I have all the requirements and successfully run both bnetserver & worldserver, while other quests with predefined rewards work without problems.
I suppose there are some missing values in quest_template

**Comment by streetrat** [comment]
the new questrewardid - based rewards are not yet iplemented

**Comment by Aokromes** [comment]
@vegax87 no, you don't have wrote what revision you are running, not even supplied sample of quest.

**Comment by streetrat** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/e5675412735a33f05f9c3215fb0cc7327a800c6c
