### ISSUE TITLE
  [6.x] npc does not work guildmaster and auctioneer 

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#14523]
Build:  https://github.com/TrinityCore/TrinityCore/commit/e57de378a602ff0c0b404247c8ce2646295ff9db

DB: TDB 6.1.2

guildmaster and auctioneer can't work so can't creat guild and sell item in auction

**Comment by frozen4** [comment]
npctrainer does not work the same

**Comment by Aokromes** [comment]
Read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
