### ISSUE TITLE
[3.3.5] Core/Spells: Intervene (Pet talent)

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14520]
Rev: https://github.com/TrinityCore/TrinityCore/commit/210e45e303b1ae33ff4bb2c21727b27ae58f0a6c

DB: TDB 11.58

As describe here http://www.wowwiki.com/Intervene_%28pet%29

Intervene is a level 20 pet ability that allows the hunter's pet to intervene an attack towards a group member.

When you use it on party member, u just see like charge effect, but pet stay on position, and not charge to target position.

Possible problem is in case SPELL_EFFECT_CHARGE in spell.cpp
##

**Comment by Frytiks** [comment]
No respond here ?

**Comment by Langerz82** [comment]
The problem is command follow enabled, the AI returns to the Owner upon spell cast. I'm looking into it to see if I can provide a fix.

**Comment by Killyana** [comment]
Cannot reproduce in rev. ffede34ba9a3
