### ISSUE TITLE
6.x Weapon Hunter bug

### ISSUE THREAD

**Issue by fallcons** [TrinityCore/TrinityCore#14521]
hi,
We can't see the weapon of the hunter.
Thx.

**Comment by Zerixx** [comment]
What? 

Do you mean to say the weapon doesn't appear? or doesn't exist?

**Comment by fallcons** [comment]
Appear

**Comment by tctwod** [comment]
Show this pull request: https://github.com/TrinityCore/TrinityCore/pull/14493

**Comment by fallcons** [comment]
Okay thx tctwod and zerixx
