### ISSUE TITLE
Vehicle::~Vehicle inaccessible from Unit.cpp

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#14529]
__Rev:__ 

*335:* 42f1a0babfaacf or newer (possibly older revs. too)
*6.x:* 653954c14d61 (presumably all revs. since 6.x was forked off an older 335)

__Bug:__

Visual studio displays the following warning in *Unit::RemoveVehicleKit()* at the line *delete m_vehicleKit;*

> *Vehicle::~Vehicle() is inaccessible*

__Notes:__

* The warning is displayed in the editor, not the output during compile
* It does not prevent compiling
* I did not do any sort of profiling to see if this would lead to a memory leak

**Comment by Shauren** [comment]
IDE bug. (Vehicle has a friend declaration for Unit::RemoveVehicleKit)

**Comment by MrSmite** [comment]
> IDE bug. (Vehicle has a friend declaration for Unit::RemoveVehicleKit)

The error is saying that *Vehicle::~Vehicle()* is inaccessible when you delete the object, nothing about the function *RemoveVehicle()* which is true since the destructor is *Protected*

**Comment by Shauren** [comment]
Read up on friendship in C++ - Unit::RemoveVehicleKit has access to Vehicle destructor (ref the link you posted - we do not delete it using base class pointer)

**Comment by MrSmite** [comment]
> Read up on friendship in C++ - Unit::RemoveVehicleKit has access to Vehicle destructor (ref the link you posted - we do not delete it using base class pointer)

Thanks, friendship in C++ is different than what I'm used to from .NET which is even more different than classic VB.
