### ISSUE TITLE
[6.x] You can not compile

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14525]
core revisi 0953bcf73f01ab5d85bb8665fbf8451d0ed460b3

../scripts/libscripts.a(cs_debug.cpp.o): In function `debug_commandscript::HandleDebugSendPlaySceneCommand(ChatHandler*, char const*)':
cs_debug.cpp:(.text._ZN19debug_commandscript31HandleDebugSendPlaySceneCommandEP11ChatHandlerPKc[_ZN19debug_commandscript31HandleDebugSendPlaySceneCommandEP11ChatHandlerPKc]+0x17d): undefined reference to `vtable for WorldPackets::Scenes::PlayScene'
cs_debug.cpp:(.text._ZN19debug_commandscript31HandleDebugSendPlaySceneCommandEP11ChatHandlerPKc[_ZN19debug_commandscript31HandleDebugSendPlaySceneCommandEP11ChatHandlerPKc]+0x2b0): undefined reference to `WorldPackets::Scenes::PlayScene::Write()'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:208: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1339: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Shauren** [comment]
Thou shalt not compile.

**Comment by deadmanevil** [comment]
then that is the error

**Comment by Vincent-Michael** [comment]
e8b54b7ae823622cca5647b3571a7740c421aa41
