### ISSUE TITLE
DB/Quest: Fixing War is Hell and Monitoring the Rift: Cleftcliff Anomaly

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14534]
Core revision:https://github.com/TrinityCore/TrinityCore/commit/61aa5ec412ee462e76f8d71d888706b02bfed372
DB version: TDB 335.58
Script version: smart_ai
Quest: Monitoring the Rift: Cleftcliff Anomaly http://www.wowhead.com/quest=11576
Quest Borean - Westrift Cleftcliff Anomaly Rhydalla http://www.wowhead.com/npc=25310

After the completion of the task to give up the task can not be completed again

A similar situation also appears in the
Alliance Corpse http://www.wowhead.com/npc=24009
Forsaken Corpse http://www.wowhead.com/npc=24010

Please excuse my English.

**Comment by Killyana** [comment]
``` sql
UPDATE `smart_scripts` SET `event_flags`=0 WHERE `entryorguid`=25310 AND `source_type`=0 AND `id`=0;
