### ISSUE TITLE
SQL / Fix Improper CompletedText Q=1578

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#14531]
__Rev:__ N/A

__DB:__ TDB_full_335.57_2014_10_19 with updates to core 42f1a0babfaacf64df31a934288979f8edfec940

__Bug:__

[Quest 1578](http://www.wowhead.com/quest=1578/supplying-the-front) has `CompletedText` that tells you to go to *North Gate Pass in Dun Morogh* however the quest NPC is at the [other end of the map](http://www.wowhead.com/npc=6030/thorvald-deepforge)

__Fix:__

```SQL
UPDATE `quest_template` SET `CompletedText`='Return to Thorvald Deepforge in the southern guard tower of Loch Modan.' WHERE `id`=1578;
```

__Note:__

* Players already on the quest will need to delete *questcache.wdb* to see the change

**Comment by DDuarte** [comment]
I've consulted with Sniffs Warlords (30/06/2010, 3.3.5 12340) and they say that the text should be "Return to Thorvald Deepforge at North Gate Pass in Dun Morogh." so I'm not quite sure what to do with this issue/fix.

**Comment by MrSmite** [comment]
> Perhaps Thorvald Deepforge should be spawned somewhere else?

All sources I could find say he's in the Valley of Kings, Loch Modan. Perhaps the sniffs are wrong somehow?

http://www.wowwiki.com/Thorvald_Deepforge
http://www.wowhead.com/npc=6030/thorvald-deepforge
http://www.thottbot.com/npc=6030
http://wow.gamepedia.com/Thorvald_Deepforge

**Comment by flippy84** [comment]
http://mmo4ever.com/wow/quest.php?id=1578

Maybe they just want to send the player the right way from north gate pass in dun morogh to south gate pass in loch modan?

**Comment by MrSmite** [comment]
> Maybe they just want to send the player the right way from north gate pass in dun morogh to south gate pass in loch modan?

Only problem with that is you won't see the "?" on the map because NGP is still in Dun Morogh. Of course there's always Google but some players I'd imagine would still get "lost" ;)

**Comment by MrSmite** [comment]
Going to close this since it's "blizzlike". At least it will be here on Github for people who want to apply it as "custom".
