### ISSUE TITLE
[Crash] Unit::ProcDamageAndSpellFor

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#14532]
http://pastebin.com/U5Ld6K5F

08a62f19b808a347aae56b4f5a689233c6a03db0

**Comment by jackpoz** [comment]
related to d23538ce568773f474ef20b4ca8217e0b218e65e

**Comment by jackpoz** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/5b5c0938da0faa5d3fcf4fd062fa712a448a67ff
