### ISSUE TITLE
[6.x] Gameobject(Chair) Interaction

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14545]
rev: 011e14bf057e8d395c171e15d2e2f916332caa0b

When you right-click a chair, others see you sitting on the chair as it is supposed to be, but you see yourself standing on the chair

**Comment by YaGa** [comment]
seems to be fixed in ca1f42d4091a91d3bd50ccc52012c836c43958f6

**Comment by Aokromes** [comment]
You can close the tickets you open :)
