### ISSUE TITLE
[3.3.5] Bug Trial of the crusader

### ISSUE THREAD

**Issue by oelsaid** [TrinityCore/TrinityCore#14543]
Rev. cc4f86cc2bf4+ 2015-04-10 (branch 3.3.5) (Win64, Release)
TDB 335.57 + Updates
NO
Linux ubuntu
the anja this in the wrong place and that no root, and not of to attack it because it is behind the invisible wall and the bosses do not leave it.

**Comment by Nyeriah** [comment]
Disable mmaps for toc (@Aokromes weren't they disabled there a while ago?) 

Anyway duplicate https://github.com/TrinityCore/TrinityCore/issues/9053

**Comment by oelsaid** [comment]
if there is an update in sql or correction is to by a play for the Anjas to the correct location used .npc moves Bugo.
