### ISSUE TITLE
[3.3.5] Beast Lore Fails on Low Level Target

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#14541]
**335 Core:** 42f1a0babfaacf64df31a934288979f8edfec940

> Note: head is identical to this revision in Spell::SelectSpellTargets() where I believe
> is the [problem (comment)](https://github.com/TrinityCore/TrinityCore/issues/14541#issuecomment-92078512) so I did not pull and compile it.

**DB:** TDB_full_335.57_2014_10_19 plus updates

**Bug:**

The spell [Beast Lore](http://www.wowhead.com/spell=1462/beast-lore) fails "Target is too low level" when cast on low level targets. There is no indicated restriction in the tooltip.

**Details:**

At level 24 I was messing around and tried casting this on a level 8 Stag and got this error. I checked wowhead and there are no mentions in the comment section about level restrictions. The spell is intended to give information on any beast in the game for the Hunter to see if it is tameable, and other information.

**Notes:**

> - Using _NPC add_ and _NPC set level_ I determined that this error happens on any creature that is more than 10 levels lower than the hunter
##

**Comment by MrSmite** [comment]
Update: The issue appears to be in *Spell::SelectSpellTargets()*

**Comment by DDuarte** [comment]
Meta: `335 Core: All DB: N/A` is as good as saying `latest version`, it doesn't really help so please give a revision where the issue is known to happen.

**Comment by MrSmite** [comment]
> Meta: 335 Core: All DB: N/A is as good as saying latest version, it doesn't really help so please give a revision where the issue is known to happen.

Sorry, I did that because a search didn't turn up any issues resolving this so I assumed it had never been reported.

**Comment by MrSmite** [comment]
This is a temporary *HACK* fix that I've been using, maybe @click will come up with something else...

__*Spell::SelectSpellTargets()*__

```c++
                 // remove targets which did not pass min level check
                 if (m_auraScaleMask && ihit->effectMask == m_auraScaleMask)
                 {
                    // HACK for spells that should not have level restriction but this function
                    // causes them to fail. Add more CASE statements as needed.
                    switch (m_spellInfo->Id)
                     {
                        case 1462:  // Beast Lore
                            break;  // not continue or stuck in infinite loop, BREAK allows us to hit the ++ below

                        default:
                        {
                            // Do not check for selfcast
                            if (!ihit->scaleAura && ihit->targetGUID != m_caster->GetGUID())
                            {
                                m_UniqueTargetInfo.erase(ihit++);
                                continue;
                            }
                            break;
                        }
                     }
                 }
                 ++ihit;
```

**Comment by McClainJ** [comment]
I took a look at this problem and I have a possible solution I am testing.
I added a method to class Spell, the method is called **BlackListMinLevel()**, 
This method returns true for any spell added as a case. I am using names I defined
in **enum SpellMinLevelBlackList** in **Spell.h** for the black-list. This function is invoked
and check inside the **Spell::SelectSpellTargets()** method, thus allowing certain spells 
to ignore a minimum level. I already added Beast_Lore as an example. 

**If this approach is not acceptable please tell me how you would like this fixed so that I may
provide assistance. If this is acceptable, I shall post this as a pull request. Code is as follows.**

_Project is currently building, wow this takes a long time to build._
**BlackListMinLevel Method**
> bool Spell::BlackListMinLevel()
> {
>     // Check against spells listed in SpellMinLevelBlackList Enum.
>     switch (m_spellInfo->Id)
>     {    
>         case SpellMinLevelBlackList::BEAST_LORE : return true;
>         // Add other blacklisted spells here.
>         default : return false;
>     }
>     
>     return false;
> }

**enum SpellMinLevelBlackList**

> enum class SpellMinLevelBlackList
> {
>     BEAST_LORE = 1462 // Beast Lore Spell ID
>         
> };

**Method added to class Spell**

> void InitExplicitTargets(SpellCastTargets const& targets);
> void SelectExplicitTargets();
> 
> bool BlackListMinLevel();
>        
> void SelectSpellTargets();
> void SelectEffectImplicitTargets(SpellEffIndex effIndex, SpellImplicitTargetInfo const& targetType, uint32& processedEffectMask);
> void SelectImplicitChannelTargets(SpellEffIndex effIndex, SpellImplicitTargetInfo const& targetType);

**Method call inside SelectSpellTargets()**

>                 // remove targets which did not pass min level check
>                 if (m_auraScaleMask && ihit->effectMask == m_auraScaleMask)
>                 {
>                     // Do not check for non min-level spells
>                     if(BlackListMinLevel())
>                     {
>                         continue;
>                     }
>                     
>                     // Do not check for selfcast
>                     if (!ihit->scaleAura && ihit->targetGUID != m_caster->GetGUID())
>                     {
>                         ihit = m_UniqueTargetInfo.erase(ihit);
>                         continue;
>                     }

**Comment by McClainJ** [comment]
idk why none of my formatting stayed in half those quote, but I assure you , I followed the standards listed in your github page.

**Comment by tkrokli** [comment]
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by McClainJ** [comment]
Thanks for the formatting tip dude.

**Comment by MrSmite** [comment]
Looks interesting.

One suggestion: Since the function returns a ```C++ bool ```, you might want to name it something like ```C++ IsBlacklistMinLevel() ``` or ```C++ HasBlacklistMinLevel() ```
