### ISSUE TITLE
[6.x] [Crash] Exception code: C0000094 INT_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14542]
rev: 15d4bf8a61b66dcea186efd96f02fa697623aa60

cannot find out when this happens

file was too large for pastebin: http://chopapp.com/#vl3ob5c3

**Comment by DDuarte** [comment]
Your link displays an empty page

**Comment by YaGa** [comment]
just noticed it does loadvery long..
https://gist.github.com/YaGa/396b504b89c7ba58ac88

**Comment by Shauren** [comment]
You tried manually spawning a (custom?) transport gameobject, obviously it will crash

**Comment by DDuarte** [comment]
Faulty line
```cpp
float timer = float(m_goValue.Transport.PathProgress % GetUInt32Value(GAMEOBJECT_LEVEL));
```

A check for zero wouldn't hurt, even if it's a custom spawn or bad DB data.

**Comment by YaGa** [comment]
thanks a lot guys!

**Comment by YaGa** [comment]
if ((GetUInt32Value(GAMEOBJECT_LEVEL) != 0) && (float(GetUInt32Value(GAMEOBJECT_LEVEL)) * 65535.0f != 0))
						{
							float timer = float(m_goValue.Transport.PathProgress % GetUInt32Value(GAMEOBJECT_LEVEL));
							pathProgress = int16(timer / float(GetUInt32Value(GAMEOBJECT_LEVEL)) * 65535.0f);
						}

is working fine for me, but is it supposed to be this way?

**Comment by DDuarte** [comment]
Math, not even once.

0 * x = 0, you don't need the 2nd part of the if

**Comment by YaGa** [comment]
oh, for sure. thats embarrassing
