### ISSUE TITLE
[Tools] connection_patcher | EX: Wrong

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#14549]
Rev. 4ced9a44807d
Windows 8.1 x64

Hello,

I try to patch my client with the connection_patcher from 6.1.2, but i receive this msg:

EX: Wrong number of arguments: Missing client file
An error occurred, Press Enter to continue...

I put the connection patcher inside de WoW folder, i have "wow.exe", "wow-64.exe", "World of Warcraft Launcher.exe", but still dont work.

Any Ideas?

Thanks.

**Comment by Aokromes** [comment]
Fill requirements of https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by DDuarte** [comment]
The first (and only) argument of the patcher is the executable name.
