### ISSUE TITLE
[6.x] WoW version indipendent from real battle.net servers

### ISSUE THREAD

**Issue by gegge** [TrinityCore/TrinityCore#14548]
When retail updates to a new patch, wow_patched.exe of the old patch won't work.
If this can be resolved, a person can play old TC rev while waiting new opcodes to be updated

**Comment by DDuarte** [comment]
If you do not let Battle.net do any update you can still get in-game with the older version. I don't see how this is a problem...

**Comment by gegge** [comment]
Nope, i tried before this last patch, i never use the bnet app.. But it seems that the exe know when retail servers update

**Comment by Aokromes** [comment]
edit config.wtf and set patchlist to localhost.

**Comment by YaGa** [comment]
or just run wow.exe with arguments  -uid wow_engb -noautolaunch64bit

**Comment by gegge** [comment]
Noautolaunch won't work, se the next update i try aokromes solution

**Comment by Jarts37** [comment]
You have to edit your wow.exe and change CDNS/Versions  patch with your actual build

**Comment by gegge** [comment]
With Ida?

**Comment by Jarts37** [comment]
You can do it with hex editor or with notepad, and everything else , you have just to edit String values

**Comment by Aokromes** [comment]
This was fixed long time ago.
