### ISSUE TITLE
[6.x] Attacking creature "Riverpaw Bandit" in Westfall

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14558]
TrinityCore rev. 909a5ebf14de+
Sometimes it´s impossible to attack this creature until i face my back to him.
Seems that this creature is jumping behind me but it´s not updated for my view.
Attacking 1-2 of these creature is enough to see the issue...
Position x=56 y=68
##

**Comment by Aokromes** [comment]
read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md before you post any new bug report.

**Comment by tkrokli** [comment]
Post your core revision hash, so your issue can be tracked. Read links on how to document issues :
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by Yalunima** [comment]
TrinityCore rev. 909a5ebf14de+

**Comment by Killyana** [comment]
This issue could be reproduce it on 7.x?

**Comment by Aokromes** [comment]
no answer after more than 1 month, closing.
