### ISSUE TITLE
[6.x] Priest/Holy Chakras changing not correct

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14559]
TrinityCore rev. 909a5ebf14de+
When changing to another chakra the old chakra[s] are still active(at least visible as active)...
##

**Comment by tkrokli** [comment]
At least post your core revision hash on each of your issues, please.

**Comment by Yalunima** [comment]
TrinityCore rev. 909a5ebf14de+
It´s meant Priest/Holy Level56:
  Chakra: Chastise
  Chakra: Sanctuary
  Chakra: Serenety....
If you switch between them the old icons remain....
How to reproduce ? - Activate any chakra and try to switch to any other Chakra.
