### ISSUE TITLE
3.3.5 Mage: Ice Barrier

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14555]
Core revision: https://github.com/TrinityCore/TrinityCore/commit/df4b175d689fa99aa3876a2c26bb24ba09970a98
DB version: TDB 335.58
Script version: Mage_ai
Ice Barrier (http://wotlk.openwow.com/spell=43039)
Shattered Barrier (http://wotlk.openwow.com/spell=54787)
ice barrier gets dispelled it activates the Shattered Barrier
Ice Barrier's removal should only freeze surrounding enemies when the shield is broken by damage, not when it is dispelled or spell stolen.

Please excuse my English.

**Comment by itslovelol** [comment]
It's because removeMode AURA_REMOVE_BY_ENEMY_SPELL includes dispels. You can change removeMode to a mask and add AURA_REMOVE_BY_DISPEL but you need to research whenever a aura should be broken by dispel OR / AND damage.
