### ISSUE TITLE
[6.x] weapon percent damage spell's Description problem

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#14554]
Build: https://github.com/TrinityCore/TrinityCore/commit/ca1f42d4091a91d3bd50ccc52012c836c43958f6
DB: TDB 6.1.2

weapon percent damage spell's Description is not Correct

Example:spellid =  1752 
Description =  "An instant strike that causes 147896 Physical damage."
it Should show 
"An instant strike that causes 1478 (weapon damage * 1.6  not  weapon damage * 160) Physical damage."

Example:spellid =3044
Description =  "An instant shot that causes 0 Arcane damage."
it Should show 
"An instant strike that causes 1013 (ranged weapon damage * 1.25 )Physical damage."

**Comment by et65** [comment]
Confirmed. Any idea when spell damage shown in the tooltp is sent to the client ?

**Comment by martial69320** [comment]
I think it's SpellEffect.dbc. But not sure
