### ISSUE TITLE
[6.x] Auction House - Searching for categories doesn´t work.

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14556]
TrinityCore rev. 909a5ebf14de+
When searching for all available items of a category you get nothing or not what you searched for...

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Yalunima** [comment]
thanks...

**Comment by DDuarte** [comment]
Did this get fixed?

**Comment by Shauren** [comment]
Probably yes - 4f98f2dac065c204f1abea45c12dae81aade58c5

**Comment by DDuarte** [comment]
Goood
