### ISSUE TITLE
[6.x] Auction House in Stormwind NPC does not respond

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14557]
TrinityCore rev. 909a5ebf14de+
In Stormwind Auction House the NPC in the middle doesn´t respond...

**Comment by msoky** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Yalunima** [comment]
TrinityCore rev. 909a5ebf14de+

**Comment by Yalunima** [comment]
thanks
