### ISSUE TITLE
Unit: UNIT_FLAG_PET_IN_COMBAT

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14566]
Once with UNIT_FLAG_PET_IN_COMBAT the npc will not be able to execute any SAI, also it will not be removed after the combat.
Example: https://github.com/TrinityCore/TrinityCore/issues/2129#issuecomment-93989349

TrinityCore rev. cc4f86cc2bf4

**Comment by MrSmite** [comment]
Is this really a *sub-petminion* issue or an SAI issue? Don't forget the core doesn't differentiate player pets from NPC pets so changing flags can lead to broken player pets.

**Comment by Killyana** [comment]
It's not an SAI issue only as the flag is not removed after the combat, but the UNIT_FLAG_IN_COMBAT  is removed correctly (tested with an without samartAI)
Also seems like class pets like "Imp"  don't get this unit_flag so it affects only "gardians"

**Comment by DDuarte** [comment]
Long shot here: Method [Unit::ClearInCombat()](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Unit/Unit.cpp#L9858) removes `UNIT_FLAG_PET_IN_COMBAT` however there's an early return if the unit is a creature and is not a pet (IsPet() returns false) and is not charmed.

**Comment by MrSmite** [comment]
Interesting, I thought all summons / guardians were considered a pet with the distinction of wether they're controllable (hunters / warlocks) or not (mages).
