### ISSUE TITLE
[3.3.5] Crash

### ISSUE THREAD

**Issue by Frytiks** [TrinityCore/TrinityCore#14565]
Hi guys, sometimes i'm getting that crash 1-2 hours 1 crash, ITS SUCH A RARE CRASH

Core rev: https://github.com/TrinityCore/TrinityCore/commit/1019649f93ae8f45f0d15a9eeeb803901c3c15cf with custom scripts

DB: TDB 11.58

http://pastebin.com/k6FQwyh8

**Comment by w1sht0l1v3** [comment]
Can confirm this also.More likely related to #14533 .

**Comment by timh52280** [comment]
Your bt seems to be optimized hiding some important info

**Comment by w1sht0l1v3** [comment]
Did you find a reason for the crash?

**Comment by Frytiks** [comment]
No, but i just think it's caused by quest item without target

**Comment by DDuarte** [comment]
If it wasn't fixed it shouldn't have been closed.

The crash seems to be related to a certain ItemTemplate of an item that casts a spell, there are no IDs in the crash log tho. Can you find which item or spell it is? (a.k.a how to reproduce this issue).

**Comment by Frytiks** [comment]
Without id can't. I'm working on LFG issue, no time for this crash. I have now uptime 3 days

**Comment by MrSmite** [comment]
> Can you find which item or spell it is? (a.k.a how to reproduce this issue).

What about running the core in VS and setting it to break on unhandled exceptions? This definitely has performance issues but without IDs it's probably the only way.

**Comment by Aokromes** [comment]
You don't need to post the whole startup log, only crashlog.
Anyway, this crash is still valid?

**Comment by Frytiks** [comment]
No it's not
