### ISSUE TITLE
[3.3.5][6.x] GameObjects with Loot should also be able to contain gold

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14564]
rev.: 2dda2483a3fcf48b672e8838bc3602c5296b8500

Lootable GameObjects aka. Chests should be able to grant gold loot. Should be probably handled like in creature_template with mingold and maxgold columns.

retail Screenshot:
![wowscrnshot_041115_225352](https://cloud.githubusercontent.com/assets/1472908/7204948/3e963234-e526-11e4-9985-0aafec686cb8.jpg)
##

**Comment by MrSmite** [comment]
This only applies to boss chests though, not standard world / dungeon chests.

You could probably put this in `gameobject_template` (`item_template` has `minMoneyLoot` and `maxMoneyLoot` as in [A Bulging Coin Purse](http://www.wowhead.com/item=10456/a-bulging-coin-purse)) but it might be better to put it in `gameobject_loot_template` as part of the loot.

**Comment by dr-j** [comment]
can confirm this with chests in Ulduar too for definite on retail Freyas, Kologarns, Hodirs, thorims chests all contain 10g (this may have been reduced since wotlk as remember seeing these bosses has dropping more gold when had looked up previously,

**Comment by Kittnz** [comment]
If i recall it was 100 gold.

**Comment by Saamsaam** [comment]
Gold per players have been reduced.(There's a blue post on wow forum that explain well the new system)  It is the same about droping a trashloot in dungeon (uncommon quality, rare or epic), it depend of the number of player in the dungeon/raid and I can't remember if it also depend of the player's level

**Comment by NorthStrider** [comment]
fact is, that the system is currently completely mssing for gameobjects. But i dont think adding this would be hard, since the loot system is similar to the creatures one

**Comment by Shauren** [comment]
Indeed it is only a matter of adding data to template or whatever and simply calling Loot::generateMoneyLoot

**Comment by MrSmite** [comment]
[This blog entry](http://eu.battle.net/wow/en/blog/10040336/) is from Ghostcrawler explaining the loot system from MoP which I would imagine is similar in 6.x with a few refinements [mentioned here](http://us.battle.net/wow/en/forum/topic/15355105387?page=127#2531)

As far as the original issue it also applies to 335, at least for raiding. When you kill a raid boss with a golden chest behind them there should be gold inside.

**Comment by Aokromes** [comment]
Implemented months ago.
