### ISSUE TITLE
3.3.5  The Amphitheater of Anguish？

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14561]
Core revision: df4b175
DB version: TDB 335.58
Gurgthock http://www.wowhead.com/npc=30007
The Amphitheater of Anguish quest It is shared
But TDB58 This is not the case

UPDATE `quest_template` SET `flags`=138 WHERE `entry` in (12932 12933 12934 12935 12936 12948）；

**Comment by Killyana** [comment]
According to wowhead these quests are not sharable.

**Comment by Aokromes** [comment]
Quick Facts
Level: 77
Requires level 75
Loremaster: Zul'Drak
Type: Group
Side: Both
Start: Gurgthock
End: Wodin the Troll-Servant
Not sharable
Difficulty: 75  80  91
Added in patch 3.3.0
Series
1.	
The Champion's Call!
2.	
The Amphitheater of Anguish: Yggdras!
3.	
The Amphitheater of Anguish: Magnataur!
4.	
The Amphitheater of Anguish: From Beyond!
5.	
The Amphitheater of Anguish: Tuskarrmageddon!
6.	
The Amphitheater of Anguish: Korrak the Bloodrager!
7.	
The Champion of Anguish

**Comment by dr-j** [comment]
This is a convey quest where when a player in party takes quest the quest should also be offered to other elegible players in party, have heard recently some people say there is bug with other quests atm where the quest is not offered to other players in group but have not tested myself

**Comment by ceresia** [comment]
The quest is offered, but when the party members accept the quest it does not officially accept or go into their quest log.

**Comment by dr-j** [comment]
thats what I meant as said I cant confirm this but have heard reports about this.
