### ISSUE TITLE
[6.x] GameObjects Despawn and Loot

### ISSUE THREAD

**Issue by DarkBrain2580** [TrinityCore/TrinityCore#14579]
rev. c3c8b7c2a638b9f9c0a79dac7c3b0025e4bed84c

I have test the Night Elves and have see GameObjects Problems by the Quest:
http://www.wowhead.com/quest=28715/demonic-thieves

The GameObject: http://www.wowhead.com/object=195074/melithars-stolen-bags

I run to the bag and then when I am in front of it, they just disappear.
They can then also not looting because they're gone yeah.
I've seen on several quest.
Is there already a solution?

**Comment by DarkBrain2580** [comment]
Can now close it is fixed now by this rev: db0b6caf141d495e0501a5bf9b47ce1f8462f7f5

**Comment by Aokromes** [comment]
@DarkBrain2580  you can close yourself your own tickets.
