### ISSUE TITLE
Hunter and Rogue and Druids and other stuff

### ISSUE THREAD

**Issue by epicwowserver** [TrinityCore/TrinityCore#14574]
Hunters cant use abilities that require ranged, pets die randomly without warning, pet action bar missing. 

Rogues do not apply combo points

Druids cant travel form.

All Trainer types (Class and Prof) dont work no interaction, 
Flight paths cant talk to, No interaction, InnKeeper no interaction

**Comment by msoky** [comment]
read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md before you post any new bug report.
