### ISSUE TITLE
[6.X] Ressurection problem

### ISSUE THREAD

**Issue by msoky** [TrinityCore/TrinityCore#14573]
When I was die as blood elf, I was click "release spirit" and then clent throw me to Barens from Sunstrider isle (blood elf)...
same as for Orc race...

client wrote this log: "Table graveyard_zone incomplete: Zone 6451 Team 67 does not have a linked graveyard"
maybe each graveyard is not linked to start zones?

SMSG_SPIRIT_HEALER_CONFIRM is disabled (i want ress from spirit healer) so, Spirit healer cant ressurect me

revision:https://github.com/TrinityCore/TrinityCore/commit/94215132c1980a30ee5de363423c8f68eaa2a0a8

**Comment by Aokromes** [comment]
#14089
