### ISSUE TITLE
World of Warcraft Patched.app doesn't work

### ISSUE THREAD

**Issue by VirusEntertainment** [TrinityCore/TrinityCore#14577]
![schermata 2015-04-19 alle 14 24 16](https://cloud.githubusercontent.com/assets/10599040/7219428/e8231950-e69f-11e4-89a6-dc02cc3d1ed5.png)

this is the error i get. 
I patched "World of Warcraft" file inside "world of warcraft.app -> show package/Contents/MacOS/"

**Comment by Aokromes** [comment]
#13903
