### ISSUE TITLE
[6.x] Whispering

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14572]
rev. d74e0d823d96df02822005e7165139b2bf1709de
whispering is only possible with .gm chat on and only for the character who has gm chat on

**Comment by Vincent-Michael** [comment]
.whisper on?

**Comment by YaGa** [comment]
same issue when whispering from and to an player account
no error appears, just not shown

**Comment by Vincent-Michael** [comment]
and your "GM.WhisperingTo" setting?

**Comment by Vincent-Michael** [comment]
![image](http://i.imgur.com/jyOtYcM.jpg)

**Comment by MitchesD** [comment]
@YaGa do you mean whispering in general or only whispering with GM?

**Comment by YaGa** [comment]
whispering in general, hm that's confusing..

**Comment by YaGa** [comment]
Oh no..I think its related to a custom patch.. shame on me if it is..

**Comment by YaGa** [comment]
my fault, I feel so ashamed, sorry for wasting your time
