### ISSUE TITLE
[Config] AHbot AuctionHouseBot.BuyPrice.Seller settings

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#14576]
The default config settings for AuctionHouseBot.BuyPrice.Seller is 1 and this means using SellPrice (the lower price).

In this way a player can earn easily 1000 gold per day just to go to AH buy items and sell it to any vendors. That's like cheating.

Strongly recommend to set this option to 0 (use BuyPrice, the higher one) by default.
##

**Comment by msoky** [comment]
read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md before you post any bug report

**Comment by Magnifikator** [comment]
Forget it and close this recommendation if you are not interested.

**Comment by MitchesD** [comment]
your ticket is not valid, we dont know your branch, your core revision, database, just nothing, ... thats the reason why you should read the basic rules of contributing

**Comment by jackpoz** [comment]
could you include a clear example of an item sold by the AHBot and how a player earns money from it ?

**Comment by Magnifikator** [comment]
I have tested after player complains 4-5 weapons, here an example:
Blinkstrike, ID 31332
Vendor BuyPrice 53G 35S 86C  / Vendor SellPrice 10G 67S 17C
AH Instant Buy 11 3 28  AH Bid 3 40 18

Because on small servers nobody is bidding, players can get it for 3 40 18 and can sell it for 10 67 17 at a vendor. 

AuctionHouseBot.BuyPrice.Seller on 1 means the AH is offering the instant buy price at the level of SellPrice of a vendor (the sellprice is the lower price, it's the money you get from vendor if you sell the item)  and additionally a much lower bid price.

With AuctionHouseBot.BuyPrice.Seller on 0  the AH is offering the instant buy price at the level of BuyPrice (the higher price, it's the amount you have to pay to buy an item) and additionally a cheaper bid price. But in this case the cheaper bid price is still higher than the price a vendor would pay.

**Comment by Magnifikator** [comment]
@MitchesD
If you read the recommendation well you will see that it is a config option. And this is seldom depending neither to branch, core revision nor database.

**Comment by MrSmite** [comment]
This technically isn't a bug because the bot is behaving as the config is intending. You just need to remember to edit your config after you update your fore.

Besides, if it defaults to __0__ as you suggest, what's preventing someone else from creating a bug report saying it should be __1__?

**Comment by Magnifikator** [comment]
As for every recommendation people have to decide if it make sense to follow the recommendation.

If the idea of the AH should be that player can earn very fast nearly unlimited money without working for, the right option is 1.
If the idea of the AH is to work more like an AH in reality than the option must be 0.

The option itself is doing what it promises. The question is what was intended to work as a default.

**Comment by Younguns** [comment]
A small server of 3 accounts...nobody cheats like that. They play to go questing, then go back to drop things into the AH. Nobody is running around and trying to make money through the AH. Now for some reason my AHbot buyer isn't working according to the conf file. Used to I could put things into the AH and the buyer would have them bidded on by the time I placed the next item into the AH. I had the chance ratio set to 500, but now he's not even bidding on items. So did someone change some thing and not mention it in the repository notes?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/812c2af4dae555b742ed318f0a93458115618356
