### ISSUE TITLE
[6.x] Barber Shop Chair - You can't "buy" your new look

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14580]
rev. db0b6caf141d495e0501a5bf9b47ce1f8462f7f5

**Comment by Pirricli** [comment]
Confirmed in some characters (I don't know the reason... race, gender, class...)
3.3.5 branch.

1019649f93ae8f45f0d15a9eeeb803901c3c15cf

**Comment by MitchesD** [comment]
broken in https://github.com/TrinityCore/TrinityCore/commit/d1902b40957c4ce6eb0f20a48d6bb86822d96bd0

**Comment by Pirricli** [comment]
The issue is in 3.3.5 branch too. Could the fix be ported to it?
Thanks.

**Comment by MitchesD** [comment]
its different, cannot reproduce the same bug, which was on 6x, on 335 branch

**Comment by Shauren** [comment]
Oh but you can port part of it
this one specifically https://github.com/TrinityCore/TrinityCore/commit/4208c0d8396e10dc806939e1d17885d16ff7b84e#diff-0b37867a050d2c3229d02ad686c95014R1414
validating appearance using CURRENT value of skin color instead 0 (if not changing)
