### ISSUE TITLE
[3.3.5] High Justice Grimstone attack players and untargettable

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14598]
High Justice Grimstone
http://www.wowhead.com/npc=10096/high-justice-grimstone

After entering ring of law, this npc attacked the party and it was untargettable. after killing the party, it started the ring of law.

Tested on cb3fcea 2015-02-05

**Comment by Killyana** [comment]
His react must be passive. 
https://github.com/TrinityCore/TrinityCore/blob/41e2b0046dc73ab2adf9c15442d70a7b769013f9/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp#L101

**Comment by dr-j** [comment]
It might also be worth noting there was some bad factions set for some mobs from cata to 3.3.5 a while ago that caused similar problems seems this mob also had faction changed from 32 to 54

**Comment by Killyana** [comment]
Faction on sniffs (3.3.0a 11159) is also 54.

**Comment by ikir83** [comment]
Tried with latest update, same issue

**Comment by tkrokli** [comment]
> Tried with latest update, same issue

... and latest update being https://github.com/TrinityCore/TrinityCore/commit/5ef9f14 ? Remember to add core rev. hash when posting.

**Comment by ikir83** [comment]
You're right

rev 2695a5fe3562 2015-04-26

**Comment by tkrokli** [comment]
You misread your core rev. hash 2b95a5fe3562 . The 2nd character in your hash is b, not 6.
`2b95a5fe3562264f52f1ca9296faf411a90d5d8d` (**DB/Quest: What Do You Feed a Yeti, Anyway?**)

**Comment by Killyana** [comment]
This will fix the issue
``` sql
UPDATE `creature_template` SET `unit_flags`=832 WHERE `entry`=10096;
```
Replace this line https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp#L166   by: 
``` cpp
me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);

**Comment by tkrokli** [comment]
OK, I see. A PR will be needed since it's a C++ update.

**Comment by tkrokli** [comment]
Interesting. @Killyana , are you just waiting for the C++ line to be included in the core before you commit the script in #8158 and close that issue? :+1:

**Comment by Killyana** [comment]
I cannot find relevant data on sniffs, so I update the unit flags as the one on  6.x, and changed UNIT_FLAG_NON_ATTACKABLE to UNIT_FLAG_PACIFIED on the script, it works fine, but I don't know if it will be accepted.

**Comment by tkrokli** [comment]
Well, I have hardly seen a smoother way of fixing an issue than the way you suggested.
Your solution is even less questionable than the Kodo Roundup quest solution I co-wrote.
