### ISSUE TITLE
zlib error code -2

### ISSUE THREAD

**Issue by viniroveran** [TrinityCore/TrinityCore#14591]
Version: 3761d24
error: Can't compress update packet (zlib: deflateInit) Error code: -2 (stream error)

Server compiled following wiki instructions, all requirements installed.

Using SSL version: OpenSSL 1.0.2a 19 Mar 2015 (library: OpenSSL 1.0.2a 19 Mar 2015)
Using Boost version: 1.57.0

Note: error appeared after latest updates (1 week~)

**Comment by DDuarte** [comment]
OS? 32 or 64 bits?

How to reproduce the issue?

**Comment by viniroveran** [comment]
Win, 64 bits.

Reproduce it by login with a character

**Comment by DDuarte** [comment]
Same stuff running here, issue doesn't happen.

**Comment by viniroveran** [comment]
I'll reinstall windows and see if it still happening, thanks

**Comment by MitchesD** [comment]
cannot confirm, just tried on 3761d241196827c5d12f2af0ce1c124d9172fc82 x64 win
