### ISSUE TITLE
zlib error code -2

### ISSUE THREAD

**Issue by viniroveran** [TrinityCore/TrinityCore#14590]
Version: https://github.com/TrinityCore/TrinityCore/commit/3761d241196827c5d12f2af0ce1c124d9172fc82
error: Can't compress update packet (zlib: deflateInit) Error code: -2 (stream error)

Server compiled following wiki instructions, all requirements installed.

Using SSL version: OpenSSL 1.0.2a 19 Mar 2015 (library: OpenSSL 1.0.2a 19 Mar 2015)
Using Boost version: 1.57.0

Note: error appeared after latest updates (1 week~)

**Comment by Aokromes** [comment]
There is no such commit on clean TC.
https://github.com/TrinityCore/TrinityCore/commit/84ff1fcb65c8

**Comment by viniroveran** [comment]
re-compiled. now completly clean TC.

latest commit:

https://github.com/TrinityCore/TrinityCore/commit/3761d241196827c5d12f2af0ce1c124d9172fc82
