### ISSUE TITLE
Some Draenor lvl and faction sql

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#14592]
-Ashran: 297 out of 574 npc faction corrections / 574 out of 574 mob&npc level corrections

-Frostfire Ridge: 
720 out of 1545 npc faction corrections 
1545 out of 1545 mob&npc level corrections

-Gorgrond: 
552 out of 689 npc faction corrections 
689 out of 689 mob&npc level corrections

-Nagrand: 
671 out of 857 npc faction corrections 
857 out of 857 mob&npc level corrections

-Shadowmoon Valley: 
818 out of 1748 npc faction corrections 
1546 out of 1748 mob&npc level corrections

-Spires of Arak: 
590 out of 718 npc faction corrections 
718 out of 718 mob&npc level corrections

-Talador: 
724 out of 956 npc faction corrections 
956 out of 956 mob&npc level corrections

-Tanaan Jungle: 115 out of 129 npc faction corrections
129 out of 129 mob&npc level corrections

-Arakkoa Outcasts - 90 out of 90 npc faction corrections
-Council of Exarchs - 1 out of 1 npc faction correction
-Frostwolf Orcs - 262 out of 262 npc faction corrections
-Laughing Skull Orcs - 15 out of 15 npc faction corrections
-Sha'tari Defense - 2 out of 2 npc faction corrections
-Steamwheedle Preservation Society - 44 out of 44 npc faction corrections

SQL File: https://www.dropbox.com/s/98eor4qake5clm4/draenor.sql?dl=0

**Comment by zuzanitha** [comment]
@tctwod  please resend link

**Comment by tctwod** [comment]
@zuzanitha for?
