### ISSUE TITLE
ScriptName exists in database, but no core script found!

### ISSUE THREAD

**Issue by oneluiz** [TrinityCore/TrinityCore#14600]
rev: 59e9bcf0bf44d89397f5a182e2ef21f7e3a3635d
TDB: 335.58

ScriptName 'npc_bloodmaul_brute' exists in database, but no core script found!
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!

**Comment by Nyeriah** [comment]
Thank you for your report but it consists of a duplicate of this issue https://github.com/TrinityCore/TrinityCore/issues/13707
