### ISSUE TITLE
[3.3.5] - Boss Sindragora bug Freez

### ISSUE THREAD

**Issue by oelsaid** [TrinityCore/TrinityCore#14602]
TrinityCore rev. 3761d2411968+ 2015-02-20 22:44:04 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.57 + Updates
Linux ubuntu

Bug: the ice of sindragora not this giving to break!
http://prntscr.com/6xqc3d
Bug: o gelo da sindragora não esta dando para quebrar!

**Comment by Rushor** [comment]
what? google translater is a bad idea ^^

https://github.com/TrinityCore/TrinityCore/issues/6541

**Comment by Nyeriah** [comment]
Yes, it's a duplicate of that bug

**Comment by oelsaid** [comment]
sorry, google translate. bug confirmed ?

**Comment by Nyeriah** [comment]
Yes, there's already a report for this issue.
Sim, já existe um ticket sobre este problema.

**Comment by oelsaid** [comment]
Obrigado caso eu queira retirar a skill do boss é possivel pois preciso de urgencia

**Comment by Nyeriah** [comment]
Yes, but if you need help with it you'll need to use our forums.
Sim, mas se precisas de ajuda com isso terás que usar o forum.

http://www.trinitycore.org/f/
