### ISSUE TITLE
(WEB) Text overflow in spells section - Czech

### ISSUE THREAD

**Issue by Rohlik** [TrinityCore/TrinityCore#14601]
Hello there!
I found this little bug in my Chrome browser. Look at word "Mana". "a" is under button when.
I use 1366x768 resolution on my monitor and "Čeština" language.
![spells](https://cloud.githubusercontent.com/assets/2051154/7319554/bbdac6e0-ea96-11e4-82ac-0884d189bfd4.PNG)

**Comment by Rohlik** [comment]
Wrong repo, sry :)

**Comment by Carbenium** [comment]
Are you sure this is the right bugtracker?

**Comment by MitchesD** [comment]
no problem

btw:
Ty popisy nedávají moc smysl mimochodem :D
