### ISSUE TITLE
Different Versions from GameObject.cpp

### ISSUE THREAD

**Issue by LoomaR1987** [TrinityCore/TrinityCore#14618]
My System Info :+1: 

Unix Debiuan Wheezy 7.x 64 Bit
Intel Xeon 3,6GHZ
Ram 32 GB
5 TB HDD

Core ... https://github.com/TrinityCore/TrinityCore/commit/491dd1852ae95bc2070a306365bb20e076946aa6

>
/home/trinity/src/TrinityCore/src/server/game/Entities/GameObject/GameObject.cpp: In member function ‘bool GameObject::Create(uint32, uint32, Map*, uint32, float, float, float, float, float, float, float, float, uint32, GOState, uint32)’:
/home/trinity/src/TrinityCore/src/server/game/Entities/GameObject/GameObject.cpp:193:25: error: ‘GAMEOBJECT_TYPE_MAP_OBJ_TRANSPORT’ was not declared in this scope

So i checked the file and check this line ...

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L193

As next step i check my old core from January ... 

```
    GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(name_id);
    if (!goinfo)
    {
        TC_LOG_ERROR("sql.sql", "Gameobject (GUID: %u Entry: %u) not created: non-existing entry in `gameobject_template`. Map: %u (X: %f Y: %f Z: %f)", guidlow, name_id, map->GetId(), x, y, z);
        return false;
    }

    if (goinfo->type == GAMEOBJECT_TYPE_TRANSPORT)
        m_updateFlag = (m_updateFlag | UPDATEFLAG_TRANSPORT) & ~UPDATEFLAG_POSITION;

    Object::_Create(guidlow, goinfo->entry, HIGHGUID_GAMEOBJECT);

    m_goInfo = goinfo;
```
I do not what is wrong :(

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8b07f1cd4d1714379f8beeea3d13ea0af118de23#commitcomment-10953948
