### ISSUE TITLE
6.x error compile

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14612]
rev 6da7a9cf00c841ff80dae4643c32824c3cb6709f
get error when compiling in this part

Linking CXX static library libg3dlib.a
[ 11%] Built target g3dlib
[ 11%] Built target generate_gamePCH.cpp
make: *** [all] Error 2

**Comment by DDuarte** [comment]
Post the whole log.

**Comment by deadmanevil** [comment]
there is complete on that stretch out that

**Comment by DDuarte** [comment]
What?

**Comment by deadmanevil** [comment]
This error is displayed when compiling

**Comment by DDuarte** [comment]
Yes, I'm asking you to post everything, not just "the error".

**Comment by deadmanevil** [comment]
[  8%] [  8%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Crypto.cpp.o
Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Cylinder.cpp.o
Linking CXX shared module libworldPCH.cpp_dephelp.so
[  8%] Built target worldPCH.cpp_dephelp
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/debugAssert.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/FileSystem.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/fileutils.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/format.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dfnmatch.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dmath.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/GThread.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Line.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/LineSegment.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Log.cpp.o
Linking CXX shared module libScriptPCH.cpp_dephelp.so
[  9%] Built target ScriptPCH.cpp_dephelp
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix3.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix4.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/MemoryManager.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/PhysicsFrame.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Plane.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/prompt.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Quat.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Random.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Ray.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/RegistryUtil.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Sphere.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/stringutils.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/System.cpp.o
[ 11%] Built target generate_bnetPCH.cpp
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextInput.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextOutput.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Triangle.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/uint128.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/UprightFrame.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector2.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector3.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
Linking CXX static library libg3dlib.a
[ 11%] Built target g3dlib
[ 11%] Built target generate_gamePCH.cpp
make: *** [all] Error 2

**Comment by DDuarte** [comment]
I fairly sure it doesn't start at 8%.

**Comment by deadmanevil** [comment]
before it starts but will not let me see above anything else to 8%

**Comment by deadmanevil** [comment]
Scanning dependencies of target gsoap
Scanning dependencies of target zmqpp
Scanning dependencies of target Detour
Scanning dependencies of target Recast
Scanning dependencies of target jemalloc
Scanning dependencies of target g3dlib
[  0%] [  0%] [  0%] [  0%] [  0%] Building CXX object dep/gsoap/CMakeFiles/gsoap.dir/soapServer.cpp.o
Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/Recast.cpp.o
Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/context.cpp.o
Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAlloc.cpp.o
Building CXX object dep/cppformat/CMakeFiles/format.dir/format.cc.o
[  0%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/arena.c.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/AABox.cpp.o
[  0%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
[  0%] Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/zmqpp.cpp.o
[  0%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMesh.cpp.o
[  0%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAlloc.cpp.o
[  0%] Built target revision.h
Scanning dependencies of target sharedPCH.cpp_dephelp
[  0%] Building CXX object src/server/shared/CMakeFiles/sharedPCH.cpp_dephelp.dir/PrecompiledHeaders/sharedPCH.cpp.o
[  0%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastArea.cpp.o
[  0%] Building CXX object dep/gsoap/CMakeFiles/gsoap.dir/soapC.cpp.o
[  0%] Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/frame.cpp.o
[  0%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastContour.cpp.o
[  0%] Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/socket.cpp.o
[  0%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshBuilder.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Any.cpp.o
[  1%] Building CXX object dep/gsoap/CMakeFiles/gsoap.dir/stdsoap2.cpp.o
[  1%] Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/message.cpp.o
[  1%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshQuery.cpp.o
[  1%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/atomic.c.o
[  2%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastFilter.cpp.o
[  2%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/base.c.o
[  2%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastLayers.cpp.o
[  2%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/bitmap.c.o
[  2%] Linking CXX shared module libsharedPCH.cpp_dephelp.so
Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/chunk.c.o
[  2%] Built target sharedPCH.cpp_dephelp
Scanning dependencies of target gamePCH.cpp_dephelp
[  2%] Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o
[  2%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/chunk_dss.c.o
[  2%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/chunk_mmap.c.o
[  2%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMesh.cpp.o
[  2%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/ckh.c.o
[  3%] Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/poller.cpp.o
[  3%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/ctl.c.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNode.cpp.o
Linking CXX static library libDetour.a
[  3%] Built target Detour
Scanning dependencies of target collisionPCH.cpp_dephelp
[  3%] Building CXX object src/server/collision/CMakeFiles/collisionPCH.cpp_dephelp.dir/PrecompiledHeaders/collisionPCH.cpp.o
Linking CXX static library libzmqpp.a
[  3%] Built target zmqpp
Scanning dependencies of target ipc
[  3%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/Commands.cpp.o
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMeshDetail.cpp.o
[  3%] Building CXX object dep/cppformat/CMakeFiles/format.dir/posix.cc.o
[  3%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/ZmqListener.cpp.o
Linking CXX shared module libcollisionPCH.cpp_dephelp.so
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/AnyTableReader.cpp.o
[  3%] Built target collisionPCH.cpp_dephelp
Scanning dependencies of target bnetPCH.cpp_dephelp
[  3%] Linking CXX static library libformat.a
Building CXX object src/server/bnetserver/CMakeFiles/bnetPCH.cpp_dephelp.dir/PrecompiledHeaders/bnetPCH.cpp.o
[  3%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/ZMQTask.cpp.o
[  3%] Built target format
Scanning dependencies of target ScriptPCH.cpp_dephelp
[  4%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/extent.c.o
[  4%] Building CXX object src/server/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/PrecompiledHeaders/ScriptPCH.cpp.o
[  4%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/hash.c.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRasterization.cpp.o
[  4%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/huge.c.o
[  4%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryFormat.cpp.o
[  4%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/ZmqMux.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRegion.cpp.o
[  4%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/jemalloc.c.o
[  4%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryInput.cpp.o
[  4%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/ZmqContext.cpp.o
[  4%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/mb.c.o
[  5%] Building CXX object src/server/ipc/CMakeFiles/ipc.dir/ZmqWorker.cpp.o
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/mutex.c.o
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/prof.c.o
Linking CXX static library libRecast.a
[  5%] Built target Recast
Scanning dependencies of target worldPCH.cpp_dephelp
[  5%] Building CXX object src/server/worldserver/CMakeFiles/worldPCH.cpp_dephelp.dir/PrecompiledHeaders/worldPCH.cpp.o
Linking CXX static library libipc.a
[  5%] Built target ipc
Scanning dependencies of target generate_sharedPCH.cpp
[  5%] Generating sharedPCH.h.gch
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/quarantine.c.o
Linking CXX static library libgsoap.a
[  5%] Built target gsoap
Scanning dependencies of target generate_collisionPCH.cpp
[  5%] Generating collisionPCH.h.gch
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/rtree.c.o
Linking CXX shared module libbnetPCH.cpp_dephelp.so
[  5%] Built target bnetPCH.cpp_dephelp
Scanning dependencies of target generate_bnetPCH.cpp
[  5%] Generating bnetPCH.h.gch
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/stats.c.o
Linking CXX shared module libgamePCH.cpp_dephelp.so
[  5%] Built target gamePCH.cpp_dephelp
Scanning dependencies of target generate_gamePCH.cpp
[  5%] Generating gamePCH.h.gch
[  5%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryOutput.cpp.o
[  5%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/tcache.c.o
[  6%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/tsd.c.o
[  6%] Building C object dep/jemalloc/CMakeFiles/jemalloc.dir/src/util.c.o
Linking C static library libjemalloc.a
[  6%] Built target jemalloc
[  6%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Box.cpp.o
[  6%] Built target generate_collisionPCH.cpp
[  6%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Capsule.cpp.o
[  6%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/CollisionDetection.cpp.o
[  7%] Built target generate_sharedPCH.cpp
Scanning dependencies of target shared
[  8%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o] Error 4
make[1]: *** [src/server/shared/CMakeFiles/shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/CoordinateFrame.cpp.o
[  8%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Crypto.cpp.o
Linking CXX shared module libworldPCH.cpp_dephelp.so
[  8%] Built target worldPCH.cpp_dephelp
[  8%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Cylinder.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/debugAssert.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/FileSystem.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/fileutils.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/format.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dfnmatch.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dmath.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/GThread.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Line.cpp.o
Linking CXX shared module libScriptPCH.cpp_dephelp.so
[  9%] Built target ScriptPCH.cpp_dephelp
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/LineSegment.cpp.o
[  9%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Log.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix3.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix4.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/MemoryManager.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/PhysicsFrame.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Plane.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/prompt.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Quat.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Random.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Ray.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/RegistryUtil.cpp.o
[ 10%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Sphere.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/stringutils.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/System.cpp.o
[ 11%] Built target generate_bnetPCH.cpp
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextInput.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextOutput.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Triangle.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/uint128.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/UprightFrame.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector2.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector3.cpp.o
[ 11%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
Linking CXX static library libg3dlib.a
[ 11%] Built target g3dlib
[ 11%] Built target generate_gamePCH.cpp
make: *** [all] Error 2

**Comment by Aokromes** [comment]
Not trinitycore issue.

[ 8%] Building CXX object src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,

Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.7/README.Bugs for instructions.
