### ISSUE TITLE
[3.3.5][6.x] Lordaeron Crier (COS)

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#14610]
In Culling of Stratholme there is a npc http://www.wowhead.com/npc=27913/lordaeron-crier on tc guid 132363.

During the waves of mobs between event starting and second boss during the 10 waves of mobs this npc is meant to annonce or yell where the next wave of mobs is there are 6 texts for this npc,, most are used more than once there are two texts for market row has the last one also plays sound which says 'You are too late champion of lordaeron the dead shall have their day'

The order in which these appear in sniff is also below.

I have tried to do this with sai but cant get it to announce anything other than the first wave as have tried using devouring ghoul to set data wont work and I cant find anyway of been able do this via db it needs to be scripted in cpp so when it spawns a wave of mobs it also triggers the appropriate text on this npc for that wave and never got it to work texts below are set to go out to whole map and that works fine.

``` sql
DELETE FROM `creature_text` WHERE `entry`=27913;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES 
(27913, 0, 0, 'Scourge forces have been spotted near the Festival Lane Gate!', 14, 0, 100, 0, 0, 0, 0, 3, 'Lordaeron Crier to Player'),
(27913, 1, 0, 'Scourge forces have been spotted near the Market Row Gate!', 14, 0, 100, 0, 0, 0, 0, 3, 'Lordaeron Crier to Player'),
(27913, 2, 0, 'Scourge forces have been spotted near the Elder\'s Square Gate!', 14, 0, 100, 0, 0, 0, 0, 3, 'Lordaeron Crier to Player'),
(27913, 3, 0, 'Scourge forces have been spotted near the Town Hall!', 14, 0, 100, 0, 0, 0, 0, 3, 'Lordaeron Crier to Player'),
(27913, 4, 0, 'Scourge forces have been spotted near the King\'s Square fountain!', 14, 0, 100, 0, 0, 0, 0, 3, 'Lordaeron Crier to Player'),
(27913, 5, 0, 'Scourge forces have been spotted near the Market Row Gate!', 14, 0, 100, 0, 0, 13471, 0, 3, 'Lordaeron Crier to Player');
```

-- Wave 1 Scourge forces have been spotted near the Festival Lane Gate! text 0
-- Wave 2 Scourge forces have been spotted near the Market Row Gate! text 1
-- Wave 3 Scourge forces have been spotted near the Festival Lane Gate! text 0
-- Wave 4 Scourge forces have been spotted near the Elder\'s Square Gate! text 2
-- Wave 5 Scourge forces have been spotted near the Town Hall! text 3
-- Wave 6 Scourge forces have been spotted near the Market Row Gate! text 1
-- Wave 7 Scourge forces have been spotted near the Elder\'s Square Gate! text 2
-- Wave 8 Scourge forces have been spotted near the Town Hall! text 3
-- Wave 9 Scourge forces have been spotted near the King\'s Square fountain! text 4
-- Wave 10 Scourge forces have been spotted near the Market Row Gate! text 5
##

**Comment by Nyeriah** [comment]
> 'You are too late champion of lordaeron the dead shall have their day'

Sniffer mess up. This is used by the Boss once it spawns.

I believe the positions need a struct of their own, so we can tear apart which text should be said at the given row. That can't be done efficiently as it is. I might have a look at this at some point, soon.

**Comment by Rushor** [comment]
moreover there should be a small white icon on the map which shows the position of the next wave, not shure if we get infos for this

![GitHub Logo](http://i.imgur.com/YTnyY7P.jpg?1)

**Comment by Aokromes** [comment]
It needs to use world states and randomization of spawn points.

**Comment by Wyrserth** [comment]
ca6228067507f19db230d415a1d088e5c0b5b808
