### ISSUE TITLE
[3.3.5][6.x][spell/script]: Pennant's mounts on Argent Tournament

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14616]
Every mount on the argent tournament have a racial Pennant depending on the player grade (Aspirant, Valiant or champion) All this is already scripted correctly, except how this spells are casted: Actually when you ride a mount the Pennant spell is not casted.
Pennants spells are triggered by http://www.wowhead.com/spell=63034 on cast, but it seems like the aura of this spell is applied by (http://www.wowhead.com/spell=63151 or http://www.wowhead.com/spell=63221) And this will not trigger the Pennant spell (this is the only explanation I could find)
How to reproduce:
Go to argent tournament where horde mount are:
- Take a horde spare ( .add 46070)
- Take the Orgrimmar wolf (.cast 62783) (spell_click handled by conditions, already scripted)
  At this point you can see that the Pennant  is not on the character but have Auras: 63151, 63034
- .cast 63034 (in your self or without target)  the pennant will be displayed and the player will get the aura ( 63432, 63431, 63433) depending in his grade.

ScriptName = "spell_gen_tournament_pennant" (maybe the problem is not there)
https://github.com/TrinityCore/TrinityCore/blob/675a2fcd3b4e46b79c57ead0fc455c4f6e4b03db/src/server/scripts/Spells/spell_generic.cpp#L2159
rev. 5b5c0938da0f
##

**Comment by sirikfoll** [comment]
The problem is that this line is returning false, dunno why :/
https://github.com/TrinityCore/TrinityCore/blob/675a2fcd3b4e46b79c57ead0fc455c4f6e4b03db/src/server/scripts/Spells/spell_generic.cpp#L2281

**Comment by Killyana** [comment]
Because the attribute is not implemented? https://github.com/TrinityCore/TrinityCore/pull/15275

**Comment by Nyeriah** [comment]
Most likely the spell script runs before the actual vehicle spawns.

**Comment by Aokromes** [comment]
Humm oculus drakes have the visual no? maybe checking how it works will help to fix this.

**Comment by Killyana** [comment]
Looks like the spell must be casted by the player on him self and not by the vehicle.
@ariel-  can you take a look? https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L2538

**Comment by ariel-** [comment]
Casted by the player. The problem is GetVehicleBase returning null, and this happens because of vehicles being handled asynchronously. The SPELL_AURA_CONTROL_VEHICLE is the first effect and gets applied before the dummy, but the VehicleJoinEvent wasn't executed, causing the script to be useless.
