### ISSUE TITLE
Quest 10950 Auchindoun and the Ring of Observance [Event] Children's Week

### ISSUE THREAD

**Issue by Servas** [TrinityCore/TrinityCore#14624]
The quest does not complete when you arrive to the zone with the children.

5ef9f1415ad96c4ea32593066d335a294e7b05c7

**Comment by tkrokli** [comment]
Please rename this part of the title: "Children Weeks" => Children's Week
(for search relevance later, even after closed issue).

**Comment by Servas** [comment]
The solution does not work in this quest.
When the orphan is near to the summoning stone in the center, then your 'orphan' will run to it and summon some random NPC.

**Comment by Servas** [comment]
This mission should trigger an event, for now is not activated.

When you can'll try rebooting the server.

**Comment by Servas** [comment]
Don´t work to this quest.

**Comment by Aokromes** [comment]
Generic bug: #5194
