### ISSUE TITLE
Quest 13930 Home Of The Bear-Men [Event] Children's Week

### ISSUE THREAD

**Issue by Servas** [TrinityCore/TrinityCore#14626]
The quest does not complete when you arrive to the zone with the children.

5ef9f1415ad96c4ea32593066d335a294e7b05c7

**Comment by tkrokli** [comment]
Please rename this part of the title: "Children Weeks" => Children's Week
(for search relevance later, even after closed issue).

**Comment by Servas** [comment]
I applied the proposed patch and it´s ok.
 thanks you

**Comment by DDuarte** [comment]
What proposed patch?

**Comment by Servas** [comment]
​In issue Quest 10945 AucHch'uu and the Mushroom People [Event] Children's
Week #14628, Dr-j proposed as temp fix until the trigger npc issue is
resolved just remember to run the delete clauses from this when fixed as it
changes nothing just adds sai and conditions.

2015-05-02 19:24 GMT+02:00 Duarte Duarte <notifications@github.com>:
