### ISSUE TITLE
Bug - eye of eternity

### ISSUE THREAD

**Issue by oelsaid** [TrinityCore/TrinityCore#14622]
TrinityCore rev. 3761d2411968+ 2015-02-20 22:44:04 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.57 + Updates
Linux ubuntu

Dragon without power
Screenshot: http://i.imgur.com/k39BYOM.jpg

**Comment by Aokromes** [comment]
update your core and database, that bug was fixed long time ago.

**Comment by oelsaid** [comment]
I update this review to another and gave GameObject error when compiling it, normal ??
