### ISSUE TITLE
Quest 10954 Jheel is at Aeris Landing! [Event] Children's Week

### ISSUE THREAD

**Issue by Servas** [TrinityCore/TrinityCore#14625]
The quest does not complete when you arrive to the zone with the children.

5ef9f1415ad96c4ea32593066d335a294e7b05c7

**Comment by tkrokli** [comment]
Please rename this part of the title: "Children Weeks" => Children's Week
(for search relevance later, even after closed issue).

**Comment by Servas** [comment]
This mission should trigger an event, for now is not activated.

When you can'll try rebooting the server.

**Comment by Servas** [comment]
Don´t work to this quest.

**Comment by Aokromes** [comment]
Generic bug: #5194
