### ISSUE TITLE
[3.3.5] Glyph of Sunder Armor

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14633]
Glyph of sunder armor should work with Devastate too, just for applying the debuff not the damage to second target. But in trinity core the debuff didn't stack on the second target. It is like the second target gets only one sunder armor effect even if the primary target has five of them.

http://www.wowwiki.com/Glyph_of_Sunder_Armor
##

**Comment by Killyana** [comment]
Confirm on rev. 5b5c0938da0f

**Comment by tkrokli** [comment]
@ikir83 : remember to post your core revision hash and TDB version for this issue to be valid.

**Comment by jackpoz** [comment]
I noticed that "Sunder Armor" with "Glyph of Sunder Armor" was applying 2 stacks at both the target and the other enemy close by with each cast.

**Comment by ikir83** [comment]
Sorry didn't have time in these months, i work soon much.
Never tried again on my server. @jackpoz can you confirm now the debuff now stacks on second target?

**Comment by tkrokli** [comment]
@ikir83 : Looks like he already did that Tuesday 7 days ago, unless I have misread his post. :-)
