### ISSUE TITLE
DB/Item: Reins of the Grand Black War Mammoth

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14634]
http://www.wowhead.com/item=43959
http://www.wowhead.com/item=44083
Must be added to the creature_loot_template with 5% chance on 10 and 25 difficulties and depending on the faction.
Npcs:
http://www.wowhead.com/npc=35013/koralon-the-flame-watcher
http://www.wowhead.com/npc=38433/toravon-the-ice-watcher
http://www.wowhead.com/npc=31125/archavon-the-stone-watcher
http://www.wowhead.com/npc=33993/emalon-the-storm-watcher

**Comment by Exodius** [comment]
From what I can see, mounts are already present in the loot tables.
```sql
SELECT * FROM creature_loot_template WHERE entry IN (35013, 38433, 31125, 33993);
```
Returns 2 different entries for each creature. First entry is a has `Reference` loot for every creature's Gear Drop and all have same second `Reference` entry (34203) that is designated for Mount Drops and a drop chance of 1%. That same `Reference` entry is linked to the "Difficulty" ID creatures of the respective bosses as well.

```sql
SELECT * FROM reference_loot_template WHERE entry=34203;
```
Returns only two rows with items being the mounts you linked.
From what I can remember from commits, conditions for mounts to drop for their respective faction are already in place however, I don't know how to check if conditions really DO exist within the DB.

So, from what I can see, you either need to bump drop chance from 1 to 5% for which I am submitting a suggested fix:

```sql
UPDATE `creature_loot_template` SET `Chance`=5 WHERE `Entry` IN (31125, 33993, 35013, 38433) AND `Item`=2;

**Comment by Killyana** [comment]
Thanks Conditions are also correct, for the droprate let's keep it like this on wowhead it's also 1%:
``` sql
SELECT * FROM `conditions` WHERE `SourceGroup` IN (34203);
