### ISSUE TITLE
[3.3.5] Silithus pvp not working.  Can't loot "Silithyst" 

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14637]
Seems Silithus pvp objects are bugged, i tried several times to take/loot  Silithyst, which you should bring to alliance/horde base but seems not to work. Can anyone confirm?

Tested on 2b95a5f 2015-04-26

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14181

**Comment by Killyana** [comment]
The aura must be removed on quest rewarded if I'm not wrong.
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (29518) AND `spell_effect` = 29519 ;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(29518, 29519 , 0, 'Silithyst Mound and Silithyst Geyser');

**Comment by Killyana** [comment]
Silithyst Mound must despawn if the player click it, but seems like there's a problem here:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/OutdoorPvP/OutdoorPvPSI.cpp#L239

**Comment by dr-j** [comment]
well I already arrived at the spell_linked_spell last week but did not know if this issue was with all tc did mention on tc dev channel

ps these do despawn for me when used with gm mode off but did not make any changes to gameobject

**Comment by Killyana** [comment]
I'm not talking about Silithyst Geyser but Silithyst Mound (they spawn if you remove the aura 29519), this gob also must despawn on click like Silithyst Geyser.

**Comment by tkrokli** [comment]
Is this issue also valid for the 3.3.5 source? It's been months since I last tested collecting Silithyst to see how long it would take to control the zone (amounts of spawn nodes, travel distance etc.) on 3.3.5.

**Comment by Killyana** [comment]
Fixed by @Whoami: http://pastebin.com/CgjRAcm5 no need to add the linked spell, just the faction of the gob must be updated.
``` sql
UPDATE `gameobject_template` SET `faction`=1673, `VerifiedBuild`=0 WHERE `entry` IN (181597);

**Comment by Kinzcool** [comment]
No need to change the VerifiedBuild here; faction field isn't part of SMSG_GAMEOBJECT_QUERY_RESPONSE.

**Comment by Killyana** [comment]
Hum ok.

**Comment by ikir83** [comment]
@Killyana 
yes mound despot but the player didn't get anything so can't score

**Comment by Killyana** [comment]
Works fine for me on rev. 5dba91fb0e38
