### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by megatronir** [TrinityCore/TrinityCore#14635]
Hi, i have a issue with login into TC clean 6x.

when i'll trying to connect it from client to server, it say like this pic:
http://8pic.ir/images/h7ig22t2ty3lpxtbfhk0.png

also sometimes when use username@email.com password, it for 3-4 sec hangup and then write : you have been disconnected from the server.

i have created account in console like: .account create admin@yahoo.com admin 
and then from " account " table copied ( id, email, sha_pass_hash ) into table battlenet_accounts, inserted, but still have same issue and cannot login into it. 

my launcher version is : 6.1.2 19802 and my gamebuild of server is same TC clean : 19793.

well in Linux Debian everythings will be fine and i can login, but in Windows server where i have installed the server cannot login, server is run bnetserver.exe and worldserver.exe without any problem.

thanks

**Comment by DDuarte** [comment]
Do not insert to the database directly. If you need to create a bnet account use `.bnetaccount create` command.

**Comment by megatronir** [comment]
i using with this command and it's create fine but still have same error " you have been disconnected from the server ".

**Comment by tkrokli** [comment]
You still need to document your core revision hash + TDB version in your original post for it to be valid.

**Comment by megatronir** [comment]
all are fine, and as i said, it's fine in Linux, or localhost of win, just from public server in a virtual machine have this issue.

**Comment by tkrokli** [comment]
Basically, your problem belongs in the TrinityCore Forum, not in the issue tracker. You have not presented enough documentation for this to be a real issue for everyone. Please read this info:
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by msoky** [comment]
1.write your REVISON !...
2.maybe SOAP system (register through web site) help you

**Comment by megatronir** [comment]
well issue solved, it's because of missmatch launcher from WIN connection patcher. thanks for following.

**Comment by msoky** [comment]
"my launcher version is : 6.1.2 19802 and my gamebuild of server is same TC clean : 19793."

**Comment by tkrokli** [comment]
> "my launcher version is : 6.1.2 19802 and my gamebuild of server is same TC clean : 19793."

Thanks for pointing out that obvious mistake by the OP. Server build version != Launcher build version
