### ISSUE TITLE
[6.x] Alliance - Brawlpub spawns

### ISSUE THREAD

**Issue by VirusEntertainment** [TrinityCore/TrinityCore#14642]
http://pastebin.com/GfNw3CXy

the area is located in storwind tram area, so no need areatriggers

**Comment by MitchesD** [comment]
it cant be pushed, did you check it for double spawns? also phaseId is not valid

**Comment by VirusEntertainment** [comment]
![wowscrnshot_050315_111850](https://cloud.githubusercontent.com/assets/10599040/7444499/38e15f96-f186-11e4-8ea1-2c754d042072.jpg)
 there are no double spawn, what should i do now?

**Comment by Kinzcool** [comment]
First of all,
```sql
SET @CGUID := (select max(guid) from creature);
SET @OGUID := (select max(guid) from gameobject);
````
this part is going to delete the last guid in the database; don't do that. Instead just set it manually to max guid + 1.

As of the fact of not being able to push it, you just have to remove the `PhaseGroup` field as it isn't a text field in the db and is of no matter in this case.

**Comment by VirusEntertainment** [comment]
oh shit! XD I forgot to edit that! 1 minute

**Comment by tkrokli** [comment]
Also: Use "INSERT INTO" instead of your 3 "REPLACE INTO" commands (not used by TC). :smirk_cat:

**Comment by Kinzcool** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9ec07e07d81a113e6cba775265325d9f6c45327b
