### ISSUE TITLE
Problem at compile branch 6xx

### ISSUE THREAD

**Issue by Lordset** [TrinityCore/TrinityCore#14645]
Hello guys,
I'm trying to compile the emu, I just pulled and I have this errors, I will thank you all for your awsome help.
Linking CXX executable bnetserver
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: /usr/local/lib64/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /usr/local/lib64/libdl.so.2 so try adding it to the linker command line
/usr/local/lib64/libdl.so.2: could not read symbols: OperaciÃ³n invÃ¡lida
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/bnetserver/bnetserver] Error 1
make[1]: *** [src/server/bnetserver/CMakeFiles/bnetserver.dir/all] Error 2

Im using Centos 6.6 (Final version)

**Comment by tkrokli** [comment]
1. This is not a forum. Post in the forum instead, http://www.trinitycore.org/f/ , for help with your setup.
2. When reporting an issue affecting everybody, post commit hash and a full log from a Gist or pastebin.
3. Retry all the steps needed to create your core. Follow the guide:
 - http://collab.kpsn.org/display/tc/Core+Installation#l-source-6x

Please close this "issue", unless you have some proof that this is an issue for everyone using your OS.

**Comment by DrakeNn** [comment]
xDDDDDDDDDDDDDDDDDDDDD
