### ISSUE TITLE
Two realm set for BG

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14647]
Welcome dear users

I needed help at
I searched some sites and forums but could not find, I saw that it create one with QueryHandler.cpp but how?

**Comment by tkrokli** [comment]
1. This is not a forum. Please use http://www.trinitycore.org/f/ for your questions.
2. You have not presented a problem affecting all users of this source.
3. You have neither documented that you are using TrinityCore source, neither branch nor core version.
 - Please close this "issue", it does not belong in the TrinityCore issue tracker.

**Comment by Runico** [comment]
https://github.com/TrinityCore/TrinityCore/wiki

**Comment by Spectrance** [comment]
thank!
