### ISSUE TITLE
[3.3.5]Compile error Ubuntu 15.04

### ISSUE THREAD

**Issue by CoolDesert** [TrinityCore/TrinityCore#14654]
[  2%] Built target jemalloc
[  6%] Built target g3dlib
[  6%] Built target Detour
[  7%] Built target Recast
[  8%] Built target format
[  8%] Built target gsoap
[  8%] Built target revision.h
[  8%] Built target sharedPCH.cpp_dephelp
[  9%] Built target generate_sharedPCH.cpp
[ 13%] Built target shared
[ 13%] Built target gamePCH.cpp_dephelp
[ 13%] Built target generate_gamePCH.cpp
[ 33%] Built target game
[ 33%] Built target collisionPCH.cpp_dephelp
[ 33%] Built target generate_collisionPCH.cpp
[ 34%] Built target collision
[ 34%] Built target authPCH.cpp_dephelp
[ 34%] Built target generate_authPCH.cpp
[ 35%] Built target authserver
[ 35%] Built target ScriptPCH.cpp_dephelp
[ 35%] Built target generate_ScriptPCH.cpp
[ 35%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/server/scripts/CMakeFiles/scripts.dir/build.make:54: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o] Error 4
CMakeFiles/Makefile2:1100: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aokromes** [comment]
Not trinitycore issue. use a diferent kernel.

**Comment by CoolDesert** [comment]
why ?  which kernel was supported ?

**Comment by Aokromes** [comment]
Non modified by data center kernels. Also you need a minimum of 2 GB of ram iirc to compile.
