### ISSUE TITLE
6x problem by giving group

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14650]
edbd44a67530f2938864fd054182553b3d5ab1ac
Error can not be given yet group is as if that option could not take active and does not comvertir band and if not when they may have functional

**Comment by DJScias** [comment]
Groups are currently not functioning on the 6.x.x branch as far as my knowledge goes.

**Comment by deadmanevil** [comment]
and here the developers will not be able to confirm when this option will be active

**Comment by MitchesD** [comment]
groups are not yet implemented, we know it

**Comment by deadmanevil** [comment]
They have some time in which to implement

**Comment by tkrokli** [comment]
It is difficult to make something work when it has not been made yet.

**Comment by DJScias** [comment]
I'd say it's probably a good thing to keep an eye on #14710 in regards to this issue. :)

**Comment by DDuarte** [comment]
Fixed in 0778c4fd563e6f112e8c1bd5fed5fbf683e9a499

**Comment by deadmanevil** [comment]
nay great thank you

**Comment by DDuarte** [comment]
Thank @et65, he did the work in a pull request.
