### ISSUE TITLE
DB/NPC: Fix InhabitType for Sapphire Hive Wasp/Sapphire Hive Drone

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14656]
``` sql
UPDATE `creature_template` SET `InhabitType`=7 WHERE `entry` IN (28086, 28085);
UPDATE `smart_scripts` SET `target_type`=21, `target_param1`=8 WHERE `entryorguid` IN (32639, 32638, 32641, 32642)AND `id`=2; -- fix text target for Traveler's Tundra Mammoth's npcs
```

**Comment by tkrokli** [comment]
So, `InhabitType`=7 is not broken anymore, as @shlomi1515 claimed in [[Core Issue] Creatures With InhabitType 7 Cant Stay in Air #6148](https://github.com/TrinityCore/TrinityCore/issues/6148) ? (just curious)

**Comment by Killyana** [comment]
For some npcs using scripted movements only.

**Comment by tkrokli** [comment]
OK, I see. That's why your suggested fix is limited to 2 creature IDs.
