### ISSUE TITLE
6.x Connection Problem - Linux

### ISSUE THREAD

**Issue by LebenHarvest** [TrinityCore/TrinityCore#14661]
Hey, I just wanted to report this connection issue I seem to have found with linux, centos 6 to be specific.

I have all the required dependencies versions or newer.

when I connect to the server it gets to retrieving character list and then disconnects my client.

![connection-problem](https://cloud.githubusercontent.com/assets/753802/7489495/26b4d638-f38c-11e4-8d4d-644a7c9ce503.jpg)

**Comment by tkrokli** [comment]
The last 2 lines in your image are the most interesting part, refers to line 457 in WorldSocket.cpp ;
Line 457 in WorldSocket.cpp in the 6.x code looks like this in the section 450 - 460:
```cpp
    // Check locked state for server
    AccountTypes allowedAccountType = sWorld->GetPlayerSecurityLimit();
    TC_LOG_DEBUG("network", "Allowed Level: %u Player Level %u", allowedAccountType, AccountTypes(security));
    if (allowedAccountType > SEC_PLAYER && AccountTypes(security) < allowedAccountType)
    {
        SendAuthResponseError(AUTH_UNAVAILABLE);
        TC_LOG_DEBUG("network", "WorldSocket::HandleAuthSession: User tries to login but his security level is not enough");
        sScriptMgr->OnFailedAccountLogin(id);
        DelayedCloseSocket();
        return;
    }
```
Even more interesting that the message that line is supposed to give you looks like this:
```cpp
"WorldSocket::HandleAuthSession: User tries to login but his security level is not enough"
```
To me, this looks like you have some account setup issues.

**Comment by Shauren** [comment]
TC_LOG_ERROR("network", "Can't compress packet opcode (zlib: deflate) Error code: %i (%s, msg: %s)", z_res, zError(z_res), _compressionStream->msg);

This is the line (zError is the null). What zlib version are you using?

**Comment by LebenHarvest** [comment]
Zlib 1.2.8

**Comment by LebenHarvest** [comment]
Fixed this issue by building and installing the latest zlib.

seems somehow cmake was using an older version even though I specified to use 1.2.8 it was using 1.2.3
