### ISSUE TITLE
[6.x] Faction Attack problem.

### ISSUE THREAD

**Issue by zedinke** [TrinityCore/TrinityCore#14662]
Hello!
Alliance and Horde faction can not attack each other.

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/wiki

**Comment by tkrokli** [comment]
I just checked your account page, you never provide much info in your posts. Well, this is not Skyfire and we are not looking into that issue until you tell us which core revision hash you use and say something about what you have tested already. If you fail to provide more info, this issue will be closed in a week.
