### ISSUE TITLE
3.3.5 boss_ignis

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14666]
from https://github.com/TrinityCore/TrinityCore/commit/1161295f4f933661ea9738e0c57049a1e38ec8f2
DB:TDB58
updata:https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/updates/world/2015_05_04_00_world.sql
scrtipname:Boss_flame_leviathan.cpp

//TOWER ap & health spells
SPELL_BUFF_TOWER_OF_STORMS     = 65076,
（http://wotlk.openwow.com/spell=65076)
SPELL_BUFF_TOWER_OF_FLAMES     = 65075,
（http://wotlk.openwow.com/spell=65075)
SPELL_BUFF_TOWER_OF_FR0ST      = 65077,
（http://wotlk.openwow.com/spell=65077)
SPELL_BUFF_TOWER_OF_LIFE       = 64482,
（http://wotlk.openwow.com/spell=64482)

Boss_flame_leviathan.cpp（http://www.wowhead.com/npc=33113） BUFF, will affect the boss_ignis.cpp

Ignis the Furnace Master There will be four towers of the property

Please excuse my English.

**Comment by w5860363** [comment]
@Aokromes Flame Leviathan Ignis the to directly beat Furnace Master with the effect of four, after the death of battle would not enter again

Please excuse my English.

**Comment by dr-j** [comment]
Think this is known bug if you do flame levithan hard mode the buffs from the towers end up on other near bosses too.

Same happens if you freya hard mode, hodir, etc end up with buffs from freya hard mode.

**Comment by w5860363** [comment]
hack 

            bool CheckAreaTarget(Unit* target)
            {
                if (target->GetEntry() == 33113)
                    return true;
                return false;
            }

**Comment by w5860363** [comment]
hack 
 if (target->GetEntry() == 33113)

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/3921
