### ISSUE TITLE
[3.3.5a] ICC Boss bug

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#14677]
Hi, there is a bug with certain boss in ICC: Sindragosa. My admin will tell me more bug boss but Sindragosa TOMB don't work
TrinityCore Revision is: 
TrinityCore rev. 335cceb26e80+ 2015-04-23 23:51:40 -0300 (3.3.5 branch) (Unix, Release)

**Comment by Aokromes** [comment]
duplicate.

**Comment by tkrokli** [comment]
Learn how to use search here on github/TC :
https://github.com/TrinityCore/TrinityCore/search?q=sindragosa+ice+tomb&state=open&type=Issues&utf8=✓
