### ISSUE TITLE
[3.3.5a] Massive HP loss when taking Grom'gol-Undercity zeppelin

### ISSUE THREAD

**Issue by shadedmagus** [TrinityCore/TrinityCore#14672]
Significant HP loss is being seen upon zoning into Tirisfal Glades when taking the zeppelin from Grom'gol to Undercity. Level 44 char with 3438 HP dropped to 802 HP after zoning in. Referencing issue #11076, since this will most likely kill low-level characters, but the HP loss happens every time. Occurred with multiple chars on 3.3.5 rev 8b50c142cbf7.
##

**Comment by jackpoz** [comment]
Please update to a more recent version and report back if it still happens, you are currently using a 3 months old version.

**Comment by Killyana** [comment]
Confirm on rev. 5dba91fb0e38
Combat logs: "PlayerX falls and loses 7360 points of life . "

**Comment by Aokromes** [comment]
Can you try after 8c61e51?

**Comment by Killyana** [comment]
Same issue on rev. f020f6f51974
"PlayerX falls and loses 11963 points of life ."

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8c61e51fe53f6429a7a8d532a5c675ff72f438ad is from today :) plz test with that up to 916ce6f :)

**Comment by shadedmagus** [comment]
Building now - saw this error pop up for Transport.cpp.o:

<code>/home/trinity-lk/TrinityCore/src/server/game/Entities/Transport/Transport.cpp:229:6: warning: unused parameter â€˜diffâ€™ [-Wunused-parameter]
 void Transport::DelayedUpdate(uint32 diff)</code>

Will let you know once it's done and I can log in.

**Comment by DDuarte** [comment]
For the nth time, warnings are not errors and that one in specific is really meaningless. It has nothing to do with your ability to login or not (login on 3.3.5 works since 7 years ago...).

**Comment by shadedmagus** [comment]
Maybe you didn't see that I'm still currently building, and can't log in until it's done...

**Comment by DDuarte** [comment]
Sorry about the passive aggressive comment, it's just that lately we had a lot of people thinking that warnings destroy the universe.

**Comment by shadedmagus** [comment]
No worries at all. :) I work in break-fix, and I have a few clients who get freaked out over the least little thing.

I'm at 76% building; as soon as it's done, I'll log in and see if this revision has fixed the issue.

**Comment by shadedmagus** [comment]
Nope, issue is still present on rev 0148832b322b.

Interesting note - just before the transition to the world travel screen, I actually saw the HP decrease, and the message "X falls and loses 3394 health."

**Comment by Killyana** [comment]
The issue is worst than before, players on rev. 5c94b52a4d24  are dropped from the transport in no where, and it causes an infinite fall, no possibility to die or do anything.

**Comment by ariel-** [comment]
@r00ty-tc : can https://github.com/r00ty-tc/TrinityCore/commit/36cd1570cd2d7a26ce68d8a27515ea7ef9de649b be pushed?

**Comment by Aokromes** [comment]
for me falls, but no infinite fall.

**Comment by Shauren** [comment]
looks like a bad hack to me
