### ISSUE TITLE
[6.x][Crash] SendObjectUpdates

### ISSUE THREAD

**Issue by doomkas** [TrinityCore/TrinityCore#14673]
rev 007ab5b
crashdump http://paste2.org/x2eLy58V

**Comment by doomkas** [comment]
The crash came after
https://github.com/TrinityCore/TrinityCore/commit/ca83e14f8b141fab0a13e08f48fca6c1ace0c4c7

**Comment by Zedron** [comment]
confirm @ 9f3cb91

**Comment by Shauren** [comment]
Stop this bullshit "confirm" without posting a crash log.
And post a proper debug log, not this partial RelWithDebInfo crap

**Comment by Zedron** [comment]
a simple "could you post a debug crashlog" would suffice

**Comment by Zedron** [comment]
https://gist.github.com/Zedron/a3bcb49f80ec2b80fe3c
