### ISSUE TITLE
[6.x][Crash] AddObjectToRemoveList

### ISSUE THREAD

**Issue by doomkas** [TrinityCore/TrinityCore#14687]
rev 007ab5b
crashdump http://paste2.org/hvxcdXFn

**Comment by doomkas** [comment]
The crash came after
https://github.com/TrinityCore/TrinityCore/commit/ca83e14f8b141fab0a13e08f48fca6c1ace0c4c7

**Comment by Manokha** [comment]
Hi @doomkas 
I took a rapid look at the commit and those line deletions look suspicious to me.
Do you manage to reproduce the issue with this diff ? (judging by your core dump, it looks like it's related to event unspawn ; which could probably be triggered somehow. It might require to have a connected character at the place of the event for it to core dump).
diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index c2f7718..7110307 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -95,12 +95,14 @@ Object::~Object()
         if (isType(TYPEMASK_ITEM))
             TC_LOG_FATAL("misc", "Item slot %u", ((Item*)this)->GetSlot());
         ASSERT(false);
+       RemoveFromWorld();
     }

     if (m_objectUpdated)
     {
         TC_LOG_FATAL("misc", "Object::~Object %s deleted but still in update list!!", GetGUID().ToString().c_str());
         ASSERT(false);
+       RemoveFromObjectUpdate();
     }

     delete[] m_uint32Values;
