### ISSUE TITLE
[3.3.5] Dire Maul West Prince Tortheldrin

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14683]
The final and option boss in Dire Maul West is not actionable, you can't speak to him  so he never attack you.

http://www.wowwiki.com/Prince_Tortheldrin

DB 335.58
rev 2b95a5fe3562 2015-04-26
##

**Comment by Rushor** [comment]
The only way of killing the prince is to destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, you may attack and end him. 

so we need the forcefield-destroy-action at

**Comment by dr-j** [comment]
forcefield does not even need destroying just needs to be activated by script

**Comment by ikir83** [comment]
OK so probably it is related to this issue

https://github.com/TrinityCore/TrinityCore/issues/14685

**Comment by offl** [comment]
#14685
