### ISSUE TITLE
[3.3.5] Dire Maul West pylons and Immol thar

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14685]
Dire Maul West pylons are not clickable. There are 5, players should click (or kill all the elementals i don't remember) to unlock Immol thar
Just the two pylons in the Immol that prison are clickable, but the first 3 are not. A GM can click it but not players so the magic cage never opens.

http://www.wowwiki.com/Immol%27thar

DB 335.58
rev 2b95a5fe3562 2015-04-26
##

**Comment by Aokromes** [comment]
Acording http://www.wowwiki.com/Prince_Tortheldrin 
"The only way of killing the prince is to destroy the guardians surrounding the pylons to lower the force field. When this is done, destroy Immol'thar. With the Prince's power greatly reduced, you may attack and end him."

Like you see no word of click pylons.

**Comment by dr-j** [comment]
Instance script needs changing and can confirm this as not working as the pylons need script to deactivate this has already previously been mentioned but has not been actioned yet,

Immo'thar should not be attackable until all pylons have been activated

Prince Tortheldrin has always been bugged and non attackable but should become attackable once immo'thar killed.

Basically the pylons need scripting

and I cannot reproduce any issue with doors as all work for me either open just by.clicking or require crescent key, or gordok courtyard key or gordok inner courtyard key.

2 of the pylons are probably wrong faction (the 2 by immol'thar) as unlike the first 3 pylons even though these have flags to say they are not selectable these 2 still show tooltip to when player when moused over and appear to be clickable, these 2 are different faction to the first 3 changing the faction to same faction as first 3 fixes this (ie tooltip no longer visible to player and not clickable.

**Comment by Rushor** [comment]
maybe this for the instancescript: 
https://gist.github.com/Rushor/832d5d63500f6ee5a4aa - instance
https://gist.github.com/Rushor/be08f588aa72a6d3c7d3 - header
https://gist.github.com/Rushor/4bf5b4297cb5d91b644a - general boss stuff
 - but by hell this needs a lot of improvements ^^

**Comment by ikir83** [comment]
Yes the pylons should deactivate when players kills the elementals, but the first 3 pylons seems to remain active. While the 2 in Immol that room can be clicked and deactivated. A GM player can click the other first 3 as well. but the prison is still there

**Comment by Keader** [comment]
@Rushor can you update this links?

**Comment by Rushor** [comment]
mostly only a convert from https://github.com/scriptdev2/scriptdev2/blob/master/scripts/kalimdor/dire_maul/instance_dire_maul.cpp

**Comment by bblewittAG** [comment]
This is still a problem in the latest Rev of TrinityCore
TrinityCore rev. f85266733214+ 2017-04-08 21:47:38 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
Does anyone know how to fix it so that it allows players to interact as a GM in GM mode it will let me interact and disable the nodes with no problems on all 5?

**Comment by Ripleybeast** [comment]
Has anyone tried working on this.   It's been bugging me for the longest time.   Even if it cant get fixed to work as intended, Im hoping someone as any info on just removing the forcefield, so immolthar is always open to attack.  I tried selecting GOB's around, but none target this forcefield, yet its a clickable item if you turn GM mode on.   Any clue how to at least remove this forcefield from my own server?  THANKS!

**Comment by Aokromes** [comment]
if a warlock or a hunter or a dk with controlable pet is on party can pull boss.

**Comment by illfated** [comment]
Seeing how old this issue is, has it ever been working at all on TC source?
Also, when looking at the only Dire Maul instance script file ( `instance_dire_maul.cpp` ), there is very little content at all in there:
https://github.com/TrinityCore/TrinityCore/blob/ada4e431ae77cf56e6f5e4441b494dd25d6b3fb9/src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp#L25-L76

Does this mean that all of the creatures in the instance are handled by SAI and DB conditions and that we should look into DB changes to solve this issue?

**Comment by illfated** [comment]
BTW, I would very much like to see a constructive discussion on this topic. If there is anything I can do to contribute, ping me.

**Comment by Wizards2k** [comment]
at moment pilon still not active and prison not work also with all guardian died, please fix

**Comment by peycho** [comment]
AFAIK the pylons don't need to be touch by players. They should some kind trigger a spell when all the guards around the pylon are killed [Mana Remnant](https://wotlk.evowow.com/?npc=11483)

At the moment, when you kill them, nothing happens. I try to click on the pylons in GM mod and the spell looks like triggered.

Core rev: 400e2913179e0ff47518558f89b687161031967a

**Comment by Aokromes** [comment]
> AFAIK the pylons don't need to be touch by players. They should some kind trigger a spell when all the guards around the pylon are killed [Mana Remnant](https://wotlk.evowow.com/?npc=11483)
> 
> At the moment, when you kill them, nothing happens. I try to click on the pylons in GM mod and the spell looks like triggered.
> 
> Core rev: [400e291](https://github.com/TrinityCore/TrinityCore/commit/400e2913179e0ff47518558f89b687161031967a)

https://github.com/TrinityCore/TrinityCore/issues/14685#issuecomment-101147944 i said that 5 years ago.

**Comment by LEO33SoFo** [comment]
I confirm this issue still happens on https://github.com/TrinityCore/TrinityCore/commit/9d959123e68020a83c780f53a967b3589cb70786.

The pylons are not deactivated upon killing their guardians and the force field surrounding **Immol'thar** is not dissipated. Had to use `.gm on` to dissipate the force field.

**Comment by illfated** [comment]
@offl : From what I can see in the Scripts folder (https://github.com/TrinityCore/TrinityCore/tree/3.3.5/src/server/scripts/Kalimdor/DireMaul), almost nothing in this instance seems to be handled in C++, so I am guessing that most of it is handled in the DB.

Would it be easy enough for you to look up and confirm this without spending much time on it, seeing that this should be mostly about a combination of GameObjects and NPCs?

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/pull/25332

**Comment by illfated** [comment]
Thank you, good point. That should have been obvious enough to me as well.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/26002c530f7183105bf3dcb33272bb0cf3322558
