### ISSUE TITLE
[6.x] Rogue Combo Points

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14680]
rev . 3c79914e7b01a44bd5b34f7728e5cb575fa48723
It does not give the rogue combo points and can not use the spell others

**Comment by Sar777** [comment]
need use POWER_COMBO_POINTS

**Comment by Rushor** [comment]
fixed with https://github.com/TrinityCore/TrinityCore/pull/15996 @Shauren ?
