### ISSUE TITLE
[6.x] Cannot compile under Mac OS X Yosemite

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#14689]
OS: Mac OS X Yosemite (fresh install)
Rev: https://github.com/TrinityCore/TrinityCore/commit/49ec5fb583629c6dd64eff7c11ca81edd478a87e

When I try to compile 6.x I got:

http://paste.ubuntu.com/11110715/

EDIT: it just affects using Debug build **and** -DSCRIPTS=0, it works if you set -DSCRIPTS=0 **or** Release build

**Comment by jaredjones** [comment]
This error looks like the "DerivedData" folder on your machine is all fucked up. I don't believe that this is a TC issue.

**Comment by ShinDarth** [comment]
@jaredjones it's a fresh install of Yosemite, what can I do to fix that?

**Comment by jaredjones** [comment]
@ShinDarth 
Delete the contents of the derived data folder, make sure to close xcode first before you actually delete the folder.

http://stackoverflow.com/questions/18933321/deleting-contents-from-xcode-derived-data-folder

**Comment by ShinDarth** [comment]
@jaredjones 
thanks for help but it doesn't work, I didn't even have that folder, tried to let Xcode create it then deleted it but nothing

**Comment by jaredjones** [comment]
Your machine has to have that folder or else Xcode won't be building anything.

**Comment by jaredjones** [comment]
My apologies, I have confirmed that I cannot build on OS X Yosemite either.
![screen shot 2015-05-15 at 11 54 12 am](https://cloud.githubusercontent.com/assets/1316894/7657654/3fec18ea-faf9-11e4-95d0-6d5bc12398da.png)

**Comment by jaredjones** [comment]
This usually means a static library is corrupt.  The table of contents said a symbol was in an object file at some offset in the archive, but the linker later found there was no member at that offset.
-Nick at Apple
kledzik@apple.com

**Comment by jaredjones** [comment]
I'm also willing to bet that LLVM Clang (latest from master) won't be able to compile TC on Linux either.

**Comment by jchenevey** [comment]
I was able to compile just yesterday on Yosemite with -DSCRIPTS=0 (before, I had the same issue as above).

**Comment by jaredjones** [comment]
Well that is good to know, at least we know the issue lies in the script library or one of its dependencies. Does anybody have a SHA hash of a commit that was known to work with the script library?

**Comment by jchenevey** [comment]
More specifically (after talking to ShinDarth), I can compile, but when I try to log into the server, once I select the Trinity realm it attempts to load the character list (which at this point is empty, because new first-timer install), and gives an error of "Wrong format occurred (string pointer is null) at /Trinity/repo/src/server/game/sServer/WorldSocket.cpp:457" (path adjusted slightly to remove user name)

**Comment by ShinDarth** [comment]
Thank you @jchenevey for having pointed it ouy. I've tried myself and I can confirm that with -DSCRIPTS=0  I can successful compile.

**Comment by Shauren** [comment]
@jchenevey - ```Wrong format occurred (string pointer is null) at /Trinity/repo/src/server/game/sServer/WorldSocket.cpp:457``` is caused by bad zlib library - make sure you are using 1.2.7+

**Comment by jchenevey** [comment]
That's what I thought, but wasn't sure how to check my version on OS X, and since it's preinstalled and no mention is made in the install scripts, I assumed it was the correct version.

**Comment by Shauren** [comment]
If this man page is to be trusted https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/zlib.3.html then it's version 1.2.5 which is too old.

**Comment by jchenevey** [comment]
Any suggestion for updating? I'm kinda new to compiling and installing stuff like that from scratch.

**Comment by Shauren** [comment]
nope, macs are gay

**Comment by jaredjones** [comment]
@Shauren is gay and loves PHP.

Why don't we just bundle ZLIB into TC?

**Comment by Aokromes** [comment]
@jaredjones we already ship zlib with tc, but it's only used by windows, i sugested to make osx to use it too.

**Comment by jaredjones** [comment]
Instructions for Updating ZLIB on OS X:
1) Install Homebrew http://brew.sh
2) brew update
3) brew install zlib
4) brew link zlib --force
5) Delete CMake caches and recompile.

**Comment by jchenevey** [comment]
Thanks. I don't know if I'll have time to try this tonight but I'll let you know when I do. 

-Joe

**Comment by ShinDarth** [comment]
MBPdiFrancesco:~ Shin$ brew update
Already up-to-date.
MBPdiFrancesco:~ Shin$ brew install zlib
Error: No available formula for zlib 
Searching formulae...
lzlib
Searching taps...
MBPdiFrancesco:~ Shin$ brew link zlib --force
Error: No such keg: /usr/local/Cellar/zlib
MBPdiFrancesco:~ Shin$

**Comment by jchenevey** [comment]
I went ahead and tried lzlib instead. So try:

Brew install lzlib
Brew link lzlib --force

Then kill the cache and recompile

I haven't seen it the compilation was successful yet, though.

**Comment by ShinDarth** [comment]
Just tried and got again error

http://paste.ubuntu.com/11174782/

**Comment by jaredjones** [comment]
@ShinDarth My apologies. You have to add a repository into home-brew first. Please remove lzlib.
brew remove lzlib.

Type (and then rerun the : 
1) brew tap homebrew/dupes
2) brew update
3) brew install zlib
4) brew link zlib --force
5) Delete CMake caches and recompile.

**Comment by ShinDarth** [comment]
Build failed...

**Comment by jaredjones** [comment]
No the zlib thing is to fix the -DSCRIPTS=0 issue where WorldSocket.cpp would fail to let you log into the game. So the first step would be to compile without scripts and see if you can log in with the updated zlib. If you can then we can more onto getting it to compile with scripts.

**Comment by jchenevey** [comment]
Compiled successfully again, and can actually get a character list. But when I try to load the world, I get the same string pointer is null error as before.

**Comment by jaredjones** [comment]
I'm pretty sure you are just not linking ZLIB in correctly. Lets deviate from that topic and focus on getting this to compile with SCRIPTS enabled. Afterwards I'll submit a PR that fixes ZLIB on OS X.

**Comment by jaredjones** [comment]
Does anyone have a known GIT Checkout that would compile under OS X w/ scripts enabled? That we we can look in-between master and whenever the last known good build was and figure out the issue.

**Comment by ShinDarth** [comment]
are there any news?

**Comment by Gacko** [comment]
Build works from CLI - Xcode sucks buildings TC since... ever. That's why I added xodebuild on the Wiki as I wrote the guide. And no, not a TC issue at all. Build works for me with make and xcodebuild (both using clang and cmake).

**Comment by ShinDarth** [comment]
@Gacko I have the same configuration but with Cmake 3.2.2

**Comment by Shauren** [comment]
Oh yeah, about that
you CANNOT use -DPREFIX with cmake 3.2 and newer, replace it with -DCMAKE_INSTALL_PREFIX

**Comment by ShinDarth** [comment]
@Shauren I used that

**Comment by Gacko** [comment]
The last time I tried 3.2.2 was a month ago and I reverted to 3.0.2 because of several errors and warnings (CMP053 etc.). I'm gonna try 3.2.2 again tomorrow, but I don't think those errors are related to the prefix nor this issue.

**Comment by Shauren** [comment]
@Gacko CMP0053 is directly related to prefix

**Comment by Gacko** [comment]
Works with CMake 3.2.2 now.

**Comment by jaredjones** [comment]
So compiling via terminal works with SCRIPTS=1 for you guys, however, what about logging in and playing the game?

**Comment by Gacko** [comment]
Yes, compilation does work with CMake 3.2.2, make and clang on latest OS X (10.10.3). I did not test it with xcodebuild since I do not have Xcode itself installed (just Command Line Tools with Make). Further I can not approve a successful login (no 6.x client).

**Comment by ShinDarth** [comment]
I've tested again and it works using:
```xcodebuild -target install -config Release```

but I still got error when I use:
 ```xcodebuild -target install -config Debug```

**Comment by Rushor** [comment]
@ShinDarth: this issue still happens? :)

**Comment by ShinDarth** [comment]
I don't know, I didn't use TrinityCore on OS X for a while... now I've updated my system to El Capitan and I will test it there in future

**Comment by Gacko** [comment]
Non PCH works well atm. PCH is broken.
