### ISSUE TITLE
3.3.5 boss_yogg_saron

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#14686]
from https://github.com/TrinityCore/TrinityCore/commit/2c462ea77676d505774e9e14907e6cdfaf250c7a
DB:TDB58
update:2015_05_12_01_world.sql
scrtipname:boss_yogg_saron.cpp

boss_sara By Shadow Nova after injury（http://wotlk.openwow.com/spell=62714）Automatic back to full life And no phase transition

Please excuse my English.

**Comment by Aokromes** [comment]
#5194
