### ISSUE TITLE
[6.x] DB/Creature-GameObject Pandaria

### ISSUE THREAD

**Issue by VirusEntertainment** [TrinityCore/TrinityCore#14681]
http://www.mediafire.com/view/j792kzez8n8540w/Pandaria.txt

if the link gives error go here: http://alternativity.altervista.org/downloads/Pandaria.txt

these are spawns sniffed from my old sniffs from build 18414, the link is from mediafire because pastebin and tinypaste can't accept more that some kb of text.

MoP Instances/Raids, Isle of Thunder not spawned.

Hope it helps
Cheers

**Comment by DDuarte** [comment]
![image](https://cloud.githubusercontent.com/assets/530940/7563480/91336eaa-f7d5-11e4-9638-b992aec0eb8f.png)

**Comment by VirusEntertainment** [comment]
Try now

**Comment by DDuarte** [comment]
Seems fine, thanks.

**Comment by VirusEntertainment** [comment]
Link modified due to little correction (there were 2 npc that spawn with the mammooth mount)

**Comment by MitchesD** [comment]
there are some double spawns

**Comment by gegge** [comment]
Maybe it's because when i sniffed i passed Some zone twice, These errors can be Fixed with a sql patch later, for the moment i think 90-95% spawns are correct

**Comment by MitchesD** [comment]
well, you cant simply sniff something and then use it, you have to check for double spawns or waypoint spawns etc.

**Comment by Kinzcool** [comment]
Zone-sniffing is an art, and to add to what @MitchesD said, it's not simply a matter of sniffing. For one part, you have to sniff at moments where there are less people, but way more importantly, you have to sniff on a character that is in no phases, aka a level 90 boosted character in this case.

**Comment by gegge** [comment]
So this is to throw away? Cause there are some wrong spawns

**Comment by Kinzcool** [comment]
> So this is to throw away? Cause there are some wrong spawns

That's the thing, you don't know what you are talking about - I was refering to the fact player needed to had never set a foot in Pandaria.

**Comment by Exodius** [comment]
I can do that. I have a boosted character with no quests completed in Pandaria. Only place I ever visited with him is the Shrine because of the portals and because he is engineer (and there is Engineering AH there). If you need me for this, I'll try to hop onto IRC tomorrow after work so you can instruct me in "how to".

**Comment by Kinzcool** [comment]
@Exodius, I appereciate your offer, but plan to actually do like I did in 4.3.4 (~1 month), that is sniffing a lot of zones (this time being Pandaria). Though, let's say I end up doing like 4 of them, I sure would request your help.

**Comment by gegge** [comment]
got it
