### ISSUE TITLE
Remote access (do i need to restart the server?)

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14695]
TDB 3.3.5_58 #14605 

Hello. If i edit the config and change enable.Ra (remote access) to 1 while server is running and then '.reload config' will it work or i need to restart the server? Our PHP script shouts that 3443 port is closed.

**Comment by jackpoz** [comment]
the fastest way is to give it a try: if after .reload config it doesn't work and after a worldserver restart it works, then you have the answer to your question

**Comment by Aokromes** [comment]
This question belongs to forum.
http://www.trinitycore.org/f/
