### ISSUE TITLE
[3.3.5] Gunship - Skybreaker Sorcerer / Kor'kron Battle-Mage

### ISSUE THREAD

**Issue by Nazzgull** [TrinityCore/TrinityCore#14696]
Hello,
I'm running latest version of TrinityCore, compiled just few hours ago. No modification made.

**Zone**: Icecrown Citadel.
**Boss**: Gunship Battle.
**Issue**: Skybreaker Sorcerer / Kor'kron Battle-Mage won't spawn at any point of fight.

**How I tested this**: Two accounts dual logged clients, gm not enabled, only god mode. Fight started fine, mobs appeared, but there is no Battle mage which should cast Bellow Zero spell on cannons. You're able to finish fight I suppose, without mages, but there's no point. I would love to see fix if possible.

Core: fb9099a97c4a+
TDB: 335.58

**Comment by Rushor** [comment]
they spawn at every 20% loss - do you tested this?

**Comment by ccrs** [comment]
there is another issue open about this problem

**Comment by Killyana** [comment]
It was fixed https://github.com/TrinityCore/TrinityCore/issues/11883 but maybe some similar issues still happen.

**Comment by Runico** [comment]
@Killyana Nope, Shauren commit's wasn't fix the issue at all

**Comment by Mack36** [comment]
Mages are summoned when a non-player (enemy) ship is damaged more than a player's ship (at least for 10% afaik).

**Comment by Nazzgull** [comment]
Hmm.. Okay, will test it later on and provide feedback here.

**Comment by Shauren** [comment]
The first mage is summoned when enemy gunship is damaged below 90% and every 30 to 35 seconds after that

**Comment by Nazzgull** [comment]
Tested with 5 ppl around. You're right, it require % health of enemy ship. Thank you for fast response.
