### ISSUE TITLE
[6.x][Crash] WorldSession  0x00000000011d5fb6 in construct<WorldPacket*, WorldPacket* const&> (__p=0x8, this=0x7fff82bfd1c0) at /usr/include/c++/4.7/ext/new_allocator.h:110

### ISSUE THREAD

**Issue by doomkas** [TrinityCore/TrinityCore#14693]
rev https://github.com/TrinityCore/TrinityCore/commit/9f3cb912816a51ac92ab0274f8f5f57f41885fca
http://paste2.org/EjXF68kO

**Comment by jackpoz** [comment]
is this the whole log ? the header part with the build mode and commit hash is missing

**Comment by doomkas** [comment]
I downloaded the zip. There is no revision.

**Comment by Warpten** [comment]
What zip.

**Comment by Aokromes** [comment]
He used download source way.

**Comment by RedSonja** [comment]
I have no crash report, world server stops at this http://pastebin.com/Zq4cepFf

Has this map recently been added? I couldn't find it with a search, and just updated to tip today. The world ran before update. Not sure if I missed something or what.  Any info would be appreciated.

**Comment by Aokromes** [comment]
maps needs to be re-extracted since few days ago.

**Comment by RedSonja** [comment]
Ok thank you Aokromes :)

**Comment by jackpoz** [comment]
@doomkas please submit the complete log without editing it at all

**Comment by et65** [comment]
Same problem with last rev (a66cbab73b138672c0db8d9b3865812f17cbd002)

Crash logs http://pastebin.com/hit1sckc

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
