### ISSUE TITLE
Quest: Troll Patrol: Done to Death #12568

### ISSUE THREAD

**Issue by fvicaria** [TrinityCore/TrinityCore#14708]
The Argent Footman Corpses seem to be in a different phase. You can see them from the distance but when you get close they disappear.
Also when using the item (as a GM) the corpse does not burn and the count is not incremented.

Hash: 0a6f48b48cf1+
Latest DB
Info:
Quest: http://www.wowhead.com/quest=12568/troll-patrol-done-to-death
Item: http://www.wowhead.com/item=38556/incinerating-oil
Spell: http://www.wowhead.com/spell=51276/incinerate-corpse

**Comment by Killyana** [comment]
Can you provide your phase in this area and also nps(corpse) phase?

**Comment by Killyana** [comment]
WIP
``` sql
UPDATE smart_scripts SET event_type=61, event_param1=0, event_param2=0, event_param3=0, event_param4=0, action_param1=10000 WHERE entryorguid=28156 AND source_type=0 AND id=3;
UPDATE smart_scripts SET link=3 WHERE entryorguid=28156 AND source_type=0 AND id=2;
UPDATE smart_scripts SET event_flags=1 WHERE entryorguid=28156 AND source_type=0 AND id=0;

**Comment by fvicaria** [comment]
I have applied the changes and phase now is good but body still doesn't burn or credit is given.
I tried different combinations for the target type and spells order but still nothing.

**Comment by Killyana** [comment]
For me it's fine I get credit, corps burns for 10 secs and then despawn, also you cannot get credit from a burning corps.

**Comment by fvicaria** [comment]
Confirmed all work fine now. I did not have your last edit with the conditions.
Anywhere I can read more about the use of conditions?

**Comment by Killyana** [comment]
Here http://collab.kpsn.org/display/tc/conditions
