### ISSUE TITLE
[master] Core/GameObject: Elevator teleports instead of moving

### ISSUE THREAD

**Issue by burbur** [TrinityCore/TrinityCore#14704]
Hello there. Don't know if you can help me. 
I don't have Draenor branch downloaded, just the old cata one you deleted a bit ago (it seems) so i cannot post last revision or so :(

Anyway, i just downloaded it a while ago and didn't use it due to personal issues. 
I was just wandering around in Icc killing things when I saw a problem with the Lady deathwhisper Icc Elevator, the one that starts after you kill her. 

I just searched this repo to see if i was missing something and I've found this fix: https://github.com/TrinityCore/TrinityCore/commit/83668e8f8fcfc7a1e4c0904d29818e6f9a976389
I've just thought i missed it... but it was there. (Even because the elevator wasn't moving at the start). 
Anyway here is a little video explaining what's the problem. (The Orgrimmar's elevators work like a charm anyway, like that fix "had fixed").

Video proof: https://vid.me/zZxj

Am I missing anything? Does this work in Draenor Branch? 
Thank you.
##

**Comment by tkrokli** [comment]
@burbur : even if the source is moved, you can still post the full TC version string from your Worldserver.
Also, if needed, we can help you fix the revision link if your revision is not the last available one.
The latest available 4.3.4 commit (so far) is this: https://github.com/TrinityCoreArchive/TrinityCore434/commit/073d749e6fa5e911358425976aa2bd63a2036c87

**Comment by DDuarte** [comment]
Would someone be kind and confirm the bug on 6.x?

**Comment by Killyana** [comment]
The command .die don't trigger some events. Aggro the boss properly and kill him with .cast 5

**Comment by Killyana** [comment]
On 6.X the object just teleports from a position to another without movements.

**Comment by DDuarte** [comment]
That seems to be what is happening in the video posted above.

**Comment by burbur** [comment]
@tkrokli yes thank you! It's that because i've just pulled until it was available the branch. 

@Killyana In this case it does, because the behavior is the same. I've killed her "normally" and with ".die". Same result. The elevator starts and it just teleport up and down after the time (I believe) it needs to go from one side to the other. So if it need 24 seconds to go downstairs it will teleport after 24 seconds plus the time needed to be stopped on the "stopFrame", like in Shauren's fix is called.

@DDuarte yes. It just teleports with the player on it... it's like it has superspeed really, more than teleport. Seems like it takes the update to client (if it needed, don't know if we need to send the information to the client), or anyway the client updates the position, only when it comes to the "stopframe" saved in the gameobject_template.

**Comment by burbur** [comment]
I don't know if this could be of help but i just tried with another elevator, the one in halls of origination. I just wrote a little script for the controller that it's on the side. (The gossip were taken from a retail walkthrough but are not the important thing right now).

The script for the two gossips is:
First: 
```
go->SetTransportState(GO_STATE_TRANSPORT_ACTIVE);
```
Second:
```
go->SetTransportState(GO_STATE_TRANSPORT_ACTIVE, 0);
go->SetTransportState(GO_STATE_TRANSPORT_STOPPED, 1);
```

The reason for the second one is that with only (transport_stopped, 1) it doesn't move at all unless i click again the first... but i guess it's right in some way. 
From what i remember in retail (i had an account in Cataclysm) there are a total of three stairs, the last one is available after you cleared all the bosses. (In game_object_template -> lift of the maker, the elevator has "three" stopframes, 0-10000-16667, even if the 0 is not counted.)
Until the third is available you can press those two gossip to make it goes downstair or upstair, to reach the floor you've selected.

Right now it seems it just teleport as you "switch" gobj state.

Video Proof: https://vid.me/dVoH

**Comment by joschiwald** [comment]
try with 266c09f8a95c06b758f1c9b0e2e52cafd451f757

**Comment by burbur** [comment]
@joschiwald Nothing to do... same behavior!

**Comment by burbur** [comment]
Well, i've just done some sniff today (on halls of origination elevator) with a friend's retail account... seems like this is what i got:

This is from when i press the second option to take it to the second floor. (GossipIndex: 1, while 0 is to the first floor, as in my video)

```
ClientToServer: CMSG_GOSSIP_SELECT_OPTION (0x1E0C) Length: 24 ConnIdx: 1 Time: 05/23/2015 14:06:56.125 Number: 217
GossipUnit: Full: 0x283AE45080CACD400014080000E087D9 GameObject/0 R3769/S5128 Map: 644 Entry: 207669 Low: 14714841
GossipID: 12646
GossipIndex: 1
PromotionCode: 

ServerToClient: SMSG_GOSSIP_COMPLETE (0x0010) Length: 0 ConnIdx: 0 Time: 05/23/2015 14:06:56.406 Number: 218

ServerToClient: SMSG_UPDATE_OBJECT (0x1CB2) Length: 42 ConnIdx: 1 Time: 05/23/2015 14:06:56.406 Number: 219
NumObjUpdates: 1
MapID: 644 (644)
HasDestroyObjects: False
Data size: 31
[0] UpdateType: Values
[0] Object Guid: Full: 0x143AE4001000000000000000000006BD Transport/0 R3769/S0 Map: 0 Low: 1725
[0] GAMEOBJECT_LEVEL: 2165917968/-2.815408E-38
[0] GAMEOBJECT_BYTES_1: 4278192921/-1.701988E+38

ClientToServer: CMSG_CLOSE_INTERACTION (0x1C36) Length: 15 ConnIdx: 1 Time: 05/23/2015 14:06:56.406 Number: 220
Guid: Full: 0x283AE45080CACD400014080000E087D9 GameObject/0 R3769/S5128 Map: 644 Entry: 207669 Low: 14714841
```

I guess the update_object is about the elevator, but i'm not sure.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
cannot reproduce on f6637439f484

**Comment by Killyana** [comment]
Still happen on 7.x and 4.3.4

**Comment by aquadeus** [comment]
after last commits about transport is this still valid?

**Comment by Shauren** [comment]
No, those commits specifically fix that issue
