### ISSUE TITLE
[3.3.5] Core/Scripts: Death's Challenge & The Endless Hunger

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14700]
TrinityCore rev. 5bd7c29 2015-05-13 22:29:49 +0200 (3.3.5 branch) (Win64, Release)

Quest: Death's Challenge http://www.wowhead.com/quest=12733/deaths-challenge (ID: 12733)
```
Olrun the Battlecaller has ordered you to win 5 duels against other death knights.
You may choose to battle death knight initiates or players.
```
- Death Knights defeated in a duel (5)

Actually 2 issues here, 1 practical (game mechanics) and 1 cosmetic :
- According to the quest description, it should be possible to choose between challenging the NPCs named "Death Knight Initiate" and challenging other players. I have tested with 3 simultaneous accounts, two normal (gmlevel 0) accounts and one gmlevel 3 account, even tried using a Night Elf vs Blood Elf with PvP on, but it appears impossible to challenge each other the same way as the NPCs. The player character names still appear in blue color, not green.

![wowscrnshot_051515_074200](https://cloud.githubusercontent.com/assets/4903600/7647763/8ccf8fe4-fada-11e4-9bbf-71353630e187.jpg)

- When my player character challenges a *Death Knight Initiate*, there are 8 (9) lines of text to choose from in the database, but 2 of them use the **$n** with the intention of showing the target name in the /Say text scripted in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L497 :

![wowscrnshot_051515_060657](https://cloud.githubusercontent.com/assets/4903600/7647753/76922c6e-fada-11e4-97cc-afbfb994a1aa.jpg)

```cpp
sCreatureTextMgr->SendChat(creature, SAY_DUEL, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, player);
```
The text is pulled from the database table `creature_text` and looks like this:
```sql
(28406,0,0,'No potions!',12,0,100,0,0,0,29265,0,'dk initiate SAY_DUEL_A'),
(28406,0,1,'Remember this day, $n, for it is the day that you will be thoroughly owned.',12,0,100,0,0,0,29270,0,'dk initiate SAY_DUEL_B'),
(28406,0,2,'I\'m going to tear your heart out, cupcake!',12,0,100,0,0,0,29263,0,'dk initiate SAY_DUEL_C'),
(28406,0,3,'I\'m going to tear your heart out, cupcake!',12,0,100,0,0,0,29263,0,'dk initiate SAY_DUEL_D'),
(28406,0,4,'Here come the tears...',12,0,100,0,0,0,29264,0,'dk initiate SAY_DUEL_E'),
(28406,0,5,'You have challenged death itself!',12,0,100,0,0,0,29262,0,'dk initiate SAY_DUEL_F'),
(28406,0,6,'The Lich King will see his true champion on this day!',12,0,100,0,0,0,29268,0,'dk initiate SAY_DUEL_G'),
(28406,0,7,'You\'re going down!',12,0,100,0,0,0,29266,0,'dk initiate SAY_DUEL_H'),
(28406,0,8,'You don\'t stand a chance, $n.',12,0,100,0,0,0,29267,0,'dk initiate SAY_DUEL_I'),
```
When I first saw the $n issue, I thought it would be just as easy as modifying the NPC quest / zone scripts, but since this text is said by the Player and with either NPC or Player as target, I really don't know.

Edit: To test this yourself, it only takes 10 minutes from starting a new DK to accepting this quest.

**Comment by MrSmite** [comment]
I've actually seen the *$n* issue quite often on 335 lately but usually just ignore it. Usually when I see it it's in a dialog that I'm clicking through.

I wonder if there's some problem with the way the strings are being parsed by the core.

**Comment by Aokromes** [comment]
Another https://github.com/TrinityCore/TrinityCore/commit/8126faccdaf1d8182cbf483a1f8262830164e9fa very likely.

**Comment by Rushor** [comment]
but this time, the creature sends the chat manually towards the player, normal talkactions from the creature have the option to enable the worldobject (player) as target. here we have the player as actor which cannot target the original creature maybe

**Comment by tkrokli** [comment]
@Aokromes : at first, I was thinking the same, but this time the roles are reversed, like Rushor said.

Update: Also in http://www.wowhead.com/quest=12848/the-endless-hunger when repeating the fight :
![wowscrnshot_072015_032132](https://cloud.githubusercontent.com/assets/4903600/8768910/214b6830-2e90-11e5-9f29-b7631cbfe4c1.jpg)
TrinityCore rev. 3c4484d782ac 2015-07-20 01:16:47 +0100 (3.3.5 branch) (Win64, Release)

I almost would not have noticed, if it wasn't for the fact that I was studying the behaviour of the NPC [Unworthy Initiate] and comparing with the video pete318 (r00ty) linked in PR #15116, https://youtu.be/ADiaJS585RM?t=2m54s, where I discovered that the NPC should go to the weapon rack instead of to the soul prison anchor like they do in TC source. (But that is a different cosmetic issue.)

I am thinking that it has got something to do with the "SAY" lines in both scripts:

`npc_unworthy_initiate` => https://github.com/TrinityCore/TrinityCore/blob/3c4484d782ace3e3662840dfa2574f334c0e8e9a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L159 :
```cpp
sCreatureTextMgr->SendChat(me, SAY_EVENT_ATTACK, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, starter);
```
`npc_death_knight_initiate` => https://github.com/TrinityCore/TrinityCore/blob/3c4484d782ace3e3662840dfa2574f334c0e8e9a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L497 :
```cpp
sCreatureTextMgr->SendChat(creature, SAY_DUEL, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, player);
```
Before I start changing something that might crash my build, has anyone got a suggestion about where I could try setting a pointer that makes the script set the player to target the NPC when saying the line?
(It does not help to target the NPC in-game, the script ignores what the player has selected currently.)

**Comment by tkrokli** [comment]
I think I have found out what is wrong with the script, at least for Quest ID 12733 [Death's Challenge].
The Player character is NOT supposed to say the text, the NPCs are supposed to say them. That makes a lot more sense too, otherwise the creature text could have used the title "Death Knight Initiate" instead of $n if the player says it. Take a look at the YouTube video from 2009, part 2/2 of the previous video I linked:

[![Death's Challenge](http://img.youtube.com/vi/hhaSikag_CY/0.jpg)](http://www.youtube.com/watch?v=hhaSikag_CY)
(Fast forward the video to 2:30 or 2:35 to see the duel where the NPC uses the player's name.)

But if the NPC is supposed to talk and not the player, why is the player saying the text?
It looks like the line `sCreatureTextMgr->SendChat(creature, SAY_DUEL, NULL, CHAT_MSG_ADDON, [...]`
points to the creature and not the player, so why won't the NPC creature say the text?

As for Quest 12848 [The Endless Hunger], I don't quite see how the NPC is supposed to say 2 lines.

BTW: I tried switching some values in line 159 and 497, but it did not work. I don't know enough yet.

**Comment by tkrokli** [comment]
Found some more "evidence" that the DK Initiates are supposed to say the text, not the player :
By carnifex2005 (1,711 – 6·12) on 2008/11/17 (Patch 3.0.3):
http://www.wowhead.com/quest=12733/deaths-challenge#comments:id=449902
`I laughed out loud at the exchange when you challenge a Death Knight Initiate...`
`Death Knight Initiate says: Remember this day, <Character Name>, for it is the day that you will be thoroughly owned.`

By msdeller (1,066 – 2·13) on 2009/11/08 (Patch 3.2.2):
http://www.wowhead.com/quest=12733/deaths-challenge#comments:id=885898
`Other Death Knight Initiate's quotes:`

`"No potions!"`
`"You're going down!"`
`"Here come the tears..."`
`"You don't stand a chance, <Character Name>."`
`"I'm going to tear your heart out, cupcake!"`

So the Say scripting is wrong, the script should select [[NPC 28392]](http://wotlk.openwow.com/npc=28392) and not the player.

**Comment by MrSmite** [comment]
The problem is how *sCreatureTextMgr->SendChat()* uses the *player* parameter sent to it by the script:

```C++
Unit* finalSource = source;
if (srcPlr)
    finalSource = srcPlr;

// snip

SendChatPacket(finalSource, builder, finalType, whisperTarget, range, team, gmOnly);
```

It appears that becasue the script sends the *player* to *SendChat()*, it swaps out the creature *source* with the player.

**Comment by tkrokli** [comment]
> It appears that because the script sends the player to SendChat() (srcPlr parameter), it swaps out the creature source with the player so when SendChatPacket() is called it uses the player instead of the creature.

Interesting. Wish I knew more about how to change that behaviour or implement the opposite effect.
I wonder why the quest wasn't scripted like other quests where the NPC does all the talking...
(I won't have time to look for solutions or comparisons this week, but if someone has a suggestion, you are more than welcome to comment and suggest.) :)

**Comment by tkrokli** [comment]
This way, the say text for `npc_unworthy_initiate` in [[quest 12848 The Endless Hunger]](http://www.wowhead.com/quest=12848/the-endless-hunger) works correctly:
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index 9747d31..955ad3f 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -156,7 +156,7 @@ public:
                 me->CastSpell(me, SPELL_DK_INITIATE_VISUAL, true);
 
                 if (Player* starter = ObjectAccessor::GetPlayer(*me, playerGUID))
-                    sCreatureTextMgr->SendChat(me, SAY_EVENT_ATTACK, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, starter);
+                    Talk(SAY_EVENT_ATTACK, starter);
 
                 phase = PHASE_TO_ATTACK;
             }
```
Based on the successful change above, I tried to use the same code for [Death's Challenge (ID 12733)](http://www.wowhead.com/quest=12733/deaths-challenge) ...
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index 955ad3f..3cb1d53 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -494,7 +494,8 @@ public:
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNK_15);
 
-            sCreatureTextMgr->SendChat(creature, SAY_DUEL, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, player);
+            if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
+                Talk(SAY_EVENT_ATTACK, player);
 
             player->CastSpell(creature, SPELL_DUEL, false);
             player->CastSpell(player, SPELL_DUEL_FLAG, true);
```
... but it causes the following error lines:
```
Error C2065: 'me'         : undeclared identifier /src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp    498    1    scripts
Error C2065: 'playerGUID' : undeclared identifier /src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp    498    1    scripts
Error C3861: 'Talk'       :  identifier not found /src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp    499    1    scripts
```
I could just create a separate PR for the working code change, since it is related to a separate quest (and script) event. I would just have to write something like "updates issue #14700" in the commit text.

**Comment by Rushor** [comment]
you never mentioned playerGUID before in the script

**Comment by tkrokli** [comment]
2015-10-08, 19:30 CEST, @Rushor said:
> you never mentioned playerGUID before in the script

Yes. I sort of knew that, but I didn't know that it could be the most important piece of those 3 errors.
I wonder if I can use `m_uiDuelerGUID` instead of `playerGUID` since it is defined in the same section, `ObjectGuid m_uiDuelerGUID;` in the script I want to update. Hmm... I will test and get back to you.

**Comment by tkrokli** [comment]
So I finally found out how to do it after reading through the script until I started to understand it:

```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index bc50dd8..360ab0f 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -457,6 +457,7 @@ enum Spells_DKI
     //SPELL_DUEL_TRIGGERED        = 52990,
     SPELL_DUEL_VICTORY          = 52994,
     SPELL_DUEL_FLAG             = 52991,
+    GROVEL                      = 7267,
 };
 
 enum Says_VBM
@@ -494,8 +495,6 @@ public:
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNK_15);
 
-            sCreatureTextMgr->SendChat(creature, SAY_DUEL, NULL, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_NORMAL, 0, TEAM_OTHER, false, player);
-
             player->CastSpell(creature, SPELL_DUEL, false);
             player->CastSpell(player, SPELL_DUEL_FLAG, true);
         }
@@ -518,11 +517,6 @@ public:
         return true;
     }
 
-    CreatureAI* GetAI(Creature* creature) const override
-    {
-        return new npc_death_knight_initiateAI(creature);
-    }
-
     struct npc_death_knight_initiateAI : public CombatAI
     {
         npc_death_knight_initiateAI(Creature* creature) : CombatAI(creature)
@@ -540,6 +534,7 @@ public:
 
         bool lose;
         ObjectGuid m_uiDuelerGUID;
+        ObjectGuid playerGUID;
         uint32 m_uiDuelTimer;
         bool m_bIsDuelInProgress;
 
@@ -557,6 +552,7 @@ public:
             if (!m_bIsDuelInProgress && pSpell->Id == SPELL_DUEL)
             {
                 m_uiDuelerGUID = pCaster->GetGUID();
+                Talk(SAY_DUEL, pCaster);
                 m_bIsDuelInProgress = true;
             }
         }
@@ -577,7 +573,7 @@ public:
                         pDoneBy->AttackStop();
                         me->CastSpell(pDoneBy, SPELL_DUEL_VICTORY, true);
                         lose = true;
-                        me->CastSpell(me, 7267, true);
+                        me->CastSpell(me, GROVEL, true);
                         me->RestoreFaction();
                     }
                 }
@@ -607,13 +603,13 @@ public:
             {
                 if (lose)
                 {
-                    if (!me->HasAura(7267))
+                    if (!me->HasAura(GROVEL))
                         EnterEvadeMode();
                     return;
                 }
                 else if (me->GetVictim() && me->EnsureVictim()->GetTypeId() == TYPEID_PLAYER && me->EnsureVictim()->HealthBelowPct(10))
                 {
-                    me->EnsureVictim()->CastSpell(me->GetVictim(), 7267, true); // beg
+                    me->EnsureVictim()->CastSpell(me->GetVictim(), GROVEL, true); // beg
                     me->EnsureVictim()->RemoveGameObject(SPELL_DUEL_FLAG, true);
                     EnterEvadeMode();
                     return;
@@ -625,6 +621,11 @@ public:
             CombatAI::UpdateAI(uiDiff);
         }
     };
+    
+    CreatureAI* GetAI(Creature* creature) const override
+    {
+        return new npc_death_knight_initiateAI(creature);
+    }
 
 };
