### ISSUE TITLE
[3.3.5] Warlock Pet running after duel.

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#14712]
If the pet is in a passive state (Ctrl + 0) and stay (CTRL + 3) in duels, if the warlock sending attack the other player at the end of the duel (winning or losing) the pet begins to run to it disappears.

Losing Duel: https://www.youtube.com/watch?v=PutZlxkGlK8
Win Duel: https://www.youtube.com/watch?v=_Xpdee-fVtI

TrinityCore rev. 5bd7c295c0b0 2015-05-13 22:29:49 +0200 (3.3.5 branch) (Win64, Release)
TDB_full_335.58_2015_03_21

**Comment by Aokromes** [comment]
Maybe related to #14242

**Comment by Keader** [comment]
I think yes

**Comment by Keader** [comment]
Fix #14242  work for me
