### ISSUE TITLE
[6.x] DBC, MAPS

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14711]
Good afternoon

When I was extracting the dbc and maps they gave me these errors and did not know if this was normal.

Rev: https://github.com/TrinityCore/TrinityCore/commit/2678c52b1fb893a3bec92a0c1caaf167cc1554f1

Link: http://pastebin.com/YuXAfD10

**Comment by tkrokli** [comment]
Read all of this: https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
At least add your TrinityCore version string from Worldserver in line 1 of your post. It would also help if you add more description to your post: http://collab.kpsn.org/display/tc/The+Issuetracker+and+You

**Comment by DDuarte** [comment]
It's normal, ignore those errors.
