### ISSUE TITLE
StartUp Errors

### ISSUE THREAD

**Issue by Dokman** [TrinityCore/TrinityCore#14717]
I have all up to date but i have this errors

Spell 43770 Effect: 43789 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 48750 Effect: 48770 listed in `spell_linked_spell` has same bp2 like effect (possible hack)
Spell 53099 Effect: 53098 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 54640 Effect: 54643 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
Spell 55288 Effect: 55289 listed in `spell_linked_spell` has same bp0 like effect (possible hack)
SourceEntry 37748 SourceGroup 6 in `condition` table - spell 37748 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 1, SourceGroup needs correction, ignoring.
SourceEntry 37748 SourceGroup 6 in `condition` table - spell 37748 does not have implicit targets of types: _AREA_, _CONE_, _NEARBY_ for effect 2, SourceGroup needs correction, ignoring.
ScriptName 'npc_brann_bronzebeard' exists in database, but no core script found!

**Comment by Aokromes** [comment]
#13707
