### ISSUE TITLE
Authserver freezes after some time.

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14715]
TDB 335_58 #14605 rev f020f6f51974
Everything was okay for one day and yesterday the problem appeared.

After some time the authserver stops (after doing the second 'updating realmlist'). There are 400 clients trying to login (but it also freezes when 1 person tries to login - 3 AM).

Tried to change the realmlist update time from 20 to 0 (worked for 5 hours and the freeze came again).

What can cause the problem?

**Comment by Aokromes** [comment]
cannot reproduce, i have months of uptime on authserver.

**Comment by selenir** [comment]
Totally no idea? Database packets size? Mysql connection?

**Comment by Noah1911** [comment]
Add revision hash.

**Comment by selenir** [comment]
updated rev

**Comment by jackpoz** [comment]
enable debug logs and check the logs

**Comment by selenir** [comment]
TrinityCore rev. f020f6f51974 2015-05-16 11:52:01 +0100 (3.3.5 branch) (Unix, R$
<Ctrl-C> to stop.

Using configuration file /usr/local/etc/authserver.conf.
Using SSL version: OpenSSL 1.0.1f 6 Jan 2014 (library: OpenSSL 1.0.1f 6 Jan 201$
Using Boost version: 1.54.0
Opening DatabasePool 'auth2'. Asynchronous connections: 1, synchronous connecti$
MySQL client library: 5.5.43
MySQL server ver: 5.5.43-0ubuntu0.14.04.1
Connected to MySQL database at localhost
MySQL client library: 5.5.43
MySQL server ver: 5.5.43-0ubuntu0.14.04.1
Connected to MySQL database at localhost
DatabasePool 'auth2' opened successfully. 2 total connections running.
Started auth database connection pool.
Updating Realm List...
Added realm "Darkmoon" at 5.196.255.95:8085.
Using processors (bitmask, hex): 1

It allow 5-10 ppl to log in and the rest is stuck at authenticating.

**Comment by selenir** [comment]
It freezes at Entering _HandleRealmList

**Comment by jackpoz** [comment]
is the log above a Debug log ? I see only usual Information messages

**Comment by et65** [comment]
Same for me, month of uptime for my authserver and no crash/freeze.

**Comment by selenir** [comment]
Debug log.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/authserver/authserver.conf.dist#L311 and https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/authserver/authserver.conf.dist#L331 set to 2 (or even 1) ?

**Comment by selenir** [comment]
It was caused by sending compresset packets to autherver by the attacker. No idea how to fix it.

**Comment by jackpoz** [comment]
you need to add rules to your firewall to drop connections/packets if there is an ongoing DoS attack

**Comment by selenir** [comment]
Yes, I can drop connection that is sending packet larger than x or connection that sends more than x packets per for ex. 5 seconds but what if packets are compressed?
