### ISSUE TITLE
[3.3.5] DB/NPC: Moving pet trainers to DB

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14719]
Some changes must be done here https://github.com/TrinityCore/TrinityCore/blob/7d1d55124c1e289748d2afefae896c97f710e57b/src/server/scripts/World/npcs_special.cpp#L1682
- Use gossips and options from the DB
- Remove useless conditions, just the one to show the option n°2 must be kept (if the player have a summoned pet)

Also ResetPetTalents(); (gossip option2) must stay there cause it's impossible to move it to DB.
``` sql
UPDATE `creature_template` SET `gossip_menu_id`=4783 WHERE `entry` IN (40405, 3698, 3545, 3306, 4320, 16675, 543);
UPDATE `creature_template` SET `exp`=0, `npcflag`=17, `trainer_type`=3, `flags_extra`=2, `ScriptName`="npc_pet_trainer" WHERE `entry`=40405;

UPDATE `npc_text` SET `BroadcastTextId0`=29541 WHERE `id`=13469;
UPDATE `npc_text` SET `BroadcastTextId0`=29562 WHERE `id`=13470;
UPDATE `npc_text` SET `BroadcastTextId0`=29578 WHERE `id`=13471;
UPDATE `npc_text` SET `BroadcastTextId0`=29581 WHERE `id`=13472;
UPDATE `npc_text` SET `BroadcastTextId0`=29626 WHERE `id`=13474;

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14,15) AND `SourceGroup`=4783;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`ErrorTextId`,`ScriptName`,`Comment`, `NegativeCondition`) VALUES
(14, 4783, 5838, 0, 15, 4, 0, 0, 0, '', 'Show gossip text if player is a hunter', 0),
(14, 4783, 5839, 0, 15, 4, 0, 0, 0, '', 'Show gossip text if player is not a hunter', 1),
(15, 4783, 0, 0, 15, 4, 0, 0, 0, '', 'Show gossip option if player is a hunter', 0),
(15, 4783, 1, 0, 15, 4, 0, 0, 0, '', 'Show gossip option if player is a hunter', 0);
```

**Comment by msoky** [comment]
what about stable masters? https://github.com/TrinityCore/TrinityCore/issues/11094

**Comment by Killyana** [comment]
I'm just moving gossips to the DB.

**Comment by Alastyr** [comment]
I don't think that NPC 3698 is a pet trainer. WoWHead doens't specify this. In fact his name is "Bolyun" instead of "Bolyun <Pet Trainer>".

**Comment by Aokromes** [comment]
http://www.wowwiki.com/Bolyun it looks they removed that on 4.0.3

**Comment by Alastyr** [comment]
@Aokromes Thank you!

**Comment by tkrokli** [comment]
OK, so now my PR [**Core/Scripts: move Pet Trainer gossip to DB**](17746) #17746 works as intended. Finally. ;-)
