### ISSUE TITLE
[3.3.5] Sindragosa - Tombs do not spawn on third phase

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14729]
TDB 335_58 Rev #14605

On third phase Sindragosa should cast Frost Tomb on random player, while on ground. It happens, but target is selected, gets the mark but the Tomb itself (GObject) does not appear.

Is there any requirement in player's distance from boss? In code everything seems to be ok.

**Comment by Aokromes** [comment]
stop reporting bugs without follow rules.
