### ISSUE TITLE
[3.3.5] Master Smith Burinate and Gaining Even More Acceptance

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14724]
Once you complete first quest, you can't turn other Dark Iron residues of rep. So you can't take Gaining Even More Acceptance

http://www.wowhead.com/quest=7737/gaining-even-more-acceptance

DB 335.58
rev 2b95a5f 2015-04-26
##

**Comment by Aokromes** [comment]
Check that you don't fit this:
http://www.wowhead.com/quest=7737/gaining-even-more-acceptance#comments:id=1640498

**Comment by ikir83** [comment]
I should not, since i'm revered with them. I see question mark on npc head, but if i right click it just open "buy/sell window"

**Comment by Rushor** [comment]
maybe related to this: https://github.com/TrinityCore/TrinityCore/issues/12713?

**Comment by Killyana** [comment]
The player must be:
The Player's standing with Confrérie du thorium is Friendly
The Player's standing with Confrérie du thorium is not Honored

Tested and works correctly.
