### ISSUE TITLE
[3.3.5a] Koralon (VoA) bugged loot (Can't loot pve items)

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14721]
Hiho! TDB 335_58 #14605 

http://imgur.com/DLHwHLV,fJ0JUSq

Screenshots above. When a masterlooter clicks a PvP item everything is ok - he can pick the raid member and give it to him. With PvE items the system is asking "Sure, to bind this item to you?" And nothing happens (looter stands up and closes the body).

it happens only on Koralon. Toravon, Emaion are working.

Any ideas?

Thank you.

**Comment by Killyana** [comment]
Cannot reproduce on rev. f020f6f51974
There's known issue with loots and there's already a ticket.
