### ISSUE TITLE
[3.3.5] Item - Robes of Insight

### ISSUE THREAD

**Issue by Kensaki** [TrinityCore/TrinityCore#14734]
The item Robes of Insight 
http://www.wowhead.com/item=940/robes-of-insight

It's supposed to reduce mana cost for the next spell only, seems to reduce mana cost by 500 for all spells cast within 10 seconds.

DB 335.58
rev 8572eea4ea2a    2015-05-17

**Comment by Killyana** [comment]
Because the 18820 is not removed when the first spell is casted.

**Comment by Rushor** [comment]
sth like:

```c++
class spell_item_insight : public SpellScriptLoader
{
    public:
        spell_item_insight() : SpellScriptLoader("spell_item_insight") { }

        class spell_item_insight_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_item_insight_AuraScript);

            void HandleProc(ProcEventInfo& /*eventInfo*/)
            {
                GetTarget()->RemoveAura(GetSpellInfo()->Id);
            }

            void Register()
            {
                OnProc += AuraProcFn(spell_item_insight_AuraScript::HandleProc);
            }
        };

        AuraScript* GetAuraScript() const
        {
            return new spell_item_insight_AuraScript();
        }
};
```

**Comment by joschiwald** [comment]
i think it is better to change proccharges in spellinfo like it is done for similar spells
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L3124

**Comment by Exodius** [comment]
@Rushor @Aokromes Git failed to close the issue.

**Comment by Rushor** [comment]
we are closing prs now? i mean if the 'fix' from the pr would not be correct and devs would close the pr, the original issue would be lost :/

**Comment by Exodius** [comment]
Oh, I didn't see that this was PR. Sorry :)
Didn't had any bad intentions.
