### ISSUE TITLE
Echoes of Lordaeron after leaving region

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14739]
http://www.wowhead.com/spell=1386/echoes-of-lordaeron

The buff remain on players even when you leave Eastern Plaguelands. Maybe i remember it wrong but it should be only in that region plus stratholme.

DB 335.58
rev 2b95a5f 2015-04-26

**Comment by tkrokli** [comment]
http://www.wowhead.com/spell=1386/echoes-of-lordaeron#comments :
`By Discolando (17,794 – 2·23·106) on 2008/07/11 (Patch 2.4.2)`
This is the Alliance version of the zone-wide buff when all four towers are under Alliance control. This buff will persist in Stratholme and Scholomance.
Last edited by Discolando on 2008/07/11 (Patch 2.4.2)
***
http://wotlk.openwow.com/spell=1386

**Comment by Killyana** [comment]
The aura fades if you leave the eastern plague land.
rev. f020f6f51974

**Comment by tkrokli** [comment]
@ikir83 : it looks like you need to update your core and database. I can't remember exactly when or where, but I think there has been done some work on aura handling since your core was made.

**Comment by ikir83** [comment]
I need to update the core today or sunday when i have time, but DB should be fine is automatic updates are really working

**Comment by tkrokli** [comment]
Make sure to compile a new core as often as possible. Some of the database updates are meant to work when the core is updated too, even if many of them are independent.
