### ISSUE TITLE
instance Trial Of The Champion 

### ISSUE THREAD

**Issue by iraj0711** [TrinityCore/TrinityCore#14731]
hi.instance toc 5 man (TrialOfTheChampion) is buged?

**Comment by Aokromes** [comment]
duplicate.

**Comment by iraj0711** [comment]
close??????????
instance is buged.can you fix instance toc 5 man?

**Comment by Nyeriah** [comment]
It has acknowledged issues that are being slowly addressed here https://github.com/TrinityCore/TrinityCore/pull/14478

This is not the place for this kind of discussion and that's why it has been closed (and why it'll now be locked)
