### ISSUE TITLE
[3.3.5] Stratholme scarlet crusade

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14737]
Hi in the scarlet area of stratholme (level 60) undead and scarlet soldier aren't fighting each other and undead continue to eade players attack

PS: also quest item in the room for The Archivist quest can be destroyed by one plater at time. I've seen this also in Ulduman, interact with quest item can be only done by one player

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by ikir83** [comment]
![schermata 2015-05-21 alle 23 03 03](https://cloud.githubusercontent.com/assets/10136428/7758918/916cc728-000d-11e5-9cb7-79477a5c0ed2.png)

**Comment by tkrokli** [comment]
@ikir83 : Notice that your issues will be closed without warning when you don't provide core revision hash.

**Comment by ikir83** [comment]
DB 335.58
rev 2b95a5f 2015-04-26

**Comment by tkrokli** [comment]
Not sure if this is a specific issue or if it is a duplicate of a general evade issue. Check #4943 or search::
https://github.com/TrinityCore/TrinityCore/search?q=evade&state=open&type=Issues&utf8=✓

**Comment by Frytiks** [comment]
@ikir83 Try this, it help me in more ways https://github.com/TrinityCore/TrinityCore/issues/4943#issuecomment-82042130
