### ISSUE TITLE
No Set Realm

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14738]
hello problems QueryHandler.cpp  //realm name - only set for cross realm interaction (such as Battlegrounds)
 id wrote Realm
It does not work
I wrote to the id realms but all exactly

**Comment by Carbenium** [comment]
Could you please rephrase your issue? And add a revision hash too.

**Comment by Spectrance** [comment]
52

**Comment by Carbenium** [comment]
Ehh what? The answer to everything is 42.
I'll close this now. If you think your issue is an actual bug, then open a new ticket in proper english please. But before you do that, read our contribuiting guidelines.

**Comment by Spectrance** [comment]
Forgive solve this problem I can not find the answer

**Comment by tkrokli** [comment]
@Spectrance : Try asking in the TrinityCore Forum : http://www.trinitycore.org/f/

This issue tracker here is not a forum page, it is **only** for reporting bugs in the source.
