### ISSUE TITLE
Cannot interact with Pylons at Dire Maul

### ISSUE THREAD

**Issue by fvicaria** [TrinityCore/TrinityCore#14746]
I am not sure if I am missing anything here.
We are supposed to deactivate 5 pylons to bring the force shield down.
Here are the ids:
177259 177258 177257 179504 179505

And the guid if you want to use ".go object guid"
29746 29745 29744 29743 29742

The problem is that you can only interact with Pylons as a GM.

Is it a flag issue?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Rushor** [comment]
dublicate of #14685
