### ISSUE TITLE
[3.3.5] Sunstrider guardian aren't attacking alliance player

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14744]
Sunstrider guardian aren't  attacking alliance player

![schermata 2015-05-22 alle 22 40 30](https://cloud.githubusercontent.com/assets/10136428/7779307/95d70938-00d3-11e5-89a5-80dc380f8eec.png)

tried at sun strider isle bridge. manny npc there aren't attacking me. Instead Silvermoon guards seem ok.

for example this npc ranger sirloin aren't attacking neither
http://www.wowhead.com/npc=15940/ranger-selron

DB 335.58
rev 0148832 2015-05-21

**Comment by Rushor** [comment]
at least on official server, they are attacking you

**Comment by Rushor** [comment]
```sql
UPDATE `creature_template` SET `unit_flags`=4096 WHERE  `entry`=15371;
```

it will fix your issue, but normally we will never change these fields

**Comment by Kittnz** [comment]
Any sniff?

**Comment by ikir83** [comment]
Ok i will query on my DB to fix this, but why not fix this on your releases?

PS: my DB is brand new, erased everything yesterday

**Comment by Aokromes** [comment]
because that query is hack.

**Comment by msoky** [comment]
why theese npcs have mana=2 ??

**Comment by ikir83** [comment]
Many NPC there are still acting weird. For example Evensong Ranger aren't attacking me but i appear in combat and they are staring at me lol. Sun strider guardian still aren't attacking me.

**Comment by ikir83** [comment]
![schermata 2015-05-27 alle 14 35 16](https://cloud.githubusercontent.com/assets/10136428/7836561/50092f7e-0481-11e5-9288-4246d6a97577.png)

**Comment by Killyana** [comment]
WIP
``` sql
UPDATE `smart_scripts` SET `action_param1`=1, `comment`='Eversong Ranger - Out of Combat - Enable Combat Movement' WHERE `entryorguid`=15938 AND `source_type`=0 AND `id`=0;
UPDATE `smart_scripts` SET `action_param1`=1, `COMMENT`='Eversong Ranger - Out of Combat - Start Attacking' WHERE `entryorguid`=15938 AND `source_type`=0 AND `id`=1;

**Comment by tkrokli** [comment]
I just tested @joschiwald's theory in https://github.com/TrinityCore/TrinityCore/pull/14780/files#r31157384
```diff
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 7f00fc7..f7e32a2 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1370,9 +1370,6 @@ bool Creature::CanStartAttack(Unit const* who, bool force) const
     if (IsCivilian())
         return false;
 
-    if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC))
-        return false;
-
     // Do not attack non-combat pets
     if (who->GetTypeId() == TYPEID_UNIT && who->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
         return false;
```
After making this change in my 3.3.5 source, the [[Sunstrider Guardians]](http://wotlk.openwow.com/npc=15371) reacted and attacked my nightelf hunter, but stopped attacking when I switched GM on again. GM on did not work for the hunter's pet, though. Not sure what stopped working there.

@ikir83 : notice that [[Ranger Selron]](http://www.wowhead.com/npc=15940/ranger-selron) is neither a guard nor has got the PvP flag on, so he will never attack a player (unless attacked first). Any NPC without the PvP flag will normally not attack a player of the opposite faction, unless the player attacks the NPC first.

**Comment by tkrokli** [comment]
@ikir83 : I just checked with @mik1893 and he has changed his PR to look like the suggestion above from @joschiwald, so you will find that it will work as soon as PR #14780 is merged (soon™).

**Comment by Carbenium** [comment]
e7484151d5483ee478d4a293b8a7b6e37e4d26af
