### ISSUE TITLE
[3.3.5] Blood Furnace: Broggok fight doesn't progress

### ISSUE THREAD

**Issue by czw** [TrinityCore/TrinityCore#14747]
When pulling the lever, you get to fight the first bunch of Nascent Fel Orc. After they are killed, you're still in combat but the rest of the chambers remain locked. The only way out is hearthstone or similar means.

Tested on 82664273cc47.

**Comment by Aokromes** [comment]
works for me on 9e3001a44b7f

**Comment by czw** [comment]
Tested again in 82664273cc47, can't reproduce.

**Comment by tkrokli** [comment]
Thanks for the update. :+1:
