### ISSUE TITLE
[6.x] Loot is not working while part of a party

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14749]
TrinityCore rev. 61b0889e6ce2+ 2015-05-23 12:09:23 +0200 (6.x branch) (Win64, Release) (worldserver-daemon)

After killing a creature i am not able to loot anything...
Prevented sending disabled opcode [SMSG_LOOT_LIST 0x08E2 (2274)] to [Player: Lubia (GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1)]

**Comment by Yalunima** [comment]
After reextracting all dbc, maps, vmaps, mmaps this problem is solved...

**Comment by DDuarte** [comment]
Reextracting dbc or maps doesn't fix packet related issues...

**Comment by Yalunima** [comment]
I have build a group with another player and the problem is back again, no one is able to loot the creatures when you are inside a party...
Leaving the party and killing a creature and i am able to loot....

**Comment by Ascathor** [comment]
I assume the loot opcode is not fixed yet. Not sure if there is one for groups and one for solo, though.

**Comment by et65** [comment]
For my part , I've uninstall my firewall and now I can loot! 

Without joke, loot packets related to party are not implemented yet :)

**Comment by alysher** [comment]
this seems to have come back. i have re extracted dbc, maps, mmaps, and vmaps, running on latest core and am unable to loot.

**Comment by tkrokli** [comment]
I am hoping that #15143 by Zerixx (Core/PacketIO: Updated and Enabled currently supported loot packets) will be of help in this issue.

**Comment by alysher** [comment]
ya
