### ISSUE TITLE
Database - Emotefields

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14757]
Suggestion:
I would be very helpful to enable the possibility to add multiple emotes to creature_addon / creature_template_addon.

Currently we have:
```sql
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES 
```
Atm we can add multiple numbers to `auras` and all auras will be applied to the creature on spawn/reset.

Well then it would be nice to add multiple number to `emote` too.

Example where it would be useful:
DB GUID: 126164
Entry: 26554

What we want:
3 rndm emotes every 2 sek.

How we must script it currently:
```sql
-- Dragonflayer Seer SAI
SET @GUID := -126164;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=26554;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@GUID AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@GUID,0,0,0,1,0,100,0,2000,2000,2000,2000,10,5,1,8,0,0,0,1,0,0,0,0,0,0,0,"Dragonflayer Seer - Out of Combat - Play Random Emote (5, 1, 8)");
```
What is negative about this:
If we apply a single guid-script to the creature, the normal entry-script of 26554 will not be excecuted

entry-script:
```sql
-- Dragonflayer Seer SAI
SET @ENTRY := 26554;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,6,0,0,7000,11000,11,48698,64,0,0,0,0,2,0,0,0,0,0,0,0,"Dragonflayer Seer - In Combat CMC - Cast 'Lightning Bolt' (Dungeon) Heroic 59081"),
(@ENTRY,0,1,0,0,0,100,6,4000,7000,12000,15000,11,48699,64,0,0,0,0,5,0,0,0,0,0,0,0,"Dragonflayer Seer - In Combat CMC - Cast 'Chain Lightning' (Dungeon) Heroic 59082"),
(@ENTRY,0,2,0,74,0,100,6,0,30,18000,21000,11,48700,0,0,0,0,0,9,0,0,0,0,0,0,0,"Dragonflayer Seer - On Friendly Between 0-30% Health - Cast 'Healing Wave' (Dungeon) Heroic 59083");
```

**Comment by Rushor** [comment]
just as conclusion from recent ideas:

enable guid-script and entry-script would be a possible start to work on

It can break something else maybe, but there is no easy solution to add an update in:
bool Creature::LoadCreaturesAddon(bool reload)
for multiple emotes

**Comment by joschiwald** [comment]
there is a difference between these emotes, the emotes from creature_addon are sent in `UnitField` `UNIT_NPC_EMOTESTATE`, the emotes you mean are sent in `SMSG_EMOTE`

**Comment by Rushor** [comment]
got some new ideas for this with `waypoint_data` and `action` which will solve all our problems while scripting stuff for npcs with SAI and waypoint_datas

i will create a propper tricket later with some examples
