### ISSUE TITLE
[6.x] Spell "Renew" & "Power Word: Fortitude" with Priest/Holy is crashing the worldserver

### ISSUE THREAD

**Issue by Yalunima** [TrinityCore/TrinityCore#14751]
TrinityCore rev. 61b0889e6ce2+ 2015-05-23 12:09:23 +0200 (6.x branch) (Win64, Release) (worldserver-daemon)

When i cast the spell "Renew" (Priest/Holy) on myself or an NPC all works well.
But when i cast it on another player the worldserver is crashing...

**Comment by Aokromes** [comment]
pls compile on debug mode and supply crashlogs.

**Comment by Yalunima** [comment]
Using Visual Studio Ultimate 2013 - Version 12.0.31101.00 Update 4
I can´t find any crashlog.
I compiled in debug mode, a new folder appears: D:\Build\bin\Debug
I copied dbc,maps,mmaps,vmaps, libeay32.dll,libmysql.dll,libzmq-v120-mt-4_0_4.dll,ssleay32.dll,bnetserver.conf, worldserver.conf from D:\Build\bin\Release to D:\Build\bin\Debug
And run the bnetserver.exe and worldserver.exe from there.
Used the spell Renew on another player character, worldserver.exe crashes but theres no folder named Crashes like in D:\Build\bin\Release...
There are some files in D:\Build\bin\Release\Crashes from today, but all file length are 0. There are also files from earlier days there with valid file contents.
I could also click on debug with Visual Studio after the crash but don´t know how to use it correct...

**Comment by DDuarte** [comment]
Copy all the .pdb files as well.

**Comment by Yalunima** [comment]
In the window D:\Build\bin\Debug\worldserver.exe are 2 error messages:
C:\Program Files (x86)\Microsoft Visual Studio 12-0\VC\include\vector(240) : Assertion failed: vector iterators incompatible
C:\Program Files (x86)\Microsoft Visual Studio 12-0\VC\include\vector(241) : Assertion failed: "Standard C++ Libraries Invalid Argument" && 0

.pdb files for each .exe are present after building in Debug Mode in the folder D:\Build\bin\Debug.
There are no .pdb files in the folder D:\Build\bin\Release.

**Comment by DDuarte** [comment]
When you see Assertion failed let worldserver crash. You'll have a crash log in the /Crashes directory.

**Comment by Yalunima** [comment]
But in the folder D:\Build\bin\Debug is no folder named Crashes !!!
Only in D:\Build\bin\Release\Crashes are 4 pairs of .dmp and .txt files with file lenght 0, so useless...

**Comment by Yalunima** [comment]
The same with the Spell "Power Word: Fortitude":
If i use the spell on myself it works fine, if i use it on another player character the worldserver is crashing. Worldserver running from inside the Debug Folder but no Crashslog will be generated...

**Comment by Shauren** [comment]
Unable to reproduce.

**Comment by EPS1L0N** [comment]
try casting it on a low level toon

**Comment by Boomper** [comment]
The crash is from https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/Spell.cpp#L860
according to .dmp file (.txt crashlogs are typical ACCESS_VIOLATION useless information)

How to replicate:
Create Priest -> level up to lvl 100 -> create another character on different account ("the other guy" from now on) -> cast Renew onto "the other guy" (make sure to keep "the other guy" on lvl 1) -> server crashes

Under Windows 8.1 64Bit, Win64 RelWithDebInfo https://github.com/TrinityCore/TrinityCore/commit/eee0eebf5141b16ea2c442b1ea7176abd7600bb8

**Comment by jackpoz** [comment]
no matter how many times we ask for a crash log, users decide NOT to post them

**Comment by Boomper** [comment]
Sorry for that, forgot to attach the crash log...
here's a new one (finally one that doesn't end after ACESS_VIOLATION)
http://pastebin.com/Qmz0afUk
