### ISSUE TITLE
DB Auto Updater

### ISSUE THREAD

**Issue by glkrlos** [TrinityCore/TrinityCore#14759]
6.x 735606bc7329b63ff

Here is a problem, when you start the connection with database using socket you get an error using auto updates:

This error:
Unknown suffix '/' used for variable 'port' (value '/var/run/mysqld/mysqld.sock')

In file: src/server/shared/Updater/DBUpdater.cpp: Line 338: Or in my comment https://github.com/TrinityCore/TrinityCore/commit/2bd1c8541d638f5041a92f491f02919270981bc2#commitcomment-11345421

Maybe the fix is adding --protocol=SOCKET when initial connection was socket?

**Comment by Naios** [comment]
We already had a topic in the [help section of the forum](http://www.trinitycore.org/f/topic/11272-automatic-db-update-system-335/?p=73126) about this.
If you could give me example arguments which are required to connect the mysql cli to a server using sockets i will add this funtionality.

**Comment by DDuarte** [comment]
https://dev.mysql.com/doc/refman/5.5/en/connecting.html#option_general_socket

**Comment by glkrlos** [comment]
http://www.trinitycore.org/f/topic/11272-automatic-db-update-system-335/?p=73515

**Comment by Killyana** [comment]
It will be closed with the PR.

**Comment by DDuarte** [comment]
This isn't fixed yet.
