### ISSUE TITLE
Battleground spirit guide not resurrecting player

### ISSUE THREAD

**Issue by LebenHarvest** [TrinityCore/TrinityCore#14754]
As title states when killed in a battleground the spirit guide at graveyard does not prompt the player with a resurrection timer nor resurrect the player at all.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by LebenHarvest** [comment]
6.x

**Comment by LebenHarvest** [comment]
and lol wut

**Comment by Alastyr** [comment]
@LebenHarvest you should edit main topic. Follow this post for example (https://github.com/TrinityCore/TrinityCore/issues/14751) or Aokromes' link (https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md).

**Comment by LebenHarvest** [comment]
Yes I will
