### ISSUE TITLE
[6.x] Graveyards not working properly

### ISSUE THREAD

**Issue by LebenHarvest** [TrinityCore/TrinityCore#14758]
TrinityCore rev. c44273e (6.x branch)
![graveyard error](https://cloud.githubusercontent.com/assets/753802/7789583/a9c446ce-021b-11e5-8a35-c9aa77b72fce.jpg)

When a player dies console prints this error. I have cross checked the dbcs and database and the table seems to be correct. Any ideas?

**Comment by Aokromes** [comment]
#14089
