### ISSUE TITLE
[6.x] dk problem

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#14752]
revis c44273ec9320af1a21a31b3b7b7e59f7869836a1
dk not stick their spells and none hurt

**Comment by DDuarte** [comment]
What?

**Comment by Frytiks** [comment]
I think he talking about most death knight spell doesn't make any damage. Etc. Death and Decay not doing any damage. Tooltip ingame talking 
Suffering 0 Shadow damage every sec. I can make for this a report.

**Comment by tkrokli** [comment]
In addition to "Death Knights not making any damage", I also think he is trying to say that the DK spells don't seem to "stick", meaning that the DKs don't keep their spells or the spells disappear (?).

**Comment by Rushor** [comment]
dup https://github.com/TrinityCore/TrinityCore/issues/14825
