### ISSUE TITLE
3.3.5 crash on lord marrawgar 

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14768]
Rev https://github.com/TrinityCore/TrinityCore/commit/41a69fa37cb01b9d99f81a033650a41ee652fad6

crash log http://pastebin.com/Yy44FAV6

when he casts bone spike graveyard server crashs

might be spell bugged or some

**Comment by DDuarte** [comment]
```c++
            npc_bone_spikeAI(Creature* creature) : ScriptedAI(creature), _hasTrappedUnit(false)
            {
                ASSERT(creature->GetVehicleKit());

                SetCombatMovement(false);
            }
```

**Comment by gearsofdeath** [comment]
i have this

**Comment by DDuarte** [comment]
I know you do. The "crash" happens in the assert. Your Bone Spike doesn't have a vehicle kit for whatever reasons.

What DB are you using?

**Comment by gearsofdeath** [comment]
TDB 335.57

**Comment by tkrokli** [comment]
@gearsofdeath : are you absolutely sure about that DB version? TDB 335.58 was released 2015-03-21.
Your commit suggests that you are using SQL files including the commit from less than 3 hours ago.
Keeping your DB in sync with the core by inserting TDB 335.58 + updates is recommended.

**Comment by Nyeriah** [comment]
Cannot confirm or reproduce. That crash *looks* like compromised database data.

**Comment by Shauren** [comment]
shit db data, not our issue since we have it set correctly in tdb

**Comment by Lillecarl** [comment]
<Aokromes> meh silly shauren [09:32:48] <WardenX> TrinityCore/TrinityCore: Shauren closed issue #14768: 3.3.5 crash on lord marrawgar  http://git.io/vkev0
<Aokromes> instead adding it to startup
<Aokromes> core NEVER must crash on runtime because bad db data


I agree, things musn't crash because of bad DB data.

**Comment by Shauren** [comment]
yeeee nooo, assert intended

**Comment by tkrokli** [comment]
`TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, RelWithDebInfo)`
(from the OP's crash log)

meh... Waste of time, not supported. I completely agree with closing this.
