### ISSUE TITLE
[3.3.5] Spell school lockouts not being sent to clientside

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#14762]
rev: https://github.com/TrinityCore/TrinityCore/commit/9e3001a44b7fbc0f098f24e0e554f3c35aad7f64

When your spell casts get interrupted and the given school is locked your spells no longer get the usual lock timer animation, but still it errors if you try to cast them.

Relates to https://github.com/TrinityCore/TrinityCore/commit/e70790576414dde16b56fd828d52a79ef540d3e9

**Comment by Aokromes** [comment]
Confirmed on 9e3001a44b7f
