### ISSUE TITLE
3.3.5 lord marrawgar  kills him self

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14769]
Rev: https://github.com/TrinityCore/TrinityCore/commit/735606bc7329b63ffa950b9a5f4385763e238d52

i have updated my TDB so the crash is fixed, but the problem now

when the boss casts bone spike he targets him self and kill him self with it

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L626
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L97

tell me, how this can target boss?

**Comment by gearsofdeath** [comment]
i dont know exactly but the spell is bugged as far as i know, since i've added the impale and impaled in 
spell linked 


INSERT INTO `world335`.`spell_linked_spell` (`spell_trigger`, `spell_effect`, `comment`) VALUES (69057, 72670, 'bone spike');
INSERT INTO `world335`.`spell_linked_spell` (`spell_trigger`, `comment`) VALUES (69057, 'bone spike');

but the spell targets the caster i even tried learning it, on my character and casts it on mobs, i got infected not the targeted

and spell impale stuns and bleeding debuff wont disappear like you are always have the debuff even if ur dead.

**Comment by MitchesD** [comment]
you did some changes with this spell in spell_linked_spell? why? this spell works as inteded without any needed changes. Use default TC DB and core. Also its logical if you use that spell (with player character), you will be the target, since it can target only players

**Comment by gearsofdeath** [comment]
with Fresh TDB when boss casts the spell nothing happens

**Comment by mik1893** [comment]
working fine on 3.3.5 it's a custom or old core... close plz

**Comment by MitchesD** [comment]
with how many target did you test it? obviously with one target he will not cast it

**Comment by gearsofdeath** [comment]
well he did cast it i saw the cast bar and then nothing happens i wont get spiked

**Comment by MitchesD** [comment]
answer my question above, with how many target did you test it?

**Comment by gearsofdeath** [comment]
it was only me fighting the boss

**Comment by mik1893** [comment]
then it will never work... the spell doesnt target the tank

**Comment by MitchesD** [comment]
then it works as intended, this spell wont hit the main tank

**Comment by gearsofdeath** [comment]
i tried with 3 persons, still wont work, fresh TDB no effect

with adding to spell_linked_spell it targets him self

which means spell issue

**Comment by mik1893** [comment]
we have tested it is working fine. update your core to latest version

**Comment by MitchesD** [comment]
also you said that you use Rev: 735606b
but thats ONLY for 6.x but you are talking about 335, so please stop lying about that ;-) I guess you have a bit mess on your server (maybe some custom patches or some pack)

**Comment by gearsofdeath** [comment]
i will try compiling new core and see thank you :)

**Comment by gearsofdeath** [comment]
Working.

**Comment by mik1893** [comment]
i wont wish you a nice day tbh
