### ISSUE TITLE
Absorb Auras & Warlock Glyph of Shadowflame

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#14761]
All absorb auras:
http://wotlk.openwow.com/spell=47891
http://www.wowhead.com/spell=17
etc.
Absorb Glyph of Shadow Flame
Use http://wotlk.openwow.com/spell=47891 (Shadow Ward)
(Absorb shadow-damage) 
Why Absorb Glyph of Shadow Flame?
http://i.imgur.com/vesYCpy.jpg
http://i.imgur.com/1ybATKb.jpg

and other absorb auras, absorb glyph of shadow flame.

**Comment by Shauren** [comment]
This is not understandable at all.
