### ISSUE TITLE
[3.3.5] In Dreams quest bugged

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14767]
Can't complete because  Taelan Fordring didn't follow players

http://www.wowhead.com/quest=5944/in-dreams

DB 335.58
rev 0148832 2015-05-21

**Comment by Runico** [comment]
confirm, but it doesn't happens all time, sometimes work as well,

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/7519
