### ISSUE TITLE
3.3.5 Raid ICC

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14772]
Rev:https://github.com/TrinityCore/TrinityCore/commit/db3b22c63e7efcce9871f116b2eacd721d71490b

I'll be posting all the issues found in Icecrown Citadel in this thread. Better than having one thread per issue, I think. If not, feel free to split it :)

- Gunship: if the encounter ends while a player is on the enemy ship, he/she should be teleported on the platform near Overlord Saurfang (or on the player faction's ship. I'm not sure about this). Instead, said player falls to his/her death. Needs some more testing to make sure when it happens.
- Most of the fire wall traps in the tunnel right after Overlord Saurfang do not work. Only the last one works.
- Sindragosa: the Ice Tomb aura is not removed when Sindragosa dies. Players can get stuck forever, since the aura has no duration (infinite).
- Lich King: the valkyries (Val'kyr Shadowguard) should spawn outside the "arena", fly near a player, pick him/her up and fly slowly toward the outer abyss. Instead, they instantly teleport to the player. Needs more testing to make sure their speed is properly set.

...

**Comment by Killyana** [comment]
Check the opened issues, and do not post multiples bugs on the same issue.

**Comment by tkrokli** [comment]
@gearsofdeath : notice what **Killyana** has written above. See list below for details:
- Never create an issue with multiple bugs, that is not how TrinityCore works.
- Search the TrinityCore issue tracker for existing bugs before reporting bugs like you did in your post 
(all the bugs you have listed are already reported, so your post is not needed).
- Learn more about existing bug reports before posting a new issue.

Read the following pages before posting again:
- http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
- http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
- http://www.trinitycore.org/f/topic/10656-updating-or-starting-with-trinitycore-issues/

**Comment by Nyeriah** [comment]
(Off-topic) You got the "tl;dr" idea backwards.

**Comment by tkrokli** [comment]
Yes, my thoughts are backwards like that. :smirk:
