### ISSUE TITLE
[3.3.5] Focus Magic proc

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14779]
Focus Magic doesn't proc on melee crits, just on spell crits.

http://wotlk.openwow.com/spell=54648

db3b22c63e7efcce9871f116b2eacd721d71490b

**Comment by MartinBT** [comment]
I think it's not suppose to proc on melee crits.

http://wowwiki.wikia.com/Focus_Magic

**Comment by Killyana** [comment]
When the target critically hits with a spell, the buff's caster also gains 3% increased chance to critically hit with spells during 10 seconds.
