### ISSUE TITLE
[335][ICC] Gunship Battle - Ending - Missing Playerport

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#14773]
Gunship: if the encounter ends while a player is on the enemy ship, he/she should be teleported on the platform near Overlord Saurfang (or on the player faction's ship. I'm not sure about this). Instead, said player falls to his/her death. Needs some more testing to make sure when it happens.

Rev:https://github.com/TrinityCore/TrinityCore/commit/db3b22c63e7efcce9871f116b2eacd721d71490b

**Comment by Killyana** [comment]
This happen only when you try to use the jetpack to return on the other ship after the end of the battle when the 2 ships are moving, and I don't think that this can be fixed, otherwise the teleport works correctly.

**Comment by gearsofdeath** [comment]
Fixed, had to reinstall the DB
