### ISSUE TITLE
[3.3.5] Bosses and Elite NPC

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14784]
when the players went to the ICC are not difficult to kill their bosses + s6 things
1 Hill keeps the weight group not only ICC even other instants

even elite mobs damage low yields,
  35 level has killed Gorlash not difficult

settings is 100% level and other

TDB 335.52 - 2013/07/17 
Rev   3875ae0

**Comment by Rushor** [comment]
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by Spectrance** [comment]
where I find the revision number?

**Comment by Aokromes** [comment]
Update your core and database before reporting bugs.
