### ISSUE TITLE
[3.3.5] No Set Realms for Cross realm

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14786]
I updated my core and base before the last
redid everything as indicated in the 3 realms Wiki established and no base but the connection to each other on the battlegrounds and random dungeon
for cross server where I missed a mistake?

in the forum there are similar themes and indicated the site for patches and bugs that I have to create one ?
if you eat the answer to this question show!

Rev 3600751
TDB 335.58

**Comment by DJScias** [comment]
Eh, I have a lot of difficulty in understanding what your issue is and wha

**Comment by DDuarte** [comment]
Cross realms are not supported.
