### ISSUE TITLE
[3.3.5] No Set Realms for Cross realm

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14787]
I updated my core and base before the last
redid everything as indicated in the 3 realms Wiki established and no base but the connection to each other on the battlegrounds and random dungeon
for cross server where I missed a mistake?

in the forum there are similar themes and indicated the site for patches and bugs that I have to create one ?
if you eat the answer to this question show!

Rev 3600751
TDB 335.58

(DDuarte->  Cross realms are not supported.)->
if not supported by Queryhandler.cpp specified but no patches and no aid
Trinity if that does not help anyone help?!

**Comment by Rushor** [comment]
start a topic in the forum to ask for support, but since this is not a real 'issue' all these issues will be closed

**Comment by Spectrance** [comment]
I was told that in the form of eating such topics
and there eat Patches

**Comment by DDuarte** [comment]
I cannot understand a word that you say.

Do not open new issues about your "issue".

Cross realms are not supported.
