### ISSUE TITLE
Spell resistance/binary resists

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#1478]
TrinityCore revision e7ff1196ed8e2a0782d7
TDB 3.38

Old patch from dr.tenma http://code.google.com/p/trinitycore/issues/detail?id=2088 implements binary resists.
At one time he tackled the problem of resistance and fixed the problem with resielence from damage from casters.

Currently the patch does not work, but the problem with resielence from damage from casters was not solved. Please review and update the patch and submit it to the repo.
##

**Comment by lineagedr** [comment]
Any news on this?

**Comment by Staleness89** [comment]
https://www.reddit.com/r/wowservers/comments/59tvha/cmangos_presents_first_fully_blizzlike_magic/

**Comment by Demonid** [comment]
Awesome work Cmangos did there, lets hope it can be ported to TC.

**Comment by Keader** [comment]
93746e8c4a79c8256cd4896533315683f143508c
