### ISSUE TITLE
[3.3.5] Core/Spells: DK Death rune usage wrong

### ISSUE THREAD

**Issue by czw** [TrinityCore/TrinityCore#14796]
When a DK casts a spell costing a Frost rune, the current version of TrinityCore has this priority:
* Find a Frost rune
* Use any Death rune

WOTLK had a small and subtle difference in the prioritization, but it was one that makes certain rotations much easier:
* Find a Frost rune
* Find a Death rune that was originally a Frost rune
* Use any Death rune
 
Tested on 62ebd002d990. Fix in progress.

**Comment by mik1893** [comment]
Closed by #50d435f
