### ISSUE TITLE
[6.x] Pet System

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#14794]
TrinityCore rev.  https://github.com/TrinityCore/TrinityCore/commit/c1bd3282f8149890003bb353186131afe4708172 (6.x branch)

class hunter 
I can not control My Pet   
there is no actionbar to control pet

and can not learn pet's talent

**Comment by tkrokli** [comment]
The 6.x branch is heavy Alpha status, so if this issue is real, it needs to be worked on for some time.
Just don't expect it to be working at the moment. TrinityCore needs more contribution work on this branch.

**Comment by brecky** [comment]
https://github.com/brecky/TrinityCore/commits/Pet_6.x

**Comment by Rushor** [comment]
see also https://github.com/TrinityCore/TrinityCore/pull/16387

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
Hunter pets and the pet control bar is working in 6.x rev. 96e5d9cd68dc 2016-06-14 19:01:30 +0200 (6.x branch) (Win64, Release). Pet control works as expected too. I did not take the time to check pet talents, though, but this issue page in itself is too outdated to be useful for tracking (IMO).

The only issue I could see, is that the pet sometimes randomly despawned  at odd times in my movements in the terrain, mostly in starting areas. But that is material for a different issue page.
