### ISSUE TITLE
[3.3.5][6.x] Naxxramas: Gluth, doesn't eat the zombies close to him

### ISSUE THREAD

**Issue by chaodhib** [TrinityCore/TrinityCore#14806]
How to reproduce the bug:
1. Go to "Naxxaramas" zone.
2. Start "Gluth" Encounter.
3. Wait for at least one zombie to pop and bring Gluth close to it (in melee range).

What should happen, what happens instead:
Gluth should turn to the zombie and eat/kill him (and in the process, heal myself a percentage of his hps). What actually happens is nothing. Gluth does correctly the emote but doesnt kill the zombies.

I already investigated the issue and looked at the code. And like predicted (by looking at an older issue regarding the zombies: https://github.com/TrinityCore/TrinityCore/issues/5005), the bug stems from the faction settings of the 2 creatures. They are friendly to each other.

The weird thing is that the rest of the code would work perfectly as it is if the corresponding dbc file (FactionTemplate.dbc) was changed accordingly. Therefore, I'm beginning to suspect that I'm using a wrong DBC or something. A confirmation/infirmation of the bug would be great.

Since the dbc files are extracted from the client, I suppose it would be bad practise to fix the bug by touching to the dbc. I could work on the issue by modifying the code if the bug is confirmed.

CORE revision number: da101732f99d9397634bbc92962aa959d4a476b5 (branch 3.3.5a)
TDB 335.58

Thank you for reading me.
Kind regards,
Chaouki Dhib

**Comment by DDuarte** [comment]
Changing DBCs would be a VeryBadIdea™. Most likely the code needs to be changed and I'm fairly sure your DBCs are not the wrong ones.

**Comment by Rushor** [comment]
```c++
                        case EVENT_CHECK_ZOMBIE:
                            if (Creature* zombie = me->FindNearestCreature(NPC_ZOMBIE, 7.0f, true))
                            {
                                if (me->IsWithinMeleeRange(zombie))
                                {
                                    me->Kill(zombie);
                                    me->ModifyHealth(int32(me->CountPctFromMaxHealth(5)));
                                }
                            }
                            events.ScheduleEvent(EVENT_CHECK_ZOMBIE, 500);
                            break;
```

maybe sth like that in the updateai or a similar script in the void MoveInLineOfSight(Unit* who) override
or maybe there is a spell for gluth to add the hp

**Comment by chaodhib** [comment]
Gluth is affiliated with FactionTemplate 21. The zombies are affiliated with FactionTemplate 233. Both of these FactionTemplates are part of the Faction 20 (Undead, Sourge) and therefore, there is no surprise that the 2 FactionTemplates are friendly with Faction 20 therefore with each other.

==> conclusion: Gluth and the zombies are friendly toward each other. So the method call SetGazeOn() on line 76 doesnt do anything.

A good but also easy way to fix: changing the zombie's FactionTemplate.

Candidates: "1620" ("Enemy") and "2189" to "2191" (those 3 are "Hates Everything").

I think it would be best to take 2191 since it also have the FactionTemplateFlags::FACTION_TEMPLATE_FLAG_HOSTILE_BY_DEFAULT flag (my only concern would be non-combat pets).

More info about FactionTemplate "2191" ": 
Part of the Faction 1145 (whose name is "Hates Everything"). This FactionTemplate is hostile to everyone (players and creatures alike) and has a creature mask, which is perfect for us.

so, the fix itself is: (one line for 10 man, the other for 25 man)

```SQL
UPDATE `world`.`creature_template` SET `faction`='2191' WHERE `entry`='16360';
UPDATE `world`.`creature_template` SET `faction`='2191' WHERE `entry`='30303';
```

With this change, every time a new zombie pop, it already has Gluth in their Threat table (with value zero) which makes them run toward him if no player aggro them, which is the right behavior we are aiming for.

**Comment by DDuarte** [comment]
> A good but also easy way to fix: changing the zombie's FactionTemplate.

You are correct on the "easy" part but not good. I'll need to verify however I'm fairly sure that the value 21 came from sniffs and therefore it should not be changed.

**Comment by chaodhib** [comment]
Gluth has FactionTemplate 21. I haven't changed that. I only changed the FactionTemplate of the zombies.

**Comment by DDuarte** [comment]
I meant 233.

**Comment by DDuarte** [comment]
```
ServerToClient: SMSG_UPDATE_OBJECT (0x6264) Length: 230 ConnIdx: 2 Time: 04/09/2012 16:45:55.892 Number: 161878
Map: 533
Count: 2
[0] UpdateType: Values
[0] GUID: Full: 0xF1303E3C000120CA Type: Creature Entry: 15932 Low: 73930
[0] UNIT_FIELD_FLAGS: 526400/7.376435E-40
[1] UpdateType: CreateObject2
[1] GUID: Full: 0xF1303FE80001D3EF Type: Creature Entry: 16360 Low: 119791
[1] Object Type: Unit (3)
[1] Living: True
[1] Has Attacking Target: False
[1] Has Vehicle Data: False
[1] Has Stationary Position: False
[1] Has GameObject Position: False
[1] Has AnimKits: False
[1] Has GameObject Rotation: False
[1] Has Fall Data: False
[1] Has Spline Data: False
[1] Has Transport Data: False
[1] Walk Speed: 2.5
[1] FlyBack Speed: 3.141593
[1] Turn Speed: 7
[1] Run Speed: 6
[1] Pitch Speed: 3.141593
[1] RunBack Speed: 4.5
[1] SwimBack Speed: 2.5
[1] Fly Speed: 4.5
[1] Swim Speed: 4.72222
[1] GUID 2: Full: 0xF1303FE80001D3EF Type: Creature Entry: 16360 Low: 119791
[1] Orientation: 5.88176
[1] Position: X: 3270.132 Y: -3169.948 Z: 297.5891
[1] OBJECT_FIELD_GUID: 119791/1.678629E-40
[1] 1: 4046471144/-8.727459E+29
[1] OBJECT_FIELD_TYPE: 9/1.261169E-44
[1] OBJECT_FIELD_ENTRY: 16360/2.292524E-41
[1] OBJECT_FIELD_SCALE_X: 1065353216/1
[1] UNIT_FIELD_BYTES_0: 16908544/2.387795E-38
[1] UNIT_FIELD_HEALTH: 504000/7.062544E-40
[1] UNIT_FIELD_MAXHEALTH: 504000/7.062544E-40
[1] UNIT_FIELD_LEVEL: 80/1.121039E-43
[1] UNIT_FIELD_FACTIONTEMPLATE: 233/3.265025E-43
[1] UNIT_FIELD_FLAGS_2: 2048/2.869859E-42
[1] UNIT_FIELD_BASEATTACKTIME: 3000/4.203895E-42
[1] 57: 3000/4.203895E-42
[1] UNIT_FIELD_BOUNDINGRADIUS: 1057308541/0.5205
[1] UNIT_FIELD_COMBATREACH: 1069547520/1.5
[1] UNIT_FIELD_DISPLAYID: 10975/1.537925E-41
[1] UNIT_FIELD_NATIVEDISPLAYID: 10975/1.537925E-41
[1] UNIT_MOD_CAST_SPEED: 1065353216/1
[1] UNIT_MOD_CAST_HASTE: 1065353216/1
[1] UNIT_CREATED_BY_SPELL: 28217/3.954044E-41
[1] UNIT_FIELD_BYTES_2: 1/1.401298E-45
[1] UNIT_FIELD_HOVERHEIGHT: 1065353216/1
```

> [1] UNIT_FIELD_FACTIONTEMPLATE: 233/3.265025E-43

As I said, faction 233 is correct and shouldn't be changed.

**Comment by chaodhib** [comment]
Alright. is 21 for Gluth also static? We could look into changing that.

**Comment by DDuarte** [comment]
Changing factions is a bad idea. 21 is correct.

---

Zombies are spawned with aura http://www.wowhead.com/spell=29307/infected-wound
Gluth says "%s spots a zombie to devour!" and casts http://www.wowhead.com/spell=28239/zombie-chow-search on the Zombie

And then I don't know how they are killed because Aokromes' warlock is too competent at killing zombies.

**Comment by ccrs** [comment]
spell http://www.wowhead.com/spell=28239/zombie-chow-search has
Effect 0: Id 1 (SPELL_EFFECT_INSTAKILL)

**Comment by DDuarte** [comment]
Indeed, I missed that. Casting that spell should spell all the hacks and faction issues.

**Comment by chaodhib** [comment]
There is also http://www.wowhead.com/spell=28404/zombie-chow-search with the same name.

I looked at the Spell.dbc file and this is IMO the only relevant info regarding the 2 spells:

28239
Attribut 0= 0x100(SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
Attribut 1= 0x80000(SPELL_ATTR1_CANT_TARGET_SELF)
Attribut 2= 0x4(SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
rangeIndex= 6 (Vision Range 100 yards)
Effect1= 1 (SPELL_EFFECT_INSTAKILL)
EffectImplicitTargetA1= 25

28404:
Attribut 0= 0x100(SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
Attribut 1= 0
Attribut 2= 0x4(SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
rangeIndex= 7 (Ten yards 10 yards)
Effect1= 1 (SPELL_EFFECT_INSTAKILL)
EffectImplicitTargetA1= 22
EffectImplicitTargetB1= 7
EffectRadiusIndex1= 13 (EFFECT_RADIUS_10_YARDS)

This is gonna be hard one since there is so few documentation available for Spell.dbc :/

28404 looks a lot like the spell that will be used to kill the zombies. I'm stuck at determining what EffectImplicitTarget fields are used for.

**Comment by chaodhib** [comment]
I have been looking at the other spells that have the same EffectImplicitTarget as Spell 28404:
http://www.wowhead.com/spell=802/mutate-bug
http://www.wowhead.com/spell=5628/gnarlpine-vengeance
http://www.wowhead.com/spell=6636/wagon-explode

 and my current explaination for  22 and 7 is : affect ONE npc and it must be near the caster.

**Comment by Shauren** [comment]
TARGET_SRC_CASTER(22) - set spell destination coords to caster position
TARGET_UNIT_SRC_AREA_ENTRY(7) - select all units of given entry (conditions table - will select ANYTHING if no conditions exist) in area

**Comment by chaodhib** [comment]
Thanks Shauren! Do you happen to know the EffectImplicitTarget explaination for 25 too?

**Comment by ccrs** [comment]
@chaodhib i recommend you to search the application "SpellWork" in TC forum :)

**Comment by chaodhib** [comment]
@ccrs Awesome. Thanks! :)

**Comment by chaodhib** [comment]
Hey guys. So, I have been thinking about which one of the 2 spells we should use.

My current understanding of the 2 spells is as follow:
* 28239 is a simple insta kill spell. The caster needs to explicitly have a target prior to casting.
* 28404 is also an insta kill spell. Except that the target is automaticly found using one or more rows in the condition table of the database.

Let's put 28239 aside and go indepth with 28404:
Once the condition table has been properly updated, a script that make use of spell 28404  would be much cleaner (a simple DoCast(28404) call every 7 seconds* would do it). 

I'm facing 2 problems though:
* So far, I haven't found how I could restrict the number of implicit targets to 1 max (in the same way it is needed for http://www.wowhead.com/spell=802/mutate-bug). If this feature doesnt exist yet, I'm pretty sure it should be added to the core.
* Gluth briefly face the zombie and "charge" it before killing it (see https://www.youtube.com/watch?v=3BC9KpeN2UM and https://www.youtube.com/watch?v=avVjzbOrvZE). I dont see how I could get that behavior from a simple DoCast() call. Since the target of that spell is implicit, I wont have a reference to it in my script. So I cannot use 28404 and at the same time, script the change of position and orientation in the script outside of the DoCast() call.

Therefore, right now, I'm working on a script that uses 28239. I have a working version but it feels very overkill.. I'll release what I have after I polish it as much as I can.

Note * : by observing closely https://www.youtube.com/watch?v=3BC9KpeN2UM, I'm pretty sure a scan of Gluth's surroundings is done every 7 seconds. If at least one zombie is found, Gluth does his emote and he starts the short sequence of actions where he turns briefly toward a random zombie, makes an animation (stand on its hind legs, the same animation he makes when he cast the armor debuff on his primary target. meaning this animation is the animation he uses when he casts a spell), kill the zombie and turn back toward its initial target.

**Comment by chaodhib** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/pull/14865
