### ISSUE TITLE
[Item] Bandages extends combat time

### ISSUE THREAD

**Issue by Lbniese** [TrinityCore/TrinityCore#14804]
EDITED:

Hello,

Using this item in combat: http://www.wowhead.com/item=14530/heavy-runecloth-bandage
will extend the time one is combat. Usual combat timer is 6 seconds, but using bandage will extend the time which leads to combat not breaking after the intended 6 seconds.
Bug is easy to replicate, but not tested with the other bandages.

Thanks

**Comment by robinsch** [comment]
Can't confirm on dc13cf0. Working fine.

**Comment by Lbniese** [comment]
Updated the bug description to avoid misinterpretation.

**Comment by robinsch** [comment]
I still can't confirm, I attack an enemy player wait 3 seconds, casting Bandage and combat drops after 2 seconds into the channel.

**Comment by Lbniese** [comment]
Strange. Thanks for trying it - Must be a mistake on my side then.. Strange though.
