### ISSUE TITLE
[Quests] Wrong POI

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#14800]
* http://www.wowhead.com/quest=11319/seeds-of-the-blacksouled-keepers
* http://www.wowhead.com/quest=11314/the-fallen-sisters

Quests are showing wrong POI. For most quests it is the position of the quest giver instead of the quest objective.

**Comment by Killyana** [comment]
For 11319  the RequiredNpcOrGo1=24235 and the npc 24235 is spawned in this area.
Same thing for 11314 RequiredNpcOrGo1=24117 (the quest guiver)

**Comment by Killyana** [comment]
I'm not sure if we are allowed to modify this table.
``` sql
UPDATE `quest_poi_points` SET `X`=2397, `Y`=-4677 WHERE `questid`=11319 AND `id`=0;
UPDATE `quest_poi_points` SET `x`=2027, `y`=-4542 WHERE `questid`=11314 AND `id`=0;

**Comment by MitchesD** [comment]
it's 335 or 6.x? Also missing TDB and revision hash

**Comment by Aokromes** [comment]
Anyway, it looks to be blizzlike bug.
http://www.wowhead.com/quest=11314/the-fallen-sisters#comments:id=1312769
http://www.wowhead.com/quest=11319/seeds-of-the-blacksouled-keepers#comments:id=1049789

**Comment by MitchesD** [comment]
Still incomplete issue, closing, also as Aokromes said, it looks like blizzlike
