### ISSUE TITLE
[3.3.5] Quest 787: The New Horde - missing gossip

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14814]
TrinityCore rev. 562da2e8b2b0 2015-05-31 01:01:55 +0200 (3.3.5 branch) (Win64, Release)
DB: TDB335.58 + updates up to and including [[2015_05_31_00_world.sql]](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/updates/world/2015_05_31_00_world.sql)

As a new Death Knight entering Azeroth and Durotar, then delivering quest ID 787 [[The New Horde]](http://wotlk.openwow.com/quest=787)  to [[Gornek]](http://wotlk.openwow.com/npc=3143),  he is supposed to have the quest gossip "Thanks for the done work!" This is according to openwow.com, since there are no other web sources (and no videos) for 3.3.5 available for this material.

Currently, the gossip only contains the title
**The New Horde**
and text :
**Rewards**
You will receive:
Experience: 5

According to [[WowPedia]](http://wow.gamepedia.com/) and [[Quest: The New Horde]](http://wow.gamepedia.com/Quest:The_New_Horde) :
Completing this quest will allow one to receive another quest: H [1] [[Your Place In The World]](http://wow.gamepedia.com/Quest:Your_Place_In_The_World).

Currently, the other quests are available even without handing in quest 787, "The New Horde".

While this issue is small and cosmetic, it should be easy to fix by linking the right text in the DB and adding the right condition, I believe. I may go looking for the gossip in the DB at a later time.

**Comment by Killyana** [comment]
Your Place In The World is most likely the first quest / task a new player in Valley of Trials. In order to turn this in; just walk into the cave close by the quest giver; it should be within sight.
Please note that if you accept or complete any of the other quests, you are no longer able to pick up this quest. So if you're going here for the Darkspear Trolls or Orgrimmar reputation, complete this first or you lose out on 75 reputation!

Concerning the missing text:  "Thanks for the done work! " you can added:
``` sql
UPDATE `quest_template` SET `OfferRewardText`="Thanks for the done work!" WHERE `id`=787;

**Comment by tkrokli** [comment]
Thanks. The SQL is simple and to the point. I guess I should make a different issue (when this one is closed) about the 'fact'  that a Death Knight should not see the other quests until quest 787 is handed in.

After I had submitted my previous post, I started thinking that any conditions would belong to the other quests, not quest 787 (since the conditions would need to hide the quest from a DK with 787 incomplete).

I suppose I should create a different issue for the conditions of the other quests, based on a death knight's approach to Azeroth after leaving the Acherus for the first time. But that condition issue is maybe even more superficial and cosmetic than this. Don't know if it is worth even opening a new issue for it.

**Comment by Killyana** [comment]
There's no sense to block access to 787 for DK or for other races as this quest is made to lead the player to the Valley of Trials.

**Comment by tkrokli** [comment]
Very well, fair enough. I will leave that question as it is, since it has
no real meaning to hide the other quests in the Valley of Trials.

~/.

**Comment by tkrokli** [comment]
Testing the SQL now (though I have no doubt that it will work). Query result :
```sql
1 queries executed, 1 success, 0 errors, 0 warnings

Query: UPDATE `quest_template` SET `OfferRewardText`="Thanks for the done work!" WHERE `id`=787

1 row(s) affected

Execution Time : 0 sec
Transfer Time  : 0.001 sec
Total Time     : 0.001 sec
```
@Killyana, your script works as intended. The quest hand-in text looks good now. Write-up and close.
