### ISSUE TITLE
Will of the Emperor encounter information. Pandaria raid.

### ISSUE THREAD

**Issue by Mogushan-Vaults** [TrinityCore/TrinityCore#14818]
1)https://github.com/TrinityCore/TrinityCore/commit/b0c4268a6b0ed1fffeb51c7542c7991399b18284

2)Hello everyone. Encounter currently not scripted. Fully the information that I have.
http://wow.gamepedia.com/Will_of_the_Emperor
http://www.wowhead.com/zone=6125/mogushan-vaults
Intro dialogue start only if http://www.wowhead.com/npc=61131/mogushan-secret-keeper
Aggro (should If he is located right in Forge of the Endless). Not Repeat. Only first try.

3)That's how it is, too, have the Forge NPC. It may be need to check the area? Or guid script?
https://github.com/satiini/addons/blob/master/Addons/DBM-MogushanVaults/WillofEmperor.lua
Timers, id and misc information.

4)http://www.youtube.com/watch?v=3q4G522gOyQ#t=15
Red rune for activation (visual dummy aura)
I found spell which plays this effect.
http://www.wowhead.com/spell=127732/cosmetic-lightning-spell. You can play sound spell effect and be convinced of it.
That's all. Unfortunately I could not find the rest of the red beams which create spawn effect for the terracotta army.
Thanks advance.

**Comment by Shauren** [comment]
Useless. Sniffs give way more information anyway.

**Comment by Aokromes** [comment]
Nor to say duplicate of  #13179

**Comment by Mogushan-Vaults** [comment]
@Shauren, Is well, I understand you.
@Aokromes, Sorry, I used the search but did not find a similar issue specifically on the Will of the Emperor on Trinity Core issue.
I use search format = This repository.
