### ISSUE TITLE
How to fix Haste Rating error

### ISSUE THREAD

**Issue by xinnaxin** [TrinityCore/TrinityCore#14816]
hello i need help ,i have Trinitycore but it source have Haste Rating error.How to fix Haste Rating error.
http://prntscr.com/6pqmyo

**Comment by DDuarte** [comment]
This is not a bug report.

**Comment by tkrokli** [comment]
Ask for help in the forum: http://www.trinitycore.org/f/ (This is not a forum, this is for source code errors.)
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
