### ISSUE TITLE
[3.3.5a] SkillRaceEntryInfo doesn't take -1 into consideration.

### ISSUE THREAD

**Issue by Ascathor** [TrinityCore/TrinityCore#14827]
Heya.

Branch: 3.3.5a (Seems irrelevant, though. Probably an issue with every branch.)
Hash: 2d349da

GetSkillRaceClassInfo() does not take -1 as ClassMask or RaceMask into consideration. Just like 2147483648 takes every possible race into consideration, -1 does just that, too. However, it's not compared in any function related to this. 

-1 is used in a few SkillLines as far as I've seen, so it might make sense to add support to -1.

**Comment by Shauren** [comment]
It doesn't have to explicitly check it, working as intended.
