### ISSUE TITLE
[3.3.5] Freez core, VmapManager2: could not load

### ISSUE THREAD

**Issue by diavolb** [TrinityCore/TrinityCore#14828]
ee0237725298e0a46a5e4bd9d39cb8e76f6ffa9e
Version Client: 3.3.5a

No error is logged at all, comes only a solid spam "VmapManager2: could not load", it occurs after some time, 100+ online server.

But one bright day caught the crash associated with VMAPS.
I tried removing the card again, does not help.
Now I try to build from the latest revision.

http://pastebin.com/vigrt3nf

VmapManager2: could not load
After that spam in the list of who is in the location written by unknown and new players generally can not go, says the connection is established.

**Comment by Aokromes** [comment]
Plz, compile core on debug mode.

**Comment by diavolb** [comment]
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
DoZoneInCombat called for creature that has empty threat list (creature entry = 34796)
VMapManager2: could not load './vmaps/Darkironforge.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockirondoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockirondoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockcelldoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockhugedoorsmechanismlock.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockhugedoorsportcullis.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockhugedoors.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockhugedoorsopendoorcollision.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultspecialdoor.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultsecretdoor.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockvaultdepositdoor02.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockirondoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockirondoor01.m2.vmo'
VMapManager2: could not load './vmaps/Blackrockirondoor01.m2.vmo'
DoZoneInCombat called for creature that has empty threat list (creature entry = 34799)
VMapManager2: could not load './vmaps/Titanchest.m2.vmo'
Spell::EffectTriggerSpell spell 47568 tried to trigger unknown spell 53258
Spell::EffectTriggerSpell spell 47568 tried to trigger unknown spell 53258
Could not load MMAP name:Черный храм, id:564, x:31, y:28 (mmap rep.: x:31, y:28)


debug shows nothing, there was no more drops, but is literally 10-30 minutes and begins flooding

**Comment by jackpoz** [comment]
do you have any custom change ? are those files actually there ?
check if worldserver (or the whole system) reached the limit of file descriptors opened

**Comment by diavolb** [comment]
Eluna, CrossfactionBG, Transmografictation

**Comment by Frytiks** [comment]
I doesn't have this problem, but i had it, have you running 2 realms on same data folder ?

**Comment by diavolb** [comment]
no, i nave 1 realm

**Comment by diavolb** [comment]
<img>https://pp.vk.me/c621521/v621521934/ba95/afxRKte943E.jpg</img>

**Comment by diavolb** [comment]
http://pastebin.com/nHwB3z2Z

**Comment by Aokromes** [comment]
useless log unless it's a crash.

**Comment by jackpoz** [comment]
"World settings reload fail: cannot open file (/home/335/x300/etc/worldserver.conf)." sounds bad and totally unrelated to vmaps.
I also suggested at https://github.com/TrinityCore/TrinityCore/issues/14828#issuecomment-112159549
>check if worldserver (or the whole system) reached the limit of file descriptors opened

but I got no reply so far.

**Comment by lainimer** [comment]
cat /proc/sys/fs/file-nr
2240    0       65536
no limit to descriptors

**Comment by diavolb** [comment]
im used no limit to descriptors

**Comment by jackpoz** [comment]
Which cards ?

**Comment by diavolb** [comment]
vmaps
I removed them from the last version 3.3.5a branch

**Comment by diavolb** [comment]
https://github.com/TrinityCore/TrinityCore/commit/bb046ce4ed59708fa002f0b7399c1412e6b1de42

**Comment by Naios** [comment]
It has nothing to do with commit bb046ce

**Comment by jackpoz** [comment]
@diavolb please explain yourself in understandable english. Also please check the file descriptor count used by worldserver or by the whole OS, I see you wrote "Im used no limit to descriptors" but that doesn't really tell anything if it reached the limit or not

**Comment by Frytiks** [comment]
@jackpoz https://github.com/TrinityCore/TrinityCore/commit/bb046ce4ed59708fa002f0b7399c1412e6b1de42#commitcomment-8129817

**Comment by diavolb** [comment]
Im used: Ubuntu 14.10 Utopic Unicorn

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by diavolb** [comment]
More is not repeated

**Comment by SQLfix** [comment]
@diavolb  how fix this problem ?
https://github.com/TrinityCore/TrinityCore/issues/17273
