### ISSUE TITLE
[6.x][Crash] Server crashes when entering black temple raid

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#14826]
rev. eee0eebf5141b16ea2c442b1ea7176abd7600bb8
http://pastebin.com/DLZ67p95

Always happens when entering bt, even with gm flag on or with a raid group. It doesn't happen with every raid, only seen with bt

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14366
