### ISSUE TITLE
The Nexus Client Crash

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14823]
Its the weirdest bug ive ever seen O.o

Just on approach to "The Rift" area of "The Nexus" client suddenly freezes and shuts down.

No custom code or data base changes.

562da2e8b2b0814b47027dfd1af2dd0d98378f88

**Comment by DDuarte** [comment]
Post the client's crashlog if you get one. It might also help if you enable packet logging in worldserver.pkt (look for World.pkt) and post the file here.

**Comment by ccrs** [comment]
No "wowerror" is displayed.
Image freezes and nothing can be done till the client closes showing the tipical windows error on applications (Application X is not responding)

**Comment by ccrs** [comment]
....

After rebuilding and recreate world database this bug suddenly disappeared D:
