### ISSUE TITLE
Reclusive Rune Master

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#14829]
Something in SAI script seems to be broken
NPC stands and the running back part isnt triggerd, and player doesnt get quest credit

Quest : Reclusive Runemaster (http://www.wowhead.com/quest=12150/reclusive-runemaster)
Quest ID : 12150
Quest NPC : Aurastrasza (http://www.wowhead.com/npc=26983/aurastrasza)
NPC ID : 26983
Target NPC : Dregmar Runebrand (http://www.wowhead.com/npc=27003/dregmar-runebrand)
Target NPC ID: 27003

198ffba5ee3b64852b3b090ebdeebd87494cc9f6

**Comment by Rushor** [comment]
yep all the actionlistpart and the texts are triggered, however the player doesn't get the killcredit and the npc does not despawn

**Comment by Killyana** [comment]
The evade action broke the action_list as usual.

**Comment by ccrs** [comment]
any way to do the same script without it?

**Comment by Killyana** [comment]
The problem is if we use a delay on the action list after the evade, the script will stuck, I will try to replace the evade with something else.

**Comment by ccrs** [comment]
replace evade with something like passive state?

**Comment by Killyana** [comment]
No, changing the react state will not stop the combat.

**Comment by ccrs** [comment]
ummm, changing it to passive + aura making it unable to be damaged + no combat move will do the trick, wont it?

plus being out of combat doesnt really matter as creature despawns after several seconds.

**Comment by Killyana** [comment]
This will fix the issue and stop the combat movements: (just need to check the respawn)
``` sql
UPDATE smart_scripts SET `event_flags`=1 WHERE `entryorguid`=27003 AND `id`=2;
UPDATE smart_scripts SET `event_param1`=5000, `event_param2`=5000 WHERE `entryorguid`=2700300 AND `id` IN (7, 6);
UPDATE smart_scripts SET `action_type`=20, `Comment`="Dregmar Runebrand - Stop Attack" WHERE `entryorguid`=2700300 AND `id`=1;

**Comment by ccrs** [comment]
force despawn will allow it to respawn? just asking, good job :)

**Comment by Killyana** [comment]
Yes he will take 10 min to respawn.

**Comment by ShinDarth** [comment]
@Killyana shouldn't you pass also the source_type when you UPDATE/DELETE something from smart_scripts table? Because there could be different entities having the same entryorguid but different source_type.

The code will be:

```sql
UPDATE `smart_scripts` SET `event_flags`= 1 WHERE `entryorguid` = 27003 AND `source_type` = 0 AND `id` = 2;
UPDATE `smart_scripts` SET `event_param1`= 5000, `event_param2`=5000 WHERE `entryorguid` = 2700300 AND `source_type` = 9 AND `id` IN (7, 6);
UPDATE `smart_scripts` SET `action_type`= 20, `Comment`="Dregmar Runebrand - Stop Attack" WHERE `entryorguid`=2700300 AND `source_type` = 9 AND `id` = 1;
UPDATE `smart_scripts` SET `action_type`= 20, `action_param1`= 1, `Comment`='Dregmar Runebrand - Start Attack' WHERE `entryorguid`=2700300 AND `source_type` = 9 AND `id` = 8;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 2700300 AND `source_type` = 9 AND `id` IN (9, 10);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(2700300,9,9,0,0,0,100,0,0,0,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Dregmar Runebrand - enable movement'),
(2700300,9,10,0,0,0,100,0,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Dregmar Runebrand - force despawn');
```

**Comment by Killyana** [comment]
Yes I forget the source type.

**Comment by tkrokli** [comment]
@ccrs : add the following to your original post:

Quest : Reclusive Runemaster (http://www.wowhead.com/quest=12150/reclusive-runemaster)
Quest ID : 12150
Quest NPC : Aurastrasza (http://www.wowhead.com/npc=26983/aurastrasza)
NPC ID : 26983
Target NPC : Dregmar Runebrand (http://www.wowhead.com/npc=27003/dregmar-runebrand)
Target NPC ID: 27003

(I can delete this post when you have added this info.)
