### ISSUE TITLE
[3.3.5] Glyphs and Talents improving ability's

### ISSUE THREAD

**Issue by vengepk** [TrinityCore/TrinityCore#14822]
When improving spells with tallens such as Water Shield They do not display on the player properly
Every spell that is improved by tallens is like this.

**Comment by vengepk** [comment]
The spell on the action bar show correct value but the buff itself shows incorrect value

**Comment by tkrokli** [comment]
Please read: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/CONTRIBUTING.md

**Comment by Nyeriah** [comment]
This is invalid - the buffs never scaled with external changes at WotLK, the texts were made with the base values and that was it.
