### ISSUE TITLE
[3.3.5]Warrior Mmaps

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14836]
Warriors use spell a jerk in BG varsong and arenas if the target a little bit closer to the texture of it goes to the texture

Mmaps settings enabled

3600751
TDB335.58

**Comment by Aokromes** [comment]
1st lawn, update your core and db before reporting bugs.

**Comment by Spectrance** [comment]
updated kernel but all exactly

I saw a server that uses an older version but they work
in the textures will not come

**Comment by Frytiks** [comment]
Can confirm it after trista patch of raycast.

**Comment by Spectrance** [comment]
indicate if this is not difficult

**Comment by lainimer** [comment]
Confirm bg textures bad

**Comment by Spectrance** [comment]
they are good, they work well but when jumping on some players or some arenas so happens that I was told to install the patch on the mmaps but he's too old to upgrade  3600751

**Comment by Rushor** [comment]
no spellids, no screenshots, no video with the wrong behaviour - this issue is a whole mess.

Pls add the the needed information and we will reopen it :)

**Comment by Keader** [comment]
Look this #11526
