### ISSUE TITLE
[6x] Instances/Raids/Dungeons still bugged.

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#14831]
**What steps will reproduce the problem?**
1. Teleport to a raid/instance/dungeon by .go xyz (I.E. .go xyz 0 0 0 1136 for Siege of Orgrimmar)
 
**What is the expected output? What do you see instead?**
 You're supposed to load in where you teleported to, instead this happens:
http://i.imgur.com/42C5oiN.jpg
 
**What version of the core and database are you using? On what operating system?**
Core Rev. https://github.com/TrinityCore/TrinityCore/commit/fb4a9823c41b31158f6b5d68fc2ffc1608051984
DB Rev. https://github.com/TrinityCore/TrinityCore/commit/e43a6b373a258eb24fc8ea5d5a86c9ad44279cd0 (last commit to 'sql')
Windows 7 Ultimate
 
**Please provide any additional information below.**
Crashdump: http://paste2.org/KenmUbW9
Note: This issue still persists after https://github.com/TrinityCore/TrinityCore/commit/b15a0b96bf05e8d2ccf6cf8f9c09a6e58dcf5b0a which closed #14366 containing about the same crashlog as mine now.

**Comment by DJScias** [comment]
Extra: After setting up a breakpoint per @DDuarte's request, I managed to get this info:
```
MapDifficultyEntry const* GetMapDifficultyData(uint32 mapId, Difficulty difficulty)
{
    auto itr = sMapDifficultyMap.find(mapId);
    if (itr == sMapDifficultyMap.end())
        return nullptr;
 
    auto diffItr = itr->second.find(difficulty);
    if (diffItr == itr->second.end())
        return nullptr;
 
    return diffItr->second;
}
```
The second return nullptr (diffItr) is called.

**Comment by Shauren** [comment]
Nope. Working as intended.
