### ISSUE TITLE
[3.3.5] [DB/Creature] Duplicates of Captain Ellis and Juniper in Howling Fjords

### ISSUE THREAD

**Issue by czw** [TrinityCore/TrinityCore#14834]
There are two copies of Juniper and Captain Ellis present, both of them standing still or floating midair.
Juniper DB GUID: 150187
Captain Ellis DB GUID: 152167

**Comment by Killyana** [comment]
Confirm on rev. 35f2f5530abc
``` sql
DELETE FROM `creature` WHERE `guid` IN (150187, 152167);

**Comment by czw** [comment]
Sorry about forgetting to specify revision.

**Comment by Aokromes** [comment]
I prefer 203125 and 152167

**Comment by Killyana** [comment]
203125 have waypoints.
