### ISSUE TITLE
[3.3.5a] Worldserver Segmentation Fault

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14835]
Hello. I need to turn on the debug mode in the worldserver (to store all the logs that are needed to discover the issue). The server crashes after these lines: http://pastebin.com/C0gQGFzF

I know that I need to turn on the debug mode, but i have no idea which lines should I apply to the logger.

TDB 335.58 #14605
Here is the config
 http://pastebin.com/pXwSpXWV

Aokromes - Please provide me some info, how to report issues (what should I type here) instead of closing everything.

Thank you.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/new

**Comment by selenir** [comment]
So I have to provide the revision from the log file/console when the server is starting, right?
And what happens, if I have Transmog Script implemented (this from Rochet)? Will my issue still be valid?

**Comment by DDuarte** [comment]
See http://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/

We need the crashlog. If you are on Linux you can use GDB.

**Comment by selenir** [comment]
Do i need to compile the server with a debug mode or just need to apply GDB to the app?

**Comment by selenir** [comment]
http://pastebin.com/nys53mGi this is all I have...

**Comment by Aokromes** [comment]
You need to compile on debug mode AND run gdb commands when it crashes.

**Comment by selenir** [comment]
Would you tell me how to compile this in debug mode? Tried -DDEBUG=1, but I read somewhere, that i need to change some cmake files (they're overwriting parameters).

**Comment by tkrokli** [comment]
http://collab.kpsn.org/display/tc/Core+Installation#linux
**Configuring for compiling**
`-DWITH_COREDEBUG` <==> Include additional debug-code in core

*Things to notice :*
-DWITH_COREDEBUG=0 **not required, as its default is : 0**

**Comment by selenir** [comment]
Tried this, but when configuration is done, it says that Trinitycore buildtype: Release.

**Comment by tkrokli** [comment]
Did you also try -DWITH_COREDEBUG=1 in cmake and then compile?

**Comment by Aokromes** [comment]
declare -x CFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

declare -x CXXFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

cmake ../ -DCMAKE_INSTALL_PREFIX=/change/path/to/trinity -DCMAKE_BUILD_TYPE=None

**Comment by selenir** [comment]
Thanks Aokromes. Worked. Server is compiling right now. When the crash comes, I post here. 
One more question. I have ~600 players on my server. If it is running under the debug mode, will it lag?

**Comment by Frytiks** [comment]
It will be slowly.

**Comment by Frytiks** [comment]
600 players on debug is not Good idea

**Comment by selenir** [comment]
Hello! http://pastebin.com/2X9XNRYu

I know, that I should put it into some log file, but no idea, what does 'gdb trinity-core --batch -x /path/to/gdb-commands' << path to gdbcommands mean.

So I did all the commands 
shell echo -e "\nCRASH ON" `date`
info program
shell echo -e "\nBACKTRACE\n"
bt
shell echo -e "\nBACKTRACE FULL\n"
bt full
shell echo -e "\nTHREADS\n"
info threads
shell echo -e "\nTHREADS BACKTRACE\n"
thread apply all bt full

After the crash and copied the console part by part.

**Comment by Aokromes** [comment]
It's not debug mode crashlog.

**Comment by selenir** [comment]
I cmaked the server with commands that you've mentioned above. What should i do next? Compile it with any parameter? Run with parameter? Could you explain? Thank you :) I thought, that this isn't debug mode, because there were no laggs at all.

**Comment by Aokromes** [comment]
No, that must be None, you very likely you forgot make install.

**Comment by selenir** [comment]
No no, I am sure that i did make install.
So the sequence:
Above commands > make > make install > run normally under gdb > debug commands from http://rgtc.wikia.com/wiki/How-to:Advanced:GDB right?

**Comment by selenir** [comment]
Should I run the server with any additional parameter? Or just GDB > run? (after make install)

**Comment by selenir** [comment]
http://pastebin.com/eH6j09jc << I think that this isn't normal. It says something about picking up the loot and it is impossible. I'm 90% sure that one of the spells crashes the server.

**Comment by selenir** [comment]
Okay, here comes a strange thing.
When server was in a normal mode (release) items like: http://www.wowhead.com/item=54218/landros-gift-box
or any other item with pickable loot was working fine.

When we opened the debug mode, these boxes were empty.
Now, crash happened, we've launched the release mode and items are back again.

Is it normal?

**Comment by Rushor** [comment]
this issue is still present @selenir?

**Comment by Rushor** [comment]
no answer after 3 days - closing
