### ISSUE TITLE
[3.3.5][6.x][DB/Creature] Skorn - Emotes

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14839]
rev https://github.com/TrinityCore/TrinityCore/commit/ed2607f12827bc1f4e764f3988093e20aa303db4

affected npcs:
17:48:39]Entry: 23663.
17:48:50]Entry: 23665.
[17:49:08]Entry: 23664.
[17:49:58]Entry: 23666.

These creatures which have the attackstate-emote should randamly cast one of the following spells at each other every 2 seconds:

(Cast) SpellID: 42901 (42901)
(Cast) SpellID: 42904 (42904)
(Cast) SpellID: 42889 (42889)
(Cast) SpellID: 42895 (42895)
(Cast) SpellID: 42880 (42880)
(Cast) SpellID: 42906 (42906)
(Cast) SpellID: 42902 (42902)
(Cast) SpellID: 42903 (42903)
(Cast) SpellID: 42907 (42907)
##

**Comment by tkrokli** [comment]
http://www.wowhead.com/zone=495/howling-fjord
***
http://www.wowhead.com/npc=23663/winterskorn-shield-maiden
http://www.wowhead.com/npc=23664/winterskorn-warrior
http://www.wowhead.com/npc=23665/winterskorn-raider
http://www.wowhead.com/npc=23666/winterskorn-berserker
***
http://www.wowhead.com/spell=42880/cosmetic-combat-attack-1h
http://www.wowhead.com/spell=42889/cosmetic-combat-attack-2h
http://www.wowhead.com/spell=42895/cosmetic-combat-knockdown-foe
http://www.wowhead.com/spell=42901/cosmetic-combat-whirlwind
http://www.wowhead.com/spell=42902/cosmetic-combat-attack-offhand
http://www.wowhead.com/spell=42903/cosmetic-combat-special-attack-1h
http://www.wowhead.com/spell=42904/cosmetic-combat-special-attack-2h-whirlwind-sfx
http://www.wowhead.com/spell=42906/cosmetic-combat-shield-block
http://www.wowhead.com/spell=42907/cosmetic-combat-shield-bash
