### ISSUE TITLE
[3.3.5] Thrallmar grunt in Hellfire Penisula

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#14844]
They didn't attack alliance players
http://www.wowhead.com/npc=16580/thrallmar-grunt

it seems there a lot of problems like this one

DB 335.58
rev 0148832 2015-05-21

**Comment by ariel-** [comment]
Try after 125d839a1878d3d3d0cbc193298f385560e268c9

**Comment by Killyana** [comment]
Wrong faction:
``` sql
Update `creature_template` SET `faction`=1669 WHERE `entry`=16580;

**Comment by dr-j** [comment]
there are a number of guards all over outlands like this they used to be hostile buy in recent months are neutral to opposite faction.

**Comment by Kinzcool** [comment]
The correct factions are 1668 for the first query, 1671 for 16831 and 1666 stays the same for 16842.

**Comment by Killyana** [comment]
Checked and updated.
