### ISSUE TITLE
6.x - access_requirement

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14846]
Hi! 
The access_requirement doesn't works. I set minlevel to 85 and I can enter to instance at lvl 1 too.

rev : https://github.com/TrinityCore/TrinityCore/commit/c0b4c7f46198a23379456ce014f3b63f9baf3f3e

**Comment by Vincent-Michael** [comment]
wrong difficulty?

**Comment by Atis6** [comment]
For example Bloodmaul Slag Mines:
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES ('1175', '1', '100', '100', '0', '0', '0', '0', '0', NULL, 'Bloodmaul Slag Mines');

**Comment by Atis6** [comment]
And for example Bloodmaul Slag Mines Normal : 
INSERT INTO `server_world`.`access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES ('1175', '0', '90', '100', '0', '0', '0', '0', '0', NULL, 'Bloodmaul Slag Mines');


And you can enter at lvl 1.

**Comment by Vincent-Michael** [comment]
normal is difficulty = 1 and heroic = 2

**Comment by Atis6** [comment]
I've updated to (Bloodmaul Normal) -->
UPDATE `access_requirement` SET `difficulty`='1' WHERE (`mapId`='1175') AND (`difficulty`='0')

I've restarted the server, and reloaded the table ... I set myself to lvl 20, logged out --> logged in ... and still i can enter to instance at lvl 20.

**Comment by MitchesD** [comment]
Try to disable GM mode

**Comment by Atis6** [comment]
I've tryed with player account, but nothing ...
Is working for you?

**Comment by MitchesD** [comment]
Just tried to enter with level 5 char inside Deadmines, ZulFarak and some others, and I was able, so something is really wrong..

**Comment by Atis6** [comment]
You haven't get a server DC when you tried to enter to the instance what was bigger level entrance access then you ?

**Comment by MitchesD** [comment]
no, I simply could enter and play
