### ISSUE TITLE
[Crash] _M_rehash_aux

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#14841]
I have the following crash:

http://pastebin.com/4qnjUWvJ

62ebd002d990c24be989c33aa60719ed5a9ba761

**Comment by jackpoz** [comment]
the crash log contains a SAI script
>WorldObject::SummonCreature (this=0x7fff88bfb000, id=26583, x=4690,05127, y=-2045,84875, z=194,348404

**Comment by Killyana** [comment]
Cannot reproduce, also the SAI is clean:
``` sql
SELECT * FROM smart_scripts WHERE entryorguid IN (26583, 2658200, 2658201);

**Comment by jackpoz** [comment]
```
SELECT action_param1 FROM `world`.`smart_scripts` WHERE entryorguid = '11660200'
```
returns 26583 and that's the npc being spawned.

```
SELECT * FROM `world`.`smart_scripts` WHERE entryorguid = '26583'
```
returns 4 rows to me with comment "Horrified Drakkari Shaman", was it modified recently ?

**Comment by Killyana** [comment]
Yes I have it with 11660201.

**Comment by jackpoz** [comment]
this is caused by SMART_ACTION_TALK modifying singleton data in a thread-unsafe environment "Map::Update()"

**Comment by jackpoz** [comment]
@Pirricli what's your worldserver.conf "MapUpdate.Threads" setting ?

**Comment by Pirricli** [comment]
#    MapUpdate.Threads
#        Description: Number of threads to update maps.
#        Default:     1

MapUpdate.Threads = 1

**Comment by jackpoz** [comment]
Let's just pretend https://github.com/TrinityCore/TrinityCore/commit/d123c811623fcedcf125f56101b6aea773f460e0 fixed the crash
