### ISSUE TITLE
[6.x] Dungeon Finder

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14858]
Hi!
The Dungeon Finder feature didn't works. On selection you can select only 'Specific Dungeons' and if you chhose one --> Find Group, nothing happens. You cannot choose 'Random Dungeon'.
Rev: https://github.com/TrinityCore/TrinityCore/commit/7c51b227a454845f58025650924b283c2b0f2742
##

**Comment by digz6666** [comment]
This feature is work in progress in https://github.com/TrinityCore/TrinityCore/pull/15107

**Comment by Zerixx** [comment]
Getting close to having the dungeon finder working. Once I get it working, I'll make sure the code isn't shitty. Thanks for the patience!

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
