### ISSUE TITLE
[6.x] new locales structure missing 

### ISSUE THREAD

**Issue by VirusEntertainment** [TrinityCore/TrinityCore#14850]
New locales structure missing (creature, creature_text, gameobject, gossip_menu_option, achievement_reward).
Actual structure not working.

Revision (core/db): https://github.com/TrinityCore/TrinityCore/commit/70fe4e57a0b6c97982fbedc521694d5a37fafae5

Links: no need of link, you can test this directly in game.

**Comment by VirusEntertainment** [comment]
why invalid? Try to put a locale that is not english, ingame you will see the NPC named in english.

**Comment by MitchesD** [comment]
It's invalid because you don't follow TC issue rules. Read this http://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by VirusEntertainment** [comment]
edited.

**Comment by Killyana** [comment]
Same issue: https://github.com/TrinityCore/TrinityCore/issues/14575
