### ISSUE TITLE
[3.3.5] Riding learn skill effect bug

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#14851]
This bug _may_ be impossible to reproduce on normal situation and it only affects riding.
In general you would need to get a riding skill and then any spell that has learn skill effect for any higher riding skill.

Learning http://wotlk.openwow.com/spell=33388 and then http://wotlk.openwow.com/spell=52382 causes a bug where your riding is at 75 and max riding is at 150. Cause of this you cant learn any riding above that. Also you can not unlearn http://wotlk.openwow.com/spell=33391 after getting bugged even by unlearning the whole skill - learning it again says you already have it.

```
.learn 33388
.cast 52382
```

The reason it buggs is that the learn skill effect uses character's pure skill value as the current skill value for SetSkill function.
However on LearnSpell functions there is a special step that uses SpellMgr::GetSpellLearnSkill to correct the skill value for riding to be 75*skillstep.

https://github.com/TrinityCore/TrinityCore/commit/239f0b4ad0e83da9d31c8031aa2e50c294bfc913
TDB 58
3.3.5, may affect other branches
##

**Comment by Rochet2** [comment]
Someone was able to reproduce this somehow in game on MaNGOS classic (1.12.1)
Same issue is likely reproducible also somewhere on TC - but dont know where.

**Comment by tkrokli** [comment]
As long as you are talking about http://www.wowhead.com/spell=52382/summon-deathcharger , it looks like the problem would be limited to the death knight class and the quest http://www.wowhead.com/quest=12687/into-the-realm-of-shadows (at least that is what it looks like to me). I have not tested your theory above, but I do not remember having trouble learning further riding skills at higher levels.

**Comment by Rochet2** [comment]
This issue has been fixed.
I believe it was fixed in https://github.com/TrinityCore/TrinityCore/commit/4b6351e6a5a#diff-5589ee47b3a7ad220cff105a8fe7eac3R3451
