### ISSUE TITLE
[6.x] Loot specialization and PvP option

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14855]
Hi! 
You can't change the Loot Specialization option, and the PvP option (Enable or Disable)

Rev : https://github.com/TrinityCore/TrinityCore/commit/ac53442e4f65bdba7a4341265d5c352d120ca057

**Comment by Aokromes** [comment]
works on f6637439f484dacc9c8deb3c4dd07832146ff6f6
