### ISSUE TITLE
[6.x] DB/Creature: Queststarter + Questender - Pandaria - WoD

### ISSUE THREAD

**Issue by ElleEntertainment** [TrinityCore/TrinityCore#14854]
Here all the updated creature queststarter/ender sniffed from wowhead with a for loop from 1 to max(entry) taken from TC creature_template table. 

Creature_QuestStarter not present in the DB:
http://www.mediafire.com/view/7sgh2l3ggj66536/creature_queststarter2.sql

Creature_QuestEnder not present in the DB:
http://www.mediafire.com/view/09iirwindtbocku/creature_questender2.sql

Creature_questStarter and Creature_QuestEnder from scratch (all 6.1.2 values, no deprecated values):
http://www.mediafire.com/view/2wsqgjfcwo25gto/table_ender.sql

http://www.mediafire.com/view/1577h0n8z7wruc1/table_starter.sql

**Comment by ShinDarth** [comment]
Ciao, thanks for sharing them.

You used  mysql dump, is it _ALL_ datas or just new? You should provide just the new data using DELETE/INSERT format instead of create/drop table.

**Comment by VirusEntertainment** [comment]
Ciao Shin!! 
It is ALL data. I don't know what is the new data, because i extracted everything from scratch because maybe old npc were updated with new quest assignment, but i could use the DELETE/INSERT format anyway.. is that ok?

**Comment by VirusEntertainment** [comment]
edit: i'm working on adding only data that were not existing in the DB

**Comment by ShinDarth** [comment]
Yes we need the new data only in order to check and import the fix

**Comment by VirusEntertainment** [comment]
http://www.mediafire.com/view/cap63jq831dadgg/creature_questender.sql

http://www.mediafire.com/view/sl6k7gg58h7rx6d/creature_queststarter.sql

DONE! These quest were not assigned.

**Comment by VirusEntertainment** [comment]
http://www.mediafire.com/view/7sgh2l3ggj66536/creature_queststarter2.sql

http://www.mediafire.com/view/09iirwindtbocku/creature_questender2.sql

Done!! These quest were not in the db

**Comment by soulfrost** [comment]
quest starter/ender tables should be truncated, cos some quests was deprecated since 6.0.1

**Comment by VirusEntertainment** [comment]
I have that table too, some1 from TC should tell me what i should give to them

**Comment by VirusEntertainment** [comment]
updated with links that fits the request of @soulfrost

**Comment by soulfrost** [comment]
i think that u can also parse GameObject quest starters/enders ;)

**Comment by MitchesD** [comment]
@soulfrost No, truncate is bad idea since we don't know how many quests can get broken due to missing data/incorrect data etc. Well we can add missing data, but dont touch old ones, if there are any quests which should not be acceptable remove them by fixes but not by this way.

**Comment by soulfrost** [comment]
just diff data which i'll be removed from this table and recheck data from wowhead / retail - u'll see that this quests deprecated

**Comment by gegge** [comment]
So this can be merged?

**Comment by VirusEntertainment** [comment]
Up

**Comment by tkrokli** [comment]
Here, I polished the files for you by removing 3946 tabs from each file and put ` (back ticks) around the word **quest** in the first line, in addition to uppercase in => **IN** as a keyword (codestyle polishing).
- https://gist.github.com/tkrokli/54f4bbd33c71239df623#file-creature_queststarter2-sql
- https://gist.github.com/tkrokli/d084015f02de74eba993#file-creature_questender2-sql

**Comment by VirusEntertainment** [comment]
Edited ALL links with @tkrokli suggestions.

**Comment by Rushor** [comment]
related:
https://github.com/TrinityCore/TrinityCore/issues/15477
https://github.com/TrinityCore/TrinityCore/issues/15474
https://github.com/TrinityCore/TrinityCore/issues/15419
https://github.com/TrinityCore/TrinityCore/issues/15410
https://github.com/TrinityCore/TrinityCore/issues/15411

**Comment by tkrokli** [comment]
@VirusEntertainment : you might want to talk with @Helias about how to run your NPC IDs through https://github.com/Helias/WoWHead-Quest-Parser to get your quests sorted and commented like Helias' issues linked in Rushor's comment above this one. I tried to use the Quest Parser, but I got only error messages. Maybe Helias could tell you how to do it in the least time-consuming way he knows?

**Comment by Helias** [comment]
It's really easy to use, but you have to install php5-curl and Apache.

https://www.youtube.com/watch?v=U7nCrJo9XEM

To run this on your PC you have to:
- Install Apache (if you installed WAMP, XAMP or EasyPHP you should already have it)
- Download the project, put it on localhost (www directory), verify that php5-curl is installed (if you install it now, restart apache) and verify that Apache is active (is you can't visit localhost you should activate apache).

If you have linux, probably, you already know how to install apache and php5-curl :P
(Online there are a lot of guide to install apache and php5-curl)

If you already installed it, go to http://localhost then go to the project and use it as the video show.

**Comment by Aokromes** [comment]
Can you update this to only the missing ones and the ones not on Helias' tickets?

**Comment by Aokromes** [comment]
near 3 months without answer, closing, if some data is still missing on Helias' tickets open a new ticket with it.
