### ISSUE TITLE
[6.x] Dressing Room

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14856]
Hi!
The Dressing Room didn't works.

Rev: https://github.com/TrinityCore/TrinityCore/commit/cb854a2b7bb7bd96cf9c4d1daf3789f797bf4db8

**Comment by MitchesD** [comment]
What exactly do you mean with Dressing room? Describe it more, I am not sure which feature do you mean

**Comment by Atis6** [comment]
Where you can view items on your character.
http://imgur.com/0BR5Wem

**Comment by Shauren** [comment]
works for me

**Comment by MitchesD** [comment]
as well works for me

**Comment by Atis6** [comment]
For any item display ?
