### ISSUE TITLE
[3.3.5] DB/Misc: Megzeg Nukklebust wrong npcflag value

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14863]
TrinityCore rev. cac4f95 2015-06-06 16:08:25 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.58 + updates up to and including `2015_06_08_00_world.sql`

Megzeg Nukklebust <Mercenary> (http://www.wowhead.com/npc=21283/megzeg-nukklebust)

![Megzeg Nukklebust](http://wow.zamimg.com/uploads/screenshots/normal/32351.jpg "Megzeg Nukklebust")

NPC ID: 21283
npcflag = 4099 (this is wrong, the NPC is not a repair NPC, he is only a quest giver with extra gossip)

Solution: remove flag 12 (4096) from the npcflag value and make him a quest giver with gossip:
```sql
UPDATE `creature_template` SET `npcflag` = npcflag&~4096 WHERE `entry`= 21283;

**Comment by Kittnz** [comment]
need to check sniffs for that.

**Comment by tkrokli** [comment]
> need to check sniffs for that.

Yes, you are right about that, I only got info from various sites like wowpedia, wowwiki, wowhead and openwow. I find it really odd, though, that this NPC has got a repair flag when he does not offer any repair function in the UI, as well as him not being a vendor. Can anyone check sniffs for me?

**Comment by Kittnz** [comment]
Yeah i didn't have time, did it fix your problem?

**Comment by tkrokli** [comment]
Well, we are still discussing this in #trinity (albeit a little awkward). The SQL fix in the main post fixes this issue, but I am still uncertain if @dr-j has given me a factual answer or not.

**Comment by dr-j** [comment]
(21283, 0, 65, 65, 1729, 3, 1, 1.142857, 2000, 2000, 1, 32768, 2048, 0, 0, 1), -- 21283

Npcflags=3

**Comment by dr-j** [comment]
also as previously said bytes2 in creature_addon_template seems wrong for this npc on tc its 4097 in sniff bytes2 is 257

**Comment by tkrokli** [comment]
:clap: Thanks a lot for the update, glad to have that info sorted out. :+1: I suppose I should add a query line for the table `creature_template_addon` too ("creature_addon_template" does not exist), if the sniffs are correct and the TC source is not. So here is a new suggestion for the SQL Query solution:
```sql
-- Set correct npcflag for NPC ID 21283, Megzeg Nukklebust
-- He is neither a vendor nor repair NPC
UPDATE `creature_template` SET `npcflag` = 3 WHERE `entry`= 21283;
UPDATE `creature_template_addon` SET `bytes2` = 257 WHERE `entry`= 21283;
```
Feel free to comment on this SQL and tell me if it needs more changes.

I have tried looking up what the values in `bytes2` or `UNIT_FIELD_BYTES_2` actually do, although only 3 values are documented. According to http://collab.kpsn.org/display/tc/creature_addon#creature_addon-bytes2 the value 1 signifies that this NPC has got `STATE_MELEE` (prepared melee weapon), which is evident from his main hand (mercenary?) knife. This value is present both in 257 (256+1) and 4097 (4096+1). What the values 256 and 4096 do, is not evident at first sight by only comparing him with other NPCs with that DB value. If you find out and tell me, I will be happy to add it to the documentation. :)
