### ISSUE TITLE
[3.3.5] BUG Achievements ID: 1817

### ISSUE THREAD

**Issue by zxyjwy** [TrinityCore/TrinityCore#14864]
Achievements ID: 1817 can not be done, I'm sorry, my English is limited!

TrinityCore rev. 770b859b5546 2015-06-10 20:04:23 +0800 (3.3.5 branch) (Win64, Release) (worldserver-daemon)
TDB 335.58 + updates up to and including 2015_06_08_00_world.sql

**Comment by tkrokli** [comment]
@zxyjwy : you have not provided the required information for a valid issue.

1. Always include your core revision hash and TDB version in your main post.
2. Always include names and links for NPCs, items, instances, objects and achievements in your post.
3. Always include what is supposed to happen + what happens instead.
4. Include information about how you discovered / tested the issue.

This is just a short list of the most important information needed in an issue, but you can add more too.

Example information (I haven't tested your issue myself) :
**Achievement: The Culling of Time (ID: 1817)**
Defeat the Infinite Corruptor in The Culling of Stratholme on Heroic Difficulty.

http://www.wowhead.com/achievement=1817/the-culling-of-time
http://wotlk.openwow.com/achievement=1817

**What is supposed to happen:** You get the achievement when you have killed the Infinite Corruptor in The Culling of Stratholme on Heroic Difficulty.

**What happens instead:** The player does not get the achievement after killing the Infinite Corruptor in The Culling of Stratholme on Heroic Difficulty (if this is what happens in your case).

(After that, write a short description about how you have tested it and what you have done to make sure that you should actually be able to get the achievement while using the straight TC source.)

**Comment by Aokromes** [comment]
Works for me (TM)

**Comment by Runico** [comment]
@Aokromes, It doesn't work at all, anyone else could confirm this ?

**Comment by tkrokli** [comment]
First of all, someone should document the issue properly and convincingly.

**Comment by sirikfoll** [comment]
isn't working, but the solution its simple:
```sql
-- Achievement The Culling of Time
DELETE FROM `disables` WHERE `entry`=7494 AND `sourceType`=4;

**Comment by Runico** [comment]
@sirikfoll, What is the reason of disabling this achievement ?

**Comment by sirikfoll** [comment]
The achievement is already disabled in current TDB, I suggested the remove from disables as a fix for the issue

**Comment by tkrokli** [comment]
I suppose Aokromes has already enabled it in his DB, if the disabled achievement works for him?

**Comment by Aokromes** [comment]
tkrokli, i tested cos patch before it was final, very likely i was told to delete the disable and that delete was missing on final commit :P

**Comment by tkrokli** [comment]
OK, does that mean @sirikfoll's suggested fix could be accepted as a solution, or do you need a new issue posted with the SQL as solution?
