### ISSUE TITLE
[3.3.5] Improved Devouring Plague error in direct damage

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#14869]
The Improved Devouring Plague talent is in error in the application of direct damage. He is totally ignoring the talent Shadow Weaving. Regardless of the number of stacks of Shadow Weaving the value of the direct damage of the Devouring Plague is not modified, only damage over time is modified.

Improved Devouring Plague Ids:

http://wotlk.openwow.com/spell=63625
http://wotlk.openwow.com/spell=63626
http://wotlk.openwow.com/spell=63627

Shadow Weaving:

http://wotlk.openwow.com/spell=15257
http://wotlk.openwow.com/spell=15331
http://wotlk.openwow.com/spell=15332

How to reproduce: Use Devouring Plague on a target.
Use Mind Fly to the Shadow Weaving accumulate 5 times. Use again Devouring Plague. Note that the Direct Damage has not undergone any modification.
Testes on rev. 3aa177410010e75934703be9247245881be73490

**Comment by Keader** [comment]
@Aokromes While writing the issue, I pressed ctrl + enter unintentionally and posted before it is finalized. Post edited already.

**Comment by Keader** [comment]
@robinsch You could take a look at this here?

**Comment by Mack36** [comment]
Is there any proof confirming that Improved Devouring Plague direct damage should depend on any dmg multiplying talent? 
There's a SPELL_ATTR3_NO_DONE_BONUS attribute attached to it [here] (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L3238), so it seems like intended.

**Comment by tkrokli** [comment]
http://wow.gamepedia.com/Improved_Devouring_Plague :
Improved Devouring Plague is a priest talent in the Shadow tree, available after spending 5 talent points. The talent causes Devouring Plague to instantly deal damage equal to 15/30% of its total periodic effect.

WotLK Patch 3.3.0 (2009-12-08):
This spell now deals 10/20/30% of its total periodic effect instantly, up from 5/10/15%.
WotLK Patch 3.1.0 (2009-04-14): Added.
***
http://wow.gamepedia.com/Shadow_Weaving :
Shadow Weaving is a priest talent which buffs the priest, increasing all shadow damage done by the priest by 2% per stack. Each point increases the chance to apply the buff by 33%, for a maximum of 100% chance.

WotLK Patch 3.0.2 (2008-10-14): Changed to a self-buff for the caster. Lowered to 3 ranks.
TBC Patch 2.1.0 (2007-05-22): Shadow damage increase per application lowered to 2%, to a maximum of 10%. Was 3%, to a maximum of 15%.

**Comment by Keader** [comment]
It makes no sense not increase. Talent must give direct damage 30% of the total DoT damage. If the DoT is incremented obviously the 30% applied directly should also increase

**Comment by Shauren** [comment]
@Keader not when the direct damage is calculated from "already increased" dot damage

**Comment by Keader** [comment]
@Shauren I confess I did not understand

**Comment by tkrokli** [comment]
@Keader : I think I see what Shauren says. Shadow Weaving damage increase is calculated first. After this, the Improved Devouring Plague talent damage is calculated, making it direct, non-increased damage.

**Comment by Keader** [comment]
But the damage from DoT is modified. Only the damage of the direct damage not. And the amount of direct damage should be 30% of the damage that the DoT will take on target. If the damage to the DoT on target increases, the direct damage applied should also increase

**Comment by robinsch** [comment]
@Keader Then find a proof. Maybe you can find a scene from http://www.warcraftmovies.com/movieview.php?id=164387

**Comment by Mack36** [comment]
I think I got it, since Improved Devouring Plague direct damage is based on DoT damage from plague, it should also be modified when DoT damage is.
Some screenshots
![1](https://cloud.githubusercontent.com/assets/5161189/8156101/b865e4d6-1363-11e5-975f-6fba7fcd05ca.jpg)
Without Shadow Weaving buff DoT damage was 610,
Direct damage from talent was 1274.
![2](https://cloud.githubusercontent.com/assets/5161189/8156106/c5900358-1363-11e5-9d0d-711a0ebf78d9.jpg)
With 5 stacks of Shadow Weaving buff DoT damage increased to 671 (which equals to 610 + 10% from Shadow Weaving) DoT dmg is Ok,
but direct damage is still the same - 1274, it supposed to be recalculated for more DoT damage, right?

And besides of that, try to calculate direct damage:
DoT tics 8 times, so its full damage is 8*610 = 4880
Direct damage should be 30% from DoT dmg 4880 * 0.3 = 1464, which != 1274
So It seems like there's another issue with this talent.

**Comment by Keader** [comment]
@robinsch In his video was a bit tricky, because needed to find two devourings without procs spell power items, with different stacks on the same target.It took a while but could find, thanks for the video.
At the moment -> 21:18 is applied a direct damage of 1988 with two stacks of Shadow Weaving
Shortly after 21:28 is applied to a direct damage of 2066 with 4 stacks of Shadow Weaving
Making the account 1988 + 4% (2 stacks of Shadow Weaving) ≅ 2067.52

@Mack36 This is exactly the logic xD

**Comment by robinsch** [comment]
```diff
diff --git a/src/server/game/Spells/Auras/SpellAuras.cpp b/src/server/game/Spells/Auras/SpellAuras.cpp
index 5479dcd..b7ee257 100644
--- a/src/server/game/Spells/Auras/SpellAuras.cpp
+++ b/src/server/game/Spells/Auras/SpellAuras.cpp
@@ -1305,6 +1305,7 @@ void Aura::HandleAuraSpecificMods(AuraApplication const* aurApp, Unit* caster, b
                     if (AuraEffect const* aurEff = caster->GetDummyAuraEffect(SPELLFAMILY_PRIEST, 3790, 1))
                     {
                         uint32 damage = caster->SpellDamageBonusDone(target, GetSpellInfo(), GetEffect(0)->GetAmount(), DOT);
+                        damage *= caster->SpellDamagePctDone(target, GetSpellInfo(), DOT);
                         damage = target->SpellDamageBonusTaken(caster, GetSpellInfo(), damage, DOT);
                         int32 basepoints0 = aurEff->GetAmount() * GetEffect(0)->GetTotalTicks() * int32(damage) / 100;
                         int32 heal = int32(CalculatePct(basepoints0, 15));
```

**Comment by Shauren** [comment]
@robinsch as a followup for that - might want to take a look at all other spell scripts calling SpellDamageBonusDone with "DOT" as argument and use SpellDamagePctDone there as well. In past SpellDamagePctDone was called inside it but this is no longer the case (to allow stat snapshotting). It looks like the author of that change didn't bother to update existing scripts

**Comment by robinsch** [comment]
@Shauren I've already checked that, but it's research work I won't do. If anyone else want to look at this I will open a issue for it.

**Comment by Keader** [comment]
@robinsch Working perfectly ...You could create a PR?

**Comment by robinsch** [comment]
@Keader ( @tkrokli ) You can create a PR with me as author.

**Comment by tkrokli** [comment]
OK, very well. Since you want me to, I'll do it. jackpoz and some of the other devs would like you to start doing PRs, though, just because... you know, direct access to the PR, coding knowledge and all that. Anyway, I'll create this one too for you. I still wish you and Keader would start maintaining your forks. :smirk_cat:

**Comment by Keader** [comment]
Closed by #14898

**Comment by tkrokli** [comment]
@Keader : that will happen if and when #14898 is merged, not before (just so you know).

**Comment by Keader** [comment]
@Shauren You say spells that are calculated according to X% of DoT?
The Conflagrate (warlocks) is less damage than expected (#14918) . Perhaps the Chimera Shot (Hunter) and Swiftmend (Heal Druid) are also problems with. I'll test them later.
