### ISSUE TITLE
[3.3.5] Changing leader of the group in Arena makes the new leader unable to talk on group chat

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#14868]
https://github.com/TrinityCore/TrinityCore/commit/f166dc3cab3f5325984c9f0fcf9ed1406ae6eae6

Pretty much the title, if you change the leader of the group while you are in arena, the new leader will be unable to say anything via /party (group chat).

That's maybe not a big problem because you can make unable to switch leader in arena, but there is another bug related to this, i'll put an example:
There are two people (player X and player Y) that are on the same group and are queued for 2v2 (they are not in the arena yet). Player X is the leader of the group. When the message appears to enter the arena battle, if player Y enters before player X in the arena, player Y will be unable to talk because a new group is created for arena. When player X enters in arena, because of AddOrSetPlayerToCorrectBgGroup changes the leader if an old group exists, player X will be the new leader and he will be unable to talk in the chat group (player Y will be able to talk again).

It is hard to explain, just test it, you will see fast what im talking about (the fastest way to test it is just switching the leader of the group while in arena).
##

**Comment by Raydor** [comment]
http://puu.sh/il7BG/d673bad9c6.png

The problem is that if you are in the arena, it doesn't detect the actual group, it detects the original group. With this change, if you are in the arena (don't know if this affects BG too), it will detect the actual group instead of the group you had before entering the arena.

**Comment by Aokromes** [comment]
This fix is valid? if yes, plz open a pr for it.

**Comment by Raydor** [comment]
Can anyone open a PR for me please?

Also I don't know if the fix is correct so will wait till the PR so someone say if it's valid.
