### ISSUE TITLE
[6x] Mirror image (mage talent)

### ISSUE THREAD

**Issue by vvizard100** [TrinityCore/TrinityCore#14867]
What steps will reproduce the problem?
Cast spell ID : 55342

What is the expected output? What do you see instead?
You're supposed to see three copies of your character binded to you, following you and attacking with you.
You see nothing, no copy appears.

What version of the core and database are you using? On what operating system?
Core Rev : https://github.com/TrinityCore/TrinityCore/commit/1d20122903a9812bea6e3e12f285de8fe073a9d3
DB : last available (on 11/06/2015)
OS : Windows 8.1

no log available for now since console returns nothing from this spell casting

EDIT : the handler in SpellHandler.cpp line 504 doesn't seems to be update... now I understand better ! xD

**Comment by Boomper** [comment]
Here's your problem:
Effect 1: Id 3 (SPELL_EFFECT_DUMMY) DIFFICULTY_NONE
BasePoints = 3
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

It's missing a spellscript/spell_trigger_spell row, if you can get your hands on packet data (for spellIid of summon spells) I can look into it :-)

**Comment by Goatform** [comment]
I think that it's MIRROR_IMAGE packet issue.

**Comment by Boomper** [comment]
@Goatform The effect of that spell he's using is SPELL_EFFECT_DUMMY and since it has no spell script it's simply not doing anything. But yes CMSG_GET_MIRROR_IMAGE_DATA, SMSG_MIRROR_IMAGE_COMPONENTED_DATA and SMSG_MIRROR_IMAGE_CREATURE_DATA are still unhandled (but they're useless if there's no effect that summons the mirror images)...

**Comment by Goatform** [comment]
Yeah, I agree.

**Comment by Sar777** [comment]
https://gist.github.com/Sar777/d2b00a3348642156156b

**Comment by vvizard100** [comment]
very nice work Sar777, image is perfectly copied ! thanks mate :)

**Comment by DDuarte** [comment]
@Sar777: may I suggest you to open a Pull Request with your code? But before that rename the packet fields to match https://gist.github.com/DDuarte/61a11138e8a359d62159 :+1:

**Comment by DDuarte** [comment]
@Sar777 code has been pushed in eeb49d238a292669e95cdbd591fcfcc55eeb560a

**Comment by Rushor** [comment]
fix was pushed, everything else belongs to https://github.com/TrinityCore/TrinityCore/issues/14825 (i added it in the todo list)
