### ISSUE TITLE
[3.3.5a] ICC: Rotface 10/25 Heroic - Vile Gas

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#14876]
1- Vile Gas should not be casted by the Trigger: 

Example: http://puu.sh/imfOk/1f7a89ba69.jpg

2- (Not sure about this but doesn't seems logical) if Creatures (Like Totems, Pets and Guardians) are nearby a player that is affected by Vile Gas, they get the Vile Gas Debuff and starting vomiting.

Example:http://puu.sh/imggd/7c888d9ba8.jpg

3.3.5a branch
hash f5530c719b71309bd476aff528b0d3e1220ca49b 
TDB 58

**Comment by tkrokli** [comment]
@Demonid : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/CONTRIBUTING.md

You should know that all issues need to be documented with core rev. hash and TDB version.

**Comment by Demonid** [comment]
@tkrokli Done, should i change anything else?

**Comment by tkrokli** [comment]
> Done, should i change anything else?

If you have got any extra addon code or any modifications to the straight 3.3.5 source, include the info.

Part of the documentation process is to say "What is supposed to happen" and "What happens instead".
Try to follow the TC example: http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
