### ISSUE TITLE
[6.x] Smart_Action_Talk isnt working

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/TrinityCore#14871]
Core rev: commit 733456ef31
Dunno what is exactly but creatures/npcs dont talk if you use a SAI.They only talk if its scripted in the core with C++.

**Comment by Killyana** [comment]
Confirm on rev. d9200f112b93

**Comment by MitchesD** [comment]
Even texts in C++ scripts don't work. I tried some bosses etc. and in sniff I see that is send only packet with default values. So I think creature texts are broken in general

**Comment by ShinDarth** [comment]
@MitchesD that was even what I thought, but in:

https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Texts/CreatureTextMgr.cpp#L304

even if you replace

```CreatureTextBuilder builder(finalSource, finalSource->getGender(), finalType, iter->group, iter->id, finalLang, whisperTarget);```

with something custom without using creature texts, like:

```
Trinity::CustomChatTextBuilder builder(finalSource, finalType, "THIS IS JUST A TEST", finalLang, whisperTarget);
```
it doesn't work. But if you replace it with something like:

```
source->Say("THIS IS JUST A TEST", LANG_UNIVERSAL);
```

it will work. So I think there is something wrong with those "builders" but I have no idea about how they work.

**Comment by ShinDarth** [comment]
Like MitchesD pointed in IRC, https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Texts/CreatureTextMgr.cpp#L36 this is never called

and I can confirm it

**Comment by DDuarte** [comment]
_builder needs to be called in https://github.com/TrinityCore/TrinityCore/commit/218f14f84b692288e58c292a9808a073e50f96ad#diff-4f6c55d7d96327acfd11a07c7362748bR148

**Comment by Daniel25** [comment]
Thanks Shauren for fixing it so fast :). And sorry for posting in a closed issue, I needed to say you thanks you.
