### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#14878]
Crashlog http://paste.ubuntu.com/11704162/

Custom Script: transmogrify - ac2 - arena spectator

Branch 3.3.5
Revision 6a637f6b1c186eb15373fce443d729dcc74e5361
TDB 58

**Comment by DJScias** [comment]
I doubt you'll get much help in regards to custom scripts breaking on the official trinity github.

**Comment by jackpoz** [comment]
can you post your /home/Source/src/server/game/Handlers/MovementHandler.cpp file ? (using a paste site please)

**Comment by Runico** [comment]
@jackpoz Yes, http://paste.ubuntu.com/11704435/

**Comment by Frytiks** [comment]
Anticheat crash

**Comment by tkrokli** [comment]
Runico, take a look at the diff I made between your MovementHandler.cpp and the original in 3.3.5:

https://gist.github.com/tkrokli/e7bbcbf28ca63e9aa698

I see quite a lot of changes from the original file. I don't know how much it affects your issue, though.

**Comment by Boomper** [comment]
replace this:
if (!plrMover->m_transport)
with:
if (plrMover && !plrMover->m_transport)

**Comment by Shauren** [comment]
As pointed out - this is not a crash in TrinityCore sources

**Comment by jackpoz** [comment]
it's crash reports like these that make us even more resilient to review crash reports with custom changes.

Are those changes added by the AC2 patch ? just to close on sight any crash report with that patch

**Comment by tkrokli** [comment]
> http://community.trinitycore.org/topic/11463-ac2/

```
Sorry, there is a problem
We could not locate the item you are trying to view.
Error code: 2F173/1
Contact Us

**Comment by Aokromes** [comment]
http://community.trinitycore.org/topic/6387-patch-ac2/

**Comment by tkrokli** [comment]
Thanks, I should have guessed that it was about AC2 and searched for the topic... =^.^=
