### ISSUE TITLE
[6.x] Auth

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14885]
Is there any way to pass the account of the version 4.3.4 to version 6.x without having to ask the password?

Because I saw that the encryption is different.

Thanks

**Comment by tkrokli** [comment]
This is not a forum. Use http://community.trinitycore.org/ for questions. Please close this issue too.

**Comment by DDuarte** [comment]
Since we only store hashes and not original passwords it's *impossible* to recreate a different hash.
