### ISSUE TITLE
[3.3.5] DB/Quest: Hellfire Fortifications (DK version)

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#14887]
TrinityCore rev. 6af3bc69970d 2015-06-13 23:11:17 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.58 + updates.

Quest ID 13411 Hellfire Fortifications DK version (http://www.wowhead.com/quest=13411/hellfire-fortifications) is missing the `RequestItemText`: Return to me after you have helped capture each fort!

In quest ID 13409 & daily quest ID: 10110, that text exists already. SQL query to compare the 3 quests:
```sql
SELECT `RequestItemsText` FROM `quest_template` WHERE `Id` IN (10110, 13409, 13411);
```
```
RequestItemsText
-------------------------------------------------------
Return to me after you have helped capture each fort!
Return to me after you have helped capture each fort!
(NULL)
```
The Alliance DKs have already got the `RequestItemsText` for all 3 quests. Query to show those 3 quests:
```sql
SELECT `RequestItemsText` FROM `quest_template` WHERE `Id` IN (10106, 13408, 13410);
```
```
RequestItemsText
---------------------------------------------------------------------------
$N, return to me when you have aided in the capture of each of the forts!
$N, return to me when you have aided in the capture of each of the forts!
$N, return to me when you have aided in the capture of each of the forts!
```
**Solution:**
```sql
UPDATE `quest_template` SET `RequestItemsText`="Return to me after you have helped capture each fort!" WHERE `Id`=13411;
```
Edit: solution tested, works as intended. Unless you have any objections, write-up and close.

**Comment by Ascathor** [comment]
Shipit.

**Comment by tkrokli** [comment]
:shipit: :wink: :computer: :monkey:
