### ISSUE TITLE
Need help. IDK

### ISSUE THREAD

**Issue by Kormandx** [TrinityCore/TrinityCore#14881]
Hello,

I am sorry for my annoying noob question, but i cant google it. I succesfully compiled Trinity Core, set conf, DB, but when i start worldserver.exe console gives to me error that table gameobject_addon is missing.
I tried recompiling, but no changes.
 I tried put worldserver.exe from Jeuties repack and it'S work!
But i wanna own worldserver please, help me.

Sincerely
Adam

**Comment by SkyFire** [comment]
![1ee1360a1b7c0617dc324cadc60cbddc](https://cloud.githubusercontent.com/assets/32227/8145055/f4f5d3a4-11bd-11e5-88bc-aa38b3d1b4c1.jpg)

**Comment by Kormandx** [comment]
I am adding info:

3.3.5a

**Comment by DDuarte** [comment]
@Kormandx: This issue section is not for installation related problems. For that we have the forums (http://community.trinitycore.org/) and our IRC channel (http://collab.kpsn.org/display/tc/IRC).

Repacks are not support for obvious reasons. If you need help with one try contacting the "authors" of said repacks instead.

I recommend you to read http://collab.kpsn.org/display/tc/Databases+Installation carefully. Everything is explained there. If you need further help just us on IRC.
