### ISSUE TITLE
6.x Compile Error[Linux Debian]

### ISSUE THREAD

**Issue by AMDIvailo** [TrinityCore/TrinityCore#14886]
Hello, i just tried to compile trinitycore 6.x and i had this error:
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1395: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aokromes** [comment]
useless log, no info, works for me.

**Comment by AMDIvailo** [comment]
How to make it be not usless?

**Comment by AMDIvailo** [comment]
What i need to post here so yo can help me?

**Comment by tkrokli** [comment]
@AMDIvailo : This is not a forum. Use http://community.trinitycore.org/ for your questions.

Your issue does not affect others, so it does not belong here in the issue tracker. Please close this now.
