### ISSUE TITLE
[6x] "Mature Chat Filter" toggle resetting on relog

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#14882]
**What steps will reproduce the problem?**
1. Uncheck "Mature Chat Filter" in "Social" so that curse words are no longer filtered.
2. Relog your account and try saying a curse word and/or open "Social" tab again in config.

**What is the expected output? What do you see instead?**
Expected: The curse words are not filtered anymore since you unchecked it.
Instead: The checkmark and filter are back, the actual unchecking of "Mature Chat Filter" was not saved for some reason.
 
**What version of the core and database are you using? On what operating system?**
Core Rev. https://github.com/TrinityCore/TrinityCore/commit/97c903ec2ab4babd6175d9569dd29bd795acba18
DB Rev. https://github.com/TrinityCore/TrinityCore/commit/74eeefa5be163a55489f91c05d7dfd1cb624c78d (last commit to 'sql')
Windows 7 Ultimate
 
**Please provide any additional information below.**
@Carbenium told me to make an issue about it, he mentioned something about this maybe being related to battle.net functionality? I don't know personally.

**Comment by Aokromes** [comment]
working on f6637439f484dacc9c8deb3c4dd07832146ff6f6
