### ISSUE TITLE
[3.3.5] Shaman - Wrong totem placement

### ISSUE THREAD

**Issue by Nertx** [TrinityCore/TrinityCore#14888]
Description: When you use Call of the Elements, Ancestor or Spirits the 4 totems are placed too close to each other.

The totems should be summoned in a wider circle, instead they are summoned right next to the feet of the shaman.

Should be like this: http://www.warcraftmovies.com/movieview.php?id=159537 10:00, 17:50, 21:45

SS on my core:

![wowscrnshot_061415_171628](https://cloud.githubusercontent.com/assets/7716284/8150309/ae282f00-12ba-11e5-9786-00c51cf1c1dd.jpg)

SS on AT server:

![wowscrnshot_061415_172233](https://cloud.githubusercontent.com/assets/7716284/8150321/691829f0-12bb-11e5-9cfd-b3508e50806a.jpg)

TrinityCore rev. 1a4f5c5f0ffe15810ffe8d0c712a8c2163b089dd

**Comment by MitchesD** [comment]
AT is a private server? If so, how you can be sure that its right? Need confirmation from retail, we are using this totem formations for years and I have never seen any issue like this, so you need more arguments ;-)

**Comment by Naios** [comment]
But is looks better ^^

**Comment by tkrokli** [comment]
"Looks nice" is never a good argument, neither are private/custom cores or pservers. Like MitchesD said, the current settings are based on sniffs from live Blizzard servers or how it works blizzlike.

**Comment by Ascathor** [comment]
^

**Comment by Nertx** [comment]
"Should be like this: http://www.warcraftmovies.com/movieview.php?id=159537 10:00, 17:50, 21:45"

You guys are blind?

**Comment by Nertx** [comment]
http://www.warcraftmovies.com/movieview.php?id=155821  00:35 4:25

@MitchesD  @Aokromes 

More proofs than retail videos are impossible to find, the SS on AT server was only for better understanding not to prove

**Comment by Kinzcool** [comment]
Just get a sniff and compare where the totems are spawned relatively to the player's position when he summoned them.

**Comment by MitchesD** [comment]
@Nertx I think that video isn't from retail

**Comment by tkrokli** [comment]
Also, the totems in your video link is placed closer than in your SS 2. It proves nothing.

**Comment by Aokromes** [comment]
Also, there is no such revision or branch on trinitycore.

**Comment by Kinzcool** [comment]
Patch 6.2.0:
![wowscrnshot_061415_173027](https://cloud.githubusercontent.com/assets/1700544/8150523/22854b30-12bb-11e5-9ebf-3c53040532dd.jpg)

**Comment by Killyana** [comment]
Here positions from 3.3.5:
```
Destination Position: X: 505.7721 Y: 526.7587 Z: 741.5216
Destination Position: X: 509.2885 Y: 524.3851 Z: 741.8252
Destination Position: X: 506.9148 Y: 520.8686 Z: 745.3129
Destination Position: X: 503.3984 Y: 523.2422 Z: 745.2871

**Comment by MitchesD** [comment]
he didn't provide any valid core hash or branch

**Comment by Kinzcool** [comment]
I just checked on TC, and actually it's like the second picture.

**Comment by Frytiks** [comment]
But carefull here, if u increase spawn range, Magna totem and fire totem not doing damage

**Comment by Killyana** [comment]
Here the difference between TC and sniffs from wotlk:
http://imgur.com/b9pVzJV

**Comment by tkrokli** [comment]
Interesting observation, Kinzkool. It means that TC 6.x does what the OP wants, but not what it is supposed to be compared to Blizzard PTR 6.2.0, if I understand your logic correctly.

**Comment by P-Kito** [comment]
I solved that with insertion in LoadDBCDataCorrections for each totem.
Prolly the wrong way, but it does increase the spawn radius.

I found a video of 3.3.5 retail showing it: https://youtu.be/tUoGXe1BORE?t=31

**Comment by P-Kito** [comment]
The private server, AT, has way too much radius I think.

**Comment by Nertx** [comment]
@MitchesD  @Aokromes I just renamed the branch when installing tc, also updated the rev

**Comment by Nertx** [comment]
@tkrokli "the SS on AT server was only for better understanding not to prove"

@P-Kito  Yes.. or may be related to vision angle also

**Comment by tkrokli** [comment]
> I just renamed the branch when installing tc, also updated the rev

Thanks, that is better and also as required. :+1:

**Comment by Nertx** [comment]
Yes, but I was referring to the topic \õ/

**Comment by Nyeriah** [comment]
![capture](https://cloud.githubusercontent.com/assets/2879479/8151208/c7e0fa58-12dd-11e5-82e1-75fcbd0a173a.JPG)

That's on retail, currently. I don't have 4 totems but doubt it'd matter anyway

**Comment by Naios** [comment]
Which are the spells that spawn the totems?

**Comment by Nertx** [comment]
These:

Call of the Elements : 66832
Call of the Ancestor : 66843
Call of the Spirits : 66844

**Comment by Keader** [comment]
Nothing new?

**Comment by lainimer** [comment]
news?

**Comment by P-Kito** [comment]
I did it really ... REALLY dirty in DBC Corrections.
```
// Correct Totem Spawn Radius
            case 8075: // Totem der Erdstärke
            case 8160:
            case 8161:
            case 10442:
            case 25361:
            case 25528:
            case 57622:
            case 58643:
            case 8143: // Totem des Erdstoßes
            case 2062: // Totem des Erdelementares
            case 8071: // Totem der Steinhaut + ranks
            case 8154:
            case 8155:
            case 10406:
            case 10407:
            case 10408:
            case 25508:
            case 25509:
            case 58751:
            case 58753:
            case 2484: // Totem der Erdbindung
            case 5730: // Totem der Steinklaue
            case 6390:
            case 6391:
            case 6392:
            case 10427:
            case 10428:
            case 25525:
            case 58580:
            case 58581:
            case 58582:
            case 8177: // Totem der Erdung
            case 6495: // Totem des Wachens
            case 3738: // Totem des Stürmischen Zorns
            case 8512: // Totem des Windzorns
            case 10595: // Totem des Naturwiderstands
            case 10600:
            case 10601:
            case 25574:
            case 58746:
            case 58749:
            case 2894: // Totem des Feuerelementares
            case 8181: // Totem des Frostwiderstands
            case 10478:
            case 10479:
            case 25560:
            case 58741:
            case 58745:
            case 8190: // Totem des glühenden Magmas
            case 10585:
            case 10586:
            case 10587:
            case 25552:
            case 58731:
            case 58734:
            case 3599: // Totem der Verbrennung
            case 6363:
            case 6364:
            case 6365:
            case 10437:
            case 10438:
            case 25533:
            case 58699:
            case 58703:
            case 58704:
            case 8227: // Totem der Flammenzunge
            case 8249:
            case 10526:
            case 16387:
            case 25557:
            case 58649:
            case 58652:
            case 58656:
            case 8170: // Totem der Reinigung
            case 5675: // Totem der Manaquelle
            case 10495:
            case 10496:
            case 10497:
            case 25570:
            case 58771:
            case 58773:
            case 58774:
            case 5394: // Totem des heilenden Flusses
            case 6375:
            case 6377:
            case 10462:
            case 10463:
            case 25567:
            case 58755:
            case 58756:
            case 58757:
            case 8184: // Totem des Feuerwiderstands
            case 10537:
            case 10538:
            case 25563:
            case 58737:
            case 58739:
            case 30706: // Ingrimm
            case 57720:
            case 57721:
            case 57722:
                spellInfo->EffectRadiusIndex[EFFECT_0] = EFFECT_RADIUS_3_YARDS;
                break;
```

**Comment by Keader** [comment]
Gives compilation error:


Error	1	error C2039: 'EffectRadiusIndex' : is not a member of 'SpellInfo'	C:\TrinityCore\src\server\game\Spells\SpellMgr.cpp	3059	1	game
	2	IntelliSense: class "SpellInfo" has no member "EffectRadiusIndex"	c:\TrinityCore\src\server\game\Spells\SpellMgr.cpp	3059	15	game

**Comment by Rushor** [comment]
the function was renamed ~2 years ago

```c++
spellInfo->Effects[EFFECT_0].RadiusEntry = sSpellRadiusStore.LookupEntry(EFFECT_RADIUS_3_YARDS);
```

**Comment by P-Kito** [comment]
Sry updated it :) But beware, this is super hacky I think.

**Comment by Keader** [comment]
now works :+1: 
The distance looks cool

**Comment by Raydor** [comment]
I did it this way:

```diff
5  src/server/game/Spells/Spell.cpp
 @@ -1301,7 +1301,10 @@ void Spell::SelectImplicitCasterDestTargets(SpellEffIndex effIndex, SpellImplici
                 dist = objSize + (dist - objSize) * float(rand_norm());
 
             Position pos = dest._position;
-            m_caster->MovePositionToFirstCollision(pos, dist, angle);
+            if (m_spellInfo->AttributesEx7 & SPELL_ATTR7_SUMMON_PLAYER_TOTEM) // Aumentado el radio de los totems del chaman para que esten mas lejos del chaman
+                m_caster->MovePositionToFirstCollision(pos, dist + 2.0f, angle);
+            else
+                m_caster->MovePositionToFirstCollision(pos, dist, angle);
 
             dest.Relocate(pos);
             break;
```

**Comment by Rushor** [comment]
we are living in times of HasAttribute() which was implemented by shocker..

**Comment by Nertx** [comment]
Working, thank you guys

**Comment by Keader** [comment]
Both work ... which is not hack ?! lol

**Comment by robinsch** [comment]
Raydor way looks cleaner, but use HasAttrubute(SPELL_ATTR7_SUMMON_PLAYER_TOTEM)

**Comment by P-Kito** [comment]
As I said, ofc it looks cleaner :+1:

**Comment by P-Kito** [comment]
Oh the factor + 2.0f is probably a bit too much. According to @Kinzcool 's Screenshot it should be something like + 1.0f

**Comment by Raydor** [comment]
Yeah, I did it before you implemented HasAttribute, and I copied it from my commit just to not create a diff only for that (im too lazy xD), that's why it doesn't have HasAttribute.

**Comment by P-Kito** [comment]
For TC I recommend a value around 0.6f to 1.0f. which looks similiar to the screenshot and video.

**Comment by Ascathor** [comment]
Better idea: Make it a config setting defaulting to 1.0f.

**Comment by P-Kito** [comment]
Good idea, but:

That's like making a config for something blizzlike, to make it customizable and non blizzlike.
I think we are aiming for blizzlike values.

**Comment by Ascathor** [comment]
#
#    MaxArenaPoints
#        Description: Maximum arena points a character can have.
#        Default:     10000

MaxArenaPoints = 10000

#
#    StartPlayerMoney
#        Description: Amount of money (in Copper) that a character has after creation.
#        Default:     0
#                     100 - (1 Silver)

StartPlayerMoney = 0



They are blizzlike on default, but can be configurated. I like that aspect and I think we should keep it from time to time
Features don't hurt, especially not changeable ones imo

**Comment by P-Kito** [comment]
okay true. I am not gonna add a "but" here. ;)

**Comment by Ascathor** [comment]
That's why we are discussing, say what's on your mind ;)

**Comment by P-Kito** [comment]
Well, I was thinking if it is really necassary to customize the totem distance...
I mean... the only reason to do it is to look like any famous arena server (AT).

**Comment by tkrokli** [comment]
So would it be interesting to set the totems' distance to be configurable to a numerical value, 0 being disabled and 1 - 20 being meters in distance away from the shaman?

**Comment by Aokromes** [comment]
Na, not 0 value, instead put the default value on conf.

**Comment by P-Kito** [comment]
```
################################################################
Totem Placement
    Description: Amount, how far away totems are placed from the summoner
    Default:     0.7 - default (blizzlike)
                     more means: Farther away from the shaman
                     less means: Closer to the shaman
################################################################               
TotemPlacement = 0.7
```

Looks good :+1:

**Comment by DDuarte** [comment]
Don't add so much bloat to settings. If the value should be 0.7 make it 0.7.

**Comment by Gacko** [comment]
@Ascathor: Doing things because we did it in the past is not an argument. Take the blizz value.

**Comment by tkrokli** [comment]
My (suggested) version, with simpler value setting as well as 0.7x resolution:
```
################################################################
#  Totem Placement
#    Description: Distance totems are placed from the summoner
#    Numerical values allowed: integer, 1-20 ( x 0.7 meters)
#    Default value:    1
#

TotemPlacement = 1

**Comment by P-Kito** [comment]
somone should actually calculate the real blizz value from the sniffs provided a few comments above.

**Comment by robinsch** [comment]
A config value for this? Are you guys serious?

**Comment by P-Kito** [comment]
someone speaking out of my soul.

**Comment by Ascathor** [comment]
We have configuration for pretty much every sh!t, honestly. But, do whatever you find approperiate, I do not see it as a bad idea.

**Comment by Kinzcool** [comment]
I haven't gotten a recent sniff to calculate it, but from the coordinations provided by @Killyana's comment, the aboslute distance between a totem and a player's position should be of 3.0f.

**Comment by Frytiks** [comment]
Config option use on localhost for testing

**Comment by P-Kito** [comment]
@Kinzcool put a 3.0f in the code provided and totems will spawn in Nevada :dart:

**Comment by Killyana** [comment]
I found better positions from 3.3.5 sniffs:
```
Destination Position: X: 230.1181 Y: -308.4589 Z: 180.4916  (totem1)
Destination Position: X: 226.1979 Y: -310.081 Z: 180.4916   (totem2)
Destination Position: X: 224.5757 Y: -306.1607 Z: 180.4915  (totem3)
Destination Position: X: 228.496 Y: -304.5386 Z: 180.4915   (totem4)

.go crea id 23954 (teleport to the map)

.go 230.1181, -308.4589, 180.4916
.go 226.1979, -310.081, 180.4916
.go 224.5757, -306.1607, 180.4915
.go 228.496, -304.5386, 180.4915

Distance between 2 Totems: The distance is: (3D) 1.742541 (2D) 1.742541 (Exact 3D) 4.242541 (Exact 2D) 4.242541 yards.
Diagonal distance between 2 totems: The distance is: (3D) 3.499943 (2D) 3.499943 (Exact 3D) 5.999943 (Exact 2D) 5.999943 yards.

**Comment by Kinzcool** [comment]
@P-Kito: the 3.0f is not what should go in the code, but instead is the radius that should be used instead of the default one that is actually load from DBC's (5.0).

**Comment by tkrokli** [comment]
**P-Kito** commented July 8, 2015, 01:06 CEST
> @Kinzcool put a 3.0f in the code provided and totems will spawn in Nevada :dart:

Thanks for the lulz. xD - Not even within the same battleground? :p
***
**Kinzcool** commented July 8, 2015, 01:38 CEST
> @P-Kito: the 3.0f is not what should go in the code, but instead is the radius that should be used instead of the default one that is actually loaded from DBCs (5.0f).
>
>If you do the ratio, it should be 40% less than the second screenshot in the OP (actual TC), which makes the positions in the 6.2.0 screenshot (correct one) I posted.

Thanks for posting the follow-up info. :-)

**Comment by P-Kito** [comment]
I am not sure but have tried using "Blink" (mage spell) after u insert your fix?

**Comment by Eliminationzx** [comment]
It's better way?
```
src/server/game/Spells/Spell.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 30c02db..29972a4 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -1294,7 +1294,7 @@ void Spell::SelectImplicitCasterDestTargets(SpellEffIndex effIndex, SpellImplici
                 dist = m_spellInfo->Effects[effIndex].CalcRadius(m_caster);
 
             if (dist < objSize)
-                dist = objSize;
+                dist = objSize * 2;
             else if (targetType.GetTarget() == TARGET_DEST_CASTER_RANDOM)
                 dist = objSize + (dist - objSize) * float(rand_norm());
```

**Comment by Frytiks** [comment]
No its increase blink distance, i will send diff later

**Comment by P-Kito** [comment]
Not just blink, all the summons for that TARGET_DEST_X. For example blood beasts @ saurfang

**Comment by Frytiks** [comment]
Try it http://pastebin.com/2mFgdwEW

**Comment by Eliminationzx** [comment]
that looks better
```
 src/server/game/Spells/Spell.cpp | 16 ++++++++++++++--
 1 file changed, 14 insertions(+), 2 deletions(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 30c02db..a2e7ecb 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -1295,8 +1295,20 @@ void Spell::SelectImplicitCasterDestTargets(SpellEffIndex effIndex, SpellImplici
 
             if (dist < objSize)
                 dist = objSize;
-            else if (targetType.GetTarget() == TARGET_DEST_CASTER_RANDOM)
-                dist = objSize + (dist - objSize) * float(rand_norm());
+
+            switch (targetType.GetTarget())
+            {
+                case TARGET_DEST_CASTER_RANDOM:
+                    dist = objSize + (dist - objSize) * float(rand_norm());
+                break;
+                case TARGET_DEST_CASTER_FRONT_LEFT:
+                case TARGET_DEST_CASTER_BACK_LEFT:
+                case TARGET_DEST_CASTER_FRONT_RIGHT:
+                case TARGET_DEST_CASTER_BACK_RIGHT:
+                    dist = objSize * 2;
+                break;
+                default: break;
+            }
 
             Position pos = dest._position;
             m_caster->MovePositionToFirstCollision(pos, dist, angle);
```

**Comment by robinsch** [comment]
try to remove the bounding radius from normal dist.

**Comment by sirikfoll** [comment]
The fix in https://github.com/TrinityCore/TrinityCore/issues/14888#issuecomment-121883114 seem to work pretty well

**Comment by Rushor** [comment]
@Eliminationzx: pls open up a pr for this fix :)

https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request

**Comment by Keader** [comment]
ref: https://github.com/TrinityCore/TrinityCore/commit/190c75c5668caae3972f061b9a1073aac219e0ef
