### ISSUE TITLE
[6.x] Obtaining list of characters

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14891]
Rev: https://github.com/TrinityCore/TrinityCore/commit/859aaa5543a60d89db21d4c4ab0740685a51933e

Good nights,

When I try to connect my game account often stays in obtaining list of characters and not continuous or does not pass directly connected.

Thanks

**Comment by MitchesD** [comment]
cannot reproduce, win64, what's your OS?

**Comment by Darkiu** [comment]
Server: Ubuntu 15.04
Cliente: Win64 and Win32

**Comment by Aokromes** [comment]
You have open port 8086?

**Comment by Darkiu** [comment]
Yes, in TCP_IN and TCP_OUT

**Comment by Darkiu** [comment]
This problem only happens to certain people not to all.

**Comment by tkrokli** [comment]
> This problem only happens to certain people not to all.

If it happens to the same people each time, I don't think it will be an issue with the source at all. You need to check your server logs for those users/computers where this happens. It can happen just because of simple things like a weird computer name or other external issues.

**Comment by ShinDarth** [comment]
It happened to me a similar issue, but only when client and server were into separated machines of the same LAN. However, pressing several times the ENTER key fixed the issue for me, but I can confirm it is not as "fluid" as it is when both client and server are on localhost.

Rev https://github.com/TrinityCore/TrinityCore/commit/3ada2ed993517a19f9733fcface94787569bbdf9
