### ISSUE TITLE
[3.3.5][Crash] SocialMgr::GetFriendInfo()

### ISSUE THREAD

**Issue by xjose93** [TrinityCore/TrinityCore#14894]
Crashlog: http://pastebin.com/2t26JH2a
Revision: cac4f95
DB version: TDB 335.58
Custom patches: transmog, ac

Details (not sure if will help):

SELECT \* FROM character_social WHERE guid = 351876;
![trwyxfc 1](https://cloud.githubusercontent.com/assets/707423/8159223/d40d6e88-1364-11e5-9c77-38ba3d888965.png)

SELECT \* FROM character_social WHERE friend = 351876;
![llz57o5 1](https://cloud.githubusercontent.com/assets/707423/8159187/87a19678-1364-11e5-98e1-815c7f6bbcd2.png)
##

**Comment by xjose93** [comment]
http://pastebin.com/6LTHTkmN & http://pastebin.com/rU8A99T1

Rev: 0b9cd22a6b5a0cca6e3c07dd5ae077ddbdfc3992

**Comment by xjose93** [comment]
http://pastebin.com/2QrkdTLp

Rev: 6a303caffd6930bf20e15668229a45a77d38f348

**Comment by xjose93** [comment]
http://pastebin.com/1zFRuu7Z

Rev: 82b7273

**Comment by xjose93** [comment]
http://pastebin.com/CuM9zJp9

Rev: fa1cad2020e5c2d54fe06ec9cd90d8e6a44daa5b

**Comment by jackpoz** [comment]
it might help to helgrind/valgrind logging out (player logs out, player kicked for afk, player kicked for double login) with a lot of friends. 
What's strange is that at that point TC runs single-threaded. How many map threads do you have in your configs ?

**Comment by planee** [comment]
comfirm，i got it serveral days ago too，any idea？

**Comment by jackpoz** [comment]
post the crash log you got several days ago then with the commit hash too

**Comment by xjose93** [comment]
@jackpoz MapUpdate.Threads = 1

And not sure about if ill be able to run valgrind/helgrind.

**Comment by jackpoz** [comment]
the helgrind/valgrind part was for those developers who wanted to work on this crash. Since you have 1 map thread then this is most likely not a threading issue.

**Comment by Pirricli** [comment]
http://pastebin.com/KPQhEEkC

b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Pirricli** [comment]
http://pastebin.com/R860zXue

ebb33bbfc1f11a16e00e0d84965ad5350267940a

**Comment by Aokromes** [comment]
1 year since the last crashlog, if this bug is still valid post one NEW ticket with updated core.
