### ISSUE TITLE
[3.3.5][Quest] Avenging The Fallen

### ISSUE THREAD

**Issue by fvicaria** [TrinityCore/TrinityCore#14892]
This quest is not supposed to be repeatable on WotLK only from Cataclysm onwards.

http://www.wowhead.com/quest=7830/avenging-the-fallen

TBD 335.58

``` SQL
UPDATE `quest_template` SET `SpecialFlags`=0 WHERE  `Id`=7830;
```

**Comment by Rushor** [comment]
remove the `world2` :)

**Comment by Killyana** [comment]
The quest was repeatable before the Patch 3.3.3, than fixed by blizzard, also this quest was removed on cataclysm.

**Comment by Rushor** [comment]
http://www.wowhead.com/quest=7830/avenging-the-fallen#comments:id=461168:reply=155437
