### ISSUE TITLE
Missing Gunship Event on Enter Instance and Enter Spawn Point 

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#14902]
Commit : https://github.com/TrinityCore/TrinityCore/commit/0b9cd22a6b5a0cca6e3c07dd5ae077ddbdfc3992

Database Version : 335.58

Os Version: Win 8.1 Pro 64

Title says all and here an Image !

![Missing Gunship](http://abload.de/img/screenshot2015-06-170ncrgc.png)

And missing some of Say Texts in ICC ! So any NPC do not Speak ! Speak in form from a Gunship event

**Comment by jackpoz** [comment]
"Fly mode on" means you flew there or you properly reached that place like a normal player would do ?

**Comment by MitchesD** [comment]
well, you are alliance player but you are on the place where should be horde gunship, so there won't never be a gunship if you are on alliance, move around, also you have to kill all previous bosses to be able run gunship battle

**Comment by Killyana** [comment]
I tested both factions and the gunship spawns correctly on rev. f5530c719b71
And I cannot understand what you mean by: "And missing some of Say Texts in ICC ! So any NPC do not Speak ! Speak in form from a Gunship event"
