### ISSUE TITLE
[Crash-6.x]  Bag::RemoveFromWorld (this=0x7fff8d03f000) at /home/wod/TrinityCore/src/server/game/Entities/Item/Container/Bag.cpp:68

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14907]
REV: https://github.com/TrinityCore/TrinityCore/commit/d2142ac380863716ecea6f4aa44f7e556e44dfd9

Link: http://pastebin.com/MZRbY5z4

Thanks.

**Comment by Carbenium** [comment]
Do you have by chance some instructions how to reproduce that crash?

**Comment by Xenon1** [comment]
This may happen for few reason
SELECT `bag` FROM character_inventory ORDER BY bag DESC LIMIT 1;
show me result

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
