### ISSUE TITLE
[Crash-6.x] Levelup  Trinity::Assert (file=file@entry=0x1ca6828 "/home/wod/TrinityCore/src/server/game/DataStores/DBCStores.h", line=line@entry=107, function=function@entry=0x1cb0aa7 <GameTable<gtOCTHpPerStaminaEntry>::EvaluateTable(unsigned int, unsigned int) const::__FUNCTION__> "EvaluateTable", message=message@entry=0x1ca6048 "row < _gtEntry->NumRows") at /home/wod/TrinityCore/src/server/shared/Debugging/Errors.cpp:32

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14905]
Today my colleagues and I have detected the crash that occurs when you try to upload a player over level 100.

REV: https://github.com/TrinityCore/TrinityCore/commit/d2142ac380863716ecea6f4aa44f7e556e44dfd9

Link: http://pastebin.com/6MRMPbPk

Thanks.

**Comment by Vincent-Michael** [comment]
we support current no custom level over 100

**Comment by Darkiu** [comment]
We know but we wanted to know what happens and what we put but if this does not help close and ready.

**Comment by imbavirus** [comment]
This only happens over level 123 for me

**Comment by Shauren** [comment]
Level 123 is the hard cap on level, gt* dbcs do not contain data for stats/ratings/whateverelse above that (some even stop at 100)

**Comment by Carbenium** [comment]
This crash is intented. Do not use levels above 123.
