### ISSUE TITLE
Crash  Object::GetUInt32Value (this=<optimized out>, index=22) at /root/test/3.3.5/src/server/game/Entities/Object/Object.cpp:282

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#14900]
Ubuntu 12.04
d86ff0814526cf1fefb1b37e487d9d414086eead

http://pastebin.com/5G12qiJa

**Comment by Voidx** [comment]
line 3 rc/server/game/Entities/Player/Player.cpp:12251

**Comment by Voidx** [comment]
one more http://pastebin.com/3Ztkz3HP
Crash 2-3 times at day.

**Comment by tkrokli** [comment]
Are you using addons like AntiCheat, Transmogrification or other extra sources?
Your logs are so minimal that all extra information is useful to make sense of your logs.

**Comment by Voidx** [comment]
i put today on full debug, wait for repeat ;)

**Comment by Frytiks** [comment]
Have you use any custom item or custom poison ?

**Comment by Shauren** [comment]
Crashes from comments 1 and 3 are different, I know what is causing http://pastebin.com/3Ztkz3HP and will fix it in near future.

**Comment by Pirricli** [comment]
http://pastebin.com/awuhrSgL

170ba68e63c46323f8624ecff24e6de1d38bd97b

**Comment by Voidx** [comment]
Thanks Shauren and Pirricli, at least im not alone on this xD

**Comment by Voidx** [comment]
any news about it?

**Comment by Voidx** [comment]
New crash today with item: 47733, no enchants.

**Comment by Voidx** [comment]
2015-07-01_13:48:41 [misc] Object::~Object GUID Full: 0x400000000add873a Type: Item Low: 182290234 deleted but still in world!!
2015-07-01_13:48:41 [misc] Item slot 255

Some misc logs befor the crash. 

Item 182290234 entry 47733

**Comment by Voidx** [comment]
Why Object has m_uint32Values = nullptr wen swap item?

**Comment by Voidx** [comment]
Continue crash every 2 hour

**Comment by sirikfoll** [comment]
How to reproduce:
.additem 37198   (http://www.wowhead.com/item=37198)
.go crea id 25478 (for the spell focus)
keep using the item, its 2 charges
crash

http://pastebin.com/NuSd2TTX
rev. 747ea7ca2c2b

**Comment by Keader** [comment]
Confirm this method @sirikfoll 
rev 68e6c95f16dc978066bb957407a1c3bfd4cb8505

**Comment by secreal** [comment]
this kind of bug like bug I found some time ago...
let's try this to reproduce...
find item something like Borean Leather Scraps or other item can be combining without cooldown... http://www.wowhead.com/item=33567
additem 9 of item
click once to create borean leather and then spam click will create the crash?

**Comment by Voidx** [comment]
Some news about this?
