### ISSUE TITLE
[Crash-6.x]  0x0000000001c6dbae in arena_mapbitsp_read (mapbitsp=<optimized out>) at /home/wod/TrinityCore/dep/jemalloc/include/jemalloc/internal/arena.h:525

### ISSUE THREAD

**Issue by Darkiu** [TrinityCore/TrinityCore#14909]
REV: https://github.com/TrinityCore/TrinityCore/commit/d2142ac380863716ecea6f4aa44f7e556e44dfd9

Link: http://pastebin.com/TawXF7Pn

Thanks.

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
Also i suggest to compile without jemalloc.
