### ISSUE TITLE
[ICC] Gunship Opposite Ship 

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#14911]
Hello

The Gunship battle opposite Ship's takes damage before the battle begin,
before the fight start there is 1 min delay to ships their position

in this time opposite ship took damage from cannons

I think this bug exist in all revisions after Battle Gunship implemented

TDB 58
Rev: c544e88437106fb79dba14bbf8469deadb679e8a
Custom Script: AC2 Transmog

**Comment by Shauren** [comment]
Not a bug. This is blizzlike
