### ISSUE TITLE
[6.1.2] Dark Portal Bugged

### ISSUE THREAD

**Issue by Lysander224** [TrinityCore/TrinityCore#14915]
The Dark Portal is green and takes you to Blasted Lands. Also, Blasted Lands appears as it does in MoP. Draenor cannot be entered whatsoever unless you use the .tele command. But when you use that command there are no NPCs.

**Comment by Kinzcool** [comment]
1st: The green Dark Portal is the one of the non-phased zone.
2nd: No NPC's have been added yet on Draenor yet.

**Comment by Lysander224** [comment]
How do I get to the phased zone then?

**Comment by Kinzcool** [comment]
.tele (normal zone's coordinations) 1190.

**Comment by Lysander224** [comment]
I did that and I get ported underneath Hillsbrad.

**Comment by Kinzcool** [comment]
If you got ported under Hillsbrad the position the core received was interpreted as 0 0 0 0

**Comment by Lysander224** [comment]
What should I do to fix this?

**Comment by tkrokli** [comment]
@Lysander224 : Read these pages, then update your main post.
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
http://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Killyana** [comment]
This is handled by terrain_swapping and not phasing, it's not completely implemented, you can just access to the required map by gm command.

**Comment by AriDEV** [comment]
on retail the bronze drake have an gossip option to swap phases for blasted lands :) the npc can be found at the road between the swamp and blasted lands he should levitate there on a rock :) and if u speak to him he have the gossip option depending on the phase if u want travel back to old times or if u want stay in the current time :) @killyana yes u are right its a terrain swap :)
