### ISSUE TITLE
[6.x] Dbc language issue

### ISSUE THREAD

**Issue by burbur** [TrinityCore/TrinityCore#14919]
Using rev: 0d095109eec313c6d0998b2ff19f585d92915bbb

Hi guys. I have a problem with dbc language in game. Tried to do a research but didn't find anything, maybe just used bad keywords. 

I've just extracted the dbc from my client with tc extractor from a fresh compile on the rev i am. 
Seems like he created three subfolders in dbcs: enUs, deDE and itIT. I don't know why i have deDE since i just download the italian package because I'm from Italy. 

Anyway it seems like all the dbcs are deDE version, or a mix between english and deutsch. 
I just tried to opened them with a dbcreader.

This is what i got so far:
Map.
![Map](http://i60.tinypic.com/2v0kikg.png)

Spells.
![Spells](http://i58.tinypic.com/9vgy29.png)

And in game (italian client):
![Chat](http://i59.tinypic.com/t7cz9l.png)

Channels are in deutsch.
At first i thought it was my bad to extract them from the deDE folder but then i just tried to open map.dbc and spell.dbc in all three subfolders (enUS, deDE, itIT) and they are exactly the same. 

I tried to opened it using spellwork (maybe my dbcreader was just bad!) and nothing, i have the deutsch description of the spells. 

In the end I modified the exctrator file on the core to make sure it extracted only the itIT dbc and it did so... but nothing changed. Still deutsch language. 

Am i missing something? Thank you in advance.

**Comment by DDuarte** [comment]
> In the end I modified the exctrator file on the core to make sure it extracted only the itIT dbc and it did so... but nothing changed. Still deutsch language.

Did you delete the cache between your tests?

Can you pastebin a `dir /s` or `ls -Rla` of your extracted dbc folder (the one with enUS/deDE/itIT subdirs)?

**Comment by burbur** [comment]
I deleted the cache and nothing. Only itIT subfolders and deutsch language. With cache and without.

Dir /s: http://pastebin.com/SAA0xGqJ

**Comment by burbur** [comment]
@DDuarte news?

A friend of mine who had not the deDE module could download enUS itIT together and they were in english and italian. I just took them from him but I this is still a problem!

**Comment by Shauren** [comment]
Fixed in 7b5e7e08981838c06db08812c7ab6261e146ecd1
