### ISSUE TITLE
[3.3.5][ICC] Gunship - Kor'kron Battle-Mage 

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14912]
Battle-mage NPC is interruptible by many spells, after interrupt npc will go on evademode

few spells those can interrupt Mage:
Freezing arrow,
Druid feral charge,
bloodelf racial spell (arcane torrent)
warrior pummel,
and ...

TDB 58
Rev: c544e88
Custom Script: AC2 Transmog

**Comment by Runico** [comment]
#11883

**Comment by Keader** [comment]
confirm 170ba68e63c46323f8624ecff24e6de1d38bd97b

**Comment by Killyana** [comment]
It's not a problem with the immunities, but a general issue that happen if the npc is rooted or in forced movement + react passif, this will cause the evade and the script will be stuck.

**Comment by Frytiks** [comment]
Hackfix set non selectable at spawn and remove it on spell cast

**Comment by Goatform** [comment]
Why not to fix it simply in SpellMgr.cpp (just add spells which this npc is casting and add interrupt immunity flags).

**Comment by Nyeriah** [comment]
It's not an immunity issue.
It's not a spell issue.

It's not even related to the mages only but you can get any creature to stuck and not move to their "slot" if you hit them with these spells.

Probably related to how the movement is handled

**Comment by lellonicole** [comment]
@nyeriah Any news?

**Comment by lellonicole** [comment]
Hi, after several attempts I realized that the problem is due to the list threath NPC empty at the time of the cast spell Below Zero.
I hope it is not un'hack, but this fix the problem:

case SLOT_FREEZE_MAGE:
        if (Player* player = me->SelectNearestPlayer(500.0f))
	{
		me->SetInCombatWithZone();
		me->AddThreat(player, 1.0f);
		me->RemoveFlag(UNIT_FIELD_FLAGS, 2);
		DoCastAOE(SPELL_BELOW_ZERO);
	}
        break;

**Comment by Keader** [comment]
is empty because he enter in evade.

**Comment by tkrokli** [comment]
@lellonicole : add ```cpp on the line above your code block (edit your comment).

if you need to add more comment text below it, you can put only the back ticks ``` before adding text.

**Comment by Keader** [comment]
Just override EnterEvadeMode() function solve this issue.
Still is hack, but is more "clean".
Creature enter in evade for some fucked reason, and stop cast because is in evade...
And when Gunship wipe, this creature is despawned... so... he dont need enter in evade in any moment in this fight...

**Comment by tkrokli** [comment]
Nice job, @Keader 👍
