### ISSUE TITLE
[3.3.5] Wintergrasp Interface Timer

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#14913]
The time to start the next Wintergrasp is having problems. Always to log the character (any map) time in the interface is always "In Progress"

![progress](https://cloud.githubusercontent.com/assets/7120913/8253198/c8c04792-1663-11e5-921f-04292791d185.png)

However if the character is in the WG map at some point, the time is updated correctly.

![timer](https://cloud.githubusercontent.com/assets/7120913/8253207/e44c8f02-1663-11e5-8631-ecf56ddb228c.png)

Reproduce: Log a character on a map any. Check the Timer. After that go in Wintergrasp (.tele Wintergrasp) and check the time.

Test on rev. 170ba68e63c46323f8624ecff24e6de1d38bd97b

**Comment by ccrs** [comment]
confirm c544e88437106fb79dba14bbf8469deadb679e8a

**Comment by lainimer** [comment]
confirm https://github.com/TrinityCore/TrinityCore/commit/a29433fbab6e6fe023413af1c9d2d850328f6ac0

**Comment by Keader** [comment]
I can not find the problem. I am not identify what exactly occurs only by entering the Wintergrasp map

**Comment by tkrokli** [comment]
Could it have anything to do with the code in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlefield/BattlefieldMgr.cpp and the references to map/zone or `updateTimer` in that file?
(Sorry that I don't know more about this.)

**Comment by Keader** [comment]
They gave me the tip to start the search for SendUpdateWorldState () in player.cpp
However printing the variables on the island, all look correct. Apparently the update time occurs for something that only occurs when entering the Wintergrasp map. I can not identify what exactly is

**Comment by robinsch** [comment]
```diff

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 275dbf9..8d46cb1 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -9616,13 +9616,9 @@ void Player::SendBattlefieldWorldStates()
     {
         if (BattlefieldWG* wg = (BattlefieldWG*)sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG))
         {
-            if (wg->IsWarTime())
-                SendUpdateWorldState(ClockWorldState[1], uint32(time(NULL)));
-            else // Time to next battle
-            {
-                uint32 timer = wg->GetTimer() / 1000;
-                SendUpdateWorldState(ClockWorldState[1], time(NULL) + timer);
-            }
+            uint32 timer = wg->IsWarTime() ? 0 : wg->GetTimer() / 1000; // 0 - Time to next battle
+            SendUpdateWorldState(ClockWorldState[1], uint32(time(NULL) + timer));
+            SendUpdateWorldState(BATTLEFIELD_WG_WORLD_STATE_ACTIVE, wg->IsWarTime() ? 0 : 1);
         }
     }
 }
```

**Comment by Keader** [comment]
Work :+1:

**Comment by Kittnz** [comment]
Can you PR this @robinsch ?

**Comment by Kittnz** [comment]
I recall that you could only see the state of WG when you were in Northrend. Maybe we need to add a check there.

**Comment by robinsch** [comment]
Well do you have any proofs for your statements?

**Comment by Aokromes** [comment]
Well, as for 6.2.0 robinsch is right.

http://i.imgur.com/lxHUnRC.jpg

But i can't remember 3.3.5a.

**Comment by Kittnz** [comment]
http://wowwiki.wikia.com/Wintergrasp

"To find out when the next battle is starting you can go to the Portal Mage in Dalaran, visit the Zone itself, or view the World Map, which (as of patch 3.1) now displays a countdown timer for the next battle when viewing the Wintergrasp zone. As of patch 3.3.3, this timer is always accessible, whether your character is in one of the Northrend zones or not. Formerly, it would not display if you hadn't been to Northrend since logging in and would display the last known time if you traveled to an area outside of Northrend."

I was right and wrong,

**Comment by Exodius** [comment]
Yes, SS taken as of writing the comment.
![wowscrnshot_062915_151107](https://cloud.githubusercontent.com/assets/817464/8408542/50bfd896-1e71-11e5-8310-c1f12eda1535.jpg)

**Comment by robinsch** [comment]
Also will be correctly displayed after changes in PR #14976

**Comment by Aokromes** [comment]
c8df10d
