### ISSUE TITLE
[6.1.2] Hallows End in June

### ISSUE THREAD

**Issue by Lysander224** [TrinityCore/TrinityCore#14916]
Title explains it all. Hallows end is happening in June.

**Comment by Aokromes** [comment]
supply required details on create ticket before create any new ticket.

**Comment by Lysander224** [comment]
All the hallows end stuff is in Goldshire and Stormwind and the horseman is flying around setting buildings on fire

**Comment by tkrokli** [comment]
@Lysander224 : Read these pages, then update your main post.
http://collab.kpsn.org/display/tc/The+Issuetracker+and+You
http://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by msoky** [comment]
he doesnt understand...
