### ISSUE TITLE
[3.3.5] Divine Shield's immunities.

### ISSUE THREAD

**Issue by JunkyBulgaria** [TrinityCore/TrinityCore#14910]
rev: 91c399cad239b20dac68629587e7c8b4ec612be3
Old issue: #5558

You need 2 characters, a paladin and another one(doesnt matter what it is).
1. Cast Divine Shield on your paladin.
2. Cast Divine Sacrifice / Hand of Sacrifice
3. Get your 2nd non-paladin character in combat or something else to recieve damage.

- The damage from the both spells Divine Sacrifice / Hand of Sacrifice on the paladin won't be immune and will bypass it.

Even huge hacks in Unit::DealDamage to hardcode the damage recieved to 0 didn't help, probably something with spell aura effects releated.

**Comment by robinsch** [comment]
@JunkyBulgaria: This should work.

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 9b0da57..03187b6 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -1780,6 +1780,12 @@ void Unit::CalcAbsorbResist(Unit* victim, SpellSchoolMask schoolMask, DamageEffe
             if (!caster || (caster == victim) || !caster->IsInWorld() || !caster->IsAlive())
                 continue;
 
+            if (caster->IsImmunedToDamage(schoolMask))
+            {
+                victim->SendSpellMiss(caster, (*itr)->GetSpellInfo()->Id, SPELL_MISS_IMMUNE);
+                continue;
+            }
+
             int32 splitDamage = (*itr)->GetAmount();
 
             // absorb must be smaller than the damage itself
@@ -1816,6 +1822,12 @@ void Unit::CalcAbsorbResist(Unit* victim, SpellSchoolMask schoolMask, DamageEffe
             if (!caster || (caster == victim) || !caster->IsInWorld() || !caster->IsAlive())
                 continue;
 
+            if (caster->IsImmunedToDamage(schoolMask))
+            {
+                victim->SendSpellMiss(caster, (*itr)->GetSpellInfo()->Id, SPELL_MISS_IMMUNE);
+                continue;
+            }
+
             uint32 splitDamage = CalculatePct(dmgInfo.GetDamage(), (*itr)->GetAmount());
 
             (*itr)->GetBase()->CallScriptEffectSplitHandlers((*itr), aurApp, dmgInfo, splitDamage);
```

**Comment by tkrokli** [comment]
@robinsch : you are good at delivering code diffs as solutions to a lot of issues. It would be awesome if you were able to create PRs for them as well, but your current 3.3.5 repository is not quite in shape to produce a PR based on independent changes. Can I offer you some assistance in setting up your local source copy on your own computer and show you how to sync separate branches for each change between your computer and your github repository, so they can be used in real PRs under your control?
I'm happy to help you, if you have got the time and feel OK about receiving some help from me. :smirk:

**Comment by JunkyBulgaria** [comment]
Working fine.

**Comment by JunkyBulgaria** [comment]
It is semi-working now, still doesn't reduce the damage taken of the victim.

**Comment by JunkyBulgaria** [comment]
Temp solution to remove the damage taken(if someone needs it):
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index a816883..ecebbc8 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -1863,6 +1863,9 @@ void Unit::CalcAbsorbResist(Unit* victim, SpellSchoolMask schoolMask, DamageEffe
 
             SendSpellNonMeleeDamageLog(caster, (*itr)->GetSpellInfo()->Id, splitted, schoolMask, splitted_absorb, 0, false, 0, false);
 
+			if (caster->HasAura(642))
+				splitted = 0;
+
             CleanDamage cleanDamage = CleanDamage(splitted, 0, BASE_ATTACK, MELEE_HIT_NORMAL);
             DealDamage(caster, splitted, &cleanDamage, DIRECT_DAMAGE, schoolMask, (*itr)->GetSpellInfo(), false);
         }
@@ -1901,6 +1904,9 @@ void Unit::CalcAbsorbResist(Unit* victim, SpellSchoolMask schoolMask, DamageEffe
             uint32 split_absorb = 0;
             DealDamageMods(caster, splitted, &split_absorb);
 
+			if (caster->HasAura(642))
+				splitted = 0;
+
             SendSpellNonMeleeDamageLog(caster, (*itr)->GetSpellInfo()->Id, splitted, schoolMask, split_absorb, 0, false, 0, false);
 
             CleanDamage cleanDamage = CleanDamage(splitted, 0, BASE_ATTACK, MELEE_HIT_NORMAL);

```

**Comment by robinsch** [comment]
@JunkyBulgaria: Can you explain it better? Should the damage still be reduced by 30%?

**Comment by Frytiks** [comment]
@robinsch Can this break something ? @JunkyBulgaria is for me safe way.

**Comment by robinsch** [comment]
@Frytiks No.

**Comment by JunkyBulgaria** [comment]
@Frytiks it might be 'safer' way but it's still a hack, the damage is 'miss' instead of immune also it's wrong way to fix it.

**Comment by robinsch** [comment]
My solution is safe, it will not break anything else and is the correct fix for this bug.

**Comment by L30m4nc3r** [comment]
After https://github.com/TrinityCore/TrinityCore/commit/2263cb9e1015ed0f6dbf83b63d8f0332bcbe6205
Not work spell reflect. Use haos bolt in spell reflect. Damage absorb.
