### ISSUE TITLE
[6.x] Phase system

### ISSUE THREAD

**Issue by vinin80** [TrinityCore/TrinityCore#14927]
Hi
Phase system only works if you change phase with command (.npc set phase). If you turn off server  after this change this doesn't work because i think phase is not loaded when server start.. sorry for my bad english

Rev 881ebcc

**Comment by thomas33** [comment]
confirm

**Comment by MitchesD** [comment]
Describe it more, which phase did you try to set? Are you sure that you are in the right phase you should be? Tell us more, it's hard to understand this issue without any proper info or way how to reproduce.

**Comment by vinin80** [comment]
spawn npc 34916
then change phase to 2 and it work but restart server and this doesn't work

**Comment by MitchesD** [comment]
How it does not work? You can't see the NPC or where is the problem? Nps has back the default phase (not 2) or what?

**Comment by vinin80** [comment]
back to default phase.... i think because i can see him in gm off (phase 1)

**Comment by vinin80** [comment]
spawn npc then change his phase to 2 and you can't see him in gm off ... but when you restart server you can see him

**Comment by MitchesD** [comment]
How did you spawn NPC? With command or with DB?

**Comment by vinin80** [comment]
in DB and with command.. is this same result

**Comment by Aokromes** [comment]
There is no phase 1 or phase 2 on 6.x branch, that's why your phase 2 is reverted.

**Comment by Killyana** [comment]
You can use this:
``` sql
| PhaseMask | PhaseID |
|         1 |     169 |
|         2 |     170 |
|         4 |     171 |
|         8 |     172 |
|        16 |     173 |
|        32 |     174 |
|        64 |     175 |
|       128 |     176 |
|       256 |     177 |

**Comment by Vincent-Michael** [comment]
https://gist.github.com/Vincent-Michael/a9734a85c9bd7420d15d

**Comment by Rushor** [comment]
anyone already tested the corescript?

**Comment by Aokromes** [comment]
Any new on this?
