### ISSUE TITLE
[3.3.5][6.x] Calendar events cap

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#14923]
- [ ] Implement cap of 30 events for player
- [ ] Implement cap of 100 events for guild
- [ ] Autodelete old events that are older than 30 days
- [ ] An event can be created only every 5 seconds

**Comment by Aokromes** [comment]
Any new on this?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fb059722fdb18a94d47b3f44a5b2d7f183bf5a29
