### ISSUE TITLE
[3.3.5] Core/npc: Invisible npcs on their mounts after the respawn

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#14926]
Rev: a35ec4c35a28b45
Npcs with visual mount form creature_addon or creature_template_addon turn invisible after respawn, this happen only if the same model is reloaded, in the case which the npc get a different model from the one when it dies, it doesn't turn invisible.
How to reproduce:
- Spawn the npc 16843
- Kill it and respawn it (do this many times)

You will notice that the npc have 4 model (human, dwarf, male or female) in the case the same model is loaded in respawn the npc will turn invisible 2 secs after the respawn, and if he get a different model he will not turn invisible.
If you aggro the npc when it's invisible then ".gm on" he will evade and load the model, he will turn visible.

This issue is not related to any recent commit, I can reproduce in an old revision before Boost migration.

**Comment by jackpoz** [comment]
Relogging or going out of visibility range make the npc appear correctly, while players still in range keep not seeing the npc

**Comment by jackpoz** [comment]
tested with 2 players, 1 gm on, 1 gm off:
- .die, wait for corpse to disappear for gm off, then respawn
- gm off sees the npc correctly, gm on sees only the horse

to me it's because client receives at same time "remove npc" + "add npc" . this looks like a bug that happens only to .gm on characters

**Comment by Wyrserth** [comment]
Cannot reproduce with either GM state. Probably fixed as a consequence of dynamic spawns.
