### ISSUE TITLE
[6.x] Rogue's combo points

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14925]
Hi!
When you strike with Rogue's ability who add you a combo points, it's not adding to your target! So you can't use that abilities wich need combo points.

Rev: https://github.com/TrinityCore/TrinityCore/commit/530074f453c568dc4065994ad908d3bfc7388534

**Comment by Sar777** [comment]
#14680

**Comment by Killyana** [comment]
Duplicated.
