### ISSUE TITLE
[6.x] Heroes Call quests

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14929]
Hi!
It's something wrong with these quests, when you enter to the ship who transports you to Northrend (or Vashir), the server is crashing and you cant log in with the character who is in the boat, or that re-crashes the server.

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by Shauren** [comment]
1. No crash log
2. Even if, this would not be a quest related issue.
