### ISSUE TITLE
[Crash]  VMAP::StaticMapTree::LoadMapTile

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#14921]
Rev: c544e88
TDB 58
Custom Scripts: Transmog - AC2
http://pastebin.com/SFxZSVt8

**Comment by jackpoz** [comment]
please try after https://github.com/TrinityCore/TrinityCore/commit/ca7f31c6cdceb7e2921d5d83e1ae22ccb247988d

**Comment by jackpoz** [comment]
no further feedback, it could be the commit above fixed the issue
