### ISSUE TITLE
[6.x] Warrior Shouts

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14931]
Hi!
The 2 shout can active at same time.
- Commanding Shout (ID: 469),
- Battle Shout (ID: 6673).

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by blindspell** [comment]
u can hack fix it from spell_linked spells
when 469 remove 6673
and vice versa

**Comment by AlcDenat** [comment]
Like that?

```
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=6673 AND `spell_effect`=-469;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (6673, -469, 0, "Battle Shout removes Commanding Shout");

DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=469 AND `spell_effect`=-6673;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (469, -6673, 0, "Commanding Shout removes Battle Shout");

**Comment by Ayik0** [comment]
better to do it via spell_stack_rules

INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES (2500, 2);
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES (2500, 6673);
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES (2500, 469);

**Comment by tkrokli** [comment]
@Ayik0 : just to improve a little on your suggestion, to follow the TC code style and make it repeatable:
```sql
-- 
DELETE FROM `spell_group_stack_rules` WHERE `group_id`= 2500 AND `stack_rule`= 2;
INSERT INTO `spell_group_stack_rules` (`group_id`,`stack_rule`) VALUES (2500, 2);

DELETE FROM `spell_group` WHERE `id`= 2500 AND `spell_id` IN (469,6673);
INSERT INTO `spell_group` (`id`,`spell_id`) VALUES
(2500, 469), -- Commanding Shout
(2500, 6673); -- Battle Shout

**Comment by Rushor** [comment]
if someone confirm, that the fix is working, it can be pushed @Ayik0 @AlcDenat @Atis6

**Comment by Aokromes** [comment]
any new on this?

**Comment by tkrokli** [comment]
Sorry, I have not had time to test this nor find out what the values are before and after using the SQL.
Like Rushor said, it would be better if the original participants of this issue could test it and confirm 
( @Atis6 , @blindspell , @AlcDenat , @Ayik0 ).

**Comment by P-Kito** [comment]
Needs revert, this was not a fix for Legion. These spells are deprecated in Legion.
