### ISSUE TITLE
[6.x] Priest's Chakras

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14932]
Hi!
The Holy Priest can activate all the 3 chakras at same time:
- Chakra: Sanctuary (ID: 81206),
- Chakra: Serenity (ID: 81208),
- Chakra: Chastise (ID: 81209).
Pic: http://i.imgur.com/h35pSt1.jpg

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by Killyana** [comment]
Duplicated: https://github.com/TrinityCore/TrinityCore/issues/14559
