### ISSUE TITLE
[3.3.5a] Lich King's defile chasing pets (25HC only)

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#14936]
REV a35ec4c

Hiho. As in the topic - when we're summoning any pet while fighting LK, defile is MOVING.

Happens only on 25HC. Same issue with missing Val'kyr's - they're not spawning on 25HC only (but yes, I'll create a new issue ;>)

Any idea?

**Comment by MitchesD** [comment]
duplicate
https://github.com/TrinityCore/TrinityCore/issues/14897
