### ISSUE TITLE
[6.x] Lightwell

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14933]
Hi!
When you casts the holy priest's Lightwell spell (ID: 724) you summoning a "cube", not a lightwell; and you can't use that to get Lightwell's HOT effect.
Pic: http://i.imgur.com/h35pSt1.jpg

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by Aokromes** [comment]
duplicate.

**Comment by Atis6** [comment]
But it's [4.3.4] branch what i found an issue.

**Comment by DDuarte** [comment]
#13685 updated.

P.S I have a dream that one day every issue that is closed as "duplicate" will have a link to the duplicated issue.

**Comment by Atis6** [comment]
Sorry guys.

**Comment by DDuarte** [comment]
@Atis6: my last comment was for Aokromes, not you :P

**Comment by Atis6** [comment]
Ohh :D than sorry once again XD

**Comment by tkrokli** [comment]
This issue was a duplicate of #13685 (sort of). DDuarte has adjusted #13685 for use with 6.x .
