### ISSUE TITLE
[6.x] Mind Blast

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14930]
Hi!
If you cast Mind Blast (spell id : 8092), you get 3 Shadow Orbs instead of 1.

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by Killyana** [comment]
Patch 7.0.3 (2016-07-19): Removed, replaced by Insanity system.
