### ISSUE TITLE
[6.x] Dungeons / Raids

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#14934]
Hi!
When you trying to enter to any dungeon / raid, you get this message (norm and HC too): 
"You are already locked to XY." But in GM mode you can enter.

- I have no any ID to dungs / raids (tested '.i u all' command too),
- After server restart doing this too ,when i never been at that dung / raid.

Rev: https://github.com/TrinityCore/TrinityCore/commit/881ebccdc4a0995732aea2052f85015aebe6f9a2

**Comment by MitchesD** [comment]
Which dungeon/raid did you try? I tried to enter Nexus without any problems

**Comment by Atis6** [comment]
Grim Batol, Iron Docks

**Comment by Atis6** [comment]
I've tried to enter Nexus, i cannot enter. It says: 
"You are already locked to The Nexus ."

Ehm ... some config isn't good for us?

**Comment by Atis6** [comment]
Hmmm ... i think my account is bugged. I've created a player account, i've tried with that, i can enter to dungeons. 
I think this can be closed.
