### ISSUE TITLE
[6.x] Scenarios provoking a server crash

### ISSUE THREAD

**Issue by vvizard100** [TrinityCore/TrinityCore#14948]
What steps will reproduce the problem?
Teleport to any scenario (for instance, .go 0 0 0 1051)

What is the expected output? What do you see instead?
You're supposed to get teleported into scenario maps (Brewmoon Festival Scenario if you take the MapID I gave you)
Worldserver.exe crash right before getting in game, during the loading screen.

What version of the core and database are you using? On what operating system?
Core Rev : https://github.com/TrinityCore/TrinityCore/commit/acc45bcf5d657671d9348e95f069ad17e1bb5631
DB Rev : latest available
OS : Windows 8.1

Please provide any additional information below.
Crashlog: http://pastebin.com/H7nDXWm5

**Comment by DDuarte** [comment]
Can you paste line 22585 of Player.cpp? It seems it's slightly different on HEAD...

**Comment by vvizard100** [comment]
well, I've got this: worldServerInfo.IsTournamentRealm = 0; /// @todo

**Comment by DDuarte** [comment]
That's not the line of the crash tho.

**Comment by vvizard100** [comment]
very interesting, thank you for this fast answer DDuarte ;)
imma trying some stuff right now :p

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
