### ISSUE TITLE
[3.3.5] Slow speed while casting

### ISSUE THREAD

**Issue by Spectrance** [TrinityCore/TrinityCore#14942]
Hi everyone

when the use spells (Hamstring, high-pitched whine, Crippling Poison, Chains of Ice, Ice Arrow, Concussive Shot, etc.)

standard running slow

when the use of GM code works correctly

relog after running standard

Rev  3600751

**Comment by DDuarte** [comment]
Now in English, please.

**Comment by tkrokli** [comment]
Also, Spectrance is using a quite old core revision from 2015-03-21 (launch of TDB 335.58).
Upgrading to a more recent core is recommended, preferably from this month.

**Comment by Spectrance** [comment]
All this spells exactly right does not reduce the speed of movement

even from old revs  to this version
