### ISSUE TITLE
[crash] .cast 54438

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#14953]
.cast 54438 is causing a crash on https://github.com/TrinityCore/TrinityCore/commit/e34f74dacea82f85b3b945e23f3432deda4595b7 Win x64 , no custom patches

Debug crash log at https://gist.github.com/jackpoz/d0ec74ff7b92d6b86278
Probably related to https://github.com/TrinityCore/TrinityCore/pull/14860

**Comment by mik1893** [comment]
sorry, did you try it from .cast, so not in the instance, isnt it?

**Comment by jackpoz** [comment]
On the PR someone pointed out that the ToCreature() check is unneeded if the object is a Unit, you can get the threatmanager object from Unit too
