### ISSUE TITLE
Certain auth tables don't exist

### ISSUE THREAD

**Issue by Kakarrott** [TrinityCore/TrinityCore#14950]
I've been trying to start my own server today and I've followed the wiki step by step and haven't had an issue up until I have to run the authserver and worldserver apps.
I've looked through everything I can and can't seem to find anything with similar problems so anyhelp would be appreciated.

An example of what I'm getting is;
In mysql_stmt_prepare() id: 1, sql: "DELETE FROM ip_banned WHERE unbandate<>bandate AND unbandate<=UNIX_TIMESTAMP()"
Table 'auth.ip_banned' doesn't exist

There are 41 of these errors in total and they seem to be the same in both authserver and worldsever logs.

**Comment by DDuarte** [comment]
Setting up auth db is a simply:

```bash
mysql -e 'CREATE DATABASE auth'
mysql auth < /sql/base/auth_database.sql
```

**Comment by bobsort** [comment]
I have the same issue, it happened after I upgraded MySql server to 5.6

Connected to MySQL database at 127.0.0.1
In mysql_stmt_prepare() id: 1, sql: "DELETE FROM ip_banned WHERE unbandate<>bandate AND unbandate<=UNIX_TIMESTAMP()"
Table 'auth.ip_banned' doesn't exist
In mysql_stmt_prepare() id: 4, sql: "INSERT INTO ip_banned (ip, bandate, unbandate, bannedby, banreason) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, 'Trinity Auth', 'Failed login autoban')"
Table 'auth.ip_banned' doesn't exist
In mysql_stmt_prepare() id: 8, sql: "INSERT INTO account_banned VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, 'Trinity Auth', 'Failed login autoban', 1)"
Table 'auth.account_banned' doesn't exist
In mysql_stmt_prepare() id: 9, sql: "DELETE FROM account_banned WHERE id = ?"
Table 'auth.account_banned' doesn't exist
In mysql_stmt_prepare() id: 11, sql: "UPDATE account SET v = ?, s = ? WHERE username = ?"
Table 'auth.account' doesn't exist
In mysql_stmt_prepare() id: 15, sql: "UPDATE account SET failed_logins = failed_logins + 1 WHERE username = ?"
Table 'auth.account' doesn't exist
In mysql_stmt_prepare() id: 23, sql: "INSERT INTO ip_banned (ip, bandate, unbandate, bannedby, banreason) VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, ?, ?)"
Table 'auth.ip_banned' doesn't exist
In mysql_stmt_prepare() id: 24, sql: "DELETE FROM ip_banned WHERE ip = ?"
Table 'auth.ip_banned' doesn't exist
In mysql_stmt_prepare() id: 28, sql: "INSERT INTO account_banned VALUES (?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+?, ?, ?, 1)"
Table 'auth.account_banned' doesn't exist
In mysql_stmt_prepare() id: 29, sql: "UPDATE account_banned SET active = 0 WHERE id = ? AND active != 0"
Table 'auth.account_banned' doesn't exist
In mysql_stmt_prepare() id: 30, sql: "DELETE FROM realmcharacters WHERE acctid = ? AND realmid = ?"
Table 'auth.realmcharacters' doesn't exist
In mysql_stmt_prepare() id: 31, sql: "DELETE FROM realmcharacters WHERE acctid = ?"
Table 'auth.realmcharacters' doesn't exist
In mysql_stmt_prepare() id: 32, sql: "INSERT INTO realmcharacters (numchars, acctid, realmid) VALUES (?, ?, ?)"
Table 'auth.realmcharacters' doesn't exist
In mysql_stmt_prepare() id: 33, sql: "SELECT SUM(numchars) FROM realmcharacters WHERE acctid = ?"
Table 'auth.realmcharacters' doesn't exist
In mysql_stmt_prepare() id: 35, sql: "INSERT INTO realmcharacters (realmid, acctid, numchars) SELECT realmlist.id, account.id, 0 FROM realmlist, account LEFT JOIN realmcharacters ON acctid=account.id WHERE acctid IS NULL"
Table 'auth.realmcharacters' doesn't exist
In mysql_stmt_prepare() id: 36, sql: "UPDATE account SET expansion = ? WHERE id = ?"
Table 'auth.account' doesn't exist
In mysql_stmt_prepare() id: 37, sql: "UPDATE account SET locked = ? WHERE id = ?"
Table 'auth.account' doesn't exist
In mysql_stmt_prepare() id: 38, sql: "UPDATE account SET lock_country = ? WHERE id = ?"
Table 'auth.account' doesn't exist
In mysql_stmt_prepare() id: 39, sql: "INSERT INTO logs (time, realm, type, level, string) VALUES (?, ?, ?, ?, ?)"

**Comment by Aokromes** [comment]
or you deleted your database or you selected bad database.

**Comment by bobsort** [comment]
The problem is missing/invalid/corrupted innodb file ibdata1 from mysql data folder. It seems mysql installer overwrites the existing file. I overwrite the ibdata file from my backup and everything is back to normal

**Comment by tkrokli** [comment]
@bobsort : this issue is still closed since DDuarte closed this on 25 Jun (see post 2 on this page).
