### ISSUE TITLE
[3.5.5a] Healing in Battleground's

### ISSUE THREAD

**Issue by Hopelessbear** [TrinityCore/TrinityCore#14957]
"All healing abilities (including items such as potions) will be decreased in effectiveness by 10% when in Battlegrounds, Arenas, or Wintergrasp." This was added in Patch 3.3.2. But it doesnt work. Any ideas?

**Comment by mik1893** [comment]
if (count > 6)
                addhealth *= (6.0f / count);
        }

+		// Reduce Healing in Bg or Arena
+        if (m_caster->ToPlayer())
+        {
+            if (m_caster->ToPlayer()->InBattleground() || m_caster->ToPlayer()->InArena())
+                addhealth *= 0.9f;
+        }
		
        m_damage -= addhealth;

In Spell::EffectHeal

**Comment by Rushor** [comment]
check spell_area in the bg/areas - maybe your are missing a db-update

Also read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md
and give us your rev.

https://code.google.com/p/trinitycore/issues/detail?id=2811

**Comment by Nyeriah** [comment]
WorksForMe(tm)

**Comment by P-Kito** [comment]
@mik1893 Even tho it would cover all the heals, it does not reduce absorb

**Comment by mik1893** [comment]
i think the shitty code i posted I used in some very old stuff. it looks like it's working on my 3.3.5

**Comment by joschiwald** [comment]
spell 74410, 74411 in spell_area should handle this

**Comment by P-Kito** [comment]
Are these Auras applied already?

**Comment by Rushor** [comment]
yes they are always applied on you if you join the bg/arena on cleantc
