### ISSUE TITLE
No Hearthstone

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#14959]
In TrinityCore rev. 0cba5558cf11+ 2015-06-24 11:05:36 +0200 (3.3.5 branch) (Unix, Release), Hearthstone don't work. we can speak to innkeeper, but location don't change and, if we delete item, innkeeper don't give it.

TrinityCore rev. 0cba5558cf11+ 2015-06-24 11:05:36 +0200 (3.3.5 branch) (Unix, Release)

**Comment by Aokromes** [comment]
.gm off

**Comment by Keader** [comment]
work for me on rev accab5451d3e62739e4aa376d25bc6623f0d3c52
Probably the "ALT" key on your keyboard was pressed, causing this problem

**Comment by martial69320** [comment]
0_o ty Aokromes, don't know that with trinitycore, with old version, there was not that ^^
