### ISSUE TITLE
[3.3.5][Spell] Jagged Knife 

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#14966]
rev: https://github.com/TrinityCore/TrinityCore/commit/7c01638d45b3eaed7af124a43f21cc6d15407667

How it is:
npc=29836 cast http://wotlk.openwow.com/spell=55348 and http://wotlk.openwow.com/spell=55521
Both Spellvisuals look like cubes.
Proof:
http://i.imgur.com/WOm9mvj.jpg

How it should be:
Both Spellvisuals should look like knifes

**Comment by Aokromes** [comment]
Confirmed, really really ancient bug.

**Comment by Trisjdc** [comment]
The cause of the bug is SMSG_SPELL_GO missing CAST_FLAG_AMMO on the cast flags for this spell. I'm not aware of a general solution...

**Comment by Kinzcool** [comment]
The spellvisuals look like cubes because no path is set for a model in SpellVisual.dbc. That being said, all the ones having a spell visual with no path set is going to have this problem.

``sql
(8908, "<Ammo - Basic>", "", 1, 1, 0.01, 100, 4, 1, 0);
(8909, "<Ammo - Preferred>", "", 1, 1, 0.01, 100, 5, 1, 0);
``

**Comment by Rushor** [comment]
maybe all these ones have the same spelliconid?

**Comment by Rushor** [comment]
one more spell=55550  maybe a more generic solution can  be found with the data of these 3

**Comment by Kinzcool** [comment]
My comment above is your generic pattern to find all the spells that will have their spellvisuals represented as cubes.

**Comment by Rushor** [comment]
oh and @Trisjdc, the hack sadly does not work :(

**Comment by Rushor** [comment]
@Treeston concernig the pr, maybe you can try to add the attribute to all spells which look like freaking cubes :>

**Comment by Treeston** [comment]
@Rushor feel free to, it's merged into mainline 3.3.5 now.

**Comment by Rushor** [comment]
thx :)
