### ISSUE TITLE
[Spell] Using a spell with a taunt effect on a player

### ISSUE THREAD

**Issue by chaodhib** [TrinityCore/TrinityCore#14968]
When using a spell with a taunt effect (example 6795, druid's Growl)  on a player:
a) It should say "Immune" above the head the of player.
b) The player shouldn't have the debuff "Taunted" applied to him.

![screenshot](http://i.imgur.com/Df3kRAe.jpg)

I tried to look at the code and modifying AuraEffect::HandleModTaunt() seems to be ineffective. The debuff is already applied when this method is reached.

An AuraScript could be used but, if i'm not mistaken, this imply to connect this script to every spell that has a Taunt effect. Isnt there any other solution?

edit: example on retail: https://www.youtube.com/watch?v=BYK6OkFwbv8 at 3:27. The dk death grip a rogue. a) immune above his head. b) no debuff with the Death Grip icon.

CORE revision number: https://github.com/TrinityCore/TrinityCore/commit/accab5451d3e62739e4aa376d25bc6623f0d3c52 (branch 3.3.5a, 26/06/15)
TDB 335.58 +updates up until 2015_06_26_02_world.

**Comment by mik1893** [comment]
source for your issue? I mean, any video / proof from retail?

**Comment by Goatform** [comment]
If I remember good, players are immune on taunt effects.

**Comment by Keader** [comment]
Players take taunt seems wrong to me

**Comment by Goatform** [comment]
Of course they will auto-target you because you casted spell on player and he doesn't have a target, try to reproduce that when player have a target and then use taunt, if player switch targets then it's high issue, but mostly like it's just visual as I said.

**Comment by chaodhib** [comment]
a) is mostly cosmestic yes.
However b) is important imo. A useless debuff like that is bad.

**Comment by emptyus** [comment]
Researching this issue can maybe reveal some other core problems. Like that one that screws up phases on LK encounter using taunt. I doubt its purely cosmetic issues or visual...

**Comment by Goatform** [comment]
That isn't same issue. PvE and PvP system are different as you know.

**Comment by chaodhib** [comment]
@Goatform this isnt about the player changing his target. It's about immunity to the spell effect and to the debuff.

**Comment by Goatform** [comment]
Yeah I understood you very well.

**Comment by Mack36** [comment]
The same thing is with warrior's Mocking Blow (spellId 694). It shouldn't deal damage to a player (due to description).

**Comment by Goatform** [comment]
Mocking Blow - " If the target is tauntable, also deals weapon damage." 

Yeah I think that you're right. player(s) should be immune on taunt effects.

**Comment by robinsch** [comment]
```diff

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index b9d4650..232bb45 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -11173,6 +11173,9 @@ bool Unit::IsImmunedToSpellEffect(SpellInfo const* spellInfo, uint32 index) cons
             if (((*iter)->GetMiscValue() & spellInfo->GetSchoolMask()) &&  // Check school
                 !spellInfo->IsPositiveEffect(index))                                  // Harmful
                 return true;
+
+        if (aura == SPELL_AURA_MOD_TAUNT && GetTypeId() == TYPEID_PLAYER)
+            return true;
     }
 
     return false;
```

**Comment by Goatform** [comment]
I didn't tested it but I think that it could break spells such as Death Grip since it has taunt effects as well.

**Comment by chaodhib** [comment]
I've tested it and it seems to work: there is no more debuff (and the pull element of death grip is still working fine). However, there is no mention on why the spell effect failed in the combat log ("spell XXX on target YYYY failed because the target is immune") and no "immune" showing up above the spell's head.

So, this is a quick fix but it's un-blizzlike.

It has been said on IRC that the problem is maybe caused by the fact that core doesn't yet support immunity on spell effect. It only supports immunity on spell. I don't understand well enough the core to give more detail. Could a dev with more experience care to comment?

**Comment by robinsch** [comment]
As you already stated the core does not support spell effect results. I could easily implement the IMMUNE message.

**Comment by chaodhib** [comment]
I tested it. Doest not work.

**Comment by robinsch** [comment]
Wooops, @chaodhib try this:

```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 30c02db..5b90124 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -2021,10 +2021,17 @@ void Spell::AddUnitTarget(Unit* target, uint32 effectMask, bool checkIfValid /*=
         if (m_spellInfo->CheckTarget(m_caster, target, implicit) != SPELL_CAST_OK)
             return;
 
+    bool sendEffectImmune = false;
     // Check for effect immune skip if immuned
     for (uint32 effIndex = 0; effIndex < MAX_SPELL_EFFECTS; ++effIndex)
         if (target->IsImmunedToSpellEffect(m_spellInfo, effIndex))
+        {
+            if (!sendEffectImmune)
+                m_caster->SendSpellMiss(target, m_spellInfo->Id, SPELL_MISS_IMMUNE);
+
+            sendEffectImmune = true;
             effectMask &= ~(1 << effIndex);
+        }
 
     ObjectGuid targetGUID = target->GetGUID();
 
```

**Comment by chaodhib** [comment]
Getting closer. However, the "immune" message appears several times now. AddUnitTarget() is being called multiple times. this number is equal to the number of spell effects the spell has.

Meaning if I use the druid or warrior's taunt (6795 & 355 respectively), since those spells have only 2 spell effects, AddUnitTarget() is called 2 times (with spell effect mask equals 1 and 2) and the "immune" message is shown 2 times.

if I use the dk's taunt (death grip 49560), the spell has 3 spell effects and AddUnitTarget() is called 3 times (with spell effect mask equals to 1, 2 and 4).

here is the call stack:
![call stack](http://i.imgur.com/cKVqpVt.png)

In most functions that calls AddUnitTarget(), the mask is actually used as a simple index (only one bit set to 1 defined by `mask = 1 << effIndex;`). The only exception is `void Spell::SelectEffectImplicitTargets(SpellEffIndex effIndex, SpellImplicitTargetInfo const& targetType, uint32& processedEffectMask)`. 

If I'm not mistaken, this means:
a) further optimisation could be possible by using the mask as an actual mask

**Comment by chaodhib** [comment]
Getting closer. However, the "immune" message appears several times now. AddUnitTarget() is being called multiple times. this number is equal to the number of spell effects the spell has.

Meaning if I use the druid or warrior's taunt (6795 & 355 respectively), since those spells have only 2 spell effects, AddUnitTarget() is called 2 times (with spell effect mask equals 1 and 2) and the "immune" message is shown 2 times.

if I use the dk's taunt (death grip 49560), the spell has 3 spell effects and AddUnitTarget() is called 3 times (with spell effect mask equals to 1, 2 and 4).

here is the call stack:
![call stack](http://i.imgur.com/cKVqpVt.png)

In most functions that calls AddUnitTarget(), the mask is actually used as a simple index (only one bit set to 1 defined by `mask = 1 << effIndex;`). The only exception is `void Spell::SelectEffectImplicitTargets(SpellEffIndex effIndex, SpellImplicitTargetInfo const& targetType, uint32& processedEffectMask)` where the mask is actually used as a mask in very few specific cases (there might be room for optimisation here).

In any case, your code in AddUnitTarget() needs to be sightly changed:

````C++
    // Check for effect immune skip if immuned
    for (uint32 effIndex = 0; effIndex < MAX_SPELL_EFFECTS; ++effIndex)
    {
        if (effectMask & 1 << effIndex && target->IsImmunedToSpellEffect(m_spellInfo, effIndex))
        {
            m_caster->SendSpellMiss(target, m_spellInfo->Id, SPELL_MISS_IMMUNE);
            effectMask &= ~(1 << effIndex);
        }
    }
````
`effectMask & 1 << effIndex &&` to take into account what I said above. And I removed the boolean stuff since the immunity should show up 2 times if the target is immune to two of the spell effect.

**Comment by chaodhib** [comment]
Could someone confirm/infirm with proof that 2 immune messages can show up to one spell? for example if the target is under ice block or divine shield and if the spell used has more than one spell effect that will affect the target.

if this is confirmed and if I'm not mistaken, it means immunity checks should only be done when handling the spell effects and not before that.

**Comment by chaodhib** [comment]
This is completely wrong. Abort mission. I repeat: Abort Mission. It seems like there is no such thing as spell effect hit results. Meaning, the only way a "immune" can show up is if the target is immune to the entire spell (which is the current behavior AFAIK).

Dk's death grip is basically 2 spells chained together (actually 3 but only 2 are relevant here), which explains the odd case of double "immune" showing up.

**Comment by chaodhib** [comment]
Fixed?
