### ISSUE TITLE
[3.3.5][6.x] Duel Groupsupport

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#14967]
Rev: https://github.com/TrinityCore/TrinityCore/commit/a29433fbab6e6fe023413af1c9d2d850328f6ac0

**Steps to reproduce:**
1. Create a DK/Paladin
2. Create 2 other players (for example a Mage and a Priest)
3. Put the Paladin and 1 player in the same group (for example Paladin and Mage)
4. Start a duel between the Mage and the Priest
5. Cast (with the Paladin) Divine Sacrifice on the Mage
6. Divine sacrifice should not affect the Mage because this one is dueling, not only the buff will be applied, also the effect (so Mage will receive less damage, and 30% of the damage will be redirected to the Paladin)

The same happens with Anti-Magic Zone, I don't know if there are more spells, probably yes, I haven't found them yet.

**Comment by robinsch** [comment]
I think this was possible on retail too. Please post a proof.

**Comment by Goatform** [comment]
I don't think so @robinsch. It shouldn't affect player(s) which are dueling.

**Comment by Raydor** [comment]
Can't find a proof, too hard :/, I reported that because it shouldn't work like that, don't know if is working as intended or not, didn't think of it.

**Comment by Raydor** [comment]
It also happens with Devour Magic.

If you are in the same party with someone that is dueling, you can cast Devour Magic to him:

![](http://puu.sh/jwnpl/cb6d677103.jpg)
![](http://puu.sh/jwnpP/dd1ed60ca5.jpg)

I doubt this was possible to do in retail

**Comment by Rushor** [comment]
can you test if this affects some totembuffs too?

**Comment by Raydor** [comment]
It does for some totems (for example Frost Resistance totem), the player also have the buff from Grounding totem, but it doesn't redirect spells.

**Comment by StormBytePP** [comment]
While in a duel, in retail, you can't interact **in any way** with involved players.

**Comment by Raydor** [comment]
Well then... this is a huge issue xD.

**Comment by StormBytePP** [comment]
What I don't remember (some time has passed without me dueling), is that if retail prevents you from casting, or you cast it but it has no effect

**Comment by yashirotcm** [comment]
Confirming this aswell, so can this be considered a bug or not?

**Comment by Rushor** [comment]
updated to a more gerneral one, to conclude the issue that must be fixed here, i would like to repeat the stormbyte:

> While in a duel, in retail, you can't interact in any way with involved players from outside
> So summary: You can't interact from outside with dueling players from your same faction

This issue concerns many spells

**Comment by tkrokli** [comment]
Has this issue been tested on TC source without being in group/party with any of the duelling players? Could the issue be related to group/party mechanics, that the group membership mechanics override the duelling player mechanics in TC source?

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.

**Comment by imstuckbro** [comment]
both examples no longer valid in e8980df1896616b8379535efd3ee16e0381fc0f5.
