### ISSUE TITLE
Crash Unit::RemoveAurasByType

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#14978]
391c81d86cd890801dd74d41685be52f205bc44c
3.3.5
http://pastebin.com/SeS6xwYC

**Comment by mik1893** [comment]
what you were doing?

**Comment by Pirricli** [comment]
I don't know if it's related to #13851

**Comment by DJScias** [comment]
@Voidx I suggest getting the latest revision of 3.3.5 first (you're running on a 31st of May commit) and then trying again to see if it happens again or not.

**Comment by Voidx** [comment]
@DJScias not significant changes on actual rev.

**Comment by Aokromes** [comment]
#13851

**Comment by zanzark** [comment]
Still crashing today

**Comment by tkrokli** [comment]
@zanzark : there is a new issue posted for this kind of crash. Post your comment & crash log there:
**[[3.3.5][Crash]Unit::RemoveAurasByType](17063) #17063**
