### ISSUE TITLE
MapRefManager problems

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#14973]
Map::GetPlayers() is unsafe, and can easily cause problems.

Following code causes leaks/crashes:
```
Map::PlayerList const& playerList = map->GetPlayers();
for (auto itr : playerList)
{
     ...
}
```

Following code causes client freezes:
```
Map::PlayerList playerList = map->GetPlayers();
....
```

The second problem is easy enough to solve by just blocking improper operators. The first looks harder, MapRefManager derives from RefManager which seems to derive from some custom LinkedList class, which doesn't seem ready for any C++11 features

**Comment by Shauren** [comment]
I have no idea where did you pull this from but neither of your examples compile with msvc

**Comment by Trisjdc** [comment]
@Shauren: I tried in MSVC, I get the same errors.

I got the behavior described on gcc (Debian 4.7.2-5) 4.7.2

**Comment by jackpoz** [comment]
is this an issue about custom code using TC code in an unsafe way or is it about current TC code of commit https://github.com/TrinityCore/TrinityCore/commit/1a34fde96b88a9059b23f4a673bd2b6421e2198b being unsafe ?

**Comment by Trisjdc** [comment]
Current code is unsafe. You shouldn't ever be able to assign-copy a list of references, where the deletion of either list will delete references from both lists.
It's equally compiling a C++11 loop (on gcc, in this case) and then leaks/crashes without any warning by the compiler.

**Comment by Shauren** [comment]
Does not build with g++ (Ubuntu 4.9.2-10ubuntu13) 4.9.2 either
http://paste2.org/UdvA0Vk9

**Comment by Trisjdc** [comment]
Issue is in my codebase, base TC doesn't give me the same problem on gcc (Debian 4.7.2-5) 4.7.2
I'll be sure to test on base TC before I open a issue next time
