### ISSUE TITLE
[6.x] Update object

### ISSUE THREAD

**Issue by Sar777** [TrinityCore/TrinityCore#14977]
The problem with the update object.
For example .npc move visually not change position.

rev. b5c5442d039f12bb114
ubuntu 12.04 LTS

**Comment by DJScias** [comment]
This is related to visibility, known issue to the TC team as far as I know.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
No answer after 6d, maybe related to #14977
