### ISSUE TITLE
[3.3.5] Missing interrupt spellcasting on Hammer Of Justice, Maim and Bash

### ISSUE THREAD

**Issue by mik1893** [TrinityCore/TrinityCore#14972]
as per title.
In patch 3.x, those 3 spells have a linked interrupt spellcasting effect, which is actually used vs creatures ( dungeon/raid bosses), commonly when stun effect of the spell cannot land cause of immunity.

This mechanic was changed in patch 3.2.0 so that the interrupt effect was applied only to mobs, not to players.

below the patch to make it work. I will push it, just if anyone want to test it before i do tomorrow afternoon when i'll have again a 3.3.5 client :)

```cpp
diff --git a/src/server/scripts/Spells/spell_generic.cpp b/src/server/scripts/Spells/spell_generic.cpp
index 68c115f..eea7bdd 100644
--- a/src/server/scripts/Spells/spell_generic.cpp
+++ b/src/server/scripts/Spells/spell_generic.cpp
@@ -4079,6 +4079,47 @@ public:
     }
 };
 
+// PVE additional interrupt effect for Maim (-22570), Bash (-5211), Hammer of Justice (-853)
+enum GenericInterruptSpells
+{
+    SPELL_INTERRUPT = 32747
+};
+
+class spell_gen_interrupt : public SpellScriptLoader
+{
+public:
+    spell_gen_interrupt() : SpellScriptLoader("spell_gen_interrupt") { }
+
+    class spell_gen_interrupt_SpellScript : public SpellScript
+    {
+        PrepareSpellScript(spell_gen_interrupt_SpellScript);
+
+        bool Validate(SpellInfo const* /*spellInfo*/) override
+        {
+            if (!sSpellMgr->GetSpellInfo(SPELL_INTERRUPT))
+                return false;
+            return true;
+        }
+
+        void HandleScript()
+        {
+            if (Unit* target = GetHitCreature())
+                    GetCaster()->CastSpell(target, SPELL_INTERRUPT, true);
+        }
+
+        void Register() override
+        {
+            BeforeHit += SpellHitFn(spell_gen_interrupt_SpellScript::HandleScript);
+        }
+    };
+
+    SpellScript* GetSpellScript() const override
+    {
+        return new spell_gen_interrupt_SpellScript();
+    }
+};
+
 void AddSC_generic_spell_scripts()
 {
     new spell_gen_absorb0_hitlimit1();
@@ -4115,6 +4156,7 @@ void AddSC_generic_spell_scripts()
     new spell_gen_gadgetzan_transporter_backfire();
     new spell_gen_gift_of_naaru();
     new spell_gen_gnomish_transporter();
+    new spell_gen_interrupt();
     new spell_gen_lifeblood();
     new spell_gen_lifebloom("spell_hexlord_lifebloom", SPELL_HEXLORD_MALACRASS_LIFEBLOOM_FINAL_HEAL);
     new spell_gen_lifebloom("spell_tur_ragepaw_lifebloom", SPELL_TUR_RAGEPAW_LIFEBLOOM_FINAL_HEAL);
```

and the sql part:
```sql
DELETE FROM `spell_script_names` WHERE `scriptname` = 'spell_gen_interrupt';
INSERT INTO `spell_script_names` VALUES 
(-22570,'spell_gen_interrupt'), -- Maim
(-5211,'spell_gen_interrupt'),  -- Bash
(-853,'spell_gen_interrupt');   -- Hammer of Justice
```

**Comment by Trisjdc** [comment]
The proper way to fix this issue is to implement the attribute, not to add custom spell scripts.

**Comment by mik1893** [comment]
you mean SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER? didnt see that, i will implement the attribute then

**Comment by mik1893** [comment]
```cpp
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index ff7c6a8..d609195 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -2421,6 +2421,10 @@ void Spell::DoAllEffectOnTarget(TargetInfo* target)
         }
     }
 
+    // Some spells (Hammer of Justice, Bash, Maim) have SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER which triggers an additional interrupt effect
+    if (unit->GetTypeId() == TYPEID_PLAYER && m_spellInfo->HasAttribute(SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER))
+        m_caster->CastSpell(unit, 32747, TRIGGERED_FULL_MASK); // this spell is found in triggering spell description
+
     if (missInfo != SPELL_MISS_EVADE && !m_caster->IsFriendlyTo(unit) && (!m_spellInfo->IsPositive() || m_spellInfo->HasEffect(SPELL_EFFECT_DISPEL)))
     {
         m_caster->CombatStart(unit, !m_spellInfo->HasAttribute(SPELL_ATTR3_NO_INITIAL_AGGRO));
```

**Comment by Ascathor** [comment]
Personally, I find the spellscript cleaner. It's a cleaner execution to solve this and should save some runtime execution.

**Comment by pete318** [comment]
Well. The spell 32747 is in the DBC text field. At the very least there should be some constant for the spell, not just the number.

It should definitely still use the DBC value though.

**Comment by Kinzcool** [comment]
It's not question of finding it cleaner or not; you are not going to script every spell because it looks cleaner when you can have generic code for ALL of them.

**Comment by ccrs** [comment]
I agree with @pete318, better take the number directly from DBC if possible.

**Comment by mik1893** [comment]
i-ll dig a bit more on it this evening, if it-s possible to take that number from DBC.. otherwise I will put a define for that spell

**Comment by chaodhib** [comment]
By searching for "32747" in the DBC, it seems like the spells Arcane Torrent (-25046- -28730-), Silencing Shot (-34490-), Strangulate (-47476- but it has an unknown aura dummy effect) and Silence (-15487-) also have the same characteristic. So yeah, it would be definitely better to make that behavior generic.

I don't think it matters much if 32747 is hardcoded since Blizzard did it too in this case.

By the way, SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER is not present in all of those spells (Bash and Silence). They both have SPELL_ATTR6_UNK23 but it might not be related.

Ending note: in my search, I also found a few other spells that uses 32747: Deadly Throw Interrupt(-32748-) and Maim Interrupt (-44835-).

**Comment by mik1893** [comment]
getting back to this, my proposed solution would be:
Implement SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER and having it cast the spell 32747 when the target is non player
For the spells having the 32747 in description but not having the SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER, add it in the spell DBC through spellmgr

any thoughts?

**Comment by Rushor** [comment]
sth. like:

```c++
    if (m_spellInfo->HasAttribute(SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER))
         if (Unit* target = m_targets.GetUnitTarget())
             if (target->GetTypeId() == TYPEID_UNIT)
                 m_caster->CastSpell(target, 32747, true);
```

in Spell::cast

**Comment by mik1893** [comment]
Yes, something like that + adding the missing attributes to all the spells missing it

**Comment by Rushor** [comment]
> (for which i need some help in research)

full list:
Hammer of Justice
Bash
Silence
Maim
Silencing Shot
Strangulate
Arcane Torrent (Energy)
Arcane Torrent (Mana)
Arcane Torrent (Runic Power)

so attribute is missing for:
```c++
            case 47476: // Deathknight - Strangulate
             case 15487: // Priest - Silence
             case 8983:  // Druid - Bash
                 spellInfo->AttributesEx7 |= SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER;
                 break;
```

**Comment by mik1893** [comment]
updated PR with those spells - thx @Rushor !!!!

**Comment by Rushor** [comment]
aoe stuff will tested in ~2 hours

**Comment by Rushor** [comment]
kay tested ingame - sadly the spell not be casted, shure that the spellcast should not be moved to Spell::cast?

**Comment by mik1893** [comment]
the problem is with arcane torrent having aoe targets - let me run locally and see where to put it to make it work

**Comment by Rushor** [comment]
btw the spellids for the aoe spells:
/?spell=25046
/?spell=50613
/?spell=28730

so we really have a conflict here as you said already, the generic code cannot be added in Spell::cast, because aoetargets will not be affected by this. is there any similar genric methode for BeforeHit for aoespells?

**Comment by mik1893** [comment]
i have changed the code now so that it work on the single spell hit - it should actually work cleaner, i will test it asap

**Comment by Rushor** [comment]
tested with the latest changes - no interrupt will be done neither singletarget nor aoetarget

**Comment by mik1893** [comment]
@Rushor 
i've updated the PR and moved the code, can you check it out?
