### ISSUE TITLE
[Crash] InstanceSaveManager::_ResetOrWarnAll()

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#14983]
a note: this crash happen in 5 or 6 am
Crashlog: http://pastebin.com/7GL3Hf1Y
Revision: c544e88437106fb79dba14bbf8469deadb679e8a
TDB 58

**Comment by jackpoz** [comment]
@Runico could you use a debug build with no optimizations at night to get the most detailed crash log you can provide ?
does this crash happen every night ?

**Comment by Runico** [comment]
@jackpoz no, this crash doesn't happen every night, but happen at near 5 or 6 AM

**Comment by Shauren** [comment]
daily instance reset then

**Comment by Aokromes** [comment]
To long time since the last crash closing, if anyone have any new crash related to this open a new ticket.
