### ISSUE TITLE
Crash Object::GetGuidValue Malygos

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#14984]
http://pastebin.com/e2t7MbfA

0b1355b2800f8000dbf245cb035ac2bc9ba4a06e

3.3.5

**Comment by Ascathor** [comment]
Breaks there
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1557

**Comment by xerkoss** [comment]
missing if (_summoner == NULL) return; before https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1548

**Comment by Voidx** [comment]
yep i think it too

**Comment by jackpoz** [comment]
since when Creatures not alive casting a spell trigger a crash ?

**Comment by jackpoz** [comment]
is https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1578 actually safe ?

**Comment by joschiwald** [comment]
not safe

**Comment by jackpoz** [comment]
this is caused by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1578 , just reproduced kicking the player that summoned Wyrmrest Skytalon
