### ISSUE TITLE
[6.1.2] Crash world server everytime that i create character and log in ?

### ISSUE THREAD

**Issue by devastates** [TrinityCore/TrinityCore#14981]
For every race that i create.

Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x1616 (5654)] from [Player: Account: 2]
Prevented sending of [SMSG_UPDATE_TALENT_DATA 0x1862 (6242)] to non existent socket 1 to [Player: Account: 2]
Prevented sending of [SMSG_SET_PROFICIENCY 0x0D75 (3445)] to non existent socket 1 to [Player: Account: 2]
Prevented sending of [SMSG_SET_PROFICIENCY 0x0D75 (3445)] to non existent socket 1 to [Player: Account: 2]
Prevented sending of [SMSG_SET_PROFICIENCY 0x0D75 (3445)] to non existent socket 1 to [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x1616 (5654)] from [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x1616 (5654)] from [Player: Account: 2]

**Comment by DJScias** [comment]
Are you entirely sure your worldserver is crashing or are you just not able to log in like in #14961?

**Comment by devastates** [comment]
How can edit this hex with what program ?

**Comment by devastates** [comment]
Can you just upload both exe-s of wow ?
