### ISSUE TITLE
Unresolved external mysql 5.7

### ISSUE THREAD

**Issue by Ascathor** [TrinityCore/TrinityCore#14992]
Rev. 6527046

As MySQL 5.7 is successfully detected by cmake, it however generates compile error with unresolved external. Using the provided lib from wiki is successful, though, even in combination with the differing sql binary.

MySQL 5.7 Community Edition.
Note: It additionally did not ship two necessary files, binary_log_funcs.h and binary_log_types.h.
Those are also named as unresolved externals. Adding those into the include folder fixes their resolve however.

http://pastebin.com/wzeisnpF

**Comment by DDuarte** [comment]
Value of MYSQL_LIBRARY and MYSQL_INCLUDES ?

**Comment by Ascathor** [comment]
MYSQL_EXECUTABLE  C:/Program Files/MySQL/MySQL Server 5.7/bin/mysql.exe
MYSQL_INCLUDE_DIR C:/Program Files/MySQL/MySQL Server 5.7/include/
MYSQL_LIBRARY          C:/Program Files/MySQL/MySQL Server 5.7/lib/libmysql.lib

Mysql also runs the sql server.

**Comment by DDuarte** [comment]
Need to link with 32 bits libmysql.lib, not x64.
