### ISSUE TITLE
CMake 3.1.3 CMP0054 policy warning

### ISSUE THREAD

**Issue by Ascathor** [TrinityCore/TrinityCore#14991]
After 77f7f56, cmake prints the following warning.

CMake Warning (dev) at dep/gsoap/CMakeLists.txt:25 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Generator:
Visual Studio 12 2013
CMake 3.2.2

**Comment by tkrokli** [comment]
Confirmed on TrinityCore rev. 5178395a4f97 2015-07-02 00:27:38 +0100 (3.3.5 branch)
Visual Studio 12 2013 Win64
CMake 3.2.3

No compiling issues, though. I guess there is missing suppress code to match the change in 77f7f56 .

**Comment by jackpoz** [comment]
the change is https://github.com/TrinityCore/TrinityCore/commit/77f7f562683753a15bd2d3f80e65385f88383566 has been copied from existing cmake script https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/cmake/macros/FindPCHSupport.cmake#L99 , all these warnings are currently ignored.

Cannot reproduce with CMake 3.0.2

**Comment by Carbenium** [comment]
This warning was introduced in CMake 3.1.3.
http://www.cmake.org/cmake/help/v3.1/policy/CMP0054.html

**Comment by tkrokli** [comment]
@Carbenium : thanks for the info. I was about to test it myself, but you saved me lots of time. :+1:

**Comment by tkrokli** [comment]
Confirming that it now also shows in rev. 678a08c8c5e2 2015-07-04 02:43:43 +0100 (6.x branch).
6.x source from 2 days back did not display this message in CMake 3.2.2.
