### ISSUE TITLE
Crash of Boost System

### ISSUE THREAD

**Issue by megatronir** [TrinityCore/TrinityCore#15004]
Hello TC project , today i noticed a new crash and it seems to be from shauren revision cods in Boost System. 
branch : 6x
link of crashlog is : http://privatepaste.com/a8ef862f4d
revision is : https://github.com/TrinityCore/TrinityCore/commit/c24787f6665b5ea2b696bdfa7134a19ab5a3c331

**Comment by DDuarte** [comment]
And how does one replicate this issue?

**Comment by megatronir** [comment]
it is randomise, i'v got this crash sometimes from yesterday and today, 2-3 times. from same call stacks in every crashlog. and it's a little hard for reproduce this crashlog really.

**Comment by Nyeriah** [comment]
>Revision: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo)

Do you have a crash log in debug mode? (not RelWithDebInfo)

**Comment by megatronir** [comment]
Nope, but maybe i can compile in debug mode too.

**Comment by megatronir** [comment]
from yesterday i've compiled in debug mode and server 2-3 times again crashed, but crashlog is empty, and not dump or created any files of crash.it seems debug mode have some problems in this case.

**Comment by megatronir** [comment]
http://privatepaste.com/25e0ec3daf , i have still this crash of boost system. in Debug mode haven't it . only in RelWithDebInf it happens.

**Comment by megatronir** [comment]
shauren pls if you find any free time take a look at this crashlog, it's general problem in TC now from boost system, i tried to reproduce it but nothing found.

**Comment by StormBytePP** [comment]
Can it be related to move constructor? Using original object after it has been moved is an undefined behavior. And I see lots of ObjectGuid usage there, while not sure if this is the case, just a hint

**Comment by megatronir** [comment]
as i said, i have no sence :( , can't reproduce it for know if it's anythings like it, if can reproduce it, then easy to fix. but the problem is i do not know from where or why it happen :) it seems isen't ingame issue, because sometimes with even 0 online happen too

**Comment by megatronir** [comment]
any news ? http://privatepaste.com/408fb122d9 with latest revision still :(

**Comment by megatronir** [comment]
it will sending unsigned int m_opcode = 0x316 ... that's strange really

**Comment by jackpoz** [comment]
crash logs expired
