### ISSUE TITLE
[3.3.5a] Leviathan does not trigger raid lock

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15005]
a29433f

Sometimes, when u kill Levy, there goes a function from instance scripts, that sets the lock (based on the flags_extra in db). When you are sitting in the machine, you are totally ignored by this script, tested 10 times. When a team is in the machine, we don't get the raid lock. When I'm without, I get.

That's why I need to hardcode this (add in JustDied()) or something.

**Comment by DDuarte** [comment]
Reword your issue. The title shouldn't be a question.

**Comment by tkrokli** [comment]
Suggestion: **[3.3.5] Leviathan does not trigger raid lock**

I don't think `SetInstanceID()` is used for bosses, I could only find that code used in Battlegrounds:

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Battleground.h#L271
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/BattlegroundMgr.cpp#L401
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/BattlegroundMgr.cpp#L489

**Comment by ariel-** [comment]
There is a aptly called function in the instancemap class called PermBindAllPlayers.

/me thinks this commit is the culprit: d888e4c7ad5ce48eb1f550b3e142dad16c026d0c

**Comment by Nyeriah** [comment]
That commit most definitely has nothing to do with that. Were players ever bound to instance while on vehicle? Seems like an issue that has been there for a while, just been brought to light now

**Comment by ariel-** [comment]
Yup they were binded while on vehicle

Relevant code:

Unit::Kill
```c++
        // Dungeon specific stuff, only applies to players killing creatures
        if (creature->GetInstanceId())
        {
            Map* instanceMap = creature->GetMap();
            Player* creditedPlayer = GetCharmerOrOwnerPlayerOrPlayerItself();
            /// @todo do instance binding anyway if the charmer/owner is offline

            if (instanceMap->IsDungeon() && creditedPlayer)
            {
                if (instanceMap->IsRaidOrHeroicDungeon())
                {
                    if (creature->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_INSTANCE_BIND)
                        ((InstanceMap*)instanceMap)->PermBindAllPlayers(creditedPlayer);
                }
                else
                {
                    // the reset time is set but not added to the scheduler
                    // until the players leave the instance
                    time_t resettime = creature->GetRespawnTimeEx() + 2 * HOUR;
                    if (InstanceSave* save = sInstanceSaveMgr->GetInstanceSave(creature->GetInstanceId()))
                        if (save->GetResetTime() < resettime) save->SetResetTime(resettime);
                }
            }
        }
```

When flame leviathan dies, _JustDied() sets bossState in done, the passengers for all the vehicles are ejected, then the Unit::Kill gets a null "creditedPlayer", the if guard fails and body is never executed

**Comment by Nyeriah** [comment]
Oh uh I see, well, that might make sense then...

**Comment by selenir** [comment]
I am thinking on a temp solution, like dismounting all on 0.1% hp, setting bind and self-dmg the boss, but yeah, it is a 400% hack.

Guys, any ideas?

**Comment by Aokromes** [comment]
Also this bug makes player to loss achievements.

**Comment by jackpoz** [comment]
delay the vehicle eject then

**Comment by selenir** [comment]
The system does not see you, when you're inside a machine. We have to delay the death of the boss :dancer:

**Comment by jackpoz** [comment]
isn't that the owner should always be set to the vehicle passenger if the damage is done by a vehicle ?

**Comment by jackpoz** [comment]
Tried killing a Runeforged Sentry with vehicle and the code specified above found the creditedPlayer correctly.
Tried with a Steelforged Defender and it that case the NPC is killed by a SAI event at 1% HP and creditedPlayer is NULL in that case.

**Comment by selenir** [comment]
I have no idea how machine damage works, but i think that you have to deal the last hit by the machine.

In my opinion, the bug is just because the player is not visible to the core while sitting in the machine.

**Comment by selenir** [comment]
I love you <3
