### ISSUE TITLE
[Core/SAI] Updateoverride ignores SPELL_AURA_MOD_CONFUSE 

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15002]
rev: https://github.com/TrinityCore/TrinityCore/commit/275bb9303438a3e6e21e90de514723fd4aba7b05

Problem:
If you cast an aura with SPELL_AURA_MOD_CONFUSE on a hostile creature which has a SmartAI, the 
SPELL_AURA_MOD_CONFUSE will be ignored and the creatures attacks you with meleehits and other Spells.

How to reproduce:
1) Go to npc=95
2) pull it
3) cast 'sheep' (spell=61721) or something similar with SPELL_AURA_MOD_CONFUSE on it
4) run away from the creature
5) run again close to the creature
=> You will see that the creature starts meleehitting, follows you and casts it's abaility whenever it is ready for it (in this case spell=10277)

Short demonstrations on it:
http://youtu.be/Sy-xVGUkp_s

What do you already tried to fix this:
```c++
--- a/src/server/game/AI/SmartScripts/SmartAI.cpp
+++ b/src/server/game/AI/SmartScripts/SmartAI.cpp
@@ -353,6 +353,9 @@ void SmartAI::UpdateAI(uint32 diff)
             mFollowArrivedTimer -= diff;
     }
 
+    if (me->HasAuraType(SPELL_AURA_MOD_CONFUSE))
+        return;
+
     if (!UpdateVictim())
         return;
```

Nevertheless this changes nothing :(

My second thought was that it only starts attacking/ meleehitting if you run again close to the creature - maybe you are triggering some action in MoveInLineofSight() then :/

**Comment by robinsch** [comment]
I just overlooked it abit, I think this is caused by void SmartAI::SetCombatMove(bool on). It will call me->GetMotionMaster()->Clear(true); which will remove the confused state.

@Rushor: You can try this, untested!
```diff
diff --git a/src/server/game/AI/SmartScripts/SmartAI.cpp b/src/server/game/AI/SmartScripts/SmartAI.cpp
index 21a15fa..5f43e38 100644
--- a/src/server/game/AI/SmartScripts/SmartAI.cpp
+++ b/src/server/game/AI/SmartScripts/SmartAI.cpp
@@ -763,6 +763,9 @@ void SmartAI::SetCombatMove(bool on)
         }
         else
         {
+            if (me->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_CONFUSED_MOVE))
+                return;
+
             me->GetMotionMaster()->MovementExpired();
             me->GetMotionMaster()->Clear(true);
             me->StopMoving();
```

**Comment by Carbenium** [comment]
a6f7bb029c8d29c19de8596d5d402222ca6c00a2
