### ISSUE TITLE
WorldSession,HandleContinuePlayerLogin,memory leak

### ISSUE THREAD

**Issue by dyf303** [TrinityCore/TrinityCore#15000]
In WorldSession::HandleContinuePlayerLogin(),we new a LoginQueryHolder,then in ProcessQueryCallbacks ,we wait and get the holder and delete it.But,I have a question,when WorldSession is destory,and the _charLoginCallback is not back,the holder will never delete?

**Comment by Shauren** [comment]
No, SQLQueryHolderTask takes care of this if _charLoginCallback doesn't fire (deleted session)

**Comment by dyf303** [comment]
I find the ~SQLQueryHolderTask only check the  variable m_executed,If it's false ,then delete m_holder.If end the WorldSession::Update invoke the ProcessQueryCallbacks(),the SQLQueryHolderTask::Execute() is invoke,then WorldSession::Update return false.The WorldSession will destory,but the holder will never delete.Because Them in two different threads.
