### ISSUE TITLE
How To Win Friends And Influence Enemies Wotlk3.3.5

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#15001]
Can´complete the quest 
"How To Win Friends And Influence Enemies" in DK Zone!

"http://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies". It´s no scripted or Broken. 

The Npc speeak not to me to complete this Quest!

**Comment by ccrs** [comment]
wtf? it is scripted and works xd

**Comment by Kittnz** [comment]
Update your core and report back @genion18

**Comment by Runico** [comment]
this quest sometimes for some reason doesn't work

**Comment by tkrokli** [comment]
@genion18 : This quest has worked for a long time. Make sure you do the quest properly:

1. Open the Ornately Jeweled Box (http://www.wowhead.com/item=39418/ornately-jeweled-box)
2. Equip 2x Keleseth's Persuader (http://www.wowhead.com/item=39371/keleseths-persuader)
3. Use only auto-attack and not spells like like Icy Touch and Death Coil (they don't count as strikes)
4. Preferably attack only 1 single NPC mob, like one of the Scarlet chaplain/priest/dean NPCs.
5. Make sure you don't use a Risen Ghoul stay away from any scourge NPC who can attack your target

Read http://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies#comments
for more tips on how to avoid problems while trying to do this quest.
