### ISSUE TITLE
[3.3.5] Distract removing Invisibility form mages.

### ISSUE THREAD

**Issue by JunkyBulgaria** [TrinityCore/TrinityCore#15010]
Title says it all.
What should happen: Mage should still be invisible.
What happens: Distract is removing the invisibility aura from mages.
ref: #155 Author: byleth
rev a328a119784252c6d514436f4ceffa693ac65453
Distract: http://wotlk.openwow.com/spell=1725
Invisibility: http://wotlk.openwow.com/spell=66

```Patch 3.2.0 (04-Aug-2009): Can no longer be interrupted by a hostile action or damage done during the 3-second Fade time, however an invisible mage is still vulnerable to Stun and Silence effects.```
Distract is not a stun or a silence either.

**Comment by Rushor** [comment]
@robinsch fixed this here https://github.com/TrinityCore/TrinityCore/pull/14824
