### ISSUE TITLE
[6.x] This NPCs should't be quest starters

### ISSUE THREAD

**Issue by msoky** [TrinityCore/TrinityCore#15013]
This NPCs should't be quest starters, but they are...
http://www.wowhead.com/npc=706
http://www.wowhead.com/npc=808
http://www.wowhead.com/npc=3102
http://www.wowhead.com/npc=10556
http://www.wowhead.com/npc=15274
http://www.wowhead.com/npc=37070
http://www.wowhead.com/npc=37073
http://www.wowhead.com/npc=37112
http://www.wowhead.com/npc=39317
http://www.wowhead.com/npc=42223

this npcs is in start locations
revision: https://github.com/TrinityCore/TrinityCore/commit/d418ae54a446472d64f2e198a61bebef205cbb2f

fix:
DELETE FROM `creature_queststarter` WHERE `id` IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);
UPDATE `creature_template` SET `npcflag`=0 WHERE `entry` IN (706,808,3102,10556,15274,37070,37073,37112,39317,42223);

**Comment by DDuarte** [comment]
Post your queries in #12752
