### ISSUE TITLE
[3.3.5] Tremor totem LoS bugged

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15012]
a29433f

1. Put a T Totem
2. Go away
3. If there's anything between you and the totem, it doesn't work.

I know, that this was fixed here: https://github.com/TrinityCore/TrinityCore/commit/5f90eb831afb021e53fa3523d02ad783cda5c446
but still not working.

Using VMAPS and MMAPS extracted one week ago.

**Comment by Killyana** [comment]
By anything you mean (a wall=map),  a npc, a player or an object?

**Comment by Runico** [comment]
@Killyana, It means line of sight
Should tremor totem works with LoS ?

**Comment by Killyana** [comment]
Yes it must.

**Comment by Nertx** [comment]
Try: https://gist.github.com/Nertx/c0192a4e568543326c1f

**Comment by Rushor** [comment]
@Nertx: pls open up a pr for this :)

https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request
