### ISSUE TITLE
[3.3.5][6.x][MMAPS] Charge ignoring z position of target

### ISSUE THREAD

**Issue by Goatform** [TrinityCore/TrinityCore#15011]
It allow caster to charge his target who's e.g. 5 yards above caster without any object (any path) to reach that target. On retail if your target is above/under you for 5 yards or more and there is no availabe path for you it will sent you "No path" error message. On TC it will let you to charge your target ignoring z position.

Here are few examples:

This is how charge works on TC:
![8jcdsrv](https://cloud.githubusercontent.com/assets/8354705/8511930/7bebd7f8-232c-11e5-9f9e-e83447697320.png)

- So ask you can see on that picture, it let you to charge target who's ... probably flying or something like that without checking z position. And on picture you can see that there are two lines which means that sometimes it will let you to "fly and charge target" and sometimes you will charge under him in "same path of your target".

This is how charge should to work (retail):
![sqmrdyo](https://cloud.githubusercontent.com/assets/8354705/8511950/56a36b40-232d-11e5-9dbb-4844ffab72fa.png)

- It shouldn't let you to charge in at all and it will sent you "No path" error.

This is situation when you are able to charge your target who's above you 5y or more.
![qx37pnp](https://cloud.githubusercontent.com/assets/8354705/8511954/7910590e-232d-11e5-983d-1efecefc58a3.png)

- So only if you have object (availabe path) for charge, it will let you to do that.

TESTED ON:
3.3.5 : dfc7176
6.x : d418ae5

**Comment by Goatform** [comment]
This is how I tried to fix it but it will cause the problem (like on picture 3.) because it doesn't have check for objects etc.

``` diff
                         result = m_preGeneratedPath.CalculatePath(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ() + target->GetObjectSize(), false);
                         if (m_preGeneratedPath.GetPathType() & PATHFIND_SHORT)
                             return SPELL_FAILED_OUT_OF_RANGE;
                        else if (!result || m_preGeneratedPath.GetPathType() & (PATHFIND_NOPATH | PATHFIND_INCOMPLETE))
                             return SPELL_FAILED_NOPATH;
                     }
+                    else if (target->GetPositionZ() > GetCaster()->GetPositionZ() + 5.0f)
+                        return SPELL_FAILED_NOPATH;
 
                     m_preGeneratedPath.ReducePathLenghtByDist(objSize);
                 }

**Comment by planee** [comment]
nice!

**Comment by Rushor** [comment]
this wasn't fixed here https://github.com/TrinityCore/TrinityCore/issues/13847?

if we apply this patch you are not able to charge if there a stair or some similar object - but you already explained this in picture 3

**Comment by Goatform** [comment]
Those issues aren't simiar.

**Comment by jackpoz** [comment]
@Goatform you need to compare target's Z and last-point-in-the-path's Z

**Comment by cemak** [comment]
maybe check straight line start z and end z

**Comment by jackpoz** [comment]
what do pets do with flying creatures on retail ? and what do walking creatures do with flying players/creatures ? Just to get an idea if we should fix only charge or the whole pathfinding algorithm used by creatures.

**Comment by cemak** [comment]
@jackpoz, i think only charge.

**Comment by cemak** [comment]
Need test
[code]
diff --git a/src/server/game/Movement/PathGenerator.cpp b/src/server/game/Movement/PathGenerator.cpp
index 0acfc78..210a826 100644
--- a/src/server/game/Movement/PathGenerator.cpp
+++ b/src/server/game/Movement/PathGenerator.cpp
@@ -940,3 +940,14 @@ void PathGenerator::ReducePathLenghtByDist(float dist)
         nextVec = currVec; // we're going backwards
     }
 }
+
+bool PathGenerator::InValidPathZ()
+{
+    G3D::Vector3 startPos = GetStartPosition();
+    G3D::Vector3 endPos = GetActualEndPosition();
+
+    if (std::fabs(endPos.z - startPos.z) > 5.f)
+        return true;
+
+    return false;
+}
diff --git a/src/server/game/Movement/PathGenerator.h b/src/server/game/Movement/PathGenerator.h
index 71e0e88..44372f1 100644
--- a/src/server/game/Movement/PathGenerator.h
+++ b/src/server/game/Movement/PathGenerator.h
@@ -58,6 +58,7 @@ class PathGenerator
         // Calculate the path from owner to given destination
         // return: true if new path was calculated, false otherwise (no change needed)
         bool CalculatePath(float destX, float destY, float destZ, bool forceDest = false, bool straightLine = false);
+        bool InValidPathZ();
 
         // option setters - use optional
         void SetUseStraightPath(bool useStraightPath) { _useStraightPath = useStraightPath; }
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 632392a..409f71d 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -5132,7 +5132,9 @@ SpellCastResult Spell::CheckCast(bool strict)
                     m_preGeneratedPath.SetPathLengthLimit(range);
                     // first try with raycast, if it fails fall back to normal path
                     bool result = m_preGeneratedPath.CalculatePath(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ() + target->GetObjectSize() / 2.f, false, true);
-                    if (m_preGeneratedPath.GetPathType() & PATHFIND_SHORT)
+                    if (m_preGeneratedPath.InValidPathZ()) // Check only for Straight Line, right ?
+                        return SPELL_FAILED_NOPATH;
+                    else if (m_preGeneratedPath.GetPathType() & PATHFIND_SHORT)
                         return SPELL_FAILED_OUT_OF_RANGE;
                     else if (!result || m_preGeneratedPath.GetPathType() & (PATHFIND_NOPATH | PATHFIND_INCOMPLETE))
                     {

[/code]

**Comment by Rushor** [comment]
@cemak this causes the issue, that you cannot charge here: 
![Bild](http://i.imgur.com/R8g8HUv.jpg)

:)

**Comment by jackpoz** [comment]
the whole idea of just checking z-diff between start and end path position makes no sense, what you want to check is if the creature is flying/in the sky (5 yards) and you can't fly

**Comment by cemak** [comment]
@jackpoz  only for creature or for player too ?

**Comment by Goatform** [comment]
@cemak, it should work same for players and creatures... you shouldn't be able to charge to your victim which is 5 yards above ground and there is not any object (available path) to him.

**Comment by cemak** [comment]
@Goatform, ok.
need test:

```javascript
diff --git a/src/server/game/Movement/PathGenerator.cpp b/src/server/game/Movement/PathGenerator.cpp
index 186b5d4..cfc4c1b 100644
--- a/src/server/game/Movement/PathGenerator.cpp
+++ b/src/server/game/Movement/PathGenerator.cpp
@@ -939,3 +939,11 @@ void PathGenerator::ReducePathLenghtByDist(float dist)
         nextVec = currVec; // we're going backwards
     }
 }
+
+bool PathGenerator::InValidPathZ(Unit* target)
+{
+    G3D::Vector3 startPos = GetStartPosition();
+    G3D::Vector3 endPos = GetActualEndPosition();
+
+    return (std::fabs(endPos.z - startPos.z) > 5.f && target->IsFlying());
+}
diff --git a/src/server/game/Movement/PathGenerator.h b/src/server/game/Movement/PathGenerator.h
index 71e0e88..44851fa 100644
--- a/src/server/game/Movement/PathGenerator.h
+++ b/src/server/game/Movement/PathGenerator.h
@@ -58,6 +58,7 @@ class PathGenerator
         // Calculate the path from owner to given destination
         // return: true if new path was calculated, false otherwise (no change needed)
         bool CalculatePath(float destX, float destY, float destZ, bool forceDest = false, bool straightLine = false);
+        bool InValidPathZ(Unit* target);
 
         // option setters - use optional
         void SetUseStraightPath(bool useStraightPath) { _useStraightPath = useStraightPath; }
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 03f14d1..e358ff1 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -5107,7 +5107,11 @@ SpellCastResult Spell::CheckCast(bool strict)
                             return SPELL_FAILED_OUT_OF_RANGE;
                         else if (!result || m_preGeneratedPath.GetPathType() & (PATHFIND_NOPATH | PATHFIND_INCOMPLETE))
                             return SPELL_FAILED_NOPATH;
+                        else if (m_preGeneratedPath.InValidPathZ(target)) // Chek z, if not in a straight line
+                            return SPELL_FAILED_NOPATH;
                     }
+                    else if (m_preGeneratedPath.InValidPathZ(target)) // Chek z, if in a straight line
+                            return SPELL_FAILED_NOPATH;
 
                     m_preGeneratedPath.ReducePathLenghtByDist(objSize); // move back
                 }

```

**Comment by Shauren** [comment]
@cemak You want to check (target->GetPositionZ() - endPos.z) > 5

**Comment by jackpoz** [comment]
which is what I wrote at https://github.com/TrinityCore/TrinityCore/issues/15011#issuecomment-118653186 :P

@cemak you can't fix something if you don't fully understand the issue, writing different patches with trial&error won't help

**Comment by cemak** [comment]
@Shauren, why (target->GetPositionZ() - endPos.z) > 5 ?
set here:
```javascript
bool PathGenerator::CalculatePath(float destX, float destY, float destZ, bool forceDest, bool straightLine) // @Edit
{
    float x, y, z;
    _sourceUnit->GetPosition(x, y, z); // GetPosition for caster
    G3D::Vector3 start(x, y, z);
    SetStartPosition(start); // Set position for caster
}
```
in my patch:
```javascript
bool PathGenerator::InValidPathZ(Unit* target)
{
    G3D::Vector3 startPos = GetStartPosition(); // Get start Positions for caster
    G3D::Vector3 endPos = GetActualEndPosition(); // Get end Possition for caster

    return (std::fabs(endPos.z - startPos.z) > 5.f && target->IsFlying());
}
```
jackpoz says "need  check start pos z and end pos z".
Goatform says "need check for IsFlying target".


@jackpoz,I have no way to check, because i'am use TC 2012 and there is no Pathfinding.

**Comment by jackpoz** [comment]
I didn't say to check start pos z, I said at https://github.com/TrinityCore/TrinityCore/issues/15011#issuecomment-118653186
> you need to compare target's Z and last-point-in-the-path's Z

which is the same as what shauren wrote.

**Comment by cemak** [comment]
@jackpoz, understood. I hadn't read properly.

**Comment by Rushor** [comment]
@cemak : pls open up a pr for your fix :)

https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.
