### ISSUE TITLE
[3.3.5][ICC] Deathbringer LoS Problems

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15018]
By killing the Deathbringer, if any player raid is out of LoS (or on another floor of Icc, gunship, etc.) the door will not open and no achiev is delivered.

video: https://youtu.be/ZVaP1S0HJE0

In the video, he entered in sometimes evade because there were only two players. By attacking the player in out of LoS he entered Evade. In a joint raid with players, this does not usually happen, however if someone is on the gunship when the death bringer die, the door will not open.

It can also be reproduce if a player is on the first floor and the Deathbringer is dead. The door also not open.
Test on Rev b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by Rushor** [comment]
never ever kill this guy with damage 1-11.
try it with normal spells instead

**Comment by Keader** [comment]
This bug occurs regardless of the spell used to kill him. If necessary you record another video using other spells.

**Comment by sirikfoll** [comment]
Confirmed on rev: 7c7d258482cb541b9a57fd9ff9b64f01c51cf4cb

To reproduce, just leave 1 player in the Gunship, while the others kill the boss normally.

It looks like the script gets stuck and do not chance the encounter's state to `DONE`

**Comment by Frytiks** [comment]
His doors not open even Raid is on floor.

**Comment by Frytiks** [comment]
And evade is just simply global problem with existing report

**Comment by Keader** [comment]
@Frytiks I did not understand in what way you say it does not open even if the raid is on the floor

**Comment by Frytiks** [comment]
If no one is on gunship, simply just all fighting boss.

**Comment by Keader** [comment]
without los i can not reproduce, happened rare times for me

**Comment by Laintime** [comment]
Need rework evede sistem.
I fix it.Not publick.

**Comment by Smokexyz** [comment]
After deathbringer is killed, the boss state is set to FAIL, for some reason.

**Comment by sucklifex** [comment]
@Smokexyz it also happens for gunship battle too

**Comment by Smokexyz** [comment]
@sucklifex cannot reproduce that on a4623efaa67be1cfea19e561be83f118a784b9d1, gunship battle sets to done after completing.
