### ISSUE TITLE
[3.3.5] Dk Runenschieden bugged

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#15019]
Hello, the DK has a Problem this this Runenschmieden.

In the bokk say it´s to me 17737/0 and the Schmiedet weapon are red (says this spell is not active)

see this Screenshot.

Testet this different repacks von Ac-Web and all this same Problem!

http://genion.bplaced.com/1/ru.jpg

greets

**Comment by tkrokli** [comment]
This is default behaviour, isn't it? The runes still work, even if that text is red. Cosmetic issue?

**Comment by tkrokli** [comment]
@genion18 : you should have written "TrinityCore rev. 6681b3600" to avoid the reason "Invalid-IncompleteData/NotTrinityCore". But it would have been closed as **DUPLICATE**, due to #13882.

**Comment by Aokromes** [comment]
He is using a repack anyway (or multiple repacks)

**Comment by tkrokli** [comment]
Good point. I did not read that part at first, due to mixed English and German text.
