### ISSUE TITLE
[3.3.5] Ancestral Awakening Overheal

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#15028]
http://wotlk.openwow.com/spell=51558

When caster gets heal mod (like Valithira http://www.wowhead.com/spell=70873) Ancestral Awakening goes crazy xD

proves: (sorry for spanish :P)
![image](https://cloud.githubusercontent.com/assets/4329612/8559278/8580ce6e-250b-11e5-89d4-ccd44e8eed36.png)
![image](https://cloud.githubusercontent.com/assets/4329612/8559332/0d34e52a-250c-11e5-8f40-9fb211cccb26.png)

23e4472d14bbf24722277d9d49c62ea7e39821c7

**Comment by ariel-** [comment]
Can't reproduce in 275c17b4c23468a3274079c1174a7e4999131d81
