### ISSUE TITLE
[3.3.5] Gap between auto attack range and "start chase" range

### ISSUE THREAD

**Issue by iTob191** [TrinityCore/TrinityCore#15026]
When tanking a boss there is a dinstance where the boss doesn't auto attack anymore but also doesn't run after you. If there is not much movement needed for the tank, he can simply get to that range and isn't going to get hitted anymore by regular auto attacks. This distance must be fairly accurate, otherwise the boss will still hit you or start running after you.

Tested with multiple bosses e.g. in ICC / Naxxramas.

Rev 23e4472 | 3.3.5

**Comment by Rushor** [comment]
@iTob191: pls provide a video to clarify this issue :)

**Comment by chaodhib** [comment]
Confirmed. Here is an example: https://we.tl/QqpeZ2jM4y

tested on d7600f1126d2780fecdfcdfc66a598a48cee0136

I talk about the cause of the issue here (in the second part): https://github.com/TrinityCore/TrinityCore/pull/17787#issuecomment-239819554

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20173
