### ISSUE TITLE
[3.3.5] Armor Penetration formula wrong

### ISSUE THREAD

**Issue by wamwam** [TrinityCore/TrinityCore#15024]
The amount of armor applicable by armor penetration is  (Armor + C)/3 where C is a constant based on the victim's level. It should be based on the attacker's level instead. 

The reason for this mistake was probably because Ghostcrawler said it was based on the victim's level in a post here: http://web.archive.org/web/20101001010647/http://forums.worldofwarcraft.com/thread.html?topicId=16473618356&sid=1&pageNo=4#77

He was wrong about C. It was tested and showed it's based on the attacker's level. I got some links where people say this:

http://wowthinktank.blogspot.nl/2010/01/druid-threat-value-of-arpen.html
http://web.archive.org/web/20110809101916/http://elitistjerks.com/f73/t63774-feral_dps_discussion/p29/
http://www.dslreports.com/forum/remark,24647816
http://www.wowhead.com/forums&topic=139546/calculating-armor-penetration

If more proof is needed I can provide some old videos from which you can directly calculate the cap.

**Comment by Keader** [comment]
Place the rev your TC or the issue will be declared invalid

**Comment by wamwam** [comment]
I haven't tested it ingame with trinitycore, I saw it here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp

If needed I'll delete this and test it manually later

**Comment by Keader** [comment]
Without TC hash rev issue will be considered invalid :x

**Comment by ccrs** [comment]
ghostcrawler post:
C=400+85*targetlevel+4.5*85*(targetlevel-59);
unit.cpp:
maxArmorPen = 400 + 85 * victim->getLevel() + 4.5f * 85 * (victim->getLevel() - 59);
