### ISSUE TITLE
Ooze Flood - Rotface

### ISSUE THREAD

**Issue by Golrag** [TrinityCore/TrinityCore#15031]
![wowscrnshot_070815_155838](https://cloud.githubusercontent.com/assets/6825243/8572036/6c3b0c6a-258a-11e5-9aaf-1c7b833df83b.jpg)
![wowscrnshot_070815_155840](https://cloud.githubusercontent.com/assets/6825243/8572041/70f101e2-258a-11e5-8c4e-f1814638c66b.jpg)

Bug: The ooze flood should be on the ground (Spells: 69782, 69796, 69798, 69801)
rev: https://github.com/TrinityCore/TrinityCore/commit/23e4472d14bbf24722277d9d49c62ea7e39821c7

Edit: fixed with this diff: http://pastebin.com/BiWuPEXg not sure if the spellmgr changes are blizzlike

**Comment by jackpoz** [comment]
that diff contains a mix of changes, are all needed to fix the issue ?

**Comment by Golrag** [comment]
```diff
@@ -448,14 +448,9 @@ class boss_professor_putricide : public CreatureScript
                             std::list<Creature*> list;
                             GetCreatureListWithEntryInGrid(list, rotface, NPC_PUDDLE_STALKER, 50.0f);
                             list.remove_if(RotfaceHeightCheck(rotface));
+                            list.sort(Trinity::ObjectDistanceOrderPred(rotface));
                             if (list.size() > 4)
-                            {
-                                list.sort(Trinity::ObjectDistanceOrderPred(rotface));
-                                do
-                                {
-                                    list.pop_back();
-                                } while (list.size() > 4);
-                            }
+                                list.resize(4); // runs .pop_back();
 
                             uint8 i = 0;
                             while (!list.empty())
```

is not needed to make it work, It just looked cleaner to me :p

**Comment by Rushor** [comment]
you tried this fix >= 5 minutes and you didn't got any crash?

**Comment by Golrag** [comment]
10 minutes in combat with rotface, no crash ^^

**Comment by Rushor** [comment]
with these changes the Ooze Flood will be summoned only near the door no?

aka: the closest points near the door http://i.imgur.com/FL5wk9o.jpg

**Comment by Golrag** [comment]
![wowscrnshot_070815_231221](https://cloud.githubusercontent.com/assets/6825243/8582392/d291b96e-25c6-11e5-8b77-08c1e6252d86.jpg)
![wowscrnshot_070815_231224](https://cloud.githubusercontent.com/assets/6825243/8582393/d2a60ad6-25c6-11e5-9e42-25d48488c31f.jpg)
This is what I get, and that's how it supposed to be :p

**Comment by Aokromes** [comment]
The same code change is needed on anub'arak's encounter with ice balls :)

**Comment by Golrag** [comment]
Question: Should spells with TARGET_UNIT_NEARBY_ENTRY (oops, wrong comment in diff) be able to target self when they have the same entry as the supposed target ?

**Comment by Shauren** [comment]
Yes

**Comment by Goatform** [comment]
Is this bugged from before or it's caused from newest commits ?

**Comment by Aokromes** [comment]
No, it's long time bugged.
