### ISSUE TITLE
[3.3.5] Adds by Novos the Summoner fall under the map

### ISSUE THREAD

**Issue by Shienor** [TrinityCore/TrinityCore#15039]
In the bossfight with Novos the Summoner (26631) the adds fall under the map after he became damage. This kill the Achievement “Oh Novos!” (Defeat Novos the Summoner in Drak'Tharon Keep on Heroic Difficulty without allowing any undead minions to reach the floor. )

The adds:
Fetid Troll Corpse(Entry: 27598)
Hulking Corpse (Entry: 27598)
Risen Shadowcaster (Entry: 27600)

**Comment by Carbenium** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md

**Comment by Shienor** [comment]
Carbenium sorry when I must ask. 3.3.5 isn't support? 
I have the last version about 3.3.5 or why you post the link?

**Comment by ccrs** [comment]
cannot confirm this

**Comment by Shienor** [comment]
I have use the Autohit Funktion and the spells from the Pala on the stairs.
What use you?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 6681b3600cff

**Comment by tkrokli** [comment]
@Shienor : it sounds like you are not using Mmaps or have got a Vmaps issue.
(You also did not provide your core rev. hash & TDB version.)
