### ISSUE TITLE
[3.3.5][Ulduar] XT002 Entering the ground

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15032]
XT002 - 33293

During the fight, depending on where you move this happens:

XT002
![wowscrnshot_070815_125151](https://cloud.githubusercontent.com/assets/7120913/8575252/62c39404-2571-11e5-9416-893b5ed9ab8e.jpg)

rev b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by Rushor** [comment]
you tried disabling the movement maps?
http://rgtc.wikia.com/wiki/Disables_tc2 - well pretty old link but meh

**Comment by joschiwald** [comment]
mimiron bug caused by incomplete hover movement implementation

xt bug caused by the stairs under the floor

**Comment by Killyana** [comment]
For XT it's the mmaps but the vmaps, with vmap.enableHeight = 0 the issue doesn't happen.

**Comment by P-Kito** [comment]
Movementmaps have nothing to do with this.

**Comment by Keader** [comment]
@Rushor this is a good choice? No other boss would have problems?

**Comment by Rushor** [comment]
i was just my first idea, but as the others said, it should be done in another way

try to use use:
33554432 = Hover mode (bytes1) in creature_template_addon for mimiron

**Comment by joschiwald** [comment]
Won't work, current hover movement implementation works for static npcs only, they start moving and hover position goes to ground

**Comment by ccrs** [comment]
@joschiwald i think its related to how movementflags are updated

**Comment by joschiwald** [comment]
on movement target destination is relocated to ground, that's all, hover offset is missing

**Comment by Keader** [comment]
No one has any idea of correction?

**Comment by Frytiks** [comment]
Disable mmaps for boss

**Comment by Keader** [comment]
How? And that would not cause others boss give problem?

**Comment by tkrokli** [comment]
@Rushor : the TC wiki has a better page for the `disables` table: http://collab.kpsn.org/display/tc/disables

@Keader : try the following Query (not sure if it is 100% correct, not tested) :
```sql
DELETE FROM `disables` WHERE `entry` IN (33293,33350);
INSERT INTO `disables` (`sourceType`,`entry`,`flags`,`params_0`,`params_1`,`comment`) VALUES
(7,33293,0,0,0,'Disable mmaps - XT002'),
(7,33350,0,0,0,'Disable mmaps - Mimiron');

**Comment by Rushor** [comment]
the documetation was down at the time i wrote this

**Comment by Frytiks** [comment]
Bad, you must add to creatute_template flag disable pathfinding

**Comment by tkrokli** [comment]
@Rushor : OK, I have seen the TC wiki site down enough times to know how inconvenient that is.
@Frytiks : thanks for the correction, I just thought Rushor and you referred to the `disables` table.

BTW, I found Rushor's explanation for the correct flag to use in #10422 : (flags_extra)
CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING = 0x20000000 // creature ignore pathfinding

Added the info above to the TC wiki page:
http://collab.kpsn.org/display/tc/creature_template#creature_template-flags_extra
```sql
-- Disable pathfinding for XT002 and Mimiron
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|1|536870912 WHERE `entry` IN (33293,33350);

**Comment by Keader** [comment]
@tkrokli still entering the ground

**Comment by tkrokli** [comment]
@Keader : are you sure you have deleted your Cache and cleaned up your WTF folder?
Anyway, can you confirm if it works when changing this setting in Worldserver.conf :
```
vmap.enableHeight = 0
```
(as suggested by Killyana 15 days ago, https://github.com/TrinityCore/TrinityCore/issues/15032#issuecomment-119689901) -- default value = 1 in Worldserver.conf

**Comment by Raydor** [comment]
XT's bug happens also with pets, if you move your pet where XT is in the first photo (near the stairs) it will go underground.

**Comment by LuqJensen** [comment]
mimiron and xt bugs are really not the same deal. 
one is about hovering and the other about maps. please separate the issue

**Comment by Keader** [comment]
done @LuqJensen  ^^

**Comment by Kittnz** [comment]
This happens in world too, voidwalkers and pets just run after a npcs, they sometimes go underground too. You can't see them but your pet is attacking and los so you can't cast, they can attack if you are right underneath them.

**Comment by Keader** [comment]
No news? :(

**Comment by Keader** [comment]
Already fixed by https://github.com/TrinityCore/TrinityCore/commit/9ad952c3bc87a03cc39c2c44a301857b8f62df7c

**Comment by Rushor** [comment]
nice :)

**Comment by tkrokli** [comment]
I can confirm that by now, using rev. b82ffb88f7e6 2016-04-26 22:25:16 +0100 (3.3.5 branch),  my 2 examples in https://github.com/TrinityCore/TrinityCore/pull/16736#issuecomment-192947256 appear to be fixed, which suggests that many NPC Z axis map issues are now fixed.
