### ISSUE TITLE
[6.x] Tools mapextrator

### ISSUE THREAD

**Issue by Atraxys** [TrinityCore/TrinityCore#15043]
Last commit 1658421403c4f0643732efd25a338ac47a3c32f4

Map & DBC Extractor
===================
error opening casc storage '/home/wow/client/Data': FILE_NOT_FOUND

Client version : 6.2 : (20216 and 20201)
Functional client used to play on the official version before

no error during compilation

**Comment by Aokromes** [comment]
repair your client.

**Comment by Atraxys** [comment]
In fact I had to copy the Data folder, thank you
