### ISSUE TITLE
[SPELL/DK] Pestilence

### ISSUE THREAD

**Issue by P-Kito** [TrinityCore/TrinityCore#15040]
I am not sure if it's a problem on current TC. But maybe someone can approve this.

Should:
Take a point between the target and dk and spread diseases to all targets within 10y (15y with Glyph).

Current:
Only spreads diseases to targets infront of the DK. And when having the Glyph to increase range to 15y, Pestilence won't trigger when DK is standing too close to the target.

Can someone confirm this on TC?

Information to this spell:
Patch 3.1.0 (14-Apr-2009): Does no damage and has only one rank. This ability will now spread disease centered on a position between the death knight and its target, rather than the target’s center position (for very large creatures, this used to cause no disease spread at all).
http://wowwiki.wikia.com/Pestilence
Uses 3 Spell_effect.
One for Single target, one for 10y AOE Enemy and 1 with 5yard target_front.

**Comment by Keader** [comment]
TC Hash?

**Comment by P-Kito** [comment]
As I said, someone has to approve this, since I don't have a runable TC on this computer.

Would be cool if you log in and try it with a DK and put ur hash in here :+1:

**Comment by DDuarte** [comment]
We got enough *real* issues, creating potential issues doesn't seem like a good idea.

If someone does confirm this I'll re-open the issue.

**Comment by fat4l** [comment]
tested on:TrinityCore rev. e77744b48eac 2015-09-30 19:16:09 +0200 (master branch) (Unix, Release)

Confirm this: "Only spreads diseases to targets infront of the DK. "
Pestilence doesn't spread if enemies are behind the DK(it doesn't spread as AOE).

Can't confirm this: "And when having the Glyph to increase range to 15y, Pestilence won't trigger when DK is standing too close to the target."

**Comment by Aokromes** [comment]
There is no such rev on trinitycore.

**Comment by tkrokli** [comment]
Nor is there any 'master' branch on TrinityCore since November 2014. Use TC source for support.

**Comment by fat4l** [comment]
ah, what about this ? 
https://github.com/TrinityCore/TrinityCore/commit/d476e0eff24af5849bbbc21128aa461a24d4fe9b
that's the last commit that we merged at.

**Comment by Aokromes** [comment]
To old commit/who knows how much custom code to trust you report.
