### ISSUE TITLE
[3.3.5][6.x][Ulduar/Algalon] Living Constellation not activating during the encounter

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15042]
Npc Entry: 33052

WoWHead Description: "Living Constellation - Spawned in threes periodically during Phase 1. Attack with  Arcane Barrage, which inflicts 4,163 to 4,837 Arcane damage. If a Living Constellation enters a Black Hole, both despawn."

However, at no time during the entire fight Algalon none of Living Constellation is active

Rev b574c99549bb8cf1d95bd4bc0c319548a678799a

**Comment by Killyana** [comment]
What do you mean by "active"?

**Comment by Keader** [comment]
Early on in the fight, Algalon creates many Living Constellation to compose the scene. However during the battle periodically should have 3 Living Constellation attacking the raid. If you test they do not attack the raid at any time during the entire battle.

How it should work: https://youtu.be/fRfVDgTLMGA?t=1m38s

(Sorry bad english)

**Comment by sirikfoll** [comment]
Someone can provide sniffs from  Algalon's encounter?

**Comment by ariel-** [comment]
Code for activation is present, but somehow not activating.

Proof: https://github.com/TrinityCore/TrinityCore/blob/b574c99549bb8cf1d95bd4bc0c319548a678799a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp#L238-L258

**Comment by tkrokli** [comment]
`*chuckle*` The spell was prepared and selected, but not put into effect. Nice catch! :+1:

**Comment by Keader** [comment]
Still dont work Ariel

**Comment by ariel-** [comment]
Read the code, constellations are activated between 45 and 50 secs after combat start

**Comment by Keader** [comment]
i know, but still dont work...

**Comment by ariel-** [comment]
Are you solo testing? collapsing stars attack a random non-tank player, so if you're the only one you won't see them activating.

**Comment by Keader** [comment]
Yes I was testing alone. It really works. However still does not work properly. 3 stars should be active ... however is activating only 1. (Test 2 characters). Moreover they should not be selectable

**Comment by Keader** [comment]
Spell needs ignore LoS for active all stars xD

**Comment by Keader** [comment]
3e7b7e415e3abdad9bde459c83cb25548130b1f6
