### ISSUE TITLE
Battle.net Error 114

### ISSUE THREAD

**Issue by Atraxys** [TrinityCore/TrinityCore#15045]
Lastest commit.
No error during compilation, extraction
patched executable launched in administrator mode
![wowscrnshot_071015_011715](https://cloud.githubusercontent.com/assets/10885309/8609148/55a83428-26a2-11e5-8175-015a9850b733.jpg)

Wow-64_Patched.exe create by connection_patcher compile on debian 8 server

**Comment by Aokromes** [comment]
You need to use wine to patch wow.exe
