### ISSUE TITLE
[3.3.5a] Invi (mage) causes Stealth (rogue) drop on the arena

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15044]
b574c99

https://www.youtube.com/watch?v=pPoOr7oAB_8
https://www.youtube.com/watch?v=LEaXXwGti9I

Happens only on arenas. It is a critical bug (probably happens only with mages).

Explanation: 

first problem:
Be a Rogue
Use Stealth
Enter the arena versus a Mage
Come to the Mage
Mage uses Invi
Get revealed 

second problem:
Also, Invi aggroes every mob in it's 'range'.

**Comment by P-Kito** [comment]
It's because of invis I believe.

**Comment by selenir** [comment]
Yes, Invi, checked. Inv is totally bugged. When casting it, everything in 10 yards is on your aggro.

**Comment by Rushor** [comment]
```c++
case 66:    // Mage Invisibility
case 35009: // Trigger Spell from Invisibility
       spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_INITIAL_AGGRO;
```

try this in spellmgr.cpp in LoadDbcDataCorrections

**Comment by robinsch** [comment]
On TBC 2.4.3 this is also caused by Pain Supression, I don't know if it is a error in 3.3.5

**Comment by Laintime** [comment]
selenir  not confirm,check you commits

**Comment by Goatform** [comment]
I cannot confirm this.

**Comment by selenir** [comment]
Rushor, not working.

**Comment by Raydor** [comment]
Can't confirm.

**Comment by Rushor** [comment]
the stealthremove after using invis is wrong > https://youtu.be/j0eNi8LM4LU
tested on cleantc right now

robinsch has a fix for the aggroissue

**Comment by selenir** [comment]
How to get to him here, on Github :D ?

**Comment by Goatform** [comment]
Try something like this:

``` diff
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -2997,6 +2997,8 @@ void SpellMgr::LoadSpellInfoCorrections()
                break;
+            case 66:    // Invisibility
+            case 35009: // Invisibility
+            case 32612: // Invisibility
+                spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_INITIAL_AGGRO;
+                spellInfo->AttributesCu |= SPELL_ATTR0_CU_NO_INITIAL_THREAT;
+                break;
            case 61407: // Energize Cores
            case 62136: // Energize Cores
            case 54069: // Energize Cores

**Comment by Rushor** [comment]
spellInfo->AttributesCu |= SPELL_ATTR0_CU_NO_INITIAL_THREAT;

is handled in db now

**Comment by Goatform** [comment]
Actually, you are right. I forgot that it's changed since I never implemented it in my core.

**Comment by robinsch** [comment]
Correct fix:
```sql
UPDATE `spell_dbc` SET `AttributesEx3`='196608' WHERE (`Id`='35009');
```

**Comment by selenir** [comment]
I love you, such dev

**Comment by JarGames** [comment]
Guys, it still doesn't work.

**Comment by selenir** [comment]
Guys, I'm sorry, but does it work for someone?

**Comment by Rushor** [comment]
yes me - i have no time to proof this with another vid
