### ISSUE TITLE
Core: Melee damage [3.3.5]

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#15056]
I've run tests on warriors and feral druid with basic builds dealing raw melee damage.

-- Fury Warrior:
I used https://github.com/TrinityCore/TrinityCore/issues/6375 to test it correctly

- dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8638341/6f740900-28b8-11e5-9863-6baef3ad2e17.png)

- expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8638344/76876caa-28b8-11e5-9490-73dc3bdecd85.png)

-- Arms Warrior:

- dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8638357/dd7dae42-28b8-11e5-9f5c-d021cdcf140e.png)

- expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8638358/e517d0ce-28b8-11e5-8b18-4a740863707b.png)

-- Feral Druid:

- dealed:
![image](https://cloud.githubusercontent.com/assets/4329612/8638277/7008a94a-28b6-11e5-9083-d5ac3bf423a6.png)

- expected:
![image](https://cloud.githubusercontent.com/assets/4329612/8638320/f740bcb2-28b7-11e5-8f45-3a81ee3eb784.png)

It seems like there is some sort of misscalculation on weapon damage that also extends to weapon damage based spells (https://github.com/TrinityCore/TrinityCore/issues/6375#issuecomment-120456307)

23e4472d14bbf24722277d9d49c62ea7e39821c7

**Comment by ccrs** [comment]
best point to start is here https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Unit/StatSystem.cpp#L387

**Comment by ariel-** [comment]
Do the 'expected' numbers factor in target armor/resilience?

**Comment by Golrag** [comment]
lvl 80 warrior, no talents & lvl 1 gear & no stance:
minimum without armor: 126
maximum without armor: 129

tested on level 80 training dummy with 9729 armor, so 38.976% damage reduction.

Expected minimum: 126 * (1 - 0.38976) = 76.89024
Expected maximum: 129 * (1 - 0.38976) = 78.72096


![](http://puu.sh/iYFzR/3b8f114047.jpg)

**Comment by ccrs** [comment]
@Golrag, its not that easy. Im not duscussing armor damage mitigation, im referring to proper weapon damage result (and there are far more formulas involved).

@ariel- indeed, drdamage takes into account both of them.

**Comment by ccrs** [comment]
warrior builds used:

- fury:
![image](https://cloud.githubusercontent.com/assets/4329612/8672297/4d0e2ea6-2a2d-11e5-89c7-3d5831033783.png)
![image](https://cloud.githubusercontent.com/assets/4329612/8672304/57c796a2-2a2d-11e5-8702-69f7fc90a30c.png)
![image](https://cloud.githubusercontent.com/assets/4329612/8672313/6d1dbd10-2a2d-11e5-9d6e-18dd11f5bb5b.png)
