### ISSUE TITLE
Fix for Mana Wyrm

### ISSUE THREAD

**Issue by Xunil1337** [TrinityCore/TrinityCore#15054]
```sql
-- Mana Wyrm is NOT a Questgiver
UPDATE `world`.`creature_template` SET `npcflag`=0 WHERE  `entry`=15274;
```

Sry i do not know where is the right place to bring up fixxes... It is a Fix for 4.3.4 Sql !

Close it or let it open ... 

Trinity Core 4.3.4

**Comment by DDuarte** [comment]
See #12752

**Comment by Xunil1337** [comment]
Okay... i use the archived core on my repo i working again on a public core and i was not secure.. is it in or not ... but thanks :)
