### ISSUE TITLE
[DB/Quest] Hellfire Fortifications - Blue Dailyflag missing above Head

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15051]
rev: https://github.com/TrinityCore/TrinityCore/commit/5b078786a21ccc0ca27835e52cfaf3d381ee7f50
IDs:
http://wotlk.openwow.com/quest=10110
http://wotlk.openwow.com/quest=10106

Tiny issue here:
These two quests are marked as repeatable. But if you run towards the questgiver, the questmark is not updated to the BLUE questmark.

(and yes i didn't looked at the nonrepeatablequests like quest=13408/quest=13409, only the repeatable quests aren't working)

**Comment by Rushor** [comment]
oh well and the proof that it should be a blue mark :)

https://youtu.be/mXK05RMcODk

**Comment by Killyana** [comment]
Can you repeat 10110 or 10106?, personally I can't, the npc have the quest mark but doesn't propose any, also if you .quest add 10106 you can not completed it.

**Comment by Rushor** [comment]
oh well it's just the issue that the flag for  quest10110/10106 does not become blue after you rewarded quest=13408/quest=13408 - repeatable is the wrong name here since it is a dailyquest

a video for this to make shure what's the issue. while starting the video i already rewarded the mainquest quest=13408/quest=13408

link: https://youtu.be/Bq5xbDEagso

**Comment by Killyana** [comment]
Ok, so this quest was repeatable than blizzard change it to daily, the problem with the quest mark without a quest comes from a wrong condition.
``` sq
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry` IN (13410, 13411);
UPDATE `quest_template_addon` SET `AllowableClasses`=32 WHERE `id` IN (13410, 13411);

**Comment by Rushor** [comment]
kay then, time to search a bit for the field in dbcs which adds the blue mark :D

**Comment by Killyana** [comment]
In your video the quest mark is blue because the quest is repeatable and not daily, you can see after completing the quest the npc propose it a gain, if you change the Flags and th specialflags to make the quest repeatable and not daily it will turn blue.

**Comment by Rushor** [comment]
kay then maybe

```sql
UPDATE `quest_template` SET `Flags`=136 WHERE  `Id` IN (10110, 10106);
```

but this didn't changed it :/

**Comment by Killyana** [comment]
Flags 136 only make the quest repeatable for me. But as I said the quest must be Type: Daily PvP as indicated on wowhead.

**Comment by Rushor** [comment]
saw some similar quest which behaves like that: quest=12288

i even copied the same flags/flagextras to the bcquest and the mark was still the same yellow one - strange

**Comment by Killyana** [comment]
From http://wowwiki.wikia.com/Quest
Daily quests:
In  Burning Crusade most quests of this type appear with the standard marker (Quest Avail 16x16), regardless of how often you do them, but in  Wrath of the Lich King several quest appear with the RRQ marker (RRQ Avail 16x16) that count against your daily quest limit.

**Comment by Rushor** [comment]
well then, thanks for this research :)
