### ISSUE TITLE
[3.3.5a] Dying inside a dungeon

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15050]
If you are a gm, you can enter any dungeon/raid with gm mode set to on ignoring all requeriments.
However, if you later turn gm off, and you die inside, since you are gm off and can't chat commands when you are died, you can't enter again the instance to revive so you are forced to revive in angel.

Suggestion: Ignore dungeon requirements when you are in ghost mode, as this can also happen to any player who has died and has expelled from group.

**Comment by joschiwald** [comment]
you can use commands on other channels like group or guild, even you are not in group/guild and dead

**Comment by StormBytePP** [comment]
Yes, that's true, but what happens to not GM accounts? When dead and expelled from group? I guess they can no longer enter dungeon

**Comment by DDuarte** [comment]
Don't guess :) verify that there is an actual issue and then report it.

**Comment by StormBytePP** [comment]
Urgs sorry, It seems I am a bit tired today, next time I will do a better check :)

**Comment by MitchesD** [comment]
also you can whisper yourself
