### ISSUE TITLE
[3.3.5a] Professor Putricide Abomination - Vehicle not healable

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15067]
b574c99

Yes, there is an opened issue with healing, but A PLAYER.

You cannot heal the abomination (not sure about normal mode, because it's not needed there). This bug makes the boss impossible to kill.

Caused by that it's a vehicle - they cannot be healed.

**Comment by Smokexyz** [comment]
I don't think this is coded entirely, a player must become the abomination after which you will gain a special set of skills for the encounter.

**Comment by Rushor** [comment]
connection to https://github.com/TrinityCore/TrinityCore/issues/13944
BUT they are seperated issues

**Comment by Keader** [comment]
I can reproduce this on rev ac727ab208e592c7a2d01ebe321944402860c3ae

![wowscrnshot_011916_163314](https://cloud.githubusercontent.com/assets/7120913/12429695/70d72ed2-beca-11e5-8e9d-7a64d7c158c2.jpg)
