### ISSUE TITLE
Vmaps not support?

### ISSUE THREAD

**Issue by Ziex0** [TrinityCore/TrinityCore#15068]
Anyone else got this problem? i download Trinitycore 6.x today.
cmake - compiling all okey until i start Worldserver.exe
then crash at here : 

http://pastebin.com/finCQ3qX

Need help..:D

**Comment by DDuarte** [comment]
Check your MySQl install. libmysql.lib must match the architecture you are compiling.

**Comment by DDuarte** [comment]
What MySQL version do you installed?

**Comment by Ziex0** [comment]
http://dev.mysql.com/downloads/windows/installer/5.6.html
I just follow all from here
http://collab.kpsn.org/display/tc/Requirements
another thing wrong maybe?

**Comment by DDuarte** [comment]
Follow this: http://collab.kpsn.org/display/tc/Application+Error%3A+0xc000007b

**Comment by Ziex0** [comment]
Fixed.. Thanks :+1:

**Comment by DDuarte** [comment]
What did you do exactly to fix it?

**Comment by Ziex0** [comment]
Add copy paste manual for this file libeay32.dll , libmysql.dll also libzmq-v120-mt-4_0_4.dll
Take each file form each path that i use.
coz idk what wrong on my compiled folder as release .. there only 4 item.

http://prntscr.com/7s48qd
