### ISSUE TITLE
[3.3.5a] [Quest ID: 10072] learning the word quest is given to incorrect character class by incorrect NPC

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15069]
rev: https://github.com/TrinityCore/TrinityCore/commit/a6c7f7889e6b682c344facc16d3d7df009094a2a

I am trying a hunter in 3.3.5a, a blood elf one. However, I realized that this quest has 2 wrong information.
1.- It is not respecting character class mask (if it has any, I did not find under quest_template any requiredclass, only I found requiredRaces), so it is being offered to a hunter (and also possibly to be offered to other classes, but I did not test that).
2.- It is offered by the wrong NPC, currently, it is offered by Ranger Sallina (NPC ID: 15513), which is the hunter's trainer. According to wowhead page, it should be offered by Matron Arena (NPC ID: 15284) instead (it also makes more sense, as Matron Arena is priests' instructor).

**Comment by Rushor** [comment]
'Well Watcher Solanian' is the questname of 10072

**Comment by Aokromes** [comment]
Swaped values anyway.

```sql
UPDATE `creature_queststarter` SET `quest`=10072 WHERE `id`=15284 AND `quest`=10070;
UPDATE `creature_queststarter` SET `quest`=10070 WHERE `id`=15513 AND `quest`=10072;

**Comment by StormBytePP** [comment]
Ouch! My bad! This seems a problem in translation, as I use loc6, it contains a totally different quest title/description (Aprender la palabra means: Learning the word in english):

SELECT Id,Title_loc1, Title_loc2, Title_loc3, Title_loc4, Title_loc5, Title_loc6 FROM locales_quest WHERE Id=10072;
+-------+------------+------------------+-------------------+------------+------------+---------------------+
| Id    | Title_loc1 | Title_loc2       | Title_loc3        | Title_loc4 | Title_loc5 | Title_loc6          |
+-------+------------+------------------+-------------------+------------+------------+---------------------+
| 10072 |            | Apprendre le mot | Das richtige Wort |            |            | Aprender la palabra |
+-------+------------+------------------+-------------------+------------+------------+---------------------+

So, here happens a strange thing: In wowhead, quest ID 10072 is in fact learning the word: http://www.wowhead.com/quest=10072/learning-the-word and also, carbonite addon for 3.3.5a tells 10072 as quest ID, which is the one I reported. However, it seems that english texts are either wrong or translation is, because both sides say completelly different things for the same quest ID.

**Comment by StormBytePP** [comment]
SELECT LogTitle,QuestDescription FROM quest_template WHERE Id=10072;
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| LogTitle              | QuestDescription                                                                                                                                                                                                                        |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Well Watcher Solanian | And now, I need for you to do something.$B$BWell Watcher Solanian is in need of your services.  You would do well to ingratiate yourself with him.$B$BHe awaits you on the exterior platform that the ramp in this chamber leads up to. |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

So, translated texts tells user to learn the priest spell, and use it, but english text is only saying to talk with an npc.

**Comment by StormBytePP** [comment]
If you say the correct one is the english one, I can update spanish translation :)

**Comment by Rushor** [comment]
problem is that we got > catatranslation for serveral locales, 
most important fix for now is the one from aokromes

**Comment by StormBytePP** [comment]
Ok, I will try to locate the old spanish translations for wotlk and try to provide a sql update at least for them.

**Comment by Killyana** [comment]
This will fix all this quests:
``` sql
UPDATE `quest_template_addon` SET `AllowableClasses`=128 WHERE `id`=10068;
UPDATE `quest_template_addon` SET `AllowableClasses`=2 WHERE `id`=10069;
UPDATE `quest_template_addon` SET `AllowableClasses`=4 WHERE `id`=10070;
UPDATE `quest_template_addon` SET `AllowableClasses`=8 WHERE `id`=10071;
UPDATE `quest_template_addon` SET `AllowableClasses`=16 WHERE `id`=10072;
UPDATE `quest_template_addon` SET `AllowableClasses`=256 WHERE `id`=10073;

UPDATE `creature_queststarter` SET `quest`=10068 WHERE `id`=15279 AND `quest`=10069;
UPDATE `creature_queststarter` SET `quest`=10069 WHERE `id`=15280 AND `quest`=10068;
UPDATE `creature_queststarter` SET `quest`=10073 WHERE `id`=15283 AND `quest`=10073;
UPDATE `creature_queststarter` SET `quest`=10072 WHERE `id`=15284 AND `quest`=10070;
UPDATE `creature_queststarter` SET `quest`=10071 WHERE `id`=15285 AND `quest`=10071;
UPDATE `creature_queststarter` SET `quest`=10070 WHERE `id`=15513 AND `quest`=10072;

**Comment by StormBytePP** [comment]
I submitted a pull-request in a try to remove all cataclysm changes in quests that are present at least in spanish translations (Some quests with other texts, like this reported ones), and many other quests I found that changed the ending location in texts and more.

Feel free to review it. I am sorry I could only update spanish translations as I don't speak the other languages.
