### ISSUE TITLE
[3.3.5] Crash Player::UninviteFromGroup 

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#15071]
http://pastebin.com/xAj80wfD
af8e9738036e2947e31b1f11bc01f7565f988376

ubuntu server 64.

**Comment by jackpoz** [comment]
just for info, did you apply any custom change ?

**Comment by tkrokli** [comment]
Looks like some form of duplicated source tree, the folder /root/aura-3.3.5/ suggests modifications :
- /root/src/server/worldserver/Main.cpp
- /root/aura-3.3.5/src/server/worldserver/Main.cpp

**Comment by Voidx** [comment]
This problem was detected on all trinity versions. I only use trasmogr

**Comment by tkrokli** [comment]
Transmogrification is custom code for the 3.3.5 branch. That is essential information to put in the OP.

**Comment by Frytiks** [comment]
That have nothing to:do with transmog ...

**Comment by jackpoz** [comment]
what are your https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L387 and https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L2270 settings ?

**Comment by Rochet2** [comment]
Maybe TC could add some asserts or similar to functions like group and similar that should always be excuted from main thread by using `std::thread::get_id`. Could be useful for having some invalid thread checking other than guessing and debug only.

**Comment by jackpoz** [comment]
The cause of this crash is still unknown so it's too early to think about solutions. A crash report with no locals makes it even harder.

**Comment by jackpoz** [comment]
still waiting for the infos asked at https://github.com/TrinityCore/TrinityCore/issues/15071#issuecomment-125163752

**Comment by Rushor** [comment]
@Voidx: this issue is still present?

**Comment by Voidx** [comment]
Hi, MapUpdate.Threads = 2
BattleGround.PremadeGroupWaitForMatch = 1800000

**Comment by Xxxhackerxxx** [comment]
confirm .

**Comment by jackpoz** [comment]
> confirm .

it's useless without a proper crash report

**Comment by Treeston** [comment]
http://pastebin.com/53zXVb5u another crash dump from #17637

**Comment by Aokromes** [comment]
near 1 year since the last crashlog, if this bug is still valid post one NEW ticket with updated core.
