### ISSUE TITLE
[3.3.5] Spells Mortar and Fire Cannon hitting friends

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15080]
spell 62358 = [Fire Cannon]
spell 62634 = [Mortar]

Spells used by Salvaged Demolisher and Salvaged Siege Engine (weapons)
Both spells are giving damage in friendly units

Test on rev fae826958915673338868d0b3b273860630638fb

Related: 6a15216380a2e44302abdc31fb37e9dd3656761b

Suggested correction:

```sql
UPDATE `conditions` SET `SourceGroup`=2 WHERE `SourceTypeOrReferenceId`=13 and`SourceGroup`=3 and`SourceEntry` IN (65044,65045);
```

There's already entry for those spells in DB, but for an inexistent effect. 
In current TDB, is for EFFECT_2,   and should be for EFFECT_1

**Comment by joschiwald** [comment]
Ulduar vehicle conditions are total wrong

**Comment by Keader** [comment]
The first floor of Ulduar as a whole seems wrong hehe

**Comment by jackpoz** [comment]
> There's already entry for those spells in DB, but for an inexistent effect. 
> In current TDB, is for EFFECT_2, and should be for EFFECT_1

Is there a db error on load about this case ? otherwise it should be added

**Comment by sirikfoll** [comment]
Anyone can confirm if these spell should hit the vehicles? In current `conditions`, it can

**Comment by Keader** [comment]
When loading does not give errors Jack

**Comment by sirikfoll** [comment]
If shouldn't hit the vehicles, this may solve it:
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN (65044,65045) AND `ConditionValue2` IN (33060,33109,34045,33062);
```

**Comment by joschiwald** [comment]
```sql
-- Removed useless conditions
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN (62290,62307,62357,62489,62635);
-- Adjusted incorrect conditions
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry` IN (62363,65044,65045);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition` ,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,2,62363,0,0,31,0,3,33214,0,0,0,'','Flame Leviathan - Anti-Air Rocket'),
(13,1,65044,0,0,32,0,0x18, 0,0,0,0,'','Flame Leviathan - Flames'), -- should hit everything
(13,2,65044,0,0,31,0,3,33090,0,0,0,'','Flame Leviathan - Flames'),
(13,1,65045,0,0,32,0,0x18, 0,0,0,0,'','Flame Leviathan - Flames'), -- should hit everything
(13,2,65045,0,0,31,0,3,33090,0,0,0,'','Flame Leviathan - Flames');
```

**Comment by Keader** [comment]
joschiwald fix is better and work :+1:

**Comment by Keader** [comment]
Related: #4078

**Comment by Killyana** [comment]
This can be pushed?

**Comment by joschiwald** [comment]
yes i guess
