### ISSUE TITLE
[3.3.5][Core/Spell] Mind Control - Diminishing return issue 

### ISSUE THREAD

**Issue by Natureknight** [TrinityCore/TrinityCore#15088]
Mind control applies a diminishing for buff and debuff of the spell. 

Issue: 
- Open 3 wow clients and login with different characters (Priest and 2 more random characters)
- Go to Ring of Trials (so they all will be enemies)
- Cast Mind Control on random player 1 (Mind Control buff is applied to the priest, and mind control debuff is applied to the random player 1 (current target))
- Cast Mind Control on random player 2 right after this: 

THERE is the issue, the buff for priest is at half duration, but the debuff for random player 2 is on full duration. 

When the buff for the priest expires, random player 2 is still in Mind Control, but priest now wont be able to cancelaura Mind Control because the buff for him is already gone bcuz of the diminishing from previous mind control on random player 1.

Priest's MC buff diminishing should be equal to current target diminishing state for MECHANIC_CHARM

3.3.5a
Hash: a6c7f78

**Comment by robinsch** [comment]
Don't apply DRs to self.

**Comment by Raydor** [comment]
Confirmed https://github.com/TrinityCore/TrinityCore/commit/8d6839e468c5af7b1096895e22b622c62ea7865e

**Comment by chaodhib** [comment]
Diminishing returns only apply to debuff, right?

I can nor test nor compile where I am right now but maybe this would help. This should apply DRs only on debuffs.
```` diff
diff --git a/src/server/game/Spells/Auras/SpellAuras.cpp b/src/server/game/Spells/Auras/SpellAuras.cpp
index e6f01de..8eda48b 100644
--- a/src/server/game/Spells/Auras/SpellAuras.cpp
+++ b/src/server/game/Spells/Auras/SpellAuras.cpp
@@ -2420,7 +2420,7 @@ void UnitAura::_ApplyForTarget(Unit* target, Unit* caster, AuraApplication * aur
     Aura::_ApplyForTarget(target, caster, aurApp);
 
     // register aura diminishing on apply
-    if (DiminishingGroup group = GetDiminishGroup())
+    if (!aurApp->IsPositive() && DiminishingGroup group = GetDiminishGroup())
         target->ApplyDiminishingAura(group, true);
 }
 
@@ -2429,7 +2429,7 @@ void UnitAura::_UnapplyForTarget(Unit* target, Unit* caster, AuraApplication * a
     Aura::_UnapplyForTarget(target, caster, aurApp);
 
     // unregister aura diminishing (and store last time)
-    if (DiminishingGroup group = GetDiminishGroup())
+    if (!aurApp->IsPositive() && DiminishingGroup group = GetDiminishGroup())
         target->ApplyDiminishingAura(group, false);
 }
````
Also, some code should handle the fact that the buff applied to the priest should have the same duration as the debuff on the target of the spell (after factoring any DR). If i'm not mistaken, this should be in an AuraScript for the second effect (Apply Aura: Dummy) of the spell Mind Control.

**Comment by elecyb** [comment]
Try this:
https://github.com/elecyb/TrinityCore/commit/f09e348f50e6c32de6cfc2e48c8a50ba8c257f72
Fixes the DR desync for MC spells, also fixes redirected spells not doing any effect (damage) if destination target is out of LoS.

**Comment by Jenkyins** [comment]
confirmed on b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Aokromes** [comment]
If anything here is valid, plz create a PR for it.
