### ISSUE TITLE
[6.x][Crash]

### ISSUE THREAD

**Issue by YaGa** [TrinityCore/TrinityCore#15085]
rev. b5c5442d039f 

Crash log: http://pastebin.com/THrtbSs5

**Comment by msoky** [comment]
i have this problem too https://github.com/TrinityCore/TrinityCore/issues/15072
crashlog: http://pastebin.com/Py1Lz6HV
and stil persist to latest revision https://github.com/TrinityCore/TrinityCore/commit/63d1d989a0d058a863b8d9b17109b4fcb34f1dd9

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e2fb3bbd466641c794438933e636d63ebf19432e
