### ISSUE TITLE
[3.3.5a] Dungeon Finder: Sometimes cannot add a single person (as a fifth person)

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15084]
b574c99

There is a bug, that when you queue to a Finder, there happen some strange things like:

- it shows missing players, when there are no missing players (group is 5, 3dps, heal, tank)
- it shows that for example healer is missing, but a DPS is missing

Also, when entering the que by solo or in 2-group party its 99% impossible to join the dungeon. When creating 3-4-5 os its kind of instant (yeah, 5 is instant :D). It doesn't happen always, but quite often. Tested on a server with 300 ppl online, tried with various mixes of partymembers, slots etc.

**Comment by Aokromes** [comment]
Duplicate.

**Comment by Aokromes** [comment]
#14331

**Comment by selenir** [comment]
No the same, because these bugs happen also before someone leave/get kicked - just on a fresh, new party. But fine! :dancers:
