### ISSUE TITLE
Western Plagueland - mobs do not evade and attacks player corpse

### ISSUE THREAD

**Issue by Sidious78** [TrinityCore/TrinityCore#15094]
Build: a9d00b9 
DB: 335.59

Skeletal Flayer: id 1783
Slaving Ghoul: id 1791

You can see the issues here: https://youtu.be/3EANZA97tls

These mobs can easily be pulled way out of their aggro zone, and do not evade. When they kill a player, they will remain on site and attack the corpse. Even after the player respawns!

I have seen this bug before, and I do think it's related to undeads. However, I did not take notes the first time I encountered it.

**Comment by Aokromes** [comment]
Strange, they even ignore .gm on / .gm visible off

**Comment by Killyana** [comment]
Problem with the aura 3391 set by SAI
