### ISSUE TITLE
[3.3.5][Core/Creature] Flying and moving NPCs vs gossip/quest hello action

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#15093]
Rev: https://github.com/TrinityCore/TrinityCore/commit/8d6839e468c5af7b1096895e22b622c62ea7865e (fresh compile)
DB: TDB 335.59

Problem1: When you interact with NPC which has waypoint_data (path) and inhabittype & Air (flying, for ex.: Olrun the Battlecaller (29047)) it will stop and freeze in air, without flying animation. But when it moving with waypoint - it flying.
Problem2: When you interact with NPC which has movement_type 1 (random) it will NOT stop, just keep moving in random direction.

For tests: Create DK and get quest "Death's Challenge" (.quest add 12733). Quest giver, Olrun the Battlecaller (.go creature 128739), has 1st problem and Death Knight Initiate (.go creature 129532) has 2nd problem.

**Comment by tkrokli** [comment]
TrinityCore rev. 9578d91d2794 2015-07-14 21:54:54 +0200 (3.3.5 branch) (Win64, Release)
DB: TDB 335.59 + updates

Problem 1 confirmed, http://www.wowhead.com/npc=29047/olrun-the-battlecaller stops, standing in the air (just swaying slightly), no flying animation (can't remember if the NPC has animation on retail, though).
Problem 2 also confirmed, though the NPC pathing is not long enough to cause any big trouble. I have seen some other NPC with a longer path, making it really annoying, though don't remember which one at the moment (have to follow up on that at a later time, thinking that this could be more than just cosmetic).

**Comment by killradio** [comment]
@tkrokli you can easily find video with this quest on youtube (for wotlk, for ex.: https://www.youtube.com/watch?v=L4Gy9G4WsQE). I think all creatures which can fly should fly/levitate when above the ground.

Another one observation, if you set WAYPOINT_MOVE_TYPE_TAKEOFF for flying creature, it will has wrong walking animation, but right standing animation while being interrupted with gossip hello.

For tests:
```sql
-- Olrun the Battlecaller
UPDATE `waypoint_data` SET `move_type` = 3 WHERE `id` = 1287390;
```

**Comment by tkrokli** [comment]
Looking at your comment above (https://github.com/TrinityCore/TrinityCore/issues/15093#issuecomment-121841283), it looks as if we need a SAI for Olrun the Battlecaller to implement the use of `WAYPOINT_MOVE_TYPE_TAKEOFF` for the interrupted stand state when in dialog with the player, while still using the existing flying animation for the rest of the pathing. Not sure when I will get time to look at this, but I am sure there are at least 4 TC users here on github who can do it faster than me. :smirk_cat:

**Comment by killradio** [comment]
You ill write SAI for each creature with inhabittype & 4 and waypoints? =]

`WAYPOINT_MOVE_TYPE_TAKEOFF` already implemented in WaypointMovementGenerator and in case it calls `init.SetAnimation(Movement::ToFly)`, but if commented right, it should play animation __after__movement done.
```cpp
        /* Plays animation after movement done
         * can't be combined with parabolic movement
         */
        void SetAnimation(AnimType anim);
```

**Comment by killradio** [comment]
Another one problem: NPCs with InhabitType = 4 during combat, after some events can land the ground and walk around. Sometimes, after evade/reset they lost flying animation and walk in air.

**Comment by Rushor** [comment]
> Another one problem: NPCs with InhabitType = 4 during combat, after some events can land the ground and walk around. Sometimes, after evade/reset they lost flying animation and walk in air.

another issue:

1) start fighting with a flying creature (inhabit 4) without a flying mount (only as player without any mount)
2) the creature will fall to the ground and is no longer able to attack the player

The position z is updated wrong maybe

**Comment by offl** [comment]
Looks outdated, would be nice to test again all mentioned cases

**Comment by illfated** [comment]
Good point. There have been so many other interesting issues, so I had forgotten these details completely.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=21657/neltharaku (SMV/Netherwing) gossip & movement works just fine, if that matters.

**Comment by offl** [comment]
> Problem2: When you interact with NPC which has movement_type 1 (random) it will NOT stop, just keep moving in random direction.

Can't reproduce in 26cc8e1e2032
