### ISSUE TITLE
[3.3.5] Lord Alexei Barov in Scholomance.... flying away :-D

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#15091]
There is a very strange and funny bug i've encountered in bosses who are stationed in low water. When the group aggro him they fly away over the ceiling... then they come back from i don't know where (sometimes with mobs)

Try it with Lord Alexei Barov in Scholomance but happened with a Dire Maul boss too which was sit in a water pool (an elemental boss). The moment you ago them, they fly away ah ah ah

DB: 335.58
Trinity Core rev 0b1355b

**Comment by Killyana** [comment]
Probably related to https://github.com/TrinityCore/TrinityCore/issues/9753 try to change the InhabitType to be sure that's related to the water.

**Comment by ikir83** [comment]
This is the best bug ever :)

**Comment by Rushor** [comment]
do you already tried what killyana said @ikir83 ?

look at the field inhabittype in the creature_template

**Comment by ikir83** [comment]
@Killyana @Rushor 
inhabittype is 3

Should i change it?

**Comment by Killyana** [comment]
Tested with the different inhabittype, the npc go to  the top floor on aggro, it's the same problem as the issue 9753.
You can set the inhabittype=7 as a temporary fix.

**Comment by Kittnz** [comment]
What's in the sniffs?

**Comment by Nyeriah** [comment]
Disabling mmaps for him also works.

```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|0x20000000 WHERE entry = 10504;
```

**Comment by Trisjdc** [comment]
This should be reopen, it's a mmap issue.

**Comment by Killyana** [comment]
general issue: https://github.com/TrinityCore/TrinityCore/issues/9753

**Comment by Trisjdc** [comment]
No, that's something else.

This one is specifically related with mmaps. That one is related with height searching. Plenty of Map::GetHeight handling calls with "z + XX", and this extra XX causes that sort of issues like that one above.
