### ISSUE TITLE
[3.3.5] Comet's Trial wrong icd

### ISSUE THREAD

**Issue by Crit1** [TrinityCore/TrinityCore#15096]
The internal cooldown of the trinket Comet's Trail is only 15 seconds, making it the best trinket ingame for a lot of classes. The icd should be the same as similar trinkets, 45 seconds.

Trinket: http://wotlk.openwow.com/item=45609

Proof for short icd: http://imgur.com/FbnjNvq

Proof for 45s retail icd: 
http://forums.elitistjerks.com/topic/71616-unholy-dps-335-king-of-anything/
http://www.wowhead.com/item=45609/comets-trail#comments (bottom comment)
http://hunterloot.com/?full=1&s=trinket (mouseover the question mark in comet's row)

Core revision: e7d12ea740e7 2015-07-11 21:11:27 +0000 (stealth_work branch) (Unic, Release)
https://github.com/pete318/TrinityCore/tree/stealth_work
Latest commit applied: 5bbd7cff4c98b59673d03416e6fff83d7db4d950

**Comment by Keader** [comment]
try this:
```sql
UPDATE `spell_proc_event` SET `Cooldown`='45' WHERE `entry`='64786';
```

**Comment by pete318** [comment]
Oddly enough, in the original "issue" reported in 2010 about ICDs all being missing this item already had a 45s timer:

https://code.google.com/p/trinitycore/issues/detail?id=2592

It was actually in a commit in 2012:

https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/sql/old/3.1.3/04360_world_spell_proc_event.sql

Most around it were 45.. I wonder if it was simply a typo.

In any case @Crit1 I added this change to the server you were testing on. Feel free to test some more with the change applied.
