### ISSUE TITLE
[3.3.5] Wrong armor value WotLK raid bosses

### ISSUE THREAD

**Issue by Crit1** [TrinityCore/TrinityCore#15106]
All raid bosses currently have 10763 armor, while it should be 10643. I have no idea where 10673 came from as I can't find any discussion from retail where that value is used. 

Proof for current:
http://i.imgur.com/dCP6WOY.jpg
http://i.imgur.com/6m8vWFF.jpg
#2749 tested on bosses too

Proof for correct value:
http://web.archive.org/web/20130209181158/http://elitistjerks.com/f47/t37804-warrior_fury_compendium/#Quick_Reference
http://web.archive.org/web/20100402061223/http://elitistjerks.com/f31/t29453-combat_ratings_level_80_a/p18 
If more proof is required., I found multiple videos from retail from which it can be calculated.

Core revision: e7d12ea740e7 2015-07-11 21:11:27 +0000 (stealth_work branch) (Unic, Release)
https://github.com/pete318/TrinityCore/tree/stealth_work
Latest commit applied: 5bbd7cff4c98b59673d03416e6fff83d7db4d950

**Comment by Rushor** [comment]
because the 7 is over the 4 in numblock - someone made a typo

**Comment by Rushor** [comment]
```sql
UPDATE `creature_classlevelstats` SET `basearmor`=10643 WHERE `level`=83 AND `class`=1;
UPDATE `creature_classlevelstats` SET `basearmor`=10643 WHERE `level`=83 AND `class`=2;
```

**Comment by ccrs** [comment]
![image](https://cloud.githubusercontent.com/assets/4329612/8758905/ad192ca0-2cea-11e5-87b6-8b4f365dab95.png)
 @Rushor what about the other classes?

**Comment by Rushor** [comment]
@ccrs - i dunno i got no other proofs for them,

the only thing i got is:

http://forums.elitistjerks.com/topic/37210-wrath-boss-armor-testing/
http://www.qqpewpew.com/2008/12/revisiting-armor-penetration-in-wrath/

EDIT: as of Nov 30, 2008, testing has been done on all bosses and it appears that for now, all bosses have the same armor value shown on Maexxna: 13083 armor. This is true for heroics and regular versions of the bosses, and 10 and 25 man raid versions.

Posted 19 May 2009 - 10:09 PM
Bosses don't have 13,083 armor anymore.

Instead, they have 10,643 armor. The implications are:

**Comment by ccrs** [comment]
so bosses can't be CLASS_ROGUE or CLASS_MAGE?

**Comment by Killyana** [comment]
What about https://github.com/TrinityCore/TrinityCore/issues/13270 ?

**Comment by Rushor** [comment]
casternpcs - so no idea how the armourvalue should be

**Comment by ccrs** [comment]
There are lots of bosses with mana xd

**Comment by tkrokli** [comment]
@ccrs : But Paladins and Shamans use mana too. Mana in itself is not enough to determine the class.

**Comment by Rushor** [comment]
open up a new issue for the creatures with mana
