### ISSUE TITLE
[Core/Spell][Shaman] Grounding Totem - Missing Grounding

### ISSUE THREAD

**Issue by Nertx** [TrinityCore/TrinityCore#15108]
Currently it is not absorbing these spells:

Deep Freeze
http://wotlk.openwow.com/spell=44572  

Conflagrate
http://wotlk.openwow.com/spell=17962 

Dispel Magic
http://wotlk.openwow.com/spell=988

TrinityCore rev. d81f15759b29157354ef447a29e43bb665faff75

**Comment by Rushor** [comment]
huntertraps to no?

**Comment by robinsch** [comment]
Remove CheckTarget check at GetMagicHitRedirectTarget. It will return SPELL_FAILED_TARGET_AURASTATE because Grounding Totem is not frozen / affected by Immolate.

**Comment by tkrokli** [comment]
Grounding Totem - Missing Grounding? Sounds like a job for an electrician... ;-)

**Comment by Nertx** [comment]
@Rushor Yes, i tested it with Freezing Arrow and confirm

@robinsch Thanks man :+1:  Do you have a fix to traps also?

**Comment by Raydor** [comment]
@Nertx Tested the fix, it also works for traps.

**Comment by Keader** [comment]
In hunter traps did not work here.
rev 9889e6f73009c9d4b83d73dbe8e9dda658e0f9a2

@Raydor Which trap you tested? I tested all here, it did not work with none

**Comment by Raydor** [comment]
@Keader with all traps that returns true in IsFriendlyTo, like freezing trap or Immolation Trap. It should not redirect traps like Frost Trap.

**Comment by Keader** [comment]
Freezing Trap dont work

**Comment by robinsch** [comment]
It's not related to this!
