### ISSUE TITLE
DB/pages: Locales for page text

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15105]
TrinityCore rev. cec97f168c11
https://gist.github.com/Killyana/8b267e3e3ea2767a5873
Adding some missing pages, adding locales for French, German, Spanish and Russian.
French locales: 100% done
German locales: 93 entry to translate
Spanish locales: 177 entry to translate
Russian locales: 201 entry to translate

We need help from German, Spanish and Russian speakers to finish the missing pages.
To find texts that must be translated use this query:
(Change Text_loc3 to Text_loc6 for Spanish and Text_loc8 for Russian) 
``` sql
SELECT * FROM page_text WHERE id IN (SELECT entry FROM locales_page_text WHERE Text_loc3 IS NULL);
```
If you propose a translation specify if you translate the text by your own or give the source of the translation (wowhead, wowwiki ect...)

Updates: https://gist.github.com/Killyana/0d899a50a7ac064ce509

**Comment by Kinzcool** [comment]
Hum, the point of locales was that it was totally blizzlike stuff, hence no more need to have lesser good patches from people, but any handmade stuff is just shit and should stay away from TDB, IMO.

**Comment by Killyana** [comment]
I found all French locales on Internet, I just translate 4 or 5 lines,  the same can be done for the other locales I guess.

**Comment by Exodius** [comment]
If I am not mistaken, these are related to in-game books and stuff, right? Can't these be used (object 175731 used as an example)?

http://de.wowhead.com/object=175731
http://ru.wowhead.com/object=175731
http://es.wowhead.com/object=175731
