### ISSUE TITLE
[3.3.5] Upper black rock spire Pyroguard Emberseer

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#15100]
They seems all related to scripting the istance

The door leading to him seems to close too fast!
We needed full party to unlock the first boss Pyroguard Emberseer and no npc warlock was there (i've read players needed are just 3 but before warlock needs to be killed)

DB: 335.58
Trinity Core rev 0b1355b

**Comment by offl** [comment]
According to #19388 this is no longer valid.
