### ISSUE TITLE
DB/Misc: Stable Master Xon'cha has wrong npcflag in creature_template

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15117]
TrinityCore rev. 9578d91d2794 2015-07-14 21:54:54 +0200 (3.3.5 branch) (Win64, Release) 
DB: TDB 335.59 + updates

http://wotlk.openwow.com/npc=9988
http://www.wowhead.com/npc=9988/xoncha
NPC ID 9988, Stable Master Xon'cha in Orgrimmar, has only got `npcflag = 1` in creature_template.
This only gives him a gossip window, no menu option to access the stable slots from flag `4194304`.

A simple comparison between him and the nearest 2 stable masters in Razor Hill and Crossroads :
```sql
SELECT * FROM `creature_template` WHERE `name` IN ("Xon'cha","Shoja'my","Sikwa");
```
```
 entry  modelid1  name      subname        IconName  gossip_menu_id  faction  npcflag  speed_walk
------  --------  --------  -------------  --------  --------------  -------  -------  ----------
  9987      9262  Shoja'my  Stable Master  (NULL)              9821      126  4194305           1
  9981      9254  Sikwa     Stable Master  (NULL)              9821       29  4194305           1
  9988      9261  Xon'cha   Stable Master  (NULL)             11971       29        1           1
```
(Yes, I removed the unrelated/uninteresting columns from the output to simplify the overview.)

Suggested fix:
```sql
UPDATE `creature_template` SET `npcflag`= 4194305 WHERE `entry`= 9988 AND `name`= "Xon'cha";
```

**Comment by Appled** [comment]
I don't think 
```sql
AND `name`= "Xon'cha"
```
is needed because entry field in creature_template is an unique field.

**Comment by tkrokli** [comment]
Yes, I just had the impression that 2 qualifiers are recommended by TC to avoid errors. Maybe because some creatures exist in more than one state or phase. (Sorry, I don't remember where I saw it or who said it.) Anyhow, I think it is nice to have in case you don't remember who creature 9988 is. :-)

**Comment by Appled** [comment]
You are correct, it is recommend to use 2 qualifiers. Creatures can exist in multiple phases but usually they share the same entry id. And if they would have different id in different phases your query would affect still the creature whose id you specified in the query, with or without the second qualifier. Two qualifiers are mostly used, and is actually needed, in editing SAI tables. I think @Aokromes can confirm that you dont need the second qualifier here.

**Comment by Nyeriah** [comment]
Creature entries are unique. Creature template != creature. Just the entry suffices.

**Comment by tkrokli** [comment]
OK, thanks for the clarification. :-) Submitting my updated SQL query here:
```sql
-- Creature ID 9988 "Xon'cha" is a Stable Master, npcflag is 4194304+1
UPDATE `creature_template` SET `npcflag`= 4194305 WHERE `entry`= 9988;

**Comment by Aokromes** [comment]
btw. better:
```sql
UPDATE `creature_template` SET `npcflag`=`npcflag`|1|4194304
```

**Comment by tkrokli** [comment]
OK, I see. It is better to use that "add to existing value" method instead of overwriting the existing value.
BTW, do you TC devs prefer not to use any explanatory comments on queries like this one, maybe because it uses more storage space if it was used on all the updates to the world DB?
