### ISSUE TITLE
[6.x] Grunt login

### ISSUE THREAD

**Issue by vvizard100** [TrinityCore/TrinityCore#15112]
Hi, just updated to last rev and got this !

What steps will reproduce ?
Just launch your server then try to connect. 

What is the expected output ?
You're expected to log in.
Console will display : http://puu.sh/j3Z5k/25728823fc.png

What version of the core and database are you using? On what operating system?
Core : https://github.com/TrinityCore/TrinityCore/commit/f4536f38123c536d90733d047e1072b4dd88e910
DB : last available
OS : W8.1 x64

Thanks :)

**Comment by DDuarte** [comment]
You need to create an account using `.bnet account create username pass` and then login with that account. Username must be an email.

**Comment by vvizard100** [comment]
Hey ! Very fast answer, but yes I already know this xD
Look what I did : http://puu.sh/j3ZB9/12b3a3d70d.png

I've tested with all of these and still, it doesn't work. That's why I'm kinda lost. However, I'm not using a enUS client, hope it's not affecting it ?

**Comment by DDuarte** [comment]
Game version of your client? Perhaps you can screenshot the login screen

**Comment by vvizard100** [comment]
Yeah sure, here you go : http://puu.sh/j40bX/cdd4ca49d6.jpg

**Comment by Vincent-Michael** [comment]
Is your client patched?

**Comment by vvizard100** [comment]
Yeup :/

**Comment by Killyana** [comment]
I just installed a fresh server with French locales, the account was created without any problem.

**Comment by Helnesis** [comment]
Yeah, account creation do not have a problem, the problem this the login :s

**Comment by vvizard100** [comment]
exactly :P

**Comment by Killyana** [comment]
Well I don't have any problem to login.

**Comment by Helnesis** [comment]
Strange. We both have the same problem ... You have a USEN customer?

**Comment by Killyana** [comment]
No

**Comment by DDuarte** [comment]
Post your client's `Connection.log` file

**Comment by vvizard100** [comment]
https://ghostbin.com/paste/2w8v5

**Comment by Vincent-Michael** [comment]
try pls with 32bit client

**Comment by Helnesis** [comment]
Okay. I have the same problem as vvizard100
Connection log with 32 bits client : https://ghostbin.com/paste/2w8v5

**Comment by Vincent-Michael** [comment]
check your table with this querys:

```sql
ALTER TABLE `battlenet_accounts` CHANGE `os` `os` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '';
ALTER TABLE `account` CHANGE `os` `os` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  '';
```

**Comment by Helnesis** [comment]
Okay I executed querys and still the same problem

**Comment by Vincent-Michael** [comment]
@Helnesis check pls your bnet console / log

**Comment by Helnesis** [comment]
http://puu.sh/j48iu/4e8aa70c61.jpg All logs :/

**Comment by Helnesis** [comment]
It is possible to send your patcher?  .. I use the one I built with core.

**Comment by vvizard100** [comment]
little up maybe ?
still can't figure out what's wrong after maaaaaany tests x)
