### ISSUE TITLE
[Core/Gossip] Gossip text Hardcoded in scripts.

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#15121]
Hello there,

Seeking a way as I transposes the English texts into German.

E.g. when I stand in Dalaran when innkeeper tells me Uda the Beast "I'd like to browse your goods." "This is also in" ScriptedGossip.h "

under #define GOSSIP_TEXT_BROWSE_GOODS "I'd like to browse your goods."

as well as for example, when Arthas in "culling_of_stratholme.cpp" "#define GOSSIP_ITEM_ARTHAS_0" I'm ready to start culling of Stratholme. "".

This Gossip Texts are Hardcoded in the Scripts and when i write it in German has the English users this in german and not in English, this is the Problem!

 6.x c4877eaf0fd2292d1a0c0b006ca8f349fae298b6
3.5.5 ab42772f8e2798dfa104cb9c7a0c44800c1f91b1

greets

**Comment by Rushor** [comment]
check the maletext/femaletext in broadcast_text and change the script (god example is https://github.com/TrinityCore/TrinityCore/commit/6c0ff5717f14e90dfd92cf963c0805adae3c668b)

**Comment by genion18** [comment]
Hallo, 

Ich hab leider keine ahnung von C++, somit weiß ich nicht wie es klappen könnte in den ganzen Scripts wo es Hardcoded ist!

greets

**Comment by Rushor** [comment]
für copy paste reicht es allemal guck dir einfach mal an versuchs auf andere script zu übertragen

for this you don't need to know anything, just try to copy the methode from other scripts. if you think your solution is acceactable and working - open up a pullrequest :)

**Comment by Rushor** [comment]
there are currently many open prs concerning the move from harcoded gossip to db gossip.
pls open **a single issue for each npc**, this stuff cannot be fixed in a few seconds.

example: https://github.com/TrinityCore/TrinityCore/pull/1643
