### ISSUE TITLE
[DEV][6.x] SAI for Catalysm creatures

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15127]
rndmhash: https://github.com/TrinityCore/TrinityCore/commit/87a5ba09e5e471b6d771a7c38c34cf7877cb7dbc

Based on the work from @Cooler-SAI we want to update all Creature abilies while using this https://github.com/Discover-/SAI-Editor to keep the TC Standards.

Things which have to be updated:
- The Comment field
- Update all Spellcasts to CmC if needed
- Remove unneeded Linking
- Check Spell if they are still present in 6.x
- Add Broadcasttexts
- Remove 'Combat-Flee' Texts since this is handled in The SAI-Action itself now
- Update Combattimer if needed
- Remove NormalDungeonFlags for Creatures in Open World

Source: https://github.com/cooler-SAI/patch
and https://github.com/cooler-SAI/TrinityCore_4.3.4_DB_Alpha/commit/f22525283756bf763510834f50915d9fc8ffeab3

Feel free to help us :)

Checkboxes for all zones to keep an organisation (also allows us to assign stuff)
Since we cannot assign multiple people to issues - summoning @Killyana :D

Instances are not listed here because they must be updated after corechanges for the instance are done.

All Zones:
- [x] BadLands  (in work by @Killyana)
- [x] Blasted Lands  (in work by @Killyana)
- [x] Burning Steppes (in work by @Killyana)
- [x]  Eastern Plaguelands   (in work by @Killyana)
- [x] Hillsbrad Foothills   (in work by @Killyana)
- [x] Searing Gorge (in work by @Killyana)
- [x]  Silverpine Forest  (in work by @Killyana)
- [x] Swamp of Sorrows   (in work by @Killyana)
- [x]  Western Plaguelands  (in work by @Killyana)

- [x] Ashenvale (by @Rushor)
- [x] Azshara ( by @Rushor)
- [x] Azuremyst Isle (by @CreshandKesh)
- [x] Darkshore (by @Rushor)
- [x] Deadwind Pass (by @cooler-SAI)
- [x] Dun Morogh (by @Rushor)
- [x]  Durotar (by @Rushor)
- [x]  Duskwood (by @Rushor)
- [x]  Dustwallow Marsh (by @Rushor)
- [x]  Elwynn Forest (by @Rushor)
- [x]  Eversong Woods (by @cooler-SAI)
- [x]  Felwood (by @Rushor)
- [x]  Feralas (by @Rushor)
- [x] Ghostlands (by @cooler-SAI)
- [x] Gilneas City (by @Rushor)
- [x] Isle of Quel'Danas (by @CreshandKesh)
- [x] Kezan (by @Rushor)
- [x] Loch Modan (by @Rushor)
- [x] Moonglade (by @Rushor)
- [x] Mount Hyjal (by @Rushor)
- [x] Northern Barrens (by @Rushor)
- [x] Southern Barrens (by @Rushor)
- [x] Stonetalon Mountains (by @Rushor)
- [x] Tanaris (by @Rushor)
- [x] Teldrassil (by @Rushor)
- [x] The Hinterlands (by @Rushor)
- [x] Thousand Needles (by @Rushor)
- [x] Uldum (by @Rushor)
- [x]  Westfall (by @Rushor)
- [x] Winterspring (by @Rushor)
- [x] Mulgore (by @Rushor)

**Comment by fallenoak** [comment]
I'm just starting to dig in to how to contribute to TrinityCore, so I apologize if this isn't an appropriate place to ask. Would recent packet caps / WDBs help with this issue for any of the zones listed above? I'm currently attempting to archive WDBs and packet cap a leveling sprint from 1 to 100, including all battlegrounds and instances.

**Comment by DDuarte** [comment]
@fallenoak: yes, they would help a lot actually. You can post them at http://community.trinitycore.org/forum/13-wdbadbsniffs/. Thanks!

**Comment by fallenoak** [comment]
@DDuarte I've posted what I've got so far. I'll keep posting as I have time.

**Comment by Rushor** [comment]
@fallenoak: if you are starting to sniff, it would be very useful if you sniff all questdetails. in the most cases the people forget to sniff the whole endevent of a creaturequestender and so on

moreover we will love you, if you name the snifffiles properly (aka: sniff_zone_nothern_barrens)

thank you very much :)

**Comment by fallenoak** [comment]
@Rushor By endevent, I assume you mean I should stick around when turning in a quest to catch things like gossip text and NPC movements/spells? I tried to do that most of the time-- sometimes it takes a bit to fire on the server, so I don't realize I'm missing something. I'll try stick around a minute or two to make sure I don't miss any.

Sorry about the naming scheme-- I hadn't realized one was specified. Do you want me to name each pkt file against that format, or just the 7z archive? I imagine I'll have 5-15 pkt files per zone, so I'm trying to include them all in single 7z archives so I don't clutter things up.

**Comment by Rushor** [comment]
add the name just for the mainfolder :)

**Comment by fallenoak** [comment]
@Rushor Will do! Thanks for letting me know.

**Comment by cooler-SAI** [comment]
@Rushor I will redone Deadwind Pass for Trinity standart - add me :)

**Comment by ShinDarth** [comment]
For non-windows users who want to contribute, there is a **cross platform** SAI Editor (inspired by Discover-'s SAI Editor):

http://community.trinitycore.org/topic/11397-keira2-the-trinitycore-database-web-editor-cross-platform/

**Comment by CreshandKesh** [comment]
@Rushor 
I'm going to help you with Azuremyst Isle.

**Comment by Rushor** [comment]
added, make shure, that we will not overwrite the already existing sais ^^

**Comment by cooler-SAI** [comment]
add me for Eversong Woods xD

**Comment by Rushor** [comment]
yes okay

**Comment by cooler-SAI** [comment]
Ghostlands - my NEXT target :)

**Comment by CreshandKesh** [comment]
add me for Isle of Queldanas :smile_cat:

**Comment by Dokman** [comment]
Woooow very good job boys!

**Comment by Rushor** [comment]
you can always help us if you like to do it :D

**Comment by Dokman** [comment]
i don't have any kind of wdb or a payed account :( i only have the starter edition
if i can try to help to you making elwynn forest...

**Comment by Rushor** [comment]
well then go for it :) i added you to the list - open up an issue if averything is done

**Comment by Dokman** [comment]
ok

**Comment by cooler-SAI** [comment]
add me for Felwood :-D

**Comment by Rushor** [comment]
if you have any questions just join collab.kpsn.org/display/tc/IRC

**Comment by Killyana** [comment]
BTW zones assigned to me are the ones which I already scripted the hole quests, just npcs movement, some phasing and combat scripts are missing, so if you already have the SAI combat script you can push it.

**Comment by Dokman** [comment]
@Rushor i can't do it for now i am busy in real life i have a lot of troubles right now TT can you unassing me please? if i have time i will try to collaborate sorry guys :(

**Comment by Rushor** [comment]
meh fuck rl :D kay done

**Comment by Rushor** [comment]
Okay. We are done with the convertion of the Fixes for the Zones. I will open up sone new issues.
1) Movement + Emotes for classiczones
2) Quests + Phaing for classizones
3) SAI + Movement for Classicinstanzen (only few updates are needed there)

**Comment by Naios** [comment]
Well done, amazing work!

**Comment by digz6666** [comment]
Well done guys!

**Comment by Exodius** [comment]
Incredible. Thanks to all involved!

**Comment by Runico** [comment]
<3

**Comment by Killyana** [comment]
@cooler-SAI do you have updated SAI for Redridge Mountains, we forgot this are.

**Comment by cooler-SAI** [comment]
@Killyana , no :(

**Comment by cooler-SAI** [comment]
@Killyana @Rushor guys, added new scripted zone Swamp of Sorrows (also new repo added)
https://github.com/cooler-SAI/patch-Lab
