### ISSUE TITLE
Crash of Map

### ISSUE THREAD

**Issue by megatronir** [TrinityCore/TrinityCore#15136]
Hi, i got a crash now and it's seems vmap or mmap system.i tried to reproduce it but cant find how this crash will goes.

crashlog : http://privatepaste.com/51b427a1f4

branch : 6x

revision: https://github.com/TrinityCore/TrinityCore/commit/eb3aeb8fd1b87c6ff00f4c2278522905e5a3dbd6

**Comment by DDuarte** [comment]
Update. 87a5ba09e5e471b6d771a7c38c34cf7877cb7dbc likely fixed your issue.

**Comment by megatronir** [comment]
thanks, i'll try to pull and test it :+1:

**Comment by DDuarte** [comment]
Re-open the issue if it still happens after that commit.

**Comment by megatronir** [comment]
ok , ty, i got a new crashlog in Mmap too .
http://privatepaste.com/b19174665e

**Comment by DDuarte** [comment]
Try after d41f87e62abef6fa4b0dc23274023d91bdc005d8

**Comment by Aokromes** [comment]
P.S. making screenshots instead posting text makes very hard for people having the same issue searching for the bug.

**Comment by planee** [comment]
update with d41f87e and  87a5ba0,but useless,same crash happened.

**Comment by megatronir** [comment]
yeah still same crash

**Comment by planee** [comment]
pls re-open the issue.

**Comment by planee** [comment]
any news o 0?

**Comment by Aokromes** [comment]
No.

**Comment by megatronir** [comment]
it's shauren work, hope so as soon as possible he have time to take a look.

**Comment by Shauren** [comment]
I have nothing to do with vmaps/mmaps and I'm not working on this issue.

**Comment by megatronir** [comment]
ye sorry as i checked it seems jackpoz works almost.

**Comment by jackpoz** [comment]
crash logs expired
