### ISSUE TITLE
[3.3.5][Master] Core/Creature - NPCs that are vehicles of other NPCs

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15153]
NPCs that are vehicles of other NPCs, are dropping the npc they carry.
Examples:

![wowscrnshot_072315_225919](https://cloud.githubusercontent.com/assets/7120913/8866261/d4598440-3190-11e5-821b-f957369c5729.jpg)
![wowscrnshot_072315_230952](https://cloud.githubusercontent.com/assets/7120913/8866260/d45917ee-3190-11e5-936c-bccd500276dd.jpg)
![wowscrnshot_072315_231104](https://cloud.githubusercontent.com/assets/7120913/8866259/d4590074-3190-11e5-90ea-c9c68cc9baeb.jpg)

I remember ever having seen similar problem with some other NPCs, but I do not remember other examples out of Ulduar now.

Reproduce:

Start the fight with the XT002 or Flame Leviathan. Use GM ON or Wipe. Normally some npc that the Leviathan carries will drop.

Rev b1ac631f68d122558c25c4da7eedef75b4c2b7b6

**Comment by joschiwald** [comment]
Just a visual bug, cause by passenger is created before vehicle at client side

**Comment by Trisjdc** [comment]
Also happens if you remove/add the vehicle from client visibility, with stealth or a simple object destroy

**Comment by Keader** [comment]
it's not exclusive for Ulduar creatures.

**Comment by xinef1** [comment]
Accessory is detected before vehicle and client can't attach it properly. As a result it drops. Detecting the vehicle latter do not change anything. The solution is to prevent detection of accessories if we do not see its vehicle.

```diff

 src/server/game/Entities/Object/Object.cpp | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index a5f5aa1..c22b08a 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -1578,6 +1578,14 @@ bool WorldObject::CanSeeOrDetect(WorldObject const* obj, bool ignoreStealth, boo
                             corpseVisibility = true;
                 }
             }
+
+            if (Unit const* target = obj->ToUnit())
+            {
+                // don't allow to detect vehicle accessory if you can't see vehicle base!
+                if (Unit const* vehicle = target->GetVehicleBase())
+                    if (!thisPlayer->HaveAtClient(vehicle))
+                        return false;
+            }
         }
 
         WorldObject const* viewpoint = this;

```

**Comment by Keader** [comment]
Improve... but still drop accessories

<details> 

![image](https://cloud.githubusercontent.com/assets/7120913/21445529/60aedca8-c8a1-11e6-875c-cc087495c1c0.png)

</details>

**Comment by Killyana** [comment]
@Keader for this accessories it's not the same issue, they are really not installed , they drops after the boss enter the combat or evade.

**Comment by Keader** [comment]
hmm, ok
@xinef1 can open pr about it? :)

**Comment by xinef1** [comment]
Anyone can open it :p as for evade accessory drop, ill take a look later
