### ISSUE TITLE
[6.x] [PR proposed] When libZeroMQ is missing, cmake detection should fail

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15152]
This is a very minor issue I discovered on a fresh gentoo testing install. I always install zeroMQ before configuring/compiling trinity but this time I just forgot it.
The result was a successful cmake configure but an unsuccessful compile.
It should raise an error if it was not detected.
Happens at least in rev eb9d08b3d0eebfe3cc482614f6dff4d8c5b607a9
Output:
cmake ../sources/ -DSCRIPTS=1 -DTOOLS=0 -DCMAKE_INSTALL_PREFIX=/data/Trinity/6.x/ -DCONF_DIR=/data/Trinity/6.x/etc/ -DCMAKE_C_FLAGS="-march=native -O3 -pipe -fomit-frame-pointer -floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block -ftree-vectorize -flto -DNDEBUG" -DCMAKE_CXX_FLAGS="-march=native -O3 -pipe -fomit-frame-pointer -floop-interchange -ftree-loop-distribution -floop-strip-mine -floop-block -ftree-vectorize -flto -DNDEBUG" -DCMAKE_BUILD_TYPE="Release"
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: Enabled c++11 support
-- GCC: Enabled C99 support
-- GCC: SFMT enabled, SSE2 flags forced
-- Found OpenSSL library: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found ZMQ library: /usr/lib64/libzmq.so
-- Found ZMQ headers: /usr/include
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib64/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found Readline library: /usr/lib64/libreadline.so
-- Include dir is: /usr/include
-- Found git binary : /usr/bin/git

* TrinityCore revision   : eb9d08b3d0ee 2015-07-23 23:45:50 +0200 (6.x branch)
* TrinityCore buildtype  : Release

* Install core to        : /data/Trinity/6.x
* Install libraries to   : /data/Trinity/6.x/lib
* Install configs to     : /data/Trinity/6.x/etc/

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : No  (default)
* Use GIT revision hash  : Yes

-- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: The Maelstrom
  -> Prepared: Events
  -> Prepared: Pet
-- SCRIPT PREPARATION COMPLETE

-- Configuring done
-- Generating done
-- Build files have been written to: /data/Trinity/6.x/build

make
(...)
Building CXX object dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/context.cpp.o
In file included from /data/Trinity/6.x/sources/dep/zmqpp/zmqpp/context.cpp:8:0:
/data/Trinity/6.x/sources/dep/zmqpp/zmqpp/context.hpp:13:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
dep/zmqpp/CMakeFiles/zmqpp.dir/build.make:54: recipe for target 'dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/context.cpp.o' failed
make[2]: *** [dep/zmqpp/CMakeFiles/zmqpp.dir/zmqpp/context.cpp.o] Error 1
CMakeFiles/Makefile2:454: recipe for target 'dep/zmqpp/CMakeFiles/zmqpp.dir/all' failed
make[1]: *** [dep/zmqpp/CMakeFiles/zmqpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Built target revision.h
Makefile:116: recipe for target 'all' failed

Of course, the detected file /usr/lib64/libzmq.so does not exist.
I've seen the code for the ZMQ finder and I don't see anything relevant wrong, but it is not working at least not in linux.

**Comment by StormBytePP** [comment]
Reading cmake documentation about it under http://www.cmake.org/cmake/help/v3.0/command/find_library.html I found that when a library is not found by find_library, a var with <var>-NOTFOUND is populated.
Using that in the conditional seems to trigger the error correctly.
This is the proposed patch:
```patch
diff --git a/cmake/macros/FindZMQ.cmake b/cmake/macros/FindZMQ.cmake
index c442f3d..d538257 100644
--- a/cmake/macros/FindZMQ.cmake
+++ b/cmake/macros/FindZMQ.cmake
@@ -72,7 +72,7 @@ find_library(ZMQ_LIBRARY
     "${ZMQ_ROOT_DIR}/lib"
 )
 
-if (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARY)
+if (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARY AND NOT ZMQ_LIBRARY-NOTFOUND)
   set(ZMQ_FOUND 1)
   message(STATUS "Found ZMQ library: ${ZMQ_LIBRARY}")
   message(STATUS "Found ZMQ headers: ${ZMQ_INCLUDE_DIR}")
```

**Comment by tkrokli** [comment]
Looks quite good, you should make a PR on it so it can be viewed properly within the source. :+1:

**Comment by StormBytePP** [comment]
Done, PR #15155 created.

**Comment by DDuarte** [comment]
> -- Found ZMQ library: /usr/lib64/libzmq.so
-- Found ZMQ headers: /usr/include

That's weird, why does it happen?

**Comment by StormBytePP** [comment]
I was also smashed by that, as it should not happen at all.
My theory, is that the vars ZMQ_LIBRARY and ZMQ_INCLUDE_DIR, will always contain a value, regardless it is found or not, that is what my PR is about, and also that is why the "Found ZMQ" messages appear.
