### ISSUE TITLE
[3.3.5][6.x][RS] Halion Spells ( Meteor Strike & Fiery Combustion)

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15154]
Meteor Strike (75952)
```
After recently updates meteor will appear like rectangular on the ground instead of +
http://i58.tinypic.com/r0xoib.jpg
```

Fiery Combustion (74562)
```
This spell every second will get bigger and bigger the visual part works but
the radius of damage part doesn't do damage at all, only first calculate of radius do damage
http://imgur.com/NWhGegd
```

Clean TC
TDB 59
Rev a9d00b9c969f2e0297bf2500fdf78bc05fe4011e

**Comment by Warpten** [comment]
Try meteor strike after https://github.com/TrinityCore/TrinityCore/commit/a82e55f6841284a68c4bb2500e342a591cb59c7a?diff=unified

About Fiery Combustion, this is a spell system bug.

**Comment by Warpten** [comment]
Shit. Noticed something. Try meteor anyway, wont be able to update before tomorrow

**Comment by Runico** [comment]
@Warpten I will test it to night, need some free time

**Comment by Runico** [comment]
@Warpten, After that commit it still same as before

**Comment by Warpten** [comment]
Try again after my last commit is cherry-picked to 3.3.5 (halion cannot be run on cata and up because a custom spell id became used by blizztards)

**Comment by Runico** [comment]
@Warpten, What about the old commit u pushed ? should i revert that and apply this one ? or apply both of them

**Comment by Nyeriah** [comment]
Well, they're not exactly spawning in a X... but! He builds nice firewalls.

Not sure if it can be noticed in the image
http://i859.photobucket.com/albums/ab153/Nyeriah/WoWScrnShot_072715_172851_zpsdnfbfkth.jpg

**Comment by Warpten** [comment]
Nyeriah: from my experience its more an X than a cross, the angle varies and the arms are randomly twistes

**Comment by Nyeriah** [comment]
Yeah, I know, I was just relating what I have seen after I cherry-picked your commit. It's spreading in a line now, instead of the X with twisted ends :p

**Comment by Warpten** [comment]
Meh. It wasnt twisted prior to my mess either way, try increasing the randomization (cant try it myself, no pc)

**Comment by Runico** [comment]
@Warpten, http://www.photobox.co.uk/my/photo?album_id=3581168004&photo_id=8764733053#8764733053

**Comment by Demonid** [comment]
http://puush.me/ for easy Screenshots.

**Comment by Aokromes** [comment]
https://getsharex.com is much better, direct links to photos without aditional web interfaces.

**Comment by Warpten** [comment]
Closing since PR fixed that, reopen if still broken
