### ISSUE TITLE
[3.3.5] Fiery Payback mage talent

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#15157]
https://github.com/TrinityCore/TrinityCore/commit/2aaab040ce6fbfc04eb55b26352e00d12fecc577

This talent has been bugged for a long time, sometimes it works like 1/2 of what it should.

Can't give exact situations to reproduce because I don't exactly know when it gets bugged, I think it is when you die or when you lose an arena and leave it but this doesn't happen in all of these situations.

When it gets bugged, looks like you lose the aura rank 2 and it returns to aura rank 1 that makes 2,5 sec CD and 3,7 casting time instead of 5 sec CD and 1,5 casting time.

I think this is the same as in https://github.com/TrinityCore/TrinityCore/issues/9281

**Comment by Rushor** [comment]
summoning @mik1893 because he knows how to reproduce it maybe :)

**Comment by planee** [comment]
confirm

**Comment by Laintime** [comment]
Confitm

**Comment by Laintime** [comment]
confirm

**Comment by Laintime** [comment]
confirm

**Comment by Raydor** [comment]
@Laintime why are you spamming "confirm" and then deleting the comment?
@planee why did you delete your "confirm" message too? XD

**Comment by Keader** [comment]
There's another problem ... When the talent is active and you spamming Pyroblast, you can use up to 2 Pyroblast before going into cooldown.

**Comment by Killyana** [comment]
mik1893 commented on 27 Aug 2014

confirm to on latest tc rev 66f4b51
How to replicate the bug:

Spec 2 points in fiery payback
talent works fine
Logout
Login back again You will see talent is actually working as it is rank 1, even if you have specced rank 2. It looks like it doesn't save the correct talent information on database or that it cannot be read. I will investigate more.

**Comment by Keader** [comment]
Any news about that?

**Comment by Keader** [comment]
If you switch build (using the dual talent) the spell back to normal operation as well.

**Comment by Bruno21024** [comment]
Any solution?

**Comment by Keader** [comment]
The spell Primal Fury (Feral Druid) has the same problem, stops working after relog.

**Comment by Rushor** [comment]
pls list all spellids which are involved

**Comment by Keader** [comment]
- 37116  Primal Fury R1
- 37117 Primal Fury R2
- 64350 Fiery Payback R1
- 64349 Fiery Payback R2

I only know these spells having this problem

**Comment by Rushor** [comment]
spell_ranks are all properly set for the talents?

**Comment by Keader** [comment]
On Database? does not have the entries

**Comment by sirikfoll** [comment]
This seems to fix the issue:
```sql
DELETE FROM `spell_ranks` WHERE `first_spell_id`=44440;

**Comment by Keader** [comment]
Fix by @sirikfoll  works for me :+1:

**Comment by Rushor** [comment]
kay then the Primal Fury issue remains - or do you want to open a new issue for this?

**Comment by Keader** [comment]
new issue, i'll try to get a way to reproduce easier

**Comment by Jenkyins** [comment]
confirmed on b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Rushor** [comment]
wait @sirikfoll

didn#t this cause the problem that player will get the effect from rank 2 if they only have skiled rank 1 ?

**Comment by sirikfoll** [comment]
No, at least in the part that affects Pyroblast it works as it's supposed to.
I did not test the damage reduction part.

**Comment by Rushor** [comment]
@Keader: can you test this part pls:
> I did not test the damage reduction part.

:)

**Comment by Keader** [comment]
Yes, it seems to be working properly
