### ISSUE TITLE
[BUG][6.x] Heirloom stuff

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#15166]
Hi, in last rev (6.x): acd3fe5807e6f81c6d49037b4e38d819d94d6166
Heirloom stuff, when we it's buy at the npc, is not in the Stuff Tab in the interface, so, we can't upgrade it to lvl90/100.

So can you do anything for that ?

**Comment by DDuarte** [comment]
One issue per ticket, please.

**Comment by Frytiks** [comment]
So just accept first thing as mentioned in title.

**Comment by martial69320** [comment]
Edited for the second issue in the ticket, i deleted it.

**Comment by Aokromes** [comment]
Test https://github.com/TrinityCore/TrinityCore/pull/15677

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9fe29de260b704603f40a8912c66dccf76fd0db8
