### ISSUE TITLE
[DB/Creature]: Ulduar - Seeping Essence does not deal damage on 10man difficulty

### ISSUE THREAD

**Issue by LuqJensen** [TrinityCore/TrinityCore#15165]
Title explains it all. 25man difficulty does not suffer from this issue and has the correct unit_flags. Issue fixed by applying unit_flags from 25man to 10man.
Commit: 66bbdfb82cc27eb6fd39b93e8c11ea0aedf21c75
```sql
UPDATE `creature_template` SET `unit_flags` = 33554432 WHERE `entry` = 34098; 
```

![image](https://cloud.githubusercontent.com/assets/2790839/8894414/65e48118-33b6-11e5-8931-18ea1357ebf3.png)

**Comment by Vincent-Michael** [comment]
[3] UNIT_FIELD_FLAGS: 33554432/9.403955E-38
y, is correct

**Comment by LuqJensen** [comment]
whats happening with this?

**Comment by Keader** [comment]
Rushor must have forgotten, I think
