### ISSUE TITLE
[master] Core/Phases: base vmaps are used instead of phased (50$ bounty)

### ISSUE THREAD

**Issue by sakuranobushi** [TrinityCore/TrinityCore#15163]
Rev: 8b3f424af8d0e645a579d07bb36d6b5ceef36450

When a npc is placed over a wmo in a phased map which does not exist in the base map the npc usually falls down as if no vmap was loaded. 

This may be due to base vmaps being used instead of the ones for the current phase.

**Comment by DDuarte** [comment]
Related to #15161?

**Comment by sakuranobushi** [comment]
I'm not sure since the problem don't usually occurs with gameobjects but map objects, such as buildings and so. And on top of that only when the zone is phased.

But I hope someone who really understands how the system works can understand the problem better than I do.

**Comment by joschiwald** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Maps/Map.h#L477
uses old and not longer used phasemask

**Comment by joschiwald** [comment]
Can you give us a good example to reproduce

**Comment by sakuranobushi** [comment]
For example if you force the terrainswap 971 on the map 870 (The alliance intro for pandaria).

Any npc spawned on the skyfire (over garroshar point) will fall down to the ground if it tries to move, for example.

**Comment by streetrat** [comment]
phase vmaps (and base maps) are not yet implemented
only mmaps handle phasing based on unit's active terrain swaps
feel free to give a hand on how to load vmaps :)

**Comment by funjoker** [comment]
https://www.bountysource.com/issues/24951339-6-x-core-phases-base-vmaps-are-used-instead-of-phased

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=24951339)](https://www.bountysource.com/issues/24951339-6-x-core-phases-base-vmaps-are-used-instead-of-phased?utm_source=24951339&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by funjoker** [comment]
To make it more clear.
All issues related to missing Implementation of vmaps to terrainswaps must be fixed to gain the bounty.

**Comment by funjoker** [comment]
Any ideas ?

**Comment by funjoker** [comment]
@Riztazz I just asume this here 

Is this worth a look ?
https://github.com/Riztazz/mop/commit/22bfe8f8efb42ad32b8783a632f98d586bd34db7
