### ISSUE TITLE
[6.2] As a GM when using additemset it hands out all the item level items.

### ISSUE THREAD

**Issue by Lazerballz** [TrinityCore/TrinityCore#15179]
Branch 6.x
Last checkout and compile time: 26-07-2015
https://github.com/TrinityCore/TrinityCore/commit/c8589f771c89d8ee946b0e4eb5e4a3f7f5c7c37a
Client : 6.2.0 20253 Win64

As an GM when using the .additemset command to hand out a set and the set has multiple levels it hands out all of them.

For example
.additemset 1194 (mage tier 16)

 hands out item level sets 528, 540, 553, 566

**Comment by DDuarte** [comment]
What do you think it should be the intended behaviour?

Should `.additemset 1194` give only one item set (the first level? the last level?)
Should `.additemset` take a 2nd parameter to specify the wanted level?

**Comment by Lazerballz** [comment]
Uhm good question.

When I look at wowhead the pictures showing the Heroic version 
http://www.wowhead.com/itemset=1194/chronomancer-regalia

The other ones are 

ilvl 566 :http://www.wowhead.com/itemset=-1009/chronomancer-regalia
ilvl 540: http://www.wowhead.com/itemset=-1055/chronomancer-regalia
ilvl 528: http://www.wowhead.com/itemset=-1032/chronomancer-regalia

I have tried to used "-<number>" before but that's a wrong value for the command.

As each set has their "own" set item number I wouldn't suggest to add a second parameter for the command but rather to support the "-<number>" value.

**Comment by Shauren** [comment]
These negative ids are wowhead fakes, there is no way we can support it.

**Comment by NorthStrider** [comment]
hm so it would require a database table with id --> setcontent

**Comment by Shauren** [comment]
and id rather not do that since dbcs is all we need here (adding all versions is just fine)

**Comment by tkrokli** [comment]
@Lazerballz : Seems like there is no solution, just the workaround of `.additem` for each piece.

**Comment by Lazerballz** [comment]
No problem from my side. Maybe a note should be handy on the GM command page saying that these things can occur when using the .additemset command.

Thanks for investigating though :-)
