### ISSUE TITLE
[6.2] spells do not make damage or heal

### ISSUE THREAD

**Issue by LebenHarvest** [TrinityCore/TrinityCore#15171]
rev:  f44364d

Just wanted to report, I'm sure this is probably already known though.

As the title says spells do no damage and the combat logs show nothing for heals and damage spells.

tested on a newly made lvl 100 paladin.

**Comment by LebenHarvest** [comment]
-Update, after testing I now see that it is simply the combat log opcodes are disabled probably.

**Comment by MitchesD** [comment]
yes, it's due to disabled opcodes, we know that

**Comment by BoThay** [comment]
wich opcode is? any solution?

**Comment by Robens** [comment]
logs opcodes

**Comment by DDuarte** [comment]
No longer an issue?
