### ISSUE TITLE
[3.3.5] Mount Fall Damage

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#15170]
https://github.com/TrinityCore/TrinityCore/commit/3950ea3881421cc295f0dd18676e65a95bfcb768

1 - use Mount
 [Mekgineer's Chopper]  [Mechano-hog]
 [Reins of the Traveler's Tundra Mammoth]

2- Go on Dalaran [ Area height ]
3 - Going Down [ Fall ]
4 - u Must Die or Damage But notting Happen [ NOt any damage 0 ]
5 - Play with your mount 
6 - Every time U want Dismount ( What happen?) Your Die ! Or get More 100% damage 

if U falling with example Mount when u dismount u give damage from falling . if Do not Dismount noting happen

(sorry for Bad english)

**Comment by Raydor** [comment]
AC2 anticheat related bug, just delete it and it will be solved.

**Comment by Aokromes** [comment]
Post it on ac2 thread.
