### ISSUE TITLE
[3.3.5][6.x][Ulduar] Flame Leviathan -Spell Battering Ram not affecting vehicles.

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15185]
Spell: Battering Ram (62376)

http://www.wowhead.com/spell=62376/battering-ram

Description: Rams the target, dealing damage and knocking it forward.

Effect#3 : 
Apply Aura: Mod % Damage Taken (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)
Value: 50%
Radius: 20 yards

Problem: The debuff is applied only if a player is hit by the spell. The correct is that cars also suffer the debuff.

Prov: Observe the right of the screen, you notice the icon of the debuff. (test on WoD)

![wow-64 2015-07-20 22-07-04-75 avi_snapshot_00 49_ 2015 07 29_09 57 07](https://cloud.githubusercontent.com/assets/7120913/8958104/3bf7a32e-35d9-11e5-91e0-51f5e2423868.jpg)

TC Rev df92d2c8d259a272bf5abfc41293f88781d03457

**Comment by Keader** [comment]
In my test, this work in all another creature. But in vehicles dont :(

**Comment by xiong94039** [comment]
scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp

void DoBatteringRamIfReady()
{
    if (me->isAttackReady())
    {
        Unit* target = ObjectAccessor::GetUnit(*me, _pursueTarget);

        // Pursue was unable to acquire a valid target, so get the current victim as target.
        if (!target && me->GetVictim())
            target = me->GetVictim();

        if (me->IsWithinCombatRange(target, 30.0f))
        {
            DoCast(target, SPELL_BATTERING_RAM);

            // new added
            Unit* target_vehicle = target->GetVehicleBase();
            if (target_vehicle)
                DoCast(target_vehicle, SPELL_BATTERING_RAM);

            me->resetAttackTimer();
        }
    }
}

**Comment by Rushor** [comment]
check if the vehicle is immue to 'Mod % Damage Taken' effects in vehicle.cpp

**Comment by Rushor** [comment]
try:

```c++
// Different immunities for vehicles goes below
    switch (GetVehicleInfo()->m_ID)
    {
        case 335: // Salvaged Chopper
        case 338: // Salvaged Demolisher
            _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, false); // Battering Ram
            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, false); // Battering Ram
            break;
    ```

in vehicle.cpp in void Vehicle::ApplyAllImmunities()

**Comment by Keader** [comment]
@Rushor are you sure that they can take knock_back?

**Comment by sirikfoll** [comment]
They can't.

**Comment by Keader** [comment]
y, last time that o did ulduar in retail they dont take knock back xd

**Comment by Killyana** [comment]
I checked many videos, and never saw a vehicle been knocked back.

**Comment by Rushor** [comment]
okay well, knockback immunity removed, but the vehicle should not be immune against SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN

**Comment by Keader** [comment]
@Rushor missing 1 vehicle, no?

Entry 33060, Salvaged Siege Engine

**Comment by Rushor** [comment]
added :)

**Comment by Keader** [comment]
Tested and working.
Can you open PR about it @Rushor ?

<details>

```diff
diff --git a/src/server/game/Entities/Vehicle/Vehicle.cpp b/src/server/game/Entities/Vehicle/Vehicle.cpp
index e930d20..d61a4fe 100755
--- a/src/server/game/Entities/Vehicle/Vehicle.cpp
+++ b/src/server/game/Entities/Vehicle/Vehicle.cpp
@@ -211,6 +211,11 @@ void Vehicle::ApplyAllImmunities()
             // why we need to apply this? we can simple add immunities to slow mechanic in DB
             _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DECREASE_SPEED, true);
             break;
+        case 335: // Salvaged Chopper
+        case 336: // Salvaged Siege Engine
+        case 338: // Salvaged Demolisher
+            _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, false); // Battering Ram
+            break;
         default:
             break;
     }
```

</details>

**Comment by Rushor** [comment]
will do

**Comment by Rushor** [comment]
done

**Comment by ariel-** [comment]
Here you can see him knocking back a demolisher: https://www.youtube.com/watch?v=ESsbxiEHaIs&feature=youtu.be&t=6m16s

**Comment by Keader** [comment]
Some bug i think ariel.
I can record a video for this fight in retail (if necessary), cars cant get knock back...

**Comment by ariel-** [comment]
The video is Patch 3.2 I think, notice the spell indicators of the Vehicles, they're different.

Maybe knock-back mechanic was changed along the way, you can't trust blizz mechanics comparing them to 3.3.5

**Comment by Keader** [comment]
193e51a80bbd31848a09d1e22bf8b7f05957b9f9
