### ISSUE TITLE
[6.x] Core/Movement: creature_formations - FollowerGUID follows LeaderGUID very bad while flying

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15190]
hash: https://github.com/TrinityCore/TrinityCore/commit/3e083c5eac91c82d2b8bbc2387f169430aafab0f
Problem: Creatures with Inhabitype 4 and creature_formations are following the Leader very bad until the follwerguid stucks in the air

How to reproduce:
1) Apply this https://gist.github.com/Rushor/121732b9cc767b8a39c2 for the wyvern in Orgrimmar
2) .go c 310863
3) look at creatureguid 310863 and 310862

Result:
You will see that the follower310862 will start following the leader 310863 - but soon the follower 310862 is going to fly to the ground with a very slow speed. The followerGUID seems to be unable to fly. The LeaderGUID meanwhile keeps flying around until it is out of sight and becomes inactive. This causes the FolloerGUID to become inactive and it starts stucking in the ground and does not move any longer.

Mainproblem which has to be improved:
FollowerGUID should always be able to fly

**Comment by Rushor** [comment]
i will make a vid to demonstrate all - without this fix orgrimmar cannot be completed xD

**Comment by Rushor** [comment]
kay done - https://youtu.be/fX9Q4e02oiI - here you can see how the follower goes down to the earth (yes i now it's 4.x client, but i'm unable to make a vid of 6.x and in 6.x it looks the same)

**Comment by Rushor** [comment]
```c++
diff --git a/src/server/game/Entities/Creature/CreatureGroups.cpp b/src/server/game/Entities/Creature/CreatureGroups.cpp
index 2ccf447..c55ee9f 100644
--- a/src/server/game/Entities/Creature/CreatureGroups.cpp
+++ b/src/server/game/Entities/Creature/CreatureGroups.cpp
@@ -244,13 +244,14 @@ void CreatureGroup::LeaderMoveTo(float x, float y, float z)
         Trinity::NormalizeMapCoord(dx);
         Trinity::NormalizeMapCoord(dy);
 
-        member->UpdateGroundPositionZ(dx, dy, dz);
+        //member->UpdateGroundPositionZ(dx, dy, dz);
 
         if (member->IsWithinDist(m_leader, dist + MAX_DESYNC))
             member->SetUnitMovementFlags(m_leader->GetUnitMovementFlags());
         else
             member->SetWalk(false);
 
+        member->UpdateMovementFlags();
         member->GetMotionMaster()->MovePoint(0, dx, dy, dz);
         member->SetHomePosition(dx, dy, dz, pathangle);
     }
```

this seems to work fine - thx @MitchesD for the proposal, maybe someone can add a 'fine' fix for this

**Comment by Rushor** [comment]
maybe we can add:
if(!member->HasFlag(Hover))
member->UpdateGroundPositionZ(dx, dy, dz);

**Comment by malcrom** [comment]
creature_formations isn't implemented properly.

**Comment by Rushor** [comment]
fix was already merged, thx @Golrag
