### ISSUE TITLE
[3.3.5][DK] Deathchill bug - Consume

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15193]
b574c99

How it works: Activate Deathchill > let Killing Machine proc > use for ex. Frost Strike > Buff is consumed by Deathchill and KM

How it should: Death Chill: The effect from this talent will no longer be consumed if Killing Machine is active.
Patch notess 3.0.8 Bug Fixes 
http://eu.battle.net/wow/en/game/patch-notes/3-0-8 [^]

Both buffs are taken while Deathchill should stay and keep our char with 100% Frost Strike crit chance.

Deathchill - http://wotlk.openwow.com/spell=49796
Killing Machine - http://wotlk.openwow.com/spell=51130
Frost Strike - http://wotlk.openwow.com/spell=49143

**Comment by cemak** [comment]
fix http://pastebin.com/6t5vPEhf

**Comment by Killyana** [comment]
Someone can take a look to the fix?

**Comment by cemak** [comment]
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index d02a22d..3c1a17c 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -7671,6 +7671,12 @@ bool Unit::HandleAuraProc(Unit* victim, uint32 damage, Aura* triggeredByAura, Sp
                     if (procSpell && procSpell->Dispel == DISPEL_DISEASE)
                         return false;
                     return true;
+
+                case 49796: // Deathchill
+                    *handled = true;
+                    if (GetAuraEffect(SPELL_AURA_ADD_FLAT_MODIFIER, SPELLFAMILY_DEATHKNIGHT, 2702, 0)) // Killing Machine
+                        return false;
+                    return true;
             }
             break;
         }

**Comment by tkrokli** [comment]
Use  ```diff  instead of only the 3 back ticks above the text to get relevant syntax highlighting. :)

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15193#issuecomment-137170644
Dont work for me

**Comment by Keader** [comment]
label feedback patchfix should be removed
