### ISSUE TITLE
DB/Startup Error With CharacterDB Update system

### ISSUE THREAD

**Issue by Dokman** [TrinityCore/TrinityCore#15198]
Wen i use a clean Characters databse the last update of characters of calendar it kill's the process of worldserver.

Branch: 6.x

Revision: https://github.com/TrinityCore/TrinityCore/commit/2c41196f03eabf26af5aa1e8b464ae1d3bf35baa

**Comment by DDuarte** [comment]
Never apply SQL updates of `characters` and `auth` on new installs.

**Comment by Rushor** [comment]
you can always join http://collab.kpsn.org/display/tc/IRC and ask if there are installationproblems - this prevents dublicated issues :)

**Comment by Naios** [comment]
Its also possible that the character base dump is not in sync with the updates anymore (means that somebody forgot to add a character update to the `updates` table)

**Comment by DDuarte** [comment]
Indeed, missing on https://github.com/TrinityCore/TrinityCore/blob/6.x/sql/base/characters_database.sql#L3067

I misunderstood the issue.
