### ISSUE TITLE
[3.3.5][Obsidian Sanctum] Vesperon

### ISSUE THREAD

**Issue by Stefan226** [TrinityCore/TrinityCore#15207]
Branch : TrinityCore rev. 80ec3e151536 (3.3.5 branch)(Unix,Release)

He works ok untill he starts the portal phase. He does that after 60 seconds (which should be 25-30, it's an easy fix, i did that but..) As soon as he spawns the portal He goes into "mode" in which he can't attack, but you can attack him ! Also when a player clicks on the portal it disappears for other players.. When you go in the portal you fight with the NPC. That NPC has despawn timer set to 28sec, which is very low and should be higher because if players don't kill him in 28sec NPC will despawn and bugg whole encounter ! (It's an easy fix too). After you kill that NPC you exit the portal but.. You somehow pull Sartharion and he pulls the whole raid :/

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/19363
