### ISSUE TITLE
Wicked Spirit (LK HC) - completely broken movement and behaviours

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15203]
b574c99

1. Gain some brave guys
2. Open LK fight
3. Get killed in 4 seconds inside a Frostmourne

Half of them are not targetable, half of them are just coming with a speed of light and hitting for 20k on 10HC (25 not tested, but they have same behaviors, tried on GM).

Tried to set lower their speed, it doesn't change anything.

**Comment by Killyana** [comment]
Almost the same issue https://github.com/TrinityCore/TrinityCore/issues/8335

**Comment by Rushor** [comment]
updated https://github.com/TrinityCore/TrinityCore/issues/8335 with a fresh tasklist of issues which are all infolvoled in this specific encounter

**Comment by Aokromes** [comment]
In fact, this issue must had been fixed few days ago.
