### ISSUE TITLE
[Core/Achievement] Save The Day

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15202]
Save the Day achievement (http://www.wowhead.com/achievement=207/save-the-day) doesnt work but there is script for that achiev (propably broken). I've tried to kill opponent with our flag in their room when their flag is controlled two times - both doesnt scored achiev.

TDB: 59
Rev: Latest Stable ( a9d00b9c969f2e0297bf2500fdf78bc05fe4011e )

**Comment by Keader** [comment]
Confirm.
I had remarked this at a time ago for Aokromes, but he said it was normal :(

**Comment by Laintime** [comment]
```
--- a/src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
+++ b/src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
@@ -883,7 +883,10 @@ bool BattlegroundWS::CheckAchievementCriteriaMeet(uint32 criteriaId, Player cons
     switch (criteriaId)
     {
         case BG_CRITERIA_CHECK_SAVE_THE_DAY:
-            return GetFlagState(player->GetTeam()) == BG_WS_FLAG_STATE_ON_BASE;
+            if(target && target->GetTypeId() == TYPEID_PLAYER) 
+			{
+                return GetFlagState(target->ToPlayer()->GetTeam()) == BG_WS_FLAG_STATE_ON_BASE;
+            }
     }
 
     return Battleground::CheckAchievementCriteriaMeet(criteriaId, player, target, miscValue);
```
Work fine.

**Comment by Keader** [comment]
@Laintime use ```diff
xD

**Comment by Laintime** [comment]
@Keader ok))))

**Comment by Keader** [comment]
work for me too @Laintime 
you can open a PR?
