### ISSUE TITLE
Loot duplicates in Instances/Dungs

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15201]
b574c99

1. Go to for example ICC
2. Win for example gunship battle
3. Loot for example 3x Muradin's Spyglass

Don't know if my core is broken or it's bugged (couldn't find any issue about this).

**Comment by Frytiks** [comment]
Change https://github.com/TrinityCore/TrinityCore/commit/ca280dbe051f2d9c43bbda128a6aa6bc19d8149f

loot.maxDuplicates = 3; to
loot.maxDuplicates = 1;

In both creature and gameobject.cpp

**Comment by Aokromes** [comment]
It's blizzlike, won't fix.

**Comment by selenir** [comment]
Wow, I'm sorry.
