### ISSUE TITLE
[3.3.5] Obsidian Sanctum

### ISSUE THREAD

**Issue by Stefan226** [TrinityCore/TrinityCore#15206]
Hello everyone !

I am still new into all this stuff (been playing with c++ for some time) , sorry if I make some mistakes in this post etc.. I've tested Obsidian Sanctum and came across some problems.. Here is the list :
1.Twilight Portals..
1.1 - They are not spawned so you have to add them manually.. I've found some query that fixes them but.. And yeah, you can find that query here : https://github.com/TrinityCore/TrinityCore/issues/13538
1.2 - After you spawn them and try to fight drakes here is what happens..
1.2.1 - Vesperon
He works ok untill he starts setting the portal to phase 2 i guess in which players can see them. He does that after 60 seconds (which should be 25-30, it's an easy fix, i did that but..) As soon as he spawns the portal He goes into "mode" in which he can't attack, but you can attack him ! Also when players clicks on the portal it disappears for other players.. When you go in the portal you fight with the NPC. That NPC has despawn timer set to 28sec, which is very low and should be higher because if players don't kill him in 28sec NPC will despawn and bugg whole encounter ! (It's an easy fix too). After you kill that NPC you exit the portal but.. You somehow pull Sartharion and he pulls the whole raid :/ (So it's your group vs the entire raid lol).. That's about it for Vesperon let's move on.
1.2.2 - Shadron
Portal encounter timer should be also set to 25-30 sec. When he spawns it he works ok, but he has the same problem like Vesperon.. When one player gets into the portal it disappears, also if you kill NPC in the portal it works well , you exit , debuff on Vesperon gets removed but you pull Sartharion and guess what ? Yeah.. You pull the whole raid again :)
That's pretty much it about Shadron let's move on..
1.2.3 - Tenebron
Like with Shadron and Vesperon his portal also disappears when one player enters it.. When you kill all eggs inside you don't exit the portal so that's a major bugg.. If you don't go into portal he will spawn little dragons. That's it with Tenebron...

2. Sartharion -Hard Mode-
There is a bug when Sartharion starts calling his drakes , one major and two minor buggs :
2.1 Tenebron - As soon as he comes from his "home" position to new position he goes into Evade mode and you can't attack him but he also doesn't attack.
2.2 Shadron - Not sure but, sometimes when he comes from his "home" position to new position and you don't attack him right away he will fly back, lol..
2.3 Vesperon - With Vesperon I am 100% sure that if you don't attack him right away he will fly back to his "home" position.

3.Trash mobs should have waypoints set and should be moving :) , only first two groups should stay in one place.

That's about it.. Sorry for the long post.. I hope this can be fixed :)

TrinityCore rev. 80ec3e151536 (3.3.5 branch)(Unix,Release)

**Comment by Rushor** [comment]
post all these issues pls in multiple separated issues - this whole list will never be fixed from one person :)

**Comment by Stefan226** [comment]
hehe, I don't expect this to be fixed like tomorrow or something.. :)
I only posted it because the developers should know about this problems ( I saw in the scripts files that Obsidian Sanctum scripts haven't been touched for like 7 months) and I am still noob to take on whole raid scripting by myself.
