### ISSUE TITLE
[3.3.5] Skettis Eviscerator

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#15217]
They are incredible friendly to me :-P

![schermata 2015-08-03 alle 23 47 08](https://cloud.githubusercontent.com/assets/10136428/9068593/76802722-3ae4-11e5-8569-1ed0b79443c4.png)

Strangely Wowhead says this NPC is not in game
http://www.wowhead.com/npc=21985/skettis-eviscerator

DB 335.8
Core b42cf8755bfb

**Comment by robinsch** [comment]
Entire Skettis is wrongly spawned.

**Comment by tkrokli** [comment]
http://wotlk.openwow.com/npc=21985 ... at least this page has some useful information about the NPC.

**Comment by robinsch** [comment]
Ask yourself why, it's using TDB as resource.

**Comment by Aokromes** [comment]
I vote another incorrect faction by massive sniffs dump :P

**Comment by CreshandKesh** [comment]
``` sql
-- Table `creature_template`
UPDATE `creature_template` SET `faction` = 1862 WHERE (entry = 21985);
```

**Comment by MrSmite** [comment]
I don't know what backend this wowhead clone uses but they indicate they're hostile to A / H

http://wowhead.project-nemesis.cz/an/?npc=21985

**Comment by Kittnz** [comment]
There are some events missing there and when i did the fly paths for the birds every npc tried to attack me. but that could be before the faction change

**Comment by MrSmite** [comment]
Don't know what backend this wowhead clone uses but it shows these as hostile to A / H

http://wowhead.project-nemesis.cz/an/?npc=21985
