### ISSUE TITLE
[3.3.5]Crash 

### ISSUE THREAD

**Issue by Laintime** [TrinityCore/TrinityCore#15215]
rev. https://github.com/TrinityCore/TrinityCore/commit/747ea7ca2c2b757dc9c5a672746d801a8365ee98
http://pastebin.com/JaDBvSeJ

Patch :Transmogrification,passiv anticheat.

**Comment by Laintime** [comment]
Invalid,close issue.

**Comment by DDuarte** [comment]
Is it?

**Comment by tkrokli** [comment]
Looks similar to at least one of the other reported Assert crashes. I am pretty sure I read a crash log during the last few days containing the same text `Assert (file=file@entry=0x1bed238 "/root/ovh.d/1/src/server/game/Entities/Object/Object.cpp", line=line@entry=312, function=function@entry=0x1beda34`
and other lines mentioning Object.cpp:312, but I failed to find the issue where the log was posted.

**Comment by Frytiks** [comment]
Most of tíme this is done by custom item scripts or by deleting item, when player is no more at world
