### ISSUE TITLE
[3.3.5] BG/IC Seaforium bombs can't get deactivated

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#15212]
Hash: https://github.com/TrinityCore/TrinityCore/commit/ce4bd3c2de8c78466f54846c3e24bc35fedfc8d8
TDB 335.59

The players of the enemy faction of the player who placed the bomb are supposed to be able to deactivate these traps by clicking on them, right now you can click on them but nothing happens, they are not deactivated so then the bomb explodes anyways.

The bombs have a script called go_massive_seaforium_charge to deactivate them when click on the bomb but it doesn't work.

**Comment by Keader** [comment]
confirm

**Comment by Aokromes** [comment]
#6626
