### ISSUE TITLE
Cmake Error (Wrong IDE)

### ISSUE THREAD

**Issue by Helnesis** [TrinityCore/TrinityCore#15214]
Hello

I have a problem : I just did a format on my computer due to a problem with my hard drive and now I cannot find Visual Studio 2013 with update 4. I have directly downloaded the Update 5. BTW I'm on Windows 10 !

Now, CMake does not support my VS version.

Would there be a solution for this trouble ? Or maybe just pass me the setup to install VS2013 update 4 ?

Core(6.x):https://github.com/TrinityCore/TrinityCore/commit/dc791d4286d236cf4cdb09241a3eabecd4f447e5
DB :  TDB 6.02
OS : Win10 (I know, it's stupid. But Windows does not let me choose :()

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by DDuarte** [comment]
What do you mean with "Now, CMake does not support my VS version."

![](http://i.imgur.com/cBN05VU.png)

**Comment by tkrokli** [comment]
@Helnesis : Could it be that the first time you install CMake, it does not show "Visual Studio 12 2013" or "Visual Studio 12 2013 Win64" as the automatically selected version, only an older compiler version?
Have you tried to drop down the scroll list under "Specify the generator for this project" and browse through the available versions in the list? I had to select it manually when I reinstalled CMake on Windows 10.

**Comment by Helnesis** [comment]
Yes, I have chosen the correct version VS I have, I CMAKE_COMPILATER_NOT_FOUND etc... error when I set everything well .. Before my PC problem, I could compile with Visual Studio 2013 With Update 4 (and I do not compile in 64-bit.)

Sry for my bad english.

**Comment by DDuarte** [comment]
Start Cmake GUI as Administrator.

**Comment by tkrokli** [comment]
I agree. Also, if you still get the error message `CMAKE_COMPILER_NOT_FOUND`, I think you should try reinstalling Visual Studio 2013 Update 4 (Community edition or Desktop Express) to make sure that CMake reads the program info correctly from your OS settings. Make sure to reboot the computer after reinstalling VS2013.
