### ISSUE TITLE
[3.3.5] DB/Quest: Elemental War - Complete Quest gossip

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15213]
rev. e6571f9869ec 2015-08-02 01:03:14 +0200 (3.3.5 branch)

http://www.wowhead.com/npc=11862/tsunaman
http://www.wowhead.com/quest=6393/elemental-war

![elemental war quest completion](https://cloud.githubusercontent.com/assets/4903600/9027264/18af86e2-394f-11e5-981e-b3113db60c23.png)

http://wow.gamepedia.com/Quest:Elemental_War
**Patch changes**
> Patch 1.2.0 (2004-12-18): Quest text for the Elemental War quest is changed. It no longer implies that a choice of rewards is available.

```sql
UPDATE `quest_template` SET `OfferRewardText` = "The water spirits within me bubble with the excitement. $N, you have given me a glorious victory to report to the Tribunal of the Tides.$b$b" WHERE `ID`= 6393;
```
This query removes the text "For your efforts, I reward you with a choice of my prized possessions."
(I have only used "WHERE `ID`= 6393" for this query. Tell me if it needs more than 1 clause and value.)

Edit: I have tested it on my core and TDB 335.59 + updates, it works as intended. :-)

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/aff9672b35b6a4d620bc36eef472fc4b354b8257
