### ISSUE TITLE
Core/Quest: quests with SpecialFlags=2 are autocompleted

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15216]
rev. dc791d4286d2
Take any quest with SpecialFlags=2 (Quest is enabled and not auto-completed.) and it will be auto completed.
Example quest: 2561 must be completed once the player use an item on the npc corpse (spell=10617) but actually it's auto-completed once it's taken.

**Comment by Kittnz** [comment]
6.x only?

**Comment by Killyana** [comment]
Yes

**Comment by CreshandKesh** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Quests/QuestDef.cpp#L310
``` cpp
bool Quest::IsAutoComplete() const
{
    return !sWorld->getBoolConfig(CONFIG_QUEST_IGNORE_AUTO_COMPLETE) && (Type == QUEST_TYPE_AUTOCOMPLETE || HasFlag(QUEST_FLAGS_AUTOCOMPLETE));
}
```

**Comment by MitchesD** [comment]
@CreshandKesh wtf? It's not related, he is talking about special flag, you are talking about quest type and flags

**Comment by xerkoss** [comment]
Any news on that?

**Comment by xerkoss** [comment]
struct QuestStatusData has no "Explored" bool . That's the only reason.  The same for "timer", has no db column to add the timer for quests. They were removed on 6.x with no sense.

**Comment by Killyana** [comment]
Still valid on rev. 7f2b7dc9c216

**Comment by Naddley** [comment]
works rev. 85205d8ca5d4
![Unbenannt](https://user-images.githubusercontent.com/64811442/202919683-f86beb11-0376-4fdd-a6d3-eeb5061df749.PNG)
