### ISSUE TITLE
[335] AHBot missing config options (DIFF included)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15221]
__Core:__ 718c238524e5d9bc4d43c56c4870c78af794f520 (still exists on https://github.com/TrinityCore/TrinityCore/commit/177b6319d1ad49a38fbd06f37671da1e3d1ae4e6)
__DB:__ N/A

__Bug:__

The AHBot config is missing the following price configs so the core ends up using default values:

> AuctionHouseBot.Items.Gray.Price.Ratio = 100
 AuctionHouseBot.Items.White.Price.Ratio = 100
 AuctionHouseBot.Items.Green.Price.Ratio = 100
 AuctionHouseBot.Items.Blue.Price.Ratio = 100
 AuctionHouseBot.Items.Purple.Price.Ratio = 100
 AuctionHouseBot.Items.Orange.Price.Ratio = 100
 AuctionHouseBot.Items.Yellow.Price.Ratio = 100

__Notes:__

* I didn't notice a commit specifically removing these options ("search this repository")
* These options are looked for in *AuctionBotConfig::GetConfigFromFile()* but since they're not in the CONF they default to 100
* These values are part of the price ratio formula in *AuctionBotSeller::LoadSellerValues()* and are intended for the server admin to be able to influence the various prices of items listed by quality (eg: a [Traveler's Backpack](http://www.wowhead.com/item=4500/travelers-backpack) without these settings results in a sell price of roughly 87 silver - the price a vendor would buy it from you for - based solely on the faction price ratio of 100).
* Since these options relate to the AHBot Seller so they shouldn't effect commit https://github.com/TrinityCore/TrinityCore/commit/177b6319d1ad49a38fbd06f37671da1e3d1ae4e6 related to buyout chances

**Comment by MrSmite** [comment]
Posting a DIFF for now, when I try to push to my clone TortoiseGit crashes...

```DIFF
From 8f5cc69c3fe4903fc739c13b78073260e7854afa Mon Sep 17 00:00:00 2001
From: MrSmite <bull@deadmines.cave>
Date: Wed, 5 Aug 2015 01:08:29 -0400
Subject: [PATCH] Add missing AHBot quality price ratio to CONF

---
 src/server/worldserver/worldserver.conf.dist | 13 +++++++++++++
 1 file changed, 13 insertions(+)

diff --git a/src/server/worldserver/worldserver.conf.dist b/src/server/worldserver/worldserver.conf.dist
index 447ef9a..23b2684 100644
--- a/src/server/worldserver/worldserver.conf.dist
+++ b/src/server/worldserver/worldserver.conf.dist
@@ -2943,6 +2943,19 @@ AuctionHouseBot.Horde.Price.Ratio = 100
 AuctionHouseBot.Neutral.Price.Ratio = 100
 
 #
+#    AuctionHouseBot.Items.QUALITY.Price.Ratio
+#       Description: Percentage by which the price of items sold of each quality is incremented / decreased (for all houses)
+#       Default:     100 - (No change)
+
+AuctionHouseBot.Items.Gray.Price.Ratio = 100
+AuctionHouseBot.Items.White.Price.Ratio = 100
+AuctionHouseBot.Items.Green.Price.Ratio = 100
+AuctionHouseBot.Items.Blue.Price.Ratio = 100
+AuctionHouseBot.Items.Purple.Price.Ratio = 100
+AuctionHouseBot.Items.Orange.Price.Ratio = 100
+AuctionHouseBot.Items.Yellow.Price.Ratio = 100
+
+#
 #    AuctionHouseBot.Items.ItemLevel.*
 #       Description: Prevent seller from listing items below/above this item level
 #       Default:     0 - (Disabled)
-- 
1.7.11.msysgit.1

```

**Comment by tkrokli** [comment]
> , when I try to push to my clone TortoiseGit crashes...

Could it have anything to do with most of your branches are updated in 2014 and the "master" branch?
I was going to suggest that I could make a PR from my fork to yours and then you could use the change to open the PR the normal way, but for that to work you would need a 3.3.5 branch updated to 747ea7ca2c .

**Comment by jackpoz** [comment]
these configs are missing since the PR https://github.com/TrinityCore/TrinityCore/pull/12917

**Comment by MrSmite** [comment]
> Could it have anything to do with most of your branches are updated in 2014

Actually I was trying to update my fork first but when it kept crashing I gave up.

> As for the tortoise crash, try updating http://msysgit.github.io/ , I see your diff used version 1.7.11 but latest is 1.9.5

Thanks, I will update when I have a minute. Come to think of it, it was a git dll related crash I was seeing, generated by *tortoiseproc.exe*

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fed67f5bc1d531f51b110915e2384333e342c1ed

**Comment by MrSmite** [comment]
> fed67f5

Thanks, I was just popping in to do a proper PR :)
