### ISSUE TITLE
in Object::SetFlag(unsigned short trinitycore) ASSERT FAILED crash

### ISSUE THREAD

**Issue by selenir** [TrinityCore/TrinityCore#15227]
b574c99

I don't have a crashlog, can't enable cause of big amount of players.

Just asking, maybe someone experienced that. I've read on RU forums that this may be caused by Gunship, no idea how to translate their language:
http://trinity-core.ru/threads/gunship-battle-%D0%91%D0%B8%D1%82%D0%B2%D0%B0-%D0%BD%D0%B0-%D0%BA%D0%BE%D1%80%D0%B0%D0%B1%D0%BB%D1%8F%D1%85.6916/page-8

**Comment by jackpoz** [comment]
What has "big amount of players" to do with debugging symbols and crashlogs ?

**Comment by Shauren** [comment]
This is completely useless. We cannot read russian and you have not actually posted anything valuable (and you claim that you even cannot do that)

**Comment by selenir** [comment]
As I personally know, to enable crashlog i need to enable debug-mode which makes the server completely unplayable with players (cause of lags)

**Comment by Aokromes** [comment]
Using:

```
declare -x CFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

declare -x CXXFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

cmake ../ -DCMAKE_INSTALL_PREFIX=/change/path/to/trinity -DCMAKE_BUILD_TYPE=None
```

or

```
declare -x CFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O1 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

declare -x CXXFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O1 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"

cmake ../ -DCMAKE_INSTALL_PREFIX=/change/path/to/trinity -DCMAKE_BUILD_TYPE=None
```

Is the way.

**Comment by jackpoz** [comment]
@selenir since you created an incomplete issue, we don't even know what's your platform. With Visual Studio RelWithDebInfo is Release + debug symbols to have a fast worldserver with the ability to create crashlogs

**Comment by selenir** [comment]
Updated OS. Yes, I know that no one would help, cause of no crashlog. I just thought that someone seen this crash before (cause this bug from trinity RU is like 2 years old and my core is updated).
