### ISSUE TITLE
[6.x] Core/quest: PortraitGiverText box and  PortraitGiverName are not shown

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15225]
rev. dc791d4286d2
For some quests there's a portrait, Portrait Name and portrait text shown in addition of the quest texts.
Example of quest: http://www.wowhead.com/quest=14005/the-vengeance-of-elune
But actually only the PortraitGiver is shown, the PortraitGiverText and the PortraitGiverName  are missing.

PortraitGiver=14383

PortraitGiverText = As Malfurion tore the remains of Xavius from Teldrassil, a great weight was lifted from the dying world tree. One last remnant of Xavius remains to torment the night elf people, but Elune's champion approaches to finally free the tree completely.

PortraitGiverName = Bough of Corruption

![schermata ](http://i.imgur.com/ZWlvx1U.jpg)

**Comment by Killyana** [comment]
This box is missing only from the quest accept window, once you take the quest it will appear in the journal and in the quest window (once taken)

![schermata ](http://i.imgur.com/x0llep6.jpg)

**Comment by Keldo** [comment]
I've noticed that some Quest, specifically in Start area's (That's as far as I have tested so far), also show an image box, often with a picture of something that is not even related to the quest.

Tested on an Undead Hunter
DB Version 602 Full with updates

**Comment by ralittle** [comment]
Very annoying cosmetic bug.  The portraits that show the incorrect NPC for the quest you would think you would see them entered in quest_template but the portrait columns are blank.  I have been digging but i cannot find where this bug is coming from.  Does anyone know?

**Comment by Lopfest** [comment]
I want to update this issue. PortraitGiverName is working for sure, PortraitGiverText probably too (not tested), but portraits are not showing on gossip hello at all when quest has flag QUEST_FLAGS_AUTO_ACCEPT. In quest log the portrait is present.

**Comment by Killyana** [comment]
Fixed
