### ISSUE TITLE
NPC with minLevel <> maxLevel levelup animation on respawn

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#15222]
Rev: https://github.com/TrinityCore/TrinityCore/commit/747ea7ca2c2b757dc9c5a672746d801a8365ee98 (fresh compile)
DB: TDB 335.59

Problem: NPC with minLevel <> maxLevel set in db should not has levelup animation during respawn. To reproduce the problem just find any NPC with minLevel <> maxLevel, kill him and wait. If old level will not match new level at respawn, you will see levelup animation for this creature.

This issue mb related for both 6.x and 3.3.5 branches.

**Comment by MrSmite** [comment]
This is an old bug. I think the core spawns the creature at minLevel then levels it up to maxLevel (just a theory).

**Comment by Trisjdc** [comment]
It happens because the level is set *after* the creature becomes visible, so there's a object update packet with the level change, and that causes the level up animation.

**Comment by killradio** [comment]
@Trisjdc 
```cpp
void Creature::Respawn(bool force)
{
    DestroyForNearbyPlayers();

    if (force)
    {
        if (IsAlive())
            setDeathState(JUST_DIED);
        else if (getDeathState() != CORPSE)
            setDeathState(CORPSE);
    }

    RemoveCorpse(false);

    if (getDeathState() == DEAD)
    {
        if (m_DBTableGuid)
            GetMap()->RemoveCreatureRespawnTime(m_DBTableGuid);

        TC_LOG_DEBUG("entities.unit", "Respawning creature %s (%s)",
            GetName().c_str(), GetGUID().ToString().c_str());
        m_respawnTime = 0;
        ResetPickPocketRefillTimer();
        loot.clear();
        if (m_originalEntry != GetEntry())
            UpdateEntry(m_originalEntry);

        SelectLevel();

        setDeathState(JUST_RESPAWNED);

        uint32 displayID = GetNativeDisplayId();
        CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelRandomGender(&displayID);
        if (minfo)                                             // Cancel load if no model defined
        {
            SetDisplayId(displayID);
            SetNativeDisplayId(displayID);
            SetByteValue(UNIT_FIELD_BYTES_0, 2, minfo->gender);
        }

        GetMotionMaster()->InitDefault();

        //Call AI respawn virtual function
        if (IsAIEnabled)
        {
            //reset the AI to be sure no dirty or uninitialized values will be used till next tick
            AI()->Reset();
            TriggerJustRespawned = true;//delay event to next tick so all creatures are created on the map before processing
        }

        uint32 poolid = GetDBTableGUIDLow() ? sPoolMgr->IsPartOfAPool<Creature>(GetDBTableGUIDLow()) : 0;
        if (poolid)
            sPoolMgr->UpdatePool<Creature>(poolid, GetDBTableGUIDLow());

        //Re-initialize reactstate that could be altered by movementgenerators
        InitializeReactState();
    }

    UpdateObjectVisibility();
}
```
SelectLevel() -- function where UNIT_FIELD_LEVEL is set for creature. As you can see visibility updated at the end of all actions. Even state JUST_RESPAWNED set after selecting the level.

**Comment by Trisjdc** [comment]
It'll probably still happen regardless if the object packet from changing a stat is sent on the next tick or ObjectAccessor tick

**Comment by killradio** [comment]
The problem is that unit update packet sent after visibility is updated.

**Comment by jackpoz** [comment]
does this happen with a normal account with .gm off too ?

**Comment by killradio** [comment]
@jackpoz tested with normal account, without gmlevel.

**Comment by Aokromes** [comment]
this is ancient bug, i am sure another ticket for it exists, but can't found.

**Comment by NorthStrider** [comment]
this is probably again the same thing like the respawn issue i mentoined. Blizz doesn't re-use the same creature after respawn, instead they create a entire new unit with new guid and so on.

**Comment by killradio** [comment]
@NorthStrider seems like you are right, but date of last answer is making me sad...

**Comment by MrSmite** [comment]
So running this through the debugger, the problem might be in *SetLevel()*, specifically when it calls *SetUInt32Value()* where it adds the object to an update queue...

```C++
if (m_inWorld && !m_objectUpdated)
{
    sObjectAccessor->AddUpdateObject(this);
    m_objectsUpdated = true;
}
```

Shouldn't we be adding a respawning creature to the update queue after it's fully spawned?

**Comment by MrSmite** [comment]
__Note:__ You can see this same behavior with the GM command __npc set level__, no reason to kill a creature and wait. This seems almost like a client limitation. Unless you have a creature to spawn for each possible level (eg: dynamic GUID) it will assume a "level up" has occurred.

**Comment by killradio** [comment]
@MrSmite thats what I thought - spawn for each min-to-max level. But in NorthStrider's issue they talked about guid recycling, so every spawn will has unique guid everytime. Tested with guid api at official server, and it seems even critters spawned with new unique guid every time. Dunno about "guid recycling", but blizz restart servers every week.

**Comment by MrSmite** [comment]
@killradio 

I think having a spawn in the DB for every possible level would be unnecessary duplication.

Maybe something like a *base_GUID* field in *creature_template* would work and then increment it based on the min / max. For example:

> * Kobold Vermin
* levelMin = 2 ' actually 1 but using 2 for illustration
* levelMax = 3 ' actually 2 but using 3 for illustration
* base_GUID = 1200

> * Forest Spider
 * entry = 30
 * levelMin = 5
 * levelMax = 6
 * base_GUID = 1202

Essentially in *creature_template*, each *base_GUID* is:

__previous_base_GUID + (previous_levelMax - previous_levelMin) + 1__

Using the *Kobold Vermin*, the table *creature* will have spawn data for GUID 1200 (eg: a level 2) but if *SetLevel()* determines a level 3 should spawn, it will use the data from 1200 but give it a GUID of 1201. Likewise, if a *Forest Spider* is spawned, GUID 1202 will be in *creature* for the level 5 but if *SetLevel()* chooses a level 6, it will use a GUID of 1203.

This way the core can spawn any number of levels but only needs data for a single GUID.

**Comment by killradio** [comment]
@MrSmite Im afraid its a bit more "simplier". Every spawn has unique spawn guid, for ex. now at official server spawn counter (guid) ~4M and it rises up from kill to kill. But TC used static lowGUIDs and thats the problem, since every spawn unit has the same guid every time..

**Comment by MrSmite** [comment]
@killradio 

Right, I'm just trying to think of an easier way to implement a level-based spawn instead of essentially rewriting the entire core. So many things depend on a GUID it may be too late to turn back.

**Comment by killradio** [comment]
@MrSmite since 7.x announced, I think its a good time to stop and think "what to do" instead of just run behind blizz and try to make everything they implemented in new addon. Mb idea to start from scratch isnt bad at all, mb develop single branch and single version isnt bad too? Anyway this issue can be closed, lets proceed here https://github.com/TrinityCore/TrinityCore/issues/13787

**Comment by MrSmite** [comment]
@killradio 

I actually like the fact there's still work being done on 335. It seems to be the only "old" version that has a lot of sniff data.

**Comment by pete318** [comment]
I'm almost certain this is a client limitation. The reason why? When testing the possibility to re-use GUIDs for the pooling system I found that the same thing will happen even with pooling if you re-use a guid that has a different level. The client caches, in memory at least the guid and level information and sends the level up animation when it differs.

If a new GUID is used every time you NEVER get the animation regardless of how many times the level changes.

So, if I ever get to finish the merge of the new map based guid change Shauron made in 6.x into 3.3.5 this will be a thing of the past for ALL creatures.

**Comment by killradio** [comment]
@pete318 yeap Im tested this with wow api and guids always increased.

**Comment by Trisjdc** [comment]
I really, really doubt the client caches of objects that were explicitly destroyed with SMSG_DESTROY_OBJECT. Template info will be saved, but not that unit field information.

In fact this whole issue is probably relatively easy to solve by just abusing a bit out of Map::RemoveFromMap and Map::AddToMap just to make sure the object isn't going to be put into the update list. Or just by hack-setting m_objectUpdated

**Comment by Shauren** [comment]
@Trisjdc and you would be mistaken. The object is not fully deleted/freed clientside until some time after despawn passes

**Comment by pete318** [comment]
As I mentioned on IRC last evening, and also in the above linked issue.

Once local guids are implemented, some config options to provide timely restarts to prevent overflows can be implemented. Re-using guids is just a kludge or a hack overall. It's not what they do on retail and they manage to keep running for a whole week (most of the time).

**Comment by MrSmite** [comment]
> Re-using guids is just a kludge or a hack overall. It's not what they do on retail and they manage to keep running for a whole week (most of the time)

How do we know for sure though? They may use a GUID from a dead npc in Elwynn for a respawn in Black Temple. Has that type of analysis ever been done? Is there a tool capable of collecting every GUID for every respawn over a week?

Besides, how would they avoid overflow with millions of players killing things and not restarting for weeks at a time?

**Comment by Aokromes** [comment]
They only reach 7d of uptime and guids are based for each map. And at least guid count are reset for instances, as for continents maybe they reset them too if they are empthy?

**Comment by pete318** [comment]
It's 16,777,216 unique IDs per instance of a map. In terms of the game that means:

Kalimdor: 16,777,216
Eastern Kingdoms: 16,777,216
Outland: 16,777,216
Northrend: 16,777,216
Each instance of a dungeon/raid/battleground map: 16,777,216

Once any of those reaches a threshold a restart should be scheduled for a preset quiet time (a-la 3am like retail).
Once a later threshold is reached, a more urgent shutdown is queued.

It will be a minor inconvenience I think, but will automatically allow the disconnection entirely of creature to guid. That is, even without pooling we can separate corpse despawn and respawn timers.

**Comment by MrSmite** [comment]
What's wrong with a table of available GUIDs `guid`, `level`

```SQL
SELECT `guid` FROM `available_guids` WHERE `level`= myLevel;
```

If the core is spawning the same level then it can reuse the creature's current GUID, otherwise it can select a new one. Would that really put such a burden on the core / db? I don' think thousands of creatures are respawning every second are they?
