### ISSUE TITLE
[3.3.5] DB/Quest: Imp Delivery (dreadsteed questline)

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15236]
TrinityCore rev. a8f447b9eff3 2015-08-07 22:50:49 +0200 (3.3.5 branch)
TDB 335.59 + regular updates + Kilyana's SAI script in **https://github.com/TrinityCore/TrinityCore/issues/8216#issuecomment-128785724** for quest 7624

- Quest 7629, Imp Delivery: (http://wotlk.openwow.com/quest=7629)
- Provided quest item: http://www.wowhead.com/item=18688/imp-in-a-jar
- Using the item spawns: http://www.wowhead.com/npc=14500/jeevee J'eeve (imp)
- Required game object near player when using the item: http://wotlk.openwow.com/object=177387 43204 (Entry: 177387) - [Alchemy Lab X:38.808201 Y:163.686005 Z:83.569801 MapId:289]

**How it works now:** Only able to progress in the warlock Dreadsteed questline after completing Quest 7624 [[Ulathek the Traitor]](http://www.wowhead.com/quest=7624/ulathek-the-traitor), this time entering Scholomance to use http://wotlk.openwow.com/item=18688, Imp in a Jar (uses spell www.wowhead.com/spell=23180/release-imp) with `Effect: Send Script Event (8438)` (not sure what that script event does). I use item 18688, the temporary imp J'eevee spawns while the character kneels like when placing a trap, but that is all. No other action or event happening.

**How it is supposed to work:** J'eevee should walk between the tables & cauldrons and say these lines:
"Ah, here we are! Well let's get to work, shall we...?"
"Oh, right! Over here now..."
"And now... the final step!" (`broadcast_text.ID 9771`)
"I'm finished.  The parchment is made.  Now, return to Gorzeeki..." (`broadcast_text.ID 9742`)
(and then he despawns with some animation looking like his soul is drained towards the ceiling)
Note: the text lines are not in the creature
Watch this YT video, this quest starts at 7:43 (linked with time mark)

[![Warlock dreadsteed quest chain part 1](http://img.youtube.com/vi/n3J8zlEPm7s/0.jpg)](http://www.youtube.com/watch?v=n3J8zlEPm7s?t=7m43s)

From the video, it looks like it used to be possible to spawn the imp just a little bit further away from the table then it currently is in TC source, my imp spawned almost under the lab table at `.gps` coordinates X:38.619999 Y:161.779999 Z:83.545601 Orientation: 4.699930

I suppose there are no sniffs for the imp pathing, so please tell me if I should approximate the waypoints based on the video (and if I use `.gps` or some other command to find the WP coordinates).

**Comment by MrSmite** [comment]
IMO if there are no sniffs then a youtube video should be considered valid if it isn't from another private server.

*offtopic:* I wish Blizzard hadn't taken the lazy way out and abandoned these unique quests. One of my most fond memories of my time on live was the Hunter's epic bow quest chain.

**Comment by tkrokli** [comment]
The only reason some might see this quest as less important than other quests, is the fact that warlocks no longer needed to do this quest to get the dreadsteed. It got trainable sometime when apprentice riding got available at level 20 (I haven't looked up the exact patch number yet). And sure enough, we didn't have any sniffs for #8216 either, so we went with the available info from other sources.

**Comment by Killyana** [comment]
Just a little script is required for this quest: on just summoned start waypoint, in some waypoints (pause + say text), on waypoint end give quest credit then cast cosmetic spell+despawn)

**Comment by Killyana** [comment]
``` sql
UPDATE `event_scripts` SET `x`=38.4345, `y`=156.9295, `z`=83.545, `o`=1.407458 WHERE `id`=8438;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry` IN (14500);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (14500) AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (1450000, 1450001) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(14500,0,0,0,54,0,100,0,0,0,0,0,80,1450000,2,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On just summoned  - Action list"),
(1450000,9,0,0,0,0,100,0,0,0,0,0,64,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Store target"),
(1450000,9,1,0,0,0,100,0,1000,1000,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Say text 1"),
(1450000,9,2,0,0,0,100,0,2000,2000,0,0,53,0,14500,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - Actionlist  - start wp"),
(14500,0,1,0,40,0,100,0,2,14500,0,0,54,3000,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp2 reached  - Pause wp"),
(14500,0,2,0,40,0,100,0,2,14500,0,0,1,1,3000,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp2 reached  - Say text 2"),
(14500,0,3,0,40,0,100,0,7,14500,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp7 reached  - Pause wp"),
(14500,0,4,0,40,0,100,0,8,14500,0,0,1,2,4000,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp7 reached  - Say text 3"),
(14500,0,5,0,40,0,100,0,11,14500,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp11 reached  - Pause wp"),
(14500,0,6,0,40,0,100,0,12,14500,0,0,80,1450001,2,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - On wp12 reached  - Action list"),
(1450001,9,0,0,0,0,100,0,4000,4000,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Say text 4"),
(1450001,9,1,0,0,0,100,0,0,0,0,0,33,14500,0,0,0,0,0,12,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Quest credit"),
(1450001,9,2,0,0,0,100,0,3000,3000,0,0,11,41232,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Cast teleport"),
(1450001,9,3,0,0,0,100,0,1000,1000,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"J'eevee - Actionlist  - Despawn");

DELETE FROM `waypoints` WHERE `entry`=14500;
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
(14500,1, 38.784, 160.639, 83.545, "J'eevee"), 
(14500,2, 36.804, 160.705, 83.545, "J'eevee"),
(14500,3, 39.287, 160.044, 83.545, "J'eevee"), 
(14500,4, 41.666, 154.591, 83.545, "J'eevee"), 
(14500,5, 45.255, 155.014, 83.545, "J'eevee"), 
(14500,6, 44.930, 161.186, 83.545, "J'eevee"), 
(14500,7, 44.347, 161.120, 83.545, "J'eevee"),
(14500,8, 46.758, 157.877, 83.545, "J'eevee"),
(14500,9, 44.640, 154.405, 83.545, "J'eevee"), 
(14500,10, 33.498, 156.046, 83.545, "J'eevee"), 
(14500,11, 28.269, 160.792, 83.545, "J'eevee"),
(14500,12, 33.294, 160.895, 83.545, "J'eevee");

DELETE FROM `creature_text` WHERE `entry` IN (14500);
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`comment`,`BroadcastTextId`) VALUES
(14500,0,0,"Ah, here we are! Well let's get to work, shall we...?",12,0,100,0,0,0, 'J''eevee', 9769),
(14500,1,0,"Oh, right! Over here now...",12,0,100,0,0,0, 'J''eevee', 9770),
(14500,2,0,"And now... the final step!",12,0,100,0,0,0, 'J''eevee', 9771),
(14500,3,0,"I'm finished. The parchment is made. Now, return to Gorzeeki...",12,0,100,0,0,0, 'J''eevee', 9742);

**Comment by tkrokli** [comment]
:smiley: Wow, nice. :+1: I thought I would at least start with the `creature_text` bit, but I took the day off with my girlfriend instead. @Killyana : You work fast when starting on something, I have to give you that. =^.^=

**Comment by MrSmite** [comment]
> The only reason some might see this quest as less important than other quests, is the fact that warlocks no longer needed to do this quest to get the dreadsteed. It got trainable sometime

Yeah, that's probably true. Personally I try to do quests even if they're not required anymore (I'm more of an immersion type player). I tend to play like I'm playing TBC (eg: I don't buy my mount until 40 - although I play Nelfs but like horses and I'm not exalted with Stormwind at 20 anyway).

**Comment by tkrokli** [comment]
Good point, I enjoy getting immersed in the classic quests and content too. :)
