### ISSUE TITLE
[3.3.5a] Cave Yeti is attacking dead player, won't make him revive

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15237]
Cave Yeti is attacking dead player, won't make him revive.

GUID: 16512
Entry: 2248
Location: Eastern Kingdoms, Hillsbrad Foothills, Darrow Hill

Revision: 747ea7ca2c2b757dc9c5a672746d801a8365ee98

![wowscrnshot_080815_205039](https://cloud.githubusercontent.com/assets/1736110/9150343/cdd198de-3e0f-11e5-815d-b3314cb64dd6.jpg)
![wowscrnshot_080815_205108](https://cloud.githubusercontent.com/assets/1736110/9150344/cdf8ef88-3e0f-11e5-8655-046401a3308b.jpg)
![wowscrnshot_080815_205150](https://cloud.githubusercontent.com/assets/1736110/9150345/cdff02b0-3e0f-11e5-8510-6a5e8aa55dd4.jpg)

**Comment by Killyana** [comment]
Cannot reproduce, also the npc doesn't have any script or aura and flags are normal, nothing special about it .

**Comment by digz6666** [comment]
@Killyana if you look at 1st screenshot the creature is targeting player while dead. I killed the creature and he revived.

**Comment by Aokromes** [comment]
Like Killyana said... unable to reproduce:

http://i.imgur.com/CinB8JV.png

**Comment by digz6666** [comment]
Is there any rare cases maybe?

**Comment by Trisjdc** [comment]
Happens when the player isn't 'dead' with the correct death state.
i.e has 0 health, but death state ALIVE

**Comment by digz6666** [comment]
@Trisjdc so maybe another issue.
