### ISSUE TITLE
[6.x] Isle of Conquest Gunships

### ISSUE THREAD

**Issue by Golrag** [TrinityCore/TrinityCore#15238]
rev: https://github.com/TrinityCore/TrinityCore/commit/7732ad5153783ca31d32c6812f21c2b723fd589a
When you are on the (horde) gunship and he is done with his path, you get teleported to nowhere.

After looking around in the code: saw that this line is causing this issue: https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Transport/Transport.cpp#L631

This sends SMSG_MOVE_TELEPORT to the client with transportdata & real position.

On retail (6.2) I didn't receive any SMSG_MOVE_TELEPORT, so I wonder if this is still needed in 6.x :)

**Comment by killradio** [comment]
I bet zeppelin from orgrimmar to thunder bluff has the same issue ;)

**Comment by Aokromes** [comment]
at least on 4.3.4 it was bugged and a ticket for it exists.

**Comment by Golrag** [comment]
@killradio just tested it, and it has the same bug :p

**Comment by Aokromes** [comment]
#12530
