### ISSUE TITLE
[3.3.5a] Naxxramas - The four horseman evade, doors closed

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15239]
Naxxramas - The four horseman's door closed, Thane Korth'azz and Baron Rivendare evades.
Players killed other 2 bosses.

Revision: 3f3ff8b36b0537d07bf8222226ab88346c689e4b

![wowscrnshot_080915_190108](https://cloud.githubusercontent.com/assets/1736110/9154466/e68a9f82-3ec9-11e5-952d-4744178056c5.jpg)
![wowscrnshot_080915_190141](https://cloud.githubusercontent.com/assets/1736110/9154464/e6898a8e-3ec9-11e5-91f6-341b2aec723e.jpg)
![wowscrnshot_080915_190316](https://cloud.githubusercontent.com/assets/1736110/9154465/e68a65f8-3ec9-11e5-95fc-e22f470ed155.jpg)

**Comment by Killyana** [comment]
Not sure about the evade issue but problem with doors is known: https://github.com/TrinityCore/TrinityCore/issues/6377

**Comment by Warhearth** [comment]
Located src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp

             //can't use entercombat(), boss' dmg aura sets near players in combat, before entering the room's door
-            instance->SetData(TYPE_BARON, IN_PROGRESS);
+            if (instance && instance->GetData(TYPE_BARON) == NOT_STARTED)
+                instance->SetData(TYPE_BARON, IN_PROGRESS);
Add this code to see if works I'm going to test it.

**Comment by Warhearth** [comment]
Confirmed working with new code thanks to cr4st.

**Comment by digz6666** [comment]
@Warhearth why it modifies code in stratholme folder? Did you applied fix to naxxramas folder?

**Comment by Warhearth** [comment]
I edited boss_baron_rivendare.cpp got it to work.

**Comment by Warhearth** [comment]
@digz6666 This fixes the doors confirmed working I did not encounter evade issue though.

**Comment by chaodhib** [comment]
#6377 is about Baron Rivendare in Stratholme. This is a completely different issue.

**Comment by Treeston** [comment]
assume closed by #16194
