### ISSUE TITLE
[6.x] Undead starting problems regarding Rigor Mortis

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15248]
I noted a bug in undead character start, regarding the "debuff" that you get once you create character and login called [Rigor Mortis](http://www.wowhead.com/spell=73523/rigor-mortis) spell.

Details:
* Non DK characters:
    * RETAIL: Rigor mortis is a buff (appears in the top side with the "good" buffs), and is dispelleable by user by making right click on it
    * TC: Rigor mortis is a debuff (appears a little down of the other buffs), and is **not** dispelleable by user by making right click on it
* DK characters:
    * RETAIL: Rigor mortis is not present at all
    * TC: Rigor mortis is a debuff, like above

In this case, the bug is important, as this makes DK character unplayable (because in non DK, the first quest you can take, removes you Rigor Mortis correctly, but that quest is not present in DK zone, so you can't simply move)

Tested in rev 590c6e399d778db459fc8417322c80549081440a

**Comment by Killyana** [comment]
```
UPDATE `playercreateinfo_cast_spell` SET `classMask`=925 WHERE `raceMask`=16 AND `spell`=73523;

**Comment by StormBytePP** [comment]
And the fix for it to not be a debuff but a dispelleable buff? That was the
another point. Thanks Killiana :)

**Comment by Goatform** [comment]
Try to use some of those attributes:
```diff
SPELL_ATTR0_DEBUFF
SPELL_ATTR0_PASSIVE
SPELL_ATTR0_CANT_CANCEL

**Comment by killradio** [comment]
@StormBytePP try this to make it positive:
```diff
diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index 94fc49a..b83c841 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -2918,6 +2918,7 @@ bool SpellInfo::_IsPositiveEffect(uint32 effIndex, bool deep) const
                 case 62344: // Fists of Stone
                 case 61819: // Manabonked! (item)
                 case 61834: // Manabonked! (minigob)
+                case 73523: // Rigor Mortis
                     return true;
                 default:
                     break;

```

**Comment by StormBytePP** [comment]
Thanks for the hints :)

**Comment by killradio** [comment]
@StormBytePP its not "hints" in this case and yes, you are welcome.
