### ISSUE TITLE
[6.x]DBC files and worldserver dataDir inconsistency

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15240]
DBC extractor, extracts data to dbc/&lt;LOCALE&gt;/ folder, but worldserver expects the data to be directly in dbc/ folder, which leads to confusion for new users, and is a clear inconsistency.
It is a minor problem, but with an easy fix. As Nay said on forums, it might have problems with file collissions between different locales, so the current behavior of DBC extractor can be kept, but we have to modify worldserver behavior.

This is my idea:
In worldserver, we have a config for the locale of the server, being it autodetect, or force set to any (I force to esES in my server). Usually, when you force it, means that you extracted your data with your locale and don't have others.
So, 
1) for DBC files, worldserver take this config option
2) With 1), look in the <locale> folder for the files
3) if the folder don't exist, then grab the files for the first subfolder of dataDir/dbc (Issue a warning in this case)
4) If no folder is present, that means that we had moved the files to make it run, so in order to keep it working without forcing people to re-extract the files, look at dbc root and issue a warning that this will be removed in the future so they can migrate again to original.
5) It can be saved to a member variable (or somewhere else), so when it has to look for files, we could have a boost::filesystem::path variable pointing to exactly where the files are detected in previous points.

I forgot to mention that this happened since always, but I put the rev I have so it is not getting closed by the bot: rev 00a77230bdee8bb7e6483e77aaa8b7127b712931

**Comment by Shauren** [comment]
Funny, 3.3.5 extractor does NOT do this, only 6.x behaves like that (and you linked a 3.3.5 rev)

**Comment by StormBytePP** [comment]
Created a PR #15253 for initial feedback/testing
