### ISSUE TITLE
[6.x] Warning: 'unitSpeedChanged' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15242]
Seems that a override keyword is missing in header file, easy to fix, not worth a PR just for this :)

REV:  590c6e399d778db459fc8417322c80549081440a

The complete warning is:

In file included from /data/Trinity/6.x/sources/src/server/scripts/Commands/cs_mmaps.cpp:31:
/data/Trinity/6.x/sources/src/server/game/Movement/MovementGenerators/PointMovementGenerator.h:39:14: warning: 'unitSpeedChanged' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void unitSpeedChanged() { i_recalculateSpeed = true; }
             ^
/data/Trinity/6.x/sources/src/server/game/Movement/MovementGenerators/PointMovementGenerator.h:52:44: note: in instantiation of template class 'PointMovementGenerator<Creature>' requested here
class AssistanceMovementGenerator : public PointMovementGenerator<Creature>
                                           ^
/data/Trinity/6.x/sources/src/server/game/Movement/MovementGenerator.h:44:22: note: overridden virtual function is here
        virtual void unitSpeedChanged() { }
                     ^
1 warning generated.

**Comment by DDuarte** [comment]
Every little fix is worth a PR :)

**Comment by StormBytePP** [comment]
Ok, created a PR: #15243 :)

**Comment by DDuarte** [comment]
Thanks :)

Just a tip: create a branch for each PR otherwise it's gonna be hard to keep them all in 6.x.

**Comment by StormBytePP** [comment]
@DDuarte Can you reopen the issue? This also applies to 3.3.5x branch, and we applied the PR to 6.x branch only. I guess it is a candidate for a cherry pick

**Comment by DDuarte** [comment]
I'll do the cherry-picks shortly, there's a bunch of them piling up.

**Comment by StormBytePP** [comment]
@DDuarte No need to cherry pick, I created a PR only for 3.3.5 as there were more override missings I fixed altogerher. PR is #15255

**Comment by DDuarte** [comment]
Look at the list at #15078 and 15078. Do you think 1 more commit will make a difference? :)

**Comment by StormBytePP** [comment]
Oops, what a huge list! Just told you as you could just forget it :)
