### ISSUE TITLE
ICC traps are activated in wrong place

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15241]
Inside ICC raid, when you enter, there are invisible traps which activate huge skeletons.
I noted that these traps gets activated where vending NPC are, and they shouldn't.
Happened some time ago, also with rev 747ea7ca2c2b757dc9c5a672746d801a8365ee98 (tested in 3.3.5 but maybe also affects 6.x)
Will try to provide a sniff for complete ICC soon.

EDIT: I don't have a rogue in retail, but I think a rogue can see and deactivate the traps, better if one person with a rogue providing the sniffs for that

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/4590
