### ISSUE TITLE
[NPC][Locales] Wrong Female and Male Name

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15250]
rev: https://github.com/TrinityCore/TrinityCore/commit/d69a31d238122ab1ceb998908ebf218299792a16
Forgive me if this is an dublicate. I searched for https://github.com/TrinityCore/TrinityCore/search?p=1&q=female+male&type=Issues&utf8=%E2%9C%93 and could not find any related report.

Problem: Sometimes a FEmale model gets the MAle Creaturename
Example: http://i.imgur.com/9zuas1r.jpg
How it should be: Female Model should always have the female Creaturename

:)

**Comment by DDuarte** [comment]
"How it should be: Female Model should always have the male Creaturename" isn't that a typo?

**Comment by Rushor** [comment]
meh copypastefail - ty

**Comment by Killyana** [comment]
It's specific to some languages, the word "sailor" in french: "marin" is used for both sex, and for other npcs like http://www.wowhead.com/npc=27202/onslaught-raven-priest the world prêtre in used for male and prêtresse for females.
In locales or even npcs names from creature_addon we don't have "female_name".
We have to check if blizzard use such female_names.

**Comment by tkrokli** [comment]
Is your example image showing a female or male name? I could not tell just by looking up "Matrose" in Google Translate. In English, there is no distinction between male or female military or navy titles, only in some titles like actor/actress or lord/lady. I presume the German NPC names are a lot more obvious when it comes to gender. What is the supposed name for a female NPC if your image is showing the wrong title? (I don't want to install the German game client on my computer just to explore your issue.) ;-)

**Comment by Killyana** [comment]
Edit:
It's implemented in 4.x and 6.x, It just must be ported for 3.x

**Comment by Kinzcool** [comment]
It can't be ported to the 3.3.5 because this feature did not exist back then; the required fields in SMSG_CREATURE_QUERY_RESPONSE are not present.

**Comment by Rushor** [comment]
but the issue is still there no?

**Comment by Kinzcool** [comment]
Well, it can't be fixed. It is blizzlike behavior as of 3.3.5.

**Comment by tkrokli** [comment]
Label this issue [ Invalid-Intended-WontFix ], maybe? :)

**Comment by Rushor** [comment]
okay thanks for this inforamtion @Kinzcool
