### ISSUE TITLE
[3.3.5]Crash Unit::SetCharmedBy

### ISSUE THREAD

**Issue by Laintime** [TrinityCore/TrinityCore#15261]
Rev https://github.com/TrinityCore/TrinityCore/commit/e3c3b8f08fad0853ca9452ae382d13f99ded2fcc
DB -TDB last
Patch - Trans,passiv anticheat.
Backtrace log http://pastebin.com/r7y75sz8

**Comment by Frytiks** [comment]
Never had this crash, maybe related to anticheat ?

**Comment by Laintime** [comment]
There was not mean that it is,repeat 1 time per week.

**Comment by Frytiks** [comment]
Can you try to cast on yourself Dominate Mind spell from Lady deathwhisper and alt+f4 ?

**Comment by Laintime** [comment]
@Frytiks no cast "You can`t do this at the moment."You can not apply for this"

**Comment by StormBytePP** [comment]
I never had any crash, maybe it is related to one of the patches you applied.

**Comment by Frytiks** [comment]
Go at lady, wait until you get this and alt+f4 or cast any spell on yourself what charm you

**Comment by jackpoz** [comment]
> See backtace log,no anticheat crash.

that's not really how it works, even a little change could create crashes in totally unrelated places in the code

**Comment by Laintime** [comment]
@jackpoz thx,sory is invalid.I try to fix queen_vampiric_bite. 
```diff

-			if (InstanceScript* instance = GetTarget()->GetInstanceScript())
-			{
-				if (instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == IN_PROGRESS)
-				{
-					if (GetTarget()->GetCharmerGUID() == instance->GetData64(DATA_BLOOD_QUEEN_LANA_THEL))
-					{
-						valid = true;
-					}
-				}
-			}
-
-			if (!valid)
-			{
-				GetTarget()->RemoveAurasDueToSpell(SPELL_UNCONTROLLABLE_FRENZY);
-				GetTarget()->RemoveAurasDueToSpell(SPELL_UNCONTROLLABLE_FRENZY_1);
-				GetTarget()->RemoveAurasDueToSpell(SPELL_UNCONTROLLABLE_FRENZY_2);
-			}
```
