### ISSUE TITLE
Character DB (Deprecated Items)

### ISSUE THREAD

**Issue by Expecto** [TrinityCore/TrinityCore#15264]
After deleting account in char table account_data remain data of empty id from account db.
Sorry, I do not know very well the English...
![default](https://cloud.githubusercontent.com/assets/961673/9209296/68719dd8-407e-11e5-9c7a-d92d539d9f33.png)

DB Last Ver 3.3.5a
Hash: eb2e8f873a5e1950446223a31872f5deed0307fe

**Comment by DDuarte** [comment]
Are these rows deleted after you run the Character Cleanup procedures?

**Comment by DDuarte** [comment]
How did you delete the account?

**Comment by DDuarte** [comment]
Always delete the account with the command `.account delete` and never edit the database directly.
