### ISSUE TITLE
[3.3.5] Core/quest: Timed quests shouldn't turn failed once completed

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15279]
rev. d69a31d23812
Example:
http://www.wowhead.com/quest=2969/freedom-for-all-creatures

Take the quest, complete it with .quest complete, then wait until the timer expire, you will see the quest will turn failed and you cannot turn it any more.

If I'm not wrong, once the quest completed the timer must turn off.

A similar issue was fixed here: https://github.com/TrinityCore/TrinityCore/pull/12959

**Comment by Nyeriah** [comment]
This is wrong, some quests can turn failed once complete (there has been a discussion in the past about this). Consider this comment:

> 2) Consider the timed quest:
> http://www.wowhead.com/quest=647
> 
> This quest has no additional requirements and is completed right after taking this quest from the questgiver. Thus, the timer for the quest does not have any sense anymore after that change, because the quest can not fail at all.

https://github.com/Elron103

It was working like that before (I mean, timed quests wouldn't fail once complete) but it has been changed as there are exceptions of quests that can fail while complete
