### ISSUE TITLE
[3.3.5][6.x] Core/DBlog: Non existing spell effects used by conditions are not notified

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15274]
rev. d69a31d23812
rev. f85ac2791236

For both 3.3.5 and 6.x, if you made a condition for a spell effect that doesn't exist it will not be notified in the logs.
Example:

``` sql
SELECT* FROM conditions WHERE SourceEntry IN (44885, 45201, 45203, 46350, 51395);
```

All these spells have only effect1 but in the conditions effect2 and effect3 are used, but nothing is shown in the DBlogs.
I got this errors on the 4.3.4 DBlogs.

**Comment by Aokromes** [comment]
still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
