### ISSUE TITLE
[3.3.5][Core/Spell] Warrior Intimidating Shout

### ISSUE THREAD

**Issue by lineagedr** [TrinityCore/TrinityCore#15288]
Spell http://www.wowhead.com/spell=5246/intimidating-shout 

When you get feared by that spell you can use emotes while in feared state. ie: sit,dance etc..

rev: c1e3fdc
(3.3.5a)
db:335.59_2015_07_14

**Comment by Aokromes** [comment]
still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.

**Comment by CraftedRO** [comment]
c3e43d3d31d8 Still valid.
