### ISSUE TITLE
[Dev]Core: Normalisation for the 2 branches

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15285]
3.3.5 https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Conditions/ConditionMgr.h#L76

6.x https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Conditions/ConditionMgr.h#L93

The Missing commit for 6.x: https://github.com/TrinityCore/TrinityCore/commit/5f8db047614a492dd178325b429839609d9f7fc5

**Comment by Vincent-Michael** [comment]
Add this in #15077 + 5f8db047614a492dd178325b429839609d9f7fc5

**Comment by msoky** [comment]
and what about merge between https://github.com/TrinityCore/TrinityCore/commit/fbca2bfd6a2ea0c03f0e94d406650c19847d8e9f and https://github.com/TrinityCore/TrinityCore/commit/654332e94b0ef746309251b77f5658f5b6a03c62 ?

**Comment by Killyana** [comment]
It will be done later by Nayd, there's already a list.
