### ISSUE TITLE
[6.x] Bnetserver - R6010 - abort() has been called

### ISSUE THREAD

**Issue by galathil** [TrinityCore/TrinityCore#15284]
TrinityCore Version : TDB.6.02 (https://github.com/TrinityCore/TrinityCore/commit/f5e92f65379aa03890605539eeafccb665e08ebc)

I found a bug with the BnetServer. 

I was with a friend on Skype (video conference) and impossible to start the application. It started correctly but  quitting immediately with this error message. After exit the calling, it will work correctly ! But impossible to reproduce the bug

``````````````````````````````````````
R6010
- Abort () has-been called Expired
``````````````````````````````````````````

I will join the crashlog : http://pastebin.com/z8xqcgnF

**Comment by Aokromes** [comment]
Iirc they both share the same port.

**Comment by DDuarte** [comment]
Change the [WorldserverListenPort](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/bnetserver/bnetserver.conf.dist#L55) from 1118 to something else

**Comment by galathil** [comment]
My Skype calling takes the port 1118 and the btnserver crashes... Normally, the problem can't appear on a server but on my dev PC it can arrived because on each calling, skype takes a port randomly. Well, no chance for this calling ^^

**Comment by DDuarte** [comment]
Now it will still crash or exit however it tells you why it happened.

**Comment by galathil** [comment]
thx
