### ISSUE TITLE
[3.3.5] LootItem::canSave always true

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#15299]
I could not find anything setting the LootItem::canSave to false so unless I missed something it is always true and thus unused for whatever purpose.
Instead it seems islooted would be better or if canSave should have been used to track if the loot is saved to database then initially it should be set to false until actually saved and set to true on delete.

Should either implement intended functionality or remove the variable if really unused (always true).
https://github.com/TrinityCore/TrinityCore/blob/ca5a2785f760a90ceb0c3d321da208ee07552f87/src/server/game/Loot/LootMgr.h#L166

branch: 3.3.5, probably also other branches
https://github.com/TrinityCore/TrinityCore/commit/ca5a2785f760a90ceb0c3d321da208ee07552f87

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/04f08d26a72ab29b11fc2aaef65bc54078cc2086 by @MrSmite added canSave, in case it can help figure out if there's a typo or a missing = false somewhere

**Comment by MrSmite** [comment]
```C++
+            // When an item is looted, it doesn't get removed from the items collection
+            //  but we don't want to resave it.
```

Indicates that during my testing I encountered an item that was saved twice. I probably should've noted what item it was.

**Comment by jackpoz** [comment]
@MrSmite with "testing https://github.com/TrinityCore/TrinityCore/commit/04f08d26a72ab29b11fc2aaef65bc54078cc2086#diff-c59edca94cdcc9d6c7296674c932be16R1248 " I meant adding a breakpoint at https://github.com/TrinityCore/TrinityCore/commit/04f08d26a72ab29b11fc2aaef65bc54078cc2086#diff-c59edca94cdcc9d6c7296674c932be16R1249 as reproducing a case that would hit the breakpoint.

Is that "_itr->canSave = false;" a WIP or is it the correct code ?

**Comment by MrSmite** [comment]
> Is that "_itr->canSave = false;" a WIP or is it the correct code ?

I haven't tested it yet, I was just brainstorming while looking at the sources. Since *canSave* defaults to *true* and the comment I left in that block is to "to prevent resaving", I think that should be *false*. Then when the actual save happens that item would be ignored.

> I meant adding a breakpoint at 04f08d2#diff-c59edca94cdcc9d6c7296674c932be16R1249 as reproducing a case that would hit the breakpoint.

Gotcha. To be honest, it's been so long since I wrote this and I don't recall ever having an issue with loot being save that shouldn't be.

**Comment by jackpoz** [comment]
kk, then it's just a matter of changing https://github.com/TrinityCore/TrinityCore/commit/04f08d26a72ab29b11fc2aaef65bc54078cc2086#diff-469201924aa4feec87dd70a2bf60bb14R672 to
```
_itr->canSave = false;
```
(writing it again for who wants to test and merge it)

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.
