### ISSUE TITLE
[6.x] Pets

### ISSUE THREAD

**Issue by LebenHarvest** [TrinityCore/TrinityCore#15298]
f979b28

Pets have no spell bars. As well they do not attack when the player attacks etc.

**Comment by Zerixx** [comment]
See Opcodes.cpp. If it says STATUS_UNHANDLED .... well, it's unhandled. Pets aren't fixed up just yet.

**Comment by LebenHarvest** [comment]
I am well aware... regardless an issue report is valid.

**Comment by StormBytePP** [comment]
An issue report about opcodes being disabled and advertised in Opcodes.cpp is not valid. It would be valid if enabling it makes it work, or if it is enabled and has some kind of fault. But not valid just because opcode is not enabled per-se

**Comment by Rushor** [comment]
duplicate from https://github.com/TrinityCore/TrinityCore/issues/14794
