### ISSUE TITLE
[3.3.5] (Ward of Laze) Mosh'ogg Witch Doctor totems not stationary and missing aura

### ISSUE THREAD

**Issue by Funkeln** [TrinityCore/TrinityCore#15304]
rev https://github.com/TrinityCore/TrinityCore/commit/30fc4f9f63b7a0ce01e5aad4667902991b70e298

http://www.wowhead.com/npc=2667 is not stationary and chases players. Should be stationary as it's a totem. Also, it does not cast http://www.wowhead.com/spell=3826/ward-of-laze-effect (Ward of Laze effect) on nearby players

They're summoned by http://www.wowhead.com/npc=1144/moshogg-witch-doctor

**Comment by tkrokli** [comment]
````sql
UPDATE `creature_template` SET `speed_walk`= 0, `speed_run`= 0, `unit_flags`= 4, `spell1`= 3826 WHERE `entry`= 2667;

**Comment by Aokromes** [comment]
speed 0 is hack.

**Comment by tkrokli** [comment]
OK, I'll remove the speed settings and let `unit_flags`= 4 `UNIT_FLAG_DISABLE_MOVE` be the fix.

**Comment by Killyana** [comment]
Better to do it with SAI: just summoned - desable movement  and IC - cast 3825 every 3 secs
Also spell 1, 2, 3 ect.. are used for spell bars like vehicles and pets.

**Comment by tkrokli** [comment]
WIP :
```sql
UPDATE `creature_template` SET `unit_flags`= 4, `AIName`= 'SmartAI' WHERE `entry`= 2667;

-- Ward of Laze SAI
-- (need to continue this tomorrow)

**Comment by ShinDarth** [comment]
@tkrokli  You're welcome! And thank you for the fix!

**Comment by tkrokli** [comment]
@Killyana : does my SAI look OK now, or does it need more adjustments?
@Funkeln : can you test this script for me, I don't have my computer with me today.

**Comment by Killyana** [comment]
The npc has the extraflag 2 so it will never attack
The timer is in ms so 3 must 3000
The unitflag 4 doesn't work on summoned units that follow the summoner
If you use the action SMART_ACTION_SET_ROOT instead of set_unitflag and remove the extra flag, the npc will enter in evade on aggro, as it can't reach the target.
I got a similar issue for a quest and no idea how to fix it.

**Comment by tkrokli** [comment]
New attempt based on the feedback, using `SMART_ACTION_SET_ROOT` and no flags.
```sql
-- SmartAI script for [Creature] ENTRY 2667 (name: Ward of Laze)

-- Table creature_template
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 2667;

-- Table smart_scripts
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 2667);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2667, 0, 0, 0, 54, 0, 100, 0, 0, 0, 0, 0, 103, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Ward of Laze - On Just Summoned - Smart Action Set Root On'),
(2667, 0, 1, 0, 0, 0, 100, 0, 3000, 3000, 3000, 3000, 11, 3825, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 'Ward of Laze - In Combat - Cast \'Ward of Laze Passive\'');

**Comment by tkrokli** [comment]
New attempt based on [**Core/Creature: implement INHABIT_ROOT to apply UNIT_STATE_ROOT to creature**](https://github.com/TrinityCore/TrinityCore/pull/17543) #17543 :
```sql
-- set InhabitType INHABIT_ROOT for NPC entry 2667 Ward of Laze
UPDATE `creature_template` SET `InhabitType`=`InhabitType`| 8 WHERE `entry`= 2667;
```
