### ISSUE TITLE
[3.3.5] Envenom gets dispelled by Cure toxic, or any other dispel

### ISSUE THREAD

**Issue by Quadral** [TrinityCore/TrinityCore#15321]
When rogue uses 5 combo, it gets a buff: Chance to apply Deadly Poison increased by 15% and frequency of applying Instant Poison increased by 75%.

However it can be dispelled by your own team mate such as Cure toxic or any other dispel spell.

Envenom: http://wotlk.openwow.com/spell=57993

30fc4f9+ 2015-08-17 23:27:42 +0200 (3.3.5 branch)

**Comment by MrSmite** [comment]
Well, according to [wowhead](http://www.wowhead.com/spell=32645/envenom#comments)

__dispel type: poison__

**Comment by Quadral** [comment]
You shouldn't dispel your own team mate buff; I've tested on retail and Arena tournament, and confirm you cannot dispel your team mate Envenom buff

**Comment by Killyana** [comment]
The aura is already considered as positive: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellInfo.cpp#L2425

**Comment by DevRival** [comment]
Any news?

**Comment by kvipka** [comment]
Hi guys =) 
https://github.com/healthstone/RE/commit/32de5cc5d6b4d75d19de633bfec9c112c4f23f6c

**Comment by Treeston** [comment]
Dispels shouldn't remove positive auras. Core bug.

@kvipka solution is hack.

**Comment by Quadral** [comment]
I believe this core bug could affect other abilities, since the core bug is allowing party members to dispel the users buff (which benefits them).

**Comment by kvipka** [comment]
yep, hack, but it's temporary solution
