### ISSUE TITLE
make: ***[all] Error 2

### ISSUE THREAD

**Issue by groota** [TrinityCore/TrinityCore#15331]
im on linux debian 7 wheezy, i just update all the trinitycore 
15dec9a76ca56930c6764e8483cbf4ce8aae4f90

Linking CXX static library libscripts.a 
[ 96%] Built target scripts
make: *** [all] Error 2

command cmake : cmake ../ -DCMAKE_INSTALL_PREFIX=/home/admin/serveur -DWITH_WA│
RNINGS=1

anyone have the solution for that ?
And really thx you for the help !

**Comment by dansanti** [comment]
Seems that you do not install all dependencies .

**Comment by groota** [comment]
which dependencies are you talking about ?

**Comment by dansanti** [comment]
Use it better, i think some folders is trying to install on system folder: 
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/admin/serveur -DCONF_DIR=/home/admin/serveur/etc -DLIBSDIR=/home/admin/serveur/lib -DTOOLS=1 -DWITH_WARNINGS=1

**Comment by groota** [comment]
i try that, now i have : [ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/PrecompiledHeaders/ScriptPCH.cpp.o        
Linking CXX static library libscripts.a                                                                      
[ 99%] Built target scripts                                                                                     
make: *** [all] Error 2

**Comment by Shauren** [comment]
#15333

**Comment by DDuarte** [comment]
Fixed by 595bb841a9f9b71bae0fcbcdfb0eb0c38143c7fc

**Comment by groota** [comment]
working ! nice guys ! really thx

**Comment by tkrokli** [comment]
Thank @StormBytePP in particular, he found the solution. :+1:
