### ISSUE TITLE
Core: Rest status is not being applied server-side

### ISSUE THREAD

**Issue by StormBytePP** [TrinityCore/TrinityCore#15338]
In rev 68e6c95f16dc978066bb957407a1c3bfd4cb8505 I noticed the whole rest system is broken (never applied server side) (applies also to 3.3.5)

This happens because the following if https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/Player/Player.cpp#L7358 is never true, because tested cities (stormwind and ironforge) have not AREA_FLAG_REST_ZONE_ALLIANCE, therefore server never applies PLAYER_FLAGS_RESTING.
However client is aware that is a resting area, as you can see "zzz" in character portrait

**Comment by Trisjdc** [comment]
It _definitely_ doesn't apply to 3.3.5

**Comment by StormBytePP** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L7365 it does

**Comment by Trisjdc** [comment]
AREA_FLAG_REST_ZONE_ALLIANCE/HORDE isn't used in major cities on 3.3.5, and the 'zzz' is a direct consequence of the server applying PLAYER_FLAGS_RESTING, it's not client-side

**Comment by jackpoz** [comment]
'zzz' is displayed even without the PLAYER_FLAGS_RESTING, in fact http://wowprogramming.com/docs/api/GetRestState returns 2 Normal even with 'zzz' but http://wowprogramming.com/docs/api/IsResting returns correctly 1 ( 'zzz' ) and nil (outdoor)

**Comment by StormBytePP** [comment]
I added more logs to Player.cpp
In this case: std::cout << "Player is rested: " << std::boolalpha << this->isRested() << std::endl;
And is returning false on each area change (stormwind -> outside, outside -> stormwind) so definitelly, server is not applying that flag.

**Comment by Trisjdc** [comment]
Player::isRested is dead code, see https://github.com/Trisjdc/TrinityCore/commit/42339c52c69ce797db3c58cf697e7d8fa198f2b9

**Comment by StormBytePP** [comment]
@Trisjdc in fact I tested your PR also, and the result is the same, exp bar is never turning blue, which means, no rested XP bonus applied, which, in turn means server is not handling properly rested status.

**Comment by Rochet2** [comment]
Maybe this has an affect?

> The rest bonus calculation looks really weird to me. Expecially that random 3% chance to actually get any resting bonus if you even are supposed to get any. Thats a separate issue though if even an issue.
Trisjdc@46b8df9#diff-5589ee47b3a7ad220cff105a8fe7eac3L1726
Im guessing it is either blizzlike to have random updates or then its trying to be a timer type thing to make it calculate less often.

**Comment by Trisjdc** [comment]
It's probably that formula. I might be wrong but it seems it needs 160 hours (according to the constants in https://github.com/Trisjdc/TrinityCore/blob/42339c52c69ce797db3c58cf697e7d8fa198f2b9/src/server/game/Entities/Player/Player.cpp#L1733) for a full rest bar?

**Comment by Rochet2** [comment]
What level characters are you guys testing with?
I debugged some with a level 1 character whose next level XP is 400.
This causes the extraPerSec in the formula to always be 0.0000 since the values are so small.

**Comment by StormBytePP** [comment]
Anyways, the bar exp is never blue, and that, I tested on retail, even with
a lvl char

**Comment by jackpoz** [comment]
@Trisjdc you are right, the flag is set just at another place https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L7442
> 	worldserver.exe!Object::SetFlag(unsigned short index, unsigned int newFlag)  Line 857	C++
>	worldserver.exe!Player::UpdateZone(unsigned int newZone, unsigned int newArea)  Line 7443	C++
 	worldserver.exe!Player::Update(unsigned int p_time)  Line 1767	C++
 	worldserver.exe!Map::Update(const unsigned int t_diff)  Line 680	C++

**Comment by Rochet2** [comment]
> It's probably that formula. I might be wrong but it seems it needs 160 hours for a full rest bar?

According to wow wiki that is what it needs on retail.

**Comment by jackpoz** [comment]
Ingame screenshot of a lvl 79
![rest](https://cloud.githubusercontent.com/assets/1153754/9426243/01409d94-4934-11e5-9c6f-9d15422607e8.png)

this is the code that make the You feel rested message take a lot of time for lvl 1 char:
```
if (m_rest_bonus > 10)
    SetByteValue(PLAYER_BYTES_2, 3, REST_STATE_RESTED);
else if (m_rest_bonus <= 1)
    SetByteValue(PLAYER_BYTES_2, 3, REST_STATE_NOT_RAF_LINKED);
```

The 10 limit looks kinda random, added in https://sourceforge.net/p/mangos/code/2610/#diff-2

**Comment by StormBytePP** [comment]
The thing is, that even in level low, you feel rested for the very first
time you enter a rest place. Of course if you enter little time, the next
kill will makw you unrested, but you are since the beginning

**Comment by StormBytePP** [comment]
Seems it is working good after all.
