### ISSUE TITLE
Error when compile [6.x]

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#15333]
TrinityCore revision   : 15dec9a76ca5 2015-08-22 00:33:59 +0200 (6.x branch)
When i compile, i get this error (pastbin link) at 55% (I'm under Debian 7 and i don't get any error on 3.3.5 branch): http://pastebin.com/9jFCrQVz
It's about spell.cpp, spell.h and GridNotifiers.h.

Compiler version: 4.7.2 (Pastbin link): http://pastebin.com/KgfX7Sh6

Thank you for help

**Comment by tkrokli** [comment]
Your core/source 15dec9a76c is more than 1 month old, it is recommended that you update your source first.

**Comment by martial69320** [comment]
I taken this rev code on src but i have: 3b98743dd5dfbe46f307a1a54a6cd53de2fb3d71 (from sql)

**Comment by tkrokli** [comment]
That sounds confusing, your complete source should be on the same core revision hash, both for the database (SQL) part as well as the core itself. A lot of non-SQL commits have been added since July 12.

**Comment by martial69320** [comment]
TrinityCore revision   : 15dec9a76ca5 2015-08-22 00:33:59 +0200 (6.x branch)

**Comment by tkrokli** [comment]
Sorry. I read the commit wrong. Lets just delete those comments, your commit is from today.

**Comment by Aokromes** [comment]
#15331

**Comment by DDuarte** [comment]
Closed by 595bb841a9f9b71bae0fcbcdfb0eb0c38143c7fc

**Comment by tkrokli** [comment]
@martial69320 : if you update your source now, your compile should work again. :smirk_cat:
