### ISSUE TITLE
AllowTwoSide - Channel chat language not working

### ISSUE THREAD

**Issue by Magic-WoW** [TrinityCore/TrinityCore#15337]
747ea7c

Hello. Maybe I'm wrong somehow, but I'm sure, that I didn't edit anything in chat scripts. I want to make both factions understand themselves but with this setting it works only for one side, Ally understands horde. The best thing is here that i've also learned common language - still nothing.

Can someone test it? Thank you.

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by Magic-WoW** [comment]
I test it on enabled cross-groups. Queued to a dungeon, tried 'say' and 'party'. Could you look if works in yours? :)

**Comment by Rochet2** [comment]
did you enable the permission for the players?
There is a two side chat permission in rbac.

**Comment by Magic-WoW** [comment]
Okay, I'm simply retarded. I've changed the group requirement in code (to prevent joining raids together) - and allow only dungeons via RDfinder. In Chathandler.cpp is a line that allows to chat on party only when enabled in config.

Thank you, Aokromes, Rochet :)
