### ISSUE TITLE
DB/Quest:  Vindicator Aldar

### ISSUE THREAD

**Issue by jududdar** [TrinityCore/TrinityCore#15344]
3.3.5 Branch
hash 603f49a55134
The quest "Vindicator Aldar" http://www.wowhead.com/quest=10304/vindicator-aldar is not given.

Have tried as Draenei and non-Draenei.  [Botanist Taerix] (http://www.wowhead.com/npc=16514/botanist-taerix) never gives the quest.  It has a pre-requisite of [Healing the Lake] (http://www.wowhead.com/quest=9294), which I have completed on both characters.

**Comment by Killyana** [comment]
I cannot reproduce it, the quest is given just after the event for http://www.wowhead.com/quest=9294/healing-the-lake

**Comment by jududdar** [comment]
Logged my GM character on to check my character's backlog.  GM is offered the quest, but my other character isn't.  Both characters are Night Elf Druids that haven't had any trickery done to them other than setting their level to 80 from level 1.

**Comment by Killyana** [comment]
Try with another character, for me there's no problem to get the quest.

**Comment by jududdar** [comment]
Created new character (Human Mage), summoned to Ammen Vale and did quests all the way up to this one.  Guess my other character is borked somehow.  I guess I'll remake as that character is the one I was going to use to sample every quest I could find!

**Comment by Killyana** [comment]
You cannot take a previous quest from a completed quest chain for a simple reason:
Quests are considered as chapters so if the quest chain has for example 5 quests and for a reason you missed the quest number 2, you cannot get it even if the issue is fixed as it doesn't make sens.

**Comment by jududdar** [comment]
Ah, good call.  Makes perfect sense!
