### ISSUE TITLE
3.3.5 Pet escape

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15342]
core:https://github.com/TrinityCore/TrinityCore/commit/603f49a55134de21b6c02b3cfcd9cb32b44c5f7b
DB:TDB59
update:2015_08_23_00_world.sql
not custom patch
Some of the pet will run away.
Mage's water element，Succubusand so on
Rarely occurs, generally occurs in a duel victory
Action bar still exists

http://s017.radikal.ru/i433/1508/33/db81af15d5a8.png

Please forgive me for my English.

**Comment by Aokromes** [comment]
Duplicate, but can't found original ticket.
