### ISSUE TITLE
[NPC] Guard Roberts should not be 100% health

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15355]
__Core [335]:__ https://github.com/TrinityCore/TrinityCore/commit/f2aa95c3503fe936f08d9fcc3c7f76f8bfcd8b36
__DB:__ TDB_full_335.58_2015_03_21 + updates

__Bug:__

[Guard Roberts](http://www.wowhead.com/npc=12423/guard-roberts) is part of the Priest class quest chain [Garments of the Light](http://www.wowhead.com/quest=5624/garments-of-the-light) in which he (or she depending on spawn) is supposed to be healed. Roberts is spawned at 100% health.

__Notes:__

* Roberts' flags were recently fixed with [this commit](https://github.com/TrinityCore/TrinityCore/commit/e26ddf79ce15321762bce456ad70384f9e943f7c) because of another quest issue
* Roberts used to have a green nameplate like other Stormwind guards, it is now blue.
* I didn't actually have a priest to try the quest yet so I don't know if 100% health prevents completion
* Because the quest is deprecated, wowhead links above don't directly link the NPC with the quest

**Comment by Killyana** [comment]
He must spawn with 95hp, the current hp is correct but the regenhealth is on, for the quest it works fine, and for nameplate it's blue because the UNIT_FLAG_PVP_ATTACKABLE (to make it healable)
``` sql
UPDATE `creature_template` SET `RegenHealth`=0 WHERE `entry`=12423;

**Comment by MrSmite** [comment]
> blue because the UNIT_FLAG_PVP_ATTACKABLE (to make it healable)

Ah, ok. I thought he was supposed to be green with PvP enabled like other guards.
