### ISSUE TITLE
[TDB 335.59] - Lady DeathWhisper Missing bitmask in mechanic_immune_mask.

### ISSUE THREAD

**Issue by aWeirdo** [TrinityCore/TrinityCore#15353]
Lady DeathWhisper is missing interrupt immunity.
Can be kicked by rogues, etc, to stop spell casting.
And since it is not blizz-like that raid bosses can be interrupted:

Current mechanic_immune_mask = 617299839

Added MECHANIC_INTERRUPT (BitMask of 33554432) which was missing.
http://collab.kpsn.org/display/tc/creature_template#creature_template-mechanic_immune_mask

```
UPDATE creature_template SET mechanic_immune_mask = 650854271 WHERE entry = 36855
```

Tested & Working.
https://github.com/TrinityCore/TrinityCore/commit/a9d00b9c969f2e0297bf2500fdf78bc05fe4011e TDB 335.59

**Comment by Shauren** [comment]
Absolutely not blizzlike. You are meant to interrupt the frostbolt volley in this encounter.

**Comment by ccrs** [comment]
Frost nova on phase 2 must be interrupted.

IMO everything is correct and blizzlike.

**Comment by Shauren** [comment]
@ccrs this boss doesnt have a frost nova - http://www.wowhead.com/spell=71420/frostbolt

**Comment by aWeirdo** [comment]
Well, my apologies then, i don't recall all boss fights back from WotLK  :P 

Just had a guy asking for a fix for it so i figured i might aswell make an issue here aswell.
i guess both him & me where wrong..
Good to see you guys caught it then :)

**Comment by Rushor** [comment]
@aWeirdo always ask your user on your server to give you proved from 2008 - 2010 for ANY fix. players are shit, they always want to have strange things, because they have no idea about wotlk itself.

**Comment by aWeirdo** [comment]
@Rushor 
True, it was a random dude at a forum^^.
i just figured it isn't normally possible to interrupt a boss and thought it was a bug aswell, just as much my fault for not checking up on it first.

**Comment by ccrs** [comment]
@Shauren I spelled it wrong (nova -> bolt) XD
