### ISSUE TITLE
Fly interaction

### ISSUE THREAD

**Issue by groota** [TrinityCore/TrinityCore#15358]
hi, 614b5832ba96b4c5905ece5490a7b5d18c2f710b ( last Modification )

We can't interact with the NPC fly , 
Received unhandled opcode [CMSG_CLOSE_INTERACTION 0x04E0 (1248)] from [Player: Player GUID Full: 0x08000400000000000000000000000024 Type: Player Entry: 0 Low: 36, Account: 407]

thx you !

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14216

**Comment by spuresz** [comment]
They do not deal with this, rather than to Gryphon Master Toybox
