### ISSUE TITLE
[Mage] T8/T8.5 mage 4p bonus

### ISSUE THREAD

**Issue by Bezo** [TrinityCore/TrinityCore#1536]
the bonus spell for 4 parts tier 8/8.5 set is not working. 
http://www.wowhead.com/spell=64869 <- the bonus for this set

Rev:a29044373877b5682591
TDB: 335.11.40 Unix
Addons: Anticheat2 , AHbot, TrinityChat2

**Comment by boom8866** [comment]
confirm this bug

**Comment by SinglemaltHC** [comment]
confirm this bug :(

**Comment by Bezo** [comment]
5 year later.. still bugged :/
