### ISSUE TITLE
[6.x] Worldserver crash

### ISSUE THREAD

**Issue by vvizard100** [TrinityCore/TrinityCore#15363]
http://pastebin.com/0bkiQsj8

Rev : https://github.com/TrinityCore/TrinityCore/commit/0327927fa61434d432f9749fd9242ae5dce9a5cd
DB : last available 

I don't even know when this crash occurs, so I cannot tell you how to reproduce it :/

**Comment by Shauren** [comment]
#15004

**Comment by megatronir** [comment]
we reproduced it and it's seems from map update,example he have a unit32 on source the packet of the read is bigger than he crash, so the boost is needed for the map updater when he use the function than he send things when its bigger as define will crash.
i think the update function is open delay maybe in 1 hour or 2 days and when its open than he ask about the boost and than he have worng unity for it

**Comment by megatronir** [comment]
i have reproduced it and it's seems from map update,example he have a unit32 on source the packet of the read is bigger than he crash, so the boost is needed for the map updater when he use the function than he send things when its bigger as define will crash. i think the update function is open delay maybe in 1 hour or 2 days and when its open than he ask about the boost and than he have worng unity for it
