### ISSUE TITLE
SQL characters update import error

### ISSUE THREAD

**Issue by Orfeous** [TrinityCore/TrinityCore#15368]
When i try to import 2015_07_28_00_characters.sql from updates folder i get the following error:

```# mysql -utrinity -ptrinity characters < 2015_07_28_00_characters.sql```
```ERROR 1054 (42S22) at line 1: Unknown column 'id' in 'calendar_invites'```

I use to create the full db before i tried updates: TDB_full_6.02_2015_07_14.7z
rev: f5e92f6

It doesnt really count but my core version is: 88eead2462d64e3de52eaa9a34b2198fe3e7b832

**Comment by Aokromes** [comment]
never import character updates on fresh installs
