### ISSUE TITLE
Lady Deathwhispers summons bug..

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15373]
Hello,

TrinityCore rev. f50df72 2015-08-24 14:52:18 +02000 ( 3.3.5 branch) (Win64, Release)

When lady deathwhisper summons mobs, they kill self with   spell,

;

http://www.wowhead.com/spell=70903/

and 

Transform for achievent doesnt come after 2/5 

http://www.wowhead.com/npc=38135/deformed-fanatic

Regards,

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/5549
