### ISSUE TITLE
DB/Core: Wrong models loaded

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15371]
rev. f50df7282018

Some unique npcs like ``` SELECT * FROM creature_template WHERE entry IN (22432, 12423); ``` have only one model on the DB: 3258 for 12423 and 14533 for 22432
But IG a female model can be loaded from creature_model_info
Here some examples:
www.wowhead.com/npc=22432/colonel-jules Male character
DisplayID: 14535 (Native: 14535). Female model from creature_model_info
DisplayID: 14533 (Native: 14533). Male model on creature

www.wowhead.com/npc=12423/guard-roberts Male character
DisplayID: 3257 (Native: 3257). Female model from creature_model_info
DisplayID: 3258 (Native: 3258). Male model on creature

**Comment by meji46** [comment]
I think the problem is in the field 'modelid_other_gender' from http://collab.kpsn.org/display/tc/creature_model_info

Modelid 14535 points 14533 and modelid 14533 points 14535. Maybe those values alternate the model loaded.

**Comment by Killyana** [comment]
@meji46 You're right, maybe @Kinzcool has a solution for this.

**Comment by malcrom** [comment]
Set model on spawn in scripting.
