### ISSUE TITLE
AoE spells hit unfriendly faction NPCs despite "at war" not being set

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15374]
Branch 3.3.5a, revision 3f3ff8b36b05

When a player uses an area of effect ability near an NPC that has an unfriendly standing towards them (without having "at war" selected in the reputation window), the NPC is hit by the AoE and subsequently aggros the player.

Examples include the Sporeggar faction in Zangarmarsh (which are encountered fighting hostile Bog Giants).

Intended behavior would be the player being unable to aggress unfriendly NPCs unless they have selected "at war" - these targets should be ignored by the AoE effect.

**Comment by StormBytePP** [comment]
Fixed by rev 4ada913d02bb5376914e46843873b3285116154f
