### ISSUE TITLE
Sindragosa [BUG]

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15372]
TrinityCore rev. f50df7282018 2015-08-24 14:52:18 +02000 ( 3.3.5 branch) (Win64, Release)

Hello, When you hit in non combat getting damage but when you are in combat  sindragosa is evading all damages.

is there update ? or need to wait?

Regards,

**Comment by ccrs** [comment]
it is evading because u didnt complete the required encounters.

**Comment by DearAdmin** [comment]
can you explain it to me please?

**Comment by Killyana** [comment]
The first four bosses + Valithria must be done to avoid the Anticheat.

**Comment by DearAdmin** [comment]
god it thanks guys.
