### ISSUE TITLE
[3.3.5] MindcontrolAI Controlled players do not use spells

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15379]
In boss like Lady Deathwhisper, Blood-Queen Lana´thel and all other boss who control players during the fight, should use the spells of players while they are controlled.
On TC controlled players give only melee damage and do not use spells.

Rev 5c97594a1691b78ab881437985dc5eeebb31a979

If there was another issue about it, excuse me. I could not find

**Comment by P-Kito** [comment]
Mindcontrol AI - Yep.

**Comment by Rushor** [comment]
or better CharmAI :D 

some basic stuff
https://github.com/Lillecarl/HGCore/commit/a421c5ba72e9bd57356bbd65564954024c811a72
https://github.com/Lillecarl/HGCore/blob/118e2d9f1c4b684b891de6e5674e419909334c5b/src/game/PlayerAI.cpp#L307
https://github.com/Lillecarl/HGCore/blame/118e2d9f1c4b684b891de6e5674e419909334c5b/src/game/PlayerAI.h
https://www.google.de/#q=void+MageAI::UpdateAI%28uint32+diff%29

**Comment by P-Kito** [comment]
There is a CharmAI currently in the code for creatures. Someone just needs to create some functions for the player case :D

**Comment by Rushor** [comment]
go for it @P-Kito :>

**Comment by ccrs** [comment]
not that easy, player has no AI when its mind controlled.

**Comment by P-Kito** [comment]
Because there is that in the code: (I saw it in SimpleCharmAI I think.. not sure though)
if (IsPlayer())
   return;

but if you would initialize an AI instead of a return, that would probably work.

**Comment by ccrs** [comment]
that code is not used, its just a placeholder. you need a spellscript or a core mechanic to set the AI to the player when the charm aura is applied.

**Comment by P-Kito** [comment]
Well I guess spellscript is not good, because its not generic. 

Not sure whether you should use cooldowns when mindcontrolled outside of an instance/raid.

**Comment by Treeston** [comment]
Closed by 25c5570.

**Comment by Runico** [comment]
Player under mind control aura character size should increase ?

**Comment by Keader** [comment]
Idk if is general
In lady deathwhisper and kelthuzad should.

**Comment by Treeston** [comment]
That's an attribute of the specific MC aura. #16634 fixes it for KT.

**Comment by Runico** [comment]
@Treeston, I hear mind controlled players should start casting after a few seconds not instant, is that true ?
