### ISSUE TITLE
[3.3.5] Spell Channeling spell range tolerance 

### ISSUE THREAD

**Issue by MidnaLol** [TrinityCore/TrinityCore#15375]
Branch 3.3.5a, revision dd90e51028b92cfe65abef72f599f32bc896a810
Possibly 6.x branch too (not tested). Same mechanic should apply

When channeling a spell. for example: Mind Flay
The target should be allowed to go beyond the max casting range of mind flay.

There should be a certain range tolerance before interrupting the spell.
While this is an easy fix as the pastebin below suggests, I don't know the correct number this tolerance should be.

A possible fix would be:
http://pastebin.com/deKkBi2x

**Comment by P-Kito** [comment]
It's not only for channels.

Start casting for example a frostbolt. Then your targets runs slightly out of range of the frostbolt spell you still be able to cast it successfully.

**Comment by Ramonoo** [comment]
You are correct, it is most likely related to each other.

**Comment by Rushor** [comment]
@Ramonoo: your pastebin das been removed - pls include the plaindiff in this issue

**Comment by Ramonoo** [comment]
http://pastebin.com/ngyxhDdW

**Comment by Ramonoo** [comment]
```
         range = m_spellInfo->GetMaxRange(m_spellInfo->IsPositive());
         if (Player* modOwner = m_caster->GetSpellModOwner())
             modOwner->ApplySpellMod(m_spellInfo->Id, SPELLMOD_RANGE, range, this);
+
+        // Blizzard adds some extra range after channeling start. need exact numbers on this
+        range *= 1.25f;
     }
 
     for (std::list<TargetInfo>::iterator ihit= m_UniqueTargetInfo.begin(); ihit != m_UniqueTargetInfo.end(); ++ihit)
```

**Comment by Aokromes** [comment]
If this fix is valid, plz open a pr for it.

**Comment by Keader** [comment]
Please test #18969

**Comment by Aokromes** [comment]
66dc97bb27382f3c0935ed6ca1abe91ceba6058d
