### ISSUE TITLE
Cannot start server.

### ISSUE THREAD

**Issue by Flameshot** [TrinityCore/TrinityCore#15383]
Hi. I am using Microsoft Visual 2015 , Boost 1.59 and when I want to open worldserver.exe it says that it need libzmq. I have installed ZeroMQ but they don't have the dll version for Microsoft Visual 2015. Any ideas?

Rev: https://github.com/TrinityCore/TrinityCore/commit/b0107802064a19d69ce06f7bcf8b8394695e6faf

**Comment by DDuarte** [comment]
What's the value of ZMQ_LIBRARY in Cmake?

**Comment by Flameshot** [comment]
libzmq-v120-mt-gd-4_0_4.lib . I tried to copy the v120.dll but i get other errors.

**Comment by DDuarte** [comment]
You need libzmq-v120-mt-gd-4_0_4.dll next to worldserver.exe

**Comment by Flameshot** [comment]
Next error: MSVCR120D.dll is missing...

**Comment by DDuarte** [comment]
http://stackoverflow.com/a/23114642/2297501

**Comment by Flameshot** [comment]
I have that redistributable packages I repaired them , still not working.

**Comment by Aokromes** [comment]
This is not a forum, also redists don't ships debuf files.

**Comment by svenstero** [comment]
same problem to me,when i start bnetserver it gives me same error.where i can set the dll location ? it is on cmake files or cpp  ?
