### ISSUE TITLE
Yogg Saron phase 3 transformation is not happening

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15381]
Yogg Saron phase 3 transformation is not happening, he just disappears after his brain damaged below 30% and become not  targetable. Adds were still spawning BTW.
There's no Warning P3, phase 3 texts appearing on screen.

BTW Sara is dead.
![Uploading sara_dead.jpg…]()

Revision: 4ada913d02bb5376914e46843873b3285116154f + applied Thorim fight pull request https://github.com/TrinityCore/TrinityCore/pull/15008.

**Comment by Keader** [comment]
Fxied by: https://github.com/TrinityCore/TrinityCore/commit/2b21fbb58e6b213cf26706dd0dd368b2ea4a92b3

**Comment by digz6666** [comment]
yes, it fixed. TY!
