### ISSUE TITLE
[3.3.5] Killing Freya doesn't make her image appear in Yogg Saron's chamber

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15380]
Killing Freya doesn't make her image appear in Yogg Saron's chamber.

Revision: 4ada913d02bb5376914e46843873b3285116154f

**Comment by joschiwald** [comment]
i guess it's a problem with grid unload
try to kill freya at the entrance to the conservatory of life

**Comment by Keader** [comment]
Here works correctly.

**Comment by digz6666** [comment]
seems like works sometimes, I used die command and it worked, i saw several cases where she died but the image of freya never appear on yogg saron chamber

**Comment by Frytiks** [comment]
Confirmed.

**Comment by Killyana** [comment]
Btw the unload grid after Freya death will keep the encounter active and players cannot enter the instance until you respawn and kill Freya a second time.

**Comment by Aokromes** [comment]
In fact, if you wait 30m or something like that you can re-enter bugged instances.

**Comment by Killyana** [comment]
If I'm not wrong After 30 min there's something like a grid reset for the hole instance if no one is inside.

**Comment by Keader** [comment]
Any news about https://github.com/TrinityCore/TrinityCore/issues/15380#issuecomment-137145438 ?

**Comment by Treeston** [comment]
Can we get verification if this still happens after 1cc0458?

**Comment by Aokromes** [comment]
over 3 months after confirmation requested, if this bug is still valid open a ticket with one updated core.
