### ISSUE TITLE
This instance is locked. [BUG]

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15387]
Hello,

rev : f50df7282018+

when I try to enter trial of crusader without gm tag

isntance says : This isntance is locked.

is there way to fix it?.

Regards,

**Comment by Aokromes** [comment]
Not a bug it's locked because it's broken.

**Comment by DearAdmin** [comment]
in next update it will be fixed or?

**Comment by Aokromes** [comment]
You can test https://github.com/TrinityCore/TrinityCore/pull/14938 but it's unfinished.

**Comment by DearAdmin** [comment]
Thank you @Aokromes , Will try! hope you can work on toc for next update!

Regards,
