### ISSUE TITLE
[3.3.5a] Quest: The Art of Persuasion

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15394]
3.3.5a branch, rev 3f3ff8b36b05, TDB 335.59

Ref: http://www.wowhead.com/quest=11648/the-art-of-persuasion
Quest credit is not received after using the needler 5 times (as intended), but only after the 7th use. In addition, the imprisoned Beryl Sorcerer stops responding to further shocks after the 7th. On retail, he keeps responding with one of three quotes - the already-existing quotes for 6th and 7th shocks, in addition to "Enough! I've told you all that I know. Your continued abuse is senseless!".

**Comment by Killyana** [comment]
The npc reset the script after 2 or 3 minutes? it looks fine for me.
For the credit_quest, this line must be moved to case 5 https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/Northrend/zone_borean_tundra.cpp#L1659
``` cpp caster->KilledMonsterCredit(NPC_IMPRISONED_BERYL_SORCERER);

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/13e509a622a6d88afe27d6cdda4cf9f402818745
