### ISSUE TITLE
[3.3.5a][6.x] Gossip taxi not working from middle floor of Wyrmrest Temple

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15398]
Branch 3.3.5a, revision 0cdf3b7a73d8, TDB 335.59

Both Taxi gossip options from Lord Afrasastrasz in the middle floor of Wyrmrest Temple print "You are too far away from the taxi stand" instead of transporting you to the ground/top of the temple, respectively.

**Comment by Rexidia** [comment]
It seems to work for me, you just have to stand behind him. Try this to see if it works for you.

**Comment by Killyana** [comment]
Yes if you stand behind the npc you can take the fly
The question is: the position of "taxi stand" is somewhere on the DB or taken directly from DBC?

**Comment by Trisjdc** [comment]
It's distance from the first WP point, iirc. I don't think there should be even such a short distance check to begin with. It should be either be removed or massively increased. I recall a Coldarra quest with a taxi spell that occasionally breaks because of the same problem.

**Comment by tkrokli** [comment]
Oh. You mean like in Quest 11969 "Springing the Trap", issue #5137 ?

**Comment by tkrokli** [comment]
Confirmed that this issue still exists on commit cc685ac when making PR #15966 .

**Comment by Staleness89** [comment]
Assuming this code in Player.cpp is related?
```C++
    // check node starting pos data set case if provided
    if (node->x != 0.0f || node->y != 0.0f || node->z != 0.0f)
    {
        if (node->map_id != GetMapId() || !IsInDist(node->x, node->y, node->z, 2 * INTERACTION_DISTANCE))
        {
            GetSession()->SendActivateTaxiReply(ERR_TAXITOOFARAWAY);
            return false;
        }
    }
```
