### ISSUE TITLE
Shamans can´t equip mail 

### ISSUE THREAD

**Issue by tctwod** [TrinityCore/TrinityCore#15391]
rev: 7b5e7e08981838c06db08812c7ab6261e146ecd1

shamans can´t equip any mail at level 40-100 but have the spell learned

i think it´s a spell issue on database

if you use .unlearn 8737  on your shaman and then use .learn 8737  you can equip the mail :D

**Comment by StormBytePP** [comment]
Furthermore, iirc, Shamans can equip mail at lvl 1 with no extra learning in 6.x

**Comment by thomas33** [comment]
`` DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=8737 AND `spell_effect`=119811;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
('8737', '119811', '0', 'Mail'); `` but i think it's hack

**Comment by dejonxavier** [comment]
doesn't fix mail issue:

http://prntscr.com/8lekzj
