### ISSUE TITLE
[3.3.5a] Utgarde Keep: Ingvar the Plunderer - Smash / Dark Smash

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15393]
Branch 3.3.5a, Revision 0cdf3b7a73d8, TDB 335.59

While testing the "Ingvar the Plunderer" encounter in Utgarde Keep, I encountered two issues related to the behavior of his Smash/Dark Smash abilities:
*Reference: http://www.wowhead.com/npc=23954/ingvar-the-plunderer#comments*

**1)** When casting "Smash" (during phase 1) and "Dark Smash" (during phase 2), the damage cone is projected in the direction of its target's current position when the cast finishes. Expected behavior would be to have it project in the direction of its target's position when the cast starts. This means dodging the ability is impossible for the tank, and attempting to do so will likely make the boss smack your party instead.
**2)** If Ingvar is not moved between casts of "Smash" (phase 1) or "Dark Smash" (phase 2), he will face the direction he was facing during the previous cast, even if his target is no longer positioned in that direction. This makes the visual facing of the model inconsistent with the direction of the damage cone.

**Reproduction steps for issue 1:**
1a) Engage Ingvar
1b) Tank Ingvar until he begins channeling Smash/Dark Smash
1c) Run through Ingvar
1d) The damage cone will be projected towards you, hitting you and anyone standing near/behind you. Expected behavior would be the damage cone being projected towards where you were when Ingvar started casting.

**Reproduction steps for issue 2:**
2a) Engage Ingvar
2b) Tank Ingvar until he begins channeling Smash/Dark Smash once. Ensure you are in melee range of Ingvar so he does not move.
2c) Run through Ingvar so he turns to face you. Remain in melee range of him so he does not move.
2d) The next time Ingvar begins channeling Smash/Dark Smash, he will visually turn away from you (towards the position you were in for step 2b) throughout the channel. Expected behavior would be Ingvar channeling in your direction.

**In addition, a minor (what I believe to be) issue, but I cannot present any non-anecdotal evidence for this:**
3) In my recollection of Retail behavior, Ingvar would always cast a spell (not sure which one, either roar or smash) right after resurrecting for phase two.

**And a minor visual thing:**
4) Ingvar displays the level-up animation when transitioning to phase two on heroic. Not sure how we could suppress this, as P1 Ingvar is a level 81, and P2 Ingvar is a level 82, which will always (?) trigger a level up animation when the client receives a changed level for the guid.

**Comment by joschiwald** [comment]
about smash: duplicate

**Comment by tkrokli** [comment]
#10803 (smash & dark smash)

**Comment by Treeston** [comment]
Above issue indicates the issue is supposedly resolved, yet it's still occurring as of 0cdf3b7a73d8.

**Comment by tkrokli** [comment]
Well, I guess that is sort of why joschiwald reopened it, even though a reopen comment is missing.

**Comment by Aokromes** [comment]
So closing as duplicated.

**Comment by Treeston** [comment]
f481ae1048aac32ba3a40491f0304d0317234295
