### ISSUE TITLE
[3.3.5][6.x] Script/NPC: Gortok Palehoof encounter at Utgarde Pinnacle

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15405]
Gortok Palehoof and the four adds when they enter in combat, they remain rooted in their position even if their target is out of their melee range of attack, they just can change orientation.
Also sometimes the red orb used to wake up this npcs skips 3, 2 or 1 npc and go directly to Gortok Palehoof.
http://www.wowhead.com/npc=26687/gortok-palehoof
http://www.wowhead.com/npc=26683/frenzied-worgen
http://www.wowhead.com/npc=26684/ravenous-furbolg
http://www.wowhead.com/npc=26685/massive-jormungar
http://www.wowhead.com/npc=26686/ferocious-rhino
http://fr.wowhead.com/npc=26688/statis-orb
https://github.com/TrinityCore/TrinityCore/blob/d7c53c30fb45f6da015e126aeb8a4a1901f72e58/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp#L715
rev. f50df7282018

**Comment by lost-illusion** [comment]
Change 
nextBoss->Attack(nextBoss->SelectNearestTarget(100), true);
to
Unit* target = nextBoss->SelectNearestTarget(100);
nextBoss->Attack(target, true);
nextBoss->GetMotionMaster()->MoveChase(target);

@Killyana @Rushor

**Comment by Rushor** [comment]
could you open up a pr for this @lost-illusion

**Comment by Keader** [comment]
Move chase is not active by "default"? when creature start attack?

**Comment by lost-illusion** [comment]
No. I have no time for full research. But i think this happened because void AttackStart(Unit* who) override with flag check. But i don't know real problem.

Manual MoveChase work 100%

**Comment by Keader** [comment]
Test it:

```diff
diff --git a/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp b/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
index 3dec0c6..1b69431 100644
--- a/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
+++ b/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
@@ -784,7 +784,7 @@ public:
                     nextBoss->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_ATTACKABLE_1 | UNIT_FLAG_IMMUNE_TO_PC);
                     nextBoss->SetStandState(UNIT_STAND_STATE_STAND);
                     nextBoss->SetInCombatWithZone();
-                    nextBoss->Attack(nextBoss->SelectNearestTarget(100), true);
+                    nextBoss->AI()->AttackStart(nextBoss->SelectNearestTarget(100.0f));
                 }
                 currentPhase = PHASE_NONE;
 
```

**Comment by Keader** [comment]
not totally fixed yet

**Comment by Rushor** [comment]
the visual spell is missing no?

**Comment by Keader** [comment]
> Also sometimes the red orb used to wake up this npcs skips 3, 2 or 1 npc and go directly to Gortok Palehoof.

Weird behavior with un-started enum xd

```
diff --git a/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp b/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
index 808fcf1..34dde46 100644
--- a/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
+++ b/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp
@@ -70,7 +70,7 @@ Position const moveLocs[] =
 
 enum Phase
 {
-    PHASE_FRENZIED_WORGEN,
+    PHASE_FRENZIED_WORGEN = 0,
     PHASE_RAVENOUS_FURLBORG,
     PHASE_MASSIVE_JORMUNGAR,
     PHASE_FEROCIOUS_RHINO,
@@ -80,7 +80,7 @@ enum Phase
 
 enum Misc
 {
-    ACTION_NEXT_PHASE,
+    ACTION_NEXT_PHASE = 0
 };
 
 class boss_palehoof : public CreatureScript
```

@Rushor what visual spell? '-'

**Comment by Rushor** [comment]
nvm i thought about a different issue xd

**Comment by Keader** [comment]
This script is ugly, i will try rewrite it btw xd

**Comment by Keader** [comment]
More issues:

- Missing heroic spells

-  Missing handle heroic spells

- Orb creature used in script dont belong to this fight

- Wrong waypoints for orbs
