### ISSUE TITLE
DB: Duplicate spawn for 27122 (Overseer Deathgaze)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15404]
Creature 27122 (quest unique spawn) has two spawns located directly next to each other as of TDB 335.59.

GUID 52290 appears to be the correct spawn, with GUID 118724 being the duplicate - however there are some other differences in the two entries that don't quite make sense to me, so I'm not comfortable with fixing this myself.

**Comment by Treeston** [comment]
Issue comment added - github's shift-enter caught me off guard. Apologies.

**Comment by Killyana** [comment]
Spawns in this area are awful.
``` sql
DELETE FROM `creature` WHERE `guid`= 118724;

**Comment by DDuarte** [comment]
@Killyana: that one has 1 in equipment_id, no issues with that?

**Comment by Killyana** [comment]
equipment_id= 0, 1 or -1 doesn't have any effect, the npc is always equipped.

**Comment by DDuarte** [comment]
Alright, so...

```sql
DELETE FROM `creature` WHERE `guid`=118724 AND `id`=27122;
```

Better be more careful when deleting spawns. Some have been deleted by mistake on 4.3.4 and 6.x
