### ISSUE TITLE
Core/npc: Trigger invisibility

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15416]
For almost all triggers using "flags_extra", modelid1=1126 and modelid2=11686, this will make them visible only for GMs (infernal model: 1126)
But for cataclysm, mop and wod there's many triggers with modelid1=11686 and modelid2=1126, this npcs with flags_extra=128 are visible to players and invisible to GMs, changing model1 to model2 and model2 to model1 fix the issue but I'm not sure if it's the correct way to do it.

This also affect 335, example npc=20978

rev. f50df7282018

**Comment by malcrom** [comment]
the model order has to be right for tiggers.

**Comment by Aokromes** [comment]
Blame blizzard, the model order is correct :/

**Comment by Pitcrawler** [comment]
It is wrong that trigger npcs are invisible to players on TC. If you look at sniffs those npcs occur in update packets. This currently is wrong. 
modelid 1126 is an invisible npc. So I suggest to change core handling of flags_extra 128 to display modelid 1126 to player chars and modelid 11686 to GM chars. I suppose this is Blizz's intention.
This would also fix those visuals that some triggers cast on other npcs like chain spells. Currently these spells are invisible, too.

**Comment by Aokromes** [comment]
f727952
