### ISSUE TITLE
[3.3.5a]The Crone doesn't become attackable during the Opera Event

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#15426]
Revision: 2bcd9c543f1f

After killing Roar, Dorothee, Tinhead, Strawman and Tito, The Crone correctly spawns, but does not become attackable. You drop combat, and if you teleport out of the instance and come back you can start up another event. The Crone will still be present during the new encounter.

**Comment by Treeston** [comment]
Hack-fixing this should be as simple as adding
`pCrone->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NON_ATTACKABLE)`
to [bosses_opera line 107](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp#L107).

Proper fix for this encounter would...be needed. It's a mess of hacks at first glance.

**Comment by Saben65** [comment]
Same issue after f6f8fcfddd.

**Comment by Treeston** [comment]
Should be (hack-)fixed by dc39de0. The encounter needs a rewrite pretty badly though, script is full of hacks.

Please report back if that fixes it.

**Comment by Saben65** [comment]
You are now able to complete the encounter with your hackfix.

**Comment by Treeston** [comment]
Alright, closing this one, then.
