### ISSUE TITLE
[3.3.5a] Air Stands Still [quest]

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15425]
Quest: http://www.wowhead.com/quest=13125/the-air-stands-still
Killing Underking Talonox doesn't give kill credit, thus not completing the quest.

![q](https://cloud.githubusercontent.com/assets/1736110/9674668/926ba5ac-52ee-11e5-805f-89bb44f0a2cd.jpg)

Revision: 821b5f2b5c17a3582e23ba22b2e7cf17e063d709

**Comment by Killyana** [comment]
I cannot reproduce it, maybe it's related to the pet.
``` sql
SELECT RequiredNpcOrGo2 FROM quest_template WHERE id=13125;

**Comment by digz6666** [comment]
@Killyana returns 30830

**Comment by tkrokli** [comment]
Underking Talonox: http://www.wowhead.com/npc=30830/underking-talonox

Just tested this quest with a random mage I leveled up to 80 and put into level 70 T6 armor set to get decent HP. When reading the posts above, I thought perhaps it could have something to do with the quest item http://www.wowhead.com/item=43206/war-horn-of-acherus (use: calls forth a knight of the Ebon Blade, http://www.wowhead.com/spell=57906/war-horn-of-acherus), but I didn't have to use it as long as I just spammed Argent Cannon Assault to decimate the hp of Talonox fast enough to survive myself. I should probably try it again, just to see if there is any difference when using the quest item or kiting Underking Talonox to drag it out some more.

**Comment by Nyeriah** [comment]
Yeah it's because of pets and the npc that assists you. You need to deal a X percentage of health in order to be eligible to kills (I don't remember how much it was right now)

**Comment by Killyana** [comment]
@Nyeriah I was always wondering if this behavior is Blizzlike?

**Comment by Nyeriah** [comment]
Yes, but I don't think the values we follow are correct. Retail seems to require way less damage in order to get credit. Haven't done any deep research on it, however.

**Comment by ccrs** [comment]
I think its the credit. If im right, its only given to current target. So to get credit player only has to taunt just when the elite is about to die. Cant test it right now though

**Comment by Nyeriah** [comment]
It's weird because according to this https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L725 pet damage should also lower the required damage to get credit from something

**Comment by digz6666** [comment]
Should be fixed by this: https://github.com/TrinityCore/TrinityCore/pull/15473
