### ISSUE TITLE
[3.3.5/Spell/DK] Acclimation dont work on Holy Resistence

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15436]
Talent : http://wotlk.openwow.com/spell=50152

The talent is working perfectly for schools: Arcane, Fire, Frost, Nature, Shadow. However the resistance to Holy does not. Although the aura appears, the damage remains at 100% with no reduction.

Holy Resist Aura:http://wotlk.openwow.com/spell=50490

Vid: https://youtu.be/PpCxxHHdmHk

TC Hash: 494007210202124c51cce3a59f7ecee569ce24be

**Comment by Tomatodev** [comment]
http://www.arenajunkies.com/topic/46046-acclamation-question/
Seems to be working as intended, because there's no such thing as holy resist.

The bug would be the aura appearing in the first place
