### ISSUE TITLE
[3.3.5a] Infiltrating Dragonmaw Fortress: NPCs count twice for killcount

### ISSUE THREAD

**Issue by Volescue** [TrinityCore/TrinityCore#15432]
Revision: 2bcd9c543f1f
DB: TDB 335.59

http://www.wowhead.com/quest=10836/infiltrating-dragonmaw-fortress

NPCs will count twice for the kill count. There appears to be no difference between this quest and other kill quests (I compared to http://www.wowhead.com/quest=10703/put-on-yer-kneepads).

NPCs that count for 2 kills (possibly more)
http://www.wowhead.com/npc=21717/dragonmaw-wrangler
http://www.wowhead.com/npc=21718/dragonmaw-subjugator

Creature listed in `quest_template` `RequiredNpcOrGo1`
http://www.wowhead.com/npc=22197/dragonmaw-orc

**Comment by Killyana** [comment]
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=21719 AND `source_type`=0 AND `id`=15;
DELETE FROM `smart_scripts` WHERE `entryorguid`=21720 AND `source_type`=0 AND `id`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=21717 AND `source_type`=0 AND `id`=3;
DELETE FROM `smart_scripts` WHERE `entryorguid`=21718 AND `source_type`=0 AND `id`=13;
DELETE FROM `smart_scripts` WHERE `entryorguid`=22331 AND `source_type`=0 AND `id`=20;

**Comment by Volescue** [comment]
All the mobs in the area now properly count as 1 kill count. Thanks!
