### ISSUE TITLE
[3.3.5a] Unable to mount while affected by Lok'lira's Bargain (SoH chain)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15448]
Branch 3.3.5, Rev 3f3ff8b36b05, TDB 335.59

You are unable to mount while under the disguise aura [Lok'lira's Bargain](http://www.wowhead.com/spell=55012/lokliras-bargain). Error provided is "you are in shapeshift form".

Expected behavior is being able to mount and, from memory, having your mount transformed into a proto-drake.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/12042
