### ISSUE TITLE
Quest: Threat from Above gives double credit for kills

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#15457]
TDB 335.59
Rev: 2bcd9c543f1f8866a2af5a5a68de3688afb3afc7

Proposed change.

```SQL
DELETE FROM `smart_scripts` WHERE  `entryorguid`=22143 AND `source_type`=0 AND `id`=4;
DELETE FROM `smart_scripts` WHERE  `entryorguid`=22144 AND `source_type`=0 AND `id`=4;
DELETE FROM `smart_scripts` WHERE  `entryorguid`=22148 AND `source_type`=0 AND `id`=2;
DELETE FROM `smart_scripts` WHERE  `entryorguid`=23022 AND `source_type`=0 AND `id`=12;
```

**Comment by MrSmite** [comment]
Question: 22143, id 4 is *On Just Died - Quest Credit 'Threat from Above' (No Repeat)*, wouldn't deleting this cause no quest credit at all?

**Comment by Killyana** [comment]
Credit_kill is set on creature_template:
``` sql
SELECT KillCredit1 FROM creature_template  WHERE Entry IN (22143, 22144, 22148, 23022);

**Comment by MrSmite** [comment]
> Credit_kill is set on creature_template:

Right but according to the wiki:

*If more than two creatures can be killed and count toward a single objective, an EAI or C++ script will be required.*

Since there are 4 mobs that count for this quest, you need the records in *smart_scripts*, no?

**Comment by Saben65** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15432 

Whichever is the correct solution applies there as well.

**Comment by MrSmite** [comment]
> Whichever is the correct solution applies there as well.

Well, sometimes I misread the wiki. @Killyana will set me straight ;)

**Comment by Shauren** [comment]
@MrSmite that wiki entry sounds really old, at some point KillCredit fields did not exist.
Wiki info should be extended to mention no need for script if KillCredit has proper data (and since it is a WDB field it must not be modified)

**Comment by MrSmite** [comment]
@Shauren, thanks for the additional info. But yes, I've run into a few wiki entries lately that don't match the DB.

For reference, this is the wiki entry I was referring to which is the only live entry I know of:

http://collab.kpsn.org/display/tc/creature_template#creature_template-KillCredit1

**Comment by Shauren** [comment]
@MrSmite well, to be honest this time its not wiki falling behind, it is just poorly worded.
The situation described there is this one
NPC_A - entry = 1, KillCredit[0] = 2, KillCredit[1] = 3
QUEST_A - requires 5 kills of entry 1 (will count automatically)
QUEST_B - requires 5 kills of entry 2 (will count automatically)
QUEST_C - requires 5 kills of entry 3 (will count automatically)
QUEST_D - requires 5 kills of entry 4 but killing NPC_A should also count (this one will need script)
