### ISSUE TITLE
Core/GameObject: Large GOs and gossip availability

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15453]
3.3.5a Branch, revision 3f3ff8b36b05, TDB 335.59

For very large GOs, the radius at which the cursor indicates dialog availability (quest icon turning yellow) is vastly different from the radius at which the GO can actually be interacted with. Notable examples I came across include Hodir's Horn in Dun Niffelem (entry 192078) and the Zim'Rhuk shrine in Zuldrak (entry 190657). For the latter example, this outright prevents the quest in question from being completed - I could not find any spot on the outside of the GO's model that would allow interaction.

**Comment by Rushor** [comment]
```diff
float GameObject::GetInteractionDistance()
{
    switch (GetGoType())
    {
        /// @todo find out how the client calculates the maximal usage distance to spellless working
        // gameobjects like guildbanks and mailboxes - 10.0 is a just an abitrary choosen number
        case GAMEOBJECT_TYPE_GUILD_BANK:
        case GAMEOBJECT_TYPE_MAILBOX:
            return 10.0f;
        case GAMEOBJECT_TYPE_FISHINGHOLE:
        case GAMEOBJECT_TYPE_FISHINGNODE:
            return 20.0f + CONTACT_DISTANCE; // max spell range
            // (custom) fix problems with big GOs, like Hodir's Helm
        case GAMEOBJECT_TYPE_QUESTGIVER:
            return INTERACTION_DISTANCE + GetFloatValue(OBJECT_FIELD_SCALE_X) + (GetEntry() == 190657 ? 40.0f : 0.0f); // Special Handling for Zim'Torga
        default:
            return INTERACTION_DISTANCE;
    }
}
```

**Comment by tkrokli** [comment]
```cpp above the code to see code syntax highlighting (just a suggestion).

**Comment by Treeston** [comment]
Feels like a hack, to be honest.

**Comment by Rushor** [comment]
that's right.

**Comment by dobrMAN** [comment]
It is only for questgiver GO's, but chest GO like 188462 [Anub'et'kan's Carapace] did not work.
May by rewrite WorldObject::GetObjectSize() like:
`float WorldObject::GetObjectSize() const
{
    return (m_valuesCount > UNIT_FIELD_COMBATREACH) ? m_floatValues[UNIT_FIELD_COMBATREACH] : m_floatValues[OBJECT_FIELD_SCALE_X];
}`?

**Comment by dobrMAN** [comment]
I fix it by add objects scale in distance calculation:
in file server\game\Entities\GameObject\GameObject.h i change overriding function _IsWithinDist
```cpp
        bool _IsWithinDist(WorldObject const* obj, float dist2compare, bool /*is3D*/) const override
        {
            //! Following check does check 3d distance
            float sizefactor = GetObjectSize() + obj->GetObjectSize();
            float maxdist = dist2compare + sizefactor;
            return IsInRange(obj->GetPositionX(), obj->GetPositionY(), obj->GetPositionZ(), maxdist);
        }
```
in file server\game\Entities\Object\Object.cpp replace default distance to object scale:
```cpp
float WorldObject::GetObjectSize() const
{
    return (m_valuesCount > UNIT_FIELD_COMBATREACH) ? m_floatValues[UNIT_FIELD_COMBATREACH] : m_floatValues[OBJECT_FIELD_SCALE_X];
}
```
I don't know is it right, but it work. May be any body discuse this changes?
P.S.: Sorry for my English, it`s not my favorite language.

**Comment by Trisjdc** [comment]
Even better would be to dig into the client formula for interaction distance. WTB some reverse-engineering capabilities.

**Comment by Rushor** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/12539

**Comment by Treeston** [comment]
how is it related @Rushor

**Comment by Rushor** [comment]
both have problems with the interaction distance

**Comment by tkrokli** [comment]
TrinityCore rev. 70b3373da1d0 2016-08-10 18:11:36 +0200 (3.3.5 branch) (Win64, Release, Static)

Still only possible to reach the Zim'Rhuk GO from the back of the surrounding object, but it works from there. I had to sneak around the corner and stand on the back ledger to get close enough to the interactive GO to get a gossip and complete the first quest to deliver 10x Drakkari Offerings via the gossip dialog.

It is possible to reach the inner GO from behind or from the side, as long as the players squeeze their characters close enough to the wall of the outer GO. If this had been working as intended, it would be possible to reach the inner GO from all sides and from melee attack distance.

**Comment by Treeston** [comment]
We still need to figure out how the client determines interaction distance.

@Shauren is there anything you can give us that can be gleaned from decompiled client?

**Comment by dobrMAN** [comment]
In current Trinity revision used hack too. I think my hack is closer to the real thing and a lot of working capacity.

**Comment by ariel-** [comment]
d03e97d53f8dcabe006773d3377842bc091359a9 is the result of my investigations on IDA, sadly I can't make sense of the gameobject code

**Comment by ariel-** [comment]
GameObject::IsInRange uses model info bounds to check distance, instead of straight center to object distance, this certainly allows for more leeway and could be a good way of solving this issue.

**Comment by sirikfoll** [comment]
I am using this as a workaround, seems to work well for both cases, GameObjects too big or too small.
```diff
diff --git a/src/server/game/Entities/GameObject/GameObject.h b/src/server/game/Entities/GameObject/GameObject.h
index 784af8fda2..74642f6246 100644
--- a/src/server/game/Entities/GameObject/GameObject.h
+++ b/src/server/game/Entities/GameObject/GameObject.h
@@ -344,6 +344,7 @@ class TC_GAME_API GameObject : public WorldObject, public GridObject<GameObject>
         bool _IsWithinDist(WorldObject const* obj, float dist2compare, bool /*is3D*/, bool /*incOwnRadius*/, bool /*incTargetRadius*/) const override
         {
             //! Following check does check 3d distance
+            dist2compare += GetCombatReach();
             return IsInRange(obj->GetPositionX(), obj->GetPositionY(), obj->GetPositionZ(), dist2compare);
         }
         GameObjectAI* m_AI;

diff --git a/src/server/game/Entities/GameObject/GameObject.cpp b/src/server/game/Entities/GameObject/GameObject.cpp
index ce9658ef37..1ebabb9191 100644
--- a/src/server/game/Entities/GameObject/GameObject.cpp
+++ b/src/server/game/Entities/GameObject/GameObject.cpp
@@ -1992,11 +1992,13 @@ bool GameObject::IsInRange(float x, float y, float z, float radius) const
 
     float sinB = dx / dist;
     float cosB = dy / dist;
+    float scale = GetFloatValue(OBJECT_FIELD_SCALE_X);
     dx = dist * (cosA * cosB + sinA * sinB);
     dy = dist * (cosA * sinB - sinA * cosB);
-    return dx < info->maxX + radius && dx > info->minX - radius
-        && dy < info->maxY + radius && dy > info->minY - radius
-        && dz < info->maxZ + radius && dz > info->minZ - radius;
+
+    return dx < (info->maxX * scale) + radius && dx >(info->minX * scale) - radius
+        && dy < (info->maxY * scale) + radius && dy >(info->minY * scale) - radius
+        && dz < (info->maxZ * scale) + radius && dz >(info->minZ * scale) - radius;
 }
 
 void GameObject::EventInform(uint32 eventId, WorldObject* invoker /*= nullptr*/)

**Comment by Warpten** [comment]
From 4.3.4

```c++
CGUnit_C *__cdecl CGGameUI::SetInteractTarget(WGUID *a3)
{
  double v1; // st7
  bool v2; // bl
  CGUnit_C *result; // eax
  DWORD v4; // esi
  CGUnit_C *v5; // esi
  unsigned int v6; // eax
  float v7; // xmm0_4

  v2 = *a3 == CGGameUI::m_interactTarget.m_qword;
  if ( CGGameUI::m_interactTarget.m_qword && !v2 )
    CGGameUI::ClearInteractTarget(&CGGameUI::m_interactTarget, *a3 != 0i64);
  result = (CGUnit_C *)a3->_2.Low;
  CGGameUI::m_interactTarget._2.Low = (DWORD)result;
  v4 = a3->_2.High;
  CGGameUI::m_interactTarget._2.High = v4;
  if ( v4 | (unsigned int)result )
  {
    result = (CGUnit_C *)ClntObjMgrObjectPtr(
                           (WGUID)__PAIR__(v4, (unsigned int)result),
                           TYPEMASK_OBJECT,
                           ".\\GameUI.cpp",
                           12360);
    v5 = result;
    if ( result )
    {
      v6 = (signed __int16)result->_.m_descriptors->OBJECT_FIELD_TYPE.m_objectType;
      if ( (v6 >> 3) & 1 )
      {
        result = (CGUnit_C *)(v6 >> 4);
        if ( (unsigned __int8)result & 1 )
        {
          CGGameUI::m_interactMaxDistSq = flt_D0BCA0;
        }
        else
        {
          v7 = v5->m_descriptors->UNIT_FIELD_COMBATREACH + 4.0;
          CGGameUI::m_interactMaxDistSq = v7 * v7;
          if ( !v2 )
          {
            CGUnit_C::PlayNPCSound(v5, 1);
            result = (CGUnit_C *)CGUnit_C::UpdateEmote(v5);
          }
        }
      }
      else
      {
        result = (CGUnit_C *)(v6 >> 5);
        if ( (unsigned __int8)result & 1 )
        {
          CGGameObject_C::StartInteraction((CGGameObject_C *)v5);
          result = (CGUnit_C *)CGGameObject_C::GetInteractDistanceSquared((CGGameObject_C *)v5);
          CGGameUI::m_interactMaxDistSq = v1;
        }
      }
    }
  }
  return result;
}
```

**Comment by sandwm** [comment]
For what it's worth, I can confirm sirikfoll's patch improving the situation with patched TrinityCore from 2018-02-20 (for details see #21465). The remaining cases of having to find the right place to stand seem to come from WoW itself (like [this quest](http://www.wowhead.com/quest=12569/crocolisk-mastery-the-ambush#comments)).

**Comment by illfated** [comment]
Minor info update regarding the original issue post and the point about Hodir's Horn in Dun Niffelem (entry 192078): for me personally, starting to do the Sons of Hodir reputation quests since April 2018 on the 3.3.5 branch, I noticed that **the easiest point to focus on** to hand in [[Blowing Hodir's Horn]](https://wow.gamepedia.com/Quest:Blowing_Hodir%27s_Horn) (http://www.wowhead.com/quest=12977/blowing-hodirs-horn) is **the mouthpiece at the end of the horn**, approachable from the ground. The quest which I find is actually more difficult to hand in is [[Polishing the Helm]](https://wow.gamepedia.com/Quest:Polishing_the_Helm) (http://www.wowhead.com/quest=13006/polishing-the-helm) because you need to hover (flying) at a specific distance and angle at the front of the helm to be able to open the quest dialogue, both for obtaining the quest and handing it in.

**Comment by WyrtWicce** [comment]
Sorry, not a coder. Just trying to get things to work on my repack (I use Jeutie's 3.3.5a). Tried several of these in HeidiSQL but it gave me a syntax error for each one. I also don't have the same file paths y'all are mentioning. If anyone can walk me through applying this fix I'd really appreciate it. To specify, in Heidi I choose the relevant stream on the left panel (in this case it made sense to go world->gameobject) then pasted the text given here in the Query space, then hit the Execute button at the top. This is how I've been told to do these before, but please let me know if I'm doing something wrong.

**Comment by Aokromes** [comment]
we don't support repacks, you cannot modify repack's source.
