### ISSUE TITLE
Wrong check on Creature::IsImmunedToSpell

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#15458]
````c++
    // Creature is immune to main mechanic of the spell
    if (GetCreatureTemplate()->MechanicImmuneMask & (1 << (spellInfo->Mechanic - 1)))
        return true;
````

CreatureTemplate:
````
256	(0x0000 0100)	MECHANIC_SILENCE
````

Spell Mechanic:
````
Mechanic = 9 (MECHANIC_SILENCE)
````

06fa7af6c56d74362c504902ac07de92370a0155

**Comment by DDuarte** [comment]
```
1 << (9 - 1) =
1 << 8 =
256
```

Where's the error?

**Comment by ccrs** [comment]
then its not the bit check

the error must be somewhere else in the next calls.

right now bosses with this MechanicInmuneMask:
````
1|2|4|8|16|32|64|128|512|1024|2048|4096|8192|65536|131072|524288|8388608|67108864|536870912
````
are inmune to silence effects like Silenced - Gag Order (http://www.wowhead.com/spell=18498) (Mechanic = 9 (MECHANIC_SILENCE))
