### ISSUE TITLE
Guild petition

### ISSUE THREAD

**Issue by Fruttits** [TrinityCore/TrinityCore#15451]
Received not handled opcode [CMSG_OFFER_PETITION 0x08A3 (2211)] from [Player: try GUID Full: 0x0800040000000000000000000000025D Type: Player Entry: 0 Low: 605, Account: 10]

Can't see the invite accept petition.

rev : 344c32c1239305d0c335f96c08dc4597d66e8c29

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14216
