### ISSUE TITLE
DB/Core/Gossip: Trainers gossips

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15465]
rev. 821b5f2b5c17
Trainers with gossip menu (almost all of them) doesn't show the gossip menu with the text and the gossip option if there's only one option in the DB.
Example:
Npc: 17005 is a weapon trainer with npcflag=81 (* has gossip (1) * is trainer (16)* is profession trainer(64)
Gossip menu: 7337 with no option
In this case the npc always show directly the training interface instead of the gossip menu + option, maybe it's normal as there's no gossip_option.

But after adding the option, the npc continue showing directly the training interface, he will show the gossip only if the option is different from GOSSIP_OPTION_TRAINER or if there's a second one.
Here a the sql to add the gossip_option that must appear in the gossip_menu:

``` sql
DELETE FROM `gossip_menu_option` WHERE (`menu_id`=7337);
INSERT INTO `gossip_menu_option` (`menu_id`,`id`,`option_icon`,`option_text`,`OptionBroadcastTextID`,`option_id`,`npc_option_npcflag`,`action_menu_id`,`action_poi_id`,`box_coded`,`box_money`,`box_text`,`BoxBroadcastTextID`) VALUES
(7337,0,3,'Show me what you know, Larenis.',13168,5,16,0,0,0,0,'',0);
```
EDIT: Same issue with vendors.

**Comment by meji46** [comment]
Maybe missing type_flag CREATURE_TYPEFLAGS_FORCE_GOSSIP?

http://www.wowhead.com/npc=233/farmer-saldean is a vendor with gossip menu and CREATURE_TYPEFLAGS_FORCE_GOSSIP who displays the text and the vendor option.

**Comment by Killyana** [comment]
For me with or without CREATURE_TYPEFLAGS_FORCE_GOSSIP the gossip is never shown, also type_flag=0 for the npc=233.

**Comment by meji46** [comment]
The type_flag for the npc=233 is in 6.x DB (changed in cataclysm?).

**Comment by Killyana** [comment]
No but templates are more blizzlike for 6.x DB.
Anyway this is not an issue, just some type_flags must be updated.
