### ISSUE TITLE
Db2

### ISSUE THREAD

**Issue by Fruttits** [TrinityCore/TrinityCore#15462]
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/Achievement.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/AuctionHouse.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/BarberShopStyle.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/BroadcastText.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/CreatureType.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/CriteriaTree.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/CurrencyTypes.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/GameObjects.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/GarrAbility.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/GarrBuilding.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/GarrClassSpec.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/GarrFollower.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/ItemClass.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/ItemLimitCategory.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/ItemRandomProperties.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/ItemRandomSuffix.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/Item-sparse.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/MailTemplate.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/Mount.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/QuestSort.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/SpecializationSpells.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/SpellRange.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/TaxiNodes.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/TotemCategory.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/Toy.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.
Attempted to load /home/admin/serveur/wow/Data/dbc/enUS/UnitPowerBar.db2 which has locales frFR as enUS. Check if you placed your localized db2 files in correct directory.

last rev : 8aba20ce3a46443d5dada180a6ef9436ea4f7d4d
https://gyazo.com/2efa6b54d42cc2fe70cd4b3824f26d7f

**Comment by Aokromes** [comment]
Read the text you pasted.
