### ISSUE TITLE
[3.3.5a] "Argent Cannon" does not grant mana on cast

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15460]
Branch 3.3.5a, revision 3f3ff8b36b05, TDB 335.59

Vehicle [Argent Cannon](http://www.wowhead.com/npc=30236) used for quest [The Last Line of Defense](http://www.wowhead.com/quest=13086/the-last-line-of-defense) has the ability [Argent Cannon](http://www.wowhead.com/spell=57385/argent-cannon). This ability is supposed to grant 100 mana (10%) on cast in order to unlock secondary ability [Reckoning Bomb](http://www.wowhead.com/spell=57412). This does not happen.

**Comment by Killyana** [comment]
The initial mana must be 0.
``` sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 57387;
INSERT INTO `spell_linked_spell` VALUES (57387, 57608, 0, 'Argent Cannon - Powering Up The Core');

**Comment by Treeston** [comment]
unit_flags2 should probably also be 0.

**Comment by Killyana** [comment]
Yes and RegenHealth also 0 as it set the npc full mana on spawn.
