### ISSUE TITLE
Crash zone humain

### ISSUE THREAD

**Issue by Fruttits** [TrinityCore/TrinityCore#15463]
rev : 8aba20ce3a46443d5dada180a6ef9436ea4f7d4d

When i spawn in humain, i have a crash zone client : 

like that in 6.1.2 : https://github.com/TrinityCore/TrinityCore/blob/6.x/sql/updates/world/2015_07_27_01_world_2015_07_26_00.sql

and : https://github.com/TrinityCore/TrinityCore/blob/6.x/sql/updates/world/2015_07_26_06_world.sql

EDIT : i guest the fault is : this npc : 49871

**Comment by Killyana** [comment]
There's already an issue for this crash, and it comes from the emote if I'm not wrong.

**Comment by Fruttits** [comment]
okay thx you @Killyana
