### ISSUE TITLE
[Alchemy] Potion Master

### ISSUE THREAD

**Issue by Bezo** [TrinityCore/TrinityCore#1546]
this ability you get from the quest [Master of Potions] but its not work 
after 100 times i make some potions its not give me extra 1. 

http://old.wowhead.com/spell=28675 [Potion Master]

Rev:a29044373877b5682591
TDB: 335.11.40 Unix
Addons: Anticheat1 , AHbot, TrinityChat2

**Comment by Aokromes** [comment]
Works for me too.
