### ISSUE TITLE
[3.3.5a] Incorrect targeting for minion spell breaks quest

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15461]
Branch 3.3.5a, revision 3f3ff8b36b05, TDB 335.59.

While possessing a [Lithe Stalker](http://www.wowhead.com/npc=30895) for the quest [Generosity Abounds](http://www.wowhead.com/quest=13146/generosity-abounds), the spell [Iron Chain](http://www.wowhead.com/spell=58203/iron-chain), which is only supposed to be castable onto [Scourge Bomb](http://www.wowhead.com/npc=31075/scourge-bomb)s, is castable onto any unit. Doing so will still apply the Iron Chain aura, which pacifies the minion, but there is no way to remove this aura (as you are not dragging a bomb behind you).

**Comment by tkrokli** [comment]
Have you checked if any of this is related to the old (and closed) issue #11855?

**Comment by Treeston** [comment]
It's the same quest, except it's now fully functional, with the one exception I mentioned in the description above - target restriction for the Iron Chain ability is missing.

**Comment by Killyana** [comment]
Looks fine for me but I need confirmation.
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry` IN (58203);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17,0,58203,0,0,31,1,3,31075,0,0,0,'','Iron Chain');

**Comment by Treeston** [comment]
Confirmed on both.

Yeah, I didn't even mention the visual quirk with the abominations not appearing to explode - I've come to typically only report actual functionality issues.

**Comment by tkrokli** [comment]
Thanks for adding the animation. The game is not quite the same without some of the visual FX. :+1:
