### ISSUE TITLE
[6.x] Portal mop

### ISSUE THREAD

**Issue by Fruttits** [TrinityCore/TrinityCore#15478]
rev : 8e6886cecd5700facd95d52d3fbd4a2689d81d5f

in stormwind, i have create the portal of mop beacause there's no one, 
but i can't know the name of the ID in : from TaxiPath.dbc
we need it for the :  data0: taxiPathID

any one know for helping, then i can send my SQL portal mop
thx you

EDIT : in stormwind, the portal to pandaria doesn't exist

**Comment by DDuarte** [comment]
This doesn't look like a TC issue

**Comment by tkrokli** [comment]
@Fruttits : Do you mean the portal to Pandaria? Referencing "MoP" in your issue is mildly confusing, because none of the TrinityCore branches are "Mists of Pandaria" 5.x branch specifically (even if 6.x includes the content.

**Comment by Fruttits** [comment]
in stormwind, the portal to pandaria doesn't exist

**Comment by tkrokli** [comment]
OK, just write that in your first post so people know what you mean.

**Comment by Killyana** [comment]
Spawns on 6.x DB are not updated their are the ones from 4.3.4.
For this kind of portal they use a spell for the teleportation, the spell is generally in data0, if it doesn't work it's probably because the visual spell is used by the gob so you have to link it with the teleportation spell.
In this case link 130703 with 130702

**Comment by Fruttits** [comment]
@Killyana  100% works, this is it, created in spell_target_position and put the id in the data0

thx you

**Comment by tkrokli** [comment]
@Killyana : could it be that the spell is actually missing in the 6.x DB and that a fix could be posted?

**Comment by Killyana** [comment]
You mustn't change WDB data, in this case the spell 130702 is triggered by 130703 that exist in data0.

**Comment by Fruttits** [comment]
@Killyana i sent you a email on the forum, can you read it plz ?

**Comment by Killyana** [comment]
I Cannot find anything in the forum, go to irc if you need help.

**Comment by Fruttits** [comment]
do you have skype ?

**Comment by tkrokli** [comment]
Skype is not practical for your questions.
Use IRC: #trinity @ irc.rizon.net (see also the [**Rules**](http://collab.kpsn.org/display/tc/IRC) before entering).

**Comment by Fruttits** [comment]
yeah im on irc , :p thx you @tkrokli

**Comment by tkrokli** [comment]
You're welcome. Hope you find someone who can help you, if you need more help.
