### ISSUE TITLE
Quest Kick, What Kick?

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#15472]
3.3.5 branch
hash 166e66cc06d4
TDB 335.59 + updates

[Kick, What Kick?] (http://www.wowhead.com/quest=12589/kick-what-kick)

Because of this line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L803
the [Apple] (http://www.wowhead.com/npc=28053/apple)(which is needed for the script run) dissapear and never gets back,
So, it's only possible to complete the quest 1 time.

Also, the [Apple] (http://www.wowhead.com/npc=28053/apple) appears in the ground, instead of above the [Lucky Wilhelm](http://www.wowhead.com/npc=28054) head. Looks like a problem with the spell in the spell_click [50556] (http://www.wowhead.com/spell=50556/ride-wilhelm), because if replaced with [46598](http://www.wowhead.com/spell=46598/ride-vehicle-hardcoded) it works.

except this 2 issues, the quest works very well

**Comment by tkrokli** [comment]
Maybe the Apple despawn could be moved outside of the loop, to run only after quest complete?

Your info regarding spell 50556 <=> 46598 is interesting. Don't know what to suggest there, though.

**Comment by Killyana** [comment]
The spell 50556 require a target condition as Targets (38, 0) (TARGET_UNIT_NEARBY_ENTRY, NO_TARGET)

**Comment by sirikfoll** [comment]
This was fixed in 22f1d269865a5980dabadab1f469e60a701e9de1
