### ISSUE TITLE
[3.3.5] Creatures putting players in combat despite already being engaged

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15482]
Branch 3.3.5, revision 6cdfe9dc095b+, TDB 335.59

Walking within aggro range of an aggressive creature that is currently engaged in combat with another creature will make the player enter combat with the first creature. Expected behavior is to have the creature ignore the player if it already has entries on its threat table (unless the player engages it).

Repro examples are the soldier vs undead battles in borean tundra, as well as the sporelok vs bog giant battles in zangarmarsh.

**Comment by Trisjdc** [comment]
I bet my ass SAI is behind this.

**Comment by Trisjdc** [comment]
Unsurprisingly enough:

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartAI.cpp#L483

**Comment by tkrokli** [comment]
Would you suggest removing or commenting out `who->SetInCombatWith(me);` to fix this issue?
I guess the normal aggro behaviour will be handled by line number 484, `me->AddThreat(who, 0.0f);`

**Comment by Treeston** [comment]
I'd suggest just restoring the commented-out elseif conditional.

Outside of instances, mobs shouldn't put you on their threat list just from distance.

**Comment by tkrokli** [comment]
OK, so https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartAI.cpp#L481-L485 should be changed to:
```cpp
            else
                if (me->GetMap()->IsDungeon())
                {
                    who->SetInCombatWith(me);
                    me->AddThreat(who, 0.0f);
                }
```
Anything else worth checking while we are at it?

**Comment by Trisjdc** [comment]
SmartAI::MoveInLineOfSight is a mess. Unnecessary code, duplicated code, stupid logic.
Change it to:
```
void SmartAI::MoveInLineOfSight(Unit* who)
{
    GetScript()->OnMoveInLineOfSight(who);

    if (AssistPlayerInCombat(who))
        return;

    CreatureAI::MoveInLineOfSight(who);
}
```

**Comment by tkrokli** [comment]
OK, thanks for the feedback. @Treeston : care to look at this and possibly make use of it? :smirk_cat:

**Comment by Treeston** [comment]
Yup, I'll look into it later today.
