### ISSUE TITLE
[3.3.5] Inconsistent behavior of simultanous trinket use

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15492]
Branch 3.3.5, revision 6cdfe9dc095b, TDB 335.59.

When a character has two trinkets with an on-use buff equipped and uses one of them, the other is put on a shared cooldown equal to the duration of the used trinket's buff. This works as intended.

However, when both trinkets are (attempted to be) used in quick succession by a macro such as

```
/use 13
/use 14
```

the results are inconsistent between attempts. In most cases, the _second_ command (the slot 14 trinket) appears to be the one that is used, however I have also seen a case where _both_ trinkets managed to activate at the same time, which should never happen.

Expected behavior is that macro use commands are strictly evaluated in the order listed. If both trinkets are ready, the first line should always succeed (inventory slot 13 trinket should be used) and the second line should then subsequently fail due to the shared cooldown. The second line should only ever succeed if the first trinket is not ready.

**Comment by Treeston** [comment]
Possibly shares a root cause with #11644.
```
<tkrokli> Treeston, about your new issue, #15492 : are there any practical similarities between it and "Aura Stuck" #11644 ?
<tkrokli> both talk about trinkets and cooldowns, but I suppose there are differences
<tkrokli> just now quite sure where they overlap, if they do at all
<Treeston> they seem related
<Treeston> both are a case of macro commands not being strictly evaluated in order
<Treeston> but evaluated "simultanously"
<tkrokli> true, I thought the content in your issue felt similar
<Treeston> so in #11644 the trinket is removed "while" the aura is applied
<tkrokli> correct
<Treeston> and in #15492 the second trinket is cast "while" the first one is cast
<tkrokli> ok, that is different enough to keep yours open.
<tkrokli> I just wasn't sure if there would be any usefulness in linking between them.
<Treeston> yeah, do it
<Treeston> i'm not familiar with how communication between client and server happens in terms of macros
<Treeston> i'm assuming the client sends multiple "use this" instructions, not one "the macro told me to use this and this" instructions
<Treeston> both feel like race condition bugs, but i'm not even close to comfortable enough with the core to say that with any semblance of confidence
<tkrokli> could be, your theory is plausible, but I can'
<tkrokli> ** I can't confirm any of it
<tkrokli> needs feedback from someone in the know.
```

**Comment by Trisjdc** [comment]
Try merging https://github.com/TrinityCore/TrinityCore/commit/1efb3f08e278530f59d681f676b031a7fc6db3ac to 3.3.5 and try after.
I've got a big feeling this is related to cooldown/category handling.

**Comment by MrSmite** [comment]
> When a character has two trinkets with an on-use buff equipped and uses one of them, the other is put on a shared cooldown equal to the duration of the used trinket's buff. This works as intended.

Keep in mind this should only apply to trinkets with similar effects.
http://wowwiki.wikia.com/wiki/Trinket

Also, since trinkets are not supposed to trigger the GCD, these trinkets for example, should be able to be used consecutively (eg: the macro you posted):

http://wotlk.openwow.com/item=47734
http://wotlk.openwow.com/item=50235

One increases AP while the other increases health. Two different effects, no GCD.

**Comment by Treeston** [comment]
In that case, the fact that the trinket that did not activate was put on a shared cooldown like I mentioned would be the bug.

Either way, the behavior is inconsistent across activations, which should never happen.

**Comment by Myst** [comment]
@Shauren any idea of how we fix this?, probably need an aditional condition on AddSpellAndCategoryCooldowns

**Comment by Treeston** [comment]
Do we have any news on this?

**Comment by tkrokli** [comment]
Is this issue unchanged before and after commit 7dcddd90be6e49281ca04239de5839e757ef3f7a (cherry-picked from commit 1efb3f0)?
(Looking at what @Trisjdc mentioned in https://github.com/TrinityCore/TrinityCore/issues/15492#issuecomment-139610745 as a possible solution to this issue.)
