### ISSUE TITLE
[3.3.5] Emote Sounds not working

### ISSUE THREAD

**Issue by Maxxgold** [TrinityCore/TrinityCore#15507]
/cry
/chicken

no sounds. The only one that works for me is /train

59eff3fef91cec1b95e552122fde6e95ba1ab0fb

**Comment by Killyana** [comment]
You are linking a 6.x rev

**Comment by tkrokli** [comment]
TrinityCore rev. 2138726e61f8 2015-09-12 22:55:44 +0200 (3.3.5 branch) (Win64, Release)
Unable to reproduce the issue. Works as intended here. Check your game settings and server version.

**Comment by Killyana** [comment]
There's no problem on 6.x neither, maybe you must provide the race and the gender of the character.

**Comment by Maxxgold** [comment]
Sorry about that.

**Comment by Maxxgold** [comment]
TrinityCore rev. e1bd06213ba2 2015-09-13 11:31:06 -0400 (3.3.5 branch) (Win64, Release) (worldserver-daemon)

**Comment by tkrokli** [comment]
Have you added something or found a non-standard core source? **e1bd06213ba2** does not exist on the TrinityCore 3.3.5 branch. No newer revision than 2138726e61f8 for 3.3.5 yet (2015-09-12 22:55:44 +0200)
