### ISSUE TITLE
DB/Quest: The Road to Darnassus quest log description

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15517]
TrinityCore rev. 20ce8cbbc24b 2015-09-14 23:38:21 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + all updates including 2015_12_09_00_world.sql

Quest 487 The Road to Darnassus, http://wotlk.openwow.com/quest=487
Quest giver NPC 2151, **Moon Priestess Amara** : http://wotlk.openwow.com/npc=2151

Currently, the quest log description contains a wrong form of the quest giver's name:
`Slay 6 Gnarlpine Ambushers and return to Sentinel Amara Nightwalker outside of Dolanaar.`

world DB update:
```sql
UPDATE `quest_template` SET `LogDescription` = 'Slay 6 Gnarlpine Ambushers and return to Moon Priestess Amara outside of Dolanaar.' WHERE `Id`= 487 AND `RequiredNpcOrGo1`= 2152;

**Comment by Nyeriah** [comment]
Is this from sniff? Wowhead comments suggest it should refer to her as "sentinel"

http://www.wowhead.com/quest=487/the-road-to-darnassus#comments:id=57796

**Comment by tkrokli** [comment]
I don't have any sniff of this yet, but I noticed that wowhead only says "Slay 8 Gnarlpine Ambushers." instead of the longer text in TDB. I guess it is Blizzard's fault and that this issue should be closed, then.

**Comment by Rushor** [comment]
http://web.archive.org/web/20100616090538/http://www.wowhead.com/quest=487

http://i.imgur.com/RarG7H1.png

Slay 6 Gnarlpine Ambushers and return to Sentinel Amara Nightwalker outside of Dolanaar. 

text is correct > closing
