### ISSUE TITLE
[shaman][talent] Improved Stormstrike

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15516]
It should have caused the following effect: "When you Stormstrike, you have a 100% chance to immediately grant you 20% of your base mana".

Shaman base mana is: 6366, So 20% of 6366 is 1273, but it return only 679 Mana

Stormstrike talent id: 17364
Wowwiki link of the Improved Stormstrike: http://www.wowwiki.com/Improved_Stormstrike
Wowwiki link to Stormstrike: http://www.wowwiki.com/Stormstrike

rev: 2138726e61f83eea76634372e8cb1b4452e0f84d

**Comment by P-Kito** [comment]
Where did you read that this is Shamans' base mana?

(Just so I can check it too)

**Comment by Runico** [comment]
@P-Kito, A shaman without any equipped item has 6366 Mana, So this should be base mana

**Comment by Rushor** [comment]
@Runico: a nacked char without any equip is NOT the fucking basemana. you must also remove the intstats from your char in the calculation

**Comment by Rushor** [comment]
see the base manavalues from http://wowwiki.wikia.com/index.php?title=Base_mana&diff=2192386&oldid=2060767 - can we close this stuff then?

**Comment by P-Kito** [comment]
close it...
