### ISSUE TITLE
[3.3.5] Warrior - Spell Recklessness aura stuck

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15529]
http://wotlk.openwow.com/spell=1719

Spell Description:
Your next 3 special ability attacks have an additional 100% to critically hit but all damage taken is increased by 20%. Lasts 12 sec.

Problem:
If you use Recklessness with spells of one target it will work normally.
However use Recklessness with spells of multiple targets, the last charge of the buff does work (is not consumed and not give the effects)

Reproduction:
Use Recklessness buff and use the spell Cleave (id = 47520) in a location with multiple targets. The first 2 charge of Recklessness will be consumed normally, however the latter will not function.

Little Vid: https://youtu.be/Z2V-vAKb5UE

Using comments in this piece of code: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L7695 is called 2 times, when it is used spells of multiple target like a cleave

Trinity Hash: 9a43dd35cdd40228db5b8519b53ca5b6438c3c18

Maybe related to: #7315

**Comment by Keader** [comment]
@robinsch I do not know if you are in time, but it is one of the few who is interested / have expertise in spells correction could take a look then ?!

**Comment by robinsch** [comment]
The entire proc system never really worked good with charges - but I currently don't have the time to fix it.

For ´hack-fixing the charges drop you could just add a check for 
if (GetCharges() > 1) *handled = true;
but this will not fix the crit chance.

**Comment by Keader** [comment]
Related too: https://github.com/TrinityCore/TrinityCore/issues/932#issuecomment-4033950

**Comment by Keader** [comment]
@ariel-  this maybe related #16186 ?
Can you take a look?

**Comment by ariel-** [comment]
@Keader Recklessness drops one charge per target, I don't know if it should be like this or should drop a charge per SPELL

**Comment by Keader** [comment]
But if by target should not consume  three charges in the first Cleave?
When there are 3 Targets when using cleave are still consumed only 2 charge

**Comment by ariel-** [comment]
Exactly,  spellMod charges (as in the part that gives next 3 spells 100% crit) will now be consumed once per target, however the aura gets stuck at 2 charges now because when you hit 3 targets, the modspells are consumed to 0, and then the aura stacks are never updated, giving the aura "stuck" at 2 stacks.

Now I don't know which one is blizzlike, to drop a charge per target (as it is) and fix the aura stacks so they match spellmod charges. OR, drop a charge per spell and fix the spellmod charges so they match aura stacks.

**Comment by Shauren** [comment]
Logic/tooltip suggests it being per spell but the real issue is that we actually have 2 separate counters for charges, one on aura and one on spellmod

**Comment by Keader** [comment]
@ariel-  @Shauren Look this: https://youtu.be/IijlbG7yrlc?t=3m10s  (Charge -> Recklessness -> Bladestorm) , all charge are consumed on first aoe damage.
I believe that the Charges are dropped for target

**Comment by Shauren** [comment]
well, idk - also bladestorm is kinda weird example because it triggers multiple spells to do damage

**Comment by Keader** [comment]
On WoW Head Comments:
"By Oberscht (19,720 – 5·25·144) on 2008/12/11 (Patch 3.0.3)		
When using Whirlwind while Recklessness is active, you loose 2 charges for every enemy you hit. Might be a bug. So make sure you have only 1 charge before using WW."

http://www.wowhead.com/spell=1719/recklessness#comments

**Comment by ariel-** [comment]
Because WW is 2 spells, one for each hand, I assume that's why it loses 2 charges per target.

As for auras, I have the theory the auras stack with themselves, which shouldn't happen either (aura charge != aura stack)

**Comment by Keader** [comment]
@ariel-  any news on this? xD

**Comment by ariel-** [comment]
Soon™

**Comment by Keader** [comment]
this is a dream?!
