### ISSUE TITLE
Transmogrification.cpp

### ISSUE THREAD

**Issue by KaraLegal** [TrinityCore/TrinityCore#15535]
Good one and my first issue and as you can see I'm using the google translator, but my problem and the following every time I try to compile the TrinityCore appears as follows:

/home/trinity/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp: In member function \u2018void Transmogrification::LoadPlayerSets(Player*)\u2019:
/home/trinity/TrinityCore/src/server/scripts/Custom/Transmog/Transmogrification.cpp:65:17: error: \u2018class Player\u2019 has no member named \u2018presetMap\u2019
         player->presetMap[PresetID].name = SetName;

I am using

Ubuntu 4.14 Server 32-bit

TrinityCore revision: 16b42a40605c + 2015-09-16 08:14:15 +0200 (3.3.5 branch)
TrinityCore buildtype: Release

**Comment by Killyana** [comment]
There's no Transmogrification on 3.3.5 branch

**Comment by tkrokli** [comment]
Custom scripts are not supported by TrinityCore either, but that is minor compared to 3.3.5 + Transmog.
@KaraLegal : ask in other forums about your problem, maybe a forum where Rochet2 can see it.

**Comment by Rochet2** [comment]
https://github.com/Rochet2/TrinityCore/issues/7
