### ISSUE TITLE
[3.3.5] Crash  Player::RefundItem

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#15536]
6fedea54ef3f1c678f0869807ac38b1db72351fd , 
http://pastebin.com/buMAL3Lm
Ubuntu 12.04.5 LTS

Custom:
Trasnmogrification.

**Comment by Rushor** [comment]
@Voidx: this issue is still present?

**Comment by tkrokli** [comment]
Would be interesting to know if the item refund event could in any way be related to transmog.

**Comment by Rushor** [comment]
no answer after monts - closing

**Comment by Rushor** [comment]
This issue actually still happens sometimes (if server has trasmog)

**Comment by Shauren** [comment]
Not our problem if transmog is the cause
