### ISSUE TITLE
[3.3.5] Core/Pet: Risen Ghoul - "Huddle" is intrerrupted instantly

### ISSUE THREAD

**Issue by unknown-8H3D** [TrinityCore/TrinityCore#15539]
Revision: https://github.com/TrinityCore/TrinityCore/commit/2138726e61f83eea76634372e8cb1b4452e0f84d

Spell: http://www.wowhead.com/spell=47484/

This spell should stop the Risen Ghoul from walking / following the owner until the channeling is finished / the owner commands the Risen Ghoul to do something else.

Currently, the spell is interrupted instantly because the Risen Ghoul continues to walk / follow the owner.

Same as: https://github.com/TrinityCore/TrinityCore/issues/14054 (Possible fix: https://github.com/TrinityCore/TrinityCore/pull/14813)

**Comment by unknown-8H3D** [comment]
Why closed ?
Issue is still valid on revision https://github.com/TrinityCore/TrinityCore/commit/c703e01471a3598f68051abb17e598e316b744ef.

**Comment by DDuarte** [comment]
> 18:57:31 <%Kilyana> Issue 15539 will be fixed by https://github.com/TrinityCore/TrinityCore/pull/14813
