### ISSUE TITLE
[3.3.5a] Prospecting has a possibility of yielding no loot

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15537]
3.3.5a, c5cc7cca3e29e176b5ec0405a05c3db8e19c4e93.

It is possibly to prospect ore and receive no loot whatsoever. To my knowledge, this is not the case on retail - you will always receive at least one gem.

**Comment by tkrokli** [comment]
Have you compared notes with what is posted in #12011 ? It looks pretty close to your question.
