### ISSUE TITLE
[335] Neutral NPCs should not assist hostile NPCs (aggro)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15549]
__Core:__ 747ea7ca2c2b757dc9c5a672746d801a8365ee98
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

Sometimes a neutral NPC will assist a hostile NPC in combat

__Details__

I was passing through Elwynn Forest on a level 2 Paladin when I was attacked by a level 5 [Mangy Wolf](http://www.wowhead.com/npc=525/mangy-wolf) (hostile). I had the wolf at about 40% health when a nearby level 1 [Diseased Young Wolf](http://wowwiki.wikia.com/wiki/Diseased_Young_Wolf) (neutral) started attacking me (no, I did not have any AOE).

__Notes:__

* I was able to reproduce this by simply running up to a level 6 Mangy Wolf and immediately upon aggro, a neutral wolf attacked me.
* The neutral wolves in Nortshire Valley do not assist each other

**Comment by tkrokli** [comment]
The page http://wow.gamepedia.com/Diseased_Young_Wolf is in better shape than the wowwiki page.

Anyway, from the same page; [**Notes:** They are socially linked to nearby](http://wow.gamepedia.com/Diseased_Young_Wolf#Notes) 
![combat_icon](https://cloud.githubusercontent.com/assets/4903600/9981554/f8bf3092-5fc0-11e5-910d-3d206386a8db.png) [Mangy Wolves](http://wow.gamepedia.com/Mangy_Wolf).

Does this suggest that the mobs are linked in-game too, like in NPC family assist?

**Comment by Killyana** [comment]
From http://wow.gamepedia.com/Mangy_Wolf
Patch 3.3.0 (2009-12-08): They will get help from nearby Combat Diseased Young Wolves or Combat Diseased Timber Wolves when being attacked.

**Comment by tkrokli** [comment]
Indeed. As well as the main text above states: " Mangy Wolves can also be found travelling alongside
![combat_icon](https://cloud.githubusercontent.com/assets/4903600/9981554/f8bf3092-5fc0-11e5-910d-3d206386a8db.png) Young Wolves, in a small patch of forest between Stormwind City and Northshire Valley. Upon attacking either of the two, the other will aggro no matter how far apart they are, as if they are 'linked'. "

**Comment by DDuarte** [comment]
I wonder how does this work in TC :P

**Comment by tkrokli** [comment]
Not sure, maybe via factions? Faction = 32 (neutral) for the young wolves, 38 for the hostile mangy wolf.
I don't know where they could be linked, though. Maybe Malcrom knows.

**Comment by MrSmite** [comment]
Interesting, thanks for the links. I wonder why the diseased wolves in Northshire Valley aren't socially linked in that way.

**Comment by tkrokli** [comment]
For good reason: you don't want the noobs to be attacked by 2, 3 or possibly 4 wolves when learning a completely new character at level 1 - 2.
