### ISSUE TITLE
Bug Reports not being submitted 6x

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#15543]
Rev: 93875c5

TDB 602

Bug reports are not being recorded in the Database.
Two friends that are testing the server with me tried to submit bugs that they found but nothing got submitted. Is this not coded yet?

**Comment by DDuarte** [comment]
CMSG_BUG_REPORT and CMSG_SUPPORT_TICKET_SUBMIT_BUG are currently unhandled otherwise this should work with minor modifications

**Comment by Keldo** [comment]
so modify opcodes or is is somewhere else?

**Comment by DDuarte** [comment]
I haven't checked if the structure changed however you can try changing to STATUS_LOGGEDIN in https://github.com/TrinityCore/TrinityCore/blob/c7d49ab91074472d821d681266ad0e90b7d8887e/src/server/game/Server/Protocol/Opcodes.cpp#L765

**Comment by Keldo** [comment]
Changing the Opcodes worked.

**Comment by Keldo** [comment]
As of today, I'm at work and do not have the revision with me.
I rebuilt this morning.
It is not submitting bugs to the database again. I have not had a chance to look at the Opcodes. Was something changed?

**Comment by tkrokli** [comment]
Check the list, 6 updates today: https://github.com/TrinityCore/TrinityCore/commits/6.x

**Comment by Keldo** [comment]
Thanks,
Once I see it implemented, I will close this again.

**Comment by tkrokli** [comment]
Your changed line is still the same as yesterday. If you don't remember where it is, follow the link:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp#L770

The only other commit to touch that file is this commit:
https://github.com/TrinityCore/TrinityCore/commit/32a2e584296556e852830e50cfa612ce279360b6#diff-6264cfa494f1cd4710766a1af602f393

**Comment by Keldo** [comment]
Should THREADUNSAFE be changed to THREADSAFE?
Just curious, as making it UNSAFE doesn't sound right to me

**Comment by tkrokli** [comment]
No, it should not be changed unless you got proof that it is safe to split the process into multiple threads (which is normally not the case).

**Comment by Keldo** [comment]
Well I pulled last night and rebuilt, its still not working. I will hard code tonight and see if it changes.
