### ISSUE TITLE
6x Zeplin Crews Falling to the Ground

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#15544]
Rev 10b068c
TDB 602

On the slope southwest of the Zeplin Towers outside of Undercity, on Approach the Purple Princess Zepplin crew falls to the ground along with 2 Vendo-O-Tron's. Since this is in a start area, I'm not sure if it is still being covered.

**Comment by Killyana** [comment]
It's not the crew who fall down, but wrong extra spawns in map 0.

**Comment by Killyana** [comment]
I removed the wrong spawns on 4.3.4 after that I figure out that guids are not the same in both branches, I will try to do it in 6.x later.
https://gitlab.com/trinitycore/TrinityCore_434/commit/ff4c7cfb29bab45d4a1ad197ae9b1fb86760299e
