### ISSUE TITLE
6x Pandaria Start No Quest

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#15545]
Rev 10b068c
TDB 602

Pandaria start area, Panda's have no quest available to them. 

this in itself makes the Pandarian race useless

**Comment by tkrokli** [comment]
Those are 2 different issues and could have 2 different solutions (I don't know yet), DB vs core.
As long as none of those 2 issues are reported already, you should split it into 2 separate issues.

**Comment by Keldo** [comment]
updated and removed the second issue

**Comment by MitchesD** [comment]
As I already said in many issues before, pandaren starting zone isn't done yet, I am working on it, but it's intended that you can't get any quests, because it can cause many problems if you can take non-scripted quests in that area.

**Comment by Keldo** [comment]
Aokromes remove this thread please.

**Comment by MrSmite** [comment]
> Aokromes remove this thread please.

No need to remove it, you should be able to close the issue (close button) since @MitchesD gave an acceptable answer.

**Comment by Aokromes** [comment]
There is no way to remove a ticket.

**Comment by tkrokli** [comment]
Good point. Thanks for verifying that, Aok. :+1:

**Comment by MrSmite** [comment]
> There is no way to remove a ticket.

Delete the repo ;)

**Comment by tkrokli** [comment]
@MrSmite : Funny. Imagine all the lost issue tracking history, as well as most users' trust in Trinity...

**Comment by BahDumbBugs** [comment]
Was this from September of this year or last.....? Just curious on the status of this.

**Comment by tkrokli** [comment]
Check the comment from MitchesD: https://github.com/TrinityCore/TrinityCore/issues/15545#issuecomment-141702372 from September 19, 2015 (same day as OP).

**Comment by BahDumbBugs** [comment]
Sorry. I withdraw my question. Thanks @tkrokli

**Comment by JaredNinja** [comment]
Hi. Is there any news on this? I'd love to see Pandaria quests integrated in Trinity 6.x

Some repacks seem to have them (not sure about the quality though). And I'm not even sure how I could add them to my 6.x core build without running into trouble later on (TBD updates?)

**Comment by jazzy348** [comment]
I too would like MOP quests.

**Comment by illfated** [comment]
@jazzy348 : Check out the PR [**[WIP] Scripts/Pandaria: The Wandering Isle**](https://github.com/TrinityCore/TrinityCore/pull/17021) #17021 to see what is being worked on.
You could also fork that branch to test the content yourself.
