### ISSUE TITLE
[3.3.5a] "At The Enemy's Gates"

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15540]
Branch 3.3.5a, revision c5cc7cca3e29e176b5ec0405a05c3db8e19c4e93.

Quest [At The Enemy's Gates](http://www.wowhead.com/quest=13847/at-the-enemys-gates) and variants for the other factions.

[Boneguard Footman](http://www.wowhead.com/npc=33438) is supposed to die on contact with the [Campaign Warhorse](http://www.wowhead.com/npc=33531/campaign-warhorse) vehicle. This does not happen.

Spell IDs supposedly used are [63000](http://www.wowhead.com/spell=63000) and [63001](http://www.wowhead.com/spell=63001).

**Comment by Rushor** [comment]
this works fine for me on latest rev. anyone can confirm this?
