### ISSUE TITLE
[335] AHBot Buyer Considers Own Auctions In Chance Calcs.

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15542]
__Core:__ 747ea7ca2c2b757dc9c5a672746d801a8365ee98
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

When calculating the *chance*, the Buyer uses *ahInfo->BuyItemCount* to determine if it needs to calculate a weighted chance. Unfortunately it considers its own auctions in this number which it can never buy.

The effect is the possibility of a very small buyout chance when player and bot sell the same item.

__Details:__

I sold 1x Small Brown Pouch (entry 4496) but the bot has 44 of them for sale. When this line was evaluated:

```C++
// If there are more than 5 items on AH of this entry, try weigh in the average buyout price
if (ahInfo->BuyItemCount > 5)
    chance *= 1.f / std::sqrt(itemBuyPrice / avgBuyPrice);
```
my auction was given a very low chance of buyout (__8.86255455__) because the bot thinks I'm selling 45 of them, even though I have the config set to a very high chance:

> AuctionHouseBot.Buyer.ChanceFactor = 90
> AuctionHouseBot.Buyer.ChanceMultiplier.Gray = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.White = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.Green = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.Blue = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.Purple = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.Orange = 1000
> AuctionHouseBot.Buyer.ChanceMultiplier.Yellow = 1000

In debug, that same auction when skipping that calculation ended up with a __27.2220325__ chance which seems more accurate since I'm only selling one and my buyout (1g 25s) is 100 times the sell price (1s 25c).

Since the bot can never buy its own auctions, it should not be considering them in formulas regarding bid or buyout of player auctions.

__Notes:__

The chance calculations use *BuyerItemInfo::ahInfo* but *BuyerItemInfo* does not contain the seller's information so there is no way for the calculations to know who's auction it is.

**Comment by Warpten** [comment]
I have no clue how this works, but try this:

```diff
@@ -120,8 +120,8 @@ uint32 AuctionBotBuyer::GetItemInformation(BuyerConfiguration& config)
         else
             itemBidPrice = std::min(itemInfo.MinBidPrice, itemBidPrice);
 
-        // Set minimum buyout price if item has buyout
-        if (entry->buyout)
+        // Set minimum buyout price if item has buyout and is not our own auction
+        if (entry->buyout && entry->owner != 0)
         {
             // Update item entry's count and total buyout prices
             // This can be used later to determine the prices and chances to buyout
@@ -154,6 +154,9 @@ uint32 AuctionBotBuyer::GetItemInformation(BuyerConfiguration& config)
 // ahInfo can be NULL
 bool AuctionBotBuyer::RollBuyChance(const BuyerItemInfo* ahInfo, const Item* item, const AuctionEntry* auction, uint32 /*bidPrice*/)
 {
+    if (auction->owner == 0)
+        return false;
+    
     if (!auction->buyout)
         return false;
 
@@ -193,6 +196,9 @@ bool AuctionBotBuyer::RollBuyChance(const BuyerItemInfo* ahInfo, const Item* ite
 // ahInfo can be NULL
 bool AuctionBotBuyer::RollBidChance(const BuyerItemInfo* ahInfo, const Item* item, const AuctionEntry* auction, uint32 bidPrice)
 {
+    if (auction->owner == 0)
+        return false;
+    
     float itemBidPrice = float(bidPrice / item->GetCount());
     float itemPrice = float(item->GetTemplate()->SellPrice ? item->GetTemplate()->SellPrice : GetVendorPrice(item->GetTemplate()->Quality));
     // The AH cut needs to be added to the price, but we dont want a 100% chance to buy if the price is exactly AH default
```

**Comment by MrSmite** [comment]
@Warpten Thanks, I was looking at a different solution.

In *AuctionBotBuyer::GetItemInformation()*, it loops through the entire auction map for the specified house where we have this:

```C++
BuyerItemInfo& itemInfo = config.SameItemInfo[item->GetEntry()];
itemInfo.BidItemCount++;
```

Thing is it doesn't check if the item belongs to the bot. Also, I can't find anywhere that *config.SameItemInfo* gets filled with data but it does... either in the code block I just referenced or where *SameItemInfo* gets filled would be the best place to skip auctions owned by the bot.

**Comment by Warpten** [comment]
Anyway the point is to not increase BidItemCount if auction owner guid is 0. cooked this through github, may have missed some.

**Comment by Rochet2** [comment]
> Also, I can't see how SameItemInfo even has any data in it because after the clear() at the function entry point, I don't see where it gets filled.

Its filled in the loop you quoted from code. `[]` operator creates elements if one does not exist and allows access and modify.
So the loop counts all items that are of same entry
```c++
    BuyerItemInfo& itemInfo = config.SameItemInfo[item->GetEntry()];
    itemInfo.BidItemCount++;
```

**Comment by MrSmite** [comment]
> [] operator creates elements

GAH! Thanks for pointing that out. I was reading that as if it were accessing an array element :(

**Comment by MrSmite** [comment]
> @Warpten Anyway the point is to not increase BidItemCount if auction owner guid is 0
> @Rochet2  So the loop counts all items that are of same entry

Yes, indeed

**Comment by Aokromes** [comment]
811b557
