### ISSUE TITLE
DB/Gossip: "Noth, where is Heigan?" menu option not responding

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15553]
TrinityCore rev. 1cb8de7d054a 2015-09-20 17:04:15 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates up to and including 2015_09_20_00_world.sql

Plaguelands: The Scarlet Enclave, Havenshire Farms, phase 2 of the DK questline.
Noth the Plaguebringer, quest NPC http://wotlk.openwow.com/npc=28919

After completing the first phase as a Death Knight, Havenshire is mostly cleared of hostile NPCs.
The player meets Noth the Plaguebringer (NPC 28919) as a quest giver for:
- The Plaguebringer's Request (http://wotlk.openwow.com/quest=12716)
- Noth's Special Brew (http://wotlk.openwow.com/quest=12717)

Noth also has got a gossip menu option saying "Noth, where is Heigan?", which the player should be able to click and get 1 of 5 random replies:
```sql
SELECT `MaleText` FROM `broadcast_text` WHERE `ID` BETWEEN 29064 AND 29068;
```
- How dare you! Get out of my sight!
- That no good kiss-up is probably practicing ballet in his chambers.
- NEVER say that name around me! Consider this your one and only warning!
- I can tell you where he's not...
- Heigan is probably performing maintenance on his slime and crap filled dance studio.

These texts are also already in `npc_text` :
```sql
SELECT * FROM `npc_text` WHERE `text0_0`= 'How dare you! Get out of my sight!'; -- ID = 13396
```
Noth's gossip menu option has been non-responsive for as long as I can remember in the TC source, nothing happens when clicking that option. This is because the gossip_menu value is missing in the `action_menu_id` (current value = 0) in the table `gossip_menu_option` and the line `menu_id` = 9754;
```sql
SELECT * FROM `gossip_menu_option` WHERE `menu_id`= 9754;
```
```
menu_id      id  option_icon  option_text             OptionBroadcastTextID  option_id  npc_option_npcflag  action_menu_id  action_poi_id  box_coded  box_money  box_text  BoxBroadcastTextID
-------  ------  -----------  ----------------------  ---------------------  ---------  ------------------  --------------  -------------  ---------  ---------  --------  ------------------
   9754       0            0  Noth, where is Heigan?                  29063          1                   1               0              0          0          0                             0
```
**Solution:** to make this menu option work, run this query on the world DB:
```sql
UPDATE `gossip_menu_option` SET `action_menu_id`= 9753 WHERE `menu_id`= 9754;

**Comment by Killyana** [comment]
Fixed here https://github.com/TrinityCore/TrinityCore/commit/5cf6b8cc86107c816731c57d8175afe755aa0cbd

**Comment by tkrokli** [comment]
I think you are confusing Friendly NPC 28919 (DK quest giver) with Hostile Noth in Naxxramas (boss).
I tried to be as specific as possible about the fact that this is NOT the Naxxramas boss, but a Quest Giver.
Please reopen until the correct fix is applied to the source.

**Comment by tkrokli** [comment]
Sorry for my previous comment, I opened the raw file and tried to read everything from the end of the page.
