### ISSUE TITLE
[335] Visible trigger in Silvermoon City

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15555]
__Core:__ 747ea7ca2c2b757dc9c5a672746d801a8365ee98
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

There is a visible trigger that looks like a giant Owl in Silvermoon City, flying on top of the Herbalism trainer:

Entry: 22023
GUID: 84939

__Notes:__

* It is not selectable by players
* It has no nameplate visible to players
* With *.gm on*
 * it has a nameplate: [DND] Spirit 1
 * it can be selected

**Comment by tkrokli** [comment]
TrinityCore rev. 1cb8de7d054a 2015-09-20 17:04:15 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates up to and including 2015_09_20_00_world.sql

Confirmed. Notice that there is no space between `[DND]` and `Spirit` in the grey owl's name.
Herbalism trainer's name and page: **Botanist Nathera <Herbalism Trainer>** (Added in patch 2.2.0)
http://wotlk.openwow.com/npc=16644 || http://www.wowhead.com/npc=16644/botanist-nathera

Nearby NPC: Melaris <Alchemy Supplies> http://www.wowhead.com/npc=16641/melaris

**[DND]Spirit 1** : http://wotlk.openwow.com/npc=22023 || http://www.wowhead.com/npc=22023/dnd-spirit-1
hint: " Location of this NPC is unknown, possibly spawned via script. "
AIName : SmartAI ; unit_flags : 33554432 (32M) (0x0200 0000 || UNIT_FLAG_NOT_SELECTABLE)
Faction: 35 for the owl, 1604 for the 2 blood elf NPCs.
Query to compare similarities and differences in the DB:
```sql
SELECT * FROM `creature_template` WHERE `entry` IN (16641,16644,22023);
```
I was wondering if this creature should be invisible to players, but I'm not sure if it is valid to use `flags_extra` and the value | 128 | CREATURE_FLAG_EXTRA_TRIGGER | 0x00000080 | creature is trigger-NPC (invisible to players only) | - I think this info must come from sniffs.
Current value in `flags_extra` is | 2 | CREATURE_FLAG_EXTRA_CIVILIAN | 0x00000002 | (creature does not aggro (ignore faction/reputation hostility)) | for all 3 creatures.

Could it be that the coordinates and scale is wrong for this bird, that it is meant to be a decoration?

**Comment by Killyana** [comment]
It's an wrong spawn, this npc is used in  http://www.wowhead.com/quest=10714/on-spirits-wings
