### ISSUE TITLE
6x NPC Trainers

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#15563]
8ea1764
TDB 602

Location is Brill/Undercity.
Trainers have no Gossip or Options.
IE: First Aid trainer Nurse Neela

When you check the world/npc_trainer table, their are only 4 entries.

**Comment by DDuarte** [comment]
#14682

**Comment by MitchesD** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14682
