### ISSUE TITLE
QUEST The Drakkensyrd weird issue..

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15568]
http://www.wowhead.com/quest=12886/the-drakkensryd

TrinityCore rev. f50df72 2015-08-24 14:52:18 +02000 ( 3.3.5 branch) (Win64, Release)

Ok, so I tried this 

#1350#issuecomment-75295161

but character is not mount up.. look this screenshot ..

![bug](https://cloud.githubusercontent.com/assets/10039561/10016956/6cc6df26-6133-11e5-921a-066d1ebf88db.png)

**Comment by Aokromes** [comment]
you found the other issue why you open new tickets?
