### ISSUE TITLE
[3.3.5a] "Hot and Cold" - quest item use inconsistent

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15566]
Branch 3.3.5a, revision c5cc7cca3e29e176b5ec0405a05c3db8e19c4e93.

On the Sons of Hodir daily quest [Hot and Cold](http://www.wowhead.com/quest=12981), after looting the "Essence of Ice", attempting to use it on the "Smoldering Iron Scrap"s is inconsistent. While it will work in about two thirds of attempts, the other third will act as if you had cast the item on yourself (you will see the particle hit animation on yourself), and will effectively "waste" the item.

**Comment by tkrokli** [comment]
Sons of Hodir : http://www.wowhead.com/faction=1119/the-sons-of-hodir
SoH quest list : http://www.wowhead.com/faction=1119/the-sons-of-hodir#quests
Hot and Cold : http://www.wowhead.com/quest=12981/hot-and-cold
Frozen Iron Scrap : http://www.wowhead.com/item=42252/frozen-iron-scrap
http://www.wowhead.com/quest=12981/hot-and-cold#comments
http://www.wowhead.com/spell=56073/summon-smoldering-scrap
Smoldering Scrap : http://wotlk.openwow.com/object=192124

**Comment by Killyana** [comment]
I'm tryning ot find the visual ice: http://www.wowhead.com/item=42252/frozen-iron-scrap#screenshots:id=99095
``` sql
DELETE FROM `conditions` WHERE `SourceEntry` = 56099 AND `SourceTypeOrReferenceId` = 13;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,1,56099,0,0,31,0,3,30169,0,0,0,'','Essence of Ice target Smoldering Scrap Bunny');

DELETE FROM `creature` WHERE `guid` IN (116640, 116641, 116642); -- duplicated spawns

**Comment by Killyana** [comment]
I have a problem with visual auras on npcs with extra_flag trigger.
If I .cast self 56135 or .aura 56135  the visual affect appears
If the spell is casted with linked_spell or casted using SAI or the aura added by SAI the visual affect is visible on gm mode only.

```
ServerToClient: SMSG_AURA_UPDATE (0xE86C) Length: 24 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238994
GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
[0] Slot: 0
[0] Spell ID: 56135 (56135)
[0] Flags: EffectIndex0, NotCaster, Positive, Duration (57)
[0] Level: 80
[0] Charges: 0
[0] Max Duration: 15000
[0] Duration: 15000

ServerToClient: SMSG_SPELL_START (0xDB2F) Length: 33 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238995
Caster GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Caster Unit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Cast Count: 0
Spell ID: 56135 (56135)
Cast Flags: HasTrajectory (2)
Time: 0
Target Flags: Self (0)

ServerToClient: SMSG_SPELL_GO (0xEC2D) Length: 44 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238996
Caster GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Caster Unit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Cast Count: 0
Spell ID: 56135 (56135)
Cast Flags: Unknown7 (256)
Time: 2850580801
Hit Count: 1
[0] Hit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Miss Count: 0
Target Flags: Unit (2)
Target GUID: 0x0
