### ISSUE TITLE
3.3.5a relog/dc should not leave party

### ISSUE THREAD

**Issue by DearAdmin** [TrinityCore/TrinityCore#15561]
Hello , sorry for open issue but since my english is bad and can't find issue

I needed to open issue

after relog or dc makes player leave party but it should not leaving party because in instance or dungeon it gives leaving..

is there any way to fix it?

again, sorry.

regards,

rev. f50df72

**Comment by Runico** [comment]
confirm, Also disconnect in BG will apply debuff on player

**Comment by Treeston** [comment]
Should kick you from party, shouldn't kick you from raid, and on relog you should still be in the party's instance and have a 60sec timer to be reinvited before you are ported out, to my knowledge.

On current TC you are logged back into a fresh instance and will likely get instagibbed by the spawned mobs.

Agree this is an issue.

**Comment by DDuarte** [comment]
@Treeston: it's not that linear, you do stay in-game for 1 minute, see this "issue" #15162

**Comment by Treeston** [comment]
Depends on the kind of "DC". If it's client kill, yes. If server closes connection, then from my experience no. Either way, logging back into an instance full of mobs is a bug.

**Comment by ccrs** [comment]
yeah, agree @Treeston 

character should spawn on party instance not on new id.

**Comment by Nyeriah** [comment]
Relates to https://github.com/TrinityCore/TrinityCore/issues/6824

It only happens to lfg groups

**Comment by Treeston** [comment]
No. We're seeing this consistently in our pre-formed groups, even if we didn't queue for LFD at all (4-manning deadmines or whatnot).

Someone DCs, relogs, and gets gibbed because they're in a different instance from everyone else (and no longer in the party).

**Comment by iarkoff** [comment]
maybe spawning in dungeon entrance(outside)/(inside, with a 60 seconds timer) instead in the DC location, but still in a "different id", so the player can be reinvited "safely"

i don't remember how this worked on retail, but i don't think it was changed

**Comment by Treeston** [comment]
Retail landed you in your party's ID with a 60 second timer running.

**Comment by ccrs** [comment]
it happens on normal difficulty, that is, instances without permanent save.

**Comment by Ascathor** [comment]
Bump, please state explicit how it's supposed to be. I have an idea how to handle this, but I need confirmation.

**Comment by ccrs** [comment]
AFAIK if character got disconected and its previous group is still in the dungeon it should be added to that group and that instance id.
Also it should keep the group stored (just as permanent save) on server shutdown (if players still are inside the dungeon). Right now if a group is inside a nonpermanent save dungeon and server shutsdown, on next connection each player appears on a new instance id (instead of the previous id).

I think the key part is to keep that "temporal" save for nonpermanent save dungeons.
