### ISSUE TITLE
Death Grip Speed

### ISSUE THREAD

**Issue by Quadral** [TrinityCore/TrinityCore#15565]
Currently the Death Grip speed is slow, and launches the player high in the air and slowly falls back to the Death knight position.

It should grip the player at high speed, without the target being launch into the air first then death gripped back down.

158d6506c907de060184de2b09e4a83239fa1ea1

http://wotlk.openwow.com/spell=49576

**Comment by Keader** [comment]
Confirm

**Comment by Aokromes** [comment]
duplicate.#565
