### ISSUE TITLE
Arena faction bug

### ISSUE THREAD

**Issue by kevinc123** [TrinityCore/TrinityCore#15572]
When 2 teams of same faction enter to arenas, any can't attack, all appear as a friend target.

Example 2 horde vs 2 horde = friend target

2 ali vs 2 horde = work fine

3.3.5a
Using last version of trinity (latest commit 811b557b3b)

**Comment by kevinc123** [comment]
Solved, dbc crashed

**Comment by DDuarte** [comment]
What?

**Comment by tkrokli** [comment]
Uh, that is a weird explanation. Are you absolutely sure about that, or did you mean "DB crashed" ?

**Comment by kevinc123** [comment]
The dbc Areatable.dbc crashed and a lot of cells crashed an shows blank spaces
