### ISSUE TITLE
[6.x] compilation errors

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#15578]
91f2bef235f8ca5aa181db328a0bbb1a1e578f4f

give me compile error I get this
/home/source/wod/TrinityCore/src/server/game/Entities/Taxi/TaxiPathGraph.cpp:26:63: fatal error: boost/property_map/transform_value_property_map.hpp: No such file or directory
compilation terminated.

**Comment by Aokromes** [comment]
Update your boost libs.
