### ISSUE TITLE
"Gurubashi Arena Event" doesn't start at 12AM, 3PM, 6PM, 9PM, 12PM, 3AM, 6AM, 9AM

### ISSUE THREAD

**Issue by unknown-8H3D** [TrinityCore/TrinityCore#15581]
Revision: https://github.com/TrinityCore/TrinityCore/commit/2138726e61f83eea76634372e8cb1b4452e0f84d

Time between events is sometime 2 hours, sometime 3 hours, this makes the event not to start at a correct time (12AM, 3PM, 6PM, 9PM, 12PM, 3AM, 6AM, 9AM).

**Comment by Rushor** [comment]
it's because of the winter/summertimer switch

**Comment by Rushor** [comment]
```sql
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`, `announce`) VALUES (16, '2007-08-05 05:00:00', '2020-12-31 06:00:00', 180, 120, 0, 'Gurubashi Arena Booty Run', 0, 2);
```

times are all correct and the creature npc=14508 run to the button in order to spawn the chest

**Comment by tkrokli** [comment]
Just to make the script a bit more complete, in case the user wants to run it twice:
```sql
DELETE FROM `game_event` WHERE `eventEntry` = 16 AND `holiday` = 0;
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`, `announce`) VALUES
(16, '2007-08-05 05:00:00', '2020-12-31 06:00:00', 180, 120, 0, 'Gurubashi Arena Booty Run', 0, 2);

**Comment by ConradBunton** [comment]
With command ".event stop 16" and ".event start 16", the npc go to spawn the crate but he makes it only one time. I must repeat the commands if I wanna see the NPC go again.
