### ISSUE TITLE
[3.3.5] Boss/Script: Gyth Upper Black Rock

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15583]
http://www.wowhead.com/npc=10339/gyth
rev. a513abc02c65
If Gyth is killed without reaching 5% hp Rend will not spawm and the encounter will stuck.
the problem is here: https://github.com/TrinityCore/TrinityCore/blob/60159297f2cb9b493da8577292daa6a6d2afa5be/src/server/scripts/EasternKingdoms/BlackrockSpire/boss_gyth.cpp#L82

**Comment by DDuarte** [comment]
Should Gyth stay alive a bit at 1 HP?

**Comment by Killyana** [comment]
Not sure, but this can fix the problem.

**Comment by tkrokli** [comment]
Looking at the online player comments, this issue existed on Blizzard's live servers in 2008, 2009, 2010:
http://www.wowhead.com/npc=10339/gyth#comments:id=537074
***
By Smadronia (11,311 – 1·20·91) on 2008/12/30 (Patch 3.0.3)
Be careful when you kill this guy, if you kill him too quickly, Rend won't spawn, and the gates won't open.
***
This is also mentioned in comments from patch 3.3.2 and 3.3.5.

By the way, Gyth was removed in 6.0.2, so this would be a 3.3.5-specific issue (if it is an issue).

**Comment by MrSmite** [comment]
Personally, I don't think this is a bug. This is a gating mechanism Blizzard used to keep people from burning through the encounter.

From my experience on retail, you had to fight through the waves of adds and wait until the Gyth spawned where you then had one tank grab Rend and another grab Gyth. The raid would finish off Rend and then focus down Gyth.

Without this the encounter becomes trivial because you can burn Rend down, skipping all the adds.

**Comment by tkrokli** [comment]
Similar issue where it is too easy to kill an elite 60+ dragon as a level 70+ well geared player:
"the ancient drake" Emberstrife, found in the Wyrmbog in Dustwallow Marsh:
http://www.wowhead.com/npc=10321/emberstrife#comments:id=74518
http://www.wowhead.com/npc=10321/emberstrife#comments:id=180633
http://www.wowhead.com/quest=4743/seal-of-ascension

In 2009 I accidentally killed Emberstrife 2 times in a row while trying to complete "Seal of Ascension".

**Comment by Shauren** [comment]
This is a bug but its blizzlike bug - it also applies to 6.x version too (the npcs have different names but encounter is pretty much the same - starts mounted and dismounts at certain % health, I personally managed to bug this out on retail by killing the mount too quick http://www.wowhead.com/npc=79912/commander-tharbek *there is a comment stating that he respawns but that was not the case for me, had to leave the dungone)

**Comment by Rushor** [comment]
so closing? :D

**Comment by Killyana** [comment]
We can just add invincibility on 5% on spawn, once amount of hp reached summon the boss and remove the invincibility.

**Comment by L30m4nc3r** [comment]
bump :facepunch:

**Comment by tkrokli** [comment]
@Killyana : I sort of agree with your suggestion, but I think it is a "workaround" more than a bugfix
(ref. Shauren's comment about this bug being blizzlike).

**Comment by Rushor** [comment]
more proof for this http://de.wowhead.com/npc=10339/gyth#comments:id=537074

i would close this issue

**Comment by Aokromes** [comment]
With the new guids system this bug is still valid?

**Comment by Rushor** [comment]
according to http://www.wowhead.com/npc=10339/gyth#comments:id=537074 we will close this, because it's a blizzlike issue

> By Smadronia (13,773 – 1·21·117) on 2008/12/30 (Patch 3.0.3)		
> Be careful when you kill this guy, if you kill him too quickly, Rend won't spawn, and the gates won't open.

**Comment by Killyana** [comment]
So why you fixed it here: https://github.com/dalaranwow/dalaran-wow/issues/90 ?

**Comment by L30m4nc3r** [comment]
ugly arrives @Rushor

**Comment by Laintime** [comment]
@Rushor maybe past you change?

**Comment by offl** [comment]
Just change his invincibility on `Reset()` and remove invincibility after `SummonedRend = true;`

**Comment by Ba4ka** [comment]
hmm, removed if (!UpdateVictim()) after SummonedRend = true; ,and        

 ``` void Reset() override
      {
            Initialize();
            events.Reset();
      } 
?

**Comment by Ba4ka** [comment]
no't help

**Comment by Ba4ka** [comment]
@offl help,no't work(

**Comment by offl** [comment]
Check how invincibility works for SAI. https://github.com/TrinityCore/TrinityCore/blob/7d00ae40458fe4399ca414c79a9b0a88b863267a/src/server/game/AI/SmartScripts/SmartAI.cpp#L626-L635

**Comment by Laintime** [comment]
@offl what for? I do not understand

**Comment by offl** [comment]
@Laintime my comment above was for Ba4ka :)
About your question:
> why this change?It's work correctly,killed boss locked door

> If Gyth is killed without reaching 5% hp Rend will not spawт and the encounter will stuck.

**Comment by Ba4ka** [comment]
@offl no is valid, rend spawned,one problems closing door

**Comment by Jinnaix** [comment]
[Dead creatures don't cast spells](https://github.com/TrinityCore/TrinityCore/issues/13441) - since the default spawning method is by spell, it can fail when you overshoot the 5% trigger. But even if you control your damage, it sometimes fail.

Blackrockspire has dozens of other issues \ missing stuff \ non blizzlike functionality and the arena encounter is so broken that its laughable to just fix this little "blizzlike problem". As @Killyana mentioned, players get stucked in the arena when this fails. We did the following to make this encounter more or less failsafe for players :

```cpp
        void JustDied(Unit* /*killer*/) override
        {
            if (!SummonedRend) 
            {           
                // Enforcing a Rend spawn even when Gyth is killed in one attack
                me->SummonCreature(NPC_WARCHIEF_REND_BLACKHAND, me->GetPosition(), TEMPSUMMON_DEAD_DESPAWN); // Rend Blackhand
                SummonedRend = true;
            }
            instance->SetBossState(DATA_GYTH, DONE);
        }
```
Anyway - there are other problems following. If you kill Rend too far away from where Nefarius stands, the gates wont open since Nefarius script is controlling them (what might be right or wrong in general, idk). 
Therefore, people can take that snippet as a workaround but a lot of Blackrockspire needs a overhaul/rework. 
Might be a good candidate for #24029

**Comment by Rushor** [comment]
Bosses should also be converted to SAI?

**Comment by Aokromes** [comment]
no.

**Comment by Jinnaix** [comment]
Ive talked to my co-admin yesterday.
Apparently he wouldnt do it the same way again since trinity has a better option with 
```cpp
 if (!SummonedRend && HealthBelowPctDamage(5))
``` 
instead of 
```cpp 
if (!SummonedRend && HealthBelowPct(5))
```

**Comment by Rushor** [comment]
custom but this solves all issues:

```c++
void JustDied(Unit* /*killer*/) override
        {
            if (!SummonedRend)
            {
                // Enforcing a Rend spawn even when Gyth is killed in one attack
                me->SummonCreature(NPC_WARCHIEF_REND_BLACKHAND, me->GetPosition(), TEMPSUMMON_DEAD_DESPAWN); // Rend Blackhand
                SummonedRend = true;
            }
            instance->SetBossState(DATA_GYTH, DONE);
            if (GameObject* gate = me->GetMap()->GetGameObject(instance->GetGuidData(GO_PORTCULLIS_ACTIVE)))
                gate->SetGoState(GO_STATE_ACTIVE);
            if(GameObject* gateboss = me->GetMap()->GetGameObject(instance->GetGuidData(GO_PORTCULLIS_TOBOSSROOMS)))
                gateboss->SetGoState(GO_STATE_ACTIVE);
        }
```

**Comment by Killyana** [comment]
This will open the gates when Gyth is killed, but it must be done when Rend is killed

**Comment by LEO33SoFo** [comment]
The issue still exists as of 9d959123e68020a83c780f53a967b3589cb70786.
Any progress yet?

**Comment by jackpoz** [comment]
If the issue was in retail, why do we even have to fix it ? It's by-design
