### ISSUE TITLE
Pandaren Faction Choosing 6.x

### ISSUE THREAD

**Issue by spuresz** [TrinityCore/TrinityCore#15597]
Pandaren Faction Choosing does not work

**Comment by Treeston** [comment]
Please specify your core revision etc.

```sql
SELECT * FROM version;
```
will show this, in addition to the core displaying it in console right after startup.

**Comment by spuresz** [comment]
Fresh
https://www.youtube.com/watch?v=U2SJDGz1iwY
Spirit of Master Shang XI npc

**Comment by MitchesD** [comment]
Wandering Isle isn't scripted yet, I don't know how many issues people have to create before they will understand, try to search for some issues about that zone at first.

**Comment by spuresz** [comment]
Okay, sorry!
