### ISSUE TITLE
[Crash] ObjectAccessor::AddCorpse

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15593]
I just had this crashlog.

http://pastebin.com/FsE45RXv

a3dbb0dd9caa1af61ff4e313ef1b75a98c17e30b
3.3.5

**Comment by Aokromes** [comment]
No rows, useless crashlog.

**Comment by Pirricli** [comment]
ummm... it's on debug mod like others... I don't know the reasons...

**Comment by DDuarte** [comment]
This might be related to the guid PR by rooty.
The crashlog is not *that* useless since there's only two asserts in `AddCorpse`, still it would be better if the log was more complete.

**Comment by pete318** [comment]
Just for completeness. Here's how it should have looked.

http://pastebin.com/qyw9giDy

**Comment by shenhuyong** [comment]
confirmed

**Comment by Shauren** [comment]
Fixed in cd27fd38b93884797c094a82dc7beb0498e2f124 (TODO: port to 3.3.5)
