### ISSUE TITLE
Gobjects not seen

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15598]
Hi, I'll try to explain how to reproduce the problem.

1. Log with a GM account.
2. Try to put a Gobject with him.
3. The info says that it's there but with an incorrect guid and you can't see it.
4. Restart the worlserver and you'll see.

a3dbb0dd9caa1af61ff4e313ef1b75a98c17e30b
3.3.5

**Comment by Killyana** [comment]
What are you using to spawn the gob?

**Comment by Pirricli** [comment]
I tried with trinitygmhelper and with command .gob add

**Comment by Killyana** [comment]
gob ID?

**Comment by Pirricli** [comment]
gob add 182567 for example

**Comment by Killyana** [comment]
Confirm, and with gob add temp 182567 the object is visible.

**Comment by Pirricli** [comment]
If you use god add temp you can't target it then.

**Comment by fvicaria** [comment]
Can anyone confirm the object can be seen now. I tried just now and still cant see it with ".gobject add" only with ".gobject add temp"
Maybe I am doing something wrong.

**Comment by Pirricli** [comment]
What commit are you using? For me works perfect now.

**Comment by fvicaria** [comment]
Yes it is. My fault.
