### ISSUE TITLE
[3.3.5] AH: Reuse Practice locks

### ISSUE THREAD

**Issue by M-Pan** [TrinityCore/TrinityCore#15592]
Placing a Practice Lock in the Auction House allows the lock to be reused when the item leaves the AH (Buy, Return, Cancel).

Core: 02d014c69d53 (3.3.5)
DB: TDB 335.59

**Comment by dr-j** [comment]
http://wowwiki.wikia.com/wiki/Practice_Lock

Ye seems used practice locks are allowed to be sold on ah but potential buyers should be told by ah if lock has been opened or not.

"On September 2, 2007, Blizzard patched-in support for the auction house telling potential buyers whether practice locks have been opened or not. Previous to this, unscrupulous players could auction their used practice locks to be bought by unsuspecting players. "

**Comment by M-Pan** [comment]
Personally I see no problems with practice locks not being allowed in the AH at all (easier from a coding view?) except for the Blizzlike factor.

**Comment by Faq** [comment]
Guessing this lock status in AH should also be for all boxes where required lockpicking? [Boxes](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=lockbox)

**Comment by Shauren** [comment]
Unfixable - this is bugged in the 3.3.5 client, even if you send the unlocked flag client ignores it for tooltips of auction items
