### ISSUE TITLE
[3.3.5] SQL fix dump

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15599]
3.3.5, 2c16edbdf32c21cd79fd1ccfc52ecf215683b6ac, TDB 335.59

Did a reset on our world DB today, and finally got around to figuring out which of the local SQL fixes that had accumulated over the weeks are still not fixed in current TDB. Dumping these here. Some of these may not be up to TDB standards. Do whatever you'd like with them, all I'm doing is pointing out these don't work as intended.

[Mistwhisper Lightning Cloud](http://www.wowhead.com/npc=28253) and [Released Soul](http://www.wowhead.com/npc=30736) are both quest visual gimmicks and should thus be immune to everything and unselectable.
```sql
UPDATE `creature_template` SET `unit_flags`=33555200 WHERE `entry` IN (28253,30736);
```

All three Death Gates for [The Air Stands Still](http://www.wowhead.com/quest=13125) shouldn't be targetable (visual gimmicks).
```sql
UPDATE `creature_template` SET `unit_flags`=34121728 WHERE `entry` IN (30850,30852,30841);
```

[En'kilah Blood Globe](http://www.wowhead.com/npc=25534)s are walking around and attacking people. That shouldn't happen.
```sql
UPDATE `creature_template` SET `unit_flags`=131076 WHERE `entry`=25534;
```

[Emanciated Mammoth Bull](http://www.wowhead.com/npc=26271) in Dragonblight is not attackable for no particular reason.
```sql
UPDATE `creature_template` SET `unit_flags`=32768 WHERE `entry`=26271;
```

[Azure Scalebane](http://www.wowhead.com/npc=31402) in Crystalsong Forest is unselectable and unattackable for no particular reason.
```sql
UPDATE `creature_template` SET `unit_flags`=512 WHERE `entry`=31402;
```

[Val'kyr Arbiter](http://www.wowhead.com/npc=30501) is a NPC that spectates your fight for the quest [Revenge for the Vargul](http://www.wowhead.com/quest=13059). It shouldn't be attackable.
```sql
UPDATE `creature_template` SET `unit_flags`=256 WHERE `entry`=30501;
```

Both [Nerubian Cocoon](http://www.wowhead.com/npc=28413) (which is, well, a cocoon) and [Blightblood Troll](http://www.wowhead.com/npc=28931) (which is mind controlled for the final fight against Drakuru) shouldn't aggro players.
```sql
UPDATE `creature_template` SET `flags_extra`=2 WHERE `entry` IN (28413,28931);
```

**Comment by Treeston** [comment]
Also of note, #7683 is still broken as of current TDB, but has had a working fix available for a fairly long time.

**Comment by MrSmite** [comment]
@Treeston Nice, thanks for sharing.

**Comment by tkrokli** [comment]
Thanks for commenting on #7683 . I looked up that very issue a few weeks ago, but couldn't quite make out why it is marked as [Feedback-PatchFix] since I don't know when (labels added, but not logged) and yet it has not been followed up much or added to the source. Is that issue page for #7683 bugged? Or do you see any good reasons why the suggested fix on that page should not be accepted?

**Comment by Killyana** [comment]
Not only unit_flags are missing but also some scripts, I will try to fix them: WIP
``` sql
UPDATE `creature_template` SET `unit_flags`=33555200 WHERE `entry`=28253;

**Comment by Killyana** [comment]
Fixed here: https://github.com/TrinityCore/TrinityCore/commit/610fab8968e1a19b76ff40c331bc6d6d9ecc33fc
