### ISSUE TITLE
crash on exec comand

### ISSUE THREAD

**Issue by c0per0** [TrinityCore/TrinityCore#15606]
in rev 747a3f1d38abdb9b711877c168243f0d398b615f after exec any command in game or in console the result is crash, its fresh compile, and db, onli updates from world.

http://pastebin.com/ECP7VtJR

**Comment by Aokromes** [comment]
Compile on REAL debug mode.
Also, cannot reproduce, you have localized commands?

**Comment by c0per0** [comment]
only trinity database, don't install any localization, later put another crash report, but compile with flag -DCMAKE_BUILD_TYPE=Debug, try a fresh recompile.

**Comment by c0per0** [comment]
solved, its de host, in other server works perfect,
