### ISSUE TITLE
DB/Gossip: Salanar the Horseman, constant gossip option

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15603]
TrinityCore rev. 3f24853e29c2 2015-09-25 22:51:42 +0200 (3.3.5 branch) (Win64, Release)

![salanar_gossip_quest_itros](https://cloud.githubusercontent.com/assets/4903600/10115715/483dc25e-6413-11e5-9423-27006dd4b6e1.png)
http://www.wowhead.com/npc=28653/salanar-the-horseman
http://wotlk.openwow.com/npc=28653 (DK Quest giver NPC)
http://www.wowhead.com/quest=12687/into-the-realm-of-shadows

```sql
SELECT * FROM `gossip_menu_option` WHERE `menu_id` = 9739;
```
```
menu_id      id  option_icon  option_text                                      OptionBroadcastTextID  option_id  npc_option_npcflag  action_menu_id  action_poi_id  box_coded  box_money  box_text  BoxBroadcastTextID
-------  ------  -----------  -----------------------------------------------  ---------------------  ---------  ------------------  --------------  -------------  ---------  ---------  --------  ------------------
   9739       0            0  Salanar, I must return to the Realm of Shadows.                  28863          1                   1               0              0          0          0                             0
```

Salanar the Horseman in Scarlet Enclave/Death's Breach is constantly showing the gossip menu option `Salanar, I must return to the Realm of Shadows.` in all his gossip windows. This option is not supposed to show unless you have taken quest 12687, "Into the Realm of Shadows".

Suggested SQL / DB fix to be inserted in the `conditions` table:
```sql
-- Gossip: Salanar the Horseman / Into the Realm of Shadows
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=9739 AND `ConditionValue1`=12687;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15,9739,0,0,0,9,0,12687,0,0,0,0,0,'','Salanar the Horseman - on gossip select - Show gossip option only if player has accepted quest 12687, but not completed it.'),
(15,9739,1,0,0,9,0,12687,0,0,0,0,0,'','Salanar the Horseman - on gossip select - Show gossip option only if player has accepted quest 12687, but not completed it.');
```
Notice that I have based the 2 lines of values above on an already existing condition "Show gossip option only if player has taken quest 5247 but not complete", but I don't know if both of the lines are needed. This is my first attempt to suggest a solution based on conditions, suggested corrections are welcome.

Notice also that `gossip_menu_option`.`menu_id` 9739 does not work at all, neither with Quest 12687 accepted nor without it. I would have suggested a solution for that too, but I don't know how to connect a spell to `gossip_menu_option`.`action_menu_id` (it should probably be posted as a separate issue).

**Comment by MrSmite** [comment]
I think this would require a script. 

For example, take a look at *Sayge* (14822), the fortune teller from the Darkmoon Faire. After clicking through a bunch of options he will cast a buff spell on the player.

His `gossip_menu` and `gossip_menu_option` don't indicate any spells however he does have *npc_sayge* listed in his `creature_template`.`ScriptName`

**Comment by tkrokli** [comment]
Thanks for the tip. I found the script `npc_sayge ` in /src/server/scripts/World/npcs_special.cpp -- so it is a C++ script.  I think I will wait and see if Killyana has any suggestions before I try to write a C++ script.

**Comment by Killyana** [comment]
You just need this for the condition :
And of course a cpp to cast the spell on gossip select.
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=9739 AND `ConditionValue1`=12687;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15,9739,0,0,0,9,0,12687,0,0,0,0,0,'','Salanar the Horseman - on gossip select - Show gossip option only if player has accepted quest 12687, but not completed it.');

**Comment by Pitcrawler** [comment]
This can be easily done in SAI. Just have him cast http://www.wowhead.com/spell=52359 and close gossip on gossip option selected.

**Comment by CreshandKesh** [comment]
Maybe this can help
``` cpp
bool OnGossipSelect(Player* player, Creature* /*creature*/, uint32 /*sender*/, uint32 /*action*/) override
{
    if(player->GetQuestStatus(12687) == QUEST_STATUS_INCOMPLETE)
    {
        player->CLOSE_GOSSIP_MENU();
        player->CastSpell(player, SPELL_REALM_OF_SHADOWS, false);
    }
    return true;
}
```

**Comment by tkrokli** [comment]
Thanks for the tip, I guess that code belongs somewhere in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L728-L807
I'm slightly uncertain about exactly where to place it, but I'll try and see if I can make it work.

Another thing I have noticed about that same quest, http://www.wowhead.com/quest=12687/into-the-realm-of-shadows, is that the level 55 version of Salanar the Horseman, NPC entry 28788, does not say his speech part before overtaking the stolen horse. The event just dismounts the player and removes the aura `REALM_OF_SHADOWS`, returning the player to the normal view. If I make a PR for the gossip_menu_item and spell, I might as well find a way to make him say his lines before he takes the horse and removes the aura too, since it would need to be inside the script `npc_salanar_the_horseman`.

Anyway, I am testing your suggestion first:
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index b37d505..c056edc 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -773,8 +773,18 @@ public:
                 }
             }
         }
 
+        bool OnGossipSelect(Player* player, Creature* /*creature*/, uint32 /*sender*/, uint32 /*action*/) override
+        {
+            if(player->GetQuestStatus(12687) == QUEST_STATUS_INCOMPLETE)
+            {
+                player->CLOSE_GOSSIP_MENU();
+                player->CastSpell(player, SPELL_REALM_OF_SHADOWS, false);
+            }
+            return true;
+        }
+
         void MoveInLineOfSight(Unit* who) override
         {
             ScriptedAI::MoveInLineOfSight(who);

**Comment by MrSmite** [comment]
> player->GetQuestStatus(12687)

Shouldn't the quest ID be defined instead of hard coded:

>  *QUEST_INTO_REALM_OF_SHADOWS=12687;*

**Comment by CreshandKesh** [comment]
``` diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index eeb8bd9..1d5ae4a 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -729,8 +729,10 @@ class npc_dark_rider_of_acherus : public CreatureScript
 ## npc_salanar_the_horseman
 ######*/
 
-enum Spells_Salanar
+enum SalanarTheHorseMan
 {
+    SALANAR_SAY                       = 0,
+    QUEST_INTO_REALMS_OF_SHADOWS      = 12687,
     SPELL_REALM_OF_SHADOWS            = 52693,
     SPELL_EFFECT_STOLEN_HORSE         = 52263,
     SPELL_DELIVER_STOLEN_HORSE        = 52264,
@@ -747,6 +749,16 @@ public:
     {
         return new npc_salanar_the_horsemanAI(creature);
     }
+    
+    bool OnGossipSelect(Player* player, Creature* creature, uint32 /*sender*/, uint32 /*action*/) override
+    {
+        if(player->GetQuestStatus(QUEST_INTO_REALMS_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)
+        {
+            player->CLOSE_GOSSIP_MENU();
+            player->CastSpell(player, SPELL_REALM_OF_SHADOWS, false);
+        }
+        return true;
+    }
 
     struct npc_salanar_the_horsemanAI : public ScriptedAI
     {
@@ -765,6 +777,7 @@ public:
                             charmer->RemoveAurasDueToSpell(SPELL_EFFECT_STOLEN_HORSE);
                             caster->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
                             caster->setFaction(35);
+                            Talk(SALANAR_SAY);
                             DoCast(caster, SPELL_CALL_DARK_RIDER, true);
                             if (Creature* Dark_Rider = me->FindNearestCreature(28654, 15))
                                 ENSURE_AI(npc_dark_rider_of_acherus::npc_dark_rider_of_acherusAI, Dark_Rider->AI())->InitDespawnHorse(caster);
@@ -785,9 +798,9 @@ public:
                     if (Player* player = charmer->ToPlayer())
                     {
                         // for quest Into the Realm of Shadows(12687)
-                        if (me->GetEntry() == 28788 && player->GetQuestStatus(12687) == QUEST_STATUS_INCOMPLETE)
+                        if (me->GetEntry() == 28788 && player->GetQuestStatus(QUEST_INTO_REALMS_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)
                         {
-                            player->GroupEventHappens(12687, me);
+                            player->GroupEventHappens(QUEST_INTO_REALMS_OF_SHADOWS, me);
                             charmer->RemoveAurasDueToSpell(SPELL_EFFECT_OVERTAKE);
                             if (Creature* creature = who->ToCreature())
                             {

```
Text:
``` sql
-- Salanar text
SET @ENTRY := 28788;
DELETE FROM creature_text WHERE entry = @ENTRY;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES 
(@ENTRY,0,0,'Impressive, death knight. Return to me in the world of the living for your reward.',12,0,100,0,0,28835,0,0,'Salanar the Horseman');
```

**Comment by tkrokli** [comment]
@MrSmite : Maybe that is true now, but it certainly doesn't seem like it used to be so. If you look at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L787-L790, you will see that it is not defined like you suggested.

@CreshandKesh : :+1: Thanks a lot for the update, very nice. I'll test it soon and see how it works.

@Pitcrawler : suggested SAI from m3 in #trinity, just a draft: http://pastebin.com/BWFVNgTv
```sql
-- SAI for quest 12687 (into-the-realm-of-shadow) - Salanar the horseman
SET @SALANAR := 28653;
SET @GOSSIP := 9739;
 
DELETE FROM `smart_scripts` WHERE `entryorguid`=@SALANAR AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(@SALANAR, 0, 0, 10, 62, 0, 100, 0, @GOSSIP, 1, 0, 0, 11, 52359, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Salanar the horseman - On Gossip Select - Cast Spell Realm of Shadows');

**Comment by Pitcrawler** [comment]
Well, I didn't notice he already had a cpp script. So it's best to add the gossip script to it like suggested above.

**Comment by MrSmite** [comment]
@tkrokli : I only suggested it because in the past when I've copied existing code I was asked to change it because there's no point in perpetuating bad coding style ;)

@CreshandKesh Thanks for the update

**Comment by tkrokli** [comment]
OK, so now I have tested the suggested patch from @CreshandKesh with some minor additions to improve on the coding style where [[NPC 28788]](http://wotlk.openwow.com/npc=28788) and [[quest ID 12687]](http://wotlk.openwow.com/quest=12687) was directly referred to with DB entry instead of being enumerated at the start of the script. [`SPELL_REALM_OF_SHADOWS`](http://wotlk.openwow.com/spell=52693) is now properly cast upon selecting the gossip option `Salanar, I must return to the Realm of Shadows.` .
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index b37d505..1b5cd31 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -729,8 +729,12 @@ class npc_dark_rider_of_acherus : public CreatureScript
 ## npc_salanar_the_horseman
 ######*/
 
-enum Spells_Salanar
+enum SalanarTheHorseMan
 {
+    SALANAR_SAY                       = 0,
+    QUEST_INTO_REALM_OF_SHADOWS       = 12687,
+    DARK_RIDER_OF_ACHERUS             = 28654,
+    SALANAR_IN_REALM_OF_SHADOWS       = 28788,
     SPELL_REALM_OF_SHADOWS            = 52693,
     SPELL_EFFECT_STOLEN_HORSE         = 52263,
     SPELL_DELIVER_STOLEN_HORSE        = 52264,
@@ -747,6 +751,16 @@ public:
     {
         return new npc_salanar_the_horsemanAI(creature);
     }
+    
+    bool OnGossipSelect(Player* player, Creature* creature, uint32 /*sender*/, uint32 /*action*/) override
+    {
+        if(player->GetQuestStatus(QUEST_INTO_REALM_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)
+        {
+            player->CLOSE_GOSSIP_MENU();
+            player->CastSpell(player, SPELL_REALM_OF_SHADOWS, false);
+        }
+        return true;
+    }
 
     struct npc_salanar_the_horsemanAI : public ScriptedAI
     {
@@ -765,8 +779,9 @@ public:
                             charmer->RemoveAurasDueToSpell(SPELL_EFFECT_STOLEN_HORSE);
                             caster->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
                             caster->setFaction(35);
+                            Talk(SALANAR_SAY);
                             DoCast(caster, SPELL_CALL_DARK_RIDER, true);
-                            if (Creature* Dark_Rider = me->FindNearestCreature(28654, 15))
+                            if (Creature* Dark_Rider = me->FindNearestCreature(DARK_RIDER_OF_ACHERUS, 15))
                                 ENSURE_AI(npc_dark_rider_of_acherus::npc_dark_rider_of_acherusAI, Dark_Rider->AI())->InitDespawnHorse(caster);
                         }
                     }
@@ -784,10 +799,9 @@ public:
                 {
                     if (Player* player = charmer->ToPlayer())
                     {
-                        // for quest Into the Realm of Shadows(12687)
-                        if (me->GetEntry() == 28788 && player->GetQuestStatus(12687) == QUEST_STATUS_INCOMPLETE)
+                        if (me->GetEntry() == SALANAR_IN_REALM_OF_SHADOWS && player->GetQuestStatus(QUEST_INTO_REALM_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)
                         {
-                            player->GroupEventHappens(12687, me);
+                            player->GroupEventHappens(QUEST_INTO_REALM_OF_SHADOWS, me);
                             charmer->RemoveAurasDueToSpell(SPELL_EFFECT_OVERTAKE);
                             if (Creature* creature = who->ToCreature())
                             {
```
```sql
-- Salanar the Horseman (NPC 28788) say line in Realm of Shadows
SET @ENTRY := 28788;
DELETE FROM `creature_text` WHERE `entry` = @ENTRY;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES 
(@ENTRY,0,0,'Impressive, death knight. Return to me in the world of the living for your reward.',12,0,100,0,0,0,28835,0,'SALANAR_SAY');

-- Salanar the Horseman (NPC 28653) conditions for the gossip_menu_option to be shown for Into the Realm of Shadows
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=9739 AND `ConditionValue1`=12687;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15,9739,0,0,0,9,0,12687,0,0,0,0,0,'','Salanar the Horseman - on gossip select - Show gossip option only if player has accepted quest 12687, but not completed it.');
```
However, [[Salanar the Horseman]](http://wotlk.openwow.com/npc=28788) does not say anything upon delivery of the [[Acherus Deathcharger]](http://wotlk.openwow.com/npc=28302) (sub-issue unchanged), have I made any changes that I shouldn't have in the core script?

**Comment by CreshandKesh** [comment]
@tkrokli, Try moving :
``` cpp
Talk(SALANAR_SAY, player);
```
 below this line https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L789

**Comment by MrSmite** [comment]
@tkrokli Shouldn't it be

> TALK_SALANAR_SAY = 28835

You mentioned in your description that is the ID for his broadcast text but in your code you define it as 0.

**Comment by MrSmite** [comment]
@tkrokli 

> Talk(SALANAR_SAY);

Try adding a target and see if it works.

**Comment by tkrokli** [comment]
@CreshandKesh : Thank you for the updated suggestion. I did try to copy it there _in addition to_ keeping it in your original line as well and also adding it to 2 more lines (though I have removed that info now because it did not seem to make any difference). I will test your new suggestion, to move it as just 1 insert (instead of using it in 3 or 4 lines) and see if that is where I went wrong.

@MrSmite :
> In CreatureTextMgr::SendChat(), without a target, the creature uses itself as a target. I don't know if this is correct or not but it seems strange that a creature would say something to itself.

Now that is an interesting thought. I wonder if that is why the /say lines appears from the player char instead of the NPC, both in the quest event [[The Endless Hunger]](http://wotlk.openwow.com/quest=12848) (quest 4 from the start) where the player targets the NPC and says lines like [[`Sate your hunger on cold steel, $r!`]](https://github.com/TrinityCore/TrinityCore/issues/14700#issuecomment-122730744) as well as the quest [[Death's Challenge]](http://www.wowhead.com/quest=12733/deaths-challenge) where the player says [[`You don\'t stand a chance, $n.`]](https://github.com/TrinityCore/TrinityCore/issues/14700#issue-76613779) and [[`Remember this day, $n, for it is the day that you will be thoroughly owned.`]](https://github.com/TrinityCore/TrinityCore/issues/14700#issue-76613779) (which should be said by the NPC) because it is apparently not possible for the player char to look up any NPC race info. This text should be filled in correctly when used in the opposite direction, said by the NPC while targeting the player char.

**Comment by tkrokli** [comment]
Sorry, no luck with any of your suggestions for where to put the line or how any of the 3 alternatives.
```cpp
Talk(SALANAR_SAY);
Talk(SALANAR_SAY, player);
Talk(SALANAR_SAY, charmer);
```
But I think I have discovered why this doesn't work (or what is missing for it to work). None of the scripts in src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp refer to the built-in spells used to [summon NPC 28788](http://wotlk.openwow.com/spell=52363) [(Salanar the Horseman)](http://wotlk.openwow.com/npc=28788). They seem to be used for the previous quest, GTP.

[[`SPELL_EFFECT_STOLEN_HORSE`]](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L735) (http://wotlk.openwow.com/spell=52263) belongs to [[Grand Theft Palomino]](http://wotlk.openwow.com/quest=12680)
Spell name: [[Stolen Horse]. Description: You've got the horse, now get it back to Salanar!](http://wotlk.openwow.com/spell=52263) (check spell icon)

[[`SPELL_DELIVER_STOLEN_HORSE`]](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L736) (http://wotlk.openwow.com/spell=52264) Delivers the stolen horse to Salanar. Must be within 5 yards of Salanar to activate. Effect 2: 28767 => http://wotlk.openwow.com/npc=28767 => [Phase 1] Havenshrie Horse Credit, Step 01 => Objective of [[Grand Theft Palomino]](http://wotlk.openwow.com/quest=12680)

[[`SPELL_CALL_DARK_RIDER`]](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L737) (http://wotlk.openwow.com/spell=52266) is used  to summon [[NPC 28654, Dark Rider of Acherus (56)]](http://wotlk.openwow.com/npc=28654), not [NPC 28788, Salanar the Horseman (55)](http://wotlk.openwow.com/npc=28788)

[[`SPELL_EFFECT_OVERTAKE`]](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L738) (http://wotlk.openwow.com/spell=52349, Overtake) is triggered by http://wotlk.openwow.com/spell=52350, Overtake (Use to overtake the Acherus Deathcharger once you have slain the Dark Rider of Acherus.)

Looking only at the spell enumerations (enums), it feels like the script stops halfway into the followup quest, [[Into the Realm of Shadows]](http://wotlk.openwow.com/quest=12687). Maybe we should add spells and script for the actual delivery?
- Horseman's Call (http://wotlk.openwow.com/spell=52362) - used by: [[Acherus Deathcharger]](http://wotlk.openwow.com/npc=28782)
- Call Salanar (http://wotlk.openwow.com/spell=52363) - triggered by: [[Horseman's Call ]](http://wotlk.openwow.com/spell=52362)

Even so, it looks like these spells are already cast by the vehicle when clicking the toolbar button [1], but we are still stuck with NPC 28788 who does not react until the vehicle reaches 0 (zero) distance to the NPC, where he dismounts the player and removes aura 52693, [[Realm of Shadows]](http://wotlk.openwow.com/spell=52693)

I am going to test moving the say line down to this section to see if anything useful happens:
```cpp
        void MoveInLineOfSight(Unit* who) override
        {
            ScriptedAI::MoveInLineOfSight(who);

            if (who->GetTypeId() == TYPEID_UNIT && who->IsVehicle() && me->IsWithinDistInMap(who, 15.0f))
            {
                if (Unit* charmer = who->GetCharmer())
                {
                    if (Player* player = charmer->ToPlayer())
                    {
                        if (me->GetEntry() == SALANAR_IN_REALM_OF_SHADOWS && player->GetQuestStatus(QUEST_INTO_REALM_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)
                        {
                            player->GroupEventHappens(QUEST_INTO_REALM_OF_SHADOWS, me);
                            Talk(SALANAR_SAY, charmer);
                            charmer->RemoveAurasDueToSpell(SPELL_EFFECT_OVERTAKE);
                            if (Creature* creature = who->ToCreature())
                            {
                                creature->DespawnOrUnsummon();
                                //creature->Respawn(true);
                            }
                        }

                        if (player->HasAura(SPELL_REALM_OF_SHADOWS))
                            player->RemoveAurasDueToSpell(SPELL_REALM_OF_SHADOWS);
                    }
                }
            }
        }

**Comment by Nyeriah** [comment]
Target should only be used if there's any parser ($n, $c, $r etc) for it in the text. It doesn't seem like there is any parser on it on the text provided.

**Comment by Nyeriah** [comment]
If the text you're trying to make him say is

```(@ENTRY,0,0,'Impressive, death knight. Return to me in the world of the living for your reward.',12,0,100,0,0,28835,0,0,'Salanar the Horseman');```

Then don't provide a target. Target should only be provided if there's any parser to receive it ($n, $c, $r etc).

**Comment by tkrokli** [comment]
Thanks, I will test that. Although when I changed the end value in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L781,
```cpp
if (who->GetTypeId() == TYPEID_UNIT && who->IsVehicle() && me->IsWithinDistInMap(who, 5.0f))
```
from `5.0f` to `15.0f` , it caused the player char to be dismounted immediately upon pressing the toolbar spell button and the say text appeared in the chat window (but no animation took place, maybe because of no wait time between the say command and the despawn action). Is there a general command to delay an action inside a script, or does it need `switch` and `case` like in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L666-L700 ?

**Comment by tkrokli** [comment]
```sql
SELECT `entry`,`name`,`gossip_menu_id`,`minlevel`,`maxlevel`,`exp`,`npcflag`,`speed_run`,`unit_flags`,`ScriptName`,`VerifiedBuild` FROM `creature_template` WHERE `name`= 'Salanar the Horseman';
```
```
 entry  name                  gossip_menu_id  minlevel  maxlevel     exp  npcflag  speed_run  unit_flags  ScriptName                VerifiedBuild
------  --------------------  --------------  --------  --------  ------  -------  ---------  ----------  ------------------------  -------------
 28653  Salanar the Horseman            9739        80        80       2        3    1.19048       32768  npc_salanar_the_horseman          12340
 28788  Salanar the Horseman               0        55        55       0        0    1.14286           0  npc_salanar_the_horseman          12340
 28908  Salanar the Horseman            9751        80        80       2        1    1.38571       32768                                    12340
```

Both NPC entry 28788 and NPC entry 28653 share the script `npc_salanar_the_horseman`. I don't think this is a good solution for 2 separate NPCs. Wouldn't it be better to let them have separate scripts?

@Pitcrawler : Maybe a SAI could be a better solution to have a separate script for ["Realm of Shadows" Salanar the Horseman (entry 28788)](http://wotlk.openwow.com/npc=28788) and keep the core script for [quest giver Salanar the Horseman, entry 28653 (lvl 80 elite)](http://wotlk.openwow.com/npc=28653). I will try to make one for the event where [NPC 28788](http://wotlk.openwow.com/npc=28788) walks up to the player character, pauses and says his text, before he dismounts the player and removes aura 52693.
Or am I making it too complicated? Do you have any useful tips to point me in the right direction? :)

**Comment by MrSmite** [comment]
> Both NPC entry 28788 and NPC entry 28653 share the script npc_salanar_the_horseman. I don't think this is a good solution for 2 separate NPCs. Wouldn't it be better to let them have separate scripts?

Depends how the script is written. If written properly, it can look at the NPC (*switch()*) and do one thing for 28788 and another for 28653.

**Comment by tkrokli** [comment]
OK, thanks for the feedback.
Maybe I am being overzealous with this attempt to make NPC 28788 say his line before throwing the player back out of the Realm of Shadows. Maybe I should just leave it for a different issue and just be happy with creating a PR for making the gossip_option work in-game and add the `conditions` line.
That is an actual improvement in itself, when looking back at my original post at the top of this page. :smirk:

**Comment by Killyana** [comment]
I think thins check is not required as there's already a condition on the DB:
``` cpp
&& player->GetQuestStatus(QUEST_INTO_REALM_OF_SHADOWS) == QUEST_STATUS_INCOMPLETE)

**Comment by tkrokli** [comment]
OK, thanks for the suggestion. I will test it tomorrow night, when I'm back from other activities. :+1:
