### ISSUE TITLE
Ubuntu 15.04 x64 Applying update "2015_08_26_00_characters_335.sql" 'C7D6A3A'... failing

### ISSUE THREAD

**Issue by rdubler** [TrinityCore/TrinityCore#15601]
I pulled a fresh CORE (3f24853e29c20c5a67394a76de2acb1a8b484018), downloaded TDB (TDB_full_335.59_2015_07_14), and built entire project as per your directions.  Everything works except the character DB. 

TDB Data:
 extracted entire TDB_full to server/bin
 files in server/bin: 
    ''characters_2015_03_21_2015_07_15.sql''
    ''TDB_full_world_335.59_2015_07_14.sql''
    ''world_2015_03_21_2015_07_15.sql''

 I get the following output:

'''wow@remo-MS-7851:~/server/bin$ ./worldserver 
TrinityCore rev. 3f24853e29c2 2015-09-25 22:51:42 +0200 (3.3.5 branch) (Unix, Release) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/wow/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.1f 6 Jan 2014 (library: OpenSSL 1.0.1f 6 Jan 2014)
Using Boost version: 1.55.0
Could not connect to MySQL database at 10.0.1.51: Unknown database 'characters'
Database "characters" does not exist, do you want to create it? [yes (default) / no]: 
yes
Creating database "characters"...
Warning: Using a password on the command line interface can be insecure.
Done.
Database Character is empty, auto populating it...
>> Applying '/home/wow/TrinityCore/sql/base/characters_database.sql'...
Warning: Using a password on the command line interface can be insecure.
>> Done!
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 7 archived updates.
Updating Character database...
>> Applying update "2015_08_26_00_characters_335.sql" 'C7D6A3A'...
Warning: Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 2: Unknown column 'corpseGuid' in 'field list'
Applying of file '/home/wow/TrinityCore/sql/updates/characters/2015_08_26_00_characters_335.sql' to database 'characters' failed! If you are an user pull the latest revision from the repository. If you are a developer fix your sql query.
Could not update the Character database, see log for details.
'''

**Comment by thetourist** [comment]
Confirmed if doing a clean install this comes up as an issue:
/* SQL Error (1054): Unknown column 'corpseGuid' in 'field list' */

If you haven't had the previous table structure, then this query fails - perhaps a if not exists check on the corpseGuid column. My MySQL is a little rusty.

**Comment by ccrs** [comment]
maybe use a procedure to check for that column before the query

**Comment by DDuarte** [comment]
It has been fixed in e5e2b093d20cda27ff4a24e82deed980d15ab523

**Comment by rdubler** [comment]
Thank you for dealing with this.
