### ISSUE TITLE
[3.3.5] Inaccessible Nodes

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#15607]
Build: https://github.com/TrinityCore/TrinityCore/commit/747a3f1d38abdb9b711877c168243f0d398b615f

How to acquire number:
1. Stand close to node that isn't accessible (can find such nodes with the map tracker)
2. Type ".gobj near"
3. Get the numbers in a similar format below, and copy/paste (with the help of an addon such as [Prat 3.0](http://www.wowace.com/addons/prat-3-0/files/8825-3-3-26/)) or retype here.

**Redridge Mountains**
5236 (Entry: 1731) - [Copper Vein X:-9195.000000 Y:-2439.000000 Z:78.889000 MapId:0]
1537 (Entry: 1618) - [Peacebloom X:-9142.000000 Y:-2509.000000 Z:118.872002 MapId:0]
1740 (Entry: 1618) - [Peacebloom X:-9599.000000 Y:-1903.000000 Z:61.005001 MapId:0]
1374 (Entry: 1618) - [Peacebloom X:-9746.000000 Y:-1772.000000 Z:52.665001 MapId:0]

**Comment by Killyana** [comment]
I don't think we can fix this, spawns are from sniffs if they are Inaccessible so it must be the case on retail.

**Comment by Rushor** [comment]
so blizzlike issue? but i remember several cases where we changed the spawnposition of gos manually

**Comment by offl** [comment]
There was a method to spawn objects with position based on wowhead's coords, in this case the object can be inaccessible.
If this method was used here we can't call those objects sniffed.

**Comment by Aokromes** [comment]
I have seen sometimes un-reachable mobs on retail, never had miner or herb recolecting char, but i also have seen un-reachable archeology nodes on retail, so maybe those nodes where a bug and later fixed.

**Comment by Aokromes** [comment]
BTW, those spawns comes from UDB XD checked one old UDB db i have and they have same coords.
