### ISSUE TITLE
[3.3.5] Imp pet repositions itself after every cast

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15600]
**Core:** 747ea7c
**DB:** TDB_full_335.59_2015_07_14 + updates

**Bug:**

The Warlock's pet Imp will reposition itself by 1 to 2 yards closer to the target after every cast. If the target (or Imp) should get within melee range, the Imp will reposition itself one last time 1 to 2 yards backward and then stop.

**Details:**
1. Grab a warlock, summon an Imp, set it to follow and put its Fireball on autocast
2. Aggro a mob, making sure you do enough initial threat that the mob ignores the Imp
3. Move away from your imp by a few yards (within the Imp's Fireball range)
4. Notice that after every Fireball cast, the Imp will reposition itself toward the target by 1 to 2 yards before casting the next Fireball

**Comment by tkrokli** [comment]
Yes, I can confirm this from all of the 3.3.5 cores I used to try to find a solution to stop the imp from going into melee range and do melee attacks when OOM. This is more or less part of the same problem as in #301, although it is not mentioned as such in the original issue.
I suppose it is a partial consequence of the imp going into melee attacks when it runs out of mana.

I guess this behaviour won't change before something is done about imp attacking in melee when OOM.

**Comment by MrSmite** [comment]
The main difference here is that the Imp should not move at all when *not* OOM unless the target goes out of range of the Fireball.

In the other case, when the Imp *is* OOM, it should either follow / stay depending on settings.

**Comment by tkrokli** [comment]
Yes, I agree with you on your conclusion there. I hope someone will suggest a usable solution for it.

**Comment by ccrs** [comment]
add distance to movechas on attack (distance equals to spellrange). thatll solve both problems.

matter here is to find a suitable nonhacky way to do that.

**Comment by tkrokli** [comment]
Yes, that is the problem. All suggestions so far have been dismissed as hacks. Solution unknown.

**Comment by MrSmite** [comment]
IMO the proper way to handle both these issues without resorting to hacks:

__This Issue__

The AI should handle a SPELL_FAILED_RANGE result (or whatever it's called) from Spell::Cast() and tell the pet to reposition. On the next AI update it can try casting again.

__Issue #301 __

The AI should handle a SPELL_NO_MANA result (or whatever it's called) from Spell::Cast() and either have the pet resume following the owner or stay, whichever the case. On the next AI update it can try casting again.

**Comment by Goatform** [comment]
Actually this is issue for every pet. E.g. check Water Elemental (every time when he casted spell he will move forward a bit. If I remember good, on retail pet won't move if he's able to cast from that range.

**Comment by MrSmite** [comment]
> @Goatform  Actually this is issue for every pet. E.g. check Water Elemental (every time when he casted spell he will move forward a bit. If I remember good, on retail pet won't move if he's able to cast from that range

Thanks for the info. I usually do my testing on Hunters and Warlocks ;)

**Comment by ccrs** [comment]
afaik only imp should always stay at cast range even on oom.

devs should decide, but i think the best solution is:
- add a specific script to imp (maybe a general script name, just in case any other creature has the same behaviour)
- set spellrange and oom condition to chase if pet has an active (automatic cast) spell that fulfills some requirements.

**Comment by MrSmite** [comment]
@ccrs 

Some interesting points but after thinking about it further, it seems to even be simpler than that.

1. The melee issue can be handled by failing *DoMeleeAttackIfReady()* if the pet cannot melee
2. The MoveChase() issue can be handled by using data from the autocast spells, as you mention**

** Only drawback here would be if there ever was a case where you had different distance autocast spells. If you always pick the shortest, the long range spell may not work well.

**Comment by Keader** [comment]
same problem with Water Elemental (Mage Frost)

**Comment by ccrs** [comment]
@Keader do u have any sort of list of affected pets?

**Comment by Keader** [comment]
No. What can remember only these two

**Comment by Aokromes** [comment]
2d1ef6b

**Comment by jerbookins** [comment]
Just letting everyone know this is still a problem on rev. 691d52daa9be

**Comment by tkrokli** [comment]
@jerbookins : Please open a new ticket for your issue. When issues get closed with a solution, chances are that something else has caused it than before.

Please also note: When opening a new issue, fill in _all the available sections_ of the issue template, in order for other users and TC devs to spend less time trying to verify your issue.
