### ISSUE TITLE
[3.3.5[ Double Quest complete Message 

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15613]
Core TrinityCore rev. 3f24853e29c2
TDB TDB 335.59 + all updates

Many quest give the text twice (quest complete)
All Escortquests have this Bug and many normal Quests

![wowscrnshot_092715_122046](https://cloud.githubusercontent.com/assets/10637389/10122275/da03b328-6513-11e5-9e3b-6e383b7f13f3.jpg)

**Comment by tkrokli** [comment]
TrinityCore rev. 747a3f1d38ab 2015-09-26 23:40:13 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + all updates up to and including sql/updates/world/2015_09_26_05_world.sql

Confirmed. This issue has been present for more than a couple of months, though I don't remember exactly when it started. Although this could be seen as a cosmetic issue, it is more than just a bit annoying, especially while trying to troubleshoot other issues and making an attempt to solve them.

Has anyone got a more precise info about when this issue first appeared?

**Comment by Tauriella** [comment]
Hmm... i don't think thats a cosmetic issue 
The next issue is:
Escort Quest does not works in a Party only the owner can accept the Quest anyGroup members can't accept the quest :(

**Comment by tkrokli** [comment]
@Tauriella : your quest issue ([5321 The Sleeper Has Awakened](http://wotlk.openwow.com/quest=5321)) not being available to complete in a group, is not related to the double "Quest Complete" message. All quests that complete **and** show a message on the screen, will show a double message, as far as I have seen.

**Comment by Treeston** [comment]
Party accept being broken is an issue,  but unrelated to this one.

**Comment by tkrokli** [comment]
It would be nice to know a bit more about where to look for the root cause of this issue, is there something like a "message handler" in the source and that it could be duplicating the messages without anyone noticing it in the code? Or is it more likely that this bug happens in the same moment as the quest objective is reached/achieved/picked up and that the verification/assertion becomes duplicated?

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14968#issuecomment-137302475 - about the Taunt "Immune" message appearing twice when the spell has 2 effects, would that be a likely cause for quest objective messages to appear twice too, if there is a spell involved in the quest objective?

**Comment by tkrokli** [comment]
Possibly caused by `AreaExploredOrEventHappens` being called twice for some reason, don't know why. Example: the first DK quest, The Emblazoned Runeblade (http://www.wowhead.com/quest=12619/the-emblazoned-runeblade). You will always get a double message from that quest as far as I know.
