### ISSUE TITLE
[3.3.5] Blackout (quest 12154)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15617]
Branch 3.3.5, revision 2c16edbdf32c21cd79fd1ccfc52ecf215683b6ac, TDB 335.59

Bugs with quest [Blackout](http://www.wowhead.com/quest=12154/blackout) make it impossible to complete.

- You can use the provided explosives without needing to be next to the [Dun Argol Power Core](http://www.wowhead.com/quest=12154/blackout).
- Using the explosives on the [Dun Argol Power Core](http://www.wowhead.com/quest=12154/blackout) does not award quest credit.

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=27075;
DELETE FROM `smart_scripts` WHERE `entryorguid`IN (27627) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(27075,0,0,1,8,0,100,0,47935,0,0,0,33,27075,0,0,0,0,0,7,0,0,0,0,0,0,0,"Dun Argol Power Core - On Spellhit  - Credit Kill"),
(27075,0,1,0,61,0,100,0,0,0,0,0,51,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dun Argol Power Core - On Spellhit  - Kill Self");

**Comment by Treeston** [comment]
That fixes the quest credit issue, but does not fix the issue where the explosives can be used anywhere (and don't auto-target the core). Conditions entry missing?

**Comment by Killyana** [comment]
No the condition is only on the effect, you can use the item but it will do nothing if you're not near the 27075, also it auto target the core, I just retest it.
