### ISSUE TITLE
[3.3.5] Breadcrumb quest should not be required for Amphitheater of Anguish

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15614]
Branch 3.3.5, revision 2c16edbdf32c21cd79fd1ccfc52ecf215683b6ac, TDB 335.59

[The Champion's Call!](http://www.wowhead.com/quest=12974) should not be required to start the [Amphitheater of Anguish](http://www.wowhead.com/quest=12932) quest chain.

```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=12932;
```

**Comment by tkrokli** [comment]
Practical / useful information about the quest line and requirements:

**WowPedia, Quest:The Amphitheater of Anguish: Yggdras!**
http://wow.gamepedia.com/Quest:The_Amphitheater_of_Anguish:_Yggdras!#Patches_and_hotfixes
http://wow.gamepedia.com/Quest:The_Amphitheater_of_Anguish:_Yggdras!#Quest_progression

**Wowhead, The Champion's Call!, user comment from 2009/04/05 (Patch 3.0.9) :**
http://www.wowhead.com/quest=12974/the-champions-call#comments:id=665963

**Comment by w5860363** [comment]
Quest chain is
http://www.wowhead.com/quest=12932
1.The Champion's Call!  http://www.wowhead.com/quest=12974
2..The Amphitheater of Anguish: Yggdras! http://www.wowhead.com/quest=12932
3.The Amphitheater of Anguish: Magnataur! http://www.wowhead.com/quest=12933
4.The Amphitheater of Anguish: From Beyond! http://www.wowhead.com/quest=12934
5.The Amphitheater of Anguish: Tuskarrmageddon! http://www.wowhead.com/quest=12935
6.The Amphitheater of Anguish: Korrak the Bloodrager! http://www.wowhead.com/quest=12936
7.The Champion of Anguish http://www.wowhead.com/quest=12948

**Comment by Killyana** [comment]
It's not required but you have to check if it still can be taken if the quest (The Amphitheater of Anguish: Yggdras! http://www.wowhead.com/quest=12932) is rewarded.

**Comment by tkrokli** [comment]
@w5860363 : I don't think you checked my link to wowpedia/gamepedia:
http://wow.gamepedia.com/Quest:The_Amphitheater_of_Anguish:_Yggdras!#Quest_progression

Quest progression:
- [77 G5] The Champion's Call! **(optional)**
- [77 G5] The Amphitheater of Anguish: Yggdras!
- [77 G5] The Amphitheater of Anguish: Magnataur!
- [77 G5] The Amphitheater of Anguish: From Beyond!
- [77 G5] The Amphitheater of Anguish: Tuskarrmageddon!
- [77 G5] The Amphitheater of Anguish: Korrak the Bloodrager!
- [78 G5] The Champion of Anguish

**Comment by Killyana** [comment]
There's 2 versions of [The Amphitheater of Anguish: Yggdras!] one that can be taken once The Champion's Call! rewarded, and another that can be taken if http://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge is rewarded. Of course the player can have access only to one of this 2 quests: ExclusiveGroup=12932 in quest_template_addon

9977 ------> 12954
12974 ----> 12932
