### ISSUE TITLE
[3.3.5] Core/Instance: Ice Block aggro/threat transfer

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15615]
core:https://github.com/TrinityCore/TrinityCore/commit/fcc6ef6b1881196bbcebf5949fe682056b366b46
TDB:59
update:https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/updates/world/2015_09_26_05_world.sql

Ice Block http://www.wowhead.com/spell=45438

Use a spell that will eliminate the current threat, and the monster will attack other targets. For example, water element, even if the pet is fixed to another place

Please forgive me for my English.

**Comment by Treeston** [comment]
Could you describe, step by step, what you are doing to make the bug occur, what happens, and what you expect should happen instead.

**Comment by w5860363** [comment]
@Treeston When spell is used, the monster's target is changed, and the other goal in time is not yet.

**Comment by Treeston** [comment]
When ice block is used, threat is temporarily suppressed, and the mob should chase after the next thing on its threat list.

What behavior are you seeing. Provide screenshots or similar, I can't quite understand what your issue is.

**Comment by w5860363** [comment]
@Treeston The use of threats in an instance can be transferred to a pet, and the pet is set at the instance entrance.

**Comment by Treeston** [comment]
So what you're saying is the mob chases after the pet despite the pet not being on the mob's threat list.

Does this behavior also occur with a second player taking the place of the pet? Does the mob turn back around and chase the mage after ice block is canceled/expires?

**Comment by pete318** [comment]
Inside an instance I would be tempted to agree. I've never tested if that works with pets in TC.

For sure, almost anything inside an instance is fair game once a creature is engaged and without anything on the threat list it should seek out the closest player/pet in range that isn't protected from combat somehow (FD, bubble, etc).

Only once all players have left or are dead (aside from DI and maybe FD and I am not sure about vanish) will the creature reset. Indeed I remember running back into an instance after dying once only to instantly become the target.

So maybe this is the suggestion, that you could leave a pet at the doorway, engage, iceblock, let the boss get most of the way to the pet, pop it off and use the time to mana/health up.

Outside of an instance, I don't know really. It makes sense that this should work both ways. e.g. you set your pet onto a creature, pet dies the creature should then turn to you. And likewise you start fighting and get out of combat for whatever reason the pet should be a logical choice. But, we'd need to seek some proof for this point I reckon.

**Comment by w5860363** [comment]
1-http://s013.radikal.ru/i323/1509/d1/72ce7b3d6e30.jpg

2-http://s017.radikal.ru/i409/1509/01/6671d3020e7e.jpg

3-http://s42.radikal.ru/i097/1509/82/e7770845dc17.jpg

4-http://s020.radikal.ru/i712/1509/21/6fb91599e1c4.jpg

**Comment by w5860363** [comment]
@pete318 Even if pet did not take part in the battle

**Comment by Treeston** [comment]
Raid trash shouldn't pulse the entire zone into combat, I don't think.

**Comment by pete318** [comment]
Yeah have to say not 100% sure about trash,

As for normally. I can understand it would make sense for it to be the case that creature is connected to you in that respect. Anyone tried on retail to see how it happens there?

**Comment by Keader** [comment]
IDK if npcs should attack another targets in this case...
I remember in Siege of Orgrimmar Heroic, in secound boss, the mage in my core using iceblock for "tank" some corrupted pandas brust. After iceblock, panda still attack him...

**Comment by Treeston** [comment]
Block should work like bubble. Mobs ignore immune targets if there are other targets available (thread suppressed).

**Comment by ariel-** [comment]
Still valid after threat rewrite? @Treeston

**Comment by Treeston** [comment]
no
