### ISSUE TITLE
[3.3.5a] Coren Direbrew is not spawned

### ISSUE THREAD

**Issue by digz6666** [TrinityCore/TrinityCore#15611]
Coren Direbrew is not spawned when doing RDF to Blackrock Depths.
NPC: http://www.wowhead.com/npc=23872/coren-direbrew

![coren](https://cloud.githubusercontent.com/assets/1736110/10121656/a89a476e-6529-11e5-9204-65155f6c6b97.jpg)

Revision: 747a3f1d38abdb9b711877c168243f0d398b615f

**Comment by Aokromes** [comment]
Like i said on the closed ticket, duplicate bug of a generic bug.

**Comment by digz6666** [comment]
@Aokromes can you point the issue link of generic bug?
