### ISSUE TITLE
Hunter automatik attack

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#15623]
core 513b756ea8afcfeb65b97e8227669681e9cd9a40
db the latest 3.3.5

Der Hunter kommt nicht aus sein automatischen Angriff, egal was man macht (esc oder ähnliches), einzigste Abhilfe ist nur das man sich einmal aus und wieder einloggt.
gestetet auf ein Level 13 hunter.

Hunter comes not the automatic Attack.
must Login/Logoff to go out of this.
testet on an Level 13 hunter.

**Comment by Rushor** [comment]
was meinst du mit "automatischen Angriff" ? etwas das attackemote, bei dem der hunter den bogen spannt?

what do you mean with "automatic Attack" ? do you mean the attackemote?

**Comment by genion18** [comment]
Jap, man hat ja die Funktion des automatischen Angriff (der dann rot blinkt) und der bleibt dauerhaft (greift alles was man im ziel nimmt automatisch an) und kann man auch nicht mehr deaktivieren, egal was man auch drückt. Auch nicht so Besonders wenn man ein Tier zähmen will und es schon tod ist bevor man es zähmen kann.

yes, the funktion AutoAttack is for ever (esc or others makes not) and attack all mobs of the world then in Target. This is not so Good when Charm Animal and the animal is death thit autoattack.

sorry for my bad english

**Comment by Rushor** [comment]
maybe caused by https://github.com/TrinityCore/TrinityCore/issues/14460 or sth similar from https://github.com/TrinityCore/TrinityCore/search?q=hunter+auto+attack&type=Issues&utf8=%E2%9C%93
