### ISSUE TITLE
[3.3.5] send mail command delivers to deleted characters when name already exists

### ISSUE THREAD

**Issue by Yehonal** [TrinityCore/TrinityCore#15626]
3.3.5 branch
hash e5e2b093d20cda27ff4a24e82deed980d15ab523

https://github.com/TrinityCore/TrinityCore/blob/cd27fd38b93884797c094a82dc7beb0498e2f124/src/server/game/Chat/Chat.cpp#L1002

ObjectMgr::GetPlayerGUIDByName(name)

this function has no filter on "archive" account, this causes .send mail command to deliver mails to deleted chars when characters name of receiver is the same of another in archive account.

I can add this filter, but is it valid for all use of GetPlayerGUIDByName? is it used to search inside archive account?

Maybe we should create a separated function to use for send mail

**Comment by Shauren** [comment]
Deleting characters in "archive" mode clears `name` field in `characters` table
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/database/Database/Implementation/CharacterDatabase.cpp#L426
^ The above statement means that ObjectMgr::GetPlayerGUIDByName querying the database by name will not find the deleted player
