### ISSUE TITLE
[6.x] Shaman cannot wear Mail 

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#15621]
http://prntscr.com/8leeai
Shaman cannot wear Mail even after level 40
Rev: https://github.com/TrinityCore/TrinityCore/commit/3bc3b67a8fae059e1019446b09882dfa7fcd11a0

**Comment by Aokromes** [comment]
#15391

**Comment by dejonxavier** [comment]
thanks!
