### ISSUE TITLE
[Crash] Player::LoadFromDB

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15633]
Recently I had this crashlog.

http://pastebin.com/fH4QtigW

fcc6ef6b1881196bbcebf5949fe682056b366b46
3.3.5

**Comment by shenhuyong** [comment]
Comfirmed 
3.3.5
70a5cdfc04f510d39af5ea050757f33804ae7723

**Comment by Carbenium** [comment]
@shenhuyong : Crashlog or nothing happened.

**Comment by Shauren** [comment]
note for debugging: Player logged out/in on the gunship inside ICC

**Comment by jackpoz** [comment]
https://gist.github.com/jackpoz/80c03fa078cad41ae4a2 valgrind log

**Comment by pete318** [comment]
Just for useful information. Steps to reproduce are as follows:

* Set config option Instance.UnloadDelay = 1
* Enter ICC, kill first 2 bosses and head to ~~Lootship~~ Gunship.
* Start event and as soon as ship starts to move logout.
* Wait a second, map will unload.
* log back in and observe the crashed worldserver.

Issue is that transport object is unloaded but pointer remains in hashmap and old guid is stored in player record. Hence it finds the old guid in the hashmap pointing to invalid memory area.
