### ISSUE TITLE
Mounted NPC aggreoes, but mount does not aggro

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15635]
3.3.5, 2c16edbdf32c21cd79fd1ccfc52ecf215683b6ac, TDB 335.59

Going near [Brunnhildar Warmaiden](http://www.wowhead.com/npc=29498/brunnhildar-warmaiden) will aggro it, but the [Brunnhildar Warbear](http://www.wowhead.com/npc=29500/brunnhildar-warbear) it is mounted on will not aggro. This leaves the Warmaiden unable to chase or attack the player, and also prevents it from ever resetting, putting the player permanently in combat.

**Comment by Killyana** [comment]
Vehicles without SAI are passive.
