### ISSUE TITLE
[6.x] Linux there are no crash logs

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#15639]
even with debugging no crash logs i understand this isnt a forum but someone keeps deleting my posts

REV: https://github.com/TrinityCore/TrinityCore/commit/8745e08be020471db886e11a3a7512a751141562

**Comment by Rochet2** [comment]
Did you try this?
https://github.com/TrinityCore/TrinityCore/tree/6.x/contrib/debugger
