### ISSUE TITLE
[6.x] Segmentation Fault

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#15649]
http://pastebin.com/CS9RKA4G

my tables are up-todate
REV: https://github.com/TrinityCore/TrinityCore/commit/fd17ea16431e0831be058ac1bbd7c37574d3c2e6

**Comment by tkrokli** [comment]
http://pastebin.com/raw.php?i=CS9RKA4G
Those console messages are mostly DBerror messages, they don't tell directly why your core crashed.
The usual request from the developers is that you compile in debug mode and provide a full crash log.

**Comment by dejonxavier** [comment]
well i fixed my problem wasnted using the updated configs!
