### ISSUE TITLE
[335] Auctionhouse uses wrong origin for mail

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15644]
__Core:__ https://github.com/TrinityCore/TrinityCore/commit/747ea7ca2c2b757dc9c5a672746d801a8365ee98
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

When you receive mail from buying out an auction, the origin house uses the place the auction was created instead of where the player bought from

__Details:__

* Create an auction in Stormwind
* Buy the auction in Darnassus
* Result: Your mail will be from the *Stormwind Auctionhouse*
* Expected: Your mail should be from the *Darnassus Auctionhouse* since that is where you "purchased" the item

__Note:__

This is mainly cosmetic and possibly difficult to verify correct behavior since retail (WoD) now [combines](http://wowwiki.wikia.com/wiki/Auction_House#cite_note-officialMergedAHWarlords-0) all the auctionhouses of a given faction.

**Comment by pete318** [comment]
Since https://github.com/TrinityCore/TrinityCore/commit/01ae5c4bf6bce7e2a9a0621eb8edcf0197bc3d2c it should always use "Alliance", "Horde" or "blackwater"  as sender for mails.

**Comment by tkrokli** [comment]
TrinityCore rev. 1dcf186dfd24 2015-09-30 22:31:00 +0200 (3.3.5 branch) (Win64, Release) / TDB 335.59

Yes, the sender is **Alliance Auction House** for both payment and sold goods now. :+1:

**Comment by pete318** [comment]
There's actually a lot changed "under the hood" for auctions in that commit. But, that should be the only real difference players will experience.

**Comment by pete318** [comment]
Anyway, closed by 01ae5c4bf6bce7e2a9a0621eb8edcf0197bc3d2c so closing this one for now.

**Comment by MrSmite** [comment]
Except the auctionhouse wasn't combined until WoD so for 335 they should still remain separate.

http://wow.gamepedia.com/Auction_House#Patch_changes
WoD Patch 6.0.2 (2014-10-14): Items listed for sale on the Alliance, Horde, and neutral auction houses have now been combined together on a per-realm basis.

**Comment by MrSmite** [comment]
Cool, thanks. I thought that was a WoD thing but it looks like in WoD they actually combined the factions together.

**Comment by pete318** [comment]
Yeah, WoD there is one AH to rule them all. From BC (and maybe a certain vanilla patch, I am not sure) they merged faction AHs. So there were essentially 3 AHs.

I'm not completely 100% that they always sent mails from "Alliance Auction House" and "Horde Auction House". But I DO have screenshots from BC of my mailbox with only mails from "Horde Auction House". I'm fairly sure they moved them all to that naming system.
