### ISSUE TITLE
[3.3.5]Wrong edge/height calculation.

### ISSUE THREAD

**Issue by Stefan226** [TrinityCore/TrinityCore#15656]
revision : 70a5cdfc04f5

![wowscrnshot_100415_023505](https://cloud.githubusercontent.com/assets/9408050/10265881/dbdeaa12-6a41-11e5-876c-6a193dadb908.jpg)

![wowscrnshot_100415_023616](https://cloud.githubusercontent.com/assets/9408050/10265873/7094d074-6a41-11e5-9a8a-a680af0967e8.jpg)

As you can see NPC can walk through fence and can climb on tree. I am new to pathfinding so if you guys can leave some comments on where to start, I've been looking at the code for few hours but still not really sure where to start.

**Comment by Aokromes** [comment]
Blizzlike xD

**Comment by Stefan226** [comment]
xD , I would like to start working on it but where to start :P

**Comment by StormBytePP** [comment]
If it's blizzlike as @Aokromes says, it will never be changed despite it seems wrong, as that's the intended behavior, the only question here, is that if that path comes from sniff or not. But again, if it comes from sniff, it will be untouched.

**Comment by MrSmite** [comment]
Strange, after looking at the first picture I've never seen a wolf path to the stairs in the abbey. There shouldn't wolves between Deputy Willem and the abbey or the vendors.

**Comment by jackpoz** [comment]
aren't wolves supposed to be able to get over fences on retail too ?

**Comment by Stefan226** [comment]
Shouldn't be. They are not walking over it on Warmane's Lordaeron btw.

**Comment by jackpoz** [comment]
what happens when they are chasing a player in elwynn forest ?

**Comment by Shauren** [comment]
@Stefan226 what happens on privete servers is absolutely irrelevant to us.

**Comment by Stefan226** [comment]
They are using TrinityCore

**Comment by Stefan226** [comment]
@jackpoz Not sure what you mean? Elwynn forest is a huge zone.. For example 
![screenshot_1](https://cloud.githubusercontent.com/assets/9408050/10269192/bebdb4da-6acf-11e5-9844-c2fba0b80066.jpg)

For example when you kite them around this pillar it's ok.. Path is working, and it's working in general but has sometimes weird calculations.

(I know that screenshot is Cata but that doesn't matter, can't login now to take screenshot in game).

**Comment by jackpoz** [comment]
> As you can see NPC can walk through fence
> aren't wolves supposed to be able to get over fences on retail too ?
> what happens when they are chasing a player in elwynn forest ?

@Stefan226 pretty clear the topic is wolves walking over fences so the retail behavior should be compared to tc one

**Comment by Goatform** [comment]
No, this isn't blizzlike at all. Pathing shouldn't work like that. Even charge pathing is working like that and it cause a lot of troubles such as #11526 and because of it sometimes player will fall underground because objects and ground are actually empty inside. It's not possible to reproduce that with NPC since they will simply ignore some part of object and fly over that empty space so they won't fall underground. I explained that on #11526 with picture and symbols.

**Comment by Stefan226** [comment]
@jackpoz  It's not just wolves. Every NPC acts like that.

**Comment by Goatform** [comment]
Exactly. As I said above, even players have that trouble just it's a bit different.

**Comment by jackpoz** [comment]
@Goatform this GitHub issue is not about charge, it's about npcs walking on fences/trees

**Comment by Goatform** [comment]
You didn't understood me correct.

**Comment by jackpoz** [comment]
and you didn't understood this issue either . Maybe https://github.com/TrinityCore/TrinityCore/commit/93a68a66c3009ea86569076ea05a39ce87dfb78d can help you understand it

**Comment by Frytiks** [comment]
Personally, i think TC have too much now behavior with fences and high climbs. Personally i reverted this commit.

**Comment by Stefan226** [comment]
Solved with reverting to 93a68a6 values.

Going to test this approach even more and give feedback!

Thanks guys.

**Comment by MrSmite** [comment]
@Stefan226 The OP mentioned 335 in the title but the screen you posted is not from a 335 Northshire. It might get a little confusing discussing broken features of a newer core in a report about broken features in an older core, even if they are the same feature.

@jackpoz I looked on youtube for a while but couldn't find anyone being chased by wolves in 335. I know the humanoid NPCs should hop the fence but not sure about animals. It would make sense that they could but with blizz, who knows... ;)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/9965 is an issue about wolves NOT jumping over fences, this #15656 is an issue about wolves jumping over fences. lol.

**Comment by pete318** [comment]
Well @jackpoz clearly Trinity should be implementing observer effect and uncertainty principle within the code!

**Comment by Aokromes** [comment]
https://onedrive.live.com/redir.aspx?cid=83725776ab2e4745&resid=83725776AB2E4745!1434&parId=83725776AB2E4745!143&authkey=!AKkhOw_ZFkunE_U&ithint=video%2cmp4

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/93a68a66c3009ea86569076ea05a39ce87dfb78d shows anyway what to change to change the mmaps behavior, parameters are commented and there are even images showing the different behaviors.
https://github.com/jackpoz/recastnavigation can also be used to load .mmtiles and see the result.
