### ISSUE TITLE
[3.3.5] gm_ticket.closedBy has wrong value when closed by console

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#15655]
Branch: 3.3.5
Tested on revisions: ba009ea2e2d13c0aa8a76df5bfead6f757ccddc3, 774ea0b4bd1e

When you close a ticket via **console** using ```ticket close``` command, the ```gm_ticket.closedBy``` field value of that ticket is **16777215**.

According to the wiki, it should be **-1** instead.

**Comment by pete318** [comment]
Yep, the reason being that -1 is treated as uint64 (which doesn't matter but we'll get to what happens next). So it becomes binary 64x1's to represent -1 (or for uint64 2^64-1). Which, for SQL would still become -1.

Where it all goes wrong is being treated as a guid. Having a high guid of 0xFFFF means it doesn't match any in the case list. So, by default is is given the answer true to HasEntry().

Later, when writing the value to the database, it calls GetCounter() to get the guid for the player. Here, if HasEntry is true, it's ANDed with 0xFFFFFF meaning what was 0xFFFFFFFFFFFFFFFF, then was trimmed to 0XFFFFFFFF (lowguid), was further trimmed to 0xFFFFFF. This 16777215 (2^24-1).

There's numerous solutions to the problem. But I wonder if just using player GUID 0 wouldn't be better overall? ObjectGuid(HighGuid::Player, uint32(0)). AH Bot uses that, and just put the same checks for 0, where currently there is -1 (if there are any checks).

Just a thought.

**Comment by StormBytePP** [comment]
I plan to change this to be NULL, as no real info for userID is taken when closed by console. It is in works in one of my PR which will be commited soon, once I have spare time
