### ISSUE TITLE
[6.x] Auction House Enabled Crashes Server

### ISSUE THREAD

**Issue by dejonxavier** [TrinityCore/TrinityCore#15650]
REV: https://github.com/TrinityCore/TrinityCore/commit/fd17ea16431e0831be058ac1bbd7c37574d3c2e6

Issue: While configuring my new set up i realized that when enabling auction house seller = server crash.

Linux
Ubuntu 15.04
8GB RAM 40GB SSD

**Comment by Rochet2** [comment]
post the config and crashlog
