### ISSUE TITLE
[3.3.5] Recuitment Letter (4992) Item Has Wrong page_text (340)

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#15659]
Build: https://github.com/TrinityCore/TrinityCore/commit/774ea0b4bd1e0d469cfce8013f2e557f030c7c97

http://www.wowhead.com/item=4992/recruitment-letter

In-game, there appears to be a good bit of unnecessary line breaks, and I'm not sure what the "Looks good to me." part is about.

![wowscrnshot_100415_093735](https://cloud.githubusercontent.com/assets/6378956/10268125/d24aa830-6a7c-11e5-8b89-8f9aeedc4412.jpg)

Not entirely sure if this is the correct format to fix it, but:

```
update `page_text` set `Text` = '<HTML>\n<BODY>\n<H1>Horde Conscription Registration</H1>\n<BR></BR>\n<P>This person has demonstrated incredible feats of strength and skill in the name of the Horde. They should immediately be assigned to work in the Crossroads.</P>\n<BR></BR>\n<BR></BR>\n<P>Respectfully yours,</P>\n<BR></BR>\n<P>Takrin Pathseeker</P>\n</BODY>\n</HTML>' where `ID` = 340
```

And in the database, the above fix looks like this:

```
<HTML>
<BODY>
<H1>Horde Conscription Registration</H1>
<BR></BR>
<P>This person has demonstrated incredible feats of strength and skill in the name of the Horde. They should immediately be assigned to work in the Crossroads.</P>
<BR></BR>
<BR></BR>
<P>Respectfully yours,</P>
<BR></BR>
<P>Takrin Pathseeker</P>
</BODY>
</HTML>
```

Instead of:

```
<HTML>
<BODY>
<H1>Horde Conscription Registration</H1>
<BR></BR>
<P>This person has demonstrated incredible feats of strength and skill in the name of the Horde. They should immediately be assigned to work in the Crossroads.</P>
<BR></BR>
<BR></BR>
<P>Respectfully yours:</P>
<BR></BR>
<BR></BR>
<BR></BR>
<BR></BR>
<P>Looks good to me.<BR></BR>
- Takrin Pathseeker</P>
</BODY>
</HTML>
```

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12286

**Comment by Espionage724** [comment]
Ah; took me a good bit to understand where and to who that letter was being addressed to:

* Kargal is the one looking for recruits for someone else and signs-off if the recruit is good enough ("Respectfully yours, (blank))
* Passes the letter to Takrin at some point
* Takrin likes what I've got and send the letter back to Kargal with his approval ("Looks good to me, Takrin"; "Respectfully yours" still blank; this is when I first get the letter)
* I do stuff for Kargal, which gains his approval, then he signs it (Respectfully yours, Kargal"; letter turns to Signed Recruitment Letter), and I pass the letter to the final person (Sergra?, not far enough in the quest to tell for sure)

So if that's correct, then the text as-is currently is fine? Are the line breaks ok? Still seems like there's a good bit of them.

**Comment by tkrokli** [comment]
Yes, the order you have described is correct, [Sergra Darkthorn](http://wotlk.openwow.com/npc=3338) in Crossroads is the final receiver. :)
http://www.wowhead.com/npc=3338/sergra-darkthorn

As for the amount of line breaks and the final line being at the bottom of the document, it is intended.
[Takrin Pathseeker](http://www.wowhead.com/npc=3336/takrin-pathseeker) is only a footman and his signature will only be useful to Kargal Battlescar. I think most of this is fairly well discussed in the issue Aokromes linked (#12286). Unless you have found other undetected problems, I think you can close this issue. The text layout in the letter is Blizzlike.

**Comment by Espionage724** [comment]
Ah, alright I guess if it's blizzlike, there's no issue :p Thanks!
