### ISSUE TITLE
[3.3.5] Dark Storms (806) Quest Has Typo

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#15652]
Build: https://github.com/TrinityCore/TrinityCore/commit/bde599e39ccdcfa76386ea74bd70d172d83c3022

http://www.wowhead.com/quest=806/dark-storms

Progress should be:
> Did you find Fizzle, name?  He, and rest of the Burning Blade, must be scoured from our lands!

There's two "and"s though in the database (quest_request_items):
> Did you find Fizzle, $N? He, and and rest of the Burning Blade, must be scoured from our lands!

I think the below should fix it:

```sql
UPDATE `quest_request_items` SET `CompletionText` = 'Did you find Fizzle, $N? He, and rest of the Burning Blade, must be scoured from our lands!' WHERE `ID` = 806
```

**Comment by tkrokli** [comment]
Thanks for the find, also for pointing out the correct table. :+1:
TDB 335.59 + updates / 774ea0b4bd1e / Confirmed.
```sql
SELECT * FROM `quest_request_items` WERE `ID` = 806;
```
```
    ID  EmoteOnComplete  EmoteOnIncomplete  CompletionText                                                                                   VerifiedBuild  
------  ---------------  -----------------  -----------------------------------------------------------------------------------------------  -------------
   806                1                  0  Did you find Fizzle, $N? He, and and rest of the Burning Blade, must be scoured from our lands!          12340
```
To stay compatible with the TC codestyle, we don't use the DB name in the Query.
Also, don't use apostrophes (' ') around numbers. Remember to end the line with semicolon ( ; ).
```sql
UPDATE `quest_request_items` SET `CompletionText` = 'Did you find Fizzle, $N? He, and rest of the Burning Blade, must be scoured from our lands!' WERE `ID` = 806;
```
Wish Blizzard had cared enough about grammar to put "He, and **the** rest of the Burning Blade," though.

**Comment by Espionage724** [comment]
Thanks for the info; yeah I thought "the" was supposed to be in-place of the 2nd "and" in-game when I read it; was surprised that it wasn't.
