### ISSUE TITLE
[3.3.5] Molten Core: Majordomo Executus : Guards Not Linking

### ISSUE THREAD

**Issue by wrathix** [TrinityCore/TrinityCore#15664]
a87f5fdcdebf7e03c29f6f14b89e8e8398c601e0

You can pull the first group of 4 Elites next to Majordomo without the boss actually agro-ing, making the fight very simple, killing those 4 on their own first.

Same goes for Pulling majordomo afterwards, only 2 of the healers to his left link with him, leaving 2 others behind.

The way this is meant to work is : agro-ing any of the 8 elites or majordomo himself will make everything pull as it should do.
Pull should agro everything like in this video: https://www.youtube.com/watch?v=-8dBZ2stFPg

Some extra issues from this boss I found here:  https://github.com/TrinityCore/TrinityCore/issues/5885

**Comment by Rushor** [comment]
try summon.DoZoneInCombat() in attackstart

**Comment by Killyana** [comment]
Or you can use creature formation to link the Npcs.

**Comment by offl** [comment]
#5885
