### ISSUE TITLE
Server crashed after insert into worldstates

### ISSUE THREAD

**Issue by prestonjamesparsons** [TrinityCore/TrinityCore#15661]
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3752, 7)
 [ERROR]: [1062] Duplicate entry '3752' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3762, 7)
 [ERROR]: [1062] Duplicate entry '3762' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3749, 7)
 [ERROR]: [1062] Duplicate entry '3749' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3751, 7)
 [ERROR]: [1062] Duplicate entry '3751' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3750, 7)
 [ERROR]: [1062] Duplicate entry '3750' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3772, 7)
 [ERROR]: [1062] Duplicate entry '3772' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3767, 7)
 [ERROR]: [1062] Duplicate entry '3767' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3769, 7)
 [ERROR]: [1062] Duplicate entry '3769' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3760, 7)
 [ERROR]: [1062] Duplicate entry '3760' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3761, 7)
 [ERROR]: [1062] Duplicate entry '3761' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3753, 7)
 [ERROR]: [1062] Duplicate entry '3753' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3758, 7)
 [ERROR]: [1062] Duplicate entry '3758' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3766, 7)
 [ERROR]: [1062] Duplicate entry '3766' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3770, 7)
 [ERROR]: [1062] Duplicate entry '3770' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3757, 7)
 [ERROR]: [1062] Duplicate entry '3757' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3755, 7)
 [ERROR]: [1062] Duplicate entry '3755' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3756, 7)
 [ERROR]: [1062] Duplicate entry '3756' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3711, 7)
 [ERROR]: [1062] Duplicate entry '3711' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3713, 7)
 [ERROR]: [1062] Duplicate entry '3713' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3714, 7)
 [ERROR]: [1062] Duplicate entry '3714' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3764, 7)
 [ERROR]: [1062] Duplicate entry '3764' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3712, 7)
 [ERROR]: [1062] Duplicate entry '3712' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3765, 7)
 [ERROR]: [1062] Duplicate entry '3765' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3759, 7)
 [ERROR]: [1062] Duplicate entry '3759' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3754, 7)
 [ERROR]: [1062] Duplicate entry '3754' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3704, 4)
 [ERROR]: [1062] Duplicate entry '3704' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3705, 4)
 [ERROR]: [1062] Duplicate entry '3705' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3771, 7)
 [ERROR]: [1062] Duplicate entry '3771' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3768, 7)
 [ERROR]: [1062] Duplicate entry '3768' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3763, 7)
 [ERROR]: [1062] Duplicate entry '3763' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3706, 4)
 [ERROR]: [1062] Duplicate entry '3706' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3773, 7)
 [ERROR]: [1062] Duplicate entry '3773' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3699, 7)
 [ERROR]: [1062] Duplicate entry '3699' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3703, 4)
 [ERROR]: [1062] Duplicate entry '3703' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3700, 4)
 [ERROR]: [1062] Duplicate entry '3700' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3698, 7)
 [ERROR]: [1062] Duplicate entry '3698' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3702, 4)
 [ERROR]: [1062] Duplicate entry '3702' for key 'PRIMARY'
SQL(p): INSERT INTO worldstates (entry, value) VALUES (3701, 4)
 [ERROR]: [1062] Duplicate entry '3701' for key 'PRIMARY'

Hash: 5fd42e68aeee 3.3.5a TDB 59
I looked that into worldstates but all are there..

**Comment by joschiwald** [comment]
where is the crash?

**Comment by tkrokli** [comment]
@prestonjamesparsons : the reason you get that list of errors when importing those values, is because they are already there. You can't use the `INSERT INTO` command unless you have deleted the existing values first. Also, if you want to make a working insert for all of those values, it should look like this:
```sql
DELETE FROM `worldstates` WHERE `entry` BETWEEN 3698 AND 3706;
DELETE FROM `worldstates` WHERE `entry` BETWEEN 3711 AND 3714;
DELETE FROM `worldstates` WHERE `entry` BETWEEN 3749 AND 3773;
INSERT INTO `worldstates` (`entry`,`value`,`comment`) VALUES
(3698,7,''),
(3699,7,''),
(3700,4,''),
(3701,4,''),
(3702,4,''),
(3703,4,''),
(3704,4,''),
(3705,4,''),
(3706,4,''),
-- skipping 4 entries
(3711,7,''),
(3712,7,''),
(3713,7,''),
(3714,7,''),
-- skipping 35 entries
(3749,7,''),
(3750,7,''),
(3751,7,''),
(3752,7,''),
(3753,7,''),
(3754,7,''),
(3755,7,''),
(3756,7,''),
(3757,7,''),
(3758,7,''),
(3759,7,''),
(3760,7,''),
(3761,7,''),
(3762,7,''),
(3763,7,''),
(3764,7,''),
(3765,7,''),
(3766,7,''),
(3767,7,''),
(3768,7,''),
(3769,7,''),
(3770,7,''),
(3771,7,''),
(3772,7,''),
(3773,7,'');
```
Not sure if your list above is complete, but this is based on your list.

Anyway, your DB/SQL problem should have been posted on the TrinityCore Forum, not here.

**Comment by joschiwald** [comment]
@tkrokli i guess that are wg worldstates which get inserted by the bad wg script

**Comment by tkrokli** [comment]
OK, that means the issue report is incomplete and also, like you say, not straight TC source.

**Comment by prestonjamesparsons** [comment]
Well, i have delete whole Worldstates then open worldserver.exe as it's create them. everything seem fine now
