### ISSUE TITLE
[Core/Pet] Fix for resummoned Pet's

### ISSUE THREAD

**Issue by PaulHellCore** [TrinityCore/TrinityCore#15666]
Hello, I closed commit [ #15074](https://github.com/TrinityCore/TrinityCore/pull/15074#issuecomment-131828975) and tried to solve another a way a resummoned of a pet.

[link to Gist!](https://gist.github.com/PaulHellCore/0526d0eccd63b851b221)

Core https://github.com/TrinityCore/TrinityCore/commit/a87f5fdcdebf7e03c29f6f14b89e8e8398c601e0

**Comment by Killyana** [comment]
Open a Pr please.

**Comment by PaulHellCore** [comment]
[Pull](https://github.com/TrinityCore/TrinityCore/pull/15667)
