### ISSUE TITLE
[CRASH] AddToGrid / Corpse

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#15684]
Rev. 3db4c642877212c1d61881b1faf0cbc9ed170534
Linux x64
Related to corpse?
3.3.5

- http://pastebin.com/NrL29xhA
- http://pastebin.com/DYsMn8e0

Thanks.

**Comment by n4ndo** [comment]
this still give at least 6 crash per day. Any ideas?

**Comment by n4ndo** [comment]
- http://pastebin.com/jUKP8MqZ
- http://pastebin.com/j3uVSatW
- http://pastebin.com/Eh5x8Ps6

**Comment by tkrokli** [comment]
I am uncertain about how to interpret some of the values in the logs, but there are some very high values in there (0x7ffff4469500 / 140737291220736 / 140737282828032). You could be running out of memory, maybe some kind of memory leak? How many players do have on your server?

**Comment by n4ndo** [comment]
@tkrokli i go to check mem values but yes i also believe some kind of mem leak on new corpse system,

- about 2k ppl.

**Comment by jackpoz** [comment]
All crash logs reported have WorldSession::HandlePlayerLogin(), InstanceMap::AddPlayerToMap(), ObjectGridLoader::LoadN() and AddWorldObject<Corpse>() . The crash is actually an assertion triggered

**Comment by n4ndo** [comment]
@jackpoz any ideas? this is crashing even more now, at least 10 crash in last hour.

this crash is with "GridUnload = 1"

- http://pastebin.com/xx906MBF

-

**Comment by tkrokli** [comment]
I still think you are getting a memory issue, but if it is caused by GUIDs being used up, I would suggest updating your core and DB to the newest available, just to be sure.
If you look at the raw paste http://pastebin.com/raw.php?i=xx906MBF and search for the term
`Cannot access memory at address`, you will find 5 entries, one of them looking like this:
```
#22 0x0000000001181f3c in WorldSession::HandlePlayerLogin (this=this@entry=0x7ffec1472780, holder=holder@entry=0x7ffec7181970) at /Desktop/Compiler/Sources/src/server/game/Handlers/CharacterHandler.cpp:892
        playerGuid = <optimized out>
        chH = {_vptr.ChatHandler = 0x18ca070 <vtable for ChatHandler+16>, m_session = 0x7ffec1472780, static load_command_table = false, sentErrorMessage = false}
        data = {<ByteBuffer> = {_vptr.ByteBuffer = 0x18c9330 <vtable for WorldPacket+16>, static DEFAULT_SIZE = 4096, _rpos = 0, _wpos = 8, _storage = std::vector of length 8, capacity 270 = {0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000'}}, m_opcode = 1109}
        stmt = <optimized out>
        pCurrChar = 0x7ffebebfa000
        IP_str = <error reading variable: Cannot access memory at address 0xffffffffffffffe8>
```
`0xffffffffffffffe8` is a quite high memory address, 18446744073709551592 (18,446,744,073,709,551,592), but I don't know exactly how it translates to physical memory.

**Comment by pete318** [comment]
@tkrokli the error is an Assert, and the assert is thrown if the object (in this case a corpse it seems) being added to a grid, already has a valid grid reference (e.g. it's already in a grid).

So I don't think it's a memory issue.

**Comment by tkrokli** [comment]
OK, thanks for setting me straight. I stand corrected. You are the real coder here. Does the amount of players make a difference in this issue, making it less likely to happen with less players on that server?

**Comment by pete318** [comment]
I think the number of players just increases the chance that someone will be doing the something that causes this to fail.

For what it's worth, I think the instance is Trial of the Crusader. My only evidence for this is that when you enter that instance the start co-ords are grid 33, 32 with cell 0,1. Which is the location of all but one of the crash dumps posted.

However, no idea what series of actions in there cause this to happen.

**Comment by jackpoz** [comment]
@pete318 try setting https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/worldserver/worldserver.conf.dist#L854 to a low value and see if it asserts. Possible cases could be:
- player dies inside an instance, logs out while in instance, instance unloads, player logs back in
- player dies inside an instance, releases, instance unloads, player enters the instance
- player dies inside an instance, releases, logs out, instance unloads, player logs in and enters the instance
- repeat with 2 players, mixing the cases

**Comment by pete318** [comment]
@jackpoz I already set that to very low (1) and tried all those cases, plus some more (ressurrect, then ressing player leaves instance, instance unloads and player 2 accepts).

I'm sure it is something along these lines, but didn't find the actual cause.

I also couldn't see anything standing out in the code that would do this. In my opinion one of two things is happening. Either the same corpse is added to the same grid twice, or the same corpse is added to different grids.

**Comment by n4ndo** [comment]
@pete318 i actually disable ToC and no more crashes for the moment.

**Comment by pete318** [comment]
So, it was a good guess. One of the crashes was for another instance. I couldn't see which. I suspect it could happen in any. But something in ToC clearly makes it more likely.

**Comment by sirikfoll** [comment]
Is a commom practice to reset the instance to restore the 50 attempts, maybe this is relevant

**Comment by pete318** [comment]
I'll take a look after dinner. It shouldn't be that, but anything is possible. Also now we have a primary candidate, I'll take a look at the scripting. Hard to believe that could do it. But, who knows?

**Comment by pete318** [comment]
Well. I honestly haven't been able to reproduce it. Mainly my limitation is, 2 logins on same computer only for testing. So, not sure how likely I'd be to find the problem this way.

@n4ndo whoever was the catalyst for this would have been logging into the game, while in ToC (maybe dead, maybe not). It would likely have disconnected them after the loading screen for ToC, without ever porting them in. If we can find out what the state of the instance when they logged out, what their raid had done since etc etc. Maybe the cause can be ascertained. But, randomly testing "around" ToC isn't likely to accidentally find it I'm afraid.

**Comment by EPS1L0N** [comment]
Try:

```diff
 void Corpse::RemoveFromWorld()
 {
     ///- Remove the corpse from the accessor
     if (IsInWorld())
+    {
         GetMap()->GetObjectsStore().Remove<Corpse>(GetGUID());
 
+        if (IsInGrid())
+            RemoveFromGrid();
+    }
+
     WorldObject::RemoveFromWorld();
 }
```

**Comment by n4ndo** [comment]
@pete318 i will try to do some test once i have some free time, but for now ToC remains closed.

**Comment by n4ndo** [comment]
@pete318 @EPS1L0N @jackpoz this is from (Wed Oct 21 21:09:39 to Wed Oct 21 21:22:19)

- http://pastebin.com/m0BPQCKZ
- http://pastebin.com/SCvD3f67
- http://pastebin.com/VLQVjkmZ
- http://pastebin.com/vrKkeaHD
- http://pastebin.com/wR4Jh4A3
- http://pastebin.com/FFahkE1P
- http://pastebin.com/NU6YiP0V

@jackpoz i go to lower the value you suggested and tell later the results.

NOTE Im almost sure this is related to new corpse system since before this changes i was having uptimes up to 3 days.

**Comment by n4ndo** [comment]
More crashes with full debug mode and "Instance.UnloadDelay = 0"

- http://pastebin.com/ppBbXmQ6
- http://pastebin.com/mEqmm1y9
- http://pastebin.com/DHYUPBEK

**Comment by EPS1L0N** [comment]
are u running base TC or do u have any custom code? I've not had this crash even once

**Comment by pete318** [comment]
@n4ndo it'd be expected to increase the occurrence frequency by changing UnloadDelay to a lower value. The bt shows it's happening on Map/Grid load when a player logs in (presumably they log in and were saved in the instance). @jackpoz was suggesting that to me to increase chance to reproduction of the issue.

Mainly what's needed is something that will ensure we can reproduce the problem on demand. For me I've not been able to do it. It could be that it's a combination of actions from multiple players (for which it's hard to me to simulate myself), or as @EPS1L0N  suggests, you have some custom code/scripting for which the recent corpse map, or overall map context changes is interfering.

At this point though, I have insufficient information to say what that is.

**Comment by sirikfoll** [comment]
Could be related #15758

**Comment by mvelasco93** [comment]
GUIDs are too high and a lot of spaces between. (2kk or 3kk created) and maybe 400 players max, don't lie.

**Comment by n4ndo** [comment]
Well, since i know i was having some great uptimes before some commits i try to revert some of them, i start from this:

- 402a3c45ffe65597d9863dce5fb76362795d706a#diff-69c61e2462b8b541822123559cd62d80

I have to say that know is a little more stable and the crash is more readeable.

- http://pastebin.com/zN3gmpEZ
- http://pastebin.com/8b1xz7Mn

**Comment by Shauren** [comment]
Readable? Don't make me laugh. That commit fully changed how corpses are added to maps/grid, any attempt to mix it with old code or plain using old code is completely useless for us.

**Comment by n4ndo** [comment]
@Shauren well, at least is not crashing every 2 minuts.

**Comment by Shauren** [comment]
I still find it very strange that you are the only one with this issue...

**Comment by n4ndo** [comment]
@Shauren well, i belive somebody on my server knows how to crash :/

**Comment by Demonid** [comment]
Shauren, he is not the only one, a server im helping out with 1.4k players was also having lots of crashes about the same stuff, they reverted the corpse commits and related and now it doesn't crash that much, 1 or 2 a day.

**Comment by EPS1L0N** [comment]
> are u running base TC or do u have any custom code? I've not had this crash even once

I'm running 6.x fyi, it's possible (though unlikely) that this crash is restricted to 3.3.5

**Comment by Shauren** [comment]
oh? that might be useful info

**Comment by pete318** [comment]
@EPS1L0N it could be restricted to 3.3.5. But, I think your anecdotal evidence doesn't say too much about this. I'll say why I think that.

So far as we've seen, it's ToC that is the prime culprit. We don't know why yet. But, it's something there. I don't suspect many people are doing ToC on a 6.x server. So, it's not so likely to happen.

I'm interested in what the cause is. But, so far I've spent more than one whole evening trying to reproduce it. So, really don't want to spend any more time on it unless someone can find a lead that I can follow.

**Comment by Shauren** [comment]
Alright, @n4ndo if you could give this patch a try http://paste2.org/v3sAyHs7 
You will need to be running WITH 402a3c45ffe65597d9863dce5fb76362795d706a as this commit is a fix for the crashes you are having (http://pastebin.com/zN3gmpEZ) - they were caused by the large guid scope changes

**Comment by Re3os** [comment]
Confirn http://pastebin.com/bgkhm3wN

**Comment by maxtros** [comment]
I'm using my own forkbased on https://github.com/TrinityCore/TrinityCore/commit/91de0322bba3ef071338ce5a71f512369486eb1f and it seems it still exist on newest rev..

**Comment by maxtros** [comment]
By the way...i'm using 3.3.5 to fork.

**Comment by Naios** [comment]
@Maxtros Modified sources are not supported here, and without a crashlog your "crash" never happened.

**Comment by maxtros** [comment]
@Naios  yes I know are not supported that is why I don't post a crashlogs....but if I'm wrong and It helps...here it's http://pastebin.com/iUEHUz3S ...but it seems even more useless due optimizations :S

**Comment by EPS1L0N** [comment]
that's a different crash
