### ISSUE TITLE
[3.3.5] Trash not despawning on soft reset after boss is killed

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15682]
3.3.5, Rev. 50cf74f0dbe1

After a boss is killed, any trash associated with that boss should despawn after a soft reset of the instance (nobody enters the instance for 30 minutes, raid is disbanded/reformed, or server is restarted). This does not happen.

**Comment by Krudor** [comment]
You are very much correct!
The systems managing raids and dungeons are starting to get outdated and would need a rework somewhere down the line, I might take a look at this after the reverse engineers do their magic with fixing most of the opcodes now that the expansion is coming to a halt.

I should probably make a thread about this somewhere but there should be a new way of handling creature spawns, which this would be related to.

**Comment by w5860363** [comment]
Do you mean with instance, the BOSS of the front of the monster should be gone?
I did not have this problem, in addition to Odul, as if it is because the header file only defines 16 BOSS

**Comment by Treeston** [comment]
1. Find an instance with an optional trash pack (ex.: Naxxramas, Spiderling packs before Anub'rekhan)
2. Kill the boss those trash packs are linked to (ex.: Anub'rekhan)
3. Exit the instance and disband/reform the raid (or: Restart the world server) to force a soft instance reset

Expected behavior:
4. After re-entering the instance, the optional trash pack should be despawned.

Instead:
4. The optional trash pack is still present.

**Comment by MrSmite** [comment]
For reference: http://wowwiki.wikia.com/wiki/Instance_reset

> A soft reset is when all party members leave the instance, and then come back in. This puts people out of combat, making mobs run back to their original places.

> The term "soft reset" can also mean having all party/raid members leave the instance for at least 30 minutes. This causes any trash mobs that have been killed to respawn. The most common reason to do this (deliberately) is to reset a boss fight that bugged out part way through the encounter.

@Treeston 

You're correct about leavng the instance for 30 minutes but I'm not sure a server restart should automatically repop the instance, it just reads from `creature_respawn`. I suppose this could be a CONF option to allow server restarts to immediately repop instance mobs.

**Comment by Keader** [comment]
Mimiron (Ulduar) on Air Phase dont despawn your adds too xD

**Comment by mvelasco93** [comment]
linked_respawn where the leader is the boss?

**Comment by Jinnaix** [comment]
Cant speak for master, but works now for 3.3.5 on rev fb227be9eb53581863a45002a3878566b3c1e22c
If the fixes referenced above are cherry picked for master, this issue can be closed.

Killing all Bosses with linked trash in MC
![image](https://user-images.githubusercontent.com/37972361/91438142-2fd73880-e86b-11ea-8194-75590f1f2e12.png)
Result after Server restart
![image](https://user-images.githubusercontent.com/37972361/91438223-4a111680-e86b-11ea-849a-f97519464b92.png)

Sidenote - the MC Trashlink example from my screenshots doesnt exist yet in TC.

**Comment by offl** [comment]
Are you sure server restart is the same as soft reset, could you please just leave instance for 31 minute after killing boss?

**Comment by Jinnaix** [comment]
Same result, ported back into a clean run after 35 minutes.

**Comment by Jinnaix** [comment]
Sidenote - the "soft reset" also happens on grid unload (default 5 minutes).

**Comment by offl** [comment]
Works even if grid unload = 0
