### ISSUE TITLE
[3.3.5] Arcane Torrent activating incorrectly  Burning Determination

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15693]
When using Arcane Torrent having points on talent Burning Determination, you gain immunity aura of silence for 20 seconds. This should only occur if silence suffered by Arcane Torrent and not to use it.

Arcane Torrent: http://wotlk.openwow.com/spell=28730
Burning Determination: http://wotlk.openwow.com/spell=54749

TC Hash: 30eaf23b6af412a0c876c13b11adda41e7027aa0

**Comment by Keader** [comment]
@ariel- it's is proc system right?

**Comment by ariel-** [comment]
Issue is no longer current as of 343419ab992ca3b8dd93e87e8a16a1ee097447bf. Closing.
