### ISSUE TITLE
[3.3.5] Crash Method

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#15696]
1- Create a Undead
2. Learn 61425
3. .gm on
4. Enter any instance
5. Mount (61425)
6. gm off
7. Log out
8. Log in and move = CRASH

Rev: 361ef5efa394a09e73223c577407bbf2aca13479

**Comment by Vincent-Michael** [comment]
server or client crash?

**Comment by Demonid** [comment]
Server Crash

**Comment by pete318** [comment]
Post debug log if you can. I tried those steps and.. No crash.

Tried in Arathi Basin and Zul'Farrak. Not sure how many others you could mount in to also try it.

**Comment by Demonid** [comment]
I did the testing on Ruby Sanctum, could you try that ?

**Comment by Nyeriah** [comment]
That crash's https://github.com/TrinityCore/TrinityCore/issues/15668#issuecomment-147133868

**Comment by Demonid** [comment]
@pete318 I miss one step, before logging out you must remove gm, so when you log in again, your char will be teleported outside the instance, then move and crash.

**Comment by pete318** [comment]
OK yes, got the crash and I agree with @Nyeriah it is the same cause as https://github.com/TrinityCore/TrinityCore/issues/15668

It's known, and the cause is also known. But no ETA on correction.

**Comment by Nyeriah** [comment]
> @pete318 I miss one step, before logging out you must remove gm, so when you log in again, your char will be teleported outside the instance, then move and crash.

Yeah, confirmed this
