### ISSUE TITLE
[3.3.5a] Quest "Beating Them Back!" showing "140211" as name

### ISSUE THREAD

**Issue by DanielMo1603** [TrinityCore/TrinityCore#15690]
Not sure how it is working on the english clients, however it should be showing this name on the german, french and spanish clients as i can see in the Database. I also wrote an update fix, not sure if it is professional enough, but it does it's job
http://www.wowhead.com/quest=28762/beating-them-back

```sql
UPDATE `locales_quest`
SET `Title_loc2` = "Repoussez-les !", `Title_loc3` = "Schlagt sie zurück!", `Title_loc7` = "¡Rechazar el ataque!", `Title_loc8` = "¡Rechazar el ataque!"
WHERE `Id` = 7
```

rev:https://github.com/TrinityCore/TrinityCore/commit/5529728ab06ddfa895e55380eee075a0a2776c0c

**Comment by Killyana** [comment]
The quest id=7 is deprecated.

**Comment by DanielMo1603** [comment]
Wowhead says deprecated, because the quest exists for every class itself: http://www.wowhead.com/search?q=Beating+Them+Back%21 however, the fix i provided works for me

**Comment by Killyana** [comment]
Yes, but you linked a 6.x revision, this issue is for 3.3.5

**Comment by DanielMo1603** [comment]
Sorry... my fault... i updated it now

**Comment by Killyana** [comment]
The quest title was changed after wotlk:
``` sql
SET `Title_loc2` = "Le nettoyage du camp des kobolds", `Title_loc3` = "Säuberung im Koboldlager", `Title_loc7` = "La Limpieza del Campamento Kóbold", `Title_loc8` = "Связанные местности" WHERE `Id` = 7

**Comment by tkrokli** [comment]
To any developer with write access to the linked 6.x cherry-picks list: This issue & commit does not belong to the 6.x branch, since the quest was replaced in 4.0.3 with the quests "Beating Them Back!" [8].
