### ISSUE TITLE
[Crash] Object::GetGuidValue

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#15700]
Yesterday I had this crashlog.

http://pastebin.com/DmBPRQd4

d028f33ed9c18449b1d4c902c3837b4679374f1f
3.3.5 branch.

**Comment by tkrokli** [comment]
Any description on how to reproduce your crash? Reading the crash log, I see UpdateSoulboundTradeItems, some mentions of Map::Update, MapUpdater and GetGuidValue. Could this have something to do with trading or moving from one map to another or entering/leaving an instance?

**Comment by Pirricli** [comment]
I don't know how to reproduce sorry.
