### ISSUE TITLE
 [3.3.5/ Spell] Mind Soothe has no effect

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15702]
Description Spell: Soothes the target, reducing the range at which it will attack you by 10 yards. Only affects Humanoid targets. Lasts 15 sec.
http://wotlk.openwow.com/spell=453

Problem: With or without the debuff, the target range is not modified.

This spell is very important in pvp.

TC Hash: 30eaf23b6af412a0c876c13b11adda41e7027aa0

**Comment by tkrokli** [comment]
Why did you close this issue? What is wrong with it? A closing comment would be useful to us others.

**Comment by Keader** [comment]
A friend who played in 3.3.5a on blizz told me that spell never worked in players ... working only creatures
