### ISSUE TITLE
object=181597/silithyst-mound, honor farm.

### ISSUE THREAD

**Issue by Voidx** [TrinityCore/TrinityCore#15708]
9b792ec481f378a4b44bffa9b8ad9b4e6e443cad

Ubuntu
video:

https://www.youtube.com/watch?v=dTEvmAvmzzo

**Comment by DDuarte** [comment]
Add a description. I don't want to see a video to know what this issue is about.

**Comment by Killyana** [comment]
Cannot reproduce, also disable gm mode when you make some tests.
