### ISSUE TITLE
[3.3.5] - Bug Icecrown Citadel

### ISSUE THREAD

**Issue by leonardofan157** [TrinityCore/TrinityCore#15713]
rev: 30eaf23
Bug 1: http://prntscr.com/8r1z16
Bug 2: http://prntscr.com/8r22ht

10N
25N
.....

not to speak to the Muradin
Versão: 3.3.5
System: Ubuntu 14.04
Core: 2821c691964f

**Comment by MrSmite** [comment]
Here's some research but I'm not sure which would be the best way to fix it (see below)

```SQL
SELECT * FROM creature_template WHERE `name`='Muradin Bronzebeard';
```

Gives three results:

* ENTRY 36948
 * `ScriptName`=npc_muradin_bronzebeard_igb
 * `gossip_menu_id`=10875
* ENTRY 37200
 * `ScriptName`=npc_muradin_bronzebeard_icc
 * `gossip_menu_id`=10933
* ENTRY 38607
 * `ScriptName`=
 * `gossip_menu_id`=0

...*but*...

```SQL
SELECT * FROM `gossip_menu_option` WHERE `menu_id` IN (10875,10933);
```
Gives only one result for 10875 (the NPC using the **npc_muradin_bronzebeard_igb** script):

* `option_text`=My companions are all accounted for, Muradin. Let's go!

So I'm not sure if that gosip option is on the wrong NPC or if they're both supposed to have that option, or if the wrong NPC is spawned in ICC in the first place.

**Comment by Killyana** [comment]
I made this with joschiwald, there's no issue, the gossip option will be visible once the gunship is done.
