### ISSUE TITLE
[6.x] Quest server crash

### ISSUE THREAD

**Issue by martial69320** [TrinityCore/TrinityCore#15718]
Hi, in Trinitycore Rev: 43f4e32cabc2d9329affda2cdabe0fc735cd849b
There is a quest named Signs of Things to Come: http://www.wowhead.com/quest=28728/signs-of-things-to-come when we talk to NPC, quest make server crash.

**Comment by Killyana** [comment]
I reproduced the crash only the first time when I completed the quest. I tried with other characters but nothing happens.

**Comment by Vincent-Michael** [comment]
pls parse debug crash log

**Comment by Rushor** [comment]
@martial69320: this crash still happens?

**Comment by Aokromes** [comment]
No answer after more than 4 months, closing.
