### ISSUE TITLE
DB/game_tele: name typo in 'OdesyusLanding'

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15725]
TrinityCore rev. 7c0270913926 2015-10-16 20:59:45 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates up to and including `2015_10_16_02_world.sql`.

Minor typo in `game_tele`.`name` for the destination Odesyus' Landing: `OdesyuLanding` ::
```sql
SELECT * FROM `game_tele` WHERE `name` LIKE '%Odesy%';
```
```
    id  position_x  position_y  position_z  orientation     map  name           
------  ----------  ----------  ----------  -----------  ------  -------------
   693    -4677.05    -12439.1     16.2655      2.09541     530  OdesyuLanding
```
Fix:
```sql
UPDATE `game_tele` SET `name` = 'OdesyusLanding' WHERE `id` = 693;

**Comment by WoWShards** [comment]
give that man a cookie (pull it up)

**Comment by tkrokli** [comment]
Hehe, thanks for the support. It is only a minor detail (cosmetic), though. :smile:
