### ISSUE TITLE
[6.x] Ubuntu 14.04 compile error

### ISSUE THREAD

**Issue by WoWShards** [TrinityCore/TrinityCore#15721]
Hello, I freshly installed TC Rev. 105f943ac6bf61535ab259685c87141d169090ef 
I followed all steps in Requirements, here is error output text:

[ 29%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/PetitionsHandler.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [src/server/game/CMakeFiles/game.dir/Entities/Player/Player.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
[ 29%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_druid.cpp.o

**Comment by Aokromes** [comment]
Not tc issue.

**Comment by WoWShards** [comment]
what then?
