### ISSUE TITLE
[3.3.5] A Cry For Help

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15722]
TrinityCore rev. d4f2367c6bfe 2015-10-16 11:16:30 +0200 (HEAD branch)

http://de.wowhead.com/quest=9528/ein-hilferuf

Magwin falls into the water.

![wowscrnshot_101715_141358](https://cloud.githubusercontent.com/assets/10637389/10558835/c12825b6-74de-11e5-8df4-f14f87f811d3.jpg)

**Comment by tkrokli** [comment]
TrinityCore rev. 7c0270913926 2015-10-16 20:59:45 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates up to and including `2015_10_16_02_world.sql`
http://www.wowhead.com/quest=9528/a-cry-for-help
http://www.wowhead.com/npc=17312/magwin
http://www.wowhead.com/npc=17311/cowlen

Confirmed. Magwin falls down into the water just before `Magwin says: Father! Father! You're alive!`

Chat log and `.gps` coordinates:
```
[20:03:16] Magwin says: Father! Father! You're alive!
[20:03:46] Magwin hugs her father.
[20:03:46] Magwin says: You can thank Nirosha for getting me back here safely, father.
[20:03:46] Quest Complete 'A Cry For Help'
[20:04:12] You are outdoors
[20:04:12] Map: 530 (Outland) Zone: 3524 (Azuremyst Isle) Area: 3524 (Azuremyst Isle) Phase: 1
[20:04:12] X: -5351.085938 Y: -11160.536133 Z: -5.967584 Orientation: 1.359874
[20:04:12] grid[21,11]cell[7,0] InstanceID: 0
[20:04:12]  ZoneX: 16.226068 ZoneY: 94.207321
[20:04:12] GroundZ: -6.881653 FloorZ: -6.881653 Have height data (Map: 1 VMap: 1 MMap: 1)
[20:04:12] Liquid level: 0.000000, ground: -6.881653, type: 15, flags 2, status: 8.
```
The quest completes, though, but Magwin never reaches Cowlen before she despawns (2 retries).
At the first retry, she tries the pier again, but on the second retry, she tries to swim out to him.

**Comment by Rushor** [comment]
```c++
void WaypointReached(uint32 waypointId) override
        {
            if (Player* player = GetPlayerForEscort())
            {
                switch (waypointId)
                {
                    case 0:
                        Talk(SAY_START, player);
                        break;
                    case 17:
                        Talk(SAY_PROGRESS, player);
                        break;
                    case 28:
                        Talk(SAY_END1, player);
                        break;
                    case 29:
                        Talk(EMOTE_HUG, player);
                        Talk(SAY_END2, player);
                        player->GroupEventHappens(QUEST_A_CRY_FOR_SAY_HELP, me);
                        break;
                }
            }
        }
``` 

maybe adding some more waypoints would fix this issue

**Comment by joslyn-liu** [comment]
https://github.com/joslyn-liu/ElunaTrinityWotlk/blob/master/sql/Joslyn-liu%20world/2015_11_16_10_joslyn_liu.sql

Fixes this.

It's a water related problem. As you may notice it messed up (for me at least) as soon as she went over the water on the dock.

**Comment by tkrokli** [comment]
@joslyn-liu : to change only 1 value like `InhabitType`, you don't need to do a full `DELETE FROM` / `INSERT INTO` pair. Use `UPDATE` / `SET` instead:
```sql
UPDATE `creature_template` SET `InhabitType` = 1 WHERE `entry` = 17312;
```
... although I think NPCs are supposed to be able to swim. Don't know about this one, though.

**Comment by joslyn-liu** [comment]
@tkrokli  Oh neat, thanks for the info on that!. I've been using delete and insert for years..

I figured this one would be fine with not being able to swim, since she shouldn't ever be actually swimming. 
Seems to work from the quest pickup spot right to the end without issue anyway.

**Comment by tkrokli** [comment]
OK, looks like at least a workaround, then. I agree that this NPC is different from regular ones.
Don't know if TC prefers this solution, though. Have to wait and see if the developers in charge like it.

**Comment by tkrokli** [comment]
TrinityCore rev. 60c8fd4874d0 2015-11-16 22:56:52 +0100 (modify_pet_speed_and_distance branch) (Win64, Release), TDB 335.60 + updates up to and including 2015_11_12_01_world.sql

Tested the database change just now, it works like you said, @joslyn-liu. It makes Magwin walk up to Cowlen and complete the quest. (My hunter pet still falls through the pier and into the water, though.)

Now we need a confirmation if it is usable at all or if it changes a Blizzard value from sniffs in the `creature_template` table.

**Comment by Aokromes** [comment]
If the fix here is valid, plz open a PR.

**Comment by tkrokli** [comment]
No PR needed; the script lines in Rushor's https://github.com/TrinityCore/TrinityCore/issues/15722#issuecomment-150173910 is a direct copy of https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp#L363-L385 and does not make any difference. Replace [Comp-C++Script] with [Comp-Database] and push this **solution**:
```sql
-- Remove InhabitType 2 (Water) from NPC 17312 (Magwin) to make her walk on the pier
UPDATE `creature_template` SET `InhabitType` = 1 WHERE `entry` = 17312;
```
Tested on rev. dc67505a081f 2016-05-26 21:23:59 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_05_26_09_world.sql`. _Works as intended._

Fix suggested in https://github.com/TrinityCore/TrinityCore/issues/15722#issuecomment-157257862 (working link: https://github.com/Joslyn-Maddie/MaddieCore/blob/master/sql/Joslyn-Maddie%20world/2015_11_16_10_joslyn_Maddie.sql), but that SQL contains an invalid `entry = 'entry'` value, therefore my suggested fix here (as well as in https://github.com/TrinityCore/TrinityCore/issues/15722#issuecomment-157267420).

Solution credit goes to @Joslyn-Maddie :+1:
