### ISSUE TITLE
[3.3.5][6.x][Core/Spell] Venomhide Poison - Enchant with wrong duration

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15739]
rev: https://github.com/TrinityCore/TrinityCore/commit/c6c3e72b55846ccfb565fd09580509800bd25c2a

Facts:
http://www.wowhead.com/spell=14792/venomhide-poison
You get this echantspell if you fight against http://www.wowhead.com/npc=6508/venomhide-ravasaur

Problem:
The duration of the enchant:
Enchant Held Item (OBSOLETE): Venomhide Poison (1003)
holds 9 HOURS

How it should be:
Enchant Held Item (OBSOLETE): Venomhide Poison (1003)
The duration should be 5 MINUTES.
The procchance and the procflags are all correct. it's only an issue with the duration of the enchant

Source:
Venomhide Poison is a temporary weapon enchantment that lasts for 5 minutes.
http://wowwiki.wikia.com/wiki/Venomhide_Poison

What i tried to fix the issue:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/SpellEffects.cpp#L2692
I added the spellinfo:
```c++
else if (m_spellInfo->Id == 14792)
        duration = 300;                                     // 5 mins
```
but this didn't changed anything. so i'm pretty lost here :D 

sideproblem: many people abuse this enchant to deal further damage in raids

**Comment by digz6666** [comment]
Confirmed, it's on top damage of skill for paladin's in raid.

**Comment by Rushor** [comment]
you can reduce the damage if you disable the sp scailing in spell_bonus_data
(that's a quick solution, but all we actually need is a fix for the duration)

**Comment by Shauren** [comment]
The effect is EnchantHeldItem, not EnchantItemTemporary

**Comment by Rushor** [comment]
then it's even more strange:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/SpellEffects.cpp#L4117
ID - 14792
Duration: ID (9)  30000, 0, 30000

**Comment by Shauren** [comment]
Actually, its not. see here:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/SpellEffects.cpp#L4135
30s * 1000 -> 8 hours and 20 minutes (ingame 9 hours)

**Comment by Rushor** [comment]
there are only 3 spells which use this effect 
ID - 53160 Dancing Rune Weapon Visual
ID - 19108 MHTest02
and the already known spell

would it be save to change the multiplier to 10 since 53160 has a unlimited duration and 19108 does not have a duration at all?

**Comment by Shauren** [comment]
why any multiplier? spell in this issue clearly has a custom duration (5 minutes)

**Comment by Rushor** [comment]
the duration is only 30 seconds (duration of the debuff) but it must be 5 minutes, so * 10 is needed :/
where do you see the 5 minutes duration in 14792?

**Comment by Shauren** [comment]
I do not. But duration of the debuff is not related in anyway to duration of the enchantment - just hardcode if (m_spellInfo->Id == 14792) duration=5*MINUTES*IN_MILLISECONDS;

**Comment by Rushor** [comment]
o7 kay

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c04c409f41b2c459aba2b8a2c0c705123d1217d6 thanks for all the help
