### ISSUE TITLE
3.3.5 Segmentation fault in arena_mapbitsp_read on fresh install

### ISSUE THREAD

**Issue by eazrael** [TrinityCore/TrinityCore#15740]
Hi, 
I hope I am doing everything right in this report. Just did my first installation of TC on Ubuntu 15.10 64bit. After start of worldserver the process segfaults after entering any line, I tried "create account", but this happens regardless of what I enter. This is a fresh installation, I was just following the wiki instructions. 

Branch is 3.3.5, build commit is 183b89dcc31e38f23645a008a8c8e6ac4e4aa9f6

World initialized in 0 minutes 14 seconds
TC>TrinityCore rev. 183b89dcc31e 2015-10-19 13:36:44 +0200 (3.3.5 branch) (Unix, Release) (worldserver-daemon) ready...
TC>create account hallo welt
TC>Segmentation fault (core dumped)
wow@wow:~/wow-debug$

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000001ab6f01 in arena_mapbitsp_read (mapbitsp=<optimized out>) at /home/wow/build/TrinityCore/dep/jemalloc/include/jemalloc/internal/arena.h:525
525             return (*mapbitsp);
[Current thread is 1 (Thread 0x7fbf04722780 (LWP 2159))]

Full (I hope so..) gdb crash log at http://pastebin.com/qiGFvAJw

Might be related to #14909 as crash at same position?

**Comment by Aokromes** [comment]
Downgrade to ubuntu 15.04 we don't support beta os.

**Comment by eazrael** [comment]
See you in 2 days.

**Comment by Aokromes** [comment]
```
World initialized in 6 minutes 47 seconds
TC>TrinityCore rev. 183b89dcc31e 2015-10-19 13:36:44 +0200 (3.3.5 branch) (Unix, Debug) (worldserver-daemon) ready...
TC>ser in
TC>==36019== Invalid free() / delete / delete[] / realloc()
==36019==    at 0x4C2D28B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==36019==    by 0x6AB28DE: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==36019==    by 0x6AB2BD8: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21)
==36019==    by 0x17E8866: ChatHandler::SetDataForCommandInTable(ChatCommand*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Chat.cpp:409)
==36019==    by 0x17E6D7B: ChatHandler::getCommandTable() (Chat.cpp:95)
==36019==    by 0x17E91FD: ChatHandler::ParseCommands(char const*) (Chat.cpp:452)
==36019==    by 0x1FA479A: World::ProcessCliCommands() (World.cpp:2736)
==36019==    by 0x1FA1AFA: World::Update(unsigned int) (World.cpp:2187)
==36019==    by 0x1777FBB: WorldUpdateLoop() (Main.cpp:378)
==36019==    by 0x1775CFF: main (Main.cpp:241)
==36019==  Address 0x346f068 is in the BSS segment of /home/aokromes/bin/trinity335a/bin/worldserver
==36019==
TrinityCore rev. 183b89dcc31e 2015-10-19 13:36:44 +0200 (3.3.5 branch) (Unix, Debug)
Online players: 0 (max: 0)
Active connections: 0 (max: 0) Queued connections: 0 (max: 0)
Server uptime: 9 Second(s).
Update time diff: 49.
TC>

**Comment by jackpoz** [comment]
someone added a new command with NULL help ?

**Comment by Shauren** [comment]
lets see then

**Comment by DDuarte** [comment]
Aok's full crashlog doesn't show help as null http://pastebin.com/Ep1gh1Di

**Comment by eazrael** [comment]
Are you currently focusing on code or DB content? 
There is also this closed forum report http://community.trinitycore.org/topic/11959-crash-on-command-execution-33559/ dating from Sep 26th. So if it's the same bug, it must be dating before that date.

**Comment by jackpoz** [comment]
![image](https://cloud.githubusercontent.com/assets/1153754/10620313/9a527e02-777a-11e5-85ce-c48106cac473.png)

**Comment by eazrael** [comment]
Just build 183b89dcc31e on Ubuntu 15.04. Worldserver starts and takes commands without crashing.

**Comment by Aokromes** [comment]
What gcc version have ubuntu 15.04?

**Comment by eazrael** [comment]
gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Espionage724** [comment]
I believe I'm running into a similar issue (fresh compile, TC crashing upon command typing in either console or in-game). This has started happening after upgrading from Fedora 22 to 23.

The GCC version seems to be the same between the two versions (gcc version 5.1.1 20150618 (Red Hat 5.1.1-4)), but they seem to be configured slightly differently (according to gcc -v, the F23 machine lacks **--with-default-libstdcxx-abi=c++98**). I'm building the same way from F22 to F23 ([specifically with this script](https://github.com/Espionage724/Linux-Stuff/blob/master/Oak/up.sh))

Is there any particular thing I should do to verify this, or any more information needed?

**Comment by Aokromes** [comment]
On Ubungtu 15.10 is --with-default-libstdcxx-abi=new
