### ISSUE TITLE
[335] Small Crag Boar - Invalid Skinning Loot

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#15742]
__Core:__ 747ea7c
__DB:__ TDB_full_335.59_2015_07_14 + updates

__Bug:__

The [Small Crag Boar](http://www.wowhead.com/npc=708/small-crag-boar#drops:mode=) has [Red Whelp Scale](http://www.wowhead.com/item=7287/red-whelp-scale) in its skinning loot

__Notes:__

According to the wowhead link above, it shouldn't have any skinning loot at all (wowhead provides a "skinning" tab for mobs that are skinnable, for example [Mangy Wolf](http://www.wowhead.com/npc=525/mangy-wolf#skinning))

**Comment by tkrokli** [comment]
I thought this was covered already by [**More Skinning Work #10744**](https://github.com/TrinityCore/TrinityCore/issues/10744) ?

**Comment by MrSmite** [comment]
> I thought this was covered already by More Skinning Work #10744 ?

Perhaps but that thread is from 2013 and doesn't appear to have been merged at any time.

**Comment by tkrokli** [comment]
As @ZxBiohazardZx said: "As always it's WIP. if you are bored and want to help out then by all means, go ahead and find the master templates in the mess that is named skinning_loot_template"
I think that means that he intended either to continue working on it or hope that someone else would pick up the task and complete it later. (Which also means that the script is not complete enough yet.)

**Comment by MrSmite** [comment]
Well if something is going to be left as a WIP for 2 (going on 3) years, it's probably better to just handle each report as they come in. Otherwise these things will never be fixed.

**Comment by Rushor** [comment]
https://web.archive.org/web/20110719135256/http://www.wowhead.com/npc=708 also confirms, the skinloot is wrong
