### ISSUE TITLE
3.3.5a Faldir's Cove - Arathi Highlands 

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#15748]
TrinityCore rev. 54341dc8ab77 2015-10-20 11:47:44 +0200 (3.3.5 branch)

Went to Faldir's Cove in Arathi and it does not give you the achievement for exploration. Explored the whole cove and still no achievement, and it looks abandoned, like there has been no scripting of anything there. No npc's...nothing.

**Comment by Killyana** [comment]
Cannot reproduce I got the area explored in the achievement and spawns are near the boat.

**Comment by Rushor** [comment]
http://i.imgur.com/opvSiK6.jpg
http://wow.freierbund.de/map_and_guide/42210/Die_Faldirbucht.html

same here
