### ISSUE TITLE
3.3.5 Headless Horseman

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15747]
TrinityCore rev. 8ff619ddc40f 2015-10-18 01:23:35 +0200

Headless Horseman have a "Unknow Name"
Headless Horseman don't run in the Sky, its more a jumping
and i think the Horseman gives a wrong text.
If you kill the Horseman after spawned a Mob with the Name 'Headless Horseman'

![wowscrnshot_101915_191352](https://cloud.githubusercontent.com/assets/10637389/10606848/dffb4d34-7735-11e5-8de7-bb0cc8bd1cdc.jpg)
![wowscrnshot_101915_191452](https://cloud.githubusercontent.com/assets/10637389/10606853/e7b41eca-7735-11e5-830e-41be8a284c60.jpg)
![wowscrnshot_101915_191654](https://cloud.githubusercontent.com/assets/10637389/10606856/eea3a598-7735-11e5-860b-8cbfa3e2d33c.jpg)

**Comment by Aokromes** [comment]
duplicate.
