### ISSUE TITLE
[6.X] Achievement

### ISSUE THREAD

**Issue by Rezer954** [TrinityCore/TrinityCore#15752]
Hi, in Trinitycore Rev: https://github.com/TrinityCore/TrinityCore/commit/a3814d493705d922e85aa27280d44e0bf3111a3a

Achievements do not work. 
Example: http://2.firepic.org/2/images/2015-10/22/tpe56p68f9eg.jpg

**Comment by Nelidon** [comment]
_achievementCriteriaTreeByCriteria is always empty

**Comment by Nelidon** [comment]
This issue is present since the convertion of Achievement to db2 file (and all db2 related to achievements).

**Comment by BahDumbBugs** [comment]
Are achievements now implemented with the above fix?

**Comment by tkrokli** [comment]
According to https://github.com/TrinityCore/TrinityCore/pull/15818 it should now be possible to read achievements stored in the DB2 files. This depends on the acievements being written correctly to the database, so you may find that some achievements don't work yet, while others do. At least you should be able to open the achievements window by pressing the toolbar button, which apparently was not possible before.
