### ISSUE TITLE
[335a] Can't revive after dying in instance

### ISSUE THREAD

**Issue by TurinTurambar** [TrinityCore/TrinityCore#15758]
3.3.5 branch
core hash c04c409f41b2c459aba2b8a2c0c705123d1217d6

Well, this one is a little tricky... 
How to reproduce:
1- Enter any dungeon instance with a party,
2- Tell them not to get out of the instance and get disconnected (alt+f4, log off, etc) or get connection issues (like cable disconnection?)
3- Wait until party expels you or server takes you out of the party because of disconnection... you will disappear from the map.
4- Log in again while your previous party is whitin the instance, you will be on the same map but in a diferent instance than the group, this is normal and ok.
5- Get killed by monsters whitin YOUR instance, you will be taken as ghost to the nearest graveyard but your corpse will remain within YOUR instance.
6- Let the original party invite you again
7- Enter the instance as ghost...
At this point you are entering the SAME instance than your party and you SHOULD revive at entering; your old instance map should be removed and your coprse should appear inside the group's instance because it is now your instance also... but this doesn't happen... you enter the instance as a ghost and remain a ghost... unable to revive because your corpse is not in THIS instance of the map... also your party cannot revive you since your corpse is not there.

**Comment by Younguns** [comment]
Not sure if this is a related problem, but when you die in Northrend there are graveyards with no spirit healers to resurrect and you are mounted on a mount. This has happened to my wife and myself.

TrinityCore rev. 641f34c78a41 2015-10-23 21:40:54 +0200 (3.3.5 branch) (Win32, Release)

**Comment by tkrokli** [comment]
@Younguns : Maybe I don't remember all the details, but I think it used to be like that back in 2009-2010 when I did instances or raids in Icecrown. I don't remember what it was like in the other zones, though.

**Comment by Runico** [comment]
confirm

**Comment by Re3os** [comment]
confirm https://github.com/TrinityCore/TrinityCore/commit/b3e718dccac3f716f3b57c44e9e11ba886b1208f

**Comment by Killyana** [comment]
Related issue:
1- Die inside a raid then leave the party and try to enter the instance to resurrect, you will not be able to do it (In this case you must resurrect outside)

2- Enter a low level instance (like stratholme) die than release, Change the donjon difficulty from normal to heroic twice to reset the instance, you will receive the message instance reseted (this mustn't happen, if there's a corpse or player inside the instance). Try to enter the instance, you will be inside it on ghost form, a window will pop up to resurect, you click accept but nothing happen.
