### ISSUE TITLE
[3.3.5] Possible bug in cooldown addition

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/TrinityCore#15766]
Rev: https://github.com/TrinityCore/TrinityCore/commit/183b89dcc31e38f23645a008a8c8e6ac4e4aa9f6

I don't know if this is really a bug, but it seems very strange to me.

When you cast a spell and a cooldown should be added, there are a lot of cooldowns that will be added.

Usually, most of them are releated with the spell (like other similar spells), but sometimes some cooldown of apparently totally unrelated spells are added.

To test it, just add a printf of **spellId** variable inside **SpellHistory::AddCooldown** method of **SpellHistory.cpp**:

https://github.com/TrinityCore/TrinityCore/blob/183b89dcc31e38f23645a008a8c8e6ac4e4aa9f6/src/server/game/Spells/SpellHistory.cpp#L427

Then try to cast a spell and see which cooldowns are added.

For example, if I try to cast the Stealth rogue spell, I get some strange cooldowns like:

http://wotlk.openwow.com/spell=71435

but this is just an example, I saw a lot of nosense cooldown addition doing few tests.

**Comment by sirikfoll** [comment]
They all have the same category: `Category = 38`
But, there's issues related with that, and as stated in some other issue, backporting 1efb3f08e278530f59d681f676b031a7fc6db3ac is supposed to fix them

**Comment by tkrokli** [comment]
@sirikfoll : I thought the same when I first read this issue, but I can't find that 6.x commit in the 3.3.5 branch — is it possible that it was added or cherry-picked under a different title? In the list  [**[DEV] 6.x -> 3.3.5 cherry-picks (TDB: 335.60 & 6.03) #15078**](https://github.com/TrinityCore/TrinityCore/issues/15078) it is still listed as not ported / not cherry-picked from 6.x to 3.3.5:
***
- [ ] 1efb3f0 Core/Spells: Improved spell category cooldown handling * Category cooldown is stored with the spell that started the cooldown (and only resetting cooldown on that spell will clear cooldowns on entire category - this fully mirrors client behavior)
- This significantly reduces the amount of data saved to database for cooldowns
- Spell casts from items that have a different category specified than on spell will now check for cooldown during the cast

***
If that status still is correct, I am uncertain what causes this issue in 3.3.5.

**Comment by Keader** [comment]
This backport is very important, it could give some priority to him xD
