### ISSUE TITLE
[3.3.5] DB/Creature: Magistrix Eredania (entry 16160) not visible

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#15770]
TrinityCore rev. f36d76e953b8 2015-10-27 22:58:03 +0000 (3.3.5 branch) (Win64, Release)
TDB 335.59 + updates up to and including 2015_10_27_02_world.sql (commit c3fe637).

Magistrix Eredania `<Enchanting Trainer>`: Level 16, faction: Silvermoon City
NPC ID / entry 16160: http://www.wowhead.com/npc=16160/magistrix-eredania
TBC & WoTLK NPC screenshot image: http://wow.zamimg.com/uploads/screenshots/normal/57383.jpg

This NPC can not be found at her supposed location in Saltheril's Haven in Eversong Woods.

How to verify the issue:
1. Create a horde character (ex. blood elf) on a gm account (gmlevel 3)
2. Use the gm command `.go creature Magistrix_Eredania` (teleports you to the correct location)
3. Step back as you would have done to interact with the NPC
4. Notice that the NPC is not there, not even with GM ON (to see invisible GOs and creatures)

Searching for "entry 16160" or "Magistrix Eredania" on this repo does not show anything mentioning her except for an old DB update for the NPCs walking speed: https://github.com/TrinityCore/TrinityCore/search?utf8=✓&q=Magistrix+Eredania&type=Code

**Comment by Killyana** [comment]
Model issue.

**Comment by tkrokli** [comment]
Oh. Is it about the `modelid1` entry in `creature_template`, or do you mean some other type of model?
```sql
SELECT * FROM `creature_template` WHERE `entry` = 16160;
```
```
 entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name                subname             IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName  MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName  VerifiedBuild
------  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ------------------  ------------------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  ------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  ----------  -------------
 16160                   0                   0                   0            0            0     16046         0         0         0  Magistrix Eredania  Enchanting Trainer  (NULL)              7524        16        16       0     1604       81           1    1.14286       1       0          0            2000             2000             1              1           8        4608         2048             0       0             2              0              0             0       7   134217728       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                     1            3            1            1.05             1              1               1                   1             0           0            1                     0            2                      12340
```

**Comment by Killyana** [comment]
``` sql SELECT * FROM creature_model_info WHERE DisplayID=16046;

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `creature_model_info` WHERE `DisplayID`= 16046;
```
```
DisplayID  BoundingRadius  CombatReach  Gender  DisplayID_Other_Gender
---------  --------------  -----------  ------  ----------------------
    16046           0.383          1.5       1                   11686
```

**Comment by Kittnz** [comment]
I can see her on my test server.

**Comment by Killyana** [comment]
Kittnz the 2 models are random.

**Comment by tkrokli** [comment]
Would this be a practical solution?
```sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`= 16046 WHERE `DisplayID`= 16046;
```
(I'm currently updating my dbc/maps/vmaps/mmaps, will be able to test again in 10 minutes.)

**Comment by Aokromes** [comment]
No, force visible model on creature table.

**Comment by tkrokli** [comment]
OK, but is the `creature_model_info` update considered a "hack" even though it works?
(checking the creature table now, will post again if I find out how it is done)

**Comment by Kittnz** [comment]
```sql UPDATE `creature` SET `modelid`=16046 WHERE  `guid`=56753;

**Comment by tkrokli** [comment]
Ah, right. I should use the primary (unique) key for SQL selections/updates, even if the NPC in question only has one single row in the table. BTW, here is a repeat of your SQL with ```sql on its own line:
```sql
UPDATE `creature` SET `modelid` = 16046 WHERE `guid` = 56753;

**Comment by Rushor** [comment]
or maybe this

```sql
-- Magistrix Eredania SAI
SET @ENTRY := 16160;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,25,0,100,0,0,0,0,0,3,16160,16046,0,0,0,0,1,0,0,0,0,0,0,0,"Magistrix Eredania - On Reset - Morph To Creature Magistrix Eredania");
```

like aok already said

**Comment by tkrokli** [comment]
Thank you for the SAI script. I just can't see a way to interpret that he meant to use SAI and to morph the NPC. I thought he meant to change the `modelid` in the `creature` table. Anyway, testing your SAI now.

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/15371
And forcing the model on creature doesn't work, the wrong model still can be used.
About the SAI it looks too much, also modelid on creature table is supposed to be used for this kind of issue.
For creature_model_info we cannot touch this table.

**Comment by tkrokli** [comment]
Hmm. I don't understand that a table can't be updated/edited/altered if it is there the problem exists, but I don't know enough of the background for that decision, so I can't actually question it. I just don't know.

@Rushor : your SAI works, just like the "illegal" update I tested on the `creature_model_info` table.

Ref. malcrom's comment https://github.com/TrinityCore/TrinityCore/issues/15371#issuecomment-136143728 : what about `event_type` 54 `JUST_SUMMONED` or 63 `JUST_CREATED`, instead of 25 `RESET` ? Do they mean something else which is not valid in this context?

**Comment by Killyana** [comment]
WIP
Gender model is loaded even if `DisplayID_Other_Gender`=0
``` sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID`=16046;
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|128 WHERE `entry` IN (22434,22435,22447,22383);
