### ISSUE TITLE
DB/Error

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15774]
TrinityCore rev. 20b4e6f03adc 2015-10-28 21:56:40 +0100 (HEAD branch)

Console Error

Creature (Entry: 29999) has wrong value (0) in `InhabitType`, creature will not correctly walk/swim/fly.
Script named 'boss_anubshiah' does not have a script name assigned in database.
Script named 'boss_gorosh_the_dervish' does not have a script name assigned in database.
Script named 'boss_grizzle' does not have a script name assigned in database.

This Error Comes after install "2015_10_27_00_world335.sql"
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (14338) is not using SmartAI, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: Creature entry (29999) is not using SmartAI, skipped loading.

**Comment by tkrokli** [comment]
Creature ID/entry 29999 = 'Cave Explosion Bunny' is a Spell Bunny used near Frostgut's Altar in Storm Peaks for the quest "A Flawless Plan" (http://www.wowhead.com/quest=12823/a-flawless-plan). I am not sure what kind of `InhabitType` it should have, but in `creature_template` the value is 4 (Flying) in my TDB 335.59 + updates up to and including 2015_10_28_00_world.sql . This entry is not present in my DBErrors.log, maybe you should check if your DB is up to date? This entry was updated in commit https://github.com/TrinityCore/TrinityCore/commit/2aaab04 (3.3.5) on 2015-07-25, so it is odd that you still get this particular entry in your log.
Read issue https://github.com/TrinityCore/TrinityCore/issues/12190 for details. You can also check your DB by running this query:
```sql
SELECT `entry`,`name`,`AIName`,`InhabitType`,`ScriptName`,`VerifiedBuild` FROM `creature_template` WHERE `entry`= 29999;
```
You should get this output:
```
 entry  name                  AIName   InhabitType  ScriptName  VerifiedBuild
------  --------------------  -------  -----------  ----------  -------------
 29999  Cave Explosion Bunny  SmartAI            4                      12340
```
The rest of your list is present in my DBErrors.log and is correct regarding those entries, they don't have any C++ script names assigned in DB, but the C++ scripts still exist in the source:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/
- boss_anubshiah.cpp
- boss_gorosh_the_dervish.cpp
- boss_grizzle.cpp

Creature entry 14338 Knot Thimblejack (http://www.wowhead.com/npc=14338/knot-thimblejack)
can be found in Dire Maul. (3.3.5 quest info in http://wotlk.openwow.com/npc=14338)
Looking up "Knot Timblejack" in the TC repository gives this result:
https://github.com/TrinityCore/TrinityCore/search?q=Knot+Thimblejack&type=Issues&utf8=✓
=> https://github.com/TrinityCore/TrinityCore/commit/b96f2e1 [**DB/Misc: Knot Thimblejack**](https://github.com/TrinityCore/TrinityCore/commit/b96f2e1) [/sql/updates/world/2015_10_27_00_world335.sql](https://github.com/TrinityCore/TrinityCore/blob/b96f2e11ca76319888f641d2b38dcefce710221f/sql/updates/world/2015_10_27_00_world335.sql)

Running this query on TDB 335.59 (+ updates) on `world`.`creature_template`
```sql
SELECT `entry`,`name`,`gossip_menu_id`,`AIName`,`InhabitType`,`ScriptName`,`VerifiedBuild` FROM `creature_template` WHERE `entry` = 14338;
```
gives this result:
```
 entry  name              gossip_menu_id  AIName  InhabitType  ScriptName  VerifiedBuild
------  ----------------  --------------  ------  -----------  ----------  -------------
 14338  Knot Thimblejack            5667                    3                      12340
```
You can see that creature 14338 is not marked as using SmartAI in the DB table `creature_template`, but when looking in the table `smart_scripts` I find this:
```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid` = 14338;
```
```
entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_x  target_y  target_z  target_o  comment
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  --------  --------  --------  --------  --------------------------------------------------
      14338            0       0       0          20                 0           100            1          5525             0             0             0           80        1433800              0              0              0              0              0            1              0              0              0         0         0         0         0  Knot - On Free Knot! Reward - run script
      14338            0       1       0          20                 0           100            1          7429             0             0             0           80        1433800              0              0              0              0              0            1              0              0              0         0         0         0         0  Knot - On Free Knot! Reward - run script
      14338            0       2       0          34                 0           100            0             0             1             0             0           41              0              0              0              0              0              0            1              0              0              0         0         0         0         0  Knot - On Point Reached - Despawn
      14338            0       3       0          25                 0           100            0             0             0             0             0           50         179511          43200              0              0              0              0            8              0              0              0   581.241   524.321  -25.4027  -2.79252  Knot - On Reset - Spawn Ball and Chain
      14338            0       4       6          62                 0           100            0          5667             0             0             0           85          22816              2              0              0              0              0            7              0              0              0         0         0         0         0  Knot - On Gossip Select  - Cast Gordok Ogre Suit
      14338            0       5       6          62                 0           100            0          5667             1             0             0           85          22814              2              0              0              0              0            7              0              0              0         0         0         0         0  Knot - On Gossip Select  - Cast Gordok Ogre Suit
      14338            0       6       0          61                 0           100            0          5667             0             0             0           72              0              0              0              0              0              0            7              0              0              0         0         0         0         0  Knot - On Gossip Select  - Close Gossip
```
Looking at [/sql/updates/world/2015_10_27_00_world335.sql](https://github.com/TrinityCore/TrinityCore/blob/b96f2e11ca76319888f641d2b38dcefce710221f/sql/updates/world/2015_10_27_00_world335.sql) again, I notice that @dr-j has forgotten to add this line in his SQL:
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 14338;
```
This should fix your list of SmartAIMgr errors (7).

**Comment by Tauriella** [comment]
Thanks for your helping :+1:
