### ISSUE TITLE
Crash WorldSession::HandlePlayerLogin

### ISSUE THREAD

**Issue by Laintime** [TrinityCore/TrinityCore#15777]
Rev.https://github.com/TrinityCore/TrinityCore/commit/c7bad70e55e02fa4270f225e2dc42fd080db4abd
GDB http://pastebin.com/Sb6cpZTF

Crash on char login.
Revert this https://github.com/TrinityCore/TrinityCore/commit/c7bad70e55e02fa4270f225e2dc42fd080db4abd no crash uptime 3h.

**Comment by Shauren** [comment]
Line numbers don't match clean sources way too much for this to be considered a valid crash report. Not to mention that Player::CheckInstanceLoginValid doesn't call GetMap at all.
