### ISSUE TITLE
[6.x][CORE] Req. Quest Info

### ISSUE THREAD

**Issue by WoWShards** [TrinityCore/TrinityCore#15788]
Rev: 81488366c0d0c096644638c79b658f78d680ab78

After you accept a quest, and you try to return you see blank. We are missing the opcode style for req. quest related stuff.

Here is a part of the log

---

No defined handler for opcode [UNKNOWN OPCODE 0x0D9E (3486)] sent by [Player: Omrok GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 2]
Received not handled opcode [CMSG_CLOSE_INTERACTION 0x0559 (1369)] from [Player: Omrok GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 2]
No defined handler for opcode [UNKNOWN OPCODE 0x0D9E (3486)] sent by [Player: Omrok GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 2]
Received not handled opcode [CMSG_CLOSE_INTERACTION 0x0559 (1369)] from [Player: Omrok GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 2]

**Comment by Aokromes** [comment]
duplicate. don't report any "not handled opcode"
