### ISSUE TITLE
[6.x] Character Creation and Login

### ISSUE THREAD

**Issue by WoWShards** [TrinityCore/TrinityCore#15785]
TC Rev: d26bc41a3e4887df7abb21ff2133cf144b08df8b

Everytime when I create a character and login, he throw me out into character selection and says world server is down. But server is still running.

---

[Player: Logging in: GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1] failed to connect 5 times to world socket, aborting login
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x0973 (2419)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x03B9 (953)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x0222 (546)] from [Player: Account: 1]

**Comment by sergeev** [comment]
I do not have this problem, you may need to update the sql for the world of the characters and auth.

**Comment by WoWShards** [comment]
No, sorry Sir.

I'm using Auto Update System, and I freshly compiled TC.

**Comment by WoWShards** [comment]
I found a way how to fix this bug, thanks to @sergeev 

When I use RealmZone 8 (English) -> crash
Realmzone 1 (Development) -> no crash

**Comment by Aokromes** [comment]
supply gdb crashlog.

**Comment by Shauren** [comment]
Not a crash.
```[Player: Logging in: GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1] failed to connect 5 times to world socket, aborting login```

**Comment by WoWShards** [comment]
normal or debug?

**Comment by WoWShards** [comment]
Notice:
After Rev c463c843257e30b780ca3ca98f6be47f15a52297 still bugged.

**Comment by WoWShards** [comment]
sorry forgot to compile facepalm - working with RealmZone 8 now...
Maybe someone else fix-feedback ?

**Comment by Ahtuno** [comment]
Since https://github.com/TrinityCore/TrinityCore/commit/c463c843257e30b780ca3ca98f6be47f15a52297 everything works fine.
