### ISSUE TITLE
[3.3.5] [Spell][Hunter] Freezing Arrow(60192) is not working

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#15794]
The category of spell Freezing Arrow(60192) is 411, and the category of trigger spell 60202 is 411 too. So after 60192 casted, the trigger spell 60202 is in a cooldown.
After ver. 7dcddd90be6e49281ca04239de5839e757ef3f7a

**Comment by tkrokli** [comment]
Isn't it correct for spells to share cooldown when the spells are tied together in the same action?
If the cooldown is identical for both, they will both be available again at the same time, right?

**Comment by shenhuyong** [comment]
Yes, after ver.7dcddd90be6e49281ca04239de5839e757ef3f7a , it Improved spell category cooldown handling. All of spells in same category will start cooldowns and save to database after a spell one of them be casted. So spell 60192 can't triggering spell 60202, because the trigger spell 60202 also has a cooldown.

**Comment by ariel-** [comment]
Shouldn't triggered spells (specially with triggered flag TRIGGERED_IGNORE_SPELL_AND_CATEGORY_CD) do just that and go ahead with the casting anyways?

**Comment by shenhuyong** [comment]
After I used “.cheat cooldown” command, the spell 60192 works fine, it can triggered spell 60202.

**Comment by sirikfoll** [comment]
Maybe this?
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 76eefa0..c8d0b84 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4668,7 +4668,7 @@ SpellCastResult Spell::CheckCast(bool strict)
                 return SPELL_FAILED_NOT_READY;
         }
 
-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
+        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && !IsIgnoringCooldowns())
         {
             if (m_triggeredByAuraSpell)
                 return SPELL_FAILED_DONT_REPORT;

```

**Comment by tkrokli** [comment]
Additional **Freezing Arrow** information, in case anyone would like to look up the details:
http://wow.gamepedia.com/Freezing_Arrow `Level 80 survival hunter ability`
http://wotlk.openwow.com/spell=60192/freezing-arrow `3.3.5 version`
http://www.wowhead.com/spell=60192/freezing-trap `reused as ordinary trap spell after patch 4.0.1`
http://www.wowhead.com/spell=60202/freezing-trap `trigger spell 60202`
http://wotlk.openwow.com/spell=60202/freezing-trap `trigger spell 60202`

**Comment by superllout** [comment]
if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && !IsIgnoringCooldowns())

This will broke Deathbringer's Will. 
Tested.

**Comment by sirikfoll** [comment]
Did anybody notest any other broken spells, besides Frozen arrow?

**Comment by DevRival** [comment]
Everything is very bad . I noticed that [Lava Lash](http://merlin.org.ua/wowhead/?spell=60103) now  has no cooldown.

**Comment by DevRival** [comment]
That's what I noticed a problem with the Frozen arrow .

**Comment by tkrokli** [comment]
I would like to point out that **Frozen** Arrow (http://www.wowhead.com/spell=126321/frozen-arrow) is an NPC ability used by Huo-Shuang <Shao-Tien Imperion> (http://www.wowhead.com/npc=63691/huo-shuang).

**Freezing** Arrow (http://wow.gamepedia.com/Freezing_Arrow / http://wotlk.openwow.com/spell=60192),
on the other hand, is the level 80 hunter trap spell in 3.3.5 (removed in patch 4.0.1).

**Comment by ccrs** [comment]
http://wotlk.openwow.com/spell=56453 Lock and Load doesnt seem to proc too.

**Comment by ccrs** [comment]
http://wotlk.openwow.com/spell=69487 overheat doesnt proc anymore

**Comment by ccrs** [comment]
it seems like several mechanics are broken right now, id say this is an important issue xd

**Comment by Demonid** [comment]
@ccrs Yep, lets hope @Shauren gets some free time and checks this :+1:

**Comment by ShinDarth** [comment]
Confirmed on https://github.com/TrinityCore/TrinityCore/commit/302623a1516e487ad64f2028aec287b99372e33a

**Comment by ccrs** [comment]
oh, right. confirm on 302623a1516e487ad64f2028aec287b99372e33a

**Comment by Laintime** [comment]
oh,confirm https://github.com/TrinityCore/TrinityCore/commit/d93b445d31aec7ffc4e937a2422ff95328b06a29

**Comment by Demonid** [comment]
confirmed on d93b445d31aec7ffc4e937a2422ff95328b06a29 (?

**Comment by Re3os** [comment]
@Demonid Why this stupid comments?

**Comment by ccrs** [comment]
we didnt post our server revision on the previous comments.

**Comment by Re3os** [comment]
@sirikfoll I'm tested you fix,this aura stacked ID 71560,71484,71559,71491.

**Comment by tkrokli** [comment]
@Re3os : A.K.A. these spells / auras:
http://www.wowhead.com/spell=71484/strength-of-the-taunka
http://www.wowhead.com/spell=71491/aim-of-the-iron-dwarves
http://www.wowhead.com/spell=71559/aim-of-the-iron-dwarves
http://www.wowhead.com/spell=71560/speed-of-the-vrykul

**Comment by Re3os** [comment]
@tkrokli sori,mobile.
Is item 
http://www.wowhead.com/item=50362
http://www.wowhead.com/item=50363

**Comment by ariel-** [comment]
Interesting you mention DBW procs, since they're handled differently, in HandleDummyAuraProc.

Also, IsReady doesn't check only for cooldowns, it also checks school locks, that way, if a spell is school locked, and cast using TRIGGERED_IGNORE_COOLDOWNS will be casted anyways.

**Comment by Re3os** [comment]
@ariel- Maybe you give us hack?

**Comment by Laintime** [comment]
@Re3os thx.
confirm https://github.com/TrinityCore/TrinityCore/commit/5df0bcdd4e2d55fb9c1abea882712585dbdcd1f3

**Comment by Re3os** [comment]
@ccrs Not fiks this commit,confirm https://github.com/TrinityCore/TrinityCore/commit/e266278f7d029f1547b1ae3228d658463c69da09

**Comment by ShinDarth** [comment]
you can easily hackfix it just by replacing:

```if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))```

with:

```if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && m_spellInfo->Id != 60202)```

but it would be nice to have a proper solution for this issue.

**Comment by Re3os** [comment]
```C++
a89a3cf6225d1381142d4679ed7ba3ad3301d1f4
 src/server/game/Spells/Spell.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 99e2d3a..0966900 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4856,7 +4856,7 @@ SpellCastResult Spell::CheckCast(bool strict)
                 return SPELL_FAILED_NOT_READY;
         }
 
-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
+        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && m_spellInfo->Id != 60202)
         {
             if (m_triggeredByAuraSpell)
                 return SPELL_FAILED_DONT_REPORT;
```

**Comment by ShinDarth** [comment]
yes @Re3os that is

**Comment by DevRival** [comment]
any news?

**Comment by Eliminationzx** [comment]
Try it.
```
 src/server/game/Spells/SpellHistory.cpp | 8 ++------
 1 file changed, 2 insertions(+), 6 deletions(-)

diff --git a/src/server/game/Spells/SpellHistory.cpp b/src/server/game/Spells/SpellHistory.cpp
index ac08f68..f86b8f5 100644
--- a/src/server/game/Spells/SpellHistory.cpp
+++ b/src/server/game/Spells/SpellHistory.cpp
@@ -185,12 +185,8 @@ void SpellHistory::HandleCooldowns(SpellInfo const* spellInfo, uint32 itemID, Sp
 bool SpellHistory::IsReady(SpellInfo const* spellInfo, uint32 itemId /*= 0*/) const
 {
     if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_SILENCE)
-        if (IsSchoolLocked(spellInfo->GetSchoolMask()))
-            return false;
-
-    if (HasCooldown(spellInfo->Id, itemId))
-        return false;
-
+       if (IsSchoolLocked(spellInfo->GetSchoolMask()) || HasCooldown(spellInfo->Id, itemId))
+           return false;
     return true;
 }
 ```

**Comment by tkrokli** [comment]
@shenhuyong , @Re3os , @Demonid : check if the suggested fix above solves the issue for you.

**Comment by Eliminationzx** [comment]
Try it
```
 src/server/game/Spells/Spell.cpp | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 84bff4a..ca9f642 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4701,13 +4701,13 @@ SpellCastResult Spell::CheckCast(bool strict)
                 return SPELL_FAILED_NOT_READY;
         }
 
-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
-        {
-            if (m_triggeredByAuraSpell)
-                return SPELL_FAILED_DONT_REPORT;
-            else
-                return SPELL_FAILED_NOT_READY;
-        }
+		if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && !(_triggeredCastFlags & TRIGGERED_IGNORE_SPELL_AND_CATEGORY_CD))
+		{
+			if (m_triggeredByAuraSpell)
+				return SPELL_FAILED_DONT_REPORT;
+			else
+				return SPELL_FAILED_NOT_READY;
+		}
     }
 
     if (m_spellInfo->HasAttribute(SPELL_ATTR7_IS_CHEAT_SPELL) && !m_caster->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_ALLOW_CHEAT_SPELLS))
```

**Comment by tkrokli** [comment]
That's a strange (and incorrect?) diff, should not need to replace more than the first line (the if test).
I think it happened because of some unneeded change in indentation for the subsequent lines.
I believe it should look like this:
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 84bff4a..ca9f642 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4701,7 +4701,7 @@ SpellCastResult Spell::CheckCast(bool strict)
                 return SPELL_FAILED_NOT_READY;
         }

-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
+        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && !(_triggeredCastFlags & TRIGGERED_IGNORE_SPELL_AND_CATEGORY_CD))
         {
             if (m_triggeredByAuraSpell)
                 return SPELL_FAILED_DONT_REPORT;
```

**Comment by Eliminationzx** [comment]
Thank you for your corrections @tkrokli

**Comment by Re3os** [comment]
```diff

a89a3cf6225d1381142d4679ed7ba3ad3301d1f4
 src/server/game/Spells/Spell.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 99e2d3a..0966900 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4856,7 +4856,7 @@ SpellCastResult Spell::CheckCast(bool strict)
                 return SPELL_FAILED_NOT_READY;
         }
 
-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
+        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && m_spellInfo->Id != 60202)
         {
             if (m_triggeredByAuraSpell)
                 return SPELL_FAILED_DONT_REPORT;

```

**Comment by tkrokli** [comment]
OK, looks like there is a discrepancy in the line numbers in Spell.cpp. I will check with current source.

**Comment by ccrs** [comment]
that's a hack, already told u before

**Comment by tkrokli** [comment]
@Eliminationzx : why did your delete your fix suggestion that Aokromes labeled [Feedback-PatchFix] ?

**Comment by Demonid** [comment]
@tkrokli Which one ?

This one? https://github.com/TrinityCore/TrinityCore/issues/15794#issuecomment-172470254

**Comment by Eliminationzx** [comment]
@tkrokli I delete that fix because it was wrong and I just didn't see when Aokromes labeled it.

**Comment by tkrokli** [comment]
OK, thanks for the details. Aok seemed to think it was valid, but then again, he's not an expert on C++
@Demonid : this code (the one that got removed):
```diff
diff --git a/src/server/game/Spells/SpellHistory.cpp b/src/server/game/Spells/SpellHistory.cpp
index ac08f68..f86b8f5 100644
--- a/src/server/game/Spells/SpellHistory.cpp
+++ b/src/server/game/Spells/SpellHistory.cpp
@@ -185,12 +185,8 @@ void SpellHistory::HandleCooldowns(SpellInfo const* spellInfo, uint32 itemID, Sp
 bool SpellHistory::IsReady(SpellInfo const* spellInfo, uint32 itemId /*= 0*/) const
 {
     if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_SILENCE)
-        if (IsSchoolLocked(spellInfo->GetSchoolMask()))
-            return false;
-
-    if (HasCooldown(spellInfo->Id, itemId))
-        return false;
-
+       if (IsSchoolLocked(spellInfo->GetSchoolMask()) || HasCooldown(spellInfo->Id, itemId))
+           return false;
     return true;
 }
```

**Comment by Shauren** [comment]
LOL.
Checking the cooldown only if the spell can be silenced? hahahhaha good one

**Comment by Eliminationzx** [comment]
@tkrokli, it's couldn't be valid I guess, because we should use this check  for all preventions types not only for silence.

**Comment by Demonid** [comment]
Freezing Trap and Overheat seems to work well using https://github.com/TrinityCore/TrinityCore/issues/15794#issuecomment-172470254

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15794#issuecomment-172470254 is the same as https://github.com/TrinityCore/TrinityCore/issues/15794#issuecomment-153231332 and there are some related issues as deathbringer's will triggering auras simultaneously.

**Comment by Demonid** [comment]
@ccrs Yep, true

**Comment by Shauren** [comment]
@Demonid @ccrs these patches break cooldowns on procs

**Comment by ccrs** [comment]
@Shauren https://github.com/ccrs/TrinityCore/commit/bb6fe2959b62697cad0aca6390494ef02129a934 more or less this?

**Comment by ccrs** [comment]
https://github.com/ccrs/TrinityCore/commits/triggeredcooldown

**Comment by Shauren** [comment]
I meant something more like the triggeredByAura arg to CastSpell

**Comment by ccrs** [comment]
````c++
        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
        {
            if (m_triggeredByAuraSpell)
            {
                if (m_triggeredByAuraSpell->GetCategory() != m_spellInfo->GetCategory())
                    return SPELL_FAILED_DONT_REPORT;
            }
            else
                return SPELL_FAILED_NOT_READY;
        }
````
like this?

**Comment by ariel-** [comment]
Doesn't mean the patch is bad either, maybe its the proc system that needs a repair after this.

If you put the cooldown in the passive (triggering aura) and check that for avoiding repeated procs?

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15794#issuecomment-172554099 that comment was referring to a previous workaround :)

**Comment by mayaren888** [comment]
@tkrokli 
`-        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry))
+        if (!m_caster->GetSpellHistory()->IsReady(m_spellInfo, m_castItemEntry) && !(_triggeredCastFlags & TRIGGERED_IGNORE_SPELL_AND_CATEGORY_CD))`

This repair method will cause the skill (spell:71519) trigger is not correct

**Comment by tkrokli** [comment]
I should probably delete my comments with code. None of it works. I just tried to show some editing.

**Comment by mayaren888** [comment]
@tkrokli 
I'm really sorry, didn't mean that your code is given a lot of people inspired.
You are a good contributor.
