### ISSUE TITLE
[3.3.5] [Crash] Player::ApplyEquipCooldown()

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#15797]
https://github.com/TrinityCore/TrinityCore/commit/e8909de8de6486b795deff4db6a477bb366ecae4

If you use [Reclaimed Shadowstrike](http://www.wowhead.com/item=49302/reclaimed-shadowstrike) to summon [Reclaimed Thunderstrike](http://www.wowhead.com/item=49301/reclaimed-thunderstrike) and then try to equip the first, the server crashes.

http://pastebin.com/X3q2Dd63

**Comment by jackpoz** [comment]
>Invalid write of size 4
   at 0x1EFAF9B: Trinity::Assert(char const*, int, char const*, char const*) (Errors.cpp:43)
   by 0x163B8D8: SpellMgr::EnsureSpellInfo(unsigned int) const (SpellMgr.h:701)
   by 0x15E869C: Player::ApplyEquipCooldown(Item*) (Player.cpp:22724)
   by 0x15975D2: Player::EquipItem(unsigned short, Item*, bool) (Player.cpp:12288)
   by 0x18D5DAA: WorldSession::HandleAutoEquipItemOpcode(WorldPacket&) (ItemHandler.cpp:245)
   by 0x1A75C99: WorldSession::Update(unsigned int, PacketFilter&) (WorldSession.cpp:322)
   by 0x1BE817D: World::UpdateSessions(unsigned int) (World.cpp:2702)
   by 0x1BE600C: World::Update(unsigned int) (World.cpp:2062)
   by 0x1292329: WorldUpdateLoop() (Main.cpp:378)
   by 0x1290054: main (Main.cpp:241)
 Address 0x0 is not stack'd, malloc'd or (recently) free'd
