### ISSUE TITLE
Core/Vehicles Problem with Bountiful Table accessory's position

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#15809]
The chairs and the table are vehicles, each chair is in one "seat" of the table.

Something is wrong with the position of the chairs, they all face the same direction and when a player sit on the chair, he appear seated in the middle of the table

![bountifultablechairs](https://cloud.githubusercontent.com/assets/11219553/10926439/9205ed42-827e-11e5-9a5e-c34ac62b401e.jpg)

The Table:
[Bountiful Table](http://wotlk.openwow.com/npc=32823) VehicleId=320, modelid1=28293

The Chairs: VehicleId=321 modelid1=29205
[The Cranberry Chair](http://wotlk.openwow.com/npc=34823)
[The Turkey Chair](http://wotlk.openwow.com/npc=34812)
[The Sweet Potato Chair](http://wotlk.openwow.com/npc=34824)
[The Pie Chair](http://wotlk.openwow.com/npc=34822)
[The Stuffing Chair](http://wotlk.openwow.com/npc=34819)

3.3.5 Brach
hash ea9c112b3085

**Comment by Aokromes** [comment]
#3998

**Comment by sirikfoll** [comment]
totally different issue..

**Comment by Aokromes** [comment]
No, that ticket is about the tables, some of the original issues maybe are fixed, but the tables are still bugged.

**Comment by Killyana** [comment]
Same vehicle issue as https://github.com/TrinityCore/TrinityCore/issues/15224#issuecomment-147102556

**Comment by sirikfoll** [comment]
appears to be a generic thing :/

**Comment by Killyana** [comment]
Also http://wotlk.openwow.com/npc=32840 and http://wotlk.openwow.com/npc=32830 cannot set their accessory because the same spell is used to be set as accessory and to set their own accessory, and TC is not handling this.
