### ISSUE TITLE
[3.3.5] Lady Vashj - Bossupdate needed

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15811]
core:https://github.com/TrinityCore/TrinityCore/commit/ea9c112b30851b6f07f36baca2a6218f6f50cf32
DB:TDB59
update:2015_11_04_00_world.sql
boss_lady_vashj.cpp

BOSS spellID 38132(http://www.wowhead.com/spell=38132) Out of the script.

**Comment by Rushor** [comment]
@w5860363: pls create another pr for this https://trinitycore.atlassian.net/wiki/display/tc/Creating+a+Pull+Request with propper tabs/spaces setting + fix the stuff mentioned in the comments from https://github.com/TrinityCore/TrinityCore/pull/15812

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/24369
