### ISSUE TITLE
[3.3.5] [Script] ICC Emblem of Frost bug

### ISSUE THREAD

**Issue by mastani** [TrinityCore/TrinityCore#15810]
Dead characters get frost without raid save !

How to reproduce:
1- Need 2 character. create a raid and enter into ICC.
2- Before first boss let's one of characters die and realese spirit. don't resurrect.
3- Kill first boss with another character.
4- Two characters get the frost. but the dead character did'nt get save. and can do it again!

This worked for next bosses.

rev: c04c409

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/7672

**Comment by mastani** [comment]
@Killyana not solved

**Comment by Rushor** [comment]
do you see any fix here?

**Comment by mastani** [comment]
@Rushor I mean that related issue

**Comment by tkrokli** [comment]
... and Killyana meant to say that your issue is so similar to issue 7672 that your issue will not be solved until issue 7672 gets solved (almost questioning if your issue is already covered by issue 7672).

**Comment by Rushor** [comment]
as @milotic mentioned in https://github.com/TrinityCore/TrinityCore/issues/7672:
> hi, problem is related with groups example if you create group with 20 players for raid all players outside raid when 10 mains characters kill boss wait turn for can go raid and boss give loot for players outside the raid and encounter, because the loot of boss encounters are not binded with players in fighting and bind loot with all players in the group, cd don´t have this problem

It's a general issue - merged to https://github.com/TrinityCore/TrinityCore/issues/7672
