### ISSUE TITLE
Compile bnetserver/worldserver fails

### ISSUE THREAD

**Issue by ridiculousness** [TrinityCore/TrinityCore#15815]
Branch 6.x
Visual Studio 2015
Boost 1.59
ZeroMQ 4.0.4 
Latest revision (check out 6th November 09:06 AM (UTC +1, Amsterdam)
https://github.com/TrinityCore/TrinityCore/commit/a70ec0ca9ab7e22fda92b56231be6f82f8b00971

I have tried searching for similar issues but am unable to find them via the issue tracker nor there is are any leads on the documentation site.

I also tried searching for the libzmq-v140-mt- but that one is nowhere to be found yet. Looks like it come with ZeroMQ 4.2.0.

So, I pointed the ZMQ library in Cmake to the file I am using in the folder where worldserver.exe & bnetserver.exe lives (older version, that still works) but then I receive below errors.

Could anyone point me in the right direction cause I know some of you are working with the same versions as I am.

24>  Main.cpp
24>  WheatyExceptionReport.cpp
24>C:\Program Files\ZeroMQ 4.0.4\bin\libzmq-v120-mt-4_0_4.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x310
25>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
25>  Building Custom Rule C:/Trinity/CMakeLists.txt
25>  CMake does not need to re-run because F:\Build\CMakeFiles\generate.stamp is up-to-date.
========== Build: 23 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

Thanks.

**Comment by Maibenrai** [comment]
Googled your error:
"Linker error LNK1107 means that you've tried to link to the DLL rather than to the .lib."

**Comment by ridiculousness** [comment]
I feel ashamed....for not looking up the error.....Am rebuilding it right now. Thanks Maibenrai.

**Comment by ridiculousness** [comment]
Same message also appears when I try to use the dll


Found ZMQ library: C:/Program Files/ZeroMQ 4.0.4/bin/libzmq-v120-mt-4_0_4.dll
Found ZMQ headers: C:/Program Files/ZeroMQ 4.0.4/include
SCRIPT PREPARATIONS
  -> Prepared: Spells

**Comment by Maibenrai** [comment]
It has to point to lib, NOT to dll 
C:/Program Files/ZeroMQ 4.0.4/lib/libzmq-v120-mt-4_0_4.lib

**Comment by ridiculousness** [comment]
Yes, I know now. 

But I would expect to get an error message when pointing it to the dll and not: Found zmq library.

Cmake doesn't autodiscover the library on my side so have to do it manually.

**Comment by Maibenrai** [comment]
No error message, because they are both libraries: static libraries (LIB) and dynamic libraries (DLL)?

**Comment by ridiculousness** [comment]
Ok.

It's had completed the compiling and now there are no more compile errors. 

Will close this issue.

Thanks again.
