### ISSUE TITLE
[6.x][CRASH] worldserver crash on start up

### ISSUE THREAD

**Issue by Ahtuno** [TrinityCore/TrinityCore#15822]
Rev: 262e61aae13a91d090220bb120e581c2875fccff

effected database: characters

---

In mysql_stmt_prepare() id: 501, sql: "INSERT INTO pvpstats_players (battleground_id, character_guid, winner, score_killing_blows, score_deaths, score_honorable_kills, score_bonus_honor, score_damage_done, score_healing_done, attr_1, attr_2, attr_3, attr_4, attr_5) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'winner' in 'field list'

**Comment by Aokromes** [comment]
bad db structure not tc related..

**Comment by Ahtuno** [comment]
@Aokromes 
... there is something wrong on your base/characters.sql !
this answer... helpful like ... update your characters.sql right, needed manually last .sql from /updates folder

**Comment by pete318** [comment]
Ensure the SQL part (sql/updates/characters/2015_11_06_00_characters_2015_10_12_00.sql) from https://github.com/TrinityCore/TrinityCore/commit/39d29edf93574d0f133a66f44f059938c4de7a98 was applied to your DB.
