### ISSUE TITLE
[Quest] Deathblow to the Legion

### ISSUE THREAD

**Issue by pak3935** [TrinityCore/TrinityCore#15831]
after the release of the portal there is a 3 NPC
http://www.wowhead.com/quest=10409/deathblow-to-the-legion
http://i.imgur.com/DP3boGf.png
https://www.youtube.com/watch?v=Ncfb5hyiy9E
TrinityCore rev. 7d5e7102cdd4 2015-11-07 20:01:53 +0100 (3.3.5 branch) (Win64, Release)

**Comment by Aokromes** [comment]
and... what's the bug?

**Comment by Killyana** [comment]
Dup #3746
