### ISSUE TITLE
[Crash] related to extractQuotedArg

### ISSUE THREAD

**Issue by mthsena** [TrinityCore/TrinityCore#15833]
Rev. 7d5e7102cdd407846fa340892df39ea49938ee69

How to reproduce:
Use .guild rename and do not put the second argument
```Example: .guild rename "guildname"```

it happens to all the commands than need two arguments

http://pastebin.com/G0mwzDgm

**Comment by jackpoz** [comment]
do you have any custom change applied ?

**Comment by mthsena** [comment]
No, clean build, you cannot reproduce ?
