### ISSUE TITLE
[6.x] Retribution Paladin. Exorcism inflicting only 1 Holy Damage

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#15834]
6.x branch
TrinityCore rev. 271390753d63 

A short video: https://www.dropbox.com/s/2ltqhzi0wfy6d02/2015-11-08_17-36-06.mp4?dl=0

**Comment by Rushor** [comment]
maybe related to https://github.com/TrinityCore/TrinityCore/issues/14825? 
maybe Exorcism need to trigger another spell for the damage?

**Comment by tkrokli** [comment]
@Maibenrai : please post the exact Spell ID you used. We need more documentation on this.
http://www.wowhead.com/spell=879/exorcism : [Effect]: School Damage (Holy) Value: 1 (AP mod: 1.686)

**Comment by Maibenrai** [comment]
I'm playing on retail now and my lvl100 ret pally's Exorcism:
Spell http://i.imgur.com/vgAnT0p.png 
Damage http://i.imgur.com/I7GnGuw.png

It is spell 879. No other spells active and only "buff" is Righteous Fury.

I can make a video if needed.
