### ISSUE TITLE
[6.x] DB/Creature: Morakki can't accept both quests 

### ISSUE THREAD

**Issue by ridiculousness** [TrinityCore/TrinityCore#15844]
Branch 6.x
Revision 6.03, https://github.com/TrinityCore/TrinityCore/commit/7c238cdefa7e83d9574d04851912ed58c81fd7ad

When talking to this npc you can select one of the 2 quests and only accept the one that you selected.

Quest: No more mercy - after accepting I can not accept the other quest
Quest: Territorial fish - after accepting I can not accept the other quest
When talking to him again, there is an empty quest windows.

Location: Darkspear Isle

**Comment by Alastyr** [comment]
Maybe "No more mercy" and "Territorial fish" have the same ExclusiveGroup. Try to set it to 0. I have not TC DB on my pc, so i can't check. If both quests have the same ExclusiveGroup, try to execute this query:

UPDATE quest_template SET ExclusiveGroup=0 WHERE id IN (24812, 24813);

**Comment by Alastyr** [comment]
I downloaded TC DB. I didn't see that a lot of things are changed. ExclusiveGroup now is put into quest_template_addon table. Both quests share the same ExclusiveGroup. The correct query is:

UPDATE quest_template_addon SET ExclusiveGroup=0 WHERE id IN (24812, 24813);

This query will fix this problem.

**Comment by tkrokli** [comment]
@Alastyr : thanks for following up on this issue. :+1: 
Pro tip: put ```sql on the blank line directly above the query, then only the 3 back ticks on the blank line below the query to end the block quote (lookup Markdown via Google: [github markdown](https://goo.gl/Za333y) )
Example:
```sql
UPDATE quest_template_addon SET ExclusiveGroup=0 WHERE id IN (24812, 24813);
```
... and here is an example of text following the block quote.

**Comment by Alastyr** [comment]
@tkrokli thanks for advices. I have just found a lot of interesting things, like ~~ before and after a query to cut it (like done above).
About the issue: just help TC, as soon as possible i'd like to help you more.

**Comment by tkrokli** [comment]
OK, sure, that works too. The blockquote text becomes non-proportional, but you leave out the option to highlight the code syntax. Of course, in a simple 1-line query, this does not mean much. In a bigger query or script, it is often useful to add syntax highlighting to make reading the code easier. Examples:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by Alastyr** [comment]
@KingPin that's great! Thanks for helping! (y)

**Comment by tkrokli** [comment]
"KingPin" ?? Are you sure this is the correct issue?

**Comment by Alastyr** [comment]
@tkrokli failed to tag, sorry.
Btw, anyone can check if the query works?

**Comment by tkrokli** [comment]
Hmm. I am mostly a 3.3.5 user, haven't played any useful game content after 4.3.4 . I also need to rebuild my DB & Core from source, so it will be a slow and ineffective process on my part. Unless someone else volunteers to test if your SQL solves the issue, I may need a description on how to prepare a character to be able to receive the quests in the first place (previous quest requirements etc.)

@ridiculousness (Ellert van der Vecht) should be a natural candidate, though. ;-)

**Comment by ridiculousness** [comment]
I have inserted the SQL on the server. When I get home I will check if things are correct now.

**Comment by Alastyr** [comment]
@ridiculousness I have just understood what the problem is. You should complete both quests to take next quest. Both quests have nextquestreward set on 24814. Exclusivegroup is set on 24812. Someone forgot to put a minus sign before 24812.

The correct query is:
```
UPDATE quest_template_addon SET ExclusiveGroup=-24812 WHERE id IN (24812, 24813);
```

Now you must complete both quest to take the last quest of troll started zone, An Ancient Enemy.

I am no able to set up my locale server at the moment, but i remember that An Ancient Enemy quest (id=24814) was bugged on 4.3.4 project. Can you confirm this on 6.x project?

**Comment by Alastyr** [comment]
Have anyone tested my query? I'm pretty sure my solution will fix this bug.

**Comment by tkrokli** [comment]
Just to make the SQL query follow the TC codestyle, it is recommended that it looks like this:
```sql
-- make both quest 24812 & 24813 available to players:
UPDATE `quest_template_addon` SET `ExclusiveGroup`= -24812 WHERE `id` IN (24812, 24813);
```
It is customary to have either a comment line or just an empty comment ( -- ) above the query. I have also added back ticks around the table name and column names, which is recommended in TC codestyle.

About the lack of response to testing your suggested solution:
Maybe it is related to the recent game client update from Blizzard, to 6.2.3?

**Comment by Alastyr** [comment]
@tkrokli Thanks for following and helping. I think is better:
 ```
-- Make both quests 24812 & 24813 available to players: you must complete both quests to take next one, quest 24814.
UPDATE `quest_template_addon` SET `ExclusiveGroup`= -24812 WHERE `id` IN (24812, 24813);
 ```

About testing, it's not a problem, just curiosity. :+1:

**Comment by Aokromes** [comment]
This fix is valid?

**Comment by tkrokli** [comment]
Going to test this now. Luckily, these 2 quests are level 1-4 quests in the Troll starter area on 6.x, so it won't take long to check it on a new character.
