### ISSUE TITLE
 [Authserver][Crash] QueryResult: Access violation - NULL

### ISSUE THREAD

**Issue by Blacktempel** [TrinityCore/TrinityCore#15848]
Branch 3.3.5
Rev: https://github.com/TrinityCore/TrinityCore/commit/311a8df4b70d89780388213ab97e8a8186d5146b
http://pastebin.com/1MP4Fbyz

When starting Authserver.exe, it throws an access violation. (NULL)
The problem appears to be in .\src\server\Database\QueryResult.cpp(50) in the constructor of PreparedResultSet.

```cpp
if (m_stmt->bind_result_done)
{
    delete[] m_stmt->bind->length;
    delete[] m_stmt->bind->is_null;
}
```
Where m_metadataResult is valid but m_stmt->bind is NULL.

**Comment by Aokromes** [comment]
You are using modified authserver.

**Comment by Blacktempel** [comment]
I do not use a modified authserver. I never modified authserver code.

**Comment by Aokromes** [comment]
Revision: TrinityCore rev. 311a8df4b70d+ 2015-11-10 16:13:21 +0100 (3.3.5 branch) (Win32, Debug)
That + is modified source.

**Comment by Blacktempel** [comment]
The modification is in the .\src\server\scripts\Custom folder, which includes a sample NPC gossip script. That's all to it. Nothing regarding authserver.

**Comment by jackpoz** [comment]
how often does this issue happen ?

**Comment by jackpoz** [comment]
it should be investigated how m_stmt->bind_result_done is managed and in which case m_stmt->bind_result_done can be != 0 but m_stmt->bind NULL

**Comment by Blacktempel** [comment]
This issue happens everytime the authserver is started. Attached to the debugger or directly from the solution (config file in both paths).
I have tried to remotely debug this issue and figure out the problem, yet without success.
I have also pulled a fresh source from git without any custom scripts / modifications and encountered the same problem. (Rev same as in report)

**Comment by jackpoz** [comment]
could you post authserver logs ? even better if you set log level to something low like 1 (Trace)

**Comment by Blacktempel** [comment]
Log-level on trace.
http://pastebin.com/fY9fhr6n
After that it hits the exception.

**Comment by Blacktempel** [comment]
I had an **old compiled authserver** to start, and tried to start the **new worldserver.** Same problem with the worldserver.
http://pastebin.com/qK4nw0Fk
Exception at the same line. I will check changes of related files and reply if I found the issue. Also tried with different MySQL versions.

**Comment by Shauren** [comment]
Can you post CMakeCache.txt? You can find it in the same directory as VS solution file.

**Comment by Blacktempel** [comment]
CMakeCache:
http://pastebin.com/c3xZA0f4

**Comment by Shauren** [comment]
Random thought: you are building with libmysql.lib from MySQL server 5.7 installation but authserver console reported libmysql.dll version 5.6 loaded? Did you forget to copy over the new dll from 5.7 installation after you upgraded? (I assume you had 5.6 installed earlier)

**Comment by Blacktempel** [comment]
I copied the dll directly from the MySQL directory, let me try this again to verify.

**Comment by Blacktempel** [comment]
I copied the "libmysql.dll" from the directory "C:\Program Files (x86)\MySQL\lib" into the directory with the compiled executeables. This version appears to be 5.6.24.0.
The "libmysql.dll" of the "\MySQLServer 5.7" directory seems to be the correct current version 5.7.9.0.

Seems like I messed up.
