### ISSUE TITLE
[Druid] Prowl - Doesn't display cooldown

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15846]
Sometimes druid's prowl spells cause a cooldown bug as player cannot see the current display cooldown, so player never will able to use it againuntil player's relogin ( Same as priest shadow form )

3.3.5
Revision 7d5e7102cdd407846fa340892df39ea49938ee69

**Comment by Shauren** [comment]
Since you commented recently on #15755 please specify if this is because of duel cd reset or not.

**Comment by Runico** [comment]
@Shauren No, this happens without that script too,

**Comment by Goatform** [comment]
Is that old bug or bug caused by latest changes ?

**Comment by Runico** [comment]
@Goatform this is new bug, caused by latest changes

**Comment by Runico** [comment]
After recently update this issue seems doesn't happens anymore
