### ISSUE TITLE
[3.3.5] Core/Spells: Wrong application of talent's bonus in Renew spell

### ISSUE THREAD

**Issue by Asterc** [TrinityCore/TrinityCore#15855]
Talents that increase bonus seems to be applying more than it's supposed in spell Renew. I perform this tests with the spell [Renew, rank 14](wotlk.openwow.com/spell=48068) using human and night elf races

The results represent the healing amount of each renew Tick
with 0 spell power
280 -> withou talents
294 -> with [Twin Disciplines, rank 5](http://wotlk.openwow.com/spell=52803) correct increase of 5%
322 -> with [Improved Renew, rank 3](http://wotlk.openwow.com/spell=17191) correct increase of 15%
308 -> with [Spiritual Healing, rank 5 enUS](http://wotlk.openwow.com/spell=15356) correct increase of 10%

with 1000 spell power:
656 -> withou talents
707 -> with [Twin Disciplines, rank 5](http://wotlk.openwow.com/spell=52803) supposed 5%, real increase ~7,7%
818 -> with [Improved Renew, rank 3](http://wotlk.openwow.com/spell=17191) supposed 15%, real increase ~24,7%
762 -> with [Spiritual Healing, rank 5](http://wotlk.openwow.com/spell=15356) supposed 10%, real increase ~16,1%

with 2000 spell power:
1032 -> withou talents
1122 -> with [Twin Disciplines, rank 5](http://wotlk.openwow.com/spell=52803) supposed 5%, real increase ~8,7%
1315 -> with [Improved Renew, rank 3](http://wotlk.openwow.com/spell=17191) supposed 15%, real increase ~27,4%
1217 -> with [Spiritual Healing, rank 5](http://wotlk.openwow.com/spell=15356) supposed 10%, real increase ~17,9%

Branch 3.3.5
Hash 302623a1516e
TDB 335.60

**Comment by lyrl** [comment]
mark

**Comment by Asterc** [comment]
anybody suggests a place to start?

**Comment by tkrokli** [comment]
`/src/server/scripts/Spells/spell_priest.cpp` most likely. That is where `spell_pri_renew` is handlet.

**Comment by Keader** [comment]
It is strange why other spells receive bonuses from talents which increase Heal / damage for "percentage" of damage / healing. Only this receives no bonus is strange...

**Comment by sirikfoll** [comment]
Not valid at 164af391c9662732dfc9cfe677c48bd3f927c2be.
Couldn't find which commit fixed it tho
