### ISSUE TITLE
Compile Error 3.3.5

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15854]
Hi
I get 2 compile error
I use Visual Studio Express 2013

Release:
https://github.com/TrinityCore/TrinityCore/commit/880412205124570e6e90a3a3410303e71c800c9c

Fehler	2	error C2065: 'LIBMYSQL_VERSION_ID': nichtdeklarierter Bezeichner (D:\TrinityCoreSRC\src\server\worldserver\Main.cpp)	d:\trinitycoresrc\src\server\database\database\DatabaseWorkerPool.h	70	1	worldserver
Fehler	1	error C2065: 'LIBMYSQL_VERSION_ID': nichtdeklarierter Bezeichner (D:\TrinityCoreSRC\src\server\authserver\Main.cpp)	d:\trinitycoresrc\src\server\database\database\DatabaseWorkerPool.h	70	1	authserver

**Comment by Shauren** [comment]
Fixed in 536365a70ffc1c443dc8ca2b95081a3061be5478

**Comment by Tauriella** [comment]
WOW
thanks for your fast fix :+1:
