### ISSUE TITLE
[6.x][Mac] WoW Patched

### ISSUE THREAD

**Issue by hankxemn** [TrinityCore/TrinityCore#15858]
My Wow.app version is: 6.2.2 (20574).
Core revision hash: 17a5f51a29040d6f178bdc8a1a3fac4c6fa8c026
TDB version: N.A

When you connect everythings going fine, the problem is when disconnect.

After disconnect always appear #114 error when tries to connect, to solve it have to patch wow app another time and everytime u disconnect is necesary patch wow another time because it stop works.
Thanks for e8108b518b0f25bd6ae4e527aa25adde0ea6f9d4 !!!

**Comment by Carbenium** [comment]
Duplicate #13903
