### ISSUE TITLE
bnet- and worldserver error mysql related ?

### ISSUE THREAD

**Issue by CRHASH** [TrinityCore/TrinityCore#15869]
Hello

I have a problem with my new compiled trinitycore. I get this error when im trying to start bnet- and worldserver.
Fatal error: Used MySQL library version (5.6.17) does not match the version used to compile Trinitycore (5.6.25).
http://i.imgur.com/JcR5nwC.png

The weird issue is that i use MySQL 5.6.27.

I have tried to reinstall mysql, and recompile the core multiple times without sucess.

I also checked my log from the compile, but no errors there..

My setup:
Windows Server 2012 R2 (x64)
openssl 1.0.1p
cmake 3.3.0
MS Visual Studio community 2013
Boost 1.58 ?
MySQL 5.6.27
ZeroMQ 4.0.4
commit 0064fc23367681d86e7c563d9ef8cf270ee72723

I hope that anyone can help me :+1: 
// CRHASH

**Comment by Aokromes** [comment]
Read the error.

**Comment by DDuarte** [comment]
Your libmysql.lib and libmysql.dll versions do not match.

**Comment by Vincent-Michael** [comment]
copy your "libmysql.dll" from "C:\Program Files\MySQL\MySQL Server 5.x\lib\" in tc folder

**Comment by CRHASH** [comment]
Ok thanks guys it was the wrong .dll file + wrong sql version.
