### ISSUE TITLE
Build/Clang: Revert 98e7ab44 and 27bb5693 with introduction of Boost 1.60

### ISSUE THREAD

**Issue by Gacko** [TrinityCore/TrinityCore#15866]
... or when Boost manages to fix one of them:

https://svn.boost.org/trac/boost/ticket/11240
https://svn.boost.org/trac/boost/ticket/11767

**Comment by Naios** [comment]
You could disable the warnings only when using the affected boost versions...

**Comment by Aokromes** [comment]
Yeah, better than revert it, on that way if someone uses one linux distribution using 1.59 and don't wanna manually install 1.60 don't needs to readd that commit.

**Comment by Gacko** [comment]
The issue is not related to a specific boost version. Others using Linux, Clang 3.6.0+ and Boost 1.59 do not have this issue. It's related to the latest Apple Clang build, so I'd rather check for this.

**Comment by Gacko** [comment]
Boost 1.60 has been released. I'll test it and revert if it works.

**Comment by Gacko** [comment]
See https://github.com/TrinityCore/TrinityCore/commit/4eae523e327d8f7ac9d1fcdd02f602e25fa937a9.
