### ISSUE TITLE
[6.x][Quest] Crocolisk Mastery: The Ambush

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#15865]
rev. 00b4e8b6cc65 
When Bushwhacker appears, you can't attack it.
When you try, it just displays text "You cannot attack that target."

**Comment by tkrokli** [comment]
http://www.wowhead.com/npc=28317/bushwhacker (Added in patch 3.0.1)

Found out what could be wrong about that NPC/mob/beast by comparing the 6.x world DB with 3.3.5:
```sql
SELECT `entry`,`modelid1`,`name`,`minlevel`,`maxlevel`,`unit_flags`,`unit_flags2`,`lootid`,`AIName`,`MovementType`,`ScriptName`,`VerifiedBuild` FROM `creature_template` WHERE `name` = 'Bushwhacker';
```
6.x world DB:
```
 entry  modelid1  name         minlevel  maxlevel  unit_flags  unit_flags2  lootid  AIName  MovementType  ScriptName       VerifiedBuild
------  --------  -----------  --------  --------  ----------  -----------  ------  ------  ------------  ---------------  -------------
 28317     25298  Bushwhacker        76        76       33024         2048   28317                     0  npc_bushwhacker          20173
```

3.3.5 world DB:
```
 entry  modelid1  name         minlevel  maxlevel  unit_flags  unit_flags2  lootid  AIName  MovementType  ScriptName       VerifiedBuild
------  --------  -----------  --------  --------  ----------  -----------  ------  ------  ------------  ---------------  -------------
 28317     25298  Bushwhacker        76        76       32768         2048   28317                     0  npc_bushwhacker          12340
```
Notice in particular the column `unit_flags` which in 6.x is `33024` and in 3.3.5 is `32768`.
(http://collab.kpsn.org/display/tc/creature_template#creature_template-unit_flags)
- unit flag 32768 = `UNIT_FLAG_UNK_15` ("unknown" 15) is unrelated, but shared.
- unit flag 33024 = 32768 + 265
- unit flag 256 = `UNIT_FLAG_IMMUNE_TO_PC` (disables combat/assistance with PlayerCharacters (PC))

Possible solution (if not just a workaround) :
```sql
UPDATE `creature_template` SET `unit_flags` = 32768 WHERE `entry` = 28317;
```
... unless this is supposed to be done in the script `npc_bushwhacker` :
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L160
```cpp
/*######
## npc_bushwhacker
######*/

class npc_bushwhacker : public CreatureScript
{
public:
    npc_bushwhacker() : CreatureScript("npc_bushwhacker") { }

    struct npc_bushwhackerAI : public ScriptedAI
    {
        npc_bushwhackerAI(Creature* creature) : ScriptedAI(creature)
        {
        }

        void InitializeAI() override
        {
            if (me->isDead())
                return;

            if (TempSummon* summ = me->ToTempSummon())
                if (Unit* summoner = summ->GetSummoner())
                    me->GetMotionMaster()->MovePoint(0, summoner->GetPositionX(), summoner->GetPositionY(), summoner->GetPositionZ());

            Reset();
        }

        void UpdateAI(uint32 /*uiDiff*/) override
        {
            if (!UpdateVictim())
                return;

            DoMeleeAttackIfReady();
        }
    };

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_bushwhackerAI(creature);
    }
};
```
But seeing that the zone_sholazar_basin script is identical from 3.3.5 to 6.x, I prefer the SQL solution:
```sql
UPDATE `creature_template` SET `unit_flags` = 32768 WHERE `entry` = 28317;
```

**Comment by Maibenrai** [comment]
Hi
Thanks for a very good explanation! :+1: 
That worked.

How about:
```
-- Bushwhacker in Sholazar Basin. Quest: Crocolisk Mastery: The Ambush
-- Remove UNIT_FLAG_IMMUNE_TO_PC so you can attack Bushwhacker
SET @NPC := 28317;
SET @UNIT_FLAG_IMMUNE_TO_PC := 256;
UPDATE `creature_template` SET `unit_flags` = `unit_flags` & ~@UNIT_FLAG_IMMUNE_TO_PC
WHERE `entry` = @NPC;
```

**Comment by offl** [comment]
[He should have this flag.](https://youtu.be/-uMpfPAzlTk?t=49)
NPC just don't have propper SAI.

**Comment by tkrokli** [comment]
@Maibenrai : You're welcome, glad I could help. :smirk_cat: About your question and query example:
- For a 1-line update query, that is way too much extra settings, save it for scripts.
- No need for & ~@UNIT_FLAG_IMMUNE_TO_PC when you know the existing value is wrong.
- One extra comment line is just a little bit much when the query in itself is only 1 line.

... unless you want to document a lot for yourself. Trinity will keep it simple (K.I.S.S.).

**Comment by Maibenrai** [comment]
@offl Just tested again. I'm stunned for 30 sec and can only attack after that.

**Comment by tkrokli** [comment]
Please reopen this issue, unless it is solved in the 6.x source. I do not have the authority to make any changes to the source, so if this issue is real in the current 6.x source, this needs to stay open.
