### ISSUE TITLE
[3.3.5/Spell] Raise Dead cooldown dont work

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15862]
The Raise Dead (46584) spell is defective in its cooldown.
After use Raise Dead and gives dismiss on pet (or sacrifice with Death Pact) the spell not becomes available again (cooldown does not work), requiring relog for her to return to work.

Hash: eddc759cbe49d8a1170660ca825eb4af8b02caa3

**Comment by ccrs** [comment]
confirm 987c1a3a532fdc459b808be360431cba3c49792f

**Comment by Laintime** [comment]
confirm https://github.com/TrinityCore/TrinityCore/commit/f01ef901efab7f5b705948880c79eaf23061791e

**Comment by Re3os** [comment]
@Shauren it's back

**Comment by Keader** [comment]
yeah, It is more rare, but happen again.
