### ISSUE TITLE
[6.x] Dark portal Swap SQL

### ISSUE THREAD

**Issue by prestonjamesparsons** [TrinityCore/TrinityCore#15872]
commit 6b479e6c3e6bcd0d6495cd3a3f6ce01fa72f9d70
TDB: 6.03

INSERT INTO `terrain_swap_defaults` (`MapId`, `TerrainSwapMap`, `Comment`) VALUES (0, 1190, 'Blasted Land Terrian');

INSERT INTO `terrain_worldmap` (`TerrainSwapMap`, `WorldMapArea`, `Comment`) VALUES (545, 683, 'Blasted Land Swap');

I have tried that, Seem working well but npcs, mobs need to cleaning up there. 
If this useless just closed :)

**Comment by tkrokli** [comment]
I don't know about the usage and consequences of your SQL, but it needs to be repeatable:
```sql
-- 
DELETE FROM `terrain_swap_defaults` WHERE `MapId`= 0 AND `TerrainSwapMap`= 1190;
INSERT INTO `terrain_swap_defaults` (`MapId`,`TerrainSwapMap`,`Comment`) VALUES
(0, 1190, 'Blasted Land Terrian');

DELETE FROM `terrain_worldmap` WHERE `TerrainSwapMap`= 545 AND `WorldMapArea`= 683;
INSERT INTO `terrain_worldmap` (`TerrainSwapMap`,`WorldMapArea`,`Comment`) VALUES
(545, 683, 'Blasted Land Swap');
```
This needs feedback from someone who knows the 6.x branch better than me, of course.
(If this is found to be usable at all, a good comment line on top of the SQL would be useful.)

**Comment by prestonjamesparsons** [comment]
Great thank

**Comment by streetrat** [comment]
the old mobs should be in phase 169 or 0, the new lvl90 mobs should be in another phase, and the map swap should be linked to that new phaseid
so if you get the phase you get the swap too

**Comment by prestonjamesparsons** [comment]
it's can be done in creature table?

**Comment by streetrat** [comment]
creature+gameobject+terrain_phase_info+phase_area+conditions
(hint: 2801 is the phaseid used for that on blizz)
or it can be done with terrain_swap_defaults+conditions too, but its easier with area

**Comment by prestonjamesparsons** [comment]
Alright, trying sort those npcs, though its easier but nah its hard lol

**Comment by streetrat** [comment]
only the old lvl 50-ish mobs are spawned in tc db, no?

**Comment by tkrokli** [comment]
That is correct, there are no interesting (or related) mobs above level 83-85 spawned in the 6.03 DB.
