### ISSUE TITLE
[3.3.5][6.x] Core/Creature: Visual effect on Trigger npc

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#15888]
Issue from: https://github.com/TrinityCore/TrinityCore/issues/15566

I have a problem with visual auras on npcs with extra_flag trigger.

If I .cast self 56135 or .aura 56135 the visual effect appears.

If the spell is casted with linked_spell or casted using SAI or the aura added by SAI the visual effect is visible on gm mode only.

Also if the aura is set on creature_addon the visual will appear.

The visual effect: http://www.wowhead.com/item=42252/frozen-iron-scrap#screenshots:id=99095
TrinityCore rev. 1511855fea15

```
ServerToClient: SMSG_AURA_UPDATE (0xE86C) Length: 24 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238994
GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
[0] Slot: 0
[0] Spell ID: 56135 (56135)
[0] Flags: EffectIndex0, NotCaster, Positive, Duration (57)
[0] Level: 80
[0] Charges: 0
[0] Max Duration: 15000
[0] Duration: 15000

ServerToClient: SMSG_SPELL_START (0xDB2F) Length: 33 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238995
Caster GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Caster Unit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Cast Count: 0
Spell ID: 56135 (56135)
Cast Flags: HasTrajectory (2)
Time: 0
Target Flags: Self (0)

ServerToClient: SMSG_SPELL_GO (0xEC2D) Length: 44 ConnIdx: 0 Time: 06/19/2011 23:57:18.000 Number: 238996
Caster GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Caster Unit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Cast Count: 0
Spell ID: 56135 (56135)
Cast Flags: Unknown7 (256)
Time: 2850580801
Hit Count: 1
[0] Hit GUID: Full: 0xF13075D9006E6FCC Type: Creature Entry: 30169 Low: 7237580
Miss Count: 0
Target Flags: Unit (2)
Target GUID: 0x0

**Comment by Pitcrawler** [comment]
I think this is due to the handling of flags_extra=128. Related #15416

If you remove flags_extra=128 and set the modelid of the trigger npc in the creature table to the invsible entry I guess it will work.

**Comment by Killyana** [comment]
This issue is wrong. Visual effects are visible on npc triggers.
