### ISSUE TITLE
[3.3.5] Database Errors

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15887]
http://paste.ubuntu.com/13477452/

Rev f012800751396309e75d0baf4ed3406855c8e93a

**Comment by jackpoz** [comment]
are there any known how to reproduce steps ?

**Comment by Runico** [comment]
@jackpoz, i have found the issue, that caused by .pdump command

**Comment by Rushor** [comment]
@Runico: This issue still happens?

**Comment by Runico** [comment]
@Rushor, not anymore
