### ISSUE TITLE
vMAP Extract

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#15897]
Commit : https://github.com/TrinityCore/TrinityCore/commit/e4bdaa01106fffe23ac3b0c7511a7ffe5ea8fd47

vMap 4 Extractor opening the path with back and for slashes ! Is that an issue or is that normal!?

```quote
Opening Data\enUS/locale-enUS.MPQ
Opening Data\enUS/expansion-locale-enUS.MPQ
Opening Data\enUS/lichking-locale-enUS.MPQ
Opening Data\common.MPQ
Opening Data\common-2.MPQ
Opening Data\expansion.MPQ
Opening Data\lichking.MPQ
Opening Data\patch.MPQ
Opening Data\patch-2.MPQ
Opening Data\patch-3.MPQ
Opening Data\patch-4.MPQ
Opening Data\enUS/patch-enUS.MPQ
Opening Data\enUS/patch-enUS-2.MPQ
Opening Data\enUS/patch-enUS-3.MPQ
```

**Comment by tkrokli** [comment]
This is normal (check the source code in commit https://github.com/TrinityCore/TrinityCore/commit/e4bdaa01106fffe23ac3b0c7511a7ffe5ea8fd47 ), usually it should not be a problem.
You can also compare with how Git and CMake handle folder paths, slash ( / ) is used then too.
