### ISSUE TITLE
[3.3.5]Spell:arcane-missiles 

### ISSUE THREAD

**Issue by Re3os** [TrinityCore/TrinityCore#15902]
rev. https://github.com/TrinityCore/TrinityCore/commit/3b90b0368a019d47911062da6257555e88d17fda
branch 3.3.5 
This commit is break spell https://github.com/TrinityCore/TrinityCore/commit/246e568bbd1c741af7204e4a4941c113b7d63e60

Cast http://www.wowhead.com/spell=30451/arcane-blast ,proc http://wotlk.openwow.com/spell=44401/missile-barrage 
cast http://www.wowhead.com/spell=5143/arcane-missiles one charge. 
Normal 5 charges.

**Comment by tkrokli** [comment]
Very few of the developers are Russian, they prefer links to English pages. Is the info the same here?
- http://www.wowhead.com/spell=30451/arcane-blast
- http://wotlk.openwow.com/spell=44401/missile-barrage

**Comment by Re3os** [comment]
@tkrokli thk,update issue.

**Comment by shenhuyong** [comment]
Confirmed

**Comment by boom8866** [comment]
Confirmed

**Comment by ShinDarth** [comment]
Ok well this should fix the issue:

https://github.com/TrinityCore/TrinityCore/pull/15907

maybe this time you can help me and test it **BEFORE** it get merged into TrinityCore. We need to ensure that there are no more broken spells.

Thanks.

**Comment by Re3os** [comment]
@ShinDarth Im tested this pull,it;s work.
THANK YOU!!!!
