### ISSUE TITLE
[3.3.5] Core/Mechanic: ResetCooldown() also removes GlobalCooldown

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15911]
rev: https://github.com/TrinityCore/TrinityCore/commit/3c4f4356298d974c507fbd4c3fa54c1d4075e091
Issue:
If you use the function ResetCooldown() like in spell_gen_divine_storm_cd_reset (https://github.com/TrinityCore/TrinityCore/blob/d03ca37f10e74ec7fe5d06957d66574b0fe14af2/src/server/scripts/Spells/spell_generic.cpp#L1359)
the running global cooldown will also be removed in the interface.

The remove of the global cooldown while using ResetCooldown() should not happen optically.
The global cooldown must always be displayed in the interface.

How to reproduce:
- Create paladin
- learn spell Divine Storm
- apply aura 70765
- apply several enrage auras in order to meleehit faster 
  (
  .aura 34409
  .aura 39249
  .aura 24318
  .aura 44779
  .aura 41305
  .aura 40743
  .aura 40683
  .aura 65126
  .aura 8269 
  .aura 24318
  .aura 44779
  .aura 41305
  .aura 40743
  )
- spamm paladin spell Divine Storm

Result: 
- Each time spell 70765 proccs the global cooldown of the paldin spell Divine Storm will also be removed.

This should not happen and causes visual issues (e.g. the player wants to cast Divine Storm because he cannot see any global cooldown in the interface, but if he clicks the spell he will get the error message that the ability is on cooldown)

Source:
https://youtu.be/bJxKUaKKmQE?t=244

Here you can see, that the global cooldown for spell Divine Storm is not removed from the interface if spell 70765 proccs.

**Comment by Trisjdc** [comment]
Interesting. Weird though, since SpellHistory::ResetCooldown only sends a SMSG_CLEAR_COOLDOWN, nothing else.

Any sniffs anywhere to see what was sent instead?

**Comment by Shauren** [comment]
Works in 6.x

**Comment by Rushor** [comment]
hm yeah the only stuff which will be sended by the spellscript is:

```c++
    WorldPacket data(SMSG_CLEAR_COOLDOWN, 4+8);
    data << uint32(spell_id);
    data << uint64(target->GetGUID());
    SendDirectMessage(&data);
```
any idea why the global cooldown of the paldin spell Divine Storm isn't removed after the cast of 70765 in the 6.x branch?

**Comment by Keader** [comment]
if i remember right, GCD is stored in spell that trigger it in 3.3.5 client
so if you clear cooldown of spell, gcd will be reseted (in client side) too

**Comment by Shauren** [comment]
I rewatched the video more closely, gcd resets when it procs right after using divine storm

bug is blizzlike
