### ISSUE TITLE
[3.3.5] Comp/core: Character stats save

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#15928]
Something is wrong in character stats save

No caster character has spellCritPct in table `character_stats`
All stats are saved without mods (?) (different numbers, lower, to client ones)

c703e01471a3598f68051abb17e598e316b744ef

**Comment by jackpoz** [comment]
what's a "character stats save" ? what's "spellCritPct" ? what's the ingame issue ?

**Comment by ccrs** [comment]
not ingame, but a feature of the core -> ````void Player::_SaveStats(SQLTransaction& trans)````

**Comment by DDuarte** [comment]
Let's try again.

What is the issue?

**Comment by ccrs** [comment]
.... 

the issue is that some stats arent saved correctly into the table. just like ````spellCritPct```` or ````rangedCritPct````

**Comment by ccrs** [comment]
to test it, just enable stats save and check a mage or a warlock.

**Comment by DDuarte** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by ccrs** [comment]
stats for a warlock in the table
`````
guid, maxhealth, maxpower1, maxpower2, maxpower3, maxpower4, maxpower5, maxpower6, maxpower7, strength, agility, stamina, intellect, spirit, armor, resHoly, resFire, resNature, resFrost, resShadow, resArcane, blockPct, dodgePct, parryPct, critPct, rangedCritPct, spellCritPct, attackPower, rangedAttackPower, spellPower, resilience
'3', '20366', '24186', '1000', '0', '100', '0', '0', '1000', '72', '74', '1341', '1374', '398', '2337', '0', '0', '0', '0', '0', '0', '0', '3.65966', '0', '17.5724', '12.3724', '0', '62', '64', '2867', '0'
````
![image](https://cloud.githubusercontent.com/assets/4329612/11511421/4993c628-9869-11e5-9fa1-b2d6e5c03d60.png)

**Comment by Aokromes** [comment]
[12:49:05] Aokromes> iirc not a bug

**Comment by ccrs** [comment]
everything is correct except from crit chance, kinda suspicious xd

**Comment by ariel-** [comment]
Ok, let's try to translate this issue:

Something is wrong in the table character_stats (ie, when setting PlayerSave.Stats.MinLevel greater than 0)

Caster characters get a saved value of 0 for spell crit pct, while ingame this is not 0.

After a bit of research in Player::_SaveStats, I can conclude the problem is using ```stmt->setFloat(index++, GetFloatValue(PLAYER_SPELL_CRIT_PERCENTAGE1));```

PLAYER_SPELL_CRIT_PERCENTAGE1 gets the spell crit % for SPELL_SCHOOL_NORMAL, which is 0, apparently.

**Comment by Aokromes** [comment]
still valid?

**Comment by CraftedRO** [comment]
yes still valid on e6d9d9ead99a with two rings of critical testing , character have 0 spell crit saved .

![Untitledzq](https://user-images.githubusercontent.com/24683355/114278128-f1c40900-9a36-11eb-9c95-d87c1ac69394.jpg)
