### ISSUE TITLE
Unresolved external mysql 5.7.9.1

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15923]
Core:https://github.com/TrinityCore/TrinityCore/commit/01beba21b5210860ddd6a37471c6b2bea77a369e
 MySQL 5.7.9.1 detected by cmake
But unable to solve the lack of external file binary_log_types.h

Program source http://dev.mysql.com/downloads/windows/installer/5.7.html

Back to 5.6 can pass, do not know is not my own problem

**Comment by Maibenrai** [comment]
binary_log_funcs.h and binary_log_types.h are missing from the mysql 5.7 community installer installation.

http://stackoverflow.com/questions/30678557/binary-log-types-h-no-such-file-or-directory

**Comment by tkrokli** [comment]
Yes, I commented in that thread on stackoverflow too. Basically, you can get the files here:

Folder: https://github.com/mysql/mysql-server/tree/5.7/libbinlogevents/export
- https://github.com/mysql/mysql-server/blob/5.7/libbinlogevents/export/binary_log_funcs.h
- https://github.com/mysql/mysql-server/blob/5.7/libbinlogevents/export/binary_log_types.h

Just like in the TC source, the .h files are pure text files, so copy/download them as you want.

**Comment by Shauren** [comment]
To my knowledge only the x64 installer lacks these files (BUT BY NO MEANS I AM SUGGESTING TO USE x86, LET 32 BIT ARCHITECTURE DIE ALREADY)
