### ISSUE TITLE
[3.3.5][6.x][Core/Spell] Rotting Putrescence - Overpowering Sickness

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15926]
rev: https://github.com/TrinityCore/TrinityCore/commit/3c4f4356298d974c507fbd4c3fa54c1d4075e091

quest=10547
spell=36810
(moreover: dk spell Blood Presence www.wowhead.com/spell=48263)

Issue:
Player gets selfheal in bloodpresence (if you are a deathknight) an the periodic spell spell=36810 triggers spell=36809

How it should be:
spell=36809 should not trigger any selfheal for the player.

Additional:
I think the problem here is that spell=36809 gets triggered by the player itself. The Bloodpresence of the DK will procc on every harmful cast. The player casts 36809 on hiself and triggers the procc of the Blood Presence. 

http://www.wowhead.com/quest=10547/of-thistleheads-and-eggs
http://www.wowhead.com/spell=36810/rotting-putrescence
http://www.wowhead.com/spell=36809/overpowering-sickness

**Comment by Rushor** [comment]
maybe this:
spellInfo->AttributesEx3 |= SPELL_ATTR3_CANT_TRIGGER_PROC;

solves the issue

**Comment by tkrokli** [comment]
Spell & Quest names: (remove this post if you find it redundant)

http://www.wowhead.com/quest=10547/of-thistleheads-and-eggs
http://www.wowhead.com/spell=36810/rotting-putrescence
http://www.wowhead.com/spell=36809/overpowering-sickness

**Comment by Rushor** [comment]
i cannot find any sources for this issue - closing until i find something for this
