### ISSUE TITLE
[3.3.5][6.x] DB/Gameobject: Netherwing Egg - Linking Spawn to Trap Netherwing Egg Dust (Visual)

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#15927]
rev: https://github.com/TrinityCore/TrinityCore/commit/3c4f4356298d974c507fbd4c3fa54c1d4075e091

object=185915
trap - object=185600

Issue:

object=185915 (the egg itself) should be linked to object=185600 (the dust visual). Each time The egg 185915 spawn, the dust 185600 should spawn in the same location like the egg.

IMPORTANT: We cannot simply add a dbspawn here because the eggspawn itself should be pooled.

What do you tried to fix the issue:
I already tried to add dbspawn and inserts in https://www.trinitycore.info/display/tc/linked_respawn ,  but this does not solved the issue.

Basically we need a script which executes two things:
1) If the egg 185915 spawn from the pool, the egg-go should spawn the dustgo 185600
2) If the egg-go 185915 was looted and changes it lootstate, the dustgo 185600 should despawn.

Problem A) Moreover each time if an egg 185915 from the pool respawns, the dustgo 185600 must be summoned again.
Problem B) Actually egg-go 185915 contains datas on the trap - object=185600 in the gameobject_template. But somehow the trap will not be spawned.
(Summoning @Gacko for this, because he maybe knows more about it)

Note:
I have no fucking idea how to solve this with SAI. I already worked out a hackshit coresolution but i could not solve Problem A. I will post the script here later.

Labels: Core + DB, not shure where it must/could be fixed

**Comment by Shauren** [comment]
You can use a pool of pools
instead of pooling eggs you pool pools of egg+dust pairs (each egg+dust pair would be in its own separate pool managed by the global one)

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/12139

**Comment by Kittnz** [comment]
I guess it's also the same for these mana crystal crates that have a glow on them and if the gob is looted the glow goes away too

**Comment by Rushor** [comment]
Found even more datas in a githubproject which i don't want to link here because i don't know if they like it

Text from the issue:



Issue: Some gameobjects should be scripted to spawn and despawn together with other gameobjects. For example gameobjects with type trap, that should spawn and despawn with the gameobject that triggers the trap. Or gameobjects that are supposed to give visual effect (glow) around another gameobject.

Current situation: At the moment most of the additional gameobjects are spawned permanently and don't despawn/respawn with the corresponding gameobject, or are not spawned at all.

List of the gameobjects that should be scripted to spawn/despawn together. Later on I will use the word "linked", meaning that the "slave" gameobject should be scripted to spawn together at the same place as the master object and despawn when the master object despawns.
ID 181272 (Dreaming Glory) should be linked to Master ID 181271 (Dreaming Glory) and Master 183054 (Dreaming Glory) - that's a trap triggered when Dreaming Glory is looted.
ID 181284 (Mana Thistle) should be linked to Master ID 181281 (Mana Thistle) - same as above.
ID 181282 (Netherbloom) should be linked to Master ID 181279 (Netherbloom) - same as above.
ID 185600 (Netherwing Egg Trap (gas)) should be linked to Master ID 185915 (Netherwing Egg) - visual gas around Netherwing Eggs - supposed to make the eggs easier to find.
ID 183768 (Etherlithium Matrix Crystal) should be linked to Master ID 183767 (Etherlithium Matrix Crystal) - visual glow around quest item - supposed to make it easier to find.
ID 184868 (Baa'ri Tablet Aura) should be linked to Master ID 184869 (Baa'ri Tablet Fragment) - same as above

**Comment by Shauren** [comment]
If these objects are traps summoned by this mechanism https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/GameObject/GameObject.h#L70 then it really needs more research (GameObjects in general too, they are poorly researched)

**Comment by Rushor** [comment]
hm yeah each object from above has the same structure
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (181271, 3, 181272);
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (181279, 3, 181282);
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (181281, 3, 181284);
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (183767, 3, 183768);
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (184869, 3, 184868);
INSERT INTO `gameobject_template` (`entry`, `type`, `data7`) VALUES (185915, 3, 185600);

**Comment by Shauren** [comment]
Most of the object pairs you linked follow the same template - trap with effect casting spell on use
But the one clearly breaking the pattern is Netherwing Egg - its almost a rule that all "trap" objects like this are never sent to client (especially not on spawn) so it must be used for something else

**Comment by dr-j** [comment]
Also maybe worth pointing out that on tc all spawns of netherwing egg are on the ledge (above ground) on retail these do spawn in the mines actually on retail I never found one above ground and never really found that many in mine either but all the ones I did manage to find where in mines and never managed fo farm more than 2 in a day, and dont think I found at same spot more than once either.

**Comment by Kittnz** [comment]
respawn timer is really long on these, atleast 6 hours if not more however these do respawn quicker if a lot of people are in the zone, but thats another issue, i did farm the eggs on the ledge and also in the mines, i added waypoints and new spawns in the mines but didn't add any eggs

**Comment by ellone716** [comment]
gameobject cant be respawn or despawn by respawn or despawn command,but maybe we could deal it with SAI,just set loot state 3 to despawn and 1 to respawn the closest gobject,such as the trap of Netherwing Egg, use action_type99, can it be work?

**Comment by Rushor** [comment]
and which action (i mean ingameaction not action in sai) should trigger the despawn and respawn?
how can we get the information, that the egg is recently respawned/despawned?

**Comment by tkrokli** [comment]
If the eggs are only respawned when a player loots an egg (except for those spawned at server start), could the loot action trigger a new respawn? Or is there a mechanism to check for a constant number? Maybe this could be sniffed, just to see which actions and opcodes are triggered upon looting. I would not think there is a need for the game to change the spawns without player interaction.

**Comment by Rushor** [comment]
could the loot action trigger a new respawn?

>> yeah the despawn of the egg could trigger the despawn of the dust

BUT:

which action should respawn the dust, if the egg respawns (remember that the go's are pooled, or at least they should be pooled)

**Comment by ellone716** [comment]
I have an idea,but I need a deeply test to confirm,can we use SAI event_type 70 value 1,action_type 99 set value 1 with an actionlist in 1min?   and  event_type 70 value 3,link an actionlist with two steps: 1st is to set the dust state value to 3,  2nd is to set the loot state to another closest or range or distance egg. can it be work?  I'm not sure if this can worked with pool system perfectly.but it just a way

**Comment by tkrokli** [comment]
@Rushor : Shauren mentioned using "a pool of pools", is that the same as the `pool_pool` table?

**Comment by ellone716** [comment]
UPDATE `gameobject_template` SET `AIName` = 'SmartGameObjectAI' WHERE `entry` = 185915;
DELETE FROM `smart_scripts` WHERE (`entryorguid`=185915 AND `source_type`=1);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(185915, 1, 0, 0, 70, 0, 100, 0, 2, 0, 0, 0, 99, 3, 0, 0, 0, 0, 0, 20, 185600, 3, 0, 0, 0, 0, 0, ""),
(185915, 1, 1, 0, 11, 0, 100, 0, 0, 0, 0, 0, 99, 1, 0, 0, 0, 0, 0, 20, 185600, 3, 0, 0, 0, 0, 0, "");

it works perfectly with respawn and despawn

**Comment by mvelasco93** [comment]
@tkrokli yes

**Comment by Rushor** [comment]
@ellone716: do you tried this script also with pooled gameobjectspawns?
