### ISSUE TITLE
[3.3.5]Warrior Neferian Berserk

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#15924]
Core:https://github.com/TrinityCore/TrinityCore/commit/01beba21b5210860ddd6a37471c6b2bea77a369e
DB:TDB60
update:2015_11_27_00_world.sql
boss_Neferian.cpp
#14845 
When Neferian cast Berserk (http://www.wowhead.com/spell=23397) Players can learn by http://wotlk.openwow.com/spell=29759 Can be switched

This may cause the player to be repeatedly added, and by a huge amount of damage.

I know this is because the Stance is the Neferian's own spell, but not the player to switch to the player.

lease excuse my English

**Comment by Aokromes** [comment]
#14845
