### ISSUE TITLE
[Crash] BIHWrap<GameObjectModel, BoundsTrait<GameObjectModel> >::remove

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15941]
http://paste.ubuntu.com/13661357/

Branch 3.3.5
Revision 8524faae94601621b16002aadb96f6d931d29f64

**Comment by jackpoz** [comment]
I see a "this=0x0" , not sure tho if that can be trusted with a Release crash log

**Comment by Runico** [comment]
this is my config
```
-DWITH_COREDEBUG=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```

**Comment by Re3os** [comment]
@Runico use
```sql cmake ../ -DCMAKE_INSTALL_PREFIX=/home/test -DWITH_COREDEBUG=1 -DCMAKE_BUILD_TYPE=Debug
```

**Comment by Aokromes** [comment]
-DWITH_COREDEBUG=1 is useless for crashlogs.

**Comment by Rushor** [comment]
@Runico: This issue is still present?

**Comment by Runico** [comment]
@Rushor, Doesn't happens recently

**Comment by Rushor** [comment]
well okay, bumb the issue if it happens again, closing for now
