### ISSUE TITLE
[3.3.5][Crash] Player::GetCollisionHeight

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15943]
http://paste.ubuntu.com/13677838/

Branch 3.3.5
Revision 94e4bddb903d581293b5a7f50f9b32d1262d2c20

**Comment by Runico** [comment]
http://paste.ubuntu.com/13950022/

**Comment by tkrokli** [comment]
I was trying to look up the points the logs refer to but 2 things are a bit odd about this issue:

1. The crash logs refer to line 26392 in Player.cpp, but Player.cpp has 30 26363 lines on that commit. The 3.3.5 commit  94e4bdd (same time as the 6.x commit) version of Player.cpp has 26307 lines. Are  the line numbers counted differently in runtime or different OS types?

2. The core rev. hash 8524faa is from 6.x, but issue title says 3.3.5. Which one is correct?

**Comment by Runico** [comment]
@tkrokli Revision updated, 94e4bddb903d581293b5a7f50f9b32d1262d2c20 is the correct one

**Comment by tkrokli** [comment]
OK, I thought it could be that version. Even so, it seems as if your core thinks that Player.cpp has got 26392 lines, 85 more lines than it had on that revision. Have you possibly added extra code to that file?

**Comment by Runico** [comment]
@tkrokli Yes i have extra code, but they aren't hardcode

**Comment by Shauren** [comment]
This is an assertion failure however for whatever reason the crash log does not have the message where it should be present
```message=0x7ffff4e139fa <_IO_vfprintf_internal+22490> "\200\275(\373\377\377"``` instead of proper text, could you supply a console log (not log files created by TC itself but one you could get by redirecting output with >)? GetCollisionHeight has multiple assertions

**Comment by Runico** [comment]
@Shauren how could i get that log ?

**Comment by tkrokli** [comment]
@Runico : if you are using a Linux OS, type `worldserver > console_log.txt` at the prompt.
If you are running this on a Windows OS, open a CMD window and run the same command there.
(Maybe I haven't provided the accurate startup command for Linux, check your regular command.)

**Comment by Rushor** [comment]
@Runico: This issue is still present?

**Comment by Runico** [comment]
@Runico, It's happens, but i have to remove that part, So Problem Solved :dancer:
an that's not right way

**Comment by SQLfix** [comment]
i have this crash too
3.3.5
https://github.com/TrinityCore/TrinityCore/commit/6cf1446d39db994cdca2db8f7f61da8423672bb3

http://paste.ubuntu.com/16565492/

in my crash log

Mount (this=0x7fffa4204000, mount=14578, VehicleId=0, creatureEntry=14549

mount 14549  [Great Brown Kodo]
3x crash with this entry

** I have some custom cod in player.cpp  (but they aren't hardcode)
