### ISSUE TITLE
[ITEM] Ashen Band of Endless Wisdom

### ISSUE THREAD

**Issue by arnisgd** [TrinityCore/TrinityCore#1594]
The proc of this ring http://www.wowhead.com/item=50400 might not be working properly. As it is said: Your helpful spells have a chance to increase your spell power by 285 for 10 sec. it sould proc form any helpfull spells, but  you will never get it proced becouse such helpfull spells like: http://www.wowhead.com/spell=17, http://www.wowhead.com/spell=139, http://www.wowhead.com/spell=70772, http://www.wowhead.com/spell=528, http://www.wowhead.com/spell=527, http://www.wowhead.com/spell=33076 of any rank and improvement are not counted as a helpfull spells, so as a discy pve priest it is imposible to proc the ring effect while healing only with these instant skills, unless you use direct healing spells like http://www.wowhead.com/spell=2061, http://www.wowhead.com/spell=2060, http://www.wowhead.com/spell=47540 and etc.

Don't know if it really should proc from these spells but as mentioned in proc description http://www.wowhead.com/spell=72419 spells above should be counted as helpfull otherwise pve disc priests will never triger this proc unless they cast so its like 2-3 trigers durnig 2 hour raid.

If you need more info i can give you some test results.

**Comment by Rushor** [comment]
is there any reliable source that proofs that it should proc on hots?

**Comment by Keader** [comment]
item still present in retail...
Someone has a retail account and have time to farm icc reputation?

**Comment by Kittnz** [comment]
I have it on my paladin, i can check tonight.

**Comment by Kittnz** [comment]
I tested this on my priest, since she has it as well.
It does not proc on hots, however on the initial cast it can proc. But not the hot.

**Comment by Keader** [comment]
Thank you @Kittnz .

**Comment by Kittnz** [comment]
You are welcome @Keader
