### ISSUE TITLE
Quest Taken in the Night 10873

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#15945]
I use TrinityCore rev. 984bf32fa89d 2015-12-05 03:53:51 +0100 (HEAD branch)
http://www.wowhead.com/quest=10873/taken-in-the-night

On Trinity Comes to many creatures from the Cocoon on BlizServer Comes only one from the Cocoon.

**Comment by Killyana** [comment]
You can have look here:
https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/src/server/scripts/Outland/zone_terokkar_forest.cpp#L290

**Comment by dr-j** [comment]
On retail a lot of different creatures which can be found elsewhere in terokkar forrest can be released from these cocoons, confirming various creatures spawn have seen Bonelashers, Doomspeakers, Arrokoa,

And in spell_dbc you will find the following spells even though they have effect 41 but changing that to 28 will usually summon

Id,EffectMiscValue1,Comment
38953,16805,Terokkar Free Webbed Creature http://www.wowhead.com/npc=16805/broken-skeleton
38955,21242,Terokkar Free Webbed Creature http://www.wowhead.com/npc=21242/auchenai-death-speaker
38956,18470,Terokkar Free Webbed Creature http://www.wowhead.com/npc=18470/bonelasher
38957,21661,Terokkar Free Webbed Creature http://www.wowhead.com/npc=21661/cabal-skirmisher
38958,18452,Terokkar Free Webbed Creature http://www.wowhead.com/npc=18452/skithian-dreadhawk
38978,22459,Terokkar Free Webbed Creature http://www.wowhead.com/npc=22459/freed-shatar-warrior

**Comment by Aokromes** [comment]
#16098
