### ISSUE TITLE
SIG_ABORT with unknown origin...

### ISSUE THREAD

**Issue by et65** [TrinityCore/TrinityCore#15951]
Very weird crash randomly at every 30-40 minutes like https://github.com/TrinityCore/TrinityCore/issues/15892

http://pastebin.com/r1fdrkfs

I don't know the origin but maybe someone of you know?

TC rev https://github.com/TrinityCore/TrinityCore/commit/93c4710c3838c3cebc164bcbb1715bfd46844ab8

**Comment by Shauren** [comment]
There is absolutely nothing in this log.

**Comment by et65** [comment]
Yes but can't do more without build the core in debug which is not recommended in production and this bug just happens in production...

**Comment by tkrokli** [comment]
"No such file or folder type." (`Aucun fichier ou dossier de ce type.`) and only referencing `../nptl/sysdeps/unix/sysv/linux/raise.c` (and other system files) - No clues to go on, just like Shauren said.

I know it is not recommended as a debug option, but what about DebWithRelInfo to see if you can trigger at least some clues about what is happening? What about extra logs in addition to the default logs?

**Comment by Shauren** [comment]
Don't expect us to try and track down something that only happens without debug info.
