### ISSUE TITLE
[6.x] NPC Diktynna not working

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#15971]
5bf9d2bed434

NPC: http://www.wowhead.com/npc=17101/diktynna

When pressing "Please teach me how to fish, Diktynna." or "I wish to browse your wares, Diktynna.", nothing happens.

![diktynna](https://cloud.githubusercontent.com/assets/1616448/11691745/b759b6ca-9e9c-11e5-9d42-1d7957735723.png)

**Comment by GnaXi** [comment]
Turns out that if you press "I wish to browse your wares, Diktynna" first, you are able to see what Diktynna is selling. If you press "Please teach me how to fish, Diktynna." and then press "I wish to browse your wares, Diktynna", it won't open.
Probably related to: https://github.com/TrinityCore/TrinityCore/issues/14682

**Comment by Killyana** [comment]
same issue as https://github.com/TrinityCore/TrinityCore/issues/14682
