### ISSUE TITLE
[6.x] NPC - "Cookie" McWeaksauce

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#15975]
5bf9d2bed434

NPC: http://www.wowhead.com/npc=17246/cookie-mcweaksauce
Clicking "Teach me how to cook, Cookie." does nothing.

![cookie](https://cloud.githubusercontent.com/assets/1616448/11695937/2ce1fb22-9eb2-11e5-801a-c6676404e84c.png)

**Comment by DDuarte** [comment]
Is the issue specific to this npc only or all (cooking) trailers?

**Comment by Shauren** [comment]
Check the branch. No trainers have db data in 6.x

**Comment by GnaXi** [comment]
So data already exist, but hasn't been implemented yet?

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/14682
