### ISSUE TITLE
Quest: Death Comes From On High: Can't be completed

### ISSUE THREAD

**Issue by aaplmike** [TrinityCore/TrinityCore#15978]
The quest http://www.wowhead.com/quest=12641/death-comes-from-on-high allows you to drive around the Eye of Archerus, however won't allow you to "analyze" any of the four target buildings. Also, there are no NPCs in the zone, where there are usually a great number that will shoot at the eye if it gets close enough. I believe this is a required quest to get beyond the starting zone for Death Knights. The quest adds two additional buttons, an "Eye of Archerus" and "Cancel". Clicking Cancel does return you to the starting point of the quest. Clicking the other has no affect. 

TrinityCore rev. 4695e234912e 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)
Database: TDB 6.03

**Comment by Aokromes** [comment]
#14928

**Comment by tkrokli** [comment]
@aaplmike : you may want to add your info to that open quest, as a confirmation with core rev. and extra information.
