### ISSUE TITLE
[3.3.5][DK] DB/Spell:  Runic Power Back on Snare/Root Spell Proc Error

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#15974]
Spell: http://www.wowhead.com/spell=61257
Description: Whenever you are struck by a movement-impairing effect, you will generate 3 Runic Power every 1 sec for 5 sec.

Problem: Effect is working for some spells (like Roots Druid), however there are spells that are not activating effect, example the root of Earthbind Totem (with Storm, Earth And Fire).

Old Issue About That: #511
Commentary important: https://github.com/TrinityCore/TrinityCore/issues/511#issuecomment-5521018

TC Hash: c182ea010c090c8695afbda690b8f4db48c356a7

**Comment by Keader** [comment]
I do not know if it's the definitive solution, but much improved effect
```sql
DELETE FROM `spell_proc_event` WHERE `entry` = 61257;
INSERT INTO `spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES
(61257, 0, 0, 0, 0, 0, 131752, 65536, 0, 0, 0);
```

sql by: @Riztazz

**Comment by Rushor** [comment]
this fix is considered as hack?

**Comment by Keader** [comment]
I think, because glyph of shadow flame dont work
