### ISSUE TITLE
[6.x] Spell - Seal of Command

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#15972]
5bf9d2bed434

Spell: http://www.wowhead.com/spell=105361/seal-of-command

When you receive it and activate it, the seal seems to be active when looking at the action bar, but it is not applied to the hero. Seal of Command cannot be deactivated again either, so it is stuck in this non-functional state.
Only been tested with the Draenor.
The spell Judgment can't be used, because the seal is not applied.

![sealofcommand](https://cloud.githubusercontent.com/assets/1616448/11691971/ac6c6b76-9e9d-11e5-9394-72c288f5b4ec.png)

**Comment by dansanti** [comment]
This mision can't be completed http://www.wowhead.com/quest=24528/the-power-of-the-light because Use Seal of Command and Hit a Training Dummy is needed , and seems Seal of command not working

**Comment by Rushor** [comment]
script missing - added to the todolist in https://github.com/TrinityCore/TrinityCore/issues/14825
