### ISSUE TITLE
[3.3.5] Quest: Return to the Earth (12417)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15984]
Branch 3.3.5, revision 01beba21b5210860ddd6a37471c6b2bea77a369e
Quest [Return to the Earth](http://www.wowhead.com/quest=12417/return-to-the-earth)
Using [Ruby Acorn](http://www.wowhead.com/quest=12417/return-to-the-earth) works fine and gives credit for the first 5 uses, but does nothing once you are at 5/6 completed. This makes the quest uncompletable.

**Comment by Killyana** [comment]
You're using the item in a npc that already gives you a credit, there's a despawn action issing.

**Comment by joslyn-liu** [comment]
@Killyana that fixes the problem, but I believe the despawn is supposed to be slightly delayed.

The vines are also supposed to be pretty large and shrink over time before the despawn, Over 10 seconds I think? The dragon should also start to shrink half way though.

I also just noticed that creatures around the dragons are attacking the "dead" dragons, pretty sure that's not intended.

**Comment by Killyana** [comment]
We don't have a mod scale SAI_action.

**Comment by Killyana** [comment]
The dragon shrinks when the dbc spell 41935 is triggered periodically by the effect3 of http://www.wowhead.com/spell=49364/return-to-earth
But 41935  doesn't have any effect maybe wrong values on spell_dbc

**Comment by dr-j** [comment]
yes probably know most wotlk spells in spell_dbc are fucked up, some tbc ones too but tbc ones more complete than wotlk ones p:
