### ISSUE TITLE
[DeathKnight] Disease

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#15990]
Deathknight's disease benefit bonus damage of attack power just first time works

How to reproduce:
1. Create DK then .additem 47734 equip the trinket
2. use Icy Touch SpellID: 49909 on dummy
3. Icy Touch hit target for 61 damage while icy touch disease is active on target use the trinket so, the dk get 1K attackpower and now icy touch shod hit more damage because of benefit bonus damage from attackpower, but it doesn't work until!
4. dk use the icy touch again, so while the trinket is active dk's uses icy touch it does the correct damage

Branch 3.3.5
Revision 94e4bdd

**Comment by ccrs** [comment]
I think this is not a bug-
AFAIK HoTs and DoTs deal damage according to oncast statistics, and only get updated on new cast (same or different spell which updates the first one)

**Comment by tkrokli** [comment]
Good point, ccrs. The server and game client might be delayed in making the new bonus take effect.

**Comment by Saben65** [comment]
Anecdotal but I remember having to recast my shadow word pain when I used my trinkets, even though Mind Flay would renew the CD, because the stats weren't added until it was you recast (essentially mind flay just added a duration to the same spell, instead of recasting a new one each time.)

Therefore, it would stand to reason that was Ccrs said is correctly. Damage modifiers are only updated on the next cast, not existing spells.

**Comment by Goatform** [comment]
I can't really remember how it was in WOTLK but I remember that in MoP spell dmg/healing formula should be updated if you get some buff/debuff which increase/decrease dmg/healing without re-casting that spell.

**Comment by velinath** [comment]
Not that forum threads should be taken as accurate, but I did find a couple of them [link](http://www.wowhead.com/forums&topic=189197) [link](http://www.wowhead.com/forums&topic=199873) that may be germane to the topic.

Anecdotally, I remember things similarly to @Saben65 and @ccrs.

**Comment by gigatotem** [comment]
Before Warlords of Draenor, DoT's did damage based on attack power/spell power and procs at the time of cast. 

Dynamic DoT scaling was introduced in 6.0

**Comment by Mollestus** [comment]
"Itâ€™s important to note that as of patch 3.3.2, Glyph of Disease will no longer cause Pestilence to â€˜rollâ€™ the AP value present when you applied diseases. Instead, whenever you case Pestilence to refresh them, diseases will look at your current value of AP (and then use that number until you cast Pestilence again). As such, one doesnâ€™t have to worry about lining up trinket procs at the start of the encounter. This makes GoD non-competitive for a single target, but still a must for a multiple target encounter."

http://forums.elitistjerks.com/topic/71616-unholy-dps-335-king-of-anything/

It´s no bug.

**Comment by ccrs** [comment]
thats not the same thing.

runico talked about using trinkets or any source of stat modification and "automatically" refresh the spell damage output.

Pestilence does cast again the DoTs and therefore they get updated, which is something that is working right now AFAIK

**Comment by Mollestus** [comment]
@ ccrs I know that pestilence is sth different.
But the author said: Instead, whenever you cast Pestilence to refresh them, diseases will look at your current value of AP and then use that number until you cast Pestilence again. 

I.e.: Until the next Pestilence nothing will change the AP value of ur diseases until the get refreshed either with pestielnce and the glyphe or like a new IT.

**Comment by ccrs** [comment]
sooo... we agree. I did not confirm nor defend the proposed issue.

**Comment by Aokromes** [comment]
So... bug or no bug?

**Comment by Rushor** [comment]
1) forget alle the dicussion from @Mollestus and @ccrs 
2) add some sources from wowhead /wowwiki to you issue @Runico

**Comment by Runico** [comment]
@Rushor,i haven't find the document for this one
