### ISSUE TITLE
[3.3.5] DB/Quest: Thassarian quests (Icecrown) do not have prerequisites set

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#15992]
Branch 3.3.5, revision 01beba21b5210860ddd6a37471c6b2bea77a369e

NPC [Thassarian](http://www.wowhead.com/npc=29799) on the Skybreaker in Icecrown offers [pretty much all of his quests](http://i.imgur.com/eqJGgg2.jpg) (a whole page) without requiring any prerequisites.

**Comment by ccrs** [comment]
this must be caused by a recent change. I did some quest there like 1 month ago or so and it was alright.

**Comment by Sakuragi85** [comment]
As of b82ffb8 he still offers all the quests from scratch along with the NPC "
High Captain Justin Bartlett" who is also onboard the ship and also offers like 10 quests at once. So Icecrown questing is pretty horrible right now.

**Comment by Treeston** [comment]
Still applies on latest 931a7623b24831adf679e0581735375077c8d252

This could use love from one of our DB devs. Wowhead has comments with all of the quest trees in Icecrown that we can use as sources.

**Comment by tkrokli** [comment]
Maybe @SnapperRy could take a closer look at those quests offered by Thassarian (http://www.wowhead.com/npc=29799/thassarian) and see what is going on there with all the quests being available all at once? :-) I am fairly sure this has got something to do with which quests are Exclusive to each other, but I don't remember all the chain quest settings.

http://www.wowhead.com/quest=13294/against-the-giants#comments:id=661937 is a useful tree view of the quest lines and chains.

**Comment by Treeston** [comment]
It's just missing appropriate requirement settings in quest_template, I would say.

**Comment by tkrokli** [comment]
Well, some of those settings have been moved to `quest_template_addon`, like `PrevQuestID`, `NextQuestID`, `ExclusiveGroup` and `SpecialFlags` in addition to the Rep fields.

The table `quest_template` seems to only contain info directly affecting each individual quest, not the interaction or relations between the quests.

**Comment by jerbookins** [comment]
The [questline](http://www.wowhead.com/quest=12898/the-shadow-vault#comments:id=846611) at Shadow Vault in Ice Crown also needs a lot of help, from [Baron Sliver](http://www.wowhead.com/npc=29343/baron-sliver).

Can refer to #20009 for database recommendations that I found to be successful in organizing Thessarian and other NPCs quest's aboard the Skybreaker.

**Comment by jerbookins** [comment]
Meaning no offense, as this is pretty much the most prominent Wotlk community in existence, but may I ask why an issue such as this issue is on the back burner? It took a few hours for me to put together the quest lines for alliance and I know very little with regards to how the database works. I would think someone with more experience could much more efficiently and quickly resolve the issues with these quest-lines.

**Comment by pangolp** [comment]
Good day. My name is Walter. I started recently contributing some fix. If anyone knows Spanish, we could get in touch and maybe I could collaborate with the community, I would also like to finish deepening some issues that I could not solve yet. Greetings.

**Comment by tkrokli** [comment]
This is not a forum. Please post on the Forum site https://community.trinitycore.org/.
Please also remove your comment when you have read this and posted on the forum pages.

**Comment by PolarCookie** [comment]
```sql
DELETE FROM `quest_template_addon` WHERE `ID` in (13231,13308,13300,13296,13336,13341,13309,13284,13290,13291,13292, 13233,13286,13287,13294, 13298,13295,13297, 13288,13289,13315,13319,13320,13321,13322,13318,13323,13342,13344,13345,13346,13350,13332,13314,13333,13334,13337,13335,13338,13339);
INSERT INTO `quest_template_addon` (`ID`,`PrevQuestID`,`NextQuestID`,`ExclusiveGroup`,`ProvidedItemCount`,`SpecialFlags`)
VALUES
(13231, 13225, 0, 0, 0, 0),
(13308, 13225, 0, 0, 0, 0),
(13300, 13225, 0, 0, 0, 1),
(13296, 13225, 0, 0, 0, 0),
(13336, 13225, 0, 0, 0, 1),
(13341, 13225, 0, 0, 0, 0),
(13309, 13341, 0, 0, 0, 1),
(13284, 13341, 0, 0, 0, 1),
(13290, 13231, 0, 0, 0, 0),
(13291, 13290, 0, 0, 1, 0),
(13292, 13291, 0, 0, 1, 1),
(13233, 13231, 0, 0, 0, 1),
(13286, 13231, 0, 0, 0, 0),
(13287, 13286, 0, 0, 0, 0),
(13294, 13287, 0, 0, 0, 0),
(13298, 13294, 0, 0, 0, 0),
(13295, 13294, 0, 0, 1, 0),
(13297, 13295, 0, 0, 0, 1),
(13288, 13287, 0, 0, 1, 0),
(13289, 13288, 0, 0, 1, 1),
(13315, 13288, 0, 0, 0, 0),
(13319, 13315, 0, 0, 0, 0),
(13320, 13315, 0, 0, 1, 0),
(13321, 13320, 0, 0, 1, 0),
(13322, 13321, 0, 0, 1, 1),
(13318, 13315, 0, 0, 0, 0),
(13323, 13318, 0, 0, 0, 1),
(13342, 13318, 0, 0, 1, 0),
(13344, 13342, 0, 0, 1, 1),
(13345, 13318, 0, 0, 0, 0),
(13346, 13345, 0, 0, 0, 0),
(13350, 13346, 0, 0, 0, 1),
(13332, 13345, 0, 0, 1, 0),
(13314, 13332, 0, 0, 1, 0),
(13333, 13314, 0, 0, 1, 1),
(13334, 13332, 13335, -13334, 0, 0),
(13337, 13346, 13335, -13334, 1, 0),
(13335, 0, 0, 0, 1, 0),
(13338, 13335, 0, 0, 0, 0),
(13339, 13335, 0, 0, 0, 0);
```

Assuming there's no typos; this should solve all the prereqs on Skybreaker, except the Killohertz questline since that needs work.
I tested it myself and quest reqs works, but it's stuck on #21253 which is still broken.

**Comment by illfated** [comment]
True, it was a bad idea to name the spell script name `spell_q13264_thats_abominable`,
given that the same spell needs to be used in 4 quest IDs. That script needs some rework.

http://www.wowhead.com/quest=13264/thats-abominable (H)
http://www.wowhead.com/quest=13276/thats-abominable (H daily)
http://www.wowhead.com/quest=13288/thats-abominable (A)
http://www.wowhead.com/quest=13289/thats-abominable (A daily)

**Comment by jerbookins** [comment]
@PolarCookie, IIRC the Killohertz quest line was removed with 3.3.5

**Comment by Aokromes** [comment]
@jerbookins nope it was removed on cata or later.
