### ISSUE TITLE
[3.3.5]  Illidan Stormrage PHASE_FLIGHT issues

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#15997]
Branch 3.3.5, revision https://github.com/TrinityCore/TrinityCore/commit/54424aff3051bdc2a05d44cbd56adf6f47b98229
DB: TDB 335.60

when Illidan enter flight phase, he will be 
1. fly 
2. falldown
3. walk to destination
4. fly
5. castspell
6. down

**Comment by Aokromes** [comment]
... what's the supposed issue?

**Comment by frozen4** [comment]
he will fly alway in flight phase  not  fly <-> down

**Comment by frozen4** [comment]
![Uploading 1.jpg…]()
![Uploading 2.png…]()

**Comment by Kittnz** [comment]
I don't get it

**Comment by lyrl** [comment]
are your akama visible ?

**Comment by Kittnz** [comment]
Ah you mean illidan flys up and then drops down and casts his spells, and when the phase is over illidan flys up again and flys down to the return position. sounds like a inhabittype problem

**Comment by Keader** [comment]
Missing hover scripts maybe?!
He "walk" in the air, instead of fly (in air phase).
Whenever he go cast a spell happens a visual bug where it appears on the ground (as if he had fallen from the flight).
Some triggers of spell are without auras and attacking players also [3.3.5]

**Comment by frozen4** [comment]
https://github.com/TrinityCore/TrinityCore/issues/7606

**Comment by Kittnz** [comment]
#7606
