### ISSUE TITLE
[3.3.5] Core/Position: Graveyard spawn misplaced: Jotunheim (Icecrown)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16003]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

The Graveyard spawn for alliance (maybe horde too) when you die in Jotunheim/the Fleshworks gets you stuck inside a skeleton on the ground.

**Comment by Killyana** [comment]
Coords for graveyards are on WorldSafeLocs.dbc we cannot change that.

**Comment by Treeston** [comment]
Maybe the GO you get stuck on is misplaced then? Not sure.

**Comment by jackpoz** [comment]
what's the blizz behavior ?

**Comment by Treeston** [comment]
No idea what the behavior was during 3.3. Maybe someone could check current live?

**Comment by msoky** [comment]
similar issues, dont forget
https://github.com/TrinityCore/TrinityCore/issues/15441
https://github.com/TrinityCore/TrinityCore/issues/14160
https://github.com/TrinityCore/TrinityCore/issues/14089

**Comment by Aokromes** [comment]
Not related at all to those 3 tickets.

**Comment by Killyana** [comment]
There's no GO at this position, it's just the map.

**Comment by Rushor** [comment]
on current retail you don't have any problems to revive. if you died, you will instantly get your flying ghost mount without stucking in the map.

**Comment by Aokromes** [comment]
I wonder if #17529 can fix this.

**Comment by offl** [comment]
#17529 merged. Should be tested.

**Comment by Killyana** [comment]
The commit wasn't cherry picked to 3.3.5

**Comment by Killyana** [comment]
Cannot reproduce on rev. 86bba6421baf
