### ISSUE TITLE
[3.3.5] Abandoning quest does not destroy quest items

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16008]
Branch 3.3.5, revision 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

Abandoning a quest should remove all related quest items from your bags (the client popup to confirm abandoning a quest states as much). However, this does not happen.

**Comment by dr-j** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/15860
