### ISSUE TITLE
[3.3.5a][Mage] Core/Spell: Hot Streak don't work with Living Bomb final (explosion) crit

### ISSUE THREAD

**Issue by Effec7** [TrinityCore/TrinityCore#16007]
As title says, Mage's [Hot Streak](http://wotlk.openwow.com/spell=44445) talent does not proc from [Living Bomb](http://wotlk.openwow.com/spell=55362) Final Tick (explosion)

**What steps will reproduce the problem**?
1.Take a Mage **Lvl 80** with **Hot Streak** and **Living bomb**.
2.Get a target which have a lot of HP (Like Dummy).
3.Hit him with **Living Bomb** and wait for **final** tick (explosion)

**How it should work**
*Any time you score 2* **non-periodic spell** *criticals in a row using Fireball, Fire Blast, Scorch,  __Living Bomb__ , or Frostfire Bolt, you have a 100% chance the next Pyroblast spell cast within 10 sec will be instant cast.*

**Core Revision:** https://github.com/TrinityCore/TrinityCore/commit/d393af75

__Thank You__ for your Help.

**Comment by ariel-** [comment]
Works correctly on rev. 805637cea15470dac4b9417494e4d89f1c1d3239
