### ISSUE TITLE
[3.3.5][VioletHold] Core/Creature: combat stuck in instance

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16013]
core:https://github.com/TrinityCore/TrinityCore/commit/b013eb1925276cde36dbcd765ee89aeecdcd21de
DB:TDB60
update:2015_12_16_00_world.sql
VioletHold

After the battle failed the plot is still carried out

http://s018.radikal.ru/i502/1512/a8/2d8276b42bf8.jpg

**Comment by danqu** [comment]
I also found the same problem, the problem is very serious!

**Comment by Aokromes** [comment]
#6756
