### ISSUE TITLE
Escort Quests Issues

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16025]
I found issues with two escort quests, I'm thinking that any quest involving escorting or involving any otherwise neutral character will glitch resulting in a noncompletion of the quest and force us to abandon the quest altogether. This may pose a problem as some quests are part of a quest chain. 

First one is: 
A Daughter's Embrace - http://www.wowhead.com/quest=25046/a-daughters-embrace
While the escort part works fine, the quest objective cant be reached because Lillian doesnt engage her father.

Second One is:
Crossroads Caravan Pickup - http://www.wowhead.com/quest=13949/crossroads-caravan-pickup
One can receive Helga's Streetsweeper but they cannot mount the Kodo, or the quest Kodo does not spawn.

TrinityCore rev=4695e234912e 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)
TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Rushor** [comment]
there are individual problems - it's not a general issue - pls open up one ticket for each issue
