### ISSUE TITLE
[3.3.5a] Professor putricide ( choking Gas Bomb )

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16024]
Choking Gas - The Choking Gas inflicts 5363 to 5637 damage and causes you to choke, reducing your chance to hit by 75% for 15 sec

the hit reduction doesnt work

https://github.com/TrinityCore/TrinityCore/commit/cc685ac334335d9f6a25a7c1c739a905f919328f

**Comment by Keader** [comment]
yes... work.
With spells, it is more difficult to notice because some spells end up hitting the target ... but with a greatly reduced damage. With Melees in general is very remarkable the number of "miss" which is given during the debuff.

**Comment by Rushor** [comment]
then reduction only counts for either melee or rangecasts - not both

**Comment by Killyana** [comment]
So the issue is valid?

**Comment by declart** [comment]
http://www.wowhead.com/spell=71279/choking-gas-explosion 

Apply Aura: Mod Melee & Ranged Hit Chance %
Value: -75%
Value: -100% - 10 Player Heroic (Legacy)
Value: -100% - 25 Player Heroic (Legacy)
Radius: 10 yards

i tryied on 10 player hc( 100% reduction ), and i've done only 2 miss, with melee attacks.
In a blizzlike server you can't hit the target with all spells that stacked with "hit chance"

**Comment by Rushor** [comment]
pls check the effectvalue for spell 71279 in dbcs

**Comment by Rushor** [comment]
@declart wrote:
i tryied on 10 player hc( 100% reduction ), and i've done only 2 miss, with melee attacks.
In a blizzlike server you can't hit the target with all spells that stacked with "hit chance" 

only meleehits or special meleeabilities?

**Comment by Rushor** [comment]
no answer after 7 days, furthermore it works fine for me, meleeattacks are missing
