### ISSUE TITLE
Find Baron Longshore Issue

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16026]
http://www.wowhead.com/quest=14045/find-baron-longshore

Baron Longshore attacks instead of talking to you to fulfill the quest objective.

Another of the few Ratchet area quest I'm finding to be glitchy. Apologies if this is a known issue that has not been carried over from the 3.x. Just making sure all the loose ends are tied up.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by tkrokli** [comment]
http://www.wowhead.com/npc=3467/baron-longshore#comments
Baron Longshore was hostile from 1.11.1 up to 3.3.5a, changed to friendly in patch 4.0.3.
Could be a faction issue, if the faction info from 3.3.5 got transferred to 6.x, or maybe a unit flag issue.

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `Faction`=2028 WHERE `entry` IN (3467);
