### ISSUE TITLE
[3.3.5a] Quest: A Delicate Touch

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16031]
b967047

[Garm Invaders](www.wowhead.com/npc=29619) / [Snowblind Followers](http://www.wowhead.com/npc=29618) don't run through the minefield. [Improved Land Mines](http://www.wowhead.com/item=40676) that you place do not go off when mobs are kited over them.

[Quest video](https://www.youtube.com/watch?v=1aCPJU9KysM)

[Quest](http://www.wowhead.com/quest=12820)

**Comment by Rushor** [comment]
a areatriggerscript and paths for many creatures are missing here

**Comment by Kittnz** [comment]
Ah yes, paths i can provide but it needs SAI scripting

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/10205

**Comment by velinath** [comment]
oops sorry, I do try and check for duplicates but didn't try that keyword
