### ISSUE TITLE
[3.3.5][6.x] DB/Quest: The Great Hunter's Challenge

### ISSUE THREAD

**Issue by aletson** [TrinityCore/TrinityCore#16037]
b967047

[Quest](http://www.wowhead.com/quest=12592)

[Drostan](http://www.wowhead.com/npc=28328) doesn't come out and talk to you while you're killing stuff.

[This video](https://www.youtube.com/watch?v=cAKV8NhfP7E) could be useful to see at which points he comes out and taunts you.

In #11003 this is mentioned, but the issue was closed before that part of the bug could be fixed. So, new issue! Please let me know if it's better practice to reopen the old issue.

**Comment by tkrokli** [comment]
Suggestion: when you post links to the creature/quest/item/spell page on wowhead, show the link itself:

http://www.wowhead.com/quest=12592/the-great-hunters-challenge

it displays both name from the page and the ID in 1 single line, more visually useful than "Link" etc.

**Comment by velinath** [comment]
Sounds good; I'll start doing that in the future.

**Comment by Rushor** [comment]
maybe there is sth like a aura for the player which handles the summon/despawn of Drostan

**Comment by Killyana** [comment]
Spell: http://wotlk.openwow.com/spell=52556
Npc: www.wowhead.com/npc=28857/drostan

**Comment by Rushor** [comment]
hm but how should http://wotlk.openwow.com/spell=52559 behave?

if the player is 5 seconds in combat, the triggered effect http://wotlk.openwow.com/spell=52556 should be executed and drostan should spawn?

or maybe another solution:

every questmob has an sai - it the questmob in 5 seconds in combat and player has quest: "The Great Hunter's Challenge" active, drostan will spawn

**Comment by Rushor** [comment]
all involved creatures:

http://www.wowhead.com/npc=28009/shardhorn-rhino
http://www.wowhead.com/npc=28001/dreadsaber
http://www.wowhead.com/npc=28011/emperor-cobra
http://www.wowhead.com/npc=28002/mangal-crocolisk
http://www.wowhead.com/npc=28380/shattertusk-bull
http://www.wowhead.com/npc=28297/shango
http://www.wowhead.com/npc=28379/shattertusk-mammoth
http://www.wowhead.com/npc=28378/primordial-drake

i will try to add a script later

**Comment by tkrokli** [comment]
Maybe worth considering: Drostan doesn't appear 60 times (once for each animal). Quote:
[[Celestrious on 2009/07/16 (Patch 3.1.3)]](http://www.wowhead.com/quest=12592/the-great-hunters-challenge#comments:id=450881:reply=109962)
"He decided to taunt my druid at kills: 8, 11, 21, 28 (He decided to take a nap), 35 (He decided to go fishing), 41, and 56, when he decided he had 54 kills. I don't know if these are the same for everyone, and I don't know if everyone else wins by just 2 mobs, either, but I know I won, taking my sweet time doing this quest."
