### ISSUE TITLE
[3.3.5a] Quest: The Air Stands Still

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16032]
b967047

The summoned NPC's for this quest don't actually do anything unless they're hit directly; otherwise, they'll just hang out and watch until either you kill the mob or it kills you.

[Quest on Wowhead](http://www.wowhead.com/quest=13125)
[War Horn of Acherus](http://www.wowhead.com/item=43206), the item that you use to summon the death knights.
[Jayde](http://www.wowhead.com/npc=30839), [Munch](http://www.wowhead.com/?npc=30840), and [Highlord Darion Mograine](http://www.wowhead.com/npc=30838) are the three death knights in question here.
[Quest video](https://www.youtube.com/watch?v=wvm6Pxex37A)

**Comment by Killyana** [comment]
Add on just summoned attack closest npc.
