### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Avenge Me!

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16033]
b967047

[Quest](http://www.wowhead.com/quest=13230)
[Dying Soldiers](http://www.wowhead.com/npc=31304) do not reward quest credit for the objective on this quest.

**Comment by tkrokli** [comment]
http://www.wowhead.com/quest=13230/avenge-me (horde)
http://www.wowhead.com/quest=13232/finish-me (alliance)
Both quests target alliance dying soldiers. Did you check if your PvP flag was on or off?

http://www.wowhead.com/quest=13230/avenge-me#comments:id=648536 (By Nightlola):
For Hunters doing this quest!
Do not shoot it.. u have to go up and stab them and don't let ur pet do the work.. or it wont count! :)

**Comment by velinath** [comment]
Wasn't doing it on a pet class, so I don't think that's the problem.

I believe the PVP flag was off, but that shouldn't matter. For the Horde quest, the Dying Soldiers still show up as hostile even with a flag off. Killing them doesn't seem to reward credit towards the quest objective.

**Comment by Killyana** [comment]
@Treeston Can you have a look to this issue ?
Looks your commit makes impossible to get the kill credit if the npc has less than 50% hp (Initial)
Example: 31304 with 29% initial HP (injured or dying)
https://github.com/TrinityCore/TrinityCore/pull/15473

**Comment by Killyana** [comment]
Adding the extra_flags must fix the issue: (not tested)
``` sql
UPDATE `creature_template` SET `flags_extra`=(`flags_extra`|2097152) WHERE `entry` IN (31304);
