### ISSUE TITLE
[3.3.5] Franclorn Forgewright

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16041]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

http://www.wowhead.com/npc=8888/franclorn-forgewright

Should only be visible while a ghost, is currently visible only while not a ghost.

**Comment by Rushor** [comment]
try this:
```sql
UPDATE `creature_template` SET `npcflag`=32771 WHERE `entry`=8888;
```

**Comment by Treeston** [comment]
Seems to work.

**Comment by Killyana** [comment]
It must be done by script, the `npcflag`=32771 doesn't exist on sniffs, and it will add the gossip option for resurrection.
Also there's a missing aura:
``` sql
UPDATE `creature_template_addon` SET `auras`=10848 WHERE `entry` IN (8888);

**Comment by boom8866** [comment]
Solve!

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/1c877ecbd2a4c81204f932a4f249b8f9dd6f5b90
