### ISSUE TITLE
[6.x] DB/Quest: The Kessel Run

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#16047]
5c74ce2e2760

Quest: http://www.wowhead.com/quest=9663/the-kessel-run

As someone demonstrated in the following video, you're supposed to get a 15 minute timer for completion of the quest and also demount, if the timer expires:
https://www.youtube.com/watch?v=ythicNpMbhw

Timer is currently not present after accepting the quest

**Comment by GnaXi** [comment]
On another note, you're not automatically dismounted, when you deliver the quest either.

**Comment by Killyana** [comment]
No need to open issues for cata+ quest if the area is not scripted:
https://github.com/TrinityCore/TrinityCore/issues/15182

**Comment by Aokromes** [comment]
I wonder if this issue is also valid on 3.3.5a

**Comment by tkrokli** [comment]
TrinityCore rev. e881afcd1c41 2016-06-18 10:44:48 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 plus updates up to and including `2016_06_18_00_world.sql`

The quest and the quest timer works as expected/intended on 3.3.5, even if I exit from the vehicle to complete a different quest before delivering this quest. (All game addons disabled during this test.)

![wowscrnshot_061816_182036](https://cloud.githubusercontent.com/assets/4903600/16172137/cb748b9a-3581-11e6-9232-31115e4c64cf.jpg)

Not sure if it is possible to bug the timer deliberately, all I could see is that the timer showed and worked on 3.3.5. Have to re-test it on current 6.x to see if it is still bugged in the TC 6.x branch.

**Comment by Aokromes** [comment]
works for me on f6637439f484dacc9c8deb3c4dd07832146ff6f6

**Comment by tkrokli** [comment]
TrinityCore rev. f6637439f484 2016-06-18 16:23:55 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_17_01_world.sql`

The quest timer works from the moment you pick up the quest, so closing this issue is correct.

The timer becomes hidden after completing the last quest objective, but I guess that could be intended behaviour, or at least how it works on retail. Several comments on the wowhead quest page point out that you need to deliver the quest before the timer expires, so it might be how it is supposed to work.

**Comment by GnaXi** [comment]
Timer is shown, yes. But you're still not demounted if the quest is failed or when it's completed.

**Comment by tkrokli** [comment]
TrinityCore rev. 7ec0d9411973 2016-06-19 23.49.16 +0200 (6.x branch) (Win64, Release, Static)

1. Failed the quest by stopping near the Exodar doing nothing. Got dismounted when time was up.
2. Failed the quest by completing all 3 objectives, but stopping short of delivery. Also dismounted.
![wowscrnshot_062016_050313](https://cloud.githubusercontent.com/assets/4903600/16182640/b43e3516-36a8-11e6-91aa-84756649931e.jpg)

***

3 - Completed quest and delivered it back to Kessel. Sat on the elekk for 8 minutes. Got dismounted.

![wowscrnshot_062016_052232](https://cloud.githubusercontent.com/assets/4903600/16182675/f8ccbd1a-36a8-11e6-99c0-12443bfb0f8d.jpg)

Try deleting your game Cache each time before you start the game client. Recompile and try again. Maybe log out and back in a few times before taking this quest. Maybe even drop your World database and let Worldserver rebuild it.

**Comment by GnaXi** [comment]
> 3 - Completed quest and delivered it back to Kessel. Sat on the elekk for 8 minutes. Got dismounted.

That is not the correct behavior though. 
You're supposed to be dismounted, when you complete the quest at Kessel.

**Comment by tkrokli** [comment]
Oh. Of course. I see it now. It is in the description of the quest. Maybe you could try your hand at creating a SAI for this event? You need the following to happen :

**Kessel - On quest 9663 (The Kessel Run) Completed - Cast spell "Cancel Kessel's Elekk (99341)"**

**Comment by GnaXi** [comment]
Is there a specific reason for the following not being used?
Dismount Kessel's Elekk (31978)

**Comment by tkrokli** [comment]
The most likely reason is that the spell ID is missing from the quest table used for quest reward.
