### ISSUE TITLE
[6.x] DB/Quest: Rune Covered Tablet

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#16045]
5c74ce2e2760

Quest: http://www.wowhead.com/quest=9514/rune-covered-tablet

You're supposed to just deliver this item to Priestess Kyleen Il'dinare at Odesyus' Landing, but are given the following instructions instead:
![untitled](https://cloud.githubusercontent.com/assets/1616448/11876825/dc79e736-a4eb-11e5-8f91-0489a951e1ee.png)

**Comment by GnaXi** [comment]
Quest can be delivered to Priestess Kyleen Il'dinare though

**Comment by Aokromes** [comment]
I wonder if this bug is valid also on 3.3.5a

**Comment by tkrokli** [comment]
It looks like a DB/quest update sync issue, since it is still showing the quest area after completion.
Have to test and see for myself, but I think it may be OK on 3.3.5. Not sure about current 6.x status.

**Comment by GnaXi** [comment]
Looks like a similar issue to: https://github.com/TrinityCore/TrinityCore/issues/16046

Accepting the quest:
![rune-covered-tablet1](https://cloud.githubusercontent.com/assets/1616448/16208972/167828b8-3735-11e6-9188-03dc720966cd.png)

Relogging:
![rune-covered-tablet2](https://cloud.githubusercontent.com/assets/1616448/16208980/1f3650c4-3735-11e6-83c7-0be0d559cb45.png)

rev. 5f2c62392cad 2016-06-20 21:53:53 +0200 (6.x branch) (Unix, Release, Dynamic)

**Comment by Aokromes** [comment]
Maybe related to #14216
