### ISSUE TITLE
[6.x] DB/Quest: Coming of Age

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#16046]
5c74ce2e2760

Quest: http://www.wowhead.com/quest=9623/coming-of-age

Quest is to be delivered to a draenei just outside of The Exodar, but it isn't shown on the map:
![untitled](https://cloud.githubusercontent.com/assets/1616448/11877935/b2778fc2-a4f2-11e5-9b15-8b575a6d698e.png)

**Comment by Aokromes** [comment]
I wonder if this bug is also valid on 3.3.5a

**Comment by tkrokli** [comment]
Should be easy to check. Steps to find out what it looks like in current source/game:
1. create a new Draenei character and use the command `.char level 10`
2. `.go creature id 17116` (Exarch Menelaous) and accept the quest "Coming of Age"
3. Check the map for quest markers (number circle, quest end icon ( ' ? ' ) etc.)

BTW, it is just as easy to do `.char level 10` +  `.quest add 9623` as well. Probably useful to be in the right area to see it on the map, though, like `go creature id 17584` (Torallius the Pack Handler).
Going to test it now, both on 3.3.5 and 6.x - reporting back with how it looks.

**Comment by tkrokli** [comment]
TrinityCore rev. 7ec0d9411973 2016-06-19 23:49:16 +0200 (6.x branch) (Win64, Release, Static)
Hang on a second... I just logged in to the same character again and _now I can see the map info_:

![coming_of_age_6_x_2_x](https://cloud.githubusercontent.com/assets/4903600/16181303/be6ed266-3699-11e6-9876-01eceb69b705.png)
This issue could be either an intermittent one or maybe a symptom of slow packet synchronization.

**Comment by GnaXi** [comment]
I can confirm that the issue is resolved by relogging.
rev. 5f2c62392cad 2016-06-20 21:53:53 +0200 (6.x branch) (Unix, Release, Dynamic)

**Comment by Aokromes** [comment]
Maybe related to #14216

**Comment by offl** [comment]
#20879
