### ISSUE TITLE
[3.3.5] Mana Feeders need spell immunity added.

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16050]
Core Rev: 80ed03a84d2a
DB: TDB 335.59

[Mana Feeder](http://www.wowhead.com/npc=16491/mana-feeder) should be immune to all spells and wand damage.

> Didn't realize these were immune to everything but melee damage so I sorta got owned on my mage. Swings with my staff are relatively slow and don't do a ton of damage. Pulled the whole area only to see "immune immune immune" everywhere. Oops.

http://www.wowhead.com/npc=16491/mana-feeder#comments:id=1703484

I have tried using certain spells that offer magic immunity such as [Damage Immunity: Magic](http://www.wowhead.com/spell=39804/damage-immunity-magic) as a hackfix but you can still do damage with wands. Therefore I do not know if wands are incorrectly being counted as physical damage, or if they just don't apply to the spells.

**Comment by offl** [comment]
Try this:
```
UPDATE `creature_template` SET `resistance1`=-1,`resistance2`=-1,`resistance3`=-1,`resistance4`=-1,`resistance5`=-1,`resistance6`=-1 WHERE `entry`=16491;
```

**Comment by Saben65** [comment]
Spells still seem to do full damage.

**Comment by Killyana** [comment]
``` sql
DELETE FROM `creature_template_addon` WHERE `entry` = 16491;
INSERT INTO `creature_template_addon` (`entry`,`auras`) VALUES (16491, '39804');

**Comment by Killyana** [comment]
Wands http://wotlk.openwow.com/spell=5009  School = Physical
