### ISSUE TITLE
3.3.5 NPC Agent Kearnen

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16057]
I use TrinityCore rev. e1bcd10c9bc2 2015-12-17 02:06:21 +0100 (HEAD branch)
Agent Kearnen the Z Position is to high

http://www.wowhead.com/npc=7024/agent-kearnen

![wowscrnshot_121815_145732](https://cloud.githubusercontent.com/assets/10637389/11898490/62e812be-a598-11e5-81d1-171b2d5a99ca.jpg)

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_addon` SET `bytes1`=8 WHERE `guid`=4216;

**Comment by Tauriella** [comment]
Perfect :+1: 
Thx
