### ISSUE TITLE
[3.3.5a][6.x] Professor Putricide and his Oozes

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16059]
http://www.wowhead.com/npc=37690/growing-ooze-puddle
http://www.wowhead.com/npc=37697/volatile-ooze

theese npc in a blizzlike server are not stunnable, fearable etc etc,
but now they can get all type of crowd control.
The only one that they can get is ([Regurgitated Ooze]50 yd range—The Regurgitated Ooze has a surprising effect on the target, slowing its movement speed by 50% and dealing 6,338 to 6,662 damage every 2 seconds for 20 seconds. Instanting-ooze-puddle) from Mutated Abomination.

https://github.com/TrinityCore/TrinityCore/commit/cc685ac334335d9f6a25a7c1c739a905f919328f

**Comment by Gargarensis** [comment]
```sql
UPDATE creature_template SET mechanic_immune_mask = 650854271 WHERE 
   entry = 37697 	-- 10N Volatile Ooze
OR entry = 38604 	-- 10H Volatile Ooze
OR entry = 38758 	-- 25N Volatize Ooze
OR entry = 38759	-- 25H Volatile Ooze
OR entry = 37562	-- 10N Gas Cloud
OR entry = 38602	-- 10H Gas Cloud
OR entry = 38760	-- 25N Gas Cloud
OR entry = 38761;	-- 25H Gas Cloud
```
It seems that Regurgitated Ooze works fine even if we use this mask.

**Comment by Rushor** [comment]
@Gargarensis: can you update the fix if you only add new flags to it?

f.ex:
```sql
UPDATE creature_template SET mechanic_immune_mask=mechanic_immune_mask|0x000004|0x000008 WHERE 
   entry = ...
```

**Comment by Gargarensis** [comment]
Yes, of course:
```sql
UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|1|2|4|8|16|32|64|256|512|1024|2048|4096|8192|65536|131072|524288|4194304|8388608|33554432|67108864|536870912 WHERE `entry` IN (
37697,    -- 10N Volatile Ooze
38604,    -- 10H Volatile Ooze
38758,    -- 25N Volatize Ooze
38759,    -- 25H Volatile Ooze
37562,    -- 10N Gas Cloud
38602,    -- 10H Gas Cloud
38760,    -- 25N Gas Cloud
38761);   -- 25H Gas Cloud
```
But the initial mask is 0, so it is almost the same thing to add each flag or set directly the value.

**Comment by Rushor** [comment]
yeah anyway, this looks much better - ty
