### ISSUE TITLE
Orc Start - Corruption

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16053]
Rolled a New Orc Warlock. Quest titled Corruption doesn't work.
Casting Corruption Spell on Training dummy doesn't credit toward quest objective.
http://www.wowhead.com/quest=25145/corruption

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Killyana** [comment]
dup: https://github.com/TrinityCore/TrinityCore/issues/15921
