### ISSUE TITLE
[6.x] Core/Loot: Auto loot Autoloot Radius - Loot System

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16065]
Sorry if this has already been reported. In retail, I used to be able to kill mobs and when all was done I would loot the trash mobs and Auto loot would hit all the loot within a specific radius. Now I have to hit every single corpse if I want to loot trash mobs. Is this a known issue/duplicate?

Thanks in advance.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by msoky** [comment]
no, but fix was there... https://github.com/TrinityCore/TrinityCore/pull/13817

**Comment by BahDumbBugs** [comment]
@msoky Thanks!

**Comment by BahDumbBugs** [comment]
Has this fix been thrown into any commit yet or any work done on it? As of 6bfcdea, there's still no AoE looting.

**Comment by Shauren** [comment]
Nope, still not implemented
