### ISSUE TITLE
[3.3.5] DB/Creature: LoS issues with mobs in outlands instances

### ISSUE THREAD

**Issue by Kensaki** [TrinityCore/TrinityCore#16069]
I'm having a lot of issues with casters/ranged mobs standing still if you move out of line of sight they wont run to you and attack.

Ethereal Sorcerer (ID: 18313)
Bleeding Hollow Darkcaster (ID: 17269)
Bleeding Hollow Archer (ID: 17270)

Picture for reference: http://oi68.tinypic.com/1z1xoac.jpg
of the Sorcerer: http://oi63.tinypic.com/4se645.jpg

rev e6903fdffa73 2015-12-15

**Comment by Saben65** [comment]
Pretty sure this has to do with this issue (https://github.com/TrinityCore/TrinityCore/issues/12476), and affects multiple mobs throughout azeroth, OL, and northrend.

Not sure if the suggested fix works.

**Comment by Kensaki** [comment]
It might, although I am experiencing the issues in combat, not out of combat. Might be the same issue

**Comment by velinath** [comment]
I am pretty sure it's more than just those instances, fwiw. There are also some mobs in Nexus that have the same problem.

**Comment by Killyana** [comment]
This issue is not valid, provide a list of npcs that must be fixed, otherwise it will be closed.

**Comment by Kensaki** [comment]
I updated it for clarity. Sorry.

**Comment by Killyana** [comment]
I will fix the reported Npcs only don't have time to check instances.

**Comment by Saben65** [comment]
**Outlands**

Steamvaults
* Coilfang Siren - 17801
* Coilfang Sorceress - 17722
* Coilfang Leper - 21338 (the ones that use ranged weapons)

The Underbog
* Murkblood Spearman - 17729
* Murkblood Oracle - 55391

The Slave Pens
Appears to all be working

The Blood Furnance
* Shadowmoon Warlock - 17371: Seems to only affect the 4 warlocks in the room after Broggok (GUID: 138235 - Appears to be because it is supposed to patrol. Doesn't patrol until it is reset for the first time. Once it starts patrolling, if you pull it from ranged, stay out of melee range, and LOS it will follow its WPs to try to get into LOS with you while walking and casting at the same time. Same issue with GUID 138234) 

Will update later for other dungeons.

**Comment by Saben65** [comment]
So I was trying to add pathing to a Coilfang Siren (17801) and found she was behaving like the Shadowmoon Warlocks in blood Furnance, so I checked out her SAI. Her first entry is as follows.

```SQL
(@ENTRY,0,0,0,1,0,100,7,0,0,0,0,21,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Coilfang Siren - Out of Combat - Disable Combat Movement (No Repeat) (Dungeon)"),
```

Changing that to enable allowed her to move along her waypoint as well as try to move into LOS. I think it broke the rest of her SAI though, as she wouldn't cast lightning bolt after the initial cast.

**Comment by tkrokli** [comment]
@Saben65 : have you tested removing `(No Repeat)`  from those Lightning Bolt lines, id 1, 3, 4 and 6 ?

I also noticed that "(No Repeat)" is commented on all the 16 SAI lines for `entryorguid` = 17801, but 2 of those 16 lines do not have any `event_flags` set, making "(No Repeat)" bogus info on line id 2 and id 8.

**Comment by Saben65** [comment]
I will try that. ID 3 and 6 do not have `no repeat`. Changing ID 1 and 4 didn't have them casting lighting bolt after trying enable as well as disable combat movement (id: 0)

I don't know if it has something to do with their SAI or the program, but SAI-Editor keeps giving me the error "Something went wrong while attempting to edit the fields based on the new selection." when I try to select ids 3, 4, 6, 12.

**Comment by tkrokli** [comment]
You may want to test if it is any easier to edit the SAI in Keira2: http://shinworld.altervista.org/Keira2/#/

**Comment by Rushor** [comment]
see also https://github.com/TrinityCore/TrinityCore/issues/18659

**Comment by Rushor** [comment]
some of them were updated with #18659, still around 100 creatures need to be converted.

**Comment by Aokromes** [comment]
Useless ticket on current form, reported mobs already fixed, open a new ticket with ids of afected npcs.
