### ISSUE TITLE
moving earthgrab totem

### ISSUE THREAD

**Issue by Rhagan** [TrinityCore/TrinityCore#16062]
TrinityCore rev. e1bcd10c9bc2 2015-12-17 02:06:21 +0100 (3.3.5 branch) (Unix, Release) 
TDB 335.60

branch 3.3.5
hash e1bcd10c9bc2

For some NPCs the Earthgrab totem behaves more like
a pet than a totem.
If the NPC Shaman moves after casting earthgrab totem the totem follows arround.
I think i recognized it in Stranglethorn, bloodscalp shamans.
http://www.wowhead.com/npc=697/bloodscalp-shaman

**Comment by Aokromes** [comment]
#15651

**Comment by tkrokli** [comment]
@Rhagan : please post your info in issue #15651 instead. Your info is useful there.
