### ISSUE TITLE
[CRASH]  EvaluateTable ASSERTION FAILED

### ISSUE THREAD

**Issue by vinin80** [TrinityCore/TrinityCore#16072]
http://pastebin.com/DLYZHimC

branch 6.x
rev. 6969bfc

**Comment by Vincent-Michael** [comment]
you set lvl over 100?

**Comment by vinin80** [comment]
no, this crash every 2-5min with 100 online

**Comment by Shauren** [comment]
NPC level over 123?

**Comment by vinin80** [comment]
nope, spell id 17137 crashing server, if this spell is disable crashing not happen

**Comment by tkrokli** [comment]
http://www.wowhead.com/spell=17137/flash-heal (Class: Priest)

**Comment by vinin80** [comment]
meh. i think this spell don't have anything with this crash because still have crash, it's have very high priority because this crashing every 1-3 min now
