### ISSUE TITLE
[master] Core/Reagent Bank - Not Yet Implemented

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16077]
Tried to purchase Reagent bank tab in Orgrimmar bank. Nothing happened and I had plenty of gold.

Will try in other cities with Alliance faction as well. Just bringing it to light.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Shauren** [comment]
I prefer the term "not implemented"

**Comment by BahDumbBugs** [comment]
Not Implemented. Borked.

**Comment by tkrokli** [comment]
There is a meaningful difference between the two, because "broken" means it worked before at some point.
If it has not been implemented yet, it can not be broken, simply because it is *not part of the code yet*.

**Comment by BahDumbBugs** [comment]
Ahhh. Ignorant moment. Sorry for the snarkiness and thanks for the clarification @tkrokli !

**Comment by tkrokli** [comment]
Fair enough. See if you can rewrite the title to something that describes the problem correctly.

**Comment by BahDumbBugs** [comment]
:+1:

**Comment by Exodius** [comment]
Found this. Dunno if helps.
Maybe someone can test/addapt?
https://github.com/Kittnz/FirestormWoD/commit/0fa6d74c18bec856665558211fbb6ed62245d2b1
https://github.com/Kittnz/FirestormWoD/commit/33094b2516efd1454ce6b0de452f4681525c127b
https://github.com/Kittnz/FirestormWoD/commit/a2474b16f740fc58c1437fcce5c2f7e4157adf93

**Comment by funjoker** [comment]
Gonna take a look into it.

**Comment by Exodius** [comment]
@Kittnz repo got taken down
Found this: https://github.com/AshamaneProject/AshamaneCore/commit/4959d87bd683a65a9613e091517753d3c0fc233d

**Comment by BahDumbBugs** [comment]
Thanks for the progress. I'm back by the way! :)
