### ISSUE TITLE
[6.x] DB/Misc: Table disables not working

### ISSUE THREAD

**Issue by ter884** [TrinityCore/TrinityCore#16074]
table "disables" does not work disable achievements, I wanted to disable the criterion for achievement (http://ru.wowhead.com/achievement=3636) criterion 11238 (sourceType=4,entry=11238,flags=0,params_0="",params_1="",comment=Achievement: Jade tiger), but in the game the character gets this criterion.

6.x
commit: ef91ba951744d9e095cd03ba4f80f5aa49bcdb32

**Comment by joschiwald** [comment]
because criteria ids in 6.x does not match with 3.3.5 ones

**Comment by ter884** [comment]
I looked through the (Viewer, DBC) the number of criteria they match

**Comment by Vincent-Michael** [comment]
![Image] (http://i.imgur.com/XbfCEnj.png)

**Comment by ter884** [comment]
![default](https://cloud.githubusercontent.com/assets/6825541/11919029/339abaae-a758-11e5-9ed2-37f8bbacbea4.PNG)

**Comment by ter884** [comment]
even if I specify 7239, 7240 not all will change also

**Comment by Lordron** [comment]
DisableMgr works with criteriaId (m_criteria field at your picture), rather than CriteriaTreeId (m_id)

**Comment by ter884** [comment]
I enter 11238 does not work

**Comment by Aokromes** [comment]
Try after d0d76ab

**Comment by Aokromes** [comment]
No answer after months, closing.
