### ISSUE TITLE
[3.3.5a] Quest: Leave Our Mark

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16081]
b967047

http://www.wowhead.com/quest=12995/leave-our-mark

http://www.wowhead.com/spell=23301/ebon-blade-banner can currently be used multiple times on the same target. It should tap the target on use.

**Comment by tkrokli** [comment]
http://wotlk.openwow.com/item=42480/ebon-blade-banner
[Use: Target and impale the corpse of any of the vrykul in the greater Jotunheim region. Range is r yards.](http://wotlk.openwow.com/spell=23301)

Linked to:
http://wotlk.openwow.com/spell=23301/ebon-blade-banner
Effect #1: Summon Object (Wild) Object: [Ebon Blade Banner (192180)](http://wotlk.openwow.com/object=192180)
Effect #2: Script Effect

Used by:
http://wotlk.openwow.com/object=192180/ebon-blade-banner (summoned by spell 23301)

Can't seem to find anything named "ebon blade banner" in the source code by doing a regular search in this repo. Searching local source code instead. (I will be back later.)

**Comment by tkrokli** [comment]
There does not seem to be any condition for the property "tapped", so I tried to make some kind of condition for spell 23301, based on the summoned gameobject 192180, but it does not work. :\
```sql
-- Condition for Ebon Blade Banner
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry`=23301;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,23301,0,0,30,1,192180,15,0,0,0,0,'','Do not cast Ebon Blade Banner if Ebon Blade Banner is planted');
```
After thinking a bit more about it, it does not seem correct to use this kind of condition either, because 2 players should be able to kill 2 mobs close to each other and plant the banner at the same time. I am guessing that this kind of issue needs a core spellscript.

**Comment by boom8866** [comment]
-- Condition for Ebon Blade Banner
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry`=23301;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,23301,0,0,30,1,192180,15,0,1,0,0,'','Do not cast Ebon Blade Banner if Ebon Blade Banner is planted');

----------
Fixes. small

**Comment by tkrokli** [comment]
Good point, I was thinking about whether or not to use `NegativeCondition`, but I forgot to test it.

**Comment by ellone716** [comment]
boom8866 commented Dec 25, 2015
 



-- Condition for Ebon Blade Banner
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry`=23301;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(17,0,23301,0,0,30,1,192180,1,0,1,0,0,'','Do not cast Ebon Blade Banner if Ebon Blade Banner is planted');

try this?
