### ISSUE TITLE
[6.x] DB/Creature: Southsea Freebooters Quest Glitch

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16086]
Killing pirates doesn't advance progress toward quest completion like it should. 

http://www.wowhead.com/search?q=Southsea+Freebooters

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by BahDumbBugs** [comment]
I'll try different Horde classes and report results here.

**Comment by tkrokli** [comment]
I presume you meant to link this quest: http://www.wowhead.com/quest=887/southsea-freebooters

**Comment by BahDumbBugs** [comment]
Youre right. My err. Merry Christmas.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
I am compiling 6.x right now, going to test it and report back very soon.
Commit hash:	41123795843b3d8b30084360a7244295dac1d200
Parent(s):	0988e8f543
