### ISSUE TITLE
[3.3.5] Core/Battleground: Multiple Battleground

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16080]
Right now there is an issue in battleground system that allow server to run multiple rbg at same time without enough players

for example: 15 players in 2 different rbg 7x player in Warsong and 8x player in another Warsong 

Revision: 94e4bdd

**Comment by L30m4nc3r** [comment]
Confrim.

**Comment by Spectrance** [comment]
@Leomancer  1

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
