### ISSUE TITLE
[3.3.5a] Deathbringer's will shapeshift bug  

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16095]
if you have Deathbringer's will you will became iron, taunka or vyrkul.
 now if one of this proc is still up, you can mount a horse with shapeshift up and this is a bug.
With iron dwarves work correctly but with the other two it doesn't . 

https://github.com/TrinityCore/TrinityCore/commit/cc685ac334335d9f6a25a7c1c739a905f919328f

**Comment by Goatform** [comment]
I guess you meant on mount scale ?

**Comment by Kittnz** [comment]
no he means he can mount up while in shapeshift form.

**Comment by Goatform** [comment]
Do you mean on e.g. : You are in cat form and Deathbginer's Will procs, you get transformed in some of 3 hero forms and you are able to cast mount without leaving cat form ?

**Comment by declart** [comment]
if im in a hero form i cant able to cast mount becouse shapeshift but its happen

**Comment by Goatform** [comment]
I don't agree with you. As I said above using mount when you have some of these 3 forms of northrend heroes is blizzlike.

**Comment by declart** [comment]
http://www.arenajunkies.com/topic/148289-deathbringers-will-cancel-mount/ 

In bg is not a blizzlike im really sure, in this link he explain to use a macro to be able to use a mount

**Comment by Killyana** [comment]
The proc of this trinket is like any other proc, the player must be able to use the mount once morphed, if blizzard messed up with this in the past we will not reproduce their bugs.
