### ISSUE TITLE
Core: Random creature_text from a groupid if a all porbability are not 100%

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#16093]
TrinityCore rev. ab831507c64c
To reproduce the issue take the quest 20438, the start the event, you will notice the gnome will say "I should keep you around." every time you throw something. The problem is there's 6 texts in this groupid and the npc must say one of the randomly.
If you check the link bellow you will notice that the probability of thexts 6.0 to 6.4 is 100%  but for 6.5 it's 40%  Now change the probability of 6.5 to 100% and start the event a gain, you will notice that the gnome choose a random text and he doesn't repeat always the same.

https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/sql/old/3.3.5a/TDB53_to_TDB54_updates/world/2014_06_26_00_world_misc.sql#L104

**Comment by Shauren** [comment]
What you described is intended behavior. There are 2 selection modes for text
* Equal chance - triggered when all rows have the same chance set
* Percentage based - all percentages must SUM to 100

The problem that needs to be fixed is not reporting the sum error at startup.
