### ISSUE TITLE
Two Coilfang Engineers spawn inside terrain

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16104]
Core Rev: 347373264b4c
TDB: 335.60

![Engineers](http://i64.tinypic.com/332mmbb.png)

These two engineers located at the beginning of Steamvaults spawn partially inside the object in front of them resulting in a "Target is not in line of sight" error.

Fix for incorrect positioning sniffed from build 20779 (current patch)
```SQL
UPDATE `creature` SET `position_x`=-5.298958, `position_y`=-131.3911, `position_z`=-21.17339, `orientation`=4.817109 WHERE `guid`= 12686 AND `id`=17721;
UPDATE `creature` SET `position_x`=-21.93356, `position_y`=-126.7303, `position_z`=-21.71569, `orientation`=4.939282 WHERE `guid`= 12687 AND `id`=17721;
```

Fix for incorrect equip_template sniffed from build 20779 (current patch). Look [here](https://github.com/TrinityCore/TrinityCore/issues/16104#issuecomment-167449184) for additional info.
```SQL
UPDATE `creature_equip_template` SET `ItemID1`=1903 WHERE `CreatureID`=17721;
```

**Comment by msoky** [comment]
spawn must be from sniffs...no custom fix

**Comment by Kittnz** [comment]
i bet the whole instance spawns are not sniffed

**Comment by Saben65** [comment]
Fair enough, just sniffed retail and came up with this. 

```SQL
UPDATE `creature` SET `position_x`=-5.298958, `position_y`=-131.3911, `position_z`=-21.17339, `orientation`=4.817109 WHERE `guid`= 12686 AND `id`=17721;
UPDATE `creature` SET `position_x`=-21.93356, `position_y`=-126.7303, `position_z`=-21.71569, `orientation`=4.939282 WHERE `guid`= 12687 AND `id`=17721;
```

**Comment by Kittnz** [comment]
What about the other spawns in the dungeon?

**Comment by Saben65** [comment]
I am working on adding all the waypoints and spawns at the moment... Don't know if it will be up to TC standards when all is said and done. The waypoints are what worries me the most since I haven't seen a way to properly go through adding them, so I think I have some that are slightly off. Also, I don't know what the correct way to add the spawns would be. For my purposes, I just  deleted all the NPCs from the instance and re-added using GUIDs starting at 300,000 to save time.

Additionally, I am having trouble getting all the spawns. I ran around the instance for a good 30 minutes and am still missing two spawns. Not quite sure how the sniffer picks up data. I always thought it was just passively. Do you have to select the target at all?

Also had to do some hacks to get things working correctly like making the mobs that patrol through the water have a InhabitType of 1 instead of 2 so they don't do the swim animation when crossing the water pools, which I am pretty certain isn't blizzlike.

**Comment by Kittnz** [comment]
start your sniffer before you enter the dungeon for starters, i am not sure about the inhabittype, i guess that needs to be checked further

**Comment by Saben65** [comment]
Ah, that would explain it. I always started it after I entered to not get all the outside spawns. Thanks.

**Comment by Kittnz** [comment]
@Saben65 did you make an issue ticket with the new path's and spawn coordinates?

**Comment by Saben65** [comment]
Negative, the place is a mess atm. I will have to have another go with it once I get a little more time. Currently I am working on adding proper pathing to Kara.

**Comment by Aokromes** [comment]
@Saben65 jump into irc irc.rizon.net #trinity
