### ISSUE TITLE
Quest: The Art of Being a Water Terror

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16107]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

[Quest: The Art of Being a Water Terror](http://www.wowhead.com/quest=13091/the-art-of-being-a-water-terror)

Frostbolt casts on the possessed [Water Terror](http://www.wowhead.com/npc=30645/water-terror#controlled-abilities) is super unreliable, with casts frequently cancelling out of nowhere.

**Comment by velinath** [comment]
does the water terror count as a vehicle? could be related to #7450 if so

**Comment by Treeston** [comment]
Yes.

**Comment by tkrokli** [comment]
First time (that I can remember) seeing that removing a SAI script is the solution to an issue. :smirk_cat:

**Comment by Treeston** [comment]
@tkrokli that's sarcasm, right? :/

**Comment by tkrokli** [comment]
Oh. Not that I know. I haven't been here more than 2 years, so I just can't remember seeing SAI scripts being part of the solution in any other way than being added to the source, not removed.

**Comment by Treeston** [comment]
I've barely been around for two months, and I can remember a few (mostly boss adds transitioning to cpp).

**Comment by tkrokli** [comment]
OK, fair enough. Maybe I just haven't watched the TrinityCore updates closely enough. Delete these comments then?

**Comment by Treeston** [comment]
Don't really care :D
