### ISSUE TITLE
[3.3.5] Quest: The Sum Is Greater Than The Parts (13043)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16106]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

[Quest: The Sum Is Greater Than The Parts](http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts)

Multiple issues:
* Spawned mobs clip through the air
* Spawned mobs are stuck in evade mode and cannot be damaged
* Due to the above, Dr. Terrible spams the hell out of his on-engage emote

**Comment by Aokromes** [comment]
mmaps bug iirc.

**Comment by Rushor** [comment]
adding CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING for all spawned creatures solves the problem sometimes :)

**Comment by BahDumbBugs** [comment]
So the issue of mobs clipping through walls can be fixed with that, @Rushor?

**Comment by Rushor** [comment]
works for me yes

**Comment by BahDumbBugs** [comment]
Cool. Thanks!

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/9753
