### ISSUE TITLE
[3.3.5] Linen Cloth Taken From Bank Doesn't Register For The Tome of Divinity Quest

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#16108]
Build: https://github.com/TrinityCore/TrinityCore/commit/812809a977e2ba2a53e55c3dfc74bbed9dd59b7a

I had several stacks of Linen Cloth in my bank. I took one stack of 20 out of it, split it into 2 stacks of 10, and put one stack back into the bank. I then immediately walked to Stephanie to give her the cloth, but the cloth didn't register (even after logging out and back in).

I sold the stack of cloth, repurchased it, and it registered then. Not really sure what would cause that to happen, but I assume it's a global thing with taking quest requirements out of the bank?

![wowscrnshot_122715_065916](https://cloud.githubusercontent.com/assets/6378956/12010133/0241384c-ac68-11e5-8407-2435ccc4853d.jpg)

**Comment by Gacko** [comment]
```but I assume it's a global thing with taking quest requirements out of the bank?```

Did you test that?

**Comment by Killyana** [comment]
No, in this case retake the quest or put items in the bank and get them back, there's already an issue but I cannot find it.
