### ISSUE TITLE
[3.3.5a] Creature: Tournament Druid Spell Target visible

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16119]
dbe854c

The units that Fhyron Shadesong uses to target the trees for a spell effect at the Argent Tournament are visible to all players.

I checked in the database, and `flags_extra` is set to 128 in character table (`CREATURE_FLAG_EXTRA_TRIGGER`), so I am not sure how to proceed from here.

http://www.wowhead.com/npc=33787/tournament-druid-spell-target

**Comment by Saben65** [comment]
Not sure if this breaks functionality or if it is the correct way to do it. The NPCs have a modelid set in their `creature`. Setting it to 0 hides them from the player, and only allows them to be seen with .gm on.

Suggested fix
```SQL
UPDATE `creature` SET `modelid`=0 WHERE `id`=33787;
```

to revert to default

```SQL
UPDATE `creature` SET `modelid`=1126 WHERE `id`=33787
```
