### ISSUE TITLE
[6.x] DB/Creature: Nalpak Missing

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16114]
Wailing Cavern Quests Cannot be completed without Nalpak. He is not in the position he should be
Checked outside the Wailing Caverns (In the eyes) and inside the Instance. Anyone else have this issue? 

http://www.wowhead.com/npc=5767/nalpak
Ends the quest http://www.wowhead.com/quest=26878/disciples-of-naralex

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by BahDumbBugs** [comment]
Question mark shows up on the mini map, by Muyoh but NPC Nalpak is not with him. Confirmed on multiple toons.

**Comment by Rushor** [comment]
```sql
USE `tc_wod_master_world`;
select * from creature where id=5767;
/* Affected rows: 0  Gefundene Zeilen: 0  Warnungen: 0  Dauer von 1 query: 0,109 sec. */
```

**Comment by BahDumbBugs** [comment]
@Rushor thanks! I'll let you know result.

**Comment by Saben65** [comment]
I don't have TDB 6.x to check for available GUIDs.

```SQL
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `phaseId`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `MovementType`) VALUES
(XXXXX, 5767, 43, 3, 1, '', -150.298, 123.82, -75.95126, 3.228859, 7200, 0, 0), -- 5767 (Area: -1)
```

**Comment by DDuarte** [comment]
Don't worry about the guids, whoever pushes this will assign proper guids.

Define a @GUID variable and set it to XXXX.

**Comment by tkrokli** [comment]
:+1: Thanks for the contribution, @Saben65 :)
