### ISSUE TITLE
[3.3.5] William Kielar (EPL tower FP)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16112]
Branch 3.3.5, commit 0bb2ba7b35c7cd136b4371f6d284eba0bd34b6e5

EPL tower flight master [William Kielar](http://www.wowhead.com/npc=17209/william-kielar)

First gossip option (Northpass) takes you to Crown Guard instead, while the other two gossip options (Eastwall and Crown Guard) do nothing when selected.

**Comment by Killyana** [comment]
Some code is missing: https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/src/server/scripts/World/npc_taxi.cpp#L303
``` cpp
        case GOSSIP_ACTION_INFO_DEF + 29:
            player->CLOSE_GOSSIP_MENU();
            player->ActivateTaxiPathTo(497);
            break;
        case GOSSIP_ACTION_INFO_DEF + 30:
            player->CLOSE_GOSSIP_MENU();
            player->ActivateTaxiPathTo(498);
            break;

**Comment by Aokromes** [comment]
IMHO it must be moved to DB with conditions.

**Comment by Killyana** [comment]
Many scripts must be moved to the DB, and we don't have enough devs for that.

**Comment by velinath** [comment]
#15957 was a similar issue. I can try and look at this later on tonight as I would imagine the solution would be similar as well. Correct me if I'm wrong, though.

(also, ref PR #15966)

**Comment by Killyana** [comment]
I will push the fix for the cpp, You can move it to DB if you want.

**Comment by velinath** [comment]
Will take a look tonight and open a PR if I figure it out. Thanks.

**Comment by Treeston** [comment]
closed  b6ed3d3

**Comment by ShinDarth** [comment]
@Killyana @Aokromes  maybe we can list all of those scripts who need to be ported from c++ to database somewhere so guys like @velinath and @tkrokli can easily help with them

**Comment by tkrokli** [comment]
@ShinDarth : the good thing now is that /src/server/scripts/World/npc_taxi.cpp is a lot smaller. :-)

**Comment by velinath** [comment]
@ShinDarth I'm hoping to spend some time with this today. I will be starting with npc_taxi where I can.

Aokromes listed a few here https://github.com/TrinityCore/TrinityCore/pull/15966#issuecomment-167864140, which may be of use for that list.

**Comment by Aokromes** [comment]
Few? no, i listed all :) (and updated the list yesterday)

**Comment by velinath** [comment]
Haha, great doc for me to be working off of then - I will download the updated list :+1:

**Comment by tkrokli** [comment]
OK, I have cloned the list to my own pastebin. I am currently looking at ways to handle the first line since I have been working a lot with the DK starting area in a few issues and PRs.

**Comment by ShinDarth** [comment]
@Aokromes  what about creating an issue/milestone instead of using just pastebin?

**Comment by tkrokli** [comment]
@ShinDarth : check out https://github.com/velinath/TrinityCore/issues/2 :smiling_imp:
