### ISSUE TITLE
[6.x] DB/Creature: Ragefire Chasm Bosses

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16113]
If this is a repeat of #6661, I apologize but the names weren't matching up to what's on my map. I took my L100 into Ragefire Chasm and looked on my map. What I found and fought did not correspond to the map. 

On the Map:
1) Adarogg
2) Dark Shaman Koranthol
3) Slagmaw
4) Lava Guard Gorgoth

Found, none of those. Just regular mobs in the areas where the bosses should be.

If you need me to link the NPC Mobs from Wowhead, I will. Just let me know.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by MitchesD** [comment]
6.x is alpha, 99% of WoD content isn't spawned/done, neither MoP content, and half of Cata.

**Comment by BahDumbBugs** [comment]
I understand that; at least Im finding things to be fixed to bring it forward to beta more, right?

**Comment by MitchesD** [comment]
well, you need to sniff spawns, then get correct spawns and set phasing, script instance script and all bosses, it takes a lot of research for each boss

**Comment by DDuarte** [comment]
> I understand that; at least Im finding things to be fixed to bring it forward to beta more, right?

Yes, report any issue that you find, doesn't matter how small it is. We (or someone else) might not have immediate fixes for them but that doesn't mean that issues should not be documented and reported.

**Comment by BahDumbBugs** [comment]
Understandable @MitchesD , but as an Alpha/Beta tester for multiple games and applications on multiple systems in the past - its my hobby and duty to help you all. As @DDuarte mentioned, every little bit helps. I know things may not get fixed at the drop of a hat and some research is required and can take aaaaaggggeeeeesssss (*cough* Battle Pet Training *cough*) and other things are merely cosmetic fixes which can be fixed easily, its good to have a list of any and all things found wrong. Im on your side here (Unless youre an Alliance fan :D ) - when it comes to squishing bugs, that's why we do what we do! Code on!

**Comment by MitchesD** [comment]
How do you want to test something what isn't scripted? Not sure if it's good to report everything whats not scripted. We know zones which aren't spawned yet, and then logically they aren't scripted too. In that way you can create thousands of tickets for every single boss/npc on WoD and the result will be the same as it is atm. At first someone have to spawn/script it, then there can be some possible bugs or things which should be reported.

If you find some NPC missing/non scripted on Cata or Wotlk, which are already scripted (mostly) then it's good to report, but I see it pointless to report nonspawned zones.

**Comment by BahDumbBugs** [comment]
I never planned to report all bosses. I figured one instance will be the same as the rest. Im just taking it as it comes. My primary focus is the overworld and the quests at the start. Ive already run through the entireity of Pandaria and Draenor for kicks and giggles. So if you want me to stop reporting, I will gladly oblige. Just dont want to step on toes here, hence my reason for asking.

**Comment by Saben65** [comment]
Adarogg - 61408
Dark Shaman Koranthal - 61412
Slagmaw - 61463
Lava Guard Gordoth - 61528

```SQL
SET @CGUID := XXXXX;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+1;
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `phaseId`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `MovementType`) VALUES
(@CGUID+0, 61408, 389, 3, 1, '', -284.6381, -53.8253, -60.73442, 0.3210851, 7200, 0, 0), -- 61408 (Area: -1)
(@CGUID+1, 61528, 389, 3, 1, '', -369.501, 166.2117, -18.52023, 1.312978, 7200, 0, 0), -- 61528 (Area: -1)
```

Those are the spawns for Gordoth and Adarogg. Tried for quite a while to get all of them, but the sniffer didn't want to pick up slagmaw or Koranthal. Gordoth appears to be spawned in with a trigger, so I am not sure how that affects the sniff data.

**Comment by BahDumbBugs** [comment]
Thanks @Saben65 , even if its not complete, it still helps us all with a poke in the proper direction. Time will complete this for us all.

**Comment by Rushor** [comment]
better report all missing spawn/instancescript in one ticket until someone will open a pr for it. 

i updated https://github.com/TrinityCore/TrinityCore/issues/13179 with all missing/outdated classicinstancescripts
