### ISSUE TITLE
Access to Lost Isles for testing

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16116]
Is there any way to access the Lost Isles as a GM? Ive tried about every listed area on the Lost Isles and every command I can think of. Can anyone give me a shove in the right direction please?

Thanks!

(Pardon the wrong forum)

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by MitchesD** [comment]
This is not a forum, for your questions use https://community.trinitycore.org/ 

Issue tracker is for bugs and fixes.
