### ISSUE TITLE
Core/Misc: item level not increasing with better gear

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16111]
As the subject states, I looted better gear fro my toons and no matter which toon I play on, any faction - the iLVL simply doesnt increase with better gear. It remains at 0/0 and all the equipment I have on is 20 or better. Just looted Blues from Ragefire Chasm and still found it at 0/0.

Is this a repeat? I checked and couldnt find anything.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Shauren** [comment]
yes.

**Comment by mhubregtse** [comment]
Any updates on this yet?

**Comment by Aokromes** [comment]
No.

**Comment by BahDumbBugs** [comment]
As of commit e0fb444 this bug is still outstanding. Just for posterity. - Carry on.
