### ISSUE TITLE
[3.3.5a] Ghostlands: Ash'ari Crystals are inside Ziggurats

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16121]
dbe854c

In Ghostlands, there are two ziggurats: the Howling and Bleeding Ziggurats. In both of these ziggurats, there is an Ash'ari Crystal sitting in the middle of the ziggurat (where players must go to complete quests). I believe this should actually be sitting up above the ziggurat.

http://www.wowhead.com/npc=10415/ashari-crystal

**Comment by Saben65** [comment]
The crystal appears to spawn ontop of the ziggurats, then proceeds to fall down.
