### ISSUE TITLE
[3.3.5] DB/Creature: Time-Lost Proto Drake movement

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16137]
Branch 3.3.5, revision fb14cb7e4fbf

[Time-Lost Proto Drake](http://www.wowhead.com/npc=32491/time-lost-proto-drake) does not fly. Instead he teleports to his supposed height periodically, then falls to the ground and does nothing.

(Also, his spawn is still broken, ref #7683).

**Comment by NorthStrider** [comment]
tried   UPDATE `creature_template` SET `InhabitType`= 4 WHERE `entry`= 32491; already?

**Comment by dr-j** [comment]
Spawning system for tlpd literally all spawn points are static rather than the 4 spawn points/paths which cross most of zone as is on retail on tc theres about 20 static spawns of tlpd which are pooled.

https://github.com/TrinityCore/TrinityCore/issues/7683

**Comment by RedSonja** [comment]
I am getting the same thing.

**Comment by Kodekc** [comment]
Fixed movement Time-Lost Proto Drake and health for Vyragosa

``` sql
UPDATE `creature_template_addon` SET `bytes1`='50331648' WHERE  `entry`=32491;
UPDATE `creature` SET `curhealth`='18900' WHERE  `guid`=202602;
```
