### ISSUE TITLE
[3.3.5] Emerald Dream instance_template and game_tele

### ISSUE THREAD

**Issue by Helias** [TrinityCore/TrinityCore#16131]
Core rev: https://github.com/TrinityCore/TrinityCore/commit/13e509a622a6d88afe27d6cdda4cf9f402818745

I saw the Emerald Dream "instance", the incomplete blizzard project of WoW that exists from WoW Classic 1.12 so I made the game_tele of this and I want to share to TrinityCore.

```SQL
DELETE FROM `instance_template` WHERE `map` = 169;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES
(169, 0, '', 0);

DELETE FROM `game_tele` WHERE `id` IN  (1425, 1426, 1427, 1428);
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES 
(1425, -366.091, 3097.86, 92.317, 0.0487625, 169, 'EmeraldDream'),
(1426, 2781.566406, 3006.763184, 23.221882, 0.5, 169, 'EmeraldStatue'),
(1427, -2128.12, -1005.89, 132.213, 0.5, 169, 'VerdantFields'),
(1428, 2732.93, -3319.63, 101.284, 0.5, 169, 'EmeraldForest');
```

Edit (DDuarte): Removed quotes around numbers in the SQL

**Comment by MitchesD** [comment]
I understand game_tele, but dunno why you added an instance template. It's not instance and it never be. Also if I am not wrong, this instance template will require instance script, because you assigned it to emerald_dream.

**Comment by Helias** [comment]
As I said in IRC, I had to add instance_template because TrinityCore doesn't read the map 169, without it, the server consider the map 169 as an invalid map and don't load the game_tele of the map.

**Comment by tkrokli** [comment]
Glad to see you post this, @Helias. :+1: Looking forward to see it in-game, either as TC source or not.

**Comment by Helias** [comment]
@tkrokli you need the texture pack to see the texture in EmeraldDream (you can download it from here https://www.dropbox.com/s/dxw2oas049im12d/patch-e.mpq?dl=0 ) put it on WoW / Data / patch-e.mpq

**Comment by tkrokli** [comment]
Nice, thanks! :)

**Comment by Killyana** [comment]
Can this be pushed?

**Comment by DDuarte** [comment]
Imo yes
