### ISSUE TITLE
[3.3.5] DB/Quest: The Hunt is On (11794)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16133]
Branch 3.3.5, revision 79c9af11b9a90b051ecc26b0a60e879e3d9c4134

[Quest: The Hunt is On](http://www.wowhead.com/quest=11794/the-hunt-is-on#screenshots:id=262507)

Quest functionality works fine, however quest targets do not display a dark glow around them while the player has the [Righteous Vision](http://www.wowhead.com/spell=46078/righteous-vision) buff. In addition, quest target [Tom Hegger](http://www.wowhead.com/npc=25827/tom-hegger) does not have the proper target set for his aggro talk (it displays $c).

**Comment by Saben65** [comment]
Looks like the spell needs core support. The NPCs were missing the aura, and it still doesn't show after adding it.

```SQL
DELETE FROM `creature_template_addon` WHERE `entry` IN (25248,25827,25828);
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(25248, 0, 0x0, 0x1, '46077'), -- 25248 - 46077
(25827, 0, 0x0, 0x1, '46077'), -- 25827 - 46077
(25828, 0, 0x0, 0x1, '46077'); -- 25828 - 46077

DELETE FROM `creature_addon` WHERE `guid` IN (117733,111073,117769);
INSERT INTO `creature_addon` (`guid`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(117733, 0, 0x0, 0x1, '46077'), -- 25827 - 46077 - 46077
(111073, 0, 0x0, 0x1, '46077'), -- 25248 - 46077 - 46077
(117769, 0, 0x0, 0x1, '46077'); -- 25828 - 46077 - 46077
```

**Comment by tkrokli** [comment]
About Tom Hegger not having a proper target, he probably needs to target his speech/yell like this (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_borean_tundra.cpp#L2316-L2320) :
```diff
                            case NPC_TOM_HEGGER:
-                               Talk(SAY_HIDDEN_CULTIST_3);
+                               Talk(SAY_HIDDEN_CULTIST_3, player);
                                uiEventTimer = 5000;
                                uiEventPhase = 2;
                                break;
```
That is at least the method that worked for `npc_mootoo_the_younger`
(feel free to correct me if it does not work the same way in this case).

**Comment by Aokromes** [comment]
This fix is valid? if yes, plz open a PR for it.

**Comment by tkrokli** [comment]
OK, I did not have an exact solution for this one 6 months ago, but now that I know more about how the compiler expects the parameter 'player' to be defined in a script, I have got one. Linking it below.

Please note: my PR only fixes the $c part of this issue, I don't know how to fix the visual aura. I suspect that the aura part has to be fixed in some kind of spell script or by linking a spell trigger to the spell used by the quest item (or maybe even that the quest item uses a triggered spell instead of the spell trigger).

**Comment by Aokromes** [comment]
736843fbb5442b1338ec888c8a702d666c95a76b

**Comment by Saben65** [comment]
This only addressed half the issue. There is still the issue with the aura. Shouldn't this be re-opened?

**Comment by Killyana** [comment]
Fixed by last changes on spells, by ariel.
