### ISSUE TITLE
[6.x] Healing Training Dummy

### ISSUE THREAD

**Issue by Foldor** [TrinityCore/TrinityCore#16139]
Rev: c08623e19a98890fea9e02a822c2d5720ae44dc1

Bug: the healing dummies are currently getting killed by their dot aura. 
On retail they do not go below 1hp.

```sql
EDIT: SAI sql removed as their is a c++ script for this as mentioned by Killyana
```

**Comment by Killyana** [comment]
There's a cpp for this npcs ScriptName: npc_training_dummy

**Comment by Foldor** [comment]
I don't know much about the core scripting so i'll leave this open for someone more knowledgeable to fix.

**Comment by BahDumbBugs** [comment]
I can confirm this glitch. The training dummy wont go below 1 HP, and furthermore, it will not release you from combat. No matter where you run, unless you engage another mob, it will keep you in combat status thus preventing you from exiting the game, utilizing taxis, among other events.

**Comment by msoky** [comment]
ScriptName: npc_training_dummy is very bad...if you delete them, class training on start locations will work

**Comment by BahDumbBugs** [comment]
@msoky - Thanks! I'll give that a whirl. Keep you posted.

**Comment by Rushor** [comment]
moved to the todolist in https://github.com/TrinityCore/TrinityCore/issues/15814
