### ISSUE TITLE
[3.3.5] Quest: Master and Servant (11730)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16136]
Branch 3.3.5, revision 79c9af11b9a90b051ecc26b0a60e879e3d9c4134

[Quest: Master and Servant (11730)](http://www.wowhead.com/quest=11730/master-and-servant)

Quest item [The Ultrasonic Screwdriver](http://www.wowhead.com/item=35116/the-ultrasonic-screwdriver) should be usable in all sub-zones of the Geyser Fields in Borean Tundra, but is only usable in certain ones.

**Comment by Killyana** [comment]
The condition on the spell is useless as all possible target are in the Geyser Fields.
``` sql
DELETE FROM `spell_area` WHERE `spell` IN(46023);
