### ISSUE TITLE
3.3.5 Wrong Spawn in Dalaran

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16134]
TrinityCore rev. 13e509a622a6 2015-12-30 02:05:24 +0100 (HEAD branch)

This NPC Spawn an a wrong Date
http://www.wowhead.com/quest=14036/pilgrims-bounty

![wowscrnshot_123115_140535](https://cloud.githubusercontent.com/assets/10637389/12064631/5239e32c-afc8-11e5-9486-506389342a70.jpg)

**Comment by msoky** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/16129

**Comment by Rushor** [comment]
moved the issue to the todolist from https://github.com/TrinityCore/TrinityCore/issues/16129
