### ISSUE TITLE
[3.3.5] Grounding Totem - Missing huntertraps

### ISSUE THREAD

**Issue by Re3os** [TrinityCore/TrinityCore#16145]
Huntertraps no redirect to grouding totem
Link:
Freezing Trap
http://www.wowhead.com/spell=60192/freezing-trap

Grounding totem
http://www.wowhead.com/spell=8177/grounding-totem

rev.https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

**Comment by Saben65** [comment]
Sources: 
http://www.wowhead.com/spell=8177/grounding-totem#comments:id=253372 - 2.3.3
http://www.wowhead.com/spell=8177/grounding-totem#comments:id=1056475 - 3.3.3

**Comment by Goatform** [comment]
Check this PR: #16146

**Comment by Re3os** [comment]
@Goatform nice,it's work)
