### ISSUE TITLE
[3.3.5] The Crippler (18689)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16148]
3.3.5 b6ed3d3fc2b8447059ff0aa0e5b6de36947fd006

18689 has UNIT_FLAG_DISABLE_MOVE set which makes him keep pathing normally while in combat.

**Comment by tkrokli** [comment]
Sorry if this seems too obvious, I thought it would be useful to have this info at hand, at least for others.
(btw, you wrote "patching", I guess autocorrect did that and you meant to write "pathing"?)

http://wow.gamepedia.com/Crippler || http://www.wowhead.com/npc=18689/crippler
```sql
SELECT `entry`,`name`,`faction`,`npcflag`,`unit_flags`,`unit_flags2`,`mechanic_immune_mask`,`VerifiedBuild`
FROM `creature_template` WHERE `entry` = 18689;
```
```
 entry  name      faction  npcflag  unit_flags  unit_flags2  mechanic_immune_mask  VerifiedBuild
------  --------  -------  -------  ----------  -----------  --------------------  -------------
 18689  Crippler       14        0           4         2048               8388624          12340
```
https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-unit_flags

Flag | | Name | Comments
--- | --- | --- | ---
4 | 0x0000 0004 | UNIT_FLAG_DISABLE_MOVE | Prevents the creature from moving at all

**Comment by Treeston** [comment]
Thanks for that, posting from mobile.
