### ISSUE TITLE
[3.3.5a][DK] Core/Spell:  Death and decay disappear

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16154]
if i start battle with D&D and the rogue sap me, the D&D disappear 

http://i.imgur.com/RLqORqj.jpg

https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

**Comment by declart** [comment]
i want to correct my issues, if i hit with D&D an enemy in stealth it disappear, also he doesnt get any damage and isnt go out from stealth.

https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by tkrokli** [comment]
I thought that would be handled by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2518-L2519
```cpp
            if (!m_spellInfo->HasAttribute(SPELL_ATTR0_CU_DONT_BREAK_STEALTH))
                unit->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);`
```
but apparently, it does not (if death & decay is supposed to break stealth). Wrong attribute somewhere?

**Comment by declart** [comment]
i want to say another thing, if i put D&D on the ground, and a rogue( in stealth)  walk on it the spell disappear.

**Comment by tkrokli** [comment]
That sounds very similar to the issue with rogues in stealth making hunter's freezing trap disappear:
[**{Spell/hunter}Hunter trap vs invisibility creatures**](10179) #10179

**Comment by declart** [comment]
But freezing trap work as game object, death and decays is a spell

**Comment by tkrokli** [comment]
Yes, I was only wondering if the rogue stealth spell causes something unwanted to happen (don't know).

**Comment by mik1893** [comment]
freezing trap is a game object , and death and decay is a gameobject - both are spell-created - so it might be related to the trap issue as @tkrokli states

**Comment by Shauren** [comment]
Death and Decay is a DynamicObject, not a GameObject

**Comment by mik1893** [comment]
ok but if it gets added to the list in robinsch check it gets fixed...
