### ISSUE TITLE
[3.3.5] From Their Corpses, Rise! (12813)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16167]
Branch 3.3.5, rev. 8a0bbc386982

[Quest: From Their Corpses, Rise!](http://www.wowhead.com/quest=12813/from-their-corpses-rise)
Provided item [Darkmender's Tincture](http://www.wowhead.com/item=40587/darkmenders-tincture) can be repeatedly used on a single corpse. It should only be usable once per corpse.

**Comment by tkrokli** [comment]
Could probably be solved by a similar conditiion to the one used in [DB/Quest: Fix spell target for Leave Our Mark quest item](https://github.com/TrinityCore/TrinityCore/commit/b269c1f1cb92389c125a29a99c5c811dbfdd89c1)(commit b269c1f), solution to  [3.3.5a] Quest: Leave Our Mark #16081, but I struggle to find NPC ID for the corpse or if it is an object.

**Comment by Saben65** [comment]
I am pretty sure the corpses are of any NPCs you kill in this list.

http://www.wowhead.com/npcs=7?filter=na=onslaught;cr=6;crs=210;crv=0
