### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Incorrect quest credit targeting for 'Feeding Arngrim' (13046)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16169]
Branch 3.3.5, rev. 8a0bbc386982
[Quest: Feeding Arngrim](http://www.wowhead.com/quest=13046/feeding-arngrim)
[Creature: Disembodied Jormungar](http://www.wowhead.com/npc=30423/disembodied-jormungar)

Quest credit is awarded to the Jormungar's current victim at the time, instead of to all players that tagged the Jormungar. This means that the quest
a) does not grant group credit
b) grants credit to the wrong player if a non-tagging player somehow makes the mob attack them instead (taunt)
c) does not grant credit at all if the Jormungar is attacking a pet or guardian

**Comment by dr-j** [comment]
a) using target 16 for credit should fix thi
b) Not easily fixable unless target 24 (All threat list)
c) This is the case with a lot of npcs in 3.3.5 (ie if a pets or guardians do more than 51% damage to a given npc then players wont receive kill credit

**Comment by Treeston** [comment]
c) is purely related to threat, not damage.

Also, the 51% bug you describe should be fixed as of #15473.

**Comment by Treeston** [comment]
Use case for `SMART_TARGET_LOOT_RECIPIENTS` (27)?

**Comment by tkrokli** [comment]
Looks very plausible to me, because quest credit should go to the player(s) who tapped the target (and therefore are eligible to loot the target).
