### ISSUE TITLE
[3.3.5][6.x] DB/Quest: You'll Need a Gryphon (12814)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16166]
Branch 3.3.5, rev. 8a0bbc386982
[Quest: You'll Need a Gryphon](http://www.wowhead.com/quest=12814/youll-need-a-gryphon)
[Onslaught Gryphon](http://www.wowhead.com/npc=29403/onslaught-gryphon) summoned by the dropped [Onslaught Gryphon Reins](http://www.wowhead.com/item=40970/onslaught-gryphon-reins) is not capable of flying.

**Comment by Rushor** [comment]
adding flying aura in creature_template_addon fixes this

**Comment by tkrokli** [comment]
You mean something like this?
```sql
--
DELETE FROM `creature_template_addon` WHERE `entry`= 29403;
INSERT INTO `creature_template_addon` (`entry`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES
(29403, 0, 0, 0, 1, 54422); -- add aura 'Flying' to Onslaught Gryphon
```
This is based on NPC 29414 Bone Gryphon, which also has the aura 'Blood Presence' (54476).

**Comment by puder** [comment]
@tkrokli  that work nice ;)

**Comment by tkrokli** [comment]
@puder : would you say that my suggested insert into `creature_template_addon` is a valid solution,
that it does not cause any new errors?

Checking current DB for any existing entries for entry 29403:
TrinityCore rev. c0b6b164f01a 2016-04-09 18:58:06 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.60 + updates up to and including `2016_04_09_04_world.sql`
```sql
SELECT * FROM `creature_template_addon` WHERE `entry`= 29403;
```
Result: `<empty>` (current DB content)

**Comment by Treeston** [comment]
Looks good to me :+1:
