### ISSUE TITLE
6.x Elevator teleports instead of moving

### ISSUE THREAD

**Issue by bobby1212** [TrinityCore/TrinityCore#16174]
I noticed today that the elevator in halls of origination jumps to the platforms instead of moving slowly.
Maker's LiftController (Entry: 207669)
I checked the database for this but I doesn't found anything wrong. I compared it with working elevators.
So anybody an idee what it could be?
I don't implicitly need a fix, I simply need a suggestion, for what it could be.
Core Revision: 9ab47a1
TDB Rev: 6.03

**Comment by Aokromes** [comment]
#14704
