### ISSUE TITLE
[3.3.5] SQL fix: Fix textrange for Algalon the Observer

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16170]
Branch 3.3.5, rev. 8a0bbc386982
Algalon's texts are currently short-ranged, being out of range even as close as the entry to the Planetarium.

```sql
UPDATE `creature_text` SET `TextRange`=3 WHERE `entry`=32871;
```

**Comment by Trisjdc** [comment]
Imo, text range for all instance bosses should probably be map-wide.

**Comment by Ascathor** [comment]
Do we have any sniffs on that ?

**Comment by Saben65** [comment]
TextRange is a table added by TC I believe as I couldn't find a similar table or data from the sniffs. He does use "say" as well as "yell", so I don't know if every text should be map-wide.

**Comment by Treeston** [comment]
Feel free to test it, but generally speaking, anything a raid boss does is zone-wide.

Standing at the entrance of his room and only getting tidbits of his intro is pretty much guaranteed to not be blizzlike :laughing:

**Comment by tkrokli** [comment]
```
*Onyxia draws a deep breath*
```
... was once triggered when setting the non-combat pet 'Onyxia Hatchling out at the Onyxia entrance :smile:

**Comment by Kittnz** [comment]
Indeed, Trisjdc is right

**Comment by Killyana** [comment]
Yes  TextRange = 3	= Map so it's correct.
