### ISSUE TITLE
[3.3.5] Stealth Detection for Steamvaults Creatures fix

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16185]
Rev: 10757e60f1fb
TDB: TDB 335.60

[Bog Overlords](http://www.wowhead.com/npc=21694/bog-overlord), [Mekgineer Steamrigger](http://www.wowhead.com/npc=17796/mekgineer-steamrigger) and [Hydromancer Thespia](http://www.wowhead.com/npc=17797/hydromancer-thespia) should all have [Invisibility and Stealth Detection](http://www.wowhead.com/spell=18950/invisibility-and-stealth-detection) per sniff data.

Suggested Fix
```SQL
DELETE FROM `creature_template_addon` WHERE `entry` IN (21694,21914,17796,17797,20629,20630);
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(21694,0,0x0,0x1,'18950'), -- 21694 - 18950
(21914,0,0x0,0x1,'18950'), -- 21914 - 18950
(17796,0,0x0,0x1,'18950'), -- 17796 - 18950 
(17797,0,0x0,0x1,'18950'), -- 17797 - 18950 
(20629,0,0x0,0x1,'18950'), -- 20629 - 18950
(20630,0,0x0,0x1,'18950'); -- 20630 - 18950
```

Additionally, Bog Overlords currently have [Disease Cloud](http://www.wowhead.com/spell=37266/disease-cloud) scripted into their SAI. From sniffs, the aura is applied to `creature_template_addon` so I do not know if it should be moved from SmartAI to `creature_template_addon` or just left in the SmartAI.

**Comment by Saben65** [comment]
Anyone have any input?

**Comment by tkrokli** [comment]
Looks like you're just waiting for the pu(ni)sher to come around, since it's already labeled a fix...

**Comment by Killyana** [comment]
For where you get this auras?

**Comment by Saben65** [comment]
It was from sniff data.
