### ISSUE TITLE
[3.3.5] Share Quest does not work if quest objective is complete

### ISSUE THREAD

**Issue by lordwind68** [TrinityCore/TrinityCore#16183]
branch: 3.3.5
rev: [f377a58](https://github.com/TrinityCore/TrinityCore/commit/f377a5875cc320934573f5980cd99388ca45f7d3)

When you try to share a quest while in a group, the quest will only share if the objective is incomplete.

This makes most(if not all) quests where the objective is to speak to another NPC un-shareable, as the objective is complete the moment you accept the quest.

How to replicate:
-Make 2 dwarves on 2 accounts.
-Group up
-Accept very first dwarf quest on 1 character
-At this point, it IS sharable.
-complete the quest, but don't hand it in (.quest complete questID)
-Quest can no longer be shared. (edit: Share button can be clicked, but does nothing)

**Comment by Treeston** [comment]
Define "can no longer be shared". The button is greyed out, or the button does nothing?

**Comment by lordwind68** [comment]
Sorry.

The button is clickable, but does nothing when clicked.

**Comment by Killyana** [comment]
Confirm, I was thinking it is the retail behavior.

**Comment by lordwind68** [comment]
I can't see it being retail behavior, but maybe I remember wrath wrong... it makes any quest with an auto complete objective (quests that require you to go to another npc) impossible to share, despite them having the shareable flag.

**Comment by Treeston** [comment]
Pretty sure it isn't retail behavior (especially since UI indicates the quest should still be sharable).

**Comment by lordwind68** [comment]
The lines I have commented out in the following snippet from QuestHandler.cpp fixes the problem. Uncommenting them brings the problem back. Haven't tested if it causes any other issues though. Thoughts?

```C++
void WorldSession::HandlePushQuestToParty(WorldPacket& recvPacket)
{
    uint32 questId;
    recvPacket >> questId;

    /* if (!_player->CanShareQuest(questId))
        return; */
    
    TC_LOG_DEBUG("network", "WORLD: Received CMSG_PUSHQUESTTOPARTY questId = %u", questId);
```

**Comment by tkrokli** [comment]
I agree 100% with you, @Treeston. If a quest is not supposed to be shareable, it should not have the button enabled in the first place. Either the quest flags are wrong, or the sharing functionality is bugged.

**Comment by Aokromes** [comment]
humm, the "very first dwarf quest" is not sharable for me, nor on tc, nor on retail.

**Comment by lordwind68** [comment]
[#179](http://www.wowhead.com/quest=179/dwarven-outfitters)
isn't shareable for you?

**Comment by Aokromes** [comment]
nope.

**Comment by lordwind68** [comment]
Are you able to accept a quest on one character that you know is shareable, complete the objective, and then share it with another player?
