### ISSUE TITLE
[3.3.5][6.x] Core/Chat: Joining a channel creates empty invalid channels

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#16190]
Joining a channel with a number name like `/join 100` will not join a channel but it will still show up in the UI under Social (O) chat tab:
![](http://i.imgur.com/kvGtwcz.png)

The channels can not be removed and trying to use them says you are not on the channel.
Seems it is hard coded that you can not join a channel that has a number as first character of the name.

I do not know what is the blizzlike behavior!

3.3.5
https://github.com/TrinityCore/TrinityCore/commit/f22b1938db5cddcb2a9988ff54dfa08d2fa1aecc

On 7.2.5 the behavior when entering bad channel (like an integer) is
![Invalid channel name](https://i.imgur.com/PD5DY1R.png)

**Comment by Langerz82** [comment]
working on this.

**Comment by Langerz82** [comment]
Ok the problem is if we remove the:
'''
    //if (isdigit(channelName[0]))
    //    return;
'''
Then it allows you to create a channel with numbers but you cant leave the channel via the client because it does not send a CMSG_CHAT_LEAVE_CHANNEL packet in the chat social window for channels with numbers you have to manually leave it by doing (/leave #channelNumber ).
I'm thinking maybe we send a CMSG_CHAT_CHANNEL_DISPLAY_LIST packet and a error message on creation of numbered channels.

**Comment by Langerz82** [comment]
See Patch:
https://gist.github.com/Langerz82/c110dec6f5b468ed4e6e504f0b5aa138

Also needs SQL command:
INSERT INTO trinity_string (`entry`, `content_default`) VALUES (10056, 'Channel must not start with a digit');

**Comment by funjoker** [comment]
Now the question. If this is on 6.x too.
Why closing it here?
Or is it only 3.3.5 ?

**Comment by Aokromes** [comment]
It will be cherry picked.

**Comment by Shauren** [comment]
@funjoker issues are closed after being fixed in at least one branch

**Comment by funjoker** [comment]
isnt it getting lost then somehow`?

**Comment by tkrokli** [comment]
As far as I know, the `3.3.5` commits are saved in a [DEV] list for cherry-picking (and the `master` commits are saved in a list to be evaluated for cherry-picking to `3.3.5`).
