### ISSUE TITLE
[3.3.5a] Creature: Skyguard Handler/Skyguard Nether Ray

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#16197]
These two mobs should be on a patrol route around Blackwind Landing. This behaviour can be seen on retail. The nether ray is slightly ahead of the handler.

On TC, the nether ray currently has random movement and the handler is idle.

NPC GUIDs: 
79010: Skyguard Nether Ray
79012: Skyguard Handler

13e509a

http://www.wowhead.com/npc=23016/skyguard-handler
http://www.wowhead.com/npc=22987/skyguard-nether-ray

**Comment by Saben65** [comment]
The Skyguard Nether Ray is directly in front of the Handler on live and the handler has like 3x more WPs than the nether ray which I think means he is the follower. Here is his WP data. You would just need to add both to `creature_formations`.

```SQL
-- Pathing for  Entry: 22987 'TDB FORMAT' 
SET @NPC := 79010;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=-3376.641,`position_y`=3642.897,`position_z`=285.1084 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-3376.641,3642.897,285.1084,0,0,0,0,100,0), -- 00:15:15
(@PATH,2,-3372.496,3645.907,284.7475,0,0,0,0,100,0), -- 00:15:16
(@PATH,3,-3376.866,3642.62,285.2078,0,0,0,0,100,0), -- 00:15:22
(@PATH,4,-3381.402,3626.403,279.4974,0,0,0,0,100,0), -- 00:15:26
(@PATH,5,-3382.558,3624.162,278.2544,0,0,0,0,100,0), -- 00:15:31
(@PATH,6,-3385.898,3620.779,276.7867,0,0,0,0,100,0), -- 00:15:33
(@PATH,7,-3389.558,3619.429,276.3516,0,0,0,0,100,0), -- 00:15:35
(@PATH,8,-3393.407,3613.085,276.4259,0,0,0,0,100,0), -- 00:15:38
(@PATH,9,-3390.018,3604.891,276.2281,0,0,0,0,100,0), -- 00:15:41
(@PATH,10,-3397.005,3597.193,277.0055,0,0,0,0,100,0), -- 00:15:44
(@PATH,11,-3393.93,3598.741,276.5433,0,0,0,0,100,0), -- 00:15:48
(@PATH,12,-3390.969,3600.254,276.3882,0,0,0,0,100,0), -- 00:15:50
(@PATH,13,-3389.908,3605.303,276.3074,0,0,0,0,100,0), -- 00:15:51
(@PATH,14,-3390.732,3618.796,276.4376,0,0,0,0,100,0), -- 00:15:55
(@PATH,15,-3384.879,3620.886,277.2273,0,0,0,0,100,0), -- 00:15:58
(@PATH,16,-3382.095,3624.67,278.3322,0,0,0,0,100,0), -- 00:16:01
(@PATH,17,-3381.752,3635.601,284.2187,0,0,0,0,100,0), -- 00:16:03
(@PATH,18,-3379.75,3638.496,285.585,0,0,0,0,100,0), -- 00:16:08
(@PATH,19,-3376.617,3642.928,285.1052,0,0,0,0,100,0), -- 00:16:12
(@PATH,20,-3372.458,3645.933,284.7447,0,0,0,0,100,0); -- 00:16:13
-- 0x1C011842401672C000002500008BC617 .go -3376.641 3642.897 285.1084
```

**Comment by velinath** [comment]
Awesome. Thanks. :+1: 

```sql
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(79010, 79012, ?, 2, 0, 0);
```
Guessing on `groupAI` because I don't really have a way of testing that on live; mobs don't go up there, and you can't get to hostile reputation with the faction as far as I can remember.

Also unsure of `dist`; eyeballing it it doesn't look very far, but can't speak to an actual proper value. Any way to pull that from the data you have?

**Comment by Saben65** [comment]
Pretty sure that is just guessed at, as there is nothing from sniffs that can be added to `creature_formations`.

**Comment by Saben65** [comment]
you also need to make an additional entry to `creature_formations` with the leader and member GUIDs being 79010 or else it won't behave properly.

**Comment by velinath** [comment]
cool, the more I know! :) Thanks. Went ahead and updated previous comment, took a shot in the dark on `dist` - I'll check it against live tomorrow and see how it looks as it's late here for me.

Appreciate all your help and info! :)

**Comment by Saben65** [comment]
So the sniffer doesn't output a SQL field for `scale` in `creature_template`. Does "OBJECT_FIELD_SCALE_X" relate to the scale from the text output?

For reference.

![Nether ray](http://i63.tinypic.com/znvri8.jpg)

Perhaps they downscaled it with the graphical updates from the following expansions? I personally don't remember them being so large, but that could be my memory failing me.

**Comment by velinath** [comment]
I never did these dudes on live, so can't speak to how they were at the time, unfortunately.

I went ahead and looked on live now, and it looks like that distance of 6 is solid.

I certainly think they look *better* when they're smaller, but no idea whether it's correct on 3.3.5a.
