### ISSUE TITLE
[3.3.5] Nedar, Lord of Rhinos...

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16198]
Branch 3.3.5, rev. 8a0bbc386982
[Quest: Nedar, Lord of Rhinos...](http://www.wowhead.com/quest=11884/nedar-lord-of-rhinos)
[Nedar](http://www.wowhead.com/npc=25801/nedar-lord-of-rhinos) has a separate spawn dismounted (incorrect) in addition to the spawn as ["Lunchbox"'](http://www.wowhead.com/npc=25968/lunchbox) rider.

**Comment by Saben65** [comment]
Suggested fix

```SQL
DELETE FROM `creature` WHERE `guid`=114867 AND `modelid`=23386;
```
