### ISSUE TITLE
[3.3.5] Professor Putricide (36678)

### ISSUE THREAD

**Issue by xjose93** [TrinityCore/TrinityCore#16207]
Bugged since rev: ce90e30a80a742640396a04a767e767c6518a0a5 (tested on branch 3.3.5).

Just we need to add again the reactstate, seems it takes as default passive reactstate so he stays like a dummy.

**Comment by Nikectory** [comment]
Same issue on rev https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab (our test core) and boss working on our live core https://github.com/TrinityCore/TrinityCore/commit/cc685ac334335d9f6a25a7c1c739a905f919328f 
He stands still until 75% of health (fight phase change) and doesn't do abilities or anything during phase 1

**Comment by ShinDarth** [comment]
Confirmed on https://github.com/TrinityCore/TrinityCore/commit/5d9370a0f755887d2fff13e4ce982bd52f00f77b

Steps to reproduce: do Rotface before, then Festergut, then the Professor Putricide will be stuck and doesn't attack.

**Comment by ShinDarth** [comment]
@xjose93 try this: https://github.com/TrinityCore/TrinityCore/pull/16208/files

tell me if my fix works for you

**Comment by DevRival** [comment]
Good job, work for me.

**Comment by ShinDarth** [comment]
Yes according to https://github.com/TrinityCore/TrinityCore/commit/ce90e30a80a742640396a04a767e767c6518a0a5

**Comment by Demonid** [comment]
@ShinDarth Check Blood Council on Heroic too, after https://github.com/TrinityCore/TrinityCore/commit/ce90e30a80a742640396a04a767e767c6518a0a5 if you wipe Shadow Prison doesn't cast anymore.

**Comment by ShinDarth** [comment]
@Demonid please open a separate issue for that

**Comment by Keader** [comment]
why still open?

**Comment by ShinDarth** [comment]
Fixed: https://github.com/TrinityCore/TrinityCore/commit/b1a89943a2158415f5b3874728aaecef2e79b1b2
