### ISSUE TITLE
Dragonmaw Peons AI issues

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16210]
Rev: 53f768bd2a
TDB: TDB 335.60

[Dragonmaw Peons](http://www.wowhead.com/npc=22252/dragonmaw-peon) will aggro, but not attack. I solved that issue by adding "DoMeleeAttackIfReady();" to the script; however, they do not reset properly. The will follow you indefinitely, and if you try to drop aggro with an ability or by enabling GM, they will stay put and do start their mining emote without running back to their spawn point.

Here is my pull request https://github.com/TrinityCore/TrinityCore/pull/16204. Any help with the resetting issue is appreciated. I tried comparing to other CreatureAI scripts and couldn't find anything that stood out, but I am not very good with C++.

**Comment by NorthStrider** [comment]
try to take a loot at the UpdateAI(uint32 diff) part of the AI script.
is there the check if (!UpdateVictim()) return; ?
if so is there a override for EnterEvadeMode() ?
