### ISSUE TITLE
[6.x] Class Specific Training Glitch

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16217]
So this particular glitch could be linked to a few other tickets opened (#14825, #14853, etc.) that are associated with the start zones for both Alliance and Horde factions. All classes that I have rolled, have had quests involving Training Dummies outside their initial camps that are designed to train their special skills usually given around Level 3. The quests can be picked up from whoever gives them, but they cannot be completed because for whatever reason or another, the Training Dummy seems to not register the effects of the spell/attack - thereby rendering it null. If there is a fix for it, please direct me in the direction I need to go from this point. Otherwise we can leave this open for future attention.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by BahDumbBugs** [comment]
*MAYBE* #16139 as well? Could it be related to the fact that the Training Dummy can't die?

**Comment by Rushor** [comment]
general issue, combined with https://github.com/TrinityCore/TrinityCore/issues/14825
