### ISSUE TITLE
[3.3.5] Core/Pet: Hunter's Pet actionbars doesn't save data

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16211]
After relog/dismount the hunter's pet action bars data will reset

How to reproduce:
1. Tame a pet ( for example - entry: 19350 )
2. in your spell book pet's spell will appear so you could change spell to automatic cast or self cast ( by right click on them ) make pet's spell self cast
3. Mount up then dismount, the spell goes as same as first time it was

Revision: 94e4bddb903d581293b5a7f50f9b32d1262d2c20

**Comment by jackpoz** [comment]
and retail behavior is that the automatic/manual cast selection is persisted ?

**Comment by Rushor** [comment]
the change in the spellbook will be saved and the automatic cast will not be readded from itself yes

**Comment by Rushor** [comment]
to clarify this: 
all settings (autocast/ no autocast) which are made for the pet in the spellbook will NOT be saved after the resummon of the pet.

**Comment by tkrokli** [comment]
Maybe related to #5551 ( [Pet - UI] "Attack" continues to flash after combat end ) ?

**Comment by Eronox** [comment]
it's saved, but not initalized.

``if (m_charmInfo->RemoveSpellFromActionBar(spell_id)) && !learn_prev && clear_ab ``

should be 

`` if (clear_ab && !learn_prev && m_charmInfo->RemoveSpellFromActionBar(spell_id))`` 

in pet.cpp
short circuit evaluation of boolean expressions can be decieving, especially if a expression is a function call itself, therefor the order would matter in this case

**Comment by tkrokli** [comment]
Sounds interesting. Have you done any code change tests yourself, or is this just on a theory stage at the moment?

**Comment by Eronox** [comment]
it's tested & verified

**Comment by Keader** [comment]
Try again @Eronox  xd
Make a PR with a clean branch :)
