### ISSUE TITLE
[3.3.5/Spells] Warrior Whirlwind behaves strangely with Recklessness

### ISSUE THREAD

**Issue by lordwind68** [TrinityCore/TrinityCore#16216]
build: 3.3.5a
rev: [f377a58](https://github.com/TrinityCore/TrinityCore/commit/f377a5875cc320934573f5980cd99388ca45f7d3)

Whirlwind and Cleave Consume 2 charges of [Recklessness](http://wotlk.openwow.com/spell=1719) (not sure if that is a bug in its own or intended) but the aura on the player only decrements by 1 charge. If you strike multiple enemies with whirlwind, it consumes all 3 charges of recklessness without any indication that it has done so. 

This appears to happen with any ability which can hit more than one target.

**Comment by ccrs** [comment]
duplicate

**Comment by lordwind68** [comment]
Apologies, didn't see it at first.

**Comment by Keader** [comment]
Look #15529
