### ISSUE TITLE
Windroc Matriarch SAI Fix

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16215]
Rev: 53f768b 
TDB: TDB 335.60

Currently [Windroc Matriach](http://www.wowhead.com/npc=19055/windroc-matriarch) does an emote that says "Emote blabla" in the chat box when summoned. Additionally, she will not start attacking the player, allowing the player to kill her without taking any damage. I updated the emote to be the correct one based on [this video](https://www.youtube.com/watch?v=PLWHG9onVl8) and switched the action from "ACTION_AUTO_ATTACK" to "ACTION_ATTACK_START" which seems to have fixed the attacking issue.

The event was originally scripted here #3031 and committed here 37ce4afe.

Suggested Fix
```SQL
UPDATE `creature_text` SET `text`='Windroc Matriarch lets loose a terrifying shriek.', `BroadcastTextId`=16149 WHERE `entry`=19055;
UPDATE `smart_scripts` SET `action_type`=49, `action_param1`=0 WHERE `entryorguid`=1905500 AND `id`=3;
```

**Comment by velinath** [comment]
broadcast text id 16149, I think, if you wanted to add that to `creature_text` too

**Comment by Saben65** [comment]
Thanks, updated original query.
