### ISSUE TITLE
[3.3.5] Vanish 

### ISSUE THREAD

**Issue by Re3os** [TrinityCore/TrinityCore#16225]
What steps will reproduce the problem?
1.Enemy cast blind
2.Player cast vanish at the same time
3.Blind miss but...

What is the expected output? What do you see instead?
Stealth appear => Stealth should break.
How it's work https://www.youtube.com/watch?v=RiUjHMEZIS4
time 3.43 

Branch 3.3.5
Rev. https://github.com/TrinityCore/TrinityCore/commit/e138e094a937139aef7a2f265fff2f64b17ffa7f

**Comment by Goatform** [comment]
Actually no, if I remember good that on retail I was literally able to "eat" spells such as Fear, Death Coil,  Blind etc using Vanish or Shadowmeld.

**Comment by Rushor** [comment]
so closing
