### ISSUE TITLE
[3.3.5a] Death's grip 

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16228]
I noticed that when I'm in bg , or duel , despite not having problems of latency Death 's Grip needs much time to bring my opponent in front of me , so if I make movements my target is brought to its previous position which I casted the Death's Grip.
Rarely it works properly .
Sometimes I click the icon of the Death's grip but the spell does not hit the opponent and then hits him after two seconds or more .
Not a problem of latency , because I can safely cast other spells

https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by Keader** [comment]
Dup? #11531 #15632
