### ISSUE TITLE
[3.3.5][6.x][ICC] Core/Spell: Blood Council Heroic - Shadow Prison

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#16226]
Shadow Prison doesn't proc after a wipe.

Reproduce:

1- Start fight with Blood Council on any Heroic mode.
2- Wait until Shadow Prison is casted and move if you want to test the spell is working.
3- Wipe
4- Start the fight again, now you wont need to worry about Shadow Prison anymore.

Tested on rev 4191bb868a33288a18079494aff6b52df19dc5b4

Happens since: ce90e30a80a742640396a04a767e767c6518a0a5

@Golrag

**Comment by sirikfoll** [comment]
Do not think is fault of ce90e30a80a742640396a04a767e767c6518a0a5
This happens long before this commit, they bug Shadow Prison and sometimes the non_selectable flag does not get removed. Easy way to reproduce is to aggro and let them evade right away, use something like vanish or .gm on

**Comment by Demonid** [comment]
There are a lot of issues related to Shadow Prison, but each one it's different.

The one im reporting started happening since that commit.

The one you are telling is about the evade system, which there is a hackfix if you look on the TC issues.

There is another one that is related to interrumping spells with taunt or similar change targets mechanics, but then again there is already a hackfix for that one.

This one is totally new, if for example, you do the steps i added above over and over without https://github.com/TrinityCore/TrinityCore/commit/ce90e30a80a742640396a04a767e767c6518a0a5 it is going to work all the time.

**Comment by Killyana** [comment]
Cannot reproduce on rev. fa3eb754cbe1

**Comment by Keader** [comment]
Just for references, fixed in https://github.com/TrinityCore/TrinityCore/commit/64f6f2a0ae7294857d5ebd1ec6034476e94656e6 xD
