### ISSUE TITLE
[6.x] DB/Creature: Ironforge Gryphon Riders Hovering

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16220]
In Ironforge - the Gryphon Rider guardians are just hovering off the ground without their mounts. Almost levitating. Have not tried aggro-ing them but will try it and report back.

TrinityCore rev. 4695e23 2015-12-09 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Saben65** [comment]
Try this.

```SQL
DELETE FROM `creature_template_addon` WHERE `entry`=51383;
INSERT INTO creature_template_addon (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(51383, 0, 24688, 50331648, 257, 0, ''); -- 51383
```
