### ISSUE TITLE
Talon King Ikiss rewarding achievement he shouldn't

### ISSUE THREAD

**Issue by Kensaki** [TrinityCore/TrinityCore#16235]
Talon King Ikiss in Sethekk Halls is rewarding "Terokkar Turkey Time" (ID 3582)
"Defeat Talon King Ikiss while wearing a Pilgrim's Hat and either a Pilgrim's Dress, Robe, or Attire."
you get the achievement despite having none of the pilgrims clothes.

tested on rev b1d0855624d1

**Comment by sirikfoll** [comment]
```sql
DELETE FROM `achievement_criteria_data` WHERE `criteria_id`=11142;
INSERT INTO `achievement_criteria_data` (`criteria_id`, `type`, `value1`, `value2`) VALUES
(11142, 5, 66303, 0),
(11142, 16, 404, 0);

**Comment by tkrokli** [comment]
Quick and nice fix, @sirikfoll ! :) Looks like `criteria_id` 11142 has no criteria data in TDB 335.60.

**Comment by dr-j** [comment]
Confirm this works not because I tested this but have been using identical for past two years, I cant remember where I found this either but I found from somewhere else too

**Comment by sirikfoll** [comment]
i found it somewhere here, triyng to remember where, to give credit

**Comment by tkrokli** [comment]
Do you know if this issue requires conditions as well to be solved? (just a thought)

**Comment by dr-j** [comment]
it does not need conditions the criteria is the conditions there was no criteria thats why was free ach.

the first line is to say must have aura from pilgrims costume, the second pilgrims bounty must be running.

**Comment by Kensaki** [comment]
pilgrims bounty world event does not need to be running to get this achievement.

**Comment by dr-j** [comment]
well thats what the second line of that criteria is for

**Comment by dr-j** [comment]
and cant find any info to confirm wether this is the case or not

**Comment by Kensaki** [comment]
on retail it did not need to be during Pilgrim's Bounty. Just as BB King did not need Winter Veil to complete.

**Comment by dr-j** [comment]
then if thats the case it only needs

~~~sql
DELETE FROM `achievement_criteria_data` WHERE `criteria_id`=11142;
INSERT INTO `achievement_criteria_data` (`criteria_id`, `type`, `value1`, `value2`) VALUES
(11142, 5, 66303, 0);
