### ISSUE TITLE
[3.3.5] Glyph of Remove Curse

### ISSUE THREAD

**Issue by DevRival** [TrinityCore/TrinityCore#16234]
Core [8ef9ea9](https://github.com/TrinityCore/TrinityCore/commit/8ef9ea9157ca6c04194888a2118be7daf303856f)
TDB 335.60

http://db.uawow.com/?item=42753

Provides a respite before the fall of rates, that is the curse that is thrown at the player during the action of the buff, begins to act anyway, albeit with a reduced time. And it should give immunity.

**Comment by tkrokli** [comment]
http://wotlk.openwow.com/item=42753 (for us English readers)
Use: Your Remove Curse spell also makes the target immune to all curses for 4 sec.
=> http://wotlk.openwow.com/spell=56601 (same description as above)

Note: in 6.x, these IDs have been rearranged with Glyph of Icy Veins / Glyph of Blast Wave (removed).

**Comment by DevRival** [comment]
Sorry for my English and link. It would be nice if there was a section for the Russians) the point is that this buff does not give immunity.

**Comment by tkrokli** [comment]
It's OK. I try to help if I can. It was in no way meant as criticism, just trying to supply extra info.

**Comment by DevRival** [comment]
My fail, glyph work))

**Comment by tkrokli** [comment]
OK, fair enough. Thanks for following up and closing. :)
