### ISSUE TITLE
[3.3.5][6.x][Ulduar] Core/Vehicle - Loot issue

### ISSUE THREAD

**Issue by danqu** [TrinityCore/TrinityCore#16233]
Ulduar to use the vehicle to kill BOSS, Players cannot pick up items!

Branch 3.3.5
Rev. e138e09

**Comment by tkrokli** [comment]
Isn't this the same kind of issue as [**{NPC} Salvaged Demolisher**](3831) #3831 ? (read the details)
Please check the other 6 open issues for similar issues to see if this issue is covered already:
https://github.com/TrinityCore/TrinityCore/search?q=Ulduar+vehicle&state=open&type=Issues&utf8=✓

**Comment by Keader** [comment]
I think it's different issue @tkrokli 
According to him, can not get loot the Flame Leviathan to kill him with the vehicle

**Comment by danqu** [comment]
@Keader Yes, this is a new problem, can not get loot the Flame Leviathan to kill him with the vehicle

**Comment by tkrokli** [comment]
@Keader : OK, fair enough. You know these issues better than me, so that's at least helpful.

**Comment by NorthStrider** [comment]
Seems to be a permission issue. The core should get a additional check if the creature is a vehicle and see if the vehicle's passenger is a player to get the proper reference.

**Comment by Rushor** [comment]
@danqu: for the future: 
always use a propper description for issues. "XXX BUG" sound not very great.

**Comment by ariel-** [comment]
This bug still valid?

**Comment by Aokromes** [comment]
No answer after near 2 months, closing, if this bug is still valid open a new ticket.

**Comment by Viste** [comment]
no if kill Flame Leviathan in last rev all is ok with loot and other.
