### ISSUE TITLE
[3.3.5][Rogue] Core/Spell: Savage Combat

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16242]
Savage Combat - http://wotlk.openwow.com/spell=58683

Core [8ef9ea9](https://github.com/TrinityCore/TrinityCore/commit/8ef9ea9157ca6c04194888a2118be7daf303856f)
TDB 355.60

Issue: The following poisons are not applying the debuff:

Mind-numbing Poison
Deadly poison
Crippling Poison
(The rest of the poisons are working just fine).

How it should work: Every single creature, once poisoned, should get a debuff called "Savage Combat" that increases physical damage taken by 4%.

**Comment by Rushor** [comment]
proccflags are:
12 Successful negative spell cast
16 Successful damage from harmful magic spell cast

so 
Mind-numbing Poison
Deadly poison
Crippling Poison

does not seem to be spells which there flags

**Comment by DevRival** [comment]
I do not understand.

**Comment by Rushor** [comment]
these spells Mind-numbing Poison, Deadly poison, Crippling Poison does not seem to apply the debuff, because the buff will not procc with the flags:
12 Successful negative spell cast
16 Successful damage from harmful magic spell cast

on these spells

**Comment by DevRival** [comment]
But the problem is that there is no debuff when a poison.

**Comment by DeActiver** [comment]
confirm not applying the debuff on the targets . b31eca151d423bb270faaa77f6e56cb08332f2cf
Savage Combat buff : Increases physical damage taken by 4%.

**Comment by DeActiver** [comment]
Like man :-1:
