### ISSUE TITLE
[3.3.5][6.x][LFG] Core/Dungeon Finder - Positions in group (interface)

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#16244]
rev: https://github.com/TrinityCore/TrinityCore/commit/4191bb868a33288a18079494aff6b52df19dc5b4

http://us.battle.net/wow/en/game/patch-notes/3-3-3
Patch 3.3.3
Parties randomly created via the Dungeon Finder will always be arranged in the party interface from top to bottom in the following order: tank, healer, damage, damage, damage.

Issue:
The group is NOT listed like this. it's random

How it should be:
1) tank
2) healer
3) dd
4) dd
5) dd

see:
![GitHub Logo](http://i.imgur.com/HklhEk6.jpg)

mainissue is https://github.com/TrinityCore/TrinityCore/issues/14331. I added this to fix the issue manually. if you want to close this issue pls add the information to https://github.com/TrinityCore/TrinityCore/issues/14331

**Comment by Aokromes** [comment]
http://i.imgur.com/j6hSebT.png cannot confirm as for mop.

**Comment by Rushor** [comment]
hm, then the patchnodes are a simply a lie? :D

**Comment by Aokromes** [comment]
Maybe it's party leader, tank, healer, dps, i still have to confirm, but queue into DF on ptr is a PITA.

**Comment by Rushor** [comment]
kay i will try to queue as healer with groupleadflag soon

**Comment by Rushor** [comment]
hm yeah seem to be like that 
https://youtu.be/S44gk6g8hAU?t=2

here it's leader, tank, rest

**Comment by dmpaul26** [comment]
The way it is currently in TC leader is always first, so I assume based on these patch notes that didn't change, but the new order (tank, heal, dps) was added on top of that, with leader taking precedence.
