### ISSUE TITLE
[3.3.5] The Air Stands Still quest

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#16249]
My users report that they can't complete this quest. They can kill Salranax the Flesh Render slain but the other 2 can be killed but the quest objectives didn't update. So you can actually kill Underking Talonox slain and High Priest Yath'amon slain but nothing happens, quest didn't update.

http://www.wowhead.com/quest=13125/the-air-stands-still

DB: 335.60
Rev: 54424aff3051

**Comment by Aokromes** [comment]
Update your core before reporting bugs, this quest was fixed 25d ago.

**Comment by ikir83** [comment]
OK thanks, sorry didn't had time! :)

**Comment by tkrokli** [comment]
Rule no. 1 : When you post to TrinityCore, you make time to check and update first.

**Comment by Treeston** [comment]
This is actually still an issue on current for me.

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/commit/375593761167ba1bf8ef16bbe345cb569ad1e00b
