### ISSUE TITLE
[3.3.5][Warrior][Talent] Rampage Stacking - Auras

### ISSUE THREAD

**Issue by EnteringCombat** [TrinityCore/TrinityCore#1626]
Once you have more than one warrior specced as Fury in your raid, you could get 2 rampage auras on yourself.
This problem is reproduced with the following steps:
1.Have 2 warriors in the same group/raid group specced as Fury.
2. One of the warriors changes spec, then goes back to Fury.
3. The warrior which respecced has 2 rampage auras.

Note: 3 warriors can cause all 3 warriors to have 2 rampage auras, granting extra 5% crit.
Note another thing: other things stack (they might've been discussed too) in a different way, say Elemental Oath and moonkin aura, Horn of Winter with Strength of Earth Totem, Leader of the Pack stacking which is being handled in a different ticket right now.

This bug generally adds an additional 5% crit to one warrior (if you have 2 fury warrs), or adds 5% crit chance to all warriors (if you have 3 or more Fury warrs in your raid).

**Comment by Runico** [comment]
Still persist

**Comment by tkrokli** [comment]
@Runico : it looks like this issue page is bugged, the issue is flagged as **Closed**
even though @Trisjdc seems to have reopened it in https://github.com/TrinityCore/TrinityCore/issues/1626#event-136706016.
You may want to open a new issue and document the existence of the bug there.

**Comment by Killyana** [comment]
Try
``` sql
DELETE FROM `spell_group_stack_rules` WHERE `group_id`=1024;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`)  VALUES (1024, 1);

**Comment by tkrokli** [comment]
Leader of the Pack (open) issue: **[3.3.5][Talent] Improved Leader of the Pack** #12830

**Comment by Runico** [comment]
@Killyana it stacks with leader of the pack too, so they can hold 15% critical instead of 5%

**Comment by Runico** [comment]
@Killyana, it doesn't works

**Comment by Jenkyins** [comment]
confirmed on  b1d0855

**Comment by Mack36** [comment]
A temp & hacky [solution](https://gist.github.com/Mack36/ae5a09f2ae3beccb746d)

**Comment by MetaBarj0** [comment]
Could we accept this fix-hack? 5 years bug is a lot...

**Comment by tkrokli** [comment]
It is labeled "hack" for a reason, mainly because it introduces new problems or does not fully solve the issue. So no, it will not be accepted as such in the source. Anyway, PRs are welcome if anyone will write a proper solution.

**Comment by ariel-** [comment]
Doesn't fix stacking with Leader of the Pack. I've already researched this problem, but having trouble finding a generic solution that doesn't break something else.
