### ISSUE TITLE
DB/Quest: Nether Gas In a Fel Fire Engine

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#16269]
This quest http://www.wowhead.com/quest=10850/nether-gas-in-a-fel-fire-engine which is required in order to complete http://www.wowhead.com/quest=10855/fel-reavers-no-thanks as was fixed in https://github.com/TrinityCore/TrinityCore/commit/01beba21b5210860ddd6a37471c6b2bea77a369e.

However with this previous fix upon returning http://www.wowhead.com/quest=10850/nether-gas-in-a-fel-fire-engine, http://www.wowhead.com/quest=10855/fel-reavers-no-thanks  you see objective complete and quest is marked as completed in log and shown as complete on map, however upon reaching quest ender has grey ? above head still and continue button greyed out when trying to return quest.

This quest has specialflags 2 which means needs to be completed by external event and this should be fulfilled by the spell '38758 - [PH] Quest reward: Nether Gas In a Fel Fire Engine' which is serverside spell and is used as a reward spell for http://www.wowhead.com/quest=10850/nether-gas-in-a-fel-fire-engine.

This issues seems to be solvable by adding a invoker cast of this spell to the script or 

~~~sql
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 22293);
DELETE FROM `smart_scripts` WHERE (source_type = 9 AND entryorguid = 2229300);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(22293, 0, 0, 0, 20, 0, 100, 0, 10850, 0, 0, 0, 80, 2229300, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - On Quest complete - Action list'),
(2229300, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list - Say text'),
(2229300, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 83, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list  - Remove npc flag'),
(2229300, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 89, 7, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list - Random Move'),
(2229300, 9, 3, 0, 0, 0, 100, 0, 6000, 6000, 0, 0, 33, 22293, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list - Give Credit'),
(2229300, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 85, 38758, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list - Invoker Cast [PH] Quest reward: Nether Gas In a Fel Fire Engine'),
(2229300, 9, 5, 0, 0, 0, 100, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Inactive Fel Reaver - Action list - Kill Itself');
~~~

For some reason this spell does not work correctly when used a a quest reward spell but does if cast on self manually or using a invoker cast in script.

**Comment by tkrokli** [comment]
Interesting, yet maybe not surprising. Precious little info to find about that spell on the web, though.

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6d10b920718fdbaf526254d74d906733edcb561d
