### ISSUE TITLE
[6.x] DB/Quest (Alliance) - Riverpaw Gnoll Bounty

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16273]
Quest is here: http://www.wowhead.com/quest=11/riverpaw-gnoll-bounty

The Gnoll mobs that drop the Painted Gnoll Armbands http://www.wowhead.com/item=782/painted-gnoll-armband only drop up to 5 of them when the quest requires 8. In other words, they stop dropping them after you collect 5. When you try to turn in at the quest giver Deputy Rainer, he acts like you have the required 8, but when you try to choose your reward and complete the quest, the error "The item was not found." appears. I will test on other Alliance toons and report findings here. 

TrinityCore rev. e1d2d60ec394 2016-01-14 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by Naddley** [comment]
ef0ba42 - cant reproduce it anymore. Quest now works fine.
