### ISSUE TITLE
[6.x] Quest (Alliance) - Hero's Call: Westfall

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16271]
Quest is here: http://www.wowhead.com/quest=28562/heros-call-westfall

On arriving at the turn in location by Jansen Stead, the "?" is visible on the minimap but NPC Lieutenant Horatio Laine is not where the "?" is, or anyplace else.

TrinityCore rev. e1d2d60ec394 2016-01-14 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by tkrokli** [comment]
Likely a common 6.x issue because of very few post-cataclysm NPC spawns in TDB 6.03.
This issue may be solved when the 6.x spawns are added at a later time.

**Comment by BahDumbBugs** [comment]
Allrighty. @tkrokli thanks! I was just surprised since this is the first glitch in the Human race that Ive found so far.

**Comment by Saben65** [comment]
Try this and see if anything else is broken. He should offer the follow on quest [Murder Was the Case They Gave Me.](http://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me).

Set the XXXX to an available GUID.
```SQL
SET @CGUID := XXXX;

INSERT INTO creature (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
('@CGUID', 42308, 0, 0, 0, 1, 1, 0, 0, 0, -9849.856, 914.9618, 30.27025, 3.979351, 120, 0, 0, 0, 0, 0, 0, 0, 0, 20886); -- 42308 (Area: 0) (Auras: 79488 - 79488)
```

**Comment by Killyana** [comment]
No just nothing is scripted there, including phasing an invisibility are spells: id: 79488 [Apply Quest Invis Zone 0] effmask: 3 charges: 0 stack: 1 slot 0

**Comment by tkrokli** [comment]
TrinityCore rev. 1b1478b 2016-06-30 17:20:13 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including 2016_06_28_01_world.sql

Confirmed, still not fixed.
Can not turn in the quests [[Furlbrow's Deed](http://www.wowhead.com/quest=184/furlbrows-deed)] and [[Hero's Call: Westfall!](http://www.wowhead.com/quest=26378/heros-call-westfall)] without `.gm on`.

**Comment by nubqt** [comment]
@Killyana: why was this ticket closed? I was able to fix the issue on a duplicate ticket: https://github.com/TrinityCore/TrinityCore/issues/18519
