### ISSUE TITLE
(3.3.5) Error C2582 in VS after Appling Treeston's Fix

### ISSUE THREAD

**Issue by CDAGaming** [TrinityCore/TrinityCore#16275]
After Applying Commit  27864ab43a2f03b5010e877ffa5b8281d9e5bba

It fixes Some of my Previos errors but Introduces 25 New Ones Like:

Error	23	error C2582: 'operator =' function is unavailable in 'BossBoundaryEntry' (E:\Trinity\Source\src\server\scripts\Northrend\IcecrownCitadel\instance_icecrown_citadel.cpp)

Please Help,
CDA

**Comment by Aokromes** [comment]
be sure you rerun cmake.

**Comment by CDAGaming** [comment]
I had edited the files myself. I have No Idea what is wrong since it didn't give these errors before I put the code in

**Comment by CDAGaming** [comment]
Well, Im an Idiot
I was in a Rush(School Exams) and Forgot to add this Line:

  ~BossBoundaryEntry() { delete boundary; }

Just added it and Ill re compile Wish Me Luck

**Comment by CDAGaming** [comment]
No Errors on CMake :)

Now for VS 2013...
