### ISSUE TITLE
(3.3.5) Error's in VS 2013 Express when Compiling TrinityCore

### ISSUE THREAD

**Issue by CDAGaming** [TrinityCore/TrinityCore#16283]
Hello Staff,

I've just Pulled All Recent Commit's from 4 days Ago and I Got an Error Saying "AreaBoundary Multiple Default Contstructs"

I had Fixed that Error with A Pull Request from @treeston which is 2083b4b1a4e4dd4fa6e670deb24b1380f1b07468

That Fixed it but introduced 2 New Errors:

Error 19 error LNK1181: cannot open input file '..\scripts\Release\scripts.lib' E:\Trinity\Build\Build7\src\server\worldserver\LINK worldserver

and

Error 17 error C2582: 'operator =' function is unavailable in 'BossBoundaryEntry' (E:\Trinity\Source_3.3.5_Work\src\server\scripts\Northrend\IcecrownCitadel\instance_icecrown_citadel.cpp) C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\utility 53 1 scripts

These Errors are in Visual Studio 2013 Express on a Windows 10 x64 Pro. On CMake I had Gotten no Errors & I have Tried this on a Fresh Source & My Normal One.

Both Replicated the Same Error & Wouldn't let me Compile successfully.

If there is Anyone who can Help me resolve this issue, I'd Greatly Appreciate it

Thanks,
TeamCDA

**Comment by tkrokli** [comment]
This is not a forum. I have recently compiled 6e624f2 on 2 different computers with VS2013 Update 5.
No errors, just those warnings that will be dealt with as soon as the PR to fix it is thoroughly checked.

**Comment by CDAGaming** [comment]
I've tried to Reach you on the Forum and No One has Replied

I also hadnt gotten Update 5 so that may be it

**Comment by tkrokli** [comment]
Possible. Try that and see if it works. If not, contact me directly via IRC. Default, straight source works.

**Comment by Vincent-Michael** [comment]
![Pic](http://i.imgur.com/TEJgeKb.png) on vs2013 is fine for me

**Comment by CDAGaming** [comment]
Ok, I'd always thought warnings affected the build. I had also Implemented his Code in my Source but if it gives errors then i'll try the Normal Source

**Comment by jackpoz** [comment]
Your issue would have been solved much sooner if you spent the required time to write a proper detailed issue report. We would have seen they were warning and filled the gap in your development knowledge that warnings are not errors.

**Comment by CDAGaming** [comment]
@jackpoz Well Once I Put in @Treeston Commit Then I got Errors

**Comment by tkrokli** [comment]
IRC = Internet Relay Chat. https://trinitycore.atlassian.net/wiki/display/tc/IRC

**Comment by CDAGaming** [comment]
I finally Got it Working, It's Just without Treeston's Fix, which is ok with me

Thanks for Helping me:)
