### ISSUE TITLE
(6.2.3.20886) After Updating, It Keeps Saying "Connecting" and Can't Connect to Realms

### ISSUE THREAD

**Issue by CDAGaming** [TrinityCore/TrinityCore#16289]
Hi Again,

After Updating my Core to d2d41c119b99e5a7734f30418c0cd724467b6f89 & My Client to 6.2.3.20886 When I try to Log on It says Bad Realm in the WorldServer.exe

I'm Gonna try and RE-Compile but If anyone has Suggestion,I'm open to them.

**Comment by Vincent-Michael** [comment]
re-patch your client

**Comment by CDAGaming** [comment]
@Vincent-Michael I'm Currently Re-Compiling & Then I'll Re-Patch my Client and see if it fixes it

**Comment by CDAGaming** [comment]
Is there any SQL Tables in My Realmlist i should change. 2/3 Realms are Red in WoW Realm Select

**Comment by MitchesD** [comment]
Issue tracker isn't for question like this, use our wiki to get needed informations or use Forum for questions.

**Comment by CDAGaming** [comment]
No-Body Ever Answers the Forums when I'm On it @MitchesD . This is the Only Place where You Guys seem to respond

**Comment by Shauren** [comment]
Fun fact: english is not a language where you capitalize every word.

**Comment by CDAGaming** [comment]
@Shauren Good point :)

**Comment by MitchesD** [comment]
No one answered? Don't lie https://community.trinitycore.org/topic/12272-335-trinitycore-compile-issues-regarding-commits-2083b4b1a4e4dd4fa6e670deb24b1380f1b07468-2da458c56d024aac04468ce2af454a83ad790bf6/

**Comment by CDAGaming** [comment]
Oops, didnt see the replies bc i haven't checked since yesterday evening
