### ISSUE TITLE
[3.3.5] Trial of The Crusader - Event Problem

### ISSUE THREAD

**Issue by Mosoo** [TrinityCore/TrinityCore#16280]
Branch : 3.3.5
Commit : 0316dff24530da83ef3466500ee8bd4e1af548ba
and yes mmaps are disabled for trial of the crusaders.

When you are enter on trial of the crusader then start the event .  gormok the impaler comes inside the ring and stay ( some times it stays behind the door )... nothing happened and he is not selectable and doesn't moving

kill him with die and the snakes are same .  Dreadscale come in and the other one does not come up from the ground so i can't test the next phases ..

before this i'm on  347373264b4ca5046af5c23378117e6ddb66504d  and everything works fine .

**Comment by Saben65** [comment]
linking these to reference what you are talking about with the disables.

https://github.com/TrinityCore/TrinityCore/issues/9053
https://github.com/TrinityCore/TrinityCore/commit/826717de1b184c0e4eb41735b56622bd85a6ba6c

**Comment by Mosoo** [comment]
@Saben65   it's already disabled in db , i'v encountered another issue with new commits .

**Comment by Saben65** [comment]
Like I said, I was just referencing what you were talking about.

**Comment by Aokromes** [comment]
Very likely bug on boundaries commit.

**Comment by Pirricli** [comment]
confirmed
0316dff24530da83ef3466500ee8bd4e1af548ba

**Comment by Pirricli** [comment]
Started with 2da458c56d024aac04468ce2af454a83ad790bf6
Tested with the previous commit and all ok.

**Comment by Re3os** [comment]
Sindragosa event don't start after die.

**Comment by Carbenium** [comment]
@Re3os: since when exactly does Sindragosa have anything to do with Trial of The Crusader?

**Comment by Re3os** [comment]
@Carbenium realy stupid?This problem is boundaries system.

**Comment by Carbenium** [comment]
@Re3os: it would be great if you could speak/write in a slightly more moderate tone. Those phrases you use aren't really appropriate for an issue tracker.
I'm not sure how many people are willing to help you with such an attitude.
Just my 2 cents...
