### ISSUE TITLE
[6.x] Worldserver Crashing After latest updates

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#16299]
After latest updates on 6.x Branch Worldserver is crashing when trying to create a new character or when trying to connect using old created characters.

I have extracted new dbc, maps , vmaps and mmaps after updating official wow client to latest version.

World Server LOG

2016-01-17_10:01:52 TrinityCore rev. 09adf4d0ad6e+ 2016-01-17 01:52:22 +0100 (6.x branch) (Win64, Release) (worldserver-daemon) ready...

**Comment by Aokromes** [comment]
Useless crashlog, compile on debug mode, put crashlog on pastebin.

**Comment by maryus101** [comment]
Doing this now

**Comment by creekers** [comment]
Hi,
same problem for me

**Comment by Aokromes** [comment]
debug mode crashlog at pastebin plz.

**Comment by creekers** [comment]
Crash log in two past http://pastebin.com/GzVLqmPT   http://pastebin.com/ZPHML3yg

**Comment by maryus101** [comment]
Crashlog and Server Log.

Cannot use pastebin because crashlog file is too big.

https://mega.nz/#!HN4X0JTJ!iz--cgsk3A4FY33eMVeVNzG1OMPLX0n_3YyI3sMvc6U

**Comment by maryus101** [comment]
UPDATE !

Map extractor detects build 20726 and game build is 20886.

This can be a problem with dbc on worldserver?
