### ISSUE TITLE
[NPC] Ashyen & Keleth Broadcast_Text Fix

### ISSUE THREAD

**Issue by Saben65** [TrinityCore/TrinityCore#16300]
Rev: e53baa7d9088
DB: TDB 335.60

The NPCs have FemaleText entries in their broadcast_text, but no MaleText which results in them saying nothing.

```SQL
SELECT * FROM `broadcast_text` WHERE `id`=8329;
```
```
    ID  Language  MaleText  FemaleText                                               EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild  
------  --------  --------  -------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  ---------------
  8329         0            Thank you for helping me. I know my way back from here.         0         0         0            0            0            0        0       0       1            18019
```

Suggested Fix: (Unsure if I should use " " or ' ').
```SQL
UPDATE `broadcast_text` SET `MaleText`="Thank you for helping me. I know my way back from here." WHERE `id`=8329;
```

**Comment by tkrokli** [comment]
Both kinds of text delimiters are valid. When single quotation mark (apostrophe) is used within names or in contractions like "Don't" or "isn't", it is practical to use double quotation marks around the lines to avoid the need for escaping the single quote with backslash ( \' ) or using double apostrophe ( '').
Otherwise, single quote or apostrophe looks slightly cleaner.

**Comment by Aokromes** [comment]
IIrc changing broadcast_text is a no-no-no.

**Comment by tkrokli** [comment]
Hmm. Unless the gender can be changed on those NPCs, we will be stuck with no words from them.

**Comment by Killyana** [comment]
I cannot find any text or npc or quest or any thing related to this.

**Comment by tkrokli** [comment]
TDB 335.60 / Rev. 6d10b920718f
Seems I was a bit hasty and didn't check the details completely. `broadcast_text`.`ID` 8329 belongs to NPC 11856, Kaya Flathoof. That is why there is only FemaleText, because the NPC is a femaie tauren.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/zone_stonetalon_mountains.cpp#L106
```sql
SELECT * FROM `broadcast_text` WHERE `ID` IN (8327,8328,8329);
```
```
    ID  Language  MaleText  FemaleText                                               EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
------  --------  --------  -------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  ---------------
  8327         0            Let's go before they find out I'm free!                         0         0         0            0            0            0        0       0       1          18019
  8328         0            Look out! We're under attack!                                   0         0         0            0            0            0        0       0       1          18019
  8329         0            Thank you for helping me. I know my way back from here.         0         0         0            0            0            0        0       0       1          18019
```
http://www.wowhead.com/npc=11856/kaya-flathoof#comments

About those entries in `creature_text`: they are strange and random (as well as incorrect):
```
 entry  groupid      id  text                                                       type  language  probability   emote  duration   sound  BroadcastTextId  TextRange  comment
------  -------  ------  -------------------------------------------------------  ------  --------  -----------  ------  --------  ------  ---------------  ---------  ---------------------------------------
 17900        0       0  Thank you for helping me. I know my way back from here.      12         0          100       0         0       0             8329          0  ashyen and keleth GOSSIP_REWARD_BLESS
 17901        0       0  Thank you for helping me. I know my way back from here.      12         0          100       0         0       0             8329          0  ashyen and keleth GOSSIP_REWARD_BLESS
```

**Comment by Saben65** [comment]
That is what I originally assumed based on the response it was giving to buff you. Therefore, the correct thing to do would be to remove the creature_text completely, and delete the part of the script that does GOSSIP_REWARD_BLESS, like I originally did, correct, @Killyana?

I am really quite certain now these creatures never said anything on reward bless (and they currently do not on retail as well), and these entries were just trivial mistakes.

**Comment by Killyana** [comment]
Your commit is correct, just add a sql file to remove the creature_text.
https://www.youtube.com/watch?v=mV5knSKtwpc
