### ISSUE TITLE
[3.3.5][6.x] DB/Quest - Wrangle some Aether Rays! doesn't count for completion.

### ISSUE THREAD

**Issue by Thurin93** [TrinityCore/TrinityCore#16305]
rev. https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f
the quest: http://wowwiki.wikia.com/wiki/Quest:Wrangle_Some_Aether_Rays!
The player needs to get a nether ray to low HP and use the quest item on them to "wrangle" them, thus despawning the Aether Ray and spawning a Wrangled Aether Ray, those Aether Rays are tied to the player via a rope and need to be dragged back to the quest giver. 

Problem: when you get back to the npc Skyguard Khatie, the objective doesn't appear as complete, doing the quest uncompletable.

**Comment by dr-j** [comment]
On retail you dont actually need to take back to quest giver although quest giver will say a line if you do take back to quest giver but this is just cosmetic as you dont actually have to do as you receive credit when you wrangle them and they dont follow you for long as they disappear after a few mins regardless of wether you took to quest giver or not but can still return quest.

**Comment by dr-j** [comment]
but confirmed credit no longer works, also animation of ropes to aether rays once wangled is missing.

**Comment by dr-j** [comment]
well the below sorts the missing rope visuals npc needs to cast at player not invoker cast on player

~~~sql
UPDATE `world3`.`smart_scripts` SET `action_type`=11, `comment`='Wrangled Aether Ray - On Just Summoned - Cast \'Wrangle Aether Rays: Wrangling Rope Channel\' (No Repeat)' WHERE  `entryorguid`=23343 AND `source_type`=0 AND `id`=0 AND `link`=1;

**Comment by jerbookins** [comment]
f909d4f1957b

Everything appeared to work correctly except that the Aether Rays take about 2-3 minutes to despawn after you complete the quest. Persists through logout.

**Comment by dr-j** [comment]
on retail these do not despawn instantly they follow you on leash for a few minutes before despawning and you can have multiple following you if you take them back to the quest giver quest giver will say line saying thank and despawn but you dont actually have to take them back as part of quest but if you do the quest giver will thank you.
