### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Steamtank Surprise (12326)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16307]
Branch 3.3.5, rev. 8a0bbc386982

[Quest: Steamtank Surprise](http://www.wowhead.com/quest=12326/steamtank-surprise)
No credit is awarded for destroying Plague Wagons. Dropping off the 7th Legion Elite works fine.

**Comment by Killyana** [comment]
Works for me.
