### ISSUE TITLE
[3.3.5][6.x] DB/Creature: Very few spawns in Wintergarde Mine

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16306]
Branch 3.3.5, rev. 8a0bbc386982

[Risen Wintergarde Miner](www.wowhead.com/npc=27401/risen-wintergarde-miner) and [Risen Wintergarde Defender](http://www.wowhead.com/npc=27284/risen-wintergarde-defender) in the Wintergarde Mine have very few spawn points, making [Quest: Not In Our Mine](http://www.wowhead.com/quest=12269/not-in-our-mine) very annoying to complete.

**Comment by Kittnz** [comment]
ill sniff and spawn

**Comment by Kittnz** [comment]
Risen Wintergarde Miner still needs SAI

**Comment by Killyana** [comment]
SAI for what?

**Comment by Kittnz** [comment]
they should mine and there are some mine nodes there too, i am not really sure what exactly i needed but they should have mine animation atleast

**Comment by tkrokli** [comment]
You mean something like emote 233 `STATE_WORK_MINING` or emote 467 `ONESHOT_WORK_MINING`?

**Comment by Treeston** [comment]
The unmoving ones should have that I assume.

**Comment by Aokromes** [comment]
Only visuals missing now.
