### ISSUE TITLE
[6.x] DB/Quest - Horde, Durotar : Never Trust a Big Barb and a Smile

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16311]
Quest is here: http://www.wowhead.com/quest=25165/never-trust-a-big-barb-and-a-smile

Issue is that you can set the totem for venom extraction, but it never actually pulls any venom for collection, thereby hindering progress toward quest completion. This is in by Sen'jin Village near Troll start zone.

TrinityCore rev. e1d2d60ec394 2016-01-14 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by tkrokli** [comment]
Have you checked if you need to trigger the envenom cast from the scorpids? (compared to what some players have written in the comment section on wowhead)

**Comment by BahDumbBugs** [comment]
Yeah Ive done that. That was the first thing I checked to make sure I was placing the totem at the correct moment. :)  Ive drawn the Scorpid to about < 50% health and triggered Envenom cast. Same result. I was able to duplicate it on 3 low level and 2 high level toons.

**Comment by BahDumbBugs** [comment]
Have you been able to duplicate the issue, or were you able to successfully draw the venom?

**Comment by tkrokli** [comment]
Been a while since I tested this quest. I think I only tested it on live servers half a year ago or more.

**Comment by KarrokDC** [comment]
Can confirm, doesn't work in TrinityCore rev. 6c48066a6f24 2016-01-11 18:33:20 +0100 (6.x branch)

**Comment by Crosha** [comment]
DELETE FROM smart_scripts WHERE entryorguid = 3125;
INSERT INTO smart_scripts (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) 
values
('3125','0','0','0','0','0','100','0','4000','4500','32000','38000','11','79687','0','0','0','0','0','2','0','0','0','0','0','0','0','Clattering Scorpid - In Combat - Cast \'Poison\' (No Repeat)'),
('3125','0','1','0','0','0','100','0','2000','9000','15000','24000','11','73672','0','0','0','0','0','2','0','0','0','0','0','0','0','Cast Envenom'),
('3125','0','2','0','31','0','100','0','73672','0','0','0','33','39236','0','0','0','0','0','2','0','0','0','0','0','0','0','Give Credit on Totem Aura'); -- Scorpion SmartScript

DELETE FROM conditions WHERE Sourceentry = 3125 AND SourceTypeOrReferenceId = 22;
INSERT INTO conditions (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) 
values
('22','3','3125','0','0','1','0','73673','1','0','0','0','0','','SAI - Give kill credit when Aura'); -- Condition to give Credit

**Comment by Flameshot** [comment]
The only problem on @Crosha smartscript is that when the mob cast Envenom and you have the quest active it should appear a text".

**Comment by tkrokli** [comment]
If you know what that text should be, please open a new issue with the necessary information about it, while referring to this issue (please use the embedded template to fill in all the info needed for a new issue).
