### ISSUE TITLE
[6.x] DB/Misc: Remove ammo

### ISSUE THREAD

**Issue by msoky** [TrinityCore/TrinityCore#16313]
https://github.com/TrinityCore/TrinityCore/commit/80ffb62c488545392d57dfac8434073cd41b0b2b
This arrows and bullets removed from cataclysm
only for 4.3.4 and 6.x

``` SQL
DELETE FROM `npc_vendor` WHERE `item` IN (2512,2515,3030,3464,9399,11285,19316,18042,12654,28053,24417,28056,30611,31949,33803,34581,31737,30319,41165,41586,52021,2516,8067,4960,2519,8068,5568,3033,8069,3465,10512,11284,10513,19317,15997,11630,13377,28060,23772,28061,30612,32883,32882,23773,34582,31735,41164,41584,52020);
DELETE FROM `creature_loot_template` WHERE `Item` IN (2512,2515,3030,3464,9399,11285,19316,18042,12654,28053,24417,28056,30611,31949,33803,34581,31737,30319,41165,41586,52021,2516,8067,4960,2519,8068,5568,3033,8069,3465,10512,11284,10513,19317,15997,11630,13377,28060,23772,28061,30612,32883,32882,23773,34582,31735,41164,41584,52020);
DELETE FROM `gameobject_loot_template` WHERE `Item` IN (2512,2515,3030,3464,9399,11285,19316,18042,12654,28053,24417,28056,30611,31949,33803,34581,31737,30319,41165,41586,52021,2516,8067,4960,2519,8068,5568,3033,8069,3465,10512,11284,10513,19317,15997,11630,13377,28060,23772,28061,30612,32883,32882,23773,34582,31735,41164,41584,52020);

**Comment by msoky** [comment]
can you merge this please?

**Comment by Rushor** [comment]
you mean commit?

**Comment by msoky** [comment]
yes please, there is 850 uselles entries with ammo, but from CATA every vendor doesnt sell ammo

**Comment by msoky** [comment]
when this will be merged?

**Comment by tkrokli** [comment]
Whenever a TC team collaborator deems it important enough, I suppose.

**Comment by msoky** [comment]
okay, if a TC team collaborator doesnt seems that this isnt important thing...then I can close it, right?

**Comment by tkrokli** [comment]
No, it is better that you leave it open, especially because it is labeled [Feedback-Patchfix].

**Comment by msoky** [comment]
I think that this https://github.com/TrinityCore/TrinityCore/issues/16498  is more important, but this remove-ammo-fix delete cca 850 entries, so this is usefull too
