### ISSUE TITLE
boss_mimiron

### ISSUE THREAD

**Issue by danqu** [TrinityCore/TrinityCore#16317]
Mimiron BOSS fighting is not perfect, there is no air combat,
Mimiron BOSS will drill underground to fight
Ask for help, Mimiron Fix

rev. 3e42d83

**Comment by ccrs** [comment]
... to say the least, duplicated

**Comment by danqu** [comment]
BOSS Mimiron third phase of the fight is not correct, not in the air attack players

**Comment by Kittnz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15177
