### ISSUE TITLE
[6.x] Can't Log Into WoW 6.2.3.20886

### ISSUE THREAD

**Issue by CDAGaming** [TrinityCore/TrinityCore#16316]
Hi,

I'm Running TrinityCore & I'm getting some errors in worldserver.exe when trying to login into the newest build in wow:

WorldSocket::HandleAuthSession: Sent Auth Response (bad realm)
 and IN-Game it says:

This Log On Server is Offline Visit (Battle.net Website Here)

This Issue has Occurred since the release of Commit d2d41c119b99e5a7734f30418c0cd724467b6f89

My DB is completely Up-to-Date and I have VS 2015 Community Update 1 & CMake 3.4.1
Both have No Issues

Edit: My Realmlist Table GameBuild is 20,726 but in BattleNet Components 20,886 is Seen in it's normal sections

Edit 2: If I edit 3 Lines in battlenet_Components from 20886 to 20779 It will Work on 20779 again but Not 20886

**Comment by CDAGaming** [comment]
Hello,Anyone Online?

**Comment by Shauren** [comment]
It looks like you have not configured RealmID properly

**Comment by CDAGaming** [comment]
@Shauren I've not edited my Realms at all except to apply your commits

**Comment by msoky** [comment]
have you this commit? https://github.com/TrinityCore/TrinityCore/commit/dfceb3dd19d9bf65c4c692714c45ee4cbe6240aa

**Comment by CDAGaming** [comment]
I have All Recent Commits ,Up to a few hours ago, including dfceb3d

**Comment by CDAGaming** [comment]
I could include some screenshots of the errors if that would help too

**Comment by CDAGaming** [comment]
Here are some Screenshots of this:

http://imgur.com/a/ic9ml

PS it's in an album, that's why it's one link

**Comment by Vincent-Michael** [comment]
@CDAGaming 

check both ids ...

![Pic1](http://i.imgur.com/QkuyQd4.png) == ![Pic2](http://i.imgur.com/w4msawe.png)

**Comment by CDAGaming** [comment]
@Vincent-Michael Both of these Rows are Correct, 6.2.3 was able to login before i applied d2d41c1 then it gave me the errors in 1st post

**Comment by CDAGaming** [comment]
Anything else I can try???

**Comment by tkrokli** [comment]
Shouldn't `auth`.`realmlist`.`gamebuild` be the exact same number as the game client, a.k.a. 20886 ?
Your imgur image says that you should be using client version 20726 ...

**Comment by DDuarte** [comment]
> Shouldn't auth.realmlist.gamebuild be the exact same number as the game client, a.k.a. 20886 ?

No. That's fine, it should be the base build.

**Comment by CDAGaming** [comment]
@DDuarte That's Correct My Base Table is 20726. It just doesnt let me connect for some reason. CMake and VS 2015 didnt give any errors when i compiled and My Server is working on 3.3.5. Any Suggestions

**Comment by tkrokli** [comment]
It can be very challenging to set up a multi-realm server, especially if you want to have both authserver and bnetserver running, as well as mixed 6.x auth with 3.3.5 auth database. Have you tried running 6.x separately, in its own folder and with a separate 6.x MySQL server database setup?

**Comment by CDAGaming** [comment]
Yes, 6.x and 3.3.5 are completly seperated from each other and I turn each server on at seperate days and times. My DB are using the same PC but are still Seperated from each other as a feared breaking something if i combined both.

**Comment by CDAGaming** [comment]
Any Way to Fix this???

**Comment by CDAGaming** [comment]
I really need help on this issue if anyone has any more suggestions. Even after Commiting and repatching it, It still shows the error.

**Comment by CDAGaming** [comment]
@msoky Oh, I didn't see your BTW Note until now

**Comment by CDAGaming** [comment]
Edit: @msoky TheFlags are already 0  but no luck

Any suggestions???

**Comment by CDAGaming** [comment]
@Shauren @Treeston @Vincent-Michael @tkrokli If there is anything I can do to fix this, Please leave suggestions (Edit has been made to original post).

**Comment by Daniel25** [comment]
Delete the battlenet folder in C://programs ,I had a similar issue. Maybe that helps.

**Comment by msoky** [comment]
delete/clean everything and do it from first step...this still works :)

**Comment by tkrokli** [comment]
For some of the login errors in the 6.2.3 game client, it is necessary to first have logged in to Blizzard's servers at least once (on a trial or normal account) and then use the connection_patcher, change the game client settings to use localhost / 127.0.0.1 as the target server to log in to. That is often the way to solve or avoid login issues for the 6.x branch. If the issue returns, you might need to log in to the Blizzard servers again, then set it back to the localhost server or own server on a different IP address. Just make sure you follow the suggested steps exactly as recommended in the TC wiki guide. If you find that the wiki guide does not describe some necessary detail, please comment on that and we will see if it needs to be changed to be sure that the guide is correct. It seems to work for most other people, though.

**Comment by Shauren** [comment]
How many times do i need to repeat this - it is NO LONGER NEEDED to connect to retail servers first anymore - patcher is now able to download modules itself

**Comment by tkrokli** [comment]
OK, sorry about that outdated info. I should not meddle with the 6.x branch without proper knowledge.

**Comment by CDAGaming** [comment]
Ok, I did get my Client from BNet so I'll try removing The BattleNet Foler and see if that helpes

**Comment by CDAGaming** [comment]
@msoky What do you mean "clean everything"

**Comment by tkrokli** [comment]
I think he means clean source, clean Build folder and clean DB. Just so you are sure there is no trash.

**Comment by CDAGaming** [comment]
I'd tried a COMPLETLY clean source, build, and DB before but No Luck. Arn't you all running build 20886 too

**Comment by CDAGaming** [comment]
Also Both Methods do Not word,sadly

**Comment by CDAGaming** [comment]
Also If I change the BNet 20886 Areas to 20779, It Works..But Not on 20886 Just for 20779 and Below.
Hope this helps...

**Comment by Shauren** [comment]
then its your own goddamn fault for not running the patcher again after updating from 20779 - the patched binary does not magically autoupdate when you update the original

**Comment by CDAGaming** [comment]
Well then it's also you're god damn fault that you didn't read that I'd already patched my client multiple time on 20886 & 20779

**Comment by Shauren** [comment]
You definitely are doing something wrong - it works for everyone else.
In my eyes this cannot be qualified as bug belonging here, on issue tracker but as support request on the forum.

**Comment by CDAGaming** [comment]
SendAuthResponseError(REALM_LIST_REALM_NOT_FOUND);
        TC_LOG_ERROR("network", "WorldSocket::HandleAuthSession: Sent Auth Response (bad realm).");
        DelayedCloseSocket();
        return;

This is a Line from 1 of Your Webpages, It's the exact error but What I'm gonna try is to:

*Use a VM and Re-Create a Fresh Server from Scratch
