### ISSUE TITLE
[3.3.5][6.x] Core/Mechanic: Quest command ( .Quest Complete | RequiredPlayerKills )

### ISSUE THREAD

**Issue by NixAJ** [TrinityCore/TrinityCore#16321]
Branch 3.3.5, rev: https://github.com/TrinityCore/TrinityCore/commit/ac64e8fbb0629e06288baaf936157887ffbd9a19

How to reproduce:
1. Accept the quests (13233 http://www.wowhead.com/quest=13233/no-mercy) from (http://www.wowhead.com/npc=30344/high-captain-justin-bartlett 30344)
2. Target yourself and use the command .quest complete 13233

What happens?, whats supposed to happen?
When you use .quest complete it's supposed to show the quest as completed in your log, however instead it shows 0/15 Players Slain.

Note: It still marks the quest as completed ( but does not update the objectives for the clients log )

Using:
Branch & Rev is at the top
DB: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.60

Extra Info:
This only seems to be the case when RequirePlayerKills > 0.

**Comment by kjanko** [comment]
Implementation for player related objectives is missing. I will write a patch tomorrow if nobody beats me to it.

**Comment by Rushor** [comment]
@kjanko: any luck so far with the pr?
