### ISSUE TITLE
[3.3.5] Core/Crash: AchievementMgr::SaveToDB (this=0x7fffaf9345c0, trans=std::shared_ptr (count 1, weak 0) 0x7fffa67ac460) at /home/Source/src/server/game/Achievements/AchievementMgr.cpp:520 520	            if (!iter->second.changed)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16325]
http://paste.ubuntu.com/14575740/
Rev: 8ef9ea9157ca6c04194888a2118be7daf303856f

**Comment by Voidx** [comment]
same problem here.

**Comment by ariel-** [comment]
```        __ts = /build/gdb-2hEJVN/gdb-7.7.1+dfsg/gdb/regcache.c:178: internal-error: register_size: Assertion `regnum >= 0 && regnum < (gdbarch_num_regs (gdbarch) + gdbarch_num_pseudo_regs (gdbarch))' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.```

Problem with debugger caused crash?

**Comment by Aokromes** [comment]
No answer after near 1 year. closing, if this bug is still valid open a new ticket on one updated core.
