### ISSUE TITLE
[3.3.5] DB erorrs

### ISSUE THREAD

**Issue by DevRival** [TrinityCore/TrinityCore#16323]
Core (https://github.com/TrinityCore/TrinityCore/commit/cdf7ac60965fb280461fc1db24ee4784c7336142)
TDB 355.60

Errors with the latest updates.
```
Table `creature` has creature (GUID: 134869 Entry: 27401) with `MovementType`=0 (idle) have `spawndist`<>0, set to 0.
Creature (GUID: 97255) does not exist but has a record in `creature_addon`
Creature (GUID: 97256) does not exist but has a record in `creature_addon`
Creature (GUID: 97257) does not exist but has a record in `creature_addon`
Creature (GUID: 97258) does not exist but has a record in `creature_addon`
Creature (GUID: 97259) does not exist but has a record in `creature_addon`
Creature (GUID: 97261) does not exist but has a record in `creature_addon`
Creature (GUID: 131106) does not exist but has a record in `creature_addon`
```

**Comment by tkrokli** [comment]
Suggested solution:

```sql
-- remove recent startup errors in 3.3.5:
UPDATE `creature` SET `spawndist`= 0 WHERE `guid`= 134869 AND `id`= 27401;
DELETE FROM `creature_addon` WHERE `guid` IN (97255,97256,97257,97258,97259,97261,131106);
```

**Comment by Kittnz** [comment]
No, just set movementype 1 for 134869

**Comment by tkrokli** [comment]
Updated with `MovementType`= 1 `Random movement inside the spawndist radius` instead of spawndist.

**Comment by fvicaria** [comment]
I don't want to open a new issue just in case this is my fault but I have tried in a clean core with clean db and I get the same.

```
Table `vehicle_template_accessory`: creature template entry 31432 has no data in npc_spellclick_spells
```

Can anyone point me to the right direction?

**Comment by tkrokli** [comment]
http://www.wowhead.com/npc=31432/ghostwing#comments
http://wow.gamepedia.com/Ghostwing (Level 80 frost wyrm, The Fleshwerks, Icecrown)
http://wow.gamepedia.com/Quest:Killing_Two_Scourge_With_One_Skeleton
http://www.wowhead.com/quest=13144/killing-two-scourge-with-one-skeleton
http://www.wowhead.com/quest=13212/hes-gone-to-pieces

Not sure, maybe this has got something to do with the mob grabbing NPC 30708, Crusader Olakin?
http://www.wowhead.com/npc=30708/crusader-olakin-sainrith

**Comment by Killyana** [comment]
We don't have a spawn for 31432 or any event that spawn it, so I don't know how you got this error.

**Comment by fvicaria** [comment]
It appear after this:

```

DELETE FROM `vehicle_template_accessory` WHERE `entry`=31432;
INSERT INTO `vehicle_template_accessory` (`entry`, `accessory_entry`, `seat_id`, `minion`, `description`, `summontype`, `summontimer`) VALUES
(31432, 31428, 0, 0, '31432 - 31428', 6, 30000); -- 31432 - 31428

``

Found on: sql\updates\world\2016_02_13_03_world.sql

**Comment by tkrokli** [comment]
OK, that would be commit https://github.com/TrinityCore/TrinityCore/commit/fb895cc99bffa668715b02b41fdf78038b2f0dfa [**DB/Misc: The Fleshwerks (Phasing)**](https://github.com/TrinityCore/TrinityCore/commit/fb895cc99bffa668715b02b41fdf78038b2f0dfa) from @dr-j 
He should know what the intention is behind that SQL query.
```sql
DELETE FROM `vehicle_template_accessory` WHERE `entry`=31432;
INSERT INTO `vehicle_template_accessory` (`entry`, `accessory_entry`, `seat_id`, `minion`, `description`, `summontype`, `summontimer`) VALUES
(31432, 31428, 0, 0, '31432 - 31428', 6, 30000); -- 31432 - 31428
```
I can now also see that it is indeed intended for the Ghostwing event with Olakin pulled off:
http://www.wowhead.com/npc=31432/ghostwing
http://www.wowhead.com/npc=31428/crusader-olakin-sainrith

**Comment by dr-j** [comment]
dont have any spellclick in sql data for this, Crusader Olakin Sainrith may need spawning but believe this should be spawned via that vehicle_template entry

(@CGUID+824, 31428, 571, 1, 64, 6648.76, 3217.726, 810.5007, 1.605703, 120, 5, 1), -- 31428 (Area: 4588) (possible waypoints or random movement)

The only other thing I have in sql data relevant to this is texts

(30631, x, x, 'Damn it, Olakin, get your arse back here! There''s work to be done!', 12, 0, 100, 5, 0, 0, 0, 'Darkrider Arly to Crusader Olakin Sainrith'),
(31428, x, x, 'Look! What''s a frostwyrm doing here? It''s coming straight for us.', 12, 0, 100, 25, 0, 0, 0, 'Crusader Olakin Sainrith to Player'),
(31432, x, x, 'Destroy our raw materials, will you? Well, the master has a special plan in mind for you... ', 12, 0, 100, 460, 0, 0, 0, 'Ghostwing to Player'),

No spellclick spell for either of those npcs and have checked whole parsed sniff data too no spellcasts at all either cast by or hitting iehter 31428 or 31432

**Comment by Killyana** [comment]
``` sql
ServerToClient: SMSG_SPELL_GO (0x0A53) Length: 52 ConnIdx: 0 Time: 11/29/2011 11:04:11.000 Number: 254722
Caster GUID: Full: 0xF1307AC40090578C Type: Creature Entry: 31428 Low: 9459596
Caster Unit GUID: Full: 0xF1307AC40090578C Type: Creature Entry: 31428 Low: 9459596
Cast Count: 0
Spell ID: 59091 (59091)
Cast Flags: Unknown7 (256)
Time: 4006094461
Hit Count: 2
[0] Hit GUID: Full: 0xF1507AC80090578D Type: Vehicle Entry: 31432 Low: 9459597
[1] Hit GUID: Full: 0xF1307AC40090578C Type: Creature Entry: 31428 Low: 9459596
Miss Count: 0
Target Flags: Unit (2)
Target GUID: 0x0

**Comment by fvicaria** [comment]
That fixes it.

**Comment by tkrokli** [comment]
OK, so maybe this:
```sql
--
-- Ghostwing needs spell 59091 in relation to Crusader Olakin Sainrith in phase 64
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`= 31432 AND `spell_id`= 59091;
INSERT INTO `npc_spellclick_spells` (`npc_entry`,`spell_id`,`cast_flags`,`user_type`) VALUES
(31432,59091,256,0);
```
(is this the change you have tested, @fvicaria ?)

**Comment by dr-j** [comment]
Killyana do you have any wp for the event as even though have the texts for some reason have no movement packets in sniff for this either as well as spells I dont even remember personally seeing it but have got the spawn and texts in sniff but nothing else other then the vehicle accessory but a few parsing errors around by where it is in parsed sniff.

**Comment by Killyana** [comment]
I have this from SMSG_ON_MONSTER_MOVE
``` sql
Position: X: 6588.427 Y: 3278.203 Z: 818.2033  -- spawn position
Waypoints: 1
Waypoint Endpoint: X: 6644.43 Y: 3222.912 Z: 823.0705 -- 1st move for the event
Waypoints: 1
Waypoint Endpoint: X: 6690.65 Y: 3177.279 Z: 860.5705 -- second move, despawn once reached
