### ISSUE TITLE
[3.3.5] Core/Crash: The Exorcism of Colonel Jules

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#16337]
http://paste.ubuntu.com/14588805/
Rev: 8ef9ea9157ca6c04194888a2118be7daf303856f

**Comment by streetrat** [comment]
bool StaticMapTree::getObjectHitPos(const Vector3& pPos1, const Vector3& pPos2, Vector3& pResultHitPos, float pModifyDist) const
.
.
.
float maxDist = (pPos2 - pPos1).magnitude();
// valid map coords should *never ever* produce float overflow, but this would produce NaNs too
ASSERT(maxDist < std::numeric_limits<float>::max());   <<<< booom

**Comment by jackpoz** [comment]
>pos = {m_positionX = -710.331909, m_positionY = 2754.3938, m_positionZ = -1.05482541e+26, m_orientation = 4.96478033}

this looks like a valid local variable

**Comment by Shauren** [comment]
but not like a valid height - client hack?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14664 triggered an assert about Z being invalid too (can't find the crash report atm) , are Creature coords validated too anytime they get changed ?

**Comment by Shauren** [comment]
From movement and creature creation yes - see Unit::UpdatePosition
no if someone hacks around stuff and calls Relocate himself

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/478cc756eb05591f36857be3ffd1895684529710/src/server/game/Grids/GridDefines.h#L230
```
inline bool IsValidMapCoord(float x, float y, float z)
{
	return IsValidMapCoord(x, y) && std::isfinite(z);
}
```
no particular checks are done on z parameter except being a valid float number and -1.05482541e+26 is still a valid float number. This means that the check
```
bool Unit::UpdatePosition(float x, float y, float z, float orientation, bool teleport)
{
    // prevent crash when a bad coord is sent by the client
    if (!Trinity::IsValidMapCoord(x, y, z, orientation))
    {
        TC_LOG_DEBUG("entities.unit", "Unit::UpdatePosition(%f, %f, %f) .. bad coordinates!", x, y, z);
        return false;
    }
```
will not prevent a very high/low z to be assigned.

**Comment by Aokromes** [comment]
I remember few months ago i tried to see how much i can fall on eoe and i reached 6 digits depth.

**Comment by jackpoz** [comment]
>Sep 22 2015 21:43:34 <jackpoz>	Aokromes: that crashlog has everything you need to reproduce it, mapId=530, x1=-710.331787, y1=2754.39331, z1=-3.21109816e+26, x2=-690.814453, y2=2758.76074, z2=94.4093781

The coordinates of the crashlog of September triggered by https://github.com/TrinityCore/TrinityCore/pull/14664 are the same as this crash so it's that usual broken PR

**Comment by xjose93** [comment]
http://pastebin.com/pvXnTihg

Rev: 1d9d03b289

**Comment by jackpoz** [comment]
>triggerSpellId = 39280

**Comment by Shauren** [comment]
>m_objectTargetGUID = {_guid = 17379391338370701283}, 0xf1300057a0161800
NPC entry with invalid position: http://www.wowhead.com/npc=22432/colonel-jules

**Comment by Aokromes** [comment]
#15370
