### ISSUE TITLE
[3.3.5][Paladin] Core/Spells: Swift Retribution and Sanctified Retribution only work in Retribution Aura

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#16331]
The talent should increase the melee speed in all auras, however only increases in Retribution.
However the form of reproduce is slightly strange:
- If you dont have any aura on login and active any of auras, talent work. :+1: 
- If you have any aura on login and active any of auras, talent work. :+1: 
- If you put retribution aura  and switch for any another aura, talent stop work and only active by putting the retribution :-1:  only returning to activate to other auras after relog.

@joschiwald can you take a look?! Maybe related : f57f784c67e8102f7add9b046d1fbedb850a21d8

TC hash: ac727ab208e592c7a2d01ebe321944402860c3ae

PS: Patch 3.1.0 (14-Apr-2009): Now affects all auras instead of only affecting Retribution Aura. (http://wowwiki.wikia.com/wiki/Swift_Retribution)

Edit:
Same problem for Sanctified Retribution spell.

**Comment by Keader** [comment]
Sanctified Retribution has the same problem.
same repro steps.

**Comment by mik1893** [comment]
that commit #f57f784 broke it
