### ISSUE TITLE
DB/Quest: Entombed in Ice - Dun Morogh  (Alliance)

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#16339]
Quest here: http://www.wowhead.com/quest=25978/entombed-in-ice

The Mountaineers that are trapped should be in a block of ice. There is no block thus not allowing quest to be completed.

TrinityCore rev. e1d2d60ec394 2016-01-14 01:33:37 +0100 (6.x branch) (Unix, Release)

**Comment by tkrokli** [comment]
The icy tombs seem to be passive NPCs : http://www.wowhead.com/npc=41768/icy-tomb
Maybe this could be another spawn issue? Not sure if there is any scripting on this one.

**Comment by offl** [comment]
Maybe they fall under map, according to other Github issues related to this quest.
Try with this:
```sql
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry`=41768;
```

**Comment by ArcaneFox** [comment]
I think it's already fixed:

![wowscrnshot_121717_173327](https://user-images.githubusercontent.com/25306170/34081671-0466cfd4-e351-11e7-93c9-406ac5e95d61.jpg)

**Comment by offl** [comment]
7f5604c1a0e8f4356bcd7e53f10704093ff6fe03
