### ISSUE TITLE
[3.3.5a] Sindragosa

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16333]
Sindragosa hits with http://www.wowhead.com/spell=71077/tail-smash
even players who are beside her legs, this should not happen because the spell is only effective if it is behind her.

-also the graves do not share the disease of the DK 
https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by Rushor** [comment]
dup from https://github.com/TrinityCore/TrinityCore/issues/12235
