### ISSUE TITLE
[3.3.5a] Arthas

### ISSUE THREAD

**Issue by declart** [TrinityCore/TrinityCore#16332]
The Lich King has several bugs:
-the first, in the middle-phase, the spell http://www.wowhead.com/spell=68981/remorseless-winter#comments affects pet and kills them (in theory it should not happen but I have to investigate).
- The second phase, the boss does not cast the spell that summons the http://www.wowhead.com/spell=69037/summon-valkyr valkirye and makes this step very simple.
- Third phase, when cast this spell http://www.wowhead.com/spell=70498/vile-spirits#comments the Vile Spirits should wait 15 seconds before being active, but this does not happen it is ALSO aggro from pets, something that must not happen.
- Third phase, does not bring all the players in this room called "frostmourne" https://www.youtube.com/watch?v=HKDLXauhy7E (in the first minute shows what should happen)

https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by Keader** [comment]
"The second phase, the boss does not cast the spell that summons the valkyr"
-Here work normally.
But remember that the Val'kyr not take tankers (so you have to have more than one character in the test)

Third phase, does not bring all the players in this room called "frostmourne"

- I Cant reproduce that too, working fine for me

"the first, in the middle-phase, the spell http://www.wowhead.com/spell=68981/remorseless-winter#comments affects pet and kills them (in theory it should not happen but I have to investigate)."

-I cant find any confirmation about this

**Comment by Demonid** [comment]
@Keader He is talking about 25H, on 25H Valkyr not spawn on TC Default source.

**Comment by Rushor** [comment]
dup from https://github.com/TrinityCore/TrinityCore/issues/15048

only report one issue / ticket

**Comment by declart** [comment]
im talking about 25h and 25n.
@Keader in our server " frostmourne " doesnt work, arthas call it but doesn't trasfer all player in frostmourne.
for the remorseless the pets must be taken less damage from spell AoE

**Comment by Keader** [comment]
ON Clean TC, all players is summoned from frostmourne. (ON 25 HEROIC)
About Valkyr, look this: https://github.com/TrinityCore/TrinityCore/issues/15048#issuecomment-173343720
Try opening a ticket/issue for each problem
