### ISSUE TITLE
[3.3.5][6.x][Core/Spell] Vile Spirit Explosion Damage

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#16349]
Explosion suppose to do between 14K and 16K damage
but in fight it will do more than 20K

SpellId: 73576
ICC 10 Normal
Rev: 8ef9ea9157ca6c04194888a2118be7daf303856f

**Comment by sirikfoll** [comment]
Seems invalid,
73576 is difficulty 0 of the spell used inside frostmourne, as it only exists in heroic mode, the damage is as follow
Heroic 10: 73804 -> BasePoints = 18850 to 21151
Heroic 25: 73805 -> BasePoints = 23563 to 26438

**Comment by Runico** [comment]
@sirikfoll So, what's the correct one ? 73803 ?

**Comment by tkrokli** [comment]
http://wotlk.openwow.com/spell=73803 : 14138 - 15862 Shadow damage to all enemies within 10 yards.
http://wotlk.openwow.com/spell=73804 : 18850 - 21150 Shadow damage to all enemies within 10 yards.
http://wotlk.openwow.com/spell=73805 : 23563 - 26437 Shadow damage to all enemies within 10 yards.
***
http://www.wowhead.com/spell=73576/explosion (valid information for patch 6.2.3 ??)
Difficulty: 10 Player Heroic (Legacy) : Deals 16965 to 19035 Shadow damage
Difficulty: 25 Player Heroic (Legacy) : Deals 21206 to 23794 Shadow damage

School Damage (Shadow)
Value: 12723 to 14277
Value: 16965 to 19035 - 10 Player Heroic (Legacy)
Value: 21206 to 23794 - 25 Player Heroic (Legacy)
Radius: 10 yards

**Comment by Rushor** [comment]
> @sirikfoll So, what's the correct one ? 73803 ?

yes (and btw always check the damage values in spell_dbc and never trust on the current values from wowhead)

**Comment by Runico** [comment]
@Rushor 73803 still do more damage than what is says on it's tooltip.

Why Close ? issue still persist

**Comment by Rushor** [comment]
so u are telling us, that spell=73576 (10 man normal) deals more than 14138 - 15862 damage?

can you proof this with an ingame screenshot?

it's a bad idea to create thousands of issues without any detailed information/ combatlogs/ proofs from wowhead-wowwiki/ links

@tkrokli is the only one who try to clean up this mess in tc

**Comment by Runico** [comment]
Rushor, Okay, I'll prove screenshot

**Comment by Runico** [comment]
@Rushor http://uploads.im/noX6M.jpg

**Comment by Rushor** [comment]
@Runico i cannot see instancemode and playerstats in this screen
