### ISSUE TITLE
[3.3.5][6.x] Core/Spell: Val'kyr Target Search

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#16347]
Spell ID - 69030 Val'kyr Target Search(http://wotlk.openwow.com/spell=69030)

If the target selected by this spell has aura due to Spell Hand of Protection(http://wotlk.openwow.com/spell=1022)
handler bound to hook `OnEffectHitTarget` of SpellScript will not be executed.

Consequently, the valkyr will not select another target, because the SpellScript will find and pass to her the right target guid, but nothing further will be executed due to the failure in `OnEffectHitTarget`  hook.

I only tested this with Hand of Protection, but supposedly works also with pretty much any invisibility/imunity spells.

Any doubt, please ask. Thanks.

hash cebdf03349ed
branch 3.3.5

**Comment by Keader** [comment]
Yeap, Invisibility causes same effect.

**Comment by sirikfoll** [comment]
Nothing but a workaround, this will allow the valkyr to search for another target in case of failure, instead of became useless.
```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
index 755bbd7..7845afc 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
@@ -2548,7 +2548,6 @@ class spell_the_lich_king_valkyr_target_search : public SpellScriptLoader
                 _target = Trinity::Containers::SelectRandomContainerElement(targets);
                 targets.clear();
                 targets.push_back(_target);
-                GetCaster()->GetAI()->SetGUID(_target->GetGUID());
             }
 
             void ReplaceTarget(std::list<WorldObject*>& targets)
@@ -2561,6 +2560,7 @@ class spell_the_lich_king_valkyr_target_search : public SpellScriptLoader
             void HandleScript(SpellEffIndex effIndex)
             {
                 PreventHitDefaultEffect(effIndex);
+                GetCaster()->GetAI()->SetGUID(GetHitUnit()->GetGUID());
                 GetCaster()->CastSpell(GetHitUnit(), SPELL_CHARGE, true);
             }

**Comment by Keader** [comment]
@ariel- any suggestion here? xd

**Comment by ariel-** [comment]
Try:

```c++
case 69030: // Val'kyr Target Search
    spellInfo->Attributes |= SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY;
    break;
```

In SpellMgr::LoadSpellInfoCorrections

**Comment by sirikfoll** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16347#issuecomment-273777894 works
