### ISSUE TITLE
[3.3.5] Crash on MVS 2013 "assertion failed map/set iterators incompatible..."

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#16353]
Crash on MVS 2013 assertion "failed map/set iterators incompatible..".
Rev: 3f886025a2559c4973ac260fc633ff74c2096932
[Place](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp#L171)
Please solve this problem.

**Comment by Aokromes** [comment]
You are running VS 2013 update 4? 5?

**Comment by Eliminationzx** [comment]
update 5

**Comment by tkrokli** [comment]
What is necessary to do, in order to reproduce your crash? Can you make a short list of actions?

**Comment by Eliminationzx** [comment]
Just switch on worldserver

**Comment by tkrokli** [comment]
I have made lots of 3.3.5 worldservers, almost daily or at least every 2 days. Both updates and separate branches to create my PRs. I never get a crash on 3.3.5 Release x64 build. The only things that stop worldserver from completing its startup, is when I forget to handle the SQLs properly (my bad).

**Comment by DDuarte** [comment]
Post a crashlog and re-open this issue.
