### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Cocooned! (12606)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16357]
3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

[Quest: Cocooned!](http://www.wowhead.com/quest=12606/cocooned)
Weird behavior with broken [cocoons](http://www.wowhead.com/npc=28413/nerubian-cocoon). Some cocoons contain nothing, while some contain multiple mobs (I've counted five drakkari captives spawn as one at one point).

**Comment by dr-j** [comment]
Well I was reposible for updating this in https://github.com/TrinityCore/TrinityCore/issues/11478 as was even worse before, this was working correctly when I updated it the npcs in question are spawned by spell which only executes once (random script run on death) as for empty cocoons this was present in original script so not sure if that should happen.

**Comment by dr-j** [comment]
This is the spell used to summon drakari captives http://www.wowhead.com/spell=51597/summon-scourged-captive and have tested it it does spawn between 4 and 6 mobs, same as wowhead data for this spell suggests

Effect	Summon (Drakkari Captive)
Value: 4 to 6

**Comment by LordUsagi** [comment]
From what I can see, some cocoons should be empty, some should contain drakari captives and other have the footmen. But only one gets summoned each time.

Could the 4 to 6 be a chance? 1/3?

**Comment by dr-j** [comment]
ID - 51597 Summon Scourged Captive
=================================================
Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (0,0)
Family SPELLFAMILY_GENERIC, flag 0x00000000 00000000 00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000100 (SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
AttributesEx2: 0x00000005 (SPELL_ATTR2_CAN_TARGET_DEAD, SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx4: 0x00000080 (SPELL_ATTR4_TRIGGERED)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 13) "Anywhere":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 50000, MaxRangeFriendly = 50000

CastingTime (Id 1) = 0.00
Duration: ID (3)  60000, 0, 60000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 28 (SPELL_EFFECT_SUMMON)
BasePoints = 4 to 7  Multiple = 1000.00
Targets (63, 0) (TARGET_DEST_TARGET_ANY, NO_TARGET)
EffectMiscValueA = 28414
EffectMiscValueB = 66

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT

**Comment by offl** [comment]
As you can see [here](https://www.youtube.com/watch?v=qV-GKMcShhQ)(wotlk) and [here](https://www.youtube.com/watch?v=nZHVkpwiq2E)(after wotlk) only one Drakkari Captive should be spawned by this spell.
> Just hit the cocoons and they crack open, they will either be **a Drakkari Captive** or **a Captive Footmen**. I opened about 10 or 15 cocoons and of course, 3 were captives. Easy quest over all.

--

> Some cocoons contain nothing

You also can see in these movies that this is blizzlike.

So if I understand correctly that's enough for this issue:
```diff
    ApplySpellFix({
+       51597, // Summon Scourged Captive
        56606, // Ride Jokkum
        61791  // Ride Vehicle (Yogg-Saron)
    }, [](SpellInfo* spellInfo)
    {
        /// @todo: remove this when basepoints of all Ride Vehicle auras are calculated correctly
        spellInfo->Effects[EFFECT_0].BasePoints = 1;
    });
```
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L3574

**Comment by Killyana** [comment]
Setting BasePoints = 1 will just reduce the number of summones npcs from 4 - 6 to 2 - 4

**Comment by Killyana** [comment]
Must be fixed by:  override DieSides

**Comment by Killyana** [comment]
``` diff
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 2d2d85bcff..d8622f9d8e 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3842,6 +3842,7 @@ void SpellMgr::LoadSpellInfoCorrections()
     });
 
     ApplySpellFix({
+        51597, // Summon Scourged Captive
         56606, // Ride Jokkum
         61791  // Ride Vehicle (Yogg-Saron)
     }, [](SpellInfo* spellInfo)
@@ -3849,6 +3850,12 @@ void SpellMgr::LoadSpellInfoCorrections()
         /// @todo: remove this when basepoints of all Ride Vehicle auras are calculated correctly
         spellInfo->Effects[EFFECT_0].BasePoints = 1;
     });
+    
+    // Summon Scourged Captive
+    ApplySpellFix({ 51597 }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->Effects[EFFECT_0].DieSides = 0;
+    });
 
     // Black Magic
     ApplySpellFix({ 59630 }, [](SpellInfo* spellInfo)
