### ISSUE TITLE
[3.3.5] Core/Mechanic: Druid flight form not abiding mount restrictions re: shapeshifts

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16354]
3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

Druids are capable of shifting into flight form while shapeshifted into (non-druid) forms that do not allow mounting. Example: [Drakuru chain ghoul form](http://www.wowhead.com/item=38699/ensorcelled-choker). The result is swimming zombies.

**Comment by LordUsagi** [comment]
In the case of that quest, it looks from the comments that someone could shapeshift into moonkin form, but not the other ones.
