### ISSUE TITLE
[3.3.5] Quest: Hell Hath a Fury (12674)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16366]
3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

[Quest: Hell Hath a Fury](http://www.wowhead.com/quest=12674)
Upon not-quite-death, all the High Priests should:

- Give quest credit to nearly players (this works)
- Become unattackable (this does not work for any except Tua-Tua)
- Be affected by their "punishment" and say their respective line, only once (Mu'funu is affected repeatedly and spams his like)
- Despawn after the "punishment" ends (this does not happen)

**Comment by dr-j** [comment]
Dont have any of these issues with this quest all three work and are affected by punishment  and despawn, however it is known that these npcs can become bugged due to the way grid system works with sai if player hex's these npcs and then leaves area before event script has finished executing.

**Comment by dr-j** [comment]
any script which uses a timed action list can become bugged if players leave grid while action list is running and if a npc with a timed action list dies while script is running the remainder of script will run on respawn or when grid is loaded after respawn.

**Comment by Rushor** [comment]
combined to a more general issue in https://github.com/TrinityCore/TrinityCore/issues/16455

**Comment by jerbookins** [comment]
I don't think this issue should be combined with #16455 and I disagree with @dr-j, the quest does not work correctly. The scripting for the NPCs is incorrect. A quest able to be completed does not make it a "working" quest.

The problems described in the ticket still stand without:
>leaving the grid while action list is running

or

>if player hexes these NPCs and then leaves area before event script has finished executing.

I'm not really sure how someone could bug the behavior of these NPCs by leaving the area "too soon" unless you're talking about stepping outside of the bounds of the  quest area and losing the Ghostly Aura (21671).

Quest behavior demonstrated in video https://streamable.com/vllra

**Comment by dr-j** [comment]
I may have made changes to sai for this, not sure but think likely.

Can't check atm
