### ISSUE TITLE
(4) "Call of Earth" Tauren Shaman quest in Mulgore

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16369]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

When completing the Shaman quest "Call of Earth" and receiving my Earth Totem, the yellow question mark remains above Seer Ravenfeather.  When you talk to her, she has nothing to say but her normal flavor text.

**Comment by BahDumbBugs** [comment]
I almost reported this one as well but I think I was missing some turn in or another part of the quest line with this. I'll verify this and how I fixed it soon.

**Comment by tkrokli** [comment]
This also happens to other quest givers like the class trainers in the Draenei starting area. Those i have observed seem to have a delay in removing their yellow ? above the quest giver's head after quest is done, but if I move out of sight or to a differently named area nearby, it is usually gone when I get back.
Could it be a server <=> client update issue?

**Comment by XaveT** [comment]
I suppose it could be indeed.  I'm going to close this and reference back to it in a new issue to describe the problem a bit more fully.  Also since the problem isn't with the quest, but the core.
