### ISSUE TITLE
[3.3.5] Quest: Scalps! (12659)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16361]
3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

[Quest: Scalps!](http://www.wowhead.com/quest=12659/scalps)

Quest item [Ahunae's Knife](http://www.wowhead.com/item=38731/ahunaes-knife) doesn't work on the [Heb'Drakkar Striker](http://www.wowhead.com/npc=28465/hebdrakkar-striker#comments)s in the area, only on the [Heb'Drakkar Headhunter](http://www.wowhead.com/npc=28600/hebdrakkar-headhunter)s.

Also, when a [Heb'Drakkar Striker](http://www.wowhead.com/npc=28465/hebdrakkar-striker#comments) is aggroed, he dismounts (intended) but never changes inhabittype, thus swimming through the air towards you.

**Comment by Rushor** [comment]
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=52090 AND `ElseGroup`=1;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(17, 0, 52090, 0, 1, 31, 1, 3, 28465, 0, 0, 173, 0, '', 'Item 38731 "Ahunae\'s Knife" targets 28465 "Heb\'Drakkar Striker'),
(17, 0, 52090, 0, 1, 36, 1, 0, 0, 0, 1, 173, 0, '', 'Item 38731 "Ahunae\'s Knife" targets 28465 "Heb\'Drakkar Striker');
```

**Comment by Kittnz** [comment]
"Also, when a Heb'Drakkar Striker is aggroed, he dismounts (intended) but never changes inhabittype, thus swimming through the air towards you." @ccrs any eta on that PR?
