### ISSUE TITLE
[3.3.5] Quest: I Sense a Disturbance (12665)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16364]
3.3.5 0316dff24530da83ef3466500ee8bd4e1af548ba

[Quest: I Sense a Disturbance](http://www.wowhead.com/quest=12665)

Quest is completely nonfunctional. Selecting the related gossip option does nothing. Quest cannot be completed.

**Comment by Pitcrawler** [comment]
Well, I scripted this quest years ago. You might want to take a look at the script. It can be found here https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/sql/old/3.3.5a/TDB49_to_TDB50_updates/world/2012_12_07_02_world_tracker_pitcrawler.sql

**Comment by Rushor** [comment]
combined to https://github.com/TrinityCore/TrinityCore/issues/15981
