### ISSUE TITLE
[3.3.5] Object - Defias Gunpowder - Acquisition should spawn attacker

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16374]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

The Defias Gunpowder object (# 17155) in Deadmines instance should spawn an Elite Defias Overseer (would link, but wowhead doesn't have the old version anymore, "new" NPC is http://www.wowhead.com/npc=48421/defias-overseer) with agro on the person who picked up the powder.  From retail days, you wouldn't even always get the item before the first shot would hit you.

**Comment by XaveT** [comment]
Not the right NPC.  It should spawn an Elite Defias Taskmaster instead.  NPC #4417
(to self: Read your notes when you do the write ups... SMH)

**Comment by Rushor** [comment]
```sql
-- Lake Surger SAI
SET @ENTRY := 17155;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,70,0,100,0,2,0,0,0,12,4417,3,120000,1,0,0,8,0,0,0,-123.7698,-613.586,14.126,6.035,"Lake Surger - On Gameobject State Changed - Summon Creature 'Defias Taskmaster'");
```

**Comment by XaveT** [comment]
This fix is perfect.

**Comment by XaveT** [comment]
Since this fixes my problem, what do I need to do to get it merged into the build?  (I'm new to this concept on github, but I'd like to help.  Is there a sticky somewhere I've missed?)

**Comment by Kittnz** [comment]
Someone needs to push it, @Rushor since it's your fix, can you push it?

**Comment by Rushor** [comment]
maybe tomorrow ~4 pm
