### ISSUE TITLE
GM Command - God Mode - not working correctly

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16373]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

I did a nice solo Deadmines run tonight for the quests and lore, and died with god mode turned on.  I investigated and found that special abilities are still affecting the "god mode : on" character.

Examples:
Defias Evoker in Deadmines - Fire damage still done from Flamestrike, still is chilled from Frost Armor.
Rhahk'zor in Deadmines - Rhahk'zor Slam still does damage and knocks down.
Goblin Woodcarver in Deadmines - Axe Toss and Cleave  (I pulled 6 of these and died from not being able to heal due to knockdown on Axe Throw)
Defias Taskmaster in Deadmines - Shoot

From what makes sense to me, God Mode should render the "god" invincible.  No damage, no effects from non-GMs.

**Comment by Keader** [comment]
In Icecrown Citadel before Sindragosa appear, she casts some spells frost that deals damage in GMs too

**Comment by Rushor** [comment]
well you take damage, but you will never die because of it - it just a visual thing

check the condition in unit.cpp in DealDamage() and you will see, that it always returns 0 with active god mode command

**Comment by Keader** [comment]
On Sindragosa you die xD

**Comment by Rushor** [comment]
sneaky bitchboss :o

**Comment by Nyeriah** [comment]
Sindragosa's fury doesn't pass through normal damage calculation https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp#L1082-L1098

**Comment by Rushor** [comment]
offtopic: actually i think that this spell was never used with patch 3.3.5, it was only a ptr spell

**Comment by XaveT** [comment]
I'll try it again.  It may have been a fluke that I died and had to run back.

**Comment by Aokromes** [comment]
+('cheat god',       2, 'Syntax: .cheat god [on/off]\r\nEnables or disables your character''s ability to take damage.'),
So, no, never intended "no effects"

**Comment by XaveT** [comment]
Gotcha.  I can't reproduce this after standing around being beaten on for a few minutes.  Closing.
