### ISSUE TITLE
Mob issue - Redridge Mystics in Redridge Mountains

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16370]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

For some reason, these mobs can cast while walking (I haven't seen them cast while running though).  Also, haven't observed one ever cast healing touch in this core.  I remember them doing it in retail many years ago though.

**Comment by Rushor** [comment]
can you give links of these creatures?

**Comment by Rushor** [comment]
current sai is like this this:

```sql
-- Redridge Mystic SAI
SET @ENTRY := 430;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,4,0,10,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Redridge Mystic - On Aggro - Say Line 0 (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,0,0,600,1800,11,20802,64,0,0,0,0,2,0,0,0,0,0,0,0,"Redridge Mystic - In Combat - Cast 'Lightning Bolt'"),
(@ENTRY,0,2,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Redridge Mystic - Between 0-15% Health - Flee For Assist (No Repeat)");
```

the cmc flag and healspell is already there

**Comment by XaveT** [comment]
Just out of curiosity, how much testing did you do?  I saw it twice while I was in Redridge Mountains, with maybe 40 Mystics killed.  It didn't happen often, but it _did_ happen.

**Comment by tkrokli** [comment]
Is it possible to document that NPC ability in some way, like video from retail or sniff?

**Comment by BahDumbBugs** [comment]
I was just running around Redridge Mountains, and I've killed a good number of Redridge Mystics and none of them were casting Lightening Bolt while walking or running. Redridge Bashers are in the same area, perhaps you confused a Basher with a Mystic?

I'm running TrinityCore rev. 6a471755231e 2016-1-14 01:33:37 +0100 (3.3.5 branch) (Unix, Release)

**Comment by tkrokli** [comment]
I did not intend to say whether you are correct or not, I just think it needs some kind of documentation.

**Comment by XaveT** [comment]
It's always possible.  I could have confused anything with anything else... it's all such old memories at this point that I could be missing all kinds of things.  I just write it down when something seems off from memory.  I'm at lvl 24 with my most familiar starting area and have only seem like 3 things in total, so I'm kind of in awe of this core and all its work folks have done on it.

I'm going to find my old fraps install and see if I can catch it in action.

**Comment by BahDumbBugs** [comment]
I can also run a Human newbie and check that area out. (If I can get myself to touch an Alliance faction on retail :laughing:  ) Subsequently, I will also keep an eye on it as I roll each Alliance class and see if it makes a difference.

**Comment by XaveT** [comment]
It's weird, but it reproduced for me in about 2 tries.

https://www.youtube.com/watch?v=ARVLHFqUFGE

**Comment by XaveT** [comment]
I also noticed this on Shadow Sprites (http://wotlk.openwow.com/npc=2003) in Teldrassil.  So it isn't the just the mob.  :(

**Comment by Saben65** [comment]
I noticed similar behavior here https://github.com/TrinityCore/TrinityCore/issues/16069#issuecomment-167384266 with the Shadowmoon Warlock, though that appeared to be related to him having waypoints. Does this particular Mystic have WPs?

**Comment by Killyana** [comment]
There's a general issue with npcs that continue waypoint movement once in combat.
About the cast while moving , it related to this issue as the cast_flag 64 is used for CMC.

**Comment by XaveT** [comment]
It has a patrol path, so I'm going to say yes.  It doesn't always happen like that though.  Sometimes it moves off the path and attacks, then flees, then starts casting while walking back too.  I can do a video of that as well if you need it.

**Comment by Rushor** [comment]
we will combine the issue with https://github.com/TrinityCore/TrinityCore/issues/12476
