### ISSUE TITLE
[Warlock] Fel Hunter's Spell Lock ability 

### ISSUE THREAD

**Issue by Nikectory** [TrinityCore/TrinityCore#16386]
Warlock' s pet Fel Hunter doesn't interrupt casts of enemy target
 http://wotlk.openwow.com/spell=19647
How sould work: 
spellcasting enemies interrupted by Spell Lock should not be able to launch a spell from the school of that interrupted for 6 sec and be silenced for all school for 3 sec.
How it works:
 Spell lock doesn't interrupt spell casting and only silences the target for 3 sec
Issue confirmed on rev: https://github.com/TrinityCore/TrinityCore/commit/3e42d83e9cb86695a0467726f327599ff354293f

**Comment by L30m4nc3r** [comment]
#3718

**Comment by Rushor** [comment]
duplicate
