### ISSUE TITLE
[3.3.5a][Naxxramas] Core/Movement: Unstoppable Abomination movement during the Kel'Thuzad fight

### ISSUE THREAD

**Issue by OScriptTC** [TrinityCore/TrinityCore#16388]
Rev: 0316dff24530da83ef3466500ee8bd4e1af548ba

YouTube video documenting the incident: https://www.youtube.com/watch?v=ZTQCflcYhF4&feature=youtu.be

Creature: http://wotlk.openwow.com/npc=16428

Well if you watched the YouTube video you'd see that there's a lot of weird movement going on there. For example dropping below the ground or flying above the ground.

**Comment by Rushor** [comment]
mmaps and vmaps enabled?

**Comment by tkrokli** [comment]
@Rushor : yes, he confirmed that in #trinity chat, but OK. Practical to have that info here too.

**Comment by OScriptTC** [comment]
MMAPs are enabled, but I'm getting this error in my WorldServer.exe I just noticed: Could not load MMAP name:Naxxramas, id:533, x:25, y:43 (mmap rep.: x:25, y:43)

Of course I tried extracting my mmaps again, but again it gave me this error. I think tried downloading tkroli's mmaps from his ac-web reapck, but it gave me the same error.

**Comment by tkrokli** [comment]
That mmap message is constant, you will always get console messages like that. Related: https://github.com/TrinityCore/TrinityCore/issues/14439

**Comment by OScriptTC** [comment]
So you're saying that this issue (which seems to be an mmaps issue) is not related in any way to that error message?

**Comment by tkrokli** [comment]
I can't say for sure. It has not yet been declared to be the exact reason for this kind of issue.

**Comment by Rushor** [comment]
@OScriptTC : do you also got this issue https://github.com/TrinityCore/TrinityCore/issues/12037 while testing? (not related to this issue here, but i'm just curious if it stil happens)

**Comment by Aokromes** [comment]
Test  #16634

**Comment by Treeston** [comment]
assume closed by #16634

**Comment by Treeston** [comment]
assume closed by #16634
