### ISSUE TITLE
[3.3.5a] DB/Quest: Replenishing the Healing Crystals

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16391]
TrinityCore rev. 3f88602 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

Previous ticket #11450, New one opened at @Rushor 's request.  @tkrokli has good ideas for a fix.

NPC Questgiver: Proenitus (ID 16477) on Azuremyst Island

First Quest - "Replenishing the Healing Crystals": http://wotlk.openwow.com/quest=9280
Second Quest - "Urgent Delivery!":  http://wotlk.openwow.com/quest=9409

Quest "Urgent Delivery!" should not be given before the quest "Replenishing the Healing Crystals" has been completed. The flavor text makes no sense if given at the same time.

**Comment by BahDumbBugs** [comment]
Let me know if @tkrokli 's fix worked. I can verify and confirm.

**Comment by tkrokli** [comment]
Draenei quest chain start: http://wow.gamepedia.com/Quest:You_Survived!#Quest_progression
- http://www.wowhead.com/quest=9280/replenishing-the-healing-crystals
- http://www.wowhead.com/quest=9409/urgent-delivery

Alliance other start: http://wow.gamepedia.com/Replenishing_the_Healing_Crystals#Quest_Progression
- http://www.wowhead.com/quest=9369/replenishing-the-healing-crystals
- http://www.wowhead.com/quest=9409/urgent-delivery

I haven't tested this exact issue yet, but it feels familiar. Information currently in TDB 335.60:
```sql
SELECT `ID`,`PrevQuestID`,`NextQuestID` FROM `quest_template_addon`
WHERE `ID` IN (9279,9280,9369,9371,9409);
```
```
    ID  PrevQuestID  NextQuestID
------  -----------  -----------
  9279            0            0
  9280         9279         9409
  9369            0         9409
  9371            0            0
  9409         9371            0
```
Looking at this info, I would think that having quest 9409 (Urgent Delivery!) in `NextQuestID` to both of the quests above would make it necessary to complete either 9280 (Draenei) or 9369 (other) to get 9409, but maybe this is incorrect. I have to test again and see. Luckily, it is at the very start of Ammen Vale.

**Comment by Saben65** [comment]
So if I understand correctly, I believe the issue is with `PrevQuestID` for ID: 9409.

```
    ID  PrevQuestID  NextQuestID  ExclusiveGroup  ProvidedItemCount  SpecialFlags
------  -----------  -----------  --------------  -----------------  ------------
  9409         9371            0               0                  1             4
------  -----------  -----------  --------------  -----------------  ------------
```
That requires the quest [Botanist Taerix](http://www.wowhead.com/quest=9371/botanist-taerix) Which doesn't follow the quest flow according to Wowhead. But I gotta confirm ingame.

**Comment by tkrokli** [comment]
Hmm, interesting. @XaveT , @BahDumbBugs : please test Saben65's SQL to see if it solves the issue.

**Comment by XaveT** [comment]
I mangled my database up testing this, so I'm honestly not sure what would happen just applying @Saben65 's changes.  What ended up making the most sense to me is: 

`            +-------+-------------+-------------+
Name        | ID    | PrevQuestID | NextQuestID |
            +-------+-------------+-------------+
D-Start     |  9279 |           0 |        9280 |
D-First     |  9280 |        9279 |        9409 |
O-First     |  9369 |           0 |        9409 |
UD!         |  9409 |           0 |           0 |
BT          |  9371 |        9409 |       10302 |
VM          | 10302 |        9371 |           0 |
            +-------+-------------+-------------+`

That way you don't have to extra-click on Proenitus to pick up the [Replenishing the Healing Crystals](http://www.wowhead.com/quest=9280/replenishing-the-healing-crystals).  Same with [Volatile Mutations](http://www.wowhead.com/quest=10302/volatile-mutations).  It's offered immediately afterward.  Sadly we can't do that with [Urgent Delivery](http://www.wowhead.com/quest=9409/urgent-delivery), since we have two possible before-quests.

**Comment by dr-j** [comment]
the quest for dreanei and the quest for other races should be exclusive grouped together with negative quest id so player can only complete either quest.

**Comment by XaveT** [comment]
Is that not taken care of by the Allowable Races flag in world.quest_template?

**Comment by Saben65** [comment]
Currently, only draenei can take the draenei quest, and the other quest is only acceptable by non draenei classes.

**Comment by tkrokli** [comment]
Notice also that there are lines in the `conditions` table affecting the quests / quest giver too:
```sql
SELECT * FROM `conditions` WHERE `Comment` LIKE '%Proenitus%';
```
(- I have taken the liberty to place the comment column first, only for readability reasons -)
```
Comment                                                                                      SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName
-------------------------------------------------------------------------------------------  -----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------
Proenitus - Show Gossip Text only if Replenishing the Healing Crystals rewarded - or                              14         7305         8669         0          0                         8                0             9280                0                0                  0          0            0            
Proenitus - Show Gossip Text only if Replenishing the Healing Crystals rewarded - or                              14         7305         8669         0          1                         8                0             9369                0                0                  0          0            0            
Proenitus - Show Gossip Text only if Replenishing the Healing Crystals not rewarded - and                         14         7305         8667         0          0                         8                0             9280                0                0                  1          0            0            
Proenitus - Show Gossip Text only if Replenishing the Healing Crystals not rewarded                               14         7305         8667         0          0                         8                0             9369                0                0                  1          0            0            
```

**Comment by SnapperRy** [comment]
Here's an improvement of XaveT's fix, taking into consideration existing DB values as of today.

```sql
UPDATE `quest_template_addon` SET `PrevQuestId`=0 WHERE `id`=9409;
UPDATE `quest_template_addon` SET `PrevQuestId`=9409 WHERE `id`=9371;
UPDATE `quest_template_addon` SET `ExclusiveGroup`=9280 WHERE `ID` IN (9280, 9369);

UPDATE `quest_template` SET `RewardNextQuest`=9409 WHERE `ID`=9280;
```
