### ISSUE TITLE
[3.3.5] Core/Spell: SPELL_EFFECT_TRIGGER_MISSILE - Triggerdelay in Vehicles

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#16397]
rev: https://github.com/TrinityCore/TrinityCore/commit/e6a7818a9a12b085c8ea07cfb8b3c6d1d700a112

**Links:**
http://www.wowhead.com/spell=52338/hurl-boulder
http://www.wowhead.com/npc=28781/battleground-demolisher

**Problem/How it is:**
Currently if you click a spell with  effect SPELL_EFFECT_TRIGGER_MISSILE in a vehicle (like the spell "Hurl Bolder" in the Vehicle "Battleground Demolisher") you will see that the spell itself has a little cooldown itself until it gets triggered.

If you compare https://www.youtube.com/watch?v=G2V9yRHsnYk with the current spellhandling, you will see the _big_ difference between the handling of vehiclespells

Current handling of the spell:
- Click on spell=52338/hurl-boulder
- you will see that you must wait around **1 seconds**
- after this one second the linked spell will finally be triggered and the fireball fly around

_The issue_:
The little cooldown from one seconds until the spell finally gets triggered should not be triggered.

**Comment by Rushor** [comment]
updated issue to a more general problem, because the problem with SPELL_EFFECT_TRIGGER_MISSILE affects all vehicles.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by CraftedRO** [comment]
32bfd0787d4371327d74e658b973af34ee450a31 comparing current behavior with wotlk classic one seems still valid no idea if it's only visual or not:

Current TC - https://youtu.be/hvfcyZ1qhc0
WotLK classic - https://youtu.be/gnnT3jk6iX4?t=85

**Comment by Shauren** [comment]
This is not a bug.
This delay behavior happens purely clientside (CAST_SPELL packet itself is delayed) and depends ONLY on visual/missile data in dbc files
Length of the delay is equal to animation duration (for this vehicle, the "loading ball" anim where it moves backward)
