### ISSUE TITLE
[6.x] Quest (Horde) - Tiger Palm

### ISSUE THREAD

**Issue by Suraf** [TrinityCore/TrinityCore#16394]
TrinityCore Rev.: d5b0ffbe9b0c07beb8d0dfc52a6532c2da805285

Target quest: http://www.wowhead.com/quest=31147/tiger-palm
Bug: Available to all classes, only suppose to be available to Monks.

Possible fix:

```sql
DELETE FROM `quest_template_addon` WHERE  `ID`=31147; -- just in case it exists, it shouldn't
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `NextQuestID`, `ExclusiveGroup`) VALUES (31147, 10, 31148, 24964);
```

**Comment by BahDumbBugs** [comment]
Duplicate #16017

**Comment by tkrokli** [comment]
@Suraf : please post your solution in issue #16017 and compare it with the values posted there.
