### ISSUE TITLE
[master] DB/Quest: The Burning Blade (quest id: 25232) Quest mobs don't drop Burning Blade Spellscroll 

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16401]
The creatures for this quest don't seem to drop the spellscrols (item id :52564)
http://www.wowhead.com/quest=25232/the-burning-blade

TrinityCore rev. 6c48066a6f24 2016-01-11 18:33:20 +0100 (6.x branch) (Win64, Release)

**Comment by offl** [comment]
Should be tested after 6feb947af6479ab315c470e4c13ade0eb935369c.

**Comment by KarrokDC** [comment]
I'm affraid that fix did not do anything to this specific quest. Retested @ rev ce0054f03090a86f6e4f1efc0eee57659481cce1

The mobs seem to lack the drop in the loottable.

**Comment by offl** [comment]
There was a core-related problem(fixed in 6feb947). Maybe the item 52564 is still missing in creature_loot_template and the solution from https://github.com/TrinityCore/TrinityCore/issues/19812#issuecomment-310358832 should be added(only creature_loot_template part).

**Comment by DantestyleXD** [comment]
Try with my last commit and give me a feedback.

**Comment by offl** [comment]
@KarrokDC try with this please:
```sql
-- Quest: The Burning Blade
DELETE FROM `creature_loot_template` WHERE `Item`= 52564;
INSERT INTO `creature_loot_template` (`Entry`,`Item`,`Chance`,`QuestRequired`,`MinCount`,`MaxCount`) VALUES
(3196,52564,86,1,1,1),(3199,52564,64,1,1,1),(3195,52564,43,1,1,1);
```

**Comment by BahDumbBugs** [comment]
Tested with commit TrinityCore rev. a16d3209fd1c 2018-01-08 00:45:24 +0100 (master branch) and still saw no spellscrolls dropped.

**Comment by tkrokli** [comment]
You could test the SQL from offl or any other suggested changes in this issue page and tell us if it works or not.
(I am currently unable to log in to my 7.x game client to test any of this, personal configuration issue)
