### ISSUE TITLE
DB：Update creature_template to 20886

### ISSUE THREAD

**Issue by PalWow** [TrinityCore/TrinityCore#16408]
Rev：https://github.com/TrinityCore/TrinityCore/commit/2e2fe86f315e0e5e8bb794e2c1a8609ee8bfcd5d

All  creature_template in 20886

http://pan.baidu.com/s/1bnVJLaZ

```sql
# TrinityCore - WowPacketParser
# File name: multi
# Detected build: V6_2_3_20886
# Detected locale: enUS
# Targeted database: WarlordsOfDraenor
# Parsing date: 01/27/2016 19:20:06

**Comment by DDuarte** [comment]
Thanks but please upload the original pkt to https://community.trinitycore.org/forum/13-wdbadbsniffs/

P.S 404 on your link

**Comment by PalWow** [comment]
DONE .

DB：all creature_template in 20886 (SQL + PKT)
By TOMX, just now

**Comment by DDuarte** [comment]
Thanks!
