### ISSUE TITLE
SQL Server Version

### ISSUE THREAD

**Issue by Exitare** [TrinityCore/TrinityCore#16407]
I`ve recompiled the Core.
I have stock Trinity, no custom changes, no sql changes, no c++ changes.

Error is the same:
TrinityCore/src/server/database/Database/DatabaseWorkerPool.h:71 in DatabaseWorkerPool FATAL ERROR:
Used MySQL library version (5.5.47) does not match the version used to compile TrinityCore (5.5.46).
After upgrading SQL Server on Ubuntu 14.10, this error message is shown. Starting Server failed.

Hash-Revision: 2e2fe86

**Comment by Aokromes** [comment]
You must have forgot make install. 
Used MySQL library version (5.5.47) does not match the version used to compile TrinityCore (5.5.46).
This is not a forum. stop to open tickets of no bugs.
