### ISSUE TITLE
[6.x] Linker issue with TC

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#16403]
The project TrinityCore takes too much time when the project is complied with debug (without scripts) on Windows 10 (Visual Studio 2013).
It takes 2 hours to the linker to generate the pdb file on a powerful computer (i7)
It seems that the issue comes from the game lib (maybe the size ?)

rev: 2e2fe86f315e0e5e8bb794e2c1a8609ee8bfcd5d

**Comment by Aokromes** [comment]
This is not a forum, maybe you need to increase your ram/virtual memory.

**Comment by Nelidon** [comment]
The problem came from the project, otherwise I won't open an issue there.
I have 12GB of memory on my computer.

**Comment by Shauren** [comment]
Disable incremental linking - change "/INCREMENTAL" to "/INCREMENTAL:NO" in cmake gui and report back

**Comment by Nelidon** [comment]
Works very well.
I compiled first time from a clean solution and next after a modification.

Thank you @Shauren.

**Comment by DDuarte** [comment]
Is this something that we want to enable by default in our CMake files?

**Comment by Nelidon** [comment]
You should turn off the incremental linking, otherwise the compilation with /debug will take 2 hours.
@Shauren do you know how to change the flag from CMake automatically?

**Comment by Shauren** [comment]
@Nelidon looking into it - also it doesnt always happen, only if you are not doing a full rebuild

**Comment by Nelidon** [comment]
@Aokromes please reopen this issue.

**Comment by Rochet2** [comment]
> I have a problem with linking my code ... would you know how a linker might never finish?
> The linker runs for hours
> but doesn't report any error or finish the process
>>are you compiling 64 bit?

> yea 64bit debug mode
> release mode works
>>I had that too once

> I fixed it first by disabling incremental linker
> but now that I divided the project into 3 cmake targets, the problem happens on both incremental linker setting

> .. time passes ..

> I found out the issue with the debug linker
> It has something to do with using a 32bit toolchain... It works when using native x64 toolchain
> Microsoft is really an asshole
> Default toolchain, even when compiling an x64 application, is the x86 one


Maybe related.

**Comment by DDuarte** [comment]
That thing with 32bit toolchain compiling 64 bit TC is known to throw out of heap errors. Seems like a recent issue with VS.
