### ISSUE TITLE
[6.x]Spell issues (global)

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#16419]
I found a very important bug in the spells. Quite some spells do not cause damage and I found what it was. 
For example http://wowhead.com/spell=2948 - deals damage (he has a spell effect only one School Damage) But if you take the same same type, but with more than 1 effect, damage is not. 
For example http://wowhead.com/spell=31661 http://wowhead.com/spell=2120 http://wowhead.com/spell=108853 http://wowhead.com/spell=11366 
I counted somewhere in the code was an error processing spelleffect when they are more than one, core begins to counting from [1] , not [0]. 
Please check.

commit  https://github.com/TrinityCore/TrinityCore/commit/01be486f2f0f35e8421d1a1919bd037194756932

**Comment by chilito** [comment]
update
after remove spelleffect [0] (21276) of  http://wowhead.com/spell=2948   from SpellEffectScaling.dbc  it's starts working good

**Comment by Aokromes** [comment]
#14825
