### ISSUE TITLE
 [3.3.5][6.x] Core: Creature equipement

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#16416]
equipment_id field on creature table is not working correctly, if it's set to 0 the npc still spawn with the equipement.
rev. cdf7ac60965f

**Comment by Saben65** [comment]
Isn't that by design because everything else in the `creature` table is inherited from the `creature_template` if left empty??

**Comment by Killyana** [comment]
Yes but there's nothing related to equipments on creature_template

**Comment by Saben65** [comment]
Ah sorry, was thinking of `creature_equip_template`.

**Comment by Kizarr** [comment]
It is located in creature_equip_template because I fixed this issue before manually I had to find the weapons and shield ID from wowhead for this npc's became TrinityCore refuses to acknowledge it.

**Comment by Langerz82** [comment]
I changed the creature_equip_template on the db and used "reload all" and it had a stale entry and wasnt reloaded from the db. However restarting the Server the equipped weapons are showing.

**Comment by Langerz82** [comment]
This simple patch should allow reloading of the creature equip template.

See:
https://gist.github.com/Langerz82/1d3c48e06f15f4d505b1f0c11c76b949
