### ISSUE TITLE
[ICC] Kinetic Bomb stuck after knockback- Blood Princes

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#16415]
After taking Knockback effect the Kinetic stuck in the air and not fall again.
Spells like: Typhoon  (Balance Druid) and Thunderstorm (Shaman Elemental) make this problem occurs.

http://wotlk.openwow.com/spell=50516
http://wotlk.openwow.com/spell=51490

TC Hash: ac727ab208e592c7a2d01ebe321944402860c3ae

Suggested Fix: (i dont know if this is hack)

```diff

diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
index f59701b..b8e7dcc 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
@@ -1222,6 +1222,7 @@ class npc_kinetic_bomb : public CreatureScript
                 _x = 0.f;
                 _y = 0.f;
                 _groundZ = 0.f;
+                me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
             }
 
             void Reset() override
```

**Comment by Rushor** [comment]
it would be great if we add a flagextra in Creature::Create to check for these immunities

(see https://code.google.com/archive/p/trinitycore/issues/4178)

**Comment by Shauren** [comment]
@Keader thats an acceptable change, you can PR it and I will merge that

**Comment by Runico** [comment]
Kinetic doesn't fall again after taking any dmg

**Comment by Keader** [comment]
Yes @Runico  but has hack fix for this
