### ISSUE TITLE
[3.3.5][6.x] Core/Event: On core restart, Lunar Fesitval Elders give out quests/coins again

### ISSUE THREAD

**Issue by XaveT** [TrinityCore/TrinityCore#16413]
TrinityCore rev. 3f886025a255 2016-01-22 22:14:28 +0100 (3.3.5 branch) (Unix, Release)

I was testing a smart script patch for a different ticket when I noticed that Lunar Festival Elders don't think I've turned in the quest for their individual coins after I restart the server.

Noticed on:
Elder Bladeleaf (http://www.wowhead.com/npc=15595/elder-bladeleaf)
Elder Stormbrow (http://www.wowhead.com/npc=15565/elder-stormbrow)

I have no reason to believe these to be unique, but I can test others further if we need it.

I'm guessing this has to do with it being a "roughly" yearly event.

**Comment by Kittnz** [comment]
So every restart you can get the quest and give it in again every server restart? Sounds like an core issue for giving quests. Probably https://github.com/TrinityCore/TrinityCore/commit/1ef1d42d145c18579a7e7ca15cebb38485bc0cff is the cause?

**Comment by sirikfoll** [comment]
you can revert https://github.com/TrinityCore/TrinityCore/commit/a8a5b5a8f02bbb112abbb9ca418939f003c74a22 as a temp solution

**Comment by XaveT** [comment]
It's just me on my core, so not a big enough deal to revert.  It would be worse on cores with actual users.

**Comment by tkrokli** [comment]
Fair enough, although the intention behind TrinityCore is learning, so I believe we ought to treat the issue as if there were players on the server and see what can be done to improve it (if at all possible).

**Comment by XaveT** [comment]
Seems to me the way Blizz would have dealt with it is store the quests like any other, per character, complete like they aren't coming back.  Then right before the event starts up again, remove those entries for a character.  It would probably be done in the Tuesday maintenance before that event.  That way they had minimal work.  It isn't all that elegant, but it would work.
