### ISSUE TITLE
[3.3.5][6.x][Hyjal Summit] Core/Creature - Archimonde spawn

### ISSUE THREAD

**Issue by Gargarensis** [TrinityCore/TrinityCore#16424]
The NPC Archimonde (17968) is spawned (but it is not visible) before killing the 4 previous bosses.

Bug: it can attack other players while remaining invisible.
Minor bug: it should be bigger (scale).

Rev: b1d0855624d1c83850fc36f5242437d7f7c1336b

**Comment by Rushor** [comment]
> Minor bug: it should be bigger (scale).

is maybe a missing aura

**Comment by Killyana** [comment]
The scale is 1 in master, according to videos from retail it's correct:
``` sql
UPDATE `creature_template` SET `scale`=1 WHERE `entry` =17968;
