### ISSUE TITLE
[3.3.5] Core/Crash: 0x00007ffff56fd6e3 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16435]
http://paste.ubuntu.com/14731041/
Rev: 8ef9ea9

**Comment by Aokromes** [comment]
#8  Unit::RemoveAurasDueToSpell (this=0x7fff6d9f2000, spellId=52693, casterGUID=..., reqEffMask=<optimized out>, removeMode=AURA_REMOVE_BY_DEFAULT) at /home/Source/src/server/game/Entities/Unit/Unit.cpp:3748

Something on dk area?

**Comment by tkrokli** [comment]
Looks like it, spellId=52693 (Realm of Shadows) related to quest 12687, Into the Realm of Shadows. Aura is removed upon delivery of the deathcharger, 10m or closer to Salanar the Horseman.

**Comment by Rushor** [comment]
@Runico: this issue is still present? do you tried to find out if it is related to some dk stuff?

**Comment by Runico** [comment]
@Rushor, Just once, I did something for that quest but no chance to reproduce crash

**Comment by sirikfoll** [comment]
https://gist.github.com/sirikfoll/9e5942644f6fee8e5de9390a3273601f
Rev. https://github.com/TrinityCore/TrinityCore/commit/d82534a7bbd401f4b672786749f10f5a95f6e76c

**Comment by Aokromes** [comment]
near 2 years since the last crash report with a lot of spells changes, if this bug is still valid open a new ticket with updated core.
