### ISSUE TITLE
[3.3.5] Halaa (Nagrand)

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#16431]
I think the pvp area is bugged (in Nagrand), i've conquered it and now NPC are duplicated (guards and seller). Also i didn't find Kartos to turn crystals but i didn't have much time to check, i will confirm this later/tomorrow.

![halaa](https://cloud.githubusercontent.com/assets/10136428/12694880/5b04f3ae-c73b-11e5-85db-233a9b04e718.jpg)

TrinityCore: cb8f64cb63c9
DB: 335.60

**Comment by Aokromes** [comment]
#8597
