### ISSUE TITLE
[3.3.5] Wind Stones

### ISSUE THREAD

**Issue by danqu** [TrinityCore/TrinityCore#16436]
Wind Stone summon BOSS，Players wear the equipment does not disappear，Unlimited summon ！
Script name: go_wind_stone
Code file: src/server/scripts/Kalimdor/zone_silithus.cpp

Rev: b1d0855

**Comment by tkrokli** [comment]
That script is on our list of "hardcoded text to be moved to database". If you have any suggestions on how to improve on the script, we could implement that at the same time. :)

**Comment by danqu** [comment]
@tkrokli Now this script does not work properly, there is BUG, you find this problem

**Comment by sirikfoll** [comment]
Upon gossip selection, the GO needs to be activated and a respawn time set, the amount changes depending on the GO type.
According to [wowwiki](http://wowwiki.wikia.com/wiki/Wind_stone)
about 5 minutes for Lesser Wind Stones
about 15 minutes for Normal Wind Stones
about 3 hours for Greater Wind Stones

I do not know if the special  items required to use the stones need to be removed too, worth remebers that this quests no longer exists in retail

Video showing the stone usage and despawn: https://www.youtube.com/watch?v=pV5qGlSKeUI

**Comment by Trisjdc** [comment]
Nothing to do with the script itself, it's just the Wind Stone GOs blocking LoS

```
-- Silithus Stone spells should ignore LoS
DELETE FROM `disables` WHERE `sourceType`=0 AND `entry` IN (24803,24745,24747,24757,24759,24761,24762,24766,24769,24771,24773,24785,24787,24791,24792,24793);
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
(0, 24803, 64, '', '', 'Abyssal Punishment ignores LoS'),
(0, 24745, 64, '', '', 'Summon Templar, Trigger ignores LoS'),
(0, 24747, 64, '', '', 'Summon Templar Fire, Trigger ignores LoS'),
(0, 24757, 64, '', '', 'Summon Templar Air, Trigger ignores LoS'),
(0, 24759, 64, '', '', 'Summon Templar Earth, Trigger ignores LoS'),
(0, 24761, 64, '', '', 'Summon Templar Water, Trigger ignores LoS'),
(0, 24762, 64, '', '', 'Summon Duke, Trigger ignores LoS'),
(0, 24766, 64, '', '', 'Summon Duke Fire, Trigger ignores LoS'),
(0, 24769, 64, '', '', 'Summon Duke Air, Trigger ignores LoS'),
(0, 24771, 64, '', '', 'Summon Duke Earth, Trigger ignores LoS'),
(0, 24773, 64, '', '', 'Summon Duke Water, Trigger ignores LoS'),
(0, 24785, 64, '', '', 'Summon Royal, Trigger ignores LoS'),
(0, 24787, 64, '', '', 'Summon Royal Fire, Trigger ignores LoS'),
(0, 24791, 64, '', '', 'Summon Royal Air, Trigger ignores LoS'),
(0, 24792, 64, '', '', 'Summon Royal Earth, Trigger ignores LoS'),
(0, 24793, 64, '', '', 'Summon Royal Water, Trigger ignores LoS');
```

**Comment by sirikfoll** [comment]
Works perfectly, thank you!

**Comment by danqu** [comment]
@Trisjdc But found a problem, there is no CD limit，Unlimited Summon

**Comment by tkrokli** [comment]
Isn't that a separate problem, something you could open a new issue for?

**Comment by danqu** [comment]
Seek to solve this problem, improve the script
