### ISSUE TITLE
[3.3.5][6.x][ICC] Core/Creature: Target selection of Sindragosa's spell, Ice Tomb(third phase only)

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#16441]
The spell do not use the target selected by the script, this causes some issues,
like freeze the tank, and announce that will freeze one player, and freeze another one

It was beeing discussed in the commit  https://github.com/TrinityCore/TrinityCore/commit/1f076a395fa7ba391e07a23f23d320943ec9e001

The piece of code responsable:
```cpp
if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, FrostBeaconSelector(me)))
{
     Talk(EMOTE_WARN_FROZEN_ORB, target);
     me->CastCustomSpell(SPELL_ICE_TOMB_TARGET, SPELLVALUE_MAX_TARGETS, 1, nullptr, TRIGGERED_FULL_MASK);
}
```

I tried changing this, but do not solved anything
```diff
- me->CastCustomSpell(SPELL_ICE_TOMB_TARGET, SPELLVALUE_MAX_TARGETS, 1, nullptr, TRIGGERED_FULL_MASK);
+ me->CastCustomSpell(SPELL_ICE_TOMB_TARGET, SPELLVALUE_MAX_TARGETS, 1, target, TRIGGERED_FULL_MASK);
```
hash 815f43be7a0e
branch 3.3.5

**Comment by Runico** [comment]
@sirikfoll, It should ice tank or not ?

**Comment by Keader** [comment]
No @runico

**Comment by Runico** [comment]
@Keader, So @sirikfoll patch will fix that part ?

**Comment by Keader** [comment]
No, he just gave an example of what he tried to do but it does not work.

**Comment by Golrag** [comment]
Spell doesn't care about the result of the SelectTarget method, even if you pass the target within CastCustomSpell, targets are selected in Spell::SelectImplicitAreaTargets (in this case).
That's why the player's name in the text is not always the one who's being ice blocked

I've got something working now will push it Soon™

**Comment by peycho** [comment]
Sindragosa's tombs still can not be targeted.

TDB 335.61 - 2016/04/11
core: 2f8493952214f328a6dfebd93414ee721a3fff3a
Newly extracted map/mmaps/vmaps/dbc

**Comment by Shauren** [comment]
@peycho This is not the same issue as this.
This issue is about sindragosa picking players to ice tomb, not about ice tomb los
