### ISSUE TITLE
[3.3.5a] Creating Character freezes Worldserver 

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16446]
rev: 20a8476cd885417b1f2fd4ac27c440efafae7bb8
branch: 3.3.5

hello, i compiled latest trinity and cant create character, server freezes no log, or gives me an error creating character here are screen. sorry for bad english.
1. Freezed
![1s](https://cloud.githubusercontent.com/assets/8265622/12715478/016cd6f8-c8f4-11e5-8a58-af17dbb1aaa8.PNG)

2. Error Creating Character
![2s](https://cloud.githubusercontent.com/assets/8265622/12715491/10530ff2-c8f4-11e5-8566-9d0b3f6c8784.PNG)

**Comment by tkrokli** [comment]
Looks like a modified game client. Make sure you reset your game client to 3.3.5a (12340) defaults.

**Comment by lashia** [comment]
i didnt change anything,  i downloaded it from warmane, 
http://prntscr.com/9xkqq1

**Comment by Aokromes** [comment]
Cannot reproduce on a properly compiled TC with unmoded client.

**Comment by tkrokli** [comment]
TrinityCore rev. 789470ccf1bf 2016-01-30 15:20:41 +0100 (3.3.5 branch) (Win64, Release)
Can't reproduce here either with my own original game client from 2010 and unmodified 3.3.5 server.

**Comment by hoxton22** [comment]
Look like you have a patch HD, Original CharSections from ur server and CharSections patched in ur client aren't the same, so when you create your character, you are not sending the same characters informations creations (skin id, face id etc....) located in your server side dbc.

I suggest you to modify Player.cpp
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L641

Change return false by return true, should work.


(sorry for my bad english btw )

**Comment by tkrokli** [comment]
@hoxton22 : that is what Aokromes and I was trying to say, a modded game client is not supported.
Thanks for posting the details about what kind of game client modding this could be, I've seen it before.

@lashia : Please use https://community.trinitycore.org/forum/9-custom-code-and-requests/ (Custom section) of the TrinityCore Forum for issues when using a modified (custom) game client as well as customized source.

**Comment by Shauren** [comment]
this isnt a server freeze

**Comment by jackpoz** [comment]
since when the console is purple with blue error messages ?

**Comment by lashia** [comment]
ill download another  client, but i compiled 3-4 days ago and played without problem

**Comment by Kittnz** [comment]
I smell a repack, you have not compiled this core yourself. Server does not even see what rev you are using and git was not correctly installed.

**Comment by lashia** [comment]
cmake cant see git so built without git and if you want i will recompile and make a video  :)

**Comment by Rushor** [comment]
If Aokromes says:
Cannot reproduce on a properly compiled TC with unmoded client.

then everything is working fine - the issue is on your side. try it with a clean core and 3.3.5 client.
