### ISSUE TITLE
[3.3.5][6.x][Druid] Core/Spell: Feral Charge (Cat)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16445]
Branch 3.3.5, rev. 8a0bbc386982

Feral Charge (Cat) should:
* Not cause target to aggro the druid if the druid is stealthed
* Cause the druid to land facing the target('s back)

http://www.wowhead.com/spell=132302/wild-charge

**Comment by tkrokli** [comment]
What is the current observed bug? The opposite of your listed effects? :)

**Comment by Treeston** [comment]
* Using Feral Charge (Cat) while stealthed makes the targeted mob enter combat with the druid
* After using Feral Charge (Cat), the druid lands facing whatever direction the arc of the charge had

**Comment by Keader** [comment]
On Spellmgr.cpp add atribute

```cpp
spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_INITIAL_AGGRO;
```
does not solve the problem of combat?

**Comment by joschiwald** [comment]
https://gist.github.com/joschiwald/2f5564d680fc74a55ff8

there is also a similar issue

**Comment by Treeston** [comment]
Also (not sure if this a bug), but you can use Feral Charge (Cat) while rooted.

**Comment by Eliminationzx** [comment]
https://github.com/Eliminationzx/TrinityCore/commit/106898cdb453a2d1be9977642ddab5a6f1a01093

**Comment by Rushor** [comment]
thx for sharing :)

**Comment by Keader** [comment]
close this please :)

**Comment by Treeston** [comment]
Ref. ff80f24 / cfed2d7 fixes the orientation issue.

Initial aggro issue still exists.

**Comment by Keader** [comment]
add in spellmgr.cpp flag >spellInfo->AttributesEx3 |= SPELL_ATTR3_NO_INITIAL_AGGRO; is hack?

**Comment by Treeston** [comment]
Yes, unless there is no better way.

**Comment by joschiwald** [comment]
b4b43d03b3fbff38ebcf84be27388202fc6cb08f
