### ISSUE TITLE
[3.3.5] Multiple spawns with the same DBGUID

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16462]
3.3.5 d5868a7db31a13ac147a66a25cb4c3a6b8a93f8a

Something is wonky here...
http://i.imgur.com/yiav0F2.jpg

Assigning @pete318  since he said he knows something

**Comment by pete318** [comment]
I know the why. Tomorrow maybe I can provide the correction. It'll only happen with grid unload.

Here's what happens. His path actually crosses two grids. [30, 44] and [30,45]. With the spawn position being in [30, 44].

So how to replicate? You wait until he's at the furthest point of his walk, which is in grid [30, 45]. Then fly away from the area to the west but staying in grid [30, 45]. Wait enough time for sure for [30, 44] to unload. Once you're sure it's unloaded (enable debug messages in maps). Go back to the area and when [30, 44] is loaded it will see there isn't already one in that grid and spawn one.

There's probably a fair few creatures this could apply to!

**Comment by tkrokli** [comment]
TrinityCore rev. f38b8efd7659 2016-02-02 19:11:24 +0100 (say_mr_smite_alarm branch) (Win64, Release) (my PR based on  60f8751), using TDB 335.60 + updates up to and including `2016_01_31_00_world.sql`

Weird. Could you happen to to get both spawns in that place? I can only find the spawn that is supposed to be there, when flying there from Shattrath with my lvl 70 night elf hunter.
Couple of things I notice about your info in the image and your issue post:
- your player character in the image is level 255 and in GM ON mode
- your core rev. hash 97dd18c is from Nov. 4, 2015 (TDB 335.59)

Would like some more issue and game details to see if I am able to replicate / reproduce your issue.
The only (and correct) spawn I could observer from my DB is this one:
```sql
SELECT * FROM `creature_template` WHERE `name` LIKE '%Gordawg%';
```
```
 entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name     subname        IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName  MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName  VerifiedBuild
------  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  -------  -------------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  ------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  ----------  ---------------
 18099                   0                   0                   0            0            0     17525         0         0         0  Gordawg  Fury of Earth  (NULL)              7576        73        73       1     1726        3        1.48    1.14286       1       1          0            2000             2000             1              1           1           0         2048             0       0             0              0              0             0       5           0       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                     1            3            1             500             1              1             4.6                   1             0         199            1                     0            0                      12340
```
```sql
SELECT * FROM `creature` WHERE `id` = 18099;
```
```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ---------------
 64052   18099     530       0       0          1          1        0             0    -872.607     6907.52     33.8552      1.99775            300          0                0    3790000        0             2        0           0             0              0
```
```
Player selected NPC
DB GUID: 64052, current GUID: 1390.
Faction: 1726.
npcFlags: 3.
Entry: 18099.
DisplayID: 17525 (Native: 17525).
Level: 73.
EquipmentId: 0 (Original: 0).
Health (base): 3794000. (max): 3794000. (current): 3794000.
InhabitType: 3
Unit Flags: 0
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1726.
SpawnTime: Full:5m Remain:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 7684
Position: -868.769104 6975.857422 34.775131.
AIName:  ScriptName: 
Flags Extra: 0
* has gossip (1)
* is quest giver (2)
```

**Comment by Treeston** [comment]
The hash in my db hadn't updated for some reason. I was running 3.3.5 d5868a7db31a13ac147a66a25cb4c3a6b8a93f8a at the time.

**Comment by Shauren** [comment]
Oh hey, my system for allowing multiple spawns of the same dbguid works (almost... there should only ever be one ALIVE)

**Comment by pete318** [comment]
@Shauren it definitely works. In the dynamic spawn work I'm doing, I created some 100x of a creature group I setup (the creatures in the Orgrimmar Inn) and then despawned them all. There's no problem with multiple spawns, same spawnid.

In this case though, it's just that the grid loader is blind. It assumes that the creature would never leave its home grid, and as such assumes every creature from that grid should be loaded.

I think a simple check in either LoadHelper or LoadCreatureFromDB against the spawnIdStore will suffice. I'll get onto it a bit later, it'll also probably need to go into 6.x. I can't see it likely that part has changed there.

**Comment by pete318** [comment]
Comments on this https://github.com/pete318/TrinityCore/commit/7f798272cd91ae9e4840e6a150a0dd261fbd93ad would be appreciated. Otherwise I'll commit this evening.

The reason I delete the dead ones too? Well that's because it would be theoretically possible that if we left the dead spawn in the other grid after loading the home grid that the other grid would unload later taking the corpse with it. In this case the creature would not spawn until his home grid was next unloaded. So, this just ensured that a creature (and only one) will spawn when it should regardless.
