### ISSUE TITLE
[3.3.5][6.x][DK] Core/Spell: Summon Gargoyle - Attackbehaviour

### ISSUE THREAD

**Issue by dixanackmad** [TrinityCore/TrinityCore#16464]
When you use ''Summon Gargoyle''  on a target your Gargoyle have to attack this target, but in b1d0855624d1c83850fc36f5242437d7f7c1336b Gargoyle appear and follow th Deathknigth without do any damage. Gargoyle will start to attack only when you move a bit. Also when he starts his attacks he doesn't the right damage, it seems he doesn't take the right stats from the deathknigth.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15522
https://github.com/TrinityCore/TrinityCore/issues/16181
https://github.com/TrinityCore/TrinityCore/issues/5136

**Comment by Rushor** [comment]
spellids: http://wotlk.openwow.com/?search=Summon+Gargoyle
