### ISSUE TITLE
[3.3.5] Core/Scripts Inconsistent behavior of OnGossiphello/sGossipSelect

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#16466]
The issue happens with all npcs or GOs that trigger actions using funcions like OnGossiphello and sGossipSelect.

What sould happen:
Even if multiple player manage to use the go/gossip at same time, the action only should be executed once.

What Happens instead:
If multiple players use the object/gossip option at the same time, all the actions linked to the function will be executed one time for each player who use it.

Some Examples:
- Icecrown Gunship Battle:
 2 players talk with Muradin Bronzebeard(Entry: 36948), all events tied to sGossipSelect will be scheduled twice, the gunship fight will be "duplicated", two opposite gunship boss, duplicate Says, etc
![wowscrnshot_020316_153943](https://cloud.githubusercontent.com/assets/11219553/12791414/32c22cda-ca8e-11e5-87e4-ae131cebba10.jpg)

- Mimiron:
Multiple players use the go_mimiron_hardmode_button(Entry: 194739) at same time, Computer texts duplicate
![wowscrnshot_020316_152337](https://cloud.githubusercontent.com/assets/11219553/12791433/51a18268-ca8e-11e5-98f8-67be9a35871b.jpg)

- Algalon:
Two players use the go_celestial_planetarium_access(Entry: 194628,194752), Algalon will the summoned twice and cause other bugs.
![wowscrnshot_020316_153237](https://cloud.githubusercontent.com/assets/11219553/12791426/47940750-ca8e-11e5-8b8a-8a464aa060bf.jpg)

- Ulduar hardmode vehicles:
Two players talk with npc_lorekeeper(Entry: 33686) multiples vehicleswill be summoned
All these can be avoided by creating a boolean variable to check if the event is already activated.
But, it would be nice if a more generic solution could be found
![wowscrnshot_020316_155823](https://cloud.githubusercontent.com/assets/11219553/12792044/182dae32-ca91-11e5-9cdf-74c5d5cfe419.jpg)

hash 815f43be7a0e
branch 3.3.5

**Comment by Keader** [comment]
On Mimiron, sometimes the "Emergency Mode" aura is doubled.

**Comment by tkrokli** [comment]
@sirikfoll : good point, it would be nice if there had been a more generic solution. Then again, that solution would have to set some kind of instance of the specific event as well as make sure that the attempt to start it again by the other player(s) do(es) not generate more error information than for the player trying to initiate a new instance of the event.

Like you mentioned, it feels like it might be easier to implement a boolean check for if it is running already and that it needs to be added for each user-created script that calls that event.

**Comment by joschiwald** [comment]
try this:
```diff
 src/server/game/Handlers/MiscHandler.cpp | 2 +-
 src/server/game/Handlers/NPCHandler.cpp  | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/server/game/Handlers/MiscHandler.cpp b/src/server/game/Handlers/MiscHandler.cpp
index 758d5af..74de957 100644
--- a/src/server/game/Handlers/MiscHandler.cpp
+++ b/src/server/game/Handlers/MiscHandler.cpp
@@ -105,7 +105,7 @@ void WorldSession::HandleGossipSelectOptionOpcode(WorldPacket& recvData)
     GameObject* go = NULL;
     if (guid.IsCreatureOrVehicle())
     {
-        unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_NONE);
+        unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_GOSSIP);
         if (!unit)
         {
             TC_LOG_DEBUG("network", "WORLD: HandleGossipSelectOptionOpcode - %s not found or you can't interact with him.", guid.ToString().c_str());
diff --git a/src/server/game/Handlers/NPCHandler.cpp b/src/server/game/Handlers/NPCHandler.cpp
index f272cd4..3c0f69f 100644
--- a/src/server/game/Handlers/NPCHandler.cpp
+++ b/src/server/game/Handlers/NPCHandler.cpp
@@ -292,7 +292,7 @@ void WorldSession::HandleGossipHelloOpcode(WorldPacket& recvData)
     ObjectGuid guid;
     recvData >> guid;
 
-    Creature* unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_NONE);
+    Creature* unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_GOSSIP);
     if (!unit)
     {
         TC_LOG_DEBUG("network", "WORLD: HandleGossipHelloOpcode - %s not found or you can not interact with him.", guid.ToString().c_str());
@@ -352,7 +352,7 @@ void WorldSession::HandleGossipHelloOpcode(WorldPacket& recvData)
         TC_LOG_DEBUG("network", "string read: %s", code.c_str());
     }
 
-    Creature* unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_NONE);
+    Creature* unit = GetPlayer()->GetNPCIfCanInteractWith(guid, UNIT_NPC_FLAG_GOSSIP);
     if (!unit)
     {
         TC_LOG_DEBUG("network", "WORLD: HandleGossipSelectOptionOpcode - Unit (GUID: %u) not found or you can't interact with him.", uint32(GUID_LOPART(guid)));

```

**Comment by sirikfoll** [comment]
@joschiwald Sadly, it does not work :/

**Comment by joschiwald** [comment]
did you tried icecrown gunship battle again? the other encounters don't have anything in code that prevents double interaction

**Comment by Keader** [comment]
@joschiwald  we tested gunship and work

**Comment by LordUsagi** [comment]
I'm pretty sure each case needs its own "security" check just like we check in conditions if creature XXX is already summoned, don't summon again etc.

**Comment by joschiwald** [comment]
try again after 8b6954e81b76f8d7c6700eaf1a8b942bebaa85a0

**Comment by sirikfoll** [comment]
It solve the duplicate actions.
The only thing that seems odd is mimiron button, if the two players click it, he bugs, does not show the "push animation" and after wipe, remains non-clicable

**Comment by Keader** [comment]
Click, wipe , click again, wipe, button dont work anymore

**Comment by joschiwald** [comment]
try this:
```diff
 .../scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp       | 2 +-
 src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp             | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
index fd945db..89868fc 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
@@ -980,7 +980,7 @@ class go_celestial_planetarium_access : public GameObjectScript
             bool GossipHello(Player* player) override
             {
                 if (go->HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE))
-                    return false;
+                    return true;
 
                 bool hasKey = true;
                 if (LockEntry const* lock = sLockStore.LookupEntry(go->GetGOInfo()->goober.lockId))
diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
index 4d6aa04..f435c66 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
@@ -1637,7 +1637,7 @@ class go_mimiron_hardmode_button : public GameObjectScript
         bool OnGossipHello(Player* /*player*/, GameObject* go) override
         {
             if (go->HasFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE))
-                return false;
+                return true;
 
             InstanceScript* instance = go->GetInstanceScript();
             if (!instance)

```

**Comment by sirikfoll** [comment]
Works ^^
