### ISSUE TITLE
[3.3.5][6.x] Core/SAI: Pet Killcredit redirection to owner

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#16470]
rev: https://github.com/TrinityCore/TrinityCore/commit/e249db9777e9914770f59e10838b742ba1b37324

**Situation:**

1) There are many creatures in the world which are scripted **with SAI** like this:
"Creature - On kill - Cast Killcredit on action invoker/victim"
The victim which killed the creature will get the killcredit.

2) Hunter can sumon pets and can kill creatures with pets.

**Problem:**
Issue can be reproduced if you merge situation 1) with situation 2)

**If a pet or guardian kills the creatures, the player will not get the killcredit and will not fullfill the questobjectives.**

**Another example**

@digz6666 wrote:
https://github.com/TrinityCore/TrinityCore/issues/15620
The Lost Mistwhisper Treasure quest is completed but cannot turn in.
Wowhead link: http://www.wowhead.com/quest=12575/the-lost-mistwhisper-treasure

![q3](https://cloud.githubusercontent.com/assets/1736110/10126622/8670e266-65c8-11e5-8e6d-b07de093dd61.jpg)
![q2](https://cloud.githubusercontent.com/assets/1736110/10126623/881f93a0-65c8-11e5-829f-c46ed2fcfa4c.jpg)

@dr-j wrote:
just remove special flags which say this quest needs to be completed by an external event since the two objectives are a requirednpcorgo and required item.

Script does call areaexploredoreventhappens on death but if a pet or guardian, or another player gets killing blow then player cant return quest.

``` sql
UPDATE `quest_template_addon` SET `SpecialFlags`=0 WHERE  `ID`=1257
```

**Comment by Rushor** [comment]
fixtry:
http://pastebin.com/eWB0pq6w

**Comment by Rushor** [comment]
Thats the one i had forgotten https://github.com/TrinityCore/TrinityCore/issues/14678

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.

**Comment by CraftedRO** [comment]
12a3316326cf0ccf19021a5cb675943562ed9aac issue seems still valid, if the pet is the one that kill Warlord Tartek the quest count as completed but you won't be able to complete it at the questgiver (not even if you follow wowhead tactic and not loot Mistwhisper Treasure first or damage more than half hp targets): https://youtu.be/W-SqhOuJIy0

Quest Name [The Lost Mistwhisper Treasure](https://www.wowhead.com/wotlk/quest=12575/the-lost-mistwhisper-treasure)
Abandoned 40
Completed 77
Last Abandoned 2025-08-22 17:32:48
Last Completed 2026-03-29 18:57:52
