### ISSUE TITLE
[3.3.5][6.x] Core/Spell: Liquid Auras will not be removed

### ISSUE THREAD

**Issue by chaodhib** [TrinityCore/TrinityCore#16480]
Some liquid Auras will not be removed if the player leaves the instance:

List of the affected spells:
- [ ] 57634: // Magma, CoA Black / Chamber
- [ ] 42201: // Water, Hyjal Past
- [ ] 37025: // Water, Coilfang Raid
- [ ] 36444: // Water, Lake Wintergrasp
- [ ] 28801: // Slime, Naxxramas

This bug is a bit hard to explain with words. So with images, to reproduce the bug (f.ex.: Slime, Naxxramas), stand in the green gu until you die:
![wowscrnshot_020616_005529](https://cloud.githubusercontent.com/assets/6612710/12862528/c2604220-cc6c-11e5-9ef1-7d0724c706c9.jpg)
![wowscrnshot_020616_005538](https://cloud.githubusercontent.com/assets/6612710/12862527/c25cce7e-cc6c-11e5-930a-f3c0d6b19f02.jpg)
Then release. And at respawn, the player still has the debuff on him:
![wowscrnshot_020616_005544](https://cloud.githubusercontent.com/assets/6612710/12862526/c25a46ea-cc6c-11e5-9c1f-b6243a11f927.jpg)

commit: https://github.com/TrinityCore/TrinityCore/commit/9d932e7f0c831615474bfc6c54d4027215d2c1b5
DB 335.6

**Comment by Keader** [comment]
same for pets in OBS?

**Comment by Rushor** [comment]
for specifix instances we could also add a OnPlayerRemoved script similar to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Instances/InstanceScript.h#L186 and remove the debuff there, but this would not be a general fix

**Comment by Demonid** [comment]
You could use this as a hackfix until fixed:

https://github.com/TrinityCore/TrinityCore/pull/14512/files

**Comment by Krudor** [comment]
Still able to reproduce this on master 136269a5851a6755f644295a0171e4bc6c2bef17

**Comment by CraftedRO** [comment]
60b75e3b6e81 Seems no longer valid tested all cases.
Maybe fixed by https://github.com/TrinityCore/TrinityCore/commit/835e2918319ed20109992086311a2c146140937f


https://user-images.githubusercontent.com/24683355/230695855-4502aff2-5701-4bfd-9ab2-6329eee26555.mp4
