### ISSUE TITLE
[DB/Quest] Warsong Recruitment Officer gives dublicate quest

### ISSUE THREAD

**Issue by OScriptTC** [TrinityCore/TrinityCore#16485]
Hello! I've noticed that this NPC gives out two of the same quests and of course that's wrong. So I did some googling and noticed that from the WoWHead comments, he's supposed to give one if quest 10172 is completed and one if it's not. So I wrote up this quick SQL query to fix it:
```
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND (`SourceEntry`=11586 OR `SourceEntry`=11585);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceEntry`,`ConditionTypeOrReference`,`ConditionValue1`,`Comment`) VALUES 
(19, 11586, 14, 10172, "Accept quest 11586 - Quest 10172 needs to be incomplete"),
(19, 11585, 8, 10172, "Accept quest 11585 - Quest 10172 needs to be rewarded");
```

confirmed by http://www.wowhead.com/quest=11586/hellscreams-vigil#comments
rev: d92d5c0d17c7bd3b03522c6146ba91d3adaea223
Latest DB

Cheers

**Comment by Rushor** [comment]
add delete statements pls

**Comment by OScriptTC** [comment]
Updated.

**Comment by OScriptTC** [comment]
Added everything that was asked for on the IRC

**Comment by Kittnz** [comment]
Nice work
