### ISSUE TITLE
[3.3.5][DK] Core/Spell: Horn of Winter appears trainable

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16482]
3.3.5 d1a185e3d5af

Death Knight trainers offer Horn of Winter Rank 1 (57330) for training even if the player already has the spell trained.

**Comment by Kittnz** [comment]
I think this is more of a generic trainer bug

**Comment by Treeston** [comment]
I've never noticed it with any other class trainers.

**Comment by LordUsagi** [comment]
It used to occur a lot with mount training on Paladins and Warlocks, maybe some spells for druids too. Not sure if it was fixed or not though.

**Comment by Rushor** [comment]
can you make a list for these spells @LordUsagi

**Comment by Treeston** [comment]
I seem to recall it happening with Howling Blast too.

**Comment by LordUsagi** [comment]
@Rushor I'm without a running core at the moment and won't be able to compile this list in a timely manner.

**Comment by SeTM** [comment]
It's hack by blizz, for show this spell, if player not have spell: Patch 3.2.0 (2009-08-04): Learning rank 2 of this ability caused players to unlearn rank 1, such that it no longer appears in their spellbook. It is now possible to relearn that rank, and death knights will no longer "forget" rank 1 when they learn rank 2.

Player should always have rank 1 in spell book.

**Comment by tkrokli** [comment]
Interesting fact. Just to add to your otherwise good and to the point comment, documentation links:
- http://wow.gamepedia.com/Patch_3.2.0#Death_knights_2
- http://us.battle.net/wow/en/game/patch-notes/3-2-0
- http://wowwiki.wikia.com/wiki/Horn_of_Winter

**Comment by Treeston** [comment]
Huh.

Does the core currently unlearn HoW rank 2 if you learn rank 1?

**Comment by tkrokli** [comment]
Weird, at rev. 99a6c84 it looks like the trainer UI is very slow at updating, showing prices of 205g for spells that are a little more than 36g when you close and reopen it. It also lists Horn of Winter (rank 1) after getting to level 74-75 and asking for more training. After a couple of close+reopen the trainer UI, the spell Horn of Winter (rank 1) goes away again and appears to be already learned alongside rank 2:

![wowscrnshot_050816_111408](https://cloud.githubusercontent.com/assets/4903600/15096986/0dab98a8-150e-11e6-9448-33c6d91fc0f1.jpg)
