### ISSUE TITLE
[3.3.5]  [The Valiant's Challenge]

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16496]
rev: 335a279d0d88cde541172b6c11b679de5ae2e41a
im new in development but i think there missing gossip menu

![wowscrnshot_020716_200536](https://cloud.githubusercontent.com/assets/8265622/12873444/428d941a-cdd6-11e5-8352-f186f23a5eac.jpg)

**Comment by Rushor** [comment]
make shure that you added all updates from https://github.com/TrinityCore/TrinityCore/issues/8718

**Comment by lashia** [comment]
i will run query from this commit 91ecd006bb02b33647af9a70a63c6514dbb86dda

**Comment by lashia** [comment]
@Rushor same

**Comment by dr-j** [comment]
You cannot do this quest using argent warhorse you have to use one of the faction mounts from outside your factions tent and you must have lance equipped (but see you did anyway)

**Comment by Treeston** [comment]
You're talking to the wrong NPC. Valiant's Challenge tells you to go to a specific squire npc and have him call an opponent for you.

The dude you're talking to is for the AT daily, not the promotion quest.

**Comment by lashia** [comment]
yes, sorry it works
