### ISSUE TITLE
[3.3.5][Priest] Core/Spell: Devouring Plague - Damage Negative 

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#16495]
if you have insufficient spell penetration versus a class with elemental resistance, the devouring plague starts giving negative damage when hp of target is low.

Steps for reproduce:

1. Put Mage and Priest em Duel
2. Add some spell penetration in Priest ( .add aura 64130 )
3. Add some Resistence on Mage (On test i used .add aura  48169 [Shadow Resist] and Mage Armor)
4. Let the mage HP around 100.
5 . See damage "heal" mage :octopus: 

Vid1: https://youtu.be/usZTefH8eX4

Vid2: https://www.youtube.com/watch?v=2je0i-4JCb4&feature=youtu.be

Mage Vision 
![wowscrnshot_020716_121741](https://cloud.githubusercontent.com/assets/7120913/12873280/ac0f28f2-cd97-11e5-885a-7272bc7febfc.jpg)

Trinity Hash: cb8f64cb63c9262717c7a019a581bd284579583c

Code related: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuras.cpp#L1298-L1313

**Comment by Rushor** [comment]
related https://github.com/TrinityCore/TrinityCore/commit/af62cf5939948ee0fc6cc28a150f43076d095491 ?

**Comment by Keader** [comment]
No, the server that I play, verison is 3-month ago and the problem occurs also

**Comment by Eliminationzx** [comment]
Try it
```diff
src/server/game/Spells/Auras/SpellAuras.cpp | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/src/server/game/Spells/Auras/SpellAuras.cpp b/src/server/game/Spells/Auras/SpellAuras.cpp
index 1ca5df6..d6a7a2d 100644
--- a/src/server/game/Spells/Auras/SpellAuras.cpp
+++ b/src/server/game/Spells/Auras/SpellAuras.cpp
@@ -1301,9 +1301,10 @@ void Aura::HandleAuraSpecificMods(AuraApplication const* aurApp, Unit* caster, b
                     // Improved Devouring Plague
                     if (AuraEffect const* aurEff = caster->GetDummyAuraEffect(SPELLFAMILY_PRIEST, 3790, 1))
                     {
-                        uint32 damage = caster->SpellDamageBonusDone(target, GetSpellInfo(), GetEffect(0)->GetAmount(), DOT);
-                        damage *= caster->SpellDamagePctDone(target, GetSpellInfo(), SPELL_DIRECT_DAMAGE);
+                        uint32 damage = std::max(GetEffect(0)->GetAmount() + GetEffect(0)->GetBonusAmount(), 0);
+                        damage = caster->SpellDamageBonusDone(target, GetSpellInfo(), damage, DOT) * caster->SpellDamagePctDone(target, GetSpellInfo(), SPELL_DIRECT_DAMAGE);
 ```

**Comment by Rushor** [comment]
bumping @Keader to test it :)

**Comment by Keader** [comment]
@Eliminationzx Dont work

**Comment by DevRival** [comment]
Work for me!

**Comment by DevRival** [comment]
My fail, realy dont work. [https://youtu.be/mUj-FDtm8B8](url)

**Comment by Eliminationzx** [comment]
@Keader, could you try to remove this `damage = target->SpellDamageBonusTaken(caster, GetSpellInfo(), damage, DOT);`? I guess the problem is here.

**Comment by Keader** [comment]
Nop. Without ```damage = target->SpellDamageBonusTaken(caster, GetSpellInfo(), damage, DOT);``` still does negative damage

**Comment by Keader** [comment]
Old Issue about this: #12682

**Comment by Shauren** [comment]
Was a combat log visual only.

**Comment by Keader** [comment]
@Shauren tested again this issue in rev 5668bc32340bd15ac2195781b8da3ad62d9c56ee
Still bugged. Damage dont show negative (like --45) but devouring plague molds your damage and never kill ter target.
