### ISSUE TITLE
[3.3.5][6.x] DB/Creature: The Halls Of Reflection - Lootissue

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16497]
rev: 335a279d0d88cde541172b6c11b679de5ae2e41a

cant loot and get quest item.

![wowscrnshot_020716_205650](https://cloud.githubusercontent.com/assets/8265622/12873691/85b9327e-cddd-11e5-9cfa-7e29077eb933.jpg)

**Comment by lashia** [comment]
i can only target it with /target Quel'Delar

**Comment by Rushor** [comment]
@MitchesD implemeted this event back in the days, maybe he knows the reason for this :)

**Comment by MitchesD** [comment]
I don't know, maybe someone broke something, when I did it, it worked, was tested many times

**Comment by Aokromes** [comment]
Yeah it worked, i don't have tried to do this quest for long time.

**Comment by DevRival** [comment]
Setting can be done without the group.

**Comment by Rushor** [comment]
kay it's indeed broken - the only problem is that the dummy for the effects is not lootable because of the missing modelid

http://i.imgur.com/l1jYw6h.jpg

if you morph it to an imp it will be lootable

```sql
UPDATE `creature_template` SET `modelid2`=20570 WHERE  `entry`=37158;
```

so something is wrong with lootinteraction for dummynpcs with playerinvisible modelid. probably a general issue

**Comment by Aokromes** [comment]
change model id without sniff is hack :)

**Comment by MitchesD** [comment]
try to remove this line and tell me again 
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp#L2576

**Comment by lashia** [comment]
Okay ill try

**Comment by Rushor** [comment]
Rushor> if we remove the line in c++, there will be the chance that the dummy gets the imp model
<Rushor> http://i.imgur.com/vup59FG.jpg

**Comment by lashia** [comment]
@Rushor nope i think you have morphed try to demoprh, i removed line but its same..


![xca](https://cloud.githubusercontent.com/assets/8265622/12875582/7002f152-ce07-11e5-88b5-0a3d02b4a228.PNG)

![wowscrnshot_020816_015515](https://cloud.githubusercontent.com/assets/8265622/12875559/61ea425a-ce07-11e5-8d81-24777e16ebdd.jpg)

**Comment by Rushor** [comment]
nono, the you were lucky, currently if we remove the line in the script there will be a 50% chance that the dummy remains invisble (like in your case) and a 50% percent chance that the dummy will be morphed to the imp an will be visible (like in my case)

**Comment by Rushor** [comment]
<MitchesD> <Shauren> Aokromes: shouldnt it have equipment so you can click the "model"?
<MitchesD> check sniffs if you can
<Rushor> just found this https://github.com/TrinityCore/TDB_4.3.4_NLU/blob/master/old/updates_03/029_wdb_templates_updates.sql#L579
<Rushor> hm yes it already has equipment on cleantc wotlk db
<Rushor> INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`) VALUES (37158, 1, 50814, 0, 0, 18019);

**Comment by Shauren** [comment]
then why is there no equipment visible on the screens pasted here?

**Comment by Rushor** [comment]
maybe related https://github.com/TrinityCore/TrinityCore/pull/16433 ?

37158 has ID=1 but because creature 37158 is atempsummon, the equipment_id will be 0 maybe? and because of this the equipment is not visible? i don't know

**Comment by Rushor** [comment]
so eh no idea what causes this issue, all equip is set properly in db and we cannot see it

**Comment by ariel-** [comment]
I think it's because spawned at runtime creatures (instead of DB spawn) have equipmentID == 0, after e3d52990dd1e543baea6fed0c7e99359263e6452 this basically means that any creature spawned at runtime won't have any equipment, and must be added by the caller.

**Comment by Aokromes** [comment]
Test https://github.com/TrinityCore/TrinityCore/pull/16638

**Comment by lashia** [comment]
@Aokromes  yes it fixes
![wowscrnshot_022916_135702](https://cloud.githubusercontent.com/assets/8265622/13391198/692c275e-deec-11e5-95a6-fdbfb95f2af5.jpg)
![wowscrnshot_022916_135731](https://cloud.githubusercontent.com/assets/8265622/13391199/6931b822-deec-11e5-9da2-dc683930b5d5.jpg)

**Comment by Aokromes** [comment]
The commit causing this bug was reverted, anyone can confirm this bug is fixed?

**Comment by ariel-** [comment]
Confirmed fix, the issue can be closed 👍
