### ISSUE TITLE
[3.3.5] DB/Creature: Toxic Tunnel

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16490]
3.3.5 d1a185e3d5af

[Toxic Tunnel](http://www.wowhead.com/npc=16400/toxic-tunnel) spawn points are incorrect in the Grobb-Gluth tunnel. There should be a safe area at the gluth end of the pipe, and more poison near the middle.

Also, players should not be put in combat with the Toxic Tunnel NPC, and spells should not suffer knockback from its damage either.

**Comment by pete318** [comment]
Just to add to this. I definitely received the spell push_back and furthermore when hit from "behind" (there really shouldn't be a concept of that in this case but ok) I was dazed by the poison pools too.

**Comment by offl** [comment]
>There should be a safe area at the gluth end of the pipe, and more poison near the middle.

I found seven spawns [here](https://www.youtube.com/watch?v=sVBwL8Sh4VA) (vanilla) and [here](https://www.youtube.com/watch?v=T_WjzQKF8E4&feature=youtu.be&t=1973) (after 3.3.5a). In both movies I can't see something like "safe area" :Ь

**Comment by dr-j** [comment]
that reminds me I did naxx on retail the other day and somekind of slime spawned in tunnel and attack which I had never seen before even though had done it several times still p:

**Comment by offl** [comment]
> Toxic Tunnel spawn points are incorrect in the Grobb-Gluth tunnel. There should be a safe area at the gluth end of the pipe, and more poison near the middle.

Since the first issue(above) is not correct(as I said above on retail there's 7 spawns, on TC they are sniffed from retail), what about the second one(below)? It can be easily fixed.

> Also, players should not be put in combat with the Toxic Tunnel NPC, and spells should not suffer knockback from its damage either.
