### ISSUE TITLE
[3.3.5][6.x] DB/Spell: Missing condition on "Collect Data" (spell 44610) and "Bluff" (spell 44609)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16502]
3.3.5 d1a185e3d5af

[Collect Data](http://www.wowhead.com/spell=44610/collect-data) and [Bluff](http://www.wowhead.com/spell=44609/bluff) for quest [Lightning Infused Relics](http://www.wowhead.com/quest=11494/lightning-infused-relics) are missing a condition that makes them only castable when an eligible target is available.

**Comment by Saben65** [comment]
This fixes the issue for the Collect Data spells used in [Iron Rune Constructs and You: Collecting Data](http://www.wowhead.com/quest=11489/iron-rune-constructs-and-you-collecting-data) and [Lightning Infused Relics](http://www.wowhead.com/quest=11494).

```SQL
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(17, 0, 44550, 0, 0, 29, 0, 24820, 5, 0, 0, 0, 0, '', 'Allow spell Collect Data only on Iron Dwarf Relics'),
(17, 0, 44610, 0, 0, 29, 0, 24824, 5, 0, 0, 0, 0, '', 'Allow spell Collect Data only on Iron Dwarf Relics');
```

I am not sure how to check if the iron rune workers are suspicious of you to fix [Bluff](http://www.wowhead.com/spell=44609/bluff).

**Comment by Killyana** [comment]
There's already conditions for this 2 spells but it's on the effects only, so spells can be casted but nothing will happen, I remember CONDITION_SOURCE_TYPE_SPELL = 17 cannot  be used for this spells
https://github.com/TrinityCore/TrinityCore/issues/14269
