### ISSUE TITLE
[6.x] DB/Creature: Missing Flightpath gossip Turida Coldwind

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16508]
In Borean Tundra starting area the player is directed to Turida Coldwind to take a flight to Dalaran (http://www.wowhead.com/quest=29609/friends-in-dalaran) However no gossip to take any flight path is available.

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior level: 71
Zone: Borean Tundra
Wowhead link: 
http://www.wowhead.com/npc=25288/turida-coldwind

**Comment by tkrokli** [comment]
TrinityCore rev. f8de1ab354fc 2016-02-10 00:01:45 +0100 (6.x branch) (Win64, Release) TDB 6.03

Confirmed. [NPC 25288 Turida Coldwind](http://www.wowhead.com/npc=25288/turida-coldwind) does not offer any flight paths at all, only quest 29609.
The NPC has `SmartAI` as AIName, but only the attack script to summon the enraged wyverns.
Need to make Flight Path script lines for her. Have to research other FPs to find out more.

**Comment by tkrokli** [comment]
So, I have been able to make some progress by comparing info from 3.3.5 + 6.x when looking in both TDB 335.60 and TDB 6.03, particularly comparing with the gossip for Surristrasz on Amber Ledge.
This is a preliminar fix to make Turida Coldwind show the correct `npc_text` and `gossip_menu_option`:
```sql
-- NPC 25288 Turida Coldwind, update existing gossip menu option with missing values
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`= 53141, `option_id`= 4, `npc_option_npcflag`= 8192 WHERE `menu_id`= 13048;

-- insert missing gossip menu
DELETE FROM `gossip_menu` WHERE `entry` = 13048 AND `text_id`= 18324;
INSERT INTO `gossip_menu` (`entry`,`text_id`) VALUES (13048,18324);
```
This will make the gossip menu contain the top text "How can I help you?'", let the quest be presented in the middle and insert the missing FP gossip menu option below the quest name.

I have not yet found out how the Flight Path to Dalaran becomes available upon taking the quest, I am not sure if this is done via a spell cast, condition or SAI script lines.
