### ISSUE TITLE
[6.x] DB/Item:  Missing model/texture on Seaforium Depth Charge

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16507]
In the quest "Bury those cockroaches" the seaforium charges that the player can use are a signature blue/white checker box. According to wowhead, the buddle casts a spell which creates:
http://www.wowhead.com/npc=25401/seaforium-depth-charge

Which I assume is the item/object missing a model.

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior level: 71
Zone: Borean Tundra
Wowhead links: 
http://www.wowhead.com/quest=11608/bury-those-cockroaches
http://www.wowhead.com/item=34710/seaforium-depth-charge-bundle
http://www.wowhead.com/npc=25401/seaforium-depth-charge#screenshots

**Comment by Aokromes** [comment]
#16567 generic bug
