### ISSUE TITLE
3.3.5 Missing NPC in BC "Warcaller Sardon Truslice"

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16519]
TrinityCore rev. 4daaf69a3c39 2016-02-08 11:57:56 +0000 (HEAD branch) + all DB Updates

This NPC can be found in Shadowmoon Valley. 

http://www.wowhead.com/npc=21771/warcaller-sardon-truslice

**Comment by Aokromes** [comment]
http://i.imgur.com/AvNKUSe.png
cannot reproduce.

**Comment by Tauriella** [comment]
UPS sorry 
 the position was changed on liveserver
![wowscrnshot_020916_103403](https://cloud.githubusercontent.com/assets/10637389/12912482/2e9df352-cf19-11e5-8b44-47a4aef5c1db.jpg)

**Comment by Kittnz** [comment]
Indeed, he now walks back and forward and has some text script
