### ISSUE TITLE
[6.x] DB/Quest: Both faction's version of "Have They No Shame" offered

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16510]
The NPC Librarian Serrah (http://www.wowhead.com/npc=26110) currently offers two instances of the quest "Have They No Shame":

http://www.wowhead.com/quest=13094/have-they-no-shame  (Alliance version)
http://www.wowhead.com/quest=13095/have-they-no-shame  (Horde version)

As an orc I should not be helping the alliance right ;-)

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior level: 71
Zone: Borean Tundra

**Comment by Alastyr** [comment]
UPDATE quest_template SET AllowableRaces= 1 + 4 + 8 + 64 + 1024 + 2097152 + 16777216 WHERE id=13094;

UPDATE quest_template SET AllowableRaces= 2 + 16 + 32 + 128 + 256 + 512 + 33554432 WHERE id=13095;

AllowableRaces should be the new "RequiredRaces". I don't have TDB 6.x on my pc to check, but if these queries work, they are right.
