### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Mission: Plague This! (11332)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16517]
3.3.5 d1a185e3d5af

[Quest: Mission: Plague This!](http://www.wowhead.com/quest=11332/mission-plague-this)

Hitting the Plague Tanks with [Orehammer's Precision Bombs](http://www.wowhead.com/item=33634/orehammers-precision-bombs) does not grant credit (even though the tank shows the "hit" animation). Quest cannot be completed.

**Comment by tkrokli** [comment]
Orehammer's Precision Bombs : http://www.wowhead.com/item=33634/orehammers-precision-bombs
Spell used with that bomb item : http://www.wowhead.com/spell=43403/orehammers-precision-bombs
Effect : Trigger Missile (Mission: Plague This!: Orehammer's Precision Bombs Dummy)
Radius: 10 yards
http://www.wowhead.com/spell=43404/mission-plague-this-orehammers-precision-bombs-dummy

Maybe we need an entry in `spell_linked_spell` to connect spell 43403 with its effect, 43404 (not found)

**Comment by Rushor** [comment]
```sql
-- New Agamand Plague Tank Bunny SAI
SET @ENTRY := 24290;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,8,0,100,0,43404,0,0,0,11,43419,0,0,0,0,0,7,0,0,0,0,0,0,0,"New Agamand Plague Tank Bunny - On Spellhit 'Mission: Plague This!: Orehammer's Precision Bombs Dummy' - Cast 'Mission: Plague This!: Kill Credit'");

```

is already there, this need the castlebale_while_flying costum attribute
