### ISSUE TITLE
[3.3.5][6.x] DB/Item: Missing condition on "Sergeant's Flare", "Sergeant's Torch", "Sergeant's Machete"

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16518]
3.3.5 d1a185e3d5af

[Item: Sergeant's Flare](http://www.wowhead.com/item=33323/sergeants-flare) ([Quest: Towers of Certain Doom](http://www.wowhead.com/quest=11245/towers-of-certain-doom))
[Item: Sergeant's Torch](http://www.wowhead.com/item=33321/sergeants-torch) ([Quest: Burn Skorn, Burn!](http://www.wowhead.com/quest=11247/burn-skorn-burn))
[Item: Sergeant's Machete](http://www.wowhead.com/item=33310/the-sergeants-machete) ([Quest: Gruesome, But Necessary](http://www.wowhead.com/quest=11246/gruesome-but-necessary))
All three can be used despite no valid targets being available.

**Comment by dr-j** [comment]
This will be the case for horde quests as well but unless these hit target they dont give credit

as for towers of certain doom believe this is meant to be the case as it targets top of tower and you can see from videos you dont have to be in range of tower you just have to be near it and it targets top of tower automatically

**Comment by Treeston** [comment]
Yes, but it shouldn't be usable unless there's actually a tower in range that you can target.

**Comment by tkrokli** [comment]
This issue has in fact been solved in commit https://github.com/TrinityCore/TrinityCore/commit/ec6e7b618615be16e675d3c081531e5eaddaa89a (see link above). Conditions "can be used within 90 yards of Skorn Tower NW/E/SW/SE Bunny" was added for both [`Spell Brave's Flare` (49625)](http://www.wowhead.com/spell=49625/braves-flare) and [`Spell Sergeant's Flare` (43106) (actually Brave's Flare Effect)](http://www.wowhead.com/spell=43106/braves-flare-effect).
