### ISSUE TITLE
[3.3.5] DB/Quest: The Cleansing (11322/11317)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16521]
3.3.5 d1a185e3d5af

Quest: The Cleansing ([Alliance](http://www.wowhead.com/quest=11322/the-cleansing)/[Horde](http://www.wowhead.com/quest=11317/the-cleansing))

After the [Inner Turmoil](http://www.wowhead.com/npc=27959/your-inner-turmoil) is defeated, the player should be affected with the [Slow Fall](http://www.wowhead.com/spell=50237/slow-fall) buff triggered by [The Cleansing: Your Inner Tormoil's On Death Cast On Master](http://www.wowhead.com/spell=50238/the-cleansing-your-inner-turmoils-on-death-cast-on-master). This does not happen.

**Comment by dr-j** [comment]
in sniff on death first http://www.wowhead.com/spell=50223/the-cleansing-your-inner-turmoils-whisper-to-controller-on-death is cast and then http://www.wowhead.com/spell=50238/the-cleansing-your-inner-turmoils-on-death-cast-on-master  this is just script effect then triggers http://www.wowhead.com/spell=50237/slow-fall on player

Also http://www.wowhead.com/spell=50217/the-cleansing-script-effect-player-cast-mirror-image should be cast immedietly before http://www.wowhead.com/spell=50218/the-cleansing-your-inner-turmoils-mirror-image-aura

http://www.wowhead.com/spell=41054/copy-weapon and http://www.wowhead.com/spell=41054/copy-weapon is recast several times by http://www.wowhead.com/npc=27959/your-inner-turmoil during combat on tc is only cast once on just summoned.

**Comment by Saben65** [comment]
This fixes the slowfall issue.

```SQL
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(27959,0,10,0,61,0,100,0,0,0,0,0,75,50237,0,0,0,0,0,7,0,0,0,0,0,0,0,"Your Inner Turmoil - On Just Died - Add Aura 'Slow Fall' (No Repeat)");
```
