### ISSUE TITLE
[3.3.5] DB/Creature: Helpless Wintergarde Villager (27336)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16529]
3.3.5 d1a185e3d5af

After being rescued for [Quest: Flight of the Wintergarde Defender](http://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender), [Helpless Wintergarde Villager](http://www.wowhead.com/npc=27336/helpless-wintergarde-villager)s can be observed rapidly hopping through the air in order to return back to their malaise in the middle of scourge-infested fields.

I would recommend training them to avoid such suicidal action and despawn in the safety of Wintergarde Keep instead.

![Image](http://i.imgur.com/iUv9CG5.jpg)

**Comment by dr-j** [comment]
well these should despawn after 5 seconds of ride vehicle aura been removed but npc must be in phase 2 for this to happen.

Phase 2 is set when the rescue villager spell hits the npc.

The way npcs evade is to blame for this as it also resets event phase mask.

**Comment by Killyana** [comment]
Fixed.
