### ISSUE TITLE
[3.3.5] Core/Maps: Dying from fall damage at Icecrown Citadel's Light's Hammer

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#16530]
rev: https://github.com/TrinityCore/TrinityCore/commit/c68feba1e0aa514c954953921e09306326d1daa9

Walking in Icecrown Citadel instantly kills you for fall damage unless you got GM mode on.

**Comment by sirikfoll** [comment]
Happens with me too, but so far I only extracted new maps, not vmaps and mmaps. Could it be the problem?

**Comment by Nyeriah** [comment]
I have extracted both maps and vmaps even though only maps were required. Mmaps are only for pathing so I doubt they'd have something to do with it. So well in short, no, vmaps don't have much to do with it either.

**Comment by ccrs** [comment]
confirm e9db04a92cea645155dc57ee54e20cba9f1b79ed

**Comment by Shauren** [comment]
This means I will need to store the new data in greater precision (obviously implying new map extraction)

**Comment by Zedron** [comment]
Happening to me in undercity as well

**Comment by pete318** [comment]
In undercity in 3.3.5? As far as I can see there isn't any "min height" data on 3.3.5 undercity, or in fact in any of the zones (that I've checked so far) prior to Outland.

**Comment by ccrs** [comment]
can't confirm the undercity bug. Have you re-extracted maps?

**Comment by pete318** [comment]
There are also a few random spots in Sunstrider Isle you'll die too. They seem to be very isolated little spots though.

**Comment by Zedron** [comment]
> can't confirm the undercity bug. Have you re-extracted maps?

lol yes. fresh maps. if i were using old maps it wouldn't boot. just extracted after compiling. its not all of undercity, only specific spots. for example if you die & release to the graveyard, then resurrect yourself, and try to walk out of undercity it will kill you. Or if you teleport to undercity and use the elevator to go out, and head toward the exit of undercity, it will kill you.

**Comment by Shauren** [comment]
3.3.5 does not have MFBO chunk on maps 0/1 because no flying

**Comment by pete318** [comment]
Yet, 530 in the Belf/Spacegoat area still have these values.. And, in a few places in belfland at least it will get you killed.

**Comment by Shauren** [comment]
530 is a flyable map in general, only a few zones are hacked in using the virtualmap from worldmapsomething.dbc
