### ISSUE TITLE
[3.3.5] Quest: Escape from Silverbrook (12308)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16546]
3.3.5. b4b43d03b3f

[Quest: Escape from Silverbrook](http://www.wowhead.com/quest=12308)

Multiple issues:
- No pursuit. Two worgen spawn initially, but leash and reset before they reach the horse.
- If a creature engages the horse, it stops pathing.
- There's a waypoint that drops the horse below the ground (just after the jump over the lake).

**Comment by dr-j** [comment]
1) This seems to be random they do spawn but dont always attack spose depends on how often you use that soeed thing but some times when you do get more that attack than other times
2) Confirmed, and cant find a way of fixing this p:
3) Also confirmed wp go underground, this occurs if u dont jump over the streams p:

**Comment by Rushor** [comment]
point 2: related to https://github.com/TrinityCore/TrinityCore/issues/7450
