### ISSUE TITLE
[3.3.5][6.x] Core/Creature: Sumonned creatures immediately attacking pets even with REACT_PASSIVE

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#16547]
For example, on lich king fight, it happens with Drudge Ghouls(entry=37695) and Vile Spirits(entry=37799),
both of them are set to REACT_PASSIVE by lich king's JustSummoned hook.
But, if a player's pet(hunter's pet, shaman's totem, etc) is nearby, the npc will immediately start attack the pet.

What seems to happen:
[inline void CreatureUnitRelocationWorker(Creature* c, Unit* u)](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Grids/Notifiers/GridNotifiers.cpp#L129) is called before the JustSummoned hook set the creature to passive, so the creature begins to attack. Not sure why it prefers pets tho

hash b4b43d03b3fb
branch 3.3.5

**Comment by tkrokli** [comment]
I don't know if this is the case, but a brainstorming guess from me would be that it sounds like `REACT_PASSIVE` is valid (or checking) only for `TYPE_ID PLAYER` and not for pets / guardians.

**Comment by ccrs** [comment]
I can see no direct call to that worker. It seems like it's delayed so the onsummon hook will actually be called on the same update tick. Could you elaborate more pls?

**Comment by sirikfoll** [comment]
the callStack: https://gist.github.com/sirikfoll/fc06318a305495d8b093

**Comment by Treeston** [comment]
Does this still happen after d4184065b6d51b250ab08f35e88868cef631ed4b ?

**Comment by sirikfoll** [comment]
yes

**Comment by sirikfoll** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/6a339ed5c91244a02fac375101f9d0d04698328b
