### ISSUE TITLE
[3.3.5][6.x] Core/Vehicle: Vehicle accessorys threat

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#16542]
Threat generated by accessory must be transferred to the vehicles, but actually all accessory generate 0 threat, example Salvaged Siege Engine http://www.wowhead.com/npc=33060 use Salvaged Siege Turret http://www.wowhead.com/npc=33067 and the vehicle is supposed to be used as tank but as the turret threat is ignored it cannot be
Rev: d67e87733b2

**Comment by sirikfoll** [comment]
Kinda related to this issue, threat system needs to be reworked for vehicles, probably not valid for all vehicles, but a lot of them aren't supposed to even have a threatList, cannons are one example.
Antipersonnel Cannon(27894) in Strand of the Ancients often bug players in combat, problem which wouldn't exist if the cannon don't have a ThreatList.

**Comment by Rushor** [comment]
as already said in https://github.com/TrinityCore/TrinityCore/issues/15591

> hmm just found this https://github.com/TrinityCore/TrinityCore/blob/d5fb18d3c3a557acaf60a39be4ad5444969dd663/src/server/game/Entities/Unit/Unit.cpp#L10657

>we can add a flagextra for alle creatures which should not generate any thread
