### ISSUE TITLE
[3.3.5][6.x] Core/Mechanic: UnitScript hooks not called

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#16543]
https://github.com/TrinityCore/TrinityCore/commit/7be13b6fda29daf825e24bffe6095d0a987afce1
This commit made UnitScript useless when inherited by Player and Creature script classes.
The reason is that you cant switch the `addToScripts` to true for them so the hooks get called and if you would, it would cause the crash that was fixed.

I suggest either calling the PlayerScript and CreatureScript hooks separately (they are not called now at all) or make the UnitScript a completely separate entity that is not inherited.

Another possible improvement could be using `std::shared_ptr` or some redesign to remove the worries about the crash on script class deletion deletion that is the issue in the first place.
That happens in the situation that the commit fixed and when you inherit multiple script classes to one class - both crash on shutdown due to attempting to delete an instance of the script classes twice.

This affects both 3.3.5 and 6.x
Here is a related TC forum topic: https://community.trinitycore.org/topic/12333-help-onheal-event/

**Comment by jackpoz** [comment]
Isn't https://github.com/TrinityCore/TrinityCore/commit/7be13b6fda29daf825e24bffe6095d0a987afce1#diff-3d759b20335cedcebd74c619a5057557L1502 enough ? Or does it have no effect at all ?

**Comment by Rochet2** [comment]
> Isn't 7be13b6#diff-3d759b20335cedcebd74c619a5057557L1502 enough ? Or does it have no effect at all ?

Im not sure what you mean. The commit did fix the crash, but it also caused any UnitScript hooks inherited by other script classes not to be triggered since the commit causes the script pointer not to be in the UnitScript list that is used to call the hooks. (The addToScripts bool should actually be checked only on shutdown)

So the commit fixed a crash and had bad side effects.

> The addToScripts bool should actually be checked only on shutdown, not deleting the script if it's set to false

That should fix this issue, yeah - and would be quick to do I guess.
