### ISSUE TITLE
[3.3.5] Quest: Mounting Up (12414)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16556]
3.3.5. b4b43d03b3f

[Quest: Mounting Up](http://www.wowhead.com/quest=12414/mounting-up)

Taming a [Highland Mustang](http://www.wowhead.com/npc=26472/highland-mustang) that stands alone works fine, apart from minor AI quirks (it will always path back to spawn after you tame it before becoming controllable).

Taming a [Highland Mustang](http://www.wowhead.com/npc=26472/highland-mustang) that is part of a roaming pack is impossible, as the pack AI will override the "move towards player" command and prevent it from ever being mounted.

**Comment by Kittnz** [comment]
This is more of a formation issue, if one of the mustangs are pulled they get removed from group and a new leader (if it is the leader of the pack) will be assigned. Not the case now.

**Comment by offl** [comment]
[Looks like they just reset the whole formation](https://youtu.be/2n8zmkp-nR4?t=117).

**Comment by Kittnz** [comment]
And they add a new horse to take it's place

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21731
