### ISSUE TITLE
[3.3.5] Creature: Fallen Earthen Warrior (26335)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16559]
3.3.5. b4b43d03b3f

[Creature: Fallen Earthen Warrior](http://www.wowhead.com/npc=26335/fallen-earthen-warrior)

He is not actually, y'know, fallen. He's alive. Which he should not be.
Execute with extreme prejudice and permanence, please.

**Comment by Rushor** [comment]
> Execute with extreme prejudice and permanence, please.

he will be reped

**Comment by tkrokli** [comment]
Are you sure about that? The pages http://wow.gamepedia.com/Fallen_Earthen_Warrior and
http://wowwiki.wikia.com/wiki/Fallen_Earthen_Warrior seem to disagree with your conclusion.

**Comment by Treeston** [comment]
Well, he should at least fallen. Y'know, lying on the ground. Would probably be a good idea to double-check retail.

**Comment by tkrokli** [comment]
OK, I agree with the statement that he should be lying on the ground, as in "inches away from death".
Would be a good idea to check sniffs for the correct `npcflags` etc. to get them correct this time around.
