### ISSUE TITLE
[6.x] Core: Missing model of object/npc created by player

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16567]
For the quest The Power of the Elements the item http://www.wowhead.com/item=35281/windsoul-totem is provided.

This casts a spell which summons: http://www.wowhead.com/npc=25987/windsoul-totem

Which appears as a blue/white checkered box: prntscr.com/a1z69q
rubic cube.

I found some previous work on this quest @ https://github.com/TrinityCore/TrinityCore/issues/6479

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior
Zone: Borean Tundra

**Comment by aquadeus** [comment]
this is fixed already
