### ISSUE TITLE
[6.x] DB/Quest/Spell: Scouting the Sinkholes (Quest(s) 11684 / 11713, spell 45853)

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16564]
For the quest Scouting the Sinkholes (http://www.wowhead.com/quest=11684/scouting-the-sinkholes)

The quest item casts the spell http://www.wowhead.com/spell=45853/survey-sinkholes
But casting is blocked as the player is not recognized as being at the right location.
Given error message is: "You must be closer to a sinkhole to use your map."

The three sinkholes are around (some ~10-15 yard circle around the following points):
Map 571 Zone 3537 Area 4035 
X: 3488.18 Y: 4514.69 Z: -20.73
X: 3647.85 Y: 4552.59 Z: -20.73
X: 3647.80 Y: 4746.04 Z: -20.73

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior level: 73
Zone: Borean Tundra

**Comment by Rushor** [comment]
spellfocus gameobjects missing?

**Comment by KarrokDC** [comment]
I'll recheck right now

**Comment by illfated** [comment]
TrinityCore rev. bc1f456125c1 2018-11-14 22:57:06 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

In 3.3.5, in addition to only working from one of the ledges around the sinkholes,
there is also the spell issue "**You have no target.**", even if you are on a location
where it is possible to use the map item and start casting.

**Comment by genion18** [comment]
Near on or in the Sinkhole say to me "You must be closer to a sinkhole to use your map."

https://www.wowhead.com/quest=11684/scouting-the-sinkholes

https://www.youtube.com/watch?v=VrVctJUktEY

https://github.com/TrinityCore/TrinityCore/issues/2028
https://github.com/TrinityCore/TrinityCore/issues/10226
https://github.com/TrinityCore/TrinityCore/issues/10225

This quest is not completable in this moment 3.3.5 core 1c2b1cbba82fcd523ccd0cceafe532f35d71dcc1
![WoWScrnShot_081119_223019](https://user-images.githubusercontent.com/321832/62839288-766deb00-bc88-11e9-8a0c-3f230a20be76.jpg)

**Comment by Aokromes** [comment]
read https://github.com/TrinityCore/TrinityCore/issues/16564#issuecomment-182983321

**Comment by genion18** [comment]
this fix this problem and is blizzlike at the video.

testet on 3.3.5

> DELETE FROM `gossip_menu_option` WHERE `guid` IN (78,79,80);
> INSERT INTO `creature` VALUES ('78', '25664', '571', '0', '0', '1', '1', '0', '0', '3487.98', '4516.90', '8.00', '2.18166', '120', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
> INSERT INTO `creature` VALUES ('79', '25665', '571', '0', '0', '1', '1', '0', '0', '3645.95', '4551.1', '8.00', '0.715585', '120', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');
> INSERT INTO `creature` VALUES ('80', '25666', '571', '0', '0', '1', '1', '0', '0', '3649.17', '4744.34', '8.00', '0.890118', '120', '0', '0', '1', '0', '0', '0', '0', '0', '', '0');

**Comment by Aokromes** [comment]
no it's not.

**Comment by illfated** [comment]
I am pretty sure we can remove "6.x" from the issue title now ...  BTW, is this actually an issue with the TC source?  ... or do too many people simply not realize that the quest can be completed if they only find the correct spot with X + Y coordinates
```cpp
{ 3487.675, 4516.643 }
{ 3645.955, 4551.105 }
{ 3649.167, 4744.338 }
```
(coordinates suggested by Aokromes above)

**Comment by Aokromes** [comment]
maybe proper fix is https://github.com/Ovahlord/TrinityCore/commit/bcd0b653d776dc081c9eb5ed06d5c35053da8494

**Comment by illfated** [comment]
Yes, with the "invisible cow" spell focus `32.0 f` above the sinkhole, players currently have to find a spot where the distance is max `30.0 f` to the spell focus, which in many cases can be difficult.

**Comment by Aokromes** [comment]
028db84
