### ISSUE TITLE
[3.3.5] Creature: Surveyor Orlond (26514)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16566]
3.3.5. b4b43d03b3f

[Creature: Surveyor Orlond](http://www.wowhead.com/npc=26514/surveyor-orlond)
Should be dead, is not dead. Extermination requested.

**Comment by Rushor** [comment]
mentally, he's dead since 6 years :D

**Comment by Saben65** [comment]
Dude really doesn't wanna die. Setting his dynamic flags to 32 result in him appearing dead, but he is still standing. What a champ.

**Comment by tkrokli** [comment]
I know changing the content in `creature_template` is not allowed without being backed up by sniff, but this is the only way I could make the NPC show up as dead and lay face down on the ground:
```sql
UPDATE `creature_template`
 SET `unit_flags`= `unit_flags`|536870912|32768, -- UNIT_FLAG_UNK_29 + UNIT_FLAG_UNK_15
 `unit_flags2`= `unit_flags2`|1,                 -- UNIT_FLAG2_FEIGN_DEATH
 `dynamicflags`= 32,                             -- UNIT_DYNFLAG_DEAD
 `type_flags`= 128                               -- CREATURE_TYPEFLAGS_DEAD_INTERACT
WHERE `entry`= 26514;
```
Note: I included `type_flags`= 128 because I suppose it will be needed to be able to handle the quests.

**Comment by Aokromes** [comment]
This is valid?

**Comment by Aokromes** [comment]
From sniffs:

```
DELETE FROM creature_template_addon WHERE `entry` IN (26514);
INSERT INTO creature_template_addon (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(26514, 0, 0, 0, 1, 0, '29266');

**Comment by Killyana** [comment]
Only the creature_template_addon is valid, it could bu pushed.

**Comment by Aokromes** [comment]
Type Flags: CanInteractWhileDead (128)
[35] UNIT_DYNAMIC_FLAGS: 32/4.484155E-44
[35] UNIT_FIELD_FLAGS: 537133824/1.118183E-19
[35] UNIT_FIELD_FLAGS_2: 2049/2.871261E-42

**Comment by Killyana** [comment]
This flags comes from the aura, try IG to look to this flags with and without the aura 29266

**Comment by tkrokli** [comment]
TrinityCore rev. bc94bbb65197 2016-06-15 15:57:51 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 plus updates up to and including `2016_06_15_10_world.sql`

He has no auras from earlier, so using the in-game command `.aura 29266` turns him completely dead, permanent (no hp, no power and lying flat on the ground. Testing if this also works from DB. BRB.
