### ISSUE TITLE
Shade of akama

### ISSUE THREAD

**Issue by susumakusu** [TrinityCore/TrinityCore#16563]
TrinityCore rev. 93889ca60ef2 2016-01-06 16:30:03 +0200 (master branch) (Unix, Release) (worldserver-daemon)

When you clean the room and talk to akama he starts to move. When he starts the "duel-energy" 
mobs are spawned and start attacking akama, exactly:

Ashtongue Defender(id:23216)
Ashtongue Rogue(id:23216)
Ashtongue Elementalist(id:23523)
Ashtongue Spiritbinder(id:23524)

Ashtongue Defender are targeteable and can be killed but the other 3 cant be killed. Evading all the time. If you defeat shade of akama, akama stay in combat and cant move.

Sorry my bad english.

**Comment by Rushor** [comment]
move the report to https://github.com/TrinityCore/TrinityCore/issues/10430

**Comment by susumakusu** [comment]
Sorry for the rev I put the rev of my server where i am testing ELUNA. Sorry, can you reopen it?

**Comment by Aokromes** [comment]
We don't support ELUNA.

**Comment by susumakusu** [comment]
Is not ELUNA, I put the rev of my other server, I confused Server.log It is Trinity Core "vanille"

**Comment by Kittnz** [comment]
This is very old core, update please.
