### ISSUE TITLE
[6.x] Item/? Object/Container z-fighting in The Geyser Fields (4035)

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16562]
In the area The Geyser Fields (area 4035) in the Borean Tundra, while doing quest Cleaning up the pools (http://www.wowhead.com/quest=11906/cleaning-up-the-pools) the player is asked to retrieve:

http://www.wowhead.com/item=34972/fizzcrank-spare-parts#contained-in-object

The containers of the objects are z-fighting with the ground causing them to seemingly appearing and disapearing as you get closer.

Screencaps:
http://prntscr.com/a1yd2n      Ah look a quest item container
http://prntscr.com/a1yddf       ohh now it's gone ;-)

I wasn't sure where this type of bug would fall under, but either something in the maps or just the object placement.

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior level: 73
Zone: Borean Tundra

**Comment by Faq** [comment]
Not occurs anymore on 8128bb97dbf4b5ba7cb0b624ce7cf7428d7bdc63

**Comment by illfated** [comment]
@Faq : Please note that the original issue is about the **master** branch. If this was happening to the 3.3.5 branch too earlier, it would be a good idea to find out where the issue was solved in 3.3.5 and check if that commit has been cherry-picked yet from the 3.3.5 branch to the [master] branch.
