### ISSUE TITLE
DB/Quest: Defeat the Gearmaster (11909)

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16569]
On this quest, reading the book (http://www.wowhead.com/object=190335/the-gearmasters-manual) does not complete the quest part "The Gearmaster's Manual researched" for quest http://www.wowhead.com/quest=11909/defeat-the-gearmaster

There is a creature (27995) named [The Gearmaster's Manual Researched Kill Credit Bunny] which seems to be involved.

Reading the book does trigger the gearmaster to spawn correctly.

TrinityCore: 6c48066a6f24ccbcb4aa527d5241a411691e3173
Trinity DB : d00ba9587d5d604a60827de2f49a74a1f7fd3455 (TDB 6.03)

Orc warrior
Zone: Borean Tundra

**Comment by nubqt** [comment]
**Forensics:** `event_scripts` was missing [the kill credit](http://www.wowhead.com/npc=27995) for when the Player clicks the book.

**Suggested fix:**

```sql
SET @OBJECT = 17209;
SET @COMMAND_KILL_CREDIT = 8;
SET @KILL_CREDIT_BUNNY = 27995;
INSERT INTO `event_scripts` VALUES ( @OBJECT, 0, @COMMAND_KILL_CREDIT, @KILL_CREDIT_BUNNY, 0, 0, 0, 0, 0, 0 );
```

Please test and confirm suggestion.

<img width="1378" alt="screen shot 2017-11-13 at 6 00 33 pm" src="https://user-images.githubusercontent.com/33535711/32753884-a31873be-c89c-11e7-8051-5d24b795b7b8.png">

<img width="1378" alt="screen shot 2017-11-13 at 6 00 40 pm" src="https://user-images.githubusercontent.com/33535711/32753893-aa92ad80-c89c-11e7-876a-eb9a8bc1508a.png">

**Comment by tkrokli** [comment]
Currently existing data for `id` 17209 in `event_scripts`
```sql
SELECT * FROM `event_scripts` WHERE `id`=17209;
```
```
   id   delay  command  datalong  datalong2  dataint        x        y        z       o
-----  ------  -------  --------  ---------  -------  -------  -------  -------  ------
17209       3       10     25834    3000000        0  4004.18  4850.36  26.0508  2.3911
```

TC codestyle suggests the following format for your query (given that `id` is not unique):
```sql
SET @GOBJECT := 17209;
SET @COMMAND_KILL_CREDIT := 8;
SET @KILL_CREDIT_BUNNY := 27995;

DELETE FROM `event_scripts` WHERE `id`= @GOBJECT AND `command`= @COMMAND_KILL_CREDIT AND `datalong`= @KILL_CREDIT_BUNNY;
INSERT INTO `event_scripts` (`id`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(@GOBJECT, 0, @COMMAND_KILL_CREDIT, @KILL_CREDIT_BUNNY, 0, 0, 0, 0, 0, 0 );
```
Then again, I don't know that table well enough to assess if your SQL should replace the existing data or if sniffs are required as proof.

**Comment by nubqt** [comment]
I checked the table structure beforehand and it does not have a primary key nor a unique key. Having two records with the same id is thus allowed in that table.

Moreover, both records should stay because the existing data (notice it has a different command--'10'--which is equivalent to TEMP_SUMMON_CREATURE) contains the script that summons the [Gearmaster Mechazod](http://www.wowhead.com/npc=25834/gearmaster-mechazod). This behavior is intended as part of the roleplaying and as part of the quest objective. It is also working properly. Removing that record would break the quest.
