### ISSUE TITLE
[3.3.5] Quest: Put on Your Best Face for Loken (12185)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16576]
3.3.5 8e6fb3b1c50f

[Quest: Put on Your Best Face for Loken](http://www.wowhead.com/quest=12185/put-on-your-best-face-for-loken)

The [Image of Loken](http://www.wowhead.com/npc=27212/image-of-loken) should not be attackable by players.

**Comment by dr-j** [comment]
correct unit flags should be 33555200
~~~sql
UPDATE `creature_template` SET `unit_flags`=33555200 WHERE  `entry`=27212;

**Comment by Saben65** [comment]
Looks good to me.
