### ISSUE TITLE
[3.3.5] Quest: Filling the Cages (11984)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16579]
3.3.5 8e6fb3b1c50f

[Quest: Filling the Cages](http://www.wowhead.com/quest=11984/filling-the-cages)
[Budd](http://www.wowhead.com/npc=32663/budd) does not have the ability required to complete the quest.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6580
