### ISSUE TITLE
[3.3.5] Quest: Chill Out, Mon (12137)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16574]
3.3.5 8e6fb3b1c50f

[Quest: Chill Out, Mon](http://www.wowhead.com/quest=12137/chill-out-mon)
The [Gan'jo's Chest](http://www.wowhead.com/object=188518/ganjos-chest) containing the [Snow of Eternal Slumber](http://www.wowhead.com/item=36859/snow-of-eternal-slumber) for the quest is spawned, but not visible (not even for a GM character).

**Comment by tkrokli** [comment]
657adc270a32 2016-02-15 00:31:39 +0100 (3.3.5 branch) (Win64, Release) / TDB 335.60 + updates
```sql
SELECT * FROM `gameobject_template` WHERE `entry`= 188518;
```
```
 entry    type  displayId  name            IconName  castBarCaption  unk1    faction   flags    size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  AIName  ScriptName  VerifiedBuild
------  ------  ---------  --------------  --------  --------------  ------  -------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ----------  -------------
188518       3       5744  Gan'jo's Chest                                          0       4     1.3    1690   23885       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
```
This gameobject is visible and can be interacted with, but only with GM ON, not in normal mode.
Either there is something wrong with the current `flags` value (4) or perhaps conditions or script?

**Comment by Treeston** [comment]
Still happening in latest rev.

**Comment by Killyana** [comment]
Cannot reproduce on  rev. d7e47de264a2  player or gm the gob is always visible.

**Comment by Treeston** [comment]
Hmm, it's broken on my server branch but that's got a bunch of PRs merged.

**Comment by offl** [comment]
Cannot reproduce in aba07047a05f
