### ISSUE TITLE
[3.3.5] Problem with creature orientation after cast

### ISSUE THREAD

**Issue by Tonghost** [TrinityCore/TrinityCore#16572]
Sunreaver Guardian Mage (Creature 29255) does not restore orientation after cast "Trespasser!" (Spell 54029)

Also for some reason is only one guard works (shown in my screenshot) and sometimes he cast spell twice.

55100e57

<img src=https://i.gyazo.com/d402c11b28ea35a15142152f1bf766f5.jpg>

**Comment by Kittnz** [comment]
Confirmed
8706ba2ca952137c23a9168a0b671c31bab0f97d

**Comment by tkrokli** [comment]
TrinityCore rev. 657adc270a32 2016-02-15 00:31:39 +0100 (3.3.5 branch) (Win64, Release)

Confirmed, the guard stops in its last casting orientation and does not reset to the initial orientation.
It is very easy to reproduce, as well as it is possible to achieve different orientations, depending on
which direction and distance to this guard your character enters their trigger zone.

**Comment by Killyana** [comment]
This happen also to Kologarn on spawn or reset.

**Comment by Nawuko** [comment]
@Treeston has currently a branch to fix some problems with spell focus @ _https://github.com/Treeston/TrinityCore/tree/3.3.5-spellfacingagainagainagain_
Maybe this solves the problem i didnt tested with Kologarn but the Sunreaver Guardian Mage is fixed with the branch and a little fix i wrote into one of his commits. :)

**Comment by tkrokli** [comment]
Thanks for the info. I was wondering if it had something to do with the script [`npc_mageguard_dalaran` (#L118)](https://github.com/TrinityCore/TrinityCore/blob/8d09065525139d4e99d5439978f3c1c95aeb2428/src/server/scripts/Northrend/zone_dalaran.cpp#L118). I guess it is not the script itself which causes the issue, but other code called by the script.

**Comment by Nawuko** [comment]
@tkrokli Not it hasnt, SetOrientation only sets the server side orientation so this dosent affect anything. But this line can be removed if the fix from @Treeston gets merged

**Comment by Killyana** [comment]
Maybe a related issue with Ormorok and its spikes, the 4 are casted on the same orientation always.

**Comment by Tonghost** [comment]
Problem with dalaran mageguards still relevant 190fdfdf63c

Maybe @ariel- can fix this
