### ISSUE TITLE
[CRASH] boss_gothik::boss_gothikAI::OpenGate

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#16575]
Today I had the following crash:

http://pastebin.com/Dm8Rcn4q

23961001b5b14d9672dd2c32293f6d75f615caeb

3.3.5 branch

**Comment by Shauren** [comment]
Crashing code path: OpenGate -> minion handling action ACTION_GATE_OPENED but no valid target is found -> evade -> boss evade -> CreatureAI::EnterEvadeMode() -> boss_gothikAI::Reset() -> _Reset() -> summnons.DespawnAll() -> iterator back in OpenGate is invalidated.

**Comment by Treeston** [comment]
:+1: for good crashdump. On it.

**Comment by Treeston** [comment]
Finding it hard to even get a repro on this one...

It requires Gothik to have a non-empty aggro table, but the spawned minion to not find any target in the entire map.

**Comment by Treeston** [comment]
Stealthed rogue somewhere in the combat area will do it.

**Comment by Treeston** [comment]
Fixed.

**Comment by Kittnz** [comment]
Quick work there @Treeston ! =D

**Comment by Pirricli** [comment]
Thank you @Treeston
