### ISSUE TITLE
[3.3.5] Creature: Invisible Stalker Grizzly Hills (27452)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16578]
3.3.5 8e6fb3b1c50f

[Invisible Stalker Grizzly Hills](http://www.wowhead.com/npc=27452/invisible-stalker-grizzly-hills) is visible.

**Comment by Killyana** [comment]
``` sql
UPDATE `creature` SET `modelid`=0 WHERE `id`=27452;

**Comment by Kodekc** [comment]
UPDATE `creature` SET `modelid`=11686 WHERE `id`=27452;

**Comment by Kodekc** [comment]
```sql
UPDATE `creature_template` SET `modelid1`='11686', `modelid2`='0', `flags_extra`='130' WHERE  `entry`=27452;
UPDATE `creature` SET `modelid`=0 WHERE `id`=27452;
```
The problem is the NPC model 1126. 
Required edit creature_template. 
I believe that we need to add a flag CREATURE_FLAG_EXTRA_CIVILIAN

**Comment by Treeston** [comment]
Why would civilian flag be needed?

**Comment by Kodekc** [comment]
@Treeston, to creature does not aggro (ignore faction/reputation hostility). Or am I wrong?

**Comment by Treeston** [comment]
Trigger flag does that already.

**Comment by Kodekc** [comment]
@Treeston, Thanks for the clarification

**Comment by Aokromes** [comment]
Modify creature_template without sniffs is hack.
Test https://github.com/TrinityCore/TrinityCore/issues/16578#issuecomment-183097633 before sugesting that.

**Comment by Killyana** [comment]
Setting the model to 0 fix the problem, why are talking about civilian flag and creature_template ?

**Comment by Treeston** [comment]
Because apparently some people believe that deleting their comments from an ongoing conversation is helpful.
