### ISSUE TITLE
[3.3.5] Divine Shield/Iceblock removing Essence of the Blood Queen

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#16589]
rev https://github.com/TrinityCore/TrinityCore/commit/a23ccc1b83ded39501d690e288be49be8f32b539

Using Iceblock or Divine Shield removes Blood Queen Lana'thel's Essence of the Blood Queen

http://www.wowhead.com/spell=70867/essence-of-the-blood-queen

**Comment by Treeston** [comment]
Probably related to changes in d67e87733b2e258dc4f5613ee7fa40445e3b215f
