### ISSUE TITLE
[3.3.5] Quest: Going Bearback (12851)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16588]
3.3.5 8e6fb3b1c50f

[Quest: Going Bearback](http://www.wowhead.com/quest=12851/going-bearback)
Icefang has the spell [Icefang Begin Pathing](http://www.wowhead.com/spell=54788/icefang-begin-pathing) on his hotbar, which he shouldn't have.

**Comment by Treeston** [comment]
Split off the "disguise dropping" issues into separate issue #16591 as it occurs with multiple different quests.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/589fed54d15c9c769ef22c0b98dcaed68d8383be
```sql
UPDATE `creature_template` SET `spell1`=54897, `spell2`=54907, `spell3`=54788 WHERE `entry`=29602; -- Icefang
 -- Last spell (spell3) shouldn't be show to the client, core implementation of vehicle spells needs to change.
```

**Comment by offl** [comment]
It's not Feedback-PatchFix, it's just a quote from commit with more information about the issue
