### ISSUE TITLE
[3.3.5] Quest: The Jig is Up (11471)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16580]
3.3.5 8e6fb3b1c50f

[Quest: The Jig is Up](http://www.wowhead.com/quest=11471/the-jig-is-up)

After ["Mad" Jonah Sterling](http://www.wowhead.com/npc=24742/mad-jonah-sterling) is "eaten" by [Hozzer](http://www.wowhead.com/npc=24547/hozzer), he does not die, instead evading back to the top of the stairs. Afterwards, he never leaves evade mode, instead walking around at quarter health and evading any other damage, leaving this quest uncompleteable by more than one group per restart.

**Comment by dr-j** [comment]
strange last action in the timed action list is to despawn "Mad" Jonah Sterling

**Comment by Treeston** [comment]
He probably evades before getting there.

**Comment by dr-j** [comment]
Actually cannot reproduce works as long as you stay there if you test work as intended,

evade is called by timed action list to force npc to leave combat after disabling hp regen, evade does not stop timed action list from working and as long as player present or grid loaded will work as intended.

I suspect that this is grid issue due to grid been unloaded before timed action list completed.

**Comment by offl** [comment]
> Also wowhead.com/npc=24547/balours must be moved here with sleep emote or aura: X: -46.246674 Y: -3392.340820 Z: -9.330437 Orientation: 3.475807

From https://github.com/TrinityCore/TrinityCore/issues/11157#issuecomment-100333286

**Comment by dr-j** [comment]
Try this 

~~~sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=2474200 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(2474200, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Set HP Regen off'),
(2474200, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Disable Autoattack'),
(2474200, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Disable Combat Movement'),
(2474200, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Say Line 1'),
(2474200, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 53, 1, 24742, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Start WP'),
(2474200, 9, 5, 0, 0, 0, 100, 0, 7000, 7000, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Say Line 2'),
(2474200, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 85, 44458, 1, 0, 0, 0, 0, 19, 24547, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Invoker Cast Hozzer Feeds'),
(2474200, 9, 7, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 1, 0, 0, 0, 0, 0, 0, 19, 24547, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Say Line 1 - Hozzer'),
(2474200, 9, 8, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '"Mad" Jonah Sterling - Script - Despawn');
~~~

This is removing the evade and making npc stop combat by other means player will remain in combat until '"Mad" Jonah Sterling despawns though

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23483
