### ISSUE TITLE
[3.3.5]Core: Creature equipement

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#16587]
After this commit https://github.com/Tonghost/TrinityCore/commit/cc3ae640a48417aae31eac8828842ab50099069b all summoned npcs doesn't load equipment, example Jaraxus.
The correct behavior must:
- If the npc is a spawn, the equipment is set or not according to equipment_id on creature table (this works correctly)
- If the npc is summoned (not a spawn) equipment must always be set, And if the npc must spawn without equipment it must be handled by the script.
rev. ebf6c7188369

**Comment by Killyana** [comment]
@Tonghost can you take a look to this issue?

**Comment by w5860363** [comment]
confirm core:https://github.com/TrinityCore/TrinityCore/commit/47f628353b5cf14dd8dc9132988546a76b4aab70

**Comment by Treeston** [comment]
Yeah, I was wondering what was up with that (Razuvious adds).

**Comment by DDuarte** [comment]
"Fixed" by 5aae01986f506b160dbd5dc08aa7e6f3fec72342
Re-opened the old issue

**Comment by Aokromes** [comment]
reverted the commit cause of this bug https://git.io/vrHbx
