### ISSUE TITLE
[3.3.5] Core/Spell: Blink in slope

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16595]
core:https://github.com/TrinityCore/TrinityCore/commit/ff45a422c5e525c4d9465e91200803ffa95700d2
DB:TDB60
maps:1.8 version
update:2016_02_12_00_world.sql

Encountered more than 20 yards from the magic effect of the slope, will be applied to the failure of the law

**Comment by Aokromes** [comment]
Test https://github.com/TrinityCore/TrinityCore/pull/15796

**Comment by Killyana** [comment]
Dup #20006
