### ISSUE TITLE
close

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16597]
close

**Comment by lashia** [comment]
with GM on npc id is 28393

**Comment by tkrokli** [comment]
That creature corpse is supposed to be in the back of the training hall area, behind Instructor Razuvious (you will see other similar creature corpses there). All these corpses are supposed to be part of a necromancy event (not yet implemented) which is where the DK player characters and initiates come from. The creature corpse you are referring to was supposedly a corpse that should float on top of one of the necromancers' reanimation spells. This has been mentioned before, I think?

**Comment by tkrokli** [comment]
@lashia By the way: unless your browser is too bugged with adware/malware, you should be able to close this issue yourself. There should be a [Close issue] button below these comments.
