### ISSUE TITLE
[3.3.5] DB/Quest: Lok'lira's Bargain" dropping after completing quests

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16591]
3.3.5 8e6fb3b1c50f

The SoH chain disguise [Lok'lira's Bargain](http://www.wowhead.com/spell=72914/lokliras-bargain) is not applied correctly if entering from the east (the Valley of Ancient Winters subzone) without first going through Brunnhildar village.

In addition, after handing in some of the quests in the SoH chain, the [Lok'lira's Bargain](http://www.wowhead.com/spell=72914/lokliras-bargain) disguise drops, and you need to leave and re-enter the area to re-apply it.

I originally encountered this for [Quest: Going Bearback](http://www.wowhead.com/quest=12851/going-bearback), but it also happens with [Quest: Cold Hearted]([Quest: Going Bearback]%28http://www.wowhead.com/quest=12851/going-bearback%29), so I am actually believing this to be a core issue.

Other quests affected include:
[Quest: Deemed Worthy](http://www.wowhead.com/quest=13063/deemed-worthy)

**Comment by w5860363** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3bc3b67a8fae059e1019446b09882dfa7fcd11a0/sql/old/3.3.5a/TDB51_to_TDB52_updates/world/2013_07_05_02_world_QuestchainSOH.sql

This task is tied to the task chain 12900

**Comment by tkrokli** [comment]
Possibly related to the Proto Drake vehicle problem in #11754 ([3.3.5][NPC/Vehicle] Freed Proto Drake). Conditions for zones the Freed Proto Drake can be used in will only work if the script is removed
(ref Killyana).

**Comment by dr-j** [comment]
Dont think this is a core issue as by looking at spell_area for spell 72914 reveals this 

spell,area,quest_start,quest_end,aura_spell,racemask,gender,autocast,quest_start_status,quest_end_status
72914,4535,12905,0,0,0,2,1,74,11
72914,4425,12905,0,0,0,2,1,74,11
72914,4422,12905,0,0,0,2,1,74,11
72914,4437,12921,13063,0,0,2,1,74,11
72914,4438,12856,12856,0,0,2,1,74,11

notice how the first 3 entries have no quest end
the last two have quest end of quests http://www.wowhead.com/quest=13063/deemed-worthy and http://www.wowhead.com/quest=12856/cold-hearted

**Comment by tkrokli** [comment]
OK, so this is how it looks in a formatted output:
```sql
SELECT * FROM `spell_area` WHERE `spell`= 72914 ORDER BY `quest_start`;
```
```
spell    area  quest_start  quest_end  aura_spell  racemask  gender  autocast  quest_start_status  quest_end_status
-----  ------  -----------  ---------  ----------  --------  ------  --------  ------------------  ------------------
72914    4438        12856      12856           0         0       2         1                  74                11
72914    4422        12905          0           0         0       2         1                  74                11
72914    4425        12905          0           0         0       2         1                  74                11
72914    4535        12905          0           0         0       2         1                  74                11
72914    4437        12921      13063           0         0       2         1                  74                11
```
Is it possible that we need quest IDs added to `quest_end` to solve this issue?

**Comment by dr-j** [comment]
not sure but it those two quests where quest end is specified where aura gets removed until area update
needs confirmation but have suspicions that aura should not be removed on quest end ie there should be no quest end for any of the areas involved especially when it causes aura to be removed between quests and adjactant areas still have it permamently

**Comment by Treeston** [comment]
Can you check which areas those are. Some areas should stop having the disguise after some point (SoH camp and surrounding area for example).

It's possible that the core simply doesn't check if the quest_end entry matches current area before removing the disguise?

**Comment by Killyana** [comment]
This issue is new, it happens also with phasing spell, months ago I tested the hole Sons of hodir quest chain and this issue doesn't happen.

**Comment by dr-j** [comment]
I think it depends on exactly where you are standing when you turn quest in since quest giver is right on edge of two areas.

Maybe spells should not be removed as soon as player leaves area believe on retail it requires you to be out of area for a few seconds before aura actually gets removed or does not get removed as soon as area changes anyway

**Comment by dr-j** [comment]
and if you want to confirm this have seen with a lot of other auras before when moving between areas but with sample satisfaction debuff from love is in the air on tc it gets removed as soon as you leave city on retail this is not instant ie does not get removed for like 5 seconds after leaving city but idk if this is time based or distance based but have noticed that with a whole load of auras that they dont get removed as soon as you change area.

**Comment by Killyana** [comment]
Fixed.
