### ISSUE TITLE
[3.3.5] Core: InstanceSaveManager::_ResetOrWarnAll cause worldserver frozen

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#16605]
After rev. 62aff401f687b56d720a320778950e82b65fbd8b
It implement handling of CMSG_SET_SAVED_INSTANCE_EXTEND.
I kill a boss in Icecrown Citadel, and I used ".debug raidreset 631" command, I found a deadlock in the mysql transaction  from InstanceSaveManager::_ResetOrWarnAll.
It will cause worldserver frozen sometimes.

This is the SQL debug log:

`[1 ms] SQL: START TRANSACTION`
`[1 ms] SQL(p): SELECT guid FROM character_instance WHERE instance = 2 and permanent = 1`
`[1 ms] SQL(p): UPDATE instance_reset SET resettime = 1455501600 WHERE mapid = 631 AND difficulty = 0`
`[1 ms] SQL: START TRANSACTION`
`[2 ms] SQL(p): UPDATE instance_reset SET resettime = 1455501600 WHERE mapid = 631 AND difficulty = 1`
`[27 ms] SQL(p): DELETE FROM character_instance USING character_instance LEFT JOIN instance ON character_instance.instance = id WHERE (extendState = 0 or permanent = 0) and map = 631 and difficulty = 0`
`[21 ms] SQL(p): DELETE FROM character_instance USING character_instance LEFT JOIN instance ON character_instance.instance = id WHERE (extendState = 0 or permanent = 0) and map = 631 and difficulty = 1`
`[27 ms] SQL(p): SELECT guid FROM character_instance WHERE instance = 2 and permanent = 1`
`[0 ms] SQL(p): DELETE FROM group_instance USING group_instance LEFT JOIN instance ON group_instance.instance = id WHERE map = 631 and difficulty = 0`
`[0 ms] SQL(p): DELETE FROM group_instance USING group_instance LEFT JOIN instance ON group_instance.instance = id WHERE map = 631 and difficulty = 1`
`[1 ms] SQL: START TRANSACTION`
`SQL(p): DELETE FROM instance WHERE map = 631 and difficulty = 1 and (SELECT guid FROM character_instance WHERE extendState != 0 AND instance = id LIMIT 1) IS NULL`
` [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction`
`[1 ms] SQL(p): UPDATE instance_reset SET resettime = 1455501600 WHERE mapid = 631 AND difficulty = 2`
`[1 ms] SQL(p): SELECT guid FROM character_instance WHERE instance = 2 and permanent = 1`
`[12 ms] SQL(p): DELETE FROM instance WHERE map = 631 and difficulty = 0 and (SELECT guid FROM character_instance WHERE extendState != 0 AND instance = id LIMIT 1) IS NULL`
`Transaction aborted. 4 queries not executed.`
`[1 ms] SQL: START TRANSACTION`
`[1 ms] SQL: ROLLBACK`
`[1 ms] SQL: START TRANSACTION`

**Comment by jackpoz** [comment]
> It will cause worldserver frozen sometimes.

it will cause worldserver frozen when you use the .debug command that should be used only when debugging, where worldserver freezes can be ignored

**Comment by Treeston** [comment]
As per d4db0c15c7e and 62001360dd1d, the core gracefully handles deadlocks and retrying. The command will still function as intended.

**Comment by silvermcd123** [comment]
not invalid. still happens.

**Comment by jackpoz** [comment]
@silvermcd123 where is the crashreport (including all the informations required when reporting a crash ) ?

**Comment by illfated** [comment]
@silvermcd123 : Better open a new issue ticket to get the current issue template with the required paragraphs and sections asking you to fill in the necessary information (e.g. for crash reports, link a crash log from a debug build).
