### ISSUE TITLE
[6.x] DB/Quest Whitebark's Memory (10166)

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16606]
For this quest ( http://www.wowhead.com/quest=10166/whitebarks-memory ) the player has to use Old Whitebark's Pendant (http://www.wowhead.com/item=28209/old-whitebarks-pendant)  near the runestone in the scorched grove in Eversong Woods

Map 530 (Outland) 
Zone 3430 (Eversong Woods) 
Area 3474 (The Scorched Grove)
X: 8211.08069
Y: -6336.0625
Z: 64.529583
Orientation: 3.375877

The spellcast of the item ( http://www.wowhead.com/spell=33980/bury-pendant ) can not be completed as the "Scorched Grove Runestone" is required but not detected at any location around the runstone.

TrinityCore rev. 52758c1a0b8e 2016-02-12 20:40:43

**Comment by Aokromes** [comment]
gameobject id: 183434

**Comment by tkrokli** [comment]
Looking up spell 33980 (Bury Pendant) in both 3.3.5 and 6.x, I find this difference interesting:
- 3.3.5: Chance = 101, charges - 0
- 6.x: Chance = 0, charges - 0
```
ID - 33980 Bury Pendant
=================================================
Description: Bury Old Whitebark's Pendant near the runestone at the Scorched Grove to lay his memory to rest.

Category = 1139, SpellIconID = 1, activeIconID = 0, SpellVisual = (703,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000100 (SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
=================================================
Spell Level = 0, base 0, max 0

Category = 1139
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 7) "Ten yards":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 10, MaxRangePositive = 10

Cast time (Id 4) = 1,00

Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00000000
Requires Spell Focus 1401
Chance = 0, charges - 0
=================================================
Effect 1: Id 61 (SPELL_EFFECT_SEND_EVENT) DIFFICULTY_NONE
BasePoints = 0
Targets (0, 0) (NO_TARGET, NO_TARGET)
EffectMiscValueA = 12530

=================================================
Items using this spell:
   28209: Old Whitebark's Pendant
```
```sql
SELECT * FROM `gameobject_template` WHERE `entry`= 183434;
```
```
 entry    type  displayId  name                            IconName  castBarCaption  unk1    faction   flags    size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  Data24  Data25  Data26  Data27  Data28  Data29  Data30  Data31  Data32  unkInt32  AIName  ScriptName  VerifiedBuild
------  ------  ---------  ------------------------------  --------  --------------  ------  -------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  --------  ------  ----------  -------------
183434       8       2770  Scorched Grove Runestone Focus                                          0       0       1    1401      20       0       1       0       0      -1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0         0                             -18019
```
Both entries in `gameobject_template` in TDB 6.04 and 335.61 are roughly the same (except for Data24 - Data32 in TDB 6.04, they only contain zeros (0)), but none of the `gameobject` tables has got ID 183434 listed as a spawn. I don't remember how GOs work when it comes to spawning or existence in the game world, so it would be nice to know more about how this is supposed to work.

**Comment by Aokromes** [comment]
I think i mistaked GO, on 3.3.5a works at

[15:00:19] 99935 (Entry: 181260) - [Scorched Grove Runestone X:8206.849609 Y:-6335.759766 Z:64.500000 MapId:530] 

On 4.3.4 works too:

[15:02:57] Whitebark's Memory completed.
[15:02:57] Experience gained: 170.

**Comment by Aokromes** [comment]
Ok, gameobject 181260 is missing on 6.x db. It was deleted by https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/6.x/world/01_2015_03_21/2015_05_09_01_world.sql

**Comment by DDuarte** [comment]
Proper commit: https://github.com/TrinityCore/TrinityCore/commit/ad0cc83c842231fedd1eb9afe962176c17dc72ff

**Comment by tkrokli** [comment]
Thanks, that makes sense. `Scorched Grove Runestone` (181260) exists on 3.3.5, but not on 6.x.
Can any of the 3.3.5 GO data be used, or do we need to use fresh sniffs to get it back in TDB 6.04?

**Comment by Aokromes** [comment]
Cannot find creature/gameobject spawned there, maybe spell focus deletion was incorrect.

**Comment by tkrokli** [comment]
TrinityCore rev. aa006b490cd0 2016-06-28 22:55:52 +0200 (6.x branch) (Win64, Release, Static)
TDB 6.04 plus updates up to and including `2016_06_28_01_world.sql`

**Suggested solution:**
```sql
-- Restore deleted gameobject 181260 (Scorched Grove Runestone)
DELETE FROM `gameobject_template` WHERE `entry`= 181260;
INSERT INTO `gameobject_template` (`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`faction`,`flags`,`size`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`Data6`,`Data7`,`Data8`,`Data9`,`Data10`,`Data11`,`Data12`,`Data13`,`Data14`,`Data15`,`Data16`,`Data17`,`Data18`,`Data19`,`Data20`,`Data21`,`Data22`,`Data23`,`Data24`,`Data25`,`Data26`,`Data27`,`Data28`,`Data29`,`Data30`,`Data31`,`Data32`,`unkInt32`,`AIName`,`ScriptName`,`VerifiedBuild`) VALUES
(181260,8,0,'Scorched Grove Runestone','','','',0,0,1,1401,35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'','',0);

DELETE FROM `gameobject` WHERE `id`= 181260;
INSERT INTO `gameobject` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnMask`,`PhaseId`,`PhaseGroup`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecs`,`animprogress`,`state`,`VerifiedBuild`) VALUES
(99935, 181260, 530, 0, 0, 1, 0, 0, 8206.85, -6335.76, 64.5, 0, 0, 0, 0, 0, 180, 0, 1, 0);
```
Tested in-game, works like in 3.3.5 with the gameobject restored like above (quest completed).
