### ISSUE TITLE
[6.x] Core: Equiped Heirloom items crash worldserver on login

### ISSUE THREAD

**Issue by KarrokDC** [TrinityCore/TrinityCore#16604]
Logging into a character that has a Heirloom equipped crashes the world server.

Crashlog: [52758c1a0b8e_worldserver.exe_[13-2_21-16-13].txt](https://github.com/TrinityCore/TrinityCore/files/129456/52758c1a0b8e_worldserver.exe_.13-2_21-16-13.txt)

In the function void WorldSession::HandlePlayerLogin(LoginQueryHolder* holder) in CharacterHandler.cpp

LoadDB will load all items, including the Heirloom, these Heirlooms have the following spells (depending on the item):
http://www.wowhead.com/spell=57353/heirloom-experience-bonus-10
http://www.wowhead.com/spell=71354/heirloom-experience-bonus-5

Which the system tries to cast in void Spell::prepare(SpellCastTargets const* targets, AuraEffect const* triggeredByAura)

However the GetOwner() function attempts to retrieve the Player out of a HashMapHolder<Player>, which isn't filled until way later in HandlePlayerLogin(LoginQueryHolder* holder) (line 1023 in CrashHandler.cpp) which causes a chain of null returns etc.

Reproduction:
1. Make a new character
2. .additem in any heirloom (see collection overview)
3. equip heirloom
4. leave game
5. join game
6. crash

TrinityCore rev. 52758c1a0b8e 2016-02-12 20:40:43

**Comment by tkrokli** [comment]
TrinityCore rev. 019d15591cd7 2016-02-13 11:43:29 -0200 (6.x branch) (Win64, Release). Confirmed. 

Commands used to add items:
`.additem [Bloodied Arcanite Reaper]`
`.additem [Charmed Ancient Bone Bow]`
`.additem [Champion Herod's Shoulder]`
Equipped only the last 2 items, bow & 2H axe can't be equipped at the same time in 6.x, only in 3.3.5.
In this case, my test character is a level 70 hunter with talents learned, but no other items equipped.

**Comment by KarrokDC** [comment]
ignore 1st commit, forgot a return; which I added in the 2nd complete commit. And  PR has been made off that last commit :)
