### ISSUE TITLE
[3.3.5] Icecrown Citadel Festergut

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16619]
rev : 657adc270a32da4ef943b443c1fdcf2814466909
festergut inflicts two players with [Gas spore ](http://www.wowhead.com/spell=69278/gas-spore) if this two players stand together after explosion they must get  [Inoculated](http://www.wowhead.com/spell=69291/inoculated) dispelled but instead of this  they get stacks.
![screenshot_4](https://cloud.githubusercontent.com/assets/8265622/13041177/4220553c-d3ce-11e5-9550-4e892374ab71.png)

**Comment by Shauren** [comment]
What? Of course not. Source please.

**Comment by Demonid** [comment]
@lashia It gets dispelled but after http://www.wowhead.com/spell=72227/gastric-explosion

Last time i check, it was working as intended, at least that mechanic you are reporting.

**Comment by lashia** [comment]
http://youtu.be/L_0n38eMJXU Listen from 2 minutes
