### ISSUE TITLE
[3.3.5] Apothecary Hummel - Event: Love is in the Air

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16629]
TrinityCore rev. ae58f8e61636 2016-02-16 12:34:20 +0100 (HEAD branch)
+ all sql updates

In  Shadowfang Keep don't spawn Apothecary Hummel if you have the Quest http://www.wowhead.com/quest=14488/youve-been-served

http://www.wowhead.com/npc=36296/apothecary-hummel
https://www.youtube.com/watch?v=10j3uyei90M

**Comment by Aokromes** [comment]
centuplicated.

**Comment by DDuarte** [comment]
#5114
