### ISSUE TITLE
[3.3.5] Core/Spell: Druid flight form & fall damage

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16627]
3.3.5 fef06781f510b

Repro:
1. Dismount/unshift from flight form at high altitude and start falling
2. Shortly before hitting the ground, switch to flight form
3. Wait a second or two, then cancel flight form

Expected result:
- As the player only fell a short distance, no/trivial fall damage should be taken

Actual result:
- Player dies of fall damage when hitting the ground as if they had fallen all the way from the original altitude

**Comment by c9240709-b07d-4439-9212-94f05f7a3212** [comment]
Happens also if .gm fly on, fly at high altitude, .gm fly off and fall, near ground .gm fly on, fly a little bit then .gm fly off at low altitude near ground. You will die.

**Comment by P-Kito** [comment]
m_movementInfo.SetFallTime(0);

Falltime is reset on Unit::SetCanFly(false) and SetCanFly(false) is called when the spelleffect for flying(mount) is removed.

Hmmmmmmmmm

**Comment by Treeston** [comment]
Mounts can't stop your fall midair because they aren't instant cast.

**Comment by tkrokli** [comment]
In addition to that, riding mount & flying mount spells **require** that you're **not moving** to be cast.

**Comment by P-Kito** [comment]
as far as I can see it, druid mount also uses SPELL_AURA_FLY_MOVEMENT_SPEED which then triggers Unit::SetCanFly(false)  upon remove and therefore m_movementInfo.SetFallTime(0);
