### ISSUE TITLE
[6.x] Core/Phase: phase update doesn't work

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#16630]
6.x branch
hash 36a1b1ccd5d42b143c5dac23ae0e81c0b5b519f5

When you change area, the phases are not updated to new ones. They update only after relog.

**Comment by tkrokli** [comment]
Could you give some examples of how to confirm/reproduce/replicate this as easy as possible? :-)

**Comment by Lopfest** [comment]
Here are screenshots:
![wowscrnshot_021616_170448](https://cloud.githubusercontent.com/assets/32191/13082232/247133fa-d4d0-11e5-98a6-3cbd0dacfa05.jpg)
![wowscrnshot_021616_170506](https://cloud.githubusercontent.com/assets/32191/13082243/29e90c90-d4d0-11e5-9a69-7995f14aa112.jpg)
![wowscrnshot_021616_170518](https://cloud.githubusercontent.com/assets/32191/13082250/303ecfee-d4d0-11e5-895b-bf6d160a535a.jpg)

And here is sql if needed:
DELETE FROM `phase_area` WHERE `AreaId` IN (5825, 5846);
INSERT INTO `phase_area` (`AreaId`, `PhaseId`, `Comment`) VALUES
-- The Dawning Valley
(5825, 592, 'Pandaren starting zone - warrior'),
(5825, 593, 'Pandaren starting zone - mage'),
(5825, 594, 'Pandaren starting zone - hunter'),
(5825, 595, 'Pandaren starting zone - priest'),
(5825, 596, 'Pandaren starting zone - rogue'),
(5825, 597, 'Pandaren starting zone - shaman'),
(5825, 598, 'Pandaren starting zone - monk'),
(5825, 629, 'Pandaren starting zone - all classes'),
(5825, 1323, 'Pandaren starting zone - all classes'),
-- Fu's Pond
(5846, 1323, 'Pandaren starting zone - all classes');

**Comment by tkrokli** [comment]
OK, thanks. I was thinking maybe testing the start of Barrens, but your example will do just as well.

(Formatting tip for posting SQL code in comments here on github: add **```sql** on a single line before the code, then add just the 3 back ticks on a single line after the code, in case you need to write more regular text after the code block.) Using your SQL as an example:
```sql
DELETE FROM `phase_area` WHERE `AreaId` IN (5825, 5846);
INSERT INTO `phase_area` (`AreaId`, `PhaseId`, `Comment`) VALUES
-- The Dawning Valley
(5825, 592, 'Pandaren starting zone - warrior'),
(5825, 593, 'Pandaren starting zone - mage'),
(5825, 594, 'Pandaren starting zone - hunter'),
(5825, 595, 'Pandaren starting zone - priest'),
(5825, 596, 'Pandaren starting zone - rogue'),
(5825, 597, 'Pandaren starting zone - shaman'),
(5825, 598, 'Pandaren starting zone - monk'),
(5825, 629, 'Pandaren starting zone - all classes'),
(5825, 1323, 'Pandaren starting zone - all classes'),
-- Fu's Pond
(5846, 1323, 'Pandaren starting zone - all classes');
```
(I can remove this example if you want to apply the code block in your own comment above.)
