### ISSUE TITLE
[3.3.5]Core: Creature boss_razorscale

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16639]
Branch:3.3.5
commit**:https://github.com/TrinityCore/TrinityCore/commit/b8bd0053d89f38930bff71d0251c0d0077afafa5
TDB version:TDB60 update:2016_02_17_00_world.sql

Describe：The harpoon cannot work conversion stage
Console:DoZoneInCombat called for creature that has empty threat list (creature entry = 34188)
Current behaviour: Don't interrupt the sky stage
*Expected behaviour*: Correct stage conversion
1.Fight and use a harpoon
2.Error appear （http://radikal.ru/fp/cb179a41f66a4d1ba7ad79dd862cf8c3）
3.BOSS is still in the air

But returning the commit to the previous version is not a problem.

Please excuse my English

**Comment by Aokromes** [comment]
#13056
