### ISSUE TITLE
All "random dungeon" queues share a "already done today" state

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16636]
3.3.5 ae58f8e616362a6d92e317e6edc576054da14975

Repro:
- Have a character that has not yet done a random LK dungeon (heroic or otherwise) in the day
- At this time, "Random LK normal" offers two emblems of triumph, while "Random LK heroic" offers two emblems of frost.
- Queue for and complete a random LK normal and receive your two emblems of triumph.

Expected behavior:
- "Random LK normal" now offers only bonus gold (no emblems), while "Random LK heroic" still offers two emblems of frost.

Current behavior:
- "Random LK normal" now offers only bonus gold (no emblems), while "Random LK heroic" now offers two emblems of triumph.

**Comment by Aokromes** [comment]
#9307

**Comment by Treeston** [comment]
fixed in 97e0d1b
