### ISSUE TITLE
[3.3.5][6.x][Deadmines] Core/Script: Mr Smite should run down when the 2 guards are dead infront of the boat.

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#16643]
**Description**: Mr Smite should run down when the 2 guards are dead infront of the boat.

**Current behaviour**: 
He doesn't run down when those 2 guards die.

**Expected behaviour**:
Mr Smite should run down when the 2 guards are dead infront of the boat.

**Steps to reproduce the problem**:
1. Run in deadmines & face Mr Smite!

**Branch(es)**: 335/6x

**TC hash/commit**:
f2ab2464bef53893015847516fbf5d7d4c8f1e22

**Comment by Rushor** [comment]
what happens if you wipe on Mr Smite? is he supposed to run back to the boat? is he supposed to stay in front of the boat after a wipe?

**Comment by Kittnz** [comment]
As far as i know he should stand infront of the ramp that he comes down from. when you wipe thats his home spot.

**Comment by TranceAccount** [comment]
What he does in rev. https://github.com/TrinityCore/TrinityCore/commit/c3037c35639a is run down when the guards are attacked/aggroed.

**Comment by TranceAccount** [comment]
They are tied to each other in [creature_formations](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129997/creature+formations) table with GroupAI set to 515.

**Comment by TranceAccount** [comment]
As shown in this video for 3.3.5 https://www.youtube.com/watch?v=i-Y1SAUGPLQ, the current behaviour is correct. This issue is not relevant for 3.3.5 branch.

**Comment by Jinnaix** [comment]
Can also be noticed in current classic videos:
https://youtu.be/1u4VBHLbD7s?t=1895

**Comment by illfated** [comment]
@MrSmite : Any comments, in your own defense, in this case? (-KEK-) 😆

**Comment by MrSmite** [comment]
> @MrSmite : Any comments, in your own defense, in this case? (-KEK-) laughing

Everybody knows cows lay down for [14 hours](http://www.milkproduction.com/Library/Scientific-articles/Housing/Cow-comfort-9/). It takes a while to digest a n00b.
