### ISSUE TITLE
[3.3.5] Core/Item: Quest items not visible to master looter

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16653]
**3.3.5 ae1a5c6c2b82**

Quest items that require the master looter to assign them are not visible to the ML if he isn't personally eligible to loot them.

**Repro:**
1. Take two characters, A and B. Group them in a raid group, and set the loot mode to Master Looter (with threshold of Epic or below).
2. Add [Key to the Focusing Iris](http://www.wowhead.com/item=44569/key-to-the-focusing-iris) to character A and complete the quest it awards.
3. Enter 10-man Naxxramas and kill Sapphiron. It will drop another copy of the [Key to the Focusing Iris](http://www.wowhead.com/item=44569/key-to-the-focusing-iris).
4. Character A (the master looter) will not be able to see this second Key, as he has already completed the quest. Character B will be able to see the second key, but will not be able to loot it, as he is not the master looter. This leaves the key irretrievable.

**Expected behavior:**
The master looter is able to see the Key, but is unable to assign it to any player that doesn't fulfill the requirements to loot it.

**Comment by dr-j** [comment]
There are a load of items wih this issue where if master looter does not meet requirements then cannot see item and unless loot put on ffa no one gets: -

* Key to the focusing iris if masterlooter has completed quest
* Head of Onyxia if master has completed quest
* quest starters in ulduar from assembly of iron and algalon if master looter has completed quest.
* profession recipes in ulduar & toc (except enchanting ones) if masterlooter does not have required profession for recipe.

and those are just the ones I can remember but theres plenty more items with this problem and there appears to be no db conditions for this items so something from dbc files?

and can confirm that on retail even if you have already done these quests or dont have profession you can still see these recipes and you can still loot them you just get error if you try and use item to start quest.

**Comment by dr-j** [comment]
this is only a problem when master looter is used as if group loot and actually think I may have said wrong think the problem maybe only with enchanting recipes in ulduar but still all in toc.

**Comment by runningnak3d** [comment]
This solves the party / group loot issues prior to your patch that disables the sparkles if no loot is available for the player. If you want to test this, you will need to backout this: https://github.com/TrinityCore/TrinityCore/commit/a49544cc187d3a156b4615907d6b82057364fcc4 patch. I still haven't had time to research the steps needed to reproduce the bug that patch introduces, but I can tell you that you will still have group / party loot problems if you don't back out that patch...

```C++
From 356ec0d4600da5987d855274d45e3ebbf99f0879 Mon Sep 17 00:00:00 2001
From: "Brian Swango (runningnak3d)" <runningnak3d@gmail.com>
Date: Wed, 8 Jun 2016 20:20:41 +0000
Subject: [PATCH] Core/Loot: Fix party loot items only being lootable by one
 member of a party

---
 src/server/game/Loot/LootMgr.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Loot/LootMgr.cpp b/src/server/game/Loot/LootMgr.cpp
index ebdeb40..3708740 100644
--- a/src/server/game/Loot/LootMgr.cpp
+++ b/src/server/game/Loot/LootMgr.cpp
@@ -354,7 +354,7 @@ LootItem::LootItem(LootStoreItem const& li)
 
     ItemTemplate const* proto = sObjectMgr->GetItemTemplate(itemid);
     freeforall  = proto && (proto->Flags & ITEM_PROTO_FLAG_MULTI_DROP);
-    follow_loot_rules = proto && (proto->FlagsCu & ITEM_FLAGS_CU_FOLLOW_LOOT_RULES);
+    follow_loot_rules = proto && (proto->FlagsCu & ITEM_FLAGS_CU_FOLLOW_LOOT_RULES && !proto->Flags & ITEM_PROTO_FLAG_MULTI_DROP);
 
     needs_quest = li.needs_quest;
```
