### ISSUE TITLE
[3.3.5] Core/Crash: HandleBattleFieldPortOpcode: crash

### ISSUE THREAD

**Issue by 090809** [TrinityCore/TrinityCore#16656]
The server crashes when during teleportation, one player leaves/is ejected from the game (crash)

Branch: 335

TC hash: rev. ea9c112

OS: ubuntu 

https://gist.github.com/090809/21410554d0cbc44f68ea log

**Comment by jackpoz** [comment]
@Shauren can we simply NULL check player in that opcode ?

**Comment by Shauren** [comment]
This must be some custom change, there is no local variable named 'player' in that handler.
and checking _player would be pointless, thats what STATUS_LOGGEDIN is for
