### ISSUE TITLE
[3.3.5] Core/Spell: Damage-over-time effects' damage incorrectly piercing immunity

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16658]
3.3.5 fef06781f510b467b1309e1cfbea1dd2d1edbae4

Periodic damage from auras that have `SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY` ignores damage immunities, such as Ice Block. This is not blizzlike.

`SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY` should only prevent the auras from being removed by such immunities, and allow them to be applied while such immunities are active, but should not prevent the damage from the aura being negated while the immunity is active.

Repro:
1. Engage Sapphiron while on a Mage or Paladin.
2. Use Ice Block / Divine Shield.
3. Still take damage from [Frost Aura](http://www.wowhead.com/spell=28531).

**Comment by mik1893** [comment]
while SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY is correctly implemented in
Unit::IsImmunedToSpell
and Unit::IsImmunedToSpellEffect
returning false, it's actually also implemented in Unit::IsImmunedToDamage

```cpp
bool Unit::IsImmunedToDamage(SpellInfo const* spellInfo) const
{
    if (spellInfo->HasAttribute(SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY))
        return false;
```
where actually it shouldn't be checked.
I distinctly remember that a mage cannot take damage from frost aura on the Sindragosa encounter (i've done it many times on retail)

**Comment by Shauren** [comment]
#9362

**Comment by mik1893** [comment]
would actually be nice if we get a proof and not just us remembering that it was like that...
