### ISSUE TITLE
[3.3.5] Core/Pet: "Roar of Sacrifice" capable of making pet engage certain NPCs

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16659]
3.3.5 d4184065b6d51b250ab08f35e88868cef631ed4b

When the hunter pet ability [Roar of Sacrifice](http://wotlk.openwow.com/spell=53480) is used on certain normally-unattackable NPCs, the pet will enter melee combat with them, allowing the hunter to indirectly kill friendly NPCs.

Examples of affected creatures include [Grezla the Hag](http://www.wowhead.com/npc=32683/grezla-the-hag) and [Marcia Chase](http://www.wowhead.com/npc=28742/marcia-chase) in Dalaran.

**Comment by MrSmite** [comment]
Both those NPCs are Kirin Tor which is a Neutral faction and should be attackable. Are you saying that even after you've earned "Friendly" rep with them that they're still attackable?

**Comment by Treeston** [comment]
The Kirin Tor are one of the main reputation factions in Wrath. You cannot set yourself At War with them.
In addition, Roar of Sacrifice is a _friendly-targeted_ ability. It should never make your pet engage in melee combat with the target it is cast on.

However, this does indeed not appear to work at reputation levels above neutral.

**Comment by MrSmite** [comment]
> It should never make your pet engage in melee combat with the target it is cast on.

Yes, that's a good point.

> However, this does indeed not appear to work at reputation levels above neutral.

Hmm, is there a DBC column that Trinity isn't looking at to decide 'neutral but unattackable'?

**Comment by Treeston** [comment]
This data already exists. If the faction is not set as "at war", it should not be attackable.

The core also properly recognizes that war cannot be set with the faction, as "peace forced" is shown in faction information (try `.lookup faction` while targeting yourself).

**Comment by Rushor** [comment]
same issue happens if you use the jump ability of the ghoul pet from dks on these "neutral but unattackable" creatures

**Comment by Treeston** [comment]
Stumbled across the location that I feel needs changing today while working on charm AI. I think the standings check in `Unit::_IsValidAttackTarget` needs to be adjusted to properly check for the "at war" flag (it's currently only checking for reaction > NEUTRAL).

**Comment by MrSmite** [comment]
@Treeston Yes, that's probably a good idea. I don't think I ever considered "at war" when I rewrote the AI years ago.
