### ISSUE TITLE
[3.3.5] [ICC] Strength of Wrynn should affect player pets

### ISSUE THREAD

**Issue by Quadral** [TrinityCore/TrinityCore#16665]
**Description**:

[Strength of Wrynn](http://www.wowhead.com/spell=73828/strength-of-wrynn):  should affect player controlled pets (Hunter pet, DeathKnight ghoul, warlock demons and other controlled units by player)

**Current behaviour**: 

When player summons his pet, it does not recieve [Strength of Wrynn](http://www.wowhead.com/spell=73828/strength-of-wrynn).

**Expected behaviour**:
Player pets should recieve the [Strength of Wrynn](http://www.wowhead.com/spell=73828/strength-of-wrynn) buff upon summoning them. 

**Steps to reproduce the problem**:

1. Create a Hunter pet or any other class which has a pet.
2. Go to ICC (Either difficulty)
3. Summon your pet, and your pet will not recieve [Strength of Wrynn](http://www.wowhead.com/spell=73828/strength-of-wrynn)

**Branch(es)**: 3.3.5

**TC hash/commit**: c14ef8852285e71b4e1b9ddba438c9917add9a2a

**TDB version**: TBD 60

**Operating system**: Windows 8

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by sirikfoll** [comment]
Duplicate #7940
