### ISSUE TITLE
[3.3.5][6.x][ICC] Gunship - No damage from cannons

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#16664]
**Description**: icc gunship do not take damage from cannons

**Current behaviour**: icc gunship do not take damage from cannons

**Expected behaviour**: Gunships should take damage from cannons

**Branch(es)**: 335/6x

**TC hash/commit**: 9c0deaaebbbd2861e10a365e283000008a2a188f

**TDB version**: 60

**Operating system**: Linux

**Comment by sirikfoll** [comment]
Any specific spets to reproduce? 
It is working normally for me.

**Comment by Rushor** [comment]
@Runico: any news on this?

**Comment by Runico** [comment]
@Rushor, I has core revert to 3 months ago, but i have plan to porting my custom codes to the latest commit in the next month
