### ISSUE TITLE
[3.3.5][6.x][PoS] Core/Spell: Throw Saronite 

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16663]
**Description**: This spell is used by:Forgemaster Garfrost http://www.wowhead.com/npc=36494

to avoid stack from boss by LoS

**Current behaviour**: the saronite rock doesn't appear on the map

**Expected behaviour**: the saronite rock must be appear on the map

**Steps to reproduce the problem**: start fight with the boss

**Branch(es)**: 335/6x

**TC hash/commit**: 9c0deaaebbbd2861e10a365e283000008a2a188f

**TDB version**: 60

**Operating system**: Linux

**Comment by Keader** [comment]
It work in current revs
