### ISSUE TITLE
[3.3.5] Core/Creature: Creature position desync when using .respawn

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16661]
3.3.5 d4184065b6d51b250ab08f35e88868cef631ed4b

When using .respawn to respawn a creature that is still in the client's cache (such as because the corpse is still visible), the creature will return to its spawn position in the server, but this is never communicated to the client. The client sees the now-alive creature at the corpse position, but is unable to interact with it there, while the client prevents interaction while standing at the correct position.

The desync persists until the next creature position update, either through the creature moving or through the client leaving and re-entering the area.

**Comment by Killyana** [comment]
Looks to be fixed by #19056

**Comment by Treeston** [comment]
Yes
