### ISSUE TITLE
mmaps could not load

### ISSUE THREAD

**Issue by iceyman** [TrinityCore/TrinityCore#16678]
**Description**: AS BELOW

**Current behaviour**: Tell us what happens

`Could not load MMAP name:Outland, id:530, x:31, y:32 (mmap rep.: x:31, y:32)
Could not load MMAP name:Outland, id:530, x:29, y:25 (mmap rep.: x:29, y:25)
Could not load MMAP name:Outland, id:530, x:29, y:24 (mmap rep.: x:29, y:24)
Could not load MMAP name:Outland, id:530, x:35, y:29 (mmap rep.: x:35, y:29)
Could not load MMAP name:Outland, id:530, x:35, y:30 (mmap rep.: x:35, y:30)
Could not load MMAP name:Outland, id:530, x:19, y:24 (mmap rep.: x:19, y:24)
Could not load MMAP name:Outland, id:530, x:19, y:22 (mmap rep.: x:19, y:22)
Could not load MMAP name:Outland, id:530, x:18, y:24 (mmap rep.: x:18, y:24)
Could not load MMAP name:Outland, id:530, x:18, y:23 (mmap rep.: x:18, y:23)
Could not load MMAP name:Outland, id:530, x:18, y:22 (mmap rep.: x:18, y:22)
Could not load MMAP name:Outland, id:530, x:20, y:24 (mmap rep.: x:20, y:24)
Could not load MMAP name:Outland, id:530, x:24, y:32 (mmap rep.: x:24, y:32)
Could not load MMAP name:Outland, id:530, x:24, y:30 (mmap rep.: x:24, y:30)
Could not load MMAP name:Outland, id:530, x:23, y:30 (mmap rep.: x:23, y:30)
Could not load MMAP name:Outland, id:530, x:23, y:31 (mmap rep.: x:23, y:31)
Could not load MMAP name:Outland, id:530, x:23, y:32 (mmap rep.: x:23, y:32)
Could not load MMAP name:Outland, id:530, x:25, y:30 (mmap rep.: x:25, y:30)
Could not load MMAP name:Outland, id:530, x:25, y:31 (mmap rep.: x:25, y:31)
Could not load MMAP name:Outland, id:530, x:25, y:32 (mmap rep.: x:25, y:32)
Could not load MMAP name:Outland, id:530, x:36, y:13 (mmap rep.: x:36, y:13)
Could not load MMAP name:Outland, id:530, x:21, y:24 (mmap rep.: x:21, y:24)
Could not load MMAP name:Outland, id:530, x:21, y:23 (mmap rep.: x:21, y:23)
Could not load MMAP name:Outland, id:530, x:21, y:22 (mmap rep.: x:21, y:22)
Could not load MMAP name:Outland, id:530, x:20, y:22 (mmap rep.: x:20, y:22)
Could not load MMAP name:Outland, id:530, x:24, y:17 (mmap rep.: x:24, y:17)
Could not load MMAP name:Outland, id:530, x:23, y:18 (mmap rep.: x:23, y:18)
Could not load MMAP name:Outland, id:530, x:35, y:28 (mmap rep.: x:35, y:28)
Could not load MMAP name:Outland, id:530, x:22, y:28 (mmap rep.: x:22, y:28)
Could not load MMAP name:Outland, id:530, x:18, y:29 (mmap rep.: x:18, y:29)
Could not load MMAP name:Outland, id:530, x:18, y:27 (mmap rep.: x:18, y:27)
Could not load MMAP name:Outland, id:530, x:19, y:27 (mmap rep.: x:19, y:27)
Could not load MMAP name:Outland, id:530, x:19, y:28 (mmap rep.: x:19, y:28)
Could not load MMAP name:Outland, id:530, x:19, y:29 (mmap rep.: x:19, y:29)
Could not load MMAP name:Outland, id:530, x:17, y:28 (mmap rep.: x:17, y:28)
Could not load MMAP name:Outland, id:530, x:17, y:29 (mmap rep.: x:17, y:29)
Could not load MMAP name:Eastern Kingdoms, id:0, x:39, y:28 (mmap rep.: x:39, y:28)
Could not load MMAP name:Eastern Kingdoms, id:0, x:18, y:36 (mmap rep.: x:18, y:36)
Could not load MMAP name:Eastern Kingdoms, id:0, x:44, y:28 (mmap rep.: x:44, y:28)
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
`

**Expected behaviour**: Tell us what should happen instead

not the above error

**Steps to reproduce the problem**:

1. fresh copy of wow installed from vanilla to BC TO WOTLK and then updated to 3.3.5a 
2. extracted new maps vmaps mmaps 
3. put new extracted maps on server 

**Branch(es)**: 335

**TC hash/commit**:  2345e848559b787710abac3bb73b513a069084c9

**TDB version**:  335.60 plus updates

**Operating system**: ubuntu 14.04 64bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#14439
