### ISSUE TITLE
Razorscale & Nefarian 

### ISSUE THREAD

**Issue by sova-bogdan** [TrinityCore/TrinityCore#16677]
Client:3.3.5a

> Rev. eee75b8 

TDB last +Updates. 

Linux Xubuntu 15.10

I use last  Maps. Vmaps. MMaps extractor.
in worldserver.conf 
vmap and mmap included.

#9083  - did not help 
#13056 - did not help 

Problem: 
1.Nefarian hangs in the air  www.wowhead.com/npc=11583
2.Razorscale hangs in the air     www.wowhead.com/npc=33186 harpoons fraction  changed.

**Comment by Aokromes** [comment]
Don't open new tickets if you find existing tickets
