### ISSUE TITLE
[3.3.5][6.x][Paladin] DB/Spell: Judgements of the Wise

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16679]
**Description**: whenever paladin's use Judgements this talent gives paladin 25% of him/his mana

**Expected behaviour**: Judgements of the Wise talent must gives mana, even Judgements get absorb

**Branch(es)**: 335/6x

**TC hash/commit**: 9c0deaaebbbd2861e10a365e283000008a2a188f

**TDB version**: 60

**Operating system**: Linux

**Comment by Kittnz** [comment]
So in short, it does not work?

**Comment by Runico** [comment]
I think this is generic problem not just this talent

anyone could confirm this issue as another spell ?

**Comment by Rushor** [comment]
try to add PROC_EX_ABSORB in spell_proc_event
