### ISSUE TITLE
[3.3.5] Core/Spell: Triggered spells never show a cast bar on the client

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16687]
3.3.5 50223ea04f8216d1fe2dd588a16a1958569f3daa

On the current core, casting a spell with _any_ triggered flag will cause the spell to not show a cast bar on the client (despite actually having a cast time).

This is caused by [this segment of SendSpellStart](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L3811-3812)

``` cpp
    if ((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell()) || m_triggeredByAuraSpell)
        castFlags |= CAST_FLAG_PENDING;
```

According to blame, this was added in 2effb7acdc08 to fix crashes with certain triggered spells.

The questions are the following:
- **Is this an issue we want to fix?** In my opinion, yes. The spell has a cast time on the server (which can be interrupted by moving etc), so this should reflect on the client.
- **How do we fix this issue?** More information would be required on what the circumstances are where retail sends this flag. Maybe @machiavell1 could elaborate if he's still around.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
