### ISSUE TITLE
[3.3.5] Quest: Mending Fences (12915)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16683]
3.3.5 fef06781f510b

[Quest: Mending Fences](http://www.wowhead.com/quest=12915/mending-fences#comments)

When using [Thorim's Charm of Earth](http://www.wowhead.com/item=41505) on a [Stormforged Iron Giant](http://www.wowhead.com/npc=29375), only two [Earthen Ironbane](http://www.wowhead.com/npc=29927/earthen-ironbane) are spawned (instead of four), and they spawn next to the player (instead of next to the targeted Giant.

In addition, they do not taunt the Giant they are fighting.

**Comment by w5860363** [comment]
@Treeston test https://github.com/TrinityCore/TrinityCore/commit/529820bc14e5d9245998fa4302565676a87a82db
TDB conditions Limit the spell
They don't attack the monster around can only use 29375
As they do not taunt NPC
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry=29927;
INSERT INTO smart_scripts VALUES (29927, 0, 0, 0, 54, 0, 100, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 19, 29375, 30, 0, 0, 0, 0, 0, 'Summon');

**Comment by Keader** [comment]
@w5860363 use ```sql xD

**Comment by tkrokli** [comment]
... and using Keira2. you get a full script with all required settings:
```sql
-- new SmartAI script for creature entry 29927 Earthen Ironbane
UPDATE `creature_template` SET `AIName` = 'SmartAI', `ScriptName`= '' WHERE `entry` = 29927;

DELETE FROM `smart_scripts` WHERE `entryorguid`= 29927 AND `source_type`= 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(29927,0,0,0,54,0,100,0,0,0,0,0,49,0,0,0,0,0,0,19,29375,30,0,0,0,0,0,'Earthen Ironbane - on Just Summoned - Start Attacking Stormforged Iron Giant');
```
I don't know the creature abilities, except for what is shown on wowhead:
http://www.wowhead.com/npc=29927/earthen-ironbane
http://www.wowhead.com/npc=29375/stormforged-iron-giant
http://www.wowhead.com/spell=55512/call-of-earth
(Summons a group of Earthen that will swarm an Iron Giant or Fire Giant near Dun Niffelem.)

**Comment by w5860363** [comment]
@tkrokli 55512 Not 55512 items on this spell spell is 55818 link 55528

**Comment by tkrokli** [comment]
Huh? Sorry, not sure if I get what you mean, but I will try.
http://www.wowhead.com/spell=55818/hurl-boulder - used by -
http://www.wowhead.com/item=41505/thorims-charm-of-earth

http://www.wowhead.com/spell=55528/summon-earthen - not sure what to do with this one.

**Comment by w5860363** [comment]
@tkrokli Maybe GIThub mangos version can help 
https://github.com/koksneo/MaNgOs/blob/62b18ebc1b8e0753ca3650e87ab80e023bd3af5d/src/game/SpellEffects.cpp#L1950

**Comment by tkrokli** [comment]
OK, if you are talking about Spell scripting, then it is not my field of expertise.
Maybe `Heaven` in #trinity could look at this case?

**Comment by CraftedRO** [comment]
0817be8f76de Seems still valid

https://user-images.githubusercontent.com/24683355/140754534-703877f7-ca4d-4990-8275-9d21baf8814d.mp4

**Comment by offl** [comment]
61f32426ab534f8b19fc85bbbac1224ffc73a70c
