### ISSUE TITLE
[3.3.5] Core/Spell: Encapsulate client crash

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16689]
Description:Boss cast spell
Current behaviou: Client crash
Expected behaviour: 

1.BOSS cast Encapsulate (http://www.wowhead.com/spell=45661)
2.mage  use Ice Block 
3.Client crash

Branch(es) :335/6x
TC hash/commit:https://github.com/TrinityCore/TrinityCore/commit/1c86d286d4f9afc365a2a64b7ed0eb2d939814b7
TDB version:TDB60
Operating system:windows
patch:NO

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp#L439

**Comment by Aokromes** [comment]
Useless crashlog, compile on debug mode and pastebin result.

**Comment by Treeston** [comment]
Crashdump from a debug build please.

**Comment by w5860363** [comment]
@Treeston Only a client crash Do you want a debug simulator client DMP files？

**Comment by Treeston** [comment]
Oh, client crash, my bad.

**Comment by Aokromes** [comment]
I suggest you to use https://github.com/Zedron/Whiff and sniff it to see what's the reason of the crash.

**Comment by jackpoz** [comment]
please test it after 8f94c9ef6b843f69d014b7e3a4b3b30e5d1515e4

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8f94c9ef6b843f69d014b7e3a4b3b30e5d1515e4
