### ISSUE TITLE
[3.3.5] Core/Command: .gobject near does not show temporary GOs

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16690]
3.3.5 8267e49

Repro:
1. .gobject add temp <id>
2. .gobject near 50

Expected:
3. The temporary GO shows up

Instead:
3. The list only shows permanent GOs in the vicinity

**Comment by dr-j** [comment]
same with .npc near it only shows spawns that are spawned via db.

**Comment by Shauren** [comment]
These commands query the db, not search grid.

**Comment by tkrokli** [comment]
... and as long as the temp gobject is not saved to the DB, there is nothing to find. Case dismissed?

**Comment by Aokromes** [comment]
Alternative: .gobj target looking in front of the desired go.

**Comment by Aokromes** [comment]
not a bug, use gobj target xd
