### ISSUE TITLE
[3.3.5] EarthLiving does not proc from Earth Shield

### ISSUE THREAD

**Issue by Runico** [TrinityCore/TrinityCore#16697]
EarthLiving: 52000
Earth Shield: 49284

**Branch(es)**: 335

**TC hash/commit**: 8ef9ea9157ca6c04194888a2118be7daf303856f

**TDB version**: 60

**Operating system**: Linux

**Comment by ariel-** [comment]
http://wow.gamepedia.com/index.php?title=Earthliving_Weapon&oldid=2800059

>  [Earth Shield] does not trigger Earthliving.

**Comment by Runico** [comment]
@ariel- http://wow.gamepedia.com/index.php?title=Earthliving_Weapon&action=history

check this one, date is for 2010

**Comment by tkrokli** [comment]
You mean the page from [18:34, 18 May 2010](http://wow.gamepedia.com/index.php?title=Earthliving_Weapon&oldid=2261932) (last page before [**4.0.3a** 21:20, 23 November 2010](http://wow.gamepedia.com/index.php?title=Earthliving_Weapon&oldid=2519534))?
- http://wow.gamepedia.com/index.php?title=Earthliving_Weapon&oldid=2261932

**Comment by Shauren** [comment]
Nowhere does it state that earth shield not triggering earthliving on that page is a cataclysm change, to me it looks like someone just took time to expand the article

**Comment by tkrokli** [comment]
OK, I don't know those spells myself. I mostly tried to help Runico point out his issue better
(although I guess I "triggered" you to refute this issue with related feedback, pointing out the case).

**Comment by ariel-** [comment]
Earthliving Weapon aura (51940 and related) does not have the spell attribute SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED, and with Earth Shield heal (379) being a triggered cast, this means ES will never trigger EL, and that probably this is intended by blizz.

**Comment by Aokromes** [comment]
so... not a bug?

**Comment by tkrokli** [comment]
According to Shauren & ariel- the facts say that this is not a bug. Only Runico claims the opposite.

**Comment by Treeston** [comment]
Spell attrs support the claim, so not a bug unless concrete proof of the opposite is provided.
