### ISSUE TITLE
[3.3.5/6.x] [Ruby Sanctum] Creatures with wrong melee damage.

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#16691]
The creatures in general Ruby Sanctum, are very low damage with melee.
DamageModifier need to be updated.

Creatures Ids:

**Trash Mobs:**

*Charscale Invoker 
```sql 
SELECT * FROM creature_template where entry = 40417;
```
*Charscale Assaulter 
```sql 
SELECT * FROM creature_template where entry = 40419;
```
*Charscale Commander 
```sql 
SELECT * FROM creature_template where entry = 40423;
```
*Charscale Elite
```sql 
 SELECT * FROM creature_template where entry = 40421;
```
**General Zarithrian Minion:**

*Onyx Flamecaller 
```sql 
SELECT * FROM creature_template where entry = 39814;
```

**Halion Minions 25 hc:**

*Living Ember 
```sql 
SELECT * FROM creature_template where entry = 40683;
```
*Living Inferno
```sql 
SELECT * FROM creature_template where entry = 40681;
```

Not sure, but I believe the Damage of Halion 25 Heroic is also low. Looking videos of the time, in Warriors tankers the average damage is 16k ~ 33k with damage reduction auras. In TC Halion gives damages 12k ~ 15k on average in Paladin with 35k armor.

PS: I looked all creatures in difficulty 25 man heroic.
PS²: Sorry about bad english.
PS³: Creatures need smart script also, I will see if I can do this part.

**Branch(es)**: 335/6x

**TC hash/commit**: 8267e493d10ce2322d13ab30e6944673000425d4

**TDB version**: TDB 335.60

**Operating system**: Win10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#11834
