### ISSUE TITLE
[3.3.5][Mage] Core/Spell: Arcane Missiles does not stop channeling if target dies

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16707]
3.3.5  3b389b7

Repro:
1. Cast Arcane missiles at a target
2. Kill the target - using .die works, as does having it die from other sources, or even if it dies from the first few missiles

Expected:
3. Arcane Missiles stops channeling as soon as the target dies.

Instead:
3. Arcane Missiles _visually_ appears to stop channeling (the cast bar disappears, and the character's emote state goes to normal). However, the character keeps casting the remaining missile ticks, even though no actual spell is fired (the character assumes the "casting" pose and the missile sound plays).

Also:
Attempting to cast Arcane Missiles at a target that is not in line of sight will trigger a global cooldown despite the spell failing.

**Comment by Goatform** [comment]
It's not just Arcane Missiles, it's an issue with channeling spells in general.

**Comment by mik1893** [comment]
case SPELL_STATE_CASTING:
        {
            if (m_timer)
            {
                // check if there are alive targets left
                if (!UpdateChanneledTargetList())
                {
                    TC_LOG_DEBUG("spells", "Channeled spell %d is removed due to lack of targets", m_spellInfo->Id);
                    SendChannelUpdate(0);
                    finish();
                }

                if (m_timer > 0)
                {
                    if (difftime >= (uint32)m_timer)
                        m_timer = 0;
                    else
                        m_timer -= difftime;
                }
            }

            if (m_timer == 0)
            {
                SendChannelUpdate(0);
                finish();
            }
            break;
        }

then my guess is UpdateChanneledTargetList() is not returning false.

From UpdateChanneledTargetList():

    for (std::list<TargetInfo>::iterator ihit= m_UniqueTargetInfo.begin(); ihit != m_UniqueTargetInfo.end(); ++ihit)
    {
        if (ihit->missCondition == SPELL_MISS_NONE && (channelTargetEffectMask & ihit->effectMask))
        {
            Unit* unit = m_caster->GetGUID() == ihit->targetGUID ? m_caster : ObjectAccessor::GetUnit(*m_caster, ihit->targetGUID);

            if (!unit)
                continue;

            if (IsValidDeadOrAliveTarget(unit))
            {
                if (channelAuraMask & ihit->effectMask)
                {
                    if (AuraApplication * aurApp = unit->GetAuraApplication(m_spellInfo->Id, m_originalCasterGUID))
                    {
                        if (m_caster != unit && !m_caster->IsWithinDistInMap(unit, range))
                        {
                            ihit->effectMask &= ~aurApp->GetEffectMask();
                            unit->RemoveAura(aurApp);
                            continue;
                        }
                    }
                    else // aura is dispelled
                        continue;
                }

                channelTargetEffectMask &= ~ihit->effectMask;   // remove from need alive mask effect that have alive target
            }
        }
    }

    // is all effects from m_needAliveTargetMask have alive targets
    return channelTargetEffectMask == 0;

might try just adding an else return false on the IsValidDeadOrAlive if

**Comment by ariel-** [comment]
Duplicated of #15186
