### ISSUE TITLE
GO Respawntimer Fix

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16701]
TC>TrinityCore rev. ffdf75a23316 2016-02-27 17:55:43 +0100 (HEAD branch)

-- Wrong respawntimer for Quest GameObjects

-- Is Important for Player's in Group

-- Empty Cauldron
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 66377;
-- Iron Chain
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 66378;
-- New Avalon Patrol Schedule
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 66308;
-- Damaged Diving Gear
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 40775;
-- Tool Kit
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 40774;
-- Deserter Propaganda
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 9175;
-- The Book of Ur
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 40667;
-- New Avalon Registry
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 66384;

**Comment by Aokromes** [comment]
Very likely hack.

**Comment by Tauriella** [comment]
No Hack its fakt
Checked on Liveserver

**Comment by Aokromes** [comment]
#12842

**Comment by Treeston** [comment]
Not related to #12842, these are perm spawned and should respawn near-instantly.

**Comment by tkrokli** [comment]
If you decide that you want to use the query above at a later time, it could look like this:
```sql
UPDATE `gameobject` SET `spawntimesecs`= 2 WHERE `guid` IN (
 9175,  -- Deserter Propaganda
40667,  -- The Book of Ur
40774,  -- Tool Kit
40775,  -- Damaged Diving Gear
66308,  -- New Avalon Patrol Schedule
66377,  -- Empty Cauldron
66378,  -- Iron Chain
66384); -- New Avalon Registry
```

**Comment by Tauriella** [comment]
:+1:
