### ISSUE TITLE
[3.3.5] Core/Client: Client desync on spline movement with MoveSplineFlag::Flying

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#16702]
https://github.com/TrinityCore/TrinityCore/commit/f9eff81388b12f6f8275f892c67bf197188c3450

Client does spline movement differently from the server for movement with MoveSplineFlag::Flying. Client has a 'slow start' with acceleration towards the end, while the server seems the opposite. I'm guessing client doesn't really use catmull-rom or at least it uses different parameters (I don't know enough on the matter).

You can replicate the problem by stunning a flying creature that is moving on a relatively long path to you (single point! no pathfinding). Stun it halfway through and sometimes you'll see quite large 'blinks' forward.

**Comment by Killyana** [comment]
Is this the issue with the val'kyr on Lich King encounter?

**Comment by Keader** [comment]
i think so Killyana.
@treeston @ccrs

**Comment by ccrs** [comment]
nope

**Comment by Killyana** [comment]
In an older core when a player is doing this quest: https://woehead.way-of-elendil.fr/?quest=12856 when the drake starts the waypoint you will see it teleporting and freezing (from the point of view of a second character) but I'm not able to reproduce it in the current revision.

**Comment by DanVS** [comment]
Should be resolved (#22582).
