### ISSUE TITLE
[3.3.5][6.x][Ruby] Halion - Healthchange

### ISSUE THREAD

**Issue by Y0jimbo** [TrinityCore/TrinityCore#16700]
**Description**: Halion 

**Current behaviour**: 
1- breath interruptable
2- when the boss shifts to shadow realm it has 100% health instead of 75%
3- the corporality is alwahs stable on 50% and never changes
4- in the heroic version the boss is already spawned when players enter the istance and chan be aggroed     without killing the other bossesn furthermore it gives no loot

**Expected behaviour**: 
1- breath should be immune to interrupt,silence and stun effects
2- when the boss shifts to the shadow realm it should be on 75% of his health
3- the perce tage of corporality should change according to the difference between health percentages on both bosses,modifying the damage taken and dealth from both the boss and the raid group.

**Steps to reproduce the problem**:

1. Go in the ruby sanctum
2. Kill 3 miniboss
3. Start fight halion

**Branch(es)**: 335

**TC hash/commit**: ae1a5c6

**TDB version**: 335.59 

**Operating system**: all

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lashia** [comment]
confirm b646bcbb915ad6abcec5d349b28a74991e1c8cad

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16725#issuecomment-193231124

**Comment by Aokromes** [comment]
This bug is still valid after dfe278459d79ade500a66356a98b4065c0722572 ?
About interrupt it's a different generic ticket.

**Comment by Keader** [comment]
i'm using sirikfoll code in our server, and health works fine.
author should tested alone.

**Comment by sirikfoll** [comment]
> Works for me ™
