### ISSUE TITLE
[3.3.5] DBErrors 

### ISSUE THREAD

**Issue by lashia** [TrinityCore/TrinityCore#16721]
The spell 34453 (rank: 1, first: 34453) listed in `spell_ranks` already has Cha$
The spell 34454 (rank: 2, first: 34453) listed in `spell_ranks` already has Cha$
The spell 34453 (rank: 1, first: 34453) listed in `spell_ranks` already has Cha$
The spell 34454 (rank: 2, first: 34453) listed in `spell_ranks` already has Cha$

**Branch(es)**: 335

**TC hash/commit**: fe707db96f711f94a461306748274fa0bffa0226

**TDB version**:60

**Operating system**:Ubuntu 14.04

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
TrinityCore rev. 768a5cf354b4 2016-03-04 00:05:52 +0100 (3.3.5 branch) (Win64, Release) (TDB 335.60)
Can not confirm by only starting up the servers. I only get this startup message now:
```
Table `gameobject` has gameobject (GUID: 5521 Entry: 148838) that has wrong spawn mask 3 including unsupported difficulty modes for map (Id: 109), skip
```
It looks like your 2 line DBError message (listed twice in your post) is gone, unless there is something specific you need to do to reproduce your error messages. Try clearing out your log and restart your servers, then see if the error is still there. See if you can write a suggestion on how to reproduce.

**Comment by Aokromes** [comment]
Same here, tk's row was the only on dberrors.

**Comment by lashia** [comment]
on rev: 6cdd29611bcfe837a5d9b4664d9a7013e99a2094 
The spell 34453 (rank: 1, first: 34453) listed in `spell_ranks` already has ChainEntry from dbc.
The spell 34454 (rank: 2, first: 34453) listed in `spell_ranks` already has ChainEntry from dbc.

**Comment by Aokromes** [comment]
3.3.5a is startup error clean.

**Comment by lashia** [comment]
and what is that error? i cleaned my old logs

**Comment by joschiwald** [comment]
You can safely remove the erroring rows from db

**Comment by tkrokli** [comment]
@lashia : you can run this query to get rid of your error:
```sql
DELETE FROM `spell_ranks` WHERE `first_spell_id` = 34453 AND `rank` IN (1,2);
```
Just so you know what your errors are caused by:
- http://wotlk.openwow.com/spell=34453 `<=>` Animal Handler, Rank 1 (3.3.5 only)
- http://wotlk.openwow.com/spell=34454 `<=>` Animal Handler, Rank 2 (3.3.5 only)

**Comment by lashia** [comment]
its coming from your pull request i added #16554

**Comment by tkrokli** [comment]
Interesting. If that is the case, it indicates that the SQL file is not needed
in the PR **[Beast Mastery hunter talent Animal Handler](https://github.com/TrinityCore/TrinityCore/pull/16554) #16554**
