### ISSUE TITLE
[3.3.5][Hunter] Core/Spell: Taming - required timer + target

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16727]
3.3.5 8e152e0d4a553bdc215d2c7fda41083b5382b235

Hunters' [Tame Beast](http://www.wowhead.com/spell=1515/tame-beast) ability does not require the hunter to keep aggro of the creature for the entirety of the channel duration to succeed on TC. It should.

**Comment by MrSmite** [comment]
Not sure if this is related but on core cebdf03349ed0c50a40cf52ddae887cf666d1eb5, the spell doesn't work at all. Once the channeling stops the combat log says "Tame beast fades from..." but the creature is never tamed.

I tried several different levels (10 to 6) ove 30 minutes and was not successful in getting any of them.

**Comment by Nawuko** [comment]
MrSmite you get a clean TC version?  If so on what spots or on what npcs it fails. I cannot confirm this.  Taming pets works fine for me.

Treestorn issue is valid. If the tame pet loses aggro it does not break the channel

**Comment by MrSmite** [comment]
> MrSmite you get a clean TC version?

@Nawuko - Thanks for reminding me. I had been working on a patch to allow other classes besides Hunter to use Tame Beast and even though I reverted the patch, there was a line I had written that was not part of the patch... naturally that line causes Finish() to never be called from EffectTameCreature().

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by MrSmite** [comment]
I haven't compiled a core recently but I dug up an older one and taming works properly.

rev ffe54eca6759

**Comment by Aokromes** [comment]
you can test on https://ubuntu.northeurope.cloudapp.azure.com

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
