### ISSUE TITLE
[3.3.5][Ulduar] Core/Scripts: Yogg-Saron Encounter Reset

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#16723]
**Description**: After start fight with Yogg-Saron not reseted Encounter.

**Current behaviour**: If raid wipe, the second attempt will not.

**Branch(es)**: 335

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/e60f575ac8d0c148f8f7ad1d38ee7c62c2c2254d

**TDB version**: TDB 335.60

**Operating system**: Ubuntu 14.04

**Comment by sirikfoll** [comment]
The trigger [Voice of Yogg Saron(33280)](http://wotlk.openwow.com/npc=33280) is responsable for the evade, but he gets threat with [Sara (33134)](http://wotlk.openwow.com/npc=33134) and [Brain of Yogg-Saron(33890)](http://wotlk.openwow.com/npc=33890) and not sure, but possible with [Yogg-Saron(33288)](http://wotlk.openwow.com/npc=33288) too. Noone of the others evade, and consequently the trigger not evade and the encounter never resets

**Comment by sirikfoll** [comment]
Well, dunno a better way to do it, this works at least:
```diff
diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
index 7da6717..363400c 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp
@@ -522,6 +522,19 @@ class boss_voice_of_yogg_saron : public CreatureScript
                 if (!UpdateVictim())
                     return;
 
+                bool _canEvade = true;
+                for (std::list<HostileReference*>::const_iterator itr = me->getThreatManager().getThreatList().begin(); itr != me->getThreatManager().getThreatList().end(); ++itr)
+                {
+                    if ((*itr)->getTarget()->GetTypeId() == TYPEID_PLAYER)
+                    {
+                        _canEvade = false;
+                        break;
+                    }
+                }
+
+                if (_canEvade)
+                    EnterEvadeMode(EVADE_REASON_NO_HOSTILES);
+
                 events.Update(diff);
                 // don't summon tentacles when illusion is shattered, delay them
                 if (_illusionShattered)

**Comment by peycho** [comment]
The code can't be compiled with the current state of the code.

**Comment by illfated** [comment]
that code in https://github.com/TrinityCore/TrinityCore/issues/16723#issuecomment-192361737 is 2 years old, so it needs to be rewritten
(lots of changes in the TC source in that time, so it should not be a surprise)

**Comment by peycho** [comment]
Yeah, but the boss still experience the same bug.

**Comment by Keader** [comment]
After new threat system, triggers can have threat list?

**Comment by Killyana** [comment]
Yes npc_trigger that deal damage get stuck in combat.

**Comment by Killyana** [comment]
Known issues:
1. Ominous Cloud stop moving after a while: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_yogg_saron.cpp#L1157
2. Sara regen health even if she's in combat: * UNIT_FLAG_IN_COMBAT (0x80000)
3. Sara and  Voice of Yogg-Saron (Entry: 33280,  ScriptName: boss_voice_of_yogg_saron)  are in combat with each other during the combat and this will remains after a wipe so the encounter never reset.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c1df161e1ddf95584030480d3dcb15149aacd7a6 fixed the clouds movement.
Anything else or can we close this ?

**Comment by Killyana** [comment]
No it's the only remaining issue

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c1df161e1ddf95584030480d3dcb15149aacd7a6
