### ISSUE TITLE
[3.3.5] Crash: SimpleCharmedAI::UpdateAI()

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#16728]
https://gist.github.com/Nyeriah/f78af67bb176879ffc80

**Branch(es)**: 335

**TC hash/commit**:
rev: https://github.com/TrinityCore/TrinityCore/commit/fe707db96f711f94a461306748274fa0bffa0226

**Comment by ariel-** [comment]
Summoning @Treeston
