### ISSUE TITLE
[3.3.5] Core/Command: .npc delete guid and wp show off not working properly

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#16733]
d55d32fa0f7a

Both commands don't work properly because of the same fault. 
.wp show off doesn't delete the visual waypoint marker (because it can't find the guid)
.npc del guid also doesn't work because of the same reason.

Looking to the code:

cs_npc.cpp line 492:
unit = handler->GetSession()->GetPlayer()->GetMap()->GetCreature(ObjectGuid(HighGuid::Unit, cr_data->id, lowguid));

unit is always 0 (null)

cs_wp.cpp line 1025:
Creature\* creature = handler->GetSession()->GetPlayer()->GetMap()->GetCreature(ObjectGuid(HighGuid::Unit, VISUAL_WAYPOINT, guid));

creature is always 0 (null)

Unfortunately I couldn't find exactly where the problem is. ObjectGuid() seems to be correct. It contains the correct guid. Maybe it's GetCreature().

**Comment by Magnifikator** [comment]
Ok, so far as I know it has something to do with using object lowguid instead of object counter at ObjectGuid()

**Comment by Shauren** [comment]
Ok I know what is wrong in npc delete, still looking at wp show

**Comment by Magnifikator** [comment]
cs_wp.cpp line 1024
ObjectGuid::LowType guid = fields[0].GetUInt32();

That's also a database guid and not a counter. Same issue same reason.

I just don't know if you should give another parameter or change the ObjectGuid() method.

**Comment by Magnifikator** [comment]
@Shauren 

Need more information ?

**Comment by Rochet2** [comment]
> Need more information ?

he needs a cloning machine.

**Comment by Magnifikator** [comment]
What does that mean ... a cloning machine ?   :-)

**Comment by tkrokli** [comment]
@Magnifikator : I don't know if you have understood what Rochet2 meant yet, but I will explain:
"Shauren has got so much to do, he must be cloned to become available enough for our questions."

**Comment by Magnifikator** [comment]
No, I haven't, good to know, thanks :-)

**Comment by Aokromes** [comment]
117d1c3
