### ISSUE TITLE
[3.3.5][Hunter] DB/Spell: Lock and Load proc

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#16731]
**Description**:
After fbb525ad3f1b60bcc86e62be749b241872f7fe17 Lock and Load procs when it shouldn't.

**Branch(es)**: 335/6x
335

**TC hash/commit**:
49de12b1cfaca7f089a1ba2660de4a8644a72e2c

**Comment by tkrokli** [comment]
Commit https://github.com/TrinityCore/TrinityCore/commit/fbb525ad3f1b60bcc86e62be749b241872f7fe17 was sourced from https://github.com/TrinityCore/TrinityCore/issues/15262 "Lock and Load Not working".

**Comment by Re3os** [comment]
```sql 
UPDATE `spell_proc_event` SET `SchoolMask`='0', `SpellFamilyName`='9', `SpellFamilyMask0`='0', `SpellFamilyMask1`='0', `SpellFamilyMask2`='0', `procFlags`='2430272', `procEx`='0', `ppmRate`='0', `CustomChance`='0', `Cooldown`='22' WHERE (`entry`='-56342');
```

**Comment by tkrokli** [comment]
@Re3os : what you have got there is basically commit https://github.com/TrinityCore/TrinityCore/commit/fbb525ad3f1b60bcc86e62be749b241872f7fe17 , but with ' ' added around the numbers.

**Comment by Aokromes** [comment]
Indeed, it's what we already have on repo.

**Comment by mayaren888** [comment]
@Re3os    so  nice   good working

**Comment by Keader** [comment]
Accourding Spell work, flag should be: 

> **Proc flag 0x00240000 (2359296), chance = 100, charges - 0**

But... with this flag, proc with traps, but dont proc with black arrow.

**Comment by ccrs** [comment]
just create a spellscript and add all the spells that should proc it...
if someone makes a list... :dancer:

**Comment by Keader** [comment]
60210 [Freezing Arrow Effect] R1

 3355 [Freezing Trap Effect] R1
 14308 [Freezing Trap Effect] R2
 14309 [Freezing Trap Effect] R3

spell 13812 = [Explosive Trap Effect] R1
spell 14314 = [Explosive Trap Effect] R2
spell 14315 = [Explosive Trap Effect] R3
spell 27026 = [Explosive Trap Effect] R4
spell 49064 = [Explosive Trap Effect] R5
spell 49065 = [Explosive Trap Effect] R6

spell 13797 = [Immolation Trap] R1
spell 14298 = [Immolation Trap] R2
spell 14303 = [Immolation Trap] R3
spell 14304 = [Immolation Trap] R4
spell 14305 = [Immolation Trap] R5
spell 27023 = [Immolation Trap] R6
spell 49053 = [Immolation Trap] R7
spell 49056 = [Immolation Trap] R8

spell 3674 = [Black Arrow] R1
spell 63668 = [Black Arrow] R2
spell 63669 = [Black Arrow] R3
spell 63670 = [Black Arrow] R4
spell 63671 = [Black Arrow] R5
spell 63672 = [Black Arrow] R6
