### ISSUE TITLE
[3.3.5] .wp modi move and del results in a crash

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#16732]
d55d32fa0f7a

.wp modi move and del results in a crash because of 2 problems in cs_wp.cpp:

- 1. On about line 600 the result of the 2nd query should be like that, otherwise you lost the reference and it will crash later:
```
            stmt->setString(5, maxDiff);
            result = WorldDatabase.Query(stmt);

            if (!result)
            {
                handler->PSendSysMessage(LANG_WAYPOINT_NOTFOUNDDBPROBLEM, wpGuid);
                return true;
            }
```

- 2. The 2nd problem is more difficult to describe for me. As I understand it works like this:
Waypoints are searched fist by guid and if it fails in a 2nd. try by position.

I belive that something is wrong with the first search. When I select a visual waypoint the search by guid always fails and I get a the message LANG_WAYPOINT_NOTFOUNDSEARCH. 

The guid is getting here: wpGuid = target->GetGUID().GetCounter();
The prepared statement is: WORLD_SEL_WAYPOINT_DATA_BY_WPGUID 
that is: "SELECT id, point, delay, move_type, action, action_chance FROM waypoint_data WHERE wpguid = ?"

Locking to the table waypoint_data row wpguid I have a complete different value. That's the reason why the first search always fails.

Sorry guys, can't describe it better, atm.

**Comment by Aokromes** [comment]
#9532

**Comment by Magnifikator** [comment]
You referenced it to an issue from 2013. But some months before the waypoints are working correct. I have done a lot of wps.

**Comment by Magnifikator** [comment]
And it has nothing to do with my issue. But it's ok, close it as you close my message always :-(

**Comment by Aokromes** [comment]
Are you sure? https://github.com/TrinityCore/TrinityCore/issues/created_by/Magnifikator

**Comment by Shauren** [comment]
indeed unrelated to #9532

**Comment by Magnifikator** [comment]
We don't need that to discuss it here Aokromes, you know exactly about what I'm speaking

**Comment by DDuarte** [comment]
Don't ignore the issue template report, especially the part where it says that if this is a crash report you need to post a crashlog.

**Comment by Magnifikator** [comment]
Why should I sent you a crash report when I give you the fix ?

**Comment by DDuarte** [comment]
If this is a fix submission (I couldn't tell it from the poor "issue" description), perhaps you can submit a PR instead? Or at least a diff?

**Comment by Magnifikator** [comment]
Sorry I can't. If you want that give me a tutorial how I can do that.

Trinity original:
```
            PreparedQueryResult queryResult = WorldDatabase.Query(stmt);

            if (!queryResult)
            {
                handler->PSendSysMessage(LANG_WAYPOINT_NOTFOUNDDBPROBLEM, wpGuid);
                return true;
            }
```

my proposal:
```
            result = WorldDatabase.Query(stmt);

            if (!result)
            {
                handler->PSendSysMessage(LANG_WAYPOINT_NOTFOUNDDBPROBLEM, wpGuid);
                return true;
            }
```

the crash is because later in the source you have:
```
        do
        {
            Field* fields = result->Fetch();
            pathid = fields[0].GetUInt32();
            point  = fields[1].GetUInt32();
        }
```

**Comment by Magnifikator** [comment]
Is working, thanks

**Comment by DevQuad** [comment]
I'm not sure, but this changes the error occurred with .mod speed command, but rather leads to crash.
[Crash](http://s019.radikal.ru/i612/1603/01/f756273f2dbc.jpg)

**Comment by Magnifikator** [comment]
Can't see anything related from .mod speed with .wp modify.
