### ISSUE TITLE
Core/ScriptedAI: Despawn at evade mechanic makes the npc engage walking after wipe

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#16738]
**Description**:
Despawn at evade mechanic implemented on BossAI makes the boss enter combat walking after one wipe.

Example: Lich King.

510bb30b2ca44f082354504b7092eee67a994ecf

**Comment by Keader** [comment]
Reproduce steps?

**Comment by ccrs** [comment]
I guess it was 1 in million chance, can't reproduce it anymore on head.
