### ISSUE TITLE
[3.3.5] Water Elemental pet not stored while mounted

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16742]
3.3.5 8e152e0d4a553bdc215d2c7fda41083b5382b235

If a mage summons a [permanent Water Elemental pet](http://wotlk.openwow.com/spell=31687) by using [Glyph of Eternal Water](http://wotlk.openwow.com/item=50045) and then mounts up, the Water Elemental will not be temporarily unsummoned like other permanent pets, but will instead follow the mage along the ground, pulling mobs/dying along the way.

**Comment by Rushor** [comment]
it think the creature should not despawn, but instead behave passive like the pets in arena

**Comment by Treeston** [comment]
Any permanent pet should temporarily despawn while the owner is mounted.

**Comment by Keader** [comment]
Maybe #15749 ?
But even if there what Rushor said... he not pulling any creature or take any damage.

**Comment by Saben65** [comment]
http://www.wowhead.com/forums&topic=148315/a-few-questions-about-perm-water-elemental

According to this, in 3.3.2 perm water elementals would follow you if you were on a flying or ground mount.

**Comment by Treeston** [comment]
Bleh. Stupid Blizzard.
