### ISSUE TITLE
3.3.5 Permanent Updating Realm List...

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16743]
**Description**:
Updating Realm List...

**Current behaviour**: Tell us what happens
Spam Updating the Realmlist in the authserver

**Branch(es)**: 335/6x

**TC hash/commit**:TC>TrinityCore rev. 7ee7548b9443 2016-03-07 10:35:33 +0100 (335 branch)

**Operating system**: Windows 7 64Bit

**Comment by DDuarte** [comment]
Why is this an issue? The message appears every 10 seconds (`RealmsStateUpdateDelay` in config)

**Comment by Tauriella** [comment]
Arrrg sorry my mistake

**Comment by DDuarte** [comment]
Ahm, you didn't need to close the issue. I just wanted to hear your opinion.

**Comment by Tauriella** [comment]
in my config is the timer every 20 seconds but in my opinion is this quite annoying 
But i can turn off this feature

**Comment by Shauren** [comment]
Then disable this log in config - server.authserver is the logger used at level INFO

**Comment by Tauriella** [comment]
Yes i have

**Comment by Shauren** [comment]
in any case, not a bug
