### ISSUE TITLE
[3.3.5] Format Exception Crashes

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#16751]
**Current behaviour**: Tell us what happens

Using certain commands crashes the server because even though the text was changed, the order which the params are sent at core is still the same, resulting in a format exception crash.

https://gist.github.com/Nyeriah/1531b1285a6b667779cb

**Steps to reproduce the problem**:

1. Log in-game
2.  Use .mod speed, or mod size
3.  Profit

**Branch(es)**: 335

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/a41bd8e94379224c081764a14a8498f0b96b6e3c

Blame goes to https://github.com/TrinityCore/TrinityCore/commit/7ee7548b9443c16d3fe01d4c95493d250b7efd9b

I have managed to crash it with both mod speed and mod size, I haven't tested all of them but I wonder if there are more of these text changes that haven't been tested and could produce the same result.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_modify.cpp#L476

**Comment by Treeston** [comment]
[Here](https://gist.github.com/Treeston/a02f188c940a8ca0ea83)'s a side-by-side of all lines changed by that commit, if someone could go through them.

**Comment by DDuarte** [comment]
Only speed related ones seem to have issues: 137, 139, 141, 143, 145, 147
