### ISSUE TITLE
Creatures are missing equipment

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#16759]
https://github.com/TrinityCore/TrinityCore/commit/d1efa0b8b1a553b184f884ad757bcebc913f117b

A ton of spawned creatures are missing equipment when they weren't before, and all temporary summons are missing equipment.
Caused by https://github.com/TrinityCore/TrinityCore/issues/16416, https://github.com/TrinityCore/TrinityCore/commit/a5042419106f4478647d78fb3d9e7a9d8fa6ed9a

**Comment by Aokromes** [comment]
test https://github.com/TrinityCore/TrinityCore/pull/16638

**Comment by Aokromes** [comment]
#16587

**Comment by Aokromes** [comment]
No no, this is no longer issue, also it was duplicate.

**Comment by Kizarr** [comment]
http://wow.zamimg.com/uploads/screenshots/normal/90137-scarlet-infantryman.jpg 
Npc: http://www.wowhead.com/npc=28609/scarlet-infantryman#screenshots:id=90137

Partial fix for shield. I haven't found weapon yet. 

Item for shield equip http://www.wowhead.com/item=12932/monster-shield-scarlet-crusade-a02

The weapon I'm still looking for.
