### ISSUE TITLE
Extractors Memory Leak

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#16757]
**Description**:
The vMap4extractor will not close completly after using it in a bat file and if a error is returned.

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Use it in a batch file
2. Overwrite the file with a new created file after an extract error (Custom Patch)
3. Result is : file is open by another process

**Branch(es)**: 335/6x
335

**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/c9f9e93c227103b405b382bd2aadb6dd83fa3c72

**TDB version**:
335_60

**Operating system**:
Windows 10 x64

**Comment by jackpoz** [comment]
process not closing is not really a memory leak, it's a process not closing

**Comment by Shoxxo** [comment]
Yup :) But using stable core i change only client not the core .

**Comment by tkrokli** [comment]
Isn't the TC 3.3.5 source code fror the extractors written specifically to match the 3.3.5a (12340) client files, making it difficult to use the extractors on game clients with a different build or patch version?

**Comment by jackpoz** [comment]
> if a error is returned

Please include the error returned

**Comment by Shoxxo** [comment]
no error, only the program say, it is in use by another process after clsing it, but i change it to one rewritten code now it works.
