### ISSUE TITLE
Creature spawn behavior with `creature_template`.`RegenHealth`=0

### ISSUE THREAD

**Issue by Trisjdc** [TrinityCore/TrinityCore#16756]
https://github.com/TrinityCore/TrinityCore/commit/c9f9e93c227103b405b382bd2aadb6dd83fa3c72

If RegenHealth=0, creature takes in the health value from `creature`.`curhealth`. This kind of sucks. since creatures can be in several modes with several different health values, and the default values on the DB cause nasty issues if you set RegenHealth=0, no warnings given. You need to 'hack' and set the health value to some health larger than all modes, if you want the creature to have max health. It's not very portable.

I suggest changing `creature`.`curhealth` to a signed int, and set it to -1 for every creature that doesn't use RegenHealth in it's template. It will be equivalent to max health.

That way one could also remove Creature::setRegeneratingHealth from the cpp scripts that mostly don't have to be there, and just set the `creature_template`.`RegenHealth` values accordingly. At least without concerns for scripts breaking because creatures suddenly have 1 health.

**Comment by dr-j** [comment]
Well even on retail hp of npcs gets glitched ie mobs respawning with random amounts of hp (can be seen especially in Tanaan), have seen this fairly regular where you see unaggrod mobs with varying amounts of hp   you may see two of exactly same mob (one with half hp, the other with full hp sometimes you come across mobs with even less than half hp.
