### ISSUE TITLE
[6.x] Phased areatriggers and gameobjects not working

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#16758]
**Current behaviour**:
Areariggers: When you trigger an areatrigger in other phase than 1, most of areatriggers are not triggered at all (verified by turning on .debug areatrigger and sniffs)
Gameobjects: Gameobjects in other phase than 1 which have a spell to be casted on use (i.e. GO 210986 with spell 114580), the spell is not casted at all. (verified by sniffs)

**Expected behaviour**: All areatriggers should be triggerable in any phase, all gameobjects should cast appropriate spell in any phase.

**Steps to reproduce the problem**:
1. phase any area
2. try to trigger areatrigger/use gameobject (type 6 or 10)

**Branch(es)**: 6x

**TC hash/commit**: 52bb6485417494e58361a75fcf73cf5f0a1d09c5

**TDB version**: TDB 6.03

**Operating system**: Win 64

**Comment by NorthStrider** [comment]
triggering an area trigger is a clientside thing so if the client doesn't tell the server that he triggered an areatrigger it means that the client doesn't notice any areatrigger. If you are trying this on maps like Gilneas, Shadow Highlands or Uldum it could mean that you're lacking a terrain swap at this situation. Areatrigger are also bound to entire mapshiftings.

**Comment by Lopfest** [comment]
Im trying it on Wandering Isle and I'm on correct terrainswap. The triggers are recognized and triggered in phase 1, but not in phase they should be.

**Comment by NorthStrider** [comment]
Are you sure you're using the correct phaseId at the point where you're trying to trigger something?

**Comment by Lopfest** [comment]
Yes I am sure. Here are data from sniffs when entering the area:
```sql
ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C)
PhaseShiftFlags: 24
PhaseShiftCount: 1
PersonalGUID: Full: 0x0
[0] PhaseFlags: 1
[0] Id: 1323
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 2
[0] VisibleMapID: 683 (683)
```
The first picture is phased (not working trigger), second picture unphased (working trigger)
![trigger](https://cloud.githubusercontent.com/assets/32191/13706917/84721384-e7a7-11e5-8c49-e772bc858350.png)

**Comment by streetrat** [comment]
note that areatriggers in the client dbc have some unknown *phase-flags* or similiar.
so probably the phase packet is sending something wrong, or simply, that trigger isnt used on blizz either (just check blasted lands red-portal map swap, there is no areatrigger on the swapped map in dbc files, but ofc you get ported on blizz :) ) so there must be server-side areatriggers at blizz

**Comment by Lopfest** [comment]
Here are some findings from AreaTrigger.dbc:

trigger_id | map_id | pos_x | pos_y | pos_z | field5 | field6 | ...
---------- | ------  | ----- | ----- | ----- | ------ | ------ | ---
7812 | 860 | 1303.464 | 3441.964 | 115.1266 | 1 | 0 | ...
7756 | 860 | 1145.142 | 3435.597 | 104.9726 | 0 | 838 | ...
7748 | 860 | 1201.563 | 3507.858 | 85.84122 | 0 | 0 | ...

Areatriggers with field5 = 1 can be triggered in any phase.
Areatriggers with field5 = 0 and field6 > 0 can be triggered only in phase specified in field6 field.
Areatriggers with field5 = 0 and field6 = 0 can only be triggered in default phase. **This is wrong**.

**Comment by Shauren** [comment]
field5 = PhaseUseFlags
field6 = PhaseId
field7 = PhaseGroupId

**Comment by Lopfest** [comment]
Could be a solution something like this?
Create new table `areatrigger_phase` with columns `entry`, `PhaseId`, `PhaseGroup` which would overwrite the DBC values.
Entry in DB with PhaseId=0 and PhaseGroup=0 would mean, that PhaseUseFlags will change to 1. (areatrigger can be triggered in any phase)
Entry in DB with PhaseId=x or PhaseGroup=y would mean, that PhaseUseFlags will be 0 and PhaseId or PhaseGroup will be overwritten with the value from DB.

**Comment by Shauren** [comment]
This is the client not sending us CMSG_AREATRIGGER opcode, not us refusing to handle it. Overriding anything serverside doesn't make sense

**Comment by streetrat** [comment]
probably you need to use the correct flags + phaseid in SMSG_PHASE_SHIFT_CHANGE packet for client to handle it right
.
.
[0] PhaseFlags: 1
[0] Id: 1323

**Comment by Lopfest** [comment]
```sql
ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C)
PhaseShiftFlags: 0
PhaseShiftCount: 1
[0] PhaseFlags: 1
[0] Id: 1323
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 4
[0] VisibleMapID: 545 (545)
[1] VisibleMapID: 683 (683)
```

This is sniff from my localhost.
The only possible relevant difference is in PhaseShiftFlags. (idk what that is)
In offic its 24, on my localhost its 0.

**Comment by Lopfest** [comment]
Anyone has any idea how to fix this? I find this issue one of the most crucial for people who are working on offi-like fixes of quests/zones.
Also, we've talked only about areatriggers above. What about phased gameobjects?

**Comment by msoky** [comment]
any news?
