### ISSUE TITLE
Quest 31450

### ISSUE THREAD

**Issue by Abrek** [TrinityCore/TrinityCore#16768]
**Description**: Quest 31450

**Current behaviour**: Cant finished, missing "I'm ready to decide" gossip option
**Expected behaviour**: You should see a window with a choice of faction: Horde or Alliance
 
**Branch(es)**: 6x

**TC hash/commit**: 16953c9025525ba88967094a9ad883aca7f8f317

**TDB version**: TDB last and ultimates updates to today

**Operating system**: Debian
Screen: http://fastpic.ru/view/73/2016/0312/e9627409448ffb7531559d85587b0710.jpg.html
 This screen after take quest = 0:13 https://www.youtube.com/watch?v=JYHKyDuW2i4

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by MitchesD** [comment]
This zone isn't scripted yet, there is already a issue for that.

**Comment by Aokromes** [comment]
Not to say you can't reach that quest on a clean TrinityCore. If you are reporting issues you must report with clean core. If you have fixed quest chain, share fixes.
