### ISSUE TITLE
Quest:I Sense a Disturbance, ID 12665

### ISSUE THREAD

**Issue by cmakee** [TrinityCore/TrinityCore#16767]
**Description**: Speak to her to be able to ride one of her children stealthily into the Altar of Quetz'lun

**Current behaviour**: If you click "Call for one of your Children", then does nothing
http://www.directupload.net/file/d/4291/ha6v22t5_jpg

**Branch(es)**: 335

**TC hash/commit**: c190577

**TDB version**: 2713907

**Operating system**: Linux

**Comment by dr-j** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/15981
