### ISSUE TITLE
Quest: Cold Hearted, ID: 12856

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16766]
**Description**: The quest itself works

**Current behaviour**: The proto-drakes fly too slow, look here the Video for exampel 
https://www.youtube.com/watch?v=L_JXPyfUFYI

**Branch(es)**: 335

**TC hash/commit**: c190577

**TDB version**: 2713907

**Operating system**: Linux

**Comment by Rushor** [comment]
general problem, vehicles sometimes become reaaaly slow (no idea how to reproduce this)

**Comment by Xanvial** [comment]
When you fly out of Dun Niffelem, the Proto-drakes speed will reset to normal (as fast as flying mount)

**Comment by Rushor** [comment]
so no issue?

**Comment by tkrokli** [comment]
I don't think this is an issue, because inside Dun Niffelem it is an advantage to move slow to aim for and pick up the Brunnhildar prisoners. I have not done this quest on retail since 2010, so I don't know what the actual behaviour should be, though.

**Comment by Rushor** [comment]
report a new issue you (the "ghost" user (whoever this was)) will see this again with detailed information on the movementspeed (which speed in which part of the quest is to slow?)
