### ISSUE TITLE
[3.3.5] Something changed with account name rules ?

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#16770]
cebe6122ad33

Since my last core update some players claims that they can not login any more. Up to the previous update in the beginning of February everything was fine.

It seems that account names with special chars (like german ö ä ü) are not allowed any more.

Testing: 
.acc crea schäfer test
Creates an account SCHäFER in the database.
But not possible to login with schäfer/test .

~~After that I tried to create a similar account:~~
~~.acc crea schafer test~~
~~Result message: "An account with this name already exists!"~~
~~However it doesn't.~~

~~Then:~~
~~.acc del schäfer~~
~~.acc crea schafer test~~
~~Now you can login with schafer/test~~

It seems to be some mismatch with chars. (uppercase/lowercase and creating the hash, maybe?) As far as I have seen in the source there was quite a lot of changes in middle of Feb. in the authserver.

**Comment by cmakee** [comment]
Mal eine andere Frage, hast du die DB auf UTF8 eingestellt und die Char DB mit UTF8 eingespielt (Heidi SQL)?

Könnte mir vorstellen,d as es Probleme machen könnte

**Comment by Magnifikator** [comment]
The table and database is UTF-8 and utf8_general_ci (means disregarding lower/uppercase)

Beside that here's a discussion about utf8_general_ci and utf8_unicode_ci. But I'm not sure if it tangents to this issue at all:
http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci

**Comment by Shauren** [comment]
It is only partly related to this.

Summing up:
* login is fixed in 2a37266269d317a7856ce2126c812f56cbd00691
* "An account with this name already exists!" is not possible to fix - mysql does not have any case-insensitive and accent-sensitive utf8 collation
