### ISSUE TITLE
3.3.5a Quest 7461 - The Madness Within

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#16778]
**Description**: 3.3.5a Quest 7461 - The Madness Within

**Current behaviour**: Kill the guardians around the 5 power pylons, but the prison shield never goes away so you can get to the demon inside.

**Expected behaviour**: The prison shield should go away and you be able to get to the demon.

**Steps to reproduce the problem**:

1. Pick up the quest from the lady.
2. Kill the guardians surrounding the 5 pylons.
3. Go back to the prison and the shield should be gone so you can kill the demon.

**Branch(es)**: 335

**TC hash/commit**: ecd74a8cccc1

**TDB version**: 335.60

**Operating system**: Win32, Release

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#14685
