### ISSUE TITLE
3.3.5 Mount Bug

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16773]
**Description**:
This message comes if you mount or unmount

Received not handled opcode [CMSG_MOVE_SET_COLLISION_HGT_ACK 0x517 (1303)] from
[Player: Mondain GUID Full: 0x000000000000003a Type: Player Low: 58, Account: 8]

**Steps to reproduce the problem**:

1. mount or unmount

**Branch(es)**: 335/6x

**TC hash/commit**:
TC>TrinityCore rev. 7f1cef3fa7f4 2016-03-13 00:57:23 +0100 (335 branch)
**TDB version**:

**Operating system**:

**Comment by TecDian** [comment]
**Core rev:** https://github.com/TrinityCore/TrinityCore/commit/fdc8b7b38a2aa974427e79454e1f94ef67a133ea 2016-03-13 20:18:22 +0100 (3.3.5 branch)

I can confirm this.

**Comment by Aokromes** [comment]
Confirmed on fdc8b7b38a2a
