### ISSUE TITLE
[6.x] Enchantment visual not working

### ISSUE THREAD

**Issue by Jarts37** [TrinityCore/TrinityCore#16776]
**Description**:
Enchantments aren't properly working since 6.1 or 6.2 rev

**Current behaviour**: 
When you enchant an item, there are no visual on the item, but you can see the enchant when you inspect your item or when you are on the character selection menu.

**Expected behaviour**: Tell us what should happen instead
No visual at all in game

**Steps to reproduce the problem**:
1. Log in game
2. .additem 30278 then .additem 115975
3. Use the enchantment on the sword (no visual on the weapon)
4. Inspect your weapon (visual working)
5. Log out, on the character selection menu (visual working)

**Branch(es)**: 6x

**TC hash/commit**: 50c8efecc5d3c7336a0f77ce7659d383293ad0f5

**TDB version**: TDB 6.03

**Operating system**: Win64

**Comment by uipoet** [comment]
Having the same issue with death knight runeforged weapons. Default animations of a weapon do display, just not enchanted/runeforged.
