### ISSUE TITLE
[6.x] DB/Creature: Prince Liam Greymane (34850) fix

### ISSUE THREAD

**Issue by Heaven31415** [TrinityCore/TrinityCore#16771]
**Description**:
Prince Liam Greymane (34850) located at Gilneas City in first phase is missing:
1. mount 
2. gossip 
3. smartAI 

I used sniffer on build **20886** to obtain informations. After that every .sql statement was checked for correctness, in-game behavior, it was also consulted with _**Nayd**_.

This fixes every described above problem, he will be mounted, with gossip and proper smartAI.

[worldDBpart](http://pastebin.com/tGv7YmcY)
[hotfixesDBpart](http://pastebin.com/gcGUGTHN)

**Branch**: 6x
**TC hash/commit**: ce88d737cfc6
**TDB version**: 6.0.3

**Comment by Aokromes** [comment]
The hotfixes part is already on db.
