### ISSUE TITLE
[3.3.5] Vehicle::InstallAccessory assert crash

### ISSUE THREAD

**Issue by Riztazz** [TrinityCore/TrinityCore#16777]
**Description**:
Assert crash after server DC/restart. After reverting the change in GridDefines https://github.com/TrinityCore/TrinityCore/commit/761c82e65ae01e56d0efc7a7ba0dabdb2e44c5a7
crashes stopped, but i have no idea why mobs fall to that position

crashlog, if someone needs the whole thing let me know in comments;p
http://paste2.org/LJnneeg7

**Steps to reproduce the problem**:

1. Enter utgarde keep
2. go to this spot in said instance: http://i.imgur.com/DR9bCYD.jpg
3. Kill all drakes in that spot
4. type .saveall
5. shut down worldserver.exe and launch it again
6. Enter UK again

Assert crash because for some reason position Z of dead drakes is set to -2000000.000000

**Branch(es)**: 335/6x
335

**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/895878010e7dc3fb342bcae5e216bc1543828213

**Operating system**:
Windows 7

**Comment by w1sht0l1v3** [comment]
I can confirm it also.

**Comment by xjose93** [comment]
I can confirm too but sadly i haven't the crashlogs :(

**Comment by jackpoz** [comment]
there might be 2 issues here: 1) drakes being moved to invalid coordinates on death and 2) Vehicle::InstallAccessory() asserting on something that can actually happen

**Comment by jackpoz** [comment]
> go to this spot in said instance: http://i.imgur.com/DR9bCYD.jpg

a .gps output would help, or even .go xyz command

**Comment by jackpoz** [comment]
The proto drakes were still were after killing them, saving, restarting worldserver. Please report any weird behavior of dead creatures that can fly, I couldn't find any other case worth to test.
