### ISSUE TITLE
Quest: The Iron Colossus, ID: 13007

### ISSUE THREAD

**Issue by cmakee** [TrinityCore/TrinityCore#16784]
**Description**: Use a Tamed Jormungar to defeat the Iron Colossus and return to Bouldercrag the Rockshaper at Bouldercrag's Refuge. 

**Current behaviour**:  You can use a Tamed Jormungar, but he had no Spells

Here is a Video -> https://www.youtube.com/watch?v=kDn4Ky5bIwo
And i think that are the Spells -> http://www.wowhead.com/npc=30301/tamed-jormungar 

**Branch(es)**: 335

**TC hash/commit**: c190577

**TDB version**: 2713907

**Operating system**: Linux

**Comment by Aokromes** [comment]
#4974
