### ISSUE TITLE
[3.3.5][Bug] Missing Scripts on Lord Kazzak (World Boss)

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#16790]
**Description**:
Lord Kazzak (World Boss) located at "The Tainted Scar" (Blasted Lands) has no scripts.
**Current behaviour**: You can Tank'n'spank him.

**Expected behaviour**: He should have scripts:
http://wowwiki.wikia.com/wiki/Lord_Kazzak_(tactics)

**Steps to reproduce the problem**:

1.  use .go xyz -132213.36 -2439.87 0.41 0
2. aggro Lord Kazzak
3. verify that he has no scripts (no scriptname on .npc info)

**Branch(es)**: 335/6x

**TC hash/commit**: TrinityCore rev. 632e66784bb5+ 2016-03-15 01:12:21 +0000 (3.3.5 branch) (Unix, Release)

**TDB version**: TDB 335.57

**Operating system**: Centos 7 64 bits

**Comment by Shauren** [comment]
> Patch 2.0.3 (09-Jan-2007): Removed.

Yeah, no.

**Comment by EternalDark** [comment]
Lord Kazzak in by the sword Archimonde restored the Dark Portal in the events of the Burning Crusade Outland has moved to the Throne of Kil'jaeden, in his place in the Tainted Scar Lord dwells Kruul.

**Comment by silvermcd123** [comment]
so it should not be there, still wrong.

**Comment by DDuarte** [comment]
It isn't there. There's only one creature_template of a creature named "Lord Kazzak" (entry = 12397) and it isn't spawned anywhere on current TDB.

You need to sort out your custom stuff....

**Comment by silvermcd123** [comment]
i'm sorry , other person reported me this. i was not sure.

**Comment by Kittnz** [comment]
In my eyes, the event scripts can be included. But disabled in game_event.

**Comment by Keader** [comment]
If we have sniffs, is possible :)

**Comment by Kittnz** [comment]
Well you don't need sniffs to script something most of the time. It helps to get the right spells etc ofc.
