### ISSUE TITLE
Boss Deathbringer Saurfang

### ISSUE THREAD

**Issue by Bodeguero** [TrinityCore/TrinityCore#16794]
When I go to attack the Orc (Boss Deathbringer Saurfang), my Worldserver.exe fall and crash. The error that appears in this is below:

boss_deathbringer_saurfang.cpp: 967 in npc_saurfang_event npc_saurfang_eventAI :: :: SetData ASSERTION FAILED: type && $$ date date <6

I'm using the Rev: https://github.com/TrinityCore/TrinityCore/commit/912514c198bd0f59bd22c4a189692aff5244f697

**Comment by DDuarte** [comment]
Follow the suggested issue template and post a crashlog. Edit your issue above and re-open.
