### ISSUE TITLE
[3.3.5][Bug - Quest] The Affray

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#16803]
**Description**:
The quest The Affray (1719) is supposed to be the final quest to receive berserker stance for warriors.

**Current behaviour**: It doesnt work, when you get to fight with Big Will he simply evades all the time.

**Expected behaviour**: You should be able to kill him.

**Branch(es)**: 335

**TC hash/commit**: TrinityCore rev. 5e74c2223bff+ 2016-03-16 21:40:15 +0100 (3.3.5 branch) (Unix, Release)

**TDB version**: TDB 335.57

**Operating system**: CentOS 7 64 bits

**Comment by silvermcd123** [comment]
https://www.youtube.com/watch?v=M7eK1eVC3zs&feature=youtu.be

**Comment by dr-j** [comment]
Cannot reproduce on revision https://github.com/TrinityCore/TrinityCore/commit/912514c198bd0f59bd22c4a189692aff5244f697

https://youtu.be/-L_ZNHn2wo4

**Comment by dr-j** [comment]
Also noticing in your video that big will appears with yellow name (like neutral npc) when should be hostile (red name)

**Comment by silvermcd123** [comment]
yes, i'm with .gm on thats why

**Comment by Aokromes** [comment]
Never use .gm on to test things.

**Comment by dr-j** [comment]
yes mmaps is enabled on realm

**Comment by silvermcd123** [comment]
@Aokromes i'm sorry but are you seeing me test anything on the video? i'm just watching someone else doing it and recording.

**Comment by dr-j** [comment]
Well to test this properly : -
1 Type
.gm  off
.gm visible on
.quest add 1718
.go creature 14137
2. Turn in http://www.wowhead.com/quest=1718/the-islander and take http://www.wowhead.com/quest=1719/the-affray
3. Move to Grate or type .go trigger 522

**Comment by silvermcd123** [comment]
dude, i tested without a gm account

**Comment by Killyana** [comment]
Cannot reproduce  rev. f835d16b2c87
