### ISSUE TITLE
[3.3.5][DB] sealed scroll case loot

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16801]
Description:Wrong sale list
Current behaviou: Can buy a lot of things
Expected behaviour:

1 forest frog (http://www.wowhead.com/npc=24396)
2.sealed scroll case http://www.wowhead.com/item=33926
3.Some items that should not exist.

Branch(es) :335/6x
TC hash/commit:https://github.com/TrinityCore/TrinityCore/commit/5e74c2223bff8a467d6f1ce18f6f08aa05e17019
TDB version:TDB60
dbupdate:2016_03_15_00_world.sql
Operating system:windows
patch:NO

Drug drawings and equipment do not exist in the box of things
http://www.wowdb.com/items/33926-sealed-scroll-case#related:contains-item

**Comment by Saben65** [comment]
Just glancing over it the loot_template looks correct for WotLK time. There appears to have been an update to it when Cataclysm was released. Is there anything specifically that you noticed is missing?

**Comment by Aokromes** [comment]
Yeah, report is indeed invalid, linking 4.0.3 item.
