### ISSUE TITLE
[6.2.3] DB/Creature: Disciple of Hate SAI (Baradin Hold - Alizabal thrash)

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16802]
**Description**:
Disciple of Hate SAI
**Current behaviour**: Tell us what happens
Not scripted.
**Expected behaviour**: Tell us what should happen instead
She is should have script.
**Steps to reproduce the problem**:

1. Enter in Baradin Hold.
2. add macro
/target Disciple of Hate
3. After focus target - start attack - she is dummy training.

**Branch(es)**: 335/6x
6.x.x Warlord of Draenor.
**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/a56a402190c885e51038df55654875cc9e875c03
**TDB version**:
6.x.x
**Operating system**:
Windows 7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
Maybe add condition - don't allow respawn if Alizabal die.
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
No.

``` SQL
-- Disciple of Hate SAI
SET @ENTRY := 56350;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,15000,15000,15000,15000,11,105859,1,0,0,0,0,2,0,0,0,0,0,0,0,"Disciple of Hate - Cast Run Through"),
(@ENTRY,0,1,0,0,0,100,0,25000,25000,25000,25000,11,105855,0,0,0,0,0,1,0,0,0,0,0,0,0,"Disciple of Hate - Cast Whirl of Blades");
```

**Comment by tkrokli** [comment]
Suggestion for your `comment` section in the SAI lines, you may want to add `- in combat -` like this:
```
,"Disciple of Hate - in combat - Cast Run Through"),
,"Disciple of Hate - in combat - Cast Whirl of Blades");
```
It is useful to document what the SAI line does by adding a description for all the active sections.

**Comment by EternalDark** [comment]
It is a trifle, issue will be hanging here still do not know how much.

**Comment by tkrokli** [comment]
It looks OK. As long as your SAI solves the issue, it will be added whenever the devs find time for it. :+1:
