### ISSUE TITLE
[3.3.5] DB/Item: Vessel of Rebirth

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#16809]
**Description:** Highlord Demitrian currently has only one gossip option and gives vessel of rebirth even if player does not already have either part of Bindings of the Windseeker. The gossip which is currently used to give this is the gossip for if player does not have Bindings of the Windseeker 

**Current behaviour:** Tell us what happens
Highlord Demitrian gives Vessel of Rebirth (using wrong gossip) even if player has not already got  either part of Bindings of the Windseeker

**Expected behaviour:** Tell us what should happen instead
Highlord Demitrian should Vessel of Rebirth only if player has already got  either part of Bindings of the Windseeker

**Steps to reproduce the problem**:
1. .go creature 42744
2. Speak to Highlord Demitrian and follow gossip right the way through
3. You will receive Vessel of Rebirth

**Branch(es)**: 335

**TC hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/912514c198bd0f59bd22c4a189692aff5244f697

**TDB version**: 335.60

``` sql
DELETE FROM `gossip_menu` WHERE `entry` IN (5689,5690);
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES 
(5689, 6842),
(5689, 6955),
(5690, 6956);

DELETE FROM `gossip_menu_option` WHERE `menu_id`= 5689;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `OptionBroadcastTextID`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`, `BoxBroadcastTextID`) VALUES 
(5689, 0, 0, 'I am listening, Demitrian.', 9298, 1, 1, 5688, 0, 0, 0, NULL, 0),
(5689, 1, 0, 'Give me the vessel, Highlord.', 9554, 1, 1, 5690, 0, 0, 0, NULL, 0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN(14,15) AND `SourceGroup`=5689;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(14, 5689, 6842, 0, 0, 2, 0, 18563, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have Bindings of the Windseeker'),
(14, 5689, 6842, 0, 0, 2, 0, 18564, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have Bindings of the Windseeker'),
(14, 5689, 6842, 0, 0, 2, 0, 19016, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have vessel of rebirth'),
(14, 5689, 6842, 0, 1, 14, 0, 7785, 0, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have vessel of rebirth'),
(14, 5689, 6955, 0, 0, 2, 0, 18563, 1, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player has Bindings of the Windseeker'),
(14, 5689, 6955, 0, 0, 2, 0, 19016, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have vessel of rebirth'),
(14, 5689, 6955, 0, 0, 14, 0, 7785, 0, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player has not taken or been rewarded for examine the vessel'),
(14, 5689, 6955, 0, 1, 2, 0, 18564, 1, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player has Bindings of the Windseeker'),
(14, 5689, 6955, 0, 1, 2, 0, 19016, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player does not have vessel of rebirth'),
(14, 5689, 6955, 0, 1, 14, 0, 7785, 0, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip menu text if player has not taken or been rewarded for examine the vessel'),
(15, 5689, 0, 0, 0, 2, 0, 18563, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have Bindings of the Windseeker'),
(15, 5689, 0, 0, 0, 2, 0, 18564, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have Bindings of the Windseeker'),
(15, 5689, 1, 0, 0, 2, 0, 18563, 1, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip option if player has Bindings of the Windseeker'),
(15, 5689, 1, 0, 0, 2, 0, 19016, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have vessel of rebirth'),
(15, 5689, 1, 0, 0, 14, 0, 7785, 0, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have vessel of rebirth'),
(15, 5689, 1, 0, 1, 2, 0, 18564, 1, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip option if player has Bindings of the Windseeker'),
(15, 5689, 1, 0, 1, 2, 0, 19016, 1, 0, 1, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have vessel of rebirth'),
(15, 5689, 1, 0, 1, 14, 0, 7785, 0, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip option if player does not have vessel of rebirth');

DELETE FROM `smart_scripts` WHERE `entryorguid`=14347 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(14347, 0, 0, 0, 62, 0, 100, 0, 5689, 1, 0, 0, 85, 22958, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Highlord Demitrian - On Gossip Complete - Cast Summon Vessel of Rebirth DND'),
(14347, 0, 1, 0, 20, 0, 100, 0, 7786, 0, 0, 0, 12, 14435, 6, 60000, 0, 0, 0, 8, 0, 0, 0, -6241.77, 1717.14, 4.25042, 0.680879, 'Highlord Demitrian - On Quest Thunderaan the Windseeker Finished - Summon Creature Prince Thunderaan at XYZO');
```

However I am unable to confirm gossip menus as it appears we dont have a single sniff to help with this, have tried searching sniff db by both npc_text entries 6955 and 6956 but no results, also no results for the spell which creates item 22958 also gives no results from sniff db.(5689 is existing gossip menu on npc) 5690 is suspected as been correct but may not be.
Also no sniffs at all of the item vessel of rebirth

**Comment by Killyana** [comment]
For (15, 5689, 1 

you must add this as the player must have the 2 parts
``` sql
(15, 5689, 1, 0, 1, 2, 0, 18563, 1, 0, 0, 0, 0, '', 'Highlord Demitrian - Show gossip option if player has Bindings of the Windseeker'),

**Comment by Elarose** [comment]
No promises but in 19 days I have a character I can undelete that held both bindings. I did go to silithus with it and talk to Demitrian but never did do the part with needing the bars. Hope I didn't toss them.

**Comment by Elarose** [comment]
https://s21.postimg.org/5u1h6hwbb/dem1.png
http://wowwiki.wikia.com/wiki/Quest:Examine_the_Vessel 
I had completed the above quest, yet abandoning its successor allowed me to again see the gossip menu and options, even allowing me to get another vessel of  rebirth.
Will sniff as I see it's been updated while I was sleeping. ;P

**Comment by Elarose** [comment]
From a sniff for developers. - Needs Conditions and Sai fixing -
Sai is currently set to give Vessel of rebirth on gossip 5704, should be 5783

Conditions needed
**No bindings** 
Gossip menu 5675 text id 6812 should show with no bindings held
Gossip menu option 5675 option 0 should appear with no bindings held

**One or Both bindings held** 
Gossip menu 5675 text id 6954 should show with one or both bindings held
Gossip menu option 5675 option 1 should appear with one or both bindings held
Gossip menu option 5675 option 0 should NOT appear with one or both bindings held

**Having gone through all the consequent gossip options from 5675 optionid 1**
Player will now have Vessel of Rebirth quest 7785
Turning in quest 7785 will give the followup quest 7786

**On quest 7786**
Gossip menu 5675 text id 6812 is shown again
Gossip menu option 5675 option 0 should NOT appear on the gossip
Gossip menu option 5675 option 1 should NOT appear on the gossip

**Declining (or cancelling 7786)**
It reverts back to gossip menu and gossip option as above in '**One or Both bindings held**' , with quest 7786 available for pickup off the menu.

Player is able to get another 'vessel of rebirth' by going through the options again. It won't start the quest though as it's already been done to get to this point.
Going through the options to get the vessel of rebirh while holding one will close it out at end with no 'error text' or anything, you just will not receive one as it's unique.

```sql
DELETE FROM `gossip_menu` WHERE (`MenuId`=5783 AND `TextId`=6958) OR (`MenuId`=5784 AND `TextId`=6956) OR (`MenuId`=5781 AND `TextId`=6955) OR (`MenuId`=5675 AND `TextId`=6954);
INSERT INTO `gossip_menu` (`MenuId`, `TextId`, `VerifiedBuild`) VALUES
(5783, 6958, 28153), -- 14347
(5784, 6956, 28153), -- 14347
(5781, 6955, 28153), -- 14347
(5675, 6954, 28153); -- 14347 This gossip is shown when one or both bindings are held

DELETE FROM `gossip_menu_option` WHERE (`MenuId`=5783 AND `OptionId`=0) OR (`MenuId`=5784 AND `OptionId`=0) OR (`MenuId`=5781 AND `OptionId`=0) OR (`MenuId`=5675 AND `OptionId`=1);
INSERT INTO `gossip_menu_option` (`MenuId`, `OptionId`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `OptionType`, `OptionNpcFlag`,`ActionMenuID`, `VerifiedBuild`) VALUES
(5783, 0, 0, 'Give me the vessel, Highlord.', 9554, 1, 1, 0, 28153), -- This last option gives 'Vessel of rebirth' and should close his gossip 
(5784, 0, 0, 'I shall scour the earth for this Earthshaper. What of the essence?', 9552, 1, 1, 5783, 28153),
(5781, 0, 0, 'The Firelord and all who dare stand in my way shall reel from my wrath.', 9549, 1, 1, 5784, 28153),
(5675, 1, 0, 'What must be done?', 9547, 1, 1, 5781, 28153);

-- Update Highlord Demitrians gossip id (currently it is set on his first gossip option page)
UPDATE `creature_template` SET `gossip_menu_id`='5675' WHERE  `entry`=14347;
```
