### ISSUE TITLE
[3.3.5][Bug - Quest] The Balance of Light And Shadow

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#16816]
**Description**:
Quest located in eastern plaguelands and is a specific quest for priests. Quest starts from the item [The Eye of Divinity] that drops in Molten Core.

**Current behaviour**: When you accept the quest , nothing happens. 

**Expected behaviour**: Mobs should appear for the priest to heal.

**Steps to reproduce the problem**:

1. Create a priest (lvl 60 min) and .go xyz 3326.89 -2995.74 163.25 0 
2. add the item [The Eye of Divinity] (18646) and accept the quest
3. Notice that nothing happens

**Branch(es)**: 335

**TC hash/commit**: TrinityCore rev. b327dc3d4ab8+ 2016-03-20 23:20:08 +0100 (3.3.5 branch) (Unix, Release)

**TDB version**: TDB 335.57

**Operating system**: CentOS 7 64 Bits

**Comment by dr-j** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/11961
