### ISSUE TITLE
Death Knight Pet AOE Damage reduction Bug

### ISSUE THREAD

**Issue by mayaren888** [TrinityCore/TrinityCore#16825]
**Description**:
Death knight's pet can't enjoy a 90% AOE damage reduction
spell ID(55620,55623)   spell name: Night of the Dead
Pets are very easy to die
Death knight's evil gift to lose value
This bug troubled us for a long time, has not been resolved, the need for a good hearted people to help,
Fix this problem
**Branch(es)**: 335/6x
335
**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/4fbffab5f8a43410c4e4487e15f22a5173b9bc9e
**TDB version**:
TDB335.60
**Operating system**:
win

spell_pet.cpp
```
void CalculateAvoidanceAmount(AuraEffect const* /* aurEff */, int32& amount, bool& /*canBeRecalculated*/)
{
    if (Unit* pet = GetUnitOwner())

    {

        if (Unit* owner = pet->GetOwner())

        {

               // Army of the dead ghoul
               if (pet->GetEntry() == ENTRY_ARMY_OF_THE_DEAD_GHOUL)
                  amount = -90;
               // Night of the dead
               else if (Aura* aur = owner->GetAuraOfRankedSpell(SPELL_NIGHT_OF_THE_DEAD))
                   amount = aur->GetSpellInfo()->Effects[EFFECT_2].CalcValue();

         }

    }
}

**Comment by Rushor** [comment]
duplicate https://github.com/TrinityCore/TrinityCore/issues/16674
