### ISSUE TITLE
[335] Pets drop target after every pet spell cast

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#16824]
**Description**:

Pets drop their target whenever they autocast a spell and reacquire it on next attack. This makes /assist macros buggy.

**Current behaviour**:

When you send your pet to attack, you will see a targeting ring on the mob's feet. When the pet casts, for example, claw, the pet will lose the target and on its next attack the targeting ring will appear again. During this "downtime", /assist macros fail becaus the pet has no target.

**Expected behaviour**:

Pets should not lose targets after every attack.

**Steps to reproduce the problem**:

1. Create the following macro and put it on your hotbar: **/assist pet**
3. Open the "interface" options and make sure "Attack on assist" and "Autoswitch attack / autoshot" are checked
4. Create a hunter and get any pet
5. Find a target of appropriate level so it or the pet doesn't die too quickly
6. Stay at max shooting range and send the pet to attack. Notice the selection ring that appears
7. Deselect the target and click the macro while the pet is running to it, notice you begin shooting immediately
8. Deselect the target and watch the pet fight. Notice after each autocast the selection ring will flicker to indicate the pet is dropping / selecting the target again.
9. Click the macro and notice it is less responsive in selecting and attacking your pet's target

**Branch(es)**: 335
**TC hash/commit**: cebdf03349ed0c50a40cf52ddae887cf666d1eb5
**TDB version**: TDB_full_world_335.60_2015_11_07.sql
**Operating system**: Windows XP and Windows 7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Nawuko** [comment]
This is maybe releated to https://github.com/TrinityCore/TrinityCore/pull/15641

This line got changed which might be the problem: https://github.com/TrinityCore/TrinityCore/pull/15641/files#diff-f3f953a63e2a008d22de69cb68f735c4R2787

I'm not 100% sure but i will run some tests and post back :)

**Comment by Nawuko** [comment]
Okay yea it was really that change.

The following fixes the problem:

```diff
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 1f7dae4..893d33a 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -2872,7 +2872,10 @@ void Creature::ReleaseFocus(Spell const* focusSpell, bool withDelay)
     if (focusSpell && focusSpell != _focusSpell)
         return;
 
-    SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
+    if (Unit* victim = GetVictim())
+        SetGuidValue(UNIT_FIELD_TARGET, victim->GetGUID());
+    else
+        SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
 
     if (_focusSpell->GetSpellInfo()->HasAttribute(SPELL_ATTR5_DONT_TURN_DURING_CAST))
         ClearUnitState(UNIT_STATE_CANNOT_TURN);

```

Let me summon @Treeston Maybe he can explains why this was changed and if we would revert this line it would break something else.

**Comment by Treeston** [comment]
If you re-target right away anim will snap back to that target (Ingvar etc).

Delay behavior shouldn't apply to pets though, that's the bug here. Let me push a fix.

**Comment by MrSmite** [comment]
Thanks @Nawuko @Treeston, I had just finished compiling a debug build to try and track it down.
