### ISSUE TITLE
spell/Languish Spell damage is too low

### ISSUE THREAD

**Issue by mayaren888** [TrinityCore/TrinityCore#16826]
**Description**:
http://www.wowhead.com/spell=71023/languish
Druid T10 Balance 4P Bonus  get languish spell,But the effect is not ideal.
Druid 2*T10+2*T9 The resulting damage is greater than Druid 4*T10 
**Current behaviour**: Tell us what happens
spell/Languish  spell damage is too low
**Expected behaviour**: Tell us what should happen instead
The damage is at least 7 times as much as it is now.
**Branch(es)**: 335/6x
335
**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/4fbffab5f8a43410c4e4487e15f22a5173b9bc9e
**TDB version**:
TDB335.60
**Operating system**:
win

**Comment by Keader** [comment]
i cant confirm this
this proc every crit for me...
i cant understand what you say on "Trigger chance is low"

**Comment by Aokromes** [comment]
1st law before reporting bugs: update your core.

**Comment by mayaren888** [comment]
@Keader  @Aokromes    So sorry  
My description is not accurate enough, I corrected my title
Trigger probability is correct
The problem is that the spell damage is too low.
I searched for information about early blizzard.
Due to the low level of the spell, the creature is resisted.
Causes the spell damage to low

**Comment by Aokromes** [comment]
You are still using to old core, update it.

**Comment by mayaren888** [comment]
@Aokromes    
1. I want to know how the problem is solved.
2, the latest code has a lot of new errors.

**Comment by Aokromes** [comment]
Well, since you refuse to update, i close this ticket, we don't support 4 months old core.
