### ISSUE TITLE
[Wintergrasp] Spirit Guides not resurrect.

### ISSUE THREAD

**Issue by DevQuad** [TrinityCore/TrinityCore#16820]
31841 - Taunka Spirit Guide 
31842 - Dwarven Spirit Guide

These spirits do not work, or rather not voskrshayut after 30 seconds of casting and tested to run the body.

Operating system - Windows
Core: [993c266](https://github.com/TrinityCore/TrinityCore/commit/993c266260ff6c30f788e530b314d6fb7f457ea0)
TDB 335.60

**Comment by jackpoz** [comment]
Follow the template that appears when creating a new issue, it's not optional https://github.com/TrinityCore/TrinityCore/issues/new
