### ISSUE TITLE
Connection Patcher cant patch build 21348

### ISSUE THREAD

**Issue by Luzifix** [TrinityCore/TrinityCore#16835]
**Description**: I try to patch my Wow-64.exe (build 21348) with the connection patcher to connect on my core but its not work.

**Current behaviour**: connection patcher cant patch Wow.exe build 21348 

**Expected behaviour**: The connection patcher patch Wow.exe with build 21348

**Steps to reproduce the problem**:

1. Drag the Wow-64.exe over the connection_patcher.exe
2. Output: http://i.imgur.com/UVSLP63.png

**Branch(es)**: 6x

**TC hash/commit**: 45c857a6bf78f7913ad4032524c84df41b7efc5f

**TDB version**: TDB 6.03

**Operating system**: Windows

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Shauren** [comment]
TrinityCore does not support 6.2.4 yet and given the few initial commits made in 6.x branch, 6.2.3 does not work anymore - stay at https://github.com/TrinityCore/TrinityCore/commit/363731aac827f3eab051064ba466cef49f6cc111

Announcement will be posted in this thread https://community.trinitycore.org/topic/10582-6x-branch-client-supported-623-20886/ once the new patch is ready.

**Comment by Luzifix** [comment]
ok thx
