### ISSUE TITLE
[3.3.5][Hunter] Core/Spell: talent "Sniper Training" triggering while dead

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16836]
3.3.5 f37682b

The hunter talent [Sniper Training](http://wotlk.openwow.com/spell=53304) applies a buff to the player if they stand still for 6 seconds.

The current core attempts to apply this buff even if the player is dead, leading to the player receiving a "You are dead" error message every 5 seconds while standing still as a ghost.

**Comment by Kodekc** [comment]
Same with talent http://wotlk.openwow.com/spell=48108!
With the explosion of fire bombs, proc will attempt to activate a dead aim

**Comment by P-Kito** [comment]
Is there any proc in WoW that requires to proc when being dead?

**Comment by mik1893** [comment]
i think we should just return... cant think of something that procs when you are dead

**Comment by Treeston** [comment]
I can pretty much guarantee that there is some niche spell somewhere that procs while dead, yes.

**Comment by mik1893** [comment]
of course, it's bl1z....

**Comment by Treeston** [comment]
That is not how core development works.

**Comment by Shauren** [comment]
As I said in the closed PR that attempted to fix it - Sniper Training is NOT A PROC
It's a periodic trigger aura.

**Comment by Nawuko** [comment]
My take on this: https://gist.github.com/Nawuko/c9f489418b6b89d1fc1ecb09a29f12d7
No gurantees and line count dosent match (You have to apply manually)

Cheers.

**Comment by Treeston** [comment]
Tested, @Nawuko? Looks like a clean solution to me (curious that `TRIGGERED_DONT_REPORT_CAST_ERROR` isn't already checked there).

**Comment by Shauren** [comment]
Why not here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L3791?

**Comment by Treeston** [comment]
Agree with @Shauren. We should remove all the various `TRIGGERED_DONT_REPORT_CAST_ERROR` checks from CheckCast and have it checked in `SendCastResult` instead.

**Comment by Nawuko** [comment]
Yea, i try always to change little as i can when it comes to something like the spell system. @Shaures sugestion makes much more sense. So go go open a PR tree <3

**Comment by Treeston** [comment]
Will do later today when I get home.

**Comment by Shauren** [comment]
Please note that you need to place it in 2 methods - SendCastResult(result) and SentPetCastResult(result), not the one taking in a large amount of arguments (its static and you dont have access to _triggeredCastFlags)

**Comment by Treeston** [comment]
Yup, I'm aware. Thanks for the heads up anyway.
