### ISSUE TITLE
[3.3.5] Creature: Steam Pump Overseer (18340)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16840]
3.3.5 f37682b

[Steam Pump Overseer](http://www.wowhead.com/npc=18340/steam-pump-overseer#comments) should appear and attack the player when using the [Ironvine Seeds](http://www.wowhead.com/item=24355/ironvine-seeds) for the quest [Balance Must Be Preserved](http://www.wowhead.com/quest=9720/balance-must-be-preserved).

This does not occur, instead the Overseer is a static spawn at each of the quest locations.

**Comment by Saben65** [comment]
I fixed this before. Will see if I can dig up the query for review.

**Comment by dr-j** [comment]
On retail there is static spawn and one spawns when you disable the console so you end up having two kill 2 at each pump unless can avoid agro
