### ISSUE TITLE
[3.3.5] NPC - Sunblade Magister (Incorrect SAI)

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#16851]
http://www.wowhead.com/npc=24685/sunblade-magister

NPC will cancel all his spells, he just spamming spells and cancels them.
Almost all of his spells have the status of "failure"

Branch: 3.3.5
TC hash/commit: ef7a91d
TDB version: 335.60

**Comment by Killyana** [comment]
Cannot reproduce.
