### ISSUE TITLE
Undocumented config options

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#16859]
**Description**:

The following config options are missing from master worldserver.conf:

``` ini
GuarderSight = 50.0

Guild.SaveInterval = 15
```

**Branch(es):** master 

**TC hash/commit**: 070bedae0c78a870ef69f6796ac956896c8e7fa2/ 580773dc1a52cf6c8177647baf15afccd557be60

**Operating system**: Win10

**Comment by tkrokli** [comment]
TrinityCore rev. 4afea55b2c60 2016-03-28 05:47:41 +0200 (3.3.5 branch) (Win64, Release)
```
Missing name DisconnectToleranceInterval in config file worldserver.conf, add "DisconnectToleranceInterval = 0" to this file
Missing name MonsterSight in config file worldserver.conf, add "MonsterSight = 50.000000" to this file
Missing name GuarderSight in config file worldserver.conf, add "GuarderSight = 50.000000" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Missing name Battleground.PrematureFinishTimer in config file worldserver.conf, add "Battleground.PrematureFinishTimer = 300000" to this file
Missing name Battleground.PremadeGroupWaitForMatch in config file worldserver.conf, add "Battleground.PremadeGroupWaitForMatch = 1800000" to this file
```
Worldserver says `Battleground.PrematureFinishTimer` + `Battleground.PremadeGroupWaitForMatch` are missing, although both those 2 values and their documentation is present in both my `Worldserver.conf.dist` and `Worldserver.conf` files:
```
#    Battleground.PrematureFinishTimer
#        Description: Time (in milliseconds) before battleground will end prematurely if there are
#                     not enough players on one team. (Values defined in battleground template)
#        Default:     300000 - (Enabled, 5 minutes)
#                     0      - (Disabled, Not recommended)

BattleGround.PrematureFinishTimer = 300000

#
#    BattleGround.PremadeGroupWaitForMatch
#        Description: Time (in milliseconds) a pre-made group has to wait for matching group of the
#                     other faction.
#        Default:     1800000 - (Enabled, 30 minutes)
#                     0       - (Disabled, Not recommended)

BattleGround.PremadeGroupWaitForMatch = 1800000
```
The remaining 3 errors are correct. `DisconnectToleranceInterval`, `MonsterSight` and `GuarderSight` are not present in `Worldserver.conf` (`Worldserver.conf.dist`) on 3.3.5.

**Comment by r00ty-tc** [comment]
I think the problem is the capital G in battleground.

**Comment by tkrokli** [comment]
Good point, I just tested your theory on rev. 4afea55b2c60 2016-03-28 05:47:41 +0200 (3.3.5 branch) and the error messages went away. Would you like me to make another PR or just do a write-up commit?

**Comment by r00ty-tc** [comment]
I think anyone with commit access that isn't only able to use a phone right now can go right ahead and commit whichever change they feel makes more sense. The dist change means no recompile so is probably easiest. Depends on the other battleground related configs though. Should all be in the same style.

**Comment by tkrokli** [comment]
Yes, I just checked the source for `worldserver.conf.dist` and those 3 are the only deviations.

**Comment by tkrokli** [comment]
So I thought to myself: "You others are probably busy enough as it is" and I just added that change to my existing PR #16861. No need for that separate write-up, then. I also made a slight info improvement.

**Comment by tkrokli** [comment]
I found this MaNGOS info from 2008 when searching for the term `CONFIG_SIGHT_MONSTER` :
http://forum.aleajecta.com/index.php/topic/6757-remove-getdistancesq-and-getdistance2dsq-both-functions-were-obsoleted-many/
***
Increase CONFIG_SIGHT_MONSTER and CONFIG_SIGHT_GUARDER to 50 yards. Before they were 20 yards and 25 yards respectively. This value limits the maximum distance that a creature can see regardless of level difference (through CreatureAI::IsVisible).

**Comment by msoky** [comment]
any news?

**Comment by BlkChockr** [comment]
C'mon guys, it's been 3 months and the commit for this exact issue is already there! I'm trying to dockerize 6.x at the moment and this is the one thing making it much harder than it would need to be :(

**Comment by DDuarte** [comment]
@BlkChockr: I'm not sure how 3 warnings at startup affect anything at all that might be related to Docker (or anything else).

**Comment by BlkChockr** [comment]
Oh, these are just warnings? I thought these were errors stopping the server from being able to start up! My fault, sorry guys :)

(I'm almost done btw, just didn't add the extracted maps yet, so that should be why its not starting)

Is it possible to show the log level of the messages on server startup?

**Comment by DDuarte** [comment]
It is, look at the log configuration section in worldserver.conf and authserver.conf.

**Comment by BlkChockr** [comment]
Ahh, pretty neat. Keep up the good work! :)

**Comment by Aokromes** [comment]
You really thing we mark cosmetic something that breaks startup of core and don't fix for months?

**Comment by Magnifikator** [comment]
Since many months there is still MonsterSight = 50.000000 missing in the worldserver.conf.dist. What's so difficult to add it ?

**Comment by DDuarte** [comment]
@Magnifikator: what's MonsterSight?

**Comment by Magnifikator** [comment]
Can't say what it is exactly. But there is this error message in the log:

```2017-07-08_16:45:24 WARN  [server.loading] Missing name MonsterSight in config file C:/Trinity Exe Latest/worldserver.conf, add "MonsterSight = 50.000000" to this file```

If I add it to a world.conf file there is no error anymore. But It belongs also to the .dist file I think.

BTW: You have noted this yourself in your first posting in this issue on 28 Mar 2016.

**Comment by DDuarte** [comment]
Now you know why that _warning_ has not been fixed yet. :)

**Comment by Magnifikator** [comment]
No

**Comment by tkrokli** [comment]
`MonsterSight` and `[CONFIG_SIGHT_MONSTER]` has always been present in the core (at least here on github).
(see the first commit from October 2, 2008 https://github.com/TrinityCore/TrinityCore/commit/9b1c0e006f20091f28f3f468cfcab1feb51286bd#diff-b32f1858cfb04ed3727c85b4aee11e7fR473 [`0 parents`](https://github.com/TrinityCore/TrinityCore/commit/9b1c0e006f20091f28f3f468cfcab1feb51286bd))

How come we only got bothered with that (cosmetic) warning less than 2 years ago?

**Comment by Aokromes** [comment]
Because before there was no warning.

**Comment by tkrokli** [comment]
Haha, right. I should have seen it coming, my question was too general. :-P
Do you know where in the source code that warning was introduced?

**Comment by neechbear** [comment]
I can see this appears to only be referenced as `CONFIG_SIGHT_MONSTER` in a couple of places. It would be really nice if someone could just pop a description into `worldserver.conf.dist`.

I'll happily push this change myself if someone can describe to me exactly what this does. I've read through the relevant blocks of code, but I wouldn't feel confident in my description, other than the obvious assumption from the naming of the value.

**Comment by tkrokli** [comment]
See my comment https://github.com/TrinityCore/TrinityCore/issues/16859#issuecomment-208835716 regarding what I could find in a regular Google search.

**Comment by tkrokli** [comment]
As I quoted in comment https://github.com/TrinityCore/TrinityCore/issues/16859#issuecomment-208835716  (lines rearranged to point out what the settings do) :
> This value limits the maximum distance that a creature can see regardless of level difference (through CreatureAI::IsVisible).
Increase CONFIG_SIGHT_MONSTER and CONFIG_SIGHT_GUARDER to 50 yards.
Before they were 20 yards and 25 yards respectively.

**Comment by Aokromes** [comment]
after 7754960 it's master branch only.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fcc8d0c4d2f045cff24d64393a3662b9d43f34fa
