### ISSUE TITLE
[6.x][Rogue] Core/Spell: Fix Rogue Talent: Burst of Speed

### ISSUE THREAD

**Issue by P-Kito** [TrinityCore/TrinityCore#16869]
**Description**:

Fixes Talent Burst of Speed, no big magic linking the correct spells together

**Current behaviour**: No effect on using the talent

**Expected behaviour**: Speed buff + Slow Removal

**Steps to reproduce the problem**:

1. Learn Talent from talent tree (rogue)
2. Use it

**Branch(es)**: 6x

**TC hash/commit**: 4a679ba1be08e9302970cd7dc11fcc70e7fc4c91

**TDB version**: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB6.03

**Operating system**: Windows

```SQL
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 108212;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(108212, 137681, 0, 'Burst of Speed - Rogue Talent');
```

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rushor** [comment]
I added the issue also in the checklist of #14825. pls cross it once the fix from this issue was merged into the db. :)

**Comment by hikagemono** [comment]
i did apply that fix, and i did try it ingame, but there is one issue remaining.
The fix makes Burst of Speed usable, but it does break stealth, which it shouldn't.
I can only report the issue tho, not enough experience to fix it myself, sry :C

**Comment by P-Kito** [comment]
That's most likely not an issue with that spell. In 6.x no spell cancels stealth... well only a few do break it.

**Comment by Aokromes** [comment]
@Shauren this is valid?

**Comment by Keader** [comment]
why not a spell script?

**Comment by P-Kito** [comment]
Spellscript for linking 2 spells together... I think that's a bit too much.

**Comment by Keader** [comment]
Mik is doing some cleanup about linkedspell
maybe spell script is more "clean"
btw, both method should work ^^
