### ISSUE TITLE
[3.3.5][BUG] Spell damage item procs scalling with spellpower

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#16867]
**Description**: spell damage item procs scalling with spellpower

**Current behaviour**: lets say your a retri paladin you get spell power from you talents, you get and item like 12631 wich is fiery plate
gauntlets adds 4 fire damage to your melee attacks but it scales with spell power making your attacks give like 200 or 300 extra damage 
instead of 4 aditional
damage its the same thing for every magical damage item ingame that give some form of extra spell damage 

**Expected behaviour**: its not supose to scale with spell power giving only the damage the item text says it gives

**Steps to reproduce the problem**:

1. get a class with spell power or spell power items
2. get an item with spell damage proc
3. hit something to try the damage 

**Branch(es)**: 335/6x

**TC hash/commit**:  TrinityCore rev. 48a12cb2f551+ 2016-03-26 09:49:16 +0100 (3.3.5 branch) (Unix, Release)

**TDB version**: TDB 335.57

**Operating system**: CentOS 64 bits

**Comment by Keader** [comment]
Based on https://github.com/TrinityCore/TrinityCore/issues/1701#issuecomment-5089361

```sql
DELETE FROM `spell_bonus_data` WHERE `entry` IN (13907,44578,28005,20007,20006,64569,64442,6297,10577,17484,21992,27655,28788,40972,60526,43731,43733,38616,21992);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(6297, 0, 0, -1, -1, 'Fiery Blaze'),
(13907, 0, 0, -1, -1, 'Demonslaying - Smite Demon'),
(44578, 0, 0, -1, -1, 'Lifeward - Lifeward'),
(28005, 0, 0, -1, -1, 'Battlemaster - Battlemaster'),
(20007, 0, 0, -1, -1, 'Crusader - Holy Strength'),
(20006, 0, 0, -1, -1, 'Unholy Weapon - Unholy Curse'),
(64569, 0, 0, -1, -1, 'Blood Draining - Blood Reserve'),
(64442, 0, 0, -1, -1, 'Blade Warding - Blade Warding'),
(10577, 0, 0, -1, -1, 'Gauntlets of the Sea (Heal)'),
(17484, 0, 0, -1, -1, 'Skullforge Reaver - Skullforge Brand'),
(27655, 0, 0, -1, -1, 'Heart of Wyrmthalak (Flame Lash)'),
(28788, 0, 0, -1, -1, 'Paladin T3 (8)'),
(40972, 0, 0, -1, -1, 'Crystal Spire of Karabor - heal effect'),
(60526, 0, 0, -1, -1, 'Living Ice Crystals - heal effect'),
(43731, 0, 0, -1, -1, 'Consumable - Stormchops (Lightning Zap)'),
(43733, 0, 0, -1, -1, 'Consumable - Stormchops (Lightning Zap)'),
(38616, 0, 0, -1, -1, 'Poison - Bloodboil Poison'),
(21992, 0, 0, -1, -1, 'Thunderfury');
```
Some items/enchant items

**Comment by tkrokli** [comment]
Very well, I'm checking for duplicates and codestyle now. Posting back as soon as I am ready.

**Comment by tkrokli** [comment]
OK, so I did not find it necessary to remove any lines in your suggested SQL query, only update one comment because most of the existing comment lines in TDB 335.60 are less correct than yours.
I chose to only keep the text `Warlock - Siphon Essence T6 2P proc` and replace the rest.
Other than that, I just sorted the spell IDs in ascending order and aligned the columns. Gist link:
- https://gist.github.com/tkrokli/197ba8fde857cf78e151#file-2016_03_29_09_world_335-sql

**Comment by Keader** [comment]
but has no duplicated lines? @tkrokli

**Comment by tkrokli** [comment]
Yes, https://gist.github.com/tkrokli/197ba8fde857cf78e151#file-2016_03_29_09_world_335-sql is ready for use. Please read through it at least once, even if I have done my best to keep it unchanged.

**Comment by Keader** [comment]
@tkrokli has some duplicated lines (lines already exists on TDB) you change comment ou something to justify modifying them?

**Comment by tkrokli** [comment]
What I tried to say above is that even if some few duplicated lines exist, I think it will make a longer script to write separate `UPDATE` lines for those lines where the spells already exists, but with wrong values and inaccurate comments. Maybe someone will disagree, but I am trying to be practical about it.

**Comment by Keader** [comment]
I understand you.

@killyana this can be pushed ?

**Comment by tkrokli** [comment]
The label [Feedback-PatchFix] is usually a good sign. :+1:

**Comment by cezeta** [comment]
lol, an antient fix resurrected :-D
