### ISSUE TITLE
[6.x] Players ejected from vehicule when changing Area/Zone

### ISSUE THREAD

**Issue by Jarts37** [TrinityCore/TrinityCore#16877]
**Description**:
When a player can control a vehicule, and can move with it, if the player/vehicule change area or zone, all the players in the vehicule are ejected.

**Current behaviour**: Tell us what happens
Players are ejected from the vehicule when the vehicule change area/zone
For example, you spawn a vehicule in GoldShire, you follow the road, then the namezone change from Goldshire to Elwynn forest and you are ejected.
Only players are ejected, if the vehicle have NPC (vehicle_template_accessory) they stay.

**Expected behaviour**: Tell us what should happen instead
All players should stay in the vehicle.

**Steps to reproduce the problem**:

1.  Teleport to Goldshire or whatever
2. Spawn a vehicle you can control (33062,28094,27761...)
3. Follow the road to the redridges or to westfall
4. When the Zone name change, players are ejected.

**Branch(es)**: 6x

**TC hash/commit**: ca4e8c6ff8543ce6b5bbd57cf82f4eb4be4b6119

**TDB version**: 6.02 (6.2.3)

**Operating system**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#16021
