### ISSUE TITLE
[3.3.5] Missing skill_fishing_base_level

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#16879]
Fishable areaId 4100 are not properly defined in `skill_fishing_base_level`.
Fishable areaId 4987 are not properly defined in `skill_fishing_base_level`.

Accidentally discovered errors in the log, perhaps there is more

Branch: 3.3.5
TC hash/commit: ef7a91d
TDB version: 335.60

**Comment by Aokromes** [comment]
4987 is RS.
4100 is CoS.
