### ISSUE TITLE
Mac OS X Executable Crash

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#16872]
**Description**:
While login the client crash
**Current behaviour**: Tell us what happens
If you patch world of warcraft.app then you start "World of Warcraft Patched.app" and then you log in, the client will crash after pressing the "connect" button.

This is the log from Errors folder: http://pastebin.com/hGJUBsGP

**Expected behaviour**: Tell us what should happen instead
You should go to characters screen.
**Steps to reproduce the problem**:

1. Patch mac client
2. Start patched client
3. Write credentials
4. Press the "connection" button.

**Branch(es)**: 335/6x
6x
**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/7f8cd123c43b3cc7f50c1084e8450aa31173b395
**TDB version**:
TDB 6.03
**Operating system**:
Mac Os X Yosemite

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Shauren** [comment]
nice.

**Comment by ikir83** [comment]
Same here

**Comment by Kedaewyn** [comment]
Same for me, but when delete tc_bundle.txt from my WoW's folder, the .app work (but cannot connect into my server)

**Comment by Rudi9719** [comment]
I'm getting a similar error, specifically with the 
Error Code:  0x85100086
Exception:   EXC_BAD_ACCESS
Description: KERN_INVALID_ADDRESS at 0x0000000000000038
part.. Except my client is looking for data/data/data[files] and I have no idea why... They're not files in my regular, retail flavour either.

**Comment by Rudi9719** [comment]
Update, the data/data/etc... Files are listed under streaming data.. Is this data being streamed from B.net? Or is it supposed to be coming from the core?

**Comment by georgel** [comment]
Also getting the same error: 
Exception Raised!
App:         /Applications/World of Warcraft/World of Warcraft Patched.app
Error Code:  0x85100086
Exception:   EXC_BAD_ACCESS
Description: KERN_INVALID_ADDRESS at 0x0000000000000038 

Please help.

**Comment by Shauren** [comment]
Try replacing your tc_bundle.txt with this one and tell me what changed (if anything)

[tc_bundle.txt](https://github.com/TrinityCore/TrinityCore/files/244931/tc_bundle.txt)

**Comment by LuigiElleBalotta** [comment]
@Shauren  it doesn't crash but i'm using 6.2.4 21355, i can see the realm list but i can't connect because tc server is updated to latest build
When trying to patch the WoW.app 6.2.4 21463 with connection_patcher i get this error:
Creating patched binary...
EX: unable to find pattern
An error occurred. Press ENTER to continue...

Tc hash/commit: https://github.com/TrinityCore/TrinityCore/commit/71a7f96e22a68654edd66ccdb5f6202dec4dfd2c

**Comment by Shauren** [comment]
Theoretically 21355 and 21463 are compatible with each other, change realmlist.gamebuild to 21355 and try again

**Comment by LuigiElleBalotta** [comment]
@Shauren  it works after changing realmlist.gamebuild to 21355
the only problem now is patching the build 21463 on mac and make it work with realmlist.gamebuild = 21463 as on TC

**Comment by Shauren** [comment]
If you manage to get in world on 21463 I will change the connection_patcher to create tc_bundle.txt with updated content

**Comment by LuigiElleBalotta** [comment]
Yes, why not? So mac user and windows user don't have differences!

**Comment by Aokromes** [comment]
Sooo any OSX user can test @Shauren's fix or no?

**Comment by Rudi9719** [comment]
Using the new tc_bundle.txt I was able to patch and connect on 6.2.4 (21463)
