### ISSUE TITLE
Mid-screen error spam in Blade's Edge Mountains

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#16889]
**Description**:
As mentioned in issue #16888 :
When flying/moving around in Blade's Edge Mountains, you see the error text "You can't do that yet".
Explanation from @meji46 : `It's triggered by spell_areas related to Apexis Emanations buffs`

**Current behaviour**: Tell us what happens
Player gets center screen error spam (in red text) as game client error announcements:
```
                            You can't do that yet
                            You can't do that yet
                            You can't do that yet
```
This happens while moving or flying, not while standing still.

**Expected behaviour**: Tell us what should happen instead
You should not see error messages just because you move/ride/fly around (not doing anything else).

**Steps to reproduce the problem**:

1. Take a character with flying skill to Blade's Edge Mountains (no adjustments needed).
2. Fly/ride/move around in the area, preferably crossing zones.
3. The error message should show up just because the character is moving around.

**Branch(es)**: 335/6x
I have only tested this on 3.3.5, so a confirmation from current 6.x users would be welcome.

**TC hash/commit**:
TrinityCore rev. c9e3f2aa9a02 2016-03-31 03:31:51 +0100 (3.3.5 branch) (Win64, Release)

**TDB version**: TDB 335.60 + updates up to and including `2016_03_29_00_world_335.sql`

**Operating system**:
 Windows 10 Home x64, version 1511 build 10586.164

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by meji46** [comment]
The problem is this commit: https://github.com/TrinityCore/TrinityCore/commit/2e111a098d62d801451335f1cca0beadd8851565

**Comment by Goatform** [comment]
@tkrokli, test this patch:

``` diff
@@ -3100,6 +3100,11 @@ void SpellMgr::LoadSpellInfoCorrections()
             case 54098: // Poison Bolt Volly - Faerlina (H)
                 spellInfo->MaxAffectedTargets = 10;
                 break;
+            case 40624: // Apexis Vibrations
+            case 40627: // Apexis Emanations
+            case 40628: // Apexis Enlightment
+                spellInfo->InterruptFlags = 0;
+                break;
             case 50312: // Unholy Frenzy
                 spellInfo->MaxAffectedTargets = 15;
                 break;

**Comment by tkrokli** [comment]
:+1: Thanks for the suggestion, I will test that to see if it will produce the desired results and report back.

**Comment by MrSmite** [comment]
Wouldn't this have something to do with it?

```SQL
(17,0,40624,0,0,1,0,40623, '', 'Swiftness - Only cast if Apexis Vibrations is active'),
```
[40624](http://www.wowhead.com/spell=40624/swiftness) says:

> Apply Aura: Increase Run Speed % Value: 15%

So it looks like the core is attempting to apply a runspeed aura to a person who's mounted. It would be the same as trying to drink a [swiftness potion](http://www.wowhead.com/item=2459/swiftness-potion) while mounted.

**Comment by Goatform** [comment]
On my core when I cast this spell it doesn't give me the same error, it's saying that I can't cast it while mounted.

**Comment by Nawuko** [comment]
Spells from spell_areas should be executed as triggerd and not yield any spellhitresult messages? Or i'm misstaken?

**Comment by tkrokli** [comment]
I don't know much about how those spells work. I only know that I get the on-screen error message without doing anything special with my characters except for entering Blade's Edge Mountains and that I get the error message both while running and flying across boundaries between named areas, like running to the door of the Circle of Blood and then back to the nearest friendly / quest giver NPC.
(I have not made any efforts yet to join the Ogri'la faction by starting to do the Apexis shard quests.)

**Comment by meji46** [comment]
Maybe changing in the conditions the ErrorType to SPELL_FAILED_CUSTOM_ERROR and ErrorTextId to SPELL_CUSTOM_ERROR_NONE

**Comment by tkrokli** [comment]
You mean something like this?
```sql
UPDATE `conditions` SET `ErrorType`= 172
 WHERE `SourceTypeOrReferenceId`= 17
 AND `SourceEntry` IN (40624,40627,40628);
```
SPELL_FAILED_CUSTOM_ERROR = 172 (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Miscellaneous/SharedDefines.h#L1013)
SPELL_CUSTOM_ERROR_NONE = 0 (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Miscellaneous/SharedDefines.h#L1035) - `ErrorTextId` is already 0 for those conditions.

I will check this and see if it removes the error message and post an update after the test.

**Comment by meji46** [comment]
Yep. In 6.X the Id is SPELL_FAILED_CUSTOM_ERROR  = 209

**Comment by MrSmite** [comment]
Won't that cause a problem with people trying to drink a [Swiftness Potion](http://www.wowhead.com/item=2459/swiftness-potion) before the cooldown runs out?

**Comment by tkrokli** [comment]
http://www.wowhead.com/spell=2379/speed (+50% speed) is a level 15 spell according to wowhead, although http://www.wowhead.com/item=2459/swiftness-potion seems to require as little as level 5.

All of these 3 spells require level 70 and only give you 15% speed increase:
- http://www.wowhead.com/spell=40624/swiftness
- http://www.wowhead.com/spell=40627/swiftness
- http://www.wowhead.com/spell=40628/swiftness

http://www.wowhead.com/item=2459/swiftness-potion#shared-cooldown:50-3+1-2 (no related cooldowns)

**Comment by MrSmite** [comment]
Well I don't know if they technically *require* level 70 because it isn't cast by a player or applied by an item the player uses. Given the way wowhead aggregates data, it could simply be that the majority of people in Blade's Edge were level 70 when the buff was applied to them.

Consider also the results for a search on [swiftness](http://www.wowhead.com/search?q=swiftness). You have a potion requiring [level 5](http://www.wowhead.com/item=2459), a potion requiring [level 55](http://www.wowhead.com/item=20081) and a potion requiring [level 90](http://www.wowhead.com/item=122452) but all of those are directly applied by the player themselves.

I wish wowhead kept their old design where when you clicked on an item it actually had a link to the spell / effect that was applied.

**Comment by tkrokli** [comment]
Well, wowhead seems to have kept some of that functionality insofar as linking to the spell with the green spell description text within the item description tooltip box on the item page. In this case, I think it would be even more helpful to have a link from the swiftness spells 40624,40627,40628 to the pages where the source of the spell could be found. To me, it looks like some [Used by:] tabs are removed from wowhead.

**Comment by MrSmite** [comment]
> linking to the spell with the green spell description text within the item description tooltip box on the item page

LOL, I didn't even realize that was a link.

**Comment by tkrokli** [comment]
I know, I did not have much need for that information back in 2006-2010, but I rediscovered the linked green (sometimes yellow) text in the spell item tooltip boxes when I started using TC source in 2013.
