### ISSUE TITLE
[3.3.5] Core/Spell: Guard's Mark (38067)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16888]
3.3.5 f37682b

When flying over hostile faction towns in Outland, the debuff [Guard's Mark](http://www.wowhead.com/spell=38067/guards-mark#comments) is correctly applied and guards are correctly spawned, but the debuff doesn't correctly make them aggro the player.

**Comment by meji46** [comment]
It's triggered by spell_areas related to Apexis Emanations buffs

**Comment by Treeston** [comment]
Make a separate issue for it please.

**Comment by Langerz82** [comment]
working on it.

**Comment by Langerz82** [comment]
```diff
diff --git src/server/scripts/World/npcs_special.cpp src/server/scripts/World/npcs_special.cpp
index 1a8a5e9773..1d06f2b925 100644
--- src/server/scripts/World/npcs_special.cpp
+++ src/server/scripts/World/npcs_special.cpp
@@ -59,11 +59,11 @@ struct SpawnAssociation
 enum AirFoceBots
 {
     SPELL_GUARDS_MARK               = 38067,
-    AURA_DURATION_TIME_LEFT         = 5000
+    AURA_DURATION_TIME_LEFT         = 30000
 };
 
 float const RANGE_TRIPWIRE          = 15.0f;
-float const RANGE_GUARDS_MARK       = 50.0f;
+float const RANGE_GUARDS_MARK       = 100.0f;
 
 SpawnAssociation spawnAssociations[] =
 {
```

**Comment by tkrokli** [comment]
I'm willing to test it, but is that small change enough to make players actually aggro the mounted flying guards?

**Comment by Langerz82** [comment]
I tested it. AURA_DURATION_TIME_LEFT was 5000 so the Flying Creatures would only aggro if they had LOS with 5 seconds left on the buff.

**Comment by tkrokli** [comment]
> [ ... ] 5 seconds left on the buff or less.

... I would have thought "5 seconds left on the buff **or more**." -- but then again, I haven't done any research.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e840d4967eae376d1bb888ae471056d05c2f0acc now causes the guards to attack right away, is that how it's supposed to be ?

**Comment by Killyana** [comment]
Yes the guard spawn and attack instantly the player that triggered the bot (has the mark)

**Comment by jackpoz** [comment]
then the whole 30 seconds check makes no sense, they should just always attack

**Comment by Killyana** [comment]
Yes, as the duration of the aura is 30 secs https://www.wowhead.com/spell=38067/guards-mark
