### ISSUE TITLE
Map & DBC Extractor - ProcSegmentation fault

### ISSUE THREAD

**Issue by douglandmesser** [TrinityCore/TrinityCore#16883]
**Description**:
ProcSegmentation fault when trying to extract map and dbc files.

**Current behaviour**: Tell us what happens
reached 42% on the first map file 'Convert map files' and then errors out saying 'ProcSegmentation fault (core dumped)%'.

**Expected behaviour**: Tell us what should happen instead
all of the maps and dbc files should get dumped into their respective folders.

**Steps to reproduce the problem**:

1. git clone -b 6.x git://github.com/TrinityCore/TrinityCore.git
2. cd TrinityCore
3. mkdir build
4. cd build
5. cmake ../ -DCMAKE_INSTALL_PREFIX=/home/douglas/wow-server/trinity-server -DCONF_DIR=/home/douglas/wow-server/trinity-server/etc -DTOOLS=1 -DWITH_WARNINGS=1
6. make
7. make install
8. downloaded newest wow files from blizzard - updated all
9. trinity-server/bin/mapextractor -l enUS

**Branch(es)**: 335/6x
6x

**TC hash/commit**:
commit 0afcefe

**TDB version**:
 TDB 6.03

**Operating system**:
trinitycore is running on fedora 23 (linux) and wow clients are running on windows 7 ultimate (32-bit)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[wow-error.txt](https://github.com/TrinityCore/TrinityCore/files/196923/wow-error.txt)

**Comment by DDuarte** [comment]
Could you try running `mapextractor` with GDB to get a crashlog? https://github.com/TrinityCore/TrinityCore/tree/6.x/contrib/debugger

**Comment by douglandmesser** [comment]
will do... running "git clone -b 6.x git://github.com/TrinityCore/TrinityCore.git" again to build with the newest files available. this will take a little while to make install.

**Comment by DDuarte** [comment]
You do not need to re-do everything. All you need to change is the step 9 of your nice steps list.
`gdb -x crashreport.gdb trinity-server/bin/mapextractor`

**Comment by douglandmesser** [comment]
darn it i should have waited. sorry. i will post results as soon as possible. it is at 26% on the 'make' portion (step #6).

**Comment by DDuarte** [comment]
You can tell cmake to only compile tools, add `-DSERVERS=0` to the list of args (if you cancel now you will still save time :P )

**Comment by douglandmesser** [comment]
well that is a heck of a lot quicker! thanks! running "gdb -x crashreport.gdb" now...

**Comment by douglandmesser** [comment]
okay, backtrace.log file generated. please see attached. and thanks for helping!

[backtrace-31march2016.txt](https://github.com/TrinityCore/TrinityCore/files/196962/backtrace-31march2016.txt)

**Comment by DDuarte** [comment]
Hmmm, seems to be in release mode (default). Add `-DCMAKE_BUILD_TYPE=Debug` to the CMake args, make, make install and run the mapextractor with gdb again. The crashlog should have more info now.

**Comment by douglandmesser** [comment]
okay, new log file generated with modified cmake argument added. lots more text as expected.

[backtrace.txt](https://github.com/TrinityCore/TrinityCore/files/196968/backtrace.txt)
please see attached.

**Comment by DDuarte** [comment]
Much better, thanks. And now it's the part I can't help you more since I have no idea what's going on in there. I'm not exactly sure if extractors need to be updated to 6.2.4, perhaps some internal format changed?

**Comment by douglandmesser** [comment]
just a side question for you. when you run the "git clone -b 6.x git://github.com/TrinityCore/TrinityCore.git" command, i presume all of the newest files get downloaded? i see some of the dates on the files like "added 2 days ago" and i wonder if i am getting the newest ones by default, without any other crazy arguments?

**Comment by douglandmesser** [comment]
just an update to help with troubleshooting. i downloaded the data files for wow version 6.1.2 and tried the map extractor. it immediately displays this message:

"error opening casc storage '/home/douglas/wow-source-old/Data' locale enUS: FILE_NOT_FOUND"

i suspect i got this error because i did not log into my retail account at least once, as i have read on other forums. i don't know how to log in without it forcing me to update the 6.1.2 files to the newest. so i am kind of stuck there.

everything worked great until that 6.2.4 upgrade came down. i am willing to format the server and reinstall from scratch if needed. sort of a control subject. let me know.

**Comment by tkrokli** [comment]
I looked through the issue and your attachments to see if I could test it and try to replicate it. You have stated that your OS is "windows 7 ultimate (32-bit)", but your file system references and command line looks like a UNIX/Linux OS or environment. Could you explain this to to me so I could understand which environment you are using? I am mostly using Windows myself, so it looks a bit confusing to me. I have only used Windows to extract the maps, even if I sometimes have compiled the server itself on debian.

**Comment by douglandmesser** [comment]
tkrokli - i apologize for the confusion. the trinitycore is running on my fedora server. the wow clients are running on windows 7 ultimate (32-bit). i was not aware that you could run the wow client in linux. what would you use for this? something like the Wine application?

**Comment by tkrokli** [comment]
Fair enough. I was mostly trying to put your map extraction process in the right perspective (and OS). What I meant to say is that it is perfectly OK to run the servers (bnetserver + worldserver) on Linux (in your case, Fedora) while running the connecting clients on Windows or Mac OSX, but I was confused about whether you were trying to do the map extraction in a Linux or Windows environment, maybe by making the Windows client filesystem available to the UNIX/Linux server where you had compiled the binaries, thereby doing the map extraction in a Linux environment to get your DB2/maps/vmaps/mmaps.
I was too uncertain to understand and visualize your compile and map extraction processes correctly.

**Comment by douglandmesser** [comment]
let me outline the process i took:

1. installed wow on a windows computer (good, normal way through battle.net launcher)
2. modified the 'C:\Program Files\World of Warcraft' folder so all users have full control
3. shared the folder so all users have full control
4. mounted the wow folder in fedora using "mount -t cifs //10.0.0.6/wow-source-newest --target /home/douglas/wow-source-newest -o credentials=/root/.smbcredentials" command.
5. ran "cp -r" to copy everything over to the fedora server
6. built and made trinitycore with tools enabled
7. ran the mapextractor script on the newely-copied data
8. i also tried running the mapextractor on the shared folder itself, instead of copying the data to the fedora sever first. both attempts produced the same error.

**Comment by tkrokli** [comment]
OK, thanks for the detailed explanation. In this case, I would say that it is more appropriate to put "Fedora version xx" with relevant details in the **Operating system:** section of your first post, because that is where your compile and extraction takes place. Myself, I always extract maps etc. on the Windows computer where I have got my client, so I don't have any experience from extracting maps on Linux.
I hope someone with more experience from doing map extraction on Linux can look into your issue. :-)

**Comment by douglandmesser** [comment]
how would i go about extracting in windows? does trinitycore have windows-based extractors that you can use? i presumed that was the devil, since the install instructions are VERY careful to warn about that sort of thing.

**Comment by tkrokli** [comment]
Oh, OK. It is perfectly possible to extract the DB2/maps/vmaps/mmaps files on a Windows file system and then copy them over to your Linux server, if your primary issue is to get the server up and running. You just choose to compile only the Tools, not servers in your Windows CMake setup, to save some time.

**Comment by douglandmesser** [comment]
i can't find anything on google about this error. i am presuming at this point that the problem is limited to my machine. i will re-image and post my findings. at that point i will close if all is well. everything was working great until that upgrade, so i think a complete re-image will help a lot.

**Comment by liszt** [comment]
I'm running FC 23 here and didn't have any issues extracting the dbc/maps/vmaps/mmaps with TrinityCore rev. 6cd7b5806521+.  Don't know what's causing the issue, but it should work with Fedora.

**Comment by douglandmesser** [comment]
thanks to all of you for your support! before i ghost the drive i am trying my luck at 3.3.5 instead. i have sooo much stuff on the fedora server, and soo many tweaks made to buried config files and such. let's see what we get...

**Comment by douglandmesser** [comment]
so this is interesting. i removed everything and installed 3.3.5 on the fedora server. not only does it run smoothly, but the build process took a fraction of the time. the map extractor froze at 42% again, so i figured i was hosed. but then it started back up and plowed through the maps at impressive speed.

so, not sure what happened there, but i am happy on 3.3.5 for now. maybe i'll give it another go after a little while. i definitely need to re-image this server. that is the first step. thanks to all!
