### ISSUE TITLE
[335] Core/Pet: DoT Damage Causes Pet Aggro Per Tick (Patch included)

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#16894]
**Description**:

Each tick of a DoT on the Hunter causes the pet to aggro

**Current behaviour**:

When a mob casts a DoT on the Hunter and you then run away to exit combat, each DoT tick will put the pet in combat and if it is on defensive it will run to attack the original caster.

**Expected behaviour**:

The pet should only aggro onto the caster on the inital cast. Subsequent damage from DoT ticks should be ignored by the pet and not put it back into combat.

**Steps to reproduce the problem**:

1. Get a Hunter
2. Get a pet, put it on defensive
3. Find something to cast a DoT on the Hunter
4. Put the pet on passive and run away to exit combat (without killing the mob)
5. Put the pet back on defensive after combat drops
6. Observe the pet as it tries to chase down the caster each time the DoT damges the Hunter (hint: click 'follow' when it begins to chase).

**Branch(es)**: 335

**TC hash/commit**: cebdf03349ed0c50a40cf52ddae887cf666d1eb5 and https://github.com/TrinityCore/TrinityCore/commit/974703671ed5f08ec0c1a5b3943fc68508f2f4d6

**TDB version**: TDB_full_world_335.60_2015_11_07.sql

**Operating system**: Win XP / 7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by MrSmite** [comment]
Here's a fix for the issue. Sorry it's not a PR but I'm having issues with SSH trying to push to my fork.

```DIFF
From ce806317223d0b91b718c129dae62ef370e43cea Mon Sep 17 00:00:00 2001
From: MrSmite <bull@deadmines.cave>
Date: Sat, 2 Apr 2016 16:19:00 -0400
Subject: [PATCH] Fix pet aggro on owner damaged by DOT

---
 src/server/game/Entities/Unit/Unit.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 96ccc2c..63c400c 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -597,7 +597,7 @@ uint32 Unit::DealDamage(Unit* victim, uint32 damage, CleanDamage const* cleanDam
     // Hook for OnDamage Event
     sScriptMgr->OnDamage(this, victim, damage);
 
-    if (victim->GetTypeId() == TYPEID_PLAYER && this != victim)
+    if (victim->GetTypeId() == TYPEID_PLAYER && this != victim && damagetype != DOT)
     {
         // Signal to pets that their owner was attacked
         Pet* pet = victim->ToPlayer()->GetPet();
-- 
2.5.1.windows.1

```

**Comment by ccrs** [comment]
actually its better to check if owner is in combat or something like that

**Comment by MrSmite** [comment]
> actually its better to check if owner is in combat or something like that

Not really, on two points:

1. If the owner is in combat in a raid but waiting out of LOS for a debuff to wear off, you don't necessarily want the pet charging across the room after a mob that had cast a DoT on the player

2. Even with *damagetype=DOT*, if the player is in combat with the same creature (caster) there will always be cases where *damagetype* is something else (eg: direct spell damage or melee damage) in which case the pet would be notified.

**Comment by mik1893** [comment]
just tested it and it looks good to me... nice spot actually. Will produce a commit for this....

**Comment by MrSmite** [comment]
> just tested it and it looks good to me... nice spot actually. Will produce a commit for this....

Thanks, I haven't had time lately to mess around with the SSH problem.
