### ISSUE TITLE
[3.3.5] Quest: "Crowleg" Dan (11479)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16903]
3.3.5 f37682b

[Quest: "Crowleg" Dan](http://www.wowhead.com/quest=11479/crowleg-dan)

["Crowleg" Dan](http://www.wowhead.com/npc=24713/crowleg-dan) should have dialog option that makes him turn hostile and attack the player. This is currently missing.

**Comment by dr-j** [comment]
This npc does not change faction at all in sniff during this quest when option selected just becomes hostile and attacks faction remains at 10888 at all times.

Once http://www.wowhead.com/quest=11504/the-dead-rise has been returned (which is usually completed before player can take http://www.wowhead.com/quest=11479/crowleg-dan) player gains aura which makes this npc neutral with players.

And I have noticed this several times with wowhead wowhead data cant always be trusted as for if a mob is friendly, neutral or hostile as have seen several instances of wowhead giving wrong info here even though we know different.

Basically once http://www.wowhead.com/quest=11504/the-dead-rise has been rewarded crowleg dan and other npcs in the area are neutral not hostile.

~~~sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=24713 AND `source_type`=0 AND `id`>1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(24713, 0, 2, 3, 62, 0, 100, 0, 9335, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '"Crowleg" Dan - On Gossip Option Select - Close Gossip'),
(24713, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '"Crowleg" Dan - On Gossip Option Select - Start Attack');

DELETE FROM `gossip_menu_option` WHERE `menu_id`=9335;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `OptionBroadcastTextID`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `box_coded`, `box_money`, `box_text`, `BoxBroadcastTextID`) VALUES 
(9335, 0, 0, 'Ummm... the frog says you''re a traitor, "matey."', 25738, 1, 1, 0, 0, 0, 0, NULL, 0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=9335;

INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15, 9335, 0, 0, 0, 9, 0, 11479, 0, 0, 0, 0, 0, '', 'Crowleg" Dan - Only show Gossip if player is on quest');
~~~

Know have seen others but cant remember all but an example of info been incorrect as wether an npc is hostile or not is http://www.wowhead.com/npc=34925/north-sea-kraken
