### ISSUE TITLE
[3.3.5] Core/Spell: Paralytic Poison (35201)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16905]
3.3.5 476eb19

[Spell: Paralytic Poison](http://www.wowhead.com/spell=35201/paralytic-poison) should stun player after 30 seconds. It does not.

**Comment by Nawuko** [comment]
SpellWork: https://gist.github.com/Nawuko/26b537bc058baec5955976ab8762b7d8

Surprisingly there is no DUMMY effect and no custom flags on this spell.

**Comment by treak** [comment]
don't know if there is already an entry in db
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`= -35201;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(-35201,35202,0,'Paralytic Poison removed - cast Paralysis');

**Comment by tkrokli** [comment]
There is no world DB entry for `spell_trigger = -35201`, `spell_trigger = 35201`, `spell_effect = 35202` or `comment` `LIKE` `'%Paralytic Poison%'` in TDB 335.60 + updates up to and including `2016_04_03_02_world.sql`. I don't know if there should be a minus sign before the spell trigger or not.

**Comment by Treeston** [comment]
I'm not familiar with how``spell_linked_spell` works - would that trigger the Paralysis proc only on expiry or also on cleanse/other removal?

It should only proc on expiry.

**Comment by Nyeriah** [comment]
Using `spell_linked_spell` is a hack 90% of time

**Comment by treak** [comment]
what about this - i think there are more Paralytic Poison spells with the same issue, so sql seems not complete

```sql
DELETE FROM `spell_script_names` WHERE `spell_script_names` = "spell_gen_paralytic_poison";
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(35201, 'spell_gen_paralytic_poison');
```
```cpp
enum Whatever
{
	SPELL_PARALYSIS = 35202;
};

class spell_gen_paralytic_poison : public SpellScriptLoader
{
public:
	spell_gen_paralytic_poison() : SpellScriptLoader("spell_gen_paralytic_poison") { }

	class spell_gen_paralytic_poison_AuraScript : public AuraScript
	{
		PrepareAuraScript(spell_gen_paralytic_poison_AuraScript);

		bool Validate(SpellInfo const* /*spellInfo*/) override
		{
			if (!sSpellMgr->GetSpellInfo(SPELL_PARALYSIS))
				return false;
			return true;
		}

		void OnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
		{
			if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_EXPIRE || !IsExpired())
				return;

			if (Unit* target = GetTarget())
				target->CastSpell(target, SPELL_PARALYSIS, true);
		}

		void Register() override
		{
			AfterEffectRemove += AuraEffectRemoveFn(spell_gen_paralytic_poison_AuraScript::OnRemove, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL);
		}
	};

	AuraScript* GetAuraScript() const override
	{
		return new spell_gen_paralytic_poison_AuraScript();
	}
};

**Comment by Treeston** [comment]
@treak they all use the same spell

**Comment by treak** [comment]
ah ok - so my suggestion above stands

**Comment by mik1893** [comment]
mind to open a PR?
