### ISSUE TITLE
[335] Core/Item: Items disappear and become unusable when placed in bags equipped from bank until logout

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#16906]
**Description**:

Items disappear when placed in bags equipped from bank until logout

**Current behaviour**:

When you equip a bag from the guild bank and then place an item in it, the item will disappear until you log out. If the item also has a hotbar button, the button will become disabled.

The item itself is not lost however. If you drag / drop another item from a different bag onto the "empty" space, the "invisible" item will appear in the other bag and the new item dropped will vanish.

**Expected behaviour**:

Items placed in bags should not become invisible / unusable

**Steps to reproduce the problem**:
1. Add some bags to the guild bank (possibly personal bank, not tested)
2. Log in a different character (not sure if this is actually necessary)
3. Put your hearthstone and some items in your default backpack (eg: Tough Jerkey)
4. Drag the hearthstone to your hotbar
5. Make sure you have an empty bag slot
6. Drag a bag from the bank to your empty bag slot (NOTE: you can also drag it to your backpack and then equip it)
7. Open the new bag
8. Drag your hearthstone to an empty slot in the new bag
9. Observe the bag still appears empty
10. Observe the hotbar button for the hearthstone is disabled and doesn't work when clicked
11. Drag the other item (eg: Tough Jerkey) from your default backpack to the _same slot_ you dropped your hearthstone
12. Observe the other item (eg: Tough Jerkey) has now vanished but the hearthstone has appeared in your default backpack
13. Log out and back in
14. Observe all items appear where they were last dragged to and hotbar buttons are now active

**Branch(es)**: 335

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/cebdf03349ed0c50a40cf52ddae887cf666d1eb5 and https://github.com/TrinityCore/TrinityCore/commit/974703671ed5f08ec0c1a5b3943fc68508f2f4d6

**TDB version**: TDB_full_world_335.60_2015_11_07.sql

**Operating system**: Win XP / 7

**Comment by MrSmite** [comment]
Additional info, this also happens if:

1. You remove a bag from the guild bank to your inventory
2. Equip that bag in your personal bank

When you put items in this bag in your personal bank, they exhibit the same behavior as above until you log out. It would seem there is an issue with the code that handles removing the bag from the bank and creating an instance of it.

**Comment by Demonid** [comment]
Is this still an issue @MrSmite ?

I been having some issues with player items since the last update i did, it could be this or related.

Most of the items "Lost" are being used on Equipment Manager, but i don't have enough information yet.

**Comment by Nyeriah** [comment]
Oh, wow, this is definitely interesting.

I have been experiencing crashes when trying to pull up bags from the guild bank. However, I'm still not quite sure how, or why it happens. Definitely related to this.

https://pastebin.com/61cTifpM

**Comment by Jildor** [comment]
Confirm in rev 445c5a0

But the item not disappears from character_inventory, seems visual bug, then I think not related with #20106

**Comment by Killyana** [comment]
This was fixed, but I cannot find the commit, and I cannot reproduce the issue in  rev. 18a4cbee5eb1

**Comment by Killyana** [comment]
To reproduce the issue, you need 2 chars:
char1: will put a bag in the guild vault
char2: will take the bag from the guild vault and equip it and move some items inside it
Video:  https://imgur.com/D3X3nEb
