### ISSUE TITLE
[6.x] Core/Terrain Swap: Areas using Terrain Swap have issues with npc pathfinding

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#16909]
**Description**:

**Current behaviour**: NPC falls through the ground after taking a few steps, not to be found again until a server restart happens.  It's as if the new swapped area is not decently being used by the pathfinding of the NPC's.

**Expected behaviour**: The NPC should just walk and not fall through the ground?

**Steps to reproduce the problem**:
1. Enable Terrain Swap on a location like Lion's Landing, Dominion Point , this is done through the DB table terrain_swap_defaults and terrain_phase_info. (If you don't know the TerrainSwapMap id's, it's 1061 for Dominion Point and 1062 for Lion's Landing)
2. Go to said location that uses Terrain Swaps (like Lion's Landing, Dominion Point),.
3. Have any NPC move from their position (!cometome 1), they will fall through the ground after taking a few steps.

**Branch(es)**: 6x

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/363731aac827f3eab051064ba466cef49f6cc111 I'm still using 6.2.3, reluctant to go 6.2.4 yet. But this would not be fixed even if I was on 6.2.4

**TDB version**: latest TDB 6.03

**Operating system**: Windows 10 Pro, 64-bit

**Comment by funjoker** [comment]
i think it's related to the vmap issue too
