### ISSUE TITLE
[3.3.5] Quest. Sorlof's Booty (11529)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16904]
3.3.5 f37682b

[Quest: Sorlof's Booty](http://www.wowhead.com/quest=11529/sorlofs-booty)

[Sorlof](http://www.wowhead.com/npc=24914/sorlof) never shows up. The pirates on the ghost ship yell their lines seemingly at random, and at all times.

The ship itself is quite bugged, too, moving short distances, then stopping - it's a circle with only 3-4 stops on retail. The plank leading up to the ship at the boarding point is always visible, but should only appear while the ship is actually at the position. NPCs on the ship do not consistently spawn for the client, either.

**Comment by dr-j** [comment]
sorlof does show up he is spawned but there are visability issues here as you cannot see sorlof from the ship if you spam the cannon while facting him you will see the text about booty dropping then if you swim to the shore and search around you will find sorlof dead and his booty

**Comment by Rushor** [comment]
increase visibility range in server config? i don't think that's an issue

**Comment by AyrtonStout** [comment]
I also had a problem with Sorlof not really showing up, or showing up and then fading back out, not even a second later. He also seemed to recover his health very quickly when I fought him.

I ended up killing him by spamming the cannon as fast as I could click, without even seeing him. He died on the opposite side of the coast, not really anywhere near the boat.

**Comment by Killyana** [comment]
Visibility distance implemented.
