### ISSUE TITLE
[3.3.5][Warrior] Core/Spell: Cyclon on Bladestorm

### ISSUE THREAD

**Issue by Heisenberg520** [TrinityCore/TrinityCore#16901]
**Description:** I found a serious bug regarding spell Cyclone http://wowwiki.wikia.com/wiki/Bladestorm spell on the Warrior Bladestorm http://wowwiki.wikia.com/wiki/Cyclone . Basically what happens is that .. Once the player (a warrior) pulls the spell Bladestorm the only way to stop it should be the Disarm spell a Rogue or Priest, and so it happens ... but if a dude try to use the spell Cyclone to stop the spell of the war is not stopped as it should be, but the spell effect graphic is displayed on the player that should be immune during the duration of Bladestorm .. plus it allows the passage of damages by the Bladestorm .. but makes the player immune from direct damage or the damage of the dots that where already on the player

**Expected behaviour:** Bladestorm should be immune to the spell Cyclone

**Steps to reproduce the problem:**
1. Start a duel with a warrior
2. Put a dot on the warrior, tell him to use the spell Bladestorm, use the spell Cyclone on him and see what happens

**Branch(es)**: 3.3.5

**TC hash/commit**: https://github.com/trinitycore/TrinityCore/commit/5e74c2223bff8a467d6f1ce18f6f08aa05e17019

**TDB version**:

**Operating system**:

**Comment by Ascathor** [comment]
Does bladestorm grant special immunity ?

**Comment by Heisenberg520** [comment]
Bladestorm should be immune to all spell that interrupts it like hex.. Cyclon or any tipe of stun , controlls.. O anything else except the spell Disarm of the Rogue and the Priest that is the only way to interrupts it

**Comment by Ascathor** [comment]
@Joschiwald Any sniffs on additional casts with bladestorm ? Maybe an additional spell handling immunity.

**Comment by oMadMano** [comment]
Here is a way of adding spell immunity to Bladestorm. Notice that this does mpt omc;ide Cyclone but its should be good for you as a starting point.

```
-- Spells: Bladestorm
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 46924;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(46924, -13810, 2, 'Bladestorm immune at Frost Trap'),
(46924, -51514, 2, 'Bladestorm immune at Hex'),
(46924, -116, 2, 'Bladestorm immune at FrostBolt'),
(46924, -45524, 2, 'Bladestorm immune at Chains of Ice'),
(46924, -68766, 2, 'Bladestorm immune at Desecration'),
(46924, -58617, 2, 'Bladestorm immune at Glyph of Heart Strike'),
(46924, -605, 2, 'Bladestorm immune at Mind Control');
```

**Comment by Shauren** [comment]
That does not add any immunities, only removes these auras when applying bladestorm

**Comment by mik1893** [comment]
I just fixed it creating a check cast on the cyclone but it's quite an hacky way...

**Comment by noryad** [comment]
Please @ariel- this is a very important bug because it affects PVP.

**Comment by ariel-** [comment]
It's not important because "PvP", even if its PvE it is important, it's broken functionality after all.
