### ISSUE TITLE
[CORE / MySQL] Tome of Polymorph: Serpent [Patchfix]

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#16918]
**Description**:

**Current behaviour**: Tell us what happens
The Book : Tome of Polymorph: Serpent has not an assigned Spell what can be learned

**Expected behaviour**: Tell us what should happen instead
The book should learn a spell to the player.

**Steps to reproduce the problem**:

1. Login to the Server
2. Add Item 44600 [Tome of Polymorph: Serpent](http://wotlk.openwow.com/item=44600)
3. No Spell to learn avaible

**Branch(es)**: 335/6x
3.3.5A

**TC hash/commit**:
7834d339ad83f1262bd8cd6184b9da8401faddfe

**TDB version**:
TDB335.60

**Operating system**:
Linux Ubuntu X64

**Patchfix**

```sql
UPDATE `item_template` SET `spellid_1`=483, `spellcharges_1`=-1, `spellid_2`=61025, `spelltrigger_2`=6, `description`='Teaches Polymorph: Serpent.' WHERE  `entry`=44600;
```
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by dr-j** [comment]
well I know this works as looks like identical to what I am came up with 2 years ago (due to transfers who knew this spell) but this definitly should not be commited to tc as was only in wotlk beta but never made it to official wotlk release.

**Comment by Shauren** [comment]
Since it never made it to the game, closing

**Comment by Shoxxo** [comment]
It is in the files so it can be used, still the item was exist but no spell asaigned, i only assign the spell and thats all, i never say merge it into the database update :)

**Comment by tkrokli** [comment]
I was looking forward to having this spell available in-game by default, but it was too good to be true.
Just like a lot of the other beta-only spells. Anyway, the useful documentation can be found here:
- http://wow.gamepedia.com/Tome_of_Polymorph:_Serpent
- http://www.wowhead.com/item=44600/tome-of-polymorph-serpent#comments
