### ISSUE TITLE
[6.x] Crash regarding MMaps and Terrain Swap

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#16910]
**Description**: This is a crash issue that happens when MMaps are enabled and you try to teleport or enter a location that uses Terrain Swap

**Current behaviour**: The server crashes with the following call stack https://gist.github.com/DJScias/38fa629f607dc6970be96a6bc09850fc (I know it says revision unknown, but git is being a tool. It uses the TC Hash/commit found below)

**Expected behaviour**: The server shouldn't crash and use the proper MMaps in the Terrain Swap.

**Steps to reproduce the problem**:

1. Enable MMaps
2. Enable Terrain Swap on a location like Lion's Landing, Dominion Point , this is done through the DB table terrain_swap_defaults and terrain_phase_info. (If you don't know the TerrainSwapMap id's, it's 1061 for Dominion Point and 1062 for Lion's Landing)
3. Go to said location that uses Terrain Swaps (like Lion's Landing, Dominion Point), 
4. Get instantly crashed with the above crashlog

**Branch(es)**: 6x

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/363731aac827f3eab051064ba466cef49f6cc111 I'm still using 6.2.3, reluctant to go 6.2.4 yet. But this would not be fixed even if I was on 6.2.4

**TDB version**: latest TDB 6.03

**Operating system**: Windows 10 Pro, 64-bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by streetrat** [comment]
https://github.com/TrinityCore/TrinityCore/commit/32e8b6506fc064fdba134d692dfe99298e43f055
above commit fixes a memleak, but totally breaks the map swap stuff

**Comment by Shauren** [comment]
@streetrat  If you know this code and how it should work, why haven't you pushed something that fixes both the memory leak and maintains working swaps?

**Comment by jackpoz** [comment]
Did you paste only a part of the crashlog instead of the complete file ?

**Comment by Warpten** [comment]
There really is no need for a crashlog. the tile is allocated with DT_TILE_FREE_DATA, it should be deallocated with DT_TILE_FREE_DATA.

**Comment by DJScias** [comment]
@jackpoz I did, considering it's about 71K lines, unless you want the full thing then I can also take care of that. :)

Kind regards,
DJScias

**Comment by et65** [comment]
@DJScias: Try this fix https://gist.github.com/et65/3bfe03eb23279fb0e5d42a496afe9a98

It removes the recast navigation DT_TILE_FREE_DATA added by Carbenium in commit 32e8b6506fc064fdba134d692dfe99298e43f055 and fixes memory leaks concerned by this same commit.

If it seems to work for everyone, I'll make a pull request.

**Comment by et65** [comment]
@DJScias : Try this fix: https://gist.github.com/et65/3bfe03eb23279fb0e5d42a496afe9a98

It removes the recast navigation DT_TILE_FREE_DATA added by Carbenium in commit 32e8b65 and fixes memory leaks concerned by this same commit.

If it seems to work for everyone, I'll make a pull request.

**Comment by Aokromes** [comment]
@et65 allways better create the pr directly.

**Comment by et65** [comment]
@Aokromes : I prefered waiting for feedbacks before, but I'm pretty sure my fix is correct... I'll make a pull request tonight ;)
