### ISSUE TITLE
[3.3.5] DB/GO: Bubbly Fissure in Desolace and Moonglade

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#16925]
**Description**: most of the Bubbly Fissure game objects currently do not have the underwater breathing spell Air Bubbles (http://www.wowhead.com/spell=17775/air-bubbles) in areas used for underwater questing. This is my suggestion for a way to set the gameobject values to make it work:

``` sql
UPDATE `gameobject_template` SET `type`= 6, `faction`= 0, `Data1`= 0, `Data2`= 8,
 `Data3`= 17775, `Data5`= 1 WHERE `entry`= 177524;
```

These values are duplicated from the Bubbly Fissure in Lushwater Oasis (GO entry 180057).

**Current behaviour**: Currently, the only Bubbly Fissure that works (at least in 3.3.5, have not tested this in 6.x) is the Lushwater Oasis Bubbly Fissure GO 180057, in the big pool where the level 20 rare elite Gesharan can be found. The Bubbly Fissure `gameobject_template` entry 177524, used off the coast of Desolace and in Lake Elune'ara in Moonglade, currently does not work even if you add the spell Air Bubbles (17775) to its DB template entry. As a player, you are forced to surface to get air or get underwater breathing potions (or, as a shaman,use waterbreathing spell or a druid can shapeshift to seal). This is practical for questing and searching for the Big Iron Fishing Pole (http://wotlk.openwow.com/item=6367) in the Shellfish Trap game objects off the coast of Desolace.

Current values for gameobject 177524 in TDB 335.60 + updates, compared to entry 180057:

``` sql
SELECT * FROM `gameobject_template` WHERE `entry` IN (177524, 180057);
```

```
 entry    type  displayId  name            IconName  castBarCaption  unk1    faction   flags    size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  AIName  ScriptName  VerifiedBuild
------  ------  ---------  --------------  --------  --------------  ------  -------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ----------  ---------------
177524       8        344  Bubbly Fissure                                         14       0       1       0      10       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
180057       6        344  Bubbly Fissure                                          0       0    0.98       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
```

Currently spawned in-game objects of entry 177524 in the DB:

``` sql
SELECT * FROM `gameobject` WHERE `id`= 177524 ORDER BY `id`, `guid`;
```

```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  position_x  position_y  position_z  orientation  rotation0  rotation1  rotation2  rotation3  spawntimesecs  animprogress   state  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  ----------  ----------  ----------  -----------  ---------  ---------  ---------  ---------  -------------  ------------  ------  ---------------
 31684  177524       1       0       0          1          1    -1876.68     3378.85    -70.1771            0          0          0          0          1            900           100       1              0
 31896  177524       1       0       0          1          1    -588.114     2858.04    -38.5369     0.628319          0          0   0.309017   0.951057            900           100       1              0
 31897  177524       1       0       0          1          1    -498.033     2739.48    -30.6666    -0.750491          0          0   0.366501  -0.930418            900           100       1              0
 31899  177524       1       0       0          1          1    -76.6455     2685.81    -99.1043      1.88496          0          0   0.809017   0.587785            900           100       1              0
 31900  177524       1       0       0          1          1    -1985.92     3374.38    -80.1733            0          0          0          0          1            900           100       1              0
 31901  177524       1       0       0          1          1       -1944     3222.99    -69.3751     -2.19912          0          0   0.891007   -0.45399            900           100       1              0
 31902  177524       1       0       0          1          1    -147.745     2589.38    -48.1679    -0.698132          0          0    0.34202  -0.939693            900           100       1              0
 31903  177524       1       0       0          1          1     161.034     2742.56    -71.4729     -2.70526          0          0   0.976296   -0.21644            900           100       1              0
 31905  177524       1       0       0          1          1    -22.3517     2831.51    -34.2596    -0.802851          0          0   0.390731  -0.920505            900           100       1              0
 31906  177524       1       0       0          1          1     55.2842     2842.69    -83.0677      2.53073          0          0   0.953717   0.300706            900           100       1              0
 31907  177524       1       0       0          1          1     -1829.4     3280.41    -68.2534      1.58825          0          0    0.71325   0.700909            900           100       1              0
 49216  177524       1       0       0          1          1     7675.39    -2659.36     406.346      1.01229          0          0    0.48481    0.87462            900           100       1              0
 49217  177524       1       0       0          1          1     7697.36    -2569.16      400.31    -0.767945          0          0   0.374607  -0.927184            900           100       1              0
```

In the GUID values column you can see that there are 11 GOs (31684-31907) off the coast of Desolace and 2 GOs in Lake Elune'ara (49216,49217) using the same GO entry (177524).

Sidenote issue in The Barrens: the Forgotten Pools fissure visual does not seem to have any GO at all (check by using the command `.gobject near` , result: only mining veins), but in retail it used to contain an active Bubbly Fissure, at least before Cataclysm. (I never visited those pools on retail after Cataclysm back in 2010-2012.) I am certain that the other Bubbly Fissures in The Barrens also used to have a functional Bubbly Fissure with the spell Air Bubbles available, like in the Sludge Fen and in the Stagnant Oasis pool, to make it more intriguing for new players to find out in which context these fissures where "magical" and discover the link to Wailing Caverns. The fissures in Sludge Fen and Stagnant Oasis are currently used for as specific quest objects with unique values, so I have no intention of changing those. I am guessing that to make those 2 work as a Bubbly Fissure as well it would be necessary to spawn an extra GO with the same settings as the Lushwater Oasis fissure, in the exact same position as the existing GO or visual texture. I am not sure how that could be done without getting visual overlay glimmer, like in other GO double spawns. Maybe it can be made non-interactive or invisible to avoid the visual issue.

**Expected behaviour**: All the Bubbly Fissure game objects should provide the spell Air Bubbles (17775) giving the player character the underwater breathing ability in a 8-10 yard radius from the game object.

**Steps to reproduce the problem**:
1. When testing in Desolace, use a character level 35 or higher to fend off nearby mobs.
2. `.go object #object_guid` (31684,31896,31897,31899,31900,31901,31902,31903,31905,31906,31907,49216,49217)
3. Observe that you don't get any underwater breathing buff from any of those game objects.
4. Compare with Lushwater Oasis fissure: `.go object 13380` (`gameobject_template` entry 180057)

**Branch(es)**: 335/6x Tested on 3.3.5, I have not researched this on 6.x.

**TC hash/commit**: rev. 7834d339ad83 2016-04-06 00:14:01 +0200 (3.3.5 branch) (Win64, Release)

**TDB version**: 335.60 + updates up to and including `2016_04_05_01_world.sql`

**Operating system**: Windows 10 Home x64, version 1511 build 10586.164

**Comment by Kittnz** [comment]
So gob 177524 should cast 17775? SAI?

Offtopic: Gonne be honest here, i am glad you do these reports but i just feel such a drag to read this all. So i am calling TLDR :dancer: 
Sorry xD

**Comment by tkrokli** [comment]
OK, I get what you're saying, I tend to write too much for some users' taste. Sorry about that. :-p

From looking at the Bubbly Fissure in Lushwater Oasis (outside Wailing Caverns), I found out that it is the only current working Bubbly Fissure (at least in Kalimdor). SAI should not be needed if the properties from GO 180057 are duplicated. The GO itself can make the Air Bubbles spell active.

Although since this is about entries in `gameobject_template`, I suppose sniff info must be used.

Maybe SAI can be used to make them work, I don't know yet (haven't tested).

If you want to see all the entries similar to the working one in the DB, they can be looked up like this:
```sql
SELECT * FROM `gameobject_template` WHERE `displayId`= 344 ORDER BY `entry`;
```
```
 entry    type  displayId  name              IconName  castBarCaption  unk1    faction   flags    size   Data0   Data1   Data2   Data3   Data4   Data5   Data6   Data7   Data8   Data9  Data10  Data11  Data12  Data13  Data14  Data15  Data16  Data17  Data18  Data19  Data20  Data21  Data22  Data23  AIName  ScriptName  VerifiedBuild
------  ------  ---------  ----------------  --------  --------------  ------  -------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ------  ----------  -------------
  3737      10        344  Bubbling Fissure                                         35       4       1      73     877     525       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
  3740       2        344  Bubbling Fissure                                          0       0       1       0     523       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
177524       8        344  Bubbly Fissure                                           14       0       1       0      10       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
180057       6        344  Bubbly Fissure                                            0       0    0.98       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187446       6        344  Bubbly Fissure                                           14       0    1.04       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187447       6        344  Bubbly Fissure                                           14       0    1.19       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187448       6        344  Bubbly Fissure                                           14       0    1.21       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187449       6        344  Bubbly Fissure                                           14       0    1.14       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187450       6        344  Bubbly Fissure                                           14       0    1.33       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187451       6        344  Bubbly Fissure                                           14       0    1.14       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              11723
187452       6        344  Bubbly Fissure                                           14       0    1.36       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187453       6        344  Bubbly Fissure                                           14       0    1.39       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187454       6        344  Bubbly Fissure                                           14       0    1.21       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187455       6        344  Bubbly Fissure                                           14       0    1.45       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
187456       6        344  Bubbly Fissure                                           14       0    1.47       0       0       8   17775       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0                              12340
```

**Comment by Rushor** [comment]
mainproblem will be that changing the db values for 177524 is a hack :(

**Comment by Kittnz** [comment]
Not if there are sniffs :dancer:

**Comment by Aokromes** [comment]
There is any sniff confirming this?

**Comment by tkrokli** [comment]
I don't know, I haven't tried to search for it. I find it hard to read through the big text files without any other tools than Ctrl-F to find values. Isn't there a simple tool to filter that information out from there?

You can just close this issue because it is too full of text and hard to read in itself. If I feel like it at a later time, I can fill in the issue template (which was created later than this issue) in a week or 2.

**Comment by Kittnz** [comment]
Don't have any sniffs dating back before cata for this.

**Comment by tkrokli** [comment]
I can understand why, it is not very likely that someone would have thought about sniffing bubbly fissures in pools, also the fact that they usually tend to not be near any interesting mobs. I just find it a bit strange that only one fissure works by supplying the underwater breathing buff and not the others.

**Comment by Kittnz** [comment]
Well yes just on spawn cast xxxx

**Comment by tkrokli** [comment]
:+1: Thanks for reminding me. (note to myself: set `AIName = SmartGameObjectAI` in `gameobject_template`)
Have to focus on finishing 2 other PRs first before getting to test this, got a lot to think about these days. :)

**Comment by Elarose** [comment]
Sent one of moonglade bubbly fissure, if it works out let me know so I can get the rest. Oh and retail behaviour of it, not that it shows much, moreso the longevity of buff, need to be right on it almost to get it, but can swim away alot further and still have it. 
https://youtu.be/Io2fMtriwwE

**Comment by tkrokli** [comment]
> https://www.youtube.com/watch?v=Io2fMtriwwE&feature=youtu.be&ab_channel=ElaroseLabouveay

Looks good to me. That is what I would expect from a Bubbly Fissure when it is Blizzlike. The whole point is not needing to surface to get air and continue searching the floor of the lake/sea/ocean near that location.

**Comment by Elarose** [comment]
Yes an old issue.  Get back to me if the sniff uploaded was of any use so I can get the rest is what I meant to say. =P

**Comment by tkrokli** [comment]
TrinityCore rev. e45d54d80e3f 2018-01-29 18:10:37 +0100 (3.3.5 branch) (Win64, Release, Static)

Update / fun fact: the sea floor in the [Sar'theris Strand](https://wow.gamepedia.com/Sar%27theris_Strand) area just outside of [Shadowprey Village](https://wow.gamepedia.com/Shadowprey_Village) where you find the [Shellfish Trap](https://wow.gamepedia.com/Shellfish_Trap) cages (those you can loot (grind) for the [Big Iron Fishing Pole](https://wow.gamepedia.com/Big_Iron_Fishing_Pole) or find the [Shellfish](https://wow.gamepedia.com/Shellfish) needed for the quest http://www.wowhead.com/quest=5421/fish-in-a-bucket) seems to have got a randomly spread pocket areas where the [[-Breath-]](https://wow.gamepedia.com/Breath_Status_Bar) bar fills up and disappears, but no visible [Breathing]. These spots are not connected to the Bubbly Fissure gameobjects, but seem to appear more frequently near the Shellfish Trap cages (although not consistently). I was grinding those traps for more than 45 minutes, but could not discover any obvious pattern for where it triggers.

Do any of you have any idea if this is something which should originally be tied to the bubbly fissure gameobjects, but has lost its limitations and has become "magic escaped in the wild"?

**Comment by illfated** [comment]
Interesting. Looks like the bubbly fissure 177524 is not meant to give a buff.
> -- data based on sniffs - 177524 is not meant to give the buff in any way

Then again, https://github.com/cmangos/tbc-db/commit/ca1e358a1f61ff8eeb6882f3ecdebd084b3ffcb0  seems to have added
```sql
UPDATE gameobject_template SET data2=8 WHERE entry IN (180057);
```
Not sure what kind of change that bit makes.
