### ISSUE TITLE
[3.3.5][Blackwing Lair][Razorgore the Untamed]

### ISSUE THREAD

**Issue by silvermcd123** [TrinityCore/TrinityCore#16924]
**Current behaviour**: In this fight at blackwing lair we are supposed to destroy the eggs while the group handles the killing of the adds. If you wipe and then you try to enter dungeon it says "fight in progress".

**Expected behaviour**: You should be able to enter the dungeon after a wipe.

**Steps to reproduce the problem**:

1. Enter BWL.
2. Start Razorgore the Untamed.
3. Wipe and try to enter again.

**Branch(es)**: 335

**TC hash/commit**:TrinityCore rev. 7834d339ad83+ 2016-04-06 00:14:01 +0200 (3.3.5 branch) (Unix, Release)

**TDB version**: TDB 335.57

**Operating system**: CentOS 7 64 bits

**Comment by Aokromes** [comment]
#6756
