### ISSUE TITLE
[6.x] Crash on login when adding port to ip address client config

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#16927]
[crashlog.txt](https://github.com/TrinityCore/TrinityCore/files/210761/crashlog.txt)
**Description**:
When you add a port to your realmlist, portal and patchlist like 127.0.0.1:8085 and log in after the worldserver crashes.

**Current behaviour**: Tell us what happens
Login with the named problem will crash the worldserver

**Expected behaviour**: Tell us what should happen instead
The worldserver should be able to handle such a foolish mistake by the user without crashing.

**Steps to reproduce the problem**:

1. use following setting for testings:
SET portal "127.0.0.1:8085"
SET realmlist "127.0.0.1:8085"
SET patchlist "127.0.0.1:8085"

2. start the game and login with the account

3. wittness the crash

**Branch(es)**: /6x

**TC hash/commit**:
f4029faecee41ef9843362f993292a1576c19626

**TDB version**:
TDB 6.03

**Operating system**:
Windows 10 Pro x64

**Comment by Nelidon** [comment]
You should read again instructions to play on a TrinityCore server.

**Comment by Ovahlord** [comment]
I know how to get into the server in the right way, it might be intresting anyways that connecting the wrong way is killing the worldserver.

**Comment by Ascathor** [comment]
realmlist and patchlist are not supposed to be added, but I can see what you mean.
