### ISSUE TITLE
[BUG] Icecrown Citadel Raid

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#16929]
**Description**:
I just update to master with some custom changes, nothing to big; most of them on scripts. But aparently something broke after update, re-check the scripts cant find with is not working:

```c#
                    case NPC_GARROSH_HELLSCREAM:
                        if (TeamInInstance == ALLIANCE)
                            creature->UpdateEntry(NPC_KING_VARIAN_WRYNN);
                        break;
```
**Current behaviour**: 
At Instance Enter as team alliance appear Garrosh
**Expected behaviour**:
At instance enter should appear Varian when alliance team

**Branch(es)**: 335/6x
335
**TC hash/commit**:
7834d339ad83f1262bd8cd6184b9da8401faddfe
**TDB version**:
60
**Operating system**:
Linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Killyana** [comment]
Cannot reproduce on TrinityCore rev. 6ca400b35eb4
Maybe the cross-faction is activated and the first player who get inside the raid was from the horde.

**Comment by n4ndo** [comment]
@Killyana thanks for your answer, but.... tc even have a cross-faction option?

**Comment by n4ndo** [comment]
@Killyana 

Aparently here is the error:

```c#
            void OnCreatureCreate(Creature* creature) override
            {
                if (!TeamInInstance)
                {
                    Map::PlayerList const &players = instance->GetPlayers();
                    if (!players.isEmpty())
                        if (Player* player = players.begin()->GetSource())
                            TeamInInstance = player->GetTeam();
                }
```

The PlayerList array is allways empty, and the Team only appears on

```c#
            void OnPlayerEnter(Player* player) override
            {
                if (!TeamInInstance)
                    TeamInInstance = player->GetTeam();
```
