### ISSUE TITLE
[3.3.5][6.x] DB/Quest: Warsong Recruitment Officer

### ISSUE THREAD

**Issue by Xanvial** [TrinityCore/TrinityCore#16926]
There's two bug regarding this npc.
When player finished quest http://www.wowhead.com/quest=10172/there-is-no-hope, which is final quest for hero of Maghar chain quest, Warsong Officer should give http://www.wowhead.com/quest=11586/hellscreams-vigil, if not, The officer will instead give http://www.wowhead.com/quest=11585/hellscreams-vigil

**Current behaviour**: 
- Warsong Recruitment Officer give wrong quest, ie. quest 11586 to player that hasn't finished Maghar quest.
- After player take/finished the quest, there still quest mark from the Officer

**Expected behaviour**: 
- if finished quest 10172, give player quest 11586, if not give 11585
- Quest mark should be disappeared after player finished one of the quest

here's the fix from 1st problem (just swap from previously commited fix)
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND (`SourceEntry`=11586 OR `SourceEntry`=11585);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceEntry`,`ConditionTypeOrReference`,`ConditionValue1`,`Comment`) VALUES 
(19, 11585, 14, 10172, "Accept quest 11585 - Quest 10172 needs to be incomplete"),
(19, 11586, 8, 10172, "Accept quest 11586 - Quest 10172 needs to be rewarded");
```

For the 2nd problem, i can only find partial fix, here (unneeded, use dr-j code below )
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 20 AND `SourceEntry` IN (11585, 11586);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(20, 0, 11585, 0, 0, 8, 0, 11586, 0, 0, 1, 0, 0, '', 'Show Mark quest 11585 - Quest 11586 is not taken'),
(20, 0, 11585, 0, 0, 9, 0, 11586, 0, 0, 1, 0, 0, '', 'Show Mark quest 11585 - Quest 11586 is not rewarded'),
(20, 0, 11586, 0, 0, 8, 0, 11585, 0, 0, 1, 0, 0, '', 'Show Mark quest 11586 - Quest 11585 is not taken'),
(20, 0, 11586, 0, 0, 9, 0, 11585, 0, 0, 1, 0, 0, '', 'Show Mark quest 11586 - Quest 11585 is not rewarded');
```
With this, the mark will disappear when user finish the quest, but not when user still has the quest in log. Not sure what's wrong with my conditions

**Branch(es)**: 335

**TC hash/commit**: 4afea55b2c60

**TDB version**: TDB 335.60

**Operating system**: Win 8.1

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
There is a known issue about some quest givers and that their question mark remains above their head, even if the quest has just been rewarded. In most of these cases, you have to move out of view distance from the quest giver and then come back, to make the question mark go away from the NPC.

**Comment by Aokromes** [comment]
Yeah, the 2nd is core bug, a ticket of it exists.

**Comment by dr-j** [comment]
Actually for the 2nd one try

~~~sql
UPDATE `quest_template_addon` SET `ExclusiveGroup`=11585 WHERE  `ID`IN(11585,11586);
~~~
as at the moment neither are exclusive grouped so if player completes quest 11585 and then later complete quest 10172 then player will be then able to take quest 11586 and believe player should only ever be able to take one version of this.

By setting exclusive group (+) it prevents any other quest in that group been taken if player either has one quest from that group taken or rewarded.

**Comment by Xanvial** [comment]
Using @dr-j code will fix the 2nd bug, without needing to add my code.

Maybe in another cases where the quest mark still shown, can be fixed like this too?
