### ISSUE TITLE
GO wrong respawntime + Fix

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16931]
```sql
-- Wrong respawntimer for Quest GameObjects
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `guid` IN (45719,45720,45721);
```
**Branch(es)**: 335

**TC hash/commit**:

**TDB version**:
TC>TrinityCore rev. 6ca400b35eb4 2016-04-09 23:23:07 +0200 (335 branch)

**Comment by Aokromes** [comment]
What quest uses this gameobjects?

**Comment by tkrokli** [comment]
The gameobjects are used in the Alliance (G) quest [[The Eastern Plagues](http://www.wowhead.com/quest=6185/the-eastern-plagues)]
For those who wonder about the quest details, here are a couple of links:
- http://wow.gamepedia.com/Quest:The_Eastern_Plagues
- http://www.wowhead.com/quest=6185/the-eastern-plagues
