### ISSUE TITLE
It can connect into Bnet

### ISSUE THREAD

**Issue by Dokman** [TrinityCore/TrinityCore#16939]
**Description**:
BnetServer it does not connect

**Current behaviour**: Tell us what happens
When i've compiled the newest TrinityCore The new auth method doesn't do anything

**Expected behaviour**: Tell us what should happen instead
I think is mostly done, so... it has to log in but i can't do anything

**Steps to reproduce the problem**:

1. Start Authserver
2. Log into you account
3. Served for the bug

**Branch(es)**: 335/6x
6x

**TC hash/commit**:
https://github.com/TrinityCore/TrinityCore/commit/926dfd1b571baa3da80f36f20412f3ecd50c2b8b

**TDB version**:
TDB 6.04

**Operating system**:
Windows 10 Pro

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Ovahlord** [comment]
set the portal in your config wtf to your local host eg. 127.0.0.1 like its descriped in the wiki. Following to that dont forget to link your battlenet account with the game account to make it working properly.

**Comment by Dokman** [comment]
i know and is made hahah

**Comment by Dokman** [comment]
in any case works...
![wowscrnshot_041116_234634](https://cloud.githubusercontent.com/assets/2290904/14443449/ae4f77cc-003f-11e6-9071-24d4446cd30c.jpg)

**Comment by Dokman** [comment]
.bnet account create mymal@domain password i know how it works

**Comment by Ovahlord** [comment]
keep in mind that using any patched wow.exe will not work. you have to use your own one by using your own connection patcher.

**Comment by Dokman** [comment]
yes it's a basic thing that i do everytime that you update the build and i update the client too...

**Comment by msoky** [comment]
I have this problem too, now solved https://community.trinitycore.org/topic/12501-cant-log-in-to-624-client/

**Comment by Aokromes** [comment]
It's configuration issue not tc issue.
