### ISSUE TITLE
Death Knight Spell's and Quest broken

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16948]
Some spells will no longer work:
Death Grip
http://www.wowhead.com/spell=49576/death-grip
Raise Dead
http://www.wowhead.com/spell=46584/raise-dead

Quest:12619 can't complet no more
If you use the Runebladed Sword nothing happens
http://www.wowhead.com/quest=12619/the-emblazoned-runeblade

On this release works all fine . TC>TrinityCore rev. 048a01f778bd 2016-04-11 03:22:51 +0100 (335 branch)
**Branch(es)**: 335

**TC hash/commit**
On this Release are the spells and Quest broken
TC>TrinityCore rev. 131ef5f2d682 2016-04-11 23:12:23 +0200 (335 branch)

**Operating system**:
Win7 64Bit

**Comment by Naios** [comment]
The error is related to eaf102b3c59232af9371839c10b6b3e8368b9cfd, I'm currently investigating...

**Comment by Nawuko** [comment]
Had the same Problem. I deleted my build directory completly and re-run cmake. Now everything works fine.

@Naios Reloading works fine on Release builds. On debug builds the worldserver crashes (it wants to write scripts_northrend.pdb (or any other scripts_*.pdb) which is currently loaded (locked) by other programs. I rewrote 2 bosses and had only 2-3 crashes. (Occured while changing the complete AI type from ScriptAI to BossAI). Everything else works fine. Good job :+1:

**Comment by Tauriella** [comment]
Thanks for your fast answer
1 have 100 Options testet for cmake and always the same result
@Nawuko can you please test the Spells and the one Quest ?

**Comment by Naios** [comment]
@Nawuko Yep, when you want to reload scripts you first need to detach the debugger to unlock the .pdb's .

**Comment by Nawuko** [comment]
Yea most of the spell scripts are broken. Mage Waterelemental, Questscripts etc.
Maybe a static compile works. Or just wait until @Naios has figured out why spell/questscripts dosent get executed correctly.

**Comment by Naios** [comment]
I figured the issue out already and will push the fix soon.

**Comment by Nawuko** [comment]
http://wowwiki.wikia.com/wiki/Soon

**Comment by Tauriella** [comment]
Nice Job
Thanks :+1:
