### ISSUE TITLE
Missing Dalaran visitor

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCore#16943]
**Description**:Missing Dalaran visitor

**Current behaviour**: no Dalaran visitor in dalaran

**Expected behaviour**: in dalaran,zone-6626 should have Dalaran visitor coming

**Steps to reproduce the problem**:

1. go to dalaran,zone-6626

**Branch(es)**: 335

**TC hash/commit**:https://github.com/TrinityCore/TrinityCore/commit/131ef5f2d682763e301102047f2f0118c88ac42d

**TDB version**:335.61

**Operating system**:windows

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Kittnz** [comment]
Dupe, https://github.com/TrinityCore/TrinityCore/issues/12581
