### ISSUE TITLE
Missing a plot after Kill Kil'jaeden

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCore#16944]
**Description**:Missing a plot after Kill Kil'jaeden

**Current behaviour**: nothing

**Expected behaviour**: after kill Kil'jaeden,we will see a short story,you can see this in youtube or other site or google

**Steps to reproduce the problem**:

1. kill Kil'jaeden in sunwell

**Branch(es)**: 335

**TC hash/commit**:https://github.com/TrinityCore/TrinityCore/commit/131ef5f2d682763e301102047f2f0118c88ac42d

**TDB version**:335.61

**Operating system**:windows

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
Duplicate, this problem is covered by issue  **[[3.3.5][6.x][SWP] Kil'Jaeden does not attack](11624)** #11624

**Comment by Rushor** [comment]
issue merged with https://github.com/TrinityCore/TrinityCore/issues/11624
