### ISSUE TITLE
Error @compile fresh 3.3.5a Core

### ISSUE THREAD

**Issue by puder** [TrinityCore/TrinityCore#16950]
**Description**: Error @compile fresh 3.3.5a Core
**Current behaviour**: i updatet my core 

--- Here the Error on Linx ---
> [ 44%] Building CXX object src/server/game/CMakeFiles/game.dir/Maps/TransportMgr.cpp.o
> [ 45%] Building CXX object src/server/game/CMakeFiles/game.dir/Maps/MapScripts.cpp.o
> [ 45%] Building CXX object src/server/game/CMakeFiles/game.dir/Maps/MapUpdater.cpp.o
> /home/test/src/server/game/Scripting/MapScripts.cpp: In member function ‘void Map::ScriptsStart(const ScriptMapMap&, uint32, Object*, Object*)’:
> /home/test/src/server/game/Scripting/MapScripts.cpp:61:21: error: ‘class ScriptMgr’ has no member named ‘IncreaseScheduledScriptsCount’
>          sScriptMgr->IncreaseScheduledScriptsCount();
>                      ^
> compilation terminated due to -Wfatal-errors.
> src/server/game/CMakeFiles/game.dir/build.make:3090: recipe for target 'src/server/game/CMakeFiles/game.dir/Scripting/MapScripts.cpp.o' failed
> make[2]: *** [src/server/game/CMakeFiles/game.dir/Scripting/MapScripts.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ^[[24~CMakeFiles/Makefile2:1133: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
> make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
> Makefile:117: recipe for target 'all' failed
> make: *** [all] Error 2

here on windows (ger edition)
12>F:\test\test\src\server\game\Scripting\MapScripts.cpp(61): error C2039: "IncreaseScheduledScriptsCount": Ist kein Element von "ScriptMgr"
12>  f:\test\test\src\server\game\scripting\ScriptMgr.h(835): note: Siehe Deklaration von "ScriptMgr"
12>F:\test\test\src\server\game\Scripting\MapScripts.cpp(89): error C2039: "IncreaseScheduledScriptsCount": Ist kein Element von "ScriptMgr"
12>  f:\test\test\src\server\game\scripting\ScriptMgr.h(835): note: Siehe Deklaration von "ScriptMgr"
12>F:\test\test\src\server\game\Scripting\MapScripts.cpp(881): error C2039: "DecreaseScheduledScriptCount": Ist kein Element von "ScriptMgr"
12>  f:\test\test\src\server\game\scripting\ScriptMgr.h(835): note: Siehe Deklaration von "ScriptMgr"

**Branch(es)**: 335

**TC hash/commit**: e82a934 

**TDB version**:TDB 335.60

**Operating system**: Linux and Windows

**Comment by Naios** [comment]
Did you rerun CMake? Since the travis build passes https://travis-ci.org/TrinityCore/TrinityCore/builds/122538792

**Comment by puder** [comment]
Same error and on windows i delete the cmake cache, on linux i delete the order and create a new.
![123123](https://cloud.githubusercontent.com/assets/17888937/14466811/c0d3087a-00d8-11e6-9d2d-9e142936ed75.jpg)
![4342](https://cloud.githubusercontent.com/assets/17888937/14466904/0e03b130-00d9-11e6-9ffb-f96a0bcb1659.jpg)

**Comment by Naios** [comment]
You are using an outdated source, the MapScripts were moved to `game/Maps` and are no longer contained in `game/Scripting`

**Comment by puder** [comment]
I have now tested and you're right, the fault lay with me. Thank you
