### ISSUE TITLE
lost my GM command

### ISSUE THREAD

**Issue by Jaihoob** [TrinityCore/TrinityCore#16952]
no more command in commit a3936c1

1. when i try using command in game dont exist
2. same in worldserver  window

**Branch(es) 6x

**TC hash/commit**: a3936c1

**TDB version**: 6.04

**Operating system**: win  10 64 bit  but my core is 32bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#16949
