### ISSUE TITLE
Boss dead by self inflicted damage don't trigger instance bind

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#16971]
**Description**:  If a boss dies from self inflicted damage, he won't trigger instance binding to the players

**Current behaviour**: Kill Baron Geddon, at 2%health he will self kill, no instance binding is triggered

**Expected behaviour**: Killing him should bind players to the instance.

**Steps to reproduce the problem**:

1. .go crea id 12056
2.  Kill Baron Geddon
3. Note that you won't be saved to instance

**Branch(es)**: 335

**TC hash/commit**: e38e1c0c549c

**TDB version**: 335.61

**Operating system**: Windows

**Linking model**: dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by myran2** [comment]
Maybe something like this?
https://github.com/myran2/TrinityCore/commit/e370a8dd47776d7222f1ecc27a795549dcaf370a
This is untested though.

**Comment by sirikfoll** [comment]
Well, it works :+1:
