### ISSUE TITLE
Vmaps problem

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#16979]
**Description**: Vmaps doesn't work

**Current behaviour**: players and npc can cast through wall or many other objects.

**Expected behaviour**: players and npc cannot cast through wall  or many other objects.

**Steps to reproduce the problem**:

1. with a player cast any damage spell to enemy or npc. maybe get duel with other player.
2. i tested in different zones like instances and open world

PD: 1 month ago vmaps workd ok (i apply updates once a month)

**Branch(es)**: 335

**TC hash/commit**: 81cee23

**TDB version**: 335.61

**Operating system**: Linux

**Linking model**: static/dynamic dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DDuarte** [comment]
Indicate a hash/version when it worked (something better than "1 month ago") and a specific place where the issue can be reproduced.

**Comment by innermous** [comment]
Git bisect might be handy for code glitch searching.

**Comment by Aokromes** [comment]
On  f9697cb86abf they work.

**Comment by IngMak** [comment]
12 mar it works f52495c

**Comment by Killyana** [comment]
Cannot reproduce on rev. dc3327f9c5f8

**Comment by Aokromes** [comment]
Cannot reproduce on 32cadcb1bb73.

**Comment by tkrokli** [comment]
I was not able reproduce the issue on 32cadcb1bb73 either, just as Aokromes said. No problems with LoS, works as intended with newly generated dbc, maps and vmaps (mmaps from March 2016 in use).
