### ISSUE TITLE
Flying Machine Engine respawntimer fix

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16970]
```sql
-- Wrong respawntimer for Quest GameObjects
-- Flyin Machine Engine
UPDATE gameobject SET spawntimesecs = 2 WHERE guid = 61208;
```
http://www.wowhead.com/object=190447/flying-machine-engine

**Branch(es)**: 335/6x

**TC hash/commit**:
TrinityCore rev. e38e1c0c549c 2016-04-15 01:56:05 +0200 (335 branch)
**TDB version**:
.61
**Operating system**:
Win.7

**Comment by Tauriella** [comment]
Sorry i have edited my first post i have changed the id to guid

**Comment by tkrokli** [comment]
Is there a practical reason why you changed to GUID instead of ID in this case? If the object only has 1 spawned entry in the `gameobject` table, it is safe to use the ID value. Theoretically, GUIDs could change, so ID is usually safer, given that there is only 1 entry (ID) of that object.

IMHO it is more practical to use GUID when you want to change specific separate spawned objects from a group of objects with the same entry or ID, while leaving identical objects in other gps locations unchanged (when there are multiple spawns of the same entry / ID, but with different GUIDs).

About your SQL codestyle; TC uses the back tick character ` before and after column names, like this:
```sql
-- Respawn timer for quest gameobject Flying Machine Engine
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `guid` = 61208;
```

**Comment by Tauriella** [comment]
Sorry @tkrokli it was my misstak this patch is testet and works fine.

**Comment by tkrokli** [comment]
OK, I just wanted you to know that if there is only 1 object (in this case, Flying Machine Engine), it is usually better to use ID (`id`) over GUID (`guid`) in the SQL - see Aokromes' reply in the other issue.

Anyway, I am interested to hear about your source for this change, where you have found that the timer should be as short as 2 seconds. I thought that only books in the libraries should respawn as quick as 2 seconds after being looted. I know that the `gameobjects` table does not list any `VerifiedBuild` number value, but it would be nice to know where in WotLK you have found this info. I also noticed your dialogue with Rushor in another issue, where the respawn time was mentioned as quite bad (4-5 minutes) before Cataclysm or Mists of Pandaria changed it to very short. It can be difficult to get hold of this exact information in sniffs, but do you have any other proof, like an old video?

**Comment by Tauriella** [comment]
Thanks for the info @tkrokli and @Aokromes 
Sorry i can only proof on the last client on liveserver, but only then if the object or quest exist.

**Comment by tkrokli** [comment]
The difference is that the spawn timers could have been changed in Cataclysm, Mists of Pandaria or Warlords of Draenor, so you don't see what it used to be in Wrath of the Lich King (3.3.5a). For proof of what it used to be in 3.3.5a, you need to check Patch Notes, find either old sniff, 6 years old YouTube video or forum comments from 2010 (or older) to support your claim about shorter spawn timers

**Comment by tkrokli** [comment]
OK, so you got some of your changes added to the TDB. Notice that the `id` value was used: :)
```sql
--
UPDATE `gameobject` SET `spawntimesecs` = 10 WHERE `id` IN (148499, 178084, 178085, 176785);
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (190447, 759);
```
I guess it is a good thing I am not one of those who get to decide what goes into the source. The TC developer team is usually better than me at deciding which parts in our suggestions are correct to use.
