### ISSUE TITLE
[3.3.5]Core/spell:boss_fathomlord_karathress totem

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#16982]
Description:Boss cast spell
Current behaviou: Totem does not attack target
Expected behaviour:

1.BOSS cast Totem (http://www.wowhead.com/spell=38236)
2.Totem does not attack target
3.totem is SAi 

Branch(es) :335/6x
TC hash/commit:https://github.com/TrinityCore/TrinityCore/commit/e38e1c0c549c6b53993972f0d94a584cb3c46eeb
TDB version:TDB61
Operating system:windows
patch:NO

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp#L715

**Comment by w5860363** [comment]
ID 22091 Spitfire totem SAi not attack target

ID 22487 ID 22486 NOT SAI

**Comment by w5860363** [comment]
-- Greater Earthbind Totem (22104)
UPDATE creature_template SET spell1=6474, AIName='', ScriptName='' WHERE entry=22486;
DELETE FROM smart_scripts WHERE entryorguid=22486 AND source_type=0;

-- Greater Poison Cleansing Totem (22487)
UPDATE creature_template SET spell1=8172, AIName='', ScriptName='' WHERE entry=22487;
DELETE FROM smart_scripts WHERE entryorguid=22487 AND source_type=0;

**Comment by Aokromes** [comment]
That won't work. spell? fields on creature_template is for mind controled mobs.

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.

**Comment by offl** [comment]
#31136
