### ISSUE TITLE
libprotobuf

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#16981]
**Description**: libprotobuf error

**Current behaviour**: After reach the character list, the worldserver display some errors about protobuf.
This only happends on Linux and Dynamic linking

**Expected behaviour**: 

**Steps to reproduce the problem**:
1. Compile the worldserver with dynamic linking (not the bnet server to see errors on worldserver)
2. Compile the bnetserver with static linking
2. Check worldserver console after reaching the characters list

**Branch(es)**: 6x

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/020a09190157235a28fdaf36e42cd263b22295de

**TDB version**: 6.04

**Operating system**: Debian

**Linking model**: dynamic

https://gist.github.com/Nelidon/c9cf2539ae5ea1f79d4e0984a9bc7e14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
@Naios

**Comment by Naios** [comment]
Could you try out this commit please, https://github.com/Naios/TrinityCore/commit/62dc20ad2c57012604988aaaa528da5188eb71c6 ?

```sh
git remote add naios https://github.com/Naios/TrinityCore.git
git fetch naios
git cherry-pick 62dc20ad2c57012
```

**Comment by Nelidon** [comment]
Your commit fix the issue :)
