### ISSUE TITLE
[3.3.5] Quest: Mystery of the Infinite (12470)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#16988]
3.3.5 476eb19

[Quest: Mystery of the Infinite](http://www.wowhead.com/quest=12470/mystery-of-the-infinite)

Multiple issues:
- [Future You](http://www.wowhead.com/npc=27899/future-you) keeps despawning and then respawning every time it exits combat.
- [Future You](http://www.wowhead.com/npc=27899/future-you) is extremely weak, causing the quest to be very difficult to complete.

**Comment by dr-j** [comment]
I did not script this however confirming about npc been weak but about the despawning you have to hug future you during the quest until you complete quest so npc does not suddenly disappear.
