### ISSUE TITLE
Mimiron - Leviathan MKII doesn't spawn with correct amount of health

### ISSUE THREAD

**Issue by Bullfface** [TrinityCore/TrinityCore#16983]
Leviathan MK II in both phase 1 and 4 of Mimiron encounter has incorrect health

Leviathan MKII spawns with 4,183,000 hp on 10 man

It should spawn with 1,742,400 hp. The SQL data base has current health set to 1742400 but he doesn't spawn with that number

Go to Mimiron encounter in Ulduar and begin fight normally to reproduce.

3.3.5

Commit hash:	4afea55b2c6035a986162a8d800a57fb1ae4cf98
Parent(s):	5f3262ff19

Current TDB

Win 7

**Comment by Aokromes** [comment]
I vote you enabled hard mode.

**Comment by Bullfface** [comment]
When HM is activated his health goes to 5,229,00 health and the emergency aura buff applies correctly.
When I spawn him outside of ulduar as well it still spawns with incorrect health

**Comment by msoky** [comment]
try if it helps update creature_template SET exp=-1 (with that - mark)

**Comment by Bullfface** [comment]
That corrected the issue! Thanks! Why does it affect it like that?

**Comment by msoky** [comment]
I dont know :D

**Comment by Bullfface** [comment]
Well I guess that's theres beauty in the mystery haha

**Comment by DDuarte** [comment]
Please, don't close the issue after a "fix" being posted. It will be closed when the fix gets pushed to the repo.

**Comment by msoky** [comment]
dont close this..

**Comment by Bullfface** [comment]
Sounds good, will note in the future.
