### ISSUE TITLE
GO Ammo Crate respawn fix

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#16990]
```sql
-- Wrong respawntimer for Quest GameObjects
-- Ammo Crate
UPDATE gameobject SET spawntimesecs = 10 WHERE guid = 10663;
```
http://www.wowhead.com/object=176785/ammo-crate

**Branch(es)**: 335

**TC hash/commit**:
TrinityCore rev. e38e1c0c549c 2016-04-15 01:56:05 +0200 (335 branch)
**TDB version**:
.61
**Operating system**:
Win.7

**Comment by Rushor** [comment]
do you have a source for these respawntimes?

**Comment by Tauriella** [comment]
No, unfortunately not but i checked the quests on liveserver if it still exists
I think 15min respawntime is very bad for a 5man Group.

**Comment by Rushor** [comment]
well i only remember http://us.battle.net/wow/en/forum/topic/1252365392

so most quests are intended to me a pain in wotlk ^^

**Comment by Tauriella** [comment]
Stupid Bli...  but they have fixed this issue :)
