### ISSUE TITLE
[6.x] Core/Mechanic: libprotobuf

### ISSUE THREAD

**Issue by Nelidon** [TrinityCore/TrinityCore#16993]
**Description**: Same as https://github.com/TrinityCore/TrinityCore/issues/16981

**Current behaviour**: Same as https://github.com/TrinityCore/TrinityCore/issues/16981

**Expected behaviour**: 

**Steps to reproduce the problem**:

**Branch(es)**: 6x  

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/25e1ecb33de8bfaea7fa7fa8c7f3da3074ea89e0

**TDB version**:  6.04

**Operating system**:  Debian

**Linking model**: dynamic

https://gist.github.com/Nelidon/8bc2bf9aa0eab5dc0fa54e823221ff5c

@Naios

**Comment by Naios** [comment]
Could you test out the following commit please? I guess that will fix your issues: https://github.com/Naios/TrinityCore/commit/d17097c5ebbdccdafcdf5dfaf7512c964f3ce2bf

```patch
diff --git a/dep/protobuf/CMakeLists.txt b/dep/protobuf/CMakeLists.txt
index 5ea6a4e..2e911f9 100644
--- a/dep/protobuf/CMakeLists.txt
+++ b/dep/protobuf/CMakeLists.txt
@@ -57,7 +57,7 @@ else()
   )
 endif()
 
-add_library(protobuf STATIC ${protobuf_STAT_SRCS})
+add_library(protobuf ${protobuf_STAT_SRCS})
 
 target_include_directories(protobuf
   PUBLIC
@@ -69,7 +69,27 @@ target_link_libraries(protobuf
   PUBLIC
     threads)
 
+if (BUILD_SHARED_LIBS)
+  target_compile_definitions(protobuf
+    PRIVATE
+      -DLIBPROTOBUF_EXPORTS
+    PUBLIC
+      -DPROTOBUF_USE_DLLS)
+endif()
+
 set_target_properties(protobuf
-    PROPERTIES
-      FOLDER
-        "dep")
+  PROPERTIES
+    FOLDER
+      "dep")
+
+if (BUILD_SHARED_LIBS)
+  if (UNIX)
+    install(TARGETS protobuf
+      LIBRARY
+        DESTINATION lib)
+  elseif (WIN32)
+    install(TARGETS protobuf
+      RUNTIME
+        DESTINATION "${CMAKE_INSTALL_PREFIX}")
+  endif()
+endif()
```
