### ISSUE TITLE
[6.x] Legendary Cloak Value issue

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#17001]
**Description**: The Legendary Cloak is always active and the value in the green field is wrong

**Current behaviour**: Tell us what happens
Read the description and see the screenshot

**Expected behaviour**: Tell us what should happen instead
Cloak should have correct parameters

**Steps to reproduce the problem**:

1. .add a legendary cloak from Pandaria
2.  Wear it
3.  Do damage and see the item tooltip

![wowscrnshot_041816_125100](https://cloud.githubusercontent.com/assets/16773213/14601801/98800fc2-0564-11e6-943e-efd1ee63e68e.jpg)

**Branch(es)**: 335/6x  
6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/e3a583646edd736176e5b4614b69fa794bc83c5b

**TDB version**:  6.04

**Operating system**:  Windows 10

**Linking model**: static/dynamic
Both

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Shauren** [comment]
Issue extends to all equippable effects with proc chance scaling with haste
