### ISSUE TITLE
[3.3.5][Icecrown Citadel] Core/Gameobject: Sindragosa Tombs

### ISSUE THREAD

**Issue by peycho** [TrinityCore/TrinityCore#17000]
Sindragosa Tombs (ice bloks) can not be target/hit by players due to LOS.

**Expected behaviour**: Tombs should be target and damaged by players so the frozen players can be released.

**Steps to reproduce the problem**:

1. Create raid
2. Go to ICC / Sindragosa
3. Try to finish the boss event.

**Branch(es)**: 335

**TC hash/commit**: 2f8493952214f328a6dfebd93414ee721a3fff3a  

**TDB version**:  TDB 335.61 - 2016/04/11

**Operating system**:  Linux Ubuntu Server 14.04 / 64

**Linking model**: static/dynamic, not sure what this is.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
Linking model (static or dynamic) is what you see in cmake if you update your core to the current Head commit (the commits introduced 1 day and later, after your commit hash). When you update your cloned repository to the current source, make sure you empty your build directory before building the files again with cmake. Then you will see the values for static or dynamic listed in the cmake output.

**Comment by Rushor** [comment]
duplicate from https://github.com/TrinityCore/TrinityCore/issues/6541
test https://github.com/TrinityCore/TrinityCore/pull/15807
