### ISSUE TITLE
[3.3.5] Spellfacing - creatures do not update target

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#17016]
**Description**: After a creature casts a spell, which normally is inactive/non-attacking, Creature::Attack is never called and thus the creature target never gets updated (cleared)

**Current behaviour**: Creature gets stuck target after casting a spell

**Expected behaviour**: Creature should clear the target if it hasn't a victim.

**Steps to reproduce the problem**: You can reproduce this enabling "Show target of target" on the interface options, for example in the mages on Dalaran as opposing faction, either way...

1. Target non-hostile target (e.g. `.go creature id  7564`)
2. Issue command `.cast back 11`, this will make the npc cast "Frostbolt of Ages" at you
3. Notice how the NPC doesn't reaquire target after the delay time, and it's target keeps stuck at you

**Branch(es)**: 335

**TC hash/commit**:  02d7df6aa4352d7112073898826ef195bedb6cff

**TDB version**:  335.61

**Operating system**:  Win 10 x64

**Linking model**: static

**Comment by ccrs** [comment]
confirm 02d7df6aa4352d7112073898826ef195bedb6cff

This is partially covered in combat by a loop in UpdateVictim which makes the creature use AttackStart on every update tick.
