### ISSUE TITLE
3.3.5/core:spell Stone script Missing

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#17013]
Description:spell Mana is not valid
Current behaviou: 
Expected behaviour:Effect of item effect

1.Alchemist stone http://www.wowhead.com/item=13503
2.Missing in the 3.3.5 branch.and The mana effect is not valid in the 6x branch

Branch(es) :335/6x
TC hash/commit: https://github.com/TrinityCore/TrinityCore/commit/02d7df6aa4352d7112073898826ef195bedb6cff
TDB version:TDB61
Operating system:windows
patch:NO

Endless Mana Potion ID 43570: Doesn't work
http://www.wowhead.com/item=43570
Endless Healing Potion ID 43569: Works
http://www.wowhead.com/item=43569
Runic Mana Potion ID 33448: Doesn't work
http://www.wowhead.com/item=33448
Runic Healing Potion ID 33447: Doesn't work
http://www.wowhead.com/item=33447/runic-healing-potion

https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Spells/spell_generic.cpp#L176
3.3.5 branch Missing And only to the health effect

**Comment by Rushor** [comment]
search for https://github.com/TrinityCore/TrinityCore/commit/b3e9ca7a6a4ea97e1b06fda70ef759f822bd4fde#diff-4522eeffcbc961602e86620011a2d579L6525 in the 3.3.5 branch

**Comment by Aokromes** [comment]
43570, 33447, 33448 works for me on  b0f9a998e187

**Comment by Rushor** [comment]
Issue number: 1337 (30.05.2016 - 10:41 am) gg :D
