### ISSUE TITLE
[6.x]Raid Difficulty

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#17026]
**Description**:
The difference between 10 and 25 Player Ids should no longer be present. When you kill the first boss in 10 Player Raid and go after this in the 25 Player Raid, you don't have a new ID (25er ID) rather you have always your one ID with the killed Boss from 10er. Like 10er and 25er are the same ID

Its from https://gitlab.com/trinitycore/TrinityCore_434/issues/60 
but it think that problem are still present in 6.x. but here come the flex raid and the raid browser ids Additionally.

**Branch(es)**: 335/6x  
6.x

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/bc106abb07dc0afc69c2a9238267081464c05254

**Comment by gonzo1247** [comment]
It's some days here that i writte this Issue here.
I don't know how this works, but what is, when its define two new Difficultys? Like RAID_DIFFICULT_10_25 and RAID_DIFFICULTY_10_25_HC and check in create instance id if the expansion from the map is 2 (WotlK) or higher and set, if they a 10 or 25er Raud from Wotlk/Cata/Mop, to this difficulty? 
But i think, this is not good working and need more reprogramming of the instance id system?

**Comment by Aokromes** [comment]
#2374

**Comment by LuigiElleBalotta** [comment]
https://github.com/SkyMist/Core/commit/104f94b497ab6cff81e7057bd3ec67be39821e66

https://github.com/SkyMist/Core/commit/d4054a685ab28d6e35f865a6d6e2dbdc3fa818b8

this should fix it.
