### ISSUE TITLE
[6.x][Quest/Spell] Corruption quest not working

### ISSUE THREAD

**Issue by bloodyshade** [TrinityCore/TrinityCore#17022]
**Description**:
When trying to complete the corruption quest, it does not recognize the spell usage and the quest doesn't progress.

**Current behavior**:
Casting corruption on the training dummies does not increase the usage counter for the [corruption](http://www.wowhead.com/quest=10073/corruption) quest.

**Expected behavior**:
The spell casting should increase the usage counter for the corruption quest, allowing for quest completion.

**Steps to reproduce the problem**:
1. Create a blood elf warlock and get level 3
2. Accept the corruption quest
3. Attack the dummies with corruption

**Branch(es)**: 335/6x  
6x

**TC hash/commit**:  
TrinityCore rev. 4fbe38063923 2016-04-23 19:35:49 +0200 (6.x branch) (Win64, Release)

**TDB version**:  
TDB 6.04

**Operating system**:  
Windows 7 Ultimate SP1 64bits
(Client version 6.2.4 (21463) x64, everything was extracted from it freshly)

**Linking model**: static/dynamic
dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
#15814
