### ISSUE TITLE
Core: Combat bug

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17027]
This steps will reproduce a combat bug:

Step1: Find 2 npcs.
Step2: Aggro this 2 npcs and runaway until one of them enter on evade mode to return to home pos.
Step3: Cast an instant spell on the npc that evades (during the evade).
Step4: Kill the second npc.
Step5: You will be stuck in combat until you kill the npc that evades.

TrinityCore rev. dc3327f9c5f8

**Comment by MrSmite** [comment]
It seems like the evade system is broken, there are also these two issues dealing with mobs and evade:

https://github.com/TrinityCore/TrinityCore/issues/4943 - Mobs evade and follow player forever
https://github.com/TrinityCore/TrinityCore/issues/1340 - Mobs evade when entering vehicle in combat

**Comment by ryoting** [comment]
i found It is prone to get stuck incombat,the lasted rev .

**Comment by Palabola** [comment]
From first virew, I guess we should implement here and other Combat Stop:

HomeMovementGenerator.cpp

void HomeMovementGenerator<Creature>::DoFinalize(Creature* owner)
{
    if (arrived)
    {
        owner->ClearUnitState(UNIT_STATE_EVADE);
        // Remove Combat here missing?!
        owner->SetWalk(true);
        owner->LoadCreaturesAddon();
        owner->AI()->JustReachedHome();
    }
}

**Comment by Rushor** [comment]
you mean: owner->CombatStop(); ?

**Comment by Palabola** [comment]
Yes

**Comment by tkrokli** [comment]
@Palabola : pro tip; if you want to highlight the text in your diff, you can use ```diff at the code block start.
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by Rushor** [comment]
i wonder if there is any situation where the combat should not be stopped if the creature uses the evade mode

Maybe it will cause issues if a creature uses GetMotionMaster()->MoveTargetHome(); ?

**Comment by Palabola** [comment]
You can check easely creature stop combat when he got the Evade state with a simple
.debug hostil (command)
Then you cast on it your cast result become "Evade" but the creature appear into your Threat list and since there is no other **Combatstop** in the core he will stay you in combat forever.

That why there is 2 solution:
1. Prevent any creatures in Evadestate can get combat or appear on a Threatlist.
2. Be sure when Creature reach his home position and remove Evatedstate from itself also remove any combat from himself.

I had no time yet try out this 2 options, but I'm sure the 2nd will solve the problem without broke anything else.

**Comment by Rushor** [comment]
going to test the 2nd one now, i will give feedback to it in the next week :)

**Comment by Rushor** [comment]
k applied both fixes:

```diff
diff --git a/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp b/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
index 626742a..fcb5aba 100644
--- a/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
+++ b/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
@@ -33,6 +33,7 @@ void HomeMovementGenerator<Creature>::DoFinalize(Creature* owner)
     if (arrived)
     {
         owner->ClearUnitState(UNIT_STATE_EVADE);
+        owner->CombatStop();
         owner->SetWalk(true);
         owner->LoadCreaturesAddon();
         owner->AI()->JustReachedHome();

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 26d14c8..074efba 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -12645,7 +12645,7 @@ void Unit::SetInCombatWith(Unit* enemy)
 
 void Unit::CombatStart(Unit* target, bool initialAggro)
 {
-    if (initialAggro)
+    if (initialAggro && !target->HasUnitState(UNIT_STATE_EVADE))
     {
         if (!target->IsStandState())
             target->SetStandState(UNIT_STAND_STATE_STAND);
```

sadly it didn't changed anything - you will always keep in combat

**Comment by sirikfoll** [comment]
Code below can properly fix the bug described in this issue:
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 1ce1c43..6168248 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4662,7 +4662,7 @@ void Spell::HandleThreatSpells()
         // for negative spells threat gets distributed among affected targets
         else
         {
-            if (!target->CanHaveThreatList())
+            if (!target->CanHaveThreatList() || target->HasUnitState(UNIT_STATE_EVADE))
                 continue;
 
             target->AddThreat(m_caster, threatToAdd, m_spellInfo->GetSchoolMask(), m_spellInfo);

**Comment by Rushor** [comment]
^
```c++
if (CanHaveThreatList() || HasUnitState(UNIT_STATE_EVADE))
```

in Unit::AddThreat

**Comment by sirikfoll** [comment]
@Rushor, in Unit::AddThreat needs to be
```cpp
if (CanHaveThreatList() && !HasUnitState(UNIT_STATE_EVADE))

**Comment by Rushor** [comment]
uuh yes - thank you

**Comment by Goatform** [comment]
So final patch should look like this, right?

```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 1ce1c43..6168248 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4662,7 +4662,7 @@ void Spell::HandleThreatSpells()
         // for negative spells threat gets distributed among affected targets
         else
         {
-            if (!target->CanHaveThreatList())
+            if (!target->CanHaveThreatList() || target->HasUnitState(UNIT_STATE_EVADE))
                 continue;

             target->AddThreat(m_caster, threatToAdd, m_spellInfo->GetSchoolMask(), m_spellInfo);

diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 1ce1c43..6168248 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -12648,7 +12648,7 @@ float Unit::ApplyTotalThreatModifier(float fThreat, SpellSchoolMask schoolMask)
 void Unit::AddThreat(Unit* victim, float fThreat, SpellSchoolMask schoolMask, SpellInfo const* threatSpell)
 {
     // Only mobs can manage threat lists
-    if (CanHaveThreatList())
+    if (CanHaveThreatList() && !HasUnitState(UNIT_STATE_EVADE))
         m_ThreatManager.addThreat(victim, fThreat, schoolMask, threatSpell);
 }

**Comment by sirikfoll** [comment]
only the second part is enough ^^

**Comment by Aokromes** [comment]
If any fix here is valid, plz open a PR.

**Comment by jackpoz** [comment]
Could some users from this discussion test https://github.com/TrinityCore/TrinityCore/pull/17186 and report there that the issue has been fixed ? The PR looks good

**Comment by tkrokli** [comment]
The PR is merged, it is enough to check the results in straight 3.3.5 source (https://github.com/TrinityCore/TrinityCore/commit/adf68a9 and newer).
