### ISSUE TITLE
[3.3.5a] Starter weapons unable to be used with weapon-required abilities

### ISSUE THREAD

**Issue by serfma** [TrinityCore/TrinityCore#17030]
**Description**: Majority of the starter weapons for all race/class combinations are unable to be used with abilities that require a melee/ranged weapon. Along with this, their icons when unequipped are a red question mark. (if they're equipped, they appear normal.) They can be used with auto attacking. 

I've also noticed the starter armor has the red question mark issue, but I chose not to list all them as it's not really an issue.

List of items:
- [Apprentice's Staff](http://www.wowhead.com/item=20978)
- [Battleworn Claymore](http://www.wowhead.com/item=23346)
- [Battleworn Hammer](http://www.wowhead.com/item=2361/battleworn-hammer)
- [Bent Staff](http://www.wowhead.com/item=35)
- [Crude Throwing Axe](http://www.wowhead.com/item=25861)
- [Handcrafted Staff](http://www.wowhead.com/item=3661)
- [Light Throwing Knife](http://www.wowhead.com/item=28979)
- [Old Blunderbuss](http://www.wowhead.com/item=2508)
- [Sharp Dagger](http://www.wowhead.com/item=20982)
- [Sharp Dirk](http://www.wowhead.com/item=50057)
- [Worn Battleaxe](http://www.wowhead.com/item=12282/worn-battleaxe)
- [Worn Dagger](http://www.wowhead.com/item=2092/worn-dagger)
- [Worn Dirk](http://www.wowhead.com/item=50055/worn-dirk)
- [Worn Greatsword](http://www.wowhead.com/item=49778)
- [Worn Mace](http://www.wowhead.com/item=36)
- [Worn Shortbow](http://www.wowhead.com/item=2504/worn-shortbow)
- [Worn Wooden Shield](http://www.wowhead.com/item=2362)
- [Weathered Crossbow](http://www.wowhead.com/item=23347)

**Current behaviour**: Starter weapons cannot be used with weapon-required abilities. e.g. Rogues cannot cast Sinister Strike due to their starter weapon(s) not being seen as a melee weapon, though they can auto attack with the weapon(s).

**Expected behaviour**: Starter weapons being seen as valid weapons that can be used in combination with weapon-required abilities, such as Sinister Strike for Rogues.

**Steps to reproduce the problem**:
1. Create any starter character such as a Warrior
2. Attempt to cast an ability that requires a melee weapon (Heroic Strike as Warrior, Sinister Strike as Rogue, etc.)

**Branch(es)**: 3.3.5a

**TC hash/commit**: hash 02d7df6aa435

**TDB version**: 335.61

**Operating system**: Windows 10, 64-bit

**Comment by Aokromes** [comment]
You are using modified client/database/broken client.

**Comment by serfma** [comment]
@Aokromes Database is brand new so I am going to go with the client. Is there any tell for in the future whether it's client-related?

**Comment by Aokromes** [comment]
The red ?

**Comment by serfma** [comment]
Ah ok. I attempted to clear cache and copy everything besides id/name from another item, thinking that if it didn't fix it wouldn't be client. My bad, sorry for the waste of time, and thanks! :)
