### ISSUE TITLE
Character Disable Mask Incomplete

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#17033]
**Description**:
```quote
CharacterCreating.Disabled = 0

#
#    CharacterCreating.Disabled.RaceMask
#        Description: Mask of races which cannot be created by players.
#        Example:     1536 - (1024 + 512, Blood Elf and Draenei races are disabled)
#        Default:     0    - (Enabled, All races are allowed)
#                     1    - (Disabled, Human)
#                     2    - (Disabled, Orc)
#                     4    - (Disabled, Dwarf)
#                     8    - (Disabled, Night Elf)
#                     16   - (Disabled, Undead)
#                     32   - (Disabled, Tauren)
#                     64   - (Disabled, Gnome)
#                     128  - (Disabled, Troll)
#                     512  - (Disabled, Blood Elf)
#                     1024 - (Disabled, Draenei)

CharacterCreating.Disabled.RaceMask = 0

#
#    CharacterCreating.Disabled.ClassMask
#        Description: Mask of classes which cannot be created by players.
#        Example:     288 - (32 + 256, Death Knight and Warlock classes are disabled)
#        Default:     0    - (Enabled, All classes are allowed)
#                     1    - (Disabled, Warrior)
#                     2    - (Disabled, Paladin)
#                     4    - (Disabled, Hunter)
#                     8    - (Disabled, Rogue)
#                     16   - (Disabled, Undead)
#                     32   - (Disabled, Death Knight)
#                     64   - (Disabled, Shaman)
#                     128  - (Disabled, Mage)
#                     256  - (Disabled, Warlock)
#                     1024 - (Disabled, Druid)

CharacterCreating.Disabled.ClassMask = 0
```

**Current behaviour**: Tell us what happens
Incomplete Character Disabling mask!

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Check the Config file.
2. 
3. 

**Branch(es)**: 335/6x  
3.3.5A
**TC hash/commit**:  
ebafa2fdeaf4544b5e62c9fab7c281d54f7aa139
**TDB version**:  

**Operating system**:  
Linux Ubuntu 16.04
**Linking model**: static/dynamic
???

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
What's the supposed issue? i can't see it.

**Comment by Shoxxo** [comment]
The issue is, you submitted an incompleted disabling mask what should be completed. Half work are okay for trinity?

**Comment by Aokromes** [comment]
If you point me what's missing.... because i cannot see it.

**Comment by Shoxxo** [comment]
#    CharacterCreating.Disabled.RaceMask
#                     128  - (Disabled, Troll)
After it comes 256 what is 256 ? Priest !?

#    CharacterCreating.Disabled.ClassMask
#                     256  - (Disabled, Warlock)
After it comes 512 what is 512 ? if i am an noob i don't know it...

**Comment by Aokromes** [comment]
https://trinitycore.atlassian.net/wiki/display/tc/ChrRaces
https://trinitycore.atlassian.net/wiki/display/tc/ChrClasses
You can blame blizzard.
