### ISSUE TITLE
[3.3.5] Core/Spell: Seal of Vengeance does not proc before 5 stacks

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#17034]
**Description**:
FIRST, i know that the tool description says something different, but please read the whole issue before you add any comments.

**Current behaviour**: Tell us what happens
Seal of Vengeance only proccs at 5 stacks.

**Expected behaviour**: Tell us what should happen instead
**The seal procs will begin triggering from auto-attacks once you have a debuff stack of any size, and strikes will always trigger a seal proc (but never a DoT application). The table below shows the damage of the proc per DoT application**"

[table]Stack Number|% of Weapon Damage|% with SotP

0|0%|0%

1|6.6%|7.6%

2|13.2%|15.2%

3|19.8%|22.8%

4|26.4%|30.4%

5|33%|38%[/table]

When an auto-attack lands (does not dodge/parry/miss) that can proc a seal the of the following things happen independently of each other (see 2 roll system).

1) A "hidden strike" which uses melee combat mechanics occurs. If it lands it refreshes/stacks SoV DoT. Only white swings can trigger a refresh or stack. (This hidden strike mechanic can also proc things like berserking..)

\\wat the fack is going on here w/ hotfixes, update this later

2) A weapon damage based proc will occur if you used a special (CS/DS/judge) or if you have a 5 stack (from auto attacks). This attack can not be avoided.

Remember #2 happens regardless of #1 landing, it just requires the initial attack (autos, cs, etc) to land.

DoT functions and mechanics:

DoT application is melee hit/exp based. (Cannot be resisted like a spell, but can be dodged or parried)

DoT will still be applied even if your white swing is fully absorbed (in a PvP situation).

DoT is only applied via auto-attacks (whites).

DoT ticks always hit.

DoT ticks are reduced by partial resist on skull mobs, but not by players (it is holy damage).

DoT gains from CoE (and equivalents).

Seal Proc functions and mechanics:

Proc (after 5 stack/triggered from specials) can NOT be dodged or parried, it occurs as long as your initial white/strike lands.

Proc suffers from partial resists (it's holy damage).

Proc gains from CoE (and equivalents).

Proc can crit. (like SoB did)

With the release of 3.2.2, SoV stack interaction should now be functioning correctly and the damage you get from procs/judgements is solely based on your stack count.

**SOURCE:** http://forums.elitistjerks.com/forums/topic/68239-retribution-updated-for-33/
http://www.worldoflogs.com/reports/rnyhwb053jp6bxqn/xe/?s=2567&e=2801&x=fullType+%3D+SWING_DAMAGE%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Seal+of+Vengeance%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Holy+Vengeance%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Crusader+Strike%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Divine+Storm%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Manifest+Anger%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+spell+%3D+%22Holy+Vengeance%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0AOR+type+%3D+TYPE_DAMAGE%0D%0AAND+spell+%3D+%22Judgement+of+Vengeance%22%0D%0AAND+sourceName+%3D+%22Morgeine%22%0D%0A

**Branch(es)**: 335/6x  
3.3.5

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/6392887f2b903d052e778711c30431b738e5edd1

**TDB version**:  
TDB version:TDB61
**Operating system**:  
Windows 10
**Linking model**: static/dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ariel-** [comment]
Archive Link as EJ doesn't exist anymore :(
http://web.archive.org/web/20110309092008/http://elitistjerks.com/f47/t49865-paladin_retribution_pve/

Will take a look at this when porting dummy procs

**Comment by ariel-** [comment]
```
Evel's melee swing hits Heroic Training Dummy for 1931 Physical.
Heroic Training Dummy is afflicted by Evel's Holy Vengeance.
Evel's Crusader Strike hits Heroic Training Dummy for 1961 Physical.
Evel's Seal of Vengeance hits Heroic Training Dummy for 618 Holy.(Critical)
Heroic Training Dummy suffers 248 Holy damage from Evel's Holy Vengeance.
Evel's Paragon is refreshed on Evel.
Evel's melee swing hits Heroic Training Dummy for 2357 Physical.
Heroic Training Dummy is afflicted by Evel's Holy Vengeance (2).
Heroic Training Dummy suffers 685 Holy damage from Evel's Holy Vengeance.
Evel's Crusader Strike hits Heroic Training Dummy for 2175 Physical.
Evel's Seal of Vengeance hits Heroic Training Dummy for 1470 Holy.(Critical)
Evel's melee swing hits Heroic Training Dummy for 4792 Physical.(Critical)
Heroic Training Dummy is afflicted by Evel's Holy Vengeance (3).
Heroic Training Dummy suffers 1036 Holy damage from Evel's Holy Vengeance.
Evel's melee swing hits Heroic Training Dummy for 2566 Physical.
Heroic Training Dummy is afflicted by Evel's Holy Vengeance (4).
Evel's Crusader Strike hits Heroic Training Dummy for 4484 Physical.(Critical)
Evel's Seal of Vengeance hits Heroic Training Dummy for 1351 Holy.
Heroic Training Dummy suffers 1397 Holy damage from Evel's Holy Vengeance.
```
