### ISSUE TITLE
a problem of saurfang

### ISSUE THREAD

**Issue by ryoting** [TrinityCore/TrinityCore#17036]
**Description**:
I use a account of gamelevel=3, and close gm mode,then into 10man or 10man hero or 25man or 25man hero of ICC
![qq 20160425175933](https://cloud.githubusercontent.com/assets/12771834/14780850/80b103f8-0b11-11e6-8130-c97c926dd4f1.png)

 , when come to saurfang,i can see the name of Martyr Stalker(Reputation) ,and it attack me always,Why can see it ?it use for what? player account can see it sometimes too.
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 335/6x  
335
**TC hash/commit**:  
9e371b7
**TDB version**:  
61
**Operating system**:  
WIN7 64bit
**Linking model**: static/dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
Very likely missing force model on summon.

**Comment by Keader** [comment]
Missing trigger flag maybe

**Comment by Aokromes** [comment]
I think it's trigger creature summoned by some spell and needs c++ to force proper model.

**Comment by Keader** [comment]
only add extra flag (128) in this npc dont solve?

**Comment by Shauren** [comment]
Nah, its a permanent spawn @Aokromes

**Comment by Demonid** [comment]
Isn't he still going to attack and get killed by players by AoE Spells?
