### ISSUE TITLE
[3.3.5] Quest: An Embarassing Incident (12699)

### ISSUE THREAD

**Issue by Sakuragi85** [TrinityCore/TrinityCore#17039]
**Description**: http://www.wowhead.com/quest=12699/an-embarrassing-incident

**Current behaviour**: Vic's Keys is supposed to be in of the muds but doesn't drop even though it has a 100% dropchance in the database

**Expected behaviour**: The Key is supposed to be in of the muds

**Steps to reproduce the problem**:

1. swim down river's heart in sholazar basin
2. open up some raised mud
3. there won't be any "Vic's Keys" inside

**Branch(es)**: 335 

**TC hash/commit**:  79df25e

**TDB version**:  TDB335.61

**Operating system**:  Windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
Why did you close this issue? Maybe you clicked the wrong button when you saved your text?

TrinityCore rev. 329006d31095 2016-04-25 23:26:04 +0100 (3.3.5 branch) (Win64, Release)
Issue confirmed. The drop rate is no longer 100% when player has accepted the quest. I just tested this with a level 77 male blood elf in full Gronnstalker gear (to bring the HP up a bit to defend against beasts) and the drop rate is not even 10%. Almost all the visible spawns of the Raised Mud gameobjects are 190779 and not 190778. Only one gobject is both 190778 and 190779, the one hidden inside the hollow waterlogged tree trunk. I still can't access gobject 190778, though, I think I'm only getting gobject 190779.

**Comment by Aokromes** [comment]
Oh, not all muds have the key:

http://i.imgur.com/rtcnolo.png

**Comment by tkrokli** [comment]
Yes, I can see that from the comments http://www.wowhead.com/item=39264/vics-keys#comments , but I think it can be difficult to get the item even if you locate the correct pile, as mentioned in http://www.wowhead.com/item=39264/vics-keys#comments:id=950685
I will continue testing on rev. 61999b125a55 2016-04-26 00:31:56 +0100 (3.3.5 branch) (Win64, Release), both with and without any gameobjects 190779 present in that lake pond, to find out more.
