### ISSUE TITLE
[6.x] Unable to build project files with cmake 3.5.0 on Unix

### ISSUE THREAD

**Issue by Epicurus4** [TrinityCore/TrinityCore#17031]
**Description**: 
Can not build project files on Unix with cmake 3.5.0. Using the Clang compiler, version 3.4.

**Current behaviour**:
CMake Error at dep/protobuf/CMakeLists.txt:63 (string):
  string sub-command REPLACE requires at least four arguments.

**Steps to reproduce the problem**:

1. Install cmake 3.5.0
2. Install Clang 3.4
3. Build project files

**Branch(es)**: 6x  

**TC hash/commit**:  913d1124491bf0561f8e9938070f22911c1ca42b

**TDB version**:  6.04

**Operating system**: Ubuntu 14.04

**Linking model**: static

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Epicurus4** [comment]
Summons @Naios

**Comment by Aokromes** [comment]
Cannot confirm on ubuntu 16.04LTS.

**Comment by Epicurus4** [comment]
The Operating system is Ubuntu 14.04, and not 16.04

**Comment by Aokromes** [comment]
That's why i tell you to do do-release-upgrade.

**Comment by Epicurus4** [comment]
do-release-upgrade

I'm not sure what the context for this suggestion is.

**Comment by Aokromes** [comment]
because http://i.imgur.com/y5EOjuU.png

**Comment by Epicurus4** [comment]
Aye, but you and I are using different platforms. It's within the realm of reason for the results to be different.

**Comment by Aokromes** [comment]
It's not trinitycore issue. it's something on your side.

**Comment by Epicurus4** [comment]
The issue is definitely with TrinityCore. You can not reproduce it because you are using a different environment. A valid issue was prematurely closed.

**Comment by Epicurus4** [comment]
-fPIC -fvisibility=hidden c_flags were needed to get the source to build a static project.

**Comment by Naios** [comment]
The `-fPIC -fvisibility=hidden` c flags are definitly not needed to build the project statically as Aokromes said already. But you are right that you got a CMake error there since the string is not quoted there (I guess your compiler wasn't detected).

**Comment by Epicurus4** [comment]
Confirmed working on d44eb86

I wouldn't go so far to say that the environment is misconfigured, however. One should not make assumptions in programming such as "It will be impossible for these flags to be empty".

Nevertheless, excellent work on updating CMake support and implementing dynamic linking.
