### ISSUE TITLE
[3.3.5] Quest: The Earthen Oath (13005)

### ISSUE THREAD

**Issue by Sakuragi85** [TrinityCore/TrinityCore#17045]
**Description**: http://www.wowhead.com/quest=13005/the-earthen-oath

**Current behaviour**: Killing Iron Sentinels doesn't count towards the questlog. Iron Dward Assailants are sometimes also not counting. Probably depends whether the neutrals flag them.

**Branch(es)**: 335/

**TC hash/commit**:  b641d7b

**TDB version**:  335.61

**Comment by tkrokli** [comment]
There is also an issue posted in #15456 [**[3.3.5a] Temporary minions for "The Earthen Oath" (13005) do not have pet bar**](15456) for the same quest. Did you notice if that is still present in addition to your issue?

**Comment by Sakuragi85** [comment]
Yes I can confirm that the pet bar is still missing. Also I noticed that the kill also sometimes counts for Iron Sentinels. I have the suspiscion that one doesn't get the killcount if the minions flag him first which is very likely.

**Comment by Saben65** [comment]
Perhaps it matters who gets the Killing Blow? In the following issue it sounds like the damage from charge is being done by the mount, instead of the player, whereas the damage from thrust is done by the player.

https://github.com/TrinityCore/TrinityCore/issues/15534

**Comment by Saben65** [comment]
For the Iron Sentinel kill credit, this should fix it.

```SQL
UPDATE `creature_template` SET `KillCredit1`=30296 WHERE `entry`=29984;
```

http://www.wowhead.com/npc=30296/iron-sentinel-credit
http://www.wowhead.com/npc=29984/iron-sentinel

**Comment by Aokromes** [comment]
Edit creature_template without sniffs is hack.

**Comment by Saben65** [comment]
So add it SAI then?

**Comment by Treeston** [comment]
Add [`CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ`](https://github.com/TrinityCore/TrinityCore/pull/16257) to the target mobs and see if that fixes it.

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `creature_template` WHERE `entry`= 30270;
```
```
 entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name              subname  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName  MovementType  InhabitType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  flags_extra  ScriptName  VerifiedBuild
------  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ----------------  -------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  ------  ------------  -----------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  -----------  ----------  -------------
 30270                   0                   0                   0            0            0     26090     26664     26921     26913  Oathbound Warder                                  0        80        80       2     1770        0           1    1.14286       1       0          0            2000             2000             1              1           8           0         2048             0       0             0              0              0             0       7           0       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                     0            3            1               1             5              1               1                   1             0         144            1                     0            0                      12340
```
No ScriptName or AIName for this mob as of now. Unless sniff confirms that this NPC should have `flags_extra` other than 0, it would need to be handled in a core script. AFAIK, SAI does not handle `CREATURE_FLAG_EXTRA_*` yet.

**Comment by Treeston** [comment]
`FLAG_EXTRA` is not a sniff field.

**Comment by tkrokli** [comment]
Thank you for setting me straight. So this should be a valid test update to check if it solves the issue:
```sql
-- Add CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ to Iron Sentinel & Iron Dwarf Assailant
UPDATE `creature_template` SET `flags_extra` = 2097152 WHERE `entry` IN (29978,29984);
```
BTW, I completely misunderstood which NPCs would need this flag to test it in my previous comment, so I have edited that comment to match the actual information in the DB.

**Comment by Treeston** [comment]
The quest _targets_ are the mobs that need the flag. The flag determines whether 50% player damage is required to get credit for killing _that specific creature_.

**Comment by tkrokli** [comment]
Oh. Right, the Credit NPCs instead of the visual NPCs. Updated again. Sorry for being such a jerk.

**Comment by Kittnz** [comment]
is this a valid fix @tkrokli ?

**Comment by tkrokli** [comment]
It should fix the quest credit regarding the NPC entry **Iron Dwarf Assailant Credit** by setting the flag `CREATURE_FLAGS_EXTRA_NO_PLAYER_DAMAGE_REQ` (2097152) on them so the player should not need to do more than 50% damage, but as Treeston said, it should be tested to see if it fixes the issue.

**Comment by Aokromes** [comment]
Any new on this?

**Comment by Killyana** [comment]
Yes adding CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ fix the issue.

**Comment by tkrokli** [comment]
Thanks for confirming. So the fix (based on Treeston's suggestion & help) is still a valid solution.
```sql
-- Set CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ on Iron Sentinel Credit & Iron Dwarf Assailant Credit
UPDATE `creature_template` SET `flags_extra`= 2097152 WHERE `entry` IN (30296, 30297);
```

**Comment by Treeston** [comment]
```sql
`flags_extra` = (`flags_extra`|2097152)
```

**Comment by tkrokli** [comment]
OK, I suppose that is the preferred way to set the flag, even if the current value is zero (0).
