### ISSUE TITLE
worldserver auth

### ISSUE THREAD

**Issue by Jaihoob** [TrinityCore/TrinityCore#17047]
**Description**: worldserver and auth wont start

after fresh compile cant start server nothing happens im on windows 10 

compile them in 32bit 

and try to start them by administator command  and nothing start no error  

**Branch(es)**: 335

**TC hash/commit**:   b82ffb8

**TDB version**:  335.61

**Operating system**:  

**Linking model**: static and dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DDuarte** [comment]
Have  you looked in Server.log? Did you try starting the servers from the cmd?

**Comment by Jaihoob** [comment]
yes i try with cmd administator and no server.log because nothing is happen

**Comment by DDuarte** [comment]
I don't know how to help... try compiling in 64 bits? check if all the DLLs match the architecture you picked?

**Comment by Jaihoob** [comment]
yeah all it 32bit  
if i compile 6.x everything work

**Comment by tkrokli** [comment]
TC>TrinityCore rev. b82ffb88f7e6 2016-04-26 22:25:16 +0100 (3.3.5 branch) (Win32, Release)
TC>TrinityCore rev. b82ffb88f7e6 2016-04-26 22:25:16 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_04_26_03_world.sql`
Windows 10 Home x64 Version 1511 (OS Build 10586.218), VS2013 Update 5, CMake 3.5.1, MySQL 5.6

CMake runs fine, the source compiles without errors (given that I use `C:/PROGRA~2/TRINIT~1` as CMAKE_INSTALL_PREFIX for the 32bit (C:\Program Files (x86)\) path to be able to avoid the 'space invalid as part of the path' install error when compiling), both `Authserver.exe` and `Worldserver.exe` runs without issues. I can not replicate your issue. Without any specific error message, it is pretty difficult to tell what kind of issue you have got.

I can only suggest that you try deleting your build folder content or use the "Delete Cache" feature in CMake before trying again. Have you tried starting Worldserver.exe inside of a CMD window to check for error messages?

If none of my 2 suggestions above are of any help, I recommend discussing your issue in the TC Forum (https://community.trinitycore.org/).
