### ISSUE TITLE
GM Achivements

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#17055]
Hello TC
I have countered bug with GM Achievements 
When GM is log out in .gm off mode and re log he starts to get achievements (Like realm first criteria)
Realm First level 80
Realm First Class
Realm First Race

GM Should not get achievements as far as i know

Steps

1. open GM 
2. Log to game turn on your gm .GM On , .level 79 
3. Re log

**Branch(es)**: 335

**TC hash/commit**: 02d7df6aa435  

**TDB version**:  335.61

**Operating system**:  Win 64bit

http://www.wowhead.com/achievement=457/realm-first-level-80
http://www.wowhead.com/search?q=Realm+first+level+80

**Comment by Aokromes** [comment]
Intended. Don't relog with gm off.
