### ISSUE TITLE
[3.3.5] Crash

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17062]
http://paste.ubuntu.com/16172730/

8114c0618062ae7072ebb1bb682ef2c85481ee23

**Comment by Robox** [comment]
bei mir auch 
Ubuntu 14.4
Boost version: 1.60.0
CMake version: 3.52
MYSQL version: 5.5.49-0ubuntu0.14.04.1
GCC version: 4.8
OpenSSL 1.0.1f

http://paste.ubuntu.com/16173729/

**Comment by jackpoz** [comment]
@Robox what has your crashlog to do with the one above ?

**Comment by Treeston** [comment]
Please provide a full debug build log from a revision that isn't 4 months old.

**Comment by Robox** [comment]
@jackpoz 

sorry did not see that it is here to hantelt veraltetet version.
had only seen a new crash reporting.
my problem relates to siech
https://github.com/TrinityCore/TrinityCore/commit/1aa30d3cce8a2003ad7873410fe9ec09ff357dcf

**Comment by Treeston** [comment]
@Robox we need a stack trace from a debug build binary to be able to reproduce.

**Comment by Robox** [comment]
@Treeston  apologize as I have a stack trace create I've never done

**Comment by jackpoz** [comment]
Please don't hijack random issues with your crash logs

**Comment by Aokromes** [comment]
No answer after months, original account deleted, closing.
