### ISSUE TITLE
Client crashes on launch - Mac

### ISSUE THREAD

**Issue by aaplmike** [TrinityCore/TrinityCore#17067]
**Description**:
Game client always crashed after entering credentials and clicking "Login".

**Current behaviour**: Tell us what happens
Game client always crashed after entering credentials and clicking "Login".

**Expected behaviour**: Tell us what should happen instead
Under previous revisions, login worked as expected. It was only after 9e875c03 that the issue presented. Also expected bnetserver to show the login attempt, but it did not. Nothing that appears notable in the logs.

**Steps to reproduce the problem**:

1. Pull latest branch and recompile & install binaries
2. Replace configs with latest dist configs
3. Verify bnetserver and worldserver launch with no problems
4. Log in to retail with client and get latest patch. Confirm it is 21463.
5. Run connection_patcher, verify success message
6. Change config to point to IP of local server (on local subnet)
7. Launc patched version
8. Provide valid credentials
9. Witness crash, with no messages or details given

Connection log shows as last line, "[IBN Login] Attempting logon | host=192.168.1.60 | port=1119", which are the correct settings. Confirmed in auth.realmlist table that address and localAddress are equal to this value. Bnetserver never shows any log lines, so the client is never making the connection. Netcat connections to the server on 1119 and 8085 both succeed. Logs on pastebin at http://pastebin.com/PyT57xWp. Let me know if anything else would be helpful.

**Branch(es)**: 335/6x  
6x

**TC hash/commit**:  
c28e6a8c160f

**TDB version**:  
TDB6.04

**Operating system**:  
OS X 10.11.4

**Linking model**: static/dynamic
static

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by LuigiElleBalotta** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16872
