### ISSUE TITLE
[3.3.5] Core/SmartAI: fighting player control while charmed

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17076]
3.3.5 d82534a

SmartAI does not currently check whether it has "control" over `me` before casting spells, moving etc.
This means that any SmartAI vehicle/charmed creature will fight against player control and attempt to movechase targets that attack it, cast spells without player input and similar.

(Splitting this issue off from PR #16020.)

**Comment by dr-j** [comment]
well there are some creatures which are charmed by various quest items which are scripted in sai,where you have totake control of another creature example are that quest to find a lithestalker also all of those quests in zul'drak where you must use sceptor to control npcs and those 2 are just off the top of my head but there are quiet a few creatures which are possessed by player during quest and these still need to run sai.

Think better solution would be disable sai in case of player mind control or similar spells been used on creatures

**Comment by Treeston** [comment]
Yes, but this also effects vehicles (which definitely still need to run smartai hooks).

The AI needs check whether the creature is player-controlled before executing startattack/movechase or similar.

**Comment by Treeston** [comment]
Closed by #17738.
