### ISSUE TITLE
Unable to login with WOW client to Trinity Server

### ISSUE THREAD

**Issue by Jacokrou** [TrinityCore/TrinityCore#17079]
TrinityCore rev. 7491caca8829 2016-04-03 15:54:32 +0100 (3.3.5 branch) (Win64, Release) (worldserver-daemon) ready...
WorldSocket::HandleAuthSession: Client xxx.xxx.xxx.22 requested connecting with realm id 879912755 but this realm has id 1 set in config.
This error is created in the Server.log file each time a client connects

**Operating system**: Windows 10 

**Linking model**: static/dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DDuarte** [comment]
Client version?

**Comment by djbeauchamp** [comment]
I would start with...
Check your worldconf.conf.  The field RealmID = 1 must match the value in your auth database. realmlist table id field for your sever.

**Comment by Jacokrou** [comment]
Client version 1.12.1 (5875)

Below Extract from Worldserver.conf
# CONNECTIONS AND DIRECTORIES
#
#    RealmID
#        Description: ID of the Realm using this config.
#        Important:   RealmID must match the realmlist inside the auth database.
#        Default:     1

RealmID = 1

#
#    DataDir
#        Description: Data directory setting.
#        Important:   DataDir needs to be quoted, as the string might contain space characters.
#        Example:     "@prefix@/share/trinitycore"
#        Default:     "."

DataDir = "."

**Comment by DDuarte** [comment]
The branch named **3.3.5** supports 3.3.5a (12340) clients, as described in https://trinitycore.atlassian.net/wiki/display/tc/Installation+Guide
