### ISSUE TITLE
[CMake] /Zm compile error after re-opening project

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#17080]
**Description**:

**Current behaviour**: After re-opening a project solution in VS 2015 I get the Zm error that there is too less memory assigned to the compiler.

**Expected behaviour**: compile should work after re-opening the project

**Steps to reproduce the problem**:

1. Generate a project
2. Compile for the first time
3. Close VS
4. Re-Open it and the project
5. change something somewhere
6. compile and get the error

(The error is thrown by the modified project such as game for example when you modify unit.cpp)

**Branch(es)**: 335/6x  

**TC hash/commit**:  7eab3d37160b1092413a8fa1df73b5d5679ee2b8

**TDB version**:  6.04

**Operating system**:  Win 10

**Linking model**: dynamic

Custom Additions: WIP Iron Docks scripts --> scripts_draenor is a new project generated by the dynamic cmake addition

**Comment by DDuarte** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17032#issuecomment-215416429

After defining the env var, restart VS and/or the computer.


This issue has been happening for a while with TC but we think that it might be a VS debug, marking as won't fix (for now, at least).
