### ISSUE TITLE
Event not found or invalid

### ISSUE THREAD

**Issue by Sktoon** [TrinityCore/TrinityCore#17089]
**Description**: Event and Creature problem

**Current behaviour**: This happen after updating the core

**Expected behaviour**: Clean console

**Steps to reproduce the problem**:

`CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 1730) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 1730) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 1751) in 'creature_text' table. Ignoring.
SmartAIMgr::LoadSmartAIFromDB: Entry 29647 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 29884 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 300) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 300) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 321) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Venomtail Scorpid (Entry 3127, GUID 321) in 'creature_text' table. Ignoring.
SmartAIMgr::LoadSmartAIFromDB: Entry 29647 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 29884 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 29647 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 29884 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
SmartAIMgr::LoadSmartAIFromDB: Entry 29647 SourceType 0, Event 1, Link Event 2 not found or invalid.
SmartAIMgr::LoadSmartAIFromDB: Entry 29884 SourceType 0, Event 4, Link Source Event not found or invalid. Event will never trigger.
`

**Branch(es)**: 3.3.5 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/8d09065525139d4e9

**TDB version**:  335.61

**Operating system**:  win server 2008

**Linking model**: static

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tkrokli** [comment]
Possible duplicate issue, Venomtail Scorpid & Orgrimmar Grunt interaction fixed by SQL in
[**Creature Orgrimmar Grunt: fix annoying console spam**](17083) #17083

**Comment by dr-j** [comment]
and those last smartaimgr errors were already fixed and errors from creaturetextmgr are not particulary useful when its script on a different creature which attempts to display text on target as the error just gives the details for the npc which attempt to display text was made on not the invoker creature.

**Comment by Sktoon** [comment]
can you give me smartaimgr error fix?

**Comment by tkrokli** [comment]
It should already be in your source if you have updated your cloned source properly and let Worldserver populate the world DB from scratch. Empty or drop your world DB and let worldserver rebuild it.

**Comment by Sktoon** [comment]
i don't need to apply database updates from updates folder?
i rebuild it and everything is okay.

**Comment by tkrokli** [comment]
Correct, ever since the DB auto updater got implemented, Worldserver handles the updates by itself
(as long as you have not changed anything in the `UPDATE SETTINGS` section in Worldserver.conf ) .

**Comment by Sktoon** [comment]
thank you so much
