### ISSUE TITLE
[3.3.5] DB/Quest 10942 ( Children's Week )

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17097]
**Description**:
Quest 10942 can't complete

1.If you use the Blood Elf Orphan Whistle the Children spawns but the children dont give the quests.
2.The Children have not a walking or running Animation

http://www.wowhead.com/quest=10942/childrens-week
https://www.youtube.com/watch?v=I3Y9ORHfBPg

**Branch(es)**: 335

**TC hash/commit**:  
TrinityCore rev. d9dcbbc8af3c 2016-05-07 11:53:46 +0100 (335 branch)
**TDB version**:  
335.61 + all Updates
**Operating system**:  
Win7 64Bit

**Comment by tkrokli** [comment]
TrinityCore rev. d9dcbbc8af3c 2016-05-07 11:53:46 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_05_07_01_world.sql`

That's odd, I can't replicate your issue. Here is my interaction using a level 77 belf hunter (gm account):

![wowscrnshot_050716_202125](https://cloud.githubusercontent.com/assets/4903600/15093778/b86a947e-1491-11e6-93dd-36416f985122.jpg)

The gm account character is with GM OFF (my default), as you can see in the picture.
You could try rebuilding your world DB (drop world, let worldserver create & populate it again).

**Comment by Tauriella** [comment]
I have now a clean Databes

Hmm.... Strange
I have droped the world and new installed Database and does not work 
![weisenkind](https://cloud.githubusercontent.com/assets/10637389/15094196/3d0817a0-149d-11e6-9a9d-cf41074fbda5.jpg)

**Comment by dr-j** [comment]
have you previously completed quests in a previous event since can confirm if you have already done quests once these never reset when they should reset each year.

**Comment by Tauriella** [comment]
I play this quest the first time

**Comment by dr-j** [comment]
one thing that maybe worth mentioning the first quest for all cw chains is taken from orphan matron not the orphan and orphan will not give any quests until the first quest from matron is returned

**Comment by tkrokli** [comment]
Notice that your character in the picture has got GM ON, which may cause undesired results.

**Comment by Tauriella** [comment]
Now i have test on a normal Horde Player Character 80 Paladin but the same result
not working

**Comment by MrSmite** [comment]
@Tauriella Did you try with different races from Horde? I noticed your OP has a Tauren but the example by tkrokli is using a Blood Elf. Perhaps it's a racial issue with the DB?

**Comment by tkrokli** [comment]
@MrSmite : not sure where you found a tauren character in this issue, I am fairly sure that the character Orcsa is a male Orc death knight `<GM>` if you are referring to Tauriella's picture in https://github.com/TrinityCore/TrinityCore/issues/17097#issuecomment-217664845 .

In theory, there could be issues with death knights if you skip the ending quests to join the Horde or the Alliance after the scourge is defeated in Acherus / the Ebon Hold. There could be something wrong with the character's faction status. We don't have enough information to go on to know why that quest will not work for that death knight character. Maybe even the quest number is wrong for a death knight.

**Comment by MrSmite** [comment]
@tkrokli At a glance I thought the picture posted was a Tauren (based on the size of the shoulder pads). I didn't click it to magnify and outside of Hunters, I'm not familiar with many armor sets.

**Comment by Tauriella** [comment]
@MrSmite work this Quest for you ?
I have testet with normal Player Chars. Horde Undead Prist / Bloodelf Paladin and always the same result:
Not working

**Comment by MrSmite** [comment]
> work this Quest for you ?

I haven't tried Horde however it does work with mixed races on Alliance. I tried it with A Night Elf Hunter, Priest and Druid in Stormwind and none of them had issues.

**Comment by Tauriella** [comment]
In Stormwind/Thunder Bluff  works all Quest fine ( Tested with Horde/Alliance Player Char's )
I meane this one Quest in Shattrath

**Comment by Killyana** [comment]
Impossible to reproduce in a clean core.

**Comment by tkrokli** [comment]
TC>TrinityCore rev. ba574fab7523 2016-06-12 16:46:20 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_06_12_09_world.sql`

Just to confirm that this still works and to repeat what said previously: I am unable to replicate your issue, not even with an Orc Death Knight, on current straight source & database content. Both quest item Blood Elf Orphan Whistle (http://www.wowhead.com/item=31880/blood-elf-orphan-whistle) and the Quest http://www.wowhead.com/quest=10942/childrens-week are working as intended with Blood Elf Orphan (http://www.wowhead.com/npc=22817/blood-elf-orphan) also responding correctly. Screenshot:

![wowscrnshot_061316_053255](https://cloud.githubusercontent.com/assets/4903600/15996576/668b998c-3129-11e6-94f8-973841140f20.jpg)

![wowscrnshot_061316_053332](https://cloud.githubusercontent.com/assets/4903600/15996570/45185100-3129-11e6-9cf4-7aef34b2a541.jpg)
***
I guess that either your core or DB must be different from straight source if you still get this issue.
