### ISSUE TITLE
[3.3.5] Crash server

### ISSUE THREAD

**Issue by leonardofan157** [TrinityCore/TrinityCore#17091]
TrinityCore rev. 811b29c8e1ebdd0e12a2a3eb7c9586b04d7f5e62 + 2016-03-12 22:44:04 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.60 + Updates
Linux ubuntu 14.04

Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Could not load MMAP name:Eastern Kingdoms, id:0, x:18, y:36 (mmap rep.: x:18, y:36)

/home/core/src/server/game/Entities/Object/Object.h:534 in GetMap ASSERTION FAILED:
  m_currMap
Segmentation fault

   
    Server crashes
    Log DB: http://pastebin.com/YRkSBE1a
    serverlog: http://pastebin.com/xJLAHwdk
    

Branch(es): 335

TC hash/commit: 811b29c8e

TDB version: TDB 335.60

Operating system: Ubuntu 14.04

**Comment by Aokromes** [comment]
Again, update you core, and compile on debug mode, running core under gdb to report one crash.

**Comment by leonardofan157** [comment]
Impossible to get help this way is showing WHAT ta happening already giving crash in this line with the game open.

**Comment by Aokromes** [comment]
Those logs, are useless, and don't helps at all to determine the crash reason, only following crashlog rules helps to find the reason.
