### ISSUE TITLE
[6.x] DB/Quest: Thirst Unending

### ISSUE THREAD

**Issue by CrisPj** [TrinityCore/TrinityCore#17098]
**Description**:
Mana Wyrm Does not give quest credit to Paladin,Monk,Warrior or Hunter

**Fix**
```sql
-- Thirst Unending 6.x
-- Arcane Torrent Monk    129597
-- Arcane Torrent Paladin 155145
-- Arcane Torrent Warrior 69179
-- Arcane Torrent Hunter  80483

SET @WYRM := 15274;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@WYRM AND `source_type`=0 and `id` in (4,5,6,7);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@WYRM,0,4,0,8,0,100,1,69179,0,0,0,11,61314,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mana Wyrm - On Spellhit 'Arcane Torrent' - Cast 'Quest Credit 8346' (No Repeat)"),
(@WYRM,0,5,0,8,0,100,1,80483,0,0,0,11,61314,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mana Wyrm - On Spellhit 'Arcane Torrent' - Cast 'Quest Credit 8346' (No Repeat)"),
(@WYRM,0,6,0,8,0,100,1,129597,0,0,0,11,61314,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mana Wyrm - On Spellhit 'Arcane Torrent' - Cast 'Quest Credit 8346' (No Repeat)"),
(@WYRM,0,7,0,8,0,100,1,155145,0,0,0,11,61314,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mana Wyrm - On Spellhit 'Arcane Torrent' - Cast 'Quest Credit 8346' (No Repeat)");
```
**Branch(es)**: 6x  

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/c75fcbe20b07fd7518be58bf02ba30d903133449

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by GnaXi** [comment]
This issue is still present in rev. 5da217877be7

**Comment by tkrokli** [comment]
@GnaXi : if this issue is not solved in 6.x, please open a new issue (if you have not done so already) where you can use the issue template to fill in as many details as possible of which character classes you have tested the issue on and more details of whether you know if this works for some classes or not.

This page is not a practical place to add any new issues, the original post was about posting a solution. (You can of course refer to this page in a new issue.)
