### ISSUE TITLE
[6.x] Errors when trying to compile

### ISSUE THREAD

**Issue by KevinCollmer** [TrinityCore/TrinityCore#17094]
**Description**:
Getting the following errors while trying to compile the latest 6.x

**TC hash/commit**: c75fcbe20b07fd7518be58bf02ba30d903133449

**Current behaviour**:
`[ 24%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_list.cpp.o
In file included from /root/wow-source/trinitycore_6.x/TrinityCore/src/server/game/Achievements/AchievementMgr.h:22:0,
                 from /root/wow-source/trinitycore_6.x/TrinityCore/src/server/scripts/Commands/cs_guild.cpp:25:
/root/wow-source/trinitycore_6.x/TrinityCore/src/server/game/Achievements/CriteriaHandler.h:65:32: error: declaration of ‘const Criteria* CriteriaTree::Criteria’ [-fpermissive]
     Criteria const* Criteria = nullptr;
                                ^
compilation terminated due to -Wfatal-errors.
src/server/scripts/CMakeFiles/scripts.dir/build.make:468: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_guild.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_guild.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
 error: declaration of ‘const Criteria* CriteriaTree::Criteria’ [-fpermissive] error: declaration of ‘const Criteria* CriteriaTree::Criteria’ [-fpermissive]CMakeFiles/Makefile2:1246: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2`

**Steps to reproduce the problem**:

1. `cmake ../ -DTOOLS=1 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DSERVERS=1 -DSCRIPTS="static" -DCMAKE_INSTALL_PREFIX=/root/wow-build/trinitycore_6.x_latest -DWITH_WARNINGS=1`
2. `make -j 4`

**Branch(es)**: 6x  

**Operating system**:  Debian 8.4

Cmake 3.5.2

Compiler version:
`ii  g++                               4:4.9.2-2                            amd64        GNU C++ compiler
ii  g++-4.9                           4.9.2-10                             amd64        GNU C++ compiler
ii  gcc                               4:4.9.2-2                            amd64        GNU C compiler
ii  gcc-4.9                           4.9.2-10                             amd64        GNU C compiler`

**Comment by Aokromes** [comment]
There is no need to close previous ticket if you get  invalid report thing, simply edit previous one to fit standards.
