### ISSUE TITLE
Crash error trinitycore rev 60

### ISSUE THREAD

**Issue by leonardofan157** [TrinityCore/TrinityCore#17090]
TrinityCore rev. 811b29c8e1ebdd0e12a2a3eb7c9586b04d7f5e62 + 2016-03-12 22:44:04 +0100 (3.3.5 branch) (Win64, Release)
TDB 335.60 + Updates
Linux ubuntu 14.04

Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Unit::HandleProcTriggerSpell: Spell 58410 (effIndex: 0) has unknown TriggerSpell 45176. Unhandled custom case?
Could not load MMAP name:Eastern Kingdoms, id:0, x:18, y:36 (mmap rep.: x:18, y:36)

/home/core/src/server/game/Entities/Object/Object.h:534 in GetMap ASSERTION FAILED:
  m_currMap
Segmentation fault

**Comment by Aokromes** [comment]
1st law update your core before report bugs.
2nd law learn to compile core on debug.
3rd law use gdb to get proper crashlog.
