### ISSUE TITLE
[3.3.5] Trial of the Crusader: Snobold Vassal unkillable

### ISSUE THREAD

**Issue by Sakuragi85** [TrinityCore/TrinityCore#17108]
**Description**: Snobold Vassals are unkillable. They can't drop under 1% (Tested on 10m and 25m as Alliance)

**Current behaviour**: The first boss spawns adds called "Snobold Vassals". The first comes about when he has 80%hp. Those adds can't be killed, only with the .die command.

**Expected behaviour**: they should be killable

**Steps to reproduce the problem**:

1. Enter the Trial of the Crusader Raid in either 10 or 25 man. (I tested as Alliance, maybe Horde one is also buggged)
2. Talk to the NPC to start the first boss encounter
3. Damage the boss until he spawns the first Vassal (about 80%)
4. Try killing the Vassal

**Branch(es)**: 335

**TC hash/commit**:   945abb1 

**TDB version**:  335.61

**Operating system**:  Windows 10

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16895#issuecomment-211077328

@ccrs  should re-write this gormok fight :D

**Comment by ConradBunton** [comment]
Snobold Vassals are not killable yet. There life down but le last life point...

**Comment by Keader** [comment]
Blame DamageTaken function. :dancer:
