### ISSUE TITLE
[3.3.5] The Ethereum can't be completed

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#17109]
http://www.wowhead.com/quest=10339/the-ethereum

After killing Ethereum Assassin (5), Ethereum Shocktrooper (5), Ethereum Researcher (2) and Captain Zovax you are supposed to talk to Commander Ameer at Ethereum transponder Zeta, but when you click on the teleport, Commander Ameer appear for few seconds and disappear without any dialogue.

I suppose Commander Ameer image should stay and complete the quest

1. kill all the target
2. activate Ethereum transponder Zeta

Trinity Core: d82534a7bbd4
DB: 335.61
OS X 10.11.4 both server and client

**Comment by dr-j** [comment]
When the teleporter is activated the npc remains for 3 mins before it despawns after which you can use the teleporter again to summon again

**Comment by ikir83** [comment]
It seems it works the second time, pretty strange. The first time the npc appear for few seconds, disappear, even the teleports is gone after a while. When I see the teleport again, activating it seems finally ok and I can speak with Ameer

**Comment by tkrokli** [comment]
What is the expected behaviour, how does the event play out on retail servers?
(It would have been an advantage if you had kept and filled in the issue template.)

**Comment by Wylath** [comment]
The problem comes from smartAI entryorguid 20482, id 2, action_type 41 after having been aggro.

**Comment by dr-j** [comment]
Its not a problem believe its intended as I remember now if the npc is agrod on retail says line and despawns and I remember scripting this now as says line 'Hostiles detected. Ending transmission.' when despawns on agro there is nothing in script to despawn the transponder.

So you need to ensure there is nothing which will agro before using transponder.

**Comment by tkrokli** [comment]
If I understand your description correctly, looking at the SAI for `entryorguid`= 20482 (Image of Commander Ameer),
```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid`= 20482 AND `id` IN (0,1,2);
```
```
entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_x  target_y  target_z  target_o  comment
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  --------  --------  --------  --------  --------------------------------------------------------------------------------
      20482            0       0       1           4                 0           100            1             0             0             0             0            1              0              0              0              0              0              0            1              0              0              0         0         0         0         0  Image of Commander Ameer - On Agro - Say Line
      20482            0       1       2          61                 0           100            1             0             0             0             0           45              1              1              0              0              0              0           14          25179         184383              0         0         0         0         0  Image of Commander Ameer - On Agro - Set Data 1 1 to Ethereum Transponder Zeta
      20482            0       2       0          61                 0           100            1             0             0             0             0           41              0              0              0              0              0              0            1              0              0              0         0         0         0         0  Image of Commander Ameer - On Agro - Despawn
```
does this mean that the player is required to make sure that there are no nearby mobs to aggro `Image of Commander Ameer` before it is safe to summon him and continue with the quest, hence nothing should be wrong with the event and the SAI? Can we conclude that this event is working as intended? Or do we need extra confirmation that even if there is nothing around to aggro `Image of Commander Ameer`, he will still despawn on the first attempt to complete this quest?

**Comment by MrSmite** [comment]
I don't know if this is a private server or not but...

https://www.youtube.com/watch?v=JIq4pCcIzn0

**Comment by dr-j** [comment]
As said it is correct behaviour for a lot of summoned quest givers to say someline and disappear on retail rather than fight,

This npc does as thats what the line saying hostiles detected, ending transmission is used but there are several other quest giver/reward npcs which wont hang around if they get agro ie another examplel of such is the npc you have to keep on summoning during the path of conqest chain in shadowmoon

**Comment by MrSmite** [comment]
> As said it is correct behaviour for a lot of summoned quest givers to say someline and disappear on retail rather than fight,

Agree. I posted the video in response to tkrokli who asked the expected behavior but forgot to quote. That's also why I indicated I didn't know if it was actually retail.

**Comment by tkrokli** [comment]
So... close issue because this is working as intended?
