### ISSUE TITLE
[3.3.5] Crashlog

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17104]
some time crashed 

i dont know why happen but i have debug crash log
i have some custom patch but crash is not from customs [ crash lines in not currect wih tc]

3.3.5

https://github.com/TrinityCore/TrinityCore/commit/775b03bf6f345ac2bdc4936bb0ead5b0ad4fb193

Centos 6

http://pastebin.com/b9v4nqZr

**Comment by Nawuko** [comment]
Custom changes. There was an error finding the display id in CreatureDisplayInfo.dbc so the server triggered an assert. This is most likely an unrealeted problem to TC (modified database, modified dbc or source).

**Comment by SQLfix** [comment]
database is clean TDB 61
DBC created from tools extractor
source is clean for display or npc s

**Comment by jackpoz** [comment]
do you have any change in Player.cpp ? lines don't match between the crashlog and sources

**Comment by Kittnz** [comment]
[21:10:23] <Kittnz> i can use it
[21:10:26] <Kittnz> its added to mounts
[21:10:28] <Kittnz> works fine

**Comment by Nawuko** [comment]
Yea i would pretty much label that as invalid report. No way of reproducing (because the assert can not occur randomly [only when the displayinfo in the dbc was not found, which is not a thing that "might happen"]). + Custom changes.

**Comment by jackpoz** [comment]
@SQLfix do you have some custom race/class combinations ?

**Comment by SQLfix** [comment]
yes  crossfaction //

**Comment by jackpoz** [comment]
Please mention the custom patches BEFORE we spend time debugging the issue, not after.
Try to reproduce it on clean TC, the crash looks caused by custom changes messing with UNIT_FIELD_NATIVEDISPLAYID at runtime and/or invalid race/class combinations
