### ISSUE TITLE
[3.3.5] Core/Spell: Homebind timer triggered by getting invited to group

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#17102]
**Description**: Homebind timer is being triggered if a player gets invited while inside an instance, regardless if inside player has a permanent bind or not.

**Current behaviour**: Homebind timer is triggered by getting invited to group

**Expected behaviour**: Homebind timer shouldn't get triggered, maybe only if inside player has a permanent bind(not sure about exactly how it should be)

**Steps to reproduce the problem**:
1.  Player A enters an instance
2.  Player B, outside the instance, invites player A
3.  Homebind timer will be triggered for player A

**Branch(es)**: 335

**TC hash/commit**: 3d8bab866831

**Comment by jackpoz** [comment]
Someone should investigate about retail behavior before anyone can work on a fix

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by sirikfoll** [comment]
No
