### ISSUE TITLE
[6.x] DB/Quest:Life of the Party

### ISSUE THREAD

**Issue by Wylath** [TrinityCore/TrinityCore#17110]
**Description**: The creature are in phaseid 379, but no spells spell with phase 379

**Current behaviour**: No phase change

**Expected behaviour**: Add phase_area with the phase change
https://www.youtube.com/watch?v=IjKLffqWdpo

**Steps to reproduce the problem**:

1. Accept the quest and see that there is not change phase

**Branch(es)**: 6x  

**TC hash/commit**:  cccdbf4

**TDB version**:  TDB 6.04

**Operating system**:  W10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Wylath** [comment]
it is now the costume change for the quest : 
```
DELETE FROM `spell_area` WHERE `spell` IN (66927, 66928);
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`,`quest_start_status`) VALUES
(66927,4765,14153,14153,0,0,1,1,8),
(66928,4765,14113,14113,0,0,0,1,8);
```

**Comment by tkrokli** [comment]
@Wylath : Pro tip for highlighting the SQL syntax in github posts: put ```sql on top of the code block. :)

**Comment by Wylath** [comment]
it still lacks the phase change and validation for the quest

**Comment by yashirotcm** [comment]
confirming that the quest phasing is missing, rendering the player useless unless they relog.

**Comment by BahDumbBugs** [comment]
Issue still persists. Quest can be accepted but no partygoers are visible until GM is turned on. Current commit is a16d320.

**Comment by tkrokli** [comment]
This issue was closed with a solution. Unless the solution is wrong,
please open a new issue ticket with full template description.

**Comment by BahDumbBugs** [comment]
Question @tkrokli  - If it was fixed, how come it was never committed?

**Comment by tkrokli** [comment]
Not sure. Some times closed issues never gets updated if a later fix solves an unsolved issue, particularly if the issue page mentions a persisting problem after a solution has already been committed. I will attribute this to not enough focus on the feedback and also that TC prefers to have a new issue ticket opened if an issue still exists after a solution has been posted.

**Comment by Aokromes** [comment]
Aokromes closed this in 507e722 on May 26, 2016

**Comment by tkrokli** [comment]
Yes, that was kind of my point, but maybe @BahDumbBugs did not notice it?
(Thanks for pointing it out, nonetheless.)

**Comment by BahDumbBugs** [comment]
Yes @tkrokli  I did miss that commit. Sorry @Aokromes . I see you closed it, but the issue is still outstanding for me. I will open a new ticket. Something isn't right - moving on.
