### ISSUE TITLE
[3.3.5][6.x] Core/SAI: OOC no repeat event not triggred on spawn/respawn

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17117]
**Description**: 
The event ooc no  repeat is not triggread on spawn/respawn it's triggred only on evade

**Current behaviour**: 
The event ooc no  repeat is triggred only on evade.

**Expected behaviour**: 
The event ooc no  repeat  must be triggred spawn, respawn and evade.

**Steps to reproduce the problem**:

1. go to creature 32262 or 26816
2. Notice they are not channeling any spell
3. Aggro one of this npc then gm on, they will evade and channel the spell
4. .die one of this npcs then respawn it, notice it  doesn't cast the spell on respawn

**Branch(es)**: 335/6x  

**TC hash/commit**:  rev. 4a85b652f2eb

**Comment by jackpoz** [comment]
shouldn't Out Of Combat be triggered only if the creature entered combat ?

**Comment by Killyana** [comment]
No, it trigger, on respawn/spawn and evade, at least it was like this weeks ago and since years.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/pull/17120

**Comment by Killyana** [comment]
Fixed
