### ISSUE TITLE
[3.3.5][6.x][ToC] Core/Creature: Anub'arak Movement

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17129]
**Description**: On P3 the Boss will focus any pet around and will stop moving.

**Steps to reproduce the problem**:

1. Go to Anub'arak with a hunt and another character
2. Keep the aggro with the second character and put the boss on P3 (around 30% HP)
3. Notice the boss is focusing the hunt pet and you cannot get it back
4. .Die the pet and move far from Anub, he will not be able to follow you
5. Retry with only one character, once the boss is on P3 he will not be able to move, the root effect is not related to the pet.

**Branch(es)**: 335/6x  

**TC hash/commit**:  rev. e130593e8547

**Comment by Keader** [comment]
confirm.
This bug is "new"
i'm using rev before jan/2016 and has no issue about it.

**Comment by ryoting** [comment]
YES,CONFIRM.

**Comment by Runico** [comment]
I have seen this bug also happens with hand of protection

**Comment by Aokromes** [comment]
It's not new bug, i have seen it for years.

**Comment by joshwhedon** [comment]
Aokromes: I can ensure you it has not been there for years, at most a few months. And you don't even need a pet to reproduce it. Personnally I was able to reproduce it simply by moving after the boss casted his P3 spell. The boss did not follow me anywhere, kept attacking / casting, but without following.

**Comment by Killyana** [comment]
The problem comes from this spell: http://www.wowhead.com/spell=66118/leeching-swarm
Find any hostile npc the, aggro it and .cast back 66118 it will focus the pet and stop moving exactly like Anub'arak

**Comment by joshwhedon** [comment]
Personnally my guess is that the spell facing fixes don't handle very well spells with a cast time and caster as target, resulting in that issue (target not being updated and caster not resuming movement).

**Comment by ryoting** [comment]
any news?

**Comment by Keader** [comment]
this issue not make any sense for me.
How a spell (66118) makes a creature focus on pet, and add aura on pet, with Attr AttributesEx3: 0x00000100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS)?

**Comment by joshwhedon** [comment]
Hi, sorry, forgot to update this thread with my findings.
IT is not the spell 66118 which is the problem, but the spell used in the script of this spell.
In the script, Anub casts a spell on a single target every second, but untriggered.
As a result the spell trigger the FocusTarget on the target, and put Anub in a state of forever focusing.
The simple solution is to make the spells in the script trigerred (or at least with the ignore spell facing flag).

**Comment by Keader** [comment]
Using:
```diff

diff --git a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
index ec6f0a3..b81e1b8 100644
--- a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
+++ b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
@@ -993,9 +993,9 @@ class spell_anubarak_leeching_swarm : public SpellScriptLoader
                     if (lifeLeeched < 250)
                         lifeLeeched = 250;
                     // Damage
-                    caster->CastCustomSpell(target, SPELL_LEECHING_SWARM_DMG, &lifeLeeched, 0, 0, false);
+                    caster->CastCustomSpell(target, SPELL_LEECHING_SWARM_DMG, &lifeLeeched, 0, 0, true);
                     // Heal
-                    caster->CastCustomSpell(caster, SPELL_LEECHING_SWARM_HEAL, &lifeLeeched, 0, 0, false);
+                    caster->CastCustomSpell(caster, SPELL_LEECHING_SWARM_HEAL, &lifeLeeched, 0, 0, true);
                 }
             }
 
```

Works (has custom stuffs, line numbers should not work).
But, still have issue.
Why pets give the aura/damage?
Spell have:
```
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
**AttributesEx3: 0x00000100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS)**
AttributesEx5: 0x00000400 (SPELL_ATTR5_HIDE_DURATION)
```

Aura should not be appled in pet

**Comment by Keader** [comment]
Ok, full diff looks like: (diff on clean tc, lines should match lol)

```diff
diff --git a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
index 7c622c6..dfe0cac 100644
--- a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
+++ b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
@@ -881,9 +881,9 @@ class spell_anubarak_leeching_swarm : public SpellScriptLoader
                     if (lifeLeeched < 250)
                         lifeLeeched = 250;
                     // Damage
-                    caster->CastCustomSpell(target, SPELL_LEECHING_SWARM_DMG, &lifeLeeched, 0, 0, false);
+                    caster->CastCustomSpell(target, SPELL_LEECHING_SWARM_DMG, &lifeLeeched, 0, 0, true);
                     // Heal
-                    caster->CastCustomSpell(caster, SPELL_LEECHING_SWARM_HEAL, &lifeLeeched, 0, 0, false);
+                    caster->CastCustomSpell(caster, SPELL_LEECHING_SWARM_HEAL, &lifeLeeched, 0, 0, true);
                 }
             }
 
diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 70eb7ad..1756a95 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3437,6 +3437,9 @@ void SpellMgr::LoadSpellInfoCorrections()
                 // unsummoned when spell missile hits the ground so nothing happen in result
                 spellInfo->DurationEntry = sSpellDurationStore.LookupEntry(85);
                 break;
+            case 66240: //Anubarak Leeching Swarm damage
+                spellInfo->AttributesEx3 |= SPELL_ATTR3_ONLY_TARGET_PLAYERS;
+                break;
             // ENDOF TRIAL OF THE CRUSADER SPELLS
             //
             // HALLS OF REFLECTION SPELLS
```

**Comment by Keader** [comment]
Fixed https://github.com/TrinityCore/TrinityCore/commit/3c35ce06af381cd416daad868c0f11709eb4855f

**Comment by joshwhedon** [comment]
Hodir seems to have the same issue, but with SPELL_ICICLE strangely.
