### ISSUE TITLE
[6.x] FAQ: cooler-SAI: whether need to patch SAI after branch6.x new install with additional packet of cooler-SAI

### ISSUE THREAD

**Issue by angelsss** [TrinityCore/TrinityCore#17123]
This is the first time I learned to report the Issues with the full template format
------------------------
**Description**: I can't decide whether I need to patch SAI use additional packet with cooler-SAI:

**Current behaviour**: Tell us what happens: I found TC 6.x git source has include scripts dir in 6.x/src/server/scripts

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1.  The player feedback no AI of some creature
2. I find AI patch source to  6.x in git repositories at https://github.com/cooler-SAI/patch
3. I was very annoyance to decide whether to patch SQL to AI with cooler-SAI

**Branch(es)**: 335/6x  : 6.x 

**TC hash/commit**:  c9ba5ce591a8

**TDB version**:  6.04

**Operating system**:   Centos 6.7 64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
This is not a forum.
