### ISSUE TITLE
Issue not fully fixed.17125

### ISSUE THREAD

**Issue by Cryselia** [TrinityCore/TrinityCore#17126]
**The Npc Issue is not fully fixed please re-open**. ref: https://github.com/TrinityCore/TrinityCore/issues/16759
https://github.com/TrinityCore/TrinityCore/issues/17125

**TC hash/commit**: 0d5adf3

**Comment by Aokromes** [comment]
the ticket is duplicate, stop opening new tickets.

**Comment by Cryselia** [comment]
I have update issue please check out 17125 with npc scarlet infantry.

**Comment by Aokromes** [comment]
You can't read that your ticket is a duplicate report of one generic bug?

**Comment by Cryselia** [comment]
@Aokromes Sorry for inconvenience I felt it was necessary to add this because it was left out on other tickets. May you please mention my comment. I wasn't quite sure how to address as i thought the issue and was stated as fixed and closed.
