### ISSUE TITLE
[3.3.5][6.x] Core/Unit: unit_flags 32768 (UNIT_FLAG_UNK_15)

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#17121]
According to my observations and analysis, to expect that the flag should impose PvP sign on the NPC, in accordance with the faction (Horde or Alliance)

From what I have done such a conclusion?
Examples of various NPC:
http://www.wowhead.com/npc=1867/dalaran-apprentice
http://www.wowhead.com/npc=2268/hillsbrad-footman
http://www.wowhead.com/npc=30244/miura-brightweaver
http://www.wowhead.com/npc=32599/surveyor-hansen
http://www.wowhead.com/npc=27035/venomspite-deathguard
http://www.wowhead.com/npc=27557/warsong-elite

The difference between these and the many other NPC official server only in absence of PvP mode.
I would like to receive more information from the Trinity community, if someone has something to say.

Implementation of the flag:

1. The list of converted fractions from FactionTemplate.dbc
2. Determine the Alliance and Horde
3. The core of the processing of this flag will check this list and add the flag PvP for NPC.

Adding manually a particular fraction in the list to avoid errors if the NPC has been assigned not true flag

Branch: 3.3.5
TC hash/commit: d9dcbbc

**Comment by tkrokli** [comment]
What is the reason for closing this? (I'm not complaining, I just think there should be an explanation.)

**Comment by Kodekc** [comment]
@tkrokli , closed, since judging by the sniffer, this flag is responsible for swimming, I turned the confusion, I can not understand why some NPC has a PvP flag, while others do not ...

**Comment by Kodekc** [comment]
https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParser/Enums/UnitFlags.cs

OnlySwim                         = 0x8000
