### ISSUE TITLE
[3.3.5/6x] Missing NPC's Weapon's in Deathknight Starting area. 

### ISSUE THREAD

**Issue by Cryselia** [TrinityCore/TrinityCore#17125]
**Description**: Death knight starting area quest http://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins for Npc's infantrymen and other npc's in area is missing weapons when they should have there weapons equipped.  

**Current behavior**: Missing weapon on npc's.

**Expected behavior**: Guards npc's should should have a weapons in there hand in starting area for death knight. 

**Steps to reproduce the problem**:

1. Create Death knight
2. Get to the quest http://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins in main quest line. 
3. These guys should have weapons not using there fist like in retail wow. Screenshot: http://img.prntscr.com/img?url=http://i.imgur.com/WRxa4ah.jpg my source also screenshot of an npc with weapon at http://www.wowhead.com/npc=28609/scarlet-infantryman this is not the only npc that should have weapon btw. 

**Branch(es)**: 335/6x  

**TC hash/commit**:   0d5adf3

**TDB version**:  3.3.5.61

**Operating system**:   Linux Ubuntu, 16.04

**Comment by Aokromes** [comment]
#16759

**Comment by Cryselia** [comment]
It's not fully fixed....

**Comment by Killyana** [comment]
Equipements are wrong for this npcs:
``` sql
UPDATE `creature_equip_template` SET `ItemID1`=38721, `ItemID2`=12932 WHERE `CreatureID`=28609;
