### ISSUE TITLE
[3.3.5] DB/creature_loot_template - excessive drop rate for white items

### ISSUE THREAD

**Issue by IzFrost** [TrinityCore/TrinityCore#17139]
**Description**:
I have not comprehensively tested this across starting zones and low-level areas, but in Durotar most mobs drop an inordinate amount of certain named white quality loot (i.e., Disciple's Cloak (6514), Journeyman's Bracers (3641), etc). This is probably a DB mistake in either what loot category mobs have been assigned, or an unusually high drop chance for those named white quality items. I can go kill 20 random Durotar mobs and end up with 9 of the Journeyman's Bracers. That's too much.

**Expected behaviour**:
At most you should expect to see a named white quality item drop rarely. And even then they have a much higher chance of being found on certain higher level quest related mobs. Think Fizzle Darkclaw as opposed to just a generic Venomtail Scorpid.

**Steps to reproduce the problem**:
1. Compile latest 3.3.5
2. Create a new character in Durotar.
3. Go kill random mobs and watch your bags clog up in seconds.

**Branch(es)**:
As far as I know 335 only.

**TC hash/commit**:  
TrinityCore rev. a01fd5226757 2016-05-15 18:08:59 +0200 (3.3.5 branch) (Win64, Release)

**TDB version**:  
TDB 335.61 with updates to current revision

**Operating system**:  
Windows 10

**Comment by IzFrost** [comment]
Sorry, to clarify, the problem seems to be in the DB table creature_loot_template.

As an example I found for loot id 3100, the 'Chance' for the following items:

Disciple's Cloak (6514) is 35.93. 
Journeyman's Belt (4663) is 15.308

Both of those values are way too high. Not sure where they came from. 

To put it in perspective, in the same loot id the chance for Broken Boar Tusk (3171) is 32.451. So, when you kill an Elder Mottled Boar you have a higher chance of getting a Disciple's Cloak than you do of getting a Broken Boar Tusk. No way that's correct. Not sure where those values came from, but they need to be adjusted down quite a bit.

**Comment by Killyana** [comment]
You have to provide Items/npcs that must be fixed if there's others.
