### ISSUE TITLE
[6.x] Core/Command: Modify speed

### ISSUE THREAD

**Issue by Anddrw** [TrinityCore/TrinityCore#17130]
**Description**: Freezes the server 
http://pastebin.com/6brbqzMh (last server output before freeze)

**Current behaviour**: Tell us what happens
In-game command input `.modify speed 15` in map Pandaria = server freeze.
**Expected behaviour**: Tell us what should happen instead
Change movement speed.
**Steps to reproduce the problem**:
1. .tele Pandaria
2. .modify speed 15
3. x

**Branch(es)**: 6x  

**TC hash/commit**:  ede8f0c

**TDB version**:  6.04

**Operating system**:  W8.1

**Comment by Aokromes** [comment]
useless crashlog,

**Comment by Anddrw** [comment]
*Edited

**Comment by Ulduar** [comment]
Wrong time sync counter from player Goko (cheater?)
What does the cheater in this case?
Try using .modify speed <= 9

**Comment by Anddrw** [comment]
The server outputs `Wrong time sync counter from player Goko (cheater?)` if i only just teleport to Pandaria, without using `modify`.

http://pastebin.com/shdiBpUd

**Comment by Ulduar** [comment]
CMSG_DB_QUERY_BULK: [Player: Goko GUID Full: 0x08000400000000000000000000000005
Type: Player Entry: 0 Low: 5, Account: 4] requested unsupported unknown hotfix t

What is this hotfix interesting.

**Comment by MrSmite** [comment]
> What is this hotfix interesting

Along with the **Race (24) has wrong teamid (2) in DBC: wrong DBC files?**, it sounds like that player may be using modified MPQ files.

**Comment by Anddrw** [comment]
> Along with the Race (24) has wrong teamid (2) in DBC: wrong DBC files?, it sounds like that player may be using modified MPQ files.

Latest WoD client, untouched. Same for dbc/db2.

`Goko its a level 100 pandaren created by me without selecting a faction.`

**Comment by MrSmite** [comment]
> Latest WoD client, untouched. Same for dbc/db2.
> 
> Goko its a level 100 pandaren created by me without selecting a faction.

Hmm, that's interesting. I wonder if there's a problem with DBC parsing in the core.

Years ago I played around with trying to create a Night Elf Warlock in 3.3.5 and that was the same complaint I used to get in the logs.

**Comment by Shauren** [comment]
Nah, thats something specific to mop and newer versions, pandaren start as neutral race and at the end of starting zone you select faction (which overwrites player race to 25/26 depending on choice)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Shauren** [comment]
doubt it ever was
