### ISSUE TITLE
[3.3.5] DB / gameobject: missing localization for Deathknell signs

### ISSUE THREAD

**Issue by lyn1337** [TrinityCore/TrinityCore#17135]
core_version: rev. 2ae85d86d3d1 2016-05-13 23:20:47 +0200 (3.3.5 branch) (Unix, Release)
db_version: TDB 335.61

The gameobject_template_locale table (not sure why it isn't named locales_gameobject) is missing 2 of 7 entries (1638, 2035) for the Deathknell street name signs. 
This leads to the signs not being localized. (see screenshots) The issue applies to the core and db version specified above for me, but maybe 6x / others as well.

Tested Query: Yes
Suggested Fix:

```sql
DELETE FROM `gameobject_template_locale` WHERE `entry`="1638";
INSERT INTO `gameobject_template_locale` (`entry`,`locale`,`name`,`castBarCaption`,`VerifiedBuild`) VALUES (1638,'deDE','Todesend','',''),(1638,'esES','Camposanto','',''),(1638,'esMX','Camposanto','',''),(1638,'frFR','Le Glas','',''),(1638,'koKR','죽음의 종소리 마을','',''),(1638,'ruRU','Похоронный Звон','',''),(1638,'zhCN','丧钟镇','',''),(1638,'zhTW','喪鐘鎮','','');

DELETE FROM `gameobject_template_locale` WHERE `entry`="2035";
INSERT INTO `gameobject_template_locale` (`entry`,`locale`,`name`,`castBarCaption`,`VerifiedBuild`) VALUES (2035,'deDE','Todesend','',''),(2035,'esES','Camposanto','',''),(2035,'esMX','Camposanto','',''),(2035,'frFR','Le Glas','',''),(2035,'koKR','죽음의 종소리 마을','',''),(2035,'ruRU','Похоронный Звон','',''),(2035,'zhCN','丧钟镇','',''),(2035,'zhTW','喪鐘鎮','','');
```

Source:
Unfortunately, these values were just taken from another (working / localized) street sign. (GO 1639, see first scrot)
![entry_1639_ingame_44801](https://cloud.githubusercontent.com/assets/10338543/15278055/3379b0f0-1b13-11e6-9ac5-9792b8a8589d.jpg)
![entry_1638_ingame_44806](https://cloud.githubusercontent.com/assets/10338543/15278056/38e4a770-1b13-11e6-98df-e56398518d26.jpg)
![entry_2035_ingame_42977](https://cloud.githubusercontent.com/assets/10338543/15278057/3a19dbec-1b13-11e6-8b78-ca4bffbe02a0.jpg)

**Comment by tkrokli** [comment]
May I suggest some minor modifications to the SQL so it follows the TrinityCore codestyle? :)
```sql
-- Localized name for gameobject entry 1638 (English name "Deathknell")
DELETE FROM `gameobject_template_locale` WHERE `entry`= 1638;
INSERT INTO `gameobject_template_locale` (`entry`,`locale`,`name`,`castBarCaption`,`VerifiedBuild`) VALUES
(1638,'deDE','Todesend','',''),
(1638,'esES','Camposanto','',''),
(1638,'esMX','Camposanto','',''),
(1638,'frFR','Le Glas','',''),
(1638,'koKR','죽음의 종소리 마을','',''),
(1638,'ruRU','Похоронный Звон','',''),
(1638,'zhCN','丧钟镇','',''),
(1638,'zhTW','喪鐘鎮','','');

-- Localized name for gameobject entry 2035 (English name "Deathknell")
DELETE FROM `gameobject_template_locale` WHERE `entry`= 2035;
INSERT INTO `gameobject_template_locale` (`entry`,`locale`,`name`,`castBarCaption`,`VerifiedBuild`) VALUES
(2035,'deDE','Todesend','',''),
(2035,'esES','Camposanto','',''),
(2035,'esMX','Camposanto','',''),
(2035,'frFR','Le Glas','',''),
(2035,'koKR','죽음의 종소리 마을','',''),
(2035,'ruRU','Похоронный Звон','',''),
(2035,'zhCN','丧钟镇','',''),
(2035,'zhTW','喪鐘鎮','','');
```

**Comment by lyn1337** [comment]
@tkrokli ty! the last suggest you made is just like the sql updates are structured iirc.
