### ISSUE TITLE
[3.3.5] DB/Creature: Add flag guard Deathguard Elite

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#17147]
http://www.wowhead.com/npc=7980/deathguard-elite
```sql
UPDATE `creature_template` SET `flags_extra`=32768 WHERE `entry`=7980;
```
Branch(es): 3.3.5
TC hash/commit: d9dcbbc
TDB version: 335.61

Edit (DDuarte): Removed quotes around numbers

**Comment by tkrokli** [comment]
Additional info for other users who don't want to look it up (and don't know this already):
https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-flags_extra
```
32768	CREATURE_FLAG_EXTRA_GUARD	0x00008000
creature is a guard (Will ignore feign death and vanish)
```

**Comment by msoky** [comment]
so, this could be for all guards in game?

**Comment by Aokromes** [comment]
No, not all.
