### ISSUE TITLE
[3.3.5][Priest] Core/Spell: Mind Control not flagging PvP

### ISSUE THREAD

**Issue by adeutscher** [TrinityCore/TrinityCore#17143]
**Description**: Mind Control does not flag the caster for PvP when used against a PvP-flagged target. This makes for some very fun shenanigans in city sieges, but definitely isn't intended.

**Current behaviour**:

A player can cast Mind Control without being flagged for PvP. This only seems to apply to successful casts, as misses still flag the user for PvP.

**Expected behaviour**: 

A player will be flagged for PvP if they cast Mind Control on a flagged target.

**Steps to reproduce the problem**:

1. Make a character, and teach them Mind Control (Id: 605).
2. Cast Mind Control on a flagged target while ***not*** PvP flagged.

**Branch(es)**: 335

**TC hash/commit**:  b91bed0

**TDB version**:  335.61

**Operating system**:  Linux

I currently have a crude fix from copying the `UpdatePvP` call in `DoAllEffectOnTarget` to `AuraEffect::HandleModPossess`, but I am still looking into how to do this earlier in the chain. Not entirely happy with the current fix since PvP flagging isn't really dealt with anywhere else in `SpellAuraEffects.cpp`, so there must be a better way.

```cpp
// if target is flagged for pvp also flag caster if a player
if (target->IsPvP() && caster->GetTypeId() == TYPEID_PLAYER)
    caster->ToPlayer()->UpdatePvP(true);
```

**Comment by adeutscher** [comment]
Found a place that I'm a bit happier with in `Spell::DoSpellHitOnUnit`.

Currently leaving the nearby check within the `m_caster->IsFriendlyTo(unit)` block in place, as I don't understand `UNIT_STATE_ATTACK_PLAYER` at this moment and whether or not it would be different from checking the target's PvP state.

Submitting a PR shortly.

**Comment by Shauren** [comment]
e7a12edb833ffe26f27d6e392e97a560ffb0c827
