### ISSUE TITLE
[3.3.5][Paladin] Core/Spell: Spiritual Attunement Healing

### ISSUE THREAD

**Issue by adeutscher** [TrinityCore/TrinityCore#17142]
**Description**: Spiritual Attunement does not give the proper amount of mana when the paladin is topped off or brought "near-full".

**Current behaviour**:

Spiritual Attunement is calculating mana gain based on the minimum of the following values: The target paladin's missing health and the amount healed. When the paladin is healed such that their missing health is less than the heal's effect, then the mana returned from Spiritual Attunement is reduced.

For example (with 2/2 in the talent for an expected 10%):
* A 2000-strength heal that brings the paladin to 3000/4000 health would restore 100 mana (based off of the target's 1000 missing health).
* A 2000-strength heal that brings the paladin to 4000/4000 (1000 effective healing) would restore 0 mana.

**Expected behaviour**:

Spiritual Attunement should be granting mana based on effective healing. For example (with 2/2 in the talent for an expected 10%):

* A 2000-strength heal that brings the paladin to 3000/4000 health should restore 200 mana.
* A 2000-strength heal that brings the paladin to 4000/4000 (1000 effective healing) should restore 100 mana.

**Steps to reproduce the problem**:

1. Create a paladin on one account, and level them up enough to make Spiritual Attunement available on the talent tree.
2.  Create a class with a healing spell, and/or use GM powers to cast arbitrary spells.
3. Deplete the paladin's health and mana. I opted to duel my target. I used GM powers to use Shadow Blast (70866) for quick-and-lazy damage and an NPC's Mana Drain (69067) spell for mana draining.

**Branch(es)**: 335

**TC hash/commit**:  b91bed0

**TDB version**:  335.61

**Operating system**:  Linux

I have a fix for this ready to push up that is an import of my fix for OregonCore ( https://bitbucket.org/oregon/oregoncore/commits/590958a ), in which I moved the call to `ProcDamageAndSpell` up to before the applied heal in the healing spell section of `Spell::DoAllEffectOnTarget` and `AuraEffect::HandlePeriodicHealAurasTick` for HoTs. I wanted to create this issue to confirm any side effects before submitting the PR.

To confirm, are there any problems in the WotLK era that will come from healing procs being instead calculated before the actual heal?

By moving heal procs to just before the actual heal is applied, the mana return from Spiritual Attunement will appear **before** the heal in the Combat Log. Is this acceptable?

If moving up the proc call is not acceptable, the alternative that was discussed in OregonCore/OregonCore#1070 was to add an extra argument value to `ProcDamageAndSpell` in order to transmit effective healing (since SA is currently calculated off of the target's health post-heal, the effective of `gain` is not passed through). This was deemed too messy a change for OC compared to bumping `ProcDamageAndSpell` up a few lines.

**Comment by mik1893** [comment]
@Shauren is reviewing the proc system and this change will likely be included in the rework.
correct me if im wrong shauren - that's what we were discussing some days ago

**Comment by ariel-** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2ff585039b254297ed38b1f56328e066698e9958

This one was made to fix this
