### ISSUE TITLE
[6.x] Connection_Patcher currently not compatible

### ISSUE THREAD

**Issue by Illenium** [TrinityCore/TrinityCore#17156]
**Description**:

**Current behaviour**: It seems that the Connection Patcher is currently no longer compatible with the latest rev. (game version)

**Expected behaviour**: You should like before login into the game and let wow streaming data.

**Steps to reproduce the problem**:

1. Install World of Warcraft (new)
2. Patch Wow.exe with latest rev. Connection_Patcher
3. Start Wow_Patched.exe > ![screenshot](https://cloud.githubusercontent.com/assets/19361030/15380898/d4cf9406-1d7a-11e6-89c4-e9da8e194e7d.jpg)

**Branch(es)**: 6.x

**TC hash/commit**:  7cf22eab81ae012099c2ed9e50bb36b146175a76

**TDB version**:  TDB 6.04

**Operating system**:  Windows 10 (64 bit)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
We don't support  6.2.4.21676 yet.

**Comment by Illenium** [comment]
_Sir what is your problem?_

I just made a Issue Ticket and you closed it instantly, my question is:
**does TrinityCore use a specific downlod data urls from web which "just are currently outdated". ?**
