### ISSUE TITLE
[3.3.5] Level 80 quests give large amount of money

### ISSUE THREAD

**Issue by serfma** [TrinityCore/TrinityCore#17159]
**Description**: Level 80 quests give a large amount of money for some odd reason. I modified my config back to default values so that there would be NO modifier on quest money but the gold is still insanely high and incorrect. It seems to only occur when you're level 80 (max capped)

http://i.imgur.com/2c4wGg4.jpg
http://i.imgur.com/SL7QGMo.jpg

Yes, I reset my config back to defaults and did a .reload config, re-logged, and have restarted the server just to verify it wasn't the config. 

**Steps to reproduce the problem**:
1. Make a level 80 Blood Elf (any class, only tested BE)
2. Grab a quest in Northrend and look at gold amount
3. Accept quest and look at gold amount in log
4. When completing the quest sometimes it's increased even further.

**Branch(es)**: 3.3.5a

**TC hash/commit**: hash 02d7df6aa435

**TDB version**: 335.61

**Operating system**: Windows 10, 64-bit

**Comment by Aokromes** [comment]
Cannot confirm. Clean client cache.

**Comment by serfma** [comment]
It wouldn't be a client cache issue if I'm actually rewarded the additional money, would it? (as in seen in bags and able to use it)

**Comment by serfma** [comment]
Cleaned my client cache and issue still persists. It only occurs when I am level 80. If I am 79, quest does not give bonus gold. Tested with this quest: http://www.wowhead.com/quest=13039/defending-the-vanguard

`Rate.Quest.Money.Reward = 1
Rate.Quest.Money.Max.Level.Reward = 80`

Are set in the worldserver.conf and .reload config issued afterwards.

**Comment by Shauren** [comment]
Rate.Quest.Money.Max.Level.Reward = 80
well... you multiplied it yourself...

**Comment by serfma** [comment]
Lol ok now I see that it's the multiplier for gold earned when you're at the max level instead of the level when you stop getting bonus money from quests. Whoops. 

`Rate.Drop.Money` is this solely for monster drops or also quests? Because when modifying the money drop multiplier it changes how much gold is gained from completing the quest.

**Comment by tkrokli** [comment]
I believe that is exactly what Shauren pointed out, but OK. You closed the issue, so it's not a problem.
From `worldserver.conf.dist` (3.3.5)
```
(Line 2005)
Rate.Drop.Money                 = 1
```
vs
```
(Lines 2041+2042)
Rate.Quest.Money.Reward = 1
Rate.Quest.Money.Max.Level.Reward = 1
```

**Comment by serfma** [comment]
Yes, I resolved my issue with `Rate.Quest.Money.Max.Level.Reward` being multiplied thus the large amounts of money.

However, what I am now curious about is whether `Rate.Drop.Money` is actually supposed to change how much gold **quests** give rather than from mob drops as changing the value changes quest gold. Just verifying whether it's actually intentional since the var has "drop" in the name.

**Comment by tkrokli** [comment]
The intention of "Drop" should be to mean "loot from killed mobs or lootable objects", not quest rewards.
I don't know enough to reference where this distinction is located in the source code, though.

**Comment by serfma** [comment]
Yes I thought so, I just wanted to make sure it was not intentional as I was experiencing it while I changed around config settings. I'll do more testing in a few hours and if anyone can verify it's an actual issue and not yet another user error, that would be great. :)

**Comment by tkrokli** [comment]
TrinityCore rev. d8cc656ff404 2016-05-20 19:28:26 +0200 (3.3.5 branch) (Win64, Release)
TDB 335.61 + updates up to and including `2016_05_20_00_world.sql`

Cannot reproduce your issue with a default level 80 human mage leveled up by GM command (but with GM OFF as character status). Only got the default quest reward **6g 80s** from [Scourge Tactics](http://www.wowhead.com/quest=13008/scourge-tactics) + Level 80 extra reward **12g 96s** (Carbonite actually listed 12g 96s as reward while the quest was active/not rewarded, but the normal quest gossip still listed 6g 80s). Total sum of reward money for a level 80 without any extra faction reputation with the Argent Vanguard:  **19g 76s**

Let me know if you think this issue would depend on faction Horde vs Alliance, if I should test specifically with a horde character, although I doubt it will make any difference except for any extra faction reputation with the Argent Vanguard (or other specific reputation in case of other quest areas).

**Comment by serfma** [comment]
Hmm I just tested that exact quest and I'm having the issue still. You're changing `Rate.drop.money`, .reload config, then re-completing the quest with both 1 and then with modified value to verify, correct? I'll attempt to update to see if it fixes this.

**Comment by serfma** [comment]
Ok I've tested again with TrinityCore rev. 1e1fcd684761 2016-05-20 21:09:03 +0200 (3.3.5 branch) (Win32, Release), TDB 335.61 + including being fully updated to `2016_05_20_00_world.sql` while still having this issue. I used default `worldserver.conf`just to verify it wasn't a configuration issue, then tried changing `Rate.Drop.Money` with the same results of quest money being changed.

I also tested with a default lvl 80 Human Mage on the quest Scourge Tactics and does not seem to be related to specific quests as I've went to numerous other zones outside of Northrend to test.

**Comment by tkrokli** [comment]
Maybe it could be worth looking into the difference between `Rate.Drop.Money`, `Rate.Quest.Money.Reward` and `Rate.Quest.Money.Max.Level.Reward` using the default value 1 in all of them and setting a specific value for one of them to check the individual behaviour, but that probably won't be worth a new TC issue before it is possible to document unwanted behaviour between those 3 settings.

I don't know exactly when I get time to test that theory, so I would suggest a personal issue in your own TC fork (if you have got one) until you can document that the TC source should behave differently. Until then, this discussion should probably take a break from the TC pages. You are welcome to post it as an issue in my TC fork if you want to continue your research if you don't have your own fork yet.
