### ISSUE TITLE
Malloc: pointer being freed was not allocated

### ISSUE THREAD

**Issue by swerve** [TrinityCore/TrinityCore#17153]
Starting worldserver produces the following error: http://pastebin.com/xuMS0pcG

**Branch(es)**: 335 (rev. 6cf1446d39db 2016-05-17 17:47:55 +0200 (3.3.5 branch))

**TDB version**:  335.61

**Operating system**:  Mac OSX 10.11.5

**Comment by jackpoz** [comment]
Invalid crash report, clicking on the "New issue" button https://github.com/TrinityCore/TrinityCore/issues/new shows "Please review the guidelines for contributing to this repository.", do that.
