### ISSUE TITLE
[3.3.5] DB/Creature: Add missing Anvilrage Overseer Spell

### ISSUE THREAD

**Issue by lyn1337** [TrinityCore/TrinityCore#17178]
core_version: TrinityCore rev. f2527f1f5a86 2016-05-23 08:51:19 +0200 (3.3.5 branch) (Unix, Release)
db_version: TDB 335.61

**Related**: #17148
Note: Experienced on [3.3.5], [6.x] needs confirmation

**Description**:
Creature "Anvilrage Overseer" (entry: 8889) is missing 

**Current behavior**: 
Creature "Anvilrage Overseer" (entry: 8889) is missing spell "Strike" (ID: 15580)

**Expected behavior**: 
Creature "Anvilrage Overseer" (entry: 8889) should have spell "Strike" (ID: 15580) available, besides (SAI) scripts.

Source:
http://www.wowhead.com/npc=8889/anvilrage-overseer#controlled-abilities

Note: creature already has spell "Haste Aura" (ID: 13589) set up in `creature_template_addon`
(see `SELECT auras FROM world.creature_template_addon WHERE entry=8889;`)
This is sufficient, but could be added to spells as well ~ probably no good.

Suggested Fix:
Tested Query: Yes
```sql
UPDATE `creature_template` SET `spell1`=15580, `VerifiedBuild`=-12340 WHERE `entry`=8889;
```
Note on VerifiedBuild:
According to the wiki page about the table, I think it needs to be updated as well.
https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-VerifiedBuild

**Comment by Aokromes** [comment]
Adding spell to creature_template don't adds it to SAI.

**Comment by lyn1337** [comment]
> Adding spell to creature_template don't adds it to SAI.

@Aokromes wasn't the plan.
forgot to mention that spell "Strike" (ID: 15580) has absolutely no CD at all. If this is how the spell should work, then the issue needs to be closed, since the creature can be mindcontrolled.

**Comment by Killyana** [comment]
The spell is used by the SAI.
