### ISSUE TITLE
 [BUG] Mounts with vendors #9235 

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17170]
**Description**:  [BUG] Mounts with vendors #9235 

**Current behaviour**: Dismount - traders are still on the ground (not despawned) - BUG

**Expected behaviour**: Traders which mast be on both side of the mammoth are spawned on ground and Dismount - traders are still on the ground (not despawned) - BUG

**Steps to reproduce the problem**:

1. Mount on Traveler's Tundra Mammoth http://www.wowhead.com/spell=61447
2. Traders which mast be on both side of the mammoth are spawned on ground
3. Dismount - traders are still on the ground (not despawned) - BUG

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:   1e1fcd6

**TDB version**:  3.3.5/61

**Operating system**:  Linux Ubuntu 16.04

@Aokromes Fixed on 0049e58
This issue has not been fixed correctly. Please reopen #9235 or close this ticket. 

Screenshot: http://img.prntscr.com/img?url=http://i.imgur.com/eB7KEsJ.jpg

**Comment by Aokromes** [comment]
.gm off
.gm visible on

**Comment by Cryselia** [comment]
@Aokromes https://stopthesethings.files.wordpress.com/2015/01/head-slap-e1422073197264.jpg

**Comment by Aokromes** [comment]
https://onedrive.live.com/redir.aspx?cid=83725776ab2e4745&resid=83725776AB2E4745!1805&parId=83725776AB2E4745!143&authkey=!ADf_xyPqFoW0efg&ithint=video%2cmp4
