### ISSUE TITLE
Stack Auras bug

### ISSUE THREAD

**Issue by JudgeGM** [TrinityCore/TrinityCore#17175]
Hello TC
I have encountered with a really odd bug 
Retribution aura is not stacking with Improved Moonkin form with Arcane Empowerment and with Swift Retribution
1. Get mage and druid and paladin level 80
2. Raise mage arcane with Arcane Empowerment , And Balance druid with Improved Moonkin form
3. Group them up together and try to use Retribution aura

Related Links 
http://wotlk.openwow.com/spell=31583
http://wotlk.openwow.com/?spell=48396
http://wotlk.openwow.com/spell=7294 - Retribution - Rank 1
http://wotlk.openwow.com/spell=54043 - Retribution - Rank 7
**Branch(es)**: 3.3.5 

**TC hash/commit**:  7c8c3b96fe20+

**TDB version**: TDB 335.61

**Operating system**:   64Bit

**Comment by Shauren** [comment]
This is because Retribution Aura has +damage and +haste effects on by default with 0 value, selecting Swift Retribution increases the value to 3% (but its set to not stack with Improved Moonkin Form) and selecting Sanctified Retribution modifies the +damage effect value to 3% (and this one doesn't stack with Arcane Empowerment)

**Comment by BlackangelWow** [comment]
Well but it means that You can use the effect of ret aura? it means you cannot use ret aura because its give you value of 0%?

**Comment by BlackangelWow** [comment]
As far as i know it shouldnt be like that , and there is a list of spell of interfere with Retribution Aura

**Comment by Shauren** [comment]
No, it shouldn't, I just gave a more detailed description on why this happens

**Comment by BlackangelWow** [comment]
Okay , thanks you very much !
