### ISSUE TITLE
[Crash] CharmInfo::IsAtStay

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17176]
**Branch(es)**: 3.3.5

**TC hash/commit**:  8ef9ea9157ca6c04194888a2118be7daf303856f

**TDB version**:  59

**Operating system**:  Linux debian

https://gist.github.com/Runico/4e70eb42d96f562a3daed84e0569724d

**Comment by Aokromes** [comment]
Plz update your core before reporting bugs.

**Comment by PiskelDEV** [comment]
I recommend the same, dont take it personally :+1:

**Comment by jackpoz** [comment]
was there anything in the console about an unhandled exception ?

**Comment by Aokromes** [comment]
deleted crashlog, closing.

**Comment by tkrokli** [comment]
Yes, the user https://github.com/Runico (@Runico) does not exist anymore.
