### ISSUE TITLE
[3.3.5][Crash] Player::DuelComplete

### ISSUE THREAD

**Issue by xjose93** [TrinityCore/TrinityCore#17177]
**Branch(es)**: 3.3.5

**TC hash/commit**:  0fbfa8ead04a59f3eef70f4f2e454e318d895bd9 (not exactly this hash on crashes because they are older, but normally is up to date)

**TDB version**:  335.60

**Operating system**:  Debian GNU/Linux 8 (jessie)

**Steps to reproduce the problem**: no idea about how to reproduce them.

https://gist.github.com/xjose93/d788074187f2133af43e221b93954789
https://gist.github.com/xjose93/2e65320651302d9ec1c8a5b84729ce17
https://gist.github.com/xjose93/efe586c0116668163e336a32b5df1ec7

I didn't see any issue open related to this crash so i open it.
It's not very usual crash it happens like 1 time per month.

**Custom things**: some custom fixes, transmog, cfbg, anticheats.

**Comment by Treeston** [comment]
Code in question:
````c++
    /* remove auras */
    AuraApplicationMap &itsAuras = duel->opponent->GetAppliedAuras();
    for (AuraApplicationMap::iterator i = itsAuras.begin(); i != itsAuras.end();)
    {
        Aura const* aura = i->second->GetBase();
        if (!i->second->IsPositive() && aura->GetCasterGUID() == GetGUID() && aura->GetApplyTime() >= duel->startTime)
            duel->opponent->RemoveAura(i);
        else
            ++i;
    }
```
`RemoveAura` takes references and properly handles advancing iterator after deletion, so iterator invalidation is not the cause.

Stack trace seems to show `i->second` possibly being null. Is it possible for there to be a null pointer in `AuraApplicationMap`?

**Comment by Shauren** [comment]
@Treeston  No.

**Comment by jackpoz** [comment]
as usual: what's your MapThread config in worldserver.conf ?

**Comment by xjose93** [comment]
1

**Comment by xjose93** [comment]
https://gist.github.com/xjose93/b3563cc34fe0e20a0ecd200e55986ea8 here is a new crashlog, its incomplete (i don't know why) but it adds something new and different to other crashlogs:

``#9  0x000000000168911a in spell_mage_living_bomb::spell_mage_living_bomb_AuraScript::AfterRemove (this=<optimized out>, aurEff=0x6f78550762c0) at /home/wow/335/source/tc335/src/server/scripts/Spells/spell_mage.cpp:500
        caster = 0x6f780ab40000
        removeMode = <optimized out>``

**Comment by Treeston** [comment]
Still hard to say anything, especially considering how many variables are optimized out of your stack traces.

Could you run a binary that's compiled without optimizations and see if that results in more informative crash dumps?

**Comment by jackpoz** [comment]
>jackpoz: looks like living bomb expired, got removed, killed the player, ended duel and started iterating spells
shauren: oh so like double remove of the same aura?
shauren: just slap a if (aurApp->GetRemoveMode()) { continue; } to that aura loop and done

**Comment by Treeston** [comment]
Great catch.

**Comment by Treeston** [comment]
```
<Shauren> Treeston: damn, you were not here when we discussed it
<Shauren> Treeston: this commit does nothing. remove mode is also checked inside RemoveAura
```

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/7ff0f3c65fd0c068560351eac92e96a8527c96a7

**Comment by jackpoz** [comment]
does this still happen ?

**Comment by xjose93** [comment]
It was happening like every month (not always), so if you want we can close it and if that keep happening i'll reopen it.
