### ISSUE TITLE
[3.3.5][Crash] Player::GetCollisionHeight

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17174]
3.3.5
https://github.com/TrinityCore/TrinityCore/commit/6cf1446d39db994cdca2db8f7f61da8423672bb3

http://paste.ubuntu.com/16565492/
http://paste.ubuntu.com/16641633/

in my crash log

Mount (this=0x7fffa4204000, mount=14578, VehicleId=0, creatureEntry=14549

mount 14549 [Great Brown Kodo]
3x crash with this entry

some issue like this
https://github.com/TrinityCore/TrinityCore/issues/15943

**Comment by Ovahlord** [comment]
ure using custom mounts or something like that ?

**Comment by SQLfix** [comment]
no .. 
This is just for creatureEntry=14549 
All crash with this entry

**Comment by Shauren** [comment]
Two things: 
* Line 26472 is nowhere close to Player::GetCollisionHeight in 3.3.5 (CUSTOM CHANGES)
* The assertion is on PLAYERS model, not the mount - `CreatureDisplayInfoEntry const* displayInfo = sCreatureDisplayInfoStore.LookupEntry(GetNativeDisplayId());`
Stop messing with native display id (CUSTOM - nothing in our codebase sets nativedisplayid for players except creation, and then it uses DBC values)

**Comment by SQLfix** [comment]
i have Crossfaction BG / Transmogrifier 
i think this is for [Crossfaction] . true ?

**Comment by Nawuko** [comment]
I think i have a Déjà vu. Some guy, this or last week, had the EXACT same crash and the same custom shitty/hacky patches and got the EXACT same answer from the TC-Devs.

Please dont open issue with custom patches. Use stock TC and check if the problem still persists afterwards you are very welcome to open an issue. Or atleast be kind enough and write any custom changes into the issue so no dev waste their time.

**Comment by SQLfix** [comment]
thanks @Shauren  I think my problem from crossfaction and like this lines
https://gist.github.com/irancore/10913800#file-gistfile1-diff-L619
