### ISSUE TITLE
[3.3.5] Opening the Dark Portal dungeon

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#17187]
I've seen 2 old issue about this but they are closed.
Finally yesterday i played this cool dungeon but...

Portal with twilight dragons opens and... enemy stay there

Instead they should attack Medivh if i remember correctly. The super weird stuff is if you don't attack these enemies spawning from the dark portal, Medivh shield goes down, it seems that enemies attack medics from the portal. I could remember wrong but it seems strange thaty can attack modish from so far away. I remember they get closer.
Also at the end of the dungeon no script/animation of opening the portal. Medivh stay there wondering why no orcs are coming ah ah ah

Just try to play this DG

1. do the pre req quest
2. go to black morass from Caverns of Time

Tested in 3.3.5

trinity core: 6cf1446

DB 335.61

**Comment by Aokromes** [comment]
#4613
