### ISSUE TITLE
[3.3.5] Spell: Mind Controled players dont return to normal speed when mind control expire

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17184]
**Description**: Mind controlled players give permanent slow , if some "slow aura" is removed during control period.

**Current behaviour**: Player A control Player B using Mind Control. Player C add Slow on Player B. Before Mind Control in Player B finalize, slow appled by Player C expire. When Mind Control in Player B expire, Player B has no slow auras, but he cant run in normal speed. like "slow effect" stuck on him.

**Expected behaviour**: After mind control expire, the controlled player should run in normal speed.

**Steps to reproduce the problem**:

1. Create Character 1, learn spells (.learn  605, .learn  31589) - Mind Control and Slow
2. Create Character 2 and Put Character  1 and Character 2 in Duel.
3. On character 1, use slow in character 2 (waiting some time, because time of slow > time of mind control) and for reproduce it, slow need expire before mind control.
4. After mind control expire, look "move speed" of Character 2.

**Branch(es)**: 3.3.5 
**TC hash/commit**:  862d068cdeba73095840506493cf3335cde711c3

**TDB version**:  335.61

**Operating system**:  Win10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Rhisk** [comment]
No need use a slow spell, you can use this for reproduce the problem.
1. Create Character 1 and learn spell Mind Control
2. Create Character 2 and Put Character 1 and Character 2 in Duel.
3. When controling character 1 press the run/walk key and change character 1 to walk mode.
4. After Mind Control expire, the character 2 continue in walk mode.

**Comment by Keader** [comment]
@Rhisk but in this case, just press "run/walk" key you can return normal speed, no?
In slow case, only speed mods (sprint, dashs, nitroboots, mounts, any 'speed up) remove the 'ghost slow'

**Comment by Rhisk** [comment]
Yes, but in both cases the problem that the 2nd characters does not return to normal speed when the Mind Control expire occurs. And I'm sure that not all players will realize that the slowness of her character is because is changed to walk mode.

**Comment by Keader** [comment]
yeap, make sense
same bug i tink

**Comment by myran2** [comment]
Maybe try calling UpdateSpeed(MOVE_RUN) and UpdateSpeed(MOVE_WALK) inside the `if (Player* player = ToPlayer())` block of `void Unit::RemoveCharmedBy(Unit* charmer)`?

**Comment by Keader** [comment]
@myran2 dont work for slow case.

**Comment by Keader** [comment]
Using  ```std::cout << "player move is: " << player->GetSpeed(MOVE_RUN) << "\n";``` in same spot, when "has move speed bug" and just controlling (wihout slow) always GetSpeed(MOVE_RUN) return the value 7.

**Comment by myran2** [comment]
Just to confirm, the issue here is that if a player has a movespeed effect on them while they are mind controlled, the effect won't go away if the effect expires before the mind control ends?

**Comment by Keader** [comment]
Yes

**Comment by Keader** [comment]
More Info: When you is bugged (has eternal slow), trinkets pvp dont remove.
But, spells that change your move speed "solve" your problem. Spells like: Sprint (Rogues), Feral Dash (Druids)... etc
In my testes i using spell 31643 = [Blazing Speed]

**Comment by Treeston** [comment]
I have two fixes for this, depending on what packet sniffs say player should get.

If they should get `SMSG_FORCE_X_SPEED_CHANGE`:
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 2aa3237..0a28ed8 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -12049,6 +12049,8 @@ void Unit::SetSpeedRate(UnitMoveType mtype, float rate)
             self << uint8(1);                               // unknown byte added in 2.1.0
         self << float(GetSpeed(mtype));
         m_movedPlayer->GetSession()->SendPacket(&self);
+        if (m_movedPlayer != ToPlayer())
+            ToPlayer()->GetSession()->SendPacket(&self);
 
         // Send notification to other players. sent to every clients (if in range) except one: the client of the player concerned by the change.
         WorldPacket data;
```

If they should get `MSG_MOVE_SET_X_SPEED`:
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 2aa3237..8f11feb 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -12056,7 +12056,7 @@ void Unit::SetSpeedRate(UnitMoveType mtype, float rate)
         data << GetPackGUID();
         BuildMovementPacket(&data);
         data << float(GetSpeed(mtype));
-        SendMessageToSet(&data, false);
+        SendMessageToSet(&data, m_movedPlayer != this);
     }
     else // unit controlled by AI.
     {
```

**Comment by Keader** [comment]
Both fix works, but we (me and sirikfoll) cant sniff it on blizz.
Based on sniff for our server, controlled player never receive SMSG_FORCE_RUN_SPEED_CHANGE or MSG_MOVE_SET_RUN_SPEED only control player (charmer player) receive it.
causing this issue.

**Comment by Treeston** [comment]
As per IRC, that entire branch is wrong:
```
<Shauren> ah the classic mover vs this issue
<Shauren> ill give you more mindfuck
<Shauren> it also depends on who controls the player
<Shauren> if its a creature then the movement is server controlled and only a single packet should be sent as broadcast - the SPLINE variant
<Treeston> it is
<Treeston> it checks m_movedPlayer
<Treeston> which should really be called m_moverPlayer tbf
<Shauren> no, it should not
<Shauren> you are confusing 2 things here
<Shauren> Player::m_mover - the unit that controls the player (charmer for you)
<Shauren> and Unit::m_movedPlayer - the player who is being controlled, on charmers side
<Shauren> the name is 100% correct and reflects its purpose
<Shauren> for anything movement related, use m_mover
<Treeston> hmm
<Treeston> is it just me or is current TC wrong then
<Treeston> check packet code in unit::setspeedrate
<Treeston> it sends to m_movedplayer if it exists
<Treeston> if unit speed is changed
<Treeston> shouldn't that be "sends to m_mover if it's a player (and exists) and speed is changed"?
<Shauren> yes it is wrong
```

**Comment by Treeston** [comment]
See #17254
