### ISSUE TITLE
[3.3.5] Aggro range

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#17181]
**Description**: Aggro range is higher than it should.
Previous discussion on this matter https://github.com/TrinityCore/TrinityCore/pull/15852#issuecomment-155795793

**Current behaviour**: Aggro range is about twice bigger than it should. [video](https://youtu.be/4wCRrCgfdP0)
Approximate with .dist command "The distance is: (3D) 22.755482 (2D) 22.754154 (Exact 3D) 44.505482 (Exact 2D) 44.504154 yards."

**Expected behaviour**: Aggro range should be smaller, example: [video](https://www.youtube.com/watch?v=zFTceGrZIVk)
Aprroximate with .dist command "The distance is: (3D) 0.000000 (2D) 0.000000 (Exact 3D) 17.817280 (Exact 2D) 17.817280 yards."

**Steps to reproduce the problem**:
1.  Go to Lord Marrowgar, step into the room and check the distance he aggro.

**Branch(es)**: 3.3.5

**TC hash/commit**:  0fbfa8ead04a

**Comment by DDuarte** [comment]
Doesn't level matter?

**Comment by sirikfoll** [comment]
not sure,just checked with a level 80, to match the retail video

**Comment by Lopfest** [comment]
Aggro range is also bigger on 6.x on Wandering Isle. I would say almost tripple time bigger

**Comment by ccrs** [comment]
the problem usually is the model size, instead of the aggro range

**Comment by Lopfest** [comment]
@ccrs Do you mean scale in creature_template, or something related to creature_model_info?
And if both of those things are correct (from sniffs) and aggro range is still bigger than it should be? =p

**Comment by ccrs** [comment]
If both things are correct and checked, maybe its the core handling what is failing.

**Comment by Killyana** [comment]
Must be fixed once https://github.com/TrinityCore/TrinityCore/commit/ea99801cd6ff687462df4fdbb69c06071dedfcf0  cherry picked

**Comment by Wyrserth** [comment]
Fixed in 980047763a685217e712f58b8713d48523d90ccb.
