### ISSUE TITLE
[3.3.5] Enraged Spirits of Fire and Earth

### ISSUE THREAD

**Issue by ikir83** [TrinityCore/TrinityCore#17183]
the quest says you must kill Enraged elemental so in totem proximity, and you have an object to summon totem

totem is following you and sometimes stop and get bugged. I see a totem in the same position since 2 days

totem should stay where planted

**Steps to reproduce the problem**:
1. Take the quest
2. Use the item
3. Totem will follow you

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

trinity core: 6cf1446d39db

DB 335.61

**Comment by tkrokli** [comment]
When referring to a quest, it is useful to include quest ID or links to the quest page. Is this one correct?
http://wotlk.openwow.com/quest=10458
http://www.wowhead.com/quest=10458/enraged-spirits-of-fire-and-earth

**Comment by ikir83** [comment]
Yes sorry i usually link quest, it was late and i was sleepy ah ah ah

Also the followup quest (water and air elemental) have the same issue with totems

**Comment by Rushor** [comment]
try to add unitflag 4 in creature_template

**Comment by offl** [comment]
```sql
--
DELETE FROM `creature_template_movement` WHERE `CreatureId` = 21071;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`) VALUES
(21071,1,1,0,1,0,0);
```
> totem is following you and sometimes stop and get bugged. I see a totem in the same position since 2 days

Cannot confirm this part with or without the fix. But I tried only several times

```text
[22:08] <Killyana> It sounds like an old issue where summoned npcs with timer get bugged if they despawn inside an inactive grid
[22:08] <Killyana> this get fixed I think
```
