### ISSUE TITLE
SetCanFly(false) don't remove flying ability

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#17199]
**Description**: .gm fly on command does not remove flying ability

**Current behaviour**:  .gm fly on command does not remove flying ability for players to rank 0. Works perfectly with a rank of account> 0

**Expected behaviour**: SetCanFly(false) remove  flying ability for players

**Branch(es)**: 6.x (maybe also on 335 branch)

**TC hash/commit**:  cd51e27

**TDB version**:  TDB  6.04

**Operating system**:  Linux debian latest revision

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
you must use gm fly OFF. and works as intended on 4ebed6e586b0 (3.3.5a).

**Comment by Pixel-Pirate** [comment]
No it's not work is you use and no gm account.

**Comment by lyn1337** [comment]
core_version: TrinityCore rev. 4a074ca47085 2016-05-26 16:15:27 +0200 (3.3.5 branch) (Unix, Release)
db_version: TDB 335.61

Works as it should on all account levels.

**Comment by tkrokli** [comment]
I recently had to empty my entire DB because of some file read/write errors, so I started off with a completely empty `auth` and `characters` DB. What I noticed at first, is that it is not enough to only use the commands
```
TC> account create tkrokli PaSsWoRd
Account created: tkrokli
TC> account set gmlevel tkrokli 3 -1
Security level of account TKROKLI changed to 3.
```
I also added `auth`.`rbac_account_permissions`.`permissionId` 194,195,197,198,199 (not sure if all were needed, but I took that chance to make sure I had access to all GM commands). Anyway, after I got all the needed GM commands, `.gm fly on` **works as intended on 3.3.5** (I should probably have researched this a bit better, but I was in a hurry at that time to test some bugged quests and find other solutions).

**Comment by Pixel-Pirate** [comment]
It's working as well with GM account but if your switch your account to rank 0 and if you give commande .gm fly to rang 0 or only for your account as you want, you will not be able to use gm fly off.

**Comment by lyn1337** [comment]
```
# id, name
373, Command: gm fly

```
is the permission needed. (also the one my test was based on)
.gm fly on / .gm fly off  both worked for me.

> TC> account set gmlevel tkrokli 3 -1

gmlevel must be 0

@tomrus88 "latest" isn't a valid db_version.
https://trinitycore.atlassian.net/wiki/display/tc/The+Issuetracker+and+You
See "What constitutes a proper version/revision?"

**Comment by Pixel-Pirate** [comment]
@lyn1337 I have update it :) DB version is TDB 6.04

**Comment by tkrokli** [comment]
OK, so I have dropped all my 6.x DBs and rebuilt them to be sure there is only default content. Checking in SQLyog, the command `.gm fly` has `id 373` in `rbac_permissions`, is linked to `id``196` in `rbac_linked_permissions` and is available only to `id 192` in `rbac_linked_permissions` and `secId``3` in `rbac_default_permissions`. As long as `.gm fly` is a self-cast command only, it should work only if you have access to the command 373 either via `id 192`(gmlevel 3), `id 196` or setting it directly in `rbac_account_permissions`. Should be working as intended. Have I missed something?

**Comment by Pixel-Pirate** [comment]
no all is ok. The command work as well with all gm account but if I give this commande to an player account with rbac_account_permissions table, for exemple, player can't stop flying with gm fly off.

**Comment by tkrokli** [comment]
OK, then I can test if I can replicate your issue based on that. BRB after a new compile & testing.

**Comment by lyn1337** [comment]
@Pixel-Pirate This is exactly what I reproduced in my first post. For 335, as stated.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 258368a2bd0e
