### ISSUE TITLE
[CRASH] GameObjectModel::intersectRay

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17192]
**Branch(es)**: 3.3.5

**TC hash/commit**:  8ef9ea9157ca6c04194888a2118be7daf303856f

**TDB version**:  59

**Operating system**:  Debian 64

https://gist.github.com/Runico/dce17e589fe123d898ae11038091d395

**Comment by Aokromes** [comment]
Again, update your core before reporting crashes.

**Comment by PiskelDEV** [comment]
Déjà-vu

**Comment by sucklifex** [comment]
http://paste.ubuntu.com/21747540/

Commit: 5868509a6366d0ba7a0fe819c3ece0e4a57c7029

this crash happens in icc gunship battle

**Comment by Aokromes** [comment]
near 1 year since the last crashlog, if this bug is still valid post one NEW ticket with updated core.
