### ISSUE TITLE
DB/Quest: Tree's Company, wrong RewardText

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#17190]
**Description**:
http://www.wowhead.com/quest=9531/trees-company
Quest ID 9531 "Tree's Company" has currently got wrong `quest_offer_reward`.`RewardText`, it is a duplicate of the `quest_template`.`QuestDescription` content. To compare the texts, use these 2 queries:
```sql
SELECT `RewardText` FROM `quest_offer_reward` WHERE `id`= 9531;
SELECT `QuestDescription` FROM `quest_template` WHERE `id`= 9531;
```

**Current behaviour**: Tell us what happens

Instead of the correct text, the the quest completion gossip shows the following text:

![tree s company](https://cloud.githubusercontent.com/assets/4903600/15583278/7d9c1456-2375-11e6-9919-4b2896152f48.png)

**Expected behaviour**: Tell us what should happen instead

The correct `quest_offer_reward`.`RewardText` should look like this:

![tree s company correct text](https://cloud.githubusercontent.com/assets/4903600/15583683/256cea74-2377-11e6-8f7c-fb1faddcfd1c.png)

**Steps to reproduce the problem**:

1. Use an alliance character, preferably Draenei. Go to Admiral Odesyus: `.go creature id 17240`
2. `.quest add 9531` and `.quest complete 9531`
3. Open the quest gossip, click [Continue] to see the quest completion page (Reward text).

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

I have only found this on 3.3.5 so far, I have not checked if it is the same on 6.x.

**TC hash/commit**:  rev. fb0881398a10 2016-05-26 10:56:50 +0200 (3.3.5 branch) (Win64, Release)

**TDB version**:  335.61 + updates up to and including `2016_05_26_01_world.sql`

**Operating system**:  Windows 10 Home edition (x64) version 1511 (OS Build 10586.318)

**Suggested solution:**
```sql
UPDATE `quest_offer_reward` SET `RewardText`= "I can't believe it!  It was the gnome all along...  I should have known!" WHERE `id` = 9531;
```
This solution is tested on TDB 335.61 and it produces the "Expected behaviour" shown above.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
Thanks for the commit. I just checked TDB 6.04 (without updates) and it appears to be correct there:
```sql
SELECT `RewardText` FROM `quest_offer_reward` WHERE `id` = 9531;
```
```
RewardText
------------------------------------------------------------------------
I can't believe it! It was the gnome all along... I should have known!
```
I will add [3.3.5] to the issue title so it becomes more apparent.

**Comment by Kittnz** [comment]
Alright, ill change it to _355 this evening.

**Comment by Aokromes** [comment]
well it won't hurt like this.

**Comment by tkrokli** [comment]
@Kittnz : I don't think it matters much, since you put `2016_05_26_08_world.sql` inside the /3.3.5/ folder.
