### ISSUE TITLE
DB/Quest: fix wrong questgivers for the "beached animal bones" quests in Darkshore

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17202]
**Description**: most (8 out of 9) of [those](http://wotlk.openwow.com/?search=beached+sea) quests have the wrong gameobject as questgiver. Easy to notice with the addon "Carbonite", but most of them can be found on Wowhead too.

**Branch(es)**: 3.3.5

**TC hash/commit**:  71081c2

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `gameobject_queststarter` WHERE `quest` IN (4722,4723,4725,4727,4728,4730,4731,4732,4733);
INSERT INTO `gameobject_queststarter` VALUES
(176190, 4722),
(175233, 4723),
(176197, 4725),
(176196, 4727),
(175226, 4728),
(175227, 4730),
(176198, 4731),
(176191, 4732),
(175230, 4733);
```

4722 had the right one to begin with, but I still put in in the query. Feel free to remove it if you really want to.

**Comment by tkrokli** [comment]
Looks good, just a minor TC codestyle detail (if you don't mind): add back ticks around column names:
```sql
DELETE FROM `gameobject_queststarter` WHERE `quest` IN (4722,4723,4725,4727,4728,4730,4731,4732,4733);
INSERT INTO `gameobject_queststarter` VALUES
```
(and sorry, no, I have not had time to test your fix yet, been too busy today with other things)

**Comment by SnapperRy** [comment]
Added backticks in the other issue (Sealed Vial of Poison), since someone already edited it here (thanks!). I often forget about them :P haven't got it on the keyboard, so had to google for them (and for using SQL syntax here, too). Got to remember ALT+96!
