### ISSUE TITLE
DB/Achievement: fix criteria for statistic "critters killed"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17201]
**Description**: creature type for criteria_id 4958 (critters killed) is set to 12 (non-combat pets). As such, counter is not increased when killing actual critters (creature type 8).

**Steps to reproduce the problem**:

1. Kill a critter.
2. Check statistics tab in achievements window for the "critters killed" statistic.

**Branch(es)**: 3.3.5. Not sure if this affects 6.x too.

**TC hash/commit**:  latest (kidding, kidding! 71081c2)

**TDB version**: 335.61

**Suggested fix**:
```sql
UPDATE `achievement_criteria_data` SET `value1`=8 WHERE `criteria_id`=4958 AND `type`=8;
```

**Comment by joschiwald** [comment]
looks correct

**Comment by tkrokli** [comment]
Good find, I never got around to test any of the general critter kills achievements on TC except for special cases with other types of critera, like the "Friend or Fowl?" Achievement -- Slay 15 turkeys in 3 minutes. ;)
