### ISSUE TITLE
DB/Quest: Sealed Vial of Poison should be repeatable

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17203]
**Description**: the quest [Sealed Vial of Poison](http://www.wowhead.com/quest=13845/sealed-vial-of-poison) from the [related item](http://www.wowhead.com/item=46004/sealed-vial-of-poison) should be repeatable ([source](http://www.wowhead.com/item=46004/sealed-vial-of-poison#comments:id=714015)).

**Current behaviour**: Right now, the quest is not repeatable, and the item cannot be received more than once (there's a condition for that).

**Branch(es)**: 3.3.5 (not sure if this applies to 6.x too).

**TC hash/commit**:  71081c2

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `SpecialFlags` = 1 WHERE `Id` = 13845;

DELETE FROM `conditions` WHERE `SourceEntry` = 46004 AND `SourceTypeOrReferenceId` = 10;
```
This fix also amends part of 81dab5b.

**Comment by tkrokli** [comment]
Nice find again, thanks for providing the fix (sorry, haven't tested it yet). http://www.wowhead.com/item=46004/sealed-vial-of-poison#comments:id=1006600 is even better as information source, because the confirming user reply got upvoted by other wowhead users.

**Comment by SnapperRy** [comment]
Right, that source is better. The more the merrier.

So yep, fix should be valid for 6.x too. It seems that it should give gold [and reputation too](http://www.wowhead.com/quest=13845/sealed-vial-of-poison#comments:id=2273848).
