### ISSUE TITLE
Should quest giver Lurielle (24117) be attackable by players?

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17215]
**Description**: title says it all. It seems strange that a neutral quest giver is attackable. Or atleast, this is common sense on my part. I don't remember her being attackable (although her "sisters" are) when I played retail. On Wowhead nobody says anything about her being directly attackable, only during what seems like a bug that was later fixed (again, not sure). Would appreciate someone with access to retail confirming if that's the case or not (still, it's a very minor bug).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  71081c2

**TDB version**:  335.61

**Suggested fix** (in case it's actually a bug):
```sql
UPDATE `creature_template` SET `unit_flags`=256 WHERE `entry`=24117;
```

**Comment by tkrokli** [comment]
http://www.wowhead.com/npc=24117/lurielle#comments:id=862031 - seems it used to be like this in retail.

**Comment by SnapperRy** [comment]
That seems to apply only to the sisters, though. I'm acting on memory here, but I remember them being attackable while the quest giver was not. That's why I'd like confirmation.

I think people would have written at lengths just how they can bother other people by killing the (neutral, without an associated faction) questgiver over and over. But I might be wrong, too.
