### ISSUE TITLE
[Spell] Deadly Poison

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#17219]
**Description**:Deadly poison consumed by crippling poison , as far as i know it should be like that , they just should stack together Deadly poison damage the target and crippling poison slowing the target

**Current behavior**: Deadly poison consumed by crippling poison

**Expected behavior**: Should stack together
**Steps to reproduce the problem**:
1. Get rogue level 80 
2. Use Poisons : Deadly and Crippling poison
3.auto attack dummy  

Ive checked it again , and Wound poison is consuming Deadly poison as well

Related Links : 
http://www.wowhead.com/spell=2823/deadly-poison
http://www.wowhead.com/spell=8679/wound-poison
http://www.wowhead.com/spell=3408/crippling-poison

**Important info**
If the rogue is using the talents Deadly Brew in Assassination 
http://wotlk.openwow.com/spell=51625 - rank 1 
http://wotlk.openwow.com/spell=51626 - rank 2

Means that when you using Instant poison it turns to Crippling poison and its canceling Deadly poison as well

**Branch(es)**: 3.3.5 

**TC hash/commit**:  80fc9cce81dc+

**TDB version**:  TDB 335.61

**Operating system**:   64bit

**Comment by BlackangelWow** [comment]
Ive checked it again , and Wound poison is consuming Deadly poison as well

Related Links : 
http://www.wowhead.com/spell=2823/deadly-poison
http://www.wowhead.com/spell=8679/wound-poison
http://www.wowhead.com/spell=3408/crippling-poison

**Comment by Killyana** [comment]
Need confirmation.

**Comment by BlackangelWow** [comment]
Like video or something like that?
