### ISSUE TITLE
[3.3.5] Loot rights issue

### ISSUE THREAD

**Issue by roc13x** [TrinityCore/TrinityCore#17211]
**Description**: Players who were not present (or even in the group) for a boss kill can still obtain loot from it. This works for Free-for-all and Master Loot modes. After a boss is killed, a new player can be invited to the group and enter the instance. This new player can then be assigned loot from the dead boss (ML), or loot it themselves (FFA).

**Current behaviour**: Players who were not present at a kill can get loot from it if they are invited after it is killed.

**Expected behaviour**: Players who were not present at a kill should never be able to obtain loot from it in any way.

**Steps to reproduce the problem**:

1. Create a group with 2 players, set loot mode to Master Loot. Enter a raid and kill a boss.
2. Now invite a third player to the group, and have them enter the instance.
3. Assign loot from the dead boss to the new player. It works, but it shouldn't.

**Branch(es)**: 3.3.5 (not tested on 6.x)

**TC hash/commit**:  70b89adcbe9cff7257892aa6848130c851373042

**TDB version**: 335.61

**Operating system**: Debian 7

**Comment by Keader** [comment]
Dup #7672
