### ISSUE TITLE
DB/Quest: remove wrong prevquest from "The Conqueror of Skorn!"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17214]
**Description**: the quest The Conqueror of Skorn! (11261, Horde version. The Alliance equivalent has no such issue) has a wrong PrevQuestID set (11244), which means that after turning in quest 11244 (Mimicking Nature's Call), The Conqueror of Skorn! will be available without doing the expected required quests in the actual chain. 

**Steps to reproduce the problem**:

1. Add to yourself, complete and turn in the quest 11244 (Mimicking Nature's Call).
2. Add to yourself the quest 11256 (Skorn Must Fall!, the first of Skorn-related quests).
3. Confirm that you can grab The Conqueror of Skorn! without even turning in the first quest in the chain.

**Branch(es)**: 3.3.5 (the 6.x database has no entry for this quest in quest_template_addon. Not sure why, as it was not removed or changed in WoD).

**TC hash/commit**:  71081c2

**TDB version**:  335.61

**Suggested fix**:  
```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=11261;
```

**Comment by tkrokli** [comment]
TrinityCore rev. 5aae01986f50 2016-05-29 18:51:58 +0100 (3.3.5 branch) (Win64, Release)
TDB 335361 + updates up to and including `2016_05_28_03_world.sql`
```sql
SELECT * FROM `quest_template_addon` WHERE `ID` in (11244,11256,11261);
```
```
    ID  MaxLevel  AllowableClasses  SourceSpellID  PrevQuestID  NextQuestID  ExclusiveGroup  RewardMailTemplateID  RewardMailDelay  RequiredSkillID  RequiredSkillPoints  RequiredMinRepFaction  RequiredMaxRepFaction  RequiredMinRepValue  RequiredMaxRepValue  ProvidedItemCount  SpecialFlags  
------  --------  ----------------  -------------  -----------  -----------  --------------  --------------------  ---------------  ---------------  -------------------  ---------------------  ---------------------  -------------------  -------------------  -----------------  --------------
 11244         0                 0              0        11243            0               0                     0                0                0                    0                      0                      0                    0                    0                  0               0
 11256         0                 0              0        11281            0               0                     0                0                0                    0                      0                      0                    0                    0                  1               0
 11261         0                 0              0        11281            0               0                     0                0                0                    0                      0                      0                    0                    0                  0               0
```
After you remove `PrevQuestID 11281` from `ID 11261`, you may as well delete the entire row, because every column except for `ID` will only contain zeros (a.k.a. empty entry). That is why there is no entry in TDB 6.04 `quest_template_addon` for quest 11261. :-)

**Comment by SnapperRy** [comment]
Right ;) it seems that in the WoD database some heavy cleanup has been made to delete unneeded quest_template_addon entries, while on the WotLK one (almost?) every quest has its own entry.

**Comment by Aokromes** [comment]
I think:

```sql
DELETE FROM `quest_template_addon` WHERE `MaxLevel` = 0 AND `AllowableClasses` = 0 AND `SourceSpellID` = 0 AND `PrevQuestID` = 0 AND `NextQuestID` = 0 AND `ExclusiveGroup` = 0 AND `RewardMailTemplateID` = 0 AND `RewardMailDelay` = 0 AND `RequiredSkillID` = 0 AND `RequiredSkillPoints` = 0 AND `RequiredMinRepFaction` = 0 AND `RequiredMaxRepFaction` = 0 AND `RequiredMinRepValue` = 0 AND `RequiredMaxRepValue` = 0 AND `ProvidedItemCount` = 0 AND `SpecialFlags` = 0;
```

Will do the job

**Comment by SnapperRy** [comment]
There doesn't seem to be any downside to it, so why not. Rows can be recreated as needed when they'll have a purpose.

**Comment by tkrokli** [comment]
Oh. I was thinking of something much simpler, like
```sql
DELETE FROM `quest_template_addon` WHERE `ID`=11261 AND `PrevQuestID`= 11281;
```
or simply
```sql
DELETE FROM `quest_template_addon` WHERE `ID`=11261;
```
... but maybe you were thinking about removing empty lines, Aokromes?

**Comment by Aokromes** [comment]
Yes, i am for delete all the rows where all columns are 0 (ofc, ID aren't counted)

**Comment by tkrokli** [comment]
OK, I meant to provide a solution for this specific issue. Quest 11261 should not have `PrevQuestID`.
Therefore, delete the entire row in `quest_template_addon` where `PrevQuestID = 11261`.

**Comment by SnapperRy** [comment]
The point is that there are many other rows with no useful data, while in the WoD database there aren't any. It makes no sense to delete some but keep some. If they are to be kept (meh, useless data), this one should stay too. If they are to be deleted (cheers), they all should go.
