### ISSUE TITLE
[3.3.5][6.x] Cabal Ritualist visible bug

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17212]
**Description**:
On many Cabal Ritualist missing the Crystal Channel effect

![visible bug](https://cloud.githubusercontent.com/assets/10637389/15634882/3d721fea-25cf-11e6-9c8a-1ea4b1aeada9.jpg)

https://www.youtube.com/watch?v=TlnAVvVMsyw

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
TC>TrinityCore rev. 80fc9cce81dc 2016-05-28 16:36:41 +0100 (335 branch)
**TDB version**:  
355.61 + all updates
**Operating system**:  
Win7 64Bit

**Comment by Rushor** [comment]
maybe the visual spell must ignore line of sight

**Comment by Ulduar** [comment]
@Rushor spell have
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)

**Comment by Rushor** [comment]
k :(

**Comment by Saben65** [comment]
Described the issue in the initial bug report. 

https://github.com/TrinityCore/TrinityCore/issues/16986

**Comment by Tauriella** [comment]
@Killyana 
You are sure this works ?

**Comment by Killyana** [comment]
It's pushed, so it works.
