### ISSUE TITLE
[3.3.5] DB/Quest: improvements to the Brood of Nozdormu ring quests

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17220]
**Description**: this fix accomplishes the following:

- Allow only one of the three ring paths to be chosen. The other two become unavailable.
- Allow to change your final ring at any time as long as you have it in your inventory (the quests are repeatable).
- Add some missing quest text.

**ToDo** (kind of):
- Anachronos should have gossip options to give a new ring if you delete it after completing any of the quests. But I have no idea what the gossip texts should be. Not setting this as a real ToDo because this fix alone is still valid.

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264 

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `ExclusiveGroup`=8747 WHERE `Id` IN (8747, 8752, 8757);

UPDATE `quest_template_addon` SET `PrevQuestId`=0, `SpecialFlags`=1 WHERE `Id` IN (8764, 8765, 8766);

DELETE FROM `conditions` WHERE `SourceEntry` IN (8764, 8765, 8766);
INSERT INTO `conditions` VALUES
(19, 0, 8764, 0, 0, 2, 0, 21200, 1, 1, 0, 0, 0, "", "Quest 8764 is available only if player has item 21200 in bags or bank"),
(20, 0, 8764, 0, 0, 2, 0, 21200, 1, 1, 0, 0, 0, "", "Show question mark for quest 8764 only if player has item 21200 in bags or bank"),

(19, 0, 8765, 0, 0, 2, 0, 21210, 1, 1, 0, 0, 0, "", "Quest 8765 is available only if player has item 21210 in bags or bank"),
(20, 0, 8765, 0, 0, 2, 0, 21210, 1, 1, 0, 0, 0, "", "Show question mark for quest 8765 only if player has item 21210 in bags or bank"),

(19, 0, 8766, 0, 0, 2, 0, 21205, 1, 1, 0, 0, 0, "", "Quest 8766 is available only if player has item 21205 in bags or bank"),
(20, 0, 8766, 0, 0, 2, 0, 21205, 1, 1, 0, 0, 0, "", "Show question mark for quest 8766 only if player has item 21205 in bags or bank");

DELETE FROM `quest_offer_reward` WHERE `ID` IN (8747, 8752, 8757);
INSERT INTO `quest_offer_reward` (`ID`,`Emote1`,`Emote2`,`Emote3`,`Emote4`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`EmoteDelay4`,`RewardText`,`VerifiedBuild`) VALUES
(8747,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8747),12340),
(8752,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8752),12340),
(8757,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8757),12340);

UPDATE `quest_request_items` SET `CompletionText` = "Never have I seen such tenacity! The Bronze Flight grants you one final enchantment. The Timeless One himself has requested it so!$B$BHand me your signet ring so that I may make the necessary adjustments." WHERE `ID` IN (8751, 8756, 8761);
```

**Comment by tkrokli** [comment]
If I may suggest a text improvement to the conditions, here is what I would like to see in there:
```sql
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrRe
(19,0,8764,0,0,2,0,21200,1,1,0,0,0"","Quest 8764 is available only if player has item 21200 in bags or bank"),
(20,0,8764,0,0,2,0,21200,1,1,0,0,0"","Show question mark for quest 8764 only if player has item 21200 in bags or bank"),

(19,0,8765,0,0,2,0,21210,1,1,0,0,0"","Quest 8765 is available only if player has item 21200 in bags or bank"),
(20,0,8765,0,0,2,0,21210,1,1,0,0,0"","Show question mark for quest 8765 only if player has item 21210 in bags or bank"),

(19,0,8766,0,0,2,0,21205,1,1,0,0,0"","Quest 8766 is available only if player has item 21200 in bags or bank"),
(20,0,8766,0,0,2,0,21205,1,1,0,0,0"","Show question mark for quest 8766 only if player has item 21205 in bags or bank");
```
Of course, you can choose to omit the `INSERT INTO` bracket with all the column names, it is just a best practice detail which TC usually keeps for assuring that the query will be correct in relation to the DB.

**Comment by lyn1337** [comment]
https://trinitycore.atlassian.net/wiki/display/tc/SQL+Guidelines :exclamation:

**Comment by tkrokli** [comment]
OK, so "**[...] and always put fields in the query.**" is the rule. Thanks for pointing that out. :+1:
I also noticed "[...] and provide as many links or details as possible. Always pretend that the Dev reading doesn't know the quest/mob/etc you are trying to fix."

- http://www.wowhead.com/npc=15192/anachronos
- http://www.wowhead.com/item=21200/signet-ring-of-the-bronze-dragonflight
- http://www.wowhead.com/quest=8751/the-protector-of-kalimdor
- http://www.wowhead.com/item=21205/signet-ring-of-the-bronze-dragonflight
- http://www.wowhead.com/quest=8756/the-qiraji-conqueror
- http://www.wowhead.com/item=21210/signet-ring-of-the-bronze-dragonflight
- http://www.wowhead.com/quest=8761/the-grand-invoker
- http://www.wowhead.com/quest=8764/the-changing-of-paths-protector-no-more
- http://www.wowhead.com/quest=8765/the-changing-of-paths-invoker-no-more
- http://www.wowhead.com/quest=8766/the-changing-of-paths-conqueror-no-more

Regarding the text you want to insert into `quest_offer_reward`, are you sure it does not show when you want to hand in the quest, or could it be a `conditions` issue? Or maybe I don't know enough about which table is used in which quests, because the same lines are found in 
```sql
SELECT * FROM `quest_request_items` WHERE `CompletionText` LIKE '%Bronze Flight%';
```
```
    ID  EmoteOnComplete  EmoteOnIncomplete  CompletionText                                                                                                                                                                                                                                                                                                                   VerifiedBuild  
------  ---------------  -----------------  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  ---------------
  8747                1                  0  Impressive, little one. You have gone through much trouble to gain the favor of the Bronze Flight. Your dedication is noted.$b$bThe signet ring of the defender will offer superior protection against the forces of evil.$b$bBe warned, once you have chosen your path, you will have no recourse should you change your mind.            12340
  8752                1                  0  Impressive, little one. You have gone through much trouble to gain the favor of the Bronze Flight. Your dedication is noted.$b$bThe signet ring of the conqueror will greatly enhance your physical attacks.$b$bBe warned, once you have chosen your path, you will have no recourse should you change your mind.                          12340
  8757                1                  0  Impressive, little one. You have gone through much trouble to gain the favor of the Bronze Flight. Your dedication is noted.$b$bThe signet ring of the invoker will greatly enhance your magical and natural abilities.$b$bBe warned, once you have chosen your path, you will have no recourse should you change your mind.               12340
```
- http://www.wowhead.com/quest=8747/the-path-of-the-protector
- http://www.wowhead.com/quest=8752/the-path-of-the-conqueror
- http://www.wowhead.com/quest=8757/the-path-of-the-invoker

If your testing has shown that these texts don't appear, maybe something got changed in the DB quest handling and that the quest text should be moved or duplicated. I'm not sure how that part works, I did not follow the changes in the world DB quest tables close enough to remember the details.

**Comment by tkrokli** [comment]
For your `quest_offer_reward` table queries, I suggest adding more info, those rows don't exist in TDB:
```sql
DELETE FROM `quest_offer_reward` WHERE `ID` IN (8747, 8752, 8757);
INSERT INTO `quest_offer_reward` (`ID`,`Emote1`,`Emote2`,`Emote3`,`Emote4`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`EmoteDelay4`,`RewardText`,`VerifiedBuild`) VALUES
(8747,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8747),12340),
(8752,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8752),12340),
(8757,1,0,0,0,0,0,0,0,(SELECT `CompletionText` FROM `quest_request_items` WHERE `ID`=8757),12340);
```
The point I am trying to make is to preserve the information already existing in the other tables, by making sure that each column field values are checked to be as correct as possible, like `VerifiedBuild` etc.
https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-VerifiedBuild

**VerifiedBuild**

This field is used by the TrinityDB Team to determine whether a template has been verified from WDB files.
- If value is 0 then it has not been parsed yet.
- If value is above 0 then it has been parsed with WDB files from that specific client build.
- If value is -1 then it is just a place holder until proper data are found on WDBs.
- If value is -Client Build then it was parsed with WDB files from that specific client build and manually edited later for some special necessity.

**Comment by SnapperRy** [comment]
Applied suggested changes, thanks!

I'd have never thought data text existed for these quests in quest_offer_reward, as the quests themselves never uses this text (those three quests have no required items of any sort, they just offer the ring for free as long as you have the required reputation).
