### ISSUE TITLE
[3.3.5][6.x] DB/Loot: Waterlogged Recipe

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17222]
**Description**: as of patch 3.2.2, the item Waterlogged Recipe was replaced with another version that doesn't turn into a bind on pickup item, allowing to drop the quest and sell the item if you're inclined to ([source](http://www.wowhead.com/item=48679/waterlogged-recipe#comments:id=772839)).
Also up drop chance a bit ([source](http://www.wowhead.com/item=48679/waterlogged-recipe#comments:id=1111938)).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `reference_loot_template` SET `Item`=49667, `Chance`=10 WHERE `Item`=48679;
```

**Comment by Rushor** [comment]
from the item you cannot take the quest again anymore

**Comment by Rushor** [comment]
UPDATE `reference_loot_template` SET `Item`='48679' WHERE  `Entry`=10016 AND `Item`=49667;

**Comment by illfated** [comment]
minor codestyle adjustments for the SQL above:
```sql
UPDATE `reference_loot_template` SET `Item`= 48679 WHERE `Entry`= 10016 AND `Item`= 49667;
```

**Comment by illfated** [comment]
BTW, you say that it is not possible to get the quest from the item, do you mean all 3 items?
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Waterlogged+Recipe

Maybe I am just a little bit confused, not getting at which point you refer to.
