### ISSUE TITLE
[3.3.5][6.x] DB/Loot: reduce dropped quantity for item "Ravasaur Pheromone Gland" 

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17229]
**Description**: [NPC](http://www.wowhead.com/npc=9683/larkorwi-mate) should drop one of those instead of two.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `creature_loot_template` SET `MinCount`=1, `MaxCount`=1 WHERE `Item`=11509;
```

**Comment by tkrokli** [comment]
Thanks for the fix, I never took the time to find out why Lar'korwi Mate drops 2 of that item on TC source.
