### ISSUE TITLE
[3.3.5] DB/Spell: add target filter for spell cast by item "Zorbin's Ultra-Shrinker"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17228]
**Description**: spell cast by item "Zorbin's Ultra-Shrinker" should target only certain creatures (giants around Feralas) that must be alive.

**Steps to reproduce the problem**:

1. Grab the item "Zorbin's Ultra-Shrinker" (18904) and right-click it.
2. The spell will fire without requiring a target.

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `conditions` WHERE `SourceEntry`=23359 AND `SourceTypeOrReferenceId`=17;
INSERT INTO `conditions` VALUES
(17, 0, 23359, 0, 0, 31, 1, 3, 5357, 0, 0, 0, 0, "", "Transmogrify! target can be Land Walker"),
(17, 0, 23359, 0, 0, 36, 1, 0, 0, 0, 0, 0, 0, "", "Transmogrify! target must be alive"),
(17, 0, 23359, 0, 1, 31, 1, 3, 5358, 0, 0, 0, 0, "", "Transmogrify! target can be Cliff Giant"),
(17, 0, 23359, 0, 1, 36, 1, 0, 0, 0, 0, 0, 0, "", "Transmogrify! target must be alive"),
(17, 0, 23359, 0, 2, 31, 1, 3, 5359, 0, 0, 0, 0, "", "Transmogrify! target can be Shore Strider"),
(17, 0, 23359, 0, 2, 36, 1, 0, 0, 0, 0, 0, 0, "", "Transmogrify! target must be alive"),
(17, 0, 23359, 0, 3, 31, 1, 3, 5360, 0, 0, 0, 0, "", "Transmogrify! target can be Deep Strider"),
(17, 0, 23359, 0, 3, 36, 1, 0, 0, 0, 0, 0, 0, "", "Transmogrify! target must be alive"),
(17, 0, 23359, 0, 4, 31, 1, 3, 5361, 0, 0, 0, 0, "", "Transmogrify! target can be Wave Strider"),
(17, 0, 23359, 0, 4, 36, 1, 0, 0, 0, 0, 0, 0, "", "Transmogrify! target must be alive");
```

**Comment by tkrokli** [comment]
Links to the item, item spell & NPCs, just for the sake of completeness:
- http://www.wowhead.com/item=18904/zorbins-ultra-shrinker
- http://www.wowhead.com/spell=23359/transmogrify
- http://www.wowhead.com/npc=5357/land-walker
- http://www.wowhead.com/npc=5358/cliff-giant
- http://www.wowhead.com/npc=5359/shore-strider
- http://www.wowhead.com/npc=5360/deep-strider
- http://www.wowhead.com/npc=5361/wave-strider
