### ISSUE TITLE
[6.x] DBErrors: Fix 52 lines referencing npc_text

### ISSUE THREAD

**Issue by tkrokli** [TrinityCore/TrinityCore#17237]
**Description**:
DBErrors.log contains 52 lines referencing 41 `npc_text`.`ID` entries, caused by incorrectly filled in values in the columns `Probability0` through `Probability7`. Only a few values are correctly placed.
Typical error message for these lines:
```
NPCText (ID: 11128) has a probability (Index: 0) set, but no BroadcastTextID to go with it
```

**Current behaviour**: Tell us what happens
DBErrors.log contains 52 lines referencing 41 `npc_text`.`ID` entries.

**Expected behaviour**: Tell us what should happen instead
DBErrors.log should not contain any lines referencing `npc_text`.`ID`

**Steps to reproduce the problem**:

1. Start up worldserver and wait until it has loaded completely.
2. Open up DBErrors.log in the core folder (or any Logs folder you have defined)
3. Search for "NPCText" and you should find 52 lines (highlighted in Notepad++)

**Branch(es)**: **6.x** (Select the branch(es) affected by this issue) 

**TC hash/commit**:  rev. fde9e8985f20 2016-05-30 18:31:30 +0200 (6.x branch) (Win64, Release)

**TDB version**:  TDB 6.04 + updates up to and including `2016_05_30_04_world.sql`

**Operating system**:   Windows 10 Home edition (x64) version 1511 (OS Build 10586.318)

**Suggested solution:**
```sql
UPDATE `npc_text` SET `Probability0`= 0 WHERE `ID` IN (518,2953,2955,2956,2957,3293,3553,4782,4935,4937,7114,7240,7904,8321,8332,8354,8358,9125,9914,10128,11128,12181,13157,14330,30000);
UPDATE `npc_text` SET `Probability0`= 1, `Probability1`= 0, `Probability2`= 0, `Probability3`= 0, `Probability4`= 0,`Probability5`= 0, `Probability6`= 0, `Probability7`= 0 WHERE `ID` IN (10059,11428);
UPDATE `npc_text` SET `Probability0`= 1, `Probability1`= 1, `Probability2`= 0 WHERE `ID` IN (2500,2502,2562,2563,2653,4033,4052,4075,4076,4077,4078);
UPDATE `npc_text` SET `Probability0`= 1, `Probability1`= 0 WHERE `ID` IN (3173,10843,13311);
```
Solution is tested 2 times on a fresh rebuilt 6.x world DB and removes 52 DBErrors about `NPCText`.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
Added solution for the following 6 lines about `ScriptName` exists in database, but core script not found:
```
ScriptName '0' exists in database, but no core script found!
ScriptName '423' exists in database, but no core script found!
ScriptName 'npc_parqual_fintallas' exists in database, but no core script found!
ScriptName 'internalitemhandler' exists in database, but no core script found!
ScriptName 'npc_anchorite_truuen' exists in database, but no core script found!
ScriptName 'npc_taxi' exists in database, but no core script found!
```
**Partial solution:**
```sql
UPDATE `creature_template` SET `ScriptName`= '' WHERE `entry` IN (4488,17209,17238,97229,89713);
```
I could not find out in which table the following 2 scripts are located: `internalitemhandler`, `423`.
I can only suggest to fill in the missing table name here:
```sql
UPDATE `unknown_table` SET `ScriptName`= '' WHERE `ScriptName` IN ('423','internalitemhandler');
```
(or split that query into 2 separate ones in case of 2 different tables)

BTW, reference old issue  [6.x] DBErrors.log #15829

**Comment by Aokromes** [comment]
LOCK TABLES `item_script_names` WRITE;
/*!40000 ALTER TABLE `item_script_names` DISABLE KEYS */;
(35205,'internalitemhandler'),(35214,'internalitemhandler'),(49867,'423');

**Comment by Shauren** [comment]
in 6.x the table is item_template_addon (there are more fields than just scriptname)

**Comment by Aokromes** [comment]
No, it's not.

http://i.imgur.com/IqPoUfW.png

**Comment by Shauren** [comment]
weird that i dont remember code i wrote in the past

**Comment by tkrokli** [comment]
Thank you for the DB info. I have modified that last query now to delete 3 rows in `item_script_names`
```sql
SELECT * FROM `item_script_names` WHERE `ScriptName` IN ('423','internalitemhandler');
```
```
   Id  ScriptName
-----  ---------------------
35205  internalitemhandler
35214  internalitemhandler
49867  423
```
Because there is no other useful info in those 3 rows and that table only functions as a link table between 2 values, I chose to delete those 3 rows instead of only removing `ScriptName`.

**Comment by Aokromes** [comment]
npc_text part needs to be re-sniffed.

**Comment by Aokromes** [comment]
#15829
