### ISSUE TITLE
[3.3.5][6.x] DB/Creature: make some creatures appear dead when appropriate

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17239]
**Description**: the creatures [Trapped Animal](http://www.wowhead.com/npc=24196/trapped-animal), [Marsh Caribou](http://www.wowhead.com/npc=25680/marsh-caribou) (only the five spawned all around [Karen "I Don't Caribou" the Culler](http://www.wowhead.com/npc=25803/karen-i-dont-caribou-the-culler)) and [K3 Snow Runner](http://www.wowhead.com/npc=29546/k3-snow-runner) should all appear dead.

Notes: I don't know if they are supposed to be targetable or not. Right now, all of those are. If anyone has more info to share, please do so!

**Current behaviour**: those creature appear alive (standing) and in some cases even walking around or attackable.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `creature` SET `spawndist`=0, `MovementType`=0, `unit_flags`=537133824 WHERE `guid` IN (103024, 103025, 103026, 103027, 103028);

DELETE FROM `creature_addon` WHERE `guid` IN (103024, 103025, 103026, 103027, 103028);
INSERT INTO `creature_addon` (`guid`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(103024, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(103025, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(103026, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(103027, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(103028, 0, 0x0, 0x1, '29266'); -- 25680 - 29266 - 29266

UPDATE `creature` SET `spawndist`=0, `MovementType`=0 WHERE `id`=29546;

DELETE FROM `creature_template_addon` WHERE `entry` IN (24196, 29546);
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(24196, 0, 0x0, 0x1, '29266'), -- 24196 - 29266
(29546, 0, 0x0, 0x1, '29266'); -- 29546 - 29266
```

Thanks dr-j for sniffs!

**Comment by dr-j** [comment]
are you sure this is correct as usually dead mobs in Northrend use a feign death spell which sets unit flags 2, dynamic flags, etc to make creature look dead and have 0 hp

Its usually only done with with flags for tbc/vanilla mobs where not selectable flags are usually preset too as otherwise even though npc lying on ground if you click on it it will show full hp.

**Comment by SnapperRy** [comment]
I'm not sure, I don't have access to retail to check if there's some aura that handles it. Didn't know there were spells for this too, thought setting flags was the usual way to do it.

On the outside it looks fine though, there's no full hp bar or anything.

**Comment by dr-j** [comment]
~~~sql
INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(24196, 0, 0x0, 0x1, '29266'), -- 24196 - 29266
(29546, 0, 0x0, 0x1, '29266'), -- 29546 - 29266

INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `phaseId`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `MovementType`) VALUES
(@CGUID+3023, 25680, 571, 1, 169, '', 2729.312, 5282.218, 70.99953, 1.413717, 120, 0, 0), -- 25680 (Area: 3537) (Auras: 29266 - 29266)
(@CGUID+3028, 25680, 571, 1, 169, '', 2736.802, 5276.029, 70.96942, 4.29351, 120, 0, 0), -- 25680 (Area: 3537) (Auras: 29266 - 29266)
(@CGUID+3029, 25680, 571, 1, 169, '', 2737.312, 5260.853, 70.45969, 0.9599311, 120, 0, 0), -- 25680 (Area: 3537) (Auras: 29266 - 29266)
(@CGUID+3033, 25680, 571, 1, 169, '', 2715.933, 5279.789, 69.87627, 5.585053, 120, 0, 0); -- 25680 (Area: 3537) (Auras: 29266 - 29266)


INSERT INTO `creature_addon` (`guid`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(@CGUID+3023, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(@CGUID+3028, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(@CGUID+3029, 0, 0x0, 0x1, '29266'), -- 25680 - 29266 - 29266
(@CGUID+3030, 0, 0x0, 0x1, '29266'); -- 25680 - 29266 - 29266

~~~

Theres sql output from sniff data

**Comment by SnapperRy** [comment]
Thanks!

Tested and works fine, although the caribous still need unit_flags set to 256 because their faction is attackable by player characters (and the aura doesn't affect that).

Just a question, still about the caribous. There are five spawn on DB, but on sniffs there are only four. Should that one be removed from the DB?

**Comment by dr-j** [comment]
I have only checked one sniff and could only find 4 but maybe the 5th was out of range when sniffed.

**Comment by SnapperRy** [comment]
Yeah that's probably the reason, going to keep it there.

**Comment by dr-j** [comment]
Proper Unit Flags for those 5 are 537133824

**Comment by SnapperRy** [comment]
Edited, thanks!
