### ISSUE TITLE
[3.3.5][6.x] DB/Loot: fix quest required to loot item "Vrykul Scroll of Ascension"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17238]
**Description**: item Vrykul Scroll of Ascension ([Alliance](http://www.wowhead.com/item=33314/vrykul-scroll-of-ascension)/[Horde](http://www.wowhead.com/item=33345/vrykul-scroll-of-ascension)) that drops from various mobs in the area Skorn (Howling Fjord) has a wrong required quest in conditions ([Alliance](http://www.wowhead.com/quest=11247/burn-skorn-burn)/[Horde](http://www.wowhead.com/quest=11258/burn-skorn-burn)). Instead, it should require a quest that comes first in the Skorn chain ([Alliance](http://www.wowhead.com/quest=11248/operation-skornful-wrath)/[Horde](http://www.wowhead.com/quest=11256/skorn-must-fall)). [Source](http://www.wowhead.com/item=33314/vrykul-scroll-of-ascension#comments:id=1300338).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `conditions` SET `ConditionValue1`=11248, `Comment`='Winterskorn mobs drop item 33314 only if Quest 11248 has been rewarded' WHERE `SourceTypeOrReferenceId`=1 AND `SourceEntry`=33314;

UPDATE `conditions` SET `ConditionValue1`=11256, `Comment`='Winterskorn mobs drop item 33345 only if Quest 11256 has been rewarded' WHERE `SourceTypeOrReferenceId`=1 AND `SourceEntry`=33345;
```

**Comment by tkrokli** [comment]
You can also add the missing comment text which should explain what the conditions do:
```sql
UPDATE `conditions` SET `ConditionValue1`=11248, `Comment`='Winterskorn mobs drop item 33314 only if Quest 11248 has been rewarded' WHERE `SourceTypeOrReferenceId`=1 AND `SourceEntry`=33314;

UPDATE `conditions` SET `ConditionValue1`=11256, `Comment`='Winterskorn mobs drop item 33345 only if Quest 11256 has been rewarded' WHERE `SourceTypeOrReferenceId`=1 AND `SourceEntry`=33345;
```

**Comment by SnapperRy** [comment]
Updated, thanks!
