### ISSUE TITLE
[Quest] The Only Cure is More Green Glow

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#1723]
Quest http://www.wowhead.com/quest=2962/the-only-cure-is-more-green-glow has a strange problem, you can use http://www.wowhead.com/item=9364 without targeting the necessary mobs and you become irradiated.

I tried to gather fallout from the irradiated lurkers and horrors, but it seems impossible to gather a sample.

TDB 40 Core: 48b0570f5333
##

**Comment by tkrokli** [comment]
http://www.wowhead.com/quest=2962/the-only-cure-is-more-green-glow (removed in patch 4.0.3a)

Heavy Leaden Collection Phial: http://www.wowhead.com/item=9364/heavy-leaden-collection-phial
uses spell 12709, Collecting Fallout: http://www.wowhead.com/spell=12709/collecting-fallout

High Potency Radioactive Fallout: http://www.wowhead.com/item=9365/high-potency-radioactive-fallout uses spell 11637, http://www.wowhead.com/spell=11637/empty-heavy-phial

Intended targets:
- Irradiated Slime: http://www.wowhead.com/npc=6218/irradiated-slime
- Corrosive Lurker: http://www.wowhead.com/npc=6219/corrosive-lurker
- Irradiated Horror: http://www.wowhead.com/npc=6220/irradiated-horror

Current conditions for spell 12709 and 11637 in TDB 335.60, current commit ecbbcc8 :
```sql
SELECT * FROM `conditions` WHERE `SourceEntry` IN (12709,11637);
```
```
SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment
-----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  -------
                     13            1        11637         0          0                        31                0                3             6218                0                  0          0            0              (NULL)
                     13            1        11637         0          1                        31                0                3             6219                0                  0          0            0              (NULL)
                     13            1        11637         0          2                        31                0                3             6220                0                  0          0            0              (NULL)
                     13            1        12709         0          0                        31                0                3             6218                0                  0          0            0              (NULL)
                     13            1        12709         0          1                        31                0                3             6219                0                  0          0            0              (NULL)
                     13            1        12709         0          2                        31                0                3             6220                0                  0          0            0              (NULL)
```
Notice that these conditions, which are supposed to select NPC 6218, 6219 and 6220, are using `SourceTypeOrReferenceId` 13, `CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET`. The comment section is unfortunately empty, so there is no exact explanation for the intention behind these conditions. Useful comments should look something like "spell Collecting Fallout requires Irradiated Slime to be targeted" with only the NPC names changed on each line.

In https://www.trinitycore.info/display/tc/conditions#conditions-Comment (below the headline "Explanation of condition types") it looks like `CONDITION_SOURCE_TYPE_SPELL` (17) would be a better solution: `ConditionTarget` = 1
"Explicit target of the spell (only for spells which take object selected by caster into account)"

Notes for this section, specifically bullet point 2 and 3, seem to confirm this theory, because the targets are supposed to be explicit and not implicit.

**Comment by Nyeriah** [comment]
http://hastebin.com/ixojivonuh.coffee

TARGET_UNIT_NEARBY_ENTRY

**Comment by tkrokli** [comment]
Oh, so that means that it is working as intended and that this issue can be closed because it works?
```
- - -
Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 2) "Combat Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 5, MaxRangeFriendly = 5

CastingTime (Id 15) = 4,00

Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00002802
Chance = 101, charges - 0
=================================================
Effect 0: Id 64 (SPELL_EFFECT_TRIGGER_SPELL)
BasePoints = 1
Targets (38, 0) (TARGET_UNIT_NEARBY_ENTRY, NO_TARGET)
   Trigger spell (11637) Empty Heavy Phial. Chance = 101
   Description: Captures radioactive fallout.

Effect 1: Id 64 (SPELL_EFFECT_TRIGGER_SPELL)
BasePoints = 1
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
   Trigger spell (11638) Radiation Poisoning. Chance = 101

Effect 2:  NO EFFECT
```
I don't know if I am misreading this, but if `TARGET_UNIT_NEARBY_ENTRY, NO_TARGET` and `TARGET_UNIT_CASTER, NO_TARGET` means that the item spell is not intended to have a target, it looks to me as if the quest item works Blizzlike already. Have I misunderstood something?

**Comment by Aokromes** [comment]
Acording http://www.wowhead.com/quest=2962/the-only-cure-is-more-green-glow#comments:id=94078 it must be used on a LIVE target.

**Comment by tkrokli** [comment]
OK, I will test it on current 3.3.5 branch, commit fbaed38, to see if it works as intended or not. Pity that the OP was not asked if he was trying to target the dead mobs or if he had tried targeting the live ones.

**Comment by Nyeriah** [comment]
CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET is the condition used (in general) for AREA, NEARBY and CONE spell target filtering, so the conditions you pasted are correct. Not checking if any other conditions are required though.

**Comment by tkrokli** [comment]
TrinityCore rev. f01280075139 2015-11-17 17:51:09 +0100 (3.3.5 branch) (Win64, Release)

There is a lot more wrong with this quest and its prerequisite than previously mentioned. I was able to complete both quests without taking a single step away from the quest giver Ozzie Togglevolt.
- Create a new character, e.g. dwarf or gnome
- Level up to 20 (.char level 20)
- .go creature [Gnoarn](http://wotlk.openwow.com/npc=6569) (and receive quest http://wotlk.openwow.com/quest=2927/the-day-after)
- .go creature [Ozzie_Togglevolt](http://wotlk.openwow.com/npc=1268) (to deliver and take nest quest, Gnogaine, quest 2926)
- Use the bottle http://wotlk.openwow.com/item=9283/empty-leaden-collection-phial (it works anywhere)
- Deliver Gnogaine and take http://wotlk.openwow.com/quest=2962/the-only-cure-is-more-green-glow
- Use http://wotlk.openwow.com/item=9364/heavy-leaden-collection-phial (it works anywhere)
- Deliver quest [[The Only Cure is More Green Glow]](http://wotlk.openwow.com/quest=2962), no movement needed.

**Comment by Staleness89** [comment]
Sunwell core fix:
```SQL
DELETE FROM `conditions` WHERE `SourceEntry`= 11513 and (`SourceTypeOrReferenceId`=17 or `SourceTypeOrReferenceId`=13);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 11513, 0, 0, 29, 0, 6213, 6, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 11513, 0, 1, 29, 0, 6329, 6, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(13, 1, 11513, 0, 0, 31, 0, 3, 6213, 0, 0, 0, 0, '', 'Requires NPC for cast'),
(13, 1, 11513, 0, 1, 31, 0, 3, 6329, 0, 0, 0, 0, '', 'Requires NPC for cast');

DELETE FROM `conditions` WHERE `SourceEntry`= 12709 and (`SourceTypeOrReferenceId`=17 or `SourceTypeOrReferenceId`=13);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(17, 0, 12709, 0, 0, 29, 0, 6218, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 1, 29, 0, 6220, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 2, 29, 0, 6219, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(13, 1, 12709, 0, 0, 31, 0, 3, 6218, 0, 0, 0, 0, '', 'Requires NPC for cast'),
(13, 1, 12709, 0, 1, 31, 0, 3, 6219, 0, 0, 0, 0, '', 'Requires NPC for cast'),
(13, 1, 12709, 0, 2, 31, 0, 3, 6220, 0, 0, 0, 0, '', 'Requires NPC for cast');
```

**Comment by Staleness89** [comment]
So this fixes most of the issues with the quest except the spell Collecting Fallout  - http://www.wowhead.com/spell=12709/collecting-fallout isn't suppose to work 100%, not sure what the chance would be on it, but it's suppose to be able to fail a few times and from what I tested, it worked every time. Other than that part, these conditions make the quest a bit more blizzlike. There are some confusing comments on WoWhead for the quest Gnogaine as to which troggs are suppose to allow casting, maybe only the irradiated ones?

**Comment by Killyana** [comment]
Here the correct conditions, but as you say spell effect1 of http://www.wowhead.com/spell=12709/collecting-fallout  must probably have 20% or 30%  chancce to proc, and we cannot do this via the DB
``` sql
DELETE FROM `conditions` WHERE `SourceEntry`= 11513 AND (`SourceTypeOrReferenceId`=17 OR `SourceTypeOrReferenceId`=13);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 11513, 0, 0, 29, 0, 6213, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 11513, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 11513, 0, 1, 29, 0, 6329, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 11513, 0, 1, 36, 0, 0, 0, 0, 0, 0, 0, '', 'Must be near NPC to cast');


DELETE FROM `conditions` WHERE `SourceEntry`= 12709 AND (`SourceTypeOrReferenceId`=17 OR `SourceTypeOrReferenceId`=13);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(17, 0, 12709, 0, 0, 29, 0, 6218, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 1, 29, 0, 6220, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 1, 36, 0, 0, 0, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 2, 29, 0, 6219, 5, 0, 0, 0, 0, '', 'Must be near NPC to cast'),
(17, 0, 12709, 0, 2, 36, 0, 0, 0, 0, 0, 0, 0, '', 'Must be near NPC to cast');
