### ISSUE TITLE
[Quest] Gerenzo's Orders

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#1724]
In quest http://www.wowhead.com/quest=1090/gerenzos-orders you must protect http://www.wowhead.com/npc=4276 against waves of kobold mobs, but nothing happens.

TDB 40 Core 48b0570f5333

**Comment by offl** [comment]
Seems that TC don't have sniffs for this quest, right?
Support can be converted from [UDB version](https://github.com/classicdb/database/issues/596) of this quest. Of course with some cosmetic changes.
Here's a [video](https://www.youtube.com/watch?v=PFNcwco8JZ0) of the quest(the most stupid video ever).
