### ISSUE TITLE
3.3.5 Building CXX object

### ISSUE THREAD

**Issue by strikeek0** [TrinityCore/TrinityCore#17240]
Building CXX object src/server/game/CMakeFiles/game.dir/DataStores/M2Stores.cpp.o
/opt/source/TrinityCore/src/server/game/DataStores/M2Stores.cpp: In function ‘bool readCamera(const M2Camera*, uint32, const M2Header*, const CinematicCameraEntry*)’:
/opt/source/TrinityCore/src/server/game/DataStores/M2Stores.cpp:154:23: error: variable ‘z’ set but not used [-Werror=unused-but-set-variable]
                 float z = lastTarget.locations.z;

**Comment by tkrokli** [comment]
Please use the TrinityCore Forum https://community.trinitycore.org/forum/5-help-and-support/ for compile issues. ... _and please close this issue too_. If you want more direct dialog with developers or advanced users, use the IRC channel #trinity @ irc.rizon.net - https://trinitycore.atlassian.net/wiki/display/tc/IRC

**Comment by Aokromes** [comment]
don't use travis' compilation flags if you don't known what they mean.
