### ISSUE TITLE
[3.3.5] DB/Quest: fix chaining for quest "A Lost Master"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17244]
**Description**: quest "[A Lost Master](http://www.wowhead.com/quest=986/a-lost-master)" requires completion of quest "[How Big a Threat?](http://www.wowhead.com/quest=985/how-big-a-threat)" (Part 2). [Source](http://www.wowhead.com/quest=986/a-lost-master#comments:id=1076593).

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=985 WHERE `ID`=986;
```

**Comment by tkrokli** [comment]
Nice, I noticed something weird about those quests while testing night elf quests in Darkshore a few weeks ago, but I didn't have time to check the details and I had a lot of other stuff to do. Thank you! :+1:
