### ISSUE TITLE
[3.3.5] DB/Quest: remove faction requirement for quest "Deviate Hides"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17248]
**Description**: the quest "[Deviate Hides](http://www.wowhead.com/quest=1486/deviate-hides)" should be available to both Horde and Alliance (right now, it's only available to Horde). [Source](http://www.wowhead.com/quest=1486/deviate-hides#comments:id=929044) (it also says Side: Both!).

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `AllowableRaces`=0 WHERE `ID`=1486;
```

**Comment by tkrokli** [comment]
Good point, I rarely go to Wailing Caverns with alliance characters, I am biased towards Horde. :laughing:
