### ISSUE TITLE
[3.3.5] DB/Quest: fix required race for "Travel to Darkshire" 

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17243]
**Description**: quest "[Travel to Darkshire](http://www.wowhead.com/quest=9429/travel-to-darkshire)" should be only available to Draenei characters. Source [1](http://www.wowhead.com/quest=9429/travel-to-darkshire#comments:id=62731)/[2](http://www.wowhead.com/quest=9429/travel-to-darkshire#comments:id=36099)/[3](http://www.wowhead.com/quest=9429/travel-to-darkshire#comments:id=985549:reply=175561) (there's one comment saying they were to get it as a human, but it doesn't really sound truthful, as well as it not making sense with the rest of the breadcrumbs meant for Draenei to help integrate with the world) .

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `AllowableRaces`=1024 WHERE `ID`=9429;
```

**Comment by lyn1337** [comment]
The argument, it won't make sense to offer the quest to non-Draenei because it is leading the race into the questing areas offering further level progess, doesn't sound very reasonable to me. Players of other races also might chose to quest in Draenei starting areas and this one should be offered to them as well, as it is of guiding nature.

Also: some attention to this comment, explaining some of the other reactions (which are, when stating the contrary, not down-voted):

> TAP3AH on 2010/03/24 (Patch 3.3.3)
> It's as called breadcrumb quest. There are usually several different ones leading to a single place. Once the follow-up quest is taken they all become unavailable.


I'm just saying that simply limiting access to a quest, based on some comments somewhere, might have a greater impact on the game, regarding achievements for example.

So, if there is no further proof, I'd leave it as it is.

**Comment by SnapperRy** [comment]
I know that alone is not proof, I just added it as an afterthought because this one NPC is one among a bunch that was added in TBC (and the other NPC's quests are all Draenei only).

The same was done with Blood Elves, and the specular opposite of this quest ([this one](http://www.wowhead.com/quest=9425)) is Blood Elf-only. I haven't added those to the issue because it's not a definite, indisputable proof. But if this was the only things to base this on, I wouldn't have opened this issue.

The best proof we're going to get are the other three comments on Wowhead saying they couldn't grab this quest with other races. [This one](http://www.wowhead.com/quest=9429/travel-to-darkshire#comments:id=62731) was quite upvoted, I doubt it would have been so if it was wrong.

**Comment by lyn1337** [comment]
Well I wouldn't call your best proof a definite and indisputable one either. The comment on that comment you've linked is just stating the opposite without being down-voted. Quick facts only mention that it's a Alliance - only quest and the comment from my last post holds the explanation for this behavior, as well as for other quests.

**Comment by SnapperRy** [comment]
Well, Wowhead's quick facts only sometimes indicate if a quest is exclusive to some races or classes, otherwise we wouldn't have so many quests of dubious availability.

[Here's](http://www.wowhead.com/npc=17103/emissary-taluun#comments:id=580581) two comments from the quest giver's page on Wowhead confirming it's Draenei only.

**Comment by lyn1337** [comment]
Maybe the line in the quest description "As we're trying to help as much as we can, […]" hints he's talking to one of his kind.

It is a downright shame all patch logs don't say anything about it.
Maybe they even changed something about it, just noticed this:
"Added in patch 3.3.0" (Quick facts)
but the comment stating it a racespecific quest is dated to 2007/04/06.

**Comment by SnapperRy** [comment]
Yeah, Wowhead is always a hit and miss for info outside of comments. Many "Added in patch x" are wrongly set to patches that came later than the quest/item.

**Comment by Killyana** [comment]
On 6.x DB the quest is available only to Draenei, so it must be correct.
