### ISSUE TITLE
[3.3.5] DB/Quest: fix required race for "Report to Tarren Mill"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17246]
**Description**: the quest "[Report to Tarren Mill](http://www.wowhead.com/quest=9425/report-to-tarren-mill)" is supposed to be only available to Blood Elves. [Source](http://www.wowhead.com/quest=9425/report-to-tarren-mill#comments:id=1098062).

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `AllowableRaces`=512 WHERE `ID`=9425;
```

**Comment by Aokromes** [comment]
Even better source, look at top right where is marked asl BE only :P

**Comment by SnapperRy** [comment]
Haha right :D didn't notice that up there.
