### ISSUE TITLE
[3.3.5] Group creation behavior inconsistent with retail

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17258]
3.3.5 e3aa192

On current TC, a group is created when the first player accepts the group invite. This means you cannot invite additional people before the first member accepts the group, and you also cannot "cancel" a group invite by leaving the group early (using `/run LeaveParty()`).

On retail, a group is created when the player first sends a group invite. You can begin inviting additional members immediately, and also leave this not-yet-visible group using `/run LeaveParty()` or similar.

**Comment by jackpoz** [comment]
could it be just a matter of changing invite/leave to handle this case too ? invite allowing multiple invites even if group is not formed and LeaveParty cancelling any pending invite.
in the other case, when does the invisible group expire ? on logout/if none accepts ?

**Comment by Treeston** [comment]
Once all invites time out, I assume.

**Comment by Kittnz** [comment]
Or if you leave "party" while no one is in the party

**Comment by Keader** [comment]
Yeap, when all invites time out

**Comment by Treeston** [comment]
no idea @kittnz
