### ISSUE TITLE
[3.3.5] DB/Quest: fix repeatableness for a few quests

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17253]
**Description**: the following quests should be repeatable (their purpose is mostly to give players a quest item in case they lose it, while [this one](http://www.wowhead.com/quest=3382/a-crew-under-fire) is proof that Blizzard hates Azshara):

- [Onu is meditating](http://www.wowhead.com/quest=961/onu-is-meditating)
- [Replacement Phial](http://www.wowhead.com/quest=3375/replacement-phial)
- [A Crew Under Fire](http://www.wowhead.com/quest=3382/a-crew-under-fire)
- [Signal for Pickup](http://www.wowhead.com/quest=3483/signal-for-pickup)

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `SpecialFlags`=`SpecialFlags`|1 WHERE `ID` IN (961, 3375, 3382, 3483);
```

**Comment by tkrokli** [comment]
The first quest in your list, [Onu is meditating], has got a bit more detail on wotlk.openwow.com:
- http://wotlk.openwow.com/quest=961/onu-is-meditating

Other than that, thank you for keeping up all this good work! :+1:

**Comment by SnapperRy** [comment]
Yeah, also the only comment on Wowhead confirms it's repeatable.

Also every other quest has either comments or the Quick Facts box confirming this :P
