### ISSUE TITLE
[3.3.5] DB/Quest: set required profession for quest "Gathering Leather"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17252]
**Description**: the quest "[Gathering Leather](http://www.wowhead.com/quest=768/gathering-leather)" should only be acceptable if the player has learned Skinning. [Source](http://www.wowhead.com/quest=768/gathering-leather#comments:id=18713), and the Quick Facts box says so, too).

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `quest_template_addon` WHERE `ID`=768;
INSERT INTO `quest_template_addon` (`ID`, `RequiredSkillID`, `RequiredSkillPoints`) VALUES
(768, 393, 1);
```

**Comment by tkrokli** [comment]
:+1: Good point. http://wow.gamepedia.com/Quest:Gathering_Leather
[Prerequisites: Skinners only.] Also, in your linked wowhead page: [Profession: Skinning]
