### ISSUE TITLE
[6.X] Build failed

### ISSUE THREAD

**Issue by Keany** [TrinityCore/TrinityCore#17251]
Dear,

i have a trouble with build on linux debian 8 jessie - fresh install

Crash: 

Scanning dependencies of target generate_gamePCH.cpp
[ 20%] Generating gamePCH.h.gch
[ 20%] Built target generate_gamePCH.cpp
Scanning dependencies of target game
[ 20%] Building CXX object src/server/game/CMakeFiles/game.dir/PrecompiledHeaders/gamePCH.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/server/game/CMakeFiles/game.dir/build.make:54: recipe for target 'src/server/game/CMakeFiles/game.dir/PrecompiledHeaders/gamePCH.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/PrecompiledHeaders/gamePCH.cpp.o] Error 4
CMakeFiles/Makefile2:1467: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Branch(es)**:  6.x 

**TC hash/commit**:  a6f6bb4fccb6 2016-05-31 19:14:31 +0200 (6.x branch)

**Operating system**:  Debian 8 Jessie

gcc --version
gcc (Debian 4.9.2-10) 4.9.2

**Comment by Aokromes** [comment]
I can't compile Trinitycore under Linux i get  c++: internal compiler error: Segmentation fault (program cc1plus)

This can be because multiple reasons:

1) Selinux stronged kernels, workaround change to one standard kernel or compile with clang instead gcc or compile without pch.

2) Low ram/swap memory, increase ram/swap amount.
