### ISSUE TITLE
[3.3.5] Compil errors

### ISSUE THREAD

**Issue by shiioo** [TrinityCore/TrinityCore#17260]
Went from this commit https://github.com/TrinityCore/TrinityCore/commit/f8064a549d1bf7e12a99066d1df35bc301805685 to this one https://github.com/TrinityCore/TrinityCore/commit/e3aa19281f4d1e2437a5654715f75ae919bd4027 and cannot compile the server anymore.

Here's what VS says:

> \src\server\game\AI\PlayerAI\PlayerAI.h(46): error C2886: 'pair<Spell *,Unit *>' : symbol cannot be used in a member using-declaration (\src\server\scripts\Spells\spell_dk.cpp)

> LINK : fatal error LNK1181: cannot open input file '..\scripts\Release\scripts.lib'

> ========== Build: 19 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

**Operating system**:  Windows 7 x64 // VS 2013

**Comment by DeActiveDev** [comment]
Confirm

**Comment by DearAdmin** [comment]
========== Build: 19 succeeded, 3 failed, 0 up-to-date, 1 skipped ==========

![adsi45z](https://cloud.githubusercontent.com/assets/10039561/15717313/1fec2134-282f-11e6-860e-549c7a2eb96a.png)

**Comment by DearAdmin** [comment]
hey @DeActiveDev   "after commit 25c5570" 

its still same err0r
