### ISSUE TITLE
[3.3.5][6.x] Sindragosa - Icy Grip

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17265]
**Description**: Icy grip should move player to center of Sindragosa

**Current behaviour**: Icy grip move player to border of Sindragosa model

**Branch(es)**: 3.3.5 

**TC hash/commit**:  325143960074a562b1d419bfe23cf9cbf1b75e11

**TDB version**:  61

**Operating system**:  Debian

**Comment by Rushor** [comment]
possible fix in https://github.com/TrinityCore/TrinityCore/issues/1087

moreover there must be some exceptions for the jump.
1.) it should not move the tank
2.) it should not move player which are in the ice block in phase 2 switch
3.) it should not move people which are not in los (f.ex. behind the iceblocks)

**Comment by Runico** [comment]
@Rushor, that fix doesnt work anymore cause of new changes

**Comment by P-Kito** [comment]
Here comes the hackfix!
```        
case 70122: // Sindragosa - Icygrip jump
                spellInfo->Effects[EFFECT_0].TargetA = SpellImplicitTargetInfo(TARGET_DEST_TARGET_ANY);
                spellInfo->Effects[EFFECT_0].Effect = SPELL_EFFECT_JUMP_DEST;
                break;
```

**Comment by Keader** [comment]
Sometimes icy grip is not casted too ._.

**Comment by Keader** [comment]
@chaodhib any idea here? :)

**Comment by chaodhib** [comment]
The current implementation of SPELL_EFFECT_JUMP is to move the caster 'x' yards away from the target, where x = target's combat reach + caster's combat reach + 0.5y.

This can easily be changed to move the caster exactly on top of the target (like this spell would require). 

However, this will break spells that uses SPELL_EFFECT_JUMP to move the caster but not exactly at the same place as where the target currently is standing at. The question is: does it happen? Is there any spells that shouldn't move the caster to where the target is standing?

If so, the answer may be in the additional data of the spell effect (https://trinitycore.atlassian.net/wiki/display/tc/Spell+Effects+Reference#SpellEffectsReference-SPELL_EFFECT_JUMP=41) which may be unimplemented or misunderstood.

**Comment by chaodhib** [comment]
The original issue has been fixed.
