### ISSUE TITLE
 VMapManager2: could not load 

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17273]
https://github.com/TrinityCore/TrinityCore/commit/6cf1446d39db994cdca2db8f7f61da8423672bb3
centos
3.3.5

Server freeze and crash for Spam 
VMapManager2: could not load ...
http://pastebin.com/ryB0w7vF

i dont know why.not new change.no update.nothing
i extract vmaps-mmaps-dbc and other from last extractor and use theme
server work perfect .without change i restart server and spam start ... player cannot connect and server crash in 10min spam

http://pastebin.com/0Gq0f6jP
http://pastebin.com/WSCgG1t2

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by SQLfix** [comment]
for me work fine . but with last restart without change i give this spams
u dont know what is wrong ?

**Comment by tkrokli** [comment]
I don't know why you get the crash, but I suggest checking for read errors on your maps files. I don't actually **know** that your files are unreadable, just suggesting that you check those files to be sure.

**Comment by Aokromes** [comment]
Maybe it's hardware issue.

**Comment by SQLfix** [comment]
i think this from GCC
becuase i use >>  scl enable devtoolset-3 bash  gcc 4.9.2
and remove gcc Defualt with version 4.7.2

and some time i test gcc version  >>> gcc --version
i see there are no command Gcc
and must type again command  >>> scl enable devtoolset-3 bash
to active gcc .... i think this is my problem

(( when spam Vmaps crash occured ))

**Comment by Aokromes** [comment]
I suggest you to try clang instead side by side gcc installation.

**Comment by SQLfix** [comment]
i check more .
when i reload Config !
"World settings reload fail: cannot open file (../etc/worldserver.conf)."

**Comment by tkrokli** [comment]
`World settings reload fail: cannot open file (../etc/worldserver.conf).`
This does not look like an issue related to VmapManager2, more like a file access issue. Could you have other forms of file read issues, like access rights or some other form of file read problems?

**Comment by SQLfix** [comment]
when VmapManager2 spam cannot load . setting reload fail ...
