### ISSUE TITLE
make error on 6.x... 

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#17277]
make error

When trying to make for the latest copy I get the following error.

Building CXX object src/common/CMakeFiles/common.dir/GitRevision.cpp.o
cc1plus: warning: /home/wow/TrinityCore/build/src/common/commonPCH.h.gch: created by a different GCC executable
cc1plus: error: one or more PCH files were found, but they were invalid
compilation terminated due to -Wfatal-errors.
src/common/CMakeFiles/common.dir/build.make:86: recipe for target 'src/common/CMakeFiles/common.dir/GitRevision.cpp.o' failed
make[2]: *** [src/common/CMakeFiles/common.dir/GitRevision.cpp.o] Error 1
CMakeFiles/Makefile2:977: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Branch: 6.x 

I think the has is 2c2bb4a2377b... I got this from the bottom line in the build/CMakeCache.txt file  

TDB Version:  Not sure what this is... is it the wow version... im running 6.2.4.21742.  

Server:  Ubuntu 16.04, Clients are MacOS and Windows.

Also... we are actively testing the code... so if you want a list of character spells that don't work... or quests.  We can supply you with anything we come across. 

Thanks

**Comment by Aokromes** [comment]
delete build directory and rerun cmake.

**Comment by dipdill** [comment]
Is that the correct hash to reference on future bugs?  And is the TDB Version the client version?

**Comment by tkrokli** [comment]
TC core revision hash is correct, it becomes a link when you have pasted it into these pages.
TDB is the TrinityCore DataBase, so it is usually 335.61 for 3.3.5 and 6.04 for 6.x (info shown in your worldserver console (and also in the authserver/bnetserver console).
