### ISSUE TITLE
SKill class/race mask not applying from DB in game - being ignored

### ISSUE THREAD

**Issue by resinate** [TrinityCore/TrinityCore#17272]
**Description**:
i set class and race mask to 0 on both to enable swords on everyone yet it doesnt work. aka priests with swords. if i hardcore add in the spell id it says i dont have profession even tho item name is white

were talking about the table - playercreateinfo_skills and playercreateinfo_spell_custom

**Current behaviour**: Tell us what happens
doesnt read the masks

**Expected behaviour**: Tell us what should happen instead
db should over-write dbc values

**Steps to reproduce the problem**:

1. set db values to 0
2. give sword
3. try to equip it

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
TrinityCore rev. 9db75766e77b69295551c987eaa2b965a7c6f45c 2016-06-02 15:57:39 -0700 (3.3.5 branch) (Win64, Release)

**TC hash/commit**:  
9db75766e77b69295551c987eaa2b965a7c6f45c

**TDB version**:  
TDB 335.61

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ariel-** [comment]
After modifying item_template be sure to clear the client cache (delete Cache folder)
besides that, client has some checks that can't be overriden serverside.

**Comment by resinate** [comment]
im talking about playercreateinfo_skills my bad

**Comment by Aokromes** [comment]
Custom modifications don't belongs here.

**Comment by Shauren** [comment]
You cannot add skills to race+class combinations that wouldn't normally be able to learn them with playercreateinfo_skills table
