### ISSUE TITLE
[3.3.5] DB / creature: remove incorrect Death Knight Initiate spawn

### ISSUE THREAD

**Issue by lyn1337** [TrinityCore/TrinityCore#17280]
core_version: TrinityCore rev. 8d2ccc4d1a88 2016-06-04 15:14:08 +0100 (3.3.5 branch) (Unix, Release)
db_version: TDB 335.61

There appears to be a Death Knight Initiate spawned in the air that isn't supposed to exist.

Tested Query: Yes
Suggested Fix:

```sql
-- remove incorrect "Death Knight Initiate" (entry: 28393) spawn
DELETE FROM `creature` WHERE `guid`=129452;
```

**Comment by Aokromes** [comment]
Duplicate, incorrect fix, also it needs mini-event.

**Comment by lyn1337** [comment]
@Aokromes That isn't precise. This particular spawn is both unverified and misplaced.

**Comment by Aokromes** [comment]
What's suposed to be un-precise? i told you it's duplicate ticket of 6631, where it's wrote that deleting the mob is incorrect fix because the mob needs one mini-event needing waypoints.
