### ISSUE TITLE
Unable to switch to the area when the battle is in progress

### ISSUE THREAD

**Issue by ryoting** [TrinityCore/TrinityCore#17295]
**Description**:
In some raid  instance(e.g.icc/ruby sanctum ..etc),when all players has died on some boss's phase inprogress ,the ghost of player come to enter instance to relive,but system tips "Unable to switch the zone when the battle is in progress",all players can't enter instance.
When all player is died.they all revive from Spirit Healer.then can enter instance , no that tips again.

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
e.g the instance of ruby sanctum .Difficulty:25 normal
1. all player in group attack halion until phase 2.
2. all player to die
3. the ghost of player come back to instance,then can't enter it,tips "can't switch zone when the battle is in progress"

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
f8064a5
**TDB version**:  
TDB.61
**Operating system**:  
WIN7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

sorry for my bad english

**Comment by Shauren** [comment]
Is this some horrible google translate?

**Comment by Keader** [comment]
If boss is in progress (not evaded wet) is normal...
Like in Lich King (Casting Remotless Winter for example).

**Comment by ryoting** [comment]
@Keader but all player has died,and can't enter instance a long time.

**Comment by Keader** [comment]
Has alot of issues about boss "stuck" in progress...
each boss can have different issue about it ._.
About Halion specific, the problem is: #17180

**Comment by Aokromes** [comment]
duplicate.
