### ISSUE TITLE
GO Respawntimer Fix for Quest 2038

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17296]
```sql
-- Wrong respawntimer for Quest GameObjects
-- Bingles's Toolbucket
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (104564,104569,104574);
```
http://de.wowhead.com/quest=2038/bingles-verschwundene-werkzeuge
http://www.wowhead.com/object=104564/bingless-toolbucket

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
TC>TrinityCore rev. a6e7c9873c7b 2016-06-05 12:28:19 +0200 (335 branch)
**TDB version**:  
335.61
**Operating system**:
Win7 64Bit  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lyn1337** [comment]
http://www.wowhead.com/quest=2038/

**Comment by Tauriella** [comment]
No :)

**Comment by tkrokli** [comment]
I did not see any comments on the wowhead pages below, what is your suggestion based on?
- http://www.wowhead.com/object=104564/bingless-toolbucket
- http://www.wowhead.com/object=104565/bingless-toolbucket
- http://www.wowhead.com/object=104566/bingless-toolbucket
- http://www.wowhead.com/object=104569/bingless-toolbucket
- http://www.wowhead.com/object=104574/bingless-toolbucket

**Comment by Tauriella** [comment]
You need for this Quest 4 Items 3 Items have in the DB 300 Sek. 104564,104569,104574 but one Item 104575 have 2Sek.
PS:5Min's respawntime its a Horror for a Group :-1: 
http://www.wowhead.com/object=104575/bingless-blastencapper

Blizzard fixed the bad respawntime because it is important for Players in a Group

**Comment by Tauriella** [comment]
Yes and the Group have a smoother gameplaying

**Comment by tkrokli** [comment]
Thank you for the extra info. I did not know that the current respawn time is as much as 5 minutes for all but one of the items. I agree that anything above 1 minute respawn time is too much for items when they are part of a shareable quest (very likely group quest). What I meant to ask is if they should be on something like a 5 or 10 second respawn timer, but if the TC developers agree on 2 seconds, I won't disagree on that decision. I just wanted to know if there are any other regular respawn timers like the one you mentioned, http://www.wowhead.com/object=104575/bingless-blastencapper , but this is OK.

**Comment by lyn1337** [comment]
@Tauriella 
I dont' think this is right. The one object respawning much faster as just as unverified as the others and as far as I can remember, both 5m and 2s seem extreme.
It took me a while to find this old [YouTube video](https://www.youtube.com/watch?v=zc9WxkHgC4Y), but I think (thanks to the troggs) you can at least make out this is higher than 2s … maybe 10s.
Yes / No / Maybe ?

**Comment by tkrokli** [comment]
From what I could see in that video, the item was looted at https://youtu.be/zc9WxkHgC4Y?t=16s and it had not respawned at least 4 seconds later (0:20) and _maybe_ not at 0:21 either, but it suggests that respawn time should be at least 5 seconds. 10 seconds is also an acceptable respawn time. It would be nice if someone with experience from object respawn times could comment on 2s / 5s / 10s respawn time.

**Comment by Tauriella** [comment]
@tkrokli 
Yes, there are various respawntime on Liveserver
0, 2, 5, 10Sek

**Comment by lyn1337** [comment]
recommending this:
```sql
-- correct spawntimesecs for gameobjects related to quest "Bingles' Missing Supplies" (entry: 2038)
UPDATE `gameobject` SET `spawntimesecs`=10 WHERE `guid`=12863; -- "Bingles's Toolbucket" (entry: 104564)
UPDATE `gameobject` SET `spawntimesecs`=10 WHERE `guid`=12864; -- "Bingles's Toolbucket" (entry: 104574)
UPDATE `gameobject` SET `spawntimesecs`=10 WHERE `guid`=12871; -- "Bingles's Blastencapper" (entry: 104575)
UPDATE `gameobject` SET `spawntimesecs`=10 WHERE `guid`=12872; -- "Bingles's Toolbucket" (entry: 104569)
```

Setting it to 10s is still ok with 5 group members having the quest and need to loot those objects and doesn't look weird insta-respawning when only one player is soloing this quest.

**Comment by Tauriella** [comment]
@lyn1337 
Good compromis

```sql
-- Wrong respawntimer for Quest GameObjects
-- Bingles's Toolbucket
UPDATE `gameobject` SET `spawntimesecs` = 10 WHERE `id` IN (104564,104569,104574,104575);
```
