### ISSUE TITLE
[3.3.5, but maybe all]: Events not scripted

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17293]
**Description**:
Operation "Gnomeregan", Zalazane's Fall, Elemental Invasion, Scourge Invasion not (fully) scripted.
**Current behaviour**: Tell us what happens
If we running events from this list, quest not working. Or events not working AT ALL.
**Expected behaviour**: Tell us what should happen instead
We need succesfully working events. It is the end of WotLK, mobs talking about Cataclysm things!
**Steps to reproduce the problem**:

1. Run some events from this list.
2. Try to complete some quests. You will be use autocomplete.
3. Try to complete latest quest. It maybe not working AT ALL.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
Maybe, all.
**TC hash/commit**:  
3bba685
**TDB version**:  
Maybe, all.
**Operating system**:  
All.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by dr-j** [comment]
Probably becase these are events which have run max 1-2 times in World of Warcrafts entire history or are not reoccuring events but one off usually an event which is active about 4 weeks before a new expansion is due.

As for Operation Gnomeregan and Zalazanes fall quest chain are linked and believe both can be completed upto the quest to get gnomeregan pride/darkspear pride (Alliance chain is permamently available as none of the npcs or quests are linked to an event, horde can only see npcs/take quests if Zalazanes fall event is active.

**Comment by DDuarte** [comment]
Focus on reporting specific issues, your description is too broad.

P.S Zalazane was fully scripted years ago: 21818fb76010b18e5751cf026af7409f5e72771f `.event start 61`

**Comment by Aokromes** [comment]
Also, elemental invasions #8607
