### ISSUE TITLE
Core/ThreatManager: doAddThreat doesnt send correct ThreatRefStatusChangeEvent to container.

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#17298]
**Description**:

``doAddThreat`` function doesnt send the correct event to container: on threat change, the container doesnt reorder the list as expected.
If there aren't any other events that make the list dirty (and then make a reorder on next update), it will continue forever unordered.
Therefore, functions like SelectTarget may return incorrect targets if a position is used.
(the target value (or order) managed by SelectTarget its the same as threatlist)

``doAddThreat`` is used in ``void Spell::EffectTaunt(SpellEffIndex /*effIndex*/)`` so any taunt spell wont make the threatlist reorder after threat consolidation.

**Expected behaviour**:
The list should be reordered (set as dirty) if the top threat value is not the first element on it.

**Steps to reproduce the problem**:

1. Go to Lich King with two characters.
2. Make it change to phase 2.
3. Make the character without LK aggro use a taunt spell on it.
4. See how defile is always used on the current "tank".

related code to the example:
````c++
if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true, -SPELL_HARVEST_SOUL_VALKYR))
{
    Talk(EMOTE_DEFILE_WARNING);
    DoCast(target, SPELL_DEFILE);
}
````

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  
7ff0f3c65fd0c068560351eac92e96a8527c96a7

**Comment by jackpoz** [comment]
strange how there's a particular function for taunt too https://github.com/TrinityCore/TrinityCore/blob/caa1b82b88edf1d425aa147c8f5851df0a5d14d2/src/server/game/Combat/ThreatManager.cpp#L485
which events do make the list dirty and trigger a reorder ?

**Comment by ccrs** [comment]
> which events do make the list dirty and trigger a reorder ?

````c++
enum UNIT_EVENT_TYPE
{
    // Player/Pet changed on/offline status
    UEV_THREAT_REF_ONLINE_STATUS        = 1<<0,

    // Threat for Player/Pet changed
    UEV_THREAT_REF_THREAT_CHANGE        = 1<<1,

    // Player/Pet will be removed from list (dead) [for internal use]
    UEV_THREAT_REF_REMOVE_FROM_LIST     = 1<<2,

    // Player/Pet entered/left  water or some other place where it is/was not accessible for the creature
    UEV_THREAT_REF_ASSECCIBLE_STATUS    = 1<<3,

    // Threat list is going to be sorted (if dirty flag is set)
    UEV_THREAT_SORT_LIST                = 1<<4,

    // New target should be fetched, could tbe the current target as well
    UEV_THREAT_SET_NEXT_TARGET          = 1<<5,

    // A new victim (target) was set. Could be NULL
    UEV_THREAT_VICTIM_CHANGED           = 1<<6

    // Future use
    //UEV_UNIT_KILLED                   = 1<<7,

    //Future use
    //UEV_UNIT_HEALTH_CHANGE            = 1<<8,
};
````

the problem is somewhere between the calls, I only know the result: no event is selected.

> isn't unitTarget->getThreatManager().setCurrentVictim(forcedVictim) enough to update the current target ?

certanly its not, even more:
````c++
void ThreatManager::setCurrentVictim(HostileReference* pHostileReference)
{
    if (pHostileReference && pHostileReference != iCurrentVictim)
    {
        iOwner->SendChangeCurrentVictimOpcode(pHostileReference);
    }
    iCurrentVictim = pHostileReference;
}
````
seems like it should never be used outside the manager.

> if the issue happens only in UnitAI::SelectTarget() with SELECT_TARGET_TOPAGGRO/SELECT_TARGET_BOTTOMAGGRO then that's a bug in that function, not in how the threat in managed and should be fixed there.

Nope, the problem is not the selection method. The function itself relies on threatcontainer being ordered (as its designed to) and I wouldn't change anything there.

> With the blackbox approach, there's no guarantee me->getThreatManager().getThreatList() will ever return a sorted list.

If all the events are handled correctly, it is guaranteed.

> It could make sense to add another function to me->getThreatManager() to return a threat-sorted list always getSortedThreatList() that will be a copy of the original one

I thought about that too as a temporal fix, that would be "hacking our way out", right? :dancer:

**Comment by jackpoz** [comment]
the event is supposed to be triggered at https://github.com/TrinityCore/TrinityCore/blob/caa1b82b88edf1d425aa147c8f5851df0a5d14d2/src/server/game/Combat/ThreatManager.cpp#L145 , could you breakpoint it on Spell::EffectTaunt() to check if it's actually called or how come it's skipped ?

**Comment by ccrs** [comment]
I'll trace it right now, my bets are the problem is here:

````c++
        case UEV_THREAT_REF_THREAT_CHANGE:
            if ((getCurrentVictim() == hostilRef && threatRefStatusChangeEvent->getFValue()<0.0f) ||
                (getCurrentVictim() != hostilRef && threatRefStatusChangeEvent->getFValue()>0.0f))
                setDirty(true);                             // the order in the threat list might have changed
            break;
````

**Comment by ccrs** [comment]
k
everything works, the event is sent correctly and the container is set as dirty.
something is off at the reorder.

**Comment by ccrs** [comment]
````c++
namespace Trinity
{
    // Binary predicate for sorting HostileReferences based on threat value
    class ThreatOrderPred
    {
        public:
            ThreatOrderPred(bool ascending = false) : m_ascending(ascending) { }
            bool operator() (HostileReference const* a, HostileReference const* b) const
            {
                return m_ascending ? a->getThreat() < b->getThreat() : a->getThreat() > b->getThreat();
            }
        private:
            const bool m_ascending;
    };
}
````

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/63f8f54e5c1efd379ce8758a19c6b9ebfec43ed8/src/server/game/Spells/SpellEffects.cpp#L2865 that seems to set a->getThreat() the same of b->getThreat(), is there a missing +1.0f ?

**Comment by ccrs** [comment]
````
[11:53:35] <+ccrs> then we have two options
[11:53:48] <+ccrs> or change all the uses of SelectTarget with a position on scripts
[11:53:56] <+ccrs> or change the logic of SelectTarget
[11:54:08] <+ccrs> because right now it takes the threatlist
[11:54:17] <+ccrs> as reference for those
[11:54:23] <+ccrs> selections
[11:54:34] <%Shauren> if you look at my later icc scripts (not the first ones) i stopped relying on threatlist and use current target/tank instead
[11:55:22] <+ccrs> then whats the point for the normal selecttarget?
[11:55:35] <+ccrs> without a predicate as nontankselector I mean
[11:55:46] <%Shauren> random
[11:55:51] <%Shauren> really random
[11:55:54] <+ccrs> lol
[11:56:02] <%Shauren> or ancient tbc level scripts that didnt really care
[11:56:14] <%Shauren> they were really simple
````

**Comment by ccrs** [comment]
new objective: fix SelectTarget
