### ISSUE TITLE
[All] Clients for expansions not supported (downgrade)

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17299]
**Description**:
We need to support 1.12.*, 2.4.* and other versions, when "expansion" value is 0 or 1.
**Current behaviour**: Tell us what happens
If we login using client with older version header, server says "Incorrect version".
**Expected behaviour**: Tell us what should happen instead
Server must allow logging in with older client if "expansion" value not 2 (or higher)
**Steps to reproduce the problem**:

1. Set lower "extension" value
2. Use 1.* or 2.* version header
3. See error

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
All
**TC hash/commit**:  
f82f06e
**TDB version**:  
All
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
If it is not blizzlike, we don't need to implement this.

**Comment by Aokromes** [comment]
It don't works like you think, expansion 0 limits maps and races to expansion 0, 1 to bc races and classes.

**Comment by DDuarte** [comment]
> If it is not blizzlike, we don't need to implement this.

Clearly not. Wow protocol isn't backwards compatible and that doesn't depend on us.
