### ISSUE TITLE
Explosive Sheep (Engineering) Not Functioning Correctly

### ISSUE THREAD

**Issue by Vavehl** [TrinityCore/TrinityCore#1729]
Explosive Sheep do not explode, although they will randomly charge enemies.  The sheep appear to last for the correct duration (3 minutes) before disappearing, but will not detonate at all.

TrinityCore Revision: 44bb64295b3eda254a83 (from 17-May-2011)
TrinityCore Database: 335.11.40
##

**Comment by offl** [comment]
Duplicate of #21753
