### ISSUE TITLE
[Almost 3.3.5]: Battle.net functions and trial version

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17294]
**Description**:
We cannot use e-mail authentication, Battle.net chat and trial versions
**Current behaviour**: Tell us what happens
1. If we use e-mail authentication, client connects to update server and says "Update required". We need to emulate this server for user patches and/or to avoid players mistakes. And we need to allow play with e-mail address.
2. Battle.net chat not implemented in server
3. Trial version not implemented in server (only Classic, TBC, WotLK)
**Expected behaviour**: Tell us what should happen instead
1. Update server implemented and we can play with not real Battle.net accounts
2. We can talk in not real Battle.net chat
3. Server admin can set "trial" flag to account.
**Steps to reproduce the problem**:

1. Try to login with e-mail address
2. Try to find Battle.net chat in TrinityCore
3. Try to set trial version to account

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
Almost 3.3.5, some functions for all patches.
**TC hash/commit**:  
3bba685
**TDB version**:  
All (we need to set "0" as "Trial" in "expansion")
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
We can't fix this.
