### ISSUE TITLE
[ALL]: Blizzlike authentication vulnerability

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17290]
**Description**:
We have vulnerability with authentication. It is blizzlike.
**Current behaviour**: Tell us what happens
If we using password "qwerty", we can authenticate. If we using "QWERTY", we can authenticate, too. Same error with login/e-mail address
**Expected behaviour**: Tell us what should happen instead
If we using password "qwerty", we must authenticate. If we using "QWERTY", we must not authenticate.
**Steps to reproduce the problem**:

1. Create an account
2. Try to login with default login and username in database. Look like QWERTY:123
3. Try to login with modified login and password. Look like qWErtY:123

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
All
**TC hash/commit**:  
3d93c12
**TDB version**:  
All
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
Not this commit. ALL commits. It is latest.

**Comment by Aokromes** [comment]
Blizzlike, intended, won't fix.

**Comment by stas730** [comment]
I think, we need only caps/not caps checker. But in custom patch. :(:
I created topic on the forum about free (as in freedom) World of Warcraft. If this can be developed, I can implement this in client (maybe).
https://community.trinitycore.org/topic/12710-we-need-to-create-free-open-source-wow-client/
P. S. Malcrom wrote "Aokromes, can you start this please." it this topic.
