### ISSUE TITLE
[6.x] QuestLog is missing QuestObjective details

### ISSUE THREAD

**Issue by Anddrw** [TrinityCore/TrinityCore#17297]
**Description**: 
1. The sidebar questlog is missing questobjective details after server restart.
2. If you logout/login you don't have any quests in the sidebar (you have to press track again).

Proof: http://prntscr.com/bctqnq

**Current behaviour**: Missing collected items, even if they are collected.

**Expected behaviour**: Should show collected items/quests in questlog.

**Steps to reproduce the problem**:

1. Take a quest.
2. Complete the objectives (loot)
3. Restart server.

**Branch(es)**: 6.x 

**TC hash/commit**:   9d7a17d

**TDB version**:  6.04

**Operating system**:  Linux/Ubuntu 16

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Shauren** [comment]
Does it only happen on collect item objectives or killing creatures too?

**Comment by Anddrw** [comment]
@Shauren, i think its happening to any kind of quest, ill check again just to make sure.

**Comment by Anddrw** [comment]
@Shauren, yeah, its happening to every kind of quest.

**Comment by Nelidon** [comment]
The thing is tracking or not a quest isn't notified to the server.

**Comment by Aokromes** [comment]
Maybe related to #15225 ?

**Comment by Rushor** [comment]
nope, this issue is only about the missing objectives [0/3 - killed turkey] 

while you already have [3/3 - killed turkey] in your inventory, the system will still show the [0/3 - killed turkey] in the top right hand corner after serverrestart
