### ISSUE TITLE
[3.3.5a] More UNIT_FLAG_IMMUNE_TO_PC flag problems

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#17302]
I've found some more bosses that have the same behaviour as nefarian before the https://github.com/TrinityCore/TrinityCore/commit/650d7ab596bf956d146a147fdc938d3c6bdae022
commit. Meaning that they aggro, but don't initiate combat.

These bosses are:
Razorgore the Untamed (ID:12435)
Chrommagus (ID:14020)
Broodlord Lashlayer (ID:12017)
Sindragosa (ID:36853)
Hodir (ID:32845)

They all have scriptname assigned on the DB.

**Branch(es)**: 3.3.5 

**TC hash/commit**:  f82f06e29e6bb0d1747541c9831875782bbe4270

**TDB version**:  TDB_full_world_335.61_2016_04_11 with updates

**Operating system**:  Win8.1 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by TerrorBringer** [comment]
Wowhead pages: 
http://www.wowhead.com/npc=12435/razorgore-the-untamed
http://www.wowhead.com/npc=14020/chromaggus
http://www.wowhead.com/npc=12017/broodlord-lashlayer
http://www.wowhead.com/npc=36853/sindragosa
http://www.wowhead.com/npc=32845/hodir

**Comment by Keader** [comment]
Related with: #16346

**Comment by Treeston** [comment]
Razorgore, Chrommaggus, Broodlord: This fight has plenty of bugs, but I couldn't find any that were related to them not engaging.
Hodir: Had a pretty serious bug that prevented the encounter from ever starting, so I fixed that one while I was at it.
Sindragosa: I couldn't find the bug you are referring to.

**Comment by Treeston** [comment]
@TerrorBringer please provide detailed repro for any bugs you think are left in e5382ee. Otherwise I will assume all are fixed and close this.

**Comment by TerrorBringer** [comment]
Well, I tried the same bosses with a clean TDB(updated) and TrinityCore version https://github.com/TrinityCore/TrinityCore/commit/7c25f3cffd0c4e15a9ff08982914fd95d5cafe2f, and the only problem I have is with Sindragosa, she talks and doesn't attack, but I still take damage from the frost aura spell.(maybe just my problem)

Toxic Sporebat (ID:22149) from the Lady Vashj fight, just floats and evades you attacks instead of dropping poison bombs.

Besides that, the other bosses I mentioned in the original post work.
