### ISSUE TITLE
NO riding trainers work

### ISSUE THREAD

**Issue by Informatique101** [TrinityCore/TrinityCore#17305]
NO RIDING TRAINERS WORK. Aokromes said that a lot of trainers were fixed, but I guess not I can`t find one, My databse is up to date, Everything is up to date. **[14682]**(https://github.com/TrinityCore/TrinityCore/issues/14682) doesn`t help me I already read it 44 times.

Can`t learn riding skill.

Should be able to learn riding skill :)

**Steps to reproduce the problem**:

1. Try and learn riding skill from any trainer.

TrinityCore rev. 8396dabdad65 2016-06-06 09:16:59 +0200 (6.x branch) (Win64, Release)
TDB 6.04 with all updates. 
Windows 7 ultimate x64

Thanks ;)

**Comment by Aokromes** [comment]
don't open new tickets, add info on existing opened ticket
