### ISSUE TITLE
Riding & Profession trainers not working?

### ISSUE THREAD

**Issue by Informatique101** [TrinityCore/TrinityCore#17304]
Riding & Profession trainers are not working.

Go to riding trainer and can`t learn any flying skills, The `Learn` button is greyed out. Go to profession trainer and no menu shows up (nothing happens when you right click)

The `Learn` button for the riding trainer should be available, and the menu for the profession trainer should show up.

Go to any riding/profession trainer and you will see.

 TrinityCore rev. 8396dabdad65 2016-06-06 09:16:59 +0200 (6.x branch) (Win64, Release)

**TDB version**:  TDB 6.0.4

**Operating system**:  W7 Ultimate X64

Everything is up to date, fresh build, did everything properly and core is also set to auto update from sql/updates (which it did sucessfully)

**Comment by Aokromes** [comment]
#14682

**Comment by Informatique101** [comment]
I saw that this was supposed to be fixed (The riding trainers) in update 2016_05_31_00_world.sql - which was obviously done, and it still doesn`t work for me... (I even tried manually executing the query to my world DB and still no luck)

**Comment by tkrokli** [comment]
@Informatique101 : you are welcome to post a new comment on #14682 if you find that there is something wrong with those trainers and if you have an idea of what needs to be done to fix it. :)

**Comment by Aokromes** [comment]
#10570
