### ISSUE TITLE
[3.3.5] DB / trinity_string: wrong string about character customization + minor fix

### ISSUE THREAD

**Issue by lyn1337** [TrinityCore/TrinityCore#17306]
**Steps to reproduce the problem**:

1. 
SELECT `content_default` FROM `trinity_string` WHERE `entry` IN(344,345,346);

**Branch(es)**: 3.3.5 / 6.x (most likely)

**TC hash/commit**:  7ff0f3c65fd0

**TDB version**:  TDB 335.61

**Source**: Tested ingame and via setting the `at_login` field in `characters` table to 8. [tc wiki](https://trinitycore.atlassian.net/wiki/pages/viewpage.action?pageId=2129969#characters%28table%29-at_login)

**Suggested Fix**:
(Tested Query: Yes)
```sql
-- fix string in trinity_string incorrectly implying character customization is forced at login
UPDATE `trinity_string` SET `content_default`='customization for player %s will be requested at next login.' WHERE `entry`=345;
UPDATE `trinity_string` SET `content_default`='customization for player %s (GUID #%u) will be requested at next login.' WHERE `entry`=346;

UPDATE `trinity_string` SET `content_default`='You already have a pet.' WHERE `entry`=344; -- add missing article
```

**Comment by tkrokli** [comment]
Nice, that is actually what we usually call "engrish text" in the TC source and I used to fix them. ;-)
TrinityCore rev. 7ff0f3c65fd0 2016-06-05 21:53:38 +0200 (3.3.5 branch) (Win64, Release) / TDB 335.61 + updates up to and including `2016_06_05_12_world.sql` - current content:
```sql
SELECT `entry`,`content_default` FROM `trinity_string` WHERE `entry` IN (344,345,346);
```
```
entry  content_default
-----  --------------------------------------------------------------------------
  344  You already have pet.
  345  Forced customize for player %s will be requested at next login.
  346  Forced customize for player %s (GUID #%u) will be requested at next login.
```

**Comment by lyn1337** [comment]
@tkrokli Oh yes, I've seen your contributions, all of them being great.
I'll refer to this as engrish in the future then, though it did quite remind me of fin pals talking english. :grin:
