### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17308]
I dont know what is this crash
http://pastebin.com/0Pw84a25

https://github.com/TrinityCore/TrinityCore/commit/123e45c119b39ec36e5051bf83f52da2fa75f376
3.3.5
centos

**Comment by Vincent-Michael** [comment]
try:
https://gist.github.com/Vincent-Michael/e9031ae69a23b6fd8c09ed10bcdbc436
