### ISSUE TITLE
[3.3.5][Trial of The Crusader/Anub'arak] Permafrost dont hit anub'arak minions

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17317]
**Description**: [Permafrost](http://www.wowhead.com/spell=66193/permafrost), casted by [Frost Sphere](http://www.wowhead.com/npc=34606/frost-sphere) should hit (get slow) in Anubarak Minions.

**Current behaviour**: When anubarak minions is under permafrost area, effect of permafrost is not applied.

**Expected behaviour**: Effects of permafrost should be applied in Anubarak minions

**Steps to reproduce the problem**:
1. Go to Anubarak (.go xyz 760 179 143 649)
2.  Add an temp anubarak (.npc add temp 34564)
3. Kill some Frost Sphere.
4. Walk to some minion under permafrost area.

**Branch(es)**: 3.3.5

**TC hash/commit**:  650d7ab596bf956d146a147fdc938d3c6bdae022

**TDB version**:  335.61 + updates

**Operating system**:  Win10

**Old Issue about it: #5963**

PS: I tried fix it using conditions: https://gist.github.com/Keader/e024776fad26bb5d39c875c2b2544503
but dont work.

Npcs Faction is right, checked with sniff.
Looks like faction issue, like cited in #5963
if Permafrost is casted by player or some faction hostil to faction 16/14, spell hits anubarak minions (with issues, but hits)

**Comment by joschiwald** [comment]
no, it is the same problem like #16999 #17312

**Comment by Keader** [comment]
How ?!
i dont see where is linked

**Comment by joschiwald** [comment]
the thing about SPELL_ATTR3_ONLY_TARGET_PLAYERS is just a part of the issue, the problem here area auras ignores conditions

the real issue:
>they do not follow generic target selection

**Comment by Keader** [comment]
@mik1893 we need an tc god now !!!

**Comment by mik1893** [comment]
@Keader let me see what we can do

**Comment by mik1893** [comment]
so, looks like with #17321 , the area aura check target issues are fixed - but not this one.
so it might need a bit more of investigation

**Comment by joschiwald** [comment]
the problem is a bit deeper than this target check

**Comment by mik1893** [comment]
yes, i've done some checks with Keader - it is due to the positive - non positive nature and the factions of the caster vs the target..

**Comment by ariel-** [comment]
Is this still valid? Permafrost uses TARGET_UNIT_DEST_AREA_ENTRY, which shouldn't do absolutely no faction checks (basically target everything that hasn't conditions)

**Comment by Killyana** [comment]
Yes still valid.

**Comment by ariel-** [comment]
Different issue, area auras were already fixed, the problem now are dynamic object auras, we probably should implement similar searcher logic like Spell. basically dynobject if it's not an ally aura tries to search for 'attackable' targets, but it must ignore faction checks because of 'entry'. Also it's ignoring conditions as it is now
