### ISSUE TITLE
[3.3.5]: Frostmourne not adding the Lich King armor

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17310]
**Description**:
Frostmourne adds a buff "New Lich King". It is bugged.
**Current behaviour**: Tell us what happens
Buff not working.
**Expected behaviour**: Tell us what should happen instead
See https://youtube.com/v/AMKQwbiMwmM, Frostmourne must add Lich King armor (buff).
**Steps to reproduce the problem**:

1. Add Frostmourne (or use buff)
2. Check your character's armor (visual)
3. No Lich King armor

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  
e5382ee
**TDB version**:  
YTDB, not TDB. I am Russian.
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Keader** [comment]
need add a "morph"?

**Comment by stas730** [comment]
P. S. I always use latest database version & patches. Now I am trying to find open-source WoW client and I'm not playing (for now).

**Comment by stas730** [comment]
Maybe, not morph. We need to add Lich King armor, that exists in client (models) but not exists in DB (and must not to be added). We need to add non-real armor.

**Comment by stas730** [comment]
Watch video, please. Not morph. And not full Lich King armor set.

**Comment by Shauren** [comment]
Hahaha, nice try. The video is just some random guy made on his custom pserver.

**Comment by stas730** [comment]
Blizzlike frostmourne does not change the skin?

**Comment by stas730** [comment]
Oh, not skin. Visual armor.

**Comment by Keader** [comment]
"no one" have this weapon on retail...

**Comment by Shauren** [comment]
And to my knowledge, LK armor does not exist in the client as wearable components and cannot be used by players (you either go full LK model or nothing)

**Comment by stas730** [comment]
Models are exist and CAN be added without client patches. Some items not exists. I will check the client patch with this armor if I find open-source WoW client.

**Comment by stas730** [comment]
*To create wearable items, we need DBC patch and icons.

**Comment by tkrokli** [comment]
Not going to happen. TC will not modify the game client nor make patches or icons for it.

**Comment by stas730** [comment]
Repeating questing — Blizzlike Frostmourne not adding Lich King armor on 3.3.5? What is doing buff?

**Comment by tkrokli** [comment]
Frostmourne is not available on retail (and never was). Your question is academic. Check the TC forum.

**Comment by stas730** [comment]
Why it wontfix? Tomorrow, I will check client patch on second computer (and test PseuWoW).

**Comment by stas730** [comment]
If Lich King armor is available, I will send info.

**Comment by tkrokli** [comment]
Not needed. TrinityCore is not a "funserver" or custom content source.

**Comment by stas730** [comment]
I am new to C++, and I can't write script for replacing armor (but not changing character). Which spell implement this? I want to impemement this Frostmourne function.

**Comment by stas730** [comment]
P. S. I want to create quests for Frostmourne.
Items:
0. Some special items (some exists in standard database)
1. Broken Frostmourne
2. Frostmourne
3. Better Frostmourne

**Comment by Anddrw** [comment]
I really think that you are also new to Engrish language. You've been told
that this LK thing its not on retail, so there is nothing to implement.
Please stop trying to make others script shit for you. Have a nice day!

**Comment by stas730** [comment]
Yes, I am new to English language.
If this not implemented in official server (when 4.0.0/newer 4.0.* released), we don't need to implement non-blizzlike functions.
