### ISSUE TITLE
[Bugged Talent] Warlock , Ruin (All Ranks 1-5)

### ISSUE THREAD

**Issue by Yehonal** [TrinityCore/TrinityCore#17319]
**Description**:

Some users are suspecting the talent ruin is bugged

They tried spell incinerate until crit, adding one point to the talent ruin for viewing scale damage

but the spell doesn't have any bonus damage due to the talent ruin

**Steps to reproduce the problem:**

1) reset spec 
2) add talent points until ruin is available
3) add 1 point to ruin and test a destruction spell ( incenerate in our case ) on a target until it does a critical damage
4) add another point and re-try
5) you cannot notice any damage difference even if you add all 5 points to this talent

![ejwfwueogyaqamc_8abgwaws3_dg0rakykouge2p6d8781wffqpznzfnzmbsx8jcdz2ee6pfv-z6lvqcq2e-tbjjuv3llmegoafgi6jdmaatgialnog8oe8vcghnyuus-700ls0ggyfsgdhb1o-nqt8fl_snpq p-0ti7_lws3sufxtnj0fg4zclow](https://cloud.githubusercontent.com/assets/147092/15902294/7bd1ea2e-2da7-11e6-85e2-c07e1433d194.jpg)
![ejwfwueogyaqamc_8adyhs6c3_dg0rakykouge2p6d8781wffqpznzfnzmbsx8jcdz2ee6pfv-z6lvqcq2e-tbjjuv3llmhqw4voapelfcebgyyalsyjjoqrwllgvl6x3o-lswzgiadfkagh6pdt1e8pl-4noq no_nfrwhrclgdtnkqpl9u9vpj6s](https://cloud.githubusercontent.com/assets/147092/15902292/7bcb4804-2da7-11e6-976d-acb904e27cac.jpg)
![ejwfwueogyaqamc_8adyrzai3_dg0rakykmuge2p6d8781wffqlfvze2fmoocytuhx7cpzasc3o5cmzn0ilve0viqnd-zbj01ijogcgsoiqggzoga0dv7isma8nsnt7w1j-1suzgiadfkcgj6hcr6vchk78nhw hz_cdc5xquu8f6mocueqli-bvuy](https://cloud.githubusercontent.com/assets/147092/15902296/7bd836fe-2da7-11e6-81b5-0e331bc3223d.jpg)
![ejwnxeeogyaqamc_8abgkaxgnzx4naqj2khlyd01_xs7h_mip59ifpw5jvmp_rij-i4hu48ly0juzhzbmwsis0xmmoqvbx4kndeak0c0cbzqo4kgyqobjx75f5mbtdk6ph4vlxjttntwg6b1fuw7ffh9azuujyk rkvd7b0so6rfctgdsj981hk2phw](https://cloud.githubusercontent.com/assets/147092/15902293/7bd08260-2da7-11e6-8b68-5935b43e66e3.jpg)
![ejwnyueogyaqamc_8abgkuxwgx48goiebnqlsd01_xs71_mid7_eiipzg4tsxzks9umoph5llowoxdm2c8het4rmmdu7pzwuogmajo9oecygrgvbwxr80mbn-t-zvrtta-rpwol37bqhtwnaac9fryjvd5ybjy0 mqtutaq4vkcnaecxiovydvmx3yq](https://cloud.githubusercontent.com/assets/147092/15902295/7bd2f522-2da7-11e6-8ebe-333efe88f742.jpg)

during the test they have no item or pet or any debuff on character

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a26401360abbee575224fd47f01f8b217028c

**TDB version**:  335.61

**Operating system**:  Linux - Ubuntu 14.04

**Comment by lyn1337** [comment]
Working as it should on:

core_version: TrinityCore rev. 7ff0f3c65fd0 2016-06-05 21:53:38 +0200 (3.3.5 branch) (Unix, Release)

**Comment by mik1893** [comment]
nonsense bug.
Incinerate Ruin at 4 talents point can crit more damage than ruin 5 talent points - 
It's because incinerate damage in a range, so for example

Ruin  4 points , crit on base damage 670
Critical damage =: 670*1.8 = 1206

Ruin a 5 points , crit on base damage 600
Critical damage =: 600*2 = 1200

You need MUCH MORE TRIES to prove that a talent like ruin works, and if you do it you will discover that incinerate on a 5 points ruin does statistically 20% more damage than a 4 points - that's exactly the talent value.
