### ISSUE TITLE
Quest: Death Comes From On High / DK Starting zone quest

### ISSUE THREAD

**Issue by Informatique101** [TrinityCore/TrinityCore#17322]
Eye of acherus has no spells to inspect the buildings around the map to complete the quest

No spells except for cancel. 

**TC hash/commit**:  TrinityCore rev. 15bea97f83f6 2016-06-07 19:05:26 +0200 (6.x branch) (Win64, Release)

**TDB version**:  6.0.4

**Operating system**:  Windows 7 X64 Ultimate

**Comment by Killyana** [comment]
Spells are on the DB, but not loaded into the interface.

**Comment by Aokromes** [comment]
#14928
