### ISSUE TITLE
[3.3.5] Core/Spells: Deadly Poison

### ISSUE THREAD

**Issue by tomlevy** [TrinityCore/TrinityCore#17326]
Description:Deadly poison consumed by crippling poison , as far as i know it should be like that , they just should stack together Deadly poison damage the target and crippling poison slowing the target

Current behavior: Deadly poison consumed by crippling poison

Expected behavior: Should stack together
Steps to reproduce the problem:
1. Get rogue level 80 
2. Use Poisons : Deadly and Crippling poison
3.auto attack dummy

Ive checked it again , and Wound poison is consuming Deadly poison as well

Related Links : 
http://www.wowhead.com/spell=2823/deadly-poison
http://www.wowhead.com/spell=8679/wound-poison
http://www.wowhead.com/spell=3408/crippling-poison

Important info
If the rogue is using the talents Deadly Brew in Assassination 
http://wotlk.openwow.com/spell=51625 - rank 1 
http://wotlk.openwow.com/spell=51626 - rank 2

Means that when you using Instant poison it turns to Crippling poison and its canceling Deadly poison as well

Branch(es): 3.3.5

TC hash/commit: 80fc9cc+

TDB version: TDB 335.61

Operating system: 64bit

Video Confirm:
https://youtu.be/8jZ4BvvbizU

Edit: 
Bug also happen when stacking Deadly Poison with paladin spell
http://wotlk.openwow.com/spell=54499

**Comment by SnapperRy** [comment]
Tested, cannot reproduce. Poisons are applied and stack correctly.

Download TC again and try.

**Comment by tomlevy** [comment]
Can you try to stack Deadly poison with http://wotlk.openwow.com/spell=54499?

**Comment by tkrokli** [comment]
Suggestion for title adjustment: **[3.3.5] Core/Spells: Deadly Poison**

**Comment by Aokromes** [comment]
#17219 it looks suspicious the same.

**Comment by tkrokli** [comment]
Could also be related to **[3.3.5][Rogue] Core/Spell: Savage Combat #16242**
