### ISSUE TITLE
[6.X] Client Crash at SMSG_UPDATE_OBJECT with Transports

### ISSUE THREAD

**Issue by Palabola** [TrinityCore/TrinityCore#17335]
**Description**:
SMSG_UPDATE_OBJECT part from retail sniff / you can diff with TC local:

http://pastebin.com/1LQW4TdS

**Current behaviour**: 
- If you are entering or logging into a Zone where player using Transport such (Orgrimmar Elevator) your client getting Crashed.

**Steps to reproduce the problem**:

1.  Player 1 & 2 stay on OG elevator and go UP/DOWN
2.  Player 2 make a relog.
3. (Player 2 shouldn't need to stay on the elevator, just need to stay ~ 70 yard distance to get Crash. ) 

**Branch(es)**:  6.X

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/f583476f9ace18a578678c2f8ae7feba9de1a02d

**TDB version**:  6.X

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Shauren** [comment]
Not seeing a client crash but a disconnect instead of player 2

**Comment by Palabola** [comment]
Yes, it is the same client Disconnect instead of crashing but if you are using Sniffer or you have older computer it will be crash.
