### ISSUE TITLE
about valkyr in latest version

### ISSUE THREAD

**Issue by ryoting** [TrinityCore/TrinityCore#17333]
**Description**:
the woltk's valkyr in icc ,don't attack player, and his body in ground.
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
8457829
**TC hash/commit**:  

**TDB version**:  
61
**Operating system**:  
win7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
![a](https://cloud.githubusercontent.com/assets/12771834/15981937/51341bd4-2faf-11e6-9c62-58e94237d6f6.jpg)

**Comment by Keader** [comment]
valkyr dont attack tanker e.e

**Comment by ryoting** [comment]
i see,there have another players in this instance
