### ISSUE TITLE
3.3.5 - Disabling VMaps results in load errors

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#17349]
**Description**:

If you disable VMaps you get errors about vmaps when loading worldserver.exe. One of them even tells you that your NPC movement will be broken.

**Current behaviour**: See description

**Expected behaviour**: Since vmaps are optional, disabling them should not generate errors nor should it break NPC movement. NPCs should be able to function properly without vmaps.

**Steps to reproduce the problem**:

1. Disable all vmaps options in the CONF
2. Remove the vmaps folder from your server asset directory
3. Start the worldserver
4. You will see the following errors:

* vmap height checking disabled NPC movement will be broken expect no support
* unable to open GameObjectModels.dmtree

**Branch(es)**: 3.3.5

**TC hash/commit**:  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version**:  N/A

**Operating system**:  Windows 7

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by jackpoz** [comment]
Works as indended, vmaps are required to have proper NPC movement. Being optional means you can choose to have broken NPC movement.

**Comment by MrSmite** [comment]
> Works as indended, vmaps are required to have proper NPC movement. Being optional means you can choose to have broken NPC movement.

Ok, just curious though what do you mean by "broken"?

I've never run with vmaps enabled and other than occasional mobs running through hills instead of over them, I've never had much problem. Besides, I thought mmaps was for npc movement.

**Comment by jackpoz** [comment]
Everything that is not working correctly is considered broken and npcs ignoring terrain height fits into this category.
Mmaps' purpose is to provide a walkable path from start to end points and it's optimized for that, with the drawback that Z is only an approximation and must be corrected with vmaps data https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/PathGenerator.cpp#L581

**Comment by MrSmite** [comment]
> Everything that is not working correctly is considered broken and npcs ignoring terrain height fits into this category.

Gotcha, I assumed vmaps was optional. Also, thanks for the clarification on mmaps. I was under the impression they would eventually replace vmaps completely.
