### ISSUE TITLE
[3.3.5][6.x] DB/Quest: add race restrictions to many Blood Elf-only quests

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17342]
**Description**: the Blood Elves' starting zone (Sunstrider Isle) quests should be only available to Blood Elves. Other Horde races begin questing with "[Slain by the Wretched](http://www.wowhead.com/quest=9704/slain-by-the-wretched)", which has [a breadcrumb quest](http://www.wowhead.com/quest=8347/aiding-the-outrunners) but no prerequisite. [Source](http://www.wowhead.com/quest=8347/aiding-the-outrunners#comments:id=857244).

Also "[Report to Splintertree Post](http://www.wowhead.com/quest=9428/report-to-splintertree-post)" and "[Delivery to the Sepulcher](http://wowwiki.wikia.com/wiki/Quest:Delivery_to_the_Sepulcher)" are Blood Elf-only too (see the links for proof).

Links to every quest:
[Reclaiming Sunstrider Isle](http://wowhead.com/quest=8325)
[Unfortunate Measures](http://wowhead.com/quest=8326)
[Report to Lanthan Perilon](http://wowhead.com/quest=8327)
[Mage Training](http://wowhead.com/quest=8328)
[Solanian's Belongings](http://wowhead.com/quest=8330)
[Aggression](http://wowhead.com/quest=8334)
[Felendren the Banished](http://wowhead.com/quest=8335)
[A Fistful of Slivers](http://wowhead.com/quest=8336)
[Tainted Arcane Sliver](http://wowhead.com/quest=8338)
[The Shrine of Dath'Remar](http://wowhead.com/quest=8345)
[Aiding the Outrunners](http://wowhead.com/quest=8347)
[Warlock Training](http://wowhead.com/quest=8563)
[Priest Training](http://wowhead.com/quest=8564)
[Delivery to the Sepulcher](http://wowhead.com/quest=9189)
[Rogue Training](http://wowhead.com/quest=9392)
[Hunter Training](http://wowhead.com/quest=9393)
[Report to Splintertree Post](http://wowhead.com/quest=9428)
[Paladin Training](http://wowhead.com/quest=9676)

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `AllowableRaces`=512 WHERE `ID` IN (8325, 9393, 8328, 9676, 8564, 9392, 8563, 8326, 8327, 8330, 8345, 8336, 8334, 8335, 8338, 8347, 9428, 9189);
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=9704;
```

**Comment by MrSmite** [comment]
Nice work.
