### ISSUE TITLE
[3.3.5][6.x] DB/Loot: fix drop chance and quantity for Rough/Coarse Stone and Copper/Tin ore from mining veins

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17341]
**Description**: title says it all. Current chance is 25%, far too low. Wowhead says 80% and it seems quite accurate from experience. 50% is what webarchive data suggests.

MaxCount for Rough Stone is 6, for Coarse Stone it's 8. [Source](http://web.archive.org/web/20100614184319/http://www.wowhead.com/object=1732/tin-vein) (if you aren't picky and don't mind checking javascript in html source).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `gameobject_loot_template` SET `Chance`=50, `MaxCount`=6 WHERE `Item`=2835 AND `Entry` IN (1502, 1735, 2626, 18092);
UPDATE `gameobject_loot_template` SET `Chance`=50, `MaxCount`=8 WHERE `Item`=2836 AND `Entry` IN (1503, 1736, 2627, 18093);
UPDATE `gameobject_loot_template` SET `MaxCount`=4 WHERE `Item` IN (2770, 2771) AND `Entry` IN (1502, 1503, 1735, 1736, 2626, 2627, 18092, 18093);
```

**Comment by lyn1337** [comment]
According to wowhead, this should apply to even more templates.
```sql
UPDATE `gameobject_loot_template` SET `Chance`=80 WHERE `Item` IN (2835, 2836) AND `Entry` IN (1502, 1503, 1735, 1736, 2626, 2627, 18092, 18093);
```

**Comment by SnapperRy** [comment]
You're right, I missed two entries :P thanks!

**Comment by lyn1337** [comment]
@SnapperRy 
…at your service. :stuck_out_tongue_winking_eye:  great fixes of yours.

**Comment by PiskelDEV** [comment]
How you wanna know If 25% was in WOTLK time, and 80% since Cata+ ?

**Comment by lyn1337** [comment]
@PiskelDEV 

> it seems quite accurate from experience.

I haven't mined on blizz servers since late BC, but 80 seems very correct to me.

**Comment by Killyana** [comment]
The actual wowhead cannot be used ss source to update drop rates.

**Comment by SnapperRy** [comment]
@PiskelDEV:

OpenWoW is run by a private server, the informations found there are as accurate as the informations found on TDB.

Stones in mining veins are very common, only a bit less than the ores themselves. [Here's a random comment](http://www.wowhead.com/object=1731/copper-vein#comments:id=518711), and I'm sure you'll find many others if you search a bit.

**Comment by SnapperRy** [comment]
Been inspecting a bit around [here](https://web.archive.org/web/20100604022459/http://www.wowhead.com/object=1731/copper-vein#mining), although the javascript isn't working correctly there's still good data to be found in the html source.

```javascript
_totalCount: 3510320, data: [
{"classs":7,"id":2770,"level":10,"name":"6Copper Ore","slot":0,"source":[2,5],"sourcemore":[{"n":"Rathis Tomber","t":1,"ti":16224,"z":3433}],"subclass":7,count:3516905,stack:[1,4]},
{"classs":7,"id":2835,"level":5,"name":"6Rough Stone","slot":0,"source":[2],"subclass":7,count:1805311,stack:[1,6]},
```

Chance seems to be around 50% (I still believe it's higher, but meh) and stack size is much lower than actual TDB.

**Comment by MrSmite** [comment]
I personally don't know what mining was like on retail but it always seemed like there wasn't enough stone on Trinity though I think 80% is too high unless you're guaranteed to get at least one copper. I'd hate to mine and get nothing but stone.

Even gems seem low but with Prospecting it's not as bad.

**Comment by lyn1337** [comment]
> Chance seems to be around 50% (I still believe it's higher, but meh) and stack size is much lower than actual TDB.

Not sure about these, I remember getting more stones from mining that I had to destroy due to insufficient inventory space. But yeah, 25% was way too low and doesn't make much sense I guess.

**Comment by Aokromes** [comment]
openwow uses YTDB, it don't must be trusted.

**Comment by PiskelDEV** [comment]
Alright , didnt know that - good to know. Just tried to help :smile:
