### ISSUE TITLE
[3.3.5] DB/Spells: Renewed Hope internal CD

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17352]
**Description**: Spell need have 15 sec of internal cooldown.

**Current behaviour**: Spell has no icd.

**Expected behaviour**: Spell should have icd

**Steps to reproduce the problem**:

1. Use Power Word Shield in two targets
2.  Renewed Hope will proc for every cast of PWS

**Branch(es)**: 3.3.5

**TC hash/commit**:  7db377c7f9743226ee18a496af8d2569917c15c9

**TDB version**:  335.61

**Operating system**:  Win10

Suggested Fix:

```sql
UPDATE `spell_proc_event` SET `Cooldown`=15 WHERE `entry`=-57470;
```

**Comment by tkrokli** [comment]
Suggestion for title adjustment: **[3.3.5] DB/Spells: Renewed Hope internal CD**

**Comment by P-Kito** [comment]
I know where you know that from :D
