### ISSUE TITLE
[6.x] Not working Glyphs system. Bug client.

### ISSUE THREAD

**Issue by wethor** [TrinityCore/TrinityCore#17351]
**Description**:
Glyphs system not working.
More detailed -> 

![screenshot_3](https://cloud.githubusercontent.com/assets/19887974/15990533/899ee850-3095-11e6-9e8b-f24858de1480.png)

**Current behaviour**: Client Bugged. Сannot use.

**Branch(es)**: 6.x

**TC hash/commit**:  c529566ac41e6d14c33015664e43c195a7a36bb6

**TDB version**:  6.x

**Operating system**:

**Comment by Anddrw** [comment]
How's this even related with the server?

**Comment by Aokromes** [comment]
Maybe it's some bad packet.

**Comment by tkrokli** [comment]
Confirmed, I see this too, default client and straight TC branch 6.x source code from current revision:
TrinityCore rev. f6637439f484 2016-06-18 16:23:55 +0200 (6.x branch) (Win64, Release, Static)

**Comment by PortgasDAce** [comment]
Not update to date anymore? because blizz removed the Glyph Window

**Comment by Shauren** [comment]
Glyph ui removed, issue outdated
