### ISSUE TITLE
[Not game bug]: Open source server, closed source client

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17361]
**Description**:
We need open source client.
**Current behaviour**: Tell us what happens
TrinityCore team developing open source server. No one attempt to develop client.
**Expected behaviour**: Tell us what should happen instead
We need to develop open source client. We can do it 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
All
**TC hash/commit**:  
813e33b
**Operating system**:  
Windows, OS X. GNU/Linux with "OSX" OS?

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by stas730** [comment]
Sorry if it is incorrect issue.

**Comment by Aokromes** [comment]
This is not open source trinitycore client tracker.

**Comment by stas730** [comment]
Where to post this "issue"?

**Comment by SnapperRy** [comment]
Blizzard's forums.

**Comment by Shauren** [comment]
No, seriously, developing a client is not a goal of this project and will never be.

**Comment by stas730** [comment]
Blizzard are idiots. It will close my topic. And account which uses fake data.
I need site, where we can start developing "Free WoW Project".

**Comment by DDuarte** [comment]
If you know JS you can help with https://github.com/wowserhq/wowser

**Comment by stas730** [comment]
I disabled JS. And this client can connect to servers now?

**Comment by stas730** [comment]
UPD: Maybe, yes. I need non-browser client, but I can check code.
