### ISSUE TITLE
[3.3.5] DB/NPC: Wrong gossip texts for Argent Tournament faction vendors

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#17368]
**Description**:
Argent Tournament factional vendors always tell you you need to be a champion of that faction before you may trade with them, even when you are a champion and can buy stuff from them.

[Trellis Morningsun](http://www.wowhead.com/npc=33557/trellis-morningsun) is a good example of this issue, although as far as I can tell all of the similar vendors have the same issue.

**Expected behaviour**: Vendors should only show this gossip text if you are not a champion with their faction. If you're a champion, you should simply be able to buy items from them.

3.3.5a / commit 813e33b9

**Comment by tkrokli** [comment]
Sounds like wrong `conditions` for the gossip, although I have trouble getting conditions to work with reputation changes, particularly with Lothos Darkbargainer in the Grim Guzzler in BRD (still on retail).

**Comment by dr-j** [comment]
Well on retail you do see no gossip if you meet the requirements to access vendor when you right click on the vendor it opens straight to vendor list (ie no gossip) gossip is only for if you dont meet the requirements.

This used to work or gossip would not be displayed as Im sure if a npc only had a single gossip option and was not just chat it would open automatically to that option as soon as the npc is interacted with.

**Comment by Killyana** [comment]
Try this and clean the client cache.
``` sql
UPDATE  `creature_template` SET `type_flags`=0 WHERE `entry` IN (33557,33555,33553,33556,33554,33657,33653,33307,33310,33650);

**Comment by velinath** [comment]
@Killyana Test works great as a fix.

If there are other NPC's with this condition are you thinking open up new issues? I think there might be a couple, can't look at them right now to confirm (the flight master and Rathis Tomber in Tranquillien spring to mind, but again, I haven't tested yet - just working off memory), but I would imagine there's no real commonality that we can leverage to just batch-update everything that does this.

**Comment by Killyana** [comment]
If there's a similar issues open another ticket.
