### ISSUE TITLE
DB/Quest: Mission Accomplished

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#17379]
**Description**:
It Appears http://www.wowhead.com/quest=5237/mission-accomplished and http://www.wowhead.com/quest=5238/mission-accomplished maybe wrong way around since the quest which is currently given to alliance actually gives rep with horde and the one which is given to horde gives reputation with alliance, both also correctly give rep with the argent dawn.

**Current behaviour**: Tell us what happens
Return either quest and you will find you only receive 1000 rep with argent dawn and no other rep
**Expected behaviour**: Tell us what should happen instead
You should receive 500 rep with horde or alliance and 1000 rep with argent dawn you do not receive the reputation with your faction as this as the reputation rewarded is for opposite faction.

Also note that wowhead data is wrong too (maybe why we have wrong data in db) or it says that alliance quest gives horde rep and horde quest gives alliance rep.

**Branch(es)**: 3.3.5 Only as depreciated in 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/cc7adf9f9cf49633ba76b5ebc86e69af382ea839

The below swaps these around since believe reputation reward fields are dbc so should not be changed

~~~sql
UPDATE `quest_template` SET `AllowableRaces`=1101 WHERE  `ID`=5237;
UPDATE `quest_template` SET `AllowableRaces`=690 WHERE  `ID`=5238;

DELETE FROM `creature_queststarter` WHERE `quest` IN(5237,5238);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES
(10837, 5238),
(10838, 5237);

DELETE FROM `creature_questender` WHERE `quest` IN(5237,5238);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(10837, 5238),
(10838, 5237);

DELETE FROM `quest_template_addon` WHERE `ID` IN(5237,5238);
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(5238, 0, 0, 0, 5236, 0, 0, 101, 86400, 0, 0, 0, 0, 0, 0, 0, 0),
(5237, 0, 0, 0, 5226, 0, 0, 107, 86400, 0, 0, 0, 0, 0, 0, 0, 0);

**Comment by SnapperRy** [comment]
@dr-j: I'd think that quest ids/texts are more likely to be correct compared to reputation fields.

If you swap the quests, you'd also have to swap all the description/requestitems/offerreward texts. And texts/quest ids are the one thing Wowhead (almost?) always gets right.

**Comment by dr-j** [comment]
Well talking of description in quest template all fields are null except for title, no text on quest details and quest request items either and then on quest offer reward both have exactly the same text '$N, your successful re-engineering of the cauldrons is a tremendous victory for us!$B$B<The commander clears his throat and begins to bellow loudly.>$B$BLet all within my presence hear: for service to the Kingdom of Stormwind and to the Alliance above and beyond the call of duty - in the face of overwhelming odds and incredible danger, might I add - I give $N this, and I extend upon $g him : her; our undying gratitude as a true hero of the Alliance.  Cheers, I say!' which looks like alliance reward text but both use this as reward text.

**Comment by dr-j** [comment]
appears reward text for horde version should be '<name>, your successful re-engineering of the cauldrons is a tremendous victory for us!


<The high executor clears his throat and begins to bellow loudly.>


Let all within my presence hear: for service to the Forsaken and to the Horde as a whole above and beyond what was expected - in the face of overwhelming odds and incredible danger, might I add - I give <name> this, and I extend upon <his/her> our undying gratitude as a true hero of the Horde. Huzzah! ' -- from http://wowwiki.wikia.com/wiki/Quest:Mission_Accomplished!_(Horde)

**Comment by SnapperRy** [comment]
Right, one of the two texts in the DB is clearly wrong. Yet I'm much more inclined to think that Wowhead's texts are right and related to the right quest ids, as I have yet to encounter a quest with wrong texts there.

Look at [this](http://www.wowhead.com/quest=5237/mission-accomplished): it has the right horde text.

**Comment by dr-j** [comment]
Ye except we know from previous issues that wowhead data is not 100% reliable as there is or was wrong data on wowhead, like showig hostilality of npcs wrong, wether quest is available to horde, alliance or both

**Comment by SnapperRy** [comment]
Wowhead had many issues with things that required extensive research, like whether a quest is available to only a certain race or class.

Faction availability of quests has to be right only if the questgiver is neutral: many quests, even on TC, are set to faction:both but the questgiver belongs to one or the other faction, which effectively makes it faction-restricted.

The easiest thing to parse for quests is questgiver and quest texts, and I have yet to see Wowhead being wrong there (issues with parses such as <race> and <class> don't really count). So I'm more inclined to believe that the ids are, effectively, right, and that the current reputation values on DB are parsed from the mistake Wowhead did.
