### ISSUE TITLE
[3.3.5] Errors with some weekly quest in Wintergrasp 

### ISSUE THREAD

**Issue by Rhisk** [TrinityCore/TrinityCore#17375]
**Description**:
Some of the Wintergrasp weekly quests can not be completed during the event because when it starts all go into a raid group and not to a bg group.
**Current behaviour**: Tell us what happens
The quest Defend the Siege, Stop the Siege, Southern Sabotage, Toppling the Towers and Victory in Wintergrasp can not be completed during the event because all players go to a raid group and not to a .bg group.
**Expected behaviour**: Tell us what should happen instead
During the WIntergrasp event all players in it  must enter a bg group not in a raid group.

**Steps to reproduce the problem**:
1. Go to Wintergraps when the event is running.
2. Try to say any in /bg
3. The game show "You not are in a Battleground group".

**Branch(es)**: 
3.3.5 
**TC hash/commit**:
TrinityCore rev. 7427ca5f8e5b+ 2016-05-24
**TDB version**:
335.61
**Operating system**:
W7 64bit

I for a temporal solution changed the QuestInfoID to 62 so that they can be completed in a raid group. Sorry my bad english.

```sql 
UPDATE `quest_template` SET `QuestInfoID`=62 WHERE `ID` IN (13181, 13183, 13185, 13186, 13222, 13223, 13538, 13539);

**Comment by tkrokli** [comment]
Thank you for taking your time to fill in the issue template properly. More users should do it like this. :-)

**Comment by TecDian** [comment]
I tried the SQL, however no change, quests still cannot be completed. I guess quest completion is not triggered be the action required. (hash 813e33b92784)

Anyway, in wordserver.conf Wintergrasp is rated as battlefield rather than battleground. Is it really blizzlike to be in a battleground group when joining Wintergrasp?

**Comment by Rhisk** [comment]
The quest are PVP type, PVP only count in bg group,

**Comment by SnapperRy** [comment]
Wintergrasp acts just like any other world pvp zone, minus the queue system. Are you really sure you should be able to use the BG chat there? I recall everyone only talking in party or raid chat.

**Comment by Aokromes** [comment]
https://www.youtube.com/watch?v=9QIvXaPR61Y here it's show raid use.

**Comment by SnapperRy** [comment]
Original issue has been fixed.
