### ISSUE TITLE
6.X Darkmoon Faire - Event NPC/Object (More)

### ISSUE THREAD

**Issue by prestonjamesparsons** [TrinityCore/TrinityCore#17383]
Description:
 Darkmoon Faires Stuff - 
NPC Creature
Adding more objects in events

Current behaviour: Tell us what happens
 Its showing on stormwind and one in orgrimmar

Expected behaviour: Tell us what should happen instead
 NPC should be disappeared when Darkmoon Faire isn't active. 
gameobject should be disappeared when Darkmoon Faire isn't active. 

Branch(es): 6.x 

TC hash/commit:  5da2178 

TDB version: 6.04

Operating system:

 wins 10

NPCS
```
DELETE FROM `game_event_creature` WHERE `guid` IN (314040, 314484, 310945);
INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
(3, 314040),
(3, 314484),
(3, 310945), 
```

GOBJECT
```
DELETE FROM `game_event_gameobject` WHERE `guid` IN (220437, 220463, 220468, 220476, 220461, 220436, 220466);
INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`) VALUES
(3, 220437),
(3, 220463),
(3, 220468),
(3, 220476),
(3, 220461),
(3, 220436),
(3, 220466);
```

**Comment by Rhisk** [comment]
No sure in 6.x but Darkmoon Faire are 3 events. 

----------------------------------------------------------------------------
eventEntry                Description
3                               Darkmoon Faire (Terokkar Forest)
4                               Darkmoon Faire (Elwynn Forest)
5                               Darkmoon Faire (Mulgore)

If that's the case your SQL should be as follows:

```sql
-- NPC
DELETE FROM `game_event_creature` WHERE `guid` IN (314040, 314484, 310945);
INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
(3, 314040),
(3, 314484),
(3, 310945),
(4, 314040),
(4, 314484),
(4, 310945), 
(5, 314040),
(5, 314484),
(5, 310945);

-- GameObject
DELETE FROM `game_event_gameobject` WHERE `guid` IN (220437, 220463, 220468, 220476, 220461, 220436, 220466);
INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`) VALUES
(3, 220437),
(3, 220463),
(3, 220468),
(3, 220476),
(3, 220461),
(3, 220436),
(3, 220466),
(4, 220437),
(4, 220463),
(4, 220468),
(4, 220476),
(4, 220461),
(4, 220436),
(4, 220466),
(5, 220437),
(5, 220463),
(5, 220468),
(5, 220476),
(5, 220461),
(5, 220436),
(5, 220466);

**Comment by Aokromes** [comment]
Starting wow 4.3 darkmoon is a single event.

**Comment by prestonjamesparsons** [comment]
4 | Darkmoon Faire (Elwynn Forest)
 5 | Darkmoon Faire (Mulgore)

Not on game_event.. 

Just though it's only Horde and Alliance different events each ?
