### ISSUE TITLE
[6.x] Achievement: He Feeds On Your Tears

### ISSUE THREAD

**Issue by killradio** [TrinityCore/TrinityCore#17387]
**Description**: Achievement "He Feeds On Your Tears" is deprecated since cata and can't be obtained, but script still presents - "achievement_he_feeds_on_your_tears" (https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp#L1369).

**Current behaviour**: 

**Expected behaviour**: 

**Steps to reproduce the problem**:

**Branch(es)**: 6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/eb9be2bffca86145efa3487bab7ea723f2fe293d

**TDB version**:  6.04

**Operating system**:  w/e

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Krudor** [comment]
There isn't a way to generically disable achievements right now is there? I don't think this data is available in the dbc files. Might be a good time to add another column to achievement_dbc in the database, if this is the case.

**Comment by killradio** [comment]
@Krudor it's not about enable/disable achievements, but code should be clean ;) btw scriptname "achievement_he_feeds_on_your_tears" already remove from DB:
```sql
> SELECT * FROM achievement_criteria_data WHERE scriptname = 'achievement_he_feeds_on_your_tears';
Empty set (0.00 sec)
```
