### ISSUE TITLE
Starting zone quests not accepting for players

### ISSUE THREAD

**Issue by ceresia** [TrinityCore/TrinityCore#17396]
**Description**: 
Starting quests in starting zones (level 1-6) are not allowing characters to accept

**Current behavior**: Tell us what happens
Attempting accept the quest merely closes the quest window, but it never accepts, and you can open the gossip on the NPC again.

**Expected behavior**: Tell us what should happen instead
Quests should appear in quest log and allow completion.

**Steps to reproduce the problem**:
1. Create new character or use existing character and move to starting location
2. Attempt to accept a starting quest, it will not accept.
3. GM can give quest, character can finish, but continuing quest will also not accept
4. Other quests in other zones (non starting) are working accordingly
4a. issue arose on my 5-15-16 build, so I wiped everything out and compiled fresh and dropped my world DB and created a fresh one today, still the same issue.

**Branch(es)**: 
3.3.5

**TC hash/commit**:  
TrinityCore rev. 90ff3ce8c825 2016-06-16 17:53:14 +0200 (3.3.5 branch) (Win32, Release)

**TDB version**:  
335.61

**Operating system**:  
Host: Server 2008R2 
Client: Windows 10 & Windows 7 both tested.

**Comment by tkrokli** [comment]
Hi ceresia, could you elaborate on which starting zones you have tested (and which ones you have not tested, if any) so we know more precisely what to test for? All the starting zone quests are auto accept (at least in 3.3.5) and I have not noticed your issue lately (but I am going to re-test, all the same).

**Comment by ceresia** [comment]
I just tested Teldrassil, Deathnell, Azuremyst Isle, and Dun Morogh.  I have not tested the others.  I haven't made a "new" character or worked on low level quests until today, I can accept quests in Duskwood, Dalaran, and other higher level zones, just not low level zones/starting zones.

**Comment by Aokromes** [comment]
Fresh created dwarf:

[11:29:23] Quest accepted: Dwarven Outfitters

**Comment by jackpoz** [comment]
@ceresia please include a quest name and id in the issue description

**Comment by ceresia** [comment]
I just fresh created a dwarf and I cannot accept Dwarven Outfitters, it closes the window but the quest doesnt go to my log and the NPC still offers it.

**Comment by Aokromes** [comment]
Maybe you have some outdated/to new addon?

**Comment by ceresia** [comment]
On my test account I have all addons disabled.

**Comment by Aokromes** [comment]
Maybe you have a broken client downloaded from some private server known because they modify clients?

**Comment by ceresia** [comment]
I am downloading another client right now, but the client I have been using for many years is my own from disc+patch.  I will report back once I get the new client, but unsure why a client would break starting zone quest acceptance and not all quest acceptance?

**Comment by ceresia** [comment]
Fresh client from download, still the same issue :/

**Comment by ceresia** [comment]
I will report back in a few minutes, I just recompiled again and I was able to accept "Dwarven Outfitters"  I will test fully and see if I cannot find the source of the issue from my build last night to this morning.

**Comment by ceresia** [comment]
I found the issue, but unsure if I want to close this or not.  In my ignorant attempts to recompile last night I reused my worldserver.conf file, figured it would save me time instead of having to input new DB info and such.  After using a fresh one today and figuring out that the following setting was causing the quests to not work:


#    Quests.IgnoreAutoAccept
#        Description: Ignore auto accept flag. Clients will have to manually accept all quests.
#        Default:     0 - (Disabled, DB values determine if quest is marked auto accept or not.)
#                     1 - (Enabled, clients will not be told to automatically accept any quest.)

Quests.IgnoreAutoAccept = 0


If I set Quests.IgnoreAutoAccept = 1  then no starting quests will work at all.  This isn't a big deal as a while ago I wanted to set this as 1 to prevent the window not closing but the quest being accepted (As Aokromes stated "(it don't closes quest windows but it acepts)")

So instead of the bug being that the quests dont work it is that the "Quests.IgnoreAutoAccept = 1" breaks being able to accept starting quests.

**Comment by DDuarte** [comment]
My suggestion is to close this one and open a new issue. If that is happening it's definitely something that should be fixed.

**Comment by ceresia** [comment]
Gotcha, thanks DDuarte
