### ISSUE TITLE
[6.x] Split worldserver

### ISSUE THREAD

**Issue by Ardinis** [TrinityCore/TrinityCore#17391]
**Description**: We should split the worldserver into two parts:
- A server to provide characters 
- A game server

By doing this, in case of server crashes the player will be redirected on the characters list instead of login screen as the retail servers (with the message "The game server is stopped").
Also since the new bnet server protocol if the server crashed you will have a wowerror when the client try to open a socket.

**Branch(es)**: 6.x

**TC hash/commit**:  afa0bac669ac787e6bd35273c967a58b3e4e2196

**TDB version**:   6.04

**Operating system**:  Linux

**Comment by DDuarte** [comment]
If we are going to have this "issue" open... why stop at splitting character list from world when ideally we could have one worldserver node per map (or at least one node for social, another for instances, another for BGs and so on).

Some initially work has been done some time ago by @raczman and @Shauren at https://github.com/raczman/TrinityCore/tree/clowncopter but it was not completed.

I think this "issue" should be a discussion on the forums instead (there are already some topics about it).

**Comment by Ovahlord** [comment]
That would be the blizzlike way. Blizzard handles it the same way. Just saw that on the PTR right now that they have seperated the characterlist from the worldservers. The worldservers themself are not bound to zones such as the entire elwynn forest. Instead they are splitted into more single areas such as a node only for Acherus or Stormwind.

While I was trying the new legion stuff I had like a 9000 ping Inside and near Ironforge while my ping was fine in Acherus even while they have been tons of players.

**Comment by Nelidon** [comment]
Soemone work(ed) on it: https://www.youtube.com/watch?v=WxvaPZGqtV0
https://github.com/GiR-Zippo/Strawberry335

**Comment by Naios** [comment]
As I said already, it would be nice to have the datastorages in a seperate server (objectserver) which makes the data available through process shared memory. (Which is also required to make multiple server instances ram efficient).

**Comment by humaniti** [comment]
This is a really hard work to get done, only server i know to have something similar is Tauri-WoW (They have different server for DB, Logon, World, Instances) and they have also Xrealm (BG from different servers) but they are working with Mangos as i know (highly modified)

**Comment by prestonjamesparsons** [comment]
Don't blizzard have 3 Different server? Instance, BG, World? 

When you look into ServerMessage.DBC 

![image](https://cloud.githubusercontent.com/assets/12567543/16149452/cf4f514a-3488-11e6-869e-c19ca2262e39.png)

**Comment by Nelidon** [comment]
Probably but as @Ovahlord noticed, the world server works like nodes. One node per zone/city to avoid lag or a crash for all connected players. Each node manages the map (creatures, gameobjects, ...).

**Comment by Aokromes** [comment]
#13014
