### ISSUE TITLE
[3.3.5] [Gossip] Vendor gossip not working properly

### ISSUE THREAD

**Issue by Maadguy** [TrinityCore/TrinityCore#17394]
When using the gossip_menu_option in DB, option_id should allow to create vendors with options like 1- plate 2- mails or whatever.
But when you set option_id to 3 (for vendor), and npc_option_npcflag to 128 (matching vendor), the action_menu_id that should be used to lead to the npc_vendor category is not working. The gossip simply doesnt display in game.

Expected behaviour : Should be able to have a single NPC with multiple npc_vendor menus.

How to reproduce :

1. Create a vendor NPC with gossip
2. Try to use vending submenus

3.3.5
core revision 90ff3ce8c825
TDB 335.61
W7
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
The vendor NPCs are working as intended in TC 3.3.5 and will not be changed. Are there any pre-Cataclysm NPCs that you know about (please provide example(s)) who should offer more than 1 category of goods? I can't think of any, so to me it looks like they are working as it did back in WoTLK.
TBH, it looks like you are asking for a feature that is not supported in this source. Got more info?
