### ISSUE TITLE
[All] Non blizzlike commands

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17401]
**Description**:
I think, blizzlike commands are /*, not .*
**Current behaviour**: Tell us what happens
First command symbol is dot.
**Expected behaviour**: Tell us what should happen instead
At official server, dot commands does not working.
**Steps to reproduce the problem**:

1. Connect to official server
2. Open chat
3. Use .commands

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
Maybe, all.
**TC hash/commit**:  
ace9c1a
**TDB version**:  
Latest
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
Intended.

**Comment by stas730** [comment]
At 3.3.5, dot commands are used at official server?

**Comment by SnapperRy** [comment]
Try logging on retail and use ! commands. Make a screenshot for us all to see :P

**Comment by stas730** [comment]
P. S. I watched video with /gm * on official PTR server. It is fake?
