### ISSUE TITLE
Food does not heal

### ISSUE THREAD

**Issue by Kamui2040** [TrinityCore/TrinityCore#17405]
**Description**:
Consuming food or drinks does not heal
**Current behaviour**: Tell us what happens
If you try to eat or drink to heal yourself, it doesn't work. Your character sits down, the animation starts and there are sparkles but, no healing. Potions are ok though. I tested this in several areas and races.
**Expected behaviour**: Tell us what should happen instead
Food and Drinks should heal you.
**Steps to reproduce the problem**:

1. Get hurt
2. eat food
3. or drink water

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  
TrinityCore rev. 736843fbb544 2016-06-17 13:28:26 +0200 (3.3.5 branch) (Win64, Release)
**TDB version**:  
335.61
**Operating system**:  
Windows 7 Ultimate 64 bit

**Comment by Aokromes** [comment]
Cannot reproduce on  90ff3ce8c825

**Comment by Keader** [comment]
some specific food?
i cant repoduce too

**Comment by SnapperRy** [comment]
Food doesn't really heal, it boosts your natural health regen. So you won't see any gained health in the combat log.

**Comment by Kamui2040** [comment]
Sorry my mistake then, I understood it differently can be closed then.
Really sorry
