### ISSUE TITLE
[6.x][Quest] Thirst Unending

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17400]
**Description**:
The quest Thirst Unending is not behaving correctly. Only been tested as a Blood Elf Warlock.
http://www.wowhead.com/quest=8346/thirst-unending

**Current behaviour**: 
Using Arcane Torrent on a Mana Wyrm does not complete the quest.

**Expected behaviour**: 
Using Arcane Torrent on a Mana Wyrm completes the quest.

**Steps to reproduce the problem**:
1. Get near a Mana Wyrm
2. Use Arcane Torrent

**Branch(es)**: 
6.x

**TC hash/commit**:  
5da217877be7

**TDB version**:  
6.04

**Operating system**:  
Debian 8

**Comment by Aokromes** [comment]
Note to self test this on 6.x works on 4.3.4

**Comment by Aokromes** [comment]
on 6.x

[11:23:43] Quest accepted: Thirst Unending
[11:24:00] Thirst Unending completed.

**Comment by GnaXi** [comment]
I am no longer able to reproduce the issue either.

**Comment by BahDumbBugs** [comment]
Blood Elf Priest - It does not work on commit fcbbeb3.

**Comment by tkrokli** [comment]
@BahDumbBugs : if the bug persists, please open a new issue with additional details for the current branch.
