### ISSUE TITLE
[6.x][Spell] Wrath doesn't cost mana

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17409]
**Description**:
http://www.wowhead.com/spell=5176/wrath

**Current behaviour**: 
Spell doesn't cost any mana to cast

**Expected behaviour**: 
Spell should cost 3.5% of base mana

**Steps to reproduce the problem**:
1. Create a druid
2. Cast the spell Wrath

**Branch(es)**: 
6.x 

**TC hash/commit**:  
5fdeb0667532

**TDB version**:  
6.04

**Operating system**:  
Debian 8

![wrath](https://cloud.githubusercontent.com/assets/1616448/16162766/b0318790-34d5-11e6-80db-ea3aa80ae6eb.png)

**Comment by P-Kito** [comment]
Did you have any auras or fresh created char?

**Comment by GnaXi** [comment]
Freshly created character

**Comment by P-Kito** [comment]
Weird, because shouldnt this come from DBC?

**Comment by Anddrw** [comment]
Many DBC values are, somehow, not correct.

**Comment by Shauren** [comment]
Works for me - this is a tooltip bug, casting it takes mana properly.

**Comment by GnaXi** [comment]
Really? I can't get it to consume any mana. It stays at 100% no matter how much I spam it.

**Comment by Aokromes** [comment]
.gm off?

**Comment by GnaXi** [comment]
I'm on an account without privileges to even use the command.

**Comment by Shauren** [comment]
Do it in balance spec

**Comment by GnaXi** [comment]
I just couldn't believe that Wrath without balance spec was free to cast, so I had to test it on a real server.
To my surprise that is indeed how it works. Without balance spec, a weaker version of Wrath is free to cast.
So it is currently being emulated as intended! :)
