### ISSUE TITLE
[6.x][Spell] Prowl 

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17410]
**Description**:

**Current behaviour**: 
Prowl (http://www.wowhead.com/spell=5215/prowl) stays active, after jumping out of Cat Form

**Expected behaviour**: 
You're supposed to drop out of Prowl, when leaving Cat Form

**Steps to reproduce the problem**:
1. Play as a Druid
2. Enter Cat Form
3. Use and stay in Prowl
4. Exit Cat Form

**Branch(es)**: 
6.x

**TC hash/commit**:  
5fdeb0667532

**TDB version**:  
6.04

**Operating system**:  
Debian 8

![prowl](https://cloud.githubusercontent.com/assets/1616448/16163332/f0900c3c-34d8-11e6-9535-7ad423c9d1f7.png)

**Comment by Nefertumm** [comment]
Still happening? If still happening, here is a fix: (idk if this is a hack)

´´´sql
INSERT INTO `spell_linked_spell` (`spell_trigger`. `spell_effect`. `type`. `comment`) VALUES (-768, -5215, 0, 'Remove prowl when exit cat form');

**Comment by ariel-** [comment]
> idk if this is a hack

Anything using spell_linked_spell is a hack in 99.99% of use cases
