### ISSUE TITLE
Ahune Crash

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17415]
http://pastebin.com/x6v83rUW

Ahune 100% chance to crash server on Cast

https://github.com/TrinityCore/TrinityCore/commit/16765a186d4359b752c6f3dd9f0a1d2ff2674d84
3.3.5
Centos

**Comment by Aokromes** [comment]
Test with https://github.com/TrinityCore/TrinityCore/pull/17320

**Comment by SQLfix** [comment]
i used https://github.com/TrinityCore/TrinityCore/pull/17320
and crash with this change ...

crash from spell_ice_spear_target_picker in this Pr https://github.com/TrinityCore/TrinityCore/pull/17320 nothing change for this spell

void HandleDummy(SpellEffIndex /*effIndex*/)
        {
            GetCaster()->CastSpell(GetHitUnit(), SPELL_SUMMON_ICE_SPEAR_BUNNY, true);
        }

**Comment by Ovahlord** [comment]
try:

void HandleDummy(SpellEffIndex /effIndex/)
{
    (Unit* caster = GetCaster())
        if (Unit* target = GetHitUnit())
            caster->CastSpell(target, SPELL_SUMMON_ICE_SPEAR_BUNNY, true);
}

that lazy nullpointer fags

**Comment by SQLfix** [comment]
error C2065: 'caster' : undeclared identifier

**Comment by Ovahlord** [comment]
try again with the code above

**Comment by Keader** [comment]
Unnecessary {}
btw, will work, but we need found the cause first..

**Comment by Ovahlord** [comment]
the aoe spell probably hit something that has been partially removed from the world already and so the core gets a nullptr unit returned. Happens pretty often in many cases so aoe spells like that one can and will cause such troubles

**Comment by sirikfoll** [comment]
`if (Creature* caster = GetCaster()->ToCreature())` indeed could cause a crash, but at least for me the crashLog provided doesn't seem to be caused by this.

Also, I can't reproduce this crash, @SQLfix  any steps to reproduce?

**Comment by SQLfix** [comment]
i need recheck !

**Comment by Keader** [comment]
clean tc?

**Comment by SQLfix** [comment]
with clean ts i have crash .
i need recheck https://github.com/TrinityCore/TrinityCore/pull/17320 and  https://github.com/TrinityCore/TrinityCore/issues/17415#issuecomment-226949242

**Comment by Runico** [comment]
http://paste.ubuntu.com/17637881/

**Comment by jackpoz** [comment]
>pos = {m_positionX = -100.300468, m_positionY = -233.534225, m_positionZ = -100000, m_orientation = 1.79768896}

that's an interesting Z

**Comment by jackpoz** [comment]
![image](https://cloud.githubusercontent.com/assets/1153754/16242264/f4ffd25e-37f1-11e6-81ce-61ae3e166d62.png)

**Comment by sirikfoll** [comment]
The auras come from there, i don't see why this crash happens in this particular case, which i still can't reproduce.
```sql
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `auras`) VALUES
(25985, 0, 0, 0, 0, '75498 46878');
```

**Comment by jackpoz** [comment]
@sirikfoll reading the crashlog is enough to spot the invalid Z and manually set Z to -100000 in a debug session to trigger the assert
