### ISSUE TITLE
[6.x] Fel Cone smoke issue

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17412]
**Description**:
Fel Cone smoke issue

**Current behaviour**: 
When picking up a Fel Cone (http://www.wowhead.com/object=1673/fel-cone) the smoke stays in place.

**Expected behaviour**: 
Smoke is supposed to disappear when picking up a Fel Cone and reappear, when the Fel Cone respawns

**Steps to reproduce the problem**:
1. Pick up the quest: http://www.wowhead.com/quest=489/seek-redemption
2. Collect a Fel Cone

**Branch(es)**:
6.x

**TC hash/commit**: 
5fdeb0667532

**TDB version**: 
6.04

**Operating system**:
Debian 8

Before and after picking up a Fel Cone:
![felcone](https://cloud.githubusercontent.com/assets/1616448/16164043/d6ab10d8-34dc-11e6-8780-1b2d6beb727f.png)![felcone2](https://cloud.githubusercontent.com/assets/1616448/16164045/d93ccb2a-34dc-11e6-808e-7fe9995f7c42.png)

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d25a8d42a381345c7fb86760049be70006a65e9d was cherry picked, https://github.com/TrinityCore/TrinityCore/commit/a38c094a11dc61c8ee1153e0aee6de9a406d6a61 wasn't.

This issue should be tested with a38c094 applied(if it is possible). I'm pretty sure the GUID-list from the sql file should be changed. Sql-query for this is still here: https://github.com/TrinityCore/TrinityCore/pull/18172
