### ISSUE TITLE
[3.3.5] DB/Quest: fix chaining for quest "Clamlette Surprise" and related pre-quests

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17425]
**Description**: the quests "[To Gadgetzan You Go!](http://www.wowhead.com/quest=6611/to-gadgetzan-you-go)" (Horde) and "[I Know A Guy...](http://www.wowhead.com/quest=6612/i-know-a-guy)" (Alliance) should lead to quest "[Clamlette Surprise](http://www.wowhead.com/quest=6610/clamlette-surprise)". The issue here is that those two quests are currently leading to [the deprecated version of this quest](http://www.wowhead.com/quest=13825/clamlette-surprise). Due to being deprecated, it cannot be accepted, leading to a stuck, non-responsive quest window.

**Branch(es)**: 3.3.5

**TC hash/commit**:   291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `RewardNextQuest`=6610 WHERE `ID` IN (6611, 6612);
```

**Comment by tkrokli** [comment]
Took me a while and some reading before I got how it is connected to patch 3.1.0, it is explained here:
[This is the version of Clamlette Surprise that you are given if you had already completed the quest before Patch 3.1.0.](http://wow.gamepedia.com/Quest:Clamlette_Surprise_(legacy))
- http://wow.gamepedia.com/Quest:Clamlette_Surprise_(legacy)
 - http://www.wowhead.com/quest=13825/clamlette-surprise

For those who did not complete the quest before patch 3.1.0, the standard quest still applies:
[For the normal version of this quest, see N [45] Clamlette Surprise.](http://wow.gamepedia.com/Quest:Clamlette_Surprise)
- http://wow.gamepedia.com/Quest:Clamlette_Surprise
 - http://www.wowhead.com/quest=6610/clamlette-surprise

**Comment by SnapperRy** [comment]
Right, the recipe from this quest was introduced in 3.1.0, and this quest was meant for people that already did the quest back then. But since we're in 3.3.5a, and 3.1.0 technically "never happened", it is deprecated :P
