### ISSUE TITLE
[6.x] Disconnected from server when changing realm and locked on this realm

### ISSUE THREAD

**Issue by et65** [TrinityCore/TrinityCore#17422]
**Description**: Disconnected from server when changing realm and locked on this realm.

**Current behaviour**: I have 4 realms. When I'm on char list of one realm and I click on "Change realm" to change realm a message "You are disconnected from server" (I think this is the English message), WOW51900306 appears. If I click on "ok" nothing happens. This problem doesn't occurs each time. If I try like 5-10 times to click, after a while the realmlist appears, but for some accounts, the realmlist will never appears regardless the number of tries.

Bnetserver logs: none concerning the problem.
Bnetclient logs:
```
6/19 12:43:57.929  [IBN_Login] Requesting change realm list
6/19 12:43:57.929  [GlueLogin] Waiting for realm list.
6/19 12:43:57.981  [IBN_Login] Received realm list ticket | code= (306)
6/19 12:43:57.981  [GlueLogin] Fatal error while logging in | result=( | code= (306) | localizedMessage= | debugMessage=Error getting RealmList ticket)
```

**Expected behaviour**: It should always propose the realmlist...

**Steps to reproduce the problem**:

1. Install more than one realm.
2. Login on a realm.
3. Click on "Change realm".

**Branch(es)**: 6.x

**TC hash/commit**:  f6637439f484dacc9c8deb3c4dd07832146ff6f6

**TDB version**:  6.04

**Operating system**:  Debian 8

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by et65** [comment]
@Aokromes : I'm not sure it's very low priority, because if somebody login on a realm, it can be locked on it for everytime...

**Comment by et65** [comment]
Seems that ResourcesService.GetContentHandle is missing:
```
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1718765138 })
```
just after this, client call ConnectionService.DisconnectRequest. It's for that player can't load realmlist anymore.

@Shauren : any idea?

**Comment by et65** [comment]
Nelidon's fix works perfectly.

@Nelidon: Thanks you :). Be careful, you have made a pull request on your own repo...

**Comment by tkrokli** [comment]
@et65 : I would say that Nelidon's way of doing it is a valid way as long as he does not want to create a PR for it to TrinityCore yet. But I see your point, if he intended to make it a TC PR. :-)

**Comment by et65** [comment]
@tkrokli : Maybe but make a pull request on a repository that you have full access has no interest... ^^

**Comment by tkrokli** [comment]
Yes, of course. He could have made a separate branch to enable him to create a PR to TC later. :-)

**Comment by Nelidon** [comment]
I made the pull request on the right repository now.
