### ISSUE TITLE
NPC quest markers turn grey at wrong character level

### ISSUE THREAD

**Issue by Kensaki** [TrinityCore/TrinityCore#17421]
**Description**:
If you pick up a level 15 quest (obtainable at level 12) they turn grey at level 20.
Quests.HighLevelHideDiff is set to 7.

**Current behaviour**: Tell us what happens
The quest marker on NPC turns grey even though if you pick up the quest, it is still green for you.
This means quests won't show up unless you track low level quests.

**Expected behaviour**: Tell us what should happen instead
The NPC quest marker should turn grey at the same level as the quest is actually grey. Level 15 quest would be at level 22 I believe. 
Tested with several quests in redridge mountains and with crossroads quests in barrens.

**Steps to reproduce the problem**:
1. make a level 20 character.
2. go to lakeshire
3. track low level quests and accept those. Notice they are green in your quest log.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
Probably both branches

**TC hash/commit**:  
62883a9d7959

**TDB version**:  
TDB_full_world_335.61_2016_04_11

**Operating system**:  
win 8.1

**Comment by MrSmite** [comment]
Even though current wowhead is for 6.x, I know the quest [Elmore's Task](http://www.wowhead.com/quest=1097/elmores-task) is the same in 3.3.5. If Blizz hasn't changed the difficulty/color relationship between expansions then yes, a lvl 15 quest would be grey at lvl 22:

> Level: 15
> Requires level 9
> Difficulty: 9 (red) 11 (orange) 13 (yellow) 18 (green) 22 (grey)

**Comment by MrSmite** [comment]
General rule was for every 7 player levels the quest drops one difficulty level, stopping at grey. However, since most data sites such as wowhead are for 6.x, it's hard to say. The data on wowhead doesn't seem to support a strict rule.

For example, this quest is identical in 335 and 6.x and follows the *7 level* rule:

> Quest: [Elmore's Task](http://www.wowhead.com/quest=1097/elmores-task)
> Level: 15
> Requires level 9
> Difficulty: 9 (red) 11 (orange) 13 (yellow) 18 (green) 22 (grey)

However this quest is also the same in both clients but uses a *5 level* rule:

> Quest: [The Weathered Grave](http://www.wowhead.com/quest=26793/the-weathered-grave)
> Level: 25
> Requires level 23
> Difficulty: 23 (yellow) 28 (green) 33 (grey)

**Comment by Kensaki** [comment]
Elmore's Task won't show up as a quest marker above NPC if you are level 20 though. Should be 22 as you stated?

**Comment by MrSmite** [comment]
> Elmore's Task won't show up as a quest marker above NPC if you are level 20 though. Should be 22 as you stated?

Yes, I agree with your initial assessment that 7 levels would be grey (eg: 15 quest / 22 player), at least that's what I remember from WotLK retail.

I was just trying to come up with some data to back it up when I noticed that the color schemes on wowhead are not consistent which is what I posted above.

**Comment by Killyana** [comment]
HighLevelHideDiff was changed from 7 on BC  to 10 on wotlk.
You can see here https://www.wowhead.com/quest=3741/hilarys-necklace
Requires level 12 and it turns grey at level 22
Also: https://us.battle.net/support/en/article/41951
So just the HighLevelHideDiff must be updated to 10

**Comment by Killyana** [comment]
The change must be on Quests.LowLevelHideDiff
The current value is 4  and it's not related to fact that the quest turns grey, the level difference between the quest level and the "grey level" could be  4 to 15
