### ISSUE TITLE
[3.3.5] DB/Loot: fix drop chance for various quest-related items

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17428]
**Description**: the following items should have a 100% drop rate:
- [Unpopped Darkmist Eye](http://www.wowhead.com/item=5884/unpopped-darkmist-eye) (sources [1](http://www.wowhead.com/item=5884/unpopped-darkmist-eye#comments:id=289247)/[2](http://www.wowhead.com/quest=1206/jarl-needs-eyes#comments:id=157963)/[3](http://www.wowhead.com/quest=1206/jarl-needs-eyes#comments:id=12842)).
- [Blood Amber](http://www.wowhead.com/item=11503/blood-amber) ([source](http://www.wowhead.com/item=11503/blood-amber#comments:id=105109)).
- [Burning Legion Missive](http://www.wowhead.com/item=29590/burning-legion-missive) (source: cannot find a comment about it, but since this item is required to continue the chain of quests, and since the Alliance version has a 100% drop rate, I believe this is correct).
- [Bleeding Hollow Torch](http://www.wowhead.com/item=31347/bleeding-hollow-torch): listed drop rate (20%) is way too low considering that the mobs that drop this item are involved in a very grind-intensive quest. Sources [1](http://www.wowhead.com/item=31347/bleeding-hollow-torch#comments:id=75735)/[2](http://www.wowhead.com/quest=10792/zethgor-must-burn#comments:id=290030).

**Branch(es)**: 3.3.5 (6.x for the Hellfire Peninsula-related drops)

**TC hash/commit**:   291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Item` IN (5884, 11503, 29590);
UPDATE `creature_loot_template` SET `Chance`=80 WHERE `Item`=31347;
```

**Comment by Exodius** [comment]
@SnapperRy, please read https://github.com/TrinityCore/TrinityCore/issues/16064#issuecomment-226246392 and use it into consideration when creating queries related to quest item drops.

```sql
-- Bleeding Hollow Torch http://eu.battle.net/wow/en/item/31347
-- Drop Chance: Guaranteed
UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Item`=31347;

**Comment by SnapperRy** [comment]
@Exodius: seems right, thanks. Will keep that in mind.

**Comment by Aokromes** [comment]
Don't trust wow 6 data for wow 3, blizzard eased a lot of quests from 3.3.5a.
