### ISSUE TITLE
[Vulnerability] [From Pandaria] Third faction using cheat

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17431]
**Description**:
If player using teleport cheat to escape Wandering Isle, we can see THIRD faction. It is friendly for all, but we cannot invite it in group.
**Current behaviour**: Tell us what happens
No faction checks for pandarens.
**Expected behaviour**: Tell us what should happen instead
We need to add faction checks and teleport character to location on Wandering Isle, which used to prevent swimming in the sea.
**Steps to reproduce the problem**:

1. Create pandaren
2. Enable GM mode
3. Teleport from Wandering Isle to GM Island
4. Disable GM mode

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
From Pandaria
**TC hash/commit**:  
688635f
**TDB version**:  
Latest
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
Gms are intended to ignore all restrictions. And players can't teleport to another map.
