### ISSUE TITLE
[3.3.5] DB/Midsummer: fix availability for the "Striking Back" daily quests

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17436]
**Description**: the "[Striking Back](http://wotlk.openwow.com/?search=striking+back)" daily quests should only become available after completing the quest "[Inform the Elder](http://www.wowhead.com/quest=12012/inform-the-elder)" ([source](http://www.wowhead.com/quest=12012/inform-the-elder#comments:id=310299)).

Only one of those daily quests should be available at a given time. based on the character's level. When the character levels up and is eligible for another version of the daily, the previous versions become unobtainable. Same source as above.

**Branch(es)**: 3.3.5

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `MaxLevel`=28 WHERE `ID`=11917;
UPDATE `quest_template_addon` SET `MaxLevel`=38 WHERE `ID`=11947;
UPDATE `quest_template_addon` SET `MaxLevel`=48 WHERE `ID`=11948;
UPDATE `quest_template_addon` SET `MaxLevel`=55 WHERE `ID`=11952;
UPDATE `quest_template_addon` SET `MaxLevel`=63 WHERE `ID`=11953;
UPDATE `quest_template_addon` SET `PrevQuestId`=12012 WHERE `ID` IN (11917, 11947, 11948, 11952, 11953);
--
```

**Comment by Killyana** [comment]
I'm working to fix all spawns and quests for this event, I will push it soon.

**Comment by Kittnz** [comment]
Ha me too @Killyana , what did you sniff already?
