### ISSUE TITLE
[3.3.5] [Achievement] Torch Juggler - Midsummer Fire Festival

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#17446]
Achievement [Torch Juggler] doesn't seems to work, when you use the Item http://www.wowhead.com/item=34599 nothing happens, no animation.

This is how it should work:

https://www.youtube.com/watch?v=iK-R09RM6Fo

3.3.5a
bdec8297d0349baa03cda3ff193c486c9a046000
TDB 61

**Comment by SQLfix** [comment]
Confirm

**Comment by BahDumbBugs** [comment]
Commit 85a2e still shows issue still persists.

**Comment by uruloke** [comment]
Also happening for me.

**Comment by TQPS** [comment]
Midsummer time 2020

Still no torch spawn

**Comment by illfated** [comment]
From issue ticket #22093 :
- https://www.wowhead.com/quest=11657/torch-catching (Alliance)
- https://www.wowhead.com/quest=11923/torch-catching (Horde)
