### ISSUE TITLE
[Crash] Player::UpdateLocalChannels

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#17448]
**TC hash/commit**:  bdec8297d0349baa03cda3ff193c486c9a046000

**TDB version**:  61

**Operating system**:  Debian

http://paste.ubuntu.com/17783807/

**Comment by Runico** [comment]
Another related crash: http://paste.ubuntu.com/17784999/

**Comment by Carbenium** [comment]
This doesn't look like clean TC. The lines in the crashlogs do not match the source code.

**Comment by jackpoz** [comment]
it seems you have bad data in m_channels, do you have any custom change that messes with it ?

**Comment by Runico** [comment]
@jackpoz not at all

**Comment by Aokromes** [comment]
channels revamp changed this a lot, if this bug is still valid open a new ticket.
