### ISSUE TITLE
[3.3.5][6.x] DB/Quest: improvements for quest "The Warp Rifts"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17440]
**Description**: the [NPC](http://www.wowhead.com/npc=20143/void-spawner-quest-warp-rifts) spawned with the [item](http://www.wowhead.com/item=29027/unstable-warp-rift-generator) given by this quest should be untargetable and have a fixed modelid (the one in creature_template.modelid2 field). [Source](https://www.youtube.com/watch?v=UQZ1qNSzPpg).

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  291a264

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `creature_template` SET `unit_flags`=33554944 WHERE `entry`=20143;
DELETE FROM `smart_scripts` WHERE `entryorguid`=20143;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(20143,0,0,0,25,0,100,0,0,0,0,0,3,0,18684,0,0,0,0,1,0,0,0,0,0,0,0,"Void Spawner - Quest - Warp Rifts - On Reset - Change modelID"),
(20143,0,1,0,1,0,100,0,2000,5000,15000,23000,11,34943,0,0,0,0,0,1,0,0,0,0,0,0,0,"Void Spawner - Quest - Warp Rifts - Out of Combat - Cast 'Summon Unstable Voidwalker' (No Repeat)");
--
```

(the "spawn voidwalkers" event already exists in db, but if I only changed the id then the query wouldn't be reimportable. This makes more sense to me)

**Comment by tkrokli** [comment]
About your source, https://www.youtube.com/watch?v=UQZ1qNSzPpg:
 **This video is unavailable.**

Sorry about that.

**Comment by SnapperRy** [comment]
@tkrokli: it works for me. Can you try again?

**Comment by dr-j** [comment]
Sniff data says that entry 20143 has unit flags 33554944 (Immune to NPC + Untargetable there is no immune to pc flags present

Display id 18684 is correct

**Comment by tkrokli** [comment]
@SnapperRy : Yes, thank you, it works now. I don't know why it was unavailable before.

**Comment by SnapperRy** [comment]
@dr-j: thanks for the sniffed flag, changed!

There is no need for immune to pc flag, apparently you can't damage what you can't target.
