### ISSUE TITLE
[6.x] Removing Gilneas Evacuation Facing Marker

### ISSUE THREAD

**Issue by Anddrw** [TrinityCore/TrinityCore#17457]
**Description**:
These imps are spawned in Gilneas. They shouldn't.
http://www.wowhead.com/npc=35830/gilneas-evacuation-facing-marker-first

**Current behaviour**: Tell us what happens
Too many imps.

**Expected behaviour**: Tell us what should happen instead
Shouldn't be there

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 6.x 

**TC hash/commit**:  55d5cd3

**TDB version**:  6.04

**Operating system**:  *Nix

Fix: 
```sql
DELETE FROM `creature` WHERE `map`=654 AND `id`=35830;
```

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
You have sniffs confirming you are right?

**Comment by Anddrw** [comment]
No, but those imps are not on retail.

**Comment by Aokromes** [comment]
They are, simply players can't see them.

**Comment by Anddrw** [comment]
This was reported from a non-gm account.

**Comment by Aokromes** [comment]
Well, i made those npcs invisible few days ago.
