### ISSUE TITLE
[3.3.5] Death Knight quests not showing up on Minimap

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17451]
**Description**:
Death Knight quests not showing up on Minimap

**Current behaviour**:
All quests in Death Knight start area is not showing up on the Minimap, but is shown correctly on the World map

**Expected behaviour**:
Quests should be shown on the Minimap

**Steps to reproduce the problem**:
1. Create a Death Knight
2. Start a quest

**Branch(es)**:
3.3.5

**TC hash/commit**:
rev. 87ebc31780b1 2016-06-22 16:31:32 +0200 (3.3.5 branch) (Unix, Release)

**TDB version**:
335.61

**Operating system**:
Debian 8

![dkquests](https://cloud.githubusercontent.com/assets/1616448/16346838/b9a4fc8e-3a49-11e6-85b3-b517feec5c39.png)

**Comment by Aokromes** [comment]
IIrc that's 4.x and higher feature.

**Comment by GnaXi** [comment]
lol, my bad. I've been playing around with 6.x for too long! :)
