### ISSUE TITLE
[6.x] Training targets grant experience

### ISSUE THREAD

**Issue by Anddrw** [TrinityCore/TrinityCore#17450]
**Description**: Training targets grant experience

**Current behaviour**: Training targets grant experience

**Expected behaviour**: Shouldn't grant experience at all.

**Steps to reproduce the problem**:

1. new Pandaren Character.
2. Kill Training Targets
3. -

**Branch(es)**: 6.x

**TC hash/commit**:  420b904

**TDB version**:  6.04

**Operating system**: *NIX 

Fix for this (hack):
```sql
UPDATE `creature_template` SET `flags_extra`=64 WHERE `entry` IN(53714, 57873, 58168, 60162, 60931, 65069);
```
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by PiskelDEV** [comment]
maybe unit flags problem ?

**Comment by SnapperRy** [comment]
Doesn't look like a hack, that flag exists precisely for the purpose of disabling exp gains. Your fix is valid :)

**Comment by Anddrw** [comment]
This issue is also related to Training Dummies. Ill edit the issue with the correct fix for dummies too.
