### ISSUE TITLE
Thorium encounter Ulduar

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#17465]
**Description**:
Thorim encounter in Ulduar does not work.  Supposed to be able to get to him via  a gate but gate doesn't open.
 http://wowwiki.wikia.com/wiki/Thorim_(tactics)

**Current behaviour**: Tell us what happens
I put this information in the description

**Expected behaviour**: Tell us what should happen instead
http://wowwiki.wikia.com/wiki/Thorim_(tactics)

**Steps to reproduce the problem**:

1.Enter the area where Thorium is 
2. Kill the mobs
3. Try to enter the gate using the lever next to it.
4. Nothing happens

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
77ca631a8c07e910a51888b7903148f88517791e

**Operating system**:  
Mac OS X

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
duplitate.
