### ISSUE TITLE
[3.3.5] [Blizzlike]: No Man's Land for Hyjal

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17467]
**Description**:
We need to disable Hyjal using No Man's Land spell and add missing NPC and object.
**Current behaviour**: Tell us what happens
Cheaters (without special programs) can go to Hyjal.
**Expected behaviour**: Tell us what should happen instead
Hyjal must to be closed.
**Steps to reproduce the problem**:

1. Teleport to Winterspring
2. Go to Hyjal without flying
3. See this not implemented function

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
From TBC to WotLK — 3.3.5
**TC hash/commit**:  
aa59ec4
**TDB version**:  
Latest.
**Operating system**:  
All

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
NPC, object and debuff:
https://youtube.com/watch?v=Uq9jKcbs1Qo

**Comment by stas730** [comment]
P. S. We have this debuff in 4.0.3a.

**Comment by dr-j** [comment]
http://wotlk.openwow.com/spell=42202

**Comment by Kittnz** [comment]
I don't think we have sniffs for hyjal on 335

**Comment by dr-j** [comment]
No we dont but by looking at that video and the fact that even though is in  hyjal does not get buff or get teleported until you enter zone or it says Hyjal on screen.

And if thats the case this can be fixed quiet easy however we still need target position for teleport
by just adding the the above spell to spell area for hyjal and adding a spell_target_position entry for http://wotlk.openwow.com/spell=42200

**Comment by Kittnz** [comment]
And we can't get that because there are no sniffs, but i remember being ported to Wintersprings, to that graveyard.

**Comment by dr-j** [comment]
Not sniffed teleport location is approx as per that video or you can see on mini map that destination is on path between snow and dirt so destination is appro

~~~sql
DELETE FROM `spell_target_position` WHERE `ID`=42200;
INSERT INTO `spell_target_position` (`ID`, `EffectIndex`, `MapID`, `PositionX`, `PositionY`, `PositionZ`, `Orientation`, `VerifiedBuild`) VALUES 
(42200, 0, 1, 5010.165039, -4554.938965, 852.146362, 0.883979, 0);

DELETE FROM `spell_area` WHERE `spell`=42202;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES 
(42202, 616, 0, 0, 0, 0, 2, 1, 64, 11);

**Comment by Kittnz** [comment]
Good enough
