### ISSUE TITLE
Death Knight Pet has no energy

### ISSUE THREAD

**Issue by Nogood4U** [TrinityCore/TrinityCore#17476]
**Description**:
Death Knigth Pet is summoned but has no energy
**Current behaviour**: Tell us what happens
I am able to summon the risen ghoul but this has no energy so it cannot cast any spells , maybe due to this
**Expected behaviour**: Tell us what should happen instead
Pet should have a energy bar
**Steps to reproduce the problem**:
1. Use Raise Dead
2. pet has no energy bar
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:  
68473cc 
**TDB version**:  
TDB_full_6.04_2016_04_11.7z
**Operating system**:  
windows 10

**Comment by Aokromes** [comment]
#13510 ?

**Comment by Nogood4U** [comment]
Not exactly , doing .cast  xxxxx does nothing , but i can use ghoul skills  that do not require energy.

Pet bar is correct , tho i had to set PetAI in creature template for it to appear(this is part of the first pull request i am preparing for trinity which is a full dk class fix).

You can look at the pet frame next to the chat for reference on the pet energy bar
[in this image i found in google (not mine )](http://i.imgur.com/cKu7KNG.jpg) , this is what is missing

i tried to hack fix it adding the line `SetPowerType(POWER_ENERGY)` in many places in Pet.cpp and Creature.cpp , with no succes, so there must be something i am not aware of (new to trinity core)
