### ISSUE TITLE
[bug] ICC Boss Deathbringer Surfang

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#17470]
**Description**:

When a horde raid 10/25, kill DeathBringer Surfang when he dies far from where he stay to speak, the animation of the father picking the body does not work and therefore the door is not opened.

**Current behaviour**: the animation of the father picking the body does not work and therefore the door is not opened.

**Expected behaviour**: the father picks up his body and leave the place, then the door of inner icc is open.

**Steps to reproduce the problem**:

1. raid with horde players
2. kill deathbringer away from the stairs

**Branch(es)**: 3.3.5 

**TC hash/commit**:  aa59ec4 

**TDB version**:  TDB 335.61

**Operating system**:  windows/ linux

PD: i'm reporting now but this problem is old, detect it at least 6 months with my friends. Sorry for my rusty english

**Comment by Keader** [comment]
#15018

**Comment by IngMak** [comment]
i.m sorry again
