### ISSUE TITLE
[bug] ICC Lady Deathwhisper (icc 2nd boss) (Devourer of Souls spell  Phantom Blast)

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#17474]
**Description**:
I have been told that no boss of instances can be interrupted, so I dared to put this bug
 the areal frostbolt can be interrupted

**Current behaviour**:  the areal frostbolt can be interrupted

**Expected behaviour**: the areal frostbolt can not be interrupted

**Steps to reproduce the problem**:

1. on raid 10/25, when lady deathwhisper lost his mana and change phase
2. lady cast some areal frostbolt who can be interrupt with warrior, dk (and other) silencing abilities

**Branch(es)**: 3.3.5 

**TC hash/commit**:  aa59ec4 

**TDB version**:  TDB 335.61

**Operating system**:  windows/ linux

PD: i'm reporting now but this problem is old, detect it at least 6 months with my friends. Sorry for my rusty english.

This happens with festergut; forge of soul boss Devourer of Souls spell Phantom_Blast
when festergut is interrupted it stay with 3 charges of his buff

**Comment by Keader** [comment]
try: https://github.com/TrinityCore/TrinityCore/pull/17389

**Comment by IngMak** [comment]
thanks for the help apologize for the inconvenience, I assumed that in these cases immunity was enough to put them, what surprised me that no one do it

**Comment by sirikfoll** [comment]
Lady Deathwhisper frostbolts should be interruptable, not a bug, [souce1](http://www.wowhead.com/npc=36855/lady-deathwhisper#comments:id=910542) [source2](http://www.mmo-champion.com/threads/755341-Lady-Deathwhisper-interrupts)

**Comment by IngMak** [comment]
I have problems accessing these pages, .. proxy.. apologize for the inconvenience

**Comment by GitVerge** [comment]
@IngMak What do you mean by "areal frostbolt"? Could you tell us the spell id? Because the frostbolt spell that hits all the party doesn't have cast time, and the other one can be interrupted as sirikfoll said.

**Comment by Keader** [comment]
@GitVerge This spell: https://github.com/sirikfoll/TrinityCore/blob/5652044704626c783f9169b06e2eed171a5eafdf/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp#L61

Btw, this issue is dupe/invalid :dancer:
