### ISSUE TITLE
[bug][spell] hunter master call

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#17473]
**Description**:

hunters can cast Master Call while the pet is dead. activating the  bonus and the death body move near the hunter

**Current behaviour**: hunters can cast Master Call while the pet is dead. activating the  bonus and the death body move near the hunter

**Expected behaviour**: hunters can not use Master Call when the pet is death.

**Steps to reproduce the problem**:

1.  kill the pet with the help of player or npc.
2. cast master call

**Branch(es)**: 3.3.5  

**TC hash/commit**:  aa59ec4

**TDB version**:   TDB 335.61

**Operating system**:  windows/ linux

PD: i'm reporting now but this problem is old, detect it at least 6 months with my friends. Sorry for my rusty english

**Comment by Keader** [comment]
Please before do creature a ticket, search if has another open...
Dup: #8403

**Comment by IngMak** [comment]
i'm sorry please delete this
