### ISSUE TITLE
[bug] ICC battle mage

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#17471]
**Description**:

event battle gunship, sometimes the battle mage stop casting the spell who freezes the cannons.
it happen when a hunter markmanship  interrupt their casting spell.

**Current behaviour **: battle mages cannot freezes the cannons

**Expected behaviour**: battle mages freezes the cannons

**Steps to reproduce the problem**:

1. event battle gunship
2. hunter markmanship (maybe other classes too) interrupt his casting spell

**Branch(es)**: 3.3.5 

**TC hash/commit**:  aa59ec4 

**TDB version**:  TDB 335.61

**Operating system**:  windows/ linux

PD: i think it can be fix changing it mechanic_immune_mask on database
 i'm reporting now but this problem is old, detect it at least 6 months with my friends. Sorry for my rusty english

**Comment by Keader** [comment]
Dup #14912

**Comment by IngMak** [comment]
i.m sorry :(
