### ISSUE TITLE
[335] INT(10) UNSIGNED Means in-game mail will fail in approx. 90 years

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#17477]
**Description**:

INT(10) UNSIGNED is not big enough to handle UNIX timestamps into infinity

**Current behaviour**:

`mail`.`expire_time` and `mail`.`deliver_time` will overflow at: *2106-02-07 at 06h 28m 16s (24h time)* which is approx. 90 years from the time of this post.

**Expected behaviour**:

The database should be robust enough to allow continued operation

**Steps to reproduce the problem**:

Max value of an INT(10) UNSIGNED is 4294967295 which is  *2106-02-07 at 06h 28m 15s (24h time)*

1. Attempt to insert 4294967296 into `mail`.`expire_time` and `mail`.`deliver_time`
2. You will get an error: *WARNING CODE: 1264, Out of range value*

NOTE: 4294967296 is *2106-02-07 at 06h 28m 16s (24h time)*

**Branch(es)**: 3.3.5 (perhaps 6.x, didn't check)

**TC hash/commit**:  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version**:  TDB_full_world_335.61_2016_04_11.sql

**Operating system**:  N/A

NOTE: UNIX timestamps calculated using

http://www.csgnetwork.com/time2unixdscalc.html
http://www.csgnetwork.com/unixds2timecalc.html

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by sirikfoll** [comment]
probably almost the same thing(int limit), this happened in my server with the arena team charters '-'

**Comment by DDuarte** [comment]
Will the game even work (without patching) in 2038?

**Comment by MrSmite** [comment]
> Will the game even work (without patching) in 2038?

I was wondering the same thing. Also, can the client handle a mail delivery time greater than 32-bit?

**Comment by Shauren** [comment]
... really?

**Comment by Keader** [comment]
yeah, int limit fucked  arena team charters on server that i play

**Comment by carlos93** [comment]
In 2106 we will be fucked because of this issue.
And probably dead.

**Comment by tkrokli** [comment]
I won't be alive to see the issue manifest. Not sure if it will be fixed while I'm alive though.

**Comment by MrSmite** [comment]
> ... really?

> n 2106 we will be fucked because of this issue.
> And probably dead.

> I won't be alive to see the issue manifest. Not sure if it will be fixed while I'm alive though.

Hey, think of your great grandkids... they may want to play "legacy" games just like the thriving Commodore 64 emulator communities ;)

**Comment by Aokromes** [comment]
I really doubt you can run 32 binaries (wow.exe) or have ipv4 support on 2106.

**Comment by MrSmite** [comment]
> I really doubt you can run 32 binaries (wow.exe) or have ipv4 support on 2106.

Sure you could. You could box up a machine today with Win 7, the WoW client and Trinity and have someone open it in a hundred years. As long as they play on localhost or connect it to another similar machine on a private LAN it will work fine ;)
