### ISSUE TITLE
[bug] ICC Lich King's Valquiries

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#17472]
**Description**:

When a horde raid 10/25, when Valkyrie take a player to throw him off the cliff, and the raid do a damage burst to the Valkyrie, she drop the player in the place and disappears.

**Current behaviour**: Tell us what happens
Valkyrie take a player to throw him off the cliff, and the raid do a damage burst to the Valkyrie, she drop the player in the place and disappears.

**Expected behaviour**: Tell us what should happen instead
Valkyrie drop the player only if she is dead.

**Steps to reproduce the problem**:

1. just go to phase when Valkyrie with a raid 10/25
2. do some damage burst to she, Valkyrie not die, but drops the player is carrying and disappears

**Branch(es)**: 3.3.5 

**TC hash/commit**:  aa59ec4 

**TDB version**:  TDB 335.61

**Operating system**:  windows/ linux

PD: i'm reporting now but this problem is old, detect it at least 1 month ago with my friends. Sorry for my rusty english

**Comment by GitVerge** [comment]
Val'kyrs have different behaviour in normal and heroic mode.
