### ISSUE TITLE
[All]: Why we cannot implement Battle.net functions/

### ISSUE THREAD

**Issue by stas730** [TrinityCore/TrinityCore#17483]
**Description**:
Why we cannot implement Battle.net functions? We are lazy?
**Current behaviour**: Tell us what happens
Battle.net functions not implemented and we not going to implement it.
**Expected behaviour**: Tell us what should happen instead
We need to implement/try to implement Battle.net functions and not say "We cannot do it".
**Steps to reproduce the problem**:

1. Try to use RealID
2. Try to use BattleTag
3. Try to use…

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
All
**TC hash/commit**:  
1b1478b
**TDB version**:  
Latest
**Operating system**:  
Latest

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by stas730** [comment]
Question: Why we cannot implement it?

**Comment by DDuarte** [comment]
We cannot do it

**Comment by stas730** [comment]
WHY?

**Comment by stas730** [comment]
Facepalm.

**Comment by DDuarte** [comment]
The 3.3.5 Battle.net module is heavily encrypted. It is out of the scope of TC to work with that.

**Comment by stas730** [comment]
[Invalid-Intended-WontFix-Blizzlike]. IT IS NOT BLIZZLIKE!

**Comment by DDuarte** [comment]
WontFix.
