### ISSUE TITLE
[6.x] DB\Quest: 14091 - Something's Amiss

### ISSUE THREAD

**Issue by vegax87** [TrinityCore/TrinityCore#17480]
**Description**: It's the first quest in Worgen starting area, but it's impossible to complete

**Current behaviour**: When I return to Prince Liam Greymane, I can't complete the quest

**Expected behaviour**: I shoud be able to complete the quest according to this video: https://www.youtube.com/watch?v=172y_pX1LZg

**Steps to reproduce the problem**:

1. Speak to Liam Greymane to start the quest
2. Speak with Liutenant Walden
3. Return to Liam Greymane

**Branch(es)**: 6.x

**TC hash/commit**:  7ed1c47f6b336cc7953373de60e964ba0a076b36

**TDB version**:  6.04

**Operating system**:  Windows 10

**Comment by Aokromes** [comment]
Because  it was complicate to search for worgen.
#11201
