### ISSUE TITLE
[3.3.5] DB/Quest: fix QuestType for "A Cold Front Approaches"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17498]
**Description**: QuestType for "[A Cold Front Approaches](http://www.wowhead.com/quest=13070/a-cold-front-approaches)" is wrongly set to 0 (autocomplete). Should instead be set to 2 (normal quest).

**Branch(es)**: 3.3.5

**TC hash/commit**:  fad58ad

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `quest_template` SET `QuestType`=2 WHERE `Id`=13070;
```

**Comment by Killyana** [comment]
There's some phasing issues with this quest

**Comment by SnapperRy** [comment]
Yep @Killyana, the phasing is quite messed up there. I believe it's because spell_area is only applied when you enter the zone, and not when you complete a quest. So you have to leave and come back.

But that's another issue (I'll see what I can do about it), this change is still valid :P

**Comment by Killyana** [comment]
Yes I will push this, Try to take a look to this: https://github.com/TrinityCore/TrinityCore/issues/16162#issuecomment-230183728
