### ISSUE TITLE
[3.3.5][Quest] Torch Catching

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17493]
**Description**:
Catch 4 torches in a row

**Current behaviour**:
When triggering the Unlit Torches near the capital bonfire, nothing happens.

**Expected behaviour**:
When triggering Unlit Torches near the capital bonfire, a shadow is supposed to leave, for you to follow.

**Steps to reproduce the problem**:
1. Pick up quest: http://www.wowhead.com/quest=11923/torch-catching
2. Stand near Bonfire
3. Trigger Unlit Torches (http://www.wowhead.com/item=34833/unlit-torches)

**Branch(es)**:
3.3.5

**TC hash/commit**:
TrinityCore rev. 663169750598 2016-07-02 14:17:50 +0200 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version**:
335.61

**Operating system**:
Debian 8

**Comment by Demonid** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/17446

Same mechanics

**Comment by Aokromes** [comment]
More than related, same bug.

**Comment by boom8866** [comment]
Confirm
