### ISSUE TITLE
DB update @ worldserver startup failed

### ISSUE THREAD

**Issue by britus** [TrinityCore/TrinityCore#17499]
**Description**:
* TrinityCore revision   : f45dfc1e4406 2016-07-03 10:39:41 +0200 (3.3.5 branch)
* TrinityCore buildtype  : Release

Worl server startp raises an error:

>> Reapplying update "2014_12_15_01_world.sql" '0F4E9DC' -> 'E87D31D' (it changed)...
ERROR 1054 (42S22) at line 121: Unknown column 'target_map' in 'field list'

**Current behaviour**: Tell us what happens
>> Auth database is up-to-date! Containing 3 new and 10 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 15 archived updates.
Updating World database...
>> Reapplying update "2014_12_15_01_world.sql" '0F4E9DC' -> 'E87D31D' (it changed)...
ERROR 1054 (42S22) at line 121: Unknown column 'target_map' in 'field list'

Applying of file '/home/eschrich/wow/tc-335/core/sql/updates/world/2014_12_15_01_world.sql' to database 'tc335_world' failed! If you are a user, pull the latest revision from the repository. If you are a developer, fix your sql query.
Update of World failed, please try manually.
In mysql_stmt_prepare() id: 8, sql: "INSERT INTO graveyard_zone (ID, GhostZone, Faction) VALUES (?, ?, ?)"
Table 'tc335_world.graveyard_zone' doesn't exist
In mysql_stmt_prepare() id: 9, sql: "DELETE FROM graveyard_zone WHERE ID = ? AND GhostZone = ? AND Faction = ?"
Table 'tc335_world.graveyard_zone' doesn't exist
Closing down DatabasePool 'tc335_world'.
Asynchronous connections on DatabasePool 'tc335_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'tc335_world' closed.
Could not prepare statements of the World database, see log for details.
Closing down DatabasePool 'tc335_world'.
Asynchronous connections on DatabasePool 'tc335_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'tc335_world' closed.
Closing down DatabasePool 'tc335_characters'.
Asynchronous connections on DatabasePool 'tc335_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'tc335_characters' closed.
Closing down DatabasePool 'tc335_auth'.
Asynchronous connections on DatabasePool 'tc335_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'tc335_auth' closed.
e
**Expected behaviour**: Tell us what should happen instead
continue update process with all other tables left and print a summery at end of the update process.

**Steps to reproduce the problem**:

1.  
2. 
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  

**TDB version**:  

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
You are running a custom core, clean core don't have such errors.

**Comment by britus** [comment]
LoL guy. its just cloned and sync with origin upstream. Thats part of yours :) OS like comments - yo#
