### ISSUE TITLE
[3.3.5][Quest] Torch Tossing

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#17492]
**Description**:
Torch Tossing

**Current behaviour**:
Quest is not completed after throwing 8 torches

**Expected behaviour**:
Quest should be completed and ready for delivery after hitting 8 braziers

**Steps to reproduce the problem**:
1. Pick up the quest Torch Tossing (http://www.wowhead.com/quest=11922/torch-tossing)

**Branch(es)**:
3.3.5

**TC hash/commit**:
TrinityCore rev. 663169750598 2016-07-02 14:17:50 +0200 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version**:
335.61

**Operating system**:
Debian 8

![torchtossing](https://cloud.githubusercontent.com/assets/1616448/16544855/b92a7ab8-4115-11e6-8b8d-3863db0cd18f.png)

**Comment by GnaXi** [comment]
Turns out to just be the time limit that doesn't reset the "Braziers Hit!" buff.

**Comment by GnaXi** [comment]
Also, visible bunnies in Silvermoon City :P
![torchtossing](https://cloud.githubusercontent.com/assets/1616448/16544905/1de5685e-4117-11e6-9dea-302383784687.png)

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by Demonid** [comment]
Maybe you have GM On or Visible Off ?

It's working for me =/

**Comment by GnaXi** [comment]
I was certain that I didn't have GM on, but I must have had then! =)

**Comment by Kittnz** [comment]
Confirmed, it does not count up & the stacks done go away.

**Comment by GnaXi** [comment]
Make sure that you complete the objective before the timer runs out.
That was my first mistake :P

**Comment by Kittnz** [comment]
Figured out my mistake too

**Comment by Aokromes** [comment]
#15279

**Comment by tkrokli** [comment]
Suggestion: Make it a rule to always turn on your own character name in the interface/Names menu. That is the easiest way to notice if you are in GM mode or not.

**Comment by funar** [comment]
I'm not sure if I should have created a new issue or not, but this one seems to have popped back into existence. I am not able to complete neither this quest, not the Catching Torches quests.  While the torches get thrown, and the flame effect on the braziers triggers, the "Braziers Hit" quest condition never increments.  It does not work for GMs nor players.

Completing the quest with ".quest complete" works (of course), but the daily quest for 40 Braziers also does not work.

Branch): 3.3.5

TC hash/commit: TrinityCore rev. 16f524ff2537 2018-06-26 20:17:59 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

OS: Ubuntu 18.04
