### ISSUE TITLE
Ulduar transporter to Spark of Imagination doesn't work

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#17503]
**Description**:
Ulduar transporter to Spark of Imagination doesn't work

**Current behaviour**: Tell us what happens
Get into the transporter and expect to be transported to Mimiron zone but instead nothing happens

**Expected behaviour**: Tell us what should happen instead
Get into the transporter and get transported to Mimiron zone

**Steps to reproduce the problem**:

1. Get in transporter
2. Wait
3. Nothing happens

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
284dd6b80d79f5691c82eda848c7474c5b87cfd9

**TDB version**:  
3.3.5
**Operating system**:  
Mac OS X

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
Unless someone broke it it was working before.

**Comment by obsidean** [comment]
to be clear, i am referring to the vehicle that brings you over.

**Comment by Aokromes** [comment]
#17354
