### ISSUE TITLE
[3.3.5][6.x] DB/Item: fix "Instant Statue Pedestal"

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17500]
**Description**: this item is currently not working on TC: you can summon the related NPC by using it, but nothing happens.

This fixes that. Data is not taken from sniffs though, quite hard to get a hold of since it's a TCG item. But for what it's worth, the fix works flawlessly compared to a [video from retail](https://www.youtube.com/watch?v=enAoYb01a-s).

Fixes #10599 (thanks to everyone who contributed there :P)

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  fad58ad

**TDB version**:  335.61

**Suggested fix**:
```sql
UPDATE `creature_template` SET `VehicleId`=732, `unit_flags`=33554432 WHERE `entry`=40246;

DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (74890, -75731);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES 
(74890, 75055, 0, "Instant Statue"),
(-75731, -75055, 0, "Instant Statue"),
(-75731, -74890, 0, "Instant Statue");

DELETE FROM `spell_custom_attr` WHERE `entry`=75731;
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES
(75731, 4096);
```

**Comment by tkrokli** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/10599 I guess? Maybe it can be closed with this one, if this solution gets accepted?

**Comment by SnapperRy** [comment]
Yep, forgot to check existing issues before posting this, edited. Thanks :)
