### ISSUE TITLE
[3.3.5] Portal in Boreanische Tundra to Orgrimmar?

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#17513]
**Description**:
Portal in Boreanische Tundra to Orgrimmar?

**Current behaviour**: Portal in Boreanische Tundra to Orgrimmar?

**Expected behaviour**: No Portal in Boreanische Tundra to Orgrimmar?

**Steps to reproduce the problem**:

1. Compile
2. Start
3. See

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
5af360844dfcb254b396961d47355c05193d9b8d
**TDB version**:  
Newest
**Operating system**:  
Win 6.1

![wowscrnshot_070416_213350](https://cloud.githubusercontent.com/assets/321832/16568851/9c83d1aa-422f-11e6-851a-be5f2c5d7a30.jpg)

**Comment by tkrokli** [comment]
TrinityCore rev. dd363662810e 2016-07-04 18:17:36 +0100 (3.3.5 branch) (Win64, Release, Static)

Can not reproduce your issue, unless the player character is on the quest [[A Life Without Regret](http://www.wowhead.com/quest=13266/a-life-without-regret)].

![wowscrnshot_070416_214826](https://cloud.githubusercontent.com/assets/4903600/16568994/5bf2f60a-4231-11e6-8c78-9712ed9d6ae8.jpg)

**Comment by jackpoz** [comment]
> Description:
> Portal in Boreanische Tundra to Orgrimmar?

what kind of description is this ?

**Comment by tkrokli** [comment]
I would think that any TC collaborator team member has access to change the title to something like this:
**[3.3.5] Portal to Orgrimmar in Warsong Hold, Borean Tundra**

**Comment by Killyana** [comment]
This portal is visible only if you are doing the quest http://www.wowhead.com/quest=13257/herald-of-war or if you're on gm mode.
``` sql
+INSERT INTO `gameobject_addon` (`guid`, `invisibilityType`, `invisibilityValue`) VALUES
+(@OGUID, 7, 1000

**Comment by genion18** [comment]
Hello,

Oh, sorry, this is the Problem (gm mode are "on".lol)

Thanks Killyana for this info.

greets

**Comment by jackpoz** [comment]
It seems you didn't read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md nor https://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/ , in particular
>Never ever test things with GM accounts
