### ISSUE TITLE
[3.3.5] DB/Spell: add usage of serverside spells for Pursuit of Justice talent

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17511]
**Description**: this Paladin talent uses the two serverside spells 61417 and 61418 to handle the mounted movement speed increase (confirmed by sniffs).

Thanks @ariel- for the input!

**Current behaviour**: Paladin talent Pursuit of Justice doesn't increase mounted movement speed.

**Branch(es)**: 3.3.5

**TC hash/commit**:  5af3608

**TDB version**:  335.61

**Suggested fix**:
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (26022, 26023);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(26022, 61417, 2, "Pursuit of Justice Mounted Movement Speed Increase"),
(26023, 61418, 2, "Pursuit of Justice Mounted Movement Speed Increase");
```

**Comment by Shauren** [comment]
Use linked aura, type = 2, you won't have to add both on cast and on remove entries

**Comment by tkrokli** [comment]
Also please add the column names of the table `spell_linked_spell` in your `INSERT INTO` part of the SQL.

**Comment by SnapperRy** [comment]
Changed, thanks :)
