### ISSUE TITLE
[3.3.5][Quest] "The Power to Destroy"

### ISSUE THREAD

**Issue by shiioo** [TrinityCore/TrinityCore#17522]
**Description**:

I'm not exactly sure it's an issue but it sure looks like it.
Quest: http://www.wowhead.com/quest=12132/the-power-to-destroy

This one asks you to get a buff from Koltira Deathweaver to go into the Realm of Shadows in order to kill few Shadowy Tormentors.
Did it few days ago, got out of the realm by clicking on the buff icon and completed the quest.

Yesterday, I upgraded from 5af360844dfcb254b396961d47355c05193d9b8d to bf30ec9c8efb40e78cc8c123780edf12e7a2a162 while being outside of Agmar's Hammer, where this quest is being done from start to finish.

I get back in town today to complete few other quests and those Shadowy Tormentors are now there, outside of the Realm of Shadows.

**Current behaviour**: Shadowy Tormentors can be seen in Agmar's Hammer despite not being in the Realm of Shadows.

**Expected behaviour**: Shadowy Tormentors shouldn't be seen outside of the Realm of Shadows.

**Branch(es)**: 3.3.5

**TC hash/commit**:  bf30ec9c8efb40e78cc8c123780edf12e7a2a162

**TDB version**:  latest

**Operating system**:  Win 7 x64

EDIT: Logged out and logged back in, and they're not there anymore. Not sure if that issue should remain opened in that case.

**Comment by Killyana** [comment]
I don't see how this could happen.
This shadows are spawned on phase 32, the phasing aura is casted on quest accepted and via the gossip if the player need to get it back, so it's not a spell_area.
http://www.wowhead.com/spell=47740/world-of-shadows

You have to check your auras once you're there (.list aura), maybe someone added a wrong spell_area in your server.

**Comment by tkrokli** [comment]
@shiioo : check if you are in GM mode or not. Useful tip: **always turn on your character name.**

**Comment by shiioo** [comment]
Well, I have two separate accounts on that server: a GM one, that I barely use, and the one I use to play. There's no other GM accounts, all the other ones only have member-level access.
And I've never altered any auras.

I recall going back and forth at Agmar's Hammer after completing that quest and logging out in the wild.

After that, I upgraded the server, slept on it, tried my luck at those 3 wanted quests the next day and went back into town.
That's when the "invisible" (which obviously were now "visible") mobs started attacking me.
Logged out, logged back in and the issue cleared itself. Was the only one playing at that time too.

Not sure it's worth keeping this one opened. At least it's recorded somewhere in case someone else encounters that issue and has more data to provide.
