### ISSUE TITLE
[6.x] [Core] Players corpses get automatically released when logging out

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/TrinityCore#17524]
**Description**: Players getting their corpses automatically released when logging out

**Current behaviour**: If you get killed in-game, don't release your corpse and just log out, your corpse gets automatically released, which means you even get removed from any instance you were in, and get another loading screen, pop up at the graveyard before you actually log out.

**Expected behaviour**: If you get killed in-game, don't release your corpse and just log out, there should be nothing weird happening, you simply just logout. When you log back in, if you're in an instance, you stay at your corpse, like nothing had happened, allowing party members to ressurect you for example. Outside instanced maps you seem to be automatically released once you log back in again.

**Steps to reproduce the problem**:
1. Get yourself killed, inside or outside an instance.
2. Without releasing your spirit, log out.
3. Inconsistent behavior represents itself, but you are automatically released from your corpse.

**Branch(es)**: 6.x

**TC hash/commit**:  9645f868ed42f2ba88c96d4106c547c480cd462b

**Comment by tkrokli** [comment]
Thanks for reporting that bug, looks like a repeating annoyance if playing or testing in group or raid.

**Comment by lorac2k14** [comment]
This is not a bug... just tested on retail if you die and log out your spirit will release

**Comment by Krudor** [comment]
Do I need to provide video proof?

**Comment by tkrokli** [comment]
Will this behaviour be different depending on if you are alone or in a 5-player party or raid group?

**Comment by Aokromes** [comment]
at least on 4.3.4 , raids and with accidental disconnect the corpse was  maintained inside raid.

**Comment by lorac2k14** [comment]
On accidental dc's yes corpse stays in instance
As for blatant disconnection your spirit "Will" release from corpse
I can provide video proof too if I must
I have tested in normal Dungeons Heroic Dungeons
