### ISSUE TITLE
Crash malformed packet

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17536]
**Description**: Sending CMSG_AUTH_SESSION packet when client is connecting to server will crashes worldserver

**Branch(es)**: 3.3.5

**TC hash/commit**:  e0cc650ea9339996b2b408f8168f6588bd088e42

**TDB version**:  61

**Operating system**:  Debian

**Output When Crashes**: terminate called after throwing an instance of 'ByteBufferPositionException'   what():  Attempted to get value with size: 32 in ByteBuffer (pos: 30 size: 8) Segmentation fault

http://paste.ubuntu.com/18694022/
http://paste.ubuntu.com/18694027/
http://paste.ubuntu.com/18702024/

**Comment by SQLfix** [comment]
Confirm 
https://github.com/TrinityCore/TrinityCore/issues/17437

**Comment by DeActiveDev** [comment]
confirm

**Comment by MrWorld** [comment]
confrim

**Comment by Shauren** [comment]
confirm my ass, don't add comments if you have nothing to add to the issue (such as crash logs if the issue is about a crash)

**Comment by SQLfix** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2b0e307ee937674c99e6b32079ef4f1888a17b36
ubuntu

My last 2 crash log [debug]
http://pastebin.com/RV8Mmr9a
http://pastebin.com/Rww6SArf

**Comment by Cl0n3r** [comment]
Confirm xDD

**Comment by sucklifex** [comment]
this still need to be ported in 3.3.5, so should be open ?

**Comment by Shauren** [comment]
No, issues that affect both branches get closed when one of them gets the fix because the other one will by default get it later too.

**Comment by AlexDev404** [comment]
> confirm my ass, don't add comments if you have nothing to add to the issue (such as crash logs if the issue is about a crash)

We'd have to see it first to confirm its existence :)
