### ISSUE TITLE
[3.3.5][Quest] Death from Below - Killed by World Invisible Trigger's Cannon Ball

### ISSUE THREAD

**Issue by Silvertower** [TrinityCore/TrinityCore#17532]
**Description**:
After starting the quest "Death from Below" and attempting to activate the nearby cannon, you will be killed by "World Invisible Trigger's Cannon Ball."

**Current behaviour**: Tell us what happens
After starting the quest "Death from Below" (Quest ID 667), if you try to activate the cannon on the ship you will be killed by "World Invisible Trigger's Cannon Ball."

**Expected behaviour**: Tell us what should happen instead
You should be able to stand next to/activate the cannon on the ship without being killed by "World Invisible Trigger's Cannon Ball."

**Steps to reproduce the problem**:

1. Accept quest "Death from Below" (Quest ID 667).
2. Try to activate the cannon on the ship next to the quest giver.
3. Be killed by "World Invisible Trigger's Cannon Ball."

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
3016783595c53d696c3355f4887da2bf83de3522

**TDB version**:  
'TrinityCore rev. 641747e5a19f+ 2016-07-06 08:49:32 -0700 (3.3.5 branch) (Unix, Release, Static)', '641747e5a19f+', 'TDB 335.61', '61'

**Operating system**:  
Ubuntu Server 16.04 64-bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
Some useful links:
- http://www.wowhead.com/quest=667/death-from-below
- http://wotlk.openwow.com/quest=667
- http://www.wowhead.com/npc=2610/shakes-obreen
- http://wotlk.openwow.com/npc=2610

NPC/item/spell info from the World Invisible Trigger and Cannon Ball might be useful.

**Comment by Silvertower** [comment]
Here's the creature "World Invisible Trigger":

On Wowhead:
[http://www.wowhead.com/npc=12999/world-invisible-trigger](http://www.wowhead.com/npc=12999/world-invisible-trigger)

In TDB:
```
# entry, difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, modelid1, modelid2, modelid3, modelid4, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, scale, rank, dmgschool, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance, unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race, type, type_flags, lootid, pickpocketloot, skinloot, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType, InhabitType, HoverHeight, HealthModifier, ManaModifier, ArmorModifier, DamageModifier, ExperienceModifier, RacialLeader, movementId, RegenHealth, mechanic_immune_mask, flags_extra, ScriptName, VerifiedBuild
'12999', '0', '0', '0', '0', '0', '17519', '11686', '0', '0', 'World Invisible Trigger', NULL, NULL, '0', '80', '80', '0', '114', '0', '1', '1.14286', '1', '0', '0', '2000', '2000', '1', '1', '1', '33587968', '2048', '0', '0', '0', '0', '0', '0', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'OutdoorPvPObjectiveAI', '0', '4', '1', '1.35', '1', '1', '1', '1', '0', '0', '1', '0', '130', '', '12340'
```

I cannot locate the "Cannon Ball" spell specifically that is being referenced. It seems most likely to be this (based on the fact that Effect2 is listed as "Instakill", which is exactly what happens, and what should happen to the attacking Naga):
[http://www.wowhead.com/spell=72680/cannon-ball](http://www.wowhead.com/spell=72680/cannon-ball)

I have a feeling that the cannon object is targeting the ground directly under the cannon (or maybe the user), instead of out on the shoreline as would be expected. I'm not sure how to locate what gets called when the user attempts to activate the cannon.

**Comment by SnapperRy** [comment]
[This is the spell used](http://www.wowhead.com/spell=4170).

I'm not sure why the gameobject casts it to anyone near it, but it should only affect the [Daggerspine Marauders](http://www.wowhead.com/npc=2775/daggerspine-marauder) involved in the quest.

The cannon is wrongly scripted, working on it. In the meanwhile, to fix this issue:
```sql
DELETE FROM `conditions` WHERE `SourceEntry`=4170 AND `SourceTypeOrReferenceId`=13;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 1, 4170, 0, 0, 31, 0, 3, 2775, 0, 1, 0, 0, "", "Cannon Ball can only hit \'Daggerspine Marauder\'");
```

**Comment by tkrokli** [comment]
Good point, SpellWork info says that spell should not target player/friendly targets, but meh. Bugs are unpredictable. For reference, SpellWork info rev. 105687228b87 2016-07-06 20:37:45 +0200 (3.3.5 branch):
```
ID - 4170 Cannon Ball
=================================================
Category = 0, SpellIconID = 965, activeIconID = 0, SpellVisual = (1564,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 4 (SPELL_SCHOOL_MASK_FIRE)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 6) "Vision Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 100, MaxRangeFriendly = 100

CastingTime (Id 1) = 0,00
RecoveryTime: 0 ms, CategoryRecoveryTime: 5000 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 1 (SPELL_EFFECT_INSTAKILL)
BasePoints = 1
Targets (17, 16) (TARGET_DEST_DB, TARGET_UNIT_DEST_AREA_ENEMY)
Radius (Id 9) 20,00

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```
