### ISSUE TITLE
Cannot start servers

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#17531]
**Description**: BNETServer and WorldServer don't start at all.

**Current behaviour**: Tell us what happens
When launching the servers I get these errors:
BNETserver --> Error in config file: cannot open file (/home/elle/server/etc/bnetserver.conf)
WorldServer --> Error in config file: cannot open file (/home/elle/server/etc/worldserver.conf)

**Expected behaviour**: Tell us what should happen instead
Servers should start

**Steps to reproduce the problem**:

1. Compile TC
2. Rename config files from ".conf.dist" to ".conf"
3. Move config files to bin folder
4. sudo ./bnetserver (press enter) / sudo ./worldserver (press enter)

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:   https://github.com/TrinityCore/TrinityCore/commit/be461280d2e919df3dbf7990cbf9684a03bcfbad

**TDB version**:  6.04

**Operating system**:  
Ubuntu 16.04 LTS

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
Never use sudo to run server.

**Comment by LuigiElleBalotta** [comment]
Well at least if it's not a core problem, help me finding a solution... I have same problem without sudo

**Comment by Aokromes** [comment]
User side problems don't belongs to tracker, you don't must move config files from installation place.

**Comment by tkrokli** [comment]
As Aokromes said, the most obvious error is that you moved the .conf files away from **server/etc/**
