### ISSUE TITLE
[3.3.5] Melee Range spells have less range than autoattacks

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#17539]
**Description**: After @Shauren changes to range of melee spells, melee spells can't be casted at the same distance at maximum range of autoattack

**Current behaviour**: Can't cast melee range spells at maximum autoattack range

**Expected behaviour**: You should be able to cast melee range spells at the same distance as you can autoattack

**Steps to reproduce the problem**:

1. Have 2 people and duel between them
2. Walk pixel by pixel until you can autoattack the enemy, then stop
3. You can autoattack the enemy but you can't cast spells like Mortal Strike (melee range spells)

**Branch(es)**: Tested in 3.3.5, don't know if this also happens in 6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/d0c377f86fec3d8ae3740fed303edfd6ec49a7ee

Proof (you can see how I can autoattack the enemy but when I try to cast Mortal Strike it returns Out of Range):
![](http://puu.sh/pTqVt/32aa97fd3d.jpg)

**Comment by SnapperRy** [comment]
Wonder if it's the autoattack range that's too high.

**Comment by Raydor** [comment]
Yeah probably the bug is on autoattack range side, I also thought that

**Comment by Shauren** [comment]
autoattack needs -1, see https://github.com/TrinityCore/TrinityCore/commit/e6a52d4aae9e8facc46c3b05e0560d540a928d73#commitcomment-18104812

**Comment by Raydor** [comment]
Tried just removing "dist" from the float
```c++
float maxdist = sizefactor;
```
for a fast testing and then is just the opposite, I can cast melee spells farther than I can autoattack. Probably you know that but just in case.

**Comment by Shauren** [comment]
Ok, then it will need a bit more work than I expected

**Comment by killradio** [comment]
@Raydor can you plz check after recent changes? Now I can cast even if staying a bit far for autoattack. Checked distance for autoattack with off - with TC you should stay closer.

**Comment by Shauren** [comment]
@killradio see https://github.com/TrinityCore/TrinityCore/commit/14b93c04ee07e9fe6e2767460e7fc7cc2b3e6808#commitcomment-18191617 - this part is missing to set min range 5

**Comment by chaodhib** [comment]
@killradio could you re-test with https://github.com/TrinityCore/TrinityCore/issues/17693 plz?

**Comment by Raydor** [comment]
Before continuing with my comment, i wanna say I know this might not gonna help you but hopefully you know the cause and can fix it so...

@chaodhib @Shauren a lot of players have been reporting me that they SOMETIMES(i hate this word) can't attack an enemy with a melee attack even tho they are in melee range (even just almoat in the same position) to their enemy. Its probably caused by lag but before these changes this wasnt happening.

I dont feel like creating a new issue for this cause I dont know how to reproduce this, neither my players, they just randomly cant do melee attacks at melee range.

**Comment by chaodhib** [comment]
They sometimes cant attack with what? Autos or melee spells or both? What makes them think they should be able to attack their target from where they are? Range indicator of melee spells? 

A video or a least a screenshot would be good. Without being able to reproduce the bug, it will be very hard to fix it.

**Comment by Raydor** [comment]
@chaodhib With both, sometimes autos and sometimes melee attacks, https://clips.twitch.tv/solaxmvp/DifficultReindeerBibleThump at second 8 you can see how he can not autoattack him even being so close to his enemy (he is saying "I don't gain rage... I can't hit from next to my enemy...").

I'm waiting for them to come to tell me more, I have a full streamming in which you can see various times the bug but its too long, im waiting for the streammer to tell me the minutes where the bug is. Anyways, maybe the one that I sen't you help in something.

I know its hard to fix without reproducing, thats why I apologise for these reports, just had to try because you maybe missed something and you might knew what or something like that.

**Comment by Raydor** [comment]
@chaodhib 
Im gonna do this comment and then gonna edit it when my players send me new screenshots/videos if you need it so I don't spam this, this is not the forum.

![](http://i.imgur.com/IY06UVT.jpg) 

In this screenshot, the player can't autoattack neither cast Plague Strike (you can see a little bit the flash on the spell) even tho he is clearly in range. As you can see, it returns Out of Range, the player told me that they both were running and they didn't stop, he was trying to cast the spell but the only way he is able to cast a spell after the bug happens is jumping or casting a ranged spell and then he is able again to cast melee spells.

**Comment by chaodhib** [comment]
I managed to reproduce the problem:
https://we.tl/ldzZxeqSij
What is shown in the debugger is the distance between the 2 players according to the core when CheckRange was called and the max range of the spell.

So yeah, basically, it's about communication delay between client & server aka lag..

**Comment by Raydor** [comment]
Okay... Doesnt sound like good news for servers, right now its so bad to have it, so much frustrating for melee players

I think im gonna revert the changes until a fix comes out.

**Comment by chaodhib** [comment]
Was there any follow up for the remaining issue?

**Comment by Raydor** [comment]
@chaodhib no

**Comment by chaodhib** [comment]
Gonna open an issue ticket for the remaining issue mentioned by @Raydor (since the PR I opened to solve it is a dead end)

**Comment by chaodhib** [comment]
Done: https://github.com/TrinityCore/TrinityCore/issues/18707. The issue is quite important imo. It deserves more attention.

**Comment by Raydor** [comment]
@chaodhib Has https://github.com/TrinityCore/TrinityCore/pull/18771 something to do with the issue you mentioned in https://github.com/TrinityCore/TrinityCore/issues/17539#issuecomment-242935319? Is it possible that it get better after your PR get merged or nothing will change?

**Comment by chaodhib** [comment]
No, sorry. It has no link. From my knowledge, the closed thing that could help with your issue is in https://github.com/TrinityCore/TrinityCore/pull/18128 but I'm not working on this atm.
