### ISSUE TITLE
[3.3.5] DB/Quest: Uncovering the Tunnels

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#17530]
http://www.wowhead.com/quest=12003/uncovering-the-tunnels
```sql
UPDATE `creature_template` SET `unit_flags`=33555200 WHERE  `entry` IN (26468, 26469, 26470);
```
(Sniff - 6.2.4 Build 21742) Add missing unit flag for:
http://www.wowhead.com/npc=26468/north-building
http://www.wowhead.com/npc=26469/south-building
http://www.wowhead.com/npc=26470/east-building

Branch(es): 3.3.5 (Tested)
TC hash/commit: 03b15d9
TDB version: 335.61

**Comment by Killyana** [comment]
This npcs are trigger-NPC they must have CREATURE_FLAG_EXTRA_TRIGGER, the unit_flag=UNIT_FLAG_NOT_SELECTABLE (0x2000000) is set by this FLAG_EXTRA so we need juste the `unit_flags`=768
``` sql
UPDATE `creature_template` SET `flags_extra`=128, `unit_flags`=768  WHERE  `entry` IN (26468, 26469, 26470);

**Comment by Killyana** [comment]
This npcs are trigger-NPC they must have CREATURE_FLAG_EXTRA_TRIGGER, the unit_flag=UNIT_FLAG_NOT_SELECTABLE (0x2000000) is set by this FLAG_EXTRA so we need juste the `unit_flags`=768
``` sql
UPDATE `creature_template` SET `flags_extra`=128, `unit_flags`=768  WHERE  `entry` IN (26468, 26469, 26470);

**Comment by Kodekc** [comment]
If you put the trigger flag, the quest will not work. NPC will not be able to kill himself

**Comment by Kodekc** [comment]
gave a ready solution, why invent something ...

**Comment by Killyana** [comment]
Why th npc need to kill himself?

**Comment by tkrokli** [comment]
@Kodekc : maybe you are confusing kill credit in script with the trigger NPC name?

**Comment by Kodekc** [comment]
This NPC is not a trigger, see SAI. If it is a trigger, then the script will not work. NPC model (11686) invisible, they simply did not have the flag

**Comment by Killyana** [comment]
It's a trigger: http://www.wowhead.com/npc=26468/north-building#screenshots:id=401886

**Comment by Kodekc** [comment]
@Killyana .morph 11686
