### ISSUE TITLE
[3.3.5][Auras]Aura charges consumed improperly

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17558]
**Description**: In some cases when a player has multiple auras that affect a specific spell using said spell should only consume one of the auras without reducing a charge or the entirety of the other aura.

**Current behaviour**: Using a spell that affects multiple auras will consume all related auras rather than just a specific one.

**Expected behaviour**: Multiple auras shouldn't be consumed.

**Steps to reproduce the problem**:

1. Take a destruction warlock with talents [[Conflagrate]](http://wotlk.openwow.com/spell=17962), [[Backlash]](http://wotlk.openwow.com/spell=34939), and [[Backdraft]](http://wotlk.openwow.com/spell=47260).
2. Let a mob attack you until you get [[Backlash]](http://wotlk.openwow.com/spell=34939) to proc.
3. Cast [[Immolate]](http://wotlk.openwow.com/spell=47811) on the target.
4. Cast [[Conflagrate]](http://wotlk.openwow.com/spell=17962) on the target to proc [[Backdraft]](http://wotlk.openwow.com/spell=47260)
5. Cast [[Shadow Bolt]](http://wotlk.openwow.com/spell=47809) or [[Incinerate]](http://wotlk.openwow.com/spell=47838).

You will see that the spell is cast instantly consuming the [[Backlash]](http://wotlk.openwow.com/spell=34939) spell as it should however one of the three charges of [[Backdraft]](http://wotlk.openwow.com/spell=47260) will get consumed as well when it shouldn't.

This issue existed in the past and was fixed via a workaround and now is back with the new spell system [(reference)](https://github.com/TrinityCore/TrinityCore/issues/2211).

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Comment by Shauren** [comment]
This is an exception with cast times where one of the mods makes the spell instant, otherwise both should be consumed

**Comment by ogeraisi** [comment]
Yes that's why I said in some cases, not sure which other spells are affected by this issue, I'm guessing [[Shadow Trance]](http://wotlk.openwow.com/spell=17941) would be one although I haven't tested it.

**Comment by Keader** [comment]
Has another issues related with Drop Charges
#15529
https://github.com/TrinityCore/TrinityCore/issues/932#issuecomment-4033950

**Comment by Keader** [comment]
@ariel- can you take a look? :smiley:
