### ISSUE TITLE
Ghost stuck on graveyard

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#17551]
**Description**:
Lately a lot of people is having the ghost stuck on graveyard after die on instance before a lot of times used to exist if you wiped on malygos, now appears to exist on all instances.

**Current behaviour**: Tell us what happens
ghost stuck on graveyard after die on instance.

**Expected behaviour**: Tell us what should happen instead
ghost can be move without problem.

**Steps to reproduce the problem**:

1. enter some instance, for example toc
2. die
3. release
4. if you can move, repeat
5. if you can't move /reload will allow you to move.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5a

**TC hash/commit**:  
0b9854428657

**TDB version**:  
61

**Operating system**:  
Linux, i don't think OS have nothing to do with this.

**Comment by offl** [comment]
I remember [this](https://bitbucket.org/lukaasm/hellground-wowemu/commits/6f0d04d6c7d6a714d1cd1883dfc90b9b7c563b66), but this fix doesn't work anyway. Maybe the reason(see commit title) of the bug is correct because projects are similar in some cases.

**Comment by tkrokli** [comment]
OK, so you are thinking that the core checks for a persistent buff like flask or battle elixir and its valid usage area, even if the player is in ghost form (which it should not, if everything else was correct)?

**Comment by Rhisk** [comment]
I see this problem sometimes when die while i suffer a lost control spell on my player.

**Comment by Rushor** [comment]
for me: the issue happens since one of those 2 commits https://github.com/TrinityCore/TrinityCore/pull/16256

**Comment by P-Kito** [comment]
Can confirm after https://github.com/TrinityCore/TrinityCore/pull/16256 it appeared

**Comment by Aokromes** [comment]
ef85d01746b744d563d7c17a0734bf7e562dfab0
