### ISSUE TITLE
[CRASH] Quest::CanIncreaseRewardedQuestCounters

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#17552]
**Description**:
When I log in to the game with some characters of my account the server crashes
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Log in.
2. Select a character from your account
3. Server crashes.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
eb1cd4c90708309a2e3c0e6e7c3e91645f725810
**TDB version**:  

**Operating system**:  
Ubuntu 16.04

Log:
https://gist.github.com/Pirricli/4819be055e45835917d7461d79a0de83
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
compile it on debug mode, also how about supply a pdump of afected character? :)

**Comment by Pirricli** [comment]
I can't enter to make a pdump...

**Comment by Aokromes** [comment]
pdump from console :P

**Comment by Pirricli** [comment]
good idea :)

**Comment by Pirricli** [comment]
Same log on debug mode
http://pastebin.com/JpLBgRHn
