### ISSUE TITLE
[3.3.5] Scripts/Spells: Life Tap

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17559]
**Description**: [Life Tap](http://wotlk.openwow.com/spell=57946) HP requirement goes up the more spirit players have causing the players to not be able to use it at times when they should be able to.

**Current behaviour**: The more spirit the player has the more HP required for the player to use the item goes.

**Expected behaviour**: Spell shouldn't scale with spirit.

**Steps to reproduce the problem**:
1. Take all gear off.
2. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell will convert X HP to Y mana.
3. Equip gear that gives extra spirit.
4. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell description states that more HP is required to use the spell.
5. Use [Life Tap](http://wotlk.openwow.com/spell=57946) you'll notice that the spell will convert still convert X HP to Y mana (as it should).

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Additional note**: The spell performs HP check based on HP percentage (not sure if that is how it should be).

**Comment by MrSmite** [comment]
Are you sure it's spirit that is scalig wrong and not spellpower?

The mana returned is scaled based on spell power. Perhaps this is also being incorrectly applied to the health requirement.

**Comment by ogeraisi** [comment]
Yes try equipping items that give you extra spirit and you'll see that the HP requirement will go up when it shouldn't

**Comment by ogeraisi** [comment]
Problem is in spell_warl_life_tap class

In SpellCastResult CheckCast()

Line #824
if ((int32(GetCaster()->GetHealth()) > int32(GetSpellInfo()->Effects[EFFECT_0].CalcValue() + (6.3875 * GetSpellInfo()->BaseLevel))))

Needs  to be changed to:
if (int32(GetCaster()->GetHealth()) > int32(GetSpellInfo()->Effects[EFFECT_0].CalcValue()))

Tooltip will still display wrong required HP value but the spell works as intended.

**Comment by Keader** [comment]
Looks like hack to me.
You tested without put items? just add some auras that change spirit or spell power and see what happens.
To me, looks  more logic if it is scaling with spell power..

**Comment by ogeraisi** [comment]
The mana gained does scale with spell power as intended regardless of this fix, the spell power has no effect on the returned mana value.

HP value should not change regardless of spell power, it is a fixed value and only the gained mana should change. As of now HP taken is a fixed value as it should be regardless of spell power. Problem is that the required HP check scales the value (even though it should be a fixed value) based on the spirit stat of the player.

This commit fixes the HP check and keeps the static value without the spirit scaling.

If anything what is this 6.3875 * BaseLevel based on?

**Comment by d3tr0l** [comment]
Nope, this should scale with spirit. It is completely missing in the script. The hp lost should be like this: "base damage" + 1.5*Spirit

**Comment by Keader** [comment]
Just for references...
About https://github.com/TrinityCore/TrinityCore/issues/17559#issuecomment-423246724
You can check in http://us.battle.net/wow/en/game/patch-notes/3-3-3

> KNOWN ISSUES
> Life Tap: The tooltip for this ability incorrectly states that the health lost is modified by spirit. Health loss is fixed and does not get increased by the Warlock’s spirit.

They are Lazy and dont fixed it in 3.3.5a too xD
