### ISSUE TITLE
[Crash] DespawnAtEvade with Hotswap

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17557]
**Description**: Using hotswap system and code present in : https://github.com/TrinityCore/TrinityCore/pull/17540 after you change something and hotswap build, server crash

**Current behaviour**:  After hotswap build and reload scripts, server crash

**Expected behaviour**: Server should not crash after reload scripts

**Steps to reproduce the problem**:

1. Add code present in https://github.com/TrinityCore/TrinityCore/pull/17540 in your trinity
2.  Active hotswap system
3. Go to Shade of Akama (.go xyz 548 401 113 564)
4. Change something in Shade of Akama script and save.
5. After Hotswap build and reload scripts, change again something and save.
6. normally after the second time when Shade of Akama spawn again (despawnAtEvade) server crash

Ps: Not necessary start fight.

Ps2: I cant provide Crashlog, because i dont know how reproduce it without Hotswap system, and i dont know how active hotswap in debug xD

**Branch(es)**: 3.3.5

**TC hash/commit**:  0547926f179f2e21af4921c43ca2cded5ba7c6a5

**TDB version**:  335.61

**Operating system**:  Win10

**Comment by Keader** [comment]
Summoning @Naios :dancer:

**Comment by Naios** [comment]
It happened again after d9755c637c39e600f145f5ecb7ff0ccf3724b1ad?

Just compile the core with debug, the crashlog is in `/crashes` as soon as the server has crashed.

**Comment by Keader** [comment]
yes still happen
and my crashes folder is always empty when this crash happens

**Comment by sirikfoll** [comment]
the Crashes folder doesn't appear to me, any known reason to that happen?

**Comment by Naios** [comment]
Maybe you could try to create the directory manually:

![screenshot_3](https://cloud.githubusercontent.com/assets/1146834/16710876/43f3422c-4640-11e6-9260-324748cd7bd6.png)

**Comment by Ovahlord** [comment]
try to trigger the evade-mode without script hotsswapping and see if the script itself is causing a issue

**Comment by Keader** [comment]
without hotswap i cant reproduce @Ovahlord

**Comment by Krudor** [comment]
I've scripted several bosses with DespawnAtEvade, using the hotswapping system, haven't had a problem :/

**Comment by Naios** [comment]
Also I retested your akama PR after d9755c6 and I didn't encounter any crash at all.
I guess a crashlog is required this time to solve your crash.

**Comment by Keader** [comment]
In this case, crash folder is always empty

![ss1](https://cloud.githubusercontent.com/assets/7120913/16714322/8e4b9464-4695-11e6-9fef-6b9c62505c39.jpg)

![ss2](https://cloud.githubusercontent.com/assets/7120913/16714323/9b05e5d8-4695-11e6-9ae7-09e3e8f78de9.jpg)

Clicking in button "depure" in crash window, give me this callstack:

https://gist.github.com/Keader/52b4e4d005e40ba6c0b4e87aae6d8cc5

**Comment by Naios** [comment]
What does the windows dialog show when you wait for some time.

**Comment by Keader** [comment]
"Depure" and "Close"

**Comment by Naios** [comment]
-> Depure and select your open Visual Studio instance

**Comment by Naios** [comment]
Better stacktrace: https://gist.github.com/Naios/361219edd09cfe92dd3e075a2fe7d1bd

**Comment by DeActiveDev** [comment]
after this commit 445746c402485fcac60c02842d0cb5e0dd605e5c have this similar problem release have crash log , but debug crash folder is always empty .

crash release : https://gist.github.com/DeActiveDev/ad00756e118cdc6ab09244276c0e3629

Branch(es): 3.3.5

TC hash/commit: 931a7623b24831adf679e0581735375077c8d252

TDB version: 335.61

**Comment by Aokromes** [comment]
Read https://github.com/TrinityCore/TrinityCore/issues/17557#issuecomment-231595023
