### ISSUE TITLE
[3.3.5] DB/Gameobject: spellfocus "Circle of Aquementas" should be invisible to players

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17560]
**Description**: [link](http://wotlk.openwow.com/object=148507).
- [ ] Not sure if this is the right way to make a spellfocus object invisible.

**Branch(es)**: 3.3.5

**TC hash/commit**:  ec919d7

**TDB version**:  335.61

**Suggested fix**:

``` sql
DELETE FROM `gameobject_addon` WHERE `guid`=20491;
INSERT INTO `gameobject_addon` (`guid`, `invisibilityType`, `invisibilityValue`) VALUES
(20491, 8, 1000);
```

**Comment by Killyana** [comment]
Related quest?
I think the model is wrong here.
