### ISSUE TITLE
Missing emote message when entering Zul'Gurub

### ISSUE THREAD

**Issue by SnapperRy** [TrinityCore/TrinityCore#17572]
**Description**: when you enter Zul'Gurub, the message "Your callous disregard for the sovereign might of the Gurubashi Empire has been noted. The inhabitants of Zul'Gurub have been alerted to your presence." should appear in chat as if it was an emote.

I'm not sure if it happened every time you enter the raid, or only when the bind is generated (ie, the first time you enter the raid each week).

Sources: [this](http://www.wowhead.com/zone=1977/zulgurub#comments:id=1140206), [this](http://imgur.com/a/VDFgm) and [this](https://www.google.com/search?q=Your+callous+disregard+for+the+sovereign+might+of+the+Gurubashi+Empire+has+been+noted.+The+inhabitants+of+Zul%E2%80%99Gurub+has+been+alerted+to+your+presence.).

**Branch(es)**: 3.3.5

**TC hash/commit**:   baf54cf

**TDB version**:  335.61

**Comment by dr-j** [comment]
Well currently when you enter zul'gurub you see hakkar yell 'Minions of Hakkar hear your god. The Sanctity of this temple has been compromised.  Invaders enroach upon holy ground! The Altar of blood must be protected. Kill them all', this only occurs when map is created or entered for first time.

**Comment by SnapperRy** [comment]
@dr-j: currently on TC nothing happens when you enter, although the yells are defined in the Hakkar script.

I'll try to dig for more screenshots to see if both the emote and the yell happen at around the same time.

**Comment by Killyana** [comment]
It's triggered by the areatrigger 3957, there's also the 3958 maybe it's use for something similar
.go trigg 3957
 .go trigg 3958

**Comment by SnapperRy** [comment]
Thanks @Killyana! Found also 3960 that should be the "You dare set foot upon Hakkari holy ground? Minions of Hakkar, destroy the infidels!" yell.

**Comment by dr-j** [comment]
Ye I found that problem when trying to script some of those missing events in Pos, even with non repeatable flags areatriggers scripts triggers immedietly

**Comment by Kittnz** [comment]
Or modify sai to have a repeatable flag on it

**Comment by Rushor** [comment]
another fix here https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/eastern_kingdoms/zulgurub/instance_zulgurub.cpp#L39

**Comment by Rushor** [comment]
i tried:

```c++
enum ZulGurubTriggerMisc
{
    // Trigger    
    AREA_TRIGGER_1 = 3960,
    AREA_TRIGGER_2 = 3958,
    AREA_TRIGGER_3 = 3957,
    
    // Texts
    SAY_ENTRANCE_1 = 2,
    SAY_ENTRANCE_2 = 3,
    SAY_ENTRANCE_3 = 10550,
};

class at_zul_gurub_entrance : public AreaTriggerScript
{
    public:
        at_zul_gurub_entrance() : AreaTriggerScript("at_zul_gurub_entrance")
        {
            activated = false;
        }
    
        bool OnTrigger(Player* player, AreaTriggerEntry const* trigger)
        {
            if (player->IsGameMaster())
                return false;
    
            if (!activated)
            {
                switch (trigger->id)
                {
                    case AREA_TRIGGER_1:
                        if (Creature* hakkar = player->FindNearestCreature(NPC_HAKKAR, 1000.0f))
                            hakkar->AI()->Talk(SAY_ENTRANCE_1);
                        break;
                    case AREA_TRIGGER_2:
                        if (Creature* hakkar = player->FindNearestCreature(NPC_HAKKAR, 1000.0f))
                            hakkar->AI()->Talk(SAY_ENTRANCE_2);
                        break;
                    case SAY_ENTRANCE_3:
                        if (Creature* hakkar = player->FindNearestCreature(NPC_HAKKAR, 1000.0f))
                            hakkar->Say(SAY_ENTRANCE_3, player);
                        break;
                    default:
                        break;
                }
                activated = true;
                return false;
            }
            return true;
        }
    
    private:
        bool activated;
};

void AddSC_instance_zulgurub()
{
    new instance_zulgurub();
    new at_zul_gurub_entrance();
}
```


```sql
DELETE FROM `areatrigger_scripts` WHERE `entry` IN (3958, 3960, 3957);
INSERT INTO `areatrigger_scripts` (`entry`, `ScriptName`) VALUES
(3958, 'at_zul_gurub_entrance'),
(3960, 'at_zul_gurub_entrance'),
(3957, 'at_zul_gurub_entrance');

UPDATE `creature_text` SET `TextRange`=3 WHERE  `entry`=14834 AND `groupid` IN (3, 2) AND `id`=0;
```

but it doesn't work

**Comment by Keader** [comment]
why not @Rushor?
The only reason for it dont work, is if player->FindNearestCreature cant find creatures
And Check if texts type are correct.

**Comment by Rushor** [comment]
> If you use same script for 3 AT, it will only work 1 time..

oh okay, i thought this is handled like scriptedai where you can use it several times

**Comment by Keader** [comment]
Ahh, nvm, forget my comment about split AT Scripts xd

**Comment by Rushor** [comment]
well i don't know, i rechecked the db entries, i temp spawned hakkar directly near the areatrigger to ensure "FindNearestCreature", gm was off. it fails every time

**Comment by Keader** [comment]
Any news on this @Rushor ?
if i remember right you was working on it, no?

**Comment by Rushor** [comment]
oh yes, your script works great :+1: however i'm not shure if we need to wait until we can fix this with sai too
