### ISSUE TITLE
Crash i_AI

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#17587]
**Description**:
CrashLogs: https://gist.github.com/sirikfoll/e2de3d63eae0329038aa1d201100bb34
(Sorry, but I can't provide a crashLog in full debug mode, just RelWithDebInfo)

**Steps to reproduce the problem**:
1. Unknown, we had seen this crash happen very rarely by quite some time ago, but seems to be incredible more frequently while using #17389
2. Just a guess, maybe related to the functionality _despawnAtEvade() at that specific case.

**Branch(es)**: 3.3.5

**TC hash/commit**:  d82534a7bbd401f4b672786749f10f5a95f6e76c

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17586#issue-165630845 someone has this crash too
@Runico Already happened in your serv?

**Comment by jackpoz** [comment]
> but seems to be incredible more frequently while using #17389

is this crash log with or without that PR ?

**Comment by Keader** [comment]
Jack, with that PR.
But this crashs is happened after that PR... after PR sees more frequent

**Comment by jackpoz** [comment]
since it's more frequent with that PR, can we get a debug crashlog ?

**Comment by sirikfoll** [comment]
Can't provide a full debug because i can't reproduce this alone, only on the server with more people, and there we can't full debug, because it's too heavy to run(we tried)

**Comment by sirikfoll** [comment]
another one https://gist.github.com/sirikfoll/fbcb3fe5514b5195c2a3e7be9180ef18

**Comment by jackpoz** [comment]
>GameEventMgr::RunSmartAIScripts (activate=true, event_id=33

**Comment by sirikfoll** [comment]
From @sucklifex http://paste.ubuntu.com/23049506/  Rev: 5868509

**Comment by sucklifex** [comment]
http://paste.ubuntu.com/23069656/

**Comment by jackpoz** [comment]
I'd suggest to change build flags to enable less optimizations and provide more details in the crashlogs, otherwise there's no way to figure out in which instance it happens

**Comment by sirikfoll** [comment]
I presume this is no longer valid, more than a year with no crash..
