### ISSUE TITLE
[3.3.5][Spell]Banish

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17581]
**Description**: Impossible to cancel the [Banish](http://wotlk.openwow.com/spell=18647) effect.

**Current behaviour**: Banished demons are immune to everything including the spell itself.

**Expected behaviour**: Casting [Banish](http://wotlk.openwow.com/spell=18647) on a banished demon should cancel the debuff.

**Steps to reproduce the problem**:

1. Cast [Banish](http://wotlk.openwow.com/spell=18647) on a demon.
2. Cast [Banish](http://wotlk.openwow.com/spell=18647) on the same banished demon.

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Comment by robinsch** [comment]
Proof?

**Comment by Aokromes** [comment]
Proof of recasting banish must remove banish? 
http://www.wowhead.com/spell=710/banish

"Banishes an enemy Demon, Aberration, or Elemental, preventing any action for 30 sec.  Limit 1 target.  Casting Banish again on the target will cancel the effect."

**Comment by Aokromes** [comment]
Confirmed bugged, long time ago it was working.

**Comment by ogeraisi** [comment]
what about 3.3.5?

**Comment by Shauren** [comment]
@ogeraisi If it was pushed to 6.x branch and is valid for 3.3.5 as well then it will be cherry picked at some point, not instantly (issues get closed once one of the branches have the fix - this ensure that work doesn't get duplicated in both branches if someone doesn't follow one of them and saves time when porting fixes so we don't have to search for issues)
