### ISSUE TITLE
NPCs while playing emote crashes the nearby clients if death state is applied

### ISSUE THREAD

**Issue by azeroc** [TrinityCore/TrinityCore#17582]
**Description**:
When you apply death state to NPCs (for example, casting Permanent Feign Death on few), while they are playing emote, then they will crash nearby clients. One NPC is not enough. You need to apply death state on at least few NPCs for the client crash to happen (for me it is usually enough with 2 npcs).

**Current behaviour**: NPCs (have to be at least few) under death state who previously were playing emote crash the client.

**Expected behaviour**: NPCs should not crash the client when applying death-state to them if they were previously playing an emote.
**Steps to reproduce the problem**:

1. Spawn several NPCs (e.g. Stormwind Guard / .npc add 1423)
2. Make them play emote (e.g. .npc play 1)
3. Apply any kind of death state spell or aura on em (e.g. .cast self 114371, which is Permanent Feign Death spell)
4. Keep applying death-state on emote-playing NPCs until client crashes

**Branch(es)**:  6.x (however, this was also present on TC's cataclysm and SkyFire's MoP core)

**TC hash/commit**:  a5b6d1992a50d4eaf4a7e13dc27e4c876467341a

**TDB version**:  6.04

**Operating system**:  Windows 10 64bit

**Additional notes**: I usually make custom command to toggle death state on NPCs, which removes emote animation plays before applying the actual death state aura, however, there have been occasions (when one spawns a looot of npcs with death state on) that even this doesn't work (client still crashes with a lot of death-stated NPCs, even when none of em were playing any emote previously).

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
#15263 ?

**Comment by Shauren** [comment]
yes, its the same issue
