### ISSUE TITLE
[3.3.5] Charge/intercept on focus breaks autoattack target

### ISSUE THREAD

**Issue by Aknunx** [TrinityCore/TrinityCore#17589]
**Description**: After charging or intercepting your focus with a macro like "/cast [target=focus] Charge" your character will start autoattacking your focus instead of your current target.

**Current behaviour**: Charge/Intercept on focus with macro breaks autoattack target.

**Expected behaviour**: You should be able to charge/incercept your focus without affecting your autoattack target if you haven't swapped your current target.

Proof : https://www.youtube.com/watch?v=z73ZsVb6aCE 2:33

**Steps to reproduce the problem**:
1. Create the macro /cast [target=focus] Charge
2. Start auto attacking your target, have your focused enemy and your target in autoattack range.
3.  Use the macro.
4. Check who's getting autoattacked now.

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/1a2bd0dc3aaa5668521cf758165c64f106e9a276

**Comment by Frytiks** [comment]
Confirmed !

**Comment by Aknunx** [comment]
Still happening on https://github.com/TrinityCore/TrinityCore/commit/7ce1cb295da73886b7ab62eb2c98f744dfb54d6d any news?

**Comment by robinsch** [comment]
This is from TC1 (5 years old)

```diff

         m_caster->GetMotionMaster()->MoveCharge(pos.m_positionX, pos.m_positionY, pos.m_positionZ + target->GetObjectSize());
 
     // not all charge effects used in negative spells
-    if (!IsPositiveSpell(m_spellInfo->Id) && m_caster->GetTypeId() == TYPEID_PLAYER)
-        m_caster->Attack(target, true);
+    if (Player* playerCaster = m_caster->ToPlayer())
+    {
+        // Check for selected unit - this will fix a bug with following macro: /cast [target=focus, exists] Intercept
+        if (!IsPositiveSpell(m_spellInfo->Id) && (playerCaster->getSelectedUnit() == target || !playerCaster->hasUnitState(UNIT_STAT_MELEE_ATTACKING)))
+            m_caster->Attack(target, true);
+    }
 }
 
 void Spell::EffectKnockBack(uint32 i)
```

**Comment by offl** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6399#issuecomment-656999541

**Comment by Aokromes** [comment]
this is still needed?

**Comment by CraftedRO** [comment]
According to blizzard [not a bug list](https://www.wowhead.com/tbc/news/burning-crusade-classic-not-a-bug-list-may-18-2021-322401) classic era:

![not a bug](https://user-images.githubusercontent.com/24683355/233856036-020e72d2-1e29-4cfc-b1a6-0e3276e4b6a2.PNG)
