### ISSUE TITLE
Crash unknow

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17584]
Crash Server with unknow Reason
Crash log
http://pastebin.com/ytGRfJku
http://pastebin.com/W9a2fTd0

https://github.com/TrinityCore/TrinityCore/commit/445746c402485fcac60c02842d0cb5e0dd605e5c
3.3.5
Ubuntu

https://github.com/TrinityCore/TrinityCore/issues/17536
https://github.com/TrinityCore/TrinityCore/issues/17437
https://github.com/TrinityCore/TrinityCore/issues/17523
Same issue

we use shauren fix 
https://github.com/TrinityCore/TrinityCore/commit/ce947814c6fa2c32c0908f1e7088ce971f74d365
but crash Again

**Comment by SQLfix** [comment]
`#28 Map::ProcessRelocationNotifies (this=this@entry=0x7fffd3867000, diff=diff@entry=11515) at /root/0000/src/server/game/Maps/Map.cpp:835
        pair = {x_coord = 291, y_coord = 171}
        cell = {data = {Part = {grid_x = 36, grid_y = 21, cell_x = 3, cell_y = 3, nocreate = 1, reserved = 0}, All = 17577316}}
        cell_relocation = {i_map = @0x7fffd3867000, cell = @0x7fffb9ffed00, p = @0x7fffb9ffed10, i_radius = 533.333313}
        cell_id = 87843
        y = 171
        x = 291
        gy = <optimized out>
        gx = <optimized out>
        cell_min = {x_coord = 288, y_coord = 168}
        cell_max = {x_coord = 296, y_coord = 176}
        i = {_Ptr = 0x7fffa580b020}
        reset = {<No data fields>}
        grid_notifier = <optimized out>
        world_notifier = <optimized out>
#29 0x000000000125a2ee in Map::Update (this=0x7fffd3867000, t_diff=11515) at /root/0000/src/server/game/Maps/Map.cpp:784
        updater = {i_timeDiff = 11515}
        grid_object_update = {i_visitor = @0x7fffb9ffed90}
        world_object_update = {i_visitor = @0x7fffb9ffed90}
#30 0x000000000123a2be in call (this=0x7fffa6d37680) at /root/0000/src/server/game/Maps/MapUpdater.cpp:42
No locals.
#31 MapUpdater::WorkerThread (this=0x21b0de8 <MapManager::instance()::instance+168>) at /root/0000/src/server/game/Maps/MapUpdater.cpp:113
        request = 0x7fffa6d37680`

**Comment by jackpoz** [comment]
It's not a crash, it's FreezeDetectorHandler triggered.
