### ISSUE TITLE
[3.3.5] DB/Creature: Scourging Crystal

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17596]
**Description**: [Scourging Crystal](http://wotlk.openwow.com/npc=24464) attacks the player if they're too close and follows them around.

**Current behaviour**: The creature attacks the players for 1 damage and follows them around.

**Expected behaviour**: The creature should be stationary and not engage combat.

**Steps to reproduce the problem**:
1. Take quest [Bring Down Those Shields (H)](http://wotlk.openwow.com/quest=11399) or [Bring Down Those Shields (Alliance)](http://wotlk.openwow.com/quest=11396).
2. Use [Scourging Crystal Controller](http://wotlk.openwow.com/item=33960) on [Scourging Crystal](http://wotlk.openwow.com/npc=24464) to remove their shield.
3. Move closer to the [Scourging Crystal](http://wotlk.openwow.com/npc=24464).

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Comment by tkrokli** [comment]
Title suggestion: **[3.3.5] DB/Creature: Scourging Crystal** (current standard for issue titles)
- http://www.wowhead.com/npc=24464/scourging-crystal

**Comment by offl** [comment]
Try with this:
```sql
--
DELETE FROM `smart_scripts` WHERE `source_type`=0 AND `entryorguid`=24464 AND `id`=2;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(24464,0,2,0,11,0,100,0,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Scourging Crystal - On Respawn - Set Reactstate Passive');
```

**Comment by Killyana** [comment]
This fixes the react but there's something wrong with the spell casted by the item,  the channeling 43882 is no longer casted 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_quest.cpp#L303-L371
