### ISSUE TITLE
Runetog Wildhammer does not allow players to fly to other flight points

### ISSUE THREAD

**Issue by Silvertower** [TrinityCore/TrinityCore#17592]
**Description**:
Runetog Wildhammer does not allow players to fly to other flight points

**Current behaviour**: Tell us what happens
When choosing the option "Show me where I can fly." from Runetog Wildhammer, nothing happens.

**Expected behaviour**: Tell us what should happen instead
Runetog Wildhammer should show available flight points to the player when choosing the option "Show me where I can fly."

**Steps to reproduce the problem**:

1. Go to Runetog Wildhammer in Shatter Point, Hellfire Peninsula
2. Talk to Runetog Wildhammer and choose option "Show me where I can fly."
3. Notice that nothing happens (no flight point window appears, the dialog does not close, etc.)

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

```sql

UPDATE `gossip_menu_option` SET `option_id` = 4, `npc_option_npcflag` = 8192 WHERE `menu_id` = 8095; -- Fix Flightmaster Runetog Wildhammer, Shatter Point


```

**TC hash/commit**:  
c4cbc4341f3394c5ff04d5eb604e6b08e3be8ae7

**TDB version**:  
335.61

**Operating system**:  
Ubuntu Server 16.04 64-bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Silvertower** [comment]
[9999_99_99_99_world.sql.txt](https://github.com/TrinityCore/TrinityCore/files/366428/9999_99_99_99_world.sql.txt)

**Comment by Aokromes** [comment]
It's simply write 
```code
```sql
-- fix
UPDATE BLABLA
```
```

**Comment by SnapperRy** [comment]
When your fix targets only the database, you can put the queries here, surrounded by the tags ````sql` and `````, like this:

```sql
UPDATE `gossip_menu_option` SET `option_id` = 4, `npc_option_npcflag` = 8192 WHERE `menu_id` = 8095;
```

**Comment by Silvertower** [comment]
Thanks. Will do. I was confused due to:

> - SQL-files : MUST be attached as a file
> 
> - Do NOT paste patches/SQL-files into the tracker as regular text in the commentary field

But perhaps I don't understand those statements properly.

Thanks again.

**Comment by Aokromes** [comment]
where you see that text?

**Comment by Silvertower** [comment]
https://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/

Third post.

**Comment by Aokromes** [comment]
Oh, wow, that post is extremely outdated.

**Comment by Silvertower** [comment]
I found that post by reading https://github.com/TrinityCore/TrinityCore/blob/3.3.5/CONTRIBUTING.md which has a link at the top to that post; that's why I was confused.

Thanks!

**Comment by Aokromes** [comment]
updated.
