### ISSUE TITLE
[3.3.5] Drakuru visibility

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17591]
3.3.5 931a7623b24831adf679e0581735375077c8d252

[Drakuru](http://www.wowhead.com/npc=26423/drakuru) in Grizzly Hills' Granite Springs camp is visible at all times. He should not be visible until you've completed [Filling the Cages](http://www.wowhead.com/quest=11984/filling-the-cages).

**Comment by dr-j** [comment]
Actually he stays visible if you loose drakurus elixir that is the npc you need to speak to get replacement as you need that item to summon (make visible) all the other spawns of drakuru.

**Comment by Treeston** [comment]
Yes, during Drakuru chain he should remain visible.

He should not _become_ visible until you've completed Filling the Cages though (that's the chain where you "catch" him and unlock the chain).

**Comment by Killyana** [comment]
I checked many videos, and Drakuru is always visible before the player take the quest Filling the Cages http://www.wowhead.com/quest=11984/filling-the-cages#videos:id=96590 also no invisibility aura on this npc on sniffs.
