### ISSUE TITLE
[3.3.5] Creature: Hearthglen Crusader (29102)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17609]
3.3.5 931a7623b24831adf679e0581735375077c8d252

[Creature: Hearthglen Crusader](http://www.wowhead.com/npc=29102/hearthglen-crusader#abilities)

A group of these will aggro any player walking up to the Lich King during the quest sequence including [Quest: An End To All Things...](http://www.wowhead.com/quest=12779/an-end-to-all-things) and quickly evaporate them from long range by spamming [Spell: Arrow Assault](http://www.wowhead.com/spell=53348/arrow-assault) at them.

These should either not attack players, or not attack players from as far away, or _something_. They make the DK starting experience pretty much impossible to complete as is.

**Comment by tkrokli** [comment]
This topic is also discussed in some older issues (even one of your own) :
- [Zone Dk Bug's](9215) #9215
- [[3.3.5][DB] Wrong Hearthglen Crusader spawns in Death Knight starting zone](15083) #15083
- [[3.3.5] Quest: An End To All Things... (12779)](16831) #16831

**Comment by Treeston** [comment]
Damn, I knew I had made an issue for this, but couldn't find it.

Closing as dup of #16831
