### ISSUE TITLE
[3.3.5] High priest thkal

### ISSUE THREAD

**Issue by Nephelion** [TrinityCore/TrinityCore#17605]
High priest thkal dont change tiger form

https://github.com/TrinityCore/TrinityCore/commit/931a7623b24831adf679e0581735375077c8d252
ubuntu
3.3.5

**Comment by tkrokli** [comment]
Please don't remove the TC issue template when creating new issues, they are put there for a reason. Your post is lacking information we would like to read and not try to guess what you mean, as well as having to look up the information ourselves (don't make the developers' work harder than it already is).

1. Make sure any NPCs are referred to by their exact name or ID by linking the page on wowhead.com or similar pages: http://www.wowhead.com/npc=14509/high-priest-thekal / http://wotlk.openwow.com/npc=14509 / http://wow.gamepedia.com/High_Priest_Thekal
2. Describe both **what is supposed to happen** and **what happens instead when using TC source.**
3. Also provide at least one example of how to test your issue by telling us how to check it in-game.

**Comment by Keader** [comment]
you can explain to me, what is the condition for boss transform yourself?
