### ISSUE TITLE
[3.3.5] Quest: Latent Power (12094)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17600]
3.3.5 931a7623b24831adf679e0581735375077c8d252

[Quest: Latent Power](http://www.wowhead.com/quest=12094/latent-power)

The [Item: Shard of Gavrock](http://www.wowhead.com/item=36787/shard-of-gavrock) ([Spell: Draw Power](http://www.wowhead.com/spell=47542/draw-power)) does not require the player to be near one of the three Ancient Stones to be channeled.
Conditions missing.

Also, quest credit is awarded at start of channel instead of at end of channel, which seems a bit strange. IDK if that's blizzlike.

**Comment by tkrokli** [comment]
Looks like a good opportunity to test Malcrom's Condition Creator (Windows application).
- https://community.trinitycore.org/topic/12800-condition-creator-windows-app/

BTW, he just told us in #trinity that he will update it to show as a taskbar icon (running/open program).

**Comment by offl** [comment]
Can be tested.
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceEntry`=47542;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 47542, 0, 0, 29, 0, 26855, 10, 0, 0, 0, 0, "", "Spell 'Draw Power' can be used within 10 yards of 'East Stone' OR"),
(17, 0, 47542, 0, 1, 29, 0, 26856, 10, 0, 0, 0, 0, "", "Spell 'Draw Power' can be used within 10 yards of 'North Stone' OR"),
(17, 0, 47542, 0, 2, 29, 0, 26857, 10, 0, 0, 0, 0, "", "Spell 'Draw Power' can be used within 10 yards of 'South Stone'");
```
> Also, quest credit is awarded at start of channel instead of at end of channel, which seems a bit strange. IDK if that's blizzlike.

[Blizzlike](https://youtu.be/nxufkJe41G4?t=12).
