### ISSUE TITLE
[3.3.5] Spells: Distract breaking Invisibility

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17602]
**Description**: Rogue spell Distract (Spellid: 1725) is breaking Mage Invisibility (Spellid: 66)

**Steps to reproduce the problem**:

1.  Use Distract in some Area with Invisible Mage.

PS: This sould be fixed by: https://github.com/TrinityCore/TrinityCore/pull/14824/files#diff-129ebf481e5c0e57031d350aacc95339R4

**Branch(es)**: 3.3.5

**TC hash/commit**:  445746c402485fcac60c02842d0cb5e0dd605e5c

**TDB version**:  335.61

**Operating system**: Win10  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Keader** [comment]
@robinsch can take a look?

**Comment by robinsch** [comment]
Invisibility isn't MOD_STEALTH. iirc it's removed because of hit by spell aura interrupt flags

**Comment by Keader** [comment]
closing...
i cant prove if this is valid issue (if this behavior is blizzlike)
