### ISSUE TITLE
[3.3.5] Mal'Ganis - The Culling of Stratholme

### ISSUE THREAD

**Issue by AciDCooL** [TrinityCore/TrinityCore#17606]
**Description**: At the last part of the The Culling of Stratholme Mal'Ganis should engage with Arthas in a roleplay, but he just stands there and is attackable (which should not happen until after the roleplay sequence). And he will bug out either will follow a player around, or keeps evadeing and running back to his original position.

**Current behaviour**: Mal'ganis is bugged and therefore players cant complete the dungeon.

**Expected behaviour**: Complete roleplay with Arthas and not be attackable until it is done.

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. c8e9184a4b14 2016-07-16 00:00:47 +0200 (3.3.5 branch) (Unix, Release, Static)

**TDB version**:  TDB_full_world_335.61_2016_04_11 + all incrementals

**Operating system**:  Fedora 24

**Comment by Wyrserth** [comment]
ca6228067507f19db230d415a1d088e5c0b5b808
