### ISSUE TITLE
WorldServer maybe Crash when input pinfo

### ISSUE THREAD

**Issue by cjl3230** [TrinityCore/TrinityCore#17618]
**Description**:
my role name is Master,When I input .pinfo without role name.WorldServer will Crash;

Using SSL version: OpenSSL 1.0.1j 15 Oct 2014 (library: OpenSSL 1.0.1j 15 Oct 2014)
Using Boost version: 1.61.0

**Current behaviour**: WorldServer will Crash;

**Expected behaviour**:get the same result as .pinfo Master

**Steps to reproduce the problem**:
1. input .pinfo at chat then press enter.
2. worldserver will crash.

**Branch(es)**: 3.3.5 

**TC hash/commit**:  028e473ec4693291266770616bcc54b71fefa835

**TDB version**:  TDB 335.61

**Operating system**:  Win10 64bit 10240

**Comment by Aokromes** [comment]
TC>TC> pinfo
TC>Player not found!
TC>

**Comment by cjl3230** [comment]
I test it in wow client(13930 zhCN/12340 zhTW)

**Comment by cjl3230** [comment]
@Aokromes

**Comment by jackpoz** [comment]
Invalid crash report, please read https://github.com/TrinityCore/TrinityCore/blob/6.x/CONTRIBUTING.md (i.e. where's the crashlog ?)

**Comment by cjl3230** [comment]
[028e473ec469_worldserver.exe_[18-7_11-49-59].txt](https://github.com/TrinityCore/TrinityCore/files/368510/028e473ec469_worldserver.exe_.18-7_11-49-59.txt)
@jackpoz

**Comment by jackpoz** [comment]
that's an exception triggered by a bad string format "Ban time remaining: %s, Banned by: %s, Reaso...".

Is "pinfo 发丝" the command you wrote ? it could be it doesn't support utf-8

**Comment by jackpoz** [comment]
summoning @Naios

**Comment by cjl3230** [comment]
@jackpoz yes， 发丝 is my role name

**Comment by Naios** [comment]
@cjl3230 You mean 发丝 is the name of your rbac group?

Could you explaim step by step how to setup a character/account that triggers the issue please?

Seems like an issue for cppformat...

**Comment by jackpoz** [comment]
That's most likely the name of the Character/Player
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_misc.cpp#L1458

**Comment by jackpoz** [comment]
>Parameter char** fmt = "Ban time remaining: %s, Banned by: %s, Reaso..."
Parameter char** <args_0> = " (offline)"
Parameter char** <args_1> = "发丝"
Parameter unsigned int& <args_2> = 0x3

**Comment by cjl3230** [comment]
@jackpoz @Naios 
1.I created a new Character/Player Name is Abcd.
2.Enter .pinfo Enter in the chat window(gm level is 3)
3.worldserver is also crash.

new crashlog is:
https://github.com/cjl3230/TrinityCore/blob/master/028e473ec469_worldserver.exe_%5B18-7_22-26-38%5D.txt

**Comment by Aokromes** [comment]
Maybe you have bad locales.

**Comment by Naios** [comment]
Bad locales for sure....

**Comment by cjl3230** [comment]
Mysql On my Win10 bit64 character set is utf-8.
mysql> show variables like '%char%';
+--------------------------+---------------------------------------------------------------+
| Variable_name            | Value                                                         |
+--------------------------+---------------------------------------------------------------+
| character_set_client     | utf8                                                          |
| character_set_connection | utf8                                                          |
| character_set_database   | utf8                                                          |
| character_set_filesystem | binary                                                        |
| character_set_results    | utf8                                                          |
| character_set_server     | utf8                                                          |
| character_set_system     | utf8                                                          |
| character_sets_dir       | C:\Program Files (x86)\MySQL\MySQL Server 5.5\share\charsets\ |
+--------------------------+---------------------------------------------------------------+
8 rows in set (0.00 sec)

I build TrinityCore by Visual Studio 2015 Update 2 . 
I think it might be worldserver running character set is ANSI cause this problem, when commissioning role name garbled.

**Comment by jackpoz** [comment]
> Maybe you have bad locales.

and what is one supposed to do to get good locales ?

**Comment by cjl3230** [comment]
@jackpoz 
Some Native habits lead role name may be in Chinese, Korean, Japanese or other languages, I think there should be a set mysql client character set of functions. Role-name character set when debugging I get is the ansi. If mysql character set used in the configuration file that would be better
Rough proposal for reference purposes only   ^_^

**Comment by Shauren** [comment]
Your database string entry is incorrect (and probably very old)
Crash log shows "Ban time remaining: %s, Banned by: %s, Reaso..."
But in current TDB the value for  is "├─ Banned: (Type: %s, Reason: %s, Time: %s, By: %s)"

Also you probably have custom changes in pinfo handler - in the crash log I can see ban info passing 3 arguments to format the ban line (string, string, int)
but in current code, https://github.com/TrinityCore/TrinityCore/blob/028e473ec4693291266770616bcc54b71fefa835/src/server/scripts/Commands/cs_misc.cpp#L1717 we have (string, string, string, string)

Based on that, I'm going to close this issue.

**Comment by cjl3230** [comment]
This is my problem. Use translated into Chinese database (world_335.59_2015_07_14) .trinity_string database has not been updated in time cause.Thanks All
