### ISSUE TITLE
Core/Auras: passive bonus shapeshift auras stacking with different casters

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#17617]
**Description**: Passive bonus talent auras are being applied on AuraEffect::HandleShapeshiftBoosts at apply case, by iterating player spells map; however in unapply case AppliedAuras map is iterated, and certain spells Like Improved Berserker Stance fail the IsRemovedAtShapeLost check, because logic is to not remove if caster != target.

This logic works fine for most cases, however when one creature forces player to shapeshift, like Nefarian's Berserk (23397) caster guid is now that of the creature, meaning that when the aura ends, the bonus aura is not removed, leaving us in a state that each cast stacks more and more.

**Current behaviour**: This special auras must not stack when triggered by the cast of creature

**Expected behaviour**: They shouldn't stack, bonus auras from talents must be removed everytime, no matter who is the caster.

**Steps to reproduce the problem**:

1. Create a warrior and invest points in Improved Berserker Stance
2. .go creature 85785
3. Engage and keep an eye in your Strength stat.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  028e473ec4693291266770616bcc54b71fefa835

**TDB version**:  335.61

**Operating system**:  Win10 x64

Refs: #3567 #6234 #14845

Note: merely removing the caster == Target [here](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuras.h#L162) breaks some hostile auras that have stance set but casted by enemy (eg. Druid demoralizing roar, can be removed by shapeshifting), now there is something in common: all these spells have SPELL_ATTR6_UNK23 set, which may be an indication of the correct check here.

```diff
         bool IsRemovedOnShapeLost(Unit* target) const
         {
-            return GetCasterGUID() == target->GetGUID()
-                    && m_spellInfo->Stances
+            return m_spellInfo->Stances
+                    && !m_spellInfo->HasAttribute(SPELL_ATTR6_UNK23)
                     && !m_spellInfo->HasAttribute(SPELL_ATTR2_NOT_NEED_SHAPESHIFT)
                     && !m_spellInfo->HasAttribute(SPELL_ATTR0_NOT_SHAPESHIFT);
         }
```

**Comment by ariel-** [comment]
Behaviour should've been mitigated with f183ed3c50cdcf13cd9fe608e0f4791177f120a4 (Still stacks auras of different caster, but only does it once)

**Comment by ccrs** [comment]
add a unit typeid check?
