### ISSUE TITLE
[3.3.5] DB/Creature: Proto-Drake Egg

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17610]
**Description**: [Proto-Drake Egg](http://wotlk.openwow.com/npc=23777) is not immune to fear/horror status effect.

**Current behaviour**: The egg flees when [Fear](http://wotlk.openwow.com/spell=65809), [Death Coil](http://wotlk.openwow.com/spell=47860) or similar spells are applied to them.

**Expected behaviour**: The egg be stationary and not move.

**Steps to reproduce the problem**:

1. Cast [Fear](http://wotlk.openwow.com/spell=65809) or [Death Coil](http://wotlk.openwow.com/spell=47860) on [Proto-Drake Egg](http://wotlk.openwow.com/npc=23777).

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Comment by dr-j** [comment]
adding the below should make them immune to fear and deathcoil but I wonder if in fact these should have any more immunities

~~~sql
UPDATE `creature_template` SET `mechanic_immune_mask`=8388672 WHERE  `entry`=23777;

**Comment by ogeraisi** [comment]
I am not sure, I tried casting [Fear](http://wotlk.openwow.com/spell=65809) on the creature in [this](https://github.com/TrinityCore/TrinityCore/issues/17596) bug report it was Feared however it stayed stationary, not sure what the actual behavior on retail is like.
