### ISSUE TITLE
[3.3.5] DB/Creature: Deathguard Molder

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#17626]
**Description**: [Deathguard Molder](http://wotlk.openwow.com/npc=27320) is spawned multiple times.

**Current behaviour**: There are two instances of the quest giver spawned.

**Expected behaviour**: There should be only one of them spawned (needs confirmation).

**Steps to reproduce the problem**:

SELECT * FROM `creature` WHERE `id`=27320;

**Branch(es)**: 3.3.5

**TC hash/commit**: [ebb33bb](https://github.com/TrinityCore/TrinityCore/commit/ebb33bbfc1f11a16e00e0d84965ad5350267940a)

**TDB version**: TDB_full_335.61_2016_04_11

**Operating system**: Windows 10 Pro x64

**Comment by malcrom** [comment]
Double Spawn guids 113329 and 113330. unsure of correct one.

**Comment by tkrokli** [comment]
TrinityCore rev. b008b677ad98 2016-07-18 20:30:58 +0200 (3.3.5 branch) (Win64, Debug, Static)
Using World DB: TDB 335.61 plus updates up to and including `2016_07_18_01_world.sql`

Confirmed. There are 2 copies of entry 27320, Deathguard Molder, on both entrances to Venomspite.
```sql
SELECT * FROM creature WHERE id=27320;
```
```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  -------------
113329   27320     571       0       0          1          1    24545             1     3257.62    -721.851      168.03      5.08075            300          0                0      10635        0             0        0           0             0              0
113330   27320     571       0       0          1          1    24545             1     3240.83     -680.25     166.873      1.93693            300          0                0      10635        0             0        0           0             0              0
```
Because it looks like the 2 copies are spawned at both ends of what could have been a waypoint path, I suggest removing the last one, `guid` 113330 (also because the quests he gives out are west of Venomspite and related to the nearby siege vehicles near `guid` 113329.)

**Suggested solution:**
```sql
-- remove duplicate creature 113330, Deathguard Molder
DELETE FROM `creature` WHERE `guid` = 113330 AND `id` = 27320;
```

**Comment by malcrom** [comment]
I suggest someone sniff it for path.

**Comment by Kittnz** [comment]
```sql
-- Delete double spawn
DELETE FROM `creature` WHERE `guid`=113329;

-- Pathing for Deathguard Molder Entry: 27320 'TDB FORMAT' 
SET @NPC := 113330;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=3242.083,`position_y`=-683.1053,`position_z`=166.9898 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1 ,3234.214,-662.9944,166.701,0,60000,0,0,100,0),
(@PATH,2 ,3242.083,-683.1053,166.9898,0,0,0,0,100,0),
(@PATH,3 ,3244.742,-697.8635,167.0145,0,0,0,0,100,0),
(@PATH,4 ,3248.017,-702.5844,167.3793,0,0,0,0,100,0),
(@PATH,5 ,3252.101,-710.5942,167.6412,0,0,0,0,100,0),
(@PATH,6 ,3257.548,-721.5476,168.0425,0,0,0,0,100,0),
(@PATH,7 ,3260.511,-729.2581,168.5909,0,60000,0,0,100,0),
(@PATH,8 ,3257.548,-721.5476,168.0425,0,0,0,0,100,0),
(@PATH,9 ,3252.101,-710.5942,167.6412,0,0,0,0,100,0),
(@PATH,10,3248.017,-702.5844,167.3793,0,0,0,0,100,0),
(@PATH,11,3245.563,-698.4318,167.1446,0,0,0,0,100,0);
-- 0x2010F047601AAE0000028300000C3809 .go 3242.083 -683.1053 166.9898

**Comment by malcrom** [comment]
Kittnz rocks

**Comment by malcrom** [comment]
Kittnz are there any orientation changes?

**Comment by tkrokli** [comment]
Looks like Deathguard Molder is pathing just fine now, with correct orientation at both entrances of Venomspite (facing out of the fenced area around the buildings) so players will meet him face to face at the gates if catching him when he pauses in his waypoint path. Thanks, Kittnz! :+1:

**Comment by Kittnz** [comment]
No orientation changes.
