### ISSUE TITLE
[3.3.5] Quest: Preparations for War (13418)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17621]
3.3.5 931a7623b24831adf679e0581735375077c8d252

[Quest: Preparations for War](http://www.wowhead.com/quest=13418/preparations-for-war)

Clicking the gossip on [Officer Van Rossem](http://www.wowhead.com/npc=31081) does nothing.

**Comment by Aokromes** [comment]
#10422
