### ISSUE TITLE
[3.3.5] Crash Player::UninviteFromGroup

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17637]
Crash server multi time
new crash . 

Log
http://pastebin.com/53zXVb5u

we have more LOG !

**Branch(es)**: 3.3.5 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/0be0606593cf6ce8a08735b070e64efa6b6f1667

**Operating system**:   ubuntu

**Comment by SQLfix** [comment]
http://pastebin.com/PFzVYF4K
http://pastebin.com/Qt8C7S8N

crash +10 time today

**Comment by Jildor** [comment]
#15071

**Comment by tkrokli** [comment]
@SQLfix : you may want to post your crash logs in the existing open issue #15071 .
