### ISSUE TITLE
SAI: Delay for Action talk

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17632]
The action_param2 = Duration to wait before TEXT_OVER event is triggered. for action=1 (talk) doesn't have any effect, the text is always triggered instantly.

To reproduce the issue: .npc add temp 25814
the  action_param2 =10000 so the text must be displayed 10 secs after the aggro, but actually it will be displayed on aggro without any delay.

rev. a2495002e590

**Comment by SnapperRy** [comment]
As it currently works, the delay set in param2 is used in conjunction with SMART_EVENT_TEXT_OVER: the text action happens instantly, and after the specified delay SMART_EVENT_TEXT_OVER is fired.

**Comment by ariel-** [comment]
So, this is actually a bad SAI instead of bad SAI handling, action_param2 on TALK actually is delay befor TEXT_OVER gets called, as you say.

What you want (delay before text) can be done with SMART_EVENT_UPDATE_IC with delay and norepeat flag

**Comment by Killyana** [comment]
In this case the wiki must be updated.

**Comment by chovie23q** [comment]
why does SMART_EVENT_TEXT_OVER not work? well like it will work, but you cant make another creature talk with it by using another creatures entry id for when they finish talking, is this intended? like heres my post on tc forums

https://community.trinitycore.org/topic/1210-sai-scripting-questions/?page=27

its right at the bottom

**Comment by Killyana** [comment]
Looks like SMART_EVENT_TEXT_OVER is broken
``` sql
UPDATE creature_template SET AIName='SmartAI' WHERE entry IN (39462,29629);
DELETE FROM smart_scripts WHERE entryorguid IN (39462,29629) AND source_type=0;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, COMMENT) VALUES
(39462,    0,    0 ,   0,    1,    0,    100,    0,    5000,    6000,    17500,    18000,    1,    0,    4500,    0,    0,    0,    0,    1,    0,   0,    0,    0,    0,    0,    0,    "test"),
(29629,    0,    0,    0,    52,    0,    100,    0,    0,    39462,    0,    0,    1,    0,    0,    0,    0,    0,    0,    1,    0,   0,    0,    0,    0,    0,    0,    "test respond");

DELETE FROM `creature_text` WHERE `entry` IN (39462,29629);
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`probability`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(39462,0,0,"text1",12,100,0,0,""),
(29629,0,0,"text2",12,100,0,0,"");

**Comment by chovie23q** [comment]
yep i think it is

**Comment by chovie23q** [comment]
if its not broken then why does it work like it should like its description?
