### ISSUE TITLE
Crash: MovementGenerators

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17638]
https://gist.github.com/Killyana/430ed7d090e24a3ccb124613c68e4e99
rev https://github.com/TrinityCore/TrinityCore/commit/eb1cd4c90708309a2e3c0e6e7c3e91645f725810

**Comment by tkrokli** [comment]
Any steps to reproduce this crash, like taking a taxi path (flight) or cancelling a flight path?

**Comment by Killyana** [comment]
No idea where it happen.

**Comment by sirikfoll** [comment]
Confirm: https://gist.github.com/sirikfoll/80081307e5c52ad02b64ca6a197e0e27
Rev. d82534a7bbd401f4b672786749f10f5a95f6e76c

**Comment by SQLfix** [comment]
in ALl my crash like this  : have :
MapUpdater::WorkerThread (this=0x23f0868 <MapManager::instance()::instance+168>)
MapManager::instance()::instance+168

**Comment by Naios** [comment]
@SQLfix it's not that uncommon to have the MapUpdater at the bottom of the callstack since most work is dispatched from there...

**Comment by Kinkiller-Uchiha** [comment]
I'm having a similar error
Crashes and when you leave this error worldserevr.exe
TrinityCore rev. 09a1cfdf771a+ 2016-07-23 03:37:09 +0200 (3.3.5 branch) (Win32, Release, Static) (worldserver-daemon)

http://prntscr.com/bxk5r2

**Comment by Aokromes** [comment]
release crashlogs are useless.

**Comment by Aokromes** [comment]
near 1 year since the last crashlog, if this bug is still valid post one NEW ticket with updated core.
