### ISSUE TITLE
GO Respawntimer fix for Quest 11695

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17643]
**Description**:
```sql
-- Wrong respawntimer for Quest GameObjects

-- http://www.wowhead.com/quest=11695/the-horn-of-elemental-fury
-- http://www.wowhead.com/object=187885/gurgleboggles-bauble
-- http://www.wowhead.com/object=187886/gurgleboggles-bauble

-- https://www.youtube.com/watch?v=6EDf8mWH77U

-- Gurgleboggle's Bauble
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (187885,187886);
```

**Branch(es)**: 3.3.5 / 6.x
**TC hash/commit**:  
TC>TrinityCore rev. 995f5f1f2b66 2016-07-20 20:19:20 +0200 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates
**Operating system**:  
Win7 64Bit

**Comment by tkrokli** [comment]
**Description:**

Wrong respawntimer for Quest GameObjects
- http://www.wowhead.com/quest=11695/the-horn-of-elemental-fury
- http://www.wowhead.com/object=187885/gurgleboggles-bauble
- http://www.wowhead.com/object=187886/gurgleboggles-bauble

Video: https://www.youtube.com/watch?v=6EDf8mWH77U
```sql
-- Gurgleboggle's Bauble
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (187885,187886);
```
