### ISSUE TITLE
[6.X] DB/Raids: Add game_tele for Hellfire Citadel Entrance.

### ISSUE THREAD

**Issue by Ulduar** [TrinityCore/TrinityCore#17646]
**Description**:
Hellfire Citadel WoD.
**Current behaviour**: Tell us what happens
Missing entrance for enter in Hellfire Citadel Raid WoD.
**Expected behaviour**: Tell us what should happen instead
See below.
**Steps to reproduce the problem**:

1. No
2. No
3. No

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/cc07a491f64fa958c8a27079bd2def84c577f816
**TDB version**:  
6.04
**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
Referenced issue:
https://github.com/TrinityCore/TrinityCore/issues/17114#issuecomment-234353214

``` SQL
DELETE FROM `game_tele` WHERE `id` IN (1579, 1580,1581,1582, 1583, 1584, 1585, 1586, 1587);
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
-- Black Gate - Archimonde fight.
(1579,4071.45,-2133.95,51.149,0,1448,DraenorHellfireCitadelBlackGateEntrance),
(1580,1491.65,2952.64,35.2391,0,1448,DraenorHellfireCitadelBlackGateExit),
-- Copypaste From WorldSafeLocs.dbc.
(1581,3976,81005859375,-760,64501953125,35,5158996582031,103,848999023438,1448,DraenorHellfireCitadelZoneInLocationOne),
(1582,3839,96997070313,-391,255004882813,45,5214996337891,181,268005371094,1448,DraenorHellfireCitadelZoneInLocationTwo),
(1583,4040,44995117188,2441,93994140625,206,296997070313,86,6840972900391,1448,DraenorHellfireCitadelZoneInLocationThree),
(1584,4152,080078125,2545,22998046875,179,916000366211,267,358001708984,1448,DraenorHellfireCitadelZoneInLocationFour),
(1585,4071,44995117188,-2133,94995117188,51,148998260498,266,305999755859,1448,DraenorHellfireCitadelZoneInLocationFive),
(1586,3965,76293945313,-694,637145996094,31,0609474182129,108,206237792969,1448,DraenorHellfireCitadelZoneInLocationSix),
(1587,3976,81005859375,-760,64501953125,35,5158996582031,103,848999023438,1448,DraenorHellfireCitadelZoneInLocationSeven);
```
Suggested sql.

**Comment by Shauren** [comment]
game_tele names must be unique and not contain spaces

**Comment by Ulduar** [comment]
Removed blanks with the names a little more complicated - in WorldSafeLocs.dbc names have not been signed.

**Comment by DDuarte** [comment]
Please test your SQL. 
`(1581,3976,81005859375,-760,64501953125,35,5158996582031,103,848999023438,1448,DraenorHellfireCitadelZoneInLocationOne),` has multiple issues, it won't even import.

**Comment by Ulduar** [comment]
@DDuarte 
read this:
```
Copypaste From WorldSafeLocs.dbc.
```

**Comment by Aokromes** [comment]
you must change x y z "," to "."

**Comment by DDuarte** [comment]
Read this: your code does not work, at all.

**Comment by offl** [comment]
Take a look at another names from this table for examples. They are simply to use. Just .tele shatt for teleport to Shattrath City. But.. do you want to type .tele DraenorHellfireCitadelZoneInLocationOne again and again? :О Difficult and non-memorable, I guess.

**Comment by Vandam** [comment]
Here is a Updated Code, this code has a ton of errors, invalid commas in wrong places.

`DELETE FROM `game_tele` WHERE `id` IN (1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587);
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1579, 4071.45, -2133.95, 51.149, 0, 1448, 'HFCEntrance');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1580, 1491.65, 2952.64, 35.2391, 0, 1448, 'HFCExit');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1581, 3976.81005859375, -760.64501953125, 35.5158996582031, 103.848999023438, 1448, 'HFCOne');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1582, 3839.96997070313, -391.255004882813, 45.5214996337891, 181.268005371094, 1448, 'HFCTwo');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1583, 4040.44995117188, 2441.93994140625, 206.296997070313, 86.6840972900391, 1448, 'HFCThree');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1584, 4152.080078125, 2545.22998046875, 179.916000366211, 267.358001708984, 1448, 'HFCFour');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1585, 4071.44995117188, -2133.94995117188, 51.148998260498, 266.305999755859, 1448, 'HFCFive');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1586, 3965.76293945313, -694.637145996094, 31.0609474182129, 108.206237792969, 1448, 'HFCSix');
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1587, 3976.81005859375, -760.64501953125, 35.5158996582031, 103.848999023438, 1448, 'HFCSeven');`
