### ISSUE TITLE
[3.3.5] Error when trying to build TrinityCore

### ISSUE THREAD

**Issue by 1285done** [TrinityCore/TrinityCore#17648]
I'm trying to build TrinityCore but I'm getting the following error a few times, which fails the build:

`linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function '_start':  
(.text+0x20): undefined reference to 'main'
collect2: error: ld returned 1 exit status 
make[2]: *** [src/server/shared/sharedPCH.h.gch] Error 1
make[1]: *** [src/server/shared/CMakeFiles/generate_sharedPCH.cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

The full log can be found here: http://pastebin.com/Q2KJ9tyE

I have tried the following:
Rerunning "cmake ../ -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=../Desktop/WowServer -DWITH_WARNINGS=1 -DTOOLS=1"
Running "make clean install" instead of "make install"
Building without the tools.

I am running this on Windows bash (Ubuntu 14.04.4 LTS)
I am using branch 3.3.5
I am using commit 5868509a6366d0ba7a0fe819c3ece0e4a57c7029

**Comment by Aokromes** [comment]
TrinityCore needs more advanced libs than the shipped on ubuntu 14.04.4
