### ISSUE TITLE
Unable to find pattern

### ISSUE THREAD

**Issue by justdothings** [TrinityCore/TrinityCore#17640]
**Description**: client version 6.2.4 (21355)

**Current behaviour**: http://prntscr.com/bvd2rh

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 6.x  

**TC hash/commit**:  420d096b6a477856979e2810a8f68d38cbce3349

**TDB version**:  TDB_full_6.04_2016_04_11.7z

**Operating system**:  windows server 2008 r2 standart

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
https://community.trinitycore.org/topic/10582-6x-branch-client-supported-70322248/#comment-79300
