### ISSUE TITLE
[Paladin] Art of War swing timer

### ISSUE THREAD

**Issue by lynxzor** [TrinityCore/TrinityCore#1765]
http://www.wowwiki.com/The_Art_of_War
Using art of wars instant exorcism or flash of light shouldn't reset the paladins swing timer.

df20ba9
up: 40

**Comment by Fergocina** [comment]
From 71b3887ec1392d858349b070fcda8138c004cd69 Mon Sep 17 00:00:00 2001
    From: Justin <fhasko@gmail.com>
    Date: Sun, 8 Feb 2015 23:39:36 +0100
    Subject: [PATCH] Reset auto-attack swing (Art of War)
    
    ---
     src/server/game/Spells/Spell.cpp | 5 +++++
     1 file changed, 5 insertions(+)
    
    diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
    index 4310439..e2c55c6 100644
    --- a/src/server/game/Spells/Spell.cpp
    +++ b/src/server/game/Spells/Spell.cpp
    @@ -3592,6 +3592,11 @@ void Spell::finish(bool ok)
                     break;
                 }
             }
    +
    +        // Fix for Flash of Light, Exorcism with Art of War
    +        if ( ( m_spellInfo->GetFirstRankSpell()->Id == 19750 || m_spellInfo->GetFirstRankSpell()->Id == 879 ) && m_caster->HasAura(59578) ) 
    +            found = true;
    +
             if (!found && !(m_spellInfo->AttributesEx2 & SPELL_ATTR2_NOT_RESET_AUTO_ACTIONS))
             {
                 m_caster->resetAttackTimer(BASE_ATTACK);
    -- 
    1.9.5.msysgit.0

**Comment by ariel-** [comment]
Bug confirmed in c25ad02c541c2621ef818ddc444812d30e14a143; report still valid.

**Comment by sirikfoll** [comment]
could reopen, please? Still valid..

**Comment by robinsch** [comment]
-    SPELL_ATTR6_UNK25                            = 0x02000000, // 25 Exorcism, Flash of Light
