### ISSUE TITLE
Implement AppVeyor

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#17652]
Since https://www.appveyor.com/blog/2016/07/16/migration-to-rackspace appveyor builds TC repo (335 branch) without timing out https://ci.appveyor.com/project/jackpoz/trinitycore-nbrh5 . This means we can build and release binaries for every commit

Version https://github.com/TrinityCore/TrinityCore/commit/5a550f9418483eb429a9953ed1ea4cf29620ace5

**Comment by PiskelDEV** [comment]
announced on 16, July (Birthday) :+1:

**Comment by jackpoz** [comment]
@DDuarte can this issue be closed ?
