### ISSUE TITLE
[3.3.5] The spell Shadowform (prist) freezes if use it very often. 

### ISSUE THREAD

**Issue by hlainin** [TrinityCore/TrinityCore#17658]
**Description**: When prist turns on and off Shadowform very often, it freezes and stop work at all.

**Steps to reproduce the problem**:

1. Turn off and on the Shadowform very quickly
2. See the video: https://youtu.be/D5GOobCLdu0

**Branch(es)**: 3.3.5

**TC hash/commit**:  
[09a1cfd](https://github.com/TrinityCore/TrinityCore/commit/09a1cfdf771a093b21779990ee516c22f66f4255)

**TDB version**:  
335.61

**Operating system**:  
Debian

**Comment by Aokromes** [comment]
#657

**Comment by hlainin** [comment]
Sorry I did not notice
