### ISSUE TITLE
World Server crashes when booting.

### ISSUE THREAD

**Issue by Nuppi** [TrinityCore/TrinityCore#17654]
World Server crashes when booting.
Loading Creature Base Stats ...
Then he freezes and crashes.

TrinityCore rev. 53e65db5cc21+ 2016-07-23 00:28:50 +0200 (6.x branch) (Win32, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file i:/TrinityCore_6.x.x/23.07.2016/Compile/bin/Release/worldserver.conf.
Using SSL version: OpenSSL 1.0.1h 5 Jun 2014 (library: OpenSSL 1.0.2e 3 Dec 2015)
Using Boost version: 1.61.0
Updating Auth database...
>> Auth database is up-to-date! Containing 6 new and 56 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 14 new and 42 archived updates.
Updating World database...
>> World database is up-to-date! Containing 117 new and 1123 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 17 new and 61 archived updates.
Realm running as realm ID 1
Using World DB: TDB 6.04
Using deDE DBC Locale
Missing name MonsterSight in config file i:/TrinityCore_6.x.x/23.07.2016/Compile/bin/Release/worldserver.conf, add "MonsterSight = 50.000000" to this file
Missing name GuarderSight in config file i:/TrinityCore_6.x.x/23.07.2016/Compile/bin/Release/worldserver.conf, add "GuarderSight = 50.000000" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps
Missing name Guild.SaveInterval in config file i:/TrinityCore_6.x.x/23.07.2016/Compile/bin/Release/worldserver.conf, add "Guild.SaveInterval = 15" to this file
Missing name Guild.UndeletableLevel in config file i:/TrinityCore_6.x.x/23.07.2016/Compile/bin/Release/worldserver.conf, add "Guild.UndeletableLevel = 4" to this file
Loading Trinity strings...
>> Loaded 1040 trinity strings in 2 ms
Initialize data stores...
>> Initialized 188 DB2 data stores in 4390 ms
>> Initialized 0 GameTables in 0 ms
Loading SpellInfo store...
>> Loaded SpellInfo store in 435 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 21 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 8959 SkillLineAbility MultiMap Data in 2 ms
Loading SpellInfo custom attributes...
>> Loaded 95 spell custom attributes from DB in 1 ms
>> Loaded SpellInfo custom attributes in 63 ms
Loading GameObject models...
Loading Script Names...
>> Loaded 2432 ScriptNames in 105 ms
Loading Instance Template...
>> Loaded 118 instance templates in 0 ms
Loading instances...
>> Loaded instances in 3 ms
Loading Localization strings...
>> Loaded 27247 creature locale strings in 310 ms
>> Loaded 19668 gameobject_template_locale strings in 180 ms
>> Loaded 18337 Quest Tempalate locale strings in 546 ms
>> Loaded 13627 Quest Objectives locale strings in 62 ms
>> Localization strings loaded in 1102 ms
Loading Account Roles and Permissions...
>> Loaded 666 permission definitions, 649 linked permissions and 4 default permissions in 2 ms
Loading Page Texts...
>> Loaded 1939 page texts in 4 ms
Loading Game Object Templates...
>> Loaded 38850 game object templates in 395 ms
Loading Transport templates...
>> Loaded 66 transport templates in 19 ms
Loading Spell Rank Data...
>> Loaded 781 spell rank records in 0 ms
Loading Spell Required Data...
>> Loaded 21 spell required records in 1 ms
Loading Spell Group types...
>> Loaded 273 spell group definitions in 1 ms
Loading Spell Learn Skills...
>> Loaded 180 Spell Learn Skills from DBC in 21 ms
Loading Spell Learn Spells...
>> Loaded 2 spell learn spells, 783 found in Spell.dbc in 21 ms
Loading Spell Proc Event conditions...
>> Loaded 374 extra spell proc event conditions in 10 ms
Loading Spell Proc conditions and data...
>> Loaded 0 spell proc conditions and data. DB table `spell_proc` is empty.
Loading Aggro Spells Definitions...
>> Loaded 20 SpellThreatEntries in 2 ms
Loading Spell Group Stack Rules...
>> Loaded 8 spell group stack rules in 1 ms
Loading NPC Texts...
>> Loaded 9333 npc texts in 51 ms
Loading Enchant Spells Proc datas...
>> Loaded 16 enchant proc data definitions in 0 ms
Loading Item Random Enchantments Table...
>> Loaded 28937 Item Enchantment definitions in 27 ms
Loading Disables
>> Loaded 5177 disables in 9 ms
Loading Items...
>> Loaded 93570 item templates in 849 ms
Loading Item set names...
>> Loaded 624 item addon templates in 2 ms
>> Loaded 14 item script names in 0 ms
Loading Creature Model Based Info Data...
>> Loaded 51592 creature model based info in 87 ms
Loading Creature templates...
>> Loaded 77012 creature definitions in 1776 ms
Loading Equipment templates...
>> Loaded 19475 equipment templates in 34 ms
Loading Creature template addons...
>> Loaded 15646 creature template addons in 28 ms
Loading Reputation Reward Rates...
>> Loaded 14 reputation_reward_rate in 1 ms
Loading Creature Reputation OnKill Data...
>> Loaded 2045 creature award reputation definitions in 5 ms
Loading Reputation Spillover Data...
>> Loaded 28 reputation_spillover_template in 1 ms
Loading Points Of Interest Data...
>> Loaded 493 Points of Interest definitions in 2 ms
Loading Creature Base Stats...

**Comment by Aokromes** [comment]
you need wow 7.0.3.22293

**Comment by GnaXi** [comment]
I have the exact same issue and have extracted from 22293.

**Comment by Vincent-Michael** [comment]
you need gt folder

**Comment by GnaXi** [comment]
Care to elaborate @Vincent-Michael? Never heard of this "gt" folder.
