### ISSUE TITLE
 Some required *.txt GameTable files (23) not found or not compatible

### ISSUE THREAD

**Issue by Remix99** [TrinityCore/TrinityCore#17662]
**Description**:
 Some required *.txt GameTable files (23) not found or not compatible:
GameTable file ./gt\ArmorMitigationByLvl.txt cannot be opened.
GameTable file ./gt\BarberShopCostBase.txt cannot be opened.
GameTable file ./gt\BaseMp.txt cannot be opened.
GameTable file ./gt\CombatRatings.txt cannot be opened.
GameTable file ./gt\ItemSocketCostPerLevel.txt cannot be opened.
GameTable file ./gt\HpPerSta.txt cannot be opened.
GameTable file ./gt\NpcDamageByClass.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp1.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp2.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp3.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp4.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp5.txt cannot be opened.
GameTable file ./gt\NpcDamageByClassExp6.txt cannot be opened.
GameTable file ./gt\NpcManaCostScaler.txt cannot be opened.
GameTable file ./gt\NpcTotalHp.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp1.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp2.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp3.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp4.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp5.txt cannot be opened.
GameTable file ./gt\NpcTotalHpExp6.txt cannot be opened.
GameTable file ./gt\SpellScaling.txt cannot be opened.
GameTable file ./gt\xp.txt cannot be opened.

**Current behaviour**: After intilizing datastore in console of worldserver it shows the error (mentioned above)

**Expected behaviour**: Gametable error

**Branch(es)**: 6.x 
**commit**:  060256000b1a553a21581b9b65e12f7cb034e148

**TDB version**:  Latest

**Operating system**:  Windows 10

**Comment by DJScias** [comment]
Hello there @Remix99 ,

These "gt" files are found in the "gt" folder that is created when extracting the db2s and maps with the mapextractor.

Make sure the created "gt" folder is in the same location as the maps, vmaps, dbc, etc.. folders (AKA the root of your project).

Kind regards,
DJScias

**Comment by Shauren** [comment]
Not a bug
