### ISSUE TITLE
Quest 12823 A Flawless Plan (Part 1 of 2)

### ISSUE THREAD

**Issue by RedSonja** [TrinityCore/TrinityCore#17667]
**Description**:
https://wotlk-twinhead.twinstar.cz/?quest=12823

**Current behaviour**: Quest is in K3 region, you have to place explosives and kill the mob that is spawned. He does appear and will agro and you can fight him and although the screen reports that he is dead he remains a 1hp and the server hangs there and then crashes.

**Expected behaviour**: Tell us what should happen instead
Should not crash the server
**Steps to reproduce the problem**:
Take the quest.
1. Pick up quest from Gino in K3 area
2. 
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  

028e473
**TDB version**:  
61
**Operating system**:  
Win10

I do not have a crash report for this sorry.

**Comment by dr-j** [comment]
Cannot reproduce using 	Hardpacked Explosive Bundle at Frostguts Altar spawns Frostgut a distance who yells line and moves to player and when killed quest completes no crash.

Tested on https://github.com/TrinityCore/TrinityCore/commit/5868509a6366d0ba7a0fe819c3ece0e4a57c7029
