### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrWorld** [TrinityCore/TrinityCore#17664]
**Description**: New Crash

**Branch(es)**: 3.3.5

**TC hash/commit**: after  b008b67  

**TDB version**:  61

**Operating system**:  Win

https://gist.github.com/MrWorld/da174fbee6caaa37fa27f7fff1be6d0a

**Comment by jackpoz** [comment]
I see a lot of 0xDDDDDDDD around

**Comment by MrWorld** [comment]
and Some user have edited WowAddin Project ,so see this packets

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.659 Number: 41072
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.659 Number: 41073
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.660 Number: 41074
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.661 Number: 41075
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.662 Number: 41076
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.663 Number: 41077
List Flags?: Unknown1 (1)

ClientToServer: CMSG_CONTACT_LIST (0x0066) Length: 4 ConnIdx: 0 EP: xx.xx.xxx.xx:27957 Time: 07/23/2016 11:40:27.664 Number: 41078
List Flags?: Unknown1 (1)

client send 41078 CMSG_CONTACT_LIST to server .
any way to fix this Crash ?
