### ISSUE TITLE
[3.3.5a] Kel'Thuzad Monsters wall

### ISSUE THREAD

**Issue by mason333** [TrinityCore/TrinityCore#17666]
Description:
Hi, I have some issue with Kel'Thuzad monsters, the video will explain better then i do..
Current behaviour: Tell us what happens
https://www.youtube.com/watch?v=rRi0ESgWIFc
as you can see, the walls don't kept the monsters in and they can go out and attack me..

Expected behaviour: Tell us what should happen instead
I expect them to stay in this little cave behind the walls.

Steps to reproduce the problem:

Ive tried to put the fix files and the original files
tried to read same issues, but i didn't found..
Branch(es): 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
TrinityCore rev. 1a2bd0dc3aaa+ 2016-07-15 15:33:23 +0200 (3.3.5 branch) (Win64, Release, Static)
**TDB version**:  
TrinityCore rev. 1a2bd0dc3aaa+ 2016-07-15 15:33:23 +0200 (3.3.5 branch) (Win64, Release, Static)
**Operating system**:  
Windows Server 2012 R2

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
triplicated. #16388

**Comment by mason333** [comment]
its not the same, my monsters don't move weird like flying around, i just don't have those walls that separate...

**Comment by Keader** [comment]
@mason333 test with https://github.com/TrinityCore/TrinityCore/pull/16634

**Comment by tkrokli** [comment]
@mason333 : What kind of walls and what caves do you mean? Looking at this video (https://www.youtube.com/watch?v=nM0NFpmi9X0 - [**TankSpot's Guide to Kel'Thuzad**](https://www.youtube.com/watch?v=nM0NFpmi9X0)) from 7 years back, I can only see some visuals in a few cubicles which may be missing in TC. Please explain more if you can.
