### ISSUE TITLE
.npc move not visually updating

### ISSUE THREAD

**Issue by azeroc** [TrinityCore/TrinityCore#17679]
**Description**: When performing command .npc move (also on .gobject move), the object does not visually move for nearby players. They have to teleport in and out or simply relog to see the new location changes.

**Current behaviour**: See above description.

**Expected behaviour**: After performing move command on npc/gobject, they should visually teleport to their new location.

**Steps to reproduce the problem**:
1. Perform .npc move or .gobject move on an object
2. DB-side and server-side they are moved, but client-side you can still see them at their old location.

**Branch(es)**:  6.x

**TC hash/commit**:  cc07a491f64fa958c8a27079bd2def84c577f816

**TDB version**:  6.04

**Operating system**:  Windows 10 64bit

**Question**: I know that there is a fix for this by "recreating" npcs/gobjects with their same spawn IDs, but recreation on NPCs specifically is slow (the old NPC takes about 1-2 secs to despawn/get deleted). Is there a way to make NPC move instantly? 

(Another fix I tried is with MotionMaster: if I relocate NPC by settings it coordinates to somewhere else and then doing `target->GetMotionMaster()->MoveJump(x, y, z, o, 10000.0f, 0.0f, EVENT_JUMP, true);`, - the NPC will teleport instantly to the new location, but ONLY if new location is further than 100 yards, otherwise it will make NPC leap towards new location between those 100 yards or less)

**Comment by Killyana** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/16661

**Comment by MrSmite** [comment]
Old bug. In fact, if you execute the move command twice consecutively it will update the NPC in the world.

**Comment by azeroc** [comment]
Rummaging through opcodes, I found a fix: `target->SendTeleportPacket(target->GetPosition());` (where target is creature pointer in .npc move command handler), you simply need to add that line of code at the end of HandleNpcMoveCommand's code or rather after NPC's position is updated server-side. This will visually teleport the NPC to new location.

As for GameObject moving. The best I can think of is invalidating its GUID for client and generate a new GUID, which is set for the same GameObject, so this new GUID is sent to the client and the client visually places that new gameobject at its new location. Though, for more simple resolution one could simply recreate gameobject with same spawn Id.

**Comment by Killyana** [comment]
Looks to be fixed by https://github.com/TrinityCore/TrinityCore/pull/19056
