### ISSUE TITLE
Dynamic Linking Error 3.3.5A

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#17677]
**Description**:

```quote
8>C:\local\boost_1_59_0\boost/multi_index/detail/ord_index_node.hpp(130): error C2280: 'std::unique_ptr<ScriptModule,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)' : attempting to reference a deleted function
8>          with
8>          [
8>              _Ty=ScriptModule
8>          ] (C:\Users\Admin\Desktop\TrinityCore-3.3.5\src\server\game\Scripting\ScriptReloadMgr.cpp)
8>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(1486) : see declaration of 'std::unique_ptr<ScriptModule,std::default_delete<_Ty>>::unique_ptr'
8>          with
8>          [
8>              _Ty=ScriptModule
8>          ]
8>          This diagnostic occurred in the compiler generated function 'ScriptModuleDeleteMessage::ScriptModuleDeleteMessage(const ScriptModuleDeleteMessage &)'
```

![Error](http://image.prntscr.com/image/4f6d58a39d694f82841c977b81f4d6a5.png)

**Current behaviour**: Tell us what happens
See description!

**Expected behaviour**: Tell us what should happen instead
Compiling without error?

**Steps to reproduce the problem**:

1. Download the Source
2. Make your changes in cmake
3. Use Dynamic Linking and compile

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
2d0fa2d0201dce03f958aa7583f51fc92c46f795

**TDB version**:  
335.61

**Operating system**:  
Windows 10 Pro N x64
32GB Ram

**Comment by Shauren** [comment]
"See description" followed by a screenshot of an error in **german** is not very useful

**Comment by Shoxxo** [comment]
i only have german programs sry that is my mainlanguage !

**Comment by Shoxxo** [comment]
Error updated in englisch

**Comment by tkrokli** [comment]
From CMake: TrinityCore revision   : 2d0fa2d0201d 2016-07-28 03:12:35 -0300 (3.3.5 branch)
TDB 335.61 (plus updates), Windows 10 x64. Current Generator: Visual Studio 12 2013 Win64
Visual Studio Version 12.0.40629.00 Update 5

Confirmed. All that is needed to reproduce this issue is to include `WITH_DYNAMIC_LINKING` in CMake.
```
 *** WITH_DYNAMIC_LINKING - INFO!
 *** Will link against shared libraries!
 *** Please note that this is an experimental feature!
```
```
13>C:\local\boost_1_59_0\boost/multi_index/detail/ord_index_node.hpp(130): error C2280: 'std::unique_ptr<ScriptModule,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)' : attempting to reference a deleted function
13>          with
13>          [
13>              _Ty=ScriptModule
13>          ] (C:\github.com\tkrokli\TrinityCore\src\server\game\Scripting\ScriptReloadMgr.cpp)
13>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(1486) : see declaration of 'std::unique_ptr<ScriptModule,std::default_delete<_Ty>>::unique_ptr'
13>          with
13>          [
13>              _Ty=ScriptModule
13>          ]
13>          This diagnostic occurred in the compiler generated function 'ScriptModuleDeleteMessage::ScriptModuleDeleteMessage(const ScriptModuleDeleteMessage &)'
```

**Comment by Shauren** [comment]
Ok, this will work with VS 2015

**Comment by Aokromes** [comment]
https://community.trinitycore.org/topic/12805-visual-studio-2013-end-of-life/
