### ISSUE TITLE
Pristine Glowbear Pelt has incorrect disenchant table

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#17684]
**Description**:
Pristine Glowbear Pelt of the Hierophant disenchant into a Small Glowing Shard.
(https://github.com/dalaranwow/dalaran-wow/issues/3595)

![](https://camo.githubusercontent.com/ed7d02a0a09bedd1ae49bc77ddc8de13656d2494/687474703a2f2f692e696d6775722e636f6d2f624c67653368612e6a7067)

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**: aaf9d7d76e17e417bfe792f441938df36884e15a

```sql
-- Pristine Glowbear Pelt
UPDATE `item_template` SET `DisenchantID`=54 WHERE `entry`=51958;
```

**Comment by Aokromes** [comment]
IIRC DisenchantID is WDB field.

**Comment by robinsch** [comment]
I highly doubt that. A ilevel 167 should not be disenchanted to a level 30 item - while all other 167 have disenchantID 54.

**Comment by Aokromes** [comment]
Ok, the WDB field was RequiredDisenchantSkill not DisenchantID

**Comment by tkrokli** [comment]
Minor detail: `item_template.entry` is `mediumint(8)` and does not need text delimiters (apostrophes).
```sql
-- Pristine Glowbear Pelt
UPDATE `item_template` SET `DisenchantID`='54' WHERE (`entry`= 51958);
```

**Comment by MrSmite** [comment]
> Minor detail: item_template.entry is mediumint(8) and does not need text delimiters (apostrophes):

This might indicate it's bad to use qualifiers around numbers:

>http://stackoverflow.com/a/6782065
>
>AFAIK it is standard, but it is considered bad practice because
- using it in a WHERE clause will prevent the optimizer from using indices (explain plan should show that)
- the database has to do additional work to convert the string to a number
- if you're using this for floating-point numbers ('9.4'), you'll run into trouble if client and server use different language settings (9.4 vs 9,4)

Which he seemingly based in part on this:

> http://dev.mysql.com/doc/refman/5.6/en/type-conversion.html
>
> the conversion from string to floating-point and from integer to floating-point do not necessarily occur the same way. The integer may be converted to floating-point by the CPU, whereas the string is converted digit by digit in an operation that involves floating-point multiplications.

The results shown will vary on different systems, and can be affected by factors such as computer architecture or the compiler version or optimization level.
