### ISSUE TITLE
Update Jemalloc

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#17685]
Jemalloc sources should be updated to latest version using the repo with cmake build files https://github.com/jemalloc/jemalloc-cmake so ease the upgrade process

Commit https://github.com/TrinityCore/TrinityCore/commit/cb247ea03313649830abcae962a6f0c1a8801445

**Comment by Naios** [comment]
Yeah I'm already on it but the current jemalloc cmake repo only supports MSVC as of now,
and I guess it will take a long time that anyone volunteers to port the autogen files to cmake,
since it contains a lot of generation logic for several os/architecture combinations.

Also I couldn't get jemalloc to run with dynamic linking...

**Comment by jackpoz** [comment]
could you open a ticket to jemalloc to add nix support to the cmake branch ? I have no clue what to ask in detail.
dynamic linking can keep it disabled.

**Comment by Naios** [comment]
That project is currently too huge for me (I already thought about that but I can't afford that much spare which would be needed to make a notifyable progress on that branch).

**Comment by Naios** [comment]
Maybe we could switch over to another memory allocator which is crossplatform and easier to port... (TcMalloc or similar)

**Comment by jackpoz** [comment]
it seems there's an active issue on jemalloc already to port the cmake branch to other platforms https://github.com/jemalloc/jemalloc/issues/303

**Comment by Naios** [comment]
There is also [rpmalloc](https://github.com/rampantpixels/rpmalloc) which showed superior results over jemalloc in their official benchmarks. If the jemalloc conversion to CMake takes much longer then we could use another allocator.

**Comment by jackpoz** [comment]
or jemalloc could be updated the old way

**Comment by Naios** [comment]
But then it's still unusable on windows

**Comment by jackpoz** [comment]
We use jemalloc only on *nix atm so it would be ok not to support Windows

**Comment by Faq** [comment]
Can any update it the old way? 
Looks like cmake wont be done for long.

**Comment by Naios** [comment]
The real question for me is whether we need to maintain an in source version for unix only when windows is not supported through our version and build system.
As far as I know without doing some research on linux it should be theoretically possible to overwrite the malloc symbol in the process without building jemalloc into the core.
Correct me if I'm wrong.

**Comment by jackpoz** [comment]
Updating jemalloc the old way (I finally figured out which was the old way)

**Comment by Naios** [comment]
I think we can remove jemalloc from the source tree and offer the possibility to preload the library, since most distributions offer their own build of jemalloc.
See https://github.com/jemalloc/jemalloc/wiki/Getting-Started for an example.

> LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` app

**Comment by Faq** [comment]
It is planned to update till 5.0.1 (July 1, 2017) ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/92cd9bd70db460fdce4af0596cf9d8ee3c3abad5

**Comment by jackpoz** [comment]
https://github.com/jemalloc/jemalloc/releases/tag/5.1.0 Jemalloc 5.1.0 was released

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8fe74bf0f90aab0b23d5ff21079cba4201bb4fdf
