### ISSUE TITLE
[Crash]_M_lower_bound 

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17682]
http://paste.ubuntu.com/21385614/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by jackpoz** [comment]
do you have any kind of custom change at all ?

**Comment by sucklifex** [comment]
@jackpoz Transmogrify

**Comment by jackpoz** [comment]
This crash happened when a player logged in with a character already ingame, logging out the ingame character which sends "Player logged out" to friends in friend list.

**Comment by sucklifex** [comment]
@jackpoz Hmmm, i did it a few times by changing characters account, but no crash at all

**Comment by jackpoz** [comment]
I fired up https://github.com/jackpoz/BotFarm with 3 accounts used by 10 bots each (30 bots total), stealing each other sessions and each other added to friend list plus a 4th character always online to monitor how they were logging in/out, still no issue.

**Comment by jackpoz** [comment]
Helgrind log didn't show anything about SocialMgr

**Comment by sucklifex** [comment]
http://paste.ubuntu.com/23388657/

**Comment by Aokromes** [comment]
near 2 years since the last crashlog, if this bug is still valid open a new ticket using updated core.
