### ISSUE TITLE
[Crash] Trinity::Assert

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17683]
http://paste.ubuntu.com/21385668/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by jackpoz** [comment]
>spellId=31726

**Comment by Aokromes** [comment]
near 2 years since the last crashlog with a lot of changes on spell system, if this bug is still valid open a new ticket using updated core.
