### ISSUE TITLE
[335] "buyout" AHBot auction places a bid instead of buying

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#17681]
**Description**:

You can't "buyout" an AHBot auction

**Current behaviour**:

Clicking "buyout" places a bid in the amount of the buyout instead of buying the item. The item is then removed and never delivered (see "Also Note" section below).

**Expected behaviour**:

Clicking "buyout" should buy the item if the player has enough money

**Steps to reproduce the problem**:

1. Create a new character to be the buyer (this allows for empty mail tables)
2. Enable AHBot seller and let it populate the AH
3. Try to buy an item using "buyout"

**Also Note:**

* Once the bid is placed, the item does not show up in your "bids" tab
* If you try to click 'buyout' again you get an error that a higher bid already exists
* If you close and reopen the AH and search in the items tab, the auction does not appear in the results
* The following SQL statements return no results, indicating the auction has been deleted

```SQL
SELECT * FROM `auctionhouse` WHERE `lastbid` > 0
SELECT * FROM `mail` WHERE `receiver` = 5;  -- 5 is the GUID of the buying character
SELECT * FROM `mail_items` WHERE `receiver` = 5;  -- 5 is the GUID of the buying character
```

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/cb247ea03313649830abcae962a6f0c1a8801445

**TDB version**:  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system**:  Win XP and Win 7

Edit: Fix hash to proper 335 branch.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
Cannot reproduce:

[10:16:12] You won an auction for Pattern: Hood of Primal Life
[10:16:12] Bid accepted.
[10:16:29] You have learned how to create a new item: Hood of Primal Life.

**Comment by MrSmite** [comment]
> BTW, your hash is 6.x branch.

Oops, thanks, I'm currently testing this with a fresh pull / build because my code matches but it's possible the EXE was compiled against a patched branch instead of HEAD.

**Comment by MrSmite** [comment]
Well, a fresh pull / compile seems to work fine so my EXE must have been out of date.
