### ISSUE TITLE
[6.x] Hotswap System Crash

### ISSUE THREAD

**Issue by PortgasDAce** [TrinityCore/TrinityCore#17708]
#**Description**:

**Current behaviour**: If you save a script, the hotswap system will recompile it, after the recompile is finished and you change something again on the script and save it, there will be a ASSERT

**Expected behaviour**: I think the new changes in the script should be recompiled without crashing the server

**Steps to reproduce the problem**:

1. Start Worldserver
2. Change something in a script
3. Let the Server recompile the script
4. Change again something in the script
5. Let the Server recompile the script
6. The server will crash

**Branch(es)**: 6.x

**TC hash/commit**:  d26ae654eb1e923dca7b9cfc8ae91de8d8e6ff86

**TDB version**:  

**Operating system**:  Windows Server 2012 R2

Crashlog: https://gist.github.com/PortgasDAce/b3637115a2d7189fc73a91ceb83485cf
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Naios** [comment]
@PortgasDAce did you use the install target?
See https://trinitycore.atlassian.net/wiki/display/tc/Using+the+script+hotswapping+system

**Comment by P-Kito** [comment]
Can be closed. 

Solution: CMAKE_INSTALL_PREFIX was set to visual studio path. The guide advices you to take a new folder outside of build dir.

**Comment by Naios** [comment]
The server shouldn't crash in these kind of situations...
