### ISSUE TITLE
[6.x] Worldserver.exe crash on Loot (Release Build)

### ISSUE THREAD

**Issue by mhubregtse** [TrinityCore/TrinityCore#17701]
When i compile the core as release the worldserver works but when someone loots something in game it crashes.

Error logs give me nothing usefull.

fcc2b2d
Win10 Pro
TDB 6.04 with updates from trinitycore autoupdate

**Comment by Aokromes** [comment]
release modes crashlogs are useless. compile on debug mode.

**Comment by DDuarte** [comment]
The crashlog you posted in the other issue IS the crash on loot.

**Comment by mhubregtse** [comment]
oh sorry this can be closed then..

**Comment by mhubregtse** [comment]
@DDuarte How come the release will run and the debug from vs2015 will not?

**Comment by tkrokli** [comment]
@mhubregtse : update your source to https://github.com/TrinityCore/TrinityCore/commit/53aecd6f09a81984eb444ba9d6552448bd6f256f (commit based on your crash log in https://github.com/TrinityCore/TrinityCore/issues/17700) and test again. It should be fixed now.
