### ISSUE TITLE
[3.3.5] chat filter

### ISSUE THREAD

**Issue by justdothings** [TrinityCore/TrinityCore#17702]
**Description**:Banned words

**Current behaviour**: is there table where i can add words which will be banned like this @!##$@%$#^! 

**Expected behaviour**: cant find table like that

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 3.3.5

**TC hash/commit**:  2967bf59b4a47837b85c995b732a6761c9c35f7e

**TDB version**:  TDB 335.61

**Operating system**:  ubuntu 14.04

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
No. That's a custom feature.
