### ISSUE TITLE
Ebon Gargoyle - Change Target bug

### ISSUE THREAD

**Issue by Swode** [TrinityCore/TrinityCore#17709]
**Description**:

**Current behaviour**: Gargoyle dont change target to attack when I run the macro

**Expected behaviour**: The Gargoyle should be change the target to attack when the ghoul its summoned with the next macro ;
``
/startattack
/petattack
/petfollow``

**Steps to reproduce the problem**:

1. summon ghoul
2. summon gargoyle
3. Run the macro, for example my macro 
#showtooltip Invocar gárgola
/cast Invocar gárgola
/cast [mod:alt, target=focus]Invocar gárgola
/startattack
/petattack

**Running on AT**
https://youtu.be/8DGVhop-Gc8
**Running on TrinityCore**
https://youtu.be/R_wiOiCYIso
**Branch(es)**: 3.3.5 

**TC hash/commit**:  TrinityCore rev. 36306c40d37c 2016-07-25 18:37:30 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version**:  335.61

**Operating system**:  Win 10

**Comment by Swode** [comment]
Help pls

**Comment by Keader** [comment]
Dup? https://github.com/TrinityCore/TrinityCore/issues/16464
https://github.com/TrinityCore/TrinityCore/issues/1909

**Comment by Swode** [comment]
Read

**Comment by Keader** [comment]
same problem to me, gargoyle target/attack.
btw, has hack fix for it here: https://github.com/TrinityCore/TrinityCore/issues/16181#issuecomment-200407265 but it's not blizzlike .

**Comment by Swode** [comment]
The problem is When I run the macro don't change the target

**Comment by Swode** [comment]
Can u teach how to add a diff to my compile?

**Comment by Swode** [comment]
Ok with https://github.com/TrinityCore/TrinityCore/issues/16181#issuecomment-200407265

Working the target

All ok :D

**Comment by ariel-** [comment]
Do not close issue as this is not fixed in repo.

**Comment by ariel-** [comment]
#1909
