### ISSUE TITLE
[3.3.5] Wintergrasp / Sota and more Object rotated wrong 

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17711]
Wintergrasp / Sota and more Object rotated wrong  from this commits
https://github.com/TrinityCore/TrinityCore/commit/62bfee37cb21584cef631dda428feaf5eb829cda
https://github.com/TrinityCore/TrinityCore/commit/2967bf59b4a47837b85c995b732a6761c9c35f7e

check screen shot
http://uploads.im/4elRI.jpg
Fot BG SOTA is occured too

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/cf8276845d9a26542fb18ca2e56b4957b61e4c73

**Operating system**:  ubuntu

**Comment by shenhuyong** [comment]
Confirmed

**Comment by tkrokli** [comment]
@shenhuyong : Please add TC hash/commit from your own core when posting "Confirmed".

**Comment by shenhuyong** [comment]
@tkrokli  commits 2967bf59b4a47837b85c995b732a6761c9c35f7e
After you run 2016_07_30_01_world.sql, you will see this problom.

**Comment by Killyana** [comment]
This happen because this gobs are not spawn on the DB but by scripts, so the script must be updated to use the new orientations.

**Comment by ariel-** [comment]
Interesting, Battlefield does not allow rotation to be passed but BattleGround does; however in sota case all rotations are 0; quick fix incoming

**Comment by SQLfix** [comment]
i use  https://github.com/TrinityCore/TrinityCore/commit/33fbc453d236d943c24fb10522ac0720c3174c3d
commit  https://github.com/TrinityCore/TrinityCore/commit/e7cfb08cb5dce8c99d2e4f70d287a76deba70a98

Not fixed [ just more rotated ]
ScreenShots
http://uploads.im/?g=0LpoJ.jpg

**Comment by ariel-** [comment]
Patience, I'm respawning all Battlegrounds, current spawns are wrong, this errors were from before, however they are now evident with GO rotation system in place.

**Comment by SQLfix** [comment]
@ariel for your Attention i Re Compile Core (multi time)+ Check
no problem find and All object is OK
tnx for your Attention 
http://uploads.im/?g=4qVgl.jpg
