### ISSUE TITLE
[6.x] Who list not working (opcode disabled)

### ISSUE THREAD

**Issue by mhubregtse** [TrinityCore/TrinityCore#17712]
When someone clicks on Refresh in the Who list nothing happens.

Worldserver.exe Console shows:
Prevented sending disabled opcode [SMSG_WHO 0x2BAE (11182)] to [Player: Mike GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 2]

53aecd6
windows 10
tdb 6.04 with updates from trinitycore autoupdate

**Comment by DDuarte** [comment]
All the STATUS_UNHANDLED in https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp are "disabled".

**Comment by mhubregtse** [comment]
Thanks @DDuarte didnt know about this, thanks for letting me know.

Is there any way that i can get these working?

**Comment by tkrokli** [comment]
If you know all the correct values for the opcode, you can try to enable them. Compare with older opcodes enabled by the TC developers, like in
- https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.cpp
- https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Protocol/Opcodes.h

and a couple of other files. (I don't know how to do it myself.) You need to know that content and how it interacts with other files to be able to fix it properly. You can of course play around in your own source and see how changes in the C++ code works if you try to enable that opcode.
