### ISSUE TITLE
[3.3.5] - Ulduar - Thorim

### ISSUE THREAD

**Issue by Swode** [TrinityCore/TrinityCore#17718]
**Description**:I can't activate the door and the boss.

**Current behaviour**: I can't click the lever.

**Expected behaviour**: The lever should be killed and start the boss encounter.

**Steps to reproduce the problem**:

1. Go to Ulduar
2. Go to Thorim
3. Try to activate Thorim

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. 36306c40d37c 2016-07-25 18:37:30 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version**:  335.61

**Operating system**:  Win 10

**Links :+1:** 
BOSS - http://www.wowhead.com/npc=32865/thorim

**Video of the issue:**
https://www.youtube.com/watch?v=GwF6j1kQ93g

Help pls :dancers:

**Comment by Aokromes** [comment]
search before reporting any new bug.

**Comment by Keader** [comment]
And try: #15008

**Comment by Swode** [comment]
@Aokromes 
Follow me in twitter pls
