### ISSUE TITLE
[3.3.5] - ToC - The super Snobold Vassal on Gormok the Impaler

### ISSUE THREAD

**Issue by Swode** [TrinityCore/TrinityCore#17716]
**Description**:Snobold Vassal BUG

**Current behaviour**: I can't attack the Snobold Vassal's.

**Expected behaviour**: The Snobold Vassal should be killed.

**Steps to reproduce the problem**:

1. Go to ToC
2. Activate the first boss
3. Try to kill Snobold Vassal

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. 36306c40d37c 2016-07-25 18:37:30 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version**:  335.61

**Operating system**:  Win 10

**Links :+1:** 
BOSS - http://www.wowhead.com/npc=34796/gormok-the-impaler
BUG NPC -http://www.wowhead.com/npc=34800/snobold-vassal

**Video of the issue:**
https://youtu.be/1d873dSEQpU

Help pls :dancers:

**Comment by Krudor** [comment]
https://github.com/TrinityCore/TrinityCore/blob/f4029faecee41ef9843362f993292a1576c19626/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp#L319

This code is wrong, Snobold Vassal's do not have any damage taken restrictions on live.
Not to mention that they don't seem to work as intended at all.

**Comment by Aokromes** [comment]
#17158

**Comment by Keader** [comment]
Look: #16895
