### ISSUE TITLE
Razorscale - Can't attack

### ISSUE THREAD

**Issue by Swode** [TrinityCore/TrinityCore#17714]
**Description**: The harpoons don't work.

**Current behaviour**: I can't activate harpoons.

**Expected behaviour**: The harpoons should be clicked.

**Steps to reproduce the problem**:

1. Go Ulduar
2. Go to Razorscale
3. Activate boss 

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. 36306c40d37c 2016-07-25 18:37:30 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version**:  335.61

**Operating system**:  Win 10

Links :+1: 
http://www.wowhead.com/npc=33186/razorscale

Video of the issue:
https://youtu.be/u_kZ9S4NUiI

Help pls :dancers:

**Comment by Aokromes** [comment]
#13056
