### ISSUE TITLE
[3.3.5] Crash Object::GetGuidValue & group invited

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17717]
Crash Object::GetGuidValue & group invited
Unknow Crash and Dont know how can crash Server

Logs:
http://pastebin.com/eme0BsDj
http://pastebin.com/rZAVh3w1

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/4baa7f443a26df36ced18f96f28c64f1920514eb

**Operating system**:  ubuntu

**Comment by jackpoz** [comment]
could you post your "/root/0000/src/server/game/Handlers/GroupHandler.cpp" file ?

**Comment by SQLfix** [comment]
this is my crashed Grouphandler.cpp file with commit https://github.com/TrinityCore/TrinityCore/commit/4baa7f443a26df36ced18f96f28c64f1920514eb

https://ufile.io/a0338

**Comment by Aokromes** [comment]
Update your core before reporting crashes, 1 crash was fixed yesterday.

**Comment by SQLfix** [comment]
i updated to https://github.com/TrinityCore/TrinityCore/commit/ad74638cd661f2373f48513a548f6504e869476a but not used it .i need rebuild on my Online server /
i every day update my Core / every day

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
no answer after 12d, closing, if this bug is still valid open a new ticket on one updated core.
