### ISSUE TITLE
Crash after new compile 3.3.5

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17724]
**Description**:
I compile the latest release and the WorldServer crashed by start.

http://www.heypasteit.com/clip/2TVW
**Branch(es)**: 3.3.5 
**TC hash/commit**:  
TrinityCore rev. e7cfb08cb5dc 2016-08-02 20:41:53 +0100 (335 branch)

**TDB version**:  

**Operating system**:  
Win7 64bit

**Comment by Aokromes** [comment]
Useless crashlog.

**Comment by DDuarte** [comment]
Aokromes means that you need to compile in Debug mode and post the crashlog.

**Comment by Tauriella** [comment]
Done
