### ISSUE TITLE
[CRASH] npc_eye_of_acherus

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#17729]
**Description**:
Crashlog http://pastebin.com/yk0MiW3E

**Steps to reproduce the problem**:
1. Create a DK Worgen.
2. Pick quest 12641 "Death Comes From On High"
3. Right clic on Eye of Acherus and server crashes.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:  
02a9ae031e71a9d075a59b25240b7e9aee6a31bb
**Operating system**:  
Ubuntu 16.04

**Comment by Aokromes** [comment]
Compile on debug mode plz.

**Comment by Pirricli** [comment]
I did

**Comment by tkrokli** [comment]
Just check `.server info` to see if you have got Debug or Release.

**Comment by Pirricli** [comment]
Debug mode is not compiled in the same way that in 3.3.5 branch?

**Comment by mhubregtse** [comment]
The crash is in 6.x too. im now compiling in debug and run on my server.

**Comment by mhubregtse** [comment]
I can confirm this one on 6.x win10 64

**Comment by funjoker** [comment]
No Backtrace = no fix.

**Comment by mhubregtse** [comment]
@funjoker What is a backtrace?

**Comment by funjoker** [comment]
compile in debug mode.
then cause crash
get log
post log

**Comment by mhubregtse** [comment]
Revision: TrinityCore rev. 9bc28632b3fb 2016-08-03 08:18:42 +0200 (6.x branch) (Win64, Debug, Dynamic)
Date 4:8:2016. Time 16:36 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Number Of Processors: 8
Physical Memory: 16724604 KB (Available: 6636880 KB)
Commit Charge Limit: 20544660 KB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 10586)


CRASHLOG
https://drive.google.com/open?id=0B3HW2Z0MMhLVNTlaM01RY045V28

**Comment by Nawuko** [comment]
https://gist.github.com/Nawuko/3f92b67e3dde0d75e0a17371e6996a5c

**Comment by mhubregtse** [comment]
Will this be implemented soon?

**Comment by mhubregtse** [comment]
Where is the possible fix? that one worked!

**Comment by Nawuko** [comment]
I removed it cause it was ugly.

**Comment by Aokromes** [comment]
acording #18362 it looks it don't crashes anymore.
