### ISSUE TITLE
[Crash] Aura::UnregisterSingleTarget

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17720]
http://paste.ubuntu.com/21922302e01/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by Aokromes** [comment]
The Paste you are looking for does not currently exist.

**Comment by sucklifex** [comment]
@jackpoz Issue updated

**Comment by sucklifex** [comment]
@aokromes Issue updated

**Comment by tkrokli** [comment]
Continued in #17722 (has backtrace).
