### ISSUE TITLE
Server crash after new complie 3.3.5 (reopening issue)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17725]
I reopening this issue with Debug Mode

Description:
 I compile the latest release and the WorldServer crashed by start.

http://www.heypasteit.com/clip/2TVY
Branch(es): 3.3.5 
TC hash/commit:

 TrinityCore rev.  e7cfb08  2016-08-02 20:41:53 +0100 (335 branch)

TDB version: 

Operating system:

 Win7 64bit

**Comment by DDuarte** [comment]
*Temporarly* you can revert 5e9f5123141e5387365da6b0214a69b0bd2cf74e

**Comment by Tauriella** [comment]
Thank you for the fastest Info :+1:

**Comment by Shauren** [comment]
Please try this fix https://gist.github.com/Shauren/340bfb34cb9448b4af4c06981c511353 (without reverting 5e9f512)

**Comment by tkrokli** [comment]
TrinityCore rev. e7cfb08cb5dc 2016-08-02 20:41:53 +0100 (3.3.5 branch) (Win64, Release, Static)
TrinityCore rev. e7cfb08cb5dc 2016-08-02 20:41:53 +0100 (3.3.5 branch) (Win64, Debug, Static)

If all that is needed is to start up Worldserver + Authserver and log in to the game, I cannot reproduce it.
Tested on binaries (2x2 sets) from both available compilers :
- Visual Studio 2013 Update 5 (12.040629.00)
- Visual Studio 2015 Update 3 (14.0.25424.00)

Windows 10 x64 Version 1511 (OS Build 10586.494)

**Comment by Tauriella** [comment]
@Shauren 
BIG THANKS YOUR FIX WORKS FINE :+1:
