### ISSUE TITLE
[7.x] .gps Command Returns Incorrect Zone and AreaId

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/TrinityCore#17723]
**Description**:
Since 7.x switch, Map::GetZoneAndAreaId returns invalid area / zone ids for Legion zones (didn't test if it also affects previous expansions zones aswell).

It can be easily confirmed by using .gps command in a Legion zone.

Note: I've extracted maps / vmaps / mmaps from a 22293 client.

**Current behaviour**:
When you type .gps command in a Legion zone, it will display improper area / zone ids. (ie: 8445 for Legion version of Dalaran)

It also affects zone displayed on character selection screen since it also relies on Map::GetZoneAndAreaId.

**Expected behaviour**:
You should see the right area / zone ids when using .gps command or when you're on character selection screen.

**Steps to reproduce the problem**:

1. Go to Legion version of Dalaran (.go xyz -828.72 4371.78 738.64 1220 1.889843)
2. Use .gps command
3. You'll see "Zone: 8445 (The Great Sea) Area: 8445 (The Great Sea)" instead of Zone: 7502 (Dalaran)

**Branch(es)**: 6.x 

**TC hash/commit**: 6c78e7bcaa3cb3201e6dc22717254d97e87438a3

**TDB version**: TDB 6.04

**Operating system**: Win10 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
You have vmaps disabled no?

**Comment by OrzelBialy** [comment]
VMaps are enabled

**Comment by DDuarte** [comment]
Issue confirmed

**Comment by OrzelBialy** [comment]
Apparently yeah it's mainly affecting Dalaran, but it's the same for Acherus: The Ebon Hold (WoTLK version), try to .go xyz 2359.64 -5662.41 382.28 0 0.596899, same issue. Apparently z isn't taken into account?

**Comment by Aokromes** [comment]
humm on 3.3.5a works:

[23:10:15] You are outdoors.
[23:10:15] Map: 0 (Eastern Kingdoms) Zone: 139 (Eastern Plaguelands) Area: 4281 (Acherus: The Ebon Hold) Phase: 4294967295
[23:10:15] X: 2359.639893 Y: -5662.410156 Z: 382.260925 Orientation: 0.596899
[23:10:15] grid[36,21]cell[3,3] InstanceID: 0
[23:10:15]  ZoneX: 83.718704 ZoneY: 50.028896
[23:10:15] GroundZ: 153.922409 FloorZ: 382.260773 Have height data (Map: 1 VMap: 1 MMap: 1)

**Comment by Valhalla-Gaming** [comment]
I mean on 7.x, the non-Class Hall version (the version created in WotLK). Not in the 335a core

**Comment by Valhalla-Gaming** [comment]
I think he means on 7.x, the non-Class Hall version (the version created in WotLK). Not the one in the 335a core.

**Comment by Aokromes** [comment]
he said on " .go xyz 2359.64 -5662.41 382.28 0 0.596899" and from that place is the .gps

**Comment by Valhalla-Gaming** [comment]
Right. So that would be Ebon Hold in the Eastern Kingdoms; and not Ebon Hold the Class Order Hall. Namely, enter " .go xyz 2359.64 -5662.41 382.28 0 0.596899" in 7.x and then type .gps to reproduce the update to his issue.

**Comment by OrzelBialy** [comment]
sorry for the confusion, I'm still talking about 7.x branch

**Comment by Aokromes** [comment]
I known you are talking about 7.x branch, i mean the same location on 3.3.5a  works properly.

**Comment by OrzelBialy** [comment]
update: If you do ```.go xyz -935.17 4706.4 928.62 1513 6.1467``` and type ```.gps``` both areaId and zoneId will return 0
