### ISSUE TITLE
[Crash] Aura::UnregisterSingleTarget

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17722]
http://paste.ubuntu.com/21924766/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by jackpoz** [comment]
I see custom code there 
>#10 0x0000000000e1261b in ST_Commands::STHomeCommand (handler=<optimized out>) at /home/2/src/server/scripts/Custom/STScript.cpp:229

**Comment by sucklifex** [comment]
@jackpoz Just a few simple lines, http://paste.ubuntu.com/21935562/

**Comment by Aokromes** [comment]
near 2 years since the last crashlog, if this bug is still valid open a new ticket using updated core.
