### ISSUE TITLE
[Ulduar] Harpoons - Before#15008

### ISSUE THREAD

**Issue by Swode** [TrinityCore/TrinityCore#17730]
**Description**: The harpoons don't point to the boss.

**Current behaviour**: The harpoons appear pointing to the other side.

**Expected behaviour**: The harpoons should be appear pointing to the boss.

**Steps to reproduce the problem**:
1. Apply #15008 
2. Go Ulduar
3. Go to Razorscale
4. Activate boss 

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. ad74638cd661 2016-08-01 19:56:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version**:  335.61

**Operating system**:  Win 10

Links :+1: 
http://www.wowhead.com/npc=33186/razorscale

Image of the issue:
http://imgur.com/a/h2BYd

Help pls :dancers:

**Comment by Aokromes** [comment]
i closed you the same issue as this few days ago because it's duplicated.

**Comment by Swode** [comment]
@Aokromes Read pls. 
It's not the same on this case the harpoons appear with other orientation.
