### ISSUE TITLE
[3.3.5] Crash creature

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17734]
New crash with unknow Log
http://pastebin.com/dKcdtVYH
http://pastebin.com/fHzCtn6M

**Branch(es)**: 3.3.5 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/5427dd4ce64ae7ee29b4e7e1678181b9e292767f

**Operating system**:  ubuntu

**Comment by jackpoz** [comment]
There's no much useful to work on in these crashlogs

**Comment by SQLfix** [comment]
Again : http://pastebin.com/g0Mx0Evq

**Comment by tkrokli** [comment]
@SQLfix : ref. the following 2 lines in your logs:
```
#4  0x00000000016ab673 in Creature::~Creature (this=this@entry=0x7fffa16b9000, __in_chrg=<optimized out>) at /root/0000/src/server/game/Entities/Creature/Creature.cpp:204
#5  0x00000000016ab715 in Creature::~Creature (this=0x7fffa16b9000, __in_chrg=<optimized out>) at /root/0000/src/server/game/Entities/Creature/Creature.cpp:211
```
Enable the worldserver.conf log `entities.unit` like this:
```
Line 3654: remove the # to enable the log, reduce 3 to 2 (debug) or 1 (trace)

#Logger.entities.unit=3,Console Server
```
Not sure how to track `Unit.cpp:286` - referenced 6 times (like `Creature.cpp:204`+`Creature.cpp:211`)

I must admit that I am skeptical about the log referencing `/usr/include/c++/4.9/bits/` in the first 3 lines, but someone with more Linux experience than me could comment on that.

**Comment by SQLfix** [comment]
@tkrokli  i use #Logger.entities.unit=3,Console Server and my Server log +100G per 10hours and cannot check it
Every day crash
http://pastebin.com/9WKpxygp

**Comment by jackpoz** [comment]
@tkrokli how does that log help tracking down the crash ?

**Comment by tkrokli** [comment]
Sorry, my mistake. I forgot that there is too much happening regarding units/creatures.
Please ignore that I suggested it. (If you want, you can even remove that comment post.)

**Comment by tkrokli** [comment]
No updates in this issue in 11 months and no other users confirming this crash since this crash was posted. If the exact same crash happens again, please open a new crash ticket with updated and current source revision in your server.
