### ISSUE TITLE
[3.3.5] SpellSteal and Sacred Shield

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#17739]
**Description**: SpellSteal doesn't work like it should when stealing Sacred Shield from an enemy paladin.

**Current behaviour**: After casting SpellSteal and steal Sacred Shield, the Sacred Shield that mage gets doesn't proc its effect.

**Expected behaviour**: Stealing Sacred Shield with SpellSteal should proc the effect that Sacred Shield gives on the mage.

**Steps to reproduce the problem**:

1. Using a paladin, cast Sacred Shield
2. Using a mage, cast SpellSteal to steal that Sacred Shield
3. Attack the mage and see how stolen Sacred Shield doesn't proc the absorb effect to the mage

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/152b3ad5b997f4be06c5bb55ddb15c57a8e28c3b

**Comment by Treeston** [comment]
[Relevant section](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L6474-L6490)

Should likely be moved to spellscript.
