### ISSUE TITLE
Mac OS X build fail

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#17740]
**Description**:
Build fail when compiling
**Current behaviour**: Tell us what happens
See Description
![schermata 2016-08-05 alle 15 30 54](https://cloud.githubusercontent.com/assets/16773213/17438273/3a6327c6-5b22-11e6-95d8-89302da5de32.png)

**Expected behaviour**: Tell us what should happen instead
Source completely compile
**Steps to reproduce the problem**:

1. Clone repository
2. Use CMAKE
3. BUILD

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/8950ec43eb185cbcdebddc2b2fafd79c7d641202
**TDB version**:  
6.04
**Operating system**:  
OS X Yosemite 10.10.5

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by LuigiElleBalotta** [comment]
@Shauren 1 month ago i could compile fine..

**Comment by obsidean** [comment]
Here is how I do it and it works fine.  

1) Getting sources
git clone https://github.com/TrinityCore/TrinityCore.git

2) Move to the folder where you want to place the TrinityCore sources, then type:
cd TrinityCore
git checkout 3.3.5
mkdir build
cd build
 
3) Generate the XCode project files
IMPORTANT: replace /Users/username/tc-server of the following command with the path where you want to install the TrinityCore server.
then type:
cmake ../ -GXcode \
-DMYSQL_ADD_INCLUDE_PATH=/usr/local/include \
-DMYSQL_LIBRARY=/usr/local/lib/libmysqlclient_r.dylib \
-DREADLINE_INCLUDE_DIR=/usr/local/opt/readline/include \
-DREADLINE_LIBRARY=/usr/local/opt/readline/lib/libreadline.dylib \
-DBOOST_INCLUDEDIR=/usr/local/include \
-DBOOST_LIBRARYDIR=/usr/local/lib \
-DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include \
-DOPENSSL_SSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib \
-DOPENSSL_CRYPTO_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib \
-DZMQ_LIBRARY=/usr/local/opt/zeromq/lib/libzmq.dylib \
-DZMQ_INCLUDE_DIR=/usr/local/opt/zeromq/include \
-DZLIB_ROOT=/usr/local/Cellar/zlib/1.2.8 \
-DCMAKE_INSTALL_PREFIX=/Users/obsidean12/trinity \
-DTOOLS=0 \
-DWITH_WARNINGS=0
 
4) Building the binaries
Type the following to build the binaries:
xcodebuild -target install -config Release

**Comment by LuigiElleBalotta** [comment]
you did it with 3.3.5 or 6.x?

**Comment by tkrokli** [comment]
@LuigiElleBalotta : From obsidean's post: `git checkout 3.3.5`

**Comment by Smokexyz** [comment]
Same error on rev bba7b6a554c3be59edc2a9b520e5ba132b0efc52 OSX 10.11.6.
compiled with the same options, target and config.

**Comment by Gacko** [comment]
Build works fine for me using...
```
$ cmake --version
cmake version 3.6.2
```
```
$ make --version
GNU Make 3.81
```
```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
```
... and:

- Boost 1.61.0
- OpenSSL 1.0.2i
- GNU Readline 6.3
- MySQL 5.7.15

... for both 6.x and 3.3.5.

Could you please mention your used tools and OS X / macOS version?

**Comment by Smokexyz** [comment]
@Gacko using brew with same versions described above.

The issue was -DOPENSSL_SSL_LIBRARIES
Where my configuration had -DOPENSSL_LIBRARIES.
Oddly, 3.3.5 didn't complain about it.

thanks for clarifying 👍

**Comment by Gacko** [comment]
[FindOpenSSL.cmake](https://github.com/TrinityCore/TrinityCore/blob/6.x/cmake/macros/FindOpenSSL.cmake) says you can only set OPENSSL_ROOT_DIR. But doing so resolves the following paths:
```
-- Found OpenSSL library: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib
-- Found OpenSSL headers: /Users/marco/Trinity/include
```
So I had to define the final variables on my own.
