### ISSUE TITLE
[Crash] on server restart or shutdown

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17742]
**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

http://paste.ubuntu.com/22326079/
http://paste.ubuntu.com/22326081/

**Comment by SQLfix** [comment]
Confirm https://github.com/TrinityCore/TrinityCore/commit/6bb6bc7f1d362a61314cfd763de67954ca1462b3

i have this crash too ..just when server restart Or shutdown occured
http://pastebin.com/DPdwQwVG

**Comment by sirikfoll** [comment]
I have been told that this `"It stopped with signal SIGABRT, Aborted."` isn't a crash, it means the program was stopped(by shutdown or restart) 
This `"Program received signal SIGSEGV, Segmentation fault."` is a crash

**Comment by jackpoz** [comment]
Looks like an unhandled exception in boost::shared_lock<boost::shared_mutex>::lock

**Comment by Aokromes** [comment]
Self remind: this bug is still valid.

**Comment by Aokromes** [comment]
i don't have seen this for long time.
