### ISSUE TITLE
Debian 8.x Compile With clang 3.5

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/TrinityCore#17760]
**Description**: The clang compile seems to be broken on Debian 8.4.0, gcc is working. The issue seems to be related to this commit https://github.com/TrinityCore/TrinityCore/commit/9bc28632b3fb59932d6d4ef124278915c5fa7c4f

**Current behaviour**: clang fails to compile the source with the following error in regex_compiler.h
https://gist.github.com/OrzelBialy/f9a1416fc63b4720427f9ce25c09d796

**Expected behaviour**: The source should compile

**Steps to reproduce the problem**:
1. Get on Debian 8.4.0
2. Install clang
3. Attempt to compile TrinityCore

**Branch(es)**: 6.x

**TC hash/commit**:  bd3541d106bbdb50ad53e38e6c7f2bc78dd6c1dc

**TDB version**:  6.04

**Operating system**:  Debian 8.4.0

**Comment by Aokromes** [comment]
It's gcc bug, as workaround you must revert that commit.

**Comment by jackpoz** [comment]
report this issue to Debian, they need to fix their clang package backporting a fix from a more recent version

**Comment by OrzelBialy** [comment]
Issue resolved with https://github.com/TrinityCore/TrinityCore/commit/b6f1f8405f57e3b65c3b838ea87141716023bc72
