### ISSUE TITLE
[Crash] CreatureAI

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17766]
http://paste.ubuntu.com/23036392/

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by sirikfoll** [comment]
I've had this crash too, but only have a partial log, nothing useful..
https://gist.github.com/sirikfoll/22a2d7898ebd3266c5286f6b414c7f28
Rev. https://github.com/TrinityCore/TrinityCore/commit/d82534a7bbd401f4b672786749f10f5a95f6e76c

**Comment by jackpoz** [comment]
it seems this crash happened in an instance but there are no useful locals to know in which instance it happened.

**Comment by Aokromes** [comment]
near 2 years since the last crashlog, if this bug is still valid open a new ticket using updated core.
