### ISSUE TITLE
Cosmeticbug for Quest 12050

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17762]
You can ever harvest the same tree, on Blizzard can you only one harvest the same tree or you wait 5mins for the respawn.

http://www.wowhead.com/quest=12050/lumber-hack
https://www.youtube.com/watch?v=560jXaL3QXA

**Branch(es)**: 3.3.5 / 6.x
**TC hash/commit**:  
TC>TrinityCore rev. 5588881be21f 2016-08-08 18:07:19 +0200 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates
**Operating system**:  
Win7 64Bit

**Comment by Killyana** [comment]
I don't know why the event gossip hello doesn't work in this case:
``` sql
SET @obj     := 188539;
UPDATE `gameobject_template` SET `AIName`='SmartGameObjectAI' WHERE `entry` IN (@obj);
DELETE FROM `smart_scripts` WHERE `source_type`=1 AND `entryorguid` IN (@obj);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@obj,1,0,0,64,0,100,0,0,0,0,0,99,3,0,0,0,0,0,1,0,0,0,0,0,0,0, 'Coldwind Tree - on gossip hello - SET_LOOT_STATE 3');
