### ISSUE TITLE
Warlock "Create Heathstone" doesn't work 

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#17772]
**Description**:  Casting Create Healthstone doesn't give you a healthstone.

**Current behaviour**: Casting Create Healthstone shows the casting bar... but when it finishes... doesn't place a healthstone in your inventory.

**Expected behaviour**: After casting the Create Healthstone spell... it places a healthstone in your inventory.

**Steps to reproduce the problem**:  Cast Create Healthstone on a warlock class.  I have only done this on a gnome warlock.

**Branch(es)**: 6.x

**TC hash/commit**:  ea1624187363

**TDB version**:  TDB 6.04

**Operating system**:  

Server OS:  Ubuntu 16.04.1 LTS
Client OS: Windows 10
Client Version:  7.0.3.22345

**Comment by dipdill** [comment]
here is the wowed.com link to the spell... sorry forgot to include it

http://www.wowhead.com/spell=6201/create-healthstone

**Comment by Killyana** [comment]
cannot reproduce on rev. 084da48ba15a
