### ISSUE TITLE
Warlock Spell - Drain Soul doesn't award a soul shard

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#17773]
**Description**:  Warlock Spell - Drain Soul doesn't award a soul shard

**Current behaviour**:  Doesn't award a soul shard when target dies from the cast.  Without the Soul Shard you can not cast unstable affliction (http://www.wowhead.com/spell=30108/unstable-affliction) or summon pets... Imp (http://www.wowhead.com/spell=688/summon-imp), Voidwalker (http://www.wowhead.com/spell=697/summon-voidwalker).  I haven't checked the rest of the summons.

**Expected behaviour**: Generates 1 Soul Shard if the target dies during this effect.

**Steps to reproduce the problem**:

Cast drain soul on a target that will die from the affect.

wowhead.com link:  http://www.wowhead.com/spell=198590/drain-soul

**Branch(es)**: 6.x

**TC hash/commit**:  ea1624187363

**TDB version**:  TDB 6.04

**Operating system**:  

Server OS: Ubuntu 16.04.1 LTS
Client OS: Windows 10
Client Version: 7.0.3.22345

**Comment by Exodius** [comment]
Dunno if helpful. Found it here: https://github.com/Ragebones/StormCore/commit/309887b3092e5f66903185633aea3b9e7d352e6f

```mysql
DELETE FROM `spell_script_names` WHERE `spell_id`=198590;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (198590, 'spell_warl_drain_soul');
```

```diff
// 198590 - Drain Soul
/// Updated 7.1.5
class spell_warl_drain_soul : public SpellScriptLoader
{
    public:
        spell_warl_drain_soul() : SpellScriptLoader("spell_warl_drain_soul") { }

        class spell_warl_drain_soul_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_warl_drain_soul_AuraScript);

            void OnPeriodic(AuraEffect const* aurEff)
            {
                if (Unit* caster = GetCaster())
                {
                    int32 damage = aurEff->GetDamage();
                    if (Aura* drainSoul = GetTarget()->GetAura(GetId()))
                        drainSoul->GetEffect(EFFECT_0)->ChangeAmount(damage);
                    damage *= 2;
                }
            }

            void Register() override
            {
                OnEffectPeriodic += AuraEffectPeriodicFn(spell_warl_drain_soul_AuraScript::OnPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_LEECH);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_warl_drain_soul_AuraScript();
        }
};

**Comment by tkrokli** [comment]
First of all, delete by `ScriptName`, not by `spell_id` alone. Secondly, we need someone with spell script experience to validate/verify the content.
