### ISSUE TITLE
Profession Trainers Don't Work

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#17785]
**Description**:  Profession trainers Don't Work

**Current behaviour**: When you talk to a profession trainer.... the dialog box never appears

**Expected behaviour**: Talk to the trainer and a dialog window should appear to give you the option to learn that profession.  I have only confirmed this with a few mining and blacksmith trainers.  I am able to grant the profession via the gm commands... but then it won't let you level it up.  will tell you that you don't have the required skill.

**Steps to reproduce the problem**:

1. Try to talk to a profession trainer.

**Branch(es)**: 6.x

**TC hash/commit**:  e6ddb9f2220b

**TDB version**:  TDB 6.04

**Operating system**: 

Server OS: Ubuntu 16.04.1 LTS
Client OS: Windows 10
Client Version: 7.0.3.22345

**Comment by Aokromes** [comment]
#14682

**Comment by dipdill** [comment]
Sorry wrong client version  7.0.3.22423
