### ISSUE TITLE
[3.3.5] Quest Item in Combat not destroyed

### ISSUE THREAD

**Issue by SQLfix** [TrinityCore/TrinityCore#17806]
[3.3.5] Quest Item in Combat not destroyed
All Need Quest items (Equipted) cannot destroyed when is in combat !.

Examle :  [Ashen Band] Fingers in ICC Quest 
1-give first Ashen Band OR any Rank OF this fingers
2-equip finger
3-Go and Attack Npc .. Combat
4-Go near Npc "Aronen" ICC and change your finger
5-Your old [equip] Finger Not Removed and new finger added

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/2585c62e6fc8925bb74160fb9b24fb1d361a8b2c

**Operating system**:  ubuntu

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by dr-j** [comment]
Maybe related to the fact that you cannot change/unequip anything other than Weapon while in combat but thats meant to be the case but could be the reason.

**Comment by Nawuko** [comment]
@dr-j Yep thats the reason. The question is what is the retail behavior:
- Ignore the restriction and destroy the Item even during combat.
- Dont allow to complete the quest if in combat

If someone knows what is the expected behavior i can open a PR.

**Comment by Shauren** [comment]
Ignore the restriction.

**Comment by Nawuko** [comment]
Yea i can find a valid SMSG_QUESTGIVER_QUEST_FAILED reason that shows that this is not possible in combat

**Comment by Nawuko** [comment]
This is broken due to a change in https://github.com/TrinityCore/TrinityCore/commit/da204ad78c0a960da9fe3ea009ac91f8f39b6af2
The last argumment for `DestroyItemCount` in `Player::RewardQuest` is changed to True (was undefined befor and defaulted to False) which enforces the combat check. @runningnak3d
