### ISSUE TITLE
Greeting questgiver-GOs

### ISSUE THREAD

**Issue by Gerhood** [TrinityCore/TrinityCore#17803]
**Current behaviour**: Many questgiver- (type2) GOs still greet the player with a default text when he is not on (or eligible for) a quest with that GO and the GO has no default text

**Expected behaviour**: The player should not be able to interact with that object

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  7f5756804edeb50cea1debe994ebed84e315f5cc

The issue could be fixed by adding the (missing) GO_FLAG_INTERACT_COND flag to these objects:

`UPDATE gameobject_template SET flags = flags | 4 WHERE type = 2 AND Data3 = 0`

**Comment by joschiwald** [comment]
did you checked sniffs?

**Comment by Gerhood** [comment]
nope

**Comment by dr-j** [comment]
If these are quest giver gos then adding flags is probably wrong as this wont make the object non selectable which will result in player not been able to take quests from such objects.

Think better solution would be to make quest starter object non selectable if there are no quests available to player from it or should only be selectable if there is at least one available quest.

**Comment by Gerhood** [comment]
Thats exaclty what GO_FLAG_INTERACT_COND does. If a player has quests for the object GO_DYNFLAG_LO_ACTIVATE wich enables interaction for GOs with that flag

**Comment by dr-j** [comment]
Oh I had a different impresstion of that was for objects which were objective of quest not starter/ender items.

**Comment by MrSmite** [comment]
Good place to test this is a the [Strange Fruited Plant](http://www.wowhead.com/object=6751/strange-fruited-plant) in Teldrassil. It has low level mobs around it (8 to 10)  and the quest is available around level 5 so it's easy to get to.
