### ISSUE TITLE
[3.3.5] Incorrect range calculation for melee spells if both players are moving

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#17818]
**Description**: Okay so this is hard to explain in text, and you will understand better with the screenshots I'll post however I will try to explain. If you and your enemy are moving, your melee spells should get extra range for melee spells. Actually, this is working but not as 100% as it should work.

**Current behaviour**: You can't cast melee range spells at a certain distance if both players are moving. The server says you can't (with an Out of range message) but the client says you actually can (by making the spell not red in the action bar).

**Expected behaviour**: Client and server should say the same in melee range spells when both players are moving

**Steps to reproduce the problem**:

1. Make an enemy move (the test is easier if the enemy is moving but in front of a wall so he isn't moving, you can see it in my first screenshot).
2. Move to that enemy until you are just in range to not be able to autoattack him because you are "Too far away".
3. Try to cast a melee spell, in my case with a DK, Scourge Strike.
4. It says "Out of range", thats ok because you are not moving so you are not getting extra range
5. Now move with E and Q nonstop while using Scourge Strike, now you should see how it gets extra range and you can hit him with it. Thats also ok (see screenshot 2).
6. Now for the real bug. Get a bit more away from the enemy and try to do the same as in step 5.
7. You should see how the client change the spell from red to white like saying you can cast that spell but the server returns "Out of Range" (see screenshot 3).

NOTE: This works at a certain distance, obviously if you get too far away from your enemy both client and server say you are not in range so this happens only at a certain distance from your enemy.

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/9072e0221b39c19fb6be154c623f45d6a9433db0

Screenshot 1 (im just out of range of autoattack but enough to cast Scourge Strike if im moving):
![](http://puu.sh/qGVLG/1be250edbf.jpg)

Screenshot 2 (im moving so I can cast Scourge Strike):
![](http://puu.sh/qGVDV/d9e2257405.jpg)

Screenshot 3 (im a little further from my enemy than the pictures 1 and 2 and im moving and my melee spells are white like I can cast them but I get "Out of range" message):
![](http://puu.sh/qGVFD/7ecb4e0957.jpg)

I'm not sure if the server is right or the client is right, im just posting this cause there is clearly a desync from client and server which makes players distracted.

**Comment by Treeston** [comment]
Without having looked into it more, this sounds like simply client and server having different positions due to lag (client does interpolation)?

**Comment by Raydor** [comment]
Idk, what I can say is that im testing this in a private dedicated server (im alone on it) and have 26ms if that helps in any way.

**Comment by Treeston** [comment]
iirc @Shauren did some looking into client logic for spell range last time this came up (#17693). Maybe he knows more.
