### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by alexandre433** [TrinityCore/TrinityCore#17812]
**Description**: "No Boost libraries were found" - Error 
I have the path set, and boost 1.5.9 is installed with the libraries

**Current behaviour**: Can't use cmake

**Branch(es)**: 3.3.5

**TC hash/commit**:  3f9cf3fdb6ab+

**TDB version**:  335.61

**Operating system**:  Windows 10 64-bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
this belongs to forum not to tracker.
