### ISSUE TITLE
[3.3.5] Quest: The Rider of the Unholy (13161) / Quest: The Rider of Frost (13162) / Quest: The Rider of Blood (13163)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17817]
3.3.5  3f9cf3f
[Quest: The Rider of the Unholy](http://www.wowhead.com/quest=13161/the-rider-of-the-unholy) - [Rokir](http://www.wowhead.com/npc=30954)
[Quest: The Rider of Frost](http://www.wowhead.com/quest=13162/the-rider-of-frost) - [Sapph](http://www.wowhead.com/npc=30956)
[Quest: The Rider of Blood](http://www.wowhead.com/quest=13163/the-rider-of-blood) - [Baelok](http://www.wowhead.com/npc=30953)

Quest credit is awarded incorrectly by SAI. Credit is awarded only to the player that dealt the final blow, regardless of whether that player is grouped or whether that player even has the target tagged.

Instead, credit should be awarded to the tagging group's members in range.

**Comment by dr-j** [comment]
Just change target 7 to 16 for kill credit

**Comment by Treeston** [comment]
Wouldn't that be giving it to _killer's_ party members, rather than tagging party's members?

**Comment by dr-j** [comment]
well the problem here is that kill credit npc is different entry so cannot use flags extra here to say no damage is required as long as player tags, there is also target 24 'all threat list' but that would also give credit to nearby players who never even tagged npc. but just got within agro range

**Comment by Treeston** [comment]
Yeah, good point. That's a deficiency. Let's fix that.
