### ISSUE TITLE
[CRASH] GetSpellIdForDifficulty

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#17810]
**Description**:
Crash by reentering a Battleground

**Branch(es)**: 3.3.5 
**TC hash/commit**:  dc78f1ecfc25a3d8e150dff571bd65c1e0ffab03
**TDB version**:  61
**Operating system**:  Linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
- http://pastebin.com/qpU7Vrqw
- http://pastebin.com/PfUZjPuG
[//]: # (For fixes containing c++ create a Pull Request)
Possible fix change in SpellMgr.cpp
```c++
uint32 SpellMgr::GetSpellIdForDifficulty(uint32 spellId, Unit const* caster) const
{
    if (!GetSpellInfo(spellId))
        return spellId;

    if (!caster || !caster->GetMap() || !caster->GetMap()->IsDungeon())
        return spellId;
```
to FinMap() ?

Thank you.

**Comment by Shauren** [comment]
Units that are not on any map should not be casting spells at all. You suggested fix is not a proper solution

**Comment by n4ndo** [comment]
Any suggestion? 10 crashes yesterday :/

**Comment by Nawuko** [comment]
Okay just checking the code and its 100% clear why this happens:

`Player::LoadFromDB` calls `currentBg->EventPlayerLoggedIn(this);` 

`EventPlayerLoggedIn` assumes the player is in the World and casts spell from the player object.

2 Options:
- Call `Battleground::EventPlayerLoggedIn` after the player is added to the world
- Dont cast fucking spells in `Battleground::EventPlayerLoggedIn`

**Comment by Nawuko** [comment]
Oh and following commit is responsible for the crash: https://github.com/TrinityCore/TrinityCore/commit/fbc521084cdd57d8e33071961aa3100e0fab2596 @ariel-

**Comment by jackpoz** [comment]
thank you for keeping your TC up to date and reporting issues very fast
