### ISSUE TITLE
wrong experience

### ISSUE THREAD

**Issue by ter884** [TrinityCore/TrinityCore#17822]
1 level should be 400, error 12000
starting with level 2, a strip of smooth experience level 1 = 400
![wowscrnshot_081916_204139](https://cloud.githubusercontent.com/assets/6825541/17818802/c1f6de5e-664d-11e6-8898-6127c3b554bb.jpg)
![wowscrnshot_081916_204123](https://cloud.githubusercontent.com/assets/6825541/17818803/c1fe4f36-664d-11e6-94d9-1b601ef67011.jpg)
7.0.3
https://github.com/TrinityCore/TrinityCore/commit/650ab693a8366847d7db8bd8443b3b4aaf99ff85

**Comment by funjoker** [comment]
Retail proof?

**Comment by funjoker** [comment]
Faile in Loading the xp GameTable.
Probably he is using the 0 row for level 1
