### ISSUE TITLE
[3.3.5] Groups dissolving on server crashes/restarts

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#17820]
**Description**:
Currently groups disband on server crashes or restarts.

**Current behaviour**: Tell us what happens
Currently groups disband on server crashes or restarts.

**Expected behaviour**: Tell us what should happen instead
Groups should not dissolve on crashes or restarts.

**Steps to reproduce the problem**:

1.  Create a group or raid.
2.  Ctrl+C your server
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/9072e0221b39c19fb6be154c623f45d6a9433db0

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
I have seen groups dissolved on PTR on crash.

**Comment by Nyeriah** [comment]
Well, it's mildly annoying when testing raids and content that requires you to be in a group. What's the point of saving group data to db if they won't be loaded away anyway btw? Referring to `group_member` etc

**Comment by Aokromes** [comment]
Dunno, it's not the 1st time i have seen raid groups disolved inside Siege of Orgrimmar.
