### ISSUE TITLE
[CRASH] ToBattlegroundMap

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#17825]
Description:
Crash by reentering a Battleground

Branch(es): 3.3.5 
TC hash/commit: 628792f960e035ca1ce10dcfbea2297a20c1e00c
TDB version: 61
Operating system: Linux

- http://pastebin.com/hpXjXNMD
- http://pastebin.com/3xexQzp7

Related to: https://github.com/TrinityCore/TrinityCore/commit/3f9cf3fdb6ab4d8c696c67df8289df016f9447ae

Thanks.

**Comment by jackpoz** [comment]
does your Player.cpp match https://github.com/TrinityCore/TrinityCore/blob/628792f960e035ca1ce10dcfbea2297a20c1e00c/src/server/game/Entities/Player/Player.cpp or do you have any custom change ?
