### ISSUE TITLE
[3.3.5] Pet talents Great Stamina and Natural Armor doesn't work at all

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#17837]
**Description**: Some pets (like bear, for example) have Great Stamina and Natural Armor talents, these talents increase stats for the pet, one increase % stamina and the other, % armor.

**Current behaviour**: Both of these talents doesn't increase any stats, they just don't work.

**Expected behaviour**: These talents should increase the pet stats.

**Steps to reproduce the problem**:
1. Tame a bear
2. Put some points on the talents Great Stamina or Natural Armor
3. Notice how the pet stats just don't increase

**Branch(es)**: 3.3.5

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/755add6fd202a50e43074c98315f74eaee1fa662

**Comment by Raydor** [comment]
Hmmm testing it more I found that these spells work, just the stats of the pet don't update until you relog so the only problem here is to update the stats when the talents are applied without reloging.

**Comment by MrSmite** [comment]
Old bug. Pet stats have never updated at talent assignment, player must relog.

The same thing happens with these talents from the Beastmastery tree:

*Thick Hide* - Increases pet armor
*Unleashed Fury* - Increases damage done by pet

**Comment by Raydor** [comment]
Updating stats like I did almost fixed it. For some reason, it lowers the base stat and I can't find the reason.

**Comment by MrSmite** [comment]
Interestingly, *UpdateAllStats()* doesn't update armor...

**Comment by MrSmite** [comment]
> Updating stats like I did almost fixed it. For some reason, it lowers the base stat and I can't find the reason.

Yeah, that is strange. *UpdateResistances()* only gets the mod value and updates the stat, it doesn't appear to touch the base stat at all.

**Comment by Raydor** [comment]
Its just a workaround, a fast test, HandleModBaseResistance is called by natural armor

**Comment by MrSmite** [comment]
> Its just a workaround, a fast test, HandleModBaseResistance is called by natural armor. I modified that too to test both talents.

Why though is it modifying the base resistance? Shouldn't it simply call *UpdateResistances(SPELL_SCHOOL_NORMAL)*?

This would trigger a call to *UpdateArmor()* which eventually calls *SetArmor(int32(value))* after calculating the modifier, not touching the base armor at all.

**Comment by Raydor** [comment]
Sorry thats my bad, got confused by the diff, natural armor calls the function HandleModResistancePercent which is where I put the UpdateStats. Using UpdateResistances there generates the same exact issue as if I use UpdateAllStats, it updates the armor but it doesn't show the same exact amount of armor as if you relog.

**Comment by Goatform** [comment]
@MrSmite, I think that this issue can be referred to #6709 as well. Since player has to relog in order to apply aura status to his pet(s) (in this case). So I assume that it is general problem with pet's talent system.

**Comment by MrSmite** [comment]
@Goatform - #6709 is for another pet talent: *Wild Hunt* but yes, as I mentioned earlier in this report, the player's talents also do not immediately update the pet's stats (which I think I reported years ago).

**Comment by MrSmite** [comment]
Note:

Great Stamina is working on 2db9269ec1c06b5fccc45dc0a5b4f714f9b48804 , you have to log out and back in to see the effect after placing a point in it. I didn't actually do the math to see if the increase is proper but there is an increase.

**Comment by MrSmite** [comment]
> this issue is still valid?

I haven't compiled a core recently for my new machine but on my old box, this server is running and talents work properly. I tamed a cat and applied both Great Stamina and Natural Armor. Upon clicking "Learn" then "Yes" to confirm, the stats were increased.

rev 2db9269 (from Jun 10, 2016)

**Comment by Aokromes** [comment]
you can test on https://tcubuntu.northeurope.cloudapp.azure.com/ if you need to be leveled jump into irc.

**Comment by Aokromes** [comment]
no answer after 2 years, if this bug is still valid post results with updated core.
