### ISSUE TITLE
[Crash] SmartAI

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17835]
http://paste.ubuntu.com/23073899

**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

**Comment by Aokromes** [comment]
1st law before reporting bugs: don't use one 2 months old core.

**Comment by sirikfoll** [comment]
for what it's worth, i have this crash too (on a 3 months old core xD)
https://gist.github.com/sirikfoll/a1b5aec0058c2efbe11bdcf4f62ae2b7

**Comment by Aokromes** [comment]
Try after a97439e8d63c0a78bda8a6ed4801f122385936e3

**Comment by Aokromes** [comment]
No answer after near 1 year, closing.
