### ISSUE TITLE
[COMPILER] libscripts_northrend

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#17836]
Description:
Could not dynamic load the shared library "/WorldServer/bin/./scripts/libscripts_northrend.so".

Branch(es): 3.3.5 
TC hash/commit: 0a53d0b1fadb0861e57ef6332d1afeb75babf836
TDB version: 61
Operating system: Linux

I want to note, that i did not change anything on my compile way mode, just pull and compile, also try with a clean compilation.

Next i try with -DSCRIPTS_NORTHREND='static' and this is the result:

```gdb
[100%] Linking CXX executable worldserver
../scripts/libscripts.a(instance_ulduar.cpp.o): In function `instance_ulduar::instance_ulduar_InstanceMapScript::SetData(unsigned int, unsigned int)':
/Compiler/Sources/src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp:972: undefined reference to `UpdateData::UpdateData()'
/Compiler/Sources/src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp:975: undefined reference to `UpdateData::BuildPacket(WorldPacket*)'
../scripts/libscripts.a(zone_wintergrasp.cpp.o): In function `go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::UpdateAI(unsigned int)':
/Compiler/Sources/src/server/scripts/Northrend/zone_wintergrasp.cpp:350: undefined reference to `WintergraspFaction'
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/worldserver/worldserver] Error 1
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [all] Error 2
```

Thanks.

**Comment by Aokromes** [comment]
[100%] Built target worldserver
Install the project...
-- Install configuration: "None"

I suggest you to rerun cmake.

**Comment by Shauren** [comment]
Clean TC sources do not have a reference to `UpdateData` in `instance_ulduar::instance_ulduar_InstanceMapScript::SetData`

**Comment by n4ndo** [comment]
thanks @Shauren, i already remove that part of the code, recompile with dynamic mode, and again the same error

```gdb
Could not dynamic load the shared library "/WorldServer/bin/./scripts/libscripts_northrend.so".
```

**Comment by tkrokli** [comment]
Try again with clean and unchanged code. There is most likely other changes you have forgotten to remove, making your source code different from straight and unchanged TrinityCore source code.

**Comment by n4ndo** [comment]
Thanks for your time.

Just doing some test, i reverted this commit: 1deb7d2df178a98bc1b1cde2ca99301e7ee85ecb and the lib libscripts_northrend was loaded successfully.
