### ISSUE TITLE
[3.3.5a] [QUEST]   The Scarlet Apocalypse

### ISSUE THREAD

**Issue by Demonith** [TrinityCore/TrinityCore#17839]
**Description**:  http://wotlk.openwow.com/quest=12778

**Current behaviour**: When get down from the Hold i get attacked by Trisifal Crusader over and over 

**Branch(es)**: 3.3.5 latest

**TDB version**:  755add6fd202

**Operating system**:  W10

**Comment by Aokromes** [comment]
#15083
