### ISSUE TITLE
Possible group thread safety issues

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#17838]
**Description**:
Members of a group can be on separate maps.
Any action that alters data of those members that are on separate maps in any situation within a map update call is a possible data race because update calls are processed with multiple threads.

For example players A and B are on separate maps, but in same group.
A map update runs for both players concurrently and calls a function that updates all of that player's group's member's achievements. Because the same action runs from two threads for the same player there should be a data race since updating achievements edits a shared container. In this case the data race could for example be caused by the call to `m_timedAchievements.erase(timedIter);`

There are two ways of getting group members and going through them.
One is thread safe as it uses guids and only allows looping through members on a map.
The other one is unsafe and allows looping through all members.

```c++
// unsafe if modifying groupie because the member is accessed directly without locks
// and this loop is done from multiple threads
for (GroupReference* itr = group->GetFirstMember(); itr != NULL; itr = itr->next())
{
    Player* groupie = itr->GetSource();
    if (groupie)
        std::cout << groupie->GetName() << std::endl;
}

// safe because ObjectAccessor::GetPlayer only finds players on same map as unit
// .. assuming unit is on the map that the current thread processes
Group::MemberSlotList const& members = group->GetMemberSlots();
for (Group::member_citerator itr = members.begin(); itr != members.end(); ++itr)
{
    Player* groupie = ObjectAccessor::GetPlayer(*unit, itr->guid);
    if (groupie)
        std::cout << groupie->GetName() << std::endl;
}
```

Both are unsafe if either are executed in multithreaded context and edit a shared global variable, such as a the achievement data if there is no lock I believe.

**Current behaviour**:
In some places the unsafe way is used to loop through players in contexts which can be executed from multiple threads at the same time.

**Expected behaviour**:
The needed processing should be delayed until single thread execution or the first approach is used for looping group members if only members on same map are needed.

**Steps to reproduce the problem**:
Here is an example chain of calls that I suspect is a possible data race:
```C++
boss_lady_deathwhisper.cpp
boss_lady_deathwhisper::JustDied // Callable from multiple threads at the same time I believe
Player::KilledMonsterCredit // called from within one of those unsafe loops
Player::UpdateAchievementCriteria
AchievementMgr::UpdateAchievementCriteria
AchievementMgr::SetCriteriaProgress
m_timedAchievements.erase(timedIter);
```

Now, as you might notice, it is unlikely true that two players in a group are killing the lady deathwhisper at the same time in different maps and causing an achievement update, but such an event would cause a data race. In fact it might be impossible to actually have this chain executed currently in real gameplay. There seem to be a number of similar occurrences in the code and it is difficult to find an actual easily reproducible example.
I myself could not see any locking at any of the stages in this chain.

Here is a callstack that shows that the JsutDied hook is called from map update:
https://gist.github.com/Rochet2/ced6f2605922bd84875cd681454b7077
The breakpoint was set on the part in Kill where JustDied is called for creature AI.

I did not use any tools to verify that there is a data race. This is simply an observation from looking at the code.

**Branch(es)**:
3.3.5, 6.x

**TC hash/commit**:
0a53d0b1fadb0861e57ef6332d1afeb75babf836

**TDB version**:
TDB_full_world_335.61_2016_04_11.sql

**Operating system**:
Windows 10 64 bit

**Comment by Shauren** [comment]
There are no "possible issues". The issue either is there (you used a tool to confirm it) or is not there (you used a tool to confirm it)

**Comment by Rochet2** [comment]
@Shauren Can you suggest a tool that runs on windows to confirm it?

This one is pretty clear as you can clearly see that the death hook can be called from multiple threads and any modification to a player in an unsafe loop as shown in main post is unsafe.

**Comment by Shauren** [comment]
On windows? Nope, set up a linux virtual machine and use valgrind - that is what I do
