### ISSUE TITLE
[6.x] Spell/Aura: Crash on BuildPacket function

### ISSUE THREAD

**Issue by Ardinis** [TrinityCore/TrinityCore#17842]
**Description**: We have a crash when we are building the packet for aura

**Current behaviour**: 

**Expected behaviour**:

**Steps to reproduce the problem**:
1. Hard to tell you...

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x
**TC hash/commit**:  f10a4c1364677717b34f8263d5e2d8fb05a90fc7

**TDB version**:  6.04

**Operating system**:  Linux

**Comment by Shauren** [comment]
https://gist.github.com/Shauren/36555c93d54c701ec70c1af974cd0f0e

Try this - if you hit the assert added here then something goes wrong with aura slot assignments

**Comment by Shauren** [comment]
Also I'm seeing a custom change in auras `lossOfControlMechanic` on top of the crash log being incomplete (its lacking the most important piece of information about the aura - AuraApplication::_slot)

**Comment by matanshukry** [comment]
1. Does this target the master branch as well?
2. Is this still valid today? I don't see any crash log nor any way to reproduce this.

**Comment by Faq** [comment]
No respire from 2016., so if still happens, can open new ticket with updated core.
