### ISSUE TITLE
[7.x PrePatch] Client Crash when summon pet

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#17848]
**Description**: Client Crash when summon pet

**Current behaviour**:  Client Crash when summon pet (hunter's pet and mage's water elemental)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. summon a pet
2. logout
3. login then Client Crash 

**Branch(es)**:  6.x 7.x PrePatch

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/796e851a8f61ea82d267af4931fe9bd1e09b5902

**TDB version**:  TDB 6.04

**Operating system**:  win7 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Nuppi** [comment]
Warlock same

**Comment by funjoker** [comment]
Petsystem broken.
:/
