### ISSUE TITLE
[6.x/7.x] Scene System 50$ bounty

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#17858]
**Description**:
The Scenes in WoW are handled clientside.
By sending the opcode SMSG_PLAY_SCENE with correct data the Client does almost everything by itself.

**Current behaviour**: Nothing, totaly missing 

**Expected behaviour**: By sending the opcode SMSG_PLAY_SCENE with correct data the Client does almost everything by itself. SceneId must be linked to SceneScriptPackageID. Scene Hotfixes must be included.

CMSG_SCENE_TRIGGER_EVENT must trigger a Server Script selected via Name. Scenes can trigger unique Scripts.

SceneInstanceId is counting up the time of Session.
On relogg it starts again at 1 (Temp data).

Canceling and completing Scenes must be implemented.

SPELL_AURA_430 are spells which start Scenes.

**Steps to reproduce the problem**:

1. Use spells with SPELL_AURA_430

**Branch(es)**: 6.x 

**TC hash/commit**:  
2017c515de588e652846fa1781cfbad64f4aaa15

**TDB version**:  
6.04

**Operating system**:  
Win10/Linux

**BountySource**
https://www.bountysource.com/issues/37241093-6-x-7-x-scene-system-50-bounty

**Comment by malcrom** [comment]
This is the gayest thing I've read all day.

**Comment by funjoker** [comment]
http://pastebin.com/7Jb3zKpd

Some Info

**Comment by Pixel-Pirate** [comment]
what the fuck ? 50$ really ? :D

**Comment by funjoker** [comment]
Well no one implemented it even it was there since Wod. So a bounty might motivate people xD
