### ISSUE TITLE
[3.3.5] Druid 'Dash' castable outside Cat Form

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17855]
3.3.5 5da3ae0

It shouldn't be castable outside Cat Form. That is all.

**Comment by tkrokli** [comment]
Links, for those of us who are interested::
- http://www.wowhead.com/spell=1850/dash
- http://www.wowhead.com/spell=1850/dash#comments
- http://www.wowhead.com/spell=1850/dash#changelog

> 

- http://wow.gamepedia.com/Dash_(druid_ability)
- http://wow.gamepedia.com/Dash_(druid_ability)#Patches_and_hotfixes

**Comment by Shauren** [comment]
Not a bug. This is unchanged on retail for a long time
Using Dash outside of cat form should activate cat form (does this part work?) and shifting out of cat form should not remove the buff but only deactivate the speed bonus (I think this part is implemented)
