### ISSUE TITLE
[6.x, 7.x PrePatch]: Warrior spell Enrage (id: 184361) procs on every attack

### ISSUE THREAD

**Issue by cybrann** [TrinityCore/TrinityCore#17866]
**Description**:
Warrior spell Enrage (id: 184361) procs on every attack

**Current behaviour**: Tell us what happens
Warrior spell Enrage procs on every offensive spell (spell that deals damage) used

**Expected behaviour**: Tell us what should happen instead
It should proc only on Bloodthirst critical strikes and when player uses Berserker rage if talent Outburst (id: 206320) is active.

**Branch(es)**: 6.x 

**TC hash/commit**:  b0c8a9411e4102bc649387f5760fb9118a4762e3

**TDB version**:  TDB 6.04_2016_04_11 (with all latest updates)

**Operating system**:  Windows 7 Ultimate

**Comment by Nyr97** [comment]
Invalid, doesn't trigger on every attack anymore.

**Comment by Aokromes** [comment]
fixed not invalid :P
