### ISSUE TITLE
[6.x] Core/Conditions: Future Feature CONDITION_QUEST_OBJECTIVE_COMPLETE

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#17863]
**Description**:
Since WoD, phase changes are caused also by single objective completions.
This condition is missing atm. This is just to have an issue opened.

**Current behaviour**: NYI

**Expected behaviour**: Comparable to `CONDITION_QUEST_COMPLETE`
If Objective is complete, condition is met.

**Branch(es)**:  6.x

**TC hash/commit**:  
9b80805d69477102a1ab29925d3c8914d2273476

**TDB version**:  
6.0.3

**Operating system**:  
All

**Comment by DDuarte** [comment]
Any suggestion what ConditionValue1/2/3 should be?

**Comment by funjoker** [comment]
I would say value1 questid and value2 objective
maybe we don't even need questid but i think it will be useful

**Comment by DDuarte** [comment]
quest id is definitely needed but how do you reference objectives?

**Comment by funjoker** [comment]
character_queststatus_objectives stores values for characters.
quest_objectives stores templates of objective. Comparing both should make it possible.

**Comment by DDuarte** [comment]
ConditionValue1 == quest_objectives.ID, got it

**Comment by funjoker** [comment]
https://github.com/Traesh/TrinityCore/tree/condition_quest_objective_complete

**Comment by funjoker** [comment]
d60daf529e7c1526ba63809ec3e651492fd55dd1
