### ISSUE TITLE
[3.3.5] Trial of the Crusader: Icehowl unit state / evade issue

### ISSUE THREAD

**Issue by DeActiveDev** [TrinityCore/TrinityCore#17864]
After the EVENT_MASSIVE_CRASH, boss must jump and place the wall randomly, then boss should move to the same place and charge, but he stops at that place and evades.

Trial of the Crusader : The Northrend Beasts 

**Current behaviour**: just stop

**Expected behaviour**: must random charge follow target

**Branch(es)**: 3.3.5

**TC hash/commit**:   211eee0fce0bf9720511ad05fae271512b24f48e

**TDB version**:  TDB 335.61 + updates

**Operating system**:  win 10

**Comment by Keader** [comment]
wtf?

**Comment by DeActiveDev** [comment]
problem is after this commit 061b62a97dc9fbc1687de48404ed8e56e4fd1f5d for change lines boss_northrend_beasts.cpp : 1110

-                            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_REMOVE_CLIENT_CONTROL);
+                            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
+                            me->SetControlled(true, UNIT_STATE_ROOT);
	
for this boss have problem , for other bosses ?!!!
