### ISSUE TITLE
[7.x PrePatch] Mastery: Unschackled Fury bug

### ISSUE THREAD

**Issue by cybrann** [TrinityCore/TrinityCore#17868]
**Description**:
Fury warrior mastery bug explanation

**Current behaviour**: Tell us what happens
When enrage is active damage that fury warrior deals is modified by fury warriors mastery Unshackled Fury. And this part is working properly. But it is bugged in another way. When enrage expires the damage is not returned to normal. It is still increased. And next time the enrage activates the damage increases once more. 

For example:
Unshackled fury is increasing the damage for 10% and the damage of bloodthirst is 1000 normaly. Now when enrage activates it is 1100. And it is working this way. But when the enrage falls off the damage still stays 1100 it is not decreased. Then next time when the enrage activates is is increased by 10% more to 1210 now. And it goes like this forever. It is possible to deal bilions of damage this way.

**Expected behaviour**: Tell us what should happen instead
The damage should be increased only during the enrage period.

**Branch(es)**: 6.x

**TC hash/commit**:  9f7c26273b96ae54542cf90872fd6c638879f0eb

**TDB version**:  6.04 TDB with the latest updates.

**Operating system**:  Windows 7 Ultimate x64

**Comment by funjoker** [comment]
Nice :D
