### ISSUE TITLE
you have been disconnected 

### ISSUE THREAD

**Issue by justdothings** [TrinityCore/TrinityCore#17873]
hello, i compiled server on linux vps and same time on windows for connection patcher in config.wtf set portal "vpsip"  but it says you have been disconnected, i need to upload client on vps and use linux connection patcher?

**Branch(es)**:  6.x 

**TC hash/commit**:  7c0b3a7bd449d83aafa80a9267763f3fc39613ac

**TDB version**:  6.04

**Operating system**:  ubuntu 16.04/ client windows 7

**Comment by Aokromes** [comment]
this belongs to forum, not to here.

**Comment by tkrokli** [comment]
Use the server computer's IPv4 localhost address in `SET portal = "127.0.0.1"`.

BTW, this is not a source code issue, it is a configuration issue just for you.
Please use the TrinityCore Forum pages for this kind of problem:
https://community.trinitycore.org/forum/5-help-and-support/

**Comment by justdothings** [comment]
but i want to server run on vps not on my computer. @tkrokli

**Comment by tkrokli** [comment]
That is a DNS problem for you to solve only, not a source code problem.
This issue tracker is only to be used for bugs in the source code, affecting all users.
Please use the TrinityCore Forum pages for this kind of problem.
https://community.trinitycore.org/forum/5-help-and-support/
