### ISSUE TITLE
[6.x] Liquids error

### ISSUE THREAD

**Issue by Regigicas** [TrinityCore/TrinityCore#17871]
**Description**: 
Liquids are not working fine in new zones post-wotlk

**Current behaviour**:
Some areas has bad information:
http://i.imgur.com/VlNfJic.jpg

Others simply doesn't have info:
http://i.imgur.com/0KxU8z1.png

**Expected behaviour**:
In the first example i shouldn't have fatigue.
In the second i should have the breath bar and liquid data.

**Steps to reproduce the problem**:
For Fatigue: .go -4821.64 -5795.38 58.71 0

For Breath and no liquid data: .go -5123.63 -5134.69 40 0

**Branch(es)**:  6.x 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/b0c8a9411e4102bc649387f5760fb9118a4762e3

**TDB version**:  TDB 6.04

**Operating system**:  Windows 10 x64

**Comment by cybrann** [comment]
Offtopic, how did you get artifact power bar to fill?

**Comment by Regigicas** [comment]
Db edit

**Comment by meji46** [comment]
Confirmed in Vashj'ir

**Comment by cybrann** [comment]
> Db edit

How? I tried to look in characters and hotfix db and it is most likely in hotfix but idk what to edit..

**Comment by Ovahlord** [comment]
@cybrann simply add artifact power items from the dungeon compendium and use them? Btw stop getting offtopic here. Stay patient and wait for something.
