### ISSUE TITLE
MMaps improvements

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#17878]
**Description**:
Current MMap settings and algorithms could be modified in attempt to improve overall pathfinding behavior. Current point of interests are:
- [ ] Z coordinate returned by Detour is incremented with += 0.5f for no apparent reason https://github.com/TrinityCore/TrinityCore/blame/ccdca7774023e7570f17cf15456384b316322420/src/server/game/Movement/PathGenerator.cpp#L734 and https://github.com/TrinityCore/TrinityCore/blame/ccdca7774023e7570f17cf15456384b316322420/src/server/game/Movement/PathGenerator.cpp#L779 . This could be related to a recent commit that increased/decreased GetHeight() ray Z position by 0.5f
- [x] detailSampleMaxError and detailSampleDist could be lowered to get a more accurate Z from Detour that will still help getting the correct Z from maps/vmaps . https://github.com/jackpoz/recastnavigation can be used to test different values. Detail Mesh quality shouldn't affect node count in the A\* algorithm and increase only mmaps generation times and memory usage. More infos about Detail Mesh at http://digestingduck.blogspot.it/2009_07_01_archive.html and http://digestingduck.blogspot.it/2009_08_01_archive.html
  - Suggested locations:
    - Map: 1 X: 1038.307251 Y: -4635.038086 Z: 57.680607
    - Map: 1 X: 1010.265259 Y: -4043.611328 Z: 27.020494
- [x] update recast to https://github.com/recastnavigation/recastnavigation/commit/15ebb8bd25e952215d2ff140d5ec01fa50294275 which supposedly fixed some height issues

**Branch(es)**:
3.3.5

**TC hash/commit**:  
c0de28b045f6c7d31652262c9b96d0739fec8110

**Comment by jackpoz** [comment]
(because it makes more sense to first discuss and then code/open a PR instead of first code/open a PR and then discuss)

**Comment by Treeston** [comment]
Ad 2: Are there any core runtime downsides to increasing mmaps accuracy? Or purely mmaps generation time (which isn't overly relevant, because one-time).

How about mmaps file sizes?

**Comment by jackpoz** [comment]
the increased accuracy applies only to detail mesh (aka *.dmesh) which is used only by getPolyHeight() queries, i.e. https://github.com/TrinityCore/TrinityCore/blame/ccdca7774023e7570f17cf15456384b316322420/src/server/game/Movement/PathGenerator.cpp#L733 .
It will most likely increase *.mmtile files since those contain the detail mesh too and this will mean increased memory usage too. The "how much" depends on how better the new settings will be (on a plain field it won't make any difference).

**Comment by r00ty-tc** [comment]
Some good ideas. Maybe that explains why when I tried to make a method to obtain vmap hints from mmaps (in order to avoid false underground ground levels).there were a few places with huge differences.

I don't know why there would be the +0.5 though. For vmap rays it makes sense, but for the navmesh it doesn't.

**Comment by Treeston** [comment]
At this point, there does not seem to be any significant disagreement about this. It's pretty safe to say you can start working on this.

Looking forward to a first testing branch that I can merge into the test server core!

**Comment by jackpoz** [comment]
1st and 3rd points are pretty straightforward, the 2nd one just needs some recastdemo tests to figure out a good pair of values (afterall it's just a slider to be moved left/right to adjust the values)

**Comment by sucofog** [comment]
Not any news about this @jackpoz ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/7ef22e43057080926685eb45f0fce3f2f3d58c61 fixed the 3rd point

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479 fixed the 2nd point

**Comment by Keader** [comment]
since you improving mmap stuffs, can take a look in https://github.com/TrinityCore/TrinityCore/issues/7592? :)

**Comment by sucofog** [comment]
@jackpoz Nice one!

**Comment by Killyana** [comment]
About the : Z coordinate returned by Detour is incremented with += 0.5f for no apparent reason 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L1414
