### ISSUE TITLE
[6.x/7.x] Death Knight's rune power has no cooldown

### ISSUE THREAD

**Issue by u0yiji** [TrinityCore/TrinityCore#17879]
**Description**:Death Knight's rune power has  no cooldown

**Current behaviour**: Death Knight's rune power immediate regenerate 

**Expected behaviour**: Death Knight's rune power has 10 sec cooldown

**Steps to reproduce the problem**:

1. cast a rune cost spell  like  49184 [Howling Blast]
2. it take 1 rune, then regenerate immediate 
3. so I can cast many spell with no power limit

**Branch(es)**: 6.x 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/e29494b01dbacda3e28766d41f6f267e4adafe29

**TDB version**:  TDB 6.04

**Operating system**:  WIN7 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by funjoker** [comment]
Rename it.
No more prepatch, Legion is live.
