### ISSUE TITLE
database issue?

### ISSUE THREAD

**Issue by kodiarctodus** [TrinityCore/TrinityCore#17875]
**Description**: Most classes start with no spells at all.

**Current behaviour**: When starting a new character, the toon has no spells. For cloth wearers, they are basically unplayable (cannot kill anything). 

**Expected behaviour**: Toons should start with skills per Blizzlike conditions. 

**Steps to reproduce the problem**:

1. Rolled Night Elf mage- no spells. Cannot kill nightsabers.
2. Recompiled, downloaded fresh DB, rolled Blood Elf mage. No spells, cannot kill mana wyrms.
3. Pulled updates using Git Extensions, recompiled, downloaded fresh DB, rolled Undead mage. No spells. Cannot kill mindless zombies. 

**Branch(es)**: 6.x

**TC hash/commit**:  7c0b3a7bd449

**TDB version**:  6.04 (TDB_full_6.04_2016_04_11.7z is the file downloaded)

**Operating system**:  Win7 Professional 64bit and Windows 10 Enterprise 64bit
[Server.txt](https://github.com/TrinityCore/TrinityCore/files/445835/Server.txt)
Additional compilation information:
Visual Studio Community 2015 update 3
CMake 3.6.1
GitExtensions 2.48.05
Boost 1.60
MySQL Server 5.6
OpenSSL 1.0.2
SQLYog 12.2.4
Git 1.9.5

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
No, you are simply using alpha software.
