### ISSUE TITLE
Quest: Blessing of Zim'Rhuk (12656)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17872]
**Description**:
If you rightclick on the GO Zim'Rhuk nothing happens.

http://de.wowhead.com/quest=12656/der-segen-von-zimrhuk
http://www.wowhead.com/object=190657/zimrhuk

**Steps to reproduce the problem**:

1.  .go 6169 -3558 386 571
2.  .quest add 12656
3.  Click on the Statue
4.  Nothing happens

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
TC>TrinityCore rev. a32536d490a3 2016-08-28 20:13:39 +0200 (335 branch)

**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates
**Operating system**:  
Win7 64Bit

**Comment by Killyana** [comment]
Try to click on a corner.

**Comment by Tauriella** [comment]
It works only on a Side for the Statue ( range Bug )

Thanks for the info.

**Comment by tkrokli** [comment]
This GO range issue is still present, but it looks like we don't have a solution for the inner GO size. See also
- [**The Blessing of Zim'Rhuk**](3528) #3528 (closed)
- [**[QUEST] The Blessing of Zim'Rhuk (12655)**](3845) #3845 (closed)
- [**[3.3.5a] Large GOs and gossip availability**](15453) #15453 (open)

**Comment by Aokromes** [comment]
#15453
