### ISSUE TITLE
[6.x/7.x] Spell: Rouge Mutilate

### ISSUE THREAD

**Issue by timsar2** [TrinityCore/TrinityCore#17888]
**Description**: Rouge Mutilate should award combo points.
- http://www.wowhead.com/spell=1329/mutilate

**Current behaviour**: Rouge Mutilate does not award combo points.

**Expected behaviour**: Caster must gain 2 combo points after using mutilate.
- http://www.wowhead.com/spell=5374/mutilate
- http://www.wowhead.com/spell=27576/mutilate-off-hand

**Steps to reproduce the problem**:
1. i think id 30 effectenegize not work
2. add :m_caster->m_movedPlayer->AddComboPoints(damage, this); into effectenergize(spelleffect.cpp) and work
3. 

**Branch(es)**: 6.x 

**TC hash/commit**:  e29494b01dba

**TDB version**:  TDB_world_6.04_2016_04_11

**Operating system**:  Windows7 x64

**Comment by ArcaneFox** [comment]
It's working, tested with a level 40 character.
(I have to unlearn [Seal Fate] because it's awards me 5 combo points [but after unlearn Mutilate gets me 2 cp].)
