### ISSUE TITLE
[3.3.5] Quest: Take No Chances (11913)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17887]
3.3.5 f5cbc17

[Quest: Take No Chances](http://www.wowhead.com/quest=11913/take-no-chances)

You can repeatedly use [Wendy's Torch](http://www.wowhead.com/item=35491) on the same sack of Frashire Grain. It never despawns.

**Comment by tkrokli** [comment]
Probably lack of despawning the target http://www.wowhead.com/npc=26161/farshire-grain-credit or maybe even not setting data for the object as used by current player (not sure how it works now, though).

**Comment by Tauriella** [comment]
Look here in 0:57min

https://www.youtube.com/watch?v=f9rSeGS7mlU

**Comment by tkrokli** [comment]
So the GO is supposed to change by despawning the original object and turn into a burning object with a certain duration? Or are the flames just a secondary object spawned on top of the original one?

**Comment by Treeston** [comment]
Flames are already spawned on TC. Not sure how.

**Comment by Aokromes** [comment]
Maybe it's one aura.

**Comment by LKArthas** [comment]
Mostly The SAI needs to have set an event_flags to 1 and check the reset SAI action script

**Comment by Staleness89** [comment]
http://www.wowhead.com/spell=46574/burn-grain
^ Spawns a gameobject (the flame) on the spell focus, which is the bag of grains.

Anybody have an idea on how to stop the spell from casting while the flame is active?

**Comment by Treeston** [comment]
Conditions. Do not allow casting if GO with entry within range = spell range.

**Comment by Staleness89** [comment]
just wondering if that will make certain ones overlap with each other if two or more are too close to each other. If not, then this would be an easy fix:
```SQL
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (17, 0, 46574, 0, 0, 30, 182071, 8, 0, 0, 0, 0, 0, '', 'Spell requires no GameObject (182071) within 8 yards');
```

**Comment by Rushor** [comment]
but the spellfocus go will not despawn with this?

**Comment by Staleness89** [comment]
it still needs something for despawning
