### ISSUE TITLE
Dreamwalker 10HC HP Reducing

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#17882]
**Branch(es)**: 3.3.5
**TC hash/commit**:  5868509a6366d0ba7a0fe819c3ece0e4a57c7029
**TDB version**:  61
**Operating system**:  Debian

in heroic mode this part doesn't work in current core:
Valithria's health decays over time. While she still starts at half health and remains at the same max health as normal mode, the decay means more healing needed as the encounter goes on. 

http://wowwiki.wikia.com/wiki/Valithria_Dreamwalker

**Comment by Treeston** [comment]
Does it work in 25-man heroic?

**Comment by sucklifex** [comment]
@Treeston, It should

**Comment by Treeston** [comment]
_Does_ it though, in the rev you mention?

**Comment by sucklifex** [comment]
@Treeston Nope, doesn't work in 25Heroic either

**Comment by Riztazz** [comment]
It took me some time back in the day to figure out whats supposed to deal damage to valithria, its those fuckers in portal phase, their aura is supposed to target valithria, AFAIK there is condition for nearby_entry missing

**Comment by Shauren** [comment]
I don't know if someone messed with the spawns but when I added this script, the spawns had a phase setup like this
Valithria (not dream phase) 1 + 4
Nightmare Cloud 16 + 4

Dream phase has mask 16 and that is where players are put. From the setup above you have Valithria and clouds share phase 4, these casts should be working through there

**Comment by sucklifex** [comment]
could be fixed by hacks ?

**Comment by Keader** [comment]
dd81978f432f9c1ecb72ebcadcb5a50042e005ad
