### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#17881]
I get this compiling error when i used vs2015.

C:\local\boost_1_59_0\boost/asio/detail/config.hpp(227): warning C4005: 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT': macro redefinition
C:\local\boost_1_59_0\boost/asio/detail/config.hpp(213): note: see previous definition of 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT'

In the installation of boost when i use the command .b2 to compile library i get error in the console.

.\boost/asio/detail/config.hpp(227): warning C4005: 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT': macro redefinition
.\boost/asio/detail/config.hpp(213): note: see previous definition of 'BOOST_ASIO_ERROR_CATEGORY_NOEXCEPT'

Branch: 3.3.5

TC hash/commit**:  69b581deff2cb42b9cb5620c87f0861fcb760bea

**Operating system**:  Windows 10 x64 Enterprise

Sorry for my english.

**Comment by Shauren** [comment]
These are warnings, not errors.

**Comment by Edreisantafe** [comment]
Thats compiling warning result in this compiling errors:
Severity	Code	Description	Project	File	Line
Error	LNK1120	7 unresolved externals	mapextractor	C:\Build\bin\Release\mapextractor.exe	1
Error	LNK1120	2 unresolved externals	mmaps_generator	C:\Build\bin\Release\mmaps_generator.exe	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(AppenderFile.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(AppenderFile.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Config.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Config.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Log.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Log.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(MapTree.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(MapTree.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Metric.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(Metric.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(VMapManager2.obj)	1
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)	mmaps_generator	C:\Build\src\tools\mmaps_generator\common.lib(VMapManager2.obj)	1
Error	LNK2019	unresolved external symbol "void __cdecl boost::filesystem::path_traits::convert(wchar_t const *,wchar_t const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::codecvt<wchar_t,char,struct _Mbstatet> const &)" (?convert@path_traits@filesystem@boost@@YAXPEB_W0AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$codecvt@_WDU_Mbstatet@@@5@@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl boost::filesystem::path::string(void)const " (?string@path@filesystem@boost@@QEBA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &,class std::codecvt<wchar_t,char,struct _Mbstatet> const &)" (?convert@path_traits@filesystem@boost@@YAXPEBD0AEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBV?$codecvt@_WDU_Mbstatet@@@5@@Z) referenced in function "public: __cdecl boost::filesystem::path::path<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,void *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@path@filesystem@boost@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "public: static class std::codecvt<wchar_t,char,struct _Mbstatet> const & __cdecl boost::filesystem::path::codecvt(void)" (?codecvt@path@filesystem@boost@@SAAEBV?$codecvt@_WDU_Mbstatet@@@std@@XZ) referenced in function "public: __cdecl boost::filesystem::path::path<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,void *)" (??$?0V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@path@filesystem@boost@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAX@Z)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "void __cdecl boost::system::`dynamic initializer for 'native_ecat''(void)" (??__Enative_ecat@system@boost@@YAXXZ)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "void __cdecl boost::system::`dynamic initializer for 'errno_ecat''(void)" (??__Eerrno_ecat@system@boost@@YAXXZ)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "class boost::filesystem::file_status __cdecl boost::filesystem::detail::status(class boost::filesystem::path const &,class boost::system::error_code *)" (?status@detail@filesystem@boost@@YA?AVfile_status@23@AEBVpath@23@PEAVerror_code@system@3@@Z) referenced in function "void __cdecl CreateDir(class boost::filesystem::path const &)" (?CreateDir@@YAXAEBVpath@filesystem@boost@@@Z)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1
Error	LNK2019	unresolved external symbol "bool __cdecl boost::filesystem::detail::create_directory(class boost::filesystem::path const &,class boost::system::error_code *)" (?create_directory@detail@filesystem@boost@@YA_NAEBVpath@23@PEAVerror_code@system@3@@Z) referenced in function "void __cdecl CreateDir(class boost::filesystem::path const &)" (?CreateDir@@YAXAEBVpath@filesystem@boost@@@Z)	mapextractor	C:\Build\src\tools\map_extractor\System.obj	1

**Comment by Aokromes** [comment]
This is not a forum, also, i sugest yo to update to boost 1.60.
