### ISSUE TITLE
[3.3.5] Raid Warning in parties

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17889]
3.3.5 f5cbc17

While in a party, you can't use `/rw`. Expected behavior is being able to use `/rw` (any member can do so, no need to be leader).

**Comment by Aokromes** [comment]
http://wowwiki.wikia.com/wiki/MACRO_raidwarning

Since patch 3,3 it isnt possible anymore to preforme a raid warning in a party

**Comment by Aokromes** [comment]
p.s. maybe someone can create a config for this.

**Comment by Treeston** [comment]
Yeah config for that would be super handy, also I'm pretty sure you could still do it during 3.3, heck you could do it through cata even. Weird.

**Comment by Treeston** [comment]
aok: add feature request label please, i can't find the option on mobile github and won't have desktop the next few days.
