### ISSUE TITLE
[7.x] Creature Scaling System (100$ bounty)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#17898]
**Description**:
In Legion, the creatures in Dungeons and leveling zones scale to your level, but only visible and occuring to you.

http://www.polygon.com/2015/11/6/9684580/world-of-warcraft-legion-zones-level-scaling

Example:
Player1 Level 101
Player2 Level 110
Moblevel seen by Player1 = 101
Moblevel seen by Player2 = 110
(this is the Same unique mob at same time)

**Current behaviour**: Nothing

**Expected behaviour**: 
- Damage done must be adapted
- Damage received must be adapted
- Health must be adapted
- Experience must be adapted
- everything i forgot to point here

How is level and damage being influced by group with different character levels?
Does it scale with itemlevel? Artifact Scenarios mobs scaling with itemlevel?

**Branch(es)**: master

**TDB version**:  703.00

**Bountysource**
https://www.bountysource.com/issues/37569917-7-x-creature-scaling-system
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=37569917)](https://www.bountysource.com/issues/37569917-7-x-creature-scaling-system?utm_source=37569917&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Seyden** [comment]
Not all creatures.. has to be a special flag for it

**Comment by Nelidon** [comment]
We need to rewrite the damage/stats system.

**Comment by LuigiElleBalotta** [comment]
There should be the player scaling system too, for example for timewalk dungeons

**Comment by Nelidon** [comment]
This is not the same system.
On Legion the world is scaling with the each player.

**Comment by Traesh** [comment]
You're sure about the itemlevel part ?

For the groups with differents levels, i suppose it's calculated in percent.

Player 1, level 100, see creature level 100 (10.000 hp)
Player 2, level 110, see creature level 100 (100.000 hp)

Player 1 hit mob for 1000 dmg, new mob % is 90%
Player 1 will see creature with 9000 hp
Player 2 will see creature with 90.000 hp

That's how i imagine it, and it seems to be fully compatible with what i observed while playing on officials.

**Comment by Nelidon** [comment]
I never heard that the world is scaling depending of your ilevel.
It's calculated only with the player level.
There is some updatefields related to the unit scaling that we should probably use.

**Comment by funjoker** [comment]
It's a question i read about it in Blizz forum.

**Comment by Shauren** [comment]
Item level scaling is a myth, only level scaling exists

**Comment by callmephil** [comment]
player of the same faction does not require to be grouped to kill the same mob.
some mobs health scale depending on the amount of player on it they are not affected by faction and killing them reward every player who's in combat with. (Scaling appear to be a health multiplication (of original hp) x (number of players on mob)

**Comment by ChazyTheBest** [comment]
The health scaling is only for rares and quest mobs. Rares are not affected by faction, but quest mobs are.

Some mobs, like the ones from world quests are lvl 110 and don't downscale (that's what I saw multiple times while leveling). Also, the Sea Skrogs are elites 110 and do not downscale. There may be more.

**Comment by funjoker** [comment]
Well i think elite and suramar mobs don't scale. But there will be definetly a flag for scaling

**Comment by Eredar** [comment]
Any updates? 
I found few packets in sniffs, that obviously related to this issue.

For example last strings in ServerToClient: SMSG_ATTACKER_STATE_UPDATE packet:
HasSandboxScaling: True
(AttackRoundInfo) (SandboxScalingData) Type: 4
(AttackRoundInfo) (SandboxScalingData) TargetLevel: 110
(AttackRoundInfo) (SandboxScalingData) Expansion: 6
(AttackRoundInfo) (SandboxScalingData) Class: 2
(AttackRoundInfo) (SandboxScalingData) TargetMinScalingLevel: 98
(AttackRoundInfo) (SandboxScalingData) TargetMaxScalingLevel: 110
(AttackRoundInfo) (SandboxScalingData) PlayerLevelDelta: 2
(AttackRoundInfo) (SandboxScalingData) TargetScalingLevelDelta: 0

SMSG_SPELL_NON_MELEE_DAMAGE_LOG
HasSandboxScaling: True
(SandboxScalingData) Type: 96
(SandboxScalingData) TargetLevel: 3
(SandboxScalingData) Expansion: 0
(SandboxScalingData) Class: 110
(SandboxScalingData) TargetMinScalingLevel: 6
(SandboxScalingData) TargetMaxScalingLevel: 2
(SandboxScalingData) PlayerLevelDelta: 28258
(SandboxScalingData) TargetScalingLevelDelta: 0

SMSG_AURA_UPDATE
HasSandboxScaling: True
(SandboxScalingData) Type: 3
(SandboxScalingData) PlayerLevelDelta: 0
(SandboxScalingData) TargetLevel: 110
(SandboxScalingData) Expansion: 6
(SandboxScalingData) Class: 1
(SandboxScalingData) TargetMinScalingLevel: 98
(SandboxScalingData) TargetMaxScalingLevel: 110
(SandboxScalingData) TargetScalingLevelDelta: 0

SMSG_SPELL_PERIODIC_AURA_LOG
(PeriodicAuraLogEffectData) HasSandboxScaling: True
(PeriodicAuraLogEffectData) (SandboxScalingData) Type: 96
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetLevel: 3
(PeriodicAuraLogEffectData) (SandboxScalingData) Expansion: 0
(PeriodicAuraLogEffectData) (SandboxScalingData) Class: 110
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetMinScalingLevel: 6
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetMaxScalingLevel: 2
(PeriodicAuraLogEffectData) (SandboxScalingData) PlayerLevelDelta: 28258
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetScalingLevelDelta: 0

**Comment by funjoker** [comment]
Well the sniff is not properly parsed (wrong structure).

```
SMSG_SPELL_NON_MELEE_DAMAGE_LOG
...
(SandboxScalingData) TargetMinScalingLevel: 6 <--- How can be MinLevel higher than max?
(SandboxScalingData) TargetMaxScalingLevel: 2 <---How can be MaxLevel lower than min?
...
```

```
SMSG_SPELL_PERIODIC_AURA_LOG
...
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetMinScalingLevel: 6 <--- How can be MinLevel higher than max?
(PeriodicAuraLogEffectData) (SandboxScalingData) TargetMaxScalingLevel: 2 <---How can be MaxLevel lower than min?
...
```

SMSG_SPELL_PERIODIC_AURA_LOG
SMSG_SPELL_NON_MELEE_DAMAGE_LOG

both need a update :D

**Comment by soulfrost** [comment]
```
ServerToClient: SMSG_SPELL_PERIODIC_AURA_LOG (0x2C1B) Length: 61 ConnIdx: 0 Time: 12/22/2016 12:52:27.155 Number: 34938
TargetGUID: Full: 0x081E2400000000000000000007FB3967; HighType: Player; Low: 133904743; Map: 0
CasterGUID: Full: 0x081E2400000000000000000005A91477; HighType: Player; Low: 94966903; Map: 0
SpellID: 207386 (207386)
PeriodicAuraLogEffectCount: 1
[0] Effect: SPELL_EFFECT_POWER_DRAIN (8)
[0] Amount: 13501
[0] OverHealOrKill: 13501
[0] SchoolMaskOrPower: 0
[0] AbsorbedOrAmplitude: 0
[0] Resisted: 0
[0] Crit: True
[0] HasPeriodicAuraLogEffectDebugInfo: False
[0] HasPlayerStatsInfo: True
(Sandbox) [0] Type: 4
(Sandbox) [0] PlayerLevelDelta: 0
(Sandbox) [0] TargetLevel: 110
(Sandbox) [0] Expansion: 0
(Sandbox) [0] Class: None (0)
(Sandbox) [0] TargetMinScalingLevel: 0
(Sandbox) [0] TargetMaxScalingLevel: 0
(Sandbox) [0] TargetScalingLevelDelta: 0
HasLogData: False
```

**Comment by funjoker** [comment]
Bounty has been increased to 100$

**Comment by Eredar** [comment]
I tryed to find out something interesting in sniffs and looks like almost every Legion npc has actual level of 110.  So server sends fake SMSG_VIGNETTE_UPDATE(not 100% sure) data to fake actual npc level.
For example:
[4] OBJECT_FIELD_ENTRY: 110534/1.548911E-40
[4] UNIT_FIELD_LEVEL: 110/1.541428E-43
[4] UNIT_FIELD_SCALING_LEVEL_MIN: 98/1.373272E-43
[4] UNIT_FIELD_SCALING_LEVEL_MAX: 110/1.541428E-43

Not sure if last two strings even handled on trinity, since the data for them should be taken from different column than min-maxlevel of creature_template.

So every player that above SCALING_LEVEL_MIN and below SCALING_LEVEL_MAX  will get spell and damage modifiers depending on their level. Maybe SMSG_SET_PCT_SPELL_MODIFIER do it. Not sure.

Also I found that scaling depends on player expirience. While you have below 50% exp of the current level, npcs will be your level minus one, and when you will go above 50% it will instantly update them for your current level.

**Comment by Traesh** [comment]
@Eredar So you were by example lvl 95, and still received "UNIT_FIELD_LEVEL: 110" ?

**Comment by Eredar** [comment]
@Traesh I was level 103 when got these results.

**Comment by Eredar** [comment]
I guess visual part (fake level and hp display clientside) should be easy to implement, because I saw it made on few realms that don't even have properly working legion quests. So maybe "fake" part with level and hp is handled completly clientside with sending proper scaling type and minmax scaling levels at UPDATE packet? It could explain why blizzard moved hp data to the client. So client will make target looking equal to player's level. And only damage out/input is handled serverside where modifiers described above making all the work.

**Comment by Eredar** [comment]
Also itemlevel scaling that @Shauren claimed as a myth, is not a myth at all. It exists in Proving Grounds. Mobs scale their stats depending on equipped itemlevel.

**Comment by Traesh** [comment]
It has maybe changed but in mop, proving ground reduced the player item level, npc didn't scale to it.

Visual is indeed handled client side, just have to add MIN/MAX_SCALING in update_object.

For creature taking damage, all creatures are created at max level internally, so it just require add (GetMaxHealth() / getMaxHealthForTarget(target))% to your damage if you are lower than creature max level

For creature damages, i suppose it require to store creature_classlevelstats in a map by level, and use the correct one depending of the player level

**Comment by Eredar** [comment]
And what about damage logs? On retail I saw level 100 that did more dps than level 110, so it sends data with modifiers to other players, and without them to the player himself.

**Comment by funjoker** [comment]
And remember the DELTALEVEL :D

**Comment by Seyden** [comment]
@Traesh god no..

you just have to upscale the damage for the specific level.. just change the level calculation and thats it..

i'm nearly finished with the system..

**Comment by Shauren** [comment]
@Eredar proving grounds use a completely different scaling mechanic, not related to what this issue is about

**Comment by Traesh** [comment]
@Seyden How do you handle the combat logs ?

**Comment by Seyden** [comment]
@Traesh  whats the problem about the combat logs? there are different types if player, pet etc.

**Comment by funjoker** [comment]
Reopen until:

https://github.com/TrinityCore/TrinityCore/commit/567590248592494adabd0ffa8cbb3c9daed983f4#commitcomment-23374328

And Mitigation is fixed
