### ISSUE TITLE
Typo in 2016_09_02_03_world.sql

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17896]
Typo in Line 6

I changed from "MODIFY COLUMN" to "MODIFY COLUMNS"
```sql
ALTER TABLE `smart_scripts` MODIFY COLUMNS `event_flags` SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';
```
TrinityCore rev. bc4b4f656cda 2016-09-04 07:09:04 -0300 (335 branch)

**Comment by tkrokli** [comment]
You have not provided any error message, info about what kind of error you get with the existing source.
Could you please add the current behaviour that seems to be a problem?
`MODIFY COLUMN` has been used a lot before in the current source, why should it not work?

**Comment by Tauriella** [comment]
I have a MySQL error in Line 6
ALTER TABLE `smart_scripts` MODIFY COLUMN `event_flags` SMALLINT(3) UNSIGNED NOT NULL DEFAULT '0';

Error message: Syntax error unexpected 'SMALLINT' (smallint)

**Comment by tkrokli** [comment]
OK, I see. Do you get the error message in DBErrors.log and in Server.log / console too? Or do you see it later, after you have logged in to the game?

**Comment by DDuarte** [comment]
MySQL version?

**Comment by Tauriella** [comment]
lol
You can Close this Issue COLUM ist correct :+1:  but i Think MySQL have a Little Bug
If i load the 2016_09_02_03_world.sql gives one error in Line 6 but i load this in the DB no error all is fine

**Comment by Tauriella** [comment]
Version is MySQL 6.2.4

**Comment by Tauriella** [comment]
Invalid-Intended/WontFix/Blizzlike

:+1:

**Comment by Tauriella** [comment]
@tkrokli 
Ashes on my head  sorry for your investigate timetime :+1:
