### ISSUE TITLE
Free Your Mind

### ISSUE THREAD

**Issue by BlackangelWow** [TrinityCore/TrinityCore#17897]
Free Your Mind Quest - is not working well + The npcs are just lying on the floor without any moving

When you Use sovereign-rod , Nothing happen 

When you Use sovereign-rod , it Should turned them to friendly (and get quest credit) 

**Steps to reproduce the problem**:

1. Get Level 80 (Optional)
2. Start the chain quest of Its all fun and games (Kill the big eye)
3. Get the Quest "Free Your Mind" Try to use sovereign-rod on one of the NPCs

Related Links
http://www.wowhead.com/item=41366/sovereign-rod
http://www.wowhead.com/npc=29769/vile
http://www.wowhead.com/npc=29770/lady-nightswood
http://www.wowhead.com/npc=29840/the-leaper

TrinityCore rev. daabb40ab853+ 2016-08-25 02:25:16 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by Aokromes** [comment]
#17624
