### ISSUE TITLE
[3.3.5][Crash] GetCurrentMovementGeneratorType

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#17895]
Description:
https://gist.github.com/Ghost-R/92151f2228d724c62b78b0624fcc9b7b

Current behaviour: 
When gunship finish and ship start move to boss 4 server crash

Branch(es): 3.3.5
TC hash/commit:  c0de28b

Operating system: 
Debian 64bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
useless crashlog, compile on debug mode.
https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672

**Comment by Ghost-R** [comment]
I use this, witch part most be change ?
`mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/TC/Core -DLIBSDIR=/TC/lib -DCONF_DIR=/TC/etc -DWITH_WARNINGS=1 -DCMAKE_C_FLAGS="-march=native -O2 -ggdb -pipe -D_LARGEFILE_SOURCE -frename-registers -fno-strict-aliasing -fno-strength-reduce -fno-delete-null-pointer-checks -finput-charset=utf-8 -fexec-charset=utf-8 -D_FILE_OFFSET_BITS=64"`

**Comment by Aokromes** [comment]
-O2 to -O1 or -O0

**Comment by Ghost-R** [comment]
How match process & memory usage will be change ?

**Comment by Aokromes** [comment]
idk, but crashlog without -O1 or -O0 are useless.

**Comment by r00ty-tc** [comment]
There's surely no problem. If you can repeat the crash, compile that way make crash, collect debug log, compile normal. ???? Profit.

**Comment by jackpoz** [comment]
I did the ICC Gunship Battle from Alliance side with https://github.com/TrinityCore/TrinityCore/commit/38f8a03781d98388408f7d4d9f906c311d21bdcc some days ago (revision previous than the reported crash one) and it didn't crash.

**Comment by Ghost-R** [comment]
@Aokromes , @jackpoz I will be close this, when I have better log I will be open new issues.
