### ISSUE TITLE
[3.3.5] Encounter is in progress after wipe from Thaddius.

### ISSUE THREAD

**Issue by tomlevy** [TrinityCore/TrinityCore#17894]
After getting wipe from Thaddius himself (NOT Stalagg or Feugen) you stuck outside Naxxramas with the error "Encounter is in progress".

3.3.5 0d2ef2ac7155cedead2c7a7cafcd937a4e1dcd99

**Comment by Aokromes** [comment]
#6756

**Comment by Aokromes** [comment]
#6756

**Comment by Rushor** [comment]
actually this is because the encounter is not set to not_started after a wipe. just a missing call in the reset functions of the encounter
