### ISSUE TITLE
Scripts: Interruped spells are not recasted

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17892]
**Description**: A boss has 2 spells: A and B, this 2 spells are important if they are not casted the encounter cannot be done.
The boss is casting the spell A almost all time, then after 1 min it must it cast Spell B that was scheduled at T time, at this moment T the boss was casting the spell A so the spell B was "ignored". In this case the spell B must be rescheduled to be cast as soon as possible. But actually it's not the case in many Boss scripts.

**Steps to reproduce the problem**:

1. .go c id 33350
2. Start Mimiron hard mode
3. Wait one minute for http://www.wowhead.com/spell=64570/flame-suppressant
4. At 90% the spell will not be casted

This issue is affecting a lot of Boss scripts.
```
<Treeston> if (me->HasUnitState(UNIT_STATE_CASTING))
<Treeston> return;
<Treeston> should be in the loop
<Treeston> not outside
<Treeston> while (uint32 eventId = events.ExecuteEvent())
<Treeston> {
<Treeston> if (me->HasUnitState
<Treeston> etc
<Treeston> afk now, exam
<ariel-> yes, there are many UpdateAI loops that do like that
<ariel-> it's plain wrong
<ariel-> also if you move check inside the while, the event will be "executed" that is, removed from eventMap
<ariel-> and never scheduled again
<ariel-> the way it is now npc stops casting to cast another thing
<ariel-> while loop should be removed entirely, it's no visible difference executing an event on the same update tick or on the next one
```

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  rev. be8d1136994f

**TDB version**:  3.3.5

**Comment by lukaasm** [comment]
something similar to spellcast queue "we" did in TBC times would be usefull I believe( it handles all that casting stuff, user all needs to do is add spell to queue )

https://bitbucket.org/lukaasm/hellground-wowemu/src/5892e38541d0e0552fdec81f969e8de22d694842/src/scripts/include/sc_creature.cpp?fileviewer=file-view-default#sc_creature.cpp-334

some cleanup & refactoring done by someone and would be good to go :p

**Comment by Ovahlord** [comment]
Sounds to me more like bad AI coding instead of a core bug. If spells are scheduled properly they shouldn't cause such issues.

**Comment by Treeston** [comment]
Confirmed, bad AI coding.
