### ISSUE TITLE
Error D8040 in 32 Bit

### ISSUE THREAD

**Issue by Nightprince** [TrinityCore/TrinityCore#17901]
Hi , In Windows 32-bit when compiling have 1 error D8040 :

2>cl : Command line error D8040: error creating or communicating with child process

**Branch(es)** : 6.x / 7.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/10b683cf96383b730a235994366abafa60867558

**TDB version**:   TDB 6.04

**Operating system**:  Win 10 & 8.1

**Comment by Aokromes** [comment]
1- Disable c/c++->general->Multi-processor compilation
2- Disable c/c++->general->optimization
3- Disable c/c++->language->open mp support

**Comment by jackpoz** [comment]
>cl : Command line error D8040: error creating or communicating with child process

this is a Visual Studio error unrelated to the code itself and should be managed on the Help section of the forum or on irc as generic help.
