### ISSUE TITLE
Scripts: Mimiron - Flame Suppressant

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17902]
**Description**: After this commit: https://github.com/TrinityCore/TrinityCore/commit/ac62d7156f93bf86f57dbad1f24f14031322fd5a  this issue must be fixed: https://github.com/TrinityCore/TrinityCore/issues/17892
But it still happen with Flame Suppressant during Mimiron HM encounter. (And probably other boss)
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp#L880
With this change: DoCastAOE(SPELL_FLAME_SUPPRESSANT_MK, true); the spell is casted, but it's a hack.

**Current behaviour**: On Mimiron HM encounter Flame Suppressant must be casted every 1min, but actually it doesn't.

**Expected behaviour**: Flame Suppressant must be rescheduled if there's an other spell during the cast time.

**Steps to reproduce the problem**:

1. .go c id 33350
2.  Start the hard mode
3. Wait 1min

**Branch(es)**: 3.3.5

**TC hash/commit**:  TrinityCore rev. 932d31598d69

**Comment by Keader** [comment]
#15838
The problem is: Another spell is casted, and when suppressant event is called, still has "gcd".
something need re-scheduler events when this happens.
In mimiron case, somes trigger-cast solve, but a generic solution will be nice ^^
