### ISSUE TITLE
[7.x] Artifact Knowledge

### ISSUE THREAD

**Issue by cybrann** [TrinityCore/TrinityCore#17907]
**Description**:
Artifact knowledge bug

**Current behaviour**: Tell us what happens
Artifact knowledge bug does not increase artifact power gain from items

**Expected behaviour**: Tell us what should happen instead
Artifact knowledge should increase artifact power gain from items by:
Level: 1 - 25%
Level: 2 - 50%
Level: 3 - 90%
Level: 4 - 140%
Level: 5 - 200%
Level: 6 - 275%
Level: 7 - 375%
Level: 8 - 500%
Level: 9 - 650%
Level: 10 - 850%
Level: 11 - 1100%
Level: 12 - 1400%
Level: 13 - 1775%
Level: 14 - 2250%
Level: 15 - 2850%
Level: 16 - 3600%
Level: 17 - 4550%
Level: 18 - 5700%
Level: 19 - 7200%
Level: 20 - 9000%
Level: 21 - 11300%
Level: 22 - 14200%
Level: 23 - 17800%
Level: 24 - 22300%
Level: 25 - 24900%

Data was taken from wowhead.com

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 6.x  

**TC hash/commit**:  Latest commit

**TDB version**:  Latest database version

**Operating system**:  Windows 7 x64 Ultimate

**Comment by Shauren** [comment]
Working as intended, use some http://www.wowhead.com/item=139390/artifact-research-notes, then add item giving artifact power that scales with knowledge level such as http://www.wowhead.com/item=141889/glory-of-the-melee

**Comment by cybrann** [comment]
I did do that with the http://www.wowhead.com/item=139506/greater-glory-of-the-order and it did not work, I can provide video if needed.
