### ISSUE TITLE
[3.3.5] access_requirement

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#17915]
Description:
I know trinitycore team don't accept not blizzlike but tc have problem in access_requirement
I add achievement 4530 for enter instance The Ruby Sanctum, problem is when player try to enter this instance have error "You must be level 80 and in a raid group to enter" not

**Steps to reproduce the problem**:
1. Add achievement 4530 to access_requirement for mapId 724
2. Try to enter to instance

**Branch(es)**:
3.3.5

**TC hash/commit**:  
TC hash/commit:  c0de28b

**TDB version**:  
TDB 335.61

**Operating system**:  
Debian 64Bir

**Comment by Aokromes** [comment]
this belongs to forum on custom section.
