### ISSUE TITLE
[7.x] Druid Feral Shred Ability

### ISSUE THREAD

**Issue by jcmillions** [TrinityCore/TrinityCore#17913]
Description: Player does not start with [Shred](http://www.wowhead.com/spell=5221/shred).

Current behaviour: Player does not start with spell shred

Expected behaviour: Player should start with spell shred

Steps to reproduce the problem:

1. Make a druid
2. Login
3. Notice that the spell is not learned upon character creation

Branch: 7.x

**TC hash/commit**:  

TDB version:  Latest

Operating system:  Win 7 Ultimate x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by cybrann** [comment]
This isn't just druid problem. Demon Hunter does not learn any spells at all upon leveling up. I know some are bugged because they are gained trough starting quests, but not all of them are.

**Comment by jcmillions** [comment]
They may fix the Demon Hunter spells at the same time as the quests. I mean it would make sense

**Comment by Shauren** [comment]
As you said, demon hunters are special because they gain spells from quests
This issue (and for all other classes) is caused by starting in wrong spec
