### ISSUE TITLE
[7.x] Invalid target map or coordinates

### ISSUE THREAD

**Issue by searum** [TrinityCore/TrinityCore#17919]
If you try to go inside a new dungeon or raid will receive an error message: Invalid target map or coordinates.

Command with coords i tried:

.go xyz 2793.01 1669.81 -39.9529 1458

TC and TDB Last rev.

**Comment by DDuarte** [comment]
Does that map have an entry in instance_templates and related tables?

**Comment by MitchesD** [comment]
I think it happens when it has no valid entrance/exit in database, possibly also instance template as Nayd said

**Comment by searum** [comment]
Ok! i will look on it and report if still the issue, thank you for answers.

**Comment by DDuarte** [comment]
Publish the fix

**Comment by searum** [comment]
DELETE FROM `instance_template` WHERE `map` IN (1456, 1458, 1466, 1477, 1501, 1516, 1544, 1554, 1462, 1475, 1498, 1533, 1492, 1493);
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES
(1456, 0, '', 0),
(1458, 0, '', 0),
(1466, 0, '', 0),
(1477, 0, '', 0),
(1501, 0, '', 0),
(1516, 0, '', 0),
(1544, 0, '', 0),
(1554, 0, '', 0),
(1462, 0, '', 0),
(1475, 0, '', 0),
(1492, 0, '', 0),
(1493, 0, '', 0),
(1533, 0, '', 0),
(1498, 0, '', 0);

**Comment by Goten87** [comment]
so sins its a 7.x bug i can say you are on legion update ?

**Comment by tkrokli** [comment]
@Goten87 : the 6.x branch is meant to match the current retail client (check version info in the source).
The branch has not been renamed yet to something more generic, like 'master'. When? Soon™.
