### ISSUE TITLE
Spell: Missile Barrage, Hot Streak and Brain Freeze are not consummed properly

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#17925]
**Description**: Missile Barrage, Hot Streak and Brain Freeze are not consummed properly on cast

**Current behaviour**: Since the change to those two spells, it is now possible to beneficiate from the proc multiple time by casting a spell at good distance. This is due to the addition of a spell proc event to those spells, since we don't drop charge for spell mod if there is a spell proc event.

**Expected behaviour**: The spell mod should be removed on cast, not on hit, like it was before

**Steps to reproduce the problem**:

1. Stay at good distance of the target
2. Have your mage with Hot Streak or Brain Freeze on
3. Cast spells consecutively

**Branch(es)**: 3.3.5 (dunno if those talents exist in 6.0)

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/81ec57b94f2ded0504a3d4755d6cc410c93597ff

**Comment by joshwhedon** [comment]
PS: I don't know if this is a temporary issue introduced while the proc system is being rewritten, or if it is just an oversight.

**Comment by Keader** [comment]
Same problem? #15605

**Comment by joshwhedon** [comment]
Not really the same no. This is not lag related, this is logic related. Previously, the aura was removed at the point where the spell was casted. Now, it is removed on hit, therefore missiles are a problem.

**Comment by Ovahlord** [comment]
Missing linked spell due to changed spell id's. Thats it.

**Comment by joshwhedon** [comment]
No that's not it. If you handle this via spell_linked_spell, then the talent fix made in https://github.com/TrinityCore/TrinityCore/commit/81ec57b94f2ded0504a3d4755d6cc410c93597ff will not work anymore, since it will not proc (as it will be removed before the spell hit).
Additionally, spell mod are not handled via spell linked spell.

**Comment by ariel-** [comment]
> PS: I don't know if this is a temporary issue introduced while the proc system is being rewritten, or if it is just an oversight. 

No, this bug was present from before... see #15942 ... incidentally Hot Streak is mentioned there.

But yes, use of QAston proc system will surely close both issues.
