### ISSUE TITLE
[7.x] Harvest Festival Horde Spawn

### ISSUE THREAD

**Issue by Vincent-Michael** [TrinityCore/TrinityCore#17928]
https://gist.github.com/Vincent-Michael/e3b5d3a27cdf2fbf78be5fe1846fec71

**Branch(es)**:  6.x

**TC hash/commit**:  10cdff2329f3ba9ba49c84d95d22fec461f83a9a

**TDB version**: 6.04

**Operating system**:  Windows 10 Pro

**Comment by Aokromes** [comment]
4552f64
