### ISSUE TITLE
[3.3.5] A Spark of Hope (12956)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#17927]
**Description**:
This Quest gives wrong Reputation XP's 250 is to low noraml is 22,000
It is important for the QuestChain

http://www.wowhead.com/quest=12956/a-spark-of-hope

**Branch(es)**: 3.3.5 / 6.x 
**TC hash/commit**:  
TC>TrinityCore rev. 62cffd11d0e9 2016-09-09 17:14:34 +0200 (335 branch)

**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql - 2016_09_09_02_world.sql
**Operating system**:  
Win7 64Bit

**Comment by Silvertower** [comment]
The TDB is incorrect for the following two quests:

http://www.wowhead.com/quest=12956/a-spark-of-hope should provide 22,000 reputation with Sons of Hodir; it incorrectly provides 250 reputation.

http://www.wowhead.com/quest=12924/forging-an-alliance should provide 250 reputation with Sons of Hodir; it incorrectly provides 22,000 reputation.

Fix (verified against wotlk.openwow.com and www.wowhead.com):

`
UPDATE `quest_template` SET `RewardFactionOverride1` = 0 WHERE `ID` = 12924;
UPDATE `quest_template` SET `RewardFactionOverride1` = 2200000 WHERE `ID` = 12956;
`

Note that setting RewardFactionOverride1 to 0 will cause the quest to reward experience based on the value of RewardFactionValue1.
