### ISSUE TITLE
[Spell/Talent] Mind Spike

### ISSUE THREAD

**Issue by nerv234** [TrinityCore/TrinityCore#17924]
**Description**: If you cast on Mind Spike it acts like it is Mind Flay

**Current behaviour**:  If you cast on Mind Spike it acts like it is Mind Flay

**Expected behaviour**:  If you cast on Mind Spike it acts like it is Mind Spike

**Steps to reproduce the problem**:
1. Create priest
2. Get talent Mind Spike
3. Cast Mind Spike by clicking on it on action bar.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  4bbe091ffb736ed98b64494272e92e65d9ecb5fd

**TDB version**:  Latest

**Operating system**:  Win 7

More info: Mind Spike doesn't have aura that overrides spell serverside (like other of talents with "replaces" have. Maybe in some packets it contains info about overriden spell id.
Btw. Clientside spell is overriden.

**Comment by aquadeus** [comment]
this spell was removed in legion?
