### ISSUE TITLE
[3.3.5] Skadi the Ruthless evade issue

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17935]
3.3.5 5d87e4a

Skadi the Ruthless immediately evades after the encounter begins. This is due to the player not having aura 47546 applied to them properly.

Adding the aura manually (using .aura 47546) makes the encounter perform as expected.

@sirikfoll

**Comment by sirikfoll** [comment]
Are you sure? '-'
Any repro steps?
Works for me in  b125a3fd2c96

**Comment by Treeston** [comment]
1. .tele utgardepinnacle
2. zone in (5-man heroic)
3. kill first room trash, then corridor trash
4. start svala event, wait for it to complete, then kill svala
5. kill staircase trash
6. kill trophy hall trash pack
7. enter eagle's eye
8. walk up to skadi to start the encounter
9. a few seconds after taking off, skadi despawns and the encounter resets
10. here, I tried .unaura all, then relogging to make sure there is no persistent aura in play
11. repeat of 9.
![wowscrnshot_091316_113043](https://cloud.githubusercontent.com/assets/14020072/18468739/9760263a-79a5-11e6-9de7-6fae413d7e35.jpg)
![wowscrnshot_091316_113046](https://cloud.githubusercontent.com/assets/14020072/18468745/9ac1ccf2-79a5-11e6-8e58-1edc27f741a3.jpg)

**Comment by shenhuyong** [comment]
The gender of spell 47546 in spell_area is 0, female player can not autocast this spell, then it only works for male players, change the gender to 2 can fix it.

**Comment by Treeston** [comment]
Oops, @sirikfoll

**Comment by Keader** [comment]
Hmm maybe its a cause that he cant reproduce

**Comment by sirikfoll** [comment]
@shenhuyong Nice finding, it's indeed the cause, thanks for noticing! 👍 
The fix:
```sql
UPDATE `spell_area` SET `gender`=2 WHERE `spell`=47546;
