### ISSUE TITLE
Cmake Errors

### ISSUE THREAD

**Issue by piccolodmq** [TrinityCore/TrinityCore#17938]
** CMAKE problems when compiling **

**I followed this guide https://trinitycore.atlassian.net/wiki/display/tc/Installation+Guide with no problems until the point where I have tu USe Cmake 3.4.6 and setup the Source Code and Build Binaries to configure and generate the compiled version and get errors**: 
**I should get a red screen in Cmake where I have to select the Tools check box and then select genereate to get the build**: 

**Septes taken **:

1. First I select Cmake
2. Select the sourcode location C:/ trinity
3. Where to build binaries C:/Build
4. I get to choose what generator to use: Choose Visual Studio 14 2015 Win64. 
4. Get this error and scren instead.
https://drive.google.com/file/d/0B8x...ew?usp=sharing

**3.3.5 Branch(es)**:

**TC hash/commit**:  

**TDB version**:  

** Windows server2012R2**:  
** 

Thanks for your help!

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
This belongs to forum, not to tracker.
