### ISSUE TITLE
[7.x] Power combo points

### ISSUE THREAD

**Issue by MelissaLeb** [TrinityCore/TrinityCore#17936]
**Description**: We can't get some combo points with the rogue

**Current behaviour**: When i try some spells to get some combo points, we don't get it

**Expected behaviour**: We should get some combo points after we uses some spells

**Branch(es)**: 6.x 

**TC hash/commit**:  42f2b3525cc2ce810d17b9c258370ec5933838b6

**TDB version**:  6.x

**Operating system**:  windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by LuigiElleBalotta** [comment]
It should be an opcode i think
