### ISSUE TITLE
Creature: Kologarn with wrong orientation

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#17933]
**Description**: Kologarn has a wrong orientation

**Current behaviour**: He is "looking" for "inside" of Ulduar

**Expected behaviour**: He should  "looking" of the door direction

**Steps to reproduce the problem**:

1. .go crea id 32930

![image](https://cloud.githubusercontent.com/assets/7120913/18420119/acbc3d1c-7841-11e6-9499-bf685856ecd0.png)

**Branch(es)**: 3.3.5

**TC hash/commit**:  12a6ade3eec67f28efe570380d6ce926cf4c0962

**TDB version**:  335.61

**Operating system**:  win10

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17234
