### ISSUE TITLE
Spell: States from auras are not cleared after death, respawn or reset

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#17931]
**Description**:
Emote states like death are not cleared after death, respawn or reset.

**Steps to reproduce the problem**:
1.  Find any npcs
2.  .cast self 29266
3.  .die .resp
4. The emote state for this npc will change to dead (the npc doesn't have the aura after respawn)

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  rev. be8d1136994f

**TDB version**:  3.3.5

**Comment by Treeston** [comment]
Will be fixed with dynspawn anyway.

**Comment by Killyana** [comment]
Fixed somehow.

**Comment by ariel-** [comment]
Fixed in 256d07f26f682a436f1c96f277309e1c76a2316a
