### ISSUE TITLE
Core/Battle.net: FailedLogin not used

### ISSUE THREAD

**Issue by joschiwald** [TrinityCore/TrinityCore#17937]
**Description**: The FailedLogins function is not used in bnetserver.

**Current behaviour**: You can enter wrong password until you guessed the right one. You never get banned by bnetserver.

**Expected behaviour**: After you entered a wrong password serveral times, you get banned by bnetserver (like authserver).

**Steps to reproduce the problem**:

1. Login with wrong password.
2. Login with wrong password.
3. Login with wrong password.

**Branch(es)**: 6.x

**TC hash/commit**:  42f2b3525cc2ce810d17b9c258370ec5933838b6

**TDB version**:  6.04

**Operating system**:  Ubuntu 16.04

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Nelidon** [comment]
Before adding new feature I think the bnetserver should be reworked to improve current performances.
https://github.com/TrinityCore/TrinityCore/issues/17841
You will just adding more queries to execute, it won't help.

**Comment by Aokromes** [comment]
it's not add new feature, it's fix broken feature.
