### ISSUE TITLE
[7.x] Flying NPCs (but spawns were taken from sniff)

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#17947]
**Description**: NPCs spawned by sniff are flying (but not on retail). Tested Dalaran (broken isles) zone.

**Current behaviour**: Tell us what happens
NPCs should be on the ground

**Expected behaviour**: Tell us what should happen instead
NPCs are flying.

**Steps to reproduce the problem**:

1. Get these spawns: https://paste.ee/p/ahevQ
2. Execute the query
3. Execute this query: INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES (1575, -828.347, 4371.34, 738.632, 1.77166, 1220, 'newdalaran');
4. Go ingame and do this command: .tele newdalaran
4. See with your eyes
![wowscrnshot_091516_134429](https://cloud.githubusercontent.com/assets/16773213/18548870/63c44962-7b4b-11e6-9dca-b58a20508198.jpg)

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
6.x

**TC hash/commit**:  
https://github.com/TrinityCore/TrinityCore/commit/ac7fccb54dd0d47c6064ddea43899066c8fc1709

**TDB version**:  
6.04

**Operating system**:  
Windows 10 / Mac OS X Yosemite

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Shauren** [comment]
Not a bug. Look closely at your `creature_template` INSERT queries, you are adding data with `InhabitType`=0 which is NOT a valid value. You should read startup errors before reporting issues.
This validation https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Globals/ObjectMgr.cpp#L921 sets all invalid values to INHABIT_ANYWHERE, allowing them to fly.

**Comment by LuigiElleBalotta** [comment]
Probably it was to 0 because there where values marked as UNKNOWN so I replaced UNKNOWN with 0.. But why the parser put "UNKNOWN"? How and where can this be fixed? @Shauren

**Comment by Krudor** [comment]
0 is a valid value for some columns. If you don't know a value for a column, defaulting to 0 is bad practise.
Setting it to something like UNKNOWN rightfully produces an error down the line so that it can be dealt with, even though it might not be user friendly.
