### ISSUE TITLE
[3.3.5] Quest: Heated Battle (12416)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17957]
3.3.5 f2067d3557ccd7595f15cf526d81d2f19911cf3c

[Quest: Heated Battle](http://www.wowhead.com/quest=12416/heated-battle)

There are practically no [Frigid Geist Attacker](http://www.wowhead.com/npc=27686/frigid-geist-attacker)s being spawned in the quest area. What few there are are hidden in side passages and don't charge into the blockade like the other creatures.

Could use a re-sniff on spawns, probably? Really really frustrating to complete right now.

**Comment by malcrom** [comment]
I just did this quest today. These are scripted spawns.

**Comment by dr-j** [comment]
well looked into this the other day these mobs come from two sources they come up out of the ground by where guards kill them and also come running the passages from shrine to guards with the occasional abomination.

**Comment by Aokromes** [comment]
this issue is still valid?
