### ISSUE TITLE
[7.x] Spell visuals

### ISSUE THREAD

**Issue by cocolino** [TrinityCore/TrinityCore#17950]
**Description**: Basic spells like Frostbolt, Fireball etc. as well as Missile spells have no visuals when cast by NPCs.

**Current behaviour**: When cast by players all the spells have correct visuals, but no visual "missile" appears when certain spells are cast by an NPC on a player. This is only related to certain spells, as Channeled ones seem to work correctly. Actual Missile triggering spells have no visual display either.

**Expected behaviour**: You should see the "missile" traveling from the NPC and hitting the player / the location when the spell is cast.

**Steps to reproduce the problem**:

1. Go to any NPC. Either wait for it to cast the spell if it has such one (i tested on satyrs underneath old dalaran - arcane bolt or something was the spell), or use .cast target for spells like 223329 or 164080.
2. The NPC casts the spell and visually displays a cast state but nothing "comes out" of him towards the player / location :stuck_out_tongue: .
3. It seems if you cast these spells as a player the visual is displayed (in most cases anyway).
4. Also sometimes the "cast sound" remains after the NPC finishes casting a spell and you can hear it loudly until you teleport or leave the area.

**Branch(es)**: 6.x (7.x, Legion 22566).
**TC hash/commit**:  7ad7729696d704f61d3d95ba7934abca1113ac18
**Operating system**:  Win7

**Comment by searum** [comment]
SMSG_PLAY_SPELL_VISUAL NYI

**Comment by Shauren** [comment]
Ok, I know what is going on here, will fix this later today

**Comment by cocolino** [comment]
Thank you very much.

**Comment by cocolino** [comment]
@searum i am not very sure it is about SMSG_PLAY_SPELL_VISUAL, from what i know that was used back in WOD separately as a custom thing NPC's do to display certain visuals, just as SMSG_PLAY_ORPHAN_SPELL_VISUAL and SMSG_PLAY_SPELL_VISUAL_KIT were (Kargath Chain Hurl, Nyami Soul Vessel etc). It doesn't seem to have changed in Legion as handling from what i have seen or appear in data regarding simple spells such as the ones i exemplified.

**Comment by Shauren** [comment]
@cocolino none of the above.

**Comment by searum** [comment]
omg, you're a beast @Shauren xD

**Comment by Ulduar** [comment]
@cocolino 
SMSG_PLAY_SPELL_VISUAL
void Unit::SendPlaySpellVisual(uint32 id, Unit* target, float Speed, float orientation, Position pos, bool ThisAsPos /*= false*/, bool SpeedAsTime /*= false*/)
SMSG_PLAY_ORPHAN_SPELL_VISUAL
void Unit::PlayOrphanSpellVisual(G3D::Vector3 Source, G3D::Vector3 Orientation, G3D::Vector3 Target, int32 Visual, float TravelSpeed, uint64 TargetGUID, bool SpeedAsTime)
Please tell me, how add method in Unit.cpp for two opcodes? Thanks advance.

``` QUOTE
SMSG_PLAY_ORPHAN_SPELL_VISUAL and SMSG_PLAY_SPELL_VISUAL_KIT were (Kargath Chain Hurl, Nyami Soul Vessel etc). It doesn't seem to have changed in Legion as handling from what I have seen or appear in data regarding simple spells such as the ones I exemplified. I reckon Shauren has a better idea of what is going on.
```
Pol and Phemos (Highmaul), Emperor Mar-gok, Koragh also used this method. Archimage Sol too.

**Comment by Ulduar** [comment]
Any news?
@Shauren 
Need your help.
SMSG_PLAY_SPELL_VISUAL_KIT 
Need add support for duration. On current state send packet with duration = 0.

Addon:
``` CPP
void Unit::SendPlaySpellVisualKit(uint32 id, uint32 type, uint32 duration)
{
    WorldPackets::Spells::PlaySpellVisualKit playSpellVisualKit;
    playSpellVisualKit.Unit = GetGUID();
    playSpellVisualKit.KitRecID = id;        ///< SpellVisualKit.dbc index
    playSpellVisualKit.KitType = type;
    playSpellVisualKit.Duration = duration;
    SendMessageToSet(playSpellVisualKit.Write(), true);

void SendPlaySpellVisualKit(uint32 id, uint32 type, uint32 duration);
}

SMSG_PLAY_SPELL_VISUAL

``` CPP
void Unit::SendPlaySpellVisual(Unit* victim, uint32 id);
{
    WorldPackets::Spells::PlaySpellVisual playSpellVisual;
    playSpellVisual.Source = GetGUID();
    playSpellVisual.Target = victim->GetGUID();
    playSpellVisual.TargetPosition = 0.0f; // slices
    playSpellVisual.SpellVisualID = id;
    playSpellVisual.MissReason = 0;
    playSpellVisual.ReflectStatus = 0;
    playSpellVisual.Orientation = 0.0f;
    playSpellVisual.SpeedAsTime = true;
    SendMessageToSet(playSpellVisual.Write(), true);

void SendPlaySpellVisual(Unit* victim, uint32 id);
}

SMSG_PLAY_ORPHAN_SPELL_VISUAL 
NYI.

**Comment by Shauren** [comment]
Why are you randomly commenting on closed and resolved issues with unrelated code? Please stop doing that.

**Comment by Ulduar2** [comment]
@Shauren new issue created.
