### ISSUE TITLE
[3.3.5] Quest: The Liquid Fire of Elune (12166)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17958]
3.3.5 f2067d3557ccd7595f15cf526d81d2f19911cf3c

[Quest: The Liquid Fire of Elune](http://www.wowhead.com/quest=12166/the-liquid-fire-of-elune)

The [Blighted Elk](http://www.wowhead.com/npc=26616/blighted-elk) and [Rabid Grizzly](http://www.wowhead.com/npc=26643/rabid-grizzly) spawns in the primary quest area (just north of the questgiver) are _way_ too dense. I suspect they're double-spawned (if not triple-spawned).

Would love if somebody could re-sniff these spawns.

**Comment by tkrokli** [comment]
Good point, those spawns seem too dense. (I usually forget it after leaving the zone, though.)

**Comment by malcrom** [comment]
I will sniff this for you.
