### ISSUE TITLE
Honor crash

### ISSUE THREAD

**Issue by krizttian** [TrinityCore/TrinityCore#17951]
**Honor crash file player.cpp**:

if player obtain honor the server crash

File error player.cpp line 6591

CurrencyTypesEntry const* currency = sCurrencyTypesStore.LookupEntry(id);
    ASSERT(currency);

**Branch(es)**: 6.x

**TC hash/commit**:  Legión 7.0.3 22566

**Comment by Aokromes** [comment]
ignore template is evil.
#17721
