### ISSUE TITLE
[3.3.5] GameObject Location

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#17963]
**Description**:
Some GameObject have incorrect location or Client WoW Error.
Guid         Entry     Map
15662 -> 170555 (Blackrock Depths)
18197 -> 170557 (Blackrock Depths)
15335 -> 170556 (Blackrock Depths)
45164 -> 194437 (Ulduar)
76910 -> 187347 (Client Error) (ERROR #134 Fatal Condition)

**Steps to reproduce the problem**:

1. go ob 15662

Branch(es):
 3.3.5

TC hash/commit:
 c0de28b 

Operating system:
 Debian 64bit

**Comment by Kittnz** [comment]
15662 -> 170555 (Blackrock Depths)
18197 -> 170557 (Blackrock Depths)
15335 -> 170556 (Blackrock Depths)

These 3 are from sniffs, i check out 2 sniffs from different versions and they all have these coordinates.

45164 -> 194437 (Ulduar) <- this gob is even still there on retail and on old 335 sniffs
76910 -> 187347 (Client Error) (ERROR #134 Fatal Condition) <- don't have any sniff for this, but this is dev land so why bother.
