### ISSUE TITLE
DoT clipping - tick timer resets

### ISSUE THREAD

**Issue by lachtanek** [TrinityCore/TrinityCore#17961]
**Description**: So, this is kinda big issue I feel, but I didn't find any reports for it. Let me state two terms:
- DoT application/reapplication: when you manually cast the spell on target.
- DoT refresh: when the aura on target is refreshed, for example refreshing Corruption by Everlasting Affliction talent.

Now, when you apply/reapply any DoT, it should reset it's periodic timer, but that doesn't happen.
But when you refresh the DoTs that allow it, the periodic timer should stay the same.
This is an important mechanic, because right now any DoT-dependant class doesn't require that much skill to perform to its best, like affliction warlocks, shadow priests, feral druids and so on, because you could just reapply the DoT before it ends and you are not penalized for it.

Some sources about DoT clipping functionality in 3.3:
http://wow.gamepedia.com/Damage_over_Time#Discussion - last paragraph
http://www.mmo-champion.com/threads/712173-Dot-clipping
http://www.wowhead.com/forums&topic=164443/clipping-dots-as-affliction

**Current behaviour**: When you manually reapply a DoT like 1 sec before it's tick, it still ticks after 1sec.

**Expected behaviour**: The periodic timer should be reset, so it should tick after TICK_FREQUENCY seconds.

**Steps to reproduce the problem**:

1. Cast Corruption (or any DoT spell) on every GCD and it still ticks.

**Branch(es)**: 3.3.5

**TC hash/commit**:  bbc983fc3d3a525187bdcf08ea6e10e8e31e1b0b

**TDB version**:  Any

**Operating system**:  Any

**Comment by lachtanek** [comment]
Currently, the problem is probably in AuraEffect::CalculatePeriodic.
We can't just reset all periodics tho, because then it breaks everlasting affliction, deadly poison and so on, it should probably reset just for non-proc-triggered auras.

**Comment by Treeston** [comment]
Resetting on nontriggered cast sounds good.

**Comment by robinsch** [comment]
Pretty stupid to get if a aura was triggered by something in Aura class. We need to pass it all along the way to reset timers.

**Comment by Treeston** [comment]
Shouldn't the duration reset happen in spell effect logic? We have triggered flags there.

**Comment by ariel-** [comment]
@robinsch, yes, that's exactly how it's handled in SunwellCore

**Comment by Treeston** [comment]
Yes, but I don't believe we create a new `Aura` for refreshes like this.

If we did, this bug likely wouldn't exist (in its current form).

**Comment by ariel-** [comment]
Indeed, Aura is created only if it doesn't exist, that was changed a while ago: 42a20f14efd4ceede6839d7baa5ab268a06b49d4

**Comment by robinsch** [comment]
@ariel- Just check the Sunwell stuff, I'd rather save it as a bool in aura, might be usable somewhere else.

**Comment by Treeston** [comment]
Just pass `bool isTriggered` to that method and reset tick timer if it isn't triggered but existing aura is found.

**Comment by robinsch** [comment]
You need to pass it along tons of function, thats why.

**Comment by Keader** [comment]
Just for references: https://github.com/TrinityCore/TrinityCore/commit/d7a78c19302d83b72e7382593b59ba0656972c92
