### ISSUE TITLE
[3.3.5] Object: Tua'kea's Fishing Hook (188370)

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#17962]
3.3.5 f2067d3557ccd7595f15cf526d81d2f19911cf3c

Entry `188370`, spawnID `150122`. Orientation is wrong, it should be aligned with the end of the (static) rope, which is part of the map.

**Comment by Kittnz** [comment]
3.3.3a sniff:
(@OGUID+1860, 188370, 571, 0, 0, 1, 1, 0, 2651.38, 1007.243, -24.03463, -2.33874, 0, 0, -0.9205046, 0.3907318, 120, 255, 1, 11723), -- 188370 (Area: 4152)

335 sniff: 
(@OGUID+0, 188370, 571, 0, 0, 1, 1, 0, 2651.38, 1007.243, -24.03463, -2.33874, 0, 0, -0.9205046, 0.3907318, 120, 255, 1, 12340), -- 188370 (Area: 0)

434:
(@OGUID+753, 188370, 571, 0, 0, 1, 1, 0, 2651.38, 1007.243, -24.03463, 3.944446, 0, 0, -0.9205046, 0.3907318, 120, 255, 1, 15595), -- 188370 (Area: 0)

5.1 sniff:
(@OGUID+790, 188370, 571, 0, 0, 1, 1, 0, 2651.38, 1007.243, -24.03463, 3.944446, 0, 0, -0.9205046, 0.3907318, 120, 255, 1, 16357), -- 188370 (Area: 4152)

current 7.03
(@OGUID+5, 188370, 571, 0, 0, 1, 1, 0, 2651.38, 1007.243, -24.03463, 3.944446, 0, 0, -0.9205046, 0.3907318, 120, 255, 1, 22594), -- 188370 (Area: -1)

**Comment by Kittnz** [comment]
UPDATE `gameobject` SET `position_x`=2651.38, `position_y`=1007.243, `position_z`=-24.03463, `orientation`=-2.33874 WHERE  `guid`=150122;
