### ISSUE TITLE
[7.x] Client Crash on add heirlooms item

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#17964]
**Description**:Client Crash on add heirlooms item

**Current behaviour**: Client Crash  

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. .add item 128173
2. Client Crash 
3. 

**Branch(es)**: 7.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/4af16d1b24bd6bc8f6cde6b926525c0f9756ccd5

**TDB version**:  TDB 6.04

**Operating system**:  win7 x64

**Comment by Linwood-WP** [comment]
Confirmed

**Comment by Nelidon** [comment]
Same issue here: https://github.com/TrinityCore/TrinityCore/issues/17942
Dynamic values aren't build correctly.

**Comment by Pixel-Pirate** [comment]
confirmed and not only for item 128173.

**Comment by ChazyTheBest** [comment]
Confirmed, it only works if you buy the heirlooms from a vendor.
