### ISSUE TITLE
[7.x] Client Crash on add custom hotfix item

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#17965]
**Description**:Client Crash on add custom hotfix item

**Current behaviour**: Client Crash 

**Expected behaviour**:  

**Steps to reproduce the problem**:

1. create a custom hotfix item  in `hotfixdatabase`.`item` and `hotfixdatabase`.`item_sparse`
2. restart server 
3. add the new hotfix item
4. Client Crash 

**Branch(es)**: 7.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/4af16d1b24bd6bc8f6cde6b926525c0f9756ccd5

**TDB version**:  TDB 6.04

**Operating system**:  win7 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by funjoker** [comment]
Custom Hotfixes. Why should we do so ?
You know there is hash ?
