### ISSUE TITLE
Core/Scripts: Unleashed Soul does not spawn

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#17968]
Instance Forge of Souls (3.3.5)

When Devourer of Souls uses spell 68939, no Unleashed Soul (NPC 36595) spawns.
I tried with old core and DB to find the origin. That bug apparently appeared between end of July and middle of August.

(Sorry for my english)
***
(edited to show how this issue should have looked if filled in properly /~tkrokli)

**Description**:
Instance: Forge of Souls : Unleashed Souls are not released in the Devourer of Souls fight
- http://www.wowhead.com/npc=36502/devourer-of-souls
- http://www.wowhead.com/spell=68939/unleashed-souls
- http://www.wowhead.com/zone=4809/the-forge-of-souls

**Current behaviour**: Tell us what happens

Unleashed Souls are not released by the Devourer of Souls 

**Expected behaviour**: Tell us what should happen instead

The Devourer of Souls should release Unleashed Souls periodically during the last boss fight.

**Steps to reproduce the problem**:
1. enter instance Forge of Souls
2. fight the last boss Devourer of Souls
3. keep the fight going long enough to see when Unleashed Souls (spell 68939) is cast

**Branch(es):** (Select the branch(es) affected by this issue) 
- [X] 3.3.5
- [ ] 6.x

**TC hash/commit:** rev. 8389991 2016-09-17 14:15:37 +200 (3.3.5 branch) (win64, Release, Dynamic)

**TDB version:** TDB `335.61` + updates up to and including `2016_09_16_08_world.sql`

**Operating system:** Windows 7 x64

**Comment by Aokromes** [comment]
ignore template is evil.

**Comment by ConradBunton** [comment]
What do you mean ?

**Comment by tkrokli** [comment]
@ConradBunton : see my edit. The reason the template was created is to ask for enough information.

**Comment by ConradBunton** [comment]
Ok... I repeat differently.

Last hash, DB 0.61 with all updates, OS Win 7 x64.

So, the last boss (Devourer of soul) summons ghost sometimes. Right ?
Since july 2016, he stoped.

**Comment by Aokromes** [comment]
you still lack hash.

**Comment by tkrokli** [comment]
There is no "latest", because the source code can be updated several times a day and we don't know exactly at which moment you pulled the source to your computer. That is why we want you to look in your Worldserver console or Server.log to find the first line with that info and paste it in the issue post.

**Comment by ConradBunton** [comment]
rev. 8389991275c2 2016-09-17 14:15:37 +200  (3.3.5 banch) (win64, Release, Dynamic)
Last installed World DB : 2016_09_16_08_world.sql

**Comment by tkrokli** [comment]
OK. Original issue comment updated with info where it should have been.

**Comment by ConradBunton** [comment]
As I said, it stopped working because of an update between the end of july and the middle of august.
I tried to see when exatly but couldn't find it.

**Comment by ConradBunton** [comment]
Cast 68939 and 68979 are now unlinked.

**Comment by tkrokli** [comment]
You mean spell ID 68939 and 68979 ?
- http://www.wowhead.com/spell=68939/unleashed-souls
  - Effect 1 : Apply Aura: Periodically trigger spell [Unleashed Souls (68967)](http://www.wowhead.com/spell=68967/unleashed-souls) Interval: 250 milliseconds
  - Effect 2 : Apply Aura: Change Model ([Devourer of Souls](http://www.wowhead.com/npc=36503))
  - Apply Aura: Root
- http://www.wowhead.com/spell=68979/unleashed-souls
  - Effect : Summon [Unleashed Soul](http://www.wowhead.com/npc=36595/unleashed-soul)

**Comment by ConradBunton** [comment]
Ok
Chained spells give : 69939 -> 69967 -> 69979
The problem is between 69967 and 69979.

**Comment by tkrokli** [comment]
OK, thanks for the extra comment. Maybe @ariel- can give us a useful comment about that.

**Comment by ConradBunton** [comment]
I add a spell_linked_spell but its not the real fix.

spell_trigger = 68967
spell_effect = 68979
type = 0

It works but souls spawn on the boss, not at random places.

The original problem appear between july 17th (Before it worked perfectly) and middle of august. But I couldnt find the concernate update.

**Comment by Keader** [comment]
Ok guys, i have a problem here.

using this spell script:

```cpp

class spell_devourer_of_souls_unleashed_souls : public SpellScriptLoader
{
public:
    spell_devourer_of_souls_unleashed_souls() : SpellScriptLoader("spell_devourer_of_souls_unleashed_souls") { }

    class spell_devourer_of_souls_unleashed_souls_SpellScript : public SpellScript
    {
        PrepareSpellScript(spell_devourer_of_souls_unleashed_souls_SpellScript);

        void TriggerSpirits(SpellEffIndex /*effIndex*/)
        {
            if (const WorldLocation* pos = GetExplTargetDest())
            {
                if (Unit* caster = GetCaster())
                {
                    caster->CastSpell(pos->GetPositionX(), pos->GetPositionY(), pos->GetPositionZ(), 68979, true);
                    std::cout << "x: " << pos->GetPositionX() << " y: " << pos->GetPositionY() << " z: " << pos->GetPositionZ() << "\n";
                }
            }
        }

        void Register() override
        {
            OnEffectHit += SpellEffectFn(spell_devourer_of_souls_unleashed_souls_SpellScript::TriggerSpirits, EFFECT_0, SPELL_EFFECT_TRIGGER_MISSILE);
        }
    };

    SpellScript* GetSpellScript() const override
    {
        return new spell_devourer_of_souls_unleashed_souls_SpellScript();
    }
};
```

I cant set position of cast, because spell 68979 is self target.
I will try get sniffs for check who realy cast this spell.

**Comment by sirikfoll** [comment]
This is another case of those range issues, need to override DBC RangeEntry for spell 68979
@ariel-  did some similar fixes, i dunno what should be the new value ^^
