### ISSUE TITLE
[3.3.5] Can mount underwater

### ISSUE THREAD

**Issue by Smokexyz** [TrinityCore/TrinityCore#17970]
**Description**:
Mounting is possible under water.

**Current behaviour**: Tell us what happens
You can mount under water.

**Expected behaviour**: Tell us what should happen instead
You shouldn't be able to mount under water?

**Steps to reproduce the problem**:

1. go underwater
2. summon a mount
3. swim with mount.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
b5035582b656df780e8ebeeb3647288bf1be8256
**TDB version**:  
3.3.5a
**Operating system**:  
OSX

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
https://www.youtube.com/watch?v=FlGxBOs2YTw blizzlike

**Comment by tkrokli** [comment]
@Smokexyz : See also PR https://github.com/TrinityCore/TrinityCore/pull/17488 for details regarding that change.

(TC used to dismount players before, but it has been fixed in the PR linked above.)

**Comment by Smokexyz** [comment]
Thanks for that.
