### ISSUE TITLE
[3.3.5] Vehicle hp resets on seat swiching

### ISSUE THREAD

**Issue by Undergarun** [TrinityCore/TrinityCore#17978]
**Description**:
Vehicle HP are restored on seat switching
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead
Vehicle HPs should not restore
**Steps to reproduce the problem**:

1. Ride a vehicle inside Ulduar
2. Make some damage to vehicle .damage 999999
3. Switch to other seat an the vehicle hp are restored to 100%

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  
068ade35b648b021cce84011bc5016fa9051daab
**TDB version**:  
TDB 335
**Operating system**:  
Ubuntu Server

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
#950
