### ISSUE TITLE
Core/SAI: SMART_TARGET_CREATURE_RANGE and SMART_TARGET_CREATURE_DISTANCE not random

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#17979]
**Description:** SMART_TARGET_CREATURE_RANGE & SMART_TARGET_CREATURE_DISTANCE has bad coding.

**Current behaviour:** Using either target, the same NPC in the range will be hit.

**Expected behaviour:** random target NPC in the range should be hit.

**Branch(es):** (Select the branch(es) affected by this issue) 
- [ ] 3.3.5
- [ ] 6.x

**Comment by jackpoz** [comment]
isn't that the current behavior is "get the first creature found" and what you want is a new behavior "get a random creature with all the creatures in the grid that satisfies the condition" ?

**Comment by jackpoz** [comment]
According to https://github.com/TrinityCore/TrinityCore/blob/3b9c78a176e74654dd55b70187c00fa8b9855227/src/server/game/AI/SmartScripts/SmartScript.cpp#L2581 , SMART_TARGET_CREATURE_RANGE returns a list of targets, not just a single one. are you sure your issue is caused by the SMART_TARGET_ parameter ?

**Comment by dr-j** [comment]
I believe SMART_TARGET_CREATURE_RANGE is working correctly but this does not target single creature it targets all creatures in given range for given entry, this one is usually used when you want the same action to triggered on more than one target npc.

ie for example for setting data on guards to make them enter into combat when npc they are guarding is attacked usually target 9 is used for this as if used with set data will set data on every elegible npc within given range.

**Comment by malcrom** [comment]
Ok well I have a number of trigger npcs in the range and the creature with SAI always hits the same tigger with his spell. There should be a way to select random

**Comment by jackpoz** [comment]
which action are you using ? is there a little test script to repro your case ? (even better if SAI users knew how to debug SAI scripting engine)

**Comment by malcrom** [comment]
-- Dragonflayer Berserker SAI
SET @ENTRY := 24216;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `creature_template_addon` WHERE `entry`=@ENTRY;
INSERT INTO `creature_template_addon` (`entry`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@ENTRY,0,0,0,1,27, '');
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,0,6000,7000,6000,7000,10,53,60,113,388,397,0,1,0,0,0,0,0,0,0,"Dragonflayer Berserker - Out of Combat - Play Random Emote"),
(@ENTRY,0,1,0,1,0,100,0,5000,15000,30000,40000,11,43291,0,0,0,0,0,11,24221,40,0,0,0,0,0,"Dragonflayer Berserker - Out of Combat - Cast Throw Bottle"),
(@ENTRY,0,2,0,1,0,100,0,14000,26000,14000,26000,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dragonflayer Berserker - Out of Combat - talk"),
(@ENTRY,0,3,0,4,0,80,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dragonflayer Berserker - Aggro - talk");

-- Texts for Dragonflayer Berserker
SET @ENTRY := 24216;
DELETE FROM `creature_text` WHERE `entry`=@ENTRY;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`comment`) VALUES
(@ENTRY,0,0,"Beg for your life...",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,0,1,"Suffer, insect!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,0,2,"Your end draws closer!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,0,3,"My life for Ymiron!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,0,4,"For Ymiron!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,0,5,"YAAARRRGH!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,1,0,"Take me! I am ready to die!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,1,1,"We battle for the glory of Ymiron! We die in the name of the Lich King!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,1,2,"Drink in their misery, brother!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,1,3,"Stand and be judged!",12,0,100,0,0,0,"Dragonflayer Berserker"),
(@ENTRY,1,4,"May you die in the Lich King''s favor!",12,0,100,0,0,0,"Dragonflayer Berserker");

**Comment by malcrom** [comment]
I would assume that SMART_TARGET_CLOSEST_CREATURE would target the closest one, SMART_TARGET_CREATURE_GUID would target certain one, and SMART_TARGET_CREATURE_RANGE or SMART_TARGET_CREATURE_DISTANCE would be random in the set range.

**Comment by malcrom** [comment]
bump

**Comment by Grz3s** [comment]
hi @malcrom 
just wonder if you know what is that brown stain... that is created in same place where Dragonflayer Berserker Target is ,,, after Dragonflayer Berserker - Cast Throw Bottle
is this spell ? npc? object ?
https://www.youtube.com/watch?v=maVt337_gCs  -- 00:05 (2 next to cages on the left .. etc)

**Comment by Killyana** [comment]
Confirm on rev. 831f5cfab865
