### ISSUE TITLE
game.PCH.cpp causes compiler to segfault on small vms

### ISSUE THREAD

**Issue by sapier** [TrinityCore/TrinityCore#17972]
**Description**:
Build process requires excessive amount of ram!
Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o

requires about 900 MB of ram to compile on debian jessie!

**Current behaviour**: 
--> compiler often crashes with internal error if your vm has only about 1gb ram attached. For some reason swap memory doesn't seem to solve the issue completely.

**Expected behaviour**:
Don't require almost 1 GB of RAM to compile a single file containing a few bytes. I know most ppl do have more then 1GB of ram but if you try to find the cc1plus segfault issue on google you'll have trinitycore problems as one of the top results. 
I'd guess something you did in your source code organization is (while not beeing formaly wrong) quite bad as of memory consumption on build.
BTW if you did try to compile trinitycore in parallel this excessive memory usage could cause issues too.

**Steps to reproduce the problem**:

1. create a debian vm with 1gb ram and additional swap space
2. clone
3. build

**Branch(es)**:  6.x

**TC hash/commit**:  
e1f4b6b04cc8bf386f23d45c930d706855af03c5

**TDB version**:  
irrelevant

**Operating system**:  
Debian Jessie

**Comment by Treeston** [comment]
If you fall way short of minimum specs, then complain in an obnoxious manner while demonstrating a complete lack of understanding of the subject you're complaining about, there is only really one way to respond to this.

Read up on what precompiled headers are, or turn them off. We aren't a tech support department that's paid to listen to your entitled bitching.

**Comment by sapier** [comment]
Oh I see there's someone "better" talking on the other side.
Well if you believe insulting ppl telling you about problems with your code (or build) will help you finding issues be it that way.
Well a quite common misstake for oss developers so don't bother too much ;-P

btw if your minimum specs require some GB of ram this just shows you do not understand your code. TrinityCore will run just fine way below 1GB of RAM. What really requires RAM is the mysql db but surprise surprise you can run it on a different machine.

**Comment by Shauren** [comment]
TrinityCore will run with less memory just fine, however the program you are using here is not TrinityCore but GCC or clang, complain to them that it uses so much memory.

Go be an ass somewhere else.
