### ISSUE TITLE
Client crash error 132 access violation

### ISSUE THREAD

**Issue by wowharley** [TrinityCore/TrinityCore#17973]
**Description**: Getting error 132 access violation when creating the following characters, human, undead, client 7.0.3 22594 using wow_patched.exe

**Current behaviour**: I was creating an account and enter the world and i received the following pop up, error 132 fatal exceptation, memory reference and the client crashed.

**Expected behaviour**: I should be able to go into the world and play around.

**Steps to reproduce the problem**:

1. Boot the server
2. Log into your account, with human warrior, undead, orc
3. log into world and the client will crash

**Branch(es)**: 6.x

**TC hash/commit**:  e1f4b6b

**TDB version**:  6.0.4

**Operating system**:  Windows 10, VS2015 update 3

**Comment by Aokromes** [comment]
because search human crash is to mainstream.

#17903
