### ISSUE TITLE
[3.3.5] Wintergrasp Buff - (UpdateTenacity)

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#17977]
**Steps to reproduce the problem**:
1. Required 4 Player's - 2 Alliance - 2 Horde
2. Go to Wintergrasp and start bf 1 (With command: bf start 1)
3. Leave one horde by: Leave zone, logout, kick, Alt+f4
4. Second Horde will be have buff SPELL_TENACITY
5. Join again with same player or new one
   You will be see buff will be not remove
   This problem just happen in horde team but in alliance team is work correct and buff will be remove when next alliance player join.

Update:
When new Horde player join and last team buff for horde, Check and remove buff from Alliance not horde team.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  
f2067d3

**Comment by ariel-** [comment]
24105ec1587be5c3864c912359cb783cd99de26a
