### ISSUE TITLE
Turning while falling

### ISSUE THREAD

**Issue by nerv234** [TrinityCore/TrinityCore#17984]
**Description**: You should be able to change falling direction in certain situations(dh glide, gliders etc)

**Current behaviour**: Won't work.

**Expected behaviour**: You should be able to change falling direction in certain situations(dh glide, gliders etc)

**Steps to reproduce the problem**:

1.  Create Demon Hunter.
2.  Jump from high, pres space bar till you get glide.
3.  Change your direction.
4.  Then you're still falling in the same direction.

Usefull Info:
Packet sent to client:
https://gist.github.com/nerv234/88a283783996f5339b7351ced5834d07
Packet sent in response for previous packet:
https://gist.github.com/nerv234/63031a89f52151b585222e4a7424c719

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) Both?

**TC hash/commit**:  cf8f30827dd5537c63a5115da5734e96fb1c1cd6

**TDB version**:  Latest

**Operating system**:  win7

**Comment by Shauren** [comment]
adad691807b4cd839f710e96beace34a7b0154ad
