### ISSUE TITLE
Core/Spells: SMSG_PLAY_SPELL_VISUAL does not show spell visuals

### ISSUE THREAD

**Issue by timh52280** [TrinityCore/TrinityCore#17993]
**Description:** Some spells using SMSG_PLAY_SPELL_VISUAL do not show the associated visual effect.

**Current behaviour:** Spells like http://www.wowhead.com/spell=152277/ravager are using this opcode to send spell visual effect, however this opcode is not implemented yet in TrinityCore 6.x

**Expected behaviour:** Using the spell above as and example, this spell must show a visual effect as this video shows: (https://www.youtube.com/watch?v=sKXWISxn4Fc). However, in TrinityCore the weapon only keeps swirling without any visual effect.

**Steps to reproduce the problem:**

Cast a spell that use SMSG_PLAY_SPELL_VISUAL like this:

```
ID - 156287 Ravager

$@spelldesc152277
Category = 0, SpellIconID = 9559, activeIconID = 0, SpellVisual = (36990, 0) --Spell visual
Family SPELLFAMILY_WARRIOR (4), flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000800
```

From sniffs I noticed that this spell is using  SMSG_PLAY_SPELL_VISUAL:

```
ServerToClient: SMSG_PLAY_SPELL_VISUAL (0x2C44) Length: 43 ConnIdx: 1 Time: 09/15/2016 12:50:37.232 Number: 188
Source: Full: 0x2030A000204A620000002C00005ADF6C Creature/0 R3112/S44 Map: 1 Entry: 76168 Low: 5955436
Target: Full: 0x0
TargetPosition: X: 2124.281 Y: -4478.961 Z: 144.7207
SpellVisualID: 36990
TravelSpeed: 0
MissReason: 0
ReflectStatus: 0
Orientation: 0
SpeedAsTime: True
```

**Branch(es):** 6.x

**TC hash/commit:**
TrinityCore rev. cf8f30827dd5+ 2016-09-22 23:41:20 +0200 (6.x branch) (Unix, Release, Dynamic)  

**TDB version:** TDB 6.04  

**Operating system:**  Ubuntu 16.04

---

(edited by @tkrokli)

**Comment by Ulduar** [comment]
I searched at github and something found. https://github.com/losolivos/chuspi/blob/master/src/server/game/Entities/Unit/Unit.cpp#L19124

void Unit::SendPlaySpellVisual(ObjectGuid source, ObjectGuid target, uint32 spellVisual, float speed)

Spell change visual effect not only from AURA_403 (implemented)

**Comment by Goatform** [comment]
I think that this is AreaTrigger issue ([click here](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Entities/AreaTrigger/AreaTrigger.cpp))

I believe that it can be fixed by updating / reworking structure:

```
    uint32 spellVisual = 0;
    if (SpellXSpellVisualEntry const* visual = sSpellXSpellVisualStore.LookupEntry(spellXSpellVisualId))
        spellVisual = visual->SpellVisualID[0];

    SetEntry(triggerEntry);
    SetDuration(spell->GetDuration());
    SetObjectScale(1);

    SetGuidValue(AREATRIGGER_CASTER, caster->GetGUID());
    SetUInt32Value(AREATRIGGER_SPELLID, spell->Id);
    SetUInt32Value(AREATRIGGER_SPELLVISUALID, spellVisual);
    SetUInt32Value(AREATRIGGER_DURATION, spell->GetDuration());
```

**Comment by timh52280** [comment]
@Goatform thank you for your answer but for example ravager does not create an area trigger so I think that your idea does not apply for that
