### ISSUE TITLE
[3.3.5] Events/Brewfest: repeatable quest flag for Brewfest quests

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#17995]
**Description:**

1. Some quests don't have flags (Daily/Weekly/Monthly), but can repeated.
2. You can complete the repeated quest, but the quest ender will not reward the quest.

**Example 1:** Quest name:  [Catch the Wild Wolpertinger!]
- H: 11431 - http://www.wowhead.com/quest=11431/catch-the-wild-wolpertinger
- A: 11117 - http://www.wowhead.com/quest=11117/catch-the-wild-wolpertinger

**Example 2:** Quest name:  [Pink Elekks On Parade]
- H: 11120 - http://www.wowhead.com/quest=11120/pink-elekks-on-parade
- A: 11118 - http://www.wowhead.com/quest=11118/pink-elekks-on-parade

**Example 3:** Quest name:  [Chug and Chuck!]
- H: 12191 - http://www.wowhead.com/quest=12191/chug-and-chuck
- A: 12022 - http://www.wowhead.com/quest=12022/chug-and-chuck

Attention: Second time when you complete the quest in quest dialog (L) show quest is complete, but when you use command lookup quest on player,  just show quest is active !!!

**Update:** Information from wowhead comments:

"The quests aren't bugged. Blizz did a reset of the quests. Unless they do this again, to fix something else, they wont be repeatable."

**Steps to reproduce the problem:**

1. .add quest 11431 or 11117
2. Complete the quest and go to the quest ender.
3. Restart the server
4. Take the quest, complete it, but quest ender will not reward the quest.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue)
- [X] **3.3.5**
- [ ] 6.x (not tested)

**TC hash/commit:** f2067d3

**Operating system:** Debian 64bit

***
(edited by tkrokli)
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Ghost-R** [comment]
@tkrokli Not just this quest i found more, this quest just for example.

**Comment by tkrokli** [comment]
OK, TC prefers to keep issues to one isolated problem per issue, unless they are grouped in the same category. Not sure if this is a case where a list will be practical, but provide a list and we will see. :-)

**Comment by Ghost-R** [comment]
@tkrokli I add more quest.

**Comment by SnapperRy** [comment]
I can't reproduce the issue. Did the quests yesterday, they aren't being offered to me again.

Seasonal quests are all added in the character_queststatus_seasonal table, which by all means acts the same way as the character_queststatus_rewarded one, with the difference that seasonal quests are reset when the event starts.

**Comment by Ghost-R** [comment]
@SnapperRy TC hash/commit ?

**Comment by SnapperRy** [comment]
fb76f1b.

**Comment by Ghost-R** [comment]
@SnapperRy, i fix Steps to reproduce the problem
When server is restart and start again this all quest for all player for run event will be remove.
Check it again .

**Comment by SnapperRy** [comment]
That same exact issue was fixed in fb6d4dd.

**Comment by Ghost-R** [comment]
@SnapperRy Thank you, i found it.
