### ISSUE TITLE
Class_unit

### ISSUE THREAD

**Issue by vato312199** [TrinityCore/TrinityCore#17998]
**Description:**

Hello, help me.. How to make an NPC appeared resource such as energy or rage? I have instead is a general in the NPC no resource except for mana. I 7.0.3.22624 build. Build me officially to the Trinity. Help!!

**Current behaviour**: not work

**Expected behaviour**: Will see resource from a NPC

**Branch(es)**: 6.x 

**Tags 7.0.3/22624**

**TDB version:** TDB 6.04

**Operating system:** Win x64

**Comment by Aokromes** [comment]
ignore template is evil.

**Comment by vato312199** [comment]
?

**Comment by tkrokli** [comment]
@vato312199 : He refers to that you removed some of the lines in the original template text, like the lines "**Steps to reproduce the problem:**" where you should have written what to do to confirm your problem and "**TC hash/commit:**  " which should be answered with your current TC revision hash from the console or log.

**Comment by tkrokli** [comment]
Closing this one as duplicate of #18000 .
