### ISSUE TITLE
606c64bae5a6 works, all update make client crash

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#18007]
606c64bae5a6 (2016-09-21 7h40) is the last for me. It's works but all update makes client crash. Tried to delete all and download to make a clean recompil... Always that client crash.

Win 64
Boost 1.61.0
OpenSSL 1.0.2f
MSVC 14

When I launch the 606c64bae5a6 and keep DB, Config... Everything is ok, it's work.

Client error message :
This application has encountered a critical error:
ERROR #132 (0x851000084) Fatal exeption!

**Comment by Aokromes** [comment]
there is no such rev on clean trinitycore.

**Comment by jackpoz** [comment]
please provide a trinitycore commit, if you are using custom sources please publish them on github and link them. from the infos you provided it's not even clear which branch you are using.

**Comment by offl** [comment]
TrinityCoreBot is on vacation? :)

**Comment by ConradBunton** [comment]
Sorry, wrong source. I posted that Issues for trinitycorelegacy. I don't know how it gone here.
