### ISSUE TITLE
[6.x] elwynn forest graveyard broken

### ISSUE THREAD

**Issue by JaredNinja** [TrinityCore/TrinityCore#18004]
**Description**: When dying in the starter area of humans, you are returning as a ghost in westfall. Not the graveyard in elwynn forest.

**Current behaviour**: See description. Maybe it's just full, but I'm pretty sure my ghost should end up there.

**Expected behaviour**: Being a ghost at elwynn forest graveyard

**Steps to reproduce the problem**:

1. Log in
2. Create new hooman
3. Die due to ferocious wolf bites right in the starting area 

**Branch(es)**: 6.x

**TC hash/commit**:  

**TDB version**:  updated 3 hours ago (where can I find it?)

**Operating system**:  W10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
#14089

**Comment by JaredNinja** [comment]
I couldn't find it using search, that is the same problem indeed. So it requires for someone to merge #e2c0189 into 6.x (just merge, or rewrite code to 6.x first?). And after that, it should be easier to fix the actual bug.

**Comment by Aokromes** [comment]
IIRC it was merged. and with simply search graveyard was the 1st match before you made this :P

**Comment by tkrokli** [comment]
if it has been merged already, why hasn't #14089 been closed yet? I have my doubts. :suspect:

**Comment by Aokromes** [comment]
because we need logs of all affected graveyards and people using the command around all affected graveyards.

**Comment by JaredNinja** [comment]
Thats something that can be done in Trinity, doesnt require retail, right? Thats something I can do.

However. The logical approach to me feels like testing it on the ones reported, then checking code, adjust it while using logic (no dirty fix, but the problem should be obvious), then fix it.

It has to be the same problem for all, otherwise it means the main branch is already dirty. I really think its not, it should be neat 10-40 lines code max

**Comment by tkrokli** [comment]
Well, TrinityCore aims at making the source code behave as close as possible to retail behaviour.
For 6.x, that normally means you can get sniff info (when possible) to write correct code.

**Comment by JaredNinja** [comment]
Yes, exactly. Thats why I appreciate Trinity so much. As close to retail as possible, no cutting corners.

However, sniffing can only provide client<->server commands. Not the logic behind it. Right?

I have not had an oppertunity to take a look at the code, but I know the client files contain graveyard positions*. So the logic should be; find nearest graveyard position to player who died.

(*killyana said that at https://github.com/TrinityCore/TrinityCore/issues/16003)

If this logic fails to point out Elwynn, then either the client files have changed because I believe it worked before. Or the trinity logic code has a flaw, which I think is the case. Otherwise none would have worked.

Now this whole logic should be 10-40 lines of code max. I cant think of any reason to have more logic to it than simply the closest.

So, checking current code and using Elwynn as a case seems like a good start to fix an annoying bug right?

**Comment by JaredNinja** [comment]
Seems like it could be a database problem, not code:
http://imgur.com/a/e2HEi

**Comment by JaredNinja** [comment]
Turns out, using the instructions on https://trinitycore.atlassian.net/wiki/display/tc/Databases+Installation you are not having the database installed correctly. at least this graveyard table is missing.
