### ISSUE TITLE
Weapon type "melee" missed

### ISSUE THREAD

**Issue by Martos** [TrinityCore/TrinityCore#18009]
**Description**: Starter weapons dont have a type "melee"

**Current behaviour**: When I attempt to cast a spell, games says "Require a melee weapons" but the weapons is already equiped

**Expected behaviour**: The initial weapon should have the type "melee"

**Steps to reproduce the problem**:

1.  Cast a spell with new character

**Branch(es)**: 3.3.5

**TC hash/commit**:  

**TDB version**:   TDB 335.61

**Operating system**:  Windows 10

This is an screenshot to explain the issues: 

![wowscrnshot_092616_185704](https://cloud.githubusercontent.com/assets/4572919/18844540/e8a1918c-841d-11e6-9124-050e3e1d332e.jpg)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
why you open a new issue about same bug? edit previous ticket with proper data, you still lack hash.
