### ISSUE TITLE
[6.x] bugs in battlenet (account creation & deletion)

### ISSUE THREAD

**Issue by JaredNinja** [TrinityCore/TrinityCore#18002]
**Description**:

**Current behaviour**: Unexpected results using .bnetaccount create, .bnetaccount delete and .bnetaccount set gmlevel due to recently introduced battlenet system.

**Expected behaviour**: creation and deletion of accounts should be done using the login of the user, not using "1#1"

@joschiwald (You worked on prep stats 22 hrs ago. Is this something you would like to fix? It seems you have the required expertise)

**Steps to reproduce the problem**:
1. Use .bnetaccount create or .bnetaccount delete
2. When deleting, also notice a record is left behind in battlenet_accounts. Need an extra prep stat in \src\server\database\Database\Implementation\LoginDatabase.cpp? like LOGIN_DEL_BNET_ACCOUNT

**Branch(es)**: 6.x

**TC hash/commit**:  what?

**TDB version**:  latest (auto update)

**Operating system**:  W10

**Comment by Aokromes** [comment]
ignore template is evil.

**Comment by JaredNinja** [comment]
so sorry. info is simple; all cloned and built today, so absolute stock and up to date code. easy to reproduce using steps above.

**Comment by tkrokli** [comment]
TC devs still prefer that you use the lines in the template for better issue tracking & info availability.

**Comment by JaredNinja** [comment]
Should I post a new issue? Or should I just be ashamed really hard and leave it like this for now? :)

**Comment by Aokromes** [comment]
you must edit existing issue.

**Comment by tkrokli** [comment]
Copy content from the page https://github.com/TrinityCore/TrinityCore/issues/new into your first post. :-)

**Comment by JaredNinja** [comment]
edited to comply with template. my bad guys.

**Comment by joschiwald** [comment]
there is no command .bnetaccount set gmlevel

**Comment by JaredNinja** [comment]
oh right, thats just .account set gmlevel. The issue remains though; it wants an account name from the accounts table instead of an email from the battlenet_accounts table.

**Comment by JaredNinja** [comment]
Wouldn't it be a solid solution to merge accounts into battlenet_accounts? This adds an extra layer of unnecessary complexity. Extra joins and relations.

If backwards compatibility is the reason; I'd love to write an update script that merges them and then transfers the "old" accounts into the new table. Hell, If I had any idea how, I could code it myself and upload it here so we can all enjoy. I don't want to have my server any different from this source for future updates by all the guys and gals working on it.

**Comment by Shauren** [comment]
@JaredNinja you are mistaken about one thing here, the relation between battlenet_accounts and accounts is not one to one. its one to many, see http://imgur.com/y75NP7V
Permissions are set on account level (one selection from the list in above screenshot). It is intended that you are able to manipulate each of them separately and I agree that "1#1" is not very user friendly but I have not had a better idea for this yet.

**Comment by JaredNinja** [comment]
My bad, I had no idea about the 1:n possibility. Your solution seem fine then. I'll think about it some more, but I probably won't come up with any better plan.

Apart from the db architecture, it still would be nicer to be able to use the email in the commands. If I understand correctly, when used that way, it only needs to fetch the parent account id to execute as expected. Saves admins looking up stuff in the database (yay for creating accounts from chat ingame)

(and of course the missing prep stat for deletion of the bnet row remains a thing)

**Comment by JaredNinja** [comment]
@shauren
Thanks for adding the commands: .bnetaccount link and .bnetaccount gameaccountcreate

Are these documented?

**Comment by tkrokli** [comment]
@JaredNinja : https://trinitycore.atlassian.net/wiki/display/tc/GM+Commands

| Command | Security | Description |
| --- | --- | --- |
| bnetaccount create | | |
| bnetaccount gameaccountcreate | | |
| bnetaccount link | | |
| bnetaccount set | | |
| bnetaccount unlink | | |

**Comment by JaredNinja** [comment]
@tkrokli Thank you

**Comment by Aokromes** [comment]
1#1 thing is blizzlike.

http://i.imgur.com/67CI0wI.png
