### ISSUE TITLE
Cannot create a new 3.3.5a compiled build, without ignoring old mistakes.

### ISSUE THREAD

**Issue by piccolodmq** [TrinityCore/TrinityCore#18003]
**Item Database its gone, and can´t compile a new server to correct this**:

**Somehow I screw up my item template database. When I go ingame, there is zero items. Since I can´t fix, this. I tried compiling a new server (didnt have anything special in the old one), and somehow the new compiled version keeps getting the old information (no item database), I tried unistalling and installing back Mysql, and sill I am getting the same, results. }}What do I have to do to get a fresh new compiled version without this errors?

I just want a fresh new compile using this guide
https://trinitycore.atlassian.net/wi...e+Installation

But I keep getting the old version again and again. (even when I compiled from zero).**: happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. I try to compile from this point:  https://trinitycore.atlassian.net/wiki/display/tc/Windows+Core+Installation
2. When I do everything from scratch, and get to the end, part where I run the worldserver and auth after compiling and build and source with different patchways (examplle c:/build4 adn source trinity3)
I still get the old accounts and errors from the prevuois server
3. How can I make a clean build that ignores all prevuois information

**Branch 3.3.5a**: 

**TC hash/commit**:  

**TDB version**:  

**Windowas 2012 data center R2 datacenter**:

**Comment by JaredNinja** [comment]
1. Empty all your tables

2. Import the FULL table (download manually: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.61 )

3. turn on auto update in your worldserver.conf.

4. start world server

..should populate the DB just fine up till last update.

**Comment by tkrokli** [comment]
This is not a TrinityCore issue, you have probably messed up your C:\ProgramData\ folders/files.
Also, this is the issue tracker for source code & real DB issues, not a forum.

**Comment by JaredNinja** [comment]
@tkrokli I'm pretty sure it can indeed all be sorted out fairly quickly. However, I understand your desire to reserve this place for tracking issues. It would really help this gentleman if you could point him to said forum, if there even is one. Thank you for your help.

**Comment by tkrokli** [comment]
Sure, no problem to provide pointers to the TrinityCore pages. Become familiar with the TC pages:
***
https://www.trinitycore.org   `<-- main start page for links / pointers`

https://community.trinitycore.org
https://community.trinitycore.org/forum/39-guides/
https://community.trinitycore.org/forum/5-help-and-support/
https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/

**Comment by JaredNinja** [comment]
@tkrokli great help! (For me too) Thanks!
