### ISSUE TITLE
Weapon type "melee" missed [3.3.5]

### ISSUE THREAD

**Issue by Martos** [TrinityCore/TrinityCore#18008]
**Description**: Starter weapons dont have a type "melee"

**Current behaviour**: When I attempt to cast a spell, games says "Require a melee weapons" but the weapons is already equiped

**Expected behaviour**: The initial weapon should have the type "melee"

**Steps to reproduce the problem**:

1. Cast a spell with new character

**Branch(es)**: 3.3.5

**TC hash/commit**:

**TDB version**: TDB 335.61

**Operating system**: Windows 10

This is an screenshot to explain the issues:
 
![wowscrnshot_092616_185704](https://cloud.githubusercontent.com/assets/4572919/18843864/13660d42-841b-11e6-852f-1b90b994a6ba.jpg)

**Comment by Aokromes** [comment]
ignore template is evil, no hash at all.

**Comment by tkrokli** [comment]
Please pick the lines from https://github.com/TrinityCore/TrinityCore/issues/new (which you removed when you opened this issue), we prefer to have those questions answered to troubleshoot your issue properly and to track it for future reference.

**Comment by Martos** [comment]
Oh okay... sorry :c

**Comment by Martos** [comment]
I have update the issues 👍

**Comment by jackpoz** [comment]
works fine with a fresh new Male Human Rogue and casting Sinister Strike
![wowscrnshot_092616_195359](https://cloud.githubusercontent.com/assets/1153754/18845974/3a53d386-8424-11e6-94ae-edcdec98fb2b.jpg)

**Comment by Martos** [comment]
Maybe is the female human rouge? I gonna try with male human rouge

**Comment by Martos** [comment]
Not work for me :c

![wowscrnshot_092616_200724](https://cloud.githubusercontent.com/assets/4572919/18846144/e6ad1f70-8424-11e6-80ef-092ce3c64c6e.jpg)

**Comment by Shauren** [comment]
Looking at the first action bar icon being a giant red ? (autoattack slot) points to a custom items which are known to not work.

**Comment by tkrokli** [comment]
@Martos : 2 things you can learn from this:

1. Test any issues you find on clean, straight, unchanged TrinityCore source before reporting.
2. When reporting an issue to the TrinityCore issue tracker, include the TC rev. hash in your report.

Your issue is, as Shauren said, most likely caused by custom code (not supported by TrinityCore).
