### ISSUE TITLE
Scripts/Azjol: Krik'thir the Gatewatcher

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#18011]
**Description**:
Reset behaviour has some flaws

**Current behaviour**: Tell us what happens
- After reset (wipe for example) aggro behaviour is not correct, when one miniboss is pulled everything is aggroed
- On wipe hadronox event is started

**Steps to reproduce the problem**:
1. aggro
2. wipe
3. engage

**TC hash/commit**:  a573e8f680429c03abba6e04f9bc326a0ebfb378

**Comment by Frytiks** [comment]
Confirm https://github.com/TrinityCore/TrinityCore/commit/a573e8f680429c03abba6e04f9bc326a0ebfb378
