### ISSUE TITLE
[6.x] Core/Phasing Terrainswap doesn't update area

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18019]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Terrainswap needs to update areas too.

**Current behaviour**: 
Terrainswap doesn't update area.

**Expected behaviour**: Terrainswap needs to update area too.

**Steps to reproduce the problem**:

1. Go to Mount Hyjal to The Inferno
2. Type .gps and look area
3. Check what your char explored (it exlpores The Regrowth instead of The Inferno)

**Branch(es)**:  6.x 

**TC hash/commit**: 9b3aacc56d4e7b24ffcc1bf6000da3a846e42b6d

**TDB version**:  6.0.4

**Operating system**:  
Win10

![wowscrnshot_092816_210107](https://cloud.githubusercontent.com/assets/846960/18928101/fa452fb4-85be-11e6-8ed5-d384a04812b5.jpg)

**Comment by Shauren** [comment]
Terrain swap not implemented for vmaps

**Comment by funjoker** [comment]
So this issue belongs to: #15163
