### ISSUE TITLE
ERROR on Worldserver

### ISSUE THREAD

**Issue by piccolodmq** [TrinityCore/TrinityCore#18016]
Hi there, 

Whenever I make a human or walk near northshrie, I get this error.

https://drive.google.com/open?id=0B8xvHOnjNZYbMDAxMHJNVml3RUE

I have been changing some custom display ID, but can`t find in the DB world/creature the displays that are showing there, or if it has to do anything with the error mention there.

This is on a 3.3.5a branch. 

Thanks for your help

**Comment by DDuarte** [comment]
Off-topic: I'm trying to understand why people completely ignore the pre-written text that is displayed when you create a new issue.

**Comment by DDuarte** [comment]
"I have been changing some custom display ID" That's your answer. Don't change stuff willy-nilly.

**Comment by funjoker** [comment]
Creature doesn't exists ingame anylonger.

**Comment by funjoker** [comment]
Fix: remove all creatures out of Creature table with id 67 :P

**Comment by piccolodmq** [comment]
I have changed the ID´s and that didnt help

**Comment by ariel-** [comment]
Drop your world database, import clean TDB 335.61 and delete your client cache folder.
