### ISSUE TITLE
Male Demon Hunter

### ISSUE THREAD

**Issue by Blasphemous** [TrinityCore/TrinityCore#18014]
Male Demon Hunter not spawning wings on double jump

Character still glides, but with no wing animation

Female shows wings, used to work, don't remember what commit, seems that male wings stop working after a commit where double jump was the focus

This is with the latest and last few or more 6.x branch

Windows 10

**Comment by Traesh** [comment]
Aokromes : ignore template is evil

**Comment by blitztech** [comment]
no wing only at male night elf ....so anyone know where to fixes it?

**Comment by jackpoz** [comment]
You didn't follow the issue template with required informations like TC hash/commit when creating the issue https://github.com/TrinityCore/TrinityCore/issues/new
