### ISSUE TITLE
[7.x] Power Insanity

### ISSUE THREAD

**Issue by M3luxit0** [TrinityCore/TrinityCore#18018]
**Description:**

Insanity power decreases with time.

**Current behaviour:** Tell us what happens

A shadow priest loses insanity over time.

**Expected behaviour:** Tell us what should happen instead

Insanity should not miss while in combat.

**Steps to reproduce the problem:**

1. Use a Shadow Priest
2. 
3. 

**Branch(es):** 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

6.x (7.x game client)

**TC hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

***
(edited by tkrokli)

**Comment by jackpoz** [comment]
you didn't specify the TC hash/commit, TDB version and Operating System required by the issue template
