### ISSUE TITLE
Crash:: std::__cxx11::_List_base<AuraEffect*, std::allocator<AuraEffect*> >::_M_clear

### ISSUE THREAD

**Issue by Magoxx** [TrinityCore/TrinityCore#18028]
[crashlog_2016-10-01_05-08-36.txt](https://github.com/TrinityCore/TrinityCore/files/504126/crashlog_2016-10-01_05-08-36.txt)

**Description**: Server crash very often

**Current behaviour**: Server crash

**Expected behaviour**: No crash

**Steps to reproduce the problem**:
1. Launch server
2. Wait
3. 

**Branch(es)**:  6.x 

**TC hash/commit**:  7225e249326f974d9525736c017277d28894663e
**TDB version**:  6.04

**Operating system**:  Ubuntu Server 14

**Comment by funjoker** [comment]
Crash from doing nothing?
Well no crash for me.

Is the crash occuring on your Private Server?
Did you modify the Source Code?

**Comment by Magoxx** [comment]
crash occur and we dont know exactly what happend, with a log we discover that is removing m_modAuras aura with type 131, but cant reproduce it.

No custom code atm

**Comment by alexandre433** [comment]
How did you add your db's to your server?

**Comment by Sar777** [comment]
confirm

**Comment by jackpoz** [comment]
> confirm

what are you confirming ? if you are confirming the crash, post your crashlog too

**Comment by Magoxx** [comment]
More crashlog

**Comment by chilito** [comment]
confirm

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18028#issuecomment-250942263

**Comment by jackpoz** [comment]
@chilito did you remove some lines from the crash log before posting it ? the initial part is missing

**Comment by chilito** [comment]
https://github.com/jackpoz deleted only computer information

**Comment by Aokromes** [comment]
over 1 year since the last crash report, if this bug is still valid, plz open a new ticket with updated core.
