### ISSUE TITLE
[7.x Crash] Item::SaveToDB

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#18025]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:Crash on Item::SaveToDB

**Current behaviour**: Crash 

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. protection paladin equip the Artifact [Truthguard](http://www.wowhead.com/item=128866)
2. change Specialization to holy and log out
3. relogin you will see your mainhand weapon disappeared  then  logout  or command .save 
4. Crash

**Branch(es)**: 6.x 

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/75f9164fc85e1551e3bb09903a9803719b774482

**TDB version**:  TDB 6.04

**Operating system**:  WIN7 x64
[Crash Log](https://github.com/TrinityCore/TrinityCore/files/501792/worldserver.exe_.30-9_5-52-56.txt)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by wowharley** [comment]
could this be related to this

https://github.com/TrinityCore/TrinityCore/issues/15263

**Comment by Nelidon** [comment]
Not linked.

**Comment by jackpoz** [comment]
could you please reproduce the crash in Debug mode since apparently you already have the steps to easily reproduce it ? thank you

**Comment by Shauren** [comment]
I know about this crash and myself have a character to consistently reproduce it, no need for more details from users.
