### ISSUE TITLE
GO Respawntimer Fix for some Quests

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18023]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
Wrong respawntimer for some Quest GameObjects

http://de.wowhead.com/quest=13242/die-dunkelheit-regt-sich
http://de.wowhead.com/object=193197/saurfangs-schlachtrustung

https://www.youtube.com/watch?v=V7cTyxnAHvQ
http://de.wowhead.com/object=191576/transporterakku

https://www.youtube.com/watch?v=OSJaHrZ7ks4
http://de.wowhead.com/object=191519/funksockels-werkzeuge

https://www.youtube.com/watch?v=LCWT3BIJrQo
http://www.wowhead.com/object=192171/colossus-attack-specs

http://www.wowhead.com/object=191708/disturbed-snow
https://www.youtube.com/watch?v=tqsc_j5Fp1w

https://www.youtube.com/watch?v=_f_uqiOPplA
http://de.wowhead.com/object=193561/ausgrabungsleiter-khronas-notizen
http://www.wowhead.com/object=193560/prospector-sorens-maps

http://www.wowhead.com/quest=9506/a-small-start
http://www.wowhead.com/object=181674/nautical-map
http://www.wowhead.com/object=181675/nautical-compass
https://www.youtube.com/watch?v=EDasisblVOE

http://www.wowhead.com/quest=9530/ive-got-a-plant
http://www.wowhead.com/object=181696/hollowed-out-tree
https://www.youtube.com/watch?v=8XhWcq_d6og

http://www.wowhead.com/object=182532/nazzivus-monument-glyphs
http://www.wowhead.com/achievement=246/know-thy-enemy
https://www.youtube.com/watch?v=nJfapjtvYhQ
-- Gameobject need a fix for Blizzlike position!

http://www.wowhead.com/quest=9548/pilfered-equipment
http://de.wowhead.com/object=181746/kloppers-ausrustung
https://www.youtube.com/watch?v=CQhBtZ1B_s4

-- Thanks to Grz3s for Pumpkin sniff.
http://www.wowhead.com/object=375/tirisfal-pumpkin

```sql
UPDATE `gameobject` SET `spawntimesecs` = 120 WHERE  `id` = 375;
UPDATE `gameobject` SET `spawntimesecs` = 5 WHERE  `id` = 181746;
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (193197,181674,181675);
UPDATE `gameobject` SET `spawntimesecs` = 0 WHERE `id` IN (191576,191519,192171,191708,193560,193561,181696,182532);
```

PS: Tested on Lifeserver with Party and Solo 
**Branch(es)**: 3.3.5 / 6.x  

**TC hash/commit**:  
TrinityCore rev. a573e8f68042 2016-09-27 03:21:49 +0200 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates
**Operating system**:  
Win7 64Bit

**Comment by PiskelDEV** [comment]
Lifeserver, what a beautiful place, where is it?

good job - btw

**Comment by tkrokli** [comment]
This part seems like a too short time to me, but I'm not an expert on the data behind it.
```
UPDATE `gameobject` SET `spawntimesecs` = 0
```
Have you really found all those values in sniffs ?

**Comment by Tauriella** [comment]
I don't use a sniff program but you can be 100% sure that is correct ( No Fantasy )
Tested on Blizzserver with Party and Solo.

**Comment by tkrokli** [comment]
OK, fair enough, I see what you mean. Let's just wait for some feedback from the TC people who knows.

**Comment by Killyana** [comment]
Don't use respawntime=0, if the gob is unique always use 2secs.
