### ISSUE TITLE
Ring of valor arena 3.3.5

### ISSUE THREAD

**Issue by franklampardahar** [TrinityCore/TrinityCore#18033]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:The Ring of Valor Arena

**Current behaviour**: elevator Not Come up characters with out use space to jump

**Expected behaviour**: anyone can update this script to latest trinity?

**Steps to reproduce the problem**:

1. i found a script to fix ring of valor and Dalaran sewers but not 100% blizzlike i use it in old trinitycore source it work good but i can't update this script to latest trinitycore. 

2. anyone can update this script to latest trinity? Script link : http://pastebin.com/rsv7ZDWM

3. i think if i can change elevator position where stay and come up fix this problem but why i can change elevator stay position? tnx so much 

**Branch(es)**: 3.3.5 latest tdb

**TC hash/commit**:  

**TDB version**:  

**Operating system**:  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
this is not for custom scripts.
