### ISSUE TITLE
[7.x.x] Core/Spells/Auras: Entangling Roots (339) Root problem

### ISSUE THREAD

**Issue by vanasis** [TrinityCore/TrinityCore#18030]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: SPELL_AURA_455 not implemented , and the root effect not working

**Current behaviour**:  No root When Casting Entangling Roots .
**Expected behaviour**: It should root the Victim .

**Steps to reproduce the problem**:

1. make a druid
2. use .level 109 command
3. switch to Feral spec or any spec with Entangling Roots
4. find a victim
5. Cast  spell 339(Entangling Roots )
6. now you can see the mob that he can walk and attack you ( but he has Entangling Roots active)

(You can use spells like taunt and test it with `.gm off` to look better)

**Temp solution for it :** 
![aura_455](https://cloud.githubusercontent.com/assets/2195153/19016794/715a4c78-8831-11e6-8d70-50c4597f863f.png)
here is a list of Spells with same Spell_Aura_455
lots of them has a root behavior( as same as Entangling Roots)
in the tooltip we can see : 
**ToolTip: Rooted.**

also we have another same spell aura effect in trinity core 
Aura Id 26 (SPELL_AURA_MOD_ROOT)
like 
ID - 512 Chains of Ice
ID - 6533 Net
and  ... 

here is a small list with SPELL_AURA_MOD_ROOT in legion 

![root](https://cloud.githubusercontent.com/assets/2195153/19016826/366a4e50-8832-11e6-958a-bc27728e8b16.png)

in this type of spells we can see another tooltip
**ToolTip: Immobilized.**

I think root / Immobilized has some small changes in legion and I need more help to find a good way .

and this is my solution use this with your own risk ( this is only for test )
Wish this help Trinity Team to find a better solving way

```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index 96bd54d..602442f 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -514,7 +514,7 @@ pAuraEffectHandler AuraEffectHandler[TOTAL_AURAS]=
     &AuraEffect::HandleNULL,                                      //452
     &AuraEffect::HandleNoImmediateEffect,                         //453 SPELL_AURA_CHARGE_RECOVERY_MOD implemented in SpellHistory::GetChargeRecoveryTime
     &AuraEffect::HandleNoImmediateEffect,                         //454 SPELL_AURA_CHARGE_RECOVERY_MULTIPLIER implemented in SpellHistory::GetChargeRecoveryTime
-    &AuraEffect::HandleNULL,                                      //455
+    &AuraEffect::HandleSpellAura555,                              //455 SPELL_AURA_455
     &AuraEffect::HandleNoImmediateEffect,                         //456 SPELL_AURA_CHARGE_RECOVERY_AFFECTED_BY_HASTE implemented in SpellHistory::GetChargeRecoveryTime
     &AuraEffect::HandleNoImmediateEffect,                         //457 SPELL_AURA_CHARGE_RECOVERY_AFFECTED_BY_HASTE_REGEN implemented in SpellHistory::GetChargeRecoveryTime
     &AuraEffect::HandleNULL,                                      //458 SPELL_AURA_IGNORE_DUAL_WIELD_HIT_PENALTY
@@ -6735,3 +6735,13 @@ void AuraEffect::HandlePlayScene(AuraApplication const* aurApp, uint8 mode, bool
         player->GetSceneMgr().CancelSceneByPackageId(sceneTemplate->ScenePackageId);
     }
 }
+
+void AuraEffect::HandleSpellAura555(AuraApplication const* aurApp, uint8 mode, bool apply) const
+{
+    if (!(mode & AURA_EFFECT_HANDLE_REAL))
+        return;
+
+    Unit* target = aurApp->GetTarget();
+
+    target->SetControlled(apply, UNIT_STATE_ROOT);
+}

```

```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.h b/src/server/game/Spells/Auras/SpellAuraEffects.h
index 03f3de4..d133db8 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.h
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.h
@@ -310,6 +310,7 @@ class TC_GAME_API AuraEffect
         void HandleOverridePetSpecs(AuraApplication const* aurApp, uint8 mode, bool apply) const;
         void HandleAllowUsingGameobjectsWhileMounted(AuraApplication const* aurApp, uint8 mode, bool apply) const;
         void HandlePlayScene(AuraApplication const* aurApp, uint8 mode, bool apply) const;
+        void HandleSpellAura555(AuraApplication const* aurApp, uint8 mode, bool apply) const;
 
         // aura effect periodic tick handlers
         void HandlePeriodicDummyAuraTick(Unit* target, Unit* caster) const;


```

**Branch(es)**: 7.x

**TC hash/commit**:  12a52595edf9ca284d9253a96396ef3321c4c094

**TDB version**:  TDB 6.04 ( with last updates till 10/1/2016 )

**Operating system**:  Windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by funjoker** [comment]
Entangling Root Spell: 339 is not the spell who roots.
It's probably linked to another spell. e.g. 40363, 66070.

:D

**Comment by vanasis** [comment]
unfortunately no , I search from sniff and don't see spells like root from sniff
I think my issue report is true and  SPELL_AURA_455  related to it.
We can wait for @Shauren  or other TC devs answer

however if we understand it is wrong , then accept my Apologize ;)
