### ISSUE TITLE
Gossip Menu Error

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#18031]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Custom Code does not accept Gossip Menus !

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. See Screenshot
2. 
3. 

![Image of Yaktocat](https://abload.de/img/gossiperroravbzx.png)

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
6fbf213e8c48+

**TDB version**:  

**Operating system**:  
Windows 10 Pro

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Vincent-Michael** [comment]
this belongs to forum on custom section.

**Comment by Shoxxo** [comment]
WTF ?! It is a generally Code struckt and you troll me with custom code forum blabla... Fick dich alter

**Comment by Aokromes** [comment]
telenpc works fine with custom gossips, so it's something on your side.

**Comment by Shoxxo** [comment]
Never it is bullshit, i checked your code and you changed the gossip code ! 

Old : https://github.com/TrinityCore/TrinityCore/blob/2d28d0c109fb58d5f5cd44814a9640bb7793b4cb/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp  -> Working very fine!

New : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/ScriptedAI/ScriptedGossip.h#L82

Thats totaly stupid to understand, why change a working system, have tooo much time ?! If it is, fix Ulduar Radio script with PlaySoundID if is player in Rango of Point xyz But noooooo fixxing stupid working functions... I charge it back

**Comment by DDuarte** [comment]
@Shoxxo: please leave
