### ISSUE TITLE
[3.3.5] Quest: Relevant Locations (12070)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18037]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
If you use the "Shard of the Earth" nothing happens,  you don't get the kill credit. 

http://www.wowhead.com/quest=12070/rallying-the-troops
https://www.youtube.com/watch?v=vjUB0gHHXVA
**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  
TC>TrinityCore rev. 050522a25b1d 2016-10-04 12:22:51 +0200 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sql + all updates

**Operating system**:  
Win7 64Bit

**Comment by Aokromes** [comment]
#16561
