### ISSUE TITLE
[3.3.5] Death Knight's spell Death Grip

### ISSUE THREAD

**Issue by DeActiver** [TrinityCore/TrinityCore#18041]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:if DK use spell Death Grip for target range attacker example Mage, Warlock, Priest, Hunter or same NPC range or speller that, characters or npc when jump stop sky and don't grip  DK .
![wowscrnshot_100516_102001](https://cloud.githubusercontent.com/assets/11397660/19104308/9ba272ee-8ae8-11e6-9d2b-7ab14508b0d3.jpg)

**Current behaviour**: stop sky and don't grip

**Expected behaviour**: must grip the earth Dk .

**Steps to reproduce the problem**:

1. must that time buff death grip characters or npc can't move or cast spells or maybe stun that time

**Branch(es)**: 3.3.5

**TC hash/commit**:  63215dd15a740b9182a518bb5588ce69153f4e35

**TDB version**:  61

**Operating system**:  Win 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by DeActiveDev** [comment]
Real this problem not is  important !! issues repeated old time

**Comment by MrSmite** [comment]
This might be a duplicate to #15632
