### ISSUE TITLE
[7.x] Male<->Female model  issue after teleport

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#18048]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The male player character model will look weird after teleport.

**Current behaviour:** The male character model changes to female.

**Expected behaviour:** Tell us what should happen instead
The male character model should stay male after teleport.

**Steps to reproduce the problem:**

1. login a male character
2. teleport to any other map (like from Kalimdor to Outland)
3. your model changes (male changes to female)

**Branch(es):** 3.3.5 / 6.x (Select the branch(es) affected by this issue)

**6.x**

**TC hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/a52c50e809d7c0ecb06a4eb81c73069d3c0e6746

**TDB version:**  TDB 6.04

**Operating system:**  Win7 x64

**this is my model**
![1](https://cloud.githubusercontent.com/assets/106937/19143772/9e46ff92-8bd8-11e6-882a-7d6d8f71dca5.jpg)

**this is how the model looks after teleport**
![2](https://cloud.githubusercontent.com/assets/106937/19143814/d3028094-8bd8-11e6-9b42-e7e84111018e.jpg)

![3](https://cloud.githubusercontent.com/assets/106937/19143830/e9f21026-8bd8-11e6-9621-08ffe09e8124.jpg)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by cooler-SAI** [comment]
damn, looks like gay party ))) LOL ))))

**Comment by emptyus** [comment]
HOT!!! lol

**Comment by frozen4** [comment]
look at the white plump hips
![4](https://cloud.githubusercontent.com/assets/106937/19145845/7be04930-8be3-11e6-9769-4e729b543623.jpg)

**Comment by searum** [comment]
And the blue model? Did you see a maleta char like a smurf? Haha

**Comment by streetrat** [comment]
Confirmed, but only happens from male to female
checked packet send out, no gender or model change is sent out
if you debug core you can see that model and gender are fine too
so NFI

**Comment by streetrat** [comment]
seems to only happen with human male characters, could not reproduce with any other race

**Comment by Krudor** [comment]
Saw this yesterday with another race, orc female model that appeared to have male orc skin on it

**Comment by streetrat** [comment]
SetByteValue(UNIT_FIELD_BYTES_0, UNIT_BYTES_0_OFFSET_GENDER, gender);
SetByteValue(PLAYER_BYTES_3, PLAYER_BYTES_3_OFFSET_GENDER, gender);

does not change back the player
is there any other stuff which changes gender?

**Comment by Kittnz** [comment]
Well yes there was, the gender is set by modelId

**Comment by streetrat** [comment]
smsg_update_object is fine too, data is the same after teleporting..
here is a packetlog: https://gist.github.com/streetrat/cc8ba64f1468a6bfd94fe1dd725a15b7

**Comment by frozen4** [comment]
druid change to blue after .unaura 768 [cat form](http://www.wowhead.com/spell=768/cat-form)
![3](https://cloud.githubusercontent.com/assets/106937/19415375/33196b3a-93a1-11e6-93aa-f8030f043f2a.jpg)

**Comment by cooler-SAI** [comment]
Legion have many surprizes))))

**Comment by Pixel-Pirate** [comment]
confirm it's very strange :p
