### ISSUE TITLE
Core/GameEvents: No "Soon" Objects spawned before the actual game event.

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#18043]
**Description**: Game Events don't have "soon" gameobjects spawned before the actual date of the game event. For example, Darkmoon "Soon" objects are spawned just before Darkmoon actually starts. Another example is Brewfest, on the place where brewfest place is there are gameobjects "Brewfest Soon!" spawned. And you can see npc's working building it, same with darkmoon.

**Current behaviour**: Objects, NPC's etc get spawned on the date they should be spawned.

**Expected behaviour**: there is no "Soon" objects before the event spawned.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
Both

**TC hash/commit**:  dac44a59b43e3857a074ea53cfb35d4ba6298bdb

**TDB version**:  61

**Comment by Killyana** [comment]
I think, It's a pre event not the same one.

**Comment by Kittnz** [comment]
Oh that could it be also. I haven't checked DBC's yet.

**Comment by SnapperRy** [comment]
I know for certain that there are pre-events for the Darkmoon Faire in db. Not sure if the timeframes are right, though.

**Comment by Killyana** [comment]
Darkmoon Faire Building (Elwynn Forest) : 23 It's the only pre-event on the DB

**Comment by funjoker** [comment]
It's an db Problem only :).

**Comment by Kittnz** [comment]
Well there should be more of these, Shattrath and Thunderbluff should get the building too.
Also brewfest has a building event. But i wonder where they got the data for that.

**Comment by Killyana** [comment]
We have some sniffs with this gameobject: http://wotlk.openwow.com/object=186217

**Comment by Kittnz** [comment]
Iron Forge Brewfest building was added in a new game event: https://github.com/TrinityCore/TrinityCore/commit/e7c5fc4df62c06e81b1dd55bdd10c314ea6ca5e7

Still missing Orgrimmar one, no sniffs for that one.

Also for Darkmoon Faire in Thunderbluff there is no event and no sniff data either.
