### ISSUE TITLE
Brewfest: Event related discrepancies

### ISSUE THREAD

**Issue by Thulium-Drake** [TrinityCore/TrinityCore#18049]
**Description**:
The Brewfest Revelers in the following cities are not transformed correctly (https://github.com/TrinityCore/TrinityCore/issues/16129#issuecomment-251781688)

EDIT: Moved Defiler/League of Arathor issues to new ticket

**Current behaviour**: Tell us what happens
-   Darnassus - They're all Goblins
-   Shattrath - They're all Goblins, but also the commoners that give out the quests are only Goblins
-   Some cities have a more varied population of Revelers then others (e.g. Ironforge has a mixture of Draenei, Gnomes and Dwarves), but that's not really an issue imho.

**Expected behaviour**: Tell us what should happen instead
- Darnassus, I'd expect Night Elfs (or a mix of Alliance races)
- Shattrath, I'd expect a mix of all races (or Blood Elf / Draenei)

**Steps to reproduce the problem**:
1. Check them out in Shattrath/Darnassus/Dalaran
2. ???
3. Profit

**Branch(es)**: 3.3.5 

**TC hash/commit**:  e1bafd6

**TDB version**:  TDB_full_335.61_2016_04_11 + updates that came with the git pull of e1bafd6

**Operating system**:  Debian Jessie

**Comment by Aokromes** [comment]
post that on the same issue you have found.

**Comment by Kittnz** [comment]
IE: make seperate issue tickets for each issue. Defiler Emissaries is not related to brewfest and vice versa.

**Comment by Thulium-Drake** [comment]
I've split the issues off in multiples, is this issue still subject to be closed?

**Comment by Killyana** [comment]
I didn't checked any "Brewfest Revelers" they are not the same npcs as Commoners.
Models are handled via auras that must be set on creature_addon.

**Comment by Kittnz** [comment]
Exactly but for some reason, they do not get transform with the aura while they have the right aura in creature_addon. I thought at first some of the spawns were bad so i got my sniffed data and deleted and replaced them with fresh info and it turned out the same as before lol. So there must be some core aura issue here i think. @ariel-

**Comment by Killyana** [comment]
I don't have any problem with setting this auras.
http://woehead.way-of-elendil.fr/?spell=43913 for example will load a night elf model,  4 models are possible 2 males and 2 females.

**Comment by Kittnz** [comment]
Checkout the Brewfest Revelers in Shattrath, there should be 3 groups, 3 horde, one just goblins (4 of them) and 3 ally's. If i recall they have the right aura but they do not change appearance.

**Comment by Killyana** [comment]
Right, the aura doens't morph, for npcs that have the correct model it's set via modelid on creature table.

**Comment by Kittnz** [comment]
i don't think that's really blizzlike tho

**Comment by Killyana** [comment]
Yes the model must be handled by the aura, but I don't know why the .cast and .aura the spell change the model, but setting it on creature_addon doesn't, even if the .list aura shows the aura on the npc.

**Comment by tkrokli** [comment]
I don't know enough about auras, but could it have anything to do with where in the list the aura is placed on the NPC, like if there is a difference in when the aura is received from `creature_addon` compared to when it is received from spell cast / aura command?

**Comment by Kittnz** [comment]
It does work in other locations. It's just not working for darnassus and shattrath

**Comment by tkrokli** [comment]
That is quite odd, almost like the issue a colleague of mine had with a projector that only worked on the ground floor, not on any of the higher floors of the building where he held beginners' computer courses.

If I didn't know better, I would guess there could be something in the zone scripts, but that is unlikely.

**Comment by ariel-** [comment]
Should've been fixed by c3a2bd32cf675d00081ffd447c93d31d48456ca2. Can confirm?

**Comment by Kittnz** [comment]
Ill test tonight @ariel- .

**Comment by Aokromes** [comment]
poke @Kittnz

**Comment by Kittnz** [comment]
works!
