### ISSUE TITLE
[6.x] Unable to Create Gnome Hunter

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/TrinityCore#18047]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Can not create gnome hunters

**Current behaviour**: When you try to create a gnome hunter, you receive a client error "Error cannot create character"

**Expected behaviour**: Should be able to create a gnome hunter as of Legion

**Steps to reproduce the problem**:

1. Login to character selection screen
2. Choose the Gnome race
3. Select the Hunter class and try to complete the creation process

**Branch(es)**: 6.x

**TC hash/commit**:  a52c50e809d7c0ecb06a4eb81c73069d3c0e6746

**TDB version**:  6.04

**Operating system**:  Windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Kittnz** [comment]
Only blood elf & night elf can?

**Comment by OrzelBialy** [comment]
@Kittnz I'm talking about Hunters, not Demon Hunters.
