### ISSUE TITLE
[3.3.5]Weapon skill don't gain

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18044]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Weapon skill don't gains

1.Make a Mage or wath ever you want  and melee damage with a Staff or Axe. 

**Branch(es)**: 3.3.5 

**TC hash/commit**:  
TC>TrinityCore rev. b5e8e0a5db69 2016-10-05 03:10:05 -0300 (335 branch)
**TDB version**:  
TDB_full_world_335.61_2016_04_11.sq + all updates
**Operating system**:  
Win7 64Bit

**Comment by Aokromes** [comment]
Are you trying to do it vs a training dummy? if yes, it's blizzlike don't gain skill.

**Comment by Tauriella** [comment]
I attack only Creatures and have no skillgain
