### ISSUE TITLE
Speaking with patrolling NPC's leaves them standing

### ISSUE THREAD

**Issue by Thulium-Drake** [TrinityCore/TrinityCore#18051]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Speaking with patrolling NPC's leaves them standing

**Current behaviour**: Tell us what happens
-   Talking with the walking Defiler Emissaries in Undercity's Inner Canal ring seems to leave them standing
-   Same thing for the City Guards in different cities
- When the zone is reloaded, the NPC can be seen moving around again.

**Expected behaviour**: Tell us what should happen instead
- Talking with a moving NPC shouldn't stop them from resuming their patrol/stroll around the city after the converstation is finished.

**Steps to reproduce the problem**:

1. Walk up to a NPC on patrol
2. End the conversation
3. Observe how the NPC just stands around

**Branch(es)**: 3.3.5 

**TC hash/commit**:  e1bafd6

**TDB version**:  TDB_full_335.61_2016_04_11 + updates that came with the git pull of e1bafd6

**Operating system**:  Debian Jessie

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
I am sure this is duplicate but the keywords to find it are to common :/

**Comment by Thulium-Drake** [comment]
I tried searching for 'Talking Guard' and 'Speaking Guard' in all (open and closed) issues, but couldn't find one that relates to this.

**Comment by Kittnz** [comment]
Maybe you just think it's a general problem so you think there is a issue ticket open for it xD. I already had that before.

**Comment by Aokromes** [comment]
#8976

**Comment by tkrokli** [comment]
Conclusion: the important keywords here are `waypoint` + `interaction` .
