### ISSUE TITLE
Crash:: GridMap::getHeightFromUint16

### ISSUE THREAD

**Issue by Magoxx** [TrinityCore/TrinityCore#18059]
[crashlog_2016-10-09_02-44-20.txt](https://github.com/TrinityCore/TrinityCore/files/518137/crashlog_2016-10-09_02-44-20.txt)

**Description**: Server crash

**Current behaviour**: Crash in GridMap

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Dont know how to reproduce it
2. 
3. 

**Branch(es)**: 6.x 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/d1ae3ccb220f7582690dc849a8fb7bd37f4a2f18

**TDB version**:  6.04

**Operating system**:  Ubuntu Server 16.04.1 LTS

**Comment by Aokromes** [comment]
Ubuntu server 14 is unsuported, upgrade.

**Comment by Magoxx** [comment]
sorry is ubuntu 16

**Comment by n4ndo** [comment]
how frecuently @Magoxx?

**Comment by Aokromes** [comment]
over 1 year since the last crash report, if this bug is still valid, plz open a new ticket with updated core.
