### ISSUE TITLE
warnings logs 3.3.5

### ISSUE THREAD

**Issue by hlainin** [TrinityCore/TrinityCore#18054]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: When I build the server warnings appear 

**Current behaviour**: appear 

> src/server/game/Spells/Auras/SpellAuras.h:293:40: warning: ‘UnitAura::m_AuraDRGroup’ is too small to hold all values of ‘enum DiminishingGroup’
>          DiminishingGroup m_AuraDRGroup:8;               // Diminishing

**Expected behaviour**: these warnings should not be

**Steps to reproduce the problem**:

1. to compile the server

**Branch(es)**: 3.3.5

**TC hash/commit**:  [b0273837](https://github.com/TrinityCore/TrinityCore/commit/b0273837049ffbd99fbea2d71a9d9feb38e70f1f)

**TDB version**:  TDB 335.61

**Operating system**:  Debian

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by DDuarte** [comment]
Warnings aren't errors. They might or might not be fixed.
