### ISSUE TITLE
[6.x] Unable to Create Gnome Hunter

### ISSUE THREAD

**Issue by OrzelBialy** [TrinityCore/TrinityCore#18052]
**Description**: Can not create gnome hunters. Original issue here: https://github.com/TrinityCore/TrinityCore/issues/18047

Collaborator read too fast and assumed "Hunter" means "Demon Hunter", then closed the issue. I'm talking about the hunter class. i.e. this class: https://worldofwarcraft.com/en-us/news/19911277/legion-class-preview-series-hunter

**Current behaviour**: When you try to create a gnome hunter, you receive a client error "Error cannot create character"

**Expected behaviour**: Should be able to create a gnome hunter as of Legion

**Steps to reproduce the problem**:
1. Login to character selection screen
2. Choose the Gnome race
3. Select the Hunter class and try to complete the creation process

**Branch(es)**: 6.x

**TC hash/commit**:  a52c50e809d7c0ecb06a4eb81c73069d3c0e6746

**TDB version**:  6.04

**Operating system**:  Windows 10

**Comment by OrzelBialy** [comment]
@Kittnz Talking about Hunters, not Demon Hunters.

**Comment by Kittnz** [comment]
Oh, alright then =) my bad

**Comment by Regigicas** [comment]
```sql
DELETE FROM playercreateinfo_cast_spell WHERE racemask = 64 AND classMask = 4;
INSERT INTO playercreateinfo_cast_spell(racemask, classmask, spell, note) VALUES
(64, 4, 153724, 'Gnome - Hunter - Mechanical Bunny');

DELETE FROM playercreateinfo WHERE race = 7 AND class = 3;
INSERT INTO playercreateinfo(race, class, map, zone, position_x, position_y, position_z, orientation) VALUES
(7, 3, 0, 5495, -4983.42, 877.7, 274.31, 3.06393);

DELETE FROM playercreateinfo_action WHERE race = 7 AND class = 3;
INSERT INTO playercreateinfo_action(race, class, button, `action`, `type`) VALUES
(7, 3, 0, 193455, 0),
(7, 3, 9, 20589, 0),
(7, 3, 10, 982, 0),
(7, 3, 11, 9, 48);

DELETE FROM player_levelstats WHERE race = 7 AND class = 3;
INSERT INTO player_levelstats(race, class, `level`, str, agi, sta, inte) VALUES
(7, 3, 1, 5, 10, 11, 13);
```
still missing stats for level > 1

**Comment by streetrat** [comment]
Can confirm, missing base stats for gnome hunter

**Comment by funjoker** [comment]
Will provide fix soon =)
Missed to add it before

**Comment by tkrokli** [comment]
... and here I was, thinking that "gnome hunters" were Tauren players who wanted to stomp on gnomes...  ;-)

**Comment by Aokromes** [comment]
from funjoker:



_Thanks to @Regigicas_ 
```
DELETE FROM playercreateinfo_cast_spell WHERE racemask = 64 AND classMask = 4;
INSERT INTO playercreateinfo_cast_spell(racemask, classmask, spell, note) VALUES
(64, 4, 153724, 'Gnome - Hunter - Mechanical Bunny');

DELETE FROM playercreateinfo WHERE race = 7 AND class = 3;
INSERT INTO playercreateinfo(race, class, map, zone, position_x, position_y, position_z, orientation) VALUES
(7, 3, 0, 5495, -4983.42, 877.7, 274.31, 3.06393);

DELETE FROM playercreateinfo_action WHERE race = 7 AND class = 3;
INSERT INTO playercreateinfo_action(race, class, button, `action`, `type`) VALUES
(7, 3, 0, 193455, 0),
(7, 3, 9, 20589, 0),
(7, 3, 10, 982, 0),
(7, 3, 11, 9, 48);
```

**Comment by funjoker** [comment]
news?

**Comment by OrzelBialy** [comment]
Sorry for the late reply. Using the statements posted by Aokromes and Regigicas works, I can create the gnome hunter. Someone from the TC team can commit that now

**Comment by funjoker** [comment]
Can someone make a SQL Update to TC?

**Comment by funjoker** [comment]
@DDuarte can you check that?
