### ISSUE TITLE
[7.x] Core/Packets: Field QuestPackageID in SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE packet

### ISSUE THREAD

**Issue by Druson** [TrinityCore/TrinityCore#18056]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
incorrect field QuestPackageID position in SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE:
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Server/Packets/QuestPackets.cpp#L293
```cpp
    _worldPacket << int32(PortraitTurnIn);  
    _worldPacket << int32(PortraitGiver);
    _worldPacket << int32(QuestPackageID);  
```

**Current behaviour**: Tell us what happens
QuestPackageID was moved below PortraitGiver. No reward item of the QuestPackageID can be shown in the quest completion dialog if no reward item is defined in the quest_template. But the  reward item can be shown in the quest detail dialog.

**Expected behaviour**: Tell us what should happen instead
According to the sniffing data, QuestPackageID should be put before PortraitTurnIn.I.e.:
```cpp
    _worldPacket << int32(QuestPackageID);  
    _worldPacket << int32(PortraitTurnIn);  
    _worldPacket << int32(PortraitGiver);
```
Reward item of the QuestPackageID is shown in the quest completion dialog.

**Steps to reproduce the problem**:
The quest reward item in the table quest_template is 0. The QuestPackageID for the quest 40077 is 714.
According to QuestPackageItem.db2, the reward item for QuestPackageID 714 is 128953, which can be shown in the quest detail dialog.

1. .quest add [40077 (The Invasion Begins)](http://www.wowhead.com/quest=40077/the-invasion-begins)
2. .quest complete 40077
3. The quest reward item ([128953, Treads of Illidari Supremacy](http://www.wowhead.com/item=128953/treads-of-illidari-supremacy)) can not be shown in the quest completion dialog. After completing the quest, you can not find the item [128953](http://www.wowhead.com/item=128953/treads-of-illidari-supremacy) in your bags either.

**Branch(es)**: 6.x 

**TC hash/commit**:  f99bb81402a15d3a86bfd38ff6a06d2fb271fb04

**TDB version**:  6.04

**Operating system**:  Win10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
OK, so if you were to create a PR to fix this, it would look something like this:
```diff
diff --git a/src/server/game/Server/Packets/QuestPackets.cpp b/src/server/game/Server/Packets/QuestPackets.cpp
index 6e45f79..8f784ed 100644
--- a/src/server/game/Server/Packets/QuestPackets.cpp
+++ b/src/server/game/Server/Packets/QuestPackets.cpp
@@ -288,9 +288,9 @@ ByteBuffer& operator<<(ByteBuffer& data, WorldPackets::Quest::QuestGiverOfferRew
 WorldPacket const* WorldPackets::Quest::QuestGiverOfferRewardMessage::Write()
 {
     _worldPacket << QuestData; // WorldPackets::Quest::QuestGiverOfferReward
+    _worldPacket << int32(QuestPackageID);
     _worldPacket << int32(PortraitTurnIn);
     _worldPacket << int32(PortraitGiver);
-    _worldPacket << int32(QuestPackageID);
 
     _worldPacket.WriteBits(QuestTitle.size(), 9);
     _worldPacket.WriteBits(RewardText.size(), 12);
```
Could you edit your "Current behaviour" & "Expected behaviour" info to explain what happens in-game?

**Comment by Druson** [comment]
the  field  packageID is binding to the  quest reward item in the db2 file. so  if the reward item in quest template is 0,  after complete the quest, you should get the reward item which is binding to  the  package id.

**Comment by Druson** [comment]
the  field  packageID is binding to the  quest reward item in the db2 file. so  if the reward item in quest template is 0,  after complete the quest, you should get the reward item which is binding to  the  package id.

**Comment by Druson** [comment]
@tkrokli updated.

**Comment by tkrokli** [comment]
Have you tested this change and seen that the result is that the quest works as intended, that the reward is shown in the Quest Reward gossip dialog after the change has been applied?

**Comment by Druson** [comment]
@tkrokli Yes, I have tested it in game. The reward item can be shown in the Quest Reward gossip dialog.

**Comment by tkrokli** [comment]
"The powers that be" object to this solution, it won't be added to TC source.

Quote:
```
you do not change packet structures without checking client code. EVER
```

**Comment by tkrokli** [comment]
OK, seems that I was sort of right in my original assessment of this, but for the wrong reasons.
I was not aware of and could not check this info in client code (from a decompiled game client).
