### ISSUE TITLE
Core/DataStores: TaxiMaskSize is not large enough

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18055]
Description: Can not load world server

Initialize data stores...

/home/XXXX/TrinityCore/src/server/game/DataStores/DB2Stores.cpp:842 in LoadStores ASSERTION FAILED:
  TaxiMaskSize >= ((sTaxiNodesStore.GetNumRows() - 1) / 8) + 1 TaxiMaskSize is not large enough to contain all taxi nodes! (current value 236, required 239)
Segmentation fault (core dumped)

Current behaviour: World fails to load on Data Stores with TaxiMaskSize Error

Expected behaviour: Value should be 239

Steps to reproduce the problem:

    Git pull origin
    CMAKE
    make
	make insstall
	./worldserver

Branch(es): 6.x

TC hash/commit: 015bc75

TDB version: 6.04

Operating system: Ubuntu 16 i386 Server

**Comment by tkrokli** [comment]
75d7577 is not in the TrinityCore commit list. How different is your source from TrinityCore?

**Comment by Keldo** [comment]
Hang on I think I copied it wrong, it's 015bc75

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/blob/015bc75d7577b6832f9152d8c26f9a74630a0f16/src/server/game/DataStores/DBCEnums.h#L749
```cpp
#define TaxiMaskSize 236
```
Check if it works if you change 236 to 239 in that line.

**Comment by Keldo** [comment]
Checking now, its a 2.5 hour build for me on this server

**Comment by Keldo** [comment]
That Fixed it

**Comment by tkrokli** [comment]
OK, that fixed it for you, but we need to test if this is the case for all users and verify if that is the correct solution. Re-opening until the issue has been confirmed/disproved/solved.

**Comment by tkrokli** [comment]
TrinityCore rev. 015bc75d7577 2016-10-07 12:05:48 -0300 (6.x branch) (Win64, Release, Static) 
```
>> Applied 27 queries. Containing 0 new and 61 archived updates.
Realm running as realm ID 1
Using World DB: TDB 6.04
Using enUS DBC Locale
Missing name MonsterSight in config file C:/Program Files/TrinityCore_6x/worldserver.conf, add "MonsterSight = 50.000000" to this file
Missing name GuarderSight in config file C:/Program Files/TrinityCore_6x/worldserver.conf, add "GuarderSight = 50.000000" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps
Missing name Guild.SaveInterval in config file C:/Program Files/TrinityCore_6x/worldserver.conf, add "Guild.SaveInterval = 15" to this file
Missing name Guild.UndeletableLevel in config file C:/Program Files/TrinityCore_6x/worldserver.conf, add "Guild.UndeletableLevel = 4" to this file
Loading Trinity strings...
>> Loaded 1054 trinity strings in 3 ms
Initialize data stores...

C:\github.com\tkrokli\TrinityCore\src\server\game\DataStores\DB2Stores.cpp:844 in DB2Manager::LoadStores ASSERTION FAILED:
  TaxiMaskSize >= ((sTaxiNodesStore.GetNumRows() - 1) / 8) + 1 TaxiMaskSize is not large enough to contain all taxi nodes! (current value 236, required 239)
```
Will test the change suggested by the error message (no other TC users running current 6.x these days?)

**Comment by Keldo** [comment]
Glad to help identify and fix, I'm in school for C++ so hopefully I can help out more soon.
