### ISSUE TITLE
Creatures not attacking? [3.3.5]

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18068]
Description: A pal of mine said he could solo the deadmines by using various points thatd bug the creatures into being unable to attack him. Said that was nonsense, but check this:

http://puu.sh/rF38h/cf51f96b73.jpg

Current behavior: Currently he is standing in a spot with 5+ NPCs around him, and their not doing anything. Their all in combat with him but not attacking?

**Expected behaviour**: They should whoop his ass?

**Steps to reproduce the problem**: He stood in position: .go xyz -158.651993 -513.984009 52.754101 36

**Branch(es)**: 3.3.5 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/b8a1a18a5a44185c0e84d23910c35ebf2706e1b5

**TDB version**:  TDB 335.61

**Operating system**:  Ubuntu 14.04

**Comment by Persephone** [comment]
Nothing has been modified in the instance at all, everything is as if trinitycore was just downloaded and installed

**Comment by Aokromes** [comment]
http://i.imgur.com/eg2ryM6.jpg

**Comment by Persephone** [comment]
Got no clue how to reproduce it then o.0 Wtfffff

**Comment by Persephone** [comment]
Pretty sure I extracted it recently. Also wouldnt the core act up if the mmaps are extracted with an older extractor?

**Comment by Persephone** [comment]
Try go here aokromes: go xyz -158.069626 -522.524109 55.916862 36

On top of the drill: http://puu.sh/rF4G1/0ba59da598.jpg

Their just standing there unable to attack but i can freely kill them 1 by 1

**Comment by jackpoz** [comment]
check if you have vmaps/mmaps enabled in the configs and check if there are any logs about mmaps not found (did someone actually move these logs to debug recently ?)

**Comment by Persephone** [comment]
All mmap/vmap configs are enabled, let me see if i can find anything in logs

**Comment by Persephone** [comment]
this is enabled: Logger.mmaps=3,Server

anything else I need?

**Comment by Aokromes** [comment]
http://i.imgur.com/krxk5Rr.jpg

**Comment by Aokromes** [comment]
and #9206

**Comment by Persephone** [comment]
Would you suggest I try and re-extract the mmaps ?

**Comment by Persephone** [comment]
@Aokromes  would you be able to upload your vmaps/mmaps? Am extracting again now, but if it doesnt fix itd love to try with yours if youd have the time to upload them

would be sweet

**Comment by Tauriella** [comment]
Your Players have GM Mode ?

**Comment by tkrokli** [comment]
I was thinking the same, that yellow NPC names suggest GM mode on the player, although I am uncertain if that is because the GM in question is looking at a normal player or not (2 separate players in the images).

**Comment by Tauriella** [comment]
I have testet and all NPC's aggro for my Player Chars

**Comment by tkrokli** [comment]
Yes, hence the label [Invalid-CannotReproduce] - it is a local problem for the issue poster only.

**Comment by Persephone** [comment]
Was me spectating a pal who bugged it.

Well, if any of you cant reproduce and I am litereally at the latest revision atm with no custom changes added. It has to be the mmaps not working properly. Just finished re-extracting them. Could some of you who says it works upload their vmaps/mmaps? So I could give that a go? would be tons appreciated

**Comment by tkrokli** [comment]
@Persephone : contact me in #trinity @ irc.rizon.net to get a link. I don't like sharing them in the TC repo.

**Comment by Persephone** [comment]
am on now are you on irc?

**Comment by tkrokli** [comment]
Yes, I saw you logged in and logged out again after 4 minutes. I use the username / nick tkrokli there too.

**Comment by Persephone** [comment]
How do i whisper you?

**Comment by tkrokli** [comment]
Just double-click my name or ask in the main channel.

**Comment by Persephone** [comment]
sent ya a pm there

**Comment by Persephone** [comment]
@tkrokli I Pm'ed you there

**Comment by tkrokli** [comment]
Sorry, I haven't seen any notification at all.
Please contact me in the Forum instead, if it gets too difficult to talk in #trinity @ irc.rizon.net
https://community.trinitycore.org/profile/18673-tkrokli/
