### ISSUE TITLE
Crash:: std::_Hashtable<unsigned int, std::pair<unsigned int const, CellObjectGuids>

### ISSUE THREAD

**Issue by Magoxx** [TrinityCore/TrinityCore#18065]
**Description**: Server crash with 10 ppl

**Current behaviour**: Server crash

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Dont know how to reproduce crash
2. 
3. 

**Branch(es)**: 6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/d1ae3ccb220f7582690dc849a8fb7bd37f4a2f18

**TDB version**:   6.04

**Operating system**:  Ubuntu server 16.04.1 LTS

[backtrace.txt](https://github.com/TrinityCore/TrinityCore/files/518522/backtrace.txt)

**Comment by n4ndo** [comment]
how frecuently @Magoxx?

**Comment by Aokromes** [comment]
no one else having this crash after a more than a year. closing, if this bug is still valid open a new ticket with updated core.
