### ISSUE TITLE
Crash:: std::_Rb_tree_increment(std::_Rb_tree_node_base const*)

### ISSUE THREAD

**Issue by Magoxx** [TrinityCore/TrinityCore#18060]
**Description**: Server crash

**Current behaviour**: Server crash with 10 ppl online.

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Dont know how reproduce it
2. 
3. 

**Branch(es)**: 6.x

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/d1ae3ccb220f7582690dc849a8fb7bd37f4a2f18

**TDB version**:  6.04
[crashlog_2016-10-08_23-31-24.txt](https://github.com/TrinityCore/TrinityCore/files/518136/crashlog_2016-10-08_23-31-24.txt)

**Operating system**:  Ubuntu server 16.04.1 LTS

**Comment by Aokromes** [comment]
Ubuntu server 14 is unsuported, upgrade.

**Comment by Magoxx** [comment]
sorry is ubuntu 16

**Comment by n4ndo** [comment]
how frecuently @Magoxx?

**Comment by Aokromes** [comment]
no one else having this crash after a more than a year. closing, if this bug is still valid open a new ticket with updated core.
