### ISSUE TITLE
[3.3.5] Quest: Post-partum Aggression (12614)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18079]
**Description**: If you sit on the [Mammoth](http://www.wowhead.com/npc=28468/stampy) and you kill [Broodmother Slivina](http://www.wowhead.com/npc=28467/broodmother-slivina), you don't get the kill credit.

If you kill the Broodmother Slivina without  the Mammoth, you get the kill credit.
- https://www.youtube.com/watch?v=x90pRt_bHnE
- http://www.wowhead.com/quest=12614/post-partum-aggression
- http://www.wowhead.com/npc=28468/stampy

**Current behaviour**: Tell us what happens
If you sit on the mammoth [Stampy](http://www.wowhead.com/npc=28468/stampy) and you kill [Broodmother Slivina](http://www.wowhead.com/npc=28467/broodmother-slivina), you don't get the kill credit.

**Expected behaviour**: Tell us what should happen instead
If you sit on the mammoth [Stampy](http://www.wowhead.com/npc=28468/stampy) and you kill [Broodmother Slivina](http://www.wowhead.com/npc=28467/broodmother-slivina), you get the kill credit.

**Steps to reproduce the problem**:
1. Get the quest [**Post-partum Aggression**](http://www.wowhead.com/quest=12614/post-partum-aggression) (from [Dorian Drakestalker](http://www.wowhead.com/npc=28376/dorian-drakestalker)), either by adding it manually via GM  command or by doing all the [The Sholazar Safari quest chain](http://wow.gamepedia.com/The_Sholazar_Safari_quest_chain) quests required for the achievement [**The Snows of Northrend**](http://wow.gamepedia.com/The_Snows_of_Northrend) (Complete all of Hemet Nesingwary quests in Northrend up to and including Post-partum Aggression.)
2. Use the mammoth [Stampy](http://www.wowhead.com/npc=28468/stampy) and proceed to kill [Broodmother Slivina](http://www.wowhead.com/npc=28467/broodmother-slivina) by using [Stampy's abilities](http://www.wowhead.com/npc=28468/stampy#controlled-abilities).
3. Notice that you you neither get the kill credit nor the achievement.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  TC>TrinityCore rev. 1667dd3b7ad9 2016-10-13 01:23:02 -0300 (335 branch)

**TDB version**:  TDB 335.61 + updates up to and including  2016_10_12_04_world_335.sq

**Operating system**:  Win7 64Bit

**Comment by el-druida** [comment]
Just add a kill credit via SAI

**Comment by tkrokli** [comment]
@SnapperRy , do you have time to comment on this issue? Stampy has no lines in `smart_scripts` , even though `AIName = SmartAI` . Broodmother Slivina (also SmartAI) only has 2 in combat abilities in SAI.

**Comment by Killyana** [comment]
This doesn't require any extra SAI the kill credit is http://www.wowhead.com/npc=28467/broodmother-slivina if there's no credit so there's an issue related to plyyers that doesn't get credit if they kill npcs with vehicles.

**Comment by el-druida** [comment]
c'mon 

-- Hemet Nesingwary 
SET @ENTRY := 28451;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,0,0,2300,3900,11,51742,64,0,0,0,0,2,0,0,0,0,0,0,0,"Hemet Nesingwary - Combat CMC - Cast 'Arcane Shot'"),
(@ENTRY,0,1,0,5,0,100,0,0,0,0,28467,33,28467,0,0,0,0,0,21,10,0,0,0,0,0,0,"Hemet Nesingwary - On Killed Unit - Quest Credit ''");

-- Stampy
SET @ENTRY := 28468;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,5,0,100,0,0,0,0,28467,33,28467,0,0,0,0,0,21,10,0,0,0,0,0,0,"Stampy - On Killed Unit - Quest Credit ''");

**Comment by Killyana** [comment]
works correctly on rev. 82c532dc239d
