### ISSUE TITLE
[7.x] Crash::Player::UpdateEnchantTime

### ISSUE THREAD

**Issue by Magoxx** [TrinityCore/TrinityCore#18074]
**Description**: when system try to update enchant time server crash

**Current behaviour**: when system try to update enchant time server crash

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**: i dont know exactly
1. i dont know exactly
2. 
3. 

**Branch(es)**: 6.x 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/53e15de4bfef27a137e1a9c3d3c0e4d5d771695f

**TDB version**:  6.04

**Operating system**:  Ubuntu server 16.04.1 LTS
[crashlog_2016-10-11_21-21-41.txt](https://github.com/TrinityCore/TrinityCore/files/523075/crashlog_2016-10-11_21-21-41.txt)

**Comment by Shauren** [comment]
Fixed in 9bce02b06a85d2f04cfe2485a094c4a7d9c7cef8
