### ISSUE TITLE
[3.3.5] DB/Quest: Rivenwood Captives (11296)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18076]
**Description**:
[Rivenwood Captives](http://www.wowhead.com/quest=11296/rivenwood-captives) / [Cocoons](http://www.wowhead.com/npc=24210/riven-widow-cocoon) are either empty or they only spawn a [Freed Winterhoof Longrunner](http://www.wowhead.com/npc=24211/freed-winterhoof-longrunner).

**Current behaviour**: Tell us what happens
The Quest itself works, but if you attack the Cocoon, only a Freed Winterhoof Longrunner comes out or the Cocoon is empty.

**Expected behaviour**: Tell us what should happen instead

Either a random creature (from the nearby area) or a Freed Winterhoof Longrunner comes out from the Cocoon if you attack.
- http://www.wowhead.com/quest=11296/rivenwood-captives
- http://www.wowhead.com/npc=24210/riven-widow-cocoon
- http://www.wowhead.com/npc=24211/freed-winterhoof-longrunner
- https://www.youtube.com/watch?v=jlMIKFYbUdI

"Very similar to the quest in Terrokar forest: http://www.wowhead.com/quest=10873/taken-in-the-night if you remember that."

**Branch(es)**: (3.3.5 / 6.x): **3.3.5**

**TC hash/commit**:   TC>TrinityCore rev. 00ad5b2d6790 2016-10-12 12:50:11 +0200 (335 branch)

**TDB version**:  TDB 335.61 + updates up to and including `2016_10_12_02_world.sql`

**Operating system**:  Win7 64Bit

**Comment by Staleness89** [comment]
Also related to this quest, the cocoons attacks you if you strike it in melee range.

**Comment by Kensaki** [comment]
the cocoons also grant experience. They shouldn't.

`UPDATE `creature_template` SET `flags_extra`=`flags_extra`|64 WHERE `entry`=24210;`

**Comment by Staleness89** [comment]
I think this should be closed. #18094

**Comment by tkrokli** [comment]
Thanks, good point. If you had included this text line in the commit message in your first commit in the PR:
```
Closes #18094
```
@TrinityCoreBot would have closed it automatically.

**Comment by Staleness89** [comment]
yes I figured it was my fault. Just happened to see it now.
