### ISSUE TITLE
Cheetah & Stealth Issues [3.3.5]

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18075]
**Description**: Proc issues with stealth and aspect of the cheetah.

**Current behaviour**:  Aspect of the cheetah do not proc Daze when struck by spells (tested with mage firball and frostball).  When struck by melee hits or abilities daze procs fine.

Stealth do not break when hit by enemy dots and you can walk over hunter traps, and they sometimes will just go away without triggering any damage.

**Expected behaviour**: Cheetah should proc daze when being hit by spells as well. And stealth should break when hit by dots and walking one very trap.

**Steps to reproduce the problem**: Hit a hunter with frostbolt while cheetah is on, and stealth get hit by dots while in stealth & walk over hunter immolation trap.

NOTE: Both spells worked fine before the new QAston proc system: https://github.com/TrinityCore/TrinityCore/commit/e641d0c7d71bdb21e443bf52bf508b1581e07839

**Branch(es)**: 3.3.5 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/9128e377e0d4e028c61ccc1e7b4fd778852ec177

**TDB version**:  TDB 335.61

**Operating system**:  Ubuntu 14.04

**Comment by ariel-** [comment]
Stealth against traps is another issue, preexistent: #10179
