### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#18082]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
````
2016-10-14_16:19:29 SmartScript: Entry 31105 has events but no events added to list because of instance flags.
````
**Steps to reproduce the problem**:
1. get inside ahn'kahet and go near jedoga area

**Branch(es)**: 3.3.5 

**TC hash/commit**:  8167d6d4a0a38f2499aa8b84b9976bc1d5b5ccd2

**Comment by Killyana** [comment]
The SAI is correct, this informtion is not supposed to be shown on the console.

**Comment by ccrs** [comment]
I saw that error on normal mode btw
