### ISSUE TITLE
[7.x] spell target wrong

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#18087]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: player get damage from self spell and some buff display debuff

**Current behaviour**: player get damage from self spell

**Expected behaviour**: player's damage spell only damage enemy, not player self 

**Steps to reproduce the problem**:

1. login a rogue and select an enemy
2. .cast 51723[Fan of Knives](http://www.wowhead.com/spell=51723) or .cast 199804 [between the eyes](http://www.wowhead.com/spell=199804)
3. player will get damage from self spell

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  https://github.com/TrinityCore/TrinityCore/commit/26de86177eef83e9fd3d3600dfc354ed4c816df2

**TDB version**:  TDB 6.04

**Operating system**:  win7 x64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Krudor** [comment]
Also saw a creature killing himself with his own arcane explosion

**Comment by joschiwald** [comment]
duplicate #18072
since d34020da7f34943e9cc84482ce19f829154334bd target is loaded as 1 where 0 is excepted
