### ISSUE TITLE
[3.3.5] Crash authserver.exe last TC

### ISSUE THREAD

**Issue by bahajan95** [TrinityCore/TrinityCore#18085]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:  Crash authserver.exe when typing login and password and attempts to enter the world of authorization gives an error and closes authserver.exe.

**Current behaviour**: release x32 
![image](https://cloud.githubusercontent.com/assets/13211961/19408374/d3a5efba-92d4-11e6-8f70-329651b3ba0b.png) searched for fix found this raczman@10b24fe
but it didn't help

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 

**TC hash/commit**:  

**TDB version**:  62

**Operating system**:  win 7 32

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by tkrokli** [comment]
Before you report your crash issue, please learn how to do the following:

1. pull the source with Git to your own computer (to keep the git revision info) before compiling
2. compile in Debug mode before reporting a crash
3. add your Debug crash log(s) to the issue for proper troubleshooting by TrinityCore

Read the following pages:
- https://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/
- https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/

**Comment by bahajan95** [comment]
I have crash logs but I do not understand them) and that you can't just help?

**Comment by tkrokli** [comment]
We need to see the core revision hash from your compiled servers to know that this is in fact a crash happening when you use the TrinityCore source. That is why I am asking you to use Git tools to pull the source to your computer before compiling. Without this info, it is anyone's guess which code you use.

Crash logs from a Release build do not have enough information for the actual cause of the crash.
That is why you need to compile your servers in Debug mode to get correct crash logs.

**Comment by bahajan95** [comment]
well I now will try while do not cover the topic in an hour I will unsubscribe, I just cloned from git

**Comment by tkrokli** [comment]
Please follow the guide https://trinitycore.atlassian.net/wiki/display/tc/Installation+Guide to set up your core correctly so you can build your servers with Git information (revision hash).
