### ISSUE TITLE
[3.3.5] Wrong Flavor Text for Argos Nightwhisper

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18088]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: [Argos Nightwhisper (entry 4984)](http://www.wowhead.com/npc=4984/argos-nightwhisper) has incorrect flavor text for the 3.3.5 expansion

**Current behaviour**: When you talk to Argos he says something along the lines of:

[*With Stormwind's park district destroyed by Deathwing's pass over the city, we're returning to Darnassus for a time.*](http://wow.gamepedia.com/Argos_Nightwhisper#Quotes)

**Expected behaviour**: Not sure, but in 3.3.5a, Deathwing hadn't destroyed Stormwind yet...

**Steps to reproduce the problem**:

1. Go to "The Park" in Stormwind
2. Talk to Argos
3. Notice that the flavor text mentions events that haven't happened.

**Branch(es)**: 3.3.5

**TC hash/commit**:  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version**:  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system**:  WinXP / Win7

**Additional Notes**: [The quest Argos offers (3765)](http://www.wowhead.com/quest=3765/the-corruption-abroad) is also an indication that his flavor text is wrong. The quest text says something like *Stormwind is such a bustling hub, I came here looking for help*...

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by SnapperRy** [comment]
Trying to hunt down the correct gossip text, it's not easy though. The npc is not involved in any "relevant" quest.

**Comment by tkrokli** [comment]
Looking at wowhead comments & wow.gamepedia.com, that seems very plausible and likely:
- http://www.wowhead.com/npc=4984/argos-nightwhisper#comments
- http://wow.gamepedia.com/Argos_Nightwhisper

I vote for removing his gossip in 3.3.5 and only show the quest content.

**Comment by MrSmite** [comment]
> I vote for removing his gossip in 3.3.5 and only show the quest content.

Sounds good. Unless you want to just change it to a *Hello $Name, I could use your help.* I mean he does send the player to BFD after all.

**Comment by tkrokli** [comment]
http://wow.gamepedia.com/Quest:The_Corruption_Abroad

I think the quest content is enough to give the player a sense of adventure. I am also fairly certain this is more of a breadcrumb quest than a requirement to get the next quest from Gershala.
```sql
SELECT `QuestDescription` FROM `quest_template` WHERE `ID`= 3765;
```
```
Stormwind -- such a bustling hub of activity.

I have traveled from afar to seek help. Often it is heard that brave adventurers roam these city streets.

My brother, Gershala, requires assistance in Darkshore. He resides in the seaside town of Auberdine.

The journey is a long and epic one. It is for this reason that I ask the help of a seasoned $c such as yourself.
```
(note: I replaced `$b$b` with the resulting NewLines in the in-game quest text)

**Comment by SnapperRy** [comment]
Checked more sniffs, the npc definitely didn't have the gossip npcflag in WotLK.

The only way he could have a gossip text in this case is if he was involved in two different quests you can accept at the same time, like a lot of npc in Booty Bay do (no gossip flag but gossip text visible in that case). But that's not the case :P
