### ISSUE TITLE
[3.3.5] Quest The Mist Isn't Listening (12538)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18080]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
You can not attack mistwhisper-warrior and mistwhisper-oracle

https://www.youtube.com/watch?v=qNRADHsL9hU
http://www.wowhead.com/quest=12538/the-mist-isnt-listening
http://www.wowhead.com/npc=28109/mistwhisper-warrior
http://www.wowhead.com/npc=28110/mistwhisper-oracle

**Branch(es)**: 3.3.5 / 6.x
**TC hash/commit**:  TC>TrinityCore rev. 1667dd3b7ad9 2016-10-13 01:23:02 -0300 (335 branch)

**TDB version**:  TDB 335.61 + updates up to and including  2016_10_12_04_world_335.sq
**Operating system**:  Win7 64Bit

**Comment by Killyana** [comment]
Dup  #9469
