### ISSUE TITLE
Summoned vehicles despawn immediately after exit

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#18089]
**Summoned vehicles despawn immediately after exit**:

**Current behaviour**: Summoned vehicles despawn immediately after exit

**Expected behaviour**: Summoned vehicles should not despawn immediately after exit

**Fixing issue will solve problem**:
1.  While scripting the "Enter the Maelstrom" quest at a point during the ride player must change seats to change the camera. When spell 86967 is cast the player leaves seat 2 and the vehicle despawns.

**Branch(es)**: 3.3.5 / 6.x

**TC hash/commit**:  

**TDB version**:  

**Operating system**:

**Comment by Treeston** [comment]
When should they despawn?

**Comment by Krudor** [comment]
Why treat them differently at all?
We have PassengerBoarded(Unit* who, int8 seatId, bool apply), to use for the cases where they should actually despawn.

**Comment by tkrokli** [comment]
Sounds almost like the issue 3.3.5 once had when passing a Flight Point, where the player would appear to fly without a mount and then re-mount mid-air, almost like a druid changing to flight form.

**Comment by Treeston** [comment]
That is completely unrelated.

**Comment by ariel-** [comment]
It's due to VehicleAI despawning, probably

**Comment by dr-j** [comment]
Another example which I mentioned before is the version of gymer which is summoned for the stormkings vengence the npc should say a line and despawn a few seconds later it is scripted to do this but this never occurs as vehicle despawns instant when player dismounts

**Comment by malcrom** [comment]
Yeah there should be a despawn timer.

**Comment by Kittnz** [comment]
Same like the Traveler's mammoth, instant despawn.

**Comment by malcrom** [comment]
And still nothing...

**Comment by ariel-** [comment]
This only happens if said vehicle is conditioned (using conditions.SourceTypeOrReferenceId = 16)

**Comment by gonzo1247** [comment]
Some news about this? The bug is still exist

**Comment by jackpoz** [comment]
@Faq is https://github.com/TrinityCore/TrinityCore/issues/24722#issuecomment-698574244 related to this issue too ?

**Comment by Faq** [comment]
About exiting, valid for 335 on a770ad0476a32007a356c3539309f7a111893145
for https://github.com/TrinityCore/TrinityCore/issues/18089#issuecomment-254069707 
Steps:
.gm on
.go c id 29647
.q add 12919
 Mount him and use exit button, he will despawn asap without saying that text.

That vehicle is from https://github.com/TrinityCore/TrinityCore/issues/18089#issuecomment-292766509 when used:
```
SELECT
	creature_template.`name`, 
	conditions.SourceEntry, 
	conditions.`Comment`
FROM
	conditions,
	creature_template
WHERE
	conditions.SourceTypeOrReferenceId = 16 AND
	conditions.SourceEntry = creature_template.entry
````

For mounts de-spawn should be asap like now. Some mount examples:
[Traveler's Tundra Mammoth](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=44234)
[Mechano-hog](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=41508)

**Comment by gonzo1247** [comment]
I search witch part of code the vehicle is despawned and i found this on follow function:
void Unit::_ExitVehicle(Position const* exitPosition)
{
    if (vehicle->GetBase()->HasUnitTypeMask(UNIT_MASK_MINION) && vehicle->GetBase()->GetTypeId() == TYPEID_UNIT)
        if (((Minion*)vehicle->GetBase())->GetOwner() == this)
                vehicle->GetBase()->ToCreature()->DespawnOrUnsummon(1);
}

That is the part how vehicle comes in and despawn on seat changes or somethin other.
To Test it, i blocked the part of "vehicle->GetBase()->ToCreature()->DespawnOrUnsummon(1);" and the vehicle isn't despawn, the seat change with spell works.
Its need a reason to block this in case of seat change - but not on leave the vehicle or with a delay..

**Comment by illfated** [comment]
```cpp
void Unit::_ExitVehicle(Position const* exitPosition)
{
    if (vehicle->GetBase()->HasUnitTypeMask(UNIT_MASK_MINION) && vehicle->GetBase()->GetTypeId() == TYPEID_UNIT)
        if (((Minion*)vehicle->GetBase())->GetOwner() == this)
            vehicle->GetBase()->ToCreature()->DespawnOrUnsummon(1);
}
```
(for readability, add MD code block with syntax highlighting)

**Comment by jackpoz** [comment]
><%jackpoz>I was wondering about https://github.com/TrinityCore/TrinityCore/issues/18089#issuecomment-750491012 if we should delay the unsummon of the vehicle long enough that it can be cancelled when changing seat
or if we should pass around a bool "changing seat"
<%Shauren> i'd do the bool

**Comment by gonzo1247** [comment]
I look around about some videos with vehicles. And i found this: https://youtu.be/YtnXw3syMOs?t=38
here can you see that the vehicle move away after player is exit.  
So its need a way to pass this part long enough if needed - not only at changing seat.

**Comment by gonzo1247** [comment]
I add a function: https://github.com/gonzo1247/TrinityCore/commit/3b4544edab64f33588bdc3828ce3848aa0084918
and with this changes you can change the seats without despawning the vehicle.
but missing is: if player exit and vehicle should still exist longer for other action

**Comment by jackpoz** [comment]
would it be possible to pass the bool variable as parameter around instead of having a state variable in Unit (that might get desynch'd with the ingame status) ?

**Comment by gonzo1247** [comment]
mhm i can look that i changed it to a paramter of Unit::_ExitVehicle , _EnterVehicle and RemovePassenger 
if it works i push it again

**Comment by gonzo1247** [comment]
i hang on this part:
`        if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT))
            caster->_ExitVehicle();`
that is called while the controll_vehicle aura is removed - whats happend after "change" the old aura shall removed and than he kill the vehicle.
it's need to check if player/unit leave the vehicle final or "leave" only for change seat

**Comment by gonzo1247** [comment]
With the hint from Shauren i look more and found an easyer way to handelt all this.
https://github.com/gonzo1247/TrinityCore/commit/7f5096472d344ce0c0ae92a6de9719b9242fd364
i add only one new line and remove the old stuff
if (!vehicle->GetBase()->HasAuraType(SPELL_AURA_CONTROL_VEHICLE))

Test and works:
Player can change seats on vehicle without despawn - testet with follow spells: 86683, 84224 and 52391
Player switch seats correctly and after all this player was ejected by 50630 and vehicle despawn.

next part would be the timed delay despawn if needed

**Comment by Faq** [comment]
Timed despawn is needed, you can see that reading up previous comments with examples.

**Comment by jackpoz** [comment]
@gonzo1247 can you PR the "don't despawn when switching seat" fix for now so we can merge that ? having small focused PRs increases the chance to getting them merged

**Comment by gonzo1247** [comment]
@jackpoz first i will look for shauren's way to fix this(https://gist.github.com/Shauren/a5a7ebf7f0004ca1dbb8e0aac283bebb )
when all done i create a PR
even for the timed despawn

**Comment by gonzo1247** [comment]
I think this issue can now be closed. Both parts are fixed, vehicle don't despawn at seat changes and is now possiblo to delay the despawn after exit from a vehicle
