### ISSUE TITLE
Drain soul returns mana without casting the spell

### ISSUE THREAD

**Issue by Thulium-Drake** [TrinityCore/TrinityCore#18099]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: This issue was added to #14859, but it required a own ticket. The fix made by @ariel- in d9743c9 didn't seem to fix it for me (I've compared the codebase on my server with the commit, it's there).

Improved Drain Soul procs are not processed correctly.

**Current behaviour**: 
Players are rewarded the additional mana for the talent without using the Drain Soul spell. The bonus mana is rewarded on killing mobs that grant XP and on those who don't grant XP. I've tested the following scenario's:

- Used a lvl 24 character (no GM mode enabled) with Improved Drain Soul talent
- Killing a lvl 5 mob with shadow bolt, was granted 15% mana
- Killed a lvl 24 mob with shadow bolt, was granted 15% mana
- Killed a random mob with .die (and no other spells), was granted 15% mana

**Expected behaviour**: 
Mana should only be awarded when the following conditions are met:

- Player is casting Drain Soul
- Player makes the killing blow with Drain Soul
- Targeted mob/player yields XP and/or Honor

**Steps to reproduce the problem**:

1. Make a Warlock character
2. .levelup 20 and .modify money 100000
3. Go to your nearest capital with a trainer using .tele, train all your spells
4. Pick 'Improved Drain Soul' from the talents
5. .tele somewhere else
6. Find and kill a mob without using Drain Soul (it works on any mob, even the ones that don't give XP)
7. See the extra mana come in when it dies

**Branch(es)**: 3.3.5

**TC hash/commit**:  c6d77e0

**TDB version**:  335.62

**Operating system**:  Debian Jessie

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ariel-** [comment]
> I've compared the codebase on my server with the commit, it's there

Are you sure that you applied the sql updates too? Try with a clean TC. Works for me @d9743c984f11069bddab9d7f006293c18a400765

**Comment by Thulium-Drake** [comment]
Thank you! For some reason those weren't applied, fix confirmed!
