### ISSUE TITLE
[3.3.5] Quest: Rallying the Troops (12070)

### ISSUE THREAD

**Issue by shiioo** [TrinityCore/TrinityCore#18096]
**Description**: [Quest (12070)](http://www.wowhead.com/quest=12070/rallying-the-troops) cannot be completed as casting the granted spell, [Shard of the Earth (36764)](http://www.wowhead.com/item=36764), doesn't give the proper credit.

**Current behaviour**: Casting the spell on a melee-fighting [Grizzly Hills Giant (26261)](http://www.wowhead.com/npc=26261) properly spawns an Iron Rune Avenger (needed for the other half of the quest) but doesn't credit the first half (Grizzly Hills Giants Rallied).

**Expected behaviour**: Casting the spell should properly credit the player.

**Steps to reproduce the problem**:

1. Accept the quest
2. Cast the spell on a melee-fighting Grizzly Hills Giant
3. Don't get credit

**Branch(es)**: 3.3.5

**TC hash/commit**:  0d725e1336f4eb40ab392471af4c2381ea04b9e6

**TDB version**:  335.61

**Operating system**:  Win7 x64

**Comment by Aokromes** [comment]
#16561

**Comment by shiioo** [comment]
@Aokromes Not the same issue: the one you linked is for the second half of the quest, which works for me. I'm reporting the first half, which doesn't at this commit.

**Comment by Tauriella** [comment]
Confirm!
