### ISSUE TITLE
Core/Creature: disabled movement not cleared on evade

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18095]
**Description**: When a creature disables movement to cast a spell or use the cast flag 64 (SAI), it will not return to the home position if the evade happen during the cast.

**Current behaviour**: The NPC will try to reach home position for 2 secs but it gets stuck.

**Expected behaviour**: The Evade must clear all kind of stuff that effects movement.

**Steps to reproduce the problem**:
1. `.go c 82534`
2. hide behind a wall to force the NPC to move
3. `.gm on` when the NPC is casting
4. Notice the NPC doesn't return to its home pos
5. `.gm on/off` many times to aggro/evade the NPC and notice the evade behavior

This issue also effects Prince Keleseth at ICC and many other NPCs who disable movements during cast.

**Branch(es)**: 3.3.5

**TC hash/commit**:  rev. 9b0fa51022fb

**Comment by DeActiveDev** [comment]
yes for example instance Ice Crown NPC Nerub'ar Broodkeeper id : 36725 effects movement, aggro

**Comment by Killyana** [comment]
Looks like the homeposition is set to current position when the npc is casting but not reset to the initial one on evade.

**Comment by Rushor** [comment]
summoning @malcrom maybe he knows more about it :)

**Comment by sirikfoll** [comment]
@xinef1 Do you suggest anything? I assume this bug is related to the HomeMovementGenerator([here](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp#L46)) but i understand nothing about that :/

**Comment by xinef1** [comment]
Well homemovement generator moves to home position (the if you mentioned checks for stun, root and distracted, they should come from auras and be properly cleared in ai evade aura clearing function before home movement is started), im not really sure why the home movement pos is even relocated (this should be corrected imo) ill check this tonight (writing from a phone)
