### ISSUE TITLE
Grace

### ISSUE THREAD

**Issue by Dreacus** [TrinityCore/TrinityCore#18098]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:Grace=47930, does not proc from penance=47540.

**Current behaviour**: Grace proc from flash heal and greater heal, but not from penance

**Expected behaviour**: Grace should proc from penance also

**Steps to reproduce the problem**:

1. have 1/2 or 2/2 in grace (Discipline priest)
2. cast penance
3. grace never proc

**Branch(es)**: 3.3.5 

**TC hash/commit**:  trinitycore rev.bef9a3cbd37d+ win64 release static

**TDB version**:  3.3.5.62

**Operating system**:  windows 2012 r2

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
there is no such thing has latest.

**Comment by ariel-** [comment]
There is no such rev in clean TrinityCore

**Comment by Dreacus** [comment]
tried on a fresh trinitycore rev f3dcdc4e647e same thing
