### ISSUE TITLE
Mass Dispel Break Stealth

### ISSUE THREAD

**Issue by Dreacus** [TrinityCore/TrinityCore#18097]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:Mass Dispel(Priest)=32375, removes Stealth=1784, from rogues

**Current behaviour**: when used on rogues, friendly or hostile mass dispel break stealth

**Expected behaviour**: mass dispel should not break dispel

**Branch(es)**: 3.3.5

**TC hash/commit**: trinitycore rev.bef9a3cbd37d+ win64 release static

**TDB version**:  3.3.5.62

**Operating system**:  windows server 2012 R2

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
there is no such thing has latest

**Comment by ariel-** [comment]
There is no such rev in clean TrinityCore

**Comment by Dreacus** [comment]
tried on fresh trinitycore rev f3dcdc4e647e same thing

**Comment by ariel-** [comment]
Ok, it's important to put tc rev. I had recently done changes to stealth procs and incorrect removals.
