### ISSUE TITLE
[3.3.5] Cyclone (Druid) not work propertly

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18108]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: Cyclone (Druid) not work propertly with Bladestorm (Warrior) and Bestial Wrath (Hunter)

**Current behaviour**: When the hunter is affected by Cyclone and casts Bestial Wrath not remove the cyclone. On the other hand, when a warrior is in Bladestorm and receive cyclone the visual effect show a cyclone but the warrior continue his bladestorm and begins the decline of cyclone.
 
**Expected behaviour**: Bestial Wrath must remove the cyclone and when a druid cast cyclone to warrior in Bladestorm de result must be inmune.

**Steps to reproduce the problem**:
First case: Druid vs Hunter - Beast Mastery.
1. Druida cast cyclone to hunter.
2. The hunter (with pet) cast Bestial Wrath.
3. The cyclone persist.

Second case: Druid vs Warrior Arms
1. The druid damages the warrior until rabies is sufficient.
2. Warrior cast Bladestorm.
3. Quickly the druid cast cyclone.
4. Visually the warrior is affected but is not true and the druid miss a chance.

**Branch(es)**: 3.3.5 

**TC hash/commit**:  7905c3c

**TDB version**:  TDB_full_world_335.62_2016_10_17 + updates

**Operating system**:  Windows

Please excuse my English.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Keader** [comment]
it's a old bug no?
#16901
