### ISSUE TITLE
[6.x] Hallow's End - Missing Heirlooms Quest #29415

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18106]
**Description**: Missing Heirlooms quest does not show the dead orc on the ship on which to continue the remainder of the quest chain. Quest number is 29415 as noted. 

**Current behaviour**: During the Hallow's End quests, I obtained this from the quest chain start "A Friend in Need" which starts at the Broken Tusk Inn in Orgrimmar, in which you are directed to find the missing heirlooms on the docks east of Orgrimmar. Searching the entire ship reveals it to be devoid of life and completely empty.

**Expected behaviour**: The courier's body should be on the ship to proceed the quest chain.

**Steps to reproduce the problem**:
1. Get quest from Broken Tusk in Orgrimmar
2. Search ship
3. Throw up hands and return to TC/ Github for resolution efforts.

**Branch(es)**: 6.x

**TC hash/commit**:   TrinityCore rev. c676e80 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version**:  6.04

**Operating system**:  Windows 10

**Comment by BahDumbBugs** [comment]
After dealing a bit more with these Hallow's End quests and Achievements, I stumbled across a few curious glitches/bugs. In the 'Tricks and Treats of Outland' segment of the Achievement, there are only two that can't be completed right off the bat. Those are the two that have to do with whether you choose allegiance with Scryers or Aldors. I have not established reputation with either faction and will be testing it shortly. With these two, however, the pumpkins are there, they are selectable (depending on your friendly status) but it will not reward you with the 'Handful of Treats' and complete that segment of the quest. More to come......

**Comment by BahDumbBugs** [comment]
In Northrend:

1) Taunka'le Village and Kamagua among others I am sure (I will validate shortly) are showing the Candy Buckets as a Daily Quest (Blue Question Mark above). They are present and selectable, but when the Handful of Treats dialogue box opens up, you cannot select "Complete Quest" to finish and receive rewards.

2) In Bor'gorok Outpost the Candy Bucket is in the middle of the Apple Bob tub. Slight location adjustment is necessary. Candy Bucket is correctly represented with a yellow Question Mark quest indicator and normal in behavior, however.

**Comment by BahDumbBugs** [comment]
Cataclysm (I know not all areas are implemented yet. This is just for posterity):

1)  Nordrassil does not have a Candy Bucket present in its proper location.
2) Oasis of Vir'sar has no Candy Bucket in its proper location. 
3) Deepholm (Not Implemented yet) - Cannot locate Candy Bucket in Temple of Earth

More to come......

**Comment by meji46** [comment]
This is fixed for the master branch
