### ISSUE TITLE
[7.x] Commands: bnet create account

### ISSUE THREAD

**Issue by Valkorion** [TrinityCore/TrinityCore#18103]
**Description**: Assertion Failed when creating an account.

**Current behaviour**: Assertion Failed when you create an account in worldserver.exe (See Screenshot) : https://puu.sh/rOvzJ/834a6de7bd.png

**Expected behaviour**: The account should be created normally. Without assertion failed

**Steps to reproduce the problem**: 

1. Open WorldServer.exe
2. Create an account with .bnet create command
3. See the result

**Branch(es)**: master (7.x)

**TC hash/commit**:  4881e45688c3d8f64cf2efaa7553ecbc02a0884a

**TDB version**: 703.00_2016_10_17

**Operating system**:  Windows 10 x64

**Comment by Aokromes** [comment]
you have to strict mysql settings.

**Comment by Aokromes** [comment]
#13840

**Comment by Valkorion** [comment]
Ok, thank you !
