### ISSUE TITLE
Viper Sting & Disengage

### ISSUE THREAD

**Issue by DeActiveDev** [TrinityCore/TrinityCore#18101]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:Viper Sting should drain 4% of target's maximum mana (up to maximum of 8% of Hunter's maximum mana). 300% of the amount drained should energize Hunter's mana.
Bug: Viper Sting does not energize Hunter in the way it should. It simply energizes Hunter with the same amount of mana drained, not 300% of it.

disengage = ok , sorry

**Branch(es)**: 3.3.5 

**TC hash/commit**:  0285486603a0364f8dfe2b6bec1391880adcede4

**TDB version**:  62

**Operating system**:  win 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ariel-** [comment]
Summoning @Krudor for the disengage part.

PS: Different issue belongs to different ticket

**Comment by ariel-** [comment]
Will consider Viper Sting, as it's the first in the title.

```
Olaf's Viper Sting drains 121 Mana from Merok Longstride. Olaf's gains 363 Mana.
```

121 x 3 = 363
