### ISSUE TITLE
3.3.5a fresh win extractors

### ISSUE THREAD

**Issue by Mordekaios** [TrinityCore/TrinityCore#18107]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Hello, can someone send me current win extractors for mmpas, vmpas and others? I have it on linux VPS, so i cant extract it. 
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5
**TC hash/commit**:  

**TDB version**:  

**Operating system**:  win 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
this don't belongs here.

**Comment by tkrokli** [comment]
To be precise, questions like this should be posted in the TrinityCore Forum pages
(https://community.trinitycore.org/) .
