### ISSUE TITLE
[3.3.5] pet will gone away on cast

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18111]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: pet will gone away on cast in stay mode without target

**Current behaviour**: pet will gone away!

**Expected behaviour**: pet should cast that spell if conditions are right

**Steps to reproduce the problem**:

1.  get a warlock and summon a minion 
2.  put the pet into stay mode without targeting anythings
3. click on one of the pet spells

**Branch(es)**: 3.3.5

**TC hash/commit** 7905c3cb877d5c3b101c50f3fc81c6df77b91c75:  

**TDB version**:  62

**Operating system**:  Linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Keader** [comment]
Dup i think: #14242
PS: I'm using https://github.com/TrinityCore/TrinityCore/issues/14242#issuecomment-103469941 for a long time and have no issues ^^

**Comment by Keader** [comment]
Dup i think: #14242
PS: I'm using https://github.com/TrinityCore/TrinityCore/issues/14242#issuecomment-103469941 for a long time and have no issues ^^
