### ISSUE TITLE
[3.3.5] Rogue Savage Combat not work

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18116]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Increases your total attack power by 4% and all physical damage caused to enemies you have poisoned is increased by 4%. Need 2 talent points for combat.

**Current behaviour**: 
Never Increases the attack power.

**Expected behaviour**: 
Increases your the attack power by 4%.

**Steps to reproduce the problem**:

1. With a rogue assign 2 talent points at  [Savage Combat].
2. The bonus never appears

**Branch(es)**: 
3.3.5

**TC hash/commit**:  
7905c3c

**TDB version**:  
TDB_full_world_335.62_2016_10_17 + updates

**Operating system**:  
Windows

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Aokromes** [comment]
#16242
