### ISSUE TITLE
[3.3.5][Warrior] Talent safeguard

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18117]
**Description**: it doesn't work at all ( before new Proc system it was working )
**Branch(es)**: 3.3.5
**TC hash/commit** 7905c3cb877d5c3b101c50f3fc81c6df77b91c75:  
**TDB version**:  62
**Operating system**:  Linux

**Comment by ariel-** [comment]
This one is not because proc system. It's because Safeguard is failing range check (see #17545)
