### ISSUE TITLE
[3.3.5] Hunter Bestial Wrath not remove cyclone

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18114]
**Description**:
When the hunter is affected by Cyclone and casts Bestial Wrath not remove the cyclone. From wowwiki: Bestial Wrath and The Beast Within Changed to function like PvP Trinkets, removing any movement impairing effects, and giving immunity to these effects for 10 seconds.", also the tooltip doesn't say this, but it now breaks all forms of CC that a PvP trinket would break (including Cyclone,Sap, etc.).

**Current behaviour**: 
When the hunter is affected by Cyclone and casts Bestial Wrath not remove the cyclone.

**Expected behaviour**: 
When the hunter is affected by Cyclone can cast Bestial Wrath, removing any movement impairing effects, and giving immunity to these effects for 10 seconds.

**Steps to reproduce the problem**:
1. Druid cast cyclone to hunter.
2. The hunter (with pet) cast Bestial Wrath.
3. The cyclone persist.

**Branch(es)**: 
3.3.5

**TC hash/commit**:  
7905c3c

**TDB version**:  
TDB_full_world_335.62_2016_10_17 + updates

**Operating system**:  
Windows

**Comment by noryad** [comment]
Since Patch 3.2.2 (2009-09-22): "Bestial Wrath and The Beast Within Changed to function like PvP Trinkets, removing any movement impairing effects, and giving immunity to these effects for 10 seconds.", also the tooltip doesn't say this, but it now breaks all forms of CC that a PvP trinket would break (including Cyclone,Sap, etc.).
http://wowwiki.wikia.com/wiki/Bestial_Wrath

**Comment by Keader** [comment]
Always when ariel have time, he fix all issues related, dont worry ^^

**Comment by MrDelta** [comment]
Are YOU Sure? 
it's too many bug! and why?!
i don't know!!!
Could YOU tell me?

**Comment by Aokromes** [comment]
You are free to clone ariel and make one army of spell fixers.

**Comment by Goatform** [comment]
``` diff

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 9ab8bf4..466eb00 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3472,6 +3472,13 @@ void SpellMgr::LoadSpellInfoCorrections()
             case 44544: // Fingers of Frost
                  spellInfo->Effects[EFFECT_0].SpellClassMask = flag96(685904631, 1151048, 0);
                  break;
+            case 34471: // The Beast Within
+                spellInfo->Attributes |= SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY;
+                spellInfo->AttributesEx5 |= SPELL_ATTR5_USABLE_WHILE_CONFUSED | SPELL_ATTR5_USABLE_WHILE_FEARED | SPELL_ATTR5_USABLE_WHILE_STUNNED;
+                break;
              case 49224: // Magic Suppression - DK
              case 49610: // Magic Suppression - DK
              case 49611: // Magic Suppression - DK

**Comment by tkrokli** [comment]
Would be good to have a comment from you, @ariel- , if the above diff is useful or not in the TC source.

**Comment by ariel-** [comment]
The attribute adding shouldn't be necessary, the problem here is that "The Beast Within" isn't being applied AT ALL when cycloned.

SPELL_AURA_MECHANIC_IMMUNITY auras probably need more research, as what TC code has is hardcoded values for each spell id using it (like PvP trinket and this talent for example)

See https://github.com/TrinityCore/TrinityCore/blob/725208d2d69d88147b2d2975f08a90279261b8cf/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L3433-L3484

**Comment by noryad** [comment]
Confirmed in d8b0a2e
