### ISSUE TITLE
[3.3.5] Posible fix for Cyclone to Warrior in Bladestorm

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18115]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: 
This is my fix and works ok.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index cecec86..f101cbd 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -2628,6 +2628,9 @@ SpellMissInfo Unit::MagicSpellHitResult(Unit* victim, SpellInfo const* spellInfo
     if (rand < tmp)
         return SPELL_MISS_MISS;
 
+    if (spellInfo->Id == 33786 && victim->HasAura(46924))  
+        return SPELL_MISS_IMMUNE;
+
     // Chance resist mechanic (select max value from every mechanic spell effect)
     int32 resist_chance = victim->GetMechanicResistChance(spellInfo) * 100;
     tmp += resist_chance;
```

**Current behaviour**: 
When a warrior is in Bladestorm and receive cyclone the visual effect show a cyclone but the warrior continue his bladestorm and begins the decline of cyclone.

**Expected behaviour**: 
When a druid cast cyclone to warrior in Bladestorm, the result must be immune.

**Steps to reproduce the problem**:
1. The druid damages the warrior until rabies is sufficient.
2. Warrior cast Bladestorm.
3. Quickly the druid cast cyclone.
4. Visually the warrior is affected but is not true and the druid miss a chance.

**Branch(es)**: 
3.3.5 

**TC hash/commit**:  
7905c3cb877d

**TDB version**:  
TDB 335.62

**Operating system**:  
Windows

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Palabola** [comment]
Or you can just simple add immunity in spell_linked_spell table.

**Comment by Aokromes** [comment]
Don't open new tickets for existing issues.
#16901
