### ISSUE TITLE
[6.x] Hallow's End Vendor Issues

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18121]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: NPC Farina (#53760) :  The vendor for masks outside Undercity during Hallow's End doesn't interact for purchasing masks or goods. Darla and Chub are the same. Not sure if was fixed in a later commit than the one I'm currently using, nor am I sure if the Alliance vendor is exhibiting the same issues. (Will check)

**Current behaviour**: No interaction between player and vendor.

**Expected behaviour**: Vendor should display goods and dialogue box should appear.

**Steps to reproduce the problem**:

1. Fly / tele to Undercity
2. Attempt to talk to Vendor
3. No need for step 3.

**Branch(es)**: 6.x - Checking 3.3.5

**TC hash/commit**:   TrinityCore rev. c676e80 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version**:  6.04

**Operating system**:  Win 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BahDumbBugs** [comment]
Cannot locate Hallow's End vendors for Alliance. Can someone point out where they would be? I admittedly have not played Alliance on retail. :)

**Comment by Foldy** [comment]
@BahDumbBugs the alliance vendors are right outside stormwind gates

**Comment by Aokromes** [comment]
6.x branch is unsupported anymore, switch to master branch.

**Comment by BahDumbBugs** [comment]
UGGGGH
