### ISSUE TITLE
DB/Spells: blood elf Steady Shot class quest + hunter spell

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18123]
**Description:** Steady Shot Quest
- http://www.wowhead.com/quest=10070/steady-shot

**Current behavior:** Kill Command gets placed on the character **twice** at Level 3, when Steady Shot (http://www.wowdb.com/spells/56641-steady-shot) should be placed on the character. Getting a double Kill command instead, this looks like a spell mismatch in the DB.

**Expected behavior:** Steady shot is needed for the character to be able to complete the quest.

**Steps to reproduce the problem:**

1. get a Blood Elf Hunter to level 2
2. accept the quest [Steady Shot](http://www.wowhead.com/quest=10070/steady-shot)
3. Reach Level 3, Cannot continue since no Steady Shot Spell gets casts on the character

**Branch(es):** master (7.0.3)

**TC rev. hash/commit:** bf702ab 

**TDB version:** TDB703.00

**Operating system:** Debian 8

**Comment by Keldo** [comment]
Cross referenced with Retail, this Quest Should be removed as it is depreciated by Blizzard

**Comment by tkrokli** [comment]
Both the quest & spell is removed on retail (www.wowhead.com still shows it available to goblin hunters) and should be removed from the TC source to make it more "blizzlike". See also:  http://www.wowhead.com/hunter-specialization-abilities/name:shot/live-only:on

**Comment by Keldo** [comment]
There is still the issue of the Kill Command being given **twice** at level 3

**Comment by tkrokli** [comment]
Maybe it can be fixed at the same time as removing the Steady Shot info.

**Comment by MrSmite** [comment]
On Topic...

Confirming what @tkrokli said, [this was removed in 7.0.3](http://wow.gamepedia.com/Steady_Shot#Patches_and_hotfixes)

Off topic..

I really hate what Blizz did to the Hunter class. No melee weapons for extra stats, no steady shot (plus many others) focus instead of mana (can't benefit from many buffs), etc.

**Comment by tkrokli** [comment]
Closed as a duplicate of [**[7.x] Class Releated Start Quests**](17792)  #17792
