### ISSUE TITLE
[Crash] Unit::GetFactionTemplateEntry

### ISSUE THREAD

**Issue by Pirricli** [TrinityCore/TrinityCore#18127]
**Description:**
I have recently updated to cdc5a36dbb8c3498fcdab43ce568548d3b60ccfa
**Current behaviour:** (Tell us what happens.)
The server crashes after 3-5 minutes

**Steps to reproduce the problem:**

1. Login a character in Dalaran or go there and it crashes.
2. 
3. 

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  
cdc5a36dbb8c3498fcdab43ce568548d3b60ccfa
**Operating system:**  
Ubuntu 16.04

http://pastebin.com/SL7t70A9
http://pastebin.com/z6GWQunV

**Comment by Aokromes** [comment]
Maybe related to #18113 ?

**Comment by Pirricli** [comment]
It seems that the problem happens when you enter dalaran or log a character there.

**Comment by Pirricli** [comment]
It was a custom npc with faction=0

**Comment by Pirricli** [comment]
Thanks to @Aokromes

**Comment by Aokromes** [comment]
IMHO this needs core fix, to avoid crash because bad db data.

**Comment by tkrokli** [comment]
Maybe the same fix as #18113 , related to wrong faction value there too?

**Comment by jackpoz** [comment]
@ariel- : it seems https://github.com/TrinityCore/TrinityCore/issues/18113#issuecomment-255413568 is incorrect as now the assert happens at runtime. if the startup check only logs an error then the assert is not the right way to handle the wrong faction (asserts must be used for impossible cases, not for bad data).
The current solution is causing the same issues as the one before. Either set a different faction on startup or abort on startup.
