### ISSUE TITLE
Valithria Dreamwalker encounter not starting.

### ISSUE THREAD

**Issue by Ikfes** [TrinityCore/TrinityCore#18126]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

After doing the Sister event with the death knight NPC's, and moving slowly to Valithria room, the gates remain closed all the time.

**Current behaviour:** (Tell us what happens.)

We killed the liches and started healing Valithria, but no mobs spawned and the gates were still closed.

When Valithria Dreamwalker was healed to 100%, she stood up but nothing else happened. The door in the back to Sindragon remained closed.

**Expected behaviour:** (Tell us what should happen instead.)

Upon entering the room and starting to heal the dragon, the gates should open and NPC's keep spawning untill the dragon is healed to 100%. After that the backdoor should open up.

**Steps to reproduce the problem:**

Try out the encounter.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

3.3.5

**TC rev. hash/commit:**  

None

**TDB version:**  

335.62

**Operating system:**  

Debian 8 latest updates

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
there is no such rev has "none"

**Comment by Ikfes** [comment]
No idea what to put in there. sorry.

**Comment by tkrokli** [comment]
if you look in the Worldserver console, it is both in the first and last line when you start Worldserver.
You can also find it in your `Server.log` if Worldserver is not running at the moment.

Very old example image found via Google:

![worldserver.exe](http://i.stack.imgur.com/5Pagn.png)

**Comment by MrSmite** [comment]
> if you look in the Worldserver console,

Even better is `uptime`.`revision` in the `auth` table.
