### ISSUE TITLE
[DB/Events] Event spawns for Brewfest / Building Darkmoon Faire

### ISSUE THREAD

**Issue by Elron103** [TrinityCore/TrinityCore#18131]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The spawns for the Brewfest and the Building Darkmoon Faire events are messed up.

**Current behaviour:** (Tell us what happens.)
The Brewfest spawns include spawns from the Building Darkmoon Faire event in Mulgore. Only the Building event for the Darkmoon Faire in Elwynn Forest is still present in database. There are Darkmoon Faire NPC spawns, that are not linked to any game event at all.

**Expected behaviour:** (Tell us what should happen instead.)
The Brewfest event should only spawn gameobjects / NPCs related to the Brewfest event. There should not be any spawns without the respective game event being active. I am not sure about the Darkmoon Faire Building events, but I would assume that it is incorrect that there is only one for Elwynn Forest and the other ones are missing.

**Steps to reproduce the problem:**

1. .go cr 137686
2. .event start 24

```sql
-- Gameobject spawns for Brewfest (event 24) include gameobjects such as
-- 178666, 'Gypsy Wagon'
-- 179964, 'DARKMOON FAIRE - Coming Soon!'
-- 179965, 'Darkmoon Faire Banner'
SELECT DISTINCT gt.entry, gt.name FROM gameobject_template gt
INNER JOIN gameobject g ON g.id = gt.entry
INNER JOIN game_event_gameobject geg ON geg.guid = g.guid
WHERE geg.evententry = 24 ORDER BY gt.entry;

-- NPC 14849, 'Darkmoon Faire Carnie' is not linked to any game event
SELECT entry, name FROM creature_template WHERE entry = 14849;
SELECT * FROM creature where guid = 137686;
SELECT * FROM game_event_creature WHERE guid = 137686;
```

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
8fe85017125803a4ca8fd1d972b128930cd364b9

**TDB version:**  
TDB 335.61

**Operating system:**  
Debian, Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Kittnz** [comment]
You are right about this, i didn't see this before. However they do use some of the same gob's in brewfest build up. But this needs to be changed and made into a new game event. I'll get right at it.
