### ISSUE TITLE
[3.3.5] DOTs remove stealth even tho you have a shield up 

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18135]
Description: If you use an item like: http://wotlk.openwow.com/item=19024
And you stealth, while having a dot on you like: http://wotlk.openwow.com/spell=594

As soon as shadow word ticks, itll say "absorbed" but stealth goes away.

**Current behaviour:** (Tell us what happens.) Stealth goes away when shadow word ticks.

**Expected behaviour:** (Tell us what should happen instead.) Shouldnt remove stealth.

**Steps to reproduce the problem:**

1. Use item http://wotlk.openwow.com/item=19024
2. Use stealth as a rogue.
3. do .aura 594 while targeting yourself. Stealth will go away.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/de22843bcbe13ea2ba1ef89605a96aaaac6a3587

**TDB version:**  TDB 335.62

**Operating system:**  Ubuntu 14.04

**Comment by Kittnz** [comment]
For food for you @ariel- :dancing_women:

**Comment by Persephone** [comment]
There is most likely a general error with every spell and damage being applied, so properly related to something deeper than just a single fix for this issue

**Comment by ariel-** [comment]
By default, procs on "taken damage" do not proc on absorbs, so yeah there must be some logic error somewhere.

**Comment by Persephone** [comment]
@ariel-  Since your the man for this spell system, would you be able to look at diminishing returns? They broke as well after the new QAston proc system

dr is supposed to be 23 seconds from first fear effect starting
and dr is resetting at 16 seconds so if you do the math 8 +4 + 2 thats 2 seconds a lock cant fear lock someone before reset when it should be 10

I can start a new issue if needed :)

**Comment by ariel-** [comment]
Diminishing returns reset at 15 seconds. Source: http://wow.gamepedia.com/index.php?title=Diminishing_returns&oldid=2514132

>  Spells must be used on the same target within 15 seconds of the *end* of the duration in order to be diminished. In other words, if a target hasn't had a slowing spell active on them for more than 15 seconds, the next slowing spell will have full effect.

**Comment by Persephone** [comment]
ok yes but 15 seconds after first cc duration ends
so after first cc ends u have 15 sec till it resets meaning 6 seconds of cc left and 9 seconds of immune
right now its just resetting 15 sec after first cast of cc
meaning u have 1 to 2 seconds where a person cannot be cc'd

**Comment by ariel-** [comment]
Additional DRs issue (should've been in another ticket, but oh well) fixed in 2f03d502f34d0e9f69fd2d23cfb69b1ec8bb8891

**Comment by Persephone** [comment]
Thanks man!
