### ISSUE TITLE
[3.3.5][Warlock] Everlasting Affliction with glyph of Glyph of Quick Decay

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18133]
Everlasting Affliction SpellID: 47205 ( Rank 5)
Glyph of Quick Decay ItemID: 50077

Both above spell and item works very well, but when they combine to work together Glyph doesn't work anymore

Example: character with 500 haste and glyph active reduce corruption time to 15 Sec instead of 18 sec
this works well, and everlasting refresh corruption every shadow bolt hits this works well, but everlasting refresh corruption with 18 sec time instead of 15 sec, everlasting doesn't calculate Glyph it should calculate it 💃 

**Branch(es)**: 3.3.5
**TC hash/commit** 7905c3cb877d5c3b101c50f3fc81c6df77b91c75:  
**TDB version**:  62
**Operating system**:  Linux

**Comment by noryad** [comment]
@ariel- @sucklifex 
I checked that it works ok, the Everlasting refresh corruption with 15 sec. Please @ariel we need to prioritize the issues related with PVP and there are some. For the other side, i am interested in to help to solve issues, i know about programming and database, where can i find documentation about the core, spells, etc.? thanks.

**Comment by tkrokli** [comment]
@noryad : core documentation is mostly the source code itself and the PRs/commits here on GitHub.

Spell info can be found in the SpellWork application:
- https://github.com/TrinityCore/SpellWork/blob/7.x/README.md

For DB info, refer to the TC wiki: https://trinitycore.atlassian.net/wiki/display/tc/World

**Comment by ariel-** [comment]
Everlasting affliction correctly calculates hasted duration for corruption, there is no issue here.
