### ISSUE TITLE
[3.3.5] Waitress Darcy Standing in Apple Bob

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18139]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Waitress Darcy (GUID 10083) is standing inside the apple bob doodad (GUID 39881) in Lakeshire

**Current behaviour:** Either Darcy or the apple bob doodad is spawned incorrectly causing Darcy to be inside the apple bob doodad.

**Expected behaviour:** Darcy should not be inside the apple bob doodad.

**Steps to reproduce the problem:**

1. Make sure the Hallows End event is active
2. Visit the inn at Lakeshire
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system:**  Win 7, Win XP

**Additional Notes:**

While this revision / DB isn't the most recent, I did search the issues and have not seen any indication that this has been reported or fixed.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Kittnz** [comment]
There is no spawn on that location in current tdb, however on retail there is a spawn. There isn't even a bucket, but there is on retail. Also in the achievements on 335 there is no record of needed this bucket. So i think this works as intended.

**Comment by Killyana** [comment]
http://i.imgur.com/yxaNL1S.jpg
``` sql
UPDATE `gameobject` SET `position_y`=-2148.561035 WHERE `guid`=39881;

**Comment by tkrokli** [comment]
TrinityCore rev. c88dd5b1cd38 2016-10-30 14:31:19 +0100 (3.3.5 branch) (Win64, Release, Static)
TDB 335.62 plus updates up to and including `2016_10_30_03_world.sql`

Issue confirmed, GO (apple bob doodad) should be moved from where [Darcy `<Waitress>`](http://www.wowhead.com/npc=379/darcy-parker) is standing.
- http://wotlk.openwow.com/npc=379
- http://www.wowhead.com/npc=379/darcy-parker

> Killyana commented: http://i.imgur.com/yxaNL1S.jpg

😆 that image looks inappropriate / somewhat sexist (although funny, since it's a cartoonish game).

**Comment by tkrokli** [comment]
Tested Killyana's fix and it works just fine. The Apple Bob GO placement is a lot better with it in DB.

**Comment by Kittnz** [comment]
Weird :/
