### ISSUE TITLE
[7.x] Maps Extractor not working

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#18143]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Map extractor extracts only DBC and GT Files then suddenly closes without any error message.
Tried on two different PCs with different version of official World of Warcraft (enUS and enGB).

TrinityCore rev. c2d1e43b3768 2016-10-26 01:47:42 +0200 (master branch) (Win64, Debug, Static) (worldserver-daemon)

**Comment by jackpoz** [comment]
start the tool from command line and post the output

**Comment by kncould** [comment]
esES version not work and the connection patcher no patch wow-64

D:\World of Warcraft>mapextractor
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

opened casc storage 'D:/World of Warcraft\Data' locale enUS
Locale enUS not installed.
opened casc storage 'D:/World of Warcraft\Data' locale koKR
Locale koKR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale frFR
Locale frFR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale deDE
Locale deDE not installed.
opened casc storage 'D:/World of Warcraft\Data' locale zhCN
Locale zhCN not installed.
opened casc storage 'D:/World of Warcraft\Data' locale zhTW
Locale zhTW not installed.
opened casc storage 'D:/World of Warcraft\Data' locale esES
Detected client build 20365 for locale esES

Extracting dbc/db2 files...
locale esES output path D:\World of Warcraft/dbc/esES/
Unable to open file DBFilesClient\CameraShakes.db2 in the archive for locale esES: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestPOIPointCliTask.db2 in the archive for locale esES: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellEffectCameraShakes.db2 in the archive for locale esES: FILE_NOT_FOUND
Extracted 0 files

opened casc storage 'D:/World of Warcraft\Data' locale esMX
Locale esMX not installed.
opened casc storage 'D:/World of Warcraft\Data' locale ruRU
Locale ruRU not installed.
opened casc storage 'D:/World of Warcraft\Data' locale ptBR
Locale ptBR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale itIT
Locale itIT not installed.
opened casc storage 'D:/World of Warcraft\Data' locale esES
Extracting game tables...
output path D:\World of Warcraft/gt/
Extracted 0 files

opened casc storage 'D:/World of Warcraft\Data' locale esES
Extracting maps...
Read Map.dbc file... Fatal error: Invalid Map.db2 file format! SUCCESS

D:\World of Warcraft>

**Comment by Vincent-Michael** [comment]
try:
https://gist.github.com/Vincent-Michael/2cbefdeae1ecbfb560b4861fc1cdcde6

**Comment by kncould** [comment]
D:\World of Warcraft>mapextractor
TrinityCore rev. c2d1e43b3768+ 2016-10-26 01:47:42 +0200 (master branch) (Win64, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

opened casc storage 'D:/World of Warcraft\Data' locale enUS
Locale enUS not installed.
opened casc storage 'D:/World of Warcraft\Data' locale koKR
Locale koKR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale frFR
Locale frFR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale deDE
Locale deDE not installed.
opened casc storage 'D:/World of Warcraft\Data' locale zhCN
Locale zhCN not installed.
opened casc storage 'D:/World of Warcraft\Data' locale zhTW
Locale zhTW not installed.
opened casc storage 'D:/World of Warcraft\Data' locale esES
Detected client build 20365 for locale esES

Extracting dbc/db2 files...
locale esES output path D:\World of Warcraft/dbc/esES/
Unable to open file DBFilesClient\CameraShakes.db2 in the archive for locale esES: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestPOIPointCliTask.db2 in the archive for locale esES: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellEffectCameraShakes.db2 in the archive for locale esES: FILE_NOT_FOUND
Extracted 0 files

opened casc storage 'D:/World of Warcraft\Data' locale esMX
Locale esMX not installed.
opened casc storage 'D:/World of Warcraft\Data' locale ruRU
Locale ruRU not installed.
opened casc storage 'D:/World of Warcraft\Data' locale ptBR
Locale ptBR not installed.
opened casc storage 'D:/World of Warcraft\Data' locale itIT
Locale itIT not installed.
opened casc storage 'D:/World of Warcraft\Data' locale esES
Extracting game tables...
output path D:\World of Warcraft/gt/
Extracted 0 files

opened casc storage 'D:/World of Warcraft\Data' locale esES
Extracting maps...
Read Map.dbc file... Done! (682 maps loaded)
Read LiquidType.dbc file...Done! (897 LiqTypes loaded)
Convert map files
Extract Azeroth (1/682)
Error loading World\Maps\Azeroth\Azeroth_37_22.adt

**Comment by zamalaev** [comment]
work extrator 7.1.0 22908 thx Vincent-Michael 
https://github.com/zamalaev/TrinityCoreLegion/commit/a99b231733355a5139edbc673e4a87e97c82dfc5

**Comment by maryus101** [comment]
how do i use Vincent-Michael`s solution?

**Comment by zamalaev** [comment]
download my extrator

**Comment by TheLU5T** [comment]
Extract dbc/db2 and maps works but **Extract vmaps gives**:

TrinityCore rev. 4c44e3f57acf 2016-10-26 08:32:08 +0300 (custom branch) (Win64, Release, Static) (VMAP data extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Extract V4.03 2015_05. Beginning work ....

opened casc storage 'G:/Games\World of Warcraft - Copy\Data' locale enUS
Detected client build: 20365

opened casc storage 'G:/Games\World of Warcraft - Copy\Data' locale enUS
Extracting GameObject models...Fatal error: Invalid GameObjectDisplayInfo.db2 file format!

**Comment by zamalaev** [comment]
Yes, I know about this mistake, you have to wait for help from the community

**Comment by Keldo** [comment]
No ones vmap4extractor or vmap4assembler is working, the above mentioned diff only fixes the map extractor, servers will still fail to start, etc. Development Cycle was not followed or Honored here Rush, rush, rush. FAIL. Can we fix it please?

**Comment by Shauren** [comment]
> No ones vmap4extractor or vmap4assembler is working, the above mentioned diff only fixes the map extractor, servers will still fail to start, etc. Development Cycle was not followed or Honored here Rush, rush, rush. FAIL. Can we fix it please? 

@Keldo so let me get this straight. I worked in my free unpaid time to deliver 7.1 ON PATCH DAY and yet all that I get was a complaint that not everything works? How nice.

**Comment by funjoker** [comment]
God Shauren has spoken. No need to rush ^^.

@Keldo Use 7.0.3 instead aslong 7.1 is not ready yet.

**Comment by hoxton22** [comment]
actually the gamebuild is set to 22900 in the SQL, it should be to 22908, i can login with this change.
The only problem i have, it's that the connexion patcher work only with the 32 bit, seems to have a problem on the Bnet certificate file to load etc...
btw, Thanks for your work Shauren, i appreciate ur work :)

**Comment by Keldo** [comment]
@Shauren, I completely understand that all of this is done on peoples Free time and that its open Source which I support 100%, it just appeared to me as I said.  I thank each and everyone of you for all of your effort, this is why I joined this community.

**Comment by Kittnz** [comment]
With comments like that @Keldo it doesn't show a good motivation. Let's hope that changes :)
