### ISSUE TITLE
[7.x] Small Typo in SpellEffects.cpp

### ISSUE THREAD

**Issue by P-Kito** [TrinityCore/TrinityCore#18140]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Typo on 
https://github.com/TrinityCore/TrinityCore/blob/6.x/src/server/game/Spells/SpellEffects.cpp#L322
SPELL_EFFECT_GIVE_HONOR should be SPELL_EFFECT_253 not 254.

**Branch(es):** master (Tell us which branch(es) this issue affects.)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Wrong branch linked, use `master` (even if the line you point to now is identical for the time being) - https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/SpellEffects.cpp#L322

Do you have proof that `SPELL_EFFECT_GIVE_HONOR` is 253 and not 254, what is your source?

**Comment by P-Kito** [comment]
There is no need for proofs if u have SpellWork open u can check it within 2 seconds :P

**Comment by P-Kito** [comment]
Invalid-IncompleteData/NotTrinityCore ?

**Comment by funjoker** [comment]
> [//]: # (***************************************************************)
> [//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
> [//]: # (***************************************************************)
> 
> **Description:**
> 
> **Current behaviour:** (Tell us what happens.)
> 
> **Expected behaviour:** (Tell us what should happen instead.)
> 
> **Steps to reproduce the problem:**
> 
> 1. 
> 2. 
> 3. 
> 
> **Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
> 
> **TC rev. hash/commit:**  
> 
> **TDB version:**  
> 
> **Operating system:**  
> 
> 
> [//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
> [//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
> [//]: # (For fixes containing C++, create a Pull Request.)
>
