### ISSUE TITLE
[7.1] Tools/Connection_Patcher: Mac OS X Executable Crash

### ISSUE THREAD

**Issue by Razinao** [TrinityCore/TrinityCore#18145]
**Description:**
On pressing 'connect' on the account credentials screen, the client crashes.

This is similar to issue https://github.com/TrinityCore/TrinityCore/issues/16872.

The client crash does not happen if tc_bundle.txt is not in your WoW folder (but you can't connect to the server)

**Current behaviour:**
You patch World of Warcraft.app, run World of Warcraft Patched.app with tc_bundle.txt in the same directory, you try to log into an account and the client crashes.

**Expected behaviour:**
You should be able to log onto the server without a client crash, like the Windows client does.

**Steps to reproduce the problem:**
1. Patch the Mac Client
2. Start the Patched Client
3. Write in Login Details
4. Press "Login"

**Branch(es):** Master

**TC rev. hash/commit:**  c2d1e43b376834f98ee0b8b1938b99a9a357c00e

**TDB version:**  703.00

**Operating system:**  OS X El Capitan 10.11.6

**Comment by zamalaev** [comment]
confirm
OS Win 64 Pro error connect to server

**Comment by cocolino** [comment]
I know this is outdated, but can we expect a ConnectionPatcher tool patterns update for 7.1 any time soon?

**Comment by Shauren** [comment]
For x64 windows yes, for mac much less likely (and x86 windows already works)

**Comment by cocolino** [comment]
x86 windows same error:

Creating patched binary...
Win32 client...
patching Portal
EX: unable to find pattern
An error occurred. Press ENTER to continue...

Thank you for your answer and have a good day.

**Comment by tkrokli** [comment]
@zamalaev : this issue belongs to OSX (Mac).

**Comment by DDuarte** [comment]
By @aaplmike on #18305:

> **Description:**
> Mac client crashes immediately on clicking connect. I've seen this error before with the tc_bundle.txt file needing to be replaced. I've put the crash dump up at http://pastebin.com/z7Y5X9m7
> 
> **Current behaviour:** (Tell us what happens.)
> Mac client crashed immediately on clicking Connect.
> 
> **Expected behaviour:** (Tell us what should happen instead.)
> Successful connect to game server.
> 
> **Steps to reproduce the problem:**
> 
> 1. Run comm client to apply all patches
> 2. Pull Master branch and build connection_patcher. Build server also with latest pull.
> 3. Apply connection patcher to client, observe success message
> 4. Change WTF/Config.wtf to point to my local server (also patched to latest)
> 5. Launch World of Warcraft Patched
> 6. Enter known good creds
> 7. Hit Connect
> 
> **Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
> Master
> 
> **TC rev. hash/commit:**  
> TrinityCore rev. 9f31a6aa3cd7 2016-11-23 17:05:36 +0100 (master branch) (MacOSX, Release, Static)
> 
> **TDB version:**  
> TDB 703.00
> 
> **Operating system:**  
> MacOS Sierra
> 
> I've removed the cache files from /Users/Shared/Blizzard/Battle.net/Cache. I've also removed tc_bundle.txt and let the patcher replace it a couple times. I've observed from the bnetserver console no connection attempts.

**Comment by ethyrie** [comment]
I can confirm the issue

**Comment by tkrokli** [comment]
@ethyrie : Please include TC rev. hash/commit (Hash de Commit) when you confirm any TC issues.
