### ISSUE TITLE
[7.X] Worldserver Crash after startup

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#18141]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Worldserver crashes afer about 5 seconds when completes loading.

Revision: TrinityCore rev. a249d86b00eb 2016-10-16 17:38:56 +0100 (6.x branch) (Win64, Release, Static)
Date 26:10:2016. Time 11:45 

World DB: TDB 703.00

[a249d86b00eb_worldserver.exe_[26-10_11-45-52].txt](https://github.com/TrinityCore/TrinityCore/files/552786/a249d86b00eb_worldserver.exe_.26-10_11-45-52.txt)

[a249d86b00eb_worldserver.exe_[26-10_11-45-52].txt](https://github.com/TrinityCore/TrinityCore/files/552790/a249d86b00eb_worldserver.exe_.26-10_11-45-52.txt)

**Comment by Aokromes** [comment]
change to master branch, 6.x branch is no longer supported.

**Comment by DDuarte** [comment]
If you want to get anything useful from crashlogs you will need to compile in debug mode.
