### ISSUE TITLE
[3.3.5] Visual bug with CC

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18142]
**Description:** After @ariel- did his fixes in: https://github.com/TrinityCore/TrinityCore/commit/2f03d502f34d0e9f69fd2d23cfb69b1ec8bb8891

The DR seems to be fixed but there is a visual bug now, where the spell visual itself stays on the target for the full duration but the CC itself goes away. This is tested with Chains of Ice.

**Current behaviour:** (Tell us what happens.) Visual stays, CC goes away as it should.

**Expected behaviour:** (Tell us what should happen instead.) The visual should also go away.

**Steps to reproduce the problem:**

1.  Use Chains of Ice on a target and wait the duration.
2.  Use chains of ice again, notice that you can run normally while the visual is still going at full duration.
3. profit.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8da43fb7c7b9d072c924a741900162584e026970

**TDB version:**  redundant

**Operating system:**   ubuntu 14.04

**Comment by Persephone** [comment]
Haha really, cosmetic 💃  ?? :P

**Comment by Shauren** [comment]
well, yeah? its just a visual

**Comment by Persephone** [comment]
Just assumed it was for code cosmetics like coding standards, not an actual ingame cosmetic ^^

**Comment by tkrokli** [comment]
Well, at least now you know what we mean when the label [Priority-Cosmetic] is used. ;-)

**Comment by Persephone** [comment]
Indeed :P

**Comment by Keader** [comment]
Relax, Ariel should fix it fast...
Labels dont define how fast a issue are fixed.

**Comment by Persephone** [comment]
Never said anything about that, just found it funny they used that label :-)

**Comment by Keader** [comment]
That label is used for all visual bugs xD

**Comment by Persephone** [comment]
as tkroli said, now I know :P

**Comment by Kittnz** [comment]
Must be something wrong eitherway, not having the desired effect is a nono

**Comment by ariel-** [comment]
I can't seem to repro the issue with Chains of Ice. Snare effects don't have DR

**Comment by Persephone** [comment]
Ahh alright my bad then :)
