### ISSUE TITLE
[3.3.5] Dots/Debuffs trigger cheetah daze

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18153]
**Description:** Dots & Debuffs trigger daze from aspect of the cheetah

**Current behaviour:** (Tell us what happens.) Dots & Debuffs trigger daze from aspect of the cheetah

**Expected behaviour:** (Tell us what should happen instead.) Only direct damage should trigger daze

**Steps to reproduce the problem:**

1. Activate aspect of the cheetah
2. get hit by a dot
3. see daze proccing

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/a056cb2978956046d135579d11cedde0a81d3c9d

**TDB version:**  TDB 335.62

**Operating system:**  ubuntu 14.04

**Comment by tkrokli** [comment]
Any closing comments, like why you closed this (invalid issue or something else) ?
