### ISSUE TITLE
[3.3.5] Chaos Bolt not working

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#18154]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**: After @ariel- did his fixes in:  d3a71a83387f757f87c7d27e1054498c8cc49c8f
Chaos Bolt not working, it has not any damage and damge log after I casted it.

**Current behaviour:** (Tell us what happens.) Chaos Bolt should has damage.

**Expected behaviour:** (Tell us what should happen instead.) Chaos Bolt should has damage.

**Steps to reproduce the problem:**

1. Cast Chaos Bolt  (lvl1 spellid: 50796, lvl2 spellid: 59170, lvl3 spellid: 59171, lvl4 spellid: 59172)
2. Cast Chaos Bolt  (lvl1 spellid: 50796, lvl2 spellid: 59170, lvl3 spellid: 59171, lvl4 spellid: 59172)
3. Cast Chaos Bolt  (lvl1 spellid: 50796, lvl2 spellid: 59170, lvl3 spellid: 59171, lvl4 spellid: 59172)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  d3a71a83387f757f87c7d27e1054498c8cc49c8f

**TDB version:**  TDB 335.62 and updated newest sql files.

**Operating system:**  Windows Server 2012 R2 64bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DeActiveDev** [comment]
all spells was fixed why change big update or small update , Trinity Core have very good dev's but for learn if is frist that dev test after code adding in source now a lot bug started in the game for this and some updates , this time 2 or 4 bug fixed that time with now update 10 or ... bug start . or now wintergrasp .... and any after old time :(( now just create new bug's

**Comment by ariel-** [comment]
@DeActiveDev the new proc system fixed long overdue bugs like #3463. No need to bitch about it

These small bugs are often easily solved.

**Comment by Killyana** [comment]
It's humanly impossible to test all spells with all talents, also every future or modification could create new bugs, it works like this. Psevers that uses TC that report issues to be fixed, otherwise deal with it.

**Comment by ariel-** [comment]
Turns out there was a mistake somewhere else

**Comment by Keader** [comment]
After large changes, new bugs ir normal. Ariel is fixing all issues related to proc system in 1 or 2 days... dont complain please, he's doing a amazing work.

**Comment by noryad** [comment]
I believe in the work of ariel, congratulations.

**Comment by shenhuyong** [comment]
It cause an warning from vs2015, warning C4146: unary minus operator applied to unsigned type, result still unsigned

**Comment by jackpoz** [comment]
> It's humanly impossible to test all spells with all talents

that's why Information Technologies developed a new common practice called Unit Testing, which incidentally is today's topic on Commit Strip http://www.commitstrip.com/en/2016/10/27/a-magical-cure/

**Comment by DeActiver** [comment]
@Keader at this time say 1 or 2 day or 1 week don't fix because now creates a lot bugs for characters or pet talents , spells , state characters imperfect and any state pet imperfect for example hit and ... , TC always GOOD runner but this time no, I patronage TC every time . i don't want say who is good who is bad work's . but if is any update better test for 1 one code fixed and creates other bugs.
generally I hope TC back to GOOD runner .

**Comment by Aokromes** [comment]
ariel- made a branch to allow people to test the fix, people had weeks to test it, if no one did, you known who to blame, and not ariel.
