### ISSUE TITLE
3.3.5 / Hunter spell volly with buff Viper Sting

### ISSUE THREAD

**Issue by DeActiveDev** [TrinityCore/TrinityCore#18152]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** don't return some % of mana with attacks volly.

**Current behaviour:** (Tell us what happens.) just give % Viper Sting mana  buff and must + Viper Sting mana buff  for volly attack hunter's, 
this problem really important for recovery mana. i tested in game real return  low mana but % viper buff for decast time volly is ok.  for attack volly don't work.

**Expected behaviour:** (Tell us what should happen instead.)

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  a056cb2978956046d135579d11cedde0a81d3c9d

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Dup #18129

Viper string must NOT proc with Volley

**Comment by DeActiveDev** [comment]
:-1:  real good

**Comment by tkrokli** [comment]
@ariel- : are you sure you haven't confused
- http://wow.gamepedia.com/Viper_Sting_(hunter_ability)

with
- http://wow.gamepedia.com/Aspect_of_the_Viper ?

***
Aspect of the Viper (http://wotlk.openwow.com/spell=34074) :

| Type       | Value                               | Type        |  Value |
| ---------  | --------------                      | ----        | ------ |
| Cost       | None                                | Duration    |   n/a  |
| Range      | 0 yards (Self)                      | School      | Nature |
| Cast time  | Instant                             | Mechanic    |   n/a  |
| Cooldown   | 1 second                            | Dispel type |   n/a  |
| Effect # 1 | Apply Aura: Mod Total Power Regen % |
|            | Value: 4 every 3 seconds            |
| Effect # 2 | Apply Aura: Mod Damage Done % (127) |
|            | Value: -50                          |

***
Viper Sting (https://web.archive.org/web/20100823102721/http://www.wowhead.com/spell=3034/viper-sting) :

| Type      | Value                                | Type        |   Value   |
| --------- | ------------------------------------ | ----------- | --------- |
| Cost      | 8% of base mana                      | Duration    | 8 seconds |
| Range     | 5 - 35 yards (Hunter)                | School      | Nature    |
| Cast time | Instant                              | Mechanic    |    n/a    |
| Cooldown  | 15 seconds                           | Dispel type | Poison    |
| Effect:   | Apply Aura: Periodically Drain Power |
|           | Value: 1 every 2 seconds             |

**Comment by ariel-** [comment]
No, Viper sting is just a mana leech aura, it's not supposed to proc with anything.

Aspect of the Viper is a proccing aura, but it shouldn't proc on Volley (as stated in #18129)

**Comment by tkrokli** [comment]
Right. Very well. Thanks for explaining it, I was a bit too busy to actually look up any proc info. 😜

**Comment by DeActiveDev** [comment]
volly+ Viper String = if Hunter's 7 shot  must with for 7 shot return % mana . 3 week before was fixed or worked but now don't work.

**Comment by Keader** [comment]
Because before proc re-write, spell was bugged and no one reported...
ancient bug btw, now looks work right 🐤

**Comment by DeActiveDev** [comment]
ok , you work's but a long time a lot bugs create and after old years now looks work right!!! ,nice

**Comment by DeActiver** [comment]
-ariel don't have idea temporary for this problem ? Or you want to be completed ?

**Comment by irgc** [comment]
hi guys

confirm
spell hunter [Aspect of the Viper] buged. 62 + 63

When will this problem be solved?

**Comment by Keader** [comment]
Is working boy...
