### ISSUE TITLE
Dynamic directory with merged binary and config

### ISSUE THREAD

**Issue by knuxyl** [TrinityCore/TrinityCore#18159]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Cannot compile under a permanent dynamic address. Trying to compile binaries with configurations in same folder and be able to move to another platform in different directory.
**Current behaviour:** (Tell us what happens.)
It installs to either a default directory (/usr/local/bin and /usr/local/etc) or what you set with CMAKE. I cannot seem to make this configuration dynamic.
**Expected behaviour:** (Tell us what should happen instead.)
I would like to have it where I can merge /usr/local/bin and /usr/local/etc (the binaries and configs) and be able to put them in whatever directory I want without recompiling the whole thing.
**Steps to reproduce the problem:**

1. Compile the source
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5, probably all TrinityCore
**TC rev. hash/commit:**  
n/a
**TDB version:**  
n/a
**Operating system:**  
Ubuntu 16.04/15.10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Just to see if I understand what you mean: You are looking for a Linux solution to make the TC server files/ directories behave like they do on Windows, where the .conf files are in the same directory as the servers and that it is possible to move that directory / folder tree to a different location?

**Comment by Keldo** [comment]
I think he is looking to make the TrinityCore install more generic Linux type. IE: /bin, /etc instead of /home/$(USER) so his install is always dynamic, most likely he is trying to create a linux install or something... ?

**Comment by tkrokli** [comment]
OK, thanks for the added details. Either way, this is not an issue, it is more like a "Future Feature Request" or a topic discussion which belongs in the TrinityCore Forum and not in the issue tracker. Close it?

**Comment by knuxyl** [comment]
I don't think I could've explained this simpler. I reinstall my linux os multiple times in a month and I don't want to have to recompile the source everytime, and I don't want to have it depend on being in a specific directory each time. I just want to be able to go in any folder that it is in and execute it. I don't care about it being in /bin or w/e, I just want to be able to move it around. As it is now, It always looks for the conf in /usr/local/etc. I don't want that. I want the config with the binaries so I can move the files around.

**Comment by tkrokli** [comment]
Well, most of us others usually like to use a fixed compilation target (maybe even with the install option included), to be able to start the servers & game with no more changes needed than the occasional modification to the .conf files. To move the files around is more like a repack philosophy, in my opinion.
That is why I said that this belongs to the TC Forums and not in the issue tracker. Objections, anyone?

**Comment by Shauren** [comment]
Both authserver and worldserver have -c/--config argument to override compiled config location so no problem here.

**Comment by knuxyl** [comment]
Thanks Shauren, doing ./authserver --config authserver.conf fixes my problem. I'd rather not have to do it this way, I'd like it to automatically do this during compilation, just check same folder for configurations files, but this works. thanks again

**Comment by Shauren** [comment]
Trust me, getting current working dir in a cross-platform way is far from an easy task.
