### ISSUE TITLE
[Quest] Ending Their World [$15]

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#1815]
In quest http://www.wowhead.com/quest=9759/ending-their-world you must follow and protect http://www.wowhead.com/npc=17982 so he can destroy the vector coil and slay  http://www.wowhead.com/npc=17678 but the event never starts.
It is also miising some spell effects like seen here: http://www.wowhead.com/npc=17678#screenshots

TDB 40 91b572d6693b

**Comment by ccrs** [comment]
the fix has major problems, and quest cant be completed

**Comment by danlapps** [comment]
Is this still valid after all the commits linked ?

**Comment by tkrokli** [comment]
@danlapps : notice that all of the commits above have only been applied to Rushor's repo, not TC repo. So until Rushor's PR is merged, TC source still has this issue (but it looks like Rushor may be close to collecting $10, by the looks of #14149).

**Comment by danlapps** [comment]
Thanks @tkrokli.  Didnt realize they were applied to Rushor and not TC :)

**Comment by tkrokli** [comment]
I know, I made that mistake myself some time ago. Hover you cursor over the PR text to see the link path (not the ALT text popup, but the browser's previewed link somewhere else on your screen).
