### ISSUE TITLE
[3.3.5/7.x] Spell Mod can be used without class mask.

### ISSUE THREAD

**Issue by Unknown-1000** [TrinityCore/TrinityCore#18160]
**Description:**
Spell Mod can be used without class mask
**Current behaviour:** (Tell us what happens.)
Spell Mod use SpellClassMask (from SpellInfo.cpp code), also used only for player target. 
**Expected behaviour:** (Tell us what should happen instead.)
Spell Mod can be used without class mask, can be used without player.
**Steps to reproduce the problem:**
1. .Cast self 52290 (Spell used by npc!), or .Cast self 105066, or .Cast self 125621, or .Cast self 160257
2. No
3. No

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Both.
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/f0f8fe7f917dc857b21119d633283abb6af39033
**TDB version:**  
https://github.com/TrinityCore/TrinityCore/releases/tag/TDB703.00
**Operating system:**  

http://www.wowhead.com/spell=52290
http://www.wowhead.com/npc=26447/drakkari-shaman

http://www.wowhead.com/spell=160257/blood-charge
http://www.wowhead.com/spell=160247/bloody-mess#triggered-by
Not have spell class mask, but have trigger spell.

http://www.wowhead.com/spell=125621/spirit-barrage#triggered-by
Not have spell class mask and used by npc.

**Comment by ariel-** [comment]
SpellMods without ClassMask/FamilyName apply to all abilities, this is totally intended and blizzlike.

```
ID - 52290 Mastered Elements
=================================================
Description: When activated, this spell gives your next damage spell a $s1% damage bonus and reduces the mana cost by $s2%.

=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 100
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 79 (SPELL_AURA_MOD_DAMAGE_PERCENT_DONE), value = 100, misc = 126 (126), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -100
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 108 (SPELL_AURA_ADD_PCT_MODIFIER), value = -100, misc = 14 (SPELLMOD_COST), miscB = 0, periodic = 0
```

**Comment by Unknown-1000** [comment]
Understand, thanks. But one little questions: how spellmod affect for trigger spell 160257. Cannot find in code handler.

**Comment by Unknown-1000** [comment]
@ariel- testing spells require the same amount of mana if have aura or not have. Without ClassMask not work. You should not have closed the issue - the problem is not solved. Please re-open.

**Comment by ariel-** [comment]
It's not a general issue.

What testing spells require mana?

**Comment by Unknown-1000** [comment]
116 - Frost Bolt. Used mana.

**Comment by tkrokli** [comment]
- http://www.wowhead.com/spell=116/frostbolt#changelog
- https://web.archive.org/web/20100809230025/http://www.wowhead.com/spell=116
- http://wotlk.openwow.com/spell=116
- http://wow.gamepedia.com/Frostbolt#Patches_and_hotfixes

**Comment by ariel-** [comment]
Frostbolt is SPELLFAMILY_MAGE, Mastered Elements is SPELLFAMILY_GENERIC, it won't affect frostbolt.

**Comment by Shauren** [comment]
But you just said this
> SpellMods without ClassMask/FamilyName apply to all abilities, this is totally intended and blizzlike.

And SPELLFAMILY_GENERIC = 0, so that is a spellmod without FamilyName

**Comment by ariel-** [comment]
Ok, I realise the logical fail

**Comment by Unknown-1000** [comment]
WoW, thanks for repair. Please add commit for master branch too. Thanks for your work.
