### ISSUE TITLE
[7.x] Missing opcodes.

### ISSUE THREAD

**Issue by cocolino** [TrinityCore/TrinityCore#18165]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** [7.x] Missing opcodes.

**Current behaviour:** (Tell us what happens.) These opcodes are missing completely.

**Expected behaviour:** (Tell us what should happen instead.) They should be researched and maybe added :stuck_out_tongue: 

**Steps to reproduce the problem:**

1. Look Below.
2. These following opcodes I have found to be missing in 7.1:

a) SMSG 0x2C58 - Related to secondary powers like Astral Power, usually sent before SMSG_SPELL_ENERGIZE_LOG. Contains uint32 powerType.
b) CMSG 0x353D - Related to Quests. This pops up only on taking a quest with Auto Accept flag (like start zones). Contains uint32 questId.
c) Other opcodes: 
                            - SMSG 0x2845 (Maybe related to Group members),
                            - SMSG 0x290E (Maybe related to Garrison opcodes - NPC open stuff),
                            - SMSG 0x2901,
                            - SMSG 0x263A (Related to AreaTriggers),
                            - CMSG 0x322A (Contains 1 uint32, some form of query request, response is SMSG 0x282E, also unk),
                            - SMSG 0x2908 (Maybe Garrison mission related),
                            - SMSG 0x2639,
                            - SMSG 0x2845.

3. If i find more i will report back (PS: This is not a typo, i wrote 3 here in the edit window and it shows 1).

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) - master, 7.x.

**TC rev. hash/commit:**  6076f9312a9925e5d6930cfcb5204df29447d143

**TDB version:**  Not important.

**Operating system:**  Not important.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
duplicate, to lazy to search for original ticket.

**Comment by cocolino** [comment]
@Aokromes This cannot be a duplicate, i doubt somebody posted something like this since the 7.1 update.

**Comment by Aokromes** [comment]
the missing opcodes per se is duplicate.

**Comment by cocolino** [comment]
Oks, i'm sorry my research is not needed :smile: . Don't forget though many opcode values changed in 7.1 though, including some of these (example points a and b).

**Comment by Shauren** [comment]
They are missing because I don't have a name for them (and I can't give them a name without knowing what exactly they do) - and we are not adding them with names like SMSG_UNKNOWN
