### ISSUE TITLE
[7.1] Can't start server under linux / DB2 error 

### ISSUE THREAD

**Issue by emilieAnd** [TrinityCore/TrinityCore#18166]
**Description:** We can't start server under linux 

**Current behaviour:** When you build the TC all is fine, but you launch worldserver, you get an error : http://pastebin.com/p5sqfhy6 / crashLog : http://pastebin.com/fxhr84DZ
Mysql : 5.5.52

Already extract all the DB2 from the official : 7.1.0 (22908)

**Expected behaviour:** Should launch the server 

**Steps to reproduce the problem:**
1. git pull TC
2. build the core 
3. Launch the worldserver

**Branch(es):** Master 7.1.0 (22908)

**TC rev. hash/commit:**  6076f9312a9925e5d6930cfcb5204df29447d143

**TDB version:**  703 

**Operating system:**  linux : debian 8.4 jessie 64

On windows everythings is work perfectly !
Thank you for your work and time !

**Comment by Keldo** [comment]
This happened to me last night on a Debian 8.d x32 Build, I'm currently building on x64

**Comment by b0ne** [comment]
I have the exact same problems on a Debian build!

**Comment by Keldo** [comment]
Build on Debian 8 x64 Complete, Segmentation Fault ..... again ......

**Comment by tkrokli** [comment]
Make sure you have followed the suggestions on the forum page:
- [**Startup errors**](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47668)
- [**How to enable debug logs**](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672)

**Comment by Keldo** [comment]
Ancient forums prior to 7.1 are useless, this had only been happening since TC jumped to 7.1

**Comment by DDuarte** [comment]
Yet to see a crashlog in debug mode.

**Comment by tkrokli** [comment]
http://pastebin.com/raw/fxhr84DZ should be a debug log from what I can see (or did I miss something?)

**Comment by Shauren** [comment]
Thats not a debug log, there are no local variables printed there

**Comment by b0ne** [comment]
@Shauren How can I make a debug log?

**Comment by b0ne** [comment]
Building with a debug log will report back when I'll have it

**Comment by b0ne** [comment]
I'm not able to do any debugLog with the info @tkrokli  gave earlier : How to enable debug logs

**Comment by duckman** [comment]
I'm having issues getting debug logs as well. Here is a gist of the log that is created, the commands being used, and the output being displayed: https://gist.github.com/duckman/8784fbcf46b96e5568ad354e8363ebfb
I'm not sure if any of this helps, but its the step I am at. If there is anything I am missing or anything else to try, I will.

**Comment by tkrokli** [comment]
http://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake
http://stackoverflow.com/questions/23907679/cmake-ignores-d-cmake-build-type-debug
http://stackoverflow.com/questions/33953922/cmake-c-set-header-debug-variable-on-compilation

http://cmake.3232098.n2.nabble.com/No-debugging-symbols-found-when-using-DCMAKE-BUILD-TYPE-Debug-td7593579.html

**Comment by Keldo** [comment]
I got the 7.1.0 Server working on Ubuntu 16 but still getting the segmentation fault on Debian 8, may have to re image my VPS to get this up and running again

**Comment by duckman** [comment]
I tried setting -DCMAKE-BUILD-TYPE to Debug instead of None and I am getting the same result. I think that's what you were getting at with your links. I'm pretty far out of my comfort zone. Sorry I can't be of more help.

**Comment by Aokromes** [comment]
IDK guys what are you doing, i have used https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672 for years and they simply work.
