### ISSUE TITLE
DB/Creature: Raptor behavior in Whelgar's Retreat in Wetlands

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18168]
**Description:** Raptors at the edge of Whelgar's Retreat in Wetlands attack and cannot be killed. 

**Current behaviour:** Very odd circumstance.  I had a low level toon and stood at the edge of Whelgar's Retreat, and suddenly was attacked by Raptors that appeared to be dead/laying on the ground. On retreat, the Raptors followed me as if they were being dragged and continued to attack; there was no way for me to defend myself as the raptors were not able to be selected for spells/casts/attack. No animation, movement or anything that would otherwise indicate they were there, other than their figure sliding towards the player. On activating my GM toon, I returned and the behavior repeated itself. With the GM mode turned on, the raptor was selectable and ".die" command killed the creature. The raptor was not selectable for attacks or any other options unless GM mode was turned on. 

**Expected behaviour:** Raptor should be killable. Selectable, and actually moving, not dragging on the ground like a dead dog on a leash.

**Steps to reproduce the problem:**
1. Roll any toon to Whelgar's Retreat in Wetlands
2. Approach edge of camp by steps.
3. Observe Raptor behavior.
4. Attempt to kill with GM off.
5. Turn GM on
6. Raptor is now selectable, yet still does not move.

**Branch(es):** 6.x, 7.x

**TC rev. hash/commit:**   TrinityCore rev. c676e80 2016-09-29 23:30:47 +0200 (6.x branch) (Unix, Release, Static)

**TDB version:**  6.x

**Operating system:**  Windows 10

**Comment by BahDumbBugs** [comment]
Raptors have names. These are showing under "Cosmetic Mottled Raptor" with GM on.

**Comment by tkrokli** [comment]
Any chance you will be moving on to the `master` branch in the near future? :-)

**Comment by BahDumbBugs** [comment]
@tkrokli - Need to discuss something with you. Any way to PM you? :)

**Comment by tkrokli** [comment]
> https://community.trinitycore.org/profile/18673-tkrokli/

**Comment by BahDumbBugs** [comment]
As of commit 8b2e071, this error still exists. Just validating it. :)

**Comment by nubqt** [comment]
The suggested expected behavior is incorrect. These NPCs are purely cosmetic as part of the lore of the camp. They are supposed to represent raptors that the dwarves have killed after getting near the dwarven camp. Therefore, they should not be clickable, nor alive, nor mobile, nor killable.

Source: http://www.wowhead.com/npc=40495/cosmetic-mottled-raptor#comments

I will see what I can do.

**Comment by nubqt** [comment]
**Forensics:** the raptors were missing the UNIT_FLAG_PACIFIED in `creature_template`. Since this is a bitwise field, adding the value of that flag to the existing value would enable the flag. Therefore, 33554432 (current flag, which makes them non-selectable) + 131072 (which restricts them from attacking) = 33685504.

**Suggested fix:**

```sql
UPDATE `creature_template` SET `unit_flags` = '33685504' WHERE `id` = '40495';
```

Please test and confirm suggestion.

**Comment by tkrokli** [comment]
TC normally uses bitwise addition in queries:
```sql
UPDATE `creature_template` SET `unit_flags`=`unit_flags`| 131072 WHERE `id`= 40495;
```
Please also note that TC codestyle requires integers (DB **int**) is never surrounded by ' ' (apostrophes).

**Comment by nubqt** [comment]
@tkrokli: shouldn't the label for feedback be added to this ticket now? (for your suggestion)

**Comment by tkrokli** [comment]
Thanks for the reminder. I had a lot on my mind.
BTW, it is mostly your suggestion. I just reformatted it.

**Comment by offl** [comment]
If he has unscripted aura or if his current unit_flags are correct(sniffed), then it is hack.

**Comment by tkrokli** [comment]
Hmm, is it possible to confirm the suggested `unit_flags` change by sniff (https://github.com/TrinityCore/TrinityCore/issues/18168#issuecomment-343871147) ? Or is it purely based on the wowhead description?

**Comment by offl** [comment]
Try with this.
```sql
UPDATE `creature_template` SET `AIName`='PassiveAI' WHERE `entry`=40495;
```

**Comment by tkrokli** [comment]
Good idea. @BahDumbBugs & @nubqt - can you check and see if it works as intended?
