### ISSUE TITLE
Boss deathbringer saurfang

### ISSUE THREAD

**Issue by DeActiver** [TrinityCore/TrinityCore#18169]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** after last update commit 2ff855054f52bf2dcf81aa7a7da7bab7f8a99686 boss don't empty energy mark , but same time ok .
must multiple tests to be , most of the first test you can know

**Current behaviour:** (Tell us what happens.) stat energy %100 Up and boss don't give mark of champion

**Expected behaviour:** (Tell us what should happen instead.) after energy stat full give mark and must back to 0 stat energy.

**Steps to reproduce the problem:**

1. commit 2ff855054f52bf2dcf81aa7a7da7bab7f8a99686 for now  and other problems

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**   d48cf7500585f277e1ee2016f2321ea48c118766

**TDB version:**  62

**Operating system:**  win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Wat

**Comment by DeActiver** [comment]
solo test !!! no

**Comment by DeActiver** [comment]
yeh  ariel-  Boss_deathbringer_saurfang fixed sorry for my mistake... Just please focus proc re-write for fix spells real very bad is for TC after old years.
thank you
