### ISSUE TITLE
[3.3.5] Spell/Racial: Fear hits shadowmelded targets

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18174]
**Description:** Fear hits shadowmelded targets
- http://wotlk.openwow.com/spell=58984
- http://www.wowhead.com/spell=58984/shadowmeld
- http://wow.gamepedia.com/Shadowmeld

**Current behaviour:** (Tell us what happens.) If you are shadowmelded and a lock uses fear, you get feared.

**Expected behaviour:** (Tell us what should happen instead.) Shouldn't get feared.

**Steps to reproduce the problem:** 
1. Get a night elf (any class) and use Shadowmeld
2. Get a horde warlock and place it near the night elf
3. Use fear near the shadowmelded player

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/0cd67c1f151a47b1eeec2f252687356ed0d79ad9

**TDB version:**  TDB 335.62    62

**Operating system:**  ubuntu 14.04

**Comment by ariel-** [comment]
Where does it say in Shadowmeld that makes you immune to fear effects?

**Comment by tkrokli** [comment]
I tried to look for anything in the spell descriptions and wowhead comments, but I could not find any definitive description saying that a shadowmelded player should become untargetable to damage or fear effects, only that it removes current threat the player has from mobs. Invalid issue, maybe?

**Comment by Keader** [comment]
Maybe should fail cast, because shadowmeld force "target lost"...

**Comment by Persephone** [comment]
Yeah what Keader said, I might have explained it wrong

**Comment by SnapperRy** [comment]
If player shadowmelds while the enemy is casting, it should probably interrupt the cast.

But if the player is shadowmelded and the warlocks gets near enough to see him, then fear should work normally.

**Comment by tkrokli** [comment]
OK, so maybe this has to be tested with equal player levels (a higher level enemy can see a shadowmelded player or if within aggro range) and also test if the fear hits from within aggro range or from outside.

**Comment by Keader** [comment]
yeap, SnapperRy is right :)

**Comment by Persephone** [comment]
@Keader exactly, that is what aint happening atm it aint cancelling :)

**Comment by ariel-** [comment]
Well, the issue repro steps made me think you were reporting that a shadowmelded player should be immune:

> Get a horde warlock and place it near the night elf
> Use fear near the shadowmelded player

**Comment by tkrokli** [comment]
Sorry for meddling with the issue, step 1 & 2 are my additions (seemed logical based on step 3).
Step 3 is the original text provided by Persephone.

**Comment by ariel-** [comment]
Can't reproduce in 471a8bccc3078778bacf3b0af63e0f0beb15d00e
