### ISSUE TITLE
Core/Spell: SPELL_ATTR6_NO_DONE_PCT_DAMAGE_MODS

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18177]
**Description:**
This attribute don't work as intended example:

ID - 12721 Deep Wounds
1. Tick 63 (100%) (Min: 113 Moy: 259 Max: 573) without icc buff
1. Tick 50 (100%) (Min: 242 Moy: 462 Max: 937) with icc buff
http://www.wowhead.com/spell=73822/hellscreams-warsong

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L8077

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 697147a59651

**Comment by ariel-** [comment]
Keep in mind, the damage of the deep wounds is not increased, but the damage of your weapons is. The attribute only means that it won't "double dip" in the damage increase.

**Comment by Killyana** [comment]
I opened this issue because deep wounds is the first source of damage for war arm and third source for war fury, this looks too much, but it's not related to this attribute.
