### ISSUE TITLE
DB/Creature: Skullsplitter Hunter & Skullsplitter Beastmaster

### ISSUE THREAD

**Issue by Staleness89** [TrinityCore/TrinityCore#18179]
**Description:**
http://wotlk.openwow.com/npc=784
http://wotlk.openwow.com/npc=669

Both these npcs have a 'Skullsplitter Pet' summon spell, which according to comments they can use shortly after their pet dies. Currently, however, the pets are spawned permanently next to these NPCs and they do not use the spell. They don't have any SAI attached as of now either.

**Current behaviour:** (Tell us what happens.)
The pet NPCs 'Skullsplinter Panther' are spawned permanently next to the Skullsplinter mobs.

**Expected behaviour:** (Tell us what should happen instead.)
The Skullsplinter Panthers should be pets, and be resummonable upon their death

**Steps to reproduce the problem:**

1. Go to Strangelthorn Vale where these npcs are.
2. Notice the panthers aren't connected to the Skullsplinter mobs as pets

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
both?

**TC rev. hash/commit:**  
6801357b8acd

**TDB version:**  
TDB 335.62

**Operating system:**  
Win 10

**SUGGESTED FIX**
```SQL
DELETE FROM `creature` where `id`=756; -- Delete all Skullsplitter Panthers

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry` IN (669,784);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (669,784) and `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(669, 0, 0, 0, 60, 0, 100, 0, 0, 0, 0, 0, 11, 3621, 32, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Skullsplitter Hunter - On Update - Cast Skullsplitter Pet'),
(669, 0, 1, 0, 0, 0, 100, 0, 4000, 6000, 8000, 10000, 11, 3148, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Skullsplitter Hunter - IC Update - Cast Head Crack'),
(669, 0, 2, 0, 0, 0, 100, 0, 6000, 8000, 10000, 12000, 11, 3391, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Skullsplitter Hunter - IC Update - Cast Thrash '),
(784, 0, 0, 0, 60, 0, 100, 0, 0, 0, 0, 0, 11, 3621, 32, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Skullsplitter Beastmaster - On Update - Cast Skullsplitter Pet'),
(784, 0, 1, 0, 9, 0, 100, 0, 5, 30, 1661, 2000, 11, 6660, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Skullsplinter Beastmaster - On Range 5-30 - Cast \'Shoot\'');

```
I made this up and actually tested it this time, but I'm not sure about the min/max repeat on Cast 'Shoot'
Also there's a similar issue with Bloodscalp Beastmasters/Bloodscalp Tigers that I will make a separate issue for when I have something for it.

**Comment by tkrokli** [comment]
http://www.wowhead.com/spell=3621/skullsplitter-pet#summons
- http://www.wowhead.com/npc=756/skullsplitter-panther

***
http://www.wowhead.com/spell=3621/skullsplitter-pet#used-by-npc
- http://www.wowhead.com/npc=784/skullsplitter-beastmaster
- http://www.wowhead.com/npc=669/skullsplitter-hunter

**Comment by Staleness89** [comment]
As for differences between branches, they're different levels but they seem to cast the same spells and summon the same npcs on retail now as well as 3.3.5 retail. The update should be good for both branches.

**Comment by tkrokli** [comment]
Let us just wait for feedback from the senior devs. Maybe Killyana, SnapperRy or dr-j can comment on it.
