### ISSUE TITLE
Core/Scripts: missing variable resets with DespawnAtEvade mechanic

### ISSUE THREAD

**Issue by Elron103** [TrinityCore/TrinityCore#18188]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
With the introduction of the DespawnAtEvade mechanic, some NPCs might have issues with evading and resetting correctly.

**Current behaviour:** (Tell us what happens.)
Some boss scripts use the DespawnAtEvade mechanic, which leads to wrong information in the creature after the respawn (e.g. for the variable m_cannotReachTarget). Previously, they used CreatureAI::_EnterEvadeMode to evade and reset correctly.

**Expected behaviour:** (Tell us what should happen instead.)
The creature should reset and evade correctly, even with the DespawnAtEvade mechanic. This means that all variable resets that are performed in CreatureAI::_EnterEvadeMode must also be performed when a creature respawns. Otherwise, the creature respawns with wrong information.

**Steps to reproduce the problem:**

Example (Currently - Wrong):
- Boss sets m_cannotReachTarget to true
- Boss evades
- Boss calls DespawnAtEvade
- Boss respawns and still has m_cannotReachTarget == true
- Boss (in dungeons - not raids) calls AI()->EnterEvadeMode(CreatureAI::EVADE_REASON_NO_PATH);
- Boss (in dungeons - not raids) loops infinitely in despawn / respawn

Example (Correct):
- Boss sets m_cannotReachTarget to true
- Boss evades
- Boss calls DespawnAtEvade
- Boss respawns
- On respawn, m_cannotReachTarget is correctly reset to false
(this might also apply for other variables, that are correctly reset in CreatureAI::_EnterEvadeMode)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
8fe8501

**TDB version:**  
 TDB 335.61

**Operating system:**  
 Debian, Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Same behavior in master branch?
Because DespawnAtEvade was ported for 6x

**Comment by Treeston** [comment]
It's not a core issue, @ariel-. CreatureAI needs to properly call _EnterEvadeMode _before_ despawning.

**Comment by Treeston** [comment]
Hm actually no, fix in core is cleaner.

**Comment by Ghost-R** [comment]
@treeston same issues ? #18095

**Comment by Treeston** [comment]
no

**Comment by tkrokli** [comment]
Happy to see that I did not misunderstand the issue completely when I picked the labels 😄  :-)
(my issue title change could have been more precise, though --- Core/Entities instead of Core/Scripts).
