### ISSUE TITLE
Using TriggerCastFlags hides cast bar

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#18181]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

When using trigger flags (any trigger flag) like TRIGGERED_IGNORE_POWER_AND_REAGENT_COST, that I tested with, there is no cast bar on the creature.
The cast bar can be seen below the creature's portrait. Also the creature does not seem to be in "casting" state while doing the casting of the spell. http://i.imgur.com/oIQYn2o.png
This seems to be only a visual bug.

The reason appears to be this:
Spell.cpp Spell::SendSpellStart
```c++
    if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell()) || m_triggeredByAuraSpell) && !m_cast_count)
        castFlags |= CAST_FLAG_PENDING;
```
because IsTriggered returns true if ANY cast flag is set CAST_FLAG_PENDING is applied to the castFlags
`bool IsTriggered() const { return (_triggeredCastFlags & TRIGGERED_FULL_MASK) != 0; }`
For some reason the flag will hide the cast bar.

I cannot know if this is intended or not, but it is certainly not expected that, for example, ignoring power and reagent cost would disable the cast bar.

In my mind it would seem as if the flag should only be applied to the cast flags if TRIGGERED_CAST_DIRECTLY trigger flag is used.

**Current behaviour:** When using trigger flags TRIGGERED_IGNORE_POWER_AND_REAGENT_COST there is no cast bar or casting state visible ingame (visual bug)

**Expected behaviour:** When using trigger flags TRIGGERED_IGNORE_POWER_AND_REAGENT_COST there is a cast bar and everything works normally except no power and reagent are taken from caster.

**Steps to reproduce the problem:**

1. Make a script that uses `unit->CastSpell(target, 143, TRIGGERED_NONE);` to cast a spell on you
2. Notice how the cast bar does show up for the fireball spell.
3. Make a script that uses `unit->CastSpell(target, 143, TRIGGERED_IGNORE_POWER_AND_REAGENT_COST);` to cast a spell on you
4. Notice how the cast bar does not show up for the fireball spell.

While debugging myself I used `.eluna sel:CastSpell(plr, 143, false)` (note to self)

**Branch(es):** 3.3.5, maybe more

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/e55641f37862434af36b2ea0aea9bf8c79773426

**TDB version:**  335.62?

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ccrs** [comment]
something noticed by @Treeston while making PlayerAI but seems like its how its supposed to be

**Comment by Treeston** [comment]
dup of #16687
