### ISSUE TITLE
[335] Jesper (holiday NPC) despawns too early

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18183]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Jesper (GUID 15310) is a questgiver for Hallows End located in the Stormwind Orphanage. He despawns before the holiday event ends.

**Current behaviour:** Jesper despawns before his holiday event ends. In my case he was gone at 9:00 pm when I went to hand in a quest. I don't know exactly when he despawned because I had not been to Stormwind earlier in the day, but the event ends at 11:59 pm on the 31st according to the in game calendar.

**Expected behaviour:** Jesper should despawn when the holiday event ends

**Steps to reproduce the problem:**

1. Make sure Hallows End is on its last day
2. Go to the Stormwind Orphanage (Cathedral Square) and check for Jesper
3. Depending on the time of day, he will be despawned before the event ends

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system:**  WinXP / Win7

**Note:** Maybe he got adopted because he's the only one that doesn't call himself "Stormwind Orphan" but he could have at least let me finish my quest ;)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
This npc is linked to Hallow's End, he cannot despawn before or after this event, probably someone killed it when you tried to complete your quest.

**Comment by tkrokli** [comment]
Oh. You mean that someone killed the event. For a second there, I thought you meant Jesper  :-p

**Comment by offl** [comment]
Jesper cannot be killed, he is a kid. In WOW players can't kill kids.
Maybe something else happened to him. It's Halloween. Weird things can happen.

**Comment by MrSmite** [comment]
> This npc is linked to Hallow's End, he cannot despawn before or after this event, probably someone killed it when you tried to complete your quest.

Nope, I don't open my server to anyone. Just me playing here.

**Comment by Killyana** [comment]
Cannot reproduce
