### ISSUE TITLE
DB/Creature: Bloodscalp Beastmaster

### ISSUE THREAD

**Issue by Staleness89** [TrinityCore/TrinityCore#18185]
**Description:**
Similar  to #18179 Bloodscalp Beastmasters should summon Bloodscalp Tigers as pets, but instead they are spawned permanently next to them. The Beastmaster is also missing SAI in general.

**Current behaviour:** (Tell us what happens.)
Notice the lack of SAI and how Bloodscalp Tigers aren't connected to Bloodscalp Beastmasters as pets

**Expected behaviour:** (Tell us what should happen instead.)
They both need SAI and to be able to summon these pets.

**Steps to reproduce the problem:**

1. with any GM character, `.go creature ID 699`
2. observe the details described above

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Both (pretty sure)

**TC rev. hash/commit:**  6801357

**TDB version:**  335.62

**Operating system:**  Win 10

**SUGGESTED FIX**
```sql
--
DELETE FROM `creature` where `id`= 698; -- Delete all Bloodscalp Tigers

UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry`= 699;
DELETE FROM `smart_scripts` WHERE `entryorguid`= 699 and `source_type`= 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(699,0, 0,0, 60, 0,100,0, 0,  0,   0,   0, 11, 3612, 32, 0,0,0,0,1,0,0,0,0,0,0,0,'Bloodscalp Beastmaster - On Update - Cast Bloodscalp Pet'),
(699,0, 1,0,  9, 0,100,0, 5, 30,1661,1661, 11, 6660, 64, 0,0,0,0,2,0,0,0,0,0,0,0,'Bloodscalp Beastmaster - On Range 5-30 - Cast \'Shoot\''),
(699,0, 2,3,  4, 0,100,1, 1, 20,   0,   0, 11, 8599,  0, 0,0,0,0,1,0,0,0,0,0,0,0,'Bloodscalp Beastmaster - On 20% Health - Cast Enrage (No Repeat)'),
(699,0, 3,0, 61, 0,100,0, 0,  0,   0,   0,  1,    0,  0, 0,0,0,0,2,0,0,0,0,0,0,0,'Bloodscalp Beastmaster - On 20% Health - Say Line 0 (No Repeat)');

DELETE FROM `creature_text` WHERE `entry`=699;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES 
(699, 0, 0, '%s goes into a frenzy!', 16, 0, 100, 0, 0, 0, 38630, 0, 'Bloodscalp Beastmaster');
```

**Comment by tkrokli** [comment]
I have edited your SQL and put the SAI lines in descending order. Easier to comprehend like that.
I also added some spacing and grouping for human readability.
