### ISSUE TITLE
[3.3.5] Gameobjects missing

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18187]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Consolen Error

```
Gameobject (GUID: 4130 Entry: 4) not created: non-existing entry in `gameobject_template`. Map: 0 (X: -7586.379883 Y: -1285.800049 Z: 301.350006)
Pre-loading base map data for map 1
Gameobject (GUID: 1249 Entry: 129) not created: non-existing entry in `gameobject_template`. Map: 1 (X: -7200.810059 Y: -3859.489990 Z: 706.231995)
```

**Steps to reproduce the problem:**

1. Start the Server with Pre_loading Map

**Branch(es):** 3.3.5 
**TC rev. hash/commit:**  
TC>TrinityCore rev. b31eca151d42 2016-11-01 22:34:44 +0100 (335 branch)

**TDB version:**  
TDB_full_world_335.62_2016_10_17.sql + updates
**Operating system:**  
Win7 64Bit

**Comment by r00ty-tc** [comment]
I don't think that's an issue with the core as such. Pre-loading maps just means all objects/npcs are loaded into memory, so it finds invalid entries upon startup instead of when that specific grid is loaded. Looks like there's a few gameobjects with invalid entry 4 in the DB.

**Comment by Aokromes** [comment]
Not on clean TDB.

**Comment by Shauren** [comment]
@Aokromes even after that trap spawns commit? LinkedTrap field is not validated during startup

**Comment by Aokromes** [comment]
what i mean, there is no gameobject spawn on database with entry 4, maybe the check is bad.

**Comment by Killyana** [comment]
Actually we still have 2 missing traps on gameobject_template: 4 and 129
```
SELECT * FROM gameobject_template WHERE TYPE=8 AND data2 != 0 AND data2 NOT IN (SELECT entry FROM gameobject_template);
SELECT * FROM gameobject_template WHERE TYPE=10 AND data12 != 0 AND data12 NOT IN (SELECT entry FROM gameobject_template);

**Comment by Aokromes** [comment]
added the 2 gos log since it's also show without preload.
