### ISSUE TITLE
Can't knock-back stunned targets.

### ISSUE THREAD

**Issue by Fimbulveter** [TrinityCore/TrinityCore#18180]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Can't knock-back stunned targets.
https://www.youtube.com/watch?v=3krCbZp1Prc (0:26, 1:20, 1:48)

**Current behaviour:** (Tell us what happens.)
Cast a knockback spell (Thunderstorm, Typhoon etc.) on a stunned target. Target won't get knocked back.

**Expected behaviour:** (Tell us what should happen instead.)
Cast a knockback spell (Thunderstorm, Typhoon etc.) on a stunned target. Target gets knocked back.

**Steps to reproduce the problem:**

1. Stun a enemy target
2. Cast thunderstorm
3. No knock-back.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
eb093c1 2016-10-28 12:13:02

**TDB version:**  
TDB_full_335.62_2016_10_17

**Operating system:**  
Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Fimbulveter** [comment]
This resolved the issue.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L4724-L4726

Change

```
// Spells with SPELL_EFFECT_KNOCK_BACK (like Thunderstorm) can't knockback target if target has ROOT/STUN
if (unitTarget->HasUnitState(UNIT_STATE_ROOT | UNIT_STATE_STUNNED))
   return;
```

to

```
// Spells with SPELL_EFFECT_KNOCK_BACK (like Thunderstorm) can't knockback target if target has ROOT
if (unitTarget->HasUnitState(UNIT_STATE_ROOT))
   return;
```

**Comment by tkrokli** [comment]
I wonder, when that code got implemented, if it worked as intended in commit https://github.com/TrinityCore/TrinityCore/commit/41f0923f1bc7563bfb176721df367a38499f5c4b

**Comment by Ovahlord** [comment]
It might have been a misinformation. Maybe it applies only on rooted targets.

**Comment by cocolino** [comment]
Root or stun does not interact with KB's. You can see that clearly as far as root is concerned in the Alysrazor intro where the rooted players and NPC's are knocked back when the volcano erupts. So the whole check is wrong.

**Comment by tkrokli** [comment]
OK, but is that true for any and all root/stun situation and if so, should that check be removed completely?

**Comment by Shauren** [comment]
@cocolino and that is a wrong example, the aura is removed just before the knockback

**Comment by cocolino** [comment]
Yes you are correct, i have reviewed it and the aura is removed before the KB (wrong memory flash, sorry 'bout that). Here is another example regarding stuns though, Siegebreaker http://www.wowhead.com/spell=176289/siegebreaker stuns and knocks you back. It is quite logical too if you consider it, a knockback is an effect that is independent of the player's will or actions, and there should be no reason for it to not worked on a stunned player. As far as root is concerned, it seems after some research that the knockback takes effect only if the spell containing it breaks / removes the root via damage or other effects it also may have (which points to the "Damage may cancel the effect." tooltip thingy on spells like http://www.wowhead.com/spell=339/entangling-roots).
