### ISSUE TITLE
High update time

### ISSUE THREAD

**Issue by Evef** [TrinityCore/TrinityCore#18186]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Hi everyone, I need some help. I have a revision about... January (I know, a little old) when I have about 1500players online .server info show me a little high updates time (about 300 with 1500) I dont have armory scripts or similar. I use 8c/12t, 128GB ram so i dont think this is the problem. I'm using Percona (I tried too with mariaDB and the results are the same)

I cant show you logs or packets cause i dont know what do u need

If you can i appreciate you help
**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5**

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  
Debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
This is Forum material, not an issue for everyone using TrinityCore source.
Please post your question in the TC Forum, https://community.trinitycore.org/forum/5-help-and-support/

**Comment by Evef** [comment]
Sorry and thank you ^^
