### ISSUE TITLE
DB/Quest: Troublesome Distractions - script missing

### ISSUE THREAD

**Issue by Ghost-R** [TrinityCore/TrinityCore#18199]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Creature entry: 20071 missing gossip & script

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)
•	Accept the quest,  Troublesome Distractions, from Tyri at coords 71.2, 35.2 (Celestial Ridge).
•	Travel west, to the Protectorate Watch Post, located at coords 58.2, 31.4.
•	Speak with Wind Trader Marid, and select the dialogue text.
•	Follow Wind Trader Marid east to coords 60.0, 39.9.
•	After Wind Trader Marid turns hostile, kill it.
•	Travel west, back to Celestial Ridge, to coords 71.2, 35.2.
•	Turn in the quest to Tyri.

Video: https://www.youtube.com/watch?v=wrYKF-nyQPc
**Steps to reproduce the problem:**

1. Take quest ID: 10273
2. Go to creature 20071

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
6214c71
**TDB version:**  
335.62
**Operating system:**  
Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Even though this issue post is more detailed (mostly due to new & improved template), I think we should maintain the history of how long this issue has existed by keeping issue https://github.com/TrinityCore/TrinityCore/issues/4617 and close this one. OK?
