### ISSUE TITLE
Aspect of the Viper only applying tick mana.

### ISSUE THREAD

**Issue by krauterz** [TrinityCore/TrinityCore#18195]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Aspect of the viper currently only applies on hit mana bonuses from spells, such as Arcane Shot, and melee auto attacks, but not ranged auto attacks. Ticks working fine.
It would be awesome if someone could confirm if this is only affecting us. Thanks.

**Steps to reproduce the problem:**

1. reduce mana pool by using spells,
2. auto attack a ranged target

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
rev. a77c94eb3752c37f9c4ac3a641288cfe5898454d
Been an ongoing issue over several revisions.

**TDB version:**  
335.62
**Operating system:**  
Windows server 2008 R2

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18152 ?

**Comment by ariel-** [comment]
Not related

**Comment by krauterz** [comment]
Performed a completely fresh build and db install and fixed the issue. sorry for wasting your time :)
