### ISSUE TITLE
[7.1] Groups: Unable to convert group to raid

### ISSUE THREAD

**Issue by Razinao** [TrinityCore/TrinityCore#18198]
**Description:**
The action of converting a group to a raid appears to be broken.

**Current behaviour:** (Tell us what happens.)
Upon clicking 'convert to raid' or after inviting a 6th person to a group and clicking the 'convert to raid' button, the group fails to be turned into a raid according to the user interface. The 6th person appears to be added to the group but cannot see anyone in their party.

**Expected behaviour:** (Tell us what should happen instead.)
After converting to raid, the user interface should update to show as a raid.

**Steps to reproduce the problem:**

1. Invite another person to your group
2. Go to the social - raid pane
3. Click 'convert to raid'

You can alternatively click 'convert to raid' by right clicking on your name

**Branch(es):** Master

**TC rev. hash/commit:**  b34904f4b5e9e2b8aecb09829edfa5578698b632

**TDB version:**  703.00

**Operating system:**  OS X El Capitan 10.11.6

**Comment by MichaelPriebe** [comment]
I'm having this issue as well. Hope it can be fixed soon.

**Comment by tkrokli** [comment]
@MichaelPriebe : please add your core revision hash to your comment so we can keep track of this.

**Comment by hoxton22** [comment]
I'm having the issue too
Rev : https://github.com/TrinityCore/TrinityCore/commit/dedf702248c4eb9a6e9d0e3203cab19b56fa4f3f
