### ISSUE TITLE
[3.3.5] Bone Spike Graveyard: impaled player disappears or falls off map

### ISSUE THREAD

**Issue by DeActiver** [TrinityCore/TrinityCore#18194]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 

~~1. With approaching player to boss for ready fight, boss automatically start fight without any attack by player ,must player start fight and combat boss , now flags_extra = 1,~~
2. Boss Lord Marrowgar :  player after free (bone_spike) disappear from map instance and if player die for (bone_spike) fall under map.

**Steps to reproduce the problem:**
1. just test ~~bosses~~ Lord Marrowgar

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) **3.3.5**

**TC rev. hash/commit:**  6214c7181dc55c1b1076c4413d8ecd09d57a3460

**TDB version:**  335.62

**Operating system:**  win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Please rewrite your issue description. In its current form it cannot be understood.

**Comment by tkrokli** [comment]
... and I have already tried to make sense of the main point in this issue.

**Comment by Aokromes** [comment]
If you mean you changed flags_extra from 1 to 2 it's obviously the boss won't agro.

**Comment by ccrs** [comment]
he doesn't like the ""new"" agressive state of bosses it seems and that bone spikes are removed after combat

**Comment by Aokromes** [comment]
well, then this looks to be a custom feature and don't belongs here, nor to say removing flag 1 is one huge unblizzlike thing.

**Comment by DeActiver** [comment]
ccrs player remove fight if die fall if live released can't see fight

**Comment by DeActiver** [comment]
Aokromes  i say 2 problem in issue , sorry for must create new issus bone_spike

**Comment by Aokromes** [comment]
write on your native language and use google translate instead your broken engrish.

**Comment by tkrokli** [comment]
... I smell some corrections to Google Translate in the future ^^

**Comment by Keader** [comment]
wtf?

**Comment by Aokromes** [comment]
keader that's why i said "your native language AND use google translate"

**Comment by jackpoz** [comment]
chances are another community member will translate it if the issue gets reported in the native language in the first place

**Comment by Aokromes** [comment]
^^ That's why it's documented:

clear title and description of the bug - if your english is very bad, please use google translate or yandex to translate to english and include one text in your native language.

**Comment by DeActiver** [comment]
Aokromes what's your mood ?
your language if is good must find , or learn language for description maybe , i don't understand you , real the description is incomplete?
I fixed it , I just wanted to report you 
If the issue is not important for you close report , instead of test friend or is important ask better cause instead of wasting time

**Comment by Keader** [comment]
@DeActiver try write it in your native language, someone should translate it xd

**Comment by Aokromes** [comment]
@DeActiver Deutsch? Буряад? Español? Português? Türkçe? Русский? پنجابی? العربية? Italiano? עברית?

**Comment by Dokman** [comment]
@DeActiver Plase not hate everyone, the community want to help you, but the community need to understand you, put your description in your language, then anyone will try to understand your language or translate it.

**Comment by tkrokli** [comment]
I agree. Please provide a full description in your native language and someone will help you translate it.

**Comment by Aokromes** [comment]
I asked him on 10 different languages to see if he answers and i got downvote xd

**Comment by DeActiver** [comment]
@Ghost-R ISSUES 2 ; no some time now always player fall under map

**Comment by DeActiver** [comment]
@Aokromes  I mind some you are selfishness, TC is your project but report bug don't need translate 10 different languages or want Overall effect on your translate . If understand priority issues if did not understand close.

So please the end your ability translate , good man if any body report you can ...
Always I like TC but now TC not is formerly TC
I try if to next post Report better say for to understand you, or better is i don't create new issue :+1: 
thank you so please end this fable.

**Comment by Aokromes** [comment]
@DeActiver we are trying to known what's your native language to see if you can write on it and someone translate it properly to english

**Comment by ccrs** [comment]
![image](https://cloud.githubusercontent.com/assets/4329612/20022918/271f790a-a2dd-11e6-9342-1b851f09f283.png)

**Comment by Keader** [comment]
Giveup Aokromes.

**Comment by Riztazz** [comment]
https://www.youtube.com/watch?v=ld2nWfIap2k

**Comment by DeActiver** [comment]
@Aokromes one of those is really trying very valuable for me has, i always figured things and ideas , and did not intend to insult , Aokromes always like Developer :100:

**Comment by MrDelta** [comment]
@Ghost-R
ISSUES 1: Boss's in ICC must not start attack player when player nearby boss, first player must attack then boss start. ## correct

ISSUES 2: Some time Bone Spike has effect on player to fall under map. ## (Alaways )

**Comment by MrDelta** [comment]
Is not it better instead of discussing...
A useful work done?
The concept understood.
More thing needs?
May very people not have the ability to speak English well. (like me :D )
Is it important?

sorry if i can not speak English well.

**Comment by Aokromes** [comment]
@MrDelta that's why we asked DeActiver to include text on native language.

**Comment by sirikfoll** [comment]
Icecrown Citadel Bosses aggro at range, not at first attack, this was implemented on #15852, so afaik Issue 1 is invalid, as it's working almost as intended, there's only a problem with the size of the aggro range, discuted in issue #17181

**Comment by Keader** [comment]
But still remain fall of the map with Bone Spike (not tested in game)

**Comment by tkrokli** [comment]
OK, as issue 1 is invalid, this issue page should change to focus on the spikes. Starting with the title.

**Comment by Killyana** [comment]
And since when we have this impaled issues, I never saw that before.

**Comment by tkrokli** [comment]
I agree, it seems unlikely, given that the OP has posted issues asking for non-blizzlike changes before.

**Comment by Keader** [comment]
I cant reproduce it on 70a867531d6c6dba13dcd56a44db855b39aa6471
works fine with clean tc/clean db, and mmaps enabled.

**Comment by Keader** [comment]
I cant reproduce it on 70a867531d6c6dba13dcd56a44db855b39aa6471
works fine with clean tc/clean db, and mmaps enabled.
