### ISSUE TITLE
[335] Forlorn Spirit (Quest) Does Not Attack

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18202]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The Forlorn Spirit (entry 2044, GUID 0) is spawned by a GO from quest [The Legend of Stalvan](http://www.wowhead.com/quest=67/deprecated-the-legend-of-stalvan) but she is spawned neutral instead of hostile.

**Current behaviour:** The NPC is spawned neutral

**Expected behaviour:** The NPC should spawn hostile

**Steps to reproduce the problem:**

1. Obtain the aforementioned quest
2. Go to the location and click on the GO
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system:**  WinXP / Win7

**Notes:**

* On retail, other parts of this [quest chain](http://wowwiki.wikia.com/wiki/The_Legend_of_Stalvan_quest_chain_(Old)) also spawn this NPC. I have not tried them in Trinity yet but I assume they'll use the same DB entry so one fix should cover them all

* Searching the repo finds an [SAI commit](https://github.com/TrinityCore/TrinityCore/issues/3690) from 2012 and a [db fix](https://github.com/TrinityCore/TrinityCore/issues/16933) for the repeatable flag but nothing mentioning this NPC.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
- http://wow.gamepedia.com/Quest:The_Legend_of_Stalvan_(2)
- http://wow.gamepedia.com/Forlorn_Spirit_(banshee)
- http://www.wowhead.com/npc=2044/forlorn-spirit

**Comment by Killyana** [comment]
As you can see here it's neutral: https://youtu.be/ScETNxgiSYA?t=1m28s

**Comment by MrSmite** [comment]
She is still supposed to attack the player

http://wowwiki.wikia.com/wiki/Forlorn_Spirit

> There is a delay when she first appears before she attacks in which you should be able to run away if you do not want to confront her.

Currently Trinity having her flagged neutral means she does not attack. I guess her script needs to be updated.

Note: I think the reason she is neutral is because you can run away from her. If she was hostile she would go after other people questing before she despawned.

Anyway, this report should be reopened and retitled: *Forlorn Spirit should be scripted to attack the player even though she's neutral*

**Comment by Killyana** [comment]
Probably start attack is called by the script.

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid`= 2044;
```
```
entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_x  target_y  target_z  target_o  comment                                             
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  --------  --------  --------  --------  ----------------------------------------------------
       2044            0       0       0          11                 0           100            1             0             0             0             0            1              0              0              0              0              0              0            1              0              0              0         0         0         0         0  Forlorn Spirit - On Respawn - Say Line 0            
       2044            0       1       0           0                 0           100            0          2000          2000          2000          2000           11           3105             32              0              0              0              0            2              0              0              0         0         0         0         0  Forlorn Spirit - In Combat - Cast 'Curse of Stalvan'
       2044            0       2       0           8                 0           100            0             0             0         45000         45000           11            118              0              0              0              0              0            7              0              0              0         0         0         0         0  Forlorn Spirit - On Spellhit - Cast 'Polymorph'     
```
Doesn't look like any start attack command in the creature's SAI.

**Comment by ZenoX92** [comment]
This should fix the issue. I also fixed spawn positions for Forlorn Spirit.
```sql
-- Forlorn Spirit
DELETE FROM `smart_scripts` WHERE `entryorguid`=2044 AND `source_type`=0 AND `id`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=204400 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2044,0,0,0,11,0,100,0,0,0,0,0,0,80,204400,2,0,0,0,0,1,0,0,0,0,0,0,0,"Forlorn Spirit - On Respawn - Run Script"),
(204400,9,0,0,0,0,100,0,3000,3000,0,0,0,49,0,0,0,0,0,0,21,50,0,0,0,0,0,0,"Forlorn Spirit - On Script - Start Attacking"),
(204400,9,1,0,0,0,100,0,0,0,0,0,0,1,0,0,0,0,0,0,21,50,0,0,0,0,0,0,"Forlorn Spirit - On Script - Say Line 0");

-- Old Footlocker
UPDATE `smart_scripts` SET `target_type`=8, `target_x`=-10951.4, `target_y`=1568.86, `target_z`=46.9779, `target_o`=3.75142 WHERE `entryorguid`=3643 AND `source_type`=1 AND `id`=0;

-- Sealed Crate
UPDATE `smart_scripts` SET `target_x`=-8841.93, `target_y`=985.171, `target_z`=98.6999, `target_o`=6.00926 WHERE `entryorguid`=1561 AND `source_type`=1 AND `id`=0;

-- Marshal Haggard's Chest
UPDATE `event_scripts` SET `delay`=0, `x`=-9553.53, `y`=-1432.44, `z`=62.2943, `o`=5.28835 WHERE `id`=264;

**Comment by illfated** [comment]
What about the actions
- `Forlorn Spirit - In Combat - Cast 'Curse of Stalvan'`
- `Forlorn Spirit - On Spellhit - Cast 'Polymorph'`

Are those actions handled elsewhere, or automatically when the NPC attacks a player?
