### ISSUE TITLE
[WIP] [7.x] Mardum - Demon Hunter Starting Area

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18204]
# **These additions are only for Legion!**

Here is my PR: #18235

**Progress:**
- [ ] Mardum Spawns
  - [x] Gameobjects
  - [x] Creatures
  - [ ] Movement
  - [ ] Phases
- [ ] Creature Related Stuff
  - [ ] Loot
  - [ ] EQ
  - [x] Auras
- [ ] Phasing
  - [ ] Conditions
  - [x] phase_area
- [ ] Scripted Content
  - [x] Trigger Scene on Start
  - [ ] Scene Scripts
  - [ ] Ingame Creature Actions
  - [ ] Scripts which need C++ Support
  - [ ] Personal Spawns (Creatures only seen by Player)
- [ ] Quest Fixes
  - [x] queststart & questender
  - [ ] Bug Fixes

Feel free to contribute.

Stuff i'm working at the moment is:

- Phasing
- Spawns
- Scene Scripts

**Comment by funjoker** [comment]
Update: Check my repo to see what i'm on atm

https://github.com/funjoker/TrinityCore/tree/demonhunter_start

**Comment by LuigiElleBalotta** [comment]
C'mon guys, come to his repo to help!

**Comment by dikkaa** [comment]
Hii @funjoker do you have any news about this PR ?
thank you for your great job !

**Comment by funjoker** [comment]
Still working on some problems atm =/.

**Comment by dikkaa** [comment]
@funjoker Ohh alright how can we help you ? (if you need help)

**Comment by funjoker** [comment]
Missing features. So need to wait until personal spawn etc is implemented

**Comment by HannibalRoG** [comment]
@funjoker Did you abandon this already?

**Comment by funjoker** [comment]
nono want to fix other things first ^^

**Comment by Pickausrname** [comment]
@funjoker Hey bro, do you have a plan to continue this? =D

**Comment by funjoker** [comment]
i have plan sure ^^ but also need to keep working on scaling and pet

**Comment by Pickausrname** [comment]
Sweet man! Meanwhile, for those of us who wants to embark on the demon hunter journey, is it possible to skip the starting zone altogether, and say, got straight to the class hall?

**Comment by funjoker** [comment]
Discontinued for now
