### ISSUE TITLE
You cannot add a language with a core function & SPELL_EFFECT_LANGUAGE is not implemented right

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#18200]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** You cannot add a language with a core function & SPELL_EFFECT_LANGUAGE is not implemented right.

**Current behaviour:**
You cannot add a language to a player with a core function, only with a spell. If the language has no spell you can't learn the language.

**Expected behaviour:** 
Should be able to add a language such as LANG_ZOMBIE to a player. This language has no spell.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Both

**TC rev. hash/commit:**  
c70edcfcead012811621203e789adc8d19ce6e69

**TDB version:**  
62
**Operating system:**  
Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Goatform** [comment]
Is this old or new issue?

**Comment by Kittnz** [comment]
@Goatform Well it's not even implemented in cmangos, so i bet an old issue. It's never really been well implemented).

**Comment by Kittnz** [comment]
Actually, it is not needed after all. All spell work perfectly.
