### ISSUE TITLE
[7.x] Auto Attack

### ISSUE THREAD

**Issue by cocolino** [TrinityCore/TrinityCore#18201]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Melee Auto Attack is bugged.

**Current behaviour:** (Tell us what happens.) Melee Autoattack is bugged and cannot be toggled. Once you go in combat with any unit it becomes "enabled" and highlighted and you cannot turn it off again by clicking on it. You can also enable it by clicking it while on an action bar and having selected the nearby unit you want to attack. The disable ("toggle off") is what doesn't work. 
As a consequence, players remain visually in a combat ready state all the time, going near a hostile unit and selecting it makes you start auto attacking it, and the only way to stop this is by re-logging. This affects not only Melee classes but also Ranged classes that use Staves etc.

**Expected behaviour:** (Tell us what should happen instead.) You should be able to enable or disable the Melee Auto Attack by clicking on the ability. When toggled off it should put you out of combat. Research shows CMSG_ATTACK_STOP and the response SMSG are correctly sent just like on retail but client-side nothing happens regarding visual ability toggle / behaviour. It does seem to stop attack swings for the current unit while you stand near it, but you start attacking any other hostile units you select.

**Steps to reproduce the problem:**

1. Drag Auto Attack from your Spell book to your action bar (spell is 6603 for Melee, which is the one that seems bugged. Tested with Wands and Bows and you can toggle it and works correctly).
2. Go near a mob you want to attack and right-click it or click the Auto Attack ability to toggle it on and start auto attacking.
3. Try to click the ability again or get out of combat by running away. The ability will not be toggled off and will remain enabled.

- As a side note: No error is displayed if you are too far from a mob when trying to auto attack it ("You are too far away!"), so that seems bugged too. The direction (orientation) error displays properly.

**Branch(es):** 7.x

**TC rev. hash/commit:**  5b8429318853f6dd34d5326dbb7418964c3203bb

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
Does this happen all the time or only when a mob moves in and out of range?

I ask because on the 3.3.5 core (#13595 #14460)it's currently broken for Hunters when a mob moves in and out of melee range, player gets stuck in auto-shot but never attacks. You have to deselect the target and reselect it to clear.

**Comment by cocolino** [comment]
This happens all the time. Initially i saw that the attack ready state was not cleared visually, and when selecting a new creature and going in attack range you start attacking it. So by dragging the auto attack on the spell bar it was clearly visible that it was active all the time (similar to what is stated in https://github.com/TrinityCore/TrinityCore/issues/14460). The new auto attack has a toggle option that only makes you stop attacking you current target when clicked and sit idle near it, but the icon is still highlighted and you still attack a newly selected target.

**Comment by cocolino** [comment]
Further research shows that, after toggling off the auto attack, dumping UnitAffectingCombat("unit") returns false for the player, and the health regen is re-enabled, plus the mid health and powers bar fades away, meaning at least partially the player is exiting combat. However, when dumping IsCurrentAction(actionSlot) with the skill bar action slot the auto attack has been dragged on to, it returns true (consistent with the visual state of the icon and relating back to CGActionBar::IsCurrentAction), meaning that something actually does fail to happen at some point, be it either missing or having changed in handling.

**Comment by Shauren** [comment]
I cannot reproduce this issue, toggling attack mode works properly as well as PLAYER_LEAVE_COMBAT ui event (its triggered by SMSG_ATTACK_STOP for current player)
