### ISSUE TITLE
[3.3.5] All of hunter's trap not working

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#18206]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
All of hunter's trap not working

**Steps to reproduce the problem:**

1.  Cast a trap spell, put a trap at the foot of a mob.
2.  You can find trap despawned and nothing happens.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2e457b3be418ce75b0e0ca901e84ebcdaf02ad18

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  Win10 64bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. 2e457b3be418 2016-11-05 01:52:38 -0300 (3.3.5 branch) (Win64, Release, Static) TDB 335.62

I can confirm this, as well as observing that most of the time, the trap visuals were often missing for me.

**Comment by shenhuyong** [comment]
Now I found revert commit b3a4815067d154fb35da87aa8e7365995d6f65f5 can fix this problem.
