### ISSUE TITLE
[3.3.5] Walk and Run speed reduction for 2 Stillpine NPCs

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18207]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
2 NPCs running to fast for the Quests
- http://www.wowhead.com/npc=17379/stillpine-ancestor-akida
- http://www.wowhead.com/npc=17391/stillpine-ancestor-coo

**Suggested fix:**
- Bug and Fix: Thanks to Grz3s for Sniff Data
- Stillpine Ancestor Akida runs too fast. Run Speed reduced.
- Stillpine Ancestor Coo walks too fast. Walk Speed reduced.

``` sql
-- Stillpine Ancestor Akida & Stillpine Ancestor Coo
UPDATE `creature_template` SET `speed_run`= 0.9 WHERE `entry` = 17379;
UPDATE `creature_template` SET `speed_walk` = 1 WHERE `entry` = 17391;
```

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:** TrinityCore rev. 2e457b3be418 2016-11-05 01:52:38 -0300 (335 branch)

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql

**Operating system:**  Win7 64Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
speed comes from sniffs.

**Comment by Tauriella** [comment]
Grz3s use only Sniff Datas
