### ISSUE TITLE
[3.3.5] Quest: Scarlet Diversions (5096)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18205]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** You can't use the Scourge Banner. 
- http://www.wowhead.com/quest=5096/scarlet-diversions
- https://www.youtube.com/watch?v=_9jV2sj97m4

**Steps to reproduce the problem:**

1. `.go 1876 -1325 60 0`
2. `.quest add 5096`
3. `.additem 12814`

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. 2e457b3be418 2016-11-05 01:52:38 -0300 (335 branch)

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:** Win7 64Bit 

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by dr-j** [comment]
because the spellfocus has negative respawn time

**Comment by Tauriella** [comment]
Is this a DB Bug or Core Bug?

**Comment by offl** [comment]
DB. Try this:
```
UPDATE `gameobject` SET `spawntimesecs`=180 WHERE `id`=176088;
```

**Comment by Tauriella** [comment]
Yep It works perfect :+1: 
Thank You

**Comment by offl** [comment]
Also looks like object 'Drop-Off Point' too shouldn't have negative respawn time.
(Used as a spellfocus for [Bag of Gold](http://www.wowhead.com/item=21041/bag-of-gold). Quest [Decoy!](http://www.wowhead.com/quest=8606/decoy))

If someone can confirm that [Bag of Gold](http://www.wowhead.com/item=21041/bag-of-gold) can't be used:
```
UPDATE `gameobject` SET `spawntimesecs`= 150 WHERE `id`= 180659;
```

**Comment by Tauriella** [comment]
Can any Dev's please pushed in the Git please ?

**Comment by Tauriella** [comment]
Thanks @tkrokli
