### ISSUE TITLE
[3.3.5] Frost Armor procs when sapped.

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18216]
**Description:** Sapping a mage with frost armor causes it to proc. It is probably not only Frost Armor that causes stealth to break

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Your not supposed to be hit by frost armor as a rogue when sapping.

**Steps to reproduce the problem:**

1. Frost armor on mage
2. Sap the mage in stealth as a rogue.

Image verification: http://puu.sh/sarWO/6a0863cbdc.jpg

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/51bd38a93bfa3d0c44d407142e94cdc7cb18e330

**TDB version:**  TDB 335.62	62

**Operating system:**  Ubuntu 14.04

**Comment by Persephone** [comment]
@ariel-  sorry for spamming with all these issues :P

**Comment by ccrs** [comment]
dont be sorry, if it wasnt for you, these issues would go unnoticed.
If something, keep up the work :)
