### ISSUE TITLE
[3.3.5] Proc infinite loop

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#18217]
**Description:**
In some situations, some spells trigger an infinite amount of procs.

**Current behaviour:** 
Following the change allowing SPELL_AURA_PROC_TRIGGER_SPELL and SPELL_AURA_PROC_TRIGGER_DAMAGE to always trigger, we end up with infinite (or semi infinite) loops.
For example, 57351 procs on pretty much everything with a proc rate of 50%, we end up with the aura procing on its spell proc.
Other spells get trickier, as they trigger a spell, which triggers an other one, which triggers back the original spell (it is the case for 59353 for example).

**Expected behaviour:** 
It should not freeze, I guess those procs should disable further procs somehow, maybe all have an internal cooldown of 1 ms or so to ensure it never gets proc again in the same loop.

**Steps to reproduce the problem:**

1. Have http://woehead.way-of-elendil.fr/?item=42989 equipped
2. Hit stuff
3. You should notice some micro freezes

It is possible to reproduce zith other spells, but difficult to pin down the exact situation. The following partial crash log (had to cut it down, was 10 megabytes) should describe one of the situations

https://gist.github.com/joshwhedon/19d2d282eeca9cc988ea8e17f15b92a2

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5 (not aware of other branches)

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/ed49626c22e7bfb731aac1d6b5607e12ec851d5a

**TDB version:**  
Irrelevant

**Operating system:**  
Irrelevant

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
summoning @ariel-
