### ISSUE TITLE
Core/Scripts: Forge of Souls, Bronjahm

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18212]
**Description:**

**Current behaviour:** Tell us what happens
- Bronjahm doesn't teleport into the middle
- The orb has wrong path

**Expected behaviour:** Tell us what should happen instead
- Bronjahm should teleport into the middle
- The orb should go to the heart of Bronjahm

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  ee52ba690d1b6fcd71b68f49264617a0c12ca9ac

**TDB version:**  335.62

**Operating system:**  Debian 8.x

**Comment by Keader** [comment]
About Devour Souls, already have issue about it : #17968

**Comment by tkrokli** [comment]
OK, I will edit this to only be about Bronjahm so people can comment about Devourer of Souls in https://github.com/TrinityCore/TrinityCore/issues/17968

**Comment by ccrs** [comment]
two different issues in one report

**Comment by tkrokli** [comment]
OK, so you want this issue split up in 2 for the current content as well?

**Comment by sirikfoll** [comment]
Fix for "Bronjahm doesn't teleport into the middle":
```diff
diff --git a/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp b/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp
index 6bc6f7a..0accd72 100644
--- a/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp
+++ b/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp
@@ -115,6 +115,7 @@ class boss_bronjahm : public CreatureScript
                 if (events.IsInPhase(PHASE_1) && !HealthAbovePct(30))
                 {
                     events.SetPhase(PHASE_2);
+                    me->InterruptNonMeleeSpells(true);
                     DoCast(me, SPELL_TELEPORT);
                     events.ScheduleEvent(EVENT_FEAR, urand(12000, 16000), 0, PHASE_2);
                     events.ScheduleEvent(EVENT_SOULSTORM, 100, 0, PHASE_2);

```
Not sure about what exactly is the other problem, "The orb has wrong path"

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Killyana** [comment]
Teleport issue fixed, the second issue is not valid for me, I don't see how the orb can go to the chest of the npc, it must just follow him and once the contact distance is reached the boss regen and the orb despawns, tested and works correctly.
