### ISSUE TITLE
Client tried to call not implemented method ResourcesService.GetContentHandle

### ISSUE THREAD

**Issue by mazdafil** [TrinityCore/TrinityCore#18213]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The crash of the server when creating any character

**Current behaviour:** Crash when creating any character

**Expected behaviour:** Create a character and enter the game

**Steps to reproduce the problem:**

1. Run bnetserver and wordserver
2. Run the actual client and create a character
3. The client disconnects from the server, and the server fails with the message Client tried to call a not implemented method ResourcesService.GetContentHandle

**Branch(es):** master

**TC rev. hash/commit:**  TrinityCore revision   : b01820704846+ 2016-11-07 00:11:04 +0100 (master branch)

**TDB version:**  TDB 703.00

**Operating system:** Ubuntu 14.04. LTS

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keldo** [comment]
Try patching to fcbb439 , and try again. I cant reproduce this at that revision

**Comment by tkrokli** [comment]
Crash reports should also include (linked) debug crash log for tracing of the actual cause of the issue.

**Comment by Shauren** [comment]
>Client tried to call not implemented method ResourcesService.GetContentHandle
This log is expected and not critical. Your issue lies somewhere else which is why crash logs are so impotant.

**Comment by Shauren** [comment]
Also I can guess your crash was somewhere in AchievementMgr that was already fixed

**Comment by Dirket** [comment]
@mazdafil I have the same problem，how did you solve it，thanks
