### ISSUE TITLE
[3.3.5a][master] cherry-pick BoundingIntervalHierarchy from CMaNGOS

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18214]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** typo in Vmap BoundingIntervalHierarchy generation
Due to this typo, some objects could be left out during BIH generation and thus never checked for intersection. This breaks height and LoS calculations in some areas.

https://github.com/cmangos/mangos-classic/pull/215

File name & path in TC: https://github.com/TrinityCore/TrinityCore/blob/master/src/common/Collision/BoundingIntervalHierarchy.cpp

**Current behaviour:** Height and LoS calculation breaks in some areas.

**Expected behaviour:** LoS and Height calculation should not break, NPCs should behave normally.

**Steps to reproduce the problem:**
The occurrence of this bug can be seen in "Md_Mushroomcave.wmo". It can be found in several locations, for example (-6140, -2960, 400), map 0. In some parts of the cave mobs will either fall through the ground or fly up into the sky when chasing the player. LoS is not obstructed there as well.

**Branch(es):** 3.3.5 **and** master

**Comment by Killyana** [comment]
Fixes: https://github.com/TrinityCore/TrinityCore/issues/9753

**Comment by jackpoz** [comment]
As usual refactor changes should be left out from commits that affect code functionality so only https://github.com/cmangos/mangos-classic/pull/215/commits/f68416c9a13da4d116ce38ed1d6b3173f4021976 should be tested and merged

**Comment by Aokromes** [comment]
@jackpoz this needs vmaps re-extraction? if yes then maybe we need to increase vmaps version no?

**Comment by Kittnz** [comment]
Any testing been done with this commit?
