### ISSUE TITLE
Cannot Complete Quest, Deactivate An'Owyn

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18210]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** This quest cannot be completed
http://www.wowhead.com/quest=9169/deactivate-anowyn

**Current behaviour:** (Tell us what happens.) This quest starts and begins with Magister Sylastor in Tranquillien, clicking Continue produces nothing
http://www.wowhead.com/npc=16237/magister-sylastor

**Expected behaviour:** (Tell us what should happen instead.) Clicking Continue should Complete the Quest

**Steps to reproduce the problem:**

1. Accept the quest from Magister Sylastor
2. Kill until you find the Crystal Controlling Orb, Deactivate the Nigh Elf Moon
3. Return to Magister Sylastor to complete the quest

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  9d88e78

**TDB version:**  7.0.3

**Operating system:**  Debian 8 x64

**TEST TO CONFIRM** http://www.trinitywow.org/register  create an account, set portal to logon.trinitywow.org, create a blood elf, run the area until you get to the proper level or let me know in game what you are doing so I can level you up, run the quest, watch it fail.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
This looks to be a generic bug, don't open more and  edit #18209

**Comment by Keldo** [comment]
Recommended fix:
```
UPDATE `quest_template` 
SET `RewardChoiceItemID1` = '23400', `RewardChoiceItemQuantity1` = '1', `RewardChoiceItemID2` = '23401', `RewardChoiceItemQuantity2` = '1' 
WHERE `quest_template`.`ID` = 9169; ```

Per Sniff: 22950_2016-11-06_12-25-33-Keldo.pkt
