### ISSUE TITLE
Cannot Complete Quest 28762

### ISSUE THREAD

**Issue by mazdafil** [TrinityCore/TrinityCore#18223]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Cannot Complete Quest 28762 Beating Them Back!

http://www.wowhead.com/quest=28762/beating-them-back
Level: 3
Requires level 1
Loremaster: Yes
Side: Alliance
Race:  Draenei
Class:  Paladin
Start: Marshal McBride
End: Marshal McBride
Not sharable
Difficulty: 1  6  8
Added in patch 4.0.3.13277

**Current behaviour:** Cannot Complete Quest 28762 - when you click on the finish button, nothing happens, the window does not close the quest, quest is not completed.

**Expected behaviour:** Complete the current quest and get a new quest.

**Steps to reproduce the problem:**

1. Get the quest from Marshal McBride
2. Kill 6 worgs of the Blackrock clan
3. Return to Marshal McBride

**Branch(es):** master

**TC rev. hash/commit:**  TrinityCore revision : fcbb439+ 2016-11-09 00:11:04 +0100 (master branch)

**TDB version:**  TDB 703.00

**Operating system:**  Ubuntu 14.04.LTS

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keldo** [comment]
[master] DB/Quest: Complete Quest button inactive, reward info missing #18209

**Comment by mazdafil** [comment]
But this quest does not require the шеуьы it requires to kill mobs. As it is now called in the required fields and in what table? Before the structure was completely different.

**Comment by Keldo** [comment]
Wow has changed quite a bit from 3.3.5->6->7...

**Comment by mazdafil** [comment]
Once there were fields RequiredNpcOrGo in table crteature_template - where now?

**Comment by Keldo** [comment]
trying to figure this out myself, I know in the issues I had, I had to update SQL

**Comment by mazdafil** [comment]
https://trinitycore.atlassian.net/wiki/display/tc/quest_objectives It's what we need - tell us only who ever the field values of the Flags and Flags2

**Comment by mazdafil** [comment]
Found description the new structure in the file QuestDef.h

**Comment by AndralJu** [comment]
Have the same problem : 

Guid: GUID Full: 0x200004000000314000000000000005C7 Type: Creature Entry: 197 Low: 40 - No quest greeting found.Error in CMSG_QUESTGIVER_CHOOSE_REWARD: player testwar (GUID Full: 0x08000400000000000000000000003C9B Type: Player Entry: 0 Low: 50) tried to get reward item (Item Entry: 57255) wich is not a reward for quest 28762 (possible packet-hacking detected)

**Comment by mazdafil** [comment]
Packet hacking detected? Maybe you need to disable anti-cheat in worldserver.conf. Unfortunately, there is no chance to test tonight I will try I will unsubscribe.

**Comment by Keldo** [comment]
this has nothing to do with anti-cheat, the damn reward item is missing the quest_template table. I linked my previous issue, if you cant go read then don't post issues.

**Comment by AndralJu** [comment]
so this is not a problem in my core ?? @Keldo

**Comment by Keldo** [comment]
No, if you go look in the quest_template table and query the Quest ID in question you will see the RewardItemID and RewardItemChoiceID Fields are all set at 0, which will trigger the error above in the server log and will cause the Quest Dialog to be non responsive when you attempt to complete the quest. This is all focused around DB Issues. There are some code issues but it will take a team of people to fix the issue at hand as I am sure its happening in every zone.

**Comment by madcatmk2** [comment]
@Keldo is it possible for players to contribute the quest rewards (in the template) somewhere so that it may be checked into the main repository?

I.e. I just encountered the issue where I cannot complete the [Gold Dust Exchange](http://www.wowhead.com/quest=47/gold-dust-exchange) quest, hence I went into the database and updated the SQL myself with the quest reward item ID and quantity.

**Comment by tkrokli** [comment]
The difficulty causing this issue is that in the current retail Blizzard servers & in the game client, quest rewards are handled differently from what it used to be during Warlords of Draenor and earlier. The DB reward tables are no longer supposed to contain the item info, it is supposed to be read directly from the DBC or DB2 files instead. More research into DB2 info handling is needed.

**Comment by madcatmk2** [comment]
Ah, but I realize that the quest is giving the right rewards, so for my own use I can just put something inside the DB table to satisfy the if condition to get quests to finish?

**Comment by tkrokli** [comment]
What you do in your own DB is up to you. We don't decide that. On the other hand, if you want to contribute to TrinityCore, you need to use straight TC source & DB content to provide correct info in comments.

**Comment by Keldo** [comment]
I have personally fixed alot of quest on my test server that were having these kind of issues and with @tkrokli 's help, some of the edits have been checked in...

Always remember to DELETE FROM then INSERT as UPDATE does not always produce desired results.

**Comment by Aokromes** [comment]
We only delete+insert when a lot of data needs to be changed.

**Comment by Edreisantafe** [comment]
Before the this commits 2c5474e319da0a24b704c1a3521be4876d7a4da3 a few missions reported by me with this same type of error in the console were solved, mysteriously this one not, however it has the same error in console than the others.
