### ISSUE TITLE
[3.3.5] GMs kicked from raid when server restart

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18228]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** When you restart server with GM on, when server back, sometimes you are kicked from instance.

**Current behaviour:** You are kiked from instances when server restart.

**Expected behaviour:** You stay inside of instance.

**Steps to reproduce the problem:**

1.  Put a character with some instance.
2. Restart server.
3.  If you stay in instance, repeat steps 1 and 2.

This commit should fix it: https://github.com/TrinityCore/TrinityCore/commit/9573ec52f0ea2fbda0fdcac1bd9ed2617d359338. But sometimes fail and show message in console:

> Player::LoadFromDB: Player 'Keader' (GUID Full: 0x0000000000000001 Type: Player Low: 1) Map: 631, X: -59.841766, Y: 2210.268555, Z: 27.902609, O: 3.149650. Areatrigger not found.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  70a867531d6c6dba13dcd56a44db855b39aa6471

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
Does the instance still exist when you enter after a server restart ? it could be the instance gets deleted.
Please try with an instance lock (kill any boss) too

**Comment by Keader** [comment]
Yes, looks like works if i binded with instance (if i kill some boss).
I did 5 times, and works in 5 times xd

**Comment by jackpoz** [comment]
Then you probably get kicked out because the instance doesn't exist anymore

**Comment by Keader** [comment]
so... this is correct behavior? or instance should not deleted if have "players inside"?

**Comment by jackpoz** [comment]
It sounds like the correct behavior, especially since there are no players inside (on restart there are no players online at all).

**Comment by Keader** [comment]
so issue can be closed? xd

**Comment by Keader** [comment]
Binded with instance, sometimes still get kicked.
but if i binded dont show any error message in console

**Comment by Keader** [comment]
With character binded dont work anymore
closing issue :)

**Comment by tkrokli** [comment]
I presume you mean "with character bound to instance, this issue does not happen any more"
(only commenting in case someone would misunderstand your closing comment).

**Comment by sirikfoll** [comment]
https://gist.github.com/sirikfoll/ee3569e9195435fddb88cd491bf01921
If anyone want's, this patch fixes it, GameMasters, with .gm on or .gm off, won't be kicked out of instances(even after server restart and without instance lock), and will also be able to enter raids without a raid group

**Comment by Keader** [comment]
Just for references: dc86a8e5db549300f7cb7b2243654c105013f929
