### ISSUE TITLE
Quest not available in game, available in the DB

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18221]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Quest are **NOT** available in Game, yet **ARE** in the database

**Current behaviour:**  No Quest is offered

**Expected behaviour:** Quest Should be offered

**Steps to reproduce the problem:**

**EXAMPLE**

1. Find the Dying Blood Elf  http://www.wowhead.com/npc=16601/dying-blood-elf
2. If it were available, accept Anok'suten http://www.wowhead.com/quest=9315/anoksuten
3.  Since it's not available, it cannot be completed, if it were, complete the Quest and turn it into Arcanist Vandril http://www.wowhead.com/npc=16197/arcanist-vandril

**Branch(es):** 7.1.0 / master

**TC rev. hash/commit:**  fcbb439 

**TDB version:**  7.0.3

**Operating system:**  Debian 8 x64

Since no one wants to answer on IRC or tell me how to attempt to fix this, I'm putting it here on the Issues. I know its not core but it will eventually need to get fixed, that is my intent and purpose here.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lorac2k14** [comment]
did you check the disables to see if it is in there? or maybe check core db error log if something is not right it will be disabled by default in some cases

**Comment by Keldo** [comment]
On this particular quest (9315) QuestType is 2 which means "Quest is enabled (does not auto-complete)." 
```sql
SELECT * FROM `quest_template` WHERE ID = 9315 
```

**Comment by tkrokli** [comment]
TrinityCore rev. a999c29a80eb 2016-11-12 00:44:49 +0100 (master branch) (Win64, Release, Static) / TDB 703.00

I am not sure exactly how this affects the quest, this is what I found specific to quest 9315:
`Quest 9315 has RewardFactionValueId1 = 100000. That is outside the range of valid values (-9 to 9).`

When searching for quest IDs in the log, make sure to add a space before & after the ID if ID < 10 000.

There are:
- 1061 error lines starting with `Quest ` mentioning `RewardFactionValueId1`
- 1101 error lines starting with `Quest ` saying "That is outside the range of valid values (-9 to 9)."
- an additional 4942 lines ending in `quest can't be done.` (but not including the error message above)
- a total of 8061 error lines starting with "Quest xxxxx has ..." in `DBErrors.log`.

By checking `DBErrors.log` you will find that there are 78 624 errors to be solved in various ways.

**Comment by Keldo** [comment]
Some how my source got crossed with 335 so I'm rebuilding to attempt to fix, if all is good, I will dig into this further.

**Comment by Keldo** [comment]
I'm wondering if this has been sniffed in WDB cause VerifiedBuild is 22908 but most others are 0. all in all Im not getting why this quest is not present. Its sort of mind boggeling

**Comment by DDuarte** [comment]
Test after 0f7b9c67f35f2d61446aebbcef48497afb321651

**Comment by Keldo** [comment]
No changes, Quest are still Not available

**Comment by Keldo** [comment]
http://www.trinitywow.org/?page=roadmap
To get an Idea of what I have found so far

**Comment by Keldo** [comment]
Even after running
```sql
DELETE FROM `creature_queststarter` WHERE `id` IN (16197);
DELETE FROM `creature_questender` WHERE `id` IN (16197);

INSERT INTO `creature_queststarter` VALUES
(16197, 9488), -- Arcanist Vandril, A Simple Robe
(16197, 9487), -- Arcanist Vandril, Arcane Reavers
(16197, 9139), -- Arcanist Vandril, Goldenmist Village
(16197, 9138), -- Arcanist Vandril, Suncrown Village
(16197, 9327), -- Arcanist Vandril, The Forsaken
(16197, 9329), -- Arcanist Vandril, The Forsaken
(16197, 9140); -- Arcanist Vandril, Windrunner Village

INSERT INTO `creature_questender` VALUES
(16197, 9488), -- Arcanist Vandril, A Simple Robe
(16197, 9315), -- Arcanist Vandril, Anok'suten
(16197, 9487), -- Arcanist Vandril, Arcane Reavers
(16197, 9148), -- Arcanist Vandril, Delivery to Tranquillien
(16197, 9139), -- Arcanist Vandril, Goldenmist Village
(16197, 9758), -- Arcanist Vandril, Return to Arcanist Vandril
(16197, 9138), -- Arcanist Vandril, Suncrown Village
(16197, 28560), -- Arcanist Vandril, Warchief's Command: Ghostlands!
(16197, 9140); -- Arcanist Vandril, Windrunner Village
```

and restarting the server completely, did not fix this

**Comment by nubqt** [comment]
**Forensics:** this is similar to what is happening with #20849. In essence, the TDB establishes incorrectly that the breadcrumb quest [Warchief's Command: Ghostlands!](http://www.wowhead.com/quest=28560) is required in order to get the quests [The Forsake](http://www.wowhead.com/quest=9327/the-forsaken) and [The Forsaken](http://www.wowhead.com/quest=9329/the-forsaken) (same quest name but with different id). This was hardcoded incorrectly in `quest_template_addon`:

```sql
SELECT * FROM `quest_template_addon` WHERE `id` IN ( '9327', '9329' );
```

This will show you that both quests have 'PrevQuestID' set as '28560' (the Warchief's Command quest).

To fix the issue you must do two things:

1. Set 'PrevQuestID' to '0' for both records.
2. Ensure that the Player cannot get the quest 'Warchief's Command: Ghostlands!' if he has already completed either of 'The Forsaken' quests.

Hope this helps!

#ps: please change the name of this ticket to 'Arcanist Vandril won't give the quest 'The Forsaken' unless Player has quest 'Warchief's Command: Ghostlands!'

#pss: @Keldo: I suggest you create a ticket for each quest giving you a problem and tag me in a reply so that I can look into each of them further.

**Comment by nubqt** [comment]
@Keldo: I just posted the solution to #20849 which is similar to the issue you reported it. Have a look. I think you should be able to tweak the solution provided there to fix the issue reported here. The difference might be in the field 'PrevQuestID' which is the one needed here while the other issue used the field 'NextQuestID'. Hope this helps!

**Comment by nubqt** [comment]
**Forensics:** a prerequisite for the quest reported in this ticket ('Anok'suten') prevented Players from ever starting the chain that ultimately leads to that quest. This solution removes the requisites for those quests ('The Forsaken' obtained from the Warchief's Command Board or from an NPC). Once the Player completes either of 'The Forsaken' quests, 'Anok'suten' becomes available without having to do any other modifications in the TDB (ie: that part is working-as-intended).

**Suggested fix:**

```sql
-- Defining quests to modify
SET @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS := 28560;
SET @QUEST_THE_FORSAKEN_FROM_NPC := 9327;
SET @QUEST_THE_FORSAKEN_FROM_WCB := 9329;

-- Removing unnecessary requirement. Player should be able to get the quests
--   @QUEST_THE_FORSAKEN_FROM_NPC and
--   @QUEST_THE_FORSAKEN_FROM_WCB
-- without having to complete
--   @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS
-- beforehand.
SET @NONE := 0;
UPDATE `quest_template` SET `RewardNextQuest` = @NONE WHERE `id` = @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS;
UPDATE `quest_template_addon` SET `PrevQuestId` = @NONE WHERE `id` IN ( @QUEST_THE_FORSAKEN_FROM_NPC, @QUEST_THE_FORSAKEN_FROM_WCB );

-- But the Player should NOT be able to get the quest
--   @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS
-- if he has already completed
--   @QUEST_THE_FORSAKEN_FROM_NPC or
--   @QUEST_THE_FORSAKEN_FROM_WCB
SET @MAKE_QUEST_AVAILABLE_TO_PLAYER := 19;
SET @IF_PLAYER_HAS_BEEN_REWARDED_QUEST := 8;
SET @NEGATE_CONDITION := 1;
SET @COMMENT := 'Makes quest available if-and-only-if Player has not completed another quest beforehand';
INSERT INTO `conditions` VALUES ( @MAKE_QUEST_AVAILABLE_TO_PLAYER, 0, @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS, 0, 0, @IF_PLAYER_HAS_BEEN_REWARDED_QUEST, 0, @QUEST_THE_FORSAKEN_FROM_NPC, 0, 0, @NEGATE_CONDITION, 0, 0, '', @COMMENT );
INSERT INTO `conditions` VALUES ( @MAKE_QUEST_AVAILABLE_TO_PLAYER, 0, @QUEST_WARCHIEFS_COMMAND_GHOSTLANDS, 0, 0, @IF_PLAYER_HAS_BEEN_REWARDED_QUEST, 0, @QUEST_THE_FORSAKEN_FROM_WCB, 0, 0, @NEGATE_CONDITION, 0, 0, '', @COMMENT );
```

<img width="1378" alt="screen shot 2017-11-15 at 12 20 22 pm" src="https://user-images.githubusercontent.com/33535711/32850797-3ab6e114-ca01-11e7-8254-6bc26b00e4fe.png">

<img width="1378" alt="screen shot 2017-11-15 at 12 24 37 pm" src="https://user-images.githubusercontent.com/33535711/32850820-4c37a892-ca01-11e7-82cc-cd64cc602a37.png">

**Comment by tkrokli** [comment]
👍 Nice usage of `SET @QUEST_NAME := value;` and visualization of documentation within the code. 😃
