### ISSUE TITLE
Core/Spells: Magic rooster.

### ISSUE THREAD

**Issue by delro92** [TrinityCore/TrinityCore#1822]
TrinityCore Hash: bdc75eb856cd+ (Win64, Release (little-endian))
TDB: Rev 40+ all updates
problem: If you mount the magic rooster and then while on it mount it again, the mount dissapears but you keep the 100% speed buff. At least with Male Taurens (will do more testing)
Item 49290
##

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6414e456ec60cd33460ecda4582f8e035198be28

**Comment by TideWoW** [comment]
Still got the bug with the newest commit 622c3c18859e11cb7fb4714fae662f44ae399111
