### ISSUE TITLE
There is no starting chain quests Pandaren

### ISSUE THREAD

**Issue by mazdafil** [TrinityCore/TrinityCore#18224]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** There is no starting chain quests Pandaren

**Current behaviour:** There is no starting chain quests Pandaren.

**Expected behaviour:** (In the starting area of the Pandaren none of the quest

**Steps to reproduce the problem:**

1. In the starting area of the Pandaren none of the quest

**Branch(es):** master

**TC rev. hash/commit:**  TrinityCore revision : fcbb439+ 2016-11-09 00:11:04 +0100 (master branch)

**TDB version:**  TDB 703.00

**Operating system:**  Ubuntu 14.04 LTS

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#17021
