### ISSUE TITLE
[3.3.5] movement Boss Twin Valkyr

### ISSUE THREAD

**Issue by DeActiver** [TrinityCore/TrinityCore#18222]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Bosses move on the ground , The boss should movement fly up ground 6.0f always in the zone , So field "HoverHeight" have problem . 
for example boss mimiron : head

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  51bd38a93bfa3d0c44d407142e94cdc7cb18e330

**TDB version:**  62

**Operating system:**  win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#15177
