### ISSUE TITLE
DB/Vendor: Darnassus Quartermaster - no dialog

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18238]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The Darnassus Quartermaster had no dialog as it's Entry was missing in the npc_vendors table

**Current behaviour:** When you click on Moon Princess Lasara, The Darnassus Quartermaster, you do not get a dialog

**Expected behaviour:** Typical Vendor Dialog should appear

**Steps to reproduce the problem:**

1. Travel to Darnassus and find the Flight Point
2. Click on Moon Princess Lasara (Darnassus Quartermaster) http://www.wowhead.com/npc=50305/moon-priestess-lasara
3. NO DIALOG

**Branch(es):** 7.1.0 / master

**TC rev. hash/commit:**  54376e0

**TDB version:**  7.0.3

**Operating system:**  Debian 8 x64

**Suggested fix:**
```sql
DELETE FROM `npc_vendor` WHERE `entry`=50305 AND `slot` IN (1,2,3,4,5);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(50305, 1, 67526, 0, 0, 0, 1, 0, 0, 0), -- Darnassian Satchel
(50305, 2, 64886, 0, 0, 0, 1, 0, 0, 0), -- Shroud of Darnassus
(50305, 3, 64887, 0, 0, 0, 1, 0, 0, 0), -- Cape of Darnassus
(50305, 4, 64888, 0, 0, 0, 1, 0, 0, 0), -- Mantle of Darnassus
(50305, 5, 45579, 0, 0, 0, 1, 0, 0, 0); -- Darnassus Tabard
```
Tested in-game, I got the NPC vendor dialog to work with the proper items in the appropriate slots.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
you can use ```sql  xd

**Comment by Keldo** [comment]
@keader thanks, and fixed

**Comment by tkrokli** [comment]
I have taken the liberty to add a `DELETE FROM` line to your SQL query.

Please notice that the `DELETE FROM` statement needs to be included to make the SQL repeatable. Usually you can include extra delimiters besides the NPC entry to make the query specific to the inserts.
