### ISSUE TITLE
[3.3.5/7.x] Aura 71736 should be applied for friendly npc in radius.

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#18233]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Aura 71736 should be applied for friendly NPC in radius.

Maybe need set Effect 0: Id 35 (SPELL_EFFECT_APPLY_AREA_AURA_PARTY) on Effect 0: Id 128 (SPELL_EFFECT_APPLY_AREA_AURA_FRIEND) 
In SpellMgr.cpp? If set - aura working and applied for friendly NPC too.

**Current behaviour:** (Tell us what happens.)
Aura 71736 applied for player only.

**Expected behaviour:** (Tell us what should happen instead.)
Aura 71736 should be applied for friendly npc in radius. Player not have this aura.
Aura used by http://www.wowhead.com/npc=37595/darkfallen-blood-knight - WARNING: THIS IS NPC.

**Steps to reproduce the problem:**

1. If you player and have player in radius spell. Used Aura 71736 and see, what aura apply for all player in radius. But player at blizzlike not have this aura. Aura used by npc (creature)
2. .go creature id 37595 and combat start.
3. NPC used aura on self (SAI script), but aura not share on friendly NPC in radius.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
7.x, but aura from Wotlk and can cause problem on 3.3.5a.

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/48f5c11355b8ca5b451366ca76c875b36b4b3b17

**TDB version:**  https://github.com/TrinityCore/TrinityCore/releases/tag/TDB703.00

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Ulduar** [comment]
I'll remember, how add issue in MangosR2, analogic problem.
Rsa solved problem (working)
You can look on this:https://github.com/mangosR2/mangos/commit/0115d0a788af8304cb399e2ff6c6e05ba33ca5bc

**Comment by Unknown-1000** [comment]
Hmm, okay. But i will add in SpellMgr.cpp. Thanks for link.

**Comment by Ulduar** [comment]
Very well.

**Comment by ariel-** [comment]
The problem are the functions Unit::IsInRaidWith, Unit::IsInPartyWith. they have checks for the case player/player, player/creature and creature/player but not for creature/creature.

Since these functions are called when filling aura targets map by grid searchers, the functions always return false if the caster of aura is a creature and the potential target is a creature too, then other creatures never get the aura applied.

**Comment by ariel-** [comment]
I'm leaving the issue open because, even if the aura targetting is fixed, these npc's still need to be scripted.

**Comment by ariel-** [comment]
Why close? Issue still valid.

**Comment by offl** [comment]
He closed all his issues and pull requests before the account deletion.
Or all his issues and pull requests were closed after the account deletion.
Look at github main page.

**Comment by offl** [comment]
Can't reproduce in aba0704
