### ISSUE TITLE
[3.3.5] Quest Issue: Triage - Hammerfall

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18236]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Patients in triage cannot be treated. Proper quest item not appearing in inventory.

**Current behaviour:** On accepting the Triage quest (Quest 6622), I can accept the quest just fine, however the required item (Triage Bandage Item 16991) does not appear in my inventory. Patients appear on the mat for me to heal but even my personal bandages do not work. Manually adding the item however causes the quest to behave normally.

**Expected behaviour:** Item (16991) Triage Bandage should be added to inventory on quest acceptance.

**Steps to reproduce the problem:**

1. Get to Hammerfall however you want.
2. Find Doctor Gregory Victor and accept quest.
3. Observe inventory missing item when you accept quest Triage.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  6a471755231e

**TDB version:**  3.3.5

**Operating system:**  Win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. ed2cd6b34f84 2016-11-10 23:00:58 +0100 (3.3.5 branch) (Win64, Release, Static) / TDB 335.62

Cannot confirm, works as intended for me. Used GM character (`.gm off`) to level up + skills + teleport.

![2016-11-12 2](https://cloud.githubusercontent.com/assets/4903600/20235742/696a3c3c-a89b-11e6-83ba-d51a4c4ffe80.png)

**Comment by tkrokli** [comment]
TC rev. hash/commit: 6a47175 is waaay too old, from 2014. We definitely don't support such old core/DB.
