### ISSUE TITLE
[3.3.5][Crash] MotionMaster::~MotionMaster

### ISSUE THREAD

**Issue by sucklifex** [TrinityCore/TrinityCore#18237]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** http://paste.ubuntu.com/23462220/

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  51bd38a93bfa3d0c44d407142e94cdc7cb18e330

**TDB version:**  62

**Operating system:**  Debian 8.x

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
All the code related to MotionMaster changed on fe68b2e99851a888c5182d7bebddfea67459afd3 i will close all tickets related to MotionMaster on 3d unless someone supplies new crashes on a build after fe68b2e99851a888c5182d7bebddfea67459afd3
