### ISSUE TITLE
[CRASH] in BIH::intersectPoint

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#18230]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Crash in BIH::intersectPoint

**Current behaviour**: Tell us what happens
Not sure why is this happening. 8 Crash after update to master.

- http://pastebin.com/4Ze5Zs26
- http://pastebin.com/3NfHAMW8
- http://pastebin.com/EWYX7r4L
...

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
51bd38a93bfa3d0c44d407142e94cdc7cb18e330

**TDB version**:  
62

**Operating system**:  
Linux x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Dup #18217

Always update core before crash reports. Compile on debug to get a proper crashlog.
