### ISSUE TITLE
[master] characters do not receive in-game mail

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18239]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Two characters have received mail from NPCs in game.
Upon checking the Mailbox, no mail appears.

**Current behaviour:** Client is not pulling mail into a user's mailbox.

**Expected behaviour:** Mail should be in the user's mailbox.

**Steps to reproduce the problem:**

1. See that you have received mail
2. Go to a mailbox
3. No mail appears

**Branch(es):** 7.1.0 / master

**TC rev. hash/commit:**  a999c29

**TDB version:**  7.0.3

**Operating system:**  Debian 8 x64

Last known working status was with the 6.x builds.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Edreisantafe** [comment]
Still buged on master a858b5fe29e5
TDB version 7.0.3
Operating System Windows 10

**Comment by joschiwald** [comment]
still not implemented

**Comment by Keldo** [comment]
Guys, once an issue is tagged, please refrain from posting "still bugged", we know this and it is or it will be worked on...  Once it has been resolved, the issue will be closed. Thus, you will know that it has been resolved.
