### ISSUE TITLE
Serious Issue

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#18244]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Level 80 Guards do not spawn when a player of the opposing faction comes into close range of a NPC or City/Camp.
**Current behaviour:** (Tell us what happens.)
https://youtu.be/10rK4yIYrnc
**Expected behaviour:** (Tell us what should happen instead.)
https://www.youtube.com/watch?v=WKO1kDxOmXo
**Steps to reproduce the problem:**

1.  Check every horde and alliance city and check every NPC (apart from critters like rabits,cockroaches and rats.)
2.  Find a fix to this.
3.  null

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  #14938

**TDB version:**  3.3.5a

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
1. This is not a serious issue, it is a low priority issue (or even a cosmetic one), if it is an issue at all.
2. You have not stated which branch this issue affects.
3. You have not stated what your core revision hash is, which makes your issue invalid until corrected.

**Comment by LewisPotato** [comment]
It is a serious issue, a group could easily pillage a city and constantly kill quest NPC's and other types. Also I'll fix this now, where do I find my core revision hash? And I thought 3.3.5a is the branch?

**Comment by tkrokli** [comment]
There are 2 branches: [`master`](https://github.com/TrinityCore/TrinityCore/tree/master) (main branch/retail) and [`3.3.5`](https://github.com/TrinityCore/TrinityCore/tree/3.3.5) - Wrath of the Lich King 3.3.5a.

TC core revision hash is found on the first and last lines in your Worldserver console (and in Server.log).

BTW, I have never heard about guards spawning if you attack NPCs which are not guards.

**Comment by LewisPotato** [comment]
Did you not watch the video where I get close to a NPC and a guard spawns? ..... -_-

**Comment by tkrokli** [comment]
Yes, I thought it was from someone's private "funserver" with custom scripts.

**Comment by LewisPotato** [comment]
Oh, and no it's 100% blizzlike.

**Comment by tkrokli** [comment]
BTW, you linked Appled's Pull Request
[**Scripts/TrialOfTheChampion: Rescripting whole dungeon [WIP]**](https://github.com/TrinityCore/TrinityCore/pull/14938) #14938
instead of posting a valid TrinityCore rev. hash.

**Comment by LewisPotato** [comment]
What?.. Did I? o.o

**Comment by LewisPotato** [comment]
I'm getting so confused, one minute...

**Comment by LewisPotato** [comment]
Going to make a fresh one with the correct information.

- Issue Closed

**Comment by Aokromes** [comment]
anyway, issue don't followed rules, and:
https://github.com/TrinityCore/TrinityCore/issues/11563

**Comment by tkrokli** [comment]
@LewisPotato : Please notice that your issue is a duplicate, feel free to post updated & valid info in #11563.

**Comment by Treeston** [comment]
> It is a serious issue, a group could easily pillage a city and constantly kill quest NPC's and other types

For future reference, we consider issues "serious" if they affect server stability (crashes) or allow players to easily gain significant advantage (for example, if you found a way to respawn a boss).
