### ISSUE TITLE
3.3.5 Branch - DeathKnight quest Eye of Archerus cant use any spell

### ISSUE THREAD

**Issue by bengelbaer** [TrinityCore/TrinityCore#18248]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
DeathKnight quest Eye of Archerus - cant activate any of the spells
**Current behaviour:** (Tell us what happens.)
If i want to aktivate a spell it says: 
that does not work while her charms since

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. Start the Quest works correctly
2. Automatic Fly to the town works fine
3. after i get the controll i cant shot any spell

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
0805766d8b07
**TDB version:**  
335.62_2016_10_17 
**Operating system:**  
Debian 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by fr4z3n** [comment]
It is a global issue with using spells in a vehicle.
since rewrite of the immunity system
@ariel-

**Comment by Aokromes** [comment]
there is no such rev on trinitycore repository.

**Comment by bahajan95** [comment]
the spell works correctly I just did, merge compiler and everything is fine

**Comment by Keader** [comment]
maybe related with: https://github.com/TrinityCore/TrinityCore/commit/352c84943c4495631a5dd1e9285cde35fdc23c37#commitcomment-19809960?

**Comment by bengelbaer** [comment]
Ok but what can i do to fix this?

**Comment by Keader** [comment]
if caused by ariel, he will fix it :)

**Comment by ccrs** [comment]
confirmed a7259cef4f3a12e7a547259b694709e430c4b7bd, "Cant do it while charmed" error
