### ISSUE TITLE
gameobject commands not working

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#18241]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The gameobject commands dont seem to be working properly together.
The gameobject target gives links that contain the gameobject DB guid.
Because of the new guid changes .gps command however searches with the ingame guid (So a gameobject that has DB guid X will have ingame guid Y which has a dynamically generated guid counter).

I guess the root causes here are that there are two guids and both are needed by the commands.
Also some commands need the entry for which there is a completely another link type.
It would be probably nice to have something like `|color|Hgameobject:entry:dbguid:ingameguid|h[name]|h|r` so one link can be used for everything and it would work/not work depending on if the info needed is available in the link.

Also .gob add command does not work for some reason. The gameobjects dont save up in DB.

**Current behaviour:**
Gameobject link from .gob tar gives DB guids. However .gps command uses core generated guids to search. The error message says player not found and should say gameobject not found.
The .gob add command does not save gameobjects to DB.

**Expected behaviour:**
Gameobject link from .gob tar should probably contain the ingame guid as well. The gps command needs to know the ingame guid to search properly (uniquely identify the gameobject) It also needs the DB guid or gameobject entry to make the guid to search with.
The error message should vary depending on what arguments were provided. For example when giving a gameobject link, it should say that no gameobject was found.
The spawned gameobjects should save to db.

**Steps to reproduce the problem:**

1. Try spawning a gameobject with .gob add 35
2. See that it is there
3. Try target it with .gob target and see that it fails to target the gameobject
4. See the gameobject table in DB and see that there are no spawns there.
5. Restart the server and go to where you spawned the object and see that it isnt there.
6. Conclusion: No gameobjects are saved and they cannot be targeted. Targeting fails because it searches the objects from DB where they dont exist.
1. Go to an existing gameobject.
2. Use .gob target on it and it should succeed because it is in DB
3. Use .gps <link of the gameobject>
4. See that it fails and the error message incorrectly says "Cannot find player"
5. Conclusion: the gps command cannot be used on the object links (even though it is intended to)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  ed2cd6b34f849f9cc9adb86318457155e47f7314

**TDB version:**  62

**Operating system:**  windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by el-druida** [comment]
eh?

**Comment by Freggar** [comment]
**TC rev.** [`08057b6d8b07`](https://github.com/TrinityCore/TrinityCore/commit/08057b6d8b076eb62d65b68fb613858d8c3b5cbd) (Branch 3.3.5a)

You stated three issues.

Issue 1: 
> `.gob add 35` doesn't add Gameobject to the Database.

Can't reproduce this issue on clean TC/DB build.

Issue 2:
> See that it fails and the error message incorrectly says "Cannot find player"

[Just a general error message, don't see much of a problem here (Note that `.gps` can also be used for players)](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_misc.cpp#L166)

Issue 3:
> Conclusion: the gps command cannot be used on the object links (even though it is intended to)

Can confirm, although it's stated that [shift-link can be used](https://trinitycore.atlassian.net/wiki/display/tc/GM+Commands), it fails on GOB links.

**Comment by Rochet2** [comment]
> Can't reproduce this issue on clean TC/DB build.

I had clean TC and DB which was just created. I believe either the compilation process had some issues or the DB had some issues. I tested 100 commits back and spawning worked fine even though no related code has changed that I can see.. Not sure why it didnt work, but probably something I wont be able to reproduce - not that I tried just now.

> Just a general error message, don't see much of a problem here (Note that .gps can also be used for players)

Its not a general error message and that is the problem.
Rather have more descriptive error or more general error than something that tells you it didnt find a completely different entity than what you were telling it to look for. "I want the location of this object" -> "Couldnt find the player" -> "??"

**Comment by tkrokli** [comment]
Maybe I have misunderstood this issue quite a lot, but just to have mentioned a couple of things:
I usually use the command `.gobject near` to get gameobject coordinates, while using `.gps` for my character or creatures I want to check for wrong spawn points. Not sure about the relevance to your issue.

I also wonder: did **ariel-**'s commit https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686 ([**Core/Scripts: Convert spells to new proc system**](https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686)) make any relevant changes that could affect this issue at all?

**Comment by Rochet2** [comment]
> Maybe I have misunderstood this issue quite a lot

`.gob target` creates a gameobject link that is not usable with `.gps` even though it should be / has been - This is the issue, if it was unclear.

> I usually use the command .gobject near to get gameobject coordinates, while using .gps for my character or creatures I want to check for wrong spawn points. Not sure about the relevance to your issue.

It is relevant in such a way that all gameobject links have the same issue - and .gob near outputs gameobject links. However there are two types of gameobject links. Ones that contain the guid and ones that contain the entry. Not sure which kind of links .gob near outputs as the documentation doesnt say and I cannot test at the moment, but this is more about the guid links rather than entry links because entry has not been supposed to be used to uniquely define a gameobject which is needed to do a .gps on a gameobject.

But if you were suggesting to use .gob near instead of .gps it is not possible, because .gps gives more information which is needed like ground and floor coordinates.

> I also wonder: did ariel-'s commit 2ff8550 (Core/Scripts: Convert spells to new proc system) make any relevant changes that could affect this issue at all?

Doesnt look like it did. All the affected files are in scripts folder and none of them were to `cs_*` files. Also the SQL looks like it changed tables and rows unrelated to this. - Not that I tested after that commit.

**Comment by Aokromes** [comment]
80cf4e3
