### ISSUE TITLE
World Server DB Issue

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18242]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** World Server failing to start, see SQL Error on this Issue

**Current behaviour:** SQL Error on Startup

**Expected behaviour:** worldserver should start

**Steps to reproduce the problem:**

1. git pull origin master
2. restart or start worldserver
3. fail

**Branch(es):** 7.1.0 / master

**TC rev. hash/commit:**  a999c29 

**TDB version:**  703

**Operating system:**  Debian 8 x64

```sql
In mysql_stmt_prepare() id: 37, sql: "SELECT casterGuid, itemGuid, spell, effectMask, recalculateMask, stackCount, maxDuration, remainTime, remainCharges, castItemLevel FROM character_aura WHERE guid = ?"
Unknown column 'itemGuid' in 'field list'
In mysql_stmt_prepare() id: 200, sql: "INSERT INTO character_aura (guid, casterGuid, itemGuid, spell, effectMask, recalculateMask, stackCount, maxDuration, remainTime, remainCharges, castItemLevel) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'itemGuid' in 'field list'
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
you are mixing 3.3.5a and master characters databases.

**Comment by Keldo** [comment]
Quick to assume, as usual. I don't even have a 335 database on that server

**Comment by Aokromes** [comment]
then you mixed 3.3.5a and master cores. because master removes the column you lack.

**Comment by tkrokli** [comment]
Anyway, that error message does not appear on straight master core + TDB 703.00 + updates.
- TrinityCore rev. a999c29a80eb 2016-11-12 00:44:49 +0100 (master branch) (Win64, Release, Static)

The only odd DB message that I could find is this (both during normal startup and after a full DB rebuild):
`Using World DB: Unknown world database.`
