### ISSUE TITLE
[335] AHBot Buyer Conflict With Neutral and TwoSide Interaction CONF

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18243]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

The following CONF combination does not work:

*AuctionHouseBot.Buyer.Neutral.Enabled = 0*
*AllowTwoSide.Interaction.Auction = 1*

**Current behaviour:**

With the above settings, the AHBot will buy auctions listed by the player in the Neutral AH (Gadgetzan)

**Expected behaviour:**

The AHBot should ignore Neutral AH auctions, regardless of the "sided" option if the Neutral buyer is disabled.

**Steps to reproduce the problem:**

1. Set the above CONF options
2. Post an auction in the neutral AH (Gadgetzan)
3. Wait and the bot will buy your auction

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + Updates

**Operating system:**  Windows

**Notes:**

The following CONF combination does work:

*AuctionHouseBot.Buyer.Neutral.Enabled = 0*
*AllowTwoSide.Interaction.Auction = 0*

with the above options, the bot correctly ignores Neutral auctions.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
It's obvius, AllowTwoSide.Interaction.Auction  makes all auctions neutral.

**Comment by MrSmite** [comment]
> It's obvious, AllowTwoSide.Interaction.Auction makes all auctions neutral.

Right which is the conflict.

TwoSidedInteraction should handle auctions in a different manner so that the Neutral house can be exempt from the bot while allowing alliance / horde houses to continue to work properly.

Perhaps have TwoSided just search between alliance / horde / neutral when building the list?

**Comment by jackpoz** [comment]
> because the bot buys everything

isn't this a matter of lowering bot buying chances ?

**Comment by MrSmite** [comment]
> isn't this a matter of lowering bot buying chances ?

Not necessarily. Because all two-sided auctions are "neutral", you can't distinguish between the factions so it would essentially be less likely to buy any auction, even those placed in a faction house and not just the ones listed in Gadgetzan.

The current implementation of two-sided is actually redundant in that context because all auctions in Gadgetzan can be purchased by both factions even without two-sided activated. The only thing two-sided does is allow you to post auctions from any city instead of traveling to Gadgetzan.

A better implementation (if possible) would be that if two-sided is active then when a player in Stormwind searches for an item, it pulls results from Horde, Alliance and (optionally) Neutral, displays them and lets them buy or bid.

This would also be more compatible with the AHBot config to not buy from Neutral. With this type of implementation for two-sided, you could do the following:

* Enable two-sided
* Disable AHBot neutral buyer
* Configure AHBot to place 500,000 items in the Alliance house (or Horde if you choose)
* Players from Horde (or Alliance) faction would still see those auctions on a search
* Enable AHBot Buyer for Alliance / Horde
* Players who post in their faction house would still have those auctions purchased by the bot but they could exchange items across faction at the Neutral house without worrying about the bot interfering.

**Comment by Jinnaix** [comment]
So by reading this, your issue is more related to the general way the crossfaction auctionhouse works, instead of having an issue with the AH buyers function.

Enabling the two-sided auctionhouse intentionally kills the alliance and the horde auctionhouse.

```cpp
AuctionHouseObject* AuctionHouseMgr::GetAuctionsMap(uint32 factionTemplateId)
{
    if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION))
        return &mNeutralAuctions;
```
```cpp
AuctionHouseObject* AuctionHouseMgr::GetAuctionsMapByHouseId(uint8 auctionHouseId)
{
    if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_AUCTION))
        return &mNeutralAuctions;
```

So having AllowTwoSide.Interaction.Auction = 1, no matter where you are, you will always get the neutral AH when interacting with it. This also goes for item listings - every item listed while having this setting enabled is listed in the neutral AH. This also applies the listing fee and %-cut from neutral values.

I would suggest opening a new issue as a feature suggestion.

**Comment by MrSmite** [comment]
> So by reading this, your issue is more related to the general way the crossfaction auctionhouse works, instead of having an issue with the AH buyers function.

No, it is with the AHBot buying auctions from the neutral AH with the CONF option disabled.

In 3.3.5, the only way to transfer items between Horde and Alliance was the neutral AH in Gadgetzan. With AHBot, you could enable "two sided auctions" to essentially combine Horde / Alliance into one but this should still respect the CONF option regarding the neutral AH.

It isn't a new feature because it already exists but is handled wrong (bug). If I enable two-sided but disable neutral then the bot should only look at items marked alliance or horde, not neutral. Any item posted in gadgetzan should be listed as neutral and neither alliance or horde. This allows anyone to view / buy from gadgetzan but still makes them invisible to the bot, as per CONF options.

**Comment by Jinnaix** [comment]
>then the bot should only look at items marked alliance or horde, not neutral.

See, this is where the problem starts.
Im gonna repeat myself, but - AllowTwoSide.Interaction.Auction = 1 kills all identifications that you point on.
And thats not the AH-Bots problem.

Look at the following table:

auctionhouse
---
| id | houseid | itemguid | itemowner | buyoutprice | time | buyguid | lastbid | startbid | deposit | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | 
| 1 | 7 | 114 | 2 | 0 | 1598775033 | 0 | 0 | 4654 | 4654 | 
| 2 | 7 | 115 | 2 | 5555 | 1598775073 | 0 | 0 | 5555 | 4654 | 
| 3 | 7 | 126 | 6 | 0 | 1598775136 | 0 | 0 | 4654 | 4654 | 

The first item was posted in Stormwind, the second item was posted in Gadgetzan and the third item was posted in Orgrimmar.

Neither you, or the bot has an option in the current setup to identify the origin of one of these auctions out of this table alone.
Where i agree with you, is, that with AuctionHouseBot.Buyer.Neutral.Enabled = 0  the bot shouldnt touch these auctions (he does) but this would end into no ahbot-buyer at all. Still, the problems origin is the way two side interaction works and this setting has nothing to do with the bot.

**Comment by MrSmite** [comment]
> Still, the problems origin is the way two side interaction works and this setting has nothing to do with the bot.

Right which is the bug. And there's actually a secondary bug too in that if the user disables the setting after having it enabled, everything ends up in one house.

When the setting is enabled, the original houseid isn't recorded so then disabling the setting results in all existing auctions being listed in houseid=7 and the other houses being empty.

Instead of this, the two-sided-auction setting (when enabled) should simply load all Alliance / Horde houses (and ignore neutral if set) and allow the player to purchase anything in the list. This would not only allow AHBot to function properly but also allow the CONF setting to be toggled on/off without creating empty auctionhouses.

**Comment by jackpoz** [comment]
As Jinnai showed at https://github.com/TrinityCore/TrinityCore/issues/18243#issuecomment-682047349 , AllowTwoSide.Interaction.Auction kills Alliance and Horde AH and redirects them to Neutral one, meaning the 3 options AuctionHouseBot.Buyer.FACTION.Enabled actually end up being the single option AuctionHouseBot.Buyer.Enabled .

It makes no sense to try supported AH faction settings when there are no AH factions anymore due to AllowTwoSide.Interaction.Auction .

The proper way to handle AllowTwoSide.Interaction.Auction = 1 is to disable all AHBot settings with faction Alliance and Horde and enable (as needed) the Neutral ones.

I'll add a log warning about this.

**Comment by MrSmite** [comment]
> 
> 
> As Jinnai showed at [#18243 (comment)](https://github.com/TrinityCore/TrinityCore/issues/18243#issuecomment-682047349) , AllowTwoSide.Interaction.Auction kills Alliance and Horde AH and redirects them to Neutral one, meaning the 3 options AuctionHouseBot.Buyer.FACTION.Enabled actually end up being the single option AuctionHouseBot.Buyer.Enabled .
> 
> It makes no sense to try supported AH faction settings when there are no AH factions anymore due to AllowTwoSide.Interaction.Auction .
> 
> The proper way to handle AllowTwoSide.Interaction.Auction = 1 is to disable all AHBot settings with faction Alliance and Horde and enable (as needed) the Neutral ones.
> 
> I'll add a log warning about this.

I know how the bot works but I was bug reporting the implementation. The proper implementation would be to place auctions as normal (eg: alliance/horde/neutral) but build the list for the player to include all three houses if the setting is enabled.

```C++

// pseudocode

// gather auction list for player based on settings
if (AllowTwoSide)
   sql = "SELECT * FROM Auctionhouse";
else
   sql = "SELECT * FROM Auctionhouse where houseID = " + id;

//display auction list to player

```

This way when the server admin disables two sided, the auctions stay in their respective houses instead of all ending up in the neutral house with alliance / horde being empty.
