### ISSUE TITLE
Spell: Spell casted by object traps 

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18256]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** When a gameobject activate a trap that cast a spell, the cast fails if the player is not too close to the gob.

**Steps to reproduce the problem:**

1. Take the quest http://www.wowhead.com/quest=10861/veil-lithic-preemptive-strike
2. .go obj 9677
3. click the egg
4. If you're not on top of the egg the spell will fail and nothing will be summoned
5. If you're on top of the egg a bird will be summoned

If I'm not wrong a range check is not required in this case as the spell is casted by the gob without a target:
https://woehead.way-of-elendil.fr/?spell=38854
https://woehead.way-of-elendil.fr/?spell=38865
objects:
https://woehead.way-of-elendil.fr/?object=185211
https://woehead.way-of-elendil.fr/?object=185208

https://woehead.way-of-elendil.fr/?object=185210
https://woehead.way-of-elendil.fr/?object=185212
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
More spell range issues
