### ISSUE TITLE
[3.3.5] Spell/Priest: Vampiric Embrace not work propertly with Mind Flay

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18250]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Vampiric Embrace (with 2 ponts in Improved Vampiric Embrace) A 25% of single-target Shadow spell damage caused by casting priest heals the priest and 5% heals the group. Mind Flay inflicts shadow damage correctly but no heal the priest or the group.

**Current behaviour:** 
The priest and the group are not healed when the priest cast Mind Flay affected by Vampiric Embrace.

**Expected behaviour:** 
The priest and the group should be healed when the priest cast Mind Flay affected by Vampiric Embrace.

**Steps to reproduce the problem:**
1. With a Shadow Priest use Vampiric Embrace.
2. Applay Mind Flay to a target.
3. The priest receives no healing.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  674ac56

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates.

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Same problem with triggered spells...

Try:

```sql
UPDATE `spell_proc` SET `AttributesMask`=`AttributesMask`|0x2 WHERE `SpellId`=15286;
```

and then `.reload spell_proc` on console/gm command

**Comment by noryad** [comment]
Perfect, now it works ok. Thank you.

**Comment by noryad** [comment]
Vampiric Embrace is incomplete because it does not work correctly with Mind Sear. The Vampiric Embrace buff specifies: x% of **single-target** Shadow spell damage caused by casting priest heals the prist and x% heals the group. The damage of Mind Sear is around the target so it should not heal, the problem is that it is healing by the damage done to each enemy around the target. Please tell me if this is enough or a new issue is required.
