### ISSUE TITLE
[master] Personal Spawning (Invisibility) (50$ bounty)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18254]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** On Retail there are some personalized events (cosmetics, dialogs).
This means only one player can see the NPCs or GOs for these events. For other players, these NPCs and GOs are invisible.
(Example: Mardum Starting Area, Sevis Brightflame at the Gates)

**Current behaviour:** NYI.

**Expected behaviour:** Method to set a player as only seer for temp spawns should be implemented.

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** master 

**TC rev. hash/commit:**  7624c7cd95fda9f0406fa8b00d8f9febe42ba820

**TDB version:**  703.00

**Operating system:**  Win 10

**Comment by streetrat** [comment]
those are probably scenes, not temp spawns

**Comment by funjoker** [comment]
Nope

**Comment by Aokromes** [comment]
For example, on suramar, the world quest to follow one spy, you can see the spy, all the other mobs, other players, and only you see your spy, other players see their own spy.

**Comment by Ovahlord** [comment]
Same goes for the arcane guardians that gives players the starting questline for legion pre-event

**Comment by Shocker** [comment]
@Aokromes that still sounds like scenes
@funjoker why are you so sure those aren't scenes?

**Comment by funjoker** [comment]
I've spent a lot of time into scenes and how they are working. 
https://github.com/TrinityCore/TrinityCore/issues/17858

Sniffs also don't show scenes related to this NPC.
Also checked SceneScripts of there is something about Sevis.

Also there are double spawns at this place (1 original, 1 personal)

**Comment by funjoker** [comment]
And on retail at the begining when accepting 40077 you can attack the appearing spawn demon.

**Comment by nerv234** [comment]
And for example when dk spawns after ending of starting cinematic(or maybe there is some areatrigger) the npc's (demonhunters) spawning and start to glide to the positions of their doublespawns without wings. This is (90% sure) to be personal not scene.

**Comment by funjoker** [comment]
nope... this is a scene nerv234 xD

**Comment by Krudor** [comment]
Would some new data for creature_template be enough to support an implementation for this, or are there more complex conditions required to make it work?
A boolean or something similiar indicating whether or not it is a personal spawn, and a field containing entry id's to point to another creature_template entry that we use to display to other players.
http://www.wowhead.com/npc=90309/exarch-yrel is a player spawned creature. She shows up as http://www.wowhead.com/npc=91911/draenei-vindicator for all other players than the summoner and should probably be part of the same core functionality.

**Comment by funjoker** [comment]
template would be wrong way. Because the temp spawns are the same IDs like the usual once. It's kinda like a clone

**Comment by funjoker** [comment]
The creatures i mean are totaly invisible and not exhancged by another creature for other players.
Maybe it's the same functionality donno =/

**Comment by Krudor** [comment]
It is just a feature that should be implemented alongside personal spawns.

**Comment by Ulduar** [comment]
@Krudor about Yrel:
Escape from Shaz'gul
http://ru.wowhead.com/quest=33081#english-comments
Yrel also look like vindicator.
    UNIT_FIELD_LOOKS_LIKE_CREATURE_ID                      = OBJECT_END + 0x0C6, // Size: 1, Flags: PUBLIC
Or
    UNIT_FIELD_STATE_WORLD_EFFECT_ID                       = OBJECT_END + 0x0C0, // Size: 4, Flags: DYNAMIC, URGENT
That one of these two should be responsible for it.

**Comment by funjoker** [comment]
50$ Bounty added
