### ISSUE TITLE
[3.3.5] Spell/Hunter: Traps are always visible to enemies

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18251]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The hunter traps are always visible and should not, this makes it very easy to avoid the traps. Enemies can only see traps up to 10 yards away, in this case it is very likely that the enemy will fall into the trap. Only rogues with Detect Traps can see traps easily.

**Current behaviour:** 
Hunter's traps are always visible.

**Expected behaviour:** 
Enemies can only see traps 10 yards or less away.

**Steps to reproduce the problem:**
1. With a hunter use any trap.
2. Any enemy can see the trap from afar.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  674ac56

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
I don't have this visibility problem. Are you sure you're testing with `.gm off`?

**Comment by noryad** [comment]
Yes I am sure, i tested without gm (gmlevel = 0) and the traps still visible. I propose to use the following addon https://www.wowace.com/media/files/449/124/RangeDisplay-r311.zip to help us to solve this problem. This addon (Range Display) shows the distance between a player and his target. Now with this tool you can verify that the enemy can see all the traps of the hunter to more than 10 yards.

**Comment by ariel-** [comment]
The problem: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L286

Traps are given a fixed stealth value of 70. That makes them easier to detect at levels greater than 14 (detection is 5 * level)

They should at least inherit owner level (ie 400 stealth at level 80)

**Comment by noryad** [comment]
I tested it with this modification 
m_stealth.AddValue(STEALTH_TRAP, 400); 
and it works ok.

**Comment by Noryad** [comment]
Confirmed in b049caf

**Comment by Noryad** [comment]
How can i access to caster's level on method https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L178 to write the correct formula?
