### ISSUE TITLE
Cannot extract data and map files from the 7.1.0.22996 client

### ISSUE THREAD

**Issue by jkrdelluser03** [TrinityCore/TrinityCore#18257]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:*I correctly compiled the project pulled from the repository of master, and copied all of the extract tools from the bin directory. Then I execute the mapextractor.exe as usual, but surprisingly it is found that the extractor cannot identify the data files located at .\World of Warcraft\Data. In fact, there are't any .mpq file in the Data directory at all!*

**Current behaviour:*The mapextractor.exe cannot read the files in Data directory any more.* 
**Expected behaviour:*Hopefully, the mapextractor.exe can read and extract the data files from the 7.1.0.22996 client.* 

**Steps to reproduce the problem:**

1. Download the TrinityCore-master.zip, extract all the files into a source directory
2. Convert the source files using the latest CMake into a VS 2015 project and correctly compile it.
3. Copy all of the extract tools into the World of Warcraft directory, and run the mapextractor.exe after which the extractor report that it cannot find the data files.

**Branch(es): master 
**TC rev. hash/commit:*7624c7cd95fda9f0406fa8b00d8f9febe42ba820*  

**TDB version:*703.00_2016_10_17*  

**Operating system:*Windows 8.1*  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by funjoker** [comment]
No valid rev. hash/commit

**Comment by jkrdelluser03** [comment]
Execuse me, where can I find the valid rev. hash/commit. I'm a freshman.

**Comment by funjoker** [comment]
Example: click on the commit when you cloned repo:

Link:
`https://github.com/TrinityCore/TrinityCore/commit/7624c7cd95fda9f0406fa8b00d8f9febe42ba820`
---------------------------------------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

7624c7cd95fda9f0406fa8b00d8f9febe42ba820

**Comment by funjoker** [comment]
I can't reproduce your issue.
For me the extractor is extracting fine.

**Comment by jkrdelluser03** [comment]
Thanks. The TC rev. hash/commit is 7624c7cd95fda9f0406fa8b00d8f9febe42ba820.

**Comment by funjoker** [comment]
You using 100% downloaded retail client ?

**Comment by jkrdelluser03** [comment]
Yes. Maybe I should not update my client today.

**Comment by funjoker** [comment]
Well..
Still working for me issue must be somewhere at you.

**Comment by jkrdelluser03** [comment]
Thanks anyway.
