### ISSUE TITLE
[master]  Dying in Valley of Trials sends you to graveyard in Northern Barrens

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#18253]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
 If you die in Valley of Trials, you end up to Northern Barrens' spirit healer

**Current behaviour:**
If you die in Valley of Trials, you end up to Northern Barrens' spirit healer

**Expected behaviour:** (Tell us what should happen instead.)
You should end up to Valley of Trials' spirit healer

**Steps to reproduce the problem:**

1. Die in Valley of Trials 
2. Release Spirit
3. 

**Branch(es):** master

**TC rev. hash/commit:**  d2d653835d0b

**TDB version:**  7.03

**Operating system:**  Debian 8.6 

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Maibenrai** [comment]
Just noticed this on the server console:
`Table `game_graveyard_zone` incomplete: Zone 6451 Team 67 does not have a linked graveyard.`

**Comment by funjoker** [comment]
Fix:

INSERT INTO `graveyard_zone` (`ID`, `GhostZone`, `Faction`, `Comment`) VALUES ('709', '6451', '67', 'Durotar, Valley of Trials');

**Comment by Maibenrai** [comment]
I just tested and it worked :)

**Comment by Maibenrai** [comment]
`mysql> select * from graveyard_zone where ID=709;
+-----+-----------+---------+----------------------------------------+
| ID  | GhostZone | Faction | Comment                                |
+-----+-----------+---------+----------------------------------------+
| 709 |      6145 |      67 | Durotar, Valley of Trials GY - Durotar |
| 709 |      6451 |      67 | Durotar, Valley of Trials              |
+-----+-----------+---------+----------------------------------------+
2 rows in set (0.00 sec)

mysql>`

Should all graveyards have/not have "GY" for sake of consistency?

I guess SQL should be like this according to https://trinitycore.atlassian.net/wiki/display/tc/SQL+Guidelines
`
DELETE FROM `graveyard_zone` `ID`=709 AND `GhostZone`=6451;
INSERT INTO `graveyard_zone` (`ID`, `GhostZone`, `Faction`, `Comment`) VALUES
(709, 6451, 67, 'Durotar, Valley of Trials');
`

**Comment by funjoker** [comment]
Well data might change due to patches.
The Comment is just an extra info.

**Comment by Edreisantafe** [comment]
This still happens in e70e0a42baf0+ TDB 7.0.3+updates

**Comment by Aokromes** [comment]
There is no such rev on trinitycore repo.

**Comment by Edreisantafe** [comment]
Sorry my bad, is this

Hash de Commit:	b8ef8466a91a55d42a395bf71ce005ae9ef02ebd

**Comment by Maibenrai** [comment]
Works here. Just tried. 
https://streamable.com/ab3v

**Comment by Edreisantafe** [comment]
Yes, work from that commit
