### ISSUE TITLE
SPELL_ATTR3_DISABLE_PROC is not handled correctly

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#18269]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** SPELL_ATTR3_DISABLE_PROC currently disables ALL the procs for the spells triggered by the aura which has this attribute.

**Current behaviour:** Paladin seals for example do not proc anything when they proc, while they should.

**Expected behaviour:** For example http://www.wowhead.com/item=50706/tiny-abomination-in-a-jar should proc from seal procs. Instead of disabling all procs, the attribute should disable all the procs for this aura (to avoid infinite loop of the seal procing its own aura). The spell scripts should also not cast the seal procs as triggered, but instead cast them as triggered without the disable proc flag.

**Steps to reproduce the problem:**

1. Login as a paladin with Seal of Corruption / Vengeance / Righteousness
2. Equip the tiny abomination
3. Hit stuff. You are supposed to sometime get 2 or 3 stacks at a time.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/503259e6fe0a1e6328090a5a2e88832b6a017516

**TDB version:**  
https://github.com/TrinityCore/TrinityCore/commit/503259e6fe0a1e6328090a5a2e88832b6a017516

**Operating system:**  
Not relevant

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
> For anyone wondering why certain classes want this more:
> It is not the 50% weapon swing's damage that people are after, but the ability of that extra swing to proc things such as poisons, and seals.

> RavenMagus on 2010/05/02 (Patch 3.3.3)
> I'm not sure why the post above was downrated. The comment was not about poisons proccing the trinket, but rather the reverse: the trinket's free melee hit activating seals and poisons off of that one hit (which does seem to be the case).

It's not seals that proc TaiaJ, it's the reverse; TaiaJ swings proc seals.

See https://github.com/TrinityCore/TrinityCore/commit/bb8763534ebff5422bf202e69add065a132e49ac#commitcomment-19794899 when you said the same.

**Comment by joshwhedon** [comment]
I raised it because all the sources I have found tend to prove you wrong on this one. For example: http://www.mmo-champion.com/threads/688878-Tiny-Abomination-in-a-Jar-test-results-w-pic
"While running tests, I found that many of our abilities can proc a mote. Judgement, DS, CS, auto, and seal damage can all grant a mote."
I fixed it and tried it on my side, but this sounds like an actual issue you may want to investigate.

**Comment by ariel-** [comment]
Certainly the implementation is the same as before (https://github.com/TrinityCore/TrinityCore/blob/1b89211c7425cb03042483c6463814c4b5adc783/src/server/game/Entities/Unit/Unit.cpp#L13936-L13938)

The same link also says

> Did your rogue friend get any procs from poisons ? I think that been fixed. Read it somewhere.
When I say procs I mean procs, the damage is the full stack of procs.
> We were chatting in vent at the time and he mentioned that the Manifest Anger damage was proc'ing poisons but his poisons were not proc'ing motes. 


The problem with mindlessly enabling procs on triggered spells is that it can provoke an endless triggerchain. I'll recheck this particular case against the old proc system and see if anything changed with its handling.

**Comment by joshwhedon** [comment]
I totally agree with you, this is something we need to be very careful about.
For the poisons, the reason is simple: poisons are not melee attacks, they are magical attacks, therefore they wouldn't proc the abo anyway.
For the endless trigger chain, I know there is a risk (I had raised the bug about it earlier), but in this case, the proc for the Seal aura should get disabled, therefore keeping the seal from procing again from any of its procs (and I think it is what the attribute is there for).
You also say it was working this way in the old proc, and seeing the old code it should have, but I think it wasn't at all, because my players started complaining about this bug after merging the change (and my players have the very bad habit to be very annoying with bugs they consider as a disadvantage :D, so they would probably not have missed it).
Also, doing some dps tests, it making multiple procs is consistant with the 4% dps it should generate.
Please note I am not trying to fight with you on that, I am very happy with the whole refactoring you made (even if it took me 3 weeks to fix all the problems with custom stuff :D). As I said I made the change on my side, it has been up for 2 days with about 250 players with no infinite loop. I just prefer giving feedback on important mechanics like that.

**Comment by ariel-** [comment]
Confirmed. Old proc system procs both on melee swing and seal damage

**Comment by joshwhedon** [comment]
If you are interrested, the way I fixed it was by two things:
- Changing the triggered flag from the seal script
- Adding a setCantProc / canProc on the aura itself, and setting it / checking it when the attribute was there:

SpellInfo const* spellInfo = aurApp->GetBase()->GetSpellInfo();
        if (spellInfo->HasAttribute(SPELL_ATTR3_DISABLE_PROC))
            aurApp->SetCantProc(true);

        aurApp->GetBase()->TriggerProcOnEvent(procEffectMask, aurApp, eventInfo);

        if (spellInfo->HasAttribute(SPELL_ATTR3_DISABLE_PROC))
            aurApp->SetCantProc(false);

Not sure you want to fix it this way, but it worked for me with not apparent issue.

**Comment by ariel-** [comment]
Spells cast with at least one trigger flag set are considered "triggered" for the effects of proc checks.

Shouldn't be necessary to change the seal script, since seal damage spells have SPELL_ATTR4_CAN_CAST_WHILE_CASTING, and that automatically sets some triggerFlags on the Spell constructor.

I'll debug the old behaviour and find out why it's now not working

**Comment by joshwhedon** [comment]
OK didn't see that. However seals in the script are casted as fully triggered at the moment (so even if the spell has that attribute, all the trigger flags are already in place)/

**Comment by ariel-** [comment]
Oh, well at least that's true for Seal of Corruption/Vengeance script

**Comment by ariel-** [comment]
Found the culprit: https://github.com/TrinityCore/TrinityCore/commit/e641d0c7d71bdb21e443bf52bf508b1581e07839#diff-952c711803610aa78110e4f92ff2516aL2305

Previous system checked DISABLE_PROC set on target only, not on caster. I recall having to change this due to chain procs. But again, that is better handled now with bb8763534ebff5422bf202e69add065a132e49ac
