### ISSUE TITLE
[3.3.5] Aspect_Of_the_Viper must return mana for AOE Damage 

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18261]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** I see Isseues about Aspect_Of_the_Viper + Volley , all mind Volley Damage return mana and does proc  , but problem is when hunter have tick " Aspect Of The Viper " and use spell Volley must returns mana for AOE damage, but  Volley doesn't proc  for ring side and all Damage 
Now problem is for Aspect_Of_the_Viper is AOE Damage don't work even for melee AOE don't work , so Volley doesn't proc yes but for AOE no.
in the all link for this problem don't say Aspect_Of_the_Viper ,doesn't proc for AOE Damage
for example : http://wow.gamepedia.com/Aspect_of_the_Viper
if for volley doesn't proc , at this time, all public servers is buged and now find this problem, after old time !!!!! ;D
Thanks

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  400a69bf9efb227e8734668f07ed2f3f2863ba47

**TDB version:**  62

**Operating system:**  win 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Mrgrasser** [comment]
for example : For every target you hit, you gain more mana (seems to be 460 mana per tick for me). If you hit 1 target with volley, you'll gain 460 mana per tick, if you hit 5 targets with volley, you'll gain 460 x 5 = 2300 mana per tick of volley.
you can AoE a mob pack with Volley (+ aspect of the viper), you get full mana instantly, and it's very good and amazing. 
Quote of friends

**Comment by ariel-** [comment]
#18129
