### ISSUE TITLE
[3.3.5] Mage and mirror images enter combat without damage

### ISSUE THREAD

**Issue by Aknunx** [TrinityCore/TrinityCore#18265]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Mage mirror images put the mage in combat instantly if they spawn close enough to an enemy.

**Current behaviour:** (Tell us what happens.) If you cast mirror images near an enemy, you'll be in combat instantly, even if you're behind a pillar and the images haven't damaged the enemy yet.

**Expected behaviour:** (Tell us what should happen instead.) You shouldn't be in combat until the mirror images damage the enemy.

**Steps to reproduce the problem:**

1.  Go into Nagrand Arena and place one player on one side of a pillar and the mage on the opposite side.
2.  Cast mirror images
3.  You'll be in combat instantly even if the images haven't damaged the enemy yet.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/7624c7cd95fda9f0406fa8b00d8f9febe42ba820

**TDB version:**   TDB 62

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
True, old bug
Happened even before #14896

**Comment by Killyana** [comment]
Cannot reproduce on rev. a891eb364e94
