### ISSUE TITLE
[master][Mac] WoW Patched

### ISSUE THREAD

**Issue by bertus193** [TrinityCore/TrinityCore#18267]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The wow patched doesn't work, when try to login always freezes and appear a fatal error closing it.

**Current behaviour:**
Wow is patched fine:
![captura de pantalla 2016-11-18 a las 10 05 53](https://cloud.githubusercontent.com/assets/22213393/20424526/aa30b68a-ad76-11e6-8ba8-07028dcc3c5c.png)

But when I try to login always freezes and break:
![captura de pantalla 2016-11-18 a las 10 05 15](https://cloud.githubusercontent.com/assets/22213393/20424553/ca8c996c-ad76-11e6-97a9-7f989daf73e3.png)

It happens always u click connect button, doesn't care the information if is true or not at login form, the client always breaks. The Config.wtf works because Windows client works fine, altough mac client no.

**Expected behaviour:**
It should connect or not.

**Steps to reproduce the problem:**

1. Open World of Warcraft Patched.app
2. Click connect

**Branch(es):** master

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/7624c7cd95fda9f0406fa8b00d8f9febe42ba820
**TDB version:**  
https://github.com/TrinityCore/TrinityCore/commit/7624c7cd95fda9f0406fa8b00d8f9febe42ba820
**Operating system:**  
MacOS Sierra 10.12.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18145
