### ISSUE TITLE
[master] DB/Quest: Rite of the Winds - cannot complete

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18262]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Standing right next to Dyami Windsoar http://www.wowhead.com/npc=36803/dyami-windsoar, Drink the Water of Vision for Quest http://www.wowhead.com/quest=24215/rite-of-the-winds, on click, **Requires you to be next to Dyami Windsoar **

**Current behaviour:** Quest fails to work

**Expected behaviour:** On drinking the Water of Vision, you should begin the Rite of Winds sequence or scenario

**Steps to reproduce the problem:**

1. Accept http://www.wowhead.com/quest=23733/rites-of-the-earthmother from http://www.wowhead.com/npc=2981/chief-hawkwind
2. Speak to http://www.wowhead.com/npc=36803/dyami-windsoar and accept http://www.wowhead.com/quest=24215/rite-of-the-winds
3. Click on the Water of Vision while standing next to Dyami Windsoar, ERROR

**Branch(es):** 7.1.0 / master

**TC rev. hash/commit:**  7675017

**TDB version:**  703

**Operating system:**  Debian 8 x64
![wowscrnshot_111616_112857](https://cloud.githubusercontent.com/assets/2609242/20362632/2ba3a6aa-abf1-11e6-879f-5cf8eaf3b2de.jpg)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
lol even blizzard have this bug:

http://www.wowhead.com/quest=24215/rite-of-the-winds#comments:id=2189486

**Comment by Aokromes** [comment]
201750 go must be spawned
