### ISSUE TITLE
[3.3.5]/petpassive command not working properly

### ISSUE THREAD

**Issue by Aknunx** [TrinityCore/TrinityCore#18264]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** /petpassive command should set your pet to passive status and inmediatly cancel any current attack from your pet, that's not how it works right now.

**Current behaviour:** (Tell us what happens.) If you're a mage with water elemental, and you're attacking someone, whenever you cast /petpassive, your pet WILL NOT cancel its current attack, instead will end the attack AND THEN turn into passive mode.
That's game breaking in some cases, for example, whenever you're focusing someone and you want to polymorph him, if your pet is also attacking that target, even if you cast /petpassive, his current attack will land, breaking your poly.

**Expected behaviour:** (Tell us what should happen instead.) /petpassive should also cancel current cast from water elemental

**Steps to reproduce the problem:**

1. Create a mage and  get frost talents.
2.  Attack someone with the water elemental.
3. Use /petpassive
4. You'll see how the elemental doesnt stop its current cast.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/7624c7cd95fda9f0406fa8b00d8f9febe42ba820

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
This is working as intended. Passive only tells the pet not to perform future attacks unless commanded, it does not interrupt the current attack. To get the result you want you need the following sequence:

> /petfollow
> /petpassive

The first command will interrupt any current attack, the second will prevent future attacks.
