### ISSUE TITLE
world.version is empty after using automatic setup

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#18274]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** world.version is empty after using automatic setup

**Current behaviour:** (Tell us what happens.)
```
TrinityCore rev. d64da044d87d 2016-11-18 00:04:02 +0100 (master branch) (Unix, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/api/trinity/trinitycore/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.1t  3 May 2016 (library: OpenSSL 1.0.1t  3 May 2016)
Using Boost version: 1.55.0
Updating Auth database...
>> Auth database is up-to-date! Containing 6 new and 82 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 3 new and 58 archived updates.
Updating World database...
>> World database is up-to-date! Containing 21 new and 1368 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 6 new and 90 archived updates.
Realm running as realm ID 1
Using World DB: Unknown world database.
Using enUS DBC Locale
```

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  Install databases using automatic setup
2. 
3. 

**Branch(es):** master

**TC rev. hash/commit:**  d64da044d87d

**TDB version:**  TDB 703.00

**Operating system:**  Debian 8.6 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. 50d9a7494b05 2016-11-20 09:59:15 +0100 (3.3.5 branch) (Win64, Release, Static) / TDB 335.62

```
>> Applied 90 queries. Containing 1 new and 1800 archived updates.
Realm running as realm ID 1
Using World DB: Unknown world database.
```
Also valid for the 3.3.5 branch.

**Comment by tkrokli** [comment]
The DB data should be inserted from the command in https://github.com/TrinityCore/TrinityCore/blob/master/src/server/worldserver/Main.cpp#L565-L571
(https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/Main.cpp#L547-L553)
```cpp
    ///- Insert version info into DB
    WorldDatabase.PExecute("UPDATE version SET core_version = '%s', core_revision = '%s'", GitRevision::GetFullVersion(), GitRevision::GetHash());        // One-time query

    sWorld->LoadDBVersion();

    TC_LOG_INFO("server.worldserver", "Using World DB: %s", sWorld->GetDBVersion());
    return true;
```
I'm too tired to continue tracing the events, so I'll have to get back to this and see if I can find out what goes on from there.

**Comment by ariel-** [comment]
Simple enough, the `version` table in world DB is not populated by the TDB sql
