### ISSUE TITLE
[3.3.5] Spell/Hunter: Traps not working vs enemies of the same faction in arenas and pvp zones

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18271]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The traps are not working when an enemy of the same faction is affected in arenas or pvp zones. Only Explosive Trap can be triggered.

**Current behaviour:** 
vs enemies of the same faction the traps are not triggered in arenas and pvp zones.

**Expected behaviour:** 
vs enemies of the same faction the traps must be triggered in arenas and pvp zones.

**Steps to reproduce the problem:**
1. (Hunter) .tele gurubashi and summon any player of the same faction.
2. Use any trap except  [Explosive Trap].
3. Nothing happens.  The same occur in Ruins of Lordaeron, etc.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  503259e

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by noryad** [comment]
This is a very important bug, but there are many. @ariel- is doing an amazing job like spell fixer but is the one. For our community 3.3.5 is the legendary branch of trinitycore, maybe it's important to give it a boost. We belive in trinitycore. Thankyou.

**Comment by Aokromes** [comment]
do i look spell fixer?

**Comment by ccrs** [comment]
![image](https://cloud.githubusercontent.com/assets/4329612/20456076/e6a8e9d8-ae6c-11e6-8dd9-30a52c3e019e.png)

**Comment by noryad** [comment]
@Aokromes 
You are a member of trinitycore, maybe you can help with something, that comment is not very friendly and does not help to solve anything.

**Comment by Mrgrasser** [comment]
@Aokromes  What do you like ?!!! you are head Developer , if you want can

**Comment by Aokromes** [comment]
your comment helps less, people fixes what they known to fix, have time to fix, if i try to fix one spell i break core,.

**Comment by Keader** [comment]
I understand you, but this project is for learning... i dont think that has some "priority" in pvp or pve issues, for me, all issue is the same.
I agree with you, ariel is doing a amazing work for 3.3.5 branch, like shauren does for master... and they need "some help". But this is a teamwork... nothing prevents that you research about this and fix by yourself and share with us.
btw i cant help you right now, buzy with https://github.com/Keader/TrinityCore/issues/1 ^^

**Comment by noryad** [comment]
Thanks @Keader , is a very professional comment, please tell me where can i find documentation about the architecture, masks, flags, etc. All i want is to help. I think that it's time to take up the subject again.

**Comment by tkrokli** [comment]
@noryad : There are several sources of documentation:

1. the source code itself (read comment lines and .h files for info)
2. the TrinityCore Wiki: https://trinitycore.atlassian.net/wiki/
3. https://github.com/TrinityCore/SpellWork (spell info based on compiled server & DBC)
4. https://trinitycore.atlassian.net/wiki/display/tc/IRC (#trinity @ irc.rizon.net) for minor questions
