### ISSUE TITLE
Core/Spell: Restricted Flight Area

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18286]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**  When you fly in Dalaran you will be dismounted directly without having this aura http://www.wowhead.com/spell=58600/restricted-flight-area it looks the dismount effect is triggered directly ignoring the count down.

**Steps to reproduce the problem:**

1.  go to dalaran with a flying mount
2.  You will be dismounted without getting the 10 secs of 58600 and without a parachute.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 50d9a7494b05

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ccrs** [comment]
``
Attributes: 0x25000000 (SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_NEGATIVE_1, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x00000800 (SPELL_ATTR1_UNK11)
AttributesEx6: 0x00001000 (SPELL_ATTR6_CASTABLE_WHILE_ON_VEHICLE)
``

**Comment by tkrokli** [comment]
TrinityCore rev. 3cc89c32d551 2016-11-20 20:01:54 +0100 (3.3.5 branch) (Win64, Release, Static) / TDB 335.62

Confirmed. Player gets no warning before being dismounted over Dalaran and no parachute either.

**Comment by joshwhedon** [comment]
I investigated that a little bit, it seems like the area is not properly found (it believes you are in the crystalsong forest while you are in dalaran). Basically there is an height calculation problem.

**Comment by joshwhedon** [comment]
I went through the commits to map handling, couldn't find anything related.

**Comment by ariel-** [comment]
Bug introduced in 5cb8409f1ee57e8dccb63cd11ce241b7a853379c. Changes in SpellInfo::CheckLocation.

Return value is correct for Spell::CheckCast (client check, icon shows "grayed out"), but not for Player::UpdateAreaDependentAuras (function is called on those 2 places)
