### ISSUE TITLE
[3.3.5] CRASH: ACCESS_VIOLATION

### ISSUE THREAD

**Issue by noryad** [TrinityCore/TrinityCore#18285]
[f30778c9982d+_worldserver.exe_[20-11_1-32-15].txt](https://github.com/TrinityCore/TrinityCore/files/602050/f30778c9982d._worldserver.exe_.20-11_1-32-15.txt)
[f30778c9982d+_worldserver.exe_[20-11_2-47-58].txt](https://github.com/TrinityCore/TrinityCore/files/602051/f30778c9982d._worldserver.exe_.20-11_2-47-58.txt)

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I can not identify the reason, i attached 2 log files. Please tell me what else can be useful.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  f30778c

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Your log files are from a Release build, they don't contain the info needed for troubleshooting.
If you get a crash, compile a Debug build and post crash logs from that.

**Comment by noryad** [comment]
Thanks for everything

**Comment by jackpoz** [comment]
Or at least RelWithDebInfo, it still provides the same performances as Release but at least the crashlog will show the functions being executed
