### ISSUE TITLE
[3.3.5] Disappear Energy Cannons

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18284]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Some time Energy Cannons for active spells disappear and don't return Energy for active Spell for example : Cannon Gunship http://wowwiki.wikia.com/wiki/Horde_Gunship_Cannon or http://wowwiki.wikia.com/wiki/Alliance_Gunship_Cannon have 2 spells for active  , Often the problem after first wipe fight it happens.
[Cannon Blast] : give Energy 6 to 10 Heat
[Incinerating Blast] : use Consumes all of the cannon's Heat to launch a massive ball of fire at the target

**Current behaviour:** (Tell us what happens.) some time if raid wipe and restart battle [Cannon Blast] don't return Energy for active  [Incinerating Blast]

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  50d9a7494b053c65734605baf0aaa1439e4a70cf

**TDB version:**  62

**Operating system:**  win 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Please provide more information about which spells, game objects and/or NPCs are involved in this issue. Links to pages on [wowhead](http://www.wowhead.com/), [wowpedia](http://wow.gamepedia.com/), [wowwiki](http://wowwiki.wikia.com/wiki/Portal:Main) etc. will also be helpful to understand your issue better.

**Comment by Mrgrasser** [comment]
@tkrokli I tried to explain that more complete description of the subject if you're feeling deficit is in the first place the problemو I get SS and videos

**Comment by ariel-** [comment]
Is this valid?

**Comment by tkrokli** [comment]
Not likely, nobody else have confirmed this so far, or even posted a duplicate issue about it. This issue also lacks a description on how to reproduce and could be closed for lack of documentation.

**Comment by ariel-** [comment]
Very well
