### ISSUE TITLE
[master] DB/Creature: Remove Stormwind Construction workers

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/TrinityCore#18288]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Remove Stormwind construction workers, Stormwind has been repaired from Deathwing's attack.

**Current behaviour:** Construction workers remain from when Stormwind was still damaged after Deathwing's attack.

**Expected behaviour:** Stormwind has been repaired and the spawns should no longer exist.

**Branch(es):** master

**TC rev. hash/commit:** d64da044d87dd8c792dd3e8dc1be53e81c701273

**TDB version:**  703.00

```sql
DELETE FROM `creature` WHERE `id` IN (28569,28596);
```

**Comment by Ovahlord** [comment]
will probably cause db errors. Also delete the creature_addon datas

**Comment by Krudor** [comment]
Yup, good idea

**Comment by Kittnz** [comment]
I wouldn't delete from creature_template_addon .

**Comment by Aokromes** [comment]
creature_addon not creature_template_addon

**Comment by Krudor** [comment]
Well, there's nothing in creature_addon for those creatures but yeah you are correct, creature_template_addon wouldn't throw any errors :P

**Comment by Kittnz** [comment]
But shouldn't be delete,  DELETE FROM `creature` WHERE id IN (28569,28596); should be enough.
