### ISSUE TITLE
Core/Spells: Cast Charm while target on water

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18281]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** If the npc is on water during the cast of a charm spell the posses will happen without aura.

**Steps to reproduce the problem:**

1. .go id 102721
2. .quest add 12214
3. .add 37202
2. .die the knight (dont hit the horse)
3. Use the item to ride it when it's on water
4. Result: http://i.imgur.com/heo0vFv.jpg

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  rev. 3f19eea5e41f

**Comment by joshwhedon** [comment]
OK so it is actually unrelated to movement. The issue is that those horses are in the water, but the aura is removed when in water (aura interrupt flag). Therefore as soon as you cast it, the aura gets removed, but you still are entering the vehicle. You are then in an invalid state.

**Comment by Langerz82** [comment]
So what would be an appropriate algorithm for fixing the issue?

**Comment by Killyana** [comment]
If the interrupt flag is used the cast spell must probably fail.
Also on rev. 01386cf4471 it crashs the server

**Comment by Langerz82** [comment]
Try and test:

```diff
diff --git src/server/game/Spells/Spell.cpp src/server/game/Spells/Spell.cpp
index 03d45aa223..0d067184a5 100644
--- src/server/game/Spells/Spell.cpp
+++ src/server/game/Spells/Spell.cpp
@@ -5802,6 +5802,12 @@ SpellCastResult Spell::CheckCast(bool strict, uint32* param1 /*= nullptr*/, uint
         }
     }
 
+    Unit* target = m_targets.GetUnitTarget();
+    if (target && m_caster->ToPlayer() && target->IsVehicle() && target->IsInWater())
+    {
+        return SPELL_FAILED_ONLY_ABOVEWATER;
+    }
+
     // all ok
     return SPELL_CAST_OK;
 }
```

**Comment by tkrokli** [comment]
@Langerz82 : Consider open a new ticket if this issue is unsolved and commit https://github.com/TrinityCore/TrinityCore/commit/eb7d22d23eedb0d1b5374f80518cd7994d7c7b3a did not solve this issue completely.
