### ISSUE TITLE
[master] Crash GetFloatValue due to Creature usage of PLAYER_FIELD_MOD_DAMAGE_DONE_PCT

### ISSUE THREAD

**Issue by DJScias** [TrinityCore/TrinityCore#18280]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Crash in regards to NPCs using certain spells, related to https://github.com/TrinityCore/TrinityCore/commit/b9f7b500a362736235fc917ce4f34aa8520eb651#commitcomment-19893545

**Current behaviour:** (Tell us what happens.) Random crashes happening due to a GetFloatValue assert caused by the following line: https://github.com/TrinityCore/TrinityCore/commit/b9f7b500a362736235fc917ce4f34aa8520eb651#diff-4522eeffcbc961602e86620011a2d579R7955

PLAYER_FIELD_MOD_DAMAGE_DONE_PCT does not exist for creatures yet it was called in that function by the server and thus caused an assert (I think at least).

**Expected behaviour:** (Tell us what should happen instead.) No crash.

**Steps to reproduce the problem:**

1.  Start your server.
2.  Find an NPC that casts spells, crashlog I read mentioned http://www.wowhead.com/npc=27800, but it's random.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/b9f7b500a362736235fc917ce4f34aa8520eb651

**TDB version:**  703.00

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Please check again with your core updated to the currently available commit, at least commit https://github.com/TrinityCore/TrinityCore/commit/ee21cd31a1dd72fcd74018d3bfc4ac488dbe7bf8 [**Core/Auras: Fixed SPELL_AURA_MOD_DAMAGE_PERCENT_DONE for creatures (a…**
…nd crashfix)](https://github.com/TrinityCore/TrinityCore/commit/ee21cd31a1dd72fcd74018d3bfc4ac488dbe7bf8)
