### ISSUE TITLE
npc equipments 7.1

### ISSUE THREAD

**Issue by Farrarie** [TrinityCore/TrinityCore#18299]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
command spawn npc lose their weapons!

**Current behaviour:** (Tell us what happens.)
When spawn npc any npc like for instance spawn orgrimmar grunt by command .npc add (creature ID)
they don't have their weapons (equipment in their hands) I think this is the fix of the problem https://github.com/conan513/SingleCore_TC/commit/8ba4d0090cb9d02bca61bff538eb8e6879ccd327
**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. check this fix and plz apply to master 7x https://github.com/conan513/SingleCore_TC/commit/8ba4d0090cb9d02bca61bff538eb8e6879ccd327
2. 
3. 

**Branch(es):**(7.1.0) / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
latest
**TDB version:**  
latest
**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
don't open a new ticket, this ticket is duplicate, that fix was reverted because it's incorrect.

**Comment by Farrarie** [comment]
@aokromes what do u mean its incorrect ?

**Comment by Farrarie** [comment]
did u fix the problem in the latest build so when I compile latest trinity core I can spawn npc with weapon in hands ??

**Comment by Farrarie** [comment]
@aokromes ??

**Comment by Aokromes** [comment]
stop spamming. i linked you one open ticket about this issue.
