### ISSUE TITLE
npc equipments 7.1

### ISSUE THREAD

**Issue by Farrarie** [TrinityCore/TrinityCore#18295]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
after patch 6.3 like in patch 6.4 and up when I spawn npc they don't have their equipments in their hands
I think somebody disabled by accident the npc equipments (weapons) can u plz check it
**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)
plz check what happened with creature equipments why when I spawn they don't have their
equipments in their hands it happened after patch 6.3 and until now
it mean a lot to me
**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
6.x
**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lorac2k14** [comment]
6x? Don't you mean master 
As for Creature equipment 
Check your creature_equip_template make sure  creature is in template
You can easily fix this by making sure your creature_equip_template has proper information in it for the creature you are trying to spawn not to mention proper equip id in creatures table
If that is 0 they will not equip
For information on [creature table](https://trinitycore.atlassian.net/wiki/display/tc/creature)
For information on [creature_equip_template](https://trinitycore.atlassian.net/wiki/display/tc/creature_equip_template)
Hope this helps shed a little light on your issue
 :-)

**Comment by Aokromes** [comment]
patch 6.3? 6.4?

**Comment by Aokromes** [comment]
#17821

**Comment by Farrarie** [comment]
thx guys for the replyes creature_equip_template
it didn't work I think the problems is this 
https://github.com/conan513/SingleCore_TC/commit/8ba4d0090cb9d02bca61bff538eb8e6879ccd327
can u plz fix it in the master

**Comment by tkrokli** [comment]
1. master is not the same as 6.x
2. make sure your core is up to date with master (7.x = retail build)
3. this issue is closed because it is a duplicate.
4. if you want to contribute, comment in issue #17821 where it belongs (and please follow TC rules)
