### ISSUE TITLE
[3.3.5] No Item was sent with mailto over RA system

### ISSUE THREAD

**Issue by bengelbaer** [TrinityCore/TrinityCore#18291]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
No Item was sent with mailto over RA system.
If i buy a Item in itemstore there loads a long time, and gives me no errors back.
It says "Success, item send over ingame mail system"

but ingame is nothing in mail sytsem.

Other things like unstuck, teleport works fine.

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. sent Item over RA 
2. RA say´s sucess
3. no item in mailsystem

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
674ac56303f0
**TDB version:**  
TDB_full_335.62_2016_10_17
**Operating system:**  
Debian 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ccrs** [comment]
LUL

**Comment by jackpoz** [comment]
> sent Item over RA

please describe the actual steps to reproduce the issue, this is just a generic description

**Comment by bengelbaer** [comment]
So, I use ACER CMS, which has a Vote and Donation shop system. RA is actually properly configured. Unstuck and Revive command work perfectly. If I now buy an ITEM over the shop, then the purchase is carried out and confirmed, but ingame comes to nothing. I guess therefore the multiple with the RA port something wrong. Maybe you can test it somehow!

**Comment by bengelbaer** [comment]
haha...

i found this...

> After several long hours working with the RA system for TrinityCore, I was unable to solve the issue surrounding the Item Store. However, I have modified the CMS with a temporary SOAP replacement for compatibility with the latest TrinityCore revisions. The official download has been updated with this temporary replacement, and will not have RA support.

so you can close this issue. Sorry. and thanks.

**Comment by DDuarte** [comment]
No, RA was not replaced by SOAP. They are both supported and both should be working.

**Comment by bengelbaer** [comment]
look here

http://azer-cms.com/?page=topic&id=1&t=3271

and you will understand.

**Comment by DDuarte** [comment]
I don't understand.

**Comment by jackpoz** [comment]
> @Kittnz closed this 37 minutes ago

so sending a mail through RA works ?

**Comment by tkrokli** [comment]
Looks more like Azer CMS uses a SOAP workaround for RA because it does not seem to work with RA only.

**Comment by ccrs** [comment]
thats why I said "LUL"
 both systems work perfectly, pretty sure its the cms not handling it correctly

**Comment by bengelbaer** [comment]
ok i test the RA system with telnet. Login is ok, but 

send mail #playername "#subject" "#text" 

does nothing. Is here a problem on Trinity????

**Comment by bengelbaer** [comment]
ok if i do the command ingame

.send mail Powergnom "test" "test"

the chat says "Mail sent to Powergnom" but there is no mail sent to the character
