### ISSUE TITLE
[3.3.5] crash cs_list 

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18296]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Worldserver crash after  list item or spam list

[unknown_worldserver.exe_[22-11_11-9-56].txt](https://github.com/TrinityCore/TrinityCore/files/605779/unknown_worldserver.exe_.22-11_11-9-56.txt)

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  add soul shard for warlock and spam add, after spam add give list item, with spam list
2. I have target dummy
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  b333c92d0cfb81dfa51c40d39a181fbff462130c

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
This is not a crash, it's FreezeDetectorHandler detecting it's taking too much time to complete the action.
You can choose a different value at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L444

Please note the "Steps to reproduce the problem:" should contain the actual steps, not a description of them.

**Comment by Mrgrasser** [comment]
MaxCoreStuckTime = 15 , ok sorry i  just try for description write " Steps to reproduce the problem"
