### ISSUE TITLE
[Demon Hunter] Glide 

### ISSUE THREAD

**Issue by imbavirus** [TrinityCore/TrinityCore#18303]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Demon Hunters' glide does not dispel upon touching the ground

**Current behaviour:** The Demon Hunter keeps gliding around on the ground 

**Expected behaviour:** Upon touching the ground the glide aura should be removed from the Demon Hunter

**Steps to reproduce the problem:**

1. Create a Demon Hunter
2. Jump 3 times or activate Glide 

**Branch(es):** master 

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/9f31a6aa3cd72f25d3fe49c6547f599772ddaeda

**TDB version:**  703.00

**Operating system:**  Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by matukaa** [comment]
Add AURA_INTERRUPT_FLAG_LANDING to the spell in SpellMgr::LoadSpellInfoCorrections() and make a SpellScript with OnCheckCast hook that returns SPELL_FAILED_NOT_ON_GROUND if !caster->IsFalling()

**Comment by streetrat** [comment]
it is missing the knock away effect too, it is another spell casted just after casting glide

**Comment by imbavirus** [comment]
Thanks @matukaa I have tested with that method and it works perfectly, I just need to add in the knock away spell and then I'll submit it as a new pull request, had some issues with my pc the last few days and moved back over to linux so I still need to finish setting everything up

**Comment by matukaa** [comment]
@imbavirus if you want to add the knockback too, you'll need a bit more work. the spell that does the knockback will knock you into a random direction (due to the current implementation of knockbacks - when no direction is given, it will randomize the angle, so whenever you try to activate Glide it will push you randomly). you need to rework the system for that a bit

**Comment by jcmillions** [comment]
@Shauren I scripted the Glide spell, but how would we go about reworking the knockback system? Any hints would help, because I'll keep working on it until it is fixed.

**Comment by matukaa** [comment]
You have two options, one being invasive, the other one is not.
If you would like to fix it only for the spell, I'd suggest using PreventHitEffect() in the EffectHitTarget phase, and do the knockback yourself (check Spell::EffectKnockBack, but be careful, Unit::KnockbackFrom will call GetSinCos(x, y, vsin, vcos), which by default returns RANDOM angles, causing you to get knocked in a random direction)
The other way would be by reworking the knockback system (by this I actually mean defaulting GetSinCos() to set vcos to cos(GetOrientation()) and vsin to sin(GetOrientation()), thus resulting in a forward push all the time). There are more spells that actually rely on a straight knockback in case when no additional parameters are given, so defaulting GetSinCos to return "straight" angles would be beneficial probably. This one needs investigation, as it may break other scripts

**Comment by jcmillions** [comment]
I don't know much about the advanced parts of TrinityCore since I just got into spell scripting, but I'll do my best. Thanks for the help

**Comment by Nupper** [comment]
This still a known issue.
