### ISSUE TITLE
Mac client crash on connect

### ISSUE THREAD

**Issue by aaplmike** [TrinityCore/TrinityCore#18305]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Mac client crashes immediately on clicking connect. I've seen this error before with the tc_bundle.txt file needing to be replaced. I've put the crash dump up at http://pastebin.com/z7Y5X9m7

**Current behaviour:** (Tell us what happens.)
Mac client crashed immediately on clicking Connect.

**Expected behaviour:** (Tell us what should happen instead.)
Successful connect to game server.

**Steps to reproduce the problem:**

1. Run comm client to apply all patches
2. Pull Master branch and build connection_patcher. Build server also with latest pull.
3. Apply connection patcher to client, observe success message
4. Change WTF/Config.wtf to point to my local server (also patched to latest)
5. Launch World of Warcraft Patched
6. Enter known good creds
7. Hit Connect

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master

**TC rev. hash/commit:**  
TrinityCore rev. 9f31a6aa3cd7 2016-11-23 17:05:36 +0100 (master branch) (MacOSX, Release, Static)

**TDB version:**  
TDB 703.00

**Operating system:**  
MacOS Sierra

I've removed the cache files from /Users/Shared/Blizzard/Battle.net/Cache. I've also removed tc_bundle.txt and let the patcher replace it a couple times. I've observed from the bnetserver console no connection attempts.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18145
