### ISSUE TITLE
[3.3.5] Dark Portal Event

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18309]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
After some time, Park NPC's on the side of the battle field and no longer fight

![wow_darkportal](https://cloud.githubusercontent.com/assets/10637389/20600833/d34dd474-b255-11e6-8493-a02f9e57cbd6.jpg)
**Steps to reproduce the problem:**

1.You must wait until this effect is true 

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  
TrinityCore rev. ab4ec5bd0112 2016-11-23 15:45:21 +0100 (335 branch)
**TDB version:**  
TDB_full_world_335.62_2016_10_17.sql + updates
**Operating system:** 
Win7 64Bit

**Comment by Killyana** [comment]
Try on rev. c2a36c9e89c7 looks be fixed.

**Comment by Tauriella** [comment]
Not fixed :(

**Comment by HannibalRoG** [comment]
Add to the report that after a while in the fight the npc get into the ladder.

**Comment by Killyana** [comment]
A test must be done after https://github.com/TrinityCore/TrinityCore/commit/69fd6245dc41dca658cadb4e99c1ee6593fe000b

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/69fd6245dc41dca658cadb4e99c1ee6593fe000b
