### ISSUE TITLE
crash bnetserver after attack this

### ISSUE THREAD

**Issue by hamedgn** [TrinityCore/TrinityCore#18312]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** crash the bnetserver after attack

**Current behaviour:** show some error and force close

**Expected behaviour:** reject this attack

**Steps to reproduce the problem:**

1. run the bnetserver 
2. some body attack to this
3. bnetserver show this errors : error link: 
[New Text Document.txt](https://github.com/TrinityCore/TrinityCore/files/613736/New.Text.Document.txt)

and crash it
**after debug with visual studio :** show this

Unhandled exception at 0x00007FF6DB44B2E4 in bnetserver.exe: 0xC0000005: Access violation writing location 0x0000000000000000.

Exception thrown at 0x00007FF6DB44B2E4 in bnetserver.exe: 0xC0000005: Access violation writing location 0x0000000000000000
Branch(es): master

crash files: [http://ldev.ir/crash.zip](url)
**TC rev. hash/commit:** 8c23059

**TDB version:** 703.00

**Operating system:** Windows Server 2016

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by funjoker** [comment]
Your link doesn't work.
There is no TDB 710 -> 703.00 only
windows 2016 -> Windows Server 2016 ?

What do you mean with "after attack"?

**Comment by jackpoz** [comment]
you can attach the crashlog (textfile) to github itself which makes it easier for us to read it

**Comment by Shauren** [comment]
Useless. These crash logs are from Release build.
```
C:\wow\TrinityCore\TrinityCore\src\server\bnetserver\Server\Session.cpp:650 in Battlenet::Session::ReadDataHandler ASSERTION FAILED:
  header.ParseFromArray(_headerBuffer.GetReadPointer(), _headerBuffer.GetActiveSize())
```
The only relevant piece of information in console logs

**Comment by hamedgn** [comment]
first post edited and link was corrected
