### ISSUE TITLE
[3.3.5] Spell/Mage: Arcane Concentration not work propertly

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18313]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
Arcane Concentration: Gives you a X% chance of entering a Clearcasting state **after any damage spell hits a target**. The Clearcasting state reduces the mana cost of your next damage spell by 100%.
The problem is that Arcane Concentration is activated by any spell. for example Arcane Intellect.

**Current behaviour:**
Arcane Concentration is activated by any spell.

**Expected behaviour:** 
Arcane Concentration only should be activated after any damage spell hits a target.

**Steps to reproduce the problem:**
1. Cast Arcane Intellect many times.
2. Clearcasting will appear at any time.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  90a5811

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Confirmed in 9b049ca
Should be labeled with Sub-Spells, Comp-Core or another?

**Comment by Noryad** [comment]
@tkrokli please this issue should be lebeled with Sub-Spells and/or another labels.

**Comment by Noryad** [comment]
@ariel- Thanks again, but now we have a big problem. Can you check #18370 please?

**Comment by ariel-** [comment]
Please do not bump closed issues with totally different issues. I've already assigned myself to that issue which means I'm looking at it, there is no need for bumping.

**Comment by Noryad** [comment]
I'm just very worried, i'm sorry it will not happen again.
