### ISSUE TITLE
[3.3.5] Crash when using Master's Call with temp pet

### ISSUE THREAD

**Issue by iridinite** [TrinityCore/TrinityCore#18316]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I encountered an assertion failure (and a resulting crash) when, as a hunter, casting Master's Call ([53271](http://www.wowhead.com/spell=53271/masters-call)) while the Filling the Cages quest ([11984](http://www.wowhead.com/quest=11984/filling-the-cages)) is active:
`TrinityCore\src\server\scripts\Spells\spell_hunter.cpp:756 in spell_hun_masters_call::spell_hun_masters_call_SpellScript::DoCheckCast ASSERTION FAILED: pet`

Crash log: https://gist.github.com/iridinite/a89f2577e7a35d29a84bcbbb9d546b8a

Specifically, your pet is replaced with Budd (spell [47014](http://www.wowhead.com/spell=47014/budds-attention-span)) so pet spells would apply to Budd, not your real pet. I have not tried any other pet spell.

**Current behaviour:** (Tell us what happens.)
`pet` in `spell_hun_masters_call_SpellScript::DoCheckCast` is `nullptr`, assertion failure is raised, server crashes.

**Expected behaviour:** (Tell us what should happen instead.)
Spell casting fails gracefully ('you do not have a pet' or something similar should suffice).

**Steps to reproduce the problem:**

1. Play a hunter character, accept 'Filling the Cages' quest ([11984](http://www.wowhead.com/quest=11984/filling-the-cages)) in Grizzly Hills
2. Have Budd replace your pet as a temporary character
3. Cast Master's Call (spell [53271](http://www.wowhead.com/spell=53271/masters-call))

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  [`ab4ec5`](https://github.com/TrinityCore/TrinityCore/commit/ab4ec5bd0112)

**TDB version:**  TDB 335.62

**Operating system:**  Server: Windows 10 Home x64 

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
caused by ```ASSERT(pet); // checked in Spell::CheckCast```
i think should be replaced by:
```cpp
if (!pet)
    return;
```

**Comment by Keader** [comment]
@iridinite can you test if fix your issue? idk how reproduce xd

**Comment by iridinite** [comment]
@Keader Yep, that fixes it.
