### ISSUE TITLE
vmap4extractor aborts while extracting files on 7.1.0.22996

### ISSUE THREAD

**Issue by dipdill** [TrinityCore/TrinityCore#18311]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**  The vmap4extractor fails while extracting files.

**Current behaviour:** The vmap4extractor ends with a std::bad_alloc Aborted (core dump)

**Expected behaviour:** Extract the vmaps for the vmap4assembler to re-assemble

**Steps to reproduce the problem:**

1. Copy the client files from a 7.0.1.22996 install to the server.
2. run the vmap4extractor while in the World of Warcraft directory.
3. will display something like this

Extracting FILE0003CAA0.xxx
Extracting FILE0003CA94.xxx
Extracting FILE0003CA9D.xxx
Extracting FILE0001C232.xxx
Extracting FILE0001C0D8.xxx
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

If someone can direct me to where the core dump file is located.... I can include it with the post.

**Branch(es):**  master 

**TC rev. hash/commit:**  9f31a6aa3cd7

**TDB version:**  703.00

**Operating system:**  Ubuntu 16.04.1 LTS

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Make sure the tools are being compiled in debug mode and then run them with [GDB](https://trinitycore.atlassian.net/wiki/display/tc/GDB). Post the crashlog in this issue once you reproduce the crash with GDB running.

P.S I guess you meant 7.1.0 and not 7.0.1.

**Comment by jackpoz** [comment]
std::bad_alloc should mean you ran out of RAM

**Comment by dipdill** [comment]
yes 7.1.0.22996... sorry for that.

Here is the output...  Hope it helps.

gdb /home/dipdill/server/bin/vmap4extractor 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dipdill/server/bin/vmap4extractor...done.
(gdb) run
Starting program: /home/dipdill/server/bin/vmap4extractor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
TrinityCore rev. 9f31a6aa3cd7 2016-11-23 17:05:36 +0100 (master branch) (Unix, Release, Static) (VMAP data extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Extract V4.03 2015_05. Beginning work ....

opened casc storage '/home/dipdill/WoW/World of Warcraft/Data' locale enUS
Detected client build: 20365

opened casc storage '/home/dipdill/WoW/World of Warcraft/Data' locale enUS
Extracting GameObject models...Extracting FILE0001C330.xxx
Extracting FILE0004D7C4.xxx
Extracting FILE0006652F.xxx
Extracting FILE00066533.xxx
Extracting FILE0006CFCB.xxx
Extracting FILE0004C4D6.xxx
Extracting FILE000648CE.xxx
Extracting FILE0001B78B.xxx
Extracting FILE0001B275.xxx
Extracting FILE0001B8BC.xxx
Extracting FILE0006EF1D.xxx
Extracting FILE0004C214.xxx
Extracting FILE0001A9D1.xxx
Extracting FILE0006B76F.xxx
Extracting FILE0006EF1F.xxx
Extracting FILE000661D0.xxx
Extracting FILE0007262C.xxx
Extracting FILE0001A6CE.xxx
Extracting FILE0007172C.xxx
Extracting FILE00071730.xxx
Extracting FILE0007172E.xxx
Extracting FILE0006DAB3.xxx
Extracting FILE00072656.xxx
Extracting FILE0005E3E1.xxx
Extracting FILE0005A7E5.xxx
Extracting FILE0007D26E.xxx
Extracting FILE00081327.xxx
Extracting FILE00077519.xxx
Extracting FILE0007DA4E.xxx
Extracting FILE0007D5C8.xxx
Extracting FILE0007D819.xxx
Extracting FILE0007D3A5.xxx
Extracting FILE0007D3A3.xxx
Extracting FILE0001B4FE.xxx
Extracting FILE0008176B.xxx
Extracting FILE0008176D.xxx
Extracting FILE0007D187.xxx
Extracting FILE0008028E.xxx
Extracting FILE0007D151.xxx
Extracting FILE00081313.xxx
Extracting FILE0001B8E5.xxx
Extracting FILE0004C74C.xxx
Extracting FILE0007FC03.xxx
Extracting FILE0007FC05.xxx
Extracting FILE0007FC07.xxx
Extracting FILE0008176F.xxx
Extracting FILE0004ABB9.xxx
Extracting FILE00080E4A.xxx
Extracting FILE00081161.xxx
Extracting FILE0001C64C.xxx
Extracting FILE00081748.xxx
Extracting FILE0006799B.xxx
Extracting FILE00081BB2.xxx
Extracting FILE00081BDE.xxx
Extracting FILE0007DF67.xxx
Extracting FILE0008C7BE.xxx
Extracting FILE0008C9BE.xxx
Extracting FILE0008CD00.xxx
Extracting FILE0003CBB8.xxx
Extracting FILE000833B1.xxx
Extracting FILE0001BA30.xxx
Extracting FILE0001A63E.xxx
Extracting FILE00080F7E.xxx
Extracting FILE000824DD.xxx
Extracting FILE00096B29.xxx
Extracting FILE00096B2D.xxx
Extracting FILE00096B2B.xxx
Extracting FILE00096B2F.xxx
Extracting FILE00096B31.xxx
Extracting FILE00096B33.xxx
Extracting FILE00096B35.xxx
Extracting FILE00096B37.xxx
Extracting FILE00096B57.xxx
Extracting FILE0008B836.xxx
Extracting FILE0001C654.xxx
Extracting FILE000552D7.xxx
Extracting FILE0001B399.xxx
Extracting FILE0001C25A.xxx
Extracting FILE000940AB.xxx
Extracting FILE0001B814.xxx
Extracting FILE0009F4EE.xxx
Extracting FILE000A2D24.xxx
Extracting FILE000A2E95.xxx
Extracting FILE000A2E98.xxx
Extracting FILE000A2F0C.xxx
Extracting FILE000A2FFA.xxx
Extracting FILE000A2B6D.xxx
Extracting FILE000CCB90.xxx
Extracting FILE000C1804.xxx
Extracting FILE000C19CB.xxx
Extracting FILE000C19CE.xxx
Extracting FILE000C2A27.xxx
Extracting FILE000C3A0F.xxx
Extracting FILE000C3A03.xxx
Extracting FILE000C3ADE.xxx
Extracting FILE000C3AE7.xxx
Extracting FILE000C3AE1.xxx
Extracting FILE00068C4B.xxx
Extracting FILE000CFDB0.xxx
Extracting FILE00098078.xxx
Extracting FILE00098076.xxx
Extracting FILE000CF526.xxx
Extracting FILE000D025C.xxx
Extracting FILE0007C81A.xxx
Extracting FILE0001B97D.xxx
Extracting FILE0001C623.xxx
Extracting FILE000DA09B.xxx
Extracting FILE000DA0A4.xxx
Extracting FILE000DA0B3.xxx
Extracting FILE000DA0E4.xxx
Extracting FILE000DA0A7.xxx
Extracting FILE000D9F93.xxx
Extracting FILE000D6CB1.xxx
Extracting FILE000D6CB4.xxx
Extracting FILE000D6CB7.xxx
Extracting FILE000DC49A.xxx
Extracting FILE000DC7C4.xxx
Extracting FILE000DC7C7.xxx
Extracting FILE000DC7CA.xxx
Extracting FILE000DC49D.xxx
Extracting FILE000DC4A1.xxx
Extracting FILE000D6D7A.xxx
Extracting FILE0003CCE2.xxx
Extracting FILE000DC4F4.xxx
Extracting FILE000D6D77.xxx
Extracting FILE000DC4A5.xxx
Extracting FILE000D9FFF.xxx
Extracting FILE000D6D97.xxx
Extracting FILE000D6D9A.xxx
Extracting FILE000D6D9F.xxx
Extracting FILE000D6D3C.xxx
Extracting FILE000D6D40.xxx
Extracting FILE000D6D4B.xxx
Extracting FILE000D9F8D.xxx
Extracting FILE000D9F90.xxx
Extracting FILE000D6CBA.xxx
Extracting FILE000D6CBD.xxx
Extracting FILE000DCAB9.xxx
Extracting FILE000DC269.xxx
Extracting FILE000DC275.xxx
Extracting FILE000D6E44.xxx
Extracting FILE000DC278.xxx
Extracting FILE000E2FB9.xxx
Extracting FILE000DFB7D.xxx
Extracting FILE000DFB0B.xxx
Extracting FILE000D6E47.xxx
Extracting FILE000D6E4A.xxx
Extracting FILE000E3176.xxx
Extracting FILE000E1D82.xxx
Extracting FILE000E4C60.xxx
Extracting FILE000E7903.xxx
Extracting FILE000E7993.xxx
Extracting FILE000E798F.xxx
Extracting FILE000E7996.xxx
Extracting FILE000E78FE.xxx
Extracting FILE000E7988.xxx
Extracting FILE0004BB28.xxx
Extracting FILE0003CC8E.xxx
Extracting FILE000E5508.xxx
Extracting FILE000E798C.xxx
Extracting FILE000E7A3C.xxx
Extracting FILE000E822F.xxx
Extracting FILE000E8233.xxx
Extracting FILE000E8239.xxx
Extracting FILE000E8236.xxx
Extracting FILE000E823C.xxx
Extracting FILE000E823F.xxx
Extracting FILE000E8242.xxx
Extracting FILE000E613F.xxx
Extracting FILE000E77B2.xxx
Extracting FILE000E7BB5.xxx
Extracting FILE000E86D8.xxx
Extracting FILE000E86DC.xxx
Extracting FILE000E8663.xxx
Extracting FILE000E8666.xxx
Extracting FILE000E8678.xxx
Extracting FILE000E867B.xxx
Extracting FILE000E866A.xxx
Extracting FILE000E8675.xxx
Extracting FILE000E86D0.xxx
Extracting FILE000E86C1.xxx
Extracting FILE000E86BA.xxx
Extracting FILE000E8692.xxx
Extracting FILE000E86C4.xxx
Extracting FILE000E86B7.xxx
Extracting FILE000E866D.xxx
Extracting FILE000E8670.xxx
Extracting FILE000E8D09.xxx
Extracting FILE000E8D0C.xxx
Extracting FILE000DC27B.xxx
Extracting FILE000D9F72.xxx
Extracting FILE0003E05A.xxx
Extracting FILE00082839.xxx
Extracting FILE000D039C.xxx
Extracting FILE000E8D4F.xxx
Extracting FILE000E8D52.xxx
Extracting FILE000ED61A.xxx
Extracting FILE000ED61E.xxx
Extracting FILE000ED622.xxx
Extracting FILE000E7F0B.xxx
Extracting FILE000EAE05.xxx
Extracting FILE000EC5CE.xxx
Extracting FILE000E65C4.xxx
Extracting FILE000CFFCD.xxx
Extracting FILE000EAA1C.xxx
Extracting FILE000EAC95.xxx
Extracting FILE000EAD7B.xxx
Extracting FILE000EAFC5.xxx
Extracting FILE000EAFC8.xxx
Extracting FILE000EB048.xxx
Extracting FILE000EB25A.xxx
Extracting FILE000EB25D.xxx
Extracting FILE000EAE9A.xxx
Extracting FILE000EAE9D.xxx
Extracting FILE000EAEA0.xxx
Extracting FILE000EB260.xxx
Extracting FILE000EB263.xxx
Extracting FILE000EB266.xxx
Extracting FILE000E597A.xxx
Extracting FILE000E597D.xxx
Extracting FILE000ED171.xxx
Extracting FILE000EDFC2.xxx
Extracting FILE000EDFC6.xxx
Extracting FILE000EDFCA.xxx
Extracting FILE000EC5D2.xxx
Extracting FILE000EC5D8.xxx
Extracting FILE000EC5E0.xxx
Extracting FILE000E959F.xxx
Extracting FILE000EA97C.xxx
Extracting FILE000EA97F.xxx
Extracting FILE000EE05E.xxx
Extracting FILE000EB269.xxx
Extracting FILE000EA529.xxx
Extracting FILE000EC466.xxx
Extracting FILE000D9F35.xxx
Extracting FILE000D9F38.xxx
Extracting FILE000D9F3B.xxx
Extracting FILE000EA2DE.xxx
Extracting FILE000E7F34.xxx
Extracting FILE000EE936.xxx
Extracting FILE000EE921.xxx
Extracting FILE000EE8C9.xxx
Extracting FILE000EED5D.xxx
Extracting FILE000EED59.xxx
Extracting FILE000EF0FB.xxx
Extracting FILE000EF0F1.xxx
Extracting FILE000EF10C.xxx
Extracting FILE000EF103.xxx
Extracting FILE000EF111.xxx
Extracting FILE000EF495.xxx
Extracting FILE000EF499.xxx
Extracting FILE000EF49C.xxx
Extracting FILE000F04F4.xxx
Extracting FILE000F050B.xxx
Extracting FILE000F050E.xxx
Extracting FILE000F0572.xxx
Extracting FILE000F04F7.xxx
Extracting FILE000F0511.xxx
Extracting FILE000F04ED.xxx
Extracting FILE000F0501.xxx
Extracting FILE000ECF95.xxx
Extracting FILE000ED4A2.xxx
Extracting FILE000F086C.xxx
Extracting FILE000F05A0.xxx
Extracting FILE000F0880.xxx
Extracting FILE000F0876.xxx
Extracting FILE000F092D.xxx
Extracting FILE000F086F.xxx
Extracting FILE000F05A3.xxx
Extracting FILE000F0883.xxx
Extracting FILE000F087B.xxx
Extracting FILE000F094A.xxx
Extracting FILE000F0A50.xxx
Extracting FILE000F0F8E.xxx
Extracting FILE000F32EF.xxx
Extracting FILE000F319D.xxx
Extracting FILE000F4152.xxx
Extracting FILE000F3387.xxx
Extracting FILE000F4412.xxx
Extracting FILE000F568D.xxx
Extracting FILE000F5AB6.xxx
Extracting FILE000BCF8C.xxx
Extracting FILE000EC72F.xxx
Extracting FILE000F0CAF.xxx
Extracting FILE000ED0B2.xxx
Extracting FILE000F037B.xxx
Extracting FILE000F5A33.xxx
Extracting FILE000F5BE5.xxx
Extracting FILE000EEEB7.xxx
Extracting FILE000F4AF8.xxx
Extracting FILE000F4AFF.xxx
Extracting FILE000F4B03.xxx
Extracting FILE000F4AF1.xxx
Extracting FILE000F4CA7.xxx
Extracting FILE000F55C5.xxx
Extracting FILE000F55CB.xxx
Extracting FILE000F5690.xxx
Extracting FILE000F5A26.xxx
Extracting FILE000F5A2A.xxx
Extracting FILE000F5C13.xxx
Extracting FILE000F5C4F.xxx
Extracting FILE000F6FD6.xxx
Extracting FILE000F6FCD.xxx
Extracting FILE000F6FC9.xxx
Extracting FILE000F6FD9.xxx
Extracting FILE000F6FE0.xxx
Extracting FILE000F7A6A.xxx
Extracting FILE000F7AC7.xxx
Extracting FILE000F7AD8.xxx
Extracting FILE000F4DB8.xxx
Extracting FILE000F8345.xxx
Extracting FILE000F8347.xxx
Extracting FILE000F8349.xxx
Extracting FILE000F6FDB.xxx
Extracting FILE000F705E.xxx
Extracting FILE000F7061.xxx
Extracting FILE000F83BA.xxx
Extracting FILE000F6FCB.xxx
Extracting FILE000F33FD.xxx
Extracting FILE000F91BA.xxx
Extracting FILE000F91C3.xxx
Extracting FILE000F91BB.xxx
Extracting FILE000F931B.xxx
Extracting FILE000F88A2.xxx
Extracting FILE000F7E32.xxx
Extracting FILE000F9319.xxx
Extracting FILE000F8675.xxx
Extracting FILE000F94D8.xxx
Extracting FILE000F5A3D.xxx
Extracting FILE000F936D.xxx
Extracting FILE000F94F7.xxx
Extracting FILE000F555C.xxx
Extracting FILE000F0637.xxx
Extracting FILE000F5AE2.xxx
Extracting FILE000FBA4F.xxx
Extracting FILE000FBA52.xxx
Extracting FILE000FBA53.xxx
Extracting FILE000F936A.xxx
Extracting FILE000F39BC.xxx
Extracting FILE000FCC29.xxx
Extracting FILE000FCC30.xxx
Extracting FILE000FCC28.xxx
Extracting FILE000FCC2A.xxx
Extracting FILE000FCC2B.xxx
Extracting FILE000FCC31.xxx
Extracting FILE000FCC32.xxx
Extracting FILE000FCC35.xxx
Extracting FILE000FD3CE.xxx
Extracting FILE000FCCAB.xxx
Extracting FILE000FCCAA.xxx
Extracting FILE000FCCA9.xxx
Extracting FILE000FCCA8.xxx
Extracting FILE000EC7B7.xxx
Extracting FILE000E8245.xxx
Extracting FILE000FCC9F.xxx
Extracting FILE000FCCA0.xxx
Extracting FILE000FCCA1.xxx
Extracting FILE000FCCA5.xxx
Extracting FILE000FF140.xxx
Extracting FILE000FC6BF.xxx
Extracting FILE000FC6BE.xxx
Extracting FILE000FC6C0.xxx
Extracting FILE000FF13B.xxx
Extracting FILE001028BB.xxx
Extracting FILE00102947.xxx
Extracting FILE00102948.xxx
Extracting FILE0010294B.xxx
Extracting FILE0010294C.xxx
Extracting FILE0010294D.xxx
Extracting FILE0010294E.xxx
Extracting FILE0010294F.xxx
Extracting FILE00102950.xxx
Extracting FILE00102951.xxx
Extracting FILE00102952.xxx
Extracting FILE00102953.xxx
Extracting FILE00102D6E.xxx
Extracting FILE00102D78.xxx
Extracting FILE00102D7A.xxx
Extracting FILE00102D8B.xxx
Extracting FILE00102D9A.xxx
Extracting FILE00102D9B.xxx
Extracting FILE00102D9F.xxx
Extracting FILE00102DA2.xxx
Extracting FILE00102DA4.xxx
Extracting FILE00102EE0.xxx
Extracting FILE00102EDC.xxx
Extracting FILE00102EDF.xxx
Extracting FILE00102954.xxx
Extracting FILE00102955.xxx
Extracting FILE00102956.xxx
Extracting FILE00102ECF.xxx
Extracting FILE00102ED0.xxx
Extracting FILE00102EDB.xxx
Extracting FILE000F4A1F.xxx
Extracting FILE00103D08.xxx
Extracting FILE00103D19.xxx
Extracting FILE00103D18.xxx
Extracting FILE000F556C.xxx
Extracting FILE00103D10.xxx
Extracting FILE00103D09.xxx
Extracting FILE00103D1A.xxx
Extracting FILE00103D1C.xxx
Extracting FILE000EA4D6.xxx
Extracting FILE00103D11.xxx
Extracting FILE00103D04.xxx
Extracting FILE00103D17.xxx
Extracting FILE00103D0C.xxx
Extracting FILE00103E10.xxx
Extracting FILE000F81A7.xxx
Extracting FILE00103D1B.xxx
Extracting FILE00103D12.xxx
Extracting FILE00103D05.xxx
Extracting FILE00103D06.xxx
Extracting FILE0004B18D.xxx
Extracting FILE000FF0BA.xxx
Extracting FILE000FF12D.xxx
Extracting FILE00108704.xxx
Extracting FILE000FA408.xxx
Extracting FILE000E88B1.xxx
Extracting FILE000CF82B.xxx
Extracting FILE000FC1F9.xxx
Extracting FILE00093C62.xxx
Extracting FILE000F02C4.xxx
Extracting FILE00110440.xxx
Extracting FILE00110441.xxx
Extracting FILE0001C3AD.xxx
Extracting FILE0001A8DB.xxx
Extracting FILE0001C3B3.xxx
Extracting FILE0010ECE8.xxx
Extracting FILE0001C593.xxx
Extracting FILE001108F4.xxx
Extracting FILE00111C8B.xxx
Extracting FILE0006B78B.xxx
Extracting FILE0006D9E9.xxx
Extracting FILE00113BDD.xxx
Extracting FILE001142DC.xxx
Extracting FILE001153C1.xxx
Extracting FILE001153C2.xxx
Extracting FILE00113EEC.xxx
Extracting FILE00115218.xxx
Extracting FILE0011449C.xxx
Extracting FILE00115C9C.xxx
Extracting FILE000F102F.xxx
Extracting FILE001164A0.xxx
Extracting FILE00109A05.xxx
Extracting FILE0006FAA4.xxx
Extracting FILE000E5A32.xxx
Extracting FILE00113CE9.xxx
Extracting FILE0010A46F.xxx
Extracting FILE00115233.xxx
Extracting FILE00111F5C.xxx
Extracting FILE00132243.xxx
Extracting FILE000E0F9B.xxx
Extracting FILE0013227F.xxx
Extracting FILE000949DF.xxx
Extracting FILE00130DA6.xxx
Extracting FILE000ECA4D.xxx
Extracting FILE000CF82E.xxx
Extracting FILE0012E2B4.xxx
Extracting FILE00135BFB.xxx
Extracting FILE0001BA39.xxx
Extracting FILE0005AB43.xxx
Extracting FILE00058B19.xxx
Extracting FILE0001C2CC.xxx
Extracting FILE00115AEF.xxx
Extracting FILE001402AF.xxx
Extracting FILE00138A21.xxx
Extracting FILE00138A24.xxx
Extracting FILE00138A23.xxx
Extracting FILE00138A01.xxx
Extracting FILE000F128F.xxx
Extracting FILE00115D66.xxx
Extracting FILE001436BB.xxx
Extracting FILE001457A1.xxx
Extracting FILE001457A3.xxx
Extracting FILE001457A5.xxx
Extracting FILE001457A7.xxx
Extracting FILE0004ACAB.xxx
Extracting FILE0001BAC9.xxx
Extracting FILE0013273E.xxx
Extracting FILE000EDD6B.xxx
Extracting FILE0010F0AD.xxx
Extracting FILE0010F0AF.xxx
Extracting FILE0014A71C.xxx
Extracting FILE0014A723.xxx
Extracting FILE0014FE48.xxx
Extracting FILE0014FC6E.xxx
Extracting FILE00150106.xxx
Extracting FILE00150903.xxx
Extracting FILE00115C9B.xxx
Extracting FILE00153AE9.xxx
Extracting FILE0010A867.xxx
Extracting FILE0010A860.xxx
Extracting FILE0010A856.xxx
Extracting FILE00111A46.xxx
Extracting FILE000DCEC0.xxx
Extracting FILE0015417B.xxx
Extracting FILE0015417D.xxx
Extracting FILE0015417F.xxx
Extracting FILE000546FB.xxx
Extracting FILE00156085.xxx
Extracting FILE00156084.xxx
Extracting FILE000359B6.xxx
Extracting FILE00109B64.xxx
Extracting FILE0001C1C7.xxx
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Program received signal SIGABRT, Aborted.
0x00007ffff6c58428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by funjoker** [comment]
how much memory does your system have?

**Comment by dipdill** [comment]
4 Gig.  I know it's not much.  But it should be able to handle this.

**Comment by tkrokli** [comment]
Just to be on the safe side, could you run `memtest86+` and check that it does not find anything wrong?
Have you checked how much free memory you have got in your current Ubuntu configuration?

**Comment by Aokromes** [comment]
Try again on head.

**Comment by tkrokli** [comment]
Yes, the tools have had some updates lately, so it is definitely worth trying again and see if it works now.

**Comment by funjoker** [comment]
deprecated

**Comment by tkrokli** [comment]
Thanks. Also no messages about this for more than a year.

**Comment by Aokromes** [comment]
maybe deprecated version, but for sure tools still can crash.
