### ISSUE TITLE
[master] Warrior charge not working

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#18326]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Warrior charge not working

**Current behaviour:** (Tell us what happens.)
Just "farts"
https://streamable.com/skod

**Expected behaviour:** (Tell us what should happen instead.)
http://www.wowhead.com/spell=100/charge

**Steps to reproduce the problem:**

1.  Level warrior to 3 and try.
2. 
3. 

**Branch(es):**
master

**TC rev. hash/commit:**  
90070d5

**TDB version:**  
703.00

**Operating system:**  
Debian 8.6 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#12075
