### ISSUE TITLE
[7.X] Spell Shaman Restoration T16_2P_Bonus/Natures Barrier.

### ISSUE THREAD

**Issue by Unknown-1000** [TrinityCore/TrinityCore#18331]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Shaman T16 Restoration 2P - Natures Barrier.
**Current behaviour:** (Tell us what happens.)
No Action on Earth Shield Heal.
**Expected behaviour:** (Tell us what should happen instead.)
http://www.wowhead.com/spell=204288/earth-shield - Dummy Aura.
http://www.wowhead.com/spell=204290/earth-shield
In Legion this is honor talent.
If you have http://www.wowhead.com/spell=145378/item-shaman-t16-restoration-2p-bonus#comments
aura, Earth Shield on Proc - Earth Shied Dummy Aura Caster should cast custom spell on proc target http://www.wowhead.com/spell=145379/natures-barrier

145378 not have proc flag, we can add proc flag in SpellMgr.cpp or spell_proc table or spell_proc_event table?
**Steps to reproduce the problem:**

1. Missing
2. Missing
3. Missing

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master, because spell add in 5.4.0.
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/def94248e1bd3862a519782c08903bb484636d81
**TDB version:**  
https://github.com/TrinityCore/TrinityCore/releases/tag/TDB703.00
**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

https://github.com/TrinityCore/TrinityCore/commit/56a7e86a2869e0b179c7ccac8221fac2979560e6
Replaced shaman spells. Earth Shield Heal have target self. This is problem.
Maybe need add SetGuid? ProcTarget select caster on proc and caster cast custom spell on ProcTarget?

**Comment by Ulduar** [comment]
``` CPP
ID - 145378 Item - Shaman T16 Restoration 2P Bonus
=================================================
Description: When Earth Shield heals a target, the target will gain $s1% of the amount healed as an absorb.
Category = 0, SpellIconID = 857, activeIconID = 0, SpellVisual = (0,0)
Family SPELLFAMILY_SHAMAN, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x09040040 (SPELL_ATTR0_PASSIVE, SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE, SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_CASTABLE_WHILE_SITTING)
AttributesEx1: 0x00000020 (SPELL_ATTR1_NOT_BREAK_STEALTH)
AttributesEx2: 0x00084000 (SPELL_ATTR2_UNK14, SPELL_ATTR2_NOT_NEED_SHAPESHIFT)
AttributesEx3: 0x04000000 (SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED)
AttributesEx4: 0x00010080 (SPELL_ATTR4_CAN_CAST_WHILE_CASTING, SPELL_ATTR4_NOT_USABLE_IN_ARENA_OR_RATED_BG)
AttributesEx5: 0x00060008 (SPELL_ATTR5_USABLE_WHILE_STUNNED, SPELL_ATTR5_USABLE_WHILE_FEARED, SPELL_ATTR5_USABLE_WHILE_CONFUSED)
AttributesEx6: 0x00001000 (SPELL_ATTR6_CASTABLE_WHILE_ON_VEHICLE)
AttributesEx8: 0x00000020 (SPELL_ATTR8_UNK5)
AttributesEx9: 0x00100800 (SPELL_ATTR9_UNK11, SPELL_ATTR9_UNK20)
AttributesEx11: 0x04010000 (SPELL_ATTR11_UNK16, SPELL_ATTR11_UNK26)
AttributesEx12: 0x00020000 (SPELL_ATTR12_UNK17)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 1) = 0,00

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 300
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 300, misc = 15 (15), miscB = 0, periodic = 0
```
Need C++ script for this aura.
And maybe spell_proc_event entry for this spell.
There amount = Earth Shield heal *amount/100.

**Comment by Ulduar** [comment]
Maybe @Aokromes, @Shauren, @tkrokli, @Krudor, @Keader, can say more.

**Comment by Unknown-1000** [comment]
Thanks for data, waiting response.
