### ISSUE TITLE
[master] Hippogryph Master Stephanos misplaced

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18339]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
The Exodar Hippogryph Master does not exist, id 17555.
- http://www.wowhead.com/npc=17555/stephanos

**Current behaviour:** (Tell us what happens.)
The Exodar Hippogryph Master currently does not exist in game.

**Expected behaviour:** (Tell us what should happen instead.)
The flight master should be in The Exodar.

**Steps to reproduce the problem:**

1. Purchase a flight to The Exodar
2. Notice that the Hippogryph Master is not there.
3. 

**Branch(es):**  master

**TC rev. hash/commit:**  9633c8c2b70d230ec0c0825e29f52722744afcb4

**TDB version:**  7.0.3 + updates

**Operating system:**  Windows 10

**Comment by tkrokli** [comment]
TrinityCore rev. 9b006e511bf4 2016-11-29 11:31:41 +0100 (master branch) (Win64, Release, Static) / TDB 703.00

Confirmed. Stephanos `<Hippogryph Master>` has not been moved to the new Taxi stand inside The Exodar  but stands at the old location. Anyone feel like visiting him on retail and get his exact position etc. in a sniff?

http://www.wowhead.com/npc=17555/stephanos#comments:id=1184199
> As of Patch 4.0.3a he is no(w) inside near the Seat of the Naaru, at the bottom of the ramp from innkeeper. He is no longer stood outside.

Current (and wrong) location in TDB 703.00:
```sql
SELECT * FROM `creature` WHERE `id`= 17555; -- Stephanos, Hippogryph Master
```
```
 guid      id     map  zoneId  areaId  spawnMask  PhaseId  PhaseGroup  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  VerifiedBuild
-----  ------  ------  ------  ------  ---------  -------  ----------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  -------------
63164   17555     530       0       0          1        0           0        0             0    -4057.15    -11788.6     8.87662      5.59502            300          0                0      14193     2790             0        0           0             0              0
```
