### ISSUE TITLE
[3.3.5] Console Spam message

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18337]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Worldserver Console shows many error messages in output.

**Current behaviour:** (Tell us what happens.)
```
Unit (Entry 18965) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18986) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18986) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18986) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  
TrinityCore rev. b049caf62fff 2016-11-28 01:30:34 +0100 (335 branch)

**TDB version:**  
TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  
Win7 64Bit

**Comment by Riztazz** [comment]
This is caused by bad script once again, do not call new movement generators in movement inform. Either stop path or call it in waypoint end hook

**Comment by ConradBunton** [comment]
Any news ?

**Comment by Tauriella** [comment]
@Riztazz take a day or two Huhh?

**Comment by Riztazz** [comment]
All of them are caused by bad scripts, stop calling new movement generators in movement inform, there - you can go fix those now

**Comment by Nameback** [comment]
Forgive me as I don't understand everything about this, so it's caused by a bad script? Is there a particular one I can find a remove? Will it be patched somewhere in the future and I can simply recompile in a week or two?

**Comment by Tauriella** [comment]
I think we can close this Thread
 Bug is fixed with TrinityCore rev.  a3c6880  2017-01-20 14:16:47 +0100 (335 branch)

Thank you very much
