### ISSUE TITLE
[3.3.5] crash spellauras

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18332]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** crash log RelWithDebInfo

[unknown_worldserver.exe_[30-11_11-5-50].txt](https://github.com/TrinityCore/TrinityCore/files/614996/unknown_worldserver.exe_.30-11_11-5-50.txt)

Edit : "Revision: TrinityCore rev. 0df7d22a89c0 2016-11-27 23:24:33 0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) "

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  0df7d22a89c09e3a15711211dec77fed8613cd1a

**TDB version:**  62

**Operating system:**  Windows Server 2012 R2

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
plz, fix "Revision: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch)" thing

**Comment by tkrokli** [comment]
Please also post a new crash log produced from actual compile on rev. 0df7d22 2016-11-27 23:24:33 0100

**Comment by Mrgrasser** [comment]
New : [NewCrashLog.txt](https://github.com/TrinityCore/TrinityCore/files/615230/NewCrashLog.txt)

**Comment by sirikfoll** [comment]
@Mrgrasser  Do you have Crossfaction?

**Comment by Mrgrasser** [comment]
yes , I have This custom patch

**Comment by sirikfoll** [comment]
This crash is caused by CrossFaction, same as in #17174

**Comment by Mrgrasser** [comment]
really Thank you @sirikfoll , for see log and help
