### ISSUE TITLE
[335] Darkmoon cannon incorrectly requires darkmoon game token

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18338]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

[Darkmoon Game Token](http://www.wowhead.com/item=71083/darkmoon-game-token) should not be required for the cannon in 3.3.5 since they were added in 4.3.0.15005.

**Current behaviour:**

[Maxima Blastenheimer](http://www.wowhead.com/npc=15303/maxima-blastenheimer), the cannon operator at the Darkmoon Faire in Elwynn Forest asks for a Darkmoon Game Token.

**Expected behaviour:**

Don't know but she should not require the token.

**Steps to reproduce the problem:**

1. Talk to the NPC mentioned above
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11 + updates

**Operating system:**  Win XP / Win 7

**Notes:**

> * Even though this is not the most recent core / db, a search of the repo did not find any open or closed report regarding this issue.
> * I could not give myself a token (they don't exist) to see if the cannon itself is scripted properly

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by pedroevil51** [comment]
Still an issue

**Comment by illfated** [comment]
in my opinion, it would be more correct to label this issue as **[Priority-Low]** instead of Cosmetic, because this issue blocks players from testing a scripted in-game feature (before the Darkmoon Game Token requirement is removed). I presume this issue is caused by a DB setting imported from 6.x, but I don't know for certain.

**Comment by MrSmite** [comment]
> I presume this issue is caused by a DB setting imported from 6.x, but I don't know for certain

Yes. In earlier versions of the DB, the coin was not required but the cannon was also not scripted**.

** Actually, long ago the cannon sort of worked but it would sometimes shoot you way into Eastvale Logging Camp, almost into Lakeshire. I think this might have been a C++ script that was then converted to a DB script which broke the cannon so it would no longer fire. Then, recently the coin issue happened...

**Comment by illfated** [comment]
Wow, nice. I forgot to think that it would be as easy as removing/changing the gossip id back to pre-Cata.
