### ISSUE TITLE
Core/SAI: Smart action move to position

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18343]
**Description:** If the npc that use this action has movement_type=1 or 2 (random move, waypoints) it will directly return to its home position to continue the random movements or the waypoint.

**Current behaviour:** After reaching the position set as target for the action move_to_pos, the npc to the home pos.
**Expected behaviour:** After reaching the position set as target for the action move_to_pos, the npc must stay in this position.

**Steps to reproduce the problem:** There's no case as always there's a hack to avoid this behavior

https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/src/server/game/AI/SmartScripts/SmartScript.cpp#L1489

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. b049caf62fff

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Kittnz** [comment]
Is this for the http://wotlk.openwow.com/quest=11919 quest?

**Comment by Killyana** [comment]
Yes it starts to make me crazy.

**Comment by Langerz82** [comment]
I will try and work on this issue tomorrow.

**Comment by tkrokli** [comment]
(Replaced the link http://wotlk.openwow.com/quest=11919 with the link https://woehead.way-of-elendil.fr/?quest=11919 in Kittnz' comment https://github.com/TrinityCore/TrinityCore/issues/18343#issuecomment-263641877, because the site **openwow.com** has been abandoned for more than a year now and is not likely to come back again.)

**Comment by Langerz82** [comment]
When: PR https://github.com/TrinityCore/TrinityCore/pull/21392 is commited it will be easier to fix this issue.

**Comment by Killyana** [comment]
For me the issue is fixed you can test with:
``` sql
UPDATE creature SET MovementType=0, spawndist=0 WHERE id=321;
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry=321;
DELETE FROM smart_scripts WHERE entryorguid=321 AND source_type=0;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, COMMENT) VALUES 
-- move to pos
-- (321, 0, 0, 0, 1, 0, 100, 1, 5000, 5000, 0, 0, 69, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, -26.2108, 0.0800, -144.708649, 0, '321 - Ooc - move to pos'),
-- (321, 0, 1, 0, 34, 0, 100, 1, 0, 1, 0, 0, 89, 5, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 -  movent informer - Random Move');
-- wp
(321, 0, 0, 0, 1, 0, 100, 1, 5000, 5000, 0, 0, 53, 1, 321, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 - Ooc - Start Waypoint'),
(321, 0, 1, 0, 58, 0, 100, 1, 0, 0, 0, 0, 89, 5, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, '321 -  on wp ended - Random Move');
DELETE FROM waypoints WHERE entry IN(321);
INSERT INTO waypoints (entry, pointid, position_x, position_y, position_z, point_comment) VALUES 
(321, 1, -26.2108, 0.0800, -144.708649, '321');
```
Still something I'm not sure about it: If the npc moves from the spawn position to a pos1 with the action move to pos and then starts a combat and evades, it must returns to the spawn position or to Pos1?

**Comment by ccrs** [comment]
spawn position. action move is just a point movement, no home position is set there.
