### ISSUE TITLE
[master] Rogue finishing moves will always only consume one combo point.

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18348]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Rogue finishing moves only have one effect independent of combo points (cp)
**Current behaviour:** (Tell us what happens.)
Rogue finishing moves will consume and perform the effect of one cp regardless of the number of combo points the player has. Tested on rupture, eviscerate, envenom, run through.
**Expected behaviour:** (Tell us what should happen instead.)
If player has 5 cp and uses finishing move, 5 cp will be consumed and the effect determined by 5 cp will be performed. If the player has 4 cp and uses a finishing move 4 cp will be consumed and the 4 cp effect will occur. Etc.
**Steps to reproduce the problem:**

1. Choose Rogue class
2. Build combo points > 1.
3. Use any finishing move
4. CP will drop by 1 only. (5->4, 4->3, 3->2, etc.)
5. Effect of finishing move at 1 cp will occur. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
https://github.com/TrinityCore/TrinityCore/releases/tag/TDB703.00
**Operating system:**  
windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by matukaa** [comment]
Also, damage/duration calculation is incorrect for CP spenders. Not only for rogues but for druids as well

**Comment by Shauren** [comment]
That should be directly related to consuming 1 CP

**Comment by matukaa** [comment]
yea, sorry I didn't link it, I just wanted to mention that too :)

**Comment by ArcaneFox** [comment]
I don't know if it helps but Ruture and Kidney Shot is always consuming 1 CP but the duration is nearly* correct. (Tested with a level 40 character.)

Ruture example
> http://www.wowhead.com/spell=1943/rupture

5 CP + Ruture = 20 sec (246 dmg)
4 CP + Ruture = 16 sec (246 dmg)
3 CP + Ruture = 12 sec (246 dmg)
2 CP + Ruture =  8 sec (246 dmg)
1 CP + Ruture =  4 sec (246 dmg)

*4 CP should be 20 sec; 3 CP should be 16 sec; etc
