### ISSUE TITLE
[3.3.5] Core/Spells: SpellRange: (Id 1) "Self Only"

### ISSUE THREAD

**Issue by Cannix** [TrinityCore/TrinityCore#18342]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Range issues with spells with SpellRange: (Id 1) "Self Only".

**Current behaviour:** (Tell us what happens.)
Spells with SpellRange: (Id 1) "Self Only" are only able to be casted on targets within 2.5 (distance calculated in Spell::GetMinMaxRange) yards, otherwise they will fail in SpellCastResult Spell::CheckRange(bool strict). For example the priest talent 47930 Grace only applies on targets within short range although it should proc on every range.

**Expected behaviour:** (Tell us what should happen instead.)
I don't know in which situations  exactly the range check should be ignored, but for example 47930 Grace or 60474, Exit Portal related to Eye of Eternity.

**Steps to reproduce the problem:**

1.  Create priest and skill talent Grace.
2.  Use Flash Heal (2061) on a different player
3.  Use varying distances

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
8fe85017125803a4ca8fd1d972b128930cd364b9

**TDB version:**  
TDB 335.61

**Operating system:**  
Debian, Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
update you core before reporting range bugs.

**Comment by Cannix** [comment]
Yeah, you are right, was fixed in 6c7cf99594d30d11d2f8ab654ea7d48845f1d777
But shouldn't be there a core solution for this case instead of overwriting the range entry for each spell?

SpellCastResult Spell::CheckRange(bool strict)
    if (m_spellInfo->RangeEntry)
    {
        // check needed by 68766 51693 - both spells are cast on enemies and have 0 max range
        // these are triggered by other spells - possibly we should omit range check in that case?
        **if (m_spellInfo->RangeEntry->ID == 1)
            return SPELL_CAST_OK;**

        range_type = m_spellInfo->RangeEntry->type;
    }

Was removed in e6a52d4aae9e8facc46c3b05e0560d540a928d73

**Comment by ariel-** [comment]
Please see https://github.com/TrinityCore/TrinityCore/issues/17545#issuecomment-246825963 for rationale on why these lines were removed and why they won't be restored.
