### ISSUE TITLE
[master] Warrior doesn't have slam at level 1 in action bar slot 2

### ISSUE THREAD

**Issue by Maibenrai** [TrinityCore/TrinityCore#18340]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Warrior doesn't have slam - http://www.wowhead.com/spell=1464/slam - at level 1 in action bar slot 2
http://pictshare.servebeer.com/a42b0a762e.jpg

**Current behaviour:** It is inserted there at level 2.

**Expected behaviour:** Warrior should have it on level 1. Compared to live Starter Edition.

**Steps to reproduce the problem:**

1. Create a level 1 warrior on current master branch
2. Open spellbook (P) and verify that the spell is available
3. Notice that the spell is not added to the action bar before reaching level 2.

**Branch(es):** master

**TC rev. hash/commit:**  e43529933fbedb02c9e4b636b6e1d9d94398e5e6

**TDB version:**  7.03

**Operating system:**  Debian 8.6 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Nyr97** [comment]
Invalid, fixed as of today.
![image](https://user-images.githubusercontent.com/30064812/152463229-492f8e02-345e-4018-b13c-717eb7187918.png)
