### ISSUE TITLE
[3.3.5] Decay / respawn timers do not account for Skinning

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18344]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

The CONF allows for changing the decay rate of corpses based on looted / unlooted state which when combined with the default respawn timer (triggered after decay) allows for controlling the speed at which instances repopulate and how often a world-based mob is available for farming.

Skinned corpses have no such timer so once they are skinned the default respawn timer is triggered thereby making farming skins extremely easy.

**Current behaviour:**

No additional timer for skinned corpses allows them to respawn too quickly.

**Expected behaviour:**

There should be a separate *Corpse.Decay.Skinned* option that triggers a timer when the creature is skinned. This timer would act as a hidden decay that gets added to the default respawn timer to bring skinned corpse respawn in line with other corpse types.

**Steps to reproduce the problem:**

1. Skin a creature
2. Loot a different creature
3. Notice which respawns faster

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  All (2db9269ec1c06b5fccc45dc0a5b4f714f9b48804)

**TDB version:**  N/A (TDB_full_world_335.61_2016_04_11 + updates)

**Operating system:**  WinXP / Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
This is no longer valid as the corpse decay is no longer used into the respawn time.
