### ISSUE TITLE
[Master] Monk's Zen Pilgrimage:return casts but does not return character to origin

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18349]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** [Zen Pilgrimage: Return](http://www.wowhead.com/spell=126895/zen-pilgrimage-return) is broken.

**Current behaviour:** (Tell us what happens.)
Zen Pilgrimage when cast ports to intended location.
However, [Zen Pilgrimage: Return](http://www.wowhead.com/spell=126895/zen-pilgrimage-return) casts but does nothing afterwards.

**Expected behaviour:** (Tell us what should happen instead.)
[Zen Pilgrimage: Return](http://www.wowhead.com/spell=126895/zen-pilgrimage-return) ports player back to where he/she cast [Zen Pilgrimage](http://www.wowhead.com/spell=200617/zen-pilgrimage).

**Steps to reproduce the problem:**

1. Cast Monk's [Zen Pilgrimage](http://www.wowhead.com/spell=200617/zen-pilgrimage)
2. Be teleported
3. Cast Monk's [Zen Pilgrimage: Return](http://www.wowhead.com/spell=126895/zen-pilgrimage-return)
4. No teleport back to starting point

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:**  9b006e511bf40020e1660adf290ceb6ed6f4fd86

**TDB version:**  703.00

**Operating system:**  windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Nyr97** [comment]
As of today, this spell is working correctly.
