### ISSUE TITLE
Core/Vehicle: [CRASH] Vehicle::RemovePassenger

### ISSUE THREAD

**Issue by Elron103** [TrinityCore/TrinityCore#18345]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The function Vehicle::RemovePassenger can cause crashes when there is instant despawning of the vehicle involved.

**Current behaviour:** (Tell us what happens.)
In the function Vehicle::RemovePassenger the line
`_me->ToCreature()->AI()->PassengerBoarded(unit, seat->first, false);`
can indirectly cause crashes.

There are some AIs (for example SAI scripts) that perform an instant despawn of the NPC if the passenger leaves the vehicle. The instant despawn of the vehicle causes nearly all pointers to get invalid (not NULL!) in this situation: _me, this, GetBase() all return invalid pointers.

Therefore, the next access to GetBase() in the line
`if (GetBase()->GetTypeId() == TYPEID_UNIT)`
causes an access to an invalid pointer, which results in a crash.

**Expected behaviour:** (Tell us what should happen instead.)
Of course the crash should not happen. But this is difficult to achieve because of multiple reasons:

- Avoiding instant despawn calls in all AIs is rather a hack than a solution

- It is also not directly possible to force some delay for this scenario (e.g. in DespawnOrUnsummon) because it can easily happen to have infinite delayed calls then

- Directly solving all accesses to invalidated pointers at that code place is difficult as well because it is not easy to detect the invalid pointers and in addition to that the function returns "this" and there are even more accesses to the same invalidated pointers in other code places that cause these calls.

Call Stack:

```
Object::GetTypeId()
Vehicle::RemovePassenger(Unit * unit)
Unit::_ExitVehicle(const Position * exitPosition)
AuraEffect::HandleAuraControlVehicle(const AuraApplication * aurApp, unsigned char mode, bool apply)
AuraEffect::HandleEffect(AuraApplication * aurApp, unsigned char mode, bool apply)
AuraApplication::_HandleEffect(unsigned char effIndex, bool apply)
Unit::_UnapplyAura(std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,AuraApplication *> > > > & i, AuraRemoveMode removeMode)
Unit::RemoveAllAurasOnDeath()
Unit::setDeathState(DeathState s)
Creature::setDeathState(DeathState s)
Unit::Kill(Unit * victim, bool durabilityLoss)
misc_commandscript::HandleDieCommand(ChatHandler * handler, const char * __formal)
ChatHandler::ExecuteCommandInTable(const std::vector<ChatCommand,std::allocator<ChatCommand> > & table, const char * text, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & fullcmd)
ChatHandler::ParseCommands(const char * text)
WorldSession::HandleMessagechatOpcode(WorldPacket & recvData)
WorldSession::Update(unsigned int diff, PacketFilter & updater)
World::UpdateSessions(unsigned int diff)
World::Update(unsigned int diff)
WorldUpdateLoop()
main(int argc, char * * argv)
```

**Steps to reproduce the problem:**
.go cr id 27292
.q a 12259
Use NPC gossip
Target your spawned vehicle
.die

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
8fe8501

**TDB version:**  
 TDB 335.61

**Operating system:**  
 Debian, Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
cannot reproduce on  0663e6a180fe

**Comment by Aokromes** [comment]
also update you core before reporting bugs.

**Comment by jackpoz** [comment]
> because it is not easy to detect the invalid pointers

it's not supported by the C++ language to detect invalid pointers (leaving aside any black magic __try/__except)
