### ISSUE TITLE
[Master] Paladin Ability: Templar's Verdict (85256)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18353]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Using Templar's Verdict results in an animation but no effect.
**Current behaviour:** (Tell us what happens.)
Templar's Verdict shows animation and expends holy charge (power), beginning auto attack vs. target enemy but dealing no damage itself.
http://imgur.com/a/qttVW
**Expected behaviour:** (Tell us what should happen instead.)
Templar's Verdict deals damage to target according to tooltip.
**Steps to reproduce the problem:**

1. Learn Templar's Verdict on paladin player
2. Gather 3 Holy Charge
3. Use Templar's Verdict on enemy.
4. See animation and holy charge diminish but no effect.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Ulduar** [comment]
http://ru.wowhead.com/spell=85256#changelog
Changed in Legion and have Dummy Effect.
I don't sure, but.

``` CPP
// 85256 - Templar's Verdict
/// Updated 7.x
class spell_pal_templar_s_verdict : public SpellScriptLoader
{
    public:
        spell_pal_templar_s_verdict() : SpellScriptLoader("spell_pal_templar_s_verdict") { }

        class spell_pal_templar_s_verdict_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_pal_templar_s_verdict_SpellScript);

            bool Validate (SpellInfo const* /*spellEntry*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_PURPOSE_PROC))
                    return false;

                return true;
            }

            bool Load() override
            {
                if (GetCaster()->GetTypeId() != TYPEID_PLAYER)
                    return false;

                if (GetCaster()->ToPlayer()->getClass() != CLASS_PALADIN)
                    return false;

                return true;
            }

            void ChangeDamage(SpellEffIndex /*effIndex*/)
            {
                Unit* caster = GetCaster();
                Unit* target= GetTarget();
                int32 damage = GetHitDamage();

                if (caster->HasAura(SPELL_PALADIN_DIVINE_PURPOSE_PROC))
                    damage *= 14;  // 14*30% = 440%
                else
                {
                    switch (caster->GetPower(POWER_HOLY_POWER))
                    {
                        case 0: // 1 Holy Power
                            // same damage
                            break;
                        case 1: // 2 Holy Power
                            damage *= 3;    // 3*30 = 90%
                            break;
                        case 2: // 3 Holy Power
                            damage *= 14;  // 14*30% = 440%
                            break;
                    }
                }
               caster->CastCustomSpell(target, 224266, &basepoints, &basepoints, NULL, true, NULL, aurEff);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_pal_templar_s_verdict_SpellScript::ChangeDamage, EFFECT_0, SPELL_EFFECT_WEAPON_PERCENT_DAMAGE);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_pal_templar_s_verdict_SpellScript();
        }
};
```
SpellScript can be affected and for 138165 (Paladin T15 Retribution 4P Bonus)

**Comment by menevia16a** [comment]
On Master branch it doesn't take away holy charge but also doesn't work.

**Comment by Nyr97** [comment]
Invalid report, the spell works correctly.
