### ISSUE TITLE
[NPC]Lady Sylvanas Windrunner

### ISSUE THREAD

**Issue by dusiak** [TrinityCore/TrinityCore#1835]
Core Revision: a1ed5628aa91288aa718
Database: TDB 335.11.40
custom patches: none

creatureID: 10181
quest: 9180

After turning in the quest http://old.wowhead.com/quest=9180 to Sylvanas she starts the Lament of the Highborne event. She becomes unresponsive to players and after some time she gets teleported high above Undercity where she floats in the air.

Suggested fix:
(sylvanas will no longer get relocated, the summoned bunnies will and Sylvanas will update her AI properly)

```
diff --git a/src/server/scripts/EasternKingdoms/undercity.cpp b/src/server/scripts/EasternKingdoms/undercity.cpp
index ea78f08..cc9bb07 100644
--- a/src/server/scripts/EasternKingdoms/undercity.cpp
+++ b/src/server/scripts/EasternKingdoms/undercity.cpp
@@ -110,7 +110,7 @@ public:
                 if (Unit *pTarget = Unit::GetUnit(*summoned, targetGUID))
                 {
                     pTarget->SendMonsterMove(pTarget->GetPositionX(), pTarget->GetPositionY(), me->GetPositionZ()+15.0f, 0);
-                    pTarget->GetMap()->CreatureRelocation(me, pTarget->GetPositionX(), pTarget->GetPositionY(), me->GetPositionZ()+15.0f, 0.0f);
+                    pTarget->GetMap()->CreatureRelocation(summoned, pTarget->GetPositionX(), pTarget->GetPositionY(), me->GetPositionZ()+15.0f, 0.0f);
                     summoned->CastSpell(pTarget, SPELL_RIBBON_OF_SOULS, false);
                 }
 

```

**Comment by danlapps** [comment]
Is this still a valid issue ?

**Comment by Killyana** [comment]
It will be closed with this: https://github.com/TrinityCore/TrinityCore/pull/14094

**Comment by Nyeriah** [comment]
Actually this issue is invalid, probably has been fixed god knows when. I'll just go ahead and close it since the issue reported on the original ticket doesn't exist anymore
