### ISSUE TITLE
[3.3.5a] Deathguard Kel

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#18356]
**Description:**
Per #17075, there were problems with the early Priest quests. It looks like some fix was pushed at that time, but that did not affect Deathguard Kel who does still not give credit for the Undead Priest quest.
**Current behaviour:** (Tell us what happens.)
Healing Deathguard Kel and buffing him with Blessing of Fortitude should grant quest credit.
**Expected behaviour:** (Tell us what should happen instead.)
It doesn't.
**Steps to reproduce the problem:**

1. Create an Undead Priest and level up to the appropriate level.
2. Get the quest Garments of Darkness, ID 5650.
3. Attempt to complete the quest objective by healing and buffing Deathguard Kel (at 59,47 in Tirisfal Glades).

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5a for sure, but couldn't tell you whether the quest exists on master or not.
**TC rev. hash/commit:**  
b333c92
**TDB version:**  
whatever comes with b333c92
**Operating system:**  
Ubuntu 16.04 LTS

**Comment by Tauriella** [comment]
@velinath using Lesser Heal (Rank 2). Afterwards, grant him Power Word: Fortitude

PS:Quest works perfect

**Comment by tkrokli** [comment]
TrinityCore rev. 62e97c45518a 2016-11-30 14:41:38 +0100 (3.3.5 branch) (Win64, Release, Static)

![wowscrnshot_113016_205955](https://cloud.githubusercontent.com/assets/4903600/20769129/fe0b4800-b740-11e6-8bf2-7f8031c36443.jpg)
![wowscrnshot_113016_210200](https://cloud.githubusercontent.com/assets/4903600/20769154/1570b318-b741-11e6-9867-4251f674bb6a.jpg)
![wowscrnshot_113016_210215](https://cloud.githubusercontent.com/assets/4903600/20769172/25bf883e-b741-11e6-8a9f-60f1b9cc16ea.jpg)
![wowscrnshot_113016_210220](https://cloud.githubusercontent.com/assets/4903600/20769183/2f284e10-b741-11e6-92de-5a6c7c2dde4b.jpg)
![wowscrnshot_113016_210235](https://cloud.githubusercontent.com/assets/4903600/20769192/385a8ca0-b741-11e6-8ca9-0e4eb6f99000.jpg)

I cannot replicate the issue. Lesser Heal (Rank 2) + Fortitude (Rank 1) works as expected & intended for me.

**Comment by velinath** [comment]
Yeah, I can't repro this either, sorry guys.
