### ISSUE TITLE
[Master] Quest: Rite of Winds (24215)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18355]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Unable to drink Water of Vision (49652) when next to Dyami Windsoar (36803).
**Current behaviour:** (Tell us what happens.)
When trying to complete Rite of Winds, player is unable to drink Water of Vision even when next to Dyami windsoar.
http://imgur.com/a/16OLd
**Expected behaviour:** (Tell us what should happen instead.)
Player can drink water of vision when next to dyami windsoar and transform into a bird.
**Steps to reproduce the problem:**

1. Play Tauren PC
2. Complete Quest Chain beginning with BattleBoars (14459) up until Rite of Winds
3. Begin Rite of Winds
4. Stand next to Dyami Windsoar
5. Use Water of Vision 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
#18262
