### ISSUE TITLE
[Master] Northshire Vineyard's Fire Trigger

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18351]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Visible Northshire Vineyard's Fire Trigger.
**Current behaviour:** (Tell us what happens.)
The Northshire Vineyard's Fire Trigger (located in northshire vineyards) can be seen with gm mode off.
http://imgur.com/a/1is3X
**Expected behaviour:** (Tell us what should happen instead.)
The Fire trigger should be invisible to all but gm's)
**Steps to reproduce the problem:**

1.  Create a human player
2.  Walk to Northshire Vineyards
3.  Can see Fire Triggers standing on fences.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Naddley** [comment]
works.
