### ISSUE TITLE
[Master] Quest:Something's Amiss

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18350]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Can't complete Quest:something's amiss (id: 14091), obtain followup quests, and worgen npcs don't spawn.
**Current behaviour:** (Tell us what happens.)
Worgen's don't begin attacking and Prince Liam Greymane (34913) doesn't offer quest completion dialogue for Something's amiss (14091). Following quest reward through commands, Prince Liam Greymane fails to offer follow up quests.
**Expected behaviour:** (Tell us what should happen instead.)
Following lockdown! (14078) (first quest in worgen starting area) and recieving Something's amiss from lieutenant walden (34863), player should be able to see worgen's spawning and complete Something's amiss by talking to prince liam greymane.
**Steps to reproduce the problem:**

1.  Create worgen pc
2.  Start and complete lockdown!
3.  Receive Something's amiss.
4.  Inability to complete by talking to prince liam greymane.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
9b006e511bf40020e1660adf290ceb6ed6f4fd86
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
#11201
