### ISSUE TITLE
[Master] Quest: Proving Pit (26276) / NPC: Darkspear Jailor (39062) - dialogue

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18368]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The troll intro questline results in a bug when interacting with the darkspear jailor for the quest proving pit. The darkspear jailor should open the cage containing a creature for the player to kill.
**Current behaviour:** (Tell us what happens.)
Talking to the darkspear jailor and clicking the dialogue button results in no effect.
On closing dialogue, console reads:
Received not handled opcode [CMSG_CLOSE_INTERACTION 0x3492 (13458)] from [Player: Trollwarlock GUID Full: 0x08000400000000000000000000000012 Type: Player Entry: 0 Low: 18, Account: 2]
http://imgur.com/a/nT8id
**Expected behaviour:** (Tell us what should happen instead.)
Talking to the darkspear troll and clicking the dialogue should result in the npc moving to the cage, opening it, and causing the enemy to enter the pit.
**Steps to reproduce the problem:**

1.  Begin quest 26276
2.  Talk to the Darkspear Jailor (39062)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
**TC rev. hash/commit:**  
c6bc131b36dea28e3a134fdb08052f4b48891792
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
#11706
