### ISSUE TITLE
[master] Death Knight spell: Death Grip (49576) - no movement script

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18365]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Death Knight spell [Death Grip](http://www.wowhead.com/spell=49576/death-grip), when cast on an enemy, should pull the enemy to you.
Tested on Worgen Death Knight

**Current behaviour:** (Tell us what happens.)
Casting [Death Grip](http://www.wowhead.com/spell=49576/death-grip) on an enemy shows the animation, but the enemy is not pulled to you.
http://imgur.com/a/SLxVW

**Expected behaviour:** (Tell us what should happen instead.)
The enemy should be pulled upward in a parabola shape and land in front of the PC.

**Steps to reproduce the problem:**

1.  `.learn 49576`
2.  cast [Death Grip](http://www.wowhead.com/spell=49576/death-grip)
3.  Observe

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:**  9b006e511bf40020e1660adf290ceb6ed6f4fd86

**TDB version:**  703.00

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by aquadeus** [comment]
this is fixed and works fine close this 😄
