### ISSUE TITLE
[Master] Quest: Runeforging: Preparation For Battle (12842) - task auto complete

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18361]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** In the quest [Runeforging: Preparation For Battle](http://www.wowhead.com/quest=12842/runeforging-preparation-for-battle), the DK player is tasked with using the newly acquired Runeforging skill (960) on their weapon to learn about runeforging. This quest is bugged.

**Current behaviour:** (Tell us what happens.)
DK player can complete the quest without performing the necessary requirements. The quest task is automatically completed when obtaining the quest. Can complete the quest immediately afterwards.
http://imgur.com/a/Qb2IO

**Expected behaviour:** (Tell us what should happen instead.) 
DK player is required to cast enchantment on weapon to complete quest.

**Steps to reproduce the problem:**

1.  Create a Death Knight
2.  Complete quest chain up to [Runeforging: Preparation For Battle](http://www.wowhead.com/quest=12842/runeforging-preparation-for-battle)
3.  Begin quest

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:**  9b006e511bf40020e1660adf290ceb6ed6f4fd86

**TDB version:**  703.00

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15216
