### ISSUE TITLE
[3.3.5a] Blink can be casted even while disoriented or frozen

### ISSUE THREAD

**Issue by chaodhib** [TrinityCore/TrinityCore#18366]
**Description:**
Mages can cast Blink even when CCed. I know that blink break stuns and roots but it can be casted even under the effects of Scatter Shot (Hunter) and Freezing Arrow (Hunter). In both case, the mage successfully changes position but the CC stays active, even after the Blink.

**Current behaviour:** Mages can cast Blink while under the effect of Scatter Shot or Freezing Arrow.

**Expected behaviour:** The spell should fail.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  
b049caf62fff5c8196a1ccc4ac4e825a97660eab

**Comment by Noryad** [comment]
Confirmed in 3d5c1b8.
Mage can cast Blink under effects Fear or Sap and should not.
