### ISSUE TITLE
[3.3.5] Spell/Druid: Cyclone not work properly with Divine Shield / Ice block

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18370]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Divine Shield: **Protects the paladin from all damage and spells** for 12 sec ...
The problem: Cyclone of druid affects a paladin with divine shield.

**Current behaviour:**
Cyclone of druid affects a paladin with divine shield.

**Expected behaviour:** 
The paladin with Divine Shield must be immune to the Cyclone.

**Steps to reproduce the problem:**
1. Paladin casts Divine Shield.
2. Druid casts Cyclone to Paladin.
3. Paladin with Divine Shield is in Cyclone.

Note the same occur with Ice Block (mage).

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  b049caf

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Cyclone has SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE and Divine Shield is School immunity... expected result?

**Comment by Noryad** [comment]
http://wow.gamepedia.com/Divine_Shield
http://wowwiki.wikia.com/wiki/Divine_Shield
Divine Shield protects the paladin from all unfriendly spells then cyclone should be inmune. Is important to validate that Divine Shield cannot be cast under the effect of Cyclone and similar effects.

**Comment by ariel-** [comment]
Note, there are spells that divine shield cannot protect against (for example http://www.wowhead.com/spell=70063)

**Comment by Noryad** [comment]
The same problem occour with Ice Block (mage). then:
1- Divine Shield/Ice Block can not be casted under the effect of Cyclone.
2- Cyclone should be inmune to targets under effect of Divince Shield/Ice Block

**Comment by Xiledria** [comment]
Fury of Frostmourne has different spell attribute - SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY

and now it is possible to dispel it even without mass dispel with Dispel Magic (which does not even have spell attrr to be unaffected by invulnerability / immunity)

I guess it should have something to do with effect value 0 / 1, because divine shield has 2 SPELL_AURA_SCHOOL_IMMUNITY, I guess one of them is immunity and the second one is invulnerability which prevents even spells with SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE or something like that :D

**Comment by Noryad** [comment]
The same proble occour with Ice Block (mage), then:
1- Cyclone can not be casted to targets under effect of Divine Shield / Ice Block.
2- Divine Shield / Ice Block can not be casted under effect of Cyclone. Actually when Divine Shield / Ice Block is casted nothing occour but the ability is put into cooldown and should not.

**Comment by Noryad** [comment]
Catapults in Strand of the Ancients can receive cyclone too.

**Comment by Shauren** [comment]
Being able to cast cyclone on divine shield (which is what the bug is about) has nothing to do with being able to cast divine shield while cycloned. These two checks should not be using the same logic. Similarly to how DK Anti-Magic shell prevents debuff applications but does not dispel them.

**Comment by Noryad** [comment]
Another important observation. 
If the druid  casts cyclone to a target and re-casts cyclone, the second should be immune if the target is under the effects of the first cyclone.

**Comment by Noryad** [comment]
Another important observation.
If the druid casts cyclone to a target and re-casts cyclone, the second should be immune if the target is under the effects of the first cyclone. It is very similar in mechanics to [Banish].

**Comment by Shauren** [comment]
No, don't compare it to Banish, that one has a special case - if you recast Banish on the same target, it unbanishes it

**Comment by ariel-** [comment]
> No, don't compare it to Banish, that one has a special case - if you recast Banish on the same target, it unbanishes it

And, incidentally, this mechanic works correctly

**Comment by ariel-** [comment]
About the dispel magic dispelling Divine Shield... its again about possitivity spell check, previous system did check possitivity only in IsImmunedToSpell, Dispel Magic was immuned in IsImmunedToDamage (albeit wrongly, because dispel magic is no damage spell).

It will require to rewrite the whole possitive/negative stuff depending on both spell effect and target (because spells like this can be both)

**Comment by Shauren** [comment]
There is nothing accidental in banish working - https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_warlock.cpp#L89

**Comment by Noryad** [comment]
Also Dispel Magic is dispeling Ice block. To rewrite the whole possitive/negative stuff is not an easy task.

**Comment by Noryad** [comment]
Cyclone tosses the enemy target into the air, preventing all action but making them invulnerable for up to 6 sec... In current revision when the target is under effects of cyclone and the druid casts cyclone again, the target is affected. Is this mechanism correct? Should be immune to the next cyclone?

**Comment by Jildor** [comment]
#5130

**Comment by Keader** [comment]
Cylone in clycloned targets should get immune result
