### ISSUE TITLE
Resurrection spirit in Northshire Valley is missing.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18376]
**Description:**
When you die in Norhtshire Valley there is no spirit of resurrection.
**Current behaviour:** (Tell us what happens.)
When you die in Norhtshire Valley there is no spirit of resurrection.
**Expected behaviour:** (Tell us what should happen instead.)
When you die the spirit most be there.
**Steps to reproduce the problem:**

1. Create a Human
2. Die
3. No resurrection Spirit

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
2c5474e319da0a24b704c1a3521be4876d7a4da3
**TDB version:**  
7.0.3 + updates
**Operating system:**  
Windows 10

**Comment by tkrokli** [comment]
Related to issue [**[master] DB/graveyard: Night Elf start zone GY: Westfall (Sentinel Hill)**](18432) #18432

**Comment by tkrokli** [comment]
Closed in https://github.com/TrinityCore/TrinityCore/commit/137b250857223c96e99873014340df0a1af32fc6 (via #18432).
