### ISSUE TITLE
Quest "Beating them back" can not complete.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18377]
Description:
In the Human start zone the first mission can not be delivered to Marshal McBride
The console show:
"Error in CMSG_QUESTGIVER_CHOOSE_REWARD: player Lucia (GUID Full: 0x0800040000000000000000000000000F Type: Player Entry: 0 Low: 15) tried to get reward item (Item Entry: 57255) wich is not a reward for quest 28762 (possible packet-hacking detected)"

Current behaviour: (Tell us what happens.)
The requirements for the mission are obtained and completed but can not be delivered to the npc.

Expected behaviour: (Tell us what should happen instead.)
To be able to deliver the mission and obtain the reward.

Steps to reproduce the problem:

1- Take quest 28762 from Marshal McBride
2- Complete quest
3- Deliver the quest to Marshal McBride

Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
TC rev. hash/commit:
2c5474e319da0a24b704c1a3521be4876d7a4da3
TDB version:
7.0.3 + updates
Operating system:
Windows 10

**Comment by offl** [comment]
#18223
