### ISSUE TITLE
[3.3.5a] Core/Spell: Focus is not cleared if the cast is interrupted

### ISSUE THREAD

**Issue by Tonghost** [TrinityCore/TrinityCore#18373]
Rel. #16572
190fdfd

![1](https://cloud.githubusercontent.com/assets/13364438/20805503/9c999364-b7ff-11e6-90b0-3da2cb901063.jpg)
![2](https://cloud.githubusercontent.com/assets/13364438/20805500/99f5bcf0-b7ff-11e6-9c8f-877bf465daca.jpg)
![3](https://cloud.githubusercontent.com/assets/13364438/20805502/9b2d89f4-b7ff-11e6-9f98-52e48dec98f1.jpg)

**Comment by tkrokli** [comment]
Please include your `TrinityCore rev.` line from your Worldserver console, either line 1 or last startup line.

**Comment by Tonghost** [comment]
@tkrokli 
190fdfd

**Comment by tkrokli** [comment]
Right. Sorry, I didn't notice that you put it in your comment in the other issue. It is still recommended to put it in the original issue post, as well as using the issue template to describe the issue. I suppose you used images to explain it if your English isn't good enough to explain it properly. Anyway, testing the issue now.

**Comment by tkrokli** [comment]
TC>TrinityCore rev. 190fdfdf63c0 2016-12-01 11:48:13 -0300 (3.3.5 branch) (Win64, Release, Static) / TDB 335.62

I can partially reproduce your issue with a random level 1 alliance character (Draenei male shaman). I tested both of the Sunreaver Guardian Mage guards, the male guard (on your right hand side as you try to enter) releases his focus after teleporting the alliance character onto the sewer cover / manhole cover every time.

The female guard (to your left as you try to enter the Sunreaver's Sanctuary), on the other hand, only releases her focus after the first attempt (or first 2), but then she seems to get her focus stuck on you.

You can also make the male guard face the wrong way after a row of attempts at entering Sunreaver's Sanctuary, but also make him turn back the right way after repeating the trespassing attempt some more.

**Comment by Killyana** [comment]
This issue could also happen with many boss like Lana'thel, Saurfang, Sindragosa ect..., so it's not related to the AI.
The easiest way to reproduce the issue is: http://i.imgur.com/xOqPme9.jpg
The npc keep the focus event if the target is dead or on gm mode.

**Comment by Killyana** [comment]
Caused by: https://github.com/joshwhedon/WayOfElendil/commit/f481ae1048aac32ba3a40491f0304d0317234295#diff-067cd3e9b67215292b6f3b62d0b30011
probably related to MustReacquireTarget() and ReleaseFocus()

**Comment by ccrs** [comment]
wrong repo on that link

**Comment by Killyana** [comment]
Corrected.

**Comment by TheWinchesters** [comment]
I am sorry that I could not undertand this 100% (Language issues)
Is this issue reporting the problem that these guards get 'stuck' and cast "Tresspaser" to every alliance player that goes nearby? Sometimes they are in a loop casting the spell all the time.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5016f588d5f20ef8eb0f3da9c3c92bbac8e132ee

**Comment by Killyana** [comment]
This is not fixed you can reproduce the issue with any npc by using gm on during the cast of a spell.

**Comment by Killyana** [comment]
The issue is back

**Comment by jackpoz** [comment]
are the exact same repro steps as before still valid ? or are there new repro steps ?

**Comment by Killyana** [comment]
Yes

**Comment by Killyana** [comment]
Initial work by @Ovahlord 
``` diff
diff --git a/src/server/game/AI/CreatureAI.cpp b/src/server/game/AI/CreatureAI.cpp
index f084fe547d..ba0a3cbdfb 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -309,6 +309,7 @@ bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
     me->SetLastDamagedTime(0);
     me->SetCannotReachTarget(false);
     me->DoNotReacquireSpellFocusTarget();
+    me->SetTarget(ObjectGuid::Empty);
     EngagementOver();
 
     return true;
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index b399af92b1..8b97d2c1f4 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -3036,11 +3036,11 @@ void Creature::SetTarget(ObjectGuid guid)
 
 void Creature::SetSpellFocus(Spell const* focusSpell, WorldObject const* target)
 {
-    // already focused
-    if (_spellFocusInfo.Spell)
+    // Pointer validation and checking for a already existing focus
+    if (_spellFocusInfo.Spell || !focusSpell)
         return;
 
-    // Prevent dead/feigning death creatures from setting a focus target, so they won't turn
+    // Prevent dead / feign death creatures from setting a focus target
     if (!IsAlive() || HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH) || HasAuraType(SPELL_AURA_FEIGN_DEATH))
         return;
 
@@ -3058,7 +3058,8 @@ void Creature::SetSpellFocus(Spell const* focusSpell, WorldObject const* target)
     if (spellInfo->HasAura(SPELL_AURA_CONTROL_VEHICLE))
         return;
 
-    if ((!target || target == this) && !focusSpell->GetCastTime()) // instant cast, untargeted (or self-targeted) spell doesn't need any facing updates
+    // instant non-channeled casts and non-target spells don't need facing updates
+    if (!target && (!focusSpell->GetCastTime() && !spellInfo->IsChanneled()))
         return;
 
     // store pre-cast values for target and orientation (used to later restore)
@@ -3174,6 +3175,12 @@ void Creature::ReacquireSpellFocusTarget()
     _spellFocusInfo.Delay = 0;
 }
 
+void Creature::DoNotReacquireSpellFocusTarget()
+{
+    _spellFocusInfo.Delay = 0;
+    _spellFocusInfo.Spell = nullptr;
+}
+
 bool Creature::IsMovementPreventedByCasting() const
 {
     // first check if currently a movement allowed channel is active and we're not casting
diff --git a/src/server/game/Entities/Creature/Creature.h b/src/server/game/Entities/Creature/Creature.h
index e853044638..fe594332f7 100644
--- a/src/server/game/Entities/Creature/Creature.h
+++ b/src/server/game/Entities/Creature/Creature.h
@@ -341,7 +341,7 @@ class TC_GAME_API Creature : public Unit, public GridObject<Creature>, public Ma
 
         // Handling caster facing during spellcast
         void SetTarget(ObjectGuid guid) override;
-        void DoNotReacquireSpellFocusTarget() { _spellFocusInfo.Delay = 0; }
+        void DoNotReacquireSpellFocusTarget();
         void SetSpellFocus(Spell const* focusSpell, WorldObject const* target);
         bool HasSpellFocus(Spell const* focusSpell = nullptr) const override;
         void ReleaseSpellFocus(Spell const* focusSpell = nullptr, bool withDelay = true);
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 5e05fd2f91..4c2f4e8c2d 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4552,10 +4552,10 @@ void Spell::SendChannelStart(uint32 duration)
     {
         unitCaster->SetChannelObjectGuid(channelTarget);
 
-        if (channelTarget != unitCaster->GetGUID())
-            if (Creature* creatureCaster = unitCaster->ToCreature())
-                if (!creatureCaster->HasSpellFocus(this))
-                    creatureCaster->SetSpellFocus(this, ObjectAccessor::GetWorldObject(*creatureCaster, channelTarget));
+        if (Creature* creatureCaster = m_caster->ToCreature())
+            if (!creatureCaster->HasSpellFocus(this))
+                creatureCaster->SetSpellFocus(this,
+                    ObjectAccessor::GetWorldObject(*creatureCaster, channelTarget));
     }
 
     unitCaster->SetUInt32Value(UNIT_CHANNEL_SPELL, m_spellInfo->Id);

**Comment by illfated** [comment]
Looks interesting, could we incorporate that code in a TC test server?

**Comment by Killyana** [comment]
The issue was reintroduced when this line was removed: https://github.com/TrinityCore/TrinityCore/commit/4a219eda07c353139608065f7d0a016094ee4ce0#diff-0d57662d3c1d09b939fdcd1b7d799a2fL348

**Comment by Killyana** [comment]
This a hack, SetTarget(ObjectGuid::Empty) must be called somewhere else, probably by DoNotReacquireSpellFocusTarget()
``` diff
diff --git a/src/server/game/AI/CreatureAI.cpp b/src/server/game/AI/CreatureAI.cpp
index 5f1d13e047..791c53dba3 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -310,6 +310,7 @@ bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
     me->SetLastDamagedTime(0);
     me->SetCannotReachTarget(false);
     me->DoNotReacquireSpellFocusTarget();
+    me->SetTarget(ObjectGuid::Empty);
     me->GetSpellHistory()->ResetAllCooldowns();
     EngagementOver();
