### ISSUE TITLE
Ra.MinLevel is ignored in worldserver.conf

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#18386]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Console reports that **RA.MinLevel** is missing in **worldserver.conf** but **Ra.MinLevel** exists. Adding **RA.MinLevel** (uppercase A) removes the error.

**Current behaviour:** Ra.MinLevel (lowercase a) is ignored, console requests RA.MinLevel (uppercase A) be added to worldserver.conf

**Expected behaviour:** Ra.MinLevel should be noticed

**Steps to reproduce the problem:**

1. Set **Ra.Enable = 1** in **worldserver.conf**
2. Start **worldserver**
3. Connect to **worldserver** over telnet
4. Check console

**Branch:** 3.3.5 (not tested on other branch(es)

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/7e0a6166576304b98fac246192cf1ce23c74f915

**TDB version:**  335.62

**Operating system:**  Fedora Server 25

**Comment by Aokromes** [comment]
3.3.5a is startup error free for me.

**Comment by Espionage724** [comment]
worldserver only shows the message for me after I connect with telenet (it doesn't appear on start-up of worldserver)
