### ISSUE TITLE
[Master] Paladin Spells: Lay on Hands (633)/Divine Shield (642)/Blessing of Protection (1022) - No forbearance (25771)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18384]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/spell=25771/forbearance
http://www.wowhead.com/spell=633/lay-on-hands
http://www.wowhead.com/spell=642/divine-shield
http://www.wowhead.com/spell=1022/blessing-of-protection
**Current behaviour:** (Tell us what happens.)
Casting lay on hands, divine shield, or blessing of protection does not apply debuff forbearance. Therefore, the paladin can cast all three in rapid succession
http://imgur.com/a/akmkU
**Expected behaviour:** (Tell us what should happen instead.)
Casting one of these three spells applies forbearance, preventing being target from the other two for 30 seconds.
**Steps to reproduce the problem:**

1. .learn 633
2. .learn 642
3. .learn 1022
4. cast all three in succession

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by streetrat** [comment]
missing server side spell.. add it to the hotfix db, it should work
