### ISSUE TITLE
[master] Paladin spell: Greater Blessing of Might (203528)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18382]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** http://www.wowhead.com/spell=203528/greater-blessing-of-might

**Current behaviour:** (Tell us what happens.)
Casting [Greater Blessing of Might](http://www.wowhead.com/spell=203528/greater-blessing-of-might) causes no buff and you deal no extra Holy damage.

http://imgur.com/a/Lrc4J

**Expected behaviour:** (Tell us what should happen instead.)
Casting [Greater Blessing of Might](http://www.wowhead.com/spell=203528/greater-blessing-of-might) gives buff to player.

**Steps to reproduce the problem:**

1. ` .learn 203528`
2. Cast on self

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:**  fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65

**TDB version:**  703.00

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Isn't it ironic? _"If you wait long enough, the problem goes away."_

http://wow.gamepedia.com/Greater_Blessing_of_Might
> The subject of this article was removed from World of Warcraft in patch 7.1.5.
> - This includes items and quests that can no longer be obtained or are now deprecated.
> - The in-game information in this article is kept purely for historical purposes and should probably not be under any other categories.

http://www.wowhead.com/spell=203528 [**This spell doesn't exist.**]
