### ISSUE TITLE
[Master] Death: Ammen Vale - Graveyard: Westfall (Sentinel Hill)

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18389]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Death in Ammen Vale teleports player to spirit healer in Westfall.

**Current behaviour:** (Tell us what happens.)
Dying in ammen vale moves the player to the graveyard in Sentinel Hill.
http://imgur.com/a/AgzCa

**Expected behaviour:** (Tell us what should happen instead.)
Dying in Ammen Vale moves the player to a graveyard in Ammen Vale.

**Steps to reproduce the problem:**

1. Create a Draenei player
2. .die on yourself
3. release spirit

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master

**TC rev. hash/commit:**  fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65

**TDB version:**  703.00

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. eba8ed329fc5 2016-12-07 23:24:32 +0100 (master branch) (Win64, Release, Static) / TDB 703.00

After using the GM command `.neargrave` a couple of times, I found that zone 6456 is not linked to a GY.
918 seems to be the only one matching, so an Alliance-only GY should look like this:
```sql
-- link Graveyard 918 to zone 6456 (Ammen Vale - unlinked zone)
DELETE FROM `graveyard_zone` WHERE `ID`= 918 AND `GhostZone`= 6456;
INSERT INTO `graveyard_zone` (`ID`,`GhostZone`,`Faction`,`Comment`) VALUES
(918, 6456, 469, 'Azuremyst Isle, Crash Site GY - Ammen Vale');
```
Tested in-game, it works as expected and intended. The ghost appears at the Crash Site GY in Ammen Vale.
