### ISSUE TITLE
[Master] Paladin Spell: Divine Steed (190784) - No Function

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18380]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/spell=190784/divine-steed
**Current behaviour:** (Tell us what happens.)
Casting the paladin spell: divine steed shows animation but has no effect. No mount, no speed buff.
http://imgur.com/a/JJhQD
**Expected behaviour:** (Tell us what should happen instead.)
Casting the paladin spell: divine steed places paladin on a mount which he/she can ride for 3 seconds with a speed buff.
**Steps to reproduce the problem:**

1. .learn 190784
2. cast spell

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Palabola** [comment]
1. Spell linked spell: 190784 -> 221883
2. Need fix to be useable in combat.
