### ISSUE TITLE
[Master] Paladin spell: Consecration (26573) - No function

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18381]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/spell=26573/consecration - no function
**Current behaviour:** (Tell us what happens.)
Casting the paladin spell: consecration has no effect. No consecration is cast underneath player and no damage is dealt. Animation, however is displayed.
http://imgur.com/a/xdlwJ
**Expected behaviour:** (Tell us what should happen instead.)
Consecration places a visible aoe underneath the player which causes holy damage to enemies
**Steps to reproduce the problem:**

1.  .learn 26573
2.  cast near enemy

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by matukaa** [comment]
Consecration is an Areatrigger, so we are waiting for Traesh to finish templates

**Comment by Aokromes** [comment]
#18035
