### ISSUE TITLE
[3.3.5] Paladin Spell don't proc

### ISSUE THREAD

**Issue by bahajan95** [TrinityCore/TrinityCore#18394]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/spell=53576/infusion-of-light
**Current behaviour:** (Tell us what happens.)
http://www.wowhead.com/spell=53576/ not proc
**Expected behaviour:** (Tell us what should happen instead.)
![5814722d5b61c](https://cloud.githubusercontent.com/assets/13211961/20858053/4cf65dd8-b95d-11e6-8c29-4045d320eeef.jpg)

at the critical hill the spell Holy shock should be proc http://www.wowhead.com/spell=53576/
**Steps to reproduce the problem:**

1. cast spell http://www.wowhead.com/spell=20473/holy-shock
2. Your Holy Shock criticals reduce the cast time of your next Holy Light by 1.5 sec or increase the healing of your next Flash of Light by 50%
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/46cb1083a5950d98933a68362c5563c1550a8cb1

**TDB version:**  TC tdb-62 + all updates

**Operating system:**  linux debian x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Re3os** [comment]
no't confirm rev https://github.com/TrinityCore/TrinityCore/commits/3.3.5
Update you core
![wowscrnshot_120516_185245](https://cloud.githubusercontent.com/assets/14326601/20889356/c06bc764-bb13-11e6-8ed0-ac3e5be099e5.jpg)

**Comment by Keader** [comment]
Yeap, tested 3d5c1b83b15cfc9f73888eb525c64323266c1fd4 and works normally ^^

**Comment by bahajan95** [comment]
big thanks
