### ISSUE TITLE
Lady Vashj fight - Toxic Sporebat problem

### ISSUE THREAD

**Issue by TheEvilPotato** [TrinityCore/TrinityCore#18390]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)
When Toxic sporebats (http://www.wowhead.com/npc=22140/toxic-sporebat) spawn in the Lady Vashj fight, they don't drop the posin bombs as intented. instead they just float there.
**Expected behaviour:** (Tell us what should happen instead.)
The sporebats should start dropping bombs as soon as they spawn
**Steps to reproduce the problem:**

1. Go to Lady Vashj
2. Fight her until her last phase
3. Watch Toxic Sporebats doing nothing

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5a
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/28050f338dfc66e0c40b6a3915bf96e38e0613e5
**TDB version:**  
62 with updates
**Operating system:**  
Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16984#issuecomment-245570172
