### ISSUE TITLE
Nefarian fight - Shadowflame Initial problem

### ISSUE THREAD

**Issue by TheEvilPotato** [TrinityCore/TrinityCore#18391]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When Nefarian (http://www.wowhead.com/npc=11583/nefarian) spawns and shadowflames everyone, he just stops... mid-air... quite depressing actually.
**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)
Nefarian should continue flying down to the platform to initiate the rest of the fight
**Steps to reproduce the problem:**

1. Endure Blackwing Lair
2. Endure Nefarian's first phase
3. Watch your hard work be squatched by a script bug

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5a
**TC rev. hash/commit:**  
28050f3
**TDB version:**  
62 with updates
**Operating system:**  
Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#9083
