### ISSUE TITLE
Group and loot not working.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18393]
**Description:**
When you are in a group and there is an unusual loot (green objects) does not appear the window to throw the dice, when trying to strip it directly appears a message where it says that they are still throwing dice, and the object can not be looted.

**Current behaviour:** (Tell us what happens.)
No dice to throw
**Expected behaviour:** (Tell us what should happen instead.)
To throw the dice to obtain the loot.
**Steps to reproduce the problem:**

1. Create a group
2. Kill a creature giving an unusual object.
3. Observe how the dice do not appear.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
2c5474e319da0a24b704c1a3521be4876d7a4da3
**TDB version:**  
7.0.3+updates
**Operating system:**  
Windows 10

**Comment by liszt** [comment]
Also in 784d70a
Temp Work-around:  Convert party to Raid and then set loot free-for-all and then back to party will at least allow items to be looted.
