### ISSUE TITLE
Worldserver crashing after startup

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#18398]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Worldserver crashes after about 10-15 secounds after everything is loaded.

TrinityCore rev. fb4097cc4a95 2016-12-02 01:04:52 +0100 (master branch) (Win64, Debug, Static) (worldserver-daemon)
Latest TDB downloaded from releases.
System : Intel Core I3 340M ; 6 GB DDR3 ; 320GB HDD ; Windows 10 Pro x64

[fb4097cc4a95_worldserver.exe_[3-12_16-53-48].txt](https://github.com/TrinityCore/TrinityCore/files/629055/fb4097cc4a95_worldserver.exe_.3-12_16-53-48.txt)
![bug](https://cloud.githubusercontent.com/assets/10487179/20861599/b0416862-b99c-11e6-8800-15ccf434ea48.jpg)

**Comment by Tauriella** [comment]
Try to Update your Core

**Comment by maryus101** [comment]
Trying now....

**Comment by Aokromes** [comment]
#17745
