### ISSUE TITLE
Spell Effects applied in wrong order

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18395]
**Description:** Spell Effects applied in wrong order.

**Expected behaviour:** Spell Effect sould be applied in correct order: EFFECT_0 -> EFFECT_1 -> EFFECT_2

**Current behaviour:** EFFECT_1 is applied before EFFECT_0.

**Steps to reproduce the problem:**

1. Target self
2.  ```.cast 41377```
3. You will not receive damage

> Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
> BasePoints = 7444 to 7557
> Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
> 
> Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 1
> Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
> Aura Id 40 (SPELL_AURA_DAMAGE_IMMUNITY), value = 1, misc = 127 (127), miscB = 0, periodic = 0

Damage should be applied before Immunity.

In sniffs packet order is:

> ServerToClient: SMSG_SPELL_NON_MELEE_DAMAGE_LOG (0x4315) Length: 45 ConnIdx: 2 Time: 05/30/2012 10:34:48.876 Number: 432310
> Target GUID: xxxxxxxxx
> Caster GUID: Full: 0xF1305B7C000050B4 Type: Creature Entry: 23420 (Essence of Anger) Low: 20660
> Spell ID: Spite (41377)
> Damage: 7525
> Overkill: -1
> SchoolMask: 8
> Absorb: 0
> Resist: 0
> Show spellname in log: false
> Unk byte: 1
> Blocked: 0
> HitType: SPELL_HIT_TYPE_UNK3 (4)
> Debug output: false
> 
> ServerToClient: SMSG_AURA_UPDATE (0x4707) Length: 30 ConnIdx: 2 Time: 05/30/2012 10:34:48.876 Number: 432311
> GUID: Full: xxxxxxxxxxx
> [0] Slot: 25
> [0] Spell ID: Spite (41377)
> [0] Flags: EffectIndex1, Duration, Negative (162)
> [0] Level: 73
> [0] Charges: 0
> [0] Caster GUID: Full: 0xF1305B7C000050B4 Type: Creature Entry: 23420 (Essence of Anger) Low: 20660
> [0] Max Duration: 2000
> [0] Duration: 2000

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  881cd78ae32d8078e247f64a73c651959a76e746

**Comment by ariel-** [comment]
Packet order isn't dependant on network?

Anyways the issue here is not effect order, they're handled sequentially -> https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L6975-L6982 for example

**Comment by Shauren** [comment]
No, damage is handled out of order (and after all effects are done), spell effect handlers only aggregate the damage for later processing (needed because almost all WEAPON_DAMAGE spells have multiple effects)

**Comment by ariel-** [comment]
I guess SPELL_EFFECT_SCHOOL_DAMAGE, handled by EffectSchoolDMG, should be handled immediately, not postponed, unlike weapon damage based effects (handled by EffectWeaponDmg), which still have their damages added together

**Comment by cbcs** [comment]
hello.can you share the sniffs tools?

**Comment by Killyana** [comment]
I tested the spell 41377 on rev. ecea2d62657e and it deal the damage before applying the immunity.

**Comment by ariel-** [comment]
Yeah, forgot to close :P
