### ISSUE TITLE
Core/Spells: mage spell Inferno Blast 108853 can not remove cast effects

### ISSUE THREAD

**Issue by cbcs** [TrinityCore/TrinityCore#18397]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Mage Spell Inferno Blast - 108853 Can not remove cast effects

**Current behaviour:** (Tell us what happens.)
When you use this spell to attack any creature The target interface is not available.

**Expected behaviour:** (Tell us what should happen instead.)
Normal casting

**Steps to reproduce the problem:**

1. Select Mage
2. Cast the Inferno Blast - 108853
3. The cast action bar exists but does not complete.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/2c5474e319da0a24b704c1a3521be4876d7a4da3

**TDB version:**  
7.0.3+updates

**Operating system:**  
Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by cbcs** [comment]
I've fixed it.

**Comment by aquadeus** [comment]
is this spell fixed?

**Comment by aquadeus** [comment]
this spell have changed to fire blast and works fine
