### ISSUE TITLE
[3.3.5] Onyxia Trinkets

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18392]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Onyxia trinkets don't work . for example :
- Purified Shard of the Scale : http://www.wowhead.com/item=49310
- Purified Shard of the Flame : http://www.wowhead.com/item=49463

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  46cb1083a5950d98933a68362c5563c1550a8cb1

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Mrgrasser** [comment]
don't check for label? or any test ?!!

**Comment by MrSmite** [comment]
For reference, the *Shard of the Scale* you have linked is the 6.x version with a *versatility* stat. The 335 version is MP/5: [Purified Shard of the Scale](http://wotlk.openwow.com/item=49310)

**Comment by Keader** [comment]
Fixed in 2ff855054f52bf2dcf81aa7a7da7bab7f8a99686
