### ISSUE TITLE
[Crash] Core/Phase: Unit::SetInPhase

### ISSUE THREAD

**Issue by Palabola** [TrinityCore/TrinityCore#18396]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
- This crash only show up in Release mode, somehow the iterator invalidation didn't happen in Debug.

**Current behaviour:** (Tell us what happens.)

- Tracelog: http://pastebin.com/zjt7iyJZ

**Expected behaviour:** (Tell us what should happen instead.)
- Phase system should be more thread safe.

**Steps to reproduce the problem:**
1.  No knowed reproduce at the moment, it's internal.

**Branch(es):**  master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**   881cd78

**TDB version:**  

**Operating system:**  Unix

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
also more than 1 year without aditional crashlogs, closing, if this bug is still valid try to use valgrind to see if you can see the crash reason.
