### ISSUE TITLE
[Master] World Server Crash - Vmaps related

### ISSUE THREAD

**Issue by mmorganj** [TrinityCore/TrinityCore#18399]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
World server crashes. Errors relating to vmaps. 
**Current behaviour:** (Tell us what happens.)
World server crashes when trying to load vmaps.
`VMap file './vmaps/0000.vmtree' does not exist
Please place VMAP-files (*.vmtree and *.vmtile) in the vmap-directory (./vmaps/), or correct the DataDir setting in your worldserver.conf file.
Unable to load critical files - server shutting down !!!`
Disabling vmaps fixes error. I have a vmaps folder and 0000.vmtree does exist.
**Expected behaviour:** (Tell us what should happen instead.)
No crash.
**Steps to reproduce the problem:**

1. Update Core
2. Run with vmaps enabled

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
79b984832ff6a30865755c0f202e08dd334d7dbc
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by funjoker** [comment]
it's probably a config problem

**Comment by mmorganj** [comment]
Maybe, no problem when on 76a56d489b86b8947611dd6080a1a9db3f34716e

**Comment by mmorganj** [comment]
22396f1bcf97d3568faa95f17dcbf0984bce0312

> Re-extracting vmaps is required

I'll close after I check; should work though.

**Comment by mmorganj** [comment]
22396f1bcf97d3568faa95f17dcbf0984bce0312
