### ISSUE TITLE
[3.3.5] Vmap4assembler not working

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#18404]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Vmap4assembler is closing and doing nothing.

**Current behaviour:** (Tell us what happens.)

Map extractor and vmap4extractor are working perfectly but vmap4assembler is closing doing nothing.
I extracted vmaps 3 times on different versions of WoW 3.3.5 (enUS enGB) with vmaps folder created manually but no luck. Still the same problem.

TrinityCore rev. 3d5c1b83b15c 2016-12-03 22:55:12 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

System : Intel Core i3 370M ; 6 GB DDR3

**Comment by Aokromes** [comment]
works for me, i had to update common.dll on client pc.

**Comment by Visagalis** [comment]
I'm having this issue still.

> spawning Map 619
> spawning Map 624
> spawning Map 628
> spawning Map 631
> spawning Map 632
> spawning Map 649
> spawning Map 650
> spawning Map 658
> spawning Map 668
> spawning Map 723
> spawning Map 724
> Calculating model bounds for map 0...
> cmpfail, VMAP042!=VMAP041
> Creating map tree for map 0...

Then it crashes. Here's dmp file: https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiI4YTVhNmE4MC1iMGZjLTQzMTMtODM1MS03MWIzYzJhYzc0YzMiLCJlbWFpbCI6Imp1bGl1c3pzQGdtYWlsLmNvbSJ9

Tested on version https://github.com/TrinityCore/TrinityCore/commit/8d2f2f8f0603608f0f21e656046cb7ffcb4813a2

**Comment by tkrokli** [comment]
@Visagalis : Can't reproduce your issue, it works just fine for me on Windows 10 + commit https://github.com/TrinityCore/TrinityCore/commit/8d2f2f8f0603608f0f21e656046cb7ffcb4813a2.

<details>

```
Extract V4.00 2012_02. Beginning work ....

Game path: Data\
Found locale 'enGB'

Adding data files from locale directories.
Scanning patch levels from data directory.
Scanning patch levels from locale directories.
Locale: enGB

[...]

using Buildings as source directory and writing output to Vmaps
Read coordinate mapping...
[...]
spawning Map 619
spawning Map 624
spawning Map 628
spawning Map 631
spawning Map 632
spawning Map 649
spawning Map 650
spawning Map 658
spawning Map 668
spawning Map 723
spawning Map 724
Calculating model bounds for map 0...
Creating map tree for map 0...
Calculating model bounds for map 1...
Creating map tree for map 1...
Calculating model bounds for map 13...
Creating map tree for map 13...
Calculating model bounds for map 25...
Creating map tree for map 25...
Calculating model bounds for map 30...
Creating map tree for map 30...
Calculating model bounds for map 33...
Creating map tree for map 33...
Calculating model bounds for map 34...
Creating map tree for map 34...
Calculating model bounds for map 35...
Creating map tree for map 35...
Calculating model bounds for map 36...
Creating map tree for map 36...
Calculating model bounds for map 37...
Creating map tree for map 37...
Calculating model bounds for map 42...
Creating map tree for map 42...
Calculating model bounds for map 43...
Creating map tree for map 43...
Calculating model bounds for map 44...
Creating map tree for map 44...
Calculating model bounds for map 47...
Creating map tree for map 47...
Calculating model bounds for map 48...
Creating map tree for map 48...
Calculating model bounds for map 70...
Creating map tree for map 70...
Calculating model bounds for map 90...
Creating map tree for map 90...
Calculating model bounds for map 109...
Creating map tree for map 109...
[...]
Calculating model bounds for map 724...
Creating map tree for map 724...
ERROR: Can't open raw model file: Buildings/Final_Stage.wmo

Converting Model Files
Converting 1000Needlesbridge.wmo
Converting 40Manarmygeneral.wmo
[...]
Converting Zulgurubtree04.m2
Converting Zulgurubtree05.m2
Ok, all done
```
</details>

**Comment by Aokromes** [comment]
Maybe he is using custom client/broken client.
Tested again with updated extractor and working as intended.
