### ISSUE TITLE
Train to Ironforge.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18400]
**Description:**
The train from Stormwind to Ironforge on reaching the platform lets you ride but once you start you stay in the air and do not travel with him, other than a wagon appears and disappears from the platform.

**Current behaviour:** (Tell us what happens.)
Once the train starts you stay in the air.
**Expected behaviour:** (Tell us what should happen instead.)
obvious
**Steps to reproduce the problem:**

1. Go to Stormwind train
2. Wait for it
3. try to travel.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
2c5474e319da0a24b704c1a3521be4876d7a4da3
**TDB version:**  
7.0.3+updates
**Operating system:**  
Windows 10

**Comment by lorac2k14** [comment]
This issue is already known and has been reported you can find the issues at 
#17204 #6395 #7286
