### ISSUE TITLE
[master] DB/mount: Frozo the Renowned carpet missing

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18407]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Frozo the Renowned (NPC 40160) is hovering in Dalaran, outside the "Like Clockwork" shop.

**Current behaviour:** Frozo is hovering off the ground. http://i.imgur.com/hwsFo27.jpg

**Expected behaviour:** Frozo should be on a flying carpet. In retail he is on a flying carpet.  See http://wow.zamimg.com/uploads/screenshots/small/556041.jpg (per WoWhead)

**Steps to reproduce the problem:**

1. Go to Dalaran
2. Go to Magus Commerce Exchange
3. Observe Frozo

**Branch(es):** Master

**TC rev. hash/commit:**  e0fb444

**TDB version:**  7.01

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Check: SELECT * FROM creature_addon WHERE guid IN (202846);
It must be:
guid, path_id, mount, bytes1, bytes2, emote, auras
 202846, 0, 31837, 0, 257, 0, 70878 75387

**Comment by tkrokli** [comment]
TrinityCore rev. 784d70af7b77 2016-12-06 08:10:41 +0100 (master branch) (Win64, Release, Static) / TDB 703.00
```sql
SELECT * FROM `creature_addon` WHERE `guid` IN (202846);
```
```
  guid  path_id   mount  bytes1  bytes2   emote  aiAnimKit  movementAnimKit  meleeAnimKit  auras 
------  -------  ------  ------  ------  ------  ---------  ---------------  ------------  ------
```
I presume you would like to add this to the table:
```sql
-- give Frozo the Renowned his carpet back
DELETE FROM `creature_addon` WHERE `guid`= 202846;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`aiAnimKit`,`movementAnimKit`,`meleeAnimKit`,`auras`) VALUES
(202846,0,31837,0,257,0,0,0,0,'70878 75387');
```

**Comment by BahDumbBugs** [comment]
@tkrokli - Well done. Thank you!

**Comment by tkrokli** [comment]
We have @Killyana to thank too because he provided the correct table name and data. I just facilitated it. :-)

**Comment by BahDumbBugs** [comment]
My bad. Killyana gets due credit too! 👍
