### ISSUE TITLE
Core/Spell First aid Bandage is not healing.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18402]
**Description:**
Bandages made with the profession first aid in applying them do not increase the life of the player.
**Current behaviour:** (Tell us what happens.)
Bandages made with the profession first aid in applying them do not increase the life of the player.
**Expected behaviour:** (Tell us what should happen instead.)
When you use the bendage, you must heal the player.
**Steps to reproduce the problem:**

1. Learn First aid.
2. Create a bandage.
3. Use it and see who it not healing you.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
79b984832ff6a30865755c0f202e08dd334d7dbc
**TDB version:**  
7.0.3+updates.
**Operating system:**  
Windows 10

**Comment by Naddley** [comment]
works rev. 85205d8ca5d4
