### ISSUE TITLE
[Master] Herbalism Skill - Gathering Issue

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18406]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Herbalism Profession Skill Gathering having issues.

**Current behaviour:** Ticket #14682 - Not sure if these two are related/relevant, but manually adding in Herbalism (Spell 2366) seemed to be acceptable as it lasted through server restart (unlike fishing, which cleared from the abilities after client reboot), however - gathering in low level start areas is not working. Rather, on attempt to gather Peacebloom, it shows up as "Invalid Item" and cannot be harvested. See photo.

http://i.imgur.com/0PA5m0P.jpg

**Expected behaviour:** Mats should be harvested and added to inventory.
**Steps to reproduce the problem:**

1. Learn / Add Herbalism Profession manually 
2. Go to low level areas and look for beginner herbs to harvest.
3. Observe the results on "Gather" function. 

**Branch(es):** Master

**TC rev. hash/commit:**  e0fb444

**TDB version:**  7.01

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Could be a "missing link" between the spell and the item or gameobject to be accessed. Not sure if this needs to be solved via spell script, DB spell tables or core changes (or a mix between any of those).

**Comment by BahDumbBugs** [comment]
Earthroot and Peacebloom show up as Invalid Target, however, Bloodthistle around Silvermoon can be harvested as normal. Could it be because Bloodthistle is used as a racial herb for Blood Elves?

**Comment by MrSmite** [comment]
Don't know if github allows merging issues but this is the same as #18378 regarding the mining skill.
