### ISSUE TITLE
DB/Creatures: Remove "Ignore pathfinding" for High Warlord Naj'entus

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18410]
**Description:** After 0df0cb30ca9de2015ec774e50bb69337382576d3 is necessary anymore.

Fix:
```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra`&~536870912 WHERE `entry`=22887;
```

**TC rev. hash/commit:**  3d5c1b83b15cfc9f73888eb525c64323266c1fd4

**Comment by jackpoz** [comment]
when was this flag added ?

**Comment by Keader** [comment]
#18229
