### ISSUE TITLE
[3.3.5] Spell/Priest: Inspiration not work properly with Penance

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18413]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Inspiration (Rank 3): Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from your **Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing** spell.
The problem is that not work with Penance.

**Current behaviour:**
Penance critical hits not reduces the target's physical damage.

**Expected behaviour:**
Penance critical hits should reduces the target's physical damage.

**Steps to reproduce the problem:**
1. Use Penance continuously.
2. Wait for a critical strike.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  3d5c1b8

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
hmm confirmed.
Inspiration dont proc with Penance Crit

**Comment by ccrs** [comment]
Does it work for other spells?

**Comment by Keader** [comment]
y
