### ISSUE TITLE
[3.3.5] Spell/Mage: Arcane Potency not work properly

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18417]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Arcane Potency (Rank 2): Increases the critical strike chance of your next damaging spell by 30% **after gaining Clearcasting or Presence of Mind.** (http://wotlk.openwow.com/spell=31572)

Here we have two problems:
**1-** Arcane Potency is activated by some spells for example Arcane Intellect, Icy Vains, Mana Shield, Slow Fall, etc. and should not. Only can be activated after gaining Clearcasting or Presence of Mind.
**2-** Buff Arcane Potency not work correctly because:
**a)** Only is consumed by spells without instant cast and should not. 
**b)** Polymorph consume Arcane Potenc and should not.
**c)** Arcane Missiles should consume Arcane Potency.
**d)** Only can be consumed by a critical damage spell.

For more details visit:
http://wow.gamepedia.com/Arcane_Potency
http://wowwiki.wikia.com/wiki/Arcane_Potency

**Current behaviour:** 
Arcane Potency is activated wrongly by spells like Arcane Intellect, Icy Vains, Mana Shield, Slow Fall, etc.

**Expected behaviour:**
Only can be activated after gaining Clearcasting or Presence of Mind. Arcane Potency Buff must comply with mencioned items a, b, c, d.

**Steps to reproduce the problem:**
1. Cast spells like Arcane Intellect, Icy Vains, Mana Shield and Slow Fall
2. Arcane Potency is activated.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  3d5c1b8

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Wiindows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
> And [Arcane potency](http://wotlk.openwow.com/spell=31572) should be removed by [Arcane missiles](http://wotlk.openwow.com/spell=25345) 
> http://wowwiki.wikia.com/wiki/Arcane_Potency
> 
> > ... Arcane Missiles consumes the Arcane Potency buff but not PoM.

(https://github.com/TrinityCore/TrinityCore/issues/18495#issuecomment-267637783)

**Comment by lost-illusion** [comment]
UPDATE `spell_proc` SET `SpellFamilyMask2`='0' WHERE `SpellId`='-31571';

But i have no idea why SpellFamilyMask2 = 8 was added after spell_proc implemented.
And when ClearCasting procs from Arcane Blast - no Arcane Potency.
@Noryad  @Keader @Aokromes

**Comment by Eliminationzx** [comment]
Fix proc by Clearcasting and Presence of Mind.
```diff
diff --git a/src/server/scripts/Spells/spell_mage.cpp b/src/server/scripts/Spells/spell_mage.cpp
index 5c49602..ecbee81 100644
--- a/src/server/scripts/Spells/spell_mage.cpp
+++ b/src/server/scripts/Spells/spell_mage.cpp
@@ -63,7 +63,9 @@ enum MageSpells
     SPELL_MAGE_T10_2P_BONUS_EFFECT               = 70753,
     SPELL_MAGE_T8_4P_BONUS                       = 64869,
     SPELL_MAGE_MISSILE_BARRAGE                   = 44401,
-    SPELL_MAGE_FINGERS_OF_FROST_AURASTATE_AURA   = 44544
+    SPELL_MAGE_FINGERS_OF_FROST_AURASTATE_AURA   = 44544,
+    SPELL_MAGE_CLEARCASTING                      = 12536,
+    SPELL_MAGE_PRESENCE_OF_MIND                  = 12043
 };
 
 enum MageSpellIcons
@@ -109,10 +111,21 @@ class spell_mage_arcane_potency : public SpellScriptLoader
             bool Validate(SpellInfo const* /*spellInfo*/) override
             {
                 if (!sSpellMgr->GetSpellInfo(SPELL_MAGE_ARCANE_POTENCY_RANK_1) ||
-                    !sSpellMgr->GetSpellInfo(SPELL_MAGE_ARCANE_POTENCY_RANK_2))
+                    !sSpellMgr->GetSpellInfo(SPELL_MAGE_ARCANE_POTENCY_RANK_2) || 
+                    !sSpellMgr->GetSpellInfo(SPELL_MAGE_CLEARCASTING) ||
+                    !sSpellMgr->GetSpellInfo(SPELL_MAGE_PRESENCE_OF_MIND)))
                     return false;
                 return true;
             }
+            
+            bool CheckProc(ProcEventInfo& eventInfo) 
+            {
+                if (SpellInfo const* spellInfo = eventInfo.GetSpellInfo())
+                    if (spellInfo->Id == SPELL_MAGE_CLEARCASTING || spellInfo->Id == SPELL_MAGE_PRESENCE_OF_MIND)
+                        return true;
+
+                return false;
+            }
 
             void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
             {
@@ -126,6 +139,7 @@ class spell_mage_arcane_potency : public SpellScriptLoader
 
             void Register() override
             {
+                DoCheckProc += AuraCheckProcFn(spell_mage_arcane_potency_AuraScript::CheckProc);
                 OnEffectProc += AuraEffectProcFn(spell_mage_arcane_potency_AuraScript::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
             }
         };
```

**Comment by ariel-** [comment]
This is not proper way to filter out procs. SpellMask in DB is for that.

**Comment by lost-illusion** [comment]
@ariel- Yes and in DB SpellFamilyMask2 = 8, but it causes proc Arcane Potency from any spells with SpellFamilyMask2 = 8. If we remove this from DB and set original mask from dbc - all works correctly.
But as i said before, when clearcast procs from Arcane Blast - no Arcane Potency. In other cases all is fine.

**Comment by ariel-** [comment]
Probably an oversight, as Clearcasting has SpellFamilyMask[2] == 0x00000008, but also do many other spells.
