### ISSUE TITLE
Levitate interrupts channeling spells

### ISSUE THREAD

**Issue by Goatform** [TrinityCore/TrinityCore#18415]
**Current behaviour:** Currently, priest's spell, Levitate is interrupting channeling spells such as Penance (Priest), Arcane Missiles (Mage), Army of the Dead (Death Knight) etc, when it gets removed.

**Expected behaviour:** When Levitate is removed and player is channeling some spell, it should not interrupt it.

**Steps to reproduce the problem:**

1. Create priest.
2.  Cast Levitate on someone
3.  Player have to use some of spells which I said above and remove Levitate effect
(Result: Then you will see how spell gets interrupted)

**Branch(es):** 3.3.5 (Confirmed)

**TC rev. hash/commit:**  3d5c1b8

**TDB version:**  335.62

**Operating system:**  Windows 7

**Comment by Keader** [comment]
Yeap, mind fly too
Is a old bug btw

**Comment by Goatform** [comment]
Well, channeling spells in general and yeah, it is very old bug.

**Comment by Goatform** [comment]
I did some research about it and I think that it could be fixed here:

```
void WorldSession::HandleCancelAuraOpcode(WorldPacket& recvPacket)
{
    uint32 spellId;
    recvPacket >> spellId;

    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
    if (!spellInfo)
        return;

    // not allow remove spells with attr SPELL_ATTR0_CANT_CANCEL
    if (spellInfo->Attributes & SPELL_ATTR0_CANT_CANCEL)
        return;

    // channeled spell case (it currently cast then)
    if (spellInfo->IsChanneled())
    {
        if (Spell* curSpell = _player->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
            if (curSpell->m_spellInfo->Id == spellId)
                _player->InterruptSpell(CURRENT_CHANNELED_SPELL);
        return;
    }

    // non channeled case:
    // don't allow remove non positive spells
    // don't allow cancelling passive auras (some of them are visible)
    if (!spellInfo->IsPositive() || spellInfo->IsPassive())
        return;

    // maybe should only remove one buff when there are multiple?
    _player->RemoveOwnedAura(spellId, 0, 0, AURA_REMOVE_BY_CANCEL);
}
```

**Comment by ariel-** [comment]
Client sends MSG_MOVE_FALL_LAND when "landing" after fall from levitate -> it counts as "moving" -> channeled is interrupted when moving -> profit
