### ISSUE TITLE
[Master] Arcane Torrent not working for BElf Priest

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18411]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** In the quest Thirst Unending, Arcane Torrent is not working for Blood Elf Priest. Refer to #17098.

**Current behaviour:**Spell casts normally, does not register on quest progress.

**Expected behaviour:** Arcane Torrent should register on quest progress. 

**Steps to reproduce the problem:**

1. Get Quest from Arcanist Hellion as a Blood Elf Priest
2. Use Arcane TOrrent on Mana Wyrm
3. Observe reaction and quest progress.

**Branch(es):** Master

**TC rev. hash/commit:**  fcbbeb3

**TDB version:**  7.01

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by CrisPj** [comment]
Try this:
```sql
-- Thirst Unending
-- Arcane Torrent Priest 232633
SET @WYRM := 15274;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@WYRM AND `source_type` = 0 and `id` = 8;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@WYRM,0,8,0,8,0,100,1,232633,0,0,0,11,61314,0,0,0,0,0,7,0,0,0,0,0,0,0,"Mana Wyrm - On Spellhit 'Arcane Torrent' - Cast 'Quest Credit 8346' (No Repeat)");
```

**Comment by aquadeus** [comment]
Is this fixed?
