### ISSUE TITLE
[335] Scrolls Are Consumed When They Fail To Apply

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18429]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Stat scrolls are consumed from inventory when they fail to apply to the target.

**Current behaviour:**

See description.

**Expected behaviour:**

Scrolls that fail to apply should remain in inventory.

**Steps to reproduce the problem:**

Tested with a Hunter

1. Apply a [Scroll of Agility II](http://www.wowhead.com/item=1477/scroll-of-agility-ii) to your pet
2. Attempt to apply a [Scroll of Stamina](http://www.wowhead.com/item=1180/scroll-of-stamina) while previous buff is active
3. You will receive an error: *A more powerful spell is active*
4. The scroll will be consumed from your inventory anyway

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system:**  WinXP / Win 7

**Notes:**

I searched both the closed / open issues and did not see anything referencing this bug so I did not pull and compile a new core.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Faq** [comment]
So, item is delete process started by 
void Spell::TakeCastItem(), here: https://github.com/TrinityCore/TrinityCore/blob/f9d117737998a6bdf560b02e9ca3f4a5ce4bfa2a/src/server/game/Spells/Spell.cpp#L4580
then triggers:
void Player::DestroyItemCount here: https://github.com/TrinityCore/TrinityCore/blob/f9d117737998a6bdf560b02e9ca3f4a5ce4bfa2a/src/server/game/Spells/Spell.cpp#L4636

Guessing, need to add check if more powerful aura applied and in that case not deleting item.

**Comment by illfated** [comment]
(linking the entire function here, for those who want a simplified access to all the lines)
https://github.com/TrinityCore/TrinityCore/blob/f9d117737998a6bdf560b02e9ca3f4a5ce4bfa2a/src/server/game/Spells/Spell.cpp#L4580-L4646

**Comment by Faq** [comment]
Could be something like this.
src\server\game\Spells\Spell.cpp
```
@@ +3512,20 +3512,15 @@
 
     FinishTargetProcessing();
 
     // spell is finished, perform some last features of the spell here
     _handle_finish_phase();
 
+    // If spell not failed, remove used for cast item if need (it can be already NULL after TakeReagents call)
+    uint32 param1 = 0, param2 = 0;
+    SpellCastResult result = CheckCast(true, &param1, &param2);
+    if (result != SPELL_FAILED_NOT_READY)
+    {
+        TakeCastItem();
+    }
-    // Remove used for cast item if need (it can be already NULL after TakeReagents call
-    TakeCastItem();
 
     // handle ammo consumption for Hunter's volley spell
     if (m_spellInfo+>IsRangedWeaponSpell() && m_spellInfo+>IsChanneled())
         TakeAmmo();
 
     if (m_spellState != SPELL_STATE_CASTING)
         finish(true);                                       // successfully finish spell cast (not last in case autorepeat or channel spell)

```

**Comment by Killyana** [comment]
Pr please

**Comment by illfated** [comment]
@Faq : Do you have something written down yet, or is it still only at a meta-code stage?

**Comment by Faq** [comment]
Posted too early, failed other tests.

**Comment by illfated** [comment]
@Killyana : may as well remove the label **[Feedback-PatchFix]** because none of us have posted any real suggestions, only linked existing TC source.

**Comment by Faq** [comment]
This should be closed
