### ISSUE TITLE
[3.3.5] Spell/Rogue: Stealth is canceled by some friendly spells

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18421]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I found two spells that cancel stealth without having entered into combat and should not, maybe there are more.
1- Heroism/Bloodlust (Shaman)
2- Turn the Tables (Rogue).

**Current behaviour:**
Stealth is canceled by Heroism/Bloodlust and Turn the Tables.

**Expected behaviour:**
Stealth should not be canceled by Heroism/Bloodlust and Turn the Tables.

**Steps to reproduce the problem:**
1. With a rogue in your party or raid use stealth.
2. Cast Heroism/Bloodlust or anyone in your party or raid blocks, dodges, or parries an attack to activate Turn the Tables.
3. Stealth is canceled without having entered into combat.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  3d5c1b8

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lostsoul123** [comment]
INSERT INTO `world`.`spell_custom_attr` (`entry`, `attributes`) VALUES ('32182', '64');
INSERT INTO `world`.`spell_custom_attr` (`entry`, `attributes`) VALUES ('2825', '64');
INSERT INTO `world`.`spell_custom_attr` (`entry`, `attributes`) VALUES ('52910', '64');
INSERT INTO `world`.`spell_custom_attr` (`entry`, `attributes`) VALUES ('52914', '64');
INSERT INTO `world`.`spell_custom_attr` (`entry`, `attributes`) VALUES ('52915', '64');

**Comment by shenhuyong** [comment]
@lostsoul123 It fixed Turn the Tables, but Heroism and Bloodlust still breaks stealth, SPELL_ATTR0_CU_DONT_BREAK_STEALTH be used to check break stealth attr only in SpellAuras.cpp Aura::GetProcEffectMask
