### ISSUE TITLE
[Crash] - SpellInfo::HasEffect

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#18424]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Crash when complete quest: http://www.wowhead.com/quest=5675/elunes-grace
Crashlog: https://gist.github.com/Jildor/ad1547e4ed24477aec0aecdeceabd261

**Current behaviour:** (Tell us what happens.)
Discovered accidentally
**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1.  add quest by command:  .quest add 5675
2.  reward quest: .quest reward 5675
3.  server crash

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  3d5c1b83b15cfc9f73888eb525c64323266c1fd4

**TDB version:**  TDB335.62

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
>spellInfo = 0x0

**Comment by jackpoz** [comment]
```
if (quest->GetRewSpellCast() > 0)
{
    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(quest->GetRewSpellCast());
    if (questGiver->isType(TYPEMASK_UNIT) && !spellInfo->HasEffect(SPELL_EFFECT_LEARN_SPELL)
```

missing NULL check or Startup check + value sanitization + ASSERT()

**Comment by ariel-** [comment]
They're already checked at startup: https://github.com/TrinityCore/TrinityCore/blob/3d5c1b83b15cfc9f73888eb525c64323266c1fd4/src/server/game/Globals/ObjectMgr.cpp#L4593-L4643

Did you make any other changes to the source?

**Comment by Jildor** [comment]
Is it possible because the quest is disabled? (Deprecated quest)

**Comment by tkrokli** [comment]
http://wow.gamepedia.com/Quest:Elune%27s_Grace (disambiguation page)

http://wow.gamepedia.com/Quest:Elune%27s_Grace_(Kalimdor)
http://wow.gamepedia.com/Quest:Elune%27s_Grace_(Stormwind)
- http://www.wowhead.com/quest=5672/elunes-grace (This quest is no longer available within the game.)
- http://www.wowhead.com/quest=5673/elunes-grace (This quest is no longer available within the game.)
- http://www.wowhead.com/quest=5674/elunes-grace (This quest is no longer available within the game.)
- http://www.wowhead.com/quest=5675/elunes-grace (This quest is no longer available within the game.)

**The subject of this article was removed from [World of Warcraft](http://wow.gamepedia.com/World_of_Warcraft) in patch [3.0.2](http://wow.gamepedia.com/Patch_3.0.2).**

If any of the quests in the chain above are available in-game, they need to be deactivated.

**Comment by ariel-** [comment]
> Is it possible because the quest is disabled? (Deprecated quest)

Totally this. ObjectMgr skips sanity check for disabled quests (in disable table)

**Comment by jackpoz** [comment]
> missing NULL check or Startup check + value sanitization + ASSERT()

the NULL check or th ASSERT() are still missing ? one of the 2 should be added.

**Comment by Shauren** [comment]
or something else - prevent completing disabled quests using gm commands

**Comment by jackpoz** [comment]
all sSpellMgr->GetSpellInfo() calls that don't expect NULL should always ASSERT() , just so we get better crashlogs. ofc if they get triggered they need to be fixed properly, like that gm command

**Comment by Aokromes** [comment]
Still valid on 391ccee

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5f6af8c6cbe7c5a622dd51a77e0d27db33c99118
