### ISSUE TITLE
[7.1.0.23171] Maps extractor - Segmentation fault: 11

### ISSUE THREAD

**Issue by Toooorch** [TrinityCore/TrinityCore#18420]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
It does not work in any possible way.

**Current behaviour:** (Tell us what happens.)
I successfully build all extractors/tools with -DTOOLS=1 and after that I wanted to extract mandatory files but it is not possible because this error:

Segmentation fault: 11
http://i.imgur.com/KJZVQZ6.png

This fail appears also in any possible way to extract these files. As you can see from screenshot I also tried to set locales and all directories as well but it did not work out.

I think it needs to be updated/modified to work with 7.1.0 because I sucessfully extract maps from older 7.x version in the exactly same way and now I recieved only this message.

Nedless to say, extractor is located directly in wow directory and the wow client is updated with battle.net.

**Expected behaviour:** (Tell us what should happen instead.)
all maps/dbc extracted

**Steps to reproduce the problem:**

1. build c856a058b50e with -DTOOLS=1
2. mv exctractor to wow directory
3. try extract with ./mapextractor -l enUS from terminal

**Branch(es):** 
master

**TC rev. hash/commit:**  
c856a058b50e (from 5 dec)

**TDB version:**  
TDB_full_703.00_2016_10_17

**Operating system:**  
Mac OS X 10.12.1 (16B2555)

Thank you guys. I already learned many things about developing because this project!

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Compile in Debug mode: `cmake -DCMAKE_BUILD_TYPE=Debug ..`
and then run mapextractor with gdb, similar to https://trinitycore.atlassian.net/wiki/display/tc/GDB

**Comment by Toooorch** [comment]
I did what you told and gdb saying 

Thread 3 received signal SIGSEGV, Segmentation fault.
0x00007fffe0a82533 in ?? ()

http://i.imgur.com/KEs76Zg.png

I think there is change from last working version of extractor because last wow build id 23171 and discussion here on github talking about older version (and then fix/update extractor for use).

Meanwhile I tried build extractor on windows - release/debug with same result - mapextractor stopped working - maybe I don't have required files because I install freash version of windows today and I don't have perfect setup.

**Comment by tkrokli** [comment]
TrinityCore rev. 784d70af7b77 2016-12-06 08:10:41 +0100 (master branch) (Win64, Release, Static) / TDB 703.00

[TOOLS] included in build, works OK, extracted dbc, gt, maps & vmaps. No issues (Windows 10 x64 build).

**Comment by liszt** [comment]
TC Rev 784d70a - Linux x64 build (gcc 6.2.1) + win7 x64 build
All tools work OK.  Extracted dbc, gt, maps, vmaps, mmaps.

**Comment by Toooorch** [comment]
Guys are you sure that you are using 7.1.0.23171? Because otherwise I don't know where is the problem.

**Comment by tkrokli** [comment]
I am fairly certain I am using that version. Here is a screenshot from my current WoW retail folder:

![wow_folder](https://cloud.githubusercontent.com/assets/4903600/20979953/fe8573dc-bcae-11e6-88af-d37142380765.png)

**Comment by Traesh** [comment]
Confirmed here, crash at mapextractor launch

I tried revert https://github.com/TrinityCore/TrinityCore/commit/c856a058b50e9f9844a4eb4b63e3786de69e6678 and now it work fine

VS debugger didn't trigger on crash, i will try to find were this come from

**Comment by Shauren** [comment]
extractors now have the same crash reporting code as bnetserver and worldserver, upload the crash log

**Comment by Traesh** [comment]
Don't see a crashlog in my folder, maybe am i missing it

Here is a screen of the crash : http://puu.sh/sHH9J/dc5b9d5d5c.png

**Comment by Toooorch** [comment]
I have same problem as Traesh on Windows - clean installation of WoW from battle.net... As I mentioned before I was able to export maps from 7.0.3 in exactly same way but now I cant :/
http://puu.sh/sHH9J/dc5b9d5d5c.png

**Comment by tkrokli** [comment]
TrinityCore rev. 6ce35f3772d3 2016-12-06 23:45:35 +0100 (master branch) (Win64, Debug, Static)

![mapextractor_debug](https://cloud.githubusercontent.com/assets/4903600/20991070/85fd53a2-bcdc-11e6-9ad9-cdf0de576881.png)

mapextractor does not seem to produce a crash log, so I opened the debugger instead:

![vs2015_debug](https://cloud.githubusercontent.com/assets/4903600/20991257/ba1150c0-bcdd-11e6-8b68-143b4b12d234.png)

Both worldserver + bnetserver start up just fine with the maps etc. from my previous build, though.

**Comment by Toooorch** [comment]
Some new thoughts. I tried commit f2277dd and it working fine except few errors.

Extracting dbc/db2 files...
locale enUS output path /Volumes/Data 1TB WDB/Library/World of Warcraft/dbc/enUS/
Unable to open file DBFilesClient\CameraShakes.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestPOIPointCliTask.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellEffectCameraShakes.db2 in the archive for locale enUS: FILE_NOT_FOUND
Extracted 566 files

Error loading World\Maps\Northrend\Northrend_30_16_obj0.adt

**Comment by Shauren** [comment]
Fix pending - https://github.com/ladislav-zezula/CascLib/pull/56

**Comment by tkrokli** [comment]
Thanks for the fix and new commit, good work as always. 👍
