### ISSUE TITLE
The World Server will not run properly

### ISSUE THREAD

**Issue by Silvertower** [TrinityCore/TrinityCore#18433]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The World Server will not run properly.

**Current behaviour:** (Tell us what happens.)
The World Server starts and then immediately exits. The log claims that '../data/vmaps/000.vmtree' does not exist, but it does.

Here is the log and shell commands that show this, along with the SHA256 hash of the file '../data/vmaps/000.vmtree':

```
trinity@trinitycloudvm:~/server/bin$ ./worldserver
TrinityCore rev. 6c28cce2f236 2016-12-08 15:52:24 +0000 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/trinity/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.58.0
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 14 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 2 new and 17 archived updates.
Updating World database...
>> World database is up-to-date! Containing 119 new and 1800 archived updates.
Realm running as realm ID 1
Using World DB: TDB 335.62
Missing name MonsterSight in config file /home/trinity/server/etc/worldserver.conf, add "MonsterSight = 50.000000" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ../data/
WORLD: MMap data directory is: ../data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ../data/vmaps
VMap file '../data/vmaps/000.vmtree' does not exist
Please place VMAP-files (*.vmtree and *.vmtile) in the vmap-directory (../data/vmaps/), or correct the DataDir setting in your worldserver.conf file.
Unable to load critical files - server shutting down !!!

trinity@trinitycloudvm:~/server/bin$ ls -al ../data/vmaps/000.vmtree
-rw-rw-r-- 1 trinity trinity 1998297 Apr 30  2016 ../data/vmaps/000.vmtree

trinity@trinitycloudvm:~/server/bin$ sha256sum ../data/vmaps/000.vmtree
b20bd037089e48247b40309f5a138cf74f2545a9e4cb4841389fa421bea47548  ../data/vmaps/000.vmtree
```

**Expected behaviour:** (Tell us what should happen instead.)

The file '../data/vmaps/000.vmtree' exists and has not changed since the server was first set up in April (see timestamp of the file above). No changes have been made to the configuration files for months (I am the only administrator and the only person with access to the host OS). The only change is the usual 'git pull origin 3.3.5' and re-builds. I re-ran cmake (cmake ../ -DCMAKE_INSTALL_PREFIX=/home/trinity/server -DCONF_DIR=/home/trinity/server/etc -DTOOLS=1 -DWITH_WARNINGS=1) and performed a 'make clean' and 'make' and 'make install' with no success.

**Steps to reproduce the problem:**

1. Start the World Server.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
6c28cce2f236

**TDB version:**  
335.62

**Operating system:**  
Ubuntu Server 16.04.1 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
It's working properly on head. i suggest you to fix your configuration, or be sure you have updated your files.

**Comment by Keader** [comment]
extract again your vmaps/mmaps files :)

**Comment by Silvertower** [comment]
If I need to extract the vmaps/mmaps then the error message should be more clear; the error states that the file does not exist, when it clearly does. I will investigate this further.

**Comment by DDuarte** [comment]
I absolutely agree, @Silvertower, and that used to be the behaviour. I have no idea what changed in this last time vmap version change.

**Comment by Keader** [comment]
Vmaps: https://github.com/TrinityCore/TrinityCore/commit/2402f476424531a175d9a016f433321f00608501

MMaps: https://github.com/TrinityCore/TrinityCore/commit/0df0cb30ca9de2015ec774e50bb69337382576d3

**Comment by tkrokli** [comment]
We could either change this issue to be about getting the wrong error message for invalid version and reopen it, or we could open a new issue and document that vmaps version check returns wrong error.

(Minor detail: rev. 6c28cce2f236 is not a straight TC rev. hash, it must be a modified one.)

**Comment by Keader** [comment]
is weird because even with old MMaps/Vmaps my worldserver open, with some erros message, but open "normally"
