### ISSUE TITLE
[4.3.4/6.x/7.x] Core/Spells - Argaloth Consuming Darkness 88954.

### ISSUE THREAD

**Issue by Unknown-1000** [TrinityCore/TrinityCore#18439]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 88954 Consuming Darkness

I can suggest variant, but not testing compile and game.

``` cpp
// 88954 - Consuming Darkness
class spell_argaloth_consuming_darkness : public SpellScriptLoader
{
    public:
        spell_argaloth_consuming_darkness() : SpellScriptLoader("spell_argaloth_consuming_darkness") { }

        class spell_argaloth_consuming_darkness_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_argaloth_consuming_darkness_SpellScript);

            void FilterTargets(std::list<WorldObject*>& targets)
            {
                Trinity::Containers::RandomResizeList(targets, GetCaster()->GetMap()->Is25ManRaid() ? 8 : 3);
            }

            void Register() override
            {
                OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_argaloth_consuming_darkness_SpellScript::FilterTargets, EFFECT_0, TARGET_UNIT_SRC_AREA_ENEMY);
            }
        };

        class spell_argaloth_consuming_darkness_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_argaloth_consuming_darkness_AuraScript);

            void OnUpdate(AuraEffect* aurEff)
            {
                // multiply, starting from 2nd tick
                if (aurEff->GetTickNumber() == 1)
                    return;

                aurEff->SetAmount(int32(aurEff->GetAmount() * 2));
            }

            void Register() override
            {
                OnEffectUpdatePeriodic += AuraEffectUpdatePeriodicFn(spell_argaloth_consuming_darkness_AuraScript::OnUpdate, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE);
            }
        };
        
        SpellScript* GetSpellScript() const override
        {
            return new spell_argaloth_consuming_darkness_SpellScript();
        }
        
        AuraScript* GetAuraScript() const override
        {
            return new spell_argaloth_consuming_darkness_AuraScript();
        }
};
```

**Current behaviour:** (Tell us what happens.)
Only filter target (3 in 10, 8 in 25 mode)

**Expected behaviour:** (Tell us what should happen instead.)
Also should be more empowered on every tick.

**Steps to reproduce the problem:**

1. Find Argaloth in Baradin Hold.
2. /target Argaloth.
3. write command .cast back 88954
4. Damage no changes.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master.

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/21be921a09a3c28140c245c2164537324d0e4802

**TDB version:**  https://github.com/TrinityCore/TrinityCore/releases/tag/TDB703.00

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Krudor** [comment]
The damage is increased by 10% for each tick, not 100%.

**Comment by Unknown-1000** [comment]
``` CPP
aurEff->SetAmount(int32(aurEff->GetAmount() * 0.1f));
```
This?

**Comment by Krudor** [comment]
Now you're decreasing the damage by 90% for every tick :P
1.1

**Comment by Unknown-1000** [comment]
1.1f?

**Comment by Krudor** [comment]
Basic math?

**Comment by Ulduar** [comment]
0.01 * 100 = 1, 0,1 * 100 = 10, why 1.1f?

**Comment by ariel-** [comment]
You have an amount X you want to *increase* by 10%
