### ISSUE TITLE
[3.3.5] Feral Bonus from auras applied twice

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18435]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Class Druid , Feral guide very high DPS relative to other class, maybe manifold other Class , I mind Cat form have problem now .

**Branch(es):** 3.3.5 (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  c08b11ccef448554bb3d1e390072cd9ddfbf82ad

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
We need something a bit more objective that this issue description.

Do you know specific spells that should do less damage?

**Comment by Mrgrasser** [comment]
all talents & spells work and ok , but state Damage very high for cat form , you can test after know Druid feral is super man :D

**Comment by tkrokli** [comment]
It would be nice if you could find some online documentation of what the damage should actually be from the spells used by feral druids and then refer to your in-game damage in the current TC 3.3.5 branch. Without documentation and comparison, it is difficult for us to know what to look for in the source.

Check sites like wowhead.com, wowwiki, wow.gamepedia.com and older sites (elitist jerks, mmo-champion etc.) with info from at least 5-6 years back when 3.3.5a was in use on official servers.

**Comment by Keader** [comment]
is ironic because i saw alot of people saying in trinity based servers that druid feral has low damage xD

**Comment by DDuarte** [comment]
Anyway, the issue is not actionable.

If there is a problem, be specific and objective about it. If it's about melee damage, clearly state that it's currently doing X and should do Y because of Z.

**Comment by Mrgrasser** [comment]
for this problem not is link wowhead.com, wowwiki, wow.gamepedia.com , if is show ...

![3_wow-guldan1](https://cloud.githubusercontent.com/assets/23469404/21032735/b98dac28-bdc0-11e6-9fb5-0aa52e47fa24.jpg)

in the picture you can see two equal hero , Maybe I picked the wrong issue

**Comment by DDuarte** [comment]
That's not a screenshot from a "public server".

**Comment by sirikfoll** [comment]
yeah, base damage in Cat Form has almost doubled, if comparing newer revs with a 5~6 months old, I don't have time to do testing, neither can say which one is correct tho :/

**Comment by Mrgrasser** [comment]
private or public , that is warmane server , but maybe the lack of a suitable source my choice is not appropriate. @DDuarte  I am not idle needlessly destroy someone's Time ... so doing X and should do Y because of Z ?
warmane or arena tournament with several years experience not is a source ?
![photo_2016-12-09_03-08-49](https://cloud.githubusercontent.com/assets/23469404/21043904/7e374668-be0e-11e6-8e86-e8e292af5cf1.jpg)

@tkrokli for this problem where must find link ?

**Comment by DDuarte** [comment]
> warmane or arena tournament with several years experience not is a source ?

Definitely not.

**Comment by Jildor** [comment]
It is probably that the data does not have the necessary data

I do not know if it is an error or not, but ....

I think the problem is caused by this commit, here:
https://github.com/TrinityCore/TrinityCore/commit/6dc37a9add631888fe5fbcd43d19c2b07bed8a57#diff-9192fbb21749a5cb201987f5563a7d8eR542

160*1.25 = 200

**Comment by tkrokli** [comment]
We are still waiting to see if there is any documentation saying that the resulting damage output is wrong.

**Comment by Mrgrasser** [comment]
@ Jildor  Thenk you, not is for that line , I back all diff damage is ok now  

![3_wow-guldan1](https://cloud.githubusercontent.com/assets/23469404/21048099/b9acc538-be22-11e6-900a-f5281cab2999.jpg)
@DDuarte _doing_ X and should do Y because of Z 
Encounter some very rude , That may not be appropriate to say some other problems , It's also very important problem after a few years. 
now druid feral is SuperMan
Instead Close issues can just an test after...

**Comment by Aokromes** [comment]
you mean close vage issues without any clear information from official blizzzard sources?

**Comment by Mrgrasser** [comment]
@Aokromes  yes official blizzzard sources but some problem don't have any source if any source is now for new patch or some back you can find some information, for this problem just need some experience and test

**Comment by Jildor** [comment]
@Mrgrasser, the info is necessary to confirm the issue, you're right, damage has increased, but if there is no proof of how it should work, it can not be confirmed

mmm, I think the commit:
https://github.com/TrinityCore/TrinityCore/commit/6dc37a9add631888fe5fbcd43d19c2b07bed8a57
is the cause, but I can't test now.

**Comment by Keader** [comment]
Arena Tournament change your class to make a "balance" in pvp... is not a source...
btw looking in old Trinity Core (6 months older) this value is smaller...

**Comment by ariel-** [comment]
> I think the problem is caused by this commit, here:
> 6dc37a9#diff-9192fbb21749a5cb201987f5563a7d8eR542

> 160*1.25 = 200

That's not how `std::max` works

**Comment by Mrgrasser** [comment]
@ Keader , I test with other class, Druid feral have very high DPS , you say Arena Tournament old Core yes but now update last Trinity Core not balance with other class , you can see : real must Crit Chance 0.00 ?!! or melee Damage 2X ?!! please  just one test or duel with other class or attack dummy and see your redact damage after understand me

**Comment by ariel-** [comment]
> you can see : real must Crit Chance 0.00 ?!! 

Not true -> http://i.imgur.com/IKitC5X.png

**Comment by Mrgrasser** [comment]
@ariel- You give talent point 12.41% without talent point o_O
In general, the problem is clear

**Comment by ariel-** [comment]
Well, after making a research through the screenshots, the only difference is that aura 3025 (Cat form passive) wasn't being taken into account before, that's the +200 AP difference (that should be +160 because of my prev comment, this is the same number the client shows).

However, now AP bonus is added TWICE

Proof: AP calcs for cat form is here: https://github.com/TrinityCore/TrinityCore/blob/c08b11ccef448554bb3d1e390072cd9ddfbf82ad/src/server/game/Entities/Unit/StatSystem.cpp#L434

Ingame, naked untalented tauren druid has base stats:
Strength = 94, Agility = 77

Replacing, 
`val2 = getLevel() * (mLevelMult + 2.0f) + GetStat(STAT_STRENGTH) * 2.0f + GetStat(STAT_AGILITY) - 20.0f + weapon_bonus + m_baseFeralAP;`
getLevel() = 80, mLevelMult = 0 (no predatory strikes), weapon_bonus = 0 (same), m_baseFeralAP = 0 (no weapon equipped)

`80 * (0 + 2) + 97 * 2 + 77 - 20 + 0 + 0 = 160 + 194 + 57 = 405`

getLevel() * 2 yields the same value than ( 40 + (level - 20) * 2 ), meaning SpellLevel calc is off, and the bonus from the aura was hardcoded, this is blatantly wrong, I see the same has been done for bear form.

**Comment by Jildor** [comment]
Yep, confirm also with Bear form 150 instead 120

**Comment by Mrgrasser** [comment]
ariel- real excellent 👍

**Comment by Jildor** [comment]
Emmm .... Can anyone check it?

I think still bugged
rev (d9d433f59db477c9e457d0774487a3ae7168bb75)

**Comment by MrDelta** [comment]
@ariel- i think.
bouns damage melee state 
 still a problem.
please check it again
i think bouns damge melee state is 2x.
check it

**Comment by Jildor** [comment]
I think the cat damage increased and bear damage decreased

btw, @MrDelta please open a new issue

**Comment by Mrgrasser** [comment]
yes freal melee damage is 2x but other state correct.

**Comment by Jildor** [comment]
I think yes, but, for separate bugs, I think is better a new issue, because, the 2x damage I think is caused by https://github.com/TrinityCore/TrinityCore/commit/6dc37a9add631888fe5fbcd43d19c2b07bed8a57

**Comment by ariel-** [comment]
The issue **reported by the screenshots** was fixed, so if you think damage is wrong then please post your proof in a new ticket.

**Comment by Killyana** [comment]
I cannot find why feral dps are over powered: 22k dps on Festergut encounter.
Reference: http://web.archive.org/web/20100716215741/http://www.worldoflogs.com/rankings/players/Icecrown_Citadel/Festergut/25H/Feral-Cat_Druid/
