### ISSUE TITLE
mmaps not finding tree file

### ISSUE THREAD

**Issue by peterjweir** [TrinityCore/TrinityCore#18431]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
mmaps_generator doesn't run correctly against vmaps directory made on master

**Current behaviour:** (Tell us what happens.)
When run it states that vmaps directory is not present or is empty

**Expected behaviour:** (Tell us what should happen instead.)
vmaps directory is present and was populated by vmap4_extractor/assembler of same commit hash
tool should generate the mmaps

**Steps to reproduce the problem:**

1. follow instructions to extract map data for linux, with tools built from current master
2. get to step involving mmaps_generator
3. cry

Confirmed resolution by separating the error print statement out. The fault believed that the directory was present but empty. The current vmaps tools generate a .dtree file, and the mmaps_generator tool is searching specifically for a *.vmtree file. Changing the filter to *.dtree allows it to run correctly.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  
ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by CDawg** [comment]
I could be wrong, but wouldn't it error out with it can't find the file if it's the wrong version?
Did you try to recompile all mmaps, vmaps, etc..?
https://github.com/TrinityCore/TrinityCore/commit/ec9a8345a49938ddd9d42e9fdf7053ac25477b4d

**Comment by BahDumbBugs** [comment]
Thats the issue I was having. I tried re-extracting vmaps - and nothing. Currently running commit fcbbeb3 with vmaps manually turned off.

**Comment by Aokromes** [comment]
you need to re-extract vmaps and mmaps.

**Comment by tkrokli** [comment]
It would be helpful if anyone with time to spare and previous experience of debugging code could run all the breakpoints in the extractor in question and try to find where the error check jumps in a case like this.

**Comment by peterjweir** [comment]
Wow, Really, thank you for being the fastest responding dev community I have ever submitted an error report to. A little more background, This is the first time I've tried to build trinitycore from the Master branch. I started with fcbbeb3 and have done everything from scratch, brand new. I ran into the issue above when I tried to run mmaps and the filenames didn't match, I don't know enough about what they are supposed to look like to be more helpful. I will try to rebuild the tools and rerun everything again to be sure. With a little bit of direction about what it is that this code is supposed to be doing I would be happy to step into the code and figure out what went wrong.

**Comment by peterjweir** [comment]
Okay, so the good news is that I got it working, the bad news is that I basically cried wolf here. I stepped through the code really carefully to figure out what was happening, and although I can't fully confirm this it appears that the issue had to do with really long filesystem paths. My samba mount had used some really long names. I made a manual samba mount point with a much shorter path and it worked correctly. Some files were working and others weren't and it caused the processing chain to look like it was working, but not really work. I've tested this working with bfa9a4c and I'm quite happy with it now.

**Comment by BahDumbBugs** [comment]
I finally reached the point where I felt, I just needed to start from scratch. Pulled the latest commit, and reworked my vmaps and mmaps extraction as @Aokromes said. Worked like a charm. My vmaps and mmaps are detected as opposed to my last commit pulled a week and a half ago. I will vouch that a re-extraction and new pull will work.
