### ISSUE TITLE
[master] TC Zone Area Model Rework

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#18443]
**Description:**
TrinityCore Zone Area system needs a rework with slight consistency update.

**Current behaviour:**
Currently TC uses Zones and Areas in Zone. And is ignoring the tertiary areas.
Or not handling the tertiary areas as part of Zone.

**Expected behaviour:** 
Rename Examples:
Zone -> Area
Area -> SubArea
Tertiary Area (NYI) -> SubSubArea

OR

Zone -> Zone
Area -> Area
Tertiary Area (NYI) -> SubArea

OR

Zone -> Zone
Area -> SubZone
Tertiary Area (NYI) -> Area

But not only renaming it. Also the Core needs to handle the tertiary area as a part of the whole Zone.
This would make the definition of a Zone whole again.

Examples with seeable Subareas are:
Vashj'ir, Stranglethorn Vale, ALL starting areas

**Branch(es):** 
master 

**TC rev. hash/commit:**  
bfa9a4c9597c748734836fa2293f1ccf9724dbba

**TDB version:**  
703.00

**Operating system:**  
Win 10 64x

**Comment by Palabola** [comment]
Wrong, TC Area/Zone system based on AreaTable.db2 which already got 5500+ Area there is no any reason to support even smaller areas.

**Comment by funjoker** [comment]
Stranglethorn Vale is Zone 5339.
Inside this Zone there are 2 other zones.
Northern Stranglethorn (33) and Cape of Stranglethorn (5278).

Defining GY/condition for the Zone 5339 will not work, at least not for Cape. So you would need to assign Them to subzone

**Comment by MrSmite** [comment]
FWIW, I like this convention, the relationships are easy to understand.

>Zone -> Zone
Area -> SubZone
Tertiary Area (NYI) -> Area

**Comment by Shauren** [comment]
drop "zone" and "subzone" terms.
AreaTableEntry field name CLEARLY describes the relation `ParentAreaID` - its a tree. current zone+area pair assumes that tree depth is always <= 2 which is clearly not the case.

**Comment by funjoker** [comment]
Seems like deprecated
