### ISSUE TITLE
Vmaps Extractor Errors

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18447]
**Description:**
Vmap Extractor Errors
**Current behaviour:** (Tell us what happens.)

Can't read FILE0001A31A, size=4294967295 read=0!
No such file.
Could not open all Group file for: FILE0001A2EB.xxx

Can't read FILE0001A31A, size=4294967295 read=0!
No such file.
Could not open all Group file for: STORMWIND.WMO

Can't read FILE0001BF09, size=4294967295 read=0!
No such file.
Could not open all Group file for: ZULAMAN_ENTRANCE.WMO

Can't read FILE0001B5E2, size=4294967295 read=0!
No such file.
Could not open all Group file for: TK_Atrium.wmo

**Expected behaviour:** (Tell us what should happen instead.)
No Errors
**Steps to reproduce the problem:**

1. Compile latest build
2. Try make Vmaps
3. Error is near start

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
TrinityCore rev. b6f1f8405f57 
**TDB version:**  
TDB 703.00
**Operating system:**  
Windows 10 Pro x64

**Comment by Aokromes** [comment]
I wonder if it's the same as https://github.com/TrinityCore/TrinityCore/issues/18420

**Comment by adryan66** [comment]
Well for me it does continue going after those errors, even says succesul, sort of : 

Extract wmo complete (No (fatal) errors)

Currently on the processing maps part, will update if i see anything else (if im fast enough)

**Comment by robinsch** [comment]
Same error with different clients

**Comment by Shauren** [comment]
These are all test maps, ignore them

**Comment by tkrokli** [comment]
@adryan66 : as Shauren said, just ignore that list of errors from vmaps extractor, it is a cosmetic problem.
Vmaps will work just fine with that output, although it would have been nice to skip the invalid maps.
