### ISSUE TITLE
[7.1.0] Passive auras stops effects after far teleports.

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#18440]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Passive auras stops effects after far teleports.
**Current behaviour:** (Tell us what happens.)
EXAMPLE: http://wowhead.com/spell=202922 Reduces the cost of Rampage by 15 Rage
On login its effect works, but if we teleporting (far) - aura exist in .list auras , but dont reduces
in teleport on same map works good
 
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/61ec5b9abf9b9d7c0c73b5b01c73a6b49f639e4e
**TDB version:**  
last
**Operating system:**  
win 64x

**Comment by matukaa** [comment]
I confirm this, although it is only client-side effect. Upon using Rampage, it consumes only 70 Rage (client shows 30, `.debug getvalue 62` (UNIT_FIELD_POWER + 0) gives me 300 as well - Rage being stored 0-1000)

**Comment by Dramacydal** [comment]
hello cataclysm
