### ISSUE TITLE
Wail of the Banshee & Clutch of Foresight

### ISSUE THREAD

**Issue by jasperrietrae2** [TrinityCore/TrinityCore#1845]
http://www.wowhead.com/item=13509
http://www.wowhead.com/item=13514

These both can be used in arena.
##

**Comment by Killyana** [comment]
It could be fixed like this, but the flag is probably wdb, I don't know if we have something to block spells on arena.
UPDATE `item_template` SET `flags`=`flags`|67108864 WHERE `entry` IN (13509,13514);

**Comment by Aokromes** [comment]
using disabled thing can be hackfixed.
