### ISSUE TITLE
[7.x] Missing game_tele for Legion Teleports

### ISSUE THREAD

**Issue by Arles91** [TrinityCore/TrinityCore#18450]
**Description:** Missing teleport locations for the Legion zones.

**Steps to reproduce the problem:**

1. For example, insert the command `.tele Mardum`
2. press "Enter"
3. get the message: `Teleport location not found.`

**Branch(es):** master

**TC rev. hash/commit:**    b6f1f84

**TDB version:** TDB_full_703.00_2016_10_17 + Updates

**Operating system:**  Win10 64bit

**Comment by adryan66** [comment]
This should add one teleporter to each zone, to explore at least.

> INSERT INTO `game_tele` (`id` , `position_x` , `position_y` , `position_z` , `orientation` , `map` , `name` ) VALUES
	(1575, 1618.68, 4773.09, 138.31, 5.54097, 1220, 'Suramar'),
	(1576, -155.38, 6785.60, 36.86, 5.8237, 1220, 'Azsuna'),
	(1577, -835.35, 4277.05, 746.25, 1.6735, 1220, 'DalaranLegion'),
	(1578, 3200.79, 1521.39, 180.53, 1.1945, 1220, 'Stormheim'),
	(1579, 4127.51, 4416.51, 767.97, 0.6408, 1220, 'Highmountain'),
	(1580, 2931.77, 6584.85, 215.19, 5.0626, 1220, 'Val''sharah');
	(1581, 1176.53, 3257.46, 64.09, 4.4196, 1481, 'Mardum');
> 

Tested all of them myself and they work.

**Comment by tkrokli** [comment]
Notice that I have just edited the SQL to be repeatable (`DELETE FROM`) and removed whitespace.

**Comment by tkrokli** [comment]
Question: how are the coordinates selected for the teleport landing point ("spawn" point)?

**Comment by Arles91** [comment]
Thanks, but i'm just tested my .sql in-game and i obtained it to be repeteable:
DELETE FROM `game_tele` WHERE `id` IN (1575,1576,1577,1578,1579,1580,1581,1582,1583);
INSERT INTO `game_tele` (`id`,`position_x`,`position_y`,`position_z`,`orientation`,`map`,`name`) VALUES
(1575, -828.835, 4371.91, 738.636, 1.88158, 1220, 'DalaranCity'); /* Dalaran, Krasus' Landing [Legion] */
(1576, 1182.7, 3282.56, 69.99, 0.08, 1481, 'Mardum'); /* Mardum, The Shattered Abyss [Demon Hunter Start Zone] */
(1577, -218.95, 5600.9, 61.1105, 3.32418, 1220, 'Azsuna'); /* Azsuna, Eye of Azshara */
(1578, 2795.81, 7279.47, 21.6704, 4.75753, 1220, 'Val\'Sharah'); /* Val'Sharah, Bradensbrook */
(1579, 4492.69, 4836.35, 661.706, 1.37009, 1220, 'Highmountain'); /* Highmountain, Nesingwary's Retreat*/
(1580, 3854.78, 2020.04, 242.638, 3.2904, 1220, 'Stormheim'); /* Stormheim, Stormtorn Foothills*/
(1581, 1708.83, 4637.75, 124.004, 5.25153, 1220, 'Suramar'); /* Suramar, Shal'Aran Sanctuary */
(1582, -1306.66, 1741.4, 7.32331, 0.0914592, 1220, 'BrokenShore'); /* BrokenShore */
(1583, -3400, 4827.46, 27.829, 3.56, 1220, 'EyeAzshara'); /* Azsuna, Eye of Azshara */

**Comment by tkrokli** [comment]
Well, there are a couple of improvements needed in your SQL:
1. Use semicolon ( ; ) only after the last values line, comma after all the others.
2. We prefer using 2 dashes ( -- ) as SQL comment signs to avoid random issues with /* this */.
```sql
DELETE FROM `game_tele` WHERE `id` IN (1575,1576,1577,1578,1579,1580,1581,1582,1583);
INSERT INTO `game_tele` (`id`,`position_x`,`position_y`,`position_z`,`orientation`,`map`,`name`) VALUES
(1575, -828.835, 4371.91, 738.636, 1.88158,   1220, 'DalaranCity'), -- Dalaran, Krasus' Landing [Legion]
(1576, 1182.7,   3282.56,   69.99, 0.08,      1481, 'Mardum'), -- Mardum, The Shattered Abyss [Demon Hunter Start Zone]
(1577, -218.95,  5600.9,  61.1105, 3.32418,   1220, 'Azsuna'), -- Azsuna, Eye of Azshara
(1578, 2795.81,  7279.47, 21.6704, 4.75753,   1220, 'Val\'Sharah'), -- Val'Sharah, Bradensbrook
(1579, 4492.69,  4836.35, 661.706, 1.37009,   1220, 'Highmountain'), -- Highmountain, Nesingwary's Retreat
(1580, 3854.78,  2020.04, 242.638, 3.2904,    1220, 'Stormheim'), -- Stormheim, Stormtorn Foothills
(1581, 1708.83,  4637.75, 124.004, 5.25153,   1220, 'Suramar'), -- Suramar, Shal'Aran Sanctuary
(1582, -1306.66, 1741.4,  7.32331, 0.0914592, 1220, 'BrokenShore'), -- BrokenShore
(1583, -3400,    4827.46, 27.829,  3.56,      1220, 'EyeAzshara'); -- Azsuna, Eye of Azshara
```
I would still like to know how the coordinates are chosen, is this where a Blizzard GM would land on retail?

**Comment by Arles91** [comment]
I'm sorry, but i didn't know it..thank you!!

Mmm...I added these coordinates in order to access the areas, but I did not check if it corresponded to those Blizzard...how to control it?

**Comment by offl** [comment]
> I would still like to know how the coordinates are chosen

The coordinates for game_tele table are chosen by the .gps command :)

> Is this where a Blizzard GM would land on retail?

No.

**Comment by adryan66** [comment]
Got my'ne with the .gps command in game and ran to all spots. Better to have some at least to check and see things then none at all.

P.S. Kinda new to sql and programming overall , might miss things.

**Comment by tkrokli** [comment]
OK, so the `.tele` coordinates are randomly chosen safe spots in-game. I thought they were calculated or selected by some pre-determined method like a pinpoint on the map so it would be "blizzlike". I think I will wait for someone with longer experience than me to decide which coordinates to choose for master.

**Comment by adryan66** [comment]
Well I don't think it matters too much since from my understanding they are gm only commands for easyer teleporting, there can be a lot more , don't see the downside of that except bigger database.
At least if there are those anyone can get to the legion zones without searching all over the place for coords for the .go command :).
Don't think there is a way for official gm commands since blizz never posts things like that.

**Comment by DDuarte** [comment]
Exactly, game_tele coordinates and places are picked on usefulness, there's no true source for the coordinates.

**Comment by tkrokli** [comment]
If nobody has anything against it, I will commit the latest suggestion by Arles91 to the source:
```sql
-- add missing teleport locations with coordinates to game_tele
DELETE FROM `game_tele` WHERE `id` IN (1575,1576,1577,1578,1579,1580,1581,1582,1583);
INSERT INTO `game_tele` (`id`,`position_x`,`position_y`,`position_z`,`orientation`,`map`,`name`) VALUES
(1575, -828.835, 4371.91, 738.636, 1.88158,   1220, "DalaranCity"),  -- Dalaran, Krasus' Landing [Legion]
(1576, 1182.7,   3282.56,   69.99, 0.08,      1481, "Mardum"),       -- Mardum, The Shattered Abyss [Demon Hunter Start Zone]
(1577, -218.95,  5600.9,  61.1105, 3.32418,   1220, "Azsuna"),       -- Azsuna, Eye of Azshara
(1578, 2795.81,  7279.47, 21.6704, 4.75753,   1220, "Val'Sharah"),   -- Val'Sharah, Bradensbrook
(1579, 4492.69,  4836.35, 661.706, 1.37009,   1220, "Highmountain"), -- Highmountain, Nesingwary's Retreat
(1580, 3854.78,  2020.04, 242.638, 3.2904,    1220, "Stormheim"),    -- Stormheim, Stormtorn Foothills
(1581, 1708.83,  4637.75, 124.004, 5.25153,   1220, "Suramar"),      -- Suramar, Shal'Aran Sanctuary
(1582, -1306.66, 1741.4,  7.32331, 0.0914592, 1220, "BrokenShore"),  -- BrokenShore
(1583, -3400,    4827.46, 27.829,  3.56,      1220, "EyeAzshara");   -- Azsuna, Eye of Azshara
--
```
If changes are needed, it can be fixed easily by a new update to the /sql/updates/world/master folder later.

**Comment by tkrokli** [comment]
(Just linking back to #18453 for visibility in case anyone reads that closed PR and gets confused.)
