### ISSUE TITLE
[Master] Hero of the Sin'dorei

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18457]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Please reference #18062. The quest Hero of the Sin'dorei is having issues on turn in. I try to click 'Complete Quest' but it says the item was not found.http://i.imgur.com/0ZVvCM5.jpg

**Current behaviour:** See above. 

**Expected behaviour:** Quest should end, be removed from log, be awarded 75 Rep with Silvermoon and you continue on your merry way. See http://www.wowhead.com/quest=9328/hero-of-the-sindorei

**Steps to reproduce the problem:**

1. Kill Dar'khan (Again?)
2. Turn in at Court of the Sun in Silvermoon
3. Click Complete Quest and observe error on screen "The Item was not Found."

**Branch(es):** Master

**TC rev. hash/commit:**  6bfcdea

**TDB version:**  703.00

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by nubqt** [comment]
**Could not replicate issue.**

Did Blizzard change the quest or did you miss a step? The quest [Hero of the Sin'dorei ](http://www.wowhead.com/quest=9328/hero-of-the-sindorei) provides [Dar'Khan's Head](http://www.wowhead.com/item=22653) automatically. I turned in the quest fine.

Could you please double-check the steps you provided?

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated revision.
