### ISSUE TITLE
[master] Creature DB Merge with 3.3.5 branch

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18455]
Added all these to current build without any issues, reduced number of start errors from 165.425 rows to 58.913 (roughly). Should make some mobs with decent levels , not quite live but better then level 1, should be easier to check for other errors, including of the same mobs. It's made with Toad so the writing of them ain't really clean. Anyone can take a look and give some pros / cons ?

https://gist.github.com/adryan66/20bc06bab63778f6c31a8de56cfaf5d4

Server is already getting these working as Warrior class, didn't see any point not to change to Warrior :

```sql
UPDATE `creature_template` SET `unit_class`= 1 WHERE `unit_class`= 0 AND !ISNULL ( unit_class );
```

**Comment by Aokromes** [comment]
It's hackfix, the creatures needs to be compared with retail, not change class to some random class without known on the future what needs to be fixed.

**Comment by funjoker** [comment]
> Server is already getting these working as Warrior class, didn't see any point not to change to Warrior :

Server is handling it as Warrior, if data is missing to not cause crashs.
Exception in Core doesn't mean to be a hackfix.

Normaly the unit_class should be sniffable. @Vincent-Michael does a lot of templates, maybe ask him.

**Comment by adryan66** [comment]
Closed because I've checked it a lot better and found more bugs then fixes, seems this way it's not the right way since 3.3.5 is a little bit too different. Will post a different way in a little while.
