### ISSUE TITLE
[master] Missing Stats from Character Stats Panel

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18465]
**Description:** Stats missing from Character Stats panel

**Current behaviour:** (Tell us what happens.)
Some stats don't show like they should.

**Expected behaviour:** (Tell us what should happen instead.)
Character Stats Panel should be - (Taken from Retail)  : 
- item level
- agility / intellect / strength (primary stat of the current spec and class)
- stamina (always)
- armor (always)
- mana regen (druid - restoration / monk - mistweaver / shaman - restoration / priest - discipline+holy / paladin - holy) 
- crit (always)
- haste (always)
- mastery (always)
- versatility (always except demon hunter - vengeance+havoc)
- leech (only if you have items with this stat)
- avoidance (only if you have items with this stat)
- dodge (druid - guardian / demon hunter - vengeance / warrior - protection / monk - brewmaster / death knight - blood / paladin - protection)
- parry (demon hunter - vengeance / warrior - protection / monk - brewmaster / death knight - blood / paladin - protection)
- block (warrior - protection / paladin - protection)

Edit : Speed doesn't show at all.
One issue : Not sure which group is first , leech/avoidance or dodge/parry/block since I don't have tanks with tertiary stats on live.

**Steps to reproduce the problem:**

1. Create a character
2. Press "C"
3. Check Character Stats Panel

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) : master

**TC rev. hash/commit:**  TrinityCore rev. a346fd2baf25

**TDB version:**  TDB 703.00

**Operating system:**  Win 10 Pro x64

**Comment by RedSonja** [comment]
Is there any news on this issue?

**Comment by tkrokli** [comment]
Apparently not.

**Comment by RedSonja** [comment]
Has the information been moved to another table?

**Comment by Shauren** [comment]
The server does not control the UI displaying stats, it can only set the stat values (like, you have 5% haste)

I say there is no bug here

**Comment by RedSonja** [comment]
I am not talking about UI display I am talking about in the Character_stats table in the Character DB. They do not show anything that is new at all. I am wondering why?

**Comment by Shauren** [comment]
But the issue isn't about `character_stats` table (thats simply not implemented)
