### ISSUE TITLE
[3.3.5] Immolate procs aftermath / conflag consumes aftermath

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18469]
**Description:** Noticed there are proc issues with immolate/conflag/aftermath.

**Current behaviour:** (Tell us what happens.) ONLY conflag should trigger aftermath.

**Expected behaviour:** (Tell us what should happen instead.) Immolate triggers aftermath, and then when you use conflag, it doesnt even apply a new aftermath.

**Steps to reproduce the problem:**

1. Cast immolate on a target (i used a dummy)
2. Notice it gets the aftermath daze
3. Cast conflag, doesnt trigger aftermath again.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**   https://github.com/TrinityCore/TrinityCore/commit/bad4b059c8652173d97891aa5a8a326ac0718961

**TDB version:**  TDB 335.62

**Operating system:**  ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
i cant reproduce it in rev 9486123afbaedfe33d7e9983d7f06f850f73bac6

**Comment by Persephone** [comment]
image here: 

http://puu.sh/sNZTc/c7f8be3082.jpg

**Comment by Keader** [comment]
only if issue intrudoced after 9486123afbaedfe33d7e9983d7f06f850f73bac6
btw, i'm updating my core, and i will test again xd

**Comment by Persephone** [comment]
Alrighty, i have the core on auto update, so every db update has been applied. Cant see to tell why it procs on immolate :/

**Comment by Keader** [comment]
Ok, tested in ff6c48732da63bfac6987203b94f343cbca74fb7 with a fresh and updated DB, and Aftermath only proc when i use conflagrate.

**Comment by Persephone** [comment]
Wtf lol. Havent changed anything that regards the spell/proc system at all. Is there something i can do to debug it to locate the issue?

**Comment by Keader** [comment]
spell_proc table

**Comment by Persephone** [comment]
Could i by any chance talk you into sending me a copy of your spell_ tables? :/ So i can give it a go? Their a few mb, would take me ages to get a full new tdb and apply all updates

**Comment by Persephone** [comment]
Something is wrong with my tables indeed, counterspell procs on every mage spell as well:

http://puu.sh/sO2ST/eb00081c3f.jpg

**Comment by Persephone** [comment]
https://community.trinitycore.org/profile/861-mr-blazzar/

my TC profile if ya cant send links over here, really hope you can do this, would save me tons of time mate <3

**Comment by Keader** [comment]
https://www.dropbox.com/s/6efopzxgdrhyygn/spell_proc_inserts.sql?dl=0

**Comment by Persephone** [comment]
thaaaank youu! let me try

**Comment by Persephone** [comment]
wtf nope >.< counterspell still procs on every mage spell and immolate still the same wthhhh

**Comment by Keader** [comment]
dont looks like trinity issue xd
try with a clean core and clean DB :)

**Comment by Persephone** [comment]
Im downloading atm, is there anything i can do to locate the issue tho? :/ must be something im missing

**Comment by Keader** [comment]
idk, only ariel- knows about proc system right now xd

**Comment by Persephone** [comment]
Can we summon @ariel-  somehow? xd Dying to know how to figure this out

**Comment by Jildor** [comment]
Why close?

**Comment by Keader** [comment]
Because is working in clean tc

**Comment by Jildor** [comment]
ah! oks, Had misunderstood xD
