### ISSUE TITLE
[3.3.5] Druid Cat & Bear damage melee state

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18460]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Druid Cat & Bear state melee damage is 2x , but other state with commit e8528717a55fbddf1ad6a7061aae5f7e293b18af correct and fixed.
issue #18435 about this problem .
please recheck it.

Edit:
![3_wow-guldan1](https://cloud.githubusercontent.com/assets/23469404/21110904/655f782e-c0b4-11e6-83f5-8b1d96486749.jpg)

![3_wow-guldan1](https://cloud.githubusercontent.com/assets/23469404/21110963/9f6e55bc-c0b4-11e6-8b0f-18e0daa34495.jpg)

**Branch(es):** 3.3.5 (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  01d272d6cb348c968c531620c341f760e50cb97b

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Jildor** [comment]
Confirm, the causant is this commit:
https://github.com/TrinityCore/TrinityCore/commit/6dc37a9add631888fe5fbcd43d19c2b07bed8a57

**Comment by Noryad** [comment]
Confirmed, druids (cat form) are doing a very hight damage.

**Comment by tkrokli** [comment]
I know it is a bit late now that the issue is closed with a solution, but it I don't think it hurts to have a couple of labels to highlight what this issue is about.

**Comment by Jildor** [comment]
![ned flanders post its](http://i.imgur.com/Sqh0b.png)

**Comment by MrDelta** [comment]
Confirmed.

**Comment by ariel-** [comment]
@MrDelta did you try commit bad4b059c8652173d97891aa5a8a326ac0718961?

When you say "confirmed" it's expected that you updated your source before, and specify the TC hash of your source in which you "confirm" the issue.
