### ISSUE TITLE
[CRASH] Object::GetGuidValue

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#18461]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Object::GetGuidValue

**Current behaviour**: Tell us what happens
Not sure why is this happening. almost 2-3 per hour.

- http://pastebin.com/hLz60wvt
- http://pastebin.com/VPMmzCmG
- http://pastebin.com/DbBj9jw6
...

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know, apartently this involve some pets.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
45f8135ac45799e555449bebb6d2a78869a439b6

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by sirikfoll** [comment]
Introduced in https://github.com/TrinityCore/TrinityCore/commit/01d272d6cb348c968c531620c341f760e50cb97b
`caster` can be nullptr

**Comment by Keader** [comment]
@ariel-

**Comment by Mrgrasser** [comment]
again have crash maybe for this
[crashlog.txt](https://github.com/TrinityCore/TrinityCore/files/658950/crashlog.txt)

**Comment by Mrgrasser** [comment]
if paladin [Divine Intervention] cast on the target fury warrior and warrior after relog give +damage for this server crash.
this work is bug but now don't work, but have crash.

**Comment by n4ndo** [comment]
Who we need to invoque @Keader ?

**Comment by n4ndo** [comment]
you still have that crash @Mrgrasser ?
