### ISSUE TITLE
[master] bnetaccount create command

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18474]
**Description:**
Bnetaccount create error.
**Current behaviour:** (Tell us what happens.)
Errors after creating account , account succesful even with them.
**Expected behaviour:** (Tell us what should happen instead.)
No Errors
**Steps to reproduce the problem:**

1. Start worldserver
2. Type ".bnetaccount create <user> <pass>" or even a wrong command like "bnet account create x y" and it will show the same error , followed by there is no such command, which is normal.
3. Check worldserver
It will show something like for the first time , after that it won't from what I've noticed : 

```
Table `command` contains an unexpected subcommand 'package' in command 'scene play package', skipped.
Table `command` contains a non-existing subcommand 'scenes' in command 'reload scenes', skipped.
```

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
TrinityCore rev. ac1dc758b98b
**TDB version:**  
703.00
**Operating system:**  
Win 10 x64 Pro

**Comment by Shauren** [comment]
Not related to any command, just bad data in world.commands table
