### ISSUE TITLE
should healing reduce active on boss ?

### ISSUE THREAD

**Issue by Xxxhackerxxx** [TrinityCore/TrinityCore#18478]
hi,
should healing reduce active on boss ?
for example on this boss :
ferya
anub'arak 
and ...

**Comment by Aokromes** [comment]
This is not a forum, if you don't known if should or don't, don't post it here. Also, no revision at all.

**Comment by tkrokli** [comment]
Yes, please use https://community.trinitycore.org/ for general questions about how the source works.
