### ISSUE TITLE
[master] Beacon of Light server crash.

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18475]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Beacon of Light server crash.

**Current behaviour:** Holy Paladin's spell Beacon of Light if used more than once in the same group/raid progressively continues to multiply healing. It causes server to copy healing 2-4-8 and more times, eventually crashing the server at x16+ values. 

**Expected behaviour:** Beacon of Light should copy 40% of casted spell only once.

**Steps to reproduce the problem:**

1.  Create a paladin, change spec to Holy, use .levelup or .learn to get Beacon of light.
2.  Join a party and cast Beacon of Light few times on different targets. After it cast any healing spell, Flash of Light for example.
3.  With every cast of Beacon it will multiply healing copies, that eventually will crash the server on 20+ copies.

**Branch(es):** master 

**TC rev. hash/commit:**  bfa9a4c9597c748734836fa2293f1ccf9724dbba

**TDB version:** TDB 703.00

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Thanks for following the issue report template but it is fundamental that you post a crashlog for crash related problemas.

**Comment by Eredar** [comment]
[bfa9a4c9597c_worldserver.exe_[14-12_15-5-27].txt](https://github.com/TrinityCore/TrinityCore/files/651667/bfa9a4c9597c_worldserver.exe_.14-12_15-5-27.txt)

**Comment by robinsch** [comment]
release crashlog doesn't help

**Comment by jackpoz** [comment]
Please build in RelWithDebInfo or Debug, reproduce the issue and post the crashlog.
There's a topic on forum with some additional details
