### ISSUE TITLE
[master] Scenario locations of Legion & WoD crashes.

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18476]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Scenario locations of Legion unavailable and forces client/server crashes when you try to get there.

**Current behaviour:** Server and/or client crashes with "unknown opcodes" errors.

**Expected behaviour:** Sucsessiful loading, no errors server/clientside.

**Steps to reproduce the problem:**

1.  Start the server, create any character.
2.  Try to get into Broken Shore/Azsuna/Other scenario zones. For example: .go 84.3099 1942.78 14 1460 or .go 301.491 7320.21 149.96 1461 or I guess almost any other Legion scenario zone.
3.  You will get client or server crash after loading will be almost complete. Mostly client crashes.

**Branch(es):** master

**TC rev. hash/commit:**  bfa9a4c9597c748734836fa2293f1ccf9724dbba

**TDB version:**  703.00

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Krudor** [comment]
You cannot enter scenario map type outside the LFG system.
They don't have dbc entries to support porting in manually (no difficulty data)

**Comment by Eredar** [comment]
Any way to fix this? I tested many solo scenario zones that appear in WoD(final location scenarios) and Legion(artifact scenarios). They arent using lfg system on blizzard servers, but still I get same crashes in their zones, for example Defence of Karabor solo(!) scenario: .go 577.7621 -2459.259 96.08557 1277

> Received not handled opcode [CMSG_QUERY_COUNTDOWN_TIMER 0x31A2 (12706)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS 0x328D (12941)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_DF_GET_JOIN_STATUS 0x3612 (13842)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_DF_GET_SYSTEM_INFO 0x3611 (13841)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_LFG_LIST_GET_STATUS 0x3609 (13833)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_REQUEST_LFG_LIST_BLACKLIST 0x327E (12926)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32CA (13002)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_DISCARDED_TIME_SYNC_ACKS 0x3A3C (14908)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
> Received not handled opcode [CMSG_DISCARDED_TIME_SYNC_ACKS 0x3A3C (14908)] from [Player: Eversong GUID Full: 0x08000400000000000000000000000001 Type: Player Entry: 0 Low: 1, Account: 1]
>

**Comment by Krudor** [comment]
No, there's no way to simply fix or implement something that would get this to work.
Scenarios can have different difficulties, and they are selected by the LFG system depending on what you queue for.

Like for the traditional maps, as I said, there is no difficulty data for scenarios, so they cannot and will not be able to be launched manually at any point. The best you could arrive at is a hack implementation to be able to enter scenarios manually, and then only a single difficulty would be available, as there's no way of selecting what difficulty a scenario is to be launched as, and that'll never be implemented in TrinityCore.

To be able to enter Scenarios, LFG needs to be working.

**Comment by Krudor** [comment]
void Player::SendInitialPacketsBeforeAddToMap()
...
worldServerInfo.InstanceGroupSize = GetMap()->GetMapDifficulty()->MaxPlayers;

this is what is causing the crash, GetMap()->GetMapDifficulty() returns nullptr

**Comment by Shauren** [comment]
That value is wrong anyway, it should send the real number of players for dynamically scaling raids (between 10 and 30)

**Comment by Eredar** [comment]
Scenarios in most cases have only one difficulty, only few pandaria scenarios have heroic mode. 

Can I teoretically hackfix them through dbc editing and adding to instance_template as normal dungeons?

**Comment by Krudor** [comment]
No I don't think so.
The server still won't know what difficulty you want to launch the map as.

**Comment by Shauren** [comment]
Server ALWAYS needs a difficulty entry, entering through LFG is not an exception

**Comment by Krudor** [comment]
What about the scenarios with missing difficulty entries, how do we handle them?

**Comment by Eredar** [comment]
Also there were scenarios in open world, like pre-Legion invasion event, what about them? They didn't have player/faction limits.

**Comment by Krudor** [comment]
You're confusing scenarios with the instance type scenario.

**Comment by Eredar** [comment]
Nope, all of them have separate area, like garrisons, so basically they all "instance type". Blizzard implemented smooth loading, almost invisible, but even on their server client stucks (load this zone) for a half second when you enter such zones.

**Comment by Eredar** [comment]
Watched playerlimit field in MapDifficulty.db2, open world maps, like broken shore, prelegion invasion and other similiar have 80 player limit.
