### ISSUE TITLE
[master] [OS X] Connection patcher

### ISSUE THREAD

**Issue by Toooorch** [TrinityCore/TrinityCore#18473]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
**Description:**
After patch World of Warcraft.app >> Patched.app crashing after attempt to login to the server. Immediately after login datas are filled...

Hopefully this Error files which generate patched.app will be useful.

[http://files.michalsoukup.com/[master]%208b2e071%20-%20Errors.zip](url)

**Current behaviour:** (Tell us what happens.)
I think problem is in patched client because on Windows I don't have this problem.

**Expected behaviour:** (Tell us what should happen instead.)
Successful login into server

**Steps to reproduce the problem:**

1. Compile connection_patcher from 8b2e071
2. patch World of Warcraft inside World of Warcraft.app >> generate Patched.app
3. Try to login into server

**Branch(es):** 
master

**TC rev. hash/commit:**  
8b2e071

**TDB version:**  
TDB_world_703.00_2016_10_17

**Operating system:**  
macOS 10.12.1 / 10.12.2 Beta (16C63a)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18145
