### ISSUE TITLE
[master] Creature Loot Tables Update.

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18477]
Feedback apreciated :)

First, partial loot tables for stonetalon : 
https://gist.github.com/adryan66/1309c62b059435d2b51d203a86176be8
Made by me, not finished, data taken from wowhead.

Second, big loot update : 
https://mega.nz/#!FhAhWQwB!dI_zysRAuRBEOEzMw519WiFim4cguZ-ra0hy8SUriDs
Taken from a 5.4.8 server, no idea which one since version in the db is empty and tested a while with zones like darkshore / stonetalon which had 0 loot tables, with this they have. 
Also checked the data randomly with wowhead (impossible to check each and every one unless someone has a different way) and it's very close to the drop % there (changes from time to time, it's not exact either).
Kept all current loot tables, added only different one's and with mobs that didn't have any. If im not wrong it might be loot even for pandaria, no idea since trinity doesn't have it spawned yet and didn't had time to check. Credit for this one goes to whoever made it.

**Comment by Maibenrai** [comment]
I have an old tool from 2012 for creating those from Wowhead. 
Need updating for new creature_loot_template.
For example.:


 E:\Dropbox\PHP>loot.exe c 4018

```SQL

-- http://www.wowhead.com/npc=4018 | Antlered Courser - NPC - World of Warcraft
DELETE FROM `creature_loot_template` WHERE `entry` = 4018;
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(4018, 1747, 0.0442, 1, 0, 1, 1), -- Linked Chain Boots
(4018, 1823, 0.2654, 1, 0, 1, 1), -- Bludgeoning Cudgel
(4018, 1824, 0.2654, 1, 0, 1, 1), -- Shiny War Axe
(4018, 3378, 0.4865, 1, 0, 1, 1), -- Brocade Belt
(4018, 5120, 2.6095, 1, 0, 1, 1), -- Long Tail Hair
(4018, 5471, 39.0535, 1, 0, 1, 1), -- Stag Meat
(4018, 5566, 21.1411, 1, 0, 1, 1), -- Broken Antler
(4018, 5871, 8.0495, 1, 0, 1, 1), -- Large Hoof
(4018, 14125, 0.3096, 1, 0, 1, 1), -- Ritual Leggings
(4018, 56156, 40.2477, 1, 0, 1, 1); -- Torn Cartilage

**Comment by adryan66** [comment]
Can you post it by any chance ? And does it update all entrys in old template corectly, like chance to negative for quests ?
Might still be useful :)

**Comment by Maibenrai** [comment]
Here it is http://pastebin.com/0UxdmzkM
I haven't studied PHP or programming so it's ugly as hell.

**Comment by adryan66** [comment]
Well neither have I but I will try to see if I manage anything :)
If anyone more skilled wants to help it would be great.

**Comment by ZxBiohazardZx** [comment]
As someone who used to do "proper" looting tables i would recommend searching for patterns instead of wowhead information. For creatures there usually exists trash loot, questloot and some sort of garanteed drops. Having all these minute %chances usually indicates you get 1 out of 200 items in trashloot (garanteed)

**Comment by adryan66** [comment]
Closing because of #18538 which is a better solution to the problem.

**Comment by Aokromes** [comment]
there is no need of close old issues, you can edit existing one.
