### ISSUE TITLE
[3.3.5] Spell: Catapults should be immune to Cyclone.

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18489]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Catapults can be affected by cyclone and should not. The cyclone delays the catapults but does not make them immune to damage. This may causes that the best strategy in battlegrounds like Strand of the Ancients is to have as many druids as possible.

**Current behaviour:** 
Catapults can be affected by cyclone.

**Expected behaviour:** 
Catapults should not be affected by cyclone.

**Steps to reproduce the problem:**
1. Druid casts cyclone to catapults in Strand of the Ancients.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  4e3ce04

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lostsoul123** [comment]
So many bugs with this cyclone spell...
What you need to do in this case is adding a mechanic_immune_mask to the creature now i think the entry for this creature is : http://www.wowhead.com/npc=27881
So a possible fix would be combining the mechanics and inserting a new value to the creature_template
(The current Combined value of mechanic_immune_mask =344276858 . so just add +131072 which is the MECHANIC_BANISH which then equals : 344407930)


UPDATE `world`.`creature_template` SET `mechanic_immune_mask`='344407930' WHERE  `entry`=27881;


now i havent tested this myself so it would be nice if you would comment the outcome thanks
Here's the link for creature_template wiki : https://trinitycore.atlassian.net/wiki/display/tc/creature_template
