### ISSUE TITLE
[7.x]: Port QAston proc system from 3.3.5 to master ($20 Bounty)

### ISSUE THREAD

**Issue by Seyden** [TrinityCore/TrinityCore#18485]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** QAstons new proc system needs to be ported from 3.3.5 branch to master branch

**Current behaviour:** Actually QAstons new proc system is only available in the 335 branch

**Expected behaviour:** Should work too in master branch

**Branch(es):** master

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
https://www.bountysource.com/issues/40091466-7-x-port-qaston-proc-system-from-3-3-5-to-master-20-bounty

**Comment by DoctorKraft** [comment]
Close by https://github.com/TrinityCore/TrinityCore/pull/20131

**Comment by tkrokli** [comment]
Good for joschiwald -- I hope @Seyden concurs. 😄
