### ISSUE TITLE
7.x Reward PvP System

### ISSUE THREAD

**Issue by andryus** [TrinityCore/TrinityCore#18480]
**Description:**
Does not the PvP rewards system work?

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

Go to Battleground 

**Branch(es):** Master

**TC rev. hash/commit:**  Trinity Core Re Unknown

**TDB version:**  7.0.3

**Operating system:**   Windows 7 - 64bits

**Comment by Deadlineem** [comment]
typing .mod honor <desired value> returns NOT IMPLEMENTED: <amount> honor NOT added.

**Comment by Golrag** [comment]
I have something for honor but there are still some missing things I would like to fix before I make a PR :/
Will see if I can do it tomorrow :)
