### ISSUE TITLE
[3.3.5] Spell/Druid: Cyclone not work properly with Pain Suppression

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18487]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Cyclone: Tosses the enemy target into the air, **preventing all action** but making them invulnerable for up to 6 sec...
The problem is that the priest under the effects of cyclone can cast Pain Suppression to a party member and should not.

**Current behaviour:** 
Priest under the effects of the cyclone can cast Pain Suppression to a party member.

**Expected behaviour:** 
Priest under the effects of the cyclone can not cast Pain Suppression to a party member.
The possible message : "Can't do that while banished" like the rest of spells in similar scenarios.

**Steps to reproduce the problem:**
1. Go to PVP Zone, for example Gurubashi.
2. Summon a Druid, a Priest and a Player X (in party with the priest).
3. Druid casts cyclone to Priest.
4. Priest casts Pain Suppression to Player X.
5. Player X receive Pain Suppression.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  4e3ce04

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by CDawg** [comment]
I don't remember, but can a priest summon Pain Suppression on themselves while under the cyclone?
If not, this may be an easy fix.

**Comment by ariel-** [comment]
Did this happen before the Immunity commits? Pain Suppression has castable while stunned flag, Cyclone is a stun aura (despite the banish mechanic)

I would like to get source for this one, as it seems logical

**Comment by Warpten** [comment]
Patch 3.2: Pain Suppression : No longer can be cast while under the effects of Incapacitate or Cyclone.

**Comment by Warpten** [comment]
You need to use mechanic rather than the aura type

**Comment by Noryad** [comment]
@ariel- Confirmed, before the immunity commits (like 3d5c1b8) works the same. Priest under the effects of the cyclone can cast Pain Suppression to a party member, not himself.

**Comment by Eliminationzx** [comment]
Also problem with death grip vs ice block, divine shield. Death grip piercing through immunity. https://github.com/TrinityCore/TrinityCore/commit/c809c220e29f7094121cc8489f5588d8bfee414d Sorry if it's wrong place for issue.

**Comment by Keader** [comment]
@Eliminationzx make a new ticket about this one please ^^
