### ISSUE TITLE
[DK] Blood Presence doesn't reduce threat by 20%

### ISSUE THREAD

**Issue by Poli93** [TrinityCore/TrinityCore#18484]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
"Strengthens the Death Knight with the presence of blood, increasing damage by 15% and healing the Death Knight by 4% of damage dealt. Only one Presence may be active at a time.
In addition to the aforementioned tooltip description Blood Presence should also reduce threat generation by 20% whilst in Blood Presence.
Apply Aura: Mod Threat (127) 
Value: -20

This addition isn't written in the tool-tips nor can be found in most sites, although if you check the auras applied by the Presence through openwow or old.wowhead you can see it also applies a mod threat aura.

**Current behaviour:** (Tell us what happens.)
I've been testing the presence for quite some time now, proving my statement is highly unlikeable, there are no many ways to calculate threat. What I've done with a couple of teammates was test it mostly on dummies and creatures, I've tried calculating the TPS and generated threat of my abilities through Omen3 and Skada, while being in Blood Presence, Unholy Presence, Frost Presence and with no Presence at all (This can be achieved by committing suicide and not selecting a presence when return back to life).

**Expected behaviour:** (Tell us what should happen instead.)
Blood Presence should also reduce the generated threat of the Death Knight's abilities by 20%. 

**Evidence to support my claim:**
http://wotlk.openwow.com/spell=48266
https://web.archive.org/web/20100810200349/http://www.wowhead.com/spell=48266
Effect #3:	Apply Aura: Mod Threat (127) = Value: -20

**Steps to reproduce the problem:**
1. Use a variety of skills against a dummy in all presences while measuring their threat with any capable addon.
2. Switch between the presences and see the threat change.
3. Grab a calculator.

**Note:**
I do not really know which operating system the realm I'm playing at is using nor it's hash or anything of this sort.
I know it makes your life a whole lot harder but I'm more interested in figuring out whether I'm right or not, so I know if working on a fix is needed.
I'm not an expert with coding so I wasn't able to find the specific code for this presence, I appreciate if any of you could guide me to where the code is at or maybe you could take a look at it and see if there's any threat reduction aura applied at all.

I appreciate any assistance whatsoever.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
> (This can be achieved by committing suicide and not selecting a presence when return back to life).

Dying does not remove the presences, the only way to achieve this is by use of `.unaura` command

And MOD_THREAT auras are handled correctly.

**Comment by Poli93** [comment]
I've also had a GM .unaura the Blood Presence just so you'd know, I thought dying also provided the same effect but I guess I was mistaken, when testing I had a Game Master accompany me.
Any chance you could guide me to where the MOD_THREAT aura is within the code ariel? I would be immensely appreciative.

**Comment by ariel-** [comment]
Sure, have at it: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L2712

In the future, just search in the code for the desired Aura (Use [SpellWork](https://github.com/TrinityCore/SpellWork) tool to get aura name)
