### ISSUE TITLE
[3.3.5] Core/Spells: spells should be disabled when not usable

### ISSUE THREAD

**Issue by djbarrueco** [TrinityCore/TrinityCore#18488]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I found several spells that are active while they can not be used. This causes that spells put into cooldown without being used. These are Ice Block, Divine Shield, Pain Suppression, Bestial Wrath.

**Current behaviour:**
Spells are enabled while they can not be used.

**Expected behaviour:** 
Spells should be disabled while they can not be used.

**Steps to reproduce the problem:**
1. Ice Block: Mage (under effects of cyclone) casts Ice Block, nothing happens, Hypothermia not appear and the spell is put into cooldwon.
2. Divine Shield: Paladin (under effects of cyclone) casts Divine Shield, nothing happens, Forbearance not appear and the spell is put into cooldwon.
3. Pain Suppression: Priest (under effects of cyclone) casts Pain Suppresion, nothing happens and the spell is put into cooldwon.
4. Bestial Wrath: Hunter (out of LOS with the pet) casts Bestial Wrath, nothing happens and spell is put into cooldwon. (Related with #10198)

Note:  Likely exist more spells with the same problem.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  4e3ce04

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lostsoul123** [comment]
possible fix:
@@ src/game/spells/spell.cpp
SpellCastResult Spell::CheckCast(bool strict, uint32* param1 /*= nullptr*/, uint32* param2 /*= nullptr*/)
{
//Cant use spell while cycloned...we can either write HasAura(33786) or just mechanic_banish + mechanic stun
	+//which i prefer mechanics ^^
	+if (m_caster->HasAuraWithMechanic(MECHANIC_BANISH) && m_caster->HasAuraWithMechanic(MECHANIC_STUN))
		+return SPELL_FAILED_STUNNED;
...
}

**Comment by ariel-** [comment]
Pain suppression no longer an issue after 27fb5fc16d88c0002898981009bedc6b8001cac7

**Comment by joshwhedon** [comment]
I can confirm for Ice Block and Divine Shield that we should not be able to cast the spell (should get an error message) according to some wiki information. At the moment those can be casted, even if ultimately the caster is immune to the spell.
I think there are two things:
In CheckCasterAuras, usableWhileStunned should not concern spells with MECHANIC_BANISHED.
But even when ignoring those spells, CheckCasterNotImmunedStunAuras still allows the spell to be casted.

**Comment by joshwhedon** [comment]
It could be because only SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE is checked, and not SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE which is the one Cyclone has.

**Comment by joshwhedon** [comment]
So I tried the following:
I have set usableWhileStunned to false anytime the user has an aura of mechanic BANISHED.
Then I updated the following method to take into account the attribute, and to use the _immunityInfo[i].MechanicImmuneMask instead of comparing the miscvalues, since SPELL_AURA_MECHANIC_IMMUNITY can have specific cases (for example the pvp trinket). I am not saying it is the right way to do it, but it may help you find the right way.

bool SpellInfo::CanSpellCastOverrideAuraEffect(SpellInfo const* auraSpellInfo, uint8 auraEffIndex) const
{
    if (!HasAttribute(SPELL_ATTR1_DISPEL_AURAS_ON_IMMUNITY))
        return false;

    if (auraSpellInfo->HasAttribute(SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY))
        return false;

    for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
    {
        if (Effects[i].Effect != SPELL_EFFECT_APPLY_AURA)
            continue;

        uint32 const miscValue = static_cast<uint32>(Effects[i].MiscValue);
        switch (Effects[i].ApplyAuraName)
        {
            case SPELL_AURA_STATE_IMMUNITY:
                if (miscValue != auraSpellInfo->Effects[auraEffIndex].ApplyAuraName)
                    continue;
                break;
            case SPELL_AURA_SCHOOL_IMMUNITY:
            case SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL:
                if (auraSpellInfo->HasAttribute(SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE) || auraSpellInfo->HasAttribute(SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE) || !(auraSpellInfo->SchoolMask & miscValue))
                    continue;
                break;
            case SPELL_AURA_DISPEL_IMMUNITY:
                if (miscValue != auraSpellInfo->Dispel)
                    continue;
                break;
            case SPELL_AURA_MECHANIC_IMMUNITY:
            {
                uint32 immuneMask = _immunityInfo[i].MechanicImmuneMask;
                if (!(immuneMask & auraSpellInfo->Mechanic))
                {
                    if (!(immuneMask & auraSpellInfo->Effects[auraEffIndex].Mechanic))
                        continue;
                }
                break;
            }
            default:
                continue;
        }

        return true;
    }

    return false;
}

**Comment by joshwhedon** [comment]
Forget what I said, after some player tests, this breaks other things even more :D.

**Comment by Noryad** [comment]
@joshwhedon Thanks for trying

**Comment by CraftedRO** [comment]
835e2918319e This seems no longer valid :
1

https://user-images.githubusercontent.com/24683355/213872600-6744cecb-abdc-4abf-b9a6-9446c7dfda4a.mp4


2

https://user-images.githubusercontent.com/24683355/213872610-1877fc1c-4908-4c1e-9c08-2361931a43f2.mp4


3

https://user-images.githubusercontent.com/24683355/213872629-fa930282-9ce5-474f-bcc9-56167d5dde03.mp4


4.Still valid but already reported in the other ticket.

https://user-images.githubusercontent.com/24683355/213872832-aa105f39-6c00-446f-a73a-c20e9743f95e.mp4
