### ISSUE TITLE
[3.3.5] Spell/Druid: Cyclone not work properly with Thunderstorm

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18497]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Cyclone: Tosses the enemy target into the air, **preventing all action** but making them invulnerable for up to 6 sec...
The problem is that the shaman under effects of cyclone can cast Thunderstorm and should not.
About Thunderstorm: Patch 3.2.2 (2009-09-22): Can no longer be used while Frozen, **Cycloned**, Sapped, or Incapacitated.

**Current behaviour:**
Shaman under effects of cyclone can cast Thunderstorm.

**Expected behaviour:** 
Shaman under effects of cyclone can not cast Thunderstorm.

**Steps to reproduce the problem:**
1. Druid casts cyclone to Shaman.
2. Shaman casts Thunderstorm.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  c809c22

**TDB version:**   TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Dalgurakk** [comment]
Again problems with Cyclone, confirmed in 13031f3.
