### ISSUE TITLE
[master] Shadow Projection issues (game video settings)

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18492]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Noticing some shadow issues with patrolling Wretched Urchins. They are on the upper levels but their shaows are walking by me on the ground level. Possibly cosmetic issue?

**Current behaviour:** (Tell us what happens.) Shadows walk around on ground level without a body to match them.
http://i.imgur.com/a3fDu7l.jpg

**Expected behaviour:** Shadows should stay with the respective player whence they come.

**Steps to reproduce the problem:**

1. Go to Commons Hall (Home of Thaelis the Hungerer)
2. Stand idle and observe shadows. Some are correct, some are not.
3. Go about your business

**Branch(es):** Master

**TC rev. hash/commit:**  6bfcdea

**TDB version:**  7.01

**Operating system:** Windows 10  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Most likely a cosmetic core issue where the floor is not defined to be "thick enough" to stop the shadows.

**Comment by BahDumbBugs** [comment]
Sunsail Anchorage in Eversong Woods also experiencing the same issue. New ticket and reference this, or leave here?

**Comment by tkrokli** [comment]
The problem itself is likely identical and caused by the same kind of handler, so it is better to generalize the title of this issue and add info about which places it is possible to replicate the issue by turning on shadow projection in the game settings (Video Settings, I presume).

**Comment by Shauren** [comment]
This is not a bug. You need to set shadow quality to High or better for terrain to give proper high quality shadows (below that level only nearby units generete them, such as npcs on upper floor)

**Comment by Warpten** [comment]
Even if it was a bug it wouldn't be anything we could handle serverside.
