### ISSUE TITLE
[Master] Warlock's 'Summon Demon' Not Working

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18493]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** My demon imp got  killed during a quest. I was unable to revive or summon him back. Logging in and out does not help. Button is responsive, but available minions do not appear to choose from. 

http://i.imgur.com/FOx0hvP.jpg

**Current behaviour:** See above. 

**Expected behaviour:** Available minions should be selectable to be summoned.

**Steps to reproduce the problem:**

1. Roll new Warlock
2. Have minion get killed
3. Try to revive.

**Branch(es):** Master

**TC rev. hash/commit:**  8b2e071

**TDB version:**  7.1.0

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Albyarion** [comment]
Just want to add up, that summoning is not possible as well even when having a soul shard in your inventory and being level 5 - this applies to MASTER Tree (date: 2/12/2017)

**Comment by funjoker** [comment]
#21016

**Comment by matanshukry** [comment]
Tested on master now, I managed to successfully re-summon my imp after killing him (using both .die and .damage commands), multiple times in a row.
Can be closed.
