### ISSUE TITLE
[3.3.5] aura stack reverse

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18495]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** buff or aura stack reverse don't works.
for example : warlock Talent [Molten Core] must after active when use spell for next spell must remove but 3 stack buff active for 15 sec !!!
this problem other classes will include mage , hunter & ...
or mage : if talent buff  [Hot Streak] active, don't remove for next spells and active for 10 sec !!! 
this is very big bug !!!

<details>

![wowscrnshot_121616_143041](https://cloud.githubusercontent.com/assets/23469404/21261160/038a5dd8-c39f-11e6-8fff-7309e31821f7.jpg)
![wowscrnshot_121616_143044](https://cloud.githubusercontent.com/assets/23469404/21261163/053164c4-c39f-11e6-8d1d-53885dfb66da.jpg)
![wowscrnshot_121616_143047](https://cloud.githubusercontent.com/assets/23469404/21261167/07db793a-c39f-11e6-9203-f464d6da22a4.jpg)
![wowscrnshot_121616_143051](https://cloud.githubusercontent.com/assets/23469404/21261169/09f7bb98-c39f-11e6-92d1-d22b66579f87.jpg)

![wowscrnshot_121616_145452](https://cloud.githubusercontent.com/assets/23469404/21261379/4543ba2a-c3a0-11e6-9e95-ff172691e962.jpg)
![wowscrnshot_121616_145455](https://cloud.githubusercontent.com/assets/23469404/21261380/48302926-c3a0-11e6-8f75-34aba2e4d04f.jpg)
![wowscrnshot_121616_145456](https://cloud.githubusercontent.com/assets/23469404/21261387/51794bfc-c3a0-11e6-8d33-d33fac1f4de0.jpg)
![wowscrnshot_121616_145458](https://cloud.githubusercontent.com/assets/23469404/21261390/5868e102-c3a0-11e6-8ba9-6ce6afd5b277.jpg)
</details>

**Current behaviour:** (Tell us what happens.) buff stacks don't remove 

**Expected behaviour:** (Tell us what should happen instead.) after any spells must remove ( if you have chance active )

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  2dbda3dc7e6d7055af4a3d4b260aac96df67b273

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
In rev 4e3ce0463c46540a25c02a503c3bf0064601df96 everything works fine...
building last rev to check again :)

**Comment by Keader** [comment]
Ok, tested in c809c220e29f7094121cc8489f5588d8bfee414d (last rev) with a clean core and clean DB, everything is working.
Tested with Mage (Hot Streak proc  issue) and Warlock (Molten Core issue).

**Comment by Mrgrasser** [comment]
everything working but after use one spell must remove [Hot Streak] and [Molten Core] , I don't say not work

**Comment by Keader** [comment]
Is working.
Hot Streak is removed when Pyroblast is casted.
Molten Core is removed when Incinerate or Soul Fire is casted.

**Comment by ariel-** [comment]
Anyone care to translate the issue?

**Comment by Keader** [comment]
Hot streak and molten core are never consumed...
But in clean tc is working...

**Comment by Eliminationzx** [comment]
[Fel domination](http://wotlk.openwow.com/spell=18708) not removed when pet is summoned.

**Comment by Keader** [comment]
Hmm i'm not test with fel domination

**Comment by Eliminationzx** [comment]
Also [Backdraft](http://wotlk.openwow.com/spell=47260) shouldn't be removed from modified cast by [Backlash](http://wotlk.openwow.com/spell=34939)
http://wowwiki.wikia.com/wiki/Backlash :

> "Wrath-Logo-Small Patch 3.2.2 (2009-09-22): When using Shadowbolt or Incinerate while having Backlash and Backdraft active, only Backlash will now be properly consumed."

**Comment by Keader** [comment]
Yeah confirmed... Backlash and Backdraft is removed when cast incinerate
And arcane misseles not consume arcane potency too xd

**Comment by Mrgrasser** [comment]
@Keader I don't know where you say work fine !!! after this commit 3a52ad8d38eb33155d4218023149c78afded779e problem has been created , I mind you don't test last TC

**Comment by Keader** [comment]
Your trinity or your DB is not clean.
Spells reported by **you** in this ticket **IS WORKING**.
**Spells reported by Eliminationzx is not working.**

**Comment by Mrgrasser** [comment]
I am not blind write Chromatic, if you test and say work fine but your the reason not is compelling "**Your trinity or your DB is not clean**" I a lot commit import in the my core and all work now this commit for your reason not work !!! lol , no problem now i find , so if any body have a lot change and release for himself now must Shift+Delete source !!!!! 

maybe close eye on the TC is better .
thank you to convince

**Comment by Eliminationzx** [comment]
Hot streak and molten core working as intended for me.

**Comment by Keader** [comment]
@Mrgrasser i dont say it.
You can have 2 Trinity. 1 clean for test/report stuffs and 1 personal. Then you can test If some modification that you did cause your issues.

**Comment by ariel-** [comment]
@Mrgrasser Noone stops you from forking TC repo, putting "your stuff" on it and don't give credit for TC devs.

But then you can't ask for support on your custom sources/db content. God knows what you have in there.
BTW commit https://github.com/TrinityCore/TrinityCore/commit/3a52ad8d38eb33155d4218023149c78afded779e has nothing to do with procs, and did not alter functionality of said spells reported by you.

**Comment by tkrokli** [comment]
@Mrgrasser : all we are asking you to do, when you report an issue, is that you have tested the issue in _unchanged_ & _unmodified_ TrinityCore source + DB in order to report something to be a bug in TrinityCore.
