### ISSUE TITLE
[master] Maelstrom and Insanity powers doesn't work

### ISSUE THREAD

**Issue by Skizooo** [TrinityCore/TrinityCore#18496]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Hello everyone, since legion they introduced new powers for some classes as maelstroms for shamans and changed some of them. Well I tried everything to add maelstrom and insanity on my servers , I even added power7 in characters table and maxpower7 in characters_stats table , but it didn't worked .Also, I changed `MAX_POWERS_PER_CLASS` to 7 in the shareddefines.h. Furthermore, only by looking at the order of powers in the shareddefines. it has a wrong order based on what my sniff's output says and based on the dbc file. Below you have an image with how our order is supposed to be based on the dbc file.
![powers in legion](https://cloud.githubusercontent.com/assets/14895884/21263622/2f939536-c398-11e6-831c-4cba4fae5651.png)
Some of the powers we have defined in there were deleted in patch 7.1 such as `POWER_DEMONIC_FURY` and `POWER_BURNING_EMBERS` , the warlock is using soul shards for all specs.
**Current behaviour:** (Tell us what happens.)
Shadow Priests doesn't have insanity when they use their shadow form and shaman elementals(after level 10) and shaman enhancement doesn't have maelstrom power bar.
**Expected behaviour:** (Tell us what should happen instead.)
Shadow Priests should have insanity when they use their shadow form and shaman elementals(after level 10) and shaman enhancement should use Maelstrom as main resource.
**Steps to reproduce the problem:**

1. Create a priest/shaman and log in game
2. .levelup 109 
3. Try to use shadow form or switch specs to elemental/enhancement for shamans.

**Branch(es):** master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/88676120586df7581677eca8d5e2724579c69482
**TDB version:**  

**Operating system:**  
Ubuntu 16.04 non-GUI.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eredar** [comment]
You can try to look how Holy Power was implemented and do something similiar. But holypower is bugged aswell, only 3 out of 5 available ingame.

**Comment by Skizooo** [comment]
@Eredar  I fixed  insanity & holly power issue, but I don t see any options for maelstrom

**Comment by Skizooo** [comment]
So, after a few more tests I found out that if you cast lava burst or any spells that generates maelstrom power you get this maelstrom power somewhere but it can 't be seen as a power bar

**Comment by Shauren** [comment]
Yes, only the bar is not visible but you still gain these powers

**Comment by Skizooo** [comment]
@Shauren  what do you think is the problem?

**Comment by Skizooo** [comment]
I will create a pull request for holy power

**Comment by Eredar** [comment]
I think on blizzard servers insanity is always available, not only in shadowform. I'll check it there and report later. Btw what about using specialization identifiers instead of spellauraeffects? This resources in most cases binded to a spec, not a spell.

**Comment by Skizooo** [comment]
@Eredar  you are right about specialization identifiers it can be fixed that way too, I will try to check it and report the results in here

**Comment by Ulduar** [comment]
Maybe for display power type need add data for https://github.com/TrinityCore/TrinityCore/blob/8444ab736568667cb6425757ce5f832cb6068379/src/server/database/Database/Implementation/HotfixDatabase.cpp#L644

// PowerDisplay.db2
// PowerType.db2
Or not?

**Comment by Skizooo** [comment]
@Ulduar  that's interesting, otherwise I don' t see the reason why those tables are there..

**Comment by Shauren** [comment]
These db2 files do not have any info about which shapeshift or player spec uses which power type.

**Comment by Skizooo** [comment]
Of course they don't have the info we need, but we have somehow to get that information from them

**Comment by Skizooo** [comment]
I was able to fix the Maelstrom power bar like this:
![maelstrom fix](https://cloud.githubusercontent.com/assets/14895884/21279130/01e2f20c-c3df-11e6-9762-30a8b6d35b8f.png)
in Player.cpp , at  void Player::ActivateTalentGroup(ChrSpecializationEntry const* spec) function, line 26094.
The proof is below:
![wowscrnshot_121616_215336](https://cloud.githubusercontent.com/assets/14895884/21279143/13d49a42-c3df-11e6-90d5-a47deb943848.jpg)

**Comment by Eredar** [comment]
PowerDisplay.db2 contains data of various boss energy pulls. Nothing related to players.

**Comment by Skizooo** [comment]
@Eredar  Thank you.
To extract the db2 data  I uploaded this program for you : [https://mega.nz/#!eYQWTZ6C!D4nWfgSNO-_aY4fNiohjcVfoXA33yyfhQ_jVG0uP_SE](url) , you open the files you need but you have to define the columns yourself using datastores files from our core.
