### ISSUE TITLE
[3.3.5] PlayerAI broken behavior

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18490]
Something in recent revs, broken PlayerAI.
**Players mind controlled, cant use any spells.**
Talking with Treeston about it, maybe should be something related with:

> Keader> https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/PlayerAI/PlayerAI.cpp
> Treeston> already found it
> Treeston> it calls canautocast
> Treeston> so canautocast returns false
> Treeston> when it should be true
> Treeston> which means no casts show up
> Treeston> selectappropriatecastforspell -> verifyandpushspellcast -> verifyspellcast -> spell::canautocast

PlayerAI implemented in #16899
Was working in 6 months ago (last time i checked xd)

**Steps to reproduce the problem:**

1.  Use 2 characters, enter in combat with some creature and with 1 character use: .cast back 71289 (or any other "mind control spell")
2.  Player mind controlled will not use spells.
3. If character is ranged (like mage) they dont start attack anyone (maybe because he cant use any spell)

With my Paladin, i saw error messages like: "You can do it while charmed"
And my laptop with core i5 2,40 Ghz cant build alot of "downgrade" revs to find what commit broken it

**Branch(es):** 3.3.5
**TC rev. hash/commit:**  2dbda3dc7e6d7055af4a3d4b260aac96df67b273

**Comment by ariel-** [comment]
Probably cast checks while charmed...

ref 425f6c3c34b72190e481ba89fd4757df238475d8
ref 50a3ce5703bdaa4fe16e2e773eabafa9a4818083 ([Relevant section](https://github.com/TrinityCore/TrinityCore/commit/50a3ce5703bdaa4fe16e2e773eabafa9a4818083#diff-952c711803610aa78110e4f92ff2516aR5761))
