### ISSUE TITLE
[Master] Winter Veil World Event not Working

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18503]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Winter Veil is supposed to be here as of 10:00 AM server time. Nothing on the Horde side is showing up. I have not checked Alliance side yet. The only thing I can find with Horde side is the Falconwing Square and by the Silvermoon FP where the commoners are giving the standard Winter Veil chatter. Orgrimmar has no tree nor is Greatfather Winter Present.

**Current behaviour:** Winter Veil is not in full swing. See photo. http://i.imgur.com/kXz4f7q.jpg

**Expected behaviour:** Winter Veil should be in full swing. 

**Steps to reproduce the problem:**

1. Go to Orgrimmar
2. Look in front of Great Hall
3. Nothing

**Branch(es):** Master

**TC rev. hash/commit:**  8b2e071

**TDB version:**  7.01

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by BahDumbBugs** [comment]
Confirmed all Alliance and Horde Capitals do not have Winter Veil decor or quests.

**Comment by offl** [comment]
![](https://media.giphy.com/media/2pjspMQCi70k/giphy.gif)

**Comment by conan513** [comment]
confirmed, the event is active but there's nothing to see

![aoap3b3](https://user-images.githubusercontent.com/459246/34318993-8371f6fe-e7d5-11e7-8c23-00b26c60c970.png)

**Comment by meji46** [comment]
Added all necessary spawns of the holiday. There are only decorations left that I'll add next year (if there is time)
