### ISSUE TITLE
[3.3.5] Spell/Warrior: Poleaxe Specialization not work properly with equipment methods

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18506]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Poleaxe Specialization (Rank 5): Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 5%.
If the warrior equips an axe/polearm Poleaxe Specialization works ok (crit chance increases by 5%). The problem is when the warrior (with axe/polearm equipped) changes the weapon by another (not axe/polearm) for example a mace. If the method used is "drag and drop" Poleaxe Specialization works ok (crit chance decreases 5%) but if the method used is "right click" or "macros" the crit chance does not decrease.

**Current behaviour:** 
The "right click" and "macros" equipment methods do not work with the Poleaxe specialization.

**Expected behaviour:** 
The "right click" and "macros" equipment methods should work ok with the Poleaxe specialization.

**Steps to reproduce the problem:**
1. Look the initial crit chance and equip an axe.
![1](https://cloud.githubusercontent.com/assets/30839/21288618/0bb8de46-c43d-11e6-9ebd-a15b417743ad.jpg)

2. Swap weapon using "drag and drop" method. Poleaxe Specialization works ok (crit chance decreases 5%).
![2](https://cloud.githubusercontent.com/assets/30839/21288689/703efdfe-c43e-11e6-8ee0-59063055a11d.jpg)

3. Equip the axe again.

4. Swap weapon using "macros" or "right click". Poleaxe Specialization not work (crit chance not decrease).
![3](https://cloud.githubusercontent.com/assets/30839/21288687/6b97dc8a-c43e-11e6-9a38-f0e3663a5d50.jpg)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2dbda3d

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Shauren** [comment]
Can you try a version before 7e83d7e22a82104e53f872758fc7fe835472782c ?

**Comment by Noryad** [comment]
@Shauren  tested in 19560fc and works ok, maybe de error was introduced in 7e83d7e.

**Comment by Shauren** [comment]
In this case, can I ask you for another test?
Could you do the same with bladestorm but swap weapons with drag&drop?

**Comment by Noryad** [comment]
Bladestorm is cancelled after swap weapon with "drag & drop" ("right click" and "macros" cancels Bladestorm  too). Tested in 19560fc.

**Comment by Shauren** [comment]
I meant bladestorm after 7e83d7e22a82104e53f872758fc7fe835472782c (since that is the commit that is supposed to "fix" it)

**Comment by Noryad** [comment]
Before 7e83d7e Bladestorm is canceled with swap weapon.
After 7e83d7e Bladestorm is not canceled with swap weapon but Poleaxe Specialization not work with "macros" and "right click".

**Comment by xinef1** [comment]
@Noryad check if it helps
https://github.com/TrinityCore/TrinityCore/commit/7e83d7e22a82104e53f872758fc7fe835472782c#commitcomment-20279526
