### ISSUE TITLE
[3.3.5] Spell/Death Knight:Frost Presence do not grant 8% endurance 

### ISSUE THREAD

**Issue by Dreacus** [TrinityCore/TrinityCore#18505]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The death knight takes on the presence of frost, increasing Stamina by 8%, armor contribution from cloth, leather, mail and plate items by 60%, and reducing damage taken by 8%. Increases threat generated. Only one Presence may be active at a time.
**Current behaviour:** (Tell us what happens.)
Frost Presence grant 60% armor but not the 8% Stamina bonus
**Expected behaviour:** (Tell us what should happen instead.)
Frost presence should grant both

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
c809c220e29f7094121cc8489f5588d8bfee414d
**TDB version:**  
3.3.5.62 + updates
**Operating system:**  
Windows 2012 r2

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eliminationzx** [comment]
Can't confirm. Work for me as intended.

**Comment by Dreacus** [comment]
please delet this issue , Frost presence works as intended 

test made with improved frost presence my bad
