### ISSUE TITLE
[3.3.5/Master] DB/Creature: Scarlet Infantryman missing weapons

### ISSUE THREAD

**Issue by Kizarr** [TrinityCore/TrinityCore#18508]
**Description:**
The NPCs are missing their respective equipment for weapons and should have all the gear equipped.

**Current behaviour:** The Scarlet Infantryman NPCs do not have weapons equipped.

**Expected behaviour:** The Scarlet Infantryman NPCs should have weapons equipped.

**Steps to reproduce the problem:**
1. Create a fresh Death Knight and complete quest line until you reach death breach go down below and you will see npc's with missing equipment.
http://image.prntscr.com/image/f24a6c7404ea4702b371585d0d473e53.png
http://image.prntscr.com/image/6fbfa55ca0b747e7bdf839ebbbfc8efd.png

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:** c809c22  

**TDB version:** TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows Server 2012 R2

**Comment by Aokromes** [comment]
#16416

**Comment by tkrokli** [comment]
... as well as https://github.com/TrinityCore/TrinityCore/issues/17821.

**Comment by Kizarr** [comment]
This is a different area then these bugs #17821 #16416 and this issue is separate from those.

**Comment by Kizarr** [comment]
It is located in creature_equip_template because I fixed this issue before manually I had to find the weapons and shield ID from wowhead for the npc's I spent a hours try to find the correct equipment on wowhead.

**Comment by tkrokli** [comment]
Please post the details in the existing bug reports. Unless there is very good reason to close the older issues, information from new duplicates should be reposted (or referred to) in the open ones.

Other than said rules for creating/updating issues, I think it takes more proof to reopen this one.

**Comment by Kizarr** [comment]
Okay first all my bug report is entirely differently location and npc's then this one report #17821 and this report doesn't even follow the template and lacks information #16416 and should be closed.

**Comment by tkrokli** [comment]
Maybe, but this is not a competition about who gets to have the open issue regarding this problem. We do recommend that you add your information to already existing open issues, because the point of keeping existing open issues (issues which have not been closed with a solution yet) is to keep a track record of how long this issue has been present. Ideally, the oldest open issue is always kept open and the new one closed.

**Comment by Kizarr** [comment]
May I ask which one of the two I should add it to then because one lacks information entirely and one is separate issue.

**Comment by tkrokli** [comment]
Use the issue page that fits your report best (the one that you think matches your problem).  We don't have exact rules for that question, it is more about which report/issue page covers it best and has the oldest list of comments as well. Some times you just need to apply your own judgement / common sense. :-)

**Comment by Kizarr** [comment]
Okay.

**Comment by Kizarr** [comment]
Patchfix it took alot of digging. Please correct my mysql
UPDATE `CreatureID` LIKE '28896' OR `ID` LIKE '1' OR `ItemID1` LIKE '38721' OR `ItemID2` LIKE '12932' OR `ItemID3` LIKE '5259' OR `VerifiedBuild` LIKE '18019'
UPDATE `CreatureID` LIKE '28609' OR `ID` LIKE '1' OR `ItemID1` LIKE '38723' OR `ItemID2` LIKE '12932' OR `ItemID3` LIKE '5259' OR `VerifiedBuild` LIKE '18019'

**Comment by tkrokli** [comment]
The SQL UPDATE command syntax you want to use in current TDB looks like this:
```sql
-- Scarlet Infantryman
UPDATE `creature_equip_template` SET `ItemID1`= 38721, `ItemID2`= 12932 WHERE `CreatureID`= 28609;
UPDATE `creature_equip_template` SET `ItemID1`= 38723, `ItemID2`= 12932 WHERE `CreatureID`= 28896;
```
`ItemID3` `5259`  is already in the table, so no need to add that.
