### ISSUE TITLE
[master] Problem using .bnet create.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18507]
**Description:**
We have a problem to create a Bnet account with the command ".bnet create user@user.com user user" that create an user in the table "battlenet_accounts" but not create the specific entry in the table "account" this account not les make a correctly login with the server.

**Current behaviour:** (Tell us what happens.)
Create the account using the command "bnet create" but only resgistrer it in table "battlenet_account".

**Expected behaviour:** (Tell us what should happen instead.)
Create the account and that account must register himself in table "battlenet_accounts" and beside in "account"

**Steps to reproduce the problem:**

1. Update the server
2. Create an account with the command ".bnet create"
3. Try to authentify the created account.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
12ac800effc552d36bfd46f24e0896433573e66f
**TDB version:**  
7.0.3+updates
**Operating system:**  
Windows 10

**Comment by joschiwald** [comment]
this command does not take the username of the gameaccount
change the 3rd arg to 1 yes or true to create a gameaccount using bnet create command

**Comment by Shauren** [comment]
@joschiwald 3rd arg defaults to true if not speficied.
