### ISSUE TITLE
[3.3.5] Spell/Warlock: Backdraft charges consumption

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#18516]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When you cast Conflagrate, the cast time and global cooldown of your next three Destruction spells is reduced by 30%. Lasts 15 sec.

**Current behaviour:** When using Shadowbolt or Incinerate while having Backlash and Backdraft active, Backdraft will be consumed.

**Expected behaviour:** When using Shadowbolt or Incinerate while having Backlash and Backdraft active, only Backlash will now be properly consumed." [wowwiki](http://wowwiki.wikia.com/wiki/Backlash)

**Steps to reproduce the problem:**

1. Wait for proc [Backlash](http://wotlk.openwow.com/spell=34939).
2. Apply [backdraft ](http://wotlk.openwow.com/spell=47260).
3. Use any spell modified by [Backlash](http://wotlk.openwow.com/spell=34939).
4. Backdraft consumed.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/85c68d634663028f2b60748eca469838d431f74b

**TDB version:**  TDB335.62

**Operating system:**  Linux debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Ariel fixed it in "new system proc"
some new changes broken it again x_x

**Comment by Noryad** [comment]
Confirmed in 85c68d6
Patch 3.2.2 (2009-09-22): When using Shadowbolt or Incinerate while having Backlash and Backdraft active, only Backlash will now be properly consumed.

**Comment by ariel-** [comment]
Yeah, I added a check for this kind of mods: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.h#L2633

**Comment by Noryad** [comment]
We will appreciate that you to resolve it again :)

**Comment by xinef1** [comment]
Try this, as far as I remember, the problem comes not from the cast time mod but from global cooldown reduction mod added independently. Easiest way to fix this is to check whether previous mod of backdraft was applied. The only spell with pct mod reducing global cooldown is backdraft. Similar problem can be observed with Sure of Light (it can proc when you are casting spell), resulting in whole charge drop when only critical chance was modified.

Because there were some changes with procs handling (especially charges dropping) this can be invalid.

```c++
 src/server/game/Entities/Player/Player.h | 14 +++++++++-----
 1 file changed, 9 insertions(+), 5 deletions(-)

diff --git a/src/server/game/Entities/Player/Player.h b/src/server/game/Entities/Player/Player.h
index dcaa219..05f6879 100644
--- a/src/server/game/Entities/Player/Player.h
+++ b/src/server/game/Entities/Player/Player.h
@@ -1605,6 +1605,7 @@ class TC_GAME_API Player : public Unit, public GridObject<Player>
 
         void AddSpellMod(SpellModifier* mod, bool apply);
         static bool IsAffectedBySpellmod(SpellInfo const* spellInfo, SpellModifier* mod, Spell* spell = nullptr);
+        static bool HasSpellMod(SpellModifier* mod, Spell* spell);
         template <SpellModOp op, class T>
         void ApplySpellMod(uint32 spellId, T& basevalue, Spell* spell = nullptr) const;
         void RestoreSpellMods(Spell* spell, uint32 ownerAuraId = 0, Aura* aura = nullptr);
@@ -2699,11 +2700,14 @@ void Player::ApplySpellMod(uint32 spellId, T& basevalue, Spell* spell /*= nullptr*/) const
                     continue;
 
                 // special case (skip > 10sec spell casts for instant cast setting)
-                if (op == SPELLMOD_CASTING_TIME)
-                {
-                    if (mod->value <= -100 && basevalue >= T(10000))
-                        continue;
-                }
+                if (op == SPELLMOD_CASTING_TIME && basevalue >= T(10000) && mod->value <= -100)
+                    continue;
+                // special exception for surge of light, dont affect crit chance if previous mods were not applied
+                else if (op == SPELLMOD_CRITICAL_CHANCE && spell && !HasSpellMod(mod, spell))
+                    continue;
+                // special case for backdraft gcd reduce with backlast time reduction, dont affect gcd if cast time was not applied
+                else if (op == SPELLMOD_GLOBAL_COOLDOWN && spell && !HasSpellMod(mod, spell))
+                    continue;
 
                 totalmul += CalculatePct(1.0f, mod->value);
                 break;

 src/server/game/Entities/Player/Player.cpp | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 21d1f25..be660dd 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -20809,6 +20809,14 @@ bool Player::IsAffectedBySpellmod(SpellInfo const* spellInfo, SpellModifier* mod
     return spellInfo->IsAffectedBySpellMod(mod);
 }
 
+bool Player::HasSpellMod(SpellModifier* mod, Spell* spell)
+{ 
+    if (!mod || !spell)
+        return false;
+
+    return spell->m_appliedMods.find(mod->ownerAura) != spell->m_appliedMods.end();
+}
+
 void Player::AddSpellMod(SpellModifier* mod, bool apply)
 {
     TC_LOG_DEBUG("spells", "Player::AddSpellMod: Player '%s' (%s), SpellID: %d", GetName().c_str(), GetGUID().ToString().c_str(), mod->spellId);
```

**Comment by Rushor** [comment]
yes and the author for this is xinef. please don't remove the name in his comments :)
