### ISSUE TITLE
DB/Gossip: Stormwind NPC (Guild Master) does not offer to create a guild

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18517]
**Description:** 
The NPC Aldwin Laughlin `<Guild Master>` (entry 4974, GUID 313942) located in the Trade District in Stormwind City at X:-8889.830078 Y:607.273987 Z:95.340897  

**Current behaviour: (Tell us what happens.)**  

The npc does not show you the posibilitie to create the guild crest or to acquire the documents to create a new guild  

**Expected behaviour: (Tell us what should happen instead.)**  

The npc should show you 2 options, one to choose the design of your guild crest, the other option allows you to create a new guild both options are now missing  

**Steps to reproduce the problem:**  

Go to Stormwind and speak with Aldwin Laughlin located at X:-8889.830078 Y:607.273987 Z:95.340897  

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**   
Master  

**TC rev. hash/commit:**  bc758991140e961ceac46b17b766b0d54b8129fb  

**TDB version:**  7.0.3+updates  

**Operating system:** Windows 10

**Comment by yvoms** [comment]
`UPDATE `world`.`creature_template` SET `npcflag`=2, `unit_flags`=512, `unit_flags2`=2048, `type`=7, `flags_extra`=2 WHERE `entry`=4974;`

**Comment by Aokromes** [comment]
```sql
UPDATE `creature_template` SET `npcflag`=`npcflag` | 2, `unit_flags`=`unit_flags` | 512, `unit_flags2`=`unit_flags2` | 2048, `type`=`type` | 7, `flags_extra`=`flags_extra` | 2 WHERE `entry`=4974;
 ```

**Comment by Killyana** [comment]
Try this without changing the creature_template:
``` sql
DELETE FROM `gossip_menu_option` WHERE `MenuID` IN (708);
