### ISSUE TITLE
[3.3.5] Spell/Generic: Will of Forsaken can't be used while controlled

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#18515]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Removes any Charm, Fear and Sleep effect. This effect shares a 45 sec cooldown with other similar effects.

**Current behaviour:** [Will of Forsaken](http://wotlk.openwow.com/spell=7744) can't be used while controlled.

**Expected behaviour:** Target should be able to use [Will of Forsaken](http://wotlk.openwow.com/spell=7744) while controlled.

**Steps to reproduce the problem:**

1. Apply any charm, fear, sleep effect.
2. Use [Will of Forsaken](http://wotlk.openwow.com/spell=7744)
3. [Will of Forsaken](http://wotlk.openwow.com/spell=7744) can't be used.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/85c68d634663028f2b60748eca469838d431f74b

**TDB version:**  TDB335.62

**Operating system:**  Linux debian 8

Current behaviour exist after https://github.com/TrinityCore/TrinityCore/commit/77a08ad73cac678ad6b85723cf2e352a8a4e355b

Probably this problem not only with Will of Forsaken.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
I can not reproduce it, tested in 85c68d6 with Fear and Seduction and [Will of the Forsaken] works ok.

**Comment by Eliminationzx** [comment]
My bad, sorry.
