### ISSUE TITLE
Warrior - Talents Fury - Negative damage when using 02 Two-Handed Weapons

### ISSUE THREAD

**Issue by Bodeguero** [TrinityCore/TrinityCore#18511]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** I'm in trouble, when the Warrior uses 02 Two-Handed Weapons the damage gets lower than when I only use 01 Two-Handed Weapon.

**OBS: I'm sorry for the mistakes in English.**

See the image below:

![2](https://cloud.githubusercontent.com/assets/8006687/21297265/482fcb72-c55b-11e6-9a5f-b9bd0eee5740.jpg)

**Current behaviour:** The damage when using 02 Two-Handed Guns gets negative.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/85c68d634663028f2b60748eca469838d431f74b

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Not a bug:

http://i.imgur.com/vKYHllN.png

**Comment by Bodeguero** [comment]
@Aokromes But before does not show as negative - at last thank you for the Support! :neckbeard:

**Comment by tkrokli** [comment]
Oh. I see. I misread the description. Titan's Grip allows using 2-hand weapons in both hands, but the 10% penalty applies when wielding 2H weapons in both hands. I thought it was the opposite, but that would not make sense, since you should not get penalties from wielding a single 2-Hand weapon (which most classes can do anyway).

**Comment by Keader** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/a4baef19dd5d1fd42f20557d34219d9d14181545

**Comment by Aokromes** [comment]
What Keader means is a4baef1 implemented the proper damage reduction.
