### ISSUE TITLE
[3.3.5] Spell/Shaman: Glyph of Totem of Wrath not work

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18514]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When you cast Totem of Wrath, you gain 30% of the totem's bonus spell power for 5 min.

**Current behaviour:** 
Totem of Wrath not grant bonus spell power.

**Expected behaviour:**
Totem of Wrath should grant bonus spell power.

**Steps to reproduce the problem:**
1. Use Glyph of Totem of Wrath.
2. Cast Totem of Wrath.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2dbda3d

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
it's broken in "new commits" because was working 6 months ago

**Comment by Eliminationzx** [comment]
Possible fix

```sql
UPDATE `spell_proc` SET `SpellPhaseMask` = `1` WHERE `SpellId` = `63280`;
```

**Comment by Aokromes** [comment]
we don't put ` around numbers :)

**Comment by Eliminationzx** [comment]
post updated

**Comment by Jildor** [comment]
```diff
- UPDATE `spell_proc` SET `SpellPhaseMask` = `0x0000001` WHERE `SpellId` = `63280`;
+ UPDATE `spell_proc` SET `SpellPhaseMask`=0x0000001 WHERE `SpellId`=63280;
```

**Comment by Noryad** [comment]
@Eliminationzx your fix works ok

**Comment by ariel-** [comment]
Are you using Call of the Elements (or similar) to summon the totem? Or direct cast?

**Comment by Noryad** [comment]
In both cases the glyph not work.

**Comment by Dalgurakk** [comment]
@Noryad @ariel- @Eliminationzx @Aokromes @Keader @Shauren 
can you email me to delvalmorell8606@gmail.com with a brief explanation about spell proc system, masks, flags... please? ^^ 
I can not find much about it and I want to contribute with you.

**Comment by Keader** [comment]
Yeah, ariel- needs update 3.3.5 wiki
