### ISSUE TITLE
Core/Spell: Penance should not heal until talent is set

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18520]
**Description:**  The priest spell "penance" has more functions than the blizzlike spell once learned (info from starter edition account)  

**Current behaviour:**  After learning "penance", the spell has the capabilities of healing allied units and damaging the enemy units  

**Expected behaviour:**  This spell at the beginning when you first learn it must only be able of damaging enemy units and only when you apply the required talent this spell should heal allied units.

**Steps to reproduce the problem:**  
1- Create a priest character  
2- Obtain level 10  
3- Use "Penance" on an allied unit and an enemy unit.

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**   Master  

**TC rev. hash/commit:**  bc758991140e961ceac46b17b766b0d54b8129fb  

**TDB version:**  703.00 + updates  

**Operating system:** Windows 10

**Comment by Ulduar** [comment]
https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/src/server/scripts/Spells/spell_priest.cpp#L774

Khm, penance have code, why not working.

Trying this variant (not testing)

``` CPP
// 47540 - Penance
class spell_pri_penance : public SpellScriptLoader
{
    public:
        spell_pri_penance() : SpellScriptLoader("spell_pri_penance") { }

        class spell_pri_penance_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_pri_penance_SpellScript);

            void HandleBeforeCast()
            {
                Unit* target = GetExplTargetUnit();
                Unit* caster = GetCaster();

                if (!caster || !target)
                    return;
            }

            void HandleOnHit()
            {
                Unit* target = GetHitUnit();
                Unit* caster = GetCaster();

                if (!caster || !target)
                    return;

                if (target->IsHostileTo(caster))
                    caster->CastSpell(unitTarget, SPELL_PRIEST_PENANCE_R1_DAMAGE, false);
                else
                    caster->CastSpell(unitTarget, SPELL_PRIEST_PENANCE_R1_HEAL, false);
            }

            void Register() override
            {
                BeforeCast += SpellCastFn(spell_pri_penance_SpellScript::HandleBeforeCast);
                OnHit += SpellHitFn(spell_pri_penance_SpellScript::HandleOnHit);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_pri_penance_SpellScript();
        }
};
```

**Comment by Edreisantafe** [comment]
This code solve the issue with Penance. They compile and work blizlike.

    SPELL_PRIEST_PENANCE_R1                         = 47540,
    SPELL_PRIEST_PENANCE_R1_DAMAGE                  = 47758,
    SPELL_PRIEST_PENANCE_R1_HEAL                    = 47757,
   +SPELL_PRIEST_THE_PENITENT_AURA		    = 200347,
    SPELL_PRIEST_REFLECTIVE_SHIELD_R1               = 33201,
    SPELL_PRIEST_REFLECTIVE_SHIELD_TRIGGERED        = 33619,


                        if (!caster->isInFront(target))
                            return SPELL_FAILED_UNIT_NOT_INFRONT;
					}
+					else 
+					{
+						//Support for modifications of this spell in Legion with The Penitent talent
+						if(!caster->HasAura(SPELL_PRIEST_THE_PENITENT_AURA))
+							return SPELL_FAILED_BAD_TARGETS;
					}
                return SPELL_CAST_OK;

Any suggestion?

**Comment by Edreisantafe** [comment]
Anyone has try it?
