### ISSUE TITLE
DB/vendor: Stormwind City Honor vendor items

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18521]
**Description:**  The honor vendors in Stormwind City do not work at all.  

**Current behaviour: (Tell us what happens.)**  
The vendors show the items, you can see them, but you can not buy them. The items do not show a price or requirement for you to acquire it and when you try to confirm the buy, an error pops up "The item was not found" (when you check the database the items exist and if you use the command ".add" you can obtain the items and use it. Because of that, we think the error is in the vendors).  

**Expected behaviour: (Tell us what should happen instead.)**  
I am not sure of what really should happen because i dont have enough info about the legion some say that the honor feature is deactivated in this DLC and others say that other coin is required for this items at any case i recommend watch blizz server.  

**Steps to reproduce the problem:**  

1. Visit stormwind  
2. go to champions hall  
3. talk to the NPC

**Branch(es):** Master  

**TC rev. hash/commit:**  bc758991140e961ceac46b17b766b0d54b8129fb  

**TDB version:**  703.00 + updates  

**Operating system:** Windows 10

**Comment by Edreisantafe** [comment]
All this vendor is from snifer from StarterEdition that actualice the vendors in Stormwind with data from Legion expansion.

`-- FULL `npc_vendor` of entry 5193
DELETE FROM `npc_vendor` WHERE (entry = 5193);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(5193, 1, 5976, 0, 0, 0, 1, 0, 0, 23222),
(5193, 17, 15196, 0, 0, 5962, 1, 0, 0, 23222),
(5193, 18, 15198, 0, 0, 5962, 1, 0, 0, 23222),
(5193, 16, 19032, 0, 0, 5992, 1, 0, 0, 23222),
(5193, 15, 19506, 0, 0, 5992, 1, 0, 0, 23222),
(5193, 13, 23999, 0, 0, 0, 1, 0, 0, 23222),
(5193, 14, 31774, 0, 0, 0, 1, 0, 0, 23222),
(5193, 11, 31775, 0, 0, 1994, 1, 0, 0, 23222),
(5193, 4, 31776, 0, 0, 0, 1, 0, 0, 23222),
(5193, 5, 31777, 0, 0, 0, 1, 0, 0, 23222),
(5193, 6, 31778, 0, 0, 0, 1, 0, 0, 23222),
(5193, 2, 31779, 0, 0, 0, 1, 0, 0, 23222),
(5193, 8, 31780, 0, 0, 0, 1, 0, 0, 23222),
(5193, 9, 31781, 0, 0, 0, 1, 0, 0, 23222),
(5193, 3, 31804, 0, 0, 0, 1, 0, 0, 23222),
(5193, 10, 32445, 0, 0, 0, 1, 0, 0, 23222),
(5193, 7, 32828, 0, 0, 1958, 1, 0, 0, 23222),
(5193, 12, 35221, 0, 0, 0, 1, 0, 0, 23222);`

`-- FULL `npc_vendor` of entry 12781
DELETE FROM `npc_vendor` WHERE (entry = 12781);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(12781, 7, 15196, 0, 0, 5962, 1, 0, 0, 23222),
(12781, 8, 15198, 0, 0, 5962, 1, 0, 0, 23222),
(12781, 9, 18606, 0, 0, 5962, 1, 0, 0, 23222),
(12781, 1, 18839, 0, 0, 0, 1, 0, 0, 23222),
(12781, 2, 18841, 0, 0, 0, 1, 0, 0, 23222),
(12781, 29, 28118, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 30, 28119, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 32, 28123, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 28, 28362, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 31, 28363, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 3, 31853, 0, 0, 0, 1, 0, 0, 23222),
(12781, 4, 31855, 0, 0, 0, 1, 0, 0, 23222),
(12781, 6, 32453, 0, 0, 0, 1, 0, 0, 23222),
(12781, 5, 32455, 0, 0, 0, 1, 0, 0, 23222),
(12781, 11, 68772, 0, 0, 6005, 1, 0, 0, 23222),
(12781, 12, 68773, 0, 0, 6005, 1, 0, 0, 23222),
(12781, 10, 68774, 0, 0, 6005, 1, 0, 0, 23222),
(12781, 14, 77130, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 15, 77131, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 21, 77132, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 26, 77133, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 27, 77134, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 22, 77136, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 17, 77137, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 23, 77138, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 18, 77139, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 13, 77140, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 24, 77141, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 19, 77142, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 20, 77143, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 25, 77144, 0, 0, 6004, 1, 0, 0, 23222),
(12781, 16, 77154, 0, 0, 6004, 1, 0, 0, 23222);`

`-- FULL `npc_vendor` of entry 12783
DELETE FROM `npc_vendor` WHERE (entry = 12783);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(12783, 1, 29465, 0, 0, 5976, 1, 0, 0, 23222),
(12783, 2, 29467, 0, 0, 5976, 1, 0, 0, 23222),
(12783, 3, 29468, 0, 0, 5976, 1, 0, 0, 23222),
(12783, 4, 29471, 0, 0, 5976, 1, 0, 0, 23222),
(12783, 5, 35906, 0, 0, 5976, 1, 0, 0, 23222);`

**Comment by Edreisantafe** [comment]
`-- FULL `npc_vendor` of entry 12784
DELETE FROM `npc_vendor` WHERE (entry = 12784);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(12784, 7, 12584, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 14, 18825, 0, 0, 5963, 1, 0, 0, 23222),
(12784, 6, 18827, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 2, 18830, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 15, 18833, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 16, 18836, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 13, 18838, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 11, 18843, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 12, 18847, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 17, 18855, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 9, 18865, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 3, 18867, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 5, 18869, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 18, 18873, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 1, 18876, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 19, 23451, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 20, 23452, 0, 0, 5963, 1, 0, 0, 23222),
(12784, 21, 23453, 0, 0, 5963, 1, 0, 0, 23222),
(12784, 10, 23454, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 4, 23455, 0, 0, 5966, 1, 0, 0, 23222),
(12784, 8, 23456, 0, 0, 5966, 1, 0, 0, 23222);`

`-- FULL `npc_vendor` of entry 52029
DELETE FROM `npc_vendor` WHERE (entry = 52029);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(52029, 96, 64720, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 97, 64721, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 95, 64722, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 125, 64723, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 123, 64724, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 124, 64725, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 129, 64732, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 128, 64733, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 130, 64734, 0, 0, 5962, 1, 0, 0, 23222),
(52029, 72, 64795, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 73, 64796, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 74, 64797, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 75, 64798, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 71, 64799, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 67, 64838, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 68, 64839, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 69, 64840, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 70, 64841, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 66, 64842, 0, 0, 5964, 1, 0, 0, 23222),
(52029, 111, 64862, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 112, 64863, 0, 0, 5963, 1, 0, 0, 23222),
(52029, 110, 64864, 0, 0, 5963, 1, 0, 0, 23222);`

`-- FULL `npc_vendor` of entry 52030
DELETE FROM `npc_vendor` WHERE (entry = 52030);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(52030, 17, 122338, 0, 0, 5973, 1, 0, 0, 23222),
(52030, 18, 122339, 0, 0, 5975, 1, 0, 0, 23222),
(52030, 12, 122364, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 16, 122365, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 11, 122366, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 14, 122367, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 13, 122368, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 15, 122369, 0, 0, 5971, 1, 0, 0, 23222),
(52030, 2, 122371, 0, 0, 5965, 1, 0, 0, 23222),
(52030, 5, 122372, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 4, 122373, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 6, 122374, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 7, 122375, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 9, 122376, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 8, 122377, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 10, 122378, 0, 0, 5969, 1, 0, 0, 23222),
(52030, 3, 122530, 0, 0, 5965, 1, 0, 0, 23222);`

`-- FULL `npc_vendor` of entry 54660
DELETE FROM `npc_vendor` WHERE (entry = 54660);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(54660, 66, 60468, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 67, 60469, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 68, 60470, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 69, 60471, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 70, 60472, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 71, 60473, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 72, 60474, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 73, 60475, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 74, 60476, 0, 0, 5964, 1, 0, 0, 23222),
(54660, 75, 60477, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 84, 60612, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 108, 60613, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 85, 60626, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 123, 60628, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 109, 60630, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 124, 60634, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 125, 60635, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 110, 60636, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 86, 60637, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 130, 60786, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 131, 60787, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 132, 60788, 0, 0, 5962, 1, 0, 0, 23222),
(54660, 133, 61324, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 151, 61325, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 156, 61326, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 134, 61327, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 135, 61328, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 145, 61329, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 136, 61330, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 137, 61331, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 153, 61332, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 152, 61333, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 138, 61335, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 154, 61336, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 146, 61338, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 157, 61339, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 143, 61340, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 147, 61341, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 148, 61342, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 144, 61343, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 155, 61344, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 139, 61345, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 158, 61346, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 150, 61350, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 149, 61351, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 140, 61353, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 142, 61354, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 141, 61355, 0, 0, 5966, 1, 0, 0, 23222),
(54660, 159, 61357, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 160, 61358, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 163, 61359, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 162, 61360, 0, 0, 5963, 1, 0, 0, 23222),
(54660, 161, 61361, 0, 0, 5963, 1, 0, 0, 23222);`

**Comment by Edreisantafe** [comment]
`-- FULL `npc_vendor` of entry 58154
DELETE FROM `npc_vendor` WHERE (entry = 58154);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES
(58154, 62, 57913, 0, 0, 0, 1, 0, 0, 23222),
(58154, 61, 57914, 0, 0, 0, 1, 0, 0, 23222),
(58154, 63, 57915, 0, 0, 0, 1, 0, 0, 23222),
(58154, 64, 57916, 0, 0, 0, 1, 0, 0, 23222),
(58154, 58, 57917, 0, 0, 0, 1, 0, 0, 23222),
(58154, 59, 57918, 0, 0, 0, 1, 0, 0, 23222),
(58154, 66, 57919, 0, 0, 0, 1, 0, 0, 23222),
(58154, 65, 57921, 0, 0, 0, 1, 0, 0, 23222),
(58154, 60, 57922, 0, 0, 0, 1, 0, 0, 23222),
(58154, 26, 57923, 0, 0, 0, 1, 0, 0, 23222),
(58154, 25, 57924, 0, 0, 0, 1, 0, 0, 23222),
(58154, 48, 57925, 0, 0, 0, 1, 0, 0, 23222),
(58154, 47, 57926, 0, 0, 0, 1, 0, 0, 23222),
(58154, 43, 57927, 0, 0, 0, 1, 0, 0, 23222),
(58154, 42, 57928, 0, 0, 0, 1, 0, 0, 23222),
(58154, 41, 57929, 0, 0, 0, 1, 0, 0, 23222),
(58154, 37, 57930, 0, 0, 0, 1, 0, 0, 23222),
(58154, 40, 57931, 0, 0, 0, 1, 0, 0, 23222),
(58154, 36, 57932, 0, 0, 0, 1, 0, 0, 23222),
(58154, 39, 57933, 0, 0, 0, 1, 0, 0, 23222),
(58154, 38, 57934, 0, 0, 0, 1, 0, 0, 23222),
(58154, 4, 58096, 0, 0, 0, 1, 0, 0, 23222),
(58154, 31, 58097, 0, 0, 0, 1, 0, 0, 23222),
(58154, 20, 58098, 0, 0, 0, 1, 0, 0, 23222),
(58154, 11, 58099, 0, 0, 0, 1, 0, 0, 23222),
(58154, 53, 58100, 0, 0, 0, 1, 0, 0, 23222),
(58154, 3, 58101, 0, 0, 0, 1, 0, 0, 23222),
(58154, 30, 58102, 0, 0, 0, 1, 0, 0, 23222),
(58154, 19, 58103, 0, 0, 0, 1, 0, 0, 23222),
(58154, 52, 58104, 0, 0, 0, 1, 0, 0, 23222),
(58154, 10, 58105, 0, 0, 0, 1, 0, 0, 23222),
(58154, 5, 58106, 0, 0, 0, 1, 0, 0, 23222),
(58154, 32, 58107, 0, 0, 0, 1, 0, 0, 23222),
(58154, 21, 58108, 0, 0, 0, 1, 0, 0, 23222),
(58154, 54, 58109, 0, 0, 0, 1, 0, 0, 23222),
(58154, 12, 58110, 0, 0, 0, 1, 0, 0, 23222),
(58154, 6, 58121, 0, 0, 0, 1, 0, 0, 23222),
(58154, 33, 58122, 0, 0, 0, 1, 0, 0, 23222),
(58154, 22, 58123, 0, 0, 0, 1, 0, 0, 23222),
(58154, 55, 58124, 0, 0, 0, 1, 0, 0, 23222),
(58154, 13, 58125, 0, 0, 0, 1, 0, 0, 23222),
(58154, 1, 58126, 0, 0, 0, 1, 0, 0, 23222),
(58154, 27, 58127, 0, 0, 0, 1, 0, 0, 23222),
(58154, 16, 58128, 0, 0, 0, 1, 0, 0, 23222),
(58154, 49, 58129, 0, 0, 0, 1, 0, 0, 23222),
(58154, 7, 58130, 0, 0, 0, 1, 0, 0, 23222),
(58154, 2, 58131, 0, 0, 0, 1, 0, 0, 23222),
(58154, 28, 58132, 0, 0, 0, 1, 0, 0, 23222),
(58154, 17, 58133, 0, 0, 0, 1, 0, 0, 23222),
(58154, 50, 58134, 0, 0, 0, 1, 0, 0, 23222),
(58154, 8, 58138, 0, 0, 0, 1, 0, 0, 23222),
(58154, 45, 58139, 0, 0, 0, 1, 0, 0, 23222),
(58154, 34, 58140, 0, 0, 0, 1, 0, 0, 23222),
(58154, 23, 58150, 0, 0, 0, 1, 0, 0, 23222),
(58154, 56, 58151, 0, 0, 0, 1, 0, 0, 23222),
(58154, 14, 58152, 0, 0, 0, 1, 0, 0, 23222),
(58154, 46, 58153, 0, 0, 0, 1, 0, 0, 23222),
(58154, 35, 58154, 0, 0, 0, 1, 0, 0, 23222),
(58154, 24, 58155, 0, 0, 0, 1, 0, 0, 23222),
(58154, 57, 58157, 0, 0, 0, 1, 0, 0, 23222),
(58154, 15, 58158, 0, 0, 0, 1, 0, 0, 23222),
(58154, 44, 58159, 0, 0, 0, 1, 0, 0, 23222),
(58154, 29, 58160, 0, 0, 0, 1, 0, 0, 23222),
(58154, 18, 58161, 0, 0, 0, 1, 0, 0, 23222),
(58154, 51, 58162, 0, 0, 0, 1, 0, 0, 23222),
(58154, 9, 58163, 0, 0, 0, 1, 0, 0, 23222),
(58154, 90, 58180, 0, 0, 0, 1, 0, 0, 23222),
(58154, 89, 58181, 0, 0, 0, 1, 0, 0, 23222),
(58154, 88, 58182, 0, 0, 0, 1, 0, 0, 23222),
(58154, 87, 58183, 0, 0, 0, 1, 0, 0, 23222),
(58154, 86, 58184, 0, 0, 0, 1, 0, 0, 23222),
(58154, 84, 58185, 0, 0, 0, 1, 0, 0, 23222),
(58154, 83, 58187, 0, 0, 0, 1, 0, 0, 23222),
(58154, 82, 58188, 0, 0, 0, 1, 0, 0, 23222),
(58154, 81, 58189, 0, 0, 0, 1, 0, 0, 23222),
(58154, 68, 58190, 0, 0, 0, 1, 0, 0, 23222),
(58154, 71, 58191, 0, 0, 0, 1, 0, 0, 23222),
(58154, 70, 58192, 0, 0, 0, 1, 0, 0, 23222),
(58154, 69, 58193, 0, 0, 0, 1, 0, 0, 23222),
(58154, 67, 58194, 0, 0, 0, 1, 0, 0, 23222),
(58154, 80, 58195, 0, 0, 0, 1, 0, 0, 23222),
(58154, 79, 58197, 0, 0, 0, 1, 0, 0, 23222),
(58154, 78, 58198, 0, 0, 0, 1, 0, 0, 23222),
(58154, 77, 58199, 0, 0, 0, 1, 0, 0, 23222),
(58154, 76, 58481, 0, 0, 0, 1, 0, 0, 23222),
(58154, 75, 58482, 0, 0, 0, 1, 0, 0, 23222),
(58154, 74, 58484, 0, 0, 0, 1, 0, 0, 23222),
(58154, 73, 58485, 0, 0, 0, 1, 0, 0, 23222),
(58154, 72, 58486, 0, 0, 0, 1, 0, 0, 23222),
(58154, 170, 60253, 0, 0, 0, 1, 0, 0, 23222),
(58154, 163, 60254, 0, 0, 0, 1, 0, 0, 23222),
(58154, 147, 60255, 0, 0, 0, 1, 0, 0, 23222),
(58154, 128, 60256, 0, 0, 0, 1, 0, 0, 23222),
(58154, 108, 60257, 0, 0, 0, 1, 0, 0, 23222),
(58154, 127, 60258, 0, 0, 0, 1, 0, 0, 23222),
(58154, 166, 60259, 0, 0, 0, 1, 0, 0, 23222),
(58154, 146, 60261, 0, 0, 0, 1, 0, 0, 23222),
(58154, 173, 60262, 0, 0, 0, 1, 0, 0, 23222),
(58154, 104, 60275, 0, 0, 0, 1, 0, 0, 23222),
(58154, 196, 65001, 0, 0, 3329, 1, 0, 0, 23222),
(58154, 190, 65088, 0, 0, 3329, 1, 0, 0, 23222),
(58154, 251, 65229, 0, 0, 3155, 1, 0, 0, 23222),
(58154, 252, 65230, 0, 0, 3055, 1, 0, 0, 23222),
(58154, 253, 65231, 0, 0, 3103, 1, 0, 0, 23222),
(58154, 254, 65232, 0, 0, 3089, 1, 0, 0, 23222),
(58154, 255, 65233, 0, 0, 3047, 1, 0, 0, 23222),
(58154, 256, 65234, 0, 0, 3156, 1, 0, 0, 23222),
(58154, 257, 65235, 0, 0, 3055, 1, 0, 0, 23222),
(58154, 258, 65236, 0, 0, 3102, 1, 0, 0, 23222),
(58154, 259, 65237, 0, 0, 3088, 1, 0, 0, 23222),
(58154, 260, 65238, 0, 0, 3047, 1, 0, 0, 23222),
(58154, 187, 67423, 0, 0, 3329, 1, 0, 0, 23222),
(58154, 199, 67428, 0, 0, 3329, 1, 0, 0, 23222),
(58154, 193, 67429, 0, 0, 3329, 1, 0, 0, 23222),
(58154, 85, 68812, 0, 0, 0, 1, 0, 0, 23222);`

**Comment by CDawg** [comment]
@Edreisantafe This is not a 3.3.5a issue

**Comment by Edreisantafe** [comment]
No, there is not, this is for Master branch.

**Comment by Rushor** [comment]
the change in the first Post:

Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)

Master > 3.3.5.

**Comment by Killyana** [comment]
Fixed by funjoker.
