### ISSUE TITLE
[3.3.5] Spell/Warlock Fel Domination charge consumption

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#18527]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Your next Imp, Voidwalker, Succubus, Felhunter or Felguard Summon spell has its casting time reduced by 5.5 sec and its Mana cost reduced by 50%.

**Current behaviour:** successful pet summoning doesn't remove [Fel domination](http://wotlk.openwow.com/spell=18708) charge.

**Expected behaviour:** successful pet summoning should drop [Fel domination](http://wotlk.openwow.com/spell=18708) charge.

**Steps to reproduce the problem:**

1. Apply Fel domination.
2. Try to summon Imp, Felguard, Succubus.
3. Fel domination still active.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/c809c220e29f7094121cc8489f5588d8bfee414d

**TDB version:**  TDB335.62

**Operating system:**  Linux debian 8

Possible fix
```sql
DELETE FROM `spell_proc` WHERE `SpellId` = 18708;
INSERT INTO `spell_proc` VALUES (18708, 0, 0, 0, 0, 0x20000000, 0, 0, 0x0000001, 0, 0x0000008, 0, 0, 0, 0);
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Confirmed in 85c68d6.
With @Eliminationzx sql Fel Domination is consumed. It will require to be reviewed by a trinitycore member.

**Comment by lostsoul123** [comment]
lemme show you a magic trick : 

class spell_warl_remove_fel_domination : public SpellScriptLoader
{
public:
	spell_warl_remove_fel_domination() : SpellScriptLoader("spell_warl_remove_fel_domination") { }

	class spell_warl_remove_fel_domination_SpellScript : public SpellScript
	{
		PrepareSpellScript(spell_warl_remove_fel_domination_SpellScript);
		void RemoveAura()
		{
			Unit* caster = GetCaster();
			if (caster->HasAura(18708))
				caster->RemoveAura(18708);
			
		}

		void Register() override
		{
			AfterCast += SpellCastFn(spell_warl_remove_fel_domination_SpellScript::RemoveAura);
		}

	};

	SpellScript* GetSpellScript() const override
	{
		return new spell_warl_remove_fel_domination_SpellScript();
	}
};
----------------------------
INSERT INTO `world`.`spell_script_names` (`spell_id`, `ScriptName`) VALUES ('-688', 'spell_warl_remove_fel_domination');
INSERT INTO `world`.`spell_script_names` (`spell_id`, `ScriptName`) VALUES ('-697', 'spell_warl_remove_fel_domination');
INSERT INTO `world`.`spell_script_names` (`spell_id`, `ScriptName`) VALUES ('-712', 'spell_warl_remove_fel_domination');
INSERT INTO `world`.`spell_script_names` (`spell_id`, `ScriptName`) VALUES ('-30146', 'spell_warl_remove_fel_domination');
INSERT INTO `world`.`spell_script_names` (`spell_id`, `ScriptName`) VALUES ('-691', 'spell_warl_remove_fel_domination');
--------------------------
tadahhhhhhhhhhh its...its gone

**Comment by Keader** [comment]
Hack, it should be handled by proc system :)

**Comment by Eliminationzx** [comment]
That hack makes me cry...

**Comment by lostsoul123** [comment]
Have a sense of humor (-_-)
