### ISSUE TITLE
DB/Creature The Npc Priestess Dentaria is missing from DB.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18522]
**Description:**  
Quest Hero´s Call: Darkshore!  
Report to Priestess Dentaria in Lor´danel in Darkshore.  

**Current behaviour:**  
Priestess Dentaria is missing.  

**Expected behaviour:**  
Priestess Dentaria should be in Lor´danel  

**Steps to reproduce the problem:**  

1- Levelup to 11.  
2- Take quest from Hero´s call in Darnassus.  
3- Try to deliver the quest.  

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**   
Master  

**TC rev. hash/commit:**  
bc758991140e961ceac46b17b766b0d54b8129fb  

**TDB version:**  
7.0.3+updates  

**Operating system:** 
Windows 10

**Comment by Eredar** [comment]
There are too much missing data in TDB 703.00. Cata, Pandaria, Draenor and Legion, almost all their dungeons and raids, scenarios and garrisons/orderhalls are empty at all. Try report "missing quest mobs" and other DB stuff when it will be significantly updated, or update it yourself (create a pull request), according to wowhead or sniffs.

As I can see main priority of TC devs is core fixes(ie crashes, scripts, mechanics implementation, client-server intercation), not db.

**Comment by Aokromes** [comment]
Unless someone deleted it on master branch it must be present:

http://i.imgur.com/JsMtnWH.jpg

**Comment by Edreisantafe** [comment]
Is Priestess Dentaria not Dentaria Silverglade lol.

**Comment by Aokromes** [comment]
http://www.wowhead.com/quest=28490/heros-call-darkshore
http://i.imgur.com/JeJnQIh.png

**Comment by Edreisantafe** [comment]
Thanks for the info, the problem then is that you can not interact with it to deliver the hero's calling mission.

**Comment by Eredar** [comment]
Sniffer:
https://community.trinitycore.org/topic/12264-trinity-cores-sniffer-for-wow-71023222
Parser:
https://github.com/TrinityCore/WowPacketParser

**Comment by Edreisantafe** [comment]
Yes, we have that tools but not the data to extract to.

**Comment by Edreisantafe** [comment]
This solve the issue:

`DELETE FROM `creature` WHERE (guid = 452554);
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `PhaseId`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (452554, 49479, 1, 0, 0, 1, 0, 0, 0, 0, 7412.9, -295.714, 7.65171, 1.00533, 300, 0, 0, 384, 0, 0, 0, 0, 0, 0);


-- FULL `creature_questender` of quest 28490
DELETE FROM `creature_questender` WHERE (quest = 28490);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(49479, 28490);`

**Comment by BahDumbBugs** [comment]
Unable to reproduce. Commit 8b2e071 shows normal progress from Hero's Call: Darkshore!

http://i.imgur.com/qdqjQ2Y.jpg

**Comment by BahDumbBugs** [comment]
However.......My L11 toon cannot see this NPC. Hmmmmm
http://i.imgur.com/8dG8aFg.jpg

The "?"is showing at the inn, but a search couldn't turn this NPC up. Maybe be a positioning issue? Under the surface of the earth maybe?

**Comment by Killyana** [comment]
Everything is working correctly, just a spell_area is missing as Darkshore is not scripted yet.
