### ISSUE TITLE
[3.3.5] Mage - Arcane Brilliance

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#18524]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Add missing spell_group for Arcane Brilliance, should not stack with Fel Intelligence

**Current behaviour:** (Tell us what happens.)
Arcane Brilliance stack with Fel Intelligence

**Expected behaviour:** (Tell us what should happen instead.)
Arcane Brilliance not stack with Fel Intelligence

**Steps to reproduce the problem:**

1. Cast Arcane Brilliance
2. Cast Fel Intelligence

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c809c220e29f7094121cc8489f5588d8bfee414d

**TDB version:**  TDB335.62

**Operating system:**  Debian

**Fix:**
```sql
DELETE FROM `spell_group` WHERE `id`=1083 AND `spell_id`=-1080;
INSERT INTO `spell_group` (`id`,`spell_id`) VALUES
(1083,-1080);
```
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by yvoms** [comment]
@Aokromes the fix the user provided is likely to work as i have resolved this the same way, I don't really see a better fix.

**Comment by Killyana** [comment]
@ariel- could this be pushed?

**Comment by ariel-** [comment]
I'm not too familiar with the grouping system, but I guess that if it has been found to work properly, sure why not
