### ISSUE TITLE
[3.3.5] Icecrown Citadel - Suppresser

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#18530]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description: Suppressers dont spawn on Valithria**

**Steps to reproduce the problem:**
Just pass Valithria

**Branch(es):** 3.3.5

**TDB version: 335.62**  

**Operating system: Windows server 2008**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by el-druida** [comment]
eh?

**Comment by jackpoz** [comment]
what's a suppressor ?

**Comment by nawuko** [comment]
He means http://www.wowhead.com/npc=37863/suppresser

**Comment by Rushor** [comment]
> what's a suppressor ?

icc encounter knowledge: https://www.youtube.com/watch?v=SiMHTK15Pik :D

**Comment by Shauren** [comment]
ffs stop writing IceCrown... its Icecrown

**Comment by ConradBunton** [comment]
Ok... SuppressErs dont spawn.

**Comment by Ulduar** [comment]
```QUOTE
stop writing IceCrown... 
```
Maybe IceCream? XD

**Comment by ConradBunton** [comment]
Bon alors, je peux aussi parler comme ça, si tu veux. Mais ça ne fera pas avancer le problème pour autant. T'es conscient que tu es en train de me prendre la tête pour une simple majuscule à la con ?

Ok ?

**Comment by ariel-** [comment]
Fix'd
