### ISSUE TITLE
[master(7.x)] Some cinematics broken

### ISSUE THREAD

**Issue by nerv234** [TrinityCore/TrinityCore#18531]
**Description:** Some cinematics are broken and not properly handled by client.

**Current behaviour:** Some cinematics just apply blackscreen for a while and don't start actual cinematic.

**Expected behaviour:** They should work normaly.

**Steps to reproduce the problem:**

1.  .cast 228520 (dh starting cinematic)

Additional info:
Effect 0: Id 45 (SPELL_EFFECT_PLAY_MOVIE)
Spells with this effect sometimes works but not at all the times. It seems that spells with miscA up to 2xx works but those with miscA above 400 won't work.

And this bug was noticed by me somewhere between moving to 4.1 patch(dh starting cinematic was working on tc for a while). 

**Branch(es):** master

**TC rev. hash/commit:**  63fd633d79985c3a4626f8c4d637a89586df420d

**TDB version:**  63fd633d79985c3a4626f8c4d637a89586df420d

**Operating system:**  win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18294

**Comment by nerv234** [comment]
You are wrong this isn't about scenes. It is about movies(diffrent packets and diffrent effect of spell).

**Comment by Shauren** [comment]
Probably just need key_chain/tact_key  db entries

**Comment by nerv234** [comment]
So could blizzard encrypt cinematic when moving from 7.0 to 7.1?

**Comment by nerv234** [comment]
afe5a1478980982b65cc5881449c9375b755f804
Ty @Vincent-Michael
