### ISSUE TITLE
Vmap Extractor

### ISSUE THREAD

**Issue by yvoms** [TrinityCore/TrinityCore#18533]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** When running the Vmap Extractor it runs good, however, it stops at a certain point, it's missing a critical file, however, i've run the vmap extractor on various clients, yet the same error persists.

**Current behavior:** (Tell us what happens.)
It's crashing on the following; 

> Extracting GameObject models...Extracting World\Wmo\Band\Final_Stage.wmo
> No such file.
> Couldn't open RootWmo!!!

**Expected behavior:** (Tell us what should happen instead.)
It shouldn't do that since the previous version of the vmap extractor was working as it should.

**Steps to reproduce the problem:**

1. Get the latest trinitycore revision on ur PC, cmake(include tools) + compile in release mode.
2. Run the Vmap extractor after you have run the map extractor.
3. The issue shall occur.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c809c220e29f7094121cc8489f5588d8bfee414d

**TDB version:**  62.

**Operating system:**  Windows 10 64 Bits, However, compiled the project in 32-bit release mode.

**Additional information:** Due to this issue occurring, you can not generate Vmaps or MMaps, however, the world server requires you to have them up to date since it will not run if they are from previous versions, so the only working fix I currently have is disabling Vmaps/Mmaps.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
That's not error, ignore.

**Comment by yvoms** [comment]
this was closed, however i can't assemble the maps.

> spawning Map 724
> Calculating model bounds for map 0...
> Creating map tree for map 0...
> Cannot open Vmaps/000.vmtree

@Aokromes
