### ISSUE TITLE
mmaps

### ISSUE THREAD

**Issue by madmax765** [TrinityCore/TrinityCore#18534]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
can not make mmaps or any thing
**Current behaviour:** (Tell us what happens.)
when i fallow institutions at https://trinitycore.atlassian.net/wiki/display/tc/Windows+Server+Setup
i run the file extractor. it closes to fast. when i right click on it run as admin.  i click 1 -extract dbc/db2 and maps. i get a pop up window - windows cannot find 'mapextractor.exe'. Make sure you typed the name correctly, and then try again. But i see mapextractor.exe in same folder.. so i dont know why its giving me this error for
**Expected behaviour:** (Tell us what should happen instead.)
should start making dbc files and mapps
**Steps to reproduce the problem:**

1.  copy four files mapextractor.exe, mmaps_generator.exe, vmap4extractor.exe and vmap4assembler.exe 
   and file extractor
2.  ran extractor
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
63fd633d79985c3a4626f8c4d637a89586df420d
**TDB version:**  
TDB_full_703.00_2016_10_17
**Operating system:**  
win 10 pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
this sounds more like an issue related to your own setup that would fit better on the forum than on the GitHub bug tracker

**Comment by Eredar** [comment]
Don't use .bat file. Extract one by one manually in this order (if I remember correctly): mapextractor, vmapextractor, vmapassembler, mmapsgenerator.

**Comment by madmax765** [comment]
if i run mapextractor i get these errors 
error opening case storage 'd:/wow\data' local enUS: file not found
![4cbfd4961bba42ceb3624b3beda334a5 1](https://cloud.githubusercontent.com/assets/29853/21345785/869567ae-c66f-11e6-811a-1fa92ecb3b50.png)

**Comment by Aokromes** [comment]
it's problem on your own configuration, this issue belongs to forum.
