### ISSUE TITLE
Map Extractor

### ISSUE THREAD

**Issue by yvoms** [TrinityCore/TrinityCore#18532]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** It seems the new map extractor is not working, aswell as for the Vmap, extractor/Assembler, they are missing certain files.

**Current behaviour:** It Will not complete or will not create the required files.

**Expected behaviour:** It should succesfully create the DBC/Maps/Vmaps/MMaps/Camera files.

**Steps to reproduce the problem:**

1. Get a client from a torrent site.
2. Execute map extractor/vmap extractor and mmaps.
3. Execute it within a command prompt so you can see why it fails (it was missing some files).

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** Current.  

**TDB version:** N/A 

**Operating system:** Windows 64 bit compiled in 32 bit mode.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
I extracted files few days ago and it worked properly, maybe you have downloaded one bad client.

**Comment by yvoms** [comment]
I've actually downloaded 3 clients so far, however i'm going to execute the map extractor in batch modus so it pauses instead of shut down instantly so you can see what i mean. give me 5 minutes please.

**Comment by yvoms** [comment]
Please close this issue, it appears i have mistaken myself, its not the Maps but the mmaps, ill create a new issue when i've attempted the ideas i have on resolving it.

**Comment by Aokromes** [comment]
well, like i told you i extracted all few days ago, so it's not a bug belonging to bug tracker.
