### ISSUE TITLE
[master] Full Tables from WoWHead

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18538]
Taken from WoWHead with the program made by Maibenrai and changed by me so that it includes more tables and it's according to 7.1.0 columns.

Download link for the SQL : 12.01.2017 - SQL Updates : 
https://mega.nz/#!1wpGSRIA!roWSOAr-KESZJQwDJuNeBi0yCbmx3DV3kwaRxV60gVQ

```
Currently : 
1. quest_template (logtitle)
2. To Be Added
3. quest_template (questdescription)
4. quest_request_items (completiontext)
5. quest_offer_reward (rewardtext)
6. creature_loot_template
7. creature_template (gold)
8. creature_template (level)
9. creature_template (model)
10. creature_template (name)
11. creature_template (subname)
12. creature_questender
13. creature_questitem
14. creature_queststarter
15. gameobject_loot_template
16. gameobject_template (name)
17. gameobject_questender
18. gameobject_questitem
19. gameobject_queststarter
20. item_loot_template
21. item_template_addon (gold)
22. fishing_loot_template
23. pickpocketing_loot_template
24. skinning_loot_template
25. npc_trainer
26. npc_vendor (NEEDS FIXING)
```

!! General Warning
There might be some values still missing because the site might not always be using the same code for all items and therefore the item will be missing.

!! Warning
All have clearing of the old table or column at start except when stated otherwise.
Added separate delete at every entry if it's needed.

```
!! FIRST+LAST !!   - First adds missing id's and last deletes empty id's. 
		   - Should always be first or last to add.

1               - Without clearing at start.
2               - To Be Added.
3               - Without clearing at start.
4               - Without clearing at start.
5               - Without clearing at start.
6               - Drop %, Reference and Group might be wrong.
6.1             - No Issues Known.
7               - No Issues Known.
8               - Without clearing at start.
9               - Without clearing at start.
10              - No Issues Known.
11              - No Issues Known.
12              - No Issues Known.
13              - Might break some quests.
14              - No Issues Known.
15              - Drop %, Reference and Group might be wrong.
15.1            - No Issues Known.
16              - To Be Added.
17              - No Issues Known.
18              - Might break some quests.
19              - No Issues Known.
20              - Drop %, Reference and Group might be wrong.
21              - No Issues Known.
22              - Drop %, Reference and Group might be wrong.
23              - Drop %, Reference and Group might be wrong.
23.1            - No Issues Known.
24              - Drop %, Reference and Group might be wrong.
24.1            - No Issues Known.
25              - No Issues Known.
26              - NEEDS FIXING - ALL INCRTIME AND EXTENDEDCOST ITEMS.
```

**Comment by DDuarte** [comment]
This has the same issues as always: Wowhead is not a reliable source for loot.

WH is good to know what drops in each NPC/GO but it is not enough to know how much it drops.

We should summon @ZxBiohazardZx from his grave.

**Comment by Maibenrai** [comment]
Very nice.  
I just wonder if they will accept so big SQL :)

**Comment by adryan66** [comment]
Well mostly the chance % , groupid and reference might be out of place , all the rest should stay the same since every has it's specific id / lootid / min,max drop etc.

**Comment by DDuarte** [comment]
"all the rest" is really small part of the loot _system_. Blindly importing loot chances from Wowhead will introduce a LOT of errors in the loot. However, I don't see anyone interested in properly (and manually) doing loot for creatures so we could probably compromise and use loot for **new** creatures.

**Comment by Maibenrai** [comment]
I had a script that compared database loot to wowhead loot and only fetched missing ones.

**Comment by adryan66** [comment]
Also, after that sql it needs to run, so that only the mobs with loot table have loot, forgot about this : 
```
UPDATE creature_template SET lootid = '';

UPDATE creature_template AS t1
JOIN creature_loot_template AS t2 ON t1.entry = t2.entry
SET t1.lootid = t1.entry;
```

**Comment by zamalaev** [comment]
need spawn NPC pandaria, draenor, legion)))

**Comment by MrSmite** [comment]
Does this take into account __*personal loot*__ drop rates or is it just a mash up of how many kills it took for an item to drop?

> http://wow.gamepedia.com/Loot#Personal_Loot
> Personal loot is the default for world bosses, Raid Finder and Warlords of Draenor Dungeon Finder groups. It is also available to raid leaders as an option for non-Raid Finder raids. Under personal loot, players do not directly roll on items; instead, the server chooses a number of players (based on group size) and awards them a random item for their spec. Mounts can also be won via this method from bosses that drop them. A window will appear telling all players what items dropped, and who received them. Gear awarded in this manner is not tradeable.

The Bonus Roll system, also introduced in Mists of Pandaria, uses this loot type as well. Players in possession of a specific token, such as a [Mogu Rune of Fate], when they kill a boss in the associated raid will be given a chance to spend the token for another try at loot from that boss. This can be done on any difficulty as well as on world bosses. The chance of obtaining loot from a boss drop is currently theorized to be approximately 15% (equivalent to an average of 3.75 items from a 25-player kill), but this has not been confirmed.

**Comment by DDuarte** [comment]
No, it doesn't take into account any of different loot modes, dynamic rates ("pity timers"), bonus rolls and a lot of other factors.

For example, if an item from a npc only drops when you have a certain quest, the loot chance for that item in Wowhead will get lower each time the npc is looted by someone without the quest.

**Comment by MrSmite** [comment]
As you mentioned earlier, *Nay*, I agree wowhead is a good source for determining what drops and maybe even stack sizes but the % chance should stay similar to how it is determined already in the core, with tweaks as necessary for new loot modes.

People who feel things are too low / high can always tweak their DB manually.

**Comment by zamalaev** [comment]
need gameobject loot

**Comment by adryan66** [comment]
Download link for Gameobject Loot Template : 
https://mega.nz/#!8pJQzaKb!2fV5FSEe6QTMeqFyYh1LIvwjqlqUGmKohefU-RxnmoU
10 will truncate gameobject_loot_template
11 will add new values
Same as before, fully taken from wowhead.

**Comment by adryan66** [comment]
Changed link and added more sqls for different tables, more to add after christmas most likely.

**Comment by Maibenrai** [comment]
```SQL
UPDATE `creature_template` SET `name` = "Remy &quot;Two Times&quot;" WHERE `entry` = 241;

You might want to change code for the next version so it replaces 
&quot;
with
\"

Line endings are also LFCRLF?

**Comment by zamalaev** [comment]
parsing faction NPC?

**Comment by adryan66** [comment]
> You might want to change code for the next version so it replaces 
> &quot;
> with
> \"
> 
> Line endings are also LFCRLF?

Fixed the " " " issue. Linebreaks are also fixed now, they were a mess mostly, using PHP_EOL.

> parsing faction NPC?

Not yet decided since faction is kinda buggy to parse, it works mostly with friendly npc, creatures like bears and others don't have faction assigned in wowhead. At least I couldn't see it on the page source.

Also, updated a few new tables + existing one's.

**Comment by zamalaev** [comment]
thx

**Comment by Exodius** [comment]
In my honest opinion, @Dduarte is right. You could compromise and use this for post-Cataclysm content. State of `*_loot_template` as it is is practically non existing. With something like this, at least we'll have a nice base to work with... The rest is simple, figure out correct drop percentages for quest items, different loot models, etc. It's always better to have something than nothing. It's something that I think is best. But, I am just a small fish in a big pond.

**Comment by Maibenrai** [comment]
@adryan66  About faction parsing. You can use for example http://www.wowhead.com/faction=47/ironforge#members.

**Comment by Aokromes** [comment]
there are multiple factions with same name, parsing by wowhead factions is useless.

**Comment by Maibenrai** [comment]
http://www.wowhead.com/factions names all different or what do you mean? And they have different ids.

**Comment by soulfrost** [comment]
@Maibenrai 809 & 1265; 1899 & 1920 & 1989; 1045 & 1061   as example

**Comment by adryan66** [comment]
Already done faction parsing but only with those that have it assigned to them, all the rest stay the same. Took it from each creature's source, felt better and more complete then checking faction tables.
Still,  the same warning applyes, bear and creatures like that won't have faction assigned in wowhead and i can't filter each and every npc like that, they will need nanual adding.

Will update it later tonight when I get home with a few more tables / fixes to existing.
Some are getting kinda final since I can't think of any other issues.

**Comment by Shauren** [comment]
From my experience on retail amount of gold dropped by bosses scales with number of people participating in the kill (so that amount per player has only a very small margin)
Gold dropped in satchels (such as the ones you get from mop LFR) has a slightly different calculation that cannot be reproduced in TC right now, its basically a range between 28-42g with the occasional chance of dropping triple that amount (for example a value of 50 would not be a valid result)

**Comment by adryan66** [comment]
> Ref creature_questitem and gameobject_questitem - both of these tables are used for showing quest items in creature/go tooltips and are part of WDB data, they cannot be taken from wowhead properly

Aha ok, just wondering what is the problem with those 2 tables (questitem), im guessing the idx value ? If it's so, won't all the entrys with idx = 0 be right and those with higher idx be wrong (or at least some of them) ?
I was checking random values after the parse and all were exactly like the one's we are having atm. 

> Gold dropped in satchels (such as the ones you get from mop LFR) has a slightly different calculation that cannot be reproduced in TC right now, its basically a range between 28-42g with the occasional chance of dropping triple that amount (for example a value of 50 would not be a valid result)

Guess parsing at 20% variance with min and max will be closer to normal then the old value of 50%, your example is exactly 20% variance. Was mostly wondering at normal mobs , not dungeon / raid since those have way bigger issues then the gold drop.

Thx for the feedback and any other feedback is welcome.

**Comment by ArcaneFox** [comment]
Is there any news about this?

**Comment by offl** [comment]
>The file you are trying to download is no longer available.
This could be due to the following reasons:
The file has been removed because of a ToS/AUP violation.
