### ISSUE TITLE
[CRASH] Trinity::PlayerListSearcher

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#18547]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Trinity::PlayerListSearcher<Trinity::AnyPlayerInObjectRangeCheck>::Visit

**Current behaviour**: Tell us what happens
Not sure why is this happening. ~2 crashes per day.

- http://pastebin.com/gkDSdS5v

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
45f8135ac45799e555449bebb6d2a78869a439b6

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
over 1 year since the last crash report, if this bug is still valid, plz open a new ticket with updated core.
