### ISSUE TITLE
Summoning Stones and most likely Warlock Summons also

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18540]
**Description:**
Instances and Raid Summoning Stones
**Current behaviour:** (Tell us what happens.)
Clicking a summoning stone while targeting a party member starts a cast , after which it pops up the portal which another player should click , after the click it will start another cast that will summon the target person.
**Expected behaviour:** (Tell us what should happen instead.)
Clicking a summoning stone should make the cast instant same as the summoning cast , there shouldn't be any casts
**Steps to reproduce the problem:**

1. Go to a summon stone with a friend
2. Try to summon him
3. Make him click the portal.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
TrinityCore rev. 32570f7203bb
**TDB version:**  
703.00
**Operating system:**  
Win 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Dup #17795
