### ISSUE TITLE
[master] Not handled opcodes.

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18545]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Many not handled opcodes, that block many key features, 
For example:

CMSG_SAVE_CLIENT_VARIABLES - key and spellbindings. They reset almost every relog and spec change.
CMSG_DF_JOIN - dungeon finder queue.
CMSG_BATTLEMASTER_JOIN_SKIRMISH - obvious.

**Current behaviour:** All of them not working, server console spammin errors.

**Expected behaviour:** All of them should get response.

**Steps to reproduce the problem:**

1.  Create a char, use .levelup till 20+ and try to queue.
2.  Bind few spells/change keybindings in options, change spec.
3.  Relog, change spec back.

**Branch(es):** master

**TC rev. hash/commit:**  538c8c3843fdf8705e348960d19b279653c03b95

**TDB version:**  703.00 with custom updates.

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#14216
