### ISSUE TITLE
Core/Spells: AuraEffect::HandleProcTriggerSpellAuraProc wrong error

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18543]
**Description:**

> AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 41469 proc, because the spell does not have an entry in Spell.dbc.

**Current behaviour:** Using aura 41469 should proc 42058. Proc looks right but trigger a error in terminal

**Expected behaviour:** Spell 41469 should proc normally 42058 without trigger any error.

**Steps to reproduce the problem:**

1. Add aura 41469 in yourself
2. Hit melee some creature
3. Look into terminal

Is weird because Seal of Command (41469) in EFFECT_0 has AuraType: SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE that should be handled by ```AuraEffect::HandleProcTriggerSpellWithValueAuraProc()```.
Nice part is: I added a breakpoint inside of ```AuraEffect::HandleProcTriggerSpellAuraProc``` and when error is trigged, indexEffect = 2, so... is trigged by EFFECT_2 of 41469.

> Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 41470
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> Aura Id 4 (SPELL_AURA_DUMMY), value = 41470, misc = 0 (0), miscB = 0, periodic = 0

**Branch(es):** 3.3.5
**TC rev. hash/commit:**   c809c220e29f7094121cc8489f5588d8bfee414d

**Comment by Keader** [comment]
@ariel-

**Comment by joschiwald** [comment]
@ariel- triggering AuraEffect::HandleProcTriggerSpellAuraProc by SPELL_AURA_DUMMY is still wrong, create a generic spellscript

**Comment by Jildor** [comment]
Poor @ariel- xD

![Homer Hair](http://3.bp.blogspot.com/-KQqHgCh0K4U/TnY27Y6eHSI/AAAAAAAAAQ8/fwF_q4RrPKs/s320/18136_415613530555_179247985555_10603895_730636_n.jpg)

**Comment by ariel-** [comment]
@joschiwald What about?

```
ID - 12958 Gag Order (Rank 2)
=================================================
Description: Gives your Shield Bash and Heroic Throw abilities a $h% chance to silence the target for $18498d and increases the damage of your Shield Slam ability by $s2%.
Category = 0, SpellIconID = 280, activeIconID = 0, SpellVisual = (0,0)
Family SPELLFAMILY_WARRIOR, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x000001D0 (SPELL_ATTR0_ABILITY, SPELL_ATTR0_PASSIVE, SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
AttributesEx3: 0x04000000 (SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED)
=================================================
Skill (Id 257) "Protection"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 1, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Proc flag 0x00015550, chance = 100, charges - 0
=================================================
  04 Successful attack by Spell that use melee weapon
  06 Successful Ranged attack(and wand spell cast)
  08 Successful Ranged attack by Spell that use ranged weapon
  10 Successful positive spell hit
  12 Successful negative spell cast
  14 Successful cast positive magic spell
  16 Successful damage from harmful magic spell cast
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 0, misc = 0 (0), miscB = 0, periodic = 0
   Trigger spell (18498) Silenced - Gag Order. Chance = 100
   Description: Gives your Shield Bash and Heroic Throw abilities a chance to silence the target for $18498d and increases the damage of your Shield Slam ability.
   ToolTip: Silenced.
```

**Comment by joschiwald** [comment]
i would create a spellscript

**Comment by Keader** [comment]
b84348f6fc7746349fdcbd443b32fe5483174442
