### ISSUE TITLE
[3.3.5 / Ruby Sanctum] Baltharus Warborn cast interrupt by UpdateSplineMovement

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18549]
**Description:** Cast of spell 76221 (SPELL_BARRIER_CHANNEL) is interrupted by movement

**Expected behaviour:** Cast of SPELL_BARRIER_CHANNEL should be interrupted only when Baltharus enter combat

**Steps to reproduce the problem:**

1. go to Baltharus (.go crea id 39751)
2. observe channel cast

Callstack from Spell::cancel() -> https://gist.github.com/Keader/943ee8c122814a0370c09b2e291e7d91

Looks like similar problem fixed in 90a58117017a93fa33864fe1892e7304e2f3bbf4

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c809c220e29f7094121cc8489f5588d8bfee414d

**Comment by xinef1** [comment]
Try this, movement shouldn't be allowed if spell is interrupted by movement
```c++
 src/server/game/Spells/SpellInfo.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index 8394ca7..f1c49d5 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -1211,7 +1211,7 @@ bool SpellInfo::IsChanneled() const
 
 bool SpellInfo::IsMoveAllowedChannel() const
 {
-    return IsChanneled() && HasAttribute(SPELL_ATTR5_CAN_CHANNEL_WHEN_MOVING);
+    return IsChanneled() && (HasAttribute(SPELL_ATTR5_CAN_CHANNEL_WHEN_MOVING) || (ChannelInterruptFlags & (AURA_INTERRUPT_FLAG_MOVE | AURA_INTERRUPT_FLAG_TURNING)));
 }
 
 bool SpellInfo::NeedsComboPoints() const
```

**Comment by Keader** [comment]
@xinef1 Tested and does not work for Baltharus

**Comment by xinef1** [comment]
Well, spell 76221 has 0x1000101F channelinterruptflags (both AURA_INTERRUPT_FLAG_MOVE and AURA_INTERRUPT_FLAG_TURNING). This means that some movegen allows to move without checking for IsMovementPreventedByCasting
At the first glance, the channel is cast at reset function (which appears directly after evade or init). Try moving it to JustReachedHome and see if it helps.

I also got this in spellmgr, maybe helpful:

<details>

```c++

		// Barrier Channel
		case 76221:
			spellInfo->ChannelInterruptFlags &= ~(AURA_INTERRUPT_FLAG_TURNING|AURA_INTERRUPT_FLAG_MOVE);
			spellInfo->EffectImplicitTargetA[EFFECT_0] = TARGET_UNIT_NEARBY_ENTRY;
			break;

```

</details>

**Comment by xinef1** [comment]
@Keader Update his orientation to 4,76864 (the angle at which he faces the trigger with channel) and apply  https://github.com/TrinityCore/TrinityCore/pull/18595

**Comment by Keader** [comment]
> [214] GUID: Full: 0xF130009B4700BB4A Type: Creature Entry: 39751 (Baltharus the Warborn) Low: 47946
> [214] Object Type: Unit (3)
> [214] Update Flags: Living, StationaryObject (96)
> [214] Movement Flags: None (0)
> [214] Extra Movement Flags: None (0)
> [214] Time: 2333322435
> [214] Position: X: 3153.061 Y: 389.4861 Z: 86.25955
> [214] Orientation: 5.637414

Current orientation is right.
And without change orientation #18595 dont work for me

**Comment by xinef1** [comment]
Then he needs a hook in spellmgr, you can check yourself that he changes orientation and this causes the channel to interrupt.

**Comment by Keader** [comment]
@xinef1 i tested today with https://github.com/TrinityCore/TrinityCore/issues/18549#issuecomment-269149153 and still dont work. He still interrupt cast

**Comment by xinef1** [comment]
@Keader Update his orientation to 4,76864 or remove AURA_INTERRUPT_FLAG_TURNING|AURA_INTERRUPT_FLAG_MOVE from ChannelInterruptFlags

**Comment by Keader** [comment]
already changed orientation to 4,76864 and dont work.
Not tested remove this flags

**Comment by xinef1** [comment]
Fuzzy eps is too small to compensate for change from loaded db orientation to GetAngle(target)

**Comment by ariel-** [comment]
Reopening, turning state doesn't get removed, if I add remove state in Creature::ReleaseFocus, spell is again cancelled.

This is not due to eps diff (creature orient is 5.637414, faces 4.76864).
What needs to be done here is don't cancel own channeling when we're facing just to start the channel

**Comment by ariel-** [comment]
No longer an issue in 522f537048189b40a12d68583485d1de7fcbf1d2

**Comment by Keader** [comment]
Just for references: https://github.com/TrinityCore/TrinityCore/commit/5a2f0ce29e29d934c200f617fec6dad619fab9a5#diff-4522eeffcbc961602e86620011a2d579 removed fix made by ariel
