### ISSUE TITLE
[master] Valarjar Aspirant Crash

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18544]
**Description:**
Valarjar Aspirant Crash
**Current behaviour:** (Tell us what happens.)
When you attack and not kill the npc , world server will crash
**Expected behaviour:** (Tell us what should happen instead.)
No crash
**Steps to reproduce the problem:**

1. .npc add 101637
2. attack with normal attacks so that the mob will still survive while getting in combat
3. after 1 sec world server will crash

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
TrinityCore rev. 32570f7203bb
**TDB version:**  
703.00
**Operating system:**  
Win 10 x64

**Comment by Eredar** [comment]
I repeat: db is far, really far away from complete state to report single creature issues. More of that, you are reporting npc that belongs to not spawned (warrior order hall) location. It obviously has wrong stats, wrong fields in creature_template and addon, etc. Best you can do right now for such issues is to get live server data (sniffs), get creature_template string of this mob, and fix it accordingly.

**Comment by DDuarte** [comment]
Post the crashlog.

**Comment by Eredar** [comment]
> Post the crashlog. 

For attacking a friendly both to A and H npc? Seriously?

**Comment by jackpoz** [comment]
> For attacking a friendly both to A and H npc? Seriously?

Yes, seriously.

**Comment by Aokromes** [comment]
no answer after more than 2 years. closing.
