### ISSUE TITLE
Mac OS X Sierra error bnetserver & world server compile

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#18552]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Error during bnetserver compiles

**Current behaviour:** (Tell us what happens.) The solution can't be compiled in Xcode because of these errors:
BNETSERVER:  http://pastebin.com/7S9PniwR
WORLDSERVER: http://pastebin.com/PuXbnh1c

**Expected behaviour:** (Tell us what should happen instead.) 
The solution should compile as in Windows.

**Steps to reproduce the problem:**

1. Clone TC repo
2. CMAKE using Xcode (install all libraries using TC forum guide)
3. Compile

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) Master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/538c8c3843fdf8705e348960d19b279653c03b95

**TDB version:**  Latest with updates

**Operating system:**  Mac OS X Sierra

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by LuigiElleBalotta** [comment]
Any news?

**Comment by Shauren** [comment]
Nope. No mac devs. I can only guess that your openssl version is bad because linker errors are related to it

**Comment by avengerweb** [comment]
same os, 3.3.5 branch build

-DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 helps

```

Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init.9 in ScriptPCH.cpp.o
      ___cxx_global_var_init.12 in ScriptPCH.cpp.o
      __GLOBAL__sub_I_ScriptPCH.cpp in ScriptPCH.cpp.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_ScriptPCH.cpp in ScriptPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/scripts/libScriptPCH.cpp_dephelp.so] Error 1
make[1]: *** [src/server/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/all] Error 2
make: *** [all] Error 2
```
