### ISSUE TITLE
I am a new trinitycore user

### ISSUE THREAD

**Issue by zeframek** [TrinityCore/TrinityCore#18555]
Please help

I do not know where to go, I'm from the Czech Republic and try trinitycore so far I like it but I want to ask on this site:
http://www.ac-web.org/forums/showthread.php?90805-C-Buy-Experience-NPC

I also have this code that I found:
http://www.ac-web.org/forums/showthread.php?95072-Lua-Buy-XP-NPC

But I do not know how it incorporated into trinitycore and how to then get into the game and whether it will work on trinitycore. Much advice please thank you.

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
This is not a forum.

**Comment by zeframek** [comment]
And can you give me some advice ?? I do not know where I go. :(

**Comment by Keader** [comment]
Hey @zeframek  you can try start with our forum : https://community.trinitycore.org/ and has some helpful informations here: https://github.com/TrinityCore/TrinityCore/wiki
Btw Welcome :)

**Comment by chaodhib** [comment]
You will also find good information here: https://trinitycore.atlassian.net/wiki/

Welcome by the way

**Comment by Aokromes** [comment]
P.S: TrinityCore don't supports LUA.
