### ISSUE TITLE
[master]TARGET_UNK_120; Implosion Crash

### ISSUE THREAD

**Issue by cbcs** [TrinityCore/TrinityCore#18558]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
TARGET_UNK_120 or Implosion Crash
**Current behaviour:** (Tell us what happens.)
When you use Implosion , world server will crash
**Expected behaviour:** (Tell us what should happen instead.)
No crash
**Steps to reproduce the problem:**

1. creatre Warlock (Demonology)
2. use Implosion or .cast 196277
3. world server will crash

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master 
**TC rev. hash/commit:**  
TrinityCore rev.https://github.com/TrinityCore/TrinityCore/commit/40cdc86e9aa00e2772db567e631ca858ab1c5be9
**TDB version:**  
703.00
**Operating system:**  
Win 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Post a crashlog.

**Comment by cbcs** [comment]
[crash.txt](https://github.com/TrinityCore/TrinityCore/files/670712/crash.txt)

**Comment by ariel-** [comment]
> When you use Implosion , world server will crash

Works as intended?

**Comment by buenodart** [comment]
Hey guys! 
I have this problem right now!

the last message on my worldserver.exe was:

C:\TrinityCore\src\server\game\Spells\Spell.cpp:1219 in Spell::SelectImplicitAreaTargets ASSERTION FAILED:
  false && "Spell::SelectImplicitAreaTargets: received not implemented target reference type"

And then... got crashed

there is a solution for this??

Thanks

**Comment by Ulduar** [comment]
Temporary solution (yes, this is hackfix, but i don't have other solution).
Replace target 120 on target 15.
```SQL
REPLACE INTO `spell_effect`(`ID`,`Effect`,`EffectBasePoints`,`EffectIndex`,`EffectAura`,`DifficultyID`,`EffectAmplitude`,`EffectAuraPeriod`,`EffectBonusCoefficient`,`EffectChainAmplitude`,`EffectChainTargets`,`EffectDieSides`,`EffectItemType`,`EffectMechanic`,`EffectPointsPerResource`,`EffectRealPointsPerLevel`,`EffectTriggerSpell`,`EffectPosFacing`,`EffectAttributes`,`BonusCoefficientFromAP`,`PvpMultiplier`,`Coefficient`,`Variance`,`ResourceCoefficient`,`GroupSizeBasePointsCoefficient`,`EffectSpellClassMask1`,`EffectSpellClassMask2`,`EffectSpellClassMask3`,`EffectSpellClassMask4`,`EffectMiscValue1`,`EffectMiscValue2`,`EffectRadiusIndex1`,`EffectRadiusIndex2`,`ImplicitTarget1`,`ImplicitTarget2`,`SpellID`,`VerifiedBuild`) VALUES  
(302944,3,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,12,15,0,196277,26654);
```

**Comment by Seyden** [comment]
its working as intended as long no one implements this target type..
