### ISSUE TITLE
[master] Average item level.

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18556]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** No equipped/max itemlevel calculations in Character window (C by default).

**Current behaviour:** 0 in all cases.

**Expected behaviour:** Two values. One for equipped average itemlevel, another for maximum average ilvl in bags.

**Steps to reproduce the problem:**

1.  Equip anything. Change items.
2.  Press C. (or open character window).
3.  Look at the item level.

**Branch(es):** master 

**TC rev. hash/commit:**  40cdc86  

**TDB version:**  TDB 703.00 with custom patches.

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by BahDumbBugs** [comment]
Duplicate. 16111
