### ISSUE TITLE
[CRASH] SendToAllButOne

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#18551]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
SendToAllButOne<Channel::JoinNotify(ObjectGuid) const::<lambda(WorldPacket&, LocaleConstant)> > (who=..., builder=..., this=0x7ffeac0d4480)

**Current behaviour**: Tell us what happens
Not sure why is this happening.

- http://pastebin.com/hmAPjdqw

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
45f8135ac45799e555449bebb6d2a78869a439b6

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Jildor** [comment]
Confirm: https://gist.github.com/Jildor/fd21c695bd680b07066e0c1da1747482

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Aokromes** [comment]
no more reports of this crash after a more than a year. closing, if this bug is still valid open a new ticket with updated core.

**Comment by Voidx** [comment]
Crash contunes https://pastebin.com/GGxgcLJk
Branch(es): 3.3.5

TC rev. hash/commit: 12679fdd080e48c684c6a557754e4ed53c7cd068

Operating system: Ubuntu server

**Comment by Killyana** [comment]
@Voidx open a new issue please.
