### ISSUE TITLE
[3.3.5/Ulduar] XT002 broken heart

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18557]
**Description:** When XT002 enter in heart phase, heart "drop" of boss body and despawn

**Current behaviour:** Heart despawn when leaves boss body (https://youtu.be/zsdHry4GYTo)

**Expected behaviour:** Heart should be exposed  and players should damage him

**Steps to reproduce the problem:**

1. Go to XT002 ( .go crea id 33293)
2.  Start fight and do some damage to force phase change

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  dbd567799f47cea46cdf4f1fb3dc61960fd283ab

It was working in rev 1f83412e4dacfa21754064c7a0a7690bb1363564 (last time i checked)

**Comment by xinef1** [comment]
@Keader the heart is installed as minion, and during fight it changes seats. As for now it changes seats by casting new control vehicle aura, which forces heart to eject xt-002 and as a minion it gets despawned on exit. I Suggest to change spellcast to ChangeSeat function which only removes unit from vehicle without calling additional functionality. 

```diff
 src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
index c77d210..b0fda6d 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
@@ -367,7 +367,7 @@ class boss_xt002 : public CreatureScript
                     heart->CastSpell(heart, SPELL_HEART_OVERLOAD);
                     heart->CastSpell(me, SPELL_HEART_LIGHTNING_TETHER);
                     heart->CastSpell(heart, SPELL_HEART_HEAL_TO_FULL, true);
-                    heart->CastSpell(me, SPELL_RIDE_VEHICLE_EXPOSED, true);
+                    heart->ChangeSeat(HEART_VEHICLE_SEAT_EXPOSED, false);
                     heart->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     heart->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNK_29);
                }
@@ -403,7 +403,7 @@ class boss_xt002 : public CreatureScript
                 if (!heart)
                     return;
 
-                heart->CastSpell(me, SPELL_HEART_RIDE_VEHICLE, true);
+                heart->ChangeSeat(HEART_VEHICLE_SEAT_NORMAL, false);
                 heart->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 heart->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNK_29);
                 heart->RemoveAurasDueToSpell(SPELL_EXPOSED_HEART);
```

**Comment by Keader** [comment]
Hmm, work but still wrong.
This change seats should be hande by spells...
Some recent change in core broken it

**Comment by xinef1** [comment]
It was always that way :p if you are not satisfied with this fix, remove minion flag in vehicle_template_accessory and ensure that heart will be despawned on xt-002 death.
