### ISSUE TITLE
[3.3.5] Honor among thieves breaks stealth

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18553]
**Description:** If i use rupture on a target and go stealth, when rupture crits it breaks stealth, only on crits. same happends on honor among thieves procs.

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Neither rupture crits nor honor should break stealth.

**Steps to reproduce the problem:**

1. get combo points
2. apply rupture to any npc
3. vanish and notice when it crits you destealth if you have honor among thieves in talents

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/dbd567799f47cea46cdf4f1fb3dc61960fd283ab

**TDB version:**  65

**Operating system:**  unbuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Persephone** [comment]
added these values in spell_custom_atr and it fixed it:

51698	64
51699	64
51700	64
51701	64
52916	64
1943	64

**Comment by Noryad** [comment]
Maybe related with #18421

**Comment by Persephone** [comment]
yeah try add those abilities into the spell_custom_Atr like i did and test should fix it

**Comment by Dalgurakk** [comment]
@Persephone  can you email me to delvalmorell8606@gmail.com with a brief explanation about spell proc system, masks, flags... please? ^^

**Comment by Persephone** [comment]
@Dalgurakk I dont know much about it, just that attribute 64 is "does not break sttealth"

**Comment by Keader** [comment]
@Dalgurakk look: https://github.com/TrinityCore/TrinityCore/pull/14824 (about this custom_attr)
