### ISSUE TITLE
[NPC] Blade's Edge plateaus - Remove creatures

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#18561]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/npc=22187/bladespine-basilisk

By adashiel (274,268 – 13·81·927) on 2007/10/07 (Patch 2.2.2)
They were removed in 2.1 when the Blade's Edge plateaus were turned into questing areas.

http://www.wowhead.com/npc=22187/bladespine-basilisk#comments:id=163931

So, let's remove them.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/5b8b779a5cbf68f8b670ea20550ac5fd0656bef8

**Operating system:**  
win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
Fix:

```sql
-- 
-- Bladespine Basilisk
-- (WoWHead) They were removed in 2.1 when the Blade's Edge plateaus were turned into questing areas.
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 22187);
DELETE FROM creature WHERE id = 22187;
```

credits to https://github.com/cmangos/wotlk-db/blob/83c35f1b0de4e7221512883dcc1c78a88b605f56/Updates/645_RandomFixes.sql and ty @Grz3s

**Comment by offl** [comment]
What about the other?
```sql
DELETE FROM `creature_addon` WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id` IN (22174,22182,22187,22201,22202,22217,22218,22221));
DELETE FROM `creature` WHERE `id` IN (22174,22182,22187,22201,22202,22217,22218,22221);
```

**Comment by Killyana** [comment]
Someone must check The crystalspine, Bash'ir Landing, Forge Camp Wrath, Ogri'la and Forge Camp as probably many spawns are missing.
