### ISSUE TITLE
[Master] Human Infestation Quest Issue

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18567]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Quest ID is 28138; Humans are bound already, and using the shackles do not work, except to unbind them, in which case they start attacking and flee when their lives get low.......only to be mauled and killed by the Domesticated Mine Creeper and NPC's Captain Keyton and the Spider-Handler Saurus. *sigh*

http://i.imgur.com/BlY3wxZ.jpg

**Current behaviour:** See above.

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. Finish Welcome to the Machine (Quest Chain - 28096) 
2. Accept quest from Captain Keyton
3. Next?

**Branch(es):** Master 

**TC rev. hash/commit:**  8b2e071

**TDB version:**  7.01

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Hillsbrad Foothills is not scripted, there's a general issue about quests not scripted.

**Comment by Rushor** [comment]
yeah just for reference: https://github.com/TrinityCore/TrinityCore/issues/15182

**Comment by BahDumbBugs** [comment]
@Rushor @Killyana Thank you. I had forgotten about the zones still needing work.
