### ISSUE TITLE
[master] Add currency to npc_vendor table

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18560]
**Description:**
Add currency to npc_vendor table
**Current behaviour:** (Tell us what happens.)
Currently I can't see a proper way to add a currency to the npc_vendor template because the 
**Expected behaviour:** (Tell us what should happen instead.)
It should be possible to add currencys at vendors.
**Steps to reproduce the problem:**

1. Check npc 87391 or 88570
2. Look at Seal of Tempered Fate
3. Check npc_vendor table and try to add it somehow directly

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
TrinityCore rev. 32570f7203bb
**TDB version:**  
703.00
**Operating system:**  
Win10 x64

**Comment by Aokromes** [comment]
Very likely it's ExtendedCost

**Comment by adryan66** [comment]
Extended cost applyes to items like tier with the helm as the extended cost , or like the halaa items that require other items , theese items are in the vendor directly with gold as the price , like a green item for example.
At least that's how I understood it.

**Comment by Shauren** [comment]
You add it the same way as regular items but set npc_vendor.type=2
