### ISSUE TITLE
[DEV] Core: Monster sparring

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18576]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Initial support for monster sparring was implemented here https://github.com/TrinityCore/TrinityCore/pull/17673

Only melee attack are working now, spells still deal damage, Also some mechanism like deal damage only until health% is not implemented.

Old issue: https://github.com/TrinityCore/TrinityCore/issues/13258

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  rev. 3e51583e6cde

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
After further investigation all known npcs that mustn't take damage under 85% hp from other creature have the flag CREATURE_DIFFICULTYFLAGS_4_UNK4 = 0x00000080 -- 128
name from binary: No NPC damage below 85%" flag for unit(s)

**Comment by Kittnz** [comment]
Then we just need a check?

**Comment by kelno** [comment]
@Killyana How do you even get those names?

**Comment by illfated** [comment]
@kelno : Looks like they are available in the source code in the `master` branch:

https://github.com/TrinityCore/TrinityCore/blob/f48b87054ed923f0af40065da90fea8bb233aff0/src/server/game/Entities/Creature/CreatureData.h#L34-L280

Not sure if they are available in 3.3.5 source, maybe one of the TC devs can tell you more.

**Comment by kelno** [comment]
Thanks, but I've seen that, the " No NPC damage below 85%" flag for unit(s)" part is what I'm wondering about, since Killyana mention "name from binary"

**Comment by illfated** [comment]
Not sure about that, maybe it is something from the DBC files?
