### ISSUE TITLE
[Quest][Wotlk] Return to Angrathar

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#18609]
As mentioned in https://github.com/TrinityCore/TrinityCore/issues/10750

the movie should be played on quest reward http://wotlk.openwow.com/quest=12499 https://youtu.be/2whrNZz2USM?t=72

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/bddf15d6965d7deafed3f0da3efda6b8e41de9e0

**Operating system:**  
win 10

**Comment by Rushor** [comment]
fix:

```sql
-- Highlord Bolvar Fordragon SAI
SET @ENTRY := 27872;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,20,0,100,0,12499,0,0,0,68,14,0,0,0,0,0,7,0,0,0,0,0,0,0,"Highlord Bolvar Fordragon - On Quest 'Return To Angrathar' Finished - Play Movie 14");
```

**Comment by Kittnz** [comment]
Does this area actually works perfectly?

**Comment by Rushor** [comment]
dr-j pushed some stuff for the wrathgate  a year ago. some npc fights look weird but the spawns seem to be correct
