### ISSUE TITLE
creature_template

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18618]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Many flags missing for the creatures + incorrect unit_class value

**Current behaviour:** (Tell us what happens.)

Lots of errors in the console

**Expected behaviour:** (Tell us what should happen instead.)

They should have this flag and probably due to the fact, that core sets unit_class to 1 anyways, this can temporary solve "console spam"

**Steps to reproduce the problem:**

1. Clean install
2. Place database files in core folder
3. Start the core

**Branch(es):** master

**TC rev. hash/commit:**  
9f81cf445ff4
**TDB version:**  
7.0.3
**Operating system:**  
TrinityCore rev. 9f81cf445ff4 2016-12-25 19:13:24 +0100 (master branch) (Win64, Debug, Static)

Here is possible solution (used script to gather all errors from log, filter all NPCs and specified flag and returned SQL file):  https://www.dropbox.com/s/fxcozz0gcv9c41r/creature_template.sql?dl=0

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by zamalaev** [comment]
thx, I will use this data to my base is need correct faction NPC
in my database have the spawn NPC of Pandaria Legion Draenor

**Comment by darki73** [comment]
There are around 24k wrong faction entries, they also set to 0. For myself, I've updated them all to 2085 or 2805 (smith like that), but this is totally wrong move. Not planning to create private server, so don't need this data to be accurate

**Comment by DDuarte** [comment]
> Not planning to create private server, so don't need this data to be accurate

That's an even better reason to make it right...

---

Default faction is 35

**Comment by zamalaev** [comment]
darki73, no private server!!! OpenSource project https://bitbucket.org/projectlegion/

**Comment by Aokromes** [comment]
since this is a hack closing, ref errors:
#15829
