### ISSUE TITLE
quest_template_addon

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18617]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Many quests missing SpecialFlag EVENT_OR_EXPLORATION

**Current behaviour:** (Tell us what happens.)

Lots of errors in the console

**Expected behaviour:** (Tell us what should happen instead.)

They should have this flag

**Steps to reproduce the problem:**

1. Clean install
2. Place database files in core folder
3. Start the core

**Branch(es):** master

**TC rev. hash/commit:**  TrinityCore rev. 9f81cf445ff4 2016-12-25 19:13:24 +0100 (master branch) (Win64, Debug, Static)

**TDB version:**  703.00

**Operating system:**  

Here is possible solution (used script to gather all errors from log, filter all NPCs and specified flag and returned SQL file):  http://pastebin.com/g7ai7sqC

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
https://trinitycore.atlassian.net/wiki/display/tc/SQL+Guidelines

**Comment by Exodius** [comment]
Formatting...
457 lines. Truth be told, I'm lazy to make a `DELETE FROM` query..
http://pastebin.com/yQ0uMb7a

**Comment by Aokromes** [comment]
cannot apply this sql.

**Comment by Aokromes** [comment]
#15829
