### ISSUE TITLE
creature_questender

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18616]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
There are many (3058) errors regarding quest ender table. 

**Current behaviour:** (Tell us what happens.)

Some of the NPCs (1272) do not have required UNIT_NPC_FLAG_QUESTGIVER

**Expected behaviour:** (Tell us what should happen instead.)

They should have this flag

**Steps to reproduce the problem:**

1. Clean install
2. Place database files in core folder
3. Start the core

**Branch(es):** master

**TC rev. hash/commit:**  
9f81cf445ff4
**TDB version:**  
7.0.3
**Operating system:**  
TrinityCore rev. 9f81cf445ff4 2016-12-25 19:13:24 +0100 (master branch) (Win64, Debug, Static)

Here is possible solution (used script to gather all errors from log, filter all NPCs and specified flag and returned SQL file):  http://pastebin.com/6X1LCRC4

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
better use 
```SQL
WHERE `entry` IN and  `npcflag` =  `npcflag` | 2

**Comment by Exodius** [comment]
Formatting...
http://pastebin.com/47whyuzK

**Comment by Aokromes** [comment]
This was fixed somewhere on #15829
