### ISSUE TITLE
[Quest] Defending Wyrmrest Temple

### ISSUE THREAD

**Issue by DannyDD** [TrinityCore/TrinityCore#1861]
Core Hash: a1ed562+
DB: TDB_335.11.40_2011_05_09 + all updates until 2011_06_05_00_world_spelldifficulty_dbc

Can use the drake mount but it hasn't any skills. Loads of spawns of azure dragons on the ground... Can't be killed meele wise because of the spell they do...

**Comment by MitchesD** [comment]
Already fixed
