### ISSUE TITLE
[3.3.5] NPC Steward of Time 

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18615]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
You can't fly with Steward of Time 
Comes only the message "is too far away"

![hdz](https://cloud.githubusercontent.com/assets/10637389/21483109/821d20a0-cb7d-11e6-8ff9-4f3b76cdeb06.jpg)

**Steps to reproduce the problem:**

1. .go 8165 -4773 35 1
2. Talk with Steward of Time
 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
TrinityCore rev. bf7e95bd5703 2016-12-26 14:25:32 +0100 (335 branch)

**TDB version:** 
TDB_full_world_335.62_2016_10_17.sql + updates 

**Operating system:**  
Win7 64Bit

**Comment by Kittnz** [comment]
tried without gm on?

**Comment by Tauriella** [comment]
GM is off, and i have testet with normal Player Char
Same result " i to far away "

**Comment by Staleness89** [comment]
confirm, I tried giving the SAI spellcasts the triggered CastFlag but I guess it doesn't ignore range requirements. Weird though because it's an SMART_ACTION_INVOKER_CAST, shouldn't have a range problem.

**Comment by Staleness89** [comment]
I looked in the Taxi dbcs, found the starting position of this taxi, moved the Steward closer to this position, and that fixes it. Could it be that the Steward is spawned in the wrong spot?

**Comment by Aokromes** [comment]
it was working for years, and i don't remember any commit moving it, also another mob on dragonbright have the same issue.

**Comment by Aokromes** [comment]
#15398

**Comment by ariel-** [comment]
For this particular issue, I found in sniff creature casting first 45331 (serverside spell). After this player self casts 34891, still taxis activated through spells check against the dbc node position.

There is no way to associate the caster with the npc triggering the event, as it's the same player. Should it be better to actually drop the check entirely if activating taxi through a spell?

**Comment by Tauriella** [comment]
@ariel- 
Maybe they look in the cmangos code as the have solved.
There it works.
