### ISSUE TITLE
Last Quest area [The Light of Dawn] !

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#18628]
Hello friends
--------------------
[The Light of Dawn]
Last Quest is a problem area - bugged

This problem is very serious!

[screenshot](http://imgur.com/rvbNpqu)

[screenshot](http://imgur.com/32nNCF7)

[screenshot](http://wow.zamimg.com/uploads/screenshots/normal/278228-the-light-of-dawn.jpg)

Here is a video how it should be : [YouTube](https://www.youtube.com/watch?v=fM8RKUeGkug)

full original report post: [click!](https://github.com/TrinityCore/TrinityCore/issues/18626)

There Reports: [report](https://github.com/TrinityCore/TrinityCore/issues/17671)

wowhead: [link](http://www.wowhead.com/quest=12801/the-light-of-dawn)

Why not solve the problem!
Please: One entry to this thread to fix it

TC rev. hash/commit:
 3.3.5 TDB 62 - last version
download: git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git

Operating system:
OS: Linux ubuntu 16.10

**Comment by Keader** [comment]
Dup #18401
