### ISSUE TITLE
[3.3.5] Scripts/Spells: Problems with mounts which change depending on your Riding skill and location

### ISSUE THREAD

**Issue by Cannix** [TrinityCore/TrinityCore#18627]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
You can fly with mounts which change depending on your Riding skill and location (e.g. 72286, Invincible) in some areas where it shouldn't be possible.
There are areas (e.g. 3479, The Veiled Sea on map 530) which don't have the AREA_FLAG_NO_FLY_ZONE flag but lie on the bc or northrend maps.

spell_generic.cpp
```
class spell_gen_mount

     uint32 map = GetVirtualMapForMapAndZone(target->GetMapId(), target->GetZoneId());
     if (map == 530 || (map == 571 && target->HasSpell(SPELL_COLD_WEATHER_FLYING)))
         canFly = true;

    AreaTableEntry const* area = sAreaTableStore.LookupEntry(target->GetAreaId());
    if (!area || (canFly && (area->flags & AREA_FLAG_NO_FLY_ZONE)))
        canFly = false;
```

**Current behaviour:** (Tell us what happens.)
You can fly with speed changing mounts in areas where you shouldn't be able to.

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. .go xyz -4264 -11335 6 530
2.  .cast 72286
3.  Jump

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
8fe85017125803a4ca8fd1d972b128930cd364b9

**TDB version:**  
TDB 335.61

**Operating system:**  
Debian, Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by xinef1** [comment]
```diff

 src/server/game/Spells/SpellMgr.cpp | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 02ff038..d9fccdc 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3496,6 +3496,10 @@ void SpellMgr::LoadSpellInfoCorrections()
         }
     }
 
+    // The Veiled Sea area in outlands (Draenei zone), client blocks casting flying mounts
+    if (AreaTableEntry* areaEntry = const_cast<AreaTableEntry*>(sAreaTableStore.LookupEntry(3479)))
+        areaEntry->flags |= AREA_FLAG_NO_FLY_ZONE;
+
     if (SummonPropertiesEntry* properties = const_cast<SummonPropertiesEntry*>(sSummonPropertiesStore.LookupEntry(121)))
         properties->Type = SUMMON_TYPE_TOTEM;
     if (SummonPropertiesEntry* properties = const_cast<SummonPropertiesEntry*>(sSummonPropertiesStore.LookupEntry(647))) // 52893
 
```

**Comment by ariel-** [comment]
> There are areas (e.g. 3479, The Veiled Sea on map 530) which don't have the AREA_FLAG_NO_FLY_ZONE flag but lie on the bc or northrend maps.

Can you fly with a regular flying mount in those zones? If not, then this script  needs to replicate the check done in https://github.com/TrinityCore/TrinityCore/blob/072ea761c6dc9891d0e929f0e618b7ae2327c421/src/server/game/Spells/SpellInfo.cpp#L1470 (Btw this amount of code duplication is bad, the same spell_gen_mount script causes #16783)

**Comment by Cannix** [comment]
No, you can't. regular flying mounts are blocked by the client.

**Comment by ariel-** [comment]
On 29827855d06bb41dd2109fc36935fc84925eb094 does not fly, but mount doesn't appear either (spell cast fails due to not being in flyable zone).

I have checked and dbc correction is not necessary. I'll use proper spell functions for checking fly-ability.
