### ISSUE TITLE
Core/Spell Charge of Warriors broken. 

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18629]
Description:
The spell Charge of warrior class, wich says: "Charge to an enemy unit, rooting it for 1.5 sec. 8-25 yards range, instant, generates 20 rage, 20 secs cooldown" have a malfunction. Does not work either on Training Dummys as on NPCs, used by a human character on level 3. This problem make imposible to deliver the quest "Charging into battle" (ID: 24969), given by LLane Beshere (DB GUID: 279903) at Northshire Valley (ID: 9) wich says: "Reach level 3 and practice using Charge on a Trainig Dummy".

Current behaviour:
The skill does not charge at all when use it, the character stays in the place and produces the visual efects except the ones related with the aproach of the player to his target, generates rage, but does not approach the character to the target and does not root it. When done, the quest does not count it as so.

Expected behaviour:
When Using Charge, the character must reach his target and then do the others effects as root. The quest must be completed after practicing Charge on a Trainig Dummy.

Steps to reproduce the problem:

1- Create a human warrior character.
2- Reach level 3.
3- Use Charge.

Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
TC rev. hash/commit:
9f81cf445ff47507a9469d57808df231460793f1
TDB version:
7.0.3+updates
Operating system:

**Comment by Edreisantafe** [comment]
This patch fix the problem blizzlike, i think...



[0001-Fixing-the-Warrior-Charge-Spell.zip](https://github.com/TrinityCore/TrinityCore/files/673492/0001-Fixing-the-Warrior-Charge-Spell.zip)

**Comment by Aokromes** [comment]
#14825
