### ISSUE TITLE
[Sniff][SQL][Legion] Dalaran and Druid Order Hall Complete Sniff

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18625]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

This is SQL files for Druid Order Hall as well as Dalaran (Legion version) from Live server. Clicked and interacted will all possible NPCs and objects there. 
![wowscrnshot_122716_033506](https://cloud.githubusercontent.com/assets/1318627/21486038/d65918b2-cbe7-11e6-84c6-b845bbf00c17.jpg)

**Current behaviour:** (Tell us what happens.)

Warrior order hall is not populated at all

**Expected behaviour:** (Tell us what should happen instead.)

Well, it should be populated

**Steps to reproduce the problem:**

1. Clean installation
2. Start the core
**Branch(es):** 

- [ ] 3.3.5
- [x] master

**TC rev. hash/commit:**  
9f81cf4
**TDB version:**  
7.0.3
**Operating system:**  
TrinityCore rev. 9f81cf4 2016-12-25 19:13:24 +0100 (master branch) (Win64, Debug, Static)

Converted sniff data can be found here (used WPP) - https://www.dropbox.com/s/ahoaeegp1l83q0i/darki73_dalaran_horde_druid_order_hall.7z?dl=0

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
never upload sniffs to the bugtracker. post such stuff here https://community.trinitycore.org/forum/13-wdbadbsniffs/ pls
