### ISSUE TITLE
[Sniff][Legion] Warrior Order Hall Sniff Converted to SQL

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18624]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

This is SQL files for Warrior Order Hall from Live server. Clicked and interacted will all possible NPCs and objects there. There are 2 files, 1 for hotfixes table and 1 for world table. 

**Current behaviour:** (Tell us what happens.)

Warrior order hall is not populated at all

**Expected behaviour:** (Tell us what should happen instead.)

Well, it should be populated

**Steps to reproduce the problem:**

1. Clean installation
2. Start the core
**Branch(es):** 

- [ ] 3.3.5
- [x] master

**TC rev. hash/commit:**  
9f81cf4
**TDB version:**  
7.0.3
**Operating system:**  
TrinityCore rev. 9f81cf4 2016-12-25 19:13:24 +0100 (master branch) (Win64, Debug, Static)

Converted sniff data can be found here (used WPP) - https://www.dropbox.com/s/kvh0ue8c735q6cs/23222_2016-12-27_darki73_warrior_order_hall.7z?dl=0

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
better upload the sniff of it in https://community.trinitycore.org/forum/13-wdbadbsniffs/ and close this issue. thank you. a developer will push the sql changes in the future.

**Comment by Rushor** [comment]
also /close here? i mean everyone can push those converted sniff datas. we always need some love for thos spawns (sai, waypoints, adjusted flags and creature addons and so on)

we have a general issue for missing spawns here https://github.com/TrinityCore/TrinityCore/issues/13179

**Comment by darki73** [comment]
@Rushor ye, sorry for the uploading it here, i'm not really a friend of git so don't know how Fork exactly works, it always breaks on me. Also, i don't want to send my data to the provided links (since as it mentioned there, my data is in there), that is why i placed converted SQLs. 

I can take a look for missing spawns (the link you provided) for sure and run all the instances with sniffer attached, but the thing that bugs me is slow start up time (2.5 minutes on my machine. i7-6700K 16GB Ram SSD). Can you please tell me if there is different situation on Linux (startup times better) and if it is, i'll install VM and provide all the necessary data for the missing spawns

**Comment by RazputinSNET** [comment]
Where can you download sniff de legion?
