### ISSUE TITLE
[Quest] The Light of dawn

### ISSUE THREAD

**Issue by bumbummen99** [TrinityCore/TrinityCore#18626]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)
- The undead, at the start of the quest, just spawn instead of being risen (See video)
- There is no timer for the battle displayed
- Darion dies if you rush to the chapel, you have to stick to him. #933 #17671
- The script for the battle seems to stop always after Tirion screams "Bring them to the chapel" ([Screenshot](http://imgur.com/32nNCF7)) or after Darion jumps over to the Lich King. [Screenshot](http://imgur.com/rvbNpqu) #933
- Darion wont respawn after ~15min. Hes respawning after ~1 hour because he is a BOSS internally and so shares the respawn time. #933 #17671

**Expected behaviour:** (Tell us what should happen instead.)
- The undead should be risen. Just a minor problem.
- A timer should be displayed that shows the next event
- Darion should walk at normal speed and should not die in this phase of the event when the player is running away
- Darion is a boss but respawns every ~10mins on blizz. 

Here is a video how it should be : [YouTube](https://www.youtube.com/watch?v=fM8RKUeGkug)

**Steps to reproduce the problem:**

1. Create a deathknight and do the quest

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
- [X] 3.3.5
- [ ] master (Not tested)

**TC rev. hash/commit:**  
4bc5a5b

**TDB version:**  
current with updates to 4bc5a5b

**Operating system:**  
Tested on Win 10 and Win 2012

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18401

**Comment by irgc** [comment]
confirm
Last Quest is a problem area - buged
.it doesnt work.

 3.3.5 TDB 62 - last version
git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git

OS: Linux ubuntu 16.10
