### ISSUE TITLE
[master] Encounter system, Encounter start/end opcodes handling.

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#18630]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Encounter system not working. Nor starts nor ends, No "Boss defeated" message after any boss. Also boss fights should be grouped up in combatlogs as encounters.

**Current behaviour:** (Tell us what happens.) Nothing, even though there is instance_encounter table in the database.

**Expected behaviour:** (Tell us what should happen instead.) Encounter started and ended in combatlogs, opcodes handled, packets sended, "boss killed" message appeared.

**Steps to reproduce the problem:**

1. Kill any dungeon/raid boss.

**Branch(es):** master

**TC rev. hash/commit:**   8742732

**TDB version:** TDB 703.00 

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Krudor** [comment]
I think @Ovahlord is best suited to answer this question when looking at the "blame" history on the related files, I'll take a small look though.

**Comment by Krudor** [comment]
Opcode supports seems to have been added but InstanceScript::SendBossKillCredit isn't called from anywhere, I assumed this could be automated and doesn't have to be manually sent from every boss script.

**Comment by Eredar** [comment]
According to sniffs:

ServerToClient: SMSG_ENCOUNTER_END (0x27BB)
EncounterID: 1295
DifficultyID: 5
GroupSize: 10
Success: True
ServerToClient: SMSG_BOSS_KILL_CREDIT (0x27BC) 
EncounterID: 1295

It looks like success:true should call boss_kill_credit with the same id.

**Comment by Krudor** [comment]
Had a look and apparently we don't have a good way yet of linking bosses to encounters yet without manual 1 by 1 mapping.

**Comment by soulfrost** [comment]
@Krudor DungeonEncounterEntry -> container with CreatureDisplayID as key & search by boss NativeDisplayId

**Comment by Krudor** [comment]
Nope, that's not good enough

**Comment by soulfrost** [comment]
@Krudor why exactly

**Comment by Krudor** [comment]
1. A display id does not uniquely identify an encounter
2. Every dungeon encounter entry does not have a display id linked to them

**Comment by Aokromes** [comment]
#14216

**Comment by Ovahlord** [comment]
the encounter id's table needs an update and the system itself also needs some fixups since cataclysm.

**Comment by Shauren** [comment]
That might have been true in WoD but recently I haven't seen any encounters not sending it

**Comment by Ovahlord** [comment]
I also mean special cases such as the gunship battle or encounters that end by a scripted event instead of killing a creature.

**Comment by Krudor** [comment]
In that case, all we need is something to distinguish between same encounters on different difficulties, no?
An updated proper value of the difficulty id column in the DungeonEncounter file, that we can put in the instance_encounter table.

It looks like blizzard stopped using that column in the DungeonEncounter file, would have been nice to know what they replaced it with, since we would be implementing something they've since marked as deprecated.

Either way something needs to be added.

**Comment by Ovahlord** [comment]
The dungeonEncounter file still being used for instance locks. It should also be responsible to display which type of encounter has been done in the lock info window when sent properly via packet.

**Comment by Krudor** [comment]
Never said anything about the file stopped being used
