### ISSUE TITLE
[7.x]Artifact passive skills can not save. 

### ISSUE THREAD

**Issue by cbcs** [TrinityCore/TrinityCore#18644]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
use any artifact.update the artifact skill.
You can see the upgrade success tips, and get passive gain effect 
For example skills 211309 .
But you quit the game and log in. the Artifact passive not saved. 
**Current behaviour:** (Tell us what happens.)
Artifact passive skills can not save. 
**Expected behaviour:** (Tell us what should happen instead.)
Artifact passive skills can not save. 
**Steps to reproduce the problem:**

1. create a 110 level Warrior . use any artifact ,like 128908.
2. upgrad this artifact. you will get a passive 211309.
3. logout game and relogin.
4.look the artifact skill.  not save 211309..
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/5c1503f859763b18c0996ac546a07fad4d3964c2
**TDB version:**  
7.03
**Operating system:**  
win7 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by zamalaev** [comment]
@darki73 +1
