### ISSUE TITLE
[NPC] Darion Morgraine duplicate

### ISSUE THREAD

**Issue by bumbummen99** [TrinityCore/TrinityCore#18643]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
While the quest 13166, Darion Morgraine should not stand in his spot at lower acherus. He is Spawned there two times currently.

**Current behaviour:** (Tell us what happens.)
Darion Morgraine spawned two times [Screenshot](http://imgur.com/a/OyLUK)

**Expected behaviour:** (Tell us what should happen instead.)
Only one Darion should be visible

**Steps to reproduce the problem:**

1. Do quest 13166

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
- [X] 3.3.5
- [ ] master

**TC rev. hash/commit:**  
9f81cf4

**TDB version:**  
current with updates

**Operating system:**  
Win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
They are 2 different NPCS:

http://www.wowhead.com/npc=31084/highlord-darion-mograine
http://www.wowhead.com/npc=28444/highlord-darion-mograine

http://i.imgur.com/tZSe5bF.png

**Comment by Rushor** [comment]
i think this is just a phasemask issue, depending on the progress of the questline of the player

**Comment by Killyana** [comment]
One is in the phase 1 and the other in phase 384, you cannot see both npcs at the same time.
