### ISSUE TITLE
[Quest][Classic]  The Sleeper Has Awakened

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#18650]
http://wotlk.openwow.com/?quest=5321

On quest accept, a sound should be played.

Fix:

```sql
-- The Sleeper Has Awakened
UPDATE `creature_text` SET `sound`=6209 WHERE  `entry`=11218 AND `groupid`=0 AND `id`=0;
```

Btw: This was the last questfix so far. I will continue with creature_movement and creature_movement_template now.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/bddf15d6965d7deafed3f0da3efda6b8e41de9e0

**Operating system:**  
win 10

**Comment by illfated** [comment]
Because at the time, in 2016, when it was committed to the 3.3.5 branch, it was still valid for master.
Hence, the file was not named/tagged `_335.sql` and therefore, not filtered out from cherry-picking.
