### ISSUE TITLE
Core/Misc Trade window issue.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18652]
**Description:**  
Trade window issue.  

**Current behaviour: (Tell us what happens.)**  
Currently when you open a trade window and put an item to trade with the other player both players can not see the item that they are going to receive but the trade is sucessfull( when you trade an item for another item you can only see the item that you put from your inventory the item from the other player you cant see it, the other player also have the same problem too).  

**Expected behaviour: (Tell us what should happen instead.)**  
Both players should see the item that they are going to receive in the trade window.  

**Steps to reproduce the problem:**  

1-Open a trade window.  
2-Make the two players trade any item.  
3-Watch the bug.  

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master  

**TC rev. hash/commit:**  
5c1503f859763b18c0996ac546a07fad4d3964c2  

**TDB version:**  
7.0.3+updates  

**Operating system:**

**Comment by Krudor** [comment]
SMSG_TRADE_UPDATED outdated structure
