### ISSUE TITLE
[Quest][TBC] The Crystals - Link issue

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#18654]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Quests needed to do the "Bombing runs" should be immediately available as of Patch 3.2
([Source](http://www.wowhead.com/achievement=1282/fa-la-la-la-ogrila#comments:id=882936))

**Current behaviour:** You need to do all the chain involving killing the Gruul's sons.

**Expected behaviour:** Chu'a'lor should offer http://www.wowhead.com/quest=11025 without any prerequisite done

**Steps to reproduce the problem:**

1. .go creature id 23233 with a fresh character
2. Notice he doesn't offer this quest
3. ?
4. Profit!

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 584d347b70be521d7431dfe1694b80f2e95b957b

**TDB version:**  335.62

**Operating system:**  Not relevant

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
fix:

```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE  `ID`=11025;
```
