### ISSUE TITLE
[3.3.5] Missing GO for Quest The Fel and the Furious (10613)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18657]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Missing 3 GO's for Quest 10613
http://www.wowhead.com/object=185057/fel-reaver-control-console

http://www.wowhead.com/quest=10613/the-fel-and-the-furious
https://www.youtube.com/watch?v=OBKWxHQHd5M
![fel](https://cloud.githubusercontent.com/assets/10637389/21543702/1fc31858-cdc9-11e6-8a70-b4672387002c.jpg)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**
  TrinityCore rev. db426ed0f971 2016-12-28 11:09:34 -0300 (335 branch)

**TDB version:** 
 TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**
Win7 64  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
only as reference:

```sql
[13:30:01]2134308 (Entry: 185060) - [Fel Reaver Control Console X:-2671.000000 Y:2694.729980 Z:102.581001 MapId:530] 
[13:30:01]2134307 (Entry: 185061) - [Fel Reaver Control Console X:-2672.429932 Y:2691.780029 Z:102.398003 MapId:530] 
[13:30:01]2134309 (Entry: 185059) - [Fel Reaver Control Console X:-2668.989990 Y:2698.530029 Z:102.662003 MapId:530] 
```

**Comment by Tauriella** [comment]
I found this in Mangos UDB 

``` sql
93971, 185059, 530, 1, 1, -2668.44, 2698.08, 102.63, 2.61799, 0, 0, 0.965925, 0.258821, 25, 255, 1
93972, 185060, 530, 1, 1, -2670.49, 2694.05, 102.467, 2.60053, 0, 0, 0.96363, 0.267241, 25, 255, 1
93973, 185061, 530, 1, 1, -2672.7, 2690.24, 102.417, 2.56563, 0, 0, 0.958819, 0.284016, 25, 255, 1
```

**Comment by Rushor** [comment]
thx :)

**Comment by Tauriella** [comment]
Can any Devs please add the GO in the DB ?
Quest can not be finished otherwise

**Comment by Rushor** [comment]
fix:

```sql
SET @OGUID := XXXXXXXXXXXXXX; --3 unused set by TC TEAM
DELETE FROM `gameobject` WHERE `id` IN (185059, 185060, 185061);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES 
(@OGUID+0, 185059, 530, 3520, 3943, 1, 1, -2668.99, 2698.53, 102.662, 2.69388, 0, 0, 0.975048, 0.221992, 300, 0, 1, 0),
(@OGUID+1, 185060, 530, 3520, 3943, 1, 1, -2671, 2694.73, 102.581, 2.57921, 0, 0, 0.960726, 0.2775, 300, 0, 1, 0),
(@OGUID+2, 185061, 530, 3520, 3943, 1, 1, -2672.43, 2691.78, 102.398, 2.5635, 0, 0, 0.958516, 0.285037, 300, 0, 1, 0);
```
