### ISSUE TITLE
[3.3.5] The problem with Salvaged Siege Engine 

### ISSUE THREAD

**Issue by hlainin** [TrinityCore/TrinityCore#18660]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The problem in Ulduar, the Salvaged Siege Engine when the player sits  in the driver's seat, the second player trying to  sit  in the second place, he stucks in the car.

**Current behaviour:** the player stucks in the car and can't get out. To exit we need to break the machine

**Expected behaviour:** the second player must get on the shooter's seat

**Steps to reproduce the problem:**

1. the first player sits in Salvaged Siege Engine
2.  the second player trying to  sit  in the shooter's seat

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  [9f919beb](https://github.com/TrinityCore/TrinityCore/commit/9f919bebacd4b850e94d39ea7612b3cf97edd801)

**TDB version:**  335.62

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
It happens because player enter in wrong seat.
Btw is Dup #3831

**Comment by hlainin** [comment]
Keader 
the theme you gave me is different. There is considered a machine id 33109 and I'm talking about id 33060. Sorry if I don't understand something.

**Comment by Keader** [comment]
y, but is same issue :)
