### ISSUE TITLE
Not working items rough sharpening stone rough and sinker

### ISSUE THREAD

**Issue by mazdafil** [TrinityCore/TrinityCore#18666]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description: Not working items rough sharpening stone rough and sinker

**Current behaviour:** (Tell us what happens.) When using coarse or rough sharpening weights does not increase weapon damage

**Steps to reproduce the problem:**

1. При использовании грубого точила или грубого грузила не происходит увеличение урона оружия
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit: TrinityCore rev. 81f16b201b12

**TDB version: TDB 335.62

**Operating system:**  Ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Jildor** [comment]
Please, update your comments in english please

I think the problem is with all weapon enchants, poison...etc

**Comment by Aokromes** [comment]
also enchant/disenchant is broken.

**Comment by mazdafil** [comment]
When using coarse or rough sharpening weights does not increase weapon damage

**Comment by mazdafil** [comment]
There is no possibility to check which commit is causing the problem. But definitely on 57e592b everything works - no problem. Also when teaching Blacksmithing - apprentice the money, but the training is not happening.

**Comment by Spennerr** [comment]
I seem to have an issue with Rockbiter Weapon as well, don't know if this is all connected.

**Comment by shenhuyong** [comment]
Revert commit 584d347b70be521d7431dfe1694b80f2e95b957b can fix these problems.

**Comment by ariel-** [comment]
Always reverting. Not the proper solution

This is again a case of blizz non-sense with the NO_TARGET thing, I'm investigating the issue.

**Comment by Shauren** [comment]
I would revert that anyway, NO_TARGET is a tricky case which in 99% cases doesn't mean "no target"
