### ISSUE TITLE
[3.3.5] Binds Spell is broken (Hearthstone)

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18672]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Binds spell for the Innkeepers are broken

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**
  TrinityCore rev. c68f72c7612c 2016-12-30 09:12:15 +0100 (335 branch)

**TDB version:** 
 TDB_full_world_335.62_2016_10_17.sq + updates

**Operating system:**  
Win7 64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
I vote same has  https://github.com/TrinityCore/TrinityCore/issues/18666

**Comment by Spennerr** [comment]
SpellInfo.cpp

`    uint32 providedTargetMask = GetProvidedTargetMask() | mask;
    if (!providedTargetMask) // no targets to select
        return 0;`

it is the same revert the change made and it fixes those spell learning issues as well as Rockbiter weapon.

**Comment by Tauriella** [comment]
Thx for the fast Info :+1:
