### ISSUE TITLE
Core/Spells: wrong calculation of weapon dependent auras

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#18687]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** See Behaviour comparison

**Current behaviour:** At the moment, auras requiring specific weapon/equipment types are removed when the required equipment is not found, which is correct.

However what happens with dual-wield classes is that bonuses are applied to both weapons; the only requirement is that only one of them happens to be of the type required by the spell.

The other weapon is not taken into account AT ALL when calculating this bonus. Let's take for example Poleaxe specialization from a fury warrior. All a warrior needs to do to get full 5% crit on all his/her attacks is just equipping an axe in any of the hands (polearms can't be dual wielded with other weapon types, at least in 3.3.5); the other hand will passively receive 5% crit bonus too, even if it's not an axe!. Ranged attacks will also receive this bonus.

Commit 584abe107e2524ae30449b87b19e335e9aa1b196 did take a step in the right direction, by comparing item class when calculating Arpen auras, so now Mace specialization works properly

**Expected behaviour:** Weapon types should be taken into account for each attack type and aura with requirements. This should be done 'automagically', to avoid copy-pastes and forgetting to call the right function.

**Steps to reproduce the problem:**

1. Get a warrior, spec into Poleaxe spec and Titan's Grip
2. .learn 197
3. .learn 202
3. .additem yourself some 2H axe and sword of your choice and equip them
4. Put breakpoints [here](https://github.com/TrinityCore/TrinityCore/blob/90a330c910804f9cb770681ff646a2362c8c0efa/src/server/game/Entities/Unit/Unit.cpp#L2905) and [here](https://github.com/TrinityCore/TrinityCore/blob/90a330c910804f9cb770681ff646a2362c8c0efa/src/server/game/Entities/Unit/Unit.cpp#L2908)
5. Now go attack something and inspect the chance value after hitting each of the breakpoints
6. Notice crit % val is the same

**Branch(es):** 3.3.5. Almost sure master too

**TC rev. hash/commit:**  90a330c910804f9cb770681ff646a2362c8c0efa

**TDB version:**  335.62

**Operating system:**  Not relevant

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Another data to input: previous attribute known as SPELL_ATTR5_SPECIAL_ITEM_CLASS_CHECK, is only present in One-Handed Weapon Specialization talents.

Wording in those spells, quote:
> Description: Increases physical damage you deal when a one-handed melee weapon is equipped by $s1%.

Suggests this attribute may be suited to skip the exact same check that is missing, and reported.

**Comment by Eliminationzx** [comment]
Think[ this](https://github.com/TrinityCore/TrinityCore/blob/90a330c910804f9cb770681ff646a2362c8c0efa/src/server/game/Entities/Unit/Unit.cpp#L2942) line should be after [this](https://github.com/TrinityCore/TrinityCore/blob/90a330c910804f9cb770681ff646a2362c8c0efa/src/server/game/Entities/Unit/Unit.cpp#L2960).

**Comment by ariel-** [comment]
Not the point of this issue.

**Comment by xinef1** [comment]
How should the character info chart react if you have zero/one/two weapons that meet requirement? Assuming the talent modify crit change for example. And remember that sometimes bugs are just features :D any source except "misleading" talent description?
To fix this problem you would have to prevent applying the aura in Player::ApplyItemDependentAuras and apply it in specific hooks like ignore armor (gather all weapon dependent talents and see what exactly should be modified to work properly in all cases)

**Comment by ariel-** [comment]
> How should the character info chart react if you have zero/one/two weapons that meet requirement? 

I don't know. Currently bonus from those auras is shown in character sheet (maybe it shouldn't since it isn't fixed crit % for all attacks, just like +% hit talents don't show in the panel)

> any source except "misleading" talent description?

I checked theorycrafting spreadsheets. And it doesn't make too much sense for a talent increasing crit % chance and crit additional damage on polearms/2h axes applying to ranged weapons even D:

> To fix this problem you would have to prevent applying the aura in Player::ApplyItemDependentAuras and apply it in specific hooks like ignore armor (gather all weapon dependent talents and see what exactly should be modified to work properly in all cases)

Could be a solution, current AuraEffect handler simply adds (in apply case) or subtracts (in unapply case) the crit amount from the character's main hand, off hand and ranged crit chance.

**Comment by Shauren** [comment]
My implementation is based on legion spell data where the ONLY player spell ingame with equipped weapon requirements is Single-Minded Fury (fury warrior)
```
ID - 81099 Single-Minded Fury
=================================================
When you dual-wield one-handed weapons, all damage is increased by $s1%, and your off-hand weapon will deal an additional $s2% damage.
```

Another thing to keep in mind is that so far no attribute has ever changed its meaning - AttributesEx5 0x00010000 is present on various unrelated spells in legion data

**Comment by xinef1** [comment]
Blizzard tooltips are often very vague, I would start with finding some evidences that it really worked the way you described it.

**Comment by Shauren** [comment]
81099 Single-Minded Fury? Tested personally on retail

**Comment by xinef1** [comment]
Sorry, it was directed to ariel-, forgot about @
