### ISSUE TITLE
[3.3.5] Core/Spell: Molten armor, Ice armor, Frost armor don't proc in absorption

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#18680]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
[Molten armor](http://wotlk.openwow.com/spell=30482)

> Causes 75 Fire damage when hit, increases your critical strike rating by 35% of your Spirit, and reduces the chance you are critically hit by 5%. Only one type of Armor spell can be active on the Mage at any time. Lasts 30 min.

[Ice armor](http://wotlk.openwow.com/spell=7302)

> Increases Armor by 290 and Frost resistance by 6. If an enemy strikes the caster, they may have their movement slowed by 30% and the time between their attacks increased by 25% for 5 sec. Only one type of Armor spell can be active on the Mage at any time. Lasts 30 min.

[Frost armor](http://wotlk.openwow.com/spell=168)

> Increases Armor by 30. If an enemy strikes the caster, they may have their movement slowed by 30% and the time between their attacks increased by 25% for 5 sec. Only one type of Armor spell can be active on the Mage at any time. Lasts 30 min.

**Current behaviour:**
[Molten armor](http://wotlk.openwow.com/spell=30482) - Don't proc while takes melee damage in absorption.
[[Ice armor](http://wotlk.openwow.com/spell=7302) | [Frost armor](http://wotlk.openwow.com/spell=168)] - Don't proc while takes any melee hit in absorption.

**Expected behaviour:**
[Molten armor](http://wotlk.openwow.com/spell=30482) - Should proc by taking any melee damage in absorption.
[[Ice armor](http://wotlk.openwow.com/spell=7302) | [Frost armor](http://wotlk.openwow.com/spell=168)] - Should proc by taking any(including sap) melee hit in absorption.

**Steps to reproduce the problem:**

First situation:
1. Apply Ice or Frost armor.
2. Apply shield [Ice Barrier](http://wotlk.openwow.com/spell=11426) for example.
3. Take any melee hit.

Second situation:
1. Apply Molten armor.
2. Apply shield [Ice Barrier](http://wotlk.openwow.com/spell=11426) for example.
3. Take any melee damage.

**Branch(es):** 3.3.5
**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/db4ceca561ffe68a0fa3ef9581aad89e6f02686d

**TDB version:**  TDB 335.62

**Operating system:**  Linux debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
The issue has a misleading title; absorbs are not hits. (And yes, they proc properly when not absorbing)

Think about stealthed rogue with PW:S staying on top of an AoE, stealth wont't fade due to damage being absorbed.

Only seldom auras must proc on absorbs. Do you have any source indicating the mage armors should proc on absorb too?

**Comment by Eliminationzx** [comment]
I have only this vid https://youtu.be/CGl8B4dMxso?t=5m8s

**Comment by ariel-** [comment]
When the rogue opens on the mage I can't see he's ever affected by Ice Armor proc, rather he's rooted by the Water elemental

**Comment by Eliminationzx** [comment]
It's not root by water elemental(water elemental has cd on this spell), it's frostbite proc by frost armor.

**Comment by ariel-** [comment]
That icon is not Ice armor. Ice armor debuff looks exactly like ice armor. The icon you point looks like Frost Nova

**Comment by Eliminationzx** [comment]
I found better video:
https://youtu.be/8_UnZOzl2MY?t=7m3s
Here you can clearly see that behavior.

**Comment by ariel-** [comment]
Thank you. Very solid proof indeed

**Comment by Eliminationzx** [comment]
Still valid.
