### ISSUE TITLE
DB/GameObjects: Missing GameObject 246779

### ISSUE THREAD

**Issue by darki73** [TrinityCore/TrinityCore#18688]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
GameObject with ID 246779 is missing from the database. According to sniffs from live server, this is a Font of Power gameobject which is used in the Mythic+ dungeons.

(@OGUID+8, 245065, 1492, 0, 0, 3, '', 0, 7260.633, 7284.174, 25.8094, 0.4974239, 0, 0, 0.2461557, 0.9692303, 7200, 255, 1, 23222), -- Kvaldir Cage (Area: -Unknown-)
(@OGUID+9, 246779, 1492, 0, 0, 3, '', 0, 7189.398, 7318.07, 23.68542, 2.962996, 0, 0, 0.9960155, 0.08917986, 7200, 255, 1, 23222), -- -Unknown- (Area: -Unknown-)
(@OGUID+10, 252145, 1492, 0, 0, 3, '', 0, 7162.329, 7317.961, 20.86309, 0.2037807, 0, 0, 0.1017141, 0.9948137, 7200, 255, 1, 23222), -- Instance Portal (Area: -Unknown-)

From these 3 rows we can see that between the instance portal and first Kvaldir cage, there is an object, entry for which is missing from the database. With using **.go xyz** in game, you will spawn right on the place of Font of Power on the live server

**Current behaviour:** (Tell us what happens.)
Not in the database
**Expected behaviour:** (Tell us what should happen instead.)
Should be in database
**Steps to reproduce the problem:**

1. Fresh install
2. Run core

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

- [x] master

**TC rev. hash/commit:**  
ca306c6019909df5e8a736b5f29141d8499d58b3
**TDB version:**  
TDB 703
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Foldy** [comment]
```sql
DELETE FROM `gameobject_template` WHERE `entry`=246779;
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `Data32`, `RequiredLevel`, `VerifiedBuild`) VALUES
(246779, 49, 11554, 'Font of Power', '', '', '', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23222);
````

**Comment by darki73** [comment]
@Foldy Hey, thank you for your response. May i just know from where you got type 49 for game object? Which dbc/db2 file is it?

**Comment by Foldy** [comment]
I didn't grab that from a dbc/db2, thats exactly how WPP produced it in the sniff SQL

**Comment by darki73** [comment]
Wow that is strange. Doing MoS 5th time today with sniffer, still cant get the object creation string (using latest WPP)

**Comment by Foldy** [comment]
I've found that clearing your wow cache works.. i did that first time and it produced all the templates, just entered BRH without clearing the cache and it didn't produce any

**Comment by darki73** [comment]
@Foldy thanks a lot for your replies! I will try to clear my cache and to run instance again, i hope it will go well. One more thing, maybe you know, does addons somehow affect parse "quality"?
