### ISSUE TITLE
[3.3.5] Server Crash by Startup

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18698]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
WorlServer crashed by Startup 

AuctionHouseBot seems to be responsible

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
TrinityCore rev. a5f12ec15132 2016-12-31 20:51:17 +0100 (335 branch)

**TDB version:**  
TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  
Win7 64Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Vincent-Michael** [comment]
Where is debug crash log? ^^

**Comment by Tauriella** [comment]
http://www.heypasteit.com/clip/39T6
