### ISSUE TITLE
If you destroy your Hearthstone, you will not get one from the Innkeeper

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18706]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: AS title says, If you destroy your Hearthstone, you will not get one (new) from the Innkeeper.

Current behaviour: If you destroy your Hearthstone, you will not get one from the Innkeeper

Expected behaviour: You should get a new Hearthstone from the Innkeeper and it should be set to the correct location.

Steps to reproduce the problem: Delete your Hearthstone, try to talk to an Inkeeper and click "Make this inn your home."

1. http://imgur.com/a/T2gvJ
2. http://imgur.com/a/T2gvJ
3. http://imgur.com/a/T2gvJ

Branch(es): 3.3.5

TC rev. hash/commit: rev db4ceca561ff

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Wrong core revision hash (master) - and I doubt that your result is from straight TrinityCore 3,3,5 source.

**Comment by starrheld** [comment]
Yes, updated now to correct Revision.
db4ceca561ff

Nothing is modified, this is source

**Comment by Shauren** [comment]
You are on a broken version, this has already been fixed
