### ISSUE TITLE
[Quest] The Emerald Dreamcatcher (2438) is marked as Weekly

### ISSUE THREAD

**Issue by TheGuyDanish** [TrinityCore/TrinityCore#18700]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The quest The Emerald Dreamcatcher in Dolanaar is marked as a weekly repeatable quest, when it should only be taken once.

**Current behaviour:** (Tell us what happens.)
The quest is marked weekly repeatable.

**Expected behaviour:** (Tell us what should happen instead.)
The quest should be marked as all others in the starting area.

**Steps to reproduce the problem:**

1. Compile a TrinityCore master branch server
2. Get a character to about level 5 so they can get the quest.
3. Accept the quest and check the quest log.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master

**TC rev. hash/commit:** 
rev. ca306c601990

**TDB version:**  
703.00 2016 10 17

**Operating system:**
Ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by TheGuyDanish** [comment]
fix:
`UPDATE quest_template SET flags = '8' WHERE id = 2438;`

**Comment by Aokromes** [comment]
http://www.wowhead.com/quest=2438/the-emerald-dreamcatcher

**Comment by TheGuyDanish** [comment]
Apologies. I was confident that I'd never seen it as a quest that could be picked up twice.
