### ISSUE TITLE
Master: Quest Runaway Shredder

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#18711]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**  During the course of quest 14129, Runaway Shredder should be a mount after breaking it down to low life. Because of that, Quest 14134 cannot be completed.

**Current behaviour:** Runaway Shredder dies instead of becoming a valid mount to collect wood piles.

**Expected behaviour:** Runaway Shredder should become a valid mount.

**Steps to reproduce the problem:**

1. Go to Azshara, accept the quest from Labor Captain Grabit
2. Break down a Runaway Shredder
3. Observer death.
4. Happy New Year!

**Branch(es):** Master

**TC rev. hash/commit:**  8b2e071

**TDB version:**  7.01

**Operating system:** Windows 10  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
we have the mainissue here: https://github.com/TrinityCore/TrinityCore/issues/15182

If a zone is not even touched by a db-dev, it's unneeded to report the questbug (my opinion)

**Comment by BahDumbBugs** [comment]
Copy. Thanks. I did a search for it or any reference to 'Runaway Shredder' and didn't come up with anything. Hence my  logic for reporting it.

**Comment by BahDumbBugs** [comment]
Just an observation - Wouldn't it make any sense to figure out which quests in each zone are working as intended, to take some of the work off the folks doing the scripting?

**Comment by Rushor** [comment]
yeah that would be nice - each zone a checklist for the stuff that works and don't work (wowwiki should have a list for each zone)

you could post that list in the forum then :)

**Comment by BahDumbBugs** [comment]
I already made a list of each zone and their respective quests (Horde only at this time) on an Excel Spreadsheet. I'll start a list. Where in the forum would you like it posted?
