### ISSUE TITLE
[7x]worldserver crash on WorldSession::Update

### ISSUE THREAD

**Issue by cbcs** [TrinityCore/TrinityCore#18714]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)
if (ShouldLogOut(currTime) && m_playerLoading.IsEmpty())
    LogoutPlayer(true);
Crash..

**Description:**
I do not know what happened.
**Current behaviour:** (Tell us what happens.)
look the crash log.
**Expected behaviour:** (Tell us what should happen instead.)
look the crash log.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/5c1503f859763b18c0996ac546a07fad4d3964c2
**TDB version:**  
7.03
**Operating system:**  
win7 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by cbcs** [comment]
[227e32f7557b+_worldserver.exe_[2-1_13-9-54].txt](https://github.com/TrinityCore/TrinityCore/files/680406/227e32f7557b._worldserver.exe_.2-1_13-9-54.txt)

**Comment by cbcs** [comment]
there is crash log and dmp
https://mega.nz/#!M5U3kDaK!hCDqHe9oezfxx4KmmZYuFUyN5M8P5kzCTFTGiaNIceg

**Comment by Aokromes** [comment]
No new crashes after over a year, if this bug is still valid, plz open a new ticket with updated core.
