### ISSUE TITLE
[3.3.5] Build Fix

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#18718]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Forgot add Headers in boss_illidari_council.cpp
Error: https://gist.github.com/Jildor/20e0383889e266daf5c27f38421c2530

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/be15beebdc0a9ec67943bd17930b868442d0ec1b

**TDB version:**  TDB335.62

**Operating system:**  Debian

**Fix:**
src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
```diff
#include "ScriptMgr.h"
#include "ScriptedCreature.h"
#include "SpellScript.h"
#include "SpellAuraEffects.h"
#include "black_temple.h"
+#include "Cell.h"
+#include "CellImpl.h"
#include "GridNotifiers.h"
#include "PassiveAI.h"
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
for c++ fixes plz open one pull request.

**Comment by Jildor** [comment]
oks, I did not know if it was necessary for this ;)

**Comment by Jildor** [comment]
Done ;)
