### ISSUE TITLE
Wrong PCT_MOD calculation

### ISSUE THREAD

**Issue by Shauren** [TrinityCore/TrinityCore#18726]
**Description:**
PCT spellmods are calculated additively (weird, right?)

**Current behaviour:** (Tell us what happens.)
PCT spellmods are calculated additively

**Expected behaviour:** (Tell us what should happen instead.)
PCT spellmods are multiplied with each other

**Steps to reproduce the problem:**
1. Apply aura http://www.wowhead.com/spell=198228/hammer-of-storms
2. Apply aura http://www.wowhead.com/spell=198361/raging-storms (modifies aura from point 3)
3. Apply aura http://www.wowhead.com/spell=201846/stormbringer
4. See tooltip value being lower than expected

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master

**TC rev. hash/commit:**  
a6d29d4058f2a4a63915aa41a6bf20c654d0511d

**Additional proof**
Retail sniff
1. Login with only http://www.wowhead.com/spell=198228/hammer-of-storms
```
ServerToClient: SMSG_SET_PCT_SPELL_MODIFIER (0x2C38) Length: 14 ConnIdx: 1 Time: 01/03/2017 17:25:13.612 Number: 2201
Modifier type count: 1
[0] Spell Mod: Damage (0)
[0] Count: 1
[0] [0] Amount: 1.08
[0] [0] Spell Mask bitpos: 76
```

2. Attack target dummy until http://www.wowhead.com/spell=201846/stormbringer procs
```
ServerToClient: SMSG_SET_PCT_SPELL_MODIFIER (0x2C38) Length: 44 ConnIdx: 1 Time: 01/03/2017 17:27:30.190 Number: 10156
Modifier type count: 3
[0] Spell Mod: Damage (0)
[0] Count: 1
[0] [0] Amount: 1.35
[0] [0] Spell Mask bitpos: 76
```

8% spellmod increase combined with 25% spellmod increase result in 35% total damage increase (1.08 * 1.25 = 1.35)

https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Player/Player.h#L2890
Current TC result is 1.08 + 1.25 = 1.33

**Comment by joschiwald** [comment]
while you are on it: calculation of flat and pct must be splitted
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Player/Player.h#L2883
there are mods mit basevalue 0 which are affected by flat and pct

**Comment by Shauren** [comment]
Example?

**Comment by joschiwald** [comment]
see above

**Comment by Shauren** [comment]
Ok, easy then

**Comment by streetrat** [comment]
void Player::SendSpellModifiers() const
has an error too
           

        for (uint8 j = 0; j < 128; ++j)
        {
            flag128 mask;
            mask[j / 32] = 1u << (j % 32);

            flatMod.ModifierData[j].ClassIndex = j;
            flatMod.ModifierData[j].ModifierValue = 0.0f;
            pctMod.ModifierData[j].ClassIndex = j;
            pctMod.ModifierData[j].ModifierValue = 1.0f; // should be 0

            for (SpellModifier* mod : m_spellMods[i])
            {
                if (mod->mask & mask)
                {
                    if (mod->type == SPELLMOD_FLAT)
                        flatMod.ModifierData[j].ModifierValue += mod->value;
                    else
                        pctMod.ModifierData[j].ModifierValue += mod->value;
                }
            }
            // if m_spellMods[i] is empty or doesnt have a pct mod then below line will be
            //                                                               1     + ( 1           *        0.01)   =  1.01  instead of 1
            pctMod.ModifierData[j].ModifierValue = 1.0f + (pctMod.ModifierData[j].ModifierValue * 0.01f);
        }

**Comment by Shauren** [comment]
Yes, I am aware of that
