### ISSUE TITLE
[Bug][Quest]Rescue OOX-17/TN

### ISSUE THREAD

**Issue by xStarfall** [TrinityCore/TrinityCore#18724]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The escort quest Rescue OOX-17/TN is bugged and I am not really sure when it crashed, because I completely remember this working back in the days. After accepting the escort quest he drives like crazy with speed up in the air.
**Current behaviour:** (Tell us what happens.)
He speeds up like crazy in the air.
**Expected behaviour:** (Tell us what should happen instead.)
He should respect a path like any escort quest.

**Steps to reproduce the problem:**

1. Complete [Find OOX-17/TN](http://wotlk.openwow.com/quest=351)
2. Accept [Rescue OOX-17/TN](http://wotlk.openwow.com/quest=648)
3. He will start to move with a crazy speed up in the air.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
b15ae6b560510f41bc6a6db1732d530a8448d59b
**TDB version:**  
TDB 335.61
**Operating system:**  
CentOS 6.8

**Details**
I am not using any custom adds to the core/DB, this has been re-tested on a completely clean build with the hash and TDB version provided up in the report. I have also noticed some other issues with escorts around the world, where they just STOP mid-way and do nothing more, they just can't continue. 

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
duplicate https://github.com/TrinityCore/TrinityCore/issues/18401

**Comment by xStarfall** [comment]
Ah, got it, really sorry for not searching more about this issue, so it's a general one as I've suspected. Thanks a lot @Rushor ! Have a great day!
