### ISSUE TITLE
[Core] Problems with Groups. 

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18744]
Description:
Problem when you leave the group or converting in Raids.

Current behaviour: (Tell us what happens.)
When you are in group and you select the option to leave the group or convert in Raid nothing is happen, you remain in the group until you log out and log in.

Expected behaviour: (Tell us what should happen instead.)
When you are in group and you select the option to leave the group or convert in Raid you have to leave the group/Raid without log out and log in.

Steps to reproduce the problem:

    Create a group.
    Select the option to leave the group.
    Convert group y Raid.

Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master
TC rev. hash/commit:
176efd27
TDB version:
7.0.3+updates
Operating system:

**Comment by lorac2k14** [comment]
possible opcode change?  does console throw message?
