### ISSUE TITLE
[master] creature_template difficulty_entry cleanup

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18740]
**Description:** creature_template difficulty_entry cleanup

**Current behaviour:** (Tell us what happens.)
Currently adding NPC for different dungeon difficulties requires adding separate NPC IDs (which shouldn't be there since it's the same NPC with different stats) because of difficulty_entry.

**Expected behaviour:** (Tell us what should happen instead.)
For a more cleaner db the creature_template should have a difficulty_type with different IDs for different difficulties or just 1 for normal with 2 if it has different. And a different table to contain the stats for the different difficulties.

This way it will avoid having multiple IDs of the same NPC and db errors regarding missing NPCs.

**Steps to reproduce the problem:**
Check DB with creature_template table.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master

**TC rev. hash/commit:**  TrinityCore rev. fc22e97369b0

**TDB version:**  TDB 703.00

**Operating system:**  Win10 x64

**Comment by adryan66** [comment]
There's no issue that it doesn't work , just cleanup so that it's cleaner without using separate id's for the same npc , it has most of the template stats the same , difference being between dificultys the hp / dmg and a few more.
Having a diferent table will free the nondiferent ids (maybe in future some new npc will be overwritten with same id).
Cleanup mostly regarding db. It will make finding different id's faster, comparing things between then also faster since the new dificulty table will be a lot smaller.

**Comment by DDuarte** [comment]
Are you aware that those difficulty entry ids are not arbitrary? The source of them is Blizz.

**Comment by adryan66** [comment]
Well I checked a few random and couldn't find anything to point me to that specific id. Guess it was from sniffs only since I couldn't find nowhere else ?
I might be wrong tho, not that experienced with TrinityCore, at least not yet.

**Comment by Killyana** [comment]
difficulty entries are WB in 3.3.5 and cata, and in master moved to DBC
