### ISSUE TITLE
The Last Line of Defense

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18746]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: Broken quest

Current behaviour: You are able to move AS the cannon, and the quest is broken to a point that it is ridiculous. The Frostbrood Destroyer's evade all the time when you attack them.

Expected behaviour: You should not be able to move the cannon, you have to in fact restart the server to get the cannon to the correct position.

Steps to reproduce the problem: Take quest The Last Line of Defense - .quest add 13086

1. Hop on one of the cannon(s), log out, log in back again...
2. Now try to hop on one of the cannon(s) again.
3. You can now move as the cannon...

You can actually complete the quest, but it will take some effort and time. This needs a fix, also the Spiders running around are running in the air and up side down.

And I believe when Reckoning Bomb is ready this text should appear on your screen:
- "Reckoning Bomb READY! Purge the evil from this land!"

http://imgur.com/a/qnqIh

Branch(es): 3.3.5

TC rev. hash/commit: de4eee3abbc3b5f59bb22fbc54c313a11f23d06b

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#16163

**Comment by Aokromes** [comment]
also, why the fuck you open a new ticket if you see another is already opened.

**Comment by starrheld** [comment]
@Aokromes Why use unnecessary profanity?

**Comment by tkrokli** [comment]
@starrheld : creating a new issue with the same content from an existing issue is counterproductive and indicates that you have ignored the rules for opening a new issue. To a system maintainer, this appears as wilful ignorance of the guidelines (from the poster's side) as well as unnecessary noise (maintenance work).

**Comment by citizenwow** [comment]
i have this problem too, they evade all the time when you attack them.
TrinityCore rev. c79571a 2019-11-03 17:00:24 +0100

**Comment by illfated** [comment]
@citizenwow : could you put that same comment in the open issue ticket #16163 (**[3.3.5][6.x] DB/Quest: The Last Line of Defense**) ?
I am fairly sure it will be more useful in the open issue ticket than here, in this closed issue.
