### ISSUE TITLE
Conditions not working for spell_loot_template

### ISSUE THREAD

**Issue by Gerhood** [TrinityCore/TrinityCore#18750]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Loot from spell_loot_template seems to be unaffected by conditions (CONDITION_SOURCE_TYPE_SPELL_LOOT_TEMPLATE, *_REFERENCE_LOOT_TEMPLATE)

**Steps to reproduce the problem:**

1. Item 33345 drops from reference entry 44002. There is a condition that prevents it from showing if quest 11258 has not been taken.
2. Add reference to spell_loot for testing:
`DELETE FROM spell_loot_template WHERE entry = 60445;`
`INSERT INTO spell_loot_template VALUES (60445, 0, 44002, 100, 0, 1, 0, 1, 1, NULL);`
3. See how .cast 60445 will give you the item regardless of your quest status

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  
85c68d634663028f2b60748eca469838d431f74b

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by CraftedRO** [comment]
835e2918319e Maybe I'm wrong but if I understand correctly this works now, I tested on [Champion of Sseratus](https://www.wowhead.com/wotlk/npc=28036/champion-of-sseratus) with [Strange Mojo](https://www.wowhead.com/wotlk/item=38321/strange-mojo) item that start a quest, and after you complete it, you can't loot it anymore.


https://user-images.githubusercontent.com/24683355/213877083-72732f62-a08e-4151-9f10-fdcb302da29d.mp4

**Comment by CraftedRO** [comment]
835e2918319e Issue is invalid because 33345 / 33314 does drop only if you had completed required quests 11256 H and 11248 A not 11258 as stated in above issue.
https://www.wowhead.com/wotlk/item=33345/vrykul-scroll-of-ascension#comments:id=963273

![sqsq](https://user-images.githubusercontent.com/24683355/213878719-d4875af5-e94c-4741-b6f3-5dd58311478b.PNG)
