### ISSUE TITLE
[Gameobject] A dusty tome

### ISSUE THREAD

**Issue by bumbummen99** [TrinityCore/TrinityCore#18753]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
There should spawn a lootable gameobject in Dire-Maul dungeon called [a dusty tome](http://wowhead.com/object=179547)
 

**Current behaviour:** (Tell us what happens.)
It does not spawn anywhere.

**Expected behaviour:** (Tell us what should happen instead.)
It should spawn at the given locations. look at the reference

**Steps to reproduce the problem:**
 -

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
- [X] 3.3.5
- [ ] master (Not tested)

**TC rev. hash/commit:**  
f7f865f
**TDB version:**  
latest with updates

**Operating system:**  
win

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
35833	179547	429	2557	2557	1	1	157,708	602,89	-26,7316	3,21621	0	0	0,999304	-0,0373	7200	0	1	0
