### ISSUE TITLE
[master] Core/Group error.

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18757]
**Description:** Problem when you are leader of group/raid and you try to leave the group.

**Current behaviour: (Tell us what happens.)**
When you create a group/raid of 3 or more people when you try to leave the group/raid with the option of leave group, you are leaving the group but in the screen the group panel is not dismissing until you log out and log in

**Expected behaviour: (Tell us what should happen instead.)**
When you create a group/raid and you select the option of leave the group/raid you have to leave the group without log out and log in

**Steps to reproduce the problem:**

1. Create a group of 3 people or more
2. Try to leave the group
3. log out and log in

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)** 
master

**TC rev. hash/commit:** a82488a0

**TDB version:** 7.0.3+updates

**Operating system:**

**Comment by Shauren** [comment]
29 Apr 2016? When the fix was yesterday? Are you kidding me?

**Comment by DJScias** [comment]
As of the current master, I'd actually like to note that this issue has not been fixed.

The following issues still exist:
1. Making a group/raid of 3 people and leaving it will now update the client-side frames. If the group /raid is composed out of 2 players it will work.
2. Making the group into a raid, once a player was kicked out and re-invited (thus has experienced broken frames at least once) does not seem to take place on their client. Making them unable to talk in raid, while the raid does exist for the other members.

A video showing these issues can be found here:
https://www.youtube.com/watch?v=U9U_-IoL5B0
(The random buildings you see are just me fucking around as it's a test server.. In case you're wondering why they're there.)

Kind regards,
DJScias
