### ISSUE TITLE
Mobs un-lootable if killed by pet

### ISSUE THREAD

**Issue by starrheld** [TrinityCore/TrinityCore#18758]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Description: If you let your pet kill mobs for you (low level mobs) the mobs won't be lootable.

Current behaviour: Can't loot mobs after pet kills it

Expected behaviour: The mobs should be lootable regardless?

Steps to reproduce the problem:

1.  Go to any low level zone as a Warlock.
2.  Dot the mob, with Defensive on.
3.  Your pet will kill the mob and you won't be able to loot the mob.

Branch(es): 3.3.5

TC rev. hash/commit: b1fa8ff028fbb7469ef93f5c5612869ec9ba37ae 

TDB version: 3.3.5.62

Operating system: Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
if you don't do damage to mob it's blizzlike.

**Comment by Nitair** [comment]
2. Dot the mob, with Defensive on. <- It should give loot.

**Comment by ariel-** [comment]
To get loot, the creature needs to have 50% damage done by players, if you let your pet do more than that, you won't get any loot.

**Comment by Shauren** [comment]
Not true at least starting from mop (cant remember earlier) - you only needed 1 damage

**Comment by Aokromes** [comment]
ariel- is right wotlk like.
