### ISSUE TITLE
[Critical Zone] The river betwen ''Durotar'' and ''Northern Barrens'' specificly at north, crashes the WoW Client. 

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18756]
Description:

The river betwen Durotar and Northern Barrens, specificly at north, currently presents critical issues.

Current behaviour: (Tell us what happens.)

When crossing the river betwen Durotar and Northern Barrens, specificly at north, the game's screen freezes badly, so the camera or the player's movement are unable to control.

Expected behaviour: (Tell us what should happen instead.)

When crossing the river betwen Durotar and Northern Barrens, specificly at north, it should not block the camera or movement's functions and the game screen should not freeze.

Steps to reproduce the problem:  

1. Create a character.  
2. Go to the river betwen Durotar and Northern Barrens, specificly at north.  

Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)  
Master  
TC rev. hash/commit:  
176efd27  
TDB version:  

7.0.3+updates  

Operating system:  

Window 10

**Comment by msoky** [comment]
I think it would be better if you post some screenshots of exact place too

**Comment by Aokromes** [comment]
better .gps of entry place, screenshots are useless to guess exact place.

**Comment by msoky** [comment]
or that, thx Aokromes

**Comment by Krudor** [comment]
Can't reproduce

**Comment by Rushor** [comment]
maybe client issue?

**Comment by Aokromes** [comment]
it can be broken client, bad emote, who knows.

**Comment by Edreisantafe** [comment]
I use the same client on Blizzard, later i left some picture from place.

**Comment by Edreisantafe** [comment]
Sorry, i cant reproduce the problem again, maybe a PC issue, please close it.
