### ISSUE TITLE
[3.3.5] Quest/Sons of Hodir: "Going Bearback" - The bear goes through the mountains.

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18763]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
After riding on the bear begins a tour but goes through mountains (vmap) and should not. After a time the bear arrives at the place of origin and then can be manipulated to finish the mission.

**Current behaviour:** 
The bear goes through mountains (vmap).

**Expected behaviour:** 
The bear must go the right way.

**Steps to reproduce the problem:**
1. gm on
2. quest add 12851
3. go zonexy 53.128944, 65.502464, 67
4. right click on Icefang.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  f6dc66e

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by starrheld** [comment]
Well that was fun, can confirm...

**Comment by Rushor** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/18401 ? not shure since this one is scripted with sai
