### ISSUE TITLE
[3.3.5] Saviana Ragefire - Broken Movement

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#18773]
**Description:** In Air Phase, creature is not flying...

**Current behaviour:** When creature active air phase, she going from the river.

<details>

![wowscrnshot_010817_224000](https://cloud.githubusercontent.com/assets/7120913/21755936/ab26e2ea-d601-11e6-873d-928e2d7490e9.jpg)

</details>

**Expected behaviour:** Saviana should fly, in this position:

<details>

![saviana1](https://cloud.githubusercontent.com/assets/7120913/21755958/f66049a4-d601-11e6-892a-1713d8db6245.jpg)

</details>

**Steps to reproduce the problem:**

1. Start saviana fight in Ruby Sanctum
2. Wait 60 sec.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  b1fa8ff028fbb7469ef93f5c5612869ec9ba37ae

Maybe related with 28050f338dfc66e0c40b6a3915bf96e38e0613e5

**Comment by Rushor** [comment]
what's the inhabittype of her?

**Comment by tkrokli** [comment]
```sql
SELECT `entry`,`name`,`InhabitType` FROM `creature_template` WHERE `entry` = 39747;
```
```
entry  name              InhabitType
-----  ----------------  -----------
39747  Saviana Ragefire            3
```

**Comment by Keader** [comment]
it continues after revert 28050f338dfc66e0c40b6a3915bf96e38e0613e5

**Comment by Keader** [comment]
Change InhabitType for 7 works...but cause other issue, in ground part of saviana body enter in ground if she moves

**Comment by Keader** [comment]
Looks like MMaps issue now...

```diff

diff --git a/src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp b/src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp
index fd28bb5..3140ce6 100644
--- a/src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp
+++ b/src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp
@@ -183,7 +183,7 @@ class boss_saviana_ragefire : public CreatureScript
                             events.Repeat(Seconds(20), Seconds(30));
                             break;
                         case EVENT_AIR_MOVEMENT:
-                            me->GetMotionMaster()->MovePoint(POINT_FLIGHT, SavianaRagefireFlyOutPos);
+                            me->GetMotionMaster()->MovePoint(POINT_FLIGHT, SavianaRagefireFlyOutPos, false);
                             break;
                         case EVENT_LAND_GROUND:
                             me->GetMotionMaster()->MoveLand(POINT_LAND_GROUND, SavianaRagefireLandPos);
@@ -277,7 +277,7 @@ class spell_saviana_conflagration_throwback : public SpellScriptLoader
             {
                 PreventHitDefaultEffect(effIndex);
                 GetHitUnit()->CastSpell(GetCaster(), uint32(GetEffectValue()), true);
-                GetHitUnit()->GetMotionMaster()->MovePoint(POINT_LAND, SavianaRagefireFlyInPos);
+                GetHitUnit()->GetMotionMaster()->MovePoint(POINT_LAND, SavianaRagefireFlyInPos, false);
             }
 
             void Register() override
```

```sql

UPDATE `creature_template` SET `flags_extra`=`flags_extra`|512 WHERE `entry`IN(39747,39823);

```

with this patch (disabling pathfinding when she enter in air phase), she can fly "normally".
Maybe related with #18364

**Comment by Killyana** [comment]
There's an issue with the inhabittype=7 https://github.com/TrinityCore/TrinityCore/issues/6148

**Comment by Keader** [comment]
She dont have innhabittype 7 in current db (https://github.com/TrinityCore/TrinityCore/issues/18773#issuecomment-273218572)
But yes, innhabitype is very weird...
If i change Saviana Innhabitype = 7, she fly normally, but she does fly animation in ground too >_<

**Comment by Killyana** [comment]
It's an old issue https://github.com/TrinityCore/TrinityCore/issues/15247

**Comment by tje3d** [comment]
Is this still valid issue? i can't reproduce it and everything works fine

**Comment by TheWinchesters** [comment]
This is the same problem that Sindragosa had which was fixed here 9ace4093d8cf67ba54912038f93fa42d3aa14b9c
Doing the same with the right CreatureID for Saviana solved the issue, at least for me.
<pre>DELETE FROM `creature_template_movement` WHERE `CreatureId` IN (39747, 39823);
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`) VALUES
(39747, 0, 0, 2, 0),
(39823, 0, 0, 2, 0);</pre>

**Comment by illfated** [comment]
@TheWinchesters : the SQL looks fine, just remember that MarkDown supports
Code and Syntax Highlighting: (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
so if you put **```sql** on top of your code block, it will highlight the SQL syntax. :-)

**Comment by TheWinchesters** [comment]
I need to save that link because I always forget how to do it!
Thank you @illfated
