### ISSUE TITLE
DB/Creature: Footman Rob, Footman Chuck and Footman George

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18770]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** This 3 npcs must have some kind of event
http://www.wowhead.com/npc=25258/footman-rob
http://www.wowhead.com/npc=25261/footman-chuck
http://www.wowhead.com/npc=25259/footman-george

**Current behaviour:** This 3 npcs are spawned but they do nothing

**Expected behaviour:** Three footmans in the tavern in Valiance Keep who appear to get some ale before getting to the front of battle.

    Footman Rob says: One last drink before we head to the front?
    Footman George says: Sure, why not?
    Footman Rob says: Barkeep! Bring out your strongest ale! We're off to the front.
    James Deacon says: You lads know the drill. No alcohol to servicemen on duty. You want the general to kill me himself?
    Footman Rob says: You'll surely make an exception for us, eh? We might not come back.
    James Deacon says: All right, all right... but you didn't get these from me!
    Footman Rob says: I guess that's it then. Off we go.
    Footman Chuck says: That was the worst beer I've ever had.
    Footman Mitch says: Hey, guys! Wait up! 

**Steps to reproduce the problem:**

1.  .go c id 25261

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:**   rev. fe999bcf78f2

**TDB version:** 3.3.5

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
maybe someone would like to sniff this? :>

**Comment by malcrom** [comment]
I will sniff it

**Comment by malcrom** [comment]
When sniffer is updated.

**Comment by Rushor** [comment]
is it an event with waypoints? else we could do it without the sniff
