### ISSUE TITLE
[3.3.5] Arena/DS: Flush Pipe

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#18776]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Spell: BG_DS_SPELL_FLUSH (57405)
Trigger Spell: 61698
When NPC waterSpout Cast the spell, nothing happens, I think the problem is the Range of the spell 61698

```sql
SELECT `RangeIndex` FROM `spell_dbc` WHERE `Id`=61698;
```
Result = 1 (Self Only)

**Current behaviour:** (Tell us what happens.)
When NPC waterSpout Cast the spell, nothing happens

**Expected behaviour:** (Tell us what should happen instead.)
When NPC waterSpout Cast the spell, players must knockback

**Steps to reproduce the problem:**

1. Enter Arena Dalaran Sewers
2. Wait to start the Arena

**Possible Fix:**
Change Spell Range (works, but I don't know if is a Hack ;S )
```sql
UPDATE `spell_dbc` SET `RangeIndex`=5 WHERE `Id`=61698;
```
**Branch(es):** 3.3.5

**TC rev. hash/commit:**  ebfa8d1648266a37152c95ee8558f90178e90939

**TDB version:**  TDB335.62

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Dalaran Arena and Ring of Valor are disabled by default, what is the reason? how can i enable it?

**Comment by Keader** [comment]
Bugs in everywhere in both arenas :)

**Comment by Noryad** [comment]
Thanks @Keader, could you be more specific?

**Comment by Keader** [comment]
If i remember right:

Dalaran Sewers has this issue and some bug in watter in the middle (i dont remember exactly what)

Ring of Valor: 
Elevators dont work (spawn in wrong place)
AOE spells like ShadowFury (Warlock) dont work in elevators.
Pets cant walk in elevators (sometimes they drop from map).
Warlocks can put portal and teleport from behind elevators.
Some AOE spells can hit other team, like Mass Dispel...

**Comment by Eliminationzx** [comment]
Looks like LOS issue...hmm
SQL fix is hack.

**Comment by Jildor** [comment]
@Eliminationzx
You can try with .cast 57405 or 61698, If you're not around of target, the spell does not work.

Does not seem to be LoS problem

**Comment by Eliminationzx** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp#L107 why it's commented?

@Jildor, try to uncomment it and test without DB changes.

**Comment by Keader** [comment]
Comment added in 1088c27562bbf60897129713b610e122fd018545
Maybe @joschiwald can tell us why it's commented  :)

**Comment by Keader** [comment]
> https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp#L107 why it's commented?

Some unfinished cleanup
Btw, is handled here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp#L82
