### ISSUE TITLE
[3.3.5] Functionality Raid Warning (/rw) not work

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#18787]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
Functionality Raid Warning (/rw) not work.

**Current behaviour:** (Tell us what happens.)
/rw not work

**Expected behaviour:** (Tell us what should happen instead.)
/rw shoul work 

**Steps to reproduce the problem:**
1. Invite a partner
2. Convert to raid
3. use /rw any_text

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  117d1c3

**TDB version:**  335.62

**Operating system:**  W8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by abines16** [comment]
This is confirmed.

**Comment by Keader** [comment]
Introduced in fc06465b17a57feafbf2c02316b1b910c2b98e89
