### ISSUE TITLE
Core/Groups: interface problems - again

### ISSUE THREAD

**Issue by Edreisantafe** [TrinityCore/TrinityCore#18789]
**Description:**  
Visual error in the client when you try to leave a group of more than 2 players.  

**Current behaviour:** (Tell us what happens.)  
When you create a group of more than 2 players and try to leave it, the game interface is not updating. It continues to show that you are still in the group, but you can read in the chat that you leave the group and you can even be invited to another group. When this happens and you are invited again to the old group, the group status does not update and doesn't show you when the group is converted to raid or converted to group again, and the chat doesn't show you the changes in the group. The raid tabs do not show any information. You have to log out and log in again to fix this problem.

**Expected behaviour:** (Tell us what should happen instead.)  
When you leave the group, the interface should update without having to log out and log in again.

**Steps to reproduce the problem:**  

1. Make a group of more than 2 players.  
2. A member has to leave the group.  
3. Invite the member again and covert the group to raid.  
4. Watch the raid tabs.  

**Branch(es):** master

**TC rev. hash/commit:**  9942b0b12e35e7477f76901fdc06d7f3d11f83cf  

**TDB version:**  703.00 + updates

**Operating system:**

**Comment by DJScias** [comment]
Posting video from the other issue I made:
https://www.youtube.com/watch?v=U9U_-IoL5B0
