### ISSUE TITLE
[Item][Classic] NPC Loot Issue Fixes (White Junk `item`s)

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#18781]
source: https://github.com/TBC-DB/Database

-- NPC Loot Issue Fixes (White Junk `item`s) - Drop Rates WAY Too High (Totally Screwed Very High Drop % For No Good Reason - Bad Query messed things up long time ago)

fix:

```sql
-- ====================
-- NPC Loot Issue Fixes (White Junk `item`s) - Drop Rates WAY Too High (Totally Screwed Very High Drop % For No Good Reason - Bad Query messed things up long time ago)
-- ====================
-- Warrior's Boots
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=2967 AND `entry` IN (3199,3244,3265);
-- Spellbinder Gloves
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=2972 AND `entry` IN (2190,11319);
-- Veteran Bracers
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=3213 AND `entry` IN (2069,3118,3269,4263,11323);
-- Spellbinder Cloak
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=4683 AND `entry` IN (3244);
-- Hunting Cloak
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=4689 AND `entry` IN (3265);
-- Disciple's Cloak
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=6514 AND `entry` IN (2957,3100,3123,3196,3244,3268);
-- Soldier's Cloak
UPDATE `creature_loot_template` SET `Chance`=0.03 WHERE `item`=6549 AND `entry` IN (2324,3632);
```

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
**3.3.5** 

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/fe999bcf78f201788fe3ca2556b73fd955444150

**Operating system:**  win 10

**Comment by offl** [comment]
This looks like the third fix :)
[Click](https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB46_to_TDB47_updates/world/2012_02_21_03_world_creature_loot_template.sql), #17578.

**Comment by Rushor** [comment]
5.7 % is still too high for the items i posted here
