### ISSUE TITLE
[3.3.5] Ulduar: Salvaged Chopper should not go through Leviathan gates

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#18788]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Like catapults,  Salvaged Chopper should not go through Leviathan gates because can define the batlle vs some boss.

**Current behaviour:** (Tell us what happens.)
Salvaged Chopper go through Leviathan gates.

**Expected behaviour:** (Tell us what should happen instead.)
Salvaged Chopper should not go through Leviathan gates.

**Steps to reproduce the problem:**
1. Kill Leviatan.
2. Use a Salvaged Chopper and go through Leviathan gates.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  117d1c3

**TDB version:**   335.62

**Operating system:**  W8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
I can not find a pattern, it occourred only once in several tries.

**Comment by Killyana** [comment]
I cannot reproduce after many attempts.
