### ISSUE TITLE
[3.3.5] Spell: Trinket PVP/Human Racial can not be used under incapacitation effects

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18798]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Trinket PVP/Every Man for Himself can not be used under the following incapacitation effects:
1. Sap-Rogue
2. Seduction-Succubus-Warlock
3. Cyclone-Druid
4. Repetance-Paladin

Maybe there are more spells with the same problem.

**Current behaviour:**
Trinket PVP can not be used under incapacitation effects.

**Expected behaviour:** 
Trinket PVP should remove incapacitation effects.

**Steps to reproduce the problem:**
1. Cast Cyclone/Sap/Seduction/Repetance to an human enemy.
2. Human use Trinket PVP or Every Man for Himself.
3. Message: Cant do that while banished/sapped/charmed/incapacited.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  151a067

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Dalgurakk** [comment]
hmmmm confirmed, big problem here.

**Comment by Mrgrasser** [comment]
yeh , confirm , again important problem :(
TC rev. hash/commit: 7d4ca0b6c4b99f9987228b5e548a2f80f208d2fb

**Comment by Eliminationzx** [comment]
Try this
```diff
diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index dff7a6a..5925a56 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -2955,7 +2955,7 @@ bool SpellInfo::SpellCancelsAuraEffect(SpellInfo const* auraSpellInfo, uint8 aur
                 break;
             case SPELL_AURA_SCHOOL_IMMUNITY:
             case SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL:
-                if (auraSpellInfo->HasAttribute(SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE) || !(auraSpellInfo->SchoolMask & miscValue))
+               if (auraSpellInfo->HasAttribute(SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE) || auraSpellInfo->HasAttribute(SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE) || !(auraSpellInfo->SchoolMask & miscValue))
```

**Comment by Eliminationzx** [comment]
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index eeb6dd6..0171d4d 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -5759,21 +5759,38 @@ SpellCastResult Spell::CheckCasterAuras(uint32* param1) const
     }
     */
 
-    if (unitflag & UNIT_FLAG_STUNNED)
+   if (unitflag & UNIT_FLAG_STUNNED)
     {
         // spell is usable while stunned, check if caster has allowed stun auras, another stun types must prevent cast spell
         if (usableWhileStunned)
         {
-            static uint32 const allowedStunMask =
-                1 << MECHANIC_STUN
-                | 1 << MECHANIC_SLEEP;
+            uint32 mask = (1 << MECHANIC_STUN) | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_HORROR);
+
+            // There some cases when spells can be used at every mechanics with SPELL_AURA_MOD_STUN
+            switch (m_spellInfo->Id)
+            {
+                case 22812: // Barkskin
+                    if (m_caster->HasAura(63248))
+                        mask |= 1 << MECHANIC_SAPPED | 1 << MECHANIC_HORROR | 1 << MECHANIC_SLEEP;
+
+                    break;
+
+                case 49039: // Lichborne
+                    mask |= 1 << MECHANIC_SLEEP;
+                    break;
+
+                default:
+                    break;
+            }
 
             bool foundNotStun = false;
             Unit::AuraEffectList const& stunAuras = m_caster->GetAuraEffectsByType(SPELL_AURA_MOD_STUN);
+
             for (AuraEffect const* stunEff : stunAuras)
             {
                 uint32 const stunMechanicMask = stunEff->GetSpellInfo()->GetAllEffectsMechanicMask();
-                if (stunMechanicMask && !(stunMechanicMask & allowedStunMask))
+
+                if (stunMechanicMask && !(stunMechanicMask & mask))
```

**Comment by Noryad** [comment]
@Eliminationzx please post when you finish, i can not follow you with so many post updates.

**Comment by Eliminationzx** [comment]
Sorry. I finished.

**Comment by Noryad** [comment]
With your patch the trinket pvp can be used again. it require to be checked by @ariel- because he wrote the last code about this.
Can you tell us about 
> p.s it also fix alot of issues about spells which usable if caster has different stun types.

?

**Comment by Eliminationzx** [comment]
@Noryad, it fix spells like - hand of freedom,  barkskin, lichborne, pain suppression(with glyph), PvP trinkets, human racial and etc,they are usable while different stun types (MECHANIC_STUN, MECHANIC_SAPPED, MECHANIC_FREEZE,MECHANIC_SLEEP,MECHANIC_CHARM, MECHANIC_HORROR,MECHANIC_BANISH).

**Comment by Dalgurakk** [comment]
@ariel- solve this please, pvp does not make sense with this problem :(
