### ISSUE TITLE
[3.3.5] Spell/Hunter: Entrapment not work

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18799]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Entrapment not prevent the move of the target.

**Current behaviour:** 
When the frost trap or snake trap is triggered, not paralyze the enemies in that area.

**Expected behaviour:** 
When the frost trap or snake trap is triggered, the enemys in that zone must be paralized.

**Steps to reproduce the problem:**

1. Hunter Casts frost trap or snake trap in any area with enemies.
2. The enemies receive some effects but never are paralized.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  151a067

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eliminationzx** [comment]
Fix
```SQL
UPDATE spell_proc SET SpellPhaseMask =0x1 WHERE SpellId=-19184;
```

**Comment by Noryad** [comment]
@Eliminationzx yor fix works :+1:

**Comment by Noryad** [comment]
@Eliminationzx your fix works :+1:
