### ISSUE TITLE
[master] items random bonuses

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#18800]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
cant add random bonus for http://wowhead.com/item=121261
add it by command and no bonus   (.additem 121261)
 
**Expected behaviour:** 
must add random bonuses

look here 
static bool HandleAddItemCommand(ChatHandler* handler, char const* args)

 Item* item = playerTarget->StoreNewItem(dest, itemId, true, Item::GenerateItemRandomPropertyId(itemId), GuidSet(), bonusListIDs);
 
Item::GenerateItemRandomPropertyId  <- this dont work
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/5b204ffe7bdfe2b50185861eb0f80f007e3429bb
 
**Operating system:**  
win 64x

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18423

**Comment by chilito** [comment]
@Aokromes    just try to add  item   .additem 121261
