### ISSUE TITLE
[3.3.5] Item Grime-Encrusted Object

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18807]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The Item Grime-Encrusted Object is on TC not Stackable on Blizz can you make a max 20 Items Stack
and on Blizz it is not a quest object but not sure if it so on TC

http://www.wowhead.com/item=9308/grime-encrusted-object

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
TrinityCore rev. 151a0670b44f 2017-01-11 16:26:56 +0100 (335 branch)

**TDB version:**  
TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  
Win7 64Bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Connot reproduce on rev. fe999bcf78f2

**Comment by Tauriella** [comment]
@Killyana yes you are right you can Stack this item as a GM :+1: 
But the Item itself don't drop as normal Loot, its droped only if you have accept the Quest then you can only one loot and not more.
If you have all Quests complet the Item don't drop anymore.

**Comment by Rushor** [comment]
so the item should always drop, regardless if the player has the quest or not.

if yes  - fix:

```sql
UPDATE `creature_loot_template` SET `QuestRequired`=0 WHERE `Item`=9308;
```

**Comment by Tauriella** [comment]
mom mo :1st_place_medal: 
I test it

**Comment by Rushor** [comment]
hm yes it's those kind of quests where you cannot accept the quest. it will not be added to you log. you need to complete them directly with the questitem. also the animation for http://www.wowhead.com/object=142487 on questreward is missing. i will open a new issue for this.

**Comment by Tauriella** [comment]
Fix works fine :+1:
