### ISSUE TITLE
[7.1.0] Character Spec Role Automatically Chosen.

### ISSUE THREAD

**Issue by sirmajor** [TrinityCore/TrinityCore#18805]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When creating character and get into game I choose a class role then when spawned in I spawn with a 'Spec' already chosen for me before I even get to lvl 10 or level requirements to change Roles, Therefore my initial pet summon spell for that Role doesn't work at all like It's there but won't work past the lvl requirment either.

This occured when making a Warlock class.

**Current behaviour:** (Tell us what happens.)
When skill/spell is added on creation, class spec chosen automatically at lvl 1.

**Expected behaviour:** (Tell us what should happen instead.)
Be able to level up till 5 and summon pet without being disabled.

**Steps to reproduce the problem:**
1. Create a Warlock class. Spec should be at (General)
2. Level up to 5.
3. Able to use Summon Pet.
4. Imp ready be used.

**Branch(es):** master (Tell us which branch(es) this issue affects.)
(master branch) (Win64, Release, Static)

**TC rev. hash/commit:**  
TrinityCore rev. 5e0191e0b7fb 2017-01-11 20:16:28 +0100

**TDB version:**  
7.0.3+updates

**Operating system:**  
Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Shauren** [comment]
Not a bug. Being specless is not a valid state since 7.0
