### ISSUE TITLE
[3.3.5] GunShip"OutOfRang"Goblin Rocket Pack

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18810]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** After use [Goblin Rocket Pack] To go Enemy ships working [Goblin Rocket Pack], but when back to the first ship[Goblin Rocket Pack] not work and warning OutOfRang , and every where in the enemy ship if use [Goblin Rocket Pack] warning OutOfRang .

Edit : Boss's in the Enemy ship modify hp 1 and Hong will move to target & if player want attack boss warining target is far !!!.
Someone that will help because what is the problem ?

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  a6acd88

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Mrgrasser** [comment]
Has anyone tested this problem?

**Comment by Mrgrasser** [comment]
close issue, my TC not clean for this problem

**Comment by SQLfix** [comment]
i have this problem https://github.com/TrinityCore/TrinityCore/commit/4843544c217800ba56b3084a8b1ca2fcf62cb091
