### ISSUE TITLE
[3.3.5] ability spells disappearing from cannon

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18812]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** If a player riding a cannon receives a Raid buff, all cannon spells for player disappear, 
for example "GunShip Cannons" or "Professor Putricide : Mutated Abomination" And ...

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**   a6acd88 

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
what?

**Comment by Mrgrasser** [comment]
if player Inside the cannon give buff, all spell's cannon disappear

**Comment by Kittnz** [comment]
Can you give us some id's so we can test this properly?

**Comment by Killyana** [comment]
Don't understand how players inside a cannon could cast their spells.

**Comment by Keader** [comment]
Easy Killyana, reporting stuffs without clean core.

**Comment by Aokromes** [comment]
I think he means if a player with one aura uses a cannon it removes spells from cannon.
