### ISSUE TITLE
[3.3.5] Elemental Devastation doesnt proc

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18819]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** http://wotlk.evowow.com/?spell=30160 does not proc

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) should proc on non-periodic offensive spell crits but nothing happends

**Steps to reproduce the problem:**

1. cast any non-periodic offensive spell and make it crit
2. no proc from  http://wotlk.evowow.com/?spell=30160
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**   https://github.com/TrinityCore/TrinityCore/commit/8a07fe7f8c653436c7d8baa8349f2bd79c92c427

**TDB version:**  61

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eliminationzx** [comment]
It works for me. Try to update your DB

**Comment by Persephone** [comment]
Really? I have tried :/ What entries do you have for it in spell_proc ?

**Comment by Eliminationzx** [comment]
+---------+------------+-----------------+------------------+------------------+------------------+-----------+---------------+----------------+---------+----------------+----------------+--------+----------+---------+
| SpellId | SchoolMask | SpellFamilyName | SpellFamilyMask0 | SpellFamilyMask1 | SpellFamilyMask2 | ProcFlags | SpellTypeMask | SpellPhaseMask | HitMask | AttributesMask | ProcsPerMinute | Chance | Cooldown | Charges |
+---------+------------+-----------------+------------------+------------------+------------------+-----------+---------------+----------------+---------+----------------+----------------+--------+----------+---------+
|  -30160 |          0 |               0 |                0 |                0 |                0 |         0 |             1 |              2 |       2 |              0 |              0 |      0 |        0 |       0 |
+---------+------------+-----------------+------------------+------------------+------------------+-----------+---------------+----------------+---------+----------------+----------------+--------+----------+---------+
1 row in set

**Comment by Persephone** [comment]
Damn, same as me :/

**Comment by Persephone** [comment]
odd

**Comment by Killyana** [comment]
Works for me too on rev. 3e51583e6cde

**Comment by Keader** [comment]
Cleanup your core/DB Persephone, if persist open a new issue.
