### ISSUE TITLE
[3.3.5] Polymorph can proc impact

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18817]
**Description:** Non-damaging spells such as polymorph can proc Impact http://wotlk.evowow.com/?spell=12358

**Current behaviour:** (Tell us what happens.) Casting polymorph on targets can cause Impact to proc

**Expected behaviour:** (Tell us what should happen instead.) Only damaging spells should proc impact

This is probably true with other non-damaging spells as well

**Steps to reproduce the problem:**

1. Spec impact
2. Cast polymorph
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8a07fe7f8c653436c7d8baa8349f2bd79c92c427

**TDB version:**  61

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eliminationzx** [comment]
UPDATE spell_proc SET SpellTypeMask=0x1 WHERE SpellId=-11103;

**Comment by Persephone** [comment]
[SQL]UPDATE spell_proc SET SpellTypeMask=0x1 WHERE SpellId=-11103;
Affected rows: 0
Time: 0.027s

already like that :/

**Comment by Eliminationzx** [comment]
updated

**Comment by Persephone** [comment]
Same, i just saw it doesnt have any row at all, im 100% sure i have all db updates. Do you have a row for it there? Only: http://wotlk.evowow.com/?spell=64343 has a row in spell_proc

**Comment by Persephone** [comment]
64343 didnt have spelltypemask to 1 ill try that and test

**Comment by Eliminationzx** [comment]
it should have spellPhaseMask = 0x2, my bad

**Comment by Persephone** [comment]
64343? So i shouldnt set typemask to 1?

**Comment by Eliminationzx** [comment]
@Persephone, yep

**Comment by Persephone** [comment]
As it already has phasemask to 2 @64343

**Comment by Eliminationzx** [comment]
Gimme one sec, I'll find true spell Id.

**Comment by Eliminationzx** [comment]
@Persephone, done

**Comment by Persephone** [comment]
@done in what way?

**Comment by Eliminationzx** [comment]
There was 2 wrong values - SpellId, SpellTypeMask.
SpellId should be `-11103` because we check proc condition of all spell ranks, `SpellTypeMask `should be `0x1` because spell proc from damage only.

**Comment by Persephone** [comment]
Sooo i should change entry 64343 to -11103?

**Comment by Persephone** [comment]
Thanks @Eliminationzx  Would you know how to fix http://wotlk.evowow.com/?spell=30160 as well? It simply doesnt proc at all no matter what i try

**Comment by Eliminationzx** [comment]
@Persephone, its my bad, in spell_proc no condition for impact. Check my first comment.

**Comment by Persephone** [comment]
@Eliminationzx  Thanks man much appreciated it works as intended now :)! Would you know how to fix elemental devastation as well? It doesnt proc at all

**Comment by Eliminationzx** [comment]
@Persephone, create a new issue.

**Comment by Persephone** [comment]
sure thing @Eliminationzx  https://github.com/TrinityCore/TrinityCore/issues/18819
