### ISSUE TITLE
[Quest/Borean Tundra] Master the Storm

### ISSUE THREAD

**Issue by GeCa7a** [TrinityCore/TrinityCore#1883]
Core 12340
3.3.5a WOTLK
[Master the Storm] http://www.wowhead.com/quest=11895 Missing npc. when you start quest the npc must appear in to the house in the back of quest giver. When I add it with .npc add it disappears after a crash or restart...

**Comment by GeneralSaurfang** [comment]
The buff associated with this quest ( http://www.wowhead.com/spell=46424/power-of-the-storm ) persists even after finishing the quest and leaving the area.

Nothing I tried seems to remove it. Not death not anything else.

**Comment by Rushor** [comment]
try to use spell_area

**Comment by Killyana** [comment]
The reward cast spell:46550 for the quest http://www.wowhead.com/quest=11896/weakness-to-lightning must be scripted to remove the aura 46424

**Comment by dr-j** [comment]
Could also use spell area for this quest/aura with autocast set to 0 if autocast is set to 0 player does not automatically obtain aura upon entering an area or taking a quest but then when the aura is present if player leaves the area defined in spell area or is not on quests req for spell area it is removed the autocast thing just tells it the aura is applied by other means but still conditions for removing aura.

**Comment by dr-j** [comment]
see https://github.com/TrinityCore/TrinityCore/commit/7c498a0cf960b43b6974d99f0cf265911c296711

**Comment by Killyana** [comment]
Ok I will add it.

**Comment by Killyana** [comment]
This can be pushed:
``` sql
DELETE FROM `spell_area` WHERE `spell` IN(46424);
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES 
(46424, 4119, 11896, 0, 0, 0, 2, 1, 10, 0),
(46424, 4035, 11896, 0, 0, 0, 2, 1, 10, 0),
(46424, 4146, 11896, 0, 0, 0, 2, 1, 10, 0),
(46424, 4116, 11896, 0, 0, 0, 2, 1, 10, 0),
(46424, 4117, 11896, 0, 0, 0, 2, 1, 10, 0),
(46424, 4037, 11896, 0, 0, 0, 2, 1, 10, 0);

DELETE FROM `spell_scripts` WHERE `id`=46550;
INSERT INTO `spell_scripts` (`id`, `effIndex`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
(46550, 0, 0, 14, 46424, 0, 0, 0, 0, 0, 0);
