### ISSUE TITLE
[master]Crash on intialize data stores

### ISSUE THREAD

**Issue by Skizooo** [TrinityCore/TrinityCore#18835]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Starting the worldserver and getting a crash on DB2Stores.cpp line 459 `ASSERT(BATTLE_PET_SPECIES_MAX_ID >= sBattlePetSpeciesStore.GetNumRows(),
        "BATTLE_PET_SPECIES_MAX_ID (%d) must be equal to or greater than %u", BATTLE_PET_SPECIES_MAX_ID, sBattlePetSpeciesStore.GetNumRows());`
**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

Below is the crash log:
[unknown_worldserver.exe_[14-1_17-23-21].txt](https://github.com/TrinityCore/TrinityCore/files/706047/unknown_worldserver.exe_.14-1_17-23-21.txt)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/8e2634b2b49eb814b8cc425a060b2f160dbb49b7
**TDB version:**  

**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Skizooo** [comment]
Setting `BATTLE_PET_SPECIES_MAX_ID` to 2023, fixed the crash,but i got another crash, ChrSpecialization. db2 , DungeonEncounter.db2 Extracted files might be from wrong client version(first one has 0 fields(expected 14), second one has 0 fields (expected 9) . I extracted the new dbc/gt/maps from the current Blizzard build, 7.1.5 23360, i think i should wait for new TC commits before extracting them.

**Comment by Vincent-Michael** [comment]
master is 7.1.0 not 7.1.5

update to 7.1.5 in sooon
