### ISSUE TITLE
[master] Druid On-Use Spell List

### ISSUE THREAD

**Issue by adryan66** [TrinityCore/TrinityCore#18840]
Most bugs that exist on druid regarding the way the spell works, excluding passives and multipliers.
If there's anything missing, feel free to add.

Druid - All Forms

- [ ] - Berserk - Color is a little darker
- [ ] - Dash - Doesn't change form to catform
- [ ] - Displacer Beast (talent) - Doesn't change to catform
- [ ] - Moonfire - Dot damage doesn't proc
- [ ] - Prowl - Doesn't change form to catform
- [ ] - Rebirth - Ressurection buff stays up after the revive
- [ ] - Travel Form - Doesn't change form
- [ ] - Wild Charge (talent) (moonkin) - Leaps forward not backward

Druid - Moonkin

- [ ] ## Blessing of Elune buff missing
- [ ] - Barkskin - Textures are being mixed
- [ ] - Blessing of the Ancients (talent) - Doesn't work at all
- [ ] - Force of Nature - Only 1 treant which doesn't do anything
- [ ] - Fury of Elune - Doesn't do anything
- [ ] - Innervate - Should work only on friendly target
- [ ] - Starfall - No damage at all
- [ ] - Stellar Flare - Doesn't do anything, not even cast
- [ ] - Sunfire - Dot damage doesn't proc
- [ ] - Warrior of Elune (talent) - Works only for 1 Charge not 2

Druid - Feral

- [ ] - Elune's Guidance - No buff after cast for the extra combopoints
- [ ] - Ferocious Bite - Doesn't consume combo points
- [ ] - Maim - Doesn't consume combo points
- [ ] - Rake - Always gives 2 combo points
- [ ] - Savage Roar (talent) - Doesn't do anything
- [ ] - Shred - Always gives 2 combo points
- [ ] - Skull Bash - Doesn't charge
- [ ] - Stampeding Roar - Doesn't change forms on use
- [ ] - Swipe - Doesn't do anything
- [ ] - Thrash - Doesn't do anything

Druid - Guardian

- [ ] - Barkskin - Textures are being mixed
- [ ] - Lunar Beam (talent) - Doesn't do anything
- [ ] - Mark of Ursol - Doesn't do anything
- [ ] - Pulverize - Doesn't do anything
- [ ] - Skull Bash - Doesn't charge
- [ ] - Swipe - Doesn't do anything
- [ ] - Thrash - Doesn't do anything

Druid - Restoration

- [ ] - Barkskin - Textures are being mixed
- [ ] - Cenarion Ward (talent) - Heals the creature attacking
- [ ] - Efflorescence - No healing or area assigned with model
- [ ] - Flourish - Doesn't do anything
- [ ] - Incarnation: Tree of Life - Doesn't end unless dispelled
- [ ] - Innervate - Should work only on friendly target
- [ ] - Lifebloom - No end healing
- [ ] - Omen of Clarity (passive) - Procs too often + Procs from other spells + Can cast more then 1 spell
- [ ] - Sunfire - Dot damage doesn't proc
- [ ] - Ursol's Vortex - Doesn't do anything

TrinityCore rev. 820c69ed8cc2

**Comment by Ulduar** [comment]
Cenarion Ward.
``` CPP
enum CenarionWard
{
  SPELL_DRUID_CENARIOUS_WARD_HEALING      = 102352,
}
// 102351 - Cenarion Ward
class spell_dru_cenarion_ward : public SpellScriptLoader
{
    public:
        spell_dru_cenarion_ward() : SpellScriptLoader("spell_dru_cenarion_ward") { }

        class spell_dru_cenarion_ward_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_dru_cenarion_ward_AuraScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_DRUID_CENARIOUS_WARD_HEALING))
                    return false;
                return true;
            }

            void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
            {
                PreventDefaultAction();
                int32 basePoints0 = CalculatePct(eventInfo.GetDamageInfo()->GetDamage(), aurEff->GetAmount());

                GetCaster()->CastCustomSpell(GetTarget(), SPELL_DRUID_CENARIOUS_WARD_HEALING, &basePoints0, &basePoints0, NULL, true);
            }

            void Register() override
            {
                OnEffectProc += AuraEffectProcFn(spell_dru_cenarion_ward_AuraScript::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_dru_cenarion_ward_AuraScript();
        }
};
```

**Comment by Aokromes** [comment]
make one ticket for each bug, search before make ticket.
