### ISSUE TITLE
Kael'thas (Tempest Keep: The Eye)

### ISSUE THREAD

**Issue by qaywsx** [TrinityCore/TrinityCore#1885]
In this encounter, when Kael'thas (http://www.wowhead.com/npc=19622) reaches 50% hp, he should perform a small scene in which he floats to the sky, some things flash, he becomes a bit bigger, and then he should go back to the ground to go on fighting as normal (with some extra attacks he gains).

The bug here is that he does gain the extra attacks, but when he goes to the sky, he stays there for the rest of the fight, he doesn't move and he doesn't go back down, he can't hit with physical attacks either, just a few spells when he can do it. Not only this voids some of the elements of the fight, but it also makes him impossible to loot because he dies in the air.
This is a very old bug though.

Taunting brings him back down and he functions normally, but each time he casts Gravity Lapse (http://www.wowhead.com/spell=35966), he goes back up and bugs again (yet if you taunt he goes down once more).

Here is a vid to show what I mean: http://www.youtube.com/watch?v=r4MzB8BDwyY&t=5m30s

Rev: https://github.com/TrinityCore/TrinityCore/commit/2a27ce8781abd21d49b3d5bd76a37aa6b52f9951
DB: TDB_335.11.40
##

**Comment by Aokromes** [comment]
Test #14874

**Comment by tkrokli** [comment]
The OP (@qaywsx) is very unlikely to reply now, looking at his user page https://github.com/qaywsx
If anybody else still gets this issue after testing #14874 , please post confirmation & some form of log.

**Comment by Nyeriah** [comment]
Fixed the issue where he wouldn't land, and the issue where he would wrongly move up the air during Gravity Lapses. Added a couple of things to the phase transition too, spawned the missing triggers and other stuff.

What's missing now is the "light show" that happens during the phase transition, lots of visual spells are cast by the triggers that are all around him.

**Comment by Aokromes** [comment]
@Nyeriah what do you need to close this ticket? i can sniff it :)

**Comment by SQLfix** [comment]
Kael'thas in 50% HP evaded !

https://github.com/TrinityCore/TrinityCore/commit/931a7623b24831adf679e0581735375077c8d252

**Comment by Killyana** [comment]
This issue was fixed long time ago.
