### ISSUE TITLE
[VMAPS/WORLDSERVER] Crash on worldserver

### ISSUE THREAD

**Issue by Skizooo** [TrinityCore/TrinityCore#18850]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I thought with the new update, this issue will be fixed, i am not sure if its only on my end,but i get a crash on worldserver because file 0000.vmtree from vmaps folder its missing, but its not. Check the pictures bellow:

![worldserver log](https://cloud.githubusercontent.com/assets/14895884/21965416/afde4e0a-db5f-11e6-946b-8c0ce89e5c32.png)
you can see the proof below that the file is in there:
![vmapsproof](https://cloud.githubusercontent.com/assets/14895884/21965423/d22b92ec-db5f-11e6-87cd-9459b5f65588.png)

i tried to extract the vmaps again, but i get an annoying crash from vmapsextractor:
![vmaps](https://cloud.githubusercontent.com/assets/14895884/21965433/f20c448a-db5f-11e6-90d6-f4b219beb194.png)
I tried to revert this commit https://github.com/TrinityCore/TrinityCore/commit/22396f1bcf97d3568faa95f17dcbf0984bce0312 because this is where @Aokromes changed to vmap 044 from 044, but no success.
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master 7.1.5
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/b483e49a56debfdc428f975a8d865320da67f6bb
**TDB version:**  

**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
it's user problem not tc problem, this don't belongs to tracker, instead to forum, update your extractors, run extractor again and delete old files and put new files.
