### ISSUE TITLE
Error message when loading outdated vmap files

### ISSUE THREAD

**Issue by devtekve** [TrinityCore/TrinityCore#18853]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** When loading maps obtained by older versions of the map extractors, an error message is received: 
`VMap file '%s' does not exist` 
and 
`Please place VMAP-files (*.vmtree and *.vmtile) in the vmap-directory (%s), or correct the DataDir setting in your worldserver.conf file.` 
But this error message is not descriptor of the real issue, because it is simply saying the map does not exist, causing confusion 

**Current behaviour:** A general error message is given if a vmap couldn't be loaded.

**Expected behaviour:** The error should NOT be general, instead should be a little more specifig error message

**Steps to reproduce the problem:**

1. Use older Vmap folder (extracted using older map extractor tool)
2. Run WorldServer and see te crash

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  ae3b74f2e2a8

**TDB version:**  irrelevant / unknown

**Operating system:**  Any

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18431

**Comment by devtekve** [comment]
@Aokromes The issue is different, it is not that I user Master tools, it is that the maps were outdated, but stills being an issue the fact that WorldServer Simply says it does not exist when it does, instead of saying that it couldn't read it.

https://community.trinitycore.org/topic/452-dbc-maps-mmaps-vmaps-problems/?do=findComment&comment=80884

(I already did the fix, I am about to do the PR, but needed to get an issue number)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18431#issuecomment-265967764

**Comment by Aokromes** [comment]
also. you don't  need one issue number to create a ticket.

**Comment by devtekve** [comment]
@Aokromes Alright, thank you, I am sorry, I am new on this and felt that needed to contribute. So you think that a little more descriptive message in case it couldn't load is not neccesary? (It happened to me and dragged me crazy thinking that it was a filesystem error, until checked the code)
