### ISSUE TITLE
[Crash] Warlock's spell "Demonic Empowerment"

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#18868]
**Description:**  

The warlock spell "Demonic Empowerment" learned on "Demonology" specialization has an issue. The console shows "\src\server\game\Spells\Spell.cpp:1191 in Spell::SelectImplicitAreaTargets ASSERTION FAILED:false && "Spell::SelectImplicitAreaTargets: received not implemented target reference type""  

**Current Behaivor:**  
Each time that the warlock use the spell named "Demonic Empowerment" this crash the server, this happen even if the warlock has a myrmidon(pet) sumoned or not.  

**Expected Behaivor:**  
When the warlock use the spell "Demonic Empowerment" the server should continue working whit any kind of problem.  

**Steps to reproduce the problem:**  
1. Create a "Warlock".  
2. Reach the level 12 with a "Warlock" and select the specialization "Demonology".  
3. Cast the spell "Demonic Empowerment".  

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**   Master

**TC rev. hash/commit:**  6f669043

**TDB version:**  7.0.3+updates

**Operating system:**

**Comment by tkrokli** [comment]
Please follow the rules in https://github.com/TrinityCore/TrinityCore/blob/master/CONTRIBUTING.md
- When reporting a crash, you MUST compile in debug mode because release dumps are useless (not enough information) - if you don't know how to compile in debug, read [this](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?#comment-47672)

**Comment by jackpoz** [comment]
It's more of a unhandled case than a crash. In production environment you probably want to delete https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp#L1192 line

**Comment by Edreisantafe** [comment]
102/5000
Thanks, I thought it was an incomplete or poorly implemented method, when I have the debug I leave it here.

**Comment by jackpoz** [comment]
It would make sense to change it to TC_LOG_ERROR() on master branch

**Comment by matukaa** [comment]
The effect should select all summons (not only permanent pets, but effectively all summons) and the caster. should have a name something like caster_and_summons. as @jackpoz mentioned, it's not a crash but rather an unimplemented target selector

**Comment by Edreisantafe** [comment]
So, no need the debug info?

**Comment by Aokromes** [comment]
#18558
