### ISSUE TITLE
[3.3.5] Crash pinfo::cs_misc

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18860]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Crash for command .pinfo

[ae3b74f_worldserver.exe_[16-1_13-59-15].txt](https://github.com/TrinityCore/TrinityCore/files/708162/ae3b74f_worldserver.exe_.16-1_13-59-15.txt)

**Branch(es):** 3.3.5  (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  ae3b74f

**TDB version:**  62

**Operating system:**  Windows Server 2012 R2

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
cannot reproduce on ae3b74f2e2a8

**Comment by Mrgrasser** [comment]
my TC update  ae3b74f , I mind crash is for this commit 117d1c31c99b00269fa73d50d1a5ccf7c49a8450

**Comment by Aokromes** [comment]
You have localized strings? if yes, revert texts to english or fix locales.

**Comment by Mrgrasser** [comment]
Oh sorry :D , for write bad English, I want just mean to say , From now on I will try 👍

**Comment by jackpoz** [comment]
If the crash is 100% reproducible then please build in Debug, reproduce the crash and post that crashlog

**Comment by Mrgrasser** [comment]
I back commit  117d1c3 , now don't have time again create Crash :|
