### ISSUE TITLE
[3.3.5] CRASH: Only occurs while loading a character specific

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#18875]
[439654d1e88d+_worldserver.exe_[17-1_12-17-56].txt](https://github.com/TrinityCore/TrinityCore/files/711861/439654d1e88d._worldserver.exe_.17-1_12-17-56.txt)

**Description:**
It worked fine until it crashed for some reason, since then this character causes the attached crash. Only occurs while loading a character specific, is not a commun problem.

**Current behaviour:** (Tell us what happens.)
Crash entering de world.

**Expected behaviour:** (Tell us what should happen instead.)
Should Crash entering de world..

**Steps to reproduce the problem:**
1. Porbably you can not reproduce, but tell me what can i do.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  439654d

**TDB version:**  335.62

**Operating system:**  W

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
Very detailed crashlog with the spell id of the aura being loaded (47440). It seems it's caused by Unit::GetReactionTo() calling Unit::GetCharmerOrOwnerOrSelf() on NULL.

**Comment by ariel-** [comment]
WEH crashlogs are so nice

**Comment by Shauren** [comment]
wow emu hacker crashlogs? u wot

**Comment by ariel-** [comment]
:)
