### ISSUE TITLE
[3.3.5] Zone Shadowmoon Valley NPC Dragonmaw Transporter

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#18872]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The Dragonmaw Transporter from Netherwing Ledge to Dragonmaw Fortress running in the Sky

http://www.wowhead.com/npc=23188/dragonmaw-transporter

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  TrinityCore rev. 1957c9c114f1 2017-01-15 08:55:11 +0100 (335 branch)

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql + updates

**Operating system:**  Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by el-druida** [comment]
that npc is missing or what?? you've to be more descriptive

**Comment by Tauriella** [comment]
Not missing, the NPC walking in the Air and don't fly.
![wowscrnshot_011817_062403](https://cloud.githubusercontent.com/assets/10637389/22051958/2bac7bcc-dd47-11e6-8893-f0e2975c799a.jpg)

**Comment by Tauriella** [comment]
I think we can close this Thread
Bug is fixed with TrinityCore rev. a3c6880579f3 2017-01-20 14:16:47 +0100 (335 branch)

Thank you very much
