### ISSUE TITLE
[3.3.5] Arcane Missiles continue after vanish

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18878]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** There seems to be a channelling issue with spells atm. 

**Current behaviour:** (Tell us what happens.) If a mage uses Arcane Missiles on a rogue, and the rogue uses "vanish" the missiles continue for the remaining of the duration and therefor breaks stealth.

Seen here: http://puu.sh/tqs3C/13382b2201.jpg

**Expected behaviour:** (Tell us what should happen instead.) The missiles should be interrupted when the rogue vanishes.

**Steps to reproduce the problem:**

1.  Cast missiles
2.  Cast vanish
3. Notice missiles continue, and breaks stealth.

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/439654d1e88dfc20ed437ac66e3b5a80833da773

**TDB version:**  62

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Persephone** [comment]
Update: Drain Life also continues to hit the rogue after he vanishes, they do not lose target. This must be a generic error in the channeling code, that doesnt check on update if the target is still there

adding this in HandlePeriodicTriggerSpellAuraTick did make the mage "stop" casting but its hacky :333

// arcane missiles (hackfix)
			case 5143:
			case 5144:
			{
				WorldObject* target = ObjectAccessor::GetUnit(*caster, caster->GetChannelObjectGuid());
				if (target && target->ToUnit() && target->ToUnit()->HasStealthAura())
				{
					caster->CastStop();
					return;
				}
			}

**Comment by Keader** [comment]
Dup #7425
