### ISSUE TITLE
[3.3.5] Taunt does not keep the target in combat [20$ bounty]

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18877]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** http://wotlk.evowow.com/?spell=355 does not keep the target in combat.

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Target should remain in combat while taunted, he is afterall, trying to attack you

**Steps to reproduce the problem:**

1. Cast taunt
2. Notice target not in combat
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**   https://github.com/TrinityCore/TrinityCore/commit/439654d1e88dfc20ed437ac66e3b5a80833da773

**TDB version:**  62

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
TDB 61?

**Comment by Persephone** [comment]
Yeah sorry i am using 62

**Comment by Persephone** [comment]
BUMP. Heard you can put bounties on these? 30$ bounty to whoever finds any suitable fix for this nonsense :3 been trying for ages now, i know its immune on players but it should still make the target go in combat so they cant stealth for example

**Comment by Keader** [comment]
@Persephone look: https://www.bountysource.com/issues/41081642-3-3-5-taunt-does-not-keep-the-target-in-combat

**Comment by Persephone** [comment]
ooh thats neat! thanks

**Comment by Persephone** [comment]
awesome, placed a bounty on it

**Comment by Eliminationzx** [comment]
@Persephone , try it.
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 7e13cd3..462acd3 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -2487,7 +2487,7 @@ void Spell::DoAllEffectOnTarget(TargetInfo* target)
     m_hitMask |= hitMask;
 
     // spellHitTarget can be null if spell is missed in DoSpellHitOnUnit
-    if (missInfo != SPELL_MISS_EVADE && spellHitTarget && !m_caster->IsFriendlyTo(unit) && (!m_spellInfo->IsPositive() || m_spellInfo->HasEffect(SPELL_EFFECT_DISPEL)))
+    if (missInfo != SPELL_MISS_EVADE && !m_caster->IsFriendlyTo(unit) && (!m_spellInfo->IsPositive() || m_spellInfo->HasEffect(SPELL_EFFECT_DISPEL)))
```

**Comment by Persephone** [comment]
moment

**Comment by Persephone** [comment]
Nope, nothing happends :/

**Comment by Eliminationzx** [comment]
Ok, I'll try to find other way.

**Comment by Persephone** [comment]
Yeah the spell still says "immune" when i hit the player, so its completely resisted. And target is not placed in combat

**Comment by Eliminationzx** [comment]
@Persephone , can you try other version?

**Comment by Persephone** [comment]
Sure hang on. 

Can anyone link me to the issue with fear pathing? Im gonna place a huge bounty on that darn issue

**Comment by Persephone** [comment]
@Eliminationzx  nope, still no combat is toggled on

**Comment by Eliminationzx** [comment]
@Persephone , updated.

**Comment by Persephone** [comment]
moment @Eliminationzx

**Comment by Persephone** [comment]
@Eliminationzx  sorry to say but same thing, fully resisted and nothing happened :/

http://puu.sh/tykcj/18bd57a158.jpg

**Comment by Eliminationzx** [comment]
@Persephone , taunt shouldn't be immuned for players?

**Comment by Persephone** [comment]
@Eliminationzx  Players are immune to taunt yeah, but they should still be placed in combat when it is casted. With your latest change they are in combat when taunt is cast yeah

**Comment by Persephone** [comment]
so it appears it fixed it

**Comment by Persephone** [comment]
just wondering if it perhaps broke something else? 

if (Unit* target = m_targets.GetUnitTarget())
+        if (!m_caster->IsFriendlyTo(target))
+            m_caster->CombatStart(target, m_spellInfo->HasInitialAggro());

could perhaps break friendly auras?

**Comment by Eliminationzx** [comment]
@Persephone , I'm not sure. Could you test it?

**Comment by Persephone** [comment]
@Eliminationzx  on it atm

**Comment by Persephone** [comment]
I tested atm, i see my previous tests werent good enough. 

just removing the spellhittarget check fixed it too:

-    if (missInfo != SPELL_MISS_EVADE && spellHitTarget && !m_caster->IsFriendlyTo(unit) && (!m_spellInfo->IsPositive() || m_spellInfo->HasEffect(SPELL_EFFECT_DISPEL)))
+	if (missInfo != SPELL_MISS_EVADE && !m_caster->IsFriendlyTo(unit) && (!m_spellInfo->IsPositive() || m_spellInfo->HasEffect(SPELL_EFFECT_DISPEL)))

your first attempt >& sorry

**Comment by Eliminationzx** [comment]
Anyway we should enter in combat state on `Spell::cast`.

**Comment by ariel-** [comment]
> Players are immune to taunt yeah, but they should still be placed in combat when it is cast.

Source? If this were fine, Warrior guides should suggest that you use Taunt against rogues/ferals instead of Rend

**Comment by xStarfall** [comment]
> just wondering if it perhaps broke something else?


if (Unit* target = m_targets.GetUnitTarget())

      if (!m_caster->IsFriendlyTo(target))

            m_caster->CombatStart(target, m_spellInfo->HasInitialAggro());
>could perhaps break friendly auras?


I am not 100% sure but could this causes Disengage from Hunters to launch them Forward instead of Backwards?

**Comment by ariel-** [comment]
> I am not 100% sure but could this causes Disengage from Hunters to launch them Forward instead of Backwards?

No, I'm betting 73a72fb7d3d7e504f3eecc801f7e3a95893e5741 broke it (but sure, it belongs to other issue)

**Comment by xStarfall** [comment]
To be honest, I really had no issue with Disengage in that commit, I was up on 684a5fd3f1895703a52cff7e7f762883c74c5aba with no issues. I know it is pretty old but it is also way newer than the commit you have referenced. After applying Eliminationzx's test-"fix" I've noticed the issue I am talking about with Disengage. After I reverted it, it all went smooth. The reason as to why I was questioning this is.. I really can not see the link between disengage/leaping and that portion of code I quoted.

**Comment by ariel-** [comment]
Fixed by Combat/Threat rewrite? @Treeston

**Comment by Treeston** [comment]
Skimming the issue - yeah.

**Comment by Treeston** [comment]
bounty was removed :disappointed:
