### ISSUE TITLE
[3.3.5] ICC: Sister Svalna's event is canceled by Val'kyr Herald attack and/or another reason

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18874]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The event works ok if the raid is not attacked by Val'kyr Herald. When Val'kyr Herald attacks the raid the NPC Crok Scourgebane helps to defeat her. After that the event does not continue. Frequently the event is canceled without the Val'kyr Herald attack, but I can not identify that pattern. This makes Sister Svalna unable to be defeated and no access to Valithria Dreamwalker.

**Current behaviour:** 
Sister Svalna's event is canceled by Val'kyr Herald attack.

**Expected behaviour:**
Sister Svalna's event should not be canceled by Val'kyr Herald attack.

**Steps to reproduce the problem:**
1. Go close to npc Crok Scourgebane in Upper Spire.
2. The event start.
3. Raid  fight vs Val'kyr Herald and NPC Crok Scourgebane helps to defeat her.
4. NPC Crok Scourgebane does not continue the event.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  439654d

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Post updated: Frequently the event is canceled without the Val'kyr Herald attack, but I can not identify that pattern.

**Comment by Keader** [comment]
#8186
