### ISSUE TITLE
2 Deathknight quests have some sort of pathing issue.

### ISSUE THREAD

**Issue by sigbinium** [TrinityCore/TrinityCore#18887]
**Description:** The quests Massacre at Light's Point and Brothers in Blood (in the DK starting zone) seem to have issues, (didn't have this last time I compiled around august last year)

**Current behaviour:**  Massacre at Light's Point - Mine Cart either phases through objects towards destination or moves in a circle near the planks of the ship. Brothers in Blood - Koltira moves while channeling.

**Expected behaviour:**  Mine Cart goes up the ship without phasing. Koltira does not move until the phase is over.

**Steps to reproduce the problem:**

1. Downloaded and installed all needed software to compile (GitExtensions - Latest, Visual Studio 2015 - Update 3, MySQL - Latest 5.6, Boost - Latest 1.60, CMake - Latest 64bit, OpenSSL 64bit - Latest 1.0.x), also cloned 3.3.5a branch and updated it regularly including the DB updates as well.
2. Compiled the core with default CMake configuration whilst setting the generator to Visual Studio14 Win64
3. Tested it and ran 6 DK characters trying to figure out why Koltira Deathweaver, as soon as he channels the barrier, exits the area.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  9355945

**TDB version:**   335.62

**Operating system:**  Win 8.1 Pro x64

(This is my first time posting here so forgive me for my naivete)

**Comment by Keader** [comment]
Is not the same issue? #18401

**Comment by sigbinium** [comment]
I forgot to mention that The Battle for Light's Hope is also messed up in my compilation. There seems to be no enemies spawned and Highlord Darion disappears when the quest starts. I don't believe it is the same issue tho as the minecarts in this revision moves and reaches (80% of the time) to its destination. I tested on 6 DK characters 2 were in GM accounts. 5 managed to reach the destination but phased through the ship and plank and 1 went around in a circle.

The quest Brothers in Blood last time I compiled ran perfectly, waves of clerics in set intervals, koltira channeling that barrier until phase was over and his chat/speech towards the entrance of the keep was perfect. In my current compilation, he seems to move all the way to the exit until he despawns without finishing the phase. 

It could be the same issue, but I believe it could also be not. I'm not quite sure.

**Comment by sigbinium** [comment]
I was wondering if there was an error in my part that lead to this or is this happening to everyone with the latest commit and db.

**Comment by Rushor** [comment]
yep it's the same issue, all escortmovement is fucked up atm (the move to some strange point while the actions are not completed yet)

**Comment by sigbinium** [comment]
Oh okay. Thank you and I hope all will be resolved soon. I'll help find any errors worth addressing to XD

**Comment by tkrokli** [comment]
Thanks for mentioning those 2 issues, though. Useful to know for future users.
