### ISSUE TITLE
[Crash] Server Crashes when character enters world new or old

### ISSUE THREAD

**Issue by lorac2k14** [TrinityCore/TrinityCore#18882]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Crash on Character load

**Current behaviour:** 
When you start server everything seems to load fine.
Then when you log in with a character it crashes core as soon as character hits the map.
Server crashes hard enough you can not log out of client, but not hard enough to drop you from world.

**Expected behaviour:** (Tell us what should happen instead.)
Server launches with no issue.
Character is able to be loaded into world with no crash.
An other issue i noticed when problem started I pushed a clean TDB to new db and there is no versioning in version even after core start up.
There seems to be an issue in the query system 

**Steps to reproduce the problem:**

1. Pull source from master branch and build in static.
2.  Launch server.
3.  Log into game. build: 23360

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
- [x] Master
- [ ] 3.3.5

**Build type affected by issue:**
- [x] Dynamic
- [x] Static

**Boost Version**
boost_1_63_0
boost 1_60_0 on last build

**TC rev. hash/commit:**  9eda3d85423b4b5a84ad0c45e1bc06db37b6eb5c

**TDB version:**  TDB 703.00

**Compiler:** MSVS 2015

**Operating system:**  Windows 2012 r2

**Additional Notes:**
An other issue i noticed when problem started I pushed a clean TDB to new db and there is no versioning in version even after core start up.
There seems to be an issue in the query system
The core does not touch version in world db but it crys about it in crashlog dump
I edited my password information in txt

**Crashlog:**
https://gist.github.com/lorac2k14/0445ce11ee2249ab883441762301cd82

**Crashlog for Revision:** 41fc011d4ece279b3b8ae5d3f9208380ca222a2c
https://gist.github.com/lorac2k14/1ad6f94d8021c481072dc377f8a594ff
Updated 1/20/17 06:00 -500gmt

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by lorac2k14** [comment]
In submitted dump I stepped my boost back to 1_61_0

**Comment by myran2** [comment]
Which locale are you using? Not enUS?

**Comment by lorac2k14** [comment]
enUS locale

**Comment by Shauren** [comment]
All characters or a specific class or?

**Comment by lorac2k14** [comment]
@Shauren Sorry it took so long to reply I wanted to test it to make sure to provide you with most accurate information It impacts all classes / races

**Comment by Aokromes** [comment]
build 23222? TC master branch needs 7.1.5.23360 not 7.1.0.

**Comment by lorac2k14** [comment]
@Aokromes please read what i said
I Tried old client as a test
The crash happens only on 23360

**Comment by lorac2k14** [comment]
@Shauren OK I think discovered the issue
It seems the Tact_key update to hotfixes went missing
I nuked the hotfixes db again and re pushed it to sql server then launched core and allowed it to auto update now i have been able to successfully log in with 2 toons so far.
However the toons created while issue was present are corrupt and this is why i did not catch that the issue is corrected. I will continue to check every class and every race and report if it is fixed.
if this is in fact the issue  I am so sorry for wasting your time.
Give me about 30 mins to check all classes / races
If all goes right I will close this issue

**Comment by lorac2k14** [comment]
yes that is what the issue was 
I feel stupid now. I read the crash debug log I should have put 2 and 2 together
Sorry for wasting your time :(

**Comment by Shauren** [comment]
but missing tact_key should not cause anything like this

**Comment by lorac2k14** [comment]
As soon as i replaced the hotfixes again and allowed the core to update it automatically again it resolved.
Is it possible something was pushed to hotfixes db from core comms during a hickup somewhere?
Not sure if that is possible.

**Comment by Shauren** [comment]
Deleted tact_key data from my db and logged in just fine with no crash, closing this
