### ISSUE TITLE
[NPC][WotlK] Ironwool Mammoth, Part 1, mini event

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#18895]
**Current behaviour**: Ironwool Mammoth http://wotlk.openwow.com/npc=29402 has a mini event that is missing on the server.
![wowscrnshot_012017_145108](https://cloud.githubusercontent.com/assets/6797611/22151704/eead095c-df27-11e6-8e25-97d54e7f5595.jpg)

**Expected behaviour**: I have recored a video from current retail, but i will also add the missing elements here:
1) Ironwool Mammoth should be spawned dead. (currently he is spawned alive and moving)
2) The Savage Hill Brute http://wotlk.openwow.com/npc=29623 (next to the mammoth) should be constantly chopping the dead mammoth.

The other npcs in the area are ok. Here is the video from retail legion from 20.01.2017:
https://www.youtube.com/watch?v=wvxcjplMrZs

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
**3.3.5** 

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/fe999bcf78f201788fe3ca2556b73fd955444150

**Operating system:**  win 10

**Comment by Rushor** [comment]
fix:

```sql
UPDATE `creature` SET `spawndist`=0, `MovementType`=0, `unit_flags`=`unit_flags`|536870912|32770, `dynamicflags`=32 WHERE  `guid`=116778;

DELETE FROM `creature_addon` WHERE `guid` IN (113320, 116778);
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES 
(113320,0,0,0,1,233, ''),
(116778,0,0,7,1,0, '29266');
```

**Comment by offl** [comment]
```spell_creature_permanent_feign_death``` is currently unused?

**Comment by Rushor** [comment]
yep, not assigned to a spellid
