### ISSUE TITLE
[3.3.5] Rather odd, Mail Issue

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18890]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** If you send a mail which contains a lot of items for example, from character A to B but then delete characer A, the mail wont appear on character B or either appear empty. It bugs out thats for sure.

I tried looking at the mail system but I have no idea where to start when locating this issue :/

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Shouldnt mail appear no matter what happened to previous character?

**Steps to reproduce the problem:**

1. Send a mail with stacked items etc from A to B
2. Delete char A before checking mail on B
3. Log on B, mail is bugged

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/23f76b563f3002e1557eb5dd75e0d26bd22357ab

**TDB version:**  62

**Operating system:**  14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#4022

**Comment by Persephone** [comment]
oh boy another ancient one :3
