### ISSUE TITLE
Core: Quest requirement check character_queststatus_seasonal

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#18913]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**   In the DB we have the quest http://www.wowhead.com/quest=8883/valadar-starsong which should not be available until http://www.wowhead.com/quest=8867/lunar-fireworks is rewarded. If you create a new character, everything is fine, but if you have an old character who completed these 2 quests last year, the NPC will show the 2 quests together. If I'm not wrong, the actual check is done in both table `character_queststatus_seasonal` and `character_queststatus_rewarded`, but it must be done only in `character_queststatus_rewarded`.

PS: `.lookup quest` shows that these 2 quests are not rewarded or taken.

**Current behaviour:** Quest requirement uses `character_queststatus_seasonal`

**Expected behaviour:** Quest requirement must use `character_queststatus_rewarded` only

**Steps to reproduce the problem:**

1. Find a character who completed these 2 quests (8867, 8883)
2.  `.go c id 15895`
3. Notice that the NPC proposes both quests

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:**  rev. 591a25500d98

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
You can also complete both quests  (8867, 8883) then .quest remove , you will not be able to get this quests, so the status rewarded is checked somewhere else than character_queststatus_rewarded

**Comment by xinef1** [comment]
Should help

```diff
 src/server/game/Entities/Player/Player.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 30fd605..e9cb8a3 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -15337,7 +15337,7 @@ bool Player::SatisfyQuestPreviousQuest(Quest const* qInfo, bool msg)
         if (qPrevInfo)
         {
             // If any of the positive previous quests completed, return true
-            if (*iter > 0 && m_RewardedQuests.find(prevId) != m_RewardedQuests.end())
+            if (*iter > 0 && GetQuestStatus(prevId) == QUEST_STATUS_REWARDED)
             {
                 // skip one-from-all exclusive group
                 if (qPrevInfo->GetExclusiveGroup() >= 0)
@@ -15356,7 +15356,7 @@ bool Player::SatisfyQuestPreviousQuest(Quest const* qInfo, bool msg)
                         continue;
 
                     // alternative quest from group also must be completed and rewarded (reported)
-                    if (m_RewardedQuests.find(exclude_Id) == m_RewardedQuests.end())
+                    if (GetQuestStatus(exclude_Id) != QUEST_STATUS_REWARDED)
                     {
                         if (msg)
                         {

```

**Comment by Killyana** [comment]
Correct me If I'm wrong:
A seasonal quest will be added in both `character_queststatus_seasonal`  once rewarded, It will remain in both table until (the event ends or I don't kow how this is handled)
This was made to avoid the reset that happen in `character_queststatus_rewarded` if the server reboot or crash, in this case  `character_queststatus_seasonal` will return that the quest is rewarded as this table doesn't reset after a reboot.

If quests stats are cleared from `character_queststatus_seasonal` once the event ends why quest chaining that use this stats consider this quests as rewarded, and if they really are rewarded why I'm able to take and complete them again the next year?

**Comment by xinef1** [comment]
All rewarded quests are put on rewarded quest map. However this won't work for seasonal quests, that should be repeatable each year. That's why additional table character_queststatus_seasonal was created, to store rewarded seasonal quests (along with normal rewarded table / map). This additional map is cleared when event ends / starts. Some functions were adjusted to check whether quest is seasonal and if so, check only seasonal map and not normal rewarded one. This way you have seasonal quests on rewarded map which can be used for achievements counting etc and additional map that allows to check if given seasonal quest can be obtained during given event.
As you can see, my patch changes manual checking of rewarded map, to use dedicated functions that properly distinguish between normal and seasonal quests and as a result, fix problem described in the issue.

**Comment by Killyana** [comment]
I tested without and with your change, and it fixes the quest chaining, but there's something that I don't understand, If I take the quest X then reward it and stop/start the event, I will be able to retake the quest again but I cannot reward it as it still exist in `character_queststatus_rewarded` this happen with or without your change, So when quests status are removed from `character_queststatus_rewarded`  ? (It's not an issue, but just want to know)
http://imgur.com/a/MHXHG

**Comment by xinef1** [comment]
You should be able to reward the quest second time, because character_queststatus_rewarded shouldn't be checked for seasonal quests at all.
The only case when quest is removed from character_queststatus_rewarded is when command quest remove is issued or when spell effect SPELL_EFFECT_CLEAR_QUEST (139) is used.

**Comment by MrSmite** [comment]
> If I take the quest X then reward it and stop/start the event, I will be able to retake the quest again but I cannot reward it as it still exist in

I think the problem is there is no call that uses *CHAR_DEL_CHARACTER_QUESTSTATUS_SEASONAL* anywhere. If you search on the repo, the only results are:

*CharacterDatabase.h*
*CharacterDatabase.cpp*

so it appears the seasonal table is never cleared which is why you can't complete them again.
