### ISSUE TITLE
[335] Pathing NPCs Should Not Resume Pathing With Dialogs Open

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#18916]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Pathing NPCs with a dialog or vendor window open will suddenly walk away from the player causing the dialog / window to close.

**Current behaviour:** See description

**Expected behaviour:** Pathing NPCs that a player interacts with should remain stopped until the player closes the dialog / vendor window

**Steps to reproduce the problem:**

1. Go to Darkshire
2. Right click on [Gavin Gnarltree](http://www.wowhead.com/npc=225/gavin-gnarltree) to open his vendor window
3. Wait

Gavin is a Weaponsmith with a vendor option. He has a path from the forge to an anvil outside and back. If you talk to him when he is at the anvil, he will walk away from you even if the vendor window is open, causing it to close.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  Any but I first noticed it in 2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:** TDB_full_world_335.61_2016_04_11 + updates

**Operating system:**  WinXP, Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
thats because fucked up sai

**Comment by Rushor** [comment]
it must be fixed individual for the creatures with SAI path.

fic for this guy here:

```sql
-- Gavin Gnarltree SAI
SET @ENTRY := 225;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0 AND `id`=7;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,7,0,64,0,100,0,0,0,0,0,54,180000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gavin Gnarltree - On Gossip Hello - Pause Waypoint");
```

The issue can be closed after the fix above was pushed.

We already have https://github.com/TrinityCore/TrinityCore/issues/18873. All sai out-of-combat scripts will be converted once the new system was implemented.

**Comment by Riztazz** [comment]
![f454cf221f84486909b0e0b7c6414861](https://cloud.githubusercontent.com/assets/16348711/22182932/cdb0747e-e0b1-11e6-9996-c559cfcae9eb.gif)
