### ISSUE TITLE
[3.3.5] Spell/Paladin: Light's Grace not work properly

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18927]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wotlk.openwow.com/spell=31836
Light's Grace (Rank 3): Gives your Holy Light spell a 100% chance to reduce the cast time of your **next Holy Light spell by 0.5 sec. This effect lasts 15 sec**.
>    With all 3 ranks trained, this talent will trigger for every cast of [Holy Light], with consecutive casts maintaining a 2 second cast time, increasing the HPS of the spell significantly.
    It's sometimes helpful to cast a "dummy" Holy Light right before the pull, to ensure that Light's Grace is active from the start.

**Current behaviour:** 
Related buff Light's Grace is consumed by the next Holy Light.

**Expected behaviour:**
Related buff Light's Grace should not be consumed by the next Holy Light for the next 15 secs.

**Steps to reproduce the problem:**
1. Paladin casts Holy Light.
2. Related buff Light's Grace appears.
3. Paladin casts Holy Light again.
4. Related buff Light's Grace disappears.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  591a255

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eliminationzx** [comment]
Fix
```SQL
DELETE FROM spell_proc WHERE SpellId = 31834;
```
