### ISSUE TITLE
[master] DB/Quests: Undead starting area (Deathknell)

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18926]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Make the Deathknell area functional and blizzlike.

**Current behaviour:** (Tell us what happens.)  There are 7 Quest missing from this start area.

**Expected behaviour:** (Tell us what should happen instead.) After Scourge on our Perimeter, you should be directed to continue on a quest chain that gets you to level 5 and leads you out of Deathknell. Currently you get stuck at level 3 after turning in "Scourge on our Perimeter" (http://www.wowhead.com/quest=26801/scourge-on-our-perimeter)

**Steps to reproduce the problem:**

1. Create an Undead character
2. Get to the point described above
3. Get stuck at Level 3, quests are out of order or nonexistent.

**Branch(es):** master

**TC rev. hash/commit:**  adbe8da 

**TDB version:**  7.0.3

**Operating system:**  Debian 8

This task list is here to assist in fixing the issues found in this area. Fixes will be provided and help is greatly appreciated. This is for the Master Branch, not 3.3.5 as this area works in the 3.3.5 release.

The unchecked quests below are either broken or nonexistent:

- [x] Fresh Out of the Grave (24959)

- [x] The Shadow Grave (28608)

- [x] Those that Couldn't be saved (26799)
```sql
UPDATE `quest_template` 
SET `RewardChoiceItemID1` = '11847', `RewardChoiceItemQuantity1` = '1', 
`RewardChoiceItemID2` = '3275', `RewardChoiceItemQuantity2` = '1' 
WHERE `quest_template`.`ID` = 26799; -- Quest: Those That Couldn't Be Saved, Undead 
```
- [x] Caretaker Caice (28652)

- [x] Beyond the Graves (25089)

- [x] The Wakening (24960)

- [x] Recruitment (26800)
```sql
UPDATE `quest_template` 
SET `RewardChoiceItemID1` = '11848', `RewardChoiceItemQuantity1` = '1', 
`RewardChoiceItemID2` = '11849', `RewardChoiceItemQuantity2` = '1', 
`RewardChoiceItemID3` = '11850', `RewardChoiceItemQuantity3` = '1' 
WHERE `quest_template`.`ID` = 26800; -- Quest: Recruitment, Undead
```
- [x] Shadow Priest Sarvis (28653)

- [x] Scourge on our Perimeter (26801)

- [x] Novice Elreth (28651)
Thanks to @CrisPj 
```sql
DELETE from quest_template_addon WHERE ID IN (28651);
```
- [x] (28651) Needs to be set to only be available after 26801

- [x] The Truth of the Grave (24961)

- [x] The Executor In the Field (28672)

- [x] The Damned (376)

- [x] Night Web's Hollow (380)

- [x] No Better Than the Zombies (24970)

- [x] Assault on the Rotbrain Encampment (24971)

- [x] Vital Intelligence (383)
- [x] (383) Needs to be set to only be available after 24971

As you can see, this is a series of quests in a specific Start Area which needs to be addressed. This is one of many areas which I will be working on.

Please Reference https://github.com/TrinityCore/TrinityCore/issues/18935 for Class Specific Obsolete Quest

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Edreisantafe** [comment]
If you allow me to add that the aura with which the undead are born could not be removed with right click. Must be removed once you accept the first mission.

**Comment by Keldo** [comment]
I don't recall and aura needing to be clicked, you accept the first quest, complete it, and continue on..

**Comment by Kittnz** [comment]
Check sniffs :)

**Comment by Keldo** [comment]
Not a forum but I'll entertain you, its been sniffed a million times, nothing got fixed

**Comment by Edreisantafe** [comment]
Not that you need it is that you can click and cancel it, when the effect should be that it can only be removed when you accept the first mission.

**Comment by Keldo** [comment]
Updated the tracker and commented on current issues..

**Comment by CrisPj** [comment]
for Novice Elreth, try deleting the obsolete quest template addon, like this:

DELETE from quest_template_addon WHERE ID IN (24964,24965,24966,24967,24968,24969);

**Comment by Keldo** [comment]
Done but can't test yet, will confirm when I get home in a few hours

**Comment by Keldo** [comment]
Not 100% in order but it works

**Comment by Keldo** [comment]
2 more minor issues and this will be complete.

**Comment by CrisPj** [comment]
Vital Intelligence (24972) only be available after 24971:
```sql
UPDATE `quest_template_addon` SET `PrevQuestID` = 24971 WHERE `ID` = 24972;
```

**Comment by Keldo** [comment]
That doesnt work, Now Scourge on our Perimeter (26801) is not available

**Comment by Keldo** [comment]
**COMPLETE FIX**
```sql
-- Undead Start Area (Deathknell) Quest Fix

UPDATE `quest_template` 
SET `RewardChoiceItemID1` = '11847', `RewardChoiceItemQuantity1` = '1', 
`RewardChoiceItemID2` = '3275', `RewardChoiceItemQuantity2` = '1' 
WHERE `quest_template`.`ID` = 26799; -- Quest: Those That Couldn't Be Saved, Undead

UPDATE `quest_template` 
SET `RewardChoiceItemID1` = '11848', `RewardChoiceItemQuantity1` = '1', 
`RewardChoiceItemID2` = '11849', `RewardChoiceItemQuantity2` = '1', 
`RewardChoiceItemID3` = '11850', `RewardChoiceItemQuantity3` = '1' 
WHERE `quest_template`.`ID` = 26800; -- Quest: Recruitment, Undead

UPDATE `quest_template_addon` SET `PrevQuestID` = 24971 WHERE `ID` = 24972; -- Vital Intelligence, Order Sequence

DELETE from quest_template_addon WHERE ID IN (28651); -- Novice Elreth
```

**Comment by Faq** [comment]
@Killyana could you please review?

**Comment by Killyana** [comment]
ok

**Comment by HannibalRoG** [comment]
Any news about this @Killyana ?

**Comment by Killyana** [comment]
RewardChoiceItem is handled by DBC according to the class, tested and works correctly on master.
