### ISSUE TITLE
[master] Mage - Frostbolt issue

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#18932]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Frostbolt isn't slowing movement speed by 50% for 15 sec.

**Current behaviour:** (Tell us what happens.) Frostbolt isn't slowing movement speed.

**Expected behaviour:** (Tell us what should happen instead.) Frostbolt should slowing movement speed.

**Steps to reproduce the problem:**

1. Select Mage
2. Cast the Frostbolt spell

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/1c00f0b2d405d5f9eee4009ca5810e9721cd36ce

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by matukaa** [comment]
You're looking for spell 205708, linked_spell type 1

**Comment by ArcaneFox** [comment]
Thank you, the following worked for me:

```sql
INSERT INTO `spell_linked_spell` VALUES(116,205708,1,'Chilled');

```

**Comment by Keader** [comment]
`spell_linked_spell` in 90% of cases is hack.
Make a little SpellScript ^^

**Comment by Keader** [comment]
I dont have spellwork of 7.x here

Try: https://gist.github.com/Keader/02eaf2fd3fa32e7c29f808802a52c111

Someone can confirm if it should be handled by proc or something?

**Comment by Edreisantafe** [comment]
I compiled it and tried it and it seems to me Blizzlike

**Comment by Keader** [comment]
nice, @tkrokli or @Edreisantafe can you open pr about it?
i dont have client or master branch here :)

**Comment by Edreisantafe** [comment]
Ok, i do it.

**Comment by Edreisantafe** [comment]
That 's what I did

**Comment by Edreisantafe** [comment]
Finally we have a PR for this.
