### ISSUE TITLE
[Quest] No place to run

### ISSUE THREAD

**Issue by DannyDD** [TrinityCore/TrinityCore#1893]
Core Hash: a1ed562+
DB: TDB_335.11.40_2011_05_09 + all updates until 2011_06_05_00_world_spelldifficulty_dbc

When using the item provided it spawns the destructive ward, but it sticks to the char that used it and the quest doesn't complete nor spawn mobs to attack the ward...

**Comment by Killyana** [comment]
I just complete the quest on 68c4ea314443, seems fixed.
