### ISSUE TITLE
DB/Quest: Investigate the Amani Catacombs

### ISSUE THREAD

**Issue by Smileynator** [TrinityCore/TrinityCore#18934]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The quest asks you to burn troll corpses given a torch.
http://www.wowhead.com/quest=9193/investigate-the-amani-catacombs

**Current behaviour:** (Tell us what happens.)
You "burn corpses". Nothing happens besides the request count upping. You can continue to burn the same corpse 10x, and nothing else needs to be done.

**Expected behaviour:** (Tell us what should happen instead.)
The corpses need to properly burn. And the corpse then despawns to later re-spawn. I also think there is some sort of pool of spawns in official WoW (IE: 25 spawn points, but only 10 active at any given time)

**Steps to reproduce the problem:**

1.  Just run through the quests. Wowhead article above tells the requirements to start it.

**Branch(es):** 3.3.5 tested, probably also master.

**TC rev. hash/commit:**  39b20b4431a1a67446e9cc4c2221fd42cc907291

**TDB version:**  TDB 335.62 + updates up to and including `2017_01_17_00_world.sql`

**Operating system:**  Windows 7

First issue here, did i do good?

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
> you can continue to burn the same corpse 10x, and nothing else needs to be done.

This isse does not exist on 335, but:

> The corpses need to properly burn.

This issue also exists on 335

**Comment by Smileynator** [comment]
@rushor unless my db is incorrect the issue does exist in 335. I could simply stand by 1 corpse and it never despawned because it doesn't burn up. The only wait time is the torch cooldown. Maybe you had that confused?

**Comment by Smileynator** [comment]
Oh, my bad. There is a 2nd requirement. That is to "walk to" the center of the generic quest area. Which properly works!
