### ISSUE TITLE
[3.3.5] Halls of Reflection: The Captain's Chest does not appear in Alliance gunship

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#18943]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wowwiki.wikia.com/wiki/The_Captain%27s_Chest
>The Captain's Chest is a loot container which can be found onboard either **The Skybreaker** or Orgrim's Hammer **at the end of the Halls of Reflection**. In order to open it, the player must escape from the Lich King and destroy the obstacles he puts in their way. 

**Current behaviour:** 
The Captain's Chest does not appear in Alliance gunship.

**Expected behaviour:** 
The Captain's Chest should appear in Alliance gunship.

**Steps to reproduce the problem:**
1. Finish The Escape of The Lich King event in Halls of Reflection.
2. The Captain's Chest does not appear in Alliance gunship.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  591a255

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
An important observation: Apart from the chest does not appear the portal to Dalaran or NPCs.

**Comment by Noryad** [comment]
@Keader 
I do not know when this event was broken for the alliance but in ad6cd70 it works ok, so i compared the files located in https://github.com/TrinityCore/TrinityCore/tree/3.3.5/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection and there were no significant differences except halls_of_reflection.cpp where
`player->PlayerTalkClass->ClearMenus();` on ad6cd70 was replaced by `ClearGossipMenuFor(player);` in current revision c2a36c9.
Before you speak to Jaina and THE_LICH_KING_ESCAPE start you can go to the end and look down to see the following
![hall](https://cloud.githubusercontent.com/assets/30839/22483396/e8a54776-e7b1-11e6-8b95-a8f608c077c5.jpg)
That means the chest, the dalaran portal and the NPCs are on the ship before the event starts and for some reason they disappear. Note that the chest can not be looted at this time and is correct. Maybe a problem related with database or some flag that affects the alliance, again the event works for the horde

**Comment by Keader** [comment]
Sure, i will look it in next week :)

**Comment by Noryad** [comment]
any news?

**Comment by Keader** [comment]
nope, no much time :(

**Comment by Noryad** [comment]
Can @sirikfoll help here?

**Comment by Noryad** [comment]
Yes, i've seen you busy lately, can @sirikfoll help here?

**Comment by tkrokli** [comment]
**sirikfoll** knows Icecrown scripts well, but I would also like to ask @Killyana if this could be caused by anything faulty in DB or if we only need to check C++ scripts (or maybe even core) for this issue.

**Comment by sirikfoll** [comment]
Don't know what could be the problem, I am not able to reproduce the issue, the Npcs and the Chest always appear to me :/

**Comment by Noryad** [comment]
Did you try with an alliance character?

**Comment by Elarose** [comment]
Just tested this with an Alliance character. Level 80 Paldin. Chest and teleport stayed and both worked for me.

**Comment by tkrokli** [comment]
Looks like this is caused by something outside of TrinityCore source. @Noryad : please test again on 100% straight TC source & DB.

**Comment by Noryad** [comment]
hmmm, invalid on f612b1c

**Comment by amaroc** [comment]
Same behavior.
Info:
- Two side faction interaction - enabled.  
- Linux, rev. 0e7f3002f51d+
- Modifications: only from Rotchet (transmogrification + portal master npc).
- 335 branch

1. Alliance - no loot, even if i add it manualy .gobject add temp  (.lookup item Captain's chest). And no any NPC on Gunship.
2. Horde - all works perfect, all NPC stay on gunship and chest with loot here.

After i test Horde faction in this instance, i did relog back to alliance character, he stayed in HoR, near gunship, and WoW- on gunship appears NPC, and chest, but i cannot be able to click on this chest and loot it.

I will try to test it on clear trinity, with and without 2-side interaction.
