### ISSUE TITLE
[3.3.5] boss professor putricide / gas cloud

### ISSUE THREAD

**Issue by Mrgrasser** [TrinityCore/TrinityCore#18946]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** gas cloud give 10 stack [Gaseous Bloat] for target , Every second 2 stack is low , must Every second 1 stack low.
edit : http://www.wowhead.com/spell=70672/gaseous-bloat
**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  2db3e86d9bf200e5049e553160bc47b7bacac621

**TDB version:**  62

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
provide spell ids pls

**Comment by Killyana** [comment]
Here we can see it's 20secs https://youtu.be/uCLrlyyXD6I?t=3m2s it's the normal mode

**Comment by Mrgrasser** [comment]
I do not know for Target Time, But the loss of the second stack 2 is now, so after 5 second gas cloud change target this is very fast .

**Comment by Killyana** [comment]
Cannot reproduce on rev. 5b6994b7aee9 the player loses 1stack every 2secs

**Comment by Keader** [comment]
@Mrgrasser Please man, build a clean trinity/clean db in other folder and test if you can reproduce before report here.
We cant help you with your custom codes.

**Comment by Mrgrasser** [comment]
@Keader I dl new TC just some change , The changes are not at all related to this topic , but check my release 
- We cant help you if your issues is caused by custom codes
I don't want your help !!! I just report for any problem And if have problem fix it, I say help me man ?!! no 
@Keader I will not put to use some of your ideas VB code

**Comment by ariel-** [comment]
> The changes are not at all related to this topic 

Impossible to know without looking at the sources, maybe you don't think that X code breaks something, but it does, this is why when reporting issues and posting your commit hash, you must use THAT hash clean
