### ISSUE TITLE
Crashs worldserver

### ISSUE THREAD

**Issue by updeal** [TrinityCore/TrinityCore#18957]
**Description:**
1. When use command  ".mod faction"  - server crashed.
2. When create gameobject of type 11 - server crashed.

**Current behaviour:**
Crash server.

**Expected behaviour:**
1. Change factions NPCs
2. When creating an object of type 11, it should appear, not to crash the server

**Steps to reproduce the problem:**
1. Used cmd ".mod faction" to target.

2. Create any object in DB, simply add the object ID and type 11. In general, I used object 216666 (Carousel Faire)

**Branch(es):** master 

**TC rev. hash/commit:**  
6f66904

**TDB version:**  
7.0.3+updates

**Operating system:**  
Win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Shauren** [comment]
And where is the crash log?

**Comment by Shauren** [comment]
ps. You must not add objects type 11 to gameobjects table, they need to go in transports
