### ISSUE TITLE
[3.3.5] Friendly bandage breaks stealth

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18951]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** If a friendly player casts bandage on a player in stealth, stealth is lost. Only when the rogue himself casts bandage, should stealth be broken. Bandage should count as a friendly heal.

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Bandage cast by friendly player should not break stealth.

**Steps to reproduce the problem:**

1.  Stealth
2.  Cast bandage on the rogue from another friendly player
3.  Notice stealth is lost

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/5b6994b7aee99ebd6ee3849ef8ba6d7e5395ffc2

**TDB version:**  62

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Persephone** [comment]
@Eliminationzx  Would you perhaps have some magic for this one too :P ?

**Comment by Eliminationzx** [comment]
@Persephone , you can try to use SPELL_ATTR0_CU_DONT_BREAK_STEALTH.

**Comment by Persephone** [comment]
Yeah testing atm, it should break tho if the rogue himself uses it wondering if adding that allows him to use it in stealth, let me test :)

**Comment by Persephone** [comment]
@Eliminationzx  damn, adding that flag still causes it to break stealth

**Comment by Persephone** [comment]
must be something in here void AuraEffect::HandlePeriodicHealAurasTick(Unit* target, Unit* caster) const

**Comment by Noryad** [comment]
Fix
`
DELETE FROM `spell_custom_attr` WHERE `entry` = 11196;
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUE (11196, 0x40); -- Recently Bandaged
`

**Comment by Noryad** [comment]
Fix
`DELETE FROM spell_custom_attr WHERE entry = 11196;`
`INSERT INTO spell_custom_attr (entry, attributes) VALUE (11196, 0x40); -- Recently Bandaged`
