### ISSUE TITLE
[3.3.5] Fear Bug Teleportation Bounty

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#18956]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Cant find the original issue, i know there are many so just creating this so place a bounty on it :) 

**Current behaviour:** (Tell us what happens.) Currently being feared will make the target teleport around, which deadly ruins pvp as it makes it impossible to hit the target properly

**Expected behaviour:** (Tell us what should happen instead.) Should run smoothly

**Steps to reproduce the problem:**

1. Cast fear in wsg
2.  notice target teleporting around like some no gcd blinking mage
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/5f901d3d75660118f705c27c84e1ae895ad8e3e7

**TDB version:**  62

**Operating system:**  ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Persephone** [comment]
https://www.bountysource.com/issues/41309352-3-3-5-fear-bug-teleportation-bounty

100$ bounty

**Comment by Aokromes** [comment]
#18306

**Comment by Persephone** [comment]
ahh there it was

**Comment by Persephone** [comment]
What happened to the bounty then?

**Comment by Persephone** [comment]
@Aokromes ^

**Comment by Aokromes** [comment]
dunno, check if you can remove it or move it to the other ticket.

**Comment by Persephone** [comment]
alright
