### ISSUE TITLE
[Item] Solace of the Defeated/Fallen

### ISSUE THREAD

**Issue by Bonecek** [TrinityCore/TrinityCore#1896]
Items http://www.wowwiki.com/Solace_of_the_Defeated_(heroic); http://www.wowwiki.com/Solace_of_the_Defeated; http://www.wowwiki.com/Solace_of_the_Fallen; http://www.wowwiki.com/Solace_of_the_Fallen_(heroic); 

do NOT stack mana regen buff on following spells: 

Druid: Rejuvenation, Lifebloom, Regrowth

Idn how is it with other classes spells. But if you can repair it with these druid spells, I can make an report for you.

**Comment by Skyepup** [comment]
--
    DELETE FROM spell_proc_event WHERE entry=67698;
    DELETE FROM spell_proc_event WHERE entry=67752;

    INSERT INTO spell_proc_event (entry, SchoolMask, SpellFamilyName, SpellFamilyMask0, SpellFamilyMask1, SpellFamilyMask2, procFlags, procEx, ppmRate, CustomChance, Cooldown) VALUES
    (67698, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);
    (67752, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);

This is tested working.

**Comment by danlapps** [comment]
Has this issue been closed in one of the many commits above ?

**Comment by Rushor** [comment]
the sql from https://github.com/Skyepup/TrinityCore/commit/cb243575c494be37b76407da3b33d314eb50a7e3 should be posted here 

and:

https://github.com/TrinityCore/TrinityCore/issues/1896#issuecomment-11885803

this needs more attention

**Comment by Exodius** [comment]
As per @Rushor's request. Posting it here:

```sql
-- Solace of the Defeated/Fallen proc fix
DELETE FROM spell_proc_event WHERE entry=67698;
INSERT INTO spell_proc_event (entry, SchoolMask, SpellFamilyName, SpellFamilyMask0, SpellFamilyMask1, SpellFamilyMask2, procFlags, procEx, ppmRate, CustomChance, Cooldown) VALUES
(67698, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);

DELETE FROM spell_proc_event WHERE entry=67752;
INSERT INTO spell_proc_event (entry, SchoolMask, SpellFamilyName, SpellFamilyMask0, SpellFamilyMask1, SpellFamilyMask2, procFlags, procEx, ppmRate, CustomChance, Cooldown) VALUES
(67752, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);

**Comment by tkrokli** [comment]
Suggestion: merge those 2 queries into 1 (since they are using the same table) :
```sql
-- Solace of the Defeated/Solace of the Fallen (Normal/Heroic) proc fix
DELETE FROM `spell_proc_event` WHERE `entry` IN (67698,67752);
INSERT INTO `spell_proc_event` (`entry`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask0`,`SpellFamilyMask1`,`SpellFamilyMask2`,`procFlags`,`procEx`,`ppmRate`,`CustomChance`,`Cooldown`) VALUES
(67698, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0),
(67752, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);

**Comment by Rushor** [comment]
pls report remaining issues in a new ticket with a propper description
