### ISSUE TITLE
Issue with importing sqls

### ISSUE THREAD

**Issue by trihexa9** [TrinityCore/TrinityCore#18964]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Unable to import the sql auth_2016_04_11_2016_10_17, characters_2016_04_11_2016_10_17, hotfixes_2016_04_11_2016_10_17, world_2016_04_11_2016_10_17

**Current behaviour:** (Tell us what happens.)
Show errors when trying to import these sql to database.
 [http://prntscr.com/e08s2g](url) 
[http://prntscr.com/e08sf0](url)
[http://prntscr.com/e08slq](url)
[http://prntscr.com/e08srp](url)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) master

**TC rev. hash/commit:** 		
adbe8daf8af45623ecd8c3d62b8fc72690578f4d

**TDB version:**  TDB 703.00

**Operating system:**  Windows 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Leave core do the work, don't import sql files manually unless you known very well what are you doing. you don't need to import those files unless you are hand updating one extreme old core.
If you have issues, ask on forum, those files works properly if properly used.

Read:
https://trinitycore.atlassian.net/wiki/display/tc/Databases+Installation
https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/

**Comment by tkrokli** [comment]
@trihexa9 : Looks like you have tried to import the SQL files without creating the databases. Like Aokromes said, use the recommended methods to create the databases and also import the SQL files by running Worldserver as soon as your source is properly updated and your compile is complete without errors. (This also depends on following all the steps in the wiki guide, like extracting dbc, maps, vmaps etc.)
