### ISSUE TITLE
Lady Deathwhisper entrace door didn't close when fight begins

### ISSUE THREAD

**Issue by GMKyle** [TrinityCore/TrinityCore#18966]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**Lady Deathwhisper entrace door keeps open when the boss event is running.

**Current behaviour:** Lady Deathwhisper entrace door remains open when the boss enter in combat.

**Expected behaviour:** Lady Deathwhisper entrace door should be closed when the boss enter in combat.

**Steps to reproduce the problem:**

1. Go to IcecrownCitadel
2. Enter in Lady Deathwhisper room or .go creature id 36855
3. Attack Lady Deathwhisper

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  5f901d3 

**Operating system:**  Debian 8

**Comment by GMKyle** [comment]
**Posible Solution**
```
--ORATORY OF THE DAMNED ENTRANCE (Lady deathwisper)
UPDATE `gameobject_template` SET `Data0` = '1' WHERE `entry` = 201563;
UPDATE `gameobject` SET `state` = '0' WHERE `guid` = 150364;
```

**Comment by Aokromes** [comment]
change data0 without sniff is hack.

**Comment by GMKyle** [comment]
Green Plague Monster Entrance have the same value in data0 also Lord Marrowgar's Entrance xD

**Comment by Keldo** [comment]
Just sniff that portion of the event and submit it, no sniff = hack in TC

**Comment by Keader** [comment]
@sirikfoll Lady deathwhisper is your script, so it's correct?
(C++ stuffs looks correct)

**Comment by Noryad** [comment]
@GMKyle The fix works ok.

**Comment by Aokromes** [comment]
Very likely only

```sql
UPDATE `gameobject` SET `state` = 0 WHERE `guid` = 150364;
```

Is needed.
