### ISSUE TITLE
Ethereal Soul-Trader companion mechanics

### ISSUE THREAD

**Issue by sigbinium** [TrinityCore/TrinityCore#18981]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

Description: Ethereal Soul-Trader companion from Soul-Trader Beacon does not reward Ethereal Credits after killing multiple enemies ranging no matter what level. (I've tested on low level mobs and mobs that still give me exp e.g. 71-80 mobs )

Current Behavior: Able to summon and interact with the Soul-Trader as being a companion pet and a vendor but does not reward Ethereal credit from kills.

Expected Behavior: Enemies slain that grant XP/Honor grants Ethereal Credits while companion is active.

Steps to Reproduce the Problem:
1. Obtain Soul-Trader Beacon from Landro Longshot or by adding the item id 38050
2. Summon the Ethereal Soul-Trader
3. Kill NPCs ranging 71-80 if you're level 80. (Killed mobs while still level 70 with mob levels ranging from 61-69 still no credits.)
4. Ethereal Soul-Trader just stares at you.

Branch: 3.3.5
TC. Rev. hash/commit: 684a5fd
TDB Version: TDB 335.62 10-16-2016 Release + Updates up to most recent 1-25-2016
OS: Win 8.1 64-bit

**Comment by ariel-** [comment]
#4152
