### ISSUE TITLE
[Protobuf] Missing .proto files in /src/server/proto/Client/ Directory.

### ISSUE THREAD

**Issue by fpark12** [TrinityCore/TrinityCore#18988]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I think it would be great if we could upload all the proto files to the repo for people who want to learn how to use protobuf and possibly improve on our existing protocols. There are a few proto files uploaded at the moment but the /src/server/proto/Client/ directory only has the compiled files. What is the reason behind not uploading all of them in the first place?

**Current behaviour:** (Tell us what happens.)
Missing .proto files.

**Expected behaviour:** (Tell us what should happen instead.)
all .proto files in /src/server/proto/Client/ should be present.
**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  32b077ade48da9c6ad90a4936b5226df494ae86c

**TDB version:**  

**Operating system:**  Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Please use our forum for this questions. https://community.trinitycore.org/

**Comment by Shauren** [comment]
/Client directory contains files extracted from the client that must not be modified, there is no room for improvement there
