### ISSUE TITLE
[master] CASC Failure Issue

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#18994]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** CASC ISSUE

**Current behaviour:** CASC is failing to talk to the patch server
![casc_issue_27jan17](https://cloud.githubusercontent.com/assets/2609242/22394990/a83e25e2-e4e4-11e6-84a3-b149a89db298.png)

**Expected behaviour:** Seemless communication and the client actually launching

**Steps to reproduce the problem:**

1. Upgrade the server to revision 0d8c75e
2. Upgrade the client to 7.1.5 23420
3. Rebuild Tools (x64) and copy common.dll to the installation directory
4. Patch Wow and Wow-64
3.  CASC Error (See the image above) almost immediately

**Branch(es):** master

**TC rev. hash/commit:**  0d8c75e 

**TDB version:**  7.0.3

**Operating system:**  Debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Ovahlord** [comment]
happens because the current wow version does not have the required version file uploaded on the trinity core repo so you have to wait until someone will do so.

**Comment by tkrokli** [comment]
Nice, the file is present now. My guess is that funjoker & Aokromes have fixed it. 👍
