### ISSUE TITLE
[3.3.5][Generated Loot] Deprecated Random Enchantments

### ISSUE THREAD

**Issue by Smileynator** [TrinityCore/TrinityCore#19006]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
I just got the following item: http://www.wowhead.com/item=15489/bloodspattered-sabatons
With the name: "Of Defense" behind it.
It gives me 3 "Defense rating" which i think is something deprecated?

**Current behaviour:** (Tell us what happens.)
Random armor enchants somehow includes "Of Defense" defense rating stat up.

**Expected behaviour:** (Tell us what should happen instead.)
I think this is deprecated. I can find no valid mentions of this random enchant online, and recent wowhead entries (Even those in way back machine to 2014)

NOTE: There may be more of these deprecated random types, but i can't find any documents online that note these edits to armor thought the history of WoW. Might help to find someone who knows how that worked on official 3.3.5. The same goes for any other items, although I think they share the same formula on the back end, I am not certain!

**Steps to reproduce the problem:**

1. Generate or gather some random loot from random mobs. Or just take my word for it and check whatever generates this loot in the source code.

**Branch(es):** 3.3.5 (Master unchecked!)

**TC rev. hash/commit:**  39b20b4431a1a67446e9cc4c2221fd42cc907291

**TDB version:**  TDB 335.62 + updates up to and including 2017_01_17_00_world.sql

**Operating system:**  Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Smileynator** [comment]
Note: I found out just now that WoW has live data stating that Of Defense, is a thing.
But instead of "upped defense" is means added dodge chance.
http://us.battle.net/wow/en/item/15489#tab=randomProperties

**Comment by ariel-** [comment]
Defense stat was removed in patch 4.0.1, in WotLK is still valid

**Comment by tkrokli** [comment]
Latest available WotLK version of the wowpedia page;  8 September 2009‎ 06:42) :
http://wow.gamepedia.com/index.php?title=Bloodspattered_Sabatons&oldid=2024308
- `of Defense	+3-4 Defense Rating`
