### ISSUE TITLE
[3.3.5] Core/Spells: stealth interrupted by Consecration while rogue has absorption aura

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#19008]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Allows the rogue to sneak around, but reduces your speed by 30%. Lasts until cancelled.

**Current behaviour:** While rogue has absorption aura [stealth ](http://wotlk.openwow.com/spell=1784)interrupted by [Consecration](http://wotlk.openwow.com/spell=26573).

**Expected behaviour:** Rogue stealth shouldn't be interrupted until absorbed periodic damage by [Consecration](http://wotlk.openwow.com/spell=26573).

proof: https://youtu.be/EwLOcI4h_kg?t=16m39s

**Steps to reproduce the problem:**

1. Apply [Power Word : Shield ](http://wotlk.openwow.com/spell=17 ) to yourself.
2. Stand on pool [Consecration](http://wotlk.openwow.com/spell=26573).
3. Stealth interrupted.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/5e46bb3e8c352cfa73b074da2608287f6d8f1513

**TDB version:**  TDB 335.62

**Operating system:**  Linux debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Motorheadx** [comment]
Confirm

**Comment by Jildor** [comment]
Only removes when cast Consecration and player has absorption aura with stealth.

But I'm not sure if it's a bug

http://www.arenajunkies.com/topic/133038-druid-stealth-working-differently-than-rogue-stealth/

> Consecrate only pops you out of stealth if you are hit by it when they cast it (caught in the 'wave' it creates..) the first time or it actually ticks and deals damage so that would be a bad example (unless you mean you can pounce for 2 seconds after taking damage which would be extremely weird and far-fetched).

**Comment by Eliminationzx** [comment]
Bump

**Comment by Keader** [comment]
in the end, rogues should lose or not stealth when hitted by AOE spells having Power World Shield?

**Comment by Jildor** [comment]
I still think it works as it should

**Comment by ariel-** [comment]
It works properly. Cast while inside radius it always pops you out of stealth, bubble or not. (in the video you can see the rogue is out of consecrate radius when it's cast)

Inside radius it only pops you out if it deals damage.
