### ISSUE TITLE
[3.3.5] Unchained Magic not working with Arcane Misseles and Penance

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19005]
**Description:** Icecrown Citadel, boss fight: Sindragosa. Unchained Magic does not stack Instability

**Current behaviour:** Casting [Arcane Missiles (spell 42846)](http://wotlk.openwow.com/spell=42846) or [Penance (spell 53007)](http://wotlk.openwow.com/spell=53007)
does not result in "Apply Aura: Proc Trigger Spell [Instability (69766)](http://www.wowhead.com/spell=69766/instability)
as the primary effect of [Unchained Magic (69762)](http://www.wowhead.com/spell=69762/unchained-magic).

**Expected behaviour:** Starting to cast Arcane Missiles or Penance should give 1 stack of Instability.

**Steps to reproduce the problem:**

1. .aura 69762
2. .cast 42846 or .cast 53007 on an enemy target

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  b209353266a86193993d99137351ece9f49b748e

**Comment by ariel-** [comment]
```sql
UPDATE `spell_proc` SET `ProcFlags`=0x15400 WHERE `SpellId`=69762;
```

Needs a little patch in penance script too (else it would trigger twice, one for the dummy spell, the other for the actual heal/damage spell):

```diff
diff --git a/src/server/scripts/Spells/spell_priest.cpp b/src/server/scripts/Spells/spell_priest.cpp
index 86a8c37..4ba3d28 100644
--- a/src/server/scripts/Spells/spell_priest.cpp
+++ b/src/server/scripts/Spells/spell_priest.cpp
@@ -958,9 +958,9 @@ class spell_pri_penance : public SpellScriptLoader
                     uint8 rank = GetSpellInfo()->GetRank();
 
                     if (caster->IsFriendlyTo(unitTarget))
-                        caster->CastSpell(unitTarget, sSpellMgr->GetSpellWithRank(SPELL_PRIEST_PENANCE_R1_HEAL, rank), false);
+                        caster->CastSpell(unitTarget, sSpellMgr->GetSpellWithRank(SPELL_PRIEST_PENANCE_R1_HEAL, rank), TRIGGERED_DISALLOW_PROC_EVENTS);
                     else
-                        caster->CastSpell(unitTarget, sSpellMgr->GetSpellWithRank(SPELL_PRIEST_PENANCE_R1_DAMAGE, rank), false);
+                        caster->CastSpell(unitTarget, sSpellMgr->GetSpellWithRank(SPELL_PRIEST_PENANCE_R1_DAMAGE, rank), TRIGGERED_DISALLOW_PROC_EVENTS);
                 }
             }
 
```

Not pushing right now, opening procflags leaves the window open to many undesired procs, will test some more with other spells

**Comment by DeActiver** [comment]
you are not player for Understanding this is not  referenced #18945 , when you don't know Why should he attempt to justify those procedures pride eyes closed this fix real hard lol
