### ISSUE TITLE
3.3.5] Spell/Mage: Glyph of Icy Veins not work properly with mage wards

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19015]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wotlk.openwow.com/item=42746
>Glyph of Icy Veins:  Your Icy Veins ability also removes all movement slowing and cast time slowing effects.

It works ok for Icy Veins. The problem is that when a mage with Glyph of Icy Veins use Fire Ward or Frost Ward produce the same effect as Icy Veins. Without the glyph both Fire Ward and Frost Ward work ok.

**Current behaviour:** 
Fire Ward or Frost Ward produce the same effect as Icy Veins.

**Expected behaviour:**
Fire Ward or Frost Ward should not produce the same effect as Icy Veins.

**Steps to reproduce the problem:**
1. Mage with slow movement effect uses Fire Ward or Frost Ward.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c2a36c9

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
```sql
UPDATE `spell_proc` SET `SpellFamilyMask2`=0 WHERE `SpellId`=56374;
```

**Comment by Noryad** [comment]
@ariel- it works ok
