### ISSUE TITLE
Core/Spells: inactive spell Fishing [secondary profession]

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19016]
**Description:**  
The spell "Fishing" [Spell ID: 131474] has issues.  

**Current behaviour: (Tell us what happens.)**  

Once you click the spell "Fishing" [Spell ID: 131474] the character doesn't get any response from this spell. In Fact, the character does not throw the bait when you are near the water.  

**Expected behaviour: (Tell us what should happen instead.)**  
Once you are near the water, and you have learned the spell "Fishing" from the profession "Fishing" you should be able to fish by using the spell "Fishing".  

**Steps to reproduce the problem:**  

1. Create any character.  
2. Reach level 5.  
3. Learn the profession "Fishing".  
4. Look for a lake or any place were you can fish.  
5. Use the spell "Fishing".  

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**  

master  

**TC rev. hash/commit:**  787adc24  

**TDB version:**  703.00 + updates

**Comment by Rhisk** [comment]
Confirmed

**Comment by DoctorKraft** [comment]
Create a simple spellscript with cast spell (131476) or directly in spellauraeffect.cpp but it's hacky ^^

**Comment by tkrokli** [comment]
Nice & quick work. Thanks, Shauren 👍
