### ISSUE TITLE
[3.3.5] Spell/Paladin: First Aid not working with Hand of Protection

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#19014]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Hand of protection nullifies First Aid. 
![first aid - hando of protection](https://cloud.githubusercontent.com/assets/23700295/22472380/4d1fa200-e78a-11e6-8fa1-21600869bab2.jpg)

**Current behaviour:** First Aid can not be used with Hand of Protection

**Expected behaviour:** Player should be able to use First Aid under Hand of protection.

**Steps to reproduce the problem:**
1. Paladin casts Hand of Protection.
2. Paladin tries to use [Heavy Frostweave Bandage](http://wotlk.openwow.com/item=34722).

Note that the same occurs with a friendly target.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  c2a36c9

**TDB version:**  62

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
http://wotlk.openwow.com/spell=10278
>Hand of Protection (Rank 3)
A targeted party or raid member is protected from all physical attacks for 10 sec, **but during that time they cannot attack or use physical abilities**. Players may only have one Hand on them per Paladin at any one time. Once protected, the target cannot be targeted by Divine Shield, Divine Protection, or Hand of Protection again for 2 min. Cannot be targeted on players who have used Avenging Wrath within the last 30 sec.

Is first aid a physical ability?

**Comment by Eliminationzx** [comment]
@Noryad , yep its physical.

> Category = 0, SpellIconId = 104, ActiveIconId = 0, SpellVisual = (100, 0)
> SpellFamilyName = SPELLFAMILY_GENERAL, SpellFamilyFlags = 0x00000000 00000000 00000000
> SpellSchoolMask = 1 (SCHOOL_MASK_PHYSICAL, SCHOOL_MASK_ALL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 2 (SPELL_PREVENTION_TYPE_PACIFY)
> Attributes
> Attributes: 0x00000010 (SPELL_ATTR_UNK4)
> AttributesEx1: 0x00004044 (SPELL_ATTR_EX_CHANNELED_1, SPELL_ATTR_EX_CHANNELED_2, SPELL_ATTR_EX_UNK14)
> Advanced info
> Spell Level = 0, BaseLevel 35, MaxLevel 43, MaxTargetLevel 0
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 16 (MECHANIC_BANDAGE)
> SpellRange (Id 11) "Fifteen yards"
> MinRange = 0
> MaxRange = 15
> CastingTime (Id 1) = 0.00
> Duration: ID (31) 8000, 0, 8000
> Interrupt Flags: 0x00000000, AuraIF 0x00000002, ChannelIF 0x00003C0E
> Chance = 101, charges - 0
> Effects
> Effect 0:
> Id: 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 725
> Targets (21, 0) (TARGET_SINGLE_FRIEND, NO_TARGET)
> Aura Id 8 (SPELL_AURA_PERIODIC_HEAL), value = 725, misc = 0 (0), miscB = 0, periodic = 1000
> Effect 1:
> NO EFFECT
> Effect 2:
> NO EFFECT
