### ISSUE TITLE
Ulduar Tram

### ISSUE THREAD

**Issue by sigbinium** [TrinityCore/TrinityCore#19017]
Description: Ulduar Tram to Mimiron does not move.

Current behaviour: Unclickable button unless GM mode is turned on. Once pressed, no tram movement.

Expected behaviour: Tram moves towards Spark of Imagination.

Steps to reproduce the problem:

1.  Head to Tram location, unclickable button unless GM mode is turned on.
2.  Stay in Tram while animation of Tram activation is going on
3.  Tram doesn't budge

Branch: 3.3.5

TC rev. hash/commit: c2a36c9

TDB version: 335.62 + updates

Operating system: Windows

**Comment by Aokromes** [comment]
#17354
