### ISSUE TITLE
SetDisableGravity  , SetCanFly not work

### ISSUE THREAD

**Issue by Xxxhackerxxx** [TrinityCore/TrinityCore#19020]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

When `InhabitType` of creature  is 5 , that means it can have flying and ground movement, but when `SetDisableGravity` and `SetCanFly` are false, the creature can fly again! In the event that it shouldn't fly! it's very important for scripting

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  b209353266a8

**TDB version:**  TDB 335.62

**Operating system:**  Windows Server 2012

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Isn't this just a special case/variant of issue #15247 [**Core/Movement: flying NPCs don't change from flying to walking once on the ground**](#15247) ?

**Comment by Keader** [comment]
Is same issue.
You can control by yourself this flags using extra flag : CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE (512) instead inhabittype.

**Comment by D4R4** [comment]
This issue is causing problems with a number of scripts, 
@Keader can you explain more about how the CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE (512) can be used to replace where 
SetCanFly(false); SetDisableGravity(false); 
and 
SetCanFly(true); SetDisableGravity(true);
is currently used to make a creature both fly and walk during different phases of it's fight?

**Comment by Keader** [comment]
Is not to replace.
When you use ```InhabitType``` fly, core force ```SetCanFly(true);```  and  ```SetDisableGravity(true);``` each update.
When you use ```CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE``` you can control yourself, when SetCanFly and SetDisableGravity will be active or not.

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Creature/Creature.h#L52
```cpp
    CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE = 0x00000200,       // creature won't update movement flags
```

**Comment by D4R4** [comment]
Works like a charm, Cheers

**Comment by tkrokli** [comment]
Glad to hear that. Would you say that your solution is a hack, or is it good enough that it could be suggested as an updated solution for scripts where flight movement control has stopped working?
