### ISSUE TITLE
Start domes of "Eye of the storm" Battleground.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19028]
**Description:**  Start domes in "Eye of the Storm" Battleground

**Current behaviour:**  
The domes are in a bad position and this lets the players go outside of the start area before battle starts.
Alliance dome [Forcefield 000]:id 184719  
Horde dome [Forcefield 001]:id 184720  

**Expected behaviour:**  
The domes should keep the players in the starts zones until the battle starts.

**Steps to reproduce the problem:**  

1. Create a character
2. Reach a level which is required by the battleground "Eye of the Storm"
3. Select the battleground Eye of the Storm in the PvP UI and see the domes' behaviour.

**Branch(es): 3.3.5 / master (Tell us which branch(es) this issue affects.)**  
Master  

**TC rev. hash/commit:**  787adc24   

**TDB version:**  703.00 + updates

**Comment by Rhisk** [comment]
Confirmed

**Comment by Aokromes** [comment]
very likely the Z coordinates are the same has the old EotS.
