### ISSUE TITLE
[335] Stair of Destiny (Outland) No NPC Battle

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#19032]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Stair of Destiny (Outland) No NPC Battle

**Current behaviour:**

When you go through the Dark Portal into Outland, the Alliance / Horde NPCs are not engaged in battle with the Pit Commander and his demons.

In order to get them to fight, the player has to aggro them and run back behind the defending line. At this point the Alliance / Horde NPCs will engage.

**Expected behaviour:**

The Alliance / Horde NPCs should engage in battle with the Pit Comander and his demons without the need of the player to aggro them first.

**Steps to reproduce the problem:**

1. Go through the portal
2. Look at everyone doing nothing
3. Aggro some demons
4. Look at everyone fighting

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c2a36c9e89c7cbd638b74334adf1b31acc97af44

**TDB version:**  TDB_full_world_335.61_2016_04_11 + Updates

**Operating system:**  WinXP / Win7

**NOTES:**

* This appears to be a spawn issue. The demons are clumped together at the bottom of the stairs, too far away from the defenders to aggro them.
* Perhaps a separate issue but the Pit Commander went down very fast when battling a single NPC Mage (damn Mages always OP). Perhaps his armor / HP stats are too low?

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Kittnz** [comment]
This is weird, because it did work a month ago. I wonder what changed.

**Comment by Tauriella** [comment]
Is this the same Issue ?

https://github.com/TrinityCore/TrinityCore/issues/18309

**Comment by Killyana** [comment]
Cannot reproduce on rev. c2a36c9e89c7

**Comment by Kittnz** [comment]
It could get stuck if the area is not active after a while

**Comment by MrSmite** [comment]
I think it may be similar to the issue mentioned by Tauriella but in my case I had never been to Outland.

I started the server, created a new character, used the GM command to level it up and went through the portal in Blasted Lands. Once on the other side, there was no battle, it appears as if the demons are spawned too far from the stairs. I pulled a bunch of them but the Pit Commander never aggro'd until I actually shot him.

**Comment by Killyana** [comment]
Npcs spawns from portals then moves to the stairs, just wait 5 min and you will get: http://i.imgur.com/im72RTg.jpg
Also they are active so no need for anyone to be present.

**Comment by MrSmite** [comment]
> Npcs spawns from portals then moves to the stairs, just wait 5 min and you will get:

Strange, I don't get that. The only NPCs that spawn and fight are a few *Infernal Seigebreaker* and they die quickly. The *Pit Commander* and his demons never move from the big "gate" that he's standing in.

**Comment by Killyana** [comment]
Infernals are summoned by the Pit Commander, if he's not there it's impossible de get them there.
You're probably using an other script.

**Comment by MrSmite** [comment]
> Infernals are summoned by the Pit Commander, if he's not there it's impossible de get them there.
> You're probably using an other script.

No, I'm not using any custom scripts. I just don't have the same battle as in your screenshots. The only NPCs that fight are the Infernals because they spawn right on top of the other NPCs. The other demons never engage.

**Comment by Kittnz** [comment]
I think it's because of the set home in the script.
