### ISSUE TITLE
[3.3.5] Extra lashtails in Barrens 

### ISSUE THREAD

**Issue by r00ty-tc** [TrinityCore/TrinityCore#19045]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

While looking at some videos of the game, on the subject of pooling. This one in particular at around this point:

https://youtu.be/xyhkTcJuOoE?t=168

There are some extra lashtails in the Barrens that don't belong there, for sure you would really not see them spawned like this in reality. As seen here:

![image](https://cloud.githubusercontent.com/assets/173349/22623241/00f124ca-eb4b-11e6-850d-09ff5aaedb6a.png)

The one that belongs can be seen to be roaming, the other 3 are static. The one that belongs is spawnId: 19816.

Those that don't are: 40493, 49495, 49496.

There is also another static one added 40494:

![image](https://cloud.githubusercontent.com/assets/173349/22623250/904540b6-eb4b-11e6-9c44-cb6f26565d5a.png)

I can't say whether that one belongs or not. For sure it shouldn't be static.

Soliciting opinion before I remove them/enable movement on the last one.

**Current behaviour:** (Tell us what happens.)
Too many lashtails.

**Expected behaviour:** (Tell us what should happen instead.)
Not so many lashtails.

**Steps to reproduce the problem:**

1. .go creature 40493
2. Observe extra lashtails
3. ?????
4. Profit

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
e991a15dd7cbf5ba374f8942b7ea88f3a4d7b365

**TDB version:**  
TDB_full_world_335.62_2016_10_17 + as per hash above.

**Operating system:**  
Linux

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Staleness89** [comment]
The same issue exists in at least a few other places that I've seen..can't think of them right now though.

**Comment by r00ty-tc** [comment]
There's quite a few improperly static around. I noticed it way back when making the original pooling update. I remade Deathknell in pooled spawns. I noticed lots weren't moving, when they most certainly should have.

Most of the time though I think it's down to people catching genuine spawn spots. If you look at random roam there's often long pauses. Probably the did a drive by sniff, picked up spawn points. No movement, assumed static spawn and that's how it was logged.

In this case though it looks like perhaps the sames spawn point was picked up multiple times at different static locations.

**Comment by Kittnz** [comment]
Don't forget some of these are spawned by hand and other from sniffs. (Back in mangos days). Like staleness said it is everywhere.. but over the years iv seen it less and less because we respawning the area.

**Comment by Smileynator** [comment]
Most static creatures i saw in barrens are roaming groups that are missing paths. Much like i saw gazelles. And wooly kodo. I made open issues for this as well. I can assume there as a moving group of raptors for sure. Nobody has a sniff of their paths though.

**Comment by MrSmite** [comment]
You have to consider skinned mobs. The YouTube video may not have them because they were previously killed and skinned so the corpse is gone and they may have not respawned yet.

**Comment by Smileynator** [comment]
Note that this might also be something altered with pooling. There was a post regarding mining notes previously, basically it needs a script to keep population in check, both minimum and maximum wise. It will need a lot of data to accurately do it like blizzard does though, and we do not yet know if there is a global static timer or amount per herd, but it sounds promising for cases like this.

**Comment by Kittnz** [comment]
After they are skinned, wouldn't the mob despawn instantly after it?

**Comment by r00ty-tc** [comment]
Well, my point was that it's highly unlikely they would be spawned so close together on retail (raptors were generally a rarer spawn in barrens compared to others). Also that they were 3 spawned together and not moving seemed odd.

**Comment by Kittnz** [comment]
Well if you spawn from a sniff and it was killed 3 times, it will be spawned somewhere 3 times. Then cleanup has never been done in most zones.

**Comment by r00ty-tc** [comment]
Yeah, the one time I added some spots to ghostlands, I made a query to only include those more than 20 or so yards from any other spot.

For sure in pooled spawns we should have some sanity check on possible spawn locations, some minimum distance before adding the spots to DB.
