### ISSUE TITLE
[3.3.5] Silithid Grub Behaviour

### ISSUE THREAD

**Issue by Smileynator** [TrinityCore/TrinityCore#19053]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The Silithid grub persumably hatches from the eggs placed by Silithid creatures in the barrens. http://wowwiki.wikia.com/wiki/Silithid_Grub 
It is unknown if they are even supposed to spawn on their own. (It is assumed that they do not)
They in fact do not spawn from these eggs (The eggs are spawned from Silithid creeper as described here in comments with their spawn behaviour: http://www.wowhead.com/npc=3250/silithid-creeper#comments )
Additionally they also die when they lose aggro. Although this may be accurate due to how they spawn. It might be better for them to simply despawn (Since corpses walking back to their original location and then disappearing are just disturbing in general)
**Current behaviour:** (Tell us what happens.)
The eggs get layed but no Grub spawns.
The Grubs are just "around" presumably an error, and have odd behavior upon losing aggro.
**Expected behaviour:** (Tell us what should happen instead.)
The eggs should instead spawn grubs when not killed fast enough. (No timer for that is known)
And the grubs despawn should probably just be a despawn, not a death followed by walking back to original aggro location as a corpse.
**Steps to reproduce the problem:**

1. Go to the southern barrens part. 
2. Attack Silithid and see eggs spawn from them during combat/upon death. But do nothing if left alone.
3. Aggro some Grubs and walk away, see what happens to them.

**Branch(es):** 3.3.5 Only

**TC rev. hash/commit:**  
39b20b4431a1a67446e9cc4c2221fd42cc907291
**TDB version:**  
TDB 335.62 + updates up to and including 2017_01_17_00_world.sql
**Operating system:**  
Windows 7

P.S. Do you hate these "issues" yet? I can stop. But you can mark them low Priority either way.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#7251
