### ISSUE TITLE
[3.3.5] NPC Missing path - Wooly Kodo & herd.

### ISSUE THREAD

**Issue by Smileynator** [TrinityCore/TrinityCore#19051]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The mob: http://www.wowhead.com/npc=3237/wooly-kodo#comments [Wooly Kodo](http://wow.gamepedia.com/Wooly_Kodo) is found with it's partner [Greater Barrens Kodo](http://wow.gamepedia.com/Greater_Barrens_Kodo) in Barrens [Southern Gold Road](http://wow.gamepedia.com/Southern_Gold_Road) (they are spawned there). According to documentation they are supposed to have a patrol path, yet we have no data on what that path was. I recall them randomly going about the general area in a herd, possibly with some normal kodos in tow.

**Current behaviour:** (Tell us what happens.) Kodos are standing still (don't even wander randomly)

**Expected behaviour:** (Tell us what should happen instead.)
Kodos should have a path to walk about the general kodo area. (Not sure if anyone has data on these paths.)

**Steps to reproduce the problem:**

1. Follow the Southern Gold Road southwards past Camp Taurajo
2. Observe the pack of kodos on the side of the road

**Branch(es):** 3.3.5 Only

**TC rev. hash/commit:**  39b20b4431a1a67446e9cc4c2221fd42cc907291

**TDB version:**  TDB 335.62 + updates up to and including 2017_01_17_00_world.sql

**Operating system:**  Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Very low chances to find sniffs with pathing for those creatures, since they were removed in patch 4.0.3a.
There are also quite a few other Barrens creatures missing their pathing info. A bit difficult to decide what to do about them, because it is hard to find reliable documentation of where their pathing used to be.

**Comment by Smileynator** [comment]
Yeah, in more locations then just barrens as well i suppose. Here was a patch of gazelles facing the same issue: http://puu.sh/tPR7w.png

If we had any wowhead like movement data we could do something regarding them.
For those we don't i suppose we must either bundle memories of people that somehow recall where they saw them. or just make something "good enuf". In these cases, making the kodos walk through the kodos infested area would probably do it. And the gazelles in the plane just act like gazelles (not crossing human walked paths, just skipping through flat plane in a circle or such)

I realize these are hard things to get something solid on, and these issues are more of a "acknowledgement of missing data" that in case someone has data, we can fill or correct it. Does that make sense? If they just bulk up and we never find the data, i suppose we need to use what i described above or just remove them altogether (I wouldn't want that). Neither is ideal.

**Comment by offl** [comment]
> If we had any wowhead like movement data we could do something regarding them.

> [3235](https://web.archive.org/web/20100421062945/http://www.wowhead.com/npc=3235)
{ count: 73, coords: [[44.3,60.8],[44.3,61.5],[44.3,77.1],[44.4,75.5],[44.4,80],[44.5,61.5],[44.7,75.9],[44.7,76.5],[44.8,74.8],[45,78],[45.1,63.1],[45.1,79.1],[45.2,63.6],[45.2,64.5],[45.2,73.3],[45.3,61.2],[45.3,73.6],[45.4,65.7],[45.4,66.9],[45.4,72.2],[45.5,64.3],[45.5,66],[45.5,66.5],[45.7,67.6],[45.7,71.9],[45.7,72.8],[45.8,62.7],[45.8,68.6],[45.8,70.9],[45.9,62.3],[46.1,60.9],[46.1,73.5],[46.1,74.5],[46.4,70],[46.5,70.8],[46.5,72.8],[46.7,67.8],[46.7,68.9],[46.7,70.3],[46.7,71.8],[46.8,74.4],[46.9,67],[47,80.3],[47.2,74.6],[47.3,66.1],[47.3,81.5],[47.5,65.2],[47.5,65.8],[47.5,79.8],[47.6,81.2],[47.6,82.5],[47.7,81.8],[47.8,79.3],[48,75.3],[48.2,63.6],[48.3,60.8],[48.3,62.8],[48.4,75.6],[48.5,60.7],[48.6,62.7],[48.7,59.9],[48.8,56.3],[48.8,61.7],[48.8,76.4],[48.8,76.5],[48.8,78.8],[48.9,56.5],[49,78.2],[49.1,59.4],[49.2,57.8],[49.5,59],[49.7,57.9],[49.8,59.7]] }

>[3236](https://web.archive.org/web/20100421062945/http://www.wowhead.com/npc=3236)
{ count: 82, coords: [[44,61.6],[44.3,77.1],[44.4,75],[44.4,79.9],[44.6,75.5],[44.7,61.5],[44.7,74.5],[44.7,76.7],[44.7,79.5],[45,79.1],[45.2,63.9],[45.2,65.4],[45.3,48.2],[45.3,61.2],[45.3,66.5],[45.3,78.3],[45.4,63.3],[45.4,65.5],[45.4,72],[45.4,73],[45.4,74],[45.5,66.5],[45.6,66.3],[45.6,68.6],[45.7,48],[45.7,62.9],[45.8,68.3],[45.8,70.9],[45.9,62.3],[46,61.4],[46,74.1],[46.1,73.3],[46.1,74.5],[46.2,49.5],[46.2,53.9],[46.2,56.3],[46.3,72.2],[46.4,53.4],[46.4,70],[46.5,70.6],[46.5,73.2],[46.7,68.3],[46.7,69.9],[46.7,72.3],[46.8,67.1],[46.8,69.4],[47,74],[47.3,56],[47.4,51.3],[47.4,65.8],[47.4,75],[47.4,80.1],[47.5,65.5],[47.6,81.7],[47.7,80.9],[47.7,82.6],[47.8,79.6],[48,64.1],[48,64.7],[48.1,76.1],[48.1,79.3],[48.2,75.3],[48.3,62.8],[48.4,60.9],[48.4,61.8],[48.5,63.5],[48.6,60.5],[48.7,62.9],[48.8,56.6],[48.8,62.3],[48.8,76.4],[48.8,77],[48.8,78.8],[48.9,56.2],[49,78.2],[49.1,57.9],[49.1,59.4],[49.2,59.5],[49.5,59.1],[49.8,57.9],[49.8,59.7],[51.7,66.1]] }

>[3237](https://web.archive.org/web/20100421062945/http://www.wowhead.com/npc=3237)
{ count: 74, coords: [[19.3,17.5],[44.2,61.1],[44.3,79.9],[44.4,61.6],[44.4,75.2],[44.7,75.6],[44.7,79.5],[44.8,61.6],[45,61.2],[45,73.4],[45,77],[45.1,74.5],[45.2,78.9],[45.3,63.6],[45.3,65.4],[45.3,77.6],[45.4,63.3],[45.4,66],[45.4,67.1],[45.4,71.8],[45.4,73.6],[45.5,63],[45.5,64.5],[45.5,66.4],[45.6,67],[45.7,61.2],[45.7,69.4],[45.8,69.7],[45.8,71.5],[45.9,68.4],[46,70.5],[46.1,61.8],[46.1,74.4],[46.1,74.6],[46.2,73.3],[46.5,71.1],[46.7,68],[46.7,68.9],[46.7,72.2],[46.7,72.7],[46.8,69.5],[47,66.9],[47.2,65.2],[47.2,66.4],[47.3,74.4],[47.3,81.6],[47.4,74.8],[47.4,80.1],[47.5,65.5],[47.5,79.4],[47.5,80.3],[47.5,81.1],[47.7,82.5],[48,64.5],[48,75.4],[48.1,63.7],[48.3,63.3],[48.3,75.7],[48.5,60.8],[48.5,61.5],[48.7,79],[48.8,56.2],[48.8,57.4],[48.8,76.4],[48.8,77.1],[48.9,62.6],[48.9,78],[49,57.5],[49,59.6],[49.1,59.2],[49.7,58.7],[49.8,58.1],[49.8,59.7],[78.5,69.2]] }

**Comment by Rushor** [comment]
cmangos has some datas for the gazelles, i will post them later

**Comment by Smileynator** [comment]
Another barens character would be Hezrul Bloodmark > http://www.wowhead.com/npc=3396/hezrul-bloodmark
Appearently he still exists, but he used to have a path around wailing caverns, where he and his underlings are now just spawned static, unmoving.

**Comment by Rushor** [comment]
also have paths for him, bumb me if i forget to push the fix for it in a week

**Comment by MrSmite** [comment]
> A bit difficult to decide what to do about them, because it is hard to find reliable documentation of where their pathing used to be.

We already have a `VerifiedBuild 12340` in `creature_template`, why not use that style of notation?

Adding this to the `waypoints` table and using a value of 0 for *custom* would allow people to fix these type of incidental issues. For creatures that don't affect a quest or a script it seems harmless.

**Comment by Staleness89** [comment]
In addition to Herzul Bloodmark there are other kolkar mobs that need to be linked to the packhounds near them, and judging by some of their positions they may need waypoints as well.

**Comment by Rushor** [comment]
see https://github.com/cmangos/tbc-db/blob/cff248f0b40e2d22100d18062a74eb91ff829e6c/Updates/SpinOnTop/182_movementBackport.sql#L1005

**Comment by MrSmite** [comment]
> Adding this to the waypoints table and using a value of 0 for custom would allow people to fix these type of incidental issues. For creatures that don't affect a quest or a script it seems harmless.

Actually, giving this further thought, it might be easier to simply have a separate table given that a path can have many waypoints. It seems like wasted data to have a `VerifiedBuild` field for every point on the path. unless you want people to be able to add unverified points to a verified path.

This seems like a better option in terms of space:

`waypoints_verifiedbuild`.`pathId`
`waypoints_verifiedbuild`.`VerifiedBuild`

**Comment by offl** [comment]
Fixed in 50ef255846bb336ebad4c7fea08982a498d8b31d
