### ISSUE TITLE
[Master] Crash AuraEffect::HandlePlayScene

### ISSUE THREAD

**Issue by vinin80** [TrinityCore/TrinityCore#19050]
**Description:**

Crash like 5-10 mins, here is crashlog:

http://pastebin.com/BahzWAhQ

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 

master

**TC rev. hash/commit:**  787adc2

**Operating system:**  Linux Debian

**Comment by tkrokli** [comment]
@vinin80 : Why did you close this issue? We usually don't close issues without a good reason for why it was closed.
