### ISSUE TITLE
[3.3.5] Spell/Warlock: Improved Drain Soul not work properly

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19068]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wotlk.openwow.com/spell=18372
>Improved Drain Soul (Rank 2): **Returns 15% of your maximum mana** if the target is killed by you while you drain its soul. In addition, your Affliction spells generate 20% less threat.

**Current behaviour:** 
Improved Drain Soul not returning a % of your maximum mana.

**Expected behaviour:** 
Improved Drain Soul should return a % of your maximum mana.

**Steps to reproduce the problem:**
1. Kill a target under effects of Drain Soul.
2. No mana gain.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c6060dd

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Fix

```
-- Drain Soul
DELETE FROM `spell_proc` WHERE `SpellId`=-1120;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(-1120, 0, 0, 0x00000000, 0x00000000, 0x00000000, 0, 0x1, 0x2, 0x0, 0x2, 0, 0, 0, 0);
```

**Comment by Noryad** [comment]
Maybe with this is enough


```sql
-- Drain Soul
UPDATE `spell_proc` SET `SpellPhaseMask` = 0x2, `AttributesMask` = 0x0 WHERE `SpellId` = -1120;
```

**Comment by ccrs** [comment]
@ariel- In the original commit months ago I had this working, iirc u changed something in the next weeks. Time to check commit logs xD

**Comment by ariel-** [comment]
Yeah, it is weird.. crazy spells
