### ISSUE TITLE
[3.3.5] Achievements: progress not given

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#19064]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Seems like recent changes to achievement system broke achievs like 
http://www.wowhead.com/achievement=557/superior

**Steps to reproduce the problem:**

1. create a character
2. give items

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  
c6060dd0c511ddad3cb1f0423aa9ccf2de7aedec

**Comment by Aokromes** [comment]
I vote https://github.com/TrinityCore/TrinityCore/commit/7c7b877c3fc0292f33f54f4e8b514be3bf8514a6

**Comment by Feedcode** [comment]
@ccrs Can confirm, giving items with needed itemlevel does not grant achievements.
@Aokromes I did revert it completely, still the same, no achievemnt. I guess the error is in another commit.

**Comment by Viste** [comment]
@Aokromes don't have that commit in source and the same 
[url=http://radikal.ru/big/avsuoqyw3ajqk][img]http://s05.radikal.ru/i178/1702/0e/75c685ea3f6ft.jpg[/img][/url] green item's on character added in past so it works
i think its 9b44ed9cda347bfda1078666b3779d985fc37b2b

**Comment by ariel-** [comment]
9b44ed9cda347bfda1078666b3779d985fc37b2b broke it, by inverting miscvalues passed in ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM (which superior and epic achievements use)
