### ISSUE TITLE
Boss Maiden of Virtue is missing melee attack animation

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#19061]
**Description:** The boss [Maiden of Virtue](http://wotlk.openwow.com/npc=16457) does not show any melee attack animation

**Current behaviour:** Boss attacks do damage, but she doesn't do the melee attack animation.

**Expected behaviour:** Maiden of Virtue should show melee attack animation during the fight,

**Steps to reproduce the problem:**

1. `.go crea id 16457`
2. Start the fight.
3. Notice that there is no melee attack animation.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  d06391d0628ffbf43da471c83653853b0926b4ab

**TDB version:**  335.62

**Comment by Aokromes** [comment]
#11854 ?

**Comment by Killyana** [comment]
Try: .morph 16198 unequip both hand and attack any npc you will see you character will not play any attack animation. If you equip any weapon it will play the animation.

**Comment by Killyana** [comment]
I checked sniffs, the boss doesn't have any equipments, and whatever the value in bytes2 the melee animation is never played.

**Comment by illfated** [comment]
That is a bit odd. Do the melee attacks need to be spells, instead of unarmed attacks, to trigger animation?

**Comment by Killyana** [comment]
It's a client issue, this model  cannot play the emote ONESHOT_ATTACKUNARMED

**Comment by offl** [comment]
Not a bug
TBC https://www.youtube.com/watch?v=tTFAx5_a8hY
WotLK https://youtu.be/AT-bAMTxi5I?t=147
The video was uploaded on Nov 23, 2010 and 3.3.5a was released on June 29, 2010
Cataclysm was released on December 7, 2010

The animation is missing even in 2009 https://www.youtube.com/watch?v=LR5ucl4NcpI

**Comment by Jildor** [comment]
Yep, seems blizzlike client bug, if you get any of custom client with npc textures > 335 you can see maiden melee attack.
