### ISSUE TITLE
[7.x] Areatrigger system

### ISSUE THREAD

**Issue by cocolino** [TrinityCore/TrinityCore#19078]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** There are a couple of issues in the Areatrigger system (implemented in 6ab3877c91c9440b81cf1c7c66a1275ee04ea26a).

**Current behaviour:** (Tell us what happens.)

Tested with AreaTrigger "Rain of Fire" - Teron'gor (156857).

Added:
```sql
DELETE FROM `areatrigger_template` WHERE `Id`= 6422;
INSERT INTO `areatrigger_template` (`Id`,`Type`,`Flags`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`VerifiedBuild`) VALUES
(6422, 0, 0, 10, 10, 0, 0, 0, 0, 23420);

DELETE FROM `spell_areatrigger` WHERE `SpellId`= 156857;
INSERT INTO `spell_areatrigger` (`SpellId`,`AreaTriggerId`,`MoveCurveId`,`ScaleCurveId`,`MorphCurveId`,`FacingCurveId`,`DecalPropertiesId`,`TimeToTarget`,`TimeToTargetScale`,`VerifiedBuild`) VALUES
(156857, 6422, 0, 0, 0, 0, 0, 0, 8000, 23420);
```
Ingame / on debugging + compared to sniff data the following issues appear:

1. At creation, the Areatrigger internal Id should be used instead of the MiscId, which is used currently.
This can be seen in the below sniff snippet:
```
[0] UpdateType: CreateObject2
[0] Object Guid: Full: 0x3430A093C00645800045D3000018F55C AreaTrigger/0 R3112/S17875 Map: 1182 Entry: 6422 Low: 1635676
```
2. In the sniffs all Areatriggers use the following stuff which is not handled currently:
```
[0] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
[0] AREATRIGGER_EXTRA_SCALE_CURVE + 6: 1/1.401298E-45
```

I am not sure if that float and int mean something separate but it's weird that all AT's have this stuff.

3. The Areatrigger does not visually display properly. Instead of showing meteors rain from the sky, only a small yellowish thing appears on the ground. Picture: https://imagebin.ca/v/3BiMKcDT5iSq

**Expected behaviour:** (Tell us what should happen instead.)

Apart from 1 and 2 which are just things I saw and reported, point 3 is the actual issue (missing visuals on certain AT's). They should display properly. The closest thing to them is a persistent area aura that spawns dyn objects (as far as what they look like), but there is no dyn object or any other stuff seen in the sniffs. Also, no other opcodes are sent regarding this Areatrigger on creation, and the create block looks largely the same. Picture: https://imagebin.ca/v/3BiMfDoR2fh6

**Steps to reproduce the problem:**

Described above.

**Branch(es):** 7.x (master)

**TC rev. hash/commit:**  bc623ed97fbe38ec0119d075f506ead42b45804c

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by matukaa** [comment]
2 and 3 are directly related. in cases when AreaTrigger has dynamic shape, you MUST set extra scale curve + 5 and +6 in order for the areatrigger to appear. otherwise there will be no animation (or something very basic, sketchy)
Also, in +5 1065353217 is not 1 in float, but 1.0000001f (as of now I don't fully know why is it exactly THAT value, but I do know that without it, the vast majority of the areatriggers will not have a proper visual)

**Comment by Skizooo** [comment]
@matukaa  thank you very much for your detailed explanation, that helps me a lot.

**Comment by matukaa** [comment]
@Skizooo you're very welcome. there are quite a lot of new fields, mechanics that are just not yet implemented, but hopefully time'll change that

**Comment by cocolino** [comment]
@matukaa I had already tried it but with 1.0f and 1, and it wasn't working, nice catch on the 1.0000001f 👍 . This isn't i think related just to those having a dynamic  shape, both it and 156974 use the same AT id and have `[0] HasDynamicShape: False` . Also, something new i have seen different, they all start at time since creation 1ms : `[0] ElapsedMs: 1`.

**Comment by joschiwald** [comment]
@cocolino your sql is invalid, we don't have spellid in spell_areatrigger table

about point 1: invalid, we use areatrigger entry and not miscid, see https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/AreaTrigger/AreaTrigger.cpp#L94

about point 2 and 3: @matukaa said enough, and i still don't know what blizz is sending there, some values have 2 int16 inside

**Comment by cocolino** [comment]
@ joschiwald Yes my bad, posted parser retrieved data (no client files available for direct miscid retrieval).

Here is something a lot more interesting i found though:

TimeToTarget and Duration should be calculated based on total spline length for AT's that move.

If you look at these 2 consecutive packets you can see exactly what happens:

1.
[2] AREATRIGGER_DURATION: 7761/1.087548E-41
[2] AREATRIGGER_TIME_TO_TARGET: 7761/1.087548E-41
[2] AREATRIGGER_TIME_TO_TARGET_SCALE: 10000/1.401298E-41
[2] AREATRIGGER_SPELLID: 157793/2.211151E-40

2.
[2] AREATRIGGER_DURATION: 7759/1.087267E-41
[2] AREATRIGGER_TIME_TO_TARGET: 7759/1.087267E-41
[2] AREATRIGGER_TIME_TO_TARGET_SCALE: 10000/1.401298E-41
[2] AREATRIGGER_SPELLID: 157793/2.211151E-40

I found that AREATRIGGER_TIME_TO_TARGET_SCALE is always given the value of the full duration of the spell (see http://www.wowhead.com/spell=157793/arcane-bomb - Duration 10 seconds), while AREATRIGGER_DURATION and AREATRIGGER_TIME_TO_TARGET are used based on the AT having movement spline points or not.
- If the AT is static, AREATRIGGER_TIME_TO_TARGET doesn't appear in the sniff, and AREATRIGGER_DURATION reflects the total duration of the spell aswell.
- If the AT has movement, the two fields are calculated on creation based on the total spline distance (distance to the end spline point) and the total spell duration - meaning the AT speed. At each update tick, the two fields are then adjusted to reflect the position change of the AT compared to the spline end point. When the AT reaches the last spline point, it must expire and get removed.

What this means is that DB fields should not be used for setting AREATRIGGER_TIME_TO_TARGET / AREATRIGGER_TIME_TO_TARGET_SCALE, since the first is dynamic and the second is always a reflection of the total spell duration. 
Also, _UpdateDuration should also change AREATRIGGER_TIME_TO_TARGET, or they both should be moved to a better place or handled differently in AreaTrigger::Update. It seems normal they are connected if an AT must move to a spot and despawn after reaching it. Note: this will need special duration addition handling for path recalculations where the AT should also return back to the caster instead of despawning, such as Divine Star.
Last, AreaTriggerReShape should not be sent to init spline movement, because if the block in BuildMovementUpdate is fine the client handles it by himself and starts the AT movement clientside. We just have to mimic it serverside. Also, AreaTriggerReShape is not sent when the destination is reached unless new points are given for path recalculation. Blame the diff if you want, but it would be more fair to call the reshape as repath and the other way around. I changed them like this to reflect what they should do better:

    SMSG_AREA_TRIGGER_RE_PATH                                      = 0x2638,
    SMSG_AREA_TRIGGER_RE_SHAPE                                     = 0x263C,

And there are also

    SMSG_AREA_TRIGGER_MOVEMENT_UPDATE                    = 0x263B,
    SMSG_AREA_TRIGGER_POSITION_UPDATE                        = 0x263A,

Which are sent on creation / position reached and signal different things i haven't fully figured out yet.

**Comment by joschiwald** [comment]
Most things are implemented like you descripted

**Comment by DoctorKraft** [comment]
```
[1] OBJECT_FIELD_SCALE_X: 1065353216/1
[1] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
```
1065353216 + 1 = 1065353217

Hm ? It's odd this value so close

**Comment by Traesh** [comment]
@DoctorKraft Found some AT where AREATRIGGER_TIME_TO_TARGET_EXTRA_SCALE isn't set but +6 changed, will need to check it ^^

Added default value in https://github.com/TrinityCore/TrinityCore/pull/19171 to fix most of visuals

**Comment by DoctorKraft** [comment]
no `AREATRIGGER_OVERRIDE_SCALE_CURVE + 6` ?

It's really strange, look this

```
[5] OBJECT_FIELD_TYPE: 257/3.601337E-43
[5] OBJECT_FIELD_ENTRY: 10470/1.467159E-41
[5] OBJECT_FIELD_SCALE_X: 1065353216/1
[5] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
[5] AREATRIGGER_EXTRA_SCALE_CURVE + 6: 1073741831/2.000002
[5] AREATRIGGER_CASTER: 149068817/1.363857E-33
[5] AREATRIGGER_CASTER + 3: 135550976/4.464057E-34
[5] AREATRIGGER_DURATION: 2792/3.912425E-42
[5] AREATRIGGER_TIME_TO_TARGET_SCALE: 2792/3.912425E-42
[5] AREATRIGGER_SPELLID: 201467/2.823154E-40

[7] OBJECT_FIELD_TYPE: 257/3.601337E-43
[7] OBJECT_FIELD_ENTRY: 10470/1.467159E-41
[7] OBJECT_FIELD_SCALE_X: 1065353216/1
[7] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
[7] AREATRIGGER_EXTRA_SCALE_CURVE + 6: 1/1.401298E-45
[7] AREATRIGGER_CASTER: 149068817/1.363857E-33
[7] AREATRIGGER_CASTER + 3: 135550976/4.464057E-34
[7] AREATRIGGER_DURATION: 2234/3.130501E-42
[7] AREATRIGGER_TIME_TO_TARGET_SCALE: 2234/3.130501E-42
[7] AREATRIGGER_SPELLID: 201467/2.823154E-40
```

it's same AT with same caster only the duration change but `AREATRIGGER_EXTRA_SCALE_CURVE + 6` have value `1` for one and other `1073741831`

**Comment by Traesh** [comment]
First value is a float, it's "2.000002", the second one is treated as an int by WPP and output 1

But it seem to be a dynamical value, shouldn't be sniffed

**Comment by DoctorKraft** [comment]
I have found

[Metamorphosis](http://www.wowhead.com/spell=162264/metamorphosis) + [Fury of the Illidari](http://www.wowhead.com/spell=201467/fury-of-the-illidari)
**when you cast Metamorphosis your model change and the visual is bigger**
```
[5] OBJECT_FIELD_TYPE: 257/3.601337E-43
[5] OBJECT_FIELD_ENTRY: 10470/1.467159E-41
[5] OBJECT_FIELD_SCALE_X: 1065353216/1
[5] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
[5] AREATRIGGER_EXTRA_SCALE_CURVE + 6: 1073741831/2.000002
[5] AREATRIGGER_CASTER: 149068817/1.363857E-33
[5] AREATRIGGER_CASTER + 3: 135550976/4.464057E-34
[5] AREATRIGGER_DURATION: 2792/3.912425E-42
[5] AREATRIGGER_TIME_TO_TARGET_SCALE: 2792/3.912425E-42
[5] AREATRIGGER_SPELLID: 201467/2.823154E-40
```

[Fury of the Illidari](http://www.wowhead.com/spell=201467/fury-of-the-illidari)
**normal model**
```
[7] OBJECT_FIELD_TYPE: 257/3.601337E-43
[7] OBJECT_FIELD_ENTRY: 10470/1.467159E-41
[7] OBJECT_FIELD_SCALE_X: 1065353216/1
[7] AREATRIGGER_EXTRA_SCALE_CURVE + 5: 1065353217/1
[7] AREATRIGGER_EXTRA_SCALE_CURVE + 6: 1/1.401298E-45
[7] AREATRIGGER_CASTER: 149068817/1.363857E-33
[7] AREATRIGGER_CASTER + 3: 135550976/4.464057E-34
[7] AREATRIGGER_DURATION: 2234/3.130501E-42
[7] AREATRIGGER_TIME_TO_TARGET_SCALE: 2234/3.130501E-42
[7] AREATRIGGER_SPELLID: 201467/2.823154E-40
```

**Comment by DoctorKraft** [comment]
yeah sorry, i confirm it's totally dynamic. I don't have same value for same AT. Your PR with `AREATRIGGER_EXTRA_SCALE_CURVE + 5 / +6` it's perfect for visual

**Comment by Nyr97** [comment]
Invalid. As of today, scale curve is already implemented in the new areatrigger system.

**Comment by Aokromes** [comment]
more than invalid, outdated
