### ISSUE TITLE
[3.3.5] Auras aren't removed during evade.

### ISSUE THREAD

**Issue by Afgann** [TrinityCore/TrinityCore#19071]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Bosses keep all auras on them when entering evade mode.
**Expected behaviour:** (Tell us what should happen instead.)
Bosses should remove auras on evade.
**Steps to reproduce the problem:**

1. Engage boss.
2. Force boss into evade mode.

More information in https://github.com/TrinityCore/TrinityCore/pull/19013

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
00889ba
**TDB version:**  
TDB_full_world_335.62_2016_10_17 + updates
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ccrs** [comment]
invalid, in that PR u are overriding the default behaviour. Check ````_EnterEvadeMode()````

**Comment by sirikfoll** [comment]
I think every boss with _DespawnAtEvade was done like that, RemoveAllAurasOnDeath() is the responsable for cleaning the auras there.

Anyway, the bug reported here is a visual one, the aura is removed, you can check by .list auras or with a me->HasAura(), but the visual remains on the boss, no idea why tho..

**Comment by Keader** [comment]
It should be handled by RemoveAurasOnDeath...

**Comment by Treeston** [comment]
GUID re-use causes this bug. Despawned mob GUID is reused, client re-uses cached auras.

Easy fix: DYNSPAWN PLS

**Comment by r00ty-tc** [comment]
In theory, I guess if you removed the auras while the creature was visible to client, before despawning. In theory, it would remove them from the local cache too. No?

Not that I'm saying we shouldn't use dynamic spawn. Just saying for this there is a workaround. :P

A lot of weird things happen because of the re-use of guids though.

**Comment by Treeston** [comment]
Yes, but that'd be a ton of extra work for something that'll be superfluous in a few weeks.

**Comment by r00ty-tc** [comment]
In a few weeks? Such optimism! So far it's gone like last time. People scan through for the codestyle stuff that can be quickly spotted and so on. But, it's a LOT to analyze and for someone to put aside that much time. Well, we'll see.

**Comment by Shauren** [comment]
Please stop putting everything under "dynamic spawning will fix it"...

**Comment by Treeston** [comment]
> Please stop putting everything under "dynamic spawning will fix it"...

Dynamic spawning has fixed it, for the record - that's 59db2ee.
