### ISSUE TITLE
Clamlette Magnifique 3.3.5

### ISSUE THREAD

**Issue by Younguns** [TrinityCore/TrinityCore#19075]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Clamlette Magnifique 

**Current behaviour:** (Tell us what happens.) Clamlette Magnifique does not restore mana as it is supposed to, but still creates cooldown for stuff like Morning Glory Dew.

**Expected behaviour:** (Tell us what should happen instead.) It should restore 2934 mana over 30 seconds, but it barely restores 1000 mana over 30 seconds.

**Steps to reproduce the problem:**

1. Consume 1x Clamlette Magnifique
2. Watch the buffs and HP/mana bars
3. Notice that mana does not get restored as much as it is supposed to do

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5 / master

**TC rev. hash/commit:**  3a65c706572e

**TDB version:**  

**Operating system:**  Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Afgann** [comment]
Try this:
```diff
src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -787,6 +787,7 @@ void AuraEffect::UpdatePeriodic(Unit* caster)
                         case 49472: // Drink Coffee
                         case 57073:
                         case 61830:
+                        case 72623:
                             if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
                                 return;
                             // Get SPELL_AURA_MOD_POWER_REGEN aura from spell
```

**Comment by Rushor** [comment]
would you like to open a pr for this @Afgann ?
