### ISSUE TITLE
Error compiling tools under ubuntu server 16.04

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#19074]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Core doesn't compile

**Current behaviour:** (Tell us what happens.)

[ 98%] Linking CXX executable mapextractor
../../../dep/CascLib/libcasc.a(CascDecompress.cpp.o): In function `CascDecompress(unsigned char*, unsigned int*, unsigned char*, unsigned int)':
CascDecompress.cpp:(.text+0x5f): undefined reference to `inflateInit_'
CascDecompress.cpp:(.text+0x96): undefined reference to `inflate'
CascDecompress.cpp:(.text+0xa0): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
src/tools/map_extractor/CMakeFiles/mapextractor.dir/build.make:161: recipe for target 'src/tools/map_extractor/mapextractor' failed
make[2]: *** [src/tools/map_extractor/mapextractor] Error 1
CMakeFiles/Makefile2:2241: recipe for target 'src/tools/map_extractor/CMakeFiles/mapextractor.dir/all' failed
make[1]: *** [src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Expected behaviour:** (Tell us what should happen instead.)
Core should compile

**Steps to reproduce the problem:**

1. git clone repo
2.  cmake -DTOOLS=1 -DWARNINGS=1
3.  make && make install

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/bc623ed97fbe38ec0119d075f506ead42b45804c
**TDB version:**  
latest version
**Operating system:**  
ubuntu server 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by LuigiElleBalotta** [comment]
Removing-DTOOLS=1 it compiles correctly.. the problem are the tools

**Comment by Aokromes** [comment]
that's why i renamed the ticket :P

**Comment by Aokromes** [comment]
Can you try to checkout 7b43adc436948b22b51db8965516ca4b503b030f or 3fd51db845e9753e4320798d1f2e41688d78d852 or f11e6c8247dc519b8331b41a76a3dd64378071d6 to see if it compiles?
