### ISSUE TITLE
Core/Spell: Friendly NPC inherit GM auras

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19077]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** If a gm has some auras like Elemental Oath, Rampage, Aura of devotion, Heroic Presence, friendly npcs will get this auras

**Current behaviour:** Friendly npcs inherit auras from Gms

**Expected behaviour:**  Friendly npcs mustn't inherit auras from GMs 

**Steps to reproduce the problem:**

1. Create a Drainei paladin
2. Use Aura of devotion or any other auras
3. find any npc then .mod faction 35
4. Notice the npc is buffed by the Aura of devotion and Heroic Presence

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. c6060dd0c511  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ViserionLIVE** [comment]
kind of funny...

**Comment by ariel-** [comment]
We could just add an UNIT_STATE_ISOLATED to gm mode characters

**Comment by Aokromes** [comment]
eea16ce
