### ISSUE TITLE
[master] Rogue - Stealth

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19085]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Stealth isn't working.

**Current behaviour:** Stealth doesn't conceal the player.

**Expected behaviour:** Stealth should conceals the player.

**Steps to reproduce the problem:**

1. Select Rogue
2. Use Stealth

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Search before you open a new issue. This is yet another spell which is not scripted, as well as being reported in the combined issue list [[6.x] Spelltriggering - Missing Scripts](14825) #14825

**Comment by tkrokli** [comment]
BTW, feel free to comment / confirm that this issue still exists on your core rev. hash in issue #14825 .

**Comment by ArcaneFox** [comment]
Ah sorry, I didn't notice the combined issue list, I will check them.
