### ISSUE TITLE
[master] Priest - Power Word: Shield

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19089]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Power Word: Shield doesn't absorb damage.

**Current behaviour:**
Power Word: Shield doesn't absorb damage.

**Expected behaviour:**
Power Word: Shield should absorb X amount of damage.

**Steps to reproduce the problem:**

1. Select Priest
2. Cast Power Word: Shield

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#19033

**Comment by tkrokli** [comment]
(The reported issue itself can be found in https://github.com/TrinityCore/TrinityCore/issues/18520)
