### ISSUE TITLE
[master] Mage - Ice Lance

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19087]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Ice Lance doesn't damage the enemy.

**Current behaviour:**
Ice Lance doing 0 damage.

**Expected behaviour:**
Ice Lance should damage the enemy.

**Steps to reproduce the problem:**

1. Select Mage
2. Cast Ice Lance

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Gwyndrichstein** [comment]
Same problem here. 

**TC rev. hash/commit:** 880a135e348da5762e9bdc469760c5436200f8bf

**TDB version:** 7.3.5

**OS**: Debian 9

**Comment by Xenirum-Core** [comment]
Please fix it

**Comment by shamage** [comment]
Confirm - Charm does not cause any harm to the adversaries.

TrinityCore rev. `56877d236019` 2018-08-25 22:47:35 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Comment by reactmay** [comment]
still not fixed

**Comment by MaxtorCoder** [comment]
> 
> 
> still not fixed

Does it look like someone is working on it? xD Have some patience, it's master. Sandbox etc.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/25680
