### ISSUE TITLE
[master] Rogue - Eviscerate

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19086]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Eviscerate always consume 1 combo point.

**Current behaviour:** 
Eviscerate always consume 1 combo point.

**Expected behaviour:** 
Eviscerate should consume every combo point and increase the damage per combo point.

**Steps to reproduce the problem:**

1. Select Rogue
2. Cast Eviscerate

**Branch(es):**
master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18348
