### ISSUE TITLE
[Spell/Racial] Gnome Escape Artist

### ISSUE THREAD

**Issue by Feedcode** [TrinityCore/TrinityCore#19093]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Gnomes racial spell "Escape Artist" is broken.

**Current behaviour:** When you click on the spell, nothing happens. Only cooldown is used. No visual effect and no spell effect.

**Expected behaviour:** When clicked on the spell, it should have a visual effect, like the Human racial and it should remove immobilization and movement speed reduction effects.

**Steps to reproduce the problem:**

1. Create a Gnome character
2. Use Gnome's racial "Escape Artist"

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  090546a

**TDB version:**  335.62_2016_10_17 + Updates

**Operating system:**  Windows 10 64-Bit Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Hmm, this is the content I could find when searching for "20589 Escape Artist":
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/old/3.3.5a/TDB51_to_TDB52_updates/world/2013_03_11_01_world_playercreateinfo_spell.sql#L439-L441
```sql
INSERT INTO `playercreateinfo_spell` (`racemask`, `classmask`, `Spell`, `Note`) VALUES
-- [...]
-- Races:   Gnome
-- Classes: Warrior, Rogue, Death Knight, Mage, Warlock
(0x40, 0x1A9, 20589, "Escape Artist"),
```
(I presume the SQL part is only implementation of the spell on Gnome players.)

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L3630-L3636
```cpp
                case 20589: // Escape artist
                case 30918: // Improved Sprint
                {
                    // Removes snares and roots.
                    unitTarget->RemoveMovementImpairingAuras(true);
                    break;
                }
```
Maybe the spell itself does not trigger, but I don't know why it only adds the cooldown.

**Comment by MetaBarj0** [comment]
Interesting, I'm gonna take a look soon

**Comment by ariel-** [comment]
Can't reproduce on 8e865a60c8152ec6a95e169040903806738bda7f
