### ISSUE TITLE
SQL file automatically changing

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#19097]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
`/sql/updates/world/3.3.5/2017_02_09_00_world.sql` keeps having some difference in git diff even if it shouldnt.

No matter what I do git keeps telling me that the file has changes I have done locally.
Basically I see one whitespace change: "Mojo Frenzy" changes to "Mojo Frenzy "
I tried doing git add -A git reset --hard HEAD
and resetting to older versions and pulling and whatever else. Whenever I do a git command the file does not get removed or reset to having no changes. If I manage to remove it manually and reset --hard and pull again then the file is there again with these changes I have not made.

**Current behaviour:** (Tell us what happens.)
Here is an example from git bash
https://gist.github.com/Rochet2/6b3c91881bf334b9bd595417ae7aa000
Using any git commands to reset the repository and then pulling latest TC will make the file appear as if it had changes I made locally even if I did not.

**Expected behaviour:** (Tell us what should happen instead.)
Everything works normally, which means there are no automatic changes made to files.

**Steps to reproduce the problem:**

1. use git pull to get latest source
2. inspect git with git status or git diff
3. see gist above for full example of what happens

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
https://github.com/TrinityCore/TrinityCore/commit/bbc6799cd7c0a83b81496c01d21c110decebae6d

**Operating system:**  
windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Can't reproduce in Win 10, check if you have some corrupted folder (ie run chkdsk)

**Comment by Rochet2** [comment]
I tested on a separate disk (Before was a HDD and now tested on an SSD) and used a completely new clone of TC. Here is the full log. Same thing happens.

https://gist.github.com/Rochet2/cc0edf4136b7a2e4deb7f987bf917abf

**Comment by Shauren** [comment]
your git config line endigs are fucked

**Comment by Rochet2** [comment]
> your git config line endigs are fucked

Actually it seems that the file in TC repo has windows line endings even if you should have unix line endings in github repo, no?

**Comment by DDuarte** [comment]
The recommended setting is core.autocrlf = input.
It pulls as is and pushes as LF.

**Comment by tkrokli** [comment]
Thanks Rochet2, both for the issue & the PR. I had started to think I had lost my mind for a moment. xD
