### ISSUE TITLE
[3.3.5] Spell/DK: Pets are not immune to fear effects

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19098]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wowwiki.wikia.com/wiki/Raise_Dead_(death_knight_ability)
>Patch 3.1.0 (14-Apr-2009): Duration lowered to 60 sec. and cooldown lowered to 3 min. The cooldown on this ability now begins when the pet dies rather than when it is summoned. This pet now despawns instantly when it dies. In addition, this ability can no longer be used while riding any type of vehicle. **The Risen Ghoul is also now properly immune to Charm, Fear, Sleep, and Horror.**

If i'm not mistaken the Gargoyle is immune to Charm, Fear, Sleep, and Horror too.

**Current behaviour:** 
Summoned pets are not immune to Fear and Horror effects.

**Expected behaviour:** 
Summoned pets should be immune to Fear and Horror effects.

**Steps to reproduce the problem:**
1. Death Knight use  [Summon Gargoyle] or [Raise Dead]
2. Cast fear, howl of terror...

![gargola](https://cloud.githubusercontent.com/assets/30839/22837240/7dc2f3d4-ef74-11e6-9916-f944775fbdfb.jpg)

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  bbc6799

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
I do not know exactly when it broke but in d9c465e it works fine.

**Comment by ccrs** [comment]
@xinef1 @ariel-

**Comment by Noryad** [comment]
PR works :+1:
