### ISSUE TITLE
[3.3.5] Acclimation does not trigger

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19096]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** some proc error with dk talent acclimation, it never triggers.

**Current behaviour:** (Tell us what happens.) ^

**Expected behaviour:** (Tell us what should happen instead.) Should trigger when being hit etc

**Steps to reproduce the problem:**

1. Spec acclimation
2. spam whatever spell on the dk
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/090546a80a0b0d29d619c1b0f38da1375dcd37d0

**TDB version:**  62

**Operating system:**   ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
Acclimatization works ok in 09cc6b3. In my case DK vs. Warlock and the two Shadow and Fire reresistances were activated. Please try with a clean core and DB.

**Comment by Persephone** [comment]
Alright thank you
