### ISSUE TITLE
[master] Mage - Cone of Cold

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19109]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Cone of Cold is outdated.

- http://www.wowhead.com/spell=120/cone-of-cold

**Current behaviour:** 
Cone of Cold is outdated.

**Expected behaviour:**
Cone of Cold should update to 7.1.5

**Steps to reproduce the problem:**

1. Select Mage
2. Level up to 34
3. Change spec to Frost
4. Cast Cone of Cold

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment]
Possible fix:

```
SPELL_MAGE_CONE_OF_COLD                      = 212792,

// 120 - Cone of Cold [7.1.5]
class spell_mage_cone_of_cold : public SpellScriptLoader
{
    public:
        spell_mage_cone_of_cold() : SpellScriptLoader("spell_mage_cone_of_cold") { }

        class spell_mage_cone_of_cold_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_mage_cone_of_cold_SpellScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_MAGE_CONE_OF_COLD))
                    return false;
                return true;
            }

            void HandleHit(SpellEffIndex /*effIndex*/)
            {
                Unit* caster = GetCaster();
                Unit* target = GetHitUnit();
                if (caster && target)
                    caster->CastSpell(target, SPELL_MAGE_CONE_OF_COLD, true);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_mage_cone_of_cold_SpellScript::HandleHit, EFFECT_0, SPELL_EFFECT_SCHOOL_DAMAGE);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_mage_cone_of_cold_SpellScript();
        }
};
```

**Comment by HannibalRoG** [comment]
@ArcaneFox I will try it and leave you right if it works or not.

**Comment by Keader** [comment]
```GetCaster();``` cant be null in SpellScripts and
```GetHitUnit();``` only can be null in ```OnEffectHitTarget``` hook, if spell hit objects

**Comment by zamalaev** [comment]
```
            void HandleHit(SpellEffIndex /*effIndex*/)
            {
                Unit* caster = GetCaster();
                Unit* target = GetHitUnit(); ?
                if (caster && target) ?
                    caster->CastSpell(target, SPELL_MAGE_CONE_OF_COLD, true);
            }
```

FIX?
            void HandleHit(SpellEffIndex /*effIndex*/)
            {
                Unit* caster = GetCaster();
                if  (Unit* target = GetHitUnit()); 
                   caster->CastSpell(target, SPELL_MAGE_CONE_OF_COLD, true);
            }

**Comment by ArcaneFox** [comment]
damage & slow working
