### ISSUE TITLE
[master] Mage - Cauterize

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19107]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The "Cauterize" passive skill prevents the player from taking damage.

- [www.wowhead.com/spell=86949/cauterize](url)

**Current behaviour:**
The "Cauterize" implementation is missing.

**Expected behaviour:**
Fatal damage instead brings you to 35% health and then burns you for 28% of your maximum health over 6 sec. While burning, movement slowing effects are suppressed and your movement speed is increased by 150%. This effect cannot occur more than once every 5 min.

**Steps to reproduce the problem:**

1. Select Mage
2. Level up to 52
3. Change spec to Fire

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Ulduar** [comment]
You can try this:
```CPP
// Cauterize - 86949
class spell_mage_cauterize: public SpellScriptLoader
{
    public:
        spell_mage_cauterize() : SpellScriptLoader("spell_mage_cauterize") { }

        class spell_mage_cauterize_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_mage_cauterize_AuraScript);

            int32 absorbChance;
            int32 healtPct;

            bool Load()
            {
                absorbChance = GetSpellInfo()->GetEffect(EFFECT_0).CalcValue(GetCaster());
                healtPct = GetSpellInfo()->GetEffect(EFFECT_1).CalcValue(GetCaster());
                return GetUnitOwner()->ToPlayer();
            }

            void CalculateAmount(AuraEffect const* /*auraEffect*/, int32& amount, bool& /*canBeRecalculated*/)
            {
                amount = -1;
            }

            void Absorb(AuraEffect* /*auraEffect*/, DamageInfo& dmgInfo, uint32& absorbAmount)
            {
                Unit* target = GetTarget();

                if (dmgInfo.GetDamage() < target->GetHealth())
                    return;

                if (target->ToPlayer()->HasSpellCooldown(86949))
                    return;

                int32 bp1 = target->CountPctFromMaxHealth(healtPct);
                target->CastCustomSpell(target, 87023, nullptr, &bp1, nullptr, true);
                target->ToPlayer()->AddSpellCooldown(86949, 0, 300 * IN_MILLISECONDS);

                absorbAmount = dmgInfo.GetDamage();
            }

            void Register()
            {
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_cauterize_AuraScript::CalculateAmount, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
                OnEffectAbsorb += AuraEffectAbsorbFn(spell_mage_cauterize_AuraScript::Absorb, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB);
            }
        };

        AuraScript* GetAuraScript() const
        {
            return new spell_mage_cauterize_AuraScript();
        }
};
```

**Comment by HannibalRoG** [comment]
@Ulduar I will try it and leave you right if it works or not.

**Comment by ArcaneFox** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5774e926d997ef870bf3f184d0f23396e283fe56
