### ISSUE TITLE
Player not Found

### ISSUE THREAD

**Issue by huesoamz** [TrinityCore/TrinityCore#19103]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** when we try to use Friend and put the  name of other character, we receive a message of "Player not found"

**Expected behaviour:** should be added the chars of the character table

**Steps to reproduce the problem:**

1. Press "O" ingame and click in "add friend"
2.  Fill with a nickname of other person
3.  Receive the message of player not found

**Branch(es):** 3.3.5 
**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8d2f2f8f0603608f0f21e656046cb7ffcb4813a2

**TDB version:**  TDB_full_335.62_2016_10_17

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by huesoamz** [comment]
![wowscrnshot_021117_011939](https://cloud.githubusercontent.com/assets/3308717/22851165/3eddc070-eff8-11e6-9c43-883b146ee8ee.jpg)

**Comment by HannibalRoG** [comment]
If the players are of different factions and you do not have enabled the option in RBac so that they can be seen it gives you that message correctly. This is not a Core error.

**Comment by Aokromes** [comment]
Working as intended on bbc6799cd7c0

**Comment by raelik** [comment]
We've been having this issue as well, and we're all Horde players.  The only difference is that two of us have GM accounts, and the non-GM players can't add the GM players.
