### ISSUE TITLE
[3.3.5][Quest] Warsong scout update - Ashenvale

### ISSUE THREAD

**Issue by Smileynator** [TrinityCore/TrinityCore#19117]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
In some quest i got 3 Warsong reports, which i can deliver in Splittertree post.
This somehow fails when i try to accept the quest Warsong Scout Update 2 times. Error says: Duplicate Item Found
**Current behaviour:** (Tell us what happens.)
This quest doesn't work due to duplicate item
**Expected behaviour:** (Tell us what should happen instead.)
IT probably shouldn't even allow me to take out the quest a 2nd time until i completed it the first time?
**Steps to reproduce the problem:**

1. Get a hold of the warsong reports http://www.wowhead.com/quest=6543/the-warsong-reports
2.  Go to the Warsong Scout at splittertree.
3. Accept is quest a 2nd time, and notice it fails. It also shouldn't allow you to do it in the first place, right?

**Branch(es):** 
3.3.5
**TC rev. hash/commit:**  
39b20b4431a1a67446e9cc4c2221fd42cc907291
**TDB version:**  
TDB 335.62 + updates up to and including 2017_01_17_00_world.sql
**Operating system:**  
Windows 7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
It is simple: when you try to complete the objective a second time at the same NPC which you have already delivered a letter from Kadrak to, you already have got 1 of these 3 items in one of your bag slots:
- http://www.wowhead.com/item=16763/warsong-runner-update
- http://www.wowhead.com/item=16764/warsong-scout-update
- http://www.wowhead.com/item=16765/warsong-outrider-update

All these 3 are UNIQUE items, which means (as you should know) that you can't have more than 1 of them at any given time (this means both bags and bank, any of your storage).

**Comment by tkrokli** [comment]
BTW, you do not _accept_ a new quest at any of the 3 Warsong NPCs, you _complete 1 of 3 objectives_.
Why Blizzard chose to do it this way in the first place, I don't know. Maybe to highlight each of the 3 NPCs?
