### ISSUE TITLE
Quest: 1920 Investigate the Blue Recluse

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19112]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** **Current behaviour:** (Tell us what happens.) **Expected behaviour:** (Tell us what should happen instead.)

The Blue Recluse area is not phased correctly. The rift disturbances are not visible. You can use the item to make the rift mobs appear, 5 of them appear at a time. When you fight them, they do not become "stunned" and you cannot use the item to capture them.

**Steps to reproduce the problem:**

1. Level 16 Mage Quest
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

c6060dd0c511 2017-02-05 21:10:15 -0300 (3.3.5 branch)

**TC rev. hash/commit:**  

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#18997
