### ISSUE TITLE
NPC Captain Greenskin is wrong model

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19125]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Captain Greenskin (Entry 647) in the Deadmines instance is the wrong model.

**Current behaviour:** (Tell us what happens.)

In-game, he appears to be an undead skeleton race. The clothes appear correct, but he is supposed to be a goblin. (Display ID: 3494)

**Expected behaviour:** (Tell us what should happen instead.)

He's supposed to be a green goblin: http://www.wowhead.com/npc=647/captain-greenskin

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c6060dd0c511 2017-02-05 21:10:15 -0300 (3.3.5 branch)

**TDB version:**  

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Try:
``` sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID`=7113;

**Comment by jerbookins** [comment]
Perfect
