### ISSUE TITLE
[3.3.5] No skinning loot from elder mottled boars

### ISSUE THREAD

**Issue by Trystanosaurus** [TrinityCore/TrinityCore#19126]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
In the latest version of 3.3.5 (63a0eadf) there is no skinning loot from quite a lot of beasts. Including elder mottled boar (id 3100). I don't know if it's because they share a skinning loot table with some other beasts. I had the same problem with lashtail raptors in stranglethorn vale.

Rolling back to the last commited version (4536846d) it's working as intended.

I'm quite new to this gitting so let me know if there's any problem with this issue.

**Current behaviour:** (Tell us what happens.)
No skinning loot from elder mottled boars in durotar.

**Expected behaviour:** (Tell us what should happen instead.)
They give skinning loot.

**Steps to reproduce the problem:**

1. Kill a elder mottled boar in northern durotar
2. Skin it
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5 as far as I know.

**TC rev. hash/commit:**  
63a0eadf - I hope this is the right number, let me know if it isn't.

**TDB version:**  
Latest, updated to "2017_02_12_00_world.sql"

**Operating system:**  
Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
thats's the current skinning loot assigned to it:

```sql
INSERT INTO `skinning_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (100002, 2318, 0, 40, 0, 1, 1, 1, 1, 'Light Leather');
INSERT INTO `skinning_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (100002, 2934, 0, 60, 0, 1, 1, 1, 1, 'Ruined Leather Scraps');
```

maybe you just had bad luck, and there was not skinning loot for you (it has a 40 and a 60 percent chance only, not 100 percent every time)

**Comment by Shauren** [comment]
this is shit loot, that should have been a grouped entry

**Comment by Rushor** [comment]
reference_loot_template then?

**Comment by Trystanosaurus** [comment]
Afraid I can't offer much more insight as I'm not really overly up on how it all works.

All I know is that I didn't make any database changes between 4536846 where it worked and 63a0ead where it didn't.

I did notice that 63a0ead includes some fixes to pick pocketing and also removes "GetSkinner()" and replaces it with "GetLootRecipientGUID()" which might have had unwanted side effects.

**Comment by tkrokli** [comment]
commit 4536846d7d30508a046f394d1f561a2c3fdcf5f0 is currently (as of this comment) still the latest commit available in the [`3.3.5`](https://github.com/TrinityCore/TrinityCore/tree/3.3.5) branch, so I think you should ask @xinef1 in the PR you have merged in and ask what he thinks about your issue.

**Comment by tkrokli** [comment]
Check @xinef1's Pull Request https://github.com/TrinityCore/TrinityCore/pull/19122 (files: https://github.com/TrinityCore/TrinityCore/pull/19122/files) and ask him about your issue with skinning. Thanks for noticing this, it needs fixing before https://github.com/TrinityCore/TrinityCore/pull/19122 gets merged.

**Comment by xinef1** [comment]
Can be closed

**Comment by tkrokli** [comment]
@Trystanosaurus : try again now, @xinef1 just added a correction in his PR (commit https://github.com/TrinityCore/TrinityCore/pull/19122/commits/24e57d38a0a0791035e47ef6ab17ac9c6aa169c7 ).

**Comment by Trystanosaurus** [comment]
Thanks all for looking into this so quickly (and for constantly improving this already great program), it's working perfectly again now.
