### ISSUE TITLE
[3.3.5][events]Darkmoon Faire NPC Bug

### ISSUE THREAD

**Issue by freejerry** [TrinityCore/TrinityCore#19120]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** I saw the NPC, Kruban Darkblade, in the Orgrimmar when Darkmoon Faire didn't start.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  TrinityCore rev. e865e5cf8e66 2017-02-11 05:55:12 +0100 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB 335.62

**Operating system:**  Ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5079#issuecomment-38694744 ?

**Comment by tkrokli** [comment]
We do not have any pathing information about Kruban Darkblade nor details of which event spawned him (no, he was not spawned together with the Darkmoon Faire, he should spawn some days before).
Unless someone has got newly found information from 3.3.5a about when he spawns and where he walked, we should probably just close this issue as unsolvable due to lack of information.

**Comment by offl** [comment]
No, i'm just trying to tell why he is spawned without the event.

**Comment by tkrokli** [comment]
OK, maybe I misunderstood the original issue post. Not sure.

**Comment by Kittnz** [comment]
Old issue: https://github.com/TrinityCore/TrinityCore/issues/5079

**Comment by offl** [comment]
Why closed?

**Comment by tkrokli** [comment]
I guess it could have something to do with my post https://github.com/TrinityCore/TrinityCore/issues/19120#issuecomment-279277027 (not sure, though).
Looks like Killyana has posted a neat fix for this issue, so it should not make much difference. 👍

**Comment by freejerry** [comment]
I think this issue is similar to old issue so I close it.
But in this issue I want to say Kruban Darkblade was appeared in Orgrimmar even the Darkmoon Faire event didn't active, not why he just stand here.

**Comment by tkrokli** [comment]
Issue #5079 was already closed, so this one could have stayed open until it had been decided what to do about Kruban Darkblade. But it does not matter, it is not important now that a fix has been posted. 😃

**Comment by freejerry** [comment]
OK, I just stay it open until it will be solved.

**Comment by Aokromes** [comment]
It was fixed by 38c6e594b54c3977646b53395df5f2f9da98dc57

**Comment by freejerry** [comment]
Oh, I saw that. :)
