### ISSUE TITLE
command modify faction crash

### ISSUE THREAD

**Issue by Farrarie** [TrinityCore/TrinityCore#19127]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
the command modify faction crash the world server
**Current behaviour:** (Tell us what happens.)
when I change a faction of an npc when I type .mod fac 1 to an npc mob the world server crash
**Expected behaviour:** (Tell us what should happen instead.)
when I type .mod fac 1 to npc the faction change without crashing the world server
**Steps to reproduce the problem:**

1. type .mod faction to an npc
2. it change the npc faction
3. dont crash the world server

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master 
**TC rev. hash/commit:**  
 8aacc07
**TDB version:**  
  703.00 and latest I keep all uptodate 2017_02_13 
**Operating system:**  
windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
When you created this issue, there was a line already in the issue description that says **"(If this is a crash report, include the crashlog with https://gist.github.com/)"**. Why did you choose to ignore this information?

**Comment by Farrarie** [comment]
I dont know what you mean im a noob at github
when I click at your link it take me to a new page create a new gist ?

**Comment by DDuarte** [comment]
Fair enough.

When your server crashed, a .txt file in the **Crashes** folder got created.
Copy paste that crash log to a gist and write here the URL of the gist.

**Comment by Farrarie** [comment]
I created the gist
https://gist.github.com/anonymous/e6f52a5e1009a8bcba2ab8f43d6894e3

**Comment by DDuarte** [comment]
Good job, that's it.

However, that crash log is not very useful because the server was compiled in Release mode.
Compile the server in **Debug mode** and post the new crashlog (you will notice that it is much more complete).

**Comment by Farrarie** [comment]
thanks friend for trying to help 
I do debug now

**Comment by Farrarie** [comment]
when I choose debug when compiling no world server or authserver their
========== Build: 20 succeeded, 6 failed, 0 up-to-date, 1 skipped ==========
and cant find error log or something in release mod its ok only in debug

**Comment by DDuarte** [comment]
The compile log has the source of the errors.

**Comment by Farrarie** [comment]
no and now even release give errors
I will re do cmake maybe files got curropt

**Comment by Farrarie** [comment]
now debug give worldserver after re do cmake 
I will do gist now

**Comment by Farrarie** [comment]
debug gist https://gist.github.com/anonymous/5a2c3314fca56705d8cf91d64ec27a58

**Comment by DDuarte** [comment]
Much better.

Please post the result of the query:

```sql
SELECT * FROM `trinity_string` WHERE `ID`=130;
```

**Comment by Farrarie** [comment]
sql error (1054) Unkown colunm ID in Where cluase

**Comment by DDuarte** [comment]
My mistake, fixed query:

```sql
SELECT * FROM `trinity_string` WHERE `entry`=130;
```

**Comment by Farrarie** [comment]
now it close the world server
I will use debug world server 
and post gist

**Comment by Farrarie** [comment]
it crash debuged world server
here is the crash.txt
https://gist.github.com/anonymous/2ec2b336e7a9169d4445250b7be2676b

**Comment by DDuarte** [comment]
Result of the query 
```sql
SELECT * FROM `trinity_string` WHERE `entry`=130;
```
??

**Comment by Farrarie** [comment]
I did it still after I did the query
the world server still crash

**Comment by DDuarte** [comment]
It's a SELECT, I want to know the result of it. It does not change anything.

**Comment by Farrarie** [comment]
I dont know what you mean
what result you want ?
I put the new crash to a new gist

**Comment by Farrarie** [comment]
You changed GUID=%i's Faction to %i, flags to %i, npcflag to %i, dynflag to %i.

**Comment by DDuarte** [comment]
That confirms the crash. Fix will be done soon.

**Comment by Farrarie** [comment]
thanks alot good friend

**Comment by DDuarte** [comment]
Fix:
```sql
UPDATE `trinity_string` SET `content_default`='You changed GUID=%s\'s Faction to %i, flags to %i, npcflag to %i, dynflag to %i.' WHERE `entry`=130;
```

**Comment by Farrarie** [comment]
it work thanks alot good friend

**Comment by Rochet2** [comment]
https://github.com/TrinityCore/TrinityCore/pull/18863
related PR that was going to fix this.

**Comment by DDuarte** [comment]
Let's use that then, thanks
