### ISSUE TITLE
IPv6 Database IP

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#19134]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Account Database does not save the full IPv6 IP

**Current behaviour:** (Tell us what happens.)
If an user registering an Account over the website and they using ipv6 it will not saved fully.

**Expected behaviour:** (Tell us what should happen instead.)
Save the full ipv6

**Steps to reproduce the problem:**

1. Create a PHP Register Script
2. Register an Account
3. Check Database entry with enabled IPv6
4. Proof : http://image.prntscr.com/image/093c3839bf5a4f30adea4848248516ae.png

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
c2a36c9e89c7

**TDB version:**  
TDB 335.62

**Operating system:**  
Linux Debian Jessy

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
Is that field being set by auth or worldserver?

**Comment by Shoxxo** [comment]
I am using SOAP, so it comes from the Worldserver into the Auth Database. But here a Tempfix, i don't know if trinitycore can handle ipv6.

```sql
ALTER TABLE `account`
	CHANGE COLUMN `last_ip` `last_ip` VARCHAR(128) NOT NULL DEFAULT '127.0.0.1' AFTER `joindate`,
	CHANGE COLUMN `last_attempt_ip` `last_attempt_ip` VARCHAR(128) NOT NULL DEFAULT '127.0.0.1' AFTER `last_ip`;
```

**Comment by Shauren** [comment]
authserver and worldserver will never write ipv6 addresses there as they cannot handle it.
Nonissue.

**Comment by Aokromes** [comment]
TIP: wow 3.3.5a client can't handle ipv6.
