### ISSUE TITLE
DB/Gossip: broken links in Stormwind Guard chat options

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19135]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The information ( directions ) you get from the Stormwind guards is incorrect or not working
**Current behaviour:** (Tell us what happens.)
The guards "chat information " comes up in a list giving directions. The information the guard says either does not work or gives you the information from the line above the one you click on.

- Guild Master works as intended
- Stable Master tells you about the Guild Master
- Class Trainer tells you about the Stable Master
- Deeprun Tram tells you about the Counting House / Auction House
- The Inn tells you about Stormwind having two Banks
- Gryphon Master tells you about the Barber Shop
- Locksmith tell about the Gryphon Master
- Weapons Trainer tells you about the Inn
- Officer Lounge does not respond
- Battle Master does not respond
- Barber does not respond

- Profession Trainers:
  - Alchemy works
  - Leatherworking works
  - Blacksmith does not respond
  - Cooking Talks about blacksmith
  - Enchanting Talks about cooking
  - Engineering talks about Enchanting
  - First Aid Talks about Engineering
  - Fishing talks about First Aid
  - Herbalist Talks about Fishing
  - Inscription does not respond
  - Mining talks about Inscription
  - Skinning does not respond
  - Tailoring Talks about Skinning

**Expected behaviour:** (Tell us what should happen instead.)
When you ask a guard for directions it should place a marker on the map as well as give you the correct information about the location or trainer you are asking about.

**Steps to reproduce the problem:**

1. Ask a guard for directions in Stormwind 
2. 
3. 

**Branch(es):** master Branch

**TC rev. hash/commit:**  941f7d2bbefc

**TDB version:**  TDB_full_703.00_2016_10_17

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by msoky** [comment]
look at https://github.com/TrinityCore/TrinityCore/issues/16498
there is fixed directions for silvermoon directions...there is way how to do it...it is needed to modify gossip_menu_option table

**Comment by tkrokli** [comment]
That description looks like the `gossip_menu_option.menu_id` values or `gossip_menu` entries could be shifted one value away from what they are supposed to be, in such a way that they point to the next one instead of the correct ID/entry (don't know yet, have not had time to look it up).

**Comment by msoky** [comment]
test it after https://github.com/TrinityCore/TrinityCore/commit/21f4ee8a9ae7ec108f87729a17c6fccc2847c040

**Comment by Aokromes** [comment]
A lot of POIs where fixed by malcrom few weeks ago, if some are missing open a new ticket for the missing ones.
