### ISSUE TITLE
In Defense of Westfall

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19137]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Quest is picked up in westfall. Unable to complete because you are not able to loot quest item

**Current behaviour:** (Tell us what happens.)
When you recieve this quest the gnoll attack order start droping off the gnolls you kill When you attempt to look a message shows on the screen " already looted "

**Expected behaviour:** (Tell us what should happen instead.)
You should be able to loot the quest item from the gnoll you kill
**Steps to reproduce the problem:**

1. Get quest http://www.wowhead.com/quest=26286/in-defense-of-westfall
2. Kill a Riverpaw Gnoll
3. Try to loot Gnoll Attack Orders

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master Branch
**TC rev. hash/commit:**  
941f7d2bbefc
**TDB version:**  
TDB_full_703.00_2016_10_17
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Items are on the DB and could be looted https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/4.3.4/TDB2_to_TDB3_updates/world/046_quest_fixes.sql#L49
