### ISSUE TITLE
Quest/Spells: The Eye of Acherus (51852) buff is not removed

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19132]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The spell/effect "Controlling the Eye of Acherus" remains on your character and must be manually dispelled after you turn in the quest [The Might of the Scourge](http://www.wowhead.com/quest=12657/the-might-of-the-scourge) (ID 12657).

The spell/effect should be automatically removed upon completion of the quest.

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
 c6060dd0c511 2017-02-05 21:10:15 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  
335.62

**Operating system:**  
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
How is this issue (or "The Might of the Scourge") related to **[BUG]visual bug about drink and food** ?

**Comment by jerbookins** [comment]
I don't understand what you mean by

> [BUG]visual bug about drink and food

**Comment by Tooa** [comment]
You referred to another issue called `[BUG]visual bug about drink and food` in your `Current behavior` description by mentioning `#12567`.

**Comment by jerbookins** [comment]
That's the quest ID. It says "Quest 12567". I'm sorry if I did not follow correct protocol with formatting my issue submission.

**Comment by tkrokli** [comment]
OK, fair enough. As long as you know that using the hash tag and a number between 1 and 19140 (currently highest number used in this repository, but increasing continuously for each new issue or PR), it will link to and refer the issue your comment is in in the other issue or pull request. Because if this GitHub feature, it is better to use plain numbers or links to wowhead or openwow.com pages to provide easy access to information about the quest ID, spell ID, NPC ID, item ID or other ID you refer to.

**Comment by jerbookins** [comment]
Good to know. Any word on a fix for the issue?

**Comment by tkrokli** [comment]
About the spell/buff you refer to, "Controlling the eye of Acherus", it would be practical if you had referred to the actual spell and confirmed in-game what the buff spell ID is, so it would be quicker to look it up.

At first, I thought you had confused [Controlling the eye of Acherus] with the buff you are supposed to gain from quest 12657 ((notice quest ID 12567 = http://www.wowhead.com/quest=12567/blessing-of-zimabwa)), namely [[Dominion Over Acherus]](http://www.wowhead.com/spell=51721/dominion-over-acherus) (http://www.wowhead.com/spell=51721/dominion-over-acherus).

After a bit of manual searching, I located spell ID 51852 [[The Eye of Acherus]](http://www.wowhead.com/spell=51852/the-eye-of-acherus) which has the flavor text "Controlling the Eye of Acherus". I am guessing this is related to the previous quest [[Death Comes From On High]](http://www.wowhead.com/quest=12641/death-comes-from-on-high) (http://www.wowhead.com/quest=12641/death-comes-from-on-high).

My first thought on this is that it could have something to do with aura handling and that the aura is not removed upon quest completion, but I don't know where it is handled yet. Maybe it is in some script, but I have not had time to look it up yet. If others have got time to look up where this is handled, it would be helpful and save some time in further troubleshooting. Mind you, this is cosmetic and not a big issue.

**Comment by jerbookins** [comment]
Yeah, I'm just flying by the seat of my pants here. I expect I'll be learning more about how to efficiently look up spell IDs and things in the near future. But thankfully someone like you is here. In the mean time, I will continue to provide as much information as I know how to access.

**Comment by MrSmite** [comment]
> My first thought on this is that it could have something to do with aura handling and that the aura is not removed upon quest completion, but I don't know where it is handled yet.

> **3.3.5** https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_quest.cpp#L2203
```C++
player->RemoveAura(THE_EYE_OF_ACHERUS);
```

> **Master** https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Spells/spell_quest.cpp#L2204
```C++
player->RemoveAura(THE_EYE_OF_ACHERUS);
```

**Comment by tkrokli** [comment]
Thanks for the code and links, good references. The Death Knight starter area is almost the same in both branches, but I am wondering if something has changed in the client communication or if there are other outside factors interfering in the quest, like spell errors. I should probably take a look at the hundreds of Server.log spell error lines and see if I can locate anything related to this spell.

**Comment by Aokromes** [comment]
#18362
