### ISSUE TITLE
DB/Quest: Feeding the hungry and the hopeless

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19136]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** You do not get credit for each NPC you "feed"
- http://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless

**Current behaviour:** (Tell us what happens.) When you target the NPC character and click on the [Westfall Stew](http://www.wowhead.com/item=57991/westfall-stew), the cooldown timer works, the object for the stew appears in front of the NPC, but you do not receive credit for doing this for the quest.

**Expected behaviour:** (Tell us what should happen instead.) When you click on the quest item, it should have an object appear in front of the NPC, and you should receive credit for doing this in the quest.

**Steps to reproduce the problem:**

1. Get quest "feeding the Hungry and hopeless
2. go to a refugee and target them then click on the quest item  
3. 

**Branch(es):** master Branch

**TC rev. hash/commit:**  941f7d2bbefc

**TDB version:**  TDB_full_703.00_2016_10_17

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by nubqt** [comment]
Confirmed on master 7334419 TDB 720.00_2017_04_18

This also belongs to master list #15182 of Cataclysm zones.
