### ISSUE TITLE
DB/Quest: The Missing Diplomat NPC faction scripting

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19142]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
In [the Missing Diplomat quest chain (quest id 1447)](http://www.wowhead.com/quest=1447/the-missing-diplomat)
 the [Old Town Thug (entry 4969)](http://wotlk.openwow.com/npc=4969) (http://www.wowhead.com/npc=4969/old-town-thug)
 who spawns in the fight do not disengage fighting and become friendly
 after you defeat [Dashel Stonefist (entry 4961)](http://www.wowhead.com/npc=4961/dashel-stonefist) (http://wotlk.openwow.com/npc=4961).

**Current behaviour:** (Tell us what happens.)
The Old Town Thugs (entry 4969) who spawn in the fight do not disengage fighting or become friendly after you defeat Dashel Stonefist (entry 4961).

**Expected behaviour:** (Tell us what should happen instead.)
The Old Town Thugs (entry 4969) should become green/friendly after Dashel Stonefist says: "It's okay, boys. Back off. You've done enough. I'll meet up with you later."

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c63f3788d9e5 2017-02-15 10:09:44 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by dr-j** [comment]
I fixed other issues with these npcs a while ago but did not do anything with faction as wowhead comments on this suggest otherwise (read last comment)

wowhead.com/npc=4969/old-town-thug#comments

**Comment by tkrokli** [comment]
Hmm. The only related comment is downrated `-3`, meaning it is not seen as very helpful, but it could still be referencing the actual behaviour back then.
http://www.wowhead.com/quest=1447/the-missing-diplomat#comments looks more detailed, though.
Could it be that players have overlooked potentially aggressive player defense mechanisms (passive)?

**Comment by dr-j** [comment]
Could be because quest has been depreciated since cata and most comments for quests removed have since been downrated as no longer valid.

**Comment by Killyana** [comment]
I'm not sure about Old Town Thugs turning friendly https://youtu.be/W65GDUOfnS8?t=10m46s

**Comment by jerbookins** [comment]
@killyana doesn't really help since he killed them...

**Comment by jerbookins** [comment]
Why would he say "Back off boys..." if they weren't supposed to stop fighting you. It is obvious.

**Comment by Rushor** [comment]
> doesn't really help since he killed them...

blizz would have added ACTION_SET_INVINCIBILITY_HP_LEVEL for them if they really should turn frriendly, but they don't

**Comment by jerbookins** [comment]
They're not supposed to be invincible. You're missing the point. The objective is to beat the Dashel, right? So when you bring his hp down, he stops fighting and says "Back off boys..." it has nothing to do with whether you have killed them prior to him saying that. If you focused on Dashel and ignored them they are supposed to stop fighting.

**Comment by jerbookins** [comment]
http://www.wowhead.com/quest=1447/the-missing-diplomat

Here is a comment from 1.12.1

**Comment by Rushor** [comment]
http://www.wowhead.com/quest=1447/the-missing-diplomat#comments:id=245675
By ajksac (670 – 4) on 2008/02/29 (Patch 2.3.3)		
this is definitly a pain....i defeated him and the gaurds stopped attcking and then all of a sudden they started again and killed me. AAAAAAAHHH

wycorp on 2008/08/11 (Patch 2.4.3)
Same thing happened to me. Also, when they started attacking again, they had gone back to full health... :(

so we need to add this bug then?

1.) reset guards once Dashel was defeated
2.) add attackstart on player for guards after a few seconds again

**Comment by Killyana** [comment]
try:
``` sql
UPDATE `smart_scripts` SET `action_type`=45, `action_param1`=1, `action_param2`=1, `Comment`="Dashel Stonefist - On Script - Set data" WHERE `entryorguid`=496101 AND `source_type`=9 AND `id`=1;
UPDATE `smart_scripts` SET `event_flags`=1 WHERE `entryorguid` IN (4961) AND `source_type`=0 AND `id`=2 AND `event_type`=2;

UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry` IN (4969);
DELETE FROM smart_scripts WHERE entryorguid=4969 AND source_type=0;
DELETE FROM smart_scripts WHERE entryorguid=496900 AND source_type=9;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, COMMENT) VALUES 
(4969, 0, 0, 1, 54, 0, 100, 0, 0, 0, 0, 0, 42, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Old Town Thug - Just summoned - Set invinciblity"),
(4969, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 30, 0, 0, 0, 0, 0, 0, "Old Town Thug - Just summoned - Start attack"),
(4969, 0, 2, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 496900, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Old Town Thug - On data set - action list"),
(496900, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Old Town Thug - action list - combat stop"),
(496900, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Old Town Thug - action list - combat stop"),
(496900, 9, 2, 0, 0, 0, 100, 0, 5000, 5000, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Old Town Thug - action list - despawn");
