### ISSUE TITLE
Trinity World outputting this database error

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19140]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Trinity World is repeating this error hundreds of times.

**Current behaviour:** (Tell us what happens.)

"CreatureTextMgr: Could not find Text for Creature Lord Thorval (Entry 28472, GUID 569) in 'creature_text' table. Ignoring."

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

3.3.5

**TC rev. hash/commit:**  

TrinityCore rev. c6060dd0c511 2017-02-05 21:10:15 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
You forgot to list which DB version you're using.

**Comment by jerbookins** [comment]
Sorry how do I check?

**Comment by MrSmite** [comment]
> Sorry how do I check?

In your *World* database there is a table called *revision* with field *db_version*.

**Comment by jerbookins** [comment]
@MrSmite  Thanks, i'll keep that in mind. I updated TrinityCore to the newest build and haven't seen the error since.

**Comment by jerbookins** [comment]
@MrSmite I don't have a table called "revision" in my world table. I have a table called "version", but it is empty.

**Comment by tkrokli** [comment]
That is OK. it is a known issue, the Worldserver does not show which DB is used either (both branches).

**Comment by MrSmite** [comment]
> @MrSmite I don't have a table called "revision" in my world table. I have a table called "version", but it is empty.

Yes, that was a typo on my part. It should be `version`.
