### ISSUE TITLE
[335] Quest 'Letter to Stormpike' Improperly Linked

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#19141]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

The quest [Letter to Stormpike (id 514)](http://wowwiki.wikia.com/wiki/Quest:Letter_to_Stormpike) is not linked to the previous quest [Encrypted Letter (id 511)](http://wowwiki.wikia.com/wiki/Quest:Encrypted_Letter_%28Hillsbrad_Foothills%29)

**Current behaviour:**

*Letter to Stormpike* should start by obtaining *Encrypted Letter* from lootable GO [Syndicate Documents (id 1738)](http://wowwiki.wikia.com/wiki/Syndicate_Documents) but instead is available from [Loremaster Dibbs (id 2277)](http://wowwiki.wikia.com/wiki/Loremaster_Dibbs) without obtaining the letter.

**Expected behaviour:**

Players should have to turn in *Encrypted Letter* to *Loremaster Dibbs* before he offers *Letter to Stormpike*

**Steps to reproduce the problem:**

1. Talk to *Loremaster Dibbs* at around level 36 without having quest / item *Encrypted Letter*
2. 
3. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/c63f3788d9e5b0fe0df32f662b2e81cedb953fb4

**TDB version:**  TDB_full_world_335.61_2016_04_11 + updates

**Operating system:**  WinXP / Win7

**NOTES:**

* I provided wowwiki links with IDs from wowhead. Wowwiki shows quest chain progression but no IDs
* Because wowhead is for 7.x, it has the quest as deprecated so the linking information is not available. It seems logical however that if a quest requires delivering to one NPC an item the player turned in to another NPC, the player would have to obtain the item first.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
``` sql
UPDATE `quest_template_addon` SET `PrevQuestID`=511 WHERE `ID`=514;

**Comment by MrSmite** [comment]
Tested and works, quest 514 no longer offered to lvl 36 Hunter without quest 511.

**Comment by Killyana** [comment]
Don't understand for what purpose RewardNextQuest is used in this case, as for the quest 511, RewardNextQuest=514

**Comment by MrSmite** [comment]
> Don't understand for what purpose RewardNextQuest is used in this case, as for the quest 511, RewardNextQuest=514

Not sure, the wiki for `quest_template` is a mess. *PrevQuestId* and *NextQuestId* are defined but not listed in the structure, *RewardNextQuest* is listed in the structure but not defined.

Based on the definitions of *Prev* and *Next*, they suffice to make sure a quest chain is properly followed.

**Comment by Killyana** [comment]
PrevQuestId and NextQuestId were moved to quest_template_addon
