### ISSUE TITLE
WPP Trinity Core Master Updates TAABOY

### ISSUE THREAD

**Issue by Taaboy** [TrinityCore/TrinityCore#19146]
[9999_99_99_99_world_01.txt](https://github.com/TrinityCore/TrinityCore/files/782642/9999_99_99_99_world_01.txt)
[9999_99_99_00_world_02.txt](https://github.com/TrinityCore/TrinityCore/files/782643/9999_99_99_00_world_02.txt)

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
SQL Updates

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
branch/master
**TC rev. hash/commit:**  
commit 0ed67081bca9a5eda357f174bcd8d6757da50534
**TDB version:**  
7.03.00
**Operating system:**  
Windows 10

**Comment by Shauren** [comment]
the queries at the end of file are very bad, loot ids don't have to be equal to creature entry (loot templates can be shared by many creatures)

**Comment by Taaboy** [comment]
Ok I remove them if you want,, upload again ,with a lot more 280Mb PKT files

**Comment by Taaboy** [comment]
Redone and Uploaded

**Comment by Shauren** [comment]
For the record, uploading compressed .pkt files here https://community.trinitycore.org/forum/13-wdbadbsniffs/ is preferred to submitting raw parsed wpp output

**Comment by Taaboy** [comment]
Forget about it , what I have seen in the sniff files, there is no-way I would upload the raw files. I am sorry ,but and it was not raw output, in the file I had put up , I had WPP the data and copy / pasted and from many different file and times till I had all I could get from applying it to the master world DB. Also upon screening thru the outputs I have found that some npc's have a 4th option for the creature_equip_template may need to add 4th ItemID ,case in point Fledgling Brave http://www.wowhead.com/npc=36942/fledgling-brave
1st ID UNIT_VIRTUAL_ITEM_SLOT_ID: 2023/2.834827E-42 = http://www.wowhead.com/item=2023/monster-spear-rusty
 UNIT_FIELD_BYTES_2: 257/3.601337E-43 goes toward the creature_template_addon for Fledgling Brave 

4th ID UNIT_VIRTUAL_ITEM_SLOT_ID + 4: 49462/6.931102E-41 =http://www.wowhead.com/item=49462/monster-gun-tauren-crude
UNIT_FIELD_BYTES_2: 258/3.61535E-43 goes towards the creature_template_addon for Fledgling Brave 
I Feel this is closed
