### ISSUE TITLE
[3.3.5] Core/Spells: High chance to resist spell

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#19143]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** It is common to see numerous resisted spells after recent commits. I'm not saying that the chance to resist is 100% wrong, that is why we need the criteria of the community to enrich this theme.
Some examples to analyze are:
1. Mage: Frostbolt casted by Mirror Images, the copies must inherit the attributes of the mage.
2. Warlock: Succubus Seduction (inherit attributes too?), Curse of the Elements.
3. Life Steal from  [Bryntroll, the Bone Arbiter].
4. Rogue poisons
5. Some Bosses.

**Current behaviour:** High chance to resist spell

**Expected behaviour:** Spells must have a lower chance to be resisted.

**Steps to reproduce the problem:**
1. Try some cases in the Description. 

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  c63f378

**TDB version:**  62

**Operating system:**  W10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Noryad** [comment]
@ariel- @xinef1 ???

**Comment by xinef1** [comment]
Probably placeboo, binaries were never resisted and now when they are, it seems like its too often. Perform some tests and see for yourself.

**Comment by ariel-** [comment]
So, valid?

**Comment by Killyana** [comment]
I got the same feedback from many players, we where using another system for binaries, but after switching to the actual TC system the chance to resist to a binary has become very high.
I'm not sure if it's correct or not, we don't have any reference to compare.

**Comment by ariel-** [comment]
Another thing to note is that boss innate resistance (15 vs lvl 83 bosses with a lvl 80 spellcaster) wasn't implemented before. This resistance can't be overcomed with spell penetration.

**Comment by xinef1** [comment]
It would be best to do some tests

**Comment by Moorgoth** [comment]
I'm not very knowledgeable about the subject but in several guides of disc priest does not recommend spell penetration, actually is common to resist Psychic Scream (vs mage and druids). Then I had to reach 130 spell penetration.

**Comment by Demonid** [comment]
@Moorgoth Thats because most of the guides are made from private servers that dont have Binary Resistances working, on Retail and on Arena Tournament, between 75 and 85 Spell Pen was mandatory for PvP, some guys were even taking +130.

**Comment by Keader** [comment]
I saw it too.
Alot of players here, complaning about Resist in spells like Fear.
Lock with 135 Spell Pene + Curse of Elements vs Shadow Priest, 4 fears, 4 resist.

**Comment by ccrs** [comment]
I think spells like Fear, that leave a negative aura and are binary might be wrongly calculated

````c++
        if (hasAura)
        {
            tmp += victim->GetMaxPositiveAuraModifierByMiscValue(SPELL_AURA_MOD_DEBUFF_RESISTANCE, static_cast<int32>(spellInfo->Dispel)) * 100;
            tmp += victim->GetMaxNegativeAuraModifierByMiscValue(SPELL_AURA_MOD_DEBUFF_RESISTANCE, static_cast<int32>(spellInfo->Dispel)) * 100;
        }

        // resistance for binary spells
        if (spellInfo->HasAttribute(SPELL_ATTR0_CU_BINARY_SPELL) && (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_NORMAL) == 0)
            if ((spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_HOLY) == 0 || victim->GetTypeId() == TYPEID_UNIT)
                tmp += int32(Unit::GetEffectiveResistChance(this, spellInfo->GetSchoolMask(), victim, spellInfo) * 10000.0f); // 100 for spell calculations, and 100 for return value percentage
````

both checks apply

**Comment by ariel-** [comment]
Both are correct. First one applies bonus from SPELL_AURA_MOD_DEBUFF_RESISTANCE (only spell is Sacred Cleansing, whic adds +30% chance to resist)

Second one calculates resist chance for binary spells, this is correct, but I'll push some cleanup commit

**Comment by ariel-** [comment]
Cleanup done in e565b34f6d24411e210151d0d03e524f94cdff85. it won't change things too much though, so closing this as 'blizzlike' unless someone can describe with actual calculations that anything is wrong
