### ISSUE TITLE
Dawning of a new day

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19152]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
You accept this quest, and go to the location of the rally noting is happening. the npc's do not spawn,  and you are not able to complete this quest
**Current behaviour:** (Tell us what happens.)
the npcs do not spawn as a result you are not able to complete this quest
**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. Get quest http://www.wowhead.com/quest=26297/the-dawning-of-a-new-day ( it is part of a chain quest )
2. go to the correct location. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master Branch
**TC rev. hash/commit:**  
941f7d2bbefc
**TDB version:**  
TDB_full_703.00_2016_10_17
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
The quest is not scripted: https://github.com/TrinityCore/TrinityCore/issues/15182

**Comment by nubqt** [comment]
Confirmed still not scripted on master 7334419 TDB 720.00_2017_04_18

Request issue is re-opened so that it can be tackled separately without having to depend on a huge WIP.
