### ISSUE TITLE
Goldtooth

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19151]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
When you do this quest, you go and kill npc Goldtooth. When you try to loot necklace a message appears " Already looted"
**Current behaviour:** (Tell us what happens.)
You are unable to loot quest item
**Expected behaviour:** (Tell us what should happen instead.)
Able to loot quest item after killing the needed NPC
**Steps to reproduce the problem:**

1. Accept quest http://www.wowhead.com/quest=87/goldtooth
2. Go to location that goldtooth is at and kill him and try to loot necklace
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master Branch
**TC rev. hash/commit:**  
941f7d2bbefc
**TDB version:**  
TDB_full_703.00_2016_10_17
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by HannibalRoG** [comment]
Same #18538
