### ISSUE TITLE
Quest: A Gift for the Warchief

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#19157]
**Description:** Thrall does not have the right quest completion text when completing the quest:
https://youtu.be/E5kCq4R4LXM?t=29

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  76f3e0edea88ce8854de11408b0f46bb6b221b49

**TDB version:**  335.62

**Operating system:**  windows

**Comment by greenbagels** [comment]
Vol'jin isn't the Warchief in 3.3.5, you sure it affects both branches?

**Comment by tkrokli** [comment]
I highly doubt it. Thrall is Warchief before Cataclysm, Garrosh comes next and then Vol'jin in the later client versions.

**Comment by Kittnz** [comment]
I'm just saying the gossip text is bad. It doesn't matter who the warchief is lol

**Comment by greenbagels** [comment]
@Kittnz yeah, but I'm saying the video shows Vol'jin using typical troll-style language, which wouldn't need to be fixed in 3.3.5 if Thrall is the one speaking (as he is not a troll).

**Comment by tkrokli** [comment]
> I'm just saying the gossip text is bad. It doesn't matter who the warchief is lol

It does actually matter, because the gossip depends on who is the current Warchief when you open the quest gossip. The `gossip_menu` texts and IDs are different in branch `3.3.5` and `master` because there are 2 different NPCs (Thrall & Vol'jin).

**Comment by Kittnz** [comment]
Oh right, he has different gossip, i didn't even notice. Kay!

**Comment by offl** [comment]
```text
Progress
Well met, <class>. Did you have something for me?

Completion
My "thanks" for this Lovely Charm Bracelet.

**Comment by offl** [comment]
```sql
--
DELETE FROM `quest_request_items` WHERE `ID`=24612;
INSERT INTO `quest_request_items` (`ID`,`CompletionText`,`VerifiedBuild`) VALUES
(24612,'Well met, $c. Did you have something for me?',-1);
DELETE FROM `quest_offer_reward` WHERE `ID`=24612;
INSERT INTO `quest_offer_reward` (`ID`,`RewardText`,`VerifiedBuild`) VALUES
(24612,'My "thanks" for this Lovely Charm Bracelet.',-1);

**Comment by Killyana** [comment]
@offl that's all for this issue?

**Comment by offl** [comment]
Emotes are missing, I'm sure everything here can be found in some old DB(from another project, maybe).

**Comment by offl** [comment]
And there's more similar quests w/o `quest_request_items` and `quest_offer_reward`, I'll check them.

**Comment by offl** [comment]
Done
