### ISSUE TITLE
Gold Dust Exchange

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#19153]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
accept this quest and go kill kobolds to be able to loot gold dust. 
**Current behaviour:** (Tell us what happens.)
When you accept this quest, you are able to loot a few gold dusts from the kobolds. I have tried this a few times and each time you are able to loot a few ( each time I did this it was a different amount) then starts to show a message on screen " already looted" 
**Expected behaviour:** (Tell us what should happen instead.)
You should be able to collect all 10 gold dusts from killing kobolds
**Steps to reproduce the problem:**

1. Accept quest http://www.wowhead.com/quest=47/gold-dust-exchange
2. start killing kobolds and start looting gold dust. at some point it will not let you. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
Master Branch
**TC rev. hash/commit:**  
941f7d2bbefc
**TDB version:**  
TDB_full_703.00_2016_10_17
**Operating system:**  
Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by HannibalRoG** [comment]
This is the same problem #18538
