### ISSUE TITLE
[4.3.4] ubuntu 16.04 make failure

### ISSUE THREAD

**Issue by knope** [TrinityCore/TrinityCore#19158]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Following install guide for linux core installation, make fails (apologies if i'm an idiot).

**Current behaviour:** (Tell us what happens.)
- all libraries accounted for, and at current release version.
- cmake successfully runs
- make runs until 24% and dies

**Expected behaviour:** (Tell us what should happen instead.)
- make should not die

**Steps to reproduce the problem:**
assuming ubuntu 16.04, the following (in sequential order) to be as steps.  Including boost/zeromq pieces missing from the guide to allow cmake to work:

## package prereqs provided from guide
```
apt-get install git cmake make gcc g++ libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev mysql-server p7zip

```

### ZeroMQ
```
wget https://github.com/zeromq/libzmq/releases/download/v4.2.1/zeromq-4.2.1.tar.gz
```
### Boost
```
wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz
```

## CMAKE and flags used:
```
declare -x CFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"
declare -x CXXFLAGS="-m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O0 -g3 -ggdb3 -pipe -msse3 -fno-strength-reduce -fno-delete-null-pointer-checks -fno-strict-aliasing -frename-registers -rdynamic"
cmake ../ -DCMAKE_INSTALL_PREFIX="/wow/trinity/server/bin"
```
## woo that's working let's make...
```
make -j8 -VERBOSE=1
...
[ 24%] Built target g3dlib
make[1]: Leaving directory '/opt/trinity/4.3.4/src/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

 [ aw :*( ]

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
4.3.4

**TC rev. hash/commit:**  
ca20d34f591e197f575387335f8787acaff51a7a

**TDB version:**  
N/A

**Operating system:**  
Ubuntu 16.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Shauren** [comment]
We don't have a 4.3.4 branch

**Comment by knope** [comment]
i'm sorry - i'm lost, intended for https://github.com/TrinityCoreLegacy/TrinityCore.git
