### ISSUE TITLE
hostname instead of an ip address in the realmlist table row address

### ISSUE THREAD

**Issue by bomrox** [TrinityCore/TrinityCore#19174]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
How to make access to one realm on different IP addresses?

My server two IP address for access from different local networks (10.111.0.1 and 10.101.17.231) and a shared host wow.tgwnet.ru who write in realmlist.wtf, but to run the server only or on this IP address 10.111.0.1 or 10.101.17.231, players can go with either one network or the other and not simultaneously obtained.

**Current behaviour:** the problem can be solved if the table realmlist in the address line enter wow.tgwnet.ru but then does not start the server authserver.exe error: Could not resolve address wow.tgwnet.ru for realm.

**Expected behaviour:** 

**Steps to reproduce the problem:**

1. the problem can be solved if the table realmlist in the address line enter hostname: wow.tgwnet.ru

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:** TrinityCore rev. 8d2f2f8f0603 2017-02-10 19:37:54 +0000 (3.3.5 branch) (Win64, Release, Static) (authserver)

**TDB version:**   TDB_full_335.62_2016_10_17

**Operating system:**  win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Stop posting your question everywhere, this belongs to forum, not to tracker, not to wiki.
