### ISSUE TITLE
[3.3.5] BG/Strand of the Ancients: Catapult gains full health after dismount it

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#19178]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Catapults on Strand of the Ancients gains full health after dismount it. Actually de best strategy is dismount and mount catapults.

**Current behaviour:** Catapults gains health after dismount it.

**Expected behaviour:** Catapults should not gains health after dismount it.

**Steps to reproduce the problem:**
1. Mount on catapult.
2. Dismount catapult.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**   1beb2e5

**TDB version:**  62

**Operating system:**  W10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by sirikfoll** [comment]
```diff
diff --git a/src/server/game/Battlegrounds/Battleground.cpp b/src/server/game/Battlegrounds/Battleground.cpp
index 84a539b..c248aed 100644
--- a/src/server/game/Battlegrounds/Battleground.cpp
+++ b/src/server/game/Battlegrounds/Battleground.cpp
@@ -1526,6 +1526,9 @@ Creature* Battleground::AddCreature(uint32 entry, uint32 type, float x, float y,
     if (respawntime)
         creature->SetRespawnDelay(respawntime);
 
+    if (creature->IsVehicle())
+        creature->setRegeneratingHealth(false);
+
     return creature;
 }

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/950
