### ISSUE TITLE
[3.3.5] Spell/Rogue: Glyph of Vanish has no effect

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#19175]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Rogue spell/glyph: Glyph of Vanish does not give any speed increase.
http://wotlk.openwow.com/spell=58038
- Glyph of Vanish: Increases your movement speed by 30% while the Vanish effect is active.

**Current behaviour:** Speed is not increased while the Vanish effect is active.

**Expected behaviour:**  Speed must be increased while the Vanish effect is active.

**Steps to reproduce the problem:**
1. Add Glyph of Vanish (http://wotlk.openwow.com/item=43380)
2. Use Vanish (http://wotlk.openwow.com/spell=1856 / 1857 / 26889)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  1beb2e5 

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Can't reproduce on f948ae80fc9a89f4ba3e22a7e93dd4ca3a13bd70

**Comment by Noryad** [comment]
sorry my bad :disappointed:
