### ISSUE TITLE
Core/Vmaps: vmaps for WMO

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19185]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Players can cast throw WMO

**Current behavior:** Players can cast throw WMO, looks like vmaps are not generated for those map objects.

**Expected behavior:** Players mustn't be able to cast throw WMO

**Steps to reproduce the problem:**

1. Find any WMO
2.  .npc add 321
3.  cast any spell on the npc when you're hidden behind the WMO

Example: .go xyz 304.09, 119.107, 46.741245 0  then cast a spell on the spider when you're behind the tree.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:**  rev. d535b98b057f

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
oh, blizzard is very tricky on this.

**Comment by Killyana** [comment]
You can reproduce this in Warsong Gulch with a tree trunk.

**Comment by Aokromes** [comment]
i mean, blizzard does strange things with obstacles, some trees blocks los others no.

**Comment by Shauren** [comment]
but trees generally are not wmos, they are m2 models that do not block los

**Comment by Killyana** [comment]
It's not only trees but also some building and rocks.

[[http://i.imgur.com/tPHHcX7.jpg|alt=octocat]]

**Comment by joshwhedon** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5430
For reference, this is this issue, and it is back.

**Comment by robinsch** [comment]
I'm pretty sure you could cast through almost everything in WSG.

**Comment by akrom23** [comment]
https://github.com/TrinityCore/TrinityCore/pull/18528 - more info.

**Comment by HelloKitty** [comment]
This was the behavior on retail. It was accepted as the behavior in a 2012 commit [here](https://github.com/TrinityCore/TrinityCore/commit/c53d722aa29ff3a39d881de7d6ef86b79deffe48) which was only reverted because it caused issues with pet pathing.

Warsong Gulch stumps are something that didn't prevent LoS. They're m2s and you can find historical QQ from [melee players](http://www.mmo-champion.com/threads/882446-Warsong-Gulch-Tree-stumps-great-line-of-sight-NOT).

It's to the best of my knowledge how LoS worked on retail in 3.3.5.

**Comment by joshwhedon** [comment]
OK thank you for all the information, feel free to close the bug if you consider the debate finished :D . It's good to know it is the expected behaviour, I was quite surprised myself.

**Comment by Killyana** [comment]
So this is the retail behavior (tested), Even if it doesn't make sense that such objects didn't prevent LOS.
