### ISSUE TITLE
Play a scene from SAI

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#19189]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** I think this function have to be integrated. We should be able to play a scene from SAI by using sceneid
We can use it for example in this quest: http://www.wowhead.com/quest=38813/orders-for-your-captains

Looking into sniff when you talk to a Coilskar this should happen:
After selecting Gossip Option -> do Phase Shift -> play scene 1094 -> give kill credit.

**Current behaviour:** (Tell us what happens.) This function is not integrated

**Expected behaviour:** (Tell us what should happen instead.) Function to be integrated

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/bfe47331957b751b1b5cac37cef54364d361d581

**TDB version:**  703.00 + updates

**Operating system:**  Ubuntu server 16.10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
01ded93
