### ISSUE TITLE
[3.3.5] Quest: Foolish Endeavors - missing question mark

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19188]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)
When you want to turn in quest 11705 [Foolish Endeavors](http://www.wowhead.com/quest=11705) there is no question mark above Garrosh Hellscream.

**Expected behaviour:** (Tell us what should happen instead.)
There should be one, es seen in the video at wowhead.

**Steps to reproduce the problem:**

1. Complete the quest.
2. Go to Garrosh Hellscream. 

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 6d991e9361fd+

**TDB version:**  according to hash

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Please note that the plus sign on the rev. hash means that you have uncommited source changes in your repo, this could mean that you have done modifications to your source.

**Comment by TecDian** [comment]
It is the Nefarian script. Nothing to do with this matter.

**Comment by Killyana** [comment]
Check the npc flag.

**Comment by TecDian** [comment]
npcFlags is 3, in db as well as live. And you get a question mark for [The Plains of Nasam](http://de.wowhead.com/quest=11652). So what's the difference?

**Comment by ariel-** [comment]
Check quest conditions

**Comment by TecDian** [comment]
It's on "Show Gossip Menu Option menu_id 4041/2 id 2 if Quest 30 is taken".

**Comment by TecDian** [comment]
Here the comments from conditions:

_Foolish Endeavors can only be taken if Varidus is near
Foolish Endeavors can only be taken if Varidus is alive
Player must have completed The Foolish Endeavors before been able to accept Hellscream's Champion_

Nothing relevant though. They are just about CONDITION_SOURCE_TYPE_QUEST_ACCEPT.

**Comment by ariel-** [comment]
It's totally relevant. If player does not comply with conditions, the quest mark will not be shown (see #18151)

**Comment by TecDian** [comment]
It shouldn't be relevant, because the conditions above are about accepting quests. Once the quest ist completed, Varidus is dead, or after respawn he is alive again. And of course he isn't near when and where I want to turn in the quest. Doesn't matter because I don't want to take the quest anymore. I have it already.

The other one is about another quest, whether I can or can't take it. Nothing in relation to the first quest at all.

You mistake the missing question mark with a missing exclamation mark, or so it seems. I was not talking about availability. The quest is available and can be turned in. There is just no mark. Go check it.
