### ISSUE TITLE
[3.3.5] Game freeze when accepting quests

### ISSUE THREAD

**Issue by AlexStoiu** [TrinityCore/TrinityCore#19180]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The core was not updated for a while (since 09.02) and today the owner of the realm did some updates, up to the last downloadable one.
After we added the update , accepting a quest freezes the game and you have to force close the game. And they can't log back in unless I clear their quest logs.

**Current behaviour:** (Tell us what happens.)
Custom / Blizzlike quests freeze game.

**Expected behaviour:** (Tell us what should happen instead.)
Quests should not freeze the game

**Steps to reproduce the problem:**

1: Accept any quest ingame

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  
2559874e8dc9+ 
**TDB version:**  
335.62
**Operating system:**  
Core : Linux
Me/Players : Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Caused by: https://github.com/TrinityCore/TrinityCore/commit/dd1aa64563bfb726e1132a135927a02fbb765454#diff-2565b3c627b521ad4ae61717a0ee22c2R343

@ariel- should fix it tonight

**Comment by AlexStoiu** [comment]
Thank you very much for the fast answer.
Also... are you constantly refreshing the page to see new posts?:)) I mean.. you answered like 20 seconds after I made the thread

**Comment by Aokromes** [comment]
we have almost instant notifications on irc of new tickets and pull requests.

**Comment by AlexStoiu** [comment]
Even more epic

**Comment by lumni1968** [comment]
Thank you.
