### ISSUE TITLE
[3.3.5] Warrior - Sunder Armor stack

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19187]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Sunder Armor (7386) trigger spell 58567 (debuff sunder armor)
The spell_group is incorrect
```sql
SELECT * FROM `spell_group` WHERE `id`=1014;
```
Appears 7386 instead 58567

**Current behaviour:** (Tell us what happens.)
Sunder Armor stack with another armor reduction debuff, by example 8647 Expose Armor (Rogue)

**Expected behaviour:** (Tell us what should happen instead.)
Sunder Armor should not stack with another armor reduction debuff, by example 8647 Expose Armor (Rogue)

**Steps to reproduce the problem:**

1. Cast Sunder Armor (Warrior)
2. Cast Expose Armor (Rogue)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/c274ea8a98e9751d50301e99eb55577ba19155f2

**TDB version:**  TDB335.62

**Operating system:**  Debian

**Fix:**
```sql
UPDATE `spell_group` SET `spell_id`=58567 WHERE `id`=1014 AND `spell_id`=7386;
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Funny, noticed another wrong stack while looking this.
