### ISSUE TITLE
[master] Hunter - Disengage

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19193]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
You can't use Disengage when you are out of combat
http://www.wowhead.com/spell=781/disengage

**Current behaviour:**
You can't use Disengage when you are out of combat

**Expected behaviour:**
You can use Disengage when you are in/out of combat

**Steps to reproduce the problem:**

1. Create hunter
2. Level up to 45
3. Change spec to BM
4. Cast Disengage

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/bfe47331957b751b1b5cac37cef54364d361d581

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment]
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Spells/spell_hunter.cpp#L285

**Comment by tkrokli** [comment]
OK, so you think something like this should be the solution?
https://github.com/TrinityCore/TrinityCore/blob/e86a2c439aa2a032ce338d974dae1e5311bcb18f/src/server/scripts/Spells/spell_hunter.cpp#L282-L289

```diff
             SpellCastResult CheckCast()
             {
                 Unit* caster = GetCaster();
-                if (caster->GetTypeId() == TYPEID_PLAYER && !caster->IsInCombat())
+                if (caster->GetTypeId() == TYPEID_PLAYER)
-                    return SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW;
-
-                return SPELL_CAST_OK;
+                    return SPELL_CAST_OK;
             }
```

**Comment by ArcaneFox** [comment]
Yes, this can be a solution.
