### ISSUE TITLE
[3.3.5] Warrior: Victory Rush

### ISSUE THREAD

**Issue by Trystanosaurus** [TrinityCore/TrinityCore#19192]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The warrior skill victory rush can be used as many times as you like (within the 20 seconds after killing an enemy giving honour/xp).

There was a similar issue in 4.3.4 (issue 9539) where the victory rush skill wasn't removing the victorious state. I tried the fix from that issue but that didn't help.

**Current behaviour:** (Tell us what happens.)
You can spam victory rush multiple times after killing an enemy.

**Expected behaviour:** (Tell us what should happen instead.)
You should only be able to use it once after each kill.

**Steps to reproduce the problem:**

1. Level warrior to level 6
2. Kill an enemy worth xp
3. Spam victory rush on his friends

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

**TC rev. hash/commit:**  
d0f76042

**TDB version:**  
335.62 with updates up to 2017_02_22_04_world_335.sql

**Operating system:**  
Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
can be handled by new proc system no?
@ariel- xd

**Comment by ariel-** [comment]
And it was, until big silly me disabled the proc

**Comment by Rushor** [comment]
why don't you test the stuff befor pushing it to the repo?
