### ISSUE TITLE
[master] DB/creature: Huojin Quartermaster

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19201]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Huojin Quartermaster (mop) not spawned
http://www.wowhead.com/npc=69333/disciple-jusi

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/bfe47331957b751b1b5cac37cef54364d361d581

**TDB version:** 703.00 + updates

**Operating system:**  Operating system: Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment]
[SQL WIP]

Huojin Pandaren faction:
> Patch 5.0.1 (Beta): Added

**Comment by funjoker** [comment]
The DB is missing every content above 4.3.4.
3 Expansions missing
