### ISSUE TITLE
After updating some players can't join to server.

### ISSUE THREAD

**Issue by Adizbek** [TrinityCore/TrinityCore#19206]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
My last version was TrinityCore rev. d42faefe9a8c+ 2016-12-23 13:07:49 +0100 (3.3.5 branch) (Unix, Release, Static) 
Current: TrinityCore rev. 278353673639 2017-02-21 21:02:12 +0500 (3.3.5 branch) (Unix, Release, Static)
I even don't know what is happening. Just stops connection while someone want to join. One some of player. Not all. Some players can't speak. Server say. You don't know this language. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#19182
