### ISSUE TITLE
[master] gobject crashes client

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#19203]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** Gameobject Blackwing Descent Elevator (id: 203716) crashes client when player reach it in any location.

**Current behaviour:** Client crash.

**Expected behaviour:** No crashes.

**Steps to reproduce the problem:**

1.  Go to Blackwing Descent or use command .gobject add 203716.
2.  Client will crash.

**Branch(es):** master

**TC rev. hash/commit:**   d7124f0

**TDB version:**  703.00

**Operating system:**  Win 10 x64 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Eredar** [comment]
Same problem for second elevator in this instance. Id: 207834. Only by removing theese gobjects from db I managed to enter blackwing descent.

**Comment by matanshukry** [comment]
I believe this issue is not valid anymore.

I'm not really sure what elevator we're talking about, but I both went to Blackwing Descent and used the supplied .gobject command, client didn't crash on neither.
