### ISSUE TITLE
[master] DB/POI: missing NPCs

### ISSUE THREAD

**Issue by BlackWolfDEsign** [TrinityCore/TrinityCore#19202]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** missing npc's

INSERT INTO `points_of_interest` (`ID`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES
(500, 9845.986, 2460.844, 7, 99, 0, 'Mönchslehrer von Darnassus', 23420),
(501, 10300.74, 2418.637, 7, 99, 0, 'Hexenmeisterlehrer von Darnassus', 23420),
(502, 9654.393, 2510.8, 7, 99, 0, 'Schamanenlehrer von Darnassus', 23420),
(503, 10124.69, 2415.28, 7, 99, 0, 'Bergbau von Darnassus', 23420),
(504, 10147.66, 2353.578, 7, 99, 0, 'Darnassus, Juwelierskunst', 23420),
(505, 10127.96, 2422.82, 7, 99, 0, 'Ingenieurskunst von Darnassus', 23420),
(506, 9608.43, 2531.16, 7, 99, 0, 'Archäologie von Darnassus', 23420);

**Current behaviour:** (Tell us what happens.) some npc's not exist

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** master

**TC rev. hash/commit:**  d7124f0

**TDB version:**  703

**Operating system:**  windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by funjoker** [comment]
English rocks!

**Comment by BlackWolfDEsign** [comment]
INSERT INTO points_of_interest (ID, PositionX, PositionY, Icon, Flags, Importance, Name, VerifiedBuild) VALUES
(500, 9845.986, 2460.844, 7, 99, 0, 'Darnassus, Monk Trainer', 23420),
(501, 10300.74, 2418.637, 7, 99, 0, 'Darnassus, Warlock Trainer', 23420),
(502, 9654.393, 2510.8, 7, 99, 0, 'Darnassus, Shaman Trainer', 23420),
(503, 10124.69, 2415.28, 7, 99, 0, 'Darnassus, Mining Trainer', 23420),
(504, 10147.66, 2353.578, 7, 99, 0, 'Darnassus, Jewelcrafting Trainer', 23420),
(505, 10127.96, 2422.82, 7, 99, 0, 'Darnassus, Engineering Trainer', 23420),
(506, 9608.43, 2531.16, 7, 99, 0, 'Darnassus, Archaeology Trainer', 23420),
(507, -8941.56, 783.764, 7, 99, 0, 'Stormwind, Tailoring Trainer', 23360),
(514, -8431.96, 687.125, 7, 99, 0, 'Stormwind, Mining Trainer', 23360),
(513, -8717.89, 464.542, 7, 99, 0, 'Stormwind, Leatherworking & -skinning', 23360),
(512, -8709.56, 621.618, 7, 99, 0, 'Stormwind, Jewelcrafting Trainer', 23360),
(515, -8979.49, 763.873, 7, 99, 0, 'Stormwind, Alchemy & Herbalism', 23360),
(511, -8801.98, 770.842, 7, 99, 0, 'Stormwind, Fishing Trainer', 23360),
(509, -8521.81, 816.241, 7, 99, 0, 'Stormwind, First Aid Trainer', 23360),
(510, -8365.68, 631.149, 7, 99, 0, 'Stormwind, Engineering Trainer', 23360),
(542, -8854.98, 800.08, 7, 99, 0, 'Stormwind, Enchanting Trainer', 23360),
(541, -8634.73, 415.613, 7, 99, 0, 'Stormwind, Inn', 23360),
(540, -8424.52, 616.797, 7, 99, 0, 'Stormwind, Blacksmithing Trainer', 23360),
(539, -8780.08, 378.651, 7, 99, 0, 'Stormwind, Riding Trainer & Mounts', 23360),
(538, -8767.48, 408.564, 7, 99, 0, 'Stormwind, Honor & Conquest Quartermaster', 23360),
(537, -8804.8, 348.023, 7, 99, 0, 'Stormwind, Valor Quartermaster', 23360),
(536, -8849.51, 500.269, 7, 99, 0, 'Stormwind, Flying Trainer & Flying Mounts', 23360),
(535, -8432.87, 555.121, 7, 99, 0, 'Stormwind, Stable Master', 23360),
(534, -8979.49, 763.873, 7, 99, 0, 'Stormwind, Alchemy & Herbalism', 23360),
(533, -8209.47, 428.528, 7, 99, 0, 'Portal to Stormwind', 23360),
(532, -8432.65, 319.663, 7, 99, 0, 'Stormwind Castle', 23360),
(531, -8789.09, 827.214, 7, 99, 0, 'Stormwind Stockade', 23360),
-- (530, -8766.67, 1033.05, 7, 99, 0, 'Die Löwenruh', 23360),
(529, -8371.78, 604.283, 7, 99, 0, 'Stormwind, Inn', 23360),
(528, -8862.7, 665.363, 7, 99, 0, 'Stormwind, Inn', 23360),
(527, -8887.54, 602.309, 7, 99, 0, 'Stormwind, Guild Master', 23360),
(526, -8182.733, 545.3889, 7, 99, 0, 'Stormwind, Monk Trainer', 23360),
(525, -8788.16, 344.498, 7, 99, 0, 'Stormwind, Warrior- & Hunter Trainer', 23360),
(524, -8945.1, 991.033, 7, 99, 0, 'Stormwind, Warlock Trainer', 23360),
(523, -8356.92, 574.814, 7, 99, 0, 'Stormwind, Shaman Trainer', 23360),
(522, -8716.23, 328.47, 7, 99, 0, 'Stormwind, Rogue Trainer', 23360),
(521, -8582.43, 806.635, 7, 99, 0, 'Stormwind, Cathedral', 23360),
(520, -9010.27, 852.878, 7, 99, 0, 'Stormwind, Mage Trainer', 23360),
(518, -8424.14, 551.444, 7, 99, 0, 'Stormwind, Hunter Trainer', 23360),
(457, -8282.65, 716.852, 7, 99, 0, 'Stormwind, Druid Trainer', 23360),
(507, -8327.83, 598.797, 7, 99, 0, 'Stormwind, Bank', 23360),
(508, -8363.9, 658.161, 7, 99, 0, 'Stormwind, Auction House', 23360),
-- (516, -8697.185, 847.6458, 7, 99, 0, 'Die Drei Winde', 23360),
(517, -8287.219, 515.5816, 7, 99, 0, 'Stormwind, Battle Pet Trainer', 23360);

**Comment by tkrokli** [comment]
1. Always use a `DELETE FROM` query before `INSERT INTO` queries in TC to make the SQL repeatable.
2. Always include back ticks around table names and column names (or select the name and use the `<>` edit toolbar button to add them).
3. To show SQL syntax highlighted on github, use **```sql** on a blank line above your query (Github Markdown).
4. If you need to write normal text below the SQL code block, put only **```** on a line below the query.

**Comment by Aokromes** [comment]
A lot of POIs where fixed by malcrom few weeks ago, if some are missing open a new ticket for the missing ones.
