### ISSUE TITLE
Quest Issue: The Missing Diplomat ID 1249

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19200]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

If you die while fighting Tapoke Jahn (Entity 4962) during the quest The Missing Diplomat (ID 1249) objective becomes completed rather than failed.

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

You should fail the quest when you die.

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
3.3.5
**TC rev. hash/commit:**  
691d52daa9be
**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
you known, i found this on retail with another escort quest as long escorted mob survives... soooo it's blizzlike.

**Comment by Elarose** [comment]
If the guards dps him down to friendly even if you die -then- it will complete the quest. I cannot reproduce the quest completion just by dying, he just runs away and it doesn't complete. Are you sure the guards didn't dps him down?

 There is a bug here however, missing texts from Slim and his friends, as seen here.

https://www.youtube.com/watch?v=tMRfdjbVJTg

His friends: 
Whoa! This is way more than what I bargained for, you're on your own, Slim!

Slim:
Oh, it's on now! But you thought I'd be alone too, huh?!
Okay, okay! No need to get all violent. I'll talk. I'll talk!
I have a few notes from the job back at my place. I'll get them and then meet you back in the inn.

**Comment by jerbookins** [comment]
> If the guards dps him down to friendly even if you die -then- it will complete the quest. 

That's a very good point and I did not consider it.
