### ISSUE TITLE
[master] Worldserver crash talking to certain npcs

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#19218]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
After accepting the quest Something's Amiss and talking to Prince Liam Greymane the server crashes
**Current behaviour:** (Tell us what happens.)
worldserver.exe crashes
**Expected behaviour:** (Tell us what should happen instead.)
You should be able to turn in above quest to Prince Liam Greymane
**Steps to reproduce the problem:**

1. Create any worgen charakter
2. Accept the quest Lockdown! http://www.wowhead.com/quest=14078/lockdown
3. Turn in Lockdown! at Lieutenant Walden, accept the quest Something's Amiss http://www.wowhead.com/quest=14091/somethings-amiss
4. Go back to Prince Liam Greymane, notice how nothing is phased and he doesn't have a questionmark over his head
5. Rightclick him anyway
6. Get kicked from the server by crashed worldserver.exe

**Crashlog:** https://gist.github.com/AlcDenat/eaea13374075441b1e240d19911f10a1

**Branch(es):** master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:**  8ad043ba692a 

**TDB version:**  TDB_world_703.00_2016_10_17.sql + Updates

**Operating system:** Windows Server 2016 standard (with gui)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment]
Same here:
https://github.com/TrinityCore/TrinityCore/issues/11201

**Comment by Vincent-Michael** [comment]
you should building in debug and post the crashlog

**Comment by AlcDenat** [comment]
Attached the crashlog with 8ad043ba692a on first post.

**Comment by HannibalRoG** [comment]
I don´t have any modifications of db2 files.

**Comment by HannibalRoG** [comment]
Any news with this crash?

**Comment by DJScias** [comment]
Hello there.

Noticed this crash as well and it got introduced with this (breakpointed it): https://github.com/TrinityCore/TrinityCore/commit/bc2380e105404535ebb89b6a379ba9bc9454acfc

Reverting that commit stops it from happening. No clue personally what went wrong though.

Kind regards,
DJScias

**Comment by Pixel-Pirate** [comment]
confirm. Crash with all npcs with gossip menu.

**Comment by ViserionLIVE** [comment]
confirmed
