### ISSUE TITLE
NPC attacking while stunned

### ISSUE THREAD

**Issue by mohamedsalah** [TrinityCore/TrinityCore#19225]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

On stunning Southsea Freebooter mobs it still can attack me using ranged weapon

**Current behaviour:** on stunning the mobs it still able to attack me with its ranged weapon

**Expected behaviour:**

it should be stunned and unable to do anything

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:**  565a6623f3d4

TrinityCore rev. 565a6623f3d4 2017-02-19 14:23:11 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon) ready...

**TDB version:**  TDB_full_335.62_2016_10_17 and updated to 2017_02_19_00_world.sql

**Operating system:** Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
that hash don't belongs to trinitycore repository, test on a clean trinitycore.
