### ISSUE TITLE
Problem with escort quest criteria fulfillment

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19221]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Escort quest not rewarded to other party members upon successful completion.

**Current behaviour:**
Our party leader started the quest Hints of a New Plague (660), upon which the game asked if the other members of the party wished to accept the quest. After the successful completion of the escort quest, only the party leader had the quest completed for turn-in.

**Expected behaviour:**
All party members should receive quest completion following successful escort of NPC.

**Steps to reproduce the problem:**

1. Form group, all members present
2. One person starts quest Hints of a new plague (660)
3. All members accept quest when prompted.
4. Escort NPC
5. Only leader will have quest completed.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 3da60f84000b 2017-02-27 22:52:48 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
I don't know how to tell.

**Operating system:**
Win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/18901
