### ISSUE TITLE
Core/SAI: Update Template sai action broke waypoints

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19223]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** For npcs that load or reset a template on respawn if they have a waypoint movement (waypoint_data) the waypoint will not start after a respawn. 
Example: http://www.wowhead.com/npc=19354/arzeth-the-merciless
(19354, 0, 5, 0, 25, 0, 100, 0, 0, 0, 0, 0, 36, 19354, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Arzeth the Merciless - On Reset - Update Template To 'Arzeth the Merciless'");

**Current behaviour:** Update Template breaks the waypoint.

**Expected behaviour:** Update Template musn't break the waypoint.

**Steps to reproduce the problem:**

1. .go c id 19354
2. .die then .respawn
3. Notice the npc will not start the waypoint after it respawn
4. `DELETE FROM smart_scripts WHERE entryorguid=19354 AND source_type=0 AND id=5;`
5. .die the .respawn and notice the npc will start the waypoint after it respawn

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 8f2bcd79da39

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Why does the npc have a smart script to "update template" to same entry?

**Comment by Rushor** [comment]
the fix was added in 2016_09_19_05_world.sql

**Comment by Killyana** [comment]
ariel_ because the original entry in not restored on evade or in respawn.

**Comment by ariel-** [comment]
But does the script to update template to 19354 work while he has entry 20680?

Curious that 20680 hasn't smartAI defined

**Comment by tkrokli** [comment]
Could the disabled waypoint movement be caused by not getting the `MovementType (2)` from the `creature` table on reset, but instead getting `MovementType (1)` applied from `creature_template` as the active value?

**Comment by ariel-** [comment]
Yes, also missing in SAI action.
