### ISSUE TITLE
Guardian of Icecrown creature_text typo

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19226]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
It is really a very minor thing. In 2016_08_24_08_world.sql there was a little mistake concerning the creature_text for the Guardian of Icecrown.

**Current behaviour:**
Instead of: "%s fleets after seeing Kel'thuzad fall!"

**Expected behaviour:**
it must be: "%s flees after seeing Kel'Thuzad fall!"

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 6d991e9361fd
**TDB version:**  according to hash
**Operating system:** Windows 10

You may use:
```sql
DELETE FROM `creature_text` WHERE `entry`=16441 AND `groupid`=0;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`probability`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(16441,0,0,"%s flees after seeing Kel'Thuzad fall!",16,100,12391,3,"Guardian of Icecrown EMOTE_FLEE");
```

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Hmm, well, OK. If you add the missing columns in your SQL (all containing zeros), it should look like this:
```sql
DELETE FROM `creature_text` WHERE `entry`=16441 AND `groupid`=0;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(16441, 0, 0, "%s flees after seeing Kel'thuzad fall!", 16, 0, 100, 0, 0, 0, 12391, 3, "Guardian of Icecrown EMOTE_FLEE");
```
This is only to be able to compare the row directly with the SQL output from
```sql
SELECT * FROM `creature_text` WHERE `entry`=16441 AND `groupid`=0;
```
TrinityCore rev. ff43a7482263 2017-02-28 16:39:59 -0300 (3.3.5 branch) (Win64, Release, Static)
```
entry  groupid      id  text                                       type  language  probability   emote  duration   sound  BroadcastTextId  TextRange  comment                          
-----  -------  ------  ---------------------------------------  ------  --------  -----------  ------  --------  ------  ---------------  ---------  -------------------------------
16441        0       0  %s fleets after seeing Kel'thuzad fall!      16         0          100       0         0       0            12391          3  Guardian of Icecrown EMOTE_FLEE
```

Then again, seeing that it is only the `text` field which needs changing, we should use an `UPDATE` query instead.

**Suggested solution:**
```sql
UPDATE `creature_text` SET `text`= "%s flees after seeing Kel'Thuzad fall!" WHERE `entry`= 16441 AND `groupid`=0;
```
I am also thinking that the server should show the text from the `broadcast_text` table directly, but I could be mistaken.
