### ISSUE TITLE
[3.3.5][Build] Linking problems after last 3 commits

### ISSUE THREAD

**Issue by avengerweb** [TrinityCore/TrinityCore#19224]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Linking problems after last 3 commits

**Current behaviour:**
Build log, include linking errors:
https://gist.github.com/anonymous/ee813bb0e3975df6e61b2c2426b3d6f0

**Steps to reproduce the problem:**
Compile without any options in cmake

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
3da60f84000bd7ffa5a1516839b84cdee4764448
Problems starts after last 3 commits

**Operating system:** 
Linux 3.16.0-4-amd64 Debian Jessie 
CMake: 3.5.2
GCC: 4.9.2 / CLang 3.9
Boost: Fails on both 1.55(from debian repo) / 1.63(compiled)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Confirmed with clang 3.8.

**Comment by Naios** [comment]
Yes you are right, the issue is present when linking statically.

**Comment by Shauren** [comment]
afaik this will require dropping game-interface

**Comment by Naios** [comment]
The error only seems related to `npc_escortAI, theoretically we can create the object files without depending on `game` until the worldserver is linked (as far as I know).

**Comment by Naios** [comment]
This is very strange, the error seems related to the linking order somehow:

```sh
nm --demangle libgame.a | grep npc_escortAI::AttackStart
0000000000000060 T npc_escortAI::AttackStart(Unit*)
```

I'll revert the commit for now as long as there is no solution found, thanks for reporting.
