### ISSUE TITLE
[3.3.5] Crash when reloading a new item

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19222]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** If you add a new item to item_template and then do .reload item_template ingame, and add the new item to yourself, the server crashes when the packet HandleSingleQueryItem is sent.

This happened after: https://github.com/TrinityCore/TrinityCore/commit/dd1aa64563bfb726e1132a135927a02fbb765454#diff-c6259c64bbf52e1df9176688935b9e82

**Current behaviour:** Explained above.

Crashlog: https://gist.github.com/Persephone/7cec22fba0dd5c37b50c91770cfb067f

**Expected behaviour:** The core shouldnt crash when reloading a new item

**Steps to reproduce the problem:**

(Make sure that CacheDataQueries is set to true in configs)

1.  Step 1 Add any new item, or edit a current item entry to a new one
2. Step 2 .reload item_template ingame
3. Step 3 Add the new item to your inventory or anyone elses, core crashes instantly.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/8f2bcd79da39ef9448938842de32b6f8572facdf

**TDB version:**  64

**Operating system:** ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Persephone** [comment]
Note: this is with CacheDataQueries set to 1 (enabled)

**Comment by AlexStoiu** [comment]
Make sure to copy  CacheDataQueries line from new worldserver to your normal one and set it to 0

**Comment by Persephone** [comment]
@AlexStoiu  What do you mean? I already have the config, I am saying if the config is enabled the server crashes when reloading a new item.

**Comment by Shauren** [comment]
.reload item_template is not a TC command
