### ISSUE TITLE
[3.3.5] "Diseased Young Wolf" & "Diseased Timber Wolf" Aggro

### ISSUE THREAD

**Issue by kaytotes** [TrinityCore/TrinityCore#19235]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Diseased Young Wolf and Diseased Timber Wolf Aggro

**Current behaviour:**

When right clicking a Diseased Young Wolf or Diseased Timber Wolf as a melee class the NPC aggros and attacks you despite being a great distance away.

![image](https://cloud.githubusercontent.com/assets/7526918/23517867/89ae6f52-ff69-11e6-82cc-70338f33f4b6.png)

**Expected behaviour:**

Should not aggro and attack.

**Steps to reproduce the problem:**

1. Create Human Warrior
2. Right Click Diseased Wolf3

**Branch(es):** 3.3.5

https://github.com/TrinityCore/TrinityCore/commit/ecfb346d1af39305923db1f19a4568355c4d94e5

**TDB version:**  TDB 335.62

**Operating system:** Windows

**Proposed Fix**

`UPDATE creature_template SET flags_extra=2 WHERE entry=299; -- Diseased Young Wolf`
`UPDATE creature_template SET flags_extra=2 WHERE entry=69; -- Diseased Timber Wolf`

**Existing Issue:** https://github.com/TrinityCore/TrinityCore/issues/8561

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
This is weird, but even if it's an issue, using flags_extra=2 is not the proper way to fix it.

**Comment by kaytotes** [comment]
I agree setting the wolves to dragonkin isn't correct but it might help greater minds track the root cause.

**Comment by Elarose** [comment]
Confirmed. Nice find. =)

**Comment by MrSmite** [comment]
I don't know if this is a bug or not, I can't remember how retail 335 was.

In Trinity however, this is because a right-click adds you to the creature's attacker list regardless of wether you actually hit them or not. When the AI iterates over the list, it is no longer empty so the creature aggros.

**Comment by kaytotes** [comment]
I'm unsure if there is a flag that controls that functionality because I would assume that if what you say is the case this would be affecting much more but I can only find an instance of this occurring with these NPCs

**Comment by Elarose** [comment]
https://youtu.be/nvPSKTsvObk?t=193
https://youtu.be/qQTO4RKli_k?t=22
https://youtu.be/Wpoi11vNh1c?t=52

Some videos, none run at the people they have to actively engage them targeting isnt enough.. though it would have been a great time saver for melee!

**Comment by MrSmite** [comment]
> Some videos, none run at the people they have to actively engage them targeting isnt enough.. though it would have been a great time saver for melee!

Except the OP specifically mentioned *right-click* which is an attack, not just *targeting*. You can't tell from a YouTube video if the player left or right clicked on the target.

**Comment by ariel-** [comment]
Honestly, makes no sense a creature with neutral standpoint (yellow) attacks a player only because the player gave the order to attack (no damage was inflicted, and way out of melee range)

**Comment by Elarose** [comment]
Yeah you can tell, right click causes fight animation to start, where left click just causes it to target and your character to stand there. Thats why https://youtu.be/nvPSKTsvObk?t=194 <-- you see him take his staff off his back and get ready to 'whack' because hes right clicked it. If he had left clicked it the wolf would be targeted but his player would stand there not removing staff. (He then hits his spell which causes weapon sheath) hes definitely right clicked it.

**Comment by MrSmite** [comment]
> PS2: This was for some guy that deleted comment, in case you're wondering

Yes, that was my original comment. I removed it because the first time I loaded the videos they were in 144p and I didn't notice the text on the screen. I updated YouTube+ addon and was able to see them in better quality.

At the tmie there were no other posts after mine so I decided to remove it.
