### ISSUE TITLE
Add percentage to worldserver when getting zone/area data

### ISSUE THREAD

**Issue by LuigiElleBalotta** [TrinityCore/TrinityCore#19230]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Need to implement percentage when setting Calculate.Creature.Zone.Area.Data and Calculate.Gameobject.Zone.Area.Data to 1 to let the user understand that worldserver is not frozen (in Ubuntu server for example it would be useful rather than Windows)

**Current behaviour:**
Feature not implemented 

**Expected behaviour:**

Feature to implement

**Steps to reproduce the problem:**

1. nano worldserver.conf
2. Calculate.Creature.Zone.Area.Data = 1
3. Calculate.GameObject.Zone.Area.Data = 1

**Branch(es):**
both

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8ad043ba692ad4cfaca24fb086053ae046467b4e

**TDB version:** Latest + updates

**Operating system:** Ubuntu server 16.10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
every load thing usually has "Loading table <name>..." and then "Table <name> loaded in <time>". This approach could be used in this case too.

p.s.: if you run worldserver with valgrind it takes around 20 minutes to start but you know it's not frozen, it's just the amount of time it takes.

**Comment by LuigiElleBalotta** [comment]
Ok but it would be nice see the percentage too like mapextractor.. just for information purpose..

**Comment by Shauren** [comment]
You know that we deleted all progress bars because they made startup slow?

**Comment by DDuarte** [comment]
They are slow if we are writing to output every "action"; if it's buffered (or each N "actions") then it has no impact whatsoever (exactly what happened in WPP).
