### ISSUE TITLE
[3.3.5] Paladin - Seal of Vengeance / Seal of Corruption

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19239]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
ID - 31801 Seal of Vengeance
ID - 53736 Seal of Corruption
ID - 53595 Hammer of the Righteous

old issues:
https://github.com/TrinityCore/TrinityCore/issues/1243
https://github.com/TrinityCore/TrinityCore/issues/1461

**Current behaviour:**
Seal of Vengeance / Seal of Corruption don't proc with Hammer of the Righteous

**Expected behaviour:**
Seal of Vengeance / Seal of Corruption should be proc with Hammer of the Righteous

**Steps to reproduce the problem:**
1. Use Seal of Vengeance / Seal of Corruption
2. Use Hammer of the Righteous

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/ff43a74822630c11851abae4cba35a6542e0c86a

**TDB version:**  TDB335.62

**Operating system:** Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
I rewrote Seal of Vengeance logic as it was badly implemented and not blizzlike.

Stacks are only generated by auto attack (white swings). What is procced by other spells is the damage part. Do you have any source stating that hammer of the righteous should stack the debuff?

**Comment by Jildor** [comment]
Yep, in old issues are more info:
http://wowwiki.wikia.com/wiki/Seal_of_Vengeance

> Note that only normal melee swings can apply the debuff, with the exception of Hammer of the Righteous. Attacks like Divine Storm and Crusader Strike will not apply or refresh the DoT, though they do gain the direct holy damage bonus if the DoT has 5 stacks.
