### ISSUE TITLE
Core/Gameobject: Gameobject type 1 remain closed

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19248]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** After https://github.com/TrinityCore/TrinityCore/commit/7567cafec84080d26ea513242a1f540a823b8f9d#diff-fe5c8ebb7ad8e663836b00f39eb524d6L620
Doors with data2=0 doesn't open any more

**Current behavior:** Gobs type 1 (and may other type) doesn't  open or change state if data2: autoClose (Time in milliseconds)=0

**Expected behavior:** Doors with data2=0 must open And remain open

**Steps to reproduce the problem:**

1. .go obj 32442
2. click the lever
3. the Cell Door will remain closed

4- execute this:```UPDATE `gameobject_template` SET  data2=3000 WHERE `entry` IN (18934); ```
5.go obj 32442
6. click the lever
7. The Cell Door will open

**Branch(es):**3.3.5

**TC rev. hash/commit:** rev. 15a207fcac15

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
@xinef1 Can you take a look to this?

**Comment by xinef1** [comment]
Sure,

```diff
GameObject::UseDoorOrButton

-    m_cooldownTime = GameTime::GetGameTimeMS() + time_to_restore;
+    m_cooldownTime = time_to_restore ? (GameTime::GetGameTimeMS() + time_to_restore) : 0;
```
Can you test?

**Comment by Killyana** [comment]
Works fine.

**Comment by ariel-** [comment]
071ba2c924ce4b27c9e16b38277ac729500f7445
