### ISSUE TITLE
[3.3.5] Many DBErrors when startup.

### ISSUE THREAD

**Issue by freejerry** [TrinityCore/TrinityCore#19240]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

There are many DBErrors when startup the worldserver.

**Current behaviour:**

DBErrors like:
...
Spell Id 72650 has DBC ProcFlags 69972, but it's of non-proc aura type, it probably needs an entry in `spell_proc` table to be handled correctly.
...
SmartAIMgr::LoadSmartAIFromDB: Entry 10680 SourceType 0, Event 4, Missing Repeat flag.
...

**Steps to reproduce the problem:**

1. Startup the worldserver and will get errors in the log file.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 63236f97af03 2017-03-03 14:54:11 +0100 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB 335.62

**Operating system:** 

The worldserver run with Ubuntu 16.04.
The client run with Windows 10.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/18542

**Comment by freejerry** [comment]
Why close the issue?
There are 2 types of error massage.
The second type of message is not similarly to #18542.

**Comment by tkrokli** [comment]
I have added the entire content of DBErrors.log (based on rev. f22fd77 2017-03-04 13:21:47 +0100) in my latest post in issue #18542 so you will find it there now.
