### ISSUE TITLE
Spawns in Pools set only at server restart, not on respawn

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19257]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Bloodstone Ore (ID 4278) mining nodes (ID 2653) do not appear in Drywhisker Gorge (Arathi Highlands) for the quest "Favor for Krazek" (ID 627)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 8e865a60c815 2017-03-07 20:20:19 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 
TDB 335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jerbookins** [comment]
During the time it took me to write this issue, one node did appear. But only one. I sat for about another half hour and waited but only saw the one node and it did not respawn.

**Comment by offl** [comment]
The main problem described here: https://github.com/TrinityCore/TrinityCore/issues/12176#issuecomment-260728044

**Comment by jerbookins** [comment]
I'm sure I'm missing something, but what does this issue have to do with the Silithid Invader issue?

**Comment by offl** [comment]
> However I also found that spawns in pools only gets set at server restart not on respawn so the same will always spawn until restart then will spawn differently.

**Comment by tkrokli** [comment]
Should this issue be renamed to a more general/generic "**Spawns in Pools set only at server restart, not on respawn**" ?

**Comment by offl** [comment]
Yes.

**Comment by dikkedeur** [comment]
i dont know if this is the same behavior but i experience a good amount of veins and herbs in area's ( due me increasing the max pool in database ) BUT after some time playing it seems they dont respawn.
so in short you mine them and it gets less and less and before you know it you only have a few spawns in those area's..
seems there is a respawning problem with objects in pools in general.

**Comment by tkrokli** [comment]
Thank you for your feedback. Please add your **core rev. hash** (like the `.server info` line from your console) to your comment so we know how updated your source is.

**Comment by dikkedeur** [comment]
TrinityCore rev. a4e2c29fba1f 2017-10-01 23:38:08 +0200 (3.3.5 branch) (Unix, Debug, Static)

**Comment by offl** [comment]
Yep, I remember that problem, I think this bug is old as pools implementation. But it is another issue.

**Comment by tkrokli** [comment]
(merged 2 comments from the same date)

**Comment by offl** [comment]
The bug from https://github.com/TrinityCore/TrinityCore/issues/19257#issuecomment-334992513 was probably reported in https://github.com/TrinityCore/TrinityCore/issues/11141

**Comment by Killyana** [comment]
Doesn't looks fixed for me, Try to kill this npc then respawn them many times, you will end with none of them spawned:

guid, pool_entry, chance, description
21317, 32492, 0, Silithyd Hive Drone
86076, 32492, 0, Silithyd Invader
86077, 32493, 0, Silithyd Invader
21318, 32493, 0, Silithyd Hive Drone
21314, 32494, 0, Silithyd Hive Drone
86075, 32494, 0, Silithyd Invader
21324, 32495, 0, Silithyd Hive Drone
86079, 32495, 0, Silithyd Invader
86078, 32496, 0, Silithyd Invader
21323, 32496, 0, Silithyd Hive Drone
21325, 32497, 0, Silithyd Hive Drone
86080, 32497, 0, Silithyd Invader
21327, 32498, 0, Silithyd Hive Drone
86081, 32498, 0, Silithyd Invader

**Comment by lachtanek** [comment]
I can imagine it not working for pools with max <= ~5 spawns which are equally chanced (chance = 0) because of the thing I mentioned in the first TODO in my PR, not sure if that piece of code is retail-like or not and definitely should not be effective for smaller pools.

**Comment by Killyana** [comment]
Lot of pools have max <= ~5  for example rare creatures with 2 or 3 spawn positions.

**Comment by lachtanek** [comment]
Thats true, dont know why i didnt think about it.
It can be fixed by removing the weird urand check in https://github.com/TrinityCore/TrinityCore/commit/de80cd2e0de470522a734e8e7a65e81b82bfc5fb#diff-90acd023cd4bbb796987fe7e52212398R356 , but there are more problems with this pool implementation I think, but I don't really know what is blizzlike so I can't really fix it.

**Comment by offl** [comment]
For example this is blizzlike fix(there's 3 spawns in total):
```sql
DELETE FROM `pool_template` WHERE `entry` = 1668;
INSERT INTO `pool_template` (`entry`,`max_limit`,`description`) VALUES 
(1668,1,'QUEST OBJECT - Bijou''s Belongings - 175334');

DELETE FROM `pool_gameobject_template` WHERE `id` = 175334;
INSERT INTO `pool_gameobject_template` (`id`, `pool_entry`, `chance`, `description`) VALUES
(175334,1668,0,'Bijou''s Belongings');
```

**Comment by offl** [comment]
To avoid misunderstandings: the comments up to https://github.com/TrinityCore/TrinityCore/issues/19257#issuecomment-334992513 (including https://github.com/TrinityCore/TrinityCore/issues/19257#issuecomment-334992513) are related only to https://github.com/TrinityCore/TrinityCore/issues/11141 and not to this issue.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21331
