### ISSUE TITLE
[3.3.5] NPC Pathfinding

### ISSUE THREAD

**Issue by AlexStoiu** [TrinityCore/TrinityCore#19259]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

NPC's run through walls or walk in the air

**Current behaviour:**
When I pull a mob for example.. and I go behind a wall , he clips through walls to get me.

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

NPC's should walk around the walls and structures not through them.

**Steps to reproduce the problem:**

1: Pull a hostile NPC and hide behind a wall , you will see him popping out from within the wall

**Branch(es):**

3.3.35

**TC rev. hash/commit:** 

TrinityCore rev. f96f1cebd4ea+ 2017-02-21 17:14:11 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  
335.62

**Operating system:** 
My OS : Windows
Server OS : Linux

Side note: I'm not a pro in core deving and such ... but someone told me it's a pathfinding problem / mmaps problem.

I have mmaps enabled => mmap.enablePathFinding = 1

Could someone else test this  on their realm? So I can see if it's from my realm or global.

Hope there is a fix for this.

Thank you

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
So... did you enable mmaps?

**Comment by AlexStoiu** [comment]
mmap.enablePathFinding = 1
Yes they are enabled.

**Comment by Aokromes** [comment]
can you supply creature ids? also, i sugest you to update  core.

**Comment by AlexStoiu** [comment]
16244 - Infectious Ghoul
27287 - Mindless Wight
27228 - Death Knight Champion 
(all hostiles so far)

And yes I will update the core this weekend. But I didn't see any updates related to this

**Comment by matheusmcardoso** [comment]
This happens a lot when i'm fighting ranged creatures and i hide behind a wall.
(eg: trolls in Grom'ol)

Also, i've seen them casting successfully a lot through hills. Not sure how related it could be.
I might open a separate issue with more details for that.

**Comment by Aokromes** [comment]
2nd part is 100% blizzlike.

**Comment by jerbookins** [comment]
@matheusmcardoso Casters can hit you through trees, ground, and other misc objects such as certain types of walls in STV. Though, most walls cannot be cast through and LOS pulling works.

**Comment by AlexStoiu** [comment]
Thing is it's not about ranged npcs.
Melee npcs just go through walls when chasing me.

**Comment by matheusmcardoso** [comment]
>Thing is it's not about ranged npcs.
Melee npcs just go through walls when chasing me.

Definitely. I only provided ranged as an example since they are the only reason i hide behind walls.

**Comment by AlexStoiu** [comment]
Anyone found a fix? Or should I come back after I updated the core?

**Comment by Traesh** [comment]
What's the size of your mmap folder ?

**Comment by Aokromes** [comment]
I tested with 27287 on 8e865a60c815 and walked around one house and they don't ignore walls.

**Comment by AlexStoiu** [comment]
TrinityCore rev. 340ce38e01fe+ 2017-03-08 18:26:41 +0200 (3.3.5 branch) (Unix, Release, Static)

Same thing.. and I updated the core.

**Comment by AlexStoiu** [comment]
@Aokromes Hey, Could you share the Mmaps you have? and Vmaps? Cause I updated to the latest version and it still happens.

**Comment by Rushor** [comment]
mmaps and vmaps will not be profided by tc or tc member
