### ISSUE TITLE
Core/SAI: SMART_ACTION_SET_EVENT_PHASE

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19250]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** The SAI action SET EVENT PHASE is no longer working.

**Steps to reproduce the problem:**

1. Execute this:
``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=321;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321) AND source_type=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(321,0,0,0,1,0,100,1,5000,5000,0,0,22,32,0,0,0,0,0,1,0,0,0,0,0,0,0,"npc - Ooc norepeat - set event phase 32"),
(321,0,1,0,1,32,100,0,7000,7000,7000,7000,37,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"npc - Ooc (pahse event 32) - kill self");
```
2. .npc add temp 321 (stay on gm on if your character is from the horde)
3. Notice the action set event phase triggered by event ooc on phase 32 is not executed and the npc is not killig its self.
4. You can also test this issue with this quest: http://woehead.way-of-elendil.fr/?quest=11537

``` sql
SELECT * FROM smart_scripts WHERE entryorguid IN (23310, 25002);
UPDATE `smart_scripts` SET `event_param3`=4000, `event_param4`=4000 WHERE `entryorguid` IN (23310) AND `source_type`=0 AND `id`=2; -- this fix will be added in a next commit
-- notice the npc 23310 will summon the Emissary of Hate only once as the action that must reset the event phase (Fel Portal Alarm - Out of Combat - Set Event Phase 0 (Phase 32)) doesn't happen.
```
**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 15a207f

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
May be related to https://github.com/TrinityCore/TrinityCore/commit/b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88#diff-37386cc2d45348bf6f906a4b67839e42L269
@xinef1 can you take a look?

**Comment by xinef1** [comment]
The phase you set is integer and not bit mask (action 22, phase 32 is invalid, should be 22, 6)

**Comment by Killyana** [comment]
Yes I tested with event phase 2 and it works, so probably the reset using the event phase 0 is not working.

**Comment by xinef1** [comment]
By reset you mean 22, 0? See no errors in code (poke me on irc, will be quicker)

**Comment by Killyana** [comment]
Thanks for the help.
