### ISSUE TITLE
Quest Stranglethorn Fever problems

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19258]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The quest Stranglethorn Fever (ID 349) is missing some scripting.

* The gorillas that spawn during the event (Enraged Silverback Gorilla, Konda, and Mokk the Savage) are each supposed to spawn outside the cave, run inside, and attack Witch Doctor Unbagwa (ID 1449).
* The gorillas are not supposed to give XP when killed.
* Witch Doctor Unbagwa does not engage in combat with the gorillas to help you, he just kinda twitches like he very rapidly starts and stops combat but never attacks.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 8e865a60c815 2017-03-07 20:20:19 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
355.62

**Operating system:**
Windows 10 Server and Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
[Can be sniffed and today](https://www.youtube.com/watch?v=1ynPlqsjlLo&feature=youtu.be&t=145).

And as you can see there is no LogDescription and QuestDescription. So:
```sql
UPDATE `quest_template` SET `LogDescription`='', `QuestDescription`='' WHERE 'ID`=349;
```

**Comment by jerbookins** [comment]
Edited this issue for clarity.

**Comment by tkrokli** [comment]
DB/SAI solution posted in **[3.3.5] DB/Quest: Stranglethorn Fever #20365**

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0da19d6a0455f05f2700478218fac704b8a0ce6a
