### ISSUE TITLE
[3.3.5] Incorrect gold on tbc bosses.

### ISSUE THREAD

**Issue by Elarose** [TrinityCore/TrinityCore#19262]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The gold from burning crusades bosses is cataclysm nerf values.

**Current behaviour:**
More gold should drop.

**Expected behaviour:**
A nice stealth nerf by blizzard back in the day. 
http://www.mmo-champion.com/threads/861388-Gold-Nerf-on-PTR-Patch-4-1
http://www.wowhead.com/magtheridons-lair#comments

Wotlk Movie of three running it, times the gold by 3 seen for party members.
https://youtu.be/KbI2-Hw24Gg?t=40
Early Cata and still the gold.
https://youtu.be/EIZ_QxbJj_I?t=149

Late cata, the nerfed gold.
https://youtu.be/7bJEEl5XtWY?t=479

**Branch(es):**

3.3.5 Only.

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/340ce38e01fed2e523784ee7a80f9fa25782d447

**TDB version:** 
2017_03_07_00_world.sql
**Operating system:** 
Win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by JJandot** [comment]
Have you tried to change mingold and maxgold value in creature_template?

**Comment by Killyana** [comment]
Wotlk raid boss here https://github.com/TrinityCore/TrinityCore/issues/23013

**Comment by illfated** [comment]
I don't know for sure, but there is the possibility that some sniff data got imported from build 18019 (patch 5.4.7).
