### ISSUE TITLE
[3.3.5] Anthion Harmon

### ISSUE THREAD

**Issue by Elarose** [TrinityCore/TrinityCore#19263]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
He's currently not located quite right, and is missing gossip along with having his weapon sheathed. (Incorrect)

**Expected behaviour:**
http://www.banthar.com/world-of-warcraft/lord-valthalak-y-la-espada-enmascarada.html
http://www.wowhead.com/npc=16016/anthion-harmon#comments

Off retail, still the same position. WARNING:The gossip in sniff is the gossip -once- his quest has been completed.
https://youtu.be/L8y7EE-JX_Q

**Branch(es):**

3.3.5 Onwards.

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/340ce38e01fed2e523784ee7a80f9fa25782d447

**TDB version:**  
2017_03_07_00_world.sql
**Operating system:** 
Win10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Rushor** [comment]
fixed with https://github.com/TrinityCore/TrinityCore/issues/22168 ?
