### ISSUE TITLE
[master] Crash on .mod faction

### ISSUE THREAD

**Issue by Traesh** [TrinityCore/TrinityCore#19260]
**Description:**

Crash when you use ".mod faction" command due to wrong parameter being awaited (first parameter is a guid formated as string, SQL await %i => int)

**Current behaviour:**

Current trinity_string's content_default 130 : "You changed GUID=%i's Faction to %i, flags to %i, npcflag to %i, dynflag to %i."

**Expected behaviour:**

Should not crash. Fixed content_default 130 : "You changed GUID=%s's Faction to %i, flags to %i, npcflag to %i, dynflag to %i."

**Steps to reproduce the problem:**

1. select a npc
2. press enter
3. type ".mod faction 14"
4. press enter

**Branch(es):**

master, don't know if apply on 3.3.5

**TC rev. hash/commit:** 

f585c831248f24c93697b0c314dd015897febe39

**TDB version:**  703.00

**Operating system:** Windows 10 64bits

**Fix SQL**

`UPDATE `trinity_string` SET `content_default` = 'You changed GUID=%s\'s Faction to %i, flags to %i, npcflag to %i, dynflag to %i.' WHERE `entry` = '130'; `

**Comment by Aokromes** [comment]
#19127

**Comment by Traesh** [comment]
I feel dirty now, shoud have searched, sorry x)
