### ISSUE TITLE
Core: Duplicated entry on friend list

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19266]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** On the friend list some contacts appears many times.

**Current behaviour:** http://i.imgur.com/1TJ2zQ8.jpg
http://i.imgur.com/oV7igXl.jpg

**Expected behaviour:** The friend must appear only once

**Steps to reproduce the problem:**

Unknown
Nothing weird or unusual on the DB

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 8089f1816c9b

**Comment by Tauriella** [comment]
Strange
I have no dublicate on frind list 
![contact](https://cloud.githubusercontent.com/assets/10637389/23766247/4c79145c-0504-11e7-9610-52307759ae53.jpg)

**Comment by Killyana** [comment]
This happen for some players with a huge friend list 30+
