### ISSUE TITLE
[Master] Specialization for hunter pet

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#19279]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

I can't choose a specialization for pet with my hunter. I have an error sent by client "You need to choose a character specialization". I think the problem is with spell effect, the core sent a specialization change for character and not pet so client return this error.

**Steps to reproduce the problem:**

1. Level up 10 (for unlock pet talent)
2. Choose a specialization for your pet
3. Error "You need to choose a character specialization"

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/a36f34af3dfa2d6e790b514247766b6cc99de596

**Operating system:** Debian Jessie 8.4

**Comment by HannibalRoG** [comment]
I found this PR but I think it was never added to the master branch.

https://github.com/TrinityCore/TrinityCore/pull/17058

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/bc1a81747ae032bc2ae3681d99f5f6058d20caff it was merged.

**Comment by DoctorKraft** [comment]
This PR is implemented in master branch, but he need a little update for legion ^^
I think the problem is `Spell::EffectActivateSpec`

**Comment by AndralJu** [comment]
@DoctorKraft Hi, i just test it and that not compile : error on : Spell.h for SpecTree;

**Comment by DoctorKraft** [comment]
@AndralJu Hmm you have more information (cmake error)? Because it's work for me

**Comment by AndralJu** [comment]
@DoctorKraft I didn't seen that i write 2 times the : SpecTree; Sorry ! i will test the code now and tell you if it's good or not ;)

**Comment by DoctorKraft** [comment]
@AndralJu No problem ^^ I hurried for this commit, it's not a good method. I rewrite and open a PR soon with good method 👍

**Comment by AndralJu** [comment]
@DoctorKraft Yes that's working now still waiting for the rewrite for the good method ;)

**Comment by AndralJu** [comment]
@DoctorKraft How i can contact you to talk about somes spells ?

**Comment by DoctorKraft** [comment]
@AndralJu https://discord.gg/7qhhSFP

**Comment by DoctorKraft** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/76dd3ae36849bc44cb77cad497575be446172d53 can be closed

**Comment by tkrokli** [comment]
Closed by commit https://github.com/TrinityCore/TrinityCore/commit/76dd3ae36849bc44cb77cad497575be446172d53 (as stated in PR #19325).
