### ISSUE TITLE
Core/crash Worldserver crash at object accesor.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19270]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Worldserver crash at object accesor

**Current behaviour:**
The hash commits from logs is diferent becouse it has the PR that we have in revision by Trinity team, the rest is pure Trinity code.
The console show this error:
"\6.x\src\server\game\Entities\Object\Object.cpp:313 in Object::GetFloatValue ASSERTION FAILED:
  index < m_valuesCount || PrintIndexError(index, false)"

Log https://gist.github.com/HannibalRoG/a6b5d871ad90c4a7e6892425b0cd0a04
**Steps to reproduce the problem:**

**Branch(es):**

master

**TC rev. hash/commit:** 

f585c831

**TDB version:**  7.0.3+updates

**Operating system:** Windows Server 2012 R2 Datacenter (worldserver.exe)
Windows 10 (client side)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Traesh** [comment]
```
        if (playerVictim->CanBlock())
        {
            Item* tmpitem = playerVictim->GetUseableItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_OFFHAND);
            if (tmpitem && !tmpitem->IsBroken() && tmpitem->GetTemplate()->GetInventoryType() == INVTYPE_SHIELD)
                chance = GetFloatValue(PLAYER_BLOCK_PERCENTAGE);
        }
```

Isn't "playerVictim->" missing in front of GetFloatValue ?
