### ISSUE TITLE
Cannot learn Enchanting Formulas

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19283]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Cannot learn certain enchanting formulas:
- Formula: Imbue Cloak - Protection (ID 6345)
- Formula: Enchant Boots - Minor Stamina (ID 6376)
- Formula: Imbue Chest - Spirit (ID 6343)

I'm not sure these items are supposed to exist.

Items purchased from the AuctionHouse Bot.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 340ce38e01fe 2017-03-08 18:26:41 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Elarose** [comment]
Sometimes the Auction Bots pulls things from the db that are not ingame. Good news is you can open your worldserver.conf and find the line AuctionHouseBot.forceExcludeItems. The comments above it are self explanatory, exclude the things you don't want appearing.  Note:Minor stam on boots is learnt from trainers.
