### ISSUE TITLE
Db/Quest No quest for human monk.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19280]
**Description:**  
When create a Human player / Monk, you cannot accept any mission.  

**Current behaviour:**  
When create a Human player / Monk. The NPC "Marshal McBridge" (DB GUID: 279961 Entry: 197). Doesn't give any mission. And the exlamación sign doesn't appear in yellow, but silver.  

**Expected behaviour:**  
Create a Human player / Monk. And the NPC "Marshal McBridge" give us the mission "Beating then Back!" (ID: 28766). 

**Steps to reproduce the problem:**  
1- Create a Human player / Monk  
2- Interact with NPC "Marshal McBridge"  

**Branch(es):** Master  

**TC rev. hash/commit:**  
a36f34af3dfa2d6e790b514247766b6cc99de596  

**TDB version:**  
7.0.3+updates

**Comment by zamalaev** [comment]
```
DELETE FROM `creature_queststarter` where `id` = 197 and `quest` = 31139;
INSERT INTO `creature_queststarter` (`id`, `quest`) values ('197', '31139'); -- Add quest  Monk"Beating Them Back!"
```
fixed

**Comment by HannibalRoG** [comment]
I test it.

**Comment by Aokromes** [comment]
No, PRs arent used for sql only fixes.

**Comment by LKArthas** [comment]
@HannibalRoG Also there's not the only quest for human monks that you need to fix, the entire questline for monks won't work for the cases of the quests Beating then Back! and the following quests are 1 for each class and Monk isn't added yet
Best regards :+1:
