### ISSUE TITLE
DB/Instance Willing caverns is empty.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19298]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

After the commit for Willing Cavern from Aokromes the instance is empty.

**Current behaviour:**

The instance willing caverns is empty.

**Expected behaviour:**

The instance must have all creatures inside.

**Steps to reproduce the problem:**

1. Create a player
2. Levelup 20
3. Go to instance

**Branch(es):**

Master

**TC rev. hash/commit:** 

fd0dc537

**TDB version:**  7.0.3+updates

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
check if you see spawmask error, maybe they changed it on legion.

**Comment by Aokromes** [comment]
```sql
UPDATE `spawnMask` = 2 WHERE `map` =43;
```

**Comment by HannibalRoG** [comment]
Yes, that works, but SAIs are not, can not complete instance because of this.

**Comment by LKArthas** [comment]
Hannibal SAIs are working Perfectly i tested and even adapt the whole commit for another 4.3.4 Source and the instance works full. :)

**Comment by HannibalRoG** [comment]
What can be happening to me for not to run the SAIs on my server?

**Comment by LKArthas** [comment]
@HannibalRoG Check if they have set the SmartAI on the creature_template or if the creatures are using a script_name

**Comment by HannibalRoG** [comment]
I edit my comment.
