### ISSUE TITLE
[linux] compilation with debug mode issue

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#19296]
**Description:**

Impossible to compile with debug mode on debian 8

**Current behaviour:**

[ 72%] Generating gamePCH.h.gch
Linking CXX static library libscripts.a
/usr/bin/ar: libscripts.a: Truncated File.
src/server/scripts/CMakeFiles/scripts.dir/build.make:15035: recipe for target 'src/server/scripts/libscripts.a' failed
make[2]: *** [src/server/scripts/libscripts.a] Error 1
CMakeFiles/Makefile2:1662: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make[1]: *** Attente des tâches non terminées...
[ 72%] Built target generate_gamePCH.cpp
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Branch(es):**

master

**TC rev. hash/commit:** 

fd0dc53

**Operating system:** Debian 8

**Comment by Aokromes** [comment]
useless log, real error must be over that.

**Comment by Pixel-Pirate** [comment]
This is the only error I get. Thanks for your answer

**Comment by Aokromes** [comment]
Scanning dependencies of target worldserver
[ 99%] [ 99%] [100%] [100%] [100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/PrecompiledHeaders/worldPCH.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RASession.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/TCSoap/TCSoap.cpp.o
Linking CXX executable worldserver
[100%] Built target worldserver

real    26m43.453s

**Comment by jackpoz** [comment]
this sounds more like an issue happening to a specific user than a generic TC issue and might fit better on the forum

**Comment by Pixel-Pirate** [comment]
Hi Jackpoz, I had try to make compilation with root user and same problem.
