### ISSUE TITLE
[Master] SPELL_AURA_PROC_ON_POWER_AMOUNT_2

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#19291]
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

SPELL_AURA_PROC_ON_POWER_AMOUNT_2 proc all times. It's not totally script

> miscB (0) = when your power up
> miscB (1) = when your power down

You can check an example with this spell [Rampage!](http://www.wowhead.com/spell=209694/rampage)
Effect 0, add aura when you have 85 rage
Effect 1, remove aura when you have 84 rage

On retail for example if you reach 85 rage and you gain again rage, you don't have proc. You need to go down rage 84 for proc again.
 
**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/c9fbab6f048fdd277f840e660c483ed426201f02

**Operating system:** Debian Jessie 8.4

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by wonder2011** [comment]
I'm working on this spell
`ID - 215571 Frothing Berserker` and i have problems with this proc. So is broken @DoctorKraft ??

**Comment by DoctorKraft** [comment]
yeah exactly, need rewrite proc for script correctly this spell

**Comment by aquadeus** [comment]
this is fixed

**Comment by Aokromes** [comment]
go check https://github.com/TrinityCore/TrinityCore/issues?q=is%3Aopen+label%3ASub-Spells+label%3ABranch-master XD
