### ISSUE TITLE
[Master] Core/Spells 219521 Shadow Covenant force logouts caster

### ISSUE THREAD

**Issue by Keital** [TrinityCore/TrinityCore#19292]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Aura 219521 Shadow Covenant when applied on a target forces client to logout the caster while active on target. 

**Current behaviour:**

Aura 219521 Shadow Covenant when applied on a target forces client to logout the caster while active on target, if you relogin and aura is still active on target clients logouts again. only when aura expires on target caster can login again. doesn't crash worldserver daemon.

Problem is not located on handler i think, cause i've commented all code in:
void Unit::CalcHealAbsorb(Unit* victim, SpellInfo const* healSpell, uint32 &healAmount, uint32 &absorb)
and the problem persist

**Expected behaviour:**

Doesn't forces caster to logout

**Steps to reproduce the problem:**

1. enter command ".aura 219521" on target
2. caster logsout

**Branch(es):**

master

**TC rev. hash/commit:** 
c9fbab6f048fdd277f840e660c483ed426201f02

Operating system: Windows

**Comment by aquadeus** [comment]
this spell is deprecated
