### ISSUE TITLE
NPC/Script: Wyrmrest Defender

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19299]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** Wyrmrest Defender must despawn if it goes outside the restricted area
https://woehead.way-of-elendil.fr/?npc=27629
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_dragonblight.cpp#L492
``` sql
SELECT * FROM `conditions` WHERE `SourceEntry` IN (27629);
```
**Current behaviour:** The player can use the vehicle to go anywhere.

**Expected behaviour:**  If the vehicle goes outside the areas defined in the conditions table it must despawn.

**Steps to reproduce the problem:**

1. .cast 49207 and ride the vehicle
2. You can go anywhere

CHANGEME 3.3.5 and master

**TC rev. hash/commit:**  rev. 8c6fa411e811

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Overriden UpdateAI doesn't do conditions check every second. Simple fix
