### ISSUE TITLE
Core/Spell: Pvp trinket  remove only one effect

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19308]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** After https://github.com/TrinityCore/TrinityCore/commit/9f2f7ebf51a587199ee7328761c5842c3f491e3b  or maybe a previous one, pvp trinket and other spells like humain racial removes only one effect instead of all ( Removes all movement impairing effects and all effects which cause loss of control of your character.)

**Current behaviour:** Pvp trinket remove only one effet

**Expected behaviour:** Pvp trinket must remove all effects

**Steps to reproduce the problem:**

1. Use 2 kind of controle or movement impairing effect on player 1
2. Use the pvp trinket on player1
3. Notice only one effect was dispelled the second one remain

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 3b27a06265e4

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Can't reproduce with Slow (Id 6146) and Ensnare (Id 48053).

Do you have any particular pair of spells that don't work?

**Comment by Killyana** [comment]
Sorry I tested with Disarm, it's not supposed to be removed with the trinket.
