### ISSUE TITLE
[Texture problems] Can cast through mountains and other.

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#19303]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
I just update and now i have this report, aparently now you can cast through mountains, doors, rocks or tiny walls.

I already check and have the latest vmap and mmaps version.

**Expected behaviour**: Tell us what should happen instead
Before you see the "You cant see the target"

**Steps to reproduce the problem**:
Go to some arena or bg (Eye of the storm), and cast some spell, heal or shot an arrow to somebody who be cover by a mountain or in a room for example.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
f7758954f7b9808a56420ac2ca75a83af4e40f4e

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by DDuarte** [comment]
> "I just update to master"

Do you mean the master branch? That one is not 3.3.5.

Anyway, do you have vmaps and mmaps enabled?

**Comment by Shauren** [comment]
Terrain (mountains, ground) does not block LoS (and never did)

**Comment by n4ndo** [comment]
Sorry about master**

Yes i have vmaps and mmaps enabled.

**Comment by n4ndo** [comment]
https://www.youtube.com/watch?v=3baDlQZj6Rs&feature=youtu.be

**Comment by Shauren** [comment]
Blizzlike, working as intended.

**Comment by n4ndo** [comment]
wow so i was wrong.. I did not think that can cast misile arcane through walls.

thanks.

**Comment by tkrokli** [comment]
Easy. You either use `<Tab>` or the chat command `/target` to place your focus on a target in range.
