### ISSUE TITLE
Aura: Misscalculation on stack change

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#19301]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

If an aura has stacks, and the stack changes, the aura effect gets misscalculated. Has been observed with SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT but most likely affects other spells.

**Current behaviour:**

Take Tenacity for example, spell 58549. Cast it once, you get your base health * 1.18. Now cast it again. It should become your base health * 1.36. However, it becomes base health * 1.18 * 1.36 instead

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Cast 58549 and observe
2. Cast 58549 and observe again
3. Profit

**Branch(es):**

3.3.5 (probably master too)

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/6f84bde8b41abc3b54356dc48a71d9269b43fc67

**Comment by Ovahlord** [comment]
Looks like there is a simple percentual addition of the already changed base value. Probably there is a missing divider like newAmount =+  baseAmount * bonus / stackCount

**Comment by joshwhedon** [comment]
Yes we treat change amount the same way we treat a totally new aura, which cause this problem of course.
