### ISSUE TITLE
Core/Quest: ExclusiveGroup Wrong restriction

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19300]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** This issue is little bit complicated to understand.
ExclusiveGroup is used in quest_templates in 2 ways, the issue is related to ExclusiveGroup <0
if ExclusiveGroup < 0 :

Allows to define a group of quests of which all must be completed and rewarded to start next quest. E.g. if quest 1000 dependent from one of quests 1200, 1201 and 1202 and all this quests have same negative exclusive group then all this quest must be completed and rewarded before quest 1000 can be started.

This works correctly, but in some cases the same value of the ExclusiveGroup is used in PrevQuestID (negative or positive doesn't matter) in this case the quest that use this PrevQuestID will be considered as a member of this negative ExclusiveGroup and will not be proposed to the player if he already rewarded one of the quests using this negative ExclusiveGroup.
Example:
SELECT PrevQuestID FROM quest_template_addon WHERE id=10919; =-10916

.quest add 10916
the dog will propose the quest Fei Fei's Treat
Don't take the quest from the dog and .quest add 10909
Notice the dog doesn't prose the quest anymore
because 10909 is using the same ExclusiveGroup  as 10916 and Fei Fei's Treat quest is using PrevQuestID =-10916

Second example:
SELECT PrevQuestID FROM quest_template_addon WHERE id IN (12034, 12039, 12056, 12100); = 12008
SELECT * FROM quest_template_addon WHERE ExclusiveGroup=-12008;= 12008, 12072, 12140, 12221
For this quest using PrevQuestID = 12008 the restriction ExclusiveGroup=-12008 is applied 

This is the reason why many players are not able to continue some chain quests after rewarding quests affected but this issue.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 8c6fa411e811

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
The problem is core inserting NextQuestId into the PrevQuest vector of that next quest, in doing that we lose the information of which quest we're supposed to allow, there should be only one prevquest. (and ExclusiveGroup should only apply restrictions on NextQuest, not prev)

**Comment by Nocty1501** [comment]
This issue still appears to be affecting quest 12008 (https://wotlkdb.com/?quest=12008) which does NOT unlock 12034 (https://wotlkdb.com/?quest=12034) or 12039 (https://wotlkdb.com/?quest=12039) as it should.

TrinityCore rev. 3ecdf2c2255b 2022-01-04 06:08:23 -0600 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
