### ISSUE TITLE
[Legion]Nerub'ar Broodkeeper 

### ISSUE THREAD

**Issue by conan513** [TrinityCore/TrinityCore#19305]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Nerub'ar Broodkeeper fall down in ICC and start attacking but can not be attacked 

1.  get level 110
2. enter icc dungeon and walk foward
3. Nerub'ar Broodkeeper falling down

**Branch(es):**

Master

https://github.com/TrinityCore/TrinityCore/commit/fd5471a913c4bc36b3831300ab2dd8de410bc984

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#15247
