### ISSUE TITLE
Problems in SAIs inside instances.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19313]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

No SAIs execute on server in instances.

**Current behaviour:**

The console show "SmartScript: Entry xxxx has events but no events added to list because of instance flags."

**Expected behaviour:**

Exceute all SAIs without errors.

**Steps to reproduce the problem:**

1- Update core and BD to last.
2- Go to Willing Caverns or any other instance that have SAIs.
3- Figth with any Boss.
4- Read the console.

**Branch(es):**

Master

**TC rev. hash/commit:** 

6239339069e2390ee3a08cbdc5c5c1d18148407b

**TDB version:**  7.0.3+updates

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
#16997

**Comment by HannibalRoG** [comment]
Lo siento por el duplicado, por cierto en tu último commit hay un error en el sql, el campo "data" no existe, debiera ser "Importance".
