### ISSUE TITLE
[CRASH] SpellInfo::GetFirstRankSpell

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#19319]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
SpellInfo::GetFirstRankSpell (this=this@entry=0x0) 

**Current behaviour**: Tell us what happens
Not sure why is this happening.

- http://pastebin.com/Yrk6YT0q
- http://pastebin.com/7Dtrv6CD
- http://pastebin.com/2LnQbnjW

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
e33263c677a3d1af61b7c2e53d72b5360ba7de4d

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
```gdb
#2  0x0000000001f68bcd in Unit::IsHighestExclusiveAura (this=this@entry=0x7ffef88e0000, aura=aura@entry=0x7ffecd9fa8e0, removeOtherAuraApplications=removeOtherAuraApplications@entry=false)
at /Compiler/Sources/src/server/game/Entities/Unit/Unit.cpp:14581
```

Line 14581 of Unit.cpp at e33263c677a3d1af61b7c2e53d72b5360ba7de4d is
```c++
/*14580*/void Unit::TextEmote(std::string const& text, WorldObject const* target /*= nullptr*/, bool isBossEmote /*= false*/)
/*14581*/{
```

**Comment by jackpoz** [comment]
>spellid_1 = 2584 http://wotlk.openwow.com/spell=2584
spellInfo2=spellInfo2@entry=0x0
WorldSession::HandleAreaSpiritHealerQueueOpcode()
Battleground::AddPlayerToResurrectQueue()

All 3 crashes happened with same spell in a battleground. A couple of asserts in SpellMgr::CheckSpellGroupStackRules() would be nice.

**Comment by n4ndo** [comment]
Today.. another 5 crashes...

**Comment by n4ndo** [comment]
https://youtu.be/Cj8zykHhhPQ

**Comment by shenhuyong** [comment]
Confirm this crash bug.
Readd HasEffect check which be removed from rev. 5eac21098efa35f3c6807a57bc44cc887c0cbc6a can fix this crash bug.
Modify SpellAuraEffects.cpp
Find
`            aurApp->GetTarget()->_RegisterAuraEffect(this, false);`
`            HandleEffect(aurApp, handleMask, false);`
Change to 
`        if (aurApp->HasEffect(GetEffIndex()))`
`        {`
`            aurApp->GetTarget()->_RegisterAuraEffect(this, false);`
`            HandleEffect(aurApp, handleMask, false);`
`        }`

Find
`            aurApp->GetTarget()->_RegisterAuraEffect(this, false);`
`            HandleEffect(aurApp, handleMask, false);`
Change to 
`        if (aurApp->HasEffect(GetEffIndex()))`
`        {`
`            aurApp->GetTarget()->_RegisterAuraEffect(this, true);`
`            HandleEffect(aurApp, handleMask, false);`
`        }`

Find
`                PeriodicTick(aurApp, caster);`
Change to 
`                if (aurApp->HasEffect(GetEffIndex()))`
`                    PeriodicTick(aurApp, caster);`

**Comment by ariel-** [comment]
Makes no sense. HasEffect is checked here: https://github.com/TrinityCore/TrinityCore/blob/5eac21098efa35f3c6807a57bc44cc887c0cbc6a/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L416

So the vector already has only applications with `this` AuraEffect applied

**Comment by shenhuyong** [comment]
I don‘t know why, but after I readded HasEffect check, the crash disappeared.

**Comment by ariel-** [comment]
Do you have any repro steps? I was hanging around in BG dead near the resurrection ghost, but didn't crash.

**Comment by shenhuyong** [comment]
Sorry, I have not. My server have 500+ players, and it crashs per 5 minutes after I removed HasEffect, the spellid from crashlog also is 2584, and crash in SpellInfo::GetFirstRankSpell.

**Comment by n4ndo** [comment]
Just note that i revert that 3 commits, and have no crash.

**Comment by shenhuyong** [comment]
I found a way to reproduce the problem.
1. Go into a Arathi Basin and .die to yourself after bg start.
2. At the graveyard and don't move, confirm you have the aura 2584.
3. If the graveyard of the position be captured by the enemy and you are still not be resurrect, you will teleport to a closest graveyard, and you will get aura 2584 again, then server will crash.

**Comment by ariel-** [comment]
I couldn't reproduce it either:

1. Alliance player assaults stables, wait for 1 minute so it's taken
2. Horde player goes to stables, .die the alliance player
3. Alliance player hits Release Spirit and repops in Stables Graveyard. (I ensured the res timer was as close as 30 secs as possible)
4. Meanwhile, the horde player assaults the stables.
5. On the alliance player, before resurrection the stables are now in conflict state with the horde, and ghost gets teleported to alliance base normally, no crash.

**Comment by shenhuyong** [comment]
I found a way to crash the server by 100%, but let me test it a few more times.

**Comment by shenhuyong** [comment]
This is the fastest way to crash the server:
1. Edit this macro and put it in your action bar (`/g .cast 2584` 18lines), and make sure you can use '.cast' command.
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
`/g .cast 2584`
2. Go into a BG, and kill your self after BG start.
3. Move your character, go into the resurrection area and out the resurrection area constantly, make sure your aura 2584 appear and disappear constantly, and at the same time, click the macro icon which in your action bar constantly, no crash no stop.
