### ISSUE TITLE
Spell/Script: Aura of Desire

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19322]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** On  Reliquary of the Lost encounter Players looses their mana bar in  5 secs when the boss use http://www.wowhead.com/spell=41350/aura-of-desire
I wasn't able to reproduce the issue in Solo, but I see it in party.

**Current behavior:** Players loses their mana too fast under http://www.wowhead.com/spell=41350/aura-of-desire

**Expected behavior:** Players must lose their mana progressively 

**Branch(es):**3.3.5

**TC rev. hash/commit:**  rev. e33263c677a3

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
I dont tested this issue, but mana drop is handled here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp#L746
if i remember right i did with Joschiwald...
Spell should drop the maximum mana of players each 8 secs

**Comment by Keader** [comment]
Hmm i can confirm this issue.
Look it:

Name: Keader ManaMax: 6201 CurrentMana: 5890 Amount: -5
Name: Bradley ManaMax: 5025 CurrentMana: 4522 Amount: -10
Name: Akama ManaMax: 28789 CurrentMana: 23115 Amount: -15

AuraScript is 1 for all creatures? :(

**Comment by Keader** [comment]
@ariel-  Any ideas here?
All targets "share" the same aura, ```effect->ChangeAmount(effect->GetAmount() - 5 );``` will update amount for each target of aura per tick
So if has 5 people/creature in SpellRange, they will lost 100% of MaxMana in 16 sec (2 update ticks)
I need a way to use same amount in all targets, before change value

**Comment by ariel-** [comment]
I don't know. Perhaps it should be handled just like health (ie, you keep the same relative amount of mana)

**Comment by Treeston** [comment]
If anyone is interested: this bug was caused by "amount change" being handled as "effect removal -> effect application". Effect application was dropping current mana, while effect removal was doing nothing.

Thus:
100/100 -> 80/80 (application) -> 80/100 (removal) -> 60/80 (application) -> 60/100 (removal) -> 20/60 (application) etc
