### ISSUE TITLE
Crash: Ice Lock used by Guard Slip'kik

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19324]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** When https://woehead.way-of-elendil.fr/?spell=22856  is cast, the server crashes.

Crash log: https://gist.github.com/Killyana/6388036e94d17ee66f1967be48c5b08d

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** rev. e33263c677a3

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
```
 basePoints = {-1648411728, 32767, 2}
```

Suspicious, the spell only has one aura effect

**Comment by ariel-** [comment]
Can't reproduce in 5d562556c35a9c506bdfaee13b51268ab8e5df67

![](http://i.imgur.com/aZuiMis.png)

**Comment by ariel-** [comment]
After a few minutes with the server running I got the crash. Seems like the smart scripts are executing again, but unit is going to be deleted already (assert on !m_cleanupDone).

Sounds like some grid problem

**Comment by ariel-** [comment]
To clarify: this is the sequence when it goes wrong:

```
#25 0x00000000016f9f0b in PointMovementGenerator<Creature>::MovementInform (this=0x7fff6e5da740, unit=0x7fff3de9c000) at /dummy/src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp:111
No locals.
#26 0x00000000016fa3d8 in PointMovementGenerator<Creature>::DoFinalize (this=<optimized out>, unit=<optimized out>) at /dummy/src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp:93
No locals.
#27 0x00000000016e3b25 in MovementGeneratorMedium<Creature, PointMovementGenerator<Creature> >::Finalize (this=<optimized out>, u=<optimized out>) at /dummy/src/server/game/Movement/MovementGenerator.h:63
No locals.
#28 0x00000000016db330 in MotionMaster::DirectDelete (this=0x7fff9dbf1100, this@entry=0x7fff16c50c40, curr=0x0, curr@entry=0x7fff6e5da740) at /dummy/src/server/game/Movement/MotionMaster.cpp:810
No locals.
#29 0x00000000016db38a in MotionMaster::DirectClean (this=0x7fff16c50c40, reset=reset@entry=false) at /dummy/src/server/game/Movement/MotionMaster.cpp:750
        curr = 0x7fff6e5da740
#30 0x00000000016e26f5 in MotionMaster::Clear (this=<optimized out>, reset=reset@entry=false) at /dummy/src/server/game/Movement/MotionMaster.cpp:112
No locals.
#31 0x0000000001a3ed4e in Unit::CleanupBeforeRemoveFromMap (this=this@entry=0x7fff3de9c000, finalCleanup=finalCleanup@entry=true) at /dummy/src/server/game/Entities/Unit/Unit.cpp:11070
        __FUNCTION__ = "CleanupBeforeRemoveFromMap"
#32 0x0000000001a55d94 in Unit::CleanupsBeforeDelete (this=0x7fff3de9c000, finalCleanup=true) at /dummy/src/server/game/Entities/Unit/Unit.cpp:11075
No locals.
```

I think that a movegen shouldn't call movementinform if it's being deleted (caused by calling Finalize on DirectDelete)
