### ISSUE TITLE
[3.3.5a] Utgarde Keep: Ingvar the Plunderer - no second phase

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19328]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Ingvar the Plunderer doesn't enter second phase.

**Current behaviour:**

When you kill the boss, he gets resurrected, but usually doesn't go into the undead phase. You have to kill him repeatedly until you may be lucky and the second phase kicks into action.

It seems that in the script ``boss_ingvar_the_plunderer.cpp`` ``EVENT_RESURRECT_2`` in this part is hardly ever reached or it is broken off at the following ``if``:
```c++
                while (uint32 eventId = _events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_RESURRECT_1:
                            if (Creature* ingvar = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_INGVAR)))
                            {
                                ingvar->RemoveAura(SPELL_INGVAR_FEIGN_DEATH);
                                ingvar->CastSpell(ingvar, SPELL_SCOURG_RESURRECTION_HEAL, false);
                            }
                            _events.ScheduleEvent(EVENT_RESURRECT_2, 3000);
                            break;
                        case EVENT_RESURRECT_2:
                            if (Creature* ingvar = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_INGVAR)))
                            {
                                ingvar->RemoveAurasDueToSpell(SPELL_SCOURG_RESURRECTION_DUMMY);
                                ingvar->AI()->DoAction(ACTION_START_PHASE_2);
                            }

                            me->GetMotionMaster()->MovePoint(2, x, y, z + 15.0f);
                            break;
                        default:
                            break;
                    }
```
I didn't find a pattern though. It seems totally arbitrary. This problem has existed already for quite a time, at least since the middle of 2016. I wonder why no one else seems to have noticed it.

**Expected behaviour:**

Easy: It should work the fist time you try it.

**Steps to reproduce the problem:**

1. Work your way through Utgarde Keep to the last boss (e.g. non-hero).
2. Engage him and kill him.
3. Watch the animation and you see the outcome.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

e9d527b70f84

**TDB version:**  according to revision

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Try after https://github.com/TrinityCore/TrinityCore/commit/bf5661e2fd05625411b184385412921b3f0fb8c5

**Comment by tkrokli** [comment]
Good point, 26 days since commit https://github.com/TrinityCore/TrinityCore/commit/e9d527b70f84d28c7ed0a2d6d0270aa89230c472 (2017-02-20).

**Comment by TecDian** [comment]
And there it goes down the gutter. Thanks for the advice. It seems to work now. What do we learn from this? Always use a fresh core to test stuff! Please accept my apologies.

Can be closed.
