### ISSUE TITLE
[335] Verifonix - Incorrect or Missing Faction and Level

### ISSUE THREAD

**Issue by MrSmite** [TrinityCore/TrinityCore#19323]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

[Verifonix](http://www.wowhead.com/npc=14492/verifonix) is incorrectly flagged neutral and is level 42. He also does not give Booty Bay rep. when killed.

**Current behaviour:**

See description

**Expected behaviour:**

Prior to Cataclysm, he should be level 34 and hostile to Alliance and Horde

> http://www.wowhead.com/npc=14492/verifonix#comments
> He used to be hostile before Cataclysm. I guess he retired, but Booty Bay decided the bounty on his head was still valid from his Venture Co. days.

**Steps to reproduce the problem:**

1. Check the database
2. 
3. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8c6fa411e8118752ddbefe8dc022514602859fb9

**TDB version:**

TDB_full_world_335.61_2016_04_11 + updates

**Operating system:**

WinXP / Win7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
> Prior to Cataclysm, he should be level 34 and hostile to Alliance and Horde

No.

> Patch 4.0.3a (2010-11-23): Level reduced from 42 to 34.

```sql
UPDATE `creature_template` SET `faction`=47 WHERE `entry`=14492;
DELETE FROM `creature_onkill_reputation` WHERE `creature_id`=14492;
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `RewOnKillRepFaction2`, `MaxStanding1`, `IsTeamAward1`, `RewOnKillRepValue1`, `MaxStanding2`, `IsTeamAward2`, `RewOnKillRepValue2`, `TeamDependent`) VALUES
(14492,21,0,5,0,5,0,0,0,0);
```

**Comment by MrSmite** [comment]
What about the comment indicating he should be hostile?
