### ISSUE TITLE
[NPC][Naxx] Trash NPC Eye Stalk are "blinking" on players instead of staying in their "place"

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19335]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Eye Stalk NPCs are blinking on current target,instead of staying in their "place"

**Current behaviour:**

Eye Stalk NPCs (Eyed Tentacles) blinking on players. I didn't changed a MovementType and InhabitType in DB. They are setted on 0 and 3.

**Expected behaviour:**

Eye Stalk NPCs must stay in their "vases? :D" idk.

**Steps to reproduce the problem:**

1. Kill two first bosses in Plague Quarter
2. Pull the Eye Stalks in corridor after Heigan

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 5d562556c35a+ 2017-03-18 11:07:41 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64 with all system updates.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
> I didn't changed a MovementType and InhabitType in DB. They are setted on 0 and 3.

After f78ab9aba45e3b4189a71bb68de6d5b13f45bbca InhabitType should be 11. Maybe f78ab9aba45e3b4189a71bb68de6d5b13f45bbca was reverted due to #17827, I dunno.

**Comment by markvetwow** [comment]
There is a little video with issue. [Link on YouTube](https://www.youtube.com/watch?v=ePTWbwjwXNE)

**Comment by Langerz82** [comment]
Shouldn't inhabit type be 8 = INHABIT_ROOT ?

Anyway im having trouble getting to the area can someone provide the coordinates?

**Comment by Killyana** [comment]
The inhabittype 8 must always be set with the inhabittype where the npc belong, example for this npc it's 11=1+2+8= ground+water+root
Anyway the issue looks to be fixed you can check with: .go c id 16236
