### ISSUE TITLE
Rogue - Stealth not fully working

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#19337]
**Description:**

The Rouge stealth ability is not working properly.

**Current behaviour:**

The Rogue stealth ability is visible on the active effects however the effect is missing - Rogue is not appearing to be transparent and the movement speed does not change after using the Stealth ability. When the Stealth ability is active, enemies still detect you.

**Expected behaviour:**

After using the Stealth ability - Rogue should become transparent and the movement speed should be decreased including the Rogue movement stance to be changed on the effect. Rogue should also not be detected by enemies.

**Steps to reproduce the problem:**

Step 1 - Create Rogue character
Step 2 - Login to the server and learn Stealth ability
Step 3 - Use Stealth ability to notice the problem

**Branch(es):**

Master

**TC rev. hash/commit:** 

**TDB version:**  703.00
TrinityCore rev. 945cfce1f63f 2017-03-20 08:54:29 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)
**Operating system:** Windows 10

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14825
