### ISSUE TITLE
[master] Invalid movement jump speed calculation

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/TrinityCore#19330]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Jump spells are currently sending wrong movement information, you start noticing it when you increase your Z position.
Using a jump spell to jump straight down does not work at all, if your X and Y position are the same but your height is different.

**Current behaviour:**

Using a jump spell in near proximity to your current X and Y position while being high up in the air will cause extremely long jump movement durations.

**Expected behaviour:**

Not extremely long jump movement durations

**Steps to reproduce the problem:**

1. .learn 162052
2. .cheat cooldown
3. Fly up into the air (fairly high, 30 yards) and try to cast the spell directly underneath you

**Branch(es):**

master, I'm guessing 3.3.5 as well if someone can confirm.

**TC rev. hash/commit:** a66a8e721f9843a05a2ab362f76ad889c24455e1

**Comment by DoctorKraft** [comment]
> EffectAmplitude = 4
(it's multiplier for speedXY)

The value are missing in spelleffect, i have trying this

```cpp
    if (effInfo->Amplitude)
        speedXY = dist * 10.0f / speedZ * float(effInfo->Amplitude);
    else
        speedXY = dist * 10.0f / speedZ;
```

in `CalculateJumpSpeeds` and works perflecty (blizzlike)

**Comment by Seyden** [comment]
Jump Speed Calculations aren't correct at all..

**Comment by ariel-** [comment]
Related #19210 ?

**Comment by DoctorKraft** [comment]
`EffectAmount` are not implemented, in WoD DBC it was a multiplier for Speed but for vertical i don't think it's the problem

**Comment by Stanwarr** [comment]
How did you even get Heroic Leap to work in the first place?

**Comment by DoctorKraft** [comment]
@Stanwarr  You need update the spellscript in spell_warrior.cpp

**Comment by Stanwarr** [comment]
Can you give me your discord user name? I might need some help.

**Comment by aquadeus** [comment]
i think this is fixed
