### ISSUE TITLE
Core/Achievements: FIRST Achievements are not loaded on startup

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19334]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** After a recent commit about achievements, every time you restart your server all "FIRST" achievements are considered as not done: first 80, first Professions, first Boss encounter ect... 

**Current behavior:** The server doesn't see (load) FIRST achievements from the DB.

**Expected behavior:** FIRST achievement must not be validated if there's already a player that did it.

**Steps to reproduce the problem:**

1. Go to Malygos 25 and kill it you will get the first achievement
2. Restart your server
3. Take another character and kill Malygos 25 you will get the first achievement again

**Branch(es):**3.3.5

**TC rev. hash/commit:** rev. e33263c677a3

**Comment by Killyana** [comment]
@ariel- caused by https://github.com/TrinityCore/TrinityCore/commit/4596c17dae1dcb199b9301b7dcfd556bb1c0d7d5 ?

**Comment by ariel-** [comment]
Most probably
