### ISSUE TITLE
[NPC][Naxx] Gothik encounter, some spectral NPCs are not visible.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19333]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

So, two NPCs on Gothik encounter are not visible on "dead" side.

**Current behaviour:**

Two NPCs are not visible:
1) Spectral Death Knight, id = 16148
2) Spectral Rider, id = 16150
They are only visible on GM state.

**Expected behaviour:**

These NPCs must be visible after "transforming" into undead on "dead" side.

**Steps to reproduce the problem:**

1. Pull Gothik on any difficulty (with at least 1 player on each side)
2. Wait for around 5-6 wave.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 5d562556c35a+ 2017-03-18 11:07:41 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8 x64 with all system updates.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Treeston** [comment]
Should be basic DB issue, @ariel-.

**Comment by offl** [comment]
After 78228b59abb54eb1036fbcbb7ed466570eec671c they now have the aura Shroud of Death (10848).

**Comment by Treeston** [comment]
That's purely a visual effect, nothing to do with visibility.

**Comment by markvetwow** [comment]
@offl, Wow! Thanks for that info! I removed that aura from creature_template_addon and it's working now. Creatures are visible on "undead" side.

**Comment by Treeston** [comment]
🤔 need to investigate. That aura is purely a dummy according to spell info.

**Comment by Killyana** [comment]
The aura is not dummy it was scripted to make nps visible only when the player is dead.

**Comment by Treeston** [comment]
Where is this script? IIRC that aura being present is sniff sourced.

**Comment by Killyana** [comment]
https://github.com/JunkyBulgaria/hachasydados-core/blob/17bf2cc99516afc445de1759d09ea98e978c3746/src/server/scripts/Spells/spell_generic.cpp#L520
https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB36_to_TDB37_updates/world/10418_world_spell_script_names.sql

**Comment by ariel-** [comment]
Oh, I see. The current script was added in e1f14215d86fc9f0cd041f0e87bf0a689c086329

**Comment by Treeston** [comment]
I just re-checked. Sniffs definitely show these mobs having 10848 on them. Investigating...

**Comment by Treeston** [comment]
Hm, the aura is used in the core by [6491](http://www.wowhead.com/npc=6491/spirit-healer), [9299](http://www.wowhead.com/npc=9299/gaeriyan) and [8888](http://www.wowhead.com/npc=8888/franclorn-forgewright), which are dead-only visible.

Tagging @xinef1, are those auras sniff sourced? Even if they are, I'd argue that the aura is still purely a visual effect, visibility should be handled by unit script.

**Comment by xinef1** [comment]
Well I was pretty convinced that dead visibility is caused by this specific aura. If sniffs show normal npcs also have this aura, we can either:
a) move dead visibility to scripts
b) add switch to aura code

I can make pr if you decide on more appropriate approach

**Comment by Treeston** [comment]
Switch in aura code sounds like a hack. Could either add a new extra flag, or move it to scripts. Either would be fine.

**Comment by ariel-** [comment]
If the spell is only used to add a visual effect and not to modify the visibility, it could be simply unbinded from the script (iif not used elsewhere)

**Comment by xinef1** [comment]
extra flag sounds good to me, @ariel-?

**Comment by ccrs** [comment]
ariel is simply asking if the spell used in naxxramas is only used in naxxramas, why not just unbind the script from it and move on?

**Comment by Treeston** [comment]
> Hm, the aura is used in the core by [6491](http://www.wowhead.com/npc=6491/spirit-healer), [9299](http://www.wowhead.com/npc=9299/gaeriyan) and [8888](http://www.wowhead.com/npc=8888/franclorn-forgewright), which are dead-only visible.

It's also used by Spirit Healer f.ex., everywhere.

Script should still be removed. Extra flag for "this NPC is only visible while a ghost" sounds reasonable.

**Comment by joschiwald** [comment]
> After 78228b5 they now have the aura Shroud of Death (10848).

is the aura on these npcs the whole fight? or do they lose them after a specific time?

**Comment by offl** [comment]
The whole fight. https://github.com/TrinityCore/TrinityCore/pull/19358 will remove invisibility changes.
