### ISSUE TITLE
[3.3.5a] Iron Gate in Scholomance does not open

### ISSUE THREAD

**Issue by shadedmagus** [TrinityCore/TrinityCore#19339]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The Iron Gate objects in the Scholomance instance are no longer opening.

**Expected behaviour:**

The Iron Gates should open when right-clicked.

**Steps to reproduce the problem:**

1. Right-click on Iron Gate in Scholomance
2. Nothing happens

**Branch(es):**

CHANGEME 3.3.5, master or both

f612b1cb4801

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
TrinityCore rev. f612b1cb4801+ 2017-03-02 01:22:55 -0300 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Linux (Fedora 24)

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
update you core before reporting bugs.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/071ba2c924ce4b27c9e16b38277ac729500f7445

**Comment by shadedmagus** [comment]
Confirmed fixed. Closing this report.
