### ISSUE TITLE
[master] DB/creature: Silverpine Forest

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19353]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Silverpine Forest spawns are missing and the Forsaken Campaign isn't implemented:
> https://www.youtube.com/watch?v=nVJRhtP5b1I

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/481825bd6d3139799cde79e14718d75ec603d728

**TDB version:**  703.00 + updates

**Operating system:** Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#15181

**Comment by ArcaneFox** [comment]
Sniffed with a clean Blood Elf Rogue (0 completed quest) but I don't have too mutch free time to finish this sql (it may contain duplicated spawns).


[Silverpine + Gilneas.zip](https://github.com/TrinityCore/TrinityCore/files/864656/Silverpine.Gilneas.zip)

**Comment by Aokromes** [comment]
seriously, NEVER, NEVER NEVER attach sniffs to a public place, people can see your personal data.
