### ISSUE TITLE
[master] mage spell Blizzard does not cast correctly

### ISSUE THREAD

**Issue by TaloniumSW** [TrinityCore/TrinityCore#19369]
**Description:**
Basically, we are trying to create a TrinityCore server using version 7.1.5 Build 23420 using the 7.3.0 Database files. And when we try to cast Blizzard, it goes through the timer and everything but nothing happens after that.

**Current behaviour:**
Casts the Blizzard spell but after the timer, it does not show any icicles coming from the sky and does not do any damage.

Error Code in Console: AreaTrigger <spellMiscId 4658> no created. Invalid areatrigger miscid <4658>

**Expected behaviour:**
Should cast the Blizzard spell, and show the icicles coming down from the sky and do damage.

CH

**Steps to reproduce the problem:**

1. Create a mage of any race ( I chose Human )
2. .level 109
3. Cast Blizzard

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. d45f535d3065 2017-03-25 17:54:19 +0100 <master branch> <Win64, RelWithDebInfo, Static> <worldserver-daemon>

**TDB version:**  703.00

**Operating system:** Windows 7 Professional x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
NYI - spell needs to be scripted.

**Comment by TaloniumSW** [comment]
If you want, i can try to script it tomorrow. But it may take some time

**Comment by TaloniumSW** [comment]
@tkrokli

**Comment by tkrokli** [comment]
Sure, feel free to go ahead. Just make sure you learn how to create & maintain a Pull Request from your own to the TC source. From what I can see, you do not seem to have forked the TrinityCore/TrinityCore repository to your own. You will need to start with that and then use git (Git Extensions) as described in the TC wiki: https://trinitycore.atlassian.net/wiki/display/tc/Windows+Requirements

**Comment by Aokromes** [comment]
#19078
