### ISSUE TITLE
Stratholme: Timmy the Cruel does not spawn

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19368]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Timmy the Cruel (ID 10808) is supposed to spawn near the gate at the south side of the courtyard immediately after you kill all of the scarlet crusade mobs in the courtyard.

http://wowwiki.wikia.com/wiki/Timmy_the_Cruel

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 986d830ae7b4 2017-03-23 03:58:03 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
TIMMY!

**Comment by offl** [comment]
c69825d96d6c7ff847c196c908e1040cb7a8d5db
