### ISSUE TITLE
[master] NPC Auctioneer Fitch No BroadcastTextID

### ISSUE THREAD

**Issue by Eleix** [TrinityCore/TrinityCore#19364]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Inside Stormwind's Auction House if you go to Auctioneer Fitch and try to open the Auction House menu he will just stand there and do nothing. 

**Current behaviour:**

Auctioneer Fitch does not open the auction house menu UI

> TC>HandleNpcTextQueryOpcode: no BroadcastTextID found for text 18205 in `npc_text table`

When: All the time

**Expected behaviour:**

Right clicking on Auctioneer Fitch should open the Auction House menu

**Steps to reproduce the problem:**

1. Go to Stormwind Auction House
2. Right Click on Auctioneer Fitch

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. df56f33a79b1 2017-03-23 15:38:53 +0100 (master branch) (Unix, Release, Static)

**TDB version:**  703.00 + updates

**Operating system:** Debian 8

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
ID 8719
Very likely the gossip_menu_id causes this, like Auctioneer Drezmit 44866.

**Comment by Eleix** [comment]
Actually just fixed the issue by importing mmaps. I didn't have them extracted but as I test I pulled them in and it appears to have fixed this issue.
