### ISSUE TITLE
[3.3.5] Obsidian Sanctum: killing Acolyte of Vesperon inside portal

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19363]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

There is a strange bug with Vesperon's Acolyte. When you killing him,all other mini-bosses and alive trash is entering combat and running to you.

**Current behaviour:**

After killing Vesperon's Acolyte inside the portal, all alive trash and mini-bosses running into your position.

**Expected behaviour:**

After killing Acolyte in "shadow realm", trash and mini-bosses must not aggro on you :(

**Steps to reproduce the problem:**

1. Pull Vesperon
2. Wait until portal is open
3. Kill Vesperon's Acolyte(add inside the portal)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9d6902331b4d+ 2017-03-25 13:34:11 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by markvetwow** [comment]
any news? :(

**Comment by tkrokli** [comment]
Unless you have got any suggestions for a solution yourself, you will need to wait until someone else figures out what is wrong and tries to do anything about it. Remember also that nobody gets paid to do this kind of work, so it depends entirely on when someone has got spare time to even try to figure out what needs to be done.

**Comment by junker1609** [comment]
For my part, the portal does not appear and one cannot even kill the acolytes.

**Comment by jackpoz** [comment]
when reporting an issue it helps a lot a developer if the description includes:
- clear .gm commands to speed up reproducing the issue, i.e. .go xyz or .go c id
- Creature entry when it's about creatures (.npc info) , GameObject entries when it's about gameobject
