### ISSUE TITLE
DB/GameObject: quest object broken for The Great Fras Siabi

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19367]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
While doing the quest The Great Fras Siabi (ID 5214) the box ([shown here](http://i.imgur.com/Jse6OA3.jpg)) is not able to be activated. Opening the box is supposed to summon Fras Siabi (ID 11058) who drops Siabi's Premium Tobacco (ID 13172).

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 986d830ae7b4 2017-03-23 03:58:03 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
It's a really bad idea to test things with gm account.

**Comment by jerbookins** [comment]
It makes no difference.

**Comment by RedSonja** [comment]
Having same issue too.

**Comment by Fearless18** [comment]
The problem is that can't be click because of flag

4 | 0x00000004 | GO_FLAG_INTERACT_COND | Untargetable, cannot interact

if change to flags=0, you can, but i guess that's not the solution.

**Comment by offl** [comment]
> GAMEOBJECT_TYPE_CHEST = 3
data8: questID (quest_template.id of completed quest)

data8 = 5214 should make the object targetable.

**Comment by tkrokli** [comment]
I would enjoy seeing this issue solved. I just wonder if the current DB content for that GO is based on sniff or not, or if MoP data has played any role here.

(Also thinking about all the comments from Aokromes stating "change GO data fields without sniff is hack".)

**Comment by offl** [comment]
data8 is already sniffed and added.
Don't know why it doesn't work.
This can be tested on master too, maybe on master it works fine.

**Comment by sirikfoll** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19367#issuecomment-319148502 is correct, set flags to 0 in gameobject_template_addon to fix it

**Comment by offl** [comment]
So why this flag was added to both branches? And what about data8 for GAMEOBJECT_TYPE_CHEST?

**Comment by schell244** [comment]
Issue is still not fixed. TrinityCore rev. 8c61ef228857 2019-12-09

**Comment by illfated** [comment]
Yeah, the discussion still seems to be whether or not it is valid to change the flag
```sql
4 | 0x00000004 | GO_FLAG_INTERACT_COND | Untargetable, cannot interact
```
to 0 (zero) to make it work, or if there is something else blocking it from working.

**Comment by jackpoz** [comment]
it would be nice to have some .go xyz coordinates with this kind of issues

**Comment by jackpoz** [comment]
To me the box sparkles and I was able to open it:
![image](https://user-images.githubusercontent.com/1153754/87884684-66ba6300-ca10-11ea-8383-92f74f923113.png)

**Comment by offl** [comment]
Works fine in 8675fd756ff9
