### ISSUE TITLE
Aurel Goldleaf in Silithus does not offer quest Medallion of Station

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19374]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
As part of the Dungeon 2 quest chain, the objective of Three Kings of Flame (quest 8961) requires that you obtain a Cinder of Cynders (item 21989). In order to summon a Duke of Cynders (creature 15206), you must have a full set of Twilight Trappings (itemset 492) and a Twilight Cultist Medallion of Station (item 20422) to activate a Wind Stone (object 180461). The Twilight Medallion of Station is unobtainable because Aurel Goldleaf (creature 15282) does not correctly offer the repeatable quest Medallion of Station (quest 8333).

- http://www.wowhead.com/quest=8961/three-kings-of-flame
- http://www.wowhead.com/item=21989/cinder-of-cynders
- http://www.wowhead.com/npc=15206/the-duke-of-cynders
- http://www.wowhead.com/item-set=492/twilight-trappings
- http://www.wowhead.com/item=20422/twilight-cultist-medallion-of-station
- http://www.wowhead.com/object=180461/wind-stone
- http://www.wowhead.com/npc=15282/aurel-goldleaf
- http://www.wowhead.com/quest=8333/medallion-of-station

**Current behaviour:** Aurel Goldleaf appears to offer no quest at all.

If I force add the quest 8333, a question mark appears over her head to complete the quest, she just doesn't offer it initially.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. 986d830ae7b4 2017-03-23 03:58:03 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.62

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
TrinityCore rev. 01aaafb0834d 2017-03-25 16:26:44 -0300 (3.3.5 branch) (Win64, Release, Static)
TDB 335.72 plus updates up to and including `2017_03_25_01_world.sql`

The tables `creature_queststarter` and `creature_questender` both show `id 15282` | `quest 8333` so that part is not the problem. For a moment, I was thinking that you might have a problem meeting the conditions for the quest, but checking the `conditions` table, I can't find quest ID 8333 mentioned in either column where it should be mentioned if the DB controls the conditions:
```sql
SELECT * FROM `conditions` WHERE `SourceEntry`= 8333 OR `ConditionValue1`= 8333;
```
[`empty result`]

Is this quest scripted in C++ ?

**Comment by jerbookins** [comment]
Aurel Goldleaf (15282) appears under creature_queststarter db:
    id    | quest
    ------------
    15282 | 8333

**Comment by tkrokli** [comment]
Yes, you are repeating what I said. "The tables `creature_queststarter` and `creature_questender` both show id 15282 | quest 8333 so that part is not the problem."

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `quest_template_addon` WHERE `ID` = 8333;
```
```
  ID  MaxLevel  AllowableClasses  SourceSpellID  PrevQuestID  NextQuestID  ExclusiveGroup  RewardMailTemplateID  RewardMailDelay  RequiredSkillID  RequiredSkillPoints  RequiredMinRepFaction  RequiredMaxRepFaction  RequiredMinRepValue  RequiredMaxRepValue  ProvidedItemCount  SpecialFlags
----  --------  ----------------  -------------  -----------  -----------  --------------  --------------------  ---------------  ---------------  -------------------  ---------------------  ---------------------  -------------------  -------------------  -----------------  ------------
8333         0                 0              0         8332            0               0                     0                0                0                    0                    609                      0                 3000                    0                  0             1
```

`SpecialFlags = 1` - Quest is repeatable.
`PrevQuestID = 8332` - did you complete quest 8332 "Dukes of the Council" first?
`RequiredMinRepValue = 3000` - requires Friendly standing
`RequiredMinRepFaction = 609` - with the Cenarion Circle

**Comment by jerbookins** [comment]
> did you complete quest 8332 "Dukes of the Council" first?

I did not. I will quest there some more and confirm.

**Comment by jerbookins** [comment]
Confirmed rep requirement, sorry I didn't even think about that.
