### ISSUE TITLE
mapextractor.exe stop responding immediately.

### ISSUE THREAD

**Issue by HonzsSedlomn** [TrinityCore/TrinityCore#19379]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

In the "Windows Server Setup" step, I'm trying to extract maps, but when i have chosen "Extract dbc/db2 and maps", mapextractor.exe has stopped responding.

**Expected behaviour:**

It should extract maps.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 85af0a06305e 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

TrinityCore rev. 85af0a06305e 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:**  3.3.5a

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
any console log ? this sounds like an issue that fits better on forum than on github since it's happening to your local configuration.

**Comment by HonzsSedlomn** [comment]
I solved it. I just needed to run it with admin rights. What a dumb i am.

**Comment by ariel-** [comment]
You shouldn't need to run it as admin (unless you are extracting from a folder that needs admin rights to write)

**Comment by tkrokli** [comment]
I think that is exactly what happened, that he ran the extractor in a sub-folder to `C:\Program Files\` or something similar.
