### ISSUE TITLE
Bodley NPC offers incorrect quest parts for D2 quest chain

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19375]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Further into the Dungeon 2 quest line, after turning in the quest "Three Kings of Flame" (8961), Bodley offers all 4 "Components of Importance" quests. This is incorrect, Bodley is supposed to offer you only one version of "Components of Importance" based on your class:
- 8962: Druidical Remains @ Hive Regal Silithus for Warrior and Mage
- 8963: Starbreeze Village Relic @ Frostwhisper Gorge Winterspring for Druid and Warlock
- 8964: Brilliant Sword of Zealotry @ Tyr's Hand Eastern Plaguelands for Hunter and Rogue
- 8965: Soul Ashes of the Banished @ Purgation Isle Hillsbrad Foothills for Priest, Paladin, and Shaman

"Components of Importance" is then followed-up with "The Left Piece of Lord Valthalak's Amulet" as listed below:
- If you do 8962, the follow up is 8966: Mor Greyhoof (Blackrock Spire)
- If you do 8963, the follow up is 8967: Isalien (Dire Maul)
- If you do 8964, the follow up is 8968: Jarien & Sothos (Stratholme, Live side)
- If you do 8965, the follow up is 8969: Kormok (Scholomance)

I did quest 8965, and Bodley offered me the correct follow up quest 8969 but he also offered 8966 which is wrong. He should only offer one. (Demo https://gfycat.com/GreedyFrailGuernseycow)

After completing "The Left piece of Lord Valthalak's Amulet", and the follow up "I See Alcaz Island in your Future" (quest 8970), "More Components of Importance" becomes available based on class. _Note: If you complete the wrong "Components of Importance" quest, Bodley will not provide the follow-up "More Components of Importance" after you turn in "I See Alcaz Island in your Future" (quest 8970)._
- 8985: Starbreeze Village Relic @ Frostwhisper Gorge Winterspring for Warrior and Rogue
- 8986: Druidical Remains @ Hive Regal Silithus for Druid, Paladin, and Shaman
- 8987: Brilliant Sword of Zealotry @ Tyr's Hand Eastern Plaguelands for Priest and Mage
- 8988: Soul Ashes of the Banished @ Purgation Isle Hillsbrad Foothills for Hunter and Warlock

And then each "More Compoents of Importance" quest leads into "The Right Piece of Lord Valthalak's Amulet" as listed:
- If you do 8985, the follow up is 8990: Isalien (Dire Maul)
- If you do 8986, the follow up is 8989: Mor Greyhoof (Blackrock Spire)
- If you do 8987, the follow up is 8991: Jarien & Sothos (Stratholme, Live side)
- If you do 8988, the follow up is 8992: Kormok (Scholomance)

http://wowwiki.wikia.com/wiki/Quest:Components_of_Importance
http://www.wowhead.com/quest=8985/more-components-of-importance#comments:id=1844029

Also, when you talk to Bodley, and click "Bodley, tell me what's going on", he gives you the complete Lord Valthalak's Amulet (item 22048) even before you're done with the quest line. And after you have completed the quest line, and killed Lord Valthalak, Bodley still provides the text "I've misplaced my Brazier of Beckoning!" which provides you with a new Brazier needed to summon Lord Valthalak.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 986d830ae7b4 2017-03-23 03:58:03 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.62

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Looks like there have been some changes in the conditions for all quests, so we need to rebuild a lot of conditions in the database. Feel free to write entirely new conditions for these quests.

**Comment by jerbookins** [comment]
I have edited this quite a number of times to try to make it as concise as possible.

**Comment by MrSmite** [comment]
In my DB they all have *AllowableClasses=0*. Perhaps this field would fix the problem?

I also note they all have *ExclusiveGroup=8962* but based on the wiki for this field, "a randomly assigned folllowup" or "all quests must be completed", it probably doesn't apply here.

**Comment by tkrokli** [comment]
Could possibly be that there is a quest requirement which has not been met, like this quest being last in a long chain or that several parallel quests in the region need to be done.

**Comment by jerbookins** [comment]
> Could possibly be that there is a quest requirement which has not been met

No. All of the quests work correctly, it's that some quests are offered when they shouldn't be.

**Comment by MrSmite** [comment]
Try this

```SQL
UPDATE `quest_template_addon` SET `AllowableClasses`=129 WHERE `ID`=8962;       -- Warrior / Mage
UPDATE `quest_template_addon` SET `AllowableClasses`=1280 WHERE `ID`=8963;      -- Druid / Warlock
UPDATE `quest_template_addon` SET `AllowableClasses`=12 WHERE `ID`=8964;        -- Hunter / Rogue
UPDATE `quest_template_addon` SET `AllowableClasses`=82 WHERE `ID`=8965;        -- Priest / Paladin / Shaman
UPDATE `quest_template_addon` SET `AllowableClasses`=9 WHERE `ID`=8985;         -- Warrior / Rogue
UPDATE `quest_template_addon` SET `AllowableClasses`=1090 WHERE `ID`=8986;      -- Druid / Paladin / Shaman
UPDATE `quest_template_addon` SET `AllowableClasses`=144 WHERE `ID`=8987;       -- Priest / Mage
UPDATE `quest_template_addon` SET `AllowableClasses`=260 WHERE `ID`=8988;       -- Hunter / Warlock
```

**Comment by jerbookins** [comment]
@MrSmite Excellent.

This has fixed the multiple quest issue regarding the first set of Components of Importance quests. However, there is still an issue with Bodley offering two versions of "The Left Piece of Lord Valthalak's Amulet".

On my test run, I completed quest 8963, which Bodley correctly offered me thanks to your fix, and then to follow it up, he offered me 8967 (which is correct) AND 8966. He should only offer me the one.

**Comment by MrSmite** [comment]
It appears those quests are faction based. Someone will have to dig up more info to be sure though...

[wowwiki has the complete chain](http://wowwiki.wikia.com/wiki/Quest:The_Left_Piece_of_Lord_Valthalak%27s_Amulet_(Stratholme))
but unfortunately doesn't mention class / race restrictions.

[Ten Ton Hammer's Details](http://www.tentonhammer.com/guides/dungeon-set-2-quests)
indicate Horde goes to Dire Maul and Alliance goes to Stratholme..

> The next part of the quest chain is to obtain the Left piece of Lord Valthalak's amulet. Depending on your faction it can be found in different places.

Horde - If you a Horde player Bodley sends you to summon the spirit of Isalien in Dire Maul east. The Spirit can only be summoned in Alzzin's Chamber. You can then get the left portion of the amulet and return to Bodley.

Alliance - If you are an Alliance player your next task is to obtain the left piece of Lord Valthalak's Amulet from Jarien and Sothos. However before you can summon them Bodley needs you to retrieve a brilliant sword of Zealotry from the praetorians in Tyr's Hand in the Eastern Plaguelands. Find the sword and return to Bodley. Now that you have the sword and brazier you can summon Jarien and Sothos and slay them. To do this you must travel to the room they were killed in. The room is the last room in Scarlet Stratholme

**Comment by jerbookins** [comment]
I disagree. It's class based.

The way Ten Ton Hammer wrote it out only specifies the differences between where to pick up the quests. The quest analysis is obviously incomplete because it doesn't reference that there are 4 different quests for both "The Left Piece of Lord Valthalak's Amulet" and "The Right Piece of Lord Valthalak's Amulet".

I believe that the information that I typed is as accurate and correct as possible.

**Comment by jerbookins** [comment]
http://i.imgur.com/P7bM6Bs.png

**Comment by MrSmite** [comment]
Ok then, based on the image you provided:

```SQL
-- Fix class restrictions for Dungeon Set 2 quest: The Left Piece of Lord Valthalak's Amulet
UPDATE `quest_template_addon` SET `AllowableClasses`=129 WHERE `ID`=8966;  -- Warrior / Mage
UPDATE `quest_template_addon` SET `AllowableClasses`=1280 WHERE `ID`=8967; -- Druid / Warlock
UPDATE `quest_template_addon` SET `AllowableClasses`=12 WHERE `ID`=8968;   -- Hunter / Rogue
UPDATE `quest_template_addon` SET `AllowableClasses`=82 WHERE `ID`=8969;   -- Priest / Paladin / Shaman

-- Fix class restrictions for Dungeon Set 2 quest: The Right Piece of Lord Valthalak's Amulet
UPDATE `quest_template_addon` SET `AllowableClasses`=9 WHERE `ID`=8990;    -- Warrior / Rogue
UPDATE `quest_template_addon` SET `AllowableClasses`=1090 WHERE `ID`=8989; -- Druid / Paladin / Shaman
UPDATE `quest_template_addon` SET `AllowableClasses`=144 WHERE `ID`=8991;  -- Priest / Mage
UPDATE `quest_template_addon` SET `AllowableClasses`=260 WHERE `ID`=8992;  -- Hunter / Warlock
```

**Comment by jerbookins** [comment]
Beautiful. That took care of Bodley offering more than one version of the same quest for "The Left Piece...". Thank you!

However, there are still issues with Bodley, regarding his speech options.

When you click "Bodley, tell me what's going on." He gives you the full Lord Valthalak's Amulet (ID 22048). He should have a speech page appear that says:
> "It's quite simple, really, <name>. My old merc company, The Veiled Blade, took the wrong mission at the wrong time. We were hired by a goblin smuggler out of Booty Bay, one Gremnik Rizzlesprang, who was covetous of Lord Valthalak's spellbook. Or, maybe there was some old rivalry there? I suppose we'll never know now, because Gremnik was killed not too long ago by a group of Valthalak's spectral assassins. They really can be very deadly when a large number of them gather. Where was I?"

http://wow.gamepedia.com/Bodley

**Comment by MrSmite** [comment]
Well in my DB Bodley has `gossip_menu`=0 so it seems his gossip system is messed up. I'm not sure how to make a gossip option give and item on the condition a quest is completed. Probably needs some C++ script to go with it.

Hopefully someone else can join in here. Although it seems a bit cosmetic since the quest chain is now completable ;)

**Comment by Killyana** [comment]
I cannot reproduce you gossip issue, for me it works correctly.
Here the commit: https://github.com/TrinityCore/TrinityCore/commit/e09a98bf1e3484b6917e298fc22cd69f93287b61

**Comment by jerbookins** [comment]
I mean to say that he currently provides an item upon speaking to him. He should not be giving an item at all. The complete gossip script is provided in the link in my previous comment.

**Comment by Killyana** [comment]
Yes my bad, the wrong gossip option ID was used in the sai event, here the fix:
``` sql
UPDATE `smart_scripts` SET `event_param2`=0 WHERE `entryorguid`=16033 AND `source_type`=0 AND `id`=3;

**Comment by jerbookins** [comment]
@Killyana Excellent!

Now the only standing issue I can see with Bodley is that he still offers the gossip "I've misplaced my Brazier of Beckoning!" even after you have completed the quest "Mea Culpa, Lord Valthalak" (ID 8995).

**Comment by tkrokli** [comment]
Adding a rule to `conditions` should fix the issue of when the gossip option is displayed.
https://trinitycore.atlassian.net/wiki/display/tc/conditions#conditions-SourceTypeOrReferenceId
- `CONDITION_SOURCE_TYPE_GOSSIP_MENU_OPTION` (15)

Let us find the necessary info to base the condition on:
```sql
SELECT * FROM `broadcast_text` WHERE `MaleText` LIKE '%Brazier of Beckoning%';
```
```
   ID  Language  MaleText                                  FemaleText                                EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
-----  --------  ----------------------------------------  ----------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  -------------
11784         0  I've misplaced the Brazier of Beckoning!  I've misplaced the Brazier of Beckoning!         5         0         0            0            0            0        0       0       1          18019
```
```sql
SELECT * FROM `gossip_menu_option` WHERE `OptionBroadcastTextID`= 11784;
```
```
menu_id      id  option_icon  option_text                               OptionBroadcastTextID  option_id  npc_option_npcflag  action_menu_id  action_poi_id  box_coded  box_money  box_text  BoxBroadcastTextID  VerifiedBuild
-------  ------  -----------  ----------------------------------------  ---------------------  ---------  ------------------  --------------  -------------  ---------  ---------  --------  ------------------  -------------
  57006       2            0  I've misplaced the Brazier of Beckoning!                  11784          1                   1           57018              0          0          0                             0              0
```
But which type of condition needs to be added? There are already 2 conditions present in TDB 335.62 for this gossip option:
```sql
SELECT * FROM `conditions` WHERE `SourceGroup`= 57006 AND `SourceEntry`= 2;
```
```
SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment
-----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  -----------------------
                     15        57006            2         0          0                         2                0            22056                1                0                  1          0            0              Requires Missing Item  
                     15        57006            2         0          0                         8                0             8995                0                0                  0          0            0              Requires Quest Rewarded
```
http://www.wowhead.com/item=22056/brazier-of-beckoning
http://www.wowhead.com/quest=8995/mea-culpa-lord-valthalak

Should the quest condition be changed to be valid only if the quest is NOT rewarded?

**Comment by Killyana** [comment]
The Brazier of Beckoning can always be taken form the npc if the player rewarded 8995, because it's not a quest item, and even after you complete this D1 quests you will keep it, and you can use it again to summon some boss in different donjons.

**Comment by tkrokli** [comment]
Then again, there are 2 different braziers:
**Brazier of Beckoning:** http://www.wowhead.com/item=22056/brazier-of-beckoning
(item provided for http://www.wowhead.com/quest=8995/mea-culpa-lord-valthalak)

**Quest: Return to Bodley** http://www.wowhead.com/quest=8996/return-to-bodley
**Reward:**
- Brazier of Invocation http://www.wowhead.com/item=22057/brazier-of-invocation
- Brazier of Invocation: User's Manual http://www.wowhead.com/item=22344/brazier-of-invocation-users-manual

**Comment by Killyana** [comment]
In this case this will fix the issue:
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup` IN (57006) AND `ConditionValue1`=8996 AND `NegativeCondition`=1;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15, 57006, 2, 0, 0, 8, 0, 8996, 0, 0, 1, 0, '', 'Requires Quest Not Rewarded');

**Comment by jerbookins** [comment]
`SQL query:
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup` IN (57006) AND `ConditionValue1`=8996 AND `NegativeCondition`=1
Matched rows: 0`

**Comment by tkrokli** [comment]
@jerbookins : The point of the first query (`DELETE FROM`) is to make the SQL repeatable, so that it can delete the same content as it inserts as well as any other preexisting matches (if any). If there are no matches already, it just continues to the next query (`INSERT INTO`).

**Comment by jerbookins** [comment]
Worked. Thank you!
