### ISSUE TITLE
Rend Blackhand Fight (UBRS) Broken

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19386]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** There are no waves of dragons leading up to the fight with Rend Blackhand & Gyth. Looks like the script is broken.

**Current behaviour:**
Currently, there is only one group of dragons that spawns behind the gate but they don't move out. The gate opens and closes a bunch until the scripting concludes and Rend finally runs out riding Gyth.

**Expected behaviour:**
When you begin the encounter, there are supposed to be multiple waves of Dragonkin of various kinds. The dragons should spawn behind the gate, the gate should open, the wave of dragons come out, the gate closes behind them, you kill the dragons, and immediately another wave of dragons is spawned behind the gate... repeat.

Wave:
1. 3 Chromatic Whelps, 1 Chromatic Dragonspawn
2. 2 Chromatic Whelps, 1 Chromatic Dragonspawn
3. 2 Chromatic Whelps, 1 Chromatic Dragonspawn, 1 Blackhand Dragon Handler
4. 2 Chromatic Whelps, 1 Chromatic Dragonspawn, 1 Blackhand Dragon Handler
5. 3 Chromatic Whelps, 1 Chromatic Dragonspawn, 1 Blackhand Dragon Handler
6. 2 Chromatic Whelps, 2 Chromatic Dragonspawn, 1 Blackhand Dragon Handler
7. Gyth & Rend

Video of the full encounter on current core build: https://youtu.be/RujH5wiMQNQ

Video of the full encounter on live (from cata, but essentially unchanged): https://youtu.be/1tGdVHw9HME?t=521

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. 85af0a0 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.62

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Elarose** [comment]
Also the guards that should spawn on the opposite ledge to nefarian after killing the first wave of trash don't appear. cmangos did some work on this, order should be this. https://youtu.be/lu94C5d9YoQ?t=480

**Comment by soniczhang11** [comment]
confirmed with b8c0aeaf14dfabc9940203aec21ef29111e755cc

**Comment by illfated** [comment]
(according to https://github.com/TrinityCore/TrinityCore/issues/24217#issue-573464937 , also confirmed using https://github.com/TrinityCore/TrinityCore/commit/cbe765df7a75f61941583ab95ecaa153e198d3de)

**Comment by LEO33SoFo** [comment]
The issue still exists as of 9d959123e68020a83c780f53a967b3589cb70786.

**Comment by JyriaLycion** [comment]
The issue still exists as of ae697a666ab9+

There was someone out there with a trinity core with a working script but can't seem to find him anymore since youtube is flooded with classic guides instead now.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15101
