### ISSUE TITLE
[3.3.5] Deathbringer not working in Alliance

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19389]
**Description:** Deathbringer not work in Alliance faction

**Current behaviour:** After click in gossip, nothing happens

**Expected behaviour:** After click in gossip, encounter should start

**Steps to reproduce the problem:**

1. Go to Deathbringer encounter with a Alliance Character
2. Talk to Murandin

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 8c3b6d57162a9da6006890dd46ad57d1f508d495

Issue caused by 0999ef0b774f2c93beefa6329d1a42a13377a35b
More details:
> You should add a entry check here.
> if (GetEntry() == creatureData->id)
> For example, High Overlord Saurfang in the battle of Deathbringer Saurfang, there is a UpdateEntry() in instance_icecrown_citadel to change the Saurfang's entry to Muradin for Alliance version, so the scriptid of Muradin is same as Saurfang, Muradin is not working to start the battle now, you can test it.
> https://github.com/TrinityCore/TrinityCore/commit/0999ef0b774f2c93beefa6329d1a42a13377a35b#commitcomment-21506458

Fix suggested by shenhuyong

```diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 3ae04cc..cea1b30 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -2591,7 +2591,8 @@ std::string Creature::GetScriptName() const
 uint32 Creature::GetScriptId() const
 {
     if (CreatureData const* creatureData = GetCreatureData())
-        return creatureData->ScriptId;
+        if (GetEntry() == creatureData->id)
+            return creatureData->ScriptId;
 
     return sObjectMgr->GetCreatureTemplate(GetEntry())->ScriptID;
 }
```

**Comment by Keader** [comment]
@Krudor , @ariel-  how clean this fix is?

**Comment by ariel-** [comment]
I have a better idea. Simply don't use creature/GO data scriptid if one is not provided in the table.
