### ISSUE TITLE
Scripts/BlackrockSpire: Emberseer fight broken

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19388]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The Blackhand Incarcerators (ID 10316) that surround Pyroguard Emberseer (ID 9816) are supposed to be non-hostile until you activate the Blackrock Altar (ID 176706). They are also supposed to be channeling some sort of spell at Pyroguard to maintain his shield. After you have activated the Blackrock Altar, the Blackhand Incarcerators will become hostile and attack if you're within agro radius, and channeling the Blackrock Altar should stop. There also should not be a spell called "Ember Seer Object Visual" being cast when you click the altar.

Currently the Blackhand Incarcerators are hostile, and simply walking into the room begins the fight and locks the entrance door. The doors should only close once the channeling is complete and the Incarcerators have become hostile.

Video of current core build: https://youtu.be/LMjpsom3zbM

Video of live server demonstrating fight (cata but essentially unchanged): https://youtu.be/vxSXOV2P6lM?t=520

**Branch(es):**  3.3.5

**TC rev. hash/commit:**   TrinityCore rev. 85af0a0 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**   335.62

**Operating system:**   Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Generic issue with cast bars shown: #17795 (Blackrock altar is a GO of type summoning ritual)

**Comment by Aokromes** [comment]
https://youtu.be/vri9bt0OQGk?t=266 yeah missing visuals + jailors agro incorrect

**Comment by offl** [comment]
All mentioned issues were fixed in https://github.com/TrinityCore/TrinityCore/commit/c3037c35639a547fca6be02ad1a0a2ed4c1c5fe9

> There also should not be a spell called "Ember Seer Object Visual" being cast when you click the altar.

https://github.com/TrinityCore/TrinityCore/issues/17795

> and channeling the Blackrock Altar should stop.

It's not shown in the video you provided
