### ISSUE TITLE
The Beast Fight (UBRS) Broken

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19387]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Firstly, there are two Blackhand Elite orcs standing directly next to The Beast (ID 10430). There is also a Blackhand Assassin orc that stealths around the room. The reason there are orcs near him is because there should be a scripted event where the 3 orcs begin running away from the beast and then die about 10 feet into the room.

Secondly, when you approach Beast in his dark hole there is a trigger that makes him walk out and then the first player he hits gets punted super high in the air, and flies all the way across the room.

Video demonstrating current core build: https://youtu.be/gPWQcC6W2r8
(The Blackhand Assassin you see in the video was killed by me.)

Video demonstrating live server (cata but essentially unchanged): https://youtu.be/vxSXOV2P6lM?t=1672
You can see that after the beast was triggered, the orcs are running away from his hole and then die. This simply demonstrates the timing of the blizz-like script. The people in the video pulled the beast sooner than the script was executed.

**Branch(es):**   3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 85af0a0 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**   335.62

**Operating system:**  Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Elarose** [comment]
Finkle Einhorn should appear only once the beast is killed and skinned, http://wow.gamepedia.com/Finkle_Einhorn
and say
 http://smg.photobucket.com/user/suz_euan/media/WoW/finkle.jpg.html

**Comment by HelloKitty** [comment]
@jerbookins This fork may help in your efforts to work on The Beast or UBRS. It includes some area triggers and etc for The Beast as well as some improved behavior. However, I had just started learning TC at the time so it's not great and thus I never attempted a PR for the mess.

You may find use from it, feel free to pilfer what you want if anything from it. https://github.com/HelloKitty/TrinityCore/commits/3.3.5-UBRSRefactor

**Comment by Keader** [comment]
56b0433b6d842e5928a453fc4bac837856ef91a7
