### ISSUE TITLE
Ysida Harmon (ID 16031) / Dead Man's Plea (ID 8945) Not Fully Scripted

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19384]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Ysida Harmon (ID 16031) is supposed to be trapped inside of a cage, and visible (and alive, if you are fast enough) at all times regardless of whether you have the quest. If you're on the quest Dead Man's Plea (ID 8945), you are correctly given The Baron's Ultimatum upon unlocking the Gauntlet Gate. If the debuff wears off, Baron kills Ysida. If you survive, the cage is unlocked and Ysida steps out of it.

Video of what happens in current core build: https://youtu.be/s9iS7pRPqTw
Pretty old video of a speed run: https://www.youtube.com/watch?v=--IiC_Wuxfg
Image of Ysida after you rescue her: https://s.blogcdn.com/wow.joystiq.com/media/2012/07/you-did-it.jpg

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 85af0a0 2017-03-29 11:28:06 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Closed by 2a25d9d9a7a7d4aa8b06f9cd0bb26b123adf7789
