### ISSUE TITLE
Sindragosa 25nm spell bug

### ISSUE THREAD

**Issue by Adizbek** [TrinityCore/TrinityCore#19395]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Sindragosa 25nm, in second phase spell of sindragosa doesn't work correctly. 
It should damage only character who is in the ice tomb, but it damages nearby characters.  

**Expected behaviour:**
Damage only character who is in the ice tomb

**Branch(es):**
3.3.5 
**TC rev. hash/commit:**
b9d456f 

TrinityCore rev. b9d456fad1e3 2017-03-31 02:41:42 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB_full_335.62_2016_10_17.7z

**Operating system:** LINUX

**Comment by ariel-** [comment]
There is a zone wide aura hitting players periodically. You have to be more precise and include combat logs

**Comment by Adizbek** [comment]
25nm only buggy. 10nm works well.

**Comment by Demonid** [comment]
Screenshots or more precise information?

**Comment by Keader** [comment]
10d without answers, so closing...
