### ISSUE TITLE
[NPC][3.3.5] Malygos Vortex trigger.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19390]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

When Malygos using his Vortex spell,there is an issue with triggering.

**Current behaviour:**

So,when Malygos is casting his Vortex spell,he pulls into Vortex only 1 player(1st aggro) into Vortex,all other players standing in platform,and after Malygos landing,they are going out of combat for a while.

**Expected behaviour:**

Malygos must pull all players in his Vortex.

**Steps to reproduce the problem:**

1. Pull Malygos with several players
2. Wait until Vortex cast
3. :(

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. dafa7267737a+ 2017-03-31 01:58:15 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#10181
