### ISSUE TITLE
[3.3.5][Naxx] Frogger,again.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19399]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Issue with Living Poison NPC triggering.

**Current behaviour:**

If player walks through Frogger NPC,this NPC do not use its exlposion spell.

**Expected behaviour:**

Frogger NPC must use their exlposion spell on players,if they walk through them.

**Video proof:**

[Link on YouTube](https://www.youtube.com/watch?v=VJ07Ou6J638)

**Steps to reproduce the problem:**

1. TP to Naxx
2. Go into Construct Quarter,you'll see these NPCs near Patchwerk
3. Try to walk through them
4. :(

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 7588be0ac5d4 2017-04-01 02:55:41 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Still valid @Treeston ?

**Comment by Treeston** [comment]
No idea, try it?

**Comment by gonzo1247** [comment]
Still exist. Testet with rev. 6c7c2c6cd279813333e0b1cc1f60b22a04f368dd

**Comment by offl** [comment]
174ac958009222aeef83520101a28963f8c63b0e
