### ISSUE TITLE
[Stats] Weapon dependent talents are not applied immediatly after learned

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#19408]
**Description:**

If you learn a new talent or switch specialisation, weapon dependant talents require to log out / in or unequip weapon to take effect.

**Current behaviour:**

If you learn a new talent or switch specialisation, weapon dependant talents require to log out / in or unequip weapon to take effect.

**Expected behaviour:**

Talents should take effect immediatly

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Login as a dk, have a two handed weapon equiped
2. Learned two handed weapon spec, stats don't change
3. Unequip / equip same weapon, stats change

**Branch(es):**
Known on 3.3.5, probably both

**TC rev. hash/commit:** 

 226a69f5dc5effb8182cd5ffa64b0ff405c5d580

**TDB version:**   226a69f5dc5effb8182cd5ffa64b0ff405c5d580

**Comment by Persephone** [comment]
Confirmed, I fixed it tem by checking it the new aura was not added, then add it. in player::learntalent

**Comment by joshwhedon** [comment]
Yeah, but since there is a specific check which ensures that we don't apply auras which are item dependant on learn, I would expect that to potentially cause problems elsewhere.
