### ISSUE TITLE
gossip typo for Sen'jin Champion's Pennant

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19402]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Something very minor again, I'm bothering you with. There is a small typo where an apostrophe ate a bit of a word and left afterwards hurriedly. In gossip_menu_option the entry at menu_id 10317, id 3 reads _Sen Champion's Pennant_. It should read of course _Sen'jin Champion's Pennant_.

This should correct the problem:

```SQL
UPDATE `gossip_menu_option` SET `option_text`= 'Sen\'jin Champion\'s Pennant' WHERE `menu_id`= 10317 AND `id`=3;
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** a2a8ffe72328

**TDB version:**  according to core version

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
In fact, looking at broadcast_text it must be:

´´´sql
UPDATE `gossip_menu_option` SET `option_text`='Darkspear Champion\'s Pennant' WHERE `menu_id`=10317 AND `id`=3;
UPDATE `gossip_menu_option` SET `option_text`='Forsaken Champion\'s Pennant' WHERE `menu_id`=10317 AND `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33681 WHERE `menu_id`=10317 AND `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33682 WHERE `menu_id`=10317 AND `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`='33683' WHERE `menu_id`=10317 AND `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`='33685' WHERE `menu_id`=10317 AND `id`=6;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`='33686' WHERE `menu_id`=10317 AND `id`=7;

**Comment by TecDian** [comment]
Good point. You may write it a little more compact.

```SQL
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33681, `option_text`=(SELECT `MaleText` FROM `broadcast_text` WHERE `ID`=33681) WHERE `menu_id`=10317 AND `id`=3;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33682, `option_text`=(SELECT `MaleText` FROM `broadcast_text` WHERE `ID`=33682) WHERE `menu_id`=10317 AND `id`=4;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33683 WHERE `menu_id`=10317 AND `id`=5;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33685 WHERE `menu_id`=10317 AND `id`=6;
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=33686 WHERE `menu_id`=10317 AND `id`=7;
```
