### ISSUE TITLE
Spawning an NPC with scripts will result in invalid scriptid

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#19405]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Adding an NPC with commands (possibly also with other means) that has a C++ script attached to it will cause the NPC not have a script since the scriptid is wrong from `Creature::GetScriptId` call.
Through debugging I can see that 3452816845 was returned as script ID from `creatureData->ScriptId` instead of 190010 that comes from `sObjectMgr->GetCreatureTemplate(GetEntry())->ScriptID` and is the real one. 
Restarting the server will fix the issue.
For further reference: http://www.ac-web.org/forums/showthread.php?226972-Custom-Scipts-Error

The issue is probably caused by the new spawn specific scripts.
https://github.com/TrinityCore/TrinityCore/pull/19247

Master branch possibly has the issue fixed already I hope.

**Current behaviour:**
- Add an NPC to DB that has a C++ gossip script to show a menu on gossip hello.
- Start server
- Spawn the NPC through `.npc add ###`
- Click on the NPC to open the gossip window
- The NPC will show the default "Greetings, <name>" text only and no scripted options.

**Expected behaviour:**
- Add an NPC to DB that has a C++ gossip script to show a menu on gossip hello
- Start server
- Spawn the NPC through `.npc add ###`
- Click on the NPC to open the gossip window
- The NPC has shows the scripted menu

**Steps to reproduce the problem:**

- Add an NPC to DB that has a C++ gossip script to show a menu on gossip hello.
- Start server
- Spawn the NPC through `.npc add ###`
- Click on the NPC to open the gossip window
- The NPC will show the default "Greetings, <name>" text only and no scripted options.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
Real TC version b9d456fad1e39943502218b3fe065be36810e139

The stuff that you wanted:
TrinityCore rev. b1ce3436febc 2017-03-31 14:10:12 +0300 (transmog branch) (Win32, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
Indeed. CreatureData::ScriptID is left uninitialized
