### ISSUE TITLE
[3.3.5] Judgement of Wisdom

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19400]
**Current behaviour:** Judgement of Wisdom always restore 1% of Base mana when effect proc.

**Expected behaviour:** Judgement of Wisdom should restore 2% of Base mana when effect proc.

**Steps to reproduce the problem:**

1. Learn max ranking of Judgement of Wisdom
2. Use judgement in some target and wait effect proc

Searching the reason, looks caused here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_paladin.cpp#L1596

```aurEff->GetAmount()``` of ```20186 - Judgement of Wisdom``` = 1.
But Judgement of Wisdom tooltip says 2%.

<details>

![wowscrnshot_040117_185620](https://cloud.githubusercontent.com/assets/7120913/24582749/f444bd2a-170c-11e7-87ef-e9fdeb45eecd.jpg)

</details>

Maybe 20186 has a DBC issue, or missing some ranking?

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 43c19f17abcf58a7edf3a17e419f4991e1ad100e

**Comment by Keader** [comment]
@ariel-  can take a look? xd

**Comment by P-Kito** [comment]
If it's a "hard number" in SpellWork Description, just put a 2 in there I guess

**Comment by ariel-** [comment]
Not a hard number, but using aurEff amount instead of doing what tooltip says ("$20268s1% of the attacker's base mana")

**Comment by P-Kito** [comment]
Didnt check Spellwork, I thought so :P
