### ISSUE TITLE
[3.3.5] Quest Offer Reward Text not shown

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#19403]
TrinityCore rev. 58f2e62098f2 2017-04-03

It seems that the text in the field RewardText of the table quest_offer_reward is not shown anymore to the player. Instead it comes always the text of the field CompletionText of the table quest_request_items.

In earlier versions it was not like this.

Example:
Make a Undead character. 
.quest add 8 (you get an starter item, a letter)
.go xyz 2269.51 244.944 34.3402 0 (jump to the quest finisher)
Check the text in the gossip window, it's: 
"Yes? Yes? What is it?$B$BThe forsaken; they certainly do have huge appetites. ......"

But it should be:
"Oh? A letter? Wonderful news! I've been waiting on word from my dear old mother in Deathknell. "

Because you have the letter and can finish the quest.

**Comment by TecDian** [comment]
My revision is a little earlier, so I don't know for sure, whether it has changed. But the correct behaviour is (and so it works):

You talk to the quest ender.
The dialogue window shows the option to give in the quest.
You click the option and the CompletionText is shown.
You click on the continue button and the RewardText is shown.
You click on finish.

So CompletionText is always shown. This is the correct way. Are you really sure the is a problem?

**Comment by Magnifikator** [comment]
If that's blizzlike that the completiontext is ALWAYS shwon before, it's may not an issue.
On some quests it's maybe a little bit irritating, because the completiontext implies sometimes that the quest is NOT finished.

**Comment by tkrokli** [comment]
The main rule is that if the quest involves any quest item(s) to be delivered to the quest ender (removed from player character's inventory), the `quest_request_items` table will be involved. When the quest does not involve any quest item(s) and only has got 1 quest completion gossip window (no "Continue" button), you will find that only `quest_offer_reward`.`RewardText` is used.

**Comment by Magnifikator** [comment]
That's a very good explanation. Thank you.
