### ISSUE TITLE
Scryer Library

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19410]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The Scryer Library (profession trainer objects) are not supposed to be usable until you are aligned with the Scryer faction.

![wowscrnshot_040517_171925](https://cloud.githubusercontent.com/assets/16745918/24731085/14f5565e-1a25-11e7-9374-c752d5e2b027.jpg)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b7329a460e58 2017-04-01 03:19:57 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
> -- Sry, what actually mean Scryer-aligned? Is Friendly enought?
> -- [I just used as neutral.](http://www.wowhead.com/npc=33619/cooking#comments:id=812609)

And there's no reason to add the conditions. If Scryers will hate you, you will not able to interact with these NPCs.
I think "Scryer-aligned" means neutral+ reputation. Not friendly or hated.

**Comment by Killyana** [comment]
According to many comments, you can use this trainers if you're not aligned :
http://www.wowhead.com/npc=33617/mining#comments:id=685997:reply=519132
http://www.wowhead.com/npc=33613/tailoring#comments:id=706676:reply=1038385

**Comment by jerbookins** [comment]
It looks like you are misunderstanding. He says

>As long as you are either NOT attuned or are attuned to Scryers, you can use these.

Meaning:

1. If you attune with Aldor, you are hated by Scryer and you **cannot** use the trainers.
2. If you are not attuned with either Aldor or Scryer you can use the trainers.
3. If you attune with Scryer, you are hated by the Aldor and you **can** use the trainers.
