### ISSUE TITLE
3.3.5 Icecrown Citadel 10h. Bug with Professor mobs 

### ISSUE THREAD

**Issue by Adizbek** [TrinityCore/TrinityCore#19415]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**Mobs doesn't attack.
They are in screenshoot.

**Expected behaviour:**
They should attack
![sdsdsd](https://cloud.githubusercontent.com/assets/10253982/24815543/ddb26a44-1bee-11e7-8065-ddd75c96e6f2.jpg)

**Branch(es):**
3.3.5 
**TC rev. hash/commit:**
b9d456f 

TrinityCore rev. b9d456fad1e3 2017-03-31 02:41:42 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB_full_335.62_2016_10_17.7z

**Operating system:** LINUX

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8d198cb36050e63811f8f7f81a3daf2a3c961950

**Comment by bahajan95** [comment]
Адизбек нужно по больше мержить или следить за коммитами а не создавать багрепорт который уже пофиксен
