### ISSUE TITLE
[3.3.5] Core crash after a commit.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19422]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

After 21b8c49, when you entering a Halls of Stone on any difficulty,core is crashing.

**Crash log**:

[21b8c4997a26+_worldserver.exe_[8-4_14-51-22].txt](https://github.com/TrinityCore/TrinityCore/files/907423/21b8c4997a26._worldserver.exe_.8-4_14-51-22.txt)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 21b8c4997a26+ 2017-04-07 21:35:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Riztazz** [comment]
@ccrs noob
