### ISSUE TITLE
[3.3.5] Halls of Stone: Tribunal of Ages issue,in addition to another issue.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19429]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

So, if speaking more precisely, there is an issue with encounter resetting.

**Current behaviour:**

In addition to #11991, encounter are not resetting after party wipes. Brann don't respawn. Gameobjects are not resetting.

**Expected behaviour:**

Encounter must reset after party wipes and Brann death.

**Steps to reproduce the problem:**

1. Start Brann Escort encounter.
2. .die on yourself and party members.
3. Allow mobs to kill Brann.
4. :(

**Branch(es):**

335.62

**TC rev. hash/commit:** 

TrinityCore rev. 2921449a333e+ 2017-04-09 09:25:58 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
post there.
