### ISSUE TITLE
[3.3.5][Pet] Pets summoned by ability issue.

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19420]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

There is an issue when you summon your Dancing Rune Weapon (or other summon by ability pets like Shadowfiend)

**Current behaviour:**

When you summon them (using your ability), they don't start attacking your target, Only if you click on attack button on pet bar. As you know, there is no pet bar when you summon DRW so weapon just floating in place and does nothing. Same issue with hunter pet can exist sometimes.

But there is another issue can happen. When you buff your pet by bloodlust and forcing him to attack your target,he do it as needed, but when bloodlust expires, pet stops any attacks and stands still in front of the target.

**Expected behaviour:**

When you summon your pet by ability(spell), it must start auto-attacking your target.

**Video proof with Runic Weapon issue:** [Link on YouTube.com](https://www.youtube.com/watch?v=_D96Qw3yw-0)

**Steps to reproduce the problem:**

1. Create DK
2. Use Dancing Runic Weapon on neutral or hostile target.
3. :(((((

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 21b8c4997a26+ 2017-04-07 21:35:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
> Same issue with hunter pet can exist sometimes.

Hunters: Working as intended

Hunter pet always spawns as defensive except on first tame when it is set to passive. If the Hunter is attacking something that is not also attacking the Hunter, the pet will not attack because that is what aggressive setting is for. Defensive requires the Hunter to be attacked.

Guardian summons: Possibly broken

Guardians (eg: pets without pet bar) are supposed to be set to aggressive on summon, perhaps this is not happening with the rune weapon?

**Comment by Aokromes** [comment]
Rune weapon already have one ticket and one PR waiting for review.

**Comment by Killyana** [comment]
same issue as https://github.com/TrinityCore/TrinityCore/issues/16464

**Comment by markvetwow** [comment]
But what about hunter's pet after BL expires? my pet stops attacking when bloodlust aura is fading from pet.

**Comment by Keader** [comment]
> Rune weapon already have one ticket and one PR waiting for review
Waiting for implement...

**Comment by MrSmite** [comment]
> But what about hunter's pet after BL expires? my pet stops attacking when bloodlust aura is fading from pet.

Maybe there's a bug returning the pet to normal attack speed.

I know the Hunter talent Frenzy works fine, when it wears off your pet returns to normal attack but I wonder if the attack speed is perhaps being set to zero when bloodlust wears off?
