### ISSUE TITLE
Stonescythe Whelps are not hostile

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19428]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Stonescythe Whelps should be hostile A/H

http://www.wowhead.com/npc=16927/stonescythe-whelp

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b7329a460e58 2017-04-01 03:19:57 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by offl** [comment]
```sql
--
UPDATE `creature_template` SET `faction` = 1873 WHERE `entry` = 16927;
```

**Comment by jerbookins** [comment]
Beautiful.
