### ISSUE TITLE
Characters Table

### ISSUE THREAD

**Issue by bblewittAG** [TrinityCore/TrinityCore#19430]
I am moving over all my accounts from 1 database of the TDB 59 to the TDB 62 core and there is skin, face, hair and facial hair coloums not playerbytes 1 and 2?

Branch: 3.3.5a

TrinityCore rev. f85266733214+ 2017-04-08 21:47:38 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

TDB 335.62
Windows 10 x64

**Comment by Aokromes** [comment]
this belongs to forum.

**Comment by DDuarte** [comment]
Apply character updates in order. One of them coverts the old tables to the new format.
