### ISSUE TITLE
[3.3.5] Spell Reflection dont reflect Chaos bolt

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19439]
**Description:**  Spell Reflection should reflect Chaos Bolt

spell 23920 = [Spell Reflection]
spell 59172 = [Chaos Bolt]

**Current behaviour:** Chaos bolt ignore Spell Reflection

**Steps to reproduce the problem:**

1. Put 1 warrior and 1 warlock in duel
2. Cast chaos bolt with warlock
3. Cast spell reflection (before cast finish)

PS: Cast Spell Reflection before chaos bolt start cast, or after cast start dont change nothing in this case

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 21b2042840e05ebeba365c54d47c07c13fde123f

**Comment by ariel-** [comment]
83177e771a373514913d066e14d5a7f9775407fe
