### ISSUE TITLE
Core/Crash worldserver crash in Taldaram encounter.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19434]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Crash in azjolnerub with boss_prince_taldaram.
This core has pvpranks and passive anticheat patch from Aokromes, the hash in log is misssing for a reason IDK.

**Current behaviour:**

log here https://gist.github.com/HannibalRoG/a6b5d871ad90c4a7e6892425b0cd0a04

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f852667332142da4d254c867d06874065f096fe2

**TDB version:**  3.3.5 62

**Operating system:** See log

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
Update your core to at least https://github.com/TrinityCore/TrinityCore/commit/46221b6dc1272989e0de85a4563fc49dba8e7851

**Comment by HannibalRoG** [comment]
Ok. i will do it.

**Comment by ariel-** [comment]
The log doesn't correspond to what you report (and it's from a month ago)

**Comment by HannibalRoG** [comment]
[unknown_worldserver.exe_[10-4_3-26-0].txt](https://github.com/TrinityCore/TrinityCore/files/910853/unknown_worldserver.exe_.10-4_3-26-0.txt)

sorry is this, gist is dummy

**Comment by ariel-** [comment]
Player::CreateWowarmoryFeed -> this function does not belong to TrinityCore.

Please report on a clean TC install

**Comment by HannibalRoG** [comment]
Yes iam forgot that patch for armory, but i think that its not the problems.

**Comment by ariel-** [comment]
It is, it's part of the crashing backtrace:

```
Call stack:
Address   Frame     Function      SourceFile
00007FF6489A1A6F  00000082A69AEC00  Object::GetGuidValue+F  d:\repositorios\3.3.5\src\server\game\entities\object\object.cpp line 315
00007FF6489EFC99  00000082A69AED10  Player::CreateWowarmoryFeed+49  d:\repositorios\3.3.5\src\server\game\entities\player\player.cpp line 26827
00007FF648B626E1  00000082A69AEF00  Unit::Kill+E61  d:\repositorios\3.3.5\src\server\game\entities\unit\unit.cpp line 12169
00007FF648B55035  00000082A69AF110  Unit::DealDamage+D55  d:\repositorios\3.3.5\src\server\game\entities\unit\unit.cpp line 856
```
