### ISSUE TITLE
Startup error, character_fishingsteps table does not exist.

### ISSUE THREAD

**Issue by FrostbyteGR** [TrinityCore/TrinityCore#19431]
**Description:**
When pulling the 3.3.5 branch, the "2017_02_26_00_characters_2016_09_13_00_characters.sql" file is absent from "sql/updates/characters/", causing a worldserver startup error (complaining about character_fishingsteps table missing).
Had to manually inject it into my database, in order to get it working.

**Current behaviour:** Server will not complete it's start up sequence.

**Expected behaviour:** Server should complete it's start up sequence.

**Steps to reproduce the problem:**
1. Pull and compile latest TC.
2. Populate auth, character, world databases and apply sql updates from source
3. Launch authserver and world server.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. f85266733214 2017-04-08 21:47:38 +0200 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)

**TDB version:** TDB 335.62

**Operating system:** Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)

**Comment by Demonid** [comment]
Are you updating a old core/database?

Because that table is already implemented on base characters.sql

**Comment by FrostbyteGR** [comment]
Well, I done did derped.. I actually updated up to 335.61, instead of 335.62
My bad, you can close this.

**Comment by FrostbyteGR** [comment]
Well, I done did derped. Turns out I had updated up to 335.61 instead of 335.62, my bad,
