### ISSUE TITLE
[3.3.5][Crash] Vyragosa

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19436]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** When fighting Vyragosa (npc id: 32630) after she casts a spell the server crashes, pretty sure its the frost breath one but am not 100%.

**Current behaviour:** Server crashes.

https://gist.github.com/Persephone/97711b9c1bf91d092573dba799b1cdab

**Expected behaviour:**

Shouldnt crash. I was told this did not happend earlier today, before i updated to: https://github.com/TrinityCore/TrinityCore/commit/e565b34f6d24411e210151d0d03e524f94cdff85

Was told no crash before I updated.

**Steps to reproduce the problem:**

1. Spawn vyragosa: .npc add 32630 then stand still and get shot, if no crash then die yourself and respawn.
2. It will crash

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/e565b34f6d24411e210151d0d03e524f94cdff85

**TDB version:**  TrinityCore rev. c47ad7b91b93 2017-04-10 15:00:19 +0200 (3.3.5 branch) (Unix, RelWith-DebInfo, Static)	c47ad7b91b93	TDB 335.62
TrinityCore rev. c47ad7b91b93 2017-04-10 15:00:19 +0200 (3.3.5 branch) (Unix, RelWith-DebInfo, Static)	c47ad7b91b93	TDB 335.62

**Operating system:** ubuntu 14.04

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
looks like binary resist issue =x

**Comment by ariel-** [comment]
Ah. Melee damage with magic school, silly.

**Comment by Persephone** [comment]
Woah, fast reactions! Thanks guys :-)!
