### ISSUE TITLE
The Fel and the Furious Quest Broken

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19435]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
After accepting the quest The Fel and the Furious (ID 10612) the Fel Reaver Control Modules become active (ID 185058, 185057, 185034) but do not function when clicked.

Clicking on the Control Module should essentially mind control one of the Fel Reaver Sentinels (ID 21949) so you can use their abilities to wipe out the infernals.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e478434146fd 2017-04-09 19:18:22 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#6778
