### ISSUE TITLE
ObjectMgr not implemented branch 3.3.5

### ISSUE THREAD

**Issue by Adizbek** [TrinityCore/TrinityCore#19437]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** Why functions of ObjectMgr: GetPlayerByLowGUID, GetPlayerGUIDByName and some others which are in master branch aren't implemented in branch 3.3.5

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** b9d456f 

TrinityCore rev. b9d456fad1e3 2017-03-31 02:41:42 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB_full_335.62_2016_10_17.7z

**Operating system:** LINUX

**Comment by ariel-** [comment]
Questions belong to forum
