### ISSUE TITLE
[3.3.5] Empowered Corruption, wrong calculation

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19442]
**Description:** Idk if i missunderstand something... but Empowered Corruption calculation looks wrong.

With a new warlock character (gnome), i got Corruption ranking 10 (Spellid:  47813)
Added a staff (to have a little spell power) item 50966 = [Abracadaver]
I'm casted 1 corruption on Ironforge Dummy (entry=31144). Each tick of corruption damaged 311.
I added 1 point Empowered Corruption (i did it by .aura 32381,for other talents not interfere)
Casted other corruption on Ironforge Dummy. Each corruption tick damaged 324.

Based talent description, corruption amount should increases = 12% of my spell.
My warlock has 657 of spell power... making some calculations:

657 * 0,12 = 78,84
311 + 78,84 = 389,84

So... with 1 point expected is 389,84 but obtained is 324
Same results applies to other rankings
Again, idk if i missunderstand something...

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 21b2042840e05ebeba365c54d47c07c13fde123f

**Comment by MrSmite** [comment]
Do those dummies have any resistances?

**Comment by ariel-** [comment]
The calculation is correct. Keep in mind Corruption inherits 20% of your spellpower (spell_bonus_data table)

Corruption tick damage = Base Damage + SP * coeff
Base is 180 for rank 10, so

180 + 657 * 0.2 = 311.4 -> correct

now we factor in Empowered Corruption. it increases spell power coefficient by 12% on the TOTAL SPELL DAMAGE, we need to calc the amount increased on each tick to be certain.

Corruption tick damage = Base Damage + (SP * (coeff + (emp. corruption / number_of_ticks) / 100)

number of ticks = maxduration / amplitude = 18000 / 3000 = 6

So the formula now is
180 + 657 * (0.2 + (12 / 6) / 100) = 180 + 657 * (0.2 + 0.02) = 180 + 657 * 0.22 = 324.52 -> as what you actually get in game

**Comment by Keader** [comment]
Hmm... perfect, thanks.
