### ISSUE TITLE
[3.3.5]Stuck tool not working correctly

### ISSUE THREAD

**Issue by Reckfull** [TrinityCore/TrinityCore#19449]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

The (Unstuck) (http://www.wowhead.com/spell=7355/stuck#changelog) option has to leave the player in the area where he is born. What you are doing is using (Hearthstone) (http://www.wowhead.com/item=6948/hearthstone) to go to that location.
After being used you must wait 5 minutes of cooldown, but your (Hearthstone) also have 30-minute of cooldown. After 5 minutes (Stuck) when used does not work and leaves you in the same area where you are.

**Current behaviour:**

The Struck Tool is now a Hearsthstone more, Not working as it should work.

**Expected behaviour:**

The (Hearthstone) and (Stuck) should work separately and have the same cooldown, too (Stuck) should take the characters to their birth zone, not to their Hearthstone or same place of you character are at that moment

**Steps to reproduce the problem:**

1- Open (Unstuck) Tool.
2- Use the tool (Stuck)
3- Wait 10s to get to your tavern (Hearthstone)
4- Open inventory.
5- Look at the Hearthstone and you will have 30 minutes cooldown.
6- Wait 5 minutes to use again (Stuck).
7- Use (Stuck).
8- Stay in the same place where you use it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6c3eaff81dda

TrinityCore rev. 0b50ea072e50 2017-04-10 12:17:08 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB_full_world_335.62_2016_10_17.sql

**Operating system:** Linux Debian 8.7

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by MrSmite** [comment]
Your link points to version 5.0.1 but your report is for 3.3.5

> 5.0.1 (Thu Jun 28 2012) Build 15589 - 1.7% base mana, 1.5 second CD
> 5.0.1 (Thu Jun 28 2012) Build 15544 - 1.5 second CD

**Comment by Aokromes** [comment]
#17291
