### ISSUE TITLE
[3.3.5] Mind Control vs NPC

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#19447]
Description: Mind Control is fading after fading after 10 seconds on a NPC.

[Mind Control] = SpellID 605

Expected behaviour: Mind Control on NPC should last for 60 Seconds (1 Minute).

Steps to reproduce the problem:

1- Mind Control an Humanoid
2- Wait 10 seconds
3- Mind Control Breaks

Seems like the Mind Control Aura is not being applied to NPC, before you could see a Debuff that lasted for 60 seconds on the NPC.

Proof:

http://i.imgur.com/YarTsDZ.jpg

Branch(es): 3.3.5

TC rev. hash/commit: 5cb1555de6db43db03d6202b7edaa9c6835ecfab

**Comment by Riztazz** [comment]
This happens because the aura is applied on caster instead of unit and so diminishing returns kick in, the question is why is it applied on caster not victim when target type is TARGET_UNIT_TARGET_ENEMY :P

**Comment by ariel-** [comment]
2nd effect is a dummy with TARGET_UNIT_CASTER

**Comment by ariel-** [comment]
> before you could see a Debuff that lasted for 60 seconds on the NPC.

Do you know how much before? I reverted back to the commit before my DR changes (f4a10571f74450daf26a5b0c5bd0f3114c231120) and still MC lasts 10 sec

**Comment by Demonid** [comment]
I was using Rev fe2a0fda4464effeb2fb655da84a0460328b1aeb before encountering this bug

**Comment by ariel-** [comment]
No luck on fe2a0fda4464effeb2fb655da84a0460328b1aeb either, so you were using an even previous version or never worked to begin with.

**Comment by ariel-** [comment]
Ah, no, spell on caster still lasts 10 sec, which constitutes another bug. After the 10 secs pass, you have the remaining 50 to control the npc.

If you don't wait those 10 secs and start moving the npc, the MC is easily broken (yet another bug)

**Comment by Demonid** [comment]
So fe2a0fda4464effeb2fb655da84a0460328b1aeb is enough to try to find what commit broke it or should i search some more?

**Comment by ariel-** [comment]
To clarify: mind control aura did always (at least as far as I could test) have a duration of only 10 secs, due to incorrectly applying DR. 

Before 2d0fb356de5b2dda06b008a875c6d4ea31eb5dfd all was fine, because the channeled interruption didn't mean that NPC had the aura removed. After that commit, the 10 sec error was made evident
