### ISSUE TITLE
[3.3.5/Ulduar] Kologarn Arms respawn without body

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19446]
**Description:** Kologarn Arms respawn without body

**Expected behaviour:** Arms respawn only if body respawn

**Steps to reproduce the problem:**

1. go crea id 32930
2. Kill kologarn
3. Back to Kologarn some hours later, arms will be respawned with kologarn dead

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 21b2042840e05ebeba365c54d47c07c13fde123f

**Comment by ccrs** [comment]
"sometime latter" what do you mean?

**Comment by sirikfoll** [comment]
That's because dead vehicles reinstall accessories, same thing occurs with XT002 Heart. Caused by: 
https://github.com/TrinityCore/TrinityCore/commit/d73ffc9e81747ef642b47f248d38144c9ead9705#diff-5278d6e24314324fd6d5f95b667cd9f7R131

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/551d0559aac663e9485b0eaffac5326536180c27
