### ISSUE TITLE
Enchanted Illidari Tabard doesn't work

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19443]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
During the quest [Dissension Amongst the Ranks...](http://www.wowhead.com/quest=10776/dissension-amongst-the-ranks) (ID 10776) the provided item, [Enchanted Illidari Tabard](http://www.wowhead.com/item=31279/enchanted-illidari-tabard) (ID 31279), does not disguise you as a Blood Elf.

![wowscrnshot_041017_235057](https://cloud.githubusercontent.com/assets/16745918/24894770/b8190ef2-1e49-11e7-8220-242c14c3f612.jpg)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e478434146fd 2017-04-09 19:18:22 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
Allowed areas:
3930 - Eclipsion Fields (Map: 530)

You must use the tabard only once your are in Eclipsion Fields.
From quest details: "Take the enchanted tabard and travel to the Eclipsion Fields, southwest of Eclipse Point. Once there, use the tabard to transform into an agent of Illidan."

**Comment by Aokromes** [comment]
http://i.imgur.com/MPeruZZ.jpg
