### ISSUE TITLE
[Proc] The Egg of Mortal Essence

### ISSUE THREAD

**Issue by Demonid** [TrinityCore/TrinityCore#19441]
http://www.wowhead.com/item=40685 should Proc on HoTs and its not doing it.

> There's a few varying opinions here in regards to Druids, so I thought I'd take one for the team and buy the thing just to get the truth. I'll just state what I found and let you decide if it's worth the Emblems or not!
> 
>     It procs on HoT ticks!
>     It procs on direct heals.
>     It will proc regardless of who the heal is on.
>     It does NOT proc on HoT ticks that were 100% overheal, but direct heal overheals can still proc it.
>     As an exception to the above, the bloom from Lifebloom cannot proc it on an overheal, despite the overheal appearing in the combat log like a direct heal (unlike HoT ticks).
>     There is a difference between the trigger on this trinket and "on spell hit/cast" trinkets/talents like Valonforth's Remembrance. For example where that trinket will proc on the initial casting of Rejuvenation, the Egg will only proc on the actual ticks.
>     As expected there is an internal cooldown, the quickest I could get two successive procs was 48sec using Lifebloom.
> 
> Update: For the life of me I can't get this to proc on Swiftmend, overheal or otherwise.

http://www.wowhead.com/item=40685/the-egg-of-mortal-essence#comments

TC rev. hash/commit: 21b2042840e05ebeba365c54d47c07c13fde123f 
TDB 62

Branch(es): 3.3.5

Btw, https://trinitycore.atlassian.net/wiki/display/tc/spell_proc is missing some vital info, how can i know the marks/flags are used for this kind of fixes?

**Comment by Keader** [comment]
wiki is not updated, you need check https://trinitycore.atlassian.net/wiki/display/tc/spell_proc and https://trinitycore.atlassian.net/wiki/display/tc/spell_proc_event to got values for all fields

**Comment by ariel-** [comment]
Updated wiki
