### ISSUE TITLE
Fumper does not summon Gigantic Bone Worm

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19451]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
The quest item, [Fumper](http://www.wowhead.com/item=31825/fumper) (ID 31825), for the quest, [The Big Bone Worm](http://www.wowhead.com/quest=10930/the-big-bone-worm) (ID 10930), does not summon any creatures within the bone wastes to the south of Auchindoun in Terokkar Forest. ~~When using the item an error appears that says "You have no target".~~

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e478434146fd 2017-04-09 19:18:22 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jerbookins** [comment]
Is 11418 a valid fix?

**Comment by Killyana** [comment]
You must use the item on a dead Decrepit Clefthoof.
Quest text: "Get out there and kill a clefthoof. Once it's dead, use the drums. Hopefully the big one will come up to feed."

**Comment by jerbookins** [comment]
Right, if I'm targeting a Clefthoof it beats the drum and still does not spawn any mobs.

**Comment by Killyana** [comment]
Dup #11418
