### ISSUE TITLE
Scouting the Sinkholes Broken Objectives

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19456]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
On the quest [Scouting the Sinkholes](http://www.wowhead.com/quest=11713/scouting-the-sinkholes) (ID 11713), using the quest item [Map of the Geyser Fields](http://www.wowhead.com/item=34920/map-of-the-geyser-fields) (ID 34920) does not complete the quest objectives.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e478434146fd 2017-04-09 19:18:22 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**
335.62

**Operating system:**
Windows 10 Client & Server

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Aokromes** [comment]
#16564
