### ISSUE TITLE
[335] [Core/Unit] wrong melee hit results

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#19455]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

units attacking other units with lower level get too often miss results

**Steps to reproduce the problem:**

1. create a level 80 char
2. attack a creature with higher level (82 for example)
(I saw it on Lady Whisp adds)
3. see the creature miss around 2/3 of its melee attacks

**Branch(es):**

3.3.5

**TC rev. hash/commit:**  10d7ae488e32b51b66e0ab3fb44feca68aaa7a8b

**Comment by ariel-** [comment]
I can't reproduce it, I don't get such amount of misses.

Specific creature ids?

**Comment by Demonid** [comment]
Well you can always miss auto-attacks on targets above your level even while having 8% hit rating, specially if you are using a dual wielding class

**Comment by ccrs** [comment]
I'll test it again, but its the creature missing its attacks, not the player

**Comment by ccrs** [comment]
confirmed again, use a new character, with no weapon skill nor defense skill, level it to 80 and face any higher level NPC

**Comment by Shauren** [comment]
"with no weapon skill" - there you have it.

**Comment by ccrs** [comment]
no no no, its the creature the one who misses, not the player

**Comment by ccrs** [comment]
after using .maxskill the npc starts to miss lot less, still does from time to time though and I dont think thats correct either: can a raid boss miss hits against a 0% defense stats player?.

best guess would be that some stats, or all, who knows; are taken from the victim instead of the attacker.

**Comment by ariel-** [comment]
> I'll test it again, but its the creature missing its attacks, not the player

I was talking about creature too

> can a raid boss miss hits against a 0% defense stats player?.

Yes, Base miss chance is 5% for equal level, the more level difference, the less chance creature has to miss (but still has some)

**Comment by ariel-** [comment]
Ah, lol, figured it out

https://github.com/TrinityCore/TrinityCore/blob/abaa9d635a6c52f78ec5eb87a5a39890645d5649/src/server/game/Entities/Unit/StatSystem.cpp#L711

We have an uncasted unsigned subtraction, which does overflow when defense is less than max.

Before e565b34f6d24411e210151d0d03e524f94cdff85, return types were both uint16, but since it's multiplying a float, the whole thing was implicity casted to float and the error went by, silent. Now the subtraction has to be done in uint32 and the fun begins
