### ISSUE TITLE
[3.3.5] The Oculus: several issues with Mage-Lord Urom

### ISSUE THREAD

**Issue by markvetwow** [TrinityCore/TrinityCore#19452]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

There will be a list with issues on this boss.

**Current behaviour:**

1. When you hit the boss in first time, he starts casting his Menagerie spell as needed, but if you interrupt that spell (I am not sure if you really can do this on retail), he stops following the script completely. It's a really old bug.
2. Even if you don't interrupt his 3 Menagerie "phases", his encounter looks really bugged. His Arcane Explosion "event". When he uses a teleport, sometimes he can bring to you back instantly and ignore a cast of Arcane Explosion. On the other hand, if he starts casting his Explosion, he falls down a little bit, then starts casting.
3. When he returns from Arcane Explosion "event" he is not following you,and stops auto attacking you.
4. If you simulate your group wipe, he is not resetting his position (if you wipe on Menagerie "phase").
5. Even if you wipe after 3 Menagerie casts, he is still targeting you even if you are in GM mode and stops following and attacking you. Only casts his spells.

And by the way. Drakes hovering in Oculus look bugged (same feature with Svala in Utgarde Pinnacle I guess it is because hovering is kind of broken) when they are moving it works very well. But if they stop, they just stand in one place and sometimes move up and down.

**Steps to reproduce the problem:**

1. Enter The Oculus.
2. Slay the two bosses **Drakos** and **Varos**.
3. Check these issues with Urom.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. d914c55c0585+ 2017-04-12 13:31:11 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.62

**Operating system:** Win 8.1 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Krudor** [comment]
Script needs to be rewritten, there's too much that isn't doing what it's supposed to.

**Comment by D0d0** [comment]
I am rewriting currently this script and he sometimes returns to the player and sometimes fall down. Do you have any idea why he is doing this? Here is part in UpdateAi (all other parts have condition `isNotInPhase(PHASE_PORTED)` so they are not executed). Help will be appreciated!
```c++
case EVENT_TELEPORT:
    events.AddPhase(PHASE_PORTED);
    me->SetCanFly(true);
    me->SetDisableGravity(true);
    me->AddUnitMovementFlag(MOVEMENTFLAG_CAN_FLY); // with out it the npc will fall down while is casting
    me->SetWalk(false);
    me->InterruptNonMeleeSpells(false);
    me->GetMotionMaster()->MoveIdle();
    DoCast(SPELL_TELEPORT);
    events.RescheduleEvent(EVENT_EXPLOSION, 1s);
    break;
case EVENT_EXPLOSION:
    Talk(EMOTE_ARCANE_EXPLOSION);
    Talk(SAY_ARCANE_EXPLOSION);
    DoCastAOE(SPELL_EMPOWERED_ARCANE_EXPLOSION);
    events.RescheduleEvent(EVENT_GO_BACK, 8s);
    return;
```c++

and the end 

```c++
if (me->HasUnitState(UNIT_STATE_CASTING) || events.IsInPhase(PHASE_PORTED))
    return;

DoMeleeAttackIfReady();
```

**Comment by Krudor** [comment]
I assume you'd want to set reaction state to passive and drop current target, can't remember 100% how this phase works.

Should be able to find multiple examples on bosses with similar phases.
