### ISSUE TITLE
[3.3.5] DB/Loot: Halls of Reflection final loot

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19462]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

At the end of the event with Arthas in HoR the ship arrives but does so without NPC or trunk of loot so it becomes impossible to loot even though it gives the achievement correctly. I remember this worked on a previous commit.

**Current behaviour:**

There is no loot for final event. This is only for Alliance. For the Horde, loot works perfectly.

**Expected behaviour:**

The ship should have NPCs and the trunk to loot it.

**Steps to reproduce the problem:**

1. Go to HoR
2. Do the final event with Jaina and Arthas.
3. The ships arrive but no npc and no loot.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4d7e7a97b329dc8ee4354f7be26c5e5efbaeba6b

**TDB version:**  3.3.5 62 +updates

**Operating system:** Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by amaroc** [comment]
Here are my comment related to latest revision and same problem: https://github.com/TrinityCore/TrinityCore/issues/18943#issuecomment-294344729

**Comment by HannibalRoG** [comment]
In my server

AllowTwoSide.Interaction.Calendar = 0
AllowTwoSide.Interaction.Group = 0
AllowTwoSide.Interaction.Guild = 0
AllowTwoSide.Trade = 0
TalentsInspecting = 0

**Comment by sirikfoll** [comment]
I think it may be a generic issue with Transports, I've been experiencing an issue with NPCs disappearing on Icecrown Airships, but not only visually, ships get completely empty, only returning after a server restart, and so far I don't know how to reproduce.
rev. 45168f9612db

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/a5df77a9d6f3e48f2c4e8a61d60e3b5f2f0c326e
