### ISSUE TITLE
[3.3.5][CRASH][Player Spell] Druid Bear Form Ability "Enrage"

### ISSUE THREAD

**Issue by kvipka** [TrinityCore/TrinityCore#19464]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Ability : Enrage:**

If use spell Enrage in bear we will take a crash.

Debug showed undeclared exception in spell_druid : 
`// 5229 - Enrage
class spell_dru_enrage : public SpellScriptLoader
{
    public:
        spell_dru_enrage() : SpellScriptLoader("spell_dru_enrage") { }`
in 
`void RecalculateBaseArmor()
            {
                Unit::AuraEffectList const& auras = GetTarget()->GetAuraEffectsByType(SPELL_AURA_MOD_BASE_RESISTANCE_PCT);
                for (Unit::AuraEffectList::const_iterator i = auras.begin(); i != auras.end(); ++i)
                {
                    SpellInfo const* spellInfo = (*i)->GetSpellInfo();
                    // Dire- / Bear Form (Passive)
                    if (spellInfo->SpellFamilyName == SPELLFAMILY_DRUID && spellInfo->SpellFamilyFlags.HasFlag(0x0, 0x0, 0x2))
                        (*i)->RecalculateAmount();
                }
            }`

**Expected behaviour:**

Just cast spell instead.

**Steps to reproduce the problem:**

1. Log in game by druid
2. .learn all my class
3. Cast bear form
4. Cast Enrage

**Branch(es):**

3.3.5

**TC rev. 2a04599ed8f471e584b3e3f72b210a67a4f1ab1c:** 

**TDB version:** TDB_full_world_335.62_2016_10_17

**Operating system:** Win64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ccrs** [comment]
post a full crashlog please

**Comment by kvipka** [comment]
hmm, strange.
 i have this trouble only in win64 and only in debug mode. In release hasn't. 
about crash in debug - after crash i have only invite to inspect undeclared exception, without any crashlogs, but in VS solution : 
http://i.imgur.com/eEF7VAJ.png
