### ISSUE TITLE
[7.1.5] mapextractor fails

### ISSUE THREAD

**Issue by valcriss** [TrinityCore/TrinityCore#19470]
**Description:**
I am making a fresh install from today's pull on master branch.
Everything was going well until the time of using mapextractor.
It ends extrating nothing after a bunch of errors.

Here is a log : https://gist.github.com/valcriss/32a2bdbcb7fe9fe3d1640f096e19712f

**Branch(es):**
master

**TC rev. hash/commit:** 

TrinityCore rev. a39cec29a375 2017-04-17 17:07:36 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)

**Operating system:** Ubuntu 16.04

**Comment by Aokromes** [comment]
7.1.5 is no longer supported.

**Comment by valcriss** [comment]
Ho ok my bad. sorry for that
