### ISSUE TITLE
Focus Magic treated like a debuff now 

### ISSUE THREAD

**Issue by mastermind007** [TrinityCore/TrinityCore#19472]
Focus Magic treated like a debuff.

At some point after March 23rd, 2017 the Focus Magic buff is acking like a debuff. The buff icon shows where debuffs topically appear.

Updated on March 23rd 2017 and if was functioning. Recompiled from current sourse as of April 14th (TrinityCore rev. 4a40b8ed4358 2017-04-14 16:53:59 -0300 (3.3.5 branch) (Win64, Release, Static) and the buff changed behavior.

Not sure if it has to do with this track number that addresses the same spell:
[https://github.com/TrinityCore/TrinityCore/issues/14779]

**Steps to reproduce the problem:**

Simply cast the buff on a friendly party member. It will show as a debuff and the player cannot remove it just like a debuff.

Branch 3.3.5, master not sure about other branches

TrinityCore rev. 4a40b8ed4358 2017-04-14 16:53:59 -0300 (3.3.5 branch) (Win64, Release, Static

TDB 335.62 

Windows 10 64bit

**Comment by Demonid** [comment]
The same happens with http://www.wowhead.com/spell=57345 and a lot of other spells

**Comment by ariel-** [comment]
It's 1ca8434b365687dbd12ca232a615d126234eba5e, apparently causes some false positives

**Comment by minkokomaung** [comment]
Divine Intervention also treated like a debuff and can't cancel by right click.

**Comment by Jildor** [comment]
>It's 1ca8434, apparently causes some false positives

Yep, by example:
`ID - 54646 Focus Magic`
Has:
`AttributesEx2: 0x00000008 (SPELL_ATTR2_UNK3)`

I think 1ca8434 must be reverted
