### ISSUE TITLE
[7.2] cant loot mobs

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#19478]
**Description:**
mobs cant looting after killing

**Current behaviour:**
mobs cant looting after killing
tested on 100% drop mobs
!but GO looted normal!

**Branch(es):**
7.2
**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/15b1aaff4189df291fc28e3607ed2b0e4d297341

**Comment by uroborusLogos** [comment]
all creatures no loot.
All world maps.

**Comment by uroborusLogos** [comment]
Unable to select a creature after killing it
Unable to Cutting a Creature After Killing (It Cutting  skins)

**Comment by tkrokli** [comment]
@uroborusLogos : When confirming an issue (or part of the issue), please link your own TC rev. hash for reference, so we can track your feedback.

**Comment by HannibalRoG** [comment]
I can confirm that bug in
f7b0f4c9c6c34ca43190e24229b4354d7a02f012
