### ISSUE TITLE
DB/Quests: High Commander Halford Wyrmbane (12174)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19489]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** High Commander Halford Wyrmbane (quest 12174)

**Current behaviour:**
When you pick up the quest High Commander Halford Wyrmbane,
 [Palena Silvercloud](http://www.wowhead.com/npc=26881/palena-silvercloud) does not offer you the gossip text "I need to get to Wintergarde Keep fast!".

- http://www.wowhead.com/quest=12174/high-commander-halford-wyrmbane
- http://www.wowhead.com/npc=26881/palena-silvercloud

**Expected behaviour:**
The quest works properly when accepted by [Greer Orehammer](http://www.wowhead.com/npc=23859/greer-orehammer):
- http://www.wowhead.com/quest=12298/high-commander-halford-wyrmbane
- http://www.wowhead.com/npc=23859/greer-orehammer

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 3028be49296c 2017-04-20 15:44:21 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.63

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
We will have to check both `gossip_menu_option` and `conditions` for this case and compare with the working gossip.

**Comment by Killyana** [comment]
There's no gossip for this npc, the spell http://www.wowhead.com/spell=48013/hippogryph-taxi-to-wintergarde  is casted when the player take the quest, it works like on retail.

**Comment by jerbookins** [comment]
There is no spell cast on me. Doesn't work for me.

**Comment by Killyana** [comment]
Tested on https://github.com/TrinityCore/TrinityCore/commit/224399958d680e281192366111fc938eddad6ef6  without any problem

**Comment by jerbookins** [comment]
Well. It doesn't work. So. I don't know what to tell you.

**Comment by jerbookins** [comment]
I've already quested beyond this so I'm going to try it again on another character in the near future and I will provide video evidence.
