### ISSUE TITLE
[3.3.5] Guardians put target in combat before reaching target

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19485]
**Description:** If you send a Guardian to attack your target, it will put the target in combat even if your Guardian is out of range.
E.g.  Frost Mage, Summon Water Elemental (31687)

When you press attack button (CTRL+1), the target will enter combat before the Water Elemental reaches target.

**Expected behaviour:** Target should enter combat when the Guardian reaches target (like when using pets).

PS: It works for pets, but does not work for "temp Pets/Guardians"

**Steps to reproduce the problem:**

1. Cast spell 31687 (Summon Water Elemental)
2. Send water elemental to attack some player out of range
3. Player enters combat state before water elemental reaches him.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f42ff8c6ba0609c2f774440dd30981356c1ffd63

**Comment by ariel-** [comment]
https://github.com/TrinityCore/TrinityCore/commit/69fd6245dc41dca658cadb4e99c1ee6593fe000b

**Comment by ccrs** [comment]
actually no

**Comment by ariel-** [comment]
> Closes #19768, #19485 and #10921.

Based on commit msg xd

**Comment by Treeston** [comment]
Was my mistake, we found out it breaks in some niche situations still. #19816 will address once we sort out bugs with aggro behavior on that one.

**Comment by jackpoz** [comment]
what's the status of this PR and its relation to the other referenced PR ?

**Comment by ccrs** [comment]
this is not a PR xd

**Comment by tkrokli** [comment]
(been there myself, made that mistake not too long ago :-P )

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/a891eb364e941a5146fba4af16e1ecf65cdd9239
