### ISSUE TITLE
[master] - Auction House

### ISSUE THREAD

**Issue by Zydrax** [TrinityCore/TrinityCore#19481]
**Description:**  Auction House can not be used to place auctions

**Current behaviour:** You can't create an auction in any Auction House.

**Expected behaviour:**
You should be able to create auction in any auction house and other players should be able to view and buy them.

**Steps to reproduce the problem:**

1. Speak with any auctioneer NPC
2. Press the 'Auctions' tab
3. Drag any sellable item to the Auction item slot
4. Press the 'Create Auction' button
5. Notice that the auction is not created.

**Branch(es):** master

**TC rev. hash/commit:** 15b1aaff4189df291fc28e3607ed2b0e4d297341

**TDB version:** 720.00 + updates

**Operating system:** Windows 10 64-bits

**Comment by Warhaxe** [comment]
I'm a little flustered about this issue too. I've been everywhere looking for a solution to the AH fix. 
Every online search leads to Ahbot. 
I have Ahbot working not a problem. 
I'm looking for a solution to get players items Posted after clicking (Create Auction). 
Nothing seems to work. 
I've been up and down the sql table changing and rechanging "BIGINT, INT, TINYINT," ect. 
Is there any way to get this silly operation to work right? 
Any help would be super appreciated... 
I need to stop going crazy over something that is probly so simple.

**Comment by gmillerd** [comment]
Logger.sql.* and Logger.auctionHouse results say what when you post an item?

Are the items actually removed from inventory? Are they in the database?

**Comment by Aokromes** [comment]
maybe related to https://github.com/TrinityCore/TrinityCore/issues/19478 ?

**Comment by Zydrax** [comment]
Any solution ?

**Comment by Zydrax** [comment]
any news?

**Comment by tkrokli** [comment]
No. We don't know when this will be fixed.

**Comment by Zydrax** [comment]
Thank you @Shauren  :)
