### ISSUE TITLE
SMSG_PLAY_SPELL_VISUAL, SMSG_PLAY_ORPHAN_SPELL_VISUAL and SMSG_PLAY_SPELL_VISUAL_KIT

### ISSUE THREAD

**Issue by Ulduar2** [TrinityCore/TrinityCore#19486]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
https://github.com/TrinityCore/TrinityCore/issues/17950#issuecomment-296251465

**Current behaviour:**
support for SMSG_PLAY_ORPHAN_SPELL_VISUAL and SMSG_PLAY_SPELL_VISUAL is missing in Unit.cpp

**Expected behaviour:**
Need add method for this opcodes, because used in something scripts.
Soul Vessel for Soulbinder Nyami (SMSG_PLAY_ORPHAN_SPELL_VISUAL ), Quake (SMSG_PLAY_SPELL_VISUAL ) for Pol and Phemos in Highmaul and over.

Kargath should used SMSG_PLAY_SPELL_VISUAL_KIT were (Kargath Chain Hurl with duration. 
On current state duration = 0.

**Steps to reproduce the problem:**

1. CHANGEME Step 1
2. Step 2
3. Step 3

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/298d86d9f725241c8a628c554bfef671e200e052

**TDB version:**  TDB 720.00

**Operating system:** CHANGEME OS

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

``` CPP
SMSG_PLAY_SPELL_VISUAL_KIT
Need add support for duration. On current state send packet with duration = 0.

Addon:

void Unit::SendPlaySpellVisualKit(uint32 id, uint32 type, uint32 duration)
{
    WorldPackets::Spells::PlaySpellVisualKit playSpellVisualKit;
    playSpellVisualKit.Unit = GetGUID();
    playSpellVisualKit.KitRecID = id;        ///< SpellVisualKit.dbc index
    playSpellVisualKit.KitType = type;
    playSpellVisualKit.Duration = duration;
    SendMessageToSet(playSpellVisualKit.Write(), true);

void SendPlaySpellVisualKit(uint32 id, uint32 type, uint32 duration);
}
SMSG_PLAY_SPELL_VISUAL

void Unit::SendPlaySpellVisual(Unit* victim, uint32 id);
{
    WorldPackets::Spells::PlaySpellVisual playSpellVisual;
    playSpellVisual.Source = GetGUID();
    playSpellVisual.Target = victim->GetGUID();
    playSpellVisual.TargetPosition = 0.0f; // slices
    playSpellVisual.SpellVisualID = id;
    playSpellVisual.MissReason = 0;
    playSpellVisual.ReflectStatus = 0;
    playSpellVisual.Orientation = 0.0f;
    playSpellVisual.SpeedAsTime = true;
    SendMessageToSet(playSpellVisual.Write(), true);

void SendPlaySpellVisual(Unit* victim, uint32 id);
}
SMSG_PLAY_ORPHAN_SPELL_VISUAL
NYI.
```
@Shauren -  this is right?

**Comment by tkrokli** [comment]
Closed by https://github.com/TrinityCore/TrinityCore/commit/7b4bdc6b8f5f9adc677165583c700774d0859869 .

**Comment by Ulduar2** [comment]
@tkrokli 
To soon... your close issue to soon.
SMSG_PLAY_SPELL_VISUAL
and
SMSG_PLAY_ORPHAN_SPELL_VISUAL
Not implemented.
Need developer help.
Please reopen.

Visual Kit - this is 1/3 issue part.

**Comment by tkrokli** [comment]
Well, you wrote in #19487 that the PR should close this issue, but OK.

**Comment by Ulduar2** [comment]
Issue adressed -yes.
But pull only for VisualKit, because easy change.
In OrphanSpellVisual and PlaySpellVisual i don't know how should be implemented wright.
Need Trinity Core developer help.
Thanks for reopen.

**Comment by Ulduar2** [comment]
Any news?

**Comment by ariel-** [comment]
> To soon... your close issue to soon.

Nice Ragnaros reference 😆

**Comment by Ulduar2** [comment]
``` QUOTE
Nice Ragnaros reference :laughing:
```
By Firelands be purge!
