### ISSUE TITLE
CMake and MariaDB

### ISSUE THREAD

**Issue by Albirew** [TrinityCore/TrinityCore#19493]
**Description:**
CMake is not working with latest MariaDB.
I know this is not really a TrinityCore issue but I dunno where to ask for help on this matter.

**Current behaviour:**
CMake Error at cmake/macros/FindMySQL.cmake:282 (message):
  Could not find MySQL headers! Please install the development libraries and
  headers
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)

**Expected behaviour:**
CMake to continue configuring.

**Steps to reproduce the problem:**
1. install or upgrade MariaDB using latest stable release from https://downloads.mariadb.org/mariadb/repositories/#mirror=cnrs&distro=Debian&distro_release=jessie--jessie&version=10.1

2. preparing to rebuild to avoid TCE00011 since we updated mysql:
```bash
cd $WOW/TrinityCore/
git pull origin 3.3.5
cd build/
make clean
rm -rf *
cmake ../ -DCMAKE_INSTALL_PREFIX=$WOW/server -DCONF_DIR=$WOW/server/etc -DTOOLS=1 -DSCRIPTS="dynamic" -DWITH_WARNINGS=1
```

**Branch(es):**
3.3.5 but might be with both

**TC rev. hash/commit:** 
TrinityCore rev. 3a65c706572e 2017-02-07 17:34:42 -0300 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version:**  
TDB 335.62

**Operating system:** 
Debian jessie x86_64

**Comment by DDuarte** [comment]
you can force -DMYSQL_INCLYDE_DIR and -DMYSQL_LIBRARY to point to the place where headers and library files. Make sure you installed the devel or dev packages of MariaDB.

**Comment by Albirew** [comment]
Thanks!

For posterity, if one bump into the same problem, one does have to:
1. `apt install libmariadbclient-dev libmariadbd-dev`
2. add on one's cmake command: `-DMYSQL_LIBRARY=/usr/lib/libmysqlclient.so.18.0.0 -DMYSQL_INCLUDE_DIR=/usr/include/mysql`
(please double-check command and paths as they may change depending on your distribution.)


As a side note, I believe it should be added in linux core install wiki page for people having same issue.

**Comment by ariel-** [comment]
There's already a compatibility package providing symlinks to mariadb installation, which makes it compatible with mysql, without needing to modify CMake parameters

**Comment by Aokromes** [comment]
libmariadb-client-lgpl-dev-compat ?

**Comment by ChazyTheBest** [comment]
I always install the latest version of everything (Arch Linux) and never had a problem...

**Comment by emperorAd** [comment]
Всем привет народ !!! Помогите мне я пытаюсь собрать сервер wow а при конфигурировании исходников вылазеет такая проблема

**Comment by emperorAd** [comment]
CMake Error at cmake/macros/FindMySQL.cmake:249 (message):
  Could not find the MySQL libraries! Please install the development
  libraries and headers
Call Stack (most recent call first):
  CMakeLists.txt:76 (find_package)

**Comment by emperorAd** [comment]
Что мне делать ???

**Comment by acidmanifesto** [comment]
> Что мне делать ???
^^What should i do??? <<Translation

Следуйте инструкциям и установите необходимые зависимости.
Follow the guide and install the required dependiences.

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977291/macOS+Requirements
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977296/Windows+Requirements

**Comment by emperorAd** [comment]
![13](https://user-images.githubusercontent.com/84341814/118760725-f96b9e80-b87b-11eb-8b76-c59b5e098727.png)

**Comment by emperorAd** [comment]
Где взять эти библиотеки ???

**Comment by Jinnaix** [comment]
English please.

**Comment by emperorAd** [comment]
Where can I get these libraries?

**Comment by Jinnaix** [comment]
Its listed under the link that was provided to you.
Under point 3, MySQL Server Community Edition
The Blue Text is also a link to the download page.
