### ISSUE TITLE
DB/Quests: A Righteous Sermon (12321)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19494]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:** A Righteous Sermon (quest 12321)

**Current behaviour:**
Inquisitor Hallard paces in front of the jail cell containing Mayor Godfrey. When you accept the quest he stops pacing, then walks to the left of the cell and doesn't stop, he just keeps going through the walls and disappears.

**Links**
- http://www.wowhead.com/quest=12321/a-righteous-sermon
- http://www.wowhead.com/npc=27316/inquisitor-hallard

**Video**
- https://gfycat.com/UncomfortableIncomparableBallpython

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 3028be49296c 2017-04-20 15:44:21 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.63

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by malcrom** [comment]
I had this working in Sai years ago.

**Comment by Killyana** [comment]
Move to pos must use target 8 not 1 with coords.

**Comment by dikkedeur** [comment]
i can confirm this 100%, just did it, and he walks straight through the walls

**Comment by tkrokli** [comment]
@dikkedeur : When confirming issues, always add your current TC rev. hash in your comment for reference (we use it to keep track of the issue). Without TC core rev. hash, the confirm comment is close to useless.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e263654c77fbbe94f3af2d462aaf203c9c4f6ec8
