### ISSUE TITLE
[master] Hunter Spell Auto-Shot

### ISSUE THREAD

**Issue by MartGon** [TrinityCore/TrinityCore#19496]
**Description:**

Spell bug that happens when auto-shot can't hit it's target.

**Current behaviour:**

The spell works correctly until you cannot hit the target for whatever reason, looking back or when you cannot see the target. After that, the spells gets stuck, an error message appears on the client ("you're in the wrong zone") and it keeps flickering on the action bar, but any shot won't be launch. Then you'll have to reactivate the spell or target something else to fix it.

**Expected behaviour:**

Auto-shot should keep launching ranged attacks if the target is now visible and in front of you, even if you couldn't hit it before.

**Steps to reproduce the problem:**

1. Create a hunter.
2. Right-click a target dummy to start auto-shot.
3. Look back like 3 seconds, error message appears on the client
4. Look again to the dummy.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 5233caf09206 2017-04-20 19:53:34 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver)

**TDB version:**  7.2.0

**Operating system:** Windows 7 Professional x64

**Comment by Killyana** [comment]
This issue is fixed on 3.3.5: https://github.com/TrinityCore/TrinityCore/pull/14889

**Comment by MartGon** [comment]
Yep, that correctly fixes the issue. I knew that this spell worked properly on 3.3.5, I thought it was a problem  of the new core, I didn't know it wasn't implemented. 
I'm sorry I didn't found this fix myself. Thx for your help!

**Comment by ariel-** [comment]
Don't close issue until it's ported to master

**Comment by aquadeus** [comment]
ths was ported to master time ago
