### ISSUE TITLE
[Crash] - IsInsideObject

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19514]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Crashlog: https://gist.github.com/Jildor/801cf06b21bee0d72b6fcfede6637d76
I find in the crashlog the spell ID - 59516 Splash
(Boss Ichoron)

I think the knockback effect in certain action causes the crash

**Steps to reproduce the problem:**

I do not know how reproduce it

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c296d255e25a2d0eb7155f64eea32cc36fed280a

**TDB version:**  TDB335.63

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ariel-** [comment]
You have an infinite loop in your code, please report the crash with a clean source.

```
#1758 0x000000000152953c in UnitAI::DoCastAOE (this=<optimized out>, spellId=<optimized out>, triggered=<optimized out>) at /home/trinity/Trinitycore/src/server/game/AI/CoreAI/UnitAI.cpp:208
#1759 0x0000000001a3c845 in Unit::DealDamage (this=0x6a73a9abe000, victim=0x6a73a9abe000, damage=963, cleanDamage=0x6a73c438dd40, damagetype=SPELL_DIRECT_DAMAGE, damageSchoolMask=SPELL_SCHOOL_MASK_FROST, spellProto=0x6a741dd72900, durabilityLoss=true) at /home/trinity/Trinitycore/src/server/game/Entities/Unit/Unit.cpp:685
```

There is no DoCastAOE call on Unit::DealDamage

**Comment by Jildor** [comment]
@ariel- 
There is nothing modified in that part of the core

The DoCastAOE is launched here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/VioletHold/boss_ichoron.cpp#L273

I think is problem with vmaps in water with the knockback in this instance when ichoron launches DoCastAOE(SPELL_SPLASH); ???

**Comment by jackpoz** [comment]
should this be reopened ?

**Comment by Killyana** [comment]
Could be reproduced in a clean core.

**Comment by ariel-** [comment]
> missInfo = SPELL_MISS_REFLECT

This is the key to reproduce the crash, normally the spell won't hit self but if it's reflected, it does
