### ISSUE TITLE
[master] Death Knight starting zone

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#19519]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Phasing isn't working correctly in the death knight starting zone.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Create a new DK

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/3b6fb1c4313881da84f23e1607ef5f700814afe1

**TDB version:**  720.00 + updates

**Operating system:** Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
Your description could do with some improvement, hard to know what the issue looks like without more info, like NPC names/IDs/links and some text about what you see vs what is expected. Leaving out parts of the template is usually not a good thing. Maybe you could add a screenshot to show what you're referring to? (Sure, we know that the phasing is not good enough in master, but issue pages can always do better with some more relevant info.)

**Comment by ArcaneFox** [comment]
Sorry but I can't describe this with words, so I made some screenshots.

![1](https://cloud.githubusercontent.com/assets/25306170/25533311/89204a44-2c30-11e7-9b6a-4b2305b87a03.jpg)
![2](https://cloud.githubusercontent.com/assets/25306170/25533310/8914f3ba-2c30-11e7-9a2f-6d48ceb554ce.jpg)

**Comment by tkrokli** [comment]
Oh. Right. 😆 Everything is happening at once. There is no divide between the phases, so all phased creatures show up in the default phase. :-p

**Comment by ccrs** [comment]
.gm off works like a charm

**Comment by tkrokli** [comment]
Aha.... should have thought about that scenario.

**Comment by Aokromes** [comment]
better, try a non-gm account.

**Comment by ArcaneFox** [comment]
I tried with a non gm account but there are no changes.

**Comment by Ulduar2** [comment]
``` QUOTE
better, try a non-gm account.
```
Not have sense, if table creature have PhaseId = 0, non-gm account not help.

**Comment by ArcaneFox** [comment]
> http://www.wowhead.com/npc=29110/the-lich-king

```sql
guid,id,map,zoneId,areaId,spawnMask,PhaseId,PhaseGroup,modelid,equipment_id,position_x,position_y,position_z,orientation,spawntimesecs,spawndist,currentwaypoint,curhealth,curmana,MovementType,npcflag,unit_flags,dynamicflags,ScriptName,VerifiedBuild
130896,29110,609,0,0,1,0,0,0,0,2310.27,-5742.21,161.207,3.85718,360,0,0,27890000,0,0,0,0,0,,0
```

**Comment by Ulduar2** [comment]
PhaseId and PhaseGroup Empty.
Death Knight have phase spells in spell_area.
Also in Cataclysm phasing system changed. On Pandaria, Draenor and Legion phase system extended.
Need add entry in creature table for working. Black job.

**Comment by MrSmite** [comment]
> better, try a non-gm account.

But honestly, a non-gm account with *gm off* should behave just like a regular account, otherwise a GM cannot ever see what a player sees without account hopping.

**Comment by Palabola** [comment]
Old PhaseValues(Pre-WoD) can be converted to PhaseGroups.

Here is my solution in PHP, not every Bitmasked Phase got equal PhaseGroup those need to be solved.

`<?php

try {

  $host = "localhost";  
  $dbname = "";
  $user = "";
  $pass = "";
    
  # MySQL with PDO_MYSQL
  $LOC_DB = new PDO("mysql:host=$host;dbname=$dbname", $user, $pass);
 

}
catch(PDOException $e) {
    echo $e->getMessage();
}

function identical_values( $arrayA , $arrayB ) {

    sort( $arrayA );
    sort( $arrayB );

    return $arrayA == $arrayB;
} 


 $phase = $_GET['phase'];
/*
|         1 |     169 |
|         2 |     170 |
|         4 |     171 |
|         8 |     172 |
|        16 |     173 |
|        32 |     174 |
|        64 |     175 |
|       128 |     176 |
|       256 |     177 |
|       512 |     178 |
|       1024 |     179 |
|       2048 |     180 |
|       4096 |     181 |
|       8192 |     182 |
|       16384 |     183 |
|       32768 |     184 |
 */
 
       for ($x = 0; $x <= 32; $x++) {

        $phase_mask[$x]['real_id'] = 169+$x;
        $phase_mask[$x]['phase_id'] = pow(2,$x);

        }
 
        
      //  var_dump($phase_mask);
 
        for ($x = 0; $x <= 32; $x++) {

            if($phase & $phase_mask[$x]['phase_id'])
                {
                    $phase_group_array[$x] = $phase_mask[$x]['real_id'];
                }

        }
        
        
    $arraysize = sizeof($phase_group_array);
    

    if($arraysize==1)
    {
     var_dump($phase_group_array);
     exit;   
    }

        
    for ($x = 367; $x <= 890; $x++) {    

    $res2 = $LOC_DB->prepare("SELECT `phase` FROM `dbc_phasexphasegroup` WHERE `group` = :group"); 
    $res2->bindValue(':group', $x, PDO::PARAM_INT);
    $res2->execute();         
    
    if ($res2->rowCount() > 0) //Van Result
    {
        $j = 0;
        unset($possible_group_array);
        
        while ($result_row = $res2->fetch())
        {  
            $possible_group_array[$j] = $result_row['phase'];
            $j++;
        }
       
      if(identical_values($possible_group_array,$phase_group_array))
      {
        echo "Phase Group: ".$x." "; 
        break;  
      }

    }

  }`
