### ISSUE TITLE
[Spell/Proc] Fingers of Frost

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19517]
**Bug1:**

**Description:** Spells like Ice Armor and Frost Armor is not proccing  Fingers of Frost

**Expected behaviour:** Ice Armor and Frost Armor should proc Fingers of Frost

**Steps to reproduce the problem:**

1. Use frost or ice armor
2. When you got melee damages, proc of Fingers of Frost never happen

PS: Fingers of Frost has proc flag: Successful damage from harmful magic spell cast (0x00010000)
I know that Ice armor and Frost armor is not damage... but is blizzlike behavior.

You can see here: https://youtu.be/fH7iomqxXfo?t=3m4s
and here: https://youtu.be/fH7iomqxXfo?t=5m48s

in both cases, spell proc when mage is not casting nothing... just getting damage from warrior.

**Bug2:**

**Description:** Cone of Cold is consuming 1 stack of Fingers of Frost when proc (when fingers of frost proc), event if Cone of Cold hit only 1 target.

**Expected behaviour:** When Fingers of Frost proc, should remain with 2 stack until next frost cast

**Steps to reproduce the problem:**

1. Cast Cone of Cold in a target until Fingers of Frost proc
2. When Fingers of Frost proc, only 1 stack remain

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3ea46e57afe26778704647084cc6fa55a798e510

**Comment by Keader** [comment]
About bug 1: http://wowwiki.wikia.com/wiki/Frostbite_(mage_talent)

> It will also always proc along with Fingers of Frost if both are fully talented.

**Comment by Laintime** [comment]
bug 1 confirm 
video https://youtu.be/X_vZaM5BbnY

**Comment by Jildor** [comment]
The first bug the problem is Fingers of Frost needs proc with triggered spells

The second bug can be fixed if change the SpellPhaseMask to PHASE_CAST instead PHASE_HIT (I don't see any problem with this change and Cone of Cold proc works fine)

Then, the fix will be:
```sql
UPDATE `spell_proc` SET `SpellPhaseMask`=1,`AttributesMask`=`AttributesMask`|0x0000002 WHERE `SpellId` IN (44543,44545);
```

**Comment by Rushor** [comment]
ehh @Jildor are you shure that it should proc on cast and not on hit? 

quote from a player:

> More specificly = having 1 fingers of frost proc while casting "frostbolt" should give you the chance to also cast "deep freeze" while your frostbolt is flying towards the target. Or frostbolt+icelance.

**Comment by Jildor** [comment]
https://www.youtube.com/watch?v=4X-GB9GB7Ic&t=8s  <-- 0:46
