### ISSUE TITLE
Charles Worth [28699] - conditions for gossip options switched

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19516]
**Description:**

The npc offers to teach [wispcloak](http://www.wowhead.com/spell=56016/wispcloak) and [deathchill cloak](http://www.wowhead.com/spell=56017/deathchill-cloak). The conditions for showing these options are switched.

**Current behaviour:**

If you have [Loremaster of Northrend](http://www.wowhead.com/achievement=41/loremaster-of-northrend) (including 1360, not on wowhead anymore), you can learn wispcloak.
If you have [Northrend Dungeonmaster](http://www.wowhead.com/achievement=1288/northrend-dungeonmaster), you can learn deathchill cloak.

**Expected behaviour:**

Vice versa. Read the gossip options.

**Steps to reproduce the problem:**

1. Get tailoring.
2. Get one of the achievements.
3. Go to the npc and talk to him.

Or simply look into the database and analyse the entries:
```SQL
SELECT * FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=10118
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3ea46e57afe26778704647084cc6fa55a798e510

**TDB version:**  according to hash

**Operating system:** Windows 10

**Fix**
This should fix the issue:
```SQL
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 15 AND `SourceGroup`= 10118 AND `SourceEntry` IN (3, 5);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15, 10118, 3, 0, 0,  7, 0,   197, 420,0,0,0,0,'', 'Only show gossip menu_id 10118 option id 3 if player has learned Tailoring skill level 420 (Alliance)'),
(15, 10118, 3, 0, 0, 17, 0,  1288,   0,0,0,0,0,'', "Only show gossip menu_id 10118 option id 3 if player has got the achievement 'Northrend Dungeonmaster'"),
(15, 10118, 3, 0, 0, 25, 0, 56016,   0,0,1,0,0,'', "Only show gossip menu_id 10118 option id 3 if player has NOT learned the spell 'Wispcloak' (56016)"),
(15, 10118, 5, 0, 0,  7, 0,   197, 420,0,0,0,0,'', 'Only show gossip menu_id 10118 option id 5 if player has learned Tailoring skill level 420'),
(15, 10118, 5, 0, 0, 17, 0,    41,   0,0,0,0,0,'', "Only show gossip menu_id 10118 option id 5 if player has got the achievement 'Loremaster of Northrend' (Alliance)"),
(15, 10118, 5, 0, 0, 25, 0, 56017,   0,0,1,0,0,'', "Only show gossip menu_id 10118 option id 5 if player has NOT learned the spell 'Deathchill Cloak' (56017)"),
(15, 10118, 5, 0, 1,  7, 0,   197, 420,0,0,0,0,'', 'Only show gossip menu_id 10118 option id 5 if player has learned Tailoring skill level 420 (Horde)'),
(15, 10118, 5, 0, 1, 17, 0,  1360,   0,0,0,0,0,'', "Only show gossip menu_id 10118 option id 5 if player has got the achievement 'Loremaster of Northrend' (Horde)");
```

**Comment by tkrokli** [comment]
I have edited the SQL above, but only changed value alignment & comment content for readability (cosmetic changes).

**Comment by dr-j** [comment]
Oh I know I was responsible for original fix for this teaching the recipes but seems I have been sitting on the following for the past 4 years p:

~~~sql
UPDATE `conditions` SET `SourceEntry`=3 WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=10118 AND `SourceEntry`=5 AND `ConditionTypeOrReference`=17 and `ConditionValue1`=1288;
UPDATE `conditions` SET `SourceEntry`=5 WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=10118 AND `SourceEntry`=3 AND `ConditionTypeOrReference`=17 and `ConditionValue1` IN(1360,41);

**Comment by tkrokli** [comment]
@dr-j : does your SQL replace TecDian's SQL, or is it in addition to the one he posted?

**Comment by TecDian** [comment]
He switches 3 and 5 for the achievements. I wrote the conditions new. Result the same.
