### ISSUE TITLE
Apothecary trio (Love is in the air) - missing mobs

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19520]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

The "Love is in the air" boss fight is missing a line.

**Current behaviour:**

When the fight starts, they summon the adds silently.

**Expected behaviour:**

They should call "Apothecaries! Give your life for the Crown!" This line was removed in patch 4.0.3a. It has to be there in 3.3.5. Therefore it is in broadcast_text.

**Steps to reproduce the problem:**

1. Start the event.
2. Use the dungeon browser to enter the  instance.
3. Just fight it through and read the lines.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 3ea46e57afe26778704647084cc6fa55a798e510

**TDB version:** according to hash

**Operating system:** Windows 10

**Fix**
The SQL part, just add the line:
```SQL
DELETE FROM `creature_text` WHERE `entry`=36296 AND `groupid`=6;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(36296,6,0,"Apothecaries! Give your life for the Crown!",12,0,100,0,0,0,38594,3,'SAY_SUMMON_ADDS');
```
The C++ part in src\server\scripts\EasternKingdoms\ShadowfangKeep\boss_apothecary_hummel.cpp:
Add line to `enum ApothecarySays`:
```c++
    SAY_SUMMON_ADDS  = 6,
```
Add line `Talk(SAY_SUMMON_ADDS);`:
```c++
                        case EVENT_START_FIGHT:
                        {
                            me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                            me->SetInCombatWithZone();
                            events.ScheduleEvent(EVENT_CALL_BAXTER, Seconds(6));
                            events.ScheduleEvent(EVENT_CALL_FRYE, Seconds(14));
                            events.ScheduleEvent(EVENT_PERFUME_SPRAY, Milliseconds(3640));
                            events.ScheduleEvent(EVENT_CHAIN_REACTION, Seconds(15));

                            Talk(SAY_SUMMON_ADDS); // add this line
                            std::vector<Creature*> trashs;
                            me->GetCreatureListWithEntryInGrid(trashs, NPC_CROWN_APOTHECARY);
                            for (Creature* crea : trashs)
                                crea->DespawnOrUnsummon();

                            break;
                        }
```
This should fix the problem.
You may want to rearrange the numbers in enum ApothecarySays and in the SQL as well to fit the flow. However this is unnecessary.

**Comment by Aokromes** [comment]
plz create a pull request for this.

**Comment by Keader** [comment]
Any proof?

**Comment by TecDian** [comment]
http://wow.gamepedia.com/Apothecary_Hummel
https://www.youtube.com/watch?v=N6iZVoHsnDU

**Comment by Keader** [comment]
Perfect, can you open a pr @TecDian ?

**Comment by sirikfoll** [comment]
You got it a little bit wrong, the Crazed Apothecary's summon wasn't implemented at all haha
The line when you add the text is to unsummon some trash mobs only

**Comment by TecDian** [comment]
This is true, I just added the line. I didn't change the event itself.
I noticed that the adds don't attack but get unsummoned. This needs to be done.

**Comment by Keader** [comment]
It's nota solves
Merged PR is wrong...
Minions is not implemented, we dont have sniffs about It and Minions Was removed from retail.

**Comment by BahDumbBugs** [comment]
Works for me. I just completed that quest.

**Comment by Vasago** [comment]
I have them there too... But some movement is really strange ... is it becuase of some movement changes done recently? Even though this one is "ranged" she is going like crazy accross the map ... going into textures for no reason ... really strange https://wow.gamepedia.com/Apothecary_Frye anyone can confirm this?

**Comment by Killyana** [comment]
For me he moves all over the place throwing perfumes, but never into texture, and it  looks to be the correct behavior: https://youtu.be/LasCpC-BTn0?t=29

**Comment by Killyana** [comment]
The Crazed Apothecary were removed in cata:
``` sql
UPDATE `creature_template` SET `exp`=2 WHERE `entry` IN (36568);
```
Summoned by
https://woehead.way-of-elendil.fr/?spell=68610

The line: "Apothecaries! Give your life for the Crown!" must be said when: Frye enter the combat :https://youtu.be/uqr1CiXAm3I?t=45

**Comment by Killyana** [comment]
Ref https://github.com/TrinityCore/TrinityCore/commit/8b5f40700a296212bb9579b08806b7d342ce5126
