### ISSUE TITLE
text handling for dk race quests

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#19536]
**Description:**

The prisoners to be executed for the dk race quests "A Special Surprise" (ID 12739,12742-12750) all have the lines for all races in creature_text. They should have only the ones they actually use. Corresponding with this the c++-script has a switch command to choose for each race what to say. This is superfluous if creature_text is written properly.

**Current behaviour:**

Absolutely OK, this isn't a bug. Just bad programming. Only that the reference to broadcast_text is wrong for some of the npcs because they have all the same entries in creature_text, resulting in minor deviations from the original.

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

173db1f5498dc7542e709a25f3a51d477b285f60

**TDB version:**  according to hash

**Operating system:** Windows 10

**Fix**

I will post a pull request for this.

Additionally I propose to delete broadcast_text entries belonging to cata and up for worgen and goblin dks. I will not include this in my pull request because I know how reluctant people here are to change these databases. Nevertheless it doesn't belong to 3.3.5

```SQL
DELETE FROM `broadcast_text` WHERE `ID` BETWEEN 49368 AND 49372;
DELETE FROM `broadcast_text` WHERE `ID` BETWEEN 49374 AND 49389;
DELETE FROM `locales_broadcast_text` WHERE `ID` BETWEEN 49368 AND 49372;
DELETE FROM `locales_broadcast_text` WHERE `ID` BETWEEN 49374 AND 49389;
```

**Comment by Aokromes** [comment]
we don't delete *_broadcast_text things

**Comment by tkrokli** [comment]
If you want to make a change, change any references to wrong text (if there are any) in the `gossip_menu` or `gossip_menu_option` tables. (I haven't noticed anything wrong on the gossip before, but I also haven't tested all races in the DK class.)

**Comment by TecDian** [comment]
@Aokromes: I thought so. It isn't necessary anyway.
@tkrokli: Everything OK with gossip.

**Comment by MrSmite** [comment]
> we don't delete *_broadcast_text things

Well the OP did indicate they're for 4.x so they shouldn't even be in the 3.x database to begin with.

**Comment by tkrokli** [comment]
Yeah, well, there is even text all the way up to patch 5.4.7c (build 18019) in that table from a massive dump from around that time.

**Comment by Aokromes** [comment]
3f34c2f5ebe8d0d9f97b169d1ace07d6ab3f3102
