### ISSUE TITLE
Leviathan in Black Temple spwan bug

### ISSUE THREAD

**Issue by junyack** [TrinityCore/TrinityCore#19533]
Leviathan which stands opposite High Warlord Naj'entus.
![image](https://cloud.githubusercontent.com/assets/3245932/25578953/09d04494-2e7c-11e7-97a3-4651d6a40af7.png)
Branch(es):
3.3.5

TC rev. hash/commit:
TrinityCore rev. 9d3810c 2017-04-30 11:03:44 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB version:
335.63

Operating system:
Windows 10 & Client

**Comment by Aokromes** [comment]
and.. what's the supposed bug?

**Comment by tkrokli** [comment]
"Removing issue template is evil." 😛

**Comment by junyack** [comment]
![image](https://cloud.githubusercontent.com/assets/3245932/25579240/d1f242b8-2e7e-11e7-88c3-76c35b05748c.png)
:D

**Comment by tkrokli** [comment]
Well, we still don't get what you are trying to say. Please describe in words by using the _original actual issue template_ .

**Comment by junyack** [comment]
One paw fell into the texture, the other higher

**Comment by tkrokli** [comment]
Well, if the creature is in its correct spot, that is not a spawn issue. A spawn issue would be if it was spawned in the wrong place.

**Comment by junyack** [comment]
Ahh okay, how fix?

**Comment by tkrokli** [comment]
Isn't this just an mmaps issue or something similar? That is a cosmetic bug and should not affect the gameplay.

**Comment by tkrokli** [comment]
Then again, if the creature had been standing on its head or lying on its side or facing backwards, that would be a spawn rotational issue.

**Comment by tkrokli** [comment]
If you can provide sniff or actual video from retail showing how it is supposed to stand, maybe checking its coordinates in TC source as well, maybe something could be done about its rotation. Would be interesting to know if it sinks or levitates when it moves around, though.

**Comment by junyack** [comment]
:D You are right, just fine, but such small errors.

**Comment by tkrokli** [comment]
Could also be useful to have a comment from @Keader to hear if this is something worth looking into.

**Comment by Keader** [comment]
DB Stuffs of Black Temple need some love...
But if i remember right, Leviathan should be in combat with 2 guards, this part is missing.

**Comment by tkrokli** [comment]
@junyack : if you want to report an issue about it, check that there are no existing open issues for Leviathan in Black Temple and create an issue where you _use the issue template_ and report that Leviathan does not have a scripted fight with the guards (and also is a bit off in his position due to missing movement, as a detail). That would make a better report.

**Comment by junyack** [comment]
https://youtu.be/pTAciZZcFfw?t=4m41s

**Comment by Aokromes** [comment]
http://i.imgur.com/voJqmDa.png

**Comment by junyack** [comment]
Yeah, in video same, mmaps ... but 2 guards only stay )

**Comment by tkrokli** [comment]
Remember that there are a lot of pserver videos on YouTube. Look for signs in video description and in the video itself to verify if it is from retail or not.

**Comment by junyack** [comment]
I know, thx.
