### ISSUE TITLE
Ice Sphere, Gas Cloud and Volatile Ooze Bugged

### ISSUE THREAD

**Issue by minkokomaung** [TrinityCore/TrinityCore#19532]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

The Lich King's ice sphere and Professor's Gas Cloud and Volatile Ooze should target 1 random player and move toward that player.

**Current behaviour:**

Currently they didn't move and stays in the place where spawned

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9d3810c3c83c 2017-04-30 11:03:44 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**
335.63
**Operating system:**
Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keader** [comment]
Caused by 3a0cb90ea994e82dd8c70888fb847082f738d5dc?!

**Comment by ariel-** [comment]
No, precisely that commit fixes those
