### ISSUE TITLE
Bugged walls, vendors, etc. in Wintergrasp

### ISSUE THREAD

**Issue by junyack** [TrinityCore/TrinityCore#19531]
Bugged walls, some invisible like this:
![image](https://cloud.githubusercontent.com/assets/3245932/25564618/e5a51aa2-2dbf-11e7-96d1-dc56bbfa78d8.png)
Some absent:
![image](https://cloud.githubusercontent.com/assets/3245932/25564662/e06efd0e-2dc0-11e7-9ff1-5e937d4e57eb.png)
All towes models bug:
![image](https://cloud.githubusercontent.com/assets/3245932/25564672/1faaad7e-2dc1-11e7-8f73-ae07119cc08a.png)
![image](https://cloud.githubusercontent.com/assets/3245932/25564673/258be834-2dc1-11e7-910b-aa9f4117f96b.png)
![image](https://cloud.githubusercontent.com/assets/3245932/25564784/34ff0f24-2dc3-11e7-9a8e-f1174147a9ea.png)

No teleports 
No vendors, etc...
Branch(es):
3.3.5

TC rev. hash/commit:
TrinityCore rev. 9d3810c3c83c 2017-04-30 11:03:44 +0200 (3.3.5 branch) (Win64, Release, Static)
TDB version:
335.63

Operating system:
Windows 10 & Client

**Comment by Keader** [comment]
Invisible walls is caused by grid unload (cause some bugs in relic too)

**Comment by junyack** [comment]
Several years ago, vendors work, battle timer... :) Now Empty Zone, no timer etc. :(

**Comment by Aokromes** [comment]
duplicate ticket. of a lot of tickets
#9205
