### ISSUE TITLE
Core/Script Priest Spell Divine Star

### ISSUE THREAD

**Issue by MartGon** [TrinityCore/TrinityCore#19549]
**Description:**

Divine Star  does not work. Nothing happens when you cast the ability.
http://www.wowhead.com/spell=110744

**Current behaviour:**

When you cast the spell, the cooldown starts but the projectile does not spawn. So it doesn't deal damage or heal. And then an erro appears on log "AreaTrigger (spellMiscId 2148) not created. Invalid areatrigger miscid (2148)"

**Expected behaviour:**

Right after the spell is casted the projectile should appear and move 24 yards forward (acording to the casters orientation) and then come back. It should deal damage or heal on it's path to every target that collides with it.

**Steps to reproduce the problem:**

1. Create a priest and .level 109 
2. Choose divine star on talents.
3. Cast divine star. Nothing happens and error appears.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 5233caf 2017-04-20 19:53:34 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver)

**TDB version:** 7.2.0

**Operating system:** Windows 7 Professional x64

**Some Notes**

I have been trying to script the areatrigger by myself, but I did not manage to move the areatrigger after it spawns. I tried by relocating to some random close Position but the client won't update the visual effect position. I know that this isn't the main topic of this issue but I would really thankful if someone could point me a bit on this.

**Comment by aquadeus** [comment]
this is fixed
