### ISSUE TITLE
Phasing problem after quest Return to Angrathar (12499)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19540]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**
Phasing issue after Return to Angrathar (12499)

**Current behaviour:**
Completing the quest Return to Angrathar (Quest 12499 - Alliance) to Highlord Bolvar Fordragon (Entry 27872) triggers a cinematic in which the Alliance and Horde leaders and most of the NPCs in the area are killed. After the cinematic is over there is no phase change.

![wowscrnshot_050117_164552](https://cloud.githubusercontent.com/assets/16745918/25597938/18f3e10c-2e8f-11e7-8c22-6ad16db4639f.jpg)

**Expected behaviour:**
Completing the quest should trigger a phase change where the zone is on fire, all of the npcs are gone or dead, and Alexstrasza is standing in the center of the calamity where she will provide a gossip text to replay the cinematic.

![wowscrnshot_050117_164445](https://cloud.githubusercontent.com/assets/16745918/25597934/095d99f4-2e8f-11e7-809d-058b77941ea7.jpg)

**Links**
http://www.wowhead.com/quest=12499/return-to-angrathar
http://www.wowhead.com/npc=27872/highlord-bolvar-fordragon

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 3028be49296c 2017-04-20 15:44:21 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:** 335.62

**Operating system:** Windows 10 Server & Client

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jerbookins** [comment]
As soon as I left the area, the phase changed.

**Comment by jerbookins** [comment]
I took the flight point to Wyrmrest Temple and discovered that maybe the phase area is not large enough
https://www.youtube.com/watch?v=Wqe6xmw0uYQ

**Comment by tkrokli** [comment]
Did you check with `.gm on` to see if there are any phased creatures/gameobjects which should be there if the phasing had been correct?

**Comment by jerbookins** [comment]
The problem is the NPCs who have died (especially Highlord Bolvar Fordragon) are still visible because they are not within the bounds of the phasing area. As soon as you leave the area, everything goes back to normal, including being able to see all of the NPCs that should be dead.

GM Mode does let me see both phases at once, nothing seems to be missing from the post-quest phase.

**Comment by tkrokli** [comment]
Hmm. I wonder where the area phasing is handled and how this can be remedied. I hope one of the main devs knows.

**Comment by jerbookins** [comment]
There seems to be some db code on this issue regarding the phasing. Maybe it could be of use? #11104

**Comment by Killyana** [comment]
fixed
