### ISSUE TITLE
[3.3.5] Daily quest status arent saved, breaks quest_template_addon

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19548]
**Description:**

Since https://github.com/TrinityCore/TrinityCore/commit/cbbb74524623ea22fc5375697d6ec2ec16a1755f the daily quests are no longer saved in character_queststatus after being rewarded, they are only there while incomplete and complete not as rewarded. This means that if you have lets say 2 quests, where quest A is a daily and Quest B is whatever, but you need to complete quest A to obtain quest B, you cant do that. As quest A will never be shown as [completed], so it doesnt satisfy for quest B in PrevQuestId. If you .quest reward a daily, youll see it no longer has any status if you do .lookup quest NAME.

**Current behaviour:**

^

**Expected behaviour:**

Completing a daily once should allow the possiblity to obtain the next quest in the chain.

**Steps to reproduce the problem:**

Explained it pretty much in description :P 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/5a2f0ce29e29d934c200f617fec6dad619fab9a5

**TDB version:**  63

**Operating system:** ubuntu 14.04

**Comment by Killyana** [comment]
Can you provide an example?

**Comment by Persephone** [comment]
Only ones i found with the criteria is http://wotlk.evowow.com/?quest=8386 but they dont have any queststarters by blizzlike standard. I noticed this via custom quests, but it should still be an easy as stated in: bool Player::GetQuestRewardStatus(uint32 quest_id) const

// for repeatable quests: rewarded field is set after first reward only to prevent getting XP more than once

But the rewarded flag is never set anymore. Meaing xp for example can be obtained over and over.

**Comment by Persephone** [comment]
And that it disallows dailies to be used as a condition for a quest chain

**Comment by Killyana** [comment]
I'm not sure if repeatable quests are supposed to be used for quest chaining, blizzard always create two version in this case, the first will be used as normal quest for chaining and the second one (daily for example) will be unlocked once the first one is rewarded.
Anyway I'm not able to find any daily or repeatable quest used as requirement.
