### ISSUE TITLE
[3.3.5] Core/Spells: Hunter's Autoshot

### ISSUE THREAD

**Issue by Eredar** [TrinityCore/TrinityCore#19546]
**Description:**

Currently Autoshot stops while moving.

**Current behaviour:**

Now if you want your autoshot to be continued, you should constantly make stops. 
For example: You pull a mob and start to walk backward to increase a distance between you and him (so you can shoot more), and there won't be next autoshot hit until you stop moving. So you should tap S many times that's obviously not intended and retarded, 

**Expected behaviour:**

Autoshot should be casted in any case if target in los.

**Steps to reproduce the problem:**

In "current behaviour".

1. Create a hunter.
2. Pull a mob.
3. Start moving.

**Branch(es):**

3.3.5 (maybe master too)

**TC rev. hash/commit:**   d625c0f

**TDB version:**  TDB 335.63

**Operating system:** Win 10 x64

**Comment by ariel-** [comment]
But you could never autoshot while moving

**Comment by Eredar** [comment]
You can autoshot while moving in cata and now in legion, and as I said in Issue, it's just retarded to spam S while moving back, do you have any proofs that autoshot was changed between wotlk and legion?

**Comment by Eredar** [comment]
Found myself in wowwiki:
Cataclysm Patch 4.0.6 (8-Feb-2011): Hunters can now use Auto Shot while moving.; Casting Trap Launcher, Distracting Shot, and Scare Beast now cancel Auto Shot when cast. This is to make it easier to crowd control creatures with Auto Shot while moving enabled.

Looks like you're right. So it wasn't obvious for blizzard for 7 years. Fine.

**Comment by ariel-** [comment]
Sounds like op to have it shooting while moving, you can escape from your target and shoot at the same time? Addons like Quartz were created because of this, you had to stop for a split second to let the shoot go and then keep moving while it cooled down.

**Comment by Aokromes** [comment]
blizzard changed the mechanic of a lot of spells with time, some where allowed to be used while moving, and later no, and the oposite.
