### ISSUE TITLE
[3.3.5] Spiritual Attunement doesnt proc

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19545]
**Description:**

Never procs, no mana is gained from being healed by allies.

**Current behaviour:**

^

**Expected behaviour:**

Should proc and heal the paladin from friendly targets heal.

**Steps to reproduce the problem:**

1. take spiritual attunement.
2. get healed by ally

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/5a2f0ce29e29d934c200f617fec6dad619fab9a5

**TDB version:**  53

**Operating system:**  ubuntu 14.04

**Comment by ariel-** [comment]
Note it got fixed with the proc system, it should only proc on effective healing, overheals will not trigger Spiritual Attunement.

**Comment by Persephone** [comment]
LOL I tested it all wrong, had it reported and just healed ma mate and saw no results. Now after being damaged i see it works fine.. Guess you learn even from such an old patch xD thanks ariel. 

Btw can you quickly confirm if nature's guardian http://wotlk.evowow.com/?spell=30881 procs for you? I've not been able to get that one to proc either since last update

**Comment by Persephone** [comment]
@ariel-  just before i open a new issue incase i misunderstood something again :P

**Comment by ariel-** [comment]
Can't test atm, but it should work
