### ISSUE TITLE
[3.3.5] PlayerStart.AllSpells doesnt work

### ISSUE THREAD

**Issue by mekoloamigo** [TrinityCore/TrinityCore#19555]
**Description:**
Hello. PlayerStart.AllSpells = 1 in worldserver.conf doesnt work. Nothing will just happen. Also trying with new created character.

**Current behaviour:**
^
**Expected behaviour:**
Learn player all spells included in playercreateinfo_spell_custom table.

**Steps to reproduce the problem:**
Explained it pretty much in description :P

**Branch(es):**
3.3.5,

**TC rev. hash/commit:** 
TrinityCore rev. a1969a3ad5fb 2017-04-18 13:07:01 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  62

**Operating system:** Windows 10

**Comment by Langerz82** [comment]
@tkrokli This now works. Close issue?
