### ISSUE TITLE
worldserver startup fails with new locale simple system

### ISSUE THREAD

**Issue by sxf1749** [TrinityCore/TrinityCore#19556]
**Description:**

maybe after locale system transfers to  simple system,
if any data in table npc_text_locale with field Text0_0 has content, startup failure.
old locale system has not startup problem

and some new  *_locale table hasnt combine primary key with field "Locale", is it ok with multi-language?

**Current behaviour:**

./worldserver startup get error 
"Segmentation fault (core dumped)"

**Expected behaviour:**

./worldserver startup successfully

**Steps to reproduce the problem:**

1. insert locale content into table npc_text_locale
2. ./worldserver  startup failed

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9ae53d257792 2017-05-06 04:45:53 +0200 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon)

**TDB version:**  63+

**Operating system:** ubuntu server 16.04

**Comment by Aokromes** [comment]
plz supply a gdb crashlog on debug mode.

**Comment by tkrokli** [comment]
`TC>TrinityCore rev. 9ae53d257792 2017-05-06 04:45:53 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...`

Unable to replicate on Windows 10 with Release build. I could try Debug, but I need to test a couple of things first.
