### ISSUE TITLE
[Crash] - dtNavMesh::calcTileLoc

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19553]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Crashlog: https://gist.github.com/Jildor/ee63573c68a03dc318cc17abcdde1704

**Steps to reproduce the problem:**

I do not know how reproduce it

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  c296d255e25a2d0eb7155f64eea32cc36fed280a

**TDB version:**  TDB335.63

**Operating system:**  Debian

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Artamedes** [comment]
This has to do with mmaps

**Comment by jackpoz** [comment]
startPoint = {590.3172, 609.158508, 5794.80371}
endPoint = {582.677734, 612.15387, 5793.00977}

**Comment by Shauren** [comment]
These are detour swapped coord (not xyz order)
```
start = {x = 5794.80371, y = 590.3172, z = 609.158508}
dest = {x = 5793.00977, y = 582.677734, z = 612.15387}
```

**Comment by Jildor** [comment]
```
.go xyz 5794.80371 590.3172 609.158508 571
.go xyz 5793.00977 582.677734 612.15387 571
```

using those coordinates on the map 571 (Northrend), you will appear right next to:
http://www.wowhead.com/npc=29533

**Comment by Jildor** [comment]
Another crash, seems the same coords (more or less)
https://gist.github.com/Jildor/5815b5b8669408fc2d9c9989d3715cf2

**Comment by Aokromes** [comment]
@Jildor you can reproduce this crash on head?

**Comment by Jildor** [comment]
I can not verify it for now, I'm sorry.
If anyone can confirm it or you can close it and when I can test it, I put the new crash log (If isn't fixed)

**Comment by robinsch** [comment]
I experience the same crash every ~1-2 days.

[1706402659.txt](https://github.com/TrinityCore/TrinityCore/files/14075280/1706402659.txt)

**Comment by CraftedRO** [comment]
> I experience the same crash every ~1-2 days.
> 
> [1706402659.txt](https://github.com/TrinityCore/TrinityCore/files/14075280/1706402659.txt)

I might be wrong but all coordinates there seems undermap, but judging by that creature text or whatever text is it I assume your core is heavy modified

**Comment by Legoso** [comment]
> I might be wrong but all coordinates there seems undermap, but judging by that creature text or whatever text is it I assume your core is heavy modified

Good point about that weird text. Just guessing here, but could something like that be caused by any external game client addons, injecting fantasy RP text into the player chat?

**Comment by Shauren** [comment]
16f555f79ef2fdebd18204bc90383ad7761343a5
