### ISSUE TITLE
[3.3.5] Hunter Beastmastery Pet Talents Broken

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#19554]
**Description:** Currently when you spec into talents in Beastmastery that affects your pet like unleashed fury & endurance training. The aura is not added to the pet as soon as the talent is taken. After a relog, the pets health increases = the auras gets applied.

**Current behaviour:**

Pet related auras do not apply to bet immediately. Re-Log is required.

**Expected behaviour:**

Pet related auras should apply to bet as soon as talent is taken.

**Steps to reproduce the problem:**

1. create hunter and spend talent points into Endurance Training while a pet is there.
2. Notice your health increases but pets doesnt.
3. Relog
4. Notice pets health is now correct.

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/5a2f0ce29e29d934c200f617fec6dad619fab9a5

**TDB version:**  63

**Operating system:** ubuntu 14.04

**Comment by Raydor** [comment]
Similar to https://github.com/TrinityCore/TrinityCore/issues/17837

**Comment by Aokromes** [comment]
same bug, read the last comment.
