### ISSUE TITLE
Core/Script The passive talent "Mania" don't give the bonus.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19569]
**Description:**

The passive talent "Mania" don't give the bonus of movement speed.

**Current behaviour:**

When choose the talen "Mania" according to the talent, for each 3 points of "Insanity" you the movement speed should increase in 1%. But at the moment is not giving the bonus of speed even though the bar of "Insanity" be the 100%

**Expected behaviour:**

For each 3 points of the bar of power "Insanity" should go up the speed of movement of Priest to 1%

**Steps to reproduce the problem:**

    1. Create a Human Player/Priest
    2. Go up it until level 30
    3. Chose the specialization "Shadow"
    4. Choose the talent "Mania"
    5. Fill the bar of power "Insanity"

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://es.wowhead.com/spell=195290/mania

**Comment by aquadeus** [comment]
since 8.0.1 blizzard has hidden the formula :/

**Comment by aquadeus** [comment]
deprecated, (Patch 8.1.0 (2018-12-11): Removed; replaced by Intangibility. ) intangibility works fine
