### ISSUE TITLE
Core/Scripts: Psychic Scream missing flee effect

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19564]
**Description:**

The Shadow Priest's spell "Psychic Scream" (8122) is malfunctioning.

**Current behaviour:**

The spell is disorienting enemies, but is not making them to flee, the stay in the place instead.

**Expected behaviour:**

Description on WowHead: http://www.wowhead.com/search?q=Psychic+Scream
"Psychic Scream: Lets out a psychic scream, causing 5 enemies within 8 yards to flee, disorienting them for 8 sec. Damage may interrupt the effect."
When they are affected by the spell, enemies should flee, running away, instead of standing in the place where they were affected.

**Steps to reproduce the problem:**

1. Create a Priest character.
2. Choose the class specialization "Shadow".
3. Reach the required level for the spell.
4. Use the spell on enemies.

**Branch(es):** Master

**TC rev. hash/commit:** 7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:** 720.00 + updates

**Operating system:** Windows 10

**Comment by Nyr97** [comment]
As of today, this spell works correctly.
