### ISSUE TITLE
Core/Script The talent Fortress of the Mind does not work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19563]
**Description:**

The Shadow Priest talent from the branch of level 15 "Fortress of the Mind" (193195) is making an issue. "Fortress of the Mind" increases damage dealed by "Mind Blast" a 10% and Insanity generated by it in a 20%. 

**Current behaviour:**

When choosing the talent, the description of the spell "Mind Blast"(8092) is anormally changed, showing incorrect stats, even thou the talent is working fine.

**Expected behaviour:**

The description of "Mind Blast" shold show the correct values according to the changes made by the talent "Fortress of the MInd".

**Steps to reproduce the problem:**

1. Create a Priest character.
2. Choose the class specialization "Shadow".
3. Reach level 15 and choose the talent "Fortress of the Mind".
4. Read the description of the spell "Mind Blast" in the spell book or the action bars.
5. Use the spell.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  CHANGEME Version of the TrinityCore database
7.0.2+updates
**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=193195/fortress-of-the-mind

**Comment by aquadeus** [comment]
is this fixed?

**Comment by mdX7** [comment]
insanity part works, damage part doesn't according to my quick tests

**Comment by mdX7** [comment]
nevermind, works properly
