### ISSUE TITLE
Core/Script The talent Amplification doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19572]
**Description:**

The talent Amplification (ID:236628) given to Mage Arcane at lv.15 has an issue

Amplification (passive): Arcane Missiles deals an additional 12% damage per Arcane Charge

**Current behaviour:**

The talent doesn´t work, it doesn´t increase the damage of Arcane Missiles per Arcane Charge

**Expected behaviour:**

When you choose this talent it should increase a 12% the damage deals by Arcane Missiles per Arcane Charge

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.15 choose the Arcane Spec
3. Use the spell Arcane Missiles in an anemy target and check the damage with 1,2,3 and 4 Arcane Charges.
4. Choose the talent Amplification from lv. 15 branch
5. Use the spell Arcane Missiles in an anemy target and check the damage with 1,2,3 and 4 Arcane Charges.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=236628/amplification

**Comment by Nyr97** [comment]
Invalid. As of today, the spell effect is unrelated to the issue posted above.
