### ISSUE TITLE
Core/Script The spell Displacement class Mage can´t be activated.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19570]
**Description:**

The spell Displacement(ID:195676) given to Mage Arcane at lv.48 has an issue

Displacement: Teleports you back to where you last Blinked from and resets the cooldown on Blink. Only usable within 10 sec. of Blinking

**Current behaviour:**

The spell never can´t be activated

**Expected behaviour:**

After use Blink you can use Displacement and return to where you last blinked from, using that will reset the cooldown on Blink. This spell is only usable within 10 sec of Blinking

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.48 and choose the Arcane Spec
3. Use the spell Blink and in the next 10 sec try to use Displacement

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=195676/displacement

**Comment by aquadeus** [comment]
this spell is deleted on shadowlands am i wrong?

**Comment by mdX7** [comment]
> 

yes its deleted / not useable atm, was replaced by altered time iirc
