### ISSUE TITLE
Core/Script The talent Mana Shield class mage has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19571]
**Description:**

The talent Mana Shield (ID:235463) given to Mage Arcane at lv.30 has an issue

Mana Shield (passive): Prismatic Barrier has no cooldown, but your mana is drained by 20% of the damage it absorbs

**Current behaviour:**

When you choose this talent it apply the effect in Prismatic Barrier, but your mana never is drained

**Expected behaviour:**

When you choose this talent it should remove the cooldown from Prismatic Barrier, but your mana is drained by 20% of the damage it absorbs

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.30 choose the Arcane Spec and the talent Mana Shield from lv.30 branch
3. Use the spell Prismatic Barrier and get it combat
4. Check if your mana are drained

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=35064/mana-shield

**Comment by aquadeus** [comment]
is this spell first replaced by incanters ward and later replaced again by incanters flow?

**Comment by aquadeus** [comment]
this talent is deprecated
