### ISSUE TITLE
Core/Script The spell Arcane Blast has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19574]
**Description:**

The spell Arcane Blast(ID:30451) given to Mage Arcane at lv.10 has an issue

Arcane Blast: Blasts the target with energy, dealing (x) Arcane damage. Damage increased by 60& per Arcane Charge. Mana cost increased 125% per Arcane Charge.

**Current behaviour:**

When you use the spell the damage and mana cost doesn´t change per Arcane Charge.

**Expected behaviour:**

When you use the spell his damage and mana cost will be increased the % that the description shows per Arcane Charges

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.10 and choose the Arcane Spec
3. Use the spell Arcane Blast with 1,2,3, and 4 arcane charges and check the damage and mana cost with every arcane charge

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=30451/arcane-blast

**Comment by aquadeus** [comment]
is this spell already fixed?

**Comment by Faq** [comment]
@aquadeus, you could set up master and check it out with provided reproduce steps.

**Comment by aquadeus** [comment]
yes this is fixed
