### ISSUE TITLE
Core/Script The spell Flurry doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19585]
**Description:**

The spell Flurry(ID:44614) given to Mage Frost at lv.20 has an issue

Flurry: Unleach a flurry of ice shards, striking the target 3 time for a total of (x) frost damage. Each shard reduces the target´s movement speed by 70% for 1 sec

**Current behaviour:**

The spell doesn´t work at all, when you cast the spell nothing happen, you don´t attack the target and any visual effect is activated

**Expected behaviour:**

when you use the spell you should strike the target 3 times with ice shards for (x) total damage and each ice shards should reduce the movement of the target 70% for 1 sec 

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.20 and choose the Frost Spec
3. Use the spell Flurry in an enemy

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=44614/flurry

**Comment by Nyr97** [comment]
As of today, the spell does use the visual and deals damage, but only once. It should be three times.
