### ISSUE TITLE
Scripts/Spells: passive spell Hunting Party increases the cooldown of Exhilaration

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19598]
**Description:**

The spell passive ''Hunting Party'' [Spell ID: 212658] of the Hunter class in the spec of Marksmanship, has an issue.

**Current behaviour:**

The spell passive ''Hunting Party'' [Spell ID: 212658] does not reduce the remaining cooldown on ''Exhilaration'' [Spell ID: 109304] by 30 sec after you kill an enemy target.

**Expected behaviour:**

The spell passive ''Hunting Party'' [Spell ID: 212658] should reduce the remaining cooldown on ''Exhilaration'' [Spell ID: 109304] by 30 sec after you kill an enemy target.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then, reach level 58 in order to learn the spell passive ''Hunting Party'' [Spell ID: 212658].
4. Kill an enemy target while having ''Exhilaration'' [Spell ID: 109304] on cooldown.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=212658/hunting-party

**Comment by MartGon** [comment]
I've seen a related bug while testing this spell. It actually **increases** the cooldown of ''Exhilaration'' [Spell ID: 109304] by 30s instead of reducing it. I think it's caused by these lines in spell_hunter.cpp on the spell_hun_hunting_party class.

```
void HandleProc(AuraEffect const* aurEff, ProcEventInfo& /*eventInfo*/)
            {
                PreventDefaultAction();
                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION, Seconds(aurEff->GetAmount()));
                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION_PET, Seconds(aurEff->GetAmount()));
            }
```
I think it's missing the '-' symbol before `aurEff->GetAmount()` so it reduces the cooldown instead of increasing it.
I've tested it on this way and it works as it should.

**Comment by tkrokli** [comment]
OK, so what you are saying is that a diff on current master (https://github.com/TrinityCore/TrinityCore/commit/9b346dc22b7aaf1f2a7dddb6b629478972231214) should look like this?
```diff
diff --git a/src/server/scripts/Spells/spell_hunter.cpp b/src/server/scripts/Spells/spell_hunter.cpp
index e37f65f..2a3da26 100644
--- a/src/server/scripts/Spells/spell_hunter.cpp
+++ b/src/server/scripts/Spells/spell_hunter.cpp
@@ -286,8 +286,8 @@ class spell_hun_hunting_party : public SpellScriptLoader
             void HandleProc(AuraEffect const* aurEff, ProcEventInfo& /*eventInfo*/)
             {
                 PreventDefaultAction();
-                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION, Seconds(aurEff->GetAmount()));
-                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION_PET, Seconds(aurEff->GetAmount()));
+                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION, -Seconds(aurEff->GetAmount()));
+                GetTarget()->GetSpellHistory()->ModifyCooldown(SPELL_HUNTER_EXHILARATION_PET, -Seconds(aurEff->GetAmount()));
             }
 
             void Register() override
```

**Comment by HannibalRoG** [comment]
I also try this and left feedback :)

**Comment by HannibalRoG** [comment]
With the fix submited by @MartGon Hunting Party work as intended, reduce 30s of cooldown on Exhilaration any time you kill an enemie.

**Comment by HannibalRoG** [comment]
In order to expedite the process of closing issues, what would be the next step? Wait for @MartGon to create a PR or do we @tkrokli ?

**Comment by tkrokli** [comment]
@HannibalRoG : the standard procedure is that the original author of the code change should create a PR to the TC source. This is mainly to be able to get correct feedback when any of the main TC developers ask questions about the code and have the author respond to any reasoning behind the changes and also how it was tested. So yeah, if you have got time and know how to do it, feel free to PR your code change, @MartGon .
