### ISSUE TITLE
DB/Spells: Bombardment (passive) proc triggers too much

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19597]
**Description:**

The spell passive ''Bombardement'' [Spell ID: 35110] of the Hunter class in the spec of Marksmanship, triggers both on non-crit and crit as well as from non-related spells.

**Current behaviour:**

The spell passive ''Bombardement'' [Spell ID: 35110] activates with the following spells: 
- Autoshoot [crit and non crit hit]
- Aimed Shot [Spell ID: 19434] [crit and non crit hit]
- Arcane Shot [Spell ID: 185358] [crit and non crit hit]
- Bursting Shot [Spell ID: 186387] [crit and non crit hit]
- Piercing Shot [Spell ID: 198670] [crit and non crit hit]
- Multi-Shot [Spell ID: 2643] [non crit]

**Expected behaviour:**

The spell passive ''Bombardement'' [Spell ID: 35110] should be only activated by critical strikes with the spell ''Multi-Shot'' [Spell ID: 2643].

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then, reach level 50 in order to learn the spell passive ''Bombardement'' [Spell ID: 35110].
4. Hit an enemy target with auto shots or with any of the following spells: ''Arcane Shot'' [Spell ID: 185358], ''Aimed Shot'' [Spell ID: 19434] , ''Bursting Shot'' [Spell ID: 186387], ''Piercing Shot'' [Spell ID: 198670] ''Multi-Shot'' [Spell ID: 2643] [Non crit hit].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=35110/bombardment

**Comment by MartGon** [comment]
Possible fix:
```
-- 35110 Bombardment
DELETE FROM `spell_proc_event` WHERE entry=35110;
INSERT INTO `spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `spellFamilyMask3`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) 
VALUES(35110,1,9,4096,0,0,0,0,2,0,0,0);
```
SpellFamilyMask0(4096)  -- Multi-Shot
ProcEx(2) -- PROC_EX_CRITICAL_HIT

**Comment by tkrokli** [comment]
@HannibalRoG : Can you test if the suggested fix works?

**Comment by HannibalRoG** [comment]
Yes, i am already on it, i include your sugestions in #19812.

**Comment by HannibalRoG** [comment]
Confirmed, with this fix it only activate with multi-shoot (critical)

**Comment by Aokromes** [comment]
@MartGon make a PR about fix.

**Comment by tkrokli** [comment]
OK, very well. I simply didn't see where it belongs in the source.

**Comment by Aokromes** [comment]
removed on BFA.
