### ISSUE TITLE
Core/Script The spell Cold Snap doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19591]
**Description:**

The spell Cold Snap(ID:235219) given to Mage Frost at lv.51 has an issue

Cold Snap: Resets the cooldown of your Frost Nova, Cone of Cold, Ice Barrier, and Ice Block

**Current behaviour:**

The spell doesn´t work, it doesn´t reset the cooldown of any spell 

**Expected behaviour:**

when you use the spell it should reset the cooldown of the spell´s that appear in the spell description

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.51 an choose the Frost Spec
3. Use the spell´s Frost Nova, Cone of Cold, Ice Barrier and Ice Block
4. Use the spell Cold Snap and check the cooldown´s

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=235219

**Comment by Nyr97** [comment]
As of today, the only spell that isn't being reset is Frost Nova.
