### ISSUE TITLE
Scripts/Spells: Volley does not reduce Focus when triggered

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19596]
**Description:**

The spell talent ''Volley'' [Spell ID: 194386] in Marksmanship and Beast Mastery specs does not reduce Focus by 3 as expected when used during Auto Attack.

**Current behaviour:**

The spell talent ''Volley'' [Spell ID: 194386] does not spend 3 focus when you hit an enemy target with an auto attack.

**Expected behaviour:**

While the spell ''Volley'' [Spell ID: 194386] is active, your auto attacks spend 3 Focus to also launch a volley of shots that hit the target and all other nearby enemies dealing 710 additional Physical damage. 

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship or Beast Mastery .
3. Reach level 90 and choose the spell talent ''Volley'' [Spell ID: 194386].
4. Then, use the spell talent ''Volley'' [Spell ID: 194386] in order to activate this spell.
5. Hit an enemy target with auto attacks.

**Branch(es):** Master

**TC rev. hash/commit:** 7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  720.00 + updates

**Operating system:** Windows 10

Description in wowhead: http://www.wowhead.com/spell=194386/volley

**Comment by MartGon** [comment]
Possible fix:
```
-- 35110 Bombardment
DELETE FROM `spell_proc_event` WHERE entry=35110;
INSERT INTO `spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `spellFamilyMask3`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) 
VALUES(35110,1,9,4096,0,0,0,0,2,0,0,0);
```
SpellFamilyMask0(4096)  -- Multi-Shot
ProcEx(2) -- PROC_EX_CRITICAL_HIT

**Comment by MartGon** [comment]
Possoble fix, I don't feel that is the best solution so here  I leave a link to my branch where the fix is: https://github.com/MartGon/TrinityCore/commit/dc9b6703a3b3d98aac5dfaeee9f9652dfcb2c1c9

**Comment by HannibalRoG** [comment]
@MartGon It is important to create a PR for this fix, more than anything, so that the knowledge of the community manages to improve it, sometimes we do not see or do things correctly and with the comments we improve and learn.

**Comment by Nyr97** [comment]
Invalid, this spell is not available anymore for Marksmanship or  Beast Mastery hunters.
