### ISSUE TITLE
Core/Script The passive spell talent Farstrider has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19601]
**Description:**

The passive spell talent ''Farstrider'' [Spell ID: 199523] of the Hunter class in the specs Marksmanship and Beast Mastery, has an issue.

**Current behaviour:**

The passive spell talent ''Farstrider'' [Spell ID: 199523] does not reset the remaining cooldown on ''Disengage'' [Spell ID: 781] when you critically hit an enemy with any ability.

**Expected behaviour:**

The passive spell talent ''Farstrider'' [Spell ID: 199523] has a 15% chance to reset the remaining cooldown on ''Disengage'' [Spell ID: 781] when you critically hit with a spell.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship or Beast Mastery.
3. Then, reach level 45 and choose the passive spell talent ''Farstrider'' [Spell ID: 199523].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=199523/farstrider

**Comment by Nyr97** [comment]
Invalid, the spell is not available anymore for marksmanship hunters.
