### ISSUE TITLE
Core/Script The spell Bursting Shot has an issue. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19609]
**Description:**

The spell ''Bursting Shot'' [Spell ID: 186387] of the Hunter class in the spec Marksmanship, has an issue.

**Current behaviour:**

When using the spell ''Bursting Shot'' [Spell ID: 186387] in front of an enemy target, it deals damage and it knocks him back but it does not desorientates the target for 4 sec.

**Expected behaviour:**

Once you use the spell ''Bursting Shot'' [Spell ID: 186387] in front of enemy targets, it should knock them back and deal 11 physical damage, and it should also desoriantate them for 4 sec.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then reach level 26 in order to learn the spell ''Bursting Shot'' [Spell ID: 186387].
4. Use ''Bursting Shot'' [Spell ID: 186387] in front of enemy targets.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=186387/bursting-shot

**Comment by Nyr97** [comment]
Invalid, the spell works as intended now.
