### ISSUE TITLE
Core/Script The passive spell talent True Aim has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19607]
**Description:**

The passive spell talent ''True Aim'' [Spell ID: 199527] of the Hunter class in the spec Marksmanship, has an issue.

**Current behaviour:**

The passive spell talent True Aim (ID of the passive spell talent buff: 199803) can be applied on a target by using the following spells: ''Bursting Shot'' [Spell ID: 186387], ''Barrage'' [Spell ID: 120360], ''Piercing Shot'' [Spell ID: 198670] and by hitting the enemy target with auto shots. 

**Expected behaviour:**

The passive spell talent ''True Aim'' [Spell ID: 199527] should apply ''True Aim'' buff [spell buff ID: 199803] on an enemy target by using only ''Arcane Shot'' [Spell ID: 185358] or ''Aimed Shot'' [Spell ID: 19434].

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then reach level 30 and choose the spell talent ''True Aim'' [Spell ID: 199527] .
4. Use any of the following spells on an enemy target in order to apply ''True Aim'' buff: ''Bursting Shot'' [Spell ID: 186387], ''Barrage'' [Spell ID: 120360], ''Piercing Shot'' [Spell ID: 198670]. You can also hit the enemy target with auto shots in order to apply ''True Aim'' buff on the target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=199527/true-aim

**Comment by Nyr97** [comment]
Invalid, the spell is not available for hunters anymore.
