### ISSUE TITLE
Core/Script The spell Multi-Shot is not working properly. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19612]
**Description:**

The spell ''Multi-Shot'' [Spell ID: 2643] of the Hunter class in the spec Marksmanship, has an issue.

**Current behaviour:**

When using ''Multi-Shot'' [Spell ID: 2643] on a single enemy target or lets just say on five enemy targets, the hunter does not gerenate 2 Focus point per target hit. The spell does not generate any Focus at all.

**Expected behaviour:**

Once you use the spell ''Multi-Shot'' [Spell ID: 2643] it should generate 2 Focus Points per target hit.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then reach level 16 in order to learn the spell ''Multi-Shot'' [Spell ID: 2643].
4. Use ''Multi-Shot'' [Spell ID: 2643] on enemy targets.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=2643/multi-shot

**Comment by Nyr97** [comment]
Invalid, the spell doesn't generate focus as of today, it rather spends it.
