### ISSUE TITLE
Core/Script The spell talent Black Arrow has issues. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19614]
**Description:**

The spell talent ''Black Arrow'' [Spell ID: 194599] of the hunter class in the spec Marksmanship, has issues.

**Current behaviour:**

When using the spell talent ''Black Arrow'' [Spell ID: 194599] on an enemy target, the spell deals damage but the ''Dark Minion'' [Npc ID: 94072] that is summoned by this spell, does not taunt your current target. ''Black Arrow'' [Spell ID 194599] does not resets once you kill an enemy target. 

**Expected behaviour:**

Once you use the spell ''Black Arrow'' [Spell ID: 194599] on an enemy target, it should deal 588 shadow damage over 8 sec and summon a ''Dark Minion'' [Npc ID: 94072] that taunts the enemy target for the duration of the spell. The remaining cooldown of ''Black Arrow'' [Spell ID: 194599 should reset once you kill an enemy. 

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. Then reach level 30 and choose the spell talent ''Black Arrow'' [Spell ID: 194599].
4. Use the spell ''Black Arrow'' [Spell ID: 194599] on an enemy target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=194599/black-arrow

**Comment by Nyr97** [comment]
Invalid, the spell is not available for Marksmanship hunters anymore.
