### ISSUE TITLE
Core/Script The spell Aimed Shot has an issue. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19610]
**Description:**

The spell ''Aimed Shot'' [Spell ID: 19434] of the Hunter class in the spec Marksmanship, has an issue.

**Current behaviour:**

''Aimed Shot'' [Spell ID: 19434] does not deal 100% increased damage on targets that hasn't been damaged yet.

**Expected behaviour:**

The spell ''Aimed Shot'' [Spell ID: 19434] should deal 80 Physical damage. The damage is increased by 100% against a target you have not yet damaged.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose the spec Marksmanship.
3. The reach level 12 in order to learn ''Aimed Shot'' [Spell ID: 19434].
4. Use ''Aimed Shot'' [Spell ID: 19434] on an enemy target that hasn't been damaged yet.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=19434/aimed-shot

**Comment by Nyr97** [comment]
Invalid, the spell's damage is not increased against a target they have not yet damaged as of today.
