### ISSUE TITLE
Core/Script The Spell passive Hunter's Mark does not work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19618]
**Description:**

The spell passive ''Hunter's Mark'' [Spell ID: 185987] of the Hunter class in Marksmanship spec does the following : Your auto shots have a chance to cause your next ''Arcane Shot'' [Spell ID: 185358] or ''Multi-Shot'' [Spell ID: 2643] to apply Hunter's Mark. Hunter's Mark activates ''Marked Shot'' [Spell ID: 185901] . This spell passive doesn't work. 

**Current behaviour:**

Once you gain the spell buff ''Marking Targets'' [Spell ID: 223138] by hitting the target with auto shots, and you use the spell ''Arcane Shot'' [Spell ID: 185358] or ''Multi-Shot'' [Spell ID: 2643] on the enemy target, the spell passive ''Hunter's Mark'' [Spell ID: 185987] does not apply on the target.

**Expected behaviour:**

Once the Hunter gains the spell buff ''Marking Targets'' [Spell ID: 223138] by hitting the target with auto shots, and then uses ''Arcane Shot'' [Spell ID: 185358] or ''Multi-Shot'' [Spell ID: 2643] on the enemy target, the spell passive ''Hunter's Mark'' [Spell ID: 185987] should be applied on the enemy target.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 10 and choose Marksmanship spec.
3. Then reach level 20 in order to learn the spell passive ''Hunter's Mark'' [Spell ID: 185987].
4. Attack an enemy with auto shots and wait until you gain ''Marking Targets'' [Spell ID: 223138] buff.
5. Once you gain ''Marking Targets'' [Spell ID: 223138] buff, hit the target with the spell ''Arcane Shot'' [Spell ID: 185358] or ''Multi-Shot'' [Spell ID: 2643].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=185987/hunters-mark

**Comment by Nyr97** [comment]
Invalid, the spell is not available to Marksmanship hunters anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
