### ISSUE TITLE
Core/Script The passive spell Mastery: Deep Healing doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19626]
**Description:**

The passive spell Mastery:Deep Healing (ID:77226) given to Chaman Restauration at lv.78 has an issue

Mastery: Deep Healing : Increases healings from your spells by up to (x)%, based on the courrent health of your target. Lower health targets are healed for more.

**Current behaviour:**

The spell doesn´t work, it doesn´t increases any spell healings

**Expected behaviour:**

when you use a healing spell, the healing should be increased by (x)% dependending of your mastery points

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.78 an choose the Restoration Spec
3. Use healings spells on allies or on yourself.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=77226/mastery-deep-healing

**Comment by aquadeus** [comment]
this is fixed
