### ISSUE TITLE
Core/Script The talent Lightning Shield has and issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19624]
**Description:**

The talent Lightning Shield(ID:192106) given to Chaman Enhancement at lv.60 has an issue

Lightning Shield: Surround yourself with a shield of lighting for 1 hour which has a chance to deal (x) nature damage when you deal or take melee damage

**Current behaviour:**

When you choose this talent and use it the buff and the visual effect appear but it doesn´t deal any damage when you deal or take melee damage

**Expected behaviour:**

When you use this talent it should deal (x) damage when you deal or take melee damage

PD: The damage depends of your lv

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.60, choose the Enhancement Spec and choose the talent Lightning Shield from lv.60 branch
3. Use the talent and get in combat
4. Check when you deal or take melee damage if the shield do any damage

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=192106/lightning-shield

**Comment by Nyr97** [comment]
Invalid, the spell works correctly as of today.
