### ISSUE TITLE
Core/Script The spell Lava Surge has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19627]
**Description:**

The spell Lava Surge (ID:77756) given to Chaman Restoration at lv.39 has an issue

Lava Surge: Your Flame Shock damage over time has a 15% chance to reset the remaining cooldown on Lava Burst and cause your next Lava Burst to be instant

**Current behaviour:**

The spell works how the description shows, the issue is that this effect is activated for other spell who has over time funtion like Riptide

**Expected behaviour:**

The effect of Lava Surge should be activated only with the spell Flame Shock

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.39 an choose the Restoration Spec
3. Use the spell Riptide in yourself or other frienly target and check that the effect of Lava Surge is activated (You probably should repeat this action some times)

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=77756/lava-surge

**Comment by Nyr97** [comment]
This was fixed on https://github.com/TrinityCore/TrinityCore/pull/27667.
