### ISSUE TITLE
Core/Script The passive spell Mastery: Enhanced Elements doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19625]
**Description:**

The passive spell Mastery: Enhanced Elements(ID:77223) given to Chaman Enhancement at lv.78 has an issue

Mastery: Enhanced Elements: Increases your chance to trigger Stormbringer and Wind Fury by (x)% and increases all Fire, Frost and Nature damage you deal by (x)%

**Current behaviour:**

The spell doesn´t work, it never increases the damage of any spell or increase your chance to trigger Stormbringer and Wind Fury

**Expected behaviour:**

After reach lv.78 and learn the spell Mastery: Enhanced Elements you chance to trigger Stormbringer and Wind Fury will be increase (x)% and all Fire, Frost and Nature damage will be increase (x)%, this % depend of your mastery points

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.77 an choose the Enhancement Spec
3. Check Fire, Frost and Nature damage you deal, and your chance to trigger Stormbringer and Wind Fury
4. Reach lv.78, increase your mastery points and check Fire, Frost and Nature damage you deal, and your chance to trigger Stormbringer and Wind Fury

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=77223/mastery-enhanced-elements

**Comment by aquadeus** [comment]
now it scales
