### ISSUE TITLE
Core/Script The spell Arcane Shot has an issue. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19620]
**Description:**

The spell ''Arcane Shot'' [Spell ID: 185358] of the Hunter class does 49 of damage to an enemy target and generate 5 points of focus. This spell has an issue.

**Current behaviour:**

When you use the spell ''Arcane Shot'' [Spell ID: 185358] it does damage but it doesn't generate 5 focus points.

**Expected behaviour:**

When you use the spell ''Arcane Shot'' [Spell ID: 185358] on an enemy target it should do 49 damage and generate 5 focus points.

**Steps to reproduce the problem:**

1. Create a Hunter.
2. Reach level 10.
3. Chose the Marksmanship specialization.
4. Use the spell ''Arcane Shot'' [Spell ID: 185358] on an enemy target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=185358/arcane-shot

**Comment by Nyr97** [comment]
Invalid, the spell costs focus rather than generating it as of today.
