### ISSUE TITLE
Core/Script The spell Healing Rain has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19637]
**Description:**

The spell Healing Rain (spell ID:73920) given to Chaman Restauration at lv.40 has an issue Healing Rain: Blanket the target area in healing rains, restoring (x) health to up 6 allies over 10 sec.

**Current behaviour:**

The spell doesn´t work, it doesn´t heal and the visual effect doesn´t appear either even when you use it only in yourself. It only create the buff but it doesn´t heal 

**Expected behaviour:**

when you use the spell it should heal to up 6 allies in the area you choose for 10 sec and also do the visual effect asigned to the spell

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.40 an choose the Restoration Spec
3. Select an area with allies and use the spell

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=73920/healing-rain

**Comment by Shauren** [comment]
Current status: works, missing target count restriction

**Comment by aquadeus** [comment]
this is fixed 100%
