### ISSUE TITLE
Core/Script The talent Voodoo Totem has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19634]
**Description:**

The talent Voodoo Totem (ID:196932) given to Chaman in all spec´s at lv.45 has an issue

Voodoo Totem: Summons a totem at the target location for 10 sec. The totem hexes all enemies within 8 yards into frogs wich are incapicitated and unable to attack or casts spells. Damage or leaving the area will intercep the effect.

**Current behaviour:**

The talent doesn´t work, when you summon the totem it appear but it doesn´t do anything 

**Expected behaviour:**

when you summon the totem all enemies in 8 yards around will hexes into frogs unable to attack or casts spells, if they get out the area or recieve damage the effect will be interrupted

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.10 an choose the Restoration Spec
3. Reach lv.45 and choose the talent Voodoo Totem
4. Use the talent on enemies
5. Repeat all steps with elemental and enhancement

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=196932/voodoo-totem

**Comment by Nyr97** [comment]
Invalid. As of today, this spell is not available for shamans anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
