### ISSUE TITLE
Core/Script The spell Ancestral Vision has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19630]
**Description:**

The spell Ancestral Vision (ID:212048) given to Chaman Restoration at lv.66 has an issue

Ancestral Vision: Returns all dead party members to life with 35% of maximun health and mana. Cannot be cast when in combat.

**Current behaviour:**

The spell doesn´t work, when you cast the spell surrounded by dead party members they don´t return to life 

**Expected behaviour:**

When you cast the spell all the dead party members should return to life

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.66 an choose the Restoration Spec
3. Use the spell surrounded by dead party members

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=212048/ancestral-vision

**Comment by Nyr97** [comment]
Invalid. As of today, the spell works correctly.
