### ISSUE TITLE
Core/Script Talent Unleash Life Visual Problem.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19638]
**Description:**

The talent Unleash Life given to Restoration Shaman in lv.15 branch has an issue. Unleash Life: Unleashes elemental forces of life, healing a friendly target for (X) and increasing the efect of the Shaman´s next direct heal by 45%

**Current behaviour:**

The talent works perfectly but has a visual problem, when you use it in the description of all your healings spell appear that your heal has decrease a 45%

**Expected behaviour:**

When you use the talent Unleash Life in the descripcion of your healings spells should appear the real valor of your heal increase by a 45%

**Steps to reproduce the problem:**

1. Create a Shaman character
2. Reach to lv.15, choise Restoration spec, and select the talent Unleash Life
3. Use the talent Unleash Life in a friendly target and check the description of your healings spells.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=73685/unleash-life

**Comment by Nyr97** [comment]
Invalid. The spell works correctly as of today and it shows the correct amount of healing both on OnTargetHit and Combatlog.
