### ISSUE TITLE
Core/Script The Talent Howl of Terror is not working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19652]
**Description:**

The Warlock's Talent "Howl of Terror" (ID: 5484) learned at level 45 Talent's branch in the specialization of Affliction, is not working.

Howl of Terror: Let loose a terrifying howl, causing 5 enemies within 5 yards to flee in fear, disorienting them for 20 sec. Damage may cancel the effect.

**Current behaviour:**

When you use the Talent Howl of Terror the animation works perfectly, the debuff is created on enemies but, they do not get disoriented, they do not flee, the talent functions does not seems to work.

**Expected behaviour:**

When using Howl of Terror should do it's function showed in it's description, enemies afected should flee for 20 sec, disorienting them.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 45 at the specialization of Affliction and choose the Talent "Howl of Terror" from level 45 Talent's branch.
3. Gather 5 or less enemies within 5 yards and use Howl of Terror.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=5484/howl-of-terror

**Comment by Nyr97** [comment]
As of today, the spell works correctly.
