### ISSUE TITLE
Core/Script The Talent Burning Rush has a critical mortal issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19650]
**Description:**

The Warlock's Talent "Burning Rush" (ID: 111400) learned at level 75 Talent's branch, has a critical mortal issue.

Burning Rush: Increases your movement speed by 50%, but also damages you for 4% of your maximum health every 1 sec. Movement impairing effects may not reduce you below 100% of normal movement speed. Last until cancelled.

**Current behaviour:**

The Talent increases the movement speed propperly, but can not be cancelled, it keeps damaging you until death.

**Expected behaviour:**

Once you activate Burning Rush, you should be able to cancel it at any time.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 60 And choose the talent "Burning Rush" from level 60 talent's branch.
3. Use Burning Rush, then try to cancel it.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=111400/burning-rush

**Comment by buenodart** [comment]
Any solution for this bug?
