### ISSUE TITLE
Core/Script The Talent Demonic Circle has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19654]
**Description:**

The Warlock's Talent "Demonic Circle" (ID: 48018) learned at level 45 talent's branch, has a critical issue.

Demonic Circle (ID: 48018): Summons a demonic circle for 15 min, allowing you to cast it again to teleport to its location and remove all movement slowing effects. Limit 1.

This spell turns into this one after use it the first time:

Demonic Circle (ID: 48020): Teleports you to your Demonic Circle and remove all movement slowing effects.

**Current behaviour:**

When you use the spell "Demonic Circle" (ID: 48018), the demonic circle is summoned with no issues and this spells turns into "Demonic Circle" (ID: 48020), when you try to use the last one it says "You can't do that yet".

**Expected behaviour:**

When you use Demonic Circle (ID: 48020) after using Demonic Circle (ID: 48018) you should be teleported to the current location of the previously summoned demonic circle.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 45 and choose "Demonic Circle" from the talent branch of that level.
3. Use Demonic Circle (ID: 48018).
4. Then try to use Demonic Circle (48020).

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=48018/demonic-circle

**Comment by BoThay** [comment]
its related to spell_aura_restrictions, it can be fixed with this hotfixes db table

**Comment by aquadeus** [comment]
this works fine
