### ISSUE TITLE
Core/Script The passive Talent Empowered Life Tap is not working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19656]
**Description:**

The Warlock's passive Talent "Empowered Life Tap" (ID: 235157) learned in the branch of level 30 at the specialization of Affliction, is not working.

Empowered Life Trap (passive): Life Tap (ID: 1454) increases your damage dealt by 10% for 20 sec.

**Current behaviour:**

When having the passive talent, Life Tap does not increase your damage dealt, is like the Talent makes no change over the spell.

**Expected behaviour:**

When having The passive Talent "Empowered Life Tap", the spell "Life Tap" should also increase your damage dealt by 10% for 20 sec.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 30 and choose the talent "Empowered Life Tap".
3. Use "Life Tap" and attack an enemy.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=235157/empowered-life-tap

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is not available for Affliction warlocks anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
