### ISSUE TITLE
Core/Script The Talent Soul Harvest is no fully working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19651]
**Description:**

The Warlock's Talent "Soul Harvest" (ID: 196098) learned at level 60 Talent's branch, is not fully working.

Soul Harvest: Increases you damage and your pet's damage by 20%. Last 15 sec, increased by 2 sec for each target afflicted by your "Agony" (ID: 980), up to a maximum of 35 sec.

**Current behaviour:**

When using the talent, damage is increased propperly but the duration of the effect is not increased by each target afflicted by "Agony".

**Expected behaviour:**

This talent's duration should be increased by 2 sec for each target afflicted by "Agony".

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 60 and choose the Talent "Soul Harvest" from the current level talent's branch.
3. Afflict some enemies with "Agony", then use "Soul Harvest", notice the duration does not change.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=196098/soul-harvest

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is not available for warlocks anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
