### ISSUE TITLE
Core/Script The Talent Mortal Coil is not fully working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19653]
**Description:**

The Warlock's Talent "Mortal Coil" (ID: 6789) learned in the Talent's branch at level 45, is not fully working.

Motal Coil: Horrifies an enemy target into fleeing, incapacitating for 3 sec and healing you for 20% of maximum health.

**Current behaviour:**

When you use the talent, it heals you the propper amount, create the right debuff on the enemy target, but the target does not flee and is not incapacitated it for 3 sec.

**Expected behaviour:**

When you use the talent on an enemy target should be incapacitated for 3 sec and fleeing, also heal you.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 45 and choose the talent "Mortal Coil" from level 45 Talent's brach.
3. Use the spell on any enemy target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=6789/mortal-coil

**Comment by Nyr97** [comment]
Invalid. As of today, the spell works correctly.
