### ISSUE TITLE
Core/Script The Talent Haunt is not fully working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19663]
**Description:**

The Talent "Haunt" (ID: 48181) learned in the specialization of Affliction at the branch of level 15, has an issue.

Haunt: A ghostly soul haunts the target, dealing (x) shadow damage an increasing your damage dealt to the target by 30% for 15 sec. If target dies, Haunt's cooldown is reset.

**Current behaviour:**

The warlock cast Haunt fine, it deals the propper damage, a debuff is created on target but it does not increase your damage dealt to the target, and Haunt's cooldown is not reset if the target dies.

**Expected behaviour:**

Besides deal damage to the target, Haunt should do all the other effects according to it's description.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 15 in the specialization of Afliction.
3. Pick the talent "Haunt" from level 15 branch.
4. Use "Haunt" and then any other damage spell.
5. Make the target dies after using Haunt

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=48181/haunt

**Comment by qxpf666** [comment]
Who has solved the problem？

**Comment by illfated** [comment]
Nobody in this repository, otherwise it would have been posted here
(proper code and not a hack, of course).

**Comment by qxpf666** [comment]
confirm

**Comment by illfated** [comment]
Which TC commit do you confirm this on?
(only "confirm" does not tell TC anything about your core)

**Comment by qxpf666** [comment]
https://github.com/TrinityCore/TrinityCore/commit/59edf6b100a9092cd530af6cab2b68a84ecd11f0

**Comment by Nyr97** [comment]
As of today, the spell increases the target's damage taken, but it is not reset upon dying while still holding the aura. Also, somehow it's set as a buff rather than a debuff.
