### ISSUE TITLE
Core/Script Warlock's Passive talent Backdraft has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19661]
**Description:**

The Passive "Backdraft"(ID 196406) (1st selection of talents in level 15) of the Warlock Class has an issue.

**Current behaviour:**

When you cast "Conflagrate" not happend nothing (Only inflict damage)

**Expected behaviour:**

When you cast "Conflagrate" should be activated the Buff "Backdraft" and reduced the cast time of "Incinerate" and "Chaos Bolt" by 30% for 5.1 sec.

**Steps to reproduce the problem:**

1. Create a character with the class "Warlock"
2. Select the specialization "Destruction" in level 10, and select the talent "Backdraft" in level 15
3. Cast "Conflagrate" on any target with the Talent passive "Backdraft".

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=196406/backdraft

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is not a talent anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
