### ISSUE TITLE
Core/Script Warlock's Spell Drain Life has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19668]
**Description:**

The spell "Drain Life" of the class "Warlock" has an issue.

**Current behaviour:**

Speciatization Destruccion:When you canalize the spell "Drain Life" cause damage and healing you but too generate "Soul Shard" in the time while during the canalization. Speciatization Afliction:When you canalize the spell "Drain Life" cause damage and healing you but the healing is a 600% from damage (more that it is in the spell description).

**Expected behaviour:**

Speciatization Destruccion:When you canalize the spell "Drain Life", only would be cause damage and healing you.(NOT generate "Soul Shard"). Speciatization Afliction: When you canalize the spell "Drain Life" cause damage and healing you, but the healing would be a 200% from damage.

**Steps to reproduce the problem:**

1. Create a class "Warlock" character.
2. (Speciatization Afliction)-Reach level 10 and select the Afliction Specialization
3. (Speciatization Destruccion)-Reach level 10 and select the Destruction Specialization
4. Cast "Drain Life" on any target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=234153/drain-life

**Comment by matanshukry** [comment]
Works as intended - can be closed.

1. The spell is now the same for both specs
2. The spell doesn't generat soul shard (on tc)
3. The spell heals 5 times more than damage done (damage 21, heals 105).
