### ISSUE TITLE
Core/Script Spell Light of the Protector has an issue. 

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19676]
**Description:**

The spell Light of the Protector of the Paladin class in the spec "Protection" has an issue. 

**Current behaviour:**

Once you use the spell Light of the Protector it only heals you for 30 HP. 

**Expected behaviour:**

Once you use the spell Light of the Protector it should heal the paladin for 30 % of its remaining health points. 

**Steps to reproduce the problem:**

1. Create a Paladin character.
2. Reach level 10 and choose the spec "Protection"
3. Reach level 40 in order to learn Light of the Protector.
4. Use the spell Light of the Protector.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=184092/light-of-the-protector

**Comment by aquadeus** [comment]
spell deprecated
