### ISSUE TITLE
Core/Script Talent Bastion of Light has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19677]
**Description:**

The spell talent Bastion of Light of the Paladin class in the spec "Protection" has an issue.

**Current behaviour:**

Once you use the spell talent Bastion of Light it does not restore 3 charges of Shield of the Righteous. 

**Expected behaviour:**

The spell talent Bastion of Light should restore 3 charges of Shield of the Righteous.

**Steps to reproduce the problem:**

1. Create a Paladin character.
2. Reach level 10 and choose the spec "Protection"
3. Then reach level 30 and choose the spell talent Bastion of Light.
4. Use Bastion of Light having already spent 2 charges of [Shield of the Righteous].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=204035/bastion-of-light

**Comment by aquadeus** [comment]
this spell is deprecated
