### ISSUE TITLE
Core/Script Talent Divine Intervention Paladin Retribution.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19683]
**Description:**

The retribution palandin talent Divine Intervention(id 213313) is not working properly

**Current behaviour:**

When you active the talent you automatically become immune to all attacks all the time.

**Expected behaviour:**

When you select the talent the cooldown of the Divine shield(id 642) is reduce by 20% and any attack which kill you instead reduces you to 20% of your maximun health and triggers Divine Shield (id 642)

**Steps to reproduce the problem:**

1. Create a Paladin
2. Reach level 10 and select retribution Spect
3. Reach level 90 and select the talent Divine Intervention(id 213313)

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=213313/divine-intervention

**Comment by Nyr97** [comment]
Invalid. The spell is not available anymore for paladins.

**Comment by Aokromes** [comment]
more than invalid, outdated
