### ISSUE TITLE
Core/Script Paladin Retribution talent Zeal Visual error.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19680]
**Description:**

Visual error with the buff of the talent zeal

**Current behaviour:**

When you select the zeal talent and you use the zeal spell on a target the buff that has to give you the spell is showing like a debuff

**Expected behaviour:**

When you use the zeal spell on a target you has to gain a buff called zeal.

**Steps to reproduce the problem:**

1. Create a paladin
2. Reach level 30 and select the Zeal talent inretribution spec.
3. Use the Zeal spell on a target

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=217020/zeal

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is correctly set as a buff on the paladin.
