### ISSUE TITLE
Core/Script Talent Devotion Aura presenting problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19685]
**Description:**

The spell talent Devotion Aura of the paladin "Holy" it is presenting problems.

**Current behaviour:**

When choosing Devotion Aura as talent point the aura is not activated. 

**Expected behaviour:**

The spell Devotion Aura when being chosen as talent point it should activate an aura that reduces 20% the damage of all the allies in 10 yards.

**Steps to reproduce the problem:**

1. create a player class paladin.
2. choose Devotion Aura as talent point in level 60 in holly spec

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=183425/devotion-aura

**Comment by Nyr97** [comment]
Invalid. This spell is not anymore a talent, but a current aura available for every paladin.

**Comment by Aokromes** [comment]
more than invalid, outdated
