### ISSUE TITLE
Core/Script Talent Fist of Justice presenting problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19687]
**Description:**

The passive power Fist of Justice of the paladin "Holy" presenting problems.

**Current behaviour:**

When using Judgment it doesn't reduce the time of remaining recharge of the power Hammer of Justice.

**Expected behaviour:**

The passive power Fist of Justice he/she makes that our Judgment it reduces 10 seconds the time of remaining recharge of Hammer of Justice.

**Steps to reproduce the problem:**

1. create a player class paladin.
2. reach level 45 and to choose Fist of Justice as talent point in holly spec.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=198054/fist-of-justice

**Comment by aquadeus** [comment]
deprecated, also the new spell (234299) works fine
