### ISSUE TITLE
Core/Script spell Talent Word of Glory.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19682]
**Description:**

The Paladin Retribution talent Word of Glory(id 210131) is not working

**Current behaviour:**

When you generates 3 charges of holy power and use the spell word of glory you are doing the animation and consuming the holy power but you are not healing yourself.

**Expected behaviour:**

When you have 3 charges of holy power and you use the spell of World of Glory you have to heal yourself and up to 5 friendly targets within 15 yards, you have a maximun of 2 charges.

**Steps to reproduce the problem:**

1. Create a Paladin
2. Reach level 10 and select Retribution Spect
3. Reach level 75 and select the talent Word of Glory (id 210131)
4. Generate 3 charges of holy power
5. Use the spell Word Of Glory

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=210191/word-of-glory

**Comment by aquadeus** [comment]
this spell is deprecated
