### ISSUE TITLE
Core/Script Talent Divine Purpose presenting problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19686]
**Description:**

The passive power Divine Purpose of the paladin "Holy" it is presenting problems 

**Current behaviour:**

When using Holy Shock and Light of Dawn these they don't restart the time of recharge of the same ones.

**Expected behaviour:**

When using Holy Shock and Light of Dawn they have 15% of probability of restarting their times of recharge.

**Steps to reproduce the problem:**

1. create a player class paladin.
2. reach level 75 and to choose Divine Purpose as talent point in holly spec.
3. prove 10 at least [Holy Shock] or [Light of Dawn]

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=197646/divine-purpose

**Comment by Nyr97** [comment]
Invalid. The spell has changed throughout the later expansions.

**Comment by Aokromes** [comment]
more than invalid, outdated
