### ISSUE TITLE
Core/Script Shield of Vengeance is not working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19696]
**Description:**

The paladin Spell Shield of Vengeance is not working proprely

**Current behaviour:**

When you use the Spell Shield of Vengeance the shield is poping with any damage and is not doing damage to the nearby enemies.

**Expected behaviour:**

When you use Shield of Vengeance it have to absorb 180 damage(level 32) for 15,2 sec and then when all the damage is a taken it has to explot dealing the same damage that has absorb distributed it in 8 nearby targets

**Steps to reproduce the problem:**

1. Create a paladin
2. Reach level 32
3. use the Spell Shield of Vengeance with a enemy and let him hit you

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=184662/shield-of-vengeance

**Comment by Naddley** [comment]
Absorption doesnt work too.
The Spell dont give the Paladin the Shield.

**Comment by illfated** [comment]
@Naddley : You might be correct, but on which core rev. hash have you verified this?

**Comment by aquadeus** [comment]
this can be closed
