### ISSUE TITLE
Core/Script Debuff Forbearance is not working at all.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19690]
**Description:**

The Paladin Debuff called Forbearance is not working

**Current behaviour:**

When you use the Divine Shield or Blessing of Protection you don´t have any debuff on you.

**Expected behaviour:**

When you use the spell Divene Shield or Blessing of Protection on you should have a debuff called Forbearance that not let you use the Divine Shield or Blessing of Protection on you for 30.3 seconds.

**Steps to reproduce the problem:**

1. Create a Paladin
2. Reach level 18
3. Use the spell Divine Shield

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=25771/forbearance

**Comment by Aokromes** [comment]
#18384
