### ISSUE TITLE
Core/Script Paladin Retribution Talent Blinding Light.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19692]
**Description:**

The paladin Talent Blinding Light of the Retribution specialization is not working

**Current behaviour:**

When you select the talent Blinding Light and then use the spell that has the same name near by a target you are doing the animation but nothing is happen

**Expected behaviour:**

When you use the spell Blinding Light you has to Emits dazzling light in all directions, blinding enemies within 10 yars, dealing holy damage and causing them to wander disoriented for 6 seconds. Non-holy damage will break the disorient effect

**Steps to reproduce the problem:**

1. Create a paladin
2. Reach level 10 and select Retribution Specialization
3. Reach level 45 and select the talent Blinding Light
4. Use the spell Blinding Light near by a enemy

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=115750/blinding-light

**Comment by offl** [comment]
00f6ca060f6a413b2e6c99e340c8f7b22e3df954

**Comment by tkrokli** [comment]
Closed by commit https://github.com/TrinityCore/TrinityCore/commit/00f6ca060f6a413b2e6c99e340c8f7b22e3df954 (via Pull Request **Scripts/Spells : Paladin Spell BlindingLight #20933** )
