### ISSUE TITLE
Core/Script spell Vendetta present problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19699]
**Description:**

The spell [Vendetta][id 79140] from class rogue presents problems. 

**Current behaviour:**

When you cast [Vendetta][id 79140] to the objective it doesn't increase you 30% of the damage inflicted to its. 

**Expected behaviour:**

When you cast [Vendetta][id 79140] to the objective it increase his damage by 30% and making it visible to you even through concealments such as stealth and invisibility.

**Steps to reproduce the problem:**

1. create a rogue character.
2. Select assassination spec
3. reach level 56.
4. apply it on the objective that you will attack.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=79140/vendetta

**Comment by Tate39** [comment]
Basicly every spell that applies aura name SPELL_AURA_MOD_SPELL_DAMAGE_FROM_CASTER seems broken.

**Comment by Nyr97** [comment]
Invalid. As of today, the spell works correctly.
