### ISSUE TITLE
Core/Script Spell Shield of the Righteous has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19697]
**Description:**

The spell of paladin protection “Shield of the Righteous” (ID: 53600) it doesn't operate correctly.

**Current behaviour:**

The spell “Shield of the Righteous” harms the that should but it doesn't reduce the received damage.

**Expected behaviour:**

The spell “Shield of the Righteous” it should reduce 26% the damage received for 4.5s.

**Steps to reproduce the problem:**

1. To be created a player of the class Paladin
2. Ascend until level 20
3. Choose the specialization “Protection”
4. Use the spell “Shield of the Righteous” in an enemy npc

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=53600/shield-of-the-righteous

**Comment by Nyr97** [comment]
As of today, the spell should apply a buff that increases your current armor. Tank class mitigations changed in BfA to increase armor values rather than reducing damage overall.
