### ISSUE TITLE
Core/Script Spell Templar´s Veredict has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19700]
**Description:**

The Paladin spell Templar´s Veredict is not working

**Current behaviour:**

When you use the Templar´s Veredict over a target the damage that you are doing is 0

**Expected behaviour:**

When you use on a target with the 3 charges of Holy Power should hit the target doing a holy damage of 107 (Level 10)

**Steps to reproduce the problem:**

1. Create a Paladin player
2. Reach Leve 10
3. Use the Crusader Striker 3 times to generate 3 charges of Holy Power
4. Use the Templar´s Veredict on a targert

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=85256/templars-verdict

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/18353
