### ISSUE TITLE
Core/Script spell Talent Greater Judgment is not working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19701]
**Description:**

The paladin Talent Greater Judgment is not working at all.

**Current behaviour:**

When you use the spell called Judgment whit the talent Greater Judgment is doing nothing no visual and no effect.

**Expected behaviour:**

With the talent your judgment have to deal damage to 2 additional nearby targert and when the target has less than 50% of life when you hit it the damage always has to be critical

**Steps to reproduce the problem:**

1. Create a paladin
2. Reach level 30
3. Select the talent Greater Judgment
4. Use the spell Judgment over a targert whit others enemys nearby and use again with the target has less than 50% of life

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=218178/greater-judgment

**Comment by Nyr97** [comment]
Invalid. As of today, this spell is not available for paladins anymore.

**Comment by Aokromes** [comment]
more than invalid, outdated
