### ISSUE TITLE
Core/Script spell Talent Ghostly Strike has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19705]
**Description:**

The spell talent [Ghostly Strike][id 196937] in the spec outlaw has an issue. 

**Current behaviour:**

When casting [Ghostly Strike][id 196937] on an enemy target, the spell does not increase 10 % of damage taken from your abilities to your current target.

**Expected behaviour:**

The spell talent [Ghostly Strike][id 196937] hits the target for an (?) amount of physical damage and it increases damage taken from your abilities for 15 seconds. 

**Steps to reproduce the problem:**

1. Create a Rogue character.
2. Choose the spec Outlaw.
3. Reach level 15.
4. Choose the spell talent [Ghostly Strike][id 196937].
5. Cast the spell talent [Ghostly Strike][id 196937] on an enemy target.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=196937/ghostly-strike

**Comment by Nyr97** [comment]
Invalid. As of today, the spell works correctly.
