### ISSUE TITLE
Core/Script spell Talent Agonizing Poison present problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19706]
**Description:**

The spell talent [Agonizing Poison][id 200802] is a poison. This poison should be applied on the enemy target once is hitten with a dagger that has the poison attatched to it. This spell talent has some issues. 

**Current behaviour:**

The spell talent [Agonizing Poison][id 200802] do not apply the poison on the enemy target once is hitten.

**Expected behaviour:**

The spell talent [Agonizing Poison][id 200802] should have a 30% chance of poisoning the enemy for 12 seconds and increase all damage done by your abilities 5.6%. Stacks up to 5 times on the target. 

**Steps to reproduce the problem:**

1. Create a Rogue character in Assesination spec.
2. Reach level 90.
3. Choose the spell talent [Agonizing Poison][id 200802].
4. Apply [Agonizing Poison][id 200802] to a dagger.
5. Attack an enemy target having [Agonizing Poison][id 200802] attatched on a dagger.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=200802/agonizing-poison

**Comment by aquadeus** [comment]
this spell does not exist anymore
