### ISSUE TITLE
Scripts/Spells: rogue spell Stealth does not work as expected

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19712]
**Description:**

The spell Stealth id: 1784 is complete broken.

**Current behaviour:**

When you use the spell nothing happens

**Expected behaviour:**

When you use the spell you enter in Stealth like the description of spell said.

**Steps to reproduce the problem:**

1. Create a PJ Rogue.
2. Reach Level 5.
3. Use the spell [Stealth] [id 1784]. 

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=1784/stealth

**Comment by ArcaneFox** [comment]
Update:
Stealth is working but after combat you can't use it for 5-20 seconds.

"Could not trigger spell 0 from aura 1784 proc, because the spell does not have an entry in Spell.dbc."

**Comment by tkrokli** [comment]
Maybe mark this issue as a duplicate and close it, if this is covered in any of the hits found by the search term "rogue stealth" + open issue?
 (https://github.com/TrinityCore/TrinityCore/search?q=rogue+stealth&state=open&type=Issues&utf8=✓ )
