### ISSUE TITLE
Core/Script the Roge spell Rupture presents problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19711]
**Description:**

The roge's spell "Rupture" (Spell ID: 1943) learned in the level 20 presents problems

**Current behaviour:**

When the Spell is used "Rupture" (Spell ID: 1943) it doesn't care the combos points that has accumulated the player always consumes 1 combo point and the damage it bases related to 1combo point

**Expected behaviour:**

The spell "Rupture" (Spell ID: 1943) it should consume the quantity of combos points that has accumulated the player until a maximum of 5 points and starting from the consumed points it will be the carried out damage. 

**Steps to reproduce the problem:**

1. Created a class player Roge
2. Take the Player to Lvl 20 and to learn the spell "Rupture" (Spell ID: 1943)
3. Enter in combat and when you arrives at the 5 combo point to use the spell "Rupture" (Spell ID: 1943)

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=1943/rupture

**Comment by offl** [comment]
#18348
