### ISSUE TITLE
Core/Script The passive spell Mastery: Starlight doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19718]
**Description:**

The passive spell Mastery: Starlight(ID:77492) given to Druid Balance at lv.78 has an issue

Mastery: Starlight: Increases Starfall and Starsurge damage, and the effect of Lunar, Solar, and Stellar empowerments by an additional (x)%

**Current behaviour:**

The spell doesn´t work, it never increases the damage of any spell

**Expected behaviour:**

After reach lv.78 and learn the spell Mastery: Starlight depending of your mastery points, it should increase (x)% Starfall and Starsurge damage, and the effect of Lunar, Solar, and Stellar empowerments

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.77 an choose the Balance Spec
3. Check Starfall and Starsurge damage, and the effect of Lunar, Solar, and Stellar empowerments
4. Reach lv.78, increase your mastery points and check Starfall and Starsurge damage, and the effect of Lunar, Solar, and Stellar empowerments

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=77492/mastery-starlight

**Comment by aquadeus** [comment]
this spell is deprecated
