### ISSUE TITLE
Core/Script spell Kidney Shot presents problems.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19710]
**Description:**

The roge's spell "Kidney Shot" (Spell ID: 408) learned in level 34 presents problems.

**Current behaviour:**

When the Spell is used "Kidney Shot" (Spell ID: 408) it doesn't care the combos points that one has accumulated, the spell always consumes 1 combo point and non stuns to the objective, but if it marks him the buff to the objective with the cooldown corresponding to combo points that one has accumulated.

**Expected behaviour:**

That the Spell "Kidney Shot" (Spell ID: 408) it should consume the quantity of combos points that has accumulated the player until a maximum of 5 points and starting from the consumed points it will be the time of duration of the stuns on the objective.

Duration of the stuns for combo points:
1 point : 2 seconds
2 points: 3 seconds
3 points: 4 seconds
4 points: 5 seconds
5 points: 6 seconds 

**Steps to reproduce the problem:**

1. created a class player Roge.
2. take the Player to Lvl 34 and to learn the spell "Kidney Shot" (Spell ID: 408)
3. enter in combat and when you arrives at the 5 I warp point to use the spell "Kidney Shot" (Spell ID: 408).

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=408/kidney-shot

**Comment by offl** [comment]
#18348
