### ISSUE TITLE
Core/Script The talent Displacer Beast has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19716]
**Description:**

The talent Displacer Beast(ID:102280) given to Druid Balance at lv.30 has an issue

Displacer Beast: Teleports you up to 20 yards forward activating Cat Form and increasing your movement speed by 50% for 2 sec.

**Current behaviour:**

When you use the talent it increase your movement speed by 50% for 2 sec, but it doesn´t activate Cat Form

**Expected behaviour:**

when you use the talent it should activate Cat Form and increase your movement speed by 50% for 2 sec

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.30 choose the Balance Spec and choose the talent Displacer Beast from lv.30 branch
3. Use the talent

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=102280/displacer-beast

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is not available for druids.
