### ISSUE TITLE
Core/Script The talent Incarnation: Guardian of Ursoc has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19728]
**Description:**

The talent Incarnation: Guardian of Ursoc(ID:102558) given to Druid Guardian at lv.75 has an issue

Incarnation: Guardian of Ursoc: An improved Bear Form that reduces the cooldown on all melee damage abilities and growl to 1,5 sec, causes Mangle to hit up to 3 targets, and increases armor by 15%. Lasts 30 sec you may freely shapeshift in and out of this improved Bear Form for its duration

**Current behaviour:**

When you use the talent it increase your armor 15% and causes Mangle to hit up to 3 targets, but the visual form doesn´t change and the spell´s Mangle and Thrash doesn´t reduces his cooldown´s to 1,5 sec instead they become instant.

**Expected behaviour:**

when you use the spell you should adopt an improved Bear Form increasing you armor 15% and reducing the cooldown of all your melee damage abilities and growl to 1,5 sec and causing that Mangle hit up to 3 targets

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.75, choose the Guardian Spec and the talent Incarnation: Guardian of Ursoc from lv.75 branch
3. Use the spell and check: your visual form and the cooldown of all your melee damage abilities

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=102558/incarnation-guardian-of-ursoc

**Comment by Nyr97** [comment]
As of today, the report is outdated in part:

- [ ] Mangle correctly hits up to 3 targets during the aura now.
- [ ] It doesn't increase armor (and it shouldn't now).
- [ ] It increases your health pool by 30 % now.
- [ ] It reduces the cooldown of some of your melee abilities (those included in Berserk) correctly.
- [ ] Bear skin changes on spell cast.

**Comment by mdX7** [comment]
> Bear skin changes on spell cast.

removed in 7.0.3
