### ISSUE TITLE
Core/Script The spell Survival Instincts has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19726]
**Description:**

The spell Survival Instincts(ID:61336) given to Druid Guardian at lv.36 has an issue

Survival Instincs: Reduces all damage you take by 50% for 6 sec. Max 2 Charges.

**Current behaviour:**

The spell doesn´t work, when you use it don´t reduce the damage you take, it increase very much the damage you take.

Example: Without the spell many npc´s lv.14 deals to me around 60 damage and after use the spell around 800 damage. This behaviour was checked with a lot of npc´s (elementals, beast and humanoids)

**Expected behaviour:**

when you use the spell all the damage you take will be reduce by 50%

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.36 an choose the Guardian Spec
3. Fight with diferents npc´s and check the damage taken
4. Use the spell Survival Instincs and Fight with diferents npc´s and check the damage taken

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=61336/survival-instincts

**Comment by Nyr97** [comment]
The spell script is outdated attached to the spell is outdated and causing this bug.
