### ISSUE TITLE
Core/Script The spell Stampeding Roar has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19724]
**Description:**

The spell Stampeding Roar(ID:77761) given to Druid Guardian at lv.50 has an issue

Stampeding Roar: Lets loose a wild roar, increasing the movement speed of all friendly players within 10 yards by 60% for 8 sec. Using this ability outside of Bear Form or Cat Form activates Bear Form

**Current behaviour:**

The spell works how the description shows but, when you use the spell outside Bear Form or Cat Form it doesn´t activate Bear Form

**Expected behaviour:**

when you use the spell it should increase the movement speed of all friendly target´s within 10 yards 60% for 8 sec and when you use it outside Bear Form or Cat Form it should activate Bear Form

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.50 and choose the Guardian Spec
3. Use the spell Stampeding Roar outside Bear Form and Cat Form

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=106898/stampeding-roar

**Comment by Nyr97** [comment]
As of today, the spell works correctly.
