### ISSUE TITLE
Core/Script The passive spell Ysera's Gift is not working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19720]
**Description:**

The druid's passive spell Ysera's Gift (ID: 145108) learned at level 34 in the specialization of Restauration, is not working.

Ysera`s Gift (passive): Heals you for 3% of your maximum health every 5 sec. If you are at full health, an injured party or raid member will be healed instead.

**Current behaviour:**

The passive spell does not heal at all, it does nothing, it has no effects.

**Expected behaviour:**

The spell should heal once every 5 sec the 3% of your maximum health, or heal an ally according to it`s description.

**Steps to reproduce the problem:**

1. Create a Restauration Druid Character.
2. Reach level 34 in the specialization of Restauration.
3. Get injured and wait 5 sec. or get near an injured party or raid member and wait 5 sec.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=145108/yseras-gift

**Comment by Nyr97** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/pull/29148.
