### ISSUE TITLE
Core/Script The spell Thick Hide doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19725]
**Description:**

The passive spell Thick Hide(ID:16931) given to Druid Guardian at lv.34 has an issue

Thick Hide (passive): Reduces all damage taken by 6%

**Current behaviour:**

The passive effect doesn´t work, all damage taken is not reduced

**Expected behaviour:**

All damage taken will by reduce by 6%

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.33 an choose the Guardian Spec
3. Check the damage you take from diferents npc´s
4. Reach lv.34 and check the damage you take from diferents npc´s

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=16931/thick-hide

**Comment by Nyr97** [comment]
As of today, the spell works correctly as SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN is implemented.
