### ISSUE TITLE
Core/Script Talent Brambles doesn´t work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19734]
**Description:**

The talent Brambles (Spell ID: 203953) given to Guardian Druid in lv.15 has an issue Brambles: Sharp brambless protect you, absorbing and reflecting up to (x) damage from each attack

**Current behaviour:**

The talent doesn´t work, don´t absorb or reflect any damage when you are under attack

**Expected behaviour:**

when you are under attack you should absorb and reflect (x) damage from each attack

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach to lv.15, choose Guardian spec, and select the talent Brambless
3. Fight with any NPC and check the damage, then unselect the talent Brambless and check the damage again

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=203953/brambles

**Comment by aquadeus** [comment]
Is this spell already fixed?

**Comment by mdX7** [comment]
yep here: https://github.com/TrinityCore/TrinityCore/commit/183f719f4e1fa975de28acdfc027ff3f23789fb7
