### ISSUE TITLE
Core/Script talent Warrior of Elune it´s not fully working.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19738]
**Description:**

Talent "Warrior of Elune" (ID: 202425) it´s not fully working 

**Current behaviour:**

The "balance druid" in level 15 can choose the talent "Warrior of Elune"(ID: 202425). Accord to the talent description, Yor next 2 "Lunar stikes" (ID: 194153) are instant cast. When activate the spell, put on the corresponding buff but only one "Lunar stike" are instant then, the buff disapear.

**Expected behaviour:**

When activate the spell "Warrior of Elune" your next 2 "Lunar stikes" are instant cast.

**Steps to reproduce the problem:**

1. Create a player druid
2. reach level 15
3. select the talent "Warrior of Elune"
4. activate the spell "Warrior of Elune"
5. launch the spell "Lunar stike" twice to an enemy

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=202425/warrior-of-elune

**Comment by Nyr97** [comment]
As of today, the spell works correctly, but the charges are not consumed.
