### ISSUE TITLE
Core/Script Spell thrash cannot by activate.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19739]
**Description:**

Spell "thrash" (ID: 106832) cannot by activate

**Current behaviour:**

The "feral druid" and the "guardian druid" in level 10 learn the spell "thrash"(ID: 106832). Accord to the spell description, thrash all nearby enemies, dealing immediate physical damage and periodic bleed damage. Actually the spell cannot by activate.

**Expected behaviour:**

The spell must by activated, thrash all nearby enemies, dealing immediate physical damage and periodic bleed damage.

**Steps to reproduce the problem:**

1. Create a player druid
2. reach level 10
3. Select spect "feral" or "tank"
4. select an enemy and activate the spell "thrash"

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=106832/thrash

**Comment by Nyr97** [comment]
As of today, the spell works correctly.
