### ISSUE TITLE
Core/Script Spell Mangle has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19733]
**Description:**

The Spell Mangle (spell ID: 33917) given to Feral and Guardian Druid has an issue

**Current behaviour:**

When you use the spell it doesn´t deal the damage that the description show, it does less damage that it should do, the damage diference growns up whith every level you get

**Expected behaviour:**

when you use the spell, you should do the damage that appear in the spell description

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach to lv.10 an choose the Guardian Spec
3. Check the damage that the spell Mangle should do in the description
4. Use the spell in a NPC and check the damage
5. Reproduce the steps 3 and 4 increasing you lv 10 by 10

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=33917/mangle

**Comment by Nyr97** [comment]
As of today, the spell works correctly.
