### ISSUE TITLE
Core/Sript Spell Maul has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19732]
**Description:**

The Spell Maul (spell ID: 6807) given to Guardian Druid has an issue

**Current behaviour:**

When you use the spell it doesn´t do the damage that the description show, it does more damage that it should do, the damage diference growns up whith every level you get

**Expected behaviour:**

when you use the spell, you should do the damage that apper in the spell description

**Steps to reproduce the problem:**

1. Create a Night Elf Druid character
2. Reach to lv.10 an choose the Guardian Spec
3. Check the damage that the spell Maul should do in the description
4. Use the spell in a NPC and check the damage
5. Repeat the steps 3 and 4 increasing you lv 10 by 10

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=6807/maul

**Comment by Nyr97** [comment]
As of today, the spell works correctly.
