### ISSUE TITLE
Core/Script Spell Ferocius Bite has an issue.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19743]
**Description:**

The spell Ferocius Bite ID:22568 when it activates he consumes only one point of combo and therefore he inflicts the damage pertaining to an alone point of combo.

**Current behaviour:**

To the hour to use it only spend one point of combo and inflict the damage of one.

**Expected behaviour:**

When it is used he should consume the quantity of points of combo that he possesses and therefore inflicting the damage assigned to each point of combo.

**Steps to reproduce the problem:**

1. Creating for oneself a Druid
2. Reach level 10
3. Use Talent Feral's spec

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=22568/ferocious-bite

**Comment by offl** [comment]
Correct name: Ferocious Bite
Possible the same as #18348. Also similar bugs were reported in #18840:
> - Ferocious Bite - Doesn't consume combo points
> - Maim - Doesn't consume combo points

**Comment by tkrokli** [comment]
I concur. This issue describes the same problem as **[master] Rogue finishing moves will always only consume one combo point. #18348** and should be solved the same way as that issue. In comment https://github.com/TrinityCore/TrinityCore/issues/18348#issuecomment-263835948 Shauren stated "That should be directly related to consuming 1 CP" regarding the previous comment https://github.com/TrinityCore/TrinityCore/issues/18348#issuecomment-263830018 about druids having the same kind of issue.

**Comment by oXL0C0Xo** [comment]
f75b98020c1b Ferocious Bite triggers no effect, has no cooldown, and consumes no combo points.

**Comment by illfated** [comment]
@oXL0C0Xo : probably better to mention that in https://github.com/TrinityCore/TrinityCore/issues/18840 (since https://github.com/TrinityCore/TrinityCore/issues/18348 was closed with a solution).

If need be, open a new ticket and use the full issue template to describe the issue details properly.
