### ISSUE TITLE
commit b52949aa1f156fb58c58ab18d9565af858361d24 breaks build

### ISSUE THREAD

**Issue by liszt** [TrinityCore/TrinityCore#19746]
commit b52949aa1f156fb58c58ab18d9565af858361d24 breaks build

**Current behaviour:**

Linux build fails with error:
[ 39%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/QueryHandler.cpp.o
/home/WoD/source/src/server/game/Handlers/QueryHandler.cpp: In member function ‘void WorldSession::HandleQuestPOIQuery(WorldPackets::Query::QuestPOIQuery&)’:
/home/WoD/source/src/server/game/Handlers/QueryHandler.cpp:375:95: error: no matching function for call to ‘std::vector<WorldPackets::Query::QuestPOIBlobPoint>::push_back(<brace-enclosed initializer list>)’
                         questPOIBlobData.QuestPOIBlobPointStats.push_back({ point.X, point.Y });
                                                                                               ^
In file included from /usr/include/c++/6.3.1/vector:64:0,
                 from /usr/include/c++/6.3.1/queue:61,
                 from /home/WoD/source/src/common/Common.h:30,
                 from PrecompiledHeaders/gamePCH.h:3:
/usr/include/c++/6.3.1/bits/stl_vector.h:914:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = WorldPackets::Query::QuestPOIBlobPoint; _Alloc = std::allocator<WorldPackets::Query::QuestPOIBlobPoint>; std::vector<_Tp, _Alloc>::value_type = WorldPackets::Query::QuestPOIBlobPoint]
       push_back(const value_type& __x)
       ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_vector.h:914:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const value_type& {aka const WorldPackets::Query::QuestPOIBlobPoint&}’
/usr/include/c++/6.3.1/bits/stl_vector.h:932:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = WorldPackets::Query::QuestPOIBlobPoint; _Alloc = std::allocator<WorldPackets::Query::QuestPOIBlobPoint>; std::vector<_Tp, _Alloc>::value_type = WorldPackets::Query::QuestPOIBlobPoint]
       push_back(value_type&& __x)
       ^~~~~~~~~
/usr/include/c++/6.3.1/bits/stl_vector.h:932:7: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘std::vector<WorldPackets::Query::QuestPOIBlobPoint>::value_type&& {aka WorldPackets::Query::QuestPOIBlobPoint&&}’
[ 39%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/QuestHandler.cpp.o

**Expected behaviour:**

Build should complete without errors

**Steps to reproduce the problem:**

1. Pull commit 26305cd5fb6c967adde5c81f9732289bf7d6d433
2. compile Trinitycore

**Branch(es):**

master

commit 26305cd5fb6c967adde5c81f9732289bf7d6d433 

**TDB version:** N/A

**Operating system: Fedora core 25

**Comment by HannibalRoG** [comment]
I can confirm that on Windows 10

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void std::vector<WorldPackets::Query::QuestPOIBlobPoint,std::allocator<_Ty>>::push_back(const WorldPackets::Query::QuestPOIBlobPoint &)': cannot convert argument 1 from 'initializer list' to 'WorldPackets::Query::QuestPOIBlobPoint &&'	game	D:\Repositorios\6.x\src\server\game\Handlers\QueryHandler.cpp	375

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ed986a416a43d57fa5695b732dd344c866ce4cfd
