### ISSUE TITLE
Core/Script: Druid spell Starsurge can not be activated

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19740]
**Description:**

Spell "starsurge" (ID: 78674) cannot by activate

**Current behaviour:**

The "balance druid" in level 10 learn the spell "Starsurge"(ID: 78674). Accord to the spell description, deal 136 astral damage and also grants you Lunar and Solar empowerments, which increase your next "lunar strike" (ID: 194153) and "Solar wrath" (ID: 190984) by 20% respectively. The spell cannot be activated

**Expected behaviour:**

The spell must by activated, deal 136 astral damage and also grants you Lunar and Solar empowerments, which increase your next "lunar strike" (ID: 194153) and "Solar wrath" (ID: 190984) by 20% respectively

**Steps to reproduce the problem:**

1. Create a player druid
2. reach level 10
3. select spect "balance"
4. select an enemy and activate the spell "starsurge"

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=78674/starsurge

**Comment by MartGon** [comment]
I've tested this spell on 0c9e338 and I think that it works correctly, it can be casted and it triggers the buffs correctly. Maybe you couldn't activate it because it needs 40 astral power to be casted, but I don't know exactly if that was the cause.

**Comment by tkrokli** [comment]
Slight correction:
```
Spell Details
School  Nature, Arcane
Cost    400 Astral Power
```

**Comment by MartGon** [comment]
Yes, my bad. The ingame tooltip says 40 though, as 100 is the maximum astral power resource.

**Comment by tkrokli** [comment]
> [ ... ] The ingame tooltip says 40 though, as 100 is the maximum astral power resource.

Is this from retail or from TC source game? Anyway, if 100 is max (if it works the same way as rogue/hunter Energy, it makes sense), I wonder where wowhead gets the value 400 from.

**Comment by MartGon** [comment]
Well on my first comment, it was from TC but I've looked on retail and the criteria is the same. The ingame tooltip says 40 astral power on both. Don't know why wowhead added an extra zero.

**Comment by P-Kito** [comment]
I found a weird bug with those spells displaying "400 ressource cost". When I joined Arenabattle and added the pvp stat templte aura, the spell cost 400 ressource and I dont know why. Same for Elemental shaman spell Earthshock which took 200 maelstrom as maximum lol.

**Comment by tkrokli** [comment]
Interesting. So the wowhead.com value 400 is correct after all, then. There must be something else than % used for that resource. Thanks for the feedback.

**Comment by Nyr97** [comment]
Invalid. As of today, this spell is not supposed to trigger any Eclipse status or empowerment.

**Comment by Aokromes** [comment]
more than invalid, outdated
