### ISSUE TITLE
[3.3.5]Console error

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19745]
**Description:** Console sql error

Description of the problem or issue here.: start server and see an error in console

**Current behaviour:**when you start server you see in console an error.

Tell us what happens. i start server, and see a error

**Expected behaviour:** error should not be there.

Tell us what should happen instead.it should not trow an error

**Steps to reproduce the problem:**
compile clean core and DB, then start server, i saw this error

1. Step 1 compiled a clean core and database.  
2. Step 2 start up the server
3. Step 3 in console i see this error

```
2017-05-10_08:31:04 ERROR [sql.sql] [1055] Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'trinity_char.gi.guid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
2017-05-10_08:31:04 ERROR [sql.sql] Unhandled MySQL errno 1055. Unexpected behaviour possible.
```

**Branch(es):**

3.3.5, 
**TC rev. hash/commit:** 
TrinityCore rev. e036d2232dae+ 2017-05-10 02:41:50 +0200 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63
**Operating system:** ubuntu server 1604 LTS

**Comment by Aokromes** [comment]
cannot reproduce, i wonder if it's because your custom odifications.

**Comment by Aokromes** [comment]
OK. it looks to be mysql 5.7 thing.
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by dikkedeur** [comment]
the only custom thing is the ac1 patch @Aokromes and that doesnt involve the console error.

**Comment by tkrokli** [comment]
MySQL 5.7 is not recommended and also warned about in the TC wiki:

3. MySQL Server Community Edition (Use the most recent 5.6.x version or 5.5 with mysql server configuration, DON'T use 5.7 version unless you know VERY WELL what are you doing, you will have issues with 5.7)
https://trinitycore.atlassian.net/wiki/display/tc/Windows+Requirements

(By all means, if you want to document how to make MySQL 5.7 work without problems with TC source, be our guest.)

**Comment by dikkedeur** [comment]
you talk about windows @tkrokli 
now back on the other subject, on TC it also says that recommended is for linux

https://trinitycore.atlassian.net/wiki/display/tc/Linux+Requirements

MySQL ≥ 5.3.0
Tested for Debian 8.4.0 and Ubuntu 16.04.
now the fun part is 16.04 comes with mysql 5.7 asfaik.

**Comment by Aokromes** [comment]
Yeah it needs to be core fixed (that's why i removed invalid-cannotreproduce thing)

**Comment by Aokromes** [comment]
```
../src/server/game/Instances/InstanceSaveMgr.cpp:    CharacterDatabase.DirectExecute("DELETE gi.* FROM group_instance     AS gi LEFT JOIN groups     AS g ON gi.guid = g.guid WHERE g.guid IS NULL");
../src/server/game/Instances/InstanceSaveMgr.cpp:    CharacterDatabase.DirectExecute("DELETE i.* FROM instance AS i LEFT JOIN character_instance AS ci ON i.id = ci.instance LEFT JOIN group_instance AS gi ON i.id = gi.instance WHERE ci.guid IS NULL AND gi.guid IS NULL");
../src/server/game/Groups/GroupMgr.cpp:        QueryResult result = CharacterDatabase.Query("SELECT gi.guid, i.map, gi.instance, gi.permanent, i.difficulty, i.resettime, COUNT(g.guid) "
../src/server/game/Groups/GroupMgr.cpp:            "LEFT JOIN character_instance ci LEFT JOIN groups g ON g.leaderGuid = ci.guid ON ci.instance = gi.instance AND ci.permanent = 1 GROUP BY gi.instance ORDER BY gi.guid");

**Comment by ariel-** [comment]
This one:

```sql
SELECT gi.guid, i.map, gi.instance, gi.permanent, i.difficulty, i.resettime, COUNT(g.guid)
            FROM group_instance gi INNER JOIN instance i ON gi.instance = i.id 
            LEFT JOIN character_instance ci LEFT JOIN groups g ON g.leaderGuid = ci.guid ON ci.instance = gi.instance AND ci.permanent = 1 GROUP BY gi.instance ORDER BY gi.guid
```

It's the only referencing gi.guid and with a GROUP BY statement
