### ISSUE TITLE
[3.3.5] Time Watchers are not in caverns of time.

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19744]
**Description:** The Npc Time Watcher that are normally in the caverns of time, are after a server restart not in the caverns of time anymore, but on the surface in tanaris.
After some time they drop through the ground, so it takes roughly 15 minutes or longer before they are not on the surface anymore

**Current behaviour:** see the describtion.

Tell us what happens.:
also mentioned in the describtion, after server restart those time watchers are not at the right place.

**Expected behaviour:**they should be in the caverns and not on the surface.

Tell us what should happen instead.they should be in the right spot.

**Steps to reproduce the problem:**

Step 1 npc id= 19918
2. restart server.. go to tanaris around the caverns of time, you will see those time watchers above the ground instead of the cavern.
3. Step 3

![schermafbeelding 2017-05-10 om 08 35 28](https://cloud.githubusercontent.com/assets/11842306/25886192/c8e3e44e-355c-11e7-9fc8-27872df3f75f.png)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e036d2232dae+ 2017-05-10 02:41:50 +0200 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:**ubuntu server 16.04 LTS

**Comment by Killyana** [comment]
You're using a different SAI that despawn the npcs, this issue happen only after a respawn, and it's related to the inhabittype.

**Comment by Killyana** [comment]
Looks like mmaps issue.

**Comment by Ovahlord** [comment]
Probably a mmaps issue. Cuz the ground finder is normalizing the Z-position from a higher point and goes down until it finds a ground. Since the cave ground is below this ground it is most likely that the Z position stops at the surface.

**Comment by Killyana** [comment]
I added CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING to this npcs but the issue still happen, also I tested with mmap.enablePathFinding = 0 and nothing changed.

**Comment by Golrag** [comment]
In ```RandomMovementGenerator<Creature>::SetRandomLocation(Creature* owner)``` ```owner->MovePositionToFirstCollision(position, distance, angle);``` Gets called. Then ```destz = NormalizeZforCollision(this, destx, desty, pos.GetPositionZ());``` is called which results in unintend destz
Note:
```

**Comment by ccrs** [comment]
yeap, thats the reason

old code simply returned on air units if collision existed, port back that behaviour?

**Comment by r00ty-tc** [comment]
@ccrs not looked at referenced code, since I'm on a phone. But for waypoint movement, the z is verified for each point there. For point movement I guess it assumes you verified z yourself. For random movement, it's finding a new x/y a random distance and direction from original xyz. So it must find the new correct z for that new position. 

If the creatures are always finding themselves on the world outside surface it sounds like it's only using map height, or map height is overriding vmap floor z?

**Comment by ccrs** [comment]
the problem is a validation on those methods: if z is within a tolerance level (upper or lower) it gets corrected to the floor/ground value
(example to show the logic, not the real values: if its within (value - 1.f, value +1.f) it chooses value)

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25

**Comment by tkrokli** [comment]
TrinityCore rev. 527ef19ae8a0 2017-12-29 20:04:04 -0300 (3.3.5 branch) (Win64, Release, Static)

Time Watchers can now be seen flying high up underneath the ceiling of Caverns of Time (main cavern).

**Comment by Killyana** [comment]
Confirm, it fixed after https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25
