### ISSUE TITLE
DB/Quest: Your Continued Support (11548) does not accept Required Money

### ISSUE THREAD

**Issue by vato312199** [TrinityCore/TrinityCore#19750]
**Description:** [Anchorite Ayuri](http://www.wowhead.com/npc=25112/anchorite-ayuri) at [Sun's Reach Sanctum](https://wow.gamepedia.com/Sun%27s_Reach_Sanctum) in [Isle of Quel'Danas](https://wow.gamepedia.com/Isle_of_Quel%27Danas) wants you to donate 10 gold.
Required money: 10 gold
- http://www.wowhead.com/quest=11548/your-continued-support
- http://www.wowhead.com/npc=25112/anchorite-ayuri

**Current behaviour:**

[Quest 11548](http://www.wowhead.com/quest=11548/your-continued-support) doesn't want to take 10 gold at the completion of the quest.
- https://wow.gamepedia.com/Quest:Your_Continued_Support

**Expected behaviour:**

A warning sign should appear, that at the end of the quest 10 gold will be donated. 
Screen: http://imgur.com/a/eFtNT

**Steps to reproduce the problem:**

1. http://www.wowhead.com/quest=11548/your-continued-support
2. .q add 11548 and complete him

**Branch(es):** Master

**TC rev. hash/commit:** 7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  720.00 + updates

**Operating system:** Win10

**Comment by Daniel25** [comment]
Posible fix:
DELETE FROM `gossip_menu_option` WHERE `menu_id`=9115 AND `id`=0;
INSERT INTO `gossip_menu_option` VALUES (9115,0,0,'',0,0,0,0,0,0,100000,'Completing this quest requires the following amount of gold. Are you sure you want to complete this quest?',0,0);

**Comment by Shauren** [comment]
Thats not a possible fix, thats a giant hack (that frame on screenshot clearly is not a gossip)

**Comment by Daniel25** [comment]
Umm ok, The id of gossip_menu is the correct ( I checked it in the db) but its missing gossip_menu_option in the db...dunno so the way to fix it, sorry. I thought that you only have to get a window with the donation money...

**Comment by Shauren** [comment]
The window is supposed to show when you click on the "Complete quest" button, not on gossip

**Comment by tkrokli** [comment]
Good point. I see that `quest_template` contains `RewardMoney` = `-100000` which in theory should produce that dialog, so maybe this isn't a DB issue and instead is a core issue?

**Comment by nubqt** [comment]
The issue at hand is that the 'Continue' button is greyed out.

<img width="1378" alt="screen shot 2017-11-13 at 1 42 56 am" src="https://user-images.githubusercontent.com/33535711/32712720-130e7012-c814-11e7-9969-fadd3d42b943.png">

**Comment by tkrokli** [comment]
Hmm. Looks like something @malcrom talked about in some other quest gossip issue way back in 6.x

**Comment by aquadeus** [comment]
this is now working
