### ISSUE TITLE
[7.2] cant register arenas

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#19757]
**Description:**

cant register any arenas

**Branch(es):**
7.2,  master
**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/9299e9bde087af7e5d777d5a55a3b79d2b63c48e

**Comment by Caydan** [comment]
Thank you for this very revealing issue. It has to be a huge bunch of work to write such detailed.

**Comment by Shauren** [comment]
Well yeah, registering arena teams was removed 2 expansions ago...
