### ISSUE TITLE
[3.3.5] Faction bug

### ISSUE THREAD

**Issue by Residentik** [TrinityCore/TrinityCore#19768]
Description:
https://github.com/TrinityCore/TrinityCore/commit/15a207fcac15d336b848f9759f75386e12b6a35f
After this commit i found strange bug. For example - boss Midnight in Karazhan.
Npc 16151 have faction 7 (this faction don't have any friendly/hostile factions in dbc files), when you start attacking midnight by first player, and after re-aggro boss to second player (by abilities), this check
(https://github.com/TrinityCore/TrinityCore/commit/15a207fcac15d336b848f9759f75386e12b6a35f#diff-f3f953a63e2a008d22de69cb68f735c4R2292) is failing and boss entering evade mode. I think all npc with this faction can have this problem, or, with simular factions.

If creature in AGRESSIVE react state, then traget can't switch target to new, and continue attacking first target using "// search nearby enemy before enter evade mode" case.

Can you please review this situation ? if need i can record video. Can be reprodusing on last rev (3.3.5 branch). In additional you can check this using 20774 npc.

Branch(es):
3.3.5

TC rev. hash/commit:
(last rev)
TrinityCore rev. edd2c1c03995 2017-05-17 07:16:46 +0300 (master branch) (Unix, Release, Static) (worldserver-daemon)

**Comment by Cannix** [comment]
Already happened before the mentioned commit.

And yes, its a general issue. NPC 26363 can't change its target either.
Happens because GetVictim() on player returns null.

Maybe something like
```
    if (this->IsInCombatWith(target))
        return true;
```
would be possible? If the creature is already infight with the target it should be acceptable?
