### ISSUE TITLE
Headless server without prompt

### ISSUE THREAD

**Issue by habovh** [TrinityCore/TrinityCore#19763]
**Description:**

I've been using `systemd` to manage `authserver` and `worldserver` for a week or so.
I realised today that these process actually really CPU intensive (event without any player, see screenshot), and I think this might be related to the fact that the `worldserver` process is spamming standard output with the default prompt over and over again:

```
● worldserver.service - TrinityCore World Server
   Loaded: loaded (/etc/systemd/system/worldserver.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-05-15 17:40:39 CEST; 5min ago
 Main PID: 26537 (worldserver)
   CGroup: /system.slice/worldserver.service
           └─26537 /home/wow/server/bin/worldserver

May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
May 15 17:46:12 ns3075730.ip-91-121-184.eu worldserver[26537]: TC>
```

![capture d ecran 2017-05-15 a 17 36 31](https://cloud.githubusercontent.com/assets/4186230/26066478/4a9a0bd8-3997-11e7-9671-45173830c631.png)

## Request 
Could it be possible to have a `--headless` on the `webserver` binary that completely disables the user input prompt? The only way to interact with the server would now be using telnet.

I could simply redirect output to `/dev/null`, but then I would not have any logging output from the server start for example.

## Server data

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 
TrinityCore rev. 231ec8331b2b 2017-04-28 19:12:48 -0300 (3.3.5 branch) (Unix, Release, Static)
**Operating system:** Ubuntu 16.04 (Xenial)

**Comment by DDuarte** [comment]
This*100, TC needs a daemon mode.

**Comment by Shauren** [comment]
Disable the cli thread - there is a config for it already
`Console.Enable`

**Comment by habovh** [comment]
Oh well that's exactly what I needed @Shauren! But why not have it as a parameter when launching the webserver? It would make sense to me... Any thoughts on this?

**Comment by gmillerd** [comment]
Why is your prompt in your logging? I have console enabled for all my servers and run systemd and don't see this interaction in the logs at all. When i want to console, i disable the service and start it manually.

```
[Unit]
Description=tc master (worldserver)
Requires=mysql.service

[Service]
Type=simple
User=wow
Group=wow
WorkingDirectory=/home/wow/games/builds/tc/master/bin
ExecStart=/home/wow/games/builds/tc/master/bin/worldserver -c /home/wow/games/builds/tc/master/etc/worldserver.conf
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by habovh** [comment]
@gmillerd well, if you do `systemctl status worldserver`, you'll likely see a bunch of trinity console prompts. If so, this means they are logged onto `syslog` (or some other logging file), otherwise you wouldn't be able to see them in the reduced log output from `systemctl status`. This adds an unnecessary overhead to the system IO, causing increased CPU usage and/or reduced disk speed and longevity.
In that case, you should disable the console when running as a service, and use telnet to access the console whenever you need to.

**Comment by gmillerd** [comment]
@habovh When query status and there are no TC> prompts produced in the logs. I don't have any content in syslog, just the files. To be clear, "No TC> in the logs"

'find $HOME/games/builds/*/*/logs/ -type f -name "*.log" -print0 | xargs -0 tail -F'
'systemctl status tc-*.service'

I of course see the last log lines, but they are unrelated.

**Comment by habovh** [comment]
@gmillerd That's weird then, because I'm basically doing the exact same thing as you are! Here's my service description:

```
[Unit]
Description=TrinityCore World Server

[Service]
WorkingDirectory=/home/wow/server
User=wow

ExecStart=/home/wow/server/bin/worldserver

ExecReload=/bin/kill -HUP $MAINPID; /home/wow/server/bin/worldserver

ExecStop=/bin/kill -HUP $MAINPID

RestartSec=10s

Restart=always

[Install]
WantedBy=multi-user.target
```

By the way, I saw you added `Requires=mysql.service`, I'll need to add it to my service as well :)

**Comment by gmillerd** [comment]
I have only console and soap running on my servers. I am not sure if you have any ra/telnet stuff running that might show those prompts. Maybe the right before the first TC> (related to remote access) is a clue to what is doing that?

I get that sort of activity with this (not that I do this), but I just did to see if empty prompts would occur.

`while true; do echo; done | ./worldserver`

**Comment by habovh** [comment]
Well, maybe. In any case, I truly didn't want the actual process to be able to be interactive, so the `Console.Enable` setting as @Shauren pointed out works for me. The whole point here was just to discuss about a possible `--daemon` or `--headless` option for the actual executable, regardless of the config file.

**Comment by Thulium-Drake** [comment]
I've already fixed this issue when I packaged the software (see: https://community.trinitycore.org/topic/13013-how-to-install-using-pre-compiled-packages/)

The solution is basically to disable the console in the config (which also disables the prompt in the logs). But in order to control the server, you need to enable the telnet console.

Feel free to check out that forum post and the packages :-)

**Comment by VictorQueiroz** [comment]
Recently I've had 5GB of stdout in less than an hour, not sure if that's a bug or whatnot. @Shauren suggestion fix the problem avoiding the TC> flooding.
