### ISSUE TITLE
Extract Error Take2

### ISSUE THREAD

**Issue by FamousL** [TrinityCore/TrinityCore#19765]
WOW Version/BUILD

7.20/ 24015

Description:

Cannot pull datafiles from 7.20 client

Current behaviour:

locale files are not found when attempting to mapextract from directory where wow.exe/etc reside
If this is a crash, post the crashlog (upload to https://gist.github.com/).

Expected behaviour:

mapextract finds datafiles

Steps to reproduce the problem:

1) build from master
2) install a clean copy of wow (from the website, latest client)
3) copy latest WOW client to server
4) run mapextract on latest WOW client files (in the directory where the wow.exe files reside)
5) PROFIT!
Branch(es):

master

TC rev. hash/commit:

f475394

--LOG---
Listing of directory where Extractor was run: https://gist.github.com/FamousL/dc8373ef0430caf745e22e292849fa94
```
/home/trinity/newserver/bin/mapextractor
TrinityCore rev. f4753944684d 2017-05-15 15:46:26 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale enUS
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale koKR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale frFR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale deDE
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale zhCN
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale zhTW
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale esES
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale esMX
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale ruRU
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale ptBR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale itIT
No locales detected
TDB version: N/A
```
Operating system: Fedora Core 25

**Comment by tkrokli** [comment]
Any chance you could compile only the tools (CMake options) on Windows, extract on a Windows file system and then copy/upload the resulting folders to your Linux server? (I'm currently unable to run a replication test in a Linux environment.)

**Comment by FamousL** [comment]
Unfortunately I do not have the ability to build anything in windows, as I do not have a windows environment to build on (wow is run through Wine)

**Comment by FamousL** [comment]
.build.info did not move during my copy for processing, (it is missing in the directory listing I posted) manually moving it fixed the issue.
