### ISSUE TITLE
[3.3.5] SAI Burning blade Cultist

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19760]
**Description:** 

Burning blade cultist (  3199  ) summons the wrong Imp as pet.

**Current behaviour:**

Currently the npc casts the wrong imp as pet, the pet has 1100 HP in a starter zone..

**Expected behaviour:**

Burning blade cultist should summon correct imp as pet

**Steps to reproduce the problem:**

1. burning blade cultist ( npc=3199  ) summons imp ( spell= 11939 )
2. Imp has too high HP ( around 1200 ) and his fireball hits really hard
3. Step 3

POSSIBLE SOLLUTION:

change the spell in smartai to another summon imp spell that matches the level and starter zone

```
UPDATE `smart_scripts` SET `action_param1` = '688' WHERE `entryorguid` = 3199 AND `source_type` = 0 AND `id` = 0 AND `link` = 0;
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e036d2232dae+ 2017-05-10 02:41:50 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:** ubuntu server 16.04

**Comment by offl** [comment]
#281

**Comment by Killyana** [comment]
The spell is the good one: http://fr.wowhead.com/npc=3199/sectateur-de-la-lame-ardente#abilities
The problem is the scaling system for pets.
