### ISSUE TITLE
Data Extraction failure?

### ISSUE THREAD

**Issue by FamousL** [TrinityCore/TrinityCore#19764]
**WOW Version/BUILD**

 7.20/ 24015

**Description:**

Cannot pull datafiles from 7.20 client

**Current behaviour:**

locale files are not found when attempting to mapextract
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

mapextract finds datafiles

**Steps to reproduce the problem:**

1) build from master
2) install a *clean* copy of wow (from the website, latest client)
3) copy latest WOW client to server
4) run mapextract on latest WOW client
5) PROFIT!

**Branch(es):**

master

**TC rev. hash/commit:** 

f4753944684dd9e98f88f7221f10501624df3352

--LOG---

/home/trinity/newserver/bin/mapextractor
TrinityCore rev. f4753944684d 2017-05-15 15:46:26 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale enUS
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale koKR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale frFR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale deDE
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale zhCN
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale zhTW
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale esES
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale esMX
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale ruRU
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale ptBR
Error opening casc storage '/mymedia/legion/Data': FILE_NOT_FOUND
error opening casc storage '/mymedia/legion/Data' locale itIT
No locales detected

**TDB version:**  N/A

**Operating system:** Fedora Core 25

**Comment by Aokromes** [comment]
you must run extractor on wow binary directory.

**Comment by tkrokli** [comment]
@FamousL : is there any way the wiki pages could be improved so you would understand earlier that you need to run the extractors in the Wow.exe / Wow-64.exe folder?

**Comment by FamousL** [comment]
I did run that in the specified folder, this is the contents of the folder this was run in

BlizzardError.exe  Cache  Data  dbghelp.dll  Launcher.db  Logs  Utils  'World of Warcraft Launcher.exe'  Wow-64.exe  Wow.exe  WoW.mfil  WTF

**Comment by FamousL** [comment]
Here is a full recursive listing of the directory structure starting at the binary's directory
(in my case /mymedia/wow)
https://gist.github.com/FamousL/dc8373ef0430caf745e22e292849fa94

**Comment by timh52280** [comment]
I have the same problem no locales are detected

**Comment by FamousL** [comment]
make sure the .buildinfo file is present. It was what prevented me from getting an extraction

**Comment by timh52280** [comment]
and if that file is no present how can I fix it?

**Comment by tkrokli** [comment]
Always run the extractors inside your WoW game root folder (where you find Wow.exe (and Wow-64.exe)). Do _not_ run them from any other folder. Also, check if patching your Wow.exe / Wow-64.exe with the connection_patcher.exe will help with this. Basically, follow the TC wiki guide as much as possible. If anything is wrong or missing in the TC wiki guide, edit it or ask about it in IRC: #trinity @ irc.rizon.net (https://trinitycore.atlassian.net/wiki/display/tc/IRC)

**Comment by timh52280** [comment]
I ran from my root wow folder, but I noticed that in my data folder there is not locales directories like (enUS, esES, etc)

**Comment by tkrokli** [comment]
Anyway, the [**TrinityCore issue tracker**](https://github.com/TrinityCore/TrinityCore/issues/) is not a forum and this is not a source code issue, otherwise other users would have reported it or confirmed your issue. Please use either https://community.trinitycore.org/ or ask in IRC: #trinity @ irc.rizon.net (https://trinitycore.atlassian.net/wiki/display/tc/IRC)
