### ISSUE TITLE
[3.3.5] Core/Pet: Action bar

### ISSUE THREAD

**Issue by Cannix** [TrinityCore/TrinityCore#19770]
**Description:**

If you summon a dead hunter pet you wont get the pet action bar.

**Current behaviour:**

No action bar.

**Expected behaviour:**

You should get an action bar.

**Steps to reproduce the problem:**

1. Kill your pet
2. Run out of range / wait for despawn
3. Summon it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. edd2c1c03995 2017-05-17 08:08:46 +0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon) 

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** 
Win

**Comment by kaldown** [comment]
![2018-02-14--01 05 31_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36176355-62e612ae-1123-11e8-887a-8c002f97a2a2.png)

**Comment by tkrokli** [comment]
@Langerz82 : Just a minor question, does the pet bar appear even when the pet is dead, or does it appear after the pet is revived? (I know, I should have tested it, I just haven't been focused enough to test it for myself yet.)

**Comment by Langerz82** [comment]
For me it disappears when your out of range and the pet is dead, but casting revive the bar appeared again. Maybe I am missing something in the test case.

**Comment by tkrokli** [comment]
OK, fair enough. I will test this later today and see if it is possible to reproduce the issue or not.

**Comment by tkrokli** [comment]
TrinityCore rev. 93357631fa8f 2018-02-18 19:52:58 +0000 (3.3.5 branch) (Win64, Release, Static)
TDB 335.64 + updates up to and including `2018_02_19_18_world_335.sql`

Took me a bit longer than I thought, but I just managed to reproduce the issue under some dubious circumstances.

I entered the Alterac Valley battleground with `.debug bg` so I could check it out on my own (playing locally on my computer). While fighting Vanndar Stormpike `<Stormpike General>`, my hunter pet got killed during one of the attempts and I chose not to resurrect it until I completed the BG and used the final "leave battleground" function from the end credit UI. After reviving my pet, I did not see the pet bar while moving around in the AV entrance cave.

![wowscrnshot_022018_234840](https://user-images.githubusercontent.com/4903600/36454250-658c0400-169b-11e8-9804-66f5117cf22e.jpg)

**But after that I teleported to Orgrimmar to hand in a quest and thereby got the pet bar back** (similar to reloading the game UI). I am uncertain how much difference it makes that my character is on an admin account (gmlevel 3), but with GM off. I had recently also modified my character's HP to 500K instead of the regular ~2500 hp. Using extra game addons like Carbonite could possibly affect this result too, so I don't evaluate my incident as solid proof.

**Comment by kaldown** [comment]
it's much simpler to reproduce:
.die [pet]
.modify speed 10
move far from where pet died, pet portrait will eventually disappear
use pet call (skill)
realize you have a pet portrait back, with no action bar, even after reviving corpse

**Comment by DanVS** [comment]
Does not happen when resurrecting pet without summoning for me.

**Comment by Langerz82** [comment]
I made it so it sends the PetActionBar to the client but its still not appearing, any idea peoples?
Here is the packet sniff section:

```
ServerToClient: SMSG_SPELL_GO (0x0132) Length: 50 ConnIdx: 0 EP: 127.0.0.1:56189 Time: 06/21/2018 20:48:16.151 Number: 273
Caster GUID: Full: 0x0000000A Type: Player Low: 10 Name: Blah
Caster Unit GUID: Full: 0x0000000A Type: Player Low: 10 Name: Blah
Cast Count: 6
Spell ID: 982 (982)
Cast Flags: 2304 (Unknown7, PredictedPower)
Time: 141799
Hit Count: 1
[0] Hit GUID: Full: 0x0000000A Type: Player Low: 10 Name: Blah
Miss Count: 0
Target Flags: 66 (Unit, DestinationLocation)
Target GUID: 0x0
Destination Transport GUID: 0x0
Destination Position: X: 9956.996 Y: 677.167 Z: 1314.434
Rune Cooldown: 291
Unk Byte 2: 0

ServerToClient: MSG_MOVE_TELEPORT (0x00C5) Length: 35 ConnIdx: 0 EP: 127.0.0.1:56189 Time: 06/21/2018 20:48:16.151 Number: 274
Guid: Full: 0xF14000000A000002 Type: Pet Entry: 10 Low: 2
Movement Flags: 0 (None)
Extra Movement Flags: 0 (None)
Time: 141799
Position: X: 9953.8 Y: 673.9979 Z: 1313.198
Orientation: 1.622398
Fall Time: 0

ServerToClient: SMSG_PET_SPELLS_MESSAGE (0x0179) Length: 144 ConnIdx: 0 EP: 127.0.0.1:56189 Time: 06/21/2018 20:48:16.152 Number: 275
GUID: Full: 0xF14000000A000002 Type: Pet Entry: 10 Low: 2
Pet Family: 26 (BirdOfPrey)
Expiration Time: 0
React state: Defensive
Command state: Stay
Flag: 0
[0] Slot: 7
[0] Action: 2
[1] Slot: 7
[1] Action: 1
[2] Slot: 7
[2] Action: 0
[3] Slot: 1
[3] Action: 0
[4] Slot: 1
[4] Action: 0
[5] Slot: 1
[5] Action: 0
[6] Slot: 1
[6] Action: 0
[7] Slot: 6
[7] Action: 2
[8] Slot: 6
[8] Action: 1
[9] Slot: 6
[9] Action: 0
Spell Count: 21
[0] Spell: 14916 (14916)
[0] Active: -32512
[1] Spell: 34666 (34666)
[1] Active: 256
[2] Spell: 16828 (16828)
[2] Active: -32512
[3] Spell: 19582 (19582)
[3] Active: 256
[4] Spell: 50541 (50541)
[4] Active: -32512
[5] Spell: 8875 (8875)
[5] Active: 256
[6] Spell: 19589 (19589)
[6] Active: 256
[7] Spell: 19581 (19581)
[7] Active: 256
[8] Spell: 17216 (17216)
[8] Active: 256
[9] Spell: 19580 (19580)
[9] Active: 256
[10] Spell: 19591 (19591)
[10] Active: 256
[11] Spell: 20782 (20782)
[11] Active: 256
[12] Spell: 34903 (34903)
[12] Active: 256
[13] Spell: 20784 (20784)
[13] Active: 256
[14] Spell: 34667 (34667)
[14] Active: 256
[15] Spell: 34675 (34675)
[15] Active: 256
[16] Spell: 34902 (34902)
[16] Active: 256
[17] Spell: 34904 (34904)
[17] Active: 256
[18] Spell: 53397 (53397)
[18] Active: 256
[19] Spell: 55566 (55566)
[19] Active: 256
[20] Spell: 61017 (61017)
[20] Active: 256
Cooldown count: 0
```

**Comment by Langerz82** [comment]
I think it's bugged on the client since the packet sends correctly and still does not load up the bar. What we should be doing is not letting the player call the pet when it's a corpse. After all it does not make much sense. Will provide a patch tomorrow.

**Comment by Langerz82** [comment]
This will prevent the player from calling a pets dead corpse.

See:
https://gist.github.com/Langerz82/a8f87cf8c95e60a741727e40e3fb9c71

**Comment by illfated** [comment]
interesting solution. I forgot that [Call Pet] should be unavailable if pet is dead, if that is how it is/was done in retail.

**Comment by jackpoz** [comment]
I remember working on this 8 years ago, I'll dig a bit more into the behavior when I have time. Could it be a dead pet called gets resurrected automatically ?

**Comment by illfated** [comment]
> Could it be a dead pet called gets resurrected automatically ?

Not from what I have seen (or at least from what I can remember during the last year). if I move far enough to lose the pet corpse and then summon it, the pet corpse appears and no automatic resurrection.

**Comment by jackpoz** [comment]
@Langerz82 I would suggest SMSG_PET_TAME_FAILURE instead of SendCastResult(SPELL_FAILED_TARGETS_DEAD) . do you have any sniff about it ? (this is actually something I fixed 9 years ago in another project)

**Comment by robinsch** [comment]
SMSG_PET_TAME_FAILURE is the correct one, with PETTAME_DEAD. This needs to be implemented in CheckCast, you can take a look at cmangos I just ported the implementation of it months ago and it's working fine.

**Comment by jackpoz** [comment]
or https://github.com/arcemu/arcemu/commit/0a7f28da8769fe44ecede9dbb98f9aaebe15dc0b which implemented it 9 years ago :P

**Comment by jackpoz** [comment]
@robinsch I created https://github.com/TrinityCore/TrinityCore/pull/23271 but it looks quite ugly the way I had to pass back to EffectSummonPet the information about the pet being dead (the code I worked on 9 years ago allowed a cleaner check). How did you implement it ? Would you like to open a PR ?

**Comment by robinsch** [comment]
I use ::CheckCast and only a query to check if pet is dead.

```
if (m_spellInfo->Id == 883)
                        if (!Pet::CanLoadPetFromDB(m_caster->ToPlayer()))
                        {
                            m_caster->ToPlayer()->SendPetTameFailure(PETTAME_DEAD);
                            return SPELL_FAILED_DONT_REPORT;
                        }
```

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23271
