### ISSUE TITLE
Gameobject Bobber (Fishing)

### ISSUE THREAD

**Issue by vato312199** [TrinityCore/TrinityCore#19773]
**Description:**

The bobber object is inactive, it is impossible to get the loot

- http://www.wowhead.com/fishing
- http://www.wowhead.com/spell=131474

**Expected behaviour:**

After some time the bobber will twitch and you can get loot by clicking on the object.

**Steps to reproduce the problem:**

1. Learn fishing from the trainer http://www.wowhead.com/npc=3332
2. Use spell "131474"

**Branch(es):** Master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  720.00 + updates

**Operating system:**  Win10 x64

**Comment by chilito** [comment]
confirmed!

**Comment by Aokromes** [comment]
I am sure this ticket is duplicated, but cannot find the other.

**Comment by Exodius** [comment]
#11520?
