### ISSUE TITLE
[3.3.5/master] Reinforced Junkbox should have a chance to drop epics

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#19776]
**Description:**

Reinforced junkbox should have a (small) chance to drop some epics, in addition to its normal loot

**Current behaviour:**

Loot missing in loot tables (confirmed with http://www.wowhead.com/item=43613)

**Expected behaviour:**

There should be a small chance to get:
- Krol Cleaver (http://www.wowhead.com/item=43611)
- Spineslicer (http://www.wowhead.com/item=43612)
- The Dusk Blade (http://www.wowhead.com/item=43613)

**Steps to reproduce the problem:**

1. Check out item_loot_template and reference_loot_template tables
2. Not found

**Branch(es):**

3.3.5, probably master too

**TC rev. hash/commit:** 

586cc0e0b4c9f63090bd340c1cf58fbfe807063e

**TDB version:**  335.63

**Operating system:** Win10 x64

**Comment by tkrokli** [comment]
Detail: According to wowhead, Spineslicer (https://db.rising-gods.de/?item=43612) seems to be removed from the game. I checked wow.gamepedia.com and found only the Ravager NPC and the quest to kill it when I searched for "Spineslicer". On wowwiki, no page exists for any of them. http://www.wowhead.com/item=43612/spineslicer is both shown as a trash item as well as tagged with the text "This item's source is no longer available/removed.". So this item will likely not be needed in master, but should be present in the 3.3.5 loot tables.

**Comment by ariel-** [comment]
Yeah, for master Spineslicer shouldn't be added as it was removed (along with all thrown weapons)

**Comment by offl** [comment]
3.3.5 & master
```sql
DELETE FROM `item_loot_template` WHERE `Entry` = 43575 AND `Item` IN (43611,43612,43613);
INSERT INTO `item_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`) VALUES
(43575,43611,0,0.01,0,1,0,1,1),
(43575,43612,0,0.01,0,1,0,1,1),
(43575,43613,0,0.01,0,1,0,1,1);
```

```sql
DELETE FROM `item_loot_template` WHERE `Entry` = 43575 AND `Item` IN (43611,43613);
INSERT INTO `item_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`) VALUES
(43575,43611,0,0.01,0,1,0,1,1),
(43575,43613,0,0.01,0,1,0,1,1);
```
