### ISSUE TITLE
Cant compil

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#19778]
I had a computer dedicated for compiling. But my HDD died and I had to reinstall it.
Now, when i try compiling, I have Error C4577 'no exept' at all files.
Someone has a solution ?

**Comment by TecDian** [comment]
This may be a question for help and as such quite OK. But it belongs into the support forum. I can't see that this is an issue with TC. So shouldn't this be closed?

**Comment by Vincent-Michael** [comment]
C4577 is no warning?

**Comment by TecDian** [comment]
If I'm not mistaken this error originates from the Boost library.
Visual Studio 2015 Update 2 seems to require an exception handling mode to be set.
And yes, it's a warning. Thus the project should compile anyway. But as I said, it seems a question for support. I may be wrong though.
