### ISSUE TITLE
[master] cannot enter Legion instances or Hellfire Citadel

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#19771]
**Description:** Area triggers are missing from database.

**Current behaviour:** Instance portal entrances do not have any functionality.

**Expected behaviour:** Able to enter instances.
I checked the wikia on how to do it but TrinityCore is vastly outdated as most still use 3.3.5a format.

**Steps to reproduce the problem:**

1. Should be self-explanatory

**Branch(es):** Master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/74456703146194de72424ec98c4ea76402077be6

**TDB version:**  720.00

**Operating system:** Windows 7

**Comment by Ulduar** [comment]
Hellfire Citadel not have entry in access_requirement. Only instance_template.

**Comment by Aokromes** [comment]
#13179
