### ISSUE TITLE
[3.3.5] Core/Spells: Dismantle remove Shield Wall 

### ISSUE THREAD

**Issue by Laintime** [TrinityCore/TrinityCore#19782]
**Description:**
Dismantle : Disarm the enemy, removing all weapons, shield or other equipment carried for 6 sec.
**Current behaviour:**
Dismantle remove Shield Wall
**Steps to reproduce the problem:**

1. Warrior use Shield Wall 
2. Rogue use Dismantle
3. Warrior remove Shield Wall and shield block

**Branch(es):**

3.3.5
**TC rev. hash/commit:** 
clean tc
https://github.com/TrinityCore/TrinityCore/commit/7afe0b7fb005999dfb8bfae45b7d22abbec29b93

![wowscrnshot_052117_184828](https://cloud.githubusercontent.com/assets/13253785/26284881/b7c63f96-3e4d-11e7-8af6-4df9d40c4547.jpg)

![wowscrnshot_052117_184831](https://cloud.githubusercontent.com/assets/13253785/26284883/ba808520-3e4d-11e7-9bd1-b79ada60d8db.jpg)

http://www.mmo-champion.com/threads/698163-Dismantling-during-shield-wall 
Re: Dismantling during shield wall
Dismantling during shieldwall won't affect the 60% damage reduction, it will simply mean the warrior can't block incoming attacks.
Dismantling just prior to a shieldwall means he won't be able to use the skill because it requires and equipped shield

**Comment by ariel-** [comment]
Weapon dependent aura removed on disarm, however shouldn't be lost as Bladestorm is....

Only meaningful difference between Bladestorm and Shield Wall/Shield Block I found is Bladestorm has SPELL_ATTR3_MAIN_HAND and SPELL_ATTR1_UNK4.

SPELL_ATTR1_UNK4 is found on some weapon dependent spells (ie EquippedItemClass is != -1), however also found on non dependent spells, so it's a toss and probably unrelated

**Comment by Laintime** [comment]
@ariel- any news?Maybe hack?

**Comment by Keader** [comment]
He will make a proper fix when have time :)

**Comment by Eliminationzx** [comment]
Any news?

**Comment by kvipka** [comment]
it should work like this ? https://www.youtube.com/watch?v=VQ_Qxa0JNDU

**Comment by Keader** [comment]
i dont think so
in your video, you lost shield, and i dont think this should happen

**Comment by kvipka** [comment]
strange, topic starter and .mmo-champion told :

> Dismantling during shieldwall won't affect the 60% damage reduction, it will simply mean the warrior can't block incoming attacks.
> Dismantling just prior to a shieldwall means he won't be able to use the skill because it requires and equipped shield.

I think warr should lost both items (main and off-hand), and can't use skills that requires items + can't block attacks.

**Comment by Keader** [comment]
Ok guys, i need help here.
I cant find a "good way" to fix it.

My "quick" solution is:

<details>

```diff

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index c4e3739..5604a22 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -23530,8 +23530,9 @@ void Player::RemoveItemDependentAurasAndCasts(Item* pItem)
             continue;
         }
 
-        // skip if not item dependent or have alternative item
-        if (HasItemFitToSpellRequirements(spellInfo, pItem))
+        // skip if not item dependent/have alternative item or is shield wall
+        // shield wall is an exception and should stay when shield is removed
+        if (HasItemFitToSpellRequirements(spellInfo, pItem) || spellInfo->Id == 871)
         {
             ++itr;
             continue;
```

</details>

This bug is caused by this line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Item/Item.cpp#L803

**Callstack is**:  Player::RemoveItemDependentAurasAndCasts -> Player::HasItemFitToSpellRequirements -> Item::IsFitToSpellRequirements

I cant think a way to fix it without "hardcoded it"
