### ISSUE TITLE
Missing Spawns in Dalaran (Broken Islands)

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#19781]
**Description:** Missing Spawns in Dalaran (Broken Islands)

Spawns are missing in New Dalaran!

**Current behaviour:** Missing spawns in new Dalaran

**Expected behaviour:** New Dalaran should fully spawned.

**Steps to reproduce the problem:**

1. Login
2. Go to new Dalaran
3. Check NPC population

**Branch(es):**   master

**TC rev. hash/commit:** 7cc3d1387d12b9d128fd812b6548113eb883c098

**TDB version:**  720

**Operating system:** Windows Server 2012 R2

**Comment by tkrokli** [comment]
Feel free to sniff the NPC population of new Dalaran and upload the sniffs to the forum page https://community.trinitycore.org/forum/13-wdbadbsniffs/ (write-only, make sure you are logged in with your TrinityCore Forum account first). Waypoints for roaming NPCs and chat speech will be needed, so the sniffs need to be performed at low-traffic times to have as little noise and activity from other players as possible in them. From the sniffs, you can make SQL queries and post them in ```sql code blocks here as suggested solutions.

**Comment by Shoxxo** [comment]
I am sniffing atmm some but i have a rota and dont sniff here and here and here. But thanks for the tip sir.

**Comment by Shoxxo** [comment]
Submitted dalaran Basics

**Comment by Aokromes** [comment]
#12975

**Comment by jcmillions** [comment]
My only concern is do we sniff it BEFORE we do any quests there?

**Comment by Shauren** [comment]
It would probably be best in all phases
