### ISSUE TITLE
[3.3.5] Sons of Hodir Gameobject quest givers

### ISSUE THREAD

**Issue by ariel-** [TrinityCore/TrinityCore#19787]
**Description:**

SoH faction questgivers are visible

**Current behaviour:**

SoH faction questgivers are always visible and they offer daily quests even before you did the quest that 'brings them'

**Expected behaviour:**

SoH questgiver gameobjects should only be visible AFTER you have done the related pre-quest:

- http://www.wowhead.com/quest=13001/raising-hodirs-spear for http://www.wowhead.com/object=192079/hodirs-spear
- http://www.wowhead.com/quest=12976/a-monument-to-the-fallen for http://www.wowhead.com/object=192078/hodirs-horn
- http://www.wowhead.com/quest=12987/mounting-hodirs-helm for http://www.wowhead.com/object=192080/hodirs-helm

**Steps to reproduce the problem:**

1. Go to Dun niffelem (ie .go xyz 7107.77 -2728.86 787.21 571)
2. .quest add 12924
3. Watch all the gameobjects pop, even though you didn't complete the prequests yet

**Branch(es):**

3.3.5, probably master too

**TC rev. hash/commit:** 
7afe0b7fb005999dfb8bfae45b7d22abbec29b93

**TDB version:**  TDB 335.63

**Operating system:** Win10 x64

**Comment by Killyana** [comment]
I cannot reproduce, actual conditions:
 12976 prevquest=12975
 12987 prevquest= 12985 and The Player's standing with The Sons of Hodir is Friendly
 13001 The Player's standing with The Sons of Hodir is Honored

After checking wowhead, this conditions looks correct.

**Comment by ariel-** [comment]
.go xyz 7107.77 -2728.86 787.21 571
.quest add 12924

Horn pops in front of you.
Updated issue with coords

**Comment by Killyana** [comment]
Cannot reproduce.

**Comment by Aokromes** [comment]
.gm off / gm visible on before quest add :)

**Comment by ariel-** [comment]
Of course doing with .gm off, .gm on allows to see always all phases

**Comment by Xyventh** [comment]
Found a fix for Hodir's Helm visibility [here](https://bitbucket.org/Whethx/trinitycore/commits/36a677d34adc19d5186b0539d73d5689ea3d9490), seems fine.

**Comment by Killyana** [comment]
Ah, I was thinking about quest availability not gob that are visible, I will fix this this issues.
