### ISSUE TITLE
[3.3.5] Warlock's Conflagrate can't be cast if the target already has Immolate from another caster

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#19790]
**Current behaviour:**

The Conflagrate spell action bar will remain grayed out if you target a unit already afflicted by Immolate from another caster.

From what I have gathered, this happens because https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L6037-L6046 only checks the aura that applied the state. So if you are not the caster who applied it, you are screwed and won't be able to cast it.

**Expected behaviour:**

The client should be updated so long the target is affected by Immolate from the caster, allowing them to cast Conflagrate.

**Steps to reproduce the problem:**

1. Character A applies Immolate on a given target  
2. Character B targets the given target and applies Immolate
3. Character A is able to cast Conflagrate, Character B is not

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/195db7c7bb7137f3ebadefa81fabdcf66672711a

**Comment by ariel-** [comment]
SharedDefines.h

```cpp
#define PER_CASTER_AURA_STATE_MASK (\
    (1<<(AURA_STATE_CONFLAGRATE-1))|(1<<(AURA_STATE_DEADLY_POISON-1)))
```

Maybe AURA_STATE_CONFLAGRATE should be removed from that mask?

**Comment by Nyeriah** [comment]
> SharedDefines.h

> #define PER_CASTER_AURA_STATE_MASK (\
 >    (1<<(AURA_STATE_CONFLAGRATE-1))|(1<<(AURA_STATE_DEADLY_POISON-1)))
> Maybe AURA_STATE_CONFLAGRATE should be removed from that mask?

Nope, if you do that then the client always has it unlocked, regardless of the immolate on target belonging to the caster or not, but attempting to cast it still fails the cast because that is already properly checked elsewhere.

**Comment by ariel-** [comment]
Then it's ok? Not allowing to cast conflagrate until the caster uses Immolate on the target

**Comment by Nyeriah** [comment]
> Then it's ok? Not allowing to cast conflagrate until the caster uses Immolate on the target

Yes, but that's not how it should work, sooo, yes, as a temporary solution we can do that I think. But at long term that probably should be looked into again :\

**Comment by ariel-** [comment]
Deleted because I screwed up xD

**Comment by Keader** [comment]
wait...
without glyph you can "stolen" immolate to other warlocks ?

**Comment by Nyeriah** [comment]
The opposite. Without the glyph it can never be cast if another warlock casts immolate first.

**Comment by Temppus** [comment]
I solved this issue when i was working on private server like this.
https://www.diffchecker.com/L77UM4sq
Maybe will help.

**Comment by ariel-** [comment]
That code solves the problem partially (ie, does not update when the target has 2 auras and one is removed)
