### ISSUE TITLE
[DB/Spells] Paladin T8 Holy 2P Bonus proc

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19796]
**Description:** Spell Paladin T8 Holy 2P Bonus is not proccing in Holy Shock crit
Spell is present on item http://www.wowhead.com/item=45374/valorous-aegis-tunic

Suggested fix: 

```sql
UPDATE `spell_proc` SET `AttributesMask`=0x2  WHERE `SpellId`=64890;
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7afe0b7fb005999dfb8bfae45b7d22abbec29b93

**Comment by ccrs** [comment]
Looks good.
