### ISSUE TITLE
[master] Arms warrior rage

### ISSUE THREAD

**Issue by cybrann** [TrinityCore/TrinityCore#19798]
**Description:**
Arms warrior spells are not consuming any rage. It might be connected to some aura/talent/passive spells.

**Current behaviour:**
Arms warrior spells are not consuming any rage.

**Expected behaviour:**
Arms warrior spells should consume rage.

**Steps to reproduce the problem:**
1. Create arms warrior
2. Get him to lvl 110
3. Use spells like slam or mortal strike

**Branch(es):** master

**TC rev. hash/commit:** 1bc60ed48dcecde74653c79873460b40aa27bb0a

**TDB version:** TDB 720.00

**Operating system:** Windows 7

**Comment by matanshukry** [comment]
Not relevant anymore.

Created a warrior and leveled it to 60, changed spec to arms.
Both slam and mortal strike consume rage
