### ISSUE TITLE
[master] Fury warrior enrage

### ISSUE THREAD

**Issue by cybrann** [TrinityCore/TrinityCore#19799]
**Description:**
Bloodthirst critical strikes will Enrage you, increasing your attack speed by 100% and damage you take by 20% for 4 sec.

**Current behaviour:**
Enrage is activated of off every attack.

**Expected behaviour:**
It should be activated only when bloodthirst crits.

**Branch(es):** master

**TC rev. hash/commit:** 1bc60ed48dcecde74653c79873460b40aa27bb0a

**TDB version:** 720.00

**Comment by Nyr97** [comment]
Invalid. As of today, the spell is not triggered by every autoattack. Also, this is a replicated report.

**Comment by Aokromes** [comment]
more than invalid, outdated
