### ISSUE TITLE
DB/Gossip: Apothecary Zamah

### ISSUE THREAD

**Issue by brotalnia** [TrinityCore/TrinityCore#19795]
**Description:**  Apothecary Zamah's gossip text is missing. She says just "Greetings, name", instead of her correct text. From this vanilla wow video you can see that she has her own text.

Video - https://youtu.be/NrSdjsrhX0s?t=29m31s
NPC - http://www.wowhead.com/npc=3419/

**Current behaviour:** She says "Greetings, $N."

![zamah-trinity](https://cloud.githubusercontent.com/assets/6519171/26403091/87b5f306-4095-11e7-8e39-61569e145c9b.jpg)

**Expected behaviour:** She should say: 

> For our people to survive, we must study the ways of nature and learn its secrets.

![zamah-retail](https://cloud.githubusercontent.com/assets/6519171/26403108/a1961594-4095-11e7-8e74-c5396d4e0911.jpg)

**Steps to reproduce the problem:**

1. Talk to Apothecary Zamah (id 3419) while you are on the quest Apothecary Zamah (id 853).

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  cacde7b9f51f

**TDB version:**  335.63

**Operating system:** Windows 7

**Comment by malcrom** [comment]
I'll get this in a couple hours when I'm home.

**Comment by offl** [comment]
#19756

**Comment by Killyana** [comment]
Dup #19756
