### ISSUE TITLE
Vendor buyings not working

### ISSUE THREAD

**Issue by HamAndRock** [TrinityCore/TrinityCore#19792]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

When i go to vendo in starting location, not tested in Ogrimmar and Other Cities, i am not able to buy anything from him even, if i have enought money. I am only able to sell to him, and buy items back from buypack.

**Expected behaviour:**

I should be able to buy items.

**Steps to reproduce the problem:**

1. Went to http://www.wowhead.com/npc=15292/faraden-thelryn, or the NPC in the location.
2. Tried to buy any item.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. cd7c4478ba0d 2017-05-23 17:06:49 +0200 (master branch) (Unix, Release, Static) (bnetserver)

**TDB version:**  TDB 720.00

**Operating system:** Debian 8.7.1 64bit

**Comment by cybrann** [comment]
Can confirm. No vendors are working

**Comment by Raydor** [comment]
Maybe related to https://github.com/TrinityCore/TrinityCore/commit/d03e97d53f8dcabe006773d3377842bc091359a9?

**Comment by Shauren** [comment]
How did you even reach that conclusion? That commit is not present in master branch

**Comment by Shauren** [comment]
Cannot reproduce, works fine for me

**Comment by Artamedes** [comment]
vendors work fine for me

**Comment by codeman8214** [comment]
It is not due to that commit but you are right it is a database issue because I had to update the database without the vendors update and it works again, it also fixed the training one as well.

**Comment by Aokromes** [comment]
If you mean https://github.com/TrinityCore/TrinityCore/commit/3633c5e5ebe4d57935702589f9f4501d8ed8739e i don't see how that can break 15292

**Comment by Aokromes** [comment]
aokromes@:~/src/7/sql/updates/world/master$ ls
2017_04_19_00_world.sql  2017_04_24_00_world.sql  2017_04_30_01_world.sql  2017_05_10_01_world.sql  2017_05_11_01_world.sql  2017_05_15_00_world.sql  2017_05_22_04_world.sql  2017_05_23_07_world.sql  2017_05_24_06_world.sql
2017_04_19_01_world.sql  2017_04_24_01_world.sql  2017_05_01_00_world.sql  2017_05_10_02_world.sql  2017_05_11_02_world.sql  2017_05_15_01_world.sql  2017_05_23_00_world.sql  2017_05_23_08_world.sql  2017_05_25_00_world.sql
2017_04_19_02_world.sql  2017_04_25_00_world.sql  2017_05_02_00_world.sql  2017_05_10_03_world.sql  2017_05_11_03_world.sql  2017_05_21_00_world.sql  2017_05_23_01_world.sql  2017_05_24_00_world.sql  2017_05_25_01_world.sql
2017_04_20_00_world.sql  2017_04_27_00_world.sql  2017_05_04_00_world.sql  2017_05_10_04_world.sql  2017_05_12_00_world.sql  2017_05_21_01_world.sql  2017_05_23_02_world.sql  2017_05_24_01_world.sql
2017_04_21_00_world.sql  2017_04_28_00_world.sql  2017_05_06_00_world.sql  2017_05_10_05_world.sql  2017_05_14_00_world.sql  2017_05_22_00_world.sql  2017_05_23_03_world.sql  2017_05_24_02_world.sql
2017_04_22_00_world.sql  2017_04_29_00_world.sql  2017_05_08_00_world.sql  2017_05_10_06_world.sql  2017_05_14_01_world.sql  2017_05_22_01_world.sql  2017_05_23_04_world.sql  2017_05_24_03_world.sql
2017_04_23_00_world.sql  2017_04_29_01_world.sql  2017_05_09_00_world.sql  2017_05_10_07_world.sql  2017_05_14_02_world.sql  2017_05_22_02_world.sql  2017_05_23_05_world.sql  2017_05_24_04_world.sql
2017_04_23_01_world.sql  2017_04_30_00_world.sql  2017_05_10_00_world.sql  2017_05_11_00_world.sql  2017_05_14_03_world.sql  2017_05_22_03_world.sql  2017_05_23_06_world.sql  2017_05_24_05_world.sql
aokromes@:~/src/7/sql/updates/world/master$ grep 15292 *
aokromes@:~/src/7/sql/updates/world/master$

**Comment by codeman8214** [comment]
lol
