### ISSUE TITLE
FlightMaster / Gryphon  Master Min/Max level Problem FIX for  (Updates #15829)

### ISSUE THREAD

**Issue by Taaboy** [TrinityCore/TrinityCore#19808]
**Description:**
With That Up date for  Flight masters/ Gryphon Master you have set them to minlvl 0 and maxlvl 0.

**Expected behaviour:**

Should Be level 110, But if you place 110 in Minlevel or maxlevel it goes to lvl 220.

To Fix this Problem make sure HealthScalingExpansion is not a negative number for Flightmaster/Gryphon Master it should be set to HealthScalingExpansion 6 , this will fix your problem and give correct health and level .
This also works with other creatures that have the level problem.

**Branch(es):**
TrinityCore rev. cc1020fcc8a2 2017-05-22 11:10:53 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)
Master

**TC rev. hash/commit:** 
b421b82ac237fc4939a183985ccaeada2ef80a98

**TDB version:** 7.20
**Operating system:** Win10 OS

**Comment by codeman8214** [comment]
I do not know how I missed this thank you for bringing this to my attention, I will have this updated quickly

**Comment by codeman8214** [comment]
```sql
UPDATE `creature_template` SET `minlevel`= 110,`maxlevel`= 110,`HealthScalingExpansion`= 6 WHERE `subname`= 'Gryphon Master';
UPDATE `creature_template` SET `minlevel`= 110,`maxlevel`= 110,`HealthScalingExpansion`= 6 WHERE `subname`= 'Flight Master';
