### ISSUE TITLE
Backpack sorting is broken

### ISSUE THREAD

**Issue by HamAndRock** [TrinityCore/TrinityCore#19807]
**Description:**

BP sorting button wont sort items and make them grey and unmovable. I can use them after death or reconnect

**Current behaviour:**

Explained above.
**Expected behaviour:**
Items should sort without any problems.
**Steps to reproduce the problem:**

1. Open BP
2. Click sort button
3 Tested with 1 bag

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. cd7c447 2017-05-23 17:06:49 +0200 (master branch) (Unix, Release, Static) (bnetserver)

**TDB version:**  720

**Operating system:** Debian

**Comment by Aokromes** [comment]
#13825
