### ISSUE TITLE
[3.3.5] Missing RP event at end of quest Jin'Zil's Forest Magic

### ISSUE THREAD

**Issue by Xyventh** [TrinityCore/TrinityCore#19803]
**Description:**

When the quest [Jin'Zil's Forest Magic](http://www.wowhead.com/quest=1058) is turned in, an event should happen where the quest giver kills the night elves inside the cages, whose wisps then leave the cave.

The quest is not available on Retail anymore, and I couldn't find any further info, but perhaps someone has a sniff somewhere.

**Current behaviour:**

No event happens when turning in the quest.

**Expected behaviour:**

Event should happen when turning in the quest.

**Branch(es):** 3.3.5.

**TC rev. hash/commit:** 66bd345

**TDB version:** 335.63

**Comment by Navedonar** [comment]
https://github.com/TrinityCore/TrinityCore/commit/27235e54c762c9fd7541d15a7235847c01524be8

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/27235e54c762c9fd7541d15a7235847c01524be8
