### ISSUE TITLE
[3.3.5] Missing RP event when the quest Forsaken Aid is accepted.

### ISSUE THREAD

**Issue by Xyventh** [TrinityCore/TrinityCore#19804]
**Description:**

When the quest [Forsaken Aid](http://www.wowhead.com/quest=1064) is accepted, a NPC should spawn and travel to the quest ender, [saying something](http://www.wowhead.com/quest=1064/deprecated-forsaken-aid#comments:id=456808:reply=97544) and despawning some time after.

Couldn't find more info right now, and the quest was removed in Cataclysm.

**Current behaviour:**

No event happens when turning in the quest.

**Expected behaviour:**

Event should happen when turning in the quest.

**Branch(es):** 3.3.5.

**TC rev. hash/commit:** 66bd345

**TDB version:** 335.63

**Comment by offl** [comment]
https://github.com/classicdb/database/commit/4870ee0d716b5e1284233e18158c7ac1b9bf1047
https://github.com/classicdb/database/commit/c5c1d9bf482d198b195e81b08f8aca0fee3a706a
If someone wants to port this :)

**Comment by tkrokli** [comment]
Some practical details:
- http://www.wowhead.com/npc=4046/magatha-grimtotem
- http://www.wowhead.com/spell=6657/summon-serpent-messenger
- http://www.wowhead.com/npc=4068/serpent-messenger
- http://www.wowhead.com/npc=3419/apothecary-zamah

```sql
SELECT * FROM `broadcast_text` WHERE `ID` IN (1420, 1419, 1412, 1418);
```
```
  ID  Language  MaleText                               FemaleText                                                     EmoteID0  EmoteID1  EmoteID2  EmoteDelay0  EmoteDelay1  EmoteDelay2  SoundId    Unk1    Unk2  VerifiedBuild
----  --------  -------------------------------------  -------------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  -------  ------  ------  -------------
1420         0                                         %s summons a messenger...                                             0         0         0            0            0            0        0       0       1          18019
1419         0                                         Go, my servant.  Send word of Stonetalon to Apothecary Zamah.         0         0         0            0            0            0        0       0       1          18019
1412         0  %s gives message to Apothecary Zamah.                                                                        0         0         0            0            0            0        0       0       1          18019
1418         0                                         %s smiles.                                                            0         0         0            0            0            0        0       0       1          18019
```
