### ISSUE TITLE
Vendor items unresponsive, unable to buy items

### ISSUE THREAD

**Issue by Hshore** [TrinityCore/TrinityCore#19811]
**Description:** Vendors wont sell anything to me.

**Current behaviour:**

Right clicking item does nothing.
Drag drop doesn't work.
Shift right click doesn't work

Sell and buyback works

**Expected behaviour:**

Purchase item will give you the selected amount in your bag

**Steps to reproduce the problem:**

Try to buy from any vendor in human starting area

**Branch(es):** master

**TC rev. hash/commit:** TC>TrinityCore rev. 5487a062ce3d 2017-05-26 23:00:29 +0200 (master branch) (Unix, Release, Static)

**TDB version:** TDB 720.00

**Operating system:** Ubuntu 17.04

**Comment by offl** [comment]
Maybe #19792 can help.

**Comment by Aokromes** [comment]
why you ignore template asking for ids of affected creatures?

**Comment by SkyFire** [comment]
I can confirm this issue.. Here are a few examples.
http://www.wowhead.com/npc=66/tharynn-bouden
http://www.wowhead.com/npc=1285/thurman-mullby
http://www.wowhead.com/npc=3937/kira-songshine

**Comment by Hshore** [comment]
Sorry Aokromes, dindnt notice you needed creature ids. First time for me.
But I think it effects every vendor in the game!
I tested Human, dwarf, night elf, Booldelf starting areas.
As well as GM teleport to SW and Ogg and no vendors working there either.

**Comment by jcmillions** [comment]
@Shauren I believe you reverted this commit on accident. [3a52bbb](https://github.com/TrinityCore/TrinityCore/commit/3a52bbb2f0c20e55cf51f89748c9203aa752783f)
