### ISSUE TITLE
[3.3.5] Zappelin Travel Problem to Stranglethorn Vale and further

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#19825]
Description:

When taking a Zappelin from Trisfal Glades towards Stranglethorn Vale, the character arrives in the location however the map is completely empty and the character is standing in air and nothing is around, you have to logout and login back again to see the map. 

When you are in Stranglethorn Vale and the Zappelin travels to another destination, after appearing on a new map, the characters is again stuck in a middle of nowhere and falls downs and eventually dies and you respawn The Barrens graveyard. 

Current behaviour:

Impossible to travel using Zappelin without a relog or death from falling.

Expected behaviour:

The Zappelin should arrive in its destination and you should normally see the whole map and stand on the Zappelin. 

Steps to reproduce the problem:

1. Create any character.
2. Teleport to Trisfal Glades.
3. Jump on a Zappelin travelling to Stranglethorn Vale.
**Branch(es):**

3.3.5 (this error may also occur in master branch however I did not test it on master)

TC rev. hash/commit: TrinityCore rev. 60a69bcd3d6a 2017-05-29 00:51:46 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

TDB version: TDB 335.63

Operating system: Windows 10

**Comment by Ferelith** [comment]
![wowscrnshot_052917_211036](https://cloud.githubusercontent.com/assets/25698730/26561297/1c49eba8-44b5-11e7-9de8-57ecb56e231e.jpg)

**Comment by Aokromes** [comment]
#14672
