### ISSUE TITLE
Vendors charging incorrect prices

### ISSUE THREAD

**Issue by Hshore** [TrinityCore/TrinityCore#19820]
**Description:**

Vendor charges more than stated for stacked items.
Charges correct amount for single item.

**Current behaviour:**

Brog Hamfist (DB GUID: 280715 Creature Entry 151), Lions pride inn, Goldshire.
Buying item "Refreshing Spring Water x5" priced at 23c
Actual cost to buy 1s18c

**Expected behaviour:**

Charge stated price of 23c for 5 Refreshing spring water

**Steps to reproduce the problem:**

Buy stacked item form Brog Hamfist (or most vendors i have checked in human starting area)

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. d427fed13b49+ 2017-05-28 14:32:18 +0200 (master branch) (Unix, Release, Static)

**TDB version:** 

TDB 720.00

**Operating system:**

Ubuntu 17.04

**Comment by HannibalRoG** [comment]
I can confirm this on all the vendors I tested, about 25

5236e6ee22cb3efec138552d9a1a174a748ffb5a

**Comment by HannibalRoG** [comment]
This can be fixed by https://github.com/TrinityCore/TrinityCore/pull/20152
more exactly the 3th 
- Fixed some vendor checks for when BuyCount > 1

**Comment by tkrokli** [comment]
Please verify if this issue is solved by commit https://github.com/TrinityCore/TrinityCore/commit/e04f75bd962006662bc0f77f0034f061605fb1c6 (Pull Request https://github.com/TrinityCore/TrinityCore/pull/20152).
I don't have a Legion client + compiled master source available to test right now.

**Comment by HannibalRoG** [comment]
Yes, i will do that today.

**Comment by HannibalRoG** [comment]
@tkrokli well i can confirm that this issue #20152 is no longer valid, pherhaps the PR #20152 solve it.
