### ISSUE TITLE
Spell/Proc : Improved Counterspell (and other procs) on reflect

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#19826]
**Description:**

Improved counterspell (and other procs) should be reflected the same way the main spell that proc them are, currently, they don't even proc.

**Current behaviour:**

Improved counterspell does not proc on the mage whose counterspell has been reflected.

**Expected behaviour:**

Improved counterspell should proc with the mage as target

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Get a warrior and a mage (with improved counterspell talent)
2. Cast Shield reflect with the warrior, and cast counterspell on the warrior with the mage
3. Counterspell is reflected, improved counterspell does not proc

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/b90fc70c209b24a8aad8e38da6be9de98f50901e

**TDB version:**
Not relvant

**Operating system:** 
Not relevant

**Comment by ariel-** [comment]
Are there any proofs of this? Most procs won't proc on reflect, as it's a special type of miss.

**Comment by joshwhedon** [comment]
Sorry my bad, I had some information about this (forum posts), but after looking further it seems like those reports were wrong and were relating some private servers issues :(. Hard to find proper data about 3.3.5 nowadays.
