### ISSUE TITLE
[3.3.5] After Server Startup Crash

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#19831]
**Description:**

After Serverstart the Server Crashd

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ed43883160f2 2017-06-01 09:08:01 -0300 (335 branch)
**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Win7

**Comment by DDuarte** [comment]
Maybe posting a crashlog wouldn't be a bad idea?

**Comment by Tauriella** [comment]
https://gist.github.com/Tauriella/114d9a8a8e976c1c98592e29d1454c51

**Comment by jackpoz** [comment]
>float m_positionX = 3926.739990
float m_positionY = 4960.709961
float m_positionZ = -12.973800
float m_orientation = 1.179500
unsigned int m_mapId = 0x23B (571)

**Comment by jackpoz** [comment]
std::string m_name = "Defendo-tank 66D"

**Comment by jackpoz** [comment]
unsigned int Entry = 0x649E

**Comment by Aokromes** [comment]
btw, not startup, you go c 51914 to get crash.

**Comment by jackpoz** [comment]
>Map::LoadAllCells

it happens on startup if the "load all cells" config is enabled

**Comment by ariel-** [comment]
```sql
SELECT `MovementType` FROM `creature_template` WHERE `entry`=25758;
```

**Comment by Shauren** [comment]
@ariel- 
`SELECT guid, `MovementType` FROM `creature` WHERE `id`=25758 and movementType > 1;`
2 results
```
51879 | 9
51914 | 9
```

**Comment by irgc** [comment]
Shauren

i Love u .

hum

**Comment by ccrs** [comment]
value validation on db load incomming

**Comment by ariel-** [comment]
Ah, so it was the spawns table the offender....

> value validation on db load incomming
sure it does
