### ISSUE TITLE
AlwaysMaxWeaponSkill and PlayerStart.AllReputation expected behaviour

### ISSUE THREAD

**Issue by cruelwow** [TrinityCore/TrinityCore#19839]
**Description:**

In worldserver.config when enabling max Weapon Skills and Reputation :

```
#
#    AlwaysMaxWeaponSkill
#        Description: Players will automatically gain max weapon/defense skill when logging in,
#                     or leveling.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AlwaysMaxWeaponSkill = 1

#
#    PlayerStart.AllReputation
#        Description: Players will start with most of the high level reputations that are needed
#                     for items, mounts etc.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

PlayerStart.AllReputation = 1
```
Weapon Skills are not maxed and no Reputations are added that are needed for items & mounts.

**Current behaviour:**
- WeaponSkills are not maxed: 1/400 when creating a new character
- Reputation such as The Ashen Verdict is not present and all other reputation are not exalted...

**Expected behaviour:**
- Weapons Skills should be maxed out.
- Important reputation to be added and Reputation to be exalted ? (Not sure)

**Steps to reproduce the problem:**
1. Enable AlwaysMaxWeaponSkill and PlayerStart.AllReputation in worldserver.conf
2. Create New Character
3. Check Weapon Skills and Reputation

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. c3176a814306 2017-05-06 15:49:56 -0300 (3.3.5 branch) (Win32, Release, Static)

**TDB version:** TDB 335.63

**Operating system:** Win 7

**Comment by tkrokli** [comment]
TrinityCore rev. abc749034eb7 2017-06-03 20:01:57 -0300 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 + updates up to and including `2017_06_03_01_world.sql`

Partially confirmed.

`AlwaysMaxWeaponSkill = 1` works for every new level, not on Player Create (Character Creation).
Tested both on a GM account (from level 1 to 11) and on a non-GM account (level 1 - 2), works as expected, also from GM command `.levelup` .
I haven't read the source code for this exact feature, therefore I am not certain if it is intended behaviour or not.
But looking at the Worldserver.conf description, it looks like the intention was to make it work on login as well.
```
#    AlwaysMaxWeaponSkill
#        Description: Players will automatically gain max weapon/defense skill when logging in,
#                     or leveling.
```
Current behaviour: Player character gains Max Weapon Skill when leveling up.
***
`PlayerStart.AllReputation = 1`
This feature does not work at all. Reputation increase is not given to Player Character, neither on login nor during levelup, neither to starting factions nor added factions.
