### ISSUE TITLE
Hunter's pet no longer applies the ability automatically

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#19837]
**Current behaviour:**

Hunter's pet no longer use ability automatically

**Expected behaviour:**

Hunter's pet must use abilities automatically

**Steps to reproduce the problem:**

Hunter's pet Boar no longer use ability automatically.

**Branch(es):**

On version 69fd624 (Partial revert), everything worked

**Operating system:** Windows 10

**Comment by Solzz** [comment]
ce3787f190d28c1e981598eef2cd24c622a2cbae

**Comment by ccrs** [comment]
confirmed, fix incomming.
