### ISSUE TITLE
Worldserver.conf disabled classmask being ignored

### ISSUE THREAD

**Issue by Darkon47** [TrinityCore/TrinityCore#19833]
**Description:**

The option for disabling the creation of certain classes in the configuration (
CharacterCreating.Disabled.ClassMask) is completely ignored

**Current behaviour:**

in conf 
CharacterCreating.Disabled.ClassMask = 2046, any account can still create characters of any class

**Expected behaviour:**

All accounts would be limited to creating only warriors

**Steps to reproduce the problem:**

1. Change CharacterCreating.Disabled.ClassMask to cover some number of classes
2. Try creating a character of a "disabled" class with a valid race

**Branch(es):**

3.3.5 dynamic_spawning 

**TC rev. hash/commit:** 

TrinityCore rev. 37c31093ab54 2017-06-07 21:50:28 +0100 (dynamic_spawning branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Windows 7

**Comment by Treeston** [comment]
Did you test this with a non-GM account? GM accounts ignore the class mask.

**Comment by Treeston** [comment]
Cannot reproduce on aeaa8ecfabc2

**Comment by tkrokli** [comment]
The fact that there are some differences between a GM account and a normal account is often overlooked by most users.
At least it is interesting to see anyone document that they are testing the dynamic_spawning branch. 😃
