### ISSUE TITLE
[3.3.5a][Springing the Trap] Spark Doesn't light the signal fire 

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#19848]
**Description:**

The quest called [Springing the Trap] in Coldarra, Borean Tundra requires you to use Raelorasz's Spark to light the signal fire in order to lure Malygos, but the spark does not light the signal fire, just knocks you down and that's all.

**Current behavior:**

Borean Tundra requires you to use Raelorasz's Spark to light the signal fire in order to lure Malygos, but the spark does not light the signal fire, just knocks you down and that's all.

**Expected behavior:**

spark should light the signal fire

**Steps to reproduce the problem:**

1.http://www.wowhead.com/quest=11969/springing-the-trap
2. Step 2
3. Step 3

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0c6829f7f22f+ 2017-06-01 21:20:55 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

TrinityCore rev. 0c6829f7f22f+ 2017-06-01 21:20:55 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:** 
TDB 335.63

**Operating system:** 
Windows Server 2012 Standard

**Comment by Aokromes** [comment]
#5137  it was hard 1st match searching for Springing
