### ISSUE TITLE
[3.3.5] Difficulty tools?!

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#19841]
hi guys
A problem in dalaran - orgrimmar - stormwind ...

class mage if use blink! on dalaran!
see images 

https://ibb.co/g0Nesa

https://ibb.co/fHc7dF

Is the problem of my data!

I must say that I used the
data - tools = vmaps -maps-mmaps - dbc
AC-Web Ultimate Repack
0.8 and above.

windows 2012 server
last download of clone src 3.3.5
tdb 63 3.3.5 + updates.
parent 9c24ec5

**Comment by Aokromes** [comment]
we don't support repacks.

**Comment by irgc** [comment]
I know !

Wanna know the problem for what it is

ise used src!

just for tools use of last repacks! trinitycore ac-web..

**Comment by Aokromes** [comment]
Also, cannot reproduce on a proper configured trinitycore.

**Comment by irgc** [comment]
I realized that the source should I use?
maps - vmaps - dbc -mmaps?
