### ISSUE TITLE
Stealth missing spell sound effect?

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#19844]
**Description:**
Decided to start the work on the rogue stealth spell (http://www.wowhead.com/spell=1784/stealth) and managed to partially fix the functionality however I've noticed an issue when the stealth spell is activated, the sound effect does not play... Any idea what may be causing it? What handles the spell sound effects?

**Current behaviour:**

Character successfully enters the stealth phase and it is not detected by enemies, effect is applied however the sound effect when activating the spell is missing.

**Expected behaviour:**

Upon activating the stealth spell, the sound effect should play as the effects are applied. The missing stealth sound effect is (best guess) (http://www.wowhead.com/sound=3325/stealth)

**Steps to reproduce the problem:**

1. Create Rogue character
2. Reach level 5
3. Activate spell Stealth (ID: 1784)

**Branch(es):**

master

**TC rev. hash/commit:** 

TC>TrinityCore rev. 12d0306543df 2017-06-03 01:34:21 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10
![wowscrnshot_060417_020313](https://cloud.githubusercontent.com/assets/25698730/26758028/c28b8022-48c9-11e7-9774-a8d846d8470f.jpg)

**Comment by ArcaneFox** [comment]
I don't know who and when fixed this but thank you! It's working. There is sound and it's no longer break after combats.

TrinityCore rev. 71212ccd716c 2018-04-22 01:47:34 +0200 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2j  26 Sep 2016)
Using Boost version: 1.64.0
Using MySQL version: 5.6.28
Using CMake version: 3.9.6
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5235125273 bytes
mmaps directory located in ./mmaps. Total size: 6070137420 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Comment by ArcaneFox** [comment]
aslo https://github.com/TrinityCore/TrinityCore/issues/19712
