### ISSUE TITLE
[3.3.5] Crash Player::GetBoundInstance

### ISSUE THREAD

**Issue by Ali-Khazaee** [TrinityCore/TrinityCore#19842]
http://paste.ubuntu.com/24760081/

**Branch(es):** 3.3.5
**TC rev. hash/commit:**  aeaa8ecfabc2885aa24a86ce22034718cb4f62d8
**TDB version:**  63
**Operating system:** Debian 8.8

**Comment by Treeston** [comment]
The crashlog is from a fairly high optimization level and not too descriptive.

Do you have a reliable reproduction and/or a debug level crashlog?

**Comment by BioGram** [comment]
@Treeston, No, It's compiled in RelWithDebInfo

**Comment by ariel-** [comment]
PlayerGetBoundInstance:

```cpp
    BoundInstancesMap::iterator itr = m_boundInstances[difficulty].find(mapid);
```

Not the first time a crashlog accessing (unordered)map element directly through operator[] is seen, usually this is because of dirty compilation. try issuing a make clean to trigger a full rebuild. Updating your gcc may also help

**Comment by Treeston** [comment]
`m_boundInstances` is an array, not a map. No `operator[]` to be seen here.

**Comment by ariel-** [comment]
Indeed, confused with the actual map. Anyways a full rebuild of the core seems to have killed these mysterious crashes in the past

**Comment by Treeston** [comment]
@BioGram how many world threads are you running?

**Comment by BioGram** [comment]
@Treeston, 
```
LoginDatabase.WorkerThreads     = 1
WorldDatabase.WorkerThreads     = 1
CharacterDatabase.WorkerThreads = 2

LoginDatabase.SynchThreads     = 1
WorldDatabase.SynchThreads     = 1
CharacterDatabase.SynchThreads = 2

ThreadPool = 4

MapUpdate.Threads = 2
```

**Comment by Treeston** [comment]
Might be a race condition (reset as player is being deallocated). Multi-threading world can lead to stability issues like that.

**Comment by tkrokli** [comment]
@BioGram : Try to reproduce the crash with default values in worldserver.conf and see if it happens again.

**Comment by jackpoz** [comment]
> Might be a race condition (reset as player is being deallocated). Multi-threading world can lead to stability issues like that.

inside InstanceSaveManager::Update() ? isn't that single threaded anyway ?

**Comment by Shauren** [comment]
It is.

**Comment by Treeston** [comment]
I stand corrected, so should be a deterministic bug then. Curious, if the `Player`s are in a valid state I can't see any reason for a crash in there.

**Comment by irgc** [comment]
oh!

**Comment by Jildor** [comment]
Confirm:
(here the crashlogs #20592 and https://github.com/TrinityCore/TrinityCore/issues/20592#issuecomment-336486188

**Comment by Jildor** [comment]
It seems to happen just when the core reset save

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 26d, if this bug is still valid open a NEW ticket with updated core.
