### ISSUE TITLE
Spell: Elixir of Detect Undead

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19853]
**Description:** The aura "Detect Undead" is removed from the player 1 secs after drink the elixir.
https://woehead.way-of-elendil.fr/?spell=11389

**Current behaviour:** The aura is removed almost instantly from the player.

**Expected behaviour:** The aura must remains 1h.

**Steps to reproduce the problem:**

1. Drink http://www.wowhead.com/item=9154/elixir-of-detect-undead
2. Notice the aura will be removed after 1secs

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. a97439e8d63c

**Comment by Keader** [comment]
confirm
is weird because spell has 
Duration: ID (42)  3600000, 0, 3600000

**Comment by ariel-** [comment]
This is the culprit:

`Power POWER_HAPPINESS, Cost 11460 + 8 Per Second`

No player has that power available, so it 'runs out' and the aura is removed on Aura::Update
