### ISSUE TITLE
CrossFaction-bg one line error

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#19855]
Hey guys sorry too
I need this patch installed perfectly, but I do not know there is a fault line

Does anyone know what to do to fix it?

CrossFactionBG.patch 3.3.5

src/server/game/Entities/Player/Player.cpp: In member function ‘void Player::setFactionForRace(uint8)’:
rc/server/game/Entities/Player/Player.cpp:6666:56: error: ‘getFaction’ was not declared in this scope
     setFaction(rEntry ? rEntry->FactionID : getFaction());
                                                        ^
src/server/game/Entities/Player/Player.cpp:6666:57: error: ‘setFaction’ was not declared in this scope
     setFaction(rEntry ? rEntry->FactionID : getFaction());
                                                         ^

windows 2012server

last trinitycore src 3.3.5 clone dl
tdb63
parent c357939

**Comment by Aokromes** [comment]
This don't belongs to trinitycore project webpages, ask for help to the patch maker.

**Comment by irgc** [comment]
I'm sorry for my mistake Posts
The link me?
I could not find webpage patch maker
