### ISSUE TITLE
[3.3.5] - Player logout in combat

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19850]
**Description:**

When player are in combat, by example fighting with another player and press Alt+F4, the server logout the player when a minute passes, but the player when login still alive

**Expected behaviour:**

I think the player should be died

**Steps to reproduce the problem:**

1. Login a player and fight with someone
2. Press Alt+F4 and wait 1 min
3. Login and steel alive

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/aeaa8ecfabc2885aa24a86ce22034718cb4f62d8

**TDB version:**  TDB335.62

**Operating system:** Debian

**Comment by Aokromes** [comment]
Nope, depends of the amount damage he takes.

**Comment by Jildor** [comment]
@Aokromes 
You can explain me better, I do not understand you ;)

**Comment by Aokromes** [comment]
if you are a lvl 80 with 30000hp and one mob makes you 300hp/second and you relog you will continue to be alive. If another mob makes you 3000hp/second you will die.

**Comment by Jildor** [comment]
Then, if pass 1 minute and the NPC or player don't kill the "offline player", the server logout player without die?

**Comment by tkrokli** [comment]
That is what you have already seen. Test by making the other character kill the logged out character faster than 60 seconds (after you close the game client). You may want to try fighting a higher level NPC too.

**Comment by Jildor** [comment]
I have found a problem

if you login with X account and put in combat with someone, you can instant logout (without die) if you open a new wow and login with the same X account.

**Comment by ariel-** [comment]
Yeah logging in the same account auto disconnects any player from that account, what should happen is the player must remain in world with disconnect timer running, only if logging to the same char should the timer be reset and the new session associated with the old player.

**Comment by Jildor** [comment]
mmm
Then, with this change, you can login 2 or more different players with the same account, this can be the end of the world or its ok? xD

btw, this issue should be reopened or need create another issue??

**Comment by tkrokli** [comment]
New issue, but make sure you test on a retail account first (trial account if you don't have a paid one) to be sure you have tested what is blizzlike and what isn't. Compare what happens when you log in to the same character, different character and different account. Save that info and use it as example when comparing to what happens in a TrinityCore setup.

**Comment by Jildor** [comment]
oks, as soon as I check it, I create a new issue

**Comment by Jildor** [comment]
Done ;)
#19926
