### ISSUE TITLE
[Master] Monk Artifact appearance instantly logout account.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19861]
**Description:**
The Artifact Weapon "Fists of the Heavens"[ItemID:133948] of monk class, Windwalker spec, crash the player account.  This is the only Artifact with this problems, we tested all of it.

**Current behaviour:** (Tell us what happens.)

When you get the Artifact Weapon "Fists of the Heavens"[ItemID:133948] or if you see his appearance the player account crash show the error dialog in the image.

![streaming error](https://user-images.githubusercontent.com/19369492/26912457-830c11b6-4be2-11e7-885b-e989ba427bae.jpg)

**Expected behaviour:** (Tell us what should happen instead.)

You should be able to see the appearance of the Artifact Weapon "Fists of the Heavens"[ItemID:133948] whitout trouble.

**Steps to reproduce the problem:**

1. Add item 133948 (This instantly logout account)
2. Or try to see the appearance directly.

**Branch(es):**  Master

**TC rev. hash/commit:**  151441697febb99048908c9a4ddcbf8080de4145

**TDB version:**  720.00 + updates

**Operating system:** Windows 10

**Comment by matukaa** [comment]
You're trying the wrong weapon. There are more versions of each artifact (i believe because of testing purposes).
You can tell if you have the ckrrect by ID: all the correct artifacts are 128xxx (or smaller, but if its 13xxxx then it's surely wrong).

http://www.wowhead.com/item=128940/fists-of-the-heavens

Try 128940 :)

**Comment by HannibalRoG** [comment]
But, this behavior its normal?

**Comment by tkrokli** [comment]
@matukaa :  Those weapons are 1 Main hand and 1 Off hand items:
https://wow.gamepedia.com/Fists_of_the_Heavens :
"Iramaat believed he had done the impossible and named the two fist weapons  [[Al'burq]](https://wow.gamepedia.com/Al%27burq) and  [[Alra'ed]](https://wow.gamepedia.com/Alra%27ed), the Fists of the Heavens."

**Al'burq** - Main Hand / Fist Weapon: (https://wow.gamepedia.com/Al%27burq)
http://www.wowhead.com/item=128940/fists-of-the-heavens

**Alra'ed** - Off Hand / Fist Weapon: (https://wow.gamepedia.com/Alra%27ed)
http://www.wowhead.com/item=133948/fists-of-the-heavens

Isn't there something else wrong, making some items not work in current core?

**Comment by matanshukry** [comment]
Not relevant anymore?

item 133948 can't be added: `Cannot create item '133948' (amount: 1)`
item 128940 doesn't cause any crash.
