### ISSUE TITLE
Matis the Cruel quest

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#19873]
d57307f63d8deb51003d61163adccce4e2c1bd47
Quest can not be completed
On the server there is a modification to the auto-level, but it should not affect the execution of the quest.
Video:
https://youtu.be/DjrSOzDFyUA

**Comment by Regrad** [comment]
Quest 9711

**Comment by ariel-** [comment]
Ignore template is evil

**Comment by ariel-** [comment]
This happens because it sets IMMUNE_TO_PC flag before casting the spell credit (31336), the spell effect complete quest has TARGET_UNIT_SRC_AREA_ENEMY which fails because player is now invalid attack target and fails checks

**Comment by Regrad** [comment]
I apologize for ignoring the template, but my knowledge of English does not allow me to describe it by template. I use Google translate. I will try to correct myself.
It's not a forum, i know. Sorry.

**Comment by Treeston** [comment]
@ariel- sounds like easy fix then, assigning to you.

@Regrad it's fine, thanks for the report :+1:
