### ISSUE TITLE
Core/Spell: Auras effects when the object is destroyed

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19876]
**Description:** When a summoned NPC cast a spell which applies an aura inflicting damage (or heal or any other effect) let's say for 60s; if this NPC is killed and despawns (object destroyed), the aura will not inflict any damage.

**Current behavior:** Auras effects don't work once the caster object is destroyed.

**Expected behavior:** Auras effects must continue event if the caster object is destroyed.

**Steps to reproduce the problem:**
You can notice this issue with Anub encounter in ToC during the transition with Swarm Scarabs.
1. `.npc add temp 34605` this NPC https://woehead.way-of-elendil.fr/?npc=34605
2. `.cast back 65775` (notice you're taking damage from the aura)
3. `.die` the NPC (notice once the NPC disappears, you will keep the aura, but no damage is dealt)

@r00ty-tc  This could be interesting to include into dynamic spawns.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. b8535dab46dd

**Comment by ariel-** [comment]
Not a spawn issue per-se, but rather an aura issue, damage **should** get calculated on cast and remain that way on affected targets, will investigate
