### ISSUE TITLE
mapextractor is not extracting specific .db2 files correctly

### ISSUE THREAD

**Issue by knuxyl** [TrinityCore/TrinityCore#19889]
TrinityCore rev. f59e2ddd3112 2017-06-15 00:34:47 +0200 (master branch) (Unix, Release, Static) (bnetserver)

```
TrinityCore rev. f59e2ddd3112 2017-06-15 00:34:47 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Opened casc storage '/home/knuxyl/Games/Legion/Data'
Detected client build 24330 for locale enUS

Extracting dbc/db2 files...
locale enUS output path /home/knuxyl/Games/Legion/dbc/enUS

```

When extracting .db2 files with mapextractor, it hangs on specific files and just keeps increasing its file size. When you cancel it and start again, it continues (I guess it's a simple file exists check) and then stops on the next problematic .db2 file. These are the files it won't extract correctly for me.

```
ChrClassesXPowerTypes.db2
CreatureImmunities.db2
DurabilityQuality.db2
EmotesTextSound.db2
GroupFinderCategory.db2
GuildColorBackground.db2
GuildColorBorder.db2
GuildColorEmblem.db2
SpellItemEnchantmentCondition.db2
SpellKeyboundOverride.db2
SpellRange.db2
UiModelScene.db2
```

If it sees all the files in my locale (enUS) it starts doing something for koKR locale and start populating the koKR folder with the same files and the exact same problem on the same files. Since I don't have the koKR locale, it's strange it is populating this folder.

```
Extracting dbc/db2 files...
locale koKR output path /home/knuxyl/Games/Legion/dbc/koKR
Unable to open file DBFilesClient\Achievement.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\Achievement_Category.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureJournal.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureMapPOI.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOI.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOIState.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaTable.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\Artifact.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearance.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearanceSet.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\AuctionHouse.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BarberShopStyle.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetAbility.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetNPCTeamMember.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetSpecies.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlemasterList.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\BroadcastText.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\Cfg_Categories.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\CharShipmentContainer.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\CharTitles.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChatChannels.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClassTitle.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClassVillain.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClasses.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrRaces.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrSpecialization.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrUpgradeTier.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\Contribution.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\Creature.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file DBFilesClient\CreatureFamily.db2 in the archive for locale koKR: FILE_NOT_FOUND
```
By copying files into each locale so it would skip them (it shouldn't even be populating them), it extracted cameras succesfully but then it stopped again on extracting gt. This has to be some kind of memory problem or something. The file HpPerSta.txt started growing in size. I did cat HpPerSta.txt and found that all it contained was repeating L.

```
Opened casc storage '/home/knuxyl/Games/Legion (copy 1)/Data'
Extracting camera files...
Read CinematicCamera.db2 file...
Done! (27 CinematicCameras loaded)
output path /home/knuxyl/Games/Legion (copy 1)/cameras
Extracted 27 camera files
Opened casc storage '/home/knuxyl/Games/Legion (copy 1)/Data'
Extracting game tables...
```

Using the older files that were a problem on the newer extractor and starting vmap4extractor throws a ton of errors. (a lot of the .xxx files were found) Below are the files that could not be found.

```
Can't open FILE0001B0AA.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE0001B0A9.xxx
Can't open FILE00071731.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE00071730.xxx
Can't open FILE000C3A11.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE000C3A0F.xxx
Extracting FILE000C3A03.xxx
Can't open FILE000C3A05.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE000C3A03.xxx
Extracting FILE000C3ADE.xxx
Can't open FILE000C3AE0.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE000C3ADE.xxx
Extracting FILE000C3AE7.xxx
Can't open FILE000C3AE9.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE000C3AE7.xxx
Extracting FILE000C3AE1.xxx
Can't open FILE000C3AE3.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: FILE000C3AE1.xxx
```

I'm not sure if the tools just haven't been updated properly or if mapsextractor has an error in its coding. vmap4extractor continues trying to get different locale maps

```
Couldn't open RootWmo!!!
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_CathedralDistrict.wmo
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_Oldtown.wmo
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_DwarvenDistrict.wmo
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_Keep.wmo
Extracting WORLD\WMO\AZEROTH\BUILDINGS\STORMWIND\SW_STAIRCASE.WMO
Extracting WORLD\WMO\AZEROTH\BUILDINGS\STORMWIND\SW_GRAVEYARDWALLS.WMO
Extracting WORLD\WMO\PANDARIA\GENERIC\GAZEBO\PA_GAZEBO.WMO
WMOInstance::WMOInstance: couldn't open ./Buildings/Uthershrine.wmo
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_TradeDistrict.wmo
Can't open FILE0006F90A.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: SW_TradeDistrict.wmo
WMOInstance::WMOInstance: couldn't open ./Buildings/Sw_Tradedistrict.wmo
Extracting WORLD\WMO\AZEROTH\BUILDINGS\HUMAN_BARRACKS\HUMAN_BARRACKS.WMO
Extracting World\wmo\Azeroth\Buildings\Stormwind\SW_TradeDistrict.wmo
Can't open FILE0006F90A.xxx, failed to get size: FILE_CORRUPT!
No such file.
Could not open all Group file for: SW_TradeDistrict.wmo
```

Source built and run on Xubuntu 16.04.1 LTS x86_64
```
knuxyl@lapras:~$ uname -a
Linux lapras 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Caydan** [comment]
Make sure you have the full client.

**Comment by Aokromes** [comment]
test after 410bc49

**Comment by knuxyl** [comment]
DBC extraction is now working except for it still fills the other locales folders even though they aren't installed. It works now except for the locales, thanks!

**Comment by Aokromes** [comment]
Tested with static compiled relwithdebug windows extractor, it worked correctly.

**Comment by tkrokli** [comment]
The resulting files work, but it is interesting to see that mapextractor detects 11 locales as present and tries to extract dbc/db2 files for all of them, even if only 1 is successful. I presume it is too difficult to get mapextractor to include a working check for which locales actually are present and in use, saving some time in the extraction process and avoid the 10 sections with extraction errors (1440).

Anyway, here is my mapextractor log from build 3d3ab2909649 :
- Page link: https://gist.github.com/tkrokli/4515e51818fc38859804dfdd78acfb4f
- File direct: https://gist.github.com/tkrokli/4515e51818fc38859804dfdd78acfb4f#file-mapextractor_log-txt
- Raw text: https://gist.githubusercontent.com/tkrokli/4515e51818fc38859804dfdd78acfb4f/raw/9dd9fc8a6bc9a48a870e2c9767e40dbba671de7a/Mapextractor_log.txt

**Comment by MolecularMan** [comment]
Hello. i have same problem with increasing filesize on lastest version. See #19953

**Comment by Whizer07** [comment]
Моя проблема решилась так #19997 
Исправьте это.
[Google translate]
My problem was solved so #19997 
Fix it.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by tkrokli** [comment]
I wish I knew or could test it. I reinstalled my computer about a month ago and don't have a copy of 7.2.5 available anymore.

**Comment by ggadea** [comment]
Have a similar problem on a Mac. I copied all the files generated by Xcode to a folder named "bin" inside my wow client folder. When running ./vmap4extractor I get: 
Fatal error: Invalid GameObjectDisplayInfo.db2 file format!

When I run ./mapextractor then I get:
...
Extracting dbc/db2 files...
locale enUS output path /Applications/Wow_DHTank/dbc/enUS
Unable to open file DBFilesClient\ItemVisualEffects.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ObjectEffectGroup.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ObjectEffectPackage.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\StringLookups.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\VideoHardware.db2 in the archive for locale enUS: FILE_NOT_FOUND
...
Invalid CinematicCamera.db2 file format. Camera extract aborted. FILE_NOT_FOUND
...

Details in the text file attached.
[errors.txt](https://github.com/TrinityCore/TrinityCore/files/1408838/errors.txt)

Could the problem be the client I have is missing those files? What build number is the last one known to allow the extraction to work? I have the Data files that came with build 25195

(Trying on a Mac after many hours of frustration fighting CMake on a PC)
Thanks

**Comment by Aokromes** [comment]
you are using unsuported client.

**Comment by ggadea** [comment]
thanks for the quick reply.

**Comment by TiagoHelel** [comment]
Hi, I have a similar problem too.

http://TrinityCore.org                    \/__/

Opened casc storage '/home/chibil/server/wow_client/Data'
Opened casc storage '/home/chibil/server/wow_client/Data'
Detected client build 34963 for locale ptBR

Opened casc storage '/home/chibil/server/wow_client/Data'
Extracting camera files...
Read CinematicCamera.db2 file...
Fatal error: Invalid CinematicCamera.db2 file format! UNKNOWN
Failed to read header

I just download the clean client from battle.net. 
Maybe something is missing?

Full log
[error.txt](https://github.com/TrinityCore/TrinityCore/files/4904618/error.txt)


Thanks
