### ISSUE TITLE
[3.3.5] Players' levitate movement has wrong animation

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#19883]
3.3.5 23f2646adf39

When under the effect of levitate (`.aura 1706`), players show the wrong animation when moving.
They *should* not show any animation, simply "hovering" forward. Instead, they show the standard running animation, giving the appearance that they're running in midair.

**Comment by Nyeriah** [comment]
This is wrong, until Cataclysm they just walked in the air as you see them doing right now

**Comment by Killyana** [comment]
Looks Nyeriah is right https://www.youtube.com/watch?v=sZcNzFVlhbs
> In Patch 4.3 Levitate becomes a true levitation as you'll just float in the air instead of running on it!

**Comment by Shauren** [comment]
Well then, working as intended
