### ISSUE TITLE
[3.3.5 crash] Could not load MMAP name:Northrend

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#19885]
**Description:**

Server crashes every day around the same hour 7 PM, the same thing shows in the log before crash:
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. bf187a195ee8+ 2017-06-09 18:27:51 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)
TrinityCore rev. 23f2646adf39+ 2017-06-14 14:31:46 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  
TDB 335.63

**Operating system:** 
Windows Server 2012

crash log:
https://gist.github.com/daddycaddy/ae169038d4af7efcd0ab60d683dce2c2
https://gist.github.com/daddycaddy/81fe2bfe3b61f17154b30799eb320ad1

**Comment by Aokromes** [comment]
useless log, supply crashlog.

**Comment by daddycaddy** [comment]
https://gist.github.com/daddycaddy/ae169038d4af7efcd0ab60d683dce2c2

**Comment by ccrs** [comment]
````
000007F60A190F70  000000185748E910  Object::GetUInt32Value+10  c:\trinitycore\trinitycore\src\server\game\entities\object\object.cpp line 292
000007F60A914037  000000185748EA00  PlayerbotHolder::ProcessBotCommand+C7  c:\trinitycore\trinitycore\src\plugins\playerbot\playerbotmgr.cpp line 144
000007F60A912A6F  000000185748ECC0  PlayerbotHolder::HandlePlayerbotCommand+A2F  c:\trinitycore\trinitycore\src\plugins\playerbot\playerbotmgr.cpp line 368
000007F60A912D5D  000000185748ED10  PlayerbotMgr::HandlePlayerbotMgrCommand+9D  c:\trinitycore\trinitycore\src\plugins\playerbot\playerbotmgr.cpp line 249
````

ummm interesting... wonder how could this affect mmaps...

**Comment by Killyana** [comment]
lines like this are spamming the server logs all the time, it's not related to any crash : 
```
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
```

**Comment by irgc** [comment]
The problem is Patch > playerbot!

**Comment by daddycaddy** [comment]
hello,
the thing is I did not have this crash before, it's just happened recently, and before that TC and Playerbot worked just fine, but if you think it's the playerbot then close the issue and I'm sorry to bother you
thanks

**Comment by tkrokli** [comment]
Did you extract new dbc, maps, vmaps & mmaps after the recent changes to vmaps? If not, that could also contribute to your issues.

**Comment by daddycaddy** [comment]
yes I did but I'm doing it now again just to be sure, I update my source every day according to TC updates and compile new version every day, first time I had crashes

**Comment by Aokromes** [comment]
well, since it's playerbots crash, it's something unsuported here.
