### ISSUE TITLE
[3.3.5] DB/Quests: Cultists Among Us

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#19880]
**Description:**

When you take from the Pre-quest a soldier in need ( quest id: 11789 ) the Hawthorn's Anti-Venom you are not able to take this quest from the shrine anymore
- http://www.wowhead.com/quest=11789/a-soldier-in-need
- http://www.wowhead.com/quest=11920/cultists-among-us
- http://www.wowhead.com/npc=25825/medic-hawthorn

**Current behaviour:**

At this moment you are not able to take the quest Cultist among us when you take Hawthorn's Anti-Venom from the chest.

**Expected behaviour:**

You should be able to take the quest cultist among us when you have completed a soldier in need.

**Steps to reproduce the problem:**

1. Make an Alliance char, level up to level 70.
2. tele to Valiance Keep == > `.tele valiancekee`
3. Take the quest A Soldier in Need (11789) from Medic Hawthorn (NPC ID 25825) outside Valiance Keep.
4. Once accepted, go to the middle boat and below deck to acquire Hawthorn's Anti-Venom from the chest.
5. Once you loot Hawthorn's Anti-Venom from the chest, you will see the altar on the left no longer has the ! mark for the quest Cultists Among Us (11920)
6. When you delete the Hawthorn's Anti-Venom from your bag, you will see that the exclamation mark ! above the shrine comes back.
7. You can't get quest from the altar anymore when you turn in or complete quest 11789 at Medic Hawthorn.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. 1660bb7d27d6+ 2017-06-07 02:33:47 +0200 (3.3.5 branch) (Unix, Release, Static)

**TDB version:** TDB 335.63

**Operating system:** Unix ubuntu server 16.04 LTS

**Comment by codeman8214** [comment]
I have a fix for this I will post it when I get home and get a chance to update it

**Comment by Killyana** [comment]
Try:
``` sql
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `id` IN (11920);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 19 AND `SourceEntry`= 11920;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(19, 0, 11920, 0, 0, 14, 0, 11789, 0, 0, 1, 0, 0, '', "Cultists Among Us");
