### ISSUE TITLE
[3.3.5] MMAPS/VMAPS: Cave/instance clogged up pathing after latest commits

### ISSUE THREAD

**Issue by Funkeln** [TrinityCore/TrinityCore#19884]
**Description:**

Pathing in caverns and general pathing has been really clogged up after latest changes. 

**Current behaviour:**

Creatures often float mid air and pathing to the upper floor. Mobs inside instances also seem to have a knack to not find a proper path and chain evade.

**Expected behaviour:**

Mobs should path properly as they used to, not float in the air, not stuck on evade...

**Steps to reproduce the problem:**

1. Extract vmaps and mmaps after the latest commits
2. Teleport to Hellfire Ramparts
3. Try to attack mobs

Try any other cave. I know caves never worked that well, but they have never been worse than now.

Dragons from cot pathing up the desert: http://i.imgur.com/qI7KYm7.jpg

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/23f2646adf3987b349196f2765e89a6061c17a29  (mmaps enabled)

**TDB version:**  TDB 335.63

**Operating system:** Windows 10 Enterprise

**Comment by Funkeln** [comment]
Extract them and try... Deadmines was completely broken also, every mob tries to evade on pull. I noticed the files wheigth way less than they used to, if that means anything...

**Comment by ccrs** [comment]
can you mark some example locations on deadmines? I cant reproduce on last commit

**Comment by ccrs** [comment]
also size is actually bigger, extraction problem on your side?

**Comment by Aokromes** [comment]
#19744
