### ISSUE TITLE
7.2.5 24330 incompatible with current build

### ISSUE THREAD

**Issue by knuxyl** [TrinityCore/TrinityCore#19891]
TrinityCore rev. f59e2ddd3112 2017-06-15 00:34:47 +0200 (master branch) (Unix, Release, Static) (bnetserver)

Using Legion 7.2.5 24330 and a lot of tinkering with trinitycore to get it to read the data (mixing with like 6 older db2 files, current won't extract them) the worldserver launches and I can login, but the realm says it is incompatible. 

Upon successfull login
https://s7.postimg.org/m2bevudtn/Screenshot_2017-06-15_02-30-10.png

After clicking the realm
https://s29.postimg.org/7qan37g0n/Screenshot_2017-06-15_02-30-31.png

**Comment by Aokromes** [comment]
stop opening multiple threads for same issue.
