### ISSUE TITLE
[3.3.5] Paladin - Righteous Vengeance

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#19898]
**Description:**

Righteous Vengeance don't works with Judgements.
I think the problem is with the Judgements SPELL_DAMAGE_CLASS_RANGED
With Judgements SPELL_DAMAGE_CLASS_MELEE works fine

**Current behaviour:**

When a Judgement with SPELL_DAMAGE_CLASS_RANGED hit the target (critical) don't proc Righteous Vengeance

**Expected behaviour:**

When a Judgement with SPELL_DAMAGE_CLASS_RANGED hit the target (critical) should proc Righteous Vengeance

**Steps to reproduce the problem:**

1. Learn talent Righteous Vengeance
2. Use a Judgement (critical hit) on someone

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/aeaa8ecfabc2885aa24a86ce22034718cb4f62d8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Keader** [comment]
Fix:

```sql

UPDATE `spell_proc` SET `AttributesMask`=0x2 WHERE `SpellId`=-53380;

```
