### ISSUE TITLE
[Master] Worlserver Crash when character logued in.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19899]
**Description:**

When any character logued in the worldserver crash without output on console

**Current behaviour:**

https://gist.github.com/HannibalRoG/c8efadcb474976b978d18ac6ff53a05f

**Branch(es):**

Master

**TC rev. hash/commit:** 

410bc499768ce2b5d1e5247815efebd0ba9b65a3

**TDB version:**  TDB 7.2.0+updates

**Operating system:** Windows 10 creators

**Comment by Nuppi** [comment]
The same under windows 7, 32 and 64 bit

**Comment by wowharley** [comment]
can confirm on Windows 10 pro 64bit and 32bit
00df865abb49f2ceb64b2537d5c085023cbb63f0 on build hash

**Comment by tkrokli** [comment]
Even when confirming, please supply crash log, especially if on other OS than the OP.

**Comment by HannibalRoG** [comment]
I must specify that this happens when entering the world not when authenticating.

**Comment by MartGon** [comment]
This only happens when logging on a character on a zone with NPCs or creatures around, I guess. You can create and log on a fresh DH,(whose starting area will be empty of creatures or NPCs spawned) and the server won't crash until you tele a zone with creatures spawned.
