### ISSUE TITLE
[DEV] Core/Movements: Add the possiblity to choose run/walk random move

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19909]
**Description:** Some NPCs must have Run speed on with random movements, This cannot be done with the actual DB scripting.

Proposed solution: Add random_movement_type on creature table: 0= walk, 1=run

**Branch(es):** both

**TC rev. hash/commit:**  rev. 9fc35785307e

**Comment by Faq** [comment]
Any example npc with such behavior?

**Comment by Killyana** [comment]
This https://www.youtube.com/watch?v=Tm_SxTkr9eU

**Comment by Killyana** [comment]
Work done by Rushor: https://gist.github.com/Killyana/acdfedd5a8c7f87fa310397dd23d1493

**Comment by jackpoz** [comment]
strange that it's a float but it's handled as a boolean

**Comment by Killyana** [comment]
Imagine 20 spawns, 10 use walk speed and 10 run speed, in this case we must add 10 extra SAI per guid instead of just set a Boolean into a field.

**Comment by Killyana** [comment]
@Sorikoff Can you open PR similar to the one that implemented chasing speed, using this https://gist.github.com/Killyana/acdfedd5a8c7f87fa310397dd23d1493 as start ?

**Comment by Sorikoff** [comment]
@Killyana, sure I could try. But as far as I understand this is for master branch nor 3.3.5?

**Comment by ccrs** [comment]
both

**Comment by Sorikoff** [comment]
You would 3 options, correct? Walk, CanRun, AlwaysRun?

**Comment by Killyana** [comment]
Yes

**Comment by Killyana** [comment]
Implemented on https://github.com/TrinityCore/TrinityCore/pull/23081
