### ISSUE TITLE
Character kills during teleportation

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#19905]
9fc35785307efd7f8af009efa7ee4d693931c83b 3.3.5 master

The character kills at teleportation, and as for unknown reasons. The log says that the character is broken to death. Video of this bug:
https://youtu.be/aDqMDClLj3c

Windows 10 x64

**Comment by Regrad** [comment]
"Anticheat.FallDelayed = 0" remove bug

**Comment by Treeston** [comment]
On it, workaround above should solve this for the time being. Need to figure out why this didn't happen in testing.

**Comment by Warpten** [comment]
because, uh.... it probably wasnt tested?

**Comment by Treeston** [comment]
No, I actually tested the change. Just got home, investigating now.

**Comment by Keader** [comment]
Btw, default value should be changed Treeston ^^

**Comment by Treeston** [comment]
Reverted original commit 27cbfc3 in 4b9b1d4. While investigating, I found a bunch of _really_ strange client behavior in edge cases (literally; it happens when walking off of really low edges) that makes false positive free detection highly unlikely using this approach.
