### ISSUE TITLE
Core/guardian: Gardian evading

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#19919]
**Description:** If you use Fire Elemental, or serpents trap against a player, this guardians will evade all the time.

**Current behaviour:** Guardians are evading if the focused player moves

**Steps to reproduce the problem:**

1. Connect 2 players
2. .cast 32982
3. Once the Fire Elemental is in combat move the other character and notice that the guardian will evade all the time

Probably related to https://github.com/TrinityCore/TrinityCore/commit/69fd6245dc41dca658cadb4e99c1ee6593fe000b
Must check getAttackersForHelper returning null

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 9fc35785307e

**Comment by Treeston** [comment]
052fc24
