### ISSUE TITLE
Propsal to Change SAI NPC 49480 Tarindrella

### ISSUE THREAD

**Issue by Taaboy** [TrinityCore/TrinityCore#19918]
My Propsal to change the SAI for Tarindrella NPC 49480

I have been working on quest 28728 , In retail once you accept quest you teleport near to NPC 49479 to hand in quest to follow on quest chain.
In current smartAI at ID 12 you go onto a timeactionlist 4948000 ID 0 then ID 1
Which it is suppose to teleport you with her spell ID - 92420 Tarindrella's Nature Teleport . The problem i have found is either no teleport or she teleports solo and leaves the player behind ,  location with or with out XYZ O set.
Remove from timeactionlist function on ID 12 to Event 19 Action 62 Target 21, which in place. It's Function to upon accepting quest 28728 then teleports map ID 1 to closet_player to XYZ and O location.
Which tests works perfectly  and the benefit npc 49480 despawns, and quest ready to hand in.

The rest of the SAI has not been modified in anyway except for ID 12 line(Last Line).

```sql

/* Table creature_template */ UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 49480; 

/* Table smart_scripts */ DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 49480);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(49480, 0, 0, 0, 1, 0, 100, 512, 3000, 3000, 3000, 3000, '', 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - ooc  - despawn if in area 188'),
(49480, 0, 1, 0, 0, 0, 100, 0, 3000, 6000, 8000, 9000, '', 11, 33844, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - IC  - Cast Entangling Roots'),
(49480, 0, 2, 0, 38, 0, 100, 0, 1, 3, 0, 0, '', 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - on data set  - Say text 3'),
(49480, 0, 3, 0, 38, 0, 100, 512, 1, 3, 0, 0, '', 11, 92573, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - on data seto  - Cast to Summon Nature\'s Bite'),
(49480, 0, 4, 0, 38, 0, 100, 512, 1, 3, 0, 0, '', 11, 92573, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - on data set  - Cast to Summon Nature\'s Bite'),
(49480, 0, 5, 0, 38, 0, 100, 512, 1, 3, 0, 0, '', 11, 92573, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - In aggro  - Cast to Summon Nature\'s Bite'),
(49480, 0, 6, 7, 54, 0, 100, 0, 0, 0, 0, 0, '', 1, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - just summoned  - Say text 0'),
(49480, 0, 7, 0, 61, 0, 100, 512, 0, 0, 0, 0, '', 8, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - just summoned  - react passif'),
(49480, 0, 8, 0, 38, 0, 40, 0, 1, 2, 0, 0, '', 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - on data set  - Say text 1'),
(49480, 0, 9, 0, 38, 0, 100, 0, 1, 1, 0, 0, '', 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - on data set  - Say text 2'),
(49480, 0, 10, 0, 20, 0, 100, 0, 28727, 0, 0, 0, '', 1, 4, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - ooc  - Say text 4'),
(49480, 0, 11, 0, 0, 0, 100, 0, 3000, 6000, 5000, 6000, '', 11, 66056, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 'Tarindrella - IC  - Cast Entangling Roots'),
(49480, 0, 12, 0, 19, 0, 100, 512, 28728, 0, 0, 0, '', 62, 1, 0, 0, 0, 0, 0, 21, 10, 0, 0, 10541.5, 875.09, 1309.06, 0.035, 'Tarindrella - On quest taken  - Teleport');
```

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. cf5aa01be7ee+ 2017-06-18 22:17:48 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  
7.20
**Operating system:** 
Win10

**Comment by Killyana** [comment]
This is a hack, try to cast the spell 92420 to see if it works correctly or not.
The only issue that could happen is if the player take the quest when the npc is in combat, in this case this will fix the issue:
``` sql
UPDATE `smart_scripts` SET `action_param2`=2 WHERE `entryorguid`=49480 AND `source_type`=0 AND `id`=12;

**Comment by HannibalRoG** [comment]
As i said in another issue that can be becose this problem with SAIs in master https://github.com/TrinityCore/TrinityCore/issues/16997
The SAI already in DB funtion sometimes and sometimes not, probably for that general issue with SAIs
If we follow your line of work we will have to change any SAIs in DB.
I think its better to wait to have that problem solved.

**Comment by Taaboy** [comment]
OK, Fair enough maybe it is a hack , but i have tried using a cast spell 92420 instead of the suggestion of teleport action and she teleports out , and leaves the player behind , i have been in combat out of combat i have killed everything in sight in the cave 8 different times , my player is not in combat, she doesn't seems that she is in combat. i have used the gm command .combatstop   and .gm on ,tried again still to no avail her current use of her spell doesn't works as intended of retail. 

As a stop gap or suggestion, I'm not saying the whole dam DB , I'm saying this case , and HannibalRoG yes SAI , I feel the SAI is not currently working as expected but is is better now then earlier releases, This maybe fixed later on without needing a of scripts or stop gaps. So does this fix  work, it teleports when you accept quest to the quest giver 100% of the time , well 100/100 for 20 Players created and done quest chain , as I said a proposal and if any other people can offer working tested suggestion, that can point me and others in the direction, and waiting for others to solve your problems is like saying hey who is gonna produce your food if your not  willing to get out of the chair and help.

Problems are solved with brains,hard work and trial and error, and that SAI could be old and not intended for legion maybe Cata and has been just sitting there looking pretty hoping someone will come along and pamper it bit to get it to work. 

If you can help and find a better way of doing the quest 28728 and teleport back after accepting quest I'm all ears and willing to help.

**Comment by Taaboy** [comment]
I have now got it working with original spell around 90% still there is a bug in cave but once you are just outside cave entrance, it works 100%.

```sql
-- Tarindrella SAI
SET @ENTRY := 49480;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,512,3000,3000,3000,3000,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - ooc  - despawn if in area 188"),
(@ENTRY,0,1,0,0,0,100,0,3000,6000,8000,9000,11,33844,0,0,0,0,0,2,0,0,0,0,0,0,0,"Tarindrella - IC  - Cast Entangling Roots"),
(@ENTRY,0,2,0,38,0,100,0,1,3,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - on data set  - Say text 3"),
(@ENTRY,0,3,0,38,0,100,512,1,3,0,0,11,92573,2,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - on data seto  - Cast to Summon Nature's Bite"),
(@ENTRY,0,4,0,38,0,100,512,1,3,0,0,11,92573,2,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - on data set  - Cast to Summon Nature's Bite"),
(@ENTRY,0,5,0,38,0,100,512,1,3,0,0,11,92573,2,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - In aggro  - Cast to Summon Nature's Bite"),
(@ENTRY,0,6,7,54,0,100,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tarindrella - just summoned  - Say text 0"),
(@ENTRY,0,7,0,61,0,100,512,0,0,0,0,8,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - just summoned  - react passif"),
(@ENTRY,0,8,0,38,0,40,0,1,2,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - on data set  - Say text 1"),
(@ENTRY,0,9,0,38,0,100,0,1,1,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tarindrella - on data set  - Say text 2"),
(@ENTRY,0,10,0,20,0,100,0,28727,0,0,0,1,4,0,0,0,0,0,23,0,0,0,0,0,0,0,"Tarindrella - ooc  - Say text 4"),
(@ENTRY,0,11,0,0,0,100,0,3000,6000,5000,6000,11,66056,0,0,0,0,0,23,0,0,0,0,0,0,0,"Tarindrella - IC  - Cast Entangling Roots"),
(@ENTRY,0,12,0,19,0,100,512,28728,0,0,0,85,92420,0,0,0,0,0,7,0,0,0,10541.5,875.09,1309.06,0.035,"Tarindrella - On quest taken  - Teleport");
```

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19918#issuecomment-309352886
blizzlike bug: 
http://www.wowhead.com/npc=49480/tarindrella#comments:id=1554172

**Comment by Killyana** [comment]
Btw, the quest works without any problem on 4.3.4

**Comment by Faq** [comment]
on 4.3.4 might be fixed that spell?
