### ISSUE TITLE
[3.3.5] Killing Spree range issue

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#19913]
**Description:** Spell Killing Spree is missing some hits when target is moving. The spell responsible for the main hand damage is: 57841, and off hand damage: 57842.
Issue is: 57841 has 5 yards range, but 57842 has "self range". So if target is moving, 57841 will hit, but 57842 will fail (out of range).

**Steps to reproduce the problem:**

1.  Use .cast 57841 in a creature with 3~4y distance. Only 1 damage will be applied
2. Use .cast 57841 very closer of creature. 2 Damages will be applied.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4b9b1d485df1f00637cd34cb5dcd7204e7cad2f5

Suggested fix: Change range to combat range (5 yards) like 57841 instead Self range.

```diff

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index d53f714..a14eddc 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3647,10 +3647,10 @@ void SpellMgr::LoadSpellInfoCorrections()
         spellInfo->RangeEntry = sSpellRangeStore.LookupEntry(155); // Hunter Range (Long)
     });
 
-    // Desecration
     ApplySpellFix({
-        55741, // (Rank 1)
-        68766  // (Rank 2)
+        55741, // Desecration (Rank 1)
+        68766, // Desecration (Rank 2)
+        57842  // Killing Spree (Off hand damage)
     }, [](SpellInfo* spellInfo)
     {
         spellInfo->RangeEntry = sSpellRangeStore.LookupEntry(2); // Melee Range
@@ -3671,7 +3671,7 @@ void SpellMgr::LoadSpellInfoCorrections()
     // Water Globule (Ichoron)
     ApplySpellFix({ 54258, 54264, 54265, 54266, 54267 }, [](SpellInfo* spellInfo)
     {
-        // in 3.3.5 there is only one radius in dbc which is 0 yards in this 
+        // in 3.3.5 there is only one radius in dbc which is 0 yards in this
         // use max radius from 4.3.4
         spellInfo->Effects[EFFECT_0].RadiusEntry = sSpellRadiusStore.LookupEntry(EFFECT_RADIUS_25_YARDS);
     });
```

**Comment by ariel-** [comment]
Every triggered spell that had range == 1 should have range bumped to 50000yd no? (basically skipping range checks like before)

**Comment by Shauren** [comment]
No, there are triggered spells (trinket procs that deal damage for example) that should respect their range (because they might be triggered by a dot tick while far away)
