### ISSUE TITLE
[3.3.5] Worldserver start database error

### ISSUE THREAD

**Issue by iBrabus** [TrinityCore/TrinityCore#19911]
**Description:**

Error of worldserver starting.

**Current behaviour:**

**After some day deleted my old database, than tried to start from new, after populating database worldserver exit and error log error gives me next:
In mysql_stmt_prepare() id: 3, sql: "SELECT entry, groupid, id, text, type, language, probability, emote, duration, sound, BroadcastTextId, TextRange FROM creature_text"
Unknown column 'entry' in 'field list'**

But entry has is in field list in sql files..

**Expected behaviour:**

**Server should turn on! (hahaha)**

**Branch(es):**

**3.3.5**

**TC rev. hash/commit:** 

**TrinityCore rev. ad6ecbf09b24 2017-03-04 12:22:21 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)**

**TDB version:**  

**TDB_full_world_335.62_2016_10_17**

**Operating system:** 

**Windows 10 Home 64bit**

**Comment by Aokromes** [comment]
update your core and database, enable autoupdater.
