### ISSUE TITLE
[3.3.5] Seed of Corruption not proc'ing explosion on unit death

### ISSUE THREAD

**Issue by Funkeln** [TrinityCore/TrinityCore#19927]
**Description:**

http://wowwiki.wikia.com/wiki/Seed_of_Corruption

Seed of Corruption should detonate if the target takes the X amount of damage specified or if it dies.

**Current behaviour:**

It only detonates if the target takes X amount of damage

**Expected behaviour:**

It should also detonate when the target dies.

**Steps to reproduce the problem:**

1. Pull a group of mobs
2. Cast SoC on one of them
3. Kill the mob affected by SoC
4. Notice there was no explosion

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9f765a162092e8b65cc9bc924e0c456f719b3678

TDB 335.63

**Operating system:** CHANGEME OS

Win10

**Comment by ariel-** [comment]
Looks like broken with 0229cb865edfd41b6f399b7be0056c5c962cbb04:

Unit is killed before proc, thus removing all auras on death = no proc, what we're missing is retail-like mechanic where unit death is delayed one world tick, that way we allow the aura to proc.

**Comment by ariel-** [comment]
#13441

**Comment by sogladev** [comment]
bug still occurs 
```
TC> server debug
TC> TrinityCore rev. 8824889f53a9 2024-06-22 14:03:17 +0200 (335 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80037
Using CMake version: 3.22.1
Compiled on: Linux 6.5.0-41-generic
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port {}
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /mnt/shared/maps. Total size: 291014951 bytes
vmaps directory located in /mnt/shared/vmaps. Total size: 657788601 bytes
mmaps directory located in /mnt/shared/mmaps. Total size: 1970857520 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.24041
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
```
