### ISSUE TITLE
[3.3.5][CRASH] Server crashs after Drakkari Colossus cast Merge(54878).

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#19924]
Worldserver will crash after Drakkari Colossus cast Merge(54878).
It not happens before ver. 052fc24315ace866ea1cf610e85df119b68100c9

**Steps to reproduce the problem:**

1. Attack Drakkari Colossus  in Gundrak.
2. Waiting for Drakkari Colossus  summon Drakkari Elemental.
3. Attack Drakkari Elemental, and put its health below 50 PCT.
4. Then worldserver will crash after Drakkari Colossus cast Merge(54878).

**Branch(es):**
3.3.5

**TC rev. hash/commit:** faf299459bb96355b8c5d86add3a22ae4bcd0491

**TDB version:**  TDB 335.63 + updates

**Operating system:** WIN 10

**Comment by Aokromes** [comment]
supply debug mode crashlog.

**Comment by sirikfoll** [comment]
`std::unique_ptr<PathGenerator> m_preGeneratedPath;` is nullptr at Spell::EffectCharge
CrashLog: https://gist.github.com/sirikfoll/fdf30d0d5c210d84566c97e70d218e2a

**Comment by ariel-** [comment]
Wondering if master has the same crash, as m_preGeneratedPath is only initialized for explicit target charge effects; and merge is implicit one
