### ISSUE TITLE
[master] trainer not working

### ISSUE THREAD

**Issue by therafah** [TrinityCore/TrinityCore#19929]
**Description:**

Cant train Apprentice Riding. 

**Current behaviour:**

It's not possible to learn Riding Spells.

**Expected behaviour:**

Since you hit level 20, you should be able to learn Riding Spells with your trainer.

**Steps to reproduce the problem:**

1. Create a new character
2. Level up 20 
3. Get some gold
4. Train the Riding Spells

**Branch(es):**

master.

**TC rev. hash/commit:** 

TrinityCore rev. cf5aa01be7ee

**TDB version:**   TDB 720.00
**Operating system:** Windows

**Comment by codeman8214** [comment]
Are you using 7.2.5 or 7.2.0

**Comment by therafah** [comment]
7.2.5

**Comment by codeman8214** [comment]
Are you trying to learn this in stormwind, because I went to east vale logging camp and it worked for me.

**Comment by therafah** [comment]
I tried only in Stormwind, im going to try in east vale

**Comment by therafah** [comment]
> Are you trying to learn this in stormwind, because I went to east vale logging camp and it worked for me.
I tried in East Vale and it's not working.

**Comment by codeman8214** [comment]
hmmm let me try stormwind and see if it works for me.

**Comment by AussieGlenn** [comment]
I am able to learn apprentice riding, 7.2.5 latest build

**Comment by buenodart** [comment]
Im trying to learn some riding skills and I cant. Even in east vale logging camp
I tried with other races and i cant did it.
I click on trainer and the window chat doesn't open!!

**Comment by ArcaneFox** [comment]
I can confirm too. In 7.1.5 I was able to learn riding in SW & Honor Hold, but currently the chat window isn't opening.

**Comment by Killyana** [comment]
Dup #20193
