### ISSUE TITLE
3.3.5 a fall and killed characters on start 

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#19923]
**Description:**

CHANGEME   a start falling characters for start logon on server and killeds theme random  full health killed.

1. characters bug start for kill random
![57089baeb4eb878a48b4886c34e38240](https://user-images.githubusercontent.com/3795778/27337823-3a2f3b68-55dc-11e7-95ec-4bf1bdb34a52.png)

Branch 3.3.5, TrinityCore rev. 23f2646adf39+ 2017-06-14 14:31:46 +0200 (3.3.5 branch) (Unix, Release, Static)

worldserver and authserver

**TDB version:**  TDB 335.63

**Operating system:** Linux version 4.4.0-62-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017

**Comment by Aokromes** [comment]
update your core.
