### ISSUE TITLE
[3.3.5] Pets should attack from behind the target $150

### ISSUE THREAD

**Issue by Funkeln** [TrinityCore/TrinityCore#19925]
**Description:**

Pets in PvE should try to position themselves behind targets to attack them and avoid being parried.
https://us.battle.net/forums/en/wow/topic/1965837204

**Current behaviour:**  Pets always attack from the front.

**Expected behaviour:**  The movement generator for pets should try to position them behind NPC targets when attacking

**Steps to reproduce the problem:**

1. Summon a hunter or warlock pet
2. Send it to attack a creature

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/9f765a162092e8b65cc9bc924e0c456f719b3678

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by ariel-** [comment]
Minions in general should actively try to search for the back of the monster.

> Pets always attack from the front.

Not completely true, they only take the shortest path available, so if you manage to position the monster between you and your minion, it'll attack from the back.

**Comment by Funkeln** [comment]
Oh, ok, thanks for confirming ariel.

@tkrokli sneak edits annoying as always.

**Comment by Killyana** [comment]
This happen also if you move the npc while the pet is attacking, it will always reloacte in front.

**Comment by MrSmite** [comment]
This is only the case when the NPC is being tanked by something else. In a solo case, the pet MUST remain in front or you end up with the "dance of death" where the mob tries to keep the pet in front and the pet keeps moving behind, leading to them moving into other adds.

Watch any of [Steevnash's Hunter Solo Tutorials](https://www.youtube.com/user/DIsteevnash/videos?sort=da&view=0&flow=list) or [Aliena's Raid Guides](https://www.youtube.com/playlist?list=PL9D63669ADB127CEC) and you will see the pet does not attempt to position itself behind a mob when it is the mob's focus.

**Comment by GlassFace** [comment]
It is true , this happened at Pets that has player owner
I was check it with storm, earth and fire at wod in retail

**Comment by metapaws** [comment]
Here is a video of the current behavior - https://www.twitch.tv/videos/153936642

The mob will always force front no matter player position. If you keep the mob standing still and rotate the mob, the pet will not move to the front, but if you move the mob, the pet will force itself to the front.

**Comment by MrSmite** [comment]
> Here is a video of the current behavior

Problem is the OP specifically mentioned the issue was for 3.3.5. While the behavior today might be different, it was certainly not this way back in 335 as seen in the videos I linked.

**Comment by Nyeriah** [comment]
> Problem is the OP specifically mentioned the issue was for 3.3.5. While the behavior today might be different, it was certainly not this way back in 335 as seen in the videos I linked.

Have you watched the video? It clearly shows it's a *TrinityCore* 3.3.5 server

**Comment by ariel-** [comment]
Nyeriah: that video (the TrinityCore one) was posted by metapaws, correctly pointing current behaviour, not by MrSmite (who posted retail player videos)

**Comment by Nyeriah** [comment]
That's essentially what I said. I don't understand what he tried to imply with his quote and comment.

That video shows the current broken behavior quite well. How it should work (and I particularly think we are past the point of confirming this) is that the pet should reposition itself if it's not the main threat target of the creature.

**Comment by MrSmite** [comment]
@Nyeriah, @ariel- 

Sorry, that was my fault. I didn't notice the "Trinitycore" label because I don't use a browser to watch Twitch streams, I use MPC-HC and livestreamer. In his comment when he said "current behavior" I thought he meant as in live servers.

At any rate Nyeriah, we seem to be in agreement; the pet should only reposition itself if it is not the primary target of the creature. If this check was left out, soloing would be extremely difficult in high population areas due to the constant repositioning.

**Comment by Keader** [comment]
With it, Halion encounter is a real challenge to Hunter BM/Lock demon...
Pets die in every breath xd

**Comment by necropola** [comment]
Gonna try to spot the cause for the issue and hopefully fix it. I'm still **very** new to TC development so any help to point me to the relevant parts of the code is appreciated.

I think the first step is to reproduce/demonstrate the issue on current TC-3.3.5 in the most simple scenario possible. Please have a look at the linked video which shows a warlock sending her pet in from behind a target dummy. It's on current TC-3.3.5 and I think we agree that the pet shouldn't prefer to attack from the front, right?
https://youtu.be/Xpj7SMhtTjI

**Comment by metapaws** [comment]
https://www.bountysource.com/issues/46407645-3-3-5-pets-should-attack-from-behind-the-target

**Comment by Keader** [comment]
@Aokromes

**Comment by Treeston** [comment]
will look into this next week, i don't think it'd be _too_ hard to pull off

**Comment by Treeston** [comment]
Thanks, will check.
