### ISSUE TITLE
7.2.5.24367 mapextractor.exe not working

### ISSUE THREAD

**Issue by ymfjly** [TrinityCore/TrinityCore#19932]
**Description:**
mapextractor.exe can not  extractor DBFilesClient\Map.db2
and  vmap4extractor.exe & vmap4assembler.exe & mmaps_generator.exe can not exteracotr vmaps and mmaps files.

I have setup wow 7.2.5 Clinet on F:\Netgame\World of Warcraft_725\World of Warcraft\
and have copy mapextractor.exe & vmap4extractor.exe & vmap4assembler.exe & mmaps_generator.exe on F:\Netgame\World of Warcraft_725\World of Warcraft\.
but mapextractor.exe can not  extractor DBFilesClient\Map.db2,I don know what happen ,I need help.

TrinityCore rev. cf5aa01be7ee 2017-06-18 22:17:48 +0200 (master branch) (Win64, Debug, Static) (Map & DBC Extractor)

**Operating system:** Win10 System

<details>

TrinityCore rev. cf5aa01be7ee 2017-06-18 22:17:48 +0200 (master branch) (Win64, Debug, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Opened casc storage 'F:/Netgame\World of Warcraft_725\World of Warcraft\Data'
Detected client build 24367 for locale enUS

Extracting dbc/db2 files...
locale enUS output path F:\Netgame\World of Warcraft_725\World of Warcraft\dbc\enUS
Unable to open file DBFilesClient\Achievement.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Achievement_Category.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureJournal.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureMapPOI.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOI.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOIState.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaTable.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Artifact.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearance.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearanceSet.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AuctionHouse.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BarberShopStyle.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetAbility.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetNPCTeamMember.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlePetSpecies.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BattlemasterList.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\BroadcastText.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Cfg_Categories.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CharShipmentContainer.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CharTitles.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChatChannels.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClassTitle.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClassVillain.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrClasses.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrRaces.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrSpecialization.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ChrUpgradeTier.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Contribution.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Creature.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CreatureFamily.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CreatureType.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CriteriaTree.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CurrencyCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\CurrencyTypes.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWord.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\DeclinedWordCases.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Difficulty.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\DungeonEncounter.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\EmotesTextData.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Exhaustion.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Faction.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\FactionGroup.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\FriendshipRepReaction.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\FriendshipReputation.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GMSurveyAnswers.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GMSurveyQuestions.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GameObjects.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GameTips.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrAbility.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrAbilityCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrBuilding.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrClassSpec.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrClassSpecPlayerCond.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrEncounter.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrFollower.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrMechanicType.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrMission.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrMissionType.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrPlotUICategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrSpecialization.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrString.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GarrTalent.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GlobalStrings.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GlyphExclusiveCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GroupFinderActivity.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GroupFinderActivityGrp.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\GroupFinderCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Heirloom.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\HolidayDescriptions.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\HolidayNames.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\InvasionClientData.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemBagFamily.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemClass.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemLimitCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemNameDescription.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemPetFood.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemRandomProperties.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemRandomSuffix.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemSearchName.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemSet.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemSparse.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemSubClass.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ItemSubClassMask.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\JournalEncounter.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\JournalEncounterCreature.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\JournalEncounterSection.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\JournalInstance.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\JournalTier.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\KeystoneAffix.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Languages.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\LfgDungeonGroup.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\LfgDungeons.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\LockType.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MailTemplate.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Map.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MapChallengeMode.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MapDifficulty.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\MapDifficultyXCondition.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Mount.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\PlayerCondition.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\PrestigeLevelInfo.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\PvpTalent.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestInfo.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestLine.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestObjective.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestSort.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\QuestV2CliTask.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ResearchBranch.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ResearchField.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ResearchProject.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ResearchSite.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Resistances.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Scenario.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ScenarioStep.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ServerMessages.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SkillLine.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SourceInfo.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpecializationSpells.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Spell.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellDispelType.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellFlyout.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellFocusObject.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellItemEnchantment.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellMechanic.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellRange.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\SpellShapeshiftForm.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Startup_Strings.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Talent.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TaxiNodes.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TextureFileData.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TotemCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Toy.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TradeSkillCategory.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TransmogSet.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\TransmogSetGroup.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Trophy.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\UnitPowerBar.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Vignette.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\WMOAreaTable.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\WorldBossLockout.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\WorldElapsedTimer.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\WorldSafeLocs.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\WorldStateUI.db2 in the archive for locale enUS: FILE_NOT_FOUND
Extracted 0 files

Opened casc storage 'F:/Netgame\World of Warcraft_725\World of Warcraft\Data'
Detected client build 24367 for locale zhCN

Extracting dbc/db2 files...
locale zhCN output path F:\Netgame\World of Warcraft_725\World of Warcraft\dbc\zhCN
Extracted 0 files

Opened casc storage 'F:/Netgame\World of Warcraft_725\World of Warcraft\Data'
Extracting camera files...
Read CinematicCamera.db2 file...
Done! (27 CinematicCameras loaded)
output path F:\Netgame\World of Warcraft_725\World of Warcraft\cameras
Extracted 0 camera files
Opened casc storage 'F:/Netgame\World of Warcraft_725\World of Warcraft\Data'
Extracting game tables...
output path F:\Netgame\World of Warcraft_725\World of Warcraft\gt
Extracted 0 files

Opened casc storage 'F:/Netgame\World of Warcraft_725\World of Warcraft\Data'
Extracting maps...
Read Map.db2 file...
Failed to open 'DBFilesClient\Map.db2' in CASC storage: FILE_NOT_FOUND
Fatal error: Invalid Map.db2 file format! FILE_NOT_FOUND

</details>

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by therafah** [comment]
Try to open your extrator using command prompt, thats how it worked for me, Open your DOS as an administrator, navigate throw your file, and then open your extrator.

**Comment by Taaboy** [comment]
1st Have you copied across as well to the wow folder libmysql.dll. 
2nd Has your Client finished downloading all the content (approx 42gig) folder size.
3rd have you login into the retail and to make sure the wtf/config is set.
4th to make is easier to extract TC Team has added under TrinityCore\contrib\extractor.bat file.
4th

**Comment by ymfjly** [comment]
I have used command prompt to open extrractor.bat as an administrator in World of Warcraft Folder.
The Client I downloaded by Blizzard downloader, the client only 38.7gig, 698 Files, 20 Folders.

My World of Warcraft client are chinese ver, so the dbc\zhCN folder have 592 files ,the dbc\enUS folder only 448 files, and map.db2 is found in World of Warcraft\dbc\zhCN folder.
Maybe mapextractor.exe can not support zhCN client well ?
If this is the reason mapextractor.exe can not extract map.db2?
Please help me, thanks.

**Comment by Taaboy** [comment]
Question Blizzard Downloader or do you mean battlenet app

**Comment by ymfjly** [comment]
I have found the problem,
In mapexactor source, system.cpp
int main(int argc, char * arg[])
{
........
if (CONF_extract & EXTRACT_MAP)
    {
        OpenCascStorage(FirstLocale);
/*In this code, FirstLocale is LOCALE_enUS,but my client is zhCN. there are not map.db2 in enUS, So this function return failed, I Changed FirstLocale to LOCALE_zhCN, mapexactor exacted map files success.*/
        ExtractMaps(build);
        CascStorage.reset();
    }
}
Thanks every one who helped me.

**Comment by 120910383** [comment]
i also use zhCN version, You are very close to the answer, only need to type arguments '-l zhCN'.
