### ISSUE TITLE
[Master] Holiday - Midsummer, Ribbon Pole Periodic eternal Visual bug.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19934]
**Description:**

In the event Midsummer festival you get an eternal animation in your PJ

**Current behaviour:**

When you use Ribbon pole from any of Ribbon pole in the event your player get aura id 45406 [Holiday - Midsummer, Ribbon Pole Periodic Visual] and your player stay eternaly with this visual even if you restart the server.

**Expected behaviour:**

When you use the Ribbon pole and move away from it the visual aura should be canceled.
See this video with the whole guide for this event https://www.youtube.com/watch?v=AKr01Mn1Rr8

**Steps to reproduce the problem:**

1. Go to any zone with Midsummer festival event active (now is active in calendar) or use .event start command.
2. Use the Ribbon Pole.

**Branch(es):**

Master

**TC rev. hash/commit:** 

a9bf342ae6eb2fed7b6f22ac0fec4a53c8352b40

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

**Comment by CDawg** [comment]
I thought this was fixed or somewhat working. I will dig through some of my deprecated code and see if there was a fix for this...
BTW, I noticed that this is not working on the latest 3.3.5a pull, not just 7x issue.

**Comment by Keader** [comment]
In 3.3.5 is working with this: https://github.com/TrinityCore/TrinityCore/issues/6876#issuecomment-311494060

**Comment by offl** [comment]
Fixed in 5b7e4efcc4db8c4f1fb25bbdf7cfca60dfb776dc?

**Comment by tkrokli** [comment]
Yes. As stated in the description for PR **#20923** .
