### ISSUE TITLE
[Master] Server crash when you use .tele command to certain location.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19940]
**Description:**

When you use command .tele orgrimmar or .tele durotar the worldserver.exe crash.

**Current behaviour:**
Crash log https://gist.github.com/HannibalRoG/c563004dddda017f13799cc599fef5e9

**Steps to reproduce the problem:**

1. Add rbac permission 737 in rbac_linked_permission table for id 195
2. Use .tele orgrimmar or .tele durotar
3. See crash log

**Branch(es):**

Master

**TC rev. hash/commit:** 

6feb947af6479ab315c470e4c13ade0eb935369c

**TDB version:**  7.2.0+updates

**Comment by HannibalRoG** [comment]
I think it is not a problem of the .tele command but the area of orgrimmar, when approaching it from any point the server crash.

**Comment by jackpoz** [comment]
>"Attempted to put a NULL-pointer in ByteBuffe..."

**Comment by searum** [comment]
yeah is not .tele problem it happens on UPDATE_OBJECT, i think related to transports (and this commit https://github.com/TrinityCore/TrinityCore/commit/777d839a5fda0d09c9f5340ac0942187f10e211e from @Shauren)

**Comment by codeman8214** [comment]
That is the issue because I reverted it back and it does not crash anymore after count was added it is handled incorrectly
