### ISSUE TITLE
[master] DB/Gameobject: Page 9

### ISSUE THREAD

**Issue by Luchass** [TrinityCore/TrinityCore#19947]
**Description:**

http://ru.wowhead.com/object=148502

**Current behaviour:**

Object (Id:148502) doesn't have proper values in gameobject_template

**Expected behaviour:**

Proper values

**Steps to reproduce the problem:**

1. SELECT * FROM `gameobject_template` WHERE `entry`=148502;

**Branch(es):**

master

**TC rev. hash/commit:** 

8fb42e5

**TDB version:**  Last + updates

**Operating system:** Windows 10

**Fix**

``` sql
DELETE FROM `gameobject_template` WHERE `entry`=148502;
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `Data32`, `RequiredLevel`, `VerifiedBuild`) VALUES
(148502, 10, 26705, 'Page 9', '', '', 0.5, 43, 0, 0, 1, 0, 0, 1, 7154, 0, 1, 231933, 0, 0, 1, 24589, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24367);
```

**Comment by Aokromes** [comment]
we don't use replace into, if some value needs to be updated we use update.

**Comment by Luchass** [comment]
It was fully changed in legion. Can I use "delete/insert" or still only "update". 😩
