### ISSUE TITLE
[3.3.5] Explosion of Living Bomb should not remove Dragon's Breath

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#19949]
**Description:** Living Bomb explosion is not working correctly with Dragon's Breath. This issue was already reported (https://github.com/TrinityCore/TrinityCore/issues/8891) long time ago (yep, its a really old bug), but it got closed don't know why. I believe this will be the last report, just pray the god @ariel-. @Keader maybe you have a fix for this :smile:.

**Current behaviour:** Explosion from Living Bomb is removing Dragon's Breath disorient effect.

**Expected behaviour:** Explosion from Living Bomb should not remove Dragon's Breath disorient effect. Proof: https://youtu.be/4oFigWAzqc0?t=18.

**Steps to reproduce the problem:**

1. Cast Living Bomb on an enemy.  
2. Cast Dragon's Breath just before Living Bomb ends and so it explodes.
3. See how Dragon's Breath is removed.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/24b11a4dc0f3862ec9d52748c4763e2c28b25458

**TDB version:**  TDB 335.63

**Comment by Keader** [comment]
i never saw it before xd

**Comment by Keader** [comment]
@Raydor Try with:

```cpp
class spell_mage_dragon_breath : public AuraScript
{
    PrepareAuraScript(spell_mage_dragon_breath);

    bool CheckProc(ProcEventInfo& eventInfo)
    {
        SpellInfo const* spellInfo = eventInfo.GetSpellInfo();
        if (spellInfo && spellInfo->SpellIconID == 3000 && spellInfo->SpellFamilyName == SPELLFAMILY_MAGE)
            return false;
        return true;
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_mage_dragon_breath::CheckProc);
    }
};
```

```sql
DELETE FROM `spell_script_names` WHERE `scriptname`='spell_mage_dragon_breath';
INSERT INTO `spell_script_names` (`spell_id`,`scriptname`) VALUES
(-31661,'spell_mage_dragon_breath');
```

**Comment by Keader** [comment]
And looks like it's correct

https://youtu.be/HMKFr7yIalw?t=17m55s
