### ISSUE TITLE
New command server debug

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#19957]
I think it can be a good idea a command called .server debug (gm only), it will return:
Compiler flags,
used libraries,
OS (exact windows version, not only win32 or win64 or unix),
used ports.
Maps, vmaps, mmaps versions and size on disk (to see if they used modified versions) and enabled or no.
dbcs and their locales.
cameras enabled or no.
TDB version.

**Branch(es):**

both

**TC rev. hash/commit:** 

19fefbb N/R

**TDB version:**  N/R

**Operating system:** N/R

**Comment by Ascathor** [comment]
Just an idea, I could imagine a parameter enabling an actual fileoutput into world folder would be an interesting feature to it. It could be referenced for issues.

**Comment by Aokromes** [comment]
Also boost version, openssl, TDB.
