### ISSUE TITLE
[master] mapextractor issue

### ISSUE THREAD

**Issue by MolecularMan** [TrinityCore/TrinityCore#19953]
**Description:**

mapextractor from last git version have issue with extracting dbc

**Current behaviour:**

file ArtifactCategory.db2 have size of 180+GB and its grow, extracting still in progress.
`TrinityCore rev. 8fb42e5ce251 2017-06-23 05:36:35 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Opened casc storage '/root/World of Warcraft/Data'
Detected client build 24367 for locale enUS

Extracting dbc/db2 files...
locale enUS output path /root/World of Warcraft/dbc/enUS
Unable to open file DBFilesClient\Achievement.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Achievement_Category.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureJournal.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AdventureMapPOI.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOI.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaPOIState.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\AreaTable.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\Artifact.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearance.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file DBFilesClient\ArtifactAppearanceSet.db2 in the archive for locale enUS: FILE_NOT_FOUND
^C
`
i read issue #19932 and run mapextractor with -l ruRU, errors gone, but file ArtifactCategory.db2 still growing:

` 
/root/wow-server24367/bin/mapextractor -l ruRU
TrinityCore rev. 8fb42e5ce251 2017-06-23 05:36:35 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Opened casc storage '/root/World of Warcraft/Data'
Detected client build 24367 for locale ruRU

Extracting dbc/db2 files...
locale ruRU output path /root/World of Warcraft/dbc/ruRU

`
this is result of command du -s dbc/ruRU/*:
`
1008    dbc/ruRU/Achievement.db2
8       dbc/ruRU/Achievement_Category.db2
92      dbc/ruRU/AdventureJournal.db2
8       dbc/ruRU/AdventureMapPOI.db2
96      dbc/ruRU/AnimKit.db2
4       dbc/ruRU/AnimKitBoneSet.db2
4       dbc/ruRU/AnimKitBoneSetAlias.db2
4       dbc/ruRU/AnimKitConfig.db2
4       dbc/ruRU/AnimKitConfigBoneSet.db2
4       dbc/ruRU/AnimKitPriority.db2
4       dbc/ruRU/AnimKitReplacement.db2
772     dbc/ruRU/AnimKitSegment.db2
12      dbc/ruRU/AnimReplacement.db2
4       dbc/ruRU/AnimReplacementSet.db2
48      dbc/ruRU/AnimationData.db2
4       dbc/ruRU/AreaFarClipOverride.db2
52      dbc/ruRU/AreaGroupMember.db2
124     dbc/ruRU/AreaPOI.db2
12      dbc/ruRU/AreaPOIState.db2
572     dbc/ruRU/AreaTable.db2
176     dbc/ruRU/AreaTrigger.db2
12      dbc/ruRU/AreaTriggerActionSet.db2
4       dbc/ruRU/AreaTriggerBox.db2
4       dbc/ruRU/AreaTriggerCylinder.db2
4       dbc/ruRU/AreaTriggerSphere.db2
4       dbc/ruRU/ArmorLocation.db2
4       dbc/ruRU/Artifact.db2
36      dbc/ruRU/ArtifactAppearance.db2
12      dbc/ruRU/ArtifactAppearanceSet.db2
193264072       dbc/ruRU/ArtifactCategory.db2
`
Also, when i run "make", some errors will be displayed:

```
[ 20%] Built target mapextractor
/root/src/TrinityCore/src/tools/vmap4_extractor/model.cpp:50:82: warning: multi-character character constant [-Wmultichar]
     while (m2start + 4 < f.getSize() && *reinterpret_cast<uint32 const*>(ptr) != '02DM')
                                                                                  ^
[ 20%] Building CXX object src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/wmo.cpp.o
[ 20%] Building CXX object src/server/proto/CMakeFiles/proto.dir/Client/global_extensions/method_options.pb.cc.o
[ 21%] Building CXX object src/server/proto/CMakeFiles/proto.dir/Login/Login.pb.cc.o
[ 21%] Building CXX object src/server/proto/CMakeFiles/proto.dir/RealmList/RealmList.pb.cc.o
[ 21%] Building CXX object src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/gameobject_extract.cpp.o
[ 21%] Building CXX object src/tools/vmap4_extractor/CMakeFiles/vmap4extractor.dir/vmapexport.cpp.o
/root/src/TrinityCore/src/tools/vmap4_extractor/gameobject_extract.cpp:89:18: warning: multi-character character constant [-Wmultichar]
     MODEL_MD20 = '02DM',
                  ^
/root/src/TrinityCore/src/tools/vmap4_extractor/gameobject_extract.cpp:90:18: warning: multi-character character constant [-Wmultichar]
     MODEL_MD21 = '12DM',
                  ^
/root/src/TrinityCore/src/tools/vmap4_extractor/gameobject_extract.cpp:91:18: warning: multi-character character constant [-Wmultichar]
     MODEL_WMO  = 'MVER'
                  ^
```

**Steps to reproduce the problem:**

1. Compile lastest master branch
2. cd to WoW-client directory
3. run "/path/to/mapextractor"

**Branch(es):**

master

**TC rev. hash/commit:** 
TrinityCore rev. 8fb42e5ce251 2017-06-23 05:36:35 +0200 (master branch) (Unix, Release, Static) (Map & DBC Extractor)

**Operating system:** 
Debian 8 x64
gcc version 4.9.2 (Debian 4.9.2-10)
cmake version 3.0.2
GNU Make 4.0 version

**Comment by Aokromes** [comment]
#19889

**Comment by MolecularMan** [comment]
i have this error on TrinityCore rev. 8fb42e5 , this is newer 410bc49 
client build 24367
