### ISSUE TITLE
Fatal error: no member named 'reference_wrapper' in namespace 'std'

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#19950]
**Description:**

When attempting to compile, get the following error:
users.../trinity/trinitycore/src/server/game/AI/CreatureAIImpl.h:28:10: fatal error: 
      no member named 'reference_wrapper' in namespace 'std'
    std::reference_wrapper<typename std::add_const<First>::type> const p...

**Expected behaviour:**
Should not stop compiling

**Steps to reproduce the problem:**
1.  Build Xcode Project Files:
cmake ../ -GXcode \
-DMYSQL_ADD_INCLUDE_PATH=/usr/local/include \
-DMYSQL_LIBRARY=/usr/local/lib/libmysqlclient_r.dylib \
-DREADLINE_INCLUDE_DIR=/usr/local/opt/readline/include \
-DREADLINE_LIBRARY=/usr/local/opt/readline/lib/libreadline.dylib \
-DBOOST_INCLUDEDIR=/usr/local/include \
-DBOOST_LIBRARYDIR=/usr/local/lib \
-DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include \
-DOPENSSL_SSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib \
-DOPENSSL_CRYPTO_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib \
-DZMQ_LIBRARY=/usr/local/opt/zeromq/lib/libzmq.dylib \
-DZMQ_INCLUDE_DIR=/usr/local/opt/zeromq/include \
-DZLIB_ROOT=/usr/local/Cellar/zlib/1.2.8 \
-DCMAKE_INSTALL_PREFIX=/Users/<username>.../trinity \
-DTOOLS=0 \
-DWITH_WARNINGS=1

2. Build Binaries with Xcode:
xcodebuild -target install -config Release

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
24b11a4dc0f3862ec9d52748c4763e2c28b25458

**TDB version:**  
335.63

**Operating system:** 
Mac OSX 10.12.5

**Comment by DDuarte** [comment]
XProject?

**Comment by obsidean** [comment]
Sorry.  Xcode

**Comment by Shauren** [comment]
5236e6ee22cb3efec138552d9a1a174a748ffb5a

**Comment by obsidean** [comment]
That works, thanks.

**Comment by Faq** [comment]
Then close?

**Comment by Jildor** [comment]
No, need cherry-pick https://github.com/TrinityCore/TrinityCore/commit/5236e6ee22cb3efec138552d9a1a174a748ffb5a in 3.3.5 branch

**Comment by snwflake** [comment]
Still not cherry-picked.
Push

**Comment by tkrokli** [comment]
@Gacko , would you mind taking a look at that? Or have you left the OSX space?

**Comment by Gacko** [comment]
No. I can take a look.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/908558ee0b63b7a1f2854a107654e3565ca79b39
