### ISSUE TITLE
[3.3.5]Core/Script The Lich King encounter, Val'kyr bug.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#19960]
**Description:**

In Phase 2 of the LK 10N he summons a Shadowguard Val'kyr NPC 36609 but they do not touch the floor. Also the LK sometimes fall under floor.

**Current behaviour:**

The Lich King beginning the second phase makes use of Summon Val´kyr http://www.wowhead.com/spell=69037/summon-valkyr but they appear in the air about 10 meters from the ground and choose their victim from the air without touching the floor in no time.

**Expected behaviour:**

They must select their victim and then go down to the floor to drag it to the edge and launch it, so that melee can do damage to them as well as range.

**Steps to reproduce the problem:**

1. Start figth with Lich King (he sometimes fall under floor)
2. Damage 20% of his life to enter in face 2
3. Watch de bug

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

431ecd6fb80be03f4e9cf4481e66cbd89f12874e

**TDB version:**  TDB_full_335.63_2017_04_18+updates

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
#7266

**Comment by HannibalRoG** [comment]
@Aokromes you scare me, you are fast!!!

**Comment by sirikfoll** [comment]
@HannibalRoG  Use https://github.com/TrinityCore/TrinityCore/issues/7266#issuecomment-289837717 to fix this issue with the valkyr
