### ISSUE TITLE
[The Obsidian Sanctum] Formation 

### ISSUE THREAD

**Issue by GreatRedem** [TrinityCore/TrinityCore#19977]
**Description:** When you start attacking single mob, the whole mobs and drake bosses will come for you

this happens after this commit: 07708483227f3dbd2c9554abab2cba475a602018

**Expected behaviour:** They shouldn't come for you
**Branch(es):** 3.3.5
**TC rev. hash/commit:**  e35092c6a164e929f9684b350093b2beefee5d86
**TDB version:**  63
**Operating system:** Debian 9

**Comment by Aokromes** [comment]
blizzlike.

**Comment by Rushor** [comment]
do you applied https://github.com/TrinityCore/TrinityCore/commit/07708483227f3dbd2c9554abab2cba475a602018#diff-7881cfd40bf2311454dda40139ea4316 ?

maybe the groupai needs to be changed after that commit for specific creatures.

**Comment by Treeston** [comment]
@Rushor or maybe you forgot to check which member was calling for help before aggroing members. 🤔

**Comment by Rushor** [comment]
ty @Treeston
