### ISSUE TITLE
[Trial of the Crusader] Jormungar stuck after submerge

### ISSUE THREAD

**Issue by GreatRedem** [TrinityCore/TrinityCore#19976]
**Description:** Jormungars boss gets stuck in floor after submerge

this happens after this commit: c35793941b3aae9b54dce92389aa528d40050754

**Expected behaviour:** They shouldn't get stuck in under floor
**Branch(es):** 3.3.5
**TC rev. hash/commit:**  e35092c6a164e929f9684b350093b2beefee5d86
**TDB version:**  63
**Operating system:** Debian 9

**Comment by Demonid** [comment]
Confirmed

**Comment by Keader** [comment]
@Warpten

**Comment by Demonid** [comment]
Btw, you can see a lot of random issues on LK too, like Adds getting inside the floor and being unable to be taunted.

**Comment by HannibalRoG** [comment]
I can confirm that with LK encounter with adds.

**Comment by Warpten** [comment]
Uhhhh.

**Comment by Golrag** [comment]
try
```diff
diff --git a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp
index 17ce945890..6ffdcfb145 100644
--- a/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp
+++ b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp
@@ -651,7 +651,10 @@ struct boss_jormungarAI : public BossAI
         events.SetPhase(PHASE_SUBMERGED);
         events.ScheduleEvent(EVENT_EMERGE, 5*IN_MILLISECONDS, 0, PHASE_SUBMERGED);
         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
-        me->GetMotionMaster()->MovePoint(0, ToCCommonLoc[1].GetPositionX()+ frand(-40.0f, 40.0f), ToCCommonLoc[1].GetPositionY() + frand(-40.0f, 40.0f), ToCCommonLoc[1].GetPositionZ());
+        float x = ToCCommonLoc[1].GetPositionX() + frand(-40.0f, 40.0f);
+        float y = ToCCommonLoc[1].GetPositionY() + frand(-40.0f, 40.0f);
+        float z = me->GetMap()->GetHeight(me->GetPhaseMask(), x, y, ToCCommonLoc[1].GetPositionZ() + 5.0f);
+        me->GetMotionMaster()->MovePoint(0, x, y, z);
         WasMobile = !WasMobile;
     }
```

**Comment by irgc** [comment]
@Confirmed

**Comment by Golrag** [comment]
I tested it with https://github.com/TrinityCore/TrinityCore/pull/20024 and it works, could work without it not sure

**Comment by Jildor** [comment]
This can be close with https://github.com/TrinityCore/TrinityCore/commit/9614f9d8cf295d4135346d59e67fa47b51d2ed88 ??

**Comment by Golrag** [comment]
Seems I never wrote down the bugged coordinates.. so it's still possible that the z value given can still be slightly under the gameobject surface (which will result in selecting a ground lower than the gameobject surface). You can use my "temp fix" above and the problem won't happen again, but I was thinking at taking into account the "collision height" of the unit and maybe add that to the unit->getHeight or something similar

**Comment by Killyana** [comment]
No issue still happen.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/95456ab5d8bd623481d315ae55dfbb44b45ba9f5
