### ISSUE TITLE
[3.3.5] Mind Control buff duration not matching spell duration (not taking DR into account) and also applied while Immune pops up

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#19970]
**Description:** When a priest casts mind control, a buff is applied to him and to the enemy. The buff duration in PvP is not affected by diminishing so it says it's always 60 seconds even thought the duration of the channeling is not that time. Also, this buff is applied when the enemy is immune to Mind Control (for example due to maximum diminishing return reached).

**Current behaviour:** Buff duration of Mind Control is always 60 seconds and should only be that in PvE. Also, the buff is applied when the spell returns Immune due to maximum diminishing return.

**Expected behaviour:** Buff duration of Mind Control should match spell duration in PvP and it shouldn't be applied if Immune pops up.

**Steps to reproduce the problem:**

1. Cast Mind Control on an enemy PLAYER.
2. See how the buff duration on the priest is 60 seconds not matching the mind control duration.

-------

1. Cast Mind Control until last diminishing return.
2. Cast Mind Control again and see how it returns immune and the buff is still applied.
3. Also see that this buff can't be removed by right clicking it.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/e07a322a3e903079ecf61746808ad428023a26a1

**TDB version:**  TDB 3.3.5 63

**Comment by Keader** [comment]
dup? https://github.com/TrinityCore/TrinityCore/issues/15088

**Comment by Shauren** [comment]
dup

**Comment by Raydor** [comment]
It's similar but not the same. That's another issue where multiple different targets share the same DR for mind control. This issue is new, before (when that issue was created) the Mind Control buff lasted correctly the duration of the channel, at some point the mind control buff got bugged, also the immune return where the buff is applied.
