### ISSUE TITLE
Custom Script not work  3.3.5 tree

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#19972]
**Description:**

Custom Script not work  3.3.5 tree

**Current behaviour:**

Not have crash

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. creature (instance) and creature script 
2. Not work add custom script  -        virtual CreatureAI* GetAI(Creature* /*creature*/) const = 0;
 GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, nullptr); 
-- a/src/server/scripts/Custom/custom_script_loader.cpp
+++ b/src/server/scripts/Custom/custom_script_loader.cpp
@@ -16,10 +16,13 @@
  */
 
 // This is where scripts' loading functions should be declared:
-
+void AddSC_ npc_arena_spectator();
 
 // The name of this function should match:
 // void Add${NameOfDirectory}Scripts()
 void AddCustomScripts()
 {
+    AddSC_ npc_arena_spectator' ();
 } 
+INSERT INTO `creature_template` (`entry`, `modelid1`, `modelid2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `scale`, `rank`, `dmgschool`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
+(@Entry, 29348, 0, @Name, @Subname, @IconName, 0, 80, 80, 2, 35, 3, 1, 0, 0, 2000, 0, 1, 0, 7, 138936390, 0, 0, 0, '', 0, 3, 1, 0, 0, 1, 0, 0, 'npc_arena_spectator');
script npc custom 
+class arena_spectator_commands : public CommandScript
+{
+public:
+	arena_spectator_commands() : CommandScript("arena_spectator_commands") { }
work 
class npc_arena_spectator : public CreatureScript ( bugs? ) 
+{
+public:
+	npc_arena_spectator() : CreatureScript("npc_arena_spectator") { }
+
not work 
+void AddSC_arena_spectator_script()
+{
+	new arena_spectator_commands();  work
+	new npc_arena_spectator();  not work
+}

Not have error in sql and custom script 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 5879eb2198fdb976b9fff136757bf8187adb6cf0

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: TrinityCore rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu server 16.04.02 lts

**Comment by Aokromes** [comment]
this don't belongs here. it belongs to the custom script thread.

**Comment by gragonvlad** [comment]
And where i find custom script thread.

**Comment by Aokromes** [comment]
if you don't known from where you got it, we less.
