### ISSUE TITLE
Missing Completion Event for Quest "Hilary's Necklace"

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#19988]
**Description:**

When the quest "Hilary's Necklace" is turned in, a small event should happen where the quest giver (Hilary) and a nearby NPC (the cat Effsee) say some texts.

**Current behaviour:**

No event happens when turning in the quest.

**Expected behaviour:**

Event should happen when turning in the quest.

**Steps to reproduce the problem:**

1. .tele lakeshire
2. .quest add 3741
3. .quest complete 3741
4. Turn in quest

**Branch(es):**

Both

**TC rev. hash/commit:** 

TrinityCore rev. 63236f97af03 2017-03-03 14:54:11 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:** 335.63

**Operating system:** Windows 7

**Comment by malcrom** [comment]
Just pushed fix today.

**Comment by ZenoX92** [comment]
This is a fix I made for this. I also included conditions in order for the quest giver gossip menu text to change after quest is rewarded. I post it in order for wiser minds to check it. Hope it helps!
---
SET @ENTRY := 8962;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(@ENTRY,'0','0','0','20','0','100','0','3741','0','0','0','80','896200','0','0','0','0','0','1','0','0','0','0','0','0','0','Hilary - On Quest \'Hilary\'s Necklace\' Finished - Run Script');

SET @ENTRY := 896200;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(@ENTRY,'9','0','0','0','0','100','0','1000','1000','0','0','1','0','0','0','0','0','0','19','8963','10','0','0','0','0','0','Hilary - On Script - Say Line 0 (Effsee)'),
(@ENTRY,'9','1','0','0','0','100','0','2000','2000','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Hilary - On Script - Say Line 0');

DELETE FROM `creature_text` WHERE `CreatureID` IN (8962, 8963);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
('8962','0','0','I know how to speak kitty, and Effsee said thank you.','12','0','100','0','0','0','4628','0','Hilary'),
('8963','0','0','Meow!','12','0','100','0','0','0','4627','0','Effsee');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 14 AND `SourceGroup`= 1621;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
('14','1621','2273','0','0','8','0','3741','0','0','1','0','0','','Hilary - Show Gossip Menu Text 2273 if Quest 3741 is not rewarded'),
('14','1621','2274','0','0','8','0','3741','0','0','0','0','0','','Hilary - Show Gossip Menu Text 2274 if Quest 3741 is rewarded');

**Comment by Aokromes** [comment]
And that's why you must update core before reporting bugs.

**Comment by offl** [comment]
> Branch(es): Both

The fix was pushed only to master.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=pKcvDCGIGFE
