### ISSUE TITLE
[Black Temple] Shade of Akama always enter evade mode

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#19980]
**Description:** When you move in line of sight of Shade of Akama, Shade of Akama always enter evade mode.
This happens after commit e2a1ccd118d129b96e09ff1a15ed0adb1d4a3897  

**Expected behaviour:**  Shade of Akama shouldn't enter evade mode.
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 5d3c69bf441afb5dc0a6a20c0d7cd375178d2aa8
**TDB version:**  TDB 335.63
**Operating system:** Windows 10

**Comment by Keader** [comment]
I dont have time to check it with debug mode now.
But Shade of Akama is entering in combat with Ashtongue Channeler and it not should happen.
He enter in evade reason: EVADE_REASON_NO_HOSTILES.
Looks more core issue then script issue...
