### ISSUE TITLE
[3.3.5] Algalon inaccessible

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#19982]
3.3.5 0d27fee

Algalon's room cannot be opened as the "Celestial Planetarium Access" console (`go_celestial_planetarium_access` in `boss_algalon_the_observer.cpp`) is not responsive.

The issue is that `GossipHello` is currently not invoked for this GO, not sure why.
One simple fix would be moving the GO AI's `GossipHello` method to be called `OnReportUse` instead - not sure if that's the appropriate solution, I just wanted to get in so I could test the threat PR with phasing.

**Comment by qyh214** [comment]
confirm in 3.3.5 6621d8f
Is there a temporary solution or a formal solution?

**Comment by Keader** [comment]
> One simple fix would be moving the GO AI's GossipHello method to be called OnReportUse instead - not sure if that's the appropriate solution, I just wanted to get in so I could test the threat PR with phasing.

if works, i dont see any problem Treeston

**Comment by qyh214** [comment]
Thanks Treeston.
use `OnReportUse` instead of `GossipHello` then work and well~
