### ISSUE TITLE
[3.3.5] Core/Spell: rune client-server desynchronization

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#19983]
**Description:**
When using any death rune build + blood tap, rune cooldown/status gets desynchronized.
Client shows available runes for the next cast but reports "runes are not ready".

After debugging I determined, the rune types, cooldown and grace periods are correct serve side, so most likely its a problem with the related packets.

**Current behaviour:**
"runes are not ready" error is shown on correct scenarios

**Steps to reproduce the problem:**
(Frost death rune build)
1. IT
2. PS
3. Pestilence
4. Blood strike
5. Blood tap
6. Spam OB - Notice the error message

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
0d27fee6f45217c07cb7abbabbca0e9f5cff3961

**Comment by Treeston** [comment]
@ccrs could you elaborate on your research on this?

**Comment by ccrs** [comment]
So far I've looked into several different sniffs looking for the relevant client and sever packets, and the first conclusion is that ``SMSG_RESYNC_RUNES`` is never used on spell cast or actually anywhere else but on player log in. Therefore the first changes I've tested are these:

```diff
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -5452,8 +5452,6 @@ void Spell::EffectActivateRune(SpellEffIndex effIndex)
 
                 player->SetRuneCooldown(l, 0);
                 --count;
-                // is needed to push through to the client that the rune is active
-                player->ResyncRunes(MAX_RUNES);
             }
             else
                 break;

--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -22608,6 +22608,8 @@ void Player::SendInitialPacketsBeforeAddToMap()
     // SMSG_UPDATE_WORLD_STATE
     // SMSG_POWER_UPDATE
 
+    ResyncRunes(MAX_RUNES);

     SetMover(this);
 }

--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -24524,6 +24524,9 @@ void Player::ConvertRune(uint8 index, RuneType newType)
 
 void Player::ResyncRunes(uint8 count) const
 {
+    if (getClass() != CLASS_DEATH_KNIGHT)
+        return;
+
     WorldPacket data(SMSG_RESYNC_RUNES, 4 + count * 2);
     data << uint32(count);
     for (uint32 i = 0; i < count; ++i)

```

And the result is a somewhat improve, but still blood tap is not counted as death rune in the client in some scenarios.

**Comment by Treeston** [comment]
@ccrs since you logged before I could tell you - I've fixed [the gist](https://gist.github.com/Treeston/6b3e96a98fd25b4501526eab77135984) to always prefer rune slot 0.

**Comment by ccrs** [comment]
tyvm, got everything to work but new aura procs overriding existing blood tap aura effect, will check duration or passive attributes or something...

also waiting for #19997 to be checked

**Comment by Treeston** [comment]
Is it even possible for multiple BT effects to be active at the same time? I mean, it's 20sec duration, 60sec cd, I think?

**Comment by ccrs** [comment]
I meant the other auras that can proc death runes, like the ones on the talent trees

**Comment by Treeston** [comment]
Spell sequence for repro.
IT PS OB BS Pest BT UA

**Comment by vanasis** [comment]
im not sure but maybe need to send ResyncRunes  only for changed runes, ( the rune that blood tap affect it ) , not MAX_RUNES.
I try to Do it , but I see strange bugs. I'm not sure Can someone provide a sniff from retail about this?

**Comment by vanasis** [comment]
After @ccrs you are right after the sniffs I see no Resync Runes at all in the sniff. I don't know How they are handled but and Without Resync Runes the cooldown is not remove

I also checked HasRuneData in SMSG_SPELL_START and SMSG_SPELL_GO they are both False in sniff

**Comment by Foereaper** [comment]
Any progress on this issue?

**Comment by Eliminationzx** [comment]
This bug only with death runes other runes seems to work fine.
Also if you remove blood tap manually you will see that death rune not disappeared (rune disappeared only visual). After that try to use blood strike It will prove it.

**Comment by Infinito47** [comment]
@ccrs Any progress?

**Comment by ccrs** [comment]
d1dc0e2dc1fbd692eeda90ae2ab82ae07e2cae0e
