### ISSUE TITLE
Core: Creature Formation

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#19995]
![way](https://user-images.githubusercontent.com/10637389/27913049-1b0e8ad8-625f-11e7-9a5d-6a8e1c21f018.jpg)

Waypoint generator does not work properly
All linked NPC's do not move only the Master NPC have a working waypoint.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 07593f6c3488 2017-07-03 19:40:56 -0300 (335 branch)

**TDB version:** TDB_full_world_335.63_2017_04_18.sql + updates

**Operating system:** Win7 64Bit

**Comment by Killyana** [comment]
The assist works correctly but not the follow.

**Comment by tkrokli** [comment]
TrinityCore rev. 07593f6c3488 2017-07-03 19:40:56 -0300 (3.3.5 branch) (Win64, Release, Static)
TDB 335.63 plus updates up to and including `2017_07_03_00_world.sql`

Confirmed. When [Fozruk](https://wow.gamepedia.com/Fozruk) started off near Circle of East Binding, he seemed to float through the first part (mmaps, vmaps or waypoint issue?) before he started walking on the ground. I was almost at the other side or below Circle of East Binding, so I didn't even notice that the 3 kobold minions (Feeboz, Znort and Sleeby) were missing, so I just thought they were missing completely (not spawned). I realize now that they just were not moving from their spawn points.
- http://www.wowhead.com/npc=2611/fozruk // https://db.rising-gods.de/?npc=2611 // https://wow.gamepedia.com/Fozruk
- http://www.wowhead.com/npc=4063/feeboz // https://db.rising-gods.de/?npc=4063 // https://wow.gamepedia.com/Feeboz
- http://www.wowhead.com/npc=2765/znort  // https://db.rising-gods.de/?npc=2765 // https://wow.gamepedia.com/Znort
- http://www.wowhead.com/npc=2764/sleeby // https://db.rising-gods.de/?npc=2764 // https://wow.gamepedia.com/Sleeby

**Comment by Tauriella** [comment]
Your fix does not work

**Comment by Tauriella** [comment]
:+1:

**Comment by Rushor** [comment]
:+1:
