### ISSUE TITLE
Cannot fight Mistwhisper / Oracle mobs when doing Frenzyheart quests.

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#19993]
**Description:**
After having started doing the Frenzyheart questlines in Sholazar Basin, e.g. [The Mist Isn't Listening](http://www.wowhead.com/quest=12538/the-mist-isnt-listening), the Oracles in the zone appear to be hostile but you cannot attack them and they do not attack you despite the reputation loss.

**Expected behaviour:**
After having lost rep with the Oracles by doing Frenzyheart quests, the Oracles should become hostile to you.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e35092c6a164

**TDB version:**
335.62

**Operating system:**
Server & Client Windows 10

**Comment by Aokromes** [comment]
#9469
