### ISSUE TITLE
Core/AuraScript: PreventDefaultAction() voids after script hooks

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#19996]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L669

Aura script after hooks are prevented, while Spell script hooks arent if the effect/hit default action is prevented.

Is this intended?
I see many scripts having after hooks and ``PreventDefaultAction()`` which simply makes them all useless.

**Branch(es):**
both

**TC rev. hash/commit:** 
1f834d3cd195de5af8e5bf7f6410ffe3af65e497

**Comment by ariel-** [comment]
After hooks are executed after the effect is applied, if you prevent that with PreventDefaultAction no effect will be applied, ever.

**Comment by ccrs** [comment]
Incorrect, even if empty the aura is still there.
And you might want to override the default behavior for a determined spell, like my case to fix the dk issue.
And also, spell doesnt follow that logic, prevent should only do that, prevent the default effect implementation

**Comment by Shauren** [comment]
SpellScript has two functions for this
`PreventHitEffect` - prevents effect handler and script hooks
`PreventHitDefaultEffect` - prevents effect handler only

**Comment by ccrs** [comment]
> 

Are you sure?

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L4822

```c++
void Spell::HandleEffects(Unit* pUnitTarget, Item* pItemTarget, GameObject* pGOTarget, uint32 i, SpellEffectHandleMode mode)
{
    effectHandleMode = mode;
    unitTarget = pUnitTarget;
    itemTarget = pItemTarget;
    gameObjTarget = pGOTarget;
    destTarget = &m_destTargets[i]._position;

    uint8 eff = m_spellInfo->Effects[i].Effect;

    TC_LOG_DEBUG("spells", "Spell: %u Effect : %u", m_spellInfo->Id, eff);

    // we do not need DamageMultiplier here.
    damage = CalculateDamage(i, nullptr);

    bool preventDefault = CallScriptEffectHandlers((SpellEffIndex)i, mode);

    if (!preventDefault && eff < TOTAL_SPELL_EFFECTS)
    {
        (this->*SpellEffects[eff])((SpellEffIndex)i);
    }
}
```

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2493

I cant see the hooks being invalidated or void by anything there, spellhit can be true if default action is prevented.

**Comment by Treeston** [comment]
`Spell::CallScriptEffectHandlers` checks `Spell::_IsEffectPrevented` in every iteration, which will return true if `SpellScript::PreventHitEffect` has previously been called for the current effect.
