### ISSUE TITLE
Pet bugs

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#19994]
Pet bugs pvp
Not have crash

Pet bug pvp

**Steps to reproduce the problem:**

1. pvp system pet bugs . If player cast Turn Evil pet  dk not fear.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 07593f6c3488666423093c2c32514a0a378da942

 `worldserver` e4491736d75e+ `authserver`  

**TDB version:**  TDB 335.63
**Operating system:** ubuntu server 16.04.02 lts

**Comment by Keader** [comment]
what?

**Comment by Raydor** [comment]
Can confirm don't understand.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6572
