### ISSUE TITLE
[7.2.5]cant extract DBC

### ISSUE THREAD

**Issue by chilito** [TrinityCore/TrinityCore#19992]
**Description:**

Cant extract DBC
http://prntscr.com/fs3yot
(PLS dont look at folder name, its lastest legion wow)

Extracted only 75 files
https://prnt.sc/fs40ls  - its lastest extracted
**Current behaviour:**

Starting extraction and process freezed.

**Branch(es):**

master
**TC rev. hash/commit:** 

**TDB version:**  
https://github.com/TrinityCore/TrinityCore/commit/d1b77e7561a3c29455c2733f86b42662c7cacac1
**Operating system:** 
win64x

**Comment by jcmillions** [comment]
+1 on the issue

**Comment by Aokromes** [comment]
#19889
