### ISSUE TITLE
[Master] Loot Permission on Gold

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#20003]
**Description:**

When looting a corpse, you receive a message "You don't have permission to loot that corpse". This was only tested on Darkwraith (ID: 15657), Rotlimb Marauder (ID: 15658) during the quest Defending Fairbreeze Village (Quest ID: 9252).

NOTE: This message occurs only when looting gold from the enemy, any other items loot fine without the notification. 

UPDATE: This has been tested on several other enemies when looting gold and this message still appears regardless of the quest or NPC, most likely a core bug.

**Current behaviour:**

The gold can still be looted from an enemy however you will still receive the notification that 
"You don't have permission to loot that corpse."

**Expected behaviour:**
No message should appear when looting gold from an enemy.

**Steps to reproduce the problem:**

1. Create a character 
2. Kill an enemy which has a gold loot (bronze, silver, gold)
3. Loot

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. fc8f0fbc2d6f 2017-07-08 20:31:51 +0200 (master branch) (Win64, Release, Static)

**Operating system:** 

Windows 10

**Comment by Ferelith** [comment]
![wowscrnshot_070817_214531](https://user-images.githubusercontent.com/25698730/27989043-bda3119a-6428-11e7-888b-17cd6ba4088a.jpg)

**Comment by Shauren** [comment]
Unable to reproduce this at 52c7f12ed35f321dc97d8caea2b112287f5ac05b

.quest add 9252

Then killed all creatures for the objective looting all of them - no error ever appeared
