### ISSUE TITLE
Movement extrapolation for pets and attacking npcs

### ISSUE THREAD

**Issue by tripleslash** [TrinityCore/TrinityCore#20004]
**Description:**

When moving your character, pets and npcs should attempt to run toward an extrapolated player position instead of the last known player position (pets should run next to the player and not behind him for instance).

**Current behaviour:**

Movement is not extrapolated and pets are running behind the player.

**Expected behaviour:**

Movement should be extrapolated

**Steps to reproduce the problem:**

1. Summon a pet
2. Move
3. Watch as the pet does not run right next to you but behind you

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

TrinityCore rev. fc8f0fb 2017-07-08 20:31:51 +0200 (master branch) (Win64, Release, Static)

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21237
