### ISSUE TITLE
Bug with quest givers on new players

### ISSUE THREAD

**Issue by IlPicasso** [TrinityCore/TrinityCore#20007]
**Description:**

My problem is basically that new players are not getting the initial quests, they create the character, they appear in the map and one can't interact with the NPC

However, if I go as a GM and use .gm on and the .gm off it works

Also

If I import a Fresh TDB (without changing neither auth and characters), it works for the first created character, and when talking with sargent willem it will automatically accept the quest

After this, if I create a new character , same raze same class it will happen again what I explained at first, I can't interact with the Initial Quest giver 

Here is a picture, which can explain what I am saying above

http://f.cgm.rs/Wow_2017-07-08_14-23-58.png

(sorry for last issue, it was done with ElunaTrinityWOTLK, this is with this repository)

**Current behaviour:**

No "!" at the head of the characters, only after doing .gm on and .gm off

**Expected behaviour:**

At the moment of appearing the map the npc should have the ! at the head, and be able to interact with him 

**Steps to reproduce the problem:**

1. Create the Character 
2. Appear in the map
3. Try to interact with the quest giver

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c6d799444572 2017-07-08 18:55:29 +0200 (3.3.5 branch) (Unix, Release, Static) (worldserver-daemon) ready...

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 16.04 x64

**Comment by IlPicasso** [comment]
Seems to be with all classes, I just created a dwarf, with first character the "!" appeared but on the second character the "!" didnt appear http://f.cgm.rs/Wow_2017-07-08_17-00-37.png

I just erased world database, and imported a fresh one to see if it fixed it and it seems it didnt, corrected it

**Comment by Treeston** [comment]
Cannot reproduce on 74af880.

**Comment by IlPicasso** [comment]
@Treeston 

It doesn't seems be to something regarding "Initial Quests" but **quests dissapear** on log out and log in

They come back when **TrinityCore is Restarted**

Tested with clean branch, clean database and the same happens, there is a video ,  well two in fact,  http://f.cgm.rs/2017-07-09_09-43-47.mp4 and  http://f.cgm.rs/2017-07-09_09-44-16.mp4
