### ISSUE TITLE
Scripts/Spells: Heroic Leap does not trigger any player action

### ISSUE THREAD

**Issue by Stanwarr** [TrinityCore/TrinityCore#20000]
**Description:**

Heroic Leap does not work at all.

**Current behaviour:**

You click the spell then where you want to jump, the spell is put into cooldown but no jumping happening.

**Expected behaviour:**

Should jump to the selected point.

**Steps to reproduce the problem:**

1. Click the spell.
2. Select where you want to leap to.
3. ????

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 4cee412faf24 2017-07-05 08:10:01 +0200 (master branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version:**  TDB 720.00

**Operating system:** Win7

**Comment by Shauren** [comment]
What a waste of issue number 20000

**Comment by irgc** [comment]
@hi shauren? can u see my post?
https://github.com/TrinityCore/TrinityCore/issues/19999

**Comment by tkrokli** [comment]
Funny related comment on wowhead:
> [I don't suspect we'll see many dwarven warriors using this ability, they keep telling me to keep my feet on the ground.](http://www.wowhead.com/spell=6544/heroic-leap#comments:id=1145559)

😆 🤣 🕺 🎮

**Comment by tkrokli** [comment]
@Stanwarr : it is actually obvious that the spell does not work, `Server.log` (and worldserver console) give these warnings (among others):
```
Spell `178368` Effect `Index: EFFECT_1 Name: 42` of script `spell_warr_heroic_leap_jump` did not match dbc effect data - handler bound to hook `OnEffectHit` of SpellScript won't be executed
Spell `178368` did not pass Validate() function of script `spell_warr_heroic_leap_jump` - script will be not added to the spell
```
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Spells/spell_warrior.cpp#L386-L417

Check and see for yourself if you can find out what is wrong there...

**Comment by Stanwarr** [comment]
Tried my best and couldn't manage to get it to work..

**Comment by tkrokli** [comment]
Anyone else interested in making an effort to find out what is wrong with the script, or rewrite the script so it will match dbc effect data?

**Comment by Nupper** [comment]
It still dose not work.

**Comment by aquadeus** [comment]
this is fixed
