### ISSUE TITLE
Icecrown Quest Problems

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20008]
**Description:**
I made my way into the Icecrown zone and have found a lot of quest errors. I'm going to be using this thread to outline them -- that is to save time and effort by creating dozens of tickets. If this is not the preferred method, and you would prefer I create a ticket for each one, tell me.

**Current behaviour:**
1. Quest [The Last Line of Defense](http://www.wowhead.com/quest=13086/the-last-line-of-defense) - Using the Argent Cannon, the abilities damage the mobs but they heal instantly. The ability Reckoning Bomb is strong enough to instantly kill the weaker scourge but does nothing to the Frostbrood Destroyers.

**Expected behaviour:**
1. Quest [The Last Line of Defense](http://www.wowhead.com/quest=13086/the-last-line-of-defense) - The mobs should retain damage done to them by the cannon.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
1f834d3cd195

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

**Comment by Treeston** [comment]
The Last Line of Defense is known issue, #16163.

**Comment by Aokromes** [comment]
No, you don't  create 1 ticket for multiple bugged quests.

**Comment by jerbookins** [comment]
@Aokromes just curious if there was any sort of progress or intention behind the locking of #20009. Should I create a ticket for each quest in the line and offer my suggestion?

**Comment by tkrokli** [comment]
@jerbookins : Yes, please keep 1 issue (or 1 quest if the quest itself is the issue) per ticket.

BTW: Locking issue #20009 is likely because issues are not meant to be personal work logs.
