### ISSUE TITLE
Crash server if login characters

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#20018]
Description:
Crash Server
Current behaviour:

https://gist.github.com/gragonvlad/6d255938f3e55a33cad9bf82c3d4ce58
https://gist.github.com/gragonvlad/57ae0de664a3e31c70f1d1886f5a5fe4
Expected behaviour:
Steps to reproduce the problem:

1.Server crash if i'm login characters
2. Another crash log  2 if used 1002 spell npc to crash . 
 #Branch(es):
3.3.5

TC rev. hash/commit:
3f8c0cb
worldserver TrinityCore rev. e449173+ 2017-02-12 08:53:17 +0000 (HEAD branch) (Unix, Debug, Static)

TDB version: TDB 335.63

Operating system: Ubuntu server 16.04.02 #

**Comment by gragonvlad** [comment]
I create all rules or not ? And how i send crash log ? gdb worldserver ? 
run ? 
all line crasher i upload link up

**Comment by Aokromes** [comment]
you are still using a 5 months core, update your core. the row on your crashlog does not exist on that way on current core.
