### ISSUE TITLE
Crash worldserver

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#20017]
Crash Server

1. 
[Switching to Thread 0x7fffb2fff700 (LWP 25859)]
0x000000000277fed9 in UnitAI::SelectTarget (this=0x0,
targetType=SELECT_TARGET_RANDOM, position=0, dist=0, playerOnly=false,
withTank=true, aura=0)
at /root/TrinityCore/TrinityCore/src/server/game/AI/CoreAI/UnitAI.cpp:108
108 return SelectTarget(targetType, position, DefaultTargetSelector(me, dist, playerOnly, withTank, aura));

3.3.5

**TC rev. hash/commit:**  3f8c0cb446327061c4d5ba06e72044fb8308f694

 `worldserver` TrinityCore rev. e4491736d75e+ 2017-02-12 08:53:17 +0000 (HEAD branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu server 16.04.02

**Comment by Aokromes** [comment]
1st law: update your core before reporting bugs, even more when it's a crash.
Also, useless crashlog.

**Comment by Keader** [comment]
Post full debug log please (and https://github.com/TrinityCore/TrinityCore/issues/20017#issuecomment-314431914)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/new asks to follow the the guidelines for contributing before opening an issue.

The crashlog reported is partial and is not enough to work on the issue. Please post the missing information and the issue will be reopened

**Comment by gragonvlad** [comment]
gdb -x crashreport.gdb ./worldserver ??? gdb worldserver and  run ?

**Comment by gragonvlad** [comment]
i'm create rules ? or not ?
