### ISSUE TITLE
DB/Quest: Finish Me! (Quest 13232)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20019]
**Description:**
http://www.wowhead.com/quest=13232/finish-me

**Current behaviour:**
Quest does not have a properly assigned quest giver.

**Expected behaviour:**
The quest should appear from a [Dying Soldier](http://www.wowhead.com/npc=31304/dying-soldier#starts) after the completion of [The Broken Front](http://www.wowhead.com/quest=13231/the-broken-front); specifically [this dying soldier](https://gfycat.com/WetUglyAttwatersprairiechicken).

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
1f834d3cd195

**TDB version:**
335.63

**Operating system:**
Windows 10 Server & Client

**Comment by Killyana** [comment]
The quest is proposed by http://www.wowhead.com/npc=30344/high-captain-justin-bartlett
"High Captain Justin Bartlett aboard the Skybreaker wants you to kill 15 Horde Players in Icecrown."

**Comment by jerbookins** [comment]
No it isn't. That is the follow up daily.

**Comment by tkrokli** [comment]
Sorry, I presumed that I knew what would be wrong before I checked the DB.
The `creature_queststarter` info is not wrong, there must be something else.

Have you checked requirements & conditions, maybe your player does not meet them yet?

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `creature_queststarter` WHERE `quest`= 13232;
```
```
   id   quest
-----  ------
31304   13232
```

**Comment by jerbookins** [comment]
I have pretty thoroughly exhausted the capabilities of my own understanding of the database information that would lead me to believe that I have checked the requirements & conditions, yes.

I have a pretty detailed outline of corrections to the quest line in question located in issue #20009

**Comment by meji46** [comment]
The problem is Smart AI.

The npc set his npcflag to 1 (Only gossip) on reset. With a gossip option he set his npcflag to 3 (Gossip & Quest).

That gossip option only is available only with quest 13232 not taken and quest 13231 completed:

```sql
INSERT INTO conditions VALUES
(15,10040,3,0,0,28,0,13231,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13231 Complete'),
(15,10040,3,0,0,14,0,13232,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13232 Not Taken');
```

But if you reward quest 13231, you can't see the gossip option. Possible fix:
```sql
DELETE FROM conditions WHERE SourceTypeOrReferenceId=15 AND SourceGroup=10040 AND SourceEntry=3;
INSERT INTO conditions VALUES
(15,10040,3,0,0,28,0,13231,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13231 Complete'),
(15,10040,3,0,0,14,0,13232,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13232 Not Taken'),

(15,10040,3,0,1,88,0,13231,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13231 Rewarded'),
(15,10040,3,0,1,14,0,13232,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13232 Not Taken');
```

**Comment by Killyana** [comment]
@meji46 Nice catch, also quest requirements must be fixed:
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=10040 AND `SourceEntry`=3;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15,10040,3,0,0,28,0,13231,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13231 Complete'),
(15,10040,3,0,0,14,0,13232,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13232 Not Taken'),
(15,10040,3,0,1,8,0,13231,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13231 Rewarded'),
(15,10040,3,0,1,14,0,13232,0,0,0,0,0,'','Only show gossip option 3 if player has quest 13232 Not Taken');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceGroup`=13232;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19,13232,0,0,0,28,0,13231,0,0,0,0,0,'','Quest 13232 Finish Me! Requires Quest 13231 The Broken Front to be complete'),
(19,13232,0,0,1,8,0,13232,0,0,0,0,0,'','Quest 13232 Finish Me! Requires Quest 13231 The Broken Front to be rewarded');
