### ISSUE TITLE
NPC placement glitch on Skybreaker

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20011]
**Description:**
Errors with placement of stationary NPCs on flying airships in Icecrown

**Current behaviour:**
If you load into the game and the Skybreaker is within visible proximity, the NPCs are locked in place. You have to fly away until the NPCs disappear or log in away from the Skybreaker to make the NPCs stand on the ship correctly.

Here is a video to help demonstrate what I mean:
https://gfycat.com/HighlevelBaggyAmericanmarten

**Expected behaviour:**
The NPCs should stand with the Skybreaker as it moves through the air regardless of whether you load into the game while standing aboard it.

**Steps to reproduce the problem:**

1. Fly to the Skybreaker or horde airship in Icecrown
2. Logout
3. Log back in

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
1f834d3cd195

**TDB version:**
335.62

**Operating system:**
Windows 10 Server & Client

**Comment by Aokromes** [comment]
#16071
