### ISSUE TITLE
Overseer Faedris (entry 32250)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20020]
**Description:**
http://www.wowhead.com/quest=13319/chain-of-command

**Current behaviour:**
There are one too many NPCs named Overseer Faedris

![wowscrnshot_071117_204328](https://user-images.githubusercontent.com/16745918/28099474-0675e624-667a-11e7-81a5-dbb0bbde1a59.jpg)

**Expected behaviour:**
There should only be one named NPC named Overseer Faedris

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
1f834d3cd195

**TDB version:**
335.63

**Operating system:**
Windows 10 Server & Client

**Comment by Aokromes** [comment]
.gm  off

**Comment by jerbookins** [comment]
I didn't test with gm on, i turned gm on so i could get close to them without them attacking me for the screenshot

**Comment by Killyana** [comment]
``` sql
DELETE FROM `creature` WHERE `guid`=125031 AND `id`=32250;

**Comment by Aokromes** [comment]
maybe it needs pathing.

**Comment by Killyana** [comment]
No the npc doesn't have any path.

**Comment by tkrokli** [comment]
TrinityCore rev. 3f8c0cb44632 2017-07-11 12:52:53 +0200 (3.3.5 branch) (Win64, Release, Static)
Using World DB: TDB 335.63 + updates up to and including `2017_07_08_00_world.sql`

Confirmed. There are 2 identical spawns in the `creature` table:
```sql
SELECT * FROM `creature` WHERE `ID` IN (SELECT `entry` FROM `creature_template` WHERE `name` like '%Faedris%');
```
```
  guid      id     map  zoneId  areaId  spawnMask  phaseMask  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  dynamicflags  ScriptName  VerifiedBuild
------  ------  ------  ------  ------  ---------  ---------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  ------------  ----------  -------------
125031   32250     571       0       0          1          1    27851             1     7484.27     2063.88     499.728      4.40205            300          0                0      10080     8814             0        0           0             0                          0
125069   32250     571       0       0          1          1    27851             1     7469.18     2064.37     499.812     0.279253            300          0                0      10080     8814             0        0           0             0                          0
```

**Comment by Aokromes** [comment]
on this case the removing one is the one out of camp.
