### ISSUE TITLE
[master] World server crash when use command.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#20023]
**Description:**

When you use command "character deleted list" world server crash

**Current behaviour:**

https://gist.github.com/HannibalRoG/42ce5c6db40983b6d8b9bbc6513f9403

**Branch(es):**

master

**TC rev. hash/commit:** 

Revision: TrinityCore rev. df66b903e37f 2017-07-12 01:23:59 +0200 (6.x branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  7.2.0+updates

**Operating system:**

**Comment by Aokromes** [comment]
Very likely the same reason as https://github.com/TrinityCore/TrinityCore/issues/19127

**Comment by Aokromes** [comment]
Also test https://github.com/TrinityCore/TrinityCore/pull/18863
