### ISSUE TITLE
[3.3.5] The Great Moongraze Hunt - Missing tooltip on Moongraze Stag

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#20037]
**Description:**

There is no quest details showing up in the tooltip
![image](https://user-images.githubusercontent.com/1616448/28332490-5510f6d6-6bf5-11e7-8d0c-2033a1905b6c.png)

**Current behaviour:**

Quest information not showing up in tooltip

**Expected behaviour:**

Quest information should be showing up in the tooltip, as it does with this one:
![image](https://user-images.githubusercontent.com/1616448/28332559-8ecadd06-6bf5-11e7-9d3e-2d2b055c81a2.png)

**Steps to reproduce the problem:**

1. Pick up the quest The Great Moongraze Hunt
2. Hover over a Moongraze Stag

**Branch(es):**

Only tested on 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 348b02155bca 2017-07-16 18:26:05 +0200 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version:**  335.63

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
It needs retail check, some quests on retail don't show the additional info.

**Comment by Aokromes** [comment]
https://youtu.be/19ttiMBjhmQ?t=23s blizzlike

**Comment by Killyana** [comment]
Because https://woehead.way-of-elendil.fr/?item=23676 is not a quest item.

**Comment by GnaXi** [comment]
Woops. my bad!
