### ISSUE TITLE
[3.3.5] Griphon Masters don't have green exclamation sign anymore

### ISSUE THREAD

**Issue by Magnifikator** [TrinityCore/TrinityCore#20035]
TrinityCore rev. e38852c5d610 2017-07-17 11:26:43 +0200 (3.3.5 branch) (Win64, Release, Static)

How to test:
- make alliance character
- .go xyz -5422.07 -2893.86 343.006 0
- Look up to Gryphon Master Thorgrum Borrelson: No green exclamation sign
- .tele bootybay
- .recall      -> still no sign

- go here: .go xyz -5424.49 -2927.44 347.343 0
- .tele bootybay
- .recall      ->now the sign appears

The reason for this behaviour I found in SendTaxiStatus() in TaxiHandler.cpp. In this function you will find a call GetNPCIfCanInteractWith(). In GetNPCIfCanInteractWith() there is at the end a distance check if the NPC is near. 
```
if (!creature->IsWithinDistInMap(this, creature->GetCombatReach() + 4.0f))
```
But that's wrong because the signs you should see from far away.

There is a 2nd problem:
How to test: Switch in conf file the network logger to debug

When you move between zones the client is asking for available nodes (as  far as I understand). The core is login this: TC_LOG_DEBUG("network", "WORLD: Received CMSG_TAXINODE_STATUS_QUERY")
As long as you are moving between zones you will see this in your log and the core is calling SendTaxiStatus()

When a player logs into the game there is no CMSG_TAXINODE_STATUS_QUERY. So the core even don't try to send a SendTaxiStatus.

**Comment by Treeston** [comment]
Thanks for the bug-hunting - should be a simple fix.

**Comment by Magnifikator** [comment]
Yes, I think so, remove the distance check and may send SendTaxiStatus with every player login.

**Comment by Treeston** [comment]
Not quite _that_ simple - other callers might rely on the distance check.

**Comment by Magnifikator** [comment]
Yes, only for SendTaxiStatus().
