### ISSUE TITLE
Capture More Dispatches Daily (Quest 13333)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20047]
**Description:**
http://www.wowhead.com/quest=13333/capture-more-dispatches

**Expected behaviour:**
Alliance daily quest requires quest 13314 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
