### ISSUE TITLE
No Rest for the Wicked Daily (Quest 13350)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20044]
**Description:**
http://www.wowhead.com/quest=13350/no-rest-for-the-wicked

**Expected behaviour:**
Alliance daily quest requires quest 13346 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
