### ISSUE TITLE
That's Abominable Daily (Quest 13289)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20040]
**Description:**
http://www.wowhead.com/quest=13289/thats-abominable

**Current behaviour:**
Alliance daily quest requires quest 13288 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
