### ISSUE TITLE
Retest Now Daily (Quest 13322)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20049]
**Description:**
http://www.wowhead.com/quest=13322/retest-now

**Expected behaviour:**
Alliance daily quest requires quest 13321 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
