### ISSUE TITLE
Drag and Drop Daily (Quest 13323)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20042]
**Description:**
http://www.wowhead.com/quest=13323/drag-and-drop

**Expected behaviour:**
Alliance daily quest requires quest 13318 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
