### ISSUE TITLE
Blood of the Chosen Daily (Quest 13336)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20048]
**Description:**
http://www.wowhead.com/quest=13336/blood-of-the-chosen

**Expected behaviour:**
Alliance daily quest requires quest 13225 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992 stop opening ticket for unordered quest chain.
