### ISSUE TITLE
Not a Bug Daily (Quest 13344)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20043]
**Description:**
http://www.wowhead.com/quest=13344/not-a-bug

**Expected behaviour:**
Alliance daily quest requires quest 13342 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
