### ISSUE TITLE
Neutralizing the Plague Daily (Quest 13297)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20041]
**Description:**
http://www.wowhead.com/quest=13297/neutralizing-the-plague

**Expected behaviour:**
Alliance daily quest requires quest 13295 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
