### ISSUE TITLE
No Mercy! Daily (Quest 13233)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20046]
**Description:**
http://www.wowhead.com/quest=13233/no-mercy

**Expected behaviour:**
Alliance daily quest requires quest 13232 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992
