### ISSUE TITLE
Assault by Ground Daily (Quest 13284)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20050]
**Description:**
http://www.wowhead.com/quest=13284/assault-by-ground

**Expected behaviour:**
Alliance daily quest requires quest 13341 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
STOP #15992
