### ISSUE TITLE
The Warchief cometh (Quest 26965)

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#20056]
**Description:**

The Questevent with Sylvanas and Garrosh will not start.

**Current behaviour:**
The Quest started by Grand Executor Mortuus and the Player must wait for the Warchief, but he will not come.

**Expected behaviour:**

Warchief Garrosh comes with Sylvanas and give new Order.

**Steps to reproduce the problem:**

1. Finish Quest: Warchief's Command: Silverpine Forest! (ID: 26964)
2. Start the Quest by Grand Executor Mortuus
3. Wait for any Changes on the Map.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 33478689bb1b+ 2017-07-18 18:19:07 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  720.00

**Operating system:** Windows Server 2012 R2

**Comment by aquadeus** [comment]
this issue can be closed

**Comment by mdX7** [comment]
implemented in 68d6044a5cfe0575d18f63d3eb7ece94515cb205
