### ISSUE TITLE
[3.3.5] Green exclamation marks above Flight Masters missing

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#20055]
**Description:**

I just realized that none of the Flight Masters that I've been to for the first time are showing the green exclamation marks above their head anymore. They did do this previously though.
So some recent update might have affected it?
I do however get the "New flight path discovered!" message when talking to them.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 348b021 2017-07-16 18:26:05 +0200 (3.3.5 branch) (Unix, Release, Dynamic)

**TDB version:**  335.63

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/24ec3ad3409e66f523f533ec1d9d573000a5807f
