### ISSUE TITLE
Assault by Air Daily (Quest 13309)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20051]
**Description:**
http://www.wowhead.com/quest=13309/assault-by-air

**Expected behaviour:**
Alliance daily quest requires quest 13341 to be completed before hand

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by Aokromes** [comment]
#15992

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15992#issuecomment-233473509

**Comment by jerbookins** [comment]
Should I stop submitting these? Because there are dozens. I don't want to waste anyone's time but I was told in #20009 that I should submit a ticket for each quest. Since no one mentioned #15992 I assumed there wasn't an existing ticket and I was also told not to submit a singular ticket encompassing all of these quests.
