### ISSUE TITLE
The Eye of Acherus (Quest 12636)

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#20064]
**Description:**

No Action for the Eye of Acherus available

**Current behaviour:**

The Eye can't interact anything. Only aborting to use the Eye is available. So you can't complete the Quest.

**Expected behaviour:**

The Eye can normally spawn Ghouls and spy the given POI etc.

**Branch(es):** master

**TC rev. hash/commit:** 

TrinityCore rev. 33478689bb1b+ 2017-07-18 18:19:07 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:** 720.00

**Operating system:** Windows Server 2012 R2

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18362
