### ISSUE TITLE
Master Shang Xi 

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#20062]
**Description:**

Master Shang Xi won't give the Startquest (The Lesson of Iron Bough) for Pandaren

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 33478689bb1b+ 2017-07-18 18:19:07 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  720.00

**Operating system:** Windows Server 2012 R2

**Comment by tkrokli** [comment]
You know, you could help us out by testing Lopfest's pull request **[[WIP] The Wandering Isle](https://github.com/TrinityCore/TrinityCore/pull/17021) #17021** and tell us if the MoP starting zone works as it should.

**Comment by nubqt** [comment]
Confirmed.

master branch 7334419
TDB 720.00_2017_04_18

<img width="1378" alt="screen shot 2017-11-13 at 12 48 17 am" src="https://user-images.githubusercontent.com/33535711/32711362-8c0f81d4-c80c-11e7-96b8-9b6a58d03579.png">

**Comment by nubqt** [comment]
Entry is missing in `creature_queststarter`.

Must insert with:

```sql
INSERT INTO `creature_queststarter` ( `id`, `quest` ) VALUES ( '53566', '30027' );
```

But that alone didn't solve the issue.

**Comment by Aokromes** [comment]
#17021
