### ISSUE TITLE
Mark of the Wild (Spell 6756)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20067]
**Description:**
Mark of the Wild has issues

**Current behaviour:**
The tooltip of the buff does not match the tooltip of the spell in the spellbook.

~~https://gfycat.com/gifs/detail/GoldenImmediateJohndory~~

**Expected behaviour:**
The tooltip should match the effect cast.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Server & Client

**Comment by jerbookins** [comment]
I'm also not sure that "Improved Mark of the Wild" (17051) is working correctly.

**Comment by jerbookins** [comment]
It looks like it isn't correctly displaying the values applied by Improved Mark of the Wild.

**Comment by Treeston** [comment]
That gif is completely impossible to get anything from. Post standard screenshots, please.

**Comment by jerbookins** [comment]
![wowscrnshot_072217_180123](https://user-images.githubusercontent.com/16745918/28495378-d6112750-6f07-11e7-8f46-7c6932b5b205.jpg)
![wowscrnshot_072217_180126](https://user-images.githubusercontent.com/16745918/28495377-d5f481f4-6f07-11e7-8bc4-0ee488a8d2cd.jpg)

**Comment by Shauren** [comment]
In 3.3.5 buff tooltips cannot properly reflect real value. This was implemented in cataclysm client.

**Comment by jerbookins** [comment]
They seem to work at all of the other levels except this level.

This seems like a wasted opportunity to **_improve_** upon what was "blizz-like"

**Comment by Shauren** [comment]
As I said, the tooltip value is hardcoded in 3.3.5 client data, it can't be changed on buffs (modifiers are not taken into account)

**Comment by jerbookins** [comment]
> As I said

You didn't actually say that earlier, but I understand.

I heard there is a project to rebuild the game binaries, that would open up some amazing possibilities yeah?
