### ISSUE TITLE
No NPC in New Avalon

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#20063]
**Description:**

All NPC in New-Avalon is missed by the Start as Death Knight

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 33478689bb1b+ 2017-07-18 18:19:07 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:** 720.00

**Operating system:** Windows Server 2012 R2

**Comment by ArcaneFox** [comment]
I can't confirm this. My DK was created in 7.1.5, today I updated the server & client to 7.2.5 24746 and the phasing is still works for me.

(My DK is before the "In Service Of The Lich King" quest chain.)

**Comment by ArcaneFox** [comment]
0) Everything is burning (houses, ships, etc).
1) There is no phasing on the "The Death Knights of Acherus" books. (3.3.5 too)
http://www.wowhead.com/object=191642/the-death-knights-of-acherus
2) In the "Death Comes From On High", the skill bar is empty.
3) In "Death Comes From On High" there is no spawned NPC (for example Scarlet Crusaders).
4) "The Scarlet Apocalypse" is available from the start.
5) Side quest giver "Olrun the Battlecaller" isn't spawned or wrong cords. ("Death's Challenge")
6) "Into the Realm of Shadows" quest do nothing and you can complete instantly.
7) Scourge Gyphorns are dead (they are fighting in another phase).
8) "Gothik the Harvester" quest start at Gothik insted of Prince Valanar.
9) Prince Valanar is in wrong phase or the player's phase isn't changed ("The Will Of The Lich King" & "The Crypt of Remembrance")

From this point the quest chain is completely broken.

**Comment by Aokromes** [comment]
#18362
