### ISSUE TITLE
Relara Whitemoon (Entry 3892)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20065]
**Description:**
http://www.wowhead.com/npc=3892/relara-whitemoon

**Current behaviour:**
![wowscrnshot_072017_155444](https://user-images.githubusercontent.com/16745918/28440606-326fd0e6-6d64-11e7-92c4-640148075f31.jpg)

**Expected behaviour:**
She should be laying down in bed

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e0194e4a2c65

**TDB version:**
335.63

**Operating system:**
Windows 10 Client & Server

**Comment by tkrokli** [comment]
Looks like this could have an easy solution, she needs a sleep aura in either the `creature_addon` or `creature_template_addon` tables.

**Comment by Killyana** [comment]
It's a core issue, the aura doesn't provide the correct state to the npc.

**Comment by tkrokli** [comment]
Yes, I see you commented that in https://github.com/TrinityCore/TrinityCore/issues/15873#issuecomment-184195999 more than a year ago, 15 Feb 2016.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/dd4ab5395fc241f8f0af568179a7ddd678e9b150
