### ISSUE TITLE
TrinityCore (master) do not start 

### ISSUE THREAD

**Issue by IlPicasso** [TrinityCore/TrinityCore#20069]
**Description:**

TC master branch does not start I get an error 

**Current behaviour:**

```
Loading scenario poi data
>> Loaded 0 scenario POI definitions. DB table `scenario_poi` is empty.
World initialized in 0 minutes 16 seconds
StartNetwork failed to bind instance socket acceptor
Failed to initialize network

/root/TrinityCore/src/server/shared/Networking/SocketMgr.h:35 in ~SocketMgr ASSERTION FAILED:
  !_threads && !_acceptor && !_threadCount StopNetwork must be called prior to SocketMgr destruction
Segmentation fault (core dumped)

```

**Expected behaviour:**

To start Correctly 
**Steps to reproduce the problem:**

1. Start TrinityCore
**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 0feb56e2c75e 2017-07-21 00:36:03 +0200 (master branch) (Unix, Release, Static) (worldserver-daemon)

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** Ubuntu 16.04 LTS

**Comment by Aokromes** [comment]
#20032
