### ISSUE TITLE
Wailing Caverns

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#20061]
**Description:**

Escort Muyoh to Naralex is broken and dont start. So the Ritual to Wake Naralex will not start.

**Current behaviour:**

Muyoh don't go to Naralex and so stopped the Dungeon here

**Expected behaviour:**

Muyoh go to Naralex and the Player has to protect him and he will start the awakening of Naralex. And he summoned Mutanus in the Ritual.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 33478689bb1b+ 2017-07-18 18:19:07 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  720.00

**Operating system:** Windows Server 2012 R2

**Comment by HannibalRoG** [comment]
Know bug https://github.com/TrinityCore/TrinityCore/issues/16997
