### ISSUE TITLE
Missing implementation of PersonalLoot

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#20066]
**Description:**

Old WoW used Data1 of gameobject as lootId.
Nowadays a lot of gameobjects don't despawn and only get "invis" for looter.
Also the gameobject is only displayed empty for players who looted it.
Data30 contains the "lootId" for the PersonalLoot

According to same system also the creature_loot part belongs to this.
Might be that the whole loot system need to be adjusted in total.

http://wow.gamepedia.com/Loot#Personal_Loot

**Current behaviour:**
Gobjects with Data1 = 0 and Data30 > 0 do not have any loot.
PersonalLoot is missing totaly.

**Expected behaviour:**
Nowadays lot of gameobjects don't despawn and only get "invis" for looter.
Also the gameobject is only displayed empty for players who looted it.
Data30 contains the "lootId" Some gobjects use Data1 AND Data30.
The system needs to leave old Gobjects working and also the new chestPersonalLoot.

Also creatures have personalLoot

**Steps to reproduce the problem:**

1. System missing totaly

**Branch(es):**

master

**TC rev. hash/commit:** 

0feb56e2c75e5cf3a8388ff6d9b9441d2b5d0c59

**TDB version:** 7.2.0

**Operating system:** Win

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47478927)](https://www.bountysource.com/issues/47478927-missing-implementation-of-personalloot?utm_source=47478927&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by funjoker** [comment]
Please ad as much information you got here.

**Comment by myran2** [comment]
So some gameobjects use Data1 and Data30 for their loot ID? Is the loot ID the same for both fields or different when both fields are used? Do you have an example gameobject that uses both?

**Comment by malcrom** [comment]
As for the dwarven start area the kegs shouldn't despawn or become invisible after you loot them.

**Comment by funjoker** [comment]
Increased to 200$

**Comment by Seyden** [comment]
You have to much muney!

**Comment by Shauren** [comment]
As it stands its blocked by lack of per-boss saves to complete (outside instances would be doable)

**Comment by FireEmerald** [comment]
Is there an extra issue open for the per boss saves?

**Comment by Shauren** [comment]
No, but its being worked on

**Comment by malcrom** [comment]
Wow this is almost two years old. I remember not being able to fix the keg quest in the dwarf start zone because of this issue.

**Comment by roc13x** [comment]
Increased to $400

**Comment by illfated** [comment]
indeed:
https://www.bountysource.com/issues/47478927-missing-implementation-of-personalloot-bounty-200
TOTAL BOUNTY VALUE
$400.00 USD

**Comment by funjoker** [comment]
Due to TOS changes at bountysource, i will withdraw my 200$ bounty

**Comment by funjoker** [comment]
Bounty has been removed

**Comment by funjoker** [comment]
Ref: 133334a902b705dae6f7e92bb1009b84cf1c51d2

**Comment by Nyr97** [comment]
Also ref: https://github.com/TrinityCore/TrinityCore/commit/641390dca2329041a6ef513c2c9f7b28d42d2762
