### ISSUE TITLE
[3.3.5] Core/Spell: Arctic winds - miss chance doesn't increase

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#20073]
**Description:**

Increases all Frost damage you cause by 5% and reduces the chance melee and ranged attacks will hit you by 5%.

**Current behaviour:**

Don't reduce the chance melee and ranged attacks.

**Expected behaviour:**

Should reduce the chance melee and ranged attacks by 5%.

**Steps to reproduce the problem:**

1. Create 80lvl mage and 80lvl warrior.
2. Learn talent [Arctic Winds - Level 5](http://wow.gamepedia.com/Arctic_Winds)
3. Add 5% hit rating for melee attacks on warrior.
4. Try to hit mage with melee spells on warrior.
5. You will see that there is no misses.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/f2f45765e408cbba49e15ea642a1ed052c751bcf

**TDB version:**  TDB 335.63

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Non-russian pages about the spell Arctic Winds:
- https://wow.gamepedia.com/Arctic_Winds
- https://woehead.way-of-elendil.fr/?spell=31678
- https://db.rising-gods.de/?spell=31678

If I understand your issue correctly, you are saying that the spell Arctic Winds doesn't provide any hit reduction as a countermeasure to the +5 hit stat increase on the warrior.

**Comment by Eliminationzx** [comment]
You're right @tkrokli , thank you.

**Comment by ariel-** [comment]
The aura works properly, if you reduce attacker's hit rating but then add hit rating to compensate, you can't miss.

Anyways I discovered something while making sense of the issue.
