### ISSUE TITLE
[master] SCRIPT_COMMAND_PLAY_ANIMKIT not executing and stopping waypoint_data path

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20076]
**Description:**
Waypoint_scripts containing SCRIPT_COMMAND_PLAY_ANIMKIT (35) are not doing anything, after that NPC moves to the next waypoint and stops there, even if he should continue his waypoint_data path. (other SCRIPT_COMMANDs are not affected)

**Current behaviour:**
When NPC reaches waypoint_data with SCRIPT_COMMAND_PLAY_ANIMKIT, he doesn't perform any animkit, then he moves to next waypoint and stops there.

**Expected behaviour:**
Execute SCRIPT_COMMAND_PLAY_ANIMKIT and continue in waypoint_data to the end.

**Steps to reproduce the problem:**

1. Create any NPC with SCRIPT_COMMAND_PLAY_ANIMKIT and waypoints

**Branch(es):** master

**TC rev. hash/commit:**  1ee9d243ea1a

**TDB version:**  TDB 720.00

**Operating system:** Win

**Comment by Shauren** [comment]
As with all emotes and animations, you have to time it yourself.

**Comment by Lopfest** [comment]
I'm not sure what do you mean. You mean emote gets canceled when moving? This is not the case.
In addition, canceling emote/animKit is (heopefully) not related to interrupting whole waypoint path.
Also, it was working on WoD.

**Comment by Lopfest** [comment]
issue was renumbered enum
https://github.com/TrinityCore/TrinityCore/commit/fac5ce67db12f1eec2f35deaee1a1a364614ddf5#diff-394234c1f24e82f608ef945f8bf032df
