### ISSUE TITLE
[3.3.5] Ulduar: Celestial planetarium access not working

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#20077]
**Description:** Celestial planetarium access (entry: 194628 and 194752) not working. 
It works fine before commit 2335b9de1a46a409c714a1dc89cbd0565545e70e  

How to fix it:
Change `bool GossipHello(Player* player) override` to `bool OnReportUse(Player* player) override` on line 993 from boss_algalon_the_observer.cpp can fix this problem.

**Expected behaviour:**  Celestial planetarium access should working.
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 1de89579c75f7b5d5028b162334fa496832a093c
**TDB version:**  TDB 335.63
**Operating system:** Windows 10

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19982
