### ISSUE TITLE
[3.3.5]Raid lockout period in calendar is wrong

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#20087]
**Description:**

I noticed this a while ago, but the lockout reset date in the calendar is shown as 2 weeks instead of 1 week as it is supposed to be. However, the lockout itself resets correctly after 1 week.

**Current behaviour:**

Currently the lockout is displayed as 2 weeks in the calendar.

**Expected behaviour:**

It should show the correct 1 week to reflect the actual reset period.

**Steps to reproduce the problem:**

1. Enter a raid and kill a boss to have the lock set.
2. Check calendar vs actual reset time.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 21b03e7

**TDB version:**  335.63

**Operating system:** Windows

Attached is a screenshot showing the reset date in the calendar. The raid was performed on the 21st and 22nd of July. http://prntscr.com/g1427t

**Comment by kaytotes** [comment]
This is most likely linked with the following https://github.com/TrinityCore/TrinityCore/issues/16845. When tinkering with that issue I ended up essentially breaking the reset dates to display as every day (blargh).

**Comment by Jinnaix** [comment]
Can be closed, the described issue is not existent as of 85a1310cd783d98a676d17085cea2dd9ad270683


![WoWScrnShot_082820_084300](https://user-images.githubusercontent.com/37972361/91530008-9bbcae00-e90a-11ea-8789-b24105fe095d.jpg)
![WoWScrnShot_082820_084306](https://user-images.githubusercontent.com/37972361/91530011-9ceddb00-e90a-11ea-8c13-9b2473f2005e.jpg)

I dont know if or how the Calendar should handle raid ID extending. Currently, it still shows the same reset day if you extend the id for another week - i have never touched that function in my wow time/in trinitycore, so i dont even know if it works at all.
