### ISSUE TITLE
[crash] High Overlord Saurfang dont spawn in Icecrown Citadel

### ISSUE THREAD

**Issue by justicebz** [TrinityCore/TrinityCore#20093]
High Overlord Saurfang dont spawn for horde, Muradin Bronzebeard in that place.

Crash: https://gist.github.com/feniixtm/268be47760d652c84b0ece9c6270f70b

**Steps to reproduce the problem:**

1. Talk to Muradin Bronzebeard or Overlord Saurfang

branch 3.3.5

TrinityCore rev. 7cbb6c101e97 2017-07-25

Using World DB: TDB 335.63

**Operating system:** Windows Server 2012 R2

**Comment by irgc** [comment]
Confirm

**Comment by ofir2006** [comment]
I'm on a fresh 335.63 and it works fine

**Comment by irgc** [comment]
what is crash!

**Comment by tkrokli** [comment]
Confirming anything without posting your own information is a useless comment.
Please post your own Debug crash log and TC core revision hash.

**Comment by jackpoz** [comment]
if you can reproduce the issue easily, please build TC in Debug mode and post a new crash log

**Comment by Aokromes** [comment]
crash fixed already, missing event #3963
