### ISSUE TITLE
[master] Error creating character

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20090]
**Description:**
19dcae0dd4346304d509ac866305b737a8683048 since this commit, it is not possible to create below characters because of "Error creating character" error:
- human female
- dwarf female
- gnome female
- draenei male
- orc female
- tauren male
- tauren female
- troll female
- pandaren female

**Current behaviour:**
Creating character combinations listed above is not possible

**Expected behaviour:**
Character creation should be successful

**Steps to reproduce the problem:**
1. create one of the character listed in description and you get an error

**Branch(es):** master

**TC rev. hash/commit:**  19dcae0dd434

**TDB version:**  720.00

**Operating system:** Win 7 x64

**Comment by Vincent-Michael** [comment]
try: https://gist.github.com/Vincent-Michael/0ce750228e0a5cca9185f73939a29a82

**Comment by Vincent-Michael** [comment]
try: https://gist.github.com/Vincent-Michael/8a11ddf2ca70d77c54e8b2a6aaa394d4

**Comment by Treeston** [comment]
Pretty sure those races are ones that don't have facial hair?

**Comment by tkrokli** [comment]
Good point, looks like it is related to either female gender or the Tauren race, where there is no Facial Hair option in the character selection screen.

**Comment by Golrag** [comment]
Taurens can have facial hair. Also, my tauren just changed appearance when I went to character selection screen :|. Other color, horns, face...

**Comment by Zyres** [comment]
Valid issue: cb4dd92629149d94e5ded6c2e8b073173bbe042a

**Comment by vinin80** [comment]
2d0e653 This doesn't work. Tested on Windows 10 x64

**Comment by Lopfest** [comment]
confirm. issue still persists.

**Comment by Shauren** [comment]
Its k, there are more changes coming (at least females work now)

**Comment by GreyPaladin** [comment]
I just pulled, complied and ran your commit 2d0e653 on linux server with a clean database Shauren..  And I got the same error: 
Player::Create: Possible hacking-attempt: Account 2 tried creating a character named 'Test' with invalid appearance attributes - refusing to do so

And I could not create any females in this closed issue,   If you want Shauren, I can re-submit the issue..

**Comment by Shauren** [comment]
No. Retest it on current after a93a5ad379635bbf4a50d48eee810e7673b07168
