### ISSUE TITLE
[master] multi-profession trainer npcflag

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20091]
**Description:**
On offic, multi-profession trainers (at least on Wandering Isle) don't have npcflag UNIT_NPC_FLAG_TRAINER (nor UNIT_NPC_FLAG_TRAINER_PROFESSION) and are able to train spells.
On TC, NPC must have UNIT_NPC_FLAG_TRAINER, otherwise it won't display window with training spells. Clicking the respective gossip_menu_option_trainer does nothing.

**Current behaviour:**
You must add UNIT_NPC_FLAG_TRAINER to the NPC so it can display the training spells window.

**Expected behaviour:**
NPCs should be able to train spells even without npcflag, when there is an gossip_menu_option_trainer for specific NPC present?

**Steps to reproduce the problem:**
1. create multi-profession trainer without UNIT_NPC_FLAG_TRAINER and it wont wor'k.

**Branch(es):** master

**TC rev. hash/commit:** 19dcae0

**TDB version:**  720.00

**Operating system:** Win 7 x64

**Comment by joschiwald** [comment]
is there another npc flag that indicate to be a trainer? can you provide some sniff example?

**Comment by Lopfest** [comment]
nothing just UNIT_NPC_FLAG_GOSSIP in this NPC
https://pastebin.com/NSJ0d8Z8

**Comment by malcrom** [comment]
Are the multi trainers shown on mini map? I think these flags may only be for that. There is no need for a trainer flag with trainerid sent from gossip.

**Comment by Lopfest** [comment]
No. I checked the profession trainer search option in minimap, and the trainer was not shown.

**Comment by malcrom** [comment]
Yeah that shouldn't be needed. There is no need for the core to check if trainer or trainertype with I'd sent from gossip.

**Comment by Shauren** [comment]
Fixed in `fb1fdf27b951fafbcb68c97675f75ef98aa5e3b7`
