### ISSUE TITLE
[Master] Crash on LoadTainers

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#20096]
**Description:**

Since https://github.com/TrinityCore/TrinityCore/commit/0cd5179726f91cc163910dd0806d622fe86d9a8c worldserver crash when you load the trainer with data in table `trainer` and `trainer_spells`

**Crashlog:** https://gist.github.com/DoctorKraft/191cd13844d54c25b9adf4c98d7046ca

Also i have a question, i have found a trainer with no gossip (MenuId), how we can set trainer on creature now? Or commit are not finished?

Thanks

**Steps to reproduce the problem:**

Start worldserver with data in table trainer and trainer_spells

**Branch(es):**

- [X] master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/43c3a780798268c2fc2d9163a9d8bd24624b8c35

**Operating system:** Debian

**Comment by Vincent-Michael** [comment]
try: https://gist.github.com/Vincent-Michael/1ff44e4d67f49f181fcf9c303fd2004c

**Comment by Vincent-Michael** [comment]
fixed in fac8ccf7e0981d3ea376aeff30788d2e53fca92f
