### ISSUE TITLE
DB/Quest: There Exists No Honor Among Birds

### ISSUE THREAD

**Issue by TULOA** [TrinityCore/TrinityCore#20098]
**Description:**

Item Trained Rock Falcon (34124) not usable.

**Current behaviour:**

Item keeps stating that it requires Vrykul Hawk Roost.
There is however no such area.

**Expected behaviour:**

Unfortunately I don't know personally. I know the falcon should collect the egg and was working in an earlier build but is now an item that's not usable. I don't see a area or map specified in the item_template that should cause issues.

**Steps to reproduce the problem:**

Accept the quest above and try to use the item at the roosts. It will state Requires Vrykul Hawk Roost.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a0bdf7e83687+ 2017-07-25 21:54:11 +0200 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  TDB 335.63

**Operating system:** Windows 10 Pro x64

Was supposedly fixed during issue: https://github.com/TrinityCore/TrinityCore/issues/16921

**Comment by TULOA** [comment]
Also I have searched at the spot where it is suppose to be and it still states the same thing.

**Comment by Killyana** [comment]
just .go xyz 388.7829, -6031.9248, 327.8406

**Comment by TULOA** [comment]
Ok so that spot works the falcon but using scavenge near the eggs is not triggering the count to increase.
