### ISSUE TITLE
[Quest] Rescue from Town Square - Again...

### ISSUE THREAD

**Issue by TULOA** [TrinityCore/TrinityCore#20102]
**Description:**

Sorry to seem like a bother... however theres an issue with this quest again.
They run away and such but no credit given.

**Current behaviour:**

NPCs run away and do all the events in the smart script but give credit.
Video: http://tpras.com/12253.html

**Expected behaviour:**

Give credit while running away.

**Steps to reproduce the problem:**

Accept Quest 12253 and head to wintergarde keep and try to do the quest.
The NPCs will run away but you wont get credit.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c70b328eda83+ 2017-08-01 18:14:55 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:** Windows 10 Pro x64

**Comment by TULOA** [comment]
I have already tried the previously mentioned fix in the closed issues section and it didn't help as it was already there.

**Comment by ofir2006** [comment]
Can confirm, using latest TDB 335.63, tried the fix and it wont work, tried fixing it myself for the past few hours but with no success.

**Comment by tkrokli** [comment]
Could be caused by the same as described in issue **[3.3.5] The Tome of Valor #20053**
Check my comment in https://github.com/TrinityCore/TrinityCore/issues/20053#issuecomment-321997575 in particular for similarities.

**Comment by jerbookins** [comment]
8888e6d96d02

still not functioning

**Comment by tkrokli** [comment]
Is this only about the quest credit itself, that the NPCs behave as intended, but no quest credit is given?
Or should we check the NPC scripts for wrong parameters?

**Comment by Killyana** [comment]
No it's a core side issue related probably to the movement generator.

**Comment by sirikfoll** [comment]
Broken here: https://github.com/TrinityCore/TrinityCore/commit/e2a1ccd118d129b96e09ff1a15ed0adb1d4a3897#diff-067cd3e9b67215292b6f3b62d0b30011L148

Now SAI tries to store its targets before actually having a target
Old and new callstacks to compare: https://gist.github.com/sirikfoll/07889e175f2200fa3f71103b9c1c99f0
