### ISSUE TITLE
[3.3.5] Scripts/Command: Strange behavior in command .npc move

### ISSUE THREAD

**Issue by Eliminationzx** [TrinityCore/TrinityCore#20104]
**Description:**

After this commit: https://github.com/TrinityCore/TrinityCore/commit/232db9777a3425891f55b5b94a02fa619adafcb5 came a strange bug with gm command [`.npc move` ](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_npc.cpp#L870)-
this command create a copy of npc which you are trying to move and this copy is dead.
When you try to remove that copy this will cause crash.

![wowscrnshot_080317_021106](https://user-images.githubusercontent.com/2004626/28890369-0d273c06-77f1-11e7-944a-f57b82578f4e.jpg)

**Current behaviour:**

Read description.

**Expected behaviour:**

Should work as intended.

**Branch(es):** `3.3.5`

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/232db9777a3425891f55b5b94a02fa619adafcb5

**TDB version:**   TDB 335.63

**Operating system:** Windows 10

**Comment by Treeston** [comment]
If that's the worst crash that dynspawn causes then I'll take it.

**Comment by Eliminationzx** [comment]
Now its .npc del command cause of crash :hushed:

**Comment by Treeston** [comment]
It shouldn't (but please open a new issue if it does).

**Comment by Eliminationzx** [comment]
https://github.com/TrinityCore/TrinityCore/commit/759357049cdbe9a2f97bbab6e61299cd65ba1bec#diff-f3f953a63e2a008d22de69cb68f735c4R1647 should be removed I guess because its cause of crash and without this part of code both command .npc del and .npc move works fine.

**Comment by Killyana** [comment]
Can you provide steps to reproduce the crash, I not able to do it on rev. 906498e9f4d8
