### ISSUE TITLE
Quest: Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by TULOA** [TrinityCore/TrinityCore#20101]
**Description:**

Cant complete quest as it doesn't complete the dialog.

**Current behaviour:**

When pressing the action it does the first speech from the bot but nothing from the NPC.
World Server Log returns:
CreatureTextMgr: Could not find TextGroup 1 for Creature Lebronski (Entry 24718, GUID 210067) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find TextGroup 2 for Creature Lebronski (Entry 24718, GUID 210067) in 'creature_text' table. Ignoring.

**Expected behaviour:**

Unsure and quest from wowhead doesn't say. Nothing happens sitting waiting either.
Wowhead Link: http://www.wowhead.com/quest=11491

**Steps to reproduce the problem:**

Accept Quest and attempt it.
Nothing happens while waiting or after using action from vehicle.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a0bdf7e+ 2017-07-25 21:54:11 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

TDB 335.63

**Operating system:** Windows 10 Pro x64

**Comment by TULOA** [comment]
Updated to:
TrinityCore rev. c70b328eda83+ 2017-08-01 18:14:55 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

Now it shows the text but still does not complete.

**Comment by dr-j** [comment]
~~~sql
UPDATE `smart_scripts` SET `event_flags`=`event_flags`|0x200 WHERE `entryorguid`IN(2485200,2485201) AND `source_type`=9;
UPDATE `smart_scripts` SET `event_flags`=`event_flags`|0x200 WHERE `entryorguid`IN(24806,24825,24852) AND `source_type`=0;
UPDATE `smart_scripts` SET `action_type`='85', `action_param1`='44569', `action_param2`='2', `target_type`='23', `target_param1`='0' WHERE  `entryorguid`=2471801 AND `source_type`=9 AND `id`=3 AND `link`=0;
~~~
that will fix the quest so event works does not fix text issue

**Comment by TULOA** [comment]
Applied the updates to rev 4505a4a30d8fee0c262a3a17253d50f8c86c9a4f and still for whatever reason its not completing. Still shows text but will not complete.

**Comment by TecDian** [comment]
The missing text was added in 2015_03_02_03.sql and accidentically deleted in 2015_03_02_04.sql. Restore:

```SQL
DELETE FROM `creature_text` WHERE `CreatureID`=24718 AND `GroupID` IN (1, 2);  
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`, `BroadcastTextId`,`TextRange`,`comment`) VALUES
(24718,1,0,"What do you think you're doing, man? Lebronski does NOT appreciate you dragging your loose metal parts all over his rug.",12,7,100,0,0,0, 23890,0,'Lebronski'),
(24718,2,0,"Far out, man. This bucket of bolts might make it after all...",12,7,100,0,0,0, 23891,0,'Lebronski');
```

**Comment by tkrokli** [comment]
So, a merge of those 2 SQL blocks should be the final solution here?
```sql
-- readd missing text from 2015_03_02_03_world.sql
DELETE FROM `creature_text` WHERE `CreatureID`=24718 AND `GroupID` IN (1, 2);  
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`, `BroadcastTextId`,`TextRange`,`comment`) VALUES
(24718,1,0,"What do you think you're doing, man? Lebronski does NOT appreciate you dragging your loose metal parts all over his rug.",12,7,100,0,0,0, 23890,0,'Lebronski'),
(24718,2,0,"Far out, man. This bucket of bolts might make it after all...",12,7,100,0,0,0, 23891,0,'Lebronski');

-- SAI action improvements for quest 11491
UPDATE `smart_scripts` SET `event_flags`=`event_flags`|0x200 WHERE `entryorguid`IN (2485200,2485201) AND `source_type`=9;
UPDATE `smart_scripts` SET `event_flags`=`event_flags`|0x200 WHERE `entryorguid`IN (24806,24825,24852) AND `source_type`=0;
UPDATE `smart_scripts` SET `action_type`='85', `action_param1`='44569', `action_param2`='2', `target_type`='23', `target_param1`='0' WHERE  `entryorguid`=2471801 AND `source_type`=9 AND `id`=3 AND `link`=0;
```

**Comment by tkrokli** [comment]
Based on your detective work, I can reference the origins:
- `creature_text` lines originally added in https://github.com/TrinityCore/TrinityCore/commit/a85bc8aa39b0fd0dea28058859f6872b85658d44
- 2 out of 3 lines removed in https://github.com/TrinityCore/TrinityCore/commit/182d4e913c2582ee810a5559e345e5e2c8ab9a50#diff-5418420038f714f453c3264bdcae83d4R47

**Comment by Killyana** [comment]
Just this:
``` sql
UPDATE `smart_scripts` SET `event_flags`=`event_flags`|512 WHERE `entryorguid` IN  (2482300) AND `source_type`=9;
-- readd missing text from 2015_03_02_03_world.sql
DELETE FROM `creature_text` WHERE `CreatureID`=24718 AND `GroupID` IN (1, 2);  
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`, `BroadcastTextId`,`TextRange`,`comment`) VALUES
(24718,1,0,"What do you think you're doing, man? Lebronski does NOT appreciate you dragging your loose metal parts all over his rug.",12,7,100,0,0,0, 23890,0,'Lebronski'),
(24718,2,0,"Far out, man. This bucket of bolts might make it after all...",12,7,100,0,0,0, 23891,0,'Lebronski');
