### ISSUE TITLE
[3.3.5] JustRespawned() of ScriptedAI not working after implemented dynamic spawning

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#20111]
**Description:** I found JustRespawned() of ScriptedAI(BossAI) not working after implemented dynamic spawning.
But if I change the groupFlags of Default Group to 3 from spawn_group in DB to make sure m_respawnCompatibilityMode always be true for every creatures and gameobjects, then JustRespawned() works fine.
This bug causes some boss not working, for example, Thaddius always disappeared in Naxxramas.

**Expected behaviour:**  JustRespawned() of ScriptedAI(BossAI) should working.
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 906498e9f4d80ff10094cd3f365b310d9dec4521
**TDB version:**  TDB 335.63
**Operating system:** Windows 10

**Comment by shenhuyong** [comment]
@Treeston

**Comment by Treeston** [comment]
Hrm, this one's tricky. The problem is simple - in `dynamic_spawning`, there is no way to distinguish between a creature respawning and being reloaded on grid load.

I'll have to think of something.

**Comment by Treeston** [comment]
^That's what I ended up thinking of.
