### ISSUE TITLE
Core/Aura: SingleTargetAura handling

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#20122]
**Description:**

The handling of SingleTargetAuras need to get a slight rework.

`void Unit::RemoveNotOwnSingleTargetAuras(uint32 newPhase, bool phaseid)`

The idea of the use of this method needs to be updated.
Also it needs a rework, maybe with more logical args.

**Current behaviour:**

On login, areachange, phaseupdate some singletarget auras are removed even if they should stay.

There are some auras who are just disappearing on areachange which shouldn't.
I guess some talents are also affected by those bug.

Example: Cavalier (paladin) stacks are removed on area change.
Example: Sacrifice (paladin) is removed on area change

I guess the areachange is more a "phase" thing. Due to phase update `RemoveNotOwnSingleTargetAuras ` is triggert.

**Expected behaviour:**

Don't know if there are auras who are removed on area change or phase change.
A player can buff you and logout without the aura to disappear.
You can write a vehicle trough several areas without getting dismounted or the mount disappear.

**Steps to reproduce the problem:**
1. Get an vehicle 
2. Ride it out of your area 
3. See the magic

**Branch(es):**

master

**TC rev. hash/commit:** 

10e81a9933919bfe3a0df6f80bb06155ea10c213

**TDB version:**  7.2.0

**Operating system:** Win

**Comment by funjoker** [comment]
#4903

**Comment by matukaa** [comment]
I can confirm, dozens of spells are incorrectly removed.

Try this one: polymorph your target, then proceed to use blink. Blink calls the HandleWorldPortAck function, which updates phase, and even though the phase does not change, the enemy instantly loses Polymorph. It's gamebreaking when it comes to arenas. You polymorph someone, blink and they are free to go.
Same happens with Beacon of Light for paladin. While running dungeons, you need to reapply Beacon of Light every two minutes, if you change subzone/area.

**Comment by offl** [comment]
Is there any difference between this issue and #16021?

**Comment by funjoker** [comment]
Yes @offl

**Comment by funjoker** [comment]
Super game breaking shit D:

**Comment by Shauren** [comment]
included in my phasing stuff (probably)

**Comment by Shauren** [comment]
fixed.
cavalier is something else (bug in talent system)

**Comment by funjoker** [comment]
JIIIHAAAA
