### ISSUE TITLE
.npc delete crash

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#20124]
**Description:**

Using .npc delete command crashes

Here is a all stack of a sort. Creature::DeleteFromDB crashes and the reason is the call stack below where most recent call is last. GetCreatureBySpawnIdStore is modified while looped through. DeleteFromDB is called by .npc delete command.
```
Creature::DeleteFromDB -- loops through GetMap()->GetCreatureBySpawnIdStore().equal_range
WorldObject::AddObjectToRemoveList
Map::AddObjectToRemoveList
WorldObject::CleanupsBeforeDelete
Creature::RemoveFromWorld -- calls Trinity::Containers::MultimapErasePair(GetMap()->GetCreatureBySpawnIdStore(), m_spawnId, this);
The loop resumes in Creature::DeleteFromDB

Result: invalid iterator
```

**Current behaviour:**

Using .npc delete crashes

**Expected behaviour:**

Using .npc delete deletes the targeted creature

**Steps to reproduce the problem:**

1. Spawn an npc by using `.npc add 36`
2. Delete the NPC by targeting it and using `.npc delete`

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/f9f5a701f48bbb703658a99d689270d6bd7469c6

**TDB version:**  

**Operating system:** windows

**Comment by tkrokli** [comment]
TrinityCore rev. 4f43f4d72f10 2017-08-08 20:29:30 +0200 (3.3.5 branch) (Win64, Release, Static)

Hmm, any other criteria to replicate this crash issue? Testing on a level 73 GM account character with `.gm off` and `.gm visible on` , I am able to delete it with no crash, but I guess it helps to be in Westfall when I do it (home of `creature_template.entry` 36, Harvest Golem. Meh, I should test this in other areas too, maybe there is some sort of restriction on where those NPCs are supposed to exist.
