### ISSUE TITLE
Core: Dupe glitch with Eternals/Crystallized elements

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#20130]
**Description:**

Stumbled upon a bug where eternals can be duped. Video attached below shows the process and that the duped items can be traded between other players. 

**Current behaviour:**

If you have two stacks of Crystallized essences in your bag, one full stack and one less than full, you can simply spam click the stack that is not full and it will sometimes (Seems variable, some players mentioned more success with higher latency) duplicate into two full Eternals. Also attempted this with other mats like Enchanting mats, but could not duplicate.

**Expected behaviour:**

If clicked, whether it be spammed or not, it should only ever create the one eternal that you have enough mats to create.

**Steps to reproduce the problem:**

1. Obtain two stacks of Crystallized essences, one full and one less than full.
2. Spam click the less than full stack.
3. This will duplicate your essences into two full Eternals. The eternals can then be split into Crystallized and trade away the excess.
4. Repeat.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

4cf4961

**Operating system:** Windows Server 2012

**Attached:**
https://www.youtube.com/watch?v=f32v7ld7CR8
Video showing the dupe as well as trading back and forth between players.

**Comment by Aokromes** [comment]
dupe ticket #19547
