### ISSUE TITLE
Scarlet Crusade faction issues?

### ISSUE THREAD

**Issue by Halokillerman7** [TrinityCore/TrinityCore#20132]
**Description:**

Have tried to edit the .dbc but not sure if i did it correctly but now the faction 21 goes back after the scarlet crusade faction 89 but just runs back to spawn location and resets

**Current behaviour:**

mobs do not attack each other just ran at each other and run back to spawn location reseting

**Expected behaviour:**

mobs should attack and kill each other

**Steps to reproduce the problem:**

npc 1831
npc 4474
or western plague lands at the location 47.2 ,51.6 Dalsons Tears ranch area 
**Branch(es):**

CHANGEME 3.3.5, master or both
 idk?

**TC rev. hash/commit:** 

no issues

**TDB version:**  TrinityCore rev. d96482b2d49c 2017-05-22 21:37:26 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** Windows

**Comment by morpheus4hire** [comment]
maybe same as #19998

**Comment by Halokillerman7** [comment]
yep

**Comment by tkrokli** [comment]
Yes, similar to my comment (https://github.com/TrinityCore/TrinityCore/issues/19998#issuecomment-318908861) about the Felstone Field farm building in Western Plaguelands and also a duplicate issue report as such. Please post in that issue if you want to add something practical which could help troubleshooting the issue. Closing this one as duplicate.
