### ISSUE TITLE
[3.3.5] [ICC] unmountable Mutated Abomination in Professor Putricide's fight

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20138]
**Description:** After using "Drink Me!" table in the room of Professor Putricide, the player that used the table gets a buff that, after 3 seconds, summons a Mutated Abomination and the player mounts (and controls) it so he can use special abilities. The part of mounting in the Mutated Abomination doesn't work.

**Current behaviour:** Mutated Abomination can't be mounted / controlled, it just spawns and stand still there making it almost impossible to complete Professor Putricide in higher difficulties.

**Expected behaviour:** Mutated Abomination should be mountable and controllable.

**Steps to reproduce the problem:** 

1. Go to Professor Putricide's room and use "Drink Me!" table to summon a Mutated Abomination.
2. See how the player can't use Mutated Abomination, it just changes the name to the player's name and nothing happens.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/00329fe9a505c437af0b7591d8321bf3b77ad7fb

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by sirikfoll** [comment]
You can use this as a workaround, until it gets properly fixed: https://github.com/TrinityCore/TrinityCore/commit/184c45cfe0fbe4f3e4fb701f0f99994df98bdc8a#commitcomment-23518109

**Comment by Raydor** [comment]
Summoning @Treeston then if you say this is related to dynamic spawn.

**Comment by nyhmii** [comment]
Exactly the same Issue.

**Comment by tkrokli** [comment]
@nyhmii : if you are trying to say that you have got the exact same issue, we would like to know which TC rev. hash/commit you are on. Otherwise, your comment does not help much.

**Comment by nyhmii** [comment]
@tkrokli 184c45c#commitcomment-23518109 is not a work around. it's what broke it in the first place. 

#20137 , #20138  - Broken by 184c45c

**Comment by tkrokli** [comment]
@nyhmii : 2 things you have misunderstood :
1. **sirikfoll** made the suggestion to use a workaround, I did not suggest that.
2. The suggestion was to use the line suggested by @shenhuyong :
```cpp
if (m_respawnCompatibilityMode && m_vehicleKit && !IsSummon() && m_spawnId)
    m_vehicleKit->Reset();
```
I don't know if that works or not, I have neither tested it myself nor suggested it to others.

Also: commit pages are not supposed to be discussions like a chat. Use IRC or TC Forum.

**Comment by nyhmii** [comment]
#20137 , #20138 New to commits and things. i found a fix to solve both at once. how do i proceed?

**Comment by Raydor** [comment]
You have to create a pull request so everyone can review your changes and tell you if those changes are valid or not or if you have to change some things before they merge your pull request into trinitycore.

Here is a guide on how to make a pull request:
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130070/Creating+a+Pull+Request
