### ISSUE TITLE
[3.3.5] [ICC] Bone Spikes of Lord Marrowgar send players to the void and also bugs their phase.

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20137]
**Description:** Bone Spikes of Lord Marrowgar are not working correctly, I'm not sure when this got bugged cause IIRC this was working correctly some time ago. I recommend you test this with http://wotlk.evowow.com/?spell=1908 for an easy test.

**Current behaviour:** When Lord Marrowgar bone spikes a player, that player stops seeing anything (don't know if this is intended but still) and if a player destroys that bone spike, the player that was trapped gets bugged out and changes phase constantly. After some time, if the same player gets bone spiked again, he goes into the void.

**Expected behaviour:** Bone Spiked player should not get sent into the void and should not continously change phase when freed from bone spikes.

**Steps to reproduce the problem:**

1. Make a party of for example 3 players (that's enough) and enter ICC
2. Start Lord Marrowgar fight and let him bone spike a player
3. Look how the player bone spiked can't see anything
4. Destroy the bone spike of that player
5. Look how that the phase of that player bugs out constantly
6. Let Lord Marrowgar spike him again
7. See how he is sent to the void

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/00329fe9a505c437af0b7591d8321bf3b77ad7fb

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by nyhmii** [comment]
#20137 , #20138 - Broken by 184c45c

**Comment by Adizbek** [comment]
When you die sometimes you spirit appear in Westfall.

**Comment by Aokromes** [comment]
Blizzlike "bug"
