### ISSUE TITLE
Unavaible to connect to server! All requiremends passed!

### ISSUE THREAD

**Issue by Lucky-Patcher** [TrinityCore/TrinityCore#20143]
**Description:**

After setting up the server, spend lots of time i am unable to connect to the server
**Current behaviour:**

CHANGEME Tell us what happens.
I created the server, compiled on linux and windows and after using the connection patcher i am not able to join my server
**Expected behaviour:**

i get a instand disconnect after logging in
**Steps to reproduce the problem:**

1. Step Create a server on linux and compile the minimum needed on windows eg connection patcher  
2. Step create a account and try to login from windows
3. Step get the disconnected message

**Branch(es):**

master

>TrinityCore rev. cb4dd9262914 2017-08-10 20:58:35 +0200 (master branch) (Unix, Release, Static) (worldserver-daemon) ready...

**TDB version:**  CHANGEME Version of the TrinityCore database
TDB 720.00

**Operating system:** CHANGEME OS
Debian 9 x64 & Windows 10 Pro

**Comment by tkrokli** [comment]
Please link a screenshot of the entire screen when getting the disconnect message.

**Comment by Lucky-Patcher** [comment]
Link of Screen : 

http://prntscr.com/g7p65g

**Comment by Lucky-Patcher** [comment]
Fixxed by Changing the restapi external ip address it sucks with local
