### ISSUE TITLE
[3.3.5] Gobs are not deletable while despawned

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20145]
**Description:** Gobs that have a despawn effect and should respawn after some time are not deletable while despawned. @Treeston.

**Current behaviour:** Some gobs can't be deleted while despawned but .gob near and .gob target says they are there but if you try to delete them by guid, the .gob delete command returns "not found".

**Expected behaviour:** Gobs should be deletable while despawned.

**Steps to reproduce the problem:**

1. Spawn a gob that have a despawn effect and should respawn, for example http://wotlk.evowow.com/?object=2691
2. Use the gob (with gm on so you can use it) and let it despawn
3. Use .gob near or .gob target to see how these commands say it is there (but despawned)
4. Use .gob delete GUID and see how it says "not found"

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/d09de6425ca789bed991f1e80652d57a7c5ff37b

**TDB version:** TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by r00ty-tc** [comment]
That's because they're genuinely not there any more. There probably should be a method added to do it by spawnId, regardless of spawned state. But it won't happen based on where it used to be, because dynamic spawns makes them actually despawn now (as they should always have).

**Comment by Raydor** [comment]
It's so frustrating not being able to delete a gob that is despawned. You just need to wait until it respawn and then delete it or restart the server and delete it.

**Comment by Telepathique** [comment]
@Raydor hi, try this : use the command .gob activate guid# and then .gob delete guid# it should work. or if you have access to the DB you can directly delete them by ID and wait to restart your server :)

**Comment by Treeston** [comment]
I continue to be baffled that there are actually use cases for the clusterfuck of hacks that are the in-place DB manipulation commands.

**Comment by Treeston** [comment]
Added another hack to the hack pile, that fixes it. Yay, progress.
