### ISSUE TITLE
[3.3.5] Fix UpdateMovementFlags ignoring DynamicTree height  never Updated into 3.3.5a branch.

### ISSUE THREAD

**Issue by nyhmii** [TrinityCore/TrinityCore#20141]
Fix UpdateMovementFlags ignoring DynamicTree height -> b85b0c2

**Comment by tkrokli** [comment]
1. I think you mean commit https://github.com/TrinityCore/TrinityCore/commit/a7ee951d9efcfb0a0a5b9ed1ec3a732c06d8877f (the PR #15168 merge commit).
2. Check commit https://github.com/TrinityCore/TrinityCore/commit/f6c849729b27b77228704b595de3adaf24da2c10#diff-f3f953a63e2a008d22de69cb68f735c4 (from PR #19840) from 2017-06-07 first.
  It changed line 2917 - from what you are asking for - into what it is now.

**Comment by Keader** [comment]
?
