### ISSUE TITLE
[3.3.5] Movement: waypoint movement 

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20142]
**Description:** When the Warsong Wind Rider lifts off, he flies very slowly.

Example: Wind Master To'bor & Warsong Wind Rider 

Many console Messages:
```
Unit (Entry 18950) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18950) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18949) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18971) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18950) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
Unit (Entry 18948) is trying to delete its updating Movement Generator (Type 2)!
```
Has worked well with this version without error Messages

TrinityCore rev. 00329fe9a505 2017-08-10 04:54:00 +0200 (335 branch)

**Branch(es):**  3.3.5

**TC rev. hash/commit:** TrinityCore rev. e2565c2597a7 2017-08-11 23:06:37 -0300 (335a branch)

**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Win7 64Bit

**Comment by ccrs** [comment]
There are two issues reported here,

first one is the log, which makes 0 sense, not necessary and not a "FATAL" situation
second one is the speed, will take a look

**Comment by ccrs** [comment]
cd4775420a4894012616d54467eb3827430245b5
taking a look to the second part now

**Comment by Tauriella** [comment]
imo no console Messages :+1:

**Comment by tkrokli** [comment]
You can avoid console messages if you want to. For warnings like the one above, just edit the worldserver.conf section `LOGGING SYSTEM SETTINGS` and remove `Console` from `Logger.sql.sql=5,Console DBErrors` so the messages will only appear in the log file.

**Comment by Tauriella** [comment]
Thanks for the Info :

**Comment by Killyana** [comment]
The speed issue: https://github.com/TrinityCore/TrinityCore/issues/21463
