### ISSUE TITLE
[3.3.5][ICC] Blood Prince Council Phasing/Vehicle Reset - Glitching making fight impossible 

### ISSUE THREAD

**Issue by nyhmii** [TrinityCore/TrinityCore#20153]
**Description:**
After starting boss fight : Blood Prince Council, Prince Valanar's hp bounces from 0 to 1882. Like he is resetting or re-appearing the whole time.  When you engage, he will suddenly die. and every-time they swap, one of the council dies and just do "nothing".

**Current behaviour:**
all 3 blood council princes are dead, while Valanar's hp bounces from 0 to 1882. Fight stops after all 3 die when each one get's the "HP stage". same problems as #20137 , #20138 

**Expected behaviour:**
Should initiate with at-least Valanar's Hp at full. and not phase out or die. 

**Steps to reproduce the problem:**
1.Just initiate the fight and damage Prince Valanar.

![image](https://user-images.githubusercontent.com/30576834/29420022-0eda050c-8371-11e7-8102-a55d09571167.png)

**Branch(es):**
 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 039a70704018 2017-08-10 17:14:53 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  
TDB 3.3.5 63

**Operating system:**
Windows 8

**Comment by nyhmii** [comment]
Still working on my 1st Commit, but i think this is the problem  : 

if (IsAIEnabled && m_triggerJustAppeared && m_deathState == ALIVE) <---- That Part there(they are in a DEAD state)
      {
        m_triggerJustAppeared = false;
         AI()->JustAppeared();
          if (m_vehicleKit)
              m_vehicleKit->Reset(); <--- resets Hp/ when attacking making it "reset to Dead" again...

**Comment by nyhmii** [comment]
Attacked it with 1 damage, resets to Dead state. 
![image](https://user-images.githubusercontent.com/30576834/29420976-ec2ebe64-8373-11e7-8af1-89b361511893.png)

**Comment by nyhmii** [comment]
Just some more screenies:

![wowscrnshot_081717_175327](https://user-images.githubusercontent.com/30576834/29421506-94813230-8375-11e7-869a-f0363b8aa95e.jpg)
![wowscrnshot_081717_175348](https://user-images.githubusercontent.com/30576834/29421508-94818a1e-8375-11e7-83be-77fbee051824.jpg)
![wowscrnshot_081717_175351](https://user-images.githubusercontent.com/30576834/29421507-94815030-8375-11e7-9095-83670a6afc71.jpg)
![wowscrnshot_081717_175436](https://user-images.githubusercontent.com/30576834/29421509-94822d5c-8375-11e7-905f-fb94076a7a3e.jpg)

**Comment by Shauren** [comment]
I don't think so. Their m_deathState is not DEAD. Its ALIVE. They only use feign death mechanic

**Comment by nyhmii** [comment]
so what why did 
if (IsAIEnabled && m_triggerJustAppeared && m_deathState == ALIVE) 
m_triggerJustAppeared = false;
AI()->JustAppeared();
if (m_vehicleKit)
m_vehicleKit->Reset();

break that mechanic. since this temp fix. this happend
