### ISSUE TITLE
Missing Texts for Farmer Saldean

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20154]
**Description:**

Farmer Saldean should say some texts every few minutes.

**Current behaviour:**

Farmer Saldean does not say anything.

**Expected behaviour:**

Farmer Saldean should speak.

**Steps to reproduce the problem:**

1. .tele saldean
2. Look for Farmer Saldean.
3. Wait next to him for all the time you want.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa68855d7d0 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Comment by ZenoX92** [comment]
I found the texts and create a SAI script for him; but I'm just a noob. You guys are the experts, so chek it. I just hope it be of help.

**Suggested Fix:**

UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=233;
DELETE FROM `creature_text` WHERE `CreatureID`=233;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
('233','0','0','Now how am I supposed to get those mechanical wretches out of my fields?','12','7','100','0','0','0','58','0','Farmer Saldean'),
('233','0','1','A bunch of thugs and thieves aren\'t going to get me to leave my land!','12','7','100','0','0','0','59','0','Farmer Saldean'),
('233','0','2','They might have run all the other farmers off, but the Saldean\'s will never leave Westfall.','12','7','100','0','0','0','60','0','Farmer Saldean');
DELETE FROM `smart_scripts` WHERE `entryorguid`=233;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
('233','0','0','0','1','0','100','0','1000','1000','180000','180000','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','Farmer Saldean - Out of Combat - Say Line 0');

**Comment by offl** [comment]
> BroadcastTextId 58 59 60

So he was one of the first NPC with script :)

**Comment by tkrokli** [comment]
Recommended TC code style SQL formatting:
```sql
-- Farmer Saldean - add back missing Out of Combat say text
UPDATE` `creature_template` SET `AIName`='SmartAI' WHERE `entry`=233;

DELETE FROM `creature_text` WHERE `CreatureID`=233;
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(233,0,0, "Now how am I supposed to get those mechanical wretches out of my fields?", 12,7,100,0,0,0,58,0,'Farmer Saldean'),
(233,0,1, "A bunch of thugs and thieves aren't going to get me to leave my land!", 12,7,100,0,0,0,59,0,'Farmer Saldean'),
(233,0,2, "They might have run all the other farmers off, but the Saldean's will never leave Westfall.", 12,7,100,0,0,0,60,0,'Farmer Saldean');

DELETE FROM `smart_scripts` WHERE `entryorguid`=233;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(233,0,0,0,1,0,100,0,1000,1000,180000,180000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Farmer Saldean - Out of Combat - Say Line 0');
```
1. Never put apostrophes ( ' ) around (integer) numbers.
2. Use double quotation marks ( " " ) when inserting text containing apostrophes to skip escapes.
3. Simple text without apostrophes in it can be quoted with single quotes (apostrophes).
