### ISSUE TITLE
Core/Gameobject: linked Traps respawns before the original gob

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#20159]
**Description:** For GAMEOBJECT_TYPE_CHEST that have  data7: linkedTrap  (GO type 6) the trap respawn before the original gob, so you will see the trap long time before the gob respawn.

**Current behaviour:** The trap respawn before the gameobject.

**Expected behaviour:** The trap must be respawned at the same time as the gameobject.

**Steps to reproduce the problem:**

1. .go obj 50420    [Netherwing Egg] GUID: 50420 ID: 185915
2. Notice the violet smoke is the trap
3. Loot the egg
4. Notice the egg and the linked trap despawns (until this step everything is fine)
5. Wait some minutes and notice the violet smoke appears (the trap) but the egg is still in not respawned

The issue is not related to dynamic spawns at it happen before.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e2565c2597a7

**Comment by Killyana** [comment]
Actually the trap is not "respawned" but summond by the original gob.

**Comment by nyhmii** [comment]
Fix - 165bc02

tested

Thanks Treeson!

**Comment by Killyana** [comment]
Not fixed on rev. 1f57d1ac67fb

**Comment by Killyana** [comment]
It looks like the trap is just deactivated by  GO_JUST_DEACTIVATED instead of being despawned, that will make it respawn after 5min.
Solution:
``` diff
diff --git a/src/server/game/Entities/GameObject/GameObject.cpp b/src/server/game/Entities/GameObject/GameObject.cpp
index fbc8c260cd..2863b351e3 100644
--- a/src/server/game/Entities/GameObject/GameObject.cpp
+++ b/src/server/game/Entities/GameObject/GameObject.cpp
@@ -415,7 +415,6 @@ void GameObject::Update(uint32 diff)
         else
             DespawnOrUnsummon(0ms, m_despawnRespawnTime);
     }
-
     switch (m_lootState)
     {
         case GO_NOT_READY:
@@ -529,10 +528,6 @@ void GameObject::Update(uint32 diff)
                         m_SkillupList.clear();
                         m_usetimes = 0;
 
-                        // If nearby linked trap exists, respawn it
-                        if (GameObject* linkedTrap = GetLinkedTrap())
-                            linkedTrap->SetLootState(GO_READY);
-
                         switch (GetGoType())
                         {
                             case GAMEOBJECT_TYPE_FISHINGNODE:   //  can't fish now
@@ -727,7 +722,7 @@ void GameObject::Update(uint32 diff)
         {
             // If nearby linked trap exists, despawn it
             if (GameObject* linkedTrap = GetLinkedTrap())
-                linkedTrap->SetLootState(GO_JUST_DEACTIVATED);
+                linkedTrap->DespawnOrUnsummon(0ms, m_despawnRespawnTime);
 
             //if Gameobject should cast spell, then this, but some GOs (type = 10) should be destroyed
             if (GetGoType() == GAMEOBJECT_TYPE_GOOBER)
