### ISSUE TITLE
Disable spell for MapID in Disables does not work

### ISSUE THREAD

**Issue by Infinito47** [TrinityCore/TrinityCore#20151]
**Description:**
Disable spell for MapID in Disables does not work

**Current behaviour:**

When trying to disable a spell in battlegrounds using the MapID flag for Disables; it does not seem to work. However, Disabling the spell entirely for all players does seem to work.

**Expected behaviour:**

The spell should be disabled in the specified MapIDs

**Steps to reproduce the problem:**

1. Disable a spell in Disables using flag sourcetype 0, flags 16 and params_0 to specify the map id
2. Server restart and /or .reload disables
3. Spell still works

**Branch(es):**

3.3.5, branch

**TC rev. hash/commit:** 

4cf4961

**TDB version:** TDB 335.63	63

**Operating system:** Windows Server 2008 R2

**Comment by Aokromes** [comment]
1 | DISABLE_TYPE_QUEST
-- | --

**Comment by Aokromes** [comment]
it must be 17.

**Comment by tkrokli** [comment]
Aha. You need to combine the flags `1 (players) + 16 (MapId)` to achieve your intended effect.
- https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130172/disables#disables-flags

**Comment by Keader** [comment]
RTFM case hehe
