### ISSUE TITLE
[3.3.5] Bowmans missing from Alterac Valley

### ISSUE THREAD

**Issue by Aknunx** [TrinityCore/TrinityCore#20165]
**Description:**

Bowmans are missing on the Frostwolf towers and Stormpike bunkers on Alterac Valley.

**Current behaviour:**

Currently the bunkers/towers from alterac valley have guardians instead of bowmans, which shouldn't be there at all.
Also when spawneds directly with .npc add the bowmans are missing their ranged weapon, meaning that they do not perform their ranged attacks.

**Expected behaviour:**

Stormpike bunkers should've Stormpike Bowmans (13358) spawned and Frostwolf towers should've Frostwolf Bowmans (13359) spawned.

**Steps to reproduce the problem:**

1. http://www.wowhead.com/npc=13358/stormpike-bowman http://www.wowhead.com/npc=13359/frostwolf-bowman
2. Join Alterac Valley.
3. Get near a tower/bunker and check the npc's there.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/fe2db0731328e104ea9e8f5d7081e732c9f02e6f

**TDB version:**  DB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/de4986d7d406120d5fd89bada3e06827e30fa604

**Comment by Raydor** [comment]
Why close if that commit is not yet merged into 3.3.5, this is still a valid issue.

**Comment by Aokromes** [comment]
because a wip for it is already opened.

**Comment by Raydor** [comment]
Imo this should be openned until it gets merged anyways, there are other wips in pull requests and issues fixed by those PR are still openned.

**Comment by Aokromes** [comment]
we never acepted tickets for already wip

**Comment by tkrokli** [comment]
Fair enough. When testing that recommended commit / branch https://github.com/TrinityCore/TrinityCore/tree/3.3.5-battleground_rewrite , is there a recommended page to report new results?
