### ISSUE TITLE
[3.3.5] GO respawntime fix for some Quests

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20162]
-- Suggest Fix for some Quest GO's
-- All existing quest I've tested on the Blizzserver.
 
http://www.wowhead.com/quest=1182/goblin-sponsorship
http://de.wowhead.com/object=20691/cozzles-schliesskiste

http://www.wowhead.com/quest=11789/a-soldier-in-need
http://de.wowhead.com/object=187980/vorrate-fur-erste-hilfe
https://www.youtube.com/watch?v=mzUeabxzRWo

https://www.youtube.com/watch?v=TRyqfWqhv74
http://de.wowhead.com/quest=10058/ein-altes-geschenk
http://de.wowhead.com/object=182804/geheimnisse-des-lichts

http://de.wowhead.com/object=182542/versiegelter-kasten
-- //Tested on Blizzserver

https://www.youtube.com/watch?v=L1A-Iw_-UQs
http://de.wowhead.com/object=181133/rathis-tombers-vorrate

http://de.wowhead.com/quest=9176/die-zwillingsziggurats
http://de.wowhead.com/object=181239/abgenutzte-truhe
http://de.wowhead.com/object=181238/verbeulte-truhe
https://www.youtube.com/watch?v=1OfhUIQoXJo

https://www.youtube.com/watch?v=C0UsHos7Z9I
http://de.wowhead.com/quest=9163/in-besetztem-gebiet
http://de.wowhead.com/object=181138/nachtelfenplane-andaroth
http://de.wowhead.com/object=181139/nachtelfenplane-anowyn
http://de.wowhead.com/object=181140/nachtelfenplane-auskundschaften-der-sindorei

https://www.youtube.com/watch?v=IyhD-pdI73o
http://de.wowhead.com/quest=9062/aufgeweichte-seiten
http://de.wowhead.com/object=181110/aufgeweichter-foliant

http://de.wowhead.com/quest=9692/der-pfad-des-adepten
http://wowdata.buffed.de/object/Kiste-mit-Bloecken-182011

https://datenbank.classic-wow.org/?object=20925
http://de.wowhead.com/quest=1202/die-docks-von-theramore
https://www.youtube.com/watch?v=UqixJz9d8pU

http://de.wowhead.com/quest=9437/der-untergang-der-morgenbo
http://de.wowhead.com/item=23657/fracht-der-morgenbo
https://www.youtube.com/watch?v=jCnV_1FSFWk
-- //Tested on Blizzserver

``` sql
-- Wrong respawntimer for some Quest GameObjects
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (20691,187980,182804,183050,181133,181238,181239,181110,182011,20925);
UPDATE `gameobject` SET `spawntimesecs` = 5 WHERE `id` IN (181138,181139,181140);
UPDATE `gameobject` SET `spawntimesecs` = 60 WHERE `id` IN (182542,181626);
```

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)

**TC rev. hash/commit:** 
 TrinityCore rev. 4f7df63f22ab 2017-08-17 23:10:41 +0200 (335a branch)

**TDB version:**  
TDB_full_world_335.63_2017_04_18 + updates

**Operating system:**  
Win7 64Bit

**Comment by tkrokli** [comment]
About this line:
```sql
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN (20691,187980,182804,183050,181133,181238,181239,181110,182011,20925);
```
```
 entry  name
------  --------------------------
 20691  Cozzle's Footlocker
 20925  Captain's Footlocker
181110  Soaked Tome
181133  Rathis Tomber's Supplies
181238  Dented Chest
181239  Worn Chest
182011  Crate of Ingots
182804  Mysteries of the Light
183050  The Saga of Terokk
187980  First Aid Supplies
```
Is the gameobject respawn time really unchanged since 10/10/2010 (Cataclysm release), that it has always been 2 seconds for those gameobjects? (I don't know, I just find it odd that there used to be any faster respawn time than 5 seconds back in the WotLK 3.3.0 - 3.3.5 days.)

**Comment by Tauriella** [comment]
On Blizzserver is for the most Quest GO's the respawntime "0"
But 
@Killyana  commented on Oct 1 2016 
Don't use respawntime=0, if the gob is unique always use 2secs.

The 5Sek respawntime is correct i have testet on Blizzserver but i have Forget the comment

**Comment by Killyana** [comment]
On retail some unique gobs doesn't despawn anymore, it wasn"t the case during wotlk and cata.

**Comment by tkrokli** [comment]
OK, very well. About code comments, would something like this be useful, or is it too much?
```sql
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `id` IN
(20691,  -- Cozzle's Footlocker
 20925,  -- Captain's Footlocker
181110,  -- Soaked Tome
181133,  -- Rathis Tomber's Supplies
181238,  -- Dented Chest
181239,  -- Worn Chest
182011,  -- Crate of Ingots
182804,  -- Mysteries of the Light
183050,  -- The Saga of Terokk
187980); -- First Aid Supplies

-- Night Elf Plans: An'daroth, An'owyn, Scrying on the Sin'dorei
UPDATE `gameobject` SET `spawntimesecs` = 5 WHERE `id` IN (181138,181139,181140);
-- Sealed Box (Investigate Tuurem), Dawn Runner Cargo/Warped Crates
UPDATE `gameobject` SET `spawntimesecs` = 60 WHERE `id` IN (182542,181626);
```
