### ISSUE TITLE
[3.3.5] Broken SPELL_EFFECT_SUMMON summoning vehicle and certain SmartAI case

### ISSUE THREAD

**Issue by lachtanek** [TrinityCore/TrinityCore#20179]
**Description:**

Apart from the reported issues, I observed that 184c45cfe0fbe4f3e4fb701f0f99994df98bdc8a sadly broken at least two more things:
1. SPELL_EFFECT_SUMMON which summons vehicle
What happens is, when spell like this summons vehicle, it immediatelly casts spell as sumonner to ride vehicle (SpellEffects.cpp:2312), then the first creature update calls Vehicle::Reset (Creature.cpp:620), which calls Vehicle::InstallAllAccessories, which calls Vehicle::RemoveAllPassengers, which ejects passenger and vehicle is despawned shortly after.
2. SMART_EVENT_JUST_SUMMONED can't trigger SMART_ACTION_WP_START, because again when SmartAI::JustAppeared() is called, it resets mEscortState, which basically stops escorting and waypoint movement.
3. it may have broken other things, not sure, if I find any I'll let you know

Not sure about the solution, maybe revert the commit (but this new JustAppeared functionality sounds more convenient so I would probably keep it) or set m_triggerJustAppeared false on creation of TempSummon

**Steps to reproduce the problem:**

Reproducing first problem:
1. .quest add 11636
2. .go creature 125433 OR .npc add temp 25459
3. click gossip option, carpet should appear and take you away, but it does not (it does, but it disappears right away due to before mentioned reason)

Reproducing second problem:
Try to add quest 12301 (its somewhere in dragonblight, POI should help you with coordinates) and use item on rune-marked spot, Alliance Emissary doesn't start his script

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

184c45cfe0fbe4f3e4fb701f0f99994df98bdc8a, will test on current as soon as possible, but I'm nearly certain 92e9376e5eecdc3412104a0ee304d389d4ce0188 didn't fix it (because it was not reported) and other changes to the functionality haven't been made

**Operating system:** All

**Comment by nyhmii** [comment]
I have a fix for you,
REPLACE:
if (m_respawnCompatibilityMode && m_vehicleKit)
m_vehicleKit->Reset(); 
WITH:
if (m_respawnCompatibilityMode && m_vehicleKit && !IsSummon() && m_spawnId)
    m_vehicleKit->Reset(); 

Or Do the long fix, 
165bc02 <- Treeston

**Comment by Treeston** [comment]
Please report back if reproduced on 92e9376, it should fix the issue.

**Comment by lachtanek** [comment]
I'm sorry, couldn't get to this earlier, fixes both problems, I didnt understand the issue as well as I throught

**Comment by nyhmii** [comment]
what do you mean?

**Comment by lachtanek** [comment]
I initially throught Treeston's commit won't fix the issue (as I wrote in the report), but it did.
