### ISSUE TITLE
Missing Texts for Zem Leeward

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20174]
**Description:**

Zem Leeward should say some texts every few minutes.

**Current behaviour:**

Zem Leeward does not say anything.

**Expected behaviour:**

Zem Leeward should speak.

**Steps to reproduce the problem:**

1. .tele lakeshire
2. Look for Zem Leeward.
3. Wait next to him for all the time you want.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Comment by Killyana** [comment]
Cannot find any text, do you have an example?

**Comment by ZenoX92** [comment]
**Suggested Fix:**

```sql
-- Zem Leeward
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=348;

DELETE FROM `creature_text` WHERE `CreatureID`=348;
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
('348','0','0','Nothing biting....','12','7','100','0','0','0','45','0','Zem Leeward'),
('348','0','1','Here fishy fishy. . . come to papa.','12','7','100','0','0','0','46','0','Zem Leeward');

DELETE FROM `smart_scripts` WHERE `entryorguid`=348;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(348,0,0,0,1,0,100,0,1000,15000,150000,180000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,'Zem Leeward - Out of Combat - Say Line 0');

**Comment by ZenoX92** [comment]
@Killyana Those are the texts, and the SAI script (Check the timing). I hope it helps.

**Comment by Killyana** [comment]
Looks good.

**Comment by ZenoX92** [comment]
@Killyana Thanks! Glad to be of help! I also have other texts for other other NPCs. Should I post them as Issues, just like this one???

**Comment by Killyana** [comment]
Yes one issue per npc.
Thanks for helping.
