### ISSUE TITLE
Auth Token Implementation

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#20178]
**Description:**

https://github.com/TrinityCore/TrinityCore/pull/10527

**Current behaviour:**

Not Implemented

**Expected behaviour:**

Login Token for more account security.

**Steps to reproduce the problem:**

No steps!

**Branch(es):**

both

**TC rev. hash/commit:** 

ab916fd1b37ca39071c2253be68e60ac2a735ada

**TDB version:**  CHANGEME Version of the TrinityCore database

TDB720.00

**Operating system:** CHANGEME OS

**Comment by Infernales** [comment]
On branch 3.3.5 works fine.

**Comment by Shoxxo** [comment]
how you can work with it on 3.3.5A ?

On my 3.3.5A it failes after setting it to 10^8

I tried using https://authenticator.me/

**Comment by Infernales** [comment]
Through the program "FreeOTP" for Android and iOS.

**Comment by Shauren** [comment]
You need to use google variant @Shoxxo - as the name implies TOTP is time based. Blizzard has their own time service for synchronizing authenticators which gives you different results than time on your pc (so blizz authenticator will not work)

ps. well... it would, if you managed to sync times

**Comment by Aokromes** [comment]
as PR states:

"
To properly use, set token_key fields with secure key in base32 form, and make sure your server time is set properly - time() returns GMT/UTC time, and ntp is synchronising time on server."

**Comment by Shoxxo** [comment]
Have build a solution for my server :)

Demo : https://www.noones-wow.com/token.php

Tested on my server and worked for the 3.3.5A version!

**Comment by funjoker** [comment]
Well kinda advertisment lol.
PS @Shoxxo. 
In germany you must have an imprint!
And yes it is germany.

**Comment by Shoxxo** [comment]
I know. But the ste is under construction without a shop system. So for the moment it is only to test token generation etc. An imprint will come later sure.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17366
