### ISSUE TITLE
[Crash] - Object::GetGuidValue

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20171]
**Description:**
No idea about this crash :(

Crashlog: https://gist.github.com/Jildor/e9f2db4f7972d361a0ac4547055c4562
Old crashlog (rev about December 2015): https://gist.github.com/Jildor/77975737cfac852745e35a236735c9eb

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 26d, if this bug is still valid open a NEW ticket with updated core.
