### ISSUE TITLE
Spawning missing creatures in Pandaria,Warlods of Draenor and Legion

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/TrinityCore#20186]
Adding missing creatures spawns in maps 780,1116,1220.

- Master

last commit: https://github.com/TrinityCore/TrinityCore/commit/28ec50b0534c721e613d68b7b1daa73d573fbc17

file creatures: 
file creature_template:
file creature_equip_template:
file creature_loot_template1:
file creature_loot_template2:
file creature_queststarter:
file creature_questender:
file creature_template_addon:
Uploaded in mega everything: 
https://mega.nz/#!yVBzkDoK!PvfQKSShlwjtwAVIFH3JPaRgpiH1IA-yaJggQCxHogU

**Comment by Killyana** [comment]
Creature_addon missing.

**Comment by Kittnz** [comment]
Is this from a leveling sniff?

**Comment by Daniel25** [comment]
It isnt a leveling sniff. The most of creatures are there (except legion). 
Timeless isle npcs are missing by the way.
I have only 36.338 creature_addon of that 123.000 spawns in my db. And I havent the sniffers now...
If the request isnt ok, no problem.

**Comment by HannibalRoG** [comment]
Most of npc in draenor and legion appear green (friendly) and with very low live.

**Comment by Daniel25** [comment]
Added creature_template_addon, creature_template, creature_queststarter, creature_questender and creature_loot_template for maps 870,1116,1220.
About duplicated spawns...strange....

**Comment by offl** [comment]
What happened to numbers after dots(PosX, PosY, PosZ, Orientation columns)? :)
```sql(@CGUID+78011,91565,1220,0,0,1,0,0,0,0,2198,2221,364,5,300,0,0,40962,0,0,0,0,0,23222),
(@CGUID+78012,91561,1220,0,0,1,0,0,0,0,2200,2222,364,2,300,0,0,40962,0,0,0,0,0,23222),
(@CGUID+78013,91561,1220,0,0,1,0,0,0,0,2217,2208,354,5,300,0,0,40962,0,0,0,0,0,23222),
(@CGUID+78014,91561,1220,0,0,1,0,0,0,0,2212,2205,356,3,300,0,0,40962,0,0,0,0,0,23222),
(@CGUID+78015,92367,1220,0,0,1,0,0,0,0,2204,2205,358,4,300,0,0,40962,0,0,0,0,0,23222),
(@CGUID+78016,91561,1220,0,0,1,0,0,0,0,2222,2210,353,0,300,0,0,40962,0,0,0,0,0,23222),

**Comment by HannibalRoG** [comment]
@ArcaneFox I have some sniff from draenor and pandarian, email me if you want the link to download.
It is sensitive information, because of that i dont want to public them.

**Comment by ArcaneFox** [comment]
I need some time to make a program for this. Once I finished it, I will post the updated sql here.

The program fill fix the duplicated spawns (only the same position) and the missing values (like 1 hp).

@HannibalRoG I will need only the sql files. Currently, I have two different sources: MoP + MoP/Draenor/Legion. Both of them are leveling sniffs.

**Comment by ArcaneFox** [comment]
Removed 10247 duplicated spawn
Wrong column values - WIP

[creature.zip](https://github.com/TrinityCore/TrinityCore/files/1253019/creature.zip)

**Comment by uroborusLogos** [comment]
Twilight Highlands Is not spawned.

**Comment by funjoker** [comment]
Duplicate spawns can indicate personal spawns or temporary spawns.

**Comment by Daniel25** [comment]
What funjoker said. If then of adding the creature_template there are duplicated spawns so maybe we can delete them. Surely there are duplicated spawns because of quests spawns, phased creatures,etc...
I just wanted to share that spawns because noone is sharing it and that maps are empty... If it is causing more issues that other thing, so you can close the request and everything will be ok :).

**Comment by HannibalRoG** [comment]
From almost the last GUID in actual DB, started in 450014 used here https://github.com/TrinityCore/TrinityCore/pull/17021 plus 2500 GUID aproximately in that PR i think GUID 453000 is a good number for this 112879 spawns.
I am rigth?

**Comment by HannibalRoG** [comment]
@ArcaneFox The problems of low life, level 1 and npc friendlys are maintained, even in your sql.
Another thing, due to the lack of information in the creature table the npc when you approach it fall from the sky.

**Comment by ArcaneFox** [comment]
@HannibalRoG Could you send me a wrong npc (or guid)?

**Comment by HannibalRoG** [comment]
@ArcaneFox .tele draenor where you appear all npc are wrong level and all green, one guid 501612

**Comment by ArcaneFox** [comment]
Yes, they are wrong without 
 - creature_template
 - creature_equip_template
 - creature_loot_template1
 - creature_loot_template2
 - creature_queststarter
 - creature_questender
 - creature_template_addon

but they are working with these sqls:
![wowscrnshot_090517_220333](https://user-images.githubusercontent.com/25306170/30081258-bf997f02-9286-11e7-8b26-d2df13b35d54.jpg)

**Comment by HannibalRoG** [comment]
@ArcaneFox what sql did you apply, the one from daniel25 or yours with the duplicated spawn removed?

**Comment by HannibalRoG** [comment]
Problem solved, i was imported only your creature... LoL
btw creatures appear yelow that means neutral... do you know how to solve?

**Comment by ArcaneFox** [comment]
I don't know well the tables of TrinityCore, but if someone could tell me the possible bad values in the fields, then maybe I can fix them (or at least separate the wrong spawns to an another file).

**Comment by Daniel25** [comment]
neutral faction=7, you can check in wowhead the correct faction or in the dbc file. (I suposse that you have .gm off).

**Comment by HannibalRoG** [comment]
I dont use GM account for testing thinks like this, i use an account with level 0, and add with RBAC commands like .tele and .modify speed.
@ArcaneFox I think we should wait for the opinion of some of the TRINITY developers to know if these npc can be added to the official DB and not waste time with them.

**Comment by funjoker** [comment]
In the past there was the idea of accepting spawns only with phases and cleaned.
But since this is a fulltime job i guess this is kinda impossible

**Comment by Hellfurian** [comment]
@ArcaneFox Getting errors trying to import your sql file :| Unknown column 'xyz' in 'field list'?

Probably something wrong on my side.

**Comment by ArcaneFox** [comment]
I don't know what changes happened to the creature table, but you can fix/import the creatures.sql with the following steps.

1) Drop your "world" db
2) Import TDB 720.00 [optional: update to 2017-08-25]
3) Import the creatures.sql
4) Update your TDB
5) Export the imported creatures to a new file

**Comment by Aokromes** [comment]
he gets error because he tried to import it without adding real guid.

**Comment by Hellfurian** [comment]
@Aokromes you're right. I feel incredibly dumb now... Thank you both.

**Comment by LuigiElleBalotta** [comment]
Since master branch is not stable i think we should take spawns as they are from sniffs. and while scripting quests etc... we can fix phases, personal spawns etc.. removing things not needed and keeping things needed.. at least we poor dev without sniffs can have sufficient data to work with

**Comment by ArcaneFox** [comment]
I've been working on this since yesterday (finally my PC working again). Trainers, vendors, flight masters, other npcs with gossip menu are spawned. Every duplicated and moving creature has removed.

WIP:
 - GUID separation
 - Hostitle creatures
 - Netural creatures

Someone know a method to separate pandaria/draenor/legion creatures?

**Comment by Killyana** [comment]
You can use entry plage, or map ID.

**Comment by ArcaneFox** [comment]
Separated 17513 moving creatures.

Need to test "creature (idle npcs).sql" and "creature (idle mobs).sql". I think this is good starting point to populate these 3 expansion.

[v9.zip](https://github.com/TrinityCore/TrinityCore/files/1498993/v9.zip)

**Comment by HannibalRoG** [comment]
Can anyone tell if this is valid?

**Comment by ArcaneFox** [comment]
There are still some multiple spawns (mainly Draenor & Legion). I used the sniffed creature_templates* to separate the moving and idling creatures.
(missing or wrong fields in the creature_template == wrong spawns)

* TrinityCore creature_template and Daniel25's creature_template

**Comment by Daniel25** [comment]
I guess that it wont be valid even if you work about it.So you can save it for your personal interest...

**Comment by Killyana** [comment]
If the spawns are cleaned they will pushed, keep on mind that cleaning existing spawns on the DB takes more time than re-spawning the whole stuff, it's the case for the DK starting area, raw spawns were pushed, and I started to clean the mess before November and still 50% of the work is not done.
