### ISSUE TITLE
DB/Text: Edwyn Van Cleef wrong Russian localization for broadcast_text

### ISSUE THREAD

**Issue by brotalnia** [TrinityCore/TrinityCore#20182]
**Description:**

Column `MaleText_loc8` for ID 6065 in table `locales_broadcast_text` has the wrong Russian localized text. The English version for this text is "The Brotherhood shall prevail!". This text has a matching sound with ID 5784. If you look in SoundEntries.dbc you will see that the name of the sound file is "EdwinVanCleefHealth03.wav". If you open "speech-ruRU.MPQ" from the Russian 3.3.5 client you'll hear that he says "Братство победит!".

**Current behaviour:**

The current translation is:
"Справедливость восторжествует!"

**Expected behaviour:**

It should be:
"Братство победит!"

**Branch(es):** 3.3.5

**TC rev. hash/commit:** cacde7b

**TDB version:**  335.63

**Comment by brotalnia** [comment]
Text for 6064 is also wrong.
It says:
"Глупцы! Правда на нашей стороне!".
In the sound file from 3.3.5 client he says:
"Глупцы! Мы боремся за правое дело!"

**Comment by offl** [comment]
Common blizzlike bug.
https://youtu.be/FAAtEBT0eqQ?t=764 Sound and text doesn't match.

**Comment by Killyana** [comment]
It's the case for french locales also, and probably DE and SP.
And we don't change wdb data.
