### ISSUE TITLE
[3.3.5] Double spawns in instances

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20183]
**Description:**

After some weeks i updated my core and after that i saw in a instance that it has some double spawns.

**Current behaviour:**

Those double spawns shouldnt be there.

**Expected behaviour:**

Only 1 mob should be on the same location not 2.

**Steps to reproduce the problem:**

1. update core to 76fc9ed6356ca34a603d4c716d2850b5b15a4164  (https://github.com/TrinityCore/TrinityCore/commit/76fc9ed6356ca34a603d4c716d2850b5b15a4164)

2) teleport for example to Azjol-Nerub ( .tele azjol )
3) go into instance.
4) the first boss fight, All 12 adds are double spawned.. the boss itself is NOT double spawned.
All trashmobs are also NOT double spawned, it seems only adds are affected.

![schermafbeelding 2017-08-22 om 07 23 00](https://user-images.githubusercontent.com/11842306/29563086-5c75133c-873c-11e7-8e96-fd834ab2b87a.png)

![schermafbeelding 2017-08-22 om 07 28 44](https://user-images.githubusercontent.com/11842306/29563094-633f96a6-873c-11e7-81e5-69d5e1240772.png)

maybe hard to see since they are dark.. but i think you get the idea.

**Branch(es):**

3.3.5 

**TC rev. hash/commit:** 

TrinityCore rev. 76fc9ed6356c 2017-08-20 22:23:32 -0300 (3.3.5 branch) (Unix, Release, Static)

**TDB version:** TDB 335.63

**Operating system:** Ubuntu 14.06

**Comment by Aokromes** [comment]
I vote it's every spawned by script the affected ones.

**Comment by Treeston** [comment]
Yeah I think these are script spawned. I'll take a look later.

**Comment by dikkedeur** [comment]
so it has nothing to do with the new dynamic spawn featured that is implemented in that time? since i didnt had it on my old core that was from june or something?

**Comment by Treeston** [comment]
Can't say for sure yet, but seems pretty likely.

**Comment by dikkedeur** [comment]
thanks for looking into it treeston

**Comment by Killyana** [comment]
Cannot reproduce on rev. 1f57d1ac67fb
Can you check guids of  a couple of npcs (double spawned)
If there's one of the 2 npcs with a DBguid!=0 it means you have wrong spawns on your DB.
If both spawns have DBguid=0 it means something is executed twice and generate a double spawn.

**Comment by dikkedeur** [comment]
went again into the instance..

they have BOTH dbguid=0

![schermafbeelding 2017-08-22 om 17 18 14](https://user-images.githubusercontent.com/11842306/29573003-12d762ee-875e-11e7-819d-6f35de599f1d.png)
![schermafbeelding 2017-08-22 om 17 18 54](https://user-images.githubusercontent.com/11842306/29573004-12f6d390-875e-11e7-8747-448258a57dac.png)

**Comment by Killyana** [comment]
Yes I was testing in the wrong server.

**Comment by irgc** [comment]
oh oh  yes :100: 

confirm

**Comment by dikkedeur** [comment]
@irgc maybe that is another thing.. dont know what is bugged, since bugged is rather meaningless thing.. better explain what is bugged when it comes to damage 👍
