### ISSUE TITLE
[335] - mail_items not deleted when expire (after return)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20194]
**Description:**

When mail with items is returned and expire_time ends, the mail is deleted, but mail_items and items in item_instance still in the DB
You can see all mail_items without mail in DB:

```sql
SELECT * FROM `mail_items` WHERE `mail_id` NOT IN (SELECT `id` FROM `mail`);
```

**Steps to reproduce the problem:**

1. Send a mail with items
2. Wait expire_time ends and mail is returned
3. Wait expire_time ends and mail is deleted
(you can update the expire_time and restart server for make faster the process)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Vincent-Michael** [comment]
try pls:

https://gist.github.com/Vincent-Michael/4edc5b3aa07c0b8eb670424d6dc8b371

**Comment by Jildor** [comment]
@Vincent-Michael  no!
Then items un ítem_instance still and...no is a good idea xD

**Comment by Jildor** [comment]
Tested and works fine @Vincent-Michael  👍

**Comment by qyh214** [comment]
Thanks!

**Comment by ccrs** [comment]
@Vincent-Michael time to commit :dancer:

**Comment by Jildor** [comment]
C'mon @Vincent-Michael  💃

**Comment by tkrokli** [comment]
Unless he uses private repositories, it looks like he doesn't have a repository to push from.
I am thinking maybe one of us could just create a PR and let V-M merge it if he wants to.
