### ISSUE TITLE
WorldServer Crashes on load.

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20191]
Description:

WorldServer crashes on load. I open the bnetserver and its ok.
My conf files are ok and the db is just created by the worldserver.exe

Error: 

In mysql_stmt_prepare() id: 35, sql: "SELECT ID, TextureFileDataID1, TextureFileDataID2, TextureFileDataID3, Flags, Race, Gender, GenType, Type, Color FROM char_sections ORDER BY ID DESC"
Unknown column 'Race' in 'field list'

Current behaviour:

WorldServer dont run

Expected behaviour:

worldserver must run

**Branch(es):**master

TC rev. hash/commit: TrinityCore rev. cdd76f3+ 2017-08-22 21:39:42 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: TDB 720.00

Operating system: Windows 10 Pro

**Comment by Aokromes** [comment]
Specific user issues don't belongs to tracker.

**Comment by buenodart** [comment]
Ill update my binaries... but what is means this dont belong to tracker?
Sorry, but im getting a lot of problems by compiling and creating the data base for trinity.
I follow the steps carefully but still having problems.
I have to fix this problem step by step, manually on my data base.. but now im having problemas with the worldserver loading... some quests, creatures... problems like that.

Ill recompile my exe! Thanks

**Comment by buenodart** [comment]
Hi! i have this problems now... what can I do?

File attached
[DBErrors.txt](https://github.com/TrinityCore/TrinityCore/files/1246941/DBErrors.txt)

**Comment by DJBoxer** [comment]
line 1-3 basically says your not using correct user and pass for mysql. so get that sorted. then redo your database. drop then import again as its a complete mess.

Also what Aokromes saying about tracker. is use forum instead as this is a user error.
