### ISSUE TITLE
Cant load WorldServer

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20190]
**Description:**

I follow each step for install my core and database and in the end i got an error: Some required *.db2 files (213 from 1) not found or not compatible.

Log attached!!
[Server.txt](https://github.com/TrinityCore/TrinityCore/files/1246776/Server.txt)

**Current behaviour:**

Some required *.db2 files (213 from 1) not found or not compatible

**Expected behaviour:**

Load, with no problem, the db2 files.

**Branch(es):**master

**TC rev. hash/commit:** TrinityCore rev. cdd76f31cb75+ 2017-08-22 21:39:42 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10 Pro

**Comment by Aokromes** [comment]
You have bad files, this don't belongs to tracker.
