### ISSUE TITLE
[3.3.5][CRASH] Crash in AuraScript::_PrepareScriptCall

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20199]
**Description:** This one happens more or less often

Crashlog: https://pastebin.com/NR1HGVJT

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/80a8867332461f4afd6f85fc41af689bc5e38466

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Vincent-Michael** [comment]
https://github.com/TrinityCore/TrinityCore/blob/a0a158b5b851db7e2c16819ec89e913d914a3aba/src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp#L230 e.g. here can null pointer
sry, i have no idea

**Comment by Raydor** [comment]
@Vincent-Michael It's not only that, there are other methods that call the crashing method, for example Aura::UpdateTargetMap:

https://pastebin.com/bDxuJe3v

@jackpoz Does anyone here at least have a workaround? :/

**Comment by irgc** [comment]
confirm

**Comment by Jildor** [comment]
Confirm: https://gist.github.com/Jildor/4c28582e73d045195e86771febce8a95

I think this crash happens after this commit (ed241a2fd6c8fd419d350210aa61eb1ad05b27bb) of @Treeston for @ccrs issue: https://github.com/TrinityCore/TrinityCore/issues/19996
but...not sure

**Comment by Treeston** [comment]
No idea why ed241a2 should cause it.

**Comment by Jildor** [comment]
I'm not sure, but in crahslogs appears:
```log
#4  AuraScript::_PrepareScriptCall (this=0x6de545225101, hookType=hookType@entry=AURA_SCRIPT_HOOK_CHECK_AREA_TARGET, aurApp=aurApp@entry=0x0) at /home/trinity/TrinityCore/src/server/game/Spells/SpellScript.cpp:956
No locals.
#5  0x000000000134d5e8 in Aura::CallScriptCheckAreaTargetHandlers (this=this@entry=0x6de57cfd82e0, target=0x6de59cda8000) at /home/trinity/TrinityCore/src/server/game/Spells/Auras/SpellAuras.cpp:2091
        hookItrEnd = <optimized out>
        hookItr = <optimized out>
        scritr = 
        result = true
```
```log
#0  AuraScript::_PrepareScriptCall (this=0xff32de0300, hookType=hookType@entry=AURA_SCRIPT_HOOK_EFFECT_UPDATE_PERIODIC, aurApp=aurApp@entry=0x0) at /home/sources/core/src/server/game/Spells/SpellScript.cpp:956
No locals.
#1  0x00000000014d024f in Aura::CallScriptEffectUpdatePeriodicHandlers (this=0x7fff38925320, aurEff=aurEff@entry=0x7fff38940640) at /home/sources/core/src/server/game/Spells/Auras/SpellAuras.cpp:2210
        effEndItr = <optimized out>
        effItr = <optimized out>
        scritr =
```

And...I don't know, I thought it might be related

I'm testing without this commit to see if crash again or not, don't hate me @Treeston 😄

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer after 26d, if this bug is still valid open a NEW ticket with updated core.
