### ISSUE TITLE
[3.3.5][CRASH] Crash due to jemalloc

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20198]
**Description:** Don't know how this happen but there is a crash in Unit::kill or WorldSession::SendPacket or whatever. 

Crashlog: https://pastebin.com/xSfdADtg

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/80a8867332461f4afd6f85fc41af689bc5e38466

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Jildor** [comment]
```
#27 0x00000000014a3254 in Spell::DoAllEffectOnTarget (this=0x7fff36823700, target=0x7fff3e49ded0) at /home/sources/core/src/server/game/Spells/Spell.cpp:2424
        damageInfo = {target = 0x7fff4a786000, attacker = 0x7fff4bb0e000, SpellID = 47610, damage = 16399, overkill = 0, schoolMask = 20, absorb = 0, resist = 0, physicalLog = false, unused = false, blocked = 0, HitInfo = 2, cleanDamage = 0, fullBlock = false}
        unit = 0x2
        hitMask = 2
```
ID - 47610 Frostfire Bolt (Rank 2)

I don't know if is related

**Comment by jackpoz** [comment]
crash in jemalloc, it would be nice to update jemalloc to a more recent version than the one we have

**Comment by Raydor** [comment]
@jackpoz Is jemalloc also related with malloc? https://pastebin.com/i4HemhKT, maybe you need to update both if they are different things.

**Comment by Raydor** [comment]
More crashes related to jemalloc, please someone try updating jemalloc, the last update to jemalloc was 3 years ago:

- https://pastebin.com/B8jy3X1R
- https://pastebin.com/zEVCcTPf

**Comment by Aokromes** [comment]
try to compile and run server server without jmalloc to see if crash changes.

**Comment by irgc** [comment]
confirm

**Comment by Aokromes** [comment]
confirm without a crashlog without jmalloc is useless.

**Comment by tkrokli** [comment]
@Raydor & @Jildor : see if you can test like Aokromes suggested in the comment above mine and post new feedback here (or fresh logs).

**Comment by Jildor** [comment]
I'm sorry, I don't have  that crash, I can't confirm 😄

**Comment by Aokromes** [comment]
Test after cc6dec7

**Comment by Faq** [comment]
one more update https://github.com/TrinityCore/TrinityCore/commit/92cd9bd70db460fdce4af0596cf9d8ee3c3abad5

**Comment by Aokromes** [comment]
If this bug is still valid open a new ticket with updated core AND without jmalloc.
