### ISSUE TITLE
How can I disable specific Specializations?

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20197]
**Description:**

Hi all.

Im having problems with some specializations and already create a issue for this...
It is possible to disable some specializations for specifics classes? Thanks for your help!

Oh... the Vengeance specialization for Demon Hunter is disabled... i want to do this with other specializations.

Branch(es): Master

TC rev. hash/commit: TrinityCore rev. a93a5ad+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: DAT 720.00

Operating system: Windows 10 Pro X64

**Comment by Aokromes** [comment]
this is not a forum.
