### ISSUE TITLE
[3.3.5] Positive Spells do not place you in combat

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#20196]
**Description:** Healing or Buffing a target who is in combat, does not put you in combat.

**Current behaviour:** ^

**Expected behaviour:** Positive spells cast on a friendly player who is in combat, should put yourself in combat as well.

**Steps to reproduce the problem:** Heal or buff a player in combat.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/203c5f705806f6f39a8392c3164ff04fc5415d58

**TDB version:**  62

**Operating system:** ubuntu 14.04

**Comment by Eliminationzx** [comment]
Can be related to https://github.com/TrinityCore/TrinityCore/pull/19930 ?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 54ec8c4389cf
