### ISSUE TITLE
Trainers not working.

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#20193]
**Description:**

Since npc_trainer converted to trainer_spell none of trainers are working. Anyone has a sql for new structure with trainer entries?

**Branch(es):**

TrinityCore rev. a93a5ad37963 2017-08-23 20:50:41 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

Database: TDB 720.00 up to date

**Operating system:** Windows 10 PRO x64

**Comment by buenodart** [comment]
Having the same problem! Trainers wont work.

**Comment by DoctorKraft** [comment]
If you are not patient, you can sniff data with [WoWPacketParser](https://github.com/TrinityCore/WowPacketParser) and set `true` for `trainer`, `gossip_menu`, `gossip_menu_option` for get SQL in config file

**Comment by maryus101** [comment]
I`m new to WowPacketParser and i need a little help. Where i can find .pkt or .bin files to put them into parser?

**Comment by IzFrost** [comment]
> I`m new to WowPacketParser and i need a little help. Where i can find .pkt or .bin files to put them into parser?

Start [here](https://community.trinitycore.org/topic/12264-trinity-cores-sniffer-for-wow-72524742/).

**Comment by ArcaneFox** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19929

**Comment by maryus101** [comment]
any news?

**Comment by chzingler** [comment]
also looking forward for an update

**Comment by madmax765** [comment]
me too lol

**Comment by Killyana** [comment]
I will close this issue as almost all trainers works properly now, if you find one that has a problem open a new issue.
