### ISSUE TITLE
Char Become Immortal when change specialization

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20195]
Description:

When you use the .levelup command in a character (not GM account) and get a specialization, the character become Immortal. For exemple: I tested with a priest (holy) and warlock (destruction). When i active the specialization the character doesn't get hits... just absorb or miss. When i change the specialization, become to works normal.

Current behaviour:

The character become immortal when active the specialization. Priest (holy), warlock (destruction), mage (fire).

Expected behaviour:

The character recieve damage

Steps to reproduce the problem:

1. Create a character with an non GM account. Priest (holy), warlock (destruction), mage (fire).
2. Log in with a GM account and .levelup 109. The char must reach the level 110.
3. Active the specialization Priest (holy), warlock (destruction), mage (fire).
4. Begin a battle and... you dont recieve damage.

Branch(es): Master

TC rev. hash/commit: TrinityCore rev. a93a5ad37963+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: DAT 720.00

Operating system: Windows 10 Pro X64

**Comment by DoctorKraft** [comment]
It's not a specialization issue, but a spell class issue. You have many spells on different classes with a large amout of absorb, for example [Cauterize](http://www.wowhead.com/spell=86949/cauterize) (EFFECT_0 : absorb damage 100000000). In this example you need script the spell with amount of absorb = -1 and check with the proc absorb when the player have 35% life you can trigger the spell in EFFECT_2

**Comment by buenodart** [comment]
DoctorKraft
I'm sorry for being newbie in this area, but i didn't find this spell on my scripts or any other spell that have this absorb effect.
=/

**Comment by Shauren** [comment]
Mages fixed in 5774e926d997ef870bf3f184d0f23396e283fe56

**Comment by buenodart** [comment]
Thanks!!!! My mage is now operating well!! Thanks team!! YOURE AWESOME!!

Now... remains the warlock and priest! =)

Thanks a LOT!!!
