### ISSUE TITLE
Worldserver loading

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20192]
Description:

WorldServer show some errors loading strings

Error:

log File attached

Current behaviour:

WorldServer run but show errors

Expected behaviour:

worldserver must run without errors
[DBErrors.txt](https://github.com/TrinityCore/TrinityCore/files/1247124/DBErrors.txt)

**Branch(es):**master

TC rev. hash/commit: TrinityCore rev. cdd76f3+ 2017-08-22 21:39:42 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: TDB 720.00

Operating system: Windows 10 Pro

**Comment by Aokromes** [comment]
#15829
