### ISSUE TITLE
Trainers wont work

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20208]
Description:

When I try to train mount, for example, the windows with the chat with the npc wont open.

Current behaviour:

When I try to train mount, for example, the windows with the chat with the npc wont open..

Expected behaviour:

When I try to train mount, for example, the windows must open.;

Steps to reproduce the problem:

1. Create a character
2. Get lvl 20
3. Try to train with the riding trainer
4. Wont work

Branch(es): master

TC rev. hash/commit: TrinityCore rev. a93a5ad37963+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: TDB 720.00

Operating system: Windows 10 Pro x64

**Comment by malcrom** [comment]
You should give name and entry, if possible, of the trainer.

**Comment by Shauren** [comment]
#20193

**Comment by buenodart** [comment]
Any trainner work =/

**Comment by buenodart** [comment]
Duplicate! Just saw! Thanks
