### ISSUE TITLE
Warlock Implosion spell causes Worldserver Crash

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20207]
**Description:**

When I use the spell Implosion in a creature the worldserver crashes.

Worldserver message before crash:

C:\TrinityCore\src\server\game\Spells\Spell.cpp:1219 in Spell::SelectImplicitAreaTargets ASSERTION FAILED:
  false && "Spell::SelectImplicitAreaTargets: received not implemented target reference type"

**Current behaviour:**

When I use the spell Implosion in a creature the worldserver crashes.

**Expected behaviour:**

When I use the spell Implosion, the worldserver can't crash;

**Steps to reproduce the problem:**

1. Create a Warlock  
2. Get lvl 110 (.levelup command)
3. Use Implosion spell in a creature
4. Server crashes

[Implosion Crashe.txt](https://github.com/TrinityCore/TrinityCore/files/1258229/Implosion.Crashe.txt)

**Branch(es):** master

TC rev. hash/commit: TrinityCore rev. a93a5ad37963+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** TDB 720.00

**Operating system:** Windows 10 Pro x64

**Comment by Aokromes** [comment]
#18558
