### ISSUE TITLE
[335] - Crash CharmInfo::IsReturning

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20200]
**Description:**

Quest: http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense
Spell ID - 37918 Arcano-pince
Spell ID - 37919 Arcano-dismantle

When use these spells on the controled npc or player causes crash

These spells have conditions, but...I think don't work

```sql
SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment                                              
-----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  -----------------------------------------------------
                     13            1        37918         0          0                        33                1                0                1                0                  1          0            0              Arcano_pince effect 0 cannot hit self                
                     13            1        37919         0          0                        33                1                0                1                0                  1          0            0              Arcano-Dismantle effect 0 cannot hit self            
                     13            2        37919         0          0                        33                1                0                1                0                  1          0            0              Arcano-Dismantle effect 1 cannot hit self            
                     13            1        37919         0          0                        31                0                3            21909                0                  0          0            0              Arcano-Dismantle effect 0 can hit only Arcano-Scorp  
                     13            2        37919         0          0                        31                0                3            21909                0                  0          0            0              Arcano-Dismantle effect 1 can hit only Arcano-Scorp  
                     13            1        37918         0          0                        31                0                3            21909                0                  0          0            0              Arcano_pince effect 0 can hit only Arcano-Scorp      
```

Crashlog: https://gist.github.com/Jildor/70850a2f99cdb30ca1088302e08c84eb

**Steps to reproduce the problem:**

1. add quest 10672
2. go to npc 21909 and use the gameobject to control the npc
3. select the player or npc controled and cast spell 37918 or 37919

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by jackpoz** [comment]
Thank you for the nice How To Reproduce steps

**Comment by irgc** [comment]
confirm

**Comment by sirikfoll** [comment]
This fixes the crash, please test and confirm if it works for you.

Possess its still a bit weird, the npc isn't fully under player control, it keeps returning to home position, but that's for another issue ^^
```sql
UPDATE `creature_template` SET `AIName`='' WHERE `entry`=21909;

**Comment by jackpoz** [comment]
the cpp code should be changed to properly fix the crash too in addition to the sql script

**Comment by lachtanek** [comment]
Better change imo would be to not be able to assign PetAI as AIName in DB, its not used anywhere and it will only cause problems since PetAI uses charminfo like everywhere

**Comment by tkrokli** [comment]
Wish I had posted about the quest issue when I first noticed it, but anyway: attempts to use the Scorpid vehicles in the quest mentioned by OP (http://www.wowhead.com/quest=10672/frankly-it-makes-no-sense) is quite difficult because of the current **Core/Movement: waypoint system issues** #20310 .

**Comment by offl** [comment]
>This fixes the crash, please test and confirm if it works for you.
>
>Possess its still a bit weird, the npc isn't fully under player control, it keeps returning to home position, but that's for another issue ^^
>```sql
>UPDATE `creature_template` SET `AIName`='' WHERE `entry`=21909;
>```
He likely tries to MoveRandom. Possible PetAI was added to disable his movement when charmed or to fix another issues.

**Comment by jackpoz** [comment]
everyone agrees to handle PetAI in the same way as https://github.com/TrinityCore/TrinityCore/commit/072c884ed86a9bf895cd5f53b0f6480ae14c3059 ?

**Comment by sirikfoll** [comment]
Yes, please.

**Comment by tkrokli** [comment]
Looks like a useful solution. I agree.

**Comment by Treeston** [comment]
+1, PetAI in DB should be invalid.

**Comment by Treeston** [comment]
(but move the check into a helper - `IsAINameValidInDB` or something)

**Comment by jackpoz** [comment]
Somebody please pushes this sql script update

> UPDATE `creature_template` SET `AIName`='' WHERE `entry`=21909;
