### ISSUE TITLE
[3.3.5] Breathing bar on land

### ISSUE THREAD

**Issue by Cyclone47** [TrinityCore/TrinityCore#20221]
**Description:**

Breathing bar appears on land. There is no water. 

Location:
Dragonblight (Ruby Dragonshrine)
3694.65 928.49 53.6 571

**Current behaviour:**

When walking in the small pit at Ruby Dragonshrine, a breathing bar shows up and your character starts drawning in the end. There is no water.
Screenshot: https://fdrop.in/zUdeqxA

**Expected behaviour:**

You should not lose breath and drawn on land.

**Steps to reproduce the problem:**

1. Type .go xyz 3694.65 928.49 53.6 571
2. Watch the breath bar appear
3. Walk a little up (breath bar disappears)
4. Walk back down
5. Watch the breath bar appear again

**Branch(es):**

3.3.5, branch

**TC rev. hash/commit:** 
4cf4961

**TDB version:**  TDB 335.63	63

**Operating system:** Server 2008 R2

**Comment by tkrokli** [comment]
Please note: your posted screenshot shows core rev. hash 44b57d23e734 and this revision is not a valid TrinityCore commit. This suggests you may have code that could change the default behaviour of the core and makes this issue less than reproducible (unsupported version). I have not tested this issue yet, but will give it a try when I get home after work (no internet at home for another week or 2, I think. I just moved to a new address).

By the way, have you checked that your coordinates are above ground on that spot? If you teleport to some coordinate where you are slightly under water, it could be a general issue with some characters having too low center of player character -- swimming while sitting on a mount makes the [ Breath ] bar appear even  if the character is 50% over water. Then again, it is also possible that the issue is related to vmaps or mmaps.

**Comment by ArcaneFox** [comment]
I don't know if this can help:

Creation of vmaps/mmaps: https://github.com/TrinityCore/TrinityCore/commit/f5ef48d188f95b22bf7f82234844d3fdb22cb108

The breathing bar only appears in a small area
![sc](https://user-images.githubusercontent.com/25306170/29918115-83fb81c0-8e44-11e7-8bcd-e55339c0cd94.jpg)

**Comment by tkrokli** [comment]
This is a very minor (and possibly cosmetic) issue compared to one of the tunnels near the Orange Crystal entrance to Maraudon, where you go to fill your vial for https://wow.gamepedia.com/Quest:Vyletongue_Corruption_(Horde) . When running lower than the orange pools, the game client shows the [ Breath ] bar for the whole section of a tunnel where you are lower than the orange pool. You have to run for at least 10 seconds to get out of the [ Breath ] bar area.

(TBH, I thought the Maraudon issue was posted here in the TC issue tracker, but I can't seem to find it now.)

**Comment by Aokromes** [comment]
cannot reproduce on head.

**Comment by Shauren** [comment]
Not fixed

**Comment by Rushor** [comment]
this also happens in barrens if i remember correctly

**Comment by Harrith** [comment]
After further investigation, I found out that the problem is with MAP_LIQUID_NO_HEIGHT in MapExtractor.

For example, in Dragonblight there is a tile without water (coords [0,0]), so for this tile liquid height is correctly set to CONF_use_minHeight, but it is not taken into account in minHeight, so the height for this tile is not extracted and other tools (vmap extractor/assembler) work with liquidLevel.

A quick fix could be by disabling this flag, or by removing condition if (liquid_show[y][x]) in min/maxHeight loop, but this option was not tested yet.

**Comment by Rushor** [comment]
could you show us a proposal fix for that @Harrith ?

**Comment by Harrith** [comment]
Yes of course, but first let me show the results in recast:
Before:
![43915426-f3d85d22-9c0a-11e8-981f-20b8675e5283](https://user-images.githubusercontent.com/40215976/77858296-e2df2f80-7202-11ea-9cad-b3d26ecea981.png)
![43915390-dead58da-9c0a-11e8-997e-7a3f7d1763ed](https://user-images.githubusercontent.com/40215976/77858297-e2df2f80-7202-11ea-8d25-e8245b67dd90.png)

After:
![after1](https://user-images.githubusercontent.com/40215976/77858346-3e112200-7203-11ea-8c02-2a6ba798cdb8.png)
![after2](https://user-images.githubusercontent.com/40215976/77858349-42d5d600-7203-11ea-907e-77119abcc302.png)

The first 2 pictures are from my older report https://github.com/TrinityCore/TrinityCore/issues/22020#issuecomment-411837843.

And now about the changes. I tried to preserve MAP_LIQUID_NO_HEIGHT flag, so I did this:
I added a new variable called forceLiquidHeight which indicates whether there is a tile in chunk without liquid data. If there is tile like that then MAP_LIQUID_NO_HEIGHT is not used. to correctly set liquid data for this tile.

I am not sure if the optimization preserves but I tried to keep it.

from System.cpp (MapExtractor)
`
        bool forceLiquidHeight = false; 

        for (int32 y = 0; y < ADT_GRID_RESOLUTION; ++y)
        {
            for (int32 x = 0; x < ADT_GRID_RESOLUTION; ++x)
            {
                if (liquid_show[y][x])
                {
                    if (minX > x) minX = x;
                    if (maxX < x) maxX = x;
                    if (minY > y) minY = y;
                    if (maxY < y) maxY = y;
                    float h = liquid_height[y][x];
                    if (maxHeight < h) maxHeight = h;
                    if (minHeight > h) minHeight = h;
                }
                else
                {
                    liquid_height.array[y][x] = CONF_use_minHeight;
                    forceLiquidHeight = true;
                }
            }
        }
. . .

        if (!forceLiquidHeight && maxHeight == minHeight)
            liquidHeader.flags |= MAP_LIQUID_NO_HEIGHT;
`

**Comment by Faq** [comment]
Could you make a diff or better PR? And don't forget to add comments in code with `//`

**Comment by jackpoz** [comment]
@Harrith got time to open the PR ?

**Comment by jackpoz** [comment]
Tried this change in Thunderbluff, still same issue:
![image](https://user-images.githubusercontent.com/1153754/89718198-7d275f00-d9bd-11ea-8c1a-0534f5064713.png)

**Comment by jackpoz** [comment]
diff I tested:
```diff
 src/tools/map_extractor/System.cpp | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/tools/map_extractor/System.cpp b/src/tools/map_extractor/System.cpp
index 3698caead7..47d0762cd5 100644
--- a/src/tools/map_extractor/System.cpp
+++ b/src/tools/map_extractor/System.cpp
@@ -766,6 +766,7 @@ bool ConvertADT(std::string const& inputPath, std::string const& outputPath, int
         int maxX = 0, maxY = 0;
         maxHeight = -20000;
         minHeight = 20000;
+        bool forceLiquidHeight = false;
         for (int y=0; y<ADT_GRID_SIZE; y++)
         {
             for(int x=0; x<ADT_GRID_SIZE; x++)
@@ -781,7 +782,10 @@ bool ConvertADT(std::string const& inputPath, std::string const& outputPath, int
                     if (minHeight > h) minHeight = h;
                 }
                 else
+                {
                     liquid_height[y][x] = CONF_use_minHeight;
+                    forceLiquidHeight = true;
+                }
             }
         }
         map.liquidMapOffset = map.heightMapOffset + map.heightMapSize;
@@ -795,7 +799,7 @@ bool ConvertADT(std::string const& inputPath, std::string const& outputPath, int
         liquidHeader.height  = maxY - minY + 1 + 1;
         liquidHeader.liquidLevel = minHeight;
 
-        if (maxHeight == minHeight)
+        if (!forceLiquidHeight && maxHeight == minHeight)
             liquidHeader.flags |= MAP_LIQUID_NO_HEIGHT;
 
         // Not need store if flat surface

```

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/26324 most likely fixed this. Test it and ask to reopen the issue if that's not the case
