### ISSUE TITLE
[3.3.5] Quest Escape from the Winterfin Caverns

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20226]
**Description:**

Escape from the Winterfin Caverns, when you escort Lurgglbr at the end of the escort it doesnt give credit for completing quest.

**Current behaviour:**

When you accept quest and escord Lurgglbr to the end, it despanws and doesnt give credit.

**Expected behaviour:**

He should give credit BEFORE he despawns

**Steps to reproduce the problem:**

1. take quest.
2) escord the little bastard.
3) at the end wait.. and wait he despawns but doesnt give credit.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4ee16fb53617 2017-08-22 21:24:22 +0200 (3.3.5 branch) (Unix, 

**TDB version:**  TDB 335.63

**Operating system:** ubuntu 14.06 lts

**Comment by Aokromes** [comment]
cc89428
