### ISSUE TITLE
[3.3.5] Stop the Ascension (11260)

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20227]
**Description:**

the quest Stop the Ascension (11260) is bugged.

**Current behaviour:**

using the quest item summons the npc, but after the first line the script stops and npc cannot be attacked.

**Expected behaviour:**

Script should go on and npc should be attackable so you can kill it and complete quest.

**Steps to reproduce the problem:**

1. get quest from scroll ( Vrykul Scroll of Ascension )
2) accept quest and go over to the tyne pyre and use the item.
3) npc halfdan will be spawned..
4) he says first line of text
5) everything stops.. he doesnt work.. is not attackable.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4ee16fb53617 2017-08-22 21:24:22 +0200 (3.3.5 branch) (Unix, Release, Static)

**TDB version:**  TDB 335.63

**Operating system:** ubuntu server 14.06 lts

**Comment by Killyana** [comment]
Related to the event "ON TEXT Over" not triggering

Halfdan the Ice-Hearted - ON Just Summoned - Talk 0
Halfdan the Ice-Hearted - ON TEXT 0 Over - Talk 1
Halfdan the Ice-Hearted - ON TEXT 1 Over - REMOVE Unitflag IMMUNE_TO_PC
Halfdan the Ice-Hearted - ON TEXT 1 Over - Attack INVOKER

**Comment by TecDian** [comment]
Tested on 951fa46fe9b1. Everything worked just fine. Seems the bug has mysteriously vanished. If someone could confirm this, the issue could be closed.

**Comment by Killyana** [comment]
Fixed by: https://github.com/TrinityCore/TrinityCore/issues/20680
