### ISSUE TITLE
Pandaria Starter Quests TDB720.00

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20220]
Description:

Can't see the starter quests npc in Wandering Isle.

Current behaviour:

Can't see the starter quests npc in Wandering Isle.

Expected behaviour:

Must see the starter quests npc in Wandering Isle

Steps to reproduce the problem:

1 - Create Pandaren Race
2 - Try to get the starter quests
3 - Dont see the npc starter quests

Branch(es): master

TC rev. hash/commit: TrinityCore rev. a93a5ad+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: TDB 720.00

Operating system: Windows 10 Pro x64

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/17021

**Comment by buenodart** [comment]
This solution wont worked for me.
I cant upgrade the DB because some fields dont have the same name of my sql fields.

For exemple... i have problem with this line

UPDATE `gameobject_template` SET `faction`=114, `VerifiedBuild`=20886 WHERE `entry` IN (209970, 209972);

my table dont have the field faction ...

some other problems i found in this solution... or maybe its a problem in my db.

Thanks

**Comment by Aokromes** [comment]
It means it's duplicated ticket.

**Comment by buenodart** [comment]
I have problem with this line too

UPDATE `creature_template` SET `exp`=4, `faction`=2395,

(this line its big to paste here)

and i get this error: /* Erro SQL (1054): Unknown column 'exp' in 'field list' */

**Comment by buenodart** [comment]
I have problem with this line too

UPDATE `creature_template` SET `exp`=4, `faction`=2395,

(this line its big to paste here)

and i get this error: /* Erro SQL (1054): Unknown column 'exp' in 'field list' */
