### ISSUE TITLE
[3.3.5] Killing the leader of a formation breaks the members

### ISSUE THREAD

**Issue by spectrez** [TrinityCore/TrinityCore#20228]
Description:

Killing the leader of a formation will cause its members unable to advance towards the victim.
i believe not having to worry about this bug would open up fixing split pulling in alot of dungeons.

Current behaviour:

-Aggro group with formation
-kill the leader before its members
-wait until members reach you
-step back abit.
-mobs will now be stuck looking at you/casting at you until they die or evade.

Expected behaviour:

-Aggro group with formation
-kill the leader before its members
-Members will continue to fight you without their leader.

Steps to reproduce the problem:

.go c 14772
Aggro the formation with the forsaken courier
kill the forsaken courier
step back and watch her guards stare you to death.

Branch(es):

3.3.5

TC rev. hash/commit: 80a8867

TDB version: TDB 335.63

Operating system: Windows

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/17563
