### ISSUE TITLE
Grand Thief Palomino Quest Doesnt Work

### ISSUE THREAD

**Issue by buenodart** [TrinityCore/TrinityCore#20223]
Description:

Grand Thief Palomino Quest Doesnt Work.

Current behaviour:

I get the quest, stole a horse and when I leave que stable I get automatically dismount and the quest wont finish.

Expected behaviour:

The quest must work. Must stole the horse and bring to the questgiver.

Steps to reproduce the problem:

1. Create a DK
2. Complete the inicial quests
3. Go to Death's Breach
4. Get the quest "Grand Thief Palomino"
5. Go to Havenshrire Stables and stole a horse
6. Try to leave the stable
7. You get unmount automatically.

Branch(es): master

TC rev. hash/commit: TrinityCore rev. a93a5ad+ 2017-08-23 20:50:41 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: TDB 720.00

Operating system: Windows 10 Pro x64

**Comment by Aokromes** [comment]
#16021
