### ISSUE TITLE
[3.3.5] Halls of Reflection: Skybreaker final poss.

### ISSUE THREAD

**Issue by GMKyle** [TrinityCore/TrinityCore#20229]
**Description:**

Halls of Reflection Skybreaker final poss is to far form stairs

**Current behaviour:**

Halls of Reflection's Skybreaker final poss is to far form stairs
![snapshot5](https://user-images.githubusercontent.com/25353073/29929202-e08a4f18-8e38-11e7-965c-3640716b9c2c.png)

**Expected behaviour:**

Halls of Reflection's Skybreaker final poss most be near stairs

**Steps to reproduce the problem:**

1. Finish The Escape of The Lich King event in Halls of Reflection.
2. Try to board Skybreaker

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 
7a62c71a46d9b8d233f3741986255a5cab33ebfd

**TDB version:**  

**Operating system:** 
Debian 8 64bits

**Comment by Killyana** [comment]
Cannot reproduce in rev. 54ec8c4389cf
