### ISSUE TITLE
NPCs using Smart_Scripts wont move while silenced

### ISSUE THREAD

**Issue by spectrez** [TrinityCore/TrinityCore#20222]
**Description:**

Currently silencing a caster that uses SAI will not force it to move towards the victim.

**Current behaviour:**

- Aggro caster
- Caster starts casting
- Player silences caster
- Caster stays at his current location while silenced
- Caster continues casting when silence flag falls off.

**Expected behaviour:**

- Aggro caster
- Caster starts casting
- Player silences caster
- Caster moves towards current Victim
- Caster continues casting when silence flag falls off.

**Steps to reproduce the problem:**

`.go c 67368`
Aggro Sunfury Magister
When she casts fireball use `.cast 18278` from a distance

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 80a886733246

**TDB version:**  TDB 335.63

**Operating system:** Windows

**Comment by nawuko** [comment]
This has more todo with old converted scripts from EventAI than SmartAI itself. The script uses tons of "ACTION_ALLOW_COMBAT_MOVEMENT" calls which is a hacky way to control "caster" movement. Scripts like those can either be fixed by adding some events to handle interrupts or a rewrite (which I would recommend).

**Comment by Killyana** [comment]
Here a clean version using CMC:
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=18855 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(18855, 0, 0, 0, 0, 0, 100, 0, 500, 500, 3000, 3000, 11, 9053, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Sunfury Magister - On Aggro - Cast 'Fireball' (No Repeat)"),
(18855, 0, 1, 0, 0, 0, 100, 0, 8000, 12000, 26000, 31000, 11, 35778, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Sunfury Magister - In Combat - Cast 'Bloodcrystal Surge' (Phase 1) (No Repeat)"),
(18855, 0, 2, 0, 2, 0, 100, 513, 0, 15, 0, 0, 25, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Sunfury Magister - Between 0-15% Health - Set Event Phase 3 (No Repeat)"),
(18855, 0, 3, 0, 1, 0, 50, 0, 10000, 20000, 15000, 30000, 11, 34397, 0, 0, 0, 0, 0, 19, 19421, 30, 0, 0, 0, 0, 0, "Sunfury Magister - Ooc - Cast Red Beam");
```
Still if the npc is silence it must moves towards its current target, this must be implemented on cast flags:  SMARTCAST_COMBAT_MOVE | 64

**Comment by nawuko** [comment]
Oh sorry, i totally forgot that TC has not implemented correct behavior on spell interrupts when SMARTCAST_COMBAT_MOVE is used. This made my comment somewhat invalid.

**Comment by spectrez** [comment]
ive been messing around with this for a while now - and ive tried this:
```
diff --git a/src/server/game/AI/SmartScripts/SmartScript.cpp b/src/server/game/AI/SmartScripts/SmartScript.cpp
index da129242cc..87b4138360 100644
--- a/src/server/game/AI/SmartScripts/SmartScript.cpp
+++ b/src/server/game/AI/SmartScripts/SmartScript.cpp
@@ -550,7 +550,8 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                             if (me->GetDistance(target) > spellInfo->GetMaxRange(true) ||
                                 me->GetDistance(target) < spellInfo->GetMinRange(true) ||
                                 !me->IsWithinLOSInMap(target) ||
-                                mana < spellInfo->CalcPowerCost(me, spellInfo->GetSchoolMask()))
+                               mana < spellInfo->CalcPowerCost(me, spellInfo->GetSchoolMask()) || 
+				 me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED))
                                 allowMove = true;
 
                             ENSURE_AI(SmartAI, me->AI())->SetCombatMove(allowMove);
```
it seems to work just fine (for mobs using flag 64) - but i dont have the knowledge or experience to tell what kind of implications this could have.

**Comment by offl** [comment]
Another solution: https://github.com/TrinityCore/TrinityCore/issues/12908#issuecomment-53144782
