### ISSUE TITLE
[3.3.5] Spell/Druid: Form can be removed when feared

### ISSUE THREAD

**Issue by Dalgurakk** [TrinityCore/TrinityCore#20230]
**Description:**
Druid is under the effects of fear must lose control of the character however can remove the form of tree and cancel the banish spell.

**Current behaviour:**
Druids can remove form when feared.

**Expected behaviour:** 
Druids should not remove form when feared.

**Steps to reproduce the problem:**

1. Warlock cast fear to druid (tree form)
2. Warlock cast banish to druid (tree form)
3. Druid feared remove tree form and the warlock cast is cancelled.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7a62c71

**TDB version:**  63 + updates

**Operating system:** Windows

**Comment by alexandre433** [comment]
Tested, the 
> cancel the banish spell
Is not true, but the part of can remove form while feared is true, I suppose that It happened on Blizzard aswell, if it's a bug or not I remember on Wotlk that it was possible.

**Comment by Aokromes** [comment]
![image](https://user-images.githubusercontent.com/539374/29960818-8084c6e6-8efd-11e7-9be6-f01f8a01e7b8.png)

**Comment by Dalgurakk** [comment]
@alexandre433 you're right, that's what i meant.

**Comment by aletuna** [comment]
Pretty sure you can/could cancel druid forms while being feared/stunned. I have no source to prove that though.

**Comment by Keader** [comment]
what he say is: you cant make a "combo" using fear and banish because he can avoid banish removing treeform while feared...
But if i remember right, i can remove my form while feared on retail

**Comment by aletuna** [comment]
That's what I meant. I'm pretty sure it's normal behavior that you can prevent getting "combo'd" by removing your form before the banish goes off.

**Comment by Keader** [comment]
@Dalgurakk have you any prof?

**Comment by Noryad** [comment]
@Keader 
http://wowwiki.wikia.com/wiki/Druid_tactics
Shifting out of a form is not a spell, nor an action, and can be done anytime (except when you are under some kind of mind control). It can be done while stunned, feared, etc but it does not break the effect. It can even be done while skinning/mining/gathering (e.g. to prepare for a heal). Shifting in to a form is an action however and cannot be done while stunned, feared, etc. 
That works fine. Tested on f86b4e4, is not a bug.
