### ISSUE TITLE
MoveCirclePath always skips first movepoint

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20238]
**Description:**
MoveCirclePath generates correct movepoint list, but the first movepoint id is always skipped and current creature position before MoveCirclePath is used instead of it.

in ``int32 MoveSplineInit::Launch()`` first movepoint is overwritten by ``args.path[0] = real_position;``

**Current behaviour:**
Lets say we want a NPC to move like this, starting from some start(spawn) position and then moving in circle:
![image](https://user-images.githubusercontent.com/32191/30004178-b340e816-90ca-11e7-8d80-185934607a58.png)

MoveCirclePath generates path list that corresponds our needs, which looks like this:
![image](https://user-images.githubusercontent.com/32191/30004199-229c71f8-90cb-11e7-8c0c-c94c6f619fa9.png)

But our NPC is moving always this way, skipping first generated point id and using its spawn position instead:
![image](https://user-images.githubusercontent.com/32191/30004233-c241dbe4-90cb-11e7-9a77-ba91e76b4690.png)

**Expected behaviour:**
Use first movepoint generated by MoveCirclePath

**Steps to reproduce the problem:**

1. change ``npc_quel_delar_sword`` script from ``_events.ScheduleEvent(EVENT_QUEL_DELAR_LAND, 15000);`` to ``_events.ScheduleEvent(EVENT_QUEL_DELAR_LAND, 150000);`` for example
2. .gm on
3. .go xyz 5309 2006 712 668
4. .npc add temp 37158
5. watch as it skips first movepoint

**Branch(es):** both

**TC rev. hash/commit:** 2d0e65386693c35ae8f00fc0a1beee032a5ccf18

**TDB version:**  720.00

**Operating system:** Win 7 x64

**Comment by jackpoz** [comment]
what if the first waypoint is set to the spawn position as index 0 waypoint ?

**Comment by Lopfest** [comment]
it is (not spawn position but current position to be precise). by first movepoint I mean index 0
MoveCirclePath generates lets say 8 waypoints, numbered by indexes 0-7.
index 0 is always overwritten by current creature position.

**Comment by ccrs** [comment]
@keader this is the explanation for Razorscale's issue

**Comment by matukaa** [comment]
Not sure if needed, but can confirm :)

**Comment by Keader** [comment]
true ccrs

**Comment by Lopfest** [comment]
also option to set walk/run would be cool. now there is only walk.

**Comment by Langerz82** [comment]
Test please. I'm not sure how to activate the quest and get to the halls of reflection. ^_^

```diff
diff --git src/server/game/Movement/Spline/MoveSplineInit.cpp src/server/game/Movement/Spline/MoveSplineInit.cpp
index 02b31cfa19..af17566768 100644
--- src/server/game/Movement/Spline/MoveSplineInit.cpp
+++ src/server/game/Movement/Spline/MoveSplineInit.cpp
@@ -87,7 +87,10 @@ namespace Movement
             return 0;
 
         // corrent first vertex
-        args.path[0] = real_position;
+        //args.path[0] = real_position;
+        const G3D::Vector3 v3realPos(real_position.x, real_position.y, real_position.z);
+        args.path.insert(args.path.begin(), v3realPos);
+
         args.initialOrientation = real_position.orientation;
         move_spline.onTransport = transport;
 
```

**Comment by Lopfest** [comment]
@Langerz82 now its not doing this
![image](https://user-images.githubusercontent.com/32191/35722550-1383f97c-07f7-11e8-886b-fa7133cdc34a.png)
but this
![image](https://user-images.githubusercontent.com/32191/35722620-4fd459b2-07f7-11e8-9bd5-f999f643b88b.png)

for testing just go to halls of reflection and manually spawn npc (.npc add temp 37158) in the middle of frostmourne altar near first boss encounter.

**Comment by Langerz82** [comment]
@Lopfest whats the go command coordinates?

**Comment by Lopfest** [comment]
.go xyz 5309 2006 712 668

**Comment by Langerz82** [comment]
@Lopfest  it just spins around really damn fast and doesnt move around a circular path, is my code broken?lol

**Comment by Lopfest** [comment]
probably yes :stuck_out_tongue:
try with clean TC code first to see what it should do +-

**Comment by Langerz82** [comment]
It's not moving in a circular path even with a clean build. Apply this patch and see if it works.

See:
https://gist.github.com/Langerz82/96b8c0643f668f92e15c498e01b629e7

**Comment by Lopfest** [comment]
no it doesnt work. it works like this, even when stepCount = 8
![image](https://user-images.githubusercontent.com/32191/35776267-715c689c-0999-11e8-954b-2b13274496f5.png)
p.s.: test on master :stuck_out_tongue:

**Comment by Lopfest** [comment]
no doesnt work. with moveFromStart = true and stepCount = 8 it moves like this:
![image](https://user-images.githubusercontent.com/32191/35776354-0e0fb666-099b-11e8-9279-7ae92b9f2886.png)
ps: test on master :stuck_out_tongue:

**Comment by Shauren** [comment]
This is intended. Creature is meant to be positioned on one of circles points when calling MoveCirclePath, not in its center which is why your SAI action fails

**Comment by Langerz82** [comment]
Well that would make it hellava lot easier, just the script will need a minor change which I will do in about an hour.

**Comment by Langerz82** [comment]
I'm getting "patch does not apply" errors for your SAI script. What command should I be using to apply the patch?

**Comment by Lopfest** [comment]
None. Apply it manually - copy paste. Master and 335 branch are not equal.

**Comment by Ovahlord** [comment]
> This is intended. Creature is meant to be positioned on one of circles points when calling MoveCirclePath, not in its center which is why your SAI action fails

Not in all cases. There are indeed some cases that use the enter_cycle flag. Seen on sniffs as well. Check this one here: https://github.com/TrinityCore/TrinityCore/issues/21387

**Comment by Ovahlord** [comment]
If someone is still on this issue please test this here: https://paste2.org/mh87NWjY
This should fix pretty much everything related to cyclic movement.

**Comment by Lopfest** [comment]
@Ovahlord i didn't test it (yet), but this creature is not flying: https://pastebin.com/BS8dqbFr

**Comment by Ovahlord** [comment]
Are you sure that this is a clean circle path? Some creatures walk cyclic but not within a perfect cycle

**Comment by Lopfest** [comment]
is this perfect circle? :smile:
distance from the middle to every "corner" is 6y with accuracy to 3 decimal places.

![image](https://user-images.githubusercontent.com/32191/36160296-1b19fd60-10e1-11e8-8414-d03cc1787e12.png)

**Comment by Ovahlord** [comment]
This is intresting.
So the update_obdate object packet does not send the enter_cycle flag anymore when the first vertex has been passed already and so the first element of the path is also not getting sent. This indeed confirms the theory that the first vertex gets deleted from the path when it has been passed, not on the next cycle. I can fix this. Give me some time please. I am currently reworking the fix and trying to use the new opcode better

**Comment by Langerz82** [comment]
May be related issue:
https://github.com/TrinityCore/TrinityCore/issues/22775
