### ISSUE TITLE
Core/Quest: Inoculation (9303) condition error

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#20249]
**Description:**

The quest Inoculation in the starting zone of Draenei has an error in condition table.

**Current behaviour:**

Quest can not complete because CONDITION_SOURCE_TYPE_SPELL its not used by spell 29528 "Inoculate Nestlewood Owlkin"

**Expected behaviour:**

Complete quest when cast spell "Inoculate Nestlewood Owlkin"

**Steps to reproduce the problem:**

1. Create Draenei
2. Add quest 9303

**Branch(es):**

Master

**TC rev. hash/commit:** 

30ff2620c2e8dc489b12c71e61f0b6f4173e8c0d

**TDB version:**  7.2.0+updates

**Operating system:** CHANGEME OS

Fix proposed:

```
`UPDATE` `conditions` SET `SourceTypeOrReferenceId`='13', `SourceGroup`='1', `SourceEntry`='29528', `SourceId`='0', `ElseGroup`='0', `ConditionTypeOrReference`='31', `ConditionTarget`='0', `ConditionValue1`='3', `ConditionValue2`='16518', `ConditionValue3`='0', `NegativeCondition`='0', `ErrorType`='0', `ErrorTextId`='0', `ScriptName`='', `Comment`=NULL WHERE (`SourceTypeOrReferenceId`='13') AND (`SourceGroup`='1') AND (`SourceEntry`='29528') AND (`SourceId`='0') AND (`ElseGroup`='0') AND (`ConditionTypeOrReference`='31') AND (`ConditionTarget`='0') AND (`ConditionValue1`='3') AND (`ConditionValue2`='16518') AND (`ConditionValue3`='0');

**Comment by Exodius** [comment]
Breaking down your suggested fix:
```sql
`UPDATE` `conditions` SET `SourceTypeOrReferenceId`='13',      `SourceGroup`='1',      `SourceEntry`='29528',      `SourceId`='0',      `ElseGroup`='0',      `ConditionTypeOrReference`='31',      `ConditionTarget`='0',      `ConditionValue1`='3',      `ConditionValue2`='16518',      `ConditionValue3`='0', `NegativeCondition`='0', `ErrorType`='0', `ErrorTextId`='0', `ScriptName`='', `Comment`=NULL
                   WHERE (`SourceTypeOrReferenceId`='13') AND (`SourceGroup`='1') AND (`SourceEntry`='29528') AND (`SourceId`='0') AND (`ElseGroup`='0') AND (`ConditionTypeOrReference`='31') AND (`ConditionTarget`='0') AND (`ConditionValue1`='3') AND (`ConditionValue2`='16518') AND (`ConditionValue3`='0');
```
you basically updated only
```
`NegativeCondition`='0', `ErrorType`='0', `ErrorTextId`='0', `ScriptName`='', `Comment`=NULL

**Comment by Killyana** [comment]
The spell and the condition is the same as 4.3.4 and 3.3.5, if some else can test the quest on master and tell us if there's an issue or not, and what kind of error is displayed when you use the item.

**Comment by nubqt** [comment]
Confirmed.

master branch 7334419
TDB 720.00_2017_04_18

error is: 'You can't do that yet.' when you click the 'Innoculating Crystal' while targeting a 'Nestlewood Owlkin.'

<img width="1378" alt="screen shot 2017-11-13 at 12 39 49 am" src="https://user-images.githubusercontent.com/33535711/32711179-a556770c-c80b-11e7-8665-f3988df0e9ff.png">

**Comment by tkrokli** [comment]
Did you try any of the suggested changes to the `conditions` table above?

**Comment by nubqt** [comment]
Nope. I will put it on my to-do list.

**Comment by Killyana** [comment]
This must be fixed on core side.

**Comment by Killyana** [comment]
Someone cast test after: https://github.com/TrinityCore/TrinityCore/commit/b7797607e0ba9c343b6a58b18627ba53ef2f2c84  ?

**Comment by Aokromes** [comment]
No answer after 2 months if this bug if still valid open a new ticket with one updated core.
