### ISSUE TITLE
[3.3.5] Subcommands are not shown to players (sec player of rbac) when typing the name of the parent command

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20242]
**Description:** If you assign a command that has subcommands to sec player of rbac and then the player type the parent command, no subcommands are shown to the player, he just instead sends the message to the chat like if the command didn't exist. I don't know when this stopped working but this was working correctly some time ago.
Alternatively, you can type .help command and see how subcommands are shown so the bug is only with the parent command without the .help. _**This only happens to players, GMs and above have this working correctly.**_

**Current behaviour:** When typing the name of a command that have subcommands on a player rank account, subcommands are not shown.

**Expected behaviour:** Subcommands should show to the player as always were when typing the parent command and hitting enter.

**Steps to reproduce the problem:**
_I think this can also be done with the default .account command assigned to player but im not sure cause that command works a little bit different so I prefer to add another command for this steps._
1.  Assign a command that has subcommands to a player rank, for example add in rbac_linked_permissions the linkedId 291 to 299 (cheat commands) to the id 199 (player commands)
2. Restart RBAC tables
3. Type .cheat with the player and see how no subcommands are shown but if you type .commands the cheat command is there and also you can use .help cheat and subcommands will be shown.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/c7d565739b2e4a1fbcd6bd61164510257e7ee90b

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Raydor** [comment]
@Shauren Can this issue be related to https://github.com/TrinityCore/TrinityCore/commit/c92faf627712d26a7abdce2db62ffb8b938a4522? I'm unable to revert that commit cause it's too old and a lot has changed since then.

**Comment by Raydor** [comment]
Okay I found the cause of this error.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Chat/Chat.cpp#L294 Players don't have this permission by default, it is added to Moderators (the next rank after player).
The fix is as simple as assigning permission 33 to player security level and removing it from the Moderator level.

**Comment by Keader** [comment]
PR it :)

**Comment by Raydor** [comment]
That doesn't matter tbh, they have a few but none of them have subcommands, they still should be able to see subcommands when typing a command, don't know if that is blizzlike or not but due to it not being too important if blizzlike or not it should be available to players so servers that want to give other commands to players won't have the issue I reported.

**Comment by joschiwald** [comment]
You have to assign the parent command to player commands too. Anyway it is a misconfigurated rbac issue. Closing.

**Comment by Raydor** [comment]
Obviously I assigned the parent command to player commands, did you test it yourself before closing?

**Comment by Shauren** [comment]
But players are not supposed to be notified if they fail command execution by default (this is blizzlike and intended)
Which means that you missing that permission on players (because you want to allow player commands) is a configuration issue, not a core bug
