### ISSUE TITLE
Naxxramas Mob Patchwerk cause crash

### ISSUE THREAD

**Issue by MaDmaX1337** [TrinityCore/TrinityCore#20247]
**Description:**

In Naxxramas if you attack the Mob ID 16028 Patchwerk my trinitycore is crashing.

**Current behaviour:**

In attack of Mob ID 16028 Server crashes

**Expected behaviour:**

Maybe server Shouldnt Crash?!

**Steps to reproduce the problem:**

1. 

**Branch(es):**

3.3.5, normal stable

**TC rev. hash/commit:** 

Rev 6621d8fd7bb2

**TDB version:**  The newest i updated the World Database all 1 Week ago i used from the zip file

**Operating system:** Windows Server

**Comment by Keader** [comment]
Try reproduce it with Debug Mode and post crash log here please.

**Comment by MaDmaX1337** [comment]
sorry im a bit new, so i have to recompile the core in debug mode right? and which log, server.log or DBerror.log?

**Comment by Keader** [comment]
when server crash will appear a new folder called Crashes

**Comment by MaDmaX1337** [comment]
I Uploaded Crash txt file and dmp file...

[crashes.zip](https://github.com/TrinityCore/TrinityCore/files/1278353/crashes.zip)

**Comment by Keader** [comment]
clean your crash folder before reproduce it, because this crashlog is not in debug mode.

**Comment by MaDmaX1337** [comment]
Sorry i cant do that, i recompiled the core to Debug and now i dont have the DLL files so i cant start in debug mode.

**Comment by Eliminationzx** [comment]
@MaDmaX1337 , you can find dll files in folder calls 'debug'.

**Comment by MaDmaX1337** [comment]
Nope i cant find it, when i compile ALL then only the .exe files are there... Where can i get those DLLs?

**Comment by MaDmaX1337** [comment]
I tested now debug run on my computer there its working with the dame dll weird...

But now the Log i hope it is the crash...

[6621d8fd7bb2+_worldserverdebug.exe_[6-9_15-53-28].txt](https://github.com/TrinityCore/TrinityCore/files/1281314/6621d8fd7bb2._worldserverdebug.exe_.6-9_15-53-28.txt)

**Comment by Jildor** [comment]
Confirm:
https://gist.github.com/Jildor/9525c5141828fdc8dd4b0951eca63649

https://github.com/TrinityCore/TrinityCore/blob/6621d8fd7bb24b2842fa665e1aef4bff428b3b70/src/server/scripts/Northrend/Naxxramas/boss_patchwerk.cpp#L144

**Comment by Jildor** [comment]
@Treeston I think crash still: https://gist.github.com/Jildor/101ad848704d4a690c664646b9926239

**Comment by Jildor** [comment]
@Treeston crash still xD
if secondThreat or thirdThreat is a pet (by example put shaman elemental fire totem) crash:
https://gist.github.com/Jildor/75d4fc68970c192e02f0b21f6f4f7be0

**Comment by Treeston** [comment]
Hrm, that makes no sense. I'll look into it some more.

**Comment by Jildor** [comment]
@Treeston 
Have you seen anything?
Crash when secondThreat or thirdThreat AddThreat(HATEFUL_THREAT_AMT); if is a pet or guardian I think.

But...I don't understand why

maybe HostileReference::updateOnlineStatus() problem with pet?

**Comment by Raydor** [comment]
Reopen this issue please, it is still present as Jildor already commented (I confirm the crash).

**Comment by Sar777** [comment]
try 
https://gist.github.com/Sar777/b019b3e514d080ff6e67e8f58af816e5

**Comment by Treeston** [comment]
No idea what you're trying to do there, @Sar777

**Comment by zorix** [comment]
Try this:
https://github.com/zorix/TrinityCore/commit/4ed7ab93ecde13af05f37cc26afb392aa4ee4605

Crash can happen in case when `pHatefulTarget` die when casting `SPELL_HATEFUL_STRIKE` then it's removed from threat list so pointer to him is no longer valid.

**Comment by Treeston** [comment]
@zorix really good point, that might be the cause here
