### ISSUE TITLE
[Master] Quest deprecated in Draenei starting zone.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#20241]
**Description:**

Npc zalduun id 16502 http://www.wowhead.com/npc=16502/zalduun has quest that its deprecated in Legion

**Current behaviour:**

Quest http://www.wowhead.com/quest=26970/learning-the-word is deprecated in Legion

**Expected behaviour:**

That quest is no longer available

**Steps to reproduce the problem:**

1. Create a Draenei
2. Speak with Zalduun

**Branch(es):**
Master

**TC rev. hash/commit:** 

52c7f12ed35f321dc97d8caea2b112287f5ac05b

**TDB version:**  7.2.0+updates

**Operating system:** CHANGEME OS

**Comment by Exodius** [comment]
Suggested Fix:
Also disable the quest for all other races. All quests are marked as removed in 7.0.3
```sql
-- Disable Priest class quests "Learning the Word", removed in 7.0.3
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry` IN (26970, 10072, 14279, 26949, 27066, 26919);
INSERT INTO `disables` (`sourceType`,`entry`,`flags`,`params_0`,`params_1`,`comment`) VALUES
(1,  26970, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Draenei'),
(1,  10072, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Blood Elf'),
(1,  14279, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Worgen'),
(1,  26949, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Night Elf'),
(1,  27066, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Tauren'),
(1,  26919, 0, '', '', 'Quest removed in patch 7.0.3: Learning the Word - Human');
