### ISSUE TITLE
[3.3.5] Autoshot and Stealth

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20243]
**Description:**

Hunter autoshot does not interrupt when you get stealth aura

**Expected behaviour:**

Should stop autoshot

**Steps to reproduce the problem:**

1. Use autoshot
2. Use Shadowmeld (Racial Night Elf) or any SPELL_AURA_MOD_STEALTH
3. You can see don't stop autoshot and you are in SPELL_AURA_MOD_STEALTH doing damage without remove the aura

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 445c5a00e8

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Eliminationzx** [comment]
We should interrupt autoshoot cast on `EffectSanctuary`.
Something like that.
```diff
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index f281b27b14..51cbffabae 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -3945,6 +3945,11 @@ void Spell::EffectSanctuary(SpellEffIndex /*effIndex*/)
 
     if (!unitTarget)
         return;
+    
+    // prevent interrupt message
+    if (GetCasterGUID() == unitTarget->GetGUID() && unitTarget->GetCurrentSpell(CURRENT_GENERIC_SPELL))
+        unitTarget->FinishSpell(CURRENT_GENERIC_SPELL, false);
+    unitTarget->InterruptNonMeleeSpells(true);
```

**Comment by Jildor** [comment]
@Eliminationzx I see this code is copied from:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L2245

You need define aura for GetCasterGUID(), if not, you can't compile
And I test and removes SPELL_AURA_MOD_STEALTH instead stop autoshot

**Comment by Jildor** [comment]
I think this is the best option, but I don't know if it's valid for make a pull request

```diff
diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index f1148515de..e9aa861c29 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -3974,6 +3974,9 @@ void Spell::EffectSanctuary(SpellEffIndex /*effIndex*/)
     if (!unitTarget)
         return;
 
+    if (unitTarget->GetTypeId() == TYPEID_PLAYER)
+        unitTarget->ToPlayer()->SendAttackSwingCancelAttack();     // melee and ranged forced attack cancel
+
     unitTarget->getHostileRefManager().UpdateVisibility();
 
     Unit::AttackerSet const& attackers = unitTarget->getAttackers();
```

**Comment by tkrokli** [comment]
If it compiles and works to the best of your knowledge, it is worth creating a pull request for even more feedback.

**Comment by Jildor** [comment]
Oks, I'm not sure if this is valid or not (works fine), I will try it ;)
#20492

**Comment by Jildor** [comment]
Was valid  🎉
