### ISSUE TITLE
Some of Grimclaw's lines are missing

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20257]
**Description:**

Some of Grimclaw's lines are missing. I think they were there at some time, because the first line for Grimclaw in `creature_text` table has `GroupID`=4. Maybe they were erased by accident?

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Comment by ZenoX92** [comment]
**Suggested Fix:**

```sql
-- Grimclaw --> Add missing lines
DELETE FROM `creature_text` WHERE `CreatureID`=3695 AND `GroupID`<4;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
('3695','0','0','%s roars at Terenthis to get his attention.','16','0','100','0','0','478','1226','0','Grimclaw'),
('3695','1','0','%s begins to moan and roar at Terenthis while stomping his paws on the ground.','16','0','100','53','0','474','1228','0','Grimclaw'),
('3695','2','0','%s roars at Terenthis more, but this time the druid seems to understand the bear.','16','0','100','0','0','473','1231','0','Grimclaw'),
('3695','3','0','%s roars in acknowledgement at Terenthis.','16','0','100','0','0','473','1233','0','Grimclaw');

**Comment by tkrokli** [comment]
>  I think they were there at some time, because the first line for Grimclaw in `creature_text` table has `GroupID`=4. Maybe they were erased by accident?

Sounds likely. I still find 3.3.5 quest text content missing or cut short, often at places where I am fairly sure it used to be present. Keep up the good work of salvaging what is lost! 👍
