### ISSUE TITLE
[3.3.5] Core crash on Patchwerk pull

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#20278]
**Description:**

When pulling patchwerk and no second or third target has initiated combat with him, the core crashes when he tries to run the Hateful Strike event.

Stack trace:
https://files.fm/down.php?i=gbjj555u&n=c7d565739b2e_worldserver.exe_%5B7-9_2-9-35%5D.txt

**Branch(es):** 3.3.5
**TC rev. hash/commit:** c7d5657
**TDB version:**  TDB 335.63
**Operating system:** Win

**Comment by Aokromes** [comment]
Update you core a crash for this was fixed yesterday.

**Comment by Foereaper** [comment]
My bad, I missed that commit when looking through what had been pushed since my last pull. Thanks!
