### ISSUE TITLE
[3.3.5] Dynamic Spawn vs DespawnAtEvade

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#20287]
**Description:** Dynamic Spawn show some conflict with DespawnAtEvade method. When creature respawn with Dynamic Spawn system, a new script is loaded (is a new creature !).
But some events triggered by areatriggers should occour just 1 time. Other bosses should have same issue related with events that should happen 1 time only.
Normally was used class constructor to handle with it, but since creature load a new script it's not possible anymore (constructor is "called again")

**Current behaviour:** DespawnAtEvade kill boss, boss respawns with a new script, areatrigger events is called again.

**Expected behaviour:** Areatrigger events called 1 time only.

**Steps to reproduce the problem:**

1.Go to Lady Deathwhisper, Teron Gorefiend or any boss with areatrigger + DespawnAtEvade
2.  Pass to areatriggers (normally in main door).
3. Start fight/Evade, pass to areatrigger again

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4d654f548b29bf61552d9f90da8254ecea91b63e

1 suggested solution for it (ccrs solution) is store this "events" in instance_script.

(issue created to remember of this problem xd)

**Comment by Shauren** [comment]
Change script to store state in instance script

**Comment by Keader** [comment]
971ed856a49dc56ea33d9a0779b1386eea5cd3ca
