### ISSUE TITLE
[3.3.5] Crash Guildbank delete item?

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20286]
**Description:**

no idea, i was not at home but my core crashed and got a crashlog.

**Current behaviour:**

based on crashlog maybe it crashed on deleting item from guildbank?

**Expected behaviour:**

would be nice if the core didnt crash :P 

**Steps to reproduce the problem:**

no idea, i was not online when it happened.
Crashlog: https://gist.github.com/dikkedeur/19b0c8e228f73fa1207725fac465fd13

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a1a12ec 2017-09-06 16:33:44 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB version: TDB 335.63

**Operating system:** Ubuntu server 16.04 lts

**Comment by jackpoz** [comment]
it looks like a crash on shutdown to me

**Comment by dikkedeur** [comment]
can be, i was not online so after i posted your reply i talked to some of my team mates and 1 told that he restarted it in that time frame.. so i think you can close this one.

**Comment by jackpoz** [comment]
well it's not supposed to crash on shutdown, that's still a issue

**Comment by Aokromes** [comment]
a ticket for crash on shutdown was opened months ago ....
https://github.com/TrinityCore/TrinityCore/issues/17742
