### ISSUE TITLE
[3.3.5] Quest: Find the ancient hero

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20284]
**Description:**

Once you find the Iskalder and bring it back to the cave with The Bone Witch, the quest does not complete.

**Current behaviour:**

 Tell us what happens.

Once you find the Iskalder and bring it back to the cave with The Bone Witch, the quest does not complete.

**Expected behaviour:**

 It should register that you have brought Iskalder back and complete the quest objective

**Steps to reproduce the problem:**

Take the quest, travel to the underground halls and find the Iskalder. Once you subjugate it with the quest item, bring it back to the cave where The Bone Witch is.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a1a12ec755e4 2017-09-05 15:33:44 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:** ubuntu server 16.04 LTS

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/20310
