### ISSUE TITLE
NPC vs NPC Aggro Seems Broken

### ISSUE THREAD

**Issue by Solzz** [TrinityCore/TrinityCore#20295]
**Description:**

NPC vs NPC aggro seems broken

**Current behaviour:**

When an NPC tries to attack another NPC they keep restting their aggro and twitch when doing this.

**Expected behaviour:**

This shouldn't happen NPC's should be allowed to aggro each other in certain situations.

**Steps to reproduce the problem:**

1. Get any pet taming quest and tame the required NPC and try use that NPC to attack another NPC with a spell such as a Dire Molted Boar in Durator you will see the Victim NPC use it's spell but not attack and your temporary quest pet will not attack anything either.
2. Inititate the quest http://www.wowhead.com/quest=1222/stinkys-escape and watch stinky and the raptors try attack him.
3. Guard outside of Razor hill will try attack a scorpid and the scorpid is constantly twitching trying to attack the guard and the guard doesn't move either.

I believe this was introduced in this commit https://github.com/TrinityCore/TrinityCore/commit/e2a1ccd118d129b96e09ff1a15ed0adb1d4a3897 as before this, the issues stated above didn't exist.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6c049eac6c48 2017-09-09 08:49:16 -0300 (3.3.5 branch) (Win64, Release, Static)

TDB version: TDB 335.63

Windows 10 64 and Ubuntu 16.04 LTS

**Comment by Solzz** [comment]
Sorry for the typo in the title it should be Broken not Borken! haha

**Comment by Killyana** [comment]
Dup #19998
