### ISSUE TITLE
[3.3.5] - Lady DeathWhisper Moves (Phase one)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20306]
**Description:**

When you start combat with Lady DeathWhisper, she moves
(Ignore this: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp#L284
and
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp#L345 )
(I think it happens with more NPC)

**Expected behaviour:**

Should stay in the position without move

**Steps to reproduce the problem:**

1. Go to the boss
2. Attack and move
3. See how the boss follow you

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4d654f548b29bf61552d9f90da8254ecea91b63e

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by sirikfoll** [comment]
Will be fixed by #20288
Thanks for reporting

**Comment by Jildor** [comment]
But this not is related with dynamic respawn I will tried before and don't happens, I think is caused after threat refactor and target selection  commits of @Treeston

**Comment by Treeston** [comment]
I don't see why that'd make her move.

**Comment by Keader** [comment]
Areatrigger force Lady go to PHASE_INTRO :)

**Comment by Treeston** [comment]
There you go, then.

**Comment by Jildor** [comment]
I try to put before rev: 2241e098a31904e596e60fb5b877fba4005b0562
I test and works fine.
Then I put after rev: 2241e098a31904e596e60fb5b877fba4005b0562
(here: 1e79bf7939ed44c1659e64dedf770861f81514c2)
And bug appears...

I don't know why...xD

**Comment by Keader** [comment]
> Areatrigger force Lady go to PHASE_INTRO 

will be fixed when #20288 gets merge

**Comment by Jildor** [comment]
Oks, only I don't know why after this commit happens xD

**Comment by sirikfoll** [comment]
Probably wrong repro steps, try
- .go crea id 36855
- Aggro boss with player 1, don't trigger intro
- Trigger intro(by getting close to the door)
- Aggro boss with player 2

**Comment by Jildor** [comment]
Not necessary make this, only kill marrowgar and go to lady, kill trash and come near her and she follow you

**Comment by Keader** [comment]
971ed856a49dc56ea33d9a0779b1386eea5cd3ca
