### ISSUE TITLE
[3.3.5] BS Trainer Dumphry Does Not Teach

### ISSUE THREAD

**Issue by ogeraisi** [TrinityCore/TrinityCore#20313]
**Description:**

Creature entry 21209 (Dumphry) is supposed to be a blacksmithing trainer but he doesn't have the trainer npcflag nor the correct trainer_type. the npc_trainer table has no entries for him either.

**Current behaviour:**

NPC wouldn't teach anything.

**Expected behaviour:**

NPC should teach blacksmithing recipes.

**Steps to reproduce the problem:**

1. Talk to NPC.

**Branch(es):**

both branches (fix for master might be different).

**TC rev. hash/commit:** 

TrinityCore rev. 62f7debffdb0 2017-09-10 17:24:03 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 10 Professional x64

I don't have any sniffs but this is a basic fix to get him working.
```sql
UPDATE creature_template SET `npcflag` = `npcflag` | 16, `trainer_type` = 2 WHERE `entry` = 21209;
INSERT INTO npc_trainer VALUES (21209,-201004,0,0,0,0),(21209,-201005,0,0,0,0),(21209,-201006,0,0,0,0);
```

**Comment by Killyana** [comment]
He doesn't teach spells that requires more than 300
https://web.archive.org/web/20110826173007/http://www.wowhead.com:80/npc=21209#comments
