### ISSUE TITLE
[master][7.3]connection_patcher unable to find pattern where patching 7.3 wow client

### ISSUE THREAD

**Issue by zhou9197** [TrinityCore/TrinityCore#20316]
**Description:**

connection_patcher unable to find pattern where patching 7.3 wow win64 client

**Current behaviour:**

TrinityCore rev. b2fc329adfab+ 2017-09-11 22:35:55 +0200 (master branch) (Win64, Release, Static) (connection_patcher)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Creating patched binary...
Determined build number: 25021
Win64 client...
patching Portal
Found offset 20070208
patching redirect RSA Modulus
Found offset 19496672
patching BNet certificate file location
Found offset 20029280
patching BNet certificate file to load from local path instead of CASC
EX: unable to find pattern

**Expected behaviour:**

patching well.

**Steps to reproduce the problem:**

1. copy connection_patcher.exe to wow folder
2. ./connection_patcher.exe --path Wow-64.exe

**Branch(es):**

master

**TC rev. hash/commit:** 

commit b2fc329adfab22b861a53889cda4c54bde372f46 (HEAD -> master, origin/master, origin/HEAD)

**TDB version:**  b2fc329adfab22b861a53889cda4c54bde372f46

**Operating system:** win10 64

**Comment by Aokromes** [comment]
https://i.imgur.com/vhhhv05.png
