### ISSUE TITLE
Death Knight Quest: An End To All Things...

### ISSUE THREAD

**Issue by minkokomaung** [TrinityCore/TrinityCore#20311]
**Description:**

Frostbrood Vanquisher can kill Scarlet Soldiers but can't destroy Scarlet Ballista.

Quest
http://www.wowhead.com/quest=12779/an-end-to-all-things

Scarlet Ballista
http://www.wowhead.com/npc=29104/scarlet-ballista

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 62f7deb

**TDB version:**  TDB 3.3.5.63

**Operating system:** Windows 10 x64

**Comment by Aokromes** [comment]
#20071
