### ISSUE TITLE
Death Knight Quest: The Light of Dawn

### ISSUE THREAD

**Issue by minkokomaung** [TrinityCore/TrinityCore#20312]
**Description:**

After gossip Highlord Darion Mograine, Scourge army start moving toward Light's Hope Chapel too fast but Highlord Darion Mograine go very slowly.
If you go together with Scourge army, Highlord Darion Mograine will disappear and battle won't start.
If you wait and go slowly with Highlord Darion Mograine, battle will start but not completable.

Quest
http://www.wowhead.com/quest=12801/the-light-of-dawn

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 62f7deb

**TDB version:**  TDB 3.3.5.63

**Operating system:** Windows 10 x64

**Comment by dikkedeur** [comment]
i can confirm this as well.. i have seens this for a long time.. sometimes it goes okay and sometimes its a mess :P

**Comment by Szone** [comment]
confirm.

**Comment by rockz1152** [comment]
confirmed 3e74ef1528db

**Comment by devtekve** [comment]
Confirmed f017b1d470ae

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/20310
