### ISSUE TITLE
[3.3.5] - Deathbringer Saurfang Outro

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20318]
**Description:**
When kill Deathbringer Saurfang seems don't start outro (Alliance), Horde seems ok
Can be related with this crash: #20093 ??

**Expected behaviour:**
Should start outro event

**Steps to reproduce the problem:**

1. Complete Gunship Battle and go to Deathbringer Saurfang
2. Start combat and kill Deathbringer Saurfang

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4d654f548b29bf61552d9f90da8254ecea91b63e

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Keader** [comment]
Related with: #3963
Missing events after Deathbringer dies :/

**Comment by Jildor** [comment]
jum, I would have sworn it worked before, sorry xD
