### ISSUE TITLE
[3.3.5] Anti Magic Shield from DKs not preventing some harmful effects from applying

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20326]
**Description:** Spell [Anti Magic Shield](https://wotlk.evowow.com/?spell=48707) doesn't prevent some harmful effects from applying.

**Current behaviour:** [Anti Magic Shield](https://wotlk.evowow.com/?spell=48707) is not preventing spells such as [Blood Plague](https://wotlk.evowow.com/?spell=55078) from applying (but it does prevent [Ebon Plague](https://wotlk.evowow.com/?spell=51735), which is also a disease), it also for example doen't prevent [Judgement](https://wotlk.evowow.com/?spell=20185). These are some examples it should prevent and are not preventing.

**Expected behaviour:** [Anti Magic Shield](https://wotlk.evowow.com/?spell=48707) should prevent harmful effects.

**Steps to reproduce the problem:**

1. Cast [Anti Magic Shield](https://wotlk.evowow.com/?spell=48707).
2. Cast [Plague Strike](https://wotlk.evowow.com/?spell=49921) at the player with the shield.
3. [Blood Plague](https://wotlk.evowow.com/?spell=55078) is applied and it shouldn't at all.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/971ed856a49dc56ea33d9a0779b1386eea5cd3ca

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Aokromes** [comment]
Effect #1 | Apply Aura: School Absorb (Holy, Fire, Nature, Frost, Shadow, Arcane)
Not sure if it must prevent diceases.

**Comment by Raydor** [comment]
@Aokromes Still Judmegent should be prevented and anyways, Ebon Plague is not applied for some reason 🤔 and its also a disease.

**Comment by Keader** [comment]
same of (https://github.com/TrinityCore/TrinityCore/issues/21343#issuecomment-397299677)
