### ISSUE TITLE
[3.3.5][CRASH] Crash in WorldObject::IsInMap

### ISSUE THREAD

**Issue by Raydor** [TrinityCore/TrinityCore#20324]
**Description:** There is a crash in WorldObject::IsInMap, this is called by boss_patchwerk.cpp, but probably there is more with other boss scripts. Summoning @Treeston cause this can probably be related to dynamic spawn (I don't know xD). No idea how to reproduce the crash, my server just crashes by some player maybe engaging patchwerk.

Crashlog: https://gist.github.com/Raydor/43a40bbc0af8520ece30bb00288b372b

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/42be04898c6fd001160ee4fdf00fc2ba5c5c1ee3

**TDB version:**  TDB 3.3.5 63

**Operating system:** Ubuntu 17.04

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20247
