### ISSUE TITLE
[3.3.5] Quest: An End To All Things

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20322]
**Description:**

Scarlet Ballistas regain their health and the quest can't be completed.

**Current behaviour:**

Scarlet Ballistas regain their health and the quest can't be completed.

**Expected behaviour:**
They should be killable.

Tell us what should happen instead.
they regain instant HP, i do around 34k damage while they are 54k and boom you see hp drop while you hit it but then 1 second later its back on full hp.

**Steps to reproduce the problem:**

Attack them with a Frostbrood Vanquisher it does a maximum of 60k dmg per hit. The ballista has 83k hp. After you hit the ballista it regains it's hp immediately. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 62f7debffdb0 2017-09-10 17:24:03 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:**ubuntu server 16.04 lts

**Comment by cirosantos0** [comment]
#20071 
#20311
