### ISSUE TITLE
Map Extractor failing [MASTER]

### ISSUE THREAD

**Issue by Ferelith** [TrinityCore/TrinityCore#20332]
**Description:**

Map extractor returns an error when trying to create maps: "Fatal error: Invalid Map.db2 file format! SUCCESS" (locale enUS)

Tried running mapextractor.exe in DOS (administrator) and it does not make a difference. The game was fully downloaded & updated.

I am out of ideas.

**Current behaviour:**

When using mapextractor - the following error appears and process is aborted "Fatal error: Invalid Map.db2 file format! SUCCESS"

**Expected behaviour:**

mapextractor.exe should extract maps without any errors.

**Steps to reproduce the problem:**

1. Get the latest commit  
2. compile
3. Use mapextractor.exe in WoW directory.

**Branch(es):**

master

**TC rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: TrinityCore rev. 115dffd

**TDB version:**  

720

**Operating system:** Win10

**Comment by Aokromes** [comment]
for sure you are using 7.3.0 unsuported client.

**Comment by Ferelith** [comment]
If this is the issue, where can I get a download or downgrade?

**Comment by Aokromes** [comment]
not here.
