### ISSUE TITLE
[3.3.5] Commander Hobb is Invisible - FIX

### ISSUE THREAD

**Issue by nathanroberts7** [TrinityCore/TrinityCore#20334]
**Description:**

Commander Hobb is invisible and only his axe is visible.

**Current behaviour:**

Same as description. You only see a floating axe.

**Expected behaviour:**

Commander Hobb should not be invisible.

**Steps to reproduce the problem:**

1. Type .go xyz -4106.56, 1126.79, 43.64 
2. See a floating axe named Commander Hobb

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 971ed856a49d+ 2017-09-14 22:532 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

Tested Query: Yes

Suggested Fix:
```sql
-- Fixes Commander Hobb's invisible model 
DELETE FROM `creature_model_info` WHERE `DisplayID`=21342 AND `BoundingRadius`=0.5;
INSERT INTO creature_model_info (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`) VALUES
(21342, 0.5, 1, 0, 21342);
```

**Comment by tkrokli** [comment]
@Killyana : in issue #15770 you said "For creature_model_info we cannot touch this table." - is this still true or does it depend on the table info (creature/DisplayID) and if it can be checked & verified by sniff info?

@nroberts57 : did you check out the issue pages **[Quest][11097][DB/SAI] Deadliest Trap Ever Laid** #6318 (comments related to Commander Hobbs' invisibility & phasing/reputation) and the closed issue #15770 **[3.3.5] DB/Creature: Magistrix Eredania (entry 16160) not visible** to find out if your suggested solution could be rejected? I noticed that the change from invisible to visible still happens depending on quest status & reputation gains when I ran through some of the quest lines in SMV last week.

**Comment by nroberts57** [comment]
You are correct, @Aokromes said to force the model to be visible in creature_table. I will fix this soon. Also, I didn't catch the invisible problem happening during different quest phases, so I'll look into that as well. 

Thanks for the input! Trying to learn and help along the way if possible.

**Comment by Killyana** [comment]
No just remove the other gender from creature_model_info, The other solution is loading the model by script:
``` sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID` IN (21505);
