### ISSUE TITLE
[osx][3.35]login failed with osx-build but success with win10-(VS2017 64)-build

### ISSUE THREAD

**Issue by zhou9197** [TrinityCore/TrinityCore#20331]
**Description:**

branch 3.35:
1. same client  3.35_12340
2. same sqls
3. same extracted map files (extracted by osx-build tools)
 cannot login with osx authserver & worldserver
 can login with win10-vs2017.64 authserver & worldserver

**Current behaviour:**

osx :(bad)
1. start client & input username & password & comfirm
2. show "server selection" , choose Trinity and Confirm (auth trace log also shows "user 'xxxxx' successfully authenticated.)
3. show "login in server..." and wait for less than 1s; go to step 2 automatically which is unexpected

win10: (good)
1. start client & input username & password & comfirm
2. show "server selection" , choose Trinity and Confirm
3. login in success and I can create or select character and enter the world

**Expected behaviour:**

login in success like win-version

**Steps to reproduce the problem:**

see  Current behaviour

**Branch(es):**

 3.3.5  

**TC rev. hash/commit:** 

TrinityCore rev. d23682331b65+ 2017-09-11 20:23:22 +0200 (b3.35 branch)

**TDB version:**  3.35.63 and updates till d23682331b65+

**Operating system:** osx 10.12.6

**Comment by obsidean** [comment]
did the worldserver daemon startup?i.e. did you get the "ready" message?  I noticed that lately it is taking 2 minutes for the  "objects pooling system" to startup.

**Comment by zhou9197** [comment]
yes, and I can create account

World initialized in 0 minutes 12 seconds
TC>TrinityCore rev. d23682331b65 2017-09-11 20:23:22 +0200 (b3.35 branch) (MacOSX, RelWithDebInfo, Static) (worldserver-daemon) ready...
TC>.account create t1 t1
TC>Account created: t1
TC> .account set gmlevel t1 3 -1
TC>Security level of account T1 changed to 3.
TC>
