### ISSUE TITLE
[Core] Several issues after 7fff83d + updates

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#20341]
**Description:**

Several features seem to have stopped working as intended after the above mentioned commit and subsequent updates. I will list things I discover below as I go along:

**Quests:**
- Massacre at Light's Point(12701), the minecart no longer gets pulled down to the boats.
- Territorial Trespass (13051), the dragon no longer lands upon quest progression.

**Instances:**
- Azjol'Nerub, Hadronox keeps resetting as soon as one of the debuffs runs out. Impossible to complete without GM intervention.
- The Culling of Stratholme, Arthas keeps getting stuck on adds and no longer continues to follow his waypoints, impossible to complete without GM intervention.

I will keep this updated with more examples as I find them, but these are the ones I have noticed so far.

Let me know if this should be split into separate issues, however they all seem to stem from the same chain of commits.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  d7e4dcc

**TDB version:**  335.63
**Operating system:** Win Server 2008

**Comment by Aokromes** [comment]
#20310

**Comment by Foereaper** [comment]
That issue only contains one of the above mentioned quests, as there are more features that seem to not work as intended would it not be better to have it as a separate issue?

**Comment by Aokromes** [comment]
maybe that ticket can be changed to generic ticket.

**Comment by Foereaper** [comment]
That works for me :)
