### ISSUE TITLE
[3.3.5] Culling of Stratholme

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#20355]
Branch(es): 3.3.5

TC rev. hash/commit: 20bc7d7

TDB version: 335.63

Operating system: Win Server 2008 R2 SP1

Description :
Chromie doesnt work to teleport (Probably in Gossip-menu_option).
Citizen dont become zombies and unattackables.
Arthas doesnt work all the time. His Gossip cant be in another language.

**Comment by HannibalRoG** [comment]
Work in progress https://github.com/TrinityCore/TrinityCore/pull/17860
