### ISSUE TITLE
[3.3.5] Anub'ar

### ISSUE THREAD

**Issue by ConradBunton** [TrinityCore/TrinityCore#20354]
**Description:** In Azjol Nerub, Anub'ar respawn in loop.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 20bc7d7161825fd5d91ff504455b4969bc885629

**TDB version:**  335.63

**Operating system:** Win Server 2008 R2 SP1

**Comment by Foereaper** [comment]
See https://github.com/TrinityCore/TrinityCore/issues/20310

**Comment by ConradBunton** [comment]
Why closed ?

**Comment by tkrokli** [comment]
Because your issue is covered by the same problem as in issue #20310 (even if it is not mentioned directly).
