### ISSUE TITLE
[3.3.5] Mount quests are broken

### ISSUE THREAD

**Issue by Noryad** [TrinityCore/TrinityCore#20356]
**Description:**
I found two broken missions related to mounts with the same behavior. After riding and walking a few meters, the player loses control of the mount and the mount returns to any point.
These are:
1. Mounting Up (12414)
2. Kaw the Mammoth Destroyer (11879)

Maybe there are more.

**Current behaviour:**
After riding and walking a few meters, the player loses control of the mount and the mount returns to any point and the quest can not be completed.

**Expected behaviour:**
Mount should be controlled by players.

**Steps to reproduce the problem:**
1. First .add quest 12414 and .add 37707 (Wild Carrot).  
2. Equip Stick.
3. Use Stick on Highland Mustang.
4. Try to control the horse for a while to the camp.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3992541
TrinityCore rev. 3992541d2d10 2017-09-19 20:36:43 +0100

**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Windows 10

**Comment by Noryad** [comment]
[A Mammoth Undertaking] same behavior

**Comment by Foereaper** [comment]
Same thing happens with the DK starter quest where you have to steal a horse, seems to be related to the way point issue a few issues down in the list. They seem to attempt to go back to the next way point in line, even when player controlled.

**Comment by Foereaper** [comment]
@Noryad I have added the above quests to the list of issues in https://github.com/TrinityCore/TrinityCore/issues/20310
