### ISSUE TITLE
[3.3.5] Guild Control Save Bug

### ISSUE THREAD

**Issue by Estaira** [TrinityCore/TrinityCore#20353]
**Description:**
When a guildmaster makes multiple changes in guild control settings and tries to save. It does not save the changes made. Instead you will have to make changes one rank at a time.

**Expected behaviour:**
The guild control settings should save all the changes made. Instead of one rank at a time.

**Steps to reproduce the problem:**
1. Create a guild
2. Make changes to multiple guild ranks. 
3. Then try to save it.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
25111b0

**TDB version:**  
335.63

**Operating system:**
Ubuntu 16.04

**Notes:**
This is a very old bug. I could not find any bug reports on this correct me if I am wrong.

**Comment by Tyrelis** [comment]
Is anyone there there no issue tags or comments?

**Comment by Langerz82** [comment]
I tested adjusting the guild control settings for Officer and it worked okay, I could apply multiple options.

TrinityCore rev. a217c0be922f+

**Comment by Langerz82** [comment]
as I suspected it only sends on type when you change two and do not press apply for the first. This issue cant be solved as the client only sends one packet for one type on apply. Unless I'm mistaken?

```
ClientToServer: CMSG_GUILD_SET_RANK_PERMISSIONS (0x0231) Length: 68 ConnIdx: 0 EP: 127.0.0.1:49917 Time: 02/02/2018 15:51:54.642 Number: 203
Rank Id: 2
Rights: 330 (GuildChatSpeak, OfficerChatSpeak, Roster, Demote)
Name: Veteran
Money Per Day: 0
[0] Tab Rights: 0 (None)
[0] Tab Slots: 0
[1] Tab Rights: 0 (None)
[1] Tab Slots: 0
[2] Tab Rights: 0 (None)
[2] Tab Slots: 0
[3] Tab Rights: 0 (None)
[3] Tab Slots: 0
[4] Tab Rights: 0 (None)
[4] Tab Slots: 0
[5] Tab Rights: 0 (None)
[5] Tab Slots: 0
```

**Comment by Tyrelis** [comment]
> Does the retail allow you to change both ranks at once?
Yes it does allow you to change both at once.

**Comment by ariel-** [comment]
But did it allow you to change more than one rank, back in 3.3.5a?

**Comment by Tyrelis** [comment]
@ariel- Yes it did as stated above...

**Comment by CraftedRO** [comment]
dd10ac27fee1 This issue is invalid because you only can edit one rank at a time and when you click Accept the tab dissapear.

This is how it works on 3.4.2 PTR (same as TC)

https://github.com/TrinityCore/TrinityCore/assets/24683355/44e4dc75-2c33-43e1-a1d7-fb69c89746a4
