### ISSUE TITLE
[Master] Trainers not Working

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#20388]
**Description:**

I tried to learn a progression and riding i right clicked the npc and nothing happoned.

**Current behaviour:**

Nothing happons when trying to use the said trainers.
(Tried with Silvermoon Trainers)

**Expected behaviour:**

Window opening up to learn from trainers.

**Steps to reproduce the problem:**

1. Go to a riding NPC ord Professions Trainer
2. Right click Npc to open what would be gossip or Straight to learning window.
3. Nothing happons

**Branch(es):**

Master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/0c0f099dd6c7474e57d80e47f6f5a2dd97bf26af

**TDB version:**  720.00

**Operating system:** Win7

**Comment by Aokromes** [comment]
#20193
