### ISSUE TITLE
[Master] Honor talents Not enabling

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#20386]
**Description:**
I've tried to enable my Honor talents in the core but they do nothing.

**Current behaviour:**

Honor talents do not lock in and learnt
![wowscrnshot_092217_173521](https://user-images.githubusercontent.com/6026902/30754903-769f0a2c-9fbc-11e7-8d73-23fff0d9918e.jpg)

**Expected behaviour:**

Honor Talents should be able to be learnt 

**Steps to reproduce the problem:**

1. level to 110
2. Enter Honor talent tab
3. Left click tab and nothing happons

**Branch(es):**

Master
**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/0c0f099dd6c7474e57d80e47f6f5a2dd97bf26af

**TDB version:**  720.00

**Operating system:**  Win7

**Comment by Aokromes** [comment]
#19962

**Comment by Nupper** [comment]
i assume it being closed meaning its a WIP?

**Comment by tkrokli** [comment]
Sort of. More like "this issue is being worked on in that PR and will be solved once the PR is merged". I suppose you can test the PR content and see for yourself if it works as intended and give feedback in the PR.
