### ISSUE TITLE
Stone Statues still misbehaving

### ISSUE THREAD

**Issue by aletson** [TrinityCore/TrinityCore#20406]
**Description:**  Stone Statues are still misbehaving similar to #6554 #1923

**Current behaviour:**

When you have a Stone Statue out (crafted object from Jewelcrafting) and attack a mob, the statue will stop healing and run to attack the mob.

**Expected behaviour:**

The statue should only heal. There's a comment on a wowhead page from back in 2.2.3 that indicates that it might go attack things if a Hunter uses Feign Death, but I have no way of confirming that.

**Steps to reproduce the problem:**

1. Get a Rough Stone Statue in your inventory. (`.additem 25498 1`)
2. Use it
3. Attack a mob.

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  7a0f1d7

**TDB version:** 335.63 with updates

**Operating system:** Ubuntu 16.04 LTS

**Comment by offl** [comment]
> There's a comment on a wowhead page from back in 2.2.3 that indicates that it might go attack things if a Hunter uses Feign Death, but I have no way of confirming that.

> If you leave combat (For example by using feign death) the statue will attack your enemy...and get killed in 1 hit ^^
http://www.wowhead.com/item=25881/heavy-stone-statue#comments:id=277273

So adding REACT_DEFENSIVE is hack?

**Comment by offl** [comment]
All of them uses NO_COMBAT difficulty flag but probably can attack if hunter uses feign death. Or Blizzard added it later to fix that bug from TBC times.
I don't like that they follows player, guardian follow movement is still used and ignores the fact that creature channels spell. And I don't want to root them.

**Comment by illfated** [comment]
Oh. I thought that maybe the solution for totems would apply in this case too.

**Comment by offl** [comment]
CREATURE_DIFFICULTYFLAGS_SESSILE                           = 0x00000100, // Creature is rooted
    CREATURE_DIFFICULTYFLAGS_IGNORE_COMBAT                     = 0x02000000,

Are flags they uses

**Comment by illfated** [comment]
Nice. Good improvement.
