### ISSUE TITLE
[3.3.5] Brewfest zone music isn't playing

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20404]
**Description:**
Sounds do not play if you go the Brewfest area

https://www.youtube.com/watch?v=RYSHFQBJZeo

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e31a2f394b95 2017-09-23 16:07:58 +0200 (335a branch)

**TDB version:**  CHANGEME Version of the TrinityCore database
TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** CHANGEME OS
Win7

**Comment by Aokromes** [comment]
works for me on durotar (very low volume)

**Comment by ArcaneFox** [comment]
In front of Stormwind, the music plays with good volume.

**Comment by Tauriella** [comment]
Uppps!
Sorry i have the Music diabled in the Client Options :-1: 
please close

**Comment by tkrokli** [comment]
Closing as requested and concluded.
