### ISSUE TITLE
3.3.5 gameobjects color

### ISSUE THREAD

**Issue by Frenlock** [TrinityCore/TrinityCore#20401]
**Description:**

Sometimes some gameobjects : mailbox , barrels , flags , indicators ( idk if all are gameobjects ) 
have a strange color like a dark-brown shadow over them . 
I tryed to re-download the game client , clear cache folder (check video settings) but didn't helped so I think that its not client-side related .
https://imgur.com/a/ID1y0

**Current behaviour:**

The gameobjects have that dark-brown color .

**Expected behaviour:**

The gameobjects shouldn't have that dark-brown color .

**Steps to reproduce the problem:**

1. Login and logout several times until the problem appear .
2. If u go through portals / use hearthstone or teleport the problem may dissapear .

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 4542d93 2017-09-21 16:26:32 +0200 (3.3.5 branch) (Win32, Release, Static)

**TDB version:**  TDB_full_335.63_2017_04_18

**Operating system:** Windows 10 x64

**Comment by Shauren** [comment]
This is definitely client related. There is zero model rendering related code on the server.

**Comment by Aokromes** [comment]
if you are running windows 10 insider build you will have this problem.

**Comment by Frenlock** [comment]
Hmm I running on Windows 10 Home x64

**Comment by CraftedRO** [comment]
Btw this is still happening on (same Windows 10 Home x64 21H1 (OS Build 19043.1237) with a clean wow client.
TrinityCore rev. c8061d8ba620 2021-09-19 02:15:09 +0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) - Aowow trinity server.

![WoWScrnShot_092321_130537](https://user-images.githubusercontent.com/24683355/134489965-cff436b5-473c-471e-bb00-fe20848e9536.jpg)
![WoWScrnShot_092321_130548](https://user-images.githubusercontent.com/24683355/134489976-85ca5f84-234d-46fd-86f1-e91ad2942319.jpg)

**Comment by Aokromes** [comment]
it's something on your settings.
https://i.imgur.com/K9Kxg5H.jpeg

**Comment by CraftedRO** [comment]
well it can be but then why with same settings if I relog / enter portals , the problem is gone ?

**Comment by ihm-tswow** [comment]
What's your GPU / graphics driver version? Would be good to collect this in case it happens to more people. There's a few other known issues with modern drivers

**Comment by ihm-tswow** [comment]
I don't know if `/console characterAmbient 0`  might force it to re-render that as a workaround, but the effect looks similar

**Comment by CraftedRO** [comment]
Nvidia Graphics Driver 456.71 ( I have [MSI GeForce GTX 1050 GAMING 2GB](https://www.msi.com/Graphics-card/GeForce-GTX-1050-GAMING-2G) )
And yea someone reported same issue but I can't find it now.
Im used with it , but its kinda weird .

**Comment by CraftedRO** [comment]
Interesting fact is that on localhost (server on same machine) it never occurs :))

**Comment by HelloKitty** [comment]
This bug is a server emulator bug, not a client bug, and it's related to https://github.com/TrinityCore/TrinityCore/issues/24846. The server should not send SMSG_UPDATE_OBJECT packets with UPDATETYPE_CREATE_OBJECT blocks containing renderable Objects, other than the local player, until the Player is added to a map.
