### ISSUE TITLE
DB/Spell: add Electric Discharge to Iron Boot Flask

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20409]
**Description:**

[Iron Boot Flask](http://www.wowhead.com/spell=58501) should occasionally cause nature damage when the aura's owner deals melee damage. This is handled by the [Electric Discharge](http://www.wowhead.com/spell=29150) aura.

[Source](http://www.wowhead.com/item=43499/iron-boot-flask#comments:id=500026).

**Branch(es):** both.

**TC rev. hash/commit:** f55ca6b

**TDB version:** 335.63

**Suggested fix**:
```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (58501, -58501);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(58501, 29150, 0, "Iron Boot Flask also applies Electric Discharge"),
(-58501, -29150, 0, "Iron Boot Flask removal also removes Electric Discharge");
```

**Comment by Shauren** [comment]
No, look closely at 58501 - it already has this component.

**Comment by Killyana** [comment]
I tested it and the  spell is casted correctly, it has 10% chance to proc  https://woehead.way-of-elendil.fr/?spell=58501

**Comment by Wyreth** [comment]
Right, sorry. Didn't notice it was baked in the actual transform spell.

Can't get that one to proc though, no matter what I do. Tried for ~20 minutes now, doubt it is just bad luck on my part.
