### ISSUE TITLE
[3.3.5] DB/Creature: remove wrong on-aggro text from Orgrimmar Grunt

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20417]
**Description:**

Orgrimmar Grunts currently have on-aggro creature text that's only meant for neutral guards (when they attack players).

Horde/Alliance guards shouldn't say things like `Your actions shame us all, $c. I hurt inside as I beat you senseless.` and `You dare spill blood on neutral ground? OUT! OUT, I SAY!`.

**Branch(es):** 3.3.5.

**TC rev. hash/commit:** cb9b9f7

**TDB version:** 335.63

**Suggested fix**:
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=3296 AND `source_type`=0 AND `id`=1;
DELETE FROM `creature_text` WHERE `CreatureID`=3296 AND `GroupID`=0;
```

**Comment by tkrokli** [comment]
Then again, I wonder if removing the text affects any phased guards for special scenarios or when they attack PvP players.

**Comment by Wyreth** [comment]
Yeah, sometimes they get stuck targeting the scorpids and keep talking every second :D

If the text was correct, I'd have set it to player-target-only. But it's not even correct, so two birds with one stone.

**Comment by SeTM** [comment]
This bug from https://github.com/TrinityCore/TrinityCore/commit/6c5d473369511c84951f37f13f4898a3f92b0343, that totaly wrong. All guards lose their guard_generic scripts.

**Comment by Wyreth** [comment]
Works fine for me. What issue are you experiencing?

**Comment by SeTM** [comment]
Look at what the guard_generic script does, and what the guardians have stopped doing, after they have changed the script to SmartAI.

**Comment by tkrokli** [comment]
Maybe I have misunderstood your argument, but isn't that about what was discussed in issue **[[3.3.5] DK ending quest, missing texts and actions of city's NPCs #15246](https://github.com/TrinityCore/TrinityCore/issues/15246)** ?

**Comment by Killyana** [comment]
@SeTM Fell free to convert the SAI to cpp or the cpp to SAI
