### ISSUE TITLE
Wintergrasp not starting

### ISSUE THREAD

**Issue by ckjet** [TrinityCore/TrinityCore#20449]
**Description:**

Wintergrasp not starting.

**Current behaviour:**

Wintergrasp not have a facction flag and in Dalaran when i ask npc about battle start he answer 2:59:59 or 2:59:58. Im use before old version and they have a commands for wintergrasp .wg and i can test with this commands category.

**Expected behaviour:**

I think problem in timer.

**Steps to reproduce the problem:**

1. .tele Dalaran
2. Ask npc about wintergrasp begining timer

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cb9b9f7247c5 2017-09-24 20:23:37 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/20144
