### ISSUE TITLE
[3.3.5] Wrong gold reward for certain quests at level cap

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20445]
**Description:**

Some quests give a lot more gold than they should at level cap. I think this affects quests with a quest level equal or superior to 80.

This applies to, at least, every Icecrown/Storm Peaks daily quest.

Let's take [Blood of the Chosen](http://www.wowhead.com/quest=13330) as example.

In DB, RewardMoney is 74000. RewardBonusMoney is 132300.

- When a level 80 tries to accept that quest, they should apparently see only the RewardBonusMoney value ([video here](https://youtu.be/DBdknwcQQJA?t=456)). But in TC, RewardMoney is sent instead.

- When the player opens the quest log and checks the quest, they see the RewardBonusMoney value in both TC and retail. This is probably the client handling the value to show.

- When the quest is turned in, in TC they receive RewardMoney+RewardBonusMoney gold.

This only seems to affect high-level quests. For lower level quests, the correct value at level cap is RewardMoney+RewardBonusMoney.

I'd like to know if someone else has any insight on the matter.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 948cc64

**TDB version:** 335.63

**Comment by Langerz82** [comment]
Seems like the values are reversed and the Wowhead DB is wrong because I dont think RewardBonusMoney should be sent instead of RewardMoney. I was gonna make a patch but I dont think it's necessary. Just my thoughts..
