### ISSUE TITLE
[3.3.5] Decrepit Darkhound Movement Bug

### ISSUE THREAD

**Issue by Tyrelis** [TrinityCore/TrinityCore#20443]
**Description:**
The npc decrepit darkhound with id 1547 in Tirisfal Glades does not have the following correct movements.

**Expected behaviour:**
The npc decrepit darkhound with id 1547 in Tirisfal Glades should have the correct movements.

**Steps to reproduce the problem:**
1. Create an horde undead.
2. .go xyz 2162.229980 273.459015 44.172642
3. Take a look at npc decrepit darkhound wrong movements.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
25111b0

**TDB version:**  
335.63

**Operating system:**
Ubuntu 16.04

**Notes:**
Video of bug: https://youtu.be/9YH3Wkn6iYw

**Comment by Killyana** [comment]
Related to the rat guid: 45153 it try to kill it but it evades.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19998
