### ISSUE TITLE
[3.3.5] Creature: Shadowpine Shadowcaster

### ISSUE THREAD

**Issue by aletson** [TrinityCore/TrinityCore#20441]
**Description:**

Shadowpine Shadowcaster (http://www.wowhead.com/npc=16469/shadowpine-shadowcaster) is not casting abilities correctly.

**Current behaviour:**

The mob properly casts Mark of Shadow, but also will attempt to cast - and immediately cancel - Mind Flay.

**Expected behaviour:**

I'm not honestly sure. Either it should not cast Mind Flay at all, as the Wowhead page seems to indicate, _or_ it should cast Mind Flay without immediately cancelling it. I'm leaning towards the second case, since otherwise Mark of Shadow has no meaning whatsoever, but trying to think back to Actual Live BC is beyond me right now.

**Steps to reproduce the problem:**

- Create level ~15 character.
- `.tele FarstriderEnclave`
- Head east, find a Shadowpine Shadowcaster.

**Branch(es):**

Certainly 3.3.5, but honestly probably both.

**TC rev. hash/commit:** 

7a0f1d7

**TDB version:**  33563 with updates

**Operating system:** Ubuntu 16.04LTS

**Comment by Teppic1** [comment]
I did some investigation here and there appears to be a core problem with the Mind Flay spell (and potentially all other similar spells).

Some NPCs that use this spell work fine (e.g. 8528 Dread Weaver), while others fail exactly in the same way (e.g. 15367 Felendren the Banished). I can't see any differences in SAI or DB details to explain that.

I know Felendren used to work, so something has changed to break it.

**Comment by velinath** [comment]
Oh, wow. Good catch @Teppic1, I will edit the issue when I am back at a computer.

**Comment by Killyana** [comment]
It's just the level difference between the npc and the player that cause the spell to miss all the time, when a channeling spell miss it shows interrupted.

**Comment by Teppic1** [comment]
Ah, that'd explain why it worked on some and not others. Though when it misses, the spell not only interrupts but causes some weird behaviour, like the npc wanders back and forth.

**Comment by offl** [comment]
The problem was caused by cast flag INTERRUPT_PREVIOUS, it's already removed from nearly all scripts
