### ISSUE TITLE
Argent Tournament

### ISSUE THREAD

**Issue by ckjet** [TrinityCore/TrinityCore#20446]
**Description:**

Can't use mount of argent tournament. When attempting to mount a horse, automatic dismounting takes place. So i can't complete start quests of tournament.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Get start quest of tournament(ids: 13828, 13835, 13837) 
2. Get and equip Alliance Lance(id: 46069)
3. Try to mount to use Stabled Quel'dorei Steed

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

TrinityCore rev. cb9b9f7247c5 2017-09-24 20:23:37 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  335.63

**Operating system:** 
Debian 9

**Comment by ArcaneFox** [comment]
It's a long story: https://github.com/TrinityCore/TrinityCore/pull/14938

**Comment by ckjet** [comment]
I can't understand. I can fix it or its can't be integrated with actual code?

**Comment by ArcaneFox** [comment]
My fault, this isn't the start event of the Trial of the Champion. It's an another issue.

**Comment by HannibalRoG** [comment]
Not long ago that mounts worked perfectly, we have to find out in which commits they broke.

**Comment by minkokomaung** [comment]
Caused by 92e9376e5eecdc3412104a0ee304d389d4ce0188?

**Comment by kvipka** [comment]
just links on quests:
[Mastery Of Melee](http://dbwotlk.com/?quest=13828)
[Mastery Of The Shield-Breaker](http://dbwotlk.com/?quest=13835)
[Mastery Of The Charge](http://dbwotlk.com/?quest=13837)

**Comment by Nocturne1501** [comment]
Still broken... any possible patches?

**Comment by Killyana** [comment]
Cannot reproduce on  rev. c031167e067d
