### ISSUE TITLE
Quest "Rescue From Jaedenar" is not working

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20440]
**Description:**

This issue was posted before (#18586,  #17227). The quest is still not working.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Comment by Aokromes** [comment]
#17227 is still open

**Comment by ZenoX92** [comment]
Sorry, I thought it was closed too. I'll post my fix there then.
