### ISSUE TITLE
[3.3.5] GObject: Mummified Troll Remains

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#20442]
**Description:**

Respawn time and spawn rate for http://www.wowhead.com/object=181148/mummified-troll-remains is set too high.

**Current behaviour:**

Almost every possible spawn for this object is active simultaneously, and the respawn rate is _very_ high. I don't know what the actual number of active simultaneous spawns should be, but I had my wife check on live for me and there were definitely a _lot_ less of them.

**Expected behaviour:**

Spawn rate and respawn rate should be brought in line with blizzlike.

**Steps to reproduce the problem:**

- `.tele Farstrider Enclave`
- `.quest add 9193`
- Run west to the catacombs, burn some troll remains, see how many there are and how fast they respawn

**Branch(es):**

3.3.5 but likely master as well

**TC rev. hash/commit:** 

7a0f1d7

**TDB version:**  335.63 with updates

**Operating system:** Ubuntu 16.04 LTS

**Comment by offl** [comment]
#18934
