### ISSUE TITLE
[3.3.5] DB/Quest: fix chaining for quests Martek the Exiled and Encrusted Tail Fins

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20453]
**Description:**

The quests [Martek the Exiled](http://www.wowhead.com/quest=1106) and [Encrusted Tail Fins](http://www.wowhead.com/quest=1107) require the quests [Salt Flat Venom](http://www.wowhead.com/quest=1104) and [Hardened Shells](http://www.wowhead.com/quest=1105) rewarded.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1a23c43

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `quest_template_addon` SET `NextQuestID`=0, `ExclusiveGroup`=0 WHERE `ID` IN (1104, 1105);
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=1107;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry` IN (1106, 1107);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19, 0, 1106, 0, 0, 8, 0, 1104, 0, 0, 0, 0, 0, "", "Quest 'Martek the Exiled' requires quest 'Salt Flat Venom' rewarded AND"),
(19, 0, 1106, 0, 0, 8, 0, 1105, 0, 0, 0, 0, 0, "", "Quest 'Martek the Exiled' requires quest 'Hardened Shells' rewarded"),
(19, 0, 1107, 0, 0, 8, 0, 1104, 0, 0, 0, 0, 0, "", "Quest 'Encrusted Tail Fins' requires quest 'Salt Flat Venom' rewarded AND"),
(19, 0, 1107, 0, 0, 8, 0, 1105, 0, 0, 0, 0, 0, "", "Quest 'Encrusted Tail Fins' requires quest 'Hardened Shells' rewarded");
```

**Comment by Killyana** [comment]
I tested the actual chaining and it it's correct:
No need to use conditions in this case.
``` sql
SELECT * FROM quest_template_addon WHERE id IN(1104, 1105,1106,1107);

**Comment by Wyreth** [comment]
It's only correct for Martek the Exiled. Encrusted Tail Fins only requires Hardened Shells currently.

Instead, both quests require both the previous two quests to be rewarded.

It's a many-to-many relationship (two-to-two actually), which as far as I know can only be done via conditions.

**Comment by Killyana** [comment]
It's weird, with this sql both quest have the same requirements, but still 1107 is unlocked only by 1107

``` sql
UPDATE `quest_template_addon` SET `PrevQuestID`=1105 WHERE `id`=1106;
UPDATE `quest_template_addon` SET `NextQuestID`=0 WHERE `id` IN (1104, 1105);

**Comment by Wyreth** [comment]
Right, that's why I don't think it can be done with quest_template_addon alone.

You can only do many-to-one relations in this case, due to how it interacts with ExclusiveGroup to pick the next quest in the chain.

**Comment by Killyana** [comment]
This will work:
But there' something wrong, if we set PrevQuestID the check for the ExculsifGroup must be check in  this case, and now it's not the case
``` sql
UPDATE `quest_template_addon` SET `NextQuestID`=0, `PrevQuestID`=0 WHERE `id` IN (1106, 1107);
UPDATE `quest_template_addon` SET `NextQuestID`=1106 WHERE `id` IN (1104);
UPDATE `quest_template_addon` SET `NextQuestID`=1107 WHERE `id` IN (1105);

**Comment by Wyreth** [comment]
Strange, had no idea it worked like that. Good find :P
