### ISSUE TITLE
Hellfire Peninsula PvP

### ISSUE THREAD

**Issue by ckjet** [TrinityCore/TrinityCore#20450]
**Description:**

Can't check PvP towers.

**Current behaviour:**

When i come to PvP-tower progress to get point not starting.

**Expected behaviour:**

Can check PvP towers.

**Steps to reproduce the problem:**

1. Teleport to Hellfile Peinsula
2. Try to check PvP tower

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cb9b9f7247c5 2017-09-24 20:23:37 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
.gm off?

**Comment by ckjet** [comment]
Sorry, my mistake, i have disabled pvp-mode.
