### ISSUE TITLE
DB/SAI: Hulking Helboar

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20459]
**Description:**

Correct spells and emote.

**Branch(es):** both,

**TC rev. hash/commit:** 79c54b8

**TDB version:** 335.63

**Suggested fix**:
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=16880 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16880, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 11, 33908, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Hulking Helboar - On Respawn - Cast 'Burning Spikes'"),
(16880, 0, 1, 0, 2, 0, 100, 1, 34, 66, 0, 0, 11, 33909, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Hulking Helboar - Between 34-66% Health - Cast 'Hulk' (No Repeat)"),
(16880, 0, 2, 0, 2, 0, 100, 1, 1, 66, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Hulking Helboar - Between 1-66% Health - Say Line 0 (No Repeat)"),
(16880, 0, 3, 0, 2, 0, 100, 1, 1, 33, 0, 0, 11, 33909, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Hulking Helboar - Between 1-33% Health - Cast 'Hulk' (No Repeat)"),
(16880, 0, 4, 0, 8, 0, 100, 1, 34665, 0, 0, 0, 33, 16992, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, "Hulking Helboar - On Spellhit 'Administer Antidote' - Quest Credit 'Testing the Antidote' (No Repeat)");

DELETE FROM `creature_text` WHERE `CreatureID` IN (16880, 16992);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(16880, 0, 0, "%s begins to grow stronger.", 16, 0, 100, 0, 0, 0, 16646, 0, "Hulking Helboar"),
(16992, 0, 0, "%s begins to grow stronger.", 16, 0, 100, 0, 0, 0, 16646, 0, "Dreadtusk");


```

**Comment by Killyana** [comment]
Don't forget the event On Respawn is not called after an evade, in this case wwe use on Reset 25.

**Comment by Wyreth** [comment]
[This particular spell](http://www.wowhead.com/spell=33908) has no duration and cannot be dispelled (it's also invisible client-side), so casting it on respawn or on reset makes no real difference. Other mobs using this spell already cast it on respawn in DB. I can change those too if you want, but again, no real difference :P

The text for 16992 is needed because this creature can transform into Dreadtusk via quest item, and that one must say the text too. So both texts are needed, otherwise we get a DB error for missing text for that creature.

Here's [Dreadtusk](https://youtu.be/w6lo9F3fZ78?t=5) and [Hulking Helboars](https://youtu.be/Av7D49333X4?t=28) both showing the same emote.

**Comment by Killyana** [comment]
Just tested it the aura fades on evade.

**Comment by Wyreth** [comment]
Ouch. Thought it wouldn't do that. Thanks for checking, I'll change the others too.

**Comment by Wyreth** [comment]
Here:

```sql
UPDATE `smart_scripts` SET `comment`="Felboar - On Reset - Cast 'Burning Spikes'" WHERE `entryorguid`=21878 AND `id`=0;
UPDATE `smart_scripts` SET `event_type`=25, `comment`="Deranged Helboar - On Reset - Cast 'Burning Spikes'" WHERE `entryorguid`=16863 AND `id`=0;
```

Just changing comment for Felboar, only had wrong spell and event names in there.

Thought I'd post it here instead of opening a new issue. Tell me if it's alright :P

**Comment by Killyana** [comment]
Already fixed for 16863 , no need to make a commit juste for a comment but I noticed the spell 33908 doesn't proc at all.

**Comment by Wyreth** [comment]
Can't see where it was fixed. 16863 is Deranged Helboar, not Hulking Helboar. It has event_type 11, it's what I used as a base for this one.

The spell works for me, it shows in combat log if you set the "Everything" filter.

**Comment by Killyana** [comment]
Yes it procs for a player level 60 but not 80, it probably miss all the time.
I will push the update with an other commit.

**Comment by Wyreth** [comment]
I don't know if it should miss/be resisted, but finding a video of a higher level doing that quest is a nightmare. Unless someone on retail wants to try it and report back, it's probably safe to say it works as intended :)
