### ISSUE TITLE
DB/Conditions: correctly filter potential targets for Arrow Assault

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20470]
**Description:**

Updates #15083, fixes the NPCs still casting Arrow Assault on players, making an irritating noise if game audio is enabled.

**Branch(es):** both.

**TC rev. hash/commit:** 3994286

**TDB version:** 335.63

**Suggested fix**:
```sql
DELETE FROM `conditions` WHERE `SourceEntry`=53349 AND `SourceTypeOrReferenceId`=17;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 53349, 0, 0, 31, 1, 3, 29106, 0, 0, 0, 0, "", "Arrow Assault targets Death Knight Champion"),
(17, 0, 53349, 0, 1, 31, 1, 3, 29115, 0, 0, 0, 0, "", "Arrow Assault targets Rampaging Abomination"),
(17, 0, 53349, 0, 2, 31, 1, 3, 29136, 0, 0, 0, 0, "", "Arrow Assault targets Volatile Ghoul"),
(17, 0, 53349, 0, 3, 31, 1, 3, 28670, 0, 0, 0, 0, "", "Arrow Assault targets Frostbrood Vanquisher");
```

**Comment by tkrokli** [comment]
Nice fix update to an quite issue! (I wonder why I didn't give that idea more thought before)

BTW, I see you wrote `Updates #15083.` -- I presume those spawns in that phase are still disputed (and hence not fully solved by your solution).

**Comment by Wyreth** [comment]
Yeah, this doesn't close that issue - just fixes a small part of it.

The remaining issue is more complex, there should be Death Knights fighting ghouls, walking around and talking.

The whole first part of the Death Knight zone should have NPCs that basically "emulate" what players do - go to quest zones, kill ghouls and talk with NPCs. They even duel each other in the quest hub below Acherus.

**Comment by tkrokli** [comment]
Very good point. I presume you meant _humans_ where you wrote 'ghouls' in that last comment, since both the NPC death knights and ghouls are under the Lich King's command in that zone.

**Comment by Wyreth** [comment]
Right, I meant "the Scarlet crusaders should fight the ghouls". Messed up a bit :P
