### ISSUE TITLE
[3.3.5] DB/Gossip: fix gossip for NPC Mor'zul Bloodbringer

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20475]
**Description:**

[Mor'zul Bloodbringer](http://www.wowhead.com/npc=14436) is missing his gossip text.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3994286

**TDB version:** 335.63

**Suggested fix**:
```sql
SET @MENUID := xxx;
UPDATE `creature_template` SET `gossip_menu_id`=@MENUID WHERE `entry`=14436;
DELETE FROM `gossip_menu` WHERE `MenuID`=@MENUID;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(@MENUID, 6990, 0);
```

**Comment by tkrokli** [comment]
Practical (cosmetic comment) tip when posting solutions with undetermined GUIDs:
```sql
SET @MENUID := xxx; -- to be set by TC
```
