### ISSUE TITLE
DB/Gossip: fix gossip text for NPC Annie Bonn

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20472]
**Description:**

[Annie Bonn](https://wow.gamepedia.com/Annie_Bonn)'s gossip text should change based on quest status.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3994286

**TDB version:** 335.63

**Suggested fix**:
```sql
DELETE FROM `gossip_menu` WHERE `MenuID`=20001 AND `TextID`=12186;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(20001, 12186, 0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=20001;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 20001, 12186, 0, 0, 8, 0, 11471, 0, 0, 1, 0, 0, "", "Gossip text 12186 requires quest 'The Jig is Up' NOT rewarded"),
(14, 20001, 12187, 0, 0, 8, 0, 11471, 0, 0, 0, 0, 0, "", "Gossip text 12187 requires quest 'The Jig is Up' rewarded");


```

**Comment by tkrokli** [comment]
Hmm. Shouldn't this be valid for `master` (Legion) too? Or is it handled differently in TDB 720.00 ?

**Comment by Wyreth** [comment]
I'm not sure about that - Cataclysm and beyond changed too much about the way gossip works I think. A lot of them aren't even shown anymore on Legion. I don't know if it was removed or just hidden, maybe someone that knows Legion in and out can answer that.

**Comment by Killyana** [comment]
I you don't have the gossip ID just leave it empty, don't set a random one.

**Comment by Wyreth** [comment]
You're right, sorry :P old fix I made some time ago, forgot to fit it to TC standards.
