### ISSUE TITLE
DB/Creature: fix gossip flag for NPC Gjonner the Merciless

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20478]
**Description:**

Gossip text is already in DB.

**Branch(es):** both.

**TC rev. hash/commit:** 3994286

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature_template` SET `npcflag`=`npcflag`|1 WHERE `entry`=31154;


```

**Comment by tkrokli** [comment]
- http://www.wowhead.com/npc=31154/gjonner-the-merciless
- https://wow.gamepedia.com/Gjonner_the_Merciless

**Comment by Faq** [comment]
flag from sniffs?

**Comment by tkrokli** [comment]
TrinityCore rev. 3994286305e0 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Win64, Release, Static)
```sql
SELECT `entry`,`name`,`gossip_menu_id`,`npcflag` FROM `creature_template` WHERE `entry`=31154;
```
```
entry  name                   gossip_menu_id  npcflag
-----  ---------------------  --------------  -------
31154  Gjonner the Merciless           10035        2
```
Not having `npcflag = npcflag | 1` when the NPC already has a `gossip_menu_id` is self-contradictory (although sniff verification is usually the norm).
