### ISSUE TITLE
DB/Creature: wrong aggro text for Volcor

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20480]
**Description:**

The aggro text for Volcor is wrong. Also, he should say 4 different lines.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Remove wrong aggro text for Volcor and add the correct ones
DELETE FROM `creature_text` WHERE `CreatureID`=3692 AND `GroupID`=4;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(3692,4,0,"Here they come!",12,7,100,0,0,0,1250,0,"Volcor"),
(3692,4,1,"We can overcome these foul creatures!",12,7,100,0,0,0,1251,0,"Volcor"),
(3692,4,2,"We shall earn our deaths at the very least!",12,7,100,0,0,0,1252,0,"Volcor"),
(3692,4,3,"Don\'t give up! Fight to the death!",12,7,100,0,0,0,1253,0,"Volcor");

**Comment by tkrokli** [comment]
Cosmetic detail about text containing apostrophes (in contractions etc.) :
When you use double quotes ( ` " " ` ), you can skip using escape (backslash), like this:
```sql
(3692,4,3,"Don't give up! Fight to the death!",12,7,100,0,0,0,1253,0,"Volcor");
```
You only need to use escape (backslash) when the text (or comment) line is surrounded by single quotes ( ` ' ' ` ) to keep the query from being misread on DB import.

**Comment by ZenoX92** [comment]
I wish I had known that before. Thanks @tkrokli. Your comments are always appreciated.
