### ISSUE TITLE
Worldserver binary is too large

### ISSUE THREAD

**Issue by Kron4ek** [TrinityCore/TrinityCore#20495]
**Description:**

Worldserver binary size is too large

**Current behaviour:**

Currently worldserver size is 665 mb.

**Expected behaviour:**

It should be 40-50 mb.

**Steps to reproduce the problem:**

1. Just compile it.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3994286

**TDB version:**  335.63

**Operating system:** Arch Linux x86_64

**Comment by Aokromes** [comment]
not a  issue, default was changed from release to relwithdebug to get proper crashlogs.

**Comment by Kron4ek** [comment]
Oh, thanks. Missed this change.
