### ISSUE TITLE
Trainer greetings aren't implemented.

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20493]
**Description:**

Yet another obscure gossip text variation from Blizzard! Aren't you happy?

On top of the trainer window for profession and class trainers, there's a line of text.

This is always the same for class trainers, but different for profession trainers depending on what they train (and some of them have unique ones, to boot).

[A video example here](https://youtu.be/UxxcAh8iqrM?t=25).

Here are the ones I could find. Once the list is complete I'll make a pull request to implement it core-side.

```sql
Cooking trainers: "Can I teach you how to turn the meat you find on beasts into a feast?"
Kylene (19186) (Cooking trainer): "There's more than one way to cook a fish."
Fishing trainers: "I can teach you how to use a fishing pole to catch fish."
Marcia Chase (28742) (Fishing trainer): "I can teach you the finer points of fishing."
First Aid trainers: "Here, let me show you how to bind those wounds...."
Enchanting trainers: "Enchanting is the art of improving existing items through magic. " -- trailing space intended
Jewelcrafting trainers: "Greetings!  Can I teach you how to cut precious gems and craft jewelry?"
Mining trainers: "You have not lived until you have dug deep into the earth."
Skinning trainers: "It requires a steady hand to remove the leather from a slain beast."
Engineering trainers: "Engineering is very simple once you grasp the basics."
Leatherworking trainers: "Greetings!  Can I teach you how to turn beast hides into armor?"
Inscription trainers: "Would you like to learn the intricacies of inscription?"
Blacksmithing trainers: "Care to learn how to turn the ore that you find into weapons and metal armor?"
Alchemy trainers: "With alchemy you can turn found herbs into healing and other types of potions."
Linzy Blackbolt (28703) (Alchemy trainer): "The herbs of Northrend can be brewed into powerful potions."
Herbalism trainers: "Searching for herbs requires both knowledge and instinct."
Tailoring trainers: "Greetings!  Can I teach you how to turn found cloth into cloth armor?"
Riding trainers: "Hello!  Can I teach you something?"
```

What's missing:
- [x] Herbalism trainers
- [x] Alchemy trainers
- [x] Inscription trainers
- [x] Tailoring trainers
- [x] Leatherworking trainers
- [x] Blacksmithing trainers

Sources: [Inscription](https://youtu.be/8sWDEZ5WSeA?t=21), [Blacksmithing](https://youtu.be/znhkYk3qAZA?t=31).

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3994286

**TDB version:** 335.63

**Comment by malcrom** [comment]
They are sent to client but not shown by client so this is not an important issue.

**Comment by Shauren** [comment]
On master that is true, but they are shown in 3.3.5 (which is what the issue is about)

**Comment by Wyreth** [comment]
[The client shows them though, at least in WotLK](https://www.youtube.com/watch?v=UxxcAh8iqrM).

**Comment by Shauren** [comment]
Just so you know, the is implemented in master branch already - main part is 0cd5179726f91cc163910dd0806d622fe86d9a8c plus a few followup commits

The difference to 3.3.5 is that on legion you can open a different trainer depending on gossip selections but on 3.3.5 there is always only one (so TrainerId field doesn't exist)

**Comment by malcrom** [comment]
ahhhh

**Comment by Wyreth** [comment]
Good to know, thanks!

**Comment by Killyana** [comment]
This commit https://github.com/TrinityCore/TrinityCore/commit/0cd5179726f91cc163910dd0806d622fe86d9a8c  implemented the trainer greeting on master

**Comment by Ghaster** [comment]
I have been working on porting commit https://github.com/TrinityCore/TrinityCore/commit/0cd5179726f91cc163910dd0806d622fe86d9a8c and the follow-ups to the 3.3.5 branch (will be opening PR soon), however while looking at the creature_template database, all of the trainer_* related fields are just 0. Is there any point in keeping them or should i just drop all of them?

**Comment by Killyana** [comment]
"all of the trainer_* related fields are just 0"
In which table?

**Comment by illfated** [comment]
@Ghaster : if you just glanced briefly at the `creature_template` table in the `world` database, it may look that way.
But there are 842 rows of trainers with data <> 0 in those columns:
```sql
SELECT * FROM `creature_template` WHERE `trainer_type` <> 0 OR `trainer_spell` <> 0 OR `trainer_class` <> 0 OR `trainer_race` <> 0;
```

**Comment by Ghaster** [comment]
@illfated Ah i see, seems like i made in typo in my own query then.

**Comment by Killyana** [comment]
Keep this fields They are used bu some npcs, and not relate to this issue.
