### ISSUE TITLE
Player::Create: Possible hacking-attempt: Account 2 tried creating a character named 'Tester' with invalid appearance attributes - refusing to do so

### ISSUE THREAD

**Issue by Parilar** [TrinityCore/TrinityCore#20497]
**Description:**

Can't create any character

**Current behaviour:**
i try to create a character and it fails when i press create

**Expected behaviour:**

Create Character failed

**Branch(es):**
newest master

**TC rev. hash/commit:** 

TrinityCore rev. 25111b09dfaa 2017-09-25 21:34:15 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB_full_720.00_2017_04_18

**Operating system:** Linux

**Comment by Tyrelis** [comment]
Try installing a fresh client without any modified patches first.

**Comment by Fujikatoma** [comment]
It's a minimal client without any patches

**Comment by Raydor** [comment]
Did you modify playercreateinfo table? There is a really old bug that happens if your playercreateinfo has coords of an instance that throws that error.

**Comment by Fujikatoma** [comment]
fresh installation of server with client DB

**Comment by Fujikatoma** [comment]
Tested with clean Full 7.2.5 Client - Same error

**Comment by Shauren** [comment]
Missing important info - class, race and selected appearances (numbers)

**Comment by Fujikatoma** [comment]
But none of the races/classes works

**Comment by Shauren** [comment]
Cannot confirm. Tried again and creation worked fine - 25111b09dfaa7270f7b34a0973d9b6375cbb8cd2

**Comment by Fujikatoma** [comment]
@Shauren which Database did you use ?

**Comment by Shauren** [comment]
There is only one database...  TDB_full_720.00_2017_04_18 with autoupdater enabled (so everything is in)

**Comment by Frenlock** [comment]
Its happen also on 3.3.5 when you use wrong client (that client with wod models) for example but I guess that its not important .

**Comment by Fujikatoma** [comment]
I've Tested 2 clean clients. How many Rows has you playercreateinfo?

**Comment by Fujikatoma** [comment]
Creating a character with every attribute on 1 works. If i change them to higher numbers it does not work

**Comment by Shauren** [comment]
I was pressing randomize button each time and it worked

**Comment by Fujikatoma** [comment]
@Shauren How many Rows has your playercreateinfo?

**Comment by Shauren** [comment]
125

**Comment by Fujikatoma** [comment]
Same here. Smth is wrong.

**Comment by magick123** [comment]
its the appearances if i to 1 one all appearances it will create a character but if i use anything other then 1 that pops up on core and characters error on client besides DH can not make them no matter what appearance combination

**Comment by Fujikatoma** [comment]
got the same as @magick123 describes

**Comment by Fujikatoma** [comment]
@Shauren still have the issue, any other ideas ?

**Comment by Aokromes** [comment]
I sugest you to drop your databases and use one clean client.

**Comment by Fujikatoma** [comment]
@Aokromes already tried. I have a completly clean client and clean DB (yesterday compiled and db recreated)

**Comment by Fujikatoma** [comment]
TC>TC>TrinityCore rev. 55105c2f8733 2017-10-16 13:57:11 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BF (14015)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BE (14014)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F7 (14071)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Player::Create: Possible hacking-attempt: Account 1 tried creating a character named 'Test' with invalid appearance attributes - refusing to do so

**Comment by Fujikatoma** [comment]
Still open. Tested several clients and still fails

**Comment by RedSonja** [comment]
I am getting that suddenly too and shortly after it server crashes. So this must be something that has been around awhile because my core is about a year old.

**Comment by Killyana** [comment]
No longer valid
