### ISSUE TITLE
[3.3.5] Priest - Hymn of Hope

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#20504]
**Description:**

ID - 64901 Hymn of Hope
```Trigger spell (64904) Hymn of Hope. Chance = 101```

ID - 64904 Hymn of Hope
```
Effect 0: Id 137 (SPELL_EFFECT_ENERGIZE_PCT)
BasePoints = 3
Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)
Radius (Id 23) 40,00

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 20
Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)
Aura Id 35 (SPELL_AURA_MOD_INCREASE_ENERGY), value = 20, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 23) 40,00
```

Possible cause?
https://github.com/TrinityCore/TrinityCore/commit/2a462e93093d177a0e0bedf3e94ac2cf4e66a3c3

**Current behaviour:**

When you use 64901 Hymn of Hope and gain aura 64904 Hymn of Hope, if you cancel 64904 Hymn of Hope, you still having the mana increased

**Expected behaviour:**

You should lost the mana increased.

**Steps to reproduce the problem:**

1. Reduce your mana (by example 1000/6000)
2. Cast 64901 Hymn of Hope
3. When you obtain 64904 Hymn of Hope, remove this aura and see how your mana still (then if you remove all ticks of 64904 Hymn of Hope, you are full restored the mana)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4d654f548b29bf61552d9f90da8254ecea91b63e

**TDB version:**  TDB335.63

**Operating system:** Debian

**Comment by Eliminationzx** [comment]
```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -3743,7 +3743,7 @@ void AuraEffect::HandleAuraModIncreaseEnergyPercent(AuraApplication const* aurAp
     }
 
     int32 dmax = ((int32)target->GetMaxPower(powerType)) - oldMaxPower;
-    if (dmax >= 0) // increase current power by dmax on both buff application and debuff removal
+    if (dmax > 0) // increase current power by dmax on both buff application and debuff removal
```

Can you test it?

**Comment by Jildor** [comment]
it does not work @Eliminationzx 

@Treeston Can you take a look here?

**Comment by tkrokli** [comment]
Let's ask @ariel- , because Treeston is quite busy studying at the start of a new semester.

**Comment by Aokromes** [comment]
like ariel- xd

**Comment by Jildor** [comment]
I was asking @Treeston because the commit that I think caused the problem is yours 😄

**Comment by Keader** [comment]
Mana should restore only If you have aura no ?

**Comment by Jildor** [comment]
The problem is when you get tick from spell 64901, you get 64904 and increase your  min and max power  %, then if you remover 64904, you lost max power increased but min power still increased, then you get another tick of 64901 and increased another time....remove  and repeat... 😄

**Comment by ariel-** [comment]
> Let's ask @ariel- , because Treeston is quite busy studying at the start of a new semester.

Studying too, that's why I've been quite inactive.

An AuraScript should do it (remove linked aura when removing the main one)

**Comment by Treeston** [comment]
Current power should remain increased when a +%mana effect is removed (that's intentional).

Removing 64901 should remove 64904, I'd say. 64904 should not reapply after 64901 removal (64901 is what triggers 64904).

**Comment by Jildor** [comment]
No, @Treeston the problem is when you remove 64904, you get another tick from 64901 and obtain another time 64904, then, you repeat this 5 times and full mana ;)

**Comment by tkrokli** [comment]
To be fair, Treeston is saying what it should be, while you said what is actually happening. That is both sides of the same issue, "**Expected behaviour:**" and "**Current behaviour:**", which your issue is all about.

**Comment by Jildor** [comment]
Yep, then, wich is the proper work?
The aura 64904 can't be removed by right click??

**Comment by Treeston** [comment]
Removing the visible one (64904?) should remove the invisible one (64901?)

**Comment by Jildor** [comment]
I think affects nearby allys too, then, if the aura can't remove  by right click, problem solved.

I don't know what is blizzlike here.

**Comment by Keader** [comment]
Nice bug btw
Maybe remove ENERGIZE_PCT if not removed by default?

**Comment by Jildor** [comment]
seems the most coherent.

I vote for kill player if not removed by expire 😈

**Comment by Keader** [comment]
What you think about https://github.com/TrinityCore/TrinityCore/issues/20504#issuecomment-336735332 @Treeston ?

**Comment by Eliminationzx** [comment]
Same problem with `SPELL_AURA_MOD_INCREASE_HEALTH`, `SPELL_AURA_MOD_INCREASE_HEALTH_2`.
Check [Commanding Shout](http://wotlk.cavernoftime.com/spell=47440)
