### ISSUE TITLE
Creature/Misc: fix blue-and-white cube thrown by Dragonflayer Strategists

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20502]
**Description:**

[Dragonflayer Strategist](http://www.wowhead.com/npc=23956)'s [Hurl](http://www.wowhead.com/spell=42772) [Dagger](http://www.wowhead.com/spell=59685) ability is shown as a blue-and-white model due to wrong data in DB.

**Branch(es):** both.

**TC rev. hash/commit:** 035993d

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature_equip_template` SET `ItemID3`=29010 WHERE `CreatureID`=23956;

DELETE FROM `spell_custom_attr` WHERE `entry` IN (42772, 59685);
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(42772, 0x80000),
(59685, 0x80000);
```

**Comment by Aokromes** [comment]
you don't known how much time i wondered how to fix this.

**Comment by Wyreth** [comment]
It was driving me crazy too :P then found out that this custom_attr was needed for it to show the actual dagger flying.

**Comment by tkrokli** [comment]
- http://www.wowhead.com/npc=23956/dragonflayer-strategist
- http://www.wowhead.com/spell=42772/hurl-dagger
- http://www.wowhead.com/spell=59685/hurl-dagger

**Comment by Aokromes** [comment]
look the date xd https://pastebin.com/FMxw8e8R

**Comment by tkrokli** [comment]
Nice & funny coincidence. Very close to and only just before Cata release.
`09/14/2010 13:27:29`
`09/10/2011 11:51:23`

**Comment by Wyreth** [comment]
@tkrokli: he probably meant that paste's creation date, ` Sep 10th, 2011`. Six years ago :P
