### ISSUE TITLE
Core/SAI: respawn action when target is despawned

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#20517]
**Description:** When the respawn action is used on a despawned creature (corps not visible) the unit will not respawn, it's caused by dynamic spawns.

**Current behaviour:** SMART_ACTION_RESPAWN_TARGET doesn't respawn a despawned unit.

**Expected behaviour:** SMART_ACTION_RESPAWN_TARGET must respawn a despawned unit.

**Steps to reproduce the problem:**

1. Take the quest 12206 from npc=27248
2. Kill the npc (guid:106544, id=27250) and wait until the corpse disappear.
3. Compete the quest 12206 and notice the respawn action doesn't respawn the target.

I didn't test it for gobs, but it's possible that affects also gameobjects.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 035993d4cc61

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

**Comment by Killyana** [comment]
@Treeston can you take a look to this issue, it musn't be hard to fix.

**Comment by Treeston** [comment]
It kinda is, since I haven't gotten around to adding respawn by guid (ref #20099), so nothing easy for SAI to hook into. 

No chance I'll find free time right now with the new semester starting. Expect contributions in a month or two maybe.

PS: "Respawn target" is impossible now - nothing to target.

**Comment by r00ty-tc** [comment]
Yeah. I think it needs to be an action to respawn spawnid. Of course the SAI cannot be on the creature itself once it properly despawns. 

The "meantime" solution is to put the spawn ID into compatible mode group.

A usable solution now would be to make a spawngroup for the spawn, and trigger a respawn of the spawngroup via SAI from another object.

**Comment by Killyana** [comment]
It affects also gobs, example: http://www.wowhead.com/quest=13051/territorial-trespass
The event_script 19714 from: http://www.wowhead.com/spell=56788/place-stolen-eggs respawn a despawned eggs, but because of this issue it doesn't respawn.

**Comment by Killyana** [comment]
@r00ty-tc Respawning a gob with sai is working, but the gob remain spawned and doesn't despawn using the timer, you can test:
https://github.com/TrinityCore/TrinityCore/issues/20929
https://github.com/TrinityCore/TrinityCore/issues/20927

**Comment by Langerz82** [comment]
@Killyana where is the script for the quest example at the top you gave? Cant find it.

**Comment by Killyana** [comment]
This is the part that respawn the eggs: https://github.com/TrinityCore/TrinityCore/commit/de49ba1d7c20dd139c84e6fde68e07adda799285

r00ty-tc is working on this : https://github.com/r00ty-tc/TrinityCore/commit/2a7e671860883d9b38e9d09da6c58451a873ee92

**Comment by Killyana** [comment]
Partially fixed by https://github.com/TrinityCore/TrinityCore/commit/691c67f0be09095a34421043baf245fdf28e5d04
Remaining issue: For the action=70 the despawn via the action_param1 must be fixed

**Comment by Treeston** [comment]
Describe what you expect `param1` to do please.

**Comment by Killyana** [comment]
The gob X is despawned (respawntime=-1 on gameobject table) if I use the action 70 to respawn this gob I can set a value on action_param1 example 10 this will respawn the gob then after 10 secs it will despawn. It's a mechanic used by many quest.
Also used by RESPAWN_GAMEOBJECT on https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130258/scripts
SCRIPT_COMMAND_RESPAWN_GAMEOBJECT = 9

        source: WorldObject (summoner).
        datalong: Guid of the gameobject to respawn. See gameobject.guid.
        datalong2: Despawn time in seconds. If the value is < 5 seconds: 5 is used instead.

**Comment by Treeston** [comment]
> respawntime=-1

ugh

**Comment by Treeston** [comment]
that "negative respawn time" shit on gobs is on my list of stuff to kill fyi

**Comment by Killyana** [comment]
This is used by  lot of gobs like "Champions' Cache".
If we get ride of the negative respawn time, tones of scripts must be updated everywhere.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/27e7906814f2696863f5ab0488c59ffa347d8cc9
