### ISSUE TITLE
DB/Gossip: Mulgris Deepriver gossip improvements

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20521]
**Description:**

Mulgris Deepriver's gossip text should change after quest "The Wildlife Suffers Too (Part 2)" is finished. Also, he should show different gossip texts for Alliance and Horde players.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Mulgris Deepriver --> Fix gossip texts
DELETE FROM `gossip_menu` WHERE `MenuID`=2921 AND `TextID` IN (3633, 3635);
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(2921,3633,0),
(2921,3635,0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 14 AND `SourceGroup`= 2921;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14,2921,3635,0,0,8,0,4985,0,0,0,0,0,'',"Show Gossip Menu Text 3635 if Quest 'The Wildlife Suffers Too (Part 2)' is rewarded"),
(14,2921,3633,0,0,6,0,67,0,0,0,0,0,'',"Show Gossip Menu Text 3633 if Player is Horde"),
(14,2921,3634,0,0,6,0,469,0,0,0,0,0,'',"Show Gossip Menu Text 3634 if Player is Alliance");

**Comment by tkrokli** [comment]
BTW, `(2921,3634,0),` already exists in TDB 335.63 `gossip_menu`.
TC recommends to keep existing data unless the data is incorrect.

**Comment by Wyreth** [comment]
This should work :P

```sql
DELETE FROM `gossip_menu` WHERE `MenuID`=2921 AND `TextID` IN (3633, 3635);
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(2921,3633,0),
(2921,3635,0);
```

**Comment by tkrokli** [comment]
Indeed. Use multiple arguments or qualifiers in the `DELETE FROM` query so it only affects the data you insert. 👍

**Comment by ZenoX92** [comment]
So simple... I feel like a fool now. :)  Thanks master @tkrokli and master @Wyreth. Next time I'll make it right.

**Comment by tkrokli** [comment]
Just edit your original SQL (copy Wyreth's suggestion) and it will be good to go. :-)

**Comment by Wyreth** [comment]
We're all learning together, master @ZenoX92 :D

**Comment by ZenoX92** [comment]
Done it!
