### ISSUE TITLE
DB/Creature: Grimmaw spawn & waypoints

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20529]
**Description:**

Grimmaw is a rare mob furbolg that should be found patrolling the Gnarlpine camps in Teldrassil. He is not spawned.
https://wow.gamepedia.com/Grimmaw
http://www.wowhead.com/npc=14429

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**

I didn't set the creature guid, 'cause I'm not sure about the number.

```sql
-- Add Missing Spawn and Waypoint Movement for Grimmaw
SET @GUID := XXXX;
DELETE FROM `creature` WHERE `guid`=@GUID;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(@GUID,14429,1,0,0,1,1,0,0,9132.61,1651.7,1322.14,4.25837,7200,0,0,222,0,2,0,0,0,'',0);

DELETE FROM `creature_addon` WHERE `guid`=@GUID;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@GUID,@GUID*10,0,0,0,0,'');

DELETE FROM `waypoint_data` WHERE `id`=@GUID*10;
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(@GUID*10,1,9132.81,1664.76,1320.77,0,0,0,0,100,0),
(@GUID*10,2,9141.27,1690.01,1320.05,0,0,0,0,100,0),
(@GUID*10,3,9141.58,1727.6,1319.16,0,0,0,0,100,0),
(@GUID*10,4,9137.61,1753.82,1319.01,0,0,0,0,100,0),
(@GUID*10,5,9116,1771.33,1321.66,0,0,0,0,100,0),
(@GUID*10,6,9109.14,1808.41,1325.54,0,0,0,0,100,0),
(@GUID*10,7,9111.24,1823.84,1328.53,0,0,0,0,100,0),
(@GUID*10,8,9108.77,1809.06,1325.75,0,0,0,0,100,0),
(@GUID*10,9,9115.99,1771.94,1321.74,0,0,0,0,100,0),
(@GUID*10,10,9136.82,1754.07,1318.87,0,0,0,0,100,0),
(@GUID*10,11,9141.64,1726.7,1319.16,0,0,0,0,100,0),
(@GUID*10,12,9141.35,1689.69,1320.03,0,0,0,0,100,0),
(@GUID*10,13,9131.44,1665.16,1320.95,0,0,0,0,100,0),
(@GUID*10,14,9132.59,1646.61,1322.61,0,0,0,0,100,0);

**Comment by tkrokli** [comment]
Interesting. I could have sworn I saw him a year or so back when I was testing low-level night elf characters & questing, but I could be wrong. What I remember most is his strange walking speed. Not sure when or how he disappeared.

BTW, tip about posting URL links: just paste the link itself, there is no need to format it (that only messes up the URL linking properties). Only use link formatting if you want to link text instead of the plain URL.

**Comment by ZenoX92** [comment]
Maybe you mistook him for Uruson, which is another rare mob furbolg who also walks pretty fast.

**Comment by tkrokli** [comment]
Then again, there is some SQL data in the TC repo, but in the 6.x & 4.3.4 branches for this creature:
https://github.com/TrinityCore/TrinityCore/search?utf8=%E2%9C%93&q=Grimmaw&type=
I imagined that it would originate from 3.3.5, but I could be mistaken there too.

**Comment by Teppic1** [comment]
He also uses Vicious Bite according to Wowhead, he has no scripting at the moment.

**Comment by ZenoX92** [comment]
I added the script for him here  #20530.
