### ISSUE TITLE
DB/SAI: Marshal McBride does not salute the player

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20533]
**Description:**

When you take the quest 'Report to Goldshire', Marshal McBride should salute the player as he speaks.

**Current behaviour:**

He speaks, but the salute emote doesn't play. The emote is correctly configured in the database.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** 335.63

**Operating system:** Windows 10

**Suggested Fix**

``` sql
-- Marshal McBride SAI
SET @ENTRY := 197;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,19,0,100,0,54,0,0,0,67,0,3000,3000,0,0,100,7,0,0,0,0,0,0,0,"Marshal McBride - On Quest 'Report to Goldshire' Taken - Create Timed Event"),
(@ENTRY,0,1,0,59,0,100,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Marshal McBride - On Timed Event 0 Triggered - Say Line 0");
```

When you take the quest his standard dialogue emote plays, and this prevents the salute emote from playing. By delaying the speech action slightly, it will play as expected.

**Comment by Killyana** [comment]
It's better to change the emote directly in quest_details.

**Comment by Teppic1** [comment]
But the creature information is sniffed from retail isn't it? The emote on the speech seems to be correct.

**Comment by Killyana** [comment]
The emote is set in creature_text it must be executed with the text.
But emotes on quest_details data are almost always wrong.
In this case we have 2 different emotes that are executed at the same time.
And as you see here https://www.youtube.com/watch?v=8Bz6Qxv7rd8 there's no talk emote before the salute (Emote triggered on the character was added after wotlk)

**Comment by Teppic1** [comment]
Yeah that's what I meant in the original report, the quest_detail emote is played, and then when the SAI makes him speak it tries to play the salute but it fails because the quest_detail one is already played.

If changing quest_detail works then it's worth deleting the SAI as it's not doing anything.

**Comment by Solzz** [comment]
Sorry I don't have a test environment for this but I think the player should also salute, does this currently happen?

You can see a video here https://www.youtube.com/watch?v=jbgBy3TCikg

**Comment by Teppic1** [comment]
Not sure if the player salutes in retail now (I know the guard still does). Interesting find!
