### ISSUE TITLE
Warlock Imp pet inches forward after every cast

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20532]
**Description:**

The imp pet moves forward to the target between casts.

**Current behaviour:**

If you are still and the imp's target is within range, after every cast it moves a little closer, casts, and repeats, until it is in melee range.

**Expected behaviour:**

It should stay still as it casts.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 10

There was a previous bug with this issue that was resolved and closed as fixed: https://github.com/TrinityCore/TrinityCore/issues/15600

**Comment by ccrs** [comment]
typo on my implementation, will commit the correction soon

**Comment by ccrs** [comment]
almost two months later equals "soon"
seems ok 👍
