### ISSUE TITLE
3.3.5 [crash] Map::ApplyDynamicModeRespawnScaling

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20535]
**Description:**

Core crashing

**Current behaviour:**

core crashing with this crashdump as result: https://gist.github.com/dikkedeur/59b7b42ea894ed4bf603613747758b1a

**Expected behaviour:**

not crashing

**Steps to reproduce the problem:**

1.dont know

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a4e2c29fba1f 2017-10-01 23:38:08 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  

TDB 335.63

**Operating system:** 
ubuntu server 16.04

**Comment by jackpoz** [comment]
the crash happened in BattlegroundAV, could you try entering that battleground to see if the crash is reproducible ?

**Comment by dikkedeur** [comment]
strange since nobody did that battleground, i tried to enter it, no crash occurred..

**Comment by r00ty-tc** [comment]
I get the same crash, upon entering AV with spawn scaling enabled. At least just now when I tried to enter I get the crash. Pretty much the same path so far as I can see.

I don't think we should be applying scaling in BGs anyway. But, I think it's worth investigating the cause, in case it's a symptom of something important we need to consider.

**Comment by r00ty-tc** [comment]
Pretty sure the problem is here:

if (!data || !(data->*spawnGroupData*->flags & SPAWNGROUP_FLAG_DYNAMIC_SPAWN_RATE))

First off, probably a check for spawnGroupData not being null is the primary solution. Probably we should fix the method AV is using to add creatures to correctly set the default group though.

**Comment by r00ty-tc** [comment]
Give this a go. It's a bit late and possibly I made a typo/missed something. But if it still looks OK tomorrow I'll likely merge.

https://github.com/r00ty-tc/TrinityCore/commit/d734cb419a7598908ad138bb0e9573d8128574f7
