### ISSUE TITLE
DB/Creature: Rathis Tomber should only show gossip menu before quest is completed

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#20543]
**Description:**

http://www.wowhead.com/npc=16224/rathis-tomber has gossip that should only show up before you've completed his quest. Once you've completed the quest, he should say something different. _On retail_, he doesn't say anything at all, just opens the vendor menu after you've finished the quest, so behavior will need to be different based on that.

**Current behaviour:**

Tomber says the same thing both before and after you turn in the quest. (at least on 3.3.5; I don't have a 7.2.5 server spun up to test on but I am guessing it's probably applicable?)

**Expected behaviour:**

Vendor menu should just open, or new gossip should show.

Possible fix (untested): 
```sql
-- 3.3.5 only - behavior different on live
DELETE FROM `gossip_menu` WHERE `MenuID`=7162 AND `TextID`=8432;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(7162, 8432, 0);

-- should this gossip menu option be vendor icon and not gossip icon as well? I have no definitive source, gossip is not present on retail
UPDATE `gossip_menu_option` SET `OptionIcon` = 1 WHERE `MenuID` = 7162;

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7162;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 7162, 8431, 0, 0, 8, 0, 9152, 0, 0, 1, 0, 0, "", "Show gossip text if quest 'Tomber\'s Supplies' has not been rewarded.");
(14, 7162, 8432, 0, 0, 8, 0, 9152, 0, 0, 0, 0, 0, "", "Show gossip text if quest 'Tomber\'s Supplies' has been rewarded.");
```

**Steps to reproduce the problem:**

`.tele tranquillien`, talk to Rathis Tomber, `.quest reward 9152`, talk to Rathis Tomber

**Branch(es):**

both, but in different ways. fix only provided for 3.3.5a, untested

**TC rev. hash/commit:** 

1af6df4

**TDB version:** 335.63 w/updates

**Operating system:** Ubuntu 16.04

**Comment by Wyreth** [comment]
@velinath you can add the new text id to the existing gossip menu :P

Like this:
```sql
DELETE FROM `gossip_menu` WHERE `MenuID`=7162 AND `TextID`=8432;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(7162, 8432, 0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7162;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 7162, 8431, 0, 0, 8, 0, 9152, 0, 0, 1, 0, 0, "", "Show gossip text if quest 'Tomber\'s Supplies' has not been rewarded.");
(14, 7162, 8432, 0, 0, 8, 0, 9152, 0, 0, 0, 0, 0, "", "Show gossip text if quest 'Tomber\'s Supplies' has been rewarded.");
```

**Comment by velinath** [comment]
ah good call yeah. I guess I am still rusty! editing that in now.

**Comment by Wyreth** [comment]
I recall there's an old Blood Elf let's play somewhere. Maybe this quest is included. Let me check, back in a minute.

**Comment by tkrokli** [comment]
Is this page content useful in this context? https://wow.gamepedia.com/Rathis_Tomber#Quote
- Initially
```
Ah, hello there, <race>. As you can see, I'm not open for business quite yet. Now, if you'll excuse me, I'm very busy.
```

- After the quest
```
Such a delight to see you again, <class>. No, really. You're the reason that I'm making money here, hand over fist.

Now, what can I sell to you today?
```

**Comment by velinath** [comment]
Nope, that's all already handled via the gossip menus

**Comment by Wyreth** [comment]
[Here it is](https://youtu.be/rVWcFeW4hdQ?t=100). The vendor window still opens automatically when talking to him after completing the quest.

I wonder when Blizzard changed this. Probably somewhere at the end of WotLK.
