### ISSUE TITLE
DB/Creature: Meven Korgal speaks every language

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20544]
**Description:**

He has quite a few lines, all set to lang 0.

**Expected behaviour:**

He should speak common (7).

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Suggested Fix:**

``UPDATE `creature_text` SET `Language`=7 WHERE `CreatureID`=1667;``

**Comment by Wyreth** [comment]
That is probably the only Scarlet NPC that should be understandable to anyone :P at least from [this comment on Wowhead](http://www.wowhead.com/npc=1667/meven-korgal#comments:id=992300).

Do you have any screenshot or video of him, perhaps?

**Comment by r00ty-tc** [comment]
I actually updated the SAI some time back to (I think) how it is now. Here's the original issue for it

https://github.com/TrinityCore/TrinityCore/issues/14387

You'll see I used 3 (not great) videos as source for how it is now. So, to change it you should find something at least more compelling that that ;)

**Comment by Wyreth** [comment]
Found [this video](https://youtu.be/-tmQbAhtUKk?t=403), but Meven Korgal didn't say anything on aggro :|

It's probably a non-guaranteed say on aggro, like every other Scarlet crusader. Going to dig more and see what I can find.

**Comment by Teppic1** [comment]
Ok, it seems his video material was based on every one of the npcs around him speaking common, so it made sense he would too. But in one of @r00ty-tc 's vids he appears to speak out of combat in orcish so it looks like this is probably just another Blizzard inconsistency.

**Comment by Wyreth** [comment]
Yeah, almost every Scarlet NPC talks in common, with some exceptions (this one, bosses in Monastery, Onslaught in Northrend).

Not the first mess-up from Blizz :P

**Comment by Killyana** [comment]
Just check the language in broadcast_text it's always the correct one:
SELECT * FROM  `broadcast_text` WHERE `id` IN (314, 316, 317);
Language=0

**Comment by Teppic1** [comment]
If it's always right surely a simple SQL script could set all of the `creature_text` entries to whatever is in relevant `broadcast_text`?

Anyway, this seems Blizzlike so I'll close :)

**Comment by Wyreth** [comment]
The one in broadcast_text isn't always correct. For example the Scarlet crusade texts that are known to be said in common have Language=0 in broadcast_text. Which is wrong.
