### ISSUE TITLE
[3.3.5] DB/Gossip: fix gossip text for some NPCs in Western Plaguelands

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20540]
**Description:**

A few questgivers in Western Plaguelands' Horde and Alliance camps had missing conditions for their gossip texts.

[One of them](http://www.wowhead.com/npc=10837) had a BroadcastText that was changed in Cataclysm or beyond, making it invalid for 3.3.5.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1af6df4

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `npc_text` SET `BroadcastTextID0`=0 WHERE `ID`=3753;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup` IN (3223, 3183, 3228, 3184, 7385);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 3223, 3978, 0, 0, 8, 0, 5230, 0, 0, 1, 0, 0, "", "Gossip text requires quest 'Return to the Bulwark' NOT rewarded"),
(14, 3223, 3979, 0, 0, 8, 0, 5230, 0, 0, 0, 0, 0, "", "Gossip text requires quest 'Return to the Bulwark' rewarded"),
(14, 3183, 3939, 0, 0, 8, 0, 5230, 0, 0, 1, 0, 0, "", "Gossip text requires quest 'Return to the Bulwark' NOT rewarded"),
(14, 3183, 4040, 0, 0, 8, 0, 5230, 0, 0, 0, 0, 0, "", "Gossip text requires quest 'Return to the Bulwark' rewarded"),
(14, 3228, 3984, 0, 0, 8, 0, 5217, 0, 0, 1, 0, 0, "", "Gossip text requires quest 'Return to Chillwind Camp' NOT rewarded"),
(14, 3228, 3985, 0, 0, 8, 0, 5217, 0, 0, 0, 0, 0, "", "Gossip text requires quest 'Return to Chillwind Camp' rewarded"),
(14, 3184, 3940, 0, 0, 8, 0, 5217, 0, 0, 1, 0, 0, "", "Gossip text requires quest 'Return to Chillwind Camp' NOT rewarded"),
(14, 3184, 4039, 0, 0, 8, 0, 5217, 0, 0, 0, 0, 0, "", "Gossip text requires quest 'Return to Chillwind Camp' rewarded"),
(14, 7385, 8846, 0, 0, 47, 0, 9474, 65, 0, 0, 0, 0, "", "Gossip text requires quest 'The Mark of the Lightbringer' rewarded or not taken"),
(14, 7385, 8964, 0, 0, 47, 0, 9474, 10, 0, 0, 0, 0, "", "Gossip text requires quest 'The Mark of the Lightbringer' taken or completed");


```

**Comment by Killyana** [comment]
`BroadcastTextID0`=0 ?

**Comment by offl** [comment]
> One of them had a BroadcastText that was changed in Cataclysm or beyond, making it invalid for 3.3.5.

**Comment by Wyreth** [comment]
Aye. It was changed after WotLK (strangely, only the Horde one. The Alliance one was untouched). So keeping that broadcast text id makes the wrong text display.

**Comment by Killyana** [comment]
broadcast_text: -- Welcome to the front lines, $c.  While politicians may connive and scheme amongst themselves, they'll find no such luxury afforded to them here.  This is the Bulwark, and we fight for our continued survival on a daily basis here.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so... especially as we push towards Andorhal and whatever malign force that controls the Scourge there.
npc_text:       -- Welcome to the front lines, $c.  While politicians may connive and scheme amongst themselves, they'll find no such luxury afforded to them here.  This is the Bulwark, and we fight for our continued survival on a daily basis here.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so.

the extra part: "especially as we push towards Andorhal and whatever malign force that controls the Scourge there." Doesn't match with the storyline ?

**Comment by Wyreth** [comment]
That extra part was present in WotLK (check [here](https://youtu.be/u-2pjvASImI?t=145) for proof). The Alliance NPC still has it, too. Just the Horde one has that extra part missing in broadcast_text.

**Comment by Killyana** [comment]
So it's fine just update the npc_text using the one from broadcast_text

**Comment by Wyreth** [comment]
Sadly not. The broadcast_text for Horde doesn't have the ".. especially as we push towards Andorhal and whatever malign force that controls the Scourge there." part. It was there in WotLK.

**Comment by Killyana** [comment]
Can you link?:
Horde: npc_text ID=,  broadcast_text id=
Alliance: npc_text ID=,  broadcast_text id=

**Comment by Wyreth** [comment]
Horde:

- Broadcast Text ID: 6229
- Content: "Welcome to the front lines, $c.  While politicians may connive and scheme amongst themselves, they'll find no such luxury afforded to them here.  This is the Bulwark, and we fight for our continued survival on a daily basis here.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so."

- npc_text ID: 3753
- Content: "Welcome to the front lines, $c.  While politicians may connive and scheme amongst themselves, they'll find no such luxury afforded to them here.  This is the Bulwark, and we fight for our continued survival on a daily basis here.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so... especially as we push towards Andorhal and whatever malign force that controls the Scourge there."

Alliance:
- Broadcast Text ID: 6230
- Content: "Welcome to the front lines, $c.  The Kingdom of Stormwind, with the aid of its allies, has sent me here to counter the growing threat of the Scourge.  Here at Chillwind Camp, we fight for our continued survival on a daily basis.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so... especially as we push towards Andorhal and whatever malign force that controls the Scourge there."

- npc_text ID: 3754.
- Content: "Welcome to the front lines, $c.  The Kingdom of Stormwind, with the aid of its allies, has sent me here to counter the growing threat of the Scourge.  Here at Chillwind Camp, we fight for our continued survival on a daily basis.$B$BIf you've come here looking for a chance to prove yourself as a hero, then you'll find plenty of opportunities to do so... especially as we push towards Andorhal and whatever malign force that controls the Scourge there."

**Comment by Wyreth** [comment]
Wrong button, sorry.

**Comment by Killyana** [comment]
Ok.

**Comment by ZenoX92** [comment]
I already had posted a fix for some of these NPCs' gossip texts (Alchemist Arbington, High Priestess MacDonnell, Apothecary Dithers and Shadow Priestess Vandis) but your fix seems better than mine. Seems also I set the wrong quest in the conditions. (I used quest "Mission Accomplished!").

**Comment by Wyreth** [comment]
Didn't see that, or I'd have posted in your issue report :P

Yeah, just found out how it works from an [old video](https://youtu.be/b6mXDKlepxQ?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=602).

Gossip for alchemist and priest changes after the first "return to camp" quest. Gossip options for the cauldrons are unlocked gradually.

It's all part of a zone-wide event where many people have to complete the cauldron quests. Misison Accomplished! is the reward for "winning" this event. I doubt we have enough data available to fix it all. I'm fixing the other involved creatures right now.

**Comment by tkrokli** [comment]
Good job, nice detective work. Thank you for the continued contribution! 👍
(adding labels to this issue even though it is closed, for archival clarity)
