### ISSUE TITLE
DB/SAI: Felweaver Scornn summons Voidwalker on reset

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20545]
**Description:**

He is currently missing his voidwalker pet, and he flees for assistance when he should not. The shadow bolt spell is correct.

Source: pretty much all wowhead comments for the pet, plus this video for having no flee:

https://www.youtube.com/watch?v=Lokag13c8ys

http://www.wowhead.com/npc=5822/felweaver-scornn

**Branch(es):**

3.3.5

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

TDB version: 335.63

**Suggested Fix:**

```sql
-- Felweaver Scornn
DELETE FROM `smart_scripts` WHERE `entryorguid`=5822 AND `source_type`=0 AND `id`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(5822,0,1,0,25,0,100,0,0,0,0,0,11,12746,0,0,0,0,0,1,0,0,0,0,0,0,0,"Felweaver Scornn - On Reset - Cast 'Summon Voidwalker'");
```

**Comment by tkrokli** [comment]
Couple of tips to your SQL:
1. [Felweaver Scornn ](http://www.wowhead.com/npc=5822/felweaver-scornn) has already got `AIName = SmartAI` in TDB 335.63, so the update is redundant.
2. Put **```sql** on top of your code block to highlight SQL code syntax.

**Comment by Teppic1** [comment]
Done.

**Comment by tkrokli** [comment]
OK. BTW, I notice you wrote "The shadow bolt is correct." -- that means you don't need to re-add the line `"Felweaver Scornn - In Combat CMC - Cast 'Shadow Bolt'"` -- or have I misunderstood something?

**Comment by Teppic1** [comment]
It needs readding because the SQL deletes the existing SAI.

**Comment by tkrokli** [comment]
That can be fixed easily, like this:
```sql
-- Felweaver Scornn summons Voidwalker on respawn
DELETE FROM `smart_scripts` WHERE `entryorguid`= 5822 AND `source_type`= 0 AND `id`= 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(5822,0,1,0,25,0,100,0,0,0,0,0,11,12746,0,0,0,0,0,1,0,0,0,0,0,0,0,"Felweaver Scornn - On Reset - Cast 'Summon Voidwalker'");
```
(since the number of lines is reduced, it will be OK to use the creature entry in those remaining 2 places)

**Comment by tkrokli** [comment]
BTW, it is helpful for others to link the creature(s) in question when posting issue tickets:
- http://www.wowhead.com/npc=5822/felweaver-scornn
- https://wow.gamepedia.com/Felweaver_Scornn

**Comment by Teppic1** [comment]
I did put the links in. And the SQL I wrote has the exact same result as what you've written. I don't know why you are picking apart everything I'm doing when I'm submitting researched fixes.

**Comment by tkrokli** [comment]
OK, fair enough. I didn't see the links, probably because I didn't refresh the page (and therefore I didn't see the link).

**Comment by tkrokli** [comment]
Regarding your SQL, you just need to add
```
AND `id`= 1
```
 to the end of your `DELETE FROM` query to make it work as intended.

TrinityCore is just as much about learning (and in this case, not needing to remove and replace existing data) when a simple adjustment can be made. I am not trying to be disrespectful of your post, I just want to help you understand the preferred methods used in TC code -- at least the parts I know something about.

**Comment by Teppic1** [comment]
I've removed the readded line.
