### ISSUE TITLE
SMART_EVENT_TEXT_OVER doesn't seem to work anymore

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20549]
**Description:**

SMART_EVENT_TEXT_OVER doesn't seem to trigger anymore. Used to work a while ago.

**Steps to reproduce the problem:**

1. .add item 33339 (Vrykul Scroll of Ascension)
2. .go xyz 1701.9583 -4109.0215 270.6181 571
3. Use the item. Three NPCs will spawn, the one in the middle will say something and get stuck there.

This creature's script uses SMART_EVENT_TEXT_OVER.
```sql
SELECT * FROM smart_scripts WHERE entryorguid=23671;
```

**Branch(es):** tested on 3.3.5.

**TC rev. hash/commit:**  26d0110

**TDB version:** 335.63

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19186

**Comment by Wyreth** [comment]
Ouch, didn't see that one. Sorry.
