### ISSUE TITLE
DB/Gossip: Temper should have different gossip texts depending on class

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#20551]
**Description:**

Tempers (npc=17205) gossip should be _"Look around you, shaman.  Can you see the balance of the elements in the earth, the air, the water and the fire that has touched them all?"_ if a shaman talks to him and _"And why would I speak with you, $r?"_ if any other class talks to him.

**Current behaviour:**

He uses the _"Look around you, shaman.  Can you see the balance of the elements in the earth, the air, the water and the fire that has touched them all?"_ gossip all the time.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3994286+ 2017-09-28 19:33:39 +0200 (3.3.5 branch) (Unix, R
elWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 8

**Suggested Fix:**

```sql
-- Update Tempers gossip to show different texts depending on class
DELETE FROM `gossip_menu` WHERE `MenuID`=7378 AND `TextID`=8830;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES 
(7378, 8830);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=7378;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(14, 7378, 8832, 0, 0, 15, 0, 64, 0, 0, 0, 0, 0, "", "Show gossip text if class is shaman"), 
(14, 7378, 8830, 0, 0, 15, 0, 64, 0, 0, 1, 0, 0, "", "Show gossip text if class isn't shaman");
```

**Comment by tkrokli** [comment]
Thank you for following up on the shaman class. From comments elsewhere in this repository, the shaman class could use more TLC.
