### ISSUE TITLE
Core/Spells: Cyclone vs Positive Auras

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#20560]
**Description:** You can hit positive auras on friendly target with Cyclone.

**Current behaviour:** You can use spells like: Lifebloom, Rejuvenation, etc. in friendly targets affected by Cyclone. When cyclone is removed, your auras become active on target

**Expected behaviour:** All positive spells should return "IMMUNE" if friendly target is affected by Cyclone

**Steps to reproduce the problem:**

1. Apply cyclone aura in a friendly target (.aura  33786)
2. Try cast any positive spell on him (like  48441)
3. After Cyclone fade, your rejuvenation will be on target.

You can use it to "refresh" lifebloom, is a little gamebreak in pvp

PS: Is working if is negative aura, is missing some check to positve auras too.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  67795685bae686094840c8805fefbe2cf0835009

**Comment by Keader** [comment]
Change this line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2509

To: ```if (unit->IsImmunedToSpell(m_spellInfo, m_caster))```
looks fix this issue, but i dont think that this is right place

**Comment by Jildor** [comment]
I don't know why should be only delayed spells, @ariel- should know it.
Maybe should be all delayed spells and positive non delayed spells??

I found this commit: https://github.com/TrinityCore/TrinityCore/commit/9f5df023b746d324588f175e264c62205b69e165

**Comment by Keader** [comment]
ariel is buzy with university, he should not appear here in this semester xD
Btw i cant understand why is checked only to delayed spells.

**Comment by ariel-** [comment]
check UNIT_STATE_ISOLATED

**Comment by CraftedRO** [comment]
835e2918319e Seems no longer valid:


https://user-images.githubusercontent.com/24683355/214086637-2ca7a69b-cc94-4bd7-b4a4-855272b8faf7.mp4
