### ISSUE TITLE
DB/Quest: Starter Area quest timer and quest creature

### ISSUE THREAD

**Issue by kingzy21** [TrinityCore/TrinityCore#20562]
**Description:**

Quest: Scalding Mornbrew Delivery has not quest timer

**Current behaviour:**

Quest: Scalding Mornbrew Delivery has not quest timer.

**Expected behaviour:**

Quest: Scalding Mornbrew Delivery to have a quest timer

**Steps to reproduce the problem:**
Do the quest and no timer appears.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
Trinitycore rev. 9fa68855d7d0 2017-08-08 11:36:46 -0300 (3.3.5 Branch) (Win64, Release, Static) (authServer)

**TDB version:**  
TDB 335.63

**Operating system:** Windows 7, 8.1 & 10

Workaround/Offered fix: 
Change value of Timeallowed column to 300 from 0 in quest_template table quest id: 3364
Tested fix and working as expected.

-------------------------------------------------------------------------------------

**Description:**

creature: Sarkoth (Scorpion) is the same scale as standard scorpions

**Current behaviour:**

creature: Sarkoth (Scorpion) is the same scale as standard scorpions

**Expected behaviour:**

creature: Sarkoth (Scorpion) to be bigger in scale as standard scorpions

**Steps to reproduce the problem:**
Start an ORC/TROLL character and run quests or visit creature: Sarkoth (Scorpion) at his spawn location.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
Trinitycore rev. 9fa68855d7d0 2017-08-08 11:36:46 -0300 (3.3.5 Branch) (Win64, Release, Static) (authServer)

**TDB version:**  
TDB 335.63

**Operating system:** Windows 7, 8.1 & 10

Workaround/Offered fix: 
Change value of scale column to 2 from 1 in Creature_template table creature id: 3281
Tested and working as expected.

up to you guys if you implement these.

**Comment by r00ty-tc** [comment]
Springpaw Lynx vs Springpaw Cub. Scale of 1.0 is correct. They use different models.

`[11] UpdateType: CreateObject1
[11] GUID: Full: 0xF1303C0600060AFD Type: Creature Entry: 15366 Low: 396029
[11] Object Type: 3 (Unit)
<snip>
[11] OBJECT_FIELD_ENTRY: 15366/2.153235E-41
[11] OBJECT_FIELD_SCALE_X: 1065353216/1
`

Scale = 1. Looking in server, I see that they ARE smaller than the lynxs. Nothing to do here IMO.

For Sarkoth, I cannot find a sniff with a spawn. So, no way to know the actual correct scale.

**Comment by Wyreth** [comment]
Scalding Moonbrew Delivery isn't supposed to have a timer since 3.3. [Source](http://www.wowhead.com/quest=3364/scalding-mornbrew-delivery#comments:id=926999).

**Comment by kingzy21** [comment]
Cheers guys thanks for the feedback. I will look at this more and change accordingly. 99% sure Sarkoth was at least 2 scale compared to others. need to get evidence of this.

Anything i can look in to? really keen to help our with testing/db tweaking.

Cheers,

KingZy.uK

**Comment by offl** [comment]
For me he is not bigger than other scorpions.
https://youtu.be/SwLjJH8LXfc?t=663

**Comment by kingzy21** [comment]
i'm sure he should be though.

**Comment by Teppic1** [comment]
Did Princess increase in size in 3.3. as well?

**Comment by offl** [comment]
Yes, but in cata http://www.wowhead.com/npc=330/princess#comments:id=1185206

**Comment by tkrokli** [comment]
@Teppic1 : Please edit your original post and remove the section about `Springpaw Cub` vs `Springpaw Lynx` because it is not a TC issue.

**Comment by Teppic1** [comment]
@tkrokli umm...what?

**Comment by tkrokli** [comment]
As **r00ty-tc** said in https://github.com/TrinityCore/TrinityCore/issues/20562#issuecomment-334746353 , `Scale = 1. Looking in server, I see that they ARE smaller than the Lynx. Nothing to do here IMO.` So I am fairly sure that section about Springpaw Cub can be removed.

**Comment by Teppic1** [comment]
You're talking to the wrong person.

**Comment by tkrokli** [comment]
Ah,. sorry. My bad. I'll delete the "spam" comments.

**Comment by Teppic1** [comment]
Looks like the fix to Sarkoth's size was lost here because the other stuff wasn't relevant to 3.3.0.

It seems he's 2x scale in 3.3.5. Not sure if he uses the same model in Cata though.

**Comment by Aokromes** [comment]
[5] OBJECT_FIELD_ENTRY: 3281/4.59766E-42
[5] OBJECT_FIELD_SCALE_X: 1065353216/1
3.3.5a sniff shows size 1 too....

**Comment by Killyana** [comment]
Here a video https://youtu.be/7tHxdjdEZZg?t=1m8s the size is the same as the one used on TC.
It was increased on cataclysm https://youtu.be/6Tf0-nG5DUo?t=30s
As no issue is valid here I will close it.

**Comment by Teppic1** [comment]
I was referring to @offl's comment above with a vid showing double size.

**Comment by Aokromes** [comment]
well 3.3.5a sniff shows 1.0 size.

**Comment by Killyana** [comment]
In 4.3.4 the model is the same as 3.3.5 and the size=1, but the npc is bigger.
I don't know how blizz made the change on 3.3.5
