### ISSUE TITLE
[crash] 3.3.5 Spell.cpp

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20573]
**Description:**

Core crashing

**Current behaviour:**

https://gist.github.com/dikkedeur/85fd2ea1a203d5da04c5c52f0f02d136

**Expected behaviour:**

should not crash.

**Steps to reproduce the problem:**

dont know how to reproduce, 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a4e2c29fba1f 2017-10-01 23:38:08 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  TDB 335.63

**Operating system:** ubuntu sever 16.04

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20172

**Comment by tkrokli** [comment]
@dikkedeur : feel free to post your crash log in issue https://github.com/TrinityCore/TrinityCore/issues/20172 (although this can be looked up via the referenced issue link).
