### ISSUE TITLE
[3.3.5] Spells/Proc: PROC_HIT_FULL_RESIST not working

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#20570]
**Description:** Even when you got full resist, handleproc hook is not called.

**Current behaviour:** Magic Absorption talent is not working, because  PROC_HIT_FULL_RESIST never triggers handle proc https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_mage.cpp#L1060

**Expected behaviour:** PROC_HIT_FULL_RESIST calls proc hooks when I have got full resistance.

**Steps to reproduce the problem:**

1. Use a mage and a priest in duel
2. Cast mind flay on mage (using mage armor) until you get resist
3. Magic absorption will not proc (breakpoint in script will not be triggered)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 98c363154ad6906fb9cfaeb2ac13b77c8540c73d

**Comment by Keader** [comment]
Missing some ```caster->ProcSkillsAndAuras``` call inside of  ```Spell::DoAllEffectOnTarget``` ?

**Comment by Keader** [comment]
@ariel- when you have time xD

**Comment by ariel-** [comment]
Not a generic issue, only bad entry in db
