### ISSUE TITLE
Minigob Manabonk on speed

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#20575]
**Description:**

Minigob Manabonk script is broken somehow.

**Current behaviour:**

He comes back within a second, over and over again. Thus he produces a lot of mail also. The only way out is for all players to leave Dalaran. Sometimes he appears additionally at strange times.

**Expected behaviour:**

He should appear according to the event data in the db (it's ok), as it was some time ago (bevor the new EncounterAI?).

**Steps to reproduce the problem:**

1. Be in Dalaran at the event time (10 and 40 minutes past the hour).
2. Be there any other time and be unlucky.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 035993d4cc61
**TDB version:** according to hash
**Operating system:** Windows 10 64bit

**Comment by r00ty-tc** [comment]
https://github.com/TrinityCore/TrinityCore/pull/20565 arriving tomorrow all going well :)

**Comment by TecDian** [comment]
Hurray!
