### ISSUE TITLE
go_brewfest_music faulty logic

### ISSUE THREAD

**Issue by killerwife** [TrinityCore/TrinityCore#20589]
**Description:**

Gameobject script go_brewfest_music is supposed to emulate the sending of music during Brewfest.
It is governed by two very ugly lines of code:
```cpp
if (me->GetAreaId() == SILVERMOON || me->GetAreaId() == UNDERCITY || me->GetAreaId() == ORGRIMMAR_1 || me->GetAreaId() == ORGRIMMAR_2 || me->GetAreaId() == THUNDERBLUFF || me->GetAreaId() == SHATTRATH)
```
and 
```cpp
if (me->GetAreaId() == IRONFORGE_1 || me->GetAreaId() == IRONFORGE_2 || me->GetAreaId() == STORMWIND || me->GetAreaId() == EXODAR || me->GetAreaId() == DARNASSUS || me->GetAreaId() == SHATTRATH)
```
What this causes is that both statements get executed for SHATTRATH, and that means players get sent 2 packets with music, one for ally one for horde. This obviously needs to be split up into a switch case.
My personal solution would be to handle all zones except shattrath by sending one packet, and shattrath by sending the respective faction packet like in Midsummer.

**Expected behaviour:**

Send one packet to player at a time.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  01d364aedbda3cdad84fcb2d5a8aa6bd7bf1a38b

**TDB version:**  01d364aedbda3cdad84fcb2d5a8aa6bd7bf1a38b

**Comment by Kittnz** [comment]
@killerwife  thanks for the report
