### ISSUE TITLE
[3.3.5] Spells with wrong order of SpellMod application

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#20597]
**I'm not 100% sure about it, i can missunderstand something**

**Description:**

Spells with Effect:

SPELL_EFFECT_WEAPON_DAMAGE,
SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL,
SPELL_EFFECT_NORMALIZED_WEAPON_DMG,
SPELL_EFFECT_WEAPON_PERCENT_DAMAGE,

Are handled in: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L3072

Checking spells like Sinister Strike (Rogue) and Crusader Strike (Paladin), both spells has talents that should change the amount getted by BasePoints of this spells.
This amount changes appear in spell tooltip, like Sinister Strike after apply Blade Twisting (31126) should change BasePoints to 198 (+10%)...

**Issue is:** This BasePoints changes, should be applied before damage is calculated. In current script it's calculated after, in this line:  https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L3350

On Crusader Strike case, with talents like The Art of War (53488) Crusader Strike should: "An instant strike that causes 93% weapon damage". If you debug the current code, is used 75% of weapon damage, and spell mods is added on damage after...

Inverting the order of SPELLMOD_DAMAGE apply (to inside of this for: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L3325
) instead after, looks more close to the value of DrDamage.

**Steps to reproduce the problem:**

1. Make a Paladin, put points in The Art of War
2. Make damage using Crusader Strike

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 98c363154ad6906fb9cfaeb2ac13b77c8540c73d

**Comment by Killyana** [comment]
If I'm not wrong last changes on this were made by ariel.
