### ISSUE TITLE
(7.2.5)arena season does not work

### ISSUE THREAD

**Issue by skillever** [TrinityCore/TrinityCore#20590]
**Description:**

hello, I have a problem activating arena season 19 - legion season 1 .. please help. I'm doing something wrong with me or there is a problem with the trinity core .... worldconfig is set up poorly, arena seeson ID 19, and arena season enable 1 ....

**Current behaviour:**
chyba ve hře- arena is temporary disabled ..... 

**Expected behaviour:**

open arena season 19 - Legion season 1

**Steps to reproduce the problem:**

**Branch(es):**

master legion

**TC rev. hash/commit:** 

TrinityCore rev. 1292a987f175+ 2017-10-09 21:23:52 +0200 (HEAD branch) (Win64, Debug, Static) (bnetserver)
<Ctrl-C> to stop.

**TDB version:**  
TBD720 + news updates
**Operating system:** 
windows 10

**Comment by Aokromes** [comment]
#19766
