### ISSUE TITLE
[quest] A Race Against Time

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#20608]
**Description:**
After using the bomb and killing Salrand, the chest containing the Broken Key spawns.
This chest is currently a single use and despawns immediately.
It should stick around and be lootable to everyone until it despawns on a timer.
http://www.wowhead.com/quest=11671/a-race-against-time#comments:id=332638:reply=56781

I bet this quest alone cost Northcraft half its population on day one, as it was a total clusterfuck. It was the last straw for me at least.
The pvp'ers had fun tho.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 1750ca5 2017-10-11 00:02:37 +0200 (HEAD branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:** 335.63

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12842
