### ISSUE TITLE
[3.3.5] Odd quest reputation rewards

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#20600]
**Description:**
Odd reputation rewards with 2 quest/repeatable-quest pairs, maybe more.
[The Sporelings' Plight](https://wow.gamepedia.com/Quest:The_Sporelings%27_Plight) rewarded 250 rep with Sporeggar (should be 750).
[More Spore Sacs](https://wow.gamepedia.com/Quest:More_Spore_Sacs) rewarded 750 rep with Sporeggar.
[Fierce Enemies](https://wow.gamepedia.com/Quest:Fierce_Enemies) rewarded 500 rep with Kurenai.
[More Warbeads](https://wow.gamepedia.com/Quest:More_Warbeads) rewarded 250 rep with Kurenai (should have been 500).

The odd part is that all 4 of these had RewardFactionValue1 set to 5 and RewardFactionOverride1 to 0 in the database.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 1750ca501f7a 2017-10-11 00:02:37 +0200 (HEAD branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**
335.63

**Operating system:**
Win 7

**Comment by Wyreth** [comment]
Can confirm.

Old Wowhead links:
- [The Sporelings' Plight](http://web.archive.org/web/20100409120414/http://www.wowhead.com/quest=9739)
- [More Warbeads](http://web.archive.org/web/20100411071755/http://www.wowhead.com:80/quest=10477)

**Comment by Aokromes** [comment]
maybe it needs data on reputation_spillover_template

**Comment by kaldown** [comment]
```
UPDATE quest_template SET RewardFactionValue1 = 7 WHERE id = 10476;
UPDATE quest_template SET RewardFactionValue2 = 7, RewardFactionID2 = 970 WHERE id = 9739;
```
It would be like:
Sporegarr increased erputation by 250
Sporegarr increased erputation by 500
Which in sum gives desired 750.
Will prepare screenshots.

**Comment by kaldown** [comment]
Ok, so in bounded PR I've got some useful information, and @tkrokli asked me to move conversation here.
According https://community.trinitycore.org/topic/58-wdb-fields/, I have no rights to modify RewardFactionValueID, but I can do it with RewardFactionOverride.
The problem is, that when RewardFactionOverride used for a repratable quest (id=10476 from this issue), you wouldn't get bonuses. 
So I don't know what to do after all.

Would be very appreciate, if someone guides me what to next (or even shows me an issue which could be accomplished by a completely newbie)

Thanks.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20600#issuecomment-340322210

**Comment by Aokromes** [comment]
Also, 9739 already have RewardFactionValue1 = 970  no need to set RewardFactionValue2

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `reputation_reward_rate` ORDER BY `faction`;
```
```
faction  quest_rate  quest_daily_rate  quest_weekly_rate  quest_monthly_rate  quest_repeatable_rate  creature_rate  spell_rate
-------  ----------  ----------------  -----------------  ------------------  ---------------------  -------------  ----------
    529           1                 1                  1                   1                      1              1           2
    576           4                 1                  1                   1                      4              1           1
    609           1                 1                  1                   1                      1              1           2
    941           2                 1                  1                   1                      1              1           1
    970           1                 1                  1                   1                      3              1           3
    978           2                 1                  1                   1                      1              1           1
   1037         1.3               1.3                1.3                 1.3                    1.3              1           1
   1052         1.3               1.3                1.3                 1.3                    1.3              1           1
   1073           1                 2                  1                   1                      1              2           2
   1090         1.3               1.3                1.3                 1.3                    1.3            1.3         1.3
   1091         1.3               1.3                1.3                 1.3                    1.3            1.3         1.3
   1098         1.3               1.3                1.3                 1.3                    1.3            1.3         1.3
   1104           1                 2                  1                   1                      1              2           2
   1105           1                 2                  1                   1                      1              2           2
   1106         1.3               1.3                1.3                 1.3                    1.3            1.3         1.3
   1119           1                 1                  1                   1                      1            1.3         1.3
```

**Comment by kaldown** [comment]
@Aokromes it won't work if you wouldn't tell for which faction you need `RewardFactionValue2`. Or maybe I didn't reload server properly to test that.

**Comment by kaldown** [comment]
@tkrokli am I right, that changing `reputation_reward_rate` would touch every quest reputation rate for particular faction? I think we don't need to increase reward for all quests, but for particular quest with `id = 9739`. Is it possible to increase reward for only one quest instead?

**Comment by tkrokli** [comment]
Good question, I don't know the answer to that. Sorry that I don't know more about it.
Maybe @Killyana or  @dr-j or someone with quest + rep DB knowledge can tell us.

**Comment by PolarCookie** [comment]
```sql
UPDATE `reputation_reward_rate` SET `quest_rate` = 3 WHERE `faction` = 970; --Sporeggar
UPDATE `reputation_reward_rate` SET `quest_repeatable_rate` = 2 WHERE `faction` IN (941, 978); --Kurenai and Mag'har
```

This fixes the issue, I checked over 
https://wow.gamepedia.com/Sporeggar
https://wow.gamepedia.com/Kurenai
and it all adds up now.
