### ISSUE TITLE
Server Restart commands

### ISSUE THREAD

**Issue by Frenlock** [TrinityCore/TrinityCore#20612]
**Description:**

> Syntax: .server restart #delay Restart the server after #delay seconds. Use #exit_code or 2 as program exit code.

Currently the restart commands work as shoutdown ones .

**Current behaviour:**

server does not restart automatically (without a restarter)

**Expected behaviour:**

server shoud be able to restart automatically

**Steps to reproduce the problem:**

1. start the server
2. restart the server
3. it will never relaunch again automatically .

**Branch(es):**

3.3.5, master or both

**TC rev. hash/commit:** 

TrinityCore rev. 1750ca501f7a 2017-10-11 00:02:37 +0200 (3.3.5 branch) (Win32, Release, Static)

**TDB version:**  TDB_full_335.63_2017_04_18
**Operating system:** Windows 10 x64

**Comment by Aokromes** [comment]
you need external software to handle restart codes.

**Comment by r00ty-tc** [comment]
As an example (debug version):

```Bash
/usr/bin/gdb -x=~/PTR-gdb -batch bin/worldserver
mv temp.gdb Crashes/log$(date +\%Y-\%m-\%d-\%H-\%M-\%S).log
while [ $? -eq 2 ]
do
/usr/bin/gdb -x=~/PTR-gdb -batch bin/worldserver
/bin/mv temp.gdb Crashes/log$(date +\%Y-\%m-\%d-\%H-\%M-\%S).log
done
```

Release:

```Bash
bin/worldserver
while [ $? -eq 2 ]
do
bin/worldserver
done
```

**Comment by Aokromes** [comment]
he is using windows xD

**Comment by r00ty-tc** [comment]
Then, there's no need to restart. No-one hosts seriously on windows, right? :P

**Comment by Frenlock** [comment]
Then, I'm not serious , windows f t w :D
