### ISSUE TITLE
[crash] 3.3.5 boss_selin_fireheart

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#20614]
**Description:**

core crashing

**Current behaviour:**
https://gist.github.com/dikkedeur/93c064dfb372daa61d93264953e5f9a6

**Expected behaviour:**

should not crash

**Steps to reproduce the problem:**

1.no idea

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a4e2c29fba1f 2017-10-01 23:38:08 +0200 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:** TDB 335.63

**Operating system:** ubuntu server 16.04 lts

**Comment by jackpoz** [comment]
Caused by the ugly list<Creature*> at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/MagistersTerrace/boss_selin_fireheart.cpp#L262 , it needs to be changed to list<ObjectGuid>

**Comment by irgc** [comment]
hi jackpoz 

please apply on tc

**Comment by tkrokli** [comment]
@irgc : Have you tested changing that keyword and found it to be a solution to this crash?

**Comment by r00ty-tc** [comment]
@tkrokli you need to change the storage, and the places it adds to the storage, and wherever the storage is used to then find the object by GUID to use. Not just a case of changing one line unfortunately.
