### ISSUE TITLE
[3.3.5] Core/Battleground: Getting double honor/kills

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#20616]
**Steps to reproduce the problem:**

1. You need use 3 characters, 2 of the same faction, 1 opposition faction
2. Put 2 characters in Party and join some bg (using join as party button) (.debug bg can help you), after join with oher faction character
3. In preparation time, force 1 of character (in party) disconect (like trying login again).
4. Login back this character.

You will notice that when you try talk something in any channel (like /bg) will show 2 times what you wrote...
Let's Bg begin...
When you kill someone in this battleground, you will get double of honor, double of kills (you can see using kill achievement), and you will lose double of mana using spells.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 558382ed6d87942603fa309b16a30e64d07bb305

**Comment by Jildor** [comment]
Oh!! good catch!
it has caused me a lot of headaches to try to reproduce this 😄

**Comment by Keader** [comment]
9f943e284f2418e8e90d1bcf5d0a5fbf073580f3

**Comment by Jildor** [comment]
@Keader @sirikfoll 
the power part still bug
>and you will lose double of mana using spells.

**Comment by tkrokli** [comment]
Maybe open a new ticket for it, or reference this page when writing a solution for that mana / power issue.

**Comment by Jildor** [comment]
Done xD
