### ISSUE TITLE
[3.3.5] Crash MapManager::GenerateInstanceId() with -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by Ikfes** [TrinityCore/TrinityCore#20634]
**Description:**

The server crash when a player enters to Naxxramas.

**Current behaviour:**

The server crash when a player enters to Naxxramas.

https://gist.githubusercontent.com/Ikfes/f76bb9f3867227c5a572b9e4698efc39/raw/c86a77977c530051ae19855fc9b438db9af4870e/crashlog

**Expected behaviour:**

Player should enter in the instance and the server shouldn't crash

**Steps to reproduce the problem:**

1. Compile with -DCMAKE_BUILD_TYPE=Debug
2. Enter in an instance

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

Revision: TrinityCore rev. 1aafa2c

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by Ikfes** [comment]
desc characters2.instance;

'id', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'map', 'smallint(5) unsigned', 'NO', 'MUL', '0', ''
'resettime', 'bigint(20) unsigned', 'NO', 'MUL', '0', ''
'difficulty', 'tinyint(3) unsigned', 'NO', 'MUL', '0', ''
'completedEncounters', 'int(10) unsigned', 'NO', '', '0', ''
'data', 'tinytext', 'NO', '', NULL, ''

desc characters2.character_instance;

'guid', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'instance', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'permanent', 'tinyint(3) unsigned', 'NO', '', '0', ''
'extendState', 'tinyint(2) unsigned', 'NO', '', '1', ''

desc characters2.group_instance;

'guid', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'instance', 'int(10) unsigned', 'NO', 'PRI', '0', ''
'permanent', 'tinyint(3) unsigned', 'NO', '', '0', ''

**Comment by Ikfes** [comment]
#19931

had same issue but that was fixed in commit #9d37c2b

**Comment by Shauren** [comment]
Did you have `Warning: GetUInt64() on non-bigint field` in your startup log? (needed logger is `sql.sql`, level WARN)

**Comment by Shauren** [comment]
While at it, I would like to know your mysql client and server versions (MySQL client library: X and MySQL server ver: X, both printed at worldserver startup) as well as result of this query

Please run this query from mysql console started with `mysql --column-type-info` arg, it will print extra info before result which is more important to this issue than the result itself
`SELECT IFNULL(MAX(id), 0) FROM instance`

**Comment by Ikfes** [comment]
> Did you have Warning: GetUInt64() on non-bigint field in your startup log? (needed logger is sql.sql, level WARN)

No such error or warning in server logs after enabling WARN 4 setting from sql.sql from worldserver.conf

> While at it, I would like to know your mysql client and server versions (MySQL client library: X and MySQL server ver: X, both printed at worldserver startup)

I can't see such info. maybe my logging settings is wrong.

> Please run this query from mysql console started with mysql --column-type-info arg, it will print extra info before result which is more important to this issue than the result itself
> SELECT IFNULL(MAX(id), 0) FROM instance

MariaDB [characters2]> SELECT IFNULL(MAX(id), 0) FROM instance;
Field   1:  `IFNULL(MAX(id), 0)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     11
Max_length: 2
Decimals:   0
Flags:      NOT_NULL BINARY NUM


+--------------------+
| IFNULL(MAX(id), 0) |
+--------------------+
|                 29 |
+--------------------+
1 row in set (0.00 sec)

**Comment by Shauren** [comment]
for versions you need log set to at least INFO

**Comment by Ikfes** [comment]
MySQL client library: 10.1.26-MariaDB
MySQL server ver: 10.1.26-MariaDB-0+deb9u1

**Comment by Ikfes** [comment]
I recompiled without debug and it works fine now.. so thats definitely the issue.

**Comment by Shauren** [comment]
You definitely used -DWITH_COREDEBUG
-DCMAKE_BUILD_TYPE=Debug has nothing to do with it

**Comment by tkrokli** [comment]
@Ikfes : if you can test again without `-DWITH_COREDEBUG` we may be able to settle this issue and find out if it is just a configuration problem (not the source).

Make sure you follow Shauren's advice too when testing again.

**Comment by Shauren** [comment]
Ok, what about this query `SELECT CAST(IFNULL(MAX(id), 0) AS UNSIGNED) FROM instance;` - same deal with --column-type-info

**Comment by Faq** [comment]
No response means no problem i guess. Close?

**Comment by tkrokli** [comment]
Closing this issue based on the use of unsupported optional software & compile parameters:
(https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements)
(https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977309/Linux+Core+Installation#LinuxCoreInstallation-Compilingthesourcecode)
