### ISSUE TITLE
DB/Creature: fix position for two NPCs in Silvermoon

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20654]
**Description:**

[Nimrida](http://www.wowhead.com/npc=18232) and [Keyanomir](http://www.wowhead.com/npc=18231) should be outside in Murder Row. Instead they were spawned nearby the Warlock trainers.

**Branch(es):** both.

**TC rev. hash/commit:** f909d4f

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature` SET `position_x`=9715.041, `position_y`=-7311.676, `position_z`=24.84278, `orientation`=4.869469 WHERE `id`=18232;
UPDATE `creature` SET `position_x`=9714.112, `position_y`=-7313.333, `position_z`=24.8485, `orientation`=1.134464 WHERE `id`=18231;


```

**Comment by Kittnz** [comment]
Are these sniffed values?

**Comment by offl** [comment]
Maybe he should walk between two or more points? Look at map.
http://www.wowhead.com/npc=18231/keyanomir#comments:id=1338259:reply=238630

**Comment by Wyreth** [comment]
I sniffed those two's positions personally before 7.3. Tried standing around them for a few hours to see if they had waypoints, but nope.

Maybe it was removed, it only happens on a certain time, or something else.

**Comment by offl** [comment]
> Maybe it was removed, **it only happens on a certain time**, or something else.

[Maybe](http://www.wowhead.com/npc=18231/keyanomir#comments:id=1342829).
But there is no reason to change his current position, because the old position was sniffed ><

**Comment by Wyreth** [comment]
@offl: this position is sniffed too, it's the place the NPCs are most active (they walk to other destinations, then come back there and pause).

Current TDB position was sniffed in the middle of a WP, it makes no sense to leave them standing where they shouldn't be standing still :P

**Comment by offl** [comment]
> Current TDB position was sniffed in the middle of a WP, it makes no sense to leave them standing where they shouldn't be standing idle :P

Well, then it's a big reason to apply your fix. I thought currently he stands at the end of his path.
