### ISSUE TITLE
DB/Misc: Stillpine Hold creature updates

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#20669]
**Description:**

- [Stillpine Defenders](http://www.wowhead.com/npc=17432/stillpine-defender), [Stillpine Hunters](http://www.wowhead.com/npc=17439/stillpine-hunter) and [Stillpine Defender Corpses](http://www.wowhead.com/npc=17437/stillpine-defender-corpse) are using the wrong models (they shouldn't be black/brown) 
- Most of the Stillpine Defenders/Hunters shouldn't move.
- Lost of NPCs in Stillpine Hold have a ranged weapon in creature_equip_template which they don't use.
- Delete all [Stillpine Raiders](http://www.wowhead.com/npc=17495/stillpine-raider) (only supposed to spawn after completing [quest=9573](http://www.wowhead.com/quest=9573/chieftain-oomooroo))

**Branch(es):**

Both

**TC rev. hash/commit:** 

TrinityCore rev. b507acf1c04f+ 2017-10-20 10:57:47 -0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**TDB version:**  335.63

**Operating system:** Windows 8

**Suggested Fix:**

```sql
-- Stillpine Hold overhaul
SET @CGUID := XXX; -- Need new GUID

DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID + 1 AND @CGUID + 5;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES 
(@CGUID + 1, 17432, 530, 0, 0, 1, 1, 0, 1, -3359.00, -12295.73, 21.895, 3.4643, 300, 0, 0, 176, 0, 0, 0, 0, 0, 0),
(@CGUID + 2, 17432, 530, 0, 0, 1, 1, 0, 1, -3362.50, -12403.92, 24.512, 2.2446, 300, 0, 0, 176, 0, 0, 0, 0, 0, 0),
(@CGUID + 3, 17432, 530, 0, 0, 1, 1, 0, 1, -3380.84, -12411.39, 19.330, 2.4017, 300, 0, 0, 176, 0, 0, 0, 0, 0, 0),
(@CGUID + 4, 17437, 530, 0, 0, 1, 1, 0, 1, -3339.58, -12352.24, 22.844, 5.8677, 300, 0, 0, 176, 0, 0, 0, 0, 0, 0),
(@CGUID + 5, 17438, 530, 0, 0, 1, 1, 0, 0, -3336.31, -12352.47, 23.182, 3.6591, 300, 0, 0, 176, 0, 0, 0, 0, 0, 0);

-- Update NPC movement, delete wrong models and ranged weapons, correct angle/distance of formation
UPDATE `creature` SET `spawndist`=0, `MovementType`=0 WHERE `guid` IN (62912, 62911, 62913, 62914, 62878, 62877, 62895, 62893, 62894, 62875, 62874, 62885);
UPDATE `creature_formations` SET `dist`=5, `angle`=270 WHERE `memberGUID`=62891;
UPDATE `creature_template` SET `modelid2`=6802, `modelid3`=0, `modelid4`=0 WHERE `entry` IN (17432, 17439, 17437);
UPDATE `creature_addon` SET `bytes2`=4097 WHERE `guid`=62892;
UPDATE `creature_equip_template` SET `ItemID3`=0 WHERE `CreatureID` IN (17432, 17443, 17446, 17445, 17444, 17440, 17442, 17441) AND `ID`=1;

-- Delete four NPCs and all Stillpine Raiders
DELETE FROM `creature` WHERE `guid` IN (62884, 62883, 60792, 60777);
DELETE FROM `creature` WHERE `id`=17495;
```

**Comment by offl** [comment]
>```sql
>UPDATE `creature_template` SET `modelid2`=6802, `modelid3`=0, `modelid4`=0 WHERE `entry` IN (17432, 17439, 17437);

Why..

**Comment by Serpaa** [comment]
That was a long time ago. If I remember correctly I always checked the TBC zones on the official server and this one looked weird because they had all sorts of different fur colours on Trinity.

Like in this video: https://www.youtube.com/watch?v=-d1WYHaV0dY they are all white.
If thats wrong or I shouldn't have updated the creature_template then im sorry. Dunno if that table is completly sniffed.

But that was my reason back then.
