### ISSUE TITLE
DB/Creature: Deepstrider Giant/Searcher has no weapon visible while pathing

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#20671]
**Description:**

The Deepstrider Giant and Deepstrider Searcher should have their weapon visible while pathing.

http://www.wowhead.com/npc=4686/deepstrider-giant
http://www.wowhead.com/npc=4687/deepstrider-searcher

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b507acf1c04f+ 2017-10-20 10:57:47 -0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**TDB version:**  335.63

**Operating system:** Windows 8

**Suggested Fix:**

```sql
-- Fix Deepstrider Giant/Searcher's weapon while pathing 
UPDATE `creature_addon` SET `bytes2`=1 WHERE `guid` IN (27937, 27938); 
```

**Comment by Killyana** [comment]
Spawns in this area are a mess.
