### ISSUE TITLE
DB/Gameobject: Ghostlands - Missing bonfire in Amani Catacombs

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20688]
**Description:**

There should be a bonfire. There is no bonfire.

https://i.ytimg.com/vi/7LNmHnGdhPI/hqdefault.jpg

https://youtu.be/_R5IaZJoUxw?t=32s

**Branch(es):**

both

**TC rev. hash/commit:** 

TrinityCore rev. 21bd52cb995b+ 2017-10-22 21:37:38 +0200 (3.3.5 branch) (Unix, R
elWithDebInfo, Static) (worldserver-daemon)

**TDB version:** 335.63

**Patch:**

```sql
SET @OGUID      := XXX; -- need a new gameobject GUID

-- Missing bonfire in Amani Catacombs
DELETE FROM `gameobject` WHERE `id`='192612' AND `guid` = @OGUID;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`) VALUES
(@OGUID, 192612, 530, 7567.64, -7359.47, 161.734, 2.429119);
```

**Comment by Kittnz** [comment]
this isn't from a sniff is it

**Comment by Aokromes** [comment]
(@OGUID+91, 192612, 530, 3433, 3509, 1, 1, 0, 7567.479, -7359.604, 161.8884, 3.159062, 0, 0, -0.9999619, 0.008734641, 120, 255, 1, 14545), -- 192612

**Comment by Teppic1** [comment]
@Kittnz nope, but I guess that other is :p
