### ISSUE TITLE
DB/Gossip: Thotar

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20696]
**Description:**

Thotar should have 2 different gossip texts, one for hunters, and one for non-hunters. Currently, he only have one.
Also, Thotar should not start quest "The Hunter's Path".

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Thotar --> Fix Gossip Text
DELETE FROM `gossip_menu` WHERE `MenuID`=4017 AND `TextID`=4973;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(4017,4973,0);

UPDATE `conditions` SET `SourceEntry`=4973 WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=4017 AND `ConditionValue1`=1531;

-- Thotar --> Remove wrong queststart
DELETE FROM `creature_queststarter` WHERE `id`=3171 AND `quest`=6069;

**Comment by tkrokli** [comment]
Aha, right. He should not **start** it, but he ends it (3.3.5).
