### ISSUE TITLE
DB/Creature: Moonstalker Runt max level is too high

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20692]
**Description:**

This NPC currently ranges from 10-17. It should be 10-12.

It seems it has been confused with the Moonstalker Sires (17-18).

http://www.wowhead.com/npc=2070/moonstalker-runt#comments
http://www.vranx.com/forums/index.php?topic=7648.0

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 21bd52cb995b+ 2017-10-22 21:37:38 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** 335.63

**Suggested Fix:**

```sql
UPDATE `creature_template` SET `maxlevel`=12 WHERE `entry`=2070;
```

**Comment by offl** [comment]
More fixes for this NPC: https://github.com/classicdb/database/issues/573 https://github.com/Looking4Group/L4G_Core/issues/3775

**Comment by tkrokli** [comment]
Possible alternative source:
- http://web.archive.org/web/20100729002604/http://www.wow-petopia.com:80/look/tigerskinblackstriped.html

Note the detail "Can be tamed only when not controlled by a Moonstalker Matriarch."
