### ISSUE TITLE
Ulduar- Hodir Trash

### ISSUE THREAD

**Issue by blub5000** [TrinityCore/TrinityCore#2070]
The waypoints from the trash before Hodir is missing. Some Jormungars were behind or under the wall. 

rev: 041e893

**Comment by danlapps** [comment]
I provided a full Ulduar sniff couple weeks ago, not sure if those data were included but Worth checking.

**Comment by Rushor** [comment]
problem is that the wpcreator isn't working currently, a manually adding and coping these coords is too hard

**Comment by Killyana** [comment]
There's no wp for this npcs they must spawn when a Snow Mound is approached. The Trigger is a vehicle with 12 sits it will eject 1 Winter Jormungar  every 4 secs when the "trap" is activated.

**Comment by Aokromes** [comment]
DELETE FROM `creature` WHERE `id` = 34137;
