### ISSUE TITLE
[ASSERT] m_sharedVision.empty()

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#20719]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
*((volatile int*)nullptr) = 0

**Current behaviour**: Tell us what happens
Not sure why is this happening.

- https://pastebin.com/E4LE7iBn

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
4eababa

**TDB version**:  
62

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by jackpoz** [comment]
>This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.
