### ISSUE TITLE
DB/SAI: Lazy Peons are heard too widely

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#20712]
**Description:**

When a Lazy Peon says "work, work!" the sound is played at full volume practically across the whole zone. Changing the action's target to nearby players fixes this.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. caf3549+ 2017-10-24 22:06:20 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** 335.63

**Suggested Fix:**

```sql
-- Only players within 20 yards will hear the sound
UPDATE `smart_scripts` SET `target_type`=18, `target_param1`=20 WHERE `target_type`=1 AND `action_type`=4 AND `action_param1`=6197;
```

**Comment by robinsch** [comment]
WORK WORK!

**Comment by tkrokli** [comment]
👍 Thank you for looking into that issue. I kept wondering why I kept hearing peons while not being within view distance of any of them in the Valley of Trials, but I never made any notes to look further into that. 😄

**Comment by Teppic1** [comment]
The wolves in Elwynn Forest do it too, it seems if you use ``TARGET_SELF`` the npcs play the sound over a megaphone.

**Comment by Teppic1** [comment]
Not sure if that needs another issue, but the same fix for 'Gray Forest Wolf'.

```sql
UPDATE `smart_scripts` SET `target_type`='18', `target_param1`='20' WHERE `entryorguid`=1922 AND `source_type`=0 AND `id`=0;
```

**Comment by Killyana** [comment]
Gray Forest Wolfs doesn't spawn the sound, if you talking about the sound loudness not reduced by the distance it was implemented in mop or another extension.

**Comment by r00ty-tc** [comment]
@Killyana it definitely is in 3.3.5. https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L2370-L2379

Try it with a sound on an NPC and you'll see it's directional and distance dependent (fades out).

**Comment by Killyana** [comment]
Here, for me the sound loudness is always the same, I remember we discuss this issue with @Kittnz when he made the music stuff for events, and someone told me it's not implemented on wotlk.
``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=321;
DELETE FROM `smart_scripts` WHERE `entryorguid`=321 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(321,0,0,0,1,0,100,0,6000,6000,6000,6000,4,6197,0,0,0,0,0,1,0,0,0,0,0,0,0,"OOC play sound");

**Comment by r00ty-tc** [comment]
I can't see anything for music. But for sure sounds can be sourced from an object and will behave accordingly. SAI, I don't know though, not checked. I would say that if the target self sound doesn't play distance sound, it probably should.

**Comment by Teppic1** [comment]
@Killyana I didn't mean Gray Forest Wolves play the work work sound, which would be quite funny. They play a howl sound in the same way which is also across the zone, that's what the other fix was for.

**Comment by tkrokli** [comment]
I remember asking in #trinity about that wolf howling sound (without any wolves in viewing distance) some time ago, but I remember being told it was part of the zone ambience sounds. Not sure if this is the same as you discuss now, but that is mostly why I never bothered to check for any other sources for it.

**Comment by Killyana** [comment]
I know, but it doesn't spam the area, also if there's no Wolf visible to the player , no sound will be played.

**Comment by Teppic1** [comment]
But because the sound is so wide, you'll  hear it at full volume inside buildings, e.g. the top of the Tower of Azora.

**Comment by Killyana** [comment]
Yes, will see if someone can fix it properly, otherwise I will push your fix.

**Comment by Kittnz** [comment]
Don't tell me you don't like some nice wolf howling in your ears.
I'll add a new smart ai function for the distance sound.
