### ISSUE TITLE
Flightmaster node prices not reduced by reputation discount

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#20713]
#**Description:**
Price when using a flightmaster is not reduced by reputation.

**Current behaviour:**
Price remains the old non discounted price.

**Expected behaviour:**
Price should be reduced by rep.

**Steps to reproduce the problem:**
Missing reduction from firstcost here
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L21236

And also in FlightPathMovementGenerator::LoadPath.

**Branch(es):**

both

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/9f943e284f2418e8e90d1bcf5d0a5fbf073580f3

**Comment by robinsch** [comment]
All nodes are affected by this

**Comment by robinsch** [comment]
This affects all nodes, should I create a new issue or do you want to track it here and reopen it?

**Comment by Shauren** [comment]
New.

**Comment by CraftedRO** [comment]
Was that new issue ever created, does it still valid ? not sure how to properly test this

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e947fcedee5fcf3983cd4a745eebcb0e05f9d771
