### ISSUE TITLE
[3.3.5] 11550 Quest Enter, the Deceiver..

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20723]
**Description:**
Quest "Enter, the Deceiver..." Horde can accept this Quest but it's only a Allianze Quest

http://www.wowhead.com/quest=11550/enter-the-deceiver

**Current behaviour:**
Horde can accept this Quest

**Expected behaviour:**
Only Allianze can accept this Quest

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 82a93e6be95a 2017-10-26 00:22:45 +0200 (335a branch)

**TDB version:** TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Win7

**Comment by STARRHELD** [comment]
```SQL
UPDATE `quest_template` SET `AllowableRaces`=1101 WHERE `ID`=11550;
```

**Comment by Shauren** [comment]
Are you sure about that? There is a video of a blood elf doing this quest on the same wowhead page that you linked

**Comment by Killyana** [comment]
wowhead mistaken.
