### ISSUE TITLE
[3.3.5/Hotswap] Crash in Magisters Terrace on runtime scripts rebuild

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#20727]
**Description:**
When reloading script that use EnsureAI, an Assertion will be triggered in `src\server\game\AI\CoreAI\UnitAI.h:34 in EnsureAI ASSERTION FAILED:  cast_ai`
This is valid for any script with EnsureAI.
**Steps to reproduce the problem:**
1.  .go crea id 24560
2.  Edit something in script https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp
3.  Wait for reload and crash.

**CrashLog**: https://gist.github.com/sirikfoll/8f0c3c4fe72483eb792f19e3e06f5610

**Branch(es):** 3.3.5
**TC rev. hash/commit:** be0ae9135039a38d3a96b25922d44f181f5aa84f
**Operating system:** Windows 10

**Comment by Faq** [comment]
This closes with https://github.com/TrinityCore/TrinityCore/commit/78f4f54f81e092c9c7b99af445fb6ec85e00e6b0

**Comment by jackpoz** [comment]
That particular script expects the Creature to still have a registered AI but it seems after a runtime script rebuild it doesn't anymore.
It isn't an issue with EnsureAI but with scripts that expect things that are not valid anymore after a runtime rebuild, the issue should be investigated in why that creature doesn't have anymore the same AI.

**Comment by Shauren** [comment]
This is simple, this script violates one of the most basic rules we set for scripts - do not access other creatures/scripts in constructor. It would work just fine if placed in Reset

**Comment by sirikfoll** [comment]
Moving the access to Reset() doesn't solve it, Moroes in Karazhan do this in Reset(), same crash..
CrashLog: [650a92dc9fcb+_worldserver.exe_[5-2_15-44-40].txt](https://github.com/TrinityCore/TrinityCore/files/1696220/650a92dc9fcb._worldserver.exe_.5-2_15-44-40.txt)

But anyway, this should be solved by changing the scripts that present the problem and not something in Hotswap then?

**Comment by Shauren** [comment]
2fd9dc2edb0355d15f5afd21cc6aa61d172d19cc should fix it for Reset calls, obviously constructor itself and calling Reset from constructor is still not allowed

**Comment by Naios** [comment]
@Shauren good catch 👍 

```c++
        Initialize();
        instance = creature->GetInstanceScript();
        AcquireGUIDs();
```

Yes... this needs to be moved out of the constructor in [boss_priestess_delrissa.cpp](https://github.com/TrinityCore/TrinityCore/blob/7d00ae40458fe4399ca414c79a9b0a88b863267a/src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp) for sure.

@sirikfoll Are you sure that you are encountering the same crash after applying the discussed changes?

**Comment by sirikfoll** [comment]
Yes Naios, before Shauren's fix, it was still crashing, even with the change that I just pushed

**Comment by Naios** [comment]
@Shauren probably the same crash is present when dealing with GameObjects and ensure AI (if this is possible).

**Comment by jackpoz** [comment]
@sirikfoll did you debug ingame the change to ensure the GUIDs are actually there when reading their array ? To me it looks like sometimes AcquireGUIDs() could just read empty guids from the other AI, making the script broken after a rebuild.
