### ISSUE TITLE
Many creatures with waypoint movement have equipments sheathed

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20729]
**Description:**

I've noticed that almost every NPC with waypoint movement in classic zones have their equipments sheathed, and this should not be.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
There's too many of them to fix them one by one, so I think it's better to use a general fix. Of course, it may affect some creatures that should actually have their equipment sheathed (Don't know any, I'm just speculating).
```sql
UPDATE `creature_addon` SET `bytes2`=4097 WHERE `path_id`>0;

**Comment by malcrom** [comment]
That seems to be mildly retarded

**Comment by ZenoX92** [comment]
@malcrom Sorry, what did you mean?

**Comment by malcrom** [comment]
You just can't set the sheath state for all NPCs with no path

**Comment by offl** [comment]
```sql
WHERE `path_id` > 0;
```
This will set the sheath state for all NPCs **with** path

**Comment by offl** [comment]
> Of course, it may affect some creatures that should actually have their equipment sheathed (Don't know any, I'm just speculating).

Then maybe better to use this?
```sql
UPDATE `creature_addon` SET `bytes2`=4097 WHERE `path_id` > 0 AND !`bytes2`;

**Comment by Killyana** [comment]
What about something like this:
``` sql
UPDATE `creature_addon` SET `bytes2`=4097 WHERE `path_id` > 0 AND `guid` IN ( SELECT `guid` FROM `creature` WHERE `id` IN (SELECT `CreatureID` FROM `creature_equip_template`));

**Comment by Killyana** [comment]
or we can use `equipment_id` IN (1,-1)  directly from creature.

**Comment by Teppic1** [comment]
I thought bytes2 was a sniffed value?

Are there NPCs that have bytes2 already set to something that doesn't include the 2 bit? As these would get overwritten.

**Comment by Killyana** [comment]
In this case we can update this npcs only:
Than check the ones manually.
``` sq
SELECT * FROM `creature_addon` WHERE `path_id` > 0 AND `guid` IN ( SELECT `guid` FROM `creature` WHERE `id` IN (SELECT `CreatureID` FROM `creature_equip_template`)) AND `bytes2`=0;

**Comment by Teppic1** [comment]
Limiting it to creature entries that have 0 for bytes2 and a path set and an equipped weapon would seem to be the least likely to cause a problem. I think global updates are a bit of a risk though. Also a huge number of existing spawns have bytes2 set to 1, which may or may not have the same effect as 4097.

**Comment by Killyana** [comment]
`bytes2`=0 and `bytes2`=4097 have the same result, is always unsheathed.

**Comment by Teppic1** [comment]
You mean = 1? If it's just the first bit then any odd number will give that effect.

**Comment by malcrom** [comment]
You have to fix the wrong ones individually not set them all the same.

**Comment by Killyana** [comment]
Yes bytes2=1 and bytes2=4097 have the same result.

**Comment by mdX7** [comment]
For a global update you should OR the bytes2, you shouldn't set them in this case. This prevents overwriting already set states from bytes2 - so basicly
```sql
UPDATE `creature_addon` SET `bytes2`=`bytes2`|0xblah WHERE some conditions are met
```

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_addon` SET `bytes2`=2 WHERE `path_id` > 0 AND `guid` IN ( SELECT `guid` FROM `creature` WHERE `id` IN (SELECT `CreatureID` FROM `creature_equip_template` WHERE ItemID1=0 AND ItemID2=0 AND ItemID3>0)) AND `bytes2`=0;
UPDATE `creature_addon` SET `bytes2`=1 WHERE `path_id` > 0 AND `guid` IN ( SELECT `guid` FROM `creature` WHERE `id` IN (SELECT `CreatureID` FROM `creature_equip_template` WHERE ItemID1>0)) AND `bytes2`=0;
