### ISSUE TITLE
[3.3.5] DB/SAI: remove wrong event from Miles Sidney

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20744]
**Description:**

Miles Sidney is a poison vendor in Stormwind. He shouldn't greet players that enter his shop (this was only implemented for Dalaran shops, as far as I know. Still nothing suggests he should do it).

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 534afe3

**TDB version:** 335.63

**Suggested fix**:
```sql
--
DELETE FROM `smart_scripts` WHERE `entryorguid`=28347 AND `id`=1;
DELETE FROM `creature_text` WHERE `CreatureID`=28347 AND `GroupID`=5;


```

**Comment by Killyana** [comment]
Just tested on retail ans he say the welcome text.

**Comment by Wyreth** [comment]
Thanks for checking :) couldn't find anything about it, so I assumed it wasn't supposed to do that.

Going to fix the related DB error then.

**Comment by Wyreth** [comment]
@Killyana: can you push this?

```sql
--
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry`=28347;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(22, 2, 28347, 0, 0, 31, 0, 4, 0, 0, 0, 0, 0, "", "Execute SAI only if invoker is a player");


```

Fixes the related DB error (NPC tries to target nearby NPC for talk event. Should only target players).
