### ISSUE TITLE
Mind Control rendering mobs/NPCs useless

### ISSUE THREAD

**Issue by Pugnadeus** [TrinityCore/TrinityCore#20769]
**Description:**

Using Mind Control on a humanoid and canceling it renders it useless, not attacking the attacker, just standing, or following his waypoints, he will not retaliate or start casting spells if attacked, he will not aggro.

**Current behaviour:**

I use Mind Control, Cancel it and the mob stops attacking me, and will never attack again until killed and respawned.

**Expected behaviour:**

I use Mind Control, he gets controled, after I cancel it, he should start attacking me if I reach his aggro range or start attacking him.

**Steps to reproduce the problem:**

1. Use Mind Control (Spell ID 605) on a humanoid,

I tested it on Wastewander Bandit, and one of my players reported it in Stratholme.

**Branch(es):**  3.3.5

**TC rev. hash/commit:** TrinityCore rev. 6070340 2017-10-07 17:13:34 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Windows 10

**Comment by Langerz82** [comment]
This needs to be tested with both Hunter Pets and Warlock Minions. I've tested with the [Taming Rod](http://db.vanillagaming.org/?item=15923) and upon dismiss the Creature restored properly.

See Patch:
https://gist.github.com/Langerz82/531d8b5fb3412d2da438c1f3d498b121

**Comment by tkrokli** [comment]
Very well. If you are certain enough that it solves the issue, would you like to open a Pull Request for it?

**Comment by Langerz82** [comment]
PR Done.

**Comment by Langerz82** [comment]
I need to work on this more I did not understand the requirements properly give me a few hours.

**Comment by Langerz82** [comment]
Ok the following should fix 2 issues. The first making Mind Control work for Humanoids properly when dismissed. The second is it should restore Hunter Pets when dismissed. It should also make Minions work as before.
This will be needed to be tested thoroughly before a PR as it affects a few systems.

See:
https://gist.github.com/Langerz82/b7681fd61b4954fb648d2d27ae8b73f6

**Comment by Langerz82** [comment]
Note - The above patch should also fix #20323

**Comment by tkrokli** [comment]
Preliminary feedback on your patch after just 1 test with a female night elf hunter, only testing the tamed creatures (I don't remember Mind Control well enough to jump straight into a character and test it without more research or info) :
- https://wow.gamepedia.com/Quest:Taming_the_Beast_(night_elf)
- https://wow.gamepedia.com/Quest:Taming_the_Beast_(night_elf_2)
- https://wow.gamepedia.com/Quest:Taming_the_Beast_(night_elf_3)

Creature 1: Webwood Lurker, hostile spider level 5-6), stayed still after taming. Attacked after being dismissed and followed my player character back to Dolanaar where it got killed by a sentinel watch NPC.
Creature 2: Nightsaber Stalker, hostile cat, level 7-8, returned to regular pathing after a little while. Attacked after being dismissed.
Creature 3: Strigid Screecher, neutral owl, level 7-8, returned to regular pathing after a little while. Attacked after being dismissed.

**Comment by Langerz82** [comment]
I think the ordering of the lines:
charm->RemoveCharmAuras();
SetCharm(charm, false);

Has affected the change, I'll test properly later today thanks for feedback.

**Comment by Langerz82** [comment]
Test this patch think I got it working.

See:
https://gist.github.com/Langerz82/b7681fd61b4954fb648d2d27ae8b73f6

**Comment by Langerz82** [comment]
Ok think I finally got it working correctly. The Pet doesnt go back home instead it dies and respawns.

Tested on a webwood lurker (aggro) and on a strigid screecher (non-aggro) and seems to be fine the creature respawns with the correct flags and states restored.

See:
https://gist.github.com/Langerz82/b7681fd61b4954fb648d2d27ae8b73f6

**Comment by Langerz82** [comment]
This patch may also affect: #21266 
In which case we push this change, then I fix the other issue.

**Comment by Langerz82** [comment]
revised patch:
https://gist.github.com/Langerz82/0021841298b5240db7c489bf722cb7c0

**Comment by illfated** [comment]
Looks like the label **[Comp-C++Script]** could be removed from this issue, based on the content of your suggested patch.

Maybe the **[Sub-Spells]** label could be substituted with **[Sub-AI]** too, unless I have misunderstood the range of this issue.
