### ISSUE TITLE
[3.3.5] Territorial Trespass Quest 13051

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20771]
**Description:**
Veranus flies to the nest but does not land.
Thorim does not appear.
You can not finish the quest.

**Expected behaviour:**
http://www.wowhead.com/quest=13051/territorial-trespass
https://www.youtube.com/watch?v=Ucdzb4oG5-0

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. aa4bf288e77f 2017-11-01 03:44:59 +0100 (335a branch)

**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:**Win7

**Comment by Killyana** [comment]
Related to: https://github.com/TrinityCore/TrinityCore/issues/20310

**Comment by Wyreth** [comment]
@Tauriella did you test it recently? Should have been fixed after #20684.

**Comment by Killyana** [comment]
The event On Waypoint Finished = 58 is not triggred

**Comment by Wyreth** [comment]
Found the issue, going to open two pull requests for this (underlying issues that affect every script like this one).

**Comment by Killyana** [comment]
``` sql
DELETE FROM `event_scripts` WHERE `id` = 19714;
INSERT INTO `event_scripts` (`id`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(19714,0,8,5272,60,0,0,0,0,0),
(19714,0,10,30461,600000,0,6947.48,-859.518,1147.6,5.67487);

**Comment by Killyana** [comment]
Related https://github.com/TrinityCore/TrinityCore/issues/8976
Removing Removing: GetScript()->OnReset(); fix the issue.
https://github.com/TrinityCore/TrinityCore/commit/e10d7dd45cfc073c791cd5e5f3f964d14b37df3d#diff-703f1f16a955ae7ddc7caf673a75d85aR612

**Comment by Shauren** [comment]
sooo, is this broken again?

**Comment by Keader** [comment]
Looks like

**Comment by Tauriella** [comment]
It works now fine 👍 in
TrinityCore rev. e4e6e2209c8a 2018-02-12 03:25:05 +0100 (335a branch)

**Comment by Killyana** [comment]
This issue is a reference for https://github.com/TrinityCore/TrinityCore/issues/20517
Respawning gobs is still not implemented.
