### ISSUE TITLE
[3.3.5] DB/Creature: prevent escort NPC Rin'ji from being killed by nearby creatures

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20775]
**Description:**

[Rin'ji](http://www.wowhead.com/npc=7780) is the quest giver for an escort quest. He shouldn't be able to get killed by the nearby hostile creatures before the escort starts.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** aa4bf28

**TDB version:** 335.63

**Suggested fix**:
```sql
--
UPDATE `creature_template` SET `unit_flags`=512 WHERE `entry`=7780;


```

**Comment by Aokromes** [comment]
i sugest `unit_flags`=`unit_flags`|whatever values

**Comment by Wyreth** [comment]
It has no unit_flags set currently, not sure if there's a sniffed value somewhere (but NPC was taken out in Cataclysm, and it's a very remote area, so unlikely :|)

**Comment by offl** [comment]
[cpp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/zone_hinterlands.cpp#L136) should be updated too(or converted to SAI(better solution)), because now he will be unattackable and during his escort quest.

**Comment by Wyreth** [comment]
Immune to NPC is automatically removed [here](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp#L433) while the escort is in progress.

Will try to convert this to SAI when I have more free time :)

**Comment by offl** [comment]
Oh, my bad.
