### ISSUE TITLE
DB/Creature: fix modelid for some creatures

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20774]
**Description:**

[Wing Commander Gryphongar](http://www.wowhead.com/npc=20232), [Wodin the Troll-Servant](http://www.wowhead.com/npc=30009) should always be male, but their modelids have the other gender ID set.

Also [Rin'ji](http://www.wowhead.com/npc=7780) currently has the wrong model set in `creature` (thanks @offl!)

**Branch(es):** both.

**TC rev. hash/commit:** aa4bf28

**TDB version:** 335.63

**Suggested fix**:
```sql
--
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID` IN (6485, 12829, 16389);
UPDATE `creature` SET `modelid`=0 WHERE `id`=7780;


```

**Comment by Aokromes** [comment]
creature_template update is incorrect:

ServerToClient: SMSG_CREATURE_QUERY_RESPONSE (0xD847) Length: 121 Time: 11/12/2011 15:00:28.000 Number: 16894
Entry: 7780
[0] Name: Rin'ji
[1] Name: 
[2] Name: 
[3] Name: 
[4] Name: 
[5] Name: 
[6] Name: 
[7] Name: 
Sub Name: Witherbark Troll
Icon Name: 
Type Flags: CanAssist (4096)
Creature Type Flags 2: 0
Type: Humanoid (7)
Family: None (0)
Rank: Normal (0)
[0] Kill Credit: 0
[1] Kill Credit: 0
[0] Display ID: 28236
[1] Display ID: 0
[2] Display ID: 0
[3] Display ID: 0

**Comment by Wyreth** [comment]
Thanks, going to take that out. Not sure what Blizzard was thinking there :P

**Comment by offl** [comment]
> [Patch 3.0.2 (2008-10-14): Model updated.](https://wow.gamepedia.com/Rin'ji)

So:
```sql
UPDATE `creature` SET `modelid`=0 WHERE `id`=7780;
```

**Comment by Wyreth** [comment]
Ooh nice, didn't know about that. Checked Wowhead screenshots but now I see they're from 2006/2008. Updated!
