### ISSUE TITLE
Wrath Gate NPCs improperly flagged

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20772]
**Description:**
The NPCs in the Court of Skulls / Wrath Gate in Dragonblight are not flagged correctly.

**Current behaviour:**
As Alliance, Horde and Scourge NPCs in the zone appear friendly (green nameplates). The Scourge provide the attack cursor but are unattackable. They appear as in combat for a split second and then they ignore you. The Horde are simply friendly.

![wowscrnshot_110117_032711](https://user-images.githubusercontent.com/16745918/32268683-b371a51e-beb5-11e7-8d31-a16dd1c77764.jpg)

**Expected behaviour:**
Scourge should be hostile, attack you within agro range, and killable.
Horde should appear as hostile (as for if you can actually attack them I am uncertain).

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 69842e562c10

**TDB version:**  335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
I'm not sure about this, someone must check on retail.

**Comment by Aokromes** [comment]
It's ancient, really really ancient bug, i don't remember if a ticket about it exists.

**Comment by tkrokli** [comment]
Very little to be found, mostly closed issues and only 2 open ones (not sure if related either):
- https://github.com/TrinityCore/TrinityCore/search?q=Angrathar&type=Issues&utf8=✓
- https://github.com/TrinityCore/TrinityCore/search?q=Angrathar&state=open&type=Issues&utf8=✓

**Comment by jerbookins** [comment]
Pretty sure one of those phasing issues was created by me, it is a similar problem but an unrelated issue as it is more directly focusing on the phasing and visibility of mobs at the Wrath Gate.

**Comment by jerbookins** [comment]
Correction, I was flying around Dragonblight again and noticed that the Scourge appears hostile to me if I am *not* within the Court of Skulls zone. As soon as I enter the zone, the Scourge behaves as described above. What does not change, however, is the hostility (red nameplates) of the Horde on the other side -- and again I do not know if they should be attackable or just appear hostile.
