### ISSUE TITLE
Crystalline Frayers inside Nexus do not agro (ID 26793)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20781]
**Description:**
http://www.wowhead.com/npc=26793/crystalline-frayer

**Current behaviour:**
Crystalline Frayers pop in and out of combat and do not attack.

**Expected behaviour:**
They should attack you.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 58dad504da18

**TDB version:**  335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16096

**Comment by jerbookins** [comment]
Would you mind linking to the existing issue, because i did not see one before posting.

**Comment by Aokromes** [comment]
https://i.imgur.com/7tIWAG5.png

**Comment by jerbookins** [comment]
I must have been SUUUUPER tired to not realize that
