### ISSUE TITLE
[3.3.5] Destiny Calls - Sethir's Journal doesn't drop

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#20790]
**Description:**

Sethir the Ancient should be dropping Sethir's Journal, if you have the quest Destiny Calls

**Current behaviour:**

Sethir the Ancient doesn't drop Sethir's Journal

**Expected behaviour:**

Sethir the Ancient should drop Sethir's Journal

**Steps to reproduce the problem:**

1. Pick up the quest Destiny Calls
2. Go kill Sethir the Ancient

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 427f68fc6a0a 2017-11-03 18:21:17 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Dynamic)

**TDB version:**  335.63

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
Nope:
https://github.com/TrinityCore/TrinityCore/issues/16422#issuecomment-176825112

**Comment by tkrokli** [comment]
From https://wow.gamepedia.com/Sethir_the_Ancient (https://wow.gamepedia.com/Sethir%27s_Journal)
> The objective of the quest A Rogue [10] Destiny Calls is to steal  [Sethir's Journal] from him without him noticing.

**Comment by GnaXi** [comment]
Woops. My bad!
