### ISSUE TITLE
DB/Creature: all the Scarlet Captain NPCs should be mounted

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20807]
**Description:**

Every [Scarlet Captain](http://www.wowhead.com/npc=28611) in the Death Knight starting zone should be on a horse. Currently there are a few that are dismounted.

**Branch(es):** both.

**TC rev. hash/commit:** 28cd4b5

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature_addon` SET `mount`=2404 WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id`=28611);


```

**Comment by mdX7** [comment]
Use creature_template_addon, would be less data in db

**Comment by Wyreth** [comment]
All those creatures already have existing data in creature_addon (most of the spawns have an unique pathing), so it can't be done in c_t_a sadly :P

**Comment by tkrokli** [comment]
http://weebls-stuff.com/toons/amazing-horse/ 😆
