### ISSUE TITLE
DB/Spawn: fix phasemask for some creatures and one gameobject in the Death Knight starting area

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20805]
**Description:**

The last version of the [The Death Knights of Acherus](http://www.wowhead.com/object=191645) book is currently spawned on top of the second-to-last version. Instead, the last version (and the gryphons allowing to reach and leave Acherus) should be still spawned before the player learns the spell Death Gate.

**Branch(es):** both.

**TC rev. hash/commit:** 28cd4b5

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature` SET `phaseMask`=`phaseMask`|128 WHERE `guid` IN (128509, 128510, 128500, 128501);
UPDATE `gameobject` SET `phaseMask`=128 WHERE `guid`=66496;


```

**Comment by offl** [comment]
> Branch(es): both.

So this will fix the issue mentioned in https://github.com/TrinityCore/TrinityCore/issues/20063#issuecomment-323383449?
> There is no phasing on the "The Death Knights of Acherus" books. (3.3.5 too)
http://www.wowhead.com/object=191642/the-death-knights-of-acherus

**Comment by Wyreth** [comment]
Yep, nice find :) it fixes that specific issue.

**Comment by Killyana** [comment]
I'm respawning/fixing the DK starting area, it will take some days, I will just push the fix for the book as this creatures will be removed
