### ISSUE TITLE
DB/Creature: fix InhabitType for NPC Carrion Condor

### ISSUE THREAD

**Issue by Wyreth** [TrinityCore/TrinityCore#20812]
**Description:**

[Carrion Condor](http://www.wowhead.com/npc=26174)s should be flying, not falling to the ground.

**Branch(es):** both.

**TC rev. hash/commit:** 28cd4b5

**TDB version:** 335.63

**Suggested fix**:
```sql
UPDATE `creature_template` SET `InhabitType`=4 WHERE `entry`=26174;


```

**Comment by Killyana** [comment]
The Inhabittype is 7, it's correct, the issue must be fixed on core side.

**Comment by Killyana** [comment]
The Inhabittype is 7, it's correct, the issue must be fixed on core side.

**Comment by tkrokli** [comment]
I presume `InhabitType=4` can be seen as a temporary workaround (I guess it works at the moment), although the intention would be to make it work with `InhabitType=7` as well, given that the core issue gets fixed.

**Comment by Killyana** [comment]
Inhabittype 7=4+2+1 so it's there, hacking values onthe  DB to avoid a core issue is always a bad idea.
