### ISSUE TITLE
Gameobject WorldEffectID conditional

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#20832]
**Description:**

Some WorldEffects of gameobjects should only be shown if some condition is fullfilled e.g. quest status.

**Current behaviour:**

when added a worldeffectid it shows all the time for everyone

**Expected behaviour:**

Depending on the condition a player should see or not see the WorldEffect.

**Steps to reproduce the problem:**

**Branch(es):**

master

**TC rev. hash/commit:** 

8654e4ec283aa56be195620891e6edb5d7c07840

**TDB version:**  7.2.0

**Operating system:** Win 10

**Comment by Faq** [comment]
Any example of such object?

**Comment by funjoker** [comment]
Gameobjects which are quest related but not necessary to use. Like: kill Mob xyz and there are gameobjects around with effects. This gobjects have a WorldEffect
