### ISSUE TITLE
[Event] Midsummer

### ISSUE THREAD

**Issue by L30m4nc3r** [TrinityCore/TrinityCore#2083]
http://www.wowhead.com/quest=11923
http://www.wowhead.com/quest=11922
http://www.wowhead.com/quest=11886
http://www.wowhead.com/quest=11972

not worked

http://ru.wowhead.com/quest=11691
http://www.youtube.com/watch?v=ZfCuHnGo6Qw

[EDIT1]

http://ru.wowhead.com/achievement=1145#comments

**Comment by Aokromes** [comment]
Few tickets exists for individual quests, some maybe are already fixed. if some quest is still bugged open individual tickets per bugged quest.
