### ISSUE TITLE
Quest 'Murder Was The Case That They Gave Me' NPCs lack gossip

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20836]
**Description:**

The NPCs required for the quest 'Murder Was The Case That They Gave Me' lack gossip.

**Current behaviour:** NPCs only say greetings.

**Expected behaviour:** They should say another gossip text and have two white chat bubbles.

**Steps to reproduce the problem:**

1. Create an Alliance character level 10.
2. Travel to Westfall.
3. Acquire the quest 'Murder Was The Case That They Gave Me.'
4. Head to the farm.
5. Click the neutral hobo NPCs.
6. Look at the gossip.

**Branch(es):** master

**TC rev. hash/commit:** 733441922b78

**TDB version:**  720.00_2017_04_18

**Operating system:** MacOS

**Comment by nubqt** [comment]
Working on this issue right now. Have gotten the gossip down but still lacking the probability of mobs attacking or completing the quest objective when the chat bubbles are clicked by the player.

Here's the general idea of how to fix it partially:

1. Change NPC type in template
2. Link gossip menu to text_id
3. add npc_text
4. update gossip_menu_option: broadcast textid
5. creature_template: ainame
6. creature_text: for each NPC
7. UPDATE `creature` SET `spawntimesecs` = '1' WHERE `id` IN ('42383','42384','42386','42391');
8. smart_script, several steps: (i) close gossip (ii) say random text @ 50% probability (iii) change unit_flag to make NPC attackable @ 50% probability (iv) attack player @ 50% probability (v) say random text @ 50% probability (vi) complete quest objective @ 50% probability (viii) despawn NPC at 50% probability

**Comment by funjoker** [comment]
"Change NPC type in template" NEVER TOUCH TEMPLATE!

**Comment by nubqt** [comment]
yes, you are right. that was a copy/paste from my notes. the NPC type doesn't need to be changed

**Comment by nubqt** [comment]
#15182 serves as the master checklist for Westfall issues, including this one.

**Comment by nubqt** [comment]
Any idea how to complete a quest objective with smart_scripts / SmartAI / SAI ? It's the only thing I have left to fix this issue.

**Comment by meji46** [comment]
Spells:

Check's spells: 79177, 79178, 79179
Killcredit spells: 79181, 79812, 79183, 79184

Don't forget that you must receive the clues in a specific order:

1.  Spell 79181 & BroadcastTextId 42380
2.  Spell 79182 & BroadcastTextId 42381
3.  Spell 79183 & BroadcastTextId 42382
4.  Spell 79184 & BroadcastTextId 42383

**Comment by nubqt** [comment]
@meji46: thanks! not sure what the first three spells are though? how can I find out?

**Comment by meji46** [comment]
It's necessary to read the quest's sniffs to see when they are used

**Comment by tkrokli** [comment]
Maybe it would be practical to see the info on wowhead pages too:
- Kill Credit:
  - http://www.wowhead.com/spell=79181/hobo-information (http://www.wowhead.com/npc=42414/furlbrow-murder-info-001)
  - http://www.wowhead.com/spell=79182/hobo-information (http://www.wowhead.com/npc=42415/furlbrow-murder-info-002)
  - http://www.wowhead.com/spell=79183/hobo-information (http://www.wowhead.com/npc=42416/furlbrow-murder-info-003)
  - http://www.wowhead.com/spell=79183/hobo-information (http://www.wowhead.com/npc=42417/furlbrow-murder-info-004)

- Server-side script (Dummy):
  - http://www.wowhead.com/spell=79177/hobo-information
  - http://www.wowhead.com/spell=79178/hobo-information

- Script Effect
  - http://www.wowhead.com/spell=79179/hobo-information

**Comment by nubqt** [comment]
Thanks! The first four were quite useful.

My guess is that they created an invisible NPC and kill it through a spell to complete the quest's objectives.

But I can't figure out what the server-side scripts and the script effect do.

Any suggestions of how I can research this further?

**Comment by tkrokli** [comment]
Not sure. Maybe the spells are supported by the dbc/DB2 content, I don't know.

If you read the page https://wow.gamepedia.com/Quest:Murder_Was_The_Case_That_They_Gave_Me , you might get an idea about the various gossips and that some of them will produce a correct gossip result, while some of the others may lead to unwanted or misleading outcomes. Not sure if that is handled by conditions or simply by the linking of the gossip options and SAI actions from there. Sniff info would help, especially if they contain any leads to if the spells are scripted in a particular way.

**Comment by nubqt** [comment]
I'm stuck in the conditions for completing the objectives and was wondering if someone could help. Everything else has been done.

The issue at hand is that like @meji46 noted, the objectives ("clues") must be completed in order. What this means in SmartAI is that certain conditions must be met before executing a script. Assuming the probability yields that the NPC completes an objective (rather than become hostiles) this is the pseudocode of what must occur:

1. if Player has NOT completed objective 1, then allow the SMART_SCRIPT_TYPE_TIMED_ACTIONLIST that completes objective 1
2. if Player has completed objective 1 but not objective 2, then allow the SMART_SCRIPT_TYPE_TIMED_ACTIONLIST that completes objective 2
3. if Player has completed objective 2 but not objective 3, then allow the SMART_SCRIPT_TYPE_TIMED_ACTIONLIST that completes objective 3
4. if Player has completed objective 3 but not objective 4, then allow the SMART_SCRIPT_TYPE_TIMED_ACTIONLIST that completes objective 4

I created both the conditions and the smart_scripts for that, but the conditions are preventing the script from running and I don't know.

Attached are screenshots of the records created under `conditions` and under `smart_scripts`. My testing NPC is a 'West Plains Drifter.'

Any help?

<img width="1552" alt="screen shot 2017-11-12 at 2 14 58 pm" src="https://user-images.githubusercontent.com/33535711/32702411-cf5de0e6-c7b4-11e7-921f-b77db64589a2.png">

<img width="1378" alt="screen shot 2017-11-12 at 12 37 50 pm" src="https://user-images.githubusercontent.com/33535711/32702416-e194a970-c7b4-11e7-99f4-0882b2ca5b3c.png">

**Comment by tkrokli** [comment]
Your images are nice to look at as such, but it is more helpful to use block quotes and paste the SQL code as straight text in the post.
To start SQL block quote, insert this code on a blank line above the code: ` ```sql ` or ` ~~~sql `
End any block quote with ` ``` ` or ` ~~~ ` to write normal text after it.

Makes it a lot easier to copy/paste lines/rows for others to suggest changes based on your code.
