### ISSUE TITLE
Quest: Sabotage & Disclosure

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20837]
**Description:**
http://www.wowhead.com/quest=12676/sabotage
http://www.wowhead.com/quest=12710/disclosure

These quests are intertwined as the quest criteria for Sabotage requires you to complete Disclosure.

**Current behaviour:**
1. Using the [Explosive Charges](http://www.wowhead.com/item=39165/explosive-charges) near a Scourgewagon places the charges and blows up the wagon but does not give credit toward the quest.

2. Credit is not given for the quest Disclosure after following Malmortis around the upper level of the floating ziggurat Voltarus.

**Expected behaviour:**

1. Using the [Explosive Charges](http://www.wowhead.com/item=39165/explosive-charges) near a Scourgewagon should give credit toward the quest.

2. Following Malmortis around the upper level of the floating ziggurat Voltarus should give you credit for Disclosure, and upon turning in Disclosure should fulfill quest criteria for Sabotage.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 30c2a96f16ef

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
Split the issue into 2, for disclosure it's relate to the waypoint issue, the other one not.
