### ISSUE TITLE
[Master] Sandstone Drake Visual Bug

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#20835]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**
 (upload to https://gist.github.com/).
![wowscrnshot_111017_174052](https://user-images.githubusercontent.com/6026902/32671172-611beeec-c63e-11e7-8a33-112f4f2595ff.jpg)

**Expected behaviour:**

No second Dragon

**Steps to reproduce the problem:**

1.Mount up

**Branch(es):**

Master

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/8654e4ec283aa56be195620891e6edb5d7c07840

**TDB version:**  720

**Operating system:** Windows

**Comment by offl** [comment]
#19758
