### ISSUE TITLE
[ASSERT] Crash on failed assertion in map.cpp

### ISSUE THREAD

**Issue by peterwankman** [TrinityCore/TrinityCore#20834]
**Description:**

The world server crashed several times with players in instances.

**Current behaviour:**

The world server crashes with a failed assertion in src/server/game/Maps/Map.cpp:3197
When the player who triggered the crash logs in the next time, the server crashes again. I can temporarily prevent the crash by deleting the appropriate row in the characters.instance table.

https://gist.github.com/peterwankman/59e1a74f6ae5e4b20191d8b858ce5221

The crash still happens sporadically afterwards.

**Expected behaviour:**

The world server should keep on running.

**Steps to reproduce the problem:**

Enter an Utgarde Keep and kill Ingvar the plunderer
Use command .respawn

Logging out and in again may not be neccessary.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 60a5535f64e4 2017-11-07 19:22:39 +0100 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:**  

TDB_full_world_335.63_2017_04_18.sql with current updates from git applied.

**Operating system:**
Debian GNU/Linux 8 ("Jessie")

**Comment by peterwankman** [comment]
I couldn't reliably trigger the crash with the instructions I gave earlier. I changed the steps to reproduce into something more precise and simpler

**Comment by r00ty-tc** [comment]
There must be a bit more to this. Since, I tried this 4-5 times in a row, with repsawn attempted after first death as well a few times. Logged out/back in. Still fine.

No luck in getting a crash.

If you can give a process we can follow assuring the crash we'll have more chance in helping.

**Comment by peterwankman** [comment]
I will look more into it and report if I find a way that always works.

**Comment by peterwankman** [comment]
Still trying to find a way to reliably crash the server.

Since this crash happens to me so often, but nobody else seems to have that problem, I'm beginning to suspect, the issue might be with something else on my system.

Still, I made a small change to Map.cpp to display the values in the failed assertion, because gdb wouldn't include them in the log:
`if(now >= next->respawnTime) fprintf(stderr, "now: %d; next->respawnTime: %d\n", now, next->respawnTime);`
gives
`now: 1510504578; next->respawnTime: -2147483635`
Which points to an integer overflow error. I'm not proficient enough in C++ to find out where that value comes from, but perhaps it helps you help me.

**Comment by r00ty-tc** [comment]
Quick question, which DB server and version are you using (Mysql/MariaDB)? I have an idea but want to setup a matching system here.

**Comment by tkrokli** [comment]
@peterwankman : check https://github.com/TrinityCore/TrinityCore/issues/20317#issuecomment-329574164 for more info on gdb crash debugging.

**Comment by r00ty-tc** [comment]
Actually another question from me, which c++ compiler and exact version in use (g++ -v or clang++ -v). Just trying to work out how you got a negative value in there.

**Comment by Shauren** [comment]
He didn't. Look at the format string, %d is a SIGNED integer, reinterpreting that value as unsigned gives 2147483661

**Comment by peterwankman** [comment]
> Quick question, which DB server and version are you using (Mysql/MariaDB)? I have an idea but want to setup a matching system here.
mysql  Ver 14.14 Distrib 5.5.58, for debian-linux-gnu (i686) using readline 6.3

> Actually another question from me, which c++ compiler and exact version in use (g++ -v or clang++ -v). Just trying to work out how you got a negative value in there.
gcc version 4.9.2 (Debian 4.9.2-10)
Full output:
https://gist.github.com/peterwankman/e7dac5c9e960cc3aa3c38cd05e2be1dc

> He didn't. Look at the format string, %d is a SIGNED integer, reinterpreting that value as unsigned gives 2147483661
time_t is a signed type. And sizeof(time_t) is 4. So, I consider my results valid.

**Comment by r00ty-tc** [comment]
Well, I saw that. But time_t is usually treated as signed. If it was treating is as a signed or unsigned 64bit int (which is is on all my systems) all is well. Debian 8 64bit gnu/clang both give size of 8 for time_t.

But, just checking if Debian 8 for i386 gives me size of 4, for time_t which might well explain everything.

**Comment by r00ty-tc** [comment]
Yeah. It looks that way. GCC on 64bit, has time_t as 64 bit signed and GCC on 32bit has time_t as 32bit signed. So does clang.

This might be a problem for all 32bit builds actually.

Probably we can cap the "infinite" respawn time to signed max 32bit, or we can force the check to be unsigned.

**Comment by r00ty-tc** [comment]
@peterwankman give https://github.com/r00ty-tc/TrinityCore/commit/4c68d1a4bbcaa8f43dea3dc0f134f3a974eb9419 a try. Longest part was getting 32bit env setup and compiling to test. Seems to stop it happening for me.

Yes, I could just compile 32bit on windows, but damn I only keep 64bit libs up to date!

**Comment by r00ty-tc** [comment]
Note, I updated the commit, also make sure that any respawn times in your DB that are > 2147483647 are set to 2147483647 before you start worldserver after this change.

**Comment by peterwankman** [comment]
Thank you very much. I pulled and the build is running, but I won't be able to test it before this evening.
Will it suffice to delete the instances or are there more tables I have to check?

**Comment by r00ty-tc** [comment]
You can delete or adjust the respawn times, it's only those values higher than 2^31-1 that cause the problem. Something like:

```SQL
UPDATE `creature_respawn` SET respawnTime = 2147483647 WHERE respawnTime > 2147483647
```

Note: Anyone else reading this, the SQL above is for 32bit systems only, respawn times normally and correctly can go much higher on 64bit systems.

**Comment by Shauren** [comment]
What exactly is going on there? Its not year 2039 yet

**Comment by r00ty-tc** [comment]
@Shauren essentially the problem is this. And it's a crappy one which will be fixed in time. @Treeston has said once all instances are upgraded to use the creature group system the old code won't be needed, that causes this problem.

The current instance code will set boss respawn times to be the maximum possible value for the type time_t. Then, when linked respawns happen, the system will look to their leader, and add "some seconds" onto that time before respawning them.

The intermediary fix I provided just caps that amount at the maximum time_t. Without it, on 32bit systems it overflows the time_t into negative values, which breaks the respawn system on an ASSERT.

So, it's essentially bad code that will be replaced but isn't yet.

**Comment by peterwankman** [comment]
I didn't experience any more crashes today. After clearing the instance, I noticed some mobs reappeared when I walked through it again, but I can't recall from my time playing retail, if that's just normal.

Thank you very much for addressing my problem so quickly.

After running it so many times in the last couple of days, I hope I'll never see Utgarde Keep again. :3

**Comment by r00ty-tc** [comment]
I expect it would have happened on any instance (well any heroic one at least) that has linked trash.

I was reliably able to reproduce it once I setup a 32bit system on VM.
