### ISSUE TITLE
Nothing happens after mounting the 'Sanitron 500' in 'Decontamination' quest 

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20847]
**Description:** Nothing happens after mounting the 'Sanitron 500' in 'Decontamination' quest.

**Current behaviour:** Nothing happens after mounting the 'Sanitron 500' in 'Decontamination' quest.

**Expected behaviour:** if I remember correctly, the Sanitron automatically moves to the middle of the room and a 'decontamination' process occurs to the character which completes the quest objective. The issue might thus be related to movements.

**Steps to reproduce the problem:**

1. Create a level 1 Female Gnome Warrior.
2. Complete the starting quests up to 'Decontamination.'
3. Mount the 'Sanitron 500.'

**Branch(es):** master

**TC rev. hash/commit:** 733441922b78

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS 10.13.1

**Comment by Aokromes** [comment]
It continues to be the same quest bugged. #16224
