### ISSUE TITLE
[3.3.5][Quest] Death Comes From On High (12641)

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#20843]
**Description:**

The Eye of Acherus does not behave as it should in regards to launching and its movement speed.

**Current behaviour:**

At the start of the quest, the Eye is not launched towards New Avalon. The Movement speed of the Eye is much slower than retail.

**Expected behaviour:**

The Eye of Acherus should launch towards New Avalon with notifications for "The Eye of Acherus launches towards its destination." and "The Eye of Acherus is in your control."
After gaining control the Eye should also move faster. 
Video for reference: https://www.youtube.com/watch?v=VAQwxyWrXrc

**Steps to reproduce the problem:**

1. Create a new deathknight.
2. Complete the intro quest chain up until this point.
3. Begin quest and use the Eye of Acherus.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3e74ef1528db 2017-11-10 23:45:42 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** TDB_full_world_335.63_2017_04_18

**Operating system:** Fedora 26

**Comment by offl** [comment]
#18362 is no longer actual?

**Comment by rockz1152** [comment]
I was still able to complete the quest with the spells provided. #18362 might only be master branch, this was tested on 3.3.5.

**Comment by noblist** [comment]
Have same problem on 3.3.5. Not going to look into what spell you posted, but the syphon works, you jjust have to send the eye yourself.

**Comment by Killyana** [comment]
"At the start of the quest, the Eye is not launched towards New Avalon" related to :https://github.com/TrinityCore/TrinityCore/issues/20310

**Comment by Killyana** [comment]
There's 2 actions not executed:
DoCast(me, SPELL_EYE_FLIGHT_BOOST);
and me->GetMotionMaster()->MovePath(me->GetEntry() * 100, false);
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L403-L416

This works correctly on master so probably broken by recent changes.

**Comment by illfated** [comment]
@Addra commented in issue #22060 :
> and the Spell Eye of Acherus Flight (Boost) is being cast on the Player instead of the controlled NPC

I am guessing that is referencing this line:
https://github.com/TrinityCore/TrinityCore/blob/718742005c3be7e57b32fd4f9b0bd85a5cdbbe27/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L403

**Comment by Addra** [comment]
`class npc_scarlet_ghoul : public CreatureScript
{
public:
    npc_scarlet_ghoul() : CreatureScript("npc_scarlet_ghoul") { }

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_scarlet_ghoulAI(creature);
    }

    struct npc_scarlet_ghoulAI : public ScriptedAI
    {
        npc_scarlet_ghoulAI(Creature* creature) : ScriptedAI(creature)
        {
            // Ghouls should display their Birth Animation
            // Crawling out of the ground
            //DoCast(me, 35177, true);
			//me->MonsterSay("Mommy?", LANG_UNIVERSAL, 0);			
            me->SetReactState(REACT_DEFENSIVE);
        }

        void FindMinions(Unit* owner)
        {
            std::list<Creature*> MinionList;
            owner->GetAllMinionsByEntry(MinionList, NPC_GHOULS);

            if (!MinionList.empty())
            {
                for (std::list<Creature*>::const_iterator itr = MinionList.begin(); itr != MinionList.end(); ++itr)
                {
                    if ((*itr)->GetOwner()->GetGUID() == me->GetOwner()->GetGUID())
                    {
                        if ((*itr)->IsInCombat() && (*itr)->getAttackerForHelper())
                        {
                            AttackStart((*itr)->getAttackerForHelper());
                        }
                    }
                }
            }
        }

        void UpdateAI(uint32 /*diff*/) override
        {
            if (!me->IsInCombat())
            {
                if (Unit* owner = me->GetOwner())
                {
                    Player* plrOwner = owner->ToPlayer();
                    if (plrOwner && plrOwner->IsInCombat())
                    {
                        if (plrOwner->getAttackerForHelper() && plrOwner->getAttackerForHelper()->GetEntry() == NPC_GHOSTS)
                            AttackStart(plrOwner->getAttackerForHelper());
                        else
                            FindMinions(owner);
                    }
                }
            }

            if (!UpdateVictim() || !me->GetVictim())
                return;

            //ScriptedAI::UpdateAI(diff);
            //Check if we have a current target
            if (me->EnsureVictim()->GetEntry() == NPC_GHOSTS)
            {
                if (me->isAttackReady())
                {
                    //If we are within range melee the target
                    if (me->IsWithinMeleeRange(me->GetVictim()))
                    {
                        me->AttackerStateUpdate(me->GetVictim());
                        me->resetAttackTimer();
                    }
                }
            }
        }
    };

};`

This works perfect! I tried it!

**Comment by Addra** [comment]
` /*######
## npc_eye_of_acherus
######*/

enum EyeOfAcherus
{
    SPELL_EYE_VISUAL            = 51892,
    SPELL_EYE_FLIGHT_BOOST      = 51923,
    SPELL_EYE_FLIGHT            = 51890,

    EVENT_MOVE_START            = 1,

    TALK_MOVE_START             = 0,
    TALK_CONTROL                = 1,

    POINT_EYE_FALL              = 1,
    POINT_EYE_MOVE_END          = 3
};

Position const EyeOFAcherusFallPoint = { 2361.21f, -5660.45f, 496.7444f, 0.0f };

class npc_eye_of_acherus : public CreatureScript
{
    public:
        npc_eye_of_acherus() : CreatureScript("npc_eye_of_acherus") { }

        struct npc_eye_of_acherusAI : public ScriptedAI
        {
            npc_eye_of_acherusAI(Creature* creature) : ScriptedAI(creature)
            {
                me->SetDisplayId(me->GetCreatureTemplate()->Modelid1);
				me->CastSpell(me, SPELL_EYE_VISUAL, true);
                me->SetReactState(REACT_PASSIVE);
				me->SetDisableGravity(true);
				me->SetControlled(true, UNIT_STATE_ROOT);

                Movement::MoveSplineInit init(me);
                init.MoveTo(EyeOFAcherusFallPoint.GetPositionX(), EyeOFAcherusFallPoint.GetPositionY(), EyeOFAcherusFallPoint.GetPositionZ(), false);
                init.SetFall();
                me->GetMotionMaster()->LaunchMoveSpline(std::move(init), POINT_EYE_FALL, MOTION_PRIORITY_NORMAL, POINT_MOTION_TYPE);
				
				_events.ScheduleEvent(EVENT_MOVE_START, 5000);
            }

            void OnCharmed(bool /*apply*/) override { }

            void UpdateAI(uint32 diff) override
            {
                _events.Update(diff);

                while (uint32 eventId = _events.ExecuteEvent())
                {
                    switch (eventId)
                    {
                        case EVENT_MOVE_START:
                        {
							 me->CastSpell(me, SPELL_EYE_FLIGHT_BOOST);
							
                            me->SetControlled(false, UNIT_STATE_ROOT);
                            if (Player* owner = me->GetCharmerOrOwner()->ToPlayer())
                            {
                                for (uint8 i = 0; i < MAX_MOVE_TYPE; ++i)
                                    me->SetSpeedRate(UnitMoveType(i), owner->GetSpeedRate(UnitMoveType(i)));
                                Talk(TALK_MOVE_START, owner);
                            }
                            me->GetMotionMaster()->MovePath(me->GetEntry() * 100, false);
                            break;
                        }
                        default:
                            break;
                    }
                }
            }

            void MovementInform(uint32 movementType, uint32 pointId) override
            {
                if (movementType == WAYPOINT_MOTION_TYPE && pointId == POINT_EYE_MOVE_END - 1)
                {
                    me->RemoveAllAuras();

                    if (Player* owner = me->GetCharmerOrOwner()->ToPlayer())
                    {
                        owner->RemoveAura(SPELL_EYE_FLIGHT_BOOST);
                        for (uint8 i = 0; i < MAX_MOVE_TYPE; ++i)
                            me->SetSpeedRate(UnitMoveType(i), owner->GetSpeedRate(UnitMoveType(i)));

                        Talk(TALK_CONTROL, owner);
                    }
                    me->SetDisableGravity(false);
					me->CastSpell(me, SPELL_EYE_FLIGHT);
                }
            }

        private:
            EventMap _events;
        };

        CreatureAI* GetAI(Creature* creature) const override
        {
            return new npc_eye_of_acherusAI(creature);
        }
};`

This works perfect! I tried it!

**Comment by illfated** [comment]
it would have been more useful if you pasted a diff or at least encapsulated the code in ```cpp block quote (MarkDown tag).
Anyway, here is what I managed to recreate in Notepad++ based on what you pasted above (there could be mistakes):
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index f4facc19d0..fcceff061a 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -375,19 +375,21 @@ class npc_eye_of_acherus : public CreatureScript
         struct npc_eye_of_acherusAI : public ScriptedAI
         {
             npc_eye_of_acherusAI(Creature* creature) : ScriptedAI(creature)
             {
                 me->SetDisplayId(me->GetCreatureTemplate()->Modelid1);
-                if (Player* owner = me->GetCharmerOrOwner()->ToPlayer())
-                    owner->SendAutoRepeatCancel(me);
-
+                me->CastSpell(me, SPELL_EYE_VISUAL, true);
                 me->SetReactState(REACT_PASSIVE);
+                me->SetDisableGravity(true);
+                me->SetControlled(true, UNIT_STATE_ROOT);
 
                 Movement::MoveSplineInit init(me);
                 init.MoveTo(EyeOFAcherusFallPoint.GetPositionX(), EyeOFAcherusFallPoint.GetPositionY(), EyeOFAcherusFallPoint.GetPositionZ(), false);
                 init.SetFall();
                 me->GetMotionMaster()->LaunchMoveSpline(std::move(init), POINT_EYE_FALL, MOTION_PRIORITY_NORMAL, POINT_MOTION_TYPE);
+
+                _events.ScheduleEvent(EVENT_MOVE_START, 5000);
             }
 
             void OnCharmed(bool /*apply*/) override { }
 
             void UpdateAI(uint32 diff) override
@@ -398,11 +400,11 @@ class npc_eye_of_acherus : public CreatureScript
                 {
                     switch (eventId)
                     {
                         case EVENT_MOVE_START:
                         {
-                            DoCast(me, SPELL_EYE_FLIGHT_BOOST);
+                            me->CastSpell(me, SPELL_EYE_FLIGHT_BOOST);
 
                             me->SetControlled(false, UNIT_STATE_ROOT);
                             if (Player* owner = me->GetCharmerOrOwner()->ToPlayer())
                             {
                                 for (uint8 i = 0; i < MAX_MOVE_TYPE; ++i)
@@ -420,11 +422,10 @@ class npc_eye_of_acherus : public CreatureScript
 
             void MovementInform(uint32 movementType, uint32 pointId) override
             {
                 if (movementType == WAYPOINT_MOTION_TYPE && pointId == POINT_EYE_MOVE_END - 1)
                 {
-                    me->SetSheath(SHEATH_STATE_MELEE);
                     me->RemoveAllAuras();
 
                     if (Player* owner = me->GetCharmerOrOwner()->ToPlayer())
                     {
                         owner->RemoveAura(SPELL_EYE_FLIGHT_BOOST);
@@ -432,18 +433,11 @@ class npc_eye_of_acherus : public CreatureScript
                             me->SetSpeedRate(UnitMoveType(i), owner->GetSpeedRate(UnitMoveType(i)));
 
                         Talk(TALK_CONTROL, owner);
                     }
                     me->SetDisableGravity(false);
-                    DoCast(me, SPELL_EYE_FLIGHT);
-                }
-
-                if (movementType == POINT_MOTION_TYPE && pointId == POINT_EYE_FALL)
-                {
-                    me->SetDisableGravity(true);
-                    me->SetControlled(true, UNIT_STATE_ROOT);
-                    _events.ScheduleEvent(EVENT_MOVE_START, 5000);
+                    me->CastSpell(me, SPELL_EYE_FLIGHT);
                 }
             }
 
         private:
             EventMap _events;
```
(I have not tested this, nor have I taken the time to find out if any of this is valid TC code)

**Comment by Aokromes** [comment]
It's https://github.com/TrinityCore/TrinityCore/pull/22054/files
