### ISSUE TITLE
Lieutenant Horatio Laine won't give the quest 'Murder Was The Case That They Gave Me' unless Player has the quest 'Hero's Call: Westfall!'

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20849]
**Description:** Lieutenant Horatio Laine won't give the quest 'Murder Was The Case That They Gave Me' unless Player has the quest 'Hero's Call: Westfall!'

**Expected behaviour:** the lieutenant must give the quest even when the Player doesn't have the other quest.

**Steps to reproduce the problem:**

1. Create a level 10 Alliance character.
2. Travel to Westfall.
3. Talk to the lieutenant.
4. The quest 'Murder Was The Case That They Gave Me' won't appear as an option (but another two will as intended).
5. Travel to one of Stormwind's Hero's Board.
6. Click the board
7. Get the quest 'Hero's Call: Westfall!'
8. Travel back to Westfall to the lieutenant
9. Speak to him
10. The quest 'Murder Was The Case That They Gave Me' will now appear as an option.

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by nubqt** [comment]
I know how to solve this issue with smart_scripts but I'm working on other issues at the moment.

For those interested:

1. Remove the hardcoded requirement from the quest database.
2. But, you must now make sure that 'Hero's Call: Westfall!' appears on Stormwind's Hero's Board if-and-only-if the Player has NOT completed the quest 'Murder Was The Case That They Gave Me,' ie: make the breadcrumb quest optional.

**Comment by tkrokli** [comment]
- https://wow.gamepedia.com/Quest:Murder_Was_The_Case_That_They_Gave_Me#Progression

OK, I see. https://wow.gamepedia.com/Quest:Hero%27s_Call:_Westfall! is only a breadcrumb quest, not required.

**Comment by nubqt** [comment]
Yes, if I recall correctly, I fixed it in my dev env by setting `NextQuestID` to '0' in `quest_template_addon` for both entries. The query for that would be:

```sql
UPDATE `quest_template_addon` SET `NextQuestID`= '0' WHERE `id` IN ( '26378', '28562' );
```

But that's not the only fix. You must also make sure that neither the other NPC nor the HCB give the quest after the Player completes 'Murder_Was_The_Case_That_They_Gave_Me.' Otherwise, the Player would already know about Westfall while the HCB would still be telling him to go back to Westfall. I didn't fix that part in my dev env so I don't know what the SQL query would look like for that one.

**Comment by nubqt** [comment]
**Forensics:** quest was incorrectly set as having a prerequesite. In addition, one of the Hero's Call board quest had a QuestType set incorrectly.

**Suggested fix**:

```sql
-- Defining quests to modify
SET @QUEST_MURDER_WAS_THE_CASE_THEY_GAVE_ME = '26209';
SET @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_NPC = '26378';
SET @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_HCB = '28562';

-- Removing unnecessary requirement:
--   * Player should be able to get @QUEST_MURDER_WAS_THE_CASE_THEY_GAVE_ME without having to complete
--     @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_NPC or @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_HCB
SET @NONE = '0';
UPDATE `quest_template` SET `RewardNextQuest` = @NONE WHERE `id` IN ( @QUEST_HEROS_CALL_WESTFALL_1, @QUEST_HEROS_CALL_WESTFALL_2 );
UPDATE `quest_template_addon` SET `NextQuestId` = @NONE WHERE `id` IN ( @QUEST_HEROS_CALL_WESTFALL_1, @QUEST_HEROS_CALL_WESTFALL_2 );

-- But Player should NOT be able to get either quest if he has already completed the quest 'Murder Was The Case They Gave Me'
SET @MAKE_QUEST_AVAILABLE_TO_PLAYER = '19';
SET @IF_PLAYER_HAS_BEEN_REWARDED_QUEST = '8';
SET @NEGATE_CONDITION = '1';
SET @COMMENT = 'Checks if Player has not been rewarded quest';
INSERT INTO `conditions` VALUES ( @MAKE_QUEST_AVAILABLE_TO_PLAYER, '0', @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_NPC, '0', '0', @IF_PLAYER_HAS_BEEN_REWARDED_QUEST, '0', @QUEST_MURDER_WAS_THE_CASE_THEY_GAVE_ME, '0', '0', @NEGATE_CONDITION, '0', '0', '', @COMMENT );
INSERT INTO `conditions` VALUES ( @MAKE_QUEST_AVAILABLE_TO_PLAYER, '0', @QUEST_HEROS_CALL_WESTFALL_OBTAINED_FROM_HCB, '0', '0', @IF_PLAYER_HAS_BEEN_REWARDED_QUEST, '0', @QUEST_MURDER_WAS_THE_CASE_THEY_GAVE_ME, '0', '0', @NEGATE_CONDITION, '0', '0', '', @COMMENT );

-- Fixing QuestType which was set incorrectly to '1' thus disabling the quest
SET @QUEST_ENABLED = '2';
UPDATE `quest_template` SET `QuestType` = @QUEST_ENABLED WHERE `id` = @QUEST_HEROS_CALL_WESTFALL_2;
```

Please test and confirm suggestion.

<img width="1378" alt="screen shot 2017-11-13 at 1 42 53 pm" src="https://user-images.githubusercontent.com/33535711/32743242-d812018e-c879-11e7-9dd5-01b9f21b1f90.png">

<img width="1378" alt="screen shot 2017-11-13 at 1 43 16 pm" src="https://user-images.githubusercontent.com/33535711/32743251-e02db476-c879-11e7-8512-4389fbf0d3ac.png">

<img width="1378" alt="screen shot 2017-11-13 at 1 45 11 pm" src="https://user-images.githubusercontent.com/33535711/32743269-eac60500-c879-11e7-82f0-651a7bde78db.png">

<img width="1378" alt="screen shot 2017-11-13 at 1 47 15 pm" src="https://user-images.githubusercontent.com/33535711/32743288-f4909b86-c879-11e7-9307-af24c0ff06ad.png">

<img width="1378" alt="screen shot 2017-11-13 at 1 48 50 pm" src="https://user-images.githubusercontent.com/33535711/32743297-fdf791ca-c879-11e7-8a76-a5bd53002b56.png">

<img width="1378" alt="screen shot 2017-11-13 at 1 49 14 pm" src="https://user-images.githubusercontent.com/33535711/32743310-06d1c34c-c87a-11e7-8aa0-2592e0d37538.png">

**Comment by tkrokli** [comment]
Looks like a good starting point, will be nice to see feedback from those of you who still have got the 7.2.0 or 7.2.5 game client.

SQL format details: Please note that TC does not use ' ' (apostrophes) around integers (unless defined in DB as char/varchar/text).
