### ISSUE TITLE
[3.3.5] Scripts/ScarletEnclave: Grand Theft Palamino (quest 12680) Deliver Stolen Horse (spell 52264)

### ISSUE THREAD

**Issue by Rockz1152** [TrinityCore/TrinityCore#20844]
**Description:**

During the quest Grand Theft Palamino, after stealing and riding back the horse to Salanar the Horseman, the player uses the "Deliver Stolen Horse" ability to gain the final credit to complete the quest. When this happens the player exits/dismouts the horse in order to turn in the quest.

**Current behaviour:**

Using the spell gives the player credit for the quest, but does not exit the player from the horse. The player cannot turn in the quest until they exit the vehicle.

**Expected behaviour:**

Using the spell gives the player quest credit and exits them from the vehicle so they can turn in the quest.
Here is a reference video to show the intended behavior: https://youtu.be/5wlMkJOekxc?t=159

**Steps to reproduce the problem:**

1. Make a deathknight
2. .quest add 12680
3. .go xyz 2218 -5817 101.54 609
4. ride horse back to Death's Breach
5. approach Salanar the Horseman and use "Deliver Stolen Horse"
 
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3e74ef1528db 2017-11-10 23:45:42 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Fedora 26

**Comment by tkrokli** [comment]
Maybe there should be some form of `ExitVehicle()` at the end of this part of the script?

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L773-L793

Then again, that script could really do with an overhaul. IIRC the event is missing where the nearby Dark Rider of Acherus (28654) should cast a whirlwind around the stolen palomino and despawn it while saying `The realm of shadows awaits...` (28794).

**Comment by tkrokli** [comment]
Related info:
- https://wow.gamepedia.com/Quest:Grand_Theft_Palomino
- http://www.wowhead.com/quest=12680/grand-theft-palomino
- http://www.wowhead.com/spell=52264/deliver-stolen-horse
  - Effect 1: Dummy (Server-side script)
  - Kill Credit ([[Phase 1] Havenshrie Horse Credit, Step 01](http://www.wowhead.com/npc=28767/phase-1-havenshrie-horse-credit-step-01))

**Comment by burbur** [comment]
Maybe it should be scripted in the Effect 1: Dummy (Server-side script) of the spell 52264, and not on the npc himself. 
The script can just remove the aura given by the horse (the one you have when to ride him) since in the video you posted the horse was still there, and despawned after the knight on the right hit it.

**Comment by burbur** [comment]
Hello there, sorry for double comment.. it is me, or this work even if you are not in range of Salanar?
I mean the quest credit part. 

I've tried on a fresh installation, but as soon as I took the horse and pressed the deliver horse spell I got the credit.

**Comment by rockz1152** [comment]
> it is me, or this work even if you are not in range of Salanar?
I mean the quest credit part.

Not just you, same for me too.

**Comment by tkrokli** [comment]
> Then again, that script could really do with an overhaul.

I should know, I wrote parts of it and I am not proud of the results.

**Comment by burbur** [comment]
So, here's my solution with brief explanation. (But I do not know Trinity standards very well, so feel free to modify it!)

First things first, SQL part:
```sql
DELETE FROM spell_script_names WHERE  spell_id=52267 AND ScriptName="spell_gen_despawn_self";
INSERT INTO spell_script_names (spell_id, ScriptName) VALUES (52264, "spell_deliver_stolen_horse");
```

These two are not formatted in TC style. 
The first one is needed because otherwise the Dark Rider of Acherus, after cast, despawn himself, and you cannot see the bubble chat: "The realm of shadows awaits..."
The second one is needed for the spell script of the spell Deliver Stolen Horse

Core part:
```diff
diff --git a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
index d11f352..1c07712 100644
--- a/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
+++ b/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
@@ -642,7 +642,11 @@ public:
 enum DarkRiderOfAcherus
 {
     SAY_DARK_RIDER              = 0,
-    SPELL_DESPAWN_HORSE         = 51918
+    SPELL_DESPAWN_HORSE         = 52267,
+
+    EVENT_START_MOVE            = 0,
+    EVENT_DESPAWN_HORSE,
+    EVENT_END_SCRIPT
 };
```
So, just correction of the spell to despawn the horse. The previous one was "Revive - Description: Resurrects a fallen death knight." and conversion to Event System for the Dark Rider of Acherus. 

 ```diff
 class npc_dark_rider_of_acherus : public CreatureScript
@@ -652,78 +656,57 @@ class npc_dark_rider_of_acherus : public CreatureScript
 
         struct npc_dark_rider_of_acherusAI : public ScriptedAI
         {
-            npc_dark_rider_of_acherusAI(Creature* creature) : ScriptedAI(creature)
-            {
-                Initialize();
-            }
-
-            void Initialize()
-            {
-                PhaseTimer = 4000;
-                Phase = 0;
-                Intro = false;
-                TargetGUID.Clear();
-            }
+            npc_dark_rider_of_acherusAI(Creature* creature) : ScriptedAI(creature) { }
 
             void Reset() override
             {
-                Initialize();
+                HorseGUID.Clear();
+
+                if (TempSummon* summon = me->ToTempSummon())
+                    if (Unit* summoner = summon->GetSummoner())
+                        HorseGUID = summoner->GetGUID();
+
+                events.ScheduleEvent(EVENT_START_MOVE, 0);
+                events.ScheduleEvent(EVENT_DESPAWN_HORSE, 5000);
+                events.ScheduleEvent(EVENT_END_SCRIPT, 12000);
             }
 
             void UpdateAI(uint32 diff) override
             {
-                if (!Intro || !TargetGUID)
-                    return;
+                events.Update(diff);
 
-                if (PhaseTimer <= diff)
+                switch (uint32 eventId = events.ExecuteEvent())
                 {
-                    switch (Phase)
-                    {
-                       case 0:
-                            Talk(SAY_DARK_RIDER);
-                            PhaseTimer = 5000;
-                            Phase = 1;
-                            break;
-                        case 1:
-                            if (Unit* target = ObjectAccessor::GetUnit(*me, TargetGUID))
-                                DoCast(target, SPELL_DESPAWN_HORSE, true);
-                            PhaseTimer = 3000;
-                            Phase = 2;
-                            break;
-                        case 2:
-                            me->SetVisible(false);
-                            PhaseTimer = 2000;
-                            Phase = 3;
-                            break;
-                        case 3:
-                            me->DespawnOrUnsummon();
-                            break;
-                        default:
-                            break;
-                    }
+                    case EVENT_START_MOVE:
+                        me->SetTarget(HorseGUID);
+                        me->SetSpeedRate(MOVE_RUN, 0.4f);
+
+                        if (Creature* horse = ObjectAccessor::GetCreature(*me, HorseGUID))
+                            me->GetMotionMaster()->MoveFollow(horse, 2.0f, 0.f);
+                        break;
+                    case EVENT_DESPAWN_HORSE:
+                        Talk(SAY_DARK_RIDER);
+                        if (Creature* horse = ObjectAccessor::GetCreature(*me, HorseGUID))
+                            DoCast(horse, SPELL_DESPAWN_HORSE, true);
+                        break;
+                    case EVENT_END_SCRIPT:
+                        me->DespawnOrUnsummon();
+                        break;
+                    default:
+                        break;
                 }
-                else
-                    PhaseTimer -= diff;
             }
 
-            void InitDespawnHorse(Unit* who)
+            void SpellHitTarget(Unit* target, SpellInfo const* spell) override
             {
-                if (!who)
-                    return;
-
-                TargetGUID = who->GetGUID();
-                me->SetWalk(true);
-                me->SetSpeedRate(MOVE_RUN, 0.4f);
-                me->GetMotionMaster()->MoveChase(who);
-                me->SetTarget(TargetGUID);
-                Intro = true;
+                if (spell->Id == SPELL_DESPAWN_HORSE && target->GetGUID() == HorseGUID)
+                    if (Creature* creature = target->ToCreature())
+                        creature->DespawnOrUnsummon(2500);
             }
 
         private:
-            uint32 PhaseTimer;
-            uint32 Phase;
-            bool Intro;
-            ObjectGuid TargetGUID;
+            ObjectGuid HorseGUID;
+            EventMap events;
         };
 ```
So, here's the rework of the Dark Rider of Acherus. I removed the uint32 timer event management and renamed the ObjectGUID variable. 
Since the Rider is summoned by a spell, we can use the TempSummon and get the summoner without the need of casting an AI from another script. 

me->GetMotionMaster()->MoveFollow(...) was needed because otherwise the Rider did not go towards the horse, since, IIRC, the MoveChase is needed for an enemy, and the horse is not an enemy in that moment.

The SpellHitTarget is to force despawn the horse after the animations. 
Timers are guessed. 

 ```diff
         CreatureAI* GetAI(Creature* creature) const override
@@ -770,28 +753,6 @@ public:
             return false;
         }
 
-        void SpellHit(Unit* caster, SpellInfo const* spell) override
-        {
-            if (spell->Id == SPELL_DELIVER_STOLEN_HORSE)
-            {
-                if (caster->GetTypeId() == TYPEID_UNIT && caster->IsVehicle())
-                {
-                    if (Unit* charmer = caster->GetCharmer())
-                    {
-                        if (charmer->HasAura(SPELL_EFFECT_STOLEN_HORSE))
-                        {
-                            charmer->RemoveAurasDueToSpell(SPELL_EFFECT_STOLEN_HORSE);
-                            caster->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
-                            caster->SetFaction(FACTION_FRIENDLY);
-                            DoCast(caster, SPELL_CALL_DARK_RIDER, true);
-                            if (Creature* Dark_Rider = me->FindNearestCreature(NPC_DARK_RIDER_OF_ACHERUS, 15))
-                                ENSURE_AI(npc_dark_rider_of_acherus::npc_dark_rider_of_acherusAI, Dark_Rider->AI())->InitDespawnHorse(caster);
-                        }
-                    }
-                }
-            }
-        }
-
         void MoveInLineOfSight(Unit* who) override
         {
             ScriptedAI::MoveInLineOfSight(who);
 ```

Straightforward: this part was moved from Salanar script to the Deliver Stolen Horse spell script, since the spell script was needed to correct the wrong behaviour of getting the quest credit even if not near Salanar. 

 ```diff
@@ -828,6 +789,64 @@ public:
     }
 };
 
+class spell_deliver_stolen_horse : public SpellScriptLoader
+{
+public:
+    spell_deliver_stolen_horse() : SpellScriptLoader("spell_deliver_stolen_horse") { }
+
+    class spell_deliver_stolen_horse_SpellScript : public SpellScript
+    {
+        PrepareSpellScript(spell_deliver_stolen_horse_SpellScript);
+
+        bool Validate(SpellInfo const* /*spellInfo*/) override
+        {
+            return ValidateSpellInfo({ SPELL_DELIVER_STOLEN_HORSE, SPELL_EFFECT_STOLEN_HORSE });
+        }
+
+        void CheckHitSalanar(SpellEffIndex effIndex)
+        {
+            // Can only hit Salanar due to TARGET_UNIT_NEARBY_ENTRY
+            if (Unit* salanar = GetHitUnit())
+                _salanarNear = true;
+        }
+
+        void CheckHitTarget(SpellEffIndex effIndex)
+        {
+            if (!_salanarNear)
+            {
+                PreventHitEffect(effIndex);
+                return;
+            }
+
+            if (Player* player = GetHitPlayer())
+                player->RemoveAurasDueToSpell(SPELL_EFFECT_STOLEN_HORSE);
+
+            if (Unit* caster = GetCaster())
+            {
+                caster->RemoveAurasDueToSpell(SPELL_EFFECT_STOLEN_HORSE);
+
+                caster->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
+                caster->SetFaction(FACTION_FRIENDLY);
+
+                caster->CastSpell(caster, SPELL_CALL_DARK_RIDER, true);
+            }
+        }
+
+        void Register() override
+        {
+            OnEffectHitTarget += SpellEffectFn(spell_deliver_stolen_horse_SpellScript::CheckHitSalanar, EFFECT_0, SPELL_EFFECT_DUMMY);
+            OnEffectHitTarget += SpellEffectFn(spell_deliver_stolen_horse_SpellScript::CheckHitTarget, EFFECT_1, SPELL_EFFECT_KILL_CREDIT2);
+        }
+
+        bool _salanarNear;
+    };
+
+    SpellScript* GetSpellScript() const override
+    {
+        return new spell_deliver_stolen_horse_SpellScript();
+    }
+};
 
 // correct way: 52312 52314 52555 ...
@@ -1244,6 +1262,7 @@ void AddSC_the_scarlet_enclave_c1()
     new npc_eye_of_acherus();
     new npc_death_knight_initiate();
     new npc_salanar_the_horseman();
+    new spell_deliver_stolen_horse();
     new npc_dark_rider_of_acherus();
     new npc_ros_dark_rider();
     new npc_dkc1_gothik();
```

Spell script for the spell Deliver Stolen Horse. 
Since it gives the credit even if not near Salanar we need a check. 

The spell already has the right condition in the database, so it can only hit Salanar. 
If we hit Salanar, then the second effect, Kill Credit, can be executed and we can remove the aura from the Player, the target of the spell, and the caster (the horse) to dismount. 
This is done because the Horse has the aura from the Stolen Horse (52263) spell. 

`
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
Aura Id 236 (SPELL_AURA_CONTROL_VEHICLE), value = 1, misc = 0 (0), miscB = 0, periodic = 0
`

and so the Horse can summon the Dark Rider and set the friendly flags. 

That's it.

**Comment by Aokromes** [comment]
we delete spell_script_names  by ScriptName, we put ` around column names, and we use pull requests for c++ fixes :)

**Comment by burbur** [comment]
Yeah I know it but it was a mess to comment! :)

If someone can test it, then I can do a pull request without problem.

To do it, I need to include the sql file, right? It's ok to "insert" in that way or should i do a delete/insert for the second row?

**Comment by tkrokli** [comment]
SQL part could look something like this:
```sql
DELETE FROM `spell_script_names` WHERE  `ScriptName` IN ('spell_gen_despawn_self', 'spell_deliver_stolen_horse');
INSERT INTO `spell_script_names` (spell_id, ScriptName) VALUES (52264, 'spell_deliver_stolen_horse');
```
Then again, I wonder why there are a bunch of differently named spell IDs linked to `spell_gen_despawn_self` in TDB 335.63:
```sql
SELECT * FROM `spell_script_names` WHERE `ScriptName`= 'spell_gen_despawn_self';
```
```
spell_id  ScriptName
--------  ----------------------
   15998  spell_gen_despawn_self
   25952  spell_gen_despawn_self
   29435  spell_gen_despawn_self
   45980  spell_gen_despawn_self
   51592  spell_gen_despawn_self
   51910  spell_gen_despawn_self
   52267  spell_gen_despawn_self
   54420  spell_gen_despawn_self
```
- http://www.wowhead.com/spell=15998/capture-worg-pup
- http://www.wowhead.com/spell=25952/reindeer-dust-effect
- http://www.wowhead.com/spell=29435/capture-female-kaliri-hatchling
- http://www.wowhead.com/spell=45980/re-cursive-transmatter-injection
- http://www.wowhead.com/spell=51592/pickup-primordial-hatchling
- http://www.wowhead.com/spell=51910/kickin-nass-quest-completion
- http://www.wowhead.com/spell=52267/despawn-horse
- http://www.wowhead.com/spell=54420/deliver-gryphon

**Comment by burbur** [comment]
Yes, I've seen it too, that's why I did the delete with the spell id.

**Comment by tkrokli** [comment]
I suppose we could simplify the SQL part to this:
```sql
UPDATE `spell_script_names` SET `ScriptName`='spell_deliver_stolen_horse' WHERE `spell_id`=52267;
```

**Comment by burbur** [comment]
Uhm @tkrokli , that's wrong because that script is for 52264, not 52267. 
The 52267 one needs to be cleared, because otherwise it despawn the Dark Rider of Acherus after cast.

**Comment by tkrokli** [comment]
Thanks for the correction, I was jumping between too many spells and copy/pasting the values.
Updated the query in my previous post. Just need confirmation from another TC member.

**Comment by burbur** [comment]
Yeah, np!

But I think the update is wrong, because in my database there was no row for that id, that's why I've used the Insert statement.

**Comment by tkrokli** [comment]
Good point. I'm deffo too tired from a cold I got.
The only way left to do it, as I see it, has to be:
```sql
-- repeal/replace some wrong spells
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_gen_despawn_self', 'spell_deliver_stolen_horse');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(15998, 'spell_gen_despawn_self'),
(25952, 'spell_gen_despawn_self'),
(29435, 'spell_gen_despawn_self'),
(45980, 'spell_gen_despawn_self'),
(51592, 'spell_gen_despawn_self'),
(51910, 'spell_gen_despawn_self'),
(52264, 'spell_deliver_stolen_horse'),
(52267, 'spell_deliver_stolen_horse'),
(54420, 'spell_gen_despawn_self');
```

**Comment by burbur** [comment]
@tkrokli ahah np!

But still, the 52267 should have no script ahahah!
Actually in the db, there is no script name for 52264 and the 52267 has the spell_gen_despawn_self. 

It should be:
52264 - spell_deliver_stolen_horse
52267 - no script!

So:
```sql
-- repeal/replace some wrong spells
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_gen_despawn_self', 'spell_deliver_stolen_horse');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(15998, 'spell_gen_despawn_self'),
(25952, 'spell_gen_despawn_self'),
(29435, 'spell_gen_despawn_self'),
(45980, 'spell_gen_despawn_self'),
(51592, 'spell_gen_despawn_self'),
(51910, 'spell_gen_despawn_self'),
(52264, 'spell_deliver_stolen_horse'),
(54420, 'spell_gen_despawn_self');
```

**Comment by tkrokli** [comment]
Very well. Hope you can start up a Pull Request so we can continue working on this.

**Comment by tkrokli** [comment]
As jackpoz said in comment https://github.com/TrinityCore/TrinityCore/pull/20897#issuecomment-357319302 upon closing the PR [abandoned],
ask there if someone else wants to take over the work needed to complete the PR-

**Comment by Sorikoff** [comment]
Can be closed.
