### ISSUE TITLE
Breastplates and legplates not rendering on Female Gnome Warriors

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20850]
**Description:** plate chest items and plate leg items do not render on Gnome Female Warriors.

I have not been able to test this in males nor in other classes so I'm limiting the description to what I have been able to verify.

**Expected behaviour:** worn items should render.

**Steps to reproduce the problem:**

1. Create a level 1 Female Gnome Warrior.
2. Send her any plate chest and leg item she can wear (increase her level if necessary; but you can try items 57562, 127431, 127683, and 57525)
3. Look at the character as she runs through the world.
4. Look at the character info.
5. Now dress both items in the dressing room (they show up there)
6. Logout to character screen (they show up there).

**Branch(es):** master

**TC rev. hash/commit:** 733441922b78

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS 10.3.1

**Comment by nubqt** [comment]
How the character looks naked:

<img width="1378" alt="screen shot 2017-11-12 at 7 06 33 pm" src="https://user-images.githubusercontent.com/33535711/32705054-a4189880-c7dd-11e7-82bf-e3adad6db91b.png">

How she looks with low level items:

<img width="1378" alt="screen shot 2017-11-12 at 7 07 04 pm" src="https://user-images.githubusercontent.com/33535711/32705062-b5c8332e-c7dd-11e7-9e44-13685015840c.png">

How she looks with higher level items:

<img width="1378" alt="screen shot 2017-11-12 at 7 07 16 pm" src="https://user-images.githubusercontent.com/33535711/32705067-bd4cfec2-c7dd-11e7-9674-d1485808c9f0.png">

**Comment by nubqt** [comment]
I apologize in advance if this is something that has to do with my own installation of TrinityCore. So in order to eliminate that possibility could someone please try to replicate this issue in Windows and in MacOS?

**Comment by funjoker** [comment]
It's an aura.
Gnomes normaly fight their way out of the poisned gnomeregan.

It's bugged intro.

http://www.wowhead.com/spell=80653

remove this aura

**Comment by nubqt** [comment]
Confirmed @funjoker findings. This is caused by #16224 not being fixed yet.

**Comment by Aokromes** [comment]
It's not a bug, checked on ptr and as long you have the aura it's blizzlike.
