### ISSUE TITLE
[3.3.5] DB/SAI: Apprentice Mirveda (npc 15402), Unexpected Results (quest 8488)

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#20853]
**Description**:
Starting the quest, three enemies spawn and attack Apprentice Mirveda. It is the player's job to defend her.

**Current behaviour**: 
If the player does too good a job of defending Apprentice Mirveda and she never gets in combat with the three enemies, the event stalls, the apprentice never exits the event state and you are not given credit for defending her. She also will not exit this state until she is killed and respawned. If the player allows her to get into combat with and then kills the three enemies, the event will end normally and the player receives quest credit properly.

**Expected behaviour**: 
Once all three enemies are killed, the player should receive quest credit regardless if Apprentice Mirveda entered combat or not.

**Steps to reproduce the problem**:
1. make a bloodelf
2. .quest add 9254
3. .quest reward 9254
4. .quest add 8487
5. .quest complete 8487
6. .go xyz 8706 -7161 45 530
7. turn in quest and then accept the next quest once it's available
8. kill the 3 enemies before they reach Apprentice Mirveda

**Branch(es)**:  3.3.5

**TC hash/commit**:  TrinityCore rev. 3e74ef1528db 2017-11-10 23:45:42 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version**:  TDB_full_world_335.63_2017_04_18

**Operating system**:  Fedora 26

**Additional Info**: Current SAI implemented https://github.com/TrinityCore/TrinityCore/commit/c5394842bb17e30535e0b65eb9f429a2529c6c94

**Comment by Killyana** [comment]
Try to test this in different situations, In combat, out of combat, and repeat it many times to see if fails or not.
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=15958 AND `source_type`=0 AND id=5;
DELETE FROM `smart_scripts` WHERE `entryorguid`=15656 AND `source_type`=0 AND id=7;
DELETE FROM `smart_scripts` WHERE `entryorguid`=15402 AND `source_type`=0 AND id>4;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(15958,0,5,0,6,2,100,0,0,0,0,0,63,1,1,0,0,0,0,19,15402,100,0,0,0,0,0,"Gharsul the Remorseless - On death - Set counter"),
(15656,0,7,0,6,2,100,0,0,0,0,0,63,1,1,0,0,0,0,19,15402,100,0,0,0,0,0,"AngerShadee - On death - Set counter"),
(15402,0,5,6,77,1,100,0,1,3,0,0,15,8488,0,0,0,0,0,12,1,0,0,0,0,0,0,"Apprentice Mirveda - On counter - Complete Quest Unexpected Results"),
(15402,0,6,7,61,1,100,0,0,0,0,0,63,1,0,1,0,0,0,1,0,0,0,0,0,0,0,"Apprentice Mirveda - On counter - Reset counter"),
(15402,0,7,0,61,1,100,0,0,0,0,0,80,1540202,2,0,0,0,0,1,0,0,0,0,0,0,0,"Apprentice Mirveda - Linked with Previous Event - Run Script"),
(15402,0,8,0,11,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Apprentice Mirveda - On Spawn - Set Immune to NPC");

**Comment by rockz1152** [comment]
Thanks for looking into it. I will test tonight and report back.

**Comment by velinath** [comment]
Script works under all circumstances. I abandoned the quest a few times to test, e.g., killing the mobs right at their spawn point & waiting until they got to Mirveda, making sure that the counter reset properly. Mirveda actually kills all of the mobs by herself which seems weird, but if you kill her with `.die` it fails the quest properly as well.

**Comment by rockz1152** [comment]
@Killyana 
Script seems to work good. I've found one way of breaking it.
Gharsul seems to run faster than the angershades, if you engage and kill him after he reaches WP1 but before the angershades do, the quest bugs out. kind of an edge case but still. I believe this implementation is much better than what was in place before.

**Comment by Killyana** [comment]
Because the call attack target on wp1 doesn't happen, caused by the actual issue with waypoints.
