### ISSUE TITLE
'Rune of Fire' can be casted on any NPC

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20869]
**Description:** [Rune of Fire](http://www.wowhead.com/item=56009/rune-of-fire) can be casted on any NPC

**Expected behaviour:** the rune should only be allowed to be casted on [Constriction Totem](http://www.wowhead.com/npc=41202/constriction-totem)

**Steps to reproduce the problem:**

1. Create a level 7 Alliance character.
2. Get the character to Dun Morogh
3. Get the quest [Pushing Forward](http://www.wowhead.com/quest=25792/pushing-forward)
4. Click any NPC
5. Click the Rune of Fire

**Branch(es):** master

**TC rev. hash/commit:** 733441922b78

**TDB version:** 720.00_2017_04_18

**Comment by nubqt** [comment]
Issue related to #16383.

**Comment by Killyana** [comment]
Just missing scripts as this area is not scripted, also there's already an issue.

**Comment by nubqt** [comment]
What's the other issue? #16383 is about kill credit, not about an unrestricted spell.

**Comment by Killyana** [comment]
Missing credit + missing condition for the spell = Quest not scripted
No need to open more than one issue in this case.

**Comment by nubqt** [comment]
I disgress. They seem to be two different issues that could be tackled separately. I don't see any issue in having two tickets for each and some sort of master list for 'Quest Pushing Forward needs full review.' Is there a documentation that shows the systematic process you followed to close this ticket?

**Comment by Aokromes** [comment]
It's only one bug: quest Pushing Forward lacking conditions because not scripted properly.

**Comment by nubqt** [comment]
I disagree with that statement and here's why:

The fix for the issue reported on _this_ ticket would be the following:

```sql
INSERT INTO `conditions` VALUES ( 17, 0, 77314, 0, 0, 29, 1, 41202, 5, 0, 0, 0, 0, '', 'Checks if the Player is near object by 5 yards' );
INSERT INTO `conditions` VALUES ( 17, 0, 77314, 0, 0, 31, 1, 3, 41202, 0, 0, 0, 0, '', 'Forces the player to target a Constriction Totem in order to use Rune of Fire' );
```

But guess what? You won't be able to fix it because you get the error 'You can't do that yet' which is documented in #20249 as a core side issue. @Killyana: could you please verify if this is true?

So, having said that, we need to differentiate among three different concepts in tickets: issues, outcomes, and goals. Our goal is to fix the Pushing Forward quest. But we can accomplish that goal by fixing different issues. The outcome of fixing the issue reported on this ticket is that Rune of Fire would only be castable on Costriction Totems. A different issue, such as #16383, can deal with the outcome of getting proper kill credits. This is known as the paradigm of [divide-and-conquer](https://effectivesoftwaredesign.com/2011/06/06/divide-and-conquer-coping-with-complexity/) and is [a best practice used in incident management](https://www.atlassian.com/it-unplugged/itsm/incident-management-expert-tips).

I strongly believe this ticket should be re-opened.

**Comment by Killyana** [comment]
Looks like this spell doesn't support the condition 17.
