### ISSUE TITLE
Quest 'Dungar Longdrink' not showing quest completed question mark on Map & Quest Log

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20876]
**Description:** Quest 'Dungar Longdrink' not showing quest completed question mark on Map & Quest Log

**Expected behaviour:** question mark should be shown on Map & Quest Log (world map).

**Steps to reproduce the problem:**

1. Create a level 5 Alliance character.
2. Get to Stormwind
3. Get the quest Dungar Longdrink (might have to .quest add since this is a chain)
4. Open your World Map

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-14 at 5 17 26 pm" src="https://user-images.githubusercontent.com/33535711/32808051-e19f20b0-c95f-11e7-8b5d-ee39352eb426.png">

**Comment by Aokromes** [comment]
I vote those 3 reports is because some of the wall of startup errors of https://github.com/TrinityCore/TrinityCore/issues/15829

**Comment by Ovahlord** [comment]
and missing points of interest.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20879
