### ISSUE TITLE
Quest 'Return to Argus' not showing quest completed question mark on Map & Quest Log

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20877]
**Description:** Quest 'Return to Argus' not showing quest completed question mark on Map & Quest Log

**Expected behaviour:** question mark should be shown on Map & Quest Log (world map).

**Steps to reproduce the problem:**

1. Create a level 5 Alliance character.
2. Get to Stormwind
3. Get the quest Return to Argus (might have to .quest add since this is a chain)
4. Open your World Map

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-14 at 5 20 47 pm" src="https://user-images.githubusercontent.com/33535711/32808237-593ce724-c960-11e7-977f-9d133ed700f7.png">

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20879
