### ISSUE TITLE
Quest 'Continue to Stormwind' not showing quest completed question mark on Map & Quest Log

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20875]
**Description:** Quest 'Continue to Stormwind' not showing quest completed question mark on Map & Quest Log

**Expected behaviour:** question mark should be shown on Map & Quest Log (world map).

**Steps to reproduce the problem:**

1. Create a level 5 Alliance character.
2. Get to Stormwind
3. Get the quest Continue to Stormwind (.quest add or get it in Elwynn Forest)
4. Open your World Map

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-14 at 5 13 43 pm" src="https://user-images.githubusercontent.com/33535711/32807885-64b56d8e-c95f-11e7-8e21-393855a55d59.png">

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20879
