### ISSUE TITLE
3.3.5 Quest A bumpy ride

### ISSUE THREAD

**Issue by ShewaWOW** [TrinityCore/TrinityCore#20872]
Description:

In the Sholazar Basin there are problems with the quest A bumpy ride from Hochschamene Rakjak.
The quest can not be completed. You will be dropped by the crocodile in the right place but the quest will not be considered finished.

Steps to reproduce the problem:

A video where the quest works properly
https://www.youtube.com/watch?v=5xEPxZ8x5tM

Branch(es):

3.3.5

TC rev. hash/commit:

TrinityCore rev. 6612ec47f4cd 2017-11-04 01:25:14 +0100 (3.3.5 branch) (Win32, Release, Static) (authserver)

TDB version:

335.63

Operating system:

Windows 7

This is my first contribution I hope I did everything right, I can only say what is not working
Sorry for the english I am using the Google translator

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/20310
No need to open new issues for quests using waypoints

**Comment by ShewaWOW** [comment]
Hello I do not know now what I did wrong the quest is not!
And the post to 20310 seems to be another quest. It was my first contribution and I do not dare to write one more now :(

**Comment by ShewaWOW** [comment]
It is not considered completed

**Comment by Killyana** [comment]
There's nothing wrong with this issue it's just related to another one effecting waypoints, hundreds of quests have the same bug as this one, so it's useless to open an issue for each one.
Once waypoints fixed, this quest could be completed againi.

**Comment by ShewaWOW** [comment]
ok Thank you for the explanation as I said I do not know me and just wanted to help and I just have to work with the Google translator

**Comment by ShewaWOW** [comment]
That means Quest where you can not finish I do not need to report?
