### ISSUE TITLE
[Master]AllowAchievementGain

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#20871]
**Description:**

AllowAchievementGain is no longer in Config and thus not disabling for GM's

**Current behaviour:**

Achievements do not disable for GM's

**Expected behaviour:**

Option do disable achievements

**Steps to reproduce the problem:**

1. World COnfig
**Branch(es):**

 master 

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/ae917e950bbf5e31cbf3c6c537bd34ba4ef883ad

**TDB version:**  720

**Operating system:** Win7

**Comment by Aokromes** [comment]
.gm on.
