### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type fmt::FormatError: unknown format code 'u' for string

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20878]
**Description:** libc++abi.dylib: terminating with uncaught exception of type fmt::FormatError: unknown format code 'u' for string

**Current behaviour:** issuing the command 'character changerace Alden' in the worldserver CLI generates that error in MacOS

**Expected behaviour:** command should not generate that error

**Steps to reproduce the problem:**

1. Create a character named Alden
2. Go to the worldserver CLI
3. Execute the command 'character changerace Alden'

**Branch(es):** master

**TC rev. hash/commit:** 733441922b78

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS 10.3.1

**Comment by nubqt** [comment]
Renamed the character to 'Anara' and after issuing the command 'character changerace Anara' I got the same error.

After the error no further commands can be issued to the worldserver and the process can't even be cancelled through CTRL+c.

Trying to restart the process fails because you get the error reported on #20032.

**Comment by nubqt** [comment]
Getting the same error in the CLI when I issue the command in-game. Can't logout from game after that.

**Comment by Shauren** [comment]
This is clearly a crash so where is the crash log?

**Comment by nubqt** [comment]
I'm completely unfamiliar with core issues since I only focus on DB ones. What do I need to upload to this ticket?

**Comment by Ascathor** [comment]
Whenever worldserver is reaching an undefined exception, there's a folder created. Within it, there's a logfile and a dmp (usually). If you compiled with debug or relwithdebuginfo, that log is useful to investigate the cause of issue.

**Comment by Shauren** [comment]
@Ascathor this guy is on mac, not windows (idk mac either)

**Comment by tkrokli** [comment]
Maybe we should ask @Gacko for assistance with this one.

**Comment by Gacko** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977313/OS+X+Core+Installation

You need to compile your binaries using the Debug or RelWithDebInfo configuration. The world server should produce the required information when it crashes then.
