### ISSUE TITLE
Quest: Disclosure

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20882]
**Description:**
http://www.wowhead.com/quest=12710/disclosure

This quest is required for completion as quest criteria for Sabotage (#20881).

**Current behaviour:**
Credit is not given for the quest Disclosure after following Malmortis around the upper level of the floating ziggurat Voltarus.

**Expected behaviour:**
Following Malmortis around the upper level of the floating ziggurat Voltarus should give you credit for Disclosure, and upon turning in Disclosure should fulfill quest criteria for Sabotage.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 30c2a96f16ef

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20310

**Comment by jerbookins** [comment]
#21030
