### ISSUE TITLE
Innkeeper Delaniel does not offer to set hearth with her

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20887]
**Description:** Innkeeper Delaniel does not offer to set hearth with her

**Expected behaviour:** innkeeper should offer to set hearth with her

**Steps to reproduce the problem:**

1. Create a level 4 Blood Elf character
2. Get the quest 'Completing the Delivery' (might have to .quest add since it's part of a chain)
3. Turn in the quest to Innkeeper Delaniel
4. Close the gossip window
5. Talk to her again
6. She offers the goods she sells rather than the options to set your hearth or see the goods she sells

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by Killyana** [comment]
I don't know why the gossip options are different from 3.3.5.
``` sql
DELETE FROM `gossip_menu_option`  WHERE `MenuID` IN (6620);
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(6620, 0, 0, "Trick or Treat!", 10693, 1, 1, 0, 0, 0, 0, "", 0, 0),
(6620, 1, 5, "Make this inn your home.", 2822, 8, 65536, 0, 0, 0, 0, "", 0, 0),
(6620, 2, 1, "I want to browse your goods.", 3370, 3, 128, 0, 0, 0, 0, "", 0, 0);

**Comment by Killyana** [comment]
This one is fixed but there's probably more similar cases.
Also a lot of Innkeepers (cata+) doesn't have any script they must at least have the generic script "npc_innkeeper"
