### ISSUE TITLE
[Master]Core/Spells - Validate(SpellInfo const* /*spellInfo*/) no validating the most of class spells

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/TrinityCore#20883]
**Description:**
 Validate(SpellInfo const* /*spellInfo*/) function not validating the most of class spells.
If you suprime the function, the spell works correctly. Dunno what is going there really...

**Current behaviour:**
Example: Stealth, when  you use the spell, nothing happens there. It shows the buff only.
Same for others spells.

**Expected behaviour:**
In this case,rogue should to get in stealth.

**Steps to reproduce the problem:**
stealth spell = 1784 . You use stealth in game, it doesnt work.
Test: 
 In [spell_rogue.cpp](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Spells/spell_rogue.cpp) ,line 616, you comment the function bool Validate(SpellInfo const* /*spellInfo*/) override
(616 - 627) and save it. You recompile and the spell will work in game.

master = 7.2.5.24742

** https://github.com/TrinityCore/TrinityCore/commit/e0be125543109fd8bcbdeb326877e1e8c7334b6c :** 

**TDB version:**  TDB_full_720.00_2017_04_18

**Operating system:** Windows 7

**Comment by Ovahlord** [comment]
Check the startup logs. the validation is used to prevent spellscripts to use wrong or missing spell datas. They are probably not updated for legion.

**Comment by Daniel25** [comment]
Ok thanks you. I just wanted to point about it, so someone with sufficient knowledge can check it and fix it if it's possible. I would like to fix it in my own but i dont know sufficient...

**Comment by joschiwald** [comment]
Validate is working as intended, it disabled outdated spellscript to prevent unexpected behavoir

most of our spellscripts need to be updated

**Comment by Daniel25** [comment]
Could you close this pull request too please? its related for this too.
[stealth pull request](https://github.com/TrinityCore/TrinityCore/pull/20237)
