### ISSUE TITLE
Misha Tor'kren can be seen twice in Durotar

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20891]
**Description:** Misha Tor'kren can be seen twice in Durotar.

**Expected behaviour:** should only be seen (or spawned?) once by Player.

**Steps to reproduce the problem:**

1. Create a level 8 Orc character.
2. Get to Durotar
3. Get to where the NPC is supposed to be
4. You'll see two of them

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-16 at 5 11 20 pm" src="https://user-images.githubusercontent.com/33535711/32919122-b8d075be-caf2-11e7-9a0c-5112351f1b39.png">

**Comment by Aokromes** [comment]
It needs waypoints.

**Comment by Killyana** [comment]
They could use invisibility aura, one visible before finishing the quest and one after.
