### ISSUE TITLE
[3.3.5] A Spirit Guide Quest 9410

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#20890]
**Description:**

If you use the Wolf Totem of Ancestral Spirit near the dead orc, the wolf is called, but it does not move, nothing happens.

http://www.wowhead.com/quest=9410/a-spirit-guide
http://www.wowhead.com/quest=9410/a-spirit-guide#videos:id=54001

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c9a7aab32e08 2017-11-16 20:40:06 +0100 (335a branch)

**TDB version:** 
TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Win7

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20310
