### ISSUE TITLE
Quests 'Hot On the Trail: The Riverpaw Clan' and 'Hot On the Trail: Murlocs' are available before completing quest 'Murder Was They Case That They Gave Me'

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20907]
**Description:** Quests 'Hot On the Trail: The Riverpaw Clan' and 'Hot On the Trail: Murlocs' are available before completing quest 'Murder Was The Case That They Gave Me'

**Expected behaviour:** both quests should be available if-and-only-if the Player has completed the quest 'Murder Was The Case That They Gave Me'

**Steps to reproduce the problem:**

1. Create a level 10 Alliance character
2. Travel to Westfall
3. Talk to Lieutenant Horatio Laine in Westfall

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by nubqt** [comment]
Source for claim: http://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me#comments:id=1211071

**Comment by Killyana** [comment]
Westfall is not scripted: https://github.com/TrinityCore/TrinityCore/issues/15182
