### ISSUE TITLE
Murloc Raiders and variants don't drop Murloc Clue when Player has quest 'Hot On The Trail: Murlocs'

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20909]
**Description:** Murloc Raiders and variants don't drop Murloc Clue when Player has quest 'Hot On The Trail: Murlocs'

**Expected behaviour:** item should have a chance to drop from those type of Murlocs when Player has quest.

**Steps to reproduce the problem:**

1. Create a level 10 Alliance character
2. Travel to Westfall
3. Get the quest 'Hot On the Trail: Murlocs'
4. Kill murlocs
5. Item doesn't drop after killing dozens

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by Killyana** [comment]
Cata+ loots are not on the DB: https://github.com/TrinityCore/TrinityCore/issues/18538

**Comment by Alastyr** [comment]
According with WoWHead, Murloc Clue (http://www.wowhead.com/item=57756/murloc-clue) could be dropped by Murloc Raider (http://www.wowhead.com/npc=515/murloc-raider) and Murloc Coastrunner (http://www.wowhead.com/npc=126/murloc-coastrunner).
 I checked in database and this item doesn't compare in creature_loot_template.

```
SELECT * FROM `creature_loot_template` WHERE `entry`=126 AND `item`=57756
SELECT * FROM `creature_loot_template` WHERE `entry`=515 AND `item`=57756
```

Results are null. These query should fix it:
```
DELETE FROM `creature_loot_template` WHERE `entry`=126 AND `item`=57756;
INSERT INTO `creature_loot_template`
VALUES
(126, 57756, 0, 19, 1, 1, 0, 1, 1, "");

DELETE FROM `creature_loot_template` WHERE `entry`=515 AND `item`=57756;
INSERT INTO `creature_loot_template`
VALUES
(515, 57756, 0, 22, 1, 1, 0, 1, 1, "");
```
