### ISSUE TITLE
Riverpaw Gnolls and variants don't drop Riverpaw Gnoll Clue when Player has quest 'Hot On The Trail: The Riverpaw Clan'

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20908]
**Description:** Riverpaw Gnolls and variants don't drop Riverpaw Gnoll Clue when Player has quest 'Hot On The Trail: The Riverpaw Clan'

**Expected behaviour:** item should have a chance to drop from those type of Gnolls when Player has quest.

**Steps to reproduce the problem:**

1. Create a level 10 Alliance character
2. Travel to Westfall
3. Get the quest 'Hot On the Trail: The Riverpaw Clan'
4. Kill gnolls
5. Item doesn't drop after killing dozens

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by Killyana** [comment]
Cata+ loots are not on the DB: https://github.com/TrinityCore/TrinityCore/issues/18538
