### ISSUE TITLE
A Spirit Guide quest issue

### ISSUE THREAD

**Issue by BillytheOrc** [TrinityCore/TrinityCore#20912]
**Description:**
This quest should spawn a wolf that goes on a waypoint adventure all the way to the Mag'har NPCs

**Current behaviour:**
The wolf just stands 

**Expected behaviour:**
It should follow  a waypoint to get to the mag'har rep guy.

**Steps to reproduce the problem:**
1. Start quest 9410 
2. Use item
3. Wolf doesn't move

**Branch(es):**

CHANGEME 3.3.5, master or both

**TrinityCore rev. 7fd8603ec5e6+ 2017-11-16 18:35:58 +0100** 

**TDB version:** 63

**Operating system:** Win10

**Comment by Aokromes** [comment]
#20310
