### ISSUE TITLE
Skittering Spiderlings are attackable rather than lootable in quest All That Skitters

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20917]
**Description:** Skittering Spiderlings are attackable rather than lootable in quest All That Skitters

**Expected behaviour:** spiderlings should be lootable and not attackable

**Steps to reproduce the problem:**

1. Create a level 33 Alliance character
2. Travel to The Hinterlands
3. Get the quest All That Skitters
4. Get near a Skittering Spiderling
5. You can attack it

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-17 at 2 38 18 am" src="https://user-images.githubusercontent.com/33535711/32936078-c7362c9a-cb40-11e7-93e8-78d50b21b7c1.png">

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15182
