### ISSUE TITLE
Hero's Call Board in Ironforge does not offer any quests

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20913]
**Description:** Hero's Call Board in Ironforge does not offer any quests

**Expected behaviour:** board should offer breadcrumb quests according to character's level.

**Steps to reproduce the problem:**

1. Create a level 30 Alliance character
2. Travel to Ironforge
3. Go to the Hero's Call Board in front of the AH
4. Notice no exclamation marks on top of it
5. Click the board
6. Nothing happens

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-17 at 1 53 10 am" src="https://user-images.githubusercontent.com/33535711/32934716-c2ac3ada-cb3a-11e7-957f-fd552e5de4ad.png">

**Comment by Alastyr** [comment]
Can you try to check if [Hero's Call Board](http://www.wowhead.com/object=206111/heros-call-board) in Stormwind works?
I checked the database.

`SELECT `type` FROM `gameobject_template` WHERE `entry`=206111;`

Stormwind's Hero's Call Board has type=2, that means GAMEOBJECT_TYPE_QUESTGIVER, but both Ironforge's Hero's Call Board (entry=207320 and entry=208316)  has type=48, that is not define in [TrinityCore's DB guide](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130143/gameobject+template#gameobject_template-type)(maybe missed documentation?)

Try this query.

`UPDATE `gameobject_template` SET `type`=2 WHERE `entry` IN (207320, 208316);`

**Comment by Aokromes** [comment]
update type without sniff is hack, very likely board lacks gameobject_queststarter.

**Comment by DoctorKraft** [comment]
After sniffing a lot of new gob, only Board and Obliterium Forge gob have this type but` type=48` are not defined also in core, no idea about this new type..

**Comment by Aokromes** [comment]
Ok, so it needs core support.

**Comment by DoctorKraft** [comment]
Exactly, need more information about `Data1` and `Data3` with this type

**Comment by Alastyr** [comment]
I found that [Ironforge's Hero's Call Board](http://www.wowhead.com/object=207320/heros-call-board) was added in 6.2. Instead, Stormwind's Hero's Call Board was added in 4.0.1 (id=[206294](http://www.wowhead.com/object=206294/heros-call-board) and id=[206111](http://www.wowhead.com/object=206111/heros-call-board)). Maybe this could help.

**Comment by DoctorKraft** [comment]
After research [Hero's Call Board](http://www.wowhead.com/object=207320/heros-call-board) don't give quest, i have try with differents char level. He open Journal Adventure only, i think WoWHead are wrong and TC dev have parse WoWHead, it's possible?
