### ISSUE TITLE
Using a Tiki Torch near a Tiki Mask doesn't give kill credit for quest Faces of Evil

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20916]
**Description:** Using a Tiki Torch near a Tiki Mask doesn't give kill credit for quest Faces of Evil

**Current behaviour:** the kill credit bunny is there (see second screenshot) but using the torch doesn't give kill credit.

**Expected behaviour:** using the torch near a mask should give kill credit.

**Steps to reproduce the problem:**

1. Create a level 33 Alliance character
2. Travel to The Hinterlands
3. Get the quest Faces of Evil
4. Get near a Tiki Mask
5. Use the Tiki Torch
6. Animation is there but nothing happens

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-17 at 2 23 16 am" src="https://user-images.githubusercontent.com/33535711/32935714-4758655c-cb3f-11e7-8010-04db48874390.png">

<img width="1378" alt="screen shot 2017-11-17 at 2 23 27 am" src="https://user-images.githubusercontent.com/33535711/32935720-4ff607fa-cb3f-11e7-9256-c2c98e2835b7.png">

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15182

**Comment by Aokromes** [comment]
P.s. while screenshots are good few times, most of times are useless for us, we prefer to include IDs of creatures and quests than screnshots.
