### ISSUE TITLE
Two-Shoed Lou is not phased in after getting quest Meet Two-Shoed Lou

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20910]
**Description:** Two-Shoed Lou is not phased in after getting quest Meet Two-Shoed Lou

**Expected behaviour:** NPC should phase in after getting the quest.

**Steps to reproduce the problem:**

1. Create a level 11 Alliance character
2. Travel to Westfall
3. Get the quest Meet Two-Shoed Lou
4. Travel to the Fulbrow's Pumpkin Farm
5. Lou is nowhere to be seen
6. Execute the command .gm on
7. Lou appears

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

**Comment by nubqt** [comment]
This belongs to master list #15182 regarding Cataclysm zones.

**Comment by tkrokli** [comment]
Most likely because the phasing in this zone is not scripted yet.

**Comment by Killyana** [comment]
Westfall is not scripted.
