### ISSUE TITLE
Using a Gryphon Chow on a Trained Razorbeak doesn't give killcredit on quest Razorbeak Friends

### ISSUE THREAD

**Issue by nubqt** [TrinityCore/TrinityCore#20914]
**Description:** Using a Gryphon Chow on a Trained Razorbeak doesn't give killcredit on quest Razorbeak Friends

**Expected behaviour:** using the chow on the razorbeak should give kill credit.

**Steps to reproduce the problem:**

1. Create a level 30 Alliance character
2. Travel to The Hinterlands
3. Get the quest Razorbeak Friends
4. Use a Gryphon Chow on a Trained Razorbeak
5. Animation is there, but no kill credit

**Branch(es):** master

**TC rev. hash/commit:** 7334419

**TDB version:** 720.00_2017_04_18

**Operating system:** MacOS

<img width="1378" alt="screen shot 2017-11-17 at 2 04 23 am" src="https://user-images.githubusercontent.com/33535711/32934948-d81a2520-cb3b-11e7-956b-81b809b4d72f.png">

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15182
