### ISSUE TITLE
[3.3.5][Quest] The Escape (863)

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#20928]
**Description:**
Escort Wizzlecrank's shredder out of the Venture Co. drill site.

**Current behaviour:**
Everything goes fine until the point after Wizzlecrank's Shredder says: "Looks like we're out of the woods, eh? Wonder what this does…", he seems to wonder around then despawns.

**Expected behaviour:**
The escort quest should continue on as outlined here: https://wow.gamepedia.com/Quest:The_Escape_(Horde)

**Steps to reproduce the problem:**
1 .quest add 858
2 .quest complete 858
3 .go xyz 1109.15 -3104.11 82.41 1
4 turn in quest and accept the next one
 
**Branch:** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. be1a1ce7c048 2017-11-16 23:35:58 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Fedora 26

**Comment by Aokromes** [comment]
#20310 ?

**Comment by Killyana** [comment]
Yes.

**Comment by Tauriella** [comment]
Please reopen this tret
This Quest can't complete

TrinityCore rev. e4e6e2209c8a 2018-02-12 03:25:05 +0100 (335a branch)

**Comment by Aokromes** [comment]
Post on #20310
