### ISSUE TITLE
SQL error while populating world database

### ISSUE THREAD

**Issue by DerC88** [TrinityCore/TrinityCore#20926]
Hey there,

I'm using TrinityCore 3.3.5 (and sometimes the Master branch as well) for quite a long time and everything went really smooth. Today I tried to update my private server to a current version and this occurs:

**Description of the problem or issue here:**
1. authserver starts fine
2. worldserver starts and when it's time to import world database updates it stops with ERROR 1728 (HY000) at line 9: cannot load from lysql.proc. The table is probably corrupted.
The sql file is /TrinityCore/sql/updates/world/3.3.5/2017_10_27_01_world.sql
Other sql updates older than this one are importing fine and I think even newer ones too.

I've dropped the whole world table and started from scratch but the error is always occuring - even after recompiling the whole server.

**Expected behaviour:**
Import the sql stuff and start the worldserver.

**Steps to reproduce the problem:**

1. git pull origin 3.3.5
2. compile 
3. start worldserver

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. rev 97f33dc77945 2017-11-11 20:27:30 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**
Debian 9 stable with unmodified sources.list and all updates

Hopefully I've entered all information needed oO

**Comment by Aokromes** [comment]
https://i.imgur.com/SK4OUH6.png
