### ISSUE TITLE
[3.3.5] DB/Gossip: J.D. Collie (NPC 9117)

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#20925]
**Description:**

J.D. Collie should occasionally say the following:

    J. D. Collie says: Ahh... My experiments never seem to work out right. Maybe I should go back downstream.
    <emote>J. D. Collie begins to combine different colored crystals together.
    J. D. Collie says: I think...I think it's working!
    J. D. Collie says: OW! That's not right!
    J. D. Collie says: Oh well... Maybe next time.

source: https://wow.gamepedia.com/J.D._Collie

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. be1a1ce7c048 2017-11-16 23:35:58 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)RelWithDebInfo, Static) (bnetserver)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Comment by tkrokli** [comment]
Please enter the SQL in an issue ticket instead of a PR. It will be regarded as a contribution,

**Comment by tkrokli** [comment]
Also please add the code `sql` directly after the first three ``` (ticks) to highlight the SQL syntax when entering the code.

**Comment by tkrokli** [comment]
Sorry, my bad. I misread the issue.

**Comment by rockz1152** [comment]
lol I was gonna say....."but this is an issue" it's all good.
