### ISSUE TITLE
spell_area QUEST_STATUS_REWARDED update

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20934]
**Description:**
When player rewards a quest, related spell_area auras are immediately updated. In some cases, it is unwanted behavior to update auras right after quest is rewarded. Instead, they should be updated after re-entering area. (it was working like this some time ago)
Similar discussion was [here](https://github.com/TrinityCore/TrinityCore/pull/18146), related to phase_area update after QUEST_STATUS_REWARDED
[Video](https://youtu.be/LLatvrnML2g?t=1m24s) - after rewarding quest, the audience NPCs are there clapping and cheering. On TC they disappear because auras are updated.

**Current behaviour:**
Player rewards a quest and auras are immediately updated.

**Expected behaviour:**
In quests like [Stronger Than Reeds](http://www.wowhead.com/quest=29662), [Stronger Than Wood](http://www.wowhead.com/quest=29771) and [Stronger Than Bone](http://www.wowhead.com/quest=29782) it is necessary to keep the zone auras active until player leaves the area.
New item in disables table could solve this issue.

**Steps to reproduce the problem:**
1. go to the quest giver and reward quest
2. see that all NPCs that should stay there until player leaves area now disappear immediately

**Branch(es):** master

**TC rev. hash/commit:** b12b37058c863bcfecfefc965da45f31b604ee3b

**TDB version:**  TDB 720.00

**Operating system:** Win 7 x64

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/20156 ?

**Comment by Lopfest** [comment]
this is not related to phases, only zone auras

**Comment by Killyana** [comment]
Just don't use quest_end on spell_area

**Comment by Lopfest** [comment]
quest_start is 0, so i can't leave quest_end also 0. They will never disappear then

**Comment by Killyana** [comment]
If quest_start=0 from where it comes the aura?

**Comment by Lopfest** [comment]
some specified quest_start and quest_end 0 can also be used to cast aura only if quest has specific status(es), in other words, it will not be cast when condition not met.
the aura has autocast flag.

**Comment by Killyana** [comment]
Give an example, I don't understand.

**Comment by Lopfest** [comment]
example of spell_area that doesn't need quest_end for the spell not to be casted after some quest status:
`(108695, 5849, 29664, 0, 0, 0, 2, 1, 8, 0), -- See Quest Invis 20 (Sparkle Bunny flames)`
but this is offtopic.

the spell this report is about is for example this:
`(108834, 5826, 0, 29662, 0, 0, 2, 1, 0, 11), -- See Quest Invis 8 (Children & Onlookers) // should be delayed`

**Comment by Killyana** [comment]
When this spell=108834 is casted ?

**Comment by Lopfest** [comment]
anytime you enter the area... until quest is rewarded

**Comment by funjoker** [comment]
`void Player::SendQuestUpdate(uint32 questId)`

Instantly causes update of phases and spell_area.
Imo this should not be.

Phases often do not update instantly or just when you changed area and come back or relogg.
Same with auras. It often happens that it they do not update instantly only on relogg or phase change.
Atm you have no chance to set it.

I would say we should add a field to spell_area to control instant update or not.

**Comment by Shauren** [comment]
@funjoker I thought about it too, field called `autoremove` (default 1) similar to `autocast`
