### ISSUE TITLE
[3.3.5] Creatures always run when chasing

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#20938]
**Description:**

Creatures always use move type MOVE_RUN when MoveChase() is issued. 

**Current behaviour:**

Creatures always use MOVE_RUN when MoveChase() is issued. regardless of whether they are set to walk or not, which is the default for any attacking creature. 

**Expected behaviour:**

Not all creatures should run when chasing their targets. Thaladred the Darkener (http://www.wowhead.com/npc=20064/thaladred-the-darkener) for example, should walk while chasing players, but currently there is no way to achieve that, because https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L220 always disables walk mode.

**Steps to reproduce the problem:**

1. Make Thaladred the Darkener walk instead running - SetWalk(true)
2. Start Kael'thas encounter
3. Watch as Thaladred still runs after his targets at full speed

**Branch(es):**

3.3.5/likely both

https://github.com/TrinityCore/TrinityCore/commit/a422dad8702c779b5665891d9e651aef575f33f7

**Comment by Ovahlord** [comment]
Well, in the most cases it is still running. The only thing that is different is, that they use a MovementId that is making their running animation look like walking and for that they also have a changed run speed.

**Comment by Krudor** [comment]
Pretty sure (https://www.wowhead.com/npc=53231/lava-scion)[Lava Scion] from firelands have the same issue.
There is a movement id present but it's still not moving correct.

**Comment by Nyeriah** [comment]
I forgot about this: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L190

EnableWalking() only returns false as well, so never walking

**Comment by Kittnz** [comment]
@Nyeriah How can i contact you?

**Comment by Langerz82** [comment]
I've tested briefly and this works. Set chase_type=1 in the DB which creatures you want to Chase Walk.

See:
https://gist.github.com/Langerz82/0c1cbc5ba3c5f444f8f5e9d6d942de65

**Comment by Aokromes** [comment]
cannot be better custom flag?

**Comment by tkrokli** [comment]
in that case, would `flags_extra` be a practical place to add the custom flag?
Looks like there are some gaps available there.

**Comment by Nyeriah** [comment]
This is an overkill. There are so few creatures that should follow this behavior. I would rather see them properly respecting the SetWalk() on/off during runtime which looks like a bug to me.

**Comment by Krudor** [comment]
@Nyeriah I don't think that'll cut it, I'm pretty sure the creatures are still using their run speed when chasing, and just want to use walking animation. (Could be wrong)

**Comment by Killyana** [comment]
Implemented by https://github.com/TrinityCore/TrinityCore/pull/23073
