### ISSUE TITLE
Command to reload gameobject template

### ISSUE THREAD

**Issue by velinath** [TrinityCore/TrinityCore#20939]
**Description:**

Currently, there is no gameobject analog to `.reload creature_template $id`. Something like `.reload gameobject_template $id` would be helpful for more easily troubleshooting changes to the gameobject template. The current behavior is that the server parses `.reload gameobject_template (anything)` as `.reload gameobject_template_locale`.

**Branch(es):**

both branches

**TC rev. hash/commit:** 

1f77bd9

**Comment by Shauren** [comment]
Impossible. almost everything in gameobject_template is cached by client (not faction and flags) but you will still need to spawn new object to see change

**Comment by velinath** [comment]
Oh cool, learned something new today. This explains my issues with testing gameobject SAI in a recent PR.

Thanks for the information, appreciate it!
