### ISSUE TITLE
[3.3.5][Quest] Questioning Reethe (1273)

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#20930]
**Description:**
The play and Ogron(npc 4983) walk over to Paval Reethe(npc 4980) to question him about the Shady Rest Inn Fire. After the event plays out, Ogron runs back to his starting spot.

**Current behaviour:**
A section of dialogue between Lieutenant Caldwell(npc 5046) and Private Hallan(npc 5045) is missing, Ogron is missing his last two lines and then fails to return to his starting position.

**Expected behaviour:**
After Paval Reethe says: "What was that? Did you hear something?", the following dialogue should take place:
> Lieutenant Caldwell says: Paval Reethe! Found you at last. And consorting with ogres now? No fear, even deserters and traitors are afforded some mercy.
> 	Lieutenant Caldwell says: Private, show Lieutenant Reethe some mercy.
> 	Private Hallan says: Gladly, sir.
> 	(She switches to a bow, shoots him once, and switches back to her sword.)
> 	Paval Reethe staggers backwards as the arrow lodges itself deeply in his chest.
> 	(Paval Reethe kneels)
> 	Paval Reethe says: Ugh... Hallan, didn't think you had it in you...
> 	Lieutenant Caldwell says: Now, let's clean up the rest of the trash, men!

Ogron is supposed to say the following lines after Reethe dies:
> Ogron says: Looks dead to me, Not much use to us like this. You'd better go back and tell Krog what happened.
> 	Ogron says: By the way, thanks for watching my back.

Ogron then runs back to his starting position.

**Additional Information:**
The full event can be seen here: https://www.youtube.com/watch?v=bHaRrXx-xAQ
Full dialogue here, see comment by Meyo: http://www.wowhead.com/quest=27261/questioning-reethe
Original wowhead page: http://www.wowhead.com/quest=1273/deprecated-questioning-reethe
	
**Steps to reproduce the problem:**
1 .quest add 1269
2 .quest reward 1269
3 .go xyz -3311.09 -3124.22 35.14 1
4 start quest and follow Ogron to start the event.
    
**Branch:** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. be1a1ce7c048 2017-11-16 23:35:58 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** TDB_full_world_335.63_2017_04_18

**Operating system:** Fedora 26

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20310
