### ISSUE TITLE
DB/SAI: Arikara

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20946]
**Description:**

Arikara is not scripted.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Arikara
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=10882;
DELETE FROM `smart_scripts` WHERE `entryorguid`=10882 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(10882,0,0,0,0,0,100,0,8000,16000,12000,24000,11,17213,32,0,0,0,0,5,0,0,0,0,0,0,0,"Arikara - In Combat - Cast Curse of Vengeance"),
(10882,0,1,0,2,0,100,1,0,30,0,0,11,8599,0,0,0,0,0,1,0,0,0,0,0,0,0,"Arikara - Between 0-30% Health - Cast Enrage (No Repeat)"),
(10882,0,2,0,2,0,100,1,0,30,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Arikara - Between 0-30% Health - Say Line 0 (No Repeat)");

DELETE FROM `creature_text` WHERE `CreatureID`=10882;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(10882,0,0,"%s becomes enraged!",16,0,100,0,0,0,10677,0,"Arikara");

**Comment by tkrokli** [comment]
- http://www.wowhead.com/npc=10882/deprecated-for-4-x-arikara
- http://wowwiki.wikia.com/wiki/Arikara
- https://wow.gamepedia.com/Arikara

**Comment by offl** [comment]
There is an interesting moment with the emote, @ZenoX92
Before Wotlk - [becomes enraged](https://youtu.be/dn3sVUahDAQ?t=43)
In Wotlk - [goes into a frenzy](https://www.youtube.com/watch?v=Jya5NRel5go)
After Wotlk - becomes enraged
http://www.wowhead.com/npc=18062/enraged-crusher#comments:id=125850

Dunno if this was changed globally :)

**Comment by ZenoX92** [comment]
Yeah, it's interesting. I would like to know if the emote text was all that was changed. Maybe the "Enrage" spell was changed too. I think we should keep it this way until we find more info.

**Comment by ZenoX92** [comment]
Open a ticket for that @offl. Here it is the fix:
```sql
UPDATE `creature_text` SET `Text`="%s goes into a frenzy!", `BroadcastTextId`=1191 WHERE `CreatureID`=10882 AND `GroupID`=0;

**Comment by offl** [comment]
@Killyana can you please push this?
