### ISSUE TITLE
DB/Waypoints: Achellios the Banished 

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20944]
**Description:**

Achellios the Banished  should be running, not walking.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Achellios the Banished - waypoint Move Type
UPDATE `waypoint_data` SET `move_type`=1 WHERE `id`=213880;

**Comment by tkrokli** [comment]
- http://www.wowhead.com/npc=5933/achellios-the-banished#comments
- https://wow.gamepedia.com/Achellios_the_Banished

**Comment by Killyana** [comment]
He's walking here :https://www.youtube.com/watch?v=FLluGl9cYQU&feature=youtu.be&t=81

**Comment by offl** [comment]
Changed in Cata https://youtu.be/BObxNsbRWsc?t=994

**Comment by ZenoX92** [comment]
He can be seen running here: https://youtu.be/BObxNsbRWsc?t=1000
