### ISSUE TITLE
DB/Quest: Homeward Bound

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20941]
**Description:**

Quest "Homeward Bound" completes automatically when accepted. This is an escort quest, it should complete when NPC reaches the end of his path.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Quest "Homeward Bound"
DELETE FROM `quest_template_addon` WHERE `ID`=4770;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(4770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2);

**Comment by tkrokli** [comment]
- https://wow.gamepedia.com/Quest:Homeward_Bound
- http://www.wowhead.com/quest=4770/homeward-bound
