### ISSUE TITLE
DB/Quest: Sacred Fire

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#20943]
**Description:**

When quest "Sacred Fire" is finished, Magatha Grimtotem should cast a spell.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Magatha Grimtotem
DELETE FROM `smart_scripts` WHERE `entryorguid`=4046 AND `source_type`=0 AND `id`=2;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4046,0,2,0,20,0,100,0,5062,0,0,0,11,60888,0,0,0,0,0,1,0,0,0,0,0,0,0,"Magatha Grimtotem - On Quest 'Sacred Fire' Finished - Cast 'Cosmetic Enchant Cast'");

**Comment by tkrokli** [comment]
- https://wow.gamepedia.com/Magatha_Grimtotem#Before_the_Cataclysm
- http://www.wowhead.com/npc=4046/magatha-grimtotem
- http://www.wowhead.com/quest=5062/sacred-fire
- https://wow.gamepedia.com/Quest:Sacred_Fire
