### ISSUE TITLE
Bountiful Feast Object (ID 195303)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#20957]
**Description:**
http://www.wowhead.com/spell=66476/bountiful-feast
http://www.wowhead.com/item=46887/bountiful-feast

In the 3 major cities where Pilgrim's Bounty takes place, there are decorative objects called Bountiful Feast that share the same object (ID 195303) as the Bountiful Feast you place on the ground for your group to eat from.

**Current behaviour:**
The decorative objects near the world event areas highlight when hovered over and show a "use" mouse cursor.

![wowscrnshot_112217_135756](https://user-images.githubusercontent.com/16745918/33149645-b78a504a-cf8d-11e7-8380-65ca4baa2d57.jpg)

**Expected behaviour:**
The **decorative** objects should not highlight or appear usable when hovered over.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** de80cd2e0de4

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
This cannot be fixed for the moment as flags can be set only on gameobject_template_addon and not on gameobject_addon (same for the faction)
``` sql
SELECT * FROM `gameobject` WHERE guid IN (76499, 76498, 76436, 76435, 76229, 76228, 76182, 76181, 76147, 76146, 76145, 76144, 76099, 76098, 76097, 76067, 76066, 76065, 76579, 76580);
