### ISSUE TITLE
[DEV] DB/GameObject: Flags and Faction on gameobject_addon

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#20958]
**Description:** Flags and Faction could be set only on gameobject_template_addon.
In same cases we need to set this data by guid as for https://github.com/TrinityCore/TrinityCore/issues/20957

So Flags and Faction must be added on gameobject_addon.

**Branch(es):** Both

**TC rev. hash/commit:** rev. 9614f9d8cf2

**Comment by Langerz82** [comment]
Hello, here is my SQL/patch please test. 

See:
https://gist.github.com/Langerz82/0a92ce8d2e3a45b0c6a686730107f782

**Comment by tkrokli** [comment]
SQL detail in your gist:
```sql
ALTER TABLE `world`.`gameobject_addon` 
ADD COLUMN `faction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' AFTER `invisibilityValue`,
ADD COLUMN `flags` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `faction`;
```
TC codestyle:: remove the `world.` part (we don't use DB name before table names).
