### ISSUE TITLE
Core/Spells: eventInfo for proc hooks should also be able to manipulate damage

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#20969]
**Description:**

The core needs support to manipulate damage from within a aurascript for example by using eventInfo.GetDamageInfo()->ModifyDamage
Some auras / talents have a proc that should increase the damage of the proc spell and to avoid ugly Unit.cpp changes it could be solved via aurascript by allowing eventInfo.GetDamageInfo()->ModifyDamage to manipulate damage from aurascript proc hooks.

**Current behaviour:**

eventInfo.GetDamageInfo()->ModifyDamage does not have any effect when used in proc-hooks such as OnEffectProc += AuraEffectProcFn.

**Expected behaviour:**

eventInfo.GetDamageInfo()->ModifyDamage should also be able to manipulate proc spell damage when used for proc hooks.

**Steps to reproduce the problem:**

1. Step 1
 As example the former 434 mastery Frostburn (id 76613) for example is dealing increased damage to frozen targets. The aura does have a proc so we can access the percentage bonus as well as the proc damage spell from there.
2. Step 2
The ideal solution would be to manipulate the damage by using following code:
```
        void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
        {
            PreventDefaultAction();
            if (aurEff->IsAffectingSpell(eventInfo.GetProcSpell()->GetSpellInfo()))
                eventInfo.GetDamageInfo()->ModifyDamage(CalculatePct(eventInfo.GetDamageInfo()->GetDamage(), aurEff->GetAmount()));
        }
```

3. Step 3
However, since eventInfo.GetDamageInfo()->ModifyDamage does not work within proc hooks this solution cannot be applied for this case as well as any other proc with similar / same behaivior.

**Branch(es):**

master

**TC rev. hash/commit:** a738c72c67aa84c73d99d78be61569f9eac62b99

**Operating system:** Win10 Pro x64

**Comment by Seyden** [comment]
Do you have a spell example? because personally i don't think, that its needed

**Comment by Ovahlord** [comment]
Named an example already in step 1 how to reproduce.

**Comment by Seyden** [comment]
You also said that it's a 434 example.. and as far as I can see, the aura doesn't need a damage modifier in the master. That's why I asked for a example... to be precise, a 7.x example would be good.

**Comment by ariel-** [comment]
The problem here being procs are independent of the damage calculation and dealing phase, it's just some info that gets called on its own accord. (ie it would make no effect to modify the damage in the DamageInfo struct)

To implement something like this you'd need to either:
- put it into Unit.cpp (Unit::SpellDamage(Pct|Bonus)Done methods) (generic way if it's some aura/effect affecting potentially lots of spells)
- make a SpellScript (preferred as long as the spell only affects a limited number of other spells)

I'd say it's not a implementation issue.
