### ISSUE TITLE
[ASSERT] Crash when spawning a creature using TotemAI

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#20975]
**Description:** When you spawn a totem using `AIName`="TotemAI" with .npc add or .npc add temp the server will crash.

**Steps to reproduce the problem:**

1. UPDATE `creature_template` SET `AIName`="TotemAI" WHERE `entry`=22091;
2. Start the server and .npc add temp 22091
3. The server will crash

Crash log: https://pastebin.com/kZYfk6SG

**Branch(es):** both

**TC rev. hash/commit:** rev. 95d298780010

**Comment by Killyana** [comment]
Yes, but some GM can miss with that

**Comment by jackpoz** [comment]
it's an assertion triggered

**Comment by Killyana** [comment]
We don't have any npc using AIName="TotemAI" for the moment.

**Comment by joschiwald** [comment]
don't set TotemAI in db, the ai is selected by default for all totems

**Comment by Killyana** [comment]
You're right, in this case, I don't know if this crash need to be fixed or not.

**Comment by sirikfoll** [comment]
That's the same problem as https://github.com/TrinityCore/TrinityCore/issues/20200 , only changing "TotemAI" to "PetAI"

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/072c884ed86a9bf895cd5f53b0f6480ae14c3059

as for 20200, are there are PetAI in creature_template that are supposed to be there ?

**Comment by Killyana** [comment]
There's only one : 21909

**Comment by jackpoz** [comment]
is that one correct to be there tho ?
