### ISSUE TITLE
[3.3.5] Pilgrim's Bounty: Sweet Potatoe

### ISSUE THREAD

**Issue by noblist** [TrinityCore/TrinityCore#20973]
Ath the feasting tables for the Pilgrims bounty, the Seet Potatoe Chair, or any for that matter, are not allowing for use of the Feast On Sweet Potato. Can not receive buffs, quest credit nor achievement credits for what this is needed for. Tried at every Alliance table at Exodar, Stormwind, Ironforge, Darnassus.

**Current behaviour:**

Since the accurate spell is avaiable, it should work when sitting in the chairs.
- http://www.wowhead.com/spell=61786/feast-on-sweet-potatoes, .  
- http://www.wowhead.com/npc=34824/the-sweet-potato-chair
- http://www.wowhead.com/pilgrims-bounty#achievements

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  TrinityCore rev. 761b050263d2 2017-11-06 10:36:21 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:**

**Comment by tkrokli** [comment]
Please update your core to include the latest patches, fixes and Pilgrim's Bounty-related material.

**Comment by noblist** [comment]
Where would I find that? I am new to the GitHub community and am learning as I go.

**Comment by tkrokli** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977329/Windows+Core+Installation
- pull the updated source from https://github.com/TrinityCore/TrinityCore  `branch 3.3.5`
- compile the updated source and run the updated server

**Comment by noblist** [comment]
TY, tkrokli

**Comment by noblist** [comment]
One last thing since we are already on this... Will there be SQL updates that can be implemented through the SQL editor to not have to recompile every update? I found the files and tried using some of them and none of them were working properly so I am guessing the compile I had was not compatible, but it also was not from open community as this one is

**Comment by tkrokli** [comment]
Sorry for the delay, I played a horde character (orc hunter, level 1-16) on commit https://github.com/TrinityCore/TrinityCore/commit/95ea4b50904a26710eead36e48a6ab29780d464b and I could not get any of the tables in the Undercity entrance area or the Durotar (outside Orgrimmar) area either. So for me, that is a confirmation of this issue as well. I do not know if we have got a solution to this issue yet.

**Comment by noblist** [comment]
Yeah, the tables have the correct spell set, but i think its a range issue... i was thinking about using sql editor and adjusting range and seeing if that works just to see, but not sure if that is the problem... Just a thought to try, but have a limited amount of time during the weekdays to work on it with two jobs now.. I just dont know how to implement changes with an SQL, but if I can use an editor fix and it works, I can post what I set to and someone who can make it an SQL to update may be able to help everyone. I use to use that for simple fixes a lot when i use to play with repacks years ago...

**Comment by tkrokli** [comment]
We probably need feedback from @sirikfoll , @Killyana or even @Keader if there is something we can do about this issue, or if this happens because some kind of external issue like the infamous "waypoint systems issues".

**Comment by noblist** [comment]
Heard about those, experienced one of them in Scarlet Enclave but have an in-game fix that is just annoying for that one

**Comment by sirikfoll** [comment]
Can't reproduce this bug. Works fine for me

**Comment by tkrokli** [comment]
Oh well. Pilgrim's Bounty is over for now, so I guess I won't be looking at it for another year.

**Comment by BahDumbBugs** [comment]
Unless you turn the Winter Veil event off and Pilgrim's Bounty back on. ;)

**Comment by tkrokli** [comment]
CBA. IRL >> VG.

**Comment by Killyana** [comment]
Works fine in rev. e253b695cc0d
