### ISSUE TITLE
IsStackableWithRanks improvements

### ISSUE THREAD

**Issue by Yehonal** [TrinityCore/TrinityCore#20971]
Don't know if it's the best place/way to discuss about code improvements. Please correct me otherwise. 

However...

About this code:

https://github.com/TrinityCore/TrinityCore/blob/331c70e695c6eef085be03a4f149158b68470035/src/server/game/Spells/SpellInfo.cpp#L1391

What about using SPELL_ATTR4_UNK21 instead?

https://github.com/TrinityCore/TrinityCore/blob/ea99801cd6ff687462df4fdbb69c06071dedfcf0/src/server/game/Miscellaneous/SharedDefines.h#L553

**Comment by Yehonal** [comment]
just noted that it doesn't fit all stances, just some (druid flight form is not included in SPELL_ATTR4_UNK21) 

invalid, closed

**Comment by Shauren** [comment]
There were also many unrelated spells found under that attribute too
