### ISSUE TITLE
[3.3.5] Core/Spell: Incorrect tooltip value for spells scaling with level of player

### ISSUE THREAD

**Issue by toto6** [TrinityCore/TrinityCore#20979]
**Description:**
The tooltip of player spells scaling with the level show the value of the spell as if the player is level 0. When using these spells, the correct value calculated with the level of the player is however used. So this bug is only that the formula is incorrect in the tooltip when hovering the spell icon in your Actionbar/Spellbook.

**Current behaviour:**
Spells scaling with player level do not correctly show there value in the tooltip. For example Mind Control 605 with formula 32 + Level * 1.00 will always display 32 in the tooltip instead of 32+level of player. Other example Blood Fury (Racial) orc 20572 formula 6 + Level * 4.00 will always display 6 in the tooltip.

**Expected behaviour:**
The value in the tooltip should be calculated using the level of the player. For example for Blood Fury, the tooltip should display 326 at level 80.

**Steps to reproduce the problem:**
 - First you must have enabled "Enhanced Tooltips" in Interface/Help
 - You can see the bug with an Orc warrior. Even if his level is greater than 1, when you mouse hover the Blood Fury spell, the value displayed is 6 regardless of the level.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. bd560fd1609c 2017-11-25 10:08:58 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/9572

**Comment by aje** [comment]
proof that this is not a client bug:
https://www.youtube.com/watch?v=tVmDZxYVrr8 at 10 seconds, we see the tooltip for Mind Control displaying "82" instead of the default 32

**Comment by Shauren** [comment]
Blood fury tooltip value calculates level from `Skill (Id 125) "Orc Racial"` divided by 5

**Comment by Warpten** [comment]
At least on 4.3.4, SKILL_CATEGORY_CLASS needs to be SKILL_RANGE_LEVEL. The client actually uses skill trees for a lot of the levels (based on a condition I don't understand. It always divides by a constant though, so that `skillLevel / X = casterLevel` is always true.

**Comment by aje** [comment]
I tried to increase manually skill and the tooltip changed its value. So a fix could be to increase by 5 all the class/race skills of a player when he levels up ?
