### ISSUE TITLE
[master] Core/Misc: Death Knight creation level requirement

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#20987]
**Description:**
The death knight level requirement isn't working.

**Current behaviour:**
The level requirement still can be found in the worldserver.conf (CharacterCreating.MinLevelForDeathKnight) but it doesn't do anything.

"The requirement of already having a level 55+ character in order to create a death knight was lifted in patch 6.1."
https://wow.gamepedia.com/Death_knight

**Expected behaviour:**
a) You can't create a new death knight.
b) The "CharacterCreating.MinLevelForDeathKnight" field is removed from the worldserver.conf and you can create a new death knight.

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/107ed5dc99ab6afebcff49a0b160fb1813c4333a

**TDB version:**  720 + Updates

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
The `CharacterCreating.MinLevelForDeathKnight = 55` setting in `worldserver.conf` is, like you say, still in there because it has not been a high priority to remove it as long as it doesn't stop other code from working or bug the game client.

I must admit that I am a bit confused or that it feels like you are talking about 2 things at the same time. Could you please clarify what you would like to see changed in the source? Maybe you could make a Pull Request for the change you want to see in the source?

**Comment by ArcaneFox** [comment]
Yes I know, we should choose between a) and b). I think the Blizzlike solution is the b) + server-side check for expansion (if it has not implemented already).

**Comment by tkrokli** [comment]
- https://wow.gamepedia.com/Death_knight#Unlocking_your_death_knight
As of [patch 5.3.0](https://wow.gamepedia.com/Patch_5.3.0), players are no longer restricted to creating a single death knight per realm. With the exception of Pandaren (who did not appear in the Wrath of the Lich King expansion), there are no racial limitations for creating your death knight. As of [patch 6.1](https://wow.gamepedia.com/Patch_6.1), the requirement to have an existing character at level 55 or higher before creating a death knight was also lifted.

**Comment by Aokromes** [comment]
workarround CharacterCreating.MinLevelForDeathKnight=1

**Comment by tkrokli** [comment]
The main point here, if I have understood ArcaneFox correctly, is that the config setting does not do anything. You can put any value there and it does not make a difference. (I don't have a working 7.2.5 game client, so I can't test it myself.)
