### ISSUE TITLE
DB/Creature: Naias

### ISSUE THREAD

**Issue by STARRHELD** [TrinityCore/TrinityCore#20984]
**Description:**

Creature is spawned far way from the altar and is missing its creature_text

**Current behaviour:**

Creature is spawned far way from the altar and is missing its creature_text

**Expected behaviour:**

Spawn facing away from the altar and say the speech:

- "Who challenges Naias? Puny $r, you are little better than those mindless trolls I have played against each other like so many pieces on a game board!"

```SQL
SELECT * FROM `broadcast_text` WHERE `ID` = 13560;
````

```CODE
| ID    | Language | MaleText                                                                                                                                              | FemaleText | EmoteID0 | EmoteID1 | EmoteID2 | EmoteDelay0 | EmoteDelay1 | EmoteDelay2 | SoundId | Unk1 | Unk2 | VerifiedBuild |
|-------|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------|------------|----------|----------|----------|-------------|-------------|-------------|---------|------|------|---------------|
| 13560 | 0        | Who challenges Naias? Puny $r, you are little better than those mindless trolls I have played against each other like so many pieces on a game board! |            | 0        | 0        | 0        | 0           | 0           | 0           | 0       | 0    | 1    | 18019         |
```
https://www.youtube.com/watch?v=KGeiXafHPZY

**Steps to reproduce the problem:**

1. .quest add 9457
2. Use [Gift of Naias]
3. Naias is spawned far away behind you.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 463ed5e1ac68

**TDB version:**  TDB_full_world_335.63_2017_04_18.sql

**Operating system:** Linux

**Comment by STARRHELD** [comment]
http://www.wowhead.com/quest=9457/
http://www.wowhead.com/item=23680/gift-of-naias
http://www.wowhead.com/npc=17207/naias

```SQL
SELECT * FROM `creature_text` WHERE `CreatureID` = 17207;
```

**Comment by STARRHELD** [comment]
Something to start with.

```SQL
DELETE FROM `creature_text` WHERE `CreatureID`=17207;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(17207, 0, 0, 'Who challenges Naias? Puny $r, you are little better than those mindless trolls I have played against each other like so many pieces on a game board!', 12, 0, 100, 0, 0, 0, 13560, 0, 'Naias');
```

**Comment by tkrokli** [comment]
I suppose we will need some kind of SmartAI script to get Naias to actually say that line at the right moment.

**Comment by STARRHELD** [comment]
How is the npc currently spawned @tkrokli? Is it via database?

**Comment by tkrokli** [comment]
No, it is via the quest item and its spell:
- http://www.wowhead.com/item=23680/gift-of-naias
- http://www.wowhead.com/spell=30015/summon-naias

**Comment by offl** [comment]
```sql
SELECT * FROM `event_scripts` WHERE `id`=10554;

**Comment by tkrokli** [comment]
```
   id   delay  command  datalong  datalong2  dataint         x       y       z       o
-----  ------  -------  --------  ---------  -------  --------  ------  ------  ------
10554       0       10     17207    3000000        0  -12150.4  918.29     1.2    0.44
```

**Comment by STARRHELD** [comment]
Where about is the spawning position sitting? Is it possible to add the creature_text on summoned?

**Comment by STARRHELD** [comment]
On phone but I see your comment, then we can edit the position of spawn easily at least

**Comment by tkrokli** [comment]
You can add the Talk command action (say  `creature_text`) on summoned via SAI `event_type` `SMART_EVENT_JUST_SUMMONED` (54)
(https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130108/smart+scripts#smart_scripts-event_type)

**Comment by STARRHELD** [comment]
My end result would be:

```SQL
DELETE FROM `event_scripts` WHERE `id`=10554;
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
(10554,0,10,17207,3000000,0,-12129.775391, 957.067749, 4.754206, 4.938643);

DELETE FROM `creature_text` WHERE `CreatureID`=17207;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(17207, 0, 0, 'Who challenges Naias? Puny $r, you are little better than those mindless trolls I have played against each other like so many pieces on a game board!', 12, 0, 100, 0, 0, 0, 13560, 0, 'Naias');

-- Naias SAI
 SET @ENTRY := 17207;
 UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
 DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
 INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,54,0,100,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,'Naias');
```
![](https://media.giphy.com/media/l2RnuEpDcSZC95rUs/giphy.gif)

Questions/Comments?

**Comment by Aokromes** [comment]
event_scripts is deprecated, can't you do it with all SAI?

**Comment by offl** [comment]
SMART_SCRIPT_TYPE_EVENT is NYI

**Comment by tkrokli** [comment]
BTW, I recommend using `UPDATE` for the changes in `event_scripts` since you change 4 columns and 6 remain unchanged.
```sql
UPDATE `event_scripts` SET `x`=-12130.098633, `y`=954.384155, `z`=4.516311, `o`=4.930158 WHERE `id`=10554;
```
Also, in general, I agree on Naias spawning close to or on his altar, but do we have any hard evidence for it?

**Comment by STARRHELD** [comment]
@tkrokli Good point, well I mean do we really have any evidence that proves that he should spawn where the location is set at now?
