### ISSUE TITLE
Quest mobs not skinnable after dropping quest items when grouped

### ISSUE THREAD

**Issue by BittyBit** [TrinityCore/TrinityCore#20985]
**Description:**  Quest mobs not skinnable after dropping quest items when grouped

**Current behaviour:**

Normally skinnable mobs that drop quest items are not skinnable after being looted.

**Expected behaviour:**

Skinnable mobs that drop quest items for players that are grouped should be skinnable by anyone after being looted.

**Steps to reproduce the problem:**

1. Form a party
2. Kill a skinnable mob that drops a quest item for the first party member to loot the mob
3. Regardless of 'whose mob it is to loot' designation, the mob will be unskinnable even if all party members loot it. The mob behaves like it is still holding the quest item for the other party members, but there is no quest item available.

This affects any quest of the type where a skinnable quest mob drops a quest item for only one member of a group. I have included the following quest/item/mob for reference.

- http://wowwiki.wikia.com/wiki/Quest:Pridewings_of_Stonetalon
- http://wowwiki.wikia.com/wiki/Pridewing_Venom_Sac
- http://wowwiki.wikia.com/wiki/Pridewing_Wyvern

**Branch(es):**  3.3.5 (not tested on master)

**TC rev. hash/commit:** 

TrinityCore rev. 97f33dc77945 2017-11-11 20:27:30 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)

**Operating system:**  Ubuntu 16.04LTS

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/13940

**Comment by BittyBit** [comment]
That issue refers to a random, and occasional unskinnable mob while ungrouped. This issue is consistent and  repeatable.

**Comment by Killyana** [comment]
It depends if the drop rate of the quest item is 100% or not

**Comment by tkrokli** [comment]
So... move the issue description from this page to ticket #13940 then?

**Comment by BittyBit** [comment]
Just for clarification, when I said :

> Kill a skinnable mob that drops a quest item for the first party member to loot the mob

I was trying to say that the issue only impacts mobs that drop the quest item. To build on the example I gave, if a Pridewing Wyvern doesn't drop a Pridewing Venom Sac (even if all or single group members have the quest) there is no issue skinning.

I did some testing and found that:

A mob that drops the quest item cannot be skinned by players inside or outside of the party if it has dropped the quest item for a player that is grouped
A mob that drops the quest item can be skinned by an ungrouped player once looted (expected) even if it has dropped the quest item for the ungrouped player. Once looted, the mob can also be skinned by a third party (again expected).
A mob that doesn't drop the quest item even if one or more party members have the quest, can be skinned by players either inside or outside of the party once the 'loot owning' player has looted it or unlocked it for another player to loot (expected).

I think that not dropping the quest items for all party members is blizzlike (circa wotlk) as is allowing the non-loot owner group member to ninja-loot the quest item. It is how the mob is flagged as skinnable after the loot operation that seems to be the issue.

**Comment by Killyana** [comment]
So the mob must not be flagged skinnable until everything is looted?
If you think so, we need a proof that it'is the retail behavior.

**Comment by offl** [comment]
Seems to be true
https://youtu.be/xoF5dOBJd34?t=68
https://youtu.be/iMjHAqLHDbc?t=42

**Comment by Killyana** [comment]
http://wowwiki.wikia.com/wiki/Skinning
- All the items from a corpse must be looted before it can be skinned.
- Any skinnable mobs will say "Skinnable" in their tooltip after they are dead and completely looted.
- If you're trying to skin something that is lootable by another player, that player must take all loot from the corpse, or you won't be able to skin it.
- In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item. This usually happens when killing several mobs at once before looting and skinning them. There is no way to skin such a corpse other than to drop at least one of the quest items so you can then loot the item one more time. Due to game mechanics, random drops from mobs are almost always determined at the time of looting, rather at some previous time. And almost all looted items required for quests can be acquired beyond the quota for the quest. Rarely, this can happen with bosses who are supposed to drop a single quest item that respawn before their previous corpse has been looted, such as Combat 15 Princess. 
- If you possess a Unique item somewhere in your inventory (bags/bank), and the mob has dropped that exact same item as lootable, you will be unable to loot it because you can only have one of any Unique item. As such, you will be unable to skin that mob.

**Comment by Killyana** [comment]
I made some tests an the npc doesn't get the skinnable flag until everything is looted, so it's blizzlike.

**Comment by BittyBit** [comment]
Was this closed because you are combining it with another ticket or because you feel that it is working as intended/blizzlike?

> In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item.

I am aware of that behavior and that is not the issue. It can be the first mob and first quest item that drops and it still exhibits the behavior.

The issue is that the mob doesn't get flagged skinnable after everyone has looted it, and that is not blizzlike. It seems like there isn't a good check to see if the quest item was picked up by any party member as opposed to every party member when it only drops for one player. This causes the mob not to be flagged skinnable when it should be flagged.

I did not notice the problem until trying to level skinning while questing/leveling in a group. If you try it you'll understand that it isn't behaving as expected.

**Comment by Killyana** [comment]
I made many tests, and if the npc is not flagged it means there's some remaining loot.
If you think it's not the case provide the npc ID and how to reproduce the issue.

**Comment by BittyBit** [comment]
The situation I described in the first posting provides what you are asking. I believe the pridewing is NPC 4012. Honestly it is an issue with any mob that fits the criteria described; normally skinnable and drops quest loot for only one party member.

If as you say there is loot remaining on the mob then the issue is how to retrieve it. I'm inclined to agree with you that there is loot remaining on the mob causing it to not be flagged skinnable. What I am saying is that after a party member loots the mob the game should stop thinking there is loot on the mob and cause it to be flagged. The loot, if there, is not visible to any player and there is no way to retrieve it.

I'm going to walk thru this just because I am unsure where I am losing you:

1. Player A and Player B form a party to complete a quest to collect items that drop from skinnable mobs.
2. The loot rules for the party are unchanged from the default group loot (I haven't tested any other looting rules)
3. Player A and Player B kill a mob that is listed as Player A's loot but it is sparkling to Player A and Player B indicating there is a quest item on the mob
4. Player A loots the mob and receives the quest item as well as any other non-quest loot the mob dropped.
5. Player B no longer sees the mob sparkling
6. Player B right clicks the mob as if to loot and nothing happens.
7. Player A attempts to skin the mob but the mob is not flagged as skinnable so the corpse remains
8. Player A and Player B kill another mob that is listed as Player B's loot but again it is sparkling for both players indicating there is a quest item on the mob
9. Player A loots the mob receiving the quest item only
10. Player B still sees the mob as sparkling
11. Player B right clicks the mob to loot and receives whatever loot the mob dropped minus the quest item
12. Player A attempts to skin the mob but the mob is not flagged as skinnable so the corpse remains
13. Player A and Player B kill a mob that is listed as Player A's loot. The mob is sparkling to Player A but not Player B indicating there is no quest item on the mob.
14. Player A loots the mob and receives the quest item as well as any other non-quest loot the mob dropped.
15. Player B no longer sees the mob sparkling
16. Player B right clicks the mob as if to loot and nothing happens.
17. Player A attempts to skin the mob and is successful
18. Player A and Player B kill a mob that is listed as Player B's loot. The mob is sparkling to Player B but not Player A indicating there is no quest item on the mob.
19. Player B loots the mob and receives the quest item as well as any other non-quest loot the mob dropped.
20. Player A no longer sees the mob sparkling
21. Player A attempts to skin the mob and is successful

The quest item should only be available to the first player to loot it from the mob. That allows the melee players closest to the mobs to ninja loot all the quest items from ranged dps and that was a blizzlike hallmark for years. The mob not being flagged as skinnable because there is quest loot still on it that only one party member can see because they are the only ones with the quest is also blizzlike and used to happen with some frequency. Mobs not being flagged skinnable after all party members have looted all items is not blizzlike behavior.

**Comment by BittyBit** [comment]
I would appreciate it if you agree that the behavior is not blizzlike that you reopen this ticket so it can get better visibility to anyone that might have the inclination to code up a solution.

**Comment by BittyBit** [comment]
I can confirm that the issue disappears when looting is set to free for all. If anyone can point me to the section of code that handles placing/removing quest loot I would appreciate it.

**Comment by tkrokli** [comment]
Maybe not exactly what you asked for, but you could look at commit https://github.com/TrinityCore/TrinityCore/commit/f5d3343f27f68c7837152fc592310397a686a83e and derive more content from that.

**Comment by BittyBit** [comment]
I'm still not sure why this is marked closed or if it is kosher to be posting updates to a closed ticket.

I wanted to add that the issue is present regardless of skinning skill or even having the profession. Two of the same mobs will be flagged differently (skinnable or unmarked as skinnable) once looted by all party members even if no member of the group is actually capable of skinning.

**Comment by tkrokli** [comment]
Well, I think it is fair game to argue that closing the issue is wrong as long as more relevant arguments are posted. I just don't want to overrule the decision made by a member with more coding and testing experience than me.

**Comment by Killyana** [comment]
I wasn't able to reproduce the issue, for me once a mob is fully looted it's flagged skinnable.
Maybe some else could confirm that's not true.

**Comment by tkrokli** [comment]
OK, I will test a bit too with first player having to loot quest object(s) from skinnable mobs. Does it make much difference that one player is on a gm account with GM OFF, or do I need to test with only normal accounts?

**Comment by Killyana** [comment]
It doesn't matter, you need 2 chars from the same faction with a quest that requires item that drops from the npc that you will test (it must be skinnable)

**Comment by BittyBit** [comment]
> I wasn't able to reproduce the issue, for me once a mob is fully looted it's flagged skinnable.
Maybe some else could confirm that's not true.

Without trying to get lost in semantics, I think you are 100% right. The question is why isn't the mob becoming fully looted and how can we make it fully looted.

In retail there would be quest items you could see but not loot (because you already had enough of them, this item starts a quest you are already on, etc.) that would prevent the flag and very very rarely there would be a mob that would not be lootable but also not flagged skinnable as described in #13940 but the behavior we are seeing now (repeatable) did not exist.

**Comment by Killyana** [comment]
In some cases you will not be able to see or loot some items, and according to wowwiki it's blizzlike
http://wowwiki.wikia.com/wiki/Skinning
In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item. This usually happens when killing several mobs at once before looting and skinning them. There is no way to skin such a corpse other than to drop at least one of the quest items so you can then loot the item one more time. Due to game mechanics, random drops from mobs are almost always determined at the time of looting, rather at some previous time. And almost all looted items required for quests can be acquired beyond the quota for the quest. Rarely, this can happen with bosses who are supposed to drop a single quest item that respawn before their previous corpse has been looted, such as Combat 15 Princess.
If you possess a Unique item somewhere in your inventory (bags/bank), and the mob has dropped that exact same item as lootable, you will be unable to loot it because you can only have one of any Unique item. As such, you will be unable to skin that mob.

**Comment by BittyBit** [comment]
> In very uncommon circumstances, a corpse can contain a quest item that you can't see because you already filled your quota for that item.

This isn't that.

If others are going to test, I wanted to post an easier scenario. Apologies for not knowing all of the GM commands to simplify the testing.

There is a level 5 quest called Zenn's Bidding http://www.wowhead.com/quest=488/zenns-bidding given by the NPC Zenn Foulhoof http://www.wowhead.com/npc=2150/zenn-foulhoof to collect amongst other things Nightsaber Fangs http://www.wowhead.com/item=3409/nightsaber-fang that drop from Nightsabers http://www.wowhead.com/npc=2042/nightsaber located in the immediate area of the quest giver.

Not that I expect anyone to invest 20 minutes in leveling to test this, but if anyone wants to test without using any GM commands, just start a Night Elf character and that is the first quest you come across exiting the beginner spawn area.

**Comment by Aokromes** [comment]
as for wow 3+ you was allowed to loot more items than the max needed for quest.
IE: you have 9 items, quest needs 10, you loot 2 and you have 10.

**Comment by tkrokli** [comment]
That is an interesting fact. Are you implying that the last quest item would be ignored (9+2) so the extra quest item would be discarded by the game client (or server) somehow?

I only remember what I have seen, using TC source, when trying to loot more quest items (can't remember how it actually worked on retail on 3.3.5a and older), when I kill more quest mobs than needed (in case some of them would be empty) and find that the TC source won't allow me to loot the extra item(s) unless it is one of the quest item types which also drops without having the quest the item is intended for.

**Comment by BittyBit** [comment]
> That is an interesting fact. Are you implying that the last quest item would be ignored (9+2) so the extra quest item would be discarded by the game client (or server) somehow?

While I cannot confirm exactly what patch introduced that behavior (I'll take Aokromes' word that it was 3+ because it helps support my ticket ;P), when it was introduced it allowed the extra quest item to remain sitting in your bag. It wasn't discarded or ignored. You would turn in 10 and the last one would stay in your bag until you remembered it was an extra for a quest you did 20 levels before and manually discard it.

Current retail behavior seems to have resolved the issue somehow. I tested the Zenn's bidding quest in a group and in addition to all party members being able to loot the fangs that drop from every nightsaber (which was definitely NOT the case in 3.3.5a retail) a group member who had 5 did not see the item while a group member that had 3 did and the mob was flagged skinnable after being looted. Unless there was some serious RNG lined up against my testing, I killed 8 of them before looting any for the final fang needed. The fist one dropped the fang and the none of the others had the fang and were all skinnable after being looted. Prior to that the drop rate was somewhere between 1 in 2 and 1 in 3, so to go 0 in 7 seems unlikely. I am guessing Blizz introduced something to  cleanup the quest item from the remaining mobs to prevent extra quest items, at least from this quest, from clogging up bags and to allow the mobs to be flagged skinnable.

**Comment by tkrokli** [comment]
OK, so current retail behaviour is that you only get the required number of items. Before 4.0.0 it was different, you were able to loot more than the required number of quest loot items, as long as it dropped from the same kill or NPC (I presume). Surplus quest items would remain in your bag after delivering the quest, required manual removal by player to clean up the bags. Thanks for reminding me of how it used to work.

**Comment by ariel-** [comment]
I think OP means lootable by all quest item, not many drops of same item nor one drop of a not lootable by all item (think onyxia's head)

**Comment by tkrokli** [comment]
Yes, I get that. My previous comment was more based on my previous reaction to Aokromes' comment and then realizing what it was supposed to be like. But I also see how it would be an issue to have single loot items drop while not being able to see them, making the "empty" creature unskinnable.
