### ISSUE TITLE
Respawn of flying NPCs

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#20980]
**Description:**
When you respawn a NPC that has INHABIT_AIR with DespawnOrUnsummon foceRespawnTime, it is not spawned on its home position, but on the position where it was despawned (it is not visual desync). It also looses the ability to fly and fall to the ground. This bug does not apply to ground creatures.
Tested on [Rimefang](http://www.wowhead.com/npc=36661/rimefang) and [Zhao-Ren](http://www.wowhead.com/npc=55786/zhao-ren).

**Current behaviour:**
NPC flies to some position, it is despawned and then spawned on the same position. After spawn, it falls to the ground and is not able to fly anymore.

**Expected behaviour:**
NPC flies to some position, it is despawned and then respawned on its home position. It should also has his ability to fly.

**Steps to reproduce the problem:**
1. create or edit some NPC script where you add some movement and then respawn using DespawnOrUnsummon function

**Branch(es):** master

**TC rev. hash/commit:** b12b37058c863bcfecfefc965da45f31b604ee3b

**TDB version:**  720.00

**Operating system:** Win 7 x64

**Comment by Killyana** [comment]
Fixed by dynamic spawns, you must just wit for the cherry picks.

**Comment by tkrokli** [comment]
![](https://img.medscape.com/thumbnail_library/dt_170111_cherry_picking_800x600.jpg)

**Comment by Killyana** [comment]
No need to keep open issues that just requires cherry picks from other branches.
