### ISSUE TITLE
Quest A Rough Ride

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21005]
**Description:**

The quest would complete if you reach the 39th waypoint, but somehow its not happen and just the Crocolisk despawned.

i've checked smart_scripts and cant find any problem there 🧐 ( 28308 )

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. fc0f80594d6d 2017-11-27 11:47:32 +0330 (3.3.5 branch) (Unix, release, Static)

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 16.04

**Comment by Aokromes** [comment]
Very likely #20310
