### ISSUE TITLE
Cmake not allowing 1.1.0b openssl on ubuntu

### ISSUE THREAD

**Issue by dimiandre** [TrinityCore/TrinityCore#21004]
**Description:**

On Ubuntu 17.10 (Artful) the libssl-dev/openssl package present in the repository is only 1.1.0g, and cmake seems to not allow that version 

**Current behaviour:**

When you run cmake you will get this error

```
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
CMake Error at cmake/macros/FindOpenSSL.cmake:226 (message):
  TrinityCore needs OpenSSL version 1.0 but found version 1.1.0g
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)
```

**Expected behaviour:**

It should generate the project because inside /cmake/macros/FindOpenSSL.cmake there is this "MAX_VERSION": 
set(OPENSSL_MAX_VERSION "1.1")

so it should allow 1.1.0g 

I temporarily avoided the error changeing it to 1.2, and i'm compiling fine

**Steps to reproduce the problem:**

1. Follow the wiki installing the sudgested packages
2. Run cmake

**Branch(es):**

master

didn't checked on 3.3.5 / 4.3.4 but i think it's the same

**TC rev. hash/commit:** 

TrinityCore rev. ce0054f03090 2017-11-25 22:28:30 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemo) ready...

**Operating system:** 
Ubuntu 17.10

**Comment by Shauren** [comment]
No. This is intended.

**Comment by Riztazz** [comment]
https://i.imgur.com/e7b92Yn.png

**Comment by dimiandre** [comment]
Yes i'm sorry, i just noticed that even with the trick the tools are not compiling. 

Someone have good hints on how to downgrade openssl from 1.1 to 1.0 (ubuntu 17) ?

**Comment by Riztazz** [comment]
Just provide openssl root dir path in cmake
cmake -DOPENSSL_ROOT_DIR=/usr/...

**Comment by Shauren** [comment]
install `libssl1.0-dev`
