### ISSUE TITLE
Lady Sathrah does not spawn where she is supposed to...

### ISSUE THREAD

**Issue by Psiborg001** [TrinityCore/TrinityCore#21006]
When given the quest "Tears of the Moon", I can run a character to the location where she is supposed to spawn and cannot find her anywhere in the area.

I am currently running core revision: 7150f8216933
I am currently running DB revision: TDB 335.63

http://www.wowhead.com/quest=2518/tears-of-the-moon
http://www.wowhead.com/npc=7319/lady-sathrah

Branch: 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 7150f8216933 2017-11-28 23:46:20 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  TDB 335.63

**Operating system:** Windows 7

**Comment by tkrokli** [comment]
"where she is supposed to spawn" is ambiguous, you have not said anything about where you have looked up that information. For all we know, you may have looked at the wowhead page, which might not be the exact information used in TDB 335.63, Please tell us more about where you think you are supposed to find that creature.

![wowscrnshot_112917_075215](https://user-images.githubusercontent.com/4903600/33361911-547dafcc-d4da-11e7-9169-b6a2c9a80b08.jpg)

**Comment by Psiborg001** [comment]
I look at the game map, and head for the marker. From there, I roamed from
the location where Sethir is located, to the river. That's the area where
she is supposed to spawn (has always spawned, any time I've played, before).

If you like, I can provide exact coordinates, and screenshots, next time.

**Comment by tkrokli** [comment]
TC quest spawns are often not at the same spot as the game client indicates via add-on indicators. Compared to what you see in the game client, this quest mob is spawned on the other side of the river. The presence is also easy to check when you use a GM character like I did. Unless you can document that the current spawn coordinates are incorrect (based on sniffs from before 2010-10-10), the creature will stay at its current location.

**Comment by Psiborg001** [comment]
I don't know what you mean by "add on indicators". I'm going off the basic
map that has always been provided by the client.
[image: Inline image 1]

For as long as I've played this game, the indicator has accurately pointed
the vicinity in which Sathrah could be found. She wandered up and down the
hill to the river. That is where I always found her.

If Wowhead (et al) is such a terrible reference, why is it something that
is part of the example of a bug tracking report? From what I've seen, most
of those database sites have been accurate, and some of them actually give
some history of where mobs once spawned versus where they spawn, now.

If this is where Sathrah spawns, I'll just have to keep it in mind that
this is the "official" spot, now.

On Nov 29, 2017 5:12 AM, "tkrokli" <notifications@github.com> wrote:

TC quest spawns are often not at the same spot as the game client indicates
via add-on indicators. Compared to what you see in the game client, this
quest mob is spawned on the other side of the river. The presence is also
easy to check when you use a GM character like I did. Unless you can
document that the current spawn coordinates are incorrect (based on sniffs
from before 2010-10-10), the creature will stay at its current location.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TrinityCore/TrinityCore/issues/21006#issuecomment-347842374>,
or mute the thread

**Comment by Psiborg001** [comment]
Hopefully, this thread will help others who have the same issue.

Thanks for the response.

**Comment by offl** [comment]
There was another issue with the same description: https://github.com/TrinityCore/TrinityCore/issues/9011
POI data and creature data doesn't match.
```text
position_x  position_y  
----------  ------------
   10979.6       1366.13

     X       Y  
------  --------
 10973      1826
```

But I assume they shouldn't match, because NPC should have path:
> confirmed at co ordinates 29,25 (she respawns here) then moves along to the river and ends up co ordinates 48,25. She will be at one of the locations. Hope this helps
>
>48,25 = X: 10979 Y: 1366
>29,25 = X: 10973 Y: 1826

Also after reading other comments I found that:
> Took about an hour, but I found her, looks like the green spiders found around the area, but she's silver. If you happen to see someone else kill her, go farm mats for about 2 hours and come back. Not worth waiting for.
--
damn, last time i did this i found her right away, now it was Haaard! i found her at 47.9/25.7 on the other side of the wellspring lake, damn. x'D weeell! its dooone =P
-- 
Yea, all the coords or different somehow, but anyone works, i have no idea why she's a spider! But i cannot do it yet since i am not a high enough level...meh. But the screen shot is cool...she either got killed and crept into a spiders life, something like that...

All these comments are from WotLK, so everything is blizzlike except one thing - NPC must have path. Maybe can be found in https://github.com/TrinityCore/TrinityCore/commit/f85ac27912362f019639cd61f7aada0116532bda. Someone should check if she have path on master.

**Comment by tkrokli** [comment]
Hmm. Good point. After all, it should be easy to use a trial account and fool about in Teldrassil. Then again, I worry that changes might have been made either in Cataclysm or Mists of Pandaria.

**Comment by offl** [comment]
As far as I remember textures in that place weren't changed, anyway should be checked.
