### ISSUE TITLE
Wooly Justice

### ISSUE THREAD

**Issue by dewmguy** [TrinityCore/TrinityCore#21017]
**Description:**
http://www.wowhead.com/quest=12707/wooly-justice

**Current behaviour:**
[Rushing Charge](http://www.wowhead.com/spell=52601/rushing-charge) (Button 1) is uncastable. It just appears greyed out, but it does correctly appear uncastable when the target is within 5 yards (button turns red).

Also, the mammoth remains calmed indefinitely.

**Expected behaviour:**
Rushing Charge should be castable from within 45 to 5 yards of the target.

The mammoth should only remain calmed by the quest item for up to 15 seconds.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  1f9f59b4b3b9

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
Seems like you are able to use Charge [only once](https://youtu.be/c0jhYGx0BvU?t=25). Charge cannot be used in combat.

**Comment by offl** [comment]
http://www.wowhead.com/spell=52599/out-of-bounds#comments NYI

**Comment by Killyana** [comment]
Attributes: 0x30200000 (SPELL_ATTR0_IMPOSSIBLE_DODGE_PARRY_BLOCK, SPELL_ATTR0_CANT_USED_IN_COMBAT, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)

**Comment by Killyana** [comment]
Spells works correctly, the issues I have is the mammoth continue the random movements once mounted and once a troll is killed it remains in combat (for this reason you cannot use the charge again) , I must gm on and off to make it ooc (looks like his in combat with the player).

**Comment by offl** [comment]
[Here](https://youtu.be/c0jhYGx0BvU?t=147) he is in combat and after `Passenger Removed`, so he uses Feign Death.

**Comment by offl** [comment]
Seems like on retail you should wait to leave combat :/
https://youtu.be/YVeEF7yOcTc?t=14

**Comment by CraftedRO** [comment]
835e2918319e The quest seems to work just fine:

https://user-images.githubusercontent.com/24683355/214100267-4cc970d5-cf12-48bb-b77b-50933050f19a.mp4
