### ISSUE TITLE
Core crashes: Segmentation fault

### ISSUE THREAD

**Issue by nudlpwn1** [TrinityCore/TrinityCore#21014]
**Description:**

worldserver binary crahes early

**Current behaviour:**

As one can see here:
https://gist.github.com/nudlpwn1/1449e67567452742f06b1d428af66add#file-server-log
The server crashes early with 'segmentation faul'

debugfile:
https://gist.github.com/nudlpwn1/1449e67567452742f06b1d428af66add#file-backtrace-log

**Expected behaviour:**

Worldser

**Steps to reproduce the problem:**

1. compile core on OS
2. set it up
3. start

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0f6feb828baf+ 2017-11-29 09:24:55 +0100 (3.3.5 branch) (Unix, None, Static) (worldserver-daemon)

**TDB version:** 335.63 TDB Version of the TrinityCore database

**Operating system:** UBUNTU 16.04 LTS OS

**Comment by Aokromes** [comment]
TrinityCore rev. 1f9f59b4b3b9+ 2017-11-30 23:36:45 +0100 (3.3.5 branch) (Unix, None, Static) (worldserver-daemon) ready...

**Comment by nudlpwn1** [comment]
Getting same error with TrinityCore rev. 1f9f59b4b3b9+ 2017-11-30 23:36:45 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Aokromes** [comment]
You are using a modified client? because i am unable to reproduce your crash.

**Comment by r00ty-tc** [comment]
Looks to me like it's kicking up a fuss loading deDE strings from AreaTable.dbc. I have deDE here too. But I am not sure if it loads anything but the default locale.. I'll have to check later.

**Comment by r00ty-tc** [comment]
No crash here, with deDE default locale, and 1f9f59b4b3b90f2976201c9b814b723c15a715fd on Win64. Don't have an Ubuntu 16.04 to hand though. Just 14.04 and 17.10.

**Comment by nudlpwn1** [comment]
Not using anything modified. :/

So, it's presumably the OS?

**Comment by r00ty-tc** [comment]
It's possible. I just know it starts fully OK for me with deDE set to default locale (and I have deDE dbcs) running on Win 64 build.

If you have access to a windows machine, might be worth testing with your dbc files (to rule out they were corrupt somehow) and if it's fine, it's likely some interaction with the O/S yes.

**Comment by Aokromes** [comment]
from where you have downloaded your wow client?

**Comment by nudlpwn1** [comment]
You are correct, it IS a corrupted client which caused this problem.
I used 2 different ones, now, I used another (fresh downloaded) client (with deDE) and it work's just fine. (No fresh compile, dropped world db/ extracted dbc / started)

Works now. Sorry for any trouble's I've caused and thank you very much for your help..
