### ISSUE TITLE
Inspiration does not work properly with Prayer of Mending

### ISSUE THREAD

**Issue by Braoo** [TrinityCore/TrinityCore#21011]
**Description:**

Inspiration (Rank 3): Reduces your target's physical damage taken by 10% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Penance, Prayer of Mending, Prayer of Healing, or Circle of Healing spell.
The problem is Inspiration does not work with Prayer of Mending.

**Current behaviour:**

Prayer of Mending critical hits do not trigger Inspiration.

**Expected behaviour:**

Prayer of Mending critical hits should trigger Inspiration.

**Steps to reproduce the problem:**

1. Cast Prayer of Mending continuously on target that is receiving continuous damage.  
2. Wait for a critical strike.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

463ed5e

**TDB version:**  TDB335.63

**Operating system:** Windows

**Comment by tkrokli** [comment]
Nice to see such a proper issue ticket. Almost a shame that you had to close it.
