### ISSUE TITLE
Scourgekabob

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21020]
**Description:**
http://www.wowhead.com/quest=12484/scourgekabob

**Current behavior:**
Clicking the [Scourged Troll Mummy](http://www.wowhead.com/object=190223/scourged-troll-mummy) object gives you the [Scourged Troll Mummy](http://www.wowhead.com/item=38149/scourged-troll-mummy) item, then causes the object to ignite and then it despawns.

**Expected behavior:**
Clicking the Scourged Troll Mummy should give you the item, but it should only ignite after you have used the item from your inventory, placing the mummy on the burning pile. The mummy should not ignite when you've picked it up.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1f9f59b4b3b9

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by STARRHELD** [comment]
Could you please provide source that this is correct? It's purely visual as well, the quest in its state is completable.

There are videos showing fire + despawning on looting the Mummy:
https://www.youtube.com/watch?v=oGg681A6FSs

**Comment by offl** [comment]
Your video is from private server.
Here's two from retail:
https://www.youtube.com/watch?v=uDK-46RDeqw
https://www.youtube.com/watch?v=FK-x7DqpLZ8

**Comment by STARRHELD** [comment]
If that's the case then just remove the burnup of the corpse

**Comment by jerbookins** [comment]
@STARRHELD It doesn't matter if it's just a cosmetic issue. While I play the game I create issues for things that aren't correct. It isn't about whether one issue is better or worse than another issue.

**Comment by tkrokli** [comment]
@jerbookins : I don't think his comment was directed at you, I think it was meant to anyone who will be able to post a suggested solution or the TC members who will push the solution commit.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=FK-x7DqpLZ8

meanwhile this works fine and is fixed

**Comment by Killyana** [comment]
I made some cosmetic changes.
