### ISSUE TITLE
DB/Creature: Riverpaw Shaman missing spawns

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#21021]
**Description:**

Currently there is only one Riverpaw Shaman spawned, two Riverpaw Scouts should be replaced with Riverpaw Shamans.

http://www.wowhead.com/npc=1065/riverpaw-shaman
http://www.wowhead.com/npc=500/riverpaw-scout

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c7043b25f659 2017-12-02 00:02:16 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  335.63

**Suggested Fix:**

```sql
-- Replace two Riverpaw Scouts with Riverpaw Shamans
DELETE FROM `creature` WHERE `guid` IN (86657, 86662);
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(86657, 1065, 0, 0, 0, 1, 1, 204, 1, -9746.86, 1189.25, 41.162, 3.7175, 300, 0, 0, 230, 249, 0, 0, 0, 0, 0),
(86662, 1065, 0, 0, 0, 1, 1, 204, 1, -9719.46, 1440.99, 45.073, 2.6005, 300, 0, 0, 230, 249, 0, 0, 0, 0, 0);
```

**Comment by Aokromes** [comment]
why no simply update the id?

**Comment by Serpaa** [comment]
Dunno why I thought it would be better to replace them instead of updating the existing ones, here is the simpler updated sql:

```sql
-- Replace two Riverpaw Scouts with Riverpaw Shamans
UPDATE `creature` SET `id`=1065, `modelid`=204, `curhealth`=230, `curmana`=249 WHERE `guid` IN (86657, 86662);
```

**Comment by offl** [comment]
Maybe they're pooled?

**Comment by Serpaa** [comment]
I really don't think blizzard would use pools for something like gnoll camps.

**Comment by offl** [comment]
They uses pools in each location :)

**Comment by tkrokli** [comment]
Which tables are used in this case? I tried to look for creature `guid` 86657, 86662 or  ID (500, 1065), but I did not find a match. Maybe I looked for the wrong values?

**Comment by Serpaa** [comment]
What exactly are you looking for? This SQL just replaces two Riverpaw Scouts with two Riverpaw Shamans, don't know why we started talking about pools.

**Comment by tkrokli** [comment]
I should have addressed my question directly to @offl since he introduced the question. I can't find any proof, so someone else will have to do so if there is any.

**Comment by offl** [comment]
Because obviously if you think that NPC "A" must be NPC "B" then there must be a pool. Because NPC "A" was sniffed. And when it was sniffed there was only one NPC "A".

Example: we sniffed 15 tortoises and only 5 kangoroo. A quest required 10 kangoroo. What can we done? We can add a pool. So there will be a (small)chance that  only 20 kangaroo will be spawned or only 20 tortoises. Or 10 kangaroo and 10 tortoises.

(or only one Riverpaw Shaman and 923 Riverpaw Scouts)

For this issue: just push the suggested fix, no matter what to do here, pools or id change. Dunno why I started talking about this.

**Comment by Serpaa** [comment]
Makes sense, the thing is just that there is only a small amount of information about this issue. Which makes it very difficult to find out how Blizzard implemented this pool.

**Comment by offl** [comment]
From 4.3.4 sniffs:
```sql
(@CGUID+309, 1065, 0, 1, 1, -9753.045, 1198.839, 41.06225, 4.852015, 120, 0, 0), -- Riverpaw Shaman (Area: Longshore)
(@CGUID+310, 1065, 0, 1, 1, -9747.28, 1188.79, 41.06223, 2.460914, 120, 0, 0), -- Riverpaw Shaman (Area: Longshore)

(@CGUID+24, 500, 0, 1, 1, -9737.032, 1028.849, 37.67341, 3.487038, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+25, 500, 0, 1, 1, -9664.42, 974.5647, 36.74027, 2.227448, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+29, 500, 0, 1, 1, -9719.453, 1019.487, 38.21123, 3.233646, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+30, 500, 0, 1, 1, -9725.191, 993.3609, 34.49269, 0.8206596, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+31, 500, 0, 1, 1, -9688.909, 1010.495, 34.98423, 1.066488, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+34, 500, 0, 1, 1, -9691.194, 1039.552, 36.37978, 4.216414, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+35, 500, 0, 1, 1, -9713.94, 1055.807, 35.05927, 3.848895, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+71, 500, 0, 1, 1, -9761.301, 1041.023, 30.82666, 4.332574, 120, 0, 0), -- Riverpaw Scout (Area: The Jansen Stead)
(@CGUID+297, 500, 0, 1, 1, -9691.816, 1456.104, 48.24353, 3.941808, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+298, 500, 0, 1, 1, -9696.382, 1419.383, 47.07426, 4.281003, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+302, 500, 0, 1, 1, -9715.04, 1212.588, 41.2898, 4.044664, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+317, 500, 0, 1, 1, -9789.465, 1452.033, 45.3976, 5.428005, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+403, 500, 0, 1, 1, -9895.233, 1561.351, 44.42556, 2.33704, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+407, 500, 0, 1, 1, -9864.574, 1591.458, 40.18173, 0.1880265, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+514, 500, 0, 1, 1, -9913.867, 1528.504, 44.51794, 2.203755, 120, 0, 0), -- Riverpaw Scout (Area: Longshore)
(@CGUID+1141, 500, 0, 1, 1, -10618.17, 1913.472, 43.52425, 6.170235, 120, 0, 0), -- Riverpaw Scout (Area: Gold Coast Quarry)
```

Your suggestion and 4.3.4 sniffs:
```sql
(86657, 1065, 0, 0, 0, 1, 1, 204, 1, -9746.86, 1189.25, 41.162, 3.7175, 300, 0, 0, 230, 249, 0, 0, 0, 0, 0),
(@CGUID+310, 1065, 0, 1, 1, -9747.28, 1188.79, 41.06223, 2.460914, 120, 0, 0), -- Riverpaw Shaman (Area: Longshore)
```

**Comment by Killyana** [comment]
If someone want to add a pool for this npcs he could open a new issue.
