### ISSUE TITLE
DB/Quest: Test of Lore (Part 6)

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21026]
**Description:**

On this quest, Parqual Fintallas (questgiver) asks you the true name of the Lich King, and then you should select 1 of 4 possible options. If you answer correctly, quest will complete, and if you answer incorrectly you will be buffed with some spell (Mark of Shame).
But when selecting gossip option 'Kil'jaeden is my answer.' nothing happens. (Script is using wrong  `event_param1`)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Parqual Fintallas
UPDATE `smart_scripts` SET `event_param1`=4764 WHERE `entryorguid`=4488 AND `source_type`=0 AND `id`=10;

**Comment by tkrokli** [comment]
Good catch, thank you for testing and posting a fix. The bug could be something left over from when I converted it from C++ script to SAI, although I haven't checked if there has been any changes after that.
