### ISSUE TITLE
quest 12701

### ISSUE THREAD

**Issue by naydensova** [TrinityCore/TrinityCore#21030]
Info:

> TrinityCore rev. a4b2c9988a51 2017-12-05

> TDB version:TDB 335.63+ lust update

> Branch:3.3.5а 

> Operating system: Win 7 x64 

Problem:
After the character gets into the Inconspicuous Mine Car, nothing happens

quest:
http://www.wowhead.com/quest=12701/massacre-at-lights-point
objective:
http://ru.wowhead.com/object=190767

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20310

**Comment by jerbookins** [comment]
#20310
