### ISSUE TITLE
ASSERTION FAILED-error after upgrade to newer revision

### ISSUE THREAD

**Issue by DerC88** [TrinityCore/TrinityCore#21034]
**Description:**

The worldserver application stops while initializing 'SpellInfo store' with an ASSERTION FAILED error in TrinityCore/src/server/game/Spells/SpellMgr.cpp:2555 in LoadSpellInfoStore

**Current behaviour:**

It simply crahses. Older revisions are working fine (have the option to recover the virtual machine from a backup). My server has been working for quite a long time but a couple of days ago I updated it to a current version (via git pull origin 3.3.5), it compiles fine but stops with error.

**Expected behaviour:**

worldserver should start up without errors. 

**Steps to reproduce the problem:**

1. git pull origin 3.3.5
2. cmake ../ -DTOOLS=1
3. make
4. make install
5. use extractors
6. start worldserver

or

1. download full 3.3.5 repository
2. cmake ../ -DTOOLS=1
3. make
4. make install
5. use extractors
6. start worldserver

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4464ec43aa59 2017-12-05 23:44:39 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Ubuntu 16.04 current

If something's missing or if you need more information - just tell me.

**Comment by Jildor** [comment]
have you applied all sql updates?
https://github.com/TrinityCore/TrinityCore/commit/8e1c74d95a79a366ca755c9ebdc2fdd24c135284

**Comment by jackpoz** [comment]
can you post the full assertion log ?

**Comment by mindsear** [comment]
I can confirm you must apply the sql updates.
I had the same problem last night.

**Comment by tkrokli** [comment]
We need more logging info, either like jackpoz said in https://github.com/TrinityCore/TrinityCore/issues/21034#issuecomment-350243442 or gist with content from DBErrors.log + Server.log and your **worldserver.conf** content too.

Notice that **mindsear** may be right about why you get this issue, that you do not have all SQL updates applied. Have you disabled DB Auto Updater (SQL updates auto import)?

**Comment by RobertoAlois** [comment]
I have the same problem. Here is the crash report:
https://pastebin.com/J6BF8L4T

Server.Log:
https://pastebin.com/3SG5W6CY

worldserver.conf:
https://pastebin.com/JWPG2a6W

The SQL updates are applied by the Worldserver automatically and the DBErrors.log is empty.

**Comment by jackpoz** [comment]
> can you post the full assertion log ?

the message on the console is not logged to the file, please post the whole assertion message displayed in worldserver.
I see you have deDE dbcs, could you try with enGB ones ?

You could also build https://github.com/TrinityCore/TrinityCore/commit/3d1ba42f428c6b920240e208c854b0bcd5d664b1 commit and look at the error log about spell effects greater than the allowed value.

**Comment by RobertoAlois** [comment]
Is this the missing part of the log you are referring to?
https://imgur.com/a/djPQJ

**Comment by jackpoz** [comment]
do you have any custom spell with SPELL_EFFECT 2907 ? did you add anything custom in spell_dbc table or applied to Spell.dbc ?

**Comment by RobertoAlois** [comment]
No I did not, spell_dbc and Spell.dbc should be unchanged.

**Comment by jackpoz** [comment]
Run this query on world database and post the result if it finds any row. 

```sql
SELECT Id, COMMENT FROM `spell_dbc` WHERE `Effect1` >= 165 OR `Effect2` >= 165 OR `Effect3` >= 165 OR `EffectApplyAuraName1` >= 317 OR `EffectApplyAuraName2` >= 317 OR `EffectApplyAuraName3` >= 317 OR `EffectImplicitTargetA1` >= 111 OR `EffectImplicitTargetA2` >= 111 OR `EffectImplicitTargetA3` >= 111 OR `EffectImplicitTargetB1` >= 111 OR `EffectImplicitTargetB2` >= 111 OR `EffectImplicitTargetB3` >= 111;
```

Did you add any custom changes at all ? If you build in Debug and post the crashlog we can check what's the spell id (and maybe post your Spell.dbc file while at it)

**Comment by RobertoAlois** [comment]
Ok the SQL query returns nothing.
https://imgur.com/a/9H09u

The only changes I made are on the creature table.

[Spell.zip](https://github.com/TrinityCore/TrinityCore/files/1543261/Spell.zip)

And the Crash.log on debug:
https://pastebin.com/4rR8K43K

**Comment by jackpoz** [comment]
The crashlog shows spellID 1200035 triggered the issue and that's not a spell contained in WoW client. Your dbcs have bad data, either because they got manually modified or because the client itself was modified.
Did you extract the dbcs on your own ? Where did you get the client ?

**Comment by RobertoAlois** [comment]
Yes I extracted the dbcs myself and the client is an old installation that I had on my pc. It should not be modified. I guess I should try to extraxct the dbcs from an other client just to be sure.

**Comment by jackpoz** [comment]
These are all the high ID spells in your Spell.dbc
![ta5mdz](https://user-images.githubusercontent.com/1153754/33777521-79c7d16e-dc45-11e7-9f40-264c5dddf9e8.jpg)

This is the spell with a very high Spell Effect that is triggering the assert:

![yx0k9w](https://user-images.githubusercontent.com/1153754/33777524-7b15e394-dc45-11e7-924e-1c7ce1b6ffc4.jpg)

**Comment by Jildor** [comment]
it seems that it is not very blizzlike 😄

**Comment by DerC88** [comment]
Hopefully i don't open this issue again by answering, but I'd like to report that it was indeed a corrupt client. Had to install from scratch via my wrath of the lichking dvd + patch to 3.3.5a and its working again. Don't know what happened to my client but that's rather unimportant i guess =)
