### ISSUE TITLE
Core/Pooling: fishing school gameobjects not visible

### ISSUE THREAD

**Issue by Strazhnik** [TrinityCore/TrinityCore#21032]
**Description:**
Gameobject don't visible where id=182956, 182954, 182953
http://www.wowhead.com/object=182956/school-of-darter
 
**Current behaviour:**
Not visible

**Expected behaviour:**
Should be visible

**Steps to reproduce the problem:**
1. go xyz where gameobject id=182956, 182954, 182953 

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
123e8a95ba60b4706617da03eb047efadc32e0e9

**TDB version:**  63

**Operating system:**  Win 7

**Comment by Killyana** [comment]
There's an issue with the pooling, I don't know if the "chance" is wrong or something related to the last changes
Example the pool 311 has max_limit=1 but you find none of the gobs spawned:
``` 
guid, pool_entry, chance
64547,  311,        0, 
64585,  311,        0, 
64704,  311,       20,

**Comment by Killyana** [comment]
@lachtanek can you check this issue?

**Comment by lachtanek** [comment]
@Killyana isn't here an error during server load, along the lines of
```Pool Id X has no equal chance pooled entites defined and explicit chance sum is not 100.```
because by a quick look that pool doesn't seem valid to me, when you specify a chance for one member, you need to specify it for the others aswell.

**Comment by Killyana** [comment]
No errors on db or server log.

**Comment by lachtanek** [comment]
Thanks for clarification, looks like my code is wrong because I didn't understand it correctly before. 
How do I do this, open a new PR?

**Comment by Killyana** [comment]
Yes please.

**Comment by Strazhnik** [comment]
@lachtanek, may be revert?

**Comment by lachtanek** [comment]
@Strazhnik sorry, kind of forgot about this, I'll open a new PR in a few days with the fix

**Comment by ariel-** [comment]
c50aefac963aca5daeacf409deca9692c6ca3924
