### ISSUE TITLE
Core/Loot: GroupId for reference loot

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21037]
**Description:** On reference_loot_template the Group_Id doesn't define only a group but in some cases also the number of items that will drop from this group, it's probably an error as it doesn't make sense.

**Current behavior:** GroupId value defines the number of items that will drop from this group.

**Expected behaviour:** GroupId mut only used to separate items into groups, the min/max is handled else ware.

**Steps to reproduce the problem:**

1. Take an alliance char  
2. .go c id 35013
3. if you kill the npc on mode 10 you will get 3 items and in mode 25 you will get 8 items
4. if you make the same test with a horde char you will get 2 items on 10 and 4 in 25

To understand the issue you must look in to this results:
``` sql
SELECT * FROM creature_loot_template WHERE entry IN (35360,35013);
SELECT * FROM reference_loot_template WHERE entry IN (34205,34204);
```
Alliance Armor sets are using the GroupId=2
Horde Armor sets+ pvp set are using the GroupId=1
It's the only difference, the number of item drop is defined into creature_loot_template.MaxCount, and it works fine for horde drops.

I made a change:  Horde Armor sets+ pvp set to GroupId=0 and Alliance Armor sets to GroupId=1, and in this case horde items and the pvp set stops dropping.

**Branch(es):** both

**TC rev. hash/commit:** rev. 0725f608aa7

**Comment by Shauren** [comment]
Loot groups always worked like that - only a single item from entire group can ever drop, what you want to use in your case is use reference loot

**Comment by Killyana** [comment]
I'm talking about reference_loot_template in this case

**Comment by meji46** [comment]
Bad design in BD.

> Alliance Armor sets are using the GroupId=2
> Horde Armor sets + pvp set are using the GroupId=1

And each faction item with a condition (except PvP items).

Alliance character rolls for an Alliance item (groupid 2) and 1 item of the other groupid:

- PvP item (without condition), added to the loot
- Horde item (with condition), excluded from the loot
- 1-2 items x 2/4 = 2-4 / 4-8

Horde character only rolls for a Horde item (groupid 1).

I suggest splitting the reference into 3 references (pvp, alliance, horde) and use this structure:

Main Ref:

- 5-10% PvP Ref
- 90-95% Faction Ref

Faction Ref:

- 100% Alliance Ref (with condition)
- 100% Horde Ref (with condition)

**Comment by Killyana** [comment]
@meji46 is it the only case we have on the DB?

**Comment by meji46** [comment]
@Killyana I think so. Maybe there is a Baradin Hold boss with the same loot structure (faction loot /pvp loot)
