### ISSUE TITLE
DB/Quest: Disclosure monologue shows $n

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21040]
**Description:**
http://www.wowhead.com/quest=12710/disclosure

**Current behaviour:**
The name variable ($n) is not correctly compiled in dialogue.

**Expected behaviour:**
"$n" in dialogue should be compiled to be the name of the character performing the quest.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 869affa89300

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
```sql
SELECT * FROM `creature_text` WHERE `CreatureID`=28948; -- Malmortis' text lines
SELECT * FROM `smart_scripts` WHERE `entryorguid` LIKE '28948%' -- SAI Lines
```
**Preliminary solution suggestion:**
```sql
--
UPDATE `smart_scripts` SET `target_type`=7, `action_param3`=1 WHERE `entryorguid` IN (28948,2894800) AND `source_type` IN (0,9) AND `action_type`=1; -- talk target = target
UPDATE `smart_scripts` SET `comment`= 'Malmortis - On Waypoint 80 Reached - Say Line 6 (No Repeat)' WHERE `entryorguid`=28948 AND `source_type`=0 AND `id`=6; -- "Line 6" instead of duplicate "Line 7"
```
BTW, why isn't there a script line for his `GroupID = 2` text line:
`Ever since his arrival from Drak'Tharon, the master has spoken of the time you would be joining him here.`
... or have I missed out on something?

**Comment by offl** [comment]
GroupID 2 wasn't added https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB52_to_TDB53_updates/world/2013_09_03_03_world_sai.sql

**Comment by offl** [comment]
```sql
--
UPDATE `smart_scripts` SET `target_type`=7, `action_param3`=1 WHERE `entryorguid` IN (28948,2894800) AND `source_type` IN (0,9) AND `action_type`=1; -- talk target = target
UPDATE `smart_scripts` SET `comment`= 'Malmortis - On Waypoint 80 Reached - Say Line 6 (No Repeat)' WHERE `entryorguid`=28948 AND `source_type`=0 AND `id`=6; -- "Line 6" instead of duplicate "Line 7"
DELETE FROM `smart_scripts` WHERE `entryorguid`=28948 AND `source_type`=0 AND `id` IN (19,20,21);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(28948,0,19,20,40,0,100,1,2,0,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Malmortis - On Waypoint 2 Reached - Pause Waypoint (No Repeat)"),
(28948,0,20,21,61,0,100,1,0,0,0,0,1,2,0,0,0,0,0,7,0,0,0,0,0,0,0,"Malmortis - On Waypoint 2 Reached - Say Line 2 (No Repeat)"),
(28948,0,21,0,61,0,100,1,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Malmortis - On Waypoint 2 Reached - Set Orientation To Invoker");

**Comment by tkrokli** [comment]
OK, very well. I was just about to comment before your latest comment that the original commit was https://github.com/TrinityCore/TrinityCore/commit/26373ee76633f6d3015b34fa68d3f50d4cd6819e from **Sep 3, 2013** (2013-09-03), but that was only to point out when it was originally added. My only question was "why wasn't it added before?" meaning that I wanted to know if there was any specific reason for it to be left out, but I suppose that question is only academic and not worth pursuing.

I also presume you have checked that your suggested solution takes into account it this does not need to be part of the script (`2894800, 9, [...]`).

**Comment by offl** [comment]
Many things are missing in this script, not only the talk action.

> I also presume you have checked that your suggested solution takes into account that this does not need to be part of the script (2894800, 9, [...]).

Yep.

**Comment by jerbookins** [comment]
> BTW, why isn't there a script line for his GroupID = 2 text line:
Ever since his arrival from Drak'Tharon, the master has spoken of the time you would be joining him here.
... or have I missed out on something?

We are also aware that he only says this if you have completed [Cleansing Draktharon](http://www.wowhead.com/quest=12238/cleansing-draktharon), right?

**Comment by tkrokli** [comment]
OK, thanks. It has been some time since I did those quests. Forgot about the condition.

**Comment by offl** [comment]
Ok, we should add two variants https://www.youtube.com/watch?v=UEq8fEz8UOo

**Comment by peycho** [comment]
The quest looks like missing quest credit at the end.
Everything works as expected, but the quest can't be completed.

core: 57070192561b6f385e4c465d397feafe85df2413

**Comment by illfated** [comment]
I wish I had more ideas about this issue, but all I could come up with at the moment is:
"Would it be useful to make sure that Malmortis targets (selects) the player before saying his text line with $n in it?"
As for the quest completion issue, I don't know what is (not) happening there yet.

**Comment by dr-j** [comment]
working
~~~sql
UPDATE `smart_scripts` SET `target_type`=23,`action_param3`=1 WHERE `entryorguid` IN (28948,2894800) AND `source_type` IN (0,9) AND `action_type`=1; 
UPDATE `smart_scripts` SET `comment`= 'Malmortis - On Waypoint 80 Reached - Say Line 6 (No Repeat)' WHERE `entryorguid`=28948 AND `source_type`=0 AND `id`=6; 
UPDATE `smart_scripts` SET `target_type`='23' WHERE  `entryorguid`=2894800 AND `source_type`=9 AND `id`=3 AND `link`=0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=28948 AND `source_type`=0 AND `id`>18;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(28948,0,19,20,40,0,100,1,2,0,0,0,54,4000,0,0,0,0,0,1,0,0,0,0,0,0,0,'Malmortis - On Waypoint 2 Reached - Pause Waypoint (No Repeat)'),
(28948,0,20,21,61,0,100,1,0,0,0,0,1,2,0,0,0,0,0,23,0,0,0,0,0,0,0,'Malmortis - On Waypoint 2 Reached - Say Line 2 (No Repeat)'),
(28948,0,21,0,61,0,100,1,0,0,0,0,66,0,0,0,0,0,0,23,0,0,0,0,0,0,0,'Malmortis - On Waypoint 2 Reached - Set Orientation To Invoker'),
(28948,0,22,0,40,0,100,1,90,0,0,0,11,53101,2,0,0,0,0,23,0,0,0,0,0,0,0,'Malmortis - On Waypoint 90 Reached - Cast Kill Credit');
