### ISSUE TITLE
DK Quests malfunctioning

### ISSUE THREAD

**Issue by sigbinium** [TrinityCore/TrinityCore#21045]
**Description:**
http://www.wowhead.com/quest=12701/massacre-at-lights-point
http://www.wowhead.com/quest=12725/brothers-in-death

These 2 Death Knight Quests are currently bugged and have similar issues. I have little experience with the code or lingo you use here but I have a feeling it may have issues in pathing and/or unit flags.

**Current Behavior:**
Massacre at Light's Point: Minecart isn't dragged by Scarlet Miner and no speech from Miner or the script doesn't seem to trigger.
Brothers in Death: Koltira Deathweaver is moving around and attacking units and stops channeling the absorb shield, his armor also disappears few seconds after the fight begins.

**Expected Behavior:** 
Massacre at Light's Point: Minecart should be dragged after Scarlet Miner says his speech with regards to it's script.
Brothers in Death: Koltira is geared up, stays in the bubble and channels it.

**Steps to Reproduce the Problem:**

1. Clone the 3.3.5a branch from the repository.
2. Compile with latest working versions of the required software.
3. Insert latest DB and run server.

**Branch:** 3.3.5

**TC Rev. Hash/Commit:**  54d0b31

**TDB Version:** 335.63

**OS:** Win 8.1 Pro 64bit

**Note:**
I have searched through the issues and found several threads that may or may not be linked to this but apparently this has been fixed before and wanted to report it to the developers, in case this issue was missed.

**Comment by tkrokli** [comment]
Both issues caused by **Core/Movement: waypoint system issues #20310** (read that page to see some affected quests)
