### ISSUE TITLE
Core/Spells: SPELL_ATTR6_UNK14 possibly solved

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/TrinityCore#21049]
**Description:**
SPELL_ATTR6_UNK14 needs to be implemented

**Current behaviour:**
SPELL_ATTR6_UNK14 is not implemented

**Expected behaviour:**
I think SPELL_ATTR6_UNK14 is attribute to allow spells to ignore silence effects.
If someone wants to look further into it and perhaps debunk theory, go for it.
This is more of a issue for documentation.

**Branch(es):**
master

**TC rev. hash/commit:** 
0afec284903b24ee5f54178ff2274734cfc2814c

**Comment by mdX7** [comment]
How do you come to this conclusion? Any examples/spells? Or just random thought?

**Comment by Krudor** [comment]
Took a look at Siamat, and he has a spell he applies to himself that pacifies and silences him.
He's still able to cast spells just fine through this silence aura, and if you look at the attributes of the spells he cast, the only unknown attribute is this attribute.

After looking up which spells use this attribute, they all appear to have something in common, they should ignore pacify and silence effects.

I'm not 100% sure but I can't see it being anything else to be honest.

**Comment by Krudor** [comment]
Could be for silence only, it's applied to hunters auto shot as well, and that spell should be stopped by pacify.

**Comment by mdX7** [comment]
Tested Solarbeam from balance druid (http://www.wowhead.com/spell=81261) on:
[Anub'ar Venomancer](http://www.wowhead.com/npc=29217) [5NH] - [Poison Bolt](http://www.wowhead.com/spell=53617)
[Stormcaller Brundir](http://www.wowhead.com/npc=32857) [10 Man all 3 alive] - [Chain Lightning](http://www.wowhead.com/spell=61879)
[Deathspeaker Attentant](http://www.wowhead.com/npc=36811) and [Deathspeaker Disciple](http://www.wowhead.com/npc=36807) - [Shadow Bolt](http://www.wowhead.com/spell=69387)

They didn't cast the mentioned spell while they were silenced. Tested each npc above for around 8 mins and checked that I do not interrupt them with Solar Beam.

**Comment by Shauren** [comment]
Silence is not the same as pacify. Two distinct mechanics (Solar Beam is silence, this issue is about pacify)

**Comment by Krudor** [comment]
Do we know exactly what spell effect / aura effect solar beam causes?

**Comment by mdX7** [comment]
yes
```
Effect 0: EffectId: 68686 Id 6 (SPELL_EFFECT_APPLY_AURA)
Difficulty: Id 0 (DIFFICULTY_NONE)
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 27 (SPELL_AURA_MOD_SILENCE), value = 0, misc = 0 (0), miscB = 0, amplitude = 0, periodic = 0
```

**Comment by Krudor** [comment]
Hm ok, well I guess that debunks that theory :(

**Comment by Krudor** [comment]
Thanks for taking your time to help verify.

**Comment by mdX7** [comment]
Pacify still may be possible, but not sure how we may test that yet

**Comment by Krudor** [comment]
Don't think we need to test it, the spells you tested aren't auto-attack spells, and Pacify wouldn't affect those spells anyway.

But I think there is a problem with SPELL_PREVENTION_TYPE_SILENCE right now then, on master.
Gonna try to remember and debug this the coming weekend and verify.

**Comment by Warpten** [comment]
There is at least attr8_unk5 that allows casts while charmed (or at least related to that) that i found recently in 434 client, that one doesn't show so it must have come later

**Comment by aquadeus** [comment]
defined SPELL_ATTR6_AI_PRIMARY_RANGED_ATTACK but not implemented

**Comment by Nyr97** [comment]
The name itself may imply that's the default spell that the AI uses when the creature's target is not in range (see Sylvanas for reference, though her toolkit is a bit more complicated?)
