### ISSUE TITLE
Core/Spell: Proc on partial block

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21065]
**Description:** Some spells most procs when the player takes melee damage, it could be 
PROC_HIT_NORMAL, PROC_HIT_CRITICAL, or a partial block.
But actually this spells doesn't proc on partial block.

Notice:
PROC_HIT_FULL_BLOCK          = 0x0002000,
PROC_HIT_BLOCK                    = 0x0000040,  (full block and partial block)
We don't have partial block mask.

**Current behavior:** Partial block doesn't procs spells that requires melee damage taken.

**Expected behavior:** Partial block must procs spells that requires melee damage taken.

**Steps to reproduce the problem:**

1. Equip https://woehead.way-of-elendil.fr/?item=50344 and a shield
2. Take damage from an npc (same level as the char)
3. notice the trinket will procs only from  PROC_HIT_CRITICAL and PROC_HIT_NORMAL only, it will never procs from partial block

**Branch(es):** 3.3.5 probably both

**TC rev. hash/commit:** rev. 51c4196acf9d

**Comment by joshwhedon** [comment]
Ideally, I think we should make PROC_HIT_BLOCK = PROC_HIT_PARTIAL_BLOCK, and update the existing spells which should proc on both partial and full block.

**Comment by ariel-** [comment]
Interesting, will check.

In theory partial damage blocks set both 'block' and 'normal' or 'crit' flags, so they should be proccing nonetheless
