### ISSUE TITLE
Scripts/Steamvaults: Main Chambers Access Panels don't open Main Chambers door

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21067]
**Description:**
Panels Object ID: 184125, 184126
Door Object ID: 183049
http://wowwiki.wikia.com/wiki/Main_Chambers_Access_Panel
No wowhead link available, objects removed

**Current behaviour:**
Clicking each Main Chambers Access Panel behind Hydromancer Thespia and Mekgineer Steamrigger do not cause the main chambers door to unlock. The animation and audio that accompany the activation of the panel seem to start too late after clicking. And there is no emote indicating that you have triggered a reaction by activating the panel.

**Expected behaviour:**
Upon activating each access panel there is an emote:

    You hear a faint echo....

Upon activating the second panel there is an additional emote:

    You hear a loud rumble of metal grinding on stone...

This is when the Main Chambers Door is supposed to be unlocked.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 906a1331b008

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by jerbookins** [comment]
.gobject activate 32708

this opens the door

**Comment by Aokromes** [comment]
Try updating to at least 98236dfa8846aeea2643deaab5ca86b803e3aee7

**Comment by jerbookins** [comment]
I literally updated like 3 hours ago

**Comment by Aokromes** [comment]
Maybe 98236df changed it.

**Comment by jerbookins** [comment]
No.

**Comment by Maxwelllmj** [comment]
It's not work !

**Comment by RedSonja** [comment]
as of October 28th it does not work yet.
