### ISSUE TITLE
[3.3.5] OfferRewardText Locale Empty

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#21076]
**Description:**

OfferRewardText Locale Empty - check table - no values there

**Current behaviour:**

When we use locale client - we can't seelocale text on Reward Quests

**Expected behaviour:**

Use ruRU or deDE ckient. Login.Get any Quest, completeQuest and check Reward description - only english text.

**Steps to reproduce the problem:**

1. Check table quest_template_locale, OfferRewardText empty

**Branch(es):**

https://github.com/TrinityCore/TrinityCore/commit/fbb2b1650fb4239c00712e4b1475873f9c30c338
Last TC 3.3.5 build

**TC rev. hash/commit:** 

 TrinityCore rev.Last build

**TDB version:**  Last TDB

**Operating system:** Win 8.1

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17680
