### ISSUE TITLE
The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21070]
**Description:**
http://www.wowhead.com/quest=10901/the-cudgel-of-kardesh
http://www.wowhead.com/quest=13431/the-cudgel-of-kardesh

This quest is part of the quest chain to earn the [Champion of the Naaru](http://www.wowhead.com/achievement=432/champion-of-the-naaru) title and the attunement to Serpentshrine Caverns. The title was only achievable, and attunement was only required, prior to wotlk transition patch 3.0.2.

**Current behaviour:**
Skar'this the Heretic offers both versions of this quest.

**Expected behaviour:**
[This version of the quest](http://www.wowhead.com/quest=10901/the-cudgel-of-kardesh) is not obtainable by players in this patch. It is only completable by players who had it in their quest logs **prior** to patch 3.0.2 and will count towards credit for the title and achievement.

[This version of the quest](http://www.wowhead.com/quest=13431/the-cudgel-of-kardesh) is only available to players **after** patch 3.0.2. It has the same objectives and allows you to finish the quest chain but will not count towards credit for the title or achievement.

Both versions of the quest require the completion of [The Mark of Vashj](http://www.wowhead.com/quest=10900/the-mark-of-vashj) (as noted in issue #21069) and requires the player to be level 70 -- not less than or greater than 70.

If you already have quest version 10901 in your quest log, 13431 should not be available to you unless you decided for whatever reason to abandon 10901.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 906a1331b008

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
> If you already have quest version 10901 in your quest log, 13431 should not be available to you unless you decided for whatever reason to abandon 10901.

In our reality we can just disable this quest?

**Comment by jerbookins** [comment]
I mean, this isn't really a blizzlike solution, this is just removing the quest from the game even though *technically* the quest is still in the game. From the perspective of being in patch 3.3.5, I understand the solution, but I don't agree with it.

**Comment by tkrokli** [comment]
Very well, you still can. You just need to enable it again by removing that code from `disables` .

**Comment by Aokromes** [comment]
The solution is correct, it's removed from questgiver, but available with commands or old characters.

**Comment by Killyana** [comment]
Removing the quest from the quest giver is the blizzlike solution, it will allow old chars that takes the quest during TBC to completed.
