### ISSUE TITLE
[3.3.5] Stealth + Absorb vs Channeled spells

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21074]
**Description:** Channeled spells like Blizzard, should remove Stealth even if some absorb is active

**Current behaviour:** Stealth is removed only after absorb fades

**Expected behaviour:** Rogue lose stealth when hitted by blizzard, even if has some absorb effect active

**Steps to reproduce the problem:**

1. Put a rogue in duel with a Mage
2. Cast stealth with rogue, add some absorb effect (like power word shield)
3. Cast Blizzard on rogue location

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 484c681e43057baf65079291d0e886b454dce7b8

Has some info about it here: http://www.arenajunkies.com/topic/163617-power-word-shield-and-stealth/

**Comment by Jildor** [comment]
Seems should be only with AoE channeled

**Comment by Nertx** [comment]
Not only channeled but AOE spells like Holy Nova, Frost Nova, Shadowfury etc don't put the target out of stealth also.
Ground spells with a duration like DnD and Consecration is supposed to remove stealth only if it hits the target on cast.

Some videos:
https://youtu.be/EwLOcI4h_kg?t=530 (Holy Nova)
https://youtu.be/MKxGDeyMbGc?t=700 (Arcane Explosion)

**Comment by Noryad** [comment]
i think @ariel- worked on that some time ago, but now it's broken, i can confirm it too

**Comment by Noryad** [comment]
this can be useful
https://eu.battle.net/forums/en/wow/topic/5168867416

**Comment by Nertx** [comment]
I think the information from wowwiki and gamepedia is risky to consider, because anyone can edit them without being sure if it's really how it should work. Video fragments like the ones you mentioned is a lot safer imo.

**Comment by Noryad** [comment]
good point

**Comment by ariel-** [comment]
> I think the information from wowwiki and gamepedia is risky to consider, because anyone can edit them without being sure if it's really how it should work. Video fragments like the ones you mentioned is a lot safer imo.

Being wikis you can always see the change history and go back to an old revision of the text

**Comment by Langerz82** [comment]
Something like this?

Patch:
https://gist.github.com/Langerz82/6f761a226810f23c7d3c78ba6de0289c

**Comment by Langerz82** [comment]
Does this work? I tested it in pvp when the player took damage only he was put out of stealth.

Patch:
https://gist.github.com/Langerz82/352015142089588b4cf2dbf634d74b73

**Comment by Keader** [comment]
@Langerz82
It break more.
Now spell not even hit rogue

**Comment by Langerz82** [comment]
ty for test, give me some time I'll fix it later today. :]

**Comment by ariel-** [comment]
Can you please apply #21260 and report back?

**Comment by Keader** [comment]
sure
doing it now.

**Comment by Keader** [comment]
Nope ariel, bug persist using #21260

**Comment by Keader** [comment]
Not possible reproduce it anymore (b978b673a9053bb0d7bd63ed9261117dc7845742)
