### ISSUE TITLE
Quest Objects missing from Heroic Shadow Labyrinth

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21087]
**Description:**
www.wowhead.com/quest=10091/the-soul-devices
http://www.wowhead.com/quest=10094/the-codex-of-blood

**Current behaviour:**
There are no Soul Device objects in Heroic Shadow Labyrinth

**Expected behaviour:**
Screenshots of Game Objects missing from Heroic that are available on Normal difficulty:

Soul Devices

![wowscrnshot_121917_005100](https://user-images.githubusercontent.com/16745918/34146436-4160d054-e457-11e7-8d06-db8cf1350f95.jpg)

Codex of Blood

![wowscrnshot_121917_014041](https://user-images.githubusercontent.com/16745918/34148211-aec5cca2-e45d-11e7-86b8-1e40ee7ea07f.jpg)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** b9b667f9253c

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
#21082
It's a generic issue.
