### ISSUE TITLE
DB/Quest: Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by OlegVintage88** [TrinityCore/TrinityCore#21084]
**Description:**
Quest http://www.wowhead.com/quest=10144/disrupt-their-reinforcements
- http://www.wowhead.com/item=28106/kingstons-primers
- http://www.wowhead.com/spell=34387/detonating-rune-stones
- http://www.wowhead.com/object=184414/portal-grimh
- http://www.wowhead.com/object=184415/portal-kaalez

After activation nothing happens, says you need to choose a goal.

**Expected behaviour:**

https://www.youtube.com/watch?v=xfK-UzxZiRE

**Steps to reproduce the problem:**

1. `.quest add 10144`
2. Collect stones with the runes of demons, approach the portal.
    Use Kingston's Primer inside Portal Grimh and Portal Kaalez.
3. Error message: You need to choose a goal

**Branch(es):**  3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b9b667f9253c 2017-12-17 20:22:34 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63

**Operating system:** Win 7 x64

**Comment by Killyana** [comment]
@joschiwald can you take a look to this, it looks related to https://github.com/TrinityCore/TrinityCore/commit/842a65ac15443ea464d85b25afb5ffd6742b1f62

**Comment by Killyana** [comment]
The spell has : 5 yards (Interact Range) but the interact distance with the gob is larger because the known issue, so if you use the item with a range>5 it will throw "you don't have a target" it must be "you're far away".
This is the correct conditions: (I'm not sure if the effect1 on gobs is required.
``` sql
DELETE FROM conditions WHERE SourceTypeOrReferenceId=13 AND SourceEntry=34387;
INSERT INTO conditions (SourceTypeOrReferenceId, SourceGroup, SourceEntry, SourceId, ElseGroup, ConditionTypeOrReference, ConditionTarget, ConditionValue1, ConditionValue2, ConditionValue3, NegativeCondition, ErrorType, ErrorTextId) VALUES
(13, 1, 34387, 0, 0, 31, 0, 5, 184289, 0, 0, 0, 0),
(13, 1, 34387, 0, 1, 31, 0, 5, 184290, 0, 0, 0, 0),
(13, 1, 34387, 0, 2, 31, 0, 5, 184414, 0, 0, 0, 0),
(13, 1, 34387, 0, 3, 31, 0, 5, 184415, 0, 0, 0, 0),
(13, 2, 34387, 0, 0, 31, 0, 3, 19717, 0, 0, 0, 0),
(13, 2, 34387, 0, 1, 31, 0, 3, 19652, 0, 0, 0, 0);

**Comment by TecDian** [comment]
The same goes for the corresponding horde quest of course.

http://www.wowhead.com/quest=10208/disrupt-their-reinforcements

So is there any progress on this matter?

**Comment by Killyana** [comment]
It will be fixed by https://github.com/TrinityCore/TrinityCore/issues/15453

**Comment by DanVS** [comment]
Not working (both 10144 and 10208) on rev 89fc4cbb7288.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15453

**Comment by illfated** [comment]
Yes, the main point of the issue https://github.com/TrinityCore/TrinityCore/issues/15453 is that there are some gameobjects you can't reach unless you move inside the outer physical object by using any kind of glitch or cheat. Some very few objects are not approachable at all. Other interaction gameobjects inside a large outer gameobject are just very hard to reach, you have to work hard to find the right spot to reach them.
