### ISSUE TITLE
Greater Blessings not working

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21081]
**Description:**
This is a new behavior since yesterday.

**Current behaviour:**
Casting any Greater Blessing spell as a Paladin does not put a buff on the player. For instance, casting Blessing of Sanctuary (20911) puts a buff on my paladin. Casting Greater Blessing of Sanctuary does not but it does consume a Symbol of Kings reagent.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** b9b667f9253c

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by ariel-** [comment]
Cannot reproduce on 00c0ec3f2784e67f4ccc7616bf65aa7e5496687a

**Comment by jerbookins** [comment]
I'm still on b9b667f9253c and it's working correctly all of a sudden. I don't know what could have changed.

**Comment by tkrokli** [comment]
Maybe it was a Cache issue - we may never know for sure.

**Comment by jerbookins** [comment]
I just ran into this issue again. It seems to be intermittent but I don't know what is causing it. Neither logging out or exiting the game fixes it.

**Comment by jerbookins** [comment]
I just ran into this issue again. It seems to be intermittent but I don't know what is causing it. Neither logging out or exiting the game fixes it. 7cc074f2a48d

**Comment by tkrokli** [comment]
Just to be sure that this is not an issue with your game client: Did you check this without any game addons loaded during testing? (some addons have a bad tendency to affect the UI negatively or stop working until UI is reloaded)

**Comment by jerbookins** [comment]
Yes

**Comment by tkrokli** [comment]
Very well. We will need more users to confirm this by reproducing the issue based on your findings.

**Comment by Keader** [comment]
working in rev 465b43fabef1727432ddda27f04b882b29fd2c7f
Please test in a clean core before report stuffs.

**Comment by jerbookins** [comment]
@Keader What exactly is that supposed to mean?

**Comment by Keader** [comment]
Reproduce steps missing, we cant know if bug is real.
Next, please put more detailed stuff possible.
I can reproduce your issue, is not working if you are inside of dungeons/raid or um Raid Group.

**Comment by jerbookins** [comment]
I can't possibly explain how to reproduce this issue. That's why I have done so much explaining of things that I have tried to do to reproduce the issue.

**Comment by jerbookins** [comment]
I just updated to 465b43fabef1, logged in with the paladin (still inside Arcatraz), and could not cast any Greater Blessing. I then teleported to the entrance and was able to cast, and now that I am inside I can continue to cast.

**Comment by ariel-** [comment]
Managed to repro with a combination of steps:
- Add paladin and another player to a group
- Convert group to raid group
- Enter The Arcatraz with the paladin
- Logout paladin inside instance and log back in
- Greater Blessing not working

Culprit commit: 95456ab5d8bd623481d315ae55dfbb44b45ba9f5 (Spell::CheckEffectTarget returned false because of Object::IsWithinLOS returning false, player is not in LOS with itself)

Tagging @Golrag here

**Comment by Golrag** [comment]
Can't reproduce with https://github.com/TrinityCore/TrinityCore/pull/21125 but I'm not sure if I followed the steps correctly tho.

**Comment by jerbookins** [comment]
You don't really need to be in a group. I have plenty of trouble with solo play.

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/e42903ec16f4849b71bc8736e3151a1e11d3cd25
