### ISSUE TITLE
Spawns missing on some BC instances on heroic mode

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21082]
**Description:**
www.wowhead.com/quest=10097/brother-against-brother
www.wowhead.com/npc=18956/lakka

**Current behaviour:**
Neither Lakka nor his cage appear in the room next to Darkweaver Syth in Sethekk Halls

**Expected behaviour:**
Lakka should be locked in a cage in the room next to Darkweaver Syth

**Branch(es):** 3.3.5

**TC rev. hash/commit:** b9b667f9253c

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
https://i.imgur.com/u6uyrSU.png

**Comment by offl** [comment]
Try now:
```sql
--
UPDATE `creature` SET `spawnMask`=3 WHERE `id`=18956;
UPDATE `gameobject` SET `spawnMask`=3 WHERE `id`=183051;
UPDATE `smart_scripts` SET `event_flags`=7 WHERE `entryorguid` IN (18956) AND `source_type`=0;
UPDATE `smart_scripts` SET `event_flags`=7 WHERE `entryorguid` IN (1895600) AND `source_type`=9;
```

**Comment by Aokromes** [comment]
http://wowwiki.wikia.com/wiki/Quest:Brother_Against_Brother it must be on normal mode too, also it's there.

**Comment by jerbookins** [comment]
Heroic:
![wowscrnshot_121817_115201](https://user-images.githubusercontent.com/16745918/34122565-256e044c-e3ea-11e7-9bde-ce9d4eeff5e2.jpg)

Normal:
![wowscrnshot_121817_115218](https://user-images.githubusercontent.com/16745918/34122568-27cdb9b2-e3ea-11e7-8547-033386980b77.jpg)

@Aokromes You mean he isn't supposed to appear in Heroic mode?

**Comment by tkrokli** [comment]
http://wowwiki.wikia.com/wiki/Quest:Brother_Against_Brother
>wowwiki.wikia.com is currently unable to handle this request.
HTTP ERROR 500

Use https://wow.gamepedia.com/Quest:Brother_Against_Brother_(Sethekk_Halls) instead if you get this error.

**Comment by offl** [comment]
Please change the title to "Ore, herb, quest objects and quest NPCs are spawned only on normal mode".

**Comment by Jildor** [comment]
Related with dynamic spawn??

**Comment by Aokromes** [comment]
No, very likely ancient like hell spawns.

**Comment by Jildor** [comment]
Ah, ok

**Comment by Aokromes** [comment]
Generic fix for most of instances, test if it adds startup errors:

```sql
--
UPDATE `creature` SET `spawnMask`=3 WHERE `id`=18956;
UPDATE `smart_scripts` SET `event_flags`=7 WHERE `entryorguid` IN (18956) AND `source_type`=0;
UPDATE `smart_scripts` SET `event_flags`=7 WHERE `entryorguid` IN (1895600) AND `source_type`=9;
UPDATE `gameobject` SET `spawnMask` = 3 WHERE `spawnMask` = 1 AND `id` IN (181278,181556,181557,181569,183051,182940,186633,185434,181275,184931,181276,181270,184956) AND `map` NOT IN (530,571);

**Comment by jerbookins** [comment]
![wowscrnshot_122117_014110](https://user-images.githubusercontent.com/16745918/34247573-39b69b14-e5f0-11e7-97b6-0d7086e1a790.jpg)

Codex of blood still missing from Shadow Lab

**Comment by jerbookins** [comment]
Soul Devices don't disappear after they have been looted

**Comment by tkrokli** [comment]
You may want to open a new issue ticket for that.
Issue different than the original one needs new ticket.
Only directly related problems should be reported on the same issue page.

**Comment by Aokromes** [comment]
and supply ids, it saves a lot of time.

**Comment by offl** [comment]
```sql
--
UPDATE `gameobject` SET `spawnMask` = 3 WHERE `id` = 182947;
```

**Comment by tkrokli** [comment]
@offl : I am guessing you have tested it too? :-)

**Comment by offl** [comment]
No

**Comment by offl** [comment]
Push it, there's nothing to test
