### ISSUE TITLE
MS Visual Studio 2017 strange messages

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#21083]
I don't know is this issue relevant or not?
If i compile the latest source with VS 2017 i becoms on the compiler strange messages
"Unknown compiler version"

I use Cmake 3.10.1 and Boost 1,64.0

TrinityCore rev. 143b2aeac063 2017-12-18 08:39:35 -0300 (335a branch)

**Comment by Shauren** [comment]
These come from boost (try 1.65). Not our problem and safe to ignore

**Comment by Aokromes** [comment]
Not tc issue, instead boost, update your boost to 1.65.1 minimum, if you still have those warnings boost needs to be updated.

**Comment by Tauriella** [comment]
Nice for the TC BOOST Support 👍 
I will try

**Comment by Aokromes** [comment]
https://github.com/boostorg/config/commit/f6296c049516c065df895f28eef442bdced4e8c1

```code
[00:57:04] <Aokromes> try go on command line to where you have cl.exe under visual studio directory and run cl /?
[01:02:11] <Kilyana> C/C++ version 19.12.25831
[01:02:32] <Aokromes> :)
[01:02:38] <Aokromes> you are farr updated lol
[01:04:32] <Kilyana> I installed VS this night so it's the last version
[01:04:35] <Aokromes> yeah
[01:05:04] <Aokromes> i wonder how to obtain _MSC_VER

**Comment by Aussiewoolf** [comment]
I found the same error coming up, it started after i updated to VS2017 Version 15.5.2 5 days ago and it  didn't happen with previous version, and boost is at 1_65_1_1 . i had no problems in compiling the core, just annoying warning message's.

**Comment by Tauriella** [comment]
The same result with Boost 1_65_1

**Comment by tkrokli** [comment]
We need to wait for the release version of Boost 1.66.0 to see if they have added support for the current VS2017 version. Boost 1.65.1 supported VS2017 up to version 15.3 or 15.4 (I don't remember exactly when the "Unknown compiler version" issue started appearing again. I just remember that I had to upgrade from 1.63.0 to 1.65.1 last time this happened some months ago).

**Comment by Aokromes** [comment]
nope, not even 1.66 will remove those warnings, 1.66 only supports up to:
last known and checked version is 19.12.25830.2 (VC++ 2017.3):
#if (_MSC_VER > 1912)

and latest is 19.12.25831 who knowns _MSC_VER

**Comment by tkrokli** [comment]
Not a good idea to use Boost 1.66.0 together with VS2017 (19.12.25831), it fails to compile the source.
- https://gist.github.com/tkrokli/5925332f349b9961eef225b50b6e9195#file-output-build-txt
