### ISSUE TITLE
Cabal Spellbinder

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21095]
**Description:**
http://www.wowhead.com/npc=18639/cabal-spellbinder

**Current behaviour:**
Cabal Spellbinder in Shadow Lab casts one Shadow Bolt and then stands there and doesn't do anything else. I have noticed this behavior with other caster NPCs so I don't know if it's an issue with the individual NPC or a common issue among many.

Something else I've noticed is silencing a caster does not force them to move toward you in an effort to use a melee attack like on live wow.

![wowscrnshot_122117_025051](https://user-images.githubusercontent.com/16745918/34250330-c7f60d66-e5f9-11e7-9803-805be1daae98.jpg)

**Expected behaviour:**
The NPC should be relying on any spells it has available, and if it is OOM or silenced, it should behave like a melee class NPC.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7cc074f2a48d

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
#9512 or something like this.

**Comment by tkrokli** [comment]
Very likely the old SAI issue with `SMART_ACTION_ALLOW_COMBAT_MOVEMENT` (in combat it doesn't work properly) as offl suggests.
