### ISSUE TITLE
DB/Creature: Udalo

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21109]
**Description:**
http://www.wowhead.com/npc=21962/udalo

**Current behaviour:**
Udalo's corpse is laying in this magic teleporter looking thing.

![wowscrnshot_122317_024941](https://user-images.githubusercontent.com/16745918/34318694-fd903422-e78b-11e7-9bf3-ca7c4f11d47c.jpg)

**Expected behaviour:**
Udalo's corpse should be off to the right side on the ramp up.

https://youtu.be/ZuJZi5pkhYo?t=1339

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7cc074f2a48d

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Serpaa** [comment]
Suggested Fix:

```sql
-- Update spawnpoint of Udalo
UPDATE `creature` SET `position_x`=469.25, `position_y`=12.05, `position_z`=49.299, `orientation`=1.5708 WHERE `guid`=10997;
```
