### ISSUE TITLE
DB/Spawns: missing creatures in Arcatraz

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21108]
**Description:**
http://www.wowhead.com/the-arcatraz

**Current behaviour:**
![wowscrnshot_122317_015357](https://user-images.githubusercontent.com/16745918/34318416-4a5aed22-e784-11e7-986e-b855c3aaac15.jpg)

**Expected behaviour:**
There should be a Protean Nightmare sitting next to the lonely Protean Horror on the ledge. And there should be a group of 5 Protean Horrors that patrol in a circle, up and around the ledge.

https://www.youtube.com/watch?v=ZuJZi5pkhYo (live wow)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7cc074f2a48d

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by dr-j** [comment]
about the protean nightmares/horrors in second room should continously spawn and move to door leading to first room and then attack the arcatraz warders/defenders but seem to get killed easily by the warders/defenders, these stop spawning once players have killed all the warders at the start but it is quiet common even on retail for players to just skip the warders zerg there way through the horrors but then if player dies and releases then most of the time player will wipe again and again trying to get back to rest of group.

This can be annoying on retail especially if you have no ability to leave combat or ressurect after dying.

I did script this but am not happy with waypoints/formations as if I remember did not spend that much time on this but still spent a while and got the event working just wp/formations are not entirely accurate
