### ISSUE TITLE
Core/Movement: Feared NPCs do not return to their home position

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#21106]
**Description:** Feared NPCs do not return to their home position.

After you cast spell id 33815 (AoE fear) on any NPC in a crowd, they do not return home after the last fear move.
They keep standing at the last fear waypoint.

**Expected behaviour:**

They should return home.

**Steps to reproduce the problem:**

1. `./cast self 33815` on an NPC in a crowd
2. watch the NPC until it gets released from Fear

**Branch(es):** Both

**TC rev. hash/commit:**  b08280fcfee500acf8b951ec2c05e0760d4b9955

**Comment by Langerz82** [comment]
I've tested on some Mobs and it works, but I don't know about players:

For patch see:
https://gist.github.com/Langerz82/72b0052a25df9ac9c7e9b0b2b05afa62

**Comment by Killyana** [comment]
Tested and works correctly.

**Comment by Shauren** [comment]
No, this is wrong. Why would you unconditionally tell npcs to run to their spawn point? They could be in combat

**Comment by Killyana** [comment]
Yes There's an issue with npcs in combat they returns to the spawn point and remain there instead of chasing their target back.

**Comment by Killyana** [comment]
This also happen if you Possess a friendly creature, example https://www.wowhead.com/npc=21909/arcano-scorp is Possess for a quest, even if it has random movements when the Possess  ends it will start doing random movement where the Possess ends and not at the home position.

**Comment by ccrs** [comment]
did possess and fear cause combat?

**Comment by Killyana** [comment]
No, combat in this cases

**Comment by Keader** [comment]
what happens in retail? If you just fear a creature?
It should back to home position, or start combat when fear fades?

**Comment by Jinnaix** [comment]
Actively casting fear on any Unit (no matter if player or creature or pet or whatsoever) sets you in combat. And when fear runs out, the former feared creature will attack you. As with all fear effects, fearing a creature can let the creature run into other mobs, getting you intro aggro with them too.

This case here and therefore the PR that i did is super specifc - you would only face it with special events/scripts or in situation where a player would die while a creature is being under his fear affect (this would drop combat anyway).

**Comment by Keader** [comment]
nice :)
