### ISSUE TITLE
Dungeon Minimap Icon

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21100]
**Current behaviour:**
The heroic mechanar dungeon mini-map icon displays a zero under the "heroic" skull in the dungeon flag.

![image](https://user-images.githubusercontent.com/16745918/34296871-08c6c082-e6d2-11e7-9411-fe94b8809f8f.png)

**Expected behaviour:**
The mini-map icon should show the number of people allowed in the instance at the selected difficulty. This seems to work correctly for raids, but entering a 10 or 25 heroic doesn't have the skull in the flag. I don't remember if it is supposed to.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7cc074f2a48d

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by jerbookins** [comment]
This seems to be isolated to specific instances. The dungeon player count is 5 while I'm in Arcatraz.

Mechanar specifically says "0" in the flag. I don't know about others yet.

**Comment by Aokromes** [comment]
botanica is also afected by this bug.

**Comment by Aokromes** [comment]
client bug, cannot be fixed.
