### ISSUE TITLE
Visual Studio: Broken single file build after recent Cotire changes

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#21104]
**Description:**

Building a single .cpp file in Visual Studio 2017 after a Clean Solution results in a build error
>1>------ Build started: Project: game, Configuration: Debug x64 ------
1>CreatureAI.cpp
1>c1xx : fatal error C1083: Cannot open compiler intermediate file: 'D:\wow\TrinityCore\win\src\server\game\Debug\cotire\game_CXX_prefix.pch': No such file or directory
1>Done building project "game.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Steps to reproduce the problem:**

1. Clean Solution in VS 2017
2. Open a .cpp file, i.e. CreatureAI.cpp
3. Choose Build > Compile or press Ctrl + F7

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

85e460802d0867634003768d7b8be356d236aba3

**Operating system:** Windows 10 x64

**Comment by Naios** [comment]
@jackpoz Did you try to create a new build directory since cotire was introduced?
I can't reproduce this issue.

The only issue which I know about that affects TC slightly is the following one: sakra/cotire#125

**Comment by jackpoz** [comment]
deleted the build folder, re-did cmake Configure and Generatre, opened in VS, opened CreatureAI.cpp, still same error
>1>------ Build started: Project: game, Configuration: Debug x64 ------
1>CreatureAI.cpp
1>c1xx : fatal error C1083: Cannot open compiler intermediate file: 'D:\wow\TrinityCore\win\src\server\game\Debug\cotire\game_CXX_prefix.pch': No such file or directory
1>Done building project "game.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jackpoz** [comment]
Could it be CreatureAI.cpp is the cpp that is supposed to create the pch and somehow it bugs out ?

**Comment by Shauren** [comment]
It actually is that cpp

**Comment by jackpoz** [comment]
Clean all

>1>------ Skipped Clean: Project: clean_cotire, Configuration: Debug x64 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Clean: Project: INSTALL, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Clean started: Project: ALL_BUILD, Configuration: Debug x64 ------
4>------ Clean started: Project: worldserver, Configuration: Debug x64 ------
5>------ Clean started: Project: authserver, Configuration: Debug x64 ------
6>------ Clean started: Project: Recast, Configuration: Debug x64 ------
7>------ Clean started: Project: scripts, Configuration: Debug x64 ------
8>------ Clean started: Project: gsoap, Configuration: Debug x64 ------
9>------ Clean started: Project: game, Configuration: Debug x64 ------
10>------ Clean started: Project: shared, Configuration: Debug x64 ------
11>------ Clean started: Project: database, Configuration: Debug x64 ------
12>------ Clean started: Project: common, Configuration: Debug x64 ------
13>------ Clean started: Project: revision_data.h, Configuration: Debug x64 ------
14>------ Clean started: Project: g3dlib, Configuration: Debug x64 ------
15>------ Clean started: Project: fmt, Configuration: Debug x64 ------
16>------ Clean started: Project: Detour, Configuration: Debug x64 ------
17>------ Clean started: Project: zlib, Configuration: Debug x64 ------
18>------ Clean started: Project: ZERO_CHECK, Configuration: Debug x64 ------
========== Clean: 16 succeeded, 0 failed, 2 skipped ==========

Try to compile only CalendarMgr.cpp

>1>------ Build started: Project: game, Configuration: Debug x64 ------
1>CreatureAI.cpp
1>D:\wow\TrinityCore\src\server\game\AI\CreatureAI.cpp : fatal error C1083: Cannot open include file: 'D:\wow\TrinityCore\win\src\server\game\Debug\cotire\game_CXX_prefix.hxx': No such file or directory
1>Done building project "game.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Shauren** [comment]
I can confirm this issue btw
Its probably caused by the way cotire sets PCH flags, instead of doing it on entire project, it marks each source individually with /Yu

**Comment by jackpoz** [comment]
@Naios any news about this ?

**Comment by Naios** [comment]
I took a look into the cotire source, however it isn't obvious what's going on inside the library.

The actual question is whether we wan't to proceed with cotire or revert our old PCH implementation back and add the capability of transitive flag inheritance to it (which was the reason for switching).

**Comment by jackpoz** [comment]
@Naios could you open an issue on Cotire about this particular Visual Studio "build single file should trigger pch" feature ?

**Comment by Naios** [comment]
Isn't this isdue reported already through sakra/cotire#125 ?

**Comment by jackpoz** [comment]
No, that's about "editing the random cpp chosen by cotire triggers a full rebuild", it's a different issue

**Comment by Shauren** [comment]
What exactly was that transitive flag stuff that our old pch thing was missing?

**Comment by Naios** [comment]
flags, features and definitions inherited by linked projects weren't applied when compiling the precompiled header which lead to errors and a header that didn't match the projects configuration.

**Comment by Shauren** [comment]
Well, it actually worked before all these changes, compile time was faster with pch

**Comment by Naios** [comment]
Mh from my point of view the current development of cotire is suspended.
There are some unmerged PR's in the cotire repository which also could fix possible issues we will encounter.

For me there are two alternatives as described above:
- **Fix cotire**
  - Fork the repo
  - Apply the outstanding PR's
  - Fix #21104
  - Fix #21118
  - PR everything back
- **Fix our old implementation**
  - We won't get any upstream changes from cotire
  - Fix transitive usage of flags, definition and features in our old implementation

I prefer the first one, however it will take some time to adapt cotire to use our MSVC pch implementation

**Comment by jackpoz** [comment]
@Naios is cotire any less dead than it was 1 year ago ?

**Comment by Naios** [comment]
Sadly yes, seems like the author abadoned it, especially because there are a lot of stale PR's.
So, how shall we continue about this?
I already looked into the source code but this issue isn't easy to fix.

**Comment by jackpoz** [comment]
maybe we should take a step back and consider if we should keep cotire in the current dead state or start lokking for something else (maybe there's an active fork somewhere ?)

**Comment by Naios** [comment]
Currnently we're maintaining our own fork at TrinityCore/cotire where I merged some PR's of the main repo, however this is a dead end since we would put too much effort into this.
I'm not aware of any fork or alternative to cotire (except of our ancient PCH implementation),
are you?

**Comment by jackpoz** [comment]
I opened an issue on the cotire repo to get some answers too, let's see who replies.

**Comment by Naios** [comment]
Ref sakra/cotire#169

**Comment by jackpoz** [comment]
I didn't want to ref the issue but ok

**Comment by jackpoz** [comment]
We will never get this feature back

**Comment by Shauren** [comment]
I'll fix it one day, after it pisses me off too much

**Comment by jackpoz** [comment]
Fixed by dropping that broken piece of software that some people refer to as "Cotire"
