### ISSUE TITLE
DB/Creature: extra creatures in Arcatraz

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21103]
**Description:**
http://www.wowhead.com/npc=20880/eredar-deathbringer
http://www.wowhead.com/npc=20883/spiteful-temptress
http://www.wowhead.com/npc=20881/unbound-devastator

Updated: 2018/1/2 6:21pm

**Current behaviour:**
There is an additional Eredar Deathbringer that should be removed (213224).

![wowscrnshot_122217_054843](https://user-images.githubusercontent.com/16745918/34299523-ae2168ee-e6e0-11e7-97c3-3a24233e0f6f.jpg)

----

There is a Spiteful Temptress where there should be an Unbound Devestator (79542).

![wowscrnshot_122317_020829](https://user-images.githubusercontent.com/16745918/34318497-80269dd2-e786-11e7-89b4-3b0ba2b9a1a4.jpg)

----

There is an additional Spiteful Temptress where there should be a Skulking Witch that is standing in the wrong place, she should be to the right of the boxes (79553). She is currently close enough to pull the boss when she is agroed if the bosses have not moved back.

![wowscrnshot_122317_021305](https://user-images.githubusercontent.com/16745918/34318512-fb381884-e786-11e7-8a3f-9af3787b9395.jpg)

----

There's an extra Protean Horror hanging out on the bridge, he should be pathed to patrol the bridge down to the bottom of the ramp and back. (79484)

![wowscrnshot_122317_022154](https://user-images.githubusercontent.com/16745918/34318543-33af7a6c-e788-11e7-963f-29cf064565d5.jpg)

----

There's an extra Protean Horror on the upper level after Scryer and Dalliah that should path across the upper level all the way into and around the room with the Ethereum Slayers/Lifebenders and back (79459).

![wowscrnshot_122317_022739](https://user-images.githubusercontent.com/16745918/34318581-fab2ac74-e788-11e7-9fb3-1281193b8ad5.jpg)

----

**Expected behaviour:**
https://youtu.be/T9WMOSiQUYQ?t=118

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7cc074f2a48d

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Please provide the `guid` for that NPC to make it easier to select the wrong spawn.
```sql
SELECT * FROM `creature` WHERE `id`=20880;
```
```
  guid      id     map  zoneId  areaId  spawnMask  PhaseId  PhaseGroup  modelid  equipment_id  position_x  position_y  position_z  orientation  spawntimesecs  spawndist  currentwaypoint  curhealth  curmana  MovementType  npcflag  unit_flags  unit_flags2  unit_flags3  dynamicflags  ScriptName  VerifiedBuild
------  ------  ------  ------  ------  ---------  -------  ----------  -------  ------------  ----------  ----------  ----------  -----------  -------------  ---------  ---------------  ---------  -------  ------------  -------  ----------  -----------  -----------  ------------  ----------  -------------
213224   20880     552       0       0          6      169           0        0             0     305.736     148.059     24.8633      3.97935           7200          0                0          1        0             0        0           0            0            0             0                          0
213223   20880     552       0       0          6      169           0        0             0     301.797     127.444     22.3108        1.309           7200          0                0          1        0             0        0           0            0            0             0                          0
```

**Comment by jerbookins** [comment]
213224

**Comment by Faq** [comment]
Yeah looks like some bad patch got in.

**Comment by tkrokli** [comment]
I could at best remove the extra spawns that should not be there, but in the case of any NPCs to be replaced with another, I wonder if a sniff is needed to get the coordinates & orientation correct.

**Comment by offl** [comment]
> There is a Spiteful Temptress where there should be an Unbound Devestator (79542).

No, they should be pooled and not replaced.

**Comment by jerbookins** [comment]
If they're "pooled" does that mean they're supposed to be random?

**Comment by jerbookins** [comment]
>They should be pooled + no, she should be here.
https://youtu.be/ZuJZi5pkhYo?t=846

This shows the Skulking Witch on the opposite side of where she is in the room (036a05458eb9), which is also different from other videos I've seen so that probably means she's supposed to walk around.

**Comment by offl** [comment]
https://github.com/Looking4Group/L4G_Core/issues/1539 maybe can help.
> -- Delete Skulking Witches - They Are Summoned By Spiteful Temptress on Aggro

P.S. can't confirm this.

**Comment by jerbookins** [comment]
Well i just took video from live wow, https://streamable.com/qehwl

I think they definitely are not summoned by the Spiteful Temptress.

**Comment by AnonXS** [comment]
This comment is placed in the sources section, as i also was not able to confirm this sort of behavior at the time (now removed it), later i checked this with sniff and the Skulking Witches do not have a createdbyspell package.
[CCDB](https://github.com/ccshiro) seems to hold data on potential paths they might have.

**Comment by offl** [comment]
Can't believe they opened their sources
