### ISSUE TITLE
Strange gossip menu that appears on all NPCs

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#21105]
**Description:**

Almost all NPCs when spoken to show this gossip..

**Current behaviour:**

when talking to a NPC like a shouting guard this last shows a gossip related to Uldum

**Expected behaviour:**

We should not see any gossip

**Steps to reproduce the problem:**

1. clone trinitycore latest build
2. install latest clean database
3. start worldserver and go to speak with any NPCs

**Branch(es):**

master

**TC rev. hash/commit:** 

18ab645

**TDB version:**  TDB 720.00

**Operating system:** Unix
![wowscrnshot_122217_232456](https://user-images.githubusercontent.com/821614/34314068-7b835ae2-e770-11e7-8c4a-cee4653b802c.jpg)

**Comment by Killyana** [comment]
Someone can confirm this issue, it looks weird.

**Comment by Ovahlord** [comment]
I remember this was the same issue that I was complaining about on 434 ealier. There was an sql fix for that.

**Comment by Pixel-Pirate** [comment]
this sql fix is not working. This gossip appear on many NPCs and as I said in description,I did not do anything more than install a blank database and compile the latest version of tc. No more no less.

**Comment by Ovahlord** [comment]
make sure you cleared you cache before checking for results. I had also to clear my cache back then.

**Comment by Pixel-Pirate** [comment]
ofc I had delete my cache folder and problem is still here

**Comment by Pixel-Pirate** [comment]
Any solution about this issue ? I have male fresh install again with clean database and the problem is still here. I do not understand..

**Comment by Rochet2** [comment]
I tested this on db9576beffda3a55006b09c81e8050ffe14958ac and 4435cb82d0e0575bf7bf3cd5308967383f70ae00
All clean installation. The game build was 24461 for both though.

No sight of such gossip menu when talking to guards in stormwind. (talked to every NPC from main square to the gates)

Seems you have some locales, where do those come from? My gossip_menu_option_locale is empty. Dont think they come from the client DBC, right?

Maybe you should try debug and set a breakpoint at PlayerMenu::SendGossipMenu for example, so you can see from the callstack and variables where the gossip originates from.
Or maybe search the gossip from DB and see what could be wrong.

**Comment by Aszune** [comment]
I have fresh compiled install with the latest commit, I tried with DBC "enUS" and "esES" locale. I can't reproduce this issue in any case.

**Comment by Pixel-Pirate** [comment]
Thank for your answers guys, so maybe it's a problem with my dbc I am running on 7.2.5.24742 version ofc ? I do not see any other explanation
