### ISSUE TITLE
spell Penance benefits from Borrowed Time without Consume buff

### ISSUE THREAD

**Issue by IngMak** [TrinityCore/TrinityCore#21112]
**Description:**

penance spell benefict from borrowed time without consume buff, this allow to cast greater heal with speed bonus

**Current behaviour:**

penance spell not consume borrowed time buff

**Expected behaviour:**

penance cant benefict from borrowed time because is channeling spell  (taking care some videos from blizzcon ) or consume it.

**Steps to reproduce the problem:**

1. get character level enough to get borrowed time and penance from Discipline talent tree 
2. cast Power word: shield (triggering borrowed time)
3. cast penance (notice borrowed time is not consume ) and cast greater heal (look casting speed benefict from borrowed time too)

**Branch(es): 3.3.5

**TC rev. hash/commit: d3d003d

**TDB version:**   	TDB 335.63 + updates

**Operating system:** Ubuntu 17.04, Windows 10

**Comment by tkrokli** [comment]
Some links to documentation or information pages would be nice. Examples:
- https://wow.gamepedia.com/Penance
- https://wow.gamepedia.com/Borrowed_Time_(priest_ability)

**Comment by Keader** [comment]
proc system can handle with it if i remember right
but we need some prof of it

**Comment by Keader** [comment]
From spellwork:

<details>

```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 25
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 65 (SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK), value = 25, misc = 14 (14), miscB = 0, periodic = 0
SpellClassMask = 00001800 00000004 00000000
	+ 2060 - Greater Heal (Rank 1)
	+ 2061 - Flash Heal (Rank 1)
	+ 9472 - Flash Heal (Rank 2)
	+ 9473 - Flash Heal (Rank 3)
	+ 9474 - Flash Heal (Rank 4)
	+ 10915 - Flash Heal (Rank 5)
	+ 10916 - Flash Heal (Rank 6)
	+ 10917 - Flash Heal (Rank 7)
	+ 10963 - Greater Heal (Rank 2)
	+ 10964 - Greater Heal (Rank 3)
	+ 10965 - Greater Heal (Rank 4)
	- 15068 - TEST Heal Self
	- 17137 - Flash Heal
	- 17138 - Flash Heal
	- 17843 - Flash Heal
	+ 25210 - Greater Heal (Rank 6)
	+ 25213 - Greater Heal (Rank 7)
	+ 25233 - Flash Heal (Rank 8)
	+ 25235 - Flash Heal (Rank 9)
	+ 25314 - Greater Heal (Rank 5)
	+ 25314 - Greater Heal (Rank 5)
	- 26565 - Heal Brethren
	- 27608 - Flash Heal (Rank 7)
	- 29564 - Greater Heal
	+ 32546 - Binding Heal (Rank 1)
	- 33641 - Flash of Light
	- 34176 - QA Heal Coefficient 1 (QASpell)
	- 35096 - Greater Heal
	- 38580 - Greater Heal
	- 38588 - Flash Heal
	- 39321 - Heal Self
	- 41378 - Greater Heal
	- 42420 - Flash Heal
	- 43431 - Flash Heal
	- 43516 - Flash Heal
	- 43575 - Flash Heal
	+ 47536 - Rapture (Rank 2)
	+ 48062 - Greater Heal (Rank 8)
	+ 48063 - Greater Heal (Rank 9)
	+ 48070 - Flash Heal (Rank 10)
	+ 48071 - Flash Heal (Rank 11)
	+ 48119 - Binding Heal (Rank 2)
	+ 48120 - Binding Heal (Rank 3)
	- 49348 - Greater Heal
	- 56331 - Flash Heal
	- 56919 - Flash Heal
	- 57766 - Flash of Light
	- 57775 - Greater Heal
	- 59997 - Flash of Light
	- 60003 - Greater Heal
	- 61965 - Greater Heal
	- 62334 - Greater Heal
	- 62442 - Greater Heal
	- 62809 - Great Heal
	- 63760 - Greater Heal
	- 67254 - Blazing Light
	- 67291 - Blazing Light
	- 71930 - Flash of Light
	- 71931 - Greater Heal
	- 72484 - Debug Heal
```

</details>

I dont saw penance there

**Comment by Keader** [comment]
Yes, Penance not remove it
https://youtu.be/MKxGDeyMbGc?t=49s
