### ISSUE TITLE
PhaseShiftFlags 8 and 16

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21119]
**Description:**
PhaseShiftFlags 8 and 16 are not implemented.

**Current behaviour:**
Hardcoded value in MiscPackets.cpp `_worldPacket << uint32(PhaseShifts.size() ? 0 : 8);`.
Unphased creatures and gameobjects disappear when player has at least one active phase.

**Expected behaviour:**
During my long observations on Wandering Isle, i found out that PhaseShiftFlag 8 could be "see unphased creatures" and PhaseShiftFlag 16 "see unphased gameobjects". There is no common phase in the zone (now I use a common phase for creatures and GOs in this PR #17021, but it is wrong).

In below quests (there are more than these I mention here) and related SMSG_PHASE_SHIFT_CHANGE packets, player doesn't have PhaseShiftFlag 8 and he does NOT see generic creatures (which I think should be unphased). In all other phases on Wandering Isle (and also in Durotar after completing Wandering Isle), player has PhaseShiftFlag 8 and 16.

[The Way of the Tushui](http://www.wowhead.com/quest=29414/the-way-of-the-tushui) - during this quest you have phase 838 and you can't see for example [Amberleaf Scamp](http://www.wowhead.com/npc=54130/amberleaf-scamp), [Corsac Fox](http://www.wowhead.com/npc=53704/corsac-fox), ...
Since phase 838 has PhaseShiftFlags 16 you should be able to see unphased GOs, like [The Dimming Flame](http://www.wowhead.com/object=209364/the-dimming-flame) and Scroll Post (entry: 209363) - the objects that Aysa sits before.
```
ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C) Length: 41 ConnIdx: 1 Time: 01/22/2016 19:26:31.578 Number: 38923
PhaseShiftFlags: 16
PhaseShiftCount: 2
PersonalGUID: Full: 0x0
[0] PhaseFlags: 0
[0] Id: 838
[1] PhaseFlags: 1
[1] Id: 1323
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 2
[0] VisibleMapID: 683 (683)
```
[Battle for the Skies](http://www.wowhead.com/quest=29786/battle-for-the-skies) - during this quest (when taken) you have pahse 524 and when you complete or reward it you have phases 536 and 1526. You also can't see any generic creatures in the area. For example [Fe-Feng Wiseman](http://www.wowhead.com/npc=55601/fe-feng-wiseman)
```
ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C) Length: 41 ConnIdx: 1 Time: 01/22/2016 21:26:41.726 Number: 139150
PhaseShiftFlags: 16
PhaseShiftCount: 2
PersonalGUID: Full: 0x0
[0] PhaseFlags: 0
[0] Id: 524
[1] PhaseFlags: 1
[1] Id: 1326
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 2
[0] VisibleMapID: 683 (683)

ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C) Length: 45 ConnIdx: 1 Time: 01/22/2016 21:29:07.009 Number: 140704
PhaseShiftFlags: 16
PhaseShiftCount: 3
PersonalGUID: Full: 0x0
[0] PhaseFlags: 0
[0] Id: 536
[1] PhaseFlags: 1
[1] Id: 1326
[2] PhaseFlags: 1
[2] Id: 1526
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 2
[0] VisibleMapID: 683 (683)

ServerToClient: SMSG_PHASE_SHIFT_CHANGE (0x137C) Length: 41 ConnIdx: 1 Time: 01/22/2016 21:29:31.283 Number: 140816
PhaseShiftFlags: 16
PhaseShiftCount: 2
PersonalGUID: Full: 0x0
[0] PhaseFlags: 0
[0] Id: 536
[1] PhaseFlags: 1
[1] Id: 1327
PreloadMapIDsCount: 0
UiWorldMapAreaIDSwap: 0
VisibleMapIDsCount: 2
[0] VisibleMapID: 683 (683)
```

Just a thought: maybe we should have also phase_template table which would hold phase flags?

**Steps to reproduce the problem:**
none

**Branch(es):** master

**TC rev. hash/commit:** e86a2c439aa2a032ce338d974dae1e5311bcb18f

**TDB version:** TDB 720.00

**Operating system:** Win 7 x64

**Comment by Lopfest** [comment]
solving this issue might fix #16758 and maybe #18885

**Comment by streetrat** [comment]
default phase is 169, so if you want to see the quest's phase and all other default un-phased stuff, then set 169 default for that zone

**Comment by Lopfest** [comment]
shouldn't it be visible in sniffs?
if its like you say, maybe a core thing to do? apply default phase to the area if phase_template phase contains flag 8.
also adding just phase 169 does not solve the thing, that in mentioned quests unphased creatures disappear but gameobjects does not. (there is no common phase, nor any matching phase group)

**Comment by Ovahlord** [comment]
are you sure that there are no matching phase groups for that? So far I wound phase groups for pretty much everything.
