### ISSUE TITLE
Visual Studio: Broken PVS-Studio check solution after Clean Solution

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#21118]
**Description:**

Doing a "Check Solution" from PVS-Studio after a VS "Clean Solution" shows the following error:
>d:\wow\trinitycore\src\server\authserver\authentication\authcodes.cpp: fatal error C1083: Cannot open include file: 'D:\wow\TrinityCore\win\src\server\authserver\Debug\cotire\authserver_CXX_prefix.hxx': No such file or directory  0

**TC rev. hash/commit:** 

2c7e921cdc14527bd99d6976793e69999f262f9d

**Operating system:** Windows 10 x64

**Comment by Faq** [comment]
Borken->Broken

**Comment by Shauren** [comment]
No, its borken.

**Comment by Naios** [comment]
Isn't this just a minor issue?
Probably PVS-Studio will work when the project was built, right?

**Comment by jackpoz** [comment]
Fixed by dropping that broken piece of software that some people refer to as "Cotire"
