### ISSUE TITLE
DB/Misc: Shadowfang Keep

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#21114]
**Description:**

This fixes a few small DB related issues in SFK:

* Update Commander Springvales weapons to the correct pre-cataclysm ones
* Update Lupine Horror and Slavering Worg to stand still
* Add chain aggro to Worgs infront of Wolf Master Nandos
* Add random movement to Razorclaw the Butcher

http://www.wowhead.com/npc=4278/commander-springvale
http://www.wowhead.com/npc=3863/lupine-horror
http://www.wowhead.com/npc=3862/slavering-worg
http://www.wowhead.com/npc=3927/wolf-master-nandos
http://www.wowhead.com/npc=3886/razorclaw-the-butcher

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3a536260f8cd 2017-12-24 13:54:15 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  335.63

**Suggested Fix:**

```sql
-- Change weapons of Commander Springvale to the correct pre-cataclysm ones
UPDATE `creature_equip_template` SET `ItemID1`=5191, `ItemID2`=1201 WHERE `CreatureID`=4278 AND `ID`=1;

-- Update Lupine Horror and Slavering Worg MovementType to stand still
UPDATE `creature` SET `spawndist`=0, `MovementType`=0 WHERE `guid` IN (16240, 16238);

-- Add chain aggro to Worgs infront of Wolf Master Nandos
DELETE FROM `creature_formations` WHERE `leaderGUID`=16241;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`) VALUES
(16241, 16241, 0, 0, 3),
(16241, 16240, 0, 0, 3),
(16241, 16238, 0, 0, 3),
(16241, 16239, 0, 0, 3);

-- Add random movement to Razorclaw the Butcher
UPDATE `creature` SET `spawndist`=5, `MovementType`=1 WHERE `guid`=16253;
```

**Comment by offl** [comment]
```sql
-- Add chain aggro to Worgs infront of Wolf Master Nandos
DELETE FROM `creature_formations` WHERE `leaderGUID`=16241;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`) VALUES
(16241, 16241, 0, 0, 3),
(16241, 16240, 0, 0, 3),
(16241, 16238, 0, 0, 3),
(16241, 16239, 0, 0, 3);
```
This part is not correct.
https://youtu.be/6lDSHN3Gl0I?t=536
