### ISSUE TITLE
[3.3.5/ICC] Missing Spawns

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21129]
**Description:** Missing some spawns of trashs before and after Blood Prince council.

https://i.imgur.com/UFX7uDC.jpg (retail)
https://i.imgur.com/9LjQe2a.jpg (TC)

Creature Entrys:

NPC_DARKFALLEN_BLOOD_KNIGHT = 37595,
NPC_DARKFALLEN_NOBLE  = 37663,
NPC_DARKFALLEN_ARCHMAGE = 37664,

Has 3 packets of trash, 1 before blood prince,  2 after (before Blood Queen)

Packets should contain:

1 noble, 2 archmage, 2 knight, 1 advisor

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 84f69a3b6c9ead74e69475a799fcef409f4369a4

**Comment by Jildor** [comment]
@Keader Can you check NPCs 37544 37545 37546 in Rampart of Skulls?
I think missing some spawns too.

**Comment by Killyana** [comment]
The screen from TC is on 10 man and the one from retail 25 man, I added the extra spawns between  10 and 25 long time ago.

**Comment by tkrokli** [comment]
OK, so no actual issue, then?

**Comment by Keader** [comment]
You're correct Killyana.
