### ISSUE TITLE
[7.3.2] Client Launcher cannot find path.

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#21136]
**Description:**

Cannot Patch World of Warcraft folder

**Current behaviour:**

![image](https://user-images.githubusercontent.com/6026902/34440013-2f24d420-ecaa-11e7-95e4-b735d9ff4ae6.png)
![image](https://user-images.githubusercontent.com/6026902/34440017-35d2f69e-ecaa-11e7-807e-ff2ee69ebd9c.png)

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Insert File into Client folder
2. Load exe.
3. Errors.

**Branch(es):**

7.3.2

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e402734f37e7177903bd81faf8f96365cd06bf0b

**TDB version:**  720
**Operating system:** Win10, Win7

**Comment by Shauren** [comment]
Is reading really that hard? You missed `--path` argument (pointing to wow install directory, not wow exe)

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/34447857-db04545c-ecdf-11e7-9f10-cd0280e2b801.png)
