### ISSUE TITLE
mana food

### ISSUE THREAD

**Issue by deadmanevil** [TrinityCore/TrinityCore#21131]
I have the problem that the meals that regenerate mana have no effect since it is as if they did nothing, I am using the last revision
84f69a3b6c9ead74e69475a799fcef409f4369a4
Branch(es):
3.3.5
TC rev. hash/commit:
TrinityCore rev. 84f69a3 2017-12-26 15:09:43 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
TDB version: 335.63

**Comment by jackpoz** [comment]
I remember this issue getting fixed some time ago, maybe some recent changes added it back

**Comment by Keader** [comment]
was fixed here https://github.com/TrinityCore/TrinityCore/commit/5fc4d36a1fd8214a0b52ba571b2e1b9c6afef79a

**Comment by jackpoz** [comment]
can you do a fast check with food too ?

**Comment by jackpoz** [comment]
Tried "Conjured Glacier Water" and "Conjured Man Strudel" and mana is regenerated properly

**Comment by Keader** [comment]
Tested in rev 84f69a3b6c9ead74e69475a799fcef409f4369a4
item 35950 = [Sweet Potato Bread]
item 33445 = [Honeymint Tea]
both working for me too.
