### ISSUE TITLE
DB/Creature/Misc: Restore deleted pool

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#21130]
**Description:**

The pool commited in 1f9f59b4b3b90f2976201c9b814b723c15a715fd was accidentally replaced in 6e6f43a5e35045bac550b2763dcc8dbed0cf6400.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 84f69a3b6c9e 2017-12-26 12:09:43 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**  335.63

**Suggested Fix:**

```sql
-- Restore deleted pool
SET @POOL_1 := XXX;

DELETE FROM `pool_template` WHERE `entry`=@POOL_1;
INSERT INTO `pool_template` VALUES 
(@POOL_1, 1, "Eye of DarKhan/Wailer Spawn 1");

DELETE FROM `pool_creature` WHERE `guid` IN (82897, 85744);
INSERT INTO `pool_creature` VALUES 
(82897, @POOL_1, 0, "Wailer Spawn 1"),
(85744, @POOL_1, 0, "Eye of DarKhan Spawn 1");
```

**Comment by tkrokli** [comment]
I forgot to mention this earlier, but I would like to give some advice regarding TC SQL codestyle:
it is recommended to use full table row inserts in `DELETE FROM / INSERT INTO` queries, like this:
```sql
DELETE FROM `pool_template` WHERE `entry`=@POOL_1;
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES
```
```sql
DELETE FROM `pool_creature` WHERE `guid` IN (82897, 85744);
INSERT INTO `pool_creature` (`guid`, `pool_entry`, `chance`, `description`) VALUES
```
if you can remember to include the column names and preferably the full row of values, it will be appreciated.

**Comment by Serpaa** [comment]
@tkrokli Im gonna keep that in mind next time, thanks!
