### ISSUE TITLE
DB/Creature: Risen Wintergarde Mage continues to walk in battle

### ISSUE THREAD

**Issue by Regrad** [TrinityCore/TrinityCore#21149]
**Description:**

Some mages continue to walk in battle.

**Current behaviour:**

For example creature id 27283

**Expected behaviour:**

Mages should not walk around during a fight. They must run up to the player and fight.

**Steps to reproduce the problem:**

3.3.5 60fadb3b96188dfe3317317a41528d85aff05dfc (last)

Video of bug: https://youtu.be/fO-m4XIwFk4

**Comment by Ovahlord** [comment]
Can you check the smartAI of this creature and check if the spell cast has the combat_move flag? if yes. try to remove it and check again.

**Comment by Killyana** [comment]
Try:
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=27283 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(27283, 0, 0, 0, 9, 0, 100, 0, 0, 40, 3400, 4800, 11, 9672, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Risen Wintergarde Mage - Within 0-40 Range - Cast 'Frostbolt'"),
(27283, 0, 1, 0, 0, 0, 100, 0, 8000, 12000, 9000, 14000, 11, 13339, 65, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, "Risen Wintergarde Mage - In Combat - Cast 'Fire Blast'");

**Comment by Regrad** [comment]
> Try:
> 
> DELETE FROM `smart_scripts` WHERE `entryorguid`=27283 AND `source_type`=0;
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
> (27283, 0, 0, 0, 0, 0, 100, 0, 1000, 2000, 3400, 4800, 11, 9672, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Risen Wintergarde Mage - IC - Cast 'Frostbolt'"),
> (27283, 0, 1, 0, 0, 0, 100, 0, 8000, 12000, 9000, 14000, 11, 13339, 65, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, "Risen Wintergarde Mage - In Combat - Cast 'Fire Blast'");

Problem fixed

**Comment by Regrad** [comment]
Is there any way to fix all the mages? Or each need to be corrected separately.

**Comment by Killyana** [comment]
Every npc must be fixed separately, you can get a list of this npcs, by searching the ones using the action 21.

**Comment by jerbookins** [comment]
is this at all related to npcs casting while running? such as the defias mages in elwynn forrest?

**Comment by Killyana** [comment]
Yes probably

**Comment by Teppic1** [comment]
There's a lot of all eventai scripts that are plain broken as SAI, they constantly try to turn combat movement on and off manually and it's totally broken (mobs will just stand there looking at you if you go out of LoS for example). Most of those can be replaced with a 1-2 line SAI script that just uses the combat move flag.

**Comment by tkrokli** [comment]
Ideally, open a new issue ticket with a pointer to this one for reference.

**Comment by offl** [comment]
2-3 issues about it are still open.
