### ISSUE TITLE
OS Crash After Recent Upgrades!

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21141]
**Description:**

After recent cpp upgrades, i had problem to compile core in ubuntu 16.04, then i decided to upgrade my OS to ubuntu 17.10. i had no problem with compiling core in ubuntu 17.10 but after few hours for some unknown reason's my VPS crashed. i thought i did somethings wrong, and recompiled core but same problem ( no weird packages installed on my server just apache,php,mysql and required packages which listed in trinitycore requirements ).
I also reinstalled OS and same problem ( OS crash after 1-2 hours ).

Due to recent ubuntu bug's, i decided to give debian 9 a try. everything goes fine, no error at compiling and so on. But same result as ubuntu, Just about two hours after running auth+world server Debian os crashed.

Im not really sure if its related to trinitycore, as i cant find any useful log but i hadn't any problem for month's before cpp upgrade.

the only weird log i can see is this ( a file called TEST.log in bin folder ):
```
soap_instantiate_SOAP_ENV__Fault(0x7efb7225dd30, -1, , )
Instantiated struct SOAP_ENV__Fault location=0x7efb6fa96000 n=-1
PATH/dep/gsoap/stdsoap2.cpp(9193): malloc(32) = 0x7efb6fa860c0
soap_instantiate_SOAP_ENV__Detail(0x7efb7225dd30, -1, , )
Instantiated struct SOAP_ENV__Detail location=0x7efb6fa86100 n=-1
PATH/dep/gsoap/stdsoap2.cpp(9193): malloc(32) = 0x7efb6fa86120
```

**Steps to reproduce the problem:**

1. git clone https://github.com/TrinityCore/TrinityCore
2. cd TrinityCore; mkdir build; cmake ../ -DTOOLS=0 -DBUILD_TYPE=release; make; make install
3. run ./authserver and ./worldserver
4. wait for about 2 hour
5. profit 😁

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 527ef19

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 17.10, Debian 9

**Comment by Aokromes** [comment]
I am running TC 3.3.5a and 4.3.4 on a dedicated server for months without crashes.

**Comment by tje3d** [comment]
my LogsDir was pointing to non-existing/no-permission folder, just changed it and no re run server, no crash in about 1 hour! i can't believe if this change fix my problem.

Anyway, why worldserver logs every incoming and outgoing soap requests? i can't see any configuration for this - RECV.log, SENT.log, TEST.log ( and i had no logs in past )

**Comment by tkrokli** [comment]
Please post questions in the TC Forum pages https://community.trinitycore.org/ (- preferably relevant sub-forum pages -) or ask in [IRC: #trinity @ irc.rizon.net](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC) if you prefer.

Since this is most likely caused by your changes to the `worldserver.conf` file, it is not an issue with the source code itself.

**Comment by tje3d** [comment]
Anyway, trinitycore should crash itself instead whole Operating System

**Comment by Aokromes** [comment]
IMHO if core crashes because non-existing / non-permision folder it must be fixed.

**Comment by tje3d** [comment]
Server uptime: 1 Hour(s) 37 Minute(s) 58 Second(s).
still no crash ( after LogsDir change ).

**Comment by tje3d** [comment]
After about 2 hour's OS crashed again 😔.
No special logs.

seems to be not a TC problem.

**Comment by tje3d** [comment]
Well, after a lot of test's, i'm 100% sure its trinitycore problem.
Using default configuration and without any custom scripts, compiled using clang and cpp but its always crash after few minutes/hours.

**Comment by tkrokli** [comment]
Have you compiled in Debug mode to get any useful crash logs?
- if yes, please post the crash log(s)
- if no, please get some useful logs

**Comment by tje3d** [comment]
No log really. Random crash in few minutes/hours.
tried to get some logs ([Link](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?do=findComment&comment=47672)), When run the server using gdb, almost crashes instantly.

backtrace.log ( nothing useful here ):
```
--- DEBUG: --- START

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1b68700 (LWP 987)]
[New Thread 0x7ffff1367700 (LWP 988)]
[New Thread 0x7ffff0954700 (LWP 989)]
[New Thread 0x7ffff0153700 (LWP 992)]
[New Thread 0x7fffef952700 (LWP 996)]
```

The last 6 lines of Server.log:
```
...
Calculate next weekly quest reset time...
Calculate next monthly quest reset time...
Calculate random battleground reset time...
Calculate guild limitation(s) reset time...
World initialized in 1 minutes 13 seconds
TrinityCore rev. 60fadb3b9618 2017-12-31 04:05:01 +0100 (3.3.5 branch) (Unix, debug, Static) (worldserver-daemon) ready...
```

Here is last -x logs:
```
tje3d    pts/0        2.180.98.44      Sun Dec 31 08:27   still logged in
runlevel (to lvl 5)   4.9.0-4-amd64    Sun Dec 31 08:27   still running
reboot   system boot  4.9.0-4-amd64    Sun Dec 31 08:27   still running
tje3d    pts/2        :pts/0:S.1       Sun Dec 31 08:24 - crash  (00:03)
tje3d    pts/1        :pts/0:S.0       Sun Dec 31 08:24 - crash  (00:03)
tje3d    pts/0        2.180.98.44      Sun Dec 31 08:19 - crash  (00:07)
runlevel (to lvl 5)   4.9.0-4-amd64    Sun Dec 31 08:19 - 08:27  (00:08)
reboot   system boot  4.9.0-4-amd64    Sun Dec 31 08:18   still running
tje3d    pts/2        :pts/0:S.1       Sun Dec 31 08:14 - crash  (00:04)
tje3d    pts/1        :pts/0:S.0       Sun Dec 31 08:13 - crash  (00:05)
tje3d    pts/0        2.180.98.44      Sun Dec 31 08:08 - crash  (00:10)
runlevel (to lvl 5)   4.9.0-4-amd64    Sun Dec 31 08:05 - 08:19  (00:13)
reboot   system boot  4.9.0-4-amd64    Sun Dec 31 08:05   still running
tje3d    pts/3        :pts/4:S.2       Sun Dec 31 07:39 - 07:40  (00:00)
tje3d    pts/1        :pts/4:S.0       Sun Dec 31 07:39 - crash  (00:25)
tje3d    pts/2        :pts/4:S.1       Sun Dec 31 07:39 - crash  (00:25)
tje3d    pts/4        2.180.98.44      Sun Dec 31 07:39 - crash  (00:25)
...
```

**Comment by Aokromes** [comment]
Server uptime: 1 Day(s) 11 Hour(s) 59 Minute(s) 58 Second(s).

Dunno, mabye it needs more resources than the ones of your VPS.

**Comment by tje3d** [comment]
8GB ram DDR4 ( i have 1-2GB always free ), 4Core Broadwell, 160GB SAS HDD.
Maybe its related to VMware Virtualization ( i just guess ), cause i successfully run exactly same core with same configuration on another machine (dedicated).
