### ISSUE TITLE
7.3 master WoWerror

### ISSUE THREAD

**Issue by AndralJu** [TrinityCore/TrinityCore#21140]
**Description:**

WoWerror (client crash) after few minutes in game

**Current behaviour:**

after few minutes in game we have a client crash (WoWerror)
tested with a human started zone : Northshire Valley
![crash](https://user-images.githubusercontent.com/23371494/34451690-707e60ec-ed2e-11e7-99bf-8e4372d599f1.png)

**Expected behaviour:**

should not have this crash

**Steps to reproduce the problem:**

1. create a human 
2. kill some mobs
3. move everywhere and wait until crash

**Branch(es):**

master

**TC rev. hash/commit:** 

96b29d2fa5068615b02e6630e944f12595ed479e

**TDB version:** 7.2 + updates

**Operating system:** windows

**Comment by Shauren** [comment]
Cannot reproduce it myself, did you use the client_launcher from old 7.3.2 branch?

**Comment by Aokromes** [comment]
Update your launcher and try again.
