### ISSUE TITLE
7.3 Sniffer

### ISSUE THREAD

**Issue by AndralJu** [TrinityCore/TrinityCore#21143]
**Description:**

Any news on the 7.3 sniffer?

**Current behaviour:**

 what about blizzard? how can we help if we're banned?

**Expected behaviour:**

should we stop the sniff or there's a new versions or way to sniff?

**Branch(es):**

CHANGEME master

**TC rev. hash/commit:** 

7fd83b8c0f1f1b11666669fd5c94833bd030ea2a

**TDB version:**  latest

**Operating system:** windows

**Comment by Aokromes** [comment]
read https://community.trinitycore.org/topic/12264-trinity-cores-sniffer-for-wow-72524742/
