### ISSUE TITLE
[3.3.5] Core/SmartScripts: DK Death Grip only works on attacking NPCs

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#21144]
Spell Death Grip works only if the Mob is in attack mode.

 http://www.wowhead.com/spell=49576/death-grip

**Branch(es):**  3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 671a34a966ae 2017-12-30 18:06:33 +0100 (335a branch)

**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Windows 7

**Comment by tkrokli** [comment]
Are you sure about that spell ID? Looks like it was added in Cataclysm or later (spell ID 60000+)
What about http://www.wowhead.com/spell=49576/death-grip or source code reference?

**Comment by Tauriella** [comment]
Ups
@tkrokli you are right :) it is spell 49576

**Comment by tkrokli** [comment]
OK, I need to test that after I have had some sleep. Can anyone else confirm this?

**Comment by Infinito47** [comment]
I do not have this issue. Even with .gm on it grips the NPC towards my test character.

**Comment by sxf1749** [comment]
I have this issue too. rev. ecc55c2
only works if the mob is in attack mode, and spell visual is ok.

**Comment by Killyana** [comment]
You're testing this issue with this npc http://www.wowhead.com/npc=28557/scarlet-peasant  ?

**Comment by Aokromes** [comment]
I tried with one mob near shattrah, with player account, indeed, it's bugged.

**Comment by Killyana** [comment]
It works only with some npcs, I cannot find why.

**Comment by lachtanek** [comment]
Only NPCs with SmartAI have this bug, the problem is here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartAI.cpp#L598 (cancelling controlled movement)

**Comment by cBonky** [comment]
is still broken
https://www.youtube.com/watch?v=c2RoRYghrzQ

3.3.5 branch
TrinityCore rev. 46fcbb42d2ad
World DB: TDB 335.63
Operating system: Windows 7 x64

**Comment by Langerz82** [comment]
Whats an NPC ID that I can test with?

**Comment by tkrokli** [comment]
TrinityCore rev. f1896144c00e 2018-01-18 19:14:38 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
TDB 335.63 + updates up to and including `2018_01_18_02_world_335.sql`

Previously, the most regular and repeatable NPC I have seen with this issue is Scarlet Medic in the DK starter area, but the issue seems to have expanded to include the other Scarlet mobs too now. When casting Death Grip, the aggro'ed NPC simply runs towards the player to attack in melee range.

**Comment by Langerz82** [comment]
@tkrokli Indeed you are correct I will try and submit a patch very soon.

**Comment by tkrokli** [comment]
@Langerz82 : I tested your fix (linked and posted in your comment above) based on current TC `3.3.5` source commit fa3eb754cb, but no improvement. In fact, it got a little bit worse. The aggro'ed NPCs just stood still after Death Grip was cast, but it was still possible to Death Grip them a second time (after cooldown) while my player character is on their threat list (same as described earlier in this issue).

**Comment by lachtanek** [comment]
Can you test reverting what @Langerz82 posted and changing
me->PauseMovement();
to
me->PauseMovement(0, 0, false);
please? It should work, if not removing me->PauseMovement() works 100%, but that is not correct probably

**Comment by tkrokli** [comment]
Thanks, will test that as soon as my current compile is done (testing the patch Langerz82 wrote for the Mind Control / Taming Rod issues).

**Comment by tje3d** [comment]
i can confirm removing me->PauseMovement() fixes the issue

**Comment by ariel-** [comment]
@ccrs: shouldn't 'forced' movements like this have highest priority?

**Comment by lachtanek** [comment]
@ariel- they do, but not if you stop all movement (PauseMovement does that, if third parameter is true)

**Comment by ariel-** [comment]
Then maybe it shouldn't stop controlled movegens, the problem here is that it's using Unit::StopMoving which simply launches a new dummy spline, that seems to have higher priority than anything

**Comment by tkrokli** [comment]
Tested in the DK starter area, the `PauseMovement` change was successful, it worked as intended.
Death Grip works without issues, even on the Scarlet Medic NPCs.
```diff
diff --git a/src/server/game/AI/SmartScripts/SmartAI.cpp b/src/server/game/AI/SmartScripts/SmartAI.cpp
index 2b815b677a..00b6661d41 100644
--- a/src/server/game/AI/SmartScripts/SmartAI.cpp
+++ b/src/server/game/AI/SmartScripts/SmartAI.cpp
@@ -595,7 +595,7 @@ void SmartAI::AttackStart(Unit* who)
     if (who && me->Attack(who, mCanAutoAttack))
     {
         me->GetMotionMaster()->Clear(MOTION_SLOT_ACTIVE);
-        me->PauseMovement();
+        me->PauseMovement(0, 0, false);
 
         if (mCanCombatMove)
         {
```
The question remains: is this an acceptable solution, or do we need more changes?

**Comment by jerbookins** [comment]
Still not working. It only works on NPCs that are already running toward you. If you cast it on an unsuspecting NPC the movement of the NPC will interrupt the pulling motion of the spell.

**Comment by Aokromes** [comment]
a patch waiting tests exist since jan 20.
