### ISSUE TITLE
Bloodlord Mandokir Enrage persists through wipe

### ISSUE THREAD

**Issue by Pugnadeus** [TrinityCore/TrinityCore#21158]
**Description:**

If you enrage Bloodlord Mandokir by killing the raptor first, wipe while the enrage is still taking place, then his enrage will persist and he will have it on his next attempt aswell.

**Current behaviour:**

You wipe while Bloodlord Mandokir is enraged, once you attempt to kill him again, the enrage will continue being on him

**Expected behaviour:**

Bloodlord Mandokir's buffs should reset after the wipe, not remain on him.

**Steps to reproduce the problem:**

1. Start encounter with Bloodlord Mandokir(ID: 11382) by killing the Vilebranch Speaker((ID: 11391)
2. Wait for him to get off his raptor so that he + Ohgan(his raptor) spawn
3. Kill Oghan(ID: 14988), watch Mandokir get enraged
4. Wipe while the enrage is still going on
5. Revive, and attempt the bossfight again

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 6070340 2017-10-07 17:13:34 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:**  TDB_full_world_335.63_2017_04_18

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
You are using a 3 month old core, please update your core.
Also test your issue again and verify if this is still happening.
Important changes are added to the source almost every week.

**Comment by offl** [comment]
#19071

**Comment by ariel-** [comment]
Unrelated to #19071 since Mandokir doesn't use _DespawnAtEvade
