### ISSUE TITLE
Scripts/Arcatraz: Millhouse Manastorm does not engage in combat

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21154]
**Description:**
http://www.wowhead.com/npc=20977/millhouse-manastorm
https://www.youtube.com/watch?v=T9WMOSiQUYQ

**Current behaviour:**
Millhouse seems to have his dialogue scripted properly, but when he's finished buffing up he just stands there. He doesn't engage in combat. It is also impossible to complete the quest Trial of the Naaru: Tenacity (10886). And if you stand still too long without engaging Harbinger Skyriss he will despawn along with Millhouse Manastorm.

**Expected behaviour:**
Millhouse should engage in combat whenever the player engages combat, after he is buffed up.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 60fadb3b9618

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
interesting comment in
https://github.com/TrinityCore/TrinityCore/blob/100ecf69f1f0aaca9a27abdba3d62087b2b6513e/src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp#L22

When this issue gets confirmed by others, it will be necessary to go through his script to find out why it fails (although the hint above suggests problems) :
https://github.com/TrinityCore/TrinityCore/blob/100ecf69f1f0aaca9a27abdba3d62087b2b6513e/src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp#L38-L228
