### ISSUE TITLE
Scripts/Arcatraz: quest "Trial of the Naaru: Tenacity" will not complete

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21155]
**Description:**
http://www.wowhead.com/quest=10886/trial-of-the-naaru-tenacity

**Current behaviour:**
Killing Harbinger Skyriss while Millhouse is alive does not fulfill the quest criteria.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 60fadb3b9618

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Very likely caused by the same type of issue as in
**Scripts/Arcatraz: Millhouse Manastorm does not engage in combat** #21154 
because he is supposed to announce and complete the quest (in his script).
