### ISSUE TITLE
DB/Creature: Harbinger Skyriss + clones, HP amount

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21168]
**Description:**
http://www.wowhead.com/npc=20912/harbinger-skyriss

**Current behaviour:**
Harbinger Skyriss only has 47k hp.

When he reaches 66% health (approx 31k hp), his first clone has approx 15k hp.

When he reaches 33% health (approx 15.5k hp), his second clone has approx 63.2k hp.

**Expected behaviour:**
On (live) heroic, Skyriss has 380k hp, both of his clones have 30k hp. On (live) normal, Skyriss has 115k hp, both of his clones when spawned have 9.1k hp. Both clone hp values at 33% and 66% are 8% of Skyriss's total health.

But [this very very old internet archive snapshot of wowhead](https://web.archive.org/web/20110801015046/http://www.wowhead.com/npc=20912) (June 25, 2011)  says 147,575 to 194,799. I don't know which you would prefer information from.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 4e9d34691997

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
Values from TBC:
```text
 entry  name                     minhealth  maxhealth  
------  -----------------------  ---------  -----------
 20912  Harbinger Skyriss           147575       147575
 21466  Harbinger Skyriss            17709        17709
 21467  Harbinger Skyriss            35418        35418
 21599  Harbinger Skyriss (1)       194799       194799
 21600  Harbinger Skyriss (1)        23612        23612
 21601  Harbinger Skyriss (1)        47224        47224
```
Heroic https://youtu.be/GDs8W8euBNo?t=204
Normal https://youtu.be/8lB9vCxUSq4?t=524

**Comment by offl** [comment]
Or difficulty entries are messed up. In this case the fix above is not correct.

**Comment by tkrokli** [comment]
Good question, need to wait for reply from someone who knows.

**Comment by offl** [comment]
Difficulty entries were messed up.
```sql
--
UPDATE `creature_template` SET `difficulty_entry_1`=21599 WHERE `entry`=20912;
UPDATE `creature_template` SET `difficulty_entry_1`=21601 WHERE `entry`=21467;
UPDATE `creature_template` SET `unit_flags`=832, `lootid`=21599, `mingold`=9588,`maxgold`=12532 WHERE `entry`=21599;
UPDATE `creature_template` SET `unit_flags`=66, `lootid`=0, `mingold`=0,`maxgold`=0,`flags_extra`=0 WHERE `entry`=21601;
UPDATE `creature_loot_template` SET `Entry`=21599 WHERE `Entry`=21601;
```
