### ISSUE TITLE
DB/Creature: Skulking Witch invisibility

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21166]
**Description:**
http://www.wowhead.com/npc=20882/skulking-witch

**Current behaviour:**
Skulking Witch is not invisible.

![wowscrnshot_010218_174115](https://user-images.githubusercontent.com/16745918/34505732-3661dd54-efe4-11e7-828a-1cbe6f117499.jpg)

**Expected behaviour:**
Skulking Witch should be invisible until agro.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 036a05458eb9

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by offl** [comment]
(20882,0,0,1,16,0,0,'32811'),
For some reason probably sniffed 32811 was replaced to 16380

**Comment by offl** [comment]
Oh, please, always write on which mode you are testing :)
There's a ton of similar bugs existing only in heroic mode, and you're always in heroic mode. But when someone tries to figure out where is the problem he always looks for normal mode entries.
```sql
--
UPDATE `creature_template_addon` SET `auras`=32811 WHERE `entry` IN (20882,21613);
```

**Comment by tkrokli** [comment]
@jerbookins : Please test and confirm what offl said in https://github.com/TrinityCore/TrinityCore/issues/21166#issuecomment-355820132 (the comment above mine).

**Comment by tkrokli** [comment]
Meh, http://www.wowhead.com/spell=16380/greater-invisibility is a Mage class spell.
I'll just post your update and close this issue anyway. 👍
