### ISSUE TITLE
creating default logger error

### ISSUE THREAD

**Issue by gearsofdeath** [TrinityCore/TrinityCore#21179]
I just compiled trinity latest rev just now and i have this weird error and cant find a solution 
https://gyazo.com/a02aa027c638746e901f6fb81a0e63e0

anyhelp please its been days

Core Version
TrinityCore rev. 73ec3a1d3b34 2017-04-19 01:14:14 +0100 (3.3.5 branch) (Win64, Release)

Core rev
73ec3a1d3b34

DB version
TDB 335.63

**Comment by Aokromes** [comment]
this belongs to forum.

**Comment by gearsofdeath** [comment]
i dont think so since i just compiled it i was compiling trinitycore easly but not this time

**Comment by tkrokli** [comment]
Default settings in `worldserver.conf` don't cause that kind of error message.
Please use default settings and then change only 1 thing at a time when testing.
Ask in TC Forum pages or in the #trinity channel on irc.rizon.net about settings.
