### ISSUE TITLE
Build/Boost: compile error on OSX (Mac)

### ISSUE THREAD

**Issue by dimiandre** [TrinityCore/TrinityCore#21171]
**Description:**
Compiling on mac osx is not working

**Current behaviour:**

When i compile i get this error

```
/Users/andrea/WoW/Trinitycore/src/common/Utilities/AsioHacksImpl.h:25:44: fatal error: incomplete type 'boost::asio::io_service' named in nested name specifier
    class AsioStrand : public boost::asio::io_service::strand
                              ~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /Users/andrea/Trinitycore/src/common/Logging/Log.cpp:1:
In file included from /Users/andrea/Trinitycore/build/src/common/Release/cotire/common_CXX_prefix.hxx:4:
In file included from /Users/andrea/Trinitycore/build/src/common/Release/cotire/common_CXX_prefix.cxx:4:
In file included from /Users/andrea/Trinitycore/src/common/PrecompiledHeaders/commonPCH.h:7:
/Users/andrea/Trinitycore/src/common/Logging/Log.h:38:15: note: forward declaration of 'boost::asio::io_service'
        class io_service;
              ^
1 error generated.
```

**Expected behaviour:**
It should not give errors 

**Steps to reproduce the problem:**

1. Follow the wiki
2. Run xcodebuild -target install -config Release

**Branch(es):**

Tested only in master, but i think both

**TC rev. hash/commit:** 
78ba1d76ddc65add3be3ccbb08c750c6a5c8f5a5

**TDB version:**  
N/A

**Operating system:** 
MacOSX 10.13.2 
Xcode 9.2
Homebrew

**Comment by tkrokli** [comment]
Unfortunately, I don't have access to any MacOS to test your issue.
I am, however, able to reproduce that error message (`fatal error: incomplete type 'boost::asio::io_service'`)
 if I use Boost 1.66.0 with Visual Studio 2017 15.5.2 (19.12.25831.0).

I don't get that error when using Boost 1.65.1 or 1.65.0, though, only the warnings about "Unknown compiler" (Boost config case).
Have you tested using different versions of Boost? Which version are you using now?

**Comment by dimiandre** [comment]
I'm on 
-- Boost version: 1.66.0

I'll try to downgrade and let you know

**Comment by Aokromes** [comment]
Try after b1ad5df1ee0620ff7b94799d6bae59aa05a0e624

**Comment by dimiandre** [comment]
@Aokromes i was already after that commit

i'm building with 1.60 and it works

**Temporary solution: downgrade**

```
brew uninstall boost
brew install boost@1.60
```

delete build folder
create build folder, run cmake again


** BUILD SUCCEEDED **

**Comment by Aokromes** [comment]
Nope, i pushed that 17 minutes ago.

**Comment by dimiandre** [comment]
@Aokromes sorry i'm dumb, i just looked at the date

i'll try it now

**Comment by jackpoz** [comment]
boost 1.66 is not supported atm https://github.com/TrinityCore/TrinityCore/commit/b1ad5df1ee0620ff7b94799d6bae59aa05a0e624#commitcomment-26407801

**Comment by dimiandre** [comment]
confirm, build stilld does not works.

I'm updating the API, but after the updated the minimum requirement will be 1.66 for all OS
should i continue or it's a waste of time ?

i'm not expert enough to enable both versions

**Comment by Aokromes** [comment]
stay on 1.65 like macos wiki states.

**Comment by dimiandre** [comment]
@Aokromes ok, i'll stop the update so

thanks!
