### ISSUE TITLE
Death knight Death Strike

### ISSUE THREAD

**Issue by murdocmurat** [TrinityCore/TrinityCore#21175]
hi i have on my core last revision bug of Death strike Dk heals not enough only 40 60 healing can someone help me on fix

trinitycore rev 9199e8f1068d+ 2017-12-19 +100 3.3.5a branch

TDB_full_world_335.63

**Comment by tje3d** [comment]
It works good. Don't forgot to apply Blood Plague and Frost Fever before using Death Strike.

**Comment by murdocmurat** [comment]
ty bro sorry my bad <3
