### ISSUE TITLE
Scripts/IcecrownCitadel: Valithria Dreamwalker does not start combat

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21174]
**Description:**

After attacking any of Risen Archmage's combat and boss should start, but it wont after 532ab1c.

i've seen that Risen Archmages wont assis't each other, or as another example the champions of Sister Svalna wont asist her and stay where they spawned, Same with Crok Scourgebane mates.

**Steps to reproduce the problem:**

1. .go creature 137747
2. attack one of the Risen Archmage and combat should start

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

08277f5

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 17.10

**Comment by Mihapro** [comment]
Creature formation?

**Comment by Treeston** [comment]
nah, valithria has some weird fuckery in her script.

i'll work on it after i finish reading the meltdown paper
