### ISSUE TITLE
DB/Spell: Magma Totem

### ISSUE THREAD

**Issue by DanVS** [TrinityCore/TrinityCore#21178]
**Description:** [Magma Totem (rank 1)](https://dbwotlk.com/?spell=8187) etc.

**Current behaviour:** Magma Totem generates threat.

**Expected behaviour:** Starting from [patch 3.0.8](http://us.battle.net/wow/en/game/patch-notes/3-0-8) it no longer generates threat (closes #4728).

**Branch(es):** 3.3.5a

**TC rev. hash/commit:** TrinityCore rev. 9f9507e6a1fd+

**Operating system:** Ubuntu 16.04

``` sql
-- Magma Totem
DELETE FROM `spell_threat` WHERE `entry` IN (8187,10579,10580,10581,25550,58732,58735);
INSERT INTO `spell_threat` (`entry`, `flatMod`, `pctMod`, `apPctMod`) VALUES 
(8187,0,0,0),
(10579,0,0,0),
(10580,0,0,0),
(10581,0,0,0),
(25550,0,0,0),
(58732,0,0,0),
(58735,0,0,0);
```

**Comment by tkrokli** [comment]
@DanVS : Would you mind including the column names in the query too? (code style, you know)

**Comment by DanVS** [comment]
Done.

**Comment by Killyana** [comment]
I think for this spells we must use spell_custom_attr with: @SPELL_ATTR0_CU_NO_INITIAL_THREAT             = 16,

**Comment by DanVS** [comment]
Is this method better?

**Comment by Jildor** [comment]
like this?
(I copy/pasted the spellids, not sure if rank is needed)

```sql
DELETE FROM `spell_custom_attr` WHERE `entry` IN (8187,10579,10580,10581,25550,58732,58735);
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(8187,16),
(10579,16),
(10580,16),
(10581,16),
(25550,16),
(58732,16),
(58735,16);
```

**Comment by Killyana** [comment]
Or maybe it's handled by this attributes:

AttributesEx3: 0x02000040 (SPELL_ATTR3_UNK6, SPELL_ATTR3_UNK25) use by: 10580
10581,25550,58732,58735, 61905 Only.

And AttributesEx3: 0x00000040 by 8187, 10579 and many others.

**Comment by tkrokli** [comment]
You mean this may be a core issue instead of a DB issue?

**Comment by Killyana** [comment]
I mean it must probably be handled by the spell attribute.
Maybe @ariel-  can take a look.
