### ISSUE TITLE
Core/Spell: Feral Spirit

### ISSUE THREAD

**Issue by DanVS** [TrinityCore/TrinityCore#21184]
**Description:** [Feral Spirit](https://dbwotlk.com/?spell=51533)

**Current behaviour:** Summoned Feral Spirit hasn't pet tab in character details windows.

**Expected behaviour:** Feral Spirit must have tab with model, stats etc. The problem is that from what I understand this window is showed only for DB saved pets (death knight/hunter/warlock), _but Spirit is counted as temporary minion/guardian_.

**Branch(es):** 3.3.5a

**TC rev. hash/commit:** TrinityCore rev. 9f9507e6a1fd+

**Operating system:** Ubuntu 16.04

**Comment by Keader** [comment]
Any prof?

**Comment by DanVS** [comment]
It's pretty hard to find video or screen, but their stats are known by [SimCraft](https://github.com/shunter/SimcraftGearOptimizer/blob/b5c1f82b2bf7579389d23b769e520a6b0968fc98/Simcraft/Simcraft/sc_shaman.cpp#L358) (you can see that fire elemental stats are unknown).

**Comment by Shauren** [comment]
Thats not proof at all

**Comment by DanVS** [comment]
My bad, they really shouldn't tab (despite some screenshots or [videos](https://youtu.be/D-cHLaJ-eJg?t=16s) shows pet tab, it's because of this [macro](http://archive.is/6SLfn#selection-1733.0-1733.155)):
```js
/run if not oldHasPetUI then oldHasPetUI = HasPetUI; HasPetUI = function() return true, false; end end PetTab_Update() ToggleCharacter("PetPaperDollFrame")```
