### ISSUE TITLE
Unknown opcode

### ISSUE THREAD

**Issue by CaptainWindmark** [TrinityCore/TrinityCore#21182]
**Current behaviour:**

This opcodes cant handle + a unknown opcode occures. 

Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BC (14012)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F6 (14070)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1684358213 })
No defined handler for opcode [UNKNOWN OPCODE 0x36B8 (14008)] sent by [Player: Account: 1]
Received not handled opcode [CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS 0x3707 (14087)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 1]
Received not handled opcode [CMSG_QUEUED_MESSAGES_END 0x376C (14188)] from [Player: Logging in: GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Prevented sending of NULL_OPCODE to [Player: Logging in: GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_QUERY_COUNTDOWN_TIMER 0x31A4 (12708)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS 0x32A0 (12960)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_DF_GET_JOIN_STATUS 0x3615 (13845)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_LFG_LIST_GET_STATUS 0x360C (13836)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_REQUEST_LFG_LIST_BLACKLIST 0x3291 (12945)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32DB (13019)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
CMSG_DB_QUERY_BULK: [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1] requested unsupported unknown hotfix type: 3386291891
Received not handled opcode [CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS 0x3707 (14087)] from [Player: Nubilus GUID Full: 0x0800040000000000000000000000000B Type: Player Entry: 0 Low: 11, Account: 1]
Received not handled opcode [CMSG_REPORT_CLIENT_VARIABLES 0x3701 (14081)] from [Player: Account: 1]
Received not handled opcode [CMSG_REPORT_ENABLED_ADDONS 0x3700 (14080)] from [Player: Account: 1]
Received not handled opcode [CMSG_REPORT_KEYBINDING_EXECUTION_COUNTS 0x3702 (14082)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BC (14012)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F6 (14070)] from [Player: Account: 1]

**Branch(es):**
master

**TC rev. hash/commit:** 
TrinityCore rev. 2ee6ce68495f+ 2018-01-04 01:15:33 +0100 (master branch) (Win64, Release, Static)

**TDB version:**  720.00

**Operating system:** WIndows Server 2012 R2

**Comment by Aokromes** [comment]
Those opcodes are unsupported and we don't have plans to support them.
