### ISSUE TITLE
DB/Gossip : gossip menu about Uldum appear on npc and gameobject

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#21186]
**Current behaviour:**

CHANGEME Tell us what happens.
When I speak to MacBride or another npc which it is possible to discuss, this gossip menu appear, and it's the same with gameobject. If i look the worldserver console I get this error :

Creature Marshal McBride (GUID Full: 0x20000400000031400000000000000077 Type: Creature Entry: 197 Low: 119 DB GUID: 279961) has UNIT_NPC_FLAG_VENDOR set but has an empty trading item list.

**Expected behaviour:**

The gossip should not appear and I should not have this error log in the console.

**Steps to reproduce the problem:**

1. git clone https://github.com/TrinityCore/Trinitycore  
2. compile and install clean TDB and make all updates
3. extract dbc & maps from your 7.3.2 client
4. Start worldserver and speak to a npc like Marschal MacBride for exemple

**Branch(es):**

master

**TC rev. hash/commit:** 739b530

TrinityCore rev. 739b5309bf56 2018-01-04 01:15:33 +0100 (master branch) (Unix, RelWithDebug, Static) (bnetserver)

**TDB version:** TDB 720.00 with updates

**Operating system:** Debian 9 Stretch

![sans titre](https://user-images.githubusercontent.com/821614/34610176-41ea1fb8-f220-11e7-9c15-6cabed9ad68a.png)
![calltoarms](https://user-images.githubusercontent.com/821614/34611195-c8053d54-f224-11e7-9f44-6c68eaf5ef4f.jpg)

**Comment by Kedaewyn** [comment]
It's same for me after fresh compil with the same os 

> Debian 9 Stretch

Same rev 

> TrinityCore  rev. 739b530 2018-01-02 15:35:42 +0100 (master branch) (Unix, RelWithDebug, Static) (bnetserver

And Same TDB version

> TDB 720.00 with updates

**Comment by Kodekc** [comment]
Critical

**Comment by Kodekc** [comment]
@Aokromes , this error disrupts the operation of all NPCs that use the gossip menu

**Comment by Shauren** [comment]
No matter what i do, I can't reproduce it.
All of the npcs on screenshow have no gossip and launch autoaccept quest like they are supposed to

**Comment by tkrokli** [comment]
Could this be specific to other language clients than the enUS version?
Or it could be caused by local language adaptions, I don't know.
(I have only got the enUS game client so I can't test this theory.)

**Comment by ForesterDev** [comment]
![image](https://user-images.githubusercontent.com/11771800/35610541-18a1d80c-067b-11e8-929e-79d75132a930.png)

I have same problem on rev. https://github.com/TrinityCore/TrinityCore/commit/dc43a08d369ef9c52b3425754545385962a2ffde (ruRU client)

**Comment by Kodekc** [comment]
The error lies in the assembly for different OS. Tested

**Comment by tkrokli** [comment]
Oh. I see. You mean that this is caused by building the servers on a different OS than the one it is running on?

**Comment by Pixel-Pirate** [comment]
@tkrokli I can't tell if the problem is present under a build windows but under mac and linux it is the case.

**Comment by tkrokli** [comment]
I don't think it can be reproduced on Windows -- many more would have confirmed it by now.

**Comment by Pixel-Pirate** [comment]
I believe so, too, but it's very embarrassing.

**Comment by ForesterDev** [comment]
This bug appear on linux-based systems, because of type mismatch in core and db.

Fix

```
ALTER TABLE `gossip_menu_option` CHANGE `MenuID` `MenuID` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `gossip_menu_option` CHANGE `OptionID` `OptionID` INT(10) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `gossip_menu_option_action` CHANGE `MenuID` `MenuID` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `gossip_menu_option_action` CHANGE `OptionID` `OptionID` INT(10) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `gossip_menu_option_box` CHANGE `MenuID` `MenuID` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `gossip_menu_option_box` CHANGE `OptionID` `OptionID` INT(10) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `gossip_menu_option_trainer` CHANGE `MenuID` `MenuID` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `gossip_menu_option_trainer` CHANGE `OptionID` `OptionID` INT(10) UNSIGNED NOT NULL DEFAULT '0';

```

**Comment by Shauren** [comment]
type mismatch? that cannot be, these tables were created by https://github.com/TrinityCore/TrinityCore/blob/master/sql/updates/world/master/2017_07_26_00_world.sql and have uint32 type in them already

**Comment by Shauren** [comment]
Unless... are you using mariadb by any chance?

**Comment by ForesterDev** [comment]
@Shauren, https://github.com/TrinityCore/TrinityCore/commit/22a8fbe4cb908988f129ec140d4beb7c8f907f67 these changese were made after your commit

**Comment by Shauren** [comment]
fuck. this explains EVERYTHING

**Comment by Pixel-Pirate** [comment]
@Shauren With WITH_COREDEBUG yes and using MariaDB

**Comment by Aokromes** [comment]
why the fuck you guys use WITH_COREDEBUG on production environments when it's stated don't use it unless told to enable it?
