### ISSUE TITLE
[Master] Artifacts Alternate Slots

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#21180]
**Description:**

The Artifacts do not automaticly add Off-hands for the ones that require it or Main hands.

**Current behaviour:**

Adding only adds the weapon the ID is assigned to like Felo'melorn the off-hand Heart of the Phoenix  dose not automaticly get added.
![wowscrnshot_010418_181102](https://user-images.githubusercontent.com/6026902/34577896-d27112ae-f17a-11e7-8f74-bb5cc74cdfb9.jpg)

**Expected behaviour:**
If an Artifact has a secondary weapon/slot aka off-hand or main hand.. both slots would automaticly be added.

**Steps to reproduce the problem:**

1. add 128820 (Felo'melorn) - Fire mage
2. Off-hand dose not apply.
3. Step 3

**Branch(es):**

Master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/2ee6ce68495ff6a84f082b53431db50633ee8c88

**TDB version:**  720.00

**Operating system:** Win7

**Comment by Shauren** [comment]
Tested on 2ee6ce68495ff6a84f082b53431db50633ee8c88
Ran exactly what you see on screenshot chat
.lookup
.add
and there it is.
![wowscrnshot_010418_215925](https://user-images.githubusercontent.com/297439/34584124-c53a015c-f19a-11e7-9e6b-93021a98509d.jpg)

**Comment by Nupper** [comment]
seems to be if artifacts are sold from vendor then.
