### ISSUE TITLE
[CRASH] in std::_Rb_tree_rebalance_for_erase

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#21188]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
Dont know how this happen.

**Current behaviour**: 
Believe related to threat system rewrite

- https://pastebin.com/s4zJVA1t

**Expected behaviour**: 

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
e0b609a178528995959e5ea54255a3f856e62913

**TDB version**:  
335.63

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Treeston** [comment]
Likely related to #21187, UB somewhere.

**Comment by lachtanek** [comment]
Don't think so, I did not touch that part of core and it is a crash in std::set::erase with uint32 (not iterator) argument which should have no way to crash. No idea about this one really.

**Comment by Treeston** [comment]
"Magical" crash dump like that indicates UB invocation previously, fyi.

**Comment by Shauren** [comment]
Might be a late side effect of #21187 if the invalid dereference didn't immediately crash but overwritten other memory location

**Comment by Treeston** [comment]
Can't be excluded, but shouldn't be relied upon.

**Comment by Treeston** [comment]
closing, see #21187
