### ISSUE TITLE
GetAreaAndZonePhases is loading wrong areas

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21196]
**Description:**
when loading phases from DB, they are loaded this way: `_phases[area].push_back(phase);`
however this "area" index is (probably) never used when deciding which areas to load during player's area change.

**Current behaviour:**
currently `GetAreaAndZonePhases` gets ALL phases from DB, regardless of which area or zone the player is located in. if there are multiple areas with the same phase, only the last phase which is loaded is applied. others are overwritten by the result of last loaded phase check - which always results to remove phase (`_phases.erase(id)` in method `SetInPhase`)

here is some output from the console, where i have put some logs:
![image](https://user-images.githubusercontent.com/32191/34649544-8a9e5cbe-f3b1-11e7-88a5-bd61296c6fa6.png)

**Expected behaviour:**
GetAreaAndZonePhases should load ONLY phases for area or zone, where player is currently located.

**Steps to reproduce the problem:**

1. insert phase into DB `INSERT INTO phase_area (AreaId, PhaseId, Comment) VALUES (5736, 169, '');`
2. go to the wandering isle, other area than Shang Xi Training Grounds, for example here: `.go xyz 1000 3600 193`
3. phase is not applied

**Branch(es):** master

**TC rev. hash/commit:** 7d00ae40458fe4399ca414c79a9b0a88b863267a

**TDB version:**  TDB 720.00

**Operating system:** Win 7 x64

**Comment by zgn1988** [comment]
confirm

if you send the player to the correct phase

![wowscrnshot_010818_050834](https://user-images.githubusercontent.com/417389/34657113-25494ae4-f434-11e7-9caf-359293a92eae.jpg)
