### ISSUE TITLE
Broggok

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21194]
**Description:**
http://www.wowhead.com/npc=17380/broggok

**Current behaviour:**
After pulling the lever to start the event, and killing each wave of Nascent Fel Orc, the doors open to allow Broggok to enter the room but he just stands there. You can attack Broggok and he doesn't do anything.

![wowscrnshot_010618_221747](https://user-images.githubusercontent.com/16745918/34646892-f1eca7b2-f330-11e7-877b-efc69bea0805.jpg)

**Expected behaviour:**
After killing the final group of Nascent Fel Orcs, the gates open and Broggok moves to the middle of the room.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** e0b609a17852

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by tje3d** [comment]
No sure if its related but same thing happened to Professor Putricide Oze's

**Comment by grigory9** [comment]
I have tested this boss and it works as expected 

> Expected behaviour:
> After killing the final group of Nascent Fel Orcs, the gates open and Broggok moves to the middle of the room.

**Branch(es):** 3.3.5
**rev. hash/commit:** 02f1399fde008d3cc40ed80cb859764fba15eeff
**TDB version:** 335.64
**Operating system:** Mac OSX High Sierra
