### ISSUE TITLE
Valithria Dreamwalker Portals Problem

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21198]
**Description:**

There is a problem with Valithria Dreamwalker portals. When you go to portals, you should not see any other player and should see valithria is flying. Also you should not take any damage from outside but you will.

![Screenshot](https://user-images.githubusercontent.com/5238989/34651561-0a8e2f50-f3e7-11e7-9e45-513810a202fd.png)

**Expected behaviour:**

Check this video: https://www.youtube.com/watch?v=LEipp3dDR9I ( 2:10 )

You should not be able to see players outside portal and also you should see Valithria is flying.

**Steps to reproduce the problem:**

1. .go creature 137747
2. wait for portals to spawn, click on any

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

38d0c1e

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

NOTE: same thing happen to Ruby Sanctum Halion, at phase 3, you will see two boss, and everyone takes damages from two phase which make its impossible to defeat ( i'l open another issue for this ).

**Comment by Keader** [comment]
Both cases is controlled by phases.
Are you sure that you're stucked in GM phase? (-1)

**Comment by tje3d** [comment]
Im sure about RS ( many players reported that ).
But this is what i see with a non-gm player (but sometimes the first Screenshot happens to some players too):
![screenshot](https://user-images.githubusercontent.com/5238989/34652863-4888f594-f3f9-11e7-9270-da652b9a4b45.png)

**Comment by Treeston** [comment]
Can no longer reproduce after 3bb33e3 and 9ad11e6.

**Comment by tje3d** [comment]
@Tesston Halion phase works good ( but i will do some more test soon ).
But when you kill Halion he just disappeared and you cant loot him, and after a few seconds Halion will respawn.

**Comment by tje3d** [comment]
tested on 663a6f2

**Comment by tje3d** [comment]
@Treeston just to note that i got acheivement but there is nothing to loot.

**Comment by Treeston** [comment]
can't test right now, but that fix should work

**Comment by tje3d** [comment]
@Treeston fixed, thanks

**Comment by Strazhnik** [comment]
Valithria don't stop event if parametrs hp=0.3 and damage=0.1 (worldserver.conf)
After few seconds the mobs are resurrectet again.
