### ISSUE TITLE
Druid Tree of Life powershifting

### ISSUE THREAD

**Issue by Johanes00** [TrinityCore/TrinityCore#21197]
**Description:**

Powershifting Tree of Life form does not remove slow/root effects from the druid

**Current behaviour:**

Powershifting Tree of Life form does not remove slow/root effects from the druid.
You can read from the combat log that this form is not re-applied

**Expected behaviour:**

Powershifting should remove slow/root effects from the druid, currently it does not. Only shifting out and back into form manually does it.

**Steps to reproduce the problem:**

1. As druid duel any class that can apply slow/root effect. Death knight for example has Chains of ice slow.

2. Make a macro and use it:
/cast !Tree of Life

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
[`e0b609a`](https://github.com/TrinityCore/TrinityCore/commit/e0b609a178528995959e5ea54255a3f856e62913)

**TDB version:**  335.63

**Operating system:** Win10

**Comment by Keader** [comment]
Just a Note: it work without macro.

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/563e02370ea81f1a6baf2dab701e0c30d4dff112

**Comment by Seyden** [comment]
Powershifting shouldn't even work in legion.. so it doesnt make sense, to improve a bug and make a bug even nicer @Keader
