### ISSUE TITLE
CMake don't generate the CMakeCache txt and use default configuration

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#21192]
**Description:**

I have a problem for generate solution with Cmake and Dynamic Linking. I click on configure and choose "Visual Studio 15 2017 Win64", configuration :

1. CMAKE_INSTALL_PREFIX - my path
2. SCRIPTS - minimal-dynamic (for example but dynamic do nothing also)
3. WITH_DYNAMIC_LINKING - checked

now when i click on generate, cmake do not take my changes in the generate log i can view **Static** for SCRIPTS. So after with build, i don't have hotswap and any .dll

- Cmake 3.10.1
- Visual Studio 2017 (MSVC 19.12.25831.0)
- OpenSSL 1.0.2
- Boost 1.65.1
- MySQL 5.6

I don't have found similar issue, so i post here but maybe it's a personnal issue. @Naios you have an idea ?

**Branch(es):** master

**TC rev. hash/commit:**  4810e020ff0fb332ec8c6b138940dd167ac94a7b

**TDB version:**  720

**Operating system:** Windows 10 Pro (last update)

**Comment by tkrokli** [comment]
Testing your steps to reproduce your issue, now compiling and running
TrinityCore rev. 5f1e65599b9d 2018-01-06 19:57:33 +0100 (master branch) (Win64, Release, Dynamic)

I am using the same dependency software as you (I think):
- Cmake 3.10.1
- Visual Studio 2017 (MSVC 19.12.25831.0)
- OpenSSL 1.0.2n  7 Dec 2017
- Boost 1.65.1
- MySQL 5.6.38

My DB was rebuilt from scratch using rev. cecf50a924ed 2018-01-05 17:56:59 +0100 (master branch) (Win64, Release, Static)

from the Cmake output window:
```
CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
MSVC: Enabled shared linking
cotire 1.7.10 loaded.
Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.6/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.6/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 5.6/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe

* TrinityCore revision   : 5f1e65599b9d 2018-01-06 19:57:33 +0100 (master branch)

* Install core to        : C:/Trinity/Core/master

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (dynamic)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

 *** WITH_DYNAMIC_LINKING - INFO!
 *** Will link against shared libraries!
 *** Please note that this is an experimental feature!

Boost version: 1.65.1
Found the following Boost libraries:
  system
  filesystem
  thread
  program_options
  iostreams
Found OpenSSL library: optimized;C:/OpenSSL-Win64/lib/VC/ssleay32MD.lib;optimized;C:/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;debug;C:/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win64/include

* Script configuration (dynamic):
    |
    +- scripts_commands.dll
    |   +- Commands
    |
    +- scripts_custom.dll
    |   +- Custom
    |
    +- scripts_easternkingdoms.dll
    |   +- EasternKingdoms
    |
    +- scripts_events.dll
    |   +- Events
    |
    +- scripts_kalimdor.dll
    |   +- Kalimdor
    |
    +- scripts_maelstrom.dll
    |   +- Maelstrom
    |
    +- scripts_northrend.dll
    |   +- Northrend
    |
    +- scripts_outdoorpvp.dll
    |   +- OutdoorPvP
    |
    +- scripts_outland.dll
    |   +- Outland
    |
    +- scripts_pet.dll
    |   +- Pet
    |
    +- scripts_spells.dll
    |   +- Spells
    |
    +- scripts_world.dll
    |   +- World
    |
CXX target scripts cotired without unity build and precompiled header. Too few applicable sources.
CXX target scripts_commands cotired without unity build.
CXX target scripts_custom cotired without unity build and precompiled header. Too few applicable sources.
CXX target scripts_easternkingdoms cotired without unity build.
CXX target scripts_events cotired without unity build.
CXX target scripts_kalimdor cotired without unity build.
CXX target scripts_maelstrom cotired without unity build.
CXX target scripts_northrend cotired without unity build.
CXX target scripts_outdoorpvp cotired without unity build.
CXX target scripts_outland cotired without unity build.
CXX target scripts_pet cotired without unity build.
CXX target scripts_spells cotired without unity build.
CXX target scripts_world cotired without unity build.

Configuring done
Generating done
```
Completed compile results:
```
41>------ Build started: Project: INSTALL, Configuration: Release x64 ------
41>-- Install configuration: "Release"
41>-- Installing: C:/Trinity/Core/master/protobuf.dll
41>-- Installing: C:/Trinity/Core/master/common.dll
41>-- Installing: C:/Trinity/Core/master/database.dll
41>-- Installing: C:/Trinity/Core/master/proto.dll
41>-- Installing: C:/Trinity/Core/master/shared.dll
41>-- Installing: C:/Trinity/Core/master/bnetserver.exe
41>-- Installing: C:/Trinity/Core/master/bnetserver.conf.dist
41>-- Up-to-date: C:/Trinity/Core/master/bnetserver.cert.pem
41>-- Up-to-date: C:/Trinity/Core/master/bnetserver.key.pem
41>-- Installing: C:/Trinity/Core/master/game.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_commands.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_custom.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_easternkingdoms.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_events.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_kalimdor.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_maelstrom.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_northrend.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_outdoorpvp.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_outland.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_pet.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_spells.dll
41>-- Installing: C:/Trinity/Core/master/scripts/scripts_world.dll
41>-- Installing: C:/Trinity/Core/master/worldserver.exe
41>-- Installing: C:/Trinity/Core/master/worldserver.conf.dist
41>-- Installing: C:/Trinity/Core/master/connection_patcher.exe
41>-- Installing: C:/Trinity/Core/master/mapextractor.exe
41>-- Installing: C:/Trinity/Core/master/vmap4assembler.exe
41>-- Installing: C:/Trinity/Core/master/vmap4extractor.exe
41>-- Installing: C:/Trinity/Core/master/mmaps_generator.exe
========== Build: 41 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Result files in the core folder:

![master_dynamic_build](https://user-images.githubusercontent.com/4903600/34643584-ef374108-f326-11e7-8a34-4d9199d2c8e0.png)
```
World initialized in 1 minutes 32 seconds
TC>TrinityCore rev. 5f1e65599b9d 2018-01-06 19:57:33 +0100 (master branch) (Win64, Release, Dynamic) (worldserver-daemon) ready...

TC>_
```
Not sure why I did not reproduce your issue. Did I miss something important?

**Comment by DoctorKraft** [comment]
Hey @tkrokli, thanks for your investigation ! But apparently the problem is only on this desktop (fresh install). It's not related with Dynamic Linking but more. I can't change configuration in CMake Gui when i click on generate my configuration are automaticly override by default confguration in options.cmake

It's strange, i found nothing about this probable bug

**Comment by tkrokli** [comment]
Very well, thank you for the extra info. I tried to start off fresh as much as possible by rebuilding the DB and reinstalling the game client (still got an issue with logging in to my game client on TC `master`, but that is unrelated to your issue). Not sure exactly what your issue can be caused by, but I will make an attempt again tomorrow.

**Comment by DoctorKraft** [comment]
It's related only with CMake i think, tried different rev but nothing. If i build the solution with default configuration of CMake, all works well (db, binary, etc...). My problem it's with interface of Cmake i can't change the configuration (but i can change configuration in options.cmake and it's works)

**Comment by tkrokli** [comment]
OK, so this could possibly be an issue only with your local software and not with the source itself (I presume). If that is the case, I will give it another try tomorrow and see if I can replicate your issue. If not, I will consider this to be not an issue for TC and label this as such ( [Invalid-CannotReproduce] ). I am currently leaving this issue open to see if someone else are able to reproduce your issue, although this issue may be closed some time during the next week.

**Comment by DoctorKraft** [comment]
Ok found the problem, it's the software "Malwarebytes" and submodule "Malwarebytes anti-ransomware". He block the generation of CMakeCache.txt. I edit the title for a better archive if people get also this error

**Comment by Aokromes** [comment]
I wonder if this needs to be reported to malwarebytes people...

**Comment by tkrokli** [comment]
Hmm, strange. I did install Malwarebytes Anti-Malware myself, but only the freeware version (including the 14-day pro trial). Not sure if I have activated Anti-Ransomware in the software (most likely I have not done so). Thank you for the feedback, it will be interesting to test if that specific setting will make it easy to replicate your Cmake problem.
