### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by brecky** [TrinityCore/TrinityCore#21195]
TrinityCore/src/server/game/DataStores/DBCStores.cpp
**Description:**

make  error

CHANGEME 3.3.5, master or both

6345c1ca7f35+ 2018-01-07 13:13:46 +0100 (3.3.5 branch)

**TDB version:**  Last version

**Operating system:** Ubuntu 16.04 LTS

-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/gcc-6
-- GCC: SFMT enabled, SSE2 flags forced
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 6345c1ca7f35+ 2018-01-07 13:13:46 +0100 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /usr/local
* Install libraries to   : /usr/local/lib
* Install configs to     : /usr/local/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : No
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include

[ 98%] Linking CXX executable worldserver
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::unwind_extra_block(bool)':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1352: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
../game/libgame.a(DBCStores.cpp.o): In function `bool boost::re_detail_106400::is_combining<wchar_t>(wchar_t)':
/usr/include/boost/regex/v4/regex_traits_defaults.hpp:76: undefined reference to `boost::re_detail_106400::is_combining_implementation(unsigned short)'
/usr/include/boost/regex/v4/regex_traits_defaults.hpp:76: undefined reference to `boost::re_detail_106400::is_combining_implementation(unsigned short)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::cpp_regex_traits<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
../game/libgame.a(DBCStores.cpp.o): In function `boost::cpp_regex_traits<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::save_state_init::save_state_init(boost::re_detail_106400::saved_state**, boost::re_detail_106400::saved_state**)':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:107: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::find_imp()':
/usr/include/boost/regex/v4/perl_matcher_common.hpp:300: undefined reference to `boost::re_detail_106400::verify_options(unsigned int, boost::regex_constants::_match_flags)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::save_state_init::~save_state_init()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::perl_matcher(__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, __gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, boost::match_results<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > > >&, boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >)':
/usr/include/boost/regex/v4/perl_matcher.hpp:383: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::construct_init(boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags)'
../game/libgame.a(DBCStores.cpp.o): In function `void boost::re_detail_106400::raise_error<boost::regex_traits_wrapper<boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > >(boost::regex_traits_wrapper<boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::error_type)':
/usr/include/boost/regex/pattern_except.hpp:75: undefined reference to `boost::re_detail_106400::raise_runtime_error(std::runtime_error const&)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::error_string[abi:cxx11](boost::regex_constants::error_type) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:447: undefined reference to `boost::re_detail_106400::get_default_error_string(boost::regex_constants::error_type)'
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:449: undefined reference to `boost::re_detail_106400::get_default_error_string(boost::regex_constants::error_type)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:211: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1562: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aokromes** [comment]
wiki states 16.04 LTS is unusuported. try installing clang.

**Comment by brecky** [comment]
Idiote  C++ 6.3.0,  Boost version: 1.64.0 What is diferenc Ubuntu 17 vs LTS 
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get install gcc-6 g++-6
 gcc-6 --version | head -n 2
gcc-6 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519
Copyright (C) 2016 Free Software Foundation, Inc.

**Comment by brecky** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements
Processor with SSE2 support 
Boost ≥ 1.56
MySQL ≥ 5.1.0 
OpenSSL = 1.0.x 
CMake ≥ 3.2.0
GCC ≥ 6.3.0 or Clang  ≥ 3.5 (heavy recommended, especially on master branch)
zlib ≥ 1.2.7

**Comment by Aokromes** [comment]
since you like to paste, look a bit under that.

**Comment by brecky** [comment]
how-to-install-latest-gcc-on-ubuntu-lts.txt
https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

**Comment by brecky** [comment]
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/clang
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 6345c1ca7f35 2018-01-07 13:13:46 +0100 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /usr/local
* Install libraries to   : /usr/local/lib
* Install configs to     : /usr/local/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Looking for open
-- Looking for open - found
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Looking for MADV_FREE
-- Looking for MADV_FREE - not found
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- CXX target common cotired without unity build.
-- CXX target database cotired without unity build.
-- CXX target shared cotired without unity build.
-- CXX target game cotired without unity build.
-- CXX target authserver cotired without unity build.

* Script configuration (static):
    |
    +- worldserver
    |   +- Pet
    |   +- Events
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Spells
    |   +- Custom
    |   +- Commands
    |   +- World
    |   +- Kalimdor
    |   +- EasternKingdoms
    |   +- Northrend
    |
-- CXX target scripts cotired without unity build.

-- CXX target worldserver cotired without unity build.
-- Configuring done
-- Generating done


[ 98%] Built target scripts
[ 98%] Generating CXX prefix source src/server/worldserver/cotire/worldserver_CXX_prefix.cxx
[ 98%] Generating CXX prefix header src/server/worldserver/cotire/worldserver_CXX_prefix.hxx
[100%] Building CXX precompiled header src/server/worldserver/cotire/worldserver_CXX_prefix.hxx.pch
Scanning dependencies of target worldserver
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/TCSoap/TCSoap.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RASession.cpp.o
[100%] Linking CXX executable worldserver
../game/libgame.a(DBCStores.cpp.o): In function `perl_matcher':
/usr/include/boost/regex/v4/perl_matcher.hpp:383: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::construct_init(boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags)'
../game/libgame.a(DBCStores.cpp.o): In function `save_state_init':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:107: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::find_imp()':
/usr/include/boost/regex/v4/perl_matcher_common.hpp:300: undefined reference to `boost::re_detail_106400::verify_options(unsigned int, boost::regex_constants::_match_flags)'
../game/libgame.a(DBCStores.cpp.o): In function `~save_state_init':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o):/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: more undefined references to `boost::re_detail_106400::get_mem_block()' follow
../game/libgame.a(DBCStores.cpp.o): In function `bool boost::re_detail_106400::is_combining<wchar_t>(wchar_t)':
/usr/include/boost/regex/v4/regex_traits_defaults.hpp:76: undefined reference to `boost::re_detail_106400::is_combining_implementation(unsigned short)'
/usr/include/boost/regex/v4/regex_traits_defaults.hpp:76: undefined reference to `boost::re_detail_106400::is_combining_implementation(unsigned short)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o):/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: more undefined references to `boost::re_detail_106400::get_mem_block()' follow
../game/libgame.a(DBCStores.cpp.o): In function `void boost::re_detail_106400::raise_error<boost::regex_traits_wrapper<boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > >(boost::regex_traits_wrapper<boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::error_type)':
/usr/include/boost/regex/pattern_except.hpp:75: undefined reference to `boost::re_detail_106400::raise_runtime_error(std::runtime_error const&)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o): In function `boost::cpp_regex_traits<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::transform[abi:cxx11](wchar_t const*, wchar_t const*) const'
../game/libgame.a(DBCStores.cpp.o): In function `boost::cpp_regex_traits<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::transform_primary[abi:cxx11](wchar_t const*, wchar_t const*) const'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::cpp_regex_traits_implementation<wchar_t>::error_string[abi:cxx11](boost::regex_constants::error_type) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:447: undefined reference to `boost::re_detail_106400::get_default_error_string(boost::regex_constants::error_type)'
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:449: undefined reference to `boost::re_detail_106400::get_default_error_string(boost::regex_constants::error_type)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::unwind_extra_block(bool)':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1352: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
../game/libgame.a(DBCStores.cpp.o): In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<wchar_t const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:222: undefined reference to `boost::re_detail_106400::get_mem_block()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:211: recipe for target 'src/server/worldserver/worldserver' failed

**Comment by brecky** [comment]
Boost
wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
tar xvjf boost_1_64_0.tar.bz2
cd boost_1_64_0
./bootstrap.sh --prefix=/usr
./b2
./b2 install
