### ISSUE TITLE
Core/Player: combat aggro problem

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21204]
**Description:**

After recent combat changes, tank really can't hold aggro on boss

**Current behaviour:**

Boss goes on dps or healers after a few damage or heal.

**Expected behaviour:**

Boss should not go on healer's, dps too after a few heal or damage.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

57672fd

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by Treeston** [comment]
That's...really not descriptive at all. What tank? What healers? What spells are used?

**Comment by tje3d** [comment]
@Tresston tested with 4 tanks, Warrior + Pala + Druid + Dk ( so i can say its not about class ).
Right in combat start, Rogue's and Hunter's uses their TOT and MT, and tank will gain about 120% aggro.
The real problem is when a player stop doing damage, he should ( i guess ) lose 5% threat every seconds, and if tank taunts the boss, all players should lose some threats about 20-30%, but its not happen now.

**Comment by Treeston** [comment]
> The real problem is when a player stop doing damage, he should ( i guess ) lose 5% threat every seconds, 
???

That's not how anything has ever worked.

**Comment by tje3d** [comment]
@Treeston this is what i understand from my players 😁
i don't know but they all said its almost impossible to tank boss anymore

**Comment by Treeston** [comment]
I just loaded up a test instance. Threat generation (and modifiers, for tanks) work as expected, as do redirects.

**Comment by Faq** [comment]
@tje3d video from your tanks would be more informative.

**Comment by tje3d** [comment]
it seems this is invalid issue. thanks.

**Comment by Treeston** [comment]
Finally figured out what was going wrong here with some help from @Foereaper (thanks).

**Comment by Treeston** [comment]
013d456
