### ISSUE TITLE
Core/Spells: Sindragosa

### ISSUE THREAD

**Issue by jimteck** [TrinityCore/TrinityCore#21202]
Description: Sindragosa no correct work spells.

Current behaviour: Sindragosa no correct work spell stack ,  fly in texture and ignore ice block.

Branch(es): 3.3.5a

TC rev. hash/commit: TrinityCore rev. 509edd43123c+

Operating system: Windows 7

**Comment by tkrokli** [comment]
1. **Always search for open issue tickets containing your topic before opening a new issue ticket** :
    https://github.com/TrinityCore/TrinityCore/search?q=Sindragosa&state=open&type=Issues&utf8=%E2%9C%93
    At least 12 open issue tickets for "Sindragosa". **A)** Post in one of them, **or B)** Document your issue properly

2. **Never remove the issue template**, it is there for a reason.
    we need to ask you for enough information so we can investigate your issue, so please provide enough details.

3. Your core is not 100% clean, it contains extra non-TrinityCore stuff. Please test on clean core.
