### ISSUE TITLE
AEO

### ISSUE THREAD

**Issue by murdocmurat** [TrinityCore/TrinityCore#21201]
The Aoe buffs damage, actually anything that involves AoE is bugged.

TrinityCore rev. 58dad504da18

**Comment by Aokromes** [comment]
Update your core before reporting bugs.

**Comment by tkrokli** [comment]
Also not very useful issue ticket when removing the template and ignoring to provide practical info about spells, scenarios etc. Could just as well have sent a tweet on twitter about this ... :-P
