### ISSUE TITLE
[CRASH] CORE / Saurfang

### ISSUE THREAD

**Issue by jimteck** [TrinityCore/TrinityCore#21203]
Description:
After kill Saurfang in ICC server crash.

Steps to reproduce the problem:
Kill Saurfang and server crash.

Branch(es): 3.3.5 / 6.x (Select the branch(es) affected by this issue)
3.3.5

TC hash/commit:
509edd43123c+

TDB version:
335.63

Operating system:
Windows 7, Static

**Comment by tje3d** [comment]
Can't reproduce in 57672fd

**Comment by Aokromes** [comment]
If you have a crash supply crashlog.

**Comment by tkrokli** [comment]
Very likely caused by the extra non-TC content in the source code used in that core.

**Comment by jimteck** [comment]
Hm i compile fresh core 2018.01.01 non crash Saurfang, after 2018.02.02 all time after kill Saurfang  server crash.......

**Comment by tje3d** [comment]
@jimteck Follow this instruction to get a crashlog: [LINK](https://community.trinitycore.org/topic/1518-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?do=findComment&comment=47672)

**Comment by jackpoz** [comment]
still no crashlog
