### ISSUE TITLE
Worldserver Crash

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#21207]
**Description:**
Worldserver crash with using command .npc info

**Current behaviour:**
Worldserver crashes with the following command : .npc info
https://gist.github.com/Atis6/7de53c659c4211e66f4ca761a47869af

**Expected behaviour:**

Should not crash.

**Steps to reproduce the problem:**
1. Add npc: 26332
2. Target him, write: .npc info
3. Server crashes with info: (0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 274dede 2017-12-24 01:00:45 +0100 (master branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**  TDB 335.63 + updates

**Operating system:** Win10 Pro x64

**Comment by tje3d** [comment]
I can't reproduce 🤔

**Comment by Shauren** [comment]
Offending line
https://github.com/TrinityCore/TrinityCore/blob/274dede3dc89fa72ec1687d5ff454feba9849e47/src/server/scripts/Commands/cs_npc.cpp#L786

`handler->PSendSysMessage(LANG_NPCINFO_CHAR, target->GetName().c_str(), target->GetSpawnId(), target->GetGUID().GetCounter(), entry, faction, npcflags, displayid, nativeid);`
Argument types passed to formatting function: `char const*, uint32, uint32, uint32, uint32, uint32, uint32, uint32` - total 8 arguments, 1 string and 7 ints.
`ChatHandler::PGetParseString<unsigned int,unsigned int,unsigned int & __ptr64,unsigned int & __ptr64,unsigned int & __ptr64,unsigned int & __ptr64,unsigned int & __ptr64>`
Argument types passed to formatting function produced by crashing binary in this issue: `uint32, uint32, uint32, uint32, uint32, uint32, uint32` - total 7 arguments, 0 strings and 7 ints

Conclusion? This looks like a case of bad merge by the user (he has custom patches applied, for example you can find eluna in the log).
