### ISSUE TITLE
[NPC SPAWN] Murlocs in Swamp of Sorrow

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#2121]
Hash 6f8f82ce130e
No added content to the server

In Swamp of Sorrow in Misty reed strand there is 2 murlocs that are spawned in two different huts ( towers ) that you are not able to touch. It will keep sawing they are not in line of sight. If you fight near them and do an area effect, you could hit them. That could bug you by keeping you in combat.
##

**Comment by Aokromes** [comment]
Works on head.
