### ISSUE TITLE
SMART_ACTION_SET_ORIENTATION not set on SMART_EVENT_WAYPOINT_REACHED

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21219]
**Description:**
SMART_EVENT_WAYPOINT_REACHED calls actions probably earlier than waypoint is reached.

**Current behaviour:**
you have to add an action list with delayed SMART_ACTION_SET_ORIENTATION for it to work.

**Expected behaviour:**
SMART_ACTION_SET_ORIENTATION should be set when waypoint is reached 

**Steps to reproduce the problem:**
1. create SAI with WP
2. add action SMART_ACTION_SET_ORIENTATION on any WP reached
3. NPC does not set orientation

**Branch(es):** master

**TC rev. hash/commit:** 5b90538919cdf8b1984049bd203104128bec5bf2

**TDB version:**  TDB 720.00

**Operating system:** Win 7 x64

**Comment by dr-j** [comment]
Actually you dont need to use a timed action list you can use event linking the action to set orientation needs to be after the action to pauae/stop wp if you set orientation before it does not work

**Comment by Shauren** [comment]
Been telling this to everyone doing c++ scripts - do not launch new movement from MovementInform hooks
SAI is not an exception to this - it also uses MovementInform internally
