### ISSUE TITLE
Scripts/Icecrown Citadel: Professor Putricide - Volatile Ooze and Gas Cloud do not move

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21218]
**Description:**

Gas Cloud and Volatile Ooze do not move.

**Current behaviour:**

Gas Cloud and Volatile Ooze stay where they spawned.

![pp1](https://user-images.githubusercontent.com/5238989/34787622-239483e2-f64d-11e7-9f5f-3cb2bb7798de.png)
![pp2](https://user-images.githubusercontent.com/5238989/34787623-23c388ae-f64d-11e7-83cf-25baa8dc4038.png)

**Expected behaviour:**

They should move towards the target after they cast their main spell.

**Steps to reproduce the problem:**

1. .go creature 201294
2. wait for Professor Putricide to summon Ooze and Gas

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  9104144

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 17.10

**Comment by tkrokli** [comment]
Possible waypoints issue? If so, is it directly related to **Core/Movement: waypoint system issues** #20310 ?

**Comment by ccrs** [comment]
no

**Comment by Keader** [comment]
Can you check if https://github.com/TrinityCore/TrinityCore/commit/3a0cb90ea994e82dd8c70888fb847082f738d5dc#diff-a47695ccf2414a7d37d3256355bfd5d3R1246 returns true or false?
(i cant reproduce your issue)

**Comment by tje3d** [comment]
@Kaeder it returns TRUE

**Comment by tje3d** [comment]
@Keader it returns TRUE

**Comment by tje3d** [comment]
HACKFIX: change `NPC_GAS_CLOUD` and `NPC_VOLATILE_OOZE` ReactState from `REACT_PASSIVE` to `REACT_DEFENSIVE` or `REACT_AGGRESSIVE`

**Comment by tkrokli** [comment]
Which categories are affected by your issue, is the cause unknown so far?
- [ ] conditions
- [ ] gameobjects
- [ ] spells

Please list & link all involved NPCs and spells, mention if there is different behaviour depending on number of targets etc.

**Comment by tje3d** [comment]
@tkrokli This has worked for me so far and I think it has been broken in the last few weeks.
Changing ReactState fixes my issue.

I guess its not related to spells ( everything was fine in this side ).

Anyway i think the real fix is what i said in "Hackfix2"

**Comment by ariel-** [comment]
Definitely broken by Combat system rewrite. @Treeston can you take a look?

**Comment by Jildor** [comment]
Still valid this issue?
is for summon @Treeston xD

**Comment by Jildor** [comment]
Ok, so, if you can @Treeston ? 😘

**Comment by TheWinchesters** [comment]
I will add:
"If the target uses spells like Vanish, Volatile Ooze/Gas Cloud stops and does nothing."

**Comment by sawd14** [comment]
any script or sql to fix this?

**Comment by tje3d** [comment]
@sawd14 https://github.com/TrinityCore/TrinityCore/issues/21218#issuecomment-358268388

**Comment by illfated** [comment]
@sawd14 : I presume you are thinking of these lines:
https://github.com/TrinityCore/TrinityCore/blob/8cac5feb58a93d498ce4ec341c66ff41a7b7077f/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L324-L333

if I have understood @tje3d correctly, he is referring to these lines:
https://github.com/TrinityCore/TrinityCore/blob/8cac5feb58a93d498ce4ec341c66ff41a7b7077f/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp#L770-L777

**Comment by Riztazz** [comment]
DoMeleeAttackIfReady() fails after GetVictim() because passive creatures doesnt really have victim, write a copy of DoMeleeAttackIfReady() and instead of GetVictim() - use threatList instead
```
void DoOozeMeleeAttackWhateverBlaBlaBla()
{
// do melee attack stuff (copy from original function)
ThreatManager& mgr = me->GetThreatManager();
if (!mgr.IsThreatListEmpty())
return;

Unit* victim = mgr.GetCurrentVictim();

// rest of the function
}
```

**Comment by Jildor** [comment]
Should be fixed with https://github.com/TrinityCore/TrinityCore/commit/1d43003cfa29cee2c7921fdeaa5c1714d085c770
