### ISSUE TITLE
Some factions are neutral to each other while they should be friendly

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#21221]
**Description:**

after some tests, I found about an issue that affects spells that are suposed to hit friendly targets but the target is considered neutral instead.
Spell 67503 for example is suposed to give the npc and his friends a aura. However, the original npc for this aura (entry: 35077) has faction 2173 and should be friendly with the player. In this case with a worgen. Can be tested with any alliance character.

**Current behaviour:**

Spells that require friendly targets such as  SPELL_EFFECT_APPLY_AREA_AURA_FRIEND are not hitting friendly players if the caster has a faction that should be friendly but instead it is considered neutral coreside.

Edit: after research I got the cause of the issue:  when you try to get the reputation level of a player the core returns Rep - 1 for some reason. When my character is friendly with the faction but I use .lookup faction I see that the faction is neutral instead of friendly.

**Expected behaviour:**

Those named factions should be friendly to the player, not neutral

**Steps to reproduce the problem:**

1. spawn any npc that you wanna use as test dummy and use a alliance character
2. set the faction of the npc by using .npc set faction 2173 
3. add the rebel valor aura (.npc add aura 67503)
4. the npc and nearby creatures that are friendly to the faction should get the aura while the player does not get the aura while he should be considered friendly

**Branch(es):**
master in each aspect but probably 335 as well in some scenarios

**TC rev. hash/commit:** 
commit: 5b90538919cdf8b1984049bd203104128bec5bf2

**Comment by jackpoz** [comment]
let's start marking this issue as master-related untill someone or you confirm it happens on 335 too

**Comment by Killyana** [comment]
Tested on 4.3.4 and master and it works correctly.

**Comment by Ovahlord** [comment]
Yes, because I fixed it on 4.3.4

**Comment by Killyana** [comment]
On master also it works correctly, you must test with a worgen char.

**Comment by Ovahlord** [comment]
I did. Thats how I discovered the issue. During working on the prison quests

**Comment by Killyana** [comment]
As you can see here https://imgur.com/a/Weg5vCT  I just .npc add temp 35077
Then My character and npcs around get the aura 67503
