### ISSUE TITLE
Misc/DB Errors

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#21224]
**Description:**

DB Errors

**Current behaviour:**

There are some DB Errors. These errors aren't crashes the server.

- Spell Id 32065 has DBC ProcFlags 262144, but it's of non-proc aura type, it probably needs an entry in `spell_proc` table to be handled correctly.
- Spell Id 36659 has DBC ProcFlags 262144, but it's of non-proc aura type, it probably needs an entry in `spell_proc` table to be handled correctly.
- No suitable start date found for holiday 283.
- No suitable start date found for holiday 284.
- No suitable start date found for holiday 285.
- No suitable start date found for holiday 353.
- No suitable start date found for holiday 400.
- No suitable start date found for holiday 420.

**Expected behaviour:**

No DB Errors.

**Steps to reproduce the problem:**

1.  
2. 
3. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c50aefac963aca5daeacf409deca9692c6ca3924

**TDB version:**  335.63

**Operating system:** Win10

**Comment by ariel-** [comment]
#18542
