### ISSUE TITLE
[3.3.5] Non-combat pet follow speed and movement type

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21232]
**Description:**

Non-combat pet follow speed should increase or decrease based on the summoners current movement speed. This is currently not happening, leading to non-combat pets falling behind when the player mounts up as an example. 

This part of the issue however I am not sure whether it was added in Wrath or not, but I seem to remember that flying pets like drakes and moths would fly with you on a flying mount, but land-based non-combat pets would despawn(?). Currently the flying pets simply fly along the ground beneath the player. Might need verification on this specifically, might have been added in Cataclysm.

**Current behaviour:**

Non-combat pet speeds are static and never change based on the players current movement speed. Flying non-combat pets do not fly and follow the owner, but run along the ground beneath the player.

**Expected behaviour:**

Non-combat pet speeds should change based on the owners current movement speed, ie. speed up when mounted, slow down when unmounted. Flying non-combat pets should follow the owner when the owner mounts a flying mount.

**Branch(es):** 3.3.5 (Possibly master?)

**TC rev. hash/commit:** 46e1e35

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12817
