### ISSUE TITLE
Crash after cb9e72e

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21231]
**Description:**

Just had a crash during a raid (Obsidian Sanctum 10 man), so not really sure what exactly caused it, but the partial dump points to caster being a null pointer in Unit::CalculateAOEAvoidance in Unit.cpp, called from AuraEffect::HandlePeriodicDamageAurasTick in SpellAuraEffects.cpp

Have not yet been able to reproduce.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 46e1e35

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by funjoker** [comment]
No log no support.

Add Crashlog here.

**Comment by Foereaper** [comment]
What part of the crash log specifically? It is too long for me to put on pastebin and/or comment

**Comment by ariel-** [comment]
You can use gist.github.com if too long for pastebin
