### ISSUE TITLE
Core/Entities: increased damage to player since f1986c6 and 01537e1

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#21236]
Hi there,
The overall damage has been increased or the defense is lowered now, either way, all mobs do way more damage now than they did before, almost double values.
I tested for several hours already and I think it happened after either: https://github.com/TrinityCore/TrinityCore/commit/01537e1dfbd042b3608d5ac895009182026def00
or 
https://github.com/TrinityCore/TrinityCore/commit/f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a13d393c9544+ 2018-01-15 05:14:03 +0800 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

TrinityCore rev. a13d393c9544+ 2018-01-15 05:14:03 +0800 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows Server 2012

**Comment by tkrokli** [comment]
BTW, please report your findings from testing on clean core.
a13d393c9544+ is not a known commit in the TC branches.
