### ISSUE TITLE
Core/Spells: Intense Cold dot damage after recent spell changes

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21230]
**Description:**

Dot damage, as an example Intense Cold (48095) cast by Keristrasza (26723) in Heroic Nexus does ~10x (and increasing exponentially) more damage than it should (1 stack does ~1k damage, should do 100 damage per tick, 9 stack does 90k damage, should do 900). I have tried to see if it happens to any other spell, but I have yet to encounter it anywhere else.

**Current behaviour:**

Currently Intense Cold does exponentially more damage than it should, may or may not affect other spells as well.

**Expected behaviour:**

Intense Cold should be at a fixed damage rate, and not increase exponentially.

**Steps to reproduce the problem:**

1. Enter the Nexus
2. Aggro Keristrasza
3. Watch combat log as Intense Cold starts proccing

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 9104144

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by jackpoz** [comment]
@ariel- could you take a look into this ?

**Comment by jackpoz** [comment]
@Foereaper could you update to latest 335 commit and test it again ? yours is 3 days old

**Comment by Foereaper** [comment]
Definitely, I'll do it this evening

**Comment by Foereaper** [comment]
Tested with latest 46e1e35 and it is no longer doing 90k damage, it is however doing 11440 damage, which is a couple hundred more than it should (900 expected) but it's definitely a lot better.

**Comment by ariel-** [comment]
It's scaling with player spellpower (because aura caster is player itself)

**Comment by Foereaper** [comment]
Yeah for sure, now it's doable as long as people drop their stacks, before said update however it was nigh impossible heh.

**Comment by Keader** [comment]
@ariel-  same issue no? https://github.com/TrinityCore/TrinityCore/issues/13287

**Comment by ariel-** [comment]
Not the same, it's not done pct damage, but base flat damage (calculated from spell power bonus)
