### ISSUE TITLE
[3.3.5] MariaDB 10.2.9 supported?

### ISSUE THREAD

**Issue by Espionage724** [TrinityCore/TrinityCore#21243]
**Branch:** 3.3.5
**TC rev. hash/commit:**  1847555c8c9e630d4d5f1328f25c875f408be949
**Operating system:** Fedora Server 27 x86_64

Regarding the following two pull requests: https://github.com/TrinityCore/TrinityCore/pull/21241 and https://github.com/TrinityCore/TrinityCore/pull/21242

I installed the `mariadb-devel` and `mariadb-server` packages.

`mysql -V` reports: `mysql  Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1`

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements claims MySQL should be 5.1.0 or higher. According to https://github.com/TrinityCore/TrinityCore/pull/21241#issuecomment-357787110, it appears the version of MariaDB currently in Fedora is unsupported?

I'm not sure if the servers actually run yet (currently extracting maps), but the compile completed without issue after those two pull request changes.

**Comment by Treeston** [comment]
We don't officially support MariaDB, though you _should_ be able to run the core on it in theory.

**Comment by Shauren** [comment]
And that means he will also not be able to run it because we assert that runtime version matches compile version

**Comment by Treeston** [comment]
Your DB can be a MariaDB database, as long as you have library files for running the server, is my point.

**Comment by Espionage724** [comment]
Thanks for the info; I used MariaDB in the past without problem.

I think there's an official repo for regular MySQL; assuming they have the latest version availiable, should that be used?

**Comment by Aokromes** [comment]
if you use debian 9 following wiki it simply works.

**Comment by Espionage724** [comment]
On Fedora 27, adding the [MySQL Community Repo](https://dev.mysql.com/downloads/repo/yum/) and installing `mysql-community-devel` works.

Adding the repo replaces MariaDB.

**Comment by ariel-** [comment]
IMO there was problem on the packages, I remember having to pull original headers from MariaDB repo

**Comment by Infernales** [comment]
Hmm... I have MariaDB 10.1.30-1 on Arch Linux and it works fine with TrinityCore.
