### ISSUE TITLE
Core/Spells: "Placing Beacon Torch" (ID 17016) in quest "All Along The Watchtowers"

### ISSUE THREAD

**Issue by bblewittAG** [TrinityCore/TrinityCore#21244]
Description:
Accepted the quest from the quest starter and then headed of to the 4 towers and then used the item needed at the door of the towers and can't get the item to be used and cannot complete the objectives.

Current behaviour:
Go to any of the 4 towers and if you use the Beacon Torch item that is given to you by the quest giver at the tower but not the door it says required Andorhal Tower but then go to the door (slightly inside) it says You have no target. It gives a slight effect on the character but keeps all the charges on the beacon torch and nothing happens. If it is suppose to give a circle to place on the floor like a spell it does not and no objectives complete at any of the 4 towers.

Expected behaviour:
Go to the 4 towers and use the Beacon Torch at the doorway and it should give a objective complete for that tower. Not sure if it is suppose to leave a beacon on the floor.

Steps to reproduce the problem:
The steps I have taken to reproduce the problem from abandon the quest and get it again was.
1) Level 58 Human Paladin (not sure if that is relevant)
2) get the quest from the plaguelands
3) go to tower 1,2,3 or 4 as all of them do the same and use the beacon torch in the doorway outside of combat

Branch(es):
3.3.5a

TC rev. hash/commit:
TrinityCore rev. 6892404b270f+ 2017-04-26 04:20:38 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

TDB version: TDB 335.63

Operating system: Windows 10 (64bit)

Extra information:
I have looked on the issues list and there was 1 similar issue but closed and I added the second DB code and added it but same result.

30 minutes later: This issue was bugging me so much I looked into the DB and found out the beacon torch item has a spell id of 17016 but could not find the spell id of 17016 in the DB

**Comment by tkrokli** [comment]
As far as I can remember from using TrinityCore the last 4 years, the target spot for the torch is between 5m and 10m _outside of each tower doorway_. Try placing it exactly in the middle between where the ramp starts and the opening of the tower doorway.

BTW, your core is almost a year old, just a week after the release of TDB 335.63

**Comment by bblewittAG** [comment]
How do I get a new one then as the releases only go up to 335.63?
Going from 5yds from outside to the doorway still the same thing.

**Comment by tkrokli** [comment]
You can update your core by pulling the latest source to your own computer, then compile it. After compiling it, run Worldserver,exe to update your local DB automatically. Then run Authserver.exe -- start the game and log in. (Follow the wiki page instructions in https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977329/Windows+Core+Installation .)

I need to test your issue tomorrow when I get back home from work.

**Comment by bblewittAG** [comment]
The one I have currently I only pulled about mid dec 2017?
Okay

**Comment by bblewittAG** [comment]
@tkrokli or anyone else having this issue,
I remade the server from today (16/1/18) with a fresh worldserver and still the same issue now my TrinityCore Rev. d4e64950a155 2018-01-16 and I am still having this issue where the Beacon Torch is still not working on the location of the towers.

**Comment by ariel-** [comment]
Spell creates GameObject entry 176093 and then activates it (TARGET_GAMEOBJECT_NEARBY_ENTRY, has conditions in DB), the problem being we don't implement spells correctly, and try to search effect targets before effect execution (ie effect 0 would summon target of the spell but we finish cast early due to not finding spell target for effect 1)

```
ID - 17016 Placing Beacon Torch
=================================================
Description: Place in the doorway at one of Andorhal's ruined towers as a magical marker for future troop movement.
Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (4363,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x10000110 (SPELL_ATTR0_ABILITY, SPELL_ATTR0_HIDE_IN_COMBAT_LOG, SPELL_ATTR0_CANT_USED_IN_COMBAT)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 12) "Interact Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 5, MaxRangeFriendly = 5

CastingTime (Id 1) = 0,00
Duration: ID (22)  45000, 0, 45000
Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00000000
Requires Spell Focus 805
Chance = 101, charges - 0
=================================================
Effect 0: Id 50 (SPELL_EFFECT_TRANS_DOOR)
BasePoints = 1
Targets (47, 0) (TARGET_DEST_CASTER_FRONT, NO_TARGET)
EffectMiscValueA = 176093

Effect 1: Id 86 (SPELL_EFFECT_ACTIVATE_OBJECT)
BasePoints = 1
Targets (40, 0) (TARGET_GAMEOBJECT_NEARBY_ENTRY, NO_TARGET)
EffectMiscValueA = 5
```

**Comment by TecDian** [comment]
It worked some time ago. Question is: what has changed and can we 'change it back'?

**Comment by Aokromes** [comment]
More like maybe it was hackworking and now it needs to be fixed.

**Comment by Killyana** [comment]
The condition looks wrong for me, the activation effect on the torch do nothing, and if it's not the torch I don't see what gob must be activated.
``` sql
DELETE FROM `conditions` WHERE  `SourceEntry` = 17016 AND `SourceTypeOrReferenceId`=13;

**Comment by ariel-** [comment]
See my previous comment, condition was correct:

> Spell creates GameObject entry 176093 and then activates it (TARGET_GAMEOBJECT_NEARBY_ENTRY, has conditions in DB), the problem being we don't implement spells correctly, and try to search effect targets before effect execution

Needs #21395 first which addresses the effect execution issue

**Comment by Killyana** [comment]
Right, But why the torch must be activated? it doesn't make cense, generally gob activation are used to trigger animation via the gob or to despawn by the activation.

**Comment by ariel-** [comment]
Maybe it triggers some animation, or signals the gameobject to launch the quest credit, don't know

**Comment by Killyana** [comment]
The credit quest is given by the spell, and there's no animation displayed by any gob related to this quest or in this area.
