### ISSUE TITLE
DB/Quest: The Black Knight's Orders

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21248]
**Description:**

Due to recent waypoint system changes, SMART_TARGET_ACTION_INVOKER not works for SMART_EVENT_WAYPOINT_REACHED, So the target_type should be changed in order to get back quest_credit works again.

**Current behaviour:**

Quest does not giving credit.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 

947cb6a

**TDB version:**  335.63

**Operating system:** Debian 9

**Suggested Fix**:

```sql
-- Black Knights Order
UPDATE `smart_scripts` SET `target_type` = 23 WHERE `entryorguid` = 33519 and `id` = 1;
```

**Comment by offl** [comment]
> -- If I understand you're trying to fix this issue #20310 by modifying the existing SAI ?
-- Yes at the first
-- Bad Idea, the issue must be fixed on core side.
https://github.com/TrinityCore/TrinityCore/pull/21245#issuecomment-358089674

**Comment by tje3d** [comment]
@offl
> Treeston  Is it good idea to check EVENT_TYPE in SMART_TARGET_ACTION_INVOKER? so we can check if the event was SMART_EVENT_WAYPOINT_* then we use OWNER_OR_SUMMONER as target? 
And this would fix current SAI ( What Killyana  wants 😉 )

> Could we? Yes.
Should we? Hell no, that's utterly counter-intuitive.

So we have to edit the SAI

**Comment by Tauriella** [comment]
@tje3d 
Your Fix works fine 👍

**Comment by tkrokli** [comment]
@Killyana or @Aokromes : is this solution acceptable, or does it need research?
