### ISSUE TITLE
[CRASH] .npc add <pet creature id> crash

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#21247]
**Description:**
Executing command ".npc add 19668" and attacking the spawned npc triggers an assert
>D:\wow\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp:546 in PetAI::CanAttack ASSERTION FAILED:
me->GetCharmInfo()

**Steps to reproduce the problem:**

1. ".npc add 19668"
2. Attack the spawned creature
3. Crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3d7166c1c78e 2018-01-16 14:44:04 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.something

**Operating system:** Windows 10

[3d7166c1c78e_worldserver.exe_[16-1_20-42-30].txt](https://github.com/TrinityCore/TrinityCore/files/1636581/3d7166c1c78e_worldserver.exe_.16-1_20-42-30.txt)

**Comment by ariel-** [comment]
Only case of a scripted AI which inherits from PetAI, the checks added on startup don't cover scripted AI;
furthermore the Permissible checks are skipped by the factory if the creature has defined ScriptName.

I think considering the inheritance that script should be fixed (GetAI return nullptr when npc doesn't have owner)

**Comment by Laintime** [comment]
Can't confirm 
rev https://github.com/TrinityCore/TrinityCore/commit/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0
Ubuntu 16.04.3 LTS (3.3.5 branch) (Unix, Debug, Static)

**Comment by Mysterium** [comment]
Confirmed
rev. 1847555c8c9e+ 2018-01-15 15:42:41 +0100 (3.3.5 branch) (Win64, Release, Static)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/95a76a83fcbad0e52c6013697544e3c5691e7e24
