### ISSUE TITLE
Enabling AHbot seller on Linux causes Segmentation Fault

### ISSUE THREAD

**Issue by zranger1** [TrinityCore/TrinityCore#21256]
**Description:**
Enabling the Ahbot seller causes a Segmentation Fault a few seconds after server initialization has completed.

**Current behaviour:**
Using GDB, I traced this to line 322 in TrinityCore/src/server/game/Entities/Item/Item.cpp.  It currently reads:
```
if (spellInfo->HasEffect(SPELL_EFFECT_GIVE_ARTIFACT_POWER))
                if (uint32 artifactKnowledgeLevel = owner->GetCurrency(CURRENCY_TYPE_ARTIFACT_KNOWLEDGE))
                    SetModifier(ITEM_MODIFIER_ARTIFACT_KNOWLEDGE_LEVEL, artifactKnowledgeLevel + 1);
```
At this point in execution, owner has the value 0x0.  Calling GetCurrency causes the segmentation fault as it tries to access an unordered_map that does not exist.
 
**Expected behaviour:**
 
After looking through the call stack for a good place for a fix, I added a test for a valid owner to Item.cpp, changing line 322 to read:
```
 if (owner && spellInfo->HasEffect(SPELL_EFFECT_GIVE_ARTIFACT_POWER))
                if (uint32 artifactKnowledgeLevel = owner->GetCurrency(CURRENCY_TYPE_ARTIFACT_KNOWLEDGE))
                    SetModifier(ITEM_MODIFIER_ARTIFACT_KNOWLEDGE_LEVEL, artifactKnowledgeLevel + 1);

```
This has fixed the immediate problem.  There is no segmentation fault, and the auction house seller is now working.  I'm new to Trinity, and haven't spent enough time with the code yet to know if this is an architecturally correct fix, so I'm just reporting it as a bug for now. 

**Steps to reproduce the problem:**
Set 
1. Build fresh worldserver on Ubuntu 16.04
2. Set AuctionHouseBot.Seller.Enabled = 1 in worldserver.conf
3. Start worldserver and wait 'till it starts adding items to the AH.  The segmentation fault will occur within a minute or two.

**Branch(es):**
master 

**TC rev. hash/commit:** 
TrinityCore rev. d1bd21233953 2018-01-15 08:43:13 +0100 (master branch) (Unix, Debug, Static) 

**TDB version:**  Using World DB: TDB 720.00

**Operating system:** Ubuntu 16.04

**Comment by jackpoz** [comment]
could anyone try this on 335 branch too ?

**Comment by Aokromes** [comment]
on 3.3.5a and 4.3.4 no crash.

**Comment by Ba4ka** [comment]
enable on 3.3.5 branch rev https://github.com/TrinityCore/TrinityCore/commit/b8c281f497d5da2251b11ab09f182a23a5721a1c no crash

**Comment by tkrokli** [comment]
`CURRENCY_TYPE_ARTIFACT_KNOWLEDGE` is specific to the `master` branch.
Looks like this is about artifacts and related items or their spells.

**Comment by jackpoz** [comment]
@zranger1 would you like to open a Pull Request with the null check you mentioned ?

**Comment by zranger1** [comment]
I would!  Will open it soon as I get home tonight.
