### ISSUE TITLE
Core/Chat/Chat.cpp

### ISSUE THREAD

**Issue by Alysrazor** [TrinityCore/TrinityCore#21251]
**Description:**

Worldserver crashes when i try to execute a command.

**Current behaviour:**

https://gist.github.com/Alysrazor/07e1c2b452ea2f390ee48ea970502a82

**Expected behaviour:**

The command that is currently written should be executed.

**Steps to reproduce the problem:**

1. Step 1 Create a character,level doesn't matter
2. Step 2 Try to execute : .npc info, .modify faction, .gobject add
3. Step 3 Go to Worldserver.exe and try to execute a command,worldserver wont do nothing, and minutes later,Windows will display a window that worldserver stopped working.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 9c857a1b910c+ 2018-01-14 21:49:42 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  720.00DB

**Operating system:** Windows 7 32bits

**Comment by aquadeus** [comment]
tested right now, no crashes
