### ISSUE TITLE
Crash  boss_hadronox

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#21258]
**Description:**

Hi there
I have the following crash on Boss Hadronox
Thanks

Crash Log: https://gist.github.com/daddycaddy/f4d9e247bed9e331fe9b63ef9aa65567

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. d4e64950a155+ 2018-01-16 07:38:54 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)
TrinityCore rev. 3d7166c1c78e+ 2018-01-16 14:44:04 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows Server 2012

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp#L363
https://github.com/TrinityCore/TrinityCore/blob/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0/src/server/game/Entities/Unit/Unit.cpp#L659
https://github.com/TrinityCore/TrinityCore/blob/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L5211
https://github.com/TrinityCore/TrinityCore/blob/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L806
https://github.com/TrinityCore/TrinityCore/blob/3d7166c1c78e0e0011af840b76f3f5a8ccccaaa0/src/server/game/Spells/Auras/SpellAuras.cpp#L732
... and so on ...
