### ISSUE TITLE
Creatures dont do melee damage to another creatures

### ISSUE THREAD

**Issue by Alysrazor** [TrinityCore/TrinityCore#21261]
**Description:**

Creatures does 0 damage to another creature,but does damage with wowhead.com/spell=3018 = ranged attack.

**Current behaviour:**

When I spawn a guard like Stormwind guard near a hostile NPC,they attack each other but they do 0 damage.

**Expected behaviour:**

The creatures should do damage to another creature.

**Steps to reproduce the problem:**

1. Step 1 Spawn a Guard, for example spawn temporaly 68 (Stormwind Guard) and 5952 (Den Grunt) 
2. Step 2 Look if they do damage with auto attack melee. As i tested,they wont do melee damage.
3. Step 3 Now Spawn 5952 and a random hostile creature, level doesnt matter.
4. Step 4 First try to look ranged attack. Den Grunt will kill or  damage to the hostile creature. Next, try to test melee damage. They wont do damage.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 9c857a1b910c+ 2018-01-14 21:49:42 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  720.00DB

**Operating system:** Windows 7 32bits

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/pull/21043
