### ISSUE TITLE
Scripts/Ulduar: Flame Leviathan does not attack

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21265]
**Description:**

Flame Leviathan (Entry: 33113) no longer moves to pursue players, and is stationary throughout the entire fight. This has only recently changed, however I have not yet had the time to check which commits would affect the behaviour.

**Current behaviour:**

Flame Leviathan does not move at all.

**Expected behaviour:**

Flame Leviathan should move and pursue targets at random throughout the fight.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f189614

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by Infinito47** [comment]
Does not seem to work anymore. Flame Leviathan resets agro and stands still. Any damage done on him just keeps resetting it.

Tested on TrinityCore rev. 4da9321d2bdd+ 2018-02-15 12:23:05 +0100 (3.3.5 branch)

**Comment by Treeston** [comment]
Cannot reproduce on latest
![image](https://user-images.githubusercontent.com/14020072/36258950-df4edbe8-125c-11e8-887c-54a8c1b6bbdb.png)

**Comment by Treeston** [comment]
...make sure you remembered to `.gm off`...

**Comment by Infinito47** [comment]
Confirmed, works just fine. I tried it without a vehicle. My bad! sorry.
