### ISSUE TITLE
Scripts/Utgarde Keep: Ingvar the Plunderer

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21264]
**Description:**

Recently, Ingvar the Plunderer (Entry: 23954, SpawnID: 126026) has not worked as intended, and upon death instead of spawning the undead version of himself (Phase 2), either does not respawn at all or respawns as the human version of himself and resetting the fight (Returns to phase 1). This causes Utgarde Keep to be uncompleteable.

**Current behaviour:**

Currently does not enter phase 2, but resets upon completion of phase 1, causing Utgarde Keep to be uncompleteable.

**Expected behaviour:**

Upon killing him in Phase 1, he should respawn as an undead and proceed to phase 2.

**Steps to reproduce the problem:**

1. Enter Utgarde Keep and progress to the end
2. Kill the human version of the boss

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f189614

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by pedroevil51** [comment]
Re-open this issue, still resets on https://github.com/TrinityCore/TrinityCore/commit/8a45191e92a277ee9aafebbd0c1aa082c6be4298

**Comment by pedroevil51** [comment]
@Treeston

**Comment by pedroevil51** [comment]
@illfated thx, i will do that
