### ISSUE TITLE
Scripts/Naxxramas: Thaddius combat start delayed

### ISSUE THREAD

**Issue by Foereaper** [TrinityCore/TrinityCore#21269]
**Description:**

Thaddius in Naxxramas does not start casting spells or attack players for a long time after entering combat, not timed exactly but I'd guess it takes 45 seconds to a minute before his AI actually kicks in after his combat phase begins.

**Current behaviour:**

Thaddius does not start his spell casting or attacking until fairly late in the fight.

**Expected behaviour:**

Thaddius should start his attacks and spells right away.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f189614

**TDB version:**  TDB 335.63

**Operating system:** Windows Server 2012

**Comment by Keader** [comment]
I confess that i dont like how combat is handled right now.
I looked Thadius code some weeks ago, and looks weird to me.
Btw, @Treeston is the best guy to check it :)
