### ISSUE TITLE
Scripts/Black Temple: Reliquary of Souls

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#21276]
**Description:**
 I don't know if it is just me having this issue but the Reliquary of Souls in the Black Temple Raid appears broken.  There doesn't appear to be any way to start the encounter.

**Current behaviour:**
When trying to start the encounter, nothing happens.

**Expected behaviour:**
Should be able to aggro the first essence and thus start the encounter.

**Steps to reproduce the problem:**
1. Go to Reliquary of Souls 
2. Try to start encounter.  Nothing happens.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. fa3eb75 2018-01-20 00:15:48 -0300 (3.3.5 branch) (MacOSX, RelWithDebInfo, Static) (worldserver-daemon) ready...

**TDB version:**  TDB 335.63

**Operating system:** MAC OSX 10.13.2

**Comment by tkrokli** [comment]
Keader knows more about this instance than many others.
Summoning @Keader .

**Comment by Keader** [comment]
Someone is broking my babys... 😠

**Comment by Keader** [comment]
Ok @Treeston this is yours xD
UpdateVictim is always returning false.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp#L259

**Comment by Treeston** [comment]
does he have a threat list at that point?

**Comment by Keader** [comment]
Should has (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp#L159)

**Comment by Keader** [comment]
a3732756121be6d5621fb42bc7a71882a28f03a6
