### ISSUE TITLE
master - Love is in the Air : Orgrimmar world events and decorations not spawning

### ISSUE THREAD

**Issue by BahDumbBugs** [TrinityCore/TrinityCore#21284]
**Description:**

When World Event (ID: 8) Love is in the Air is enabled - The decor is not showing up in Orgrimmar. NPC chars do not spawn. i.e. Crown Chemical Company Event Merchants and Event NPC Detective Snap Snagglebolt are all missing.

**Current behaviour:**

Event decor and NPCs do not spawn. 

**Expected behaviour:**

When event starts, NPCs and all decor should spawn in Capital Cities. Have not seen any in Orgrimmar or Thunder Bluff. Will check other capital cities.

**Steps to reproduce the problem:**

1. Enable World Event 'Love is in the air'
2. Go to Capital cities
3. Observe locations where NPCs and Decor should spawn.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. a16d3209fd1c 2018-01-08 00:45:24 +0100 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  720.00

**Operating system:** Windows 10

**Comment by Ovahlord** [comment]
Not supported atm / not spawned

**Comment by BahDumbBugs** [comment]
Acknowledged. Just for the record then. Thanks @Ovahlord

**Comment by funjoker** [comment]
I try my best to get the datas.

**Comment by Kittnz** [comment]
i might have some info on this

**Comment by Faq** [comment]
@Kittnz can you share?

**Comment by Kittnz** [comment]
sure, check with me on irc

**Comment by meji46** [comment]
Closed by https://github.com/TrinityCore/TrinityCore/commit/bf9e47001d8cba3331bebbc7b8a107472fdc4050
