### ISSUE TITLE
Scripts/Icecrown Citadel: Sindragosa + adds not spawned/reset after Dreamwalker failure

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21286]
**Description:**

Icecrown: Sindragosa does not spawn/reset after a Dreamwalker failure.

**Expected behaviour:**

Sindragosa should be in her place.

**Steps to reproduce the problem:**

1. Go to Icecrown Citadel ( Sindragosa and Adds is in her place now )
2. .go creature 137747 ( Dreamwalker )
3. Start encounter and it should reset because you didn't complete other boss ( it happens even if you completed them )
4. After Dreamwalker reset go to Sindragosa ( .go xyz 4322 2484 211 )

Note: some players said it happens without Dreamwalker failure, but i can't find out how

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 013d456

**TDB version:**  335.63

**Operating system:** Ubuntu 17.10

**Comment by tje3d** [comment]
I think it's happen after 3bb33e3

**Comment by Gooyeth** [comment]
Confirm 013d456.

**Comment by Gooyeth** [comment]
I have done tests and sometimes it is invoked correctly, but for the most part it never works.

I clarify in case of doubt that they check the bug and it "works".

**Comment by tje3d** [comment]
The interesting thing is if a GM executes the .respawn Command, Sindra and All adds will respawns and everything works fine.

**Comment by tje3d** [comment]
@Treeston Sorry, can you take a look at this?

**Comment by Treeston** [comment]
Does this also happen if you progress through the instance normally?

**Comment by tje3d** [comment]
@Treeston yes its happen.
I see that it's happen after Dreamwalker boss finish.

**Comment by Strazhnik** [comment]
Confirmed on a7556ce

**Comment by zabiksandbox** [comment]
Yes. Its happen without dreamwalker failure.

**Comment by Treeston** [comment]
This one took a while to find, heh - turns out one of my refactors in 9f9507e6a1fd50a5ce643a4096c1712700244a61 was a tad too aggressive for its own good.

Fixed.
