### ISSUE TITLE
Faction related crash

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21288]
**Description:**

Very frequent crash, in the lapse of 1 hour occurs 3 to 4 times.

**Current behaviour:**

Apparently there is a failure to obtain faction value

Crashlog: https://drive.google.com/open?id=18L8NevI022IBPndvO2wOX_fJb2ORtOnF

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  013d456

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by joschiwald** [comment]
```code
{"success":false,"error":404,"message":"Not Found"}
```

**Comment by tje3d** [comment]
that server crashes too

**Comment by Gooyeth** [comment]
I tried to upload it in Gist, but it throws me error... u.u

**Comment by jackpoz** [comment]
You can drag and drop files here on github too

**Comment by Gooyeth** [comment]
Ready, link updated.

I did not upload it to Github because it only allows me 10 MB.

**Comment by ariel-** [comment]
Looks like an infinite recursion on CreatureGroup::MemberEngagingTarget

**Comment by ariel-** [comment]
I can't reproduce it using the data from crashlog:

``` 
groupAI = 3 '\003'
gy = 36
gx = 42
```

- .go cre 111997 (I'm guessing spawn, he's part of a group with groupAI == 3 and is within grid size (< 533.333 from grid (42, 36) in map 571)
- then waiting and/or spawning a hostile creature (ie .npc add temp 31139)
- formation goes to attack the hostile, no crash

**Comment by ariel-** [comment]
Looks related to dynspawn, since formation dead leaders/members can still be on map when they respawn, they aren't removed from the group, and new one is added
