### ISSUE TITLE
Crash of worldserver

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#21285]
**Description:**

The worldserver.exe crashes when I try to start it. It comes as far as

> Initialize data stores...

You can find the crash log here: https://gist.github.com/TecDian/4600c3b055232460c841048e6ba5d70d

Maybe I do something wrong and it is not an issue of trinitycore. I'd be very grateful for any kind of help.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** a3732756121b

**Operating system:** Windows 10

**Comment by Foereaper** [comment]
Recompile as debug and try again, that crash log has little to no info

**Comment by TecDian** [comment]
I really have to apologise. My mistake was that I used the wrong locale of the dbc files I extracted earlier. I forgot that I had installed all language versions of the client for testing purposes (only missing ones: both Chinese and the Korean client - if someone happened to have them anywhere?). Using the right dbc files according to the locale in the worldserver.conf solved my problem. Silly me!
