### ISSUE TITLE
Scripts/Spells: Lady Deathwhisper/Cult Fanatic - Vampiric Might

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21294]
**Description:**

The spell has a spelltrigger at 0.

**Current behaviour:**
NPC: http://www.wowhead.com/npc=37890
Spell: http://www.wowhead.com/spell=70674/vampiric-might

> AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 70674 proc, because the spell does not have an entry in Spell.dbc.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 514c847

**TDB version:** TDB 335.63

**Operating system:** Debian 9

**Comment by Killyana** [comment]
Effect2 of https://woehead.way-of-elendil.fr/?spell=70674 must trigger https://woehead.way-of-elendil.fr/?spell=70677 on each hit
It must be done by a cpp script.
