### ISSUE TITLE
[3.3.5] gcc g++ 6.3.0 compile warnings

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#21292]
**Description:**

Warnings in build

**Current behaviour:**

See description.

**Expected behaviour:**

Should not get warnings.

**Steps to reproduce the problem:**

Warnings:

/opt/atlassian/bamboo/xml-data/build-dir/WC-EWD-JOB1/src/common/Collision/Maps/TileAssembler.cpp: In member function ‘bool VMAP::TileAssembler::readMapSpawns()’:
/opt/atlassian/bamboo/xml-data/build-dir/WC-EWD-JOB1/src/common/Collision/Maps/TileAssembler.cpp:227:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread(&tileX, sizeof(uint32), 1, dirf);
                                                   ^
/opt/atlassian/bamboo/xml-data/build-dir/WC-EWD-JOB1/src/common/Collision/Maps/TileAssembler.cpp:228:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
             fread(&tileY, sizeof(uint32), 1, dirf);

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

514c847881a9fff504e90f1186a1209c0b8a3674

**TDB version:**  335.63

**Comment by Aokromes** [comment]
what compiler are you using? because ATM TC is warning free.

**Comment by Atis6** [comment]
GCC G++ 6.3.0

**Comment by tkrokli** [comment]
Could you also tell us your full compile command, including arguments / parameters?

**Comment by Atis6** [comment]
With default complile command.

**Comment by Aokromes** [comment]
i cannot reproduce them on debian 9 with gcc 6.3.0.

**Comment by tje3d** [comment]
c099174

**Comment by Aokromes** [comment]
That don't changes the reported file.

**Comment by Atis6** [comment]
Than dont know, i just simple using make -j4.

**Comment by Aokromes** [comment]
what os you use?

**Comment by Atis6** [comment]
Ubuntu 16.04 LTS

**Comment by tkrokli** [comment]
Aokromes, haven't you warned against using Ubuntu 16.04 LTS in default build before, unless certain develop packages are added?
