### ISSUE TITLE
DB/Gossip: Call to Arms! (Gameobject)

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21299]
**Description:**

* Add gossip text to gameobject "Call to Arms!"

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Call to Arms! --> Fix Gossip Text
UPDATE `gossip_menu` SET `TextID`=7274 WHERE `MenuID`=6121;

**Comment by tkrokli** [comment]
I presume this is the Revantusk Village (Hinterlands, horde) notice board?
Or is this the one in Stormwind?

**Comment by ZenoX92** [comment]
Yeah, it's the board from Revantusk Village.
