### ISSUE TITLE
DB/Conditions: Master Smith Burninate

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21298]
**Description:**

* Fix conditions for Master Smith Burninate's gossip texts (He should show a different gossip text only if player has completed quest "What the Flux?" and is exalted with Thorium Brotherhood)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Master Smith Burninate --> Fix gossip conditions
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=5962;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14,5962,7121,0,0,8,0,7722,0,0,0,0,0,"","Show gossip text 7121 if player has quest 'What the Flux?' rewarded"),
(14,5962,7121,0,0,5,0,59,128,0,0,0,0,"","Show gossip text 7121 if player is exalted with Thorium Brotherhood");

**Comment by tkrokli** [comment]
`3.3.5` branch only, see linked page below for details:
- https://wow.gamepedia.com/Master_Smith_Burninate#Quests
