### ISSUE TITLE
Quest "No Mere Dream" The Escort NPC Does Not Start Moving

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21291]
**Description:**

"Clintar Dreamwalker's Spirit" Does not start moving when a player take "No Mere Dream" quest.
Seems like a movement system issue.

**Expected behaviour:**

"Clintar Dreamwalker's Spirit" is Escort NPC and should walk his path

**Steps to reproduce the problem:**

1. .go creature 42360
2. take "No Mere Dream" quest

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 514c847

**TDB version:** TDB 335.63

**Operating system:** Ubuntu 17.10

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/20310
