### ISSUE TITLE
FreezerDetector:Handler

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21295]
**Description:**

Crash occurs for no apparent reason, it happens in Release and Debug.

`MaxCoreStuckTime = 120`

https://gist.github.com/Gooyeth/de7465acc70ed12342b0fc342e167962

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 514c847

**TDB version:**  TDB 335.63

**Operating system:** Debian 9 - **RAM**: 64 GB - Using NVMe

**Comment by ariel-** [comment]
Please use the contrib/debugger/crashreport.gdb to generate crashlogs on gdb, freeze crashes are useless to debug without all threads backtrace

**Comment by Gooyeth** [comment]
Ready, thanks.
[crash_freezer.txt](https://github.com/TrinityCore/TrinityCore/files/1656896/crash_freezer.txt)

**Comment by Aokromes** [comment]
Maybe the same as https://github.com/TrinityCore/TrinityCore/issues/21187

**Comment by Shauren** [comment]
@Aokromes definitely no
From that crash log it looks like map update simply took a long time, what is your freeze limit set to?

**Comment by ariel-** [comment]
> `MaxCoreStuckTime = 120`

**Comment by Gooyeth** [comment]
I have disabled the spell "Mirror Image" and the crash has decreased considerably, with stability for more than 8 hours without it.

**Comment by Shauren** [comment]
@Treeston  Could it be that new threat manager is very slow or has some infinite loop?

**Comment by Treeston** [comment]
Unlikely, though obviously possible.

**Comment by Treeston** [comment]
(ED: `MaxCoreStuckTime` is in what unit? 120 _seconds_?)

**Comment by Gooyeth** [comment]
Yes, seconds.

Even with more than 15 minutes no more response is obtained.

**Comment by jackpoz** [comment]
the only thread doing something there is calling CombatManager::SetInCombatWith(), it's probably not a coincidence

**Comment by Treeston** [comment]
@Gooyeth did it crash at all with mirror images disabled?

**Comment by Gooyeth** [comment]
The crash is still, but less frequently.

Without disable the spell, it was stable for 30 minutes - 1 hour.

**Comment by Treeston** [comment]
What sort of player count are we talking about? Would it be feasible to figure out what players were doing at the time of the crash?

**Comment by Gooyeth** [comment]
It is produced even with 10 active players, I could not say exactly what action they were performing.

**Comment by Treeston** [comment]
3203065 and 0ee1484 add some assertions that should catch one potential cause of this earlier (and more definitively) - please update and let me know what happens.

**Comment by Gooyeth** [comment]
Updated, let's try!

Thanks.

**Comment by Gooyeth** [comment]
@Treeston: https://gist.github.com/Gooyeth/cadaf2ed0900ecbef70bfc6a145979bc

**Comment by Treeston** [comment]
@Gooyeth do you happen to have the actual assert message too (displayed in the console)?

**Comment by Gooyeth** [comment]
No, but I can try again.

**Comment by Gooyeth** [comment]
@Treeston: I tried, but the error is not shown in the log.

**Comment by Treeston** [comment]
Hm, alright. Just the fact that this assertion triggers is very valuable information to me.

**Comment by Gooyeth** [comment]
@Treeston: Apparently it is an error with mounted npcs.

> 
> - Frenzied Gargoyle tried to add combatant Fordragon Knight to threat list, but this failed - potential infinite loop
> - Niffelem Frost Giant tried to add combatant Brunnhildar Warmaiden to threat list, but this failed - potential infinite loop

**Comment by Shauren** [comment]
mounted or vehicle passengers? big difference

**Comment by Treeston** [comment]
Those are vehicle passengers. Right now we don't allow `UNIT_MASK_ACCESSORY` passengers to have threat, but allow them to have combat - I wonder if we should just block them from having combat too.....

I'm not familiar with vehicle code. `UNIT_MASK_ACCESSORY` are permanent attachments, right (guns and whatnot?) I don't see any reason why they should ever have combat instead of the main vehicle body.

**Comment by Gooyeth** [comment]
@Shauren: Vehicle passengers, I still learn english 😕

**Comment by Treeston** [comment]
test after 1acfefb please

**Comment by Gooyeth** [comment]
@Treeston: 12 hours and 40 minutes of stability 👍

**Comment by Faq** [comment]
@Gooyeth with Mirror Image enabled, right?

**Comment by Gooyeth** [comment]
@Faq: Yes!

**Comment by Treeston** [comment]
@Gooyeth  any crashes since 1acfefb?

**Comment by Gooyeth** [comment]
@Treeston: Related no.

However, I have noticed that the mobs evade having low life, I do not know if it will be related.

**Comment by Treeston** [comment]
don't see how that could be related, open a new issue please if you can reproduce reliably
