### ISSUE TITLE
Incorrect Weapon Damage Calculation

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21308]
**Description:**

Sometimes, somehow, player weapon damage is reduced too much and a relog will fix the issue. It happens very rarely.

**Current behaviour:**

As i said before. Here is an example ( his weapon damage should be around 1100 ):

![rogue1](https://user-images.githubusercontent.com/5238989/35297521-7949f1c2-0094-11e8-8f92-e149b3d43d64.jpg)
![rogue2](https://user-images.githubusercontent.com/5238989/35297523-7a39eeca-0094-11e8-82ec-a34cb5fa5bae.jpg)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** aef5f8e

**TDB version:**  TDB 335.63

**Operating system:** Ubuntu 17.10

**Comment by ariel-** [comment]
Do you know how to reproduce? (ie possible buffs/debuffs you may have had at the time, if you were disarmed, etc.)

**Comment by shenhuyong** [comment]
Equip a weapon and an amor, then unequip the amor, now you can find your weapon damage disappeared.

**Comment by shenhuyong** [comment]
I fixed it, the prolem is in Player::_ApplyWeaponDamage from ver.f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb .
I moved 'if (!apply)' into 'for (uint8 i = 0; i < MAX_ITEM_PROTO_DAMAGES; ++i)', and changed 'SetBaseWeaponDamage(attType, MINDAMAGE, BASE_MINDAMAGE, 0);' to 'SetBaseWeaponDamage(attType, MINDAMAGE, BASE_MINDAMAGE, i);', changed 'SetBaseWeaponDamage(attType, MINDAMAGE, BASE_MAXDAMAGE, 0);' to 'SetBaseWeaponDamage(attType, MINDAMAGE, BASE_MAXDAMAGE, i);',  deleted 'SetBaseWeaponDamage(attType, MINDAMAGE, 0.f, 1);' and 'SetBaseWeaponDamage(attType, MAXDAMAGE, 0.f, 1);'.

**Comment by ariel-** [comment]
That's bad, secondary damage type must be 0 if no weapon present
