### ISSUE TITLE
DB/Conditions: Kalaran Windblade

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21303]
**Description:**

* Kalaran Windblade should show gossip option if player does NOT have item "Torch of Retribution"

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Kalaran Windblade --> Fix condition
UPDATE `conditions` SET `NegativeCondition`=1 WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=1323 AND `ConditionTypeOrReference`=2;

**Comment by tkrokli** [comment]
This query should probably be pushed together with one of the other DB fixes for Kalaran Windblade (although it is quite OK to post it as its own issue page).
