### ISSUE TITLE
Scripts/Eye Of Eternity: Malygos - Vortex Visual crash

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21315]
**Description:**

Crash generated in the spell "Vortex Visual".

**Current behaviour:**

https://gist.github.com/Gooyeth/3179a02da9326ed4b7016d15ffe807c0

**Branch(es):** 3.3.5

**TC rev. hash/commit:** db525a14011a9c0678094903ccb5f84248a91f2d

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by ariel-** [comment]
Invalid combat ref on threat list?

https://github.com/TrinityCore/TrinityCore/blob/db525a14011a9c0678094903ccb5f84248a91f2d/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1828-L1830

**Comment by Treeston** [comment]
Iterator invalidation is my guess.

**Comment by Treeston** [comment]
please check if this still happens after 4cb13af

**Comment by Treeston** [comment]
I reverted fix commit 6bbc95f in 4bd2d28, as I believe 65709e1c3081c97442792695cbc0f0826015d625 has made it unnecessary.

Regardless, I will reopen this issue for a few days pending further absence of reports.

**Comment by Treeston** [comment]
assuming fixed then
