### ISSUE TITLE
Gharsul the Remorseless

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#21326]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
Gharsul the Remorseless (86933) is spawned in Eversong Woods. (Unexpected Results is working.)
http://www.wowhead.com/npc=15958/gharsul-the-remorseless

**Expected behaviour:** 
Just delete it.

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/dc43a08d369ef9c52b3425754545385962a2ffde

**TDB version:**  
master TDB 720.00 + updates

**Operating system:**  Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Killyana** [comment]
It was removed: https://github.com/TrinityCore/TrinityCore/commit/c536207c674ce1f143d5136c44830b1444d37f32
Don't understand how the spawn is still on the DB.

**Comment by Aokromes** [comment]
bad cherry pick.
