### ISSUE TITLE
Karazhan Chess Event

### ISSUE THREAD

**Issue by Atis6** [TrinityCore/TrinityCore#21329]
**Description:**

Chess Event in Karazhan.

**Current behaviour:**

Chess event doesnt works. You cant move any creature.

**Expected behaviour:**

Should work.

**Steps to reproduce the problem:**

1. Go to Karazhan to Chess Event
2. Talk with any creature
3. Start it (doesn starts)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

1acfefb973895b0e3df3c8d9b43b920d2a1b5392

**TDB version:**  TDB 335.63

**Operating system:** Win10 x64

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/7938
