### ISSUE TITLE
Core/GameObject: quest/object missing from Strange Fruited Plant

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#21328]
**Description:**

The Strange Fruited Plant is unattached. The db world / gameobject_template is missing a GUID 219 492 record.
http://www.wowhead.com/object=6751/strange-fruited-plant

**Current behaviour:**

The plant is visible, has a quest, but can not be accepted/opened.

**Branch(es):**  Master

**TC rev. hash/commit:** 

TrinityCore rev. 9e8b4bd4e28b 2018-01-20 16:48:26 +0100 (master branch) (Win32, RelWithDebInfo, Static)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10

**Comment by Faq** [comment]
//www.wowhead.com/?quest=918 (Timberling Seeds) and //www.wowhead.com/?quest=919 (Timberling Sprouts) are prereq for this quest.

**Comment by tkrokli** [comment]
Good point, thanks for pointing out that part.
@Ravens62 : please check that you have done the prerequisite quest(s).

**Comment by Aokromes** [comment]
At least on 4.3.4...

[23:32:17] Quest accepted: The Glowing Fruit

**Comment by tkrokli** [comment]
Very well, anyone who can confirm that quest http://www.wowhead.com/quest=930/the-glowing-fruit is working on `master` ?

**Comment by Killyana** [comment]
Same faction and flags as 4.3.4
``` sql
SELECT * FROM gameobject_template_addon WHERE entry IN (6751);
```

**Comment by tkrokli** [comment]
So, very likely that OP has forgotten the quest relations, then.
Do we wait a bit more for confirmation or close this issue now?

**Comment by Aokromes** [comment]
on 4.3.4 there is no quest pre-requests, a comment on quest states you can do the 3 quests at once.

**Comment by Killyana** [comment]
Looks like a core issue related to gob interaction.

**Comment by funjoker** [comment]
will take a look tomorrow :D

**Comment by Ravens62** [comment]
I wrote that, but any interaction. In db's record of what is queststarter quest should offer. But the data on what that object is.

**Comment by funjoker** [comment]
![wowscrnshot_013018_172652](https://user-images.githubusercontent.com/846960/35577881-dd0615a8-05e2-11e8-9d9a-a25ec520b4ed.jpg)
![wowscrnshot_013018_172655](https://user-images.githubusercontent.com/846960/35577885-dfd04c36-05e2-11e8-9664-c09f489948d4.jpg)
![wowscrnshot_013018_172700](https://user-images.githubusercontent.com/846960/35577887-e24769ea-05e2-11e8-9b60-b99b1590cf32.jpg)

**Comment by Aokromes** [comment]
#15453
