### ISSUE TITLE
Core/GameObject/Spells: incorrect handling of spell executing GObjects

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21330]
**Description:**

The behavior in TC is totaly different to Retail and hacked.
This causes a lot of cosmetic and logic error which need to fixed by hacks again.
This issue is caused by TC spell system.
This system needs a rewrite to support gameobject casts.

I donno if there are other related issues. Or if there are other systems which need to be rewirten for this working properly.

**Current behaviour:**

At the moment, gameobjects which execute a spell, make the player cast the spell.
This way targets are incorrect and visuals are getting lost, because gameobjects in TC can't cast spells.
This causes many gobjects not to work properly.

**Expected behaviour:**
On Retail gameobjects are able to cast spells. Proven a lot of times in sniffs.

**Steps to reproduce the problem:**

1. Use some newer unhacked fixed gameobjects which should cast a spell on you.

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

0f5b8447d0c82120e5ff58eb1931e80911017cdc

**TDB version:**  
TDB 3.3.5
TDB 7.2.0

**Operating system:** Win

**Comment by ariel-** [comment]
Known issue, we currently summon a world trigger in place for gameobject casts. I'm currently working to revamp the existing systems but it'll take time

**Comment by funjoker** [comment]
Also Master Branch :D

**Comment by Treeston** [comment]
This is almost guaranteed to originate on 3.3.5, then make the CP to master eventually.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/18752 and  https://github.com/TrinityCore/TrinityCore/pull/18885
