### ISSUE TITLE
Client Crashing in Northrend.

### ISSUE THREAD

**Issue by bblewittAG** [TrinityCore/TrinityCore#21339]
Description:
I have just entered Northrend at level 70 and done 3 areas of it to reach 75 and now it is crashing on me most of the time.

Current behaviour:
Here is a crash report and it seams to be different most of the time it crashes.
https://gist.github.com/bblewittAG/a3b5665d2785ded1ce49eb98ac6146ea

Steps to reproduce the problem:
1. Just level 75 in dalaran or any other place in northrend
2. teleporting or flying it cause it.
3. walking around also does it.

Branch:
3.3.5a

TC rev. hash/commit:
TrinityCore rev. d4e64950a155 2018-01-16 07:38:54 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

TDB version:
335.63
Updated for the rev.

Operating system:
Win 10 64 bit

Notes:
I have no clue if this a common issue and have posted a thread on the forums and no one has gotten back to me about it and this is the latest crash I have gotten then my post.
If anyone can help me out on why this is happening most grateful.

**Comment by Aokromes** [comment]
[11:20:19] Map: 571 (Northrend) Zone: 4395 (Dalaran) Area: 4739 (Runeweaver Square) Phase: 4294967295
[11:20:19] X: 5804.149902 Y: 624.770996 Z: 647.767029 Orientation: 1.640000
[11:20:19] grid[42,33]cell[7,1] InstanceID: 0
[11:20:19]  ZoneX: inf ZoneY: inf
[11:20:19] GroundZ: 163.721085 FloorZ: 647.767944 Have height data (Map: 1 VMap: 1 MMap: 1)

**Comment by bblewittAG** [comment]
That means?
Sorry I am not sure how to read it.

**Comment by Aokromes** [comment]
I am on dalaran, no crash.

**Comment by bblewittAG** [comment]
Strange?
I have noticed it is random when it happens so is there anything to prevent it?

**Comment by tkrokli** [comment]
I will do my best to test your issue when I get back home.
Have you tested with old+new maps/vmaps/mmaps?

**Comment by tkrokli** [comment]
BTW, regarding your gist file log and
```
File:	.\MapMem.cpp
Line:	558

Requested 2287384 bytes of memory
```
https://www.google.com/search?dcr=0&source=hp&ei=k8RxWqakAYKasgHm244o&q=MapMem.cpp&oq=MapMem.cpp&gs_l=psy-ab.3..35i39k1j0i30k1.11803.11803.0.13010.3.1.0.0.0.0.84.84.1.1.0....0...1c.1.64.psy-ab..2.1.83.0...0.nH3Gq9Y9428

Lots of hits from retail players too, so I would troubleshoot my game client first if I were you.

**Comment by tkrokli** [comment]
Also worth noticing: it is your game client that crashes (wow.exe crash log), not your server. That in itself mostly disqualifies the problem as a TC issue.

**Comment by ariel-** [comment]
How much RAM do you have? it seems you don't have enough to run both server and client at the same time

**Comment by Infinito47** [comment]
Are you running the WOD model patch by any chance? I heard many reports about it crashing in Dalaran.

**Comment by Killyana** [comment]
>Requested 2287384 bytes of memory
You're probably using a client patch that uses too much ram, just google: "large-address-aware" and use it to allow wow.exe to handle more than 2 gigabytes without crashing.

**Comment by Shauren** [comment]
2287384 is merely 2MB, i think his system is just out of memory
