### ISSUE TITLE
[7.x] DB/SAI: Reworked SAI for Small Crag Boar

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#21337]
**Description:**

http://www.wowhead.com/npc=708
http://www.wowhead.com/spell=44530

Does not work SAI

**Current behaviour:**

Effect 1 | Charge
Effect 2 | Apply Aura: Mod Damage Done (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)
Effect 3 | Apply Aura: Increase Run Speed
Range | 30 yards (Medium)

**Expected behaviour:**

``` sql
-- DB/SAI: Reworked SAI for Small Crag Boar

UPDATE `smart_scripts` SET `event_type`=9, `event_param1`=5, `event_param2`=30, `event_param3`=1500, `event_param4`=2000, `action_param2`=1, `target_type`=2, `comment`='Small Crag Boar - Within 5-30 Range - Cast \'Boar Charge\' (No Repeat)' WHERE `entryorguid`=708 AND `source_type`=0 AND `id`=0 AND `link`=0;
```
**Branch(es) and other:**

Branch(es): 7.3.2 (Tested)
TC hash/commit: dc43a08
TDB version: TDB 720.00

**Comment by tkrokli** [comment]
Since you are presenting separate solutions to each branch, I split the 2 queries up for you.
I also removed the apostrophes around the number values in the 7.3.2 query,
as well as adding a missing `DELETE FROM` query to your 3.3.5 solution.

**Comment by Kodekc** [comment]
@tkrokli Thanks!

**Comment by offl** [comment]
I'm 100% sure he didn't use that spell in 3.3.5.

**Comment by Kodekc** [comment]
@offl https://web.archive.org/web/20110719135256/http://www.wowhead.com:80/npc=708#abilities

Earlier versions I do not have

**Comment by offl** [comment]
https://web.archive.org/web/20100417075326/http://www.wowhead.com:80/npc=708

**Comment by Kodekc** [comment]
Poorly displays the page. But most likely you are right

**Comment by tkrokli** [comment]
Even though the TC sniff archive goes back to patch 3.3.0a Build 11159, the spell Boar Charge (44530) was not sniffed until patch 4.3.3 Build 15354.

http://www.wowhead.com/spell=44530/boar-charge#changelog suggests that it could have appeared either in patch 4.1.0 (Thu May 05 2011) Build 13914 or slightly before (I am guessing 4.0.6).

**Comment by Kodekc** [comment]
Updated based on discussion results

**Comment by tkrokli** [comment]
Although it is not a fact per se, it is fun to notice how it is described on https://wow.gamepedia.com/Small_Crag_Boar

"Lately they have been becoming so aggressive that hunters in the area find it no fun to go boar hunting anymore. Talin Keeneye in Coldridge Valley hires young Alliance recruits who are willing to reduce the population."
