### ISSUE TITLE
[3.3.5] Anti-magic Shell

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21343]
**Description:** Some spells is ignoring Anti-magic shell.

**Current behaviour:** Spells like Shadowflame (with Glyph of Shadowflame), Spell Lock (warlock pet) is ignoring anti-magic shell and applying effects anyway.

**Expected behaviour:** Old behavior cause "Immune" message when this spells is casted in a target with AMS.

**Steps to reproduce the problem:**

1. Put 2 characters in duel
2. Check that spell effects will hit DK with AMS (

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 21ad8761e9a6621b58262f89da9a0052d3aa0e6a

**Comment by Laintime** [comment]
it's afrer change for spell,sum @ariel-

**Comment by Golrag** [comment]
IIRC isn't this because of spell_linked_spell table ? Spell gets cast and the linked spell gets cast by the target instead of the caster of the original spell. It's been a while since I looked at that (see #8996)

**Comment by Keader** [comment]
I found where is the problem, but idk how correct fix.

Here:

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L7711

Is returning `SPELL_AURA_NONE`, making Shadowflame skip school check (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L7717-L7724)

**Comment by Keader** [comment]
It should be: (I think lul)

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 4817ef5151..ad2df41131 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -7713,16 +7713,16 @@ bool Unit::IsImmunedToSpellEffect(SpellInfo const* spellInfo, uint32 index, Worl
             SpellImmuneContainer const& list = m_spellImmune[IMMUNITY_STATE];
             if (list.count(aura) > 0)
                 return true;
+        }
 
-            if (!spellInfo->HasAttribute(SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE))
-            {
-                // Check for immune to application of harmful magical effects
-                AuraEffectList const& immuneAuraApply = GetAuraEffectsByType(SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL);
-                for (AuraEffectList::const_iterator iter = immuneAuraApply.begin(); iter != immuneAuraApply.end(); ++iter)
-                    if (((*iter)->GetMiscValue() & spellInfo->GetSchoolMask()) &&                   // Check school
-                        ((caster && !IsFriendlyTo(caster)) || !spellInfo->IsPositiveEffect(index))) // Harmful
-                        return true;
-            }
+        if (!spellInfo->HasAttribute(SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE))
+        {
+            // Check for immune to application of harmful magical effects
+            AuraEffectList const& immuneAuraApply = GetAuraEffectsByType(SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL);
+            for (AuraEffectList::const_iterator iter = immuneAuraApply.begin(); iter != immuneAuraApply.end(); ++iter)
+                if (((*iter)->GetMiscValue() & spellInfo->GetSchoolMask()) &&                   // Check school
+                    ((caster && !IsFriendlyTo(caster)) || !spellInfo->IsPositiveEffect(index))) // Harmful
+                    return true;
         }
     }
 
```

**Comment by Keader** [comment]
In all cases has SPELL_ATTR3_IGNORE_HIT_RESULT, so i realy think that should ignore AMS.
I reported it based in old behavior, but right now i'm not sure if is or not a bug.
If someone can find any good prof of it, i can reopen, but until then closed.
