### ISSUE TITLE
[Master] Core/Misc: Bank of Materials can not be pay

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#21349]
**Description:**

No scripts. No implementation

**Expected behaviour:**

The ability to buy and store items in it

**Steps to reproduce the problem:**

.go cre id 44852 (Horde)
.go cre id 43819 (Alliance)

**Branch(es):**

Master

**TC rev. hash/commit:** 

Branch(es): 7.3.2 (Tested)
TC hash/commit: dc43a08
TDB version: TDB 720.00

**Comment by Aokromes** [comment]
#16077

**Comment by Kodekc** [comment]
I did not find it through search

**Comment by Aokromes** [comment]
1st match searching for bank.
