### ISSUE TITLE
Proc function - TriggerAurasProcOnEvent - with nonsensical logic

### ISSUE THREAD

**Issue by killerwife** [TrinityCore/TrinityCore#21344]
TriggerAurasProcOnEvent
If you open this function, you do the folowing:
    if (disableProcs)
        SetCantProc(true);

but inside the loop you do
        if (spellInfo->HasAttribute(SPELL_ATTR3_DISABLE_PROC))
            SetCantProc(false);

so even if globally for the whole set of procs, a disable procs spell appears, it turns on the proccing for subsequent procs
I have no idea whether this is correct or not, but it doesn't sound valid to me logically.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a217c0be922f7a14bf78acb87aaaef5bc99afe95

**Comment by Shauren** [comment]
@ariel-

**Comment by ariel-** [comment]
Nah it's good. SetCantProc is like a "stack", it just increases m_procDeep which is an integer, so no, it won't override the globally setted SetCantProc for triggered spells.
