### ISSUE TITLE
[3.3.5] Stuck at Connected.

### ISSUE THREAD

**Issue by gladiator889** [TrinityCore/TrinityCore#21346]
**Description:**

Hi. 

First of all, thanks for all your effort to make TC perfect.

I pull the latest version of TC thru github  about 2 weeks ago, and complied with VS2017.
Everything has been running fine, but I have one issue now.
When I start the worldserver.exe, it works very good. But, users are stuck at Connected when login if something is triggered, sometimes after 3 days from the server start, sometimes 5hours from the server start.. 

I guess if my worldserver,conf is wrong, no one could log in all time.

No crash messages on TC console
No Error log / messages / anything.
On server side, everything looks fine.

What should I try to fix this?

**Current behaviour:**

Like above

**Expected behaviour:**

Everyone should be able to log in as always.

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
Worldserver : TrinityCore rev. f50a33341892+ 2018-01-12 00:07:29 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver_daemon)

Auth : TrinityCore rev. f50a33341892+ 2018-01-12 00:07:29 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

**TDB version:**  TDB 335.63

**Operating system:** WIN 2016 SERVER

**Comment by tkrokli** [comment]
I have never seen this issue personally on 3.3.5 _unless I managed to mess up my personal configuration by myself_. Default configuration has always worked locally, since I almost always run my servers on my Windows PC.

**Comment by tkrokli** [comment]
Please also note that this is more likely to be a personal issue and not a source code issue, so it does not actually belong here in the issue tracker (unless someone else can confirm the exact same problem, using nothing but pure, unchanged and verified TrinityCore source code and with a standardized network setup for external connections.

**Comment by Treeston** [comment]
> TrinityCore rev. f50a333*+*
We do not support modified cores. Please ensure you can replicate the issue on an unmodified latest core.
