### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by Mysterium** [TrinityCore/TrinityCore#21340]
**Description:**

Worldserver crashes after login

**Current behaviour:**

After i compiled a fresh core and tried to login, this error crashes the server:
Attempt set value to non-existed value field: 3041 (count: 1326) for object typeid: 4 type mask: 25

https://gist.github.com/Mysterium/43026aac7bd35079eea0954a7aab7048
Screen: https://imgur.com/a/pZi89

**Expected behaviour:**

no crash & login? xD

**Steps to reproduce the problem:**

1. compile fresh core
2. batch fresh DB
3. login with any char

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**TDB version:**   TDB 335.63

**Operating system:** Windows Server 2012

**Comment by tkrokli** [comment]
Looks like the crash could be related to PvP Arena Team activity?

**Comment by Mysterium** [comment]
Okay, strange
Deleted all arena teams and now its working..
Closed.
