### ISSUE TITLE
Crash in PlayerCreateInfoSkill

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21347]
**Description:**

The only special thing about my server is i've created some char's with character dump load.
I had some forbidden skill errors too ( is there anyway to fix this? )

**Branch(es):** 3.3.5

**TC rev. hash/commit:** a217c0b

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Crash log:** [crash1.log](https://github.com/TrinityCore/TrinityCore/files/1689522/crash1.log)

**Comment by Shauren** [comment]
`{SkillId = 54648, Rank = 786}`
Values look sort of valid if swapped, broken dump input?

**Comment by tje3d** [comment]
@Shauren it seems to be. Is there anyway to delete skill and prevent crash?

**Comment by Aokromes** [comment]
IMHO core must be safe of crash because bad db data.

**Comment by jackpoz** [comment]
> I had some forbidden skill errors too ( is there anyway to fix this? )

could you post the log about forbidden skills ?

**Comment by jackpoz** [comment]
By looking at Player.cpp line counts it looks like you have some custom changes applied to Player.cpp, could you please check that ?

**Comment by tje3d** [comment]
@jackpoz yes exactly and the crash happens when a player with changed faction logouts in bg.

**Comment by Shauren** [comment]
This is a crossfaction bg crash.

**Comment by jackpoz** [comment]
@tje3d next time please include in the issue description the link to your public fork and branch with all the custom changes applied
