### ISSUE TITLE
[Icecrown Citadel] Bosses must enter combat in their aggro radius

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#2134]
Core Rev: https://github.com/TrinityCore/TrinityCore/commit/360f0534ce857d89e792ad3c493c412411b49f53
Full DB: TDB_335.11.41_2011_06_18
DB Updates up to: 2011_06_26_07_world_spell_script_names.sql

These bosses don't start attacking until you hit them:
Lord Marrowgar
Lady Deathwhisper
Deathbringer Saurfang
Festergut
Rotface
Professor Putricide
Blood Prince Council

In retail these bosses start attacking when you reach their aggro radius.

**Comment by Nyeriah** [comment]
Actually Marrowgar attacks you if you move up him https://www.youtube.com/watch?v=tbIxK3_woKo&feature=youtu.be

**Comment by Rushor** [comment]
thx for these infos

**Comment by P-Kito** [comment]
My bad

**Comment by Aokromes** [comment]
Fixed already.
