### ISSUE TITLE
When creature run away in fear to nearest ally creature. It comes back alone still

### ISSUE THREAD

**Issue by kaldown** [TrinityCore/TrinityCore#21354]
**Description:**

When creature run away in fear to nearest ally creature. It comes back alone still.
But it could be because this creature has an evade state.
Possible cross with https://github.com/TrinityCore/TrinityCore/issues/21353

**Current behaviour:**

Mob asking for help, but none of it allies won't help him (bu should)

**Expected behaviour:**

Creature should get back with an allies if some of them were near.

**Steps to reproduce the problem:**

Try to fight

.go creature 9739 but don't kill him
it will turn back to a place, with NO ally, even if it were near.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB_full_world_335.63_2017_04_18 Version of the TrinityCore database

**Operating system:** Debian 9.0 OS

**Comment by tkrokli** [comment]
@Kittnz - what is different here from your issue **[3.3.5] Creature that flee and seek assistance don't aggro the npc it runs to.** **#21279** ?

**Comment by tkrokli** [comment]
Please also check your **worldserver.conf** settings (default settings below):
```
CreatureFamilyFleeAssistanceRadius = 30
CreatureFamilyAssistanceRadius = 10
CreatureFamilyAssistanceDelay = 1500
CreatureFamilyFleeDelay = 7000
```

**Comment by kaldown** [comment]
Yeap, thanks for notifying about worldserver.conf
And this is a duplicate of https://github.com/TrinityCore/TrinityCore/issues/21279
