### ISSUE TITLE
Dynamic script compile failed

### ISSUE THREAD

**Issue by kaldown** [TrinityCore/TrinityCore#21350]
**Description:**

`make` failed when trying to compile with the following options:
according [Using the script hotswapping system](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/18874377/Using+the+script+hotswapping+system#Usingthescripthotswappingsystem-Enablingthehotswapsystem)
`cmake ../ -DCMAKE_INSTALL_PREFIX=/XXX/WoW/server_dynamic -DWITH_WARNINGS=1 -DSCRIPTS=dynamic`

**Current behaviour:**
```
[ 16%] Linking CXX shared library libcommon.so
/usr/bin/ld: /usr/local/lib/libcrypto.a(cryptlib.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/common/CMakeFiles/common.dir/build.make:1148: recipe for target 'src/common/libcommon.so' failed
make[2]: *** [src/common/libcommon.so] Error 1
CMakeFiles/Makefile2:934: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Expected behaviour:**

Should be compiled, as well as without `-DSCRIPTS=dynamic` option applied.

**Steps to reproduce the problem:**

```
cd /home/kaldown/projects/TrinityCore/build
cmake ../ -DCMAKE_INSTALL_PREFIX=/XXX/WoW/server_dynamic -DWITH_WARNINGS=1 -DSCRIPTS=dynamic
make -j4
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

* TrinityCore revision   : a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch)                    
* TrinityCore buildtype  : RelWithDebInfo

**Operating system:** Debian 9.0 OS

In addition.
If it would be not possible to fix an issue -> I must go for static script linking.
So then. If I change something in script - what are the minimal moves I should do to test script in-game?

**Comment by tkrokli** [comment]
Have you tested without `-DWITH_WARNINGS=1` (using `-DWITH_WARNINGS=0` instead) or tried compiling in Release build instead of RelWithDebInfo ?
Dynamic build is considered experimental, so you should avoid warnings, if possible.
Then again, we need feedback from other Linux users like @Aokromes .

**Comment by Aokromes** [comment]
[100%] Built target worldserver

real    16m31.518s
user    48m32.788s
sys     3m2.888s

cannot reproduce.

**Comment by kaldown** [comment]
I think that's because of OpenSSL. Could you please share your full version of it, @Aokromes ?
Thanks.

**Comment by Aokromes** [comment]
I use the one on wiki.

**Comment by kaldown** [comment]
`/usr/bin/ld: /usr/local/lib/libcrypto.a(cryptlib.o):` it's a strange error output. Maybe I'm wrong, but, isn't it should be using a lib I've pointed while CMAKE ?
```
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/kaldown/WoW/server_dynamic -DWITH_WARNINGS=1 -DOPENSSL_LIBRARIES=/usr/local/openssl-1.0.2n/lib -DOPENSSL_INCLUDE_DIR=/usr/local/openssl-1.0.2n/include -DSCRIPTS=dynamic
```
Why won't `ld` use right path which is `usr/local/openssl-1.0.2n/lib`
```
ls /usr/local/openssl-1.0.2n/lib/lib*                                               
/usr/local/openssl-1.0.2n/lib/libcrypto.a  /usr/local/openssl-1.0.2n/lib/libssl.a
```

Ok I'll try to do exactly what on [requirements](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130068/Requirements), but strange that, I already have different libssl versions

```
dpkg -l | grep -i libssl | awk '{print $2}'
libssl-dev:amd64
libssl-doc
libssl1.0.0:amd64
libssl1.0.2:amd64
libssl1.1:amd64
libssl1.1:i386
```

**Comment by kaldown** [comment]
Alright.
Prev posts doesn't help.
So I up a vagrant and did all things from requirements - and it works.
I think that an issue shouldn't be closed, because even with strict options of an openssl version usage, building fails as I mention above.
I don't know how to fix this, and actually don't know what is linker (`ld`) actually means and how it works. Will investigate into, and hopefully suggest a fix.

**Comment by kaldown** [comment]
Ok then. I've solved this.

```
# openssl preparations
wget https://www.openssl.org/source/openssl-1.0.2n.tar.gz
gzip -d openssl-1.0.2n.tar.gz
cd openssl-1.0.2n
export CFLAGS=-fPIC
./config shared --openssldir=/usr/local/openssl-1.0.2n
make
make test
make install

# TC preparations
cd TrinityCore/build
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/kaldown/WoW/server_dynamic -DWITH_WARNINGS=1 -DOPENSSL_LIBRARIES=/usr/local/openssl-1.0.2n/lib -DOPENSSL_INCLUDE_DIR=/usr/local/openssl-1.0.2n/include -DSCRIPTS=dynamic -DOPENSSL_ROOT_DIR=/usr/local/openssl-1.0.2n -DOPENSSL_CRYPTO_LIBRARIES=/usr/local/openssl-1.0.2n/lib/libcrypto.a -DOPENSSL_SSL_LIBRARIES=/usr/local/openssl-1.0.2n/lib/libssl.a

make
make install
```
pay attention that you must declare all other flags in addition to ones noticed in [installation instructions](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977309/Linux+Core+Installation)
openssl should be configured with `'shared' and with CFLAGS=-fPIC`
otherwise you'll fail on linking libcommon.so

**Comment by rbedfordpro** [comment]
@kaldown did you ever run into: (granted, this is on AzerothCore)...
I followed your steps and get this when running cmake:
src/common/Cryptography/OpenSSLCrypto.cpp:27:17: fatal error: use of undeclared identifier 'CRYPTO_LOCK'
    if (mode && CRYPTO_LOCK)
