### ISSUE TITLE
SPELL_EFFECT_TELEPORT_UNITS stopping all player combat?

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#21362]
As of 6bbc95f, [SpellEffects.cpp line `1063ff`](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L1064):
```cpp
    if (unitTarget->GetTypeId() == TYPEID_PLAYER)
        unitTarget->ToPlayer()->TeleportTo(mapid, x, y, z, orientation, unitTarget == m_caster ? TELE_TO_SPELL | TELE_TO_NOT_LEAVE_COMBAT : 0);
    else if (mapid == unitTarget->GetMapId())
        unitTarget->NearTeleportTo(x, y, z, orientation, unitTarget == m_caster);
```
So players will be forced out of combat by non-selfcast teleports, even if they're extremely near ones. I wonder if this is correct - for example 73040, used during the Malygos fight, is a near teleport that is cast on the player by a trigger NPC.

Opinions?

**Comment by sirikfoll** [comment]
Same problem with Lich King's spell `ID - 72597 Harvest Soul`, it currently removes combat while teleporting players to frostmourne room.

**Comment by ariel-** [comment]
Just a logic error in the effect handler, combat should only be removed when far teleporting (ie player changes map), if it's on the same map we should keep combat and map update will take care of removing it if too far

**Comment by ariel-** [comment]
https://github.com/TrinityCore/TrinityCore/commit/913d33532b3875a56d18882487b009e1114a2e39 changed function priority (TeleportTo always called for players, even if it's a near teleport). 

Partial reverting does not break #11076 as far as I could test
