### ISSUE TITLE
DB/Spell: Insect Swarm not stacking

### ISSUE THREAD

**Issue by Despondencyy** [TrinityCore/TrinityCore#21367]
**Description:** If a Balance Druid casts "Insect Swarm" it will overwrite any existing "Insect Swarm" cast by any other Balance Druid.

**Expected behavior:** It should be possible for multiple Insect Swarms to be on the target, however the "-3% chance to Hit" should not be stacking.

**Steps to reproduce the problem:**

1. Create two Druids and spec into "Insect Swarm & Improved Insect Swarm".
2. Try to cast them both in succession and observe that the second one will replace the first one.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**   rev. 4bd2d28119a8

TDB version: 335.63

```SQL
-- Insect Swarm stacking
UPDATE `spell_group_stack_rules` SET `stack_rule`= 3 WHERE `group_id`= 1060;
```

**Comment by Keader** [comment]
It's a attack spell.
Your fix looks correct to me.

**Comment by TecDian** [comment]
If this is OK, shouldn't it be pushed?

**Comment by ariel-** [comment]
Needs a little core help to actually only stack hit debuffs once (maybe this is why it was put as exclusive aura?)
