### ISSUE TITLE
Quest The fog is not listening

### ISSUE THREAD

**Issue by ShewaWOW** [TrinityCore/TrinityCore#21365]
Quest The fog is not listening

This is the episode Quest of a bumpy ride

You have to kill 12 Mistwhisper Gorloc (The Oracles)

The problem is that you can not attack them

https://www.youtube.com/watch?v=qNRADHsL9hU

If the problem is known please delete!

**Branch(es):**

(335.63)

**TC rev. hash/commit:** 

TrinityCore rev. 4bd2d28119a8 2018-02-05 10:14:00 +0100 (3.3.5 branch) (Win64, Release, Static) (authserver)

**Comment by Aokromes** [comment]
#9469

**Comment by ShewaWOW** [comment]
OK thank you :)

**Comment by ShewaWOW** [comment]
The quest with the crocodile now works thank you :)
