### ISSUE TITLE
[CRASH] in GetMap

### ISSUE THREAD

**Issue by n4ndo** [TrinityCore/TrinityCore#21361]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description**:
in GetMap (this=0x7ffeb4416800) at /Sources/src/server/game/Entities/Object/Object.h:370
370         Map* GetMap() const { ASSERT(m_currMap); return m_currMap; }

**Current behaviour**: 

- https://pastebin.com/5mi7TAFv

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
Dont know

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5

**TC hash/commit**:  
8f71307e5619c8ef1801488812e20d07714fd733

**TDB version**:  
335.63

**Operating system**:  
Linux x64, Static

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by tkrokli** [comment]
If 8f71307 is your core, you should update at least 1 commit
- as mentioned in the commit comments (by Killyana & ariel- )

**Comment by Aokromes** [comment]
paste expired, closing, if this bug is still valid open a new ticket with updated core.
