### ISSUE TITLE
[crash] Trinity::Abort <> FreezeDetector::Handler

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#21378]
**Description:**

My core crashes randomly multiple times a day, always with the same crashlog.

**Current behaviour:**

Core crashes randomly, it can run for hours then suddenly this happens

If this is a crash, post the crashlog (upload to https://gist.github.com/).
https://gist.github.com/dikkedeur/16603651bdff5599d362b4e30c8d4e63
**Expected behaviour:**

Tell us what should happen instead.
it should not randomly crash. at least not with this output, normally it seems that this output is when a shutdown is forced by myself.

**Steps to reproduce the problem:**

1) no idea, it happens randomly, after the boost update, thats all i can think off.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 275c17b4c234 2018-01-26 23:56:39 +0100 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  CHANGEME Version of the TrinityCore database
TDB 335.63

**Operating system:** CHANGEME OS
ubuntu server 16.04 lts

**Comment by Shauren** [comment]
Update. Fixed after your version
