### ISSUE TITLE
[CRASH] AuraEffect::HandleProcTriggerDamageAuraProc

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#21379]
**Description:**
Spell 56584 Combined Toxins proc crashes the server

**Steps to reproduce the problem:**
Not 100% chance:
1. Get a Warlock with Hellfire
2. .go xyz 505 -1038 31 619
3. Aggro the Deep Crawlers and spam Hellfire

100% chance:
1. .aura 56584
2. Do damage to something with spell 47823

**CrashLog**: https://gist.github.com/sirikfoll/17c63a2e3a86ed6d8fcfaf8bfb34a02e

**Branch(es):** 3.3.5
**TC rev. hash/commit:** cfaa4e6caf8f

**Comment by kvipka** [comment]
` src/server/game/Spells/Auras/SpellAuraEffects.cpp | 27 +++++++++++++----------
 1 file changed, 15 insertions(+), 12 deletions(-)

diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index aae80c6e27..52791f0203 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -5695,20 +5695,23 @@ void AuraEffect::HandleProcTriggerDamageAuraProc(AuraApplication* aurApp, ProcEv
 
     Unit* target = aurApp->GetTarget();
     Unit* triggerTarget = eventInfo.GetProcTarget();
-    if (triggerTarget->HasUnitState(UNIT_STATE_ISOLATED) || triggerTarget->IsImmunedToDamage(GetSpellInfo()))
+    if (target && triggerTarget)
     {
-        SendTickImmune(triggerTarget, target);
-        return;
-    }
+        if (triggerTarget->HasUnitState(UNIT_STATE_ISOLATED) || triggerTarget->IsImmunedToDamage(GetSpellInfo()))
+        {
+            SendTickImmune(triggerTarget, target);
+            return;
+        }
 
-    SpellNonMeleeDamage damageInfo(target, triggerTarget, GetId(), GetSpellInfo()->SchoolMask);
-    uint32 damage = target->SpellDamageBonusDone(triggerTarget, GetSpellInfo(), GetAmount(), SPELL_DIRECT_DAMAGE, { });
-    damage = triggerTarget->SpellDamageBonusTaken(target, GetSpellInfo(), damage, SPELL_DIRECT_DAMAGE);
-    target->CalculateSpellDamageTaken(&damageInfo, damage, GetSpellInfo());
-    Unit::DealDamageMods(damageInfo.target, damageInfo.damage, &damageInfo.absorb);
-    target->SendSpellNonMeleeDamageLog(&damageInfo);
-    TC_LOG_DEBUG("spells", "AuraEffect::HandleProcTriggerDamageAuraProc: Triggering %u spell damage from aura %u proc", damage, GetId());
-    target->DealSpellDamage(&damageInfo, true);
+        SpellNonMeleeDamage damageInfo(target, triggerTarget, GetId(), GetSpellInfo()->SchoolMask);
+        uint32 damage = target->SpellDamageBonusDone(triggerTarget, GetSpellInfo(), GetAmount(), SPELL_DIRECT_DAMAGE, { });
+        damage = triggerTarget->SpellDamageBonusTaken(target, GetSpellInfo(), damage, SPELL_DIRECT_DAMAGE);
+        target->CalculateSpellDamageTaken(&damageInfo, damage, GetSpellInfo());
+        Unit::DealDamageMods(damageInfo.target, damageInfo.damage, &damageInfo.absorb);
+        target->SendSpellNonMeleeDamageLog(&damageInfo);
+        TC_LOG_DEBUG("spells", "AuraEffect::HandleProcTriggerDamageAuraProc: Triggering %u spell damage from aura %u proc", damage, GetId());
+        target->DealSpellDamage(&damageInfo, true);
+    }
 }
 
 void AuraEffect::HandleRaidProcFromChargeAuraProc(AuraApplication* aurApp, ProcEventInfo& /*eventInfo*/)
`

**Comment by tkrokli** [comment]
So the crash log references these lines (only listing the first 5)
https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Entities/Unit/Unit.h#L830
https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L5675
https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L995
https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L2070
https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Entities/Unit/Unit.cpp#L11033
***
Just a question to those of you who are better at reading crash logs: Should I read those lines in context of the directly preceding lines, or even include the following lines, to get an idea of what is going on?

**Comment by jackpoz** [comment]
did you apply the aura to the Player or to the Creature ? Because I applied it to the Creature and it triggered the spell just fine.

**Comment by jackpoz** [comment]
@ariel- could you check if it's correct that https://github.com/TrinityCore/TrinityCore/blob/cfaa4e6caf8f26eb850a714994b533a77e92a92f/src/server/game/Spells/Spell.cpp#L3373 passes nullptr in some arguments causing eventInfo.GetProcTarget() to return nullptr ?

**Comment by ariel-** [comment]
It's correct in that case, as it is cast phase (ie no explicit target)
