### ISSUE TITLE
[crash] CreatureAI::DoZoneInCombat <> npc_twilight_whelp

### ISSUE THREAD

**Issue by dikkedeur** [TrinityCore/TrinityCore#21377]
**Description:**

Core crashes when encountering this npc or after it or whatever.

**Current behaviour:**
core crashes

If this is a crash, post the crashlog (upload to https://gist.github.com/).
https://gist.github.com/dikkedeur/33f056ad61ba785e28047871a3545a2a

**Expected behaviour:**

core should not crash.

**Steps to reproduce the problem:**

1) i was not at home when it happened i got crashlog in my mail about my core crashing with this crashlog.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 275c17b4c234 2018-01-26 23:56:39 +0100 (3.3.5 branch) (Unix, Debug, Static)

**TDB version:**  

TDB 335.63

**Operating system:** 
Ubuntu server 16.04 lts

**Comment by Shauren** [comment]
garbage script - Reset() must not be called in constructor

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5aba5c7afff4289b6b90311f66e6939791b89ee4
