### ISSUE TITLE
Mapextractor.exe error

### ISSUE THREAD

**Issue by jcmillions** [TrinityCore/TrinityCore#21381]
**Description:**  Mapextractor.exe fails to extract maps.

CHANGEME Description of the problem or issue here.

**Current behaviour:** Mapextractor.exe fails to extract maps.

> https://pastebin.com/Au8eDn6H

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:** Maps should extract to a folder called maps.

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Compile TrinityCore
2. Move mapextractor.exe to the root of your World of Warcraft folder
3. Open mapextractor.exe

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. a3f63f6650c0 2018-02-07 15:02:53 +0100 (master branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**TDB version** N/A

**Operating system:** Windows 10 Pro x64

**Comment by Aokromes** [comment]
https://i.imgur.com/YqeAxHI.png

**Comment by jcmillions** [comment]
Ah, sorry @Aokromes. I was so used to being caught up to retail I just assumed it would work lol.
