### ISSUE TITLE
DB/Quest-Decontamination

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#21388]
**Description:**

Jump on the sanitron and complete the decontamination process.

**Current behaviour:**

I'll jump, but the sanitron will not move, just hang on it.

**Expected behaviour:**

He should take me to the other side of the hall.

**Steps to reproduce the problem:**

1. Accept quest-http://www.wowhead.com/quest=27635/decontamination
2. Jump on the sanitron-http://www.wowhead.com/npc=46185/sanitron-500

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. a3b9eb21b337 2018-02-01 12:16:24 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10

**Comment by offl** [comment]
#16224
