### ISSUE TITLE
DB/Graveyard: New Tinkertown

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#21389]
**Description:**

Incorrect assignment of the Spirthealer area in New Tinkertown.

**Current behaviour:**

Place of death and cemetery at Sentinell hill
![wowscrnshot_021018_165607](https://user-images.githubusercontent.com/35656251/36064390-a57734b8-0e8a-11e8-9f34-16d67efc0f27.jpg)

**Expected behaviour:**

The cemetery at New Thinkertown is.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. a3b9eb21b337 2018-02-01 12:16:24 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 720.00

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
#19253

**Comment by Ravens62** [comment]
I've managed to fix the link to the graveyard. Functional throughout New Tinkerton.

```sql

DELETE FROM `graveyard_zone` WHERE `ID` IN (1471);
INSERT INTO `graveyard_zone` (`ID`,`GhostZone`,`Faction`, `Comment`) VALUES
(1471, 6457, 469, "Dun Morogh, Iceflow Lake - Dun Morogh");

**Comment by tkrokli** [comment]
@Ravens62 : please post in the linked issue ticket (#19253).
