### ISSUE TITLE
SQL error while populating character database

### ISSUE THREAD

**Issue by damiansp21** [TrinityCore/TrinityCore#21391]
Description:

Hello i'm new here and i want to report a SQL/DB Error. in a fresh tc

Current behaviour:

There are the error.

Reapplying update "2018_01_13_00_characters.sql" 'E3C0DA9' -> 'A9940D4' (it changed)...
Updating Character database...
ERROR 1060 (42S21) at line 1: Duplicate column name 'critChance'
and  Duplicate column name 'applyResilience'
Expected behaviour:

No DB Errors while populating/or updating character database

Steps to reproduce the problem:
i don't think that this is needed.
Branch(es):

3.3.5

TC rev. hash/commit:

3acd9a7

TDB version: 335.63

Operating system: Ubuntu 17

**Comment by Aokromes** [comment]
sha1sum sql/updates/characters/3.3.5/2018_01_13_00_characters.sql
e3c0da9995ba71ed5a267294470cd03dc51862dd  sql/updates/characters/3.3.5/2018_01_13_00_characters.sql

the problem must be on your side.
