### ISSUE TITLE
Flight Master Enraged Guards

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#21397]
**Description:**

Issue regarding the flight master enraged guards that are summoned upon attack.

**Current behaviour:**

Whilst you are attacking the two enraged <whatever> as you are fighting them they will despawn during mid fight.

**Expected behaviour:**

I believe they should stay spawned until killed, not despawn mid fight.

**Steps to reproduce the problem:**

Attack any alliance or horde flight master to see it for yourself.

**Branch(es):**

This affects branch 3.3.5a.

**TC rev. hash/commit:** 

TrinityCore rev. a217c0be922f 2018-01-31 00:59:14 -0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:** 

TDB 335.63

**Operating system:**

Windows 10

**Comment by Killyana** [comment]
Every npc has his own script, provide pncs entry that have this issue.

**Comment by LewisPotato** [comment]
Umm, how do I do that?

I only wanted to make the contributors aware of this issue.

**Comment by tkrokli** [comment]
If this is a real issue (compared to retail), it should be possible to replicate the 'Expected behaviour' by attacking a Flight Master on retail and stay alive long enough to enrage the NPC to see if the summoned beasts stay alive until you kill them. If that is the case, it may be worth sniffing the event.

**Comment by LewisPotato** [comment]
Yeah, I checked and they are meant to stay summoned until they've died of course.

Also will sniffers get my retail banned? I don't want to take the risk if it can.

**Comment by Killyana** [comment]
Fixed here https://github.com/TrinityCore/TrinityCore/commit/adae429aa01028911337443166b336a2ea8a6762
