### ISSUE TITLE
Core/Spells: Autoshot interrupt

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21390]
**Description:** If you change target while casting Steady Shot, autoshot just stop work.

**Steps to reproduce the problem:**

1. Start cast Steady Shot
2. Before Cast finish, change target
3. Autoshot will not work anymore, you need back to old target to autoshot work back.

Using macro like:

> /cast !auto shot
> /cast Steady Shot

cause a weird behavior.
You will cast steady shot in 1 target and autoshot in other haha

A little video showing this bug: https://www.youtube.com/watch?v=ysV3ebFl1Ks

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 54b0b8f5ead41f936b12e97d1b4fbacd9b89ab53

**Comment by Foereaper** [comment]
This really reminds me of a similar issue that was present on Mangos a few years back... Let me find the commit.

**Comment by Foereaper** [comment]
Tested the "above" fix and it works, but considering the original comment I'm unsure what else it could impact, as it stops every autocast spell on dropping your target.

**Comment by Keader** [comment]
Nope, it dont solve this issue.
Autoshot still stop work in a new target.

**Comment by Foereaper** [comment]
Hm, strange, I was able to recreate the issue prior to it but not afterwards, maybe I was doing something wrong?
