### ISSUE TITLE
Core/Groups: Group leave aura removal bug

### ISSUE THREAD

**Issue by killerwife** [TrinityCore/TrinityCore#21394]
**Description:**

Player leaves group. All his auras are supposed to be removed from party members if they are party/raid restricted.

**Current behaviour:**

Soulstone is not removed from its target, if caster is removed from group whilst being offline.

**Expected behaviour:**

Soulstone is removed in all cases.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

725dd8a655d83ed7d4a56e4b602a11772a6da024

Code responsible:

```
    Player* player = ObjectAccessor::FindConnectedPlayer(guid);
    if (player)
    {
        for (GroupReference* itr = GetFirstMember(); itr != nullptr; itr = itr->next())
        {
            if (Player* groupMember = itr->GetSource())
            {
                if (groupMember->GetGUID() == guid)
                    continue;

                groupMember->RemoveAllGroupBuffsFromCaster(guid);
                player->RemoveAllGroupBuffsFromCaster(groupMember->GetGUID());
            }
        }
    }
```
 if (player) is a wrong condition. The block needs to execute even if its nullptr. Guid is enough to remove it from party members. We also dont need to remove any auras from him, since he is offline.

**Comment by ariel-** [comment]
What should happen if a player gets disconnected? Buffs should still be applied?

**Comment by killerwife** [comment]
The same thing should happen when a player is connected, as when he is disconnected. His party buff auras should be removed from party members.

**Comment by Killyana** [comment]
Fixed in TrinityCore rev. 75e7404bba8c
