### ISSUE TITLE
Vampiric Touch Deals too much damage

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21393]
**Description:**

Vampiric Touch Deals too much damage.

It should deal maximum 10k-15k damage with critical but now it deals about 30K-40K crit and 10k-15k non-crit ( BiS Gear )

![vampiric_touch](https://user-images.githubusercontent.com/5238989/36072998-9f86c26c-0f3e-11e8-9c2d-2d4c25f40080.jpg)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 638cb33

**TDB version:**  TDB 335.63

**Operating system:** Debian 9

**Comment by tje3d** [comment]
Same happens with Warlock's Unstable Affliction spell.
![warlock](https://user-images.githubusercontent.com/5238989/36074128-e4e8caa0-0f50-11e8-8a7e-77bcdc0b18f2.jpg)

**Comment by Keader** [comment]
Unstable Affliction should does alot of damage if someone dispel it.
But 18k looks so much o.o

**Comment by tje3d** [comment]
@Keader 18K non-crit 😁

**Comment by Gooyeth** [comment]
@tje3d: Try again after the fix, in my case the problem still continues.

**Comment by Gooyeth** [comment]
Still bug, causes damage of 20k.

**Comment by Strazhnik** [comment]
Confirmed in eb7d22d

**Comment by Killyana** [comment]
Cannot reproduce on rev. eb7d22d23eed
Try with a new char without buffs, maybe it's caused by something else.

**Comment by Strazhnik** [comment]
The more spd, the higher the damage. If dispel at 1000 spd= 7000 damage in 1000 resilience.

**Comment by ariel-** [comment]
We have no data on this spell that can confirm or dismiss the bug. It's supposed to scale on tick damage and do the equivalent of 8 ticks at once

**Comment by Strazhnik** [comment]
1000×1.2+1360= 2560 without talents
http://wowwiki.wikia.com/wiki/Spell_power_coefficient

**Comment by Killyana** [comment]
Looks correct for me https://imgur.com/a/wP6wM
Values matchs DrDamage calculations.

**Comment by Shauren** [comment]
@Killyana the issue description is garbage but this is about the on-dispel damage, not ticks

Please provide:
.pdump of spriest you used to test
.pdump of target you used to test
damage value you saw in your test
and expected damage for spriest you used to test

**Comment by Strazhnik** [comment]
About the on-Dispel damage. Test without talents and etc.
spriest:
spd=2619
paladin:
resilience=1061
Vampiric touch dispel=9736
I think it shoul be=(2619*1.2+1360)-22.51%=3489

**Comment by ariel-** [comment]
170 * 8 = 1360 is tick base damage, you're not factoring in spell power coefficient from the ticks. That's why I think scaling of 120% is wrong for this spell and that it should use tick bonus.

SPELL_ATTR4_FIXED_DAMAGE is causing it not being affected by resilience; but unmitigated damage seems ok:

Tick damage: 170 + (2619 * 0.4) = 1217.6
Damage for 8 ticks: 8 * 1217.6 = 9740.8, which seems spot on with your 9736 result.

Missing 22.51% damage reduction from resil = 0.7749 * 9740.8 = 7548.15

**Comment by Strazhnik** [comment]
@ariel- 
I'm talking only about the damage that is caused by the dispel.(2 part of the spell)
Tick damage = true

**Comment by Strazhnik** [comment]
Sorry, i mistake.
Tick damage=116×8=935;
116+(2619*0.4)=1164;
Damage for 8 tick=8*1164=9312.
If dispel this spell damage=(2619*1.2+1360)-22.51%=3489(2 part of the spell)

**Comment by Warpten** [comment]
It needs to be fixed damage otherwise it will double dip it. Ticks are already affected.

**Comment by ariel-** [comment]
> Tick damage = 106 * 8 = 850 is tick base damage;
106 + (2619 * 0.4) = 1154;

I don't know where are you getting the 106 from.
```
ID - 48160 Vampiric Touch (Rank 5)
=================================================
(...)

Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 170 Bonus = 0,40
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 3 (SPELL_AURA_PERIODIC_DAMAGE), value = 170, misc = 0 (0), miscB = 0, periodic = 3000
```

170 is the base damage without sp

so, get the damage per tick, and multiply it  by 8 you get the amount of damage you should get on dispel

> It needs to be fixed damage otherwise it will double dip on resilience. Combustion had the same issue early in Cata and that's how they fixed it.

Already added the fixed damage attribute however the calculation in AuraEffect::GetAmount only takes caster bonuses, resilience reduction is applied per tick. As the dispell reaction is from a script, I need to take into account victim taken bonuses (which includes resilience)

**Comment by Warpten** [comment]
Well I'm down for whatever as long as shadow doesn't break :(

**Comment by Strazhnik** [comment]
@ariel-
https://wotlk-twinhead.twinstar.cz/?spell=48160#comments
170 damage every 3 seconds. 
In 15 sec=5 tick.
- Causes 850 Shadow damage over 15sec. 170 * 5 = 850. 
- If the Vampiric Touch is dispelled it will cause 1360 damage to the afflicted target.

**Comment by Warpten** [comment]
Friendly reminder that tooltip in wrath are not in the least bit accurate when it comes to damage valued

**Comment by ariel-** [comment]
Also this:

> there's a reason no one did that unless with an absorb shield up, or as a holy pally. It hits hard, like UA. {{ citation needed }}

**Comment by Strazhnik** [comment]
@ariel-
I tested the damage with 6000 spd (without resil)
1) Tick damage = 2577 * 5 = 12885
2) dispelled damage = 20616 
This is normal? 😊

**Comment by ariel-** [comment]
It's * 8 instead of * 5. And you have a very high amount of spell power

**Comment by Strazhnik** [comment]
In combat log 5 tick

**Comment by ariel-** [comment]
It will always deal full damage of 8 ticks, despite if you let it tick for less

**Comment by Shauren** [comment]
Are you sure about that? I don't have spellwork with me right now but according to https://wotlk-twinhead.twinstar.cz/?spell=48160 this rank has a duration of 15 seconds with ticks every 3 seconds - that would give it 5 ticks, not 8

**Comment by Jildor** [comment]
<details>

```
ID - 48160 Vampiric Touch (Rank 5)
=================================================
Description: Causes $o2 Shadow damage over $d to your target and causes up to 10 party or raid members to gain 1% of their maximum mana per 5 sec when you deal damage from Mind Blast. In addition, if the Vampiric Touch is dispelled it will cause $*8;s2 damage to the afflicted target.
ToolTip: $s2 Shadow damage every $t2 seconds. Priest's party or raid members gain 1% of their maximum mana per 5 sec when the priest deals damage from Mind Blast.
Category = 0, SpellIconID = 2213, activeIconID = 0, SpellVisual = (3582,0)
Family SPELLFAMILY_PRIEST, flag [0] 0x00000000 [1] 0x00000400 [2] 0x00000400

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
=================================================
AttributesEx3: 0x04000000 (SPELL_ATTR3_CAN_PROC_WITH_TRIGGERED)
AttributesEx6: 0x00800000 (SPELL_ATTR6_UNK23)
=================================================
Skill (Id 78) "Shadow Magic"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 80, base 80, max 84, maxTarget 0

Category = 0
DispelType = 1 (DISPEL_MAGIC)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 4) "Medium Range":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 30, MaxRangeFriendly = 30

CastingTime (Id 16) = 1,50
RecoveryTime: 0 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 133, StartRecoveryTime = 1500,00 ms
Duration: ID (8)  15000, 0, 15000
Power POWER_MANA, Cost 16 %
Interrupt Flags: 0x0000000F, AuraIF 0x00000000, ChannelIF 0x00000000
Proc flag 0x00020000, chance = 100, charges - 0
=================================================
  17 Taken magic spell damage
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 2
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 2, misc = 0 (0), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 170
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 3 (SPELL_AURA_PERIODIC_DAMAGE), value = 170, misc = 0 (0), miscB = 0, periodic = 3000

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 0, misc = 0 (0), miscB = 0, periodic = 0
```

</details>

**Comment by Shauren** [comment]
Yeah, thats 5 ticks. Am I missing some talent increasing duration that would give it 8 ticks?

**Comment by Jildor** [comment]
But description say:
>In addition, if the Vampiric Touch is dispelled it will cause $*8;s2 damage to the afflicted target.

This 8 is the @ariel- number I think

**Comment by Shauren** [comment]
then i see no problem here

**Comment by Jildor** [comment]
I agree
