### ISSUE TITLE
Broken tooth (creature 2850) wrong attack speed

### ISSUE THREAD

**Issue by kaldown** [TrinityCore/TrinityCore#21408]
**Description:**

[Broken tooth](http://wowwiki.wikia.com/wiki/Broken_Tooth) wrong attack speed.

**Current behaviour:**

After `tame beast` (SpellID = 1515) on broken tooth, you'll get creature with attack speed: 2.0
But rumors says that is the only one creature with BaseAttackTime = 1000

```
select name, baseattacktime from creature_template where entry = 2850;                                                 
+--------------+----------------+
| name         | baseattacktime |
+--------------+----------------+
| Broken Tooth |           2000 |
+--------------+----------------+

```

**Expected behaviour:**

BaseAttackTime should be 1000

**Steps to reproduce the problem:**

1. .go creature 2850 
2. .pet create on him
3. look attack speed

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

**TDB version:**  TrinityCore rev. c7095375c37c+ 2018-02-12 18:36:10 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Dynamic) (worldserver-daemon)

**Operating system:** debian 9.0

![2018-02-13--20 08 47_1366x768_scrot](https://user-images.githubusercontent.com/3754017/36163459-8823a5d2-10fa-11e8-845c-ba897584652e.png)

**Comment by kaldown** [comment]
`UPDATE creature_template SET baseattacktime = 1000, rangeattacktime = 1000 where entry = 2850;`

**Comment by offl** [comment]
From your link:
He was sought after for his 1.0 attack speed, which was the quickest in the game. However, since pet speed normalization in patch 2.0.1 he has lost this ability and is no longer considered a pet to strive for.

**Comment by tkrokli** [comment]
Yes, I remember "pet speed normalization" was quite a disappointment at the time, although it did lead to hunters selecting pets more freely and only go for pets with special abilities during leveling, until that part was changed too in one of the 3.x patches.
