### ISSUE TITLE
[7.x] Core/SAI: SMART_EVENT_GOSSIP_SELECT

### ISSUE THREAD

**Issue by Kodekc** [TrinityCore/TrinityCore#21402]
**Description:**

Creature entry has unknown gossip option id for menu

**Current behaviour:**

Can not find id

**Expected behaviour:**

Need fix event_type: **id -> OptionIndex**

**Branch(es):**

Master

**TC rev. hash/commit:** 

91aa8e1193db690e5a50c700280cc7103e2f10b4

**TDB version:**  TDB version: TDB 720.00

**Operating system:** Win7

**Comment by Kodekc** [comment]
It should be rewritten, like this https://github.com/TrinityCore/TrinityCore/commit/b3f9d5e5af79c3c76043f29aa467c2c619386e0d

**Comment by Shauren** [comment]
Values in database for gossip menu options did not change, there is no reason for this to be broken
