### ISSUE TITLE
[3.3.5] DB AutoUpdate not working

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#21407]
DB AutoUpdater does not work anymore.
The Server don't start
If you disable in the conf the autoupdate, the server start normal.

in my worldserver.conf
Updates.EnableDatabases = 4

**Branch(es):**

3.3.5**TC rev. hash/commit:** 

TrinityCore rev. 9f59fb54fc16 2018-02-13 01:55:03 +0100 (335a branch)

**TDB version:**  TDB_full_world_335.63_2017_04_18 + updates

**Operating system:** Win7

**Comment by tkrokli** [comment]
Thanks for mentioning the issue, even if I had discovered it at almost the same time. 👍
