### ISSUE TITLE
Core/Vehicles: Accessories ejected on evade

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21410]
**Description:** Putricide tentacles are not handled correctly: 38309, 38308 they never appears, you can just see them on the floor  with gm on once Putricide evades.

**Current behaviour:** Putricide tentacles are never installed on the boss.

**Expected behaviour:** Putricide tentacles must always be installed on the boss and morph on phase 2 and 3
related spells: (notice the scale changes according to the phase with the spell https://woehead.way-of-elendil.fr/?spell=71703 for example)
https://woehead.way-of-elendil.fr/?search=Green+Bottle
https://woehead.way-of-elendil.fr/?search=Orange+Bottle

**Steps to reproduce the problem:**

1. .go c id 36678
2. start a combat then gm on
3. notice the 2 tentacle are on the floor
4. Put the boss on phase 2 then 3 and notice there's no tentacles

**Branch(es):** 3.3.5 and master probably

**TC rev. hash/commit:** rev. f91a9f8b14e6

**Comment by Killyana** [comment]
@Keader this could be funny to script

**Comment by Keader** [comment]
I dont think so.
Sirikfoll says: It's vehicle issue :/

**Comment by Killyana** [comment]
I tested after a crash the 2 tentacles were installed on the boss, and they get the correct auras on phase1 and 2, the only issue here that they are ejected after an evade, probably caused by a call "remove all auras"

**Comment by Shauren** [comment]
I'm pretty sure I made vehicle auras not get removed on evade years ago

**Comment by Killyana** [comment]
I fixed it like this, but I think It's better to find out why the accessories are ejected.
```  cpp
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
index ff0dd69597..f8791a9c38 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
@@ -253,6 +253,7 @@ class boss_professor_putricide : public CreatureScript
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->SetImmuneToPC(false);
                 }
+
             }
 
             void JustEngagedWith(Unit* who) override
@@ -266,7 +267,8 @@ class boss_professor_putricide : public CreatureScript
                     instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                     return;
                 }
-
+                if (Vehicle* vehicleKit = me->GetVehicleKit())
+                    vehicleKit->InstallAllAccessories(false);
                 me->setActive(true);
                 events.Reset();
                 events.ScheduleEvent(EVENT_BERSERK, 600000);

**Comment by Killyana** [comment]
This happen also with the leviathan, it ejects his turret on evade.

**Comment by Infinito47** [comment]
Also happens on Mimirons turret.

**Comment by tkrokli** [comment]
Your diff looks a bit unclear, does it really make a difference to add the blank line ?
```diff
@@ -253,6 +253,7 @@ class boss_professor_putricide : public CreatureScript
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->SetImmuneToPC(false);
                 }
+
             }
 
             void JustEngagedWith(Unit* who) override
```
Maybe I'm wrong, but I think it would be enough to include this:
```diff
@@ -267,6 +267,8 @@ class boss_professor_putricide : public CreatureScript
                     return;
                 }

+                if (Vehicle* vehicleKit = me->GetVehicleKit())
+                    vehicleKit->InstallAllAccessories(false);
                 me->setActive(true);
                 events.Reset();
                 events.ScheduleEvent(EVENT_BERSERK, 600000);
```

**Comment by Shauren** [comment]
works on master (for now, until all cherrypicks happen)

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/6dae4a747da558ca46a777186d4519c32fc1bf04
