### ISSUE TITLE
[Spells] Glyph of Renew wrong value

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21418]
**Description:** Using a level 80 character, with no talents, renew should heal 1400 in 15 sec (280 in each tick). Glyph should increase heal amount in 25% and decrease 3 sec of renew hot.

**Current behaviour:** After add glyph, tooltip change to "heal 1750", but current total amount is wrong.

With no Glyph: 5 * 280 = 1400.
With Glyph: 4 * 350 (25% of increase) = 1400.

In the end, amount healed is the same.
In this case should be something like 437~437

**Steps to reproduce the problem:**

1. Use renew without glyph
2. Use renew with glyph

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 63c436f5fb6924b872050cf5838a4052d9034935

**Comment by Keader** [comment]
Now i'm confuse about something... Headlinerko points me something in discord...
Has some comments in wowhead, like (http://www.wowhead.com/item=42411/charred-glyph#comments:id=641774) that say: "So only thing what this glyph do, is incerasing amount healed per tick-amount healed is same."

Maybe wrong tooltip?

**Comment by ariel-** [comment]
Glyph is working properly, we can safely ignore amount healed because it's cancelled in calculation:

Renew does 5 ticks unglyphed, each tick heals (X/5) of total amount
Glyph it, it reduces duration by 3 seconds (effectively removing one tick, but on the other hand each tick will heal now (X/5*1.25)

so unglyphed: 5 ticks of X/5 = 5*(X/5) = X
glyphed: 4 ticks of X/5*1.25 = 4*(X/5*1.25) = X

**Comment by Keader** [comment]
so @ariel-  Empowered Renew is bugged?

Talent in rank 3 (63543) say:

> Description: Your Renew spell gains an additional 15% of your bonus healing effects, and your Renew will instantly heal the target for 15% of the total periodic effect.

Adding this talent using .aura, without any other talent and using glyph i got:

262 of heal caused by Empowered Renew.

But... total heal is 1450
1450 + 15% = 1610
15% of 1610 = 241.5

**Comment by tkrokli** [comment]
I could be wrong, but I think you may be misreading the talent description.
"bonus healing effects" != total heal // => calculate the bonus heal values + 15%

**Comment by ariel-** [comment]
Exactly, it only means it improves SP coeff by 15%, not that it'll heal for 15% more

**Comment by Keader** [comment]
Still dont understand where 262 come from :(

**Comment by ariel-** [comment]
Fixed empowered renew calc in ab1aa8e3844753e8f8d0c2ec0974c6050acfea55
