### ISSUE TITLE
[3.3.5] WorldServer assertion triggered after Start

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#21426]
**Description:**
The server crashes after starting

https://gist.github.com/Tauriella/0fdee80ac200beafbe6f9670db484287

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 4da9321d2bdd 2018-02-15 12:23:05 +0100 (335a branch)

**TDB version:**  TDB_full_world_335.63_2017_04_18 + all updates

**Operating system:** Win7

**Comment by funjoker** [comment]
Compile in Debug.

**Comment by Tauriella** [comment]
arrg wrong log caught
mom 👍

**Comment by Treeston** [comment]
That call stack is one hell of a ride.

**Comment by jackpoz** [comment]
Please build in RelWithDebInfo (or even better in Debug) mode and post the crashlog.
Crash logs with TC build in Release mode can't be analysed.

Did you apply any custom change ? If so then please add a link to the branch on a public fork with all the custom changes.

**Comment by Treeston** [comment]
Did you use the same character database on any of the unstable branches? This oddly reminds me of a character aura corruption crash I had a few days ago after working on #21400...

**Comment by funjoker** [comment]
it is debug. just reload the log

**Comment by Treeston** [comment]
_(assigning it to aura guy anyway in case you didn't)_

**Comment by Tauriella** [comment]
@Treeston 
I use onli one DB i use clean core and clean DB

**Comment by ariel-** [comment]
Try applying #21395 and report back. Thanks

**Comment by jackpoz** [comment]
Some useful infos:
- Spell ID: 38857
- Creature ID: 22242
- Creature Name: Bash'ir Spell-Thief
- Map ID: 530
- Position: 
  - X: 3816.229980
  - Y: 5935.109863
  - Z: 266.966003
- deDE DBCs

**Comment by jackpoz** [comment]
@Tauriella you probably got an error printed in the console too before the assertion triggered, that's useful too when reporting an assertion.

**Comment by Tauriella** [comment]
Sorry
Unfortunately, I do not know how to reset versions :(

**Comment by ariel-** [comment]
Also you have BaseMapLoadAllGrids=1 as I see on the callstack (MapManager::DoForAllMaps) after World::SetInitialWorldSettings.

Try momentarily disabling it to stop it from crashing at start

**Comment by Tauriella** [comment]
@jackpoz 
D:\TC335SRC\src\server\game\Spells\Auras\SpellAuras.cpp:662 in Aura::UpdateTarge
tMap ABORTED.

**Comment by jackpoz** [comment]
did it log anything like
>Aura %u: Owner %s (map %u) is not in the same map as target %s (map %u).

?

**Comment by ariel-** [comment]
Repro steps with BaseMapLoadAllGrids=0:

- Log into a character with '.go creature' permission
- .go creature 77964

**Comment by Treeston** [comment]
on a clean core?

**Comment by Tauriella** [comment]
@ariel- 
 BaseMapLoadAllGrids=1 dont work
BaseMapLoadAllGrids=0 Works 👍  Server Start fine

**Comment by Tauriella** [comment]
@Treeston yes Clean core no Custom Scripts

**Comment by Tauriella** [comment]
If i use .go creature 77964 the server Crasht

**Comment by ariel-** [comment]
Yes, those are the bug reproducing steps, of course it will crash! :P
