### ISSUE TITLE
DB/Gossip: Trainer gossip menu not showing

### ISSUE THREAD

**Issue by rapsys** [TrinityCore/TrinityCore#21437]
**Description:**  None of the trainer menus are working ( #21417 follow-up )

**Current behaviour:**

Click a trainer to learn a profession, gossip menu does not pop up.
Error log: `Creature entry 4614 has unknown gossip option 17 for menu 0.`

Exceptions:
- The Chef `<Cooking Trainer>`  (entry 47405) in Brill is working
- Rand Rhobart `<Skinning Trainer>` (6289) in Death's Watch Waystation

Reinstalled fedora 26 server in a virtual box to see from where it may comes, same problem as in my mageia 6.
Built with : `cmake ../TrinityCore -DSCRIPTS=static`

**Expected behaviour:**

Profession menu should pop up and you should be able to learn the profession.

**Steps to reproduce the problem:**

1. Any trainer in Undercity for example (tried them all as a blood elf mage)
2. Try to speaking with them
3. Menus don't work

**Branch(es):**  master

**TC rev. hash/commit:** 

TrinityCore rev c0abcc838be6+ 2018-02-12 19:34:24 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**TDB version:** TDB_full_720.00_2017_04_18.7z

**Operating system:**

Fedora release 26 (Twenty Six)
Mageia release 6 (Official) for x86_64

**Comment by rapsys** [comment]
It follow this bug reports : https://github.com/TrinityCore/TrinityCore/issues/21417

**Comment by rapsys** [comment]
For some reason "the chef" npc (47405) in "the brill" zone is working, other don't works...

**Comment by rapsys** [comment]
An exception is Rand Rhobart (6289) in Death's Watch Waystation, which works as a skinning trainer.
But Shelene Rhobart on the same spot is not working for example.

**Comment by tkrokli** [comment]
If you need to add more information to this issue, please edit the main post.
(Check my edits, I have moved the content from your removed comments there.)

**Comment by DoctorKraft** [comment]
If it's a `gossip_menu_option` for open trainer, you need to set `OptionType `at 5 and `OptionNpcFlag `at 16

**Comment by shamage** [comment]
the interesting thing is that for example, in an alliance in Stormwinde and the surrounding area, I did not even beat one coach where it would work. I've already found one trainer in the horde (see video) where it worked properly. Videos (in 3 pieces) can be downloaded from this link: https://www.ulozto.cz/!7NanpF2HFIHh/video-trinity-testing-rar   ( click slow download at free )

**Comment by funjoker** [comment]
Can't find any gossip_menu_option with MenuId = 8522

**Comment by Killyana** [comment]
Almost all vendors are fixed, if you found some trainers not working correctly open a new issue.
