### ISSUE TITLE
3.3.5a World Server Crash regarding Auras

### ISSUE THREAD

**Issue by mordusangelsdevs** [TrinityCore/TrinityCore#21430]
**Description:**

Receiving Segmentation Fault when try trying to launch 3.3.5a world server

**Current behaviour:**

CHANGEME Tell us what happens.
https://gist.github.com/mordusangelsdevs/1b6964eb50259fc0371bcef47ab49662

Server is unable to launch

Pulled down updates and received this error

**Branch(es):**

3.3.5a

** 7dc78d8  ** 

Using configuration file /home/wowserver/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0

**TDB version:**  335.63

**Operating system:** Ubuntu 17.10x64

**Comment by Aokromes** [comment]
/home/wowserver/TrinityCore/src/server/game/Spells/SpellMgr.cpp:2555 in LoadSpellInfoStore ASSERTION FAILED:
  effect.ApplyAuraName < TOTAL_AURAS TOTAL_AURAS must be at least 397

you look to have custom dbc files

**Comment by mordusangelsdevs** [comment]
I just pulled down a fresh copy of the stock dbc files that I compiled and received the same error, suggestions?

**Comment by tkrokli** [comment]
Try a different set of dbc files from another source. Also, this is not a forum, use the [IRC channel #trinity @ irc,rizon.net](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC) for this type of questions.
