### ISSUE TITLE
DB/Quest: The Corruption Abroad (Breadcrumb quest)

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21449]
**Description:**

* Quest "The Corruption Abroad" is optional, not a prerequisite for quest "Researching the Corruption"
* Quest "The Corruption Abroad" should not be available if player has accepted and/or completed quest "Researching the Corruption"
* Quest "Researching the Corruption" should not be obtainable if player is on quest "The Corruption Abroad". Once quest "The Corruption Abroad" is turned in, quest "Researching the Corruption" will become available again as a followup quest

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Breadcrumb Quest "The Corruption Abroad"
UPDATE `quest_template_addon` SET `PrevQuestID`=0 WHERE `ID`=1275;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry` IN (3765,1275);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19,0,3765,0,0,14,0,1275,0,0,0,0,0,"","Quest 'The Corruption Abroad' can only be taken if quest 'Researching the Corruption' is not taken"),
(19,0,1275,0,0,28,0,3765,0,0,1,0,0,"","Quest 'Researching the Corruption' can only be taken if quest 'The Corruption Abroad' is not completed");

**Comment by tkrokli** [comment]
https://wow.gamepedia.com/Quest:The_Corruption_Abroad
