### ISSUE TITLE
DB/Creature: A-Me 01

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21443]
**Description:**

* A-Me 01 should be "dead".
* A-Me 01 is wrongly targeting player for its aggro texts. It should target the aggressor. (This creature is using C++ scripting, so this must be fixed in core side. @Killyana, could you take a look to it?)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Add Standstate Dead to A-Me 01
UPDATE `creature_addon` SET `bytes1`=7 WHERE `guid`=24268;

**Comment by tkrokli** [comment]
I presume you mean this part in `src/server/scripts/Kalimdor/zone_ungoro_crater.cpp`
https://github.com/TrinityCore/TrinityCore/blob/01386cf447186fb0d810941b03cf3a7c7a1d9641/src/server/scripts/Kalimdor/zone_ungoro_crater.cpp#L78-L99
It should be reasonably easy to improve it, but at the moment I can't remember how to select the aggressor in the script.

**Comment by ZenoX92** [comment]
Yeah, that's why I meant. SAY_AGGRO1, SAY_AGGRO2 and SAY_AGGRO3 should target the summoned creatures.

**Comment by tkrokli** [comment]
Very well. Most other users are quicker than me at finding the solution to that part, but if the solution is simple enough, it can be pushed together with the SQL update. Or, if someone thinks the script needs improvements, they could also choose to open a PR for the suggested changes.

**Comment by offl** [comment]
You can convert this script to SAI.

**Comment by tkrokli** [comment]
Good idea. Anyway, a change in the .cpp file is needed in both cases.

**Comment by ZenoX92** [comment]
OK. I'll see what I can do.
