### ISSUE TITLE
DB/SAI: Arkkoran Clacker

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21454]
**Description:**

* Add ability "Call for Help" to Arkkoran Clacker

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9fa6885 2017-08-08 11:36:46 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.63

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Arkkoran Clacker
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=6135;
DELETE FROM `smart_scripts` WHERE `entryorguid`=6135 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(6135,0,0,0,2,0,100,1,0,50,0,0,39,30,1,0,0,0,0,1,0,0,0,0,0,0,0,"Arkkoran Clacker - Between 0-50% Health - Call For Help (No Repeat)");

**Comment by tkrokli** [comment]
Very sparse web page info about the creature too:
- http://www.wowhead.com/npc=6135/arkkoran-clacker
- https://wow.gamepedia.com/Arkkoran_Clacker
- http://wowwiki.wikia.com/wiki/Arkkoran_Clacker
