### ISSUE TITLE
Double Process "Deathbringer's Will"

### ISSUE THREAD

**Issue by tje3d** [TrinityCore/TrinityCore#21455]
**Description:**

Its happen very rarely.

![screen shot 1396-11-30 at 6 56 00 pm](https://user-images.githubusercontent.com/5238989/36385487-f6dde328-15a7-11e8-8b13-8b7743131a4b.png)
![screen shot 1396-11-30 at 6 56 10 pm](https://user-images.githubusercontent.com/5238989/36385488-f7158558-15a7-11e8-9b24-0ca54594ade9.png)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** e482d9f

**TDB version:** TDB 335.63

**Operating system:** Debian9

**Comment by Keader** [comment]
lol is proccing 2 effects o.O

**Comment by ariel-** [comment]
Do you have any custom patches?

**Comment by Killyana** [comment]
Confirm on rev. ba27711145d1
looks like there's no cool down.

**Comment by ariel-** [comment]
Can't reproduce on eb7d22d23eedb0d1b5374f80518cd7994d7c7b3a, even with extreme levels of haste, the cooldown is consistently checked and avoids two procs before it has ended.

Do you have any specific steps?

**Comment by Killyana** [comment]
Here a screen: https://imgur.com/a/2SRHy
The 2 procs doesn't happen at the same time but they must be done in a short interval, something like 3 secs other wise the second procs will not happen.

To reproduce it easily remove the procs by a right click, disconnect the char an reconnect it and try again.

**Comment by Shauren** [comment]
Proc cooldown is stored in Aura class, obviously relogging will allow a double proc

**Comment by Killyana** [comment]
You can reproduce it also after 15 min hitting a dummy.

**Comment by Nitair** [comment]
I can confirm this issue at 3753ec56476d597b180968eb673cb20776785f31

**Comment by ariel-** [comment]
Well I can't get it to proc twice. I'm suspecting this to be something else.

Can you send me your Spell.dbc?

**Comment by Killyana** [comment]
Cannot reproduce on rev. ecea2d62657e
