### ISSUE TITLE
[3.3.5] DB/Quest: Orabus the Helmsman

### ISSUE THREAD

**Issue by sandwm** [TrinityCore/TrinityCore#21465]
**Description:**

Using the Horn of the Ancient Mariner, try to summon Orabus the Helmsman when on the quest with the same name. He won't appear.

**Current behaviour:**

The message "Requires you to be standing at the end of Warsong Jetty." appears.

**Expected behaviour:**

A ship should appear, carrying [Orabus the Helmsman](http://www.wowhead.com/npc=32576/orabus-the-helmsman) (and some of his men), allowing you to fight him.

**Steps to reproduce the problem:**

1. Get the Quest [Orabus the Helmsman](http://www.wowhead.com/quest=11661/orabus-the-helmsman)
2. Go to the end of the Warsong Jetty as seen on the quest map. I tried standing at the same place as in [this youtube video](https://youtu.be/km6vCKWyK9Q?t=40s) as well as some other places, including the shallow water.
3. Use the [Horn of the Ancient Mariner](http://www.wowhead.com/item=34844/horn-of-the-ancient-mariner) (provided by the quest)

**Branch:**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. eb7d22d23eed 2018-02-20 19:34:58 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

Also happened with:

TrinityCore rev. 85e460802d08 2017-12-21 23:31:11 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:**

I don't know for sure. The server is not run by me, but I asked the operator and will get back to you, when I know the exact version. But as he started the update just about two hours ago, it is probably the current version as of 2018-02-21 00:23:00 UTC

**Operating system:** Linux

**Comment by Aokromes** [comment]
#15453 it works on certain places.

**Comment by sandwm** [comment]
You're right. It actually worked after finding the right coordinates, below the front of the tower. Just for reference: The gameobject is "End of Warsong Jetty" (Entry 187706), coordinates (X, Y) 2793.270020, 7018.879883

No ship appeared, but Orabus the Helmsman did, allowing for quest completion.
