### ISSUE TITLE
[3.3.5] [Spells] Loss of character control

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21460]
**Description:**

You lose control of your character at various spells, just reporting this one here.

**Current behaviour:**

Casting blind then gouge on a player, causes loss of character control. You cannot move

**Expected behaviour:**

Should be able to move properly afterwards

**Steps to reproduce the problem:**

1. Cast blind on a player  
2. Cast gouge on a player
3. After gouge goes away, you cant move your character. You can speak and all but you cant move until you relog, not even dying gives you back the ability to move.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/1cc3d33cfe7e51d66925d5df536a952165a88094

**TDB version:**  64
**Operating system:** ubuntu

**Comment by Keader** [comment]
@ariel-  caused by e315e41d36061fc88dfa09bfa0da1fbc0c00826f i belive.
I think that is same issue of Lady Deathwhisper Mind Control + CC issue.

**Comment by Persephone** [comment]
Probably, it happends with a lot of spells that causes loss of char control, you dont get it back

**Comment by Persephone** [comment]
@Keader  @ariel-  also happends with freeze trap and ice block
