### ISSUE TITLE
[3.3.5] Mounted movement above indoor area (while still outdoors) dismounts instantly

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21461]
**Description:**

No idea what commit caused this, just got it reported today and it was true lel. Running on a mount over the tunnel in WSG makes your char dismount.

**Current behaviour:**

Video: https://www.dropbox.com/s/m9yqiwwx9mxw2w2/IMG_0643.MOV?dl=0

**Expected behaviour:**

You should not dismount on terrain above "no mount" area. Only if you go inside that place

**Steps to reproduce the problem:**

1. .go xyz 1421.112183 1470.923828 349.519348 489
2. Mount up
3. Run forward towards the "lamp" thingie, once your above the tunnel below you insta dismount.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/1cc3d33cfe7e51d66925d5df536a952165a88094

**TDB version:**  64

**Operating system:** ubuntu

**Comment by tkrokli** [comment]
If this is a recent problem, that it did not happen a week ago, check commit https://github.com/TrinityCore/TrinityCore/commit/9e0faace9a5114fc2324c2c601ba943272e0d6ff / **Core/Entities: Reduce the probability of units dropping under the map** #21322

**Comment by Persephone** [comment]
Could be related to that i will run a test tomorrow

**Comment by Gooyeth** [comment]
Duplicate #21338
