### ISSUE TITLE
DB/Creature: Deathguard Elites & Stormwind City Guards do not use their Crossbow

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#21470]
**Description:**

I know these issues aren't a big deal but I like to report them because else they never get noticed. :-)

Deathguard Elites & Stormwind City Guards issue.

**Current behaviour:**

They don't have a ranged weapon which is a crossbow to shoot players with from sight. They both use a crossbow, not sure how to find out which one they use but it shouldn't be hard for me to find out.

**Expected behaviour:**

They should have a crossbow equipped and use the spell 'Shoot' when targeting an enemy from sight. The crossbow is meant to be hidden but when its needed he'll get it out to use it and if he loses aggro with the person he was shooting he holds the crossbow in his hand for some time before putting it away and going back to his Callous Axe. Also if he reaches the person he'll switch to his axe and put the crossbow on his back and it will become hidden within some time of it not being used.

**Steps to reproduce the problem:**

1. Aggro a Stormwind Guard or a Deathguard Elite from a distance. :-)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33cfe7e 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  The latest release.

**Operating system:** Windows 10

**Comment by ZenoX92** [comment]
Actually, they do have a crossbow, but they don't use it because they have no combat scripts.

**Suggested Fix:**
```sql
-- Deathguard Elite
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=7980;
DELETE FROM `smart_scripts` WHERE `entryorguid`=7980 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7980,0,0,0,0,0,100,0,0,0,2000,4000,11,6660,64,0,0,0,0,2,0,0,0,0,0,0,0,"Deathguard Elite - In Combat - Cast 'Shoot'");

-- Stormwind City Guard
DELETE FROM `creature_text` WHERE `CreatureID`=68 AND `GroupID`=0; -- Remove wrong aggro texts

DELETE FROM `smart_scripts` WHERE `entryorguid`=68 AND `source_type`=0 AND `id`>0;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (6800,6801,6802,6803,6804) AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(68,0,1,0,0,0,100,0,0,0,2000,4000,11,6660,64,0,0,0,0,2,0,0,0,0,0,0,0,"Stormwind City Guard - In Combat - Cast 'Shoot'"),
(68,0,2,0,9,0,100,0,0,5,11000,14000,11,12169,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - Within 0-5 Range - Cast 'Shield Block'"),
(68,0,3,0,0,0,100,0,5000,9000,8000,13000,11,12170,0,0,0,0,0,2,0,0,0,0,0,0,0,"Stormwind City Guard - In Combat - Cast 'Revenge'"),
(68,0,4,0,22,0,100,0,101,5000,5000,0,80,6800,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Wave' - Run Script"),
(68,0,5,0,22,0,100,0,78,5000,5000,0,80,6801,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Salute' - Run Script"),
(68,0,6,0,22,0,100,0,58,5000,5000,0,80,6802,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Kiss' - Run Script"),
(68,0,7,0,22,0,100,0,84,5000,5000,0,80,6803,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Shy' - Run Script"),
(68,0,8,0,22,0,100,0,77,5000,5000,0,80,6804,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Rude' - Run Script"),
(68,0,9,0,22,0,100,0,22,5000,5000,0,80,6804,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Chicken' - Run Script"),
(68,0,10,0,22,0,100,0,17,5000,5000,0,80,6802,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Received Emote 'Bow' - Run Script"),
(6800,9,0,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6800,9,1,0,0,0,100,0,2000,2000,0,0,5,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Play Emote 'Wave'"),
(6800,9,2,0,0,0,100,0,10000,10000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6801,9,0,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6801,9,1,0,0,0,100,0,2000,2000,0,0,5,66,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Play Emote 'Salute'"),
(6801,9,2,0,0,0,100,0,10000,10000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6802,9,0,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6802,9,1,0,0,0,100,0,2000,2000,0,0,5,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Play Emote 'Bow'"),
(6802,9,2,0,0,0,100,0,10000,10000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6803,9,0,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6803,9,1,0,0,0,100,0,2000,2000,0,0,5,23,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Play Emote 'Flex'"),
(6803,9,2,0,0,0,100,0,10000,10000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6804,9,0,0,0,0,100,0,0,0,0,0,66,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation"),
(6804,9,1,0,0,0,100,0,2000,2000,0,0,5,25,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Play Emote 'Point'"),
(6804,9,2,0,0,0,100,0,10000,10000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind City Guard - On Script - Set Orientation");

**Comment by LewisPotato** [comment]
This works like a charm!

However this goes for pretty much all guards of all races, they have the weapon (luckily) but no script to use it.

**Comment by tkrokli** [comment]
Thank you for testing it and giving feedback. Yes, but it is a start.
Notice that you yourself only specified the 2 types of guards in the issue title
(**Deathguard Elites + Stormwind City Guards Do Not Have Ranged Crossbow**).

You may want to open a new issue ticket for the missing/remaining ones. ;-)

**Comment by Aokromes** [comment]
I wonder if this thing can be handled by GuardAI.

**Comment by tkrokli** [comment]
You mean the C++ script that is supposed to spawn new guards on faction attack?

**Comment by LewisPotato** [comment]
Isn't that script broken or not even worked on?

**Comment by tkrokli** [comment]
I don't know enough about those details. Other TC members would have to answer that question.
For now, the most practical solution is to use the suggested solution above and close this ticket.
Other solutions can be applied later in a new commit or ticket, likely discarding the current solution.

**Comment by Aokromes** [comment]
IMHO guards must use GuardAI, that's why it exists, not SAI.

**Comment by tkrokli** [comment]
OK, so you recommend not pushing the suggested fix and wait for a different solution?

**Comment by LewisPotato** [comment]
Just want to note pretty much all guards that have a ranged weapon can't use them because they don't have the script.

**Comment by Killyana** [comment]
All guards are using GuardAI except the ones on Orgrimmar and Stormwind, because the last DKS quest was scripted by SAI, if we restore the cpp script for this npcs the SAI quest part must be converted to cpp.

**Comment by tkrokli** [comment]
Oh. Right. That is a nice twist. Gives me mixed emotions 😆 😞 on which solution to choose.

**Comment by LewisPotato** [comment]
I don't see what the issue is with using SAI for the Stormwind Guards, Orgrimmar Grunts & Deathguard Elites, is there a reason why it **has** to be done using GuardAI?

**Comment by tkrokli** [comment]
Fair question. I would like to see this issue closed by simply committing the suggested fix and leave the remaining discussion about GuardAI to a new ticket or PR (if someone wants to start improving that script to cover the intended functionality).

**Comment by LewisPotato** [comment]
I agree, I won't make the new issue about the GuardAI since I have no clue on how it works, hopefully someone else will figure it out. :-)

Closed.

**Comment by tkrokli** [comment]
Uhm, I meant that it should be closed when the SQL is committed.

**Comment by LewisPotato** [comment]
Oh.. How do I do that?

**Comment by tkrokli** [comment]
TC members (like myself) will do it. We push a commit with a line saying "Closes #21470" as one of the secondary lines of the commit message text and (hopefully, when it is up & running) @TrinityCoreBot will close the issue mentioned in the commit.

**Comment by tkrokli** [comment]
Oh, and @ZenoX92 , just a little F.Y.I. about the creature_text removal query; when looking at TDB 335.64 content:
```sql
SELECT * FROM `creature_text` WHERE `CreatureID`=68;
```
```
CreatureID  GroupID      ID  Text                                                      Type  Language  Probability   Emote  Duration   Sound  BroadcastTextId  TextRange  comment
----------  -------  ------  ------------------------------------------------------  ------  --------  -----------  ------  --------  ------  ---------------  ---------  --------------------
        68        2       0  %s throws a rotten apple at $n.                             16         0          100       0         0       0            31671          0  Stormwind City Guard
        68        3       0  %s throws rotten banana on $n.                              16         0          100       0         0       0            31672          0  Stormwind City Guard
        68        4       0  %s spits on $n.                                             16         0          100       0         0       0            31673          0  Stormwind City Guard
        68        5       0  Monster!                                                    12         0          100       0         0       0            31662          0  Stormwind City Guard
        68        5       1  Murderer!                                                   12         0          100       0         0       0            31679          0  Stormwind City Guard
        68        5       2  GET A ROPE!                                                 12         0          100       0         0       0            31669          0  Stormwind City Guard
        68        5       3  How dare you set foot in our city!                          12         0          100       0         0       0            31684          0  Stormwind City Guard
        68        5       4  You disgust me.                                             12         0          100       0         0       0            31680          0  Stormwind City Guard
        68        5       5  Looks like we're going to have ourselves an execution.      12         0          100       0         0       0            31682          0  Stormwind City Guard
        68        5       6  Traitorous dog.                                             12         0          100       0         0       0            31665          0  Stormwind City Guard
        68        5       7  My family was wiped out by the Scourge! MONSTER!            12         0          100       0         0       0            31667          0  Stormwind City Guard
```
The current content does not have any lines with `GroupID = 0` -- did you intend to remove something else?

**Comment by LewisPotato** [comment]
By the way when I tested this suggested fix I still have it applied to my server, will the update just overwrite it?

**Comment by tkrokli** [comment]
Any `UPDATE` lines to columns where you already have got the correct change will in practice ignore already applied changes (manually applied updates will show a log of which lines are skipped) and move on to the next query.

**Comment by LewisPotato** [comment]
Ah okay thank you, nothing to worry about. :-)

**Comment by tkrokli** [comment]
And BTW, for the sake of being informative (and hopefully making you learn something), the regular SQL files pushed to the `updates` folders contain `DELETE FROM / INSERT INTO` queries to make sure that the SQL file is repeatable for anyone who wants to apply the file manually, even after the world server has applied those changes automatically (when the automatic SQL update function is in place). The exception being when a column is changed (`ALTER / ADD / DELETE` - most often in `auth` or `characters` ) are made to the tables. For any `DELETE FROM / INSERT INTO` query, the values _will_ be rewritten/overwritten. The queries should normally only affect the columns/rows where the changes are needed & intended, as long as the query is properly written to target only the required changes.
