### ISSUE TITLE
The Nexus: Commander Kolurg keeps respawning

### ISSUE THREAD

**Issue by Infinito47** [TrinityCore/TrinityCore#21473]
**Description:**

The Nexus: Commander Kolurg keeps respawning after being killed - Abusable to farm emblems.

**Current behaviour:**
When joining The Nexus as a horde, after killing Commander Kolurg, the boss will almost instantly respawn. Making it very abusable to farm emblems. 

**Expected behaviour:**

Commander Kolurg should remain dead and not respawn like the alliance version, Commander Stoutbeard. Seems to work fine. 

Upon looking into it, I saw this comment:
// Alliance npcs are spawned by default, if you are alliance, you will fight against horde npcs.
I guess that's why the alliance works.

**Steps to reproduce the problem:**

1. Join The Nexus (heroic)
2. Kill Commander Kolurg
3. Wait for the respawn (about 1 second)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. eb7d22d23eed+ 2018-02-20 19:34:58 -0300 (3.3.5 branch) (Win64, Debug, Static)

**TDB version:**  TDB 335.64

**Operating system:** Server 2008 R2

**Comment by Treeston** [comment]
closed by 94b5d9b
