### ISSUE TITLE
Ghost mode bug after relog

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21472]
**Description:**
When you die in the world by any circumstance and you logout from the server voluntarily or involuntarily,after log in, you aren't able to recover your body and not even recover it by the Spirit Healer, the server detects you as you were alive because you start to recover your HP.

- It happens in instances and out of them. (You can enter in the instance as a ghost)

**Current behaviour:**
If you are dead, after a DC from server you aren't able to recover your body not even with the Spirit Healer
.

**Expected behaviour:**
Being able to recover body after a DC issue

**Steps to reproduce the problem:**

1. Step: Die by any circumstance
2. Step: Relog after being dead
3. Step: Try to recover body in your dead point or with a Spirit Healer

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
b197529

**TDB version:**  
335.64

**Operating system:** Win 10 x64

**Comment by Gooyeth** [comment]
@ariel-: It can not be revived with the corpse, after of relog.

**Comment by ariel-** [comment]
I can

**Comment by Tatara902** [comment]
@ariel-  happening again after 02f1399
