### ISSUE TITLE
Mind Control stuck other players (PVP)

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21471]
**Description:**

When you use the spell "Mind Control" in other player, that player get stuck and isn't able to move or cast anything. You need to relog to remove that bug

**Current behaviour:**
Mind control spell stuck players after its effect is removed

**Expected behaviour:**
The other player should be able to move and cast after mind control effect is removed

**Steps to reproduce the problem:**
1. Step : Cast Mind Control over a player.
2. Step Wait until mind control effect is removed.
3. Step Player who received the spell is stucked.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
b197529

**TDB version:** 
335.64
**Operating system:** Win 10 x64

**Comment by Keader** [comment]
your rev is master rev...

**Comment by Tatara902** [comment]
Ohh sorry! Thank you
