### ISSUE TITLE
3.3.5 Auth server failing linking during compile with atom issues

### ISSUE THREAD

**Issue by draziw77** [TrinityCore/TrinityCore#21478]
**Description:**
During the linking of the auth server binaries the compiler halts giving undefined atom references.

**Current behaviour:**

Getting the following compile time error:
```
[ 37%] Linking CXX executable authserver
../../common/libcommon.a(AppenderFile.cpp.o): In function std::__atomic_base<unsigned long long>::store(unsigned long long, std::memory_order)': /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/atomic_base.h:374: undefined reference to__atomic_store_8'
../../common/libcommon.a(AppenderFile.cpp.o): In function std::__atomic_base<unsigned long long>::load(std::memory_order) const': /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/atomic_base.h:396: undefined reference to__atomic_load_8'
../../common/libcommon.a(AppenderFile.cpp.o): In function std::__atomic_base<unsigned long long>::operator+=(unsigned long long)': /usr/bin/../lib/gcc/i686-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/atomic_base.h:312: undefined reference to__atomic_fetch_add_8'
/usr/bin/../lib/gcc/i686-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/atomic_base.h:312: undefined reference to `__atomic_fetch_add_8'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/server/authserver/CMakeFiles/authserver.dir/build.make:207: recipe for target 'src/server/authserver/authserver' failed
make[2]: *** [src/server/authserver/authserver] Error 1
CMakeFiles/Makefile2:1405: recipe for target 'src/server/authserver/CMakeFiles/authserver.dir/all' failed
make[1]: *** [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2 
```
**Expected behaviour:**

Auth server obj should compile and be linked successfully

**Steps to reproduce the problem:**

1. Created Ubuntu 17.10.1 server  
2. Followed directions to get all the PREREQS: The C compiler identification is Clang 4.0.1
```
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Detected 32-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/i386-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 3753ec56476d+ 2018-02-22 02:37:00 -0300 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /home/draziw77/server
* Install libraries to   : /home/draziw77/server/lib
* Install configs to     : /home/draziw77/server/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for open
-- Looking for open - found
-- Found OpenSSL library: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Looking for MADV_FREE
-- Looking for MADV_FREE - found
-- Found Readline library: /usr/lib/i386-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Found BZip2: /usr/lib/i386-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- CXX target common cotired without unity build.
-- CXX target database cotired without unity build.
-- CXX target shared cotired without unity build.
-- CXX target game cotired without unity build.
-- CXX target authserver cotired without unity build.

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |
-- CXX target scripts cotired without unity build.

-- CXX target worldserver cotired without unity build.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/draziw77/TrinityCore/build
```
3. At 37% when trying to link the auth server the above DESC error is thrown.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3753ec56476d+ 2018-02-22 02:37:00 -0300 (3.3.5 branch) 

**TDB version:**  TDB_full_735.00_2018_02_19.7z

**Operating system:** UBUNTU 17.10.1 OS

**Comment by tkrokli** [comment]
I made some modifications to your issue ticket post:
- removed the text `Description of the problem or issue here.` from your description
- switched placing of the text in the **Description:** and the "**Current behaviour:**" sections
- changed `**3753ec56476d+ 2018-02-22 02:37:00 -0300 (3.3.5 branch)**` to 
- added back "**TC rev. hash/commit:** " as title for that info and removed the "CHANGEME " part from that section
- added code block around the output texts in your descriptions for more precise viewing

I can't tell if this is because of some code you added to your source code (3753ec56476d+ `<-` notice the plus sign) or if this is something caused by specifics in your Linux version. I will leave that question to someone who knows Linux a lot better than me.

**Comment by draziw77** [comment]
I have not modded the source code at all.  I had all this working on ubuntu 16 until they stopped supporting it.  Then I wiped my drive grabbed the latest 32 bit Ubuntu 17 and started from scratch.  I had never received that issue in the past.  Thanks for cleaning up my post.  First time actually posting in here.

**Comment by tkrokli** [comment]
Very well, although the plus sign ( `+` ) is normally caused by added/modified source code. That signature change only happens when the source code is not identical to the TC source code at the linked commit in your TC rev. hash/commit, as far as I know. We will have to wait for someone else to confirm your issue on recent source or the same commit as you have used.

**Comment by jackpoz** [comment]
does this happen only with ubuntu 32 bits ? last time I tried on ubuntu 17.10 64 bits it built fine

**Comment by jackpoz** [comment]
it built fine on Ubuntu 17.10

<details>CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- Clang: All warnings enabled
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 16b5f39de629 2018-02-24 14:54:42 +0100 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /home/jackpoz/trinity
* Install libraries to   : /home/jackpoz/trinity/lib
* Install configs to     : /home/jackpoz/trinity/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : No
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show all warnings      : Yes
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

 *** NOJEM - WARNING!
 *** jemalloc linking has been disabled!
 *** Please note that this is for DEBUGGING WITH VALGRIND only!
 *** DO NOT DISABLE IT UNLESS YOU KNOW WHAT YOU'RE DOING!

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

-- Configuring done
-- Generating done
-- Build files have been written to: /home/jackpoz/trinity/sources/asan
[  0%] Built target Detour
[  1%] Built target Recast
[  5%] Built target g3dlib
[  5%] Built target fmt
[  6%] Built target gsoap
[  6%] Built target revision_data.h
Scanning dependencies of target common
[  6%] Building CXX object src/common/CMakeFiles/common.dir/GitRevision.cpp.o
[  6%] Linking CXX static library libcommon.a
[ 10%] Built target common
Scanning dependencies of target database
[ 10%] Building CXX object src/server/database/CMakeFiles/database.dir/Updater/DBUpdater.cpp.o
[ 10%] Linking CXX static library libdatabase.a
[ 12%] Built target database
[ 13%] Built target shared
[ 13%] Linking CXX executable authserver
[ 36%] Built target game
Scanning dependencies of target scripts
[ 37%] Built target authserver
[ 37%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/gen_scriptloader/static/ScriptLoader.cpp.o
[ 37%] Linking CXX static library libscripts.a
[ 98%] Built target scripts
[ 98%] Linking CXX executable worldserver
[100%] Built target worldserver
[  4%] Built target g3dlib
[  4%] Built target Detour
[  5%] Built target Recast
[  5%] Built target fmt
[  6%] Built target gsoap
[  6%] Built target revision_data.h
[ 10%] Built target common
[ 12%] Built target database
[ 13%] Built target shared
[ 36%] Built target game
[ 37%] Built target authserver
[ 98%] Built target scripts
[100%] Built target worldserver
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/jackpoz/trinity/bin/authserver
-- Set runtime path of "/home/jackpoz/trinity/bin/authserver" to "/home/jackpoz/trinity/lib"
-- Up-to-date: /home/jackpoz/trinity/etc/authserver.conf.dist
-- Installing: /home/jackpoz/trinity/bin/worldserver
-- Set runtime path of "/home/jackpoz/trinity/bin/worldserver" to "/home/jackpoz/trinity/lib"
-- Up-to-date: /home/jackpoz/trinity/etc/worldserver.conf.dist</details>

**Comment by jackpoz** [comment]
According to a google search it seems to be a bug in LLVM on i386 linux:
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216745
- https://reviews.llvm.org/D28213#665967
- https://bugs.llvm.org/show_bug.cgi?id=31864
- https://reviews.llvm.org/D29542

this ofc is out of scope of TC project. I would suggest to try building with GCC or switching to a 64 bit OS.
Please let us know if you solved the issue for other users that might have had it too.

**Comment by draziw77** [comment]
Forced to use an old 32-bit computer atm.... Was hoping someone else had a similar issue with a 32-bit version of Ubuntu 17.10.  Thanks for the assistance though.

**Comment by MrSmite** [comment]
For the time being, would this help?

[ttps://stackoverflow.com/questions/1978155/how-to-undefine-a-define-at-commandline-using-gcc](How to undefine a define at commandline using gcc)

Is it possible to redefine __GCC_ATOMIC_BOOL_LOCK_FREE to use the old i386 value?
