### ISSUE TITLE
Halion phases Issues

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21482]
**Description:**

After having done the phase 1, the players of the physical  realm can watch and heal players of the twilight realm and vice versa, also the players of the twilight realm can receive damage from the physical realm(Meteor strike, Flame breath and combustion--- tested in 10N )

Some screen to show:
- Player in the twilight realm can receive damage from physical world and watch players from physical world https://prnt.sc/iiiufx (Tested 10N)
- Players in the physical realm can watch players from twilight realm https://prnt.sc/iij8wc (Player with twilight realm aura from physical realm)
- Players in the physical realm can heal players from twilight realm and vice versa https://prnt.sc/iiiwtr
- The issue is mainly with paladins

**Current behaviour:**
Players receive damage from both realms only being in one realm and in not heroic mode
(Tested with paladins)

**Expected behaviour:**
Players should only receive damage from the realm that they are.

**Steps to reproduce the problem:**

1. Step 1 Dps Halion until Phase 2 starts
2. Step 2 Enter Twilight realm and watch the issues
3. Step 3 Let some players stay in physical realm to watch the issues

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
94b5d9b

**TDB version:**  
335.64

**Operating system:** Win 10 x64

**Comment by ariel-** [comment]
Rev 691c67f0be09095a34421043baf245fdf28e5d04. Cannot reproduce

Player in physical realm can't see player in twilight realm: ![](https://i.imgur.com/ea7DZeU.jpg)
Player in twilight realm can't see player in physical realm: ![](https://i.imgur.com/McEtyvQ.jpg)

**Comment by Warpten** [comment]
The only cross phase visibility happens in heroic, where players in a phase need to avoid the AoE effect of combustion/consumption both.

**Comment by Keader** [comment]
Little tip: If some GM summon a player and this player go to ruby, he can see 2 halions.
Summon make you change to "GM Phase", maybe it happens 4 u Tatara902

**Comment by ariel-** [comment]
Yes, gm mode on allow you to see all phases

**Comment by tkrokli** [comment]
So, possibly invalid issue due to GM ON status or not tested as a normal player ( `gmlevel 0` ) / non-GM player?

**Comment by Tatara902** [comment]
It was tested with non GM accounts, however i will try to reproduce the issue because everything were ok yesterday. 
**
If that raid has some damage issues related to skills of the bosses, should i make another issue or its easily fixed in the DB ? (Dusk Shroud — Halion and Blade Tempest — Baltharus the Warborn )

**Comment by ariel-** [comment]
Pure damage spells shouldn't have issues, the problem are the ones which depend on creature melee damage, that is another issue and I think it already has a ticket

**Comment by Tatara902** [comment]
I understand now, the damage from abilities like this http://www.wowhead.com/spell=75125/blade-tempest can be modified in the DB because it depends on the damage of the creature, however how can the damage of this http://www.wowhead.com/spell=75476/dusk-shroud (Aura) be modified ? , since it damages the tank 7 k per second and should not be more than 3k, can also corrected by a damagemultiplier modification?

**Comment by ariel-** [comment]
That one, depends on difficulty, it doesn't use the same spell id on all difficulties, doing more damage on other modes

**Comment by tje3d** [comment]
@Tatara902 Do you have this pull req #20144 ?

**Comment by sirikfoll** [comment]
There was a issue that could left players stuck with Wintergrasp phasing auras, that will cause this issue with Halion, and some others in Valithria.
But its already fixed! If that is the case, you can easily detect the wrong auras with ".list auras" and just do a ".unaura all" on the bugged players.

**Comment by Tatara902** [comment]
@tje3d not yet!

**Comment by Tatara902** [comment]
I found the real problem with Halion, will open another issue. Thank you!
