### ISSUE TITLE
Player Character Rollback

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21486]
**Description:**

Rollback possibly related to aura of paladin

**Current behaviour:**

> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (32, 32, 63531, 6, 6, 1, 0, 3, 0, 0, -1, -1, -1, -1, 0, 0, 1)
>  [ERROR]: [1062] Duplicate entry '32-32-63531-6' for key 'PRIMARY'
> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (131, 131, 63531, 6, 6, 1, 0, 3, 3, 0, -1, -1, -1, -1, 0, 0, 1)
>  [ERROR]: [1062] Duplicate entry '131-131-63531-6' for key 'PRIMARY'
> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (63, 63, 63531, 6, 6, 1, 0, 3, 3, 0, -1, -1, -1, -1, 0, 0, 1)
>  [ERROR]: [1062] Duplicate entry '63-63-63531-6' for key 'PRIMARY'
> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (22213, 22213, 63531, 6, 6, 1, 0, 3, 3, 0, -1, -1, -1, -1, 0, 0, 1)
>  [ERROR]: [1062] Duplicate entry '87-87-63531-6' for key 'PRIMARY'
> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (654868, 654868, 63531, 6, 6, 1, 0, 3, 0, 0, -1, -1, -1, -1, 0, 0, 1)
>  [ERROR]: [1062] Duplicate entry '87-87-63531-6' for key 'PRIMARY'
> SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (584503, 584503, 63531, 6, 6, 1, 0, 3, 0, 0, -1, -1, -1, -1, 0, 0, 1)

1. Login character
2. Levelup, move character, or other thing
3. Relog
4. The character is not saved, throws the DB error and returns to the starting position.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 94b5d9bfa1195ad7c32cf51a665b55514dac0938

**TDB version:**  TDB 335.64

**Operating system:** Debian 9

**Comment by ariel-** [comment]
Can't reproduce on 691c67f0be09095a34421043baf245fdf28e5d04

Send me a .pdump of the affected character(s). One of them should be enough

**Comment by Gooyeth** [comment]
Confirmed on Windows 10 too.
It happens with any paladin.
[Oram.zip](https://github.com/TrinityCore/TrinityCore/files/1750638/Oram.zip)

**Comment by TecDian** [comment]
Same here.

`
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (25, 25, 63531, 6, 6, 1, 0, 3, 3, 0, -1, -1, -1, -1, 0, 0, 1)
 [ERROR]: [1062] Duplicate entry '25-25-63531-6' for key 'PRIMARY'
`

**Comment by ariel-** [comment]
I see now, aura is being inserted twice into m_ownedAuras. First is due to spell script 'spell_pal_improved_aura', the second one is from Player::_LoadAuras
