### ISSUE TITLE
[NPC] Apothecary Keever

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#21488]
**Description:**
After 2018_01_24_03_world.sql Apothecary Keever (5734) causes lots of errors by smart_script lines

```sql
(573400, 9, 14, 0, 0, 0, 100, 0, 2000, 2000, 0, 0, 45, 2, 2, 0, 0, 0, 0, 19, 5742, 0, 0, 0, 0, 0, 0, 'Apothecary Keever <Royal Apothecary Society> - Script - Set Data 2 2 on Caged Toad'),
(573400, 9, 20, 0, 0, 0, 100, 0, 4000, 4000, 0, 0, 45, 3, 3, 0, 0, 0, 0, 19, 5739, 0, 0, 0, 0, 0, 0, 'Apothecary Keever <Royal Apothecary Society> - Script - Set Data 3 3 on Caged Squirrel'),
(573400, 9, 26, 0, 0, 0, 100, 0, 4000, 4000, 0, 0, 45, 4, 4, 0, 0, 0, 0, 19, 5741, 0, 0, 0, 0, 0, 0, 'Apothecary Keever <Royal Apothecary Society> - Script - Set Data 4 4 on Caged Rabbit'),
(573400, 9, 31, 0, 0, 0, 100, 0, 4000, 4000, 0, 0, 45, 5, 5, 0, 0, 0, 0, 19, 5743, 0, 0, 0, 0, 0, 0, 'Apothecary Keever <Royal Apothecary Society> - Script - Set Data 5 5 on Caged Sheep'),
```

because the creatures called by these lines have no SmartAI. I guess the author Dr-J forgot to add them.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 94b5d9bfa119
**TDB version:** according to hash
**Operating system:** Windows 10

**Comment by tkrokli** [comment]
I can confirm this on several revision commits (most of the ones used during the last month). Was usually too busy with other stuff to report it, though.

**Comment by Killyana** [comment]
Past all DB errors relate to the issue.

**Comment by tkrokli** [comment]
```
ERROR [sql.sql] SmartScript: Action target Creature (GUID: 0 Entry: 5739) is not using SmartAI, action called by Creature (GUID: 31870 Entry: 5734) skipped to prevent crash.
ERROR [sql.sql] SmartScript: Action target Creature (GUID: 0 Entry: 5741) is not using SmartAI, action called by Creature (GUID: 31870 Entry: 5734) skipped to prevent crash.
ERROR [sql.sql] SmartScript: Action target Creature (GUID: 0 Entry: 5742) is not using SmartAI, action called by Creature (GUID: 31870 Entry: 5734) skipped to prevent crash.
ERROR [sql.sql] SmartScript: Action target Creature (GUID: 0 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 31870 Entry: 5734) skipped to prevent crash.
```
-- each line (5739, 5741, 5742, 5743) repeated 30 times or more within a short period of time...

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry` IN (5736,5739,5741, 5742,5743);

**Comment by tkrokli** [comment]
Very well, let's test that update for a day or so. OK with you, @TecDian ?

**Comment by TecDian** [comment]
I'll test it. Although, unlike 5736, which has got a smart_script, the other IDs have none. Therefore I doubt it will change much - exept for the error message of course. But, as I said, I'll give it a try.

**Comment by Killyana** [comment]
The SAI change the template entry of caged human or dwarf, and the new template try execute the sai but it doesn't have `AIName`="SmartAI" so it throws an error.

**Comment by TecDian** [comment]
Well, I happily admit to have been wrong about this.
First: it works!
And second: learnt something.
Thus, as much as I am concerned, it can go ahead. Thanks a lot!
