### ISSUE TITLE
[3.3.5/Ulduar] XT002 Heart not working

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21489]
**Description:** Heart not working after first expose heart phase

**Current behaviour:** XT002 cant find heart :/

**Expected behaviour:** XT002 should find heart \o/

**Steps to reproduce the problem:**

1. drop HP until active expose heart phase.
2. Wait until secound expose heart phase.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 31f14dadde46445ae7e3e0330a3811b185bd8a61

PS: No need no one try fix this issue... I will start a rewrite in XT002 this week end, is just for remember me xD

**Comment by Jildor** [comment]
Can be related with: https://github.com/TrinityCore/TrinityCore/issues/21410 ??

**Comment by tkrokli** [comment]
"Take heart `$n`, for the task I am about to give you is a dire one."
"If you look deep enough, I am sure you can find it in your heart to feel sympathy for him."
