### ISSUE TITLE
Some items not showing in character selection

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#21483]
**Description:**

`Item::GetDisplayId` returns 0 for some items.

Causing some specific items do not show up in char selection screen.
Example item: http://www.wowhead.com/item=116244/spaulders-of-the-iron-crucible

This issue may be appearing only on/after 7.3.5.25996
It seems they removed some (possibly duplicate data) rows from `ItemModifiedAppearance.db2` in the update on this patch. Rows that used to have 0,1,4 appearancemodid may now only have 4.

**Current behaviour:**

Item::GetDisplayId returns 0 for some items.
This causes the item to not appear in character screen in character selection window when logging in, since 0 is saved to DB (characters.equipmentCache) as displayid to show on char screen.

**Expected behaviour:**

Item::GetDisplayId should return the displayid of the item.
The shoulder item should show in char selection screen.

**Steps to reproduce the problem:**

1. create draenei paladin and log in
2. use .level 110
3. use .additem 116244
4. equip the item and log out
5. notice there is no shoulders equipped in char screen

**Branch(es):** master

**TC rev. hash/commit:** 8467503b90915e95ae4270e30a01a0cb00715db1

**TDB version:**  735.00_2018_02_19 + updates

**Operating system:** windows 10

**Comment by Rochet2** [comment]
Looking in `ItemModifiedAppearance.db2` we can see that the entry 116244 only has one row and it has appearancemodid 4. Comparing the model that the client seems to pick and the one with appearance 4 seem to be the same model.

From this I assume that when there are rows for an entry, but no row without appearancemodid, then the lowest appearancemodid is used as the default.
Just guessing though.

**Comment by tkrokli** [comment]
Just out of curiosity, could this have anything to do with `uint16` vs `uint32` values stored?

**Comment by Rochet2** [comment]
> Just out of curiosity, could this have anything to do with uint16 vs uint32 values stored?

No.
The current system expects all items to have data in db2 with appearancemodid 0.
Seems that blizz has some items (like the example item) which has only appearancemodid 4.
Some items used to have the rows with modid 0, but on new patch no longer have it (like the item in the example above)

**Comment by Shauren** [comment]
Not a bug with appearances themselves, requires items to be created correctly

**Comment by Rochet2** [comment]
Maybe then block using .add without a valid modid?

**Comment by Faq** [comment]
Is this still a valid thing?

**Comment by Shauren** [comment]
No, its just items having wrong context value, this doesn't need fixing
