### ISSUE TITLE
[Utgarde Pinnacle] Skadi the Ruthless

### ISSUE THREAD

**Issue by Kawphi** [TrinityCore/TrinityCore#2149]
Core Revision: 719a079464dc
DB Revision: TDB 335.11.41
Addons: None

Issue -
When you reach the Harpoon guns and begin to take down Grauf and Skadi, the guns kill both Grauf and Skadi. This causes both Grauf and Skadi to fall and become un-lootable.

You're supposed to use the Harpoon Guns to kill Grauf causing Skadi to jump off his mount and attack the group. There also should be a notification for when Grauf is in range of the harpoon guns and you should not be able to continue using the harpoon guns even when Grauf is 'bombing' the hallway.

**Comment by Killyana** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/2660
