### ISSUE TITLE
Scripts/Oculus: mounting issue after first boss

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21492]
**Description:**

After killing the first boss "Drakos the interrogator" you can choose one of the 3 drakes available, the issue is that when you summon the drake you can't mount it to fly to the second boss of the instance, making it impossible to complete.

**Current behaviour:**

You can't mount the drakes available after killing first boss

**Expected behaviour:**
Able to mount the drakes to fly to the second boss

**Steps to reproduce the problem:**

1. Step. Enter Oculus and kill the first boss
2. Step Talk with npc and get any drake you want
3. Step Summon it and try to mount

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
9f92896  

**TDB version:**  
335.64

**Operating system:** Win 10 x64

**Comment by Foereaper** [comment]
Can confirm, this must have broken recently as it worked not long ago

**Comment by shenhuyong** [comment]
Confirm,  f1f6976f91952806f8b2bcc23fbbef5a8075fe73 causes this bug.
