### ISSUE TITLE
Core/Combat: Threat issues in raids

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21499]
**Description:**
If a tank loses the threat of the boss, that tank isn't able to recover the focus of the boss, not even with a taunt. After using taunt, the boss attacks the tank for 2 seconds, but then it starts to attack the player that stole the aggro. That DPS player has to run around 5 seconds to let the tank recover the threat. However, in heroic instances you get killed before that happens. It seems that DPS players are generating more threat than a tank.

In some special cases, like the boss Festergut, you need 2-3 tanks to switch focus when the main tank has enough stacks of Gastric Bloat and you need to switch tanks. It is not easy to do that, because taunts from the off-tanks are not enough to change the focus of the boss, making the main tank receive more marks of Gastric Bloat than he should, getting killed in the process. I would say that the main issue is that Taunt is not working as it should.
 
- Already checked the issue #21204, but the commit didn't work as it should.

**Current behaviour:**

Tanks aren't able to recover the threat easily after losing it, Taunt not working as it should.

**Expected behaviour:**

If the tank loses aggro, he should be able to recover it fast with a Taunt.

**Steps to reproduce the problem:**

1. Test a boss like Deathbringer Saurfang and let a tank lose the threat.
2. Taunt the boss and check how many seconds you need to recover that threat.
3. May be tested with two tanks on a boss like Festergut (switching aggro).

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  acdf7be

**TDB version:** 335.64

**Operating system:** Win 10 x64

**Comment by Foereaper** [comment]
Experienced the same thing today, though I can't really say for sure since I was only observing and not part of the raid group myself, but had some issues on Naxxramas bosses like 4 horsemen where the bosses would not gain aggro on tank swap at all, and ran back to the original target after taunt duration.

**Comment by jackpoz** [comment]
@Treeston could you take a look at this ? thanks

**Comment by Treeston** [comment]
I can reproduce - taunt seems to sometimes match threat to the wrong target. I will investigate.
