### ISSUE TITLE
Scripts/Hellfire Ramparts: Nazan (Vazruden's Mount) movement, repeated evade & reset

### ISSUE THREAD

**Issue by skipperheartbeat** [TrinityCore/TrinityCore#21504]
**Description:**

This has been an issue for as long as i remember and is desperate for a re-write. I couldn't find an open ticket for it, so here goes.

Phase 1: Two trash mobs. Nothing special

Phase 2: Vazruden
Vazruden will come after you. Simple tank and spank. His mount (Nazan) will randomly shoot fireballs. These may leave fire behind.

Phase 3: Nazan lands
Abilities: AE breath attack. He will randomly fireball people which leaves behind the fire on the ground.
Nazan will land in the middle of the platform. It should have lots of magic resistance.

**Current behaviour:**

Phase 1 - Nazan's flight movement is a mix of flight and walking on air. It does at least allow you to continue.
Phase 2 - Working although ugly.
Phase 3 - Nazan decends but starts to evade and attack, over and over again to the point you have to .die it.

**Expected behaviour:**

Nazan flies in a circling motion around the central arena, comes to the center and drops Vazruden off for phase 2
Once complete, Nazan descends to the center and fights the third phase, after which the loot box is accessible.

**Steps to reproduce the problem:**

Go to Hellfire Ramparts and fight Nazan and Vazruden Bosses

**Branch(es):**

Only tested on 3.3.5 but probably both.

**TC rev. hash/commit:** 

TC rev. hash/commit: acdf7be

**TDB version:**  335.64

**Operating system:** Ubuntu 17:10

**Comment by tkrokli** [comment]
extra info:
- https://wow.gamepedia.com/Vazruden
- https://wow.gamepedia.com/Nazan

**Comment by Keader** [comment]
Shit script...
Need a full rewrite xD

**Comment by TecDian** [comment]
Well, we kill him frequently without problems. If nothing has changed during the past 7 days ...

**Comment by tkrokli** [comment]
Maybe it depends on the player details, like running the instance with 4-5 regular account players or if using only 1 overpowered admin account character to run it alone and how fast you progress through the instance.

**Comment by skipperheartbeat** [comment]
It was possible to complete prior to commit acdf7be but not any more.

**Comment by TecDian** [comment]
This commit is about some gobs and has nothing to do with this, I guess.

Anyway, I testet it and can confirm. After killing Vazruden, the couple appears at the chest, walks to the middle of the platform while shouting text line 13981 (broadcast_text) and vanishes, only to reappear instantly at the spot, running to the chest, where it starts anew.

Although it is possible to kill the flying dragon first, then kill the boss.

**Comment by Aokromes** [comment]
workaround: kill nazan1st.

**Comment by illfated** [comment]
> (Revisiting this ticket to remember the workaround to complete the quest & instance, playing on: )

TrinityCore rev. 862d47394b8c 2019-12-27 17:28:09 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by Keader** [comment]
workaround: delete the script and make a new one !

**Comment by illfated** [comment]
😄 Haha yeah, well ... That is actually not a workaround, that is the correct procedure.

**Comment by Aokromes** [comment]
if anyone can ship a temp fix i can supply sniffs for proper script :P

**Comment by ryancheung** [comment]
Is there any public tool to sniff in Retail wow ? I want to do that too.

**Comment by Aokromes** [comment]
no.

**Comment by Keader** [comment]
i have a hack for this somewhere, i will search lol

**Comment by skipperheartbeat** [comment]
I have a working version of this script. Its just a slightly modified version of the current one but with the changes made by Aokromes, and a change about a month go. I does make it work again.

I can paste it here if you want to mod / push it?

**Comment by illfated** [comment]
As long as you don't feel like opening a PR for it, sure, go ahead.

**Comment by skipperheartbeat** [comment]
I'll have a look through the guide and see if I can open a PR

**Comment by skipperheartbeat** [comment]
PR opened. Hopefully i did it right.

**Comment by illfated** [comment]
Looks more or less OK, just a few minor details in your attempt at linking this issue ticket page from the PR (I linked it now). You might want to update your PR branch to include the **ci/circleci: nopch** fix in commit https://github.com/TrinityCore/TrinityCore/commit/9009c82a8db2bdb433cba17820af8b0cef8e28e3 , but then again, you probably struggle enough with the content itself to complete the requested changes, so I won't treat this as a request for you to change your PR too much.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8ac83744293afe297bce2597107bc5da5445ccbb
