### ISSUE TITLE
[master]  [crash] in GetGameTableColumnForClass<GtNpcTotalHpEntry>

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#21502]
**Description:**

Core is unable to load informations about base creature stats correctly when table creature_classlevelstats isn't empty

Description of the problem or issue here.

**Current behaviour:**

Error when loading Creature Base Stats informations

gdb data => https://pastebin.com/MzK1nCxy

**Expected behaviour:**

Core should be able to load its information without any problems.

**Branch(es):**

master

**TC rev. hash/commit:** 

9c41708

**TDB version:**  TDB735.00

**Operating system:** unix debian

**Comment by Pixel-Pirate** [comment]
Somebody can confirm it ?

**Comment by DoctorKraft** [comment]
Can't reproduct :/
What are the steps for get same result?

**Comment by Pixel-Pirate** [comment]
Maybe this is only on Unix build. What's tout operating system ?
No really steps just clone the latest tc version and install the latest database version.

**Comment by DoctorKraft** [comment]
Currently Windows 10
Hm it's since 7.3.5 update?

**Comment by Pixel-Pirate** [comment]
I think this appear only on unix build. Yes after db update.

**Comment by tkrokli** [comment]
OK, so you need testers with access to one or more Linux flavors to test the master branch, particularly when loading Creature Base Stats information. You might have to write a more detailed step-by-step procedure on how to replicate it, to see if anyone is able to reproduce your issue.

**Comment by Pixel-Pirate** [comment]
Thank you for your time @tkrokli . Problem solved whith cleaning and re cleaning my cash compiler. Don't ask why gcc was completly crazy sometime :)

#21522 is still relevant today
