### ISSUE TITLE
DB/Quest: Hallowed Scroll & Glyphic Scroll

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21506]
**Description:**

* Quests "Hallowed Scroll" & "Glyphic Scroll" should become available once quest "The Mindless Ones" is rewarded, not when quest "A New Plague" is rewarded.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Fix prerequisite for quests "Hallowed Scroll" & "Glyphic Scroll"
UPDATE `quest_template_addon` SET `PrevQuestID`=364 WHERE `ID` IN (3097,3098);

**Comment by tkrokli** [comment]
Info/details:
- http://www.wowhead.com/quest=364/the-mindless-ones (https://woehead.way-of-elendil.fr/?quest=364)
- http://www.wowhead.com/quest=3097/hallowed-scroll (https://woehead.way-of-elendil.fr/?quest=3097)
- http://www.wowhead.com/quest=3098/glyphic-scroll (https://woehead.way-of-elendil.fr/?quest=3098)
