### ISSUE TITLE
[Azjol Nerub] Hadronox

### ISSUE THREAD

**Issue by Kawphi** [TrinityCore/TrinityCore#2150]
Core Revision: 719a079464dc
DB Revision: TDB 335.11.41
Addons: None

Issue -
Hadronox should cast Leech Poison on all mobs when the gauntlet event is started, not when you engage him. This causes him to die to the mobs if you don't get down to him quick enough. Taken from retail experience.

**Comment by Aokromes** [comment]
Test #17118
