### ISSUE TITLE
Scripts/World: Training Dummy running in fear

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21513]
**Description:**

When you use a spell that makes the Training Dummy in fear, they run like a player. They should not move.
Abilities like Fear and Psychic Scream makes them run in fear

**Current behaviour:**

Training Dummy run in fear when a player cast the abilities mentioned above

**Expected behaviour:**
Training Dummy shouldn't run in fear when a player cast a fear spell on them

**Steps to reproduce the problem:**

1.  Step 1 Find a training dummy in any city of Azeroth
2. Step 2 Cast a fear spell
3. Step 3 Watch them run

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
c9b730c

**TDB version:** 
335.64
**Operating system:** Win 10 x64

**Comment by tkrokli** [comment]
Almost as funny as the bug where you could polymorph (sheep) a grounding totem. ^^

**Comment by ariel-** [comment]
Removing UNIT_STATE_STUNNED from the dummy in a23c97a0fcc53e5da0bee5fc033dd3748774c337 is what causes it to roam when feared (it hasn't fear immunity set in template)

**Comment by LewisPotato** [comment]
I can confirm that the aura get's applied to the training dummy but it stands still (obviously).

**Comment by ariel-** [comment]
Then it's script issue

**Comment by tkrokli** [comment]
https://github.com/TrinityCore/TrinityCore/blob/efef6b5e36a8cd8eca023b8aa6a5d8cbd532ca68/src/server/scripts/World/npcs_special.cpp#L1746-L1832
