### ISSUE TITLE
Quest: The Caverns of Time

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21516]
**Description:**
http://www.wowhead.com/quest=10277/the-caverns-of-time

**Current behaviour:**
Nothing happens.

**Expected behaviour:**
There is supposed to be a Custodian that is spawned at the start of the quest and gives you a tour of the Caverns of Time (similar to the custodian that guides you around Shattrath).

He should walk you around the area and has this script:

>Greetings, &lt;name&gt;. I will guide you through the cavern. Please try and keep up.

>We do not know if the Caverns of Time have always been accessible to mortals. Truly, it is impossible to tell as the Timeless One is in perpetual motion, changing our timeways as he sees fit. What you see now may very well not exist tomorrow. You may wake up and have no memory of this place.

>It is strange, I know... Most mortals cannot actually comprehend what they see here, as often, what they see is not anchored within their own perception of reality.

>Follow me, please. &lt;The Custodian leads you to the entrance of the Old Hillsbrad timeway.&gt;

>There are only two truths to be found here: First, that time is chaotic, always in flux, and completely malleable and second, perception does not dictate reality.

>As custodians of time, we watch over and care for Nozdormu's realm. The master is away at the moment, which means that attempts are being made to dramatically alter time. The master never meddles in the affairs of mortals but instead corrects the alterations made to time by others. He is reactionary in this regard.

>For normal maintenance of time, the Keepers of Time are sufficient caretakers. We are able to deal with most ordinary disturbances. I speak of little things, such as rogue mages changing something in the past to elevate their status or wealth in the present.

>These tunnels that you see are called timeways. They are infinite in number. The ones that currently exist in your reality are what the master has deemed as 'trouble spots.' These trouble spots may differ completely in theme but they always share a cause. That is, their existence is a result of the same temporal disturbance. Remember that should you venture inside one...

>This timeway is in great disarray! We have agents inside right now attempting to restore order. What information I have indicates that Thrall's freedom is in jeopardy. A malevolent organization known as the Infinite Dragonflight is trying to prevent his escape. I fear without outside assistance, all will be lost.

>Follow me, please. &lt;The Custodian leads you to the entrance of the Black Morass timeway.&gt;

>We have very little information on this timeway. Sa'at has been dispatched and is currently inside. The data we have gathered from his correspondence is that the Infinite Dragonflight are once again attempting to alter time. Could it be that the opening of the Dark Portal is being targeted for sabotage? Let us hope not...

>Follow me, please. &lt;The Custodian leads you to the closed timeway with the wrecked ships in front of it.&gt;

>This timeway is currently collapsing. What that may hold for the past, present and future is currently unknown...

>The timeways are currently ranked in order from least catastrophic to most catastrophic. Note that they are all classified as catastrophic, meaning that any single one of these timeways collapsing would mean that your world would end. We only classify them in such a way so that the heroes and adventurers that are sent here know which timeway best suits their abilities.

>Follow me, please. &lt;The Custodian leads you to the entrance of the Mount Hyjal timeway.&gt;

>All we know of this timeway is that it leads to Mount Hyjal. The Infinite Dragonflight have gone to great lengths to prevent our involvement. We know next to nothing, mortal. Soridormi is currently attempting to break through the timeway's defenses but has thus far been unsuccessful. You might be our only hope of breaking through and resolving the conflict.

>Follow me, please. &lt;The Custodian leads you back to Andormu.&gt;

>Our time is at an end &lt;name&gt;. I would wish you luck, if such a thing existed.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** b197529f1e89

**TDB version:** 335.63

**Operating system:** Windows 10

**Comment by Killyana** [comment]
The quest was working correctly, the npc spawns by https://woehead.way-of-elendil.fr/?spell=34877 casted by the player when the quest is taken, the problem is the npc  https://woehead.way-of-elendil.fr/?npc=20129 is not summoned when the spell is casted.

**Comment by tkrokli** [comment]
This issue must be fairly recent. I seem to remember doing this quest normally last year, around the time when the Keepers of Time were misplaced outdoors on the Tanaris sand dunes.

**Comment by ariel-** [comment]
Not a spell problem, the spell is correctly summoning the Custodians of Time, except in bad coords, this is vmap issue. I actually think is the same as #19744

Spawned at pos = {m_positionX=-8374.02246 m_positionY=-4251.74365 m_positionZ=12.2198591 ...}

gps output:
You are outdoors.
Map: 1 (Kalimdor) Zone: 440 (Tanaris) Area: 2300 (Caverns of Time) Phase: 4294967295
X: -8374.024414 Y: -4251.744141 Z: -205.213364 Orientation: 1.000288
grid[16,24]cell[2,0] InstanceID: 0
 ZoneX: 58.449196 ZoneY: 54.326618
GroundZ: 12.220015 FloorZ: -205.213287 Have height data (Map: 1 VMap: 1 MMap: 1)

**Comment by ariel-** [comment]
Tagging @Golrag

**Comment by tkrokli** [comment]
See also **Blink / Killing Spree teleport issues** #21624

**Comment by jerbookins** [comment]
68989081b1c0

The Custodian of Time now properly spawns when the quest is accepted but there is still no NPC scripted dialogue.

Also, there appear to be multiple instances of the Custodian of Time NPC throughout the Caverns of Time.

![wowscrnshot_050818_025152](https://user-images.githubusercontent.com/16745918/39747716-547c4e20-526b-11e8-848c-e060c5049087.jpg)

![wowscrnshot_050818_025536](https://user-images.githubusercontent.com/16745918/39747724-5ba9092c-526b-11e8-8db6-3e7ce2ce48dd.jpg)

**Comment by Killyana** [comment]
I don't have any double spawn, the quest works correctly, text are displayed and the quest completed at the end: https://imgur.com/a/3igscs1

**Comment by jerbookins** [comment]
This is what happens to me.
https://streamable.com/jr0ni

**Comment by jerbookins** [comment]
Nevermind about the extra Custodians of Time but I'm still not getting any dialogue.

https://streamable.com/jr0ni
