### ISSUE TITLE
[master] [crash] in WriteRecordData<sItemSparseStore>

### ISSUE THREAD

**Issue by Pixel-Pirate** [TrinityCore/TrinityCore#21522]
**Description:**

Worldserver crash when you try to add a custom item from hotfixes, problème appear since 7.3.5 version.

gdb data https://pastebin.com/Mrbezhpy

**Expected behaviour:**

Item must to be added correctly.

**Steps to reproduce the problem:**
1) Insert this in your Hotfixes db:
`DELETE FROM item WHERE id = 500000;
INSERT INTO item VALUES (500000,511044,2,4,-1,0,13,3,8,'');
DELETE FROM item_appearance WHERE id = 1;
INSERT INTO item_appearance VALUES (1,85561,511044,0,0,'');
DELETE FROM item_modified_appearance WHERE id = 500000;
INSERT INTO item_modified_appearance VALUES (500000,1,0,0,0,500000,'');
DELETE FROM item_sparse WHERE id = 500000;
INSERT INTO item_sparse (id, NAME, Description, Quality, InventoryType, RequiredLevel) VALUES (500000,'test hammer','Test',4,13,110);
DELETE FROM hotfix_data WHERE id IN (1,2,3,4);
INSERT INTO hotfix_data VALUES (1,3834752085,500000,0),(2,1109793673,1,0),(3,1344507586,500000,0),(4,2442913102,500000,0);`

2) Restart or start your worldserver
3) Try to additem 500000

**Branch(es):** master

**TC rev. hash/commit:**  9c41708

**TDB version:**  TDB735.00

**Operating system:** Unix Debian

**Comment by tkrokli** [comment]
Difference between this issue and your previous issue, **[master] [crash] in GetGameTableColumnForClass<GtNpcTotalHpEntry> #21502** `-- is it only the insert listed in Step 1, or is it more ?

**Comment by Pixel-Pirate** [comment]
is it a new issue, two different problem. I don't know if it's the same on windows build.

**Comment by lyosky** [comment]
it's the same on windows build too

**Comment by Gwyndrichstein** [comment]
Same problem here, creating a new record in item_sparse table will crash the server. Editing or adding new items is now unavailable.
