### ISSUE TITLE
Compile error  no member named 'make_reverse_iterator' in namespace 'std'

### ISSUE THREAD

**Issue by EdwardGO** [TrinityCore/TrinityCore#21527]
**Description:**

Compile error on master branch: https://paste2.org/znyV5JkP (3.3.5 no error)

**TC rev. hash/commit:**  06520a322b30 2018-03-01 08:19:52 +0100 (master branch)
**TDB version:**  TDB 735.00
**Operating system:** Debian 9

$ cmake --version
cmake version 3.10.2

$gcc --version
gcc (GCC) 7.3.0

$ clang --version
clang version 5.0.1-svn325091-1~exp1 (branches/release_50)

$ openssl version
OpenSSL 1.0.1t  3 May 2016

Boost version: boost_1_63_0 

Is any library incorrect?
regards!

**Comment by tkrokli** [comment]
Maybe try again using `clang version 5.0.0 (tags/RELEASE_500/final)`
(https://travis-ci.org/TrinityCore/TrinityCore/jobs/347848720#L910)
I don't know, I haven't tested on Linux for a year now.

**Comment by EdwardGO** [comment]
@tkrokli is working now! thank you!
