### ISSUE TITLE
[master] Warsong Gulch (Battleground)

### ISSUE THREAD

**Issue by ForesterDev** [TrinityCore/TrinityCore#21525]
**Description:**

Can't capture any flag at WS bg

**Current behaviour:**

When you are on your flag capture point with enemy's flag - nothing happens.

![image](https://user-images.githubusercontent.com/11771800/36834664-00ed960e-1d4d-11e8-85e0-29c42f594ef0.png)

**Expected behaviour:**

You should capture the flag

**Branch(es):**

master 

**TC rev. hash/commit:** 

06520a322b305c54a83be2adf48971bf4d0c0fc0

**Operating system:** win/debian

The root of the problem - areatriggers were removed from AreaTrigger.db2

In 3.3.5a there was areatriggers:

8965 // Horde Start
8966: // Alliance Start
3646: // Alliance Flag spawn
3647: // Horde Flag spawn

but in 7.3.5 these areatriggers are missing. So the part of code now is obsolete. Maybe some ideas how to properly fix that problem?

**Comment by Alelight** [comment]
What tools do you need to find the new areatriggers? I have not yet understood the correlation between file db2 (client), what is in the db and what is really triggered.  For example: in AreaTrigger.db2 it exists an area trigger buff, with id=3686 that fortunately works in game(it's a speed buff nearly the alliance flag), but i can't find that in the db. Hotfixes table have: area_trigger, db_area_triggers_25632. AreaTrigger.db2 lines are integrated in the table db_area_triggers_25632. Why this area trigger works even if there isn't any relation in the db? I think I'm missing something...

**Comment by Warpten** [comment]
Wrath: That's because the server doesn't update the fact that you are already in the areatrigger when your team returns the flag. 

Live: Areatriggers moved to server side because the client doesn't need to know about these. That's also how buffs in BGs should be handled, not some ugly proximity hack

**Comment by Golrag** [comment]
The areatriggers for the buffs are still present client side I did something a while ago for trap gameobjects (which they are part of) for 335: https://github.com/Golrag/TrinityCore/commit/c13a5c19c7ee669bc8adc40ff5fbea583a342925

It's weird that they keep them for the buffs tho, maybe someone on the bfa beta can check if they are still there (clientside) ?

**Comment by aquadeus** [comment]
is this fixed after the rewrite?

**Comment by mdX7** [comment]
> is this fixed after the rewrite?

yes
