### ISSUE TITLE
Scripts/Icecrown Citadel: Blood Queen Lana'thel - Vampiric Bite issue

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21537]
**Description:**

After starting the encounter with Lana'thel, the boss use the spell "Vampiric Bite" on a random player, not in the highest threat possible without being the tank, she might bite a healer or a dps that aren't in the top on the highest threat. (Tested with addon Omen)

**Current behaviour:**
Blood Queen Lana'thel isn't biting the highest threat possible excluding the tanks.

**Expected behaviour:**
Blood Queen Lana'thel should bite the highest threat possible excluding the tanks.

**Steps to reproduce the problem:**

1. Start an encounter with Blood Queen Lanathel
2. Let her bite someone 
3. Check the bitten player with the Omen addon, it should present differences with player of the highest threat (Omen) and the bitten player.

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  ad79631

**TDB version:**  335.64

**Operating system:** Win 10 x64

**Comment by pedroevil51** [comment]
We need another threat system rewrite

**Comment by Keader** [comment]
@Treeston (https://github.com/TrinityCore/TrinityCore/issues/21537#issuecomment-408463838)
lul

**Comment by pedroevil51** [comment]
@Keader :( its a joke kaeder-san

**Comment by Keader** [comment]
I wonder, why we use this method here: https://github.com/TrinityCore/TrinityCore/blame/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp#L369
We just need select top threat excluding tank/off tank
i cant see any threat amount check inside method used.

**Comment by Shauren** [comment]
Because the offtank for that encounter is not the second highest threat but player closest to main tank

**Comment by Shauren** [comment]
Because that was supposed to exclude target based on custom offtank rules for that encounter (closest to main tank, not second on threat)

**Comment by Keader** [comment]
Oh yes.
Checking again, we dont use return of this method to chose target of Vampiric Bite, we just use to sort list.
Btw, why method call ```GetUnsortedThreatList()``` if returns ```GetSortedThreatList()```? o.O

**Comment by Keader** [comment]
I was looking into a old core :/

**Comment by Treeston** [comment]
Pre-refactor it returned sorted, now it doesn't, don't rely on it ever returning any particularly structured threat list.
