### ISSUE TITLE
DB/Quest: The Ancient Statuette

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21545]
**Description:**

* Add outro event for quest "The Ancient Statuette"
* Fix NPC flags for Talen and remove wrong gossip text (He didn't have a gossip text before Cataclysm)

Note: I set some of the texts with `BroadcastTextId`=0 because Blizzard changed this quest (and the texts) a little bit after Patch 4.0.3. Before Cataclysm, you were supposed to collect a single statuette, but after Cataclysm you have to collect 10 statuettes, so the texts were modified (basically, they changed them from singular to plural). You can see the texts here:
Before Cataclysm: https://wow.gamepedia.com/Quest:The_Ancient_Statuette
After Cataclysm: https://wow.gamepedia.com/Quest:The_Ancient_Statuettes

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Talen
DELETE FROM `creature_text` WHERE `CreatureID`=3846;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(3846,0,0,"This statuette must hold a hidden compartment....",12,7,100,1,0,0,0,0,"Talen"),
(3846,1,0,"%s searches the ancient statuette.",16,0,100,0,0,0,0,0,"Talen"),
(3846,2,0,"It's locked!  NO!!",12,7,100,15,0,0,0,0,"Talen"),
(3846,3,0,"$n, I am in need of your help once again.",12,7,100,1,0,0,1355,0,"Talen");

DELETE FROM `smart_scripts` WHERE `entryorguid`=3846 AND `source_type`=0 AND `id`=1;
DELETE FROM `smart_scripts` WHERE `entryorguid`=384600 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(3846,0,1,0,20,0,100,0,1007,0,0,0,80,384600,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Quest 'The Ancient Statuette' Finished - Run Script"),
(384600,9,0,0,0,0,100,0,0,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Remove Npc Flag Questgiver"),
(384600,9,1,0,0,0,100,0,0,0,0,0,91,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Remove Flag Standstate 'Sit Down'"),
(384600,9,2,0,0,0,100,0,2000,2000,0,0,66,0,0,0,0,0,0,8,0,0,0,0,0,0,6.16678,"Talen - On Script - Set Orientation"),
(384600,9,3,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Say Line 0"),
(384600,9,4,0,0,0,100,0,4000,4000,0,0,90,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Set Flag Standstate 'Kneel'"),
(384600,9,5,0,0,0,100,0,1000,1000,0,0,50,18603,12,0,0,0,0,8,0,0,0,3471.69,846.893,5.39909,4.67058,"Talen - On Script - Summon Gameobject 'Ancient Statuette'"),
(384600,9,6,0,0,0,100,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Say Line 1"),
(384600,9,7,0,0,0,100,0,8000,8000,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Say Line 2"),
(384600,9,8,0,0,0,100,0,4000,4000,0,0,91,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Remove Flag Standstate 'Kneel'"),
(384600,9,9,0,0,0,100,0,2000,2000,0,0,66,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Set Orientation"),
(384600,9,10,0,0,0,100,0,0,0,0,0,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Say Line 3"),
(384600,9,11,0,0,0,100,0,0,0,0,0,82,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Add Npc Flag Questgiver"),
(384600,9,12,0,0,0,100,0,20000,20000,0,0,90,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Talen - On Script - Set Flag Standstate Sit Down");

UPDATE `creature_template` SET `npcflag`=2, `gossip_menu_id`=0 WHERE `entry`=3846; -- Fix NPC flag and remove gossip

**Comment by tkrokli** [comment]
Yes, it looks like the 3.3.5a `broadcast_text` lines were replaced/overwritten by the Cataclysm version when the DB was mass updated with build `18019` content (or maybe the 3.3.5a content was not even there before). I don't know if we have got sniffs containing the pre-Cataclysm texts.

**Comment by offl** [comment]
You can change the broadcast texts.

**Comment by tkrokli** [comment]
Sure, but I don't remember if TC has got a requirement for sniffs as base for such a change.

**Comment by ZenoX92** [comment]
I'm not sure if changing the broadcast texts is allowed, but what's the point in that anyway? As far as I know, the broadcast text ID in the `creature_text` table is used only for translating the texts into other languages, so if you change the broadcast texts, you'll have to change the broadcast text locales as well, or else the translation will be wrong. I would make the translations but I only speak Spanish (and English, of course).

**Comment by Aokromes** [comment]
no it's not.  broadcast_text source is post cata, if BroadcastTextId is replaced on cata BroadcastTextId must be 0 and use the correct creature_text.
