### ISSUE TITLE
DB/Text: Blastmaster Emi Shortfuse

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21543]
**Description:**

* Fix `Language` and `BroadcastTextId` for two of Blastmaster Emi Shortfuse's texts.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Blastmaster Emi Shortfuse
UPDATE `creature_text` SET `Text`="FIRE IN THE HOLE!", `Language`=0, `BroadcastTextId`=4137 WHERE `CreatureID`=7998 AND `GroupID`=11;
UPDATE `creature_text` SET `BroadcastTextId`=4207 WHERE `CreatureID`=7998 AND `GroupID`=13;

**Comment by TecDian** [comment]
I confirm the issue - have wanted to report this for a long time, but never did.
I also confirm the fix suggested. It's correct and it works.
