### ISSUE TITLE
[3.3.5] Player not dismounted inside houses

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21550]
**Description:**

You can run with mount into the houses on the battlefield like berserker or healing, the small ones, and you dont get dismounted.

**Current behaviour:**

You can run with mount into the houses on the battlefield like berserker or healing, the small ones, and you dont get dismounted.

**Expected behaviour:**

shouldnt be able to mount inside thouse houses

**Steps to reproduce the problem:**

1. run with mount into any of the wsg houses

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/ad796318e8c34df177a935892f27c6a7b4f2f901

**TDB version:**  
64
**Operating system:** 

ubuntu

**Comment by tkrokli** [comment]
TrinityCore rev. ad796318e8c3 2018-03-02 02:57:23 -0300 (3.3.5 branch) (Win64, Release, Static)

If you ride a flying mount and enter any house in Outland, you will not get dismounted either.
The player can keep flying as long as still riding the mount used outdoors.

**Comment by Warpten** [comment]
Summoning @Golrag

**Comment by Aokromes** [comment]
I am instant dismounted on shattrah's bank while using headless horseman mount or traveler's tundra mamouth.

**Comment by Tatara902** [comment]
You can test in the Auction House of orgrimmar and even in instances like Icecrown Citadel and Ulduar(Antechamber)

**Comment by Aokromes** [comment]
367db4e
