### ISSUE TITLE
[3.3.5] Disarm prevents totems from being summoned

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21552]
**Description:**

Whenever a shaman gets disarmed, he cannot put down totems for the disarm duration.

**Current behaviour:**

Whenever a shaman gets disarmed, he cannot put down totems for the disarm duration. 

Note: You must have the Totem equipped, if it is in my bag, I can summon totems just fine o.0 even while disarmed.

* suggested fix *

Change GetUseableItemByPos to GetItemByPos in bool Player::HasItemFitToSpellRequirements(SpellInfo const* spellInfo, Item const* ignoreItem) const

**Expected behaviour:**

Shaman should still be able to put down totems while disarmed.

**Steps to reproduce the problem:**

1. Cast disarm on shaman who has totem equipped in relic slot.
2. Try to summon a totem.

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/367db4e1d641b56d8d7df83320c14b283bd007ce

**TDB version:**  64

**Operating system:** ubuntu

**Comment by tkrokli** [comment]
Which one of the 4 `GetUseableItemByPos` are you referring to, 1, 2, 3 or all 4 of them?
https://github.com/TrinityCore/TrinityCore/blob/367db4e1d641b56d8d7df83320c14b283bd007ce/src/server/game/Entities/Player/Player.cpp#L23426-L23479

Would it be of any use to look at this section,
https://github.com/TrinityCore/TrinityCore/blob/367db4e1d641b56d8d7df83320c14b283bd007ce/src/server/game/Entities/Player/Player.cpp#L10268-L10296

or maybe even this section?
https://github.com/TrinityCore/TrinityCore/blob/367db4e1d641b56d8d7df83320c14b283bd007ce/src/server/game/Entities/Player/Player.cpp#L9856-L9899

**Comment by Persephone** [comment]
Ah sorry i meant hastotemcagetory changed it there

**Comment by tkrokli** [comment]
Very well, but you still need to be more specific. There are three (3) entries of `GetUseableItemByPos` in that section. Please comment with a code block example (diff or cpp) or tell us if you mean all 3 `GetUseableItemByPos` entries.

**Comment by Killyana** [comment]
A similar issue was closed https://github.com/TrinityCore/TrinityCore/issues/6780

**Comment by ariel-** [comment]
Indeed. proof: 
http://www.arenajunkies.com/topic/198811-dismantle/

> This is correct. blizzard thought if you are disarmed you have no weapons, and totems can be a weapon. a defensive weapon aswell as a offensive weapon. Therefor you couldn't drop totems while dismanteled.
