### ISSUE TITLE
Scripts/Zul Aman: boss Zul'jin resets after changing form

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21564]
**Description:**

When you start an encounter with the last boss of Zul'Aman, after some time of the battle, the boss resets and goes back to the initial position with a full hp bar. It happens when he switches to another form, but he doesn't find a target and goes back to the initial point.

**Current behaviour:**
Zul'Jin resets after changing form, going back to the initial point and players are not able to kill him.

**Expected behaviour:**
Zul'Jin should not reset after changing form, players should be able to finish killing him at that point.

**Steps to reproduce the problem:**

1. Go to Zul'Aman instance and find a way to the last boss
2. Start the fight with Zul'Jin and continue until form change.
3. Let him change form and watch what happens next.

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  b5f0fd1

**TDB version:**  335.64

**Operating system:**  Win 10 x64

**Comment by tkrokli** [comment]
Very well. I see you have noticed (#21571) that this could be a general issue, although we don't know exactly what yet.

**Comment by Tatara902** [comment]
Just removed " ResetThreatList(); " in line 305 of boss_zuljin and it works, when he changed his form he just resets.
