### ISSUE TITLE
[3.3.5] Core/Spells: Inner Focus

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21567]
**Description:**

Casting inner focus (https://wotlk.evowow.com/?spell=14751)
makes the character do the animation but he doesnt get the buff.
Perhaps its consuming itself?

**Expected behaviour:**

If you do .aura 14751 you do get the aura tho, and the buff works. For some reason casting it wont give the buff tho.

**Steps to reproduce the problem:**

1. create a priest and cast https://wotlk.evowow.com/?spell=14751 

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/171583b9844f86301afbf5fba9c3778ce6252b38

**TDB version:** 335.64

**Operating system:** ubuntu

**Comment by Persephone** [comment]
Summoning @ariel-

**Comment by Persephone** [comment]
Yep i found the error, its consuming itself.

`ApplySpellFix({
        14751 // fix inner focus so it doesnt consume itself
        }, [](SpellInfo* spellInfo)
    {
        spellInfo->SpellFamilyFlags[1] = 0;
        spellInfo->SpellFamilyFlags[2] = 0;
    });`

**Comment by tkrokli** [comment]
I will wait for someone who knows to say if this is a valid solution.

**Comment by Persephone** [comment]
Seems odd if it is tho, i just noticed that it had itself as a proc target in Effects[0] and Effects[1] so tried removing the family flags and it worked. But seems like a hack to me :P

**Comment by tkrokli** [comment]
You may want to check out PR https://github.com/TrinityCore/TrinityCore/pull/21260 **Core/Spells: proc updates**

**Comment by Persephone** [comment]
Yeah just did that pr seems to address a lot of the current issues, why aint it merged :3!?

**Comment by tkrokli** [comment]
Usually because it needs more research & testing, but also things take time.
Feel free to test the current PR content in a branch of your local source.
Feedback from testing is very much appreciated.
Also note the High priority PR referenced by ariel- in the comment after yours.

**Comment by Killyana** [comment]
Cannot reproduce on rev. ecea2d62657e

**Comment by kvipka** [comment]
![default](https://user-images.githubusercontent.com/2619928/37224024-544c7f8a-23e3-11e8-87d4-78ec447c5d44.png)
pls don't use this shit, use dbwotlk.com

**Comment by tkrokli** [comment]
Well, if that is meant for @Persephone , I suppose I could suggest a couple of sites we're already using:
- https://woehead.way-of-elendil.fr/?spell=14751
- https://reinosdeleyenda.org/aowow/?spell=14751
- https://db.rising-gods.de/?spell=14751

(for spells, items, quests etc. which is no longer found or changed too much on www.wowhead.com)
The TC owners most likely have got useful sites to recommend as well.
***
Also, @kvipka , we do our best to avoid unrelated comments in the issue tracker.

**Comment by kvipka** [comment]
@tkrokli  no trouble =) pls keep this politic on tracker for all ppl and remove all information with advertisment
