### ISSUE TITLE
Lich King Issues after Fury of Frostmourne

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21571]
**Description:**

After you damage Lich King to 10 % and he cast Fury of Frostmourne, if everybody dies in the raid, the HP bar of the boss reset and you have to kill him 100% to 0% (He keeps levitating after Terenas ress and he doesn't attack players)

**Current behaviour:**

Hp bar of Lick King resets after killing all players in 4th phase (10%) so you have to get him down again.

**Expected behaviour:**

Lich king only should have 10 % of HP when Terenas ress all the raid ending the encounter.

**Steps to reproduce the problem:**

1. Step 1 Phase Lich king to 10 % 
2. Step 2 Let everybody of the raid die.
3. Step 3 Watch how the hp bar of the boss resets

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
e9aba10

**TDB version:**   335.64

**Operating system:** Win 10 x64

**Comment by Aokromes** [comment]
update your core.

**Comment by Killyana** [comment]
Confirm on rev. 7452074829c2

**Comment by Treeston** [comment]
Sounds like script issue, he should reset properly.

**Comment by Shauren** [comment]
He should **_NOT_** reset

**Comment by Treeston** [comment]
Oh, wait, he goes to 100% if people die to Fury? Thought you meant people dying after Terenas' rez.

Curious what's up with that. Maybe Terenas doesn't keep him in combat?

**Comment by Killyana** [comment]
Once Fury of Frostmourne is casted an all players are dead he get out of combat.

**Comment by Aokromes** [comment]
#21572  related?

**Comment by Tatara902** [comment]
Can be related with #21564 ?

**Comment by Nitair** [comment]
@Killyana (https://github.com/TrinityCore/TrinityCore/issues/21571#issuecomment-371836596) Maybe he should stay in fight with Tirion ?

**Comment by Keader** [comment]
UpdateVictim() is not called after fury of frostmourne call.
It's not script issue, it's core issue.

**Comment by pedroevil51** [comment]
Any news on this? i would pay anyone who wants to spend time and fix this here , 50$

**Comment by Treeston** [comment]
Put a bounty on it?

**Comment by Keader** [comment]
@treeston
IDK if is this case, but I got some issues in lich King, he resetting up caused by that "fake evade" when creature cant reach a target

**Comment by pedroevil51** [comment]
@Treeston i would but nobody works on bounty..

**Comment by TheWinchesters** [comment]
I would like to pay too using the bounty system or anything but I do not know if there is any news about this issue

**Comment by illfated** [comment]
Link to this issue on www.BountySource.com in case anyone decides to post a bounty:
https://www.bountysource.com/issues/55993035-lich-king-issues-after-fury-of-frostmourne

**Comment by joshwhedon** [comment]
So he exits combat ? Or he just regenerates ? IS the boss still in combat with something when this happens ? What is the behaviour on retail, is he still in combat or he exits combat and should just not regenerate ?

**Comment by Killyana** [comment]
On TC he exists combat and this cause the health regen, I don't know if he must be keept in combat, with  Tirion or not.
