### ISSUE TITLE
Core/Spell: Power Word: Shield

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21577]
**Description:** Cast the spell https://woehead.way-of-elendil.fr/?spell=17 on your char (priest) or any other friendly target, the target will get the debuff Weakened Soul, but the shield will appear only when Weakened Soul expire

**Current behaviour:** Power Word: Shield is casted when Weakened Soul expire

**Expected behaviour:** Power Word: Shield must be applied with Weakened Soul.

**Steps to reproduce the problem:**

1. connect a priest
2. cast Power Word: Shield

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. ecea2d62657e

**Comment by ariel-** [comment]
Ah, ugly m_preCastSpell logic
