### ISSUE TITLE
Core/Spells: Spells cannot target npcs with UNIT_FLAG_NOT_SELECTABLE or UNIT_FLAG_IMMUNE_TO_NPC

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21579]
**Description:** After last changes some spells like https://woehead.way-of-elendil.fr/?spell=52683 cannot target npcs that have UNIT_FLAG_NOT_SELECTABLE or UNIT_FLAG_IMMUNE_TO_NPC or both.

If we remove this flags, the npc 28889 will be able to cast the spell via the sai script.
``` sql
UPDATE `creature_template` SET `unit_flags`=0 WHERE `entry` IN (28886,28892,28896,28898);
```
But if I try to cast it with .cast 52683  it tells me I don't have a target.

**Steps to reproduce the problem:**
1. .go c 82879
2. notice the npc will not cast 52683 
3. Remove this unitflags and mod fac 35 this npcs (to avoid combat) and the spell will be casted
4. Try .cast 52683  near creature guid 82879 and notice the error

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. ecea2d62657e

**Comment by Keader** [comment]
Maybe some variance of this bug, is causing xt002 issues? (https://github.com/TrinityCore/TrinityCore/pull/21566#issuecomment-371934427)
