### ISSUE TITLE
Scripts/Naxxramas: Noth the Plaguebringer gets stuck

### ISSUE THREAD

**Issue by Cyclone47** [TrinityCore/TrinityCore#21572]
**Description:**
 Noth the Plaguebringer gets stuck in phase 2 upon teleporting back from the balcony to the room

**Current behaviour:**
 Noth the Plaguebringer gets stuck in phase 2 upon teleporting back from the balcony to the room
This happens when a pet such as a warlock imp or a hunter pet is attacking the boss. The pet will start moving forwards and backwards really fast. Noth will then remain stuck.

**Expected behaviour:**
Noth should teleport downstairs and the fight should continue.

**Steps to reproduce the problem:**

Start fighting Noth The Plaguebringer. Set your pet on aggressive and make it attack Noth.
Wait for Noth to teleport to the balcony.
Wait for Noth to teleport back down.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**

TrinityCore rev. 7452074829c2 2018-03-09 00:38:20 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:** TDB 335.64

**Operating system:** Server 2012

**Comment by tkrokli** [comment]
Hmm, if it wasn't for the fact that the issue **Core/Movement: waypoint system issues [45$]** #20310 is closed already, I would have said that this issue belongs there. Not sure about this one until someone else can confirm it on updated TC source.

BTW, could you check if the exact same issue happens with the newest commits pushed to `3.3.5` today?

**Comment by Infinito47** [comment]
I'll test this evening.

**Comment by Infinito47** [comment]
I noticed weird pet behaviour on every boss so far that teleports away or becomes unreachable.  

Such as Anub'arak in Azjol Nerub.  Pets will start running crazy over the ground. Like the pet keeps trying to attack it and doesn't reset.

**Comment by Faq** [comment]
let's keep one problem per issue and try with today's latest commit

**Comment by Aokromes** [comment]
I suppose it's one generic bug  #21571

**Comment by Infinito47** [comment]
Issue still happening on 
TrinityCore rev. e7e46b2a822c 2018-03-10 13:31:49 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Comment by Xatmo980** [comment]
i fixed it in a hacky way i noticed that in the code he gets set the un attackable flag when he goes up to the balcony but for some reason the flag does not get removed when he comes back down even tho in the code it shows it should... i just removed the part that makes him un attackable in the first place lol

**Comment by illfated** [comment]
@Xatmo980 : Are you sure you are using the current code? Your code looks different from the TC 3.3.5 source code, based on commit https://github.com/TrinityCore/TrinityCore/commit/cdf4040f4fce4f1e5ebb33525c4618845605081c :
https://github.com/TrinityCore/TrinityCore/blob/cdf4040f4fce4f1e5ebb33525c4618845605081c/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L245-L328
If you read the entire file
https://raw.githubusercontent.com/TrinityCore/TrinityCore/cdf4040f4fce4f1e5ebb33525c4618845605081c/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp
you will notice that `UNIT_FLAG_IMMUNE_TO_PC` is not found anywhere in that file now.
See also commit https://github.com/TrinityCore/TrinityCore/commit/74af880217fc567c9949d7557408718af889402f#diff-ba2ea5a1fcd441bf72d646496a2199d9 from July 9, 2017 to find out when it was removed.

Are you using a really really old script base or simply a heavily modified one?

**Comment by Xatmo980** [comment]
ill take a close look i thought my code was current if not i apologiz. tho the pervious person stated 5 days ago it still happends i can throw in the code thats in the current state of the script and retest to see if it still persists

**Comment by illfated** [comment]
Fair enough. I presume something unexpected is going on in the code and it is preventing the call to unset the immunity.

**Comment by Killyana** [comment]
This looks more as a script issue as the boss keeps:

UNIT_FLAG_IMMUNE_TO_PC (0x100)
UNIT_FLAG_NOT_SELECTABLE (0x2000000)

Even if the combat stops.

**Comment by illfated** [comment]
Looks like the script needs to be tested with code added (some kind of debug functionality) to tell if the script ever reaches the part where the immunity should be removed.

**Comment by Cobus420** [comment]
Still happen on latest rev. [310296f](https://github.com/TrinityCore/TrinityCore/commit/310296f48f8563f138d3d4502b8e1e12112cb0f6)
(3.3.5 branch) (Win64, RelWithDebInfo, Static) 

You can see that he cast the spell where he want to teleport back. And then there it stops. 
Noth still follows you when you fly up to him. But He dosnt attack and is still not selectable.

**Comment by Killyana** [comment]
this reset is not executed https://github.com/TrinityCore/TrinityCore/blob/cdf4040f4fce4f1e5ebb33525c4618845605081c/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L98
related to https://github.com/TrinityCore/TrinityCore/issues/23008

**Comment by Cobus420** [comment]
#23008 is closed and merged on #23197 but Noth still stuck at same Point here with me. Using rev. [7807016](https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7)
(3.3.5 branch) (Win64, RelWithDebInfo, Static) 
Can we open this again?

**Comment by Cobus420** [comment]
Can we re-open this? #23008 was merged but the bug with Noth still appears as known on latest 
rev. [00e98a3](https://github.com/TrinityCore/TrinityCore/commit/00e98a34c127b3308d0ef3accf7ea1a2bb999085)
(3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Comment by Killyana** [comment]
I tried to reproduce the issue again, The boss never get stuck.
Provide the exact steps to reproduce the issue.

**Comment by RowinRuizendaal** [comment]
Still having this issue at latest rev

**Comment by WoWPortal** [comment]
The problem here is DoCastAOE(SPELL_TELEPORT_BACK); and  me->SetImmuneToPC(false);

**Comment by illfated** [comment]
Thanks for the update. BTW, that code you refer to is found twice: 1st in `void Reset() override` and 2nd in `switch (eventId)`:
https://github.com/TrinityCore/TrinityCore/blob/49d0a5bbb69dd352bac0009625ded2c472b66805/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L98-L117

https://github.com/TrinityCore/TrinityCore/blob/49d0a5bbb69dd352bac0009625ded2c472b66805/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L296-L308

**Comment by junker1609** [comment]
> Thanks for the update. BTW, that code you refer to is found twice: 1st in `void Reset() override` and 2nd in `switch (eventId)`:
> https://github.com/TrinityCore/TrinityCore/blob/49d0a5bbb69dd352bac0009625ded2c472b66805/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L98-L117
> 
> https://github.com/TrinityCore/TrinityCore/blob/49d0a5bbb69dd352bac0009625ded2c472b66805/src/server/scripts/Northrend/Naxxramas/boss_noth.cpp#L296-L308

Doesnt work for me, he stayed on the balcony.

**Comment by illfated** [comment]
Not intended to suggest any solution, I was only linking the current source code.
I linked 2 sections because I don't know which one @xParad0x refers to.

**Comment by junker1609** [comment]
So we dont have a solution yet.

**Comment by illfated** [comment]
Appears so, although I have not tested this myself (and it is not high on my own list of priorities).
I notice that this issue got closed on Apr 20, 2019, with a reference to #23008 (which in turn got closed by the PR #23197 and its commit https://github.com/TrinityCore/TrinityCore/commit/56b65329e5dc2fb04d5b1d6068d957490146ee89), but apparently, you still seem to have this issue.

Please note: If you want this issue ticket to be reopened, you need to provide **exact** steps to reproduce that issue.
Otherwise, you may want to open a new and well-documented issue ticket, where all steps are carefully described.

**Comment by Killyana** [comment]
Please stop commenting in close issues.
We have already an open ticket #23909
