### ISSUE TITLE
[DEV] Core/GameObject: Gameobjects casting spells

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21580]
**Description:** Gameobjects that must cast spell, check the faction before casting the spell, but as most have faction=0, the cast fails.
``` sql
SELECT * FROM `gameobject_template` WHERE entry IN (191609); -- spell 51888
Error:  GameObject (template id: 191609) has invalid faction (faction template id) #0
```

**Steps to reproduce the problem:**

1. Take the quest http://www.wowhead.com/quest=12641/death-comes-from-on-high
2. Use the gob to summon the eye
3. the gob will not cast the spell 51888 and you will get the error: GameObject (template id: 191609) has invalid faction (faction template id) #0

**Branch(es):** 3.3.5

**TDB version:**  rev. d007d94d2cf

**Comment by tkrokli** [comment]
Will it be necessary to look for the GO factions in sniffs, or can their faction be assigned as Hostile or Friendly?

**Comment by ariel-** [comment]
The problem here with that particular spell is that it's failing LOS checks.

**Comment by Killyana** [comment]
About Los for gameobjects almost all have DATA used to handle the los
Example: for 191609
10 GAMEOBJECT_TYPE_GOOBER 
DATA16= requireLOS; // 16 require LOS, enum { false, true, }; Default: false
