### ISSUE TITLE
Quest: 9600 - Redemption

### ISSUE THREAD

**Issue by Animalthug** [TrinityCore/TrinityCore#21585]
**Description:**

QUEST: 9600 Redemption
NPC: 17509 Jol
Draenei specific paladin quest to receive spell "Redemption"

"Jol wants you to resurrect a Young Furbolg Shaman with the Symbol of Life and return to her."

**Current behaviour:**

On use "6866 - Symbol of Life",
Does not register a target (you can use the item without any target selected.)
Does not register targeted NPC 17542 - Young Furbolg Shaman (quest objective)
Apon cast completion character states "I need to target something"

**Expected behaviour:**

Cast when selected NPC 17542 - Young Furbolg Shaman is targeted
Revive NPC 17542 - Young Furbolg Shaman upon completion of cast

**Steps to reproduce the problem:**

1. Create Draenei Paladin
2. Level to 12
3. Travel to Exodar and speak to NPC: 17509 Jol
4. Travel to Bloodmyst Isle to resurrect NPC 17542 - Young Furbolg Shaman

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 02f1399fde00 2018-03-10 20:51:14 -0300 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  335.64

**Operating system:** Windows 10 64

**Comment by Aokromes** [comment]
update your core before reporting bugs.

**Comment by Animalthug** [comment]
Will do, thank you.
