### ISSUE TITLE
Training Dummy gets disoriented from Dark Edge of Insanity proc

### ISSUE THREAD

**Issue by Pugnadeus** [TrinityCore/TrinityCore#21582]
**Description:**

The Training Dummy gets disoriented from the proc of the weapon Dark Edge of Insanity

**Current behaviour:**

The effect procs and the training dummy gets disoriented, it starts moving around

**Expected behaviour:**

Training Dummy should stand on one spot, it shouldn't move if it gets disoriented.

**Steps to reproduce the problem:**

Equip Dark Edge of Insanity (ID: 21134) and start auto attacking the dummy.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ad796318e8c3 2018-03-02 02:57:23 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:** TDB_full_world_335.64_2018_02_19

**Operating system:** Windows 10 64-bit

**Comment by Aokromes** [comment]
#21513
