### ISSUE TITLE
Server Crash related to SpellAuras

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#21588]
Branch(es): 3.3.5

Revision: TrinityCore rev. a891eb364e94+ 2018-03-11 13:23:23 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

gist link: https://gist.github.com/daddycaddy/56150ad652687d540f625211a7a4adcf

message in-game server when it crashes: a path to SpellAuras.cpp:581 in Aura::_UnapplyForTarget ASSERTION FAILED: auraApp->GetRemoveMode<>

**Comment by Persephone** [comment]
Since the spell-system rewrite server has become very unstable, dunno if related to this one

**Comment by ariel-** [comment]
> a891eb3+

What custom changes do you have?

PS: delete template is evil

**Comment by tje3d** [comment]
@ariel- nevermind, keep up the good work
