### ISSUE TITLE
Gameobject/Script: Broggok

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21589]
**Description:** If the group wipes the boss reset, npcs respawn and the door close, but the levier [Cell Door Lever] GUID: 150441 ID: 181982 doesn't respawn.

**Current behaviour:** GUID: 150441 ID: 181982 doesn't respawn after a wipe.

**Expected behaviour:** GUID: 150441 ID: 181982 must respawn after a wipe.

**Steps to reproduce the problem:**

1. .go obj 150441 
2. use the levier and kill the npcs until the boss aggro
3. .gm on
4. notice every thing is reset but the levier doesn't respawn

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp#L153-L156

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. a891eb364e94

**Comment by offl** [comment]
The lever shouldn't despawn at all. Probably even after a week.

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/c71e36acaea9c04e63dcba9a39b5a6a76e3cac75#diff-71f0dbd6c5a0bebf11dfc16eda2993ae
