### ISSUE TITLE
[3.3.5] Magic Rooster Crashes Client

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21597]
**Description:**

When you mount up on http://www.wowhead.com/item=46778/magic-rooster-egg it gives you 2 buffs. Right clicking any of them makes the game crash, not the server, but the client.

http://prntscr.com/iq22mo

**Expected behaviour:**

Your not supposed to get 2 buffs from mounting up on a mount, and shouldnt crash the client wen trying to dismount it :P

**Steps to reproduce the problem:**

1. Mount up on http://www.wowhead.com/item=46778/magic-rooster-egg
2. Right click on any of the two buffs to try and dismount
3. client will freeze and crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/ef4b1492e18c9573c38605b026106ee6d80e4863

**TDB version:**  64

**Operating system:** unbuntu

**Comment by Kittnz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/1822

**Comment by Aokromes** [comment]
different bug

**Comment by gangscape** [comment]
Resetting instances also crashes the client in latest build.
