### ISSUE TITLE
Core/Unit:  Creture with UNIT_FLAG_PACIFIED enter combat mode

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21592]
**Description:** Npcs with unit_flags UNIT_FLAG_PACIFIED enter combat mode.

**Steps to reproduce the problem:**

1.  .go c id 24248
2. .gm off 
3. .mod pha 2
4. notice the lich king is in combat even if he's pacified

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. a891eb364e94

**Comment by Ovahlord** [comment]
Afaik pacify is not responsible to block engages, it's suposed to disable melee attacks.
There are some bosses like Siamat who pacify themself to block their melee attacks while they are in combat

**Comment by Killyana** [comment]
Yes, looks to be related to something else
