### ISSUE TITLE
[master] npc_vendor update (part1)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21604]
**Description:**

https://gist.github.com/funjoker/710115f9f715e6887743c9e15c795f8e

**Branch(es):**

master

**TC rev. hash/commit:** 

12beb3dd1b5166481ed68f945b4294ff4aca9000

**TDB version:**  735

**Comment by shamage** [comment]
I have found some matches but it is necessary that somebody else besides me has confirmed that it is right.

32   (37674, 27, 151615, 0, 5791, 1, 0, 0, 25881), -- Weathered Heirloom Scabbard
36   (37674, 23, 142341, 0, 3690, 1, 0, 0, 25881), -- Love Boat
37   (37674, 22, 144339, 0, 6149, 1, 0, 0, 25881), -- Sturdy Love Fool
80   (52029, 10, 146437, 0, 6012, 1, 0, 0, 25881), -- Bloodthirsty Gladiator's Silk Armor
83   (6294, 8, 150743, 0, 6196, 1, 0, 0, 25881), -- Surviving Kalimdor
84   (6294, 7, 150746, 0, 6196, 1, 0, 0, 25881), -- To Modernize the Provisioning of Azeroth
86   (6294, 5, 151614, 0, 6195, 1, 0, 0, 25881), -- Weathered Heirloom Armor Casing
320   (73190, 10, 152870, 0, 5214, 1, 0, 0, 25881), -- Vicious War Fox
321   (73190, 9, 142234, 0, 5214, 1, 0, 0, 25881), -- Vicious War Bear
322   (73190, 8, 142237, 0, 5214, 1, 0, 0, 25881), -- Vicious War Lion
323   (73190, 7, 143648, 0, 5214, 1, 0, 0, 25881), -- Vicious War Turtle
324   (119390, 4, 146317, 0, 6189, 1, 0, 0, 25881), -- Mr. Smite's Supplies
325   (119390, 3, 150742, 0, 6189, 1, 0, 0, 25881), -- Pet Reaper 0.9
326   (119390, 2, 150741, 0, 6190, 1, 0, 0, 25881), -- Tricorne
327   (119390, 1, 150739, 0, 6191, 1, 0, 0, 25881), -- Pocket Cannon
539   (54660, 11, 146641, 0, 5981, 1, 0, 0, 25881), -- Vicious Gladiator's Weapons
540   (54660, 10, 146537, 0, 6012, 1, 0, 0, 25881), -- Vicious Gladiator's Silk Armor
672   (69974, 11, 146640, 0, 5981, 1, 0, 0, 25881), -- Ruthless Gladiator's Weapons
673   (69974, 10, 146517, 0, 6012, 1, 0, 0, 25881), -- Ruthless Gladiator's Silk Armor
770   (54442, 9, 151116, 0, 6211, 1, 50225, 0, 25881), -- Fashionable Undershirt
771   (54442, 8, 151120, 0, 6188, 1, 9206, 0, 25881), -- -Righteous Battleplate
772   (54442, 7, 151119, 0, 6188, 1, 4617, 0, 25881), -- Der'izu Armor
773   (54442, 6, 151118, 0, 6188, 1, 17097, 0, 25881), -- Obsidian Prowler's Garb
774   (54442, 5, 151117, 0, 6188, 1, 0, 0, 25881), -- Mana-Etched Regalia
775   (54442, 4, 157577, 0, 6188, 1, 9206, 0, 25881), -- Goldspine Plate
776   (54442, 3, 157576, 0, 6188, 1, 4617, 0, 25881), -- Crimson Sentinel Garb
777   (54442, 2, 157574, 0, 6188, 1, 17097, 0, 25881), -- Tundraspite Armor
778   (54442, 1, 157573, 0, 6188, 1, 0, 0, 25881), -- Mindwrack Raiment
927   (69975, 11, 146639, 0, 5981, 1, 0, 0, 25881), -- Cataclysmic Gladiator's Weapons
928   (69975, 10, 146457, 0, 6012, 1, 0, 0, 25881), -- Cataclysmic Gladiator's Silk Armor

**Comment by tkrokli** [comment]
Pro tip: add 3 back ticks + sql ( **```sql** ) in on a blank line on top of your code block to highlight the SQL syntax.

**Comment by funjoker** [comment]
```sql
INSERT INTO `pro_tips` (`ID`, `Sensei`, `Tip`) VALUES
(1, "tkrokli", "Pro tip: add 3 back ticks + sql ( ```sql ) in on a blank line on top of your code block to highlight the SQL syntax");
```

:D

**Comment by shamage** [comment]
I therefore have to think as follows : 

```
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `ExtendedCost`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `VerifiedBuild`) VALUES

(37674, 27, 151615, 0, 5791, 1, 0, 0, 25881), -- Weathered Heirloom Scabbard
(37674, 23, 142341, 0, 3690, 1, 0, 0, 25881), -- Love Boat
(37674, 22, 144339, 0, 6149, 1, 0, 0, 25881), -- Sturdy Love Fool
(52029, 10, 146437, 0, 6012, 1, 0, 0, 25881), -- Bloodthirsty Gladiator's Silk Armor
(6294, 8, 150743, 0, 6196, 1, 0, 0, 25881), -- Surviving Kalimdor
(6294, 7, 150746, 0, 6196, 1, 0, 0, 25881), -- To Modernize the Provisioning of Azeroth
(6294, 6, 151615, 0, 6194, 1, 0, 0, 25881), -- Weathered Heirloom Scabbard
(6294, 5, 151614, 0, 6195, 1, 0, 0, 25881), -- Weathered Heirloom Armor Casing
(73190, 10, 152870, 0, 5214, 1, 0, 0, 25881), -- Vicious War Fox
(73190, 9, 142234, 0, 5214, 1, 0, 0, 25881), -- Vicious War Bear
(73190, 8, 142237, 0, 5214, 1, 0, 0, 25881), -- Vicious War Lion
(73190, 7, 143648, 0, 5214, 1, 0, 0, 25881), -- Vicious War Turtle
(119390, 4, 146317, 0, 6189, 1, 0, 0, 25881), -- Mr. Smite's Supplies
(119390, 3, 150742, 0, 6189, 1, 0, 0, 25881), -- Pet Reaper 0.9
(119390, 2, 150741, 0, 6190, 1, 0, 0, 25881), -- Tricorne
(119390, 1, 150739, 0, 6191, 1, 0, 0, 25881), -- Pocket Cannon
(54660, 11, 146641, 0, 5981, 1, 0, 0, 25881), -- Vicious Gladiator's Weapons
(54660, 10, 146537, 0, 6012, 1, 0, 0, 25881), -- Vicious Gladiator's Silk Armor
(69974, 11, 146640, 0, 5981, 1, 0, 0, 25881), -- Ruthless Gladiator's Weapons
(69974, 10, 146517, 0, 6012, 1, 0, 0, 25881), -- Ruthless Gladiator's Silk Armor
(54442, 9, 151116, 0, 6211, 1, 50225, 0, 25881), -- Fashionable Undershirt
(54442, 8, 151120, 0, 6188, 1, 9206, 0, 25881), -- Righteous Battleplate
(54442, 7, 151119, 0, 6188, 1, 4617, 0, 25881), -- Der'izu Armor
(54442, 6, 151118, 0, 6188, 1, 17097, 0, 25881), -- Obsidian Prowler's Garb
(54442, 5, 151117, 0, 6188, 1, 0, 0, 25881), -- Mana-Etched Regalia
(54442, 4, 157577, 0, 6188, 1, 9206, 0, 25881), -- Goldspine Plate
(54442, 3, 157576, 0, 6188, 1, 4617, 0, 25881), -- Crimson Sentinel Garb
(54442, 2, 157574, 0, 6188, 1, 17097, 0, 25881), -- Tundraspite Armor
(54442, 1, 157573, 0, 6188, 1, 0, 0, 25881), -- Mindwrack Raiment
(69975, 11, 146639, 0, 5981, 1, 0, 0, 25881), -- Cataclysmic Gladiator's Weapons
(69975, 10, 146457, 0, 6012, 1, 0, 0, 25881), -- Cataclysmic Gladiator's Silk Armor
```
