### ISSUE TITLE
[3.3.5] Core/Spells: improved Devouring Plague and Glyph of Power Word: Shield

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21602]
**Description:**

Improved devouring plague and glyph of power word shield applies their procs twice. You get insane amount of damage from the imp dp talent and glyph heals you twice, both seem to be going off twice.

Picture here of the proc blowing off twice: almost every cast it triggers twice.

EDIT: After a bit research, i saw that devouring plague procs twice after you cast it once, as soon as the target has the periodic debuff the 2nd time you cast dp it procs the IMP DP talent twice. Same with Glyph of Power Word Shield, 2nd time you apply it, it heals you twice.

http://prntscr.com/iqbrbf 

**Expected behaviour:**

Shouldnt proc twice

**Steps to reproduce the problem:**

1. Spec into Talent or add the glyph and make em proc normally, theyll be doing twice the damage / heal they are supposed to do.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/6414e456ec60cd33460ecda4582f8e035198be28

**TDB version:**  64

**Operating system:** ubuntu

**Comment by tkrokli** [comment]
Direct link (from viewed page source): https://image.prntscr.com/image/Zl64DLHqQfKUmtyGRjqw_Q.png
