### ISSUE TITLE
[Crash] - UnitAura::AddStaticApplication

### ISSUE THREAD

**Issue by Strazhnik** [TrinityCore/TrinityCore#21609]
**Description:**

Crash in Valithria Dreamwalker

**Current behaviour:**

https://gist.github.com/Strazhnik/d1ef145c429e453fc6f066e76d703cfb

**Steps to reproduce the problem:**

1. Config: hp = 0.51, damage = 0.1 (and default)
2. Several time heal Valithria and continue to kill mobs 
3. Crash

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
b978b673a9053bb0d7bd63ed9261117dc7845742

**TDB version:** 
 b978b673a9053bb0d7bd63ed9261117dc7845742

**Operating system:**
Ubuntu

**Comment by ariel-** [comment]
> Heal and resurrections Velithria several times

Do you know with what heal it happens?
When you say resurrect, is it related to Valithria?

**Comment by Strazhnik** [comment]
Any time heal Valithria and continue to kill mobs = server crash

**Comment by ariel-** [comment]
No crashes here (b978b673a9053bb0d7bd63ed9261117dc7845742 too)

**Comment by Strazhnik** [comment]
Now crash on Lich and Saurfang. I will make a crash log later.

**Comment by tkrokli** [comment]
@Strazhnik : Please confirm with core rev. hash on the already registered issue
**Crash Npc High Overlord Saurfang** #21644 (if your crash log has the same kind of crash)

Referenced crash is probably in
https://github.com/TrinityCore/TrinityCore/blob/1c8d9af0846036fddef3aa8daf7506d0ebadddb9/src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp#L692
