### ISSUE TITLE
[3.3.5] Core/Spells: Green Buff in WSG does nothing

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#21615]
**Description:**

The buff applies from the gameobject, to the player, but the buff itself does nothing, no heal, no anything. You can see in combat log nothing is displayed at all.

Image: http://prntscr.com/iqqg6t

I get the buff, animation, but buff does nothing.

**Expected behaviour:**

should restore some health and mana

**Steps to reproduce the problem:**

1. Walk into green buff in WSG
2. Notice that the character does not get any spell benefits

**Branch(es):**  3.3.5

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/28288698441524081d583af95f19cb1c9fb90387

**TDB version:**  335.64

**Operating system:** ubuntu

**Comment by Persephone** [comment]
@ariel- Is this related to gameobject casting?

**Comment by Persephone** [comment]
@ariel-  Nope tested casting the buff on myself (23493), nothing is happening i do get visual but it aint healing

**Comment by Killyana** [comment]
It could be related to the faction not set correctly to gobs that are not spawned (summoned, or temp spawn like BG spawns)
If you .gob add 180147 the gob will cast the spell on you char
If you .gob add temp 180147 the gob will not cast the spell

**Comment by Persephone** [comment]
Its not related to the other issue xD ffs! Already explained this. Green buff script is broken has nothing to do with stealth! Reopen the other

**Comment by Killyana** [comment]
Chickens https://woehead.way-of-elendil.fr/?npc=620 can get the auras from this gobs.

**Comment by Hir0shi** [comment]
@confirm

please if can fixed!

old time is buged this issue

**Comment by Killyana** [comment]
Caused by https://github.com/TrinityCore/TrinityCore/commit/34967e9c32b2c7e871bb93f41609a3b08ad92931#diff-fe5c8ebb7ad8e663836b00f39eb524d6

**Comment by Jildor** [comment]
So, when will @ariel- appear? 😢

**Comment by Keader** [comment]
It's a good question xD

**Comment by Hir0shi** [comment]
we can help of project sunwell is fixed this bug?!

copy cod!

**Comment by Hir0shi** [comment]
guys

can give me patch for fix this bug!?

:disappointed:

**Comment by illfated** [comment]
@Hir0shi : This is not a forum.
Please post only useful comments.

**Comment by Hir0shi** [comment]
okay but , this bug is old and never to fixed  :disappointed:

**Comment by Killyana** [comment]
This issue is not caused by new commit as it's possible to reproduce it in 2 years old core.

**Comment by Killyana** [comment]
The issue with the spell 23493 https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L2844 is not related this traps not being triggered, if you cast the spell on you char it will regen your health but not if casted by a gob as it use caster characteristics to calculate the amount of health.

**Comment by Killyana** [comment]
Caused by: https://github.com/TrinityCore/TrinityCore/pull/21395#discussion_r279559933

**Comment by joshwhedon** [comment]
In 3.3.5, trap LOS is checked, because there is no flag indicating it should ignore LOS. As a result they can fail due to LOS issues.

The following can solve it but unsure it is the correct way.

bool IsIgnoringLOSChecks() const
    {
        switch (type)
        {
            case GAMEOBJECT_TYPE_BUTTON: return button.losOK == 0;
            case GAMEOBJECT_TYPE_QUESTGIVER: return questgiver.losOK == 0;
            case GAMEOBJECT_TYPE_CHEST: return chest.losOK == 0;
            case GAMEOBJECT_TYPE_GOOBER: return goober.losOK == 0;
            case GAMEOBJECT_TYPE_FLAGSTAND: return flagstand.losOK == 0;
            case GAMEOBJECT_TYPE_TRAP: return true;
            default: return false;
        }
    }

**Comment by illfated** [comment]
(just copy-pasting the code above, using MarkDown to indent and highlight the syntax)
```cpp
bool IsIgnoringLOSChecks() const
{
    switch (type)
    {
        case GAMEOBJECT_TYPE_BUTTON:
            return button.losOK == 0;
        case GAMEOBJECT_TYPE_QUESTGIVER:
            return questgiver.losOK == 0;
        case GAMEOBJECT_TYPE_CHEST:
            return chest.losOK == 0;
        case GAMEOBJECT_TYPE_GOOBER:
            return goober.losOK == 0;
        case GAMEOBJECT_TYPE_FLAGSTAND:
            return flagstand.losOK == 0;
        case GAMEOBJECT_TYPE_TRAP:
            return true;
        default:
            return false;
    }
}
```

**Comment by joshwhedon** [comment]
Thank you sorry about the syntax. Tried the insert code button but it still looked like crap :D .

**Comment by Aokromes** [comment]
https://i.imgur.com/bAx0AKs.png

**Comment by illfated** [comment]
Notice that this issue happens in Naxxramas too, during the encounter with Heigan the Unclean and his Eruption spell, which does no damage at all.

**Comment by jackpoz** [comment]
@joshwhedon please check your change ingame and if it works, open a PR

**Comment by joshwhedon** [comment]
It does work, tested locally, but sorry I don't really have the resources to prepare pull requests for it at the moment. Feel free to use the fix if you want it, or want to raise a pr for it.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23936

**Comment by gonzo1247** [comment]
still exist https://github.com/TrinityCore/TrinityCore/issues/23919

**Comment by illfated** [comment]
Well. I am not too sure about that, although my testing is limited to 1 character/1 game instance (hence using a GM account). Using a gmlevel 3 character for testing, with GM off, seems to receive the buff as expected. Could be different for normal account characters, but I don't know. Heigan & Noth spell issues are confirmed, though.
