### ISSUE TITLE
[3.3.5] Mage armor reduces the duration of all harmful magical effects by more than 50%.

### ISSUE THREAD

**Issue by Hyrem** [TrinityCore/TrinityCore#21616]
Mage armor reduces the duration of all harmful magical effects by more than 50%.

**Current behaviour:**

when mage armor is active, the harmful magical effects of any kind have a much shorter duration than their default value, for example, default vampire touch lasts 15 sec, but lasts 3 sec while the magician's armor is active, this same happens with psychic scream, polyphormia, etc.

**Expected behaviour:**

the magician's armor should reduce to 50% any damaging magic attack.
spell=43024

**Steps to reproduce the problem:**

1. Apply the aura of mage armor.
2. Duel or combat versus Priest.
3. Apply vampiric touch or psychic scream, mind control.
4. See Duration of debuffs.

**Branch(es):**

3.3.5, 

**TC rev. hash/commit:** 

TrinityCore rev. 901eed782851 2018-03-10 15:51:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB version:**  TDB 335.64

**Operating system:** Win Server 2012 R2

**Comment by Faq** [comment]
please update your core

**Comment by ariel-** [comment]
Fixed in ac976550632f17f5a3ec7eaae354f84faf2656e5. Please update
