### ISSUE TITLE
[3.3.5] Power word: shield puts friendly rogue out of stealth

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21611]
**Description:**

Casting Power Word: Shield on a friendly rogue in stealth, makes him exit stealth.

**Expected behaviour:**

Any friendly buff on a rogue should not de-stealth him, possibly because "weakened soul" counts as negative aura, so it removes stealth?

**Steps to reproduce the problem:**

1. stealth on rogue
2. cast power word shield on the rogue
3. he exits stealth

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/b978b673a9053bb0d7bd63ed9261117dc7845742

**TDB version:**  64

**Operating system:** ubuntu

**Comment by ariel-** [comment]
> possibly because "weakened soul" counts as negative aura, so it removes stealth

Exactly this. Side effect of bd3530dd1f71ce0cd4ce8368af3947cb525349b2, Weakened Soul was previously applied directly, skipping proc system. It was shown in sniffs that previous comment "Blizz doesn't bother to cast" was incorrect, and Weakened Soul is CASTED instead of applied directly, this causes it to register in proc system now

**Comment by Persephone** [comment]
Any way to make it skip proc system again? I tried adding the attributes1 flag DOES_NOT_BREAK_STEALTH, but yeah, still breaks stealth :/

**Comment by Persephone** [comment]
Hackfixed it by changing:

```
void WeakenSoul()
            {
                if (Unit* target = GetHitUnit())
                    GetCaster()->AddAura(target, GetSpellInfo()->ExcludeTargetAuraSpell, true);
            }
```

to

```
void WeakenSoul()
            {
                if (Unit* target = GetHitUnit())
                    GetCaster()->AddAura(GetSpellInfo()->ExcludeTargetAuraSpell, target);
            }
```

Adding it as an aura instead skips proc system, i am still in stealth, and aura is still negative and fully working. 

Dunno if this is suitable :#

**Comment by ariel-** [comment]
No, if sniff says it's casted then adding it directly is a hack.
