### ISSUE TITLE
[3.3.5] Core/Spells: Dazzling Longsword

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21626]
**Description:**

https://woehead.way-of-elendil.fr/?item=869 , its effect about preventing invisibility or stealth doesn't work. Rogues can both vanish and stealth while affected.

**Expected behaviour:**

Shouldnt be able to stealth / vanish.

**Steps to reproduce the problem:**

1. Apply debuff, notice you can still stealth/vanish.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8cf7eda8c12f8fd5c64245cb24c102c62967a030

**TDB version:**  64

**Operating system:** ubuntu

**Comment by tkrokli** [comment]
Related information:
- item: https://woehead.way-of-elendil.fr/?item=869 (Dazzling Longsword)
- spell: https://woehead.way-of-elendil.fr/?spell=13752 (Faerie Fire)
Instant cast
Decrease the armor of the target by 100 for 30 sec. While affected, the target cannot stealth or turn invisible.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e#commitcomment-38375561
