### ISSUE TITLE
Core/Spell: Mod Hit Chance Value : -100

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21629]
**Description:** Some spells have Effect: Apply Aura : Mod Hit ChanceValeur : -100 this means the npc with  this aura cannot miss, or be parry or dodge. it's used by auras that trigger a spell via melee hit, like https://woehead.way-of-elendil.fr/?spell=63767
When the Robot bomb hit a player it explode, the issue is if it's a tank it will miss, parry and dodge the hit.

**Steps to reproduce the problem:**

1. connect a tank level 80 with a good gear
2. .npc add temp 33836
3. Notice the result of the melee from the robor

**Branch(es):** Both

**TC rev. hash/commit:**  rev. 8cf7eda8c12f

**Comment by tkrokli** [comment]
More info (for those who want it):
- https://wow.gamepedia.com/Mimiron_(tactics)#Bomb_Bot
- http://www.wowhead.com/npc=33836/bomb-bot#comments
- http://www.wowhead.com/spell=63801/bomb-bot

**Comment by ariel-** [comment]
But -100 would imply its hit chance is REDUCED by 100% ie, it has 100% increased chance to miss attack

**Comment by Shauren** [comment]
use this `PROC_HIT_MISS = 0x0000004`

**Comment by Killyana** [comment]
Similar: spells: 62052, 63492 ,63767
