### ISSUE TITLE
Time Watchers out of place

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21625]
**Description:**
www.wowhead.com/npc=19918/time-watcher

**Current behaviour:**
There are about a dozen dragons that all fly around at surface level (some come from underground) and land and just sit around in Tanaris.

https://streamable.com/xebe5

**Expected behaviour:**
These should be way under Tanaris in the Caverns of Time, pretty sure they fly down, turn into men, and then walk through a portal somewhere.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  b978b673a905

**TDB version:** 335.64

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
is this the same issue as in **[3.3.5] Time Watchers are not in caverns of time.** #19744 ?
(Z coordinate issues are described in #21624, although focused on spell casts)

**Comment by tkrokli** [comment]
Related issue: **Quest: The Caverns of Time** #21516

**Comment by Killyana** [comment]
@Golrag can you take a look at this issues? #21625   #21624 #21516

**Comment by Golrag** [comment]
Sure, expect a PR in the weekend :p
