### ISSUE TITLE
Blink / Killing Spree teleport issues

### ISSUE THREAD

**Issue by Wilcalaf** [TrinityCore/TrinityCore#21624]
**Description:**

on Utgarde keep. almost in all the dungeon (after the entrance a little bit) , if a player uses blink or  killing spree they will end up in very strange places.

On the escape from lich king event in HoR, After the entrance to the cave Area:4908 )The hidden Passage)
Around cords X:5408.7 Y: 1824.2 Z:760.56
ZoneX: 40.07 ZoneY: 12.2
(Actually not sure which cord to provide)

Mobs spawned there fly up through the roof ending up unkillable by players
its also happen to players if they use abilities like Blink or Killing spree or other teleport abilities.

 in Trial of Crusader raid on Anub room. using either blink or killing spree will make u end up in different places

Shaman Totems Will also end up in strange places

I have reverted the changes done by this PR
#21322 
and its not happening anymore, so i assume something here its what is causing this

(sorry for multiple places i put them because they are related to same issue looks like when its inside a cave in an instance its happening)

**Current behaviour:**

Players and mob that teleports in specific place end up in very weird places

**Expected behaviour:**

To not end up in weird places like above the roof but where its supposed to.

**Steps to reproduce the problem:**

Go to Halls of reflection (or Utgarde keep/Trial of crusader)
If you are on Halls of reflection it will only happen around 
Around cords X:5408.7 Y: 1824.2 Z:760.56
ZoneX: 40.07 ZoneY: 12.2
(inside the cave)
In utgarde keep it will happen almost in all the dungeon after entrance a little bit.
and on Trial of crusader it will happen in Anubarak Room

After you are in any of those places, use Blink or killing spree.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** cc231fd9985de62070edaa7e4cc1731f80049501

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** Win 64

**Comment by Re3os** [comment]
sum @Kvipka

**Comment by Devgasm** [comment]
Mobs flying through the roof also happens in trial of the crusader, specifically underneath the ground during the fight with the beetle boss (can't remember the name off the top of my head). Can be seen if you try to summon totems with a shaman, try to charge one of the mobs that spawn during the boss fight, and also if you summon a non combat pet. Also experienced with the bombs at mimiron in ulduar, they float up and out through the map.

**Comment by Wilcalaf** [comment]
@Devgasm Yes, there might be probably more places where this happens.
If you revert https://github.com/TrinityCore/TrinityCore/pull/21322
it will solve most of them but will make blink and fear problematic again.

**Comment by tkrokli** [comment]
As Golrag mentioned in https://github.com/TrinityCore/TrinityCore/issues/21625#issuecomment-373144623 , we may see a PR to fix this kind of issue during the coming weekend.

**Comment by diegobfl** [comment]
@tkrokli Have you seen any correction for this error?

**Comment by tkrokli** [comment]
@diegobfl : follow PR https://github.com/TrinityCore/TrinityCore/pull/21658 to find out.
(ref. : https://github.com/TrinityCore/TrinityCore/issues/21625#issuecomment-373144623)
