### ISSUE TITLE
[3.3.5] Walking over buffs in stealth

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#21631]
**Description:**

Walking over a buff in any battleground while stealthed, triggers the object so it dissapears but the player receives no buff.

**Expected behaviour:**

Should give the buff anyway even though stealthed.

**Steps to reproduce the problem:**

1. Create rogue
2. enter wsg
3. stealth walk over any buff

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e

**Operating system:** ubuntu

**Comment by Killyana** [comment]
Duplicated https://github.com/TrinityCore/TrinityCore/issues/21615

**Comment by Persephone** [comment]
@Killyana  no this aint duplicated. This is when IN STEALTH the gobject goes away but doesnt cast, has nothing to do with that other issue.

**Comment by Killyana** [comment]
Stealth or not you will never get the buff.

**Comment by Killyana** [comment]
So it must be test it with this gob https://woehead.way-of-elendil.fr/?object=179906
Without being Stealth the player get the aura id: 23493 [Restauration] but it doesn't heal him,  and if the player is stealth it desn't get he aura 23493.

**Comment by Persephone** [comment]
@Killyana if NOT STEALTH you get the buffs but only the heal buff doesnt do anything as described in my other issue why as it uses unit caser not gameobect. 

But this issue is that if stealthed NOTHING happends at all, which is another issue

**Comment by Persephone** [comment]
i fixed this by changing the CastSpell to ADdAura in gameobject.cpp

```
if (goInfo->trap.spellId)
                            target->AddAura(goInfo->trap.spellId, target);
```

now traps works as they should again even in stealth, but ye, hackfix again :#

**Comment by diegobfl** [comment]
TrinityCore/src/server/game/Entities/GameObject/GameObject.cpp

else if (Unit* target = ObjectAccessor::GetUnit(*this, m_lootStateUnitGUID))
                    {
                        // Some traps do not have a spell but should be triggered
                        CastSpellExtraArgs args;
                        args.SetOriginalCaster(GetOwnerGUID());
                        if (goInfo->trap.spellId)
                            CastSpell(target, goInfo->trap.spellId, args);

A correção foi feita nessas linhas de cima ?

@Persephone

**Comment by diegobfl** [comment]
Can you tell me why the flags of Alterac Valley can not be caught?

Neither she nor the Buffs of BG

**Comment by Animalthug** [comment]
Thanks for hack fix, works @Persephone .

```
                        // Some traps do not have a spell but should be triggered
                        CastSpellExtraArgs args;
                        args.SetOriginalCaster(GetOwnerGUID());
                        if (goInfo->trap.spellId)
                            target->AddAura(goInfo->trap.spellId, target);
```

**Comment by Pugnadeus** [comment]
Update: Walking over Berserker buff doesn't do anything, I just tested, was using a Warrior.

**Comment by devfrom** [comment]
@Persephone @kvipka 

                        // Some traps do not have a spell but should be triggered
                        CastSpellExtraArgs args;
                        args.SetOriginalCaster(GetOwnerGUID());
                        if (goInfo->trap.spellId)
                            target->AddAura(goInfo->trap.spellId, target);


adding this hackfix the BG Berserk buff will be corrected and added to the player when it goes over, however this change causes the Hunter Trap to not function properly when the hunter casts the trap when passing through it nothing happens.

can you help me?

**Comment by Killyana** [comment]
After fixing https://github.com/TrinityCore/TrinityCore/issues/21615 this issue also was fixed
