### ISSUE TITLE
Problem with update 2017_05_04_00_world.sql

### ISSUE THREAD

**Issue by rickjs** [TrinityCore/TrinityCore#21639]
**Description:**
update 2017_05_04_00_world.sql failed after running worldserver. Full sql TDB_full_world_335.64_2018_02_19 was installed previously

CHANGEME Description of the problem or issue here.
lines 
ALTER TABLE `creature_text` CHANGE `entry` `CreatureID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `creature_text` CHANGE `groupid` `GroupID` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `creature_text` CHANGE `id` `ID` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0';

Commenting out the three lines fixes problem.
Keys entry, groupid, id were already set to new names.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**
Worldserver should run all updates without errors.

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
1. Install TDB_full_world_335.64_2018_02_19.sql
2. Run worldserver.

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**
3.3.5
CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command

**Operating system:** CHANGEME OS
Windows 10

**Comment by Aokromes** [comment]
you don't must apply any sql inside old.

**Comment by tkrokli** [comment]
Never apply older SQL files than the base `TDB_full_world_*` file.
**They are already part of the `TDB_full_world_*` file.**

**Comment by rickjs** [comment]
Hi,


I didn't apply the update, worldserver did.


Thanks,

Rick


________________________________

**Comment by rickjs** [comment]
Hi,


Worldserver applied the update.


Thanks,

Rick


________________________________

**Comment by tkrokli** [comment]
Source code (core) needs to be on par with the DB to avoid wrong DB status or storing archived SQL files as new updates.

**Comment by rickjs** [comment]
Hi,


Source was pulled on 3/13, ran cmake and remade solution for VS2017, compiled all build, no problem. Noticed there was a new TDB_full_world_335.64_2018_02_19, so dropped tables and ran TDB from console, no errors (I've seen where worldserver didn't run  TDB so prefer to manually install TDB). Ran worldserver and got that sql error when server continued with rest of updates. Thought it was strange that old updates were running. Put comments on the three lines indicated, ran worldserver again, finished updates, no problem. WOW 3.35 runs, no errors.


BTW, kept character and auth db, checked if there was any updates previous to 2018_02_19 date, no updates needed.


Thanks,

Rick

________________________________

**Comment by tkrokli** [comment]
OK, so problem solved, then. This issue is already closed, so no need for more follow-ups. No-one else has confirmed or reported this issue, so I don't see a need for reopening this issue.
