### ISSUE TITLE
Core/Spell:  Debuffs are not renewed on target

### ISSUE THREAD

**Issue by Hyrem** [TrinityCore/TrinityCore#21635]
**Description:**

Some mage debuffs do not reset dots.

**Current behaviour:**

You apply a debuff on the target, before the end of the timer you renew the dot, but the cooldown timer of the debuff continues counting and does not restart.

**Expected behaviour:**

When applying a debuff and renewing it, the timer should restart the count from the beginning.

**Steps to reproduce the problem:**

1. Apply frostbolt of frost or frostfire bolt.
2. Before finishing the cooldown debuff, apply the new spell.
3. The debuff timer on the target is not renewed

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ddd60a948c43 2018-03-14 20:50:54 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** WIN SERVER 2012 R2

**Comment by Langerz82** [comment]
might as well fix this issue since i am working on this section of code.

**Comment by Langerz82** [comment]
```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index 4f27edc633..9aa7e60849 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -581,6 +581,8 @@ void AuraEffect::CalculatePeriodic(Unit* caster, bool resetPeriodicTimer /*= tru
         case SPELL_AURA_PERIODIC_DUMMY:
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
         case SPELL_AURA_MOD_ATTACK_POWER_OF_ARMOR:
+        case SPELL_AURA_MOD_HEALING_PCT:
+        case SPELL_AURA_MOD_DECREASE_SPEED:
             m_isPeriodic = true;
             break;
         default:
```

**Comment by Langerz82** [comment]
Ok here we go, ready to test:

See:
https://gist.github.com/Langerz82/ed8fc0e5786a20b6de109372e4b37701

**Comment by r0m1ntik** [comment]
@Langerz82 work fin for my.

**Comment by matyashlavacek** [comment]
@Langerz82 Any updates on this? Can I help you out with something? I'd love to have this fixed

**Comment by Langerz82** [comment]
Just run in debug mode and set a breakpoint on CalculatePeriodic and check the spell Aura Fear has.
In general I'm not PR'ing any Spell code, as @ariel 's knows more what changes should occur (I have basic knowledge of spell code).

**Comment by Keader** [comment]
Maybe same of https://github.com/TrinityCore/TrinityCore/issues/22272?

**Comment by Killyana** [comment]
Not exactly the same issue, #22272 is about debuff not being stack, but it could be caused by the same "bug"

**Comment by Aokromes** [comment]
test after a099974

**Comment by Killyana** [comment]
Fixed
