### ISSUE TITLE
[3.3.5] Stoneclaw Shield Causes Auto Attacks to miss

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21638]
**Description:**

When a shaman is wearing a shield and he gets affected by stoneclaw shield, i miss like 99% of all auto attacks against him.

Litereally all i see is "miss miss miss miss"

**Expected behaviour:**

Should not miss?

**Steps to reproduce the problem:**

1. attack shaman who has shield and stoneclaw totem
2. notice auto attacks miss constantly

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e

**Operating system:** ubuntu

**Comment by ariel-** [comment]
Rev 25d4bcba3d24. Can't reproduce

**Comment by Aokromes** [comment]
plz, on the future use the command server debug as stated on create ticket.

**Comment by tkrokli** [comment]
Maybe we should alter the issue template to say " **Output from .server debug :**" on one of the fields.

**Comment by Aokromes** [comment]
I did that already, but people is ignoring it.

**Comment by tkrokli** [comment]
Too bad for them, because that means they will get less help in finding out what is wrong.

**Comment by Killyana** [comment]
Cannot reproduce on rev. 9e0a343f729e
But I noticed something about hit chance, if the player has an aura that reduce the hit chance per 100% like https://woehead.way-of-elendil.fr/?spell=72619 he still able to hit the target sometimes.
