### ISSUE TITLE
Server Crash by using a bag with ID in description!

### ISSUE THREAD

**Issue by Shoxxo** [TrinityCore/TrinityCore#21636]
**Description:**
```
Note from expected player.

oh fuck, das war eben komisch. ist eine klassenquest. musste ein item zum falkenplatz bringen. hab auf den weg dorthin beim verkäufer halt gemacht. wollte dann das questitem in der tasche verschieben und ist dann verschwunden. tut mir leid.... zur not lösche summerfly 


english : 


oh fuck, that was funny. is a class quest. had to bring an item to the falcon place. I stopped there at the seller stop. then wanted to move the questitem in the bag and then disappeared. I'm sorry .... to erase summerfly
```

Server crashes if a player has a specific item. with id 177293, 177265

**Current behaviour:**

CHANGEME Tell us what happens.
https://gist.github.com/Shoxxo/0aec4305a680fecdb70eee60775d5e53

**Expected behaviour:**

never see this error before...

**Steps to reproduce the problem:**
i do not know how to reproduce this error. i see a player has that item and if he log in with tha, he crashes the server.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e

**Operating system:** 
Debian 9 x64

**Comment by Devgasm** [comment]
Same as https://github.com/TrinityCore/TrinityCore/issues/21628
