### ISSUE TITLE
[3.3.5] Blessing of Wisdom and Mana Spring Totem doesnt stack

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21637]
**Description:**

Blessing of Wisdom gives 20 mp5
Mana Spring gives 21 mp5
When you have BoW and then get affected by Mana Spring, it removes Blessing of Wisdom instead of stacking them

**Expected behaviour:**

Blessing of Wisdom & Mana Spring should stack

**Steps to reproduce the problem:**

1. Cast both above spells on yourself or another character

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9e0a343f729eb7e172c447dccb066f4f236aa11e

**Operating system:** ubuntu

**Comment by ariel-** [comment]
Not stack, rather have both effects but only the greater counting (due to stuff like Imp. BoW)
