### ISSUE TITLE
[master] I can not log in

### ISSUE THREAD

**Issue by Bodeguero** [TrinityCore/TrinityCore#21633]
**Description:**

 *I'am not able to log in, I created the account correctly, turned on the server but at the time of connecting hangs.* **PS: Sorry for language errors.**

**Current behaviour:**

*WorldSocket :: HandleAuthSession: Authentication failed for account: 1 ('1 # 1') address: 127.0.0.1*

![image](https://user-images.githubusercontent.com/8006687/37481697-254f455a-2861-11e8-9c29-6e4b2b60912d.png)

**Branch(es):**

master

**TC rev. hash/commit:** 
*TrinityCore Revision: https://github.com/TrinityCore/TrinityCore/commit/d1146a4495d542702954702b3d6a11ddb0beb81a*

**Operating system:** *WinServer 2012 R2*

**Comment by DoctorKraft** [comment]
Wrong rev (build) of your Wow.exe, run again the tools connection_patcher.exe with the correct rev of wow.exe

**Comment by Bodeguero** [comment]
@DoctorKraft Could you make the wow.exe already patched available? Or at least it's not patched for us to do this, all I have is patched and my internet is too bad to download the game.

**Comment by tkrokli** [comment]
@Bodeguero : github & TC do not support sharing binaries in these pages. Please use other forums for game file sharing.

**Comment by Bodeguero** [comment]
@tkrokli Can not even send a download link?

**Comment by tkrokli** [comment]
Please use forum pages or IRC. Traceable links for Blizzard files is a liability and can be penalized by site owner (GitHub).

**Comment by Bodeguero** [comment]
Resolved

**Comment by jtoporowski** [comment]
Can you say how you fixed this? I'm having the same issue and have checked both the client version and the gamebuild in the realmlist table.

**Comment by tomlutom** [comment]
yea i have same problem with legion repack.
love ppl who write solved and bye
