### ISSUE TITLE
[3.3.5]  Debuffs dispellable by target player

### ISSUE THREAD

**Issue by Hyrem** [TrinityCore/TrinityCore#21634]
**Description:**

Some Debuffs that are applied to the target can be removed by the target player because they remain as buffs (not debuff).

**Current behaviour:**

Warlock Haunt, Dk Ebone Plague, Paladin Judgment Debuffs in the objective they are applied as buffs and can be eliminated by the objective

**Expected behaviour:**

Debuffs should not be applied as buffs

**Steps to reproduce the problem:**

1. With Warlock, apply Haunt, The target can right click on the buff that is applied, not debuff.
2. With DK, apply Ebone Plague. The target can right click on the buff that is applied, not debuff.
3. With Pally apply Judgment of Justice. The target can right click on the buff that is applied, not debuff.

**Branch(es):**  3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ddd60a948c43 2018-03-14 20:50:54 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** WIN SERVER 2012 R2

**Comment by Foereaper** [comment]
Experiencing this with a lot more spells, as an example most debuffs put on players in Icecrown Citadel are clickable
