### ISSUE TITLE
Quest: Redemption

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21655]
**Description:**
http://www.wowhead.com/quest=5742/redemption

**Current behaviour:**
Tirion Fordring doesn't have speech dialogue to click on to progress the quest.

**Expected behaviour:**
He should have speech dialogue to click on to "listen to what he has to say".

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 1c8d9af08460

**Operating system:** Windows 10

**Comment by tkrokli** [comment]
Hmm..... did you read the quest text? I think I improved that script myself, unless it has been converted to SAI.

**Comment by jerbookins** [comment]
http://www.wowhead.com/quest=5742/redemption#comments:id=618739

I did not see any sort of dialogue options available to me as described in this comment.

**Comment by Killyana** [comment]
Condition: Show gossip menu option 3502 only if player is sitting (any type)

**Comment by tkrokli** [comment]
TrinityCore rev. 1c8d9af08460 2018-03-16 12:34:42 -0300 (3.3.5 branch) (Win64, Release, Static)

![redemption_1](https://user-images.githubusercontent.com/4903600/37554972-89028a5a-29e0-11e8-871d-27bd57b211c9.png)

![wowscrnshot_031718_121303](https://user-images.githubusercontent.com/4903600/37554982-ab5c879a-29e0-11e8-8a22-0fcfd6ce9817.jpg)

Working as expected & intended.

**Comment by jerbookins** [comment]
omfg

thanks.

**Comment by tkrokli** [comment]
I know. I worked in close contact with @Treeston to create a working condition to detect whether or not the player is sitting to make this gossip work as intended. ^^ (ref.: **Core/Scripts: move npc_tirion_fordring to DB/SAI** #16680 -- notice in particular the last line in the SQL part. ^^ )

**Comment by offl** [comment]
Bad news everyone https://youtu.be/Fiu_sVevUyw?t=91

**Comment by illfated** [comment]
I wonder if "sitting on a mount" counts as fulfilling the condition to "Sit and listen to my story, $r.", but I guess that is probably stretching the imagination, of what Blizzard could have developed for that quest scenario, too far.

**Comment by offl** [comment]
No, there simply no such condition at all
If such thing existed tons of people added comments about that here https://www.wowhead.com/quest=5742/redemption#comments simply because this is so unique condition, and as you can see there's no a single word about that

**Comment by illfated** [comment]
Very well, fair enough. I presume we have to remove the condition for that quest.

**Comment by illfated** [comment]
Suggestion:
```sql
-- Remove incorrect condition requiring player to be sitting to be able to see the quest gossip option for quest 5742
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 15 AND `SourceGroup`= 3502 AND `ConditionTypeOrReference`= 47 AND `ConditionValue1`= 10;
```

**Comment by illfated** [comment]
By the way, there are actually comments saying that you need to sit to see the dialogue appear:
- https://classic.wowhead.com/quest=5742/redemption#comments:id=2743175
- https://classic.wowhead.com/quest=5742/redemption#comments:id=3248340

(My request to have that condition created was based on those comments, maybe even others.)

**Comment by offl** [comment]
> https://classic.wowhead.com/quest=5742/redemption#comments:id=2743175

He just copied all texts

> https://classic.wowhead.com/quest=5742/redemption#comments:id=3248340

Even if existed, it was removed

**Comment by illfated** [comment]
Fair enough. I concur.
```sql
SELECT * FROM `conditions` WHERE `SourceTypeOrReferenceId`= 15 AND `SourceGroup`= 3502;
```
```
SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment
-----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  -----------------------------------------------------------------
            15               3502          0           0         1                 42                     0                 1              1                0                  0          0            0                     Show gossip menu option 3502 only if player is sitting (any type)
            15               3502          0           0         1                 47                     0              5742             10                0                  0          0            0                     Show gossip menu option 3502 only if Quest 5742 is taken (active)
```

I have to correct that SQL suggestion above, it was for the wrong line. Here is the correct row:

**Suggested solution:**

```sql
-- Remove incorrect condition requiring player to be sitting to be able to see the quest gossip option for quest 'Redemption' (5742)
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`= 15 AND `SourceGroup`= 3502 AND `ConditionTypeOrReference`= 42 AND `ConditionValue1`= 1;
```

**Comment by illfated** [comment]
Minor detail (not important) but just for the record, since the wowhead page seems to scroll to the wrong comment:
- https://classic.wowhead.com/quest=5742/redemption#comments:id=2743175

![image](https://user-images.githubusercontent.com/38162891/99131789-51e38a00-2614-11eb-8ee8-d3b576c73271.png)
