### ISSUE TITLE
[3.3.5] Bloodmyst Isle doesn't have Mining nodes & Herbs

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#21657]
Bloodmyst Isle doesn't have any mining nodes and no herbs, apart from quest related herbs.

rev 9e0a343 with all updates

**Comment by ariel-** [comment]
Delete template is evil

**Comment by offl** [comment]
I have only 50% of mining nodes at this moment, didn't yet checked herbs
If anyone got sniffs with creatures 17606,17524,17343,17345,17713,17331,17324,17588,17344,17527,17522,17610 (those are located in Bloodmyst), please share sql file only(only `gameobject` table)

**Comment by offl** [comment]
I'll add objects & pools this week
