### ISSUE TITLE
Crash on Map::getNGrid

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21668]
**Current behaviour:**

https://gist.github.com/Gooyeth/bb41f3d9f64b227591678969730c1fed

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 07e42f7d4121e18f6f61cafe8e6fe389ff8b1beb

**Operating system:** Debian 9

**Comment by shenhuyong** [comment]
2baa81065ba27f0a6d278a8dd8a79b7c831e0a2b causes this crash.
Line 138 in TargetedMovementGenerator.cpp, the size of GetTarget()->GetNearPoint() possible be a too large value to make x or y > MAX_NUMBER_OF_GRIDS.

**Comment by tkrokli** [comment]
Question to other TC members: is there enough info in the posted gist to label this issue with [HasBacktrace] ?

**Comment by Shauren** [comment]
i have an idea here
