### ISSUE TITLE
[3.3.5] Double Flag Carrier WSG

### ISSUE THREAD

**Issue by Persephone** [TrinityCore/TrinityCore#21667]
**Description:**

If you pick up the flag in WSG and someone on your team summons the https://woehead.way-of-elendil.fr/?spell=55531 (Mechano-hog), then you sit in the Mechano-hog with him.

You somehow transfer the flag to him if he disbands the vehicle, leaving you both to have the flag buff visual on, so it confuses the enemy team.
Only the guy you transferred it to can capture it, the other guy still has the spell buff visual so it looks like he has the flag.

**Expected behaviour:**

Shouldn't duplicate flags, should probably just drop it once he enters the vehicle.

**Steps to reproduce the problem:**

1. Pick up flag on Player A.
2. Player B summons https://woehead.way-of-elendil.fr/?spell=55531
3. Player A enters https://woehead.way-of-elendil.fr/?spell=55531
4. Player B dismounts
5. you now both have the flag buff

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/07e42f7d4121e18f6f61cafe8e6fe389ff8b1beb

**Operating system:** ubuntu

**Comment by Jildor** [comment]
Reason?

**Comment by tkrokli** [comment]
Wish I knew, it is always a good idea to write why an issue gets closed.
