### ISSUE TITLE
[3.3.5] Spells: Slime Pool Effect visibility issue

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#21660]
**Description:** Slime Pool Effect (66882), cast by Slime Pool in Northrend Beasts encounter is only visible after you use .gm on and .gm off

**Current behaviour:** Spell is invisible until you see the NPC.

**Expected behaviour:** Spell should me always visible.

**Steps to reproduce the problem:**

1. Enter the Trial of the Crusader instance.
2. Use `.npc add temp 35176` with gm off.
3. You will only be able to see the visual effect if you use `.gm on`

PS: The NPC does not have the trigger flag, it uses an invisible model.
NPC script is present here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp#L907

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 7fdffe89846ec8a313cfb577bd90a09d7707556d

**Comment by Keader** [comment]
PS: I tested change npc to a visible model, and issue remain xD

**Comment by Killyana** [comment]
The npc npc_jormungars_slime_pool melee players.

**Comment by Wilcalaf** [comment]
i fixed it on my local with a Hack, like in the file @Keader linked by making the boss spawning also the visual but as he said its probably not a script problem

**Comment by ariel-** [comment]
I reverted back to 022538e1851fc9d72d7c363b8f1b426584c7223b, just before merging spell rewrite and the issue is there. so it's not due to the spell changes either

**Comment by Tatara902** [comment]
What commit you mean by Threat Rewrite @Keader  (71b5ed6) ?

**Comment by Faq** [comment]
@Tatara902 with this 425b181544a21d2246fdf0261ba76a37e2510883

**Comment by tje3d** [comment]
replace reset() with JustEngagedWith() in npc_jormungars_slime_pool fixes the issue

**Comment by Keader** [comment]
Still looks incorrect :)

**Comment by tje3d** [comment]
@Keader yes for sure, but better than nothing 😜
