### ISSUE TITLE
Crash on Creature - LoadFromDB

### ISSUE THREAD

**Issue by Gooyeth** [TrinityCore/TrinityCore#21665]
**Current behaviour:**

https://gist.github.com/Gooyeth/8e3e18a622f20987863635fbd2e2db83

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 07e42f7d4121e18f6f61cafe8e6fe389ff8b1beb

**Operating system:** Debian 9

**Comment by Foereaper** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21641 related?

**Comment by tkrokli** [comment]
Possibly. Need confirmation from someone who reads crash logs better than me.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21641

**Comment by diegobfl** [comment]
@Killyana @tkrokli  Any solution to solve this crash?

**Comment by tkrokli** [comment]
@diegobfl : follow the dialogue in issue https://github.com/TrinityCore/TrinityCore/issues/21641 and see if anyone posts something related or useful there. Consider this issue page closed, no more follow-up here.
