### ISSUE TITLE
Rotface Issue with Oozes

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21672]
**Description:**
After removing the disease of "Mutated Infection" a little ooze appear, after removing two diseases if you try to put together 2 little oozes a big ooze should appear removing the 2 little oozes, however that doesn't happen, after joining 2 little oozes the big one never spawn, so after an encounter you have a lot of little oozes in the instance.
- Tested in 25N

**Current behaviour:**
After putting together 2 little oozes a big ooze doesn't appear.

**Expected behaviour:**

After putting together 2 little oozes a big ooze should appear.

**Steps to reproduce the problem:**

1. Step Go to ICC and start an encounter with Rotface
2. Step Use any skill that can remove the disease "Mutated Infection"
3. Step Try to join the little oozes

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

3670779

**Operating system:** Win 10 x64

**Comment by Aokromes** [comment]
why you people ignore the new requirement to use .server debug command ?

**Comment by Gooyeth** [comment]
@Aokromes: In my case because almost always when I make a report I do not have the console at hand.

**Comment by Foereaper** [comment]
Experienced the same with the oozes a couple days ago, haven't seen it before so figured it was a one time thing only, but haven't really looked into recreating the issue either.

**Comment by tje3d** [comment]
Spell system issue?

**Comment by tje3d** [comment]
Does anybody have idea?

**Comment by Langerz82** [comment]
I only have very basic knowledge of the game. So I have to reproduce the issue before I can even know what to look for haha. Anyway I will give it a go.

**Comment by Langerz82** [comment]
I temp spawned the little oozes in icecrown citadel and it worked for me as intended.
Do a clean build of the latest:

**Comment by tje3d** [comment]
@Langerz82 "When two Small Oozes get near one another, they will merge and become a Big Ooze".
And because of this issue, you will have a lot little ooze at the end of the fight.

**Comment by AByakugans** [comment]
Anyone knows any solution for this?

**Comment by illfated** [comment]
Need to verify if it stops working in the central part of this spell script or if something else in `boss_rotface.cpp` affects it.
https://github.com/TrinityCore/TrinityCore/blob/f1a1acdc89a6521fddca98cc8ef8d6e7ed0b9495/src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp#L580-L610

**Comment by sawd14** [comment]
Anyone can help?

**Comment by illfated** [comment]
@AByakugans , @sawd14 : you can try experimenting with the settings in `spell_rotface_little_ooze_combine_SpellScript` (the code I linked above) to see if any changes there can make it work. Other than that, I would think maybe @Keader or @sirikfoll might have ideas where to look or try out changes. (We are still hoping to hear more from @ariel- whenever he gets time to take a closer look at the spells.)

**Comment by AByakugans** [comment]
Can @Keader look into this maybe?

**Comment by AByakugans** [comment]
Nothing helped what I tried ... I even tried some modifications like:
```
                        case EVENT_SLIME_SPRAY:
                            if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true))
                            {
                                DoSummon(NPC_OOZE_SPRAY_STALKER, *target, 8000, TEMPSUMMON_TIMED_DESPAWN);
                                Talk(EMOTE_SLIME_SPRAY);
                                DoCast(me, SPELL_SLIME_SPRAY);
                            }
                            events.ScheduleEvent(EVENT_SLIME_SPRAY, 20s);
                            break;
```
To this one:
```
                        case EVENT_SLIME_SPRAY:
                            if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 0.0f, true))
                            {
                                Talk(EMOTE_SLIME_SPRAY);
                                if (Creature* stalker = DoSummon(NPC_OOZE_SPRAY_STALKER, *target, 8000, TEMPSUMMON_TIMED_DESPAWN))
                                    DoCast(stalker, SPELL_SLIME_SPRAY);
                            }
                            events.ScheduleEvent(EVENT_SLIME_SPRAY, 20s);
                            break;
```
No change at all.

**Comment by AByakugans** [comment]
Anyone has any solution I can test for you?

**Comment by Killyana** [comment]
Cannot reproduce on rev. 3d3b7f438c66
