### ISSUE TITLE
[3.3.5] Problems with the GEODATA of the ice crown Citadel

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21689]
**Description:**

Literally 5 minutes ago, 've reassembled GEODATA, and NPS continue not to fly properly. PS it is wrong to fly the rest is all good. This applies to both Valkyries and Lana and syndrome. 
In config everything is included including mmap
Immediately apologize for the translation from Russian.
Sreens:
https://s8.hostingkartinok.com/uploads/images/2018/03/09431162d00f5f1442db3903b4747646.png
https://s8.hostingkartinok.com/uploads/images/2018/03/e477d959240e670cf623bc144a3e5f56.png

REV https://github.com/TrinityCore/TrinityCore/commit/3420b8d5c4dd21b66502ace7cd6ee210d6e6e8e1

**Comment by tkrokli** [comment]
Maybe you mean Vmaps or Mmaps? This problem is highly related to
**Core/Entities: Reduce probability of going under the map** #21658
Also affected by the changes from
**Core/Entities: Reduce the probability of units dropping under the map** #2132

Other possible related issues:
- [3.3.5] Strange NPC movement behavior #19998
- Time Watchers out of place #21625
- Val'kyr Shadowguard #7266

**Comment by Keader** [comment]
Valkyr use hover if i remember right
maybe missing some data in Shauren pr?

**Comment by tkrokli** [comment]
Good point. Maybe. Needs more research.

**Comment by vahzxz** [comment]
The problem is even probably not only with the CLC. Because at RS 2 a BJ flies not as high as you need. Then in the same CLK Syndrome at all on air phase flies in texture. There are other NPCs who have the air phase is also not behaving properly.

**Comment by vahzxz** [comment]
Rudely speaking the NPC fly leaps
https://s8.hostingkartinok.com/uploads/images/2018/03/a1aad887276bea4164558e0c802accf2.png
https://s8.hostingkartinok.com/uploads/images/2018/03/f6b4fca56eeca3339c38408512cbb4a4.png

**Comment by vahzxz** [comment]
Start location DK
https://s8.hostingkartinok.com/uploads/images/2018/03/7c46b3e0a1a392c5b6ffffc38aa4808b.png

**Comment by Killyana** [comment]
This is weird I checked all this npcs and I don't have this issues. You're probably using a repack or your core is not properly updated.
https://imgur.com/a/W9wUD

**Comment by Aokromes** [comment]
why you guys ignore the server debug command.
Anyway confirm what killyana said.
https://i.imgur.com/2bK89I2.jpg

**Comment by vahzxz** [comment]
![image](https://user-images.githubusercontent.com/37352351/37881749-d7e4b0a6-30a4-11e8-9e66-98363e74f90f.png)
![image](https://user-images.githubusercontent.com/37352351/37881760-eab7d4e2-30a4-11e8-83f4-992a93c498fa.png)
I just a couple of minutes ago downloaded the source code and made the latest updates to the database from 23.03. As you can see in the screenshots of the map, GEODATA and DBS rebuilt just yesterday, and the problem remained

**Comment by vahzxz** [comment]
@Aokromes 
What do you mean?
