### ISSUE TITLE
NPC can see through walls

### ISSUE THREAD

**Issue by Bluechen80** [TrinityCore/TrinityCore#21686]
Description:
NPC can see through walls

Current behaviour:
Im a lvl 13 Priest and i quest in Westfall. In Westfall are many houses with Defias Trapper and other Defias guys. if i walk around that house on the wallside. They run all out to attack me. 

Expected behaviour:
Normaly nothing happens cause they cant see me 

Branch(es):
3.3.3a

TC rev. hash/commit:
TrinityCore 2018_02_19

TDB version:
TDB 335.64

Operating system:
My OS : Windows 10

Step 1 Go to Westfall with a lvl 13 Char
Step 2 Go to the House in the North Coordinate: 49,19 Furlbrow's Pumpkin Farm
Step 3 move along the walls or just go near to a house wall
Step 4 Ull see they run out to attack u

**Comment by Ovahlord** [comment]
Dumb question: do you have your vmaps enabled?

**Comment by tkrokli** [comment]
That is why we ask for output from the command `.server debug`
-- but users are not able to read instructions, as usual.

**Comment by Bluechen80** [comment]
Hello Vmaps are on and here is the Server Log:

TrinityCore rev. 1cc3d33cfe7e 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file E:/3.3.5a February-20-2018 (x64) MySQL 5.5.9/Core/worldserver.conf.
Using SSL version: OpenSSL 1.0.2j  26 Sep 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.60.0
Automatic database updates are disabled for all databases!
Realm running as realm ID 1
Using World DB: TDB 335.64
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 64
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps
Loading Trinity strings...
>> Loaded 961 trinity strings in 1 ms
Initialize data stores...
>> Initialized 112 data stores in 486 ms
Using deDE DBC Locale as default. All available DBC locales: deDE 
>> Loading Cinematic Camera files
>> Loaded 14 cinematic waypoint sets in 1 ms
Initializing PlayerDump tables...
>> Initialized tables for PlayerDump in 224 ms.
Loading SpellInfo store...
>> Loaded SpellInfo store in 29 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 6 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 10219 SkillLineAbility MultiMap Data in 1 ms
Loading SpellInfo custom attributes...
>> Loaded 233 spell custom attributes from DB in 1 ms
>> Loaded SpellInfo custom attributes in 14 ms
Loading SpellInfo diminishing infos...
>> Loaded SpellInfo diminishing infos in 3 ms
Loading SpellInfo immunity infos...
>> Loaded SpellInfo immunity infos in 4 ms
Loading GameObject models...
Loading Script Names...
>> Loaded 2952 ScriptNames in 1 ms
Loading Instance Template...
>> Loaded 84 instance templates in 0 ms
Loading instances...
>> Loaded instances in 1 ms
Loading character cache store...
Loaded character infos for 4 characters in 0 ms
Loading Broadcast texts...
>> Loaded 73039 broadcast texts in 159 ms
>> Loaded 73039 broadcast text locales in 652 ms
Loading Localization strings...
>> Loaded 27246 creature locale strings in 185 ms
>> Loaded 19670 gameobject_template_locale strings in 118 ms
>> Loaded 38112 Item locale strings in 267 ms
>> Loaded 2472 Item set name locale strings in 7 ms
>> Loaded 9456 Quest locale strings in 166 ms
>> Loaded 1 NpcText locale strings in 1 ms
>> Loaded 1946 PageText locale strings in 15 ms
>> Loaded 453 points_of_interest locale strings in 1 ms
>> Loaded 18 quest greeting locale strings in 0 ms
>> Localization strings loaded in 761 ms
Loading Account Roles and Permissions...
>> Loaded 663 permission definitions, 646 linked permissions and 4 default permissions in 1 ms
Loading Page Texts...
>> Loaded 1950 page texts in 2 ms
Loading Game Object Templates...
>> Loaded 21587 game object templates in 91 ms
Loading Game Object template addons...
>> Loaded 21520 game object template addons in 14 ms
Loading Transport templates...
>> Loaded 30 transport templates in 0 ms
Loading Transport animations and rotations...
Loading Spell Rank Data...
>> Loaded 3460 spell rank records in 2 ms
Loading Spell Required Data...
>> Loaded 41 spell required records in 1 ms
Loading Spell Group types...
>> Loaded 540 spell group definitions in 0 ms
Loading Spell Learn Skills...
>> Loaded 103 Spell Learn Skills from DBC in 2 ms
Loading SpellInfo SpellSpecific and AuraState...
>> Loaded SpellInfo SpellSpecific and AuraState in 4 ms
Loading Spell Learn Spells...
>> Loaded 8 spell learn spells + 574 found in DBC in 2 ms
Loading Spell Proc conditions and data...
>> Loaded 835 spell proc conditions and data in 1 ms
Generating spell proc data from SpellMap...
>> Generated spell proc data for 1415 spells in 2 ms
Loading Spell Bonus Data...
>> Loaded 216 extra spell bonus data in 0 ms
Loading Aggro Spells Definitions...
>> Loaded 106 SpellThreatEntries in 1 ms
Loading Spell Group Stack Rules...
>> Loaded 62 spell group stack rules in 0 ms
>> Parsing SPELL_GROUP_STACK_RULE_EXCLUSIVE_SAME_EFFECT stack rules...
>> Parsed 12 SPELL_GROUP_STACK_RULE_EXCLUSIVE_SAME_EFFECT stack rules in 0 ms
Loading NPC Texts...
>> Loaded 8257 npc texts in 87 ms
Loading Enchant Spells Proc datas...
>> Loaded 42 enchant proc data definitions in 1 ms
Loading Item Random Enchantments Table...
>> Loaded 28607 Item Enchantment definitions in 12 ms
Loading Disables
>> Loaded 829 disables in 1 ms
Loading Items...
>> Loaded 38607 item templates in 628 ms
Loading Item set names...
>> Loaded 2481 item set names in 2 ms
Loading Creature Model Based Info Data...
>> Loaded 24143 creature model based info in 17 ms
Loading Creature templates...
>> Loaded 29923 creature definitions in 307 ms
Loading Equipment templates...
>> Loaded 10709 equipment templates in 9 ms
Loading Creature template addons...
>> Loaded 8331 creature template addons in 7 ms
Loading Reputation Reward Rates...
>> Loaded 16 reputation_reward_rate in 0 ms
Loading Creature Reputation OnKill Data...
>> Loaded 2034 creature award reputation definitions in 3 ms
Loading Reputation Spillover Data...
>> Loaded 26 reputation_spillover_template in 0 ms
Loading Points Of Interest Data...
>> Loaded 453 Points of Interest definitions in 1 ms
Loading Creature Base Stats...
>> Loaded 400 creature base stats in 3 ms
Loading Spawn Group Templates...
>> Loaded 47 spawn group templates in 0 ms
Loading instance spawn groups...
>> Loaded 47 instance spawn groups in 0 ms
Loading Creature Data...
>> Loaded 147877 creatures in 759 ms
Loading Temporary Summon Data...
>> Loaded 663 temp summons in 1 ms
Loading pet levelup spells...
>> Loaded 993 pet levelup and default spells for 39 families in 3 ms
Loading pet default spells additional to levelup spells...
>> Loaded addition spells for 111 pet spell data entries in 2 ms
Loading summonable creature templates...
>> Loaded 459 summonable creature templates in 3 ms
Loading Creature Addon Data...
>> Loaded 35702 creature addons in 30 ms
Loading Gameobject Data...
>> Loaded 91069 gameobjects in 547 ms
Loading Spawn Group Data...
>> Loaded 97284 spawn group members in 55 ms
Loading GameObject Addon Data...
>> Loaded 60035 gameobject addons in 91 ms
Loading GameObject Quest Items...
>> Loaded 857 gameobject quest items in 0 ms
Loading Creature Quest Items...
>> Loaded 4391 creature quest items in 3 ms
Loading Creature Linked Respawn...
>> Loaded 5059 linked respawns in 3 ms
Loading Weather Data...
>> Loaded 35 weather definitions in 0 ms
Loading Quests...
>> Loaded 9464 quests definitions in 163 ms
Checking Quest Disables
>> Checked 661 quest disables in 0 ms
Loading Quest POI
>> Loaded 8953 quest POI definitions in 58 ms
Loading Quests Starters and Enders...
Loading GO Start Quest Data...
>> Loaded 446 quest relations from gameobject_queststarter in 0 ms
Loading GO End Quest Data...
>> Loaded 456 quest relations from gameobject_questender in 0 ms
Loading Creature Start Quest Data...
>> Loaded 7443 quest relations from creature_queststarter in 3 ms
Loading Creature End Quest Data...
>> Loaded 7878 quest relations from creature_questender in 4 ms
Loading Quests Greetings...
>> Loaded 81 quest_greeting in 0 ms
Loading Objects Pooling Data...
>> Loaded 3103 objects pools in 1 ms
Loading Creatures Pooling Data...
>> Loaded 1022 creatures in pools in 1 ms
Loading Gameobject Pooling Data...
>> Loaded 24685 gameobject in pools in 17 ms
Loading Mother Pooling Data...
>> Loaded 2271 pools in mother pools in 1 ms
Loading Quest Pooling Data...
>> Loaded 182 quests in pools in 0 ms
Starting objects pooling system...
Loading Game Event Data...
>> Loaded 120 holiday dates in 0 ms
>> Loaded 73 game events in 0 ms.
Loading Game Event Saves Data...
>> Loaded 0 game event saves in game events. DB table `game_event_save` is empty.
Loading Game Event Prerequisite Data...
>> Loaded 0 game event prerequisites in game events. DB table `game_event_prerequisite` is empty.
Loading Game Event Creature Data...
>> Loaded 9599 creatures in game events in 4 ms.
Loading Game Event GO Data...
>> Loaded 31084 gameobjects in game events in 11 ms.
Loading Game Event Model/Equipment Change Data...
>> Loaded 9 model/equipment changes in game events in 0 ms.
Loading Game Event Quest Data...
>> Loaded 223 quests additions in game events in 0 ms.
Loading Game Event GO Quest Data...
>> Loaded 78 quests additions in game events in 0 ms.
Loading Game Event Quest Condition Data...
>> Loaded 0 quest event conditions in game events. DB table `game_event_quest_condition` is empty.
Loading Game Event Condition Data...
>> Loaded 0 conditions in game events. DB table `game_event_condition` is empty.
Loading Game Event Condition Save Data...
>> Loaded 0 condition saves in game events. DB table `game_event_condition_save` is empty.
Loading Game Event NPCflag Data...
>> Loaded 5 npcflags in game events in 0 ms.
Loading Game Event Seasonal Quest Relations...
>> Loaded 690 quests additions in game events in 0 ms.
Loading Game Event Vendor Additions Data...
>> Loaded 14 vendor additions in game events in 1 ms.
Loading Game Event Battleground Data...
>> Loaded 6 battleground holidays in game events in 0 ms.
Loading Game Event Pool Data...
>> Loaded 8 pools for game events in 0 ms.
Loading UNIT_NPC_FLAG_SPELLCLICK Data...
>> Loaded 326 spellclick definitions in 2 ms
Loading Vehicle Template Accessories...
>> Loaded 187 Vehicle Template Accessories in 0 ms
Loading Vehicle Accessories...
>> Loaded 0 Vehicle Accessories in 0 ms
Loading SpellArea Data...
>> Loaded 726 spell area requirements in 1 ms
Loading AreaTrigger definitions...
>> Loaded 275 area trigger teleport definitions in 0 ms
Loading Access Requirements...
>> Loaded 121 access requirement definitions in 0 ms
Loading Quest Area Triggers...
>> Loaded 60 quest trigger points in 0 ms
Loading Tavern Area Triggers...
>> Loaded 114 tavern triggers in 0 ms
Loading AreaTrigger script names...
>> Loaded 139 areatrigger scripts in 0 ms
Loading LFG entrance positions...
>> Loaded 20 lfg entrance positions in 0 ms
Loading Dungeon boss data...
>> Loaded 612 instance encounters in 0 ms
Loading LFG rewards...
>> Loaded 15 lfg dungeon rewards in 0 ms
Loading Graveyard-zone links...
>> Loaded 700 graveyard-zone links in 0 ms
Loading spell pet auras...
>> Loaded 47 spell pet auras in 1 ms
Loading Spell target coordinates...
>> Loaded 568 spell teleport coordinates in 1 ms
Loading enchant custom attributes...
>> Loaded 32 custom enchant attributes in 1 ms
Loading linked spells...
>> Loaded 459 linked spells in 0 ms
Loading Player Create Data...
>> Loaded 62 player create definitions in 0 ms
Loading Player Create Items Data...
>> Loaded 1 custom player create items in 0 ms
Loading Player Create Skill Data...
>> Loaded 1094 player create skills in 0 ms
Loading Player Create Spell Data...
>> Loaded 2680 custom player create spells in 0 ms
Loading Player Create Cast Spell Data...
>> Loaded 19 player create cast spells in 0 ms
Loading Player Create Action Data...
>> Loaded 325 player create actions in 1 ms
Loading Player Create Level HP/Mana Data...
>> Loaded 800 level health/mana definitions in 0 ms
Loading Player Create Level Stats Data...
>> Loaded 4960 level stats definitions in 4 ms
Loading Player Create XP Data...
>> Loaded 79 xp for level definitions in 0 ms
Loading Exploration BaseXP Data...
>> Loaded 80 BaseXP definitions in 1 ms
Loading Pet Name Parts...
>> Loaded 313 pet name parts in 0 ms
Loading the max pet number...
>> Loaded the max pet number: 0 in 0 ms
Loading pet level stats...
>> Loaded 2560 level pet stats definitions in 2 ms
Loading Player level dependent mail rewards...
>> Loaded 25 level dependent mail rewards in 0 ms
Loading creature loot templates...
>> Loaded 333684 creature loot templates in 472 ms
Loading fishing loot templates...
>> Loaded 266 fishing loot templates in 0 ms
Loading gameobject loot templates...
>> Loaded 18256 gameobject loot templates in 21 ms
Loading item loot templates...
>> Loaded 5017 item loot templates in 8 ms
Loading mail loot templates...
>> Loaded 117 mail loot templates in 0 ms
Loading milling loot templates...
>> Loaded 45 milling loot templates in 3 ms
Loading pickpocketing loot templates...
>> Loaded 11048 pickpocketing loot templates in 15 ms
Loading skinning loot templates...
>> Loaded 1900 skinning loot templates in 4 ms
Loading disenchanting loot templates...
>> Loaded 124 disenchanting loot templates in 4 ms
Loading prospecting loot templates...
>> Loaded 36 prospecting loot templates in 2 ms
Loading spell loot templates...
>> Loaded 168 spell loot templates in 1 ms
Loading reference loot templates...
>> Loaded refence loot templates in 24 ms
Loading Skill Discovery Table...
>> Loaded 347 skill discovery definitions in 2 ms.
Loading Skill Extra Item Table...
>> Loaded 225 spell specialization definitions in 0 ms
Loading Skill Perfection Data Table...
>> Loaded 72 spell perfection definitions in 0 ms.
Loading Skill Fishing base level requirements...
>> Loaded 95 areas for fishing base skill level in 0 ms
Loading Achievements...
>> Loaded 43 achievement references in 0 ms.
Loading Achievement Criteria Lists...
>> Loaded 7655 achievement criteria in 2 ms.
Loading Achievement Criteria Data...
>> Loaded 2692 additional achievement criteria data in 2 ms
Loading Achievement Rewards...
>> Loaded 112 achievement rewards in 0 ms.
Loading Achievement Reward Locales...
>> Loaded 0 achievement reward locale strings.  DB table `achievement_reward_locale` is empty.
Loading Completed Achievements...
>> Loaded 43 realm first completed achievements in 0 ms.
Loading Item Auctions...
>> Loaded 0 auction items. DB table `auctionhouse` or `item_instance` is empty!
Loading Auctions...
>> Loaded 0 auctions. DB table `auctionhouse` is empty.
Loading Guilds...
Loading guilds definitions...
>> Loaded 0 guild definitions. DB table `guild` is empty.
Loading ArenaTeams...
>> Loaded 0 arena teams. DB table `arena_team` is empty!
Loading Groups...
>> Loaded 0 group definitions. DB table `groups` is empty!
Loading ReservedNames...
>> Loaded 0 reserved player names. DB table `reserved_name` is empty!
Loading GameObjects for quests...
>> Loaded 1798 GameObjects for quests in 2 ms
Loading BattleMasters...
>> Loaded 146 battlemaster entries in 2 ms
Loading GameTeleports...
>> Loaded 1432 GameTeleports in 3 ms
Loading Gossip menu...
>> Loaded 5826 gossip_menu IDs in 2 ms
Loading Gossip menu options...
>> Loaded 4188 gossip_menu_option entries in 7 ms
Loading Vendors...
>> Loaded 37498 Vendors in 21 ms
Loading Trainers...
>> Loaded 79765 Trainers in 212 ms
Loading Waypoints...
>> Loaded 128937 waypoints in 279 ms
Loading SmartAI Waypoints...
>> Loaded 570 SmartAI waypoint paths (total 7058 waypoints) in 2 ms
Loading Creature Formations...
>> Loaded 1520 creatures in formations in 2 ms
Loading World States...
>> Loaded 85 world states in 0 ms
Loading Conditions...
>> Loaded 13672 conditions in 22 ms
Loading faction change achievement pairs...
>> Loaded 125 faction change achievement pairs in 0 ms
Loading faction change spell pairs...
>> Loaded 109 faction change spell pairs in 0 ms
Loading faction change quest pairs...
>> Loaded 250 faction change quest pairs in 0 ms
Loading faction change item pairs...
>> Loaded 724 faction change item pairs in 0 ms
Loading faction change reputation pairs...
>> Loaded 16 faction change reputation pairs in 0 ms
Loading faction change title pairs...
>> Loaded 22 faction change title pairs in 0 ms
Loading GM tickets...
>> Loaded 1 GM tickets in 0 ms
Loading GM surveys...
>> Loaded GM Survey count from database in 0 ms
Loading client addons...
>> Loaded 23 known addons in 0 ms
Returning old mails...
>> No expired mails found.
Loading Autobroadcasts...
>> Loaded 0 autobroadcasts definitions. DB table `autobroadcast` is empty for this realm!
Loading spell_scripts...
>> Loaded 130 script definitions in 1 ms
Loading event_scripts...
>> Loaded 476 script definitions in 1 ms
Loading waypoint_scripts...
>> Loaded 717 script definitions in 2 ms
Loading spell script names...
>> Loaded 2091 spell script names in 2 ms
Loading Creature Texts...
>> Loaded 14095 creature texts for 3204 creatures in 17 ms
Loading Creature Text Locales...
>> Loaded 5 creature localized texts in 1 ms
Initializing Scripts...
Loading Script Waypoints for 74 creature(s)...
>> Loaded 1997 Script Waypoint nodes in 2 ms
>> Loaded spline chain data for 56 chains, consisting of 76 splines with 439 waypoints in 1 ms
Loading C++ scripts
>> Loaded 2995 C++ scripts in 33 ms
Validating spell scripts...
>> Validated 2647 scripts in 2 ms
Loading SmartAI scripts...
>> Loaded SmartAIMgr Helpers in 6 ms
>> Loaded 11488 SmartAI scripts in 84 ms
Loading Calendar data...
>> Loaded 0 calendar events in 0 ms
>> Loaded 0 calendar invites in 0 ms
Loading Petitions...
>> Loaded 0 petitions.
Loading Signatures...
>> Loaded 0 Petition signs!
Loading Item loot...
>> Loaded 0 stored item loots
>> Loaded 0 stored item money
Initialize query data...
Initialize game time and timers
Mail timer set to: 180, mail return is called every 1440 minutes
Starting Map System
Starting Game Event system...
Initialize AuctionHouseBot...
Initializing Opcodes...
Starting Arena Season...
Starting Battleground System
>> Loaded 11 battlegrounds in 0 ms
Starting Outdoor PvP System
>> Loaded 6 outdoor PvP definitions in 0 ms
Starting Battlefield System
Loading Transports...
>> Spawned 20 continent transports in 157 ms
Loading Warden Checks...
Loading Warden Action Overrides...
Deleting expired bans...
Calculate next daily quest reset time...
Calculate next weekly quest reset time...
Calculate next monthly quest reset time...
Calculate random battleground reset time...
Calculate guild limitation(s) reset time...
World initialized in 0 minutes 8 seconds
TrinityCore rev. 1cc3d33cfe7e 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...

**Comment by Killyana** [comment]
Cannot reproduce, event with a char level 1, and a distance=6 inside a building this npcs doesn't aggro.
rev. fb31cb7c047f

**Comment by Bluechen80** [comment]
Killyana, its nice that u have no issues but i have them and just close this will not fix it. So pls let us find a way to fix it. U say a distance of 6. where can i check this ?  Pls help me.  And if u need a Video to prof it its no big thing.

**Comment by tkrokli** [comment]
Some details you want to look into:
1. Your core is somewhat old (about a month): TrinityCore rev. 1cc3d33cfe7e 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, Release, Static)
-- we prefer that you test and make reports based on a fairly recent TC core rev. hash.
2. `server debug` can be entered in your Worldserver console, from the `TC>_` prompt. As an example, here is what I get on current core with my settings:
```
TC> server debug
TrinityCore rev. fb31cb7c047f 2018-03-23 17:34:10 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
```
3. Your worldserver console output says
```
Automatic database updates are disabled for all databases!
```
... which hints to that your configuration may be less than optimal in other places as well, which we can't verify. You want to test your issue on default settings before reporting this as an issue caused by TC source.

**Comment by Killyana** [comment]
I tested with this npcs: (and many others) with a player level 1
SpawnID: 90334   being outside
SpawnID: 52881   being inside
SpawnID: 89447
SpawnID: 89450

**Comment by Bluechen80** [comment]
ok guys i understand that and im sorry if it is my own fault. Its a Repack from a Forum and i learned how to compile on my own 3 days ago.

i will compile a newer Version on Monday and i wil test it again with default settings.

I will get back u u then again. Anyways thank u guys for ur time and thx for all your work!

**Comment by Bluechen80** [comment]
Well then u was right. it was my fault! Just compiled a new Version and reextract all the files (map, mmaps, vmaps etc.) And everything is perfect now. So a big sorry. But this helps me to leran how to compile on my own so its a good thing too :)
