### ISSUE TITLE
[master] Manny DB Errors you can help me?

### ISSUE THREAD

**Issue by Trackhe** [TrinityCore/TrinityCore#21688]
**Description:**

I have many DB errors like that does not exist.
I'm trying to fix it with the information from https://github.com/TrinityCore/TrinityCore/issues/20186
but I just made it to create the missing NPC's. Here is my subsequently written log.

**Current behaviour:**

NPC are there, but the server writes these errors: DBerror.log

**Expected behaviour:**

No missing's.

**Branch(es):**

master 7.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1e62b53c6682 2018-03-21 09:59:58 +0100 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Debian 9. with external mysql on another Debian 9 machine.

[DBErrors.log](https://github.com/TrinityCore/TrinityCore/files/1844742/DBErrors.log) (it is much!!!)

Please Help Thanks.

**Comment by Aokromes** [comment]
#15829

**Comment by Trackhe** [comment]
I have soo many missings and issues is this normal?

**Comment by tkrokli** [comment]
Yes, it is normal. Please read the source code and use TrinityCore Forum pages (https://community.trinitycore.org/) if you want to discuss your individual issues after making changes to your own DB or source code.
