### ISSUE TITLE
[Master] Default view distance not blizzlike

### ISSUE THREAD

**Issue by Daribon** [TrinityCore/TrinityCore#21681]
**Description:**
Default view distance is currently lower than it is on retail.

**Current behaviour:**
Currently the default view distance is set to 90.
Instances are set to 170 and battlegrounds/arenas are set to 533.
This is not correct.

**Expected behaviour:**
The default view distance outdoor should be 100. I no longer have the documents that truly shows this, however I'm certain that 100 yards is correct since I've tested it on retail since MoP and it always turn out to be 100 yards.
Instanced view distance should be between 300 and 400 from my tests.
My results from retail for some instances:
399.8383 -- Deadmines
299 -- Gnomeregan
299.7412 -- WC
I do lack my old testing docs on instances,  however I've been able to find my battleground docs.

From my tests, the default battleground view distance should be way higher.
Here is from Netherstorm recorded on in October 2017:
```<Npc>
    <Entry>0</Entry>
    <Name>Pajin</Name>
    <Position>
      <X>1805.883</X>
      <Y>1530.591</Y>
      <Z>1248.403</Z>
      <Type>Flying</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>NetherstormBG</ContinentId>
  </Npc>

Distance: 738.4362

  <Npc>
    <Entry>0</Entry>
    <Name>Aisda</Name>
    <Position>
      <X>1795.463</X>
      <Y>1540.44</Y>
      <Z>1252.986</Z>
      <Type>Flying</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>NetherstormBG</ContinentId>
  </Npc>

Distance: 746.4011
Distance2D: 746.4009
  <Npc>
    <Entry>0</Entry>
    <Name>Postulat</Name>
    <Position>
      <X>1790.371</X>
      <Y>1539.031</Y>
      <Z>1253.573</Z>
      <Type>Flying</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>NetherstormBG</ContinentId>
  </Npc>

Distance: 753.1147
Distance2D: 753.1145
```
From Arathi Basin:
```
  <Npc>
    <Entry>0</Entry>
    <Name>Onimoosha</Name>
    <Position>
      <X>703.449</X>
      <Y>685.8611</Y>
      <Z>-16.33741</Z>
      <Type>Flying</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>PVPZone04</ContinentId>
  </Npc>

Distance: 919.6025

Distance2D: 919.58

  <Npc>
    <Entry>0</Entry>
    <Name>Monuxia</Name>
    <Position>
      <X>707.3217</X>
      <Y>697.4426</Y>
      <Z>-16.49415</Z>
      <Type>Flying</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>PVPZone04</ContinentId>
  </Npc>

Distance: 902.1982

Distance2D: 902.1656
```
From Warsong Gulch:
```
  <Npc>
    <Entry>0</Entry>
    <Name>Allenia</Name>
    <Position>
      <X>938.1502</X>
      <Y>1432.726</Y>
      <Z>345.5357</Z>
      <Type>None</Type>
    </Position>
    <Faction>Alliance</Faction>
    <Type>None</Type>
    <ContinentId>PVPZone03</ContinentId>
  </Npc>
Distance: 587.7457

Distance2D: 587.7102
```
I've attached attached some screenshots showing various players locations during my battlegrounds.
WSG: 
![firefox_2018-03-22_20-57-45](https://user-images.githubusercontent.com/6137576/37795102-c220182a-2e13-11e8-9699-2d090b89cfd3.png)
Arathi Basin:
![firefox_2018-03-22_20-56-25](https://user-images.githubusercontent.com/6137576/37795103-c2455374-2e13-11e8-8bf5-ba2abfe5ea86.png)
Arathi Basin:
![firefox_2018-03-22_20-56-58](https://user-images.githubusercontent.com/6137576/37795104-c269c326-2e13-11e8-9243-a4ee8a077a93.png)
Eye of the Storm:
![firefox_2018-03-22_20-57-26](https://user-images.githubusercontent.com/6137576/37795105-c28e0100-2e13-11e8-8cf2-2a96adda1eef.png)

**Branch(es):**
master
**TC rev. hash/commit:** 
8cff0d4a9062a2eedd0391e21e2cadb363d47904

**Comment by Kittnz** [comment]
Correct however 533.f is the grid size, thats why it can't be higher.

**Comment by tkrokli** [comment]
Still the same unchanged game client limitation from back in 2010?

**Comment by tje3d** [comment]
Similar to #13660 which is stated as won't fix

**Comment by Kittnz** [comment]
Doubt it, prolly 100.f normal world. https://trinitycore.atlassian.net/wiki/spaces/tc/pages/74950924/Lua+Scene+Script+Documentation#LuaSceneScriptDocumentation-ActorAOIRange

**Comment by Daribon** [comment]
I've done some looking around on retail today. This is the following results I got when checking how far I could run before despawn or how close I would have to be for it to spawn.

```EntryID 5595 DynFlags 0 Scale 1
GUID 203ADC00000576C0003083000435522E
Name Ironforge Guard
Mount 0 Level 110 Health 1558901
DisplayID 3526 Distance: 99.7695
TargetPos -4995.1 -1224.35 501.686 0.715585
PlayerPos -4997.37 -1124.6 501.695 1.51064

EntryID 5595 DynFlags 0 Scale 1
GUID 203ADC00000576C0003083000435522E
Name Ironforge Guard
Mount 0 Level 110 Health 1558901
DisplayID 3526 Distance: 100.118
TargetPos -4995.1 -1224.35 501.686 0.715585
PlayerPos -4997.35 -1124.25 501.688 1.51064

EntryID 52335 DynFlags 0 Scale 1
GUID 203ADC0000331BC00030830000355222
Name Dareth
Mount 0 Level 60 Health 15140
DisplayID 37844 Distance: 99.8314
TargetPos -5081.38 -780.411 495.187 3.36849
PlayerPos -5159.62 -735.384 452.559 2.85236

EntryID 727 DynFlags 0 Scale 1
GUID 203CD4000000B5C00060B00000B553C7
Name Ironforge Mountaineer
Mount 0 Level 15 Health 1356
DisplayID 1598 Distance: 100.643
TargetPos -5610.72 -490.063 397.501 2.19911
PlayerPos -5710.11 -505.876 396.461 3.68409

EntryID 727 DynFlags 0 Scale 1
GUID 203CD4000000B5C00060B00003B553CE
Name Ironforge Mountaineer
Mount 0 Level 15 Health 1356
DisplayID 1608 Distance: 97.6948
TargetPos -5373.57 -544.752 400.391 0.471239
PlayerPos -5403.03 -637.533 392.143 2.52769

EntryID 7954 DynFlags 0 Scale 1
GUID 203CD4000007C4800060B000003553B6
Name Binjy Featherwhistle
Mount 0 Level 50 Health 9400
DisplayID 7038 Distance: 99.9576
TargetPos -5457.24 -618.481 393.397 4.97419
PlayerPos -5426.82 -713.697 393.756 1.60248

EntryID 1694 DynFlags 0 Scale 1
GUID 203CD4000001A7800060B000003553BC
Name Loslor Rudge
Mount 0 Level 10 Health 338
DisplayID 3392 Distance: 99.7778
TargetPos -5499.7 -664.575 395.312 0.453786
PlayerPos -5406.27 -629.612 393.345 3.37355

EntryID 42218 DynFlags 0 Scale 1
GUID 20307C0000293A800056BE0007355747
Name Stormwind Royal Guard
Mount 0 Level 110 Health 2078534
DisplayID 32729 Distance: 99.9991
TargetPos -8909.29 -132.802 80.5557 2.11185
PlayerPos -8999.11 -89.1564 85.8201 2.63986

EntryID 49871 DynFlags 0 Scale 1
GUID 20307C000030B3C00056BE0000B5574A
Name Blackrock Worg
Mount 0 Level 1 Health 72
DisplayID 40147 Distance: 99.974
TargetPos -8970.11 -79.942 87.7795 3.91231
PlayerPos -8992.6 -176.856 77.9502 4.96454```

**Comment by Kittnz** [comment]
#21111 
Pretty much the same issue!

**Comment by Takenbacon** [comment]
For battlegrounds it should probably just loop all the grids and cells for visibility searcher, this would be relatively simple and removes the 533 max distance limitation. However, this comes at a cost of a bit more iterations involved due to static grid/cell counts. On the default setup this would be MAX_NUMBER_OF_GRIDS (64) * MAX_NUMBER_OF_CELLS (8) = 512. The difference is probably negligible, but who knows.

Maybe @Shauren has a better idea
