### ISSUE TITLE
Core/Creature: Melee attack reset if the target moves

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21680]
**Description:** if you are in combat with a npc, if you move you char le animation of the melee attack will reset even if the npc doesn't move at all

**Current behavior:** The melee animation is reseting if the player moves an stay at melee range.

**Expected behavior:** The melee animation musn't reset if the player moves an stay at melee range.

**Steps to reproduce the problem:**

1. .go c id 36627
2. start the combat 
3. spam move forward or back without moving the boss
4. Notice the melee animation keep resetting

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 7c5b69d18bb3

**Comment by tkrokli** [comment]
Has this got any relation to the stuck player "attack stance" when doing the quest http://www.wowhead.com/quest=11876/help-those-that-cannot-help-themselves ? Player needs to press 'ESC' or similar to get out of the "attack stance" gained from doing the trap release action.

**Comment by Killyana** [comment]
No, this issue is related to npcs not players.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/11854
