### ISSUE TITLE
Core/Instances: Raid-wide combat ress cooldown underflow

### ISSUE THREAD

**Issue by matukaa** [TrinityCore/TrinityCore#21697]
**Description:**

After 1e62b53c66829dc9820117e17bfb44cb2652f814 the issue with only 1 charge being restored is still not fixed, due to the fact that _combatResurrectionTimer is stored as uint32

**Current behaviour:**

Every update cycle, _combatResurrectionTimer is lowered by the current "diff", but since _combatResurrectionTimer is a uint32, it will underflow is almost all the cases, resulting in the fact that actually no charges are restored at all.

**Expected behaviour:**

Every 90/raidsize minutes 1 charge should be restored for Combat Resurrects.

**Steps to reproduce the problem:**

1. Create 2 characters, one which has a CR
2. Enter a raid and engage a boss
3. Use 1 CR, after the given time, the charge will not be granted, because the timer underflows: https://imgur.com/a/N3lsp

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/f74212c8b8d3d31b4f254538da2f586395ff18a8

**Operating system:** Windows 10

https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Instances/InstanceScript.h#L331

This needs to be changed to int32

**Comment by tkrokli** [comment]
Sure, but is it a better solution than only using positive integers as valid values for `_combatResurrectionTimer` ?

**Comment by Seyden** [comment]
tbh.. i prefer it with uint32.. but its up to @Shauren

**Comment by joschiwald** [comment]
can't reproduce and the timer can't underflow

there must be something wrong on your side, 1e62b53c66829dc9820117e17bfb44cb2652f814 fixed this issue
