### ISSUE TITLE
[3.3.5] Quest: Death Comes From On High

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21691]
**Description:**

In quests http://www.wowhead.com/quest=12641/death-comes-from-on-high  you need to use a subject of "control Mechanism Eye of Zul", after its application you turn into the eye of Zul and need to fly down to inspect the specified locations. Now everything works, except that in oke Zula can't fly!

https://s8.hostingkartinok.com/uploads/images/2018/03/dd4174575290c8fc87825eab2abd650e.png

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/fb31cb7c047f4d79e7bea04b72175e6ef251a317

**Comment by Killyana** [comment]
Cannot reproduce, you are using a non trinity core, or a modified one.

**Comment by vahzxz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21689#issuecomment-376016131
