### ISSUE TITLE
[3.3.5] The air phase of Sindragosa

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21694]
**Description:**

Sindragosa incorrectly takes off and during the air phase goes under the floor in the texture
![image](https://user-images.githubusercontent.com/37352351/37897313-9a1b114e-30ee-11e8-86c1-c4b62c72fe5c.png)

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/fb31cb7c047f4d79e7bea04b72175e6ef251a317

**Comment by Killyana** [comment]
Cannot reproduce
