### ISSUE TITLE
not building on ubuntu 16.04

### ISSUE THREAD

**Issue by daxgo** [TrinityCore/TrinityCore#21699]
I've been some time building this source code, fine with Ubuntu 14.04, but, recently, migrate my servers to Ubuntu 16.04, NOT COMPILING ANYTHING of trinity, even the older sources that compile in the old repo, other sources yes, but this NOT

I have BOOST 1.66, zlib 1.2.11, and the another are from the REPO

look here
root@dayron-pc:/home/dayron/Escritorio/TrinityCore-master/build# cmake ../ -DPREFIX=/home/`echo $USER`/wow -DTOOLS=1
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git
-- 
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* TrinityCore revision   : unknown 1970-01-01 00:00:00 +0000 (Archived branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /usr/local
* Install libraries to   : /usr/local/lib
* Install configs to     : /usr/local/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test STD_HAS_WORKING_WREGEX
-- Performing Test STD_HAS_WORKING_WREGEX - Failed
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
-- Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11") 
-- Looking for open
-- Looking for open - found
-- Found OpenSSL library: /usr/lib/libssl.so;/usr/lib/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/libreadline.so
-- Include dir is: /usr/include
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- CXX target common cotired without unity build.
-- CXX target database cotired without unity build.
-- CXX target proto cotired without unity build.
-- CXX target shared cotired without unity build.
-- CXX target bnetserver cotired without unity build.
-- CXX target game cotired without unity build.

* Script configuration (static):
    |
    +- worldserver
    |   +- Outland
    |   +- Events
    |   +- Northrend
    |   +- World
    |   +- Commands
    |   +- Kalimdor
    |   +- Maelstrom
    |   +- Spells
    |   +- Custom
    |   +- Pet
    |   +- OutdoorPvP
    |   +- EasternKingdoms
    |
-- CXX target scripts cotired without unity build.

-- CXX target worldserver cotired without unity build.
-- Configuring done
CMake Error in dep/g3dlite/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/recastnavigation/Detour/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/recastnavigation/Recast/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/fmt/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/jemalloc/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/gsoap/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/protobuf/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/CascLib/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in dep/CascLib/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/common/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/database/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/proto/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/shared/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/bnetserver/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/game/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/scripts/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/server/worldserver/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/connection_patcher/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/extractor_common/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/map_extractor/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/vmap4_assembler/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/vmap4_extractor/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

CMake Error in src/tools/mmaps_generator/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .

-- Generating done
-- Build files have been written to: /home/dayron/Escritorio/TrinityCore-master/build

doing the make:

root@dayron-pc:/home/dayron/Escritorio/TrinityCore-master/build# make
Scanning dependencies of target g3dlib
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/AABox.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Any.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/AnyTableReader.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryFormat.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryInput.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryOutput.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Box.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Capsule.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/CollisionDetection.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/CoordinateFrame.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Crypto.cpp.o
[  0%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Cylinder.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/debugAssert.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/FileSystem.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/fileutils.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/format.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dfnmatch.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/g3dmath.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/GThread.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Line.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/LineSegment.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Log.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix3.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix4.cpp.o
[  1%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/MemoryManager.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/PhysicsFrame.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Plane.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/prompt.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Quat.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Random.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Ray.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/RegistryUtil.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Sphere.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/stringutils.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/System.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextInput.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/TextOutput.cpp.o
[  2%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Triangle.cpp.o
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/uint128.cpp.o
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/UprightFrame.cpp.o
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector2.cpp.o
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector3.cpp.o
[  3%] Building CXX object dep/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
[  3%] Linking CXX static library libg3dlib.a
[  3%] Built target g3dlib
Scanning dependencies of target Detour
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAlloc.cpp.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMesh.cpp.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshBuilder.cpp.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshQuery.cpp.o
[  3%] Building CXX object dep/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNode.cpp.o
[  3%] Linking CXX static library libDetour.a
[  3%] Built target Detour
Scanning dependencies of target Recast
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/Recast.cpp.o
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAlloc.cpp.o
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastArea.cpp.o
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastContour.cpp.o
[  3%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastFilter.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastLayers.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMesh.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMeshDetail.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRasterization.cpp.o
[  4%] Building CXX object dep/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRegion.cpp.o
[  4%] Linking CXX static library libRecast.a
[  4%] Built target Recast
Scanning dependencies of target fmt
[  4%] Building CXX object dep/fmt/CMakeFiles/fmt.dir/fmt/format.cc.o
In file included from /home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.cc:28:0:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:490:12: error: ‘std::move’ has not been declared
 using std::move;
            ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:857:29: error: expected ‘,’ or ‘...’ before ‘&&’ token
   MemoryBuffer(MemoryBuffer &&other) {
                             ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:857:36: error: invalid constructor; you probably meant ‘fmt::internal::MemoryBuffer<T, SIZE, Allocator> (const fmt::internal::MemoryBuffer<T, SIZE, Allocator>&)’
   MemoryBuffer(MemoryBuffer &&other) {
                                    ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:861:40: error: expected ‘,’ or ‘...’ before ‘&&’ token
   MemoryBuffer &operator=(MemoryBuffer &&other) {
                                        ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h: In member function ‘void fmt::internal::MemoryBuffer<T, SIZE, Allocator>::move(fmt::internal::MemoryBuffer<T, SIZE, Allocator>&)’:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:841:18: error: ‘move’ is not a member of ‘std’
     this_alloc = std::move(other_alloc);
                  ^
In file included from /usr/include/c++/5/cassert:43:0,
                 from /home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:32,
                 from /home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.cc:28:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h: In member function ‘fmt::internal::MemoryBuffer<T, SIZE, Allocator>& fmt::internal::MemoryBuffer<T, SIZE, Allocator>::operator=(fmt::internal::MemoryBuffer<T, SIZE, Allocator>)’:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:862:21: error: ‘other’ was not declared in this scope
     assert(this != &other);
                     ^
In file included from /home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.cc:28:0:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h: At global scope:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:3302:39: error: expected ‘,’ or ‘...’ before ‘&&’ token
   BasicMemoryWriter(BasicMemoryWriter &&other)
                                       ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:3302:46: error: invalid constructor; you probably meant ‘fmt::BasicMemoryWriter<Char, Allocator> (const fmt::BasicMemoryWriter<Char, Allocator>&)’
   BasicMemoryWriter(BasicMemoryWriter &&other)
                                              ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:3311:50: error: expected ‘,’ or ‘...’ before ‘&&’ token
   BasicMemoryWriter &operator=(BasicMemoryWriter &&other) {
                                                  ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h: In member function ‘fmt::BasicMemoryWriter<Char, Allocator>& fmt::BasicMemoryWriter<Char, Allocator>::operator=(fmt::BasicMemoryWriter<Char, Allocator>)’:
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:3312:15: error: ‘move’ is not a member of ‘std’
     buffer_ = std::move(other.buffer_);
               ^
/home/dayron/Escritorio/TrinityCore-master/dep/fmt/fmt/format.h:3312:25: error: ‘other’ was not declared in this scope
     buffer_ = std::move(other.buffer_);
                         ^
dep/fmt/CMakeFiles/fmt.dir/build.make:62: fallo en las instrucciones para el objetivo 'dep/fmt/CMakeFiles/fmt.dir/fmt/format.cc.o'
make[2]: *** [dep/fmt/CMakeFiles/fmt.dir/fmt/format.cc.o] Error 1
CMakeFiles/Makefile2:450: fallo en las instrucciones para el objetivo 'dep/fmt/CMakeFiles/fmt.dir/all'
make[1]: *** [dep/fmt/CMakeFiles/fmt.dir/all] Error 2
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by tje3d** [comment]
@daxgo No supported, you need to upgrade to Ubuntu 17.10

**Comment by Gooyeth** [comment]
@daxgo: It does not correspond here, visit https://community.trinitycore.org/

**Comment by Aokromes** [comment]
https://i.imgur.com/HFvioVP.png

**Comment by daxgo** [comment]
Thank you "Aokromes" and "tje3d", many thanks, I had my broken head, literal, whit that
