### ISSUE TITLE
[3.3.5] Explanation of the problem

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21692]
**Description:**

Problems:
https://github.com/TrinityCore/TrinityCore/issues/21691
https://github.com/TrinityCore/TrinityCore/issues/21689

Answer:
https://github.com/TrinityCore/TrinityCore/issues/21689#issuecomment-376016131

REV https://github.com/TrinityCore/TrinityCore/commit/3420b8d5c4dd21b66502ace7cd6ee210d6e6e8e1

**Comment by Aokromes** [comment]
this is not a forum, and like we have show you we cannot reproduce the bug.
