### ISSUE TITLE
DB/Quest: "Feathers for Nafien" & "Speak to Salfa"

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21706]
**Description:**

Quests "Feathers for Nafien" and "Speak to Salfa" should become available after quest "Deadwood of the North" is rewarded.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Fix prerequisite for quest "Feathers for Nafien"
UPDATE `quest_template_addon` SET `PrevQuestID`=8461 WHERE `ID`=8467;

-- Fix prerequisite for quest "Speak to Salfa"
DELETE FROM `quest_template_addon` WHERE `ID`=8465;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(8465,0,0,0,8461,0,0,0,0,0,0,0,0,0,0,0,0);

**Comment by ZenoX92** [comment]
It's a pleasure, @Gooyeth. :)

**Comment by msoky** [comment]
thx for your work, can you add to every commit link to wowhead? it will be much easier to search what is fixing
