### ISSUE TITLE
Problem with npcbots to spawn not possible

### ISSUE THREAD

**Issue by nussige** [TrinityCore/TrinityCore#21703]
**Description:**

Problem with npcbots to spawn not possible

**Current behaviour:**

if I make .npcb loo 1 (for Kríeger)
and ID example: .npc add 70224 spawn no npcbots

**Expected behaviour:**

npcbots to spawn not possible

**Steps to reproduce the problem:**

1.  https://picload.org/view/daiodwpw/1.jpg.html

2. if I make .npcb loo 1 (for Kríeger) or .npc add 70224 spawn no npcbots 

3. So in creature_template all are in there 70001 to 70246
if I add .npc add 70224 it does not work
but he creates it in world creature
and do not create it in characters_npcbot
If I add it to characters_npcbot, the server crashes 

**Branch(es):**

bots-test    (335)

https://github.com/livingsacrifice/TrinityCore/tree/bots-test

**TC rev. hash/commit:** 

TrinityCore rev. 19820ac0689a 2018-03-16 13:44:13 -0500 (bots-test branch) (Win64, Release, Static) (worldserver-daemon)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.0q 15 Jan 2015)
Using Boost version: 1.63.0
Using MySQL version: 5.6.36
Using CMake version: 3.8.0
Using World DB: TDB 335.63
Visual studio 2015 Community

**Operating system:** 

Windows 10 Home x64

**Comment by Aokromes** [comment]
this tracker is for TrinityCore, not for forks.

**Comment by nussige** [comment]
sorry I was here in the forum

**Comment by tkrokli** [comment]
This is **not** a forum. This is the **TrinityCore issue tracker** (general real source code bug reporting) where users can _document what is wrong_ in the _unchanged_ TrinityCore source code.
