### ISSUE TITLE
missing player information "AREA"

### ISSUE THREAD

**Issue by razielvonchronos** [TrinityCore/TrinityCore#21727]
**Description:**  Missing Area information in `.pi` command

**Current behavior:**
I just noticed that when I type `.pi` the Area is `<unknown>`.
When I use .pi command it shows `Area:  <unknown>`

**Expected behavior:**
When you use .pi command it should show Area: 2037

**Steps to reproduce the problem:**
1. enter in game
2. use the command `.pi`
3. be awesome as always ^^ 

**Branch(es):**   3.3.5

**TC rev. hash/commit:**  e482d9f303c73e86df49b1943122a70418cfef27

**Operating system:**  Win7 64 OS

**Comment by tkrokli** [comment]
Just tested the command `.pinfo` or `.pi` -- it shows `Area: <unknown>` only if the Zone + Area is the same (no separately named subzone (Area).
Use the command `.gps` to verify and see if that is what happens. This issue is cosmetic, to say the least.

**Comment by razielvonchronos** [comment]
You are right,I went to Eastern Plaguewands(zone139) and Blackwood Lake (area 2624), ".pi" and ".gps" command showed the Area number and name.
.go xyz 4244.6 -2731.4 6.1 0 0 (Quel'thalas  cords)
So as you said it is just when Area and Zone are the same.

**Comment by tkrokli** [comment]
OK, thanks for confirming that bit. I suppose it could be fixed if someone can figure out how to make the command display the Zone name as Area name if there is no actual Area name for that coordinate.

**Comment by razielvonchronos** [comment]
I am sorry for bringing back this threat to life,but I am just curious. 
Why is there no Area column?

**Comment by Killyana** [comment]
Pinf and .gps doesn't return the same Area: (It was like this since ever)

.Pinf: Map: Royaumes de l'est, Area:  <unknown> , Zone: Quel'thalas
.gps: Map: 0 (Royaumes de l'est) Zone: 2037 (Quel'thalas) Area: 2037 (Quel'thalas) Phase: 4294967295
On the actual core:

**Comment by illfated** [comment]
Maybe someone who knows how to write proper code checks would like to compose an addition to the `.pinfo` command so it substitutes `<unknown>` with the Zone name if there is no name for the Area (if that would be an acceptable solution).

**Comment by razielvonchronos** [comment]
It is not a big deal,but I am wondering why there is no Area column,since I just realized that I can't make a SQL query in PHP to echo the player's area into "Online Players" page.
Anyway,you probably have bigger things to do,I was just curious ^^

**Comment by illfated** [comment]
Good point, I forgot about the DB part of the issue. Have to wait and see if anyone picks up the "challenge".

**Comment by Aokromes** [comment]
Easy, area ain't saved because client don't asks for it for who is online.
If you want to known how to get area with php go check:
https://github.com/TrinityCore/minimanager

**Comment by razielvonchronos** [comment]
Thank you @Aokromes  ^,.,^
