### ISSUE TITLE
Critters enter Evade and do not die from some attacks

### ISSUE THREAD

**Issue by Bluechen80** [TrinityCore/TrinityCore#21736]
OK me again. I hope I post everything right the first time.

**Description:**
I try to kill deer, cows, chicken and so on with spells. Some work, some not. So I tried to kill a deer with a Priest's **Shadow Word: Pain**, but it just ignored my spell. I tried to kill a Sheep with a Mage's Fireball, but nothing happened to the Sheep. I have tested this with all dot spells, but Shadow Word: Pain is 100%

Level 1 Mage and level 13 Priest

**Current behaviour:**
Cast **Shadow Word: Pain** and the critter does not die. Here are two videos where you can see what I am talking about:
- https://www.youtube.com/watch?v=RSWdmz0Vx7w 
- https://www.youtube.com/watch?v=G3MqayMztao

**Expected behaviour:**
Cast the spell and the critter dies.

**Branch(es):**  3.3.5a

**TC rev. hash/commit:**  TrinityCore rev. 99993a7f62b2 2018-03-26

**TDB version:**  TDB 335.64

**Operating system:**  Windows 10

**Comment by tkrokli** [comment]
TrinityCore rev. b274c4b5c346 2018-03-28 04:15:09 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

I can to some extent confirm this for a higher level character too (hunter level 74). When using ranged attack (bow+arrows), the first attack usually causes the critter to enter Evade and can sometimes cause the player character to get stuck in melee attack stance. Sometimes the critter dies on the second shot, some times not at all and in that case it will only die if a melee attack lands on it.

**Comment by Bluechen80** [comment]
I tested it with Pets today, for example the Warlocks Imp Pet. He's working the way he's supposed to. No evading at all!!!!

**Comment by Killyana** [comment]
This was fixed by previous commits
