### ISSUE TITLE
[3.3.5] Unable to cast Druid Fight Forms in Northrend 

### ISSUE THREAD

**Issue by mc2programmer** [TrinityCore/TrinityCore#21744]
**Description:**
Unable to cast "Flight Form" (33943) or "Swift Flight Form" (40120) in Northrend

**Current behaviour:**
If you try to cast either Flight form anywhere in Northrend you get the following message
"You can't use that here."

**Expected behaviour:**
Spell 33943 and 40120 state
Shapeshift into swift flight form, increasing movement speed by 280% and allowing you to fly. Cannot use in combat. Can only use this form in Outland or Northrend.

The act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.
these spells do work in Outland

**Steps to reproduce the problem:**

1. Try to cast either flight form in Northrend

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
DB/locales_quest: Fix localizations for Manhunt
Closes #17353
1.0.9567
a day ago by Aokromes (committed by GitHub)
3.3.5 88130d86

**Operating system:**
Windows 7/Linux

**Comment by Aokromes** [comment]
I am still unable to reproduce it on 88130d86b0ab, be sure you have learned fly on northrend.
