### ISSUE TITLE
Crash when trying to despawn vehicle after killing accessory

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21746]
**Description:**
Server crashes when I kill NPC mounted on vehicle.

```
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=55506;
UPDATE `creature_template` SET `VehicleId`=2360, `AIName`='SmartAI' WHERE `entry`=64258;

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (55506, 64258);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
-- Raggis
(55506, 0, 0, 0, 0, 0, 100, 0, 8000, 12000, 35000, 40000, 11, 125383, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Raggis - Update IC - Cast Burrow'),
-- Raggis (vehicle)
(64258, 0, 0, 0, 54, 0, 100, 0, 0, 0, 0, 0, 85, 125386, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Raggis - Just Spawned - Invoker Cast Raggis Ride Vehicle'),
(64258, 0, 1, 0, 28, 0, 100, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Raggis - Passenger Removed - Despawn');
```
**Current behaviour:**
[Crashlog](https://gist.github.com/Lopfest/e6a98e29cfc2b9490d94cc6b125f79b6)

**Steps to reproduce the problem:**
1. execute query in description
2. .npc add temp 55506
3. wait for him to finish casting burrow
4. kill him while burrowed

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 8454bbb5ac0f+ 2018-03-31 12:53:53 +0200 (testPhases branch) (Win64, Debug, Dynamic)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May2017)
Using Boost version: 1.65.0
Using MySQL version: 5.6.28
Using CMake version: 3.9.5
Compiled on: Windows
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 826214003 bytes
vmaps directory located in ./vmaps. Total size: 4981383659 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Operating system:** Win 7 x64

**Comment by DoctorKraft** [comment]
Maybe 551d0559aac663e9485b0eaffac5326536180c27

**Comment by Lopfest** [comment]
i tested above patch and it still crashed. here is crashlog with applied patch if needed. [crashlog](https://gist.github.com/Lopfest/7f3f24ec56bb091208e17518f6c70e45)

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Aokromes** [comment]
no answer, closing.
