### ISSUE TITLE
SPELL_EFFECT_PERSISTENT_AREA_AURA ignore phases

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21747]
**Description:**
spells with SPELL_EFFECT_PERSISTENT_AREA_AURA ignore phasing and effect are always "spawned" in default phase instead of current caster's phase. This bug was also present even before phasing rewrite.
Example spells: 10341, 11829, 17742, 19099, 132020

**Current behaviour:**
spell effect always appears only in default phase

**Expected behaviour:**
spells with this effect should "spawn" effect in caster's current phase(s)

**Steps to reproduce the problem:**
1. cast any spell with SPELL_EFFECT_PERSISTENT_AREA_AURA while phased

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 8454bbb5ac0f+ 2018-03-31 12:53:53 +0200 (testPhases branch) (Win64, Debug, Dynamic)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May2017)
Using Boost version: 1.65.0
Using MySQL version: 5.6.28
Using CMake version: 3.9.5
Compiled on: Windows
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 826214003 bytes
vmaps directory located in ./vmaps. Total size: 4981383659 bytes
mmaps directory located in ./mmaps. Total size: 6218932948 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Operating system:** Win 7 x64

**Comment by ariel-** [comment]
Guess it needs spell searchers for DynAuras ported from 3.3.5 branch

**Comment by Shauren** [comment]
No, it just needs `PhasingHandler::InheritPhaseShift(dynObj, spellCaster)` somewhere
