### ISSUE TITLE
DB/Quest: The Fight Continues

### ISSUE THREAD

**Issue by MauFus** [TrinityCore/TrinityCore#21745]
**Description:**

Quest [The Fight Continues](http://www.wowhead.com/quest=26208/the-fight-continues) has no prerequisite

**Current behaviour:**

Above-mentioned quest may be accepted even if previous quest hasn't been completed

**Expected behaviour:**

Above-mentioned quest may be accepted only if player have completed one of previous quest, which are different for each class (pls refer to Wowhead page linked above)

**Steps to reproduce the problem:**

1. Create a Gnome character
2. Go to [High Tinker Mekkatorque](http://www.wowhead.com/npc=42317/high-tinker-mekkatorque)
3. You can accept [The Fight Continues](http://www.wowhead.com/quest=26208/the-fight-continues) even if no previous quest has been completed

**Branch(es):**

master

**TC rev. hash/commit:** 

Commit: ad948edac0f4b2bf54cbef4eea6d5590918827b5

**Operating system:** Windows

**Fix:** 
The following query fix the problem (tested):
```sql
UPDATE `quest_template_addon` SET `NextQuestID` = 26208 where `ID` in (26421, 26422, 26423, 26424, 26425, 31137, 41218);
```

**Comment by tkrokli** [comment]
TC source does not use `world.` as part of the solution, because some users don't necessarily name their world DB "world". Also, the update is automatically added to the world DB by the `sql/updates/world/master` folder will be placed in.

**Comment by MauFus** [comment]
Thanks for the hint!
I updated the query accordingly

**Comment by tkrokli** [comment]
Please also add back ticks ( ` ) around the names of the fields
```
`quest_template_addon` `NextQuestID` `ID`
```

**Comment by MauFus** [comment]
Done
