### ISSUE TITLE
DB/Spell: Rake

### ISSUE THREAD

**Issue by DanVS** [TrinityCore/TrinityCore#21759]
**Description:**

Rake must ignore armor on application. See [patch note](https://wow.gamepedia.com/Rake):
`Patch 2.0.1 (05-Dec-2006): The initial damage is no longer mitigated by armor.`

``` sql
-- Rake
SET @SPELL_ATTR0_CU_IGNORE_ARMOR = 32768;
DELETE FROM `spell_custom_attr` WHERE entry IN (1822,1823,1824,9904,27003,48573,48574);
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(1822, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 1
(1823, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 2
(1824, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 3
(9904, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 4
(27003,@SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 5
(48573,@SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 6
(48574,@SPELL_ATTR0_CU_IGNORE_ARMOR); -- Rake, rank 7
```

**Branch(es):**

- [x] 3.3.5
- [ ] master

**TC rev. hash/commit:** 

TC>TrinityCore rev. e350cfc4374f+ 2018-04-02 00:48:08 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.58.0
Using MySQL version: 5.7.21
Using CMake version: 3.5.1
Compiled on:  
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 252191207 bytes
vmaps directory located in ../data/vmaps. Total size: 588247501 bytes
mmaps directory located in ../data/mmaps. Total size: 2152621156 bytes
Using World DB: TDB 335.64

**Comment by tkrokli** [comment]
There are 7 ranks of the spell, so maybe add https://woehead.way-of-elendil.fr/?spell=48574 too?
```sql
DELETE FROM `spell_custom_attr` WHERE entry IN (1822,1823,1824,9904,27003,48573,48574);
INSERT INTO `spell_custom_attr` (`entry`,`attributes`) VALUES
(1822, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 1
(1823, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 2
(1824, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 3
(9904, @SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 4
(27003,@SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 5
(48573,@SPELL_ATTR0_CU_IGNORE_ARMOR), -- Rake, rank 6
(48574,@SPELL_ATTR0_CU_IGNORE_ARMOR); -- Rake, rank 7
```
... or is there something special about rank 7 that makes it unneeded here?

**Comment by DanVS** [comment]
Just forgot :) Thanks!

**Comment by DanVS** [comment]
It does not work itself. I have tested second level spell with and without this change. In first case rake damages for about 16 on apply, in second for 28, which is much closer to the tooltip specified. 16 also matches armor reduction formula: `3791÷((85×58)+3791+400)×100 ≈ 41,5%`.

**Comment by ariel-** [comment]
Ah, I know why is this. Because damage processed out of order. (effIndex == -1 in that case)
