### ISSUE TITLE
Spell power scales backwards beyond level 80

### ISSUE THREAD

**Issue by akke92** [TrinityCore/TrinityCore#21764]
**Description**
I've compiled a TC (latest rev) and have made some core changes to be able to reach beyond level 80. 
(Max level 255). 
The issue is that spell power does not scale as it should when going beyond level 80. 

**Current behaviour:**
Spell damage works perfectly up to level ~80. After level 80 (we're talking 100-255) the spells start doing less damage the higher level you get?! It's like it's scaling backwards when going higher in levels. When you're level 255 it gives about as much as when you're level 1.

**Expected behaviour:**
As i've made custom changes to the DB resulting in that you get +stats for each level after 80, it shouldn't decrease the spell damage when it reaches higher levels. It should instead continue increasing the spell damage as it does for level 1 - 80

**Steps to reproduce the problem:**
1. Set your servers max level to above 80. 
2. Create a spell caster and set it's level to the servers max level or any level beyond level 80. 
3. Cast spells and notice that you're doing very low damage. (You can from here also change back to level 80 to notice that the spell damage is significantly higher than on the higher levels. Just for proving purposes)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c2f16579888b 2018-03-31 09:13:33 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.63.0
Using MySQL version: 5.6.39
Using CMake version: 3.11.0
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** 
Windows 10.0.16299

**Comment by Aokromes** [comment]
this is unsuported here.

**Comment by Shauren** [comment]
This is intended. Spellpower scaling has diminishing returns based on your level vs level of the rank of spell you are using (this is to discourage downranking)

**Comment by akke92** [comment]
I suppose that you don't have the permission to give me guidelines to where this could be removed so that i may customize my core the way i want it?

**Comment by tkrokli** [comment]
That is material for the Trinity Forum pages (https://community.trinitycore.org/forum/9-custom-code-and-requests/) -- look for "Non-Blizzlike hacks".

**Comment by akke92** [comment]
Thanks Tkrokli!

Unfortunately the "Non-Blizzlike hacks" forum has been inactive for more than a year and i will therefore probably not get any help in a reasonable time slot.
But thank you for your time!

**Comment by akke92** [comment]
@Shauren Thank you for pointing me in the right direction.
Found the algorithm for CalculateLevelPenalty and modified it for my compile and got it working flawlessly.

Best regards,
akke92

**Comment by Crackjawz** [comment]
@akke92 Hey I think what you've done is interesting would you mind detailing how you did a little bit ? That would be great still new to programming and such trying to learn as much as I can. Thank you in advance !
