### ISSUE TITLE
Core/Phasing: TerrainSwappedMaps not swapping

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21773]
**Description:**
Note: before phasing rewrite this was working

On Wandering Isle there are 2 terrain swaps. 
```sql
DELETE FROM `terrain_worldmap` WHERE `TerrainSwapMap` IN (975, 976);
INSERT INTO `terrain_worldmap` (`TerrainSwapMap`, `WorldMapArea`, `Comment`) VALUES
(975, 683, 'Wandering Isle terrain injured'),
(976, 683, 'Wandering Isle terrain healed');
```
Before quest [Risking It All](http://www.wowhead.com/quest=30767/risking-it-all) is complete/rewarded, player has active default map 860.
After this quest becomes complete, map should swap to 975.
Then after quest [The Healing of Shen-zin Su](http://www.wowhead.com/quest=29799/the-healing-of-shen-zin-su) is rewarded, map should swap to 976.

I have put tons of logging everywhere, probably the most important part is PhasingHandler::OnConditionChange.
- If I don't define anything in terrain_swap_defaults (which should be correct) then none of the swapped terrains work. Player is always in default map 860. In logs there is none terrain, not in phaseShift neither suppressedPhaseShift.
- If I define value `(860, 860, '')`, then none of the swapped terrains work. Player is always in default map 860. In logs is mentioned only one map - 860, which is in phaseShift.
- If I define value `(860, 975, '')`, then default map is ok, second terrain 975 is ok, but terrain 976 is never applied. In logs is mentioned only one terrain map - 976 which is in suppressedPhaseShift.
- If I define value `(860, 976, '')`, then default map is ok, second terrain 975 is never applied and terrain 976 is ok. In logs is mentioned only one terrain map - 975 which is in suppressedPhaseShift.

Here are the conditions:
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=25 AND `SourceEntry` IN (975, 976);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
-- TerrainSwaps
(25, 0, 975, 0, 0, 28, 0, 30767, 0, 0, 0, 0, 0, '', 'TerrainSwap 975 only when player has quest 30767 complete'),
(25, 0, 975, 0, 1, 8, 0, 30767, 0, 0, 0, 0, 0, '', 'TerrainSwap 975 only when player has quest 30767 rewarded'),
(25, 0, 975, 0, 1, 8, 0, 29799, 0, 0, 1, 0, 0, '', 'TerrainSwap 975 only when player has quest 29799 not rewarded'),
(25, 0, 975, 0, 2, 1, 0, 118233, 0, 0, 0, 0, 0, '', 'TerrainSwap 975 only when player has aura'), -- temp
(25, 0, 976, 0, 0, 8, 0, 29799, 0, 0, 0, 0, 0, '', 'TerrainSwap 976 only when player has quest 29799 rewarded'),
(25, 0, 976, 0, 0, 1, 0, 118233, 0, 0, 1, 0, 0, '', 'TerrainSwap 976 only when player has not aura'); -- temp
```

**Current behaviour:**
terrainSwapMap seems to be not even loaded, regardless whether i meet condition or not

**Expected behaviour:**
terrainSwapMap should be loaded and applied when condition is met

**Steps to reproduce the problem:**
1. .go xyz 248 3931 66 860
2. .quest add 30767
3. .quest complete 30767
4. then progress through next quest

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. c7d6873c3616 2018-04-03 17:18:46 +0200 (WanderingIsle branch) (Win64, Debug, Dynamic)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May2017)
Using Boost version: 1.65.0
Using MySQL version: 5.6.28
Using CMake version: 3.9.5
Compiled on: Windows 6.1.7601
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 900646209 bytes
vmaps directory located in ./vmaps. Total size: 4984780324 bytes
mmaps directory located in ./mmaps. Total size: 6374007076 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Operating system:** Win 7 x64

**Comment by Ovahlord** [comment]
Did you try to negate the terrain swap by using negative conditions?

**Comment by tkrokli** [comment]
BTW, is this DB only, or a Core + DB issue?

**Comment by Lopfest** [comment]
@Ovahlord playing with condition wont help if the terrainswap is not even registered as inactive map.
@tkrokli i think its core only issue

**Comment by Lopfest** [comment]
ok, i just found out that i was inserting terrainSwaps in wrong table. terrain_swap_defaults has to contain terrainSwaps, not terrain_worldmap!

**Comment by dio85** [comment]
i want swap in stormwind... 1064 or what is the id. but not work... 

SourceTypeOrReferenceId	SourceGroup	SourceEntry	SourceId	ElseGroup	ConditionTypeOrReference	ConditionTarget	ConditionValue1	ConditionValue2	ConditionValue3	NegativeCondition	ErrorType	ErrorTextId	ScriptName	Comment
25	0	29548	0	0	9	0	1064	0	0	0	0	0		StormwindPandaria


if the conditions value the quest id, not work too.
if CTOR not 9->8 not work too.
i added the map on terrain_map_swap, and the terain_woldmap too.
Any idea?

The questID 29548 The Mission
