### ISSUE TITLE
[master] DB/Creature: Trainer Update 3

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21788]
**Description:**

Another update for trainers.
https://gist.github.com/funjoker/36f6b3df3c9aa695ca7dc7d525dca3c1

**Branch(es):**

master

**TC rev. hash/commit:** 

72a9a8a29c4e7af6ece82ebd7b0330403ee38e57

**Operating system:** Win10

**Comment by tkrokli** [comment]
There are more than a few spell ID duplicates in your UPDATE queries.
Any chance you could reduce the number of or remove all duplicates?
