### ISSUE TITLE
[3.3.5] Core/Movement: flight <-> walk transition movement flag update issue

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21787]
**Description:**

The problem is the following
Under attack are the Valkyries, when she descends, then falls in Mat
![image](https://user-images.githubusercontent.com/37352351/38423002-50a62088-39b5-11e8-896d-61d7db356bc9.png)
I decided to put the Valkyrie on the track team, to check what the problem is. In the end, Valkyrie is like need
![image](https://user-images.githubusercontent.com/37352351/38423073-8bdf4fee-39b5-11e8-8299-fde6ce74b449.png)
When attacking, as it is necessary correctly
![image](https://user-images.githubusercontent.com/37352351/38423298-31bc746e-39b6-11e8-8327-4bbae018f03e.png)
But he returned it to its place again, half the textures
![image](https://user-images.githubusercontent.com/37352351/38423356-51c49b10-39b6-11e8-9892-5af57fa80234.png)
The first assumption I had was that it was an unsuccessful update, but I waited a week and Poltava again updated the core and the base, but everything remained in its place and constantly all rests on the NPC, which fly, the same problem with Lana, she must return to its place running, and it's the place that flies
![image](https://user-images.githubusercontent.com/37352351/38423552-ea4e5a60-39b6-11e8-9985-5e3abe4dd8ed.png)
Sorry for my translation from Russian

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/9f03743d2d803cba553b2f95a87b106bf5e3f672

![image](https://user-images.githubusercontent.com/37352351/38422750-8acd918e-39b4-11e8-8dd4-86808fbbed28.png)

![image](https://user-images.githubusercontent.com/37352351/38422702-653de68a-39b4-11e8-935d-ca215b5d9093.png)

**Comment by Aokromes** [comment]
use .server debug command when reporting bugs.

**Comment by vahzxz** [comment]
@Aokromes 
![image](https://user-images.githubusercontent.com/37352351/38423877-dbfb8568-39b7-11e8-8015-f45d081a92ba.png)
![image](https://user-images.githubusercontent.com/37352351/38423887-e6c372b2-39b7-11e8-9c66-5b2202464b74.png)
![image](https://user-images.githubusercontent.com/37352351/38423928-0daaed9c-39b8-11e8-9a9d-4c4685f1ef98.png)
If that VMAP turned off to check whether it will solve the problem

**Comment by vahzxz** [comment]
It is the problem that occurs when the NPC flies

**Comment by vahzxz** [comment]
![image](https://user-images.githubusercontent.com/37352351/38424611-4d23076e-39ba-11e8-9e55-b9304e6a5e8c.png)
In the crypt of NPS in General are not moving to me
They only attack when I get there. 
![image](https://user-images.githubusercontent.com/37352351/38424711-9ce235cc-39ba-11e8-918f-7d632d691d40.png)

**Comment by vahzxz** [comment]
![image](https://user-images.githubusercontent.com/37352351/38425875-bb2d0ebe-39bd-11e8-9967-fdf30ef4c0fd.png)
LSU the problem not only with flying the NPC

**Comment by Ovahlord** [comment]
It is basicly a movement flag update issue. The core currently does not properly recocgnize to switch between flight and walk so when a creature is flying and comes to the ground the core somehow still recognizes the creature as flying.

**Comment by tkrokli** [comment]
@vahzxz : You should definitely test again after commit https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4 to check for changes.

**Comment by Killyana** [comment]
I'm not able to reproduce all  this issues
About: walk transition movement flag update issue: https://github.com/TrinityCore/TrinityCore/issues/15247
