### ISSUE TITLE
[3.3.5] Incorrect movement of the NPC

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#21793]
**Description:**

Recently discussed this appeal https://github.com/TrinityCore/TrinityCore/issues/21787 In the comments it was written that you need to update the kernel to this revision https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4
![image](https://user-images.githubusercontent.com/37352351/38459931-05262b12-3ab9-11e8-949b-505d1d5bc9da.png)
![image](https://user-images.githubusercontent.com/37352351/38459936-12b6069e-3ab9-11e8-97a8-1dba3f5e8c27.png)
![image](https://user-images.githubusercontent.com/37352351/38459941-1bf488de-3ab9-11e8-9476-d540effd2b4d.png)
The problem with Valkyries come around, but not fully
![image](https://user-images.githubusercontent.com/37352351/38459956-4a40ca2c-3ab9-11e8-9c9c-475c468794b8.png)
But if you move a little backward or forward, well, get Valkyrie to move, then there is this situation.
![image](https://user-images.githubusercontent.com/37352351/38459971-83a81f9a-3ab9-11e8-8d67-264d42137b2f.png)
My treatment permanently closed due to the fact that not those who do not have this problem, but I always take off the screenshots that I have a new revision and periodically updating the kernel. And once again, I'm re-assembling the maps.

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4

**Comment by Killyana** [comment]
Just set: Movement type: Ground: Hover

**Comment by Killyana** [comment]
Actually I cannot reproduce even with:
Movement type: Ground: None, Swim: false, Flight: DisableGravity

**Comment by Treeston** [comment]
@Shauren since hover is your stuff i guess?

**Comment by Nitair** [comment]
You can go into Stratholme (to the ziggurats) and notice that these Gargoyles shows the same issue (maybe better as with these valkyrs)

**Comment by Treeston** [comment]
share the `worldserver.conf` you are reproducing this with please

**Comment by vahzxz** [comment]
@Treeston http://dropmefiles.com/8WY6p

**Comment by Nitair** [comment]
@vahzxz we should use https://gist.github.com/
I've added you conf file as gist https://gist.github.com/Nitair/3ca1d7bd8b056ac215a4b579ac8dab44

**Comment by illfated** [comment]
only diff from worldserver.conf compared to worldserver.conf.dist is DB names

**Comment by vahzxz** [comment]
@Nitair thank

**Comment by vahzxz** [comment]
https://youtu.be/E_VguYYRC6U
Video of the problem

**Comment by Shauren** [comment]
Thats not a problem. In the output of .server debug you have `MMAPs status: Disabled`

**Comment by vahzxz** [comment]
@Shauren I MMAPS also included - this does not solve the problem. can record video with included MMAP

**Comment by illfated** [comment]
isn't Golrag working on another map fix for stuff like this?

**Comment by vahzxz** [comment]
@illfated not understand

**Comment by illfated** [comment]
Sorry, my bad. I didn't see https://github.com/TrinityCore/TrinityCore/pull/21658#issuecomment-379492967 until now.
