### ISSUE TITLE
[master] DB/broadcast_text Update some broadcast_texts

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21799]
**Description:**

Added some broadcast_text data (needed for npc_text)
https://gist.github.com/funjoker/44aee7a836bc173b52c9871fb882f5f6

**Branch(es):**

master

**TC rev. hash/commit:** 

4ea54b80bc4f0364ceab5ad94fb701ded292647b

**Operating system:** Win10

**Comment by joschiwald** [comment]
since broadcast_text is able to bruteforce, i won't accept a partial update

**Comment by funjoker** [comment]
Wondering why i have additions and not only Updates. A Lot Texts are not even 7.3.5 content
