### ISSUE TITLE
[BUG] DND

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21795]
hi

/dnd It has a problem
if player say  /dnd !  all cant wis to player!

/dnd no wis me

windows server 2016
trinitycore https://github.com/TrinityCore/TrinityCore/commit/4ea54b80bc4f0364ceab5ad94fb701ded292647b

I remember that too old was the bug in Trinity

**Comment by offl** [comment]
https://us.battle.net/forums/en/wow/topic/2522075136
