### ISSUE TITLE
DB/Creatures: Update model

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#21812]
**Description:**

- Add default data for models of creatures
- Remove models deprecated

I know a sniff are needed for get object scale but it's only a base
Greatly reduced DB errors

**Suggested fix:**

https://gist.github.com/DoctorKraft/203fad8ac1fdd7303cf1c111958c535d

**Branch(es):**

- [X] Master

 master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/08193cf625b6e2af54eba2bd36145837500a1c33

**Comment by funjoker** [comment]
do not push it yet.
I gonna add more soon here too

**Comment by Aokromes** [comment]
when soon(TM)? :P
