### ISSUE TITLE
[3.3.5] Major bug - Shadow Priest GM invisibility as player!

### ISSUE THREAD

**Issue by eocrs** [TrinityCore/TrinityCore#21815]
**Description:**

This works for Shadow Priests.
Following the steps to reproduce this you gain GM invisibility as normal player.

**Current behaviour:**

Basically Shadow Priest players gain invisibility, GM like, not target-able. 
I tested on various races, with .learn all my class / learn from trainer, works for all situations.

**Expected behaviour:**

You should not be able to cast Dispersion while mounted.

**Steps to reproduce the problem:**

1. Mount up (any mount)
2. Cast Shadowform
3. Cast Dispersion
4. Cancel Shadowform BEFORE Dispersion expires (quick cancel)

Step 1 or 2 don't need to be in exact order, only the order of 3 and 4 is important to reproduce this.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
Latest build but was working even 2 weeks ago.
1e25b215e5c5a94b85addcc79ce4851f3269dc95

**Operating system:** CHANGEME OS
Win Server 2012 R2

**Comment by Keader** [comment]
#240
#8526
#2529
#1538
Blizzlike bug :)
