### ISSUE TITLE
DB/Spawn: Change SpawnMask for Ulduar

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#21813]
**Description:**

- Change SpawnMask to Raid Flex and Timewalking for Ulduar raid

Greatly reduced DB errors

**Suggested fix:**

https://gist.github.com/DoctorKraft/f80d361cfb19e27eb8729e7cab38d171

**Branch(es):**

- [X] Master

 master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/08193cf625b6e2af54eba2bd36145837500a1c33

**Comment by joschiwald** [comment]
what happened to chests which were 10 men or 25 men only?

**Comment by Shauren** [comment]
Loot tables for 10 and 25man were merged
