### ISSUE TITLE
DB/Quests: Update ProvidedItemCount in quest_template_addon

### ISSUE THREAD

**Issue by DoctorKraft** [TrinityCore/TrinityCore#21811]
**Description:**

- Add default data based on StartItem of quests

Greatly reduced DB errors

**Suggested fix:**

https://gist.github.com/DoctorKraft/7543bcccaf47b2cad57477d7b8689275

**Branch(es):**

- [X] Master

 master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/08193cf625b6e2af54eba2bd36145837500a1c33

**Comment by joschiwald** [comment]
how did you generated these sqls?

**Comment by DoctorKraft** [comment]
Generated with SQL errors. Some quests can need more than 1 stack but in this state, the core add this default value if nothing found.
