### ISSUE TITLE
Forge of Souls mob groups separable

### ISSUE THREAD

**Issue by TecDian** [TrinityCore/TrinityCore#21829]
**Description:**

Mobs in groups can be pulled one by one.

**Expected behaviour:**

Pull one, get all.

**Steps to reproduce the problem:**

1. Enter the instance.
2. Pull first mob of second group.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3cd7851
TrinityCore rev. 3cd7851 2018-04-09 16:53:41 +0200 (3.3.5 branch) (Win64, Release, Static)
 Using SSL version: OpenSSL 1.0.2l 25 May 2017 (library: OpenSSL 1.0.2l 25 May 2017)
 Using Boost version: 1.65.0
 Using MySQL version: 5.6.37
 Using CMake version: 3.9.3
 Compiled on: Windows 10.0.16299
 Automatic database updates are disabled for all databases!
 Worldserver listening connections on port 8085
 Realmlist (Realm Id: 1) configured in port 8085
 VMAPs Status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
 MMAPs status: Enabled
 maps directory located in ./maps. Total size: 253388027 bytes
 vmaps directory located in ./vmaps. Total size: 592050936 bytes
 mmaps directory located in ./mmaps. Total size: 2152621724 bytes
 Using deDE DBC Locale as default. All available DBC locales: deDE
 Using World DB: TDB 335.64

**Operating system:** Windows 10

**Comment by Pugnadeus** [comment]
Same issue as reported here, just different instance
https://github.com/TrinityCore/TrinityCore/issues/20714
