### ISSUE TITLE
Mist of the Kvaldir

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21825]
**Description:**
https://www.wowhead.com/spell=54119/mist-of-the-kvaldir

**Current behaviour:**
The mist effect placed on players within the Riplash Strand area in Borean Tundra currently overpowers the death effect.

**Expected behaviour:**
Mist spell should only be effective while alive.

**TC rev. hash/commit:**
TrinityCore rev. 1e25b215e5c5 2018-04-11 21:39:37 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.64.0
Using MySQL version: 5.5.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Comment by illfated** [comment]
Are you sure, do you have any proof for that?
The last wowhead comment suggests that it is intended:

By KeiyaDMF (494 – 2·10) on 2010/03/02 (Patch 3.3.2)
Entering the mist while dead causes the blue-and-white death screen effect to be replaced by the "engulfed by the mist" screen effect... enabling you to see your ghost in colour! (It's still blue though.)
Interestingly, if you have the Animal Blood debuff on you, drops of blood are visible dripping off your ghost.

**Comment by Killyana** [comment]
It also have the attribute SPELL_ATTR2_CAN_TARGET_DEAD.
