### ISSUE TITLE
[master] npc_vendor slots

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21831]
**Description:**

I'm unsure if slots are static. Or are different depending on which realm you are.
Would mean it's unclever to parse slots of npc_vendor items. And would make this column unnecessary.

**Current behaviour:**

Slots are static.

**Expected behaviour:**

I'm unsure if slots are static. Or are different depending on which realm you are.
I've sniffed some npcs several times and the slots seem to change.

**Branch(es):**

master

**TC rev. hash/commit:** 
60c4c29da53da5bad7b40045d10478242d9ce764

**Operating system:** Win 10

**Comment by Killyana** [comment]
Slots changes when a limited Item is purchased, in this case items after this slot takes current slot-1

**Comment by offl** [comment]
But in other cases the slots are static. And they seems to be created manually.

**Comment by Killyana** [comment]
I tested and it works correctly as on retail, so we will keep sniffed slots.
