### ISSUE TITLE
Knockback for NPC - drop them under texture 

### ISSUE THREAD

**Issue by kvipka** [TrinityCore/TrinityCore#21839]
**Description:**

When you cast spell with knockback effect, you can drop npc in texture, if it happen near slope.

**Current behaviour:**

For example .tele tanaris and play with spells with knockback effects.

**Expected behaviour:**

Npc shouldn't drop under textures

**Steps to reproduce the problem:**

1. .tele tanaris.  
2. .learn 51490
3. Go at npc : scorpions or dogs and cast it 

**Branch(es):**

3.3.5

**TC rev. hash/commit:**  743980a6255a222827d4cc8555eccb14192cb260

**Operating system:** Win64

Video : https://www.youtube.com/watch?v=C85HG8Ia1VA&feature=youtu.be

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/21255

**Comment by SoulKah** [comment]
Bump to give this issue some attention, first attempts looked promising but the topic died ;(

**Comment by Langerz82** [comment]
I'm having a bit of a look into this.

**Comment by Langerz82** [comment]
Test Please:
https://gist.github.com/Langerz82/e35f37c279c2ca455e9941a6a72752a4

Be aware that knockback in tight areas such as dungeons has not been tested yet.

**Comment by Killyana** [comment]
This was fixed
