### ISSUE TITLE
Quest/SpellClick/Loot: Gluttonous Lurkers (12527) - Zul'Drak Rat gives no loot

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#21841]
**Description:**

For the quest http://www.wowhead.com/quest=12527/gluttonous-lurkers
you are supposed to pick up 5x5 http://www.wowhead.com/npc=28202/zuldrak-rat
(the critters are lootable as long as you are on the quest)
and thereby collect 5x5 http://www.wowhead.com/item=38380/zuldrak-rat
which you are supposed to throw at a http://www.wowhead.com/npc=28145/lurking-basilisk (5x)
to turn it into a http://www.wowhead.com/npc=28203/gorged-lurking-basilisk
so you can finally loot the quest item http://www.wowhead.com/item=38382/basilisk-crystals (5x)

**Current behaviour:**

When you loot the live Zul'Drak Rat (NPC 28202), they despawn (as expected), but don't give any loot what so ever.

(Possibly related to **DB/SAI: spell 47096 does not create any loot item** #21772 )

**Expected behaviour:**

When you loot the live Zul'Drak Rat (NPC 28202) and with the quest active, the loot should be 100% Zul'Drak Rat (item 38380) -- 1 item looted for each NPC despawned.

**Steps to reproduce the problem:**

1. get a level 75+ character (practical level for the area)
2. `.quest add 12527`
3. Right-click and loot (moneybag icon) any of the Zul'Drak Rat NPCs
4. Notice that you don't get any expected loot.

**Branch(es):**

Tested on 3.3.5, but could be valid on master if the same SAI/conditions/spell system applies to master.

**TC rev. hash/commit:** 

TC>server debug
TrinityCore rev. 743980a6255a 2018-04-15 17:08:48 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10 Home x64

**Comment by Killyana** [comment]
Dup #21772
