### ISSUE TITLE
[Master] Allied races creation

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#21840]
**Description:**

Cannot create a Void Elf, even when having the required achievements. Might be same for other races.

**Expected behaviour:**

Should be able to create and log in

**Steps to reproduce the problem:**

1. Log in on a normal character and grant yourself achievements [12066](http://www.wowhead.com/achievement=12076/protector-of-the-argussian-reach), [12076](http://www.wowhead.com/achievement=12066/you-are-now-prepared), and [12447](http://www.wowhead.com/achievement=12447/allied-races-void-elf-unlock-requirements)
2. Open character creation and try to select Void Elves

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 6f0078a89dab 2018-04-15 13:33:25 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 10

**Comment by Shauren** [comment]
blocked by lack of account wide achievements

**Comment by Smerdokryl** [comment]
@Shauren any temporary workaround?

**Comment by Smerdokryl** [comment]
allied races when

**Comment by Aokromes** [comment]
soon(TM)

**Comment by vileninja** [comment]
any ETA on allied races?

**Comment by Aokromes** [comment]
soon(TM), you don't have even mop content.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24175#issuecomment-588511187

**Comment by Lillecarl** [comment]
@vileninja https://wowwiki.fandom.com/wiki/Soon If you didn't get the reference
