### ISSUE TITLE
[Master] CharBaseInfo hotfix table

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#21855]
Not there in TrinityCore rev. 11c3c456b7e1 2018-04-18 20:27:45 +0300 (master branch) (Win64, RelWithDebInfo, Static). Will it be added?

**Comment by Aokromes** [comment]
when someone makes one PR to use it.

**Comment by Smerdokryl** [comment]
'PR'?

**Comment by illfated** [comment]
PR = **Pull Request** - also known as "a suggested fix" - to the existing TrinityCore source code.
Probability for the PR content to be merged into TC source depends on how good the suggested fix is.

**Comment by Smerdokryl** [comment]
@illfated Well, it's not exactly a fix, unless CharBaseInfo was intended to be there (though, why in the world would it not be?), more of a suggestion of an additional feature

**Comment by Gooyeth** [comment]
@Smerdokryl: It's simple, you just have to wait for someone to do the implementation.

**Comment by Smerdokryl** [comment]
@Gooyeth or do it myself, once I'm capable

**Comment by Shauren** [comment]
Loading new DB2s is very easy, just follow the same pattern as every other DB2. But why is this one needed?

**Comment by Smerdokryl** [comment]
@Shauren to enable new Race/Class combos
