### ISSUE TITLE
[BUG] AutoDistributePoints!

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21858]
hi

on worldserver.conf

Arena.AutoDistributePoints = 1
and
Arena.AutoDistributeInterval = 7

but the server fast rest team ratings arenas!
Every few minutes!
Flushing Arena points based on team ratings, this may take a few .....

debian server

last: https://github.com/TrinityCore/TrinityCore/commit/a5df77a9d6f3e48f2c4e8a61d60e3b5f2f0c326e

**Comment by Gooyeth** [comment]
Please give me the result of this query of the DB characters:
```sql
SELECT `value` FROM `worldstates` WHERE `entry`=20001;
```

**Comment by irgc** [comment]
hi dear
backup of  character database and table is

INSERT INTO `worldstates` (`entry`, `value`, `comment`) VALUES
(20001, 4838400, 'NextArenaPointDistributionTime');

**Comment by irgc** [comment]
@Gooyeth 

in my server 
Arena DistributePoints is disable!
It takes a long time to fix this؟

**Comment by Aokromes** [comment]
test https://github.com/TrinityCore/TrinityCore/pull/21859

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/59f80f555c2b7608ee2457e8f4a93d0418022a1b
