### ISSUE TITLE
[Master] TARGET_UNK_120 not implemented

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#21854]
**Description:**

Learning [[The Codex of Xerrath]](http://www.wowhead.com/spell=101508/the-codex-of-xerrath) or adding it in character_spells and logging in causes worldserver.exe to freeze indefinitely after displaying the following error:

```
C:\TrinityLegion\Core\src\server\game\Spells\Spell.cpp:1217 in Spell::SelectImplicitAreaTargets ASSERTION FAILED:
  false && "Spell::SelectImplicitAreaTargets: received not implemented target reference type"
```

**Steps to reproduce the problem:**

1. .learn 101508

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 11c3c456b7e1 2018-04-18 20:27:45 +0300 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
#18558
