### ISSUE TITLE
[BUG] Death Knight Quests

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21864]
1. [Into the Realm of Shadows]
- cant move creatures for get start

2. [The Gift That Keeps On Giving]
- cant move creatures for  get start

the last tc3.3.5 : tested all quests Dk Area is worked , just this quests! 

os: windows 2016
version: https://github.com/TrinityCore/TrinityCore/commit/b19413aaf21d439d5b9735a13cec70410b58027f

**Comment by Killyana** [comment]
Don't remove the template.

**Comment by msoky** [comment]
which OS is "win 2016"? :)

**Comment by Aokromes** [comment]
windows server 2016.

**Comment by Killyana** [comment]
The Gift That Keeps On Giving works correctly for me.
