### ISSUE TITLE
[master] DB: Update broadcast_text and broadcast_text_locale

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21867]
**Description:**

Bruteforce Build: 26365

###  broadcast_text
enUS: https://gist.github.com/funjoker/1fc3f70120a50b04e824669d1f9a4592

### broadcast_text_locale
deDE: https://gist.github.com/funjoker/b60b4d1dac40277908dbf12e67292cc0

frFR: https://gist.github.com/funjoker/e75b8eb2c829f0d8893f897eebf3c1f3

esES: https://gist.github.com/funjoker/7bfe883b67f3ecca522a88e9bd9dd2e9

zhTW: https://gist.github.com/funjoker/20db82512714c23f8e29c5dbd607b6db

itIT: https://gist.github.com/funjoker/4f9bdde11556c7fea24ed7c9184f1aeb

zhCN: https://gist.github.com/funjoker/34dd2700d3d51f271b66a2cdc925646d

ptBR: https://gist.github.com/funjoker/c3b0ec9534207325607640f86aba5cfb

koKR: https://gist.github.com/funjoker/3d30fa791aa316c82c04a9f48b9c3b55

esMX: https://gist.github.com/funjoker/61b3a8d7d6fb34016e6bb2692b267efb

ruRU: https://gist.github.com/funjoker/53af6ded4c84c39bea7ece2a52aa6965

VerifiedBuild Updates (all): https://gist.github.com/funjoker/4a895c406238a82a4399869712e0b9c6

**TC rev. hash/commit:** 

48911ec01c9c8d0c5006c3473112dab74f4b4837

**Comment by Killyana** [comment]
129 Mo I cannot push that.

**Comment by joschiwald** [comment]
i'm not going to push that now, the delete queries needs to be simplified like `ID IN (x, y) AND locale=z`
same with the VerifiedBuild only updates

**Comment by joschiwald** [comment]
also waiting for bruteforce of the current build

**Comment by funjoker** [comment]
> also waiting for bruteforce of the current build 

i dont think that there a many differences between this build and current. If there even some.

**Comment by funjoker** [comment]
UPDATED TO: 26365

**Comment by funjoker** [comment]
@joschiwald there you go

**Comment by funjoker** [comment]
Needs more fix.
Found issues according to Escaping rules.

**Comment by funjoker** [comment]
Ok. Now it's fine to go.
