### ISSUE TITLE
Pet Trainer Varzok not training (also all trainers in Brill and Undercity)

### ISSUE THREAD

**Issue by Pickausrname** [TrinityCore/TrinityCore#21878]
**Description:**
Said profession and pet trainer not working; the conversation dialogue box does open, showing the option "train me". But when you click on it, no further action happens.

**Current behaviour:**
As above

**Expected behaviour:**

When you click the "Train Me." option , a spell will be cast upon you and you will learn the spell.

**Steps to reproduce the problem:**
1. Go to: http://www.wowhead.com/npc=63626/varzok
2. Click on him, which opens up the conversation dialogue box.
3. Click on "Train Me." And nothing happens.

**Branch(es):*
Master

TC Rev.:
TrinityCore rev. 95475fed2e18 2018-04-17 19:57:49 +0200 (master branch) (Win64, RelWithDebInfo, Static)

Windows:
Compiled on: Windows 10.0.16299

DB:
Using World DB: TDB 735.00

**Comment by Pickausrname** [comment]
Asides from reporting this bug, all I really wanted isjust ot be able to do Pet Battles.
I have tried adding to the character_spells table, the spell Id (125610) for "Battle Pet Training", that I sniffed from spell.db2. This does activate the Battle Pet Tab, as in I can buy pets and drop them in the battle pet slots. But I cannot track battle pets on the map, and I cannot initiate fights against them.
Is it possible to enable Battle Pet playing by manipulating the DB?

Thanks!

**Comment by funjoker** [comment]
Battle Pet is BARELY implemented

**Comment by Pickausrname** [comment]
Ok, do Battle Pets doesn't curently work? O well. 

Is it possible to fix the bug where the trainer is not training?

**Comment by funjoker** [comment]
Sniff the trainers and you can fix it ^^

**Comment by mdX7** [comment]
Fixed in 6374145060884c4d7bc6eba56a6ffee7c6b44266
