### ISSUE TITLE
Fedora 27 make error on RandomMovementGenerator.cpp.o

### ISSUE THREAD

**Issue by maramound** [TrinityCore/TrinityCore#21871]
**Description:**

Fedora server 27 (64-bit), MySQL 5.7 Community Server, TC Branch-3.3.5a

/root/TrinityCore/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp:29:1: error: definition of explicitly-defaulted ‘RandomMovementGenerator<T>::~RandomMovementGenerator() [with T = Creature]’

**Current behaviour:**

[ 16%] Building CXX object src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/RandomMovementGenerator.cpp.o
/root/TrinityCore/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp:29:1: error: definition of explicitly-defaulted ‘RandomMovementGenerator<T>::~RandomMovementGenerator() [with T = Creature]’
 RandomMovementGenerator<T>::~RandomMovementGenerator() = default;
 ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2458: src/server/game/CMakeFiles/game.dir/Movement/MovementGenerators/RandomMovementGenerator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1280: src/server/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Expected behaviour:**

no error

**Steps to reproduce the problem:**

cd ~/
git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git
cd TrinityCore
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/root/trinity-server -DTOOLS=1 -DWITH_WARNINGS=1
make

i tried using mariadb instead. still seeing that "MYSQL_SERVER_VERSION was not declared in this scope" error with mariadb (#21755).

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

commit fcb1e3e6424ef86934132e1111052a6798d78bc9
Date:   Thu Apr 19 17:35:57 2018 +0200

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Fedora server 27 (64-bit)

**Comment by Aokromes** [comment]
74760aa

**Comment by maramound** [comment]
Did I provide the wrong commit value? I ran the the git clone command this morning. I'm not sure how I can upgrade to anything newer...?

**Comment by Aokromes** [comment]
git pull
