### ISSUE TITLE
Core: Incorrect Death state

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21873]
**Description:** If you die near a creature than .saveall and close the server without releasing the spirit, if you connect your char back you will find it dead and the npc is attacking it, you cannot release (as there's no release interface)  the pinf returns Alive ?: Yes, but you're actually dead.

**Steps to reproduce the problem:**

1. go at an agressive creature position
2. once incombat .die your char
3. .saveall
4. Close the server
5. start the server and connect you char
6. Notice the issue

Could be related to https://github.com/TrinityCore/TrinityCore/issues/21481

**Branch(es):** 3.3.5

TrinityCore rev. 4b8410717f5f 2018-04-22 21:54:37 +0200 (heads/ccrs/movesplinemove branch) (Win32, Release, Static)
Using SSL version: OpenSSL 1.0.1e 11 Feb 2013 (library: OpenSSL 1.0.1e 11 Feb 2013)
Using Boost version: 1.59.0
Using MySQL version: 5.5.39
Using CMake version: 3.10.1
Compiled on: Windows 10.0.16299
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2229000480 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR 
Using World DB: TDB 335.64

**Comment by Eleix** [comment]
Odd, I just tried to reproduce it on rev. 970c617ebae7 2018-04-18 and I did not experience the bug you encountered. I .saveall after dying, I shut the server down, restarted and rejoined the server on my still dead (unreleased spirit) character and I was already ported to the graveyard.

**Comment by Treeston** [comment]
Confirm, I can reproduce.

**Comment by Treeston** [comment]
Weird. With `.saveall` I can reproduce, without I cannot.

why oh why do i suspect dotcommand dark magix.
