### ISSUE TITLE
Server crash related with pet issues

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21870]
**Description:**

After you tamed a pet, if you attack and kill a beast with the same id of the pet(NPC ID) the server crashes. The beast should be killed with that pet, even happen if that beast focus your pet and you kill it.
- It seems the crash only happen with the pet "Carrion Bird" specifically with the NPC http://www.wowhead.com/npc=16973/bonestripper-vulture
http://www.wowhead.com/npc=16972/bonestripper-buzzard
- Tested with both of those pets and tested with a Rhino pet, the last one didn't crash the server.
Crashlog: https://gist.github.com/Tatara902/3800672a552dcf001f6d6c108577d58b

**Current behaviour:**

Server crashes after killing a beast with your pet with the same NPC ID of that pet.

**Expected behaviour:**

Not a crash

**Steps to reproduce the problem:**

1. Step: Tame a pet with the ID 16973 
2. Step Attack and kill a beast of the same id (16973) with your own pet
3. Step Wait for crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. f1ab32fbb7d5+ 2018-04-22 17:22:26 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.39
Using CMake version: 3.10.2
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Win 10 x64

**Comment by joschiwald** [comment]
provide a crashlog

**Comment by irgc** [comment]
こんにちは :smile:

**Comment by Tatara902** [comment]
Cant provide a crashlog since the worldserver.exe doesn't stop working, so there is no  "crashes"  folder
After reproducing the bug the last thing that is written in worldserver.exe is " C:\Trinity\TrinityCore\src\server\game\AI\CoreAI\UnitAI.h:36 in EnsureAI ASSERTION FAILED:
  cast_ai "

**Comment by illfated** [comment]
If the server does not crash, you should edit the title and the main issue post and replace "crash" with a better explanation for what happens when you get that error message.

**Comment by Killyana** [comment]
Crash log: https://gist.github.com/Killyana/4ef26826186602a2c7d1a4fab5953129

**Comment by Shauren** [comment]
just amazing... sai strikes again

**Comment by Killyana** [comment]
This is the SAI for the 2 npcs:
``` sql
DELETE FROM `creature_text` WHERE `CreatureID` IN (16972, 16973);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(16972, 0, 0, "%s smells a fresh corpse nearby.", 16, 0, 100, 0, 0, 0, 16746, 0, "Bonestripper Buzzard"),
(16973, 0, 0, "%s smells a fresh corpse nearby.", 16, 0, 100, 0, 0, 0, 16746, 0, "Bonestripper Vulture");

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (16972, 16973) AND `source_type`=0 AND `id` IN (1, 2, 3);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16972, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 16972, 20, 0, 0, 0, 0, 0, "Bonestripper Buzzard - On Death - Set Data 1 1 to nearby Bonestripper Buzzard"),
(16972, 0, 2, 3, 38, 0, 100, 0, 1, 1, 0, 0, 69, 0, 0, 0, 0, 0, 0, 19, 16972, 100, 1, 0, 0, 0, 0, "Bonestripper Buzzard - On Data 1 1 Set - Move To Pos"),
(16972, 0, 3, 0, 61, 0, 100, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Bonestripper Buzzard - On Data 1 1 Set - Talk 0"),
(16973, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 16973, 20, 0, 0, 0, 0, 0, "Bonestripper Vulture - On Death - Set Data 1 1 to nearby Bonestripper Vulture"),
(16973, 0, 2, 3, 38, 0, 100, 0, 1, 1, 0, 0, 69, 0, 0, 0, 0, 0, 0, 19, 16973, 100, 1, 0, 0, 0, 0, "Bonestripper Vulture - On Data 1 1 Set - Move To Pos"),
(16973, 0, 3, 0, 61, 0, 100, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Bonestripper Vulture - On Data 1 1 Set - Talk 0");
```

Player's pets doesn't execute any SAI, so I don't see how this could happen.

**Comment by Shauren** [comment]
Most likely its action target selected a player pet (see OP, `Server crashes after killing a beast with your pet with the same NPC ID of that pet`)

**Comment by ccrs** [comment]
yeah, the pet still has the ai name on its template, so IsSmart still selects it as valid
maybe some new TYPE values can solve this easily
