### ISSUE TITLE
[master] Eviscerate

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#21874]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** 
Id of the Eviscerate is changed.
> http://www.wowhead.com/spell=196819/eviscerate

2098 - Run Through
196819 - Eviscerate

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 71212cc 2018-04-22 01:47:34 +0200 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2l 25 May 2017 (library: OpenSSL 1.0.2j 26 Sep 2016)
Using Boost version: 1.64.0
Using MySQL version: 5.6.28
Using CMake version: 3.9.6
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5235125273 bytes
mmaps directory located in ./mmaps. Total size: 6070137420 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Operating system:** Windows 10 x64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by ArcaneFox** [comment]
[Tested ingame]
Suggested Fix:

/* Existing Spells */
/* 2098      spell_rog_eviscerate */
/* 2098 spell_rog_serrated_blades */
DELETE FROM `spell_script_names` where `spell_id` IN (2098, 196819);
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(2098, 'spell_rog_run_through'),
(196819, 'spell_rog_eviscerate');

**Comment by illfated** [comment]
http://www.wowhead.com/spell=2098/run-through
Script `spell_rog_run_through` not yet implemented.

http://www.wowhead.com/spell=196819/eviscerate
Still commented as spell ID 2098 in current master:
https://github.com/TrinityCore/TrinityCore/blob/48911ec01c9c8d0c5006c3473112dab74f4b4837/src/server/scripts/Spells/spell_rogue.cpp#L918-L919
