### ISSUE TITLE
 [master] DB: Update quest_template, quest_locales and relations

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#21889]
**Description:**

Bruteforce Build: 26365

###  quest_template
- enUS: 
  - template + objectives + visual: https://gist.github.com/funjoker/361885732c2a57ddd3ee159a16cabf59
### quest_locales

- deDE:
  - template: https://gist.github.com/funjoker/9733f362f57bd396c1a2ae4c178ff721
  - objectives: https://gist.github.com/funjoker/79f704cd6a5a88d6b15c3deffc00a310
 
- frFR: 
  - template: https://gist.github.com/funjoker/f5d695d1749748290f0ca03ffb79bab3
  - objectives: https://gist.github.com/funjoker/02f2307e19f1a31910914a01d37a1b32
 
- esES: 
  - template: https://gist.github.com/funjoker/c3d1ad2d6231e38c42ff877af4c4c252
  - objectives: https://gist.github.com/funjoker/d9cfc24a762ba39758d34e917f38cae8
 
- zhTW: 
  - template: https://gist.github.com/funjoker/7851ac0bd60b855dc3e3cd6d35f8f3ec
  - objectives: https://gist.github.com/funjoker/edf14925146cec3ee4fdaac94d340bcd
 
- itIT: 
  - template: https://gist.github.com/funjoker/923022c23570a436075660729e6978b6
  - objectives: https://gist.github.com/funjoker/03a10341c09998b99eadd1e28b80b2cf
 
- zhCN: 
  - template: https://gist.github.com/funjoker/fe353d92e66305bbdae332851a1d5e3b
  - objectives: https://gist.github.com/funjoker/1b8bb2fea29c163ec05c19a64123b533
 
- ptBR: 
  - template: https://gist.github.com/funjoker/67ee19944c4c9bfb715e391591bf293e
  - objectives: https://gist.github.com/funjoker/fa644cadf9291f78b6b606694105d972
 
- koKR: 
  - template: https://gist.github.com/funjoker/7a33f13d8f1632af14509f57b9e6d2a1
  - objectives: https://gist.github.com/funjoker/7c91c6964c6a08b18c21ff78a550096b
 
- esMX: 
  - template: https://gist.github.com/funjoker/6d97033e5cf5c7a7050c65573929af54
  - objectives: https://gist.github.com/funjoker/00eaee722199b97f2f3b9430237e70e8
 
- ruRU: 
  - template: https://gist.github.com/funjoker/14906d026f0cc3d11fce507fda403af6
  - objectives: https://gist.github.com/funjoker/361e1e225380f12eadd46ef8a5d8ca26
 
- VerifiedBuild Updates (all): 
  - https://gist.github.com/funjoker/e88889ab80020c0e2cb6ffc417b34dfa

**TC rev. hash/commit:** 

48911ec01c9c8d0c5006c3473112dab74f4b4837

**Comment by DoctorKraft** [comment]
Sound good! Nice work 👍

**Comment by Killyana** [comment]
French locales looks fine.

**Comment by funjoker** [comment]
Ok everything ready to go.
