### ISSUE TITLE
Karazhan Issues with Opera Event

### ISSUE THREAD

**Issue by Tatara902** [TrinityCore/TrinityCore#21881]
**Description:**

After talking to Barnes to start the "Opera Event" he walks to the middle of the opera hall and he should introduce one of the events that should occur, however he doesnt introduce any event and then he walks back out of the hall. The curtain opens but there is no boss, so you get stucked in the hall and not being able to enter again because the "Instance is in Combat".

**Current behaviour:**

Opera Event is not working, Barnes doesn't introduce the event.

**Expected behaviour:**

Opera Event Should work.

**Steps to reproduce the problem:**

1. Step. Enter Karazhan and kill Moroes to be able to talk with Barnes.
2. Step Talk to Barnes and enter the opera event.
3. Step Watch how he walks back and the you get stucked in.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 52cfea6d9c47+ 2018-04-25 11:14:01 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.39
Using CMake version: 3.10.2
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Win 10 x64

**Comment by midiman369** [comment]
I'm experiencing the same issue.  is there a workaround that I'm not finding from other opera related issues (most closed)?

**Comment by Maxwelllmj** [comment]
add "m_uiEventId = urand(1, 3);" before "StartEvent();"

**Comment by illfated** [comment]
@Maxwelllmj : that sounds interesting, especially if it solves the issue.
Would you like to try a pull request with that code added?

**Comment by Maxwelllmj** [comment]
@illfated  I don't have my own fork, it may takes a little time. I am syncing code here is slow.

**Comment by Killyana** [comment]
related to https://github.com/TrinityCore/TrinityCore/issues/23008
