### ISSUE TITLE
Warlock Immolate DOT not working.

### ISSUE THREAD

**Issue by Pickausrname** [TrinityCore/TrinityCore#21882]
Description:
When immolate is cast, the DoT icon that should appear on the mob does not come up, and the Mob doesn't seems to be taking DoT. 

Current behaviour:
As above

Expected behaviour:

When immolate is cast, the DoT icon should appear on the mob, and the Mob should take the DoT described in the spell description.. 

Steps to reproduce the problem:

1. Go to a mob, cast Immolate on it.

*Branch(es):
Master

TC Rev.:
TrinityCore rev. 95475fe 2018-04-17 19:57:49 +0200 (master branch) (Win64, RelWithDebInfo, Static)

Windows:
Compiled on: Windows 10.0.16299

DB:
Using World DB: TDB 735.00

**Comment by ArcaneFox** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19666
