### ISSUE TITLE
Errors while compiling world server with latest codes

### ISSUE THREAD

**Issue by yisunfc** [TrinityCore/TrinityCore#21883]
**Description:**

I've run a test server based on branch 3.3.5 for almost 2 months. However, I've failed in compiling world server for several times since I pulled the latest code yesterday. In addition, it still failed after executing `make clean && make` command.

**Current behaviour:**

The error logs are as follows:
> [ 98%] Linking CXX executable worldserver
../scripts/libscripts.a(chapter1.cpp.o): In function `npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(int)':
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp:1062: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(boss_headless_horseman.cpp.o): In function `boss_headless_horseman::boss_headless_horsemanAI::SpellHit(Unit*, SpellInfo const*)':
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/ScarletMonastery/boss_headless_horseman.cpp:608: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(trial_of_the_champion.cpp.o): In function `npc_announcer_toc5::npc_announcer_toc5AI::DoSummonGrandChampion(unsigned int)':
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp:288: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp:291: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp:294: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(boss_the_lich_king.cpp.o):/root/games/TrinityCore_code/TrinityCore/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp:750: more undefined references to `ChaseAngle::ChaseAngle(float, float)' follow
../game/libgame.a(MotionMaster.cpp.o): In function `GenericMovementGenerator':
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: undefined reference to `vtable for GenericMovementGenerator'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: undefined reference to `vtable for GenericMovementGenerator'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: undefined reference to `vtable for GenericMovementGenerator'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: undefined reference to `vtable for GenericMovementGenerator'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: undefined reference to `vtable for GenericMovementGenerator'
../game/libgame.a(MotionMaster.cpp.o):/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h:32: more undefined references to `vtable for GenericMovementGenerator' follow
../game/libgame.a(ChaseMovementGenerator.cpp.o): In function `PositionOkay(Unit*, Unit*, boost::optional<float>, boost::optional<float>, boost::optional<ChaseAngle>)':
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/ChaseMovementGenerator.cpp:43: undefined reference to `ChaseAngle::IsAngleOkay(float) const'
../game/libgame.a(FollowMovementGenerator.cpp.o): In function `FollowMovementGenerator::Update(Unit*, unsigned int)':
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:100: undefined reference to `ChaseAngle::IsAngleOkay(float) const'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:104: undefined reference to `ChaseAngle::UpperBound() const'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:105: undefined reference to `ChaseAngle::LowerBound() const'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:107: undefined reference to `ChaseAngle::UpperBound() const'
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:109: undefined reference to `ChaseAngle::LowerBound() const'
../game/libgame.a(FollowMovementGenerator.cpp.o): In function `PositionOkay(Unit*, Unit*, float, boost::optional<ChaseAngle>)':
/root/games/TrinityCore_code/TrinityCore/src/server/game/Movement/MovementGenerators/FollowMovementGenerator.cpp:38: undefined reference to `ChaseAngle::IsAngleOkay(float) const'
../scripts/libscripts.a(boss_mr_smite.cpp.o): In function `void boost::optional_detail::optional_base<ChaseRange>::construct<float&>(float&, void const*)':
/usr/include/boost/optional/optional.hpp:465: undefined reference to `ChaseRange::ChaseRange(float)'
../scripts/libscripts.a(boss_mr_smite.cpp.o): In function `void boost::optional_detail::optional_base<ChaseAngle>::construct<float&>(float&, void const*)':
/usr/include/boost/optional/optional.hpp:465: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(boss_midnight.cpp.o): In function `boss_attumen::boss_attumenAI::SpellHit(Unit*, SpellInfo const*)':
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp:241: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp:247: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(boss_midnight.cpp.o): In function `operator()':
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp:263: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp:264: undefined reference to `ChaseAngle::ChaseAngle(float, float)'
../scripts/libscripts.a(boss_vexallus.cpp.o):/root/games/TrinityCore_code/TrinityCore/src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp:98: more undefined references to `ChaseAngle::ChaseAngle(float, float)' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:211: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1514: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Expected behaviour:**

Linking worldserver succeeds.

**Steps to reproduce the problem:**

1. execute `make` command in build directory.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Here is some information might be useful:
1. output of `clang -v`:
> clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

2. output of `git log`:
> commit 5a22467912ef038c4a8df20547cab4b1b747ad09
Author: Keader <keader.android@gmail.com>
Date:   Wed Apr 25 18:21:16 2018 -0300

    Core/Handlers: Fixed a Equipament Manager typo

**Operating system:** 
Debian 9.3 x86_64

**Comment by Maxwelllmj** [comment]
I compiled this one minute ago.  No error.  Do you CMAKE after pull new code?

**Comment by yisunfc** [comment]
@Maxwelllmj  Thanks a lot! I forgot to CMAKE again, sorry for my mistake.

**Comment by Maxwelllmj** [comment]
你娃上海的，害我打英语 怪难受的
