### ISSUE TITLE
mmaps_generator unable to load LiquidType.db2

### ISSUE THREAD

**Issue by rapsys** [TrinityCore/TrinityCore#21898]
**Description:**

Linux build is missing a filter on dbc subdirectories to exclude "." and ".." directories.

**Current behaviour:**

Currently if you start mmaps_generator it fail with error -5 Unable to load [dbc/./]LiquidType.db2

**Expected behaviour:**

It should generate the required mmaps

**Steps to reproduce the problem:**

1. $ mmpas_generator
Unable to load LiquidType.db2

**Branch(es):**

master

**TC rev. hash/commit:** 

8fa3d2a3852e+ 2018-05-01 19:26:22 +0300 (master branch)

**Operating system:**

Mageia release 6 (Official) for x86_64

**Fixing patch proposal:**

```diff
diff --git a/src/tools/mmaps_generator/PathCommon.h b/src/tools/mmaps_generator/PathCommon.h
index 31ac3711b4..54a3b66a95 100644
--- a/src/tools/mmaps_generator/PathCommon.h
+++ b/src/tools/mmaps_generator/PathCommon.h
@@ -26,6 +26,7 @@
 #ifndef _WIN32
     #include <cstddef>
     #include <dirent.h>
+    #include <cstring>
 #else
     #include <Windows.h>
 #endif
@@ -106,8 +107,11 @@ namespace MMAP
             errno = 0;
             if ((dp = readdir(dirp)) != NULL)
             {
-                if (matchWildcardFilter(filter.c_str(), dp->d_name))
-                    fileList.push_back(std::string(dp->d_name));
+                if (matchWildcardFilter(filter.c_str(), dp->d_name)) {
+                    if (strcmp(dp->d_name, ".") != 0 && strcmp(dp->d_name, "..") != 0) {
+                        fileList.push_back(std::string(dp->d_name));
+                    }
+                }
             }
             else
                 break;
```

**Shauren fixed it for win32, but not linux:**

```
3743d042017 src/tools/mmaps_generator/PathCommon.h (Shauren           2018-03-03 14:29:53 +0100  93)             if (strcmp(findFileInfo.cFileName, ".") != 0 && strcmp(findFileInfo.cFileName, "..") != 0)
259a29c0935 src/tools/mmaps_generator/PathCommon.h (Shauren           2013-01-22 18:40:32 +0100  94)                 fileList.push_back(std::string(findFileInfo.cFileName));
```

**Comment by illfated** [comment]
Tips and tricks regarding Syntax highlighting in GitHub Flavored Markdown:
- https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
- https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
- https://highlightjs.org/static/demo/

TrinityCore pages often use
```
```cpp or ```diff or ```sql
```
for syntax highlighting in code blocks.
(if the back ticks ``` are difficult to type on your keyboard, you can also use tilde ~~~ )
