### ISSUE TITLE
[creature] cast spells

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#21895]
instance
http://www.wowhead.com/the-forge-of-souls
boss
http://www.wowhead.com/npc=36497

cast spell use by boss king = can players  ruins spells of boss! cd

spell
http://www.wowhead.com/spell=68921/soulstorm

This problem did not exist!
tc: https://github.com/TrinityCore/TrinityCore/commit/26a444719b6bdc06a00f7737a70a6fb4bd6443db

os: windows sv 2016

**Comment by Faq** [comment]
Missing lot of details, what instance, what boss, what spells.
Why deleted issue template? You need to fill all asked info@

**Comment by irgc** [comment]
@Faq 
my post updated
and
Players can ruin spells using their own spells!

**Comment by Foereaper** [comment]
What he means is that some bosses can be interrupted and some boss spells even experience push back effects from being damaged :) The original post is quite lackluster though lol.

**Comment by illfated** [comment]
How about copying back some of the deleted lines from https://github.com/TrinityCore/TrinityCore/issues/new
and fill in the missing info so we can read the issue better. Also, I usually get names too in my wowhead links:
- http://www.wowhead.com/npc=36497/bronjahm
- http://www.wowhead.com/npc=36502/devourer-of-souls
- http://www.wowhead.com/npc=36494/forgemaster-garfrost
- http://www.wowhead.com/npc=36476/ick
- http://www.wowhead.com/npc=36477/krick
- http://www.wowhead.com/npc=36658/scourgelord-tyrannus

Naming (and linking) the affected spells would be an improvement too.

**Comment by Killyana** [comment]
This npcs have interruptible spells: http://www.wowhead.com/npc=36502/devourer-of-souls#comments:id=939170:reply=142602
Unless you provide example of spells, the issue will be closed.

**Comment by illfated** [comment]
https://wow.gamepedia.com/Devourer_of_Souls#Strategy

**Comment by irgc** [comment]
if u want closed my report np ! but  coming soon will to again reports

please if u can check fulled topic.

**Comment by irgc** [comment]
example
http://www.wowhead.com/the-forge-of-souls
boss
http://www.wowhead.com/npc=36497
spell
http://www.wowhead.com/spell=68921/soulstorm

**Comment by offl** [comment]
Bronjahm's mechanic_immune_masks contains MECHANIC_INTERRUPT. It means you can't interrupt his spells. I can't interrupt his spells in 8a9cc0f65d8f
