### ISSUE TITLE
Crash (freeze, infinite loop) related to PhaseShift

### ISSUE THREAD

**Issue by wwolegion** [TrinityCore/TrinityCore#21902]
**Description:**

A freeze (detected by anti freeze thread) is found, possibly inside function `intersectRay` from `gameobjectmodel.cpp`.

**Steps to reproduce the problem:**

Don't really know how to reproduce, seems to be randomly happening

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 2d666810d2ce 2018-04-28 16:36:42 +0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows Server 2012 X64 R2

[2d666810d2ce_worldserver.exe_.2-5_22-18-56.txt](https://github.com/TrinityCore/TrinityCore/files/1969001/2d666810d2ce_worldserver.exe_.2-5_22-18-56.txt)

**Comment by funjoker** [comment]
Compile in Debug and reproduce again

**Comment by Shauren** [comment]
Values in the log are too optimized to be of any use, also `Ashamane::VariablesSafe Variables = 0x9807F4E928`

**Comment by wwolegion** [comment]
It is release with debug symbols.

**Comment by jackpoz** [comment]
Some useful infos:
>float m_positionX = 1798.091797
float m_positionY = -47.318489
float m_positionZ = 292.497406
float m_orientation = 3.039274
unsigned int m_mapId = 0x498

>std::string m_name = "Defiled Spirit"

>Local G3D::Vector3 start
	float x = 1798.091797
	float y = -47.318489
	float z = 0.000000

>Local G3D::Vector3 dest
	float x = 1776.635132
	float y = 0.486524
	float z = -109856.250000

**Comment by jackpoz** [comment]
But as Shauren pointed out, do you have any custom change applied to the sources ? Please include a link to a public fork with all the changes included

**Comment by Shauren** [comment]
@jackpoz here it is https://github.com/AshamaneProject/AshamaneCore

**Comment by Shauren** [comment]
> float z = -109856.250000

At this point I'm not sure this variable was optimized out and contains garbage or it really got invalid coord passed from somewhere

**Comment by Faq** [comment]
@jackpoz there is ready dashboard to take?

**Comment by Animalthug** [comment]
Getting same access violation

**Comment by jackpoz** [comment]
@Faq https://trinitycore.atlassian.net/wiki/spaces/tc/pages/19955721/Monitoring+a+TrinityCore+server

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
no answer, closing.
