### ISSUE TITLE
Don Carlos

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21918]
**Description:**
https://www.wowhead.com/npc=28132/don-carlos

**Current behaviour:**
Don Carlos does not dismount when engaged in combat.

**Expected behaviour:**
Don Carlos should dismount when engaged in combat. He should also prioritize ranged combat over melee combat, unless you are within melee range.

**TC rev. hash/commit:** 
TrinityCore rev. 68989081b1c0 2018-05-08 02:10:08 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.64.0
Using MySQL version: 5.5.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Comment by illfated** [comment]
Several NPCs with waypoint movement seem to have this issue.
Especially those where you need to kill the rider to steal the horse.
For example: Scarlet Onslaught Warhorse
(http://www.wowhead.com/npc=27213/onslaught-warhorse)
The horse keeps walking its waypoints after becoming friendly.

**Comment by jerbookins** [comment]
This is what happens to me.
https://streamable.com/jr0ni

**Comment by offl** [comment]
He shouldn't https://www.youtube.com/watch?v=5V_K1j76GqE
Currently all NPCs dismount when engaged, except NPCs with CREATURE_TYPEFLAGS_MOUNTED_COMBAT

**Comment by jerbookins** [comment]
That video looks like private server footage. Why is Don Carlos and Guerrero running back and forth like that so quickly?
