### ISSUE TITLE
SPELL_EFFECT_171 not implemented

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21917]
**Description:**
SPELL_EFFECT_171 should work as summon personal gameobject. Used for example in quest [Bidden to Greatness](http://www.wowhead.com/quest=29792/bidden-to-greatness).

Video:
https://www.youtube.com/watch?v=j6bWCpwtdfs
First summon is at 0:32 with spell [115426](http://www.wowhead.com/spell=115426/summon-mandori-door)
Second summon is at 0:55 with spell [115435](http://www.wowhead.com/spell=115435/summon-pei-wu-door)
(SPELL_EFFECT_REMOVE_AURA in those two spells removes visibility of first doors that are permanent and are always closed)

**Current behaviour:**
not implemented, nothing spawns

**Expected behaviour:**
should be implemented as summon personal gameobject

**Steps to reproduce the problem:**
1. login with two players and stand next to each other
2. cast 115426
3. only caster should see the door

**Branch(es):** master

**TC rev. hash/commit:** 921235b3e9af0d72c49035016065552a7b34d9ca

**Operating system:** any

**Comment by msoky** [comment]
somebody have solution for this problem?

**Comment by msoky** [comment]
@funjoker @Shauren guys, could you please look at this? thx
and  TARGET_UNK_123 not implemented too

**Comment by msoky** [comment]
TARGET_UNK_123 should be TARGET_UNIT_AREA_TAP_LIST ?
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/9fe40967b179a238e111132e7d4e757a260fa4a2

**Comment by Shauren** [comment]
You know that commit is based on something I already pushed to master branch right?
