### ISSUE TITLE
Could not populate the World database

### ISSUE THREAD

**Issue by neo0nymous** [TrinityCore/TrinityCore#21915]
**Description:**

So everything works Fine ( Authserver ) but when i try to Start the Worldserver it says:                     "Could not populate the World database Download TDB_world_735.00_2018_02_19.sql"
But i cant find that file anywhere.

**Branch(es):**

master

**Operating system:**

Windows 10 Home 64Bit

Here is the Full Log:
`TrinityCore rev. b773d9997bdd 2018-05-06 00:39:13 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file D:/Users/NEO/Desktop/wowserver/Legion Server/worldserver.conf.
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.63.0
Daemon PID: 14196

Process priority class set to HIGH
Database Auth is empty, auto populating it...
>> Applying '../TrinityCore/sql/base/auth_database.sql'...
Warning: Using a password on the command line interface can be insecure.

>> Done!
Database Character is empty, auto populating it...
>> Applying '../TrinityCore/sql/base/characters_database.sql'...
Warning: Using a password on the command line interface can be insecure.

>> Done!
Database World is empty, auto populating it...
>> File "TDB_world_735.00_2018_02_19.sql" is missing, download it from "https://github.com/TrinityCore/TrinityCore/releases" uncompress it and place the file "TDB_world_735.00_2018_02_19.sql" in the directory "D:/Users/NEO/Desktop/wowserver/Legion Server".
Could not populate the World database, see log for details.
`

**Comment by Aokromes** [comment]
File "TDB_world_735.00_2018_02_19.sql" is missing, download it from "https://github.com/TrinityCore/TrinityCore/releases" uncompress it and place the file

**Comment by neo0nymous** [comment]
Oh god guess im blind sry.
