### ISSUE TITLE
Core/Spell: AOE with immune to pc and immune to npc flag

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21929]
**Description:** Npcs with the unit flag immune to pc could be hit by players aoe, and they can hit players with aoe.

It's also the case for 2 npcs with immune to npc flag

**Steps to reproduce the problem:**

Immune to PC case

1. Connect an alliance character
2. .npc add temp 31563
3. .cast 5740
4. Notice the npc will take damage
5. .cast self 5740
6. Notice your char will take damage

Immune to NPC case
1. .npc add temp 15008 (to time one inface of the other)
2. .mod fac 1981 the first npc
3. .mod fac 12 the second npc
4. .cast self 5740 or 26029 and notice the npc get hitten by the aoe

**Branch(es):** 3.3.5
TrinityCore rev. 5f6af8c6cbe7 2018-05-05 19:17:52 +0200 (3.3.5 branch) (Win32, Debug, Static)
Using SSL version: OpenSSL 1.0.1e 11 Feb 2013 (library: OpenSSL 1.0.1e 11 Feb 2013)
Using Boost version: 1.59.0
Using MySQL version: 5.5.39
Using CMake version: 3.10.1
Compiled on: Windows 
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2229000480 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR 
Using World DB: TDB 335.64

**Comment by Devgasm** [comment]
Noticeable in Dalaran, the "unfriendly" mobs walking around can be hit by AoE's like Consecration and Divine Storm

**Comment by Langerz82** [comment]
Test Patch.

```diff
diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index bf37a3d390..d18be1848e 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -2445,6 +2445,11 @@ SpellMissInfo WorldObject::MagicSpellHitResult(Unit* victim, SpellInfo const* sp
     if (!victim->IsAlive() && victim->GetTypeId() != TYPEID_PLAYER)
         return SPELL_MISS_NONE;
 
+    if (GetTypeId() == TYPEID_PLAYER && victim->IsImmuneToPC())
+        return SPELL_MISS_MISS;
+    if (GetTypeId() == TYPEID_UNIT && victim->IsImmuneToNPC())
+        return SPELL_MISS_MISS;
+
     SpellSchoolMask schoolMask = spellInfo->GetSchoolMask();
     // PvP - PvE spell misschances per leveldif > 2
     int32 lchance = victim->GetTypeId() == TYPEID_PLAYER ? 7 : 11;
```

**Comment by Treeston** [comment]
In the future, the simpler the repro is, the better. It's always best to use pre-existing npcs instead of relying on `.mod` commands, to avoid having to check for bugs in those commands.
