### ISSUE TITLE
Shade of Akama not targetable

### ISSUE THREAD

**Issue by midiman369** [TrinityCore/TrinityCore#21926]
**Description:**

Shade of Akama never becomes targetable and so you are unable to progress through the instance.

**Current behaviour:**

In Black Temple, The Shade immediately runs toward Akama and starts fighting him as soon as the fight is started by talking to Akama.  Even after you kill the channelers the shade never becomes targetable/attackable.

**Expected behaviour:**

The Shade of Akama should not start attacking Akama until the Chanellers are killed.  If Shade of Akama is attacking..  he should be targetable by players for attack.

**Steps to reproduce the problem:**

1. reach Shade of Akama (http://www.wowhead.com/npc=22841/shade-of-akama) 
2. Speak with Akama to start encounter.
3. Kill all chanellers.
4. <Shade is not targetable>

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

server debug
TrinityCore rev. 081eab3cf5a5 2018-05-02 19:09:37 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.40
Using CMake version: 3.11.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10

**Comment by shenhuyong** [comment]
2a84562dc85516f432bb1e5de9add23c28b26ce4 cause this bug, it seems miss AI()->MovementInform in ChaseMovementGenerator.cpp and FollowMovementGenerator.cpp, so Shade of Akama can not remove UNIT_FLAG_NOT_SELECTABLE flag from MovementInform() in boss_shade_of_akama.cpp.

**Comment by Keader** [comment]
@Treeston

**Comment by Treeston** [comment]
re-test after 56a056a

**Comment by shenhuyong** [comment]
Tested, it works fine now.
