### ISSUE TITLE
Thrall - Durnholde Keep

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21921]
**Description:**
https://www.wowhead.com/npc=17876/thrall
https://www.wowhead.com/quest=10284/escape-from-durnholde
https://wotlk.evowow.com/?object=184393
https://www.youtube.com/watch?v=Mw8mIWn5W0E

**Current behaviour:**
The object "Prison Door" highlights with mouse-over and is usable by players. Right clicking the gate opens the door.

Thrall always has a dialogue option that just says "[PH] Start Walking".

Thrall aggros creatures through walls, and even paths through the castle walls until he gets outside.

**Expected behaviour:**
The opening of the door should only occur when clicking the dialogue text to begin the escort quest for Escape from Durnholde.

Thrall should only have a dialogue option that says "We are ready to get you out of here, Thrall. Let's go!" and it should only appear AFTER you have accepted the quest Escape from Durnholde. At which point, the Prison Door should open and the escort quest should begin.

**TC rev. hash/commit:** 
TrinityCore rev. 68989081b1c0 2018-05-08 02:10:08 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.64.0
Using MySQL version: 5.5.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Comment by illfated** [comment]
TBC/WotLK version: http://www.wowhead.com/quest=10284/escape-from-durnholde
Cataclysm+ version: http://www.wowhead.com/quest=29599/escape-from-durnholde

**Comment by Killyana** [comment]
caused by https://github.com/TrinityCore/TrinityCore/issues/23008
