### ISSUE TITLE
Guerrero

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#21925]
**Description:**
https://www.wowhead.com/npc=28163/guerrero
https://streamable.com/je62f

**Current behaviour:**
Don Carlos' wolf Guerrero is glitchy. He follows Don Carlos but walks strangely. If you engage him in combat and then disengage, either through `.gm` or `.combat` or even death, he doesn't disengage and return to follow Don Carlos. He will just stand there acting like he's in combat.

![wowscrnshot_051018_051126](https://user-images.githubusercontent.com/16745918/39867133-b92fb2f2-5410-11e8-9f49-1b36a8391d2d.jpg)

**Expected behaviour:**
Guerrero should walk at the same pace as Don Carlos, slightly to the side rear of his horse. When disengaged from combat, he should return to Don Carlos' side.

**TC rev. hash/commit:** 
TrinityCore rev. 68989081b1c0 2018-05-08 02:10:08 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.64.0
Using MySQL version: 5.5.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.15063
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Comment by Killyana** [comment]
Related to :
https://github.com/TrinityCore/TrinityCore/issues/12596
https://github.com/TrinityCore/TrinityCore/issues/12817
