### ISSUE TITLE
vmap4assembler.exe crash

### ISSUE THREAD

**Issue by Lopfest** [TrinityCore/TrinityCore#21920]
**Description:**
Cant extract vmaps due to  vmap4assembler.exe crash.
vmap4extractor.exe is successfull, Buildings folder has size 2.75GB.
Using correct wow version 7.3.5 (26365)
Processor type (in case its threading issue or something): Intel® Core™ i7-5820K

**Current behaviour:**
vmap4assembler.exe crashes when started. No crashlog is generated. If it helps, here is problem description (in Slovak language):
```
Popis problému:
  Názov problémovej udalosti:		APPCRASH
  Názov aplikácie:			vmap4assembler.exe
  Verzia aplikácie:			0.0.0.0
  Časová pečiatka aplikácie:		5af15844
  Názov chybného modulu:		StackHash_f734
  Verzia chybného modulu:		6.1.7601.24094
  Časová pečiatka chybného modulu:	5abee643
  Kód výnimky:				c0000374
  Odsadenie výnimky:			00000000000bf6b2
  Verzia OS:				6.1.7601.2.1.0.256.1
  Identifikácia miestneho nastavenia:	1051
  Ďalšie informácie 1:			f734
  Ďalšie informácie 2:			f73474a5e3bd8df731ec6818dd81779d
  Ďalšie informácie 3:			9745
  Ďalšie informácie 4:			97459b55c0700c4c99466601358feb7b
```

**Expected behaviour:**
no crash

**Steps to reproduce the problem:**
1. extract vmaps

**Branch(es):** master

**TC rev. hash/commit:** 921235b3e9af0d72c49035016065552a7b34d9ca

**Operating system:** Win 7 Ultimate x64

**Comment by Shauren** [comment]
Useless, no crash log

**Comment by Lopfest** [comment]
update. after reinstalling vcredist packages, i got other error (still without crashlog)
```
using Buildings as source directory and writing output to vmaps
Read coordinate mapping...
Error reading ModelSpawn, file name too long!

Converting Model Files
HEAP CORRUPTION DETECTED: after Normal block (#163) at 0x0000000000494BC0.
CRT detected that the application wrote to memory after end of heap buffer.
Ok, all done
```
what could be wrong?

**Comment by Shauren** [comment]
Are you using incompatible versions of extractor and assembler? (old extractor + new assembler or new extractor + old assembler)

**Comment by Lopfest** [comment]
no i builded and copied them to wow folder all together. they all have today's last modified date

**Comment by Aokromes** [comment]
try yo move wow directory to c:\ d:\ and run again.

**Comment by HannibalRoG** [comment]
I have the same issue here using 

> Buildings as source directory and writing output to vmaps
> Read coordinate mapping...
> Error reading ModelSpawn, file name too long!
> 
> Converting Model Files
> 
> C:\Program Files\Client World of Warcraft Legion>

**Comment by Lopfest** [comment]
command prompt or extractor.bat

**Comment by leviathonbeast** [comment]
more information would be helpful :)

**Comment by Lopfest** [comment]
idk what else to tell. everything is here already.
running `start /b vmap4assembler.exe Buildings vmaps` either crashes (vmap4assembler.exe stopped working), or outputs with [this error](https://github.com/TrinityCore/TrinityCore/issues/21920#issuecomment-387379254)

**Comment by leviathonbeast** [comment]
why "start /b"?

**Comment by Lopfest** [comment]
that absolutely doesn't matter. even without /b it crashes. /b just doesn't open new cmd window

**Comment by leviathonbeast** [comment]
its got to be your windows os that is the problem maybe not updated ?

im using the latest Windows 10 pro.

**Comment by Lopfest** [comment]
omg I found the issue. copying newly built common.dll from build directory to wow directory fixed it!
and i hate windows 10

**Comment by Shauren** [comment]
if you build with dynamic linking you must always update all dlls (unfun fact, vmap assembler is entirely implemented in common, its main function only deals with cmdline args)

**Comment by shamage** [comment]
@Lopfest  :  This assembly is seamless for compilation

TrinityCore rev. 921235b3e9af 2018-05-07 17:45:09 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows Pro 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Comment by HannibalRoG** [comment]
@Lopfest confirmed worked for me too.
