### ISSUE TITLE
Stormwind Royal Guard in Elwynn Forest

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#21931]
**Description:**

Guardian formation is not correct + walks wrong route.

**Current behaviour:**

The guards pass through a completely different route, through objects but also in the air.

**Expected behaviour:**

They should walk according to the exact formation (group) and should walk along the marked path.

**Steps to reproduce the problem:**

1. [Stormwind Royal Guard ( wowhead )](http://www.wowhead.com/npc=42218/stormwind-royal-guard) 
2. walk to the border line between stormwind and evelin forest (before the stormwind entrance) here I start my journey Stormwind Royal Guard
3. look like guards moving off the tracks and completely pushed to themselves 
4. in the case of an enemy approach, they must immediately attack - destroy the enemy and then re-group and continue on the road

**Branch(es):**   master

**TC rev. hash/commit:** 

TrinityCore rev. 8391119aa6e5 2018-05-12 19:51:42 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
mmaps directory located in ./mmaps. Total size: 6432765196 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00

**Comment by shamage** [comment]
![formation 2](https://user-images.githubusercontent.com/7515044/39965884-119a888e-56a2-11e8-82fd-283c0a665f39.png)
![formation](https://user-images.githubusercontent.com/7515044/39965885-11b6ef1a-56a2-11e8-8693-d8b4ff5a2b5b.png)

can anyone help me with this?

**Comment by ArcaneFox** [comment]
Maybe it's related to https://github.com/TrinityCore/TrinityCore/commit/05fb27dae4e8af859e01e5b9e52b082cba217657

**Comment by MrSmite** [comment]
Maybe they saw some [Earthroot](http://www.wowhead.com/item=2449/earthroot) and wanted to level their [Herbalism](http://www.wowhead.com/herbalism) :stuck_out_tongue: :

**Comment by shamage** [comment]
@ArcaneFox  - it's possible, but I'm not well enough to handle it myself . 
I need to be more experienced than I am

**Comment by Ovahlord** [comment]
Looks to me that the formation leader is way ahead of the rest of the formation so the other creatures are just trying to keep up.

**Comment by Killyana** [comment]
The issue is core side, use ".wp show on" on the leader an you will see it skips some waypoints, also this issue doesn't  happen on 4.3.4 with the exact same sql:  https://github.com/TrinityCore/TrinityCore/commit/bc974cd2f78f7cd8eda340d89fac557920b0fd76

**Comment by shamage** [comment]
I looked at it and found the information. For WP is PatchID: 2807910 - is it right?

**Comment by shamage** [comment]
After implementation of WP points, soldiers are already holding their way and attacking enemies. 
1.) However, there is a variety of situations when the soldiers do not return to their original position (to be on horseback) but remain without a horse and go on foot any
2.) the leader who leads the group will inevitably leak away from the group right from the start

**Comment by shamage** [comment]
![first start server](https://user-images.githubusercontent.com/7515044/40133552-70d09dc0-5940-11e8-9fa5-95ee9086bb77.png)
here is seen as the leader runs away from the group - the group is still just forming

**Comment by shamage** [comment]
![second - leader runs away](https://user-images.githubusercontent.com/7515044/40133727-d9ef3e10-5940-11e8-9a98-352c619ae49d.png)


Here is how the group formed, but the leader continues to run ahead

**Comment by shamage** [comment]
![formation](https://user-images.githubusercontent.com/7515044/40134068-b1c961b2-5941-11e8-8363-7f7dd466b318.png)


here it is seen that after the attack the group is formed (without a leader) but no longer horses go on foot

**Comment by welder1976** [comment]
this smart script

**Comment by welder1976** [comment]
DELETE FROM `smart_scripts` WHERE `entryorguid`=42218 AND `source_type`=0 AND `id`>0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(42218,0,1,0,4,0,100,0,0,0,0,0,28,78855,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind Royal Guard - On aggro - Remove aura"),
(42218,0,2,0,34,0,100,0,2,58,0,0,41,0,0,0,0,0,0,11,42218,30,0,0,0,0,0,"Stormwind Royal Guard - On movement informer - despawn all guars");

**Comment by welder1976** [comment]
also a similar implementation of this circulation is realized in Northrend in the fortress of the Alliance Borean tundra

**Comment by illfated** [comment]
Please put **```sql** (GitHub MarkDown code block) on a single empty line on top of your SQL code, for easier reading.

**Comment by shamage** [comment]
```sql
DELETE FROM smart_scripts WHERE entryorguid=42218 AND source_type=0 AND id>0;
INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(42218,0,1,0,4,0,100,0,0,0,0,0,28,78855,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormwind Royal Guard - On aggro - Remove aura"),
(42218,0,2,0,34,0,100,0,2,58,0,0,41,0,0,0,0,0,0,11,42218,30,0,0,0,0,0,"Stormwind Royal Guard - On movement informer - despawn all guars");
```

@welder1976  : 


I tried this script from you, but the suggestion you made did not solve the current issue. I feel as though a script has been incorrectly implemented and the behavior of the group leader with waipoint has incorrect values. But this is purely my consideration.

**Comment by shamage** [comment]
Unfortunately, I had a lot of work and I could not deal with this issue ...

**Comment by shamage** [comment]
It works seamlessly on this version rev. 555b2d40ecc2

**Comment by shamage** [comment]
@Killyana 
 Has this been fixed by this update?  [link](https://github.com/TrinityCore/TrinityCore/commit/8391119aa6e56fa29416135e08c728a308db04a9)

**Comment by CraftedRO** [comment]
I coud be wrong but I think Killyana is no longer active on github at least for two years like.

**Comment by shamage** [comment]
pity, so I probably won't know the answer anymore
