### ISSUE TITLE
[master] Database - Fix a few Scarlet Monastery issues

### ISSUE THREAD

**Issue by Krudor** [TrinityCore/TrinityCore#21930]
**Description:**

Removes several duplicate Armory and Cathedral doors.
Update Armory, Cathedral doors and the levers faction so that they cannot be interacted with.
Add missing entrance and exit portals.
Redirect existing entrance triggers from the old maps to the Mists of Pandaria versions.
Configure exit triggers for the Mists of Pandaria versions of Scarlet Monastery and Scarlet Halls.
Remove entrance triggers for the old instances, Cathedral and Armory.

**Current behaviour:**

There are duplicate door spawns in Scarlet Monastery, outside the instances.
There are no instance portals.
Upon entering an instance, you are teleported to the old version instead of the updated ones.
Players are able to open Cathedral and Armory doors.
Cathedral and Armory instances are still able to be entered.

**Expected behaviour:**

There are no duplicate door spawns, no missing instance portals, the Cathedral and Armory doors cannot be opened, and players are teleported to the Mists of Pandaria versions of the Scarlet Monastery instances.

**Suggested fix:**

https://gist.github.com/Krudor/899daadf4aaf9622656dcc547e80f65a

**Branch(es):** master

**TC rev. hash/commit:** 136269a5851a6755f644295a0171e4bc6c2bef17

**Comment by Killyana** [comment]
Just instance template was missing, added in the sql.

**Comment by Krudor** [comment]
Cheers
