### ISSUE TITLE
[BUG] Quest

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21935]
quest item:  [Battered Hilt] http://www.wowhead.com/item=50379
i  will tested for this , all is worked! but just one!

quest bug  [Thalorien Dawnseeker]

horde
http://www.wowhead.com/quest=24563/thalorien-dawnseeker

alliance
http://www.wowhead.com/quest=24535/thalorien-dawnseeker

information! unknow

tc: 26a4447
os: windows 2016 sv

**Comment by Aokromes** [comment]
#12444

**Comment by irgc** [comment]
@Aokromes 

i set on world database table quest_template  
"QuestTyp" 2 to 0 
for automatic complete  but  But it will not to auto com!

what do I do :disappointed:

**Comment by funjoker** [comment]
If you want to make it autocomplete:

Quest needs also Flags =| 65536 (atleast afaik)
