### ISSUE TITLE
Instance: Halls of Reflection

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21941]
http://www.wowhead.com/spell=69780/remorseless-winter is freezing the Lich King movements instead of slowing it (it doesn't happen always, probably caused also by the channeling spell used to summon the npcs)

At the end the ship doesn't use bombs for the last event.

TrinityCore rev. 5f6af8c6cbe7 2018-05-05 19:17:52 +0200 (3.3.5 branch) (Win32, Debug, Static)
Using SSL version: OpenSSL 1.0.1e 11 Feb 2013 (library: OpenSSL 1.0.1e 11 Feb 2013)
Using Boost version: 1.59.0
Using MySQL version: 5.5.39
Using CMake version: 3.10.1
Compiled on: Windows 
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2229000480 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR 
Using World DB: TDB 335.64

**Comment by irgc** [comment]
If this problem does not matter!

Close the instance?

**Comment by Ovahlord** [comment]
Do not expect your reports to get fixed immediately. TC is a free time community project. Which means that you can also contribute by helping to fix things.

**Comment by shenhuyong** [comment]
2a84562dc85516f432bb1e5de9add23c28b26ce4 cause this bug, it  bearks lich king do ChaseMove().

**Comment by Keader** [comment]
@Treeston

**Comment by Treeston** [comment]
re-test after 56a056a

**Comment by shenhuyong** [comment]
I tested, still not fixed, the problem is not about MovementInform(), MovementInform() in npc_the_lich_king_escape_hor() just be called from MovePoint() in npc_jaina_or_sylvanas_escape_hor(), the problem is Lich King stop his chase moving after he casted some summon spell (69818, 69836, 69835), I don't know why.

**Comment by shenhuyong** [comment]
I added a MoveChase() in UpdateAI() to let Lich King get on with his chase moving faster, then Lich King can move immediately after he casted summon spells.

**Comment by irgc** [comment]
confirm

tested not fixed.

after https://github.com/TrinityCore/TrinityCore/commit/56a056a8a5f5aa61c68a2b827d8d64ff2fc9abdd

**Comment by irgc** [comment]
commented 11 days ago
-
ok i will to closed instance. (HOR)

**Comment by Keader** [comment]
You're free to do everything you want in your fork :)

**Comment by pedroevil51** [comment]
#21290  Related to this maybe?

**Comment by pedroevil51** [comment]
Also, can you share your "hack fix" ? would help a lot

**Comment by Killyana** [comment]
Cannot reproduce on rev. 3d3b7f438c66
