### ISSUE TITLE
Zul'aman 4 chests cannot be opened

### ISSUE THREAD

**Issue by Maxwelllmj** [TrinityCore/TrinityCore#21949]
**Description:**

Zul'aman 4 chests can't open.

**Current behaviour:**

After defeating boss in Zul'aman, I can't open the chests.

**Expected behaviour:**

After defeating boss in Zul'aman, open the chests to get loot

**Steps to reproduce the problem:**

1. Step 1 
get into Zul'aman, slay the first boss.
2. Step 2
chat with hostage, select gossip option.
3. Step 3
when the chest appear,  it was locked or unselectable. 

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
7e0c0e6b79f8

**Operating system:** win10

**Comment by Maxwelllmj** [comment]
I tried to fix it myself, but I failed.  just cann't find the problem.

**Comment by xlla** [comment]
same issue here, how open the chest, it is locked
