### ISSUE TITLE
DB/Quest: Remove Deprecated Quests

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#21940]
**Description:**

Quest "The Tome of Nobility" (ID: 4485) and quest "The Tome of Nobility" (ID: 4486) used to be the quests where paladins could obtain their mount. They were removed from the game since The Burning Crusade expansion. Paladins are now able to train their mount from any trainer.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry` IN (4485,4486);
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
(1,4485,0,"","","Deprecated quest"),
(1,4486,0,"","","Deprecated quest");

**Comment by illfated** [comment]
Maybe add the name of the quest at the end of the comment line?
(I know, not strictly required, but nice to have when there is text there already.)
`"Deprecated quest: The Tome of Nobility"`
