### ISSUE TITLE
[BUG] group!

### ISSUE THREAD

**Issue by irgc** [TrinityCore/TrinityCore#21942]
if player disconnect inside instance , he remove of raid party group!

tc: 26a4447
os: windows 2016 sv

**Comment by Gooyeth** [comment]
Always the issue template... 🔫

**Comment by Killyana** [comment]
If you disconnect normally you will leave the group, if you alt F4, client crash or disconnect (connection issue) you will remain in the group as disconnected)

**Comment by Gooyeth** [comment]
One important point: is he in combat while disconnecting?.

If you are in a raid you must not leave the group, never.

**Comment by Aokromes** [comment]
not true, i have seen raid group to be dismantled on ptr on a server crash.
