### ISSUE TITLE
Core/Transport: Clientside issue with dissapearing npcs

### ISSUE THREAD

**Issue by Maiievs** [TrinityCore/TrinityCore#21946]
**Description:**
If you logout on a transport, when you log back, there will be no npcs on the transport.

**Current behaviour:**
No npc on transport after log back.

**Expected behaviour:**
There should be npcs there.

**Steps to reproduce the problem:**
1. .go xyz 100.635406 -3691.131592 2.032307 571
2. Enter the boat when it gets there.
3. Logout inside it.
4. Log back.
5. Note boat is empty.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  7e0c0e6b79f8 
```
TrinityCore rev. 7e0c0e6b79f8 2018-05-16 01:32:24 +0200 (3.3.5 branch) (Win64, Release, Dynamic)
Using SSL version: OpenSSL 1.0.2m  2 Nov 2017 (library: OpenSSL 1.0.2j  26 Sep 2016)
Using Boost version: 1.65.1
Using MySQL version: 5.7.20
Using CMake version: 3.9.5
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/Release/maps. Total size: 252191207 bytes
vmaps directory located in C:/Build/bin/Release/vmaps. Total size: 590027046 bytes
mmaps directory located in C:/Build/bin/Release/mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
```

**Comment by Maiievs** [comment]
Not really the same, other issue is more about a "visibility distance desync", this one goes further, but ok

**Comment by Killyana** [comment]
It looks to be related to transport spawns (and players) not loaded to the client if the character login on the transport, you can still /tar npc or player.

If the npcs moves they will turn visible and same for players.

**Comment by Killyana** [comment]
The issue changed since, now the npcs are visible but don't move with the ship, they will end up like this, when the ship moves:
![image](https://user-images.githubusercontent.com/6587064/73073736-44f47f00-3eb8-11ea-8406-f51a856b053c.png)

**Comment by LKArthas** [comment]
Transports aren't treated as Map?? a common issue that i saw before is that NPC's doesn't have updated the map position on the gunships, there for they fall down, check if this serves you for something, for Ashamane Fork works good

-- Spawn Skybreaker/Orgrimm Hammer Gunship creatures/Objects
DELETE from creature where map=623;
DELETE from creature_template_addon where entry IN (select id FROM creature WHERE map=623);
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneID`, `areaID`, `spawnMask`, `phaseID`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`) VALUES 
(379000, 30343, 623, -1, -1, 1, 169, 0, 0, 5.24027, 0.25788, 20.8691, 3.15905, 120, 0, 0, 1, 0, 0, 0, 0),
(379001, 30640, 623, -1, -1, 1, 169, 0, 0, 35.0385, 36.0634, 25.1171, 5.28835, 120, 0, 0, 1, 0, 0, 0, 0),
(379002, 30640, 623, -1, -1, 1, 169, 0, 0, 6.90969, 9.52932, 20.5401, 2.30383, 120, 0, 0, 1, 0, 0, 0, 0),
(379003, 30640, 623, -1, -1, 1, 169, 0, 0, -56.3119, 12.3922, 31.0047, 3.28122, 120, 0, 0, 1, 0, 0, 0, 0),
(379004, 30640, 623, -1, -1, 1, 169, 0, 0, -27.1637, 2.98126, 20.5409, 0.122173, 120, 0, 0, 1, 0, 0, 0, 0),
(379005, 30476, 623, -1, -1, 1, 169, 0, 0, 31.4181, 0.126893, 41.6982, 0.0523599, 120, 0, 0, 1, 0, 0, 0, 0),
(379006, 30559, 623, -1, -1, 1, 169, 0, 0, 38.1615, -0.040522, 40.168, 4.2237, 120, 0, 0, 1, 0, 0, 0, 0),
(379007, 31353, 623, -1, -1, 1, 169, 0, 0, -21.72, 19.337, 9.6871, 1.64061, 120, 0, 0, 1, 0, 0, 0, 0),
(379008, 29799, 623, -1, -1, 1, 169, 0, 0, 34.5332, -38.5618, 25.0323, 3.15234, 120, 0, 0, 1, 0, 0, 0, 0),
(379009, 30344, 623, -1, -1, 1, 169, 0, 0, 43.6738, 0.121325, 25.1341, 3.10227, 120, 0, 0, 1, 0, 0, 0, 0),
(379010, 30345, 623, -1, -1, 1, 169, 0, 0, -48.0654, -0.185737, -4.98898, 3.11436, 120, 0, 0, 1, 0, 0, 0, 0),
(379011, 30346, 623, -1, -1, 1, 169, 0, 0, 25.0778, -0.047958, 9.59893, 3.13291, 120, 0, 0, 1, 0, 0, 0, 0),
(379012, 30347, 623, -1, -1, 1, 169, 0, 0, 28.6378, -7.55243, 23.2873, 0.157027, 120, 0, 0, 1, 0, 0, 0, 0),
(379013, 30350, 623, -1, -1, 1, 169, 0, 0, 16.4056, -2.2827, 20.4235, 3.11453, 120, 0, 0, 1, 0, 0, 0, 0),
(379014, 30351, 623, -1, -1, 1, 169, 0, 0, 2.42088, -23.0053, 22.5625, 0.046087, 120, 0, 0, 1, 0, 0, 0, 0),
(379015, 30351, 623, -1, -1, 1, 169, 0, 0, 1.29162, -9.37181, 20.458, 3.17295, 120, 0, 0, 1, 0, 0, 0, 0),
(379016, 30351, 623, -1, -1, 1, 169, 0, 0, 0.773476, 22.5004, 22.5503, 3.2248, 120, 0, 0, 1, 0, 0, 0, 0),
(379017, 30351, 623, -1, -1, 1, 169, 0, 0, 39.976, 44.3876, 25.0331, 3.16019, 120, 0, 0, 1, 0, 0, 0, 0),
(379018, 30351, 623, -1, -1, 1, 169, 0, 0, -36.4471, 6.81573, 20.4485, 4.73177, 120, 0, 0, 1, 0, 0, 0, 0),
(379019, 30351, 623, -1, -1, 1, 169, 0, 0, -36.1811, -6.90251, 20.4501, 1.6483, 120, 0, 0, 1, 0, 0, 0, 0),
(379020, 30351, 623, -1, -1, 1, 169, 0, 0, 1.44228, 9.63379, 20.4566, 3.15096, 120, 0, 0, 1, 0, 0, 0, 0),
(379021, 30352, 623, -1, -1, 1, 169, 0, 0, 48.8649, -8.72834, 40.0818, 3.12642, 120, 0, 0, 1, 0, 0, 0, 0),
(379022, 30352, 623, -1, -1, 1, 169, 0, 0, -17.337, 3.98796, 20.7652, 3.1541, 120, 0, 0, 1, 0, 0, 0, 0),
(379023, 30352, 623, -1, -1, 1, 169, 0, 0, 16.5684, 2.46962, 20.4252, 3.1329, 120, 0, 0, 1, 0, 0, 0, 0),
(379024, 30352, 623, -1, -1, 1, 169, 0, 0, 43.7981, 13.0009, -2.07474, 4.61776, 120, 0, 0, 1, 0, 0, 0, 0),
(379025, 30352, 623, -1, -1, 1, 169, 0, 0, -67.4841, 3.50927, 9.60209, 5.83577, 120, 0, 0, 1, 0, 0, 0, 0),
(379026, 30352, 623, -1, -1, 1, 169, 0, 0, -17.2379, -3.94242, 20.7667, 3.1541, 120, 0, 0, 1, 0, 0, 0, 0),
(379027, 30352, 623, -1, -1, 1, 169, 0, 0, -67.1723, -3.73439, 9.60211, 0.318344, 120, 0, 0, 1, 0, 0, 0, 0),
(379028, 30352, 623, -1, -1, 1, 169, 0, 0, 36.4909, 6.11523, 9.60666, 3.01117, 120, 0, 0, 1, 0, 0, 0, 0),
(379029, 30352, 623, -1, -1, 1, 169, 0, 0, -49.1048, 0.044213, 20.6694, 0.029782, 120, 0, 0, 1, 0, 0, 0, 0),
(379030, 30352, 623, -1, -1, 1, 169, 0, 0, 36.436, -6.06257, 9.60687, 3.09364, 120, 0, 0, 1, 0, 0, 0, 0),
(379031, 30352, 623, -1, -1, 1, 169, 0, 0, 48.8813, 8.78624, 40.0817, 3.1426, 120, 0, 0, 1, 0, 0, 0, 0),
(379032, 30352, 623, -1, -1, 1, 169, 0, 0, -60.5592, 0.055898, -5.27774, 0.004184, 120, 0, 0, 1, 0, 0, 0, 0),
(379033, 30380, 623, -1, -1, 1, 169, 0, 0, -6.13984, 21.6533, 9.991, 1.48436, 120, 0, 0, 1, 0, 0, 0, 0),
(379034, 30380, 623, -1, -1, 1, 169, 0, 0, 3.99105, -21.2539, 9.67311, 4.9577, 120, 0, 0, 1, 0, 0, 0, 0),
(379035, 30380, 623, -1, -1, 1, 169, 0, 0, -41.0289, 25.7685, 1.20385, 1.49696, 120, 0, 0, 1, 0, 0, 0, 0),
(379036, 30380, 623, -1, -1, 1, 169, 0, 0, -17.4619, 22.2092, 9.60018, 1.58254, 120, 0, 0, 1, 0, 0, 0, 0),
(379037, 30380, 623, -1, -1, 1, 169, 0, 0, -8.79147, 30.0334, -0.157799, 0.471494, 120, 0, 0, 1, 0, 0, 0, 0),
(379038, 30380, 623, -1, -1, 1, 169, 0, 0, -26.5726, 29.6008, -0.15773, 0.856857, 120, 0, 0, 1, 0, 0, 0, 0),
(379039, 30380, 623, -1, -1, 1, 169, 0, 0, 45.5093, 6.67955, 30.1788, 5.44543, 120, 0, 0, 1, 0, 0, 0, 0),
(379040, 30380, 623, -1, -1, 1, 169, 0, 0, 1.92073, 28.7498, 0.101361, 0.232732, 120, 0, 0, 1, 0, 0, 0, 0),
(379041, 30380, 623, -1, -1, 1, 169, 0, 0, -37.3836, 19.9617, 9.59771, 1.87549, 120, 0, 0, 1, 0, 0, 0, 0),
(379042, 30380, 623, -1, -1, 1, 169, 0, 0, -37.1975, -20.2765, 9.65711, 4.32467, 120, 0, 0, 1, 0, 0, 0, 0),
(379043, 30380, 623, -1, -1, 1, 169, 0, 0, -7.54172, -30.0747, 0.101348, 4.17752, 120, 0, 0, 1, 0, 0, 0, 0),
(379044, 30380, 623, -1, -1, 1, 169, 0, 0, -30.1731, -21.9358, 9.59686, 4.72914, 120, 0, 0, 1, 0, 0, 0, 0),
(379045, 30380, 623, -1, -1, 1, 169, 0, 0, 3.45962, -28.1289, 0.101388, 4.29376, 120, 0, 0, 1, 0, 0, 0, 0),
(379046, 30380, 623, -1, -1, 1, 169, 0, 0, -18.0212, -22.0926, 9.60068, 4.66788, 120, 0, 0, 1, 0, 0, 0, 0),
(379047, 30380, 623, -1, -1, 1, 169, 0, 0, -24.7068, -29.9771, 0.101334, 3.66623, 120, 0, 0, 1, 0, 0, 0, 0),
(379048, 30380, 623, -1, -1, 1, 169, 0, 0, 3.92454, 20.827, 9.67354, 1.30372, 120, 0, 0, 1, 0, 0, 0, 0),
(379049, 30380, 623, -1, -1, 1, 169, 0, 0, -6.33308, -21.7722, 9.99575, 4.85167, 120, 0, 0, 1, 0, 0, 0, 0),
(379050, 30380, 623, -1, -1, 1, 169, 0, 0, -39.6946, -26.8419, 0.82802, 2.93659, 120, 0, 0, 1, 0, 0, 0, 0),
(379051, 30392, 623, -1, -1, 1, 169, 0, 0, 28.7566, 7.6217, 23.2872, 6.08285, 120, 0, 0, 1, 0, 0, 0, 0),
(379052, 30394, 623, -1, -1, 1, 169, 0, 0, -14.1505, 23.0373, -5.24869, 0.027745, 120, 0, 0, 1, 0, 0, 0, 0),
(379053, 30394, 623, -1, -1, 1, 169, 0, 0, -11.7295, -24.7904, 9.58663, 1.63703, 120, 0, 0, 1, 0, 0, 0, 0),
(379054, 30394, 623, -1, -1, 1, 169, 0, 0, -11.9688, 25.5424, 9.58513, 4.66945, 120, 0, 0, 1, 0, 0, 0, 0),
(379055, 30394, 623, -1, -1, 1, 169, 0, 0, -57.9337, 6.01148, 23.5029, 1.54855, 120, 0, 0, 1, 0, 0, 0, 0),
(379056, 30394, 623, -1, -1, 1, 169, 0, 0, -14.3898, -23.2398, -5.25039, 6.16013, 120, 0, 0, 1, 0, 0, 0, 0),
(379057, 30394, 623, -1, -1, 1, 169, 0, 0, -48.1449, -3.10366, -5.21617, 3.11436, 120, 0, 0, 1, 0, 0, 0, 0),
(379058, 30833, 623, -1, -1, 1, 169, 0, 0, 6.18656, -0.008156, 20.5756, 6.28313, 120, 0, 0, 1, 0, 0, 0, 0),
(379059, 30867, 623, -1, -1, 1, 169, 0, 0, -11.0475, -22.7053, 22.5096, 4.51265, 120, 0, 0, 1, 0, 0, 0, 0),
(379060, 30867, 623, -1, -1, 1, 169, 0, 0, -32.9158, -22.1469, 22.5861, 4.59982, 120, 0, 0, 1, 0, 0, 0, 0),
(379061, 30867, 623, -1, -1, 1, 169, 0, 0, -10.0824, 23.2226, 22.5129, 1.54405, 120, 0, 0, 1, 0, 0, 0, 0),
(379062, 30867, 623, -1, -1, 1, 169, 0, 0, 36.8757, 45.226, 25.0331, 2.16509, 120, 0, 0, 1, 0, 0, 0, 0),
(379063, 30867, 623, -1, -1, 1, 169, 0, 0, -33.4747, 22.2096, 22.5895, 1.56211, 120, 0, 0, 1, 0, 0, 0, 0),
(379064, 30867, 623, -1, -1, 1, 169, 0, 0, 36.9277, -44.9241, 25.0318, 4.11052, 120, 0, 0, 1, 0, 0, 0, 0),
(379065, 31259, 623, -1, -1, 1, 169, 0, 0, 16.8761, -17.8635, 20.4597, 2.02864, 120, 0, 0, 1, 0, 0, 0, 0),
(379066, 32302, 623, -1, -1, 1, 169, 0, 0, 54.6648, -6.9431, 40.0874, 3.0302, 120, 0, 0, 1, 0, 0, 0, 0),
(379067, 32566, 623, -1, -1, 1, 169, 0, 0, 34.6465, -41.7087, 25.0325, 3.20731, 120, 0, 0, 1, 0, 0, 0, 0),
(379068, 32777, 623, -1, -1, 1, 169, 0, 0, 42.9517, 4.20903, 25.1088, 3.47298, 120, 0, 0, 1, 0, 0, 0, 0),
(379069, 30651, 623, -1, -1, 1, 169, 0, 0, -17.8134, 32.0788, 12.3449, 1.55334, 120, 0, 0, 1, 0, 0, 0, 0),
(379070, 30651, 623, -1, -1, 1, 169, 0, 0, 5.88316, 30.5042, 12.3476, 1.32645, 120, 0, 0, 1, 0, 0, 0, 0),
(379071, 30651, 623, -1, -1, 1, 169, 0, 0, -40.6824, 29.2156, 12.335, 1.91986, 120, 0, 0, 1, 0, 0, 0, 0),
(379072, 30646, 623, -1, -1, 1, 169, 0, 0, -30.2557, 31.8003, 12.3542, 1.6057, 120, 0, 0, 1, 0, 0, 0, 0),
(379073, 30646, 623, -1, -1, 1, 169, 0, 0, -5.32528, 31.625, 12.34, 1.50098, 120, 0, 0, 1, 0, 0, 0, 0),
(379074, 30832, 623, -1, -1, 1, 169, 0, 0, 35.923, 48.7502, 34.3824, 4.67748, 120, 0, 0, 1, 0, 0, 0, 0),
(379075, 30832, 623, -1, -1, 1, 169, 0, 0, -6.26244, 40.0266, 24.1449, 4.71239, 120, 0, 0, 1, 0, 0, 0, 0),
(379076, 30832, 623, -1, -1, 1, 169, 0, 0, -27.1578, 39.3915, 26.3797, 4.71239, 120, 0, 0, 1, 0, 0, 0, 0),
(379077, 30832, 623, -1, -1, 1, 169, 0, 0, -61.933, 22.002, 33.9965, 4.86947, 120, 0, 0, 1, 0, 0, 0, 0);

DELETE from creature_template_addon where entry IN (30343,30476,30832,30646,30651);
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES 
(30343, 0, 0, 0, 1, 0, NULL),
(30476, 0, 0, 0, 0, 0, '56852'),
(30832, 0, 0, 0, 1, 0, ''),
(30646, 0, 0, 0, 1, 0, ''),
(30651, 0, 0, 0, 1, 0, '');

DELETE from `gameobject` where `map`=623;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneID`, `areaID`, `spawnMask`, `phaseID`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES 
(100601, 195682, 623, -1, -1, 3, 169, 4.39529, 13.6833, 20.8039, 4.18465, 0, 0, 0, 0, 7200, 255, 1);

DELETE from `creature` where `map`=622;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneID`, `areaID`, `spawnMask`, `phaseID`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`) VALUES 
(379078, 30342, 622, -1, -1, 1, 169, 0, 0, 23.4324, 0.020079, 33.5795, 3.10669, 120, 0, 0, 1, 0, 0, 0, 0),
(379079, 31261, 622, -1, -1, 1, 169, 0, 0, -46.1665, 12.0447, 13.221, 1.43655, 120, 0, 0, 1, 0, 0, 0, 0),
(379080, 30699, 622, -1, -1, 1, 169, 0, 0, 1.85384, 32.8888, 10.0236, 1.58825, 120, 0, 0, 1, 0, 0, 0, 0),
(379081, 30690, 622, -1, -1, 1, 169, 0, 0, 15.2472, 32.3771, 10.6319, 1.07816, 120, 0, 0, 1, 0, 0, 0, 0),
(379082, 30690, 622, -1, -1, 1, 169, 0, 0, -11.2231, 32.912, 10.5587, 1.66664, 120, 0, 0, 1, 0, 0, 0, 0),
(379083, 30588, 622, -1, -1, 1, 169, 0, 0, -18.1028, -0.042108, 45.3172, 1.76278, 120, 0, 0, 1, 0, 0, 0, 0),
(379084, 30649, 622, -1, -1, 1, 169, 0, 0, 50.9957, 46.9566, 23.4137, 2.58309, 120, 0, 0, 1, 0, 0, 0, 0),
(379085, 30649, 622, -1, -1, 1, 169, 0, 0, 4.10968, 19.5269, 34.7477, 3.75246, 120, 0, 0, 1, 0, 0, 0, 0),
(379086, 30649, 622, -1, -1, 1, 169, 0, 0, 2.00674, 15.7385, 9.25007, 3.36848, 120, 0, 0, 1, 0, 0, 0, 0),
(379087, 30649, 622, -1, -1, 1, 169, 0, 0, -32.5343, 24.3023, 33.9708, 3.21141, 120, 0, 0, 1, 0, 0, 0, 0),
(379088, 30700, 622, -1, -1, 1, 169, 0, 0, 38.7626, 30.0934, 2.30818, 1.13446, 120, 0, 0, 1, 0, 0, 0, 0),
(379089, 30700, 622, -1, -1, 1, 169, 0, 0, -35.6663, 29.4333, 1.87925, 1.74533, 120, 0, 0, 1, 0, 0, 0, 0),
(379090, 30700, 622, -1, -1, 1, 169, 0, 0, 7.41708, 32.8267, 38.356, 1.55334, 120, 0, 0, 1, 0, 0, 0, 0),
(379091, 30700, 622, -1, -1, 1, 169, 0, 0, -55.9708, 28.4419, 18.025, 2.26893, 120, 0, 0, 1, 0, 0, 0, 0),
(379092, 30707, 622, -1, -1, 1, 169, 0, 0, 19.4709, 27.5296, 10.6453, 1.39626, 120, 0, 0, 1, 0, 0, 0, 0),
(379093, 30707, 622, -1, -1, 1, 169, 0, 0, -15.3085, 30.5928, 11.1161, 2.63545, 120, 0, 0, 1, 0, 0, 0, 0),
(379094, 30749, 622, -1, -1, 1, 169, 0, 0, -32.8779, 72.0731, 11.9128, 5.20108, 120, 0, 0, 1, 0, 0, 0, 0),
(379095, 30749, 622, -1, -1, 1, 169, 0, 0, 5.97916, 81.071, 33.4889, 4.64258, 120, 0, 0, 1, 0, 0, 0, 0),
(379096, 30749, 622, -1, -1, 1, 169, 0, 0, 50.6202, 68.2188, 11.5619, 4.06662, 120, 0, 0, 1, 0, 0, 0, 0),
(379097, 30589, 622, -1, -1, 1, 169, 0, 0, -11.832, -0.019289, 43.1147, 4.15388, 120, 0, 0, 1, 0, 0, 0, 0),
(379098, 30752, 622, -1, -1, 1, 169, 0, 0, 1.90987, 29.4374, 9.41023, 1.44862, 120, 0, 0, 1, 0, 0, 0, 0),
(379099, 30752, 622, -1, -1, 1, 169, 0, 0, 15.412, 29.3357, 10.002, 1.46608, 120, 0, 0, 1, 0, 0, 0, 0),
(379100, 30752, 622, -1, -1, 1, 169, 0, 0, 7.70243, 25.2304, 35.0808, 4.76475, 120, 0, 0, 1, 0, 0, 0, 0),
(379101, 30752, 622, -1, -1, 1, 169, 0, 0, -11.2548, 29.2534, 10.0028, 1.51844, 120, 0, 0, 1, 0, 0, 0, 0),
(379102, 30752, 622, -1, -1, 1, 169, 0, 0, 15.6916, -30.0409, 9.98218, 4.69494, 120, 0, 0, 1, 0, 0, 0, 0),
(379103, 30752, 622, -1, -1, 1, 169, 0, 0, 2.15097, -29.6063, 9.39967, 4.67748, 120, 0, 0, 1, 0, 0, 0, 0),
(379104, 30752, 622, -1, -1, 1, 169, 0, 0, -11.3778, -29.1484, 10.0136, 4.64258, 120, 0, 0, 1, 0, 0, 0, 0),
(379105, 30752, 622, -1, -1, 1, 169, 0, 0, 8.47234, -22.3667, 34.9983, 1.78024, 120, 0, 0, 1, 0, 0, 0, 0),
(379106, 31243, 622, -1, -1, 1, 169, 0, 0, -11.1884, -33.2367, 10.5973, 4.66003, 120, 0, 0, 1, 0, 0, 0, 0),
(379107, 31243, 622, -1, -1, 1, 169, 0, 0, 2.00544, -33.1426, 10.0028, 4.72984, 120, 0, 0, 1, 0, 0, 0, 0),
(379108, 31243, 622, -1, -1, 1, 169, 0, 0, 15.3881, -33.1, 10.6511, 4.74729, 120, 0, 0, 1, 0, 0, 0, 0),
(379109, 31353, 622, -1, -1, 1, 169, 0, 0, -7.99985, 17.8519, 35.0486, 2.46091, 120, 0, 0, 1, 0, 0, 0, 0),
(379110, 29795, 622, -1, -1, 1, 169, 0, 0, 45.6197, 7.29317, 30.0955, 4.67642, 120, 0, 0, 1, 0, 0, 0, 0),
(379111, 30753, 622, -1, -1, 1, 169, 0, 0, -26.8391, -10.402, 35.5991, 1.29366, 120, 0, 0, 1, 0, 0, 0, 0),
(379112, 30753, 622, -1, -1, 1, 169, 0, 0, 2.15579, 17.0338, 9.16353, 1.54405, 120, 0, 0, 1, 0, 0, 0, 0),
(379113, 30753, 622, -1, -1, 1, 169, 0, 0, -7.63407, 0.007234, 86.0904, 6.2728, 120, 0, 0, 1, 0, 0, 0, 0),
(379114, 30753, 622, -1, -1, 1, 169, 0, 0, 46.382, 7.89944, 10.4129, 3.96271, 120, 0, 0, 1, 0, 0, 0, 0),
(379115, 30753, 622, -1, -1, 1, 169, 0, 0, 45.981, -6.55312, 10.3636, 2.23091, 120, 0, 0, 1, 0, 0, 0, 0),
(379116, 30753, 622, -1, -1, 1, 169, 0, 0, 15.254, -0.009458, 86.0904, 3.14299, 120, 0, 0, 1, 0, 0, 0, 0),
(379117, 30753, 622, -1, -1, 1, 169, 0, 0, -34.939, -11.6484, 11.4697, 5.50858, 120, 0, 0, 1, 0, 0, 0, 0),
(379118, 30753, 622, -1, -1, 1, 169, 0, 0, -34.785, 11.9312, 11.4869, 0.836243, 120, 0, 0, 1, 0, 0, 0, 0),
(379119, 30753, 622, -1, -1, 1, 169, 0, 0, -26.9812, 10.5208, 35.5936, 4.74156, 120, 0, 0, 1, 0, 0, 0, 0),
(379120, 30753, 622, -1, -1, 1, 169, 0, 0, 1.98831, -18.0873, 9.16057, 4.66993, 120, 0, 0, 1, 0, 0, 0, 0),
(379121, 30754, 622, -1, -1, 1, 169, 0, 0, -19.0109, 27.0177, 89.9667, 6.22411, 120, 0, 0, 1, 0, 0, 0, 0),
(379122, 30754, 622, -1, -1, 1, 169, 0, 0, -54.639, -15.3254, 34.3972, 3.83128, 120, 0, 0, 1, 0, 0, 0, 0),
(379123, 30754, 622, -1, -1, 1, 169, 0, 0, -54.7182, 15.5861, 34.3897, 2.50086, 120, 0, 0, 1, 0, 0, 0, 0),
(379124, 30754, 622, -1, -1, 1, 169, 0, 0, -18.9215, -26.8371, 89.9664, 0.087792, 120, 0, 0, 1, 0, 0, 0, 0),
(379125, 30755, 622, -1, -1, 1, 169, 0, 0, -3.46042, 28.0231, 34.2784, 4.66548, 120, 0, 0, 1, 0, 0, 0, 0),
(379126, 30755, 622, -1, -1, 1, 169, 0, 0, 7.21494, -6.31021, 34.4191, 3.11118, 120, 0, 0, 1, 0, 0, 0, 0),
(379127, 30755, 622, -1, -1, 1, 169, 0, 0, 24.5852, 6.86575, 7.06382, 3.11055, 120, 0, 0, 1, 0, 0, 0, 0),
(379128, 30755, 622, -1, -1, 1, 169, 0, 0, 8.85995, 18.8224, 8.7027, 4.69035, 120, 0, 0, 1, 0, 0, 0, 0),
(379129, 30755, 622, -1, -1, 1, 169, 0, 0, 24.3302, -6.97827, 7.08356, 3.34184, 120, 0, 0, 1, 0, 0, 0, 0),
(379130, 30755, 622, -1, -1, 1, 169, 0, 0, -4.43012, 18.742, 8.62646, 4.66286, 120, 0, 0, 1, 0, 0, 0, 0),
(379131, 30755, 622, -1, -1, 1, 169, 0, 0, -5.59682, -28.2501, 34.1226, 1.55058, 120, 0, 0, 1, 0, 0, 0, 0),
(379132, 30755, 622, -1, -1, 1, 169, 0, 0, -4.46811, -18.5567, 8.62604, 1.53698, 120, 0, 0, 1, 0, 0, 0, 0),
(379133, 30755, 622, -1, -1, 1, 169, 0, 0, 29.8693, -29.5825, 89.7663, 3.05267, 120, 0, 0, 1, 0, 0, 0, 0),
(379134, 30755, 622, -1, -1, 1, 169, 0, 0, 8.83021, -4.6978, 84.7137, 2.34582, 120, 0, 0, 1, 0, 0, 0, 0),
(379135, 30755, 622, -1, -1, 1, 169, 0, 0, 37.6428, -9.00797, 30.0954, 0.004917, 120, 0, 0, 1, 0, 0, 0, 0),
(379136, 30755, 622, -1, -1, 1, 169, 0, 0, -26.188, -6.1712, 9.33333, 3.14217, 120, 0, 0, 1, 0, 0, 0, 0),
(379137, 30755, 622, -1, -1, 1, 169, 0, 0, 9.06884, -18.7113, 8.70787, 1.56054, 120, 0, 0, 1, 0, 0, 0, 0),
(379138, 30755, 622, -1, -1, 1, 169, 0, 0, 8.67689, 4.88796, 84.7137, 3.90012, 120, 0, 0, 1, 0, 0, 0, 0),
(379139, 30755, 622, -1, -1, 1, 169, 0, 0, 7.49121, 6.05275, 34.4239, 3.16615, 120, 0, 0, 1, 0, 0, 0, 0),
(379140, 30755, 622, -1, -1, 1, 169, 0, 0, 37.6401, 8.9586, 30.0954, 0.012771, 120, 0, 0, 1, 0, 0, 0, 0),
(379141, 30755, 622, -1, -1, 1, 169, 0, 0, -26.1511, 6.90449, 9.405, 3.12647, 120, 0, 0, 1, 0, 0, 0, 0),
(379142, 30755, 622, -1, -1, 1, 169, 0, 0, 29.4588, 29.8761, 89.7684, 3.15321, 120, 0, 0, 1, 0, 0, 0, 0),
(379143, 30824, 622, -1, -1, 1, 169, 0, 0, 55.5028, 0.080449, 30.5268, 3.15669, 120, 0, 0, 1, 0, 0, 0, 0),
(379144, 30825, 622, -1, -1, 1, 169, 0, 0, 38.4745, 0.038424, 10.1868, 3.15788, 120, 0, 0, 1, 0, 0, 0, 0),
(379145, 30826, 622, -1, -1, 1, 169, 0, 0, 55.0542, -3.74557, 30.0955, 2.77577, 120, 0, 0, 1, 0, 0, 0, 0),
(379146, 30827, 622, -1, -1, 1, 169, 0, 0, 45.884, -8.99976, 30.0955, 1.52942, 120, 0, 0, 1, 0, 0, 0, 0),
(379147, 30866, 622, -1, -1, 1, 169, 0, 0, -36.528, 23.9373, 33.9184, 1.89617, 120, 0, 0, 1, 0, 0, 0, 0),
(379148, 30866, 622, -1, -1, 1, 169, 0, 0, 15.9225, 26.2539, 35.4586, 1.60085, 120, 0, 0, 1, 0, 0, 0, 0),
(379149, 30866, 622, -1, -1, 1, 169, 0, 0, -36.1494, -23.2606, 33.9568, 4.2232, 120, 0, 0, 1, 0, 0, 0, 0),
(379150, 30866, 622, -1, -1, 1, 169, 0, 0, 17.7216, -26.2695, 35.5686, 5.06367, 120, 0, 0, 1, 0, 0, 0, 0),
(379151, 32301, 622, -1, -1, 1, 169, 0, 0, -3.37706, 0.007499, 34.0151, 4.65055, 120, 0, 0, 1, 0, 0, 0, 0);

DELETE from creature_template_addon where entry IN (30342,30588,31353);
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES 
(30342, 0, 0, 0, 1, 0, NULL),
(30588, 0, 0, 0, 1, 0, '57424'),
(31353, 0, 0, 0, 1, 0, '');

DELETE from gameobject where map=622;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneID`, `areaID`, `spawnMask`, `phaseID`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`) VALUES 
(100600, 195682, 622, -1, -1, 3, 169, 22.177, 22.9527, 35.6576, 4.29351, 0, 0, 0, 0, 7200, 255, 1);

**Comment by Killyana** [comment]
Spawn are fine in both ships, this issue happen with any other transport having spawns

**Comment by Rushor** [comment]
maybe ths is because the npcs are loaded before the transport map or vise versa?

it looks like they just drop below the transport map without having a map

**Comment by Vaternos** [comment]
UP

**Comment by Rushor** [comment]
any kind of temp solution out there to improve that? maybe disabeling the mmaps on that transport could help?

**Comment by sanctum32** [comment]
I managed to sort this by replacing

```c
void Player::UpdateObjectVisibility(bool forced)
{
    if (!forced)
        AddToNotify(NOTIFY_VISIBILITY_CHANGED);
    else
    {
        Unit::UpdateObjectVisibility(true);
        UpdateVisibilityForPlayer();
    }
}

```
to

```c
void Player::UpdateObjectVisibility(bool forced)
{
    if (!forced)
    {
        AddToNotify(NOTIFY_VISIBILITY_CHANGED);
    }
    else if (!GetSession()->PlayerLoading())`
    {
        Unit::UpdateObjectVisibility(true);
        UpdateVisibilityForPlayer();
    }
}

```

**Comment by CraftedRO** [comment]
d6ccdbea10a29091afc20471331f50260f65ac46 seems no longer valid
