### ISSUE TITLE
Phasing issue

### ISSUE THREAD

**Issue by silviu2008** [TrinityCore/TrinityCore#21952]
**Description:**

I apologize if  this is not an issue and just my bad understanding on how phasing works.
The problem is that phase is lost after using certain spells (one for sure is http://www.wowhead.com/spell=1953/blink)

**Current behaviour:**

Phase is lost after some spells are casted, like Blink.

**Expected behaviour:**

Maybe phase should be kept, i don't know for sure.

**Steps to reproduce the problem:**

1. Create a mage character
2. use .mod phase 200 on it
3. cast http://www.wowhead.com/spell=1953/blink

Phase 200 is lost after spell cast.

**Branch(es):**

Tested only on master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/19fd295685901f2d46110b23c6bca30e68b1385e

**Operating system:** Windows x64

**Comment by Shauren** [comment]
all custom phases set by gm commands are always lost when phasing update happens
