### ISSUE TITLE
Core/gameobject: Gameobject visibility not updating

### ISSUE THREAD

**Issue by Sevenn83** [TrinityCore/TrinityCore#21953]
**Description:**

`.gob move`or `.gob turn` are not updating visually, you need to relog or teleport to yourself to update visibility, I check on the core, and the line `object->UpdateObjectVisibility();` seems to do nothing.

**Current behaviour:**

Using `.gob move` or `.gob turn` seems to do nothing. However after relog or teleport to yourself you see the changes.

**Expected behaviour:**

Using `.gob move` or `.gob turn` should move the gameobject to the player's position immediately, and update visibility for near players

**Steps to reproduce the problem:**

1. `.gob add 189289`
2. `.gob target`
3. Move a bit and use `.gob move` or `.gob turn` with the gameobject link from the previous step
4. The object is not visually updated
5. Relog or Teleport to yourself and observe that the object did move to your location

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 19fd295 2018-05-21 13:39:14 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** windows 10

**Comment by Shauren** [comment]
#21729
