### ISSUE TITLE
Mage flash(spell 1953) to higher place will fall into void.

### ISSUE THREAD

**Issue by Maxwelllmj** [TrinityCore/TrinityCore#21962]
**Description:**

Mage Flash to higher place will fall into void.

**Current behaviour:**

Mage Flash to higher place will fall into void.

**Expected behaviour:**

Mage Flash to higher place, if player can walk to destination, player would teleport to there.
If player cant walk there, player will be sent as far as possible.

**Steps to reproduce the problem:**

1. Step 1 
    Create a mage, learn flash(spell 1953).
2. Step 2
    Find a uphill.  
3. Step 3
    Use flash toward the uphill

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
17539f1cb319f0d8d089038a4b10924d145ee248

**Operating system:** win10

**Comment by Maxwelllmj** [comment]
I tried to add _sourceUnit->GetMap()->GetHeight(destPosition) in CalculatePath to find Z.   But only the destPosition is higher than the ground can find the right Z coordinates.

**Comment by Aokromes** [comment]
#16595
