### ISSUE TITLE
Core/Movements: Creatures can walk up but cannot walk down, when mmap.enablePathFinding = 1.

### ISSUE THREAD

**Issue by Maxwelllmj** [TrinityCore/TrinityCore#21969]
**Description:**

Creatures can walk but cannot walk down, when mmap.enablePathFinding = 1.

**Current behaviour:**

When fight with malchezaar, I was hit to the corner. then malchezaar run to the low wall, and never come down again.

**Expected behaviour:**

If his goal is at the corner, he should stand in a reasonable place and attack the target instead of putting on the wall. Even on the wall should be able to come down. 

**Steps to reproduce the problem:**

1. Step 1 
    open GM mode(.gm on).    type ".go xyz -10962 -2018 276 532"  teleport to malchezaar
2. Step 2
    close GM mode(.gm off).   attack Malchezaar and leading him to the corner
3. Step 3
    Waiting for Malchezaar to walk to the wall, if he don't go, just move left and right .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. f8427ccfb2d8+ 2018-05-26 22:11:52 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Dynamic)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on: Linux 4.9.0-6-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252190595 bytes
vmaps directory located in ./vmaps. Total size: 588247333 bytes
mmaps directory located in ./mmaps. Total size: 2152621560 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: TDB 335.64

**Operating system:** debian9

**Comment by Maxwelllmj** [comment]
:(

**Comment by Langerz82** [comment]
Does this patch make any difference?

See:
https://github.com/TrinityCore/TrinityCore/issues/22116

**Comment by illfated** [comment]
Maybe it has been solved in one of the recent map changes to the core.
@Maxwelllmj : Can you confirm if the issue with Prince Malchezaar has been solved?

**Comment by Killyana** [comment]
Still an issue: 
![image](https://user-images.githubusercontent.com/6587064/53489085-78544100-3a90-11e9-9189-8d572663293f.png)

**Comment by Killyana** [comment]
@jackpoz for this case we can just add disable path finding for this boss.

**Comment by Aokromes** [comment]
or maybe change script for a better check of walls.

**Comment by Jinnaix** [comment]
As of 4caa218 im unable to perma-stuck him on that wall.
This might be "fixed" by 995a443 ? Ive rerun mmaps for this.
That doesnt totally break the fight anymore but this area is still wonky as hell and has issues - he cant melee a player close to the wall and he can now climb the whole mountain if you lead him on the small wall and than move back to the door.

**Comment by Killyana** [comment]
It's still messy and the player can avoid melee in some corners.

**Comment by Jinnaix** [comment]
I didnt test if Malchezaar might attack another target if he cant melee the tank - that might be the case. So Players trying to avoid melee damage might wreck the raid by this.

**Comment by jackpoz** [comment]
are there some new .go xyz steps to reproduce this issue ?

**Comment by jackpoz** [comment]
can someone retest this in a recent revision ?

**Comment by Jildor** [comment]
Tested on rev: f474418651557acb621e9634993738118fb54a7e
.gm on
.go boss malchezaar
attack the boss and move to the corner of wall
you can see how the boss can't attack melee but you can hit him
example: https://imgur.com/9FqPj1N

**Comment by jackpoz** [comment]
pretty sure this is the same issue as in Dalaran Arena where we keep doing "find poly" instead of keeping track of the actual poly where the unit is.

**Comment by jackpoz** [comment]
![image](https://user-images.githubusercontent.com/1153754/106367097-9394ee80-6340-11eb-82d2-30b968a9af9b.png)

as the issue is about "can walk up but cannot walk down", in this case the boss is not supposed to walk up at all as those polys are disconnected, caused by picking the wrong poly as current implementation doesn't keep track of the current poly where a unit is

**Comment by jackpoz** [comment]
![image](https://user-images.githubusercontent.com/1153754/106367374-782ae300-6342-11eb-8c4d-d71ed70b2a0a.png)

See how startPoly changes all of a sudden in the last line of the Output window ? that's PathGenerator picking the wrong poly. It might be vmap checks make the boss be above ground level in the first place, allowing this issue to happen even more clearly.

**Comment by jackpoz** [comment]
The correct poly is at 7.8y, the wrong poly is at 4.8y so it picks the wrong one.
Z is 283.7 while the floor is at 279.7

**Comment by jackpoz** [comment]
Increasing the walkable radius didn't really fix anything.

As the issue is that map/vmap height forces the boss to be on the level of the low wall, I tried disabling those checks for this boss and this is how it looks:

https://imgur.com/a/YZKV8lP

**Comment by Jildor** [comment]
nice 👍

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/26092
