### ISSUE TITLE
Core/Creature: Assist doesn't happen with neutral npcs

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#21967]
**Description:**

Npcs on formation using groupAI: 515 | Everyone assists everyone and member follow the leader or other kind of assist doesn't assist other members if they are neutral to the player.

This also happen with npcs that are close each to other.

**Steps to reproduce the problem:**

1. .go c 80849 
2. aggro one of the pigs and notice the 2 others doesn't assist
3. .gm on
4. mod fac 17 the three pigs and aggro one of them (notice the 2 others will assist

Second case:
1. .go 473 (gm on)
2. Aggro the npcs when you're max distance
3. notice the 3 other humans on the house will assist
4. gm on
5. .mod fac 7 the three human int the house
6. aggro the npc guid=473  (Notice the 2 others will not assist

**Branch(es):** 3.3.5

TrinityCore rev. 6519c90467ca 2018-05-26 19:59:07 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.6.15
Using CMake version: 3.11.2
Compiled on: Windows 
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2229000480 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR 
Using World DB: TDB 335.64

**Comment by Langerz82** [comment]
Trying to add formations to the pigs as they have none attached but im getting this error from the worldserver.exe.

Added:
INSERT INTO `world`.`creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES ('80849', '80848', '0', '0', '515', '0', '0');
INSERT INTO `world`.`creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES ('80849', '80850', '0', '0', '515', '0', '0');

Error:
Loading Creature Formations...
creature_formation contains leader spawn 80849 which is not included on its formation, removing

**Comment by Killyana** [comment]
They have a formation https://github.com/TrinityCore/TrinityCore/commit/5eb6e2bbcd03b57952f0739d837cb976061348cb

**Comment by Langerz82** [comment]
ok cool, will have a look at it later. I was missing this from my DB.

**Comment by Langerz82** [comment]
with just the creature formations it was working for me. Looking into it further.

**Comment by Langerz82** [comment]
ok casting "Hand of Reckoning" on one of the pigs with faction 7 does indeed not aggro the other pig. Is it retail like to when taunted the whole creature group attacks?

**Comment by Langerz82** [comment]
This seems to make it work for the above case.

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index bc9c1bd278..bb7269a0bc 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -8596,13 +8596,13 @@ void Unit::EngageWithTarget(Unit* enemy)
     if (!enemy)
         return;
 
-    if (IsEngagedBy(enemy))
-        return;
-
-    if (CanHaveThreatList())
-        m_threatManager.AddThreat(enemy, 0.0f, nullptr, true, true);
-    else
-        SetInCombatWith(enemy);
+    if (!IsEngagedBy(enemy))
+    {
+        if (CanHaveThreatList())
+            m_threatManager.AddThreat(enemy, 0.0f, nullptr, true, true);
+        else
+            SetInCombatWith(enemy);
+    }
 
     if (Creature* creature = ToCreature())
         if (CreatureGroup* formation = creature->GetFormation())

```

**Comment by Treeston** [comment]
Cannot reproduce case 1 on latest 3.3.5.

I believe case 2 to be intended behavior. Neutral creatures do not have nearby auto-assist.
