### ISSUE TITLE
Server Crash on _CreateAuraApplication

### ISSUE THREAD

**Issue by daddycaddy** [TrinityCore/TrinityCore#21980]
Server Crash on _CreateAuraApplication

Crash Report: https://gist.github.com/daddycaddy/aa6d6db91430b4eb631773f616ed40b4

Revision: TrinityCore rev. f8427ccfb2d8+ 2018-05-26 22:11:52 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

OS: Windows Server 2012 Standard (Version 6.2, Build 9200)

PS: I do not have more information about it, I will update if I find anything else, thank you

**Comment by Gooyeth** [comment]
Duplicate #21856
