### ISSUE TITLE
DB/Quest: Picking Up Some Power Converters (10584) Unable to start

### ISSUE THREAD

**Issue by Bilibox** [TrinityCore/TrinityCore#21986]
**Description:**

Quest:
http://www.wowhead.com/quest=10584/picking-up-some-power-converters
Quest Item:
http://www.wowhead.com/item=30656/protovoltaic-magneto-collector
Object on ground: 
http://www.wowhead.com/object=184906/power-converter
NPC:
http://www.wowhead.com/npc=21691/toshley

**Current behaviour:**

1. Unable to Start quest. Toshley does not have the beginning of the quest.

2. During quest Object on ground does not despawn. (Power Converter)

**Expected behaviour:**

1. Toshley should allow you to take the quest at level 65+.
2. When object on ground is used it should despawn for an amount of time.

**Steps to reproduce the problem:**

1. Go to Toshley (Quest not found)
2. .quest add 10584 
3. Go to quest area click on Power Converter. (Object not Despawning)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 80b0125d90e2 2018-5-29 21:45:34 +0200 (3.3.5 Branch) (Win 64, Release, Static)

**Operating system:** Windows

**Comment by Killyana** [comment]
There's a quest requirements: 10516 -> 10517 -> 10518 -> 10580 -> 10588 -> 10581 -> 10584

**Comment by Bilibox** [comment]
@Killyana Correct. I redid this on my GM and it worked but for some reason my main account it didn't.

**Comment by Bilibox** [comment]
The second issue of the object not despawning is still an issue...

**Comment by Killyana** [comment]
This gobs will not respawn because of https://github.com/TrinityCore/TrinityCore/issues/21792
