### ISSUE TITLE
Test Flight quests Throw you in wrong direction

### ISSUE THREAD

**Issue by Bilibox** [TrinityCore/TrinityCore#21987]
**Description:**

Test Flight Quests 
http://www.wowhead.com/quest=10557/test-flight-the-zephyrium-capacitorium
http://www.wowhead.com/quest=10710/test-flight-the-singing-ridge
http://www.wowhead.com/quest=10711/test-flight-razaans-landing
http://www.wowhead.com/quest=10712/test-flight-ruuan-weald

Quest Giver:
http://www.wowhead.com/npc=21460/tally-zapnabber

Quest Progression:
http://www.wowhead.com/npc=21461/rally-zapnabber

Spell Cast on you:
http://www.wowhead.com/spell=36795/cannon-channel-dnd

Buff that is put on you
http://www.wowhead.com/spell=37962/soaring
http://www.wowhead.com/spell=36812/soaring
http://www.wowhead.com/spell=37968/soaring
http://www.wowhead.com/spell=37910/soaring

**Current behaviour:**
Currently each of these quests throw you in the wrong direction. Once Cannon Channel dnd is cast you are thrown to a random area. Also when put into place during Cannon Channel DND the character is not "floating" as expected. 

**Expected behaviour:**

Once Cannon Channel DND is cast while floating you are thrown to certain Cords depending on the quest. 

Coords of where to end up per quest
ruuan-weald = 62:39
razaans-landing = 66:49
the-singing-ridge = 67:73
the-zephyrium-capacitorium = 54:73

Video Showing Expected Behavior
https://www.youtube.com/watch?v=Vuaa-0mlHDc
https://www.youtube.com/watch?v=J07g2e3Bw5k
https://www.youtube.com/watch?v=fFSAMFj_An0
https://www.youtube.com/watch?v=O7f61WsQjp8
**Steps to reproduce the problem:**

1. Talk to Tally Zapnabber and grab quest.
2. Go to Rally Zapnabber and choose to go to the location.
3. Allow Cannon Channel DND to be cast.
4. The appropriate spell Soaring is then put on you but pushes you the wrong way.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e3e2bb60f6ffccbdcc11cfbdb009fa6e6ffdcb6b

**Operating system:** Windows

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/17840
