### ISSUE TITLE
DB/Quest: Sabatoge the Warp-Gate, NPC does not continue quest

### ISSUE THREAD

**Issue by Bilibox** [TrinityCore/TrinityCore#21993]
**Description:**
http://www.wowhead.com/quest=10310/sabotage-the-warp-gate
http://www.wowhead.com/npc=20281/drijya

NPC does not move from 1st pylon.

**Current behaviour:**

NPC stops at first pylon, does not continue 

**Expected behaviour:**

NPC moves from 1st to second pylon, second to third set, npc goes back to start position

https://www.youtube.com/watch?v=3-C8Vdqoy9Q

**Steps to reproduce the problem:**

1. Accept quest from NPC
2. Follow NPC to 1st pillar and kill adds
3. 

**Branch(es):**

3.3.5
**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e3e2bb60f6ffccbdcc11cfbdb009fa6e6ffdcb6b

**Operating system:** Windows

**REF ISSUE**
https://github.com/TrinityCore/TrinityCore/issues/18603
Looks like it was fixed but as of now the issue persists.

**Comment by Killyana** [comment]
Must be tested once issues related to waypoints fixed.

**Comment by offl** [comment]
Can't reproduce in 8a9cc0f65d8f
