### ISSUE TITLE
[3.3.5] Spell proc system: Penance + Grace

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#22005]
56a056a

Priest's Penance consists of multiple spells when cast on allies.

47540 - "Penance (spellbook)" - the spell in the spellbook
47757 - "Penance (heal)" - the channeled healing spell, cast by Penance (spellbook)'s spell script
47750 - "Penance (projectile)" - the actual orb that does healing, triggered by Penance (heal)

Grace (47517) lists Penance (heal) and Penance (projectile) in its proc data. The spell script on 47540 (see `spell_priest.cpp`) casts Penance (heal) with `TRIGGERED_DISALLOW_PROC_EVENTS`. However, the initial hit phase of Penance (heal) still triggers Grace, first on the target and then on the priest itself (when applying the channel aura). This is incorrect, as only Penance (projectile) should apply Grace on impact.

It would appear that `TRIGGERED_DISALLOW_PROC_EVENTS` is not honored here.

**Comment by Jildor** [comment]
I hope @ariel- is still alive :pray:

**Comment by Keader** [comment]
Buzy with University, he should back when semester is over :)

**Comment by Jildor** [comment]
So by the moment he isn't alive 😄

**Comment by Rushor** [comment]
Penance restacks Grace from 0 stacks everytime it is cast, so it will never benefit from the grace effect

**Comment by CraftedRO** [comment]
> Penance restacks Grace from 0 stacks everytime it is cast, so it will never benefit from the grace effect

9d445b4016581ad3bf20ac7efd840250f72854e2 this seems no longer the case, penance will continue grace stacks at least visually
