### ISSUE TITLE
[3.3.5] Scripts/Pit of Saron: Ick should update threat list when top threat player dies

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#22001]
**Description:**

When Ick lose target (player die), Ick doesn't move to another player in group, so, you are free to attack in range.

Dungeon: http://www.wowhead.com/pit-of-saron
Boss: http://www.wowhead.com/npc=36476/ick

@Keader 

**Steps to reproduce the problem:**

1. Get 2 players and go to Ick in Pit of Saron
2. 1 player attack Ick and die
3. Another player cast in range

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 982643cd9679 2018-06-03 10:06:57 -0700 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on: Linux 4.9.0-4-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

**Comment by ccrs** [comment]
related to #21900

**Comment by Jildor** [comment]
@ccrs
I think in  this case isn't related with these issue.
it's boss script problem (target guid) I think.

And  happens before this issue too

**Comment by illfated** [comment]
suggestion for issue title (based on your description that this is a script issue):
**Scripts/Pit of Saron: Ick should update threat list when top threat player dies**

**Comment by Keader** [comment]
lul

```
                if (!me->IsEngaged())
                    return;
```

Yeah looks like script issue xD
i will check later.

**Comment by Jildor** [comment]
@illfated edited ;)

**Comment by illfated** [comment]
Also, a suggestion for TC members with access to set labels for this issue:
**[Comp-C++Script] [Sub-Instances]**
