### ISSUE TITLE
Spells/item: Titanium Seal of Dalaran

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#22017]
**Description:**

"Titanium Seal of Dalaran" does not seem to have any scripted spell effects for the item (not yet implemented?).
(See also the old issue #3434 which was closed without any solution or suggestion that it worked for anyone.)

- https://wow.gamepedia.com/Titanium_Seal_of_Dalaran
- http://www.wowhead.com/item=44430/titanium-seal-of-dalaran (mailed item from [Achievement: The Coin Master](http://www.wowhead.com/achievement=2096/the-coin-master))
- http://www.wowhead.com/spell=60458/toss-your-luck [Trigger Missile ([Toss Your Luck!](http://www.wowhead.com/spell=60476/toss-your-luck))] 
`Flags : Can only be used during nighttime`
- http://www.wowhead.com/spell=60476/toss-your-luck (Script Effect)

**Current behaviour:**

1. Your character moves its hands together shortly as if performing a profession action
2. You hear the "plink" sound of a coin hitting a surface, just like when you toss one of the gold coins into the Dalaran fishing pond.
3. The 10 second item cooldown runs and seems to work as expected.
4. None of the expected visual results happen at all, like the chat log text line
`<Name> casually flips <his/her> Titanium Seal of Dalaran.`

... which should lead to one of these 2 lines (fancy way of rolling `/random 2`):

- `<Name> catches the coin heads up!`
- `<Name> finds the coin face down for tails!`

**Expected behaviour:**

1. There should be a brief animation of a (gold?) coin being tossed up in the air. Posted images suggest it lands as a visible coin object on the ground.
2. There should be 2 chat text message lines as a result of using the item: `<Name> casually flips <his/her> Titanium Seal of Dalaran.` and one of the 2 possible results.

**Steps to reproduce the problem:**

1. Complete the achievement [The Coin Master](http://www.wowhead.com/achievement=2096/the-coin-master) or `.additem 44430`
2. Use the item "Titanium Seal of Dalaran" (10 second cooldown).
3. Listen to the coin sound and look for any visual effects.

**Branch(es):**  3.3.5

**TC rev. hash/commit:** 

TC>server debug
TrinityCore rev. 5fa783bd34d8 2018-06-09 10:10:54 -0300 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10 Home x64 version 1803 (OS-build 17134.81)

**Comment by offl** [comment]
I guess the missile data is broken since it looks like player catches the coin almost instantly, I don't see any coin at all
Texts are here and I guess the fact that they comes without $n will be a problem too
```sql
SELECT * FROM broadcast_text WHERE id IN (32638,32663,32664)
```
```txt
    ID  LanguageID  Text                                                                        Text1                                                                       EmoteID1  EmoteID2  EmoteID3  EmoteDelay1  EmoteDelay2  EmoteDelay3  SoundEntriesID  EmotesID   Flags  VerifiedBuild  
------  ----------  --------------------------------------------------------------------------  --------------------------------------------------------------------------  --------  --------  --------  -----------  -----------  -----------  --------------  --------  ------  ---------------
 32638           0  casually flips his |Hitem:44430|h|cff0070dd[Titanium Seal of Dalaran]|r|h.  casually flips her |Hitem:44430|h|cff0070dd[Titanium Seal of Dalaran]|r|h.         0         0         0            0            0            0               0         0       1            18019
 32663           0  catches the coin heads up!                                                  catches the coin heads up!                                                         0         0         0            0            0            0               0         0       1            18019
 32664           0  finds the coin face down for tails!                                         finds the coin face down for tails!                                                0         0         0            0            0            0               0         0       1            18019
```

**Comment by illfated** [comment]
Thank you for looking into this. I had the chance to get this coin again after getting the achievement "The Coin Master" last weekend (f418631de0c1), but it behaved just like you wrote in your first sentence.

**Comment by CraftedRO** [comment]
has this been fixed ?
