### ISSUE TITLE
NPC: Firewing Courier missing aggro text

### ISSUE THREAD

**Issue by Jonne733** [TrinityCore/TrinityCore#22021]
**Description:**

[Firewing Courier ](https://woehead.way-of-elendil.fr/?npc=18548)missing aggro text

**Current behaviour:**
Text is missing when you engage him

**Expected behaviour:**
He is suppose to say "This belongs to Firewing Point.  You'll not be putting your grubby hands on it!" when you engage in combat with him. See screenshot
![firewing_courier](https://user-images.githubusercontent.com/40151102/41223421-05d5e1d6-6d6a-11e8-9c72-3654134a0673.jpg)

**Steps to reproduce the problem:**

1. Go to npc [18548](http://www.wowhead.com/npc=18548/firewing-courier)
2. Aggro him.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 5fa783bd34d8e5b32aded6b87a1e4b196b7c4022
**TDB version**: ed63d15
**Operating system:** Windows 10

**Additional info**
- The text appear regardless if you have the quest [Investigate Tuurem
](http://www.wowhead.com/quest=9990/investigate-tuurem) in your quest log or not.
- All info from live server

**Sugested Fix**
```sql
-- Firewing Courier Aggro Text
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=18548;
DELETE FROM `smart_scripts` WHERE `entryorguid`=18548 AND `source_type`=0 AND `id`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(18548,0,0,0,4,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Firewing Courier - On Aggro - Say Line 0");

DELETE FROM `creature_text` WHERE `CreatureID`=18548;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(18548,0,0,"This belongs to Firewing Point.  You'll not be putting your grubby hands on it!",12,0,100,0,0,0,15528,0,"Firewing Courier");
```

**Comment by illfated** [comment]
Maybe your 3.3.5 game client is not set to show speech bubbles? (just guessing)

**Comment by Jonne733** [comment]
![wowscrnshot_061318_095105](https://user-images.githubusercontent.com/40151102/41337490-a5ccea8c-6eef-11e8-9e8f-be46f1e455cf.jpg)
Nope they work ;)

**Comment by Jonne733** [comment]
Okey never mind, the speech bubble does appear now but instead the text gets double posted in chat window.
![firewing_courier_update](https://user-images.githubusercontent.com/40151102/41337918-ee18dc46-6ef0-11e8-8789-d392c6dc90dd.jpg)

**Comment by ZenoX92** [comment]
Your fix is working just fine. I've just tested it. But there's no need to set `id`=1, since it's the only script you can set `id`=0.

**Comment by Jonne733** [comment]
Updated original scrip with ZenoX92's sugestion, works good. Thank you :)

**Comment by illfated** [comment]
Perhaps you had a temporary game client Cache or addon issue?
I have had such issues long ago when testing my own solutions (as tkrokli).
