### ISSUE TITLE
[Master] Core crash when accepting quest

### ISSUE THREAD

**Issue by Phentora** [TrinityCore/TrinityCore#22038]
**Description:**

I have a Undead character where i performed several relogins and now when i login with that specific character and accept [Novice Elreth quest (28651)](http://www.wowhead.com/quest=28651/novice-elreth), the core crashes.

**Steps to reproduce the problem:**

1.  Create a Undead character.
2.  Play with him normally and perform a few relogins.
3.  Take quest Novice Elreth.

**Branch:**
Master

**TC rev. hash/commit:** 
TrinityCore rev.36ff7668823f 2018-06-03 13:31:13 +0200 (master branch) (Win64, Debug, Static)

**Operating system:** Windows 10 x64

Crashdumps: 

> https://gist.github.com/Phentora/8bded5d0d08cda72ba02abed0a5dea65
> https://gist.github.com/Phentora/1fed731340b74fa5e4613662a20c4ae1
> https://gist.github.com/Phentora/3108d32b35a436189b6cf74287d9b84a
> [dmpFiles.zip](https://github.com/TrinityCore/TrinityCore/files/2103858/dmpFiles.zip)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21775
