### ISSUE TITLE
Stuck after realm selection even in local 

### ISSUE THREAD

**Issue by lMGKl** [TrinityCore/TrinityCore#22035]
Hello, i thank you in advance for your massive work on the trinitycore @Shauren 
**Description:**

When i try to connect from local or from external ip client stuck on "logging in to game server"after the realm selection and  worldserver  says :
 "TrinityCore rev. 33e06fc677d2 2018-06-13 14:05:48 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon) ready...
WorldSocket::HandleAuthSession: Authentication failed for account: 2 ('2#1') address: 2.xxx.xxx.xxx

**Current behaviour:**
[https://imgur.com/a/2bCwF2d](url)

**Expected behaviour:**

should let me connect and see the character list

i don't know

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 33e06fc677d2 2018-06-13 14:05:48 +0200 (master branch) (Win64, Release, Static)

**Operating system:** Windows server 2012

**Comment by Aokromes** [comment]
user missconfiguration don't belongs here.

**Comment by lMGKl** [comment]
super nice guy! ^^

**Comment by illfated** [comment]
Use the TrinityCore Forum pages (create a new account or log in to) https://community.trinitycore.org/
Alternatively, ask in the IRC channel #trinity @ irc.rizon.net to ask for help in a direct chat dialogue.
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC
