### ISSUE TITLE
Mobs that flee at low health are lagging the game

### ISSUE THREAD

**Issue by rbasniak** [TrinityCore/TrinityCore#22048]
**Description:**

Mobs that flee at low health are lagging the game

**Current behaviour:**

When you attack a mob that flees when they're low at health, the moment they should run away if we cast another spell, the spell animation cast doesn't finish and you can't do anything else. After about 30s the games goes back to normal and the mob appears dead. I experieced this on the Kobolds near Goldshire and with the plant guys on Druid starting area, near Darnassus/

**Expected behaviour:**

When the mob flee, the game shouldn't freeze

**Steps to reproduce the problem:**

1. Attack Kobold Tunnelers at Fagordeep Mine, near Goldshire (http://www.wowhead.com/npc=475/kobold-tunneler)
2. Keep attacking until he's low at health and should start fleeing
3. Everything in the game freezes in place (like when there's a lot of lag in the server). 
4. After about 30s, everything goes back to normal

**Branch(es):**

3.3.5

628b488ebd

**Operating system:** Windows Server 2016

**Comment by Killyana** [comment]
http://www.wowhead.com/npc=475/kobold-tunneler doesn't flee at low health.

**Comment by rbasniak** [comment]
@Killyana Ok, thanks. I was pretty sure what they had in common was that they flee, but the issue is still happening anyway.

I'll recompile with your revision and I'll update this post today.

**Comment by illfated** [comment]
Also remember that some game client addons can cause random lag (test without all addons to check).

**Comment by rbasniak** [comment]
@Killyana You're right, it doesn't happen on 8a31204. I'll try to recompile with the latest commit to update the post.

**Comment by rbasniak** [comment]
Actually what was causing this was messing too much with the following rates:
```
Rate.Drop.Item.Poor             = 1
Rate.Drop.Item.Normal           = 1
Rate.Drop.Item.Uncommon         = 1
Rate.Drop.Item.Rare             = 50
Rate.Drop.Item.Epic             = 500
Rate.Drop.Item.Legendary        = 1
Rate.Drop.Item.Artifact         = 1
Rate.Drop.Item.Referenced       = 1
Rate.Drop.Money                 = 1
Rate.Drop.Item.ReferencedAmount = 10
```

I was using very high values in them, now that I lowered them, it doesn't happen anymore.

**Comment by illfated** [comment]
Thank you for telling us what caused your problem and thereby verifying that it was not caused by the source code itself.

To save yourself some time in the future, make sure you test with standard settings before opening an issue. Saves everyone's time. 🕑
