### ISSUE TITLE
Warlock demonic circle no teleport

### ISSUE THREAD

**Issue by yudian1994** [TrinityCore/TrinityCore#22040]
Description:
Echiso demonic circle does not teleport to the place where it is invoked

Current behavior:
When you put the demonic circle and you give it to teleport it does not teleport besides that it does not admit to launch any other branch of the branch.

Expected behavior:
When you invoke demonic circle and then you teleport to teleport to the place where it was invoked and remove all the effects that cause movement reduction on the player

Steps to reproduce the problem:
1-Create a warlock player and specialize in destruction
2-Choose demonic circle talent
3-Use the demonic circle
Description:
Echiso demonic circle does not teleport to the place where it is invoked

Current behavior:
When you put the demonic circle and you give it to teleport it does not teleport besides that it does not admit to launch any other branch of the branch.

Expected behavior:
When you invoke demonic circle and then you teleport to teleport to the place where it was invoked and remove all the effects that cause movement reduction on the player

Steps to reproduce the problem:
1-Create a warlock player and specialize in destruction
2-Choose demonic circle talent
3-Use the demonic circle

TC rev. hash / commit:
TC> TrinityCore rev. 170d10b8a92c + 2018-06-14 23:08:55 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon) ready ...
OS:
Windows 10 Build: 1709

**Comment by Aokromes** [comment]
#19654
