### ISSUE TITLE
Remove Curse "Nothing to dispell" 3.3.5

### ISSUE THREAD

**Issue by Jasonqt** [TrinityCore/TrinityCore#22051]
**Description:**

Remove Curse wont dispell target if you have the same curse applied

**Current behaviour:**

Remove Curse doesn't work properly. When you try to remove a curse from a friendly target when you both have the same curse applied, it says "Nothing to dispell". However, if you dont have said curse, and your friendly target does, It works. (Tested on Mage and Druid) 
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Even if you have same curse as your partymember(s), you should be able to dispell target.

**Steps to reproduce the problem:**

1. Go to molten core / .go creature 56737
2. Attack Gehennas, and wait for her to apply the debuff to you and your target
3. Try to dispell your partymember(s)

**Branch(es):**

Tested only on 3.3.5

**TC rev. hash/commit:** 718742005c3b

Debug command:
TrinityCore rev. 718742005c3b+ 2018-06-17 17:03:10 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.65.1
Using MySQL version: 10.1.30-MariaDB
Using CMake version: 3.11.2
Compiled on: Windows 6.1.7601
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Disabled
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 

**Operating system:** Tested on Debian 9, Windows 7 & 10.

**Comment by Langerz82** [comment]
I created a party of two. Casted "Curse of the elements" on both party members, used "Remove curse" on target party member and its working as intended. Whats the debuff spell id the creature is casting?

**Comment by Jasonqt** [comment]
I forgot to mention, if you do it that way it will work. You have to make a mob cast it on you for it not to work.

**Comment by Langerz82** [comment]
Can you give an example thats not in an instance, with commands to get there. (Im a WoW noob) XD

**Comment by illfated** [comment]
GM character can use `.go creature Gehennas` and then `.summon (player name)`
There are mobs in Stratholme who cast curses too, you may want to check there.
(GM command `.tele stratholme` to get to the entrance, then `.summon (player name)`

**Comment by Langerz82** [comment]
I used two GM accounts, Got into instance, put GOD mode on (so i dont die instantly :P). When Gehannas Curse is cast, I can still remove it even though I had it on the casting Dispel Character. 

I'm using an older branch could this be the reason its working for me?

rev: TrinityCore rev. ed63d15dfe95 2018-02-18 18:56:29

**Comment by Killyana** [comment]
I cannot reproduce on rev. 8a312046b221

**Comment by illfated** [comment]
@Jasonqt : My apologies, I forgot to check the exact wording of your command line.
You did not use 'id' which means you went to the `guid` of Gehennas, not the id. Fair enough.

**Comment by Cillez** [comment]
I can confirm it happend to me on the rev OP has noted.
@Langerz82 i went back to feburary myself and its working fine, so its something that was changed between february-June.

Ill try latest rev and report back

**Comment by Cillez** [comment]
Still not working on 029c4232a7f5

@Killyana did you do what he stated in his second comment?

**Comment by Killyana** [comment]
I updated the core rev. 2e6100919d77
Now I'm not able to dispel another player from my party, it tells me "there's nothing to dispel"
If I have the same aura as the player from my party, if I dispel my char the other player will be dispelled, also if I .unaura my char the aura will also be dispelled from the other player.

If I unaura the other player the aura will reapply as soon as it's dispelled, it's like it was linked to my char.

**Comment by Langerz82** [comment]
think I got something, will provide a patch later.

**Comment by Langerz82** [comment]
See if this works. Seems to be working for me. The only other query I have is should dispell get rid of the parties buffs or just a single target? Cause it's removing it like a party buff.

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 6e8a96d72f..d19d325894 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -4414,11 +4414,12 @@ void Unit::GetDispellableAuraList(WorldObject const* caster, uint32 dispelMask,
     if (dispelMask & (1 << DISPEL_DISEASE) && HasAura(50536))
         dispelMask &= ~(1 << DISPEL_DISEASE);
 
-    AuraMap const& auras = GetOwnedAuras();
+    AuraApplicationMap const& auras = GetAppliedAuras();
     for (auto itr = auras.begin(); itr != auras.end(); ++itr)
     {
-        Aura* aura = itr->second;
-        AuraApplication const* aurApp = aura->GetApplicationOfTarget(GetGUID());
+        AuraApplication* aurApp = itr->second;
+        Aura* aura = aurApp->GetBase();
         if (!aurApp)
             continue;
 
```

**Comment by Killyana** [comment]
It must be removed only from the dispelled player.

**Comment by Langerz82** [comment]
TODO: Make Remove Curse only dispell targets Curse.

**Comment by Langerz82** [comment]
Here is a patch for testing. It makes allot of changes so there may be bugs. Needs testing thoroughly with all aura spells as it makes logic adjustments to them.

See:
https://gist.github.com/Langerz82/3ff58eb6b82a6bfd1e3e21cb55bd22c0

**Comment by Langerz82** [comment]
hang on some bugs working out still.

**Comment by Langerz82** [comment]
ok, ready for testing. Only briefly tested do NOT use on production servers as there may be memory leaks and/or unnecessary processing overhead.

**Comment by Langerz82** [comment]
i just noticed setting stackamount is way incorrect. Will fix soon tm. lol

**Comment by Langerz82** [comment]
Let the errors I mean testing begin! Ha

**Comment by Langerz82** [comment]
AoE's like Blizzard dont seem to be working for me with this patch, I think. Can someone else test it too?

**Comment by Cillez** [comment]
Blizzard and Volley seems to be bugged from that patch. Only other spell i could think of is shadowfury for warlocks, but thats working fine.

**Comment by Langerz82** [comment]
I think that the following is causing the targeted AoE's not to work. Could be wrong test without it.

```diff
diff --git a/src/server/game/Spells/Auras/SpellAuras.cpp b/src/server/game/Spells/Auras/SpellAuras.cpp
index 142e6f8b4e..c15fcbd540 100644
--- a/src/server/game/Spells/Auras/SpellAuras.cpp
+++ b/src/server/game/Spells/Auras/SpellAuras.cpp
@@ -728,9 +728,8 @@ void Aura::UpdateTargetMap(Unit* caster, bool apply)
             {
                 // aura is already applied, this means we need to update effects of current application
                 itr->first->_UnapplyAura(aurApp, AURA_REMOVE_BY_DEFAULT);
+                itr->first->_CreateAuraApplication(this, itr->second);
             }
-
-            itr->first->_CreateAuraApplication(this, itr->second);
             ++itr;
         }
     }
```

**Comment by Langerz82** [comment]
Blizzard is bugged for the revision:
TrinityCore rev. 2e6100919d77 2018-06-25

It's unrelated to this patch.

**Comment by Langerz82** [comment]
Is this patch working and fix the issues?

See:
https://gist.github.com/Langerz82/3ff58eb6b82a6bfd1e3e21cb55bd22c0

**Comment by jackpoz** [comment]
@Langerz82 please open a PR when posting C++ changes

**Comment by Langerz82** [comment]
I had trouble in the past making branches as my base was a mess. I'll give it another try soon. ^-^
