### ISSUE TITLE
subscript operator

### ISSUE THREAD

**Issue by not-wlan** [TrinityCore/TrinityCore#22064]
https://github.com/TrinityCore/TrinityCore/blob/b8e88cd887eb1c9b922832c55d012f30902d8d79/src/common/Cryptography/OpenSSLCrypto.cpp#L29

https://github.com/TrinityCore/TrinityCore/blob/b8e88cd887eb1c9b922832c55d012f30902d8d79/src/common/Cryptography/OpenSSLCrypto.cpp#L31

is the subscript operator intended here? the .at() method will throw if the index is out of range which is admittedly unlikely but still better than accessing invalid memory :)

**Comment by Treeston** [comment]
do you have any reason to assume that the method would be called with an invalid `type` param?

**Comment by Shauren** [comment]
This is safe. (would be a bug in openssl library otherwise)
