### ISSUE TITLE
Eye of Archerus Script not working correctly

### ISSUE THREAD

**Issue by Addra** [TrinityCore/TrinityCore#22060]
**Description:**
Quest: http://www.wowhead.com/quest=12641/death-comes-from-on-high
NPC: http://www.wowhead.com/npc=28511/eye-of-acherus

Script does not work correctly, the Eye of Acherus is to slow and the Spell [Eye of Acherus Flight (Boost)](http://de.wowhead.com/spell=51923/eye-of-acherus-flight-boost) is being cast on the Player instead of the controlled NPC

**Branch:** 3.3.5 (master branch possible too)

**TC rev. hash/commit:**
TrinityCore rev. 718742005c3b 2018-06-17 17:03:10 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** 335.64
**Operating system:** Ubuntu 18.04

**Comment by rockz1152** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20843 ?

**Comment by Addra** [comment]
Is include
