### ISSUE TITLE
[Master] DB/Quest: Palm of the Tiger Quest

### ISSUE THREAD

**Issue by oXL0C0Xo** [TrinityCore/TrinityCore#22067]
**Description:**

Palm of the Tiger Quest is offered to classes other than Monk.

**Current behaviour:**

In Northshire Valley starting a human Paladin, the NPC Bao gives Monk quest "Palm of the Tiger".

**Expected behaviour:**

Quest should be available to Monk class only.

**Steps to reproduce the problem:**

Start a new character and get to level 2. I started a Paladin, have not tested other classes yet.

**Branch(es):**

master

**TC rev. hash/commit:** 

b8e88cd887eb

**Operating system:**

Server : Ubuntu Server 17.10
Client : Windows 10 Pro 1803

**Comment by ZenoX92** [comment]
Wasn't this quest removed in Legion?
https://wow.gamepedia.com/Quest:Palm_of_the_Tiger

**Comment by voarsh2** [comment]
I can confirm I ran into this problem.

I don't get offered any quests afterwards

**Comment by voarsh2** [comment]
I also see issues with Pandaren, Monk class. I don't even get the first quest assigned to me.

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/commit/064ff56a29331e490c5b8b038473c310115a6a1f
