### ISSUE TITLE
Priest [Inner fire] Spell

### ISSUE THREAD

**Issue by btechn01** [TrinityCore/TrinityCore#22074]
**Description:**

Priest spell - [Inner fire] lose stacks even though shielded by [power word: shield]

**Expected behaviour:**

Stacks should only be removed if hero actually take damage

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

35ba5aa

**Operating system:** Windows 10

**Comment by Keader** [comment]
Can be handled by spell_proc table/system.
But we need some prof that should not proc when get absorb.

**Comment by AByakugans** [comment]
"Can be handled by spell_proc table/system." How exactly and what proof?

**Comment by Aokromes** [comment]
no answer after a lot of time, if you have a PROFF of this must be like this post it and i will reopen it.

**Comment by illfated** [comment]
"proof" - but OK. We get your meaning.

**Comment by Demonid** [comment]
@Aokromes Check this out, this video is from 2009, pretty sure its from retail:

https://youtu.be/DMXM4D8vHgg?t=34

You can clearly see how Inner Fire charges drop only when PW: Shield is down, pretty sure other buffs with charges should work similar (Like Resto Shaman Shields and so)

**Comment by Jildor** [comment]
well, we can see this in wowwiki:
https://wowwiki.fandom.com/wiki/Inner_Fire
>Patch 1.10.2 (02-May-2006): Rank 3 will no longer have charges consumed when Power Word: Shield is active.

So probably shouldn't consume charges with absorb effects, what do you think @keader ??

**Comment by Jildor** [comment]
this issue seems related with: #24402
if you test do damage with one of those weapons:
https://github.com/TrinityCore/TrinityCore/issues/19081#issuecomment-280916269

works fine (doesn't drop charges)
