### ISSUE TITLE
[3.3.5] Ahune doesn't appears

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#22071]
**Description:**

When you start gossip on gameobject go_ahune_ice_stone to summon Ahune, Ahune not appears

Boss: http://www.wowhead.com/npc=25740/ahune

**Steps to reproduce the problem:**

1. event start 1
2. gm on
3. go cre id 25697
4. get quest 11691
5. gm off
6. go to gameobject go_ahune_ice_stone
7. complete quest on gameobject
8. Start gossip on gameobject

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 98fd8d4c7489 2018-06-15 12:56:33 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on:
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

**Comment by illfated** [comment]
Confirmed on current source too, had to use the command `.npc add temp 25740` to make him appear.
Thank you for posting this, I was starting to think was the only one with this issue and that I did something wrong.
(SQL files from June 21, 2018 added to the core version below.)

TrinityCore rev. 718742005c3b 2018-06-17 17:03:10 +0200 (3.3.5 branch) (Win64, Release, Static)
Online players: 0 (max: 1)
Active connections: 0 (max: 1) Queued connections: 0 (max: 0)
Server uptime: 3 Hour(s) 49 Minute(s) 39 Second(s).
Update time diff: 51.
TC> server debug
TrinityCore rev. 718742005c3b 2018-06-17 17:03:10 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by Jildor** [comment]
Yep, maybe this is caused because npc_ahune_bunny doesn't get victim

**Comment by midiman369** [comment]
Just wanted to add that I too am experiencing the same, or similar issue with this quest (http://www.wowhead.com/quest=11955/ahune-the-frost-lord).  I am not able to find Numa Cloudsister (http://www.wowhead.com/npc=25710/numa-cloudsister) anywhere in the Slave Pens.

TrinityCore rev. 4fe5a167d298+ 2018-06-01 10:38:07 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.40
Using CMake version: 3.11.1
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by Jildor** [comment]
Yes, the problem is npc_ahune_bunny doesn't get victim
I remove this:

```diff
diff --git a/src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp b/src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp
index ffcd188c82..1538bb79f3 100644
--- a/src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp
+++ b/src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp
@@ -437,8 +437,8 @@ class npc_ahune_bunny : public CreatureScript
 
         void UpdateAI(uint32 diff) override
         {
-            if (!UpdateVictim())
-                return;
+            // if (!UpdateVictim())
+            //     return;
 
             _events.Update(diff);
```

and now boss ahune appears, but this is a very bad idea probably 😄 
@Keader can you take a look here?
