### ISSUE TITLE
Core/DataStores: heap-buffer-overflow reported by AddressSanitizer

### ISSUE THREAD

**Issue by joschiwald** [TrinityCore/TrinityCore#22085]
**Description:**

heap-buffer-overflow reported by AddressSanitizer

**Current behaviour:**

Issue reported when loading ArtifactPowerPicker.db2
https://gist.github.com/joschiwald/2e23331ac369aaf45c564a15a25254f7

**Expected behaviour:**

No issue

**Steps to reproduce the problem:**

1. Compile worldserver including AddressSanitizer (-fsanitize=address)
2. Start worldserver

**Branch(es):**

master

**TC rev. hash/commit:** 

f75b98020c1b5b264eb5a8e232c0b68c1e700250

**Operating system:** Debian 9, GCC 6.3

**Comment by Aokromes** [comment]
@joschiwald this is still a thing?

**Comment by Aokromes** [comment]
no answer after more than 1 year, closing.
