### ISSUE TITLE
taxi_path character field fails to reset after arrival at destination node

### ISSUE THREAD

**Issue by Nocturne1501** [TrinityCore/TrinityCore#22089]
**Description:**

taxi_path character field doesn't reset upon arrival, causing a teleport on relog.

**Current behaviour:**

Flying to any taxi node causes the taxi_path field for that character not to reset, even after arrival, which gives the following worldserver console error: "Player Low: ID> has too short taxi destination list, teleport to original node." The player character is then teleported to their last taxi arrival location.

**Expected behaviour:**

taxi_path should reset properly after arrival.

**Steps to reproduce the problem:**

1. Fly to any taxi node.
2. Wait to arrive at destination.
3. Relog.
4. Your character will be teleported to their destination node, regardless of where they currently are.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

029c4232a7f5

**Operating system:**

Windows 7 Ultimate

**Comment by illfated** [comment]
TrinityCore rev. 029c4232a7f5 2018-06-23 22:57:44 +0200 (3.3.5 branch) (Win64, Release, Static)
```
2018-06-24_23:32:05 ERROR [entities.player] Player::LoadFromDB: Player (GUID Full: 0x0000000000000001 Type: Player Low: 1) has too short taxi destination list, teleport to original node.
2018-06-24_23:32:21 ERROR [mmaps] Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
2018-06-24_23:32:21 ERROR [mmaps] Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
2018-06-24_23:32:38 ERROR [mmaps] Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
2018-06-24_23:32:38 ERROR [mmaps] Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:30, y:30 (mmap rep.: x:30, y:30)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:30, y:28 (mmap rep.: x:30, y:28)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:29, y:28 (mmap rep.: x:29, y:28)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:29, y:30 (mmap rep.: x:29, y:30)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:31, y:28 (mmap rep.: x:31, y:28)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:31, y:29 (mmap rep.: x:31, y:29)
2018-06-24_23:35:35 ERROR [mmaps] Could not load MMAP name:Scarlet Monastery, id:189, x:31, y:30 (mmap rep.: x:31, y:30)
```
(I know, the Mmap "errors" are not real errors, they are just info which can be ignored. My log level is set to `1 - (Trace)` though.)

**Comment by WOW-Reborn** [comment]
Confirm still happening with 5cdb53896f89+ for me it seems to be affecting mainly one player using a paladin.

**Comment by Nocturne1501** [comment]
A hack to fix this is to comment out lines 17318 and 17319 in core/src/server/game/Entities/Player/Player.cpp

**Comment by illfated** [comment]
So if you want to remove lines 17318 and 17319 (still a hack), it would look like this?
```diff
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 266adf32dd..8b15ef1950 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -17313,12 +17313,10 @@ bool Player::LoadFromDB(ObjectGuid guid, SQLQueryHolder *holder)
             m_taxi.ClearTaxiDestinations();
         }
 
         if (uint32 node_id = m_taxi.GetTaxiSource())
         {
-            // save source node as recall coord to prevent recall and fall from sky
-            TaxiNodesEntry const* nodeEntry = sTaxiNodesStore.LookupEntry(node_id);
             if (nodeEntry && nodeEntry->map_id == GetMapId())
             {
                 ASSERT(nodeEntry);                                  // checked in m_taxi.LoadTaxiDestinationsFromString
                 mapId = nodeEntry->map_id;
                 Relocate(nodeEntry->x, nodeEntry->y, nodeEntry->z, 0.0f);
            }

            // flight will started later
        }
    }
```

**Comment by Nocturne1501** [comment]
@illfated hm, looks like my file is a little bit different. Apologies!
Look up the line that contains "too short taxi destination". Comment out (put // before) the two lines directly under it.

**Comment by illfated** [comment]
OK, so you are talking about lines 17310 + 17311 on current source,
TrinityCore rev. 59edf6b100a9 2018-08-11 19:12:48 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
```diff
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 266adf32dd..e63a8b501b 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -17305,12 +17305,12 @@ bool Player::LoadFromDB(ObjectGuid guid, SQLQueryHolder *holder)
                 RelocateToHomebind();
             }
             else                                                // has start node, teleport to it
             {
                 TC_LOG_ERROR("entities.player", "Player::LoadFromDB: Player (%s) has too short taxi destination list, teleport to original node.", GetGUID().ToString().c_str());
-                mapId = nodeEntry->map_id;
-                Relocate(nodeEntry->x, nodeEntry->y, nodeEntry->z, 0.0f);
+                // mapId = nodeEntry->map_id;
+                // Relocate(nodeEntry->x, nodeEntry->y, nodeEntry->z, 0.0f);
             }
             m_taxi.ClearTaxiDestinations();
         }
 
         if (uint32 node_id = m_taxi.GetTaxiSource())
```
(I haven't tested it myself, so I have no idea of the consequences.)

**Comment by Nocturne1501** [comment]
Yes, this is the hack I use for my server. No negative consequences, at least not as far as I can tell.

**Comment by TerrorBringer** [comment]
This issue happens to my paladin aswell.

Rev 073ba8e

**Comment by illfated** [comment]
I have not tested this theory myself, but I think this issue mostly happens with GM or admin characters who use the teleport command `.tele <destination>` to move around in the game. Feel free to test and report back if this happens to a non-GM character who is not teleported around by a GM (or admin) character, only using in-game teleports, mage portals and transports.

**Comment by Nocturne1501** [comment]
@illfated Nope, on my server several different players reported this happening to their characters, and I never teleport anybody around for any reason, which is why I had to implement the hack.

**Comment by illfated** [comment]
Very well, then. Thanks for confirming that it happens regardless of character security level.

How similar or different is this issue compared to [**Character Rollback to Previous Location upon Logout**](https://github.com/TrinityCore/TrinityCore/issues/22234) #22234 ?

**Comment by Nocturne1501** [comment]
Not at all, from what I could tell. I've never seen that particular error message in my server log.

**Comment by illfated** [comment]
Fair enough. That leaves only the end result, character logging in has been reset to the previously saved location (which in issue #22234 only applies to paladins).

This issue is about Taxi path end not being saved in some scenarios, whereas the other issue is about paladin auras causing the last saved character position not to be saved.

**Comment by illfated** [comment]
To any of the TC developers and users with useful experience with TC core & DB: is there any recommended log we should turn on to log what goes wrong in character save, so we could start testing and reporting what could actually be the cause of this kind of issues?
