### ISSUE TITLE
[master] DB/Scaling Update creature_template_scaling (Northrend)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#22095]
**Description:**

Filling Northrend scaling data:

https://gist.github.com/funjoker/9fac0e76baeab0e027f47694f4576896

**Branch(es):**

master

**TC rev. hash/commit:** 

5b4cc687233e1eb53b9456e7eac7a840016a49e8

**Comment by joschiwald** [comment]
we already have some of them in our database

enabled database connection and set SQLOrderByKey to true in WPP please

**Comment by funjoker** [comment]
Copied wrong link. sorry...

**Comment by Shauren** [comment]
yeah, levels below 60 were sort of suspicious
