### ISSUE TITLE
[3.3.5] Priest: Power Word: Shield

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#22090]
**Description:**

ID - 17 Power Word: Shield (Rank 1)
spell_pri_power_word_shield
https://github.com/TrinityCore/TrinityCore/blob/16f524ff2537646417d1150ef3bdab8e4cc8a2b1/src/server/scripts/Spells/spell_priest.cpp#L1021-L1022

This part of absorb script is wrong, because Focused Power isn't the only one that has this effect (SPELL_AURA_MOD_HEALING_DONE_PERCENT).

By example, Power Word: Shield is affected by ICC buff (the result is correct, but ICC buff should be fixed (https://github.com/TrinityCore/TrinityCore/issues/21415))
And maybe another auras with SPELL_AURA_MOD_HEALING_DONE_PERCENT are affecting, so this script need a better check.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 98fd8d4c7489 2018-06-15 12:56:33 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on:
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

**Comment by Warpten** [comment]
That's litterally just a comment

**Comment by Jildor** [comment]
See this commit: https://github.com/TrinityCore/TrinityCore/commit/2202c4fa9771428a225ba4f11bf3824511cbbc18

Here only affect to Focused Power, not all SPELL_AURA_MOD_HEALING_DONE_PERCENT Auras

**Comment by Keader** [comment]
```caster->GetTotalAuraMultiplier(SPELL_AURA_MOD_HEALING_DONE_PERCENT);``` will get all auras with 
```SPELL_AURA_MOD_HEALING_DONE_PERCENT``` Jildor, not just Focused power.

**Comment by Keader** [comment]
we have some list, of what should affect it?
Btw, i miss you ariel !! haha

**Comment by Keader** [comment]
@joschiwald do you remember about it?
Looks like is your script (https://github.com/TrinityCore/TrinityCore/commit/c38d95ac33e44ea30908b5d8e8707848094dd5f0)

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/617e9dacc8c7b87b7ed292eb200aef1a569609e8
