### ISSUE TITLE
[master] DB Northrend Gossip

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#22097]
**Description:**

https://gist.github.com/funjoker/635df16fddfc993aee771fbbe8a0bb58
https://gist.github.com/funjoker/1c3d31ea334826665ce0a1d70592f747

**Branch(es):**

master

**TC rev. hash/commit:** 

5b4cc687233e1eb53b9456e7eac7a840016a49e8

**Operating system:** Win 10

**Comment by joschiwald** [comment]
parse multiple sniff files in one run to get pretty concatenated output

**Comment by funjoker** [comment]
WPP gives allways 1 output from each file anyway.
And Fusion.pkt kills gossip parsing atm.

**Comment by Killyana** [comment]
I didn't forget this, it need deeper cleaning as gossips are involved in many scripts, and lot of this must also be pushed to 3.3.5, I started working on it, I will finish it after spawning Twilight Highlands area.
