### ISSUE TITLE
[3.3.5] Hunter: Spell Aimed Shot

### ISSUE THREAD

**Issue by r0m1ntik** [TrinityCore/TrinityCore#22109]
**Description:**

Aimed Shot http://www.wowhead.com/spell=38861/aimed-shot
Does not update the aura if already hanging on a target.
Aura ID: 49050

Video: https://streamable.com/9o54z

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

TrinityCore rev. 98fd8d4 2018-06-15 12:56:33 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l 25 May 2017 (library: OpenSSL 1.0.2l 25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2

**Comment by tje3d** [comment]
related #21635?

**Comment by r0m1ntik** [comment]
@tje3d Yes

**Comment by Keader** [comment]
Duplicated #21635
