### ISSUE TITLE
MysqlTypeToField replacement.

### ISSUE THREAD

**Issue by Langerz82** [TrinityCore/TrinityCore#22118]
**Description:**

Changed method MysqlTypeToField.diff
I profiled it both ways and this one runs faster.

See:
https://gist.github.com/Langerz82/0d87270bb1096f0c4550204f7ebe87bf

**Current behaviour:**

MysqlTypeToField() uses a large switch and too many conditionals.

**Expected behaviour:**

Uses Map to find out which datatype is appropriate

**Steps to reproduce the problem:**

1. Profile current way check execution time.
2. Apply patch then check execution time.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 2e6100919d77+ 2018-06-25 00:42:30 +0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**Operating system:**  Win 10

**Comment by Lordron** [comment]
how it can be faster than switch?

**Comment by Rochet2** [comment]
https://ideone.com/zjCb57

> Success	#stdin #stdout 1.3s 4376KB
repetitions: 100000000
old: 0
new: 1295
milliseconds

According to this the map is infinitely slower than the old switch.

**Comment by Shauren** [comment]
Yeah, there is no way map can be faster - also this breaks my include cleanup (windows headers must not be included in a header)

**Comment by Langerz82** [comment]
I tested this in codeXL and it was about 150ms faster during server boot, its strange that your test case shows 0ms Rochet2 sure it aint bugged? lol

**Comment by Seyden** [comment]
It probably shows 0 because the time it needed is so small that it was below 1 ms.. but yeah like the others said.. it's not possible, that a lookup table is faster than a switch

**Comment by Langerz82** [comment]
It's so strange, I'll test both in runtime of the boot process and report the results.

**Comment by Langerz82** [comment]
See, like I said the New function is reported as faster in CodeXL, wonder what is causing this.. Could be a windows compiler issue.

https://ibb.co/fnePxJ

**Comment by Langerz82** [comment]
I feel so dumb lol, the CodeXL's Call Graph is what I should of looked at:
https://ibb.co/fiKUWd

Thanks guys for the feedback.
