### ISSUE TITLE
[master] Update Spelltarget

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#22115]
**Description:**

No idea if they are legit.
data taken from sniffs

https://gist.github.com/funjoker/0bfe9b9e9ff90f04110768efe035bb26

**Branch(es):**

master

**TC rev. hash/commit:** 

c2d61e05cf3dc555608e6b2a06772c27d207548c

**Comment by Killyana** [comment]
This is wrong the map must be 0 as the quest is on Redridge Mountains http://www.wowhead.com/quest=26616/its-never-over
``` sql
UPDATE `spell_target_position` SET `MapID`=1, `VerifiedBuild`=25881 WHERE (`ID`=81243 AND `EffectIndex`=0);
