### ISSUE TITLE
[3.3.5] Spell Reflection

### ISSUE THREAD

**Issue by r0m1ntik** [TrinityCore/TrinityCore#22111]
**Description:**

[Spell Reflection](http://www.wowhead.com/spell=23920/spell-reflection) does not fall off when you remove the shield.

Video: https://streamable.com/q248y

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

TrinityCore rev. 98fd8d4 2018-06-15 12:56:33 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l 25 May 2017 (library: OpenSSL 1.0.2l 25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2

**Comment by Jildor** [comment]
Duplicated: #21594
