### ISSUE TITLE
Testing Item Query Locale combined

### ISSUE THREAD

**Issue by Langerz82** [TrinityCore/TrinityCore#22126]
**Description:**

I noticed the Item Query Data runs a bit slow, and in searching through the code I noticed that we have an WorldPacket object for each Locale which I dont think is needed.
So I went about making a Locale Arrays for item name & description that holds the 9 languages and this is what I came up with:
https://gist.github.com/Langerz82/c769f2b56e982e791f13f309ab6daec1

old method profile:
https://ibb.co/gho9Wd

new method profile:
https://ibb.co/gja6Bd

edit:
This needs to be test on non-US clients to make sure everything works fine.

**Current behaviour:**

Server instantiates a WorldPacket for each ItemTemplate locale.

**Expected behaviour:**

Server instantiates one WorldPacket for each ItemTemplate.

**Steps to reproduce the problem:**

1. Apply Patch
2. Use Profiler

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 2e6100919d77 2018-06-25 00:42:30 +0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**Operating system:** Win 10

**Comment by Langerz82** [comment]
If this is good I can do the other ones too.

**Comment by Shauren** [comment]
This is not good at all, what you are doing here is removing locales entirely and always sending enUS

**Comment by Langerz82** [comment]
I just need a method to update the locale when the packet is sent then. This has a significant boost in startup performance so please dont disclude it just cause it's currently bugged.

**Comment by Shauren** [comment]
What you are proposing is either updating global state (terrible design idea, can never be fast & threadsafe) or making a copy (completely removing the point of cache). On top of that this is an OPTIONAL feature that can be turned off in config for development

**Comment by Langerz82** [comment]
I'll try and code it so cache is preserved still.

**Comment by Langerz82** [comment]
Here is what I got, does it work on non-US locales? It's meant too.
I'm not positive it's thread safe either, though I tried to make it so.

See:
https://gist.github.com/Langerz82/23ae52a6e4d098b7a735e0f728a277b2

**Comment by Shauren** [comment]
reflect.diff? doesnt look related to this

**Comment by Langerz82** [comment]
I got a problem the Quests arent tracking with my changes. :( When I fix it ill submit.

**Comment by Langerz82** [comment]
Memory corruption due to not passing the LocaleConstant properly. :D

**Comment by Langerz82** [comment]
I'm going to scrap my changes, it adds additional complexity, runs faster at boot, and at runtime is probably a bit slower since it cant use the packet cache feature. Here it is for reference.

See:
https://gist.github.com/Langerz82/7cf94b65c7bcfedf6e9256067d9991c4

**Comment by Langerz82** [comment]
What if we created the users default locale QueryData, and created the others as requested during run-time? Just an idea, I think it could work with some changes to my code I made.
That way caching would work and it would have fast-loading times still, and a smaller memory footprint unless of course u have many locales playing during run-time.

**Comment by Langerz82** [comment]
Here is a prototype of what I mean, it still has a couple bugs such as the tracker corrupting and the reward item names not appearing.

See:
https://gist.github.com/Langerz82/0dec4a73c1d190858a42bca97fdfd890

**Comment by Langerz82** [comment]
I wouldnt waist the others time yet in reviewing it until its completely threadsafe, and working properly. It might need a config value too in case the server owner wants to disable processing packet languages during runtime.
And if it's ok I'll have to do some of the other templates as well. But it's looking promising.

**Comment by Langerz82** [comment]
Ok, ready for testing this patch only applies to QuestTemplates so far:

Patch described here:

> What if we created the users default locale QueryData, and created the others as requested during run-time? Just an idea, I think it could work with some changes to my code I made.
That way caching would work and it would have fast-loading times still, and a smaller memory footprint unless of course u have many locales playing during run-time.

See:
https://gist.github.com/Langerz82/9582293b4ffd8481488c61efb1928f7f
