### ISSUE TITLE
[3.3.5] DB/Quest: Seared Scourge (daily)

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22129]
**Description:**
quest Seared Scourge (daily) is missing it's prequest, can be picked up on arrival at Granite Springs and completed alongside the non-daily version

```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=12029 WHERE `ID`=12038;
```

**Branch(es):**
3.3.5

TC rev. hash/commit:
TC rev. 8a7fdbd
TDB version 335.64

**Comment by illfated** [comment]
Title suggestion: **[3.3.5] DB/Quest: Seared Scourge (daily)**

Links:
- https://wow.gamepedia.com/Quest:Seared_Scourge_(Daily)
- http://www.wowhead.com/quest=12038/seared-scourge
- https://wow.gamepedia.com/Quest:Seared_Scourge
- http://www.wowhead.com/quest=12029/seared-scourge
