### ISSUE TITLE
[3.3.5] DB/quest: Engineering Membership Renewals

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22134]
**Description:**
Membership Renewal quests should have a 2g fee to renew the card, currently you can spam accept these quests and sell the rewards 24 hours later.
In addition the membership cards and renewal quests were removed around 3.1.

```sql
-- Engineering memberships
UPDATE `quest_template` SET `RewardMoney`='-20000', `LogDescription`='In order to renew your membership card, you will need to pay the renewal fee of two gold pieces.' WHERE `ID` IN (3644,3645,3646,3647);

DELETE FROM `disables` WHERE `sourceType` = 1 and `entry` IN (3644,3645,3646,3647);
INSERT INTO `disables` (`sourceType`,`entry`, `comment`) VALUES
(1, 3644, `Depracted quest`),
(1, 3645, `Depracted quest`),
(1, 3646, `Depracted quest`),
(1, 3647, `Depracted quest`);
```

**Branch(es):**
3.3.5

TC rev. hash/commit:
TC rev. 8a7fdbd
TDB version 335.64

**Comment by offl** [comment]
```sql
DELETE FROM `creature_queststarter` WHERE `quest` IN (3644,3645,3646,3647);
DELETE FROM `creature_questender` WHERE `quest` IN (3644,3645,3646,3647);
```
Use the `disables` table :)

**Comment by Killyana** [comment]
`LogDescription`='In order to renew your membership card, you will need to pay the renewal fee of two gold pieces.
It's the same text as:
``` sql
SELECT * FROM quest_request_items WHERE ID IN (3644,3645,3646,3647);

**Comment by Killyana** [comment]
In some cases it's better to keep information about queststarter and questender.
