### ISSUE TITLE
[3.3.5] DB/Quest: Kurzen's Mystery

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22130]
**Description:**
http://www.wowhead.com/quest=207/kurzens-mystery#comments:id=98747
Kurzen's Mystery has The Second Rebellion and Bad Medicine as prequests, but those are set as joint prequests for Special Forces.
Setting Kurzen's Mystery to just Bad Medicine.

```sql
UPDATE `quest_template_Addon` SET `PrevQuestID`=204 WHERE `ID`=207;
```

**Branch(es):**
3.3.5

TC rev. hash/commit:
TC rev. 8a7fdbd
TDB version 335.64

**Comment by illfated** [comment]
Title suggestion: **[3.3.5] DB/Quest: Kurzen's Mystery**

**Comment by Killyana** [comment]
This the actual chaining:  203+204--->574---->202----->207
As you see 204 is not a direct requirement to get 207
