### ISSUE TITLE
BG/IoC : Bosses Doors bug & Bosses missing

### ISSUE THREAD

**Issue by Maphaze** [TrinityCore/TrinityCore#22138]
**Description:**

Some bugs related to bosses and keeps of both faction (alliance & horde) in IoC.

**Current behaviour:**

There are no faction bosses in keeps
The door that allow players to access bosses is not opening the right way (not opening at all)

**Expected behaviour:**
There should be a boss in alliance keep and in the horde keep
The door that allow players to access bosses should be opened from as soon as one of the keep doors has been destroyed.

**Steps to reproduce the problem:**

1. Start a IoC BG (in debug mode) 
2. Destroy one of the ennemy keep doors using siege machine
You will see that the door to access boss is still closed
4. Activate gm mode and click on the door to open it
5. Walk to the location of the boss
You will see that the boss isn't spawned.

**Branch(es):**

3.3.5 (maybe on master, i'm not working on the master one at the moment so...)

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/076c7a7b32c0804013f24f46596fe316258bde1a

**Operating system:**
Linux/Debian 9

**Comment by jackpoz** [comment]
Does it happen even without starting a bg in debug mode ?

**Comment by Maphaze** [comment]
We still have the issue without using IoC debug mode.

**Comment by Maphaze** [comment]
Using the Visual Studio attach process feature on worldserver, I have added two breakpoints

- At `BattlegroundIC::AddPlayer`
This breakpoint is only here to check that i am correctly triggering breakpoint in attach process feature. When i entered in IoC, **this breakpoint has been triggered**.
- At `BattlegroundIC::DestroyGate`
This breakpoint should have been triggered when one of the keep doors is destroyed but **it doesn't triggered**. It seems to explain why the behing logic (opening of boss keep door & spawn of the boss isn't done).

I'm actually looking for the place where the `BattlegroundIC::DestroyGate` should be called but i have got no idea..
