### ISSUE TITLE
[3.3.5] DB/Loot: Tunnel Rat Ear

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22132]
**Description:**
Currently only 1/6 type of Tunnel Rat drops ears for the quest "Rat Catching" 

Drop rate is higher inside the cave.
http://www.wowhead.com/item=3110/tunnel-rat-ear#comments:id=353270

```sql
DELETE FROM `creature_loot_template` WHERE `Entry` in (1172,1174,1175,1176,1177) and `item` = 3110;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Chance`) VALUES
(1172, 3110, 38),
(1174, 3110, 60),
(1175, 3110, 60),
(1176, 3110, 38),
(1177, 3110, 60);
```

**Branch(es):**
3.3.5

TC rev. hash/commit:
TC rev. 8a7fdbd
TDB version 335.64

**Comment by illfated** [comment]
Title suggestion: **[3.3.5] DB/Loot: Tunnel Rat Ear**

**Comment by Killyana** [comment]
https://woehead.way-of-elendil.fr/?item=3110
``` sql  
SELECT * FROM `reference_loot_template` WHERE `item` = 3110;
SELECT * FROM `creature_loot_template` WHERE `reference` = 45008;
