### ISSUE TITLE
[3.3.5] DB/Loot: A Mangled Journal

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22131]
**Description:**
Drop rate on A Mangled Journal in Un'goro Crater is crazy low, this comment summarizes the issue well.
http://www.wowhead.com/item=11116/a-mangled-journal#comments:id=102680

```sql
UPDATE `creature_loot_template` SET `Chance`=60 WHERE `Item`=11116;
```

Drop rate is most likely supposed to be 100%, but where's the fun in that? 60% is enough.

**Branch(es):**
3.3.5

TC rev. hash/commit:
TC rev. 8a7fdbd
TDB version 335.64

**Comment by illfated** [comment]
Title suggestion: **[3.3.5] DB/Loot: A Mangled Journal**

**Comment by FireEmerald** [comment]
"crazy low" = ?%

**Comment by illfated** [comment]
I presume that is referring to the wowhead.com drop rate column, ranging from 0.80 % to 0.01 % (and even 0 %).
Then again, wowhead.com loot tables are infamous for being contaminated by loot values from not eligible players.

**Comment by PolarCookie** [comment]
@FireEmerald https://wotlk.evowow.com/?item=11116#dropped-by:0-8+1
Droprates have been blindly taken from wowhead drop tables, without reading the comment I highlighted. It's 4% on Ravasaurs and just-don't-even-bother% on the rest. It's a massive pain right now to get this item which was intended to be a very guaranteed drop, some old wowhead comments complain you get to many of them and it's annoying to throw them away all the time (especially when the book would keep dropping until you completed the quest).

**Comment by illfated** [comment]
> you get to many of them and it's annoying to throw them away all the time (especially when [it] keeps dropping until you complete the quest).

This is currently the case with the loot item Unadorned Seal of Ascension:
- http://www.wowhead.com/item=12219/unadorned-seal-of-ascension
- https://wow.gamepedia.com/Unadorned_Seal_of_Ascension


<details>

```sql
SELECT * FROM `creature_loot_template` WHERE `item`= 12219;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
 9043   12219          0      10              0         1        0         1         1  (NULL)
 9044   12219          0      10              0         1        0         1         1  (NULL)
 9045   12219          0      10              0         1        0         1         1  (NULL)
 9046   12219          0      10              0         1        0         1         1  (NULL)
 9097   12219          0      10              0         1        0         1         1  (NULL)
 9098   12219          0      10              0         1        0         1         1  (NULL)
 9196   12219          0      10              0         1        0         1         1  (NULL)
 9197   12219          0      10              0         1        0         1         1  (NULL)
 9198   12219          0      10              0         1        0         1         1  (NULL)
 9199   12219          0      10              0         1        0         1         1  (NULL)
 9200   12219          0      10              0         1        0         1         1  (NULL)
 9201   12219          0      10              0         1        0         1         1  (NULL)
 9216   12219          0      10              0         1        0         1         1  (NULL)
 9217   12219          0      10              0         1        0         1         1  (NULL)
 9218   12219          0      10              0         1        0         1         1  (NULL)
 9219   12219          0      10              0         1        0         1         1  (NULL)
 9236   12219          0      10              0         1        0         1         1  (NULL)
 9237   12219          0      10              0         1        0         1         1  (NULL)
 9239   12219          0      10              0         1        0         1         1  (NULL)
 9240   12219          0      10              0         1        0         1         1  (NULL)
 9241   12219          0      10              0         1        0         1         1  (NULL)
 9257   12219          0      10              0         1        0         1         1  (NULL)
 9258   12219          0      10              0         1        0         1         1  (NULL)
 9259   12219          0      10              0         1        0         1         1  (NULL)
 9260   12219          0      10              0         1        0         1         1  (NULL)
 9261   12219          0      10              0         1        0         1         1  (NULL)
 9262   12219          0      10              0         1        0         1         1  (NULL)
 9263   12219          0      10              0         1        0         1         1  (NULL)
 9264   12219          0      10              0         1        0         1         1  (NULL)
 9265   12219          0      10              0         1        0         1         1  (NULL)
 9266   12219          0      10              0         1        0         1         1  (NULL)
 9267   12219          0      10              0         1        0         1         1  (NULL)
 9268   12219          0      10              0         1        0         1         1  (NULL)
 9269   12219          0      10              0         1        0         1         1  (NULL)
 9568   12219          0      10              0         1        0         1         1  (NULL)
 9583   12219          0      10              0         1        0         1         1  (NULL)
 9596   12219          0      10              0         1        0         1         1  (NULL)
 9692   12219          0      10              0         1        0         1         1  (NULL)
 9693   12219          0      10              0         1        0         1         1  (NULL)
 9716   12219          0      10              0         1        0         1         1  (NULL)
 9717   12219          0      10              0         1        0         1         1  (NULL)
 9718   12219          0      10              0         1        0         1         1  (NULL)
 9736   12219          0      10              0         1        0         1         1  (NULL)
10584   12219          0      10              0         1        0         1         1  (NULL)
```
</details>

***
Fair enough that it should be easy to acquire the quest item in time to meet the quest giver, but it keeps dropping after taking the quest http://www.wowhead.com/quest=4742/seal-of-ascension from Vaelan (https://woehead.way-of-elendil.fr/?npc=10296). I must have destroyed and re-looted it 20 times or more when soloing LBRS on TC. (Yes, I know, I could have left it unlooted, but I prefer to see consistent corpse despawns.) Anyway, I think it should stop dropping for a player when the quest is taken, even if it is supposed to drop at least once for all members in a vanilla-style raid before taking the quest.

TC>server debug
TrinityCore rev. 16f524ff2537 2018-06-26 20:17:59 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.38
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
