### ISSUE TITLE
Frostbolt uses lower rank versions of itself on lower level mobs

### ISSUE THREAD

**Issue by Nocturne1501** [TrinityCore/TrinityCore#22153]
**Description:**

Using mage's Frostbolt spell on targets that are too low level (for example, >20 levels below the mage) causes the game to downrank the spell and cast a lower rank version. This can easily be tested by giving a character the highest rank of frostbolt, then using it on a level 1 enemy. The frostbolt fired will be rank 2 (estimate).

**Current behaviour:**

**Expected behaviour:**

The actual rank used should be used with the spell, i.e. if rank 7 is used, rank 7 should be fired, not a downranked version.

**Steps to reproduce the problem:**

Simply fire a high-rank frostbolt at a target of a much lower level than the mage firing it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b68a4e2b8e16 2018-06-28 03:17:42 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**

Ubuntu 18.04 LTS

**Comment by kvipka** [comment]
confirm

it related with this line : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/SpellHandler.cpp#L407

i think there are should be:
`if (targets.GetUnitTarget() && targets.GetUnitTarget()->IsFriendlyTo(caster))`

**Comment by Treeston** [comment]
Can reproduce on latest
