### ISSUE TITLE
[3.3.5] Core/Spells: Shadow of Death & Spiritual Vengeance should be negative spells

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#22160]
**Description:**

Boss: http://www.wowhead.com/npc=22871

Auras:
ID - 40268 Spiritual Vengeance
ID - 40251 Shadow of Death

Should be debuffs, now are buffs and can be removed by right click

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 2ef331584868 2018-07-11 18:14:09 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on: Linux 4.9.0-4-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

**Comment by Keader** [comment]
Jildor, check : https://github.com/TrinityCore/TrinityCore/commit/5fa783bd34d8e5b32aded6b87a1e4b196b7c4022
And add spells there

**Comment by illfated** [comment]
Suggestion for a possible title for this issue:
**[3.3.5] Core/Spells: Shadow of Death & Spiritual Vengeance should be negative spells**

**Comment by Jildor** [comment]
Done ;)

**Comment by Keader** [comment]
e114939071fe0aa09491c2f4ebbb3cf4f3aa5fd9
