### ISSUE TITLE
[3.3.5] BlackTemple/Teron Gorefiend: Crash spell Spiritual Vengeance

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#22161]
**Description:**

Boss: http://www.wowhead.com/npc=22871

Crashlog: https://gist.github.com/Jildor/7d11c61c2bcc18718713431204a85b0f

Hi @Keader 

**Steps to reproduce the problem:**

1. Start encounter with boss Teron Gorefiend
2. Get aura Spiritual Vengeance
3. When you cancel aura in the action bar or remove buff by right click (should be a debuff, issue: https://github.com/TrinityCore/TrinityCore/issues/22160) crash.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 2ef331584868 2018-07-11 18:14:09 +0200 (3.3.5 branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.62.0
Using MySQL version: 10.1.26-MariaDB
Using CMake version: 3.7.2
Compiled on: Linux 4.9.0-4-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/335/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/trinity/data/335/data/vmaps. Total size: 588247501 bytes
mmaps directory located in /home/trinity/data/335/data/mmaps. Total size: 2152621156 bytes
Using esES DBC Locale as default. All available DBC locales: esES
Using World DB: TDB 335.64

**Comment by Keader** [comment]
Sirikfoll failed in try reproduce it.
Btw, maybe caused by: https://github.com/TrinityCore/TrinityCore/commit/c9b09fc2cbba9ec8bda124b73bd081581e7bfadc ?

**Comment by illfated** [comment]
I presume you mean
https://github.com/TrinityCore/TrinityCore/blob/2ef33158486831aa061050f5cc7d316fee17721d/src/server/scripts/Outland/BlackTemple/boss_teron_gorefiend.cpp#L396
and that you removed it in case it caused the crash.

Jildor should test with your change in commit https://github.com/TrinityCore/TrinityCore/commit/c9b09fc2cbba9ec8bda124b73bd081581e7bfadc and see if the crash is gone now.

**Comment by Jildor** [comment]
Easy to reproduce it fast:
1. .aura 40251
2. wait to finish aura and get aura ID - 40268 Spiritual Vengeance
3. cancel Spiritual Vengeance in action bar or remove buff
4. crash

And happens after https://github.com/TrinityCore/TrinityCore/commit/c9b09fc2cbba9ec8bda124b73bd081581e7bfadc

**Comment by Jildor** [comment]
With this I can't reproduce crash: https://github.com/TrinityCore/TrinityCore/pull/22164

**Comment by illfated** [comment]
Possibly, your crash log references `spell_teron_gorefiend_spiritual_vengeance::OnRemove` in backtrace line `#7` :
https://gist.github.com/Jildor/7d11c61c2bcc18718713431204a85b0f#file-crash_spell_teron_gorefiend_spiritual_vengeance-log-L14
which points to line 390 in
https://github.com/TrinityCore/TrinityCore/blob/2ef33158486831aa061050f5cc7d316fee17721d/src/server/scripts/Outland/BlackTemple/boss_teron_gorefiend.cpp#L388-L391

**Comment by Keader** [comment]
e114939071fe0aa09491c2f4ebbb3cf4f3aa5fd9
