### ISSUE TITLE
[3.3.5][Optimization] ByteBuffer using dynamic arrays instead of vectors.

### ISSUE THREAD

**Issue by Langerz82** [TrinityCore/TrinityCore#22163]
**Description:**

ByteBuffer uses vectors which can consume more memory than needed and have more overhead compared to dynamic arrays. This patch suggestion is to use dynamic arrays.
From my preliminary tests it looks to be saving around 1GB of ram when booted and is much faster at booting up and at generating packets.
I will provide a patch probably later today for testing.

**Current behaviour:**
Vectors are used in ByteBuffer
Well my patch atm crashes at random points, when I have some degree of stability will post the patch.

**Expected behaviour:**
The Server running fast and smooth.

**Steps to reproduce the problem:**

1. Run the Server and watch it boot slow and consume more memory than is needed.

**Branch(es):**

3.3.5, maybe master too.

TrinityCore rev. 2ef331584868+ 2018-07-11 18:14:09 +0200 (3.3.5 branch) (Win64, Debug, Static) 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Win 10

**Comment by jackpoz** [comment]
The 1GB is with caching enabled, right ? Is there any difference when the caching is disabled ?

**Comment by Langerz82** [comment]
right, It will be less with caching disabled as there will be less bytebuffers no doubt.

**Comment by Langerz82** [comment]
See:
https://gist.github.com/Langerz82/a147c512e7867f8e1156c2edcd8c2238

Note - It does not work currently. The packets usually at request Item response is corrupted. I think it may be something pushing them out of alignment but im not too sure yet.

**Comment by Langerz82** [comment]
worked it out, one the assignment operators was not copying the data across leading to memory corruption.

```
        ByteBuffer& operator=(ByteBuffer&& right)
        {
            if (this != &right)
            {
                _rpos = right._rpos;
                right._rpos = 0;
                _wpos = right._wpos;
                right._wpos = 0;
                maxSize = right.maxSize;
                //_storage = right._storage;
                if (maxSize > 0)
                {
                    _storage = DBG_NEW uint8[maxSize];
                    if (_wpos > 0)
                        std::memcpy(_storage, right._storage, _wpos);
                }
            }
            return *this;
        }
```

Will submit the corrected patch gotta test it a bit more though.

**Comment by Shauren** [comment]
pointless.
just call shrink_to_fit on the internal vector for cache packets

**Comment by Rochet2** [comment]
Here are some stats with caching enabled:
```
Initialize query data...
total _storage.size(): 304592819
total _storage.capacity(): 1411757354
totaladditionalreserves: 0
totaladditionalresizes: 0
usagepct: 0.215754

after shrink to fit
total _storage.size(): 304592819
total _storage.capacity(): 304592819
usagepct: 1.000000
```
For c9b09fc2cbba9ec8bda124b73bd081581e7bfadc
With https://gist.github.com/Rochet2/2318025dfd9a9433d08b48e5fe97c746

1411757354-304592819 uint8 = 1107164535 bytes ~= 1.1 gigabytes
Indeed it seems that currently 1GB is wasted when cache is on.

**Comment by Langerz82** [comment]
not to mention dynamic arrays is much faster because we can internally control the way it's resized and copied when resizing.

**Comment by Langerz82** [comment]
Ready for testing: https://gist.github.com/Langerz82/a147c512e7867f8e1156c2edcd8c2238

I'll test boot times and what not and do some proper tests to show if it's not only a smaller footprint but faster execution times.

**Comment by Langerz82** [comment]
The problem is to show it is indeed more efficient I have to run it in debug mode to show you the amount of hits resizing vectors do internally which slows down execution time considerably.

**Comment by Warpten** [comment]
The only possible memory hit you can see from a vector is if capacity > size.

The only possible speed hit you can see from a vector is resizes (reduction is a no-op) or construction (because the backing array is initialized to default values).

**Comment by Langerz82** [comment]
The dynamic array seems to run allot faster than std::vector. The new operator is relevant here in the third link because the new ByteBuffer uses it to create resized arrays. If we tweak the resizing number on this, I'd expect it to run even quicker. 
Granted we can use reserve, resize, and shrink_to_fit but that will be more overhead.
For something as integral as the ByteBuffer that's used for packet processing I think this deserves some serious consideration.

Diagnostics on functions:
https://ibb.co/mKsgZJ
https://ibb.co/kGNgZJ
https://ibb.co/i0YYgy

**Comment by Langerz82** [comment]
Perhaps ill write up a test processing lots of packets and see if it makes any real difference. I spent allot of time trying to debug the changes so I guess I was too invested in the changes and not aware of the shrink_to_fit and it's real performance.

**Comment by Langerz82** [comment]
The test:
https://gist.github.com/Langerz82/88509ede00dfb8b990713044c7b99a63

The results:
```
10.944 | 10.974 | 11.32   |  
30.439 | 31.586 | 30.157 |  
41.455 | 41.34   | 41.699 |  
50.323 | 48.571 | 51.137 |  
44.091 | 44.255 | 46.834 |  
32.011 | 29.122 | 29.555 |  
30.221 | 31.375 | 30.711 |  
29.235 | 27.206 | 25.902 |  
24.225 | 26.588 | 19.544 |  
24.702 | 26.459 | 23.608 |  
27.255 | 27.489 | 29.385 |  
23.2     | 18.98   | 20.626 |  
27.105 | 29.671 | 26.855 |  
28.689 | 27.171 | 27.831 |  
22.283 | 22.717 | 21.286 |  
25.445 | 24.659 | 27.461 |  
29.344 | 25.642 | 30.711 |  
19.4     | 19.023 | 18.861 |  
20.713 | 21.02   | 18.979 |  
34.97   | 34.62   | 34.009 |  
22.957 | 22.797 | 22.6645 | ← Averages
```

**Comment by jackpoz** [comment]
I'd say to use the shrink_to_fit in the meantime this PR gets reviewed

**Comment by Shauren** [comment]
This is totally not what I'm seeing. I actually took time to run this myself
Results were as expected, TC version lost in debug mode (only by 60%, debug checks inside vector itself) but won BY LARGE MARGIN in release (more than 200% faster in 86 bit, 400% in 64 bit)

I edited your benchmark code to construct each ByteBuffer array inside ` for (int n = 0; n < 20; ++n)` loop to avoid growing it on every iteration (which btw gave me results were TC version was 16000% faster on the final run)

![bytebuffer](https://user-images.githubusercontent.com/297439/42841971-061693e8-8a0c-11e8-80df-30a013a9b5bb.png)

**Comment by ccrs** [comment]
in conclusion having reserve is way better than allocating new space when needed.
but, is the shrink_to_fit thing still viable?

**Comment by Shauren** [comment]
yes

**Comment by Langerz82** [comment]
Calling reserve is CHEATING the test. I can make a simple reserve function in the Dynamic Arrays and it outperforms the old class (almost 70% in debug mode, and around 20-30% for release mode for x64).

Test:
https://gist.github.com/Langerz82/e46204b0212a2e8ab63d74095d04aacf

New Byte Buffer:
https://gist.github.com/Langerz82/9ca298d9b8a7dacd7535b045527fc0ff
https://gist.github.com/Langerz82/e3f4bf3d642ccfce6b5cf47ef7baf91e

**Comment by jackpoz** [comment]
> almost 70% in debug mode

we can ignore any % in debug mode and focus only on release one when optimizing performances

**Comment by Warpten** [comment]
The simple fact that you get better numbers in debug than in release should show you that something wrong is going on

**Comment by Shauren** [comment]
Cheating? What cheating? I merely ran unmodified TC ByteBuffer and your resizeMem patch with no extra reserve calls

**Comment by Langerz82** [comment]
Haha sorry Shauren I misread your post, I thought you made the call to reserve which effectively bypasses the growth algorithm until it's full. Have you tested my new ByteBuffer? It shouldn't do those extra calls because it uses a 1.5 multiplier, I could use 2 like vectors but I read somewhere 1.5 is close to a nice natural growth.

**Comment by Shauren** [comment]
Yes, I tested it, your version performed worse. Now if you basically mirror vector allocation pattern then there is no point at all in changing it as vector allows for far cleaner code

ps. mscv vector uses 1.5, gcc has 2
