### ISSUE TITLE
DB/Gossip: Royal Historian Archesonus

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22179]
**Description:**

Royal Historian Archesonus should show a different gossip text if player is on quest "The Smoldering Ruins of Thaurissan".

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Royal Historian Archesonus
DELETE FROM `gossip_menu` WHERE `MenuID`=1561 AND `TextID`=2235;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(1561,2235,0);

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=1561;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14,1561,2235,0,0,9,0,3702,0,0,0,0,0,"","Show gossip text 2235 if quest 'The Smoldering Ruins of Thaurissan' is taken");

**Comment by illfated** [comment]
Out of curiosity, does that gossip option open to the following gossip options, shown in the quest page?
(https://wow.gamepedia.com/Quest:The_Smoldering_Ruins_of_Thaurissan)

**Comment by ZenoX92** [comment]
The gossip option was already set, and yes it all happens as in the page.

What I fixed was the gossip text. She normally says: "Greetings, $N. Have you come to learn of the history of Ironforge?"
But when you take the quest she should say instead: "Notify me when you are ready to listen to the story."
