### ISSUE TITLE
[3.3.5] Error - Could not fetch prepared statement 65 on database `auth`, connection type: synchronous.

### ISSUE THREAD

**Issue by Langerz82** [TrinityCore/TrinityCore#22174]
**Description:**
SQL Error in a recent 335 build:

**Current behaviour:**
Could not fetch prepared statement 65 on database `auth`, connection type: synchronous.

d:\workspace\joslan\wowtc\trinitycore\src\server\database\database\mysqlconnection.cpp:252 in MySQLConnection::_Query ASSERTION FAILED:
  m_mStmt

**Expected behaviour:**
The build include prepared statement 65.
Note - If someone could point to me a fix soon that would be great, I'm testing a new push and using this build to test.

**Steps to reproduce the problem:**

1. Run Build Error comes up.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 2ef331584868+ 2018-07-11 18:14:09 +0200 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**Operating system:** Win 10 x64 Build

**Comment by Langerz82** [comment]
Hey, I must be missing a SQL update, how do I merge the 335 latest into my Fork?

**Comment by WildCoffee** [comment]
You've made changes to the source, so it's probably related to the changes you've made. You could try adding a breakpoint on line 251 and debug from there. You can also check the DBErrors.log file for help, there might be an error there you can track down. If you want to see the prepared statements they're in the LoginDatabase.cpp file.

**Comment by Aokromes** [comment]
user isues doesn't belongs to BUG tracker.

**Comment by illfated** [comment]
This may feel a bit insensitive, but I recommend that you recreate your 3.3.5 branch in a new folder and add your PR branches there. Then re-upload your working 3,3,5 branch to your repository and make it replace your broken 3.3.5.

(I know, this will close your existing pull requests and force you to open new ones.)
