### ISSUE TITLE
DB/Quest: Gaffer Jacks

### ISSUE THREAD

**Issue by WildCoffee** [TrinityCore/TrinityCore#22175]
**Description:**

- Drop the existing primary key on fishing_loot_template because Entry/Item is not a unique combination (some areas can have multiple entries, like Darkshore). 
- Create a new primary key of Entry/Item/GroupId because that should be unique
- Add the missing group entry in fishing_loot_template for Darkshore so that Gaffer Jacks can be fished. Quest Required is ignored on this table, so I've left it as 0 so it doesn't generate a warning

This closes #21690 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 8a7fdbda0081 2018-06-27 21:38:10 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**TDB:** 335.64

**Operating system:** Windows 10

**Suggested Fix:**

```sql
-- Remove existing Primary Key
ALTER TABLE `fishing_loot_template` DROP PRIMARY KEY;

-- Create new Primary Key
ALTER TABLE `fishing_loot_template` ADD PRIMARY KEY (`Entry`, `Item`, `GroupId`);

-- Insert new Darkshore entries

DELETE FROM `fishing_loot_template` WHERE `Entry`= 148;
INSERT INTO `fishing_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(148, 11104, 11104, 100, 0, 1, 1, 1, 1, 'Darkshore Normal'),
(148, 11104, 11104, 100, 0, 1, 0, 1, 1, 'Darkshore Quest');
```

**Comment by Killyana** [comment]
If I apply you SQL I will get 3 loots:
- Quest item
- a Fish from groupId=0
- a Fish from groupId=1
So I will just update the groupId on fishing_loot_template to 0, the player will get the quest Item + a fish if he's on the quest.
