### ISSUE TITLE
Firs Aid Trainer / Angela Leifeld  in Stormwind

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#22172]
**Description:**

First Aid Trainer / [Angela Leifeld](http://www.wowhead.com/npc=56796/angela-leifeld) - the book of learning can not be opened

**Current behaviour:**

after you click on the teacher, the First Aid Learning book will not be opened

**Expected behaviour:**

Clicking on a teacher should open a first aid learning book

**Steps to reproduce the problem:**

1. the book of learning can not be opened 
2. after opening a book of learning, first aid should be learned
3. [Angela Leifeld ](http://www.wowhead.com/npc=56796/angela-leifeld)- First Aid Trainer

**Branch(es):**

**CHANGEME  :**  master

**TC rev. hash/commit:** 
TrinityCore rev. c2d61e05cf3d 2018-06-29 22:38:38 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
**Operating system:** Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
**Using World DB:** TDB 735.00

**Comment by Aokromes** [comment]
#20193
