### ISSUE TITLE
Quest : Find the Ancient Hero - quest item not working properly

### ISSUE THREAD

**Issue by spraypaint1993** [TrinityCore/TrinityCore#22171]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

 Tell us what happens.
When i use the quest item  [The Bone Witch's Amulet](http://www.wowhead.com/item=43166/the-bone-witchs-amulet) on [Iskalder](http://www.wowhead.com/npc=30884/iskalder) it begins to channel the spell but before the channel is finished somehow it gets interupted and Iskalder disapears
**Expected behaviour:**
When i cast the quest item it should finish the channeling without interuption and then it will make him friendly and wil begin to follow me ,for finishing the quest i must return him to the quest giver.
Here is a [video](http://www.wowhead.com/quest=13133/find-the-ancient-hero#videos:id=74138) what should happen if the quest is working properly.
Tell us what should happen instead.

**Steps to reproduce the problem:**

1. You should start the quest chain by kiling [Apprentice Osterkilgr](http://www.wowhead.com/npc=30409/apprentice-osterkilgr) and looting the [Dr. Terrible's "Building a Better Flesh Giant](http://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) ,the quest chain start from this item.
2. The first quest of the quest chain is [The Sum is Greater than the Parts](http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts) you need to kill [Dr. terrible](http://www.wowhead.com/npc=30404/dr-terrible) by taking control of [Nergeld](http://www.wowhead.com/npc=30403/nergeld) , after compleating the quest you must return it to [The bone Witch](http://www.wowhead.com/npc=30232/the-bone-witch)
3. You will receive new quest [The Art of Being a Water Terror](http://www.wowhead.com/quest=13091/the-art-of-being-a-water-terror), you should click on the door near the water terrors and by clicking it you will become a Water Terror , after that you have to kill 10 Jotunheim vrykul.Return the quest back to the Bone Witch.
4. The new quest that you will receive is [Through the Eye](http://www.wowhead.com/quest=13121/through-the-eye) you need to go to Kul'galar Keep and then clicking on the Eye of the lich king and wait for the short dialoge to end, Here is a 
[http://www.wowhead.com/quest=13121/through-the-eye#videos:id=74145](video)
for that quest.
5.After compleating the three quests from above you will be able to take  [Find the Ancient Hero](http://www.wowhead.com/quest=13133/find-the-ancient-hero)

TrinityCore rev. 31c01e166136 2018-07-14 08:07:23 +0300 
(3.3.5 branch)
 (Win64, RelWithDebInfo, Static)

**Comment by Aokromes** [comment]
plz, update your core before reporting bugs, over 1 month old is "to old".

**Comment by spraypaint1993** [comment]
im sorry the core is on last version i just didnt know it and use the last quest report as a template, i edited the report hopes its alright now , apologize.

**Comment by illfated** [comment]
Looking at the commit list, your commit revision hash (31c01e166136) does not appear:
https://github.com/TrinityCore/TrinityCore/commits/3.3.5
(Also according to that list, there is no 3.3.5 commit for the 14. of July.)
Master branch has got 2 commits from the 14. of July, but none of them match your hash:
https://github.com/TrinityCore/TrinityCore/commits/master
The conclusion we draw from it is that you have likely made some changes to your core.

Anyway, I still have got 1 character with [The Sum is Greater than the Parts](http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts) (Quest ID 13043) on its list, so I may as well test if I can reproduce your issue later.

**Comment by Langerz82** [comment]
It seems the Script is missing. 
SELECT * FROM world.smart_scripts where entryorguid=30884 AND id=1
The SmartScript will not work as it does not convert the Monster into a friendly target and also breaks from applying the spell (as the monster is despawned when calling spell update).
Not sure how to fix this will continue to look into it.

**Comment by Langerz82** [comment]
Has anyone got another example of an item that makes a particular creature into a friendly?

**Comment by Langerz82** [comment]
Working on this.

**Comment by Langerz82** [comment]
Apply SQL and re-test. Note - Iskalder just follows but isnt charmed, should he be?

```sql
USE `world`;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 30884;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 30886;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30884,0,0,0,54,0,100,512,0,0,0,0,0,1,1,100,0,0,0,0,1,0,0,0,0,0,0,0,0,'Iskalder - On Just Summoned - Say Line 1');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30884,0,1,0,8,0,100,512,3921,0,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Iskalder - On Spellhit \'The Bone Witch\'s Amulet\' - Despawn');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30884,0,2,0,8,0,100,512,3921,0,0,0,0,12,30886,5,0,0,0,0,1,0,0,0,0,0,0,0,0,'Iskalder - On Spellhit \'The Bone Witch\'s Amulet\' - Respawn Subjecate');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30886,0,0,0,0,0,100,513,1,1,1,1,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Subjugated Iskalder - In Combat - Set Flag Immune To NPC\'s');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30886,0,1,0,54,0,100,512,0,0,0,0,0,29,0,0,30232,0,1,0,21,30,0,0,0,0,0,0,0,'Subjugated Iskalder - Out of Combat - Start Follow Invoker');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (30886,0,2,0,65,0,100,0,0,0,0,0,0,11,25729,0,0,0,0,0,23,0,0,0,0,0,0,0,0,'Subjugated Iskalder - On Follow Complete - Cast \'Find the Ancient Hero: Kill Credit\'');
```

**Comment by illfated** [comment]
SQL from above, simplified for readability etc. :
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (30884, 30886) AND  `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(30884,0,0,0,54,0,100,512,   0,0,0,0,0, 1,    1,100,    0,0,0,0, 1, 0,0,0,0,0,0,0,0,'Iskalder - On Just Summoned - Say Line 1'),
(30884,0,1,0, 8,0,100,512,3921,0,0,0,0,41,    0,  0,    0,0,0,0, 1, 0,0,0,0,0,0,0,0,"Iskalder - On Spellhit 'The Bone Witch's Amulet' - Despawn"),
(30884,0,2,0, 8,0,100,512,3921,0,0,0,0,12,30886,  5,    0,0,0,0, 1, 0,0,0,0,0,0,0,0,"Iskalder - On Spellhit 'The Bone Witch's Amulet' - Respawn Subjecate"),
(30886,0,0,0, 0,0,100,513,   1,1,1,1,0,18,  512,  0,    0,0,0,0, 1, 0,0,0,0,0,0,0,0,'Subjugated Iskalder - In Combat - Set Flag Immune To NPC'),
(30886,0,1,0,54,0,100,512,   0,0,0,0,0,29,    0,  0,30232,0,1,0,21,30,0,0,0,0,0,0,0,'Subjugated Iskalder - Out of Combat - Start Follow Invoker'),
(30886,0,2,0,65,0,100,  0,   0,0,0,0,0,11,25729,  0,    0,0,0,0,23, 0,0,0,0,0,0,0,0,"Subjugated Iskalder - On Follow Complete - Cast 'Find the Ancient Hero: Kill Credit'");
```

**Comment by Killyana** [comment]
It was just a bad concept: the despawn was triggered 5 secs after the beginning of the channeling spell, and as the channeling spell triggers the summon spell also after 5 secs, it fails to find the target despawned at the exact time, I changed the despawn to be triggered by the summon spell.
