### ISSUE TITLE
DB/Core/Scripts: Princess Moira Bronzebeard

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22182]
**Description:**

Princess Moira Bronzebeard shoud display an emote text when Emperor Dagran Thaurissan is slain.

Since she is already scripted in core side, and since I know nothing about C++ scripts, I will only add the text. Someone else (@Killyana?) will have to do the hard part.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Princess Moira Bronzebeard
DELETE FROM `creature_text` WHERE `CreatureID`=8929;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(8929,0,0,"%s is visibly shaken by the death of Emperor Thaurissan.",16,0,100,18,0,0,5429,0,"Princess Moira Bronzebeard");

**Comment by illfated** [comment]
I could be wrong, but I'm thinking that the issue page title here should be:
**DB/Creature: Princess Moira Bronzebeard**

the core part could be named
**Scripts/Blackrock Depths: Princess Moira Bronzebeard** (or maybe **Scripts/Creature: boss_moira_bronzebeard**)
File location: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_moira_bronzebeard.cpp

She needs an enum for the text, probably something like
```cpp
enum Emote
{
    EMOTE_SHAKEN    = 0
};
```
although the `= 0` part can be skipped if the emote enum stays alone.
Not sure if it belongs with more enums, like `enum Misc` (if additional enums are added)
Then again, we also need an event registered when the emperor dies.
(I don't remember enough scripting for this at the moment.)
