### ISSUE TITLE
Most "dead" bodies placed on terrain can be attacked with AOE spells, as well as "invalid target" mobs

### ISSUE THREAD

**Issue by Nocturne1501** [TrinityCore/TrinityCore#22184]
**Description:**

A player can attack and hit "dead" bodies pre-placed on the ground by using AOE spells. This also happens with "untargetable" mobs.

**Current behaviour:**

Certain "dead" NPCs (for example, Slain Cultists of the Cult of the Damned in Borean Tundra) can be attacked and hit with AOE spells. On some occasions, this will even put the player in combat with the dead body, essentially locking them into combat until they use an escape effect (invisibility, for example).

The same thing happens with untargetable hostile NPCs, such as enemy faction NPCs in neutral capitals (Shattrath, presumed Dalaran also), where the NPCs can freely be hit with AOE spells, but I am unable to confirm whether entering combat with them is possible.

In both cases, trying to use targeted spells (i.e. Mage's Frostbolt) will correctly display an "invalid target" message. However, using an AOE spell (i.e. Mage's Arcane Explosion) will hit the target(s) regardless.

**Expected behaviour:**

"Dead" bodies and hostile faction members in neutral capitals should not be targetable by any spells, AOE or not.

**Steps to reproduce the problem:**

1. Find a "dead" NPC in the level (NPCs slain by the player do not work with this)
2. Use an AOE spell that does not require a target on the NPC (Blizzard, Arcane Explosion, etc)
3. ???
4. Profit!

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b68a4e2b8e16 2018-06-28 03:17:42 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:**

Ubuntu 18.04

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21929

**Comment by Nocturne1501** [comment]
(Sorry! Didn't see that!)
