### ISSUE TITLE
DB/Quest: Lightforge Ingots

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22196]
**Description:**

Quest "Lightforge Ingots" was removed from game and replaced by quest "The Lost Ingots".

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry`=526;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
(1,526,0,"","","Deprecated quest");

**Comment by illfated** [comment]
Extra quest info:
- http://www.wowhead.com/quest=526/lightforge-ingots
  - https://woehead.way-of-elendil.fr/?quest=526

- http://www.wowhead.com/quest=324/the-lost-ingots
  - https://woehead.way-of-elendil.fr/?quest=324
