### ISSUE TITLE
Darkmoon Faire event start wrong

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#22199]
**Description:**

Darkmoon Faire event is active. But the Start Time should set on 04.08. Look at the Ingame Calendar

**Steps to reproduce the problem:**

1. Login
2. user command .event active
3. show that Darkmoon Faire is active (event Id 3) 
4. show to Calendar. Darkmoon Faire should start at 04.08 as next.

**Branch(es):**

335 / master / 4.3.4

**TC rev. hash/commit:** 

 TrinityCore rev. 4ca277b34531 2018-07-25 21:39:17 +0200 (4.3.4 branch)

**Operating system:** CHANGEME OS

**Comment by illfated** [comment]
Detail: 4.3.4 is no longer an active branch in TrinityCore.

**Comment by Killyana** [comment]
Cannot reproduce
