### ISSUE TITLE
[Master] MoP+ Content

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#22204]
**Description:**

No NPCs or gameobjects are placed anywhere, and dungeons and raids do not have teleport entries  - applies to MoP and above (quests do exist, though, strangely enough).

**Expected behaviour:**

Should be otherwise

**Steps to reproduce the problem:**

1. Go to any MoP+ location

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 394f9775a7c6 2018-07-28 19:42:50 +0200 (master branch) (Win64, Release, Static)

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12975
