### ISSUE TITLE
DB/Gossip: Captain Nials, Skuerto, Apprentice Kryten & Navigator Mehran

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22219]
**Description:**

* Remove wrong gossip text for Captain Nials
* Remove wrong gossip text for Skuerto
* Fix gossip text for Apprentice Kryten
* Fix gossip text emote for Navigator Mehran
* Remove wrong gossip flag for Restless Apparition

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Captain Nials
UPDATE `creature_template` SET `npcflag`=2, `gossip_menu_id`=0 WHERE `entry`=2700;

UPDATE `smart_scripts` SET `action_param1`=2 WHERE `entryorguid`=270000 AND `source_type`=9 AND `id` IN (0,9);

-- Skuerto
UPDATE `creature_template` SET `npcflag`=2, `gossip_menu_id`=0 WHERE `entry`=2789;

-- Apprentice Kryten
DELETE FROM `gossip_menu` WHERE `MenuID`=2601 AND `TextID`=3294;

-- Navigator Mehran
UPDATE `npc_text` SET `em0_0`=0, `em0_1`=274 WHERE `ID`=12209;

-- Restless Apparition
UPDATE `creature_template` SET `npcflag`=0 WHERE `entry`=23861;

**Comment by Killyana** [comment]
I commented this: 
``` sql
DELETE FROM `gossip_menu` WHERE `MenuID`=2601 AND `TextID`=3294;
``` 
As on wowpedia: https://wow.gamepedia.com/Apprentice_Kryten
Quotes

    Don't mind Skuerto, <name>. He doesn't mean to be rude, he's just terribly busy. While we are waiting for him to finish scouting, why don't we work on something more productive?
 (This quote refers to activity removed after the Shattering. Formerly, Kryten referenced Skuerto as scouting Boulderfist Hall.[2])

**Comment by ZenoX92** [comment]
Yes, you are right @Killyana. I thought the text was wrong because I watched all of Apprentice Kryten's quests in a video, and he never showed that text, but then I realized I had watched every quest, except the breadcrumb quest "Malin's Request". So, I assume he says that text after you complete the breadcrumb quest (which ends with Skuerto) and before you take his first quest ("Worth Its Weight in Gold"). Here are the conditions:
```sql
-- Apprentice Kryten
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=14 AND `SourceGroup`=2601;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14,2601,3294,0,0,8,0,690,0,0,0,0,0,"","Show gossip text 3294 if quest 'Malin's Request' is rewarded"),
(14,2601,3294,0,0,14,0,691,0,0,0,0,0,"","Show gossip text 3294 if quest 'Worth Its Weight in Gold' is not taken");
