### ISSUE TITLE
[Master] Antorus worldserver crash

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#22215]
**Description:**

Going to Antorus causes the "instance creation aborted" error and crash

[172ccdb49929+_worldserver.exe_[1-8_20-46-33].txt](https://github.com/TrinityCore/TrinityCore/files/2250519/172ccdb49929%2B_worldserver.exe_.1-8_20-46-33.txt)

**Expected behaviour:**

Should let me in

**Steps to reproduce the problem:**

1. Place your character in the raid (for example, by editing the character's location to 2870 -4561 200 1712 in the characters db)
2. Log in

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 172ccdb49929+ 2018-08-01 19:11:02 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 10

**Comment by Smerdokryl** [comment]
A different crash also happens if Antorus is made a normal map, instead of raid, by a hotfix:

[172ccdb49929+_worldserver.exe_[3-8_18-1-24].txt](https://github.com/TrinityCore/TrinityCore/files/2257800/172ccdb49929%2B_worldserver.exe_.3-8_18-1-24.txt)

**Comment by Shauren** [comment]
Both are caused by bad db data
First case is missing instance_template
Second is missing MapDifficulty.db2 entry (you cant just edit map type from instance to continent and expect it to work)
