### ISSUE TITLE
Missing npc Rudra Amberstill

### ISSUE THREAD

**Issue by Ravens62** [TrinityCore/TrinityCore#22214]
Missing npc http://www.wowhead.com/npc=1265/rudra-amberstill

**Description:**

There is no data about npc in db "creature".
It is stated in "queststarter" and "creature template".
But it does not appear.

**Branch(es):**

master

TrinityCore rev. c2d61e05cf3d 2018-06-29 22:38:38 +0200 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**Windows 10**

**Comment by illfated** [comment]
Present in 3.3.5 and there is nothing online suggesting that this spawn should be removed.
Looks like a missing DB spawn, then (or possibly a bugged spawn deletion).

**Comment by ratkosrb** [comment]
Checked on live servers and she is still there.
![wow 2018-08-02 09-43-01-92](https://user-images.githubusercontent.com/35845488/43566865-741360c8-961f-11e8-8848-44686886787e.jpg)
