### ISSUE TITLE
Core/SAI: SMART_ACTION_CROSS_CAST (85) not working with specific target types

### ISSUE THREAD

**Issue by Pharonax** [TrinityCore/TrinityCore#22225]
**Description:**

The action SMART_ACTION_CROSS_CAST (85) does not work with the following target types:
12
17
18
21

**Current behaviour:**

The action will not be executed if it has the above target types.

**Expected behaviour:**

The action should be executed and should work with the given target type.

**Steps to reproduce the problem:**

1. Use Action 85, together with target type 12, 17, 18 or 21
2. Watch it fail.

**Branch(es):**

3.3.5

(haven't tested master but it could be affected there too)

**TC rev. hash/commit:** 

TC>TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Using MySQL version: 5.7.22
Using CMake version: 3.9.1
Compiled on: Linux 4.13.0-46-generic
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in /home/dev/server/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/dev/server/data/vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

TC revision 5cdb53896f89bfff82ad627dd30aebe3834aabf5

**Operating system:** Ubuntu 17.10

**Comment by illfated** [comment]
It should be noted that this issue is directly related to the issue **The Valiant's Challenge: defeating the Argent Champion gives no credit #22210** and possibly other issues (already reported or not yet reported).

**Comment by Pharonax** [comment]
Yes, in this issue, Killyana posted a SELECT query of all entries affected by this issue.

**Comment by Killyana** [comment]
The issue is about SMART_ACTION_INVOKER_CAST, andd no need to have a second one, #22210  is enough.
