### ISSUE TITLE
Mac connection_patcher: unable to find pattern

### ISSUE THREAD

**Issue by SachikoMaeda** [TrinityCore/TrinityCore#22227]
**Description:**

Attempting to patch Legion Mac .app version 7.3.5 (26972) with connection_patcher fails with error.

**Current behaviour:**

TrinityCore rev. a8a071e9d951 2018-08-05 18:57:35 +0200 (master branch) (MacOSX, RelWithDebInfo, Static) (connection_patcher)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Creating patched binary...
EX: unable to find pattern
An error occurred. Press ENTER to continue...

**Expected behaviour:**

Patch successful

**Steps to reproduce the problem:**

1. Successful build in macOS High Sierra with Xcode 
2. Use Terminal with directory to connection_patcher and World of Warcraft.app

**Branch(es):**

master

**TC rev. hash/commit:** 
a8a071e9d951 2018-08-05 18:57:35 +0200 (master branch)

**Operating system:** macOS High Sierra 10.13.6

**Comment by illfated** [comment]
if you want to display and keep your pasted text from the console window using monospaced text, you can use 3 back ticks ( **```** ) on a blank line after **Current behaviour:** and before **Expected behaviour:** .

See also https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by Shauren** [comment]
Wontfix this close to bfa
