### ISSUE TITLE
Core/Spell: SPELL_ATTR4_UNK2 determines if aura continues to expire while offline

### ISSUE THREAD

**Issue by ratkosrb** [TrinityCore/TrinityCore#22224]
**Description:**

I was looking through old patch notes when i saw this:

```
World of Warcraft Client Patch 1.12.0 (2006-08-22)
-  The deserter debuff will now continue to expire even while you are offline.
```
https://github.com/brotalnia/ely-database/blob/master/new_progression/Patchnotes%20(ALPHA%20to%201.12.1).txt#L139

So i compared the Spell.dbc data for the deserter spell (ID 26013) in the 1.12.1.5875 and 1.11.2.5464 clients, and I noticed that the only difference between the 2 versions, is that in 1.12 it has attributes4 = 4, while in 1.11 it is 0.
![deserter](https://user-images.githubusercontent.com/35845488/43674431-727ee750-97c3-11e8-87e5-129deae89eba.jpg)

Upon checking for spells that have that attributes in 3.3.5, it seems to be present in all the ones that should continue to expire while the player is offline.

Some examples are:
24755 - Tricked or Treated
26013 - Deserter
57723 - Exhaustion
57724 - Sated
71041 - Dungeon Deserter
71328 - Dungeon Cooldown

In addition, Wowhead seems to already have defined the attributes as "Continues while logged out".
http://www.wowhead.com/spells?filter=85;1;0
All the spells listed here have the attributes.

**Current behaviour:**

This attribute is not used.

**Expected behaviour:**

It should be renamed and used to determine whether an aura has a real time duration.

**Branch(es):**

both

**TC rev. hash/commit:** 

ba9943d8a422c0ca9db0dd340f1e9e2ca67c8c33

**Comment by illfated** [comment]
Nice find. Interesting too. I hope it can be implemented.

**Comment by wonder2011** [comment]
So, all other spells must save cooldowns and begin down when you loggin ??, and only spells with this attr will down cd when you are offline ?

**Comment by wonder2011** [comment]
@Shauren please check this. This is very important to fix.

**Comment by aquadeus** [comment]
this is fixed
