### ISSUE TITLE
DB/Object: The Park

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22237]
**Description:**

* Fix rotation for gameobject "The Park" (guid: 42874)
* Delete a duplicate spawn (guid: 42873)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 1cc3d33 2018-02-19 20:21:57 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
UPDATE `gameobject` SET `rotation2`=0.944089, `rotation3`=-0.329691 WHERE `guid`=42874;

DELETE FROM `gameobject` WHERE `guid`=42873;
DELETE FROM `gameobject_addon` WHERE `guid`=42873;

**Comment by ZenoX92** [comment]
I'm deleting the duplicate with the higher guid. Currently there are 3 different spawns for gameobject "The Park" (Guids: 42872, 42873 & 42874), but there should be only 2. Objects 42872 & 42873 are spawned in the same place, so I removed the one with the higher guid (42873). Object 42874 is correctly spawned.

I should have explained this when I submitted the fix. My bad!

**Comment by Aokromes** [comment]
ahh ok, thx for clarification :)

**Comment by illfated** [comment]
OK, nice, so this is about https://woehead.way-of-elendil.fr/?object=25341 ?

**Comment by ZenoX92** [comment]
Yes, it is.
