### ISSUE TITLE
DB/Misc: fix Worgen intro

### ISSUE THREAD

**Issue by ReyDonovan** [TrinityCore/TrinityCore#22255]
**Description:**
fix change phases start worgen area
CHANGEME Description of the problem or issue here.
not works
**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
fix test in game works
```
-- worgen intro
UPDATE `creature_template` SET `npcflag` = 0 WHERE `entry` = 34884; -- not questgiver

UPDATE `quest_template_addon` SET `ExclusiveGroup` = -14093 WHERE `ID` IN (14098, 14093);

DELETE FROM `conditions` WHERE `SourceEntry`=4756;
DELETE FROM `conditions` WHERE `SourceGroup`=170 AND `ConditionValue1`=14078;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(26, 169, 4756, 0, 0, 28, 0, 14078, 0, 0, 1, 0, 0, '', 'Phase 169 until Quest 14078 not complete'),
(26, 170, 0, 0, 0, 28, 0, 14078, 0, 0, 0, 0, 0, '', 'Phase 170 until Quest 14078 complete');

 
DELETE FROM `spell_area` WHERE `area`=4756;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES
(59073, 4756, 14078, 0, 0, 0, 2, 1, 64, 0), -- phase 170
(49416, 4756, 14078, 0, 0, 0, 2, 1, 64, 0); -- Generic Quest Invisibility 1
```

**Branch(es):** master

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 41c4fec

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS win10 Pro

**Comment by ReyDonovan** [comment]
```
-- worgen intro
UPDATE `creature_template` SET `npcflag` = 0 WHERE `entry` = 34884; -- not questgiver

UPDATE `quest_template_addon` SET `ExclusiveGroup` = -14093 WHERE `ID` IN (14098, 14093);

DELETE FROM `conditions` WHERE `SourceEntry`=4756;
DELETE FROM `conditions` WHERE `SourceGroup`=170 AND `ConditionValue1`=14078;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(26, 169, 4756, 0, 0, 28, 0, 14078, 0, 0, 1, 0, 0, '', 'Phase 169 until Quest 14078 not complete'),
(26, 170, 0, 0, 0, 28, 0, 14078, 0, 0, 0, 0, 0, '', 'Phase 170 until Quest 14078 complete');
 
DELETE FROM `spell_area` WHERE `area`=4756;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `flags`, `quest_start_status`, `quest_end_status`) VALUES
(59073, 4756, 14078, 0, 0, 0, 2, 1, 64, 0), -- phase 170
(49416, 4756, 14078, 0, 0, 0, 2, 1, 64, 0); -- Generic Quest Invisibility 1
```
fix sql error
8 queries executed, 8 success, 0 errors, 0 warnings

**Comment by illfated** [comment]
@ReyDonovan & @shamage - F.Y.I. - if you want to see the SQL code syntax highlighted (MarkDown) for the code you put in your comments, you can use **```sql** on top of your code blocks.

**Comment by shamage** [comment]
@illfated  - edited   :)

**Comment by dio85** [comment]
26	169	0	0	0	28	0	14078	0	0	0	0	0		Phase 170 until Quest 14078 complete
26	169	4756	0	0	8	0	14078	0	0	1	0	0		Phase 169 until Quest 14078 not complete
26	170	0	0	0	28	0	14091	0	0	0	0	0		Phase out 169 Quest 14078

work correcly for me.

**Comment by shamage** [comment]
@dio85   :  your phasing ( phase 170 ) adjustment works on Map 654 , Area 4755 ? 

or the command is needed : `.mod phase 170 `

**Comment by dio85** [comment]
i not need the command :D work for me fully.

**Comment by dio85** [comment]
if u have 7.3.5 sniffs plss share for me! thanks :)

**Comment by dio85** [comment]
And the answer for, why have 2 169 phase... need 1 in-and out. if u dont go out 169,170 phase mob spawned on area... so that not very good for u

**Comment by shamage** [comment]
@dio85  : 
I still do not know very much - I'm just learning the basics, so I do not even control the taste ( sniffs )

**Comment by dio85** [comment]
Me2 :) the database is easy. core hard.. 💃

**Comment by Killyana** [comment]
The phasing is wrong, I will cherry pick some stuff from 4.3.4 later.

**Comment by dio85** [comment]
why? in cataclysm use too 169,170, etc,etc phases. just wotlk use pahse 1,2.

**Comment by shamage** [comment]
@dio85 - 
would it be possible to add a modification to phase 170 ? ( I mean passing from phase 169 to phase 170 )

**Comment by dio85** [comment]
Sure, in worgen are have many many phase change.... maybe 10.. 14... 15.. so ...
