### ISSUE TITLE
Warrior Charge Underwater Facing the Wrong Way

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22253]
**Description:**

Warrior charge underwater causes the warrior to charge at the mob but faces the wrong way.

**Current behaviour:**

When your underwater fighting turtles for instance and you use charge the charge works but when you stop at the mob you are facing the wrong way.

**Expected behaviour:**

You should be able to use the charge underwater and stop right in front of the mob so you can instantly attack without having to move around to get the mob in front of you.

**Steps to reproduce the problem:**

1. Go anywhere where there is deep water and mobs
2. Cast charge on any mob and your toon will run at them.
3. Then you are greeted by the error that you are facing the wrong way.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6726126664db+

**Operating system:** 

Windows Server 2012

**Comment by illfated** [comment]
out of curiosity: does the warrior charge end before or after the target?
if the charge ends on the other side of the target, it could be a movement calculation issue.
on the other hand, if the warrior stops before the target, the orientation would be the problem.

**Comment by illfated** [comment]
Very well, thanks for the feedback. I am fairly sure I have noticed it while testing warrior class characters, but never thought it was a permanent issue, more or less a maps/mmaps issue related to other charge issues already open here in the tracker. Since you have tested it in detail like you documented above, it is more likely to be a core issue.

**Comment by Killyana** [comment]
Th issue is when you charge a creature in water you will end on top of it, the issue is not with facing but the height end position.

**Comment by Faq** [comment]
me summns @Ovahlord

**Comment by jackpoz** [comment]
caused most likely by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L5512

**Comment by Killyana** [comment]
We must fix https://github.com/TrinityCore/TrinityCore/issues/23326 first, as I cannot charge any creature in water, it always returns no path available.

**Comment by jackpoz** [comment]
I was able to charge just fine at the coordinates you provided. maybe the target has to be 4 yards underground ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24010
