### ISSUE TITLE
[Legion] Quest Opening the Test Kitchen  ID 40991

### ISSUE THREAD

**Issue by kikote300** [TrinityCore/TrinityCore#22267]
https://www.wowhead.com/quest=40991/opening-the-test-kitchen bug

Description:

Can not be completed ,why do not do the phases

Branch(es):

master

TrinityCore rev. c2d61e0 2018-06-29 22:38:38 +0200 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12975
