### ISSUE TITLE
[DEV]Core/Quest: Breadcrumb quests requirements

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22264]
**Description:** RewardNextQuest  was used to handle the availability of Breadcrumb quests, but it's no longer the case since some changes done years ago, example:

Quest A and Quest B are Breadcrumb for quest C, in this case we put RewardNextQuest=C for A and B. 
But  RewardNextQuest  isn't supposed to handle this kind of requirements:
``` 
RewardNextQuest: (Old field name: NextQuestIdChain)
The quest entry from a creature or gameobject that ends a quest and starts a new one. The result is, that if you end the quest, the new quest instantly appears from the quest giver.
```
So we need a new field on `quest_template_addon` called `Breadcrumb`, that makes the quest not available if the quest on `Breadcrumb` is taken/completed/rewarded.

PS: I know there's the table conditions that could handle this, but it's not the correct way.

Ref: https://github.com/TrinityCore/TrinityCore/issues/20452 https://github.com/TrinityCore/TrinityCore/issues/22216

**Branch(es):** both

**TC rev. hash/commit:** rev. 41982aa30026

**Comment by illfated** [comment]
Impressive. That is a good amount of work.

**Comment by Killyana** [comment]
For this reason I don't like using conditions for BreadCrumb Quest, instead of putting just a value on quest_template_addon, we end with a wall of sql, also we will not have a good visibility about the chaining, it's better to wait for someone to implement it on quest template addon.

**Comment by ZenoX92** [comment]
OK. I will continue searching for more breadcrumb quests so, when the feature is implemented, we could have a full list of all of them.

**Comment by Killyana** [comment]
RewardNextQuest was changed here: https://github.com/TrinityCore/TrinityCore/commit/a82a12b5ef5c466496c314b5a1eb6838dc598b15
This part of coded must be used for a new DB fiel on quest_template_addon called "breadcrumb"

**Comment by Aokromes** [comment]
Adding more to the list:
https://www.wowhead.com/quest=12795/taking-a-stand#comments:id=731421

https://www.wowhead.com/quest=12885/the-exiles-of-ulduar
https://www.wowhead.com/quest=12930/rare-earth

Breadcrumb Quests:
https://www.wowhead.com/quest=11038/assist-exarch-orelis [-> Distraction at Manaforge B'naar]
https://www.wowhead.com/quest=10183/off-to-area-52 [-> You're Hired!]
https://www.wowhead.com/quest=11036/out-of-this-world-produce [-> You're Hired!]
https://www.wowhead.com/quest=11037/a-strange-vision [-> You're Hired!]
https://www.wowhead.com/quest=11040/parts-for-the-rocket-chief [-> You're Hired!]
https://www.wowhead.com/quest=11042/a-mystifying-vision [-> You're Hired!]

**Comment by meji46** [comment]
A breadcrumb quest meets the following requirements:

Example
* Quest A (Breadcrumb)
* Quest B

* Quest A is taken/completed -> Quest B not available
* Quest A is not taken/rewarded -> Quest B available
* Quest B is taken/completed/rewarded -> Quest A not available

**Comment by Killyana** [comment]
No @meji46  this is wrong

**Comment by Killyana** [comment]
It works like this:
Example:
-Quest A (Breadcrumb)
-Quest B

* Quest A is taken/completed -> Quest B available
*  Quest A is not taken/rewarded -> Quest B available
* Quest B is taken/completed/rewarded -> Quest A not available

**Comment by meji46** [comment]
That's wrong for Hero's Call Board quests.  They worked like I said (tested in MoP & WoD).

**Comment by meji46** [comment]
There are special cases with false breadcrumbs like quest 25316.

**Comment by Aokromes** [comment]
5ed7711
