### ISSUE TITLE
Core/Spells: Spells applying aura with a speed do not stack properly

### ISSUE THREAD

**Issue by kelno** [TrinityCore/TrinityCore#22272]
**Description:**

Spells with a speed (= fly time) applying auras do not reapply on target if another aura with same id and caster is already present. Thus timer is not refreshed nor stacks incremented. 

**Current behaviour:**

New spell cast does not increment stacks.

**Expected behaviour:**

New spell cast does increment stacks.

**Steps to reproduce the problem:**

1. `.npc add 17256` (Hellfire channeler)
2. `.cast 30531` from your player character two times or more.

The creature still has one stack, while the aura should stack up to 99 times.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

(using last revision atm)
TrinityCore rev. cbacc72d934c 2018-08-15 20:14:16 +0200 (3.3.5 branch) (Win64, Debug, Static)

**Operating system:** 
Windows 10 x64

**Additional notes:** 
It seems related to this block: https://github.com/TrinityCore/TrinityCore/blob/cbacc72d934c10448762b67a0fa97ea4eb38cb63/src/server/game/Spells/Spell.cpp#L2767-L2773
Removing the GetAura does seem to fix the problem but cause other issues (can give more details if this is useful to you).

**Comment by Vortalex** [comment]
I've noticed the same problem. You beat me to the punch. It's not that it doesn't stack properly, it's just not reapplying the aura at all if the aura already exists on the target by the same caster. Another example to use for replicating this would be to cast Warlock's Haunt spell 48181.

**Comment by kelno** [comment]
Thanks, I've updated issue description with your input.

**Comment by Keader** [comment]
I dont have spell system knowledge to fix it...
But my debug shows that's this lines fault: 

https://github.com/TrinityCore/TrinityCore/blob/cbacc72d934c10448762b67a0fa97ea4eb38cb63/src/server/game/Spells/Spell.cpp#L2771-L2772

_spellAura is not null to enter in ```if``` below, so it ignore stack stuff.
checking old core, logic now looks weird.

**Comment by PolarCookie** [comment]
https://github.com/TrinityCore/TrinityCore/commit/28288698441524081d583af95f19cb1c9fb90387 is the commit in question and lines

https://github.com/TrinityCore/TrinityCore/blob/a10870571558424033c2ffb41e4759e6581c8d86/src/server/game/Spells/Spell.cpp#L2765-L2772
should be straight up deleted, this issue closed and #21609, #21612 reopened, as there exists delayed, multitarget spells which stack auras, notably https://www.wowhead.com/spell=33657/resonance

**Comment by Aokromes** [comment]
a099974

**Comment by Killyana** [comment]
When the npc cast the spell 30531 it gather 3 stacks instead of only one also the scale doesn't change maybe not related to this issue.
rev. fb1d568fbaed

**Comment by kelno** [comment]
Yeah there is something wrong with a099974, aura is getting created for effect 0 then refreshed two times with the two remaining effects.

**Comment by PolarCookie** [comment]
This is fixed in https://github.com/TrinityCore/TrinityCore/pull/22794, but now https://dbwotlk.com/?spell=46598 broke and I'm still trying to figure out why.

**Comment by Aokromes** [comment]
i wonder if this can be the reason of decimation being broken.

**Comment by illfated** [comment]
Hmm. Maybe. Could be proc related -- I presume it doesn't trigger.
https://woehead.way-of-elendil.fr/?spell=63156/decimation
Depends on how it is broken, if parameters are needed for the spell or any error message/logs.
@Jildor : do you think it could be fixed in a similar way to your last PR?

**Comment by illfated** [comment]
Ah. Right. Sounds similar to quest spells which should work without a target.
I suspect that the spell needs to have its parameters redefined in its script(s).

**Comment by Jildor** [comment]
I'm sorry, I don't know whats happens here

**Comment by illfated** [comment]
Thanks for the feedback. We need to look at the aura spell ID instead:
https://woehead.way-of-elendil.fr/?spell=63165/decimation

| Spell Details |  |
|:----------:| --- |
| Effect # 1 | Apply Aura: Add Percent Modifier (Casting Time)Value: -20 |
| Effect # 2 | Apply Aura: No Reagent Use |

I'm a bit uncertain about where to go from there, but 2 is the missing effect.

**Comment by kelno** [comment]
I think the current fix (a099974) also breaks Seed of Corruption proc among other things, the dummy effect gets applied then removed immediately on spell hit (id: 27243).
https://github.com/TrinityCore/TrinityCore/pull/22794 seems to fix that particular issue as well.

**Comment by PolarCookie** [comment]
can confirm SoC works on #22794, haven't tested on a099974 but can take an educated guess what happens there.
