### ISSUE TITLE
DB/Creature: Wandering Forest Walker

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22285]
**Description:** The number of https://www.wowhead.com/npc=7584/wandering-forest-walker was increased on 3.2,  see the comments.

**Current behavior:** There's only 5 spawns

**Expected behavior:** More spawns must be added

**TC rev. hash/commit:**  rev. 8711c53

**Comment by offl** [comment]
Yeah but wowhead wasn't updated, they seems to change everything only between expansions
The coords shows actual paths
<details>
var g_mapper_data = {
--
  | 357: {
  | 0: { count: 178, coords: [[38.2,23.1],[38.4,21],[38.5,23.4],[38.6,21.3],[38.8,21.6],[39,24.2],[40.1,22.1],[40.4,24.5],[40.5,22.4],[40.7,22.5],[41,24.2],[41.4,25.7],[41.6,25.6],[42,24.9],[42.1,23.9],[43.7,24.9],[43.9,22.1],[51.2,48.4],[51.2,48.8],[51.5,48.6],[52,46.8],[53.3,46.6],[53.8,47.1],[54.3,68.5],[54.4,68.1],[54.5,69.8],[54.6,69.2],[54.8,67.4],[54.9,67.5],[55,47.3],[55,64.8],[55.2,47.6],[55.2,65.8],[55.4,63.9],[55.4,70.9],[55.5,59.3],[55.5,66.3],[55.6,61.4],[55.6,63.3],[55.6,63.8],[55.6,71.4],[55.6,71.7],[55.7,59.9],[55.7,61.5],[55.9,46.5],[56,72.8],[56.6,46.7],[57,73.2],[57.2,47.8],[57.9,50.8],[58.1,51.6],[58.1,74],[58.2,48],[58.3,74.5],[59.1,47.6],[59.4,52.1],[59.5,48.4],[59.5,52.1],[59.9,48.8],[60.3,49.5],[60.4,51.3],[60.6,51.1],[68.4,46.4],[68.5,46.6],[68.9,45.7],[69.2,51.4],[69.3,44.9],[69.3,51.5],[69.3,53.5],[69.4,42.3],[69.4,42.8],[69.4,44.3],[69.4,53.2],[69.5,44.6],[69.5,51.2],[69.5,51.6],[69.6,44.4],[69.6,53.3],[69.6,53.5],[69.7,42.5],[69.9,41.4],[70,41.8],[70,46.3],[70,60.4],[70.1,47.1],[70.1,60.7],[70.2,47.5],[70.5,46.4],[70.5,47],[70.6,60.1],[70.8,53.8],[70.9,53.3],[71,42],[71,57.7],[71.3,43.2],[71.3,43.5],[71.5,53.4],[71.5,53.5],[71.6,43.3],[71.6,58.3],[71.8,40.3],[71.8,41.2],[71.8,41.5],[72.2,59.4],[72.4,44.4],[72.4,44.5],[72.5,41.2],[72.5,44.4],[72.5,44.8],[72.5,56.6],[72.6,58.7],[72.9,55.7],[73.1,40],[73.2,51],[73.4,54.7],[73.4,57.8],[73.5,51.2],[73.5,58.5],[73.6,54.5],[73.7,54.1],[73.8,39],[74,51.7],[74.3,52.9],[74.3,57.4],[74.3,57.8],[74.5,57.3],[74.6,52.9],[74.6,53.5],[74.8,55.8],[75,38.3],[75.2,51.5],[75.4,38.7],[75.4,51.1],[75.6,51],[75.6,51.5],[75.7,39.2],[76.3,40.2],[76.3,40.5],[76.3,49],[76.5,48.7],[76.6,40.7],[76.6,48.4],[76.7,39.3],[77.3,40.4],[78.1,41.3],[78.2,47.8],[78.4,42.2],[78.4,42.5],[78.5,42.3],[78.7,43.9],[78.7,48.1],[78.8,38],[78.9,42.9],[78.9,44.5],[79.2,38.5],[80.4,38.4],[80.4,38.8],[80.5,38.4],[80.6,38.9],[81.3,45.2],[81.6,45.3],[84.3,38.5],[84.4,38.3],[84.6,38.5],[84.7,38.4],[85.7,43.4],[85.9,43.9],[85.9,45.5],[86.1,44.8],[86.5,41.6],[86.6,41.4],[87.3,44.1],[87.3,44.6],[87.6,44.5],[87.8,42.5],[87.9,42.4],[87.9,44.4],[88.5,45.4]] }
  | }
  | };
</details>

Maybe you can use the cata spawns but there's too much of them

**Comment by Kittnz** [comment]
What i found from sniffs from wrath.

```sql
(@CGUID+1931, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4338.483, -683.7444, -30.53012, 4.621318, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)
(@CGUID+1934, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4427.19, -661.3543, -14.01237, 3.076181, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)

(@CGUID+554, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4277.734, -577.9316, -10.89243, 2.73388, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+555, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4337.464, -669.8854, -31.81298, 1.494931, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+556, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4419.029, -637.1534, -15.76648, 3.120111, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+559, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4369.188, -533.3929, 8.425774, 2.35067, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)
(@CGUID+571, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4350.682, -50.00621, 54.83132, 5.545178, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)
(@CGUID+579, 7584, 1, 357, 0, 1, 1, 0, 0, 0, -4240.287, 171.1342, 58.67483, 1.815345, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+622, 7584, 1, 357, 2518, 1, 1, 0, 0, 0, -4123.302, -38.17434, 60.95847, 4.899057, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 2518 - Difficulty: 0)

(@CGUID+35, 7584, 1, 357, 2518, 1, 1, 0, 0, 0, -4247.73, 147.1846, 58.22672, 3.536234, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 2518 - Difficulty: 0)
(@CGUID+83, 7584, 1, 357, 0, 1, 1, 0, 0, 0, -4751.078, 621.162, 44.7485, 0.407713, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)

(@CGUID+666, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4450.787, -546.1805, 11.6428, 2.897247, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+667, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4485.163, -515.1431, 12.28099, 1.086292, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+671, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4433.816, -640.0276, -13.42026, 3.805205, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+673, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4468.881, -552.8833, 10.3777, 3.965646, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+674, 7584, 1, 400, 0, 1, 1, 0, 0, 0, -4394.776, -526.709, 9.359841, 1.473069, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)
(@CGUID+683, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4174.38, -145.5162, 55.91825, 3.266917, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)
(@CGUID+691, 7584, 1, 357, 1137, 1, 1, 0, 0, 0, -4258.124, 125.5109, 58.75974, 4.084282, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 1137 - Difficulty: 0)
(@CGUID+747, 7584, 1, 357, 0, 1, 1, 0, 0, 0, -4747.854, 614.676, 44.39301, 2.433602, 120, 0, 0, 0, 0, 0, 0, 0, 0, 11159), -- 7584 (Area: 0 - Difficulty: 0)

**Comment by Killyana** [comment]
19 extra spawns looks fine.

**Comment by Kittnz** [comment]
Thats all i have for wrath spawns. Did cata change a lot in that area?

**Comment by Aokromes** [comment]
No.

**Comment by Kittnz** [comment]
Then we should be able to get all spawns.
