### ISSUE TITLE
Whispers from horde player to alliance gm and vice versa

### ISSUE THREAD

**Issue by SoyTorete** [TrinityCore/TrinityCore#22283]
I have seen there is a closed issue about this https://github.com/TrinityCore/TrinityCore/issues/22271
I am having the same problem.
And not only me, I have asked a friend if he can compile and try.
We both have the same issue.
Aokromes closed the issue, but I would like to ask if someone can just try a new fresh compilation and check this.

This is tested on Debian 9, windows 7, windows 8.1
Tested revisions:
e5b8b1e99a4e7361be862ae6e1f29189907167e4
0df3cb5bcc8097070b1f215032d3914d6a577f01
cbacc72d934c10448762b67a0fa97ea4eb38cb63
TDB: 335.64
Branch: 3.3.5a

**Comment by WOW-Reborn** [comment]
I confirm. Simular issue i have. Currently running one horde and one alliance character to talk to everyone

**Comment by Killyana** [comment]
Confirmed

**Comment by Winchester1987** [comment]
Confirm
And thanks for testing this time.

**Comment by Meltie2013** [comment]
I can confirm this as well.

**Comment by Gooyeth** [comment]
Hi, I need you to help me test: #22298

**Comment by jackpoz** [comment]
The PR has been reverted
