### ISSUE TITLE
[3.3.5] Blastenheimer 5000 Ultra Cannon (Darkmoon)

### ISSUE THREAD

**Issue by D3thw0lf** [TrinityCore/TrinityCore#2229]
Good Day,
I want to say that the Blastenheimer 5000 Ultra Cannon do not work. I'm so sorry (when you know that) but this is my first report.
(And I hope you understand me , because my english isn't the best ;D)

I hope it will be fixed soon. Have a nice day :)
##

**Comment by Rushor** [comment]
okay i could convert this: http://pastebin.com/0gNG5cBn

My current problem: the spell kicks the player in ANY direction and not directly towards the lake.
Is there a possibility to relocate the position of the unit for this spell?

**Comment by joschiwald** [comment]
caster should not equal the target

try:
`go->CastSpell(player, 42867, true);`

**Comment by Rushor** [comment]
\o/

go->CastSpell(player, 42867);

this worked, thx!

the duration of the buff seems to be too short :D every time one will die on the ground. i will pr this for the other goes soon :)

**Comment by DDuarte** [comment]
Do not close your issue because someone posted a fix. You reported a Trimity issue therefore it should be fixed on Trinity.

**Comment by Rushor** [comment]
some more improvement https://gist.github.com/Rushor/1f78501492e831de5416

**Comment by Aokromes** [comment]
@Rushor can you merge this fix?

**Comment by offl** [comment]
Same as in https://github.com/TrinityCore/TrinityCore/issues/17840#issuecomment-359564220
The orientation depends on player location, probably.
Or very likely it depends by cannon's orientation. Look closely https://www.youtube.com/watch?v=_Tr82lm4n30

**Comment by tkrokli** [comment]
@offl : I don't think assigning Rushor to this issue will be useful, he is not a member of TC anymore. If you check his page, you will see that he is only member of the Dalaran-wow community.

**Comment by offl** [comment]
He was unassigned :)
Don't know how it works, but it is automatic.

**Comment by tkrokli** [comment]
My bad, you're right (I should get myself new reading glasses). :-P
