### ISSUE TITLE
DB/Creature: George Candarte (2698) is invisible

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#22293]
**Description:**

Like @Rushor noted in https://github.com/dalaranwow/dalaran-wow/issues/5420 , George Candarte (entry 2698) has an invisible model here on TrinityCore 3.3.5 too, while he should look like an undead male.
- https://wow.gamepedia.com/George_Candarte
- https://woehead.way-of-elendil.fr/?npc=2698
- https://www.wowhead.com/npc=2698/george-candarte

**Current behaviour:**

It looks like George Candarte (entry 2698) has an invisible or invalid model. Only his weapon and an off-hand flask are visible.

![george candarte](https://user-images.githubusercontent.com/38162891/44367358-cbd94700-a4cf-11e8-9c9e-65d812c2f802.png)

This is the first time I have visited this creature ever, but I suspect that he has been like this for some time here on TrinityCore.

**Expected behaviour:**

George Candarte (entry 2698) should be visible and shown as an undead male:

![image](https://user-images.githubusercontent.com/38162891/44367477-325e6500-a4d0-11e8-9e4e-e8bee40458e8.png)

**Steps to reproduce the problem:**

1. Log on to a horde character (or `.gm on` if using an alliance character).  
2. `.go creature id 2698` (he is standing near the north end of Thoradin's Wall in Hillsbrad Foothills)
3. Observe that only his hand-held items can be selected and are visible.

**Branch(es):**

3.3.5 and likely master branch, he is still active according to wow.gamepedia.com and wowhead.

**TC rev. hash/commit:** 

TrinityCore rev. eb1972f21d6e 2018-08-20 19:04:21 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10 Home x64 version 1803 (OS build 17134.228)

**Comment by illfated** [comment]
BTW, if you would like to have a quick look at the current `creature_template` data on this creature in TDB 335.64, here it is:
```sql
SELECT * FROM `creature_template` WHERE `entry`= 2698;
```
```
entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name             subname                  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family  trainer_type  trainer_spell  trainer_class  trainer_race    type  type_flags  lootid  pickpocketloot  skinloot  resistance1  resistance2  resistance3  resistance4  resistance5  resistance6  spell1  spell2  spell3  spell4  spell5  spell6  spell7  spell8  PetSpellDataId  VehicleId  mingold  maxgold  AIName  MovementType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  spell_school_immune_mask  flags_extra  ScriptName  VerifiedBuild
-----  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ---------------  -----------------------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------------  -------------  -------------  ------------  ------  ----------  ------  --------------  --------  -----------  -----------  -----------  -----------  -----------  -----------  ------  ------  ------  ------  ------  ------  ------  ------  --------------  ---------  -------  -------  ------  ------------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  ------------------------  -----------  ----------  -------------
 2698                   0                   0                   0            0            0      3680         0         0         0  George Candarte  Leatherworking Supplies  (NULL)                 0        31        31       0       68      128           1    1.14286       1       0          0            2000             2000             1              1           1       37376         2048             0       0             0              0              0             0       7           0       0               0         0            0            0            0            0            0            0       0       0       0       0       0       0       0       0               0          0        0        0                     0            1             1.1             1              1               1                   1             0           0            1                     0                         0            2                      12340
```

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID` IN (3680);

**Comment by illfated** [comment]
Thank you., that is the correct solution. 👍
I had forgotten that "feature" in DB. 😅
