### ISSUE TITLE
Core/Spells: Spells with knockback and miscvalue of 0 do not work against creatures

### ISSUE THREAD

**Issue by Vortalex** [TrinityCore/TrinityCore#22295]
**Description:**

Spells with a knockback effect and a miscvalue of 0 do not correctly knockback creatures, but they do correctly knockback players. If the miscvalue is anything higher than 0, it knocks back both creatures and players correctly.

**Current behaviour:**

Spells that knockback the target do not knockback if the miscvalue is set to 0, but they do correctly work against players.

**Expected behaviour:**

Spells with knockback should knockback creatures regardless of miscvalue.

**Steps to reproduce the problem:**

1. You would need to create a spell that has a SpellEffectKnockback (value 98) and a base value set to anything (100 will do) and a target of value 6 (enemy). Make sure your miscvalue is set to 0 (no XY directional speed)
2. Cast the spell against an enemy player, and notice that the knockback blasts the player directly up into the air.
3. Cast the spell against an enemy creature, and notice that the knockback never applies.
4. Go back and change the miscvalue on the spell to anything other than 0 (50 will do)
5. Cast the spell against the enemy player and creature again and notice that the knockback works correctly on both targets

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TC rev 2ef331584868 2018-07-11 18:14:09 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Win 10

**Comment by Killyana** [comment]
Duplicates of https://github.com/TrinityCore/TrinityCore/issues/19210 ?

**Comment by Vortalex** [comment]
Ah, yeah I guess so. This issue is over a year old and still not fixed? Lord.

**Comment by illfated** [comment]
Well, when it comes to movement issues, it often tends to be long or tedious work for the coders to find a solution.
Note **ariel-**'s comment from Feb 28, 2017:
> Took a look at this, is not a spell issue, rather a movement issue. Splines are currently not launched for vertical movements.

Unless it is something really game breaking, coders tend to focus on things they find more interesting or important.

**Comment by Vortalex** [comment]
Well, for spells that knockup enemies, it's a little bit important.
