### ISSUE TITLE
Bloodworms 28017

### ISSUE THREAD

**Issue by yvomsx** [TrinityCore/TrinityCore#22304]
**Description:**

2018-08-23_19:44:01 ERROR [misc.movesplineinitargs] MoveSplineInitArgs::Validate: expression 'velocity >= 0.01f' failed for GUID: 0 Entry: 28017

**Current behaviour:**
Error in worldserver.

CHANGEME Tell us what happens.
Whenever a Deathknight is in a dungeon and his bloodworms are attacking the error is spammed in the world server for about 5 or 6 times.

**Expected behaviour:**
No messages should be spammed.

CHANGEME Tell us what should happen instead.
Mentioned above

**Steps to reproduce the problem:**
Play a blood deathknight and the above message will be triggered when bloodworms are being used in a dungoen.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
50f70a3fafd53b5c8b0ca08e9d5fb760d9316f41

**Operating system:** WIN64

**Comment by Keader** [comment]
My change was based in Shade of Akama encounter, where Shade of Akama can have velocity below 0.1f
Looks like @Ovahlord found some encounters with velocity below 0.01f, so, this check need be updated

**Comment by Ovahlord** [comment]
There are indeed some game parts where the velocity can go below 0.01f. The Plants vs. Zombies questline for example has super slow zombies that can be slowed even further.

**Comment by yvomsx** [comment]
Im pretty sure the check was not added with the consideration there are creatures going under 0.1 velo, i guess a check for negative numbers would do?

**Comment by Ovahlord** [comment]
It is 0.01 already. It can be even smaller tho.

**Comment by yvomsx** [comment]
Set to 0.01 resulted in no more errors.

**Comment by Faq** [comment]
@yvomsx  you meant 0.001?

**Comment by yvomsx** [comment]
Yes correct, 0.001 my bad.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f1f05767edf35d759d107d3fad4ec56d6d2a3202
