### ISSUE TITLE
[CRASH] Death comes from on High

### ISSUE THREAD

**Issue by pedroevil51** [TrinityCore/TrinityCore#22307]
**Description:**

Server Crash on the Quest Death comes from on High

**Current behaviour:**
Crashes when clicking to start the timed event of the eye
https://pastebin.com/KbLFedds

**Expected behaviour:**

Not crash

**Steps to reproduce the problem:**

1. Create DK - Quest add 12641
2. Click on the Eye control mechanism
3. See as the server crashes

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/d2d9f470c388a80d395e9a49a860ceb0b7e27fd3

**Operating system:** WS 2012 R2

**Comment by Meltie2013** [comment]
I got the same result with a crash log here.

https://pastebin.com/RCYKcKhb

**Branch(es):**
3.3.5a

**TC rev. hash/commit:**
https://github.com/TrinityCore/TrinityCore/commit/d2d9f470c388a80d395e9a49a860ceb0b7e27fd3

**Operating system:**
Ubuntu 18
