### ISSUE TITLE
[3.3.5] DB/Gameobject: Indurium Mineral Vein (19903) gives no loot when mined

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#22317]
**Description:**

Zone/instance: Uldaman (https://woehead.way-of-elendil.fr/?zone=1337)
- quest Indurium Ore (https://woehead.way-of-elendil.fr/?quest=1192)
- item Indurium Ore (https://woehead.way-of-elendil.fr/?item=5833)
- object Indurium Mineral Vein (https://woehead.way-of-elendil.fr/?object=19903)

Mining skill 150 or higher is required to mine Indurium Ore from Indurium Mineral Vein.

**Current behaviour:**

After performing the skill 'mining' on Indurium Mineral Vein, the vein despawns, but no loot drops into the backpack.

**Expected behaviour:**

After performing the skill 'mining' on Indurium Mineral Vein, 2-4 items of Indurium Ore should be found in your backpack.

**Steps to reproduce the problem:**

1. get a level 40 (or higher) character with mining skill and get ready to land among aggressive NPCs (`.gm on` is a useful preparation)
2. `.go object 40689` / `.go object 40690` / `.go object 40691` and assess the amount of surrounding hostile NPCs
3. perform mining (150+) on the object, preferably with `.gm off`
4. Notice that it despawns. Check your bag and chat log to see that there is no sign of any such loot.

**Branch(es):**

3.3.5 (removed from World of Warcraft in patch 4.0.3a.)

**TC rev. hash/commit:** 

TrinityCore rev. 151ed6f684b4 2018-08-26 16:15:54 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10 Home x64 version 1803

**Comment by illfated** [comment]
Hmm, maybe the quest requirement is incorrect? Should we change `QuestRequired` to 0, perhaps?
The quest can't be picked up, it is a repeatable hand-in quest and can only be accessed if you already have got Indurium Ore x 4.
```sql
SELECT * FROM `gameobject_loot_template` WHERE `Item`=5833;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  ---------
 3266    5833          0     100              1         1        0         2         4  (NULL)
```
BTW, why is the `Entry` value 3288? I thought that would be the `gameobject_template`.`entry`
-- but that suggests the gameobject "Cauldron" (guid 15118) in the Bael Modan digsite in The Barrens
instead of Indurium Mineral Vein (entry 19903, guid 40689, 40690, 40691)

**Comment by Killyana** [comment]
LootID for Gameobjects is not the entry but from Data on gameobject_template.
