### ISSUE TITLE
[CRASH] Random Crash 

### ISSUE THREAD

**Issue by pedroevil51** [TrinityCore/TrinityCore#22314]
**Description:**

The Server crashed, i tried to debug but could not find anything

**Current behaviour:**

Server Crashed at Random , i don't know what caused it
https://gist.github.com/pedroevil51/5f794fd79c14941e753f076b5bddd926

**Expected behaviour:**

Not Crash

**Steps to reproduce the problem:**

1. Server UP for about 6-7 hours no problem, then crashed 
I Tried to debug, but din't find anything

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/d4ef2529e91043bc719c3238714413fd21c9005c
**Operating system:** Windows Server 2012 R2

**Comment by jackpoz** [comment]
Most likely fixed by https://github.com/TrinityCore/TrinityCore/commit/ec1cfa36f4c286ad8037516460a4e99ea5d7a5ed
