### ISSUE TITLE
DB/Gossip: Doctor Gregory Victor is using Doctor Gustaf VanHowzen's gossip

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#22324]
**Description:**

Doctor Gregory Victor is currently using Doctor Gustaf VanHowzen's gossip instead of his own.
- https://www.wowhead.com/npc=12920/doctor-gregory-victor
- https://www.wowhead.com/npc=12939/doctor-gustaf-vanhowzen

```sql
-- some useful queries to find the info in TDB 335.64 (world)
SELECT * FROM `creature_template` WHERE `entry` IN (12920,12939);
SELECT * FROM `broadcast_text` WHERE `ID` IN (8969,8974);
SELECT * FROM `npc_text` WHERE `BroadcastTextID0` IN (8969,8974);
SELECT * FROM `npc_text` WHERE `ID` IN (6413,6415);
SELECT * FROM `gossip_menu` WHERE `TextID` IN (6413,6415);
SELECT * FROM `gossip_menu` WHERE `MenuID` IN (5381,5382);
SELECT * FROM `creature_template` WHERE `gossip_menu_id` IN (5381,5382);
```

**Current behaviour:**

![image](https://user-images.githubusercontent.com/38162891/44686590-03f00500-aa4f-11e8-8e75-d9f6c8ea3293.png)

**Expected behaviour:**

He should instead be using his own text:
`Greetings, $N. I am Doctor Gregory Victor, head trauma surgeon of Horde Trauma.`

**Steps to reproduce the problem:**

1. `.go creature id 12920`
2. Talk to Doctor Gregory Victor (open his gossip window)
3. Notice that he is using the Alliance text instead of the Horde text.

(or simply use the SQL queries listed at the start of this issue post)

**Branch(es):**

3.3.5, maybe master (I don't have TDB 735.00 configured on my computer)

**TC rev. hash/commit:** 

TrinityCore rev. 4e5d1b70219d 2018-08-27 20:41:07 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows 10 Home x64 version 1803

**Suggested solution:**
```sql
-- Doctor Gregory Victor
UPDATE `creature_template` SET `gossip_menu_id`= 5381 WHERE `entry`=12920 AND `gossip_menu_id`=5382;
```

**Comment by illfated** [comment]
Anyone got time to check this info on TDB 735.00 / `master` ?

**Comment by Killyana** [comment]
`gossip_menu_id`= 5381 on master and 4.3.4
