### ISSUE TITLE
Achievement Hadronox Denied counts on both Normal and Heroic difficulties.

### ISSUE THREAD

**Issue by nagrandbugtracker** [TrinityCore/TrinityCore#22322]
**Description:**

Achievement Hadronox Denied counts in both Heroic and Normal. Normally, it should only count on Heroic mode, not on both. Achievement ID : 1297

**Current behaviour:**

Kill the big spidey, and you get achievement in normal difficulty.

**Expected behaviour:**

If in normal difficulty, achievement should NOT count, only in heroic mode.

**Steps to reproduce the problem:**

1. Go to dungeon.
2. Go to Hadronox
3. Kill Hadronox before he moves up the tunnel.
4. Get achievement
5. Profit.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 151ed6f684b4+ 2018-08-26 16:15:54 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Operating system:** 
Debian 9 x64

**Comment by Aokromes** [comment]
fbef398
