### ISSUE TITLE
Core/Spell [3.3.5] DK Spell - [Hungering Cold]

### ISSUE THREAD

**Issue by diegobfl** [TrinityCore/TrinityCore#22333]
**Description:**

DK's Spell [Hungering Cold] does not work properly.

**Current behavior:**

When the spell is cast on the targets it freezes all that are around, the more when you will attack only 1 target frozen all the others will be thawed

**Expected behavior:**

When using the spell [Hungering Cold] it should freeze all targets around, and when attacking again only 1 target frozen the others should not thaw.

**Steps to reproduce the problem:**

Launch the spell on the 2 or more targets and attack only 1 target and the others must not thaw

Subsidiary (s):

3.3.5

TC rev. hash / commit:

TC rev https://github.com/TrinityCore/TrinityCore/commit/da21ca80fc35a325df0fb0ef2f687a91121d42de

Operational system:

Win 8 R2

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/22051 the aura will be dispelled from all targets that have the same aura instead of only the player effected by the dispel.

**Comment by Killyana** [comment]
Duplicates of  #21810
