### ISSUE TITLE
Issue with Skybreaker npc's on login

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22339]
**Description:**
When you log into a character placed on the Skybreaker in Icecrown, all npcs slide off as if not connected to the ship.
Flying out of visual range and then back again fixes it to normal.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
56877d23601980d8a2637b1717574c6b39d66943

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21946

**Comment by PolarCookie** [comment]
The Skybreaker doesn't have the '100-yard difference' issue like Ogrim's Hammer, all npc's spawn instantly and are visually stable, but they don't follow the ship movement when you log on.

**Comment by illfated** [comment]
OK, so maybe the closed issue **NPC placement glitch on Skybreaker** #20011 is closer to this issue.

**Comment by PolarCookie** [comment]
That's it! :heart:  Illfated
