### ISSUE TITLE
Core/SAI: SMART_ACTION_REMOVE_MOVEMENT

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22346]
**Description:** The action doesn't work anymore.

**Current behavior:**  The movement from creature table (waypoint, random movement) doesn't stop.

**Steps to reproduce the problem:**
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (-77358) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`)  VALUES
(-77358,0, 0,0,1,0,100,1,10000,10000,0,0, 127,2,1,0,0,0,0,1,0,0,0,0,0,0,0, 'npc - ooc no repeat - stop movement');
```
1. Execute the sql above
2. .go c 77358
3. Notice the npc will not stop the waypoint after 10 secs

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. b4a1887c4d8d

**Comment by ccrs** [comment]
- **action_param1**: movementType

```c++
enum MovementGeneratorType : uint8
{
    IDLE_MOTION_TYPE                = 0,     // IdleMovementGenerator.h
    RANDOM_MOTION_TYPE              = 1,     // RandomMovementGenerator.h
    WAYPOINT_MOTION_TYPE            = 2,     // WaypointMovementGenerator.h
    MAX_DB_MOTION_TYPE              = 3,     // Below motion types can't be set in DB.
    CONFUSED_MOTION_TYPE            = 4,     // ConfusedMovementGenerator.h
    CHASE_MOTION_TYPE               = 5,     // ChaseMovementGenerator.h
    HOME_MOTION_TYPE                = 6,     // HomeMovementGenerator.h
    FLIGHT_MOTION_TYPE              = 7,     // FlightPathMovementGenerator.h
    POINT_MOTION_TYPE               = 8,     // PointMovementGenerator.h
    FLEEING_MOTION_TYPE             = 9,     // FleeingMovementGenerator.h
    DISTRACT_MOTION_TYPE            = 10,    // IdleMovementGenerator.h
    ASSISTANCE_MOTION_TYPE          = 11,    // PointMovementGenerator.h
    ASSISTANCE_DISTRACT_MOTION_TYPE = 12,    // IdleMovementGenerator.h
    TIMED_FLEEING_MOTION_TYPE       = 13,    // FleeingMovementGenerator.h
    FOLLOW_MOTION_TYPE              = 14,    // FollowMovementGenerator.h
    ROTATE_MOTION_TYPE              = 15,    // IdleMovementGenerator.h
    EFFECT_MOTION_TYPE              = 16,
    SPLINE_CHAIN_MOTION_TYPE        = 17,    // SplineChainMovementGenerator.h
    FORMATION_MOTION_TYPE           = 18,    // FormationMovementGenerator.h
    MAX_MOTION_TYPE                          // limit
};
```

- **action_param2**: forced

Right now the behaviour is:

1. Locate if there is a generator with the given MovementType in MOTION_SLOT_ACTIVE
2. Remove it
3. If _forced_ is set, execute StopMoving


NOTES:
- MOTION_SLOT_DEFAULT is currently not affected by this. In common terms, DB set movements are not affected by the Remove part.
- _Remove_ means **Remove**, the generator will be erased from existance, wont be there in the future.

**Comment by ccrs** [comment]
Notice that the step 3, the StopMoving call, is executing regardles of the result of steps 1 and 2.

But that wont solve the issue u are mentioning because the generator, in this case RandomMovementGenerator, will just send a new movement on its next check.

Solutions:
- Add a parameter to the action to signal the motion slot it affects. Problem: if used on a DB set generator, it wont reapear till some event reloads or resets MotionMaster, commonly evade.
- Implement ```SMART_ACTION_PAUSE_MOVEMENT```

**Comment by ccrs** [comment]
How many scripts are affected by this? I thought there were none. Even made the query IIRC.

**Comment by ccrs** [comment]
I don't know if the documentation was updated on the wiki page, made the request for someone with access to do it though.

**Comment by Killyana** [comment]
Yes there's no SAI that use this action, but I need it for this one:
https://github.com/TrinityCore/TrinityCore/issues/21570#issuecomment-417090178

This action is supposed to allow the control of movements that are not from SAI actions.
I prefer adding a parameter to the action to signal the motion slot that affects.

Also I think It's better to have full control and the possibility to resume the movement from MOTION_SLOT_DEFAULT without calling and evade.
