### ISSUE TITLE
[3.3.5] DB/Quest-Creatures : Drake Hunt missing creatures. Quest ID: 11940

### ISSUE THREAD

**Issue by nagrandbugtracker** [TrinityCore/TrinityCore#22347]
**Description:**

Creatures (ID: 21627) are missing entirelly in Coldarra map. Quest cannot be completed, manual spawning gives a creature without a waypoint.
**Current behaviour:**

Creatures are missing, manual spawn makes stationary and without a waypoints.

**Expected behaviour:**

https://www.youtube.com/watch?v=JSefFj2rNlY

**Steps to reproduce the problem:**

1. .q ad 11940
2. .tele coldarra
3. Look around for Nexus Drake Hatchlings.
OPTIONAL:
4. .npc add 21627

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 75e7404bba8c+ 2018-08-28 19:42:18 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:** Debian 9 x64

**Comment by Killyana** [comment]
There's 7 https://www.wowhead.com/npc=26127/nexus-drake-hatchling spawned

**Comment by illfated** [comment]
@nagrandbugtracker : apparently, your code has got some additional code which may cause unwanted behaviour.
Test again on 100% clean TC source & DB to see that it works as intended.
