### ISSUE TITLE
3.3.5a authserver undefined behavior compiling with C++17

### ISSUE THREAD

**Issue by jameyboor** [TrinityCore/TrinityCore#22343]
**Description:**

When compiling 3.3.5a TC x64 Release MSVC 2017 C++17, the authserver will not work.

Compiling the project authserver and the requirements for authserver (common, database & shared) as C++17 introduces a bug in Release:

In Debug builds the authserver will work correctly.
In RelWithDebInfo or Release builds the authserver will not work correctly. It will reject the player's credentials even if they're correct.

A short video of the problem occuring: https://www.youtube.com/watch?v=pVQoAlbXnkc (sorry for the quality)

**What I've tried:**

Switching from MySQL to MariaDB, no luck.
Switching OpenSSL versions (1.0.2 - 1.1.0i), no luck.
Switching Boost versions ( 1.64 - 1.68), no luck.
Building my own Boost binaries with /std:c++17 set, no luck.

MSVC Info:

Microsoft Visual Studio Enterprise 2017 
Version 15.8.1
Installed Version: Enterprise
Visual C++ 2017
Microsoft Visual C++ 2017

---

This sounds like UB that has surfaced with a compiler & optimizer upgrade (since it doesn't happen in debug), but I have yet to find where.

I'd like to invite anyone that wants to, to build auth and its requirements in GCC or Clang (no MinGW) and post back the results. This way a compiler bug is ruled out.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
(pick your poison, all recent commits thus far), currently on b4a1887c4d8df5a7729ed5c4126f6a7655a02127.

**Operating system:** Win 7 x64 Ultimate

**Comment by Killyana** [comment]
I'm using:
Microsoft Visual Studio Community 2017
Version 15.5.2
Installed Version: Community
Visual C++ 2017
Microsoft Visual C++ 2017
Boost 1.67

And I compile x64 on release and debug without any issue related to authserver

**Comment by jameyboor** [comment]
That's because your toolset isn't set to C++17.

You should add 
```
set (CMAKE_CXX_STANDARD 17)
```
To your root CMakeLists.txt

And then open cmake/macros/FindPCHSupport.cmake, and edit:
```
set_property(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 14)
```

To
```
set_property(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 17)
```

Then re-configure and generate CMake. Then all projects will be using C++17, retry after doing that.

**Comment by Warpten** [comment]
I faced a similar issue when writing my own grunt client, this is likely to be a cache fail or an optimizer bug. I fixed it by being aggressive with the optimizer. See https://github.com/Warpten/wowgm/issues/1.

**Comment by jameyboor** [comment]
Thanks @Warpten, I'll try that.

**Comment by Warpten** [comment]
The idea was to prevent the optimizer from being too brutal. This is a band-aid, but a simple repro test case doesn't bug out and thus can't be submitted as a ticket to MS.

**Comment by jameyboor** [comment]
Really hard to provide some repro case to submit as issue ticket then.

**Comment by jameyboor** [comment]
My mistake.

I tried your rewrite and that seems to have worked, thanks @Warpten. Now onto reproducing a small case for bug reporting.

**Comment by jackpoz** [comment]
> Version 15.8.1

could you try with a more recent VS 2017 version or even VS 2019 ? See for example these /std:c++17 related issues in VS 2017 15.8.1:
- https://developercommunity.visualstudio.com/content/problem/313340/c-vs-2017-update-8-difference-in-member-function-p.html
- https://developercommunity.visualstudio.com/content/problem/322651/code-generated-by-vc-1581-compiler-lead-to-crash.html

**Comment by jameyboor** [comment]
@jackpoz Will test when I get the chance.

@Warpten Your issue linked 404'd, do you still remember what method needed edits? It was something in HandleLogonProof right?

**Comment by illfated** [comment]
Only 1 searchable repository named "wowgm" on all of Github: https://github.com/bmjoy/wowgm

**Comment by jameyboor** [comment]
https://github.com/bmjoy/wowgm/blob/master/src/wowgm/Protocol/Authentification/AuthSocket.cpp#L185 found it, thanks @illfated .

**Comment by Warpten** [comment]
Oops, I moved the repo to private. Won't move it back for now.

**Comment by Aokromes** [comment]
anyone can test this on latest VS 2017 (15.9.16) and latest VS 2019? we are looking to use C++17 features ASAP.

**Comment by jackpoz** [comment]
I made a PR to enable C++17, much easier than having to manually edit files (why don't people push changes to branches instead of writing manual steps ?)

I still need to raise VS version to a C++17-working one

**Comment by Warpten** [comment]
> (why don't people push changes to branches instead of writing manual steps ?)

The TLDR is that I don't have a clone of TC.

**Comment by jackpoz** [comment]
You patch is not needed and it doesn't enable c++17 in cmake, so I didn't mean you :)

**Comment by Aokromes** [comment]
anyone? https://github.com/TrinityCore/TrinityCore/issues/22343#issuecomment-534041584

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23868 works fine and raises VS version

**Comment by ryancheung** [comment]
I tested https://github.com/TrinityTBC/core/commit/45cd1850790e54f752ffd9d0cd508417604c6241 and every thing just works fine in Release build .

VS version: Visual studio 2017 Community
msvc version: 14.16.27023
cl.exe version:  19.16.27034

It's time to step into c++17.
