### ISSUE TITLE
Compiling errors isFeared and isFrozen

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22349]
**Description:**

Updated server now while I am compiling I am receiving a huge amount of errors all related to isFeared and isFrozen isn't a member of unit.

**Current behaviour:**

When compiling Visual Studio 2017 Community issues out a few hundred errors regarding isFrozen and isFeared not being a member of unit.

**Expected behaviour:**

Should compile without errors.

**Steps to reproduce the problem:**

Do a pull on your TrinityCore 3.3.5 clone and attempt to compile it in Visual Studio.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c78f454c0ee74000ab7f77463e8b44ff7480fdec

**Operating system:** 

Windows Server 2016

**Comment by Treeston** [comment]
These methods do not exist on latest `3.3.5` revision. Are you using a modified core?

**Comment by leviathonbeast** [comment]
confirmed cannot reproduce. i just compiled a fresh clone of 3.3.5 on vs 2017

**Comment by WOW-Reborn** [comment]
Sorry guys it was my fault apparently my merging application didn't have one little box checked and it didn't see the comment made to a map file where isFrozen was changed to isRooted.  Merged it and works fine now. Thanks for the input.
