### ISSUE TITLE
Issue with Orgim's Hammer npcs

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22340]
**Description:**
Npcs on Ogrim's Hammer in Icecrown periodically phase away and back again.
This can be particularly pronounced when either logging on while on the ship, or approaching by flight, where it can take several seconds, if at all, for the npcs to appear.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
56877d23601980d8a2637b1717574c6b39d66943

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21946
