### ISSUE TITLE
DB/World fix orgrimmar guard gossip text

### ISSUE THREAD

**Issue by leviathonbeast** [TrinityCore/TrinityCore#22348]
**Description:**

Fix Orgrimmar Guard Gossip
It was taken from a 8.0.1.xxxxx sniff but if i remember the guard gossip never changed from 7.3.5 to now

**Current behaviour:**

well they say Greetings Name

**Expected behaviour:**

actually display some useful guard gossip

**Steps to reproduce the problem:**

1. talk to a guard in orgrimmar id 3296

**Branch(es):**

 Master

**TC rev. hash/commit:** 
TrinityCore rev. f70a67772073 2018-08-29 17:48:53 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
https://github.com/TrinityCore/TrinityCore/commit/f70a677720733e0bc7a6756034d4f837b78be6bf

**Operating system:** 

Win/Linux/Mac anything that runs Trinity.

**Suggested Fix**:

https://gist.github.com/leviathonbeast/e510b8f51ca3998d75e64f3ea3893143

**Comment by shamage** [comment]
@leviathonbeast  : can you give me a functional sniff for wow ver. 8.0.1.xxx?


I should be interested in sniffing - and learning to do it (Unfortunately, the description of how it was done was unsuccessful for me) I could not start running a sniff yet - thx

**Comment by leviathonbeast** [comment]
https://arctium.io/files/?f=15a5d276664246

**Comment by leviathonbeast** [comment]
quick parse for the POIs too 

for some reason the sniffer got the ids wrong in like 2 of them so far i noticed. it mixed up the id for Embassy and put it for Guild Services instead lol.

`DELETE FROM `gossip_menu_option_action` WHERE (`MenuId`=1942 AND `OptionIndex`=0) OR (`MenuId`=1951 AND `OptionIndex`=14) OR (`MenuId`=1942 AND `OptionIndex`=1) OR (`MenuId`=1942 AND `OptionIndex`=2) OR (`MenuId`=1942 AND `OptionIndex`=3) OR (`MenuId`=1942 AND `OptionIndex`=4) OR (`MenuId`=1942 AND `OptionIndex`=5) OR (`MenuId`=1942 AND `OptionIndex`=6) OR (`MenuId`=1951 AND `OptionIndex`=13) OR (`MenuId`=1942 AND `OptionIndex`=7) OR (`MenuId`=1942 AND `OptionIndex`=8) OR (`MenuId`=1942 AND `OptionIndex`=9) OR (`MenuId`=1942 AND `OptionIndex`=10) OR (`MenuId`=1942 AND `OptionIndex`=11) OR (`MenuId`=1942 AND `OptionIndex`=12) OR (`MenuId`=1942 AND `OptionIndex`=13) OR (`MenuId`=1942 AND `OptionIndex`=14) OR (`MenuId`=1942 AND `OptionIndex`=15) OR (`MenuId`=1942 AND `OptionIndex`=16) OR (`MenuId`=1951 AND `OptionIndex`=15) OR (`MenuId`=9727 AND `OptionIndex`=1) OR (`MenuId`=1951 AND `OptionIndex`=16) OR (`MenuId`=9727 AND `OptionIndex`=0) OR (`MenuId`=12245 AND `OptionIndex`=8) OR (`MenuId`=12245 AND `OptionIndex`=7) OR (`MenuId`=12245 AND `OptionIndex`=6) OR (`MenuId`=12245 AND `OptionIndex`=5) OR (`MenuId`=12245 AND `OptionIndex`=4) OR (`MenuId`=12245 AND `OptionIndex`=3) OR (`MenuId`=12245 AND `OptionIndex`=2) OR (`MenuId`=12245 AND `OptionIndex`=1) OR (`MenuId`=12245 AND `OptionIndex`=0) OR (`MenuId`=1951 AND `OptionIndex`=12) OR (`MenuId`=12637 AND `OptionIndex`=1) OR (`MenuId`=1951 AND `OptionIndex`=11) OR (`MenuId`=12637 AND `OptionIndex`=0) OR (`MenuId`=1951 AND `OptionIndex`=10) OR (`MenuId`=1951 AND `OptionIndex`=9) OR (`MenuId`=1949 AND `OptionIndex`=9) OR (`MenuId`=1951 AND `OptionIndex`=8) OR (`MenuId`=1949 AND `OptionIndex`=8) OR (`MenuId`=1949 AND `OptionIndex`=7) OR (`MenuId`=1949 AND `OptionIndex`=6) OR (`MenuId`=1949 AND `OptionIndex`=5) OR (`MenuId`=1949 AND `OptionIndex`=4) OR (`MenuId`=1949 AND `OptionIndex`=3) OR (`MenuId`=1949 AND `OptionIndex`=2) OR (`MenuId`=1949 AND `OptionIndex`=1) OR (`MenuId`=1949 AND `OptionIndex`=0) OR (`MenuId`=1951 AND `OptionIndex`=7) OR (`MenuId`=1951 AND `OptionIndex`=6) OR (`MenuId`=1951 AND `OptionIndex`=5) OR (`MenuId`=12639 AND `OptionIndex`=1) OR (`MenuId`=1951 AND `OptionIndex`=4) OR (`MenuId`=12638 AND `OptionIndex`=0) OR (`MenuId`=12639 AND `OptionIndex`=0) OR (`MenuId`=1951 AND `OptionIndex`=3) OR (`MenuId`=1951 AND `OptionIndex`=2) OR (`MenuId`=1951 AND `OptionIndex`=0);
INSERT INTO `gossip_menu_option_action` (`MenuId`, `OptionIndex`, `ActionMenuId`, `ActionPoiId`) VALUES
(1942, 0, 1845, 279),
(1951, 14, 1942, 0),
(1942, 1, 12308, 2524),
(1942, 2, 1846, 280),
(1942, 3, 1861, 281),
(1942, 4, 1862, 282),
(1942, 5, 1981, 307),
(1942, 6, 1863, 283),
(1951, 13, 12245, 0),
(1942, 7, 1864, 284),
(1942, 8, 12654, 2637),
(1942, 9, 1865, 285),
(1942, 10, 10017, 2277),
(1942, 11, 12654, 2639),
(1942, 12, 1866, 287),
(1942, 13, 1868, 288),
(1942, 14, 12654, 2638),
(1942, 15, 1869, 287),
(1942, 16, 1871, 289),
(1951, 15, 4902, 848),
(9727, 1, 9726, 2104),
(1951, 16, 9727, 0),
(9727, 0, 2481, 827),
(12245, 8, 20935, 5223),
(12245, 7, 20927, 5225),
(12245, 6, 20932, 5222),
(12245, 5, 20928, 2517),
(12245, 4, 20931, 5219),
(12245, 3, 20933, 5224),
(12245, 2, 20934, 5221),
(12245, 1, 20930, 5220),
(12245, 0, 20929, 5218),
(1951, 12, 5882, 1468),
(12637, 1, 12626, 270),
(1951, 11, 12637, 0),
(12637, 0, 1904, 2512),
(1951, 10, 1903, 269),
(1951, 9, 1902, 268),
(1949, 9, 13863, 2768),
(1951, 8, 1949, 0),
(1949, 8, 1912, 275),
(1949, 7, 1911, 278),
(1949, 6, 1910, 277),
(1949, 5, 1909, 2546),
(1949, 4, 1908, 2551),
(1949, 3, 8644, 2544),
(1949, 2, 12309, 2525),
(1949, 1, 1906, 272),
(1949, 0, 12654, 2547),
(1951, 7, 8224, 2012),
(1951, 6, 10018, 2276),
(1951, 5, 12638, 0),
(12639, 1, 12628, 2513),
(1951, 4, 12639, 0),
(12638, 0, 1901, 267),
(12639, 0, 2403, 347),
(1951, 3, 12246, 2527),
(1951, 2, 12246, 2527),
(1951, 0, 14951, 2888);

DELETE FROM `points_of_interest` WHERE `ID` IN (279, 2524, 280, 281, 282, 307, 283, 284, 2637, 285, 2277, 2639, 287, 288, 2636, 289, 848, 2104, 827, 5223, 
5225, 5222, 2517, 5219, 5224, 5221, 5220, 5218, 1468, 270, 2638, 2512, 269, 268, 2768, 275, 278, 277, 2546, 2551, 2544, 2525, 272, 2547, 2012, 2276, 2513, 267, 347, 2527, 2888);
INSERT INTO `points_of_interest` (`ID`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`, `VerifiedBuild`) VALUES
(279, 1946.59, -4472.42, 7, 99, 0, 'Orgrimmar Alchemy', 27481),
(2524, 1668.48, -4359.67, 7, 99, 0, 'Orgrimmar Archaeology', 27481),
(280, 2077.391, -4807.912, 7, 99, 0, 'The Burning Anvil', 27481),
(281, 1773.28, -4493.09, 7, 99, 0, 'Orgrimmar Cooking', 27481),
(282, 1926.54, -4430.92, 7, 99, 0, 'Orgrimmar Enchanting', 27481),
(307, 1833.67, -4497.54, 7, 99, 0, 'Orgrimmar Engineering', 27481),
(283, 1484.66, -4176.12, 7, 99, 0, 'Survival of the Fittest', 27481),
(284, 2000.15, -4664.54, 7, 99, 0, 'Orgrimmar Fishing', 27481),
(2637, 1799.538, -4357.022, 7, 99, 0, 'Orgrimmar Flying Trainer', 27481),
(285, 1896.35, -4450.83, 7, 99, 0, 'Orgrimmar Herbalism', 27481),
(2277, 1842.33, -4477.9, 7, 99, 0, 'Orgrimmar Inscription', 27481),
(2639, 2088.818, -4767.181, 7, 99, 0, 'Orgrimmar Jewelcrafting', 27481),
(287, 1848, -4555.32, 7, 99, 0, 'Orgrimmar Leatherworking', 27481),
(288, 2081.972, -4764.094, 7, 99, 0, 'Orgrimmar Mining', 27481),
(2638, 2085.344, -4572.828, 7, 99, 0, 'Orgrimmar Riding Trainer', 27481),
(289, 1803.03, -4547.34, 7, 99, 0, 'Orgrimmar Tailoring', 27481),
(848, 2077.635, -4587.134, 7, 99, 0, 'Orgrimmar Stable Master', 27481),
(2104, 1738.83, -4280.79, 7, 99, 0, 'Orgrimmar Western Zeppelin Tower', 27481),
(827, 1843.63, -4394.62, 7, 99, 0, 'Orgrimmar Eastern Zeppelin Tower', 27481),
(5223, 1763.15, -4295.4, 7, 99, 0, 'Orgrimmar Portal to Dalaran', 27481),
(5225, 1773.77, -4328.87, 7, 99, 0, 'Orgrimmar Portal to Blasted Lands', 27481),
(5222, 2014.46, -4699.16, 7, 99, 0, 'Orgrimmar Portal to Honeydew Village', 27481),
(2517, 2047.94, -4377.4, 7, 99, 0, 'Orgrimmar Cataclysm Portals', 27481),
(5219, 1760.66, -4281.79, 7, 99, 0, 'Orgrimmar Zeppelin to Borean Tundra', 27481),
(5224, 1791.43, -4280.63, 7, 99, 0, 'Orgrimmar Portal to Hellfire Peninsula', 27481),
(5221, 1867.04, -4416.05, 7, 99, 0, 'Orgrimmar Zeppelin to Stranglethorn Vale', 27481),
(5220, 1843.47, -4393.98, 7, 99, 0, 'Orgrimmar Zeppelin to Tirisfal Glades', 27481),
(5218, 1738.75, -4259.86, 7, 99, 0, 'Orgrimmar Zeppelin to Thunder Bluff', 27481),
(1468, 1650.37, -4225.17, 7, 99, 0, 'Orgrimmar Hall of Legends', 27481),
(270, 1918.094, -4730.686, 7, 99, 0, 'Orgrimmar Inn', 27481),
(2512, 1572.304, -4436.325, 7, 99, 0, 'Orgrimmar Inn', 27481),
(269, 1611.974, -4345.156, 7, 99, 0, 'Horde Embassy', 27481),
(268, 1800.22, -4369.74, 7, 99, 0, 'Orgrimmar Flight Master', 27481),
(2768, 2023.557, -4704.186, 7, 99, 0, 'Orgrimmar Monk Trainer', 27481),
(275, 1962.52, -4766.58, 7, 99, 0, 'Orgrimmar Warrior Trainer', 27481),
(278, 1849.58, -4359.69, 7, 99, 0, 'Darkfire Enclave', 27481),
(277, 1773.39, -4278.97, 7, 99, 0, 'Shadowswift Brotherhood', 27481),
(2546, 1884.111, -4282.452, 7, 99, 0, 'Orgrimmar Shaman Trainer', 27481),
(2551, 1664.37, -4361.8, 7, 99, 0, 'Orgrimmar Priest Trainer', 27481),
(2544, 1863.972, -4292.818, 7, 99, 0, 'Orgrimmar Paladin Trainer', 27481),
(2525, 1767.12, -4343.18, 7, 99, 0, 'Orgrimmar Mage Trainer', 27481),
(272, 2109.26, -4630.1, 7, 99, 0, 'Orgrimmar Hunter Trainer', 27481),
(2547, 1888.885, -4285.238, 7, 99, 0, 'Orgrimmar Druid Trainer', 27481),
(2012, 1961.85, -4801.29, 7, 99, 0, 'Orgrimmar Battlemasters', 27481),
(2276, 1782.49, -4212.75, 7, 99, 0, 'Orgrimmar Barber', 27481),
(2513, 2041.32, -4674.58, 7, 99, 0, 'Orgrimmar Auction House', 27481),
(267, 1537.41, -4364.21, 7, 99, 0, 'Orgrimmar Bank', 27481),
(347, 1617.56, -4425.31, 7, 99, 0, 'Orgrimmar Auction House', 27481),
(2527, 1731.276, -4510.059, 7, 99, 0, 'Orgrimmar Ethereals', 27481),
(2888, 1799.408, -4420.585, 7, 99, 0, 'Orgrimmar Battle Pet Trainer', 27481);
`

**Comment by funjoker** [comment]
Note: POIs have IDs now.

Did you use the updated wpp?

**Comment by shamage** [comment]
I have a problem - let me do whatever console I can open for a maximum of 3 seconds after running - at the same time, the game will start right. I followed the instructions and I do not know why I can not. I'm clueless!

I really want to help, sniff but when I can not run the program , 
I really do not know what I'm doing wrong or what I miss

I read a few tutorials - all are almost the same, but as a beginner I do not know the advice ...

Can you help me  ?

**Comment by leviathonbeast** [comment]
@funjoker yes i used the up to date bfa PR of wpp

**Comment by Aokromes** [comment]
acording modox, no longer valid.
