### ISSUE TITLE
Core/Script: gossip reaction logic

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22341]
**Description:** It looks like gossipStep is skipping the step 0 and jumping directly to step 1.
In this script https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp#L523
Arthas must summon Jaina at step 0 but it doesn't happen, only Uther is summoned at step 1

**Steps to reproduce the problem:**

1. .go c id 26499
2. Talk to Arthas to start the event
3. Notice Jaina is never summoned

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 75e7404bba8c

**Comment by Treeston** [comment]
I don't see how this is related to EscortAI? The logic you linked is the script's gossip reaction logic.

**Comment by kuskmen** [comment]
Hi guys, this is will be my first issue to tackle with in TC, but I would like to join and it seems like this is the most convenient for start.

I checked current behavior and it is like @Killyana said, but I think that Uther is also not spawned correctly. Shouldn't it be like [here](https://youtu.be/PvtsLfBOwec?t=145)?

**Comment by Killyana** [comment]
There's a rewrite for this dungeon, the issue here step=0 is skipped

**Comment by Killyana** [comment]
It's related to https://github.com/TrinityCore/TrinityCore/issues/23008
caused by https://github.com/TrinityCore/TrinityCore/commit/e4e6e2209c8ad6cc534460a4ec9f6da469761d15#diff-2270235252e23698c6d2c9a49eb35bb1

this hook is not executed https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp#L323
