### ISSUE TITLE
Mage buffs that does not renew

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22355]
For now, I have seen the problem in the following spells:
- Frostbolt (Mage, spell=116)
- Fireball (Mage, spell=133)

**Expected behaviour:**
If you use any of the mentioned spells, it applies an aura on the target. if you use the same spell while the aura is active, it should be renewed.

**Current behaviour:**
The aura does not renew.

**Steps to reproduce the problem:**
1. Use Frostbolt or Fireball repeatedly on the same target

Branch: 3.3.5a
TC rev: c00a2ef
TDB: 335.64
OS: Debian 9 / Windows 8.1

I could not find any issue related to this.
If this is already reported, please close this.

**Comment by EricksOliveira** [comment]
This problem really happens. The same goes for the Spell FrostFire Bolt (Mage, spell = 44614).

**Comment by Winchester1987** [comment]
Looks like some generic problem affecting a certain type of spells.
Not sure if the title of the issue is the best one since this may be happening in other classes.

**Comment by nagrandbugtracker** [comment]
Confirmed on TrinityCore rev. 8a45191e92a2+ 2018-08-30 23:24:52 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Probably the same issue as https://github.com/TrinityCore/TrinityCore/issues/22272#issuecomment-418515774

**Comment by illfated** [comment]
TrinityCore rev. db3671b93518 2018-09-03 19:16:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Confirmed. This issue has been around for almost as long as I can remember.

**Comment by Winchester1987** [comment]
I think this is about the same problem https://github.com/TrinityCore/TrinityCore/issues/21635

**Comment by Killyana** [comment]
yes.

**Comment by santahashi** [comment]
> yes.

This problem doesn't happen with the last release

**Comment by illfated** [comment]
@santahashi : which specific problem do you not see anymore?
And BTW, which commit is "the last release" in your case?

**Comment by santahashi** [comment]
Many Thanks to your reply
The last release in my case is indeed the lastest commit, I’ve always
updated my source on a daily routine.
I have experienced the mentioned “invalid faction” during escort mission.
For the lastest commit, I’ve found it to contain various bugs such as aura
skill stacks, frost nova’s effect , blink’s spell and effect renew  which
wasnt happened in the lastest release (19/feb)

**Comment by illfated** [comment]
"the lastest commit" is not specific enough for those of us who want to troubleshoot issues.
When you look at the `3.3.5` commits (https://github.com/TrinityCore/TrinityCore/commits/3.3.5)
you will see that there is often more than 1 or 2 commits per day.

Referring to the exact TrinityCore revision hash or commit
(the latest one right now is e5d63bc5b02d0427beb2adf5571a90e92ebc1721 from 1 hour ago)
helps us to deduce where the interesting changes can be found.

**Comment by santahashi** [comment]
I dont know how to properly link a commit, but here is the reference code:
fcb45c4

**Comment by illfated** [comment]
Thank you. That is the "core revision hash" or "commit" I was talking about. 👍

**Comment by santahashi** [comment]
Many thanks for your hard work ^_^ I also experienced various skill bugs
that wasnt there on the lastest Release (19/Feb) as mentioned above
May you look in it as well?

**Comment by illfated** [comment]
Feb. 19 is very close to the TDB 335.64 release date:
https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.64
> DDuarte released this on Feb 18 · 744 commits to 3.3.5 since this release

I recommend that you either post in one of the open issue tickets
(if your existing problems already have got open tickets here in the tracker)
or open a new ticket in the TrinityCore issue tracker if there are no open ones.

Use the search function on top of the page to find issues related to your problem.
(https://github.com/TrinityCore/TrinityCore/search?q=issue&state=open&type=Issues)

When you open a new issue ticket, please make sure you fill in all the required info.
