### ISSUE TITLE
Quest 218 The Stolen Journal / German Quest (Feuer und Eis) is wrong

### ISSUE THREAD

**Issue by Bluechen80** [TrinityCore/TrinityCore#22356]
Quest: Quest 218 The Stolen Journal / Das gestohlene Tagebuch

Description:
The english Version of this quest ist 100% perfect, the german one isnt!
In the german locale the quest is called "Feuer und Eis" wich is the replaced quest of The Stolen Journal / Das gestohlene Tagebuch in Warlords of Dreanor.

i fixed this so heres all u need its 100% right from a 3.3.5a Server Video.

Current behaviour:
Like i said its a wrong Text

Expected behaviour:
Here is the right Text for the german Locales Quest 218

ID: 218	
Locale: deDE	
Title: Das gestohlene Tagebuch	
Details: Mein Tagebuch! Sie haben es in die Höhle gebracht. Der, der es hatte, war ein großer Kerl mit seltsamen Zeichen auf der Haut und im Gesicht. Viel mehr konnte ich leider nicht sehen.

Ihr hattet ja mit den Trollen Erfolg, vielleicht könntet Ihr es mir wiederbeschaffen?

Objectives: Tötet Grik'nir den Kalten.

OfferReward Text: Großartig, $N! Vielen Dank, dass Ihr mein Notizbuch zurückgeholt habt. Nun, es scheint, als sei das Trollproblem hier im Eisklammtal unter Kontrolle und als müssten wir uns nicht allzu viele Sorgen machen.

Nachdem ich meinem Bericht den letzten Schliff gegeben habe, werde ich jemanden brauchen, der ihn meinem Bruder Senir bringt.

Requested Itemstext: $N! Glück gehabt?

TrinityCore rev. 8e4f6777a28a 2018-08-30 21:08:28 +0200 (3.3.5 branch)

TDB version: TDB 335.64 latest updates installed

Operating system: Windows 10
Using SSL version: OpenSSL 1.0.2p  14 Aug 2018 (library: OpenSSL 1.0.2p  14 Aug 2018)
Using Boost version: 1.68.0
MySQL client library: 5.6.39
MySQL server ver: 5.6.39-log

**Comment by ZenoX92** [comment]
```sql
UPDATE `quest_template_locale` SET `Title`="Das gestohlene Tagebuch", `Details`="Mein Tagebuch! Sie haben es in die Höhle gebracht. Der, der es hatte, war ein großer Kerl mit seltsamen Zeichen auf der Haut und im Gesicht. Viel mehr konnte ich leider nicht sehen.$B$BIhr hattet ja mit den Trollen Erfolg, vielleicht könntet Ihr es mir wiederbeschaffen?", `Objectives`="Tötet Grik'nir den Kalten.", `OfferRewardText`="Text: Großartig, $N! Vielen Dank, dass Ihr mein Notizbuch zurückgeholt habt. Nun, es scheint, als sei das Trollproblem hier im Eisklammtal unter Kontrolle und als müssten wir uns nicht allzu viele Sorgen machen.$B$BNachdem ich meinem Bericht den letzten Schliff gegeben habe, werde ich jemanden brauchen, der ihn meinem Bruder Senir bringt.", `RequestItemsText`="$N! Glück gehabt?" WHERE `ID`=218 AND `locale`="deDE";
