### ISSUE TITLE
[Master] Dread Ship Vazuvius spell crash

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#22359]
**Description:**

[Spell 148026](www.wowhead.com/spell=148026) causes a server crash with 
`AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 14161 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 76806 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 76806 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 79096 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 14161 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 76806 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 76806 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 14161 proc, because the spell does not have an entry in Spell.dbc.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 79096 proc, because the spell does not have an entry in Spell.dbc.` in worldserver (not sure if related)

[172ccdb49929+_worldserver.exe_[31-8_5-16-6].txt](https://github.com/TrinityCore/TrinityCore/files/2338855/172ccdb49929%2B_worldserver.exe_.31-8_5-16-6.txt)

**Branch(es):**

Master

**TC rev. hash/commit:** 

TrinityCore rev. 172ccdb49929+ 2018-08-01 19:11:02 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Shauren** [comment]
No, this was the target type 120, now implemented
