### ISSUE TITLE
Honor Hold Fear Bug

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22362]
**Description:**

Honor Hold is totally messed up with the infernal hellfire.

**Current behaviour:**

CHANGEME Tell us what happens.
When hellfire is triggered in Honor Hold all the NPCs run around like crazy and get stuck in random places.  Also it makes your character run around and not able to control movement at all.

**Expected behaviour:**

From what I remember the NPCs moving around is normal but they are not returning to their location after the fear ends one example is the flight master.  But I'm not totally sure if the actual player is supposed to be feared around like crazy.

**Steps to reproduce the problem:**

Go to Honor Hold in Hellfire Peninsula 
Wait for the Infernal Hellfire to start raining down.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8a45191e92a277ee9aafebbd0c1aa082c6be4298

**Operating system:** 

Windows Server 2016

**Comment by WOW-Reborn** [comment]
It does exist, I don't know why your saying it doesn't but the infernal hellfire does rain down.

**Comment by Killyana** [comment]
Yes I have to wait for a moment.
Anyway it's a general issue https://github.com/TrinityCore/TrinityCore/issues/21106

**Comment by WOW-Reborn** [comment]
Question though, I know the NPCs are suppose to flee but was it normal for it to make the players toon run in fear as well?  I can't remember that far back.

**Comment by Killyana** [comment]
This issue is closed be cause the main issue is a duplicate, the second issue is not really an issue as there's no proof.

Also it's better to have only one bug in the ticket not 2 or 3.
