### ISSUE TITLE
[3.3.5] Death Knight dancing bug

### ISSUE THREAD

**Issue by EricksOliveira** [TrinityCore/TrinityCore#22361]
**Description:**

Death Knight is dancing the wrong way.

**Current behaviour:**

By using the / dance command he is pulling the dance of other races. Example: DK-Human pulling dance from Blood Elf.

**Expected behaviour:**

The dance has to be done according to each race.

**Steps to reproduce the problem:**

1. Create a Human Death Knight.
2. Use the / dance command

**Branch(es):**

Branch: 3.3.5a

**TC rev. hash/commit:** 

TC rev: 8a45191
TDB: 335.64

**Operating system:**

Windows 7

**Comment by Meltie2013** [comment]
Unable to reproduce this bug.

**TC rev. hash/commit:**
https://github.com/TrinityCore/TrinityCore/commit/705852c2a210ae435703aa28b099fb5de943b8ad

**Operating system:**
Ubuntu 18 / CentOS 7
