### ISSUE TITLE
Core/Movements: Random Movements remains even if the unit in under player control

### ISSUE THREAD

**Issue by WOW-Reborn** [TrinityCore/TrinityCore#22368]
**Description:**

Unable to control Mammoth's for long.

**Current behaviour:**

When the Mammoth is under your control the effect doesn't let you move far before breaking.

**Expected behaviour:**

The effect should last until you get the mammoth to its destination.

**Steps to reproduce the problem:**

Use the harness on a mammoth.
Start to move her and shortly the spell will break.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9ace4093d8cf67ba54912038f93fa42d3aa14b9c

**Operating system:** 

Windows Server 2016

Side note information
This effect along with several others seems to utilize the same system as the priest's mind control ability. Granted I could be wrong about this as I don't know C++ to understand the actual core; however, the effect that is happening to the mammoth is the exact same that happens when using Mind Control after the da21ca80fc35a325df0fb0ef2f687a91121d42de revision.  It was after the updates to the charmed system happened that the priest mind control and quest like this seemed like once under your control and you moved more than a few feet the control breaks.  Just thought I would throw this additional info out there.

**Comment by Cyclone47** [comment]
I'm pretty sure this was fixed after treeston claimed his bounty. https://github.com/TrinityCore/TrinityCore/issues/20310 - I even closed the internal bug report on our server. Can verify that this is broken again on a recent rev.

**Comment by Killyana** [comment]
This issue is new, introduced by a recent commit.

**Comment by Killyana** [comment]
Caused by https://github.com/TrinityCore/TrinityCore/commit/da21ca80fc35a325df0fb0ef2f687a91121d42de

**Comment by Winchester1987** [comment]
I did not apply that commit in one of my servers and the bug is present there.

**Comment by illfated** [comment]
Hmm, does that imply that this has got something to do with `DoZoneInCombat` and code related to ut?

**Comment by Winchester1987** [comment]
Or maybe it is something else.
I will go back 1 month and start from there.

**Comment by Winchester1987** [comment]
Last commit: cbacc72d934c10448762b67a0fa97ea4eb38cb63 → The bug is present.
How far should I go?

I noticed something while testing "A mammoth Undertakin" and "Kaw the Mammoth Destroyer" (I hope I can explain this correctly):
- Normally the NPC walks a little and stops for a few seconds, walks a little and stops for a few seconds,... etc.
- Imagine that the NPC has this behaviour in a minute:
0 to 10 seconds: The NPC walks.
11 to 20 seconds: The NPC stands still.
21 to 30 secods: The NPC walks.

- Now, mount it and do nothing → the NPC does the same (walks a little and stops for a few seconds).
0 to 10 seconds: The NPC walks and does not care if someone is mounted or not.
11 to 20 seconds: This is the moment when you can control it.
21 to 30 seconds: The NPC walks and you can not control it until it's his turn to stand still again.

The NPC is like "I do not care if someone mounted me, I should to walk now, so I walk".

I hope this is useful and understandable.

**Comment by illfated** [comment]
> Last commit: https://github.com/TrinityCore/TrinityCore/commit/cbacc72d934c10448762b67a0fa97ea4eb38cb63 → The bug is present.
> How far should I go?

To answer that question in particular: from what I see in the commits https://github.com/TrinityCore/TrinityCore/commit/cbacc72d934c10448762b67a0fa97ea4eb38cb63 (**DB/Quest: The Missing Diplomat (Part 16)**), https://github.com/TrinityCore/TrinityCore/commit/25d7b7c819048d0c2d62b61dc47624735935a5f3 (**DB/Quest: Cleansing Witch Hill**) and https://github.com/TrinityCore/TrinityCore/commit/82f6d482732e621882fa536ee04368034f78e00a (**DB/Item: Lunar Festival Invitation**), those 3 commits do not look like they should affect other creatures outside of those commits.

It would be more likely that a commit like https://github.com/TrinityCore/TrinityCore/commit/077bf43ab5e4a646d2898eea28e4b8752a93fc89 (**Scripts/Commands: Fix .quest complete to properly work with PvP kill quests.**) could have an impact on other quests, but I am still not certain that it is the exact cause of this issue (needs testing).

**Comment by Winchester1987** [comment]
You are right. I asked myself "what if I go a whole month back?" just to see that the problem is not caused by a really recent commit.
Will test something better tomorrow (sleeping now).

**Comment by illfated** [comment]
Very well, fair enough. 🛌 I also recommend deleting the game Cache folder between tests. 🎮 🕺

**Comment by jerbookins** [comment]
#16556

This issue also affects the quest [Mounting Up](https://www.wowhead.com/quest=12414/mounting-up)

**Comment by Killyana** [comment]
Related to #21731

**Comment by illfated** [comment]
Still an issue as of TrinityCore rev. 518e6299ca08 2019-01-19 17:41:03 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static).
- https://www.wowhead.com/quest=12607/a-mammoth-undertaking (https://woehead.way-of-elendil.fr/?quest=12607)
- https://www.wowhead.com/spell=51659/apply-harness (https://woehead.way-of-elendil.fr/?spell=51659)
- https://www.wowhead.com/npc=28379/shattertusk-mammoth (https://woehead.way-of-elendil.fr/?npc=28379)

My temporary solution to complete the quest was to find and mount the Shattertusk Mammoth closest to Zootfizzle, then dismount from vehicle at the closest point to Zootfizzle it could get to before random movement turns it away. When I dismounted, the random movement stopped briefly and I was able to mount again and move it closer to Zootfizzle. Did this a couple of times and reached the quest giver and was able to hand in the mammoth.

I wonder if we either need some kind of script to remove the random movement state from the creature when mounting it, or if the Shattertusk Mammoth should despawn and player should mount a separate creature without random movement.
