### ISSUE TITLE
ban account = error

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22360]
Problem baneed account!

.ban acc test 10d ads

Error:
Ban exists
Ban exists
Ban exists

The account can not be banned!

windows server 2012

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/cbacc72d934c10448762b67a0fa97ea4eb38cb63

**Comment by Killyana** [comment]
If you try to ban an account already banned you will have the error: Ban exists
You must unban acc, then reban it with another duration or reason.
