### ISSUE TITLE
Quest : Feeling Crabby ? - can not be completed

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#22372]
**Description:**

after receiving the job and finding the crabs in the channels, you can not attack them

**Current behaviour:**

I take the role [Feeling Crabby?](https://www.wowhead.com/quest=26177/feeling-crabby) find the [Canal Crab](https://www.wowhead.com/item=57175/canal-crab) in the channels I mark them but I can not attack

**Expected behaviour:**

after taking the job kill us crabs to do the job

**Steps to reproduce the problem:**

1. take the role / Quest : [Feeling Crabby?](https://www.wowhead.com/quest=26177/feeling-crabby)
2. Find [Canal Crab](https://www.wowhead.com/item=57175/canal-crab)
3. kill crabs to accomplish the role

**Branch(es):**   master

**TC rev. hash/commit:** 

TrinityCore rev. 56877d236019 2018-08-25 22:47:35 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 900650049 bytes
vmaps directory located in ./vmaps. Total size: 5127494765 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 735.00
**Operating system:** Windows 10.0.17134

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15182
