### ISSUE TITLE
NPCs who give quest items

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22370]
So far, I found the problem in the following quests:
- Finding the Phylactery (https://www.wowhead.com/quest=11956/finding-the-phylactery)
- Rifle the Bodies (https://www.wowhead.com/quest=12000/rifle-the-bodies)

**Description:**
The common thing with these quests is:
- Right click on a NPC to receive a quest item.

**Current behaviour:**
- After right clicking the NPC, it disappears but does not give any item.

**Expected behaviour:**
- The character should receive the quest item and after that, the NPC should disappear.

Branch: 3.3.5a
TC rev: c00a2ef
TDB: 335.64
OS: Debian 9 / Windows 8.1

Note: If this can be solved using smart_scripts, I could try a solution.

**Comment by funjoker** [comment]
1. Quest needs Script and loot for npcs
2. Quest npc is spellclick -> there is a table in db + condition

**Comment by PolarCookie** [comment]
Find the Phylactery works, except that the urn doesn't despawn.
You don't get the quest item from the urn tho.

https://github.com/TrinityCore/TrinityCore/issues/21772

**Comment by WOW-Reborn** [comment]
This will never fly with the TrinityCore guys but @funjoker if your looking for a temp fix to let you do quest 12000 and 11999-Rifle the Bodies you can apply this and do a .reload smart_scripts

`-- Dead Mage Hunter SAI
DELETE FROM `smart_scripts` WHERE `entryorguid`=26477 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(26477,0,0,1,8,0,100,513,61832,0,0,0,41,1000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dead Mage Hunter - On Spellhit 'Rifle the Bodies: Create Magehunter Personal Effects Cover' - Despawn In 1000 ms (No Repeat)"),
(26477,0,1,0,61,0,100,0,0,0,0,0,83,16777216,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dead Mage Hunter - On Spellhit - Remove Npc Flag Spellclick (No Repeat)");`

**Comment by PolarCookie** [comment]
@WOW-Reborn you can do

\```sql
SQL STATEMENTS
\```

and it will look like
```sql
-- Dead Mage Hunter SAI

DELETE FROM smart_scripts WHERE entryorguid=26477 AND source_type=0;

INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(26477,0,0,1,8,0,100,513,61832,0,0,0,41,1000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dead Mage Hunter - On Spellhit 'Rifle the Bodies: Create Magehunter Personal Effects Cover' - Despawn In 1000 ms (No Repeat)"),
(26477,0,1,0,61,0,100,0,0,0,0,0,83,16777216,0,0,0,0,0,1,0,0,0,0,0,0,0,"Dead Mage Hunter - On Spellhit -
Remove Npc Flag Spellclick (No Repeat)");
```

**Comment by WOW-Reborn** [comment]
@PolarCookie thanks I couldn't figure out how they were getting it to look right lol

**Comment by illfated** [comment]
@WOW-Reborn : for code handling in github comments, I think you will find this interesting:
- https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown
- https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
- https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by illfated** [comment]
I am also trying to come up with a more precise and accurate title for this issue.
See if you think this suggestion, or something similar, fits better than the current.
**DB/SAI: Quest items looted by spellclick**

**Comment by Winchester1987** [comment]
@illfated that title looks better.
Sometimes I have just crappy titles since english is not my native language.

More quest with the same issue:
https://www.wowhead.com/quest=12527/gluttonous-lurkers
https://www.wowhead.com/quest=12629/you-can-run-but-you-cant-hide

**Comment by Killyana** [comment]
Dup #21772
