### ISSUE TITLE
Core/Spells: Zul'Drak Rat (50894)

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22377]
**Description:**
https://www.wowhead.com/spell=50894/zuldrak-rat is not stacking.

**Steps to reproduce the problem:**
.tele Zul'Drak
find a basilisk and do
.cast 50894

The issue might lie in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2765
Spell Zul'Drak Rat has a speed of 15, so it will check if unit already has an aura, find the old one and not update. I set speed to 0 in the debugger and it was stacking fine afterwards, but the stacks happened instantly upon spellcast, not waiting on rat to hit target, ofc.
The comment does not match the condition, what exactly is meant by multiple targets?

https://github.com/TrinityCore/TrinityCore/commit/28288698441524081d583af95f19cb1c9fb90387 introduced this check.
@ariel-

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
ca7ee982db4d25c464acf6daadc150d58dafa016

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/22272
