### ISSUE TITLE
Mirror Images Crash

### ISSUE THREAD

**Issue by kotishe** [TrinityCore/TrinityCore#22396]
**Description:**

Mirror Images  mage spell Crash

**Current behaviour:**

If some characters cast Mirror Image server crashed 
https://gist.github.com/kotishe/6ca601a70a571203ecb108b1659e43ef

**Expected behaviour:**

Server should dont crashed.

**Steps to reproduce the problem:**

1. Cast Mirror Image
2. ???
3. CRASH!!!

**Branch:**

3.3.5

**TC rev. hash/commit:** 

**Operating system:** Win 10 64bit

**Comment by Shauren** [comment]
commit 98d4c4a88e46 does not exist in any of TC branches and SpellHandler.cpp line 662 points to this
https://github.com/TrinityCore/TrinityCore/blob/66a87c4642d25f27ca24254cfeb0a0c4b21036b1/src/server/game/Handlers/SpellHandler.cpp#L662

**Comment by kotishe** [comment]
Thanks, I understood what the problem is, the topic can be closed
