### ISSUE TITLE
Gahz'rilla doesn't start moving randomly at the end of her waypoint

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22394]
**Description:**

When Gahz'rilla reaches the end of her waypoint, she should start moving randomly, but instead she remains idle. The script was working just fine in my old core (rev. 1cc3d33), but now it seems something changed in core side.

The same happens with Impsy and probably many other NPCs.

**Steps to reproduce the problem:**

1. .tele zulfarrak
2. Go by the pool.
3. Sound the gong.
4. Watch as Gahz'rilla walks out of the pool.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a10870571558 2018-09-03 22:06:51 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.64

**Operating system:** Windows 7

**Comment by illfated** [comment]
Not sure how similar my experience is, but about a week ago (around September 1) I ran Zul'Farrak with my main GM character (level 45+) and summoned Gahz'rilla in the pool. On my first attempt, Gahz'rilla was stuck in the pool, never leaving it, but also unattackable (seemed to be stuck in combat with my character). I had to leave, reset the instance and reenter to get Gahz'rilla to move out of the pool. Unfortunately, I did not spend much time waiting to see whether Gahz'rilla would move around or do anything else than leave the pool, so I can't confirm if this is the current behaviour of Gahz'rilla on 3.3.5, but it seems plausible.

**Comment by Killyana** [comment]
I replaced:
``` sql
(7273,0,5,0,58,0,100,0,2,7273,0,0,89,10,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gahz'rilla - On Waypoint 2 Reached - Start Random Movement");
```
By:
``` sql
(7273,0,5,0,58,0,100,0,0,0,0,0,89,10,0,0,0,0,0,1,0,0,0,0,0,0,0,"Gahz'rilla - On Waypoint ended - Start Random Movement");
```
And it works, so the issue is the npc will not do any other movement until waypoint movement is expired, even if the point 2 is the last one.

**Comment by illfated** [comment]
Based on what you found, it looks like waypoint movement type must expire before movement type can be changed by SAI, otherwise it gets stuck.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/24187
