### ISSUE TITLE
Serpent Sting (ID13552)

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22392]
**Description:**
https://wotlk.evowow.com/?spell=13552

**Current behaviour:**
Serpent Sting debuff doesn't renew on target when recast

**Expected behaviour:**
Serpent Sting debuff should renew on target when recast.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 759c16f2bec6 2018-08-26 14:24:56 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Dup #22355
