### ISSUE TITLE
Core/Spell: Guardian Swarm

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22393]
**Description:**
Auriaya's spell Guardian Swarm is not spawning any Swarming Guardian

**Current behaviour:**
Aura [Guardian Swarm](https://wotlk.evowow.com/?spell=64396) triggers the spell [Summon Swarming Guardian](https://wotlk.evowow.com/?spell=64397) periodically, but SSG fails when it reaches
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L1097
where it fails to find a target, range is 0 and setting it in debugger to >0 makes the [Swarming Guardian](https://wotlk.evowow.com/?npc=34034) spawn.

**Steps to reproduce the problem:**
Either fight Auriaya with 2 characters or '.cast 64396' on an enemy player.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
a10870571558424033c2ffb41e4759e6581c8d86

**Comment by Keader** [comment]
i will take a look today
