### ISSUE TITLE
[3.3.5] Take down Tethyr! - Cove Cannon not working

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22407]
**Description:**

In quest https://www.wowhead.com/quest=11198/deprecated-take-down-tethyr you should be able to use the 3 Cove Cannons to kill Tethyr. As it stands, the cannons do not work. The rest of the scripting is working.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
073ba8e

**Operating system:** 
 Win 10 x64

**Comment by Killyana** [comment]
Con you provide more details about  "do not work"? not clickable or clickable but cast nothing ?

**Comment by TerrorBringer** [comment]
You can click it, then it becomes unclickable for a few seconds, but it does not fire.

**Comment by RedSonja** [comment]
Agreed as of Oct 28,2018

**Comment by soniczhang11** [comment]
Still the same problem with bda351d7f1cb3ff663a9d231afa85864ea0f8078

**Comment by illfated** [comment]
We know that it is a GameObject issue, @soniczhang11 . No need to open a new issue ticket for the same problem so long as there is one open already. What is needed here is productive feedback with what could cause the gameobjects to have stopped working, because I am fairly sure they worked OK in 2016-2017.

**Comment by soniczhang11** [comment]
> We know that it is a GameObject issue, @soniczhang11 . No need to open a new issue ticket for the same problem so long as there is one open already. What is needed here is productive feedback with what could have caused the gameobjects to stop working, because I am fairly sure they worked OK in 2016-2017.

Sorry for that. After I clicked the cannon, I got this `GameObject (template id: 186432) has invalid faction (faction template id) #0`

**Comment by illfated** [comment]
Fair enough. I am not sure if that log entry is the cause of this issue, but it is good that you mention it anyway, in case I am mistaken about that log entry. There are a lot of gameobjects creating that log entry, but from what I can remember, it has shown up for gameobjects which work as expected in-game, so I cannot say for certain if it is the direct cause or not.

**Comment by Killyana** [comment]
When a gob cast a spell if this spell has a visual like a missile it will not be displayed.
``` sql
UPDATE `smart_scripts` SET  `event_param1`=16000,`event_param2`=16000 WHERE `entryorguid`=23900 AND `source_type`=0 AND `id`=2;
UPDATE `smart_scripts` SET  `action_param1`=768 WHERE `entryorguid`=2389900 AND `source_type`=9 AND `id`=2;
UPDATE `smart_scripts` SET  `action_param1`=768 WHERE `entryorguid`=23899 AND `source_type`=0 AND `id`=2;
UPDATE `creature_template_movement` SET `Ground`=1 WHERE `CreatureID`=23899;
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 42578;
DELETE FROM `spell_scripts` WHERE `id`=42578;
INSERT INTO `spell_scripts` (`id`,`effIndex`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(42578,0,0,15,42576,0,0,0,0,0,0);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (23899) AND `source_type`=0 AND `id`=10;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(23899,0,10,0,40,0,100,0,1,23899,0,0,103,1,0,0,0,0,0,1,0,0,0,0,0,0,0,'Tethyr - Waypoint reached - Root');
