### ISSUE TITLE
Icefang - Spell Burst of Speed

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22402]
**Description:**
When mounted, Icefang (npc=29602) has spell Burst of Speed (spell=54907) which causes Icefang to sprint at double speed for 5 seconds

**Current behaviour:**
The spell does nothing. Buff appears but speed is not modified.

**Expected behaviour:**
Icefang should go double speed.

**Steps to reproduce the problem:**
1. .go c id 29592
2. .q a 12851
3. Mount Icefang
4. Use Burst of Speed

Branch: 3.3.5a
TC rev: c00a2ef
TDB: 335.64
OS: Debian 9 / Windows 8.1

**Comment by Killyana** [comment]
This is not a spell issue, the npc is supposed to do the waypoint with run speed not the walk speed:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_storm_peaks.cpp#L344-L382
``` sql
SELECT *   FROM `script_waypoint` WHERE `entry` IN (29602);
```
It's related to https://github.com/TrinityCore/TrinityCore/issues/21290
