### ISSUE TITLE
[3.3.5] Die while channeling spells that heal

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22409]
This is not easy to report since it does not always happen and I still cant find where is the last detail that makes this error to happen. I will understand if this is closed.
I decided to report to see if someone can help with more info so I can upgrade this to a better report or have a better idea of what is happening in these cases.

I just have friends that reported me this issue. I am still trying to replicate the error.

There are two channeled spells that heals the target:
- Drain life (Warlock, spell=47857)
- Penance (Priest, spell=47540)

**Description:**
The general situation is:
You are a warlock draining life or a priest channeling penance while in raid, bg, etc, and you receive enough damage to kill you, from players or NPCs.

**Current behaviour:**
Under some particular cases (This where I don not know what is the specific condition I am missing) you die, but:
- There is no "revive button".
- Instantly, you appear in the same place where you died
- You cannot move. (Sometimes you can)
- Nobody can damage/heal you
- You can not damage/heal

If you relog, the problem dissapears.

**Expected behaviour:**
- You die normally.

**Steps to reproduce the problem:**
You can not just go with a priest and a dps to let channeling the priest and kill him with the dps.
This could happen in a raid, in bg, etc.

**Branch(es):**
Branch: 3.3.5a
TC rev: c00a2ef
TDB: 335.64
OS: Debian 9 / Windows 8.1

**Comment by Winchester1987** [comment]
Thank you a lot.
I have seen this problem every now and then when you are gm and use those commands testing something, but it looks like now it is affecting class's spells.

Should I edit the issue or change to a better title?

**Comment by Keader** [comment]
No need, it's fine i think.
Using commands is just a faster way to reproduce it, but root problem is the same.
You got HP change while you dead

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/21873
