### ISSUE TITLE
Lathoric the Black

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22418]
**Description:**
https://www.wowhead.com/npc=8391/lathoric-the-black
https://www.wowhead.com/quest=28056/rise-obsidion
https://www.wowhead.com/npc=8284/dorius-stonetender

**Current behaviour:**
Dorius Stonetender appears upon accepting the quest Rise, Obsidion! He goes through a script and then transforms into Lathoric the Black. Obsidion and wakes up and attacks you while Lathoric just appears to be in combat, following the player around, but isn't attackable and remains friendly (green).

https://streamable.com/jes24

**Expected behaviour:**
Lathoric the Black should appear in the same place that Dorius disappeared. Transition looks weird and is confusing in terms of story-telling because they're the same person. Lathoric is supposed to become hostile when he engages in combat.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 759c16f2bec6 2018-08-26 14:24:56 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Your core is old or there's some modifications, as the Lathoric the Black has the faction 120 and if the player is neutral or  friendly with this faction, the npc will just evade and despawn.
