### ISSUE TITLE
[3.3.5] Icecrown citadel Parent map

### ISSUE THREAD

**Issue by PatricNox** [TrinityCore/TrinityCore#22413]
**Description:**

Icecrown Citadel's parent map should be Northrend.

**Current behaviour:**

As of now, players gets ported to their hearthstone location/Dalaran after logging out inside a raid group than later on is disbanded.

**Expected behaviour:**

The player should appear in Northrend.

**Steps to reproduce the problem:**

1. Join raidgroup in ICC
2. Logout
3. Disband Raidgroup
4. Login

**Branch(es):**

Only tested on 3.3.5 

**TC rev. hash/commit:** 

TrinityCore rev. b50f35f56bff 2018-09-09 12:45:26 -0300

**SQL Contribution to fix explained issue** 
` 
UPDATE `instance_template` SET `parent`='571' WHERE `map`='631';`

**Comment by Jildor** [comment]
You can do it in one line better ;)

**Comment by PatricNox** [comment]
Indeed but one liners aren't always the best documentation, as my mum used to tell me :1234: 

`UPDATE `instance_template` SET `parent`='571' WHERE `map` IN (724, 668, 658, 632, 631);`

**Comment by illfated** [comment]
Tip: if you want to highlight code block syntax, use GitHub Flavored MarkDown: **```sql**
example:
```sql
UPDATE `instance_template` SET `parent`= 571 WHERE `map` IN (724, 668, 658, 632, 631);
```
