### ISSUE TITLE
Logout doesn't always save coordinates

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22428]
**Description:**
Logout doesn't always save player's coordinates.

**Current behaviour:**
Sometimes when signing in, the player is returned to their last flight point instead of where the player logged out.

**Expected behaviour:**
The player should appear exactly where they logged out every time they sign in, unless maybe if they're dead.

**Steps to reproduce the problem:**
Reproducing the steps is pretty difficult, I'm not aware of a pattern to suggest replicating the issue.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c5fa08afc1d1 2018-09-11 18:51:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22234

**Comment by jerbookins** [comment]
@Aokromes I'm not sure this is exactly the same thing.

When I logged in, my server console said:
`Player::LoadFromDB: Player (GUID Full: 0x0000000000000062 Type: Player Low: 98) has too short taxi destination list, teleport to original node.`

**Comment by Treeston** [comment]
Just because both issues exhibit the same symptoms (a position rollback) that doesn't mean they have the same cause.

Position rollback just means that something went wrong when saving the character to the DB.

**Comment by Hir0shi** [comment]
OH OH
:smiley: 
CONFIRM
