### ISSUE TITLE
[3.3.5] Achievement Leeeeroy!

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22430]
**Description:**

The achievement Leeeeeroy (https://www.wowhead.com/achievement=2188/leeeeeeeeeeeeeroy) does not work because there are no whelps to kill.

**Current behaviour:**
When the character steps over the eggs, they break but the whelps do not appear.
If the server is running debug mode, they appear properly. (I do not know what that means)

**Expected behaviour:**
A whelp should appear for each time the character interacts with an egg.

Whelp: https://www.wowhead.com/npc=10161/rookery-whelp

Branch: 3.3.5
TC /Commit: 70955ed3a68a58701ae50c8f0f9afdec4f60853d
OS: Windows 8.1 / Debian 9

**Comment by Killyana** [comment]
As you can see there's 2 secs incant for the spell: https://woehead.way-of-elendil.fr/?spell=15745
This explains why on retails videos eggs hatches after 2 secs once activated and not instantly.

**Comment by Winchester1987** [comment]
Details I forgot:
If you insert breakpoints in the function that summons a whelp and run the Server in debug mode, everytime you step over a egg that breakpoint is reached and eveything is fine.
Running the Server as normal does not give the same results

**Comment by Winchester1987** [comment]
Thank you. 
I was adding details when you solved it.
