### ISSUE TITLE
[3.3.5] Character gender not sent with guild roster

### ISSUE THREAD

**Issue by xvwyh** [TrinityCore/TrinityCore#22433]
In `Guild::Member::WritePacket` the currently unknown value `uint8(0)` is in fact member's gender. This is correctly implemented in `master` branch, but is still missing in `3.3.5`.

This affects the display of class (and possibly race) name in the guild roster window on non-english locales, russian in particular. (e.g. "Охотник" for male hunter and "Охотница" for female hunter).

When implementing, the gender will have to be stored inside `Guild::Member` class, and updated alongside other stats in both overloads of `Guild::Member::SetStats`. And please don't use `uint8` to store it, there's a perfectly serviceable `enum Gender`.

And just to please @TrinityCoreBot: 0f3156d324ff8134171bada01b40f5c23f5c43cc

**Comment by msoky** [comment]
if it is correctly implemented in master, I prefer to wait for cherry-pick :)

**Comment by Aokromes** [comment]
you are to late. also no one is cping 3.3.5a to master or master to 3.3.5a.

**Comment by msoky** [comment]
and that is sad...

**Comment by Kittnz** [comment]
As far as i can tell, it's correctly implemented on master. No need to do anything.
