### ISSUE TITLE
[3.3.5] Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22431]
**Description:**
I saw this while testing the quest https://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer. I think the problem is not this quest or the npc needed, but some generic vehicle problem instead.

**Current behaviour:**
When you mount https://www.wowhead.com/npc=25743/wooly-mammoth-bull, you can control him for a few seconds but after that, the mammoth goes back to his original point without letting the player control him till he finishes returning.
When the player can control him again and try to go to the quest zone, the problem appens again.

**Expected behaviour:**
The player should control the NPC normally.

**Steps to reproduce the problem:**
1. .quest add 11879
2.  mount NPC 25743
3. Try to do the quest

Branch: 3.3.5
TC /Commit: 70955ed
OS: Windows 8.1 / Debian 9

PD: The title is bad. I do not know which one is better.

**Comment by illfated** [comment]
Similar problem to what is described in the issue [**A Mammoth Undertaking**](https://github.com/TrinityCore/TrinityCore/issues/22368) #22368
