### ISSUE TITLE
[3.3.5a] Quest: Cleansing Witch Hill

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22441]
**Description:**
After 7346793bcdfef591658b6934220dc25ee52351a3 and quoting WOW-Reborn:
"now Zelfrax gets spawned twice and Jarl who cast the spell to summon Zelfrax is laying flat on the ground."

https://ibb.co/k4h8ge

Branch: 3.3.5
Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
OS: Windows 8.1 / Debian 9

**Comment by Killyana** [comment]
#22364
