### ISSUE TITLE
The Skettis Offensive

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22445]
**Description:**
https://www.wowhead.com/quest=10879/the-skettis-offensive

**Current behaviour:**
Killing the Avatar of Terokk, the final wave of the fight, the quest is not completed.

**Expected behaviour:**
Killing the Avatar of Terokk should complete the quest.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c5fa08afc1d1 2018-09-11 18:51:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Window 10 Pro

**Comment by jerbookins** [comment]
I abandoned the quest and I’ll try it again when I get home. Maybe let the avatar get closer? /shrug

**Comment by EricksOliveira** [comment]
Kind of hard to explain. I just waited for them to attack and I killed. I made the alliance. If there is still a problem, post the details.

**Comment by jerbookins** [comment]
Still cannot complete. I waited for the mobs to pause in their waiting position. They don't engage combat with anything other than a player. I stood directly next to Defender Grashna the entire event and put my pet on passive. Made certain to get the first shot on every mob before engaging my pet.

**Comment by jerbookins** [comment]
Tried it again without using my pet at all and it worked.

**Comment by jerbookins** [comment]
I think this might be an issue that extends beyond this quest. I am at the ring of blood at can't get credit for killing the bosses if I use my pet.

**Comment by Aokromes** [comment]
if pets does most of all damage not getting credit is blizzlike.
