### ISSUE TITLE
[BfA] Compiling, 14 failed

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#22443]
**Description:**

Compiling the current BfA branch produces the following output with 14 failures

[BuildOutput.txt](https://github.com/TrinityCore/TrinityCore/files/2386840/BuildOutput.txt)

**Branch(es):**

BfA

**TC rev. hash/commit:** 

0c38fa1cf4dbec41452b851f214e8dc81f960bf6

**Operating system:** Windows 10

**Comment by Shauren** [comment]
yes. very much work in progress
