### ISSUE TITLE
[3.3.5] Crash worldserver related to FlightPathMovementGenerator

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22444]
Using rev ce46a0d53c3dbd6d2837020686e3880d98c545ed I had this crash:

`Thread 7 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff2d5ff700 (LWP 31846)]
0x00000000028ebf9a in FlightPathMovementGenerator::InitEndGridInfo (this=0x7fff2d7b0360) at /TrinityCore/src/server/game/Movement/MovementGenerators/FlightPathMovementGenerator.cpp:252
252	    _endMapId = _path[nodeCount - 1]->MapID; //! MapId of last node`

I think that this may be related to a3697052c3860b9bd5524b932fbda9c8690e9e72
I reverted that commit and I had no more crashes so far.

Branch: 3.3.5
Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
OS: Windows 8.1 / Debian 9

**Comment by Hir0shi** [comment]
Confirm

**Comment by jackpoz** [comment]
please post the whole crashlog on https://gist.github.com/ , a single line is not enough for us to do anything

**Comment by Winchester1987** [comment]
Here https://gist.github.com/Winchester1987/7bb51b4335d343081c042199be1215f2

**Comment by illfated** [comment]
https://github.com/Winchester1987 does not exist anymore (and not the gist pages either), so you need to re-upload the gist to an existing page.

**Comment by TheWinchesters** [comment]
@illfated 
Thank you. Updated.

**Comment by jackpoz** [comment]
please try after https://github.com/TrinityCore/TrinityCore/commit/2a06923879ccbcfff35cba4f35427eaf8c79dffd

**Comment by TheWinchesters** [comment]
I would love to try, but since I still dont get along with crash logs I would not know what to do to replicate what happened in the crashlog I posted here.

**Comment by Faq** [comment]
@TheWinchesters just update your core to revision what @jackpoz linked, there with it should be more info in crashlog to solve this.

**Comment by Treeston** [comment]
tagged issue has repro

**Comment by Killyana** [comment]
The spell 45883 was casted twice: Effet #1 Send Taxi :  (792)
I suppose if you start a taxi when the char is already into a fly it will crash

**Comment by Treeston** [comment]
Trying to start a flight path while a flight path was already in progress.

Starting the second one would first setup `m_taxi`, then `Remove` any pre-existing flight movement generators, which would cause the logic added in a369705 to reset `m_taxi`.

You ended up with a flight path movement generator without any flight path data, which would crash.

The aforementioned `Remove` call was changed to an assertion in ead439f, which should catch stuff like this during testing.
