### ISSUE TITLE
Core/Movements: Rooted Npcs musn't fall to the ground once dead

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22447]
**Description:** Rooted Npcs are falling to the ground once dead.

**Expected behavior:**  Rooted Npcs mustn't fall to the ground once dead.

**Steps to reproduce the problem:**

1. .go c id 29747
2. .die the eye
3. notice it falls to the ground

Here you can see it must remain dead at the spawn position: https://youtu.be/Dt-Z_Gj__pE?t=1m8s

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 28591fd1658e

**Operating system:** CHANGEME OS

**Comment by Krudor** [comment]
Not always true, some rooted creatures do fall to the ground on death, can't give you any 3.3.5 examples but for Cataclysm at least.

**Comment by Killyana** [comment]
We need examples to see the difference between a creature that falls and another one that doesn't.

**Comment by sirikfoll** [comment]
All the cases I've experienced so far, when they shouldn't fall, was due to missing this:
```sql
UPDATE `creature_template_movement` SET `Ground`=1, `Swim`=0, `Flight`=0, `Rooted`=1 WHERE `CreatureId`=29747;

**Comment by Killyana** [comment]
Npc 29747 have this:
Movement type: Ground: None, Swim: false, Flight: DisableGravity, Rooted

**Comment by Killyana** [comment]
It looks like sirikfoll is right npcs that mustn't fall have `Ground`=1 and `Flight`=0
The ones that falls `Ground`=0 and `Flight`=1

**Comment by illfated** [comment]
suggestion: **DB/Movement: elevated rooted NPCs must not fall to the ground when dead**
