### ISSUE TITLE
[3.3.5] Profession link problem

### ISSUE THREAD

**Issue by Winchester1987** [TrinityCore/TrinityCore#22446]
Some players can not link professions to chat. This affects to random players and I did not find a common pattern.

**Current behaviour:**
When a player links, for example Jewelcrafting, to the chat, it shows plain text instead of the profession link.
The console outputs:
"Player XXX sent a chatmessage with an invalid link - corrected"

ChatStrictLinkChecking.Severity is 0.

According to that console message, I think this may be related to f27284594b18000a1c098262728fb19fdc63fc6c

**Expected behaviour:**
The player should be able to link any profession to the chat

Branch: 3.3.5a
Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
OS: Windows 8.1 / Debian 9

**Comment by Aokromes** [comment]
if they use localized client (for example spanish or german or french client) you need to have the dbcs for those languages too.

**Comment by Aokromes** [comment]
p.s update your core, few followups where made to the initial commit.
https://i.imgur.com/aR50Xy6.png

**Comment by Treeston** [comment]
Does this consistently affect the same players, @Winchester1987?

**Comment by Hir0shi** [comment]
confirm

can't not sher link professions !

**Comment by Aokromes** [comment]
again, update your core before reporting bugs, to at least bf6082a8354910beef00551b1c17bcdfe9492ab1

**Comment by Winchester1987** [comment]
@Treeston yes.
A few random players have the problem, no matter what I do or try.
I even moved one character of those players to my own account, where all my characters works perfectly.
Deleting Cache y WTF everytime, that character does not work trying esES, esMX and enUS clients.

I have esES dbc locales.
ChatStrictLinkChecking.Severity = 1 → The player A, who uses enUS, client can not link professions to the chat because, ofcourse, I do not have the dbcs for that language.
                                                          → The player B, who uses esES client, can not link professions.
ChatStrictLinkChecking.Severity = 0 → The player A now can link professions to the chat.
                                                          → The player B still can not.

**Comment by Shauren** [comment]
can you provide a .pdump of that character?

**Comment by Winchester1987** [comment]
https://gist.github.com/Winchester1987/fad2d6ef7cc03506806ffc2f3ac1a5b2

**Comment by Winchester1987** [comment]
Oh right, it is the Transmogrification.
In a while, I will do the same without that.

**Comment by Treeston** [comment]
Should be fine, I manually removed the conflicting data. Can't reproduce on enUS, will get back to you once I get myself a esES client.

PS: I suspect it's due to the `í` in `Joyería`.

**Comment by Treeston** [comment]
Cannot reproduce on esES using `Severity = 0`

**Comment by Treeston** [comment]
Cannot reproduce on esES using `Severity = 1` either

**Comment by Treeston** [comment]
Hmm, can reproduce using provided pdump. Curious.

**Comment by Winchester1987** [comment]
I cannot reproduce using my characters either.
Other people can too. It affects some random characters and I can not find what they have in common.

**Comment by Treeston** [comment]
Heh. It breaks if the hex representation of their GUID contains `A` to `F`.

I thought that owner GUID field was decimal rawguid, the client sends hexadecimal rawguid. It never broke before (because we didn't even check that field), now it broke.

Fix incoming.
