### ISSUE TITLE
Core/Instance: Creature entry not updated correctly according to the team faction

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22459]
[A] Inside the Frozen Citadel (quest=24510)

End: Lady Jaina Proudmoore (npc=37597)
.npc info shows:
SpawnID: 201765
Entry: 37597
DisplayID: 28213 (She looks like Lady Sylvanas Windrunner)

<pre>SELECT entry, modelid1, modelid2, modelid3, modelid4, name FROM world.creature_template where entry=37597;</pre>

| entry  | modelid1 | modelid2  | modelid3 | modelid4  | name |
| ------------- | ------------- | ------------- | ------------- |------------- | ------------- |
| 37597  | 30867  | 0  | 0  | 0  | Lady Jaina Proudmoore  |

<pre>SELECT guid, id, modelid FROM world.creature where guid = 201765;</pre>

| guid  | id | modelid  |
| ------------- | ------------- | ------------- |
| 201765  | 37596  | 28213  |

-----------------------------------------------------------------------------------------
[A] The Pit of Saron (quest=24683)

Start:
Lady Jaina Proudmoore (npc=38160) -> Ok
Lady Jaina Proudmoore (npc=37597) -> This one should not start this quest

End:
Lady Jaina Proudmoore (npc=36993) -> Ok
Lady Jaina Proudmoore (npc=37597) -> This one should not end this quest
	   
Based on:
→ https://www.wowhead.com/quest=24683/the-pit-of-saron
→ http://wotlk.cavernoftime.com/quest=24683
→ Quest says "Meet Lady Jaina Proudmoore just inside the Pit of Saron." so it does not sound logic that you can turn in this quest inside the Forge of Souls

-----------------------------------------------------------------------------------------  
Lady Jaina Proudmoore (npc=36993)
.npc info shows:
SpawnID: 201886
Entry: 36993
DisplayID: 28213 (She looks like Lady Sylvanas Windrunner)

<pre>SELECT entry, modelid1, modelid2, modelid3, modelid4, name FROM world.creature_template where entry=36993;</pre>

| entry  | modelid1 | modelid2  | modelid3 | modelid4  | name |
| ------------- | ------------- | ------------- | ------------- |------------- | ------------- |
| 36993  | 30867  | 0  | 0  | 0  | Lady Jaina Proudmoore  |

<pre>SELECT guid, id, modelid FROM world.creature where guid = 201886;</pre>

| guid  | id | modelid  |
| ------------- | ------------- | ------------- |
| 201886  | 36990  | 28213  |

Branch: 3.3.5
TC Rev: e5d63bc5b02d0427beb2adf5571a90e92ebc1721
OS: Windows 8.1 / Debian 9

**Comment by TheWinchesters** [comment]
Is this related to the fact that an horde player sees Jaina Proudmoore (ID=37597) inside Forge of Souls and can not turn in the quest 'Inside the Frozen Citadel'? Or should I open a new issue?

**Comment by illfated** [comment]
I thought this would have something to do with the instance script not using correct DB values, but I could just as easily be wrong about that.
