### ISSUE TITLE
Kirin'Var Village, Netherstorm Item Quests Broken

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22455]
**Description:**
http://www.wowhead.com/item=28351/dathrics-blade
http://www.wowhead.com/quest=10182/battle-mage-dathric

http://www.wowhead.com/item=28336/belmaras-tome
http://www.wowhead.com/quest=10305/abjurist-belmara

http://www.wowhead.com/item=28352/luminraths-mantle
http://www.wowhead.com/quest=10306/conjurer-luminrath

http://www.wowhead.com/item=28353/cohliens-cap
http://www.wowhead.com/quest=10307/cohlien-frostweaver

Each quest requires that you take the quest item to a specific location (Bookshelf, Dresser, Footlocker or weapon rack), use the item (the item despawns on use) to spawn the original owner of that item.

**Current behaviour:**
The NPC spawns as **neutral**, stands still for a minute, then despawns. None of the 4 quests can be completed.

**Expected behaviour:**
The NPC should spawn with a neutral faction to the player, turn and walk to their gameobject (Bookshelf, Dresser, Footlocker or weapon rack), say some text about their own item, then despawn at the same time as quest completes (kill credit or quest state change).

**Steps to reproduce the problem:**
1. Use a level 68-70 character, go to Kirin'Var Village in Netherstorm.
2. .additem 28336, 28351, 28352, 28353
3. Right-click the quest items and accept the quests.
4. Take the quest items to their respective target game objects (Bookshelf, Dresser, Footlocker or weapon rack)
5. Right-click the item (which despawns) on their respective locations and see that the NPC spawns, but nothing more happens.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c5fa08afc1d1 2018-09-11 18:51:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

_Originally posted by @ghost in https://github.com/TrinityCore/TrinityCore/issues/20053#issuecomment-321997575_

**Comment by Killyana** [comment]
Cannot reproduce, works correctly on rev. 28591fd1658e
