### ISSUE TITLE
TC link filtering not blizzlike

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#22451]
**Description:**

TC and retail have some differences in the filtering rules.
If a message contains a link that cannot be corrected to text then it is not sent at all on retail, while on TC the link is removed but message is still sent otherwise.

Currently you can for example send empty messages if the message contains only invalid link.
Also sending a link and some text will send the text without the link.
This does not happen on retail.

You can close this if 335 didnt have it like this or this is irrelevant. :)

**Current behaviour:**

chat links that cannot be corrected are removed

**Expected behaviour:**

chat links that cannot be corrected should block the whole message from being sent

**Steps to reproduce the problem:**

1. Send the following messages on retail and on TC:
```
/run SendChatMessage("\124cFFDDD000\124Hquest:\124htest\124h\124r", "WHISPER", nil, GetUnitName("PLAYER"))
/run SendChatMessage("\124cFFDDD000\124Hquest:\124htest\124h\124raaa", "WHISPER", nil, GetUnitName("PLAYER"))
```
2. observe the difference of messages not sent on retail but are sent on TC without the link present.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d1a6546ff78d273d1759f9af5a2d26424739710c

**Operating system:**

windows 10

**Comment by Treeston** [comment]
Thinking about it some more, invalid links should only ever occur in a malicious attacker situation. Will change to filter these messages entirely again.

**Comment by Rochet2** [comment]
In the other issue I also noted that

> By the way. Interestingly sending an empty addon message disconnects you on retail.

But this I feel is probably something we can ignore. Just thought it might be relevant here.

**Comment by Treeston** [comment]
Hmm, elaborate on "empty addon message" please. Empty prefix and message?

Keep in mind 3.3.5 addon messages are actually sent as `prefix|message` last I checked.

**Comment by Treeston** [comment]
Scratch that, it's `prefix<tab>message`. Question still stands.

**Comment by Rochet2** [comment]
> Hmm, elaborate on "empty addon message" please. Empty prefix and message?

`/run C_ChatInfo.SendAddonMessage("test", "", "WHISPER", GetUnitName("player"))`

**Comment by Rochet2** [comment]
Does the change block the message from being sent if severity is 1 and I link with `[Hearthssstone]`?
On blizz only `Hearthssstone` is shown without the link (not sure about color though). Not that I would prefer it either way.

**Comment by Treeston** [comment]
Yeah, it blocks it entirely now. Will leave it this way.
