### ISSUE TITLE
Addon messages are being filtered

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#22450]
**Description:**

Chat links are filtered from addon messages. They should not be.
On retail you can run
```
/run C_ChatInfo.RegisterAddonMessagePrefix("test")
/run f = CreateFrame("Frame") f:SetScript("OnEvent", function(_,_,_, m) for i = 1, #m do print(m:sub(i,i)) end end) f:RegisterEvent("CHAT_MSG_ADDON")
/run C_ChatInfo.SendAddonMessage("test", "\124cFFDDD000\124Hquest:\124htest\124h\124r", "WHISPER", GetUnitName("player"))
```
and observe the full message being printed even though chat link is invalid.

In old code you can see this was checked, but in new code addon messages are filtered like all other messages:
https://github.com/TrinityCore/TrinityCore/pull/22417/files#diff-837bf337034c2e2b821314e771c2ee61L225

_By the way_. Interestingly sending an empty addon message disconnects you on retail.

**Current behaviour:**

Chat links are filtered from addon messages.

**Expected behaviour:**

They should not be.

**Steps to reproduce the problem:**

1. Send the following messages:
```
/run f = CreateFrame("Frame") f:SetScript("OnEvent", function(_,_,_, m) for i = 1, #m do print(m:sub(i,i)) end end) f:RegisterEvent("CHAT_MSG_ADDON")
/run SendAddonMessage("test", "\124cFFDDD000\124Hquest:\124htest\124h\124r", "WHISPER", GetUnitName("player"))
```
2. Observe no messages being printed.
3. Observe server log indicating of invalid chat link. `Player Chra (GUID: 7) sent a chatmessage with an invalid link - corrected`

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d1a6546ff78d273d1759f9af5a2d26424739710c

**Operating system:**

windows 10

**Comment by Rochet2** [comment]
Well, the chat link filtering removes for example `|a` from `|asd`.
I for one use compression in addon messages in AIO and the compression may result in | character, which means chat filtering will invalidate the whole compressed content.
Basically any text containing the pipe character will be screwed in addon messages.

Im sure there are more addons that use it than just mine, since it is supported on retail. I just dont use any addons so dont know any. Maybe someone else knows more widely used ones.

**Comment by Treeston** [comment]
Ah, I guess that's true, we hit messages that aren't even trying to be links. Will fix.
