### ISSUE TITLE
Core/Spell: Immunity from spell_school_immune_mask with positive spells

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22458]
**Description:** spell_school_immune_mask was added to make npcs immune to magic school.
Example the npc=18865 has spell_school_immune_mask =64 (SPELL_SCHOOL_ARCANE)
When the npc cast Arcane Shield on it self it resists and he don't get the buff
https://woehead.way-of-elendil.fr/?spell=36640

**Current behaviour:** spell_school_immune_mask effects positive and negative spells

**Expected behaviour:** spell_school_immune_mask must effect only negative spells

**Steps to reproduce the problem:**

1. .go c id 18865 
2. aggro the npc
3. notice he will cast 36640 but he will not get the shield

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 28591fd1658e

**Comment by Langerz82** [comment]
I'll take a look at this further tomorrow. ^-^

**Comment by Langerz82** [comment]
His only casting warp storm. Am I missing some SQL for him to cast the spell?

**Comment by Killyana** [comment]
This is the current sai
``` sql
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, COMMENT) VALUES
(18865, 0, 0, 0, 23, 0, 100, 0, 36640, 0, 1000, 1000, 0, 11, 36640, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Warp Aberration - On missing aura - Cast 'Arcane Shield' (No Repeat)"),
(18865, 0, 1, 0, 8, 0, 100, 513, 34520, 0, 0, 0, 0, 22, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Warp Aberration - On Spellhit 'Elemental Power Extractor' - Set Event Phase 1 (No Repeat)"),
(18865, 0, 2, 0, 6, 1, 100, 512, 0, 0, 0, 0, 0, 11, 34525, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Warp Aberration - On Just Died - Cast 'Create Elemental Power' (No Repeat)"),
(18865, 0, 3, 0, 0, 0, 100, 0, 2500, 5000, 30000, 35000, 0, 11, 36577, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Warp Aberration - In Combat - Cast 'Warp Storm' (No Repeat)");

**Comment by Langerz82** [comment]
think my changes was preventing the spell from even starting to cast, gotta test further and ty for quick reply.

**Comment by Langerz82** [comment]
Is it an instant spell? Im not seeing him trying to cast anything except Nova Storm.

**Comment by Killyana** [comment]
Just .unaura 36640  and he will cast the spell.

**Comment by Langerz82** [comment]
His still not casting the spell, are you using an updated revision?

**Comment by Killyana** [comment]
Just .go c id 18865  (with gm ON  no need to aggro the npc) you will see it casting the spell again and again, an the log will be spammed by:
Bouclier des arcanes Aberration dimensionnelle a échoué. Aberration dimensionnelle est insensible.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23999
