### ISSUE TITLE
Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22463]
**Description:**
https://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer

**Current behaviour:**
You can hop on the back of a mammoth but the game quickly attempts to resume it's mammoth meandering and random movement, usually taking you and the mammoth back to it's original spot where it may continue to wander around.

**Expected behaviour:**
You should have full control over the mammoth while riding it until such point you "leave vehicle", the mammoth dies, or you get kicked off for quest completion.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c5fa08afc1d1 2018-09-11 18:51:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by TheWinchesters** [comment]
This is reported here → #22368

**Comment by illfated** [comment]
Yes, as well as in #22431 which got closed due to similar behaviour as #22368 .
