### ISSUE TITLE
[3.3.5] Some few issues with Mage skills

### ISSUE THREAD

**Issue by santahashi** [TrinityCore/TrinityCore#22464]
**Description:**

1) Mage skills such as Frost Bolt and Fire Ball doesn't renew the effect on monster
2) If one of the monsters that got rooted from Frost Nova received damage the others will also get out of ice 
3) Blink sometimes drop out of map

**Expected behaviour:**

1) The effect renew
2) Only the monster that got hit can break out of ice, the rest stay rooted
3) Normally blink on map

**Branch(es):**

3.35 

**TC rev. hash/commit:** 

fcb45c4

**Operating system:** Windows Server 2012

Many thanks

**Comment by EricksOliveira** [comment]
Related to " Mage skills such as Frost Bolt and Fire Ball doesn't renew the effect on monster " 
there is already an open issue. [# 21635](https://github.com/TrinityCore/TrinityCore/issues/21635)
