### ISSUE TITLE
Hah... You're Not So Big Now

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22478]
**Description:**
https://www.wowhead.com/quest=11653/hah-youre-not-so-big-now
https://www.wowhead.com/item=34812/craftys-ultra-advanced-proto-typical-shortening-blaster
https://www.wowhead.com/npc=25434/magmoth-crusher
https://www.wowhead.com/npc=25432/mate-of-magmothregar

[List of Spell Effects](https://www.wowhead.com/item=34812/craftys-ultra-advanced-proto-typical-shortening-blaster#comments:id=624842)

**Current behaviour:**
Killing a Magmoth Crusher or Mate of Magmothregar with a debuff aura cast by Crafty's Ultra-Advanced Proto-Typical Shortening Blaster does not always grant credit for the quest. Only some debuffs appear to work as intended.

Does not grant quest criteria if debuff aura is [Yellow](https://www.wowhead.com/spell=45677/yellow)

**Expected behaviour:**
If the quest mob has a debuff aura from the quest item on it at the time of death it should grant quest criteria.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
It's not related to auras, only Magmoth Crusher have the script to give credit

**Comment by illfated** [comment]
@jerbookins : Thank you for only writing the quest title in the issue title, it was kind of funny to see in the [Notifications](https://github.com/notifications) list, it made me chuckle (normally we include a prefix like **DB/Quest;** ). Thanks.

**Comment by jerbookins** [comment]
> It's not related to auras, only Magmoth Crusher have the script to give credit

That doesn't make it right.

From the quest:
> Test out Crafty's Ultra-Advanced Proto-Typical Shortening Blaster on 5 Magmoth Crushers or Mates of Magmothregar. After you have done so, return to her at Fizzcrank Airstrip.

**Comment by jerbookins** [comment]
@illfated If I don't do anything, it usually gets corrected by a mod. And If I try to give it the right title, it usually gets corrected by a mod. So... I dunno. Not really going to worry about it because ultimately I'm not at the level of knowledge about the naming schemes that the rest of you devs are.
