### ISSUE TITLE
DB/Quest: Iron Rune Constructs and You: Collecting Data

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22484]
**Description:**
https://www.wowhead.com/quest=11489/iron-rune-constructs-and-you-collecting-data
https://www.wowhead.com/spell=44550/collect-data
https://www.wowhead.com/spell=44551/collect-data-credit

![wowscrnshot_092118_173901](https://user-images.githubusercontent.com/16745918/45910422-22cf8600-bdc6-11e8-8952-6e7ad9b45e4b.jpg)

**Current behaviour:**
Using the spell Collect Data at the specified location while controlling the Iron Rune Construct emits an electrical spell effect at empty space above a wheelbarrow. No quest credit is provided.

**Expected behaviour:**
There is supposed to be a floating blue crystal above the wheelbarrow. Casting Collect Data should provide credit for the quest.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Related to gameobjects issues

**Comment by Killyana** [comment]
works fine
