### ISSUE TITLE
DB/Quest: Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22485]
**Description:**
https://www.wowhead.com/quest=11491/iron-rune-constructs-and-you-the-bluff
https://www.wowhead.com/spell=44562/bluff

**Current behaviour:**
When you walk on Lebronski's rug he says
> What do you think you're doing, man? Lebronski does NOT appreciate you dragging your loose metal parts all over his rug.

When you cast the spell Bluff, Lebronski says
> Far out, man. This bucket of bolts might make it after all...

but it does not trigger the quest criteria to be completed.

**Expected behaviour:**
The quest criteria should be given when you cast the Bluff spell after ~~Lebowski~~ Lebronski gets pissed at you.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Related to gameobjects issues

**Comment by Killyana** [comment]
works fine
