### ISSUE TITLE
DB/Quest: Lightning Infused Relics

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22486]
**Description:**
https://www.wowhead.com/quest=11494/lightning-infused-relics
https://www.wowhead.com/spell=44610/collect-data

**Current behaviour:**
Using the Collect Data spell on the blue crystals does not trigger quest criteria to complete the quest.

**Expected behaviour:**
Using the Collect Data spell on the blue crystals should trigger quest criteria to complete the quest.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Related to gameobject issues.

**Comment by lactoseti** [comment]
fix (tested):
```sql
UPDATE smart_scripts SET action_param1 = 6000 WHERE entryorguid = 24824;

**Comment by Killyana** [comment]
I saw a similar issue where the npc must cast a spell and despawn, if you use the exact same timer in this case 5secs the despawn happen before the other action and the script fails.

**Comment by lactoseti** [comment]
you're absolutely right; that's what was causing it.  I saw the fix you put in is a little different--I'll take a look but if it's easy to explain, how does it work?  I saw a couple other quests that have similar issues and would like to submit fixes the right way

**Comment by illfated** [comment]
Related to the description content of the Collect Data Credit spell (44611):
- https://www.wowhead.com/spell=44611/collect-data-credit

**Comment by Killyana** [comment]
@lactoseti  it depends, in this case it's a spell triggered by an other, the second spell must be usedby the spell_hit event and not the first one to avoid setting a timer for the despawn

**Comment by Freeman256** [comment]
At the moment the quest is working, but there are still problems:
1) The golem, for some reason, can fly. It shouldn't be like that;
2) The ability "Bluff" does not work, and overly suspicious dwarves expose the player, they all become aggressive towards him, and the player has to return to the camp of the league of explorers to disguise himself as a golem again. 

https://github.com/TrinityCore/TrinityCore/commit/7050a5ccb617dae2b329c8f7d8d08e6c502a9370
TrinityCore rev. 2021-08-10 ‏‎‏‎19:13:59 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by offl** [comment]
Always create a new issue if you want to report a bug
