### ISSUE TITLE
DB/Quest: Into the World of Spirits

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22480]
**Description:**
https://www.wowhead.com/quest=11333/into-the-world-of-spirits
https://www.wowhead.com/item=33635/reagent-pouch

**Current behaviour:**
The Reagent Pouch is nowhere to be found. .gobject near 100 resulted in only Valgarde Supply Crates

**Expected behaviour:**
Reagent Pouch should be located on the deck of the sunken ship in Daggercap Bay.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Aokromes** [comment]
INSERT INTO `trinity335`.`gameobject`(`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES (56732, 186662, 571, 0, 0, 1, 1, 1032.58, -5153.86, -51.1602, -1.64061, 0, 0, -0.731354, 0.681998, 300, 100, 1, '', 0);

It's there for me.

**Comment by Killyana** [comment]
It's not the same spot indicate by the game or quest helper, I don't know if the position must be updated or if there's a pool.

**Comment by Aokromes** [comment]
acording wowhead photo it's where it's spawned.

**Comment by illfated** [comment]
Found it using a level 60 horde GM character, but much closer to Utgarde Keep and its waterfall than indicated by Carbonite / Quest Helper.
GM command to find it directly: `.go gameobject 56732`
Also confirmed that "Find herbs" shows it on the minimap, whereas removing the quest from log deactivates the object (still visible).

TrinityCore rev. 28a91300eb9c 2018-09-22 04:56:39 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.6.41
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Comment by ZenoX92** [comment]
There seems to be at least 3 different spots where the object is spawned, and I don't think it requires a pool. According to some wowhead comments, the object is spawned in different locations at the same time.
```sql
-- Reagent Pouch
SET @GUID := XXXX;
DELETE FROM `gameobject` WHERE `guid` IN (@GUID, @GUID+1);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(@GUID,186662,571,0,0,1,1,728.518,-5168.96,-74.5936,3.31947,-0,-0,-0.996048,0.0888202,300,100,1,"",0),
(@GUID+1,186662,571,0,0,1,1,797.097,-5146.8,-82.1851,2.47513,-0,-0,-0.944991,-0.327096,300,100,1,"",0);

**Comment by Killyana** [comment]
According to the quest text, it's unique:

- Thoralius the Wise at Valgarde wants you to find his Reagent Pouch

- If you wish to learn more, I will require my reagent pouch. It was lost in a ship that is now at the bottom of Daggercap Bay, just east of here. 

- Have you found my reagent pouch?

**Comment by ZenoX92** [comment]
I know, but the comments here suggest otherwise.
https://www.wowhead.com/quest=11333/into-the-world-of-spirits

**Comment by ZenoX92** [comment]
Anyway, if you need a pool here you go:
```sql
-- Reagent Pouch
SET @GUID := XXXX;
SET @POOL := YYYY;
DELETE FROM `gameobject` WHERE `guid` IN (@GUID, @GUID+1);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(@GUID,186662,571,0,0,1,1,728.518,-5168.96,-74.5936,3.31947,-0,-0,-0.996048,0.0888202,300,100,1,"",0),
(@GUID+1,186662,571,0,0,1,1,797.097,-5146.8,-82.1851,2.47513,-0,-0,-0.944991,-0.327096,300,100,1,"",0);

DELETE FROM `pool_template` WHERE `entry`=@POOL;
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES
(@POOL,1,"Reagent Pouch");

DELETE FROM `pool_gameobject` WHERE `pool_entry`=@POOL;
INSERT INTO `pool_gameobject` (`guid`, `pool_entry`, `chance`, `description`) VALUES
(@GUID,@POOL,0,"Reagent Pouch (186662) - Spawn 1"),
(@GUID+1,@POOL,0,"Reagent Pouch (186662) - Spawn 2"),
(56732,@POOL,0,"Reagent Pouch (186662) - Spawn 3");
