### ISSUE TITLE
Trained Rock Falcon

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22482]
**Description:**
https://www.wowhead.com/quest=11465/the-ransacked-caravan
https://www.wowhead.com/item=34111/trained-rock-falcon

https://www.wowhead.com/quest=11468/falcon-versus-hawk
https://www.wowhead.com/item=34121/trained-rock-falcon

**Current behaviour:**
Using the Trained Rock Falcon successfully sends a falcon to your target, the target disappears when the falcon reaches it, the falcon returns to you but does not give you the needed quest item.

**Expected behaviour:**
When the falcon returns, you should collect 1 quest item.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Ontari784ever** [comment]
Confirmed on TrinityCore rev. 1daf318, same behaviour as in description.
Nagrand.net - https://www.youtube.com/watch?v=7vcHD4k4v5s&feature=youtu.be

Battle.net - https://www.youtube.com/watch?time_continue=44&v=2zXNyD8n8bk

**Comment by sirikfoll** [comment]
Not sure if correct, but this fixes the issue and make it look more blizzlike (item is added when the falcon hit the target, not the player)
In SpellMgr.cpp
```cpp
ApplySpellFix({ 44327, 44408 }, [](SpellInfo* spellInfo)
{
    spellInfo->Speed = 0.0f;
});

**Comment by tarwyn** [comment]
I applied the patch from @sirikfoll and can confirm that it fixes the issue.

**Comment by illfated** [comment]
I could open a Pull Request for the patch to be added, but I have forgotten any rules (if there are any) for where to place new additions in the current `SpellMgr.cpp` file content. (How is the order arranged, how can I tell where to place any new `ApplySpellFix` lines?)

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L4423

**Comment by illfated** [comment]
Oh. right. I see. So we should expand the existing spell correction instead of adding a new one, I presume.
```cpp
// Trained Rock Falcon & Frost Bomb
    ApplySpellFix({ 44327, 44408, 69846 }, [](SpellInfo* spellInfo)
    {
        spellInfo->Speed = 0.0f;    // This spell's summon happens instantly
    });
```
Does my attempt above look correct to you?

**Comment by Keader** [comment]
yes @illfated
