### ISSUE TITLE
Fjord Hawk Eggs

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22483]
**Description:**
https://www.wowhead.com/quest=11470/there-exists-no-honor-among-birds
https://www.wowhead.com/object=186946/fjord-hawk-egg
https://www.wowhead.com/item=34123/fjord-hawk-egg

**Current behaviour:**
Opening a Fjord Hawk Egg (object) for a Fjord Hawk Egg (item) does not make the object disappear upon collection of the item. You can sit at one egg and collect all 8 quest items.

**Expected behaviour:**
The egg should disappear and respawn after a while.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by offl** [comment]
Handled by Effect 1 (Activate Object: (Despawn)) of spell [Scavenge](http://wowhead.com/spell=44422), Activate Object effect was implemented in https://github.com/TrinityCore/TrinityCore/commit/203573db83fb1d3f141b5aadbf1d1ca0a637bf94, condition for spell to target eggs already added long time ago.
