### ISSUE TITLE
Halls of Stone: Brann Bronzebeard

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22488]
Without any character interacting or being close to Brann Bronzebeard (https://www.wowhead.com/npc=28070), this NPC is killed by a walking Unrelenting Construct (https://www.wowhead.com/npc=27971) that gets too close to him.

https://ibb.co/bF5iuz

**Expected behaviour:**
Brann Bronzebeard should not be killed while the event is not started.

Branch: 3.3.5
TC Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
OS: Windows 8.1 / Debian 9

**Comment by CraftedRO** [comment]
b19d7c51f573 Without any interaction can't confirm this issue anymore (tested on both difficulties).


https://user-images.githubusercontent.com/24683355/192083701-8fbe7693-5f19-4b4d-96d0-38007424c648.mp4
