### ISSUE TITLE
DB/Quest: We Call Him Steelfeather

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22497]
**Description:**
https://www.wowhead.com/quest=11418/we-call-him-steelfeather
https://www.wowhead.com/item=34026/feathered-charm

**Current behaviour:**
Using the Feathered Charm allows you to see through Steelfeather's eyes, but all she does is fly around in a circle above town.

**Expected behaviour:**
When you use Feathered Charm, Steelfeather is supposed to fly directly to her nest and hang out with her chicks for around 5-10 seconds and then credit is given for the quest for Learning Steelfeather's Secret.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6859
