### ISSUE TITLE
[DB] Error Logs

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22499]
DataBase.log Errors

<details>
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 13895, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 10486, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 3550, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 11374, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 6957, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
SQL(p): INSERT INTO character_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (3743, 3743, 59620, 3, 3, 1, 400, -5, 0, 399, -6, 0, 15000, 4938, 0, 0, 1)

 [ERROR]: [1062] Duplicate entry '3743-3743-59620-3' for key 'PRIMARY'
</details>

Branch(es):
3.3.5
TC rev. hash/commit:
TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/609c1acc09c7f25f047638224036ae497a1a964b

database :TDB64 + all updates.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22234
