### ISSUE TITLE
DB/Quest: Everything Must Be Ready

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22495]
**Description:**
https://www.wowhead.com/npc=24494/quartermaster-brevin
https://www.wowhead.com/quest=11406/everything-must-be-ready
https://www.wowhead.com/quest=11250/all-hail-the-conqueror-of-skorn

**Current behaviour:**
Quartermaster Brevin doesn't offer the quest Everything Must Be Ready after completing All Hail the Conquerer of Skorn!

quest_template_addon:
![image](https://user-images.githubusercontent.com/16745918/45925657-ff483080-bed6-11e8-984d-ac7b61d8d898.png)

creature_queststarter:
![image](https://user-images.githubusercontent.com/16745918/45925650-de7fdb00-bed6-11e8-80e5-3f60327b0e36.png)

**Expected behaviour:**
Quartermaster Brevin should offer the quest Everything Must Be Ready.

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Everything Must Be Ready is a Breadcrumb quest for Down to the Wire, so if Down to the Wire is taken or rewarded, "Everything Must Be Ready" will no longer be available.

But there's an issue with  Preying Upon the Weak that use Everything Must Be Ready as requirement, and Breadcrumb quests must never be used as requirements.
