### ISSUE TITLE
DB/Quest: Danger! Explosives!

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22490]
**Description:**
https://www.wowhead.com/quest=11218/danger-explosives
https://www.wowhead.com/item=33190/steelrings-foolproof-dynamite
https://www.wowhead.com/object=186403/whisper-gulch-ore
https://www.wowhead.com/object=186468/whisper-gulch-ore-fragment
https://www.wowhead.com/object=186404/whisper-gulch-gem

**Current behaviour:**
Using the Dynamite on Whisper Gulch Ore does not cause the Ore to explode into parts of Whisper Gulch Ore Fragments or Gems

**Expected behaviour:**
Using the Dynamite on Whisper Gulch Ore should cause the Ore to explode into parts of Whisper Gulch Ore Fragments and Gems

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by illfated** [comment]
Any server console messages or entries in any of the Log files during your attempts to use the dynamite on the ores?

**Comment by Killyana** [comment]
Related to the gameobject trap issues.

**Comment by illfated** [comment]
OK, thanks. I thought perhaps it had something to do with gameobject faction issues.

**Comment by jerbookins** [comment]
When you use the dynamite, the items despawn after about 2 seconds which is only about enough time to pick up one at a time. 16fde1ffad38
