### ISSUE TITLE
[3.3.5] DB/Spells/Procs: Battlegear of Eternal Justice, paladins AQ20 set

### ISSUE THREAD

**Issue by Nyeriah** [TrinityCore/TrinityCore#22503]
**Description:**

Currently the set bonus never procs because procs are set to "Successful hit from ranged spell that uses ranged weapon" at DBC but the Judgement damage spell (54158) has damage class 2 (SPELL_DAMAGE_CLASS_MELEE), so it never procs.

**Expected behaviour:**

Should have a 20% chance to regen 100 mana on every successful judgement hit.

**Steps to reproduce the problem:**

1. Equip those items https://www.wowhead.com/item-set=506/battlegear-of-eternal-justice
2. Cast judgement on something for a while

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

https://github.com/TrinityCore/TrinityCore/commit/135aed62a844d1af62fa1034b81173b8c1af811a

Fix:
``` SQL
UPDATE `spell_proc` SET `ProcFlags` = `ProcFlags` |16 WHERE `SpellId` = 26135;
```

**Comment by Nyeriah** [comment]
The same happens with paladin's judgement set bonus

``` SQL
DELETE FROM `spell_proc` WHERE `SpellId` = 23591;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(23591, 0, 10, 8388608, 0, 0, 16, 0, 2, 0, 2, 0, 0, 0, 0);
```

I am guessing outdated DBCs, since those were vanilla bonuses and things changed quite a lot from vanilla to wrath.

**Comment by Keader** [comment]
yeah, both looks correct to me.
