### ISSUE TITLE
DB/Quest: Defending Wyrmrest Temple

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22500]
**Description:**
https://www.wowhead.com/quest=12372/defending-wyrmrest-temple
https://www.wowhead.com/npc=27629/wyrmrest-defender
https://www.wowhead.com/spell=49243/immolation
https://www.wowhead.com/npc=27682/azure-drake

**Current behaviour:**
While riding a Wyrmrest Defender, using the spell Immolate on an Azure Drake says "invalid target".

**Expected behaviour:**
You should be able to use Immolate on Azure Dragons and Drakes.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
If someone can move this gossip option to the DB https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_dragonblight.cpp#L490 , it's already there just need to be used on the cpp:
``` sql
SELECT * FROM gossip_menu_option WHERE menu_id IN (9568);

**Comment by illfated** [comment]
It would be my pleasure to help you killing that `#define` and move it to enum.
Is a diff patch enough, or would you like a PR for it?
