### ISSUE TITLE
Crash after using .go c id 29799

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22502]
As the title says, the only thing I did, while doing quests, was trying to go to the NPC 29799 and worldserver crashed.
(https://www.wowhead.com/npc=29799/thassarian)

**Steps to reproduce the problem:**
1. .go c id 29799

I have 3 versions, different OS.
One is recent, two are a week older.
I will share the crashlogs of each one just with the purpose of giving extra info in case it is useful.

Branch 3.3.5 (for all of them)

Version 1:
TC rev: 609c1acc09c7f25f047638224036ae497a1a964b
RelWithDevInfo
OS: Windows 8.1
Crashlog: https://gist.github.com/TheWinchesters/4a742829ea0bfc4710dee8f2065717a4

Version 2:
TC Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
RelWithDevInfo
OS: Windows 8.1
Crashlog: https://gist.github.com/TheWinchesters/417637921284ed80dbdc53951a88ab6a

Version 3:
TC Rev: ce46a0d53c3dbd6d2837020686e3880d98c545ed
Debug
OS: Debian 9
Crashlog: https://gist.github.com/TheWinchesters/b1a9371fbcadad07bb1d942662bec487

I will be compiling again so I can test this with last rev.

**Comment by Aokromes** [comment]
b27a769

**Comment by TheWinchesters** [comment]
Just some hours late haha
