### ISSUE TITLE
DB/Loot: Adjust wolf trash drops in Northshire

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#22519]
**Description:**

Follow up to https://github.com/TrinityCore/TrinityCore/issues/20624 since the trash drops on the two wolves are set too low.

The suggested fix increases the chances of ruined pelt, broken claw and chipped claw to 33% and groups them so one will always drop. The NPCs are:

https://www.wowhead.com/npc=69/diseased-timber-wolf
https://www.wowhead.com/npc=299/young-wolf

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d5888a5f8f49

**Suggested Fix**

```sql
UPDATE `creature_loot_template` SET `Chance`=33.3,`GroupID`=1 WHERE `Entry` IN (299,69) AND `Item` IN (4865,7073,7074);
```

**Comment by illfated** [comment]
Keep up the good work, we do appreciate it. I often think I should look into this myself when I get a lot of empty loot, but I always end up wasting too much time looking for proof for the drop rates, resulting in me giving up on the individual creatures dropping either too much or nothing at all.
