### ISSUE TITLE
[3.3.5] Chat Latin American characters blocked

### ISSUE THREAD

**Issue by boveloco** [TrinityCore/TrinityCore#22511]
**Description:**

When any Latin American Characters are written, the message is blocked;

Eg: é, á, ã, ñ, º, etc

**Current behaviour:**

It's logged and the message is blocked.

**Expected behaviour:**

The message is delivered to the chat.

**Steps to reproduce the problem:**

Write any cases above in chat!

**Branch(es):** 3.3.5

**TC hash/commit**: fcb45c416a6aa72ef1019e8ee8445b38d102aa0e
 
**TDB version**:  1E0A9E1EB8795CBAA1BA778DFFAFEC27F1BE45B8

Operating system: Ubuntu 18.04.1

this code is blocking the string. Don't know if i change it what could be the side effects.

```
 if (isNasty(c))
             {
                 TC_LOG_ERROR("network", "Player %s (GUID: %u) sent a message containing invalid character %u - blocked", GetPlayer()->GetName().c_str(),
                     GetPlayer()->GetGUID().GetCounter(), uint8(c));
                return;
            }
```

**Comment by funjoker** [comment]
`isNasty`is correct

it filters:

```
^@
^A
^B
^C
^D
^E
^F
^G
^H
^I
^J
^K
^L
^M
^N
^O
^P
^Q
^R
^S
^T
^U
^V
^W
^X
^Y
^Z
^[
^\
^]
^^
^_

```
