### ISSUE TITLE
Core/Command: Appear provide a wrong undermap position

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22514]
.app player

Game Master goes under the ground, Some areas

for fix , gm fly on.

Branch(es):
3.3.5
TC rev. hash/commit:
TrinityCore rev. 609c1ac

**Comment by jackpoz** [comment]
any example about where this happens ? a .gps coordinate of the target player would be nice

**Comment by Aokromes** [comment]
i am sure this is duplicate ticket, but cannot find other

**Comment by Aokromes** [comment]
no, gm command too.

**Comment by Killyana** [comment]
Actually I get this issue, but you can reproduce it only once per connection:
1- Connect the first char
2- .go xyz 3559.759, 352.908, 118.595978 571   (Char1)
3- Connect the second char
4- .tele shattrath (then disconnect the second char and reconnect it)
5- .appear char1 and notice the position

Position of the char1: 3559.759, 352.908, 118.595978
Position of the char2: 3557.179,  355.273, -507.334320 (after the appear "under map")

The correct position of the appear must be 3556.445068 Y: 351.782349 Z: 118.595978 (you can get it by usinf appear a second time)

**Comment by Shauren** [comment]
Cause: WorldObject::GetNearPoint calls `(searcher ? searcher : this)->UpdateAllowedPositionZ(x, y, z)` which looks for Z coord at original gm map (GetContactPoint should never be used for units on different maps)
