### ISSUE TITLE
Core/ICC: Skybreaker Mortar Soldier/Kor'kron Rocketeer

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22517]
**Description:**
These NPCs in the gunship battle:
https://www.wowhead.com/npc=36978 (A)
https://www.wowhead.com/npc=36982 (H)

They do nothing, they do not attack or act defensive or use spells/habilities.

Branch: 3.3.5
TC Rev: 7baf5b2
OS: Win 8.1 / Debian 9

**Comment by Killyana** [comment]
They just cast rocket to gunship, it's the retail behavior.

**Comment by Shauren** [comment]
Yeah, not a bug

**Comment by TheWinchesters** [comment]
Ooh, sorry for the bad report and thanks for the answers!
