### ISSUE TITLE
Crash in Player.cpp related to questgiver

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22516]
This is a bad report because I have nothing but a crashlog.
The only thing I know is that it is related to:
`if (auto questStatus = questgiver->ToCreature()->AI()->GetDialogStatus(this))`

https://gist.github.com/TheWinchesters/70a1621a31142224906678f0bdc8dcf9

Branch: 3.3.5
TC Rev: 7baf5b2
OS: Win 8.1 / Debian 9

**Comment by illfated** [comment]
Your debug crash log with backtrace is a good start.
I have seen a lot worse than this, so don't worry.

**Comment by Hir0shi** [comment]
Any News!

**Comment by jackpoz** [comment]
@Hir0shi every time you want to confirm a crash you must fill a proper crash report with revision, platform, TDB version and adding the link to the crashlog uploaded to Gist . Simply writing "confirm" is totally useless.

**Comment by Hir0shi** [comment]
ilove you:D

**Comment by jackpoz** [comment]
this crash happens somewhere in an instance as there is InstanceMap::Update() in the callstack

**Comment by TheWinchesters** [comment]
I have tried and nothing.
I even tried that several characters interact with Coren at the same time, one with quest 11486, other with quest 11454, and other one made Coren enemy.
I will keep trying different things.

**Comment by jackpoz** [comment]
@TheWinchesters any news about this issue ? did it happen again or should we just close it ?

**Comment by jackpoz** [comment]
@Keader I thought the same and wrote a patch before reading your comment :)
Maybe there's even a Coverity/PVS-Studio issue about it but I haven't had time to check those in a while.

Fixed in https://github.com/TrinityCore/TrinityCore/commit/6859dfa2d157f0d174004a00a9d047d6eb38f9a1
