### ISSUE TITLE
Spell: Wing Buffet

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22512]
**Description:**
https://www.wowhead.com/spell=48620/wing-buffet
https://www.wowhead.com/quest=12255/the-thane-of-voldrune

**Current behaviour:**
While flying the dragon, Flamebringer, during the quest The Thane of Voldrune, the spell Wing Buffet does not incur the GCD and is usable while other spells are on GCD.

**Expected behaviour:**
Wing Buffet should be on the GCD.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 6490408d4ef5 2018-09-20 03:03:00 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by illfated** [comment]
I know, miniscule and cosmetic, but I guess you meant Global Cooldown (GCD) and not Global Downcool (GDC)
(or Game Developers' Conference (GDC), for that matter).

**Comment by jerbookins** [comment]
Hah. Yep. Probably why I didn't realize it was a typo.

**Comment by Killyana** [comment]
I'm pretty sure there's an issue about pet/guardian spells not triggering the CD, but I cannot find it.
