### ISSUE TITLE
[3.3.5] Core/Spell: Wrong Warrior Spell

### ISSUE THREAD

**Issue by devfrom** [TrinityCore/TrinityCore#22526]
**Description:**

Wrong Warrior Spell

**Current behavior:**
When we use the spells [Shield Block] [Shield Reflect] and then swap Shield and One-hand for a Two-hand Spell still continues.

**Expected behavior:**

When switching from one-hand and shield to two-hand weapons the spell must be removed.

Steps to reproduce the problem:

Branch (s):

3.3.5 Rev 64

TC rev. hash / commit:

https://github.com/TrinityCore/TrinityCore/commit/af704150215e35ecc9108dadafa903f40a3d7107

Operational system:

Windows 7 Ultimate

**Comment by illfated** [comment]
Extra information (which could have been added in your issue post):
- https://woehead.way-of-elendil.fr/?spell=2565 (Shield Block)
- https://woehead.way-of-elendil.fr/?search=Shield+Reflect#spells

**Comment by Killyana** [comment]
@Keader close ? https://github.com/TrinityCore/TrinityCore/issues/21594

**Comment by illfated** [comment]
According to @ariel- in https://github.com/TrinityCore/TrinityCore/issues/21594#issuecomment-372192023 it is intended (Blizzlike) behaviour
(would be nice to get a "confirm" from Keader too, though).

**Comment by Keader** [comment]
ariel say that it is blizzlike, so invalid.

**Comment by devfrom** [comment]
@Keader I did not understand the comment

**Comment by Keader** [comment]
read https://github.com/TrinityCore/TrinityCore/issues/21594#issuecomment-372192023 @devfrom.
i reported it some months ago, and ariel say that it is indeed
