### ISSUE TITLE
Core/Spell: Rockbiter Weapon

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22528]
**Description:** When a Shaman use https://woehead.way-of-elendil.fr/?spell=10399 the amount of bonus will stay event if the enchant is replaced by something else like https://woehead.way-of-elendil.fr/?spell=51993

**Steps to reproduce the problem:**

1. Connect a shaman and use https://woehead.way-of-elendil.fr/?spell=10399
2. Right click on the buff to remove it and notice the damage bonus will not be subtracted
3. You can also use https://woehead.way-of-elendil.fr/?spell=51993 after https://woehead.way-of-elendil.fr/?spell=10399 and you will have the same result 

**Branch(es):** 3.3.5

**TC rev. hash/commit:** TrinityCore rev. 0b0bbe433094 2018-09-25

**Comment by Langerz82** [comment]
Might be related to:
https://github.com/TrinityCore/TrinityCore/issues/22051

Dispell should be working correctly on that patch.

**Comment by Killyana** [comment]
No this issue could be reproduced on 2 old core
