### ISSUE TITLE
[3.3.5] Some places in the city of storms, factions can not attack

### ISSUE THREAD

**Issue by diegobfl** [TrinityCore/TrinityCore#22524]
**Description:**

Some sites of stormwind factions can not attack themselves

**Current behavior:**

When the two factions are in certain places and also inside the water as shown in the video below, the attack is not allowed.

see the video below
https://youtu.be/bDoB_ktGwZA

**Expected behavior:**

The two factions must become enemies in the territory of the city

Steps to reproduce the problem:

I do not know at the moment

Branch (s):

3.3.5 Rev 64 Clear 32x

TC rev. hash / commit:

5fee6ec

Operational system:

Windows Server 2008 R2

**Comment by Killyana** [comment]
I cannot reproduce on TrinityCore rev. 0b0bbe433094 
I tested in the exact spot shown in the video
