### ISSUE TITLE
[3.3.5] Core/Spell: Fear - [Psychic Scream]  [Howl of Terror] and Terror are wrong 

### ISSUE THREAD

**Issue by diegobfl** [TrinityCore/TrinityCore#22523]
**Description:**

Fear - [Psychic Scream]  [Howl of Terror] and Terror are wrong

**Current behavior:**
When the priest uses the [Psychic Scream] spell on two or more target players and players use a human trinket or racial effects remover, two things go wrong:

1. Two target in Fear and only 1 use the human trinket or racial effect remover, the other targets also removed the fear. Video 0.31 seconds

2. Two targets or more in Fear and only 1 use the human trinket or racial removal effect, Fear returns automatically. Video: 0.8 seconds

see the video below
https://youtu.be/tT2us3cVRC4

**Expected behavior:**

1. Two or more target players in Fear use human trinket or racial effects remover, only you should get out of fear and not the other targets

2. Use trinket or racial human effects remover to get out of Fear, he should not get Fear again.

**Steps to reproduce the problem:**

I do not know at the moment.

Branch (s):

3.3.5 Rev 64 Clean 32x

TC rev. hash / commit:

https://github.com/TrinityCore/TrinityCore/commit/5fee6ec642e8b36ede1fc78b1afe402eab597e0b

Operational system:

Windows Server 2008 R2

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21810
