### ISSUE TITLE
DB/Quest: Learning to Leave and Return: the Magical Way

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22530]
**Description:**
In the quest Learning to Leave and Return: the Magical Way (https://www.wowhead.com/quest=12790) you have to use the Teleport to Violet Stand Crystal and the Teleport to Dalaran Crystal.

**Current behaviour:**
Teleport to Violet Stand Crystal (https://www.wowhead.com/object=191229) does not teleport the character.
And since you need to use that one to be able to use Teleport to Dalaran Crystal (https://www.wowhead.com/object=191230) I do not know if this one works.

**Expected behaviour:**
You should be teleported after using the crystals.

**Steps to reproduce the problem:**
1. .q a 12790
2. .go c id 29156
3. Try using the crystal

Branch: 3.3.5
TC Rev.: 7baf5b24525551ddf00c88084edb2a1bafeb758d
OS: Windows 8.1 / Debian 9

**Comment by nagrandbugtracker** [comment]
It does work but you literally need to stand below the crystals.

**Comment by illfated** [comment]
That is interesting. Maybe this has got something to do with
GameObject usage radius, similar to the issue discussed in https://github.com/TrinityCore/TrinityCore/issues/15453 ?
([**Core/GameObject: Large GOs and gossip availability**](https://github.com/TrinityCore/TrinityCore/issues/15453))

**Comment by kaiyazeera** [comment]
I just ran into this issue, too. The quest object was marked completed, but I wasn't teleported. It did work however to stand directly below the crystals. Kinda irritating, would probably not have noticed if it wasn't for @Ontari784ever mentioning it (thanks!)
