### ISSUE TITLE
Crash worldserver: Player.cpp → (mod->type == SPELLMOD_FLAT) ? SMSG_SET_FLAT_SPELL_MODIFIER : SMSG_SET_PCT_SPELL_MODIFIER;

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22533]
**Description:**
Once again, I just have a crashlog. I can not give more info since I am still not good reading crashlogs.

https://gist.github.com/TheWinchesters/f797414ad8c4d2f47527e990b8a8d6cd

This happened just once.
I have a server with just a little group of people so how many people is playing could be a factor.

Branch: 3.3.5
TC Rev.: 7baf5b2
OS: Windows 8.1 / Debian 9

**Comment by jackpoz** [comment]
This happened in an instance when spell 31224 Cloak of Shadows expired from a player.

**Comment by TheWinchesters** [comment]
Maybe a specific instance? Should I go to all instances to see if I can replicate the crash?

**Comment by sirikfoll** [comment]
I've had some similar crashes, about 1 every couple months since January, my logs are very limited, but just in case:
https://gist.github.com/sirikfoll/5dda9ad412d597c3dd4db8f446d0e296
https://gist.github.com/sirikfoll/d22211bf339eae50f71ea33359f41e4d
https://gist.github.com/sirikfoll/775f4e07730d4554cbc98a42d601f01e
https://gist.github.com/sirikfoll/024b203850907233c1813e8b0cd83a60

**Comment by jackpoz** [comment]
all these crashes seem to happen on logout with the most different spells:
- https://wotlk.evowow.com/?spell=67188
- https://wotlk.evowow.com/?spell=18744
- https://wotlk.evowow.com/?spell=19287
- https://wotlk.evowow.com/?spell=33607

**Comment by illfated** [comment]
... or for those of us who are too lazy to turn off our adblock addon (& w/names included) :
- https://woehead.way-of-elendil.fr/?spell=67188/item-paladin-t9-retribution-2p-bonus-righteous-vengeance
- https://woehead.way-of-elendil.fr/?spell=18744/fel-vitality (Warlock)
- https://woehead.way-of-elendil.fr/?spell=19287/survival-tactics (Hunter)
- https://woehead.way-of-elendil.fr/?spell=33607/wrath-of-cenarius (Druid)

**Comment by jackpoz** [comment]
@sirikfoll do you have any custom change applied ? please post the commit hash when posting a crash log...

**Comment by sirikfoll** [comment]
Already received them without the hash :/
Just know that It kept happening with different versions along the year, and very rare

**Comment by jackpoz** [comment]
Is this still happening ?

**Comment by TheWinchesters** [comment]
In my case, not anymore.
