### ISSUE TITLE
[3.3.5] Build issue on Linux

### ISSUE THREAD

**Issue by funar** [TrinityCore/TrinityCore#22541]
**Description:**
Unable to build on Ubuntu Linux 18.04.1

**Current behaviour:**
"make" returns the following:
`[ 18%] Linking CXX executable authserver
make[2]: *** No rule to make target '../src/server/game/DataStores/DBCEnums.h', needed by 'src/server/game/cotire/game_CXX_prefix.hxx.gch'.  Stop.
CMakeFiles/Makefile2:1279: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 18%] Built target vmap4extractor
[ 19%] Built target mapextractor
make[2]: *** No rule to make target '../src/server/game/DataStores/DBCEnums.h', needed by 'src/server/scripts/cotire/scripts_CXX_prefix.hxx.gch'.  Stop.
CMakeFiles/Makefile2:1467: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2`

**Expected behaviour:**
The code should build? :)

**Steps to reproduce the problem:**
1. Pull current (ab3eab990eb01e6209b8527b98ef169136f81a24) from Git.
2. cmake && make -j10
3. Observe error

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
ab3eab990eb01e6209b8527b98ef169136f81a24

**Operating system:**
Ubuntu 18.04.1 x86_64

**Comment by Aokromes** [comment]
rerun cmake
