### ISSUE TITLE
[3.3.5] Quest: Redemption

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22544]
**Description:**

When you accept https://www.wowhead.com/quest=5742/redemption, you should be able to talk to Tirion Fordring through gossip options, when you accept the quest, no such option appears. The NPC has SmartAI for the menuIDs

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9ec3724

**Operating system:** 

Win 10 x64

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21655#issuecomment-373911560
