### ISSUE TITLE
Crash: /boss_xt002.cpp:754 → caster->GetAI()->SetData(DATA_GRAVITY_BOMB_CASUALTY, 1)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22545]
**Description:**
I am sorry I can not give more useful information about how this happened.

https://gist.github.com/TheWinchesters/bf9447b364a7c70e72b192e0a6708541

Please let me know if I should make better titles for crashes.

Branch: 3.3.5
TC Rev.: 7baf5b2
OS: Debian 9

**Comment by illfated** [comment]
This crash looks a lot more TC source related (assuming your source is clean).
I will still wait for a coder (like WildCoffee) to say anything specific.

**Comment by TheWinchesters** [comment]
@illfated 
Since the other crash I had about "error reading variable", I have started to think if some crashs are just related to particular things like "memory/hardware/etc".
I think that it will be better if I wait till the crash occurs more times and I can find a way to replicate it so other can test it too.

**Comment by Keader** [comment]
1fe8fe30debbd17082b3178fc56795ca02faa6b6

**Comment by P-Kito** [comment]
https://github.com/TrinityCore/TrinityCore/commit/1fe8fe30debbd17082b3178fc56795ca02faa6b6#diff-85c87008bb49d20766555094e5d0996eR734

@Keader there is another case of this GetAI() call.. maybe change them all?

**Comment by Keader** [comment]
Nope.
This case, caster is always xt002.
Issue here is: Caster was player, not xt002

```
ServerToClient: SMSG_SPELL_NON_MELEE_DAMAGE_LOG (0x062E) Length: 44 ConnIdx: 1 Time: 07/20/2015 22:31:25.671 Number: 29000
Me: Full: Player/0 /S0 Map: 0 (Eastern Kingdoms) Low: 
CasterGUID:Full: Player/0 /S0 Map: 0 (Eastern Kingdoms) Low: 
SpellID: Gravity Bomb (63025)
Damage: 0
OverKill: -1
SchoolMask: 32
ShieldBlock: 12033
Resisted: 0
Absorbed: 0
Periodic: False
Flags: OffHand (4)
HasLogData: False
```

**Comment by P-Kito** [comment]
Oh you are right, I didn't see the full code.
I am too rusty nowadays 👍 

Good finding @Keader
