### ISSUE TITLE
Jump Speed Calculations

### ISSUE THREAD

**Issue by xvwyh** [TrinityCore/TrinityCore#22547]
I've been initially meaning to post this with a few unsolved problems, but the comment @jidevlpr left here https://github.com/TrinityCore/TrinityCore/issues/22434#issuecomment-425654375 turned out the be the final missing piece of the puzzle. Knowing now that spline speed limits changed with Cata, I reexamined my research and everything fell into place. And now I'm confident to say that I figured it out completely.

#### The problem

Historically jump speed have always been defined incorrectly on private servers. We use some ephemeral "speedZ", which then gets somehow transformed into height, which then gets transformed into vertical acceleration to be send in a packet. But what do designers/scripters care about when making creatures jump? How high the jump will be. We have an additional pointless step in "speedZ", which makes creating jumps a confusing trial-and-error process.

Besides this, we have long struggled to understand how to use the values provided in spell effects responsible for making units jumps: `SPELL_EFFECT_JUMP` and `SPELL_EFFECT_JUMP_DEST`. And the overcomplication in the form of this "speedZ" prevented us from figuring it out earlier.

Blizzard understood this right from the start, take a look at the parameters they use for their "jump" actions: https://docs.google.com/spreadsheets/d/1Wh1e1ZXYM-sw3wWrY9dGZ2ngK8oa3PA2XIftQJuf5R0/edit#gid=740715654&range=A342:J347

They pass height right away. Min and max height, even. And also a speed multiplier. Can you guess now what MiscValueA, MiscValueB and ValueMultiplier do in spell effects? Yup, min and max jump height (multiplied by 10, so designers have more precision than just "1 yard"), and a speed multiplier.

#### Easy Implementation

Replace the entirety of `Spell::CalculateJumpSpeeds` with:
```cpp
    float runSpeed = m_caster->IsControlledByPlayer() ? playerBaseMoveSpeed[MOVE_RUN] : baseMoveSpeed[MOVE_RUN];
    if (Creature* creature = m_caster->ToCreature())
        runSpeed *= creature->GetCreatureInfo()->speed_run;

    float multiplier = m_spellInfo->Effects[i].ValueMultiplier;
    if (multiplier <= 0.0f)
        multiplier = 1.0f;

#if WOW_VERSION <= WOTLK
    speedXY = std::min(runSpeed * 3.0f * multiplier, std::max(28.0f, m_caster->GetSpeed(MOVE_RUN) * 4.0f));
#else
    speedXY = std::min(runSpeed * 3.0f * multiplier, 50.0f);
#endif

    float duration = dist / speedXY;
    float durationSqr = duration * duration;
    float minHeight = m_spellInfo->Effects[i].MiscValue  ? m_spellInfo->Effects[i].MiscValue  / 10.0f :    0.5f; // Lower bound is blizzlike
    float maxHeight = m_spellInfo->Effects[i].MiscValueB ? m_spellInfo->Effects[i].MiscValueB / 10.0f : 1000.0f; // Upper bound is unknown
    float height;
    if (durationSqr < minHeight * 8 / Movement::gravity)
        height = minHeight;
    else if (durationSqr > maxHeight * 8 / Movement::gravity)
        height = maxHeight;
    else
        height = Movement::gravity * durationSqr / 8;

    speedZ = std::sqrt(2 * Movement::gravity * height);
```

Remove the macro depending on which version of WoW you're servicing. If it happens to be Cata or later, also alter the code from #22434 according to @jidevlpr's comment:
```diff
-args.velocity = std::min(args.velocity, args.flags.catmullrom || args.flags.flying ? 50.0f : std::max(28.0f, unit->GetSpeed(MOVE_RUN) * 4.0f));
+args.velocity = std::min(args.velocity, args.flags.catmullrom || args.flags.flying || args.flags.falling || args.flags.parabolic ? 50.0f : std::max(28.0f, unit->GetSpeed(MOVE_RUN) * 4.0f));
```
Or, I dunno, add a helper method to `MoveSplineFlags` that will check these flags for you, so the code looks less like a mess.

You may have some of the following questions:

- **Why is the speed additionally multiplied by 3?**
That's the base jump speed Blizzard uses. Any jump with no additional parameters set would have a speed equal to 3 times the base run speed. Jump speed multiplier just modifies the already multiplied speed, so if you want jump speed to be equal to run speed, you would have to specify the speed multiplier of 0.333, repeating of course. A multiplier of 1 (or 0, in which case the default "1" is used) means "3 times the run speed".
Although, since they still use a field I called "MoveSpeed" in the spreadsheet linked above, it may be possible that they can switch whether they want to use walk or run speed.

- **What's the deal with runSpeed getting multiplied by creature template's run_speed, why not GetSpeed(MOVE_RUN)?**
We NEED to use just the base creature's run speed, unaffected by speed modifiers. You can confirm this for yourself by examining Lich King kill sniffs. At 10% phase Tirion (base speed 8) gets buffed with a +100% speed aura 71773 (now his speed is 16), and yet his jump speed is 14.4. Tirion jumps with a spell 71809, which has ValueMultiplier = 0.60. If we were to assume that the current run speed is used, not the base speed, then his jump speed should've been 16 * 3 * 0.60 = 28.8. But it's half of that. If we take the base speed, then everything matches: 8 * 3 * 0.60 = 14.4.
This may require special handling for pets, I dunno how they're implemented in TC at this time, but I just keep their speed normalized to 8 yards/sec and start splines with custom velocity if I want them to follow their owner faster or slower. I doubt pets should keep the speed of their original creatures, so you would want to replace
`runSpeed *= creature->GetCreatureInfo()->speed_run;`
with something like
`runSpeed *= creature->isPet() || creature->IsEnslaved() ? 8.0f / 7.0f : creature->GetCreatureInfo()->speed_run;`

- **What's the deal with all these checks against gravity?**
Jump height is chosen in such a way that vertical acceleration (the float value sent in MONSTER_MOVE packets) stays equal to gravity (19.2911). The amount of vertical acceleration, in turn, depends on how long the path is time-wise. The shorter the path - the more acceleration has to be applied to match the required height in the short time window. When both min and max height are provided - the resulting height will be chosen between min and max depending on how long it takes to travel the path. If it IS possible to pick a height in-between min and max, then vertical velocity will stay equal to gravity. But if the path is too short - more acceleration needs to be applied to even reach the minimum desired height, so minimum height is chosen and acceleration ends up being higher than gravity. If, on the other hand, the path is too long - less acceleration is needed to reach the highest desired height, so maximum height is chosen and acceleration ends up being lower than gravity.
If min height is not specified - a default of 0.5 yards is chosen, this was confirmed to be Blizzlike from multiple sniffs.
If max height is not specified - height will be increasing the further away you are from your destination, with acceleration remaining equal to gravity. Having some kind of a cap is still a good idea, lest you want your players to be launched to infinity and beyond, so I chose 1000 yards, but I imagine a lower number would be more reasonable, say, a 100.

- **What about SpellInfo::Speed? Shouldn't jump speed by synchronized with that?**
As far as I can tell: no. Blizzard manually set the missile speed for such spells to be close to what the jump speed will be after all the multiplications, although not too close. Go look at https://youtu.be/jcf1dKDIung?t=247 (4:07). You'll see that the visual effect from the ground impact happens sooner than the Mistress finishes her jump. And the spell's speed is indeed faster than jump speed ends up being, completely mimicing the inaccuracy seen in the video.

#### Proper Implementation

1. Get rid of `speedZ` everywhere. Change `MotionMaster::MoveJump` to instead accept something like `Range<float> height` or simply `std::pair<float, float> height` for specifying jump height instead of `speedZ`, and just pass `{ MiscValueA / 10.0f, MiscValueB / 10.0f }` there, getting rid of pretty much the entire `Spell::CalculateJumpSpeeds`. Bonus points if you also remove `speedXY` as well and instead just pass `ValueMultiplier`, getting rid of `Spell::CalculateJumpSpeeds` entirely. Then, inside `MotionMaster::MoveJump` you can choose the jump speed based on unit's base run speed and provided multiplier like in the code above, as well as the jump height, choosing between provided min and max values, skipping `speedZ` calculation bit entirely.
2. Edit core scripts to provide explicit heights instead of speedZ (and speed multiplier instead of raw speedXY, if you're brave enough).
3. Edit SAI scripts to provide explicit heights*10 instead of speedZ (and speed multiplier instead of raw speedXY, if you're still brave enough, although good luck doing that with INT columns. Perhaps *100 is a good idea? Make it behave like percentages instead of floating point multipliers).

#### Additional research could be nice

- Do players also use just their base run speed of 7, or is it affected by aura modifiers? The problem here is that all class spells that make players jump already have such high multipliers (3 or 4) that players hit the spline speed cap, and thus the speed gets clamped. We need to examine sniffs where a player is slowed down significantly and uses a jump spell. And we need to do this on post-cata sniffs, where jump spline speed cap is hardcoded to be 50, in WotLK and prior the cap is adjusted based on player's current (slowed down) speed, so it's likely they will still be hitting the cap. On the other hand, if a player can be slowed down so much, that their run_speed * 3 * 4 will still be below 28 yards/sec, then even WotLK sniffs will do.
- BasePoints still remains without a use. It's unclear if it even has any use. The whatever non-zero values there are might just be remnants of some other effects the spells had before they were replaced with jumps (a knockback, for example).

Hi, bot: 4ce6d6b9f643253092812fe6c6f172a41a6c51a7

P.S. Why do `playerBaseMoveSpeed` and `baseMoveSpeed` even exist? They have exactly the same values...

**Comment by Shauren** [comment]
Very good

ref P.S. - player speed multiplier from worldserver.conf

**Comment by Seyden** [comment]
Some information i gathered over the time while dealing with such jump effects:

SPELL_EFFECT_254 as example:
This spell effect is using a spellEffectExtraData progressCurveId which is modifying the visual of the jump and probably something else too.

The thing i found out about these jumps is, the time the jump needs always depends on the max distance the jump can do. Which means, if you got a talent which modifies the max distance of a jump, the time increases too. If you jump to a different Z position, the time here is increased a lot, due to height differences.

But what didn't matter was, if you only jump 1 yard in front of you, or 40 yards, it always took like 851 ms for a certain spell.

And ofc if you jumped 40 yards, the height of the jump wasn't that big, but if you only jumped 1 yard, the height of the jump was way bigger.

A video i did:

https://www.youtube.com/watch?v=Ciy4WTUqbUs

**Comment by xvwyh** [comment]
0197a2f990aa7c7eaf8637a2a5da7f43def9c4bd
