### ISSUE TITLE
Issue with 4 dbc files after commit 4990423dbfdda716078f7fa9e31b455541426b82

### ISSUE THREAD

**Issue by alexmocanu** [TrinityCore/TrinityCore#22540]
**Description:**

After compiling the 3.3.5 branch (cloned at commit 4990423dbfdda716078f7fa9e31b455541426b82) several dbc files are no longer compatible. 

I extracted a fresh set of dbc's and maps using the extractors compiled at the same time with TC but I got the same error. 

**Current behaviour:**

When starting the worldserver I get this error:
```
Some required *.dbc files (4 from 112) not found or not compatible:
../data/dbc/AchievementCriteria.dbc
../data/dbc/PvPDifficulty.dbc
../data/dbc/RandomPropertiesPoints.dbc
../data/dbc/SpellShapeshift.dbc
```

**Expected behaviour:**
The world server should just start up and not throw this error?

**Steps to reproduce the problem:**
I'm using a Debian 9 machine
1. Clone the repository (latest commit when I tested was 990423dbfdda716078f7fa9e31b455541426b82)
2. Follow the steps on the wiki to setup the server, database, etc. 
3. Try to start the worldserver

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
990423dbfdda716078f7fa9e31b455541426b82

**Operating system:** Debian 9

**Comment by alexmocanu** [comment]
I think there might be a issue with the dbc&maps extractor itself. I guess it hasn't been updated to take into account the new file names. 

After manually renaming the 4 dbc files like this everything worked:
```
Achievement_Criteria.dbc => AchievementCriteria.dbc
PvpDifficulty.dbc => PvPDifficulty.dbc
RandPropPoints.dbc => RandomPropertiesPoints.dbc
SpellShapeshiftForm.dbc => SpellShapeshift.dbc
```

**Comment by Aokromes** [comment]
ab3eab9
