### ISSUE TITLE
DB/Quest: The Iron Colossus (ID:13007) , Tamed Jormungar has no abilities.

### ISSUE THREAD

**Issue by nagrandbugtracker** [TrinityCore/TrinityCore#22550]
**Description:**

Tamed Jormungar has no abilities, so quest is impossible to complete.

**Current behaviour:**

Doesn't have any special abilities or spells.

**Expected behaviour:**

Tamed Jormungar should have these abilities:
https://www.wowhead.com/spell=56524/acid-breath
https://www.wowhead.com/spell=56508/emerge
https://www.wowhead.com/spell=56504/submerge
https://www.wowhead.com/spell=56513/jormungar-strike

**Steps to reproduce the problem:**

1. .q add 13007
2. .tele stormpeaks, goto 27,36
3. try to control the tamed jormungar with control orb.
4. You'll see it has no abilities.
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. d24b461+

**Operating system:** Unix, Debian 9 x64

**Comment by Aokromes** [comment]
#4974
