### ISSUE TITLE
Wrong Z coord in Howling Fjord

### ISSUE THREAD

**Issue by Harrith** [TrinityCore/TrinityCore#22562]
**Description:**

There is a place in Howling Fjord near creature id 23906 where Z coord is wrong.

**Current behaviour:**

Player's Z coord is 204.904 and even creature's Z coord is same, but ground and floor Z coord is 198.65. So in result when player attacks the creature and creature moves or when creature evades it goes under the texture.

**Expected behaviour:**

Creature should not move under the texture and Z coord and floor/ground Z coord should be the same.

**Steps to reproduce the problem:**

1. .go c id 23906
2. .gps

**Branch(es):**

4.3.4, but most likely master and 3.3.5 too

**TC rev. hash/commit:** 

fbd781a4a345

**Operating system:** Win10

**Comment by Killyana** [comment]
I don"t have GroundZ= FloorZ and I cannot reproduce the issue

X: 795.208984 Y: -4086.389893 Z: 204.904007 Orientation: 5.235990
GroundZ: 198.649750 FloorZ: 204.880722 Have height data (Map: 1 VMap: 1 MMap: 1)

**Comment by Harrith** [comment]
Could you tell me, please, which 4.3.4 branch did you use? I have tried Ovahlord's 4.3.4 branch and there it is not working.

**Comment by Killyana** [comment]
https://gitlab.com/trinitycore/TrinityCore_434/
But I think it's the same mmap/vmaps

**Comment by Harrith** [comment]
Unfortunately there are not the same maps :( In Ovahlord's core there are maps version 1.7 but in this 4.3.4 branch there are maps version 1.6.

**Comment by Harrith** [comment]
Ok, I have found out that f1c54a4529a0909809f94b449a765cf3a63df1fb broke it.
