### ISSUE TITLE
Quest/script: Troll Patrol: The Alchemist's Apprentice

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22563]
**Description:**  When  you put all required items in the cauldron, the quest is not completed and the aura id: 51216 [Alchemist's Apprentice Invisbuff]  is not removed from the character.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_zuldrak.cpp#L829-L832

https://woehead.way-of-elendil.fr/?quest=12541

**Steps to reproduce the problem:**

1. .go c id 28205
2. .quest add 12596 (quest requirement)
3. take the quest "Troll Patrol: The Alchemist's Apprentice" from the npc and talk to him to start the quest
4. Put all required items in the Caldron and notice at the end the quest is not completed and your char will keep the aura 51216 

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. ab3eab990eb0

**Comment by WildCoffee** [comment]
This bug is actually for the daily [Troll Patrol: The Alchemists Apprentice](https://woehead.way-of-elendil.fr/?quest=12541).

The other problem I've noticed is that it triggers combat when I start the quest. The aura isn't being removed if you fail either, which is preventing you from retaking the quest.

**Comment by Killyana** [comment]
The issue is for both quests as the script is the same

**Comment by Killyana** [comment]
Yes you're right

**Comment by Killyana** [comment]
And the quest works correctly

**Comment by WildCoffee** [comment]
It's actually broken for me, maybe there is something wrong with my character. Also, Lab Work doesn't seem to be implemented at all.

**Comment by Killyana** [comment]
I just tested this quest, the only issue is the quest giver start a combat with the player when the event starts, probably because he cast this spell: DoCast(player, SPELL_ALCHEMIST_APPRENTICE_INVISBUFF);

**Comment by WildCoffee** [comment]
When you complete or fail the quest, is that aura removed/combat ended? That is aura 51216. I'm still getting the same results as your initial report. That aura is applied and isn't removed which leaves you in combat and unable to logout.

**Comment by Killyana** [comment]
No the combat is an issue, it musn't happen.

**Comment by illfated** [comment]
So... maybe re-open this issue ticket as the problem still exists?
Or does it need a different issue ticket for the combat problem?

**Comment by Killyana** [comment]
It's a different issue.
