### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#22564]
**Description:**

Build Fails

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

When compile the build should succeed.

**Steps to reproduce the problem:**

1. Use cmake to create the build files  :
cmake ../ -GXcode \
-DMYSQL_ADD_INCLUDE_PATH=/usr/local/include \
-DMYSQL_LIBRARY=/usr/local/lib/libmysqlclient_r.dylib \
-DREADLINE_INCLUDE_DIR=/usr/local/opt/readline/include \
-DREADLINE_LIBRARY=/usr/local/opt/readline/lib/libreadline.dylib \
-DBOOST_INCLUDEDIR=/usr/local/include \
-DBOOST_LIBRARYDIR=/usr/local/lib \
-DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include \
-DOPENSSL_SSL_LIBRARIES=/usr/local/opt/openssl/lib/libssl.dylib \
-DOPENSSL_CRYPTO_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.dylib \
-DZMQ_LIBRARY=/usr/local/opt/zeromq/lib/libzmq.dylib \
-DZMQ_INCLUDE_DIR=/usr/local/opt/zeromq/include \
-DZLIB_ROOT=/usr/local/Cellar/zlib/1.2.8 \
-DCMAKE_INSTALL_PREFIX=/Users/USERNAME/trinity \
-DTOOLS=0 \
-DWITH_WARNINGS=0

2. Create the bin files
xcodebuild -target install -config Release

3. Get Build Failed Message:
The following build commands failed:
	ProcessPCH++ /Users/USERNAME/trinity/trinitycore/build/src/common/SharedPrecompiledHeaders/SharedPrecompiledHeaders/5665311458217885209/common_CXX_prefix.hxx.gch /Users/USERNAME/trinity/trinitycore/build/src/common/Release/cotire/common_CXX_prefix.hxx normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Branch(es):**
 3.3.5

**TC rev. hash/commit:** 

1daf318cbb8c13d46fb1e207ac54b7f54eafebf3

**Operating system:** Mac OS X Build 10.13.6

**Comment by jackpoz** [comment]
is there any other detail about why it failed ? syntax error, missing dependency, anything ?

**Comment by obsidean** [comment]
Unfortunately not.  Nothing showed up.  I have been looking at that for the past hour.  I hate Mac OSX...

**Comment by obsidean** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19950

**Comment by obsidean** [comment]
I upgraded the dependencies to the latest version, then ran the cmake as above and now the project file isn't even being generated.  What versions of the dependencies are required for this to work?(mysql, openssl, readline, cmake, boost, and zlib)?

**Comment by Aokromes** [comment]
if you use mysql higher than 5.7 it won't work.

**Comment by obsidean** [comment]
thanks, I am aware.  Still having the same issue.

**Comment by jackpoz** [comment]
what error does cmake show when failing to generate the project files ?

**Comment by obsidean** [comment]
I see that there are a couple of fixes that were implemented.  Unfortunately I am still getting an error that boost library couldn't be found.  The version I have is 1.67.0_1:

CMake Error at cmake/macros/FindBoost.cmake:1231 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.57.0

  Boost include path: /opt/local/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
Call Stack (most recent call first):
  dep/boost/CMakeLists.txt:44 (find_package)

**Comment by obsidean** [comment]
Found the problem:
(i) Upgrade dependencies, except MySQL
(ii) Link boost
(iii) Everything should work from there.

I am going to close the issue.
