### ISSUE TITLE
Rescuing Evanor (ID : 16681) Crashes the server right after accepting the quest.

### ISSUE THREAD

**Issue by nagrandbugtracker** [TrinityCore/TrinityCore#22561]
**Description:**

Upon accepting quest, server crashes immediately.

**Current behaviour:**

Upon accepting quest, server crashes immediately.

**Expected behaviour:**

It definitely should not crash server.

**Steps to reproduce the problem:**

1. .tele borean
2. .q add 11680
3. finish the quest (don't use GM commands, go to questender).
4. accept quest 11681(don't do .q add 11681, go old fashioned style to NPC)
5. should crash instantly upon receiving quest.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3ca43dbf542c 

**Operating system:** Unix, Debian 9 x64

**Comment by Hir0shi** [comment]
Crash log?

**Comment by nagrandbugtracker** [comment]
> Crash log?

<%Treeston> alternately, just report the quest id if it's easy to reproduce
<%Treeston> reliable repro is far better than any crash log

In meantime, still working on crash log.

**Comment by Treeston** [comment]
dup #22444
