### ISSUE TITLE
{Quest} The Hunter and the Prince Part II

### ISSUE THREAD

**Issue by AByakugans** [TrinityCore/TrinityCore#22577]
**Description:**

http://old.wowhead.com/spell=60617 -- Parry is Bugged.

**Current behaviour:**

The mana gain when you parry is bugged its gives you 0 mana

**Expected behaviour:**

The mana gain when you parry should be huge to continue ok in quest.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2033159030274401baf8d8745b3d40b6d49f9a5b

**Operating system:** Linux

Old issue here with additional info: https://github.com/TrinityCore/TrinityCore/issues/4854

**Comment by illfated** [comment]
More info related to https://www.wowhead.com/spell=60617/parry
- https://woehead.way-of-elendil.fr/?spell=60617
- https://wow.gamepedia.com/Parry#Chance_to_parry
- http://wowwiki.wikia.com/wiki/Parry

**Comment by Rushor** [comment]
@Killyana 

```sql
DELETE FROM `spell_proc` WHERE `SpellId` = 60617;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES 
(60617, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0);
```
