### ISSUE TITLE
[3.3.5] [Quest: 13216] Battle at Valhalas: The Return of Sigrid Iceborn Part II

### ISSUE THREAD

**Issue by AByakugans** [TrinityCore/TrinityCore#22578]
**Description:**

When you accept the quest, the required Sigrid Iceborn spawn but immediatelly leaving combat and cannot attack it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2033159030274401baf8d8745b3d40b6d49f9a5b

**Operating system:** Linux

Old issue here with additional info: https://github.com/TrinityCore/TrinityCore/issues/14287

**Comment by illfated** [comment]
Nice. Thanks.
