### ISSUE TITLE
LocalDefense Spawned Guards - Not Working

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#22575]
**Description:**

So each city and town has a unique guard that will spawn in a specific area in that city or town and it can only be triggered by a player of the opposing faction attacking a NPC, getting too close to an NPC making it call out for help or even walking into the enemy territory.

**Current behaviour:**

They do not work, I think we could sniff the data for these guys, I know they exist because there are some that have been (probably accidentally) sniffed and are set as a permanent NPC (See this: https://imgur.com/a/m5HQnBH)

**Expected behaviour:**

They should only spawn when a player of the opposing faction attack an NPC, walk into the enemy territory or getting too close to an NPC which often makes it call out for help.

If the guard(s) reset back to their spawn location, they should walk around on the spot and despawn after 3 minutes of non-combat activity.

**Steps to reproduce the problem:**

1. Go to any city or camp of the opposing faction or town or even a camp!
2. Attack an NPC, walk into the territory or go close to an NPC.
3. See http://wowwiki.wikia.com/wiki/Guard

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. 609c1acc09c7 2018-09-22 08:48:04 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**

Windows 7

**Comment by LewisPotato** [comment]
I really think this should get fixed, maybe we could make invisible bunnys that spawn the guard using a unique spell like "Summon - Stormwind City Guard" or something.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/11563

**Comment by LewisPotato** [comment]
Why close it? This is probably the only one where it is explained very well.. Whatever floats your boat. lmao

**Comment by funjoker** [comment]
Ever heard about "reference". This Issue is referenced now in #11563
