### ISSUE TITLE
[BUG] WORLDSERVER TiME START!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22585]
errosr:

World initialized in 0 minutes 20 seconds
StartNetwork failed to bind socket acceptor
Failed to initialize network

-
how to fixed
should wait 3 or 4 minute for start again worldserver and authserver!

Branch: 3.3.5
TC Rev:  https://github.com/TrinityCore/TrinityCore/commit/ce46a0d53c3dbd6d2837020686e3880d98c545ed

OS: WindoWs

**Comment by Aokromes** [comment]
duplicate.

**Comment by Hir0shi** [comment]
@Aokromes 

Oh No please :(

**Comment by TheWinchesters** [comment]
Are you using a restarter?
