### ISSUE TITLE
Wrong liquid status in Borean Tundra

### ISSUE THREAD

**Issue by Harrith** [TrinityCore/TrinityCore#22588]
**Description:**

There is a place in Coldarra where player has breath timer but he is not in the water. I am so sorry but I don't have neither Legion client nor maps, vmaps,... , so I can't test it in the master branch.

May I also ask you for testing https://github.com/TrinityCore/TrinityCore/issues/22562 in the master branch? It is really possible that it happens there too, thank you.

**Current behaviour:**

Player has breath timer.

**Expected behaviour:**

Player should not have breath timer.

**Steps to reproduce the problem:**

1. .go xyz 3289.781 6604.514 -2.32 571

**Branch(es):**

4.3.4 but most likely master too

**TC rev. hash/commit:** fbd781a4a345

**Operating system:** Win10

**Comment by Treeston** [comment]
confirm on 335

**Comment by Killyana** [comment]
Similar issue https://github.com/TrinityCore/TrinityCore/issues/20221

**Comment by Pharonax** [comment]
Confirmed rev da30a1c

**Comment by Aokromes** [comment]
test again on head

**Comment by Shauren** [comment]
Not fixed  but duplicate of #20221 (affects both branches)
