### ISSUE TITLE
[3.3.5] Old Ironbark event does not exist.

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22594]
**Description:**

After killing https://www.wowhead.com/npc=11490/zevrim-thornhoof, you can speak to https://www.wowhead.com/npc=14241/ironbark-the-redeemed, which was previously https://www.wowhead.com/npc=11491/old-ironbark (before killing Zevrim),  and then he smashes the door leading to Alzzin the Wildshaper. As it stands, this event does not exist and there is no door blocking your way, you can avoid Zevrim Thornhoof and go straight to Alzzin.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9ec3724

**Operating system:**

Win 10 x64

**Comment by Killyana** [comment]
Please check the existing issues before opening a new one https://github.com/TrinityCore/TrinityCore/issues/14791
