### ISSUE TITLE
[BUG] ChatFlood!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22591]
anti chatflood system: not worked, tested in game by macro spam chats !
example:
/macro = > /say hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world

Spam Chat sends time in 2sec!

###############
worldserver.cfg

ChatFlood.MessageCount = 5
ChatFlood.MessageDelay = 1
ChatFlood.MuteTime = 10

################

Trinitycore 3.3.5
TC Rev: https://github.com/TrinityCore/TrinityCore/commit/7baf5b24525551ddf00c88084edb2a1bafeb758d

Os: Windows Server

**Comment by Hir0shi** [comment]
hi, tested by player account!

**Comment by Treeston** [comment]
cannot reproduce on latest 3.3.5

**Comment by Hir0shi** [comment]
@Treeston

i update to last version!

what is it your cfg!
