### ISSUE TITLE
[3.3.5] The Matron Protectare/Rune of Mazthoril

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22597]
**Description:**

Quest https://www.wowhead.com/quest=5160/the-matron-protectorate cannot be completed because the Rune of Mazthoril does not teleport the player to Haleh.

**Branch(es)** 

3.3.5

**TC rev. hash/commit:** 

9ec3724

**Operating system:** 

Win 10 x64

**Comment by Killyana** [comment]
Related to traps not being triggered.

**Comment by ZenoX92** [comment]
The trap is working, but it's not in the same position than the rune circle.
```sql
-- Rune of Mazthoril LT
UPDATE `gameobject` SET `position_x`=5893.48, `position_y`=-4054.75, `position_z`=596.385 WHERE `guid`=49001;

**Comment by Killyana** [comment]
I was trying to find why the other teleport work and not this one.

**Comment by illfated** [comment]
Interesting. Maybe a position problem for the exit teleport too?

**Comment by ZenoX92** [comment]
Well, the exit teleport is not in the exact position where it should be, but since it's working just fine, maybe it's better to keep it that way.
