### ISSUE TITLE
[3.3.5] Immol'thar prison does not disappear after clearing the five pylons

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#22593]
**Description:**

When you clear the mobs surronding the five pylons in dire maul west, each pillar should lose their glow, when the five pillars are cleared of trash mobs, immolthar's prison should disappear, and you should be able to fight with him.

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

9ec3724

**Operating system:** 

Win 10 x64

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/14685
