### ISSUE TITLE
Core/Quest: Quests related to professions/specializations must be removed if the profession/specialization is forgetten

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#226]
Core revision: Trinity Core 10868 Operating System: Win32, little-endian
using TDB UP36 (doesn't really matter, it's a core issue)

When you get a profession specialization (ie. armorsmith as blacksmith spec) and you try to change to another profession specialization (weaponsmith) by either unlearning it and learning in the normal, blizzlike way or using .cast (spell to unlearn that specialization) after relogging, you have both profession specializations (ie. armorsmith and weaponsmith).
##

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16188 partially fixed the issues reported here

**Comment by ariel-** [comment]
Can this be closed now?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16188#issuecomment-169076168

**Comment by msoky** [comment]
this is still valid? I met a lot of players witch is using this bug and have more than 2 professions...cmon, this is almost 7 years old report

**Comment by jackpoz** [comment]
> cmon, this is almost 7 years old report

glad to see you volunteered to fix it, please submit a Pull Request once you have the fix

**Comment by msoky** [comment]
sorry, no, I dont have fix, I want only point on this and avoid not to forget this old reports. I think this is big bug and used by players very often

**Comment by Aokromes** [comment]
Specializations != professions, also not big bug at all.

**Comment by Shauren** [comment]
Issue tracker is not a forum where you can bump posts. Most of the time posting useless comments like that have the exact opposite effect and issue will keep being unfixed

**Comment by DoctorKraft** [comment]
take a look at CMSG_UNLEARN_SPECIALIZATION

**Comment by Killyana** [comment]
Remaining issue: quests that requires a skill  like https://woehead.way-of-elendil.fr/?quest=10902 must be removed from the journal when the player Unlearn the profession, or maybe just don't allow the quest to be rewarded. The correct behavior must be checked on retail.
