### ISSUE TITLE
Error applying SQL update

### ISSUE THREAD

**Issue by rockz1152** [TrinityCore/TrinityCore#22615]
**Description:**

SQL error while applying updates when starting worldserver

**Current behaviour:**

```
>>Applying update "2018_10_09_02_world_335.sql" '8CF69D6'...
ERROR 1366 (HY000) at line 20: Incorrect string value: '\xD0\xAF \xD0\xB6\xD0...' for column 'RewardText' at row 43226
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c56bac777a60 2018-10-10 19:00:49 +0200 (3.3.5 branch) (Unix, Release, Static)

**Operating system:** Fedora 28

**Comment by Aokromes** [comment]
wiki states:

You will need MySQL Strict Mode to be disabled (specially if you use mysql 5.7).
