### ISSUE TITLE
Core: Game Events and pooling

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22610]
**Description:** If a creature has multiple pooled spawns and this spawns are into a game event, when the game event starts all spawns on the pool will appears.

If you kill this spawns only one will respawn, it's like the spawn mechanism of the event is overriding the pooling.

**Steps to reproduce the problem:**

1. .event start 25 (night)
2. .go c 28458
3. .go c 86825
4. .go c 86826
5. Notice the npc Leprithus is spawned in the three spots even if he's into a pool.
https://github.com/TrinityCore/TrinityCore/commit/29cf1af4339dcba94b1e1eed094487f637d804dd#diff-d97d47f0aecd28396772b11542a4989dR2

**Branch(es):** Both

**TC rev. hash/commit:**  rev. 7c003c568cdd

**Comment by r00ty-tc** [comment]
Can you try:

```SQL
DELETE FROM game_event_creature
WHERE eventEntry = 25
AND guid in (28458, 86825, 86826);

INSERT INTO game_event_pool
(eventEntry, pool_entry)
VALUES
(25, 1004);
```

This isn't a bug as such, but event has it's own table and code to handle spawning a pool.

**Comment by Killyana** [comment]
Works fine thanks
