### ISSUE TITLE
[Class Paladin] PowerFull Or Buged!?

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22627]
They report that the paladin class is very strong! 
I checked I saw right

tested by pro players, paladin class winer of
warrior, priest shadow, dk unholy, rouge, hunter, durid, shaman

<b>What i saw: </b>

example class paladin: items
full relentless ,can
killed warrior full item wrathful !

example class paladin: spells
<b> iknow 100% buged spell [The Art of War] fast to used By Cast Level Spells .</b>
I am not sure for -> & [Sacred Shield] & Critical hits or ...

I do not know how to explain ! ( !
please
If anyone can recheck!!
Very important and complicated

<b>pvp realm:</b>

Branch(es): Both
TC 3.3.5 rev. hash/commit: rev. https://github.com/TrinityCore/TrinityCore/commit/d24b46139600c74f5e200d9ab1592d7128245113
os: windows server

**Comment by Killyana** [comment]
This is not a forum, you must use the template provided to open an issue.
