### ISSUE TITLE
[BUG SPELL]  The Art of War | 100% Chance To Use!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22628]
Ok, I studied the problem of Paladin's great power!

Spell [The Art of War] is Buged By 100% Chance!

Use by attack mele Weapon , Use by spells =>  [Crusader Strike] &  [Judgement of Light] &  [Divine Storm]
You just get one of these spells Or Normal mele Attack By Weapon => Activated [The Art of War] !

<b>and this has caused the paladin bug class</b>

please don't close issue, If you think I'm wrong, please check!

Branch(es): Both
TC 3.3.5 rev. hash/commit: rev. d24b461
os: windows server

**Comment by Keader** [comment]
Yeah, just remove template, no one use it anyway ! 😢

**Comment by Hir0shi** [comment]
see on image! this spell is buged chance to use!

https://cdn1.imggmi.com/uploads/2018/10/11/cc448d04ced13fbcab96e7d239b79ecf-full.png

**Comment by Keader** [comment]
what you saying is: Art of War has proc chance = 100%?

**Comment by Hir0shi** [comment]
this spell Art of War Activated  by attack Mele Weapon Or Use By spells!

Free  Chance 100% !

**Comment by Hir0shi** [comment]
i will to remove all items and tested !

https://cdn1.imggmi.com/uploads/2018/10/11/fd732f63cd04fdc33fa68c7067396168-full.png

**Comment by Keader** [comment]
Ok @Hir0shi can you check something for me?
Run in your world DB:

``` sql
SELECT HitMask FROM spell_proc where SpellId=-53486;
```

Tell me the result.

**Comment by Hir0shi** [comment]
Ok. i will tested

**Comment by Keader** [comment]
Ok, tested in TC and is working fine. So it's not TC issue Hiroshi, is in your server.
My guess is: Has wrong HitMask, someone fucks it.
My suggestion to fix it is:

```sql
UPDATE `spell_proc` SET `HitMask`=2 WHERE `SpellId`=-53486;
```

Good Luck.
