### ISSUE TITLE
DB/Creature: Fallen Hero of the Horde

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22634]
**Description:**

* Fix conditions for gossip option 2 (the one that allows you to summon Corporal Thund Splithoof)
   * Prevent Corporal Thund Splithoof from being summoned multiple times
   * Corporal Thund Splithoof should be "summonable" until quest "Heroes of Old (Part 2)" is rewarded
* Fallen Hero of the Horde shoud cast "Call of Thund"  when quest "Heroes of Old (Part 1)" is taken
* Fallen Hero of the Horde should say some text when Corporal Thund Splithoof is summoned

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a10870571558 2018-09-03 22:06:51 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Fallen Hero of the Horde
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=840 AND `SourceEntry`=2;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(15,840,2,0,0,14,0,2702,0,0,1,0,0,"","Show gossip option if quest 'Heroes of Old (Part 1)' is taken, completed or rewarded"),
(15,840,2,0,0,8,0,2701,0,0,1,0,0,"","Show gossip option if quest 'Heroes of Old (Part 2)' is not rewarded"),
(15,840,2,0,0,29,1,7750,200,0,1,0,0,"","Show gossip option if Corporal Thund Splithoof is not already summoned");

DELETE FROM `smart_scripts` WHERE `entryorguid`=7572 AND `source_type`=0 AND `id` IN (5,6);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7572,0,5,0,62,0,100,0,840,2,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Fallen Hero of the Horde - On Gossip Option 2 Selected - Say Line 0"),
(7572,0,6,0,19,0,100,0,2702,0,0,0,11,11024,0,0,0,0,0,1,0,0,0,0,0,0,0,"Fallen Hero of the Horde - On Quest 'Heroes of Old (Part 1)' Taken - Cast 'Call of Thund'");

DELETE FROM `creature_text` WHERE `CreatureID`=7572;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(7572,0,0,"Per your request, Corporal Splithoof has come, $n.",12,0,100,0,0,0,3764,0,"Fallen Hero of the Horde");

**Comment by illfated** [comment]
Finally. A proper end to this quest line. I can still remember the emotions it gave me when I completed it on retail in 2009-2010.

**Comment by illfated** [comment]
Funny side note:
The spell name "Call of Thund" (https://woehead.way-of-elendil.fr/?spell=11024) sounds a bit like a shaman quest line.
Also, when I try to google the name, I get a lot of `knockback()` references from other RPG sites.... 😄

**Comment by illfated** [comment]
The quest chain itself was pretty much straight forward, unfortunately I don't remember any special details about the NPCs or their actions. I mostly reacted to the text content. Note that I was doing the quests as part of a personal effort to gain the Loremaster achievement (WotLK) and was already at level 80, so I did not have much challenge in completing them (except a few elite NPCs I met on my way). But what was nice about the chain was the way it told some of the lore in the past of the Blasted Lands and before the Dark Portal, leaving you with a feeling that you would have liked to see absolutely all the vanilla WoW content and build on that when going through the TBC and WotLK content.
