### ISSUE TITLE
Core: creature loot nothing in battleground

### ISSUE THREAD

**Issue by micckkk** [TrinityCore/TrinityCore#22631]
Description: battlegroundAV all npc not loot

Branch(es):

3.3.5

TC rev. hash/commit:

https://github.com/TrinityCore/TrinityCore/commit/fd73543d91e3c660746b0abdd20461f4bdbaf700

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3515

**Comment by micckkk** [comment]
thank's Killyana
