### ISSUE TITLE
DB/Quest: Heroes of Old (Part 2)

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22635]
**Description:**

* Fix quest ender for quest "Heroes of Old (Part 2)"
(it should end with gameobject "Spectral Lockbox", not with NPC Corporal Thund Splithoof)
https://wow.gamepedia.com/Heroes_of_Old_(2)
* Set a despawn timer for Corporal Thund Splithoof

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a10870571558 2018-09-03 22:06:51 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
DELETE FROM `creature_questender` WHERE `quest`=2701;
DELETE FROM `gameobject_questender` WHERE `quest`=2701;
INSERT INTO `gameobject_questender` (`id`, `quest`) VALUES
(141980,2701);

DELETE FROM `smart_scripts` WHERE `entryorguid`=7750 AND `source_type`=0 AND `id`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7750,0,0,0,54,0,100,0,0,0,0,0,41,60000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Corporal Thund Splithoof - Just Summoned - Despawn in 60 seconds");

**Comment by illfated** [comment]
Thank you. I have been looking forward to this way of doing it for 4 years.
