### ISSUE TITLE
DB/Gossip: Franclorn Forgewright

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22636]
**Description:**

The last part of Franclorn Forgewright's dialogue is missing.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a10870571558 2018-09-03 22:06:51 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Franclorn Forgewright
DELETE FROM `gossip_menu` WHERE `MenuID`=1667;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`, `VerifiedBuild`) VALUES
(1667,2319,0);

DELETE FROM `gossip_menu_option` WHERE `MenuID`=1666;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(1666,0,0,"Just show me the way, Franclorn.",4654,1,1,1667,0,0,0,"",0,0);

DELETE FROM `npc_text` WHERE `ID`=2319;
INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`) VALUES
(2319,"You will find Fineous Darkvire beyond the Ring of Law, in the Hall of Crafting. Kill the miserable cur and recover Ironfel.$B$BTake Ironfel to the Shrine of Thaurissan and place the hammer in its rightful place: In the hands of the statue erected in my honor.$B$BWhen this is done, the compartment in which I stored the master key will open. More importantly, Ironfel will remain forever in my grasp. Should they make an attempt to remove the hammer; both the statue and hammer will shatter, lost forever.","",4655,0,1,0,0,0,0,0,0);

**Comment by offl** [comment]
Just of curious: is this text and gossip menu mentioned somewhere(wiki, wowhead)?
Because I did not found it in wiki or wowhead and it is not shown in https://youtu.be/b-hJX-a3GLw?t=84
Some of the broadcast_text's texts were never used even if they are related to some implemented events

**Comment by illfated** [comment]
Interesting point, I didn't think of that before now.
Could this be connected to the fact that the quests  got removed in patch 4.0.3a (Cataclysm) and that a lot of TDB 335 content comes from Mists of Pandaria Patch 5.4.7, build 18019?
https://www.wowhead.com/npc=8888/franclorn-forgewright#comments:id=1815063
- https://wow.gamepedia.com/Franclorn_Forgewright#Quests
- https://wow.gamepedia.com/Dark_Iron_Legacy
- https://wow.gamepedia.com/Dark_Iron_Legacy_(2)

**Comment by offl** [comment]
> Could this be connected to the fact that the quests got removed in patch 4.0.3a (Cataclysm) and that a lot of TDB 335 content comes from Mists of Pandaria Patch 5.4.7, build 18019?

Nope as I gave the video above from WotLK (with no newly added text) + his old texts were sniffed in 2xx
So it is not related to Cataclysm

I think Blizzard just decided to make his gossip story available without any quests. But it required to remove last gossip option and text related to specific quest - "You will find Fineous Darkvire beyond the Ring of Law blah blah blah".
So then they added this text to quest description and removed the last gossip option and text, so it was never shown in game thus was never sniffed and will be never sniffed

Btw I hope this time we well have fully sniffed vanilla content as the classic wow is soon coming
