### ISSUE TITLE
3.3.5 worldserver error on applying updates

### ISSUE THREAD

**Issue by Asandru** [TrinityCore/TrinityCore#22632]
**Description:**

I compiled a fresh trinitycore 3.3.5 branch and upon starting worldserver and applying updates at a point I encountered this error in worldserver console:

> ERROR 1366 (HY000) at line 20: Incorrect string value: '\xD0\xAF \xD0\xB6\xD0...' for column 'RewardText' at row 43226
> 
> 
> Applying of file 'D:/Scene Gaming/realm1/ElunaTrinityWotlk/sql/updates/world/3.3.5/2018_10_09_02_world_335.sql' to database 'realm1world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
> Could not update the World database, see log for details.
> 

**Current behaviour:**

did not crash, just closed the worldserver

**Expected behaviour:**

should fix the sql update?

**Steps to reproduce the problem:**

1. Fresh compiled 3.3.5
2. run authserver.exe
3. run worldserver.exe
4. error result written above^

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Latest commit: https://github.com/TrinityCore/TrinityCore/commit/fd73543d91e3c660746b0abdd20461f4bdbaf700

**Operating system:** Windows 10 pro 64bit

**Comment by Aokromes** [comment]
wiki states disable strict mode.

**Comment by Asandru** [comment]
What do you mean by strict mode?

**Comment by Asandru** [comment]
Like this? `set global sql_mode='';`

**Comment by illfated** [comment]
https://www.knowledgebase-script.com/kb/article/6/how-do-i-disable-strict-mode-in-mysql-163.html
https://tehnoblog.org/mysql-server-compatibility-how-to-disable-strict-mode/
http://support.crowdvox.com/index.php?pg=kb.page&id=113

https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sql-mode-strict
