### ISSUE TITLE
Archaeologist Andorin

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22647]
**Description:**
https://www.wowhead.com/npc=29650/archaeologist-andorin
https://www.wowhead.com/quest=12854/on-branns-trail
https://www.wowhead.com/quest=12855/sniffing-out-the-perpetrator

**Current behaviour:**
Offers both On Brann's Trail and Sniffing out the Perpetrator

**Expected behaviour:**
Should offer Sniffing out the Perpetrator only after completing On Brann's Trail

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 7b9106a7f22d 2018-10-11 20:41:50 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4a9e0b5aca540cc0dda788fa41c3bc7c0035b3c7
