### ISSUE TITLE
[master/3.3.5] Hellfire Peninsula quest OfferReward, RequestItems deDE locales

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#22658]
**Description:**
Add most Hellfire Peninsula deDE quest offer reward and request items locales.

Both alliance and horde quests.
https://gist.github.com/AlcDenat/3faafd1d2035d7305b804df238638b2b

**Branch(es):**
- [X] 3.3.5
- [X] master

**TC rev. hash/commit:** 
6cb754ca4e6b
27510aa29911

**Comment by Killyana** [comment]
Are you sure TrinityCore Hellfire Peninsula quest changed since wotlk? If deprecated it doesn't matter as not available.

**Comment by AlcDenat** [comment]
I'm pretty sure there's nothing changed in the quests - I just noticed that some questids are deprecated while running through it two times with horde/alliance and had to fix some crawled stuff. 

If that doesn't matter, push it to master. DB layout in this regard is the same so it should be fine. It'll leave some quests on master without deDE locales (dark portal opening stuff?) but thats also fine.

**Comment by AlcDenat** [comment]
Just noticed, there is no "ObjectiveText" in quest_template in master, so above sql only works on 3.3.5 currently.

Dont push this yet - I'll split it tomorrow I guess.

1 PR for master+3.3.5 with most of the reward locales
1 PR for 3.3.5 with ObjectiveText in quest_template
1 PR for master with ObjectiveText in quest_objective

since I plan to get every zone, sorry for spam in advance :+1:

**Comment by AlcDenat** [comment]
done, now can be pushed to 3.3.5 & master
