### ISSUE TITLE
Error On Build (Transmog)

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22657]
The Last Tc 3.3.5 Error On Build

TrinityCore/src/server/game/DataStores/DBCStores.cpp:115:57: error: use of undeclared identifier
'ItemDisplayTemplateEntryfmt'; did you mean 'MailTemplateEntryfmt'?
DBCStorage sItemDisplayInfoStore(ItemDisplayTemplateEntryfmt);
^~~~~~~~~~~~~~~~~~~~~~~~~~~

<details>

[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_guild.cpp.o
/home/TrinityCore/src/server/game/DataStores/DBCStores.cpp:115:57: error: use of undeclared identifier
      'ItemDisplayTemplateEntryfmt'; did you mean 'MailTemplateEntryfmt'?
DBCStorage <ItemDisplayInfoEntry> sItemDisplayInfoStore(ItemDisplayTemplateEntryfmt);
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                        MailTemplateEntryfmt
/home/TrinityCore/src/server/shared/DataStores/DBCfmt.h:90:16: note: 'MailTemplateEntryfmt' declared here
char constexpr MailTemplateEntryfmt[] = "nxxxxxxxxxxxxxxxxxssssssssssssssssx";
               ^
[ 26%] Building CXX object src/server/game/CMakeFiles/game.dir/DataStores/M2Stores.cpp.o
1 error generated.
src/server/game/CMakeFiles/game.dir/build.make:1577: recipe for target 'src/server/game/CMakeFiles/game.dir                                                                                                    /DataStores/DBCStores.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/DataStores/DBCStores.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_honor.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_instance.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_learn.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_lfg.cpp.o
CMakeFiles/Makefile2:1197: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</details>

Debian 9
Branch: 3.3.5
Rev: https://github.com/TrinityCore/TrinityCore/commit/619f72f3ac83be2324b278ab614b0a9f22498752
Diff: Transmog

**Comment by Rochet2** [comment]
`ItemDisplayTemplateEntryfmt` is commented out by default.
https://github.com/TrinityCore/TrinityCore/blob/8edea4a3c294a1892c4bbdfdfbf043009a0d5c43/src/server/shared/DataStores/DBCfmt.h#L79
When updating it probably got commented out again during merge conflict solving.

Do note that simply uncommenting is not enough if you use transmogrification for example since the format in TC code is different to what transmog uses and simply uncommenting will then use wrong format.

**Comment by Hir0shi** [comment]
@Rochet2 
How to fixed?!

**Comment by Rochet2** [comment]
For transmogrification you would make sure all the needed changes to the files in `src/server/shared/DataStores/` and `src/server/game/DataStores/` are in place. See https://github.com/TrinityCore/TrinityCore/compare/3.3.5...Rochet2:bbf8b5e6286346457fe07ca868b0706d7e5167d4#files_bucket

**Comment by Hir0shi** [comment]
ok tnx !

this updated killed transmog for all time!?

:disappointed:

**Comment by Pharonax** [comment]
Seeing as this issue is not TC-related, can we close this? AFAIK there is no support from official TC for custom patches.
