### ISSUE TITLE
Quest/DB: Brann Bronzebeard

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22650]
**Description:**
https://www.wowhead.com/quest=12973/the-brothers-bronzebeard
https://www.wowhead.com/quest=12880/the-master-explorer

**Current behaviour:**
Brann Bronzebeard offers the quest **The Brothers Bronzebeard** before you turn in **The Master Explorer**.

**Expected behaviour:**
The Master Explorer is required to have been completed before The Brothers Bronzebeard can be accepted.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 7b9106a7f22d 2018-10-11 20:41:50 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by illfated** [comment]
Ref. **[DEV]Core/Quest: Breadcrumb quests requirements** #22264

BTW: TC usually uses DB/Quest: - in that order - (main category/sub-category) in issue titles.

**Comment by Aokromes** [comment]
needs to be fixed by https://github.com/TrinityCore/TrinityCore/issues/22264

**Comment by jerbookins** [comment]
@Aokromes does this really count as a breadcrumb, though? Most breadcrumbs involve multiple quests intended to bring you to a new hub location in order to start up new quest lines. These quests are very much related, The Master Explorer is just the end of a chain that leads to The Brothers Bronzebeard.
