### ISSUE TITLE
The Brothers Bronzebeard

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#22651]
**Description:**
https://www.wowhead.com/quest=12973/the-brothers-bronzebeard

**Current behaviour:**
1. Brann's Flying Machine seems to have a custom path of only a few points and the flying looks poor.
2. While standing on the left wing of Brann's Flying machine, Stormforged Soldiers appear on the right wing and engage in combat with you.
3. When Stormforged Soldiers die, they tend to remain on the wing of the plane. Some continue to stand as if still in combat and take a couple minutes to despawn. Others die normally and lay down but remain on the wing for minutes.
4. Hovering over Brann's Flying Machine shows an enter vehicle icon. But right clicking the plane does nothing.
5. Stormforged Soldiers standing on the walls casting spells at Brann's Flying Machine tend to miss very often.

**Expected behaviour:**
1. Brann's Flying Machine should path in a smoother spiral upward to the top of the Engine of the Makers (possibly attracting more agro from npc's that cast spells from the walls of the Engine).
2. Stormforged Soldiers that jump up on the right wing should first engage in combat with the plane, as the whole challenge of the quest is to avoid damage done to the plane.
3. Any Stormforged Soldiers that die on the wing of the plane should get knocked off of the plane.
4. Brann's Flying Machine should not appear to be interactive at all once you initially start the quest by jumping on the wing.
5. Stormforged Soldiers should target and hit the plane a lot more often, giving risk that the plane might die before the quest can be completed.

https://youtu.be/JRsRjaGV3jA

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 7b9106a7f22d 2018-10-11 20:41:50 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.12.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.64

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
Waypoints for the flying machine was taken from sniffs, the issue is related to Catmullrom waypoint movemen not being implemtend

Stormforged Soldiers not being ejected once dead is a new issue related to the core.

The spell click cursor that appear is also a general issue, even with condition the cursor will remains.
``` sql
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry` IN (30134) AND `spell_id`=55089;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES
(30134, 55089, 0, 0);

UPDATE  `npc_spellclick_spells` SET user_type=0 WHERE `npc_entry` IN (30134);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=18 AND `SourceEntry` IN  (55089);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(18,30134,55089,0,0,31,0,3,30136,0,0,0,'','Only npc for spellclick');
```

This cosmetic spell must always miss the flying machine https://woehead.way-of-elendil.fr/?spell=56622 you can check videos.

**Comment by Killyana** [comment]
I tried to add threat to the Stormforged Soldier once on the flying machine, but it doesn't work, it looks accessory cannot have threat towards the vehicle.

``` sql
UPDATE  `creature_template` SET `faction`=290 WHERE `entry` IN (30134);
UPDATE `smart_scripts` SET `event_type`=60 WHERE `entryorguid` IN (30134) AND `source_type`=0 AND `id` IN (13,14);
DELETE FROM `smart_scripts` WHERE `entryorguid` = 30136 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(30136, 0, 0, 0, 0, 0, 100, 0, 3000, 3000, 4000, 4000, 11, 56621, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,0,'Stormforged Soldier - In Combat - Cast Thunder Orb'),
(30136, 0, 1, 0, 23, 0, 100, 0, 55089, 1, 2000, 2000, 123, 1000, 0, 0, 0, 0, 0, 19, 30134, 0, 0, 0, 0, 0,0,'Stormforged Soldier - Has aura - Add threat machine');

**Comment by Killyana** [comment]
Remaining issues are in other ticket.
