### ISSUE TITLE
Instance/script: High Priestess of Thaurissan

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22660]
**Description:** The npc https://woehead.way-of-elendil.fr/?npc=8929 must change its template according if all players in the donjon has this quest rewarded or not:

For the Alliance: https://woehead.way-of-elendil.fr/?quest=4363
For the Horde : https://woehead.way-of-elendil.fr/?quest=4004

If the condition is true the npc will be changed to https://woehead.way-of-elendil.fr/?npc=10076
Otherwise https://woehead.way-of-elendil.fr/?npc=8929 will remains.

https://wow.gamepedia.com/High_Priestess_of_Thaurissan

**Branch(es):** both maybe I cannot find more info

**TC rev. hash/commit:**  rev. 1e99f9832718

**Comment by kuskmen** [comment]
@Killyana , do you know if it has to be dynamic or once changed it never changes back?

**Comment by Killyana** [comment]
Make it static, when the instance is created.

**Comment by kuskmen** [comment]
I think it is impossible to be done when instance is created but more like when creature is created (i.e when it comes in line of sight for one of the players).

**Comment by Killyana** [comment]
When the instance is created you check quest statuts for all players and you store the result into a boolean, this boolean will be used when the creature is created to decide if a update entry must be done or not.
