### ISSUE TITLE
Hallow's end: Pumpkin Shrine gossip menu option

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22664]
**Description:**
Pumpkin shrine (object=186267) has a gossip menu option 'Call the Headless Horseman' (menu_id = 8891) but it does nothing.
I have researched but I did not found information about how it should work.

Branch: 3.3.5
TC rev: 7b9106a
OS: Win 8.1

**Comment by illfated** [comment]
Odd. Shouldn't that option only be available if you have started the quest?
And what about the Dreary Candle?
- https://www.wowhead.com/quest=11405/call-the-headless-horseman
- https://www.wowhead.com/item=33985/dreary-candle

**Comment by TheWinchesters** [comment]
Looks like it is always visible without any condition.
It is visible even with the Headless Horseman already summoned.

**Comment by illfated** [comment]
For some odd reason (back in 2018), I did not think of comparing the item description on wowhead with the one on tcubuntu.northeurope.cloudapp.azure.com/aowow/ :

On https://www.wowhead.com/item=33985/dreary-candle | Provided for (4) | Objective of (4) | :

Name | Level | Req. | Side | Rewards | Exp. | Money | Category | Completion
-- | :--: | :--: | :--: | :--: | :--: | :--: | -- | --
[Call the Headless Horseman](https://www.wowhead.com/quest=11404/call-the-headless-horseman) | <sub>1</sub> <br> <sup>Daily Group</sup> | 1	|	|	| 30 |	|	[Hallow's End](https://www.wowhead.com/quests=9.-1003)
[Call the Headless Horseman](https://www.wowhead.com/quest=11401/call-the-headless-horseman) | <sub>1</sub> <br> <sup>Daily Dungeon</sup> | 1 	| ?? |	|	30	|	| [Hallow's End](https://www.wowhead.com/quests=9.-1003)
[Call the Headless Horseman](https://www.wowhead.com/quest=11392/call-the-headless-horseman) | 10 |	10 |	??	| |	180	|	| [Hallow's End](https://www.wowhead.com/quests=9.-1003)
[Call the Headless Horseman](https://www.wowhead.com/quest=11405/call-the-headless-horseman) | <sub>20</sub> <br> <sup>Daily Dungeon</sup> | 20	|	| |	350	| |	[Hallow's End](https://www.wowhead.com/quests=9.-1003)

On https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=33985 | Objective of (4) | Provided for (4) | :

Name | Level | Req. | Side | Rewards | Exp. | Money | Category
-- | :--: | :--: | :--: | :--: | :--: | :--: | --
[Call the Headless Horseman](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11404) <sub>_Disabled_</sub> | Daily | 75 |   |   | 1 |   | [Hallow's End](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quests=9.-1003)
[Call the Headless Horseman](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11401) <sub>_Disabled_</sub> | Daily Dungeon | 75 |   |   | 1 |   | [Hallow's End](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quests=9.-1003)
[Call the Headless Horseman](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11405) | Daily Dungeon | 75 |   |   | 1 |   | [Hallow's End](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quests=9.-1003)
[Call the Headless Horseman](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11392) <sub>_Disabled_</sub> | 80 | 75 |   |   | 2200 |   | [Hallow's End](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quests=9.-1003)

I have not checked any of the details yet. There seems to be some discrepancy here, even though I don't know how important it is.

**Comment by offl** [comment]
Probably because of Patch 7.2.5 (2017-06-13): The Headless Horseman now scales to the player's level, starting at 23.

**Comment by Keader** [comment]
https://www.youtube.com/watch?v=0RZ8LrkUZJw

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a93abcf8031fc3b4dc6db16aa09d92a221bc6a77
