### ISSUE TITLE
Spell/Script: Haunting Phantoms

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22662]
**Description:** https://www.wowhead.com/spell=16336/haunting-phantom used by https://www.wowhead.com/npc=10385 and https://www.wowhead.com/npc=10384 must summon one of this npcs randomly if the player has the aura:

https://woehead.way-of-elendil.fr/?npc=10389 https://woehead.way-of-elendil.fr/?spell=16335
https://woehead.way-of-elendil.fr/?npc=10388 https://woehead.way-of-elendil.fr/?spell=16334

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/Stratholme/stratholme.cpp#L203

The spell is not scripted and not used by this npcs.

**Branch(es):** both

**TC rev. hash/commit:**  rev. cf2ca013f7a3

**Comment by PolarCookie** [comment]
Dummy aura that randomly triggers script, similar to https://github.com/TrinityCore/TrinityCore/issues/22687

**Comment by Killyana** [comment]
Yes it must be the 16336
