### ISSUE TITLE
Hallow's end: Sir Thomas

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22667]
**Description:**
According to wowhead comments, "after you vanquish the Headless Horseman during the Hallows End event, the ghost of Sir Thomas will appear". (https://www.wowhead.com/npc=23904/sir-thomas).
Also, he is offering both alliance and horde quest https://www.wowhead.com/quest=11242 / https://www.wowhead.com/quest=11403 to any character.
I may think that is becasue these quests does not have ``AllowableRaces`` in the ``quest_template`` table so maybe this work:
<pre>UPDATE `quest_template` SET `AllowableRaces` = '1101' WHERE (`ID` = '11242');
UPDATE `quest_template` SET `AllowableRaces` = '690' WHERE (`ID` = '11403');</pre>

**Current behaviour:**
He does not appear.

**Steps to reproduce the problem:**
1. .go gameobject 54947
2. Start the event
3. Kill the Headless Horseman

Branch(es): 3.3.5
TC rev. hash/commit: 48eba61
Operating system: Win 8.1

**Comment by Killyana** [comment]
As you can see here some spells are used to summon the npc https://youtu.be/mzdwge0a_G8?t=184
We don't have any sniff of the encounter for the moment.

**Comment by TheWinchesters** [comment]
Thanks for the explanation!

**Comment by Killyana** [comment]
``` sql
DELETE FROM `creature_template_addon` WHERE `entry`=23904;
INSERT INTO `creature_template_addon` (`entry`, `bytes2`,`auras`) VALUES
(23904, 1, '42823'); -- 23904 (Sir Thomas)

**Comment by Keader** [comment]
@Killyana with https://github.com/TrinityCore/TrinityCore/pull/25614 it will be summoned.
You need handle with both quest showing for both factions issues (i know nothing about quests xD)

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a93abcf8031fc3b4dc6db16aa09d92a221bc6a77
