### ISSUE TITLE
[BUG] Link Sher Talents!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22685]
Some talents can not be linked!

example:
paladin , talent  [Sanctified Retribution]
or
can not be linked talents off, you can just linked Some Activated and taken!

os: server
Branch(es): 3.3.5
TC rev. hash/commit: rev. https://github.com/TrinityCore/TrinityCore/commit/1e99f98327189c00e9e5e552d332120f12d38f03

**Comment by Hir0shi** [comment]
updated to https://github.com/TrinityCore/TrinityCore/commit/beed1f9dbeac8bf374fb37120513f8b7de44a1e3

don't work!

**Comment by Aokromes** [comment]
you don't need to spam, i already confirmed the bug exist.

**Comment by Jildor** [comment]
I guess he means link the talent in the chat
