### ISSUE TITLE
Spell/Script: Scourge Disguise

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22687]
**Description:**
https://www.wowhead.com/spell=51966/scourge-disguise
The "unstable and may begin to wear off unexpectedly" part of this spell isn't working.

Educated guess, but applying this spell should also apply
https://www.wowhead.com/spell=51971/scourge-disguise-instability
a hidden aura which will randomly trigger 
https://www.wowhead.com/spell=52010/scourge-disguise-expiring

Edit:
Got
https://www.wowhead.com/spell=54089/drop-disguise
wrong, it is used by Drakuru sometimes to trigger 52010, 52010 handles taking of disguise as is.

**Branch(es):** both

**TC rev. hash/commit:** rev. 31a2a39

**Comment by dr-j** [comment]
Yes had to incorporate hack for this functionality in https://github.com/TrinityCore/TrinityCore/commit/dd985a8c2635d31b66b12624dfbafe59673d4fdd
