### ISSUE TITLE
[BUG] Gobject On BG - > [return bg heal] !

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22693]
don't give heal to player on Battleground maps By  Gobject [return bg heal] !

os: win server
Branch(es): 3.3.5
TC rev. hash/commit: rev. https://github.com/TrinityCore/TrinityCore/commit/1e99f98327189c00e9e5e552d332120f12d38f03

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21615
