### ISSUE TITLE
DB/Quest: Fire Sapta & Water Sapta

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#22703]
**Description:**

* Fix availability for quests "Fire Sapta" & "Water Sapta"

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a10870571558 2018-09-03 22:06:51 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- Quest "Fire Sapta"
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=1464 AND `ConditionTypeOrReference`=2;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19,0,1464,0,0,2,0,6636,1,1,1,0,0,"","Quest 'Fire Sapta' can only be taken if player does not have item 'Fire Sapta'");

-- Quest "Water Sapta"
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=972;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19,0,972,0,0,14,0,96,0,0,0,0,0,"","Quest 'Water Sapta' can only be taken if quest 'Call of Water (Part 9)' is not taken"),
(19,0,972,0,0,2,0,6637,1,1,1,0,0,"","Quest 'Water Sapta' can only be taken if player does not have item 'Water Sapta'");

**Comment by ZenoX92** [comment]
@Killyana, I noticed some strange issue when testing this. If I deleted the item, for the quest to show up again I had to log out and log in, or kill and respawn the NPC. Can you take a look at this?

**Comment by illfated** [comment]
Sounds like a similar issue I had when some of my quest items were in the bank and I had to log out and back in with the items in my backpack to get the quest to show up as completed. The quest I had this kind of issue with was https://www.wowhead.com/quest=10757/rohoks-request (https://woehead.way-of-elendil.fr/?quest=10757).

**Comment by Killyana** [comment]
@ZenoX92 Yes it's an old issue, quest availability is not updated correctly to the client.

**Comment by Killyana** [comment]
The condition looks incorrect for me, it must be:
``` sql
(19, 0, 972, 0, 0, 8, 0, 220, 0, 0, 0, 0, 0, "", "Show quest 'Water Sapta' only if quest 'Call of water' is Rewarded"),
(19, 0, 972, 0, 0, 2, 0, 6637, 1, 1, 1, 0, 0, "", "Show quest 'Water Sapta' only if the item 'water-sapta' is not in player's bags or bank"),
(19, 0, 972, 0, 0, 8, 0, 96, 0, 0, 1, 0, 0, "", "Show quest 'Water Sapta' only if quest 'Call of water' is not Rewarded");

**Comment by illfated** [comment]
Heh. "Call of water" as quest name is mildly confusing, because of all the quests named as such.
How about "**Call of Water (6)**" for q ID 220 and "**Call of Water (9)**" for q ID 96 in the comment?

**Comment by ZenoX92** [comment]
I think this part is not needed:

(19, 0, 972, 0, 0, 8, 0, 220, 0, 0, 0, 0, 0, "", "Show quest 'Water Sapta' only if quest 'Call of water' is Rewarded"),

Quest "Water Sapta" has already a prerequisite in the "quest_template_addon" table.

And about this part:

(19, 0, 972, 0, 0, 8, 0, 96, 0, 0, 1, 0, 0, "", "Show quest 'Water Sapta' only if quest 'Call of water' is not Rewarded");

I think it's better to use Condition Type 14 instead of 8. You don't need the item once you have taken quest 96. Otherwise, the gossip option will be visible when you talk to the NPC to turn in the quest.
