### ISSUE TITLE
Print gameobject rotation

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#22714]
**Description:**

There is no way to view the full rotation of gameobjects with a command. You can only view orientation (yaw), but not pitch or roll even if you can set them with `.gobject turn <guid> <yaw> <pitch> <roll>`.

Suggestions

1. `.gps <link>` prints current rotation as a part of the other info
2. `.gobject info guid <link/guid>` prints current rotation as a part of the other info
3. `.gobject turn <link/guid>` prints current rotation instead of setting one when no rotation arguments given

**Current behaviour:**

There is no way to view the full rotation of gameobjects.

**Expected behaviour:**

There would be a command to view the current rotation (yaw, pitch and roll) of a gameobject.

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

0a0312b705ecb1a318fd3abe545b571a3a349a9c

**Comment by jackpoz** [comment]
sounds like a good idea. do you plan on implementing yourself the suggestions above ?

**Comment by Rochet2** [comment]
Well, sure. I am not sure if it should be added to one or all of them though.

**Comment by Shauren** [comment]
Just to info
