### ISSUE TITLE
Gobject: The Raven's Claw

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22717]
**Description:**
The gobject https://es.wowhead.com/object=185554/the-ravens-claw is used to summon Anzu.

**Current behaviour:**
You can summon the NPC Anzu as many times as you want.
**Expected behaviour:**
The gobject should be deactivated once Anzu is summoned.

**Steps to reproduce the problem:**
1. .add 32449 (Gobject needs this key)
2. .go gameobject 44722
4. Click the gobject several times

Branch: 3.3.5a
TC rev: 0a0312b
OS: Win 8.1

**Comment by RedSonja** [comment]
confirmed

**Comment by TheWinchesters** [comment]
This worked for me
```sql
UPDATE `gameobject_template` SET data3 = 86400000 WHERE entry = 185554;
```
I do not know if this could be a good solution to apply here.

**Comment by offl** [comment]
Duplicate of #25481

**Comment by jackpoz** [comment]
let's do the other way around

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25481#issuecomment-696021124 has some useful info for a related error log triggered by this issue

**Comment by jackpoz** [comment]
can a check be implemented with conditions ?

**Comment by Keader** [comment]
InstanceScript has support to implement it
