### ISSUE TITLE
[master/3.3.5] Niobe Whizzlespark is friendly towards horde

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#22724]
**Current behaviour:**
Niobe Whizzlespark is friendly towards horde chars

**Expected behaviour:**
Niobe Whizzlespark should attack any horde chars (shes alliance)
https://www.wowhead.com/npc=24868/niobe-whizzlespark

**Steps to reproduce the problem:**
1. create any horde char
2. .tele wildhammer
3. turn around north-west to see her

**Branch(es):**
- [x] 3.3.5
- [X] master

**TC rev. hash/commit:** 
6cb754ca4e6b
27510aa29911

**Comment by Killyana** [comment]
The faction is 35 in 3.3.5,  4.3.4 and 7.3.5 it's an issue from retail as you can see here https://www.wowhead.com/npc=24868/niobe-whizzlespark#comments:id=184413:reply=21296

The horde trainer have the faction 66 horde generic, so probably it must be 189 alliance generic.

**Comment by AlcDenat** [comment]
Holy balls you're right - didn't even think of that.

I just went there on live with my horde main and there she is - friendly and willing to teach me engineering.

We want this to be blizzlike so...

**Comment by Killyana** [comment]
Ask Blizzard to fix the faction, once done we can update the DB.

**Comment by AlcDenat** [comment]
Funny - I just reported it as a bug (as maybe hundreds before me) :+1:

**Comment by offl** [comment]
She was sniffed in 2.x.x and the faction was never changed according to other DBs

**Comment by Aokromes** [comment]
https://i.imgur.com/ifnYRxx.jpg and still friendly on ptr xd

**Comment by Killyana** [comment]
``` sql
UPDATE `creature_template` SET `faction`=189 WHERE `entry`=24868;
