### ISSUE TITLE
Crash after spawning, moving, turning, deleting gameobjects and then relogging

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#22720]
**Description:**

Editing gameobject positions in game (spawning, moving, turning, deleting) results in a crash if the player logs out, waits for a time and logs in. (I was logged out automatically, waited for a lengthy time and logged back in)

All editing of gameobjects was done with GM commands.

**Current behaviour:**

After editing gameobject positions and deleting gameobjects and relogging the server crashes with the following message:
```
c:\users\user\documents\cores\fork\335\source\src\server\game\grids\objectgridloader.cpp:148 in LoadHelper ASSERTION FAILED:
  godata
Tried to load gameobject with spawnId 166664, but no such object exists.
```

Crashlogs:
clean core: https://gist.github.com/Rochet2/2928f008b03c47fa94288879dfe2a64f
core with dressnpcs: https://gist.github.com/Rochet2/0e287215d6eebabcfda2aaf7cb26a26b

**Expected behaviour:**

No crashes

**Steps to reproduce the problem:**

1. spawn objects with ,gob add
2. move objects with .gob move
3. turn objects with .gob turn
4. delete objects with .gob del
5. wait until autologged out
6. log back in
7. crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0a0312b705ec 2018-10-25 12:10:27 +0200 (3.3.5 branch) (Win64, Debug, Static)
```
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.68.0
Using MySQL version: 5.6.36
Using CMake version: 3.8.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64
```

**Operating system:**
Windows 10

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21803

**Comment by jackpoz** [comment]
what are your setting about grid unload ?

**Comment by Rochet2** [comment]
https://gist.github.com/Rochet2/56cdcde5e3bd281a9b0a5ece19cf50f1#file-worldserver-conf-L288
Settings should mostly be default

**Comment by jackpoz** [comment]
thanks, thought so that it was enabled

**Comment by jackpoz** [comment]
I was wondering, why is this even an assert and not just an error ?

**Comment by Shauren** [comment]
Because its never supposed to happen, a gameobject having spawnId !=0 while sObjectMgr->GetGameObjectData(spawnId) returns nullptr. That field implies a db spawn and all db spawns without exception must have valid data in gameobject table (which is what sObjectMgr->GetGameObjectData(spawnId) returns)

**Comment by jackpoz** [comment]
This happens due to the hacky nature of .gob commands that SaveToDB/Delete/LoadFromDB gameobjects (due to 335 client requiring that) and the async nature of Delete(), calling Map::RemoveFromMap() after having called LoadFromDB().
