### ISSUE TITLE
Server Much To Crashed!

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22731]
Description: I do not know
server Much  , will to crashed !

crash log!

https://gist.github.com/Hir0shi/08ca9e109d52b479a462ea70729a8968

Branch: 3.3.5

TC rev: https://github.com/TrinityCore/TrinityCore/commit/0a0312b705ecb1a318fd3abe545b571a3a349a9c

Operating system: debian

**Comment by Ovahlord** [comment]
Looks like a nullpointer crash when doing melee attacks while charmed

**Comment by Jildor** [comment]
Can be related with @Treeston commit??
https://github.com/TrinityCore/TrinityCore/commit/042f5515e4f3e52b0d2e23d9b9e147041849ce12#diff-89e4c142cf547b5178c8bd67179b5b9c

**Comment by Hir0shi** [comment]
trinitycore developer please help me , my server is down :cry: 

I can not run server, The server crashed ten times a day  :disappointed: 

Someone helps please

**Comment by Shauren** [comment]
We are not your live support, stop spamming comments (this is not a forum, you cannot "bump" issues)

**Comment by Hir0shi** [comment]
yes i know and so Very sorry @Shauren 

Fix it whenever you like.

**Comment by jackpoz** [comment]
this looks the same as https://github.com/TrinityCore/TrinityCore/issues/22629 
btw do you have any custom change ?

**Comment by Hir0shi** [comment]
hi @jackpoz 

When players are in instances or map areas killed to creatures,
server will to crashed !!

chance to crash.

**Comment by jackpoz** [comment]
please try building in Debug mode and post a crash with that. It might be that the issue happens in https://github.com/TrinityCore/TrinityCore/blob/f7283d97660be93921fdabb58a9fc3a245ece6e2/src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp#L165 so try to reproduce the crash while playing in Naxxramas fighting KelThuzad

**Comment by jackpoz** [comment]
it's also used in https://github.com/TrinityCore/TrinityCore/blob/0a0312b705ecb1a318fd3abe545b571a3a349a9c/src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_blackheart_the_inciter.cpp#L58 , could you try Shadow Labyrinth fighting BlackHeart The Inciter ?

**Comment by Hir0shi** [comment]
tested boss_blackheart_the_inciter , server don't crashed
crash is not for this boss!

 i know crash is payer killed creatures and server will to crashed

player / UnitAI.

if (me->HasUnitState(UNIT_STATE_CASTING))

victim = <optimized out>
target = <optimized out>
charmer = <optimized out>
player = 0x7fff3ef100c0
updater = {i_timeDiff = 100}
 world_object_update = <optimized out>
grid_object_update = <optimized out>
now = <optimized out>
unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140734489425664, 5281893881263977768, 140734489417664, 0, 140735090962080, 140737488340688, -5281714111950064344, -5281910322644880088}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
not_first_call = <optimized out>

No locals.

**Comment by jackpoz** [comment]
is that from TrinityCore build in Debug mode ? I mean using CMake parameter -DCMAKE_BUILD_TYPE=Debug

**Comment by Hir0shi** [comment]
oh ` sry  , yes It is true!

UnitAI::DoMeleeAttackIfReady (this=0x7fff43afee00) at /in/TrinityCore/src/server/game/AI/TrinityCoreAI/UnitAI.cpp:64
victim = <optimized out>

in PlayerAI::DoAutoAttackIfReady (this=<optimized out>) at /in/TrinityCore/src/server/game/AI/PlayerAI/PlayerAI.cpp:584
No locals.

SimpleCharmedPlayerAI::UpdateAI (this=0x7fff43afee00, diff=<optimized out>) at /in/TrinityCore/src/server/game/AI/PlayerAI/PlayerAI.cpp:1245
        target = <optimized out>
        charmer = <optimized out>

in Player::Update (this=0x7fff3ef100c0, p_time=100) at /in/TrinityCore/src/server/game/Entities/Player/Player.cpp:1075
        now = 1540887090
        pet = <optimized out>

in Map::Update (this=0x7fffb4c3e000, t_diff=100) at /in/TrinityCore/src/server/game/Maps/Map.cpp:789
        player = 0x7fff3ef100c0
        updater = {i_timeDiff = 100}
        world_object_update = <optimized out>
        grid_object_update = <optimized out>

in InstanceMap::Update (this=0x7fffb4c3e000, t_diff=100) at /in/TrinityCore/src/server/game/Maps/Map.cpp:3851
No locals.

in MapUpdateRequest::call (this=0x7fffea494700) at /in/TrinityCore/src/server/game/Maps/MapUpdater.cpp:42
No locals.

in MapUpdater::WorkerThread (this=0x20cabe0 <MapManager::instance()::instance+160>) at /in/TrinityCore/src/server/game/Maps/MapUpdater.cpp:113
        request = 0xab00000100000079

**Comment by sirikfoll** [comment]
@Hir0shi, you could add this line, it may give you information on which instance the crash happens
```diff
diff --git a/src/server/game/Maps/Map.cpp b/src/server/game/Maps/Map.cpp
index 921f982b5a..1bdb2d8d5c 100644
--- a/src/server/game/Maps/Map.cpp
+++ b/src/server/game/Maps/Map.cpp
@@ -744,6 +744,7 @@ void Map::UpdatePlayerZoneStats(uint32 oldZone, uint32 newZone)
 
 void Map::Update(uint32 t_diff)
 {
+    volatile uint32 debugMapID = GetId();
     _dynamicTree.update(t_diff);
     /// update worldsessions for existing players
     for (m_mapRefIter = m_mapRefManager.begin(); m_mapRefIter != m_mapRefManager.end(); ++m_mapRefIter)

```

**Comment by Hir0shi** [comment]
hi  @sirikfoll 

okay i will aded
your line cod on source. -> Maps/Map.cpp

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/d8fee3c46b70fed660aec905a496e56d6a327aaf and post the new crashlog on gist if you get any

**Comment by jackpoz** [comment]
Continuing the discussion at https://github.com/TrinityCore/TrinityCore/issues/22861
