### ISSUE TITLE
[3.3.5] Deathfrost effect

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22730]
**Description:**
The enchantment Deathfrost (https://www.wowhead.com/spell=46578/deathfrost) inflicts additional Frost damage and slows the target.

**Current behaviour:**
Slow effect is never applied.

**Expected behaviour:**
Slow effect should work on targets < 73.

Branch: 3.3.5
TC rev: 9b02fe6
OS: Win 8.1

**Comment by Pharonax** [comment]
spell_proc table?

**Comment by Razfury** [comment]
f5220ee4c2a1729c778013379c4a5ba95f7307ed but did not add proc so it needs added

**Comment by Keader** [comment]
Working.
Like Razfury say, it only proc if player has level below 74
