### ISSUE TITLE
Warlock Spell Error

### ISSUE THREAD

**Issue by animaflower** [TrinityCore/TrinityCore#22732]
**Description:**

spell id : 48181

spell name : 鬼影缠身

**Current behaviour:**

Continuous use can not refresh the target aura

**Expected behaviour:**

Continuous use can refresh the target aura

**Steps to reproduce the problem:**

Continuous use the spell

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

257ae44

**Operating system:** 

windows 7

**Comment by NixAJ** [comment]
Please update the issue with a valid commit hash and whatever else TC might need. 

Would love to have this issue sorted.

**Comment by TheWinchesters** [comment]
Am I wrong or this is related to "Core/Spell: Debuffs are not renewed on target"?

**Comment by illfated** [comment]
issue #21635 I presume. Same debuff refresh issue with hunter stings (although not mentioned in #21635 ).

**Comment by Aokromes** [comment]
test after a099974

**Comment by animaflower** [comment]
Great

**Comment by Killyana** [comment]
Dup of #21635
