### ISSUE TITLE
[3.3.5] ICC/Professor Putricide: Volatile Ooze/Gas Cloud

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22756]
**Description:**
Volatile Ooze/Gas Cloud stops following the player if the player uses spells like Blink or Warlock portal and stays there doing nothing.
Also, nothing happens if Gas Cloud reaches the target.
If the target uses spells like Vanish, Volatile Ooze/Gas Cloud stops and does nothing.

**Expected behaviour:**
Volatile Ooze/Gas Cloud should not stop following the player even after that type of spells and after target lost, should look for another target.

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by AByakugans** [comment]
Again reported here already: https://github.com/TrinityCore/TrinityCore/issues/21672

**Comment by TheWinchesters** [comment]
@AByakugans thank you again
