### ISSUE TITLE
ICC: Valithria Dreamwalker

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22753]
**Description:**
Valithria Dreamwalker (https://www.wowhead.com/npc=36789) is moved by some spell while the encounter is happening. I think it is Column of Frost (https://www.wowhead.com/spell=70702) because it is the only spell that has a movement effect in that zone.
Whatever  is affecting Valithria, she flies and rests on another place of the room, like in this image:
https://imgur.com/85c1WPc

**Expected behaviour:**
She should not move

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by TheWinchesters** [comment]
There is a CREATURE_TYPEFLAGS_BOSS (Changes creature's visible level to "??" in the creature's portrait - Inmune Knockback.) and I wanted to see if Valithria has this type_flags, but what does '67113036' means in type_flags?
That number is not a sum of possible type_flags and entries 36789, 38174 are the only ones with that value

**Comment by TheWinchesters** [comment]
Not sure if it is the best solution but adding CREATURE_FLAG_EXTRA_IMMUNITY_KNOCKBACK in flags_extra solves this.

**Comment by lachtanek** [comment]
it should be alright I don't think you should be able to knockback a boss (exceptions might exist tho)

**Comment by Keader** [comment]
Looks correct to me @TheWinchesters

**Comment by TheWinchesters** [comment]
This is what I did:
```sql
UPDATE `creature_template` SET `flags_extra` = '1073741825' WHERE `entry` IN ( '36789', '38174');
```

**Comment by Keader** [comment]
Hmm, is never good just make "extra_flags = something"

Is better like this:

```sql
UPDATE `creature_template` SET `flags_extra` =  `flags_extra` |1073741824 WHERE `entry`  IN(36789,38174);
```

**Comment by TheWinchesters** [comment]
Thank you for the explanation :D
