### ISSUE TITLE
ToC: Twin Val'kyrs

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22755]
**Description:**
Issue 1: If you wipe while fighintg the Twin Val'kyrs you can not enter the instance again because an encounter is happening.
Issue 2: When the Twin Val'kyrs show up, they appear above the ground.

Should they disappear after the wipe and the player should call them again?

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by Keader** [comment]
"Issue 2: When the Twin Val'kyrs show up, they appear above the ground."
Need active hover

**Comment by TheWinchesters** [comment]
Please let me know if something needs more explanation. I do my best but English is not my native language.

**Comment by Keader** [comment]
4c6f0eaa8d2b680c98ba125b5c90748f31928eda
