### ISSUE TITLE
ICC: Suppressors

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22754]
**Description:**
Suppressor (https://www.wowhead.com/npc=37863) should go directly to Valithria Dreamwalker and attack her casting (https://www.wowhead.com/spell=70588/suppression) but if a player is in the zone the suppressor goes to Valithria and as soon as he is at her side, he goes to attack the player.
If no player, supressor goes to Valithria and casts normally.
Also, I am not sure if Suppression is doing something. Healing amount does not change even if Valithria has this debuff x 12.

Here, I have a big group of suppressors. I did nothing, they just came:
https://imgur.com/KTDTE9i
(Silenciador = Suppressor)

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by sawd14** [comment]
@Treeston @Shauren  can you pls help with this issue

**Comment by TheWinchesters** [comment]
Please, do not tag people just to tell them "fix this / help with this".
Each person who is helping in this project is already contributing doing the best and they do it according to their possibilities, free time, etc.
Be patient.

**Comment by illfated** [comment]
It is usually practical to show differences (diff content) using ```diff if you already have got a .diff or .patch output, like in Git Extensions.
You can also use online diff tools, but most of them only show the entire file, not the changed parts with patch information.
If online diff tools are your only option, you need to copy/paste only the changed lines.

Output from Git Extensions:
```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
index 7752d697da..98b6e2b941 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
@@ -883,12 +883,11 @@ class npc_suppresser : public CreatureScript
             void MovementInform(uint32 /*type*/, uint32 id) override
             {
                 if (id == 42)
                 {
-                    me->SetReactState(REACT_AGGRESSIVE);
                     if (Creature* valithria = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_DREAMWALKER)))
                     {
-                        AttackStart(valithria);
+                        me->SetTarget(_instance->GetGuidData(DATA_VALITHRIA_DREAMWALKER));
                         DoCastAOE(SPELL_SUPPRESSION);
                     }
                 }
             }
```

**Comment by Shauren** [comment]
You should never use `SetTarget`, all this does is change current visible target (the thing you see when you enable target of target unit frame) and will be automatically changed by core (for example on threat update)

**Comment by TheWinchesters** [comment]
`FocusTarget` is a better or worst idea?

**Comment by lachtanek** [comment]
you could override CanAIAttack method, something like
```c++
bool CanAIAttack(Unit const* target) const override {
    return target->GetGUID() == _instance->GetGuidData(DATA_VALITHRIA_DREAMWALKER);
}
```

**Comment by TheWinchesters** [comment]
I have been watching videos and I did not see suppressers attack players.

Here, they talk about it in the comment section
https://github.com/TrinityCore/TrinityCore/commit/8ce80db6e6787ecb967c36e84791042eef5ac5e0

Maybe someone who has played 3.3.5a can clarify this.

**Comment by lachtanek** [comment]
actually they should never attack as said in comments in the commit mentioned, they should just cast a spell on Valithria, so someone needs to find out why (if) they don't and fix that problem instead

**Comment by TheWinchesters** [comment]
@lachtanek
This line: `me->SetReactState(REACT_AGGRESSIVE);`
Once they go to x position, they go attack players as the other mobs in the room do.

**Comment by Keader** [comment]
1 issue remain in Suppresser.
He's interrupting self caused by UpdateSpline.
I will open a new ticket for it tomorrow.

**Comment by TheWinchesters** [comment]
What about the spell https://www.wowhead.com/spell=70588/suppression ?
Looks like it does nothing.

**Comment by Keader** [comment]
@TheWinchesters
Effect is there, but cast fail, caused by SplineUpdate (https://github.com/TrinityCore/TrinityCore/issues/22754#issuecomment-451626325)
It's not Suppressor issue, is Spell System one.
Check https://github.com/TrinityCore/TrinityCore/issues/21048#issuecomment-451338102
