### ISSUE TITLE
DB/Quest: The Amphitheater of Anguish: Yggdras!

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22752]
**Description:**
If you have completed Ring of Blood in Nagrand, Gurgthock will offer a different version of Yggdras with some variation on the text.

**Current behaviour:**
If you have completed Ring of Blood in Nagrand; Gurgthock offers both versions of Yggdras.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
257ae44

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=12932;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19, 0, 12932, 0, 0, 8, 0, 9977, 0, 0, 1, 0, 0, '', 'Quest "The Amphitheater of Anguish: Yggdras!" non-champion version can only be taken if "The Ring of Blood: The Final Challenge" is not rewarded');
```

**Comment by PolarCookie** [comment]
Closes https://github.com/TrinityCore/TrinityCore/issues/20780

**Comment by Killyana** [comment]
This is wrong as 12932 has 12974 as requirement

**Comment by PolarCookie** [comment]
@Killyana 
https://www.wowhead.com/quest=12974/the-champions-call#comments:id=665963
https://www.wowhead.com/quest=12974/the-champions-call#comments:id=1059238

12974 is a breadcrumb quest, and this ticket doesn't address that issue.
This issue was about Gurgthock offering both versions of Yggdras if you had already completed Ring of Blood, and in that case the non-champion version is disabled.

Reopen.

**Comment by PolarCookie** [comment]
![yggdras](https://user-images.githubusercontent.com/1158801/49694684-cf7fff00-fb8e-11e8-8c14-95f99ec75534.png)
@Killyana
