### ISSUE TITLE
[master/3.3.5] Achievement Reward Locales deDE

### ISSUE THREAD

**Issue by AlcDenat** [TrinityCore/TrinityCore#22761]
**Description:**
Add most achievement_reward_locale deDE locales for send mails.

Both alliance and horde mail.
https://gist.github.com/AlcDenat/a1f04663ff873e1a72262d812cdb85f8

**Branch(es):**
- [X] 3.3.5
- [X] master if/when https://github.com/TrinityCore/TrinityCore/pull/22764 gets merged

**TC rev. hash/commit:** 
6cb754ca4e6b

**Comment by Shauren** [comment]
master still has locales_achievement_reward table in old format
