### ISSUE TITLE
 Resurrection after release doesn't work in instances [new Issues][15$]

### ISSUE THREAD

**Issue by micckkk** [TrinityCore/TrinityCore#22762]
Description:
This should always work, but currently does so only outdoors. Select the spell, click the body of the dead character. The casting begins (and eventually ends), but the receiving player never gets the question about resurrection.
I know for sure this is faulty with the priest spell and I suspect it's the same for all other classes.

Expected behaviour:
Being able to recover body after a DC issue
Steps to reproduce the problem:
Step: Die by any circumstance
Step: Relog after being dead
Step: Try to recover body in your dead point or with a Spirit Healer
Branch(es):
3.3.5
TC rev. hash/commit:
https://github.com/TrinityCore/TrinityCore/commit/d10e42c049b56937fee442d04e38232b6fd66e4cTDB version:
335.64
Operating system: Win 10 x64

**Comment by jackpoz** [comment]
could you check if an older commit has the same issue ? also note that the hash you pasted doesn't exist in TC

**Comment by Razfury** [comment]
@jackpoz 
I think he meant this commit: d10e42c049b56937fee442d04e38232b6fd66e4c

**Comment by illfated** [comment]
Yes, the letters "TDB" became attached to the end of the issue commit link, likely caused by removal of all the original spacing & MarkDown codes from the TC issue template.

**Comment by Jinnaii** [comment]
Well, i can only confirm this...
I have digged trough a lot of functions to find a reason for this problem, but i couldnt identify it.

> BuildPlayerRepop()
> HandleCorpseQueryOpcode(WorldPacket & /*recvData*/) 
> HandleRepopRequestOpcode(WorldPacket& recvData)
> SetResurrectRequestData(WorldObject const* caster, uint32 health, uint32 mana, uint32 appliedAura)
> HandlePreventResurrection(AuraApplication const* aurApp, uint8 mode, bool apply)
> SendResurrectRequest(Player* target)
> EffectResurrectNew

The case here is - if a player releases himself as a ghost, you can only resurrect him (his dead body) if you and his ghost share the same mapID. 
It doesnt matter if this map is a dungeon or not (tested this by let the ghost take a ship transport from eastern kingdoms to kalimdor).

Maybe someone with more in-depth knowledge finds the time and interest to look into this issue.

**Comment by jackpoz** [comment]
>Shauren: Hint: Map::AddFarSpellCallback

**Comment by Jildor** [comment]
so, the problem is caused here: https://github.com/TrinityCore/TrinityCore/commit/080d2c6cd439acb2059adc4e24a279de98aa0db6

should be added here SPELL_EFFECT_RESURRECT_NEW like SPELL_EFFECT_SUMMON_RAF_FRIEND or what is the way?

**Comment by Shauren** [comment]
Im wondering if these far spell callbacks are actually safe...

**Comment by ForesterDev** [comment]
@Jildor it will not work, because m_caster->ToPlayer()->GetTarget() in case for SPELL_EFFECT_RESURRECT_NEW and SPELL_EFFECT_RESURRECT is null

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/cc71da35b5dc74abf71f8691161525a23d870bb5
