### ISSUE TITLE
[BUG] spell_bonus_data

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22778]
the world spell_bonus_data table have a lots of all , can't update!

example:
INSERT INTO `spell_bonus_data` VALUES (2061, 100, 0, -1, -1, 'Flash Heal');

.reload spell_bonus_data or restart worldserver .
Did not Change!

Branch: 3.3.5

TC rev: https://github.com/TrinityCore/TrinityCore/commit/d8fee3c46b70fed660aec905a496e56d6a327aaf
Operating system: debian

**Comment by PolarCookie** [comment]
Are you sure that `entry = 2061` exists? I can't find it in my own database.

**Comment by Killyana** [comment]
Looks like spell_bonus_data no longer changes bonus coefficients.

**Comment by Hir0shi** [comment]
dear @jackpoz
Can check , Can not add spell on spell_bonus_data .

example:
INSERT INTO spell_bonus_data VALUES (2061, 100, 0, -1, -1, 'Flash Heal');

server restart and again start ,  but spell Does not apply !!

**Comment by illfated** [comment]
issue title suggestion: **Core/Spells: DB table spell_bonus_data no longer changes bonus coefficients**

**Comment by Shauren** [comment]
Its working as intended, you are most likely hitting coef penalty for being too high level compared to the rank you are attempting to cast.
