### ISSUE TITLE
PowerShell script to automate TC setup

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#22779]
**Description:**

Create a PowerShell script that automates the TC setup, from binaries to MySQL to table setup.
The script should allow to choose between downloading binaries from AppVeyor or installing VS and building TC from the sources. It should allow to update existing TC setups too. It could save locally to a *.xml file the previous choices and ask if it should use the previous settings for update.
The targeted PowerShell version will be 2.0 (or try to at least) which is the default one shipped with Windows Server 2008 R2.
The development will be done at https://gist.github.com/jackpoz/6161c2872d9fd0527f506036ed5c5922 , keeping version control on Gist without requiring git to be installed (as the script itself is supposed to install git if required, so I need a VM without git).

Script flow (to be refined):
- [x] Ask between fresh install or update
  - [x] For fresh install
    - [x] Ask between AppVeyor or VS
      - [x] For AppVeyor
        - [x] Download the AppVeyor artifact zip
        - [x] Extract the zip
        - [x] Download VC++ runtime
        - [x] Install VC++ runtime
          - [ ] Check Windows version requirements
      - [ ] For VS
        - [ ] ...
    - [ ] Download TDB
      - [x] Upload a .zip version on GitHub to ease the extraction process, removing 7-Zip dependency
      - [ ] Verify that powershell has tls12 support, otherwise github download fails
    - [ ] Ask if MySQL is already installed
      - [ ] If yes
        - [ ] Get the "root" connection infos from user input
      - [ ] If no
        - [ ] Download MySQL version 5.x x64 (better if same version of AppVeyor)
        - [ ] Install MySQL
        - [ ] Either get the "root" connection infos from MySQL install or from user input
    - [ ] Create MySQL user
    - [ ] Create MySQL databases
    - [ ] Change config files with MySQL informations and set to automatically create the databases and apply db updates
    - [ ] Ask between using already extracted DBCs/Map/VMap/MMap or extract them
      - [ ] For existing ones
        - [ ] Copy them to the binaries folder
      - [ ] For extracting them
        - [ ] ...
    - [ ] Start authserver to create the database
    - [ ] Configure auth database with whatever is required
    - [ ] Start worldserver to create the databases
    - [ ] Configure character database with whatever is required (or through worldserver command prompt)
  - [ ] For update
    - [ ] ...

Slightly unrelated changes required:
- [ ] include all SQL scripts in AppVeyor artifacts
- [ ] include boost dll in AppVeyor artifacts

**TC rev. hash/commit:** d8fee3c46b70fed660aec905a496e56d6a327aaf

**Operating system:** Windows

Useful links and documentation:
- PowerShell Demo: Prompt for Choice https://social.technet.microsoft.com/wiki/contents/articles/24030.powershell-demo-prompt-for-choice.aspx
- Downloading AppVeyor build artifacts (PowerShell - basic example) https://www.appveyor.com/docs/api/samples/download-artifacts-ps/
- AppVeyor direct link to latest successfully built artifacts https://github.com/appveyor/ci/issues/403#issuecomment-180026470
- Direct link to AppVeyor TrinityCore binaries https://ci.appveyor.com/api/projects/DDuarte/trinitycore/artifacts/build/bin/TrinityCoreWin64VS2017.zip
- Extracting the content of a zip file in PowerShell 2.0 https://stackoverflow.com/questions/12165856/how-do-i-pass-option-flags-to-folder-copyhere-in-powershell

**Comment by jackpoz** [comment]
this will be a long journey, especially with PowerShell 2.0 which seems to be as complete as .NET 1.1

**Comment by Faq** [comment]
Why 2.0, but not to go for newest PowerShell Core 6.x?
https://4sysops.com/wiki/differences-between-powershell-versions/

**Comment by jackpoz** [comment]
>The targeted PowerShell version will be 2.0 (or try to at least) which is the default one shipped with Windows Server 2008 R2.

**Comment by Faq** [comment]
just saying Windows Server 2008 R2 SP1 supports also working with PowerShell Core 6.x

And if you read link I provided, then You know at least this:

> Does Windows PowerShell have a future?
> No, the future belongs to PowerShell Core. As things stand now, Microsoft will only provide bug fixes and security updates for Windows PowerShell. Only PowerShell Core will receive feature updates.

**Comment by jackpoz** [comment]
my point is, supporting the lowest powershell will allow anyone to just click the script without installing anything more

**Comment by jackpoz** [comment]
little update, now the binaries can be download from AppVeyor. Turns out the appveyor archive is 100 MB due to HUGE pdb files, and it's going to get bigger when I'll include all SQL updates files.

**Comment by illfated** [comment]
Best of luck with that, hope you don't run into anything major. 👍

**Comment by jackpoz** [comment]
Added the download of VC++ runtime(s), VC++ 14 is giving issues on WinServer 2008 R2 though and is not installing the required UCRT

**Comment by jackpoz** [comment]
Time has passed, now docker images seem to be the best way to skip building TC (or downloading binaries from appveyor)
