### ISSUE TITLE
[3.3.5] Koralon's loot (10n)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22777]
**Description:**
Koralon 10N (NPC 35013) is dropping item Savage Gladiator's Mooncloth Hood https://www.wowhead.com/item=41848 instead of Furious Gladiator's Dreadplate Legguards https://www.wowhead.com/item=40848

If I am not wrong, it should be:
(EDIT: I have found out that 34204 id reference is for PvE items and 34210 is for PvP items)
(EDIT 2: Corrected because I was not deleting 41848 (wrong item) and improved thanks to @illfated)
 ```sql
-- Furious Gladiator's Dreadplate Legguards
DELETE FROM `reference_loot_template` WHERE `Item` IN (40848, 41848) AND `Entry` IN (34204, 34210);
INSERT INTO `reference_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`) VALUES
(34210, 40848, 0, 0, 0, 1, 1, 1, 1);
 ```

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by illfated** [comment]
Recommended format / codestyle:
```sql
-- Furious Gladiator's Dreadplate Legguards
DELETE FROM `reference_loot_template` WHERE `Item` = 40848 AND `Entry` IN (34204,34210);
INSERT INTO `reference_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`) VALUES
(34210, 40848, 0, 0, 0, 1, 1, 1, 1);
```

**Comment by TheWinchesters** [comment]
@illfated always giving the best recommendations.

**Comment by Killyana** [comment]
Just the item must be updated no need of a delete/insert
``` sql
UPDATE `reference_loot_template` SET `Item`=40848 WHERE `entry`=34204 AND `Item`=41848;

**Comment by illfated** [comment]
Oh, Right. I forgot that the issue was only about replacing the item.

**Comment by TheWinchesters** [comment]
I did that first but then I thought that 34204 reference id was for PvE items and 34210 for PVP ones for a reason.

**Comment by illfated** [comment]
The `reference_loot_template` entries can be quite confusing.
Some times, they don't make much sense.
