### ISSUE TITLE
[3.3.5/Ruby Sanctum] Baltharus the Warborn moves while channeling Blade Tempest

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22773]
**Description:**
Baltharus the Warborn (https://www.wowhead.com/npc=39751/baltharus-the-warborn) moves in a strange way while channeling Blade Tempest (https://www.wowhead.com/spell=75125/blade-tempest).
He does not move his feet, but it is like he "slides" towards the character who has the aggro while channeling Blade Tempest.

**Steps to reproduce the problem:**
1. .go c id 39751
2. start combat
3. Run when he starts channeling Blade Tempest

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by Keader** [comment]
If i remember right, it's blizzlike.
He should walk while tempest keep, and animation is very weird when he do it.
I can check again in retail later, but pretty sure that it's "correct" behavior.

**Comment by TheWinchesters** [comment]
Trying to find some vid so you do not need to check it.
This one: https://www.youtube.com/watch?v=KEqrkLkq8pM is after 3.3.5a (2013 aprox) and in the first seconds you can still see Baltharus channeling Blade Tempest and "sliding".

**Comment by Keader** [comment]
Yeah, blizzlike :/

**Comment by illfated** [comment]
No worries, @TheWinchesters . it could happen to anyone.

**Comment by Keader** [comment]
Is always better do a little search before report.
But yes, no problem, can happens to anyone xD
