### ISSUE TITLE
[3.3.5/Ruby Sanctum] Halion (Shadow realm)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22774]
**Description:**
The Shadow realm version of Halion does not attack unless a player attack her first.
I think it is because her ReactState is "DEFENSIVE"

**Current behaviour:**
She stays there if nobody attacks her.

**Expected behaviour:**
She should attack instantly when players enter the shadow realm.

Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by Keader** [comment]
@sirikfoll it's indeed, no?

**Comment by Killyana** [comment]
The react must be "DEFENSIVE"
