### ISSUE TITLE
[3.3.5] Warlock: Haunt

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22786]
English version:
**Description:**
Haunt (https://www.wowhead.com/spell=48181/haunt):
"When the Haunt spell ends or is dispelled, the soul is returned to you, healing you for 100% of the damage it did to the target".

**Current behaviour:**
Haunt is not renewed if it is casted on a target that already has it.
Now, if you cast Haunt continually, when Haunt returns the heal effect, it will heal the sum of all the damage done by all the times that Haunt was casted on the objective before the effect ends.
EDIT: I think heal returned is too big to be just "the sum of the damage made by all the times that Haunt was casted".

**Steps to reproduce the problem:**
1. Pick some objective.
2. .cheat cooldown
3. Spam Haunt and wait till heal effect is returned to the caster

-------------------------------------------------------------------------------------------------------------
Spanish version:
**Descripción:**
Poseer tiene un efecto de sanación cuando se acaba o es disipado, sanando un 100% del daño infligido.

**Comportamiento actual:**
Poseer no se renueva en un target que ya lo tiene.
Si se lanza continuamente sobre el target, cuando Poseer en el objetivo se acabe, la sanación es la suma del daño de todos los "Poseer" que se han logrado lanzar en el objetivo antes de que se acabe el efecto.
Edit: Creo que la sanación que vuelve es algo más que sólo la suma del daño de todo los "Poseer" lanzados, porque es un número realmente grande.

**Pasos para reproducir el problema:**
1. Buscar un target
2. .cheat cooldown
3. Spamear Poseer hasta que devuelva el efecto de sananción

**Branch(es):**
Branch: 3.3.5
TC rev: 257ae44
OS: Win 8.1

**Comment by PolarCookie** [comment]
Sorta fixed in https://github.com/TrinityCore/TrinityCore/commit/a0999744ef02bf1494233411d873552d3d564d8a, haunt is not stacking the heal and refreshing duration properly, but when I refresh this happens
![wowscrnshot_111318_053616](https://user-images.githubusercontent.com/1158801/48391298-44822500-e706-11e8-8a9e-21ce99ddcb77.jpg)

**Comment by Langerz82** [comment]
Just by looking at the code it may seem that m_spellInfo->Speed is equal to 0 for Haunt. Can someone test this who has more knowledge? I don't want to just remove the conditional as I'm sure it's used for something.

**Comment by PolarCookie** [comment]
@Langerz82 this was fixed in https://github.com/TrinityCore/TrinityCore/pull/22794, but Haunt having 0 speed sounds weird, it's 20 in the DBC.

**Comment by Langerz82** [comment]
How do you obtain the spell in 335.
.levelup 90
.learn all my spells

It does not appear in the spellbook,either when I use .learn 48481.

Please advise.

**Comment by Langerz82** [comment]
The Fix:
```diff
diff --git a/src/server/scripts/Spells/spell_warlock.cpp b/src/server/scripts/Spells/spell_warlock.cpp
index 3629b2f1d2..2c3bda3a59 100644
--- a/src/server/scripts/Spells/spell_warlock.cpp
+++ b/src/server/scripts/Spells/spell_warlock.cpp
@@ -793,6 +793,10 @@ class spell_warl_haunt : public SpellScriptLoader
 
             void HandleRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
             {
+                AuraRemoveMode removeMode = GetTargetApplication()->GetRemoveMode();
+                if (removeMode == AURA_REMOVE_NONE)
+                    return;
+
                 if (Unit* caster = GetCaster())
                 {
                     CastSpellExtraArgs args(aurEff);
```

**Comment by TheWinchesters** [comment]
@Langerz82 
I have tried that one and it works nice.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ec3cb05d7fbc5cef60d000af910dc39dd3af92bf
