### ISSUE TITLE
Crashe trainer_spell (bfa branch)

### ISSUE THREAD

**Issue by ReyDonovan** [TrinityCore/TrinityCore#22787]
**Description:**

crache load server

CHANGEME Description of the problem or issue here.

1) add spell trainer_spell table https://www.wowhead.com/spell=264578/leatherworking
2) crashe load server
```
d:\trinitycore\src\server\game\globals\objectmgr.cpp:8677 in ObjectMgr::LoadTrainers ASSERTION FAILED:
  spell.LearnedSpellId == spell.SpellId Only one learned spell is currently supported - spell 264578 already teaches 2108 but it tried to overwrite it with 264577
```

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

**Branch(es):** bfa

**TC rev. hash/commit:** d087f113ca831efb28810e08be68385f871687a8

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by Shauren** [comment]
This is during startup and I know about it

**Comment by welder1976** [comment]
played just a hack
