### ISSUE TITLE
[Spell] Bug [Death Wish]

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22790]
Description: Warrior Class, Spell [Death Wish]
This spell should be active for 30 seconds but it goes after 2 seconds, if  Warrior hit Attack.

https://wotlk.evowow.com/?spell=12292

for 30sec stats
lncrases physucal damage by 20%
lncrases all damage taken by 5%

Branch: 3.3.5
TC rev: https://github.com/TrinityCore/TrinityCore/commit/d8fee3c46b70fed660aec905a496e56d6a327aaf
Operating system: debian

**Comment by Hir0shi** [comment]
@jackpoz 

can u fixed?

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21880

**Comment by jackpoz** [comment]
I don't do spell fixes
