### ISSUE TITLE
DB/Quest: Shimmer Stout

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22797]
**Description:**
Quest Rejold's New Brew is only a reminding breadcrumb quest for Shimmer Stout.
Shimmer Stout does not require Rejold's New Brew.
https://www.wowhead.com/quest=415/rejolds-new-brew#comments:id=190337

```sql
UPDATE `quest_template_addon` SET `PrevQuestID` = 315 WHERE `ID` = 413;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=415;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19, 0, 415, 0, 0, 14, 0, 413, 0, 0, 0, 0, 0, "", 'Quest "Rejold\'s New Brew" can be be accepted if quest "Shimmer Stout" not taken/rewarded');
```

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
bc1f456125c1b6c90617a514152d69c40ce64886

**Comment by Killyana** [comment]
Relate to https://github.com/TrinityCore/TrinityCore/issues/22264

**Comment by Aokromes** [comment]
needs to be fixed by https://github.com/TrinityCore/TrinityCore/issues/22264
