### ISSUE TITLE
[BfA] DB/Quest: Quest POI data

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#22791]
**Description:**

Bruteforced Quest POI data for the following tables:
- quest_poi
- quest_poi_points

Will add quest_template, creature_template + locales aswell in the next few days.

**Current behaviour:**

-

**Expected behaviour:**

-

**Steps to reproduce the problem:**

-

**Branch(es):**

bfa

**TC rev. hash/commit:** 

1423d3e7f36d9601060c1cc89171801609aad352

**Operating system:** -

**Suggested fix:**

NOTE: I'm using truncate since this is a full bruteforce with all data.

https://gist.githubusercontent.com/mdX7/0003901ca68a7a3b6f2a6b72a6d6542a/raw/ba952b49504a771eccd6145ddf75d612102d9567/quest_poi.sql

**Comment by ReyDonovan** [comment]
thx ModoX

**Comment by funjoker** [comment]
someone pushing that?
