### ISSUE TITLE
Death Comes From On high

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#22802]
**Description:**
spells and such have been fixed for the eye,
However it does not yet launch to its destination, and for some reason u can only move in 4 directions, not up and down, which is mandatory for the quest.
Video of how it should work; https://www.youtube.com/watch?v=9V8KWMMa0aU

**Current behaviour:**

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

The eye should launch to the location in the video and controlling it should be restricted untill the location is reached.

**Steps to reproduce the problem:**

1. Compile latest revision of the core /  launch realm
2. Make a DK
3. Accept and initiate the quest.

**Branch(es):**

3.3.5 - Not sure for other branches.

**TC rev. hash/commit:** 
bc1f456125c1

**Operating system:** WIN64

**Comment by yvomsx** [comment]
if this is a core fix, would data.SetOpcode(SMSG_MOVE_SET_CAN_FLY); do the job?

**Comment by yvomsx** [comment]
https://github.com/TrinityCore/TrinityCore/pull/22091/commits/3d816edef44e50cde57e33b38433471798fb3171

The event does start but does not do anything else but saying the eye is being launched, it does not actually launch to its destination, u have to manually fly there ??

**Comment by Killyana** [comment]
I don't know, 3.3.5 core is no longer playable, it's the worst TC core since maybe ever.
Trying to fix scripts that was working correctly before changes done on core side is not the correct way.

**Comment by yvomsx** [comment]
it seems the events bug out however thanks @Killyana

**Comment by yvomsx** [comment]
Update :: https://youtu.be/69SjQW9mZrU
This is the current behaiviour.

among this there are some other minor bugs in chapter1.cpp
The chains supposed to be linked to the initiates are not working either,
However will open a new issue for this,

**Comment by RedSonja** [comment]
I have no idea ofc but would it be possible to revert 3.3.5's core back to when it did work right, and somehow keep the Characters db from being a total mess?

**Comment by yvomsx** [comment]
@RedSonja Do u remember when that was?
As i can tell right now it seems MovementInform is never being called.

**Comment by RedSonja** [comment]
Sorry for the delay in response.  
I had not updated for years because so much was working. The only reason I finally did was for the Gunship Battle, really trying to revert back to this.  db_version 335.52 and core_revision le75celf36ed+

Not sure that will help you but I am going back if at all possible.

**Comment by IllInuz** [comment]
10$ to whoever fixes this.

**Comment by Sorikoff** [comment]
Does #22794 resolve this problem?

**Comment by IllInuz** [comment]
What does that have to do with the event timer not being called? @Sorikoff

**Comment by Sorikoff** [comment]
It worked before modifications made to spells system.

**Comment by illfated** [comment]
@IllInuz : some of the older scripts (like `npc_eye_of_acherus`) contain timers which may not work as intended now.

**Comment by Sorikoff** [comment]
Looks to me that for somewhat reason move path is called, but no movement happens. Any ideas?

**Comment by illfated** [comment]
Could very well be that IllInuz is correct in his comment https://github.com/TrinityCore/TrinityCore/issues/22802#issuecomment-451611229
> As i can tell right now it seems MovementInform is never being called.

This script used to work a year or 2 ago, but recent changes to the core also changed this.

**Comment by IllInuz** [comment]
current revision b1545e76ef4e 2019-03-03 12:48:52 +0100
Still not calling MovementInform

**Comment by Sorikoff** [comment]
> Looks to me that for somewhat reason move path is called, but no movement happens. Any ideas?

Never mind. Not related just as MovementInform.

**Comment by IllInuz** [comment]
I guess ill do more debugging, ill start with the various events.

**Comment by qyh214** [comment]
confirm in e4a1556e09ea38ece9a76b0d190d2b2f29bf5bb9 

and also the eye moves is too slowly!
