### ISSUE TITLE
Blinking causes falling trough map

### ISSUE THREAD

**Issue by yvomsx** [TrinityCore/TrinityCore#22803]
**Description:**
In some occasions when a player is to cast blink on a surface that is higher then the player, lets say for example he is standing infront of a mountain, or is in the water, lower then the ground surface, and the player casts blink pointing to the surface, he is likely to fall trough the world, cause he litterly blinked trough the floor.

CHANGEME Description of the problem or issue here.
Blink and maps dont go well together.

**Current behaviour:**
It causes blink to fall trough the floor in certain situations.

**Expected behaviour:**
blink should be casted the regular way and if blocked by anything in its way it should stop infront at that point.

**Steps to reproduce the problem:**

1. Create a mage, and learn blink, or just learn spellid = 1953
2. Cast it facing a mountain forcing yourself to go trough it.
3. You will fall trough the world.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 

bc1f456125c1b6c90617a514152d69c40ce64886

**Operating system:** WIN64

**Comment by Aokromes** [comment]
#21255
