### ISSUE TITLE
DB/Quest: Kim'Jael Indeed

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#22809]
**Description:**
All 4 quest items drop on the first crate looted every time.
https://www.wowhead.com/quest=3601/kimjael-indeed

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
bc1f456125c1b6c90617a514152d69c40ce64886

**Comment by illfated** [comment]
Based on the comments in https://www.wowhead.com/quest=3601/kimjael-indeed#comments ,
I think there should be less than 100% drop chance, but maybe not _much_ less than 50% -- seeing that some players got 2 or 3 from the same crate.
```sql
SELECT * FROM `gameobject_loot_template` WHERE `Item` IN (10715,10717,10718,10722);
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
 9677   10715          0     100              1         1        0         1         1  (NULL)
 9677   10717          0     100              1         1        0         1         1  (NULL)
 9677   10718          0     100              1         1        0         1         1  (NULL)
 9677   10722          0     100              1         1        0         1         1  (NULL)
```
Then again, out of all the players who found this quest, they could have found more than 1 crate without quest items.
