### ISSUE TITLE
On centos6 complie error compiler feature "cxx_alias_templates" is not known to CXX compiler

### ISSUE THREAD

**Issue by darkz1984** [TrinityCore/TrinityCore#22813]
**Description:**

I complie trinitycore on centos 6 follow the wiki page,but when I run: 
cmake ../ -DCMAKE_INSTALL_PREFIX=/data/tmp/server
return me some error:

> -- CXX target worldserver cotired without unity build.

> -- Configuring done
> CMake Error in dep/g3dlite/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/recastnavigation/Detour/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/recastnavigation/Recast/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/fmt/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/jemalloc/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/jemalloc/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/gsoap/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in dep/libmpq/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/common/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/database/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/shared/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/game/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/authserver/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/scripts/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/server/worldserver/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/tools/map_extractor/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/tools/vmap4_assembler/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/tools/vmap4_extractor/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.
> 
> 
> CMake Error in src/tools/mmaps_generator/CMakeLists.txt:
>   The compiler feature "cxx_alias_templates" is not known to CXX compiler
> 
>   "GNU"
> 
>   version 4.4.7.

**Steps to reproduce the problem:**

follow the wiki page and run to  cmake ../ -DCMAKE_INSTALL_PREFIX=/data/tmp/server

**Branch(es):**

tag: TDB 335.64
I use
git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git
get the version

**TC rev. hash/commit:** 
maybe：
commit bc1f456125c1b6c90617a514152d69c40ce64886
**Operating system:** 
Centos6

**Comment by Aokromes** [comment]
centos 6 is extremely outdated package wise, i recommend you to switch to debian 9, if you want to continue with it, install clang.
