### ISSUE TITLE
[3.3.5] [Pilgrims Bounty] Achievement - The Turkinator 

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22818]
**Description:**
Achievement: https://www.wowhead.com/achievement=3578/the-turkinator
NPC: https://www.wowhead.com/npc=32820/wild-turkey
Aura: https://www.wowhead.com/spell=62014

**Current behaviour:**
The aura 62014 does not stack.
Every time the player kills a wild turkey, the buff is removed and added again.
Even if aura 62014 is casted 40 times using commands, the achievement is not triggered.
According to this commit 529899675ab3ef58c7c564bd17e0339bcbbddc23, there is a switch case handling this achievement, but it looks like the switch is never reached.

**Expected behaviour:**
Aura 62014 should stack for every wild turkey killed and Achievement 3578 should trigger after killing 40 wild turkeys in 30 seconds or less.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
bc1f456125c1b6c90617a514152d69c40ce64886

**Operating system:**
Win 8.1

**Comment by jackpoz** [comment]
maybe one of the latest stacking aura commits broke it ? could you (or anyone) check if it works with an older commit ?

**Comment by TheWinchesters** [comment]
Using rev: 5b99ce2f83036a685a93f597f63d4ec914be6970 → Issue is present
Should I use a older one?

**Comment by illfated** [comment]
Yes, please do. Something like 4 - 5 months old core could be interesting. (Just remember we used to have some creature movement issues then.)

**Comment by Killyana** [comment]
the aura is not tacking just a new one is added:
``` 
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 0 duration: 109733 maxduration: 180000   caster: creature guid: 2330
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 1 duration: 118787 maxduration: 180000   caster: creature guid: 2325
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 2 duration: 137285 maxduration: 180000   caster: creature guid: 2324
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 3 duration: 150695 maxduration: 180000   caster: creature guid: 2862
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 4 duration: 157130 maxduration: 180000   caster: creature guid: 2863
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 5 duration: 167915 maxduration: 180000   caster: creature guid: 2878
id: 25281 [Marqueur de dinde] effmask: 1 charges: 0 stack: 1 slot 6 duration: 171567 maxduration: 180000   caster: creature guid: 2870

**Comment by illfated** [comment]
- https://woehead.way-of-elendil.fr/?spell=62014/turkey-tracker

Will it need to be updated in
https://github.com/TrinityCore/TrinityCore/blob/69fd5d0d8f8449082dd7667cf496c573b3516fe5/src/server/scripts/Spells/spell_holiday.cpp#L595-L665
... or does will it need adjusting in how it is handled in the DB?
( ... or does it need extra scripting for the spell 62014? )
