### ISSUE TITLE
[3.3.5] Round Robin/Group Loot does not apply to quest items

### ISSUE THREAD

**Issue by kartoffelsup** [TrinityCore/TrinityCore#22829]
**Description:**

As far as I remember, quest items were a part of group loot/round robin rules in WOTLK. However,
on _352c4a4_ with _2018_11_21_00_world.sql_ one is able to 'steal' another group members quest item (even though he is the 'round_robin_player')

**Current behaviour:**

If in a group with another player with both having the same quest where specific items need to be looted from creatures (i.e. [Lynx Collar](https://www.wowhead.com/item=20797/lynx-collar)  for Quest [Unfortunate Measures](https://www.wowhead.com/quest=8326/unfortunate-measures)), if a quest item drops and the Loot Mode is set to 'Group Loot', the _non-round_robin_player can_ 'steal' the quest item from the _round_robin_player_.

**Expected behaviour:**

AFAIR, only the round_robin_player should be able to receive the quest item as long as they still need it.

**Steps to reproduce the problem:**

1. Start 2 Clients
2. Create BloodElf on Client1
3. Create another BloodElf on Client2
4. Group them up
5. Make sure Loot Type is set to Group Loot
6. Accept Quest [Unfortunate Measures](https://www.wowhead.com/quest=8326/unfortunate-measures) on both
7. Kill a [Springpaw Cub](https://www.wowhead.com/npc=15366/springpaw-cub)
8. Notice how the _non-round_robin_player_ can steal the [Lynx Collar](https://www.wowhead.com/item=20797/lynx-collar) from the _round_robin_player_.

**Branch(es):**

3.3.5

**TC rev. hash/commit:**  352c4a4

**Operating system:** Manjaro Linux x64

**Comment by illfated** [comment]
Aren't they separate loot categories? Or did I miss something important?
In my game client, I see the following loot methods:
- Loot: Free for All
- Loot: Round Robin
- Loot: Master Looter
- Loot: Group Loot
- Loot: Need Before Greed

(only the group leader can see more than the active method)

**Comment by kartoffelsup** [comment]
I saw in the code that the field 'round_robin_player' is being used for both Group Loot and Round Robin.
Though to be frank, I have never used Round Robin ever, so I guess I can only provide info on Group Loot in this case.

**Comment by Shauren** [comment]
I don't know. I thought quest items were supposed to be FFA (unlimited copies) for entire group (with the exception of raid quests like shadowmourne)

**Comment by Killyana** [comment]
It depends if the item ha the Flags=2048 "Item is party loot and can be looted by all"
I'm not sure about only "round_robin_player" could loot the item.
If it's the case imagine the player number one completed the quest (have required Lynx Collar int he inventory) and he will help player number 2 to finish the quest, in this case killed npc tague for player number 1 will not show the item for player 2.

**Comment by kartoffelsup** [comment]
> I don't know about this. I thought quest items were supposed to be FFA with unlimited copies for entire group (with the exception of raid quests like shadowmourne) - and that is how it works for as long as I played on retail (that is cata)

I think this is especially the case in Legion/BFA. But if my memory doesn't fail me, this was not true for WOTLK. Most of the quest items were actually bound to the 'round_robin_player', unless they had finished the quest/are not on the quest.

**Comment by Shauren** [comment]
The thing you need to always keep in mind is that wiki writers do not know anything about how most of the stuff works under the hood and especially they do not know about various item flags such as the one mentioned earlier ITEM_FLAG_MULTI_DROP.
So do not go by "quest item or not" but rather just check the flag

**Comment by Killyana** [comment]
Confirm, if there's a quest item dropped by the npc, the corpse could be loot by any member that need this item (but only the quest item will be visible for this players).

According to many sources the corpse must turn lootable and show the quest item only if the player tagged that own the loot doesn't require the quest item.

**Comment by CraftedRO** [comment]
I guess this can be closed meanwhile.
