### ISSUE TITLE
[3.3.5a] Network Issue or Simular

### ISSUE THREAD

**Issue by simple4dev** [TrinityCore/TrinityCore#22827]
**Description:**

Well, im leading a project for few years now, having 400 players online under the working days, 600-700 at weekend. After many years of using the same core, ive made an massive update, servers and etc run fine took a while. But guess what? i lost 200 players cus the server dont restart i have perment downtimes over half hours or smth till the msg arrive me that the servers dont come up. Thanks, someone of TC Devs owe me 500$ donations per month from beeing unable to commit working changes. I mean what the fuck is this useful if u cant even restart the thing? TC became uninteresing just now. Thanks, i further take bugs then a offline server.

**Current behaviour:**

Updated to 352c4a4c680c94fc9fbc725c51135667662f1c77

On Restart/Shutdown/Crash/Usage of TrinityCore:
Failed to initialize Network
StartNetwork failed to bind socket acceptor

Everything sucks, servers dont restart i loose more and more players cant babysit the fking console im a working dude.

**Expected behaviour:**

WORKING REBOOT PROGRESS

**Steps to reproduce the problem:**

Pff.... How should i know im not a dev, but maybe if you have already open Issues about that, why dont you fix it.. Or better... dont make the mistakes and LEAVE IT AS IT IS... or dont you use the executeables yourself??? Everything else then fun here... TrinityCore was ever the Core you could use with the lowest problems... now... it doesnt even restart... all the bugfixes now doesnt matter anymore since noone play a server with that hell of downtimes

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

352c4a4c680c94fc9fbc725c51135667662f1c77

**Operating system:**
Linux Debian 9.10 64bit minimal

**Comment by Aokromes** [comment]
#20032

**Comment by Aokromes** [comment]
you don't paid a single cent to trinitycore, also:


  Also, for each author's protection and ours, we want to make certain
that everyone understands that there is no warranty for this free
software.  If the software is modified by someone else and passed on, we
want its recipients to know that what they have is not the original, so
that any problems introduced by others will not reflect on the original
authors' reputations.

**Comment by simple4dev** [comment]
self-protection.. Instead of rework it.. ive been browsing. sry for 800th post this... May work on it then leave people with it alone?

**Comment by simple4dev** [comment]
and ur post tell me ur money hungry as fuck.. do i need to pay that you fix your mistakes (dont know who made the terrible update that stops a working restarting on any kind of way)

**Comment by simple4dev** [comment]
but hey..... sry for the spamm. Its Closed? Means u fixed it? or do you just try to block the truth not be shown as Open Issue?

**Comment by Jildor** [comment]
@simple4dev he's ref issue: #20032
so, maybe this is closed because it's duplicated

**Comment by illfated** [comment]
Correct. Duplicate issue. Search for existing issues before opening new tickets.
