### ISSUE TITLE
[3.3.5] The Eye: Kael'thas Sunstrider (Mind Control)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22826]
**Description:**
During the encounter, Kael'thas Sunstrider (https://www.wowhead.com/npc=19622) casts Mind Control (https://www.wowhead.com/spell=36797).

**Current behaviour:**
He controls everyone in the raid, making impossible to defeat him.

**Expected behaviour:**
It should be: Mind controls 2-3 people in the raid.

Info:
http://wowwiki.wikia.com/wiki/Kael%27thas_Sunstrider_(tactics)
https://www.wowhead.com/npc=19622/kaelthas-sunstrider#comments:id=112215

Branch(es):
3.3.5

TC rev. hash/commit:
bc1f456

Operating system:
Win 8.1

**Comment by illfated** [comment]
Seems to me that identical auras are copied to every player, as well as removed from every player, when any spell is cast on players (as long as one of the spell effects is supposed to add or remove auras on player(s)).

**Comment by TheWinchesters** [comment]
I think that happens because this:
`DoCastAOE(SPELL_MIND_CONTROL, true);`
(Or I am really wrong)

**Comment by killerwife** [comment]
-- Kael MC should only hit 3 targets
UPDATE `spell_template` SET `MaxAffectedTargets`=3 WHERE `Id`=36797;
Or whatever equivalent TC uses. Confirmed through extensive research on Kael.

**Comment by Keader** [comment]
0ee8a77dce32a5bc057bd4c8caa309be6963e7bf
Ty Jildor
