### ISSUE TITLE
[3.3.5] ToC10/25: Dreadscale & Acidmaw (Slime Pool)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22837]
**Description:**
Slime Pool:
Spawns Slime Pool underneath the jormungar's body. The Slime Pool grows in size for 30 seconds and inflicts ~2,000 Nature damage every 1 second to players standing in it.

Used by:
Dreadscale https://www.wowhead.com/npc=34799/dreadscale
Acidmaw: https://www.wowhead.com/npc=35144/acidmaw

**Current behaviour:**
Slime Pool has not visual effect on the ground.

**Expected behaviour:**
Slime Pool should have a visual effect on the ground, a green green smoke in a circular shape.
A video just for visual explanation: https://www.youtube.com/watch?v=I_H8KiUhBy8

Branch(es):
3.3.5

TC rev. hash/commit:
bc1f456

Operating system:
Win 8.1

**Comment by Keader** [comment]
Dup of #21660
