### ISSUE TITLE
[BfA] DB/Hotfixes: Updated broadcast_text data from 8.0.1 (+ locales)

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#22832]
**Description:**

Bruteforce data for broadcast_text & locales.

**Branch(es):**

bfa

**TC rev. hash/commit:** 

947771e6bdbeaa8788c373e0659cd8ca95cd96f2

**Suggested Fix:**

enUS: https://gist.githubusercontent.com/mdX7/f447a857d3bccde6d0e15afbcc3a7ce7/raw/b0dd616edaa5744f2447f29f18b57a5c3c80329e/28153_enUS_broadcast_text.sql

Locales
deDE: https://gist.githubusercontent.com/mdX7/0bd49450701b9ceec40035e3cf202dae/raw/1ec8534f8cd9f429b16903df94ddf43f5e1c66b8/28153_deDE_broadcast_text_locales.sql
esES: https://gist.githubusercontent.com/mdX7/196236a4b7896a97724ee3ed88d52b0e/raw/5dc11790dc9e86439af985fb5321bad3db6da852/28153_esES_broadcast_text_locales.sql
esMX: https://gist.githubusercontent.com/mdX7/aeb09b195cdd820b595207bb3eefb22e/raw/3698aa62e836be1cfa66c5481ef271aa6e69c7e5/28153_esMX_broadcast_text_locales.sql
frFR: https://gist.githubusercontent.com/mdX7/38682371b37e9aead6c736f52d22842f/raw/8409c3f72871dbf2be2219310e1a8802e254649e/28153_frFR_broadcast_text_locales.sql
itIT: https://gist.githubusercontent.com/mdX7/1f1e05241e7f71393124faf6c06498a4/raw/23c5bd12fa08f171520440820a74c5400942435a/28153_itIT_broadcast_text_locales.sql
koKR: https://gist.githubusercontent.com/mdX7/0d453c09b9fd58de8bf3746a5ec5bbf6/raw/65c01c678ba7677cef743618cdcbd2fbfb5f9af8/28153_koKR_broadcast_text_locales.sql
ptBR: https://gist.githubusercontent.com/mdX7/ea5620d3fa606fdca165bf298761733b/raw/900097382e2731711b9519873b9fc5b63c7eb81b/28153_ptBR_broadcast_text_locales.sql
ruRU: https://gist.githubusercontent.com/mdX7/ff1196490ed246eaca4fdecddab7320d/raw/c2e51125c6582d2f61bfd759f929f0fb76455ff4/28153_ruRU_broadcast_text_locales.sql
zhCN: https://gist.githubusercontent.com/mdX7/45993bba60095fd34cc3edeae49d3ad3/raw/09a133146d5e4a80d6397c59ceef79b57cb764a3/28153_zhCN_broadcast_text_locales.sql
zhTW: https://gist.githubusercontent.com/mdX7/3ce61c92086790d8fbb95e5d959107b9/raw/306a3046719bcabe5ca63b79579cc394face83db/28153_zhTW_broadcast_text_locales.sql

**Comment by funjoker** [comment]
someone willing to merge that?
