### ISSUE TITLE
[BfA] Assertion failed: pointer LookupEntry(id)

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#22834]
**Description:**

I have hotfixed map 1955 to not be a dungeon (map type in map.db2), and now when teleporting to it, worldserver displays the following message and crashes:

![image](https://user-images.githubusercontent.com/35412834/49106736-e283fc80-f27b-11e8-99d8-0c7e34d65549.png)

Crash log:
[947771e6bdbe_worldserver.exe_[27-11_19-25-39].txt](https://github.com/TrinityCore/TrinityCore/files/2621587/947771e6bdbe_worldserver.exe_.27-11_19-25-39.txt)

I have tried copying map flags and the MapDifficulty entry from Eastern Kingdoms, and also removed the instance_template entry (which I had created myself prior to that). None of this helped.

**Branch(es):**

BfA

**TC rev. hash/commit:** 

TrinityCore rev. 947771e6bdbe 2018-11-25 14:28:44 +0100 (bfa branch) (Win64, RelWithDebInfo, Dynamic)

**Operating system:** Windows 10

**Comment by Shauren** [comment]
I have a feeling your hotfix data in map table is bad (in a column other than type)

**Comment by Smerdokryl** [comment]
@Shauren WDBX does sometimes mess columns up when exporting, but I did check and it looks all right. 

`1955	ScenarioIslandsTutorial	Неизведанный остров					0	0	1	0	0	0	549	4095	4095	-1	0	1	2047	0	159399517	262160	0	12	28153`

The 4095, 4095 would make more sense in ParentMap and CosmeticParentMap (even though this map doesn't even exist, like what the hell), but I triple-checked it with DB2defines.h and the original DB2 and it seems correct

**Comment by Shauren** [comment]
WDBX gave you completely wrong values. both ParentMap columns are really -1

**Comment by Smerdokryl** [comment]
@Shauren The arctium viewer would suggest that TimeOfDayOverride and ParentMapID are -1, and CosmeticParentMap is 65535.

Is there a reliable tool to read db2s that you can recommend?

**Comment by Shauren** [comment]
No, but in the debugger you can do this
![obraz](https://user-images.githubusercontent.com/297439/49117870-854f7180-f2a2-11e8-98e8-bac15865ebca.png)

**Comment by Smerdokryl** [comment]
Thank you, that's quite useful
