### ISSUE TITLE
[3.3.5] Quest: Cruel's Intentions

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22842]
**Description:**
It is not possible to have the quest Cruel's Intentions https://www.wowhead.com/quest=10136 from the NPC.
PrevQuest Required is 10390 but even if this one is rewarded, NPC 3230 does not offers the quest 10136.
I have tried doing all the quests that the wowhead comments say.
Is it deprecated or something?

Branch(es): 3.3.5
TC rev. hash/commit: bc1f456
Operating system: Win 8.1

**Comment by illfated** [comment]
TrinityCore rev. 352c4a4c680c 2018-11-21 22:37:58 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Confirmed, Nazgrel has not offered me the quest "Cruel's Intentions" for as long as I can remember.

No, the quest is not in the `disables` table, so it is not disabled there.
`creature_queststarter` & `creature_questender` contain the following:
```
  id   quest
----  ------
3230   10136
```
So, the quest + NPC is present in both those tables. Let's check all the other tables too.

**Comment by Aokromes** [comment]
https://i.imgur.com/7pTRAK5.png

**Comment by illfated** [comment]
Mission: Kill the Messenger (Horde) - (https://wow.gamepedia.com/Mission:_Kill_the_Messenger_(Horde))

    The subject of this article or section did not make it out of the beta stages of World of Warcraft or its expansions.
    The in-game information in this article or section is kept purely for historical purposes.

Mission: Be the Messenger (Horde) - (https://wow.gamepedia.com/Mission:_Be_the_Messenger_(Horde)

    The subject of this article or section did not make it out of the beta stages of World of Warcraft or its expansions.
    The in-game information in this article or section is kept purely for historical purposes.

**Comment by Killyana** [comment]
Cruel's Intentions is the last quest.

The chain must be like this:

Felspark Ravine
Forward Base: Reaver's Fall
Disrupt Their Reinforcements
Mission: Gateways Murketh and Shaadraz
Mission: The Abyssal Shelf
Return to Thrallmar
Forge Camp: Mageddon
Cannons of Rage
Doorway to the Abyss
Cruel's Intentions
--
Doorway to the Abyss + Vile Plans
The Agony and the Darkness

Just this is needed
``` sql
UPDATE `quest_template` SET `RewardNextQuest`=0 WHERE `ID`=10135;
UPDATE `quest_template_addon` SET `NextQuestID`=0 WHERE `ID`=10135;

**Comment by illfated** [comment]
OK, so if I have got all 3 (Doorway to the Abyss, Vile Plans, The Agony and the Darkness) as rewarded on my character, but not Cruel's Intentions, is that just because Cruel's Intentions was chained to quests that were only available during the TBC beta and therefore blocked? I would have thought that there should be some kind of requirement for the last 3 to be available only if Cruel's Intentions is complete (but I have probably overlooked something).
