### ISSUE TITLE
Dungeon finder

### ISSUE THREAD

**Issue by RedSonja** [TrinityCore/TrinityCore#22850]
Dungeon Finder not working.

I am not sure if this is the correct place to put this or not, but the Dungeon Finder does not work at all for me.

Every player is locked out of every dungeon even if they have never been in any of the ones in the Dungeon Finder. I have looked but this was the only thing I could find related to it. For me, it has not worked for years. 
Just wondering if it has anything to do with this disable map you are talking about, and if that was put into the core on Nov 25, 2016, then shouldn't it be working now?

**Current behaviour:**
Everyone is locked out.

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**
People put in their skill ie, dps, tank, healer click on dungeon you want into and it summons you all there.

**Steps to reproduce the problem:**
Open dungeon finder put in your skill and see the locks on every dungeon.

**Branch(es):**

3.3.5, is the only one I know about.

**TC rev. hash/commit:** 
257ae44

**Operating system:**Win10

**Comment by Aokromes** [comment]
it's working for me on 
[17:53:45] TrinityCore rev. 606fbc248223 2018-12-08 13:10:50 +0100 (3.3.5 branch) (Unix, None, Static)

**Comment by RedSonja** [comment]
I retested it on a different account and it works with an admin account, but not any other.

**Comment by jackpoz** [comment]
Do they have the required gear score ? Got a screenshot of the locked out dungeon finder ?

**Comment by jackpoz** [comment]
What is your DungeonFinder.OptionsMask setting ?

**Comment by RedSonja** [comment]
> What is your DungeonFinder.OptionsMask setting ?
Is set at = 1 should I change it to 3 maybe?
![wowscrnshot_120918_101454](https://user-images.githubusercontent.com/581124/49699814-7b2f4c00-fb9b-11e8-9315-c850d3ce9627.jpg)

**Comment by RedSonja** [comment]
Ok I am not sure how yours works Aokromes but I pulled a clean clone and as of commit  df641e9 on 12-9-18 it does not work, and the setting in config is set to DungeonFinder.OptionsMask =1.  The only way I can see it with any dungeons open is if I am on an admin account.

**Comment by RedSonja** [comment]
Thank you TheWinchesters I will check that out you have been most helpful, again thank you.
