### ISSUE TITLE
Connection Patcher not compile for BFA 8.0.1.28153

### ISSUE THREAD

**Issue by mindevis** [TrinityCore/TrinityCore#22855]
**Description:**

In latest commit not compile connection patcher
Tested in Windows 10 and Ubuntu Server 18.04 LTS

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e9bcae1fada64bc3400c3204f7365edcecd640cc

**Operating system:** CHANGEME OS
Windows 10 x64
Ubuntu Server 18.04 LTS

**Comment by Aokromes** [comment]
there is no connection patcher.

**Comment by mindevis** [comment]
For BFA 8.0.1 do not need connection patcher?

**Comment by mindevis** [comment]
to me, already aokromes said about the launcher, thank you.

**Comment by iamchenxin** [comment]
What's this launcher solution? Should it means Arctium Launcher?

**Comment by iamchenxin** [comment]
> There will be a launcher solution

I try "Arctium Launcher" with 8.0.1.28153 many times, but still get "Authentication failed for account" in mac. It is okay in windows. The 8.0.1.28153 app i used is from Nazmir and Firestorm. Both failed with Arctium. 
What's the right way to make 8.0.1.28153 app work in mac.

**Comment by Shauren** [comment]
Mac clients are at this point not supported.
