### ISSUE TITLE
[master][crash] Worldserver crash on spell.cpp:1193

### ISSUE THREAD

**Issue by maryus101** [TrinityCore/TrinityCore#22869]
World server crashes on accessing spell.cpp:1193

**Branch(es):**

master

**TC rev. hash/commit:** TrinityCore rev. e9bcae1fada6 2018-12-09 16:07:38 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows 7 Pro x64

Crash log:
[e9bcae1fada6_worldserver.exe_[15-12_17-37-37].txt](https://github.com/TrinityCore/TrinityCore/files/2683801/e9bcae1fada6_worldserver.exe_.15-12_17-37-37.txt)

**Comment by illfated** [comment]
Not sure if `RelWithDebInfo` will give TC coders enough info to find the cause of your crash, but I will leave it to them to decide.
Anyway, here is a shortcut to the line you mentioned:
https://github.com/TrinityCore/TrinityCore/blob/e9bcae1fada64bc3400c3204f7365edcecd640cc/src/server/game/Spells/Spell.cpp#L1190-L1195

**Comment by maryus101** [comment]
TrinityCore rev. 80c3304daf8a 2018-12-18 12:50:15 +0100 (master branch) (Win64, Debug, Static)

Crashlog from debug:


[80c3304daf8a_worldserver.exe_[20-12_11-40-2].txt](https://github.com/TrinityCore/TrinityCore/files/2698267/80c3304daf8a_worldserver.exe_.20-12_11-40-2.txt)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18558
