### ISSUE TITLE
[3.3.5] The Brothers Bronzebeard (phasing problem)

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22867]
**Description:**
After completing the quest chain from quest 12871 https://www.wowhead.com/quest=12871/aid-from-the-explorers-league to quest 12973 https://ultimowow.com/wotlk/?quest=12973 the character gets stuck in a phase defined by aura 55782 https://www.wowhead.com/spell=55782/phase-shift-1-foote-steppes, where the character can no longer see normal NPCs/Objects in area 4432.

funjoker explained me that spell_area table holds these kind of things.
So, spell 55782 has this entry:

| spell        | area           | quest_start  | quest_end  | aura_spell  | racemask | gender | autocast | quest_start_status | quest_end_status |
| ------------- | ------------- | ----- | ---- | ---- | ---- | ---- | ---- | ---- | ----- |
| 55782     | 4432| 12973 | 0|  0 | 0 | 2 | 1 | 74 | 0 |

If I understand correctly, the spell will be in the character if quest 12973 is QUEST_STATUS_REWARDED | QUEST_STATUS_INCOMPLETE | QUEST_STATUS_COMPLETE

So, if the player has this quest rewarded, he/she will be stuck in that phase because there is nothing that will remove it.

If the playes abandonds this quest, he/she will be stuck in phase 4, due to spell 55873 (In case he is doing the quest chain correctly):

| spell        | area           | quest_start  | quest_end  | aura_spell  | racemask | gender | autocast | quest_start_status | quest_end_status |
| ------------- | ------------- | ----- | ---- | ---- | ---- | ---- | ---- | ---- | ----- |
| 55783     | 4432| 12879 | 12973 |  0 | 0 | 2 | 1 | 66 | 1 |

If a players gets to this point of the quest chain, there is no way to go, he/she will be stuck in phase 2 or 4 forever.
I can not suggest anything because I do not know how this should be.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 9a924fb

**Operating system:** Win 8.1

**Comment by Killyana** [comment]
I need a proof, after completing this quest the phase will be switch to the old one and not to phase 4.

**Comment by TheWinchesters** [comment]
I try different things, using different chars:
- If you only take quest 12973, once is rewarded spell 55782 is not removed and it will remain in the character in area 4432.
- If you do the quests 12879, 12880, once rewarded spell 55783 is not removed and it will reamin in the character in area 4432.

**Comment by Killyana** [comment]
By proof I mean retail behavior, how the phasing works on retails in this area once the quest is rewarded.

**Comment by TheWinchesters** [comment]
Oh, sorry.
At first I thought I was doing something wrong and this issue was worthless.

**Comment by illfated** [comment]
The issue is OK, we just need to see some documentation of how it works on retail to understand exactly what is wrong in the TC source or DB.

**Comment by Jildor** [comment]
@Killyana you add spell_area in this commit:
https://github.com/TrinityCore/TrinityCore/commit/7cbce97ae4c5aeb53b58981607dd219311be07f6#diff-27e406260d4caecd571938238f1a2e93R96

But this causes the issue described here, seems not correct for me, because players can stuck in the phase completing this quest.

I think should be corrected the spell_area to restore phase when complete the quest.

And I think should have the quest a pre requisite quest (https://www.wowhead.com/quest=12880/the-master-explorer) to get https://www.wowhead.com/quest=12973/the-brothers-bronzebeard

**Comment by Killyana** [comment]
We have 3 issues here:
- I need proof/confirmation from retail that the area spell 55782 ends with the quest 12973 (the player will return in phase 1 ?)
- The npc https://www.wowhead.com/npc=30382/brann-bronzebeard must be hidden by phasing or invisibility aura until The Master Explorer taken, then turn back invisible when The Brothers Bronzebeard taken
- The https://www.wowhead.com/npc=30052/creteus is alive in phase 1, if once The Brothers Bronzebeard quest rewarded and the player is back in phase 1 he will see it alive, this doesn't make sense as it was killed during the quest line. (invisibility aura?)

**Comment by Jildor** [comment]
https://www.wowhead.com/quest=12869/pushed-too-far
Pushed too far is a Daily quest that can get only before complete The Brothers Bronzebeard quest.

We can see in this video the quest: https://www.youtube.com/watch?v=vFPZdTT9vZI
and the npcs around the area 4432 are visible (those npcs are in phase 1)

**Comment by Killyana** [comment]
Does https://www.wowhead.com/npc=30052/creteus is visible for a horde character?

**Comment by Jildor** [comment]
I'm sorry, I don't know about the NPC creteus

**Comment by Killyana** [comment]
He's visible: https://youtu.be/W9hEGUn39_U?t=14 for the horde
So the aura is removed when https://www.wowhead.com/npc=30382/brann-bronzebeard  is rewarded
