### ISSUE TITLE
Core/Misc: Log more information in asserts

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#22873]
**Description:**

Improvement to https://github.com/TrinityCore/TrinityCore/pull/22783

**Current behaviour:**

Map shows only MapID.

**Changes proposed:**

Include name to MapID

**Steps to reproduce the problem:**

1. get a crash
2. see ramdom map id
3. go dig wiki to find what map is :)

**Branch(es):**

CHANGEME 3.3.5 for now

**TC rev. hash/commit:** 

6658de05db81 (N/R)

**Operating system:** (N/R)

**Comment by jackpoz** [comment]
soon someone will ask for a screenshot of the location! xD

**Comment by illfated** [comment]
Maybe someone is capable of writing a script tool to add in the `/contrib/` folder to translate the map ID to its in-game name, or even a debug tool? Wouldn't hurt, I presume.

**Comment by Aokromes** [comment]
no need of external things:

TC> lo map mechanar
TC>554 - [Tempest Keep: The Mechanar][Instance]

**Comment by illfated** [comment]
OK, fair enough. I thought you meant translating the numerical ID if someone is uncertain about the map name.

**Comment by Aokromes** [comment]
even better:
MapID: 601 Azjol Nerub
and
Aura: Id: 53472 Pound
and 
Creature Entry: 29120 Anub'arak

**Comment by jackpoz** [comment]
Done
