### ISSUE TITLE
>> Applying update "2018_12_09_00_hotfixes.sql" '3BC8C33'... ERROR 1054 (42S22) at line 86: Unknown column 'PosX' in 'artifact_power'

### ISSUE THREAD

**Issue by chandlju** [TrinityCore/TrinityCore#22874]
**Description:**

cant import hotfix database updates and without them the server wont run. i created the mysql from the source code didnt import anything just opened bnetserver and world server and let them auto populate the empty databases but it always fails at 

>> Applying update "2018_12_09_00_hotfixes.sql" '3BC8C33'...
ERROR 1054 (42S22) at line 86: Unknown column 'PosX' in 'artifact_power'

this is extremely frustrating ive even edited that update to remove the posx in artifact power and ran it threw Heidisql with no success 

*Current behaviour:**

>> Applying update "2018_12_09_00_hotfixes.sql" '3BC8C33'...
ERROR 1054 (42S22) at line 86: Unknown column 'PosX' in 'artifact_power'

ive tried many differnt ways and they all end the same this update stops me yet i need them or the server returns 

In mysql_stmt_prepare() id: 16, sql: "UPDATE creature SET MovementType = ? WHERE guid = ?"
Unknown column 'guid' in 'where clause'
In mysql_stmt_prepare() id: 19, sql: "UPDATE creature SET position_x = ?, position_y = ?, position_z = ?, orientation = ? WHERE guid = ?"
Unknown column 'guid' in 'where clause'
In mysql_stmt_prepare() id: 20, sql: "UPDATE creature SET spawndist = ?, MovementType = ? WHERE guid = ?"
Unknown column 'guid' in 'where clause'
In mysql_stmt_prepare() id: 21, sql: "UPDATE creature SET spawntimesecs = ? WHERE guid = ?"
Unknown column 'guid' in 'where clause'
In mysql_stmt_prepare() id: 53, sql: "DELETE FROM creature WHERE guid = ?"
Unknown column 'guid' in 'where clause'
In mysql_stmt_prepare() id: 62, sql: "INSERT INTO creature (guid, id , map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'guid' in 'field list'
In mysql_stmt_prepare() id: 65, sql: "INSERT INTO gameobject (guid, id, map, spawnMask, phaseMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecs, animprogress, state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'phaseMask' in 'field list'

this is extremely frustrating ive even edited that update to remove the posx in artifact power and ran it threw Heidisql with no success 

**Expected behaviour:**

the hotfixes sql update 12-9-00 needs to be fixed 

**Steps to reproduce the problem:**

1. Step 1 Download and compile the master source code 
2. Step 2 Copy all into one folder with the dbc,maps,mmaps,vmaps,gt,worldserver.exe/conf and bnetserver.exe/conf along with the lastest 7.3.5 world and hotfixes database sqls 
3. Step 3 Open create_mysql.sql in sql/create inside the source codes directory 
4. Step 4 Run Bnetserver.exe and Worldserver.exe allow it to populate and update the databases until it envitably crashes at Error 1054  12_9_00_hotfixes.sql  has unknown entity 'PosX' in colomn 'artifact_power'

**Branch(es):**

master

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** windows 10

**Comment by chandlju** [comment]
how to i edit the label on this issue

**Comment by chandlju** [comment]
thank you

**Comment by ReyDonovan** [comment]
use 5.6.xx not problem

**Comment by chandlju** [comment]
does 32 bit matter if i have everything else 64?

**Comment by illfated** [comment]
As long as the `libmysql.dll` file you use with your core is 32-bit too (e.g. sourced from the MySQL server lib folder), when your MySQL server is 32-bit, it should work OK.

**Comment by ReyDonovan** [comment]
@illfated I don't know why, but on version 5.5 there was a syntax error on 5.6 not

**Comment by illfated** [comment]
Could be something changed in MySQL between the versions, but I have not had time to research the differences between 5.5 and 5.6. Feel free to read the MySQL 5.6 change-log to find out what has been added in 5.6 which did not work in 5.5.

**Comment by chandlju** [comment]
ok thank you, i guess 5.6 just doesnt come with a standalone 64bit msi the 32 bit one is both.

**Comment by illfated** [comment]
It is correct that the installer is 32 bit, but you can pick 64 bit server from the list when installing.
I use 64 bit MySQL server, whereas the installer & Notifier are both 32 bit only.
