### ISSUE TITLE
Please, sincerely, is there torrent or magnet for 8.0.1.28153 client? 

### ISSUE THREAD

**Issue by ddzzhen** [TrinityCore/TrinityCore#22881]
**Description:**
i want to test about it, but there is no version only 8.1.X now.
If it is not convenient, you can talk privately. thank you very much.

CHANGEME Description of the problem or issue here.

**Current behaviour:**
can`t  extract the dbc or gt from client.

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by funjoker** [comment]
Get the 8.0.1 Exe and use a launcher like arctium.

**Comment by ddzzhen** [comment]
> Get the 8.0.1 Exe and use a launcher like arctium.

Thank you very much, i have got the arctium but not 8.0.1.exe .
 If it is convenient, please send an exe to "ddzzhen@gmail.com"
Sincerely thanks!
