### ISSUE TITLE
[3.3.5] ICC / Lich King: Harvest Soul

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22883]
**Description:**
Harvest Soul (https://www.wowhead.com/spell=68980/harvest-soul ): [...] If the target is still alive after the channel is completed, the target's soul will be transfered into Frostmourne to be devoured.
Harvest Souls ( https://www.wowhead.com/spell=73654/harvest-souls): [...] If a target is still alive after the channel is completed, that target's soul will be transfered into Frostmourne to be devoured. Heroic mode only.

**Current behaviour:**
All characters die for fall damage.
Gooyeth commented about this here, saying that caused the problem: https://github.com/TrinityCore/TrinityCore/pull/21888

**Expected behaviour:**
Character/s should enter the frostmourne.

**Steps to reproduce the problem:**
1. .go xyz 529.302 -2124.49 840.857 631
2. .npc add temp 36598

**Branch:** 3.3.5
**TC rev. hash/commit:** afdbc5ffe38e9b845f6ef123849139e846a540ae
**Operating system:** Win 8.1

**Comment by ccrs** [comment]
I have to say I never did any test to check the relation of the PR and this issue

**Comment by Keader** [comment]
> basic structure changes, nothing behavioural

Nothing change in behavior, how can be the cause ccrs? '-'

**Comment by ccrs** [comment]
well, it was a complete re-implementation and this is the only known open related issue 💃 

fine debugging is necessary to truly know what is going on here

**Comment by TheWinchesters** [comment]
Weird thing:
.go xyz 10093.84 -6906.91 1.374 530
Swim in north direction
At some point, character dies. Reason: Fall

**Comment by TheWinchesters** [comment]
Update:
If you try this with gm visible off, there is no vehicle, no animation for the character but he enters the Frostmourne.
Not sure if the problem is the vehicle or if this means something else.

**Comment by illfated** [comment]
interesting point. I don't know either, but maybe there could be a phasing issue with the vehicle?

**Comment by sirikfoll** [comment]
When it was working, you would receive all the packets related to leaving the vehicle first and then the ones from the teleport,
what happens now is the opposite

**Comment by Killyana** [comment]
Cannot reproduce in rev. bd64deee3a08
