### ISSUE TITLE
[3.3.5] ICC / Lich King: Necrotic Plague

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22884]
**Description:**
Necrotic Plague (https://www.wowhead.com/spell=70337/necrotic-plague):
Infests the target with a deadly plague, causing 50000 Shadow damage every 5 sec for 15 seg. If the target dies while afflicted or the effect ends, this effect will gain an additional stack and jump to a nearby unit. If this effect is dispeled, it will lose a stack and jump to a nearby unit. 

**Current behaviour:**
The effect jumps to a nearby unit but it does not gain an additional stack.

**Expected behaviour:**
It should gain an additional stack after jumping to a nearby unit.

**Branch):** 3.3.5
**TC rev. hash/commit:** afdbc5ffe38e9b845f6ef123849139e846a540ae
**Operating system:** Win 8.1

**Comment by Killyana** [comment]
Could be related to https://github.com/TrinityCore/TrinityCore/issues/21810

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24338
