### ISSUE TITLE
pvp flag picking on mount in bg !

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22899]
player on bg droped flag + casted mount and fast picking flag !

Ride on a mount with a flag .

os: win server
Branch(es): 3.3.5
TC rev / https://github.com/TrinityCore/TrinityCore/commit/3dbe80ee2e0d1848302bcf34b654693462942639

**Comment by Killyana** [comment]
Impossible to reproduce on rev. 1c4cdfd32503
