### ISSUE TITLE
[3.3.5] Zul'Gurub / High Priestess Jeklik: Aggro Pathing

### ISSUE THREAD

**Issue by Shaboogity** [TrinityCore/TrinityCore#22893]
**Description:**

In the raid instance, Zul'Gurub, High Priestess Jeklik is unable to fly down to the target at the start of the fight.  

**Current behavior:**

When aggroed, she will be in bat form and stop at the edge of the ledge she's standing on.  Moving around on the play area below her causes her to move back and forth on the ledge, but does not cause her to come to the player. 

You can get her unstuck by using the "gm fly" command to increase the player's altitude (approx.  15ft), at this point she will fly to the player.

If you stop battle, either with the player's death or turning on gm mode, she will try to go back to her starting position, but stops on the ground on the lower play area.  (I guess that's good in this instance, but not expected)

**Expected behavior:**

She is normally supposed to fly down to the player who aggroed her.  

**Steps to reproduce the problem:**

1. Start battle with High Priestess Jeklik 
2. Workaround: use "gm fly on" to raise the player.  This seems to help correct the pathing.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. cb136387218b 2018-12-19 16:08:35 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.0.2p  14 Aug 2018 (library: OpenSSL 1.0.2p  14 Aug 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.6.41
Using CMake version: 3.12.1
Compiled on: Windows 6.1.7601
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Windows Server 2008 R2

**Comment by micckkk** [comment]
confirm in the last rev

**Comment by illfated** [comment]
@micckkk : I presume you are referring to commit https://github.com/TrinityCore/TrinityCore/commit/58c5dfac1d8d314b9243fde52466b3c933fb7d7f , but it would have been best if you could put your actual commit rev. hash in the comment when posting "confirm in the last rev" messages.

**Comment by jackpoz** [comment]
could you please include some more detailed steps like .go xyz coordinates to teleport to the boss to start the fight ?

**Comment by Killyana** [comment]
.go xyz -12275.12402, -1404.69226, 130.630646 309
And move to the boss, she will morph into a bat, but  will be stuck in the top.

**Comment by jackpoz** [comment]
it seems like ChaseMovementGenerator uses pathfinding even if the creature can fly and as we don't have a concept of "jumping down", no creature will reach any player in a floor below

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d182e5f7e73e614185f4470429467befd6e03981

**Comment by jackpoz** [comment]
Note: ChaseMovementGenerator is bugged as it doesn't handle incomplete paths when the target is far away from the player, I think it should set SetCannotReachTarget to true in that case

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/386b5a6fd948b4866cbd9a8a9892e8777922e9c9 now handles incomplete path case but there is still a check from the previous code that doesn't cause any evade in instances

**Comment by Wyrserth** [comment]
Issue is still valid after d910ffd77949f422bd08f12079866962fb53c4dc.
