### ISSUE TITLE
[Crash] DynamicObject*

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#22896]
Description: Unit:: RemoveDynObject, spellId=48210

Crash log
https://gist.github.com/HAANAAE/55a11beec00a77f686b4616016f9bcfc

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/4c3af3b636d5e9279fb694c9d9a5a4422ad773d0
Operating system: debian

**Comment by jackpoz** [comment]
Spell https://wotlk.evowow.com/spell=48210 (and spell https://wotlk.evowow.com/spell=48181) don't actually create any DynamicObject. The issue is probably caused by another spell.

**Comment by TheWinchesters** [comment]
I had this same crash today.
SpellID=50919
https://wotlk.evowow.com/spellid=50919

**Comment by Faq** [comment]
@TheWinchesters could you post hash and crashlog?

**Comment by TheWinchesters** [comment]
I could.
I did not do it because that crash was in a bit outdated server (1 month or so). Rev https://github.com/TrinityCore/TrinityCore/commit/4337eefc8f77ec2f64f2bda747292ea4e50199ea
So, maybe it is not useful. Do I post it anyway?

I am trying to reproduce the problem in a updated core but it is a bit tricky. 
I need to get disconnected at some exact moment while clicking on the npc.

**Comment by jackpoz** [comment]
Post the crash anyway please

**Comment by TheWinchesters** [comment]
https://gist.github.com/TheWinchesters/eceb3ba3927a42e491d8ff667016a384

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by jackpoz** [comment]
could someone try to reproduce it at https://tcubuntu.northeurope.cloudapp.azure.com/ ?

**Comment by TheWinchesters** [comment]
I would love to help but, where do I start?

**Comment by illfated** [comment]
@TheWinchesters : I think a good start would be to see if you can reproduce this crash on an up-to-date core, no older than Friday January 8, 2021 (commit https://github.com/TrinityCore/TrinityCore/commit/817bd92a2ae4f9c107961c9ac0d8e109f4b46be7). 

If you are able to reproduce the crash again and post a new Debug crash log, it will be a good indicator that this issue ticket needs to stay open until we find out exactly what could be causing this crash.

**Comment by jackpoz** [comment]
Keep posting crashlogs as they happen

**Comment by Aokromes** [comment]
more than 1 month without answer, if this bug is still valid open a new ticket with updated core.
