### ISSUE TITLE
Some trainers dont work (mount, pet)

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#22906]
**Description:**

When clicking on https://www.wowhead.com/npc=20511/ilsa-blusterbrew to train with an alliance, you are shown an empty gossip menu. Worldserver shows `GOSSIP_OPTION_TRAINER:: Player Vakil (GUID: 1) requested wrong gossip menu: 8622 at Creature: Ilsa Blusterbrew (Entry: 20511)`.

It seems this happens for trainers that have trainer.type = 1 and trainer.requirement = 0, which causes them to fail `trainer->IsTrainerValidForPlayer` check.

Not all trainers with these trainer type and requirement seem to ever reach that check however and work fine. For example npc entry 20500, which uses the same trainer id. The reason is that he does not have gossip in npcflags.

**Current behaviour:**

Trainer does not open menu.

**Expected behaviour:**

The trainer shows the training menu.

**Steps to reproduce the problem:**

1. Go to NPC entry 20511 with an alliance player
2. try to open the trainer menu for mounts

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 15c50069dd59 2019-01-01 18:30:54 +0100 (HEAD branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.0.2k  26 Jan 2017 (library: OpenSSL 1.0.2k  26 Jan 2017)
Using Boost version: 1.68.0
Using MySQL version: 5.6.36
Using CMake version: 3.8.0
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** 

Windows 10

**Comment by Aokromes** [comment]
try updating to head, changes to trainers where made on the last few hours.

**Comment by Shauren** [comment]
Only changes to spells, not trainers themselves

**Comment by Rochet2** [comment]
Still happens on 19791a35df11 with clean just made world DB.

**Comment by Killyana** [comment]
It happen for all riding trainers that have * gossip menu (0x1)
