### ISSUE TITLE
[Crash] spell_pri_power_word_shield

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#22917]
Description: I do not know, crash log a lot ...

Crash log / 33.3MB

https://ufile.io/ujall

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/3b5014fdae1b57add7fd204a9f9f10f3c2092b83
Operating system: debian

**Comment by Aokromes** [comment]
use https://gist.github.com/ instead that shitty hosting plz.

**Comment by Aokromes** [comment]
+ also compile on debug mode or releasewithdbg

**Comment by HAANAAE** [comment]
ican't upload gist ! error not allowed , and on issues

You can't comment at this time — your comment is too long (maximum is 65536 characters).

**Comment by jackpoz** [comment]
This is an infinite loop triggered by spell_pri_power_word_shield script

**Comment by Keader** [comment]
Wait, caster and target has the shield
Damn it

**Comment by jackpoz** [comment]
Please note Reflective Shield talent https://wotlk.evowow.com/?spell=33201 is required to trigged the issue

**Comment by Keader** [comment]
Fixed by 545bee04961450465a851196412f56b5578d9837
