### ISSUE TITLE
[3.3.5] Incorrect item in item_template

### ISSUE THREAD

**Issue by Ghaster** [TrinityCore/TrinityCore#22914]
**Description:**

I don't believe this item has ever existed on "official" servers:
![gdgfds](https://user-images.githubusercontent.com/11392454/50738184-8ba20900-11d1-11e9-94ec-f5673635a315.jpg)

**Suggested fix:**

```
DELETE FROM `item_template` WHERE `entry`=1700;
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:**
cd656b7bed44c8c1c96144c0591f275b534df3f1

**Comment by Aokromes** [comment]
it exists on dbc.

**Comment by Ghaster** [comment]
This one does:
https://www.wowhead.com/item=1700/deprecated-blood-totem
"Admin Warlord's Claymore" certainly does not.

**Comment by Aokromes** [comment]
"deprecated" since wow who knows.

**Comment by Ghaster** [comment]
It's the same item in the Classic 1.13 build: https://classic.wowhead.com/item=1700

You can see the old "Admin Warlord's Claymore" here: http://web.archive.org/web/20080522074518/http://wow.allakhazam.com:80/db/item.html?witem=1700 
 It's was actually a two-handed sword and not a neck with damage. The Item ID does exist, but the one in the DB is wrong as hell and is 100% supposed to be that deprecated blood totem.

**Comment by illfated** [comment]
Notice also the comments low down on that page:
> gm weapon
Posted: May 10th 2008 12:53pm | IP: Logged | Reply to this
Icronnuva
4 posts
Score: Default 
Its obviosly a gm weapon 
^_^

**Comment by Aokromes** [comment]
maybe they reused it on half time, but if you change the type core will complain about bad type.

**Comment by illfated** [comment]
I guess that is why I am getting a lot of unusable items in the AH when I allow all items and not excluding any.
