### ISSUE TITLE
Core/Movements: Incorrect formation behavior

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22919]
**Description:** For formations when the follower has a lower speed than the leader, once it gets  too far it will run to the next waypoint and reach it before the leader and wait for him.

This is definitively not the correct behavior, probably the follower must use the same speed as the leader and if he gets too far (for some reason) he must run to the contact point with the leader+ the follow distance, and not to the next waypoint.

**Steps to reproduce the problem:**

1. UPDATE creature_template SET speed_walk=0.5 WHERE entry IN (5701);
2. .go c id 5701
3. the npc 5701 (Selina Pickman) is following the leader, just notice the behavior
You can also use ".wp show on"  on the leader to see the waypoints

**Branch(es):** both probably

**TC rev. hash/commit:**  rev. dd81978f432f

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/FormationMovementGenerator.cpp

Current implementation is really basic. The correct one, the one you mention, requires time and thought

**Comment by Ovahlord** [comment]
In fact it appears that formation members have way more move calls than the leader. When you use tool like the waypoint creator you can see that the formation members have a very even line of points which means that they have a fixed interval which is making them move to their destination.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24379
