### ISSUE TITLE
Spell::EffectTriggerSpell spell 7405 tried to trigger unknown spell 58568

### ISSUE THREAD

**Issue by splinecl** [TrinityCore/TrinityCore#22928]
**Description:**

When fighting some "Shadowhide Warrior" today, I saw a lot of these in the server log

> Spell::EffectTriggerSpell spell 7405 tried to trigger unknown spell 58568

**Current behaviour:**

Error in log when creatures try to use spell 7405 (Sunder Armor)

**Expected behaviour:**

No errors in log when creatures use "Sunder Armor".

**Steps to reproduce the problem:**

1. .go xyz -9181.3496 -3229.61 105.5 0
2. Some Shadowhide Warriors should start attacking
2. When they use Sunder Armor(7405), you get an error in log

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 5e73647c8433 2019-01-09 17:24:30 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows 10

**Comment by splinecl** [comment]
These are the creatures that seem to be using 7405

SELECT * FROM world.creature_template where spell1=7405;
SELECT * FROM world.creature_template where spell2=7405;

**Comment by splinecl** [comment]
ok, then I looked in the wrong place, but the error remains either way.

**Comment by Killyana** [comment]
It's an unkwon dbc_spell like many others: 10876, 15579, 19229, 22540,  25584, 37503, 47805, 55157, 58568, 58570, 65095

We will probably never get this data.

**Comment by splinecl** [comment]
Alright I will put it on my ignore list then, thanks for the replies.
