### ISSUE TITLE
pcopy command

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#22921]
**Description:**

pcopy command will be the fast way for pdump + pload

**Current behaviour:**

When we have to test bugs we must levelup characters, equip them, learn talents and spells or pdump a character and load to one new account

**Expected behaviour:**

with pcopy it will allow use pcopy "source character" "target account" we will have a copy of one existing character.

**Steps to reproduce the problem:**

1. go test some bug

**Branch(es):**

CHANGEME both

**TC rev. hash/commit:** 

N/R d12f0841f198

**Operating system:** N/R

**Comment by yvomsx** [comment]
Easily achievable if using the existing .char moveaccount and altering it, where it doesn't only change the accountid, but inserts a new instance?

**Comment by Aokromes** [comment]
no need of "newname" target account, core will force rename of the 2nd char.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6215da0d640bd86a7c2bc144859c1542f09fc1a6
