### ISSUE TITLE
Bug Spell - Icebound Fortitude - DK

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#22925]
Description: spell for class dk  if use 12sec all attacks => mele / magics ! Full miss .

https://wotlk-twinhead.twinstar.cz/?spell=66023

TC: 3.3.5
TC rev: https://github.com/TrinityCore/TrinityCore/commit/4771a4363f5e5487de6506110504935dcd917d9e
OS: Win

**Comment by Killyana** [comment]
Cannot reproduce on  rev. d12f0841f198
