### ISSUE TITLE
Mage Quest - Items of Power

### ISSUE THREAD

**Issue by jempson** [TrinityCore/TrinityCore#22927]
**Description:**

mage quest - Items of Power - lets me use the items to charge them at Circle of Outer Binding in Arathi highlands, but I can't ever loot them once charged for the quest.

**Current behaviour:**

mage quest - Items of Power - it does the entire animation, showing it hovering over the stone at Circle of Outer Binding, but it never shows that I can click it to get the charged item, eventually it just disappears, I even stayed for 10+min after, with nothing showing up.

**Expected behaviour:**

Retrieve the charged bramble.

**Steps to reproduce the problem:**

1. https://www.wowhead.com/quest=1948/items-of-power

**Branch(es):**

Branch 3.3.5a

**TC rev. hash/commit:** 

TC rev. b283565d8adb394862ea2affd2af497bac6cdbcb

**Operating system:** 

Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6388
