### ISSUE TITLE
Demoralizing Shout and critters

### ISSUE THREAD

**Issue by splinecl** [TrinityCore/TrinityCore#22931]
**Description:**

When using the warrior ability Demoralizing Shout near critters, like for example the Black Rats that are all over Shadowfang Keep, you get flagged for being in combat, but critters don't attack. So unless you can find the random critter that you are flagged for combat with and kill them, you will be stuck in combat, which is not very cool.

**Current behaviour:**

When using Demoralizing Shout near critters you get flagged for combat against that critter, but since critters don't attack it can be hard figuring out why you are in combat.

**Expected behaviour:**

Not sure. Demoralizing Shout  should not flag for combat against critters, or combat flag should be removed when Demoralizing Shout debuff expires on critter. Not sure which one is correct.

**Steps to reproduce the problem:**

1. .go xyz -9358.24 114.352 61.839 0
2. Go near a rabbit
3. Use Demoralizing Shout
4. Notice that you get flagged for combat, even after Demoralizing Shout expires on critter

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b7a3affc0c46 2019-01-10 15:07:09 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows 10

EDIT: Changed description to reflect discussion about critters in comments.

**Comment by illfated** [comment]
I think that line about neutral creatures is meant to describe creatures (NPCs) with higher level than critters, but I could be wrong.
To me, it looks like critters don't have any aggressive or defensive AI, only a fleeing mechanism.
(Then again, my memory may be clouded from using TC source all the time since 2013.)

**Comment by splinecl** [comment]
The same happens when using the druid bear form ability Demoralizing Roar.

Also the issue only seem to happen when used against neutral creatures that can not attack, like rabbits, rats and sheep. The behavior seems correct against neutral creatures that can attack.

**Comment by splinecl** [comment]
> I think that line about neutral creatures is meant to describe creatures (NPCs) with higher level than critters, but I could be wrong.
> To me, it looks like critters don't have any aggressive or defensive AI, only a fleeing mechanism.
> (Then again, my memory may be clouded from using TC source all the time since 2013.)

Yes, you are correct, it seems to only happen against critters.

**Comment by illfated** [comment]
If that is the case, that only critters keep you in combat, it is likely a flaw in how aggro is handled by critters.
We need someone with experience with the current combat AI to chip in on this issue.

**Comment by splinecl** [comment]
I modified description and title to correctly reflect that this is about critters.

**Comment by Killyana** [comment]
Before the combat/threat rewrite, critters just evades upon they get the aura.

**Comment by splinecl** [comment]
For whatever it's worth, in retail critters just flee when hit by the debuff, you never enter into combat.

**Comment by illfated** [comment]
... which makes it a goal for TC code to become more Blizzlike.

**Comment by splinecl** [comment]
When I wrote retail, I mean BfA, so not sure how accurate the info is for 3.3.5, but thats all I had access to.

**Comment by offl** [comment]
Moreover some of them can cast spells: https://www.wowhead.com/npc=14881/spider#comments:id=234523 (it was caused by Poison Proc aura I believe)

**Comment by splinecl** [comment]
But isn't that only critters that can attack? Those that can attack should of course just attack like any other creature, but the critters that can not attack should not put you in combat, right?

**Comment by Aokromes** [comment]
i wonder if this bug is the reason of people stuck on combat with critters...

**Comment by splinecl** [comment]
We had a hell of a time in Shadowfang Keep because of this, we were constantly stuck in combat, and had to use GM commands to get out of combat, otherwise it would have been unplayable.
