### ISSUE TITLE
[3.3.5] Error logged when using Mind Control

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#22939]
**Description:**

Casting Mind Control the first time to a player after logging in triggers this log message in the console
>Attempt to assign charm AI to player GUID Full: 0x0000000000000003 Type: Player Low: 3 who is charmed by non-creature GUID Full: 0x0000000000000001 Type: Player Low: 1

**Steps to reproduce the problem:**

1. Login with 2 characters, 1 priest, 1 horde and 1 ally
2. Enable PvP and make sure the 2 characters can target each other in offensive mode
3. Cast Mind Control

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

95398fadf958

**Operating system:** Windows 10

**Comment by CraftedRO** [comment]
319434544baa018339ba6284ebb910eec1418a4f In my tests this seems no longer valid: https://youtu.be/CT0TcGlAqRY

**Comment by jackpoz** [comment]
I wonder if I fixed it and forgot to close the issue

**Comment by CraftedRO** [comment]
now, there's other error instead when you auto attack with controlled player another npc: 

> HandlePetStopAttack: GUID Full: 0x000000000000000c Type: Player Low: 12 does not exist
