### ISSUE TITLE
[3.3.5]Eye Of Eternity reset event

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCore#22948]
**Description:**

If I fail in battle,after enter instance again and I can not restart battle.

The middle jewelry is not reset

**Current behaviour:**

The middle jewelry is not reset so I can not restart battle.

**Expected behaviour:**

The middle jewelry should reset and show.

**Steps to reproduce the problem:**

1. enter in Eye Of Eternity and click the middle jewelry(gameobject) start battle.

2.die!

3.enter in raid again and you see. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d609e515d7f5ab2f250fec409d9fb690f301b906

**Operating system:** Windows 10

**Comment by Killyana** [comment]
The orb must respawn with the boss

**Comment by Matt0615** [comment]
#24426 @Killyana

**Comment by Shauren** [comment]
f57b1e27d062286553b8dd3199ce118eb99ac270
