### ISSUE TITLE
DB/SAI: North Fleet Marksman

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#22949]
**Description:**
Howling Fjord NPC North Fleet Marksman  ([23946](https://woehead.way-of-elendil.fr/?npc=23946)) must act like ranged class. North Fleet Marksman should use [Shoot](https://woehead.way-of-elendil.fr/?spell=15547) and [Aimed Shot](https://woehead.way-of-elendil.fr/?spell=38370).

**Branch(es):**
3.3.5 and master

**TC rev. hash/commit:** 
TrinityCore rev. 9faad4601bc6 2019-01-12 12:16:23 +0100 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:** 335.64

**Operating system:** *nix

**Comment by illfated** [comment]
- https://www.wowhead.com/npc=23946/north-fleet-marksman#abilities
- https://www.wowhead.com/spell=78841/aimed-shot
- https://www.wowhead.com/spell=6660/shoot#used-by-npc (Used by (308))
