### ISSUE TITLE
DB/SAI: Vengeance Bringer

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#22943]
**Description:**
Implement scripts ([Battle Shout](https://woehead.way-of-elendil.fr/?spell=32064) and [Mortal Strike](https://woehead.way-of-elendil.fr/?spell=32736) casting) for Howling Fjord NPC Vengeance Bringer ([23865](https://woehead.way-of-elendil.fr/?npc=23865)).

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 9faad4601bc6 2019-01-12 12:16:23 +0100 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:** 335.64

**Operating system:** *nix

**Suggested Fix:**
```sql
-- Vengeance Bringer (23865)
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=23865;
DELETE FROM `smart_scripts` WHERE `entryorguid`=23865 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(23865,0,0,0,0,0,100,0,0,0,60000,60000,0,11,32064,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Vengeance Bringer - In Combat - Cast 'Battle Shout'"),
(23865,0,1,0,0,0,100,0,3000,6000,7000,10000,0,11,32736,0,0,0,0,0,2,0,0,0,0,0,0,0,0,"Vengeance Bringer - In Combat - Cast 'Mortal Strike'");
```

**Comment by illfated** [comment]
Looks good to me.™ The creature does not have any `AIName` nor `ScriptName` yet, so no other changes are needed.
BTW, have you tested this ingame too, just to see that the spells are cast correctly and without visual issues?

**Comment by Sorikoff** [comment]
Yes, I test all scripts ingame.
