### ISSUE TITLE
[3.3.5] Core/Spell: Negative auras displayed as buff instead of debuff

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22940]
**Description:**
Spell: Leeching Swarm (https://www.wowhead.com/spell=53468)
Leeching Swarm is a buff that Deals 2 Nature damage per second

**Current behaviour:**
It appears like a buff, instead of a debuff

**Expected behaviour:**
It should be a debuff.

**Steps to reproduce the problem:**

1. .go c id 29120
2. Start the encounter and Anub'arak will cast this on the character.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 7b40303a488ef3edcee0930aee5171bb3df97688
**Operating system:** Win 8.1

**Comment by illfated** [comment]
Notice also that https://www.wowhead.com/spell=53467/leeching-swarm is the spell cast by Anub'arak to trigger 53468,
https://github.com/TrinityCore/TrinityCore/blob/fcfcb0eb6f2c5f7152542f3c8deb47e5a99f52f4/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp#L38
https://github.com/TrinityCore/TrinityCore/blob/fcfcb0eb6f2c5f7152542f3c8deb47e5a99f52f4/src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp#L200-L204

I am trying to figure out if it needs an entry in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellInfo.cpp or maybe a custom entry in `boss_anubarak.cpp` (like for Anub'arak in Trial Of The Crusader), but @Keader knows a lot more than me about this.

**Comment by Killyana** [comment]
This is a general issue about negative aura displayed as buff instead of a debuff
