### ISSUE TITLE
[3.3.5] Buffs stacking

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22945]
**Description:**
Based on: 
https://www.mmo-champion.com/threads/612981-Patch-3-0-2-On-Debuffs-Buffs-and-Raid-Stacking
- Attack Power Buff (Multiplier): Abomination's Might, Trueshot Aura, Unleashed Rage
- Melee Critical Strike Chance Buff: Leader of the Pack, Rampage

**Current behaviour:**
Trueshot Aura and Unleashed Rage are stacked
Leader of the Pack and Rampage are stacked

**Expected behaviour:**
Trueshot Aura and Unleashed Rage shouldn't stack.
Leader of the Pack and Rampage shouldn't stack.

**Related links:**
Trueshot Aura: https://db.rising-gods.de/?spell=19506
Unleashed Rage: https://db.rising-gods.de/?spell=30802 (rank 1)
Leader of the Pack: https://db.rising-gods.de/?spell=24932
Rampage: https://db.rising-gods.de/?spell=29801

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 7b40303a488ef3edcee0930aee5171bb3df97688
**Operating system:** Win 8.1

**Comment by Keader** [comment]
Checking current DB, i's fixed already.
All spells is in spell_group/spell_group_stack_rules.
f7d385abf022b154c74120f83b5e3a11f2d19262
