### ISSUE TITLE
[3.3.5] Nefarian event

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22946]
**Description:**
Talking with Lord Victor Nefarius, the Nefarian event will start.

**Current behaviour:**
Nothing happens after talking with Lord Victor Nefarius
All the previous bosses are 'DONE'.
Am I missing some condition?.

**Expected behaviour:**
The raid should be able to start the event and defeat Nefarian.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 7b40303
**Operating system:** Win 8.1

**Comment by jackpoz** [comment]
>bool GossipSelect(Player* player, uint32 menuId, uint32 gossipListId) override
        {
            if (menuId == GOSSIP_ID && gossipListId == GOSSIP_OPTION_ID)
            {
                CloseGossipMenuFor(player);
                Talk(SAY_GAMESBEGIN_1);
                BeginEvent(player);
            }
            return false;
        }

does it say anything after you select the gossip ?

**Comment by ccrs** [comment]
I think its a mistake on ariel's refactor process, iirc ```, uint32 menuId, uint32 gossipListId``` are not the correct parameters
