### ISSUE TITLE
[3.3.5] Worldserver.conf and timezones

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#22956]
**Description:**
In a local enviroment, Everything that has an "hour of the day when xxx occurs" in worldserver.conf occurs 3 hours earlier.
At least in my case, (GMT-3).

Example:
Worlserver.conf: `Instance.ResetTimeHour = 4` (default)
Server: Global instance resets at 1 AM

Is this intended? Or it should use the timezone of the machine where the core is running?

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 7e579a98483313cb68b58dcc1dd0d25903812f93
**Operating system:** Win 8.1

**Comment by Aokromes** [comment]
on my case instance reset set to 6 enables reset on 7am.

**Comment by Jildor** [comment]
You should configure your timezone of the machine for this case

**Comment by TheWinchesters** [comment]
Configured for my case:
Timezone
(UTC-3:00) Buenos Aires

**Comment by illfated** [comment]
I use the default setting ( `Instance.ResetTimeHour = 4` ) and my resets occur at 03:00 (am). My TZ is GMT+1.

@TheWinchesters : have you checked your auth `realmlist.timezone` setting?

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/8390

**Comment by jackpoz** [comment]
Not the same issue as this is about events running serverside while the other issue is about timezone ignored in the packet sent by the client

**Comment by jackpoz** [comment]
I opened a draft PR https://github.com/TrinityCore/TrinityCore/pull/23540

**Comment by jackpoz** [comment]
which configs does it affect other than Instance.ResetTimeHour ?

**Comment by TheWinchesters** [comment]
- Everything that has a 'hour of the day' in worldserver config
- weekend xp rate

**Comment by TheWinchesters** [comment]
- Quests.DailyResetTime
- Guild.ResetHour
- Respawn.RestartQuietTime
- Battleground.Random.ResetHour
- weekend xp rate

and not sure about CleanOldMailTime

**Comment by jackpoz** [comment]
Do all these reset at wrong time ?

**Comment by jackpoz** [comment]
I tried Guild.ResetHour and it called World::ResetGuildCap() at the right hour of the day

**Comment by TheWinchesters** [comment]
Oh, sorry. My mistake.

**Comment by jackpoz** [comment]
could you check the others too and see which ones are broken ?

**Comment by TheWinchesters** [comment]
This is everything I have experienced so far, (UTC -3):
- It is 23:45 while I am writting this and Darkmon Faire event is not active when it should end at midnight. I checked the same in localhost.
- Fishing events during weekend start 3hs sooner.
- I killed a boss and it says that the instance cd will end in X days, 3 hours. (worldserver config says 6 AM).
- Once the server restarted because of Respawn.GuidAlertLevel and it restarted at midnight (worldserver config says 3 AM).
- Sunday , 22:00hs, people complained because the XP was normal and it was true. (xp is 2.0 during Friday, Saturday and Sunday)

A easy test for anyone would be entering an instance and see what the welcome message says or wait to see when the Kalu'ak event starts tomorrow.

**Comment by jackpoz** [comment]
could you check if https://github.com/TrinityCore/TrinityCore/pull/23540 fixes the instance reset ?

**Comment by jackpoz** [comment]
Updated https://github.com/TrinityCore/TrinityCore/pull/23540 to support Respawn.RestartQuietTime too

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23540 fixed some issue

**Comment by illfated** [comment]
Stranglethorn Fishing Extravaganza is still problematic, isn't it? Or maybe I have forgotten to check if the events occur at a different time than 14:00 local time on Sunday, and whether I could have set a different time deviation somewhere in the config.

**Comment by jackpoz** [comment]
Reopen if there are still some issues

**Comment by xlla** [comment]
what is a proper way to configure timezone of the server?
I found the Stranglethorn Fishing Extravaganza event's start_time was set to 2016-10-30 22:00:00 in my world db.
my os timezone is +8,  it seems the db init process add extra +8 to each game event's start_time, so the Stranglethorn Fishing Extravaganza was not started as 2 pm on my client (timezone +8 also).
