### ISSUE TITLE
DB/CORE: SCRIPT_COMMAND_CAST_SPELL for gameobjects

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22966]
**Description:** This 2 gobs SELECT * FROM `gameobject_template` WHERE `entry` IN (180911, 180912);   are goobers they have a dbc spell on data=10 that is casted when the player click the gob.

Once clicked this DBC spell will trigger another spell casted by the gob on the player via spell_script: 
SELECT * FROM `spell_scripts` WHERE id IN (34448, 34452);

Before the implementation of gameobject cast, this was working correctly, but now it looks like `spell_scripts` doesn't support a gob as a source caster:

SCRIPT_COMMAND_CAST_SPELL ('spell_scripts' script id: 34448) no source unit found for spell 26566
SCRIPT_COMMAND_CAST_SPELL ('spell_scripts' script id: 34452) no source unit found for spell 26572

/// todo Allow gameobjects to be targets and casters
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/MapScripts.cpp#L665

**Steps to reproduce the problem:**

1. .go xyz 9333.637, -7879.619, 74.91 530  (Don't get too close to the orb or you will be teleported by the area trigger)
2. Clique the orb (No tp will be executed)
3. look to the server log (console)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 0cbdbd8a3f3c

**Comment by jackpoz** [comment]
is there any requirement to be able to click the orb ?

**Comment by Killyana** [comment]
No requirements, just a horde char.

**Comment by jackpoz** [comment]
```sql
UPDATE `spell_dbc` SET `effectimplicittargeta1`=25, `rangeindex`=12 WHERE `Id` IN (34448, 34452);
```
this is needed to let 34448 target the player.
then 26566 is triggered but it doesn't allow to target the player so the spell fails...

**Comment by jackpoz** [comment]
@Killyana I allowed gameobjects to cast spells at https://github.com/TrinityCore/TrinityCore/commit/813cf761fcf8737e50486672be28900c9cf4f36f but the current database data must be updated to reflect the change from Player -> Player to GameObject -> Player:
- the server side spells need to be able to target Player so EffectImplicitTargetA1 = 25 (Any)
- RangeIndex = 12 (Interaction) otherwise spell will fail with Out Of Range (not shown ingame since the GO is casting)
Here's a working example
```sql
UPDATE `spell_dbc` SET `effectimplicittargeta1`=25, `rangeindex`=12 WHERE `Id` IN (34448, 34452);
UPDATE `spell_scripts` SET `datalong2`=2 WHERE `Id` IN (34448, 34452);
```

**Comment by Killyana** [comment]
Works fine Thanks, I will check the other spells.

**Comment by illfated** [comment]
Good work, thanks for the effort so far. 👍
