### ISSUE TITLE
Core/SAI: Move to position and orientation

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22975]
**Description:** The action SMART_ACTION_MOVE_TO_POS could use the target SMART_TARGET_POSITION that has x, y, z and orientation.

The issue here is the orientation is always ignored, so an extra action "set orientation" must be usedd once the position reached.

We need the orientation to be set for the npc once the position reached if the orientation is not 0

**Branch(es):** both

**TC rev. hash/commit:**  rev. 813cf761fcf8

**Comment by Rushor** [comment]
yeah that would be really nice. in the other scriptsystem with `waypoints` the set of the orientation works fine.

**Comment by Killyana** [comment]
We don't have orientation in waypoints table neither, it was added in waypoint_data only, adding orientation field in waypoints table will avoid using set orientation every time we need the npc to change orientation after a pause or at the end of the path.

**Comment by offl** [comment]
MoveType (walk \ run \ fly) will be also useful in waypoints table & SMART_ACTION_MOVE_TO_POS
WaitTime in waypoints table would be also useful

**Comment by Rushor** [comment]
Actually using waypoint data for sai is a good solution and add a sai action for calling waypoint-data. It's strange that we have 3 scripts systems for pathing: waypoints, waypoint-data, script-waypoints

**Comment by offl** [comment]
> It's strange that we have 3 scripts systems for pathing: waypoints, waypoint-data, script-waypoints

And they are different from each other :rofl: 

The best we can use today is CMaNGOS' creature_movement & creature_movement_template with deletion of all another systems except splines and including script_waypoint.

They have the [PathID column](https://github.com/cmangos/mangos-tbc/commit/652382c43bee18affc2535172cbfe3aa6e208fae), this allow you not to create waypoints with ID*100 (888800 or 888801 or 888802). Just always 8888 + PathID column. Plus now you can load waypoint by changing creature_template.MovementType to 2. But now you will have to create waypoints for every creature even if they uses the same waypoint.
Plus you can [summon creature with the PathID parameter](https://github.com/cmangos/mangos-tbc/commit/652382c43bee18affc2535172cbfe3aa6e208fae#diff-08c5c4dca930b7acf7d5c045dc6f496bR1611). Without this you will never script [some NPCs properly without](https://github.com/cmangos/tbc-db/commit/b6e118eb01dcfab7493474715cc92be62a62b381#diff-e1b28cee751dc1b4835cb396492a25faR134) C++.

**Comment by Killyana** [comment]
It will be also nice the have action_param5=movement_type=0/1 (run/walk)

**Comment by illfated** [comment]
I could not find the "separate PR" Sorikoff spoke of (https://github.com/TrinityCore/TrinityCore/pull/24201#issuecomment-591393639) in the closed PR. Maybe it has not been written or pushed yet?

**Comment by Killyana** [comment]
There's no PR about speed, this issue is about orientation only.
