### ISSUE TITLE
Trial Of The Crusader boss kill status

### ISSUE THREAD

**Issue by qyh214** [TrinityCore/TrinityCore#22980]
**Description:** 

kill boss and loot,Pickup status( It seems can loot again) is still displayed, but it is ineffective.

all bosses in Trial Of The Crusader have this issue.

AND I know The body needs to be kept on display after killed by player.

**Current behaviour:**
like Description

**Expected behaviour:**

After loot,Should no longer display lootable status.

**Steps to reproduce the problem:**

1. enter in Trial Of The Crusader
2. kill boss ,loot

**Branch(es):**

3.3.5, maybe both

**TC rev. hash/commit:** 

71fd5f19dc99acec6fdeb9decfc4a241134f68d2

**Operating system:** Win10 x64

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/12086
The boss will drop Alliance and horde items but players will be able to see only items related to their faction. If you activate cross faction you can make mixed party and you will be able to loot everything.

**Comment by illfated** [comment]
I presume you are referring to the conf setting `AllowTwoSide.Interaction.Group` - or do we need to check other cross-faction settings too when this happens?

**Comment by Aokromes** [comment]
a1b2aa9
