### ISSUE TITLE
Core/Combat: Pets doesn't set their master in combat when they attack a player

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#22989]
**Description:**
 If you send your pet to attack a player you will not enter the combat mode.

If the other player hit you pet (one melee hit) your char will enter combat mode for 5secs.

If you send your pet to attack an other pet (the attacked pet must be in passive mode) the second player will be spammed by enter/leave combat

**Steps to reproduce the problem:**

1. Connect 2 chars with controlled pets  
2. Put the 2 pets in passive mode
3. Send one of the pets to attack the other player and notice the character will remain out of combat
4. Send the first pet to attack the second pet and look the character that have his pet attacked, he will be spammed with enter/leave combat

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 717e050edb73

**Comment by Jildor** [comment]
Maybe this commit is the cause?
https://github.com/TrinityCore/TrinityCore/commit/8aee9dd9489bfb60b321368dd4465700f13b35e5#diff-98fab3902dbf17ec663e0197696687b2

**Comment by Jildor** [comment]
It seems on purpose: https://github.com/TrinityCore/TrinityCore/pull/12083

**Comment by Killyana** [comment]
Thanks
