### ISSUE TITLE
Spell system

### ISSUE THREAD

**Issue by ReyDonovan** [TrinityCore/TrinityCore#22988]
**Description:**

I noticed that all healing spells work correctly except that they will not heal
CHANGEME Description of the problem or issue here.

https://www.wowhead.com/spell=774
Heals the target for (72% of Spell power) over 12 sec.

TrinituCore in game 
cast 774
Heals the target for (0% of Spell power) over 12 sec.

and so with all healing spells on all classes
--

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**
master 

**TC rev. hash/commit:** 
e754000a7a6383b9248064a4f37aa36ba0ac8f1d
CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by illfated** [comment]
Did you solve the issue? If yes, how?
Unless the issue is solved or a duplicate of an existing issue ticket,
you don't have to close this ticket.
A comment with the reason for closing this issue would also be nice.
