### ISSUE TITLE
crash on CallForHelp

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#22983]
**Description:**

crash on calling for help

**Current behaviour:**

https://gist.github.com/Aokromes/ed5c253cca67e17e13620303c36fae15

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

717e050edb73

**Operating system:** Debian 9 x64

**Comment by jackpoz** [comment]
@Treeston is it ok to change this assert to a if check ?https://github.com/TrinityCore/TrinityCore/blob/717e050edb73f8ae0874944561069924224986e0/src/server/game/Entities/Creature/Creature.cpp#L2267

The IsEngaged() check and all the GetVictim()/GetTarget() calls seem quite unrelated to each other, plus IsEngaged() goes through offline references but GetVictim()/GetTarget() skip those.

**Comment by Treeston** [comment]
Something is fishy if IsEngaged is true but the unit is not in combat. Even if the threat ref is offline, it should still be in combat.

Find the root cause. Something not calling UpdateVictim?

**Comment by jackpoz** [comment]
The point is that IsEngaged() doesn't call UpdateVictim() but for example GetThreatManager().GetCurrentVictim() does, so maybe IsEngaged() should be checked again after ? https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Combat/ThreatManager.cpp#L203

Or is UpdateVictim() supposed to be called everytime there is a change in the threat manager instead of like once every Creature::Update() ?

**Comment by Treeston** [comment]
`UpdateVictim` should be called before the AI calls for help for sure. I mean, you don't want to call for help if there's no combat anymore...

**Comment by jackpoz** [comment]
In this case the assert is triggered by a SAI script event SMART_EVENT_HEALT_PCT that executes action SMART_ACTION_CALL_FOR_HELP, so maybe UpdateVictim() should be added there and checked there ?

**Comment by Treeston** [comment]
Why does SmartScript execute a health event in the first place if UpdateVictim failed?

**Comment by jackpoz** [comment]
There's no check about UpdateVictim() in SMART_EVENT_HEALT_PCT handler, it could also be UpdateVictim() has not been reached yet or a previous SMART_EVENT_* caused the victim not to be valid anymore.
There are probably a thousand different ways to trigger that :) I also don't see SMART_EVENT_HEALT_PCT to have to be bound to having an enemy active (enemy could have died in the meantime or stealthed or whatever)

**Comment by jackpoz** [comment]
Opened a PR to mode the assert to TC_LOG_ERROR, the current code doesn't inspire me enough to think the assert can never happen. We'll leave this issue open until we have clear How To Reproduce steps so we can evaluate if we should move it to TC_LOG_DEBUG or change threat code and put it back to ASSERT

**Comment by Treeston** [comment]
SmartAI executing a call for help event while the creature is not engaged is incorrect, full stop.

This is an assertion for a reason.

**Comment by Shauren** [comment]
Question becomes then HOW? I thought it is safe to assume that for SMART_EVENT_HEALTH_PCT to trigger, creature must be in combat and taking damage

**Comment by Killyana** [comment]
Yes SMART_EVENT_HEALTH_PCT triggers only if the creature is in combat, I tried to reproduce CALL_FOR_HELP triggering out of combat in this case, but it was impossible.

**Comment by jackpoz** [comment]
@Shauren as I wrote in https://github.com/TrinityCore/TrinityCore/issues/22983#issuecomment-457197799 , ThreatManager calls UpdateVictim() when used inside https://github.com/TrinityCore/TrinityCore/blob/717e050edb73f8ae0874944561069924224986e0/src/server/game/Entities/Creature/Creature.cpp#L2257 so checking a condition, calling functions that change that condition and that asserting after that the condition is still the same does not make any sense.

See https://github.com/TrinityCore/TrinityCore/blob/717e050edb73f8ae0874944561069924224986e0/src/server/game/Entities/Creature/Creature.cpp#L2259 , even there IsEngaged() is checked.

About being "incorrect", the point of asserts is not to crash worldserver whenever there is "incorrect" code, the point is to stop execution soon to avoid executing more code in an unstable state that could corrupt data and crash anyway later on. Creature::CallForHelp() called without having a victim anymore doesn't sound like the case just described and there is not reason to cause a crash for that.
If you think there can be a bug then add a TC_LOG_ERROR .

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23034
