### ISSUE TITLE
[BUG] Banned Account exists !

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#22990]
Problem baneed account!

.ban acc test 10d advs

Error:
Ban exists

.unban acc test
test unbanned.

again

.ban acc test 10d advs
Error:
Ban exists

The account can not be banned!

windows server 2012 / 64bit

TC/RV
https://github.com/TrinityCore/TrinityCore/commit/372de1cafea6a10ba157e3e468ab17809ce5c0a5

**Comment by IllInuz** [comment]
Will check this to confirm.

**Comment by Hir0shi** [comment]
This problem occurs for some accounts !

**Comment by Killyana** [comment]
Could you provide this information for one of this accounts ?
``` sql
SELECT * FROM account_banned WHERE id= ; -- Auth DB

**Comment by Infernales** [comment]
@Killyana And you will not receive any data. Ban data will not be entered in the table. And after restarting the server, you still can not give out a ban on this account. Funny hack on LUA right?
