### ISSUE TITLE
GEODATA

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#22995]
Why did you break the GEODATA when I collected the core 2 years ago? everything was fine, what happened now? The creatures in the ice crown Citadel are behaving horribly. Please indicate why this happened and take it as a basis. I apologize for the transfer just from Russia
https://s8.hostingkartinok.com/uploads/images/2019/01/b32d821e4ec60607ac73c9412df69015.jpg
https://s8.hostingkartinok.com/uploads/images/2019/01/9aa8c171bed39a281d5ed86ae351c759.jpg
https://s8.hostingkartinok.com/uploads/images/2019/01/dfd6352e3f2929eaa00b3dec861f82d8.jpg
Maps extracted times 5 so same GEODATA included here is screen config
https://s8.hostingkartinok.com/uploads/images/2019/01/24a3012744bb08f1dd50efcf22da1030.png
Also asked many people who are also engaged in the kernel of Trinity and they also confirmed this bug

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 00958c9
**Operating system:** Debian 9

**Comment by Killyana** [comment]
You missed up with this screen https://s8.hostingkartinok.com/uploads/images/2019/01/dfd6352e3f2929eaa00b3dec861f82d8.jpg

Your core is one year old, also the + at the end indicate modifications done on your side.

**Comment by Warpten** [comment]
The + you're seeing is part of the timezone for time strings....
But yeah, anyways, this looks like old (6+ months) code.
