### ISSUE TITLE
[3.3.5] 'Join arenas' permission

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23000]
**Description:**
The core does not check if player has permission 'Join arenas' when the player joins arenas.
So, if you deny this permission to an account, for example, it does nothing and the player still can enter arenas.

The check exists, in Player.cpp:
```cpp
bool Player::CanJoinToBattleground(Battleground const* bg) const
{
    // check Deserter debuff
    if (HasAura(26013))
        return false;

    if (bg->isArena() && !GetSession()->HasPermission(rbac::RBAC_PERM_JOIN_ARENAS))
        return false;

    if (bg->IsRandom() && !GetSession()->HasPermission(rbac::RBAC_PERM_JOIN_RANDOM_BG))
        return false;

    if (!GetSession()->HasPermission(rbac::RBAC_PERM_JOIN_NORMAL_BG))
        return false;

    return true;
}
```
But, this function is called using this if in Group.cpp
```cpp
if (bgOrTemplate->GetTypeID() != BATTLEGROUND_AA && !member->CanJoinToBattleground(bgOrTemplate))
            return ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS;
```

So, the check is used when it is a battleground, but it is not used when it is an arena.

Remembering I am still a noob about some things, possible solutions could be:
1) Remove `bgOrTemplate->GetTypeID() != BATTLEGROUND_AA` from the if and modify this check in `CanJoinToBattleground`  
```cpp
if (!bg->isArena() && HasAura(26013))
```
2) Create two different functions for each situation (Arena | Battleground) to avoid unnecessary checks

3) I am wrong and all the options are shit

**Branch:** 3.3.5
**TC rev. hash/commit:** 71dde16ce9a9c7904a2902ae288b3f05851224ac
**Operating system:** Win 8.1

**Comment by Meltie2013** [comment]
I have no issues with this at all. Make sure the permission id is not granted too the account and permissions reloaded after the change. With GM accounts, make sure the permission is removed or not granted too them.

**Comment by TheWinchesters** [comment]
I tested using a normal player account where I removed the permission using `rbac_account_permission`.
I have reloaded RBAC and I have even restarted the server.
But thank you for your answer. I will re-check again!

**Comment by TheWinchesters** [comment]
I recompiled core.
Now using rev: 9d37d395119a805ee05daaf41485b591d613d744
Using 2 accounts, normal ones.
I have denied permission 5 even to both of them using `rbac_account_permission`.
Reloaded RBAC
Both players joined arena as a group successfully.

To see if I was doing this correctly, I took the same account and denied the permissions:
3 - Join Normal Battleground
4 - Join Random Battleground
5 - Join Arenas
and I tried:
Player can not join normal battleground
Player can not join random battleground
Player can join arenas

I have run the core again and still the same

Maybe can someone else check this too?

**Comment by illfated** [comment]
TrinityCore rev. 9c6e838083f1 2019-01-31 09:46:48 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

Start of table `rbac_permissions` :
```
id  name
--  ------------------------
 1  Instant logout
 2  Skip Queue
 3  Join Normal Battleground
 4  Join Random Battleground
 5  Join Arenas
 6  Join Dungeon Finder
 7  Skip idle connection check
```

```sql
SELECT * FROM `rbac_linked_permissions` WHERE `linkedId`=5;
```
```
 id  linkedId
---  --------
195         5
```
```sql
SELECT * FROM `rbac_default_permissions`;
```
```
secId  permissionId  realmId
-----  ------------  -------
    3           192       -1
    2           193       -1
    1           194       -1
    0           195       -1
```
I could be wrong, but it looks like all security levels are granted access to `Join Arenas` by default.
(At the moment, I don't remember which method is recommended to disable that permission.)

**Comment by illfated** [comment]
Thank you for the comment. I don't know for sure, but maybe one of the TC coders could post
a reply and say if your code change is usable or maybe enough to be made into a Pull Request.
