### ISSUE TITLE
Unable to send Quest Links in Chat

### ISSUE THREAD

**Issue by Meltie2013** [TrinityCore/TrinityCore#23002]
**Description:**

Players unable too send quest links in chat too groups, guilds or any near by player.

**Current behaviour:**

Players unable too send quest links in chat. Server appears too be blocking the links among sending them. Most likely related too the this PR made back in September https://github.com/TrinityCore/TrinityCore/pull/22417.

**Expected behaviour:**

Should be able send the links just like items and professions.

**Steps to reproduce the problem:**
1. Enable `UI.ShowQuestLevelsInDialogs` and start/restart your server.
2. Make any class or race and log into the game or use an existing character.
3. Go to any Quest Giver and choose a quest.
4. Try to send the Quest Link in chat `/s` or any chat channel for that matter.

**Log Output:**
```
Player Test (GUID: 4) sent a message with an invalid link:
 |cffffff00|Hquest:9487:16|h[[16] Arcane Reavers]|h|r
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/6026da0b6a0676d01def2583c56de856b88da389

**Operating system:** 

Debian 9 (Stretch)

**Related To**
https://github.com/TrinityCore/TrinityCore/pull/22417

**Comment by Meltie2013** [comment]
So we all know, this was a fresh pull and compile few days ago as marked in the hash/commit.

**Comment by Meltie2013** [comment]
Yes, I have that on currently.

**Comment by jackpoz** [comment]
as a workaround you could disable that custom config until the new link check takes that into account

**Comment by jackpoz** [comment]
This has been fixed by https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/e2353e7658bb81a6716a97dd47a266e8944b5705 and will stay in https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-custom_links branch but will not be merged into the main tc repo because of the changes required in how links are sanitized. Feel free to merge that branch in your custom fork.
