### ISSUE TITLE
Core: Reset() is not called on EscortAI::InitializeAI()

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23008]
**Description:** For scripts like https://github.com/TrinityCore/TrinityCore/commit/806dd940cec8352cc3a619b9cab39c95d7b86e59#diff-0f63a810cdcb3d6d4abb0497234168eaL279

If the npc must execute some actions upon summoned, if Reset() is used nothing happen as Reset() is called before the npc is added to the map.

If Reset() is replaced by JustAppeared() it work fine.

**Steps to reproduce the problem:**

1. revert https://github.com/TrinityCore/TrinityCore/commit/806dd940cec8352cc3a619b9cab39c95d7b86e59#diff-0f63a810cdcb3d6d4abb0497234168eaL279
2. .go game 150054 
3. .quest add 11253
4. use the item to summon the dog
5. the dog will not start the waypoint
6. Replace Reset() by  JustAppeared() and it will start the waypoint

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. b1604ba0cd6d

**Comment by jackpoz** [comment]
isn't this just the way it is and not an issue ?

**Comment by Killyana** [comment]
I don't know, it was working before Dynamic spawns, if it's the case all scripts that use Reset() with summoned npcs must be updated.

**Comment by jackpoz** [comment]
ah then it sounds more like a bug

**Comment by Ovahlord** [comment]
I think it might be related to some not so old change that was changing the order of the spawn handling due to some GetEntry stuff for faction related handlingd  instance scripts

**Comment by Killyana** [comment]
caused by https://github.com/TrinityCore/TrinityCore/commit/e4e6e2209c8ad6cc534460a4ec9f6da469761d15#diff-2270235252e23698c6d2c9a49eb35bb1
So we need to change all Reset() for escort scripts?

**Comment by Ovahlord** [comment]
According to the logic of that change, yes.

**Comment by Killyana** [comment]
I restored just the reset() and it works just fine

**Comment by jackpoz** [comment]
Does that reset the AI twice ?

**Comment by Killyana** [comment]
I don't know maybe @Treeston could help as it's his commit
