### ISSUE TITLE
[3.3.5]Core/Movement: Problems with GEODATA

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#23004]
Once again, I create a request to check the bug, which is present not only for me. This time the video was removed from the show team .server debug and .server info. The problem with the movement of the mobs on the texture is decided, but the problem with Valkyries is not. Please do not tell me what revision of GEODATA and not relevant. I even to collect GEODATA threw off the client on VDS and through Linux converted.

https://youtu.be/S5aRgQJ0VVk

https://github.com/TrinityCore/TrinityCore/issues/23003
https://github.com/TrinityCore/TrinityCore/issues/22995

Branch(es): **3.3.5**
TC rev. hash/commit: **#22994**
Operating system: **Debian 9**

**Comment by vahzxz** [comment]
I apologize for the transfer

**Comment by vahzxz** [comment]
The problem remained
https://hkar.ru/X9V9
https://hkar.ru/X9Va

**Comment by Killyana** [comment]
You must test on a flat ground, the issue happen only in special spots like the edge of the bridge, it's related to vmaps/mmaps not being perfectly precise.

**Comment by vahzxz** [comment]
@Killyana Already several times converted. I ask you to throw your converted map will be grateful

**Comment by Shauren** [comment]
I watched that video and basically, when a creature is flying we don't do pathfinding, we only do that for ground movement (won't fix)

**Comment by vahzxz** [comment]
@Shauren So you have in previous versions was all well. about a year and a half ago. You broke everything. It doesn't seem like it's worth revisiting the GEODATA corrections and revealing the wrong corrections.

**Comment by Shauren** [comment]
No, flying movement never used pathfinding (ever)

**Comment by vahzxz** [comment]
@Shauren I you can lead many cores implemented on Trinity. That is, almost all everyone is working and almost everyone I asked you why off paid GEODATA is not working and they said because I stopped to update Poltarev years ago. And besides, Valkyries are fine, the route the fact that they do not see the object under the ground
