### ISSUE TITLE
[3.3.5]Core/Movement: Problems with GEODATA

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#23003]
Again, I write about problems in GEODATA in Icecrown Citadel. Please check with yourself and give an answer if you have such a problem. Wrote already to other Russian system administrators they said that this problem is present, and nobody is going to correct it. In a config all GEODATA is included, also tried to disconnect it in General it led to deterioration of result.
Here is a screenshot of the problem
https://hkar.ru/X9u2

Branch(es): **3.3.5**
TC rev. hash/commit: **#22994**
Operating system: **Dibian 9**

**Comment by Aokromes** [comment]
you cheated us before. post the screenshot with .server info and .server debug content.

**Comment by vahzxz** [comment]
https://hkar.ru/X9ue
https://hkar.ru/X9uf

**Comment by vahzxz** [comment]
> https://hkar.ru/X9ue
> https://hkar.ru/X9uf
\

**Comment by Shauren** [comment]
That specific NPC? Probably just incorrect movement data in db, not a vmaps/mmaps issue

**Comment by vahzxz** [comment]
In the core and in the database there were no changes purely all over github. I have 10 already pumped source nothing helped not only with the Valkyrie with other creatures in this inst. For example, a creature jumps on textures.

**Comment by vahzxz** [comment]
Another is constantly spam this error. Although the conversion took extractors from the core
https://hkar.ru/X9uK

**Comment by Aokromes** [comment]
update your mmaps.
