### ISSUE TITLE
DB/Creature: Gold amount for wotlk Boss

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23013]
**Description:**
Gold amount is wrong or missing for almost all raid boss.

This issue is to gather the correct value for every boss/difficulty:

<table>
<tr><th>Boss</th><th>10nm</th><th>25nm</th><th>10hm</th><th>25hm</th></tr>
<tr><td>Baltharus the Warborn</td><th>600000/700000</th><th>1500000/1750000</th><th>600000/700000</th><th>1500000/1750000</th></tr>
<tr><td>General Zarithrian</td><th>600000/700000</th><th>1500000/1750000</th><th>600000/700000</th><th>1500000/1750000</th></tr>
<tr><td>Saviana Ragefire</td><th>600000/700000</th><th>1500000/1750000</th><th>600000/700000</th><th>1500000/1750000</th></tr>
<tr><td>Halion</td><th>2000000/2250000</th><th>2000000/2250000</th><th>2000000/2250000</th><th>2000000/2250000</th></tr>
<tr><td>Onyxia</td><th>800000/1200000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Tenebron</td><th>160000/200000 </th><th>400000/500000</th><th>none</th><th>none</th></tr>
<tr><td>Shadron</td><th>160000/200000 </th><th>400000/500000</th><th>none</th><th>none</th></tr>
<tr><td>Vesperon</td><th>160000/200000 </th><th>400000/500000</th><th>none</th><th>none</th></tr>
<tr><td>Sartharion</td><th>1800000/2000000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Malygos</td><th>1500000/1800000</th><th>2500000/3000000</th><th>none</th><th>none</th></tr>
<tr><td>Archavon the Stone Watcher</td><th>1700000/1900000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Emalon the Storm Watcher</td><th>1700000/1900000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Koralon the Flame Watcher</td><th>1700000/1900000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Toravon the Ice Watcher</td><th>1700000/1900000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Lord Marrowgar</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Lady Deathwhisper</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Gunship Battle</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Deathbringer Saurfang</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Festergut</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Rotface</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Professor Putricide</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Blood Prince Council</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Blood-Queen Lana'thel</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Valithria Dreamwalker</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>Sindragosa</td><th>800000/900000</th><th>2000000/2250000</th><th>1000000/1200000</th><th>2000000/2250000</th></tr>
<tr><td>The Lich King</td><th>1000000/1200000</th><th>2000000/2250000</th><th>1200000/1400000</th><th>2000000/2250000</th></tr>
<tr><td>Flame Leviathan</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Ignis the Furnace Master</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Razorscale</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>XT-002 Deconstructor</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Assembly of Iron</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Kologarn</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Auriaya</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Freya</td></td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Hodir</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Mimiron</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Thorim</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>General Vezax</td><th>1500000/1800000</th><th>2000000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Yogg-Saron</td><th>1800000/2000000</th><th>3000000/3250000</th><th>none</th><th>none</th></tr>
<tr><td>Algalon the Observer</td><th>1800000/2000000</th><th>3000000/3250000</th><th>none</th><th>none</th></tr>
<tr><td>Anub'Rekhan</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Grand Widow Faerlina</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Maexxna</td><th>1700000/1800000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Noth the Plaguebringer</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Heigan the Unclean</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Loatheb</td><th>1700000/1800000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Instructor Razuvious</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Gothik the Harvester</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>The Four Horsemen</td><th>1700000/1800000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Patchwerk</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Grobbulus</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Gluth</td><th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Thaddius</td><th>1700000/1800000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Sapphiron<th>1200000/1400000</th><th>2000000/2250000</th><th>none</th><th>none</th></tr>
<tr><td>Kel'Thuzad</td><th>1800000/2000000</th><th>2250000/2500000</th><th>none</th><th>none</th></tr>
<tr><td>Icehowl</td><th>800000-900000</th><th>2000000-2250000</th><th>900000-1000000</th><th>2250000-2500000</th></tr>
<tr><td>Lord Jaraxxusl</td><th>800000-900000</th><th>2000000-2250000</th><th>900000-1000000</th><th>2250000-2500000</th></tr>
<tr><td>Faction Championsl</td><th>800000-900000</th><th>2000000-2250000</th><th>900000-1000000</th><th>2250000-2500000</th></tr>
<tr><td>Twin Val'kyr: Fjola & Eydisl</td><th>800000-900000</th><th>2000000-2250000</th><th>900000-1000000</th><th>2250000-2500000</th></tr>
<tr><td>Anub'arak</td><th>900000-1000000</th><th>2250000-2500000</th><th>1000000-1100000</th><th>2500000-2700000</th></tr>
</table>

**Branch(es):**3.3.5

**TC rev. hash/commit:** rev. f04e90f63842

**Comment by Killyana** [comment]
The only way to get this data are videos from wotlk era like: https://youtu.be/aDUVgJjIyJg?t=143 we can see here the player get 6.28.72 gold it means the boss drops 628720 golds as it's 10 normal mode.
In this case min/max for Baltharus the Warborn in 10nm =600000/650000

**Comment by Jildor** [comment]
wtf, how you do to see all bosses in 19 hours? 🤣

**Comment by Faq** [comment]
Multitasking makes wonders but also mistakes :)

**Comment by Killyana** [comment]
Blizzard use the same amount for boss in the same raid, exception for end wings or the final boss, even if I checked every boss, it makes things easier.

Btw they changed the way that players got gold in raids since cata, instead of dropping the whole amount and divide it between players, they divide the amount by 10 or 25 according to the difficulty for every player, to avoid high amount of gold gathered in soloing raids. For this reason in Solo videos the amount is accurate once multilayered by 10 or 25.
