### ISSUE TITLE
[QUEST] Death Comes From on High

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#23017]
The eye of Akarusa descends and does not rise at all. There is only movement in 4 directions: Right, left, forward, backward. Up and down NO.

https://www.wowhead.com/quest=12641/death-comes-from-on-high

Branch(es): **3.3.5**
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/f04e90f638425c0e0ef2e40f0cd29ab7eec625d1
Operating system: **Debian 9**

**Comment by Aokromes** [comment]
#22802
