### ISSUE TITLE
[master] Crash Spell : Animal companion (267116) / missing SpellEffect

### ISSUE THREAD

**Issue by Jarts37** [TrinityCore/TrinityCore#23015]
**Description:**

Choosing the talent Animal Compagnon as Beast master hunter, cause crash

**Current behaviour:**

Choosing the talent Animal Compagnon as Beast master hunter, cause crash

**Expected behaviour:**

Not crashing

**Steps to reproduce the problem:**

1. Create character hunter, choose BM spec
2. Pick Animal Companion talent
3. crash

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/622c3c18859e11cb7fb4714fae662f44ae399111

**Operating system:** windows10 64b

**Comment by Jarts37** [comment]
Note : 
The spell have spell effect 493 (source wowhead :  Effect #1 | Apply Aura: ?? (Aura #493) )

According to https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L560
the last referenced spelleffect is 491, and by checking spelleffect.db2, this is the only spell with an effect > 491 (492 does not exist in any spells)

I think the problem is located here, two missing spelleffects in AuraEffectHandler list

**Comment by Shauren** [comment]
Correct.
