### ISSUE TITLE
[3.3.5] Event: Stranglethorn Fishing Extravaganza Turn-ins

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23011]
**Description:**
This event spawns the quest giver for the event.

**Current behaviour:**
DB shows that length is 180 (3 hours) but ingame, .event inf 62 shows:
- Length: 2 day(s)
- Next state change: 2019-05-03_00-00-00

Stranglethorn Fishing Extravaganza is a Sunday event and the quest giver is not in the realm when the pools are active.

**Expected behaviour:**
I have did some research and it looks like the NPC should spawn when the pools spawns and should be there for 3 hours.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** f04e90f
**Operating system:** Win 8.1

**Comment by TheWinchesters** [comment]
The weird thing is that "Start" changes after the event is active.
I discovered it the first week of January.
That week, .event info 62 showed that the 'Next state change' would be '2019-02-01' and it was active for 2 days. I waited because I thought that it would be ok after that date.
After last sunday, 'Start' and 'Next state change' are 2019-05-03_00-00-00

**Comment by illfated** [comment]
Maybe it is unstable because there is no correct time for event 62 in DB until the 3rd of May 2019 ?

**Comment by TheWinchesters** [comment]
> Maybe it is unstable because there is no correct time for event 62 in DB until the 3rd of May 2019 ?

I thought the same when .event info 62 was 'Start: 2019-02-01_00-00-00'.
Event started that day, and ended two days later.
After that, .event info 62 has a new 'Start' date.

**Comment by illfated** [comment]
Thanks for pointing out the details. Just a quick update on what is in TDB 335.64 @ rev. 33c58b4aaf4a 2019-02-03 17:01:05 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) :
```sql
SELECT * FROM `game_event` WHERE `description` LIKE '%Stranglethorn%';
```
```
eventEntry       start_time             end_time      occurence  length  holiday  holidayStage  description                                       world_event  announce
----------  -------------------  -------------------  ---------  ------  -------  ------------  ------------------------------------------------  -----------  --------
        14  2016-10-29 01:00:00  2020-12-31 06:00:00      10080    1440        0             0  Stranglethorn Fishing Extravaganza Announce                 0         2
        15  2016-10-30 15:00:00  2020-12-31 06:00:00      10080     120      301             0  Stranglethorn Fishing Extravaganza Fishing Pools            0         2
        62  2016-10-30 15:00:00  2020-12-31 06:00:00      10080     180      376             1  Stranglethorn Fishing Extravaganza Turn-ins                 0         2
```
The odd thing is that the `start_time` values look OK for now, because they have not yet been active.
But as you pointed out, something is going to change part of this content next time the event is active.

**Comment by TheWinchesters** [comment]
This is what I found:
event 62 has 'holiday' = 376
'holiday' field description: Holiday ID from  Holidays DBC file.
I have read Holidays.dbc and 376 has description 'Calendar_DarkmoonFaireTerokkar'.

Could this value be the cause of the problem?

**Comment by illfated** [comment]
That seems very likely. Could you also check what the _actual_ Holiday ID is for all 3 Stranglethorn Fishing Extravaganza events? I suspect that 2 or maybe all 3 event IDs are wrong.

**Comment by TheWinchesters** [comment]
301 and 424 have description Calendar_FishingExtravaganza
In the db, 301 is Stranglethorn Fishing Extravaganza and 424 is Kalu'ak fishing derby.
Using Kalu'ak event info in db (because it is a similar event and that one is working correctly), I did the same with Stranglethorn Fishing Extravaganza and removed holiday = 376 for eventid 62. Looks like it works.

I noticed this because Darkmoon faire (Mulgore) and Darkmoon faire Building (Mulgore) are wrong too.
Both of them are active at the same time.

**Comment by illfated** [comment]
Nice. Would you like to propose a solution by posting the necessary SQL code block in your next comment? I am out in the woods, in my friend's cabin, so I only got my phone here. (Will be home again in the evening, though.)

**Comment by illfated** [comment]
Just to get some more feedback: Would it not be correct to add the holiday ID to all 3 events? i.e. / e.g.
```sql
--  Stranglethorn Fishing Extravaganza holiday ID (301)
UPDATE `game_event` SET `holiday`=301 WHERE `eventEntry` IN (
 14,  -- Stranglethorn Fishing Extravaganza Announce
 15,  -- Stranglethorn Fishing Extravaganza Fishing Pools
 62); -- Stranglethorn Fishing Extravaganza Turn-ins
```

**Comment by TheWinchesters** [comment]
Not sure what is the best solution. This is what I thought:
- Kalu'ak Fishing Derby Turn-ins works
- Kalu'ak Fishing Derby Turn-ins has holiday = 0 and holidayStage = 0
- Let's do the same with Stranglethorn Fishing Extravaganza Turn-ins to see what happens.
It worked.

```sql
UPDATE `game_event` SET `holiday` = '0', `holidayStage` = '0' WHERE (`eventEntry` = '62');
```

And for Darkmoon Faire Building events:
I have used event Darkmoon Faire Building (Elwynn Forest) as example because it is the only one who works correctly
```sql
UPDATE `game_event` SET `length` = '4320', `holiday` = '375', `holidayStage` = '1' WHERE (`eventEntry` = '71');
UPDATE `game_event` SET `length` = '4320', `holiday` = '376', `holidayStage` = '1' WHERE (`eventEntry` = '77');
```

**Comment by illfated** [comment]
Fair enough, looks like you have done some testing too.
TC SQL codestyle tip: remove apostrophes around numbers
(except for aura IDs when field is defined as `text`).

Example:
```sql
-- Stranglethorn Fishing Extravaganza Turn-ins
UPDATE `game_event` SET `holiday`= 0, `holidayStage`= 0 WHERE (`eventEntry`= 62);

-- Darkmoon Faire Building (Mulgore / Terokkar Forest)
UPDATE `game_event` SET `length`= 4320, `holiday`= 375, `holidayStage`= 1 WHERE (`eventEntry`= 71);
UPDATE `game_event` SET `length`= 4320, `holiday`= 376, `holidayStage`= 1 WHERE (`eventEntry`= 77);
```
(yes, I know that SQL editors often put apostrophes around number values in the output window)

**Comment by LordWaycrest** [comment]
I'm assuming there is a fix confirmed, when will this fix be made official?

**Comment by illfated** [comment]
Unfortunately, there is no confirmed fix yet (at least that I know), I have not had time to test anything useful myself. I was hoping someone else would post a useful suggestion for further testing, but that has not happened yet.

@offl : Do you have any suggestions for how to solve this?

**Comment by offl** [comment]
Test https://github.com/TrinityCore/TrinityCore/issues/23011#issuecomment-490624237? :)

**Comment by illfated** [comment]
@offl : Thank you for your reply, we should definitely test it.
@jackpoz : Could we add that to the current TC server or maybe on a test server?

**Comment by LordWaycrest** [comment]
> @offl : Thank you for your reply, we should definitely test it.
> @jackpoz : Could we add that to the current TC server or maybe on a test server?

Probably best on a test server since we are testing.

**Comment by illfated** [comment]
Not many people are using the TC server, mainly 1 at a time (Aokromes, jackpoz, sometimes me, maybe Killyana).
https://tcubuntu.northeurope.cloudapp.azure.com/

**Comment by LordWaycrest** [comment]
Is it open to the public? I don't mind coming to help test

**Comment by illfated** [comment]
Currently, tcubuntu.northeurope.cloudapp.azure.com is using the straight unchanged 3.3.5 source from the TC repository.

That is why I asked jackpoz if the SQL above can be added somewhere, because I currently don't have a local core or working compile setup on my computer.

**Comment by LordWaycrest** [comment]
> Currently, tcubuntu.northeurope.cloudapp.azure.com is using the straight unchanged 3.3.5 source from the TC repository.
> That is why I asked jackpoz if the SQL above can be added somewhere, because I currently don't have a local core or working compile setup on my computer.

I have a public test realm, if that's any good?

**Comment by illfated** [comment]
I presume I will have to return to this topic next weekend, since the main point here is to test if the changes will make the Stranglethorn Fishing Extravaganza events work as on retail (Blizzard), which is in the timeframe 14:00 - 16:00 (server time) every Sunday.

**Comment by LordWaycrest** [comment]
> I presume I will have to return to this topic next weekend, since the main point here is to test if the changes will make the Stranglethorn Fishing Extravaganza events work as on retail (Blizzard), which is in the timeframe 14:00 - 16:00 (server time) every Sunday.

I can apply that SQL to the database and go from there, unless you want to wait.

**Comment by illfated** [comment]
> > I presume I will have to return to this topic next weekend, since the main point here is to test if the changes will make the Stranglethorn Fishing Extravaganza events work as on retail (Blizzard), which is in the timeframe 14:00 - 16:00 (server time) every Sunday.
> 
> I can apply that SQL to the database and go from there, unless you want to wait.

Sure thing, feel free to apply the SQL. The more servers we can test it on, the better chance we stand to find out if it is the solution. 👍

**Comment by illfated** [comment]
BTW, I recommend using the TC SQL codestyle format:
```sql
-- Stranglethorn Fishing Extravaganza Turn-ins
UPDATE `game_event` SET `holiday`= 0, `holidayStage`= 0 WHERE (`eventEntry`= 62);

-- Darkmoon Faire Building (Mulgore / Terokkar Forest)
UPDATE `game_event` SET `length`= 4320, `holiday`= 375, `holidayStage`= 1 WHERE (`eventEntry`= 71);
UPDATE `game_event` SET `length`= 4320, `holiday`= 376, `holidayStage`= 1 WHERE (`eventEntry`= 77);
```
(<== Original solution by @TheWinchesters ==>)

**Comment by LordWaycrest** [comment]
> BTW, I recommend using the TC SQL codestyle format:
> -- Stranglethorn Fishing Extravaganza Turn-ins
> UPDATE `game_event` SET `holiday`= 0, `holidayStage`= 0 WHERE `eventEntry`= 62;
> 
> -- Darkmoon Faire Building (Mulgore / Terokkar Forest)
> UPDATE `game_event` SET `length`= 4320, `holiday`= 375, `holidayStage`= 1 WHERE `eventEntry`= 71;
> UPDATE `game_event` SET `length`= 4320, `holiday`= 376, `holidayStage`= 1 WHERE `eventEntry`= 77;
> (<== Original solution by @TheWinchesters ==>)

I'll make you an account and PM details if you want.

Realmlist is beta.eu.logon.ideagaming.com

**Comment by illfated** [comment]
Thanks, I will have to get back to you on that later. I need to get some sleep before I start my regular work week (9;00-5:00 CET, with 1 hour additional travel time before & after).

**Comment by LordWaycrest** [comment]
> Thanks, I will have to get back to you on that later. I need to get some sleep before I start my regular work week (9;00-5:00 CET, with 1 hour additional travel time before & after).

Okay matey, have a good one :)

**Comment by Jildor** [comment]
Seems wrong holiday yes, added here: https://github.com/TrinityCore/TrinityCore/commit/951fa46fe9b14a9e275ac9306b2346959e40e3e5#diff-07e3e9dbb0ea1e070fc108901cf6f155R187

@Killyana we could push https://github.com/TrinityCore/TrinityCore/issues/23011#issuecomment-583908954 ?

**Comment by TheWinchesters** [comment]
The notification of this almost gave me a heart attack.
Thank you.
