### ISSUE TITLE
Quest Massacre At Lights Point

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#23018]
After completing the quest the gun has spell sending home. The problem is that the dragon has to fly, not run on the ground. And PS don't give just run. What causes dismount

https://youtu.be/TzW4bpAeIFM
https://www.wowhead.com/quest=12701/massacre-at-lights-point

Branch(es): **3.3.5**
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/f04e90f638425c0e0ef2e40f0cd29ab7eec625d1
Operating system: **Debian 9**

**Comment by Killyana** [comment]
You have clearly a problem in your server, but impossible to say what's exactly cause it.
https://imgur.com/a/X2thZIq

**Comment by vahzxz** [comment]
@Killyana What can be problems using LAST revision of the kernel. I'm asking you again. Please throw off on any file sharing your cards. Once. To this problems disappeared. Thank you in advance.

**Comment by vahzxz** [comment]
@Killyana No, I've tried worse. So and am asking your maps
There are suspicions that Russian customers are inadequately exporting maps

**Comment by illfated** [comment]
Maybe I misunderstand you, but it looks to me as if you are saying that the Russian game clients could cause maps to be incorrectly extracted.

If that is a correct interpretation, I suggest that you try downloading (p2p) a complete 3.3.5a, **en-GB** or **en-US** game client only to extract maps/vmaps/mmaps and then use those in your server.

**Comment by vahzxz** [comment]
@illfated I was looking for an English-speaking client there is no official client. Perhaps not looking hard enough. Please even used to give a link to the client

**Comment by vahzxz** [comment]
Right now I will try to download the English client
