### ISSUE TITLE
[3.3.5] Spell Stacking Highest Effect

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#23019]
**Description:**
Spell Stacking is broken. SPELL_GROUP_STACK_RULE_EXCLUSIVE_HIGHEST should make the group entry with the highest aura amount be active.

For example Totem of Wrath gets not overwritten by Demonic Pact (47240 - Talent, 48090 Aura) if the basepoints are higher from Demonic Pact.

**Expected behaviour:**
The aura with the highest amount should be active.

**Steps to reproduce the problem:**
```
.learn 688
.learn 47240
.learn 47193 
.learn 57722
.add 5176
```

Learn Summon Imp, learn Demonic Pact, learn Demonic Empowerment to boost Pet crit chance, learn Totem of Wrath, add Totem of Wrath. Summon Totem, summon Pet, give pet Demonic Empowerment 
and let it crit with Firebolt.

If you have above 2850 Spellpower Demonic Pact should overwrite Totem of Wrath.
Here is a macro to get 3,5k spellpower:
```
.aura 52810 
.aura 48626 
.aura 54192 
.aura 69709 
.aura 40142  
.aura 35902
.aura 36385
.aura 35898 
```

**Branch(es):**

3.3.5, maybe master?

**TC rev. hash/commit:** 
42edba699dc8f47084756a4e3ab7d85ea96e81fb

**Comment by robinsch** [comment]
Related code parts:

bool Unit::IsHighestExclusiveAura(Aura const* aura, bool removeOtherAuraApplications /*= false*/)
void Unit::_RemoveNoStackAurasDueToAura(Aura* aura)

**Comment by robinsch** [comment]
Fixes this specific issue but will probably break other stuff.

```
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -3925,23 +3925,6 @@ void Unit::_RemoveNoStackAurasDueToAura(Aura* aura)
 {
     SpellInfo const* spellProto = aura->GetSpellInfo();
 
-    // passive spell special case (only non stackable with ranks)
-    if (spellProto->IsPassiveStackableWithRanks())
-        return;
-
-    if (!IsHighestExclusiveAura(aura))
-    {
-        if (!aura->GetSpellInfo()->IsAffectingArea())
-        {
-            Unit* caster = aura->GetCaster();
-            if (caster && caster->GetTypeId() == TYPEID_PLAYER)
-                Spell::SendCastResult(caster->ToPlayer(), aura->GetSpellInfo(), 1, SPELL_FAILED_AURA_BOUNCED);
-        }
-
-        aura->Remove();
-        return;
-    }
-
     bool remove = false;
     for (AuraApplicationMap::iterator i = m_appliedAuras.begin(); i != m_appliedAuras.end(); ++i)
     {
```

**Comment by Keader** [comment]
Was not SpellGroups issue, was Demonic Pact fault.
Spell Healing effect was not getting correct basepoints and always stay in "1".
So totem of wrath was always more powerfull.
