### ISSUE TITLE
Creature/Script: Anub'Arak TOC

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23010]
**Description:** ~~On 10 mode only one Nerubian Burrower spawn instead of 2 and on 25 mode only 2 Nerubian Burrower spawns instead of 4.~~

Once under ground there's no spikes at all.

**Branch(es):**3.3.5

**TC rev. hash/commit:**  rev. f04e90f63842

**Comment by TheWinchesters** [comment]
Nerubian Burrower:
According to this, there is a difference between Normal and heroic modes:
https://wow.gamepedia.com/Anub%27arak_(Trial_of_the_Crusader_tactics)
10N: 1
10H: 2
25N: 2
25H: 4

**Comment by Killyana** [comment]
Yes, so there's only an issue with the spikes

**Comment by Keader** [comment]
Last fix about it: https://github.com/TrinityCore/TrinityCore/commit/8b9d18f29ca5febf27328634ef1323ea890b40c4

**Comment by kuskmen** [comment]
So this has to be closed?

**Comment by Killyana** [comment]
No still no spikes

**Comment by AByakugans** [comment]
Hello, anything new about this boss? This is ghe only problem in this instance. Also not sure his ability leech is working ok.

**Comment by Vasago** [comment]
Hello, anything new about this? Spikes are still not working ok nor Leech.

**Comment by MeluS** [comment]
anything new about this?

**Comment by Jildor** [comment]
Can be closed ;)
