### ISSUE TITLE
Core/Combat: Auto Attacking Creatures

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#23012]
**Description:**
Character does not automatically attack creatures in melee (ranged not checked), although abilities are attacking normally. When this happens, creature shortly evades, therefore making any combat and the whole game pretty unplayable.

**Steps to reproduce the problem:**

1. `.go c id 23989`.
2. Start melee combat with creature. Do not use special abilities.
3. Notice that your character won't automatically attack creature, and creature shortly evades.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. f04e90f63842+ 2019-02-02 21:51:04 +0100 (3.3.5 branch) (Unix, Debug, Static)
Using SSL version: OpenSSL 1.1.0g  2 Nov 2017 (library: OpenSSL 1.1.0g  2 Nov 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.7.25
Using CMake version: 3.10.2
Compiled on: Linux 

**Operating system:** Ubuntu 18.04

**Comment by Killyana** [comment]
I cannot reproduce the issue on rev. f04e90f63842

**Comment by Sorikoff** [comment]
I am using clean sources and DB. Maybe there is something in the config?

**Comment by Killyana** [comment]
Don't think so, which class and weapon are using?

**Comment by Killyana** [comment]
Did you tested with an other character?

**Comment by Sorikoff** [comment]
Resolved with new character.
