### ISSUE TITLE
[3.3.5] ICC: Vile gas

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23020]
**Description:**
Spell: Vile gas (https://db.rising-gods.de/?spell=72273)
Desc: "Inflicts a Vile plague in targeted area, inflicting 4875 to 5125 damage every 2 sec for 6 sec. The plague causes the infected targets to vomit uncontrollably inflicting 3900 to 4100 damage to nearby allies."
This spells is used by Festergut https://es.wowhead.com/npc=36626

**Current behaviour:**
Some recent change has broken this spell.
The player vomits but it does not lose control.

**Expected behaviour:**
Player should lose control of his character if he is affected by this spell.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** f04e90f638425c0e0ef2e40f0cd29ab7eec625d1
**Operating system:** Win 8.1

**Comment by illfated** [comment]
Thank you for making me smile & grin with this issue, "Vile gas". 😄
You just reminded me of all the inevitable/unavoidable fart jokes
occurring on retail back in 2009-2010 when raiding ICC content.

**Comment by Azland** [comment]
@TheWinchesters I'm unable to reproduce this one by fighting Festergut in ICC25. Vile plague is causing 'disorientation' and loss of control every time I'm hit by it. Human racial removes it when used. 
Any steps I'm missing here?
