### ISSUE TITLE
[Crash] pet->AI & KilledUnit

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23036]
Description: pet->AI()->KilledUnit(victim);

Crash log
https://gist.github.com/HAANAAE/2f0cffb8d7a4aee96d859bf18e141c25

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/2fda1572d214d0b114e0291106363f49c2d3179e
Operating system: debian

**Comment by jackpoz** [comment]
maybe it's worth adding an assert on pet->AI()

**Comment by Shauren** [comment]
I'm not sure about what happened here... a mind controlled player that has a pet?

**Comment by jackpoz** [comment]
maybe a mind controlled player killed his own pet ? could anyone try to repro this case ?

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/43dec9e4d0b6f7da3c2051624742e9fb8a9bcb31

**Comment by Aokromes** [comment]
no answer after > 2 months, closing, if this bug is still valid open a NEW ticket with updated core.

**Comment by jackpoz** [comment]
@Aokromes this is actually the same as https://github.com/TrinityCore/TrinityCore/issues/23211

**Comment by jackpoz** [comment]
Most likely caused by the way https://github.com/TrinityCore/TrinityCore/commit/d4ef2529e91043bc719c3238714413fd21c9005c#diff-4522eeffcbc961602e86620011a2d579R11550 works

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/70fcdc687d1227a796c03f6353fc8dbfc4f4aea3
