### ISSUE TITLE
Client freeze on Ulduar

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23042]
**Description:**

Client freezes on ulduar

**Current behaviour:**

Client freezes on ulduar

**Expected behaviour:**

No freeze :P

**Steps to reproduce the problem:**

0. gm fly on
1. kill Kologarn .go c id 32930
2. take teleport to mimiron (spark of imagination)
3. take teleport back to Kologarn
4. client freezes.
(using .dam will work too)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2fd9b3f394d9

**Operating system:** Debian 9 x64.

**Comment by Aokromes** [comment]
(it looks you can tele to Kologarn, kill it, take teleport to mimiron and return with same result)

**Comment by jackpoz** [comment]
Direction: STC Opcode: [SMSG_COMPRESSED_UPDATE_OBJECT 0x01F6 (502)] is the last opcode sent before freezing the client (debugged it)

**Comment by micckkk** [comment]
> Shauren added a commit that referenced this issue 16 days ago 

Core/Movement: Prevent rooted units from falling …  

problem still exist

**Comment by jackpoz** [comment]
any how to reproduce steps ? which revision ?

**Comment by TheWinchesters** [comment]
Rev. f1ab05ab46a559f99bf5c086228eb011dff10f02
I could not reproduce the issue explained here (Kologarn / Ulduar) but you can freeze client if:
- Use 2 chars (one must be a mage with Ice block)
- .go c id 36789
- .inst setb 0 3 (up to boss 9)
- Start the encounter
- When portals spawn, use the mage and enter (only the mage)
- Once inside, use Ice Block
- Switch to the char that did not enter the portals and it will be frozen

**Comment by jackpoz** [comment]
could you open a new issue with those steps ?

**Comment by jackpoz** [comment]
Issue is being tracked at https://github.com/TrinityCore/TrinityCore/issues/23320
