### ISSUE TITLE
DB/SAI: Shoveltusk Stag

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#23041]
**Description:**
Implement scripts for Howling Fjord NPC Shardhorn Rhino ([23691](https://woehead.way-of-elendil.fr/?npc=23691)).

**Branch(es):**
3.3.5 and master

**TC rev. hash/commit:** 
TrinityCore rev. 59682bbd9b333a8e6dbfd3c6884b16afdb510197 2019-01-12 12:16:23 +0100 (3.3.5 branch) (Unix, Debug, Static) (worldserver-daemon)

**TDB version:** 335.64

**Operating system:** *nix

**Suggested Fix:**
```sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=23691;
DELETE FROM `smart_scripts` WHERE `entryorguid`=23691 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(23691,0,0,0,0,0,100,0,5000,9000,7000,12000,11,32019,0,0,0,0,0,2,0,0,0,0,0,0,0,"Shoveltusk Stag - In Combat - Cast 'Gore'");
```

**Comment by illfated** [comment]
Note: `creature_template`.`entry` 23691 = Shoveltusk Stag (you may want to change your issue title & comments, the SAI comment line for the spell "Gore" looks OK).
- https://www.wowhead.com/npc=23691/shoveltusk-stag#abilities
- https://www.wowhead.com/spell=32019/gore
- https://www.wowhead.com/npc=28009/shardhorn-rhino#abilities

(Shardhorn Rhino uses Gore too, in case that is what confused you.)

BTW, the spell https://www.wowhead.com/spell=55193/rhino-charge is not listed on the page shardhorn-rhino#abilities, but the spell page links back to the page https://www.wowhead.com/npc=28009/shardhorn-rhino .

Do you have any sniff or log showing that Shoveltusk Stag uses Rhino Charge?

**Comment by Sorikoff** [comment]
Excuse me. Got it all wrong.

**Comment by illfated** [comment]
No worries. Someone would have mentioned it sooner or later.

BTW, I also mentioned the issue comment - you may want to change the creature name there too:
> **Description:**
> Implement scripts for Howling Fjord NPC **Shardhorn Rhino** ([23691](https://woehead.way-of-elendil.fr/?npc=23691)).
>

**Comment by Sorikoff** [comment]
Sure. Done! Thanks!
