### ISSUE TITLE
Worldserver crashes on authserver update

### ISSUE THREAD

**Issue by jphax** [TrinityCore/TrinityCore#23044]
**Description:**

The worldserver crashes on first launch with an error about a duplicate filename: 

Duplicate filename "/home/theguy/TrinityCore/sql/updates/auth/3.3.5/2018_02_19_00_auth.sql" occurred. Because updates are ordered by their filenames, every name needs to be unique!

**Current behaviour:**
it succesfully updated world and cahracter databases but on auth it crashes. heres the full output if i run it again:

TrinityCore rev. 12e6faa0fa0c 2019-02-08 22:21:03 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/theguy/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Updating Auth database...
Duplicate filename "/home/theguy/TrinityCore/sql/updates/auth/3.3.5/2018_02_19_00_auth.sql" occurred. Because updates are ordered by their filenames, every name needs to be unique!
Could not update the Login database, see log for details.

when i look in the database in phpmyadmin it seems filled.
when i delete the supposedly duplicated file, adn the ones it complains about after that, or when i disable updates in the config file, it just spits out a lot of sql errors about tables not existing.

**Expected behaviour:**

It should update the database and not crash.

**Steps to reproduce the problem:**

1. clone 3.3.5 branch  
2. build server
3. download db TDB_full_world_335.64_2018_02_19.7z and extract
4. run worldserver

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 12e6faa0fa0c 2019-02-08 22:21:03 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Ubuntu 17.10

**Comment by jphax** [comment]
renaming the files fixed it for me, but it said the original fiels were still there also.

**Comment by illfated** [comment]
TrinityCore source does not have any duplicates in that folder:
- https://github.com/TrinityCore/TrinityCore/tree/3.3.5/sql/updates/auth/3.3.5
```
2018_02_19_00_auth.sql
2018_03_06_00_auth.sql
2018_03_08_00_auth.sql
2018_06_23_00_auth.sql
2018_08_30_00_auth.sql
2018_09_06_00_auth.sql
2018_09_17_00_auth.sql
2018_12_30_00_auth.sql
```
I don't know how, but it is most likely that something you did created a duplicate file.

**Comment by jphax** [comment]
my folder looked exactly the same, and removing the files resulted in errors, while renaming them fixed the problem.

or maybe i twas because i had also pulled update folders of master branch and it tried to apply them. after deleting those everything worked fine

**Comment by illfated** [comment]
Oh. I see. That is very likely. The duplicate file had to come from somewhere.
I recommend that you close this issue now that you know where it failed.
