### ISSUE TITLE
Holy wrath deals no damage

### ISSUE THREAD

**Issue by lactoseti** [TrinityCore/TrinityCore#23056]
**Description:**

Holy wrath does no damage.

**Current behaviour:**

Holy wrath does no damage.

**Expected behaviour:**

Holy wrath should do damage to all types, only stun certain types.

**Steps to reproduce the problem:**

Cast holy wrath.

**Branch(es):**

3.3.5

TC rev. hash/commit: [58c5dfa](https://github.com/TrinityCore/TrinityCore/commit/58c5dfac1d8d314b9243fde52466b3c933fb7d7f)
Os: windows 2016 server

**Comment by Aokromes** [comment]
acording this https://github.com/TrinityCore/TrinityCore/issues/9684 your issue is incorrect.

**Comment by lactoseti** [comment]
It shouldn't *stun* everyone, but it does *damage* to everyone.  See the
text here:

https://wotlk-twinhead.twinstar.cz/?spell=48817
Sends bolts of holy power in all directions, causing xxx to xxx Holy damage
and stunning all Undead and Demon targets within 10 yds for 3sec.

**Comment by ratkosrb** [comment]
Maybe my memory is wrong, but i believe they changed it to damage all types of enemies in cataclysm, so in 3.3.5 it should not damage non undead/demon targets.

**Comment by Killyana** [comment]
No it must deals damage to all creature and stun only demons and undeads, the issue is Creature Type Mask = 0x00000024 (DEMON, UNDEAD) is applied to effect 1 and effect 2, it must be use only by : Effect #2 | Apply Aura: Stun

.go c id 31787  and .cast 48817 you will damage the npc and it will be sunned as it's an undead

**Comment by ratkosrb** [comment]
In the WowWiki article on the spell it says this:
```
Holy Wrath cannot damage Forsaken NPCs or players, who are Humanoid (not Undead), except for the Abomination guards in Undercity because they are classified as Undead. 
```

https://wowwiki.fandom.com/wiki/Holy_Wrath?oldid=2366144

**Comment by Shauren** [comment]
Well, that looks pretty much as "working as intended" to me

**Comment by Killyana** [comment]
Yes the tool-tip is not clear.

**Comment by gmillerd** [comment]
> Maybe my memory is wrong, but i believe they changed it to damage all types of enemies in cataclysm, so in 3.3.5 it should not damage non undead/demon targets.

The glyph provided "Your Holy Wrath now also stuns Elementals, Dragonkin, and Aberrations", which is a serious DR for a pile of encounters. (Heathstone spell flavor text of "C'mon Molten Giant!!")
