### ISSUE TITLE
DB/Creature: Dying Blood Elf should have 1HP

### ISSUE THREAD

**Issue by Serpaa** [TrinityCore/TrinityCore#23063]
**Description:**

Dying Blood Elf should have 1HP and not regenerate.

https://www.wowhead.com/npc=16601/dying-blood-elf

**Current behaviour:**

He's full HP.

**Branch(es):**

Both

**TC rev. hash/commit:** 

c8dfab776133

**Suggested Fix:**

```sql
-- Update Dying Blood Elf to 1 HP
UPDATE `creature` SET `curhealth`=1 WHERE `id`=16601; 
UPDATE `creature_template` SET `RegenHealth`=0 WHERE `entry`=16601;
```

**Comment by illfated** [comment]
Thank you for this update. The TDB needs similar updates for several other dead or near-death NPCs, but I don't have any sniff data to base any actual suggestions for the SQL query updates. The best I can do is to open new issues for those corpses or dying NPCs who display 100% HP in-game. Should I open an issue for each NPC , or list all the NPCs in need of update in a single issue ticket?
