### ISSUE TITLE
[3.3.5] chat commands with "trigered" instead of "triggered"

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#23065]
**Description:**

Some commands have "trigered" in the help instead of "triggered"

| name | permission | help |
| --- | --- | --- |
cast back | 268 | Syntax: .cast back #spellid [triggered] Selected target will cast #spellid to your character. If '**trigered**' or part provided then spell casted with triggered flag.
cast dist | 269 | Syntax: .cast dist #spellid [#dist [triggered]] You will cast spell to pint at distance #dist. If '**trigered**' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.
cast self | 270 | Syntax: .cast self #spellid [triggered] Cast #spellid by target at target itself. If '**trigered**' or part provided then spell casted with triggered flag.
cast target | 271 | Syntax: .cast target #spellid [triggered] Selected target will cast #spellid to his victim. If '**trigered**' or part provided then spell casted with triggered flag.
cast | 267 | Syntax: .cast #spellid [triggered] Cast #spellid to selected target. If no target selected cast to self. If '**trigered**' or part provided then spell casted with triggered flag.
cast dest | 272 | Syntax: .cast dest #spellid #x #y #z [triggered] Selected target will cast #spellid at provided destination. If '**trigered**' or part provided then spell casted with triggered flag.

```sql
SELECT * FROM command WHERE HELP LIKE '%trigered%'
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

76cc94f325ab68f66a4fa7b5d30316508e27c0ce

**Operating system:** Win10

**Comment by illfated** [comment]
When I see stuff like that, I somehow wish that the specific sentence containing the typo had been part of its own column, making it easier to do a regexp search & replace.

Then again, I presume it can be easily done by exporting the search query result to SQL file and edit that file in [insert favorite ASCII text editor here] and post the content to this issue.

**Comment by jackpoz** [comment]
now that you mention it, it's easy with MySQL
```sql
UPDATE `command` SET `help` = REPLACE(`help`, 'trigered', 'triggered');
```

**Comment by illfated** [comment]
Good call, very nice and smooth. I will test it as soon as I have recompiled and rebuilt my 335_world DB.

**Comment by illfated** [comment]
Heh, right. I was a bit too slow, working on Microsoft Docs instead of doing what I said earlier. Oh well. 😄
