### ISSUE TITLE
[Crash] BIH::intersectRay

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#23074]
**Description:**

Core freezes in BIH::intersectRay,

Relevant Positions
_startPosition 4963.540039 5860.516113 -65.350929
_endPosition  4991.889160 5889.807129 -63.911865
start = {x = 4961.76709, y = 5855.54395, z = -65.2397156}
dest = {x = 4990.77686, y = 5891.15967, z = -63.481739}

CrashLog: https://gist.github.com/sirikfoll/7e6bd31912dd71c7ea67ac5b87d510f5

<details>

![wowscrnshot_022519_165311](https://user-images.githubusercontent.com/11219553/53364989-d7924400-391e-11e9-97ab-191888c904c6.jpg)
</details>

**Steps to reproduce the problem:**

Not precise at all, but..
1. .go xyz 4990.750488 5891.492188 -64.037643 571
2. .mod speed all 6
3. .cast 42650 (summon Army of the Dead)
4. Run with your character around the small wooden tents

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  f17120cc784e

**Comment by Shauren** [comment]
> float tf = -nan(ind)
doesnt look too good

**Comment by jackpoz** [comment]
probably a missing std::isfinite() check in latest recastnavigation changes (and I'd say there will be more issues like this until we/they fix them all)

**Comment by jackpoz** [comment]
For debugging purposes one can set /fp:strict and then _controlfp_s(&oldStateFP, 0x0, _MCW_EM) which will cause an exception whenever nan(ind) is triggered

**Comment by jackpoz** [comment]
Hardened the checks in https://github.com/TrinityCore/TrinityCore/commit/c602220e02bed1ad76c9e60064eeec5fd97bfe80 , let us know if you find another place where it happens
