### ISSUE TITLE
[3.3.5] Ephemeral Snowflake proc

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23078]
**Description:**
Ephemeral Snowflake: https://www.wowhead.com/item=50260
"Equip: You gain 11 mana each time you heal a target with one of your spells."

**Current behaviour:**
You gain 11 mana with a lot of spells that does not heal.

**Expected behaviour:**
What the tooltip says, I guess.

Some examples where you will gain 11 mana casting these spells:
Blessing of Might
Righteous Fury
Hand of Freedom
Hand of Protection
Divine Illumination
Any Seal (paladin)
Find Herbs

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 2ebaa9fa86a2
**Operating system:** Win 8.1

**Comment by Killyana** [comment]
Proc flag 0x00044000, chance = 100, charges - 0
=================================================
  14 Successful cast positive magic spell
  18 Deal periodic damage

**Comment by illfated** [comment]
Would it be useful to know that some non-player (cheat) damaging spells also gives a lot of mana to the caster?
When I want to shorten a fight between my character and NPCs in-game, I use Argent Cannon Assault (ID 57387)
(https://www.wowhead.com/spell=57387/argent-cannon-assault), which feeds more mana to the player than
what would normally be obtainable through potions etc.

**Comment by Keader** [comment]
```sql
DELETE FROM `spell_proc` WHERE `SpellId`=71567;
INSERT INTO `spell_proc` (`SpellId`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask0`,`SpellFamilyMask1`,`SpellFamilyMask2`,`ProcFlags`,`SpellTypeMask`,`SpellPhaseMask`,`HitMask`,`AttributesMask`,`ProcsPerMinute`,`Chance`,`Cooldown`,`Charges`) VALUES
(71567,0,0,0,0,0,0,2,2,0,0,0,0,0,0);

```

Check if work

**Comment by Killyana** [comment]
Still proc with  Sheath of Light.

**Comment by Keader** [comment]
Should not proc with Sheath of Light?
Because it has a periodic heal effect
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET)
Aura Id 8 (SPELL_AURA_PERIODIC_HEAL), value = 0, misc = 0 (0), miscB = 0, periodic = 3000
```

**Comment by Killyana** [comment]
Yes it's correct

**Comment by Keader** [comment]
@TheWinchesters Can you test it?

**Comment by Killyana** [comment]
The proc must have 0.4 Secs of CD https://woehead.way-of-elendil.fr/?spell=71567  when I tested I get 4 procs in 1 sec.

**Comment by Keader** [comment]
Updated in https://github.com/TrinityCore/TrinityCore/issues/23078#issuecomment-468419870
