### ISSUE TITLE
[3.3.5] Crash: SplineChainMovementGenerator::SendSplineFor: referenced index (1) higher than path size (1)!

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23077]
**Description:**
Nightbane (NPC=17225, Karazhan boss) has a Flight phase and then comes back to the ground.
If a player uses Death Grip while Nightbane is flying back to the ground, worldserver will crash.
Reason:
`SplineChainMovementGenerator::SendSplineFor: referenced index (1) higher than path size (1)!`

**Steps to reproduce the problem:**
1. .learn 49576  
2. go gameobj 334
3. Activate the gobject
4. Do some damage till his health hits 75%, 50%, or 25%
5. Wait till he starts flying to come back to the ground.
6. Cast Death Grip before he touches the ground.

**Crashlog:** https://gist.github.com/TheWinchesters/315bfa85158c7c3c864d50fd9cbdd6a7
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 2ebaa9fa86a2
**Operating system:** Win 8.1

**Comment by TheWinchesters** [comment]
I still can, using rev. fe311260f7fab3b6fb4d7dd2ee88826820379d94
To reproduce it, Death Grip must be used at some point when Nightbane is close to the floor.
This is where Nightbane was when the crash happened:
https://imgur.com/a/7u57MJQ

**Comment by jackpoz** [comment]
is the crashlog the full file or only a part ? is it possible to get a crashlog in Debug ?

**Comment by TheWinchesters** [comment]
Rev. 16bf11ab20fcd5e3984dd90d011d13f56288d1ea
Debug mode
https://gist.github.com/TheWinchesters/bb73fd6e7b84bb2bd53159d90759f142

**Comment by jackpoz** [comment]
try with https://github.com/jackpoz/TrinityCore/commit/7a8dc13c7d69df0bdd27ea3330f242a4437ba620

**Comment by jackpoz** [comment]
btw @Killyana , is one supposed to be able to cast Death Grip to this boss ? (please wait until the crash is fixed before changing anything about the boss)

**Comment by Killyana** [comment]
No the boss must be immune to grip bump or knock back.

**Comment by TheWinchesters** [comment]
> try with [jackpoz@7a8dc13](https://github.com/jackpoz/TrinityCore/commit/7a8dc13c7d69df0bdd27ea3330f242a4437ba620)

I can no longer reproduce it using that.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5d7f0eef6e2f89d5dbeb0a702f7a35c95626240e

**Comment by jackpoz** [comment]
thanks again @TheWinchesters  for the how to reproduce steps and for the tests.

@Killyana feel free to add the immunities 👍

**Comment by jackpoz** [comment]
@ccrs is this issue still happening to you ?

**Comment by xvwyh** [comment]
I think I found your problem:
`SplineChainResumeInfo(uint32 id, std::vector<SplineChainLink> const* chain, bool walk, uint8 splineIndex, uint8 wpIndex, uint32 msToNext)`
is called by
`return SplineChainResumeInfo(_id, &_chain, _walk, _nextIndex, 0, 1u);`
`return SplineChainResumeInfo(_id, &_chain, _walk, uint8(_nextIndex - 1), uint8(owner->movespline->_currentSplineIdx()), _msToNext);`

`_nextIndex` value is being passed to `splineIndex` parameter, and `_currentSplineIdx()` value is being passed to `wpIndex` parameter. I imagine they need to be swapped around.

**Comment by jackpoz** [comment]
see https://github.com/TrinityCore/TrinityCore/commit/5d7f0eef6e2f89d5dbeb0a702f7a35c95626240e#commitcomment-33725259 , closing this issue again as there's nothing else to fix
