### ISSUE TITLE
Bubble Fesher

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23084]
**Description:**
Bubble feshers are supposed to give underwater breathing where these are not doing so.

**Current behaviour:**
Does nothing just bubbles 

**Expected behaviour:**
Should refill the water breathing bar.

**Steps to reproduce the problem:**
go under water, find a bubble thing.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
b1545e76ef4e 2019-03-03 12:48:52 +0100

**Operating system:** Win64

**Comment by Killyana** [comment]
Already discussed here https://github.com/TrinityCore/TrinityCore/issues/16925
