### ISSUE TITLE
Core/Quest: repeatable quest mark

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23087]
**Description:** For a repeatable quest the mark must always be a "Blue ?"
The issue here is the quest mark is shown as (yellow !) if the quest level it's not "gray" (player level - quest level=<10) and it will turns  "Blue ?" once "gray" (player level - quest level>10) 

**Expected behavior:** The quest mark must always be  a "Blue ?"

**Steps to reproduce the problem:**

1. Connect a horde char level 80
2. .go c id 14727
3. complete all quests proposed until the repeatable quest with a "Blue ?" is displayed
4. .level -10 your char (level 70)
5. .die and .resp the npc
6. Notice the quest mark is displayed as (yellow !)
7. .level 1 (level 71)
8. .die and .resp the npc
9. Notice the quest mark is displayed as (Blue ?)

The quest=7837  Has Level: 60 it means it will turn gray at level 71

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 72052aa9a556

**Comment by jackpoz** [comment]
Please try with https://github.com/TrinityCore/TrinityCore/pull/23338 (other cases should be tested too)
