### ISSUE TITLE
Creature/Script: Script rewrite for Volkhan

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23082]
**Description:** Health pct is triggered when the npc regen after an evade
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp#L290

When an npc evade it regen its life slowly, this could trigger health pct events like for the boss https://www.wowhead.com/npc=28587/volkhan

**Steps to reproduce the problem:**

1. .go c id 28587  
2. put the boss below 10% of hp
3. .gm on
4. Notice he will spam an cast some spell related to the event health pct

**Branch(es):** 3.3.5
**TC rev. hash/commit:** rev. 9467fc9a0115

**Comment by Keader** [comment]
Bad script.

**Comment by Killyana** [comment]
There's also something related to BRITTLE_GOLEM but the npc never spawns, there's only MOLTEN_GOLEM

**Comment by kuskmen** [comment]
I've tried this in rev. [63aa5d1](https://github.com/TrinityCore/TrinityCore/commit/63aa5d1e3559) and it is not reproducing, however @Killyana  is right and brittle golems are not summoned, while there is logic for them? What should we do? Can someone write some requirements and I might take this issue.

**Comment by Killyana** [comment]
Still happen for me.

**Comment by jackpoz** [comment]
The chat spam has been fixed

**Comment by jackpoz** [comment]
Molten Golem spawns, when they get the killing blow they become Brittle Golems https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp#L430
![image](https://user-images.githubusercontent.com/1153754/58749044-2a7d1980-8481-11e9-8419-c101d01c7b68.png)
