### ISSUE TITLE
[Crash] Object::~Object 

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23083]
Description: I did not catch, ~Object !

Crash log
https://gist.github.com/HAANAAE/7424bbb5f1b3fecf3aefadab5b4c04ea

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/f17120cc784ee1f52a24424a78a64d71ad73b713
Operating system: debian

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
more than 1 month without answer, if this bug is still valid open a new ticket.
