### ISSUE TITLE
[3.3.5] Linking a quest

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23097]
**Description:**
Since a while you are unable to link quests in to the chat, it used to work but due to recent changes you can no longer link, i have checked the config files and i couldn't find anything weird there.

**Current behaviour:**
Linking a quest in a chat message returns the chat message not being sent.

**Expected behaviour:**
The quest should be linked within the player chat and players should be able to click it.
In any case it does not work at the moment.

**Steps to reproduce the problem:**

1. Go ingame, add urself a quest.
2. Try to link it in "Say" "Party" or "Guild" Chat
3. As you can see the message is never being sent.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e1aafdd+ 2019-03-03 23:19:03 -0300 (3.3.5 branch)

**Operating system:** WIN64

**Comment by Killyana** [comment]
Cannot reproduce on rev. 78d6115fdc14
See https://github.com/TrinityCore/TrinityCoreCustomChanges/issues/1 fo custom changes

**Comment by IllInuz** [comment]
Just updated to 78d6115
Still unable to link quests, custom changes what do u mean by that my config is fresh 💯
