### ISSUE TITLE
[3.3.5] Quest: Aces High!

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23094]
**Description:**
So on the quest when you are mounted on the quest dragon.
You are given 6 ability’s, 1 of the ability’s is not working.
The ability is flame shield. Your suppose to use the 1 ability to build up charges which effect the flame shield
But for the many times i attempted it, it was not applying itself to reduce the damage.

**Current behaviour:**
^--

**Expected behaviour:**
^--
CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

**Branch(es):**3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e1aafddc2e90+ 2019-03-03 23:19:03 -0300 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** Win64

**Comment by Killyana** [comment]
The issue is incomplete, we need quest ID, creature ID and spell ID

**Comment by IllInuz** [comment]
http://www.wowhead.com/quest=13413
https://www.wowhead.com/npc=32535/wyrmrest-skytalon

**Comment by illfated** [comment]
Also: [https://wow.gamepedia.com/Aces_High!](https://wow.gamepedia.com/Aces_High!)
(plus https://wow.gamepedia.com/Aces_High!_(daily))
Category: the Nexus in Coldarra.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/11566
