### ISSUE TITLE
[3.3.5] Scarlet monastary - High inquisitor Fairbanks

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23096]
**Description:**
When the player enters the area of Scarlet Monastery holding High Inquisitor Fairbanks, he will spawn laying down on the floor rather then standing up. This is a small bug as he still works as intended, but I’m providing the bug report just in case.
CHANGEME Description of the problem or issue here.

**Current behaviour:**
he lies down.

**Expected behaviour:**
he has to stand.

**Steps to reproduce the problem:**
Cosmetic issue.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e1aafdd+ 2019-03-03 23:19:03 -0300 (3.3.5 branch)

**Operating system:** CHANGEME OS
WIN64

**Comment by illfated** [comment]
Looks like Mists of Pandaria patch 5.4.7 content could have caused this issue:
https://wow.gamepedia.com/High_Inquisitor_Fairbanks#Death
> ![](https://gamepedia.cursecdn.com/wowpedia/2/26/Mists-Logo-Small.png)  This section concerns content related to Mists of Pandaria.
>
> High Inquisitor Fairbanks' undead body can be found in the secret room of Scarlet Monastery. He is lying on the ground lifeless. Perhaps, he may have found peace after the heroes collected his bounty from Dominic.

**Comment by offl** [comment]
Weird. Scarlet was fully sniffed, so maybe someone changed the stand state later or it is handled by script on retail. He's not laying in videos or screenshots.

I remember someone fixed bug when he was not able to change stand state to stand on aggro(probably it was on CMaNGOS). And I'm 100% sure he is laying for more than 10 years.

**Comment by illfated** [comment]
Remember that lots of data from build 18019 (Patch 5.4.7) was dumped into TDB 335 (you can even find some data from build 20886 (Patch 6.2.3a) in TDB 335).

**Comment by offl** [comment]
The stand state wasn't changed in TDB or in 10+ year old databases.
P.S. https://github.com/TrinityCore/TrinityCore/issues/4998

**Comment by illfated** [comment]
Thank you and sorry, I did not check anything, so I based my comment on presumptions instead of facts.

Should we go ahead and change the script so it only uses `UNIT_STAND_STATE_STAND` instead of `UNIT_STAND_STATE_DEAD` ?
https://github.com/TrinityCore/TrinityCore/blob/9e58ef6940c78d92f1553cf7ab75e87a6e2cf112/src/server/scripts/EasternKingdoms/ScarletMonastery/boss_high_inquisitor_fairbanks.cpp#L79-L90

**Comment by offl** [comment]
UNIT_STAND_STATE_DEAD is also handled in the DB for 10+ years, so this will change nothing
Probably sniffs must be checked(if any). Maybe he changes the stand state during instance progress or something like this. I believe the current stand state was sniffed long time ago.

**Comment by Killyana** [comment]
Just watched Asmongold live against High Inquisitor Fairbanks an the boss was laying at the ground.
But I'm not sure about CREATURE_FLAG_EXTRA_CIVILIAN (0x2)

**Comment by Killyana** [comment]
Yes works as intended https://www.twitch.tv/videos/430235329 (7.15min)
