### ISSUE TITLE
[Crash] WorldObject::GetGridActivationRange

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23092]
Description: the reason object in InstanceMap !

Crash/log
https://gist.github.com/HAANAAE/ee447faae607d01cd4cf8dd05af313fb

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/f17120cc784ee1f52a24424a78a64d71ad73b713
Operating system: debian

**Comment by Strazhnik** [comment]
Crash in Naxxramas (Thaddius, Kel'Thuzad).
@Killyana, can you confirm this?

**Comment by jackpoz** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/1c833f28e471e3787f1d328e44af5f065ad9ca8c
