### ISSUE TITLE
[3.3.5] Doomwalker Movement

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23093]
**Description:**
http://prntscr.com/mtnuvb
Stands there not moving, im pretty sure he has to walk around

**Current behaviour:**
Standing still doing nothing lazy dude.

**Expected behaviour:**
Walking a certain path.

**Steps to reproduce the problem:**
.go creature 84633

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e1aafddc2e90+ 2019-03-03 23:19:03 -0300 (3.3.5 branch)

**Operating system:** 
(Win64, Release, Static)

**Comment by Killyana** [comment]
He has a waypoint
``` sql
SELECT * FROM waypoint_data WHERE id=846330;

**Comment by IllInuz** [comment]
Typo made when this was implemented then maybe? let me check.

**Comment by Killyana** [comment]
``` sql
UPDATE `creature` SET `MovementType`=2 WHERE `id` IN (17711);

**Comment by IllInuz** [comment]
why not put this within the pull requests?

**Comment by Killyana** [comment]
It's just a sql, we don't use a PR for that.

**Comment by IllInuz** [comment]
ah but it will be put in the tdb update right?

**Comment by Killyana** [comment]
It's already on the DB

**Comment by illfated** [comment]
@IllInuz : Pull Requests are for code review - to have other users and team members discuss and review the content.
TrinityCore owners have selected to do this only for C++ code or C++ mixed with SQL content.
Like Killyana said, SQL solutions are only posted in issue pages and **committed** directly to the source
by one of the members with push access to the repository (see also commit https://github.com/TrinityCore/TrinityCore/commit/93072c8d1cf7c355e83498ee93550c77e54a66e1).
