### ISSUE TITLE
Core/Unit: prevent the full cleanup of movements on death

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23095]
**Description:** When you kill an accessory of a vehicle it remains installed and moves with the vehicle.

**Steps to reproduce the problem:**

1.  .go c id 29698 OR  27213
2. Kill the rider
3. Notice the rider remains in the vehicle once dead

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 78d6115fdc

**Comment by Killyana** [comment]
Caused by https://github.com/TrinityCore/TrinityCore/commit/982643cd96790ffc54e7a3e507469649f3b074d2#diff-4522eeffcbc961602e86620011a2d579R8701
removing :    `GetMotionMaster()->Clear();`   fix the issue

**Comment by ccrs** [comment]
umm that causes the problem, but the solution is not to clear all movements... this one is tricky

you see, getting out of a vehicle is actually a movement

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L12625

so we should not remove ALL movements, but just the ones we want to... and those are..?
- getting out of vehicles?? always NOT remove get-out-of-vehicle-movements??? who knows...
- any other movement that should NOT be removed??

how do we NOT remove those movements?
- create a MovementGeneratorMode designed to be ignored on the cleanup?
- perform a search&find in-place (in unit, where the clean call is) looking for them?

**Comment by PolarCookie** [comment]
Other movements to NOT remove is knockbacks; creatures dying in the air freeze where they die.
Try doing "That's Abominable".

Commenting out to "fix" it
https://github.com/TrinityCore/TrinityCore/blob/3bc1900018fd38d23e656237e751cbe1ebb8552d/src/server/game/Entities/Unit/Unit.cpp#L8711-L8712

**Comment by Sorikoff** [comment]
I think getting out of vehicles should always allow, well, getting out of them. Is there even any example of dead passenger staying in the vehicle? I can't think of such.

**Comment by jackpoz** [comment]
how about restoring the code that was working fine before "Internal structure and handling changes, nothing behavioural (or thats the intention at least)." commit and have another commit that will try to change the old behavior with in a PR that will handle whatever all cases are ?

**Comment by Sorikoff** [comment]
I'm no expert here but if that would solve this issue then why not?

**Comment by ccrs** [comment]
yo, thats going too far there @jackpoz 
we're talking about a rework with very, very few edge cases

**Comment by jackpoz** [comment]
Confirmed using 28921f191de2269dd90b50ac99dd0d29ba90d0c4

@ccrs years are pessing and the issues added in the movement rewrite are still there. could you please fix this ?

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/25404 to fix the issue

**Comment by Faq** [comment]
SO here in total mentioned 2 cases:
1. with vehicles (original report with reproduce steps);
2. when used knockbacks https://github.com/TrinityCore/TrinityCore/issues/23095#issuecomment-470601211

**Comment by jackpoz** [comment]
well my PR takes care of the case reported in this issue, I didn't test the knockback one. Maybe it's better to move that to a different issue

**Comment by jackpoz** [comment]
> Other movements to NOT remove is knockbacks; creatures dying in the air freeze where they die.
> Try doing "That's Abominable".

This bit still needs to be fixed

**Comment by Faq** [comment]
Rechecked 2nd part on rev ff26027453179448bb972d88a51e565d71e95f3f

![image](https://user-images.githubusercontent.com/322016/92312888-e5259100-efcd-11ea-9153-193ca76469b5.png)

**Comment by jackpoz** [comment]
> @ccrs years are passing and the issues added in the movement rewrite are still there. could you please fix this ?

2nd try

**Comment by jackpoz** [comment]
Notes to reproduce the issue:
- target a mob
- .cast 59576 to trigger the knockback
- .damage 10000000 to kill the mob in the air

**Comment by jackpoz** [comment]
I created a PR at https://github.com/TrinityCore/TrinityCore/pull/26549 to fix this issue
