### ISSUE TITLE
3.3.5 Cmake error C1083 Cannot open include file: 'pthread.h'

### ISSUE THREAD

**Issue by zezreli** [TrinityCore/TrinityCore#23099]
**Description:**

So me and a friend is trying to setup a 3.3.5 server as a learning project to learn new things,
we followed the core installation on the trinity website step by step, and still got errors, so we went through everything again looking for the problem and found this error, 

  C:\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Build\CMakeFiles\CMakeTmp\cmTC_c2120.vcxproj]

**Current behaviour:**

https://gist.github.com/zezreli/ff0b3edb69de9fe4f5d8c882bf325524
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Cmake should have created a visual studio file so that we could have buildt the server to get started

**Steps to reproduce the problem:**

1. Step 1 follow the wiki 
2. Step 2
3. Step 3

**Branch(es):**
3.3.5
**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** windows 10OS

**Comment by Aokromes** [comment]
https://community.trinitycore.org/topic/120-compile-or-cmake-problems/
