### ISSUE TITLE
[3.3.5] Linking quest - Fresh build.

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23100]
**Description:**
When on a fresh build of trinitycore, i am still unable to link messages in game.
I created an issue yesterday which got closed cause it worked for that one person.

However i am still unable to even on a fresh compile.

Player Illinux (GUID: 2) sent a message with an invalid link:
 |cff40c040|Hquest:12214:72|h[[72] Fresh Remounts]|h|r

**Current behaviour:**
It is not working, and i have no custom changes made whatsoever it is a fresh recompile.

**Expected behaviour:**
Should link the quest as it is supposed to.

**Steps to reproduce the problem:**

1. add urself a quest
2. Shift click to link it and send the message
3. Does not work.

**Branch(es):**3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c826d86853ff 2019-03-06 13:30:53 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** WIN64

**Comment by Aokromes** [comment]
disable send level option OR use the patch you was told to use.

**Comment by IllInuz** [comment]
@Killyana 
I felt like tagging u here since u where certain it was fixed, however i just did a fresh compile on my other PC and i noticed it was still not working running a clean untouched core, with default configs.

**Comment by IllInuz** [comment]
@Aokromes Fresh compile untouched config, havent touched anything and the send level option is disabled by default, the patch link that was provided is not working.

**Comment by Aokromes** [comment]
you look to have UI.ShowQuestLevelsInDialogs = 1

**Comment by IllInuz** [comment]
Put it to 0, had to abondon all quests, as it was still using the [level] [questname] format after changing it, abondoning and retaking the quests gives it the correct format.
