### ISSUE TITLE
[3.3.5] Naxxramas

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23102]
**Description:**
Naxxramas

Anub’Rekhan

He regularly spawns a Crypt Guard that needs offtanking, she applies a non-removable poison (Acid Split) on its target. He also shoots Impale in a large cone towards a rnd player. anyone in that cone will get thrown in the air (for this reason it is important to be distributed in the room). Dead Crypt Guards or playerz spawn Corpse Scarabs from their bodies which have to be destroyed with AoE.
BUG! Corpse Scarabs are not spawning. Acid Spit does not apply.
Now lets get to the main tactic. Every 90s he casts Locust Swarm which does stackable damage and silence 30m around him (this silence also includes auto-attacks etc). He also becomes 25% slower and another add spawns. The tanks is supposed to kite him along one side of the room.
BUG! For some reason he got bugged under the floor with us, I dont know how - and never came up again.

This Boss is not doable without GM support after he bugs under the floor.

Grand Widow Faerlina seems to work just fine.
Maexxna seems to work just fine.

Noth the Plaguebringer

He casts Curse of the Plaguebringer on rnd playerz, if not decursed within 10s they get Wrath of the Plaguebringer (each one) an AoE explosion. He spawns two Plagued Warriors periodicly and will enrage after 3 teleportations.
Every 110s he teleports onto a plattform above the field and spawns waves of skeletons (Plagues Champion and Plagued Guardian). There are two waves in total, the phase lasts for 70s then Noth comes back and dacapo.

BUG! When Noth teleports back to the battlefield he gets stuck (somewhere). He still appeares on the plattform but is untargetable and does not appear on the battlefield.

This Boss is currently not doable without GM support!

Heigan the Unclean

He casts an aura around himself that increases castings by 300% (Spell Disruption) and applies a DoT on rnd player (Decrepit Fever). He casts Eruption that covers 3/4 of the room in nature flames.
He changes every 45s between two phases. Phase1 he is on the plattform, Eruption gets cast very quickly + Plague Cloud (a strong AoE on the raised plattform) Phase2 starts with him blinking into the group. Now Eruption gets cast slower + DoT
+ Aura.
Standard is in Ph1 for everyone to run (Heigan-Dance) and in Ph2 for the tank to continue running (+melees) while heal and casters nuke him from the safety of the plattform.
BUG! Eruption doesnt do any damage, negating the entire bossmechanics!

Loatheb seems to work just fine.
Instructor Razuvious seems to work just fine.
Gothik the Harvester seems to work just fine.
The Four Horsemen seem to work just fine.
Patchwerk seems to work just fine.
Grobbulus seems to work just fine.

Current behaviour:
It is alot of information in one report, However its pretty detailed, and i figured sharing this with u.

Expected behaviour:

Steps to reproduce the problem:

Branch(es): 3.3.5

TC rev. hash/commit: TrinityCore rev. e482d9f 2018-02-18 12:20:25 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

Operating system: Win64

**Comment by Aokromes** [comment]
don't post multiple bugged npcs on a single ticket.

**Comment by Faq** [comment]
@IllInuz please split issues in separate tickets, but before that search if there is none active ticket with same issue.
