### ISSUE TITLE
DB/Quest: It Goes to 11...

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#23104]
Since #6844 is closed, I decided to continue conversation in new issue.

**Description:**
Quest is not working. I fixed Vrykul Harpoon Gun (27992) problem with the following SQL:
```sql
UPDATE `creature_template` SET `unit_flags`=`unit_flags`|4, `spell1`=43986, `spell2`=43997, `AIName`='SmartAI' WHERE `entry`=27992;
```

But the problem is with the quest triggers (24538, 24646, 24647). I'd like them to cast quest credit spell and start event with Defenders. Nothing happens whatever I try. Could someone experienced help with that?

**Expected behaviour:** [https://www.youtube.com/watch?v=JBiE2hLGqOE](https://www.youtube.com/watch?v=JBiE2hLGqOE)

**Steps to reproduce the problem:** `.q a 11421`

**Branch(es):** both

**TC rev. hash/commit:** ec3cb05d7fbc5cef60d000af910dc39dd3af92bf

**Operating system:**

**Comment by ccrs** [comment]
is the grid containing the triggers even active? seems too far away for the default grid load distance

**Comment by Sorikoff** [comment]
Don't know. What to do then? Make triggers active?

**Comment by Killyana** [comment]
Even if you set this npcs trigger active a player must go there to activate this grids at every server startup

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/6844
