### ISSUE TITLE
The problem with the SQL query in the table "character_pet_declinedname".

### ISSUE THREAD

**Issue by Infernales** [TrinityCore/TrinityCore#23106]
**Description:**

The problem with the SQL query in the table "character_pet_declinedname".

**Current behaviour:**
SQL(p): INSERT INTO character_pet_declinedname (id, owner, genitive, dative, accusative, instrumental, prepositional) VALUES (1, 'Теста', 'Тесту', 'Теста', 'Тестом', 'Тесте', 0)
 [ERROR]: [1366] Incorrect integer value: 'Теста' for column `characters1`.`character_pet_declinedname`.`owner` at row 1

**Expected behaviour:**

The SQL query should look like this: "INSERT INTO character_pet_declinedname (id, owner, genitive, dative, accusative, instrumental, prepositional) VALUES (1, 0,'Теста', 'Тесту', 'Теста', 'Тестом', 'Тесте') ". But then again, why is the value of "owner" equal to 0?

**Steps to reproduce the problem:**

1. Enable the DeclinedNames = 1 option in worldserver.conf and connect to the server from a russian client.
2. Create a hunter and tame a pet.
3. Rename the pet.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8140775

**Operating system:** 
Arch Linux

**Comment by illfated** [comment]
I don't know why that happens, but this is some of the relevant code:
https://github.com/TrinityCore/TrinityCore/blob/8140775bdaa84a25e7f68c42fe2b93d6aab1ca7c/src/server/database/Database/Implementation/CharacterDatabase.cpp#L573-L579

**Comment by Infernales** [comment]
Yes, everything is correct in this file, but the request is formed like:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/PetHandler.cpp
This, again, as I understand it, and I could be wrong.

**Comment by jackpoz** [comment]
Does this happen only with Russian client ?

**Comment by Infernales** [comment]
@jackpoz Well, in fact, this should work only with a russian client.

**Comment by Shauren** [comment]
Yeah, declined names are a feature of russian client

**Comment by Shauren** [comment]
Hah, it was only broken for 7 years

**Comment by illfated** [comment]
Thanks for solving the issue, and quite quick too. 👍
