### ISSUE TITLE
[3.3.5] OS Bugs

### ISSUE THREAD

**Issue by IllInuz** [TrinityCore/TrinityCore#23101]
**Description:**
Obsidian Sanctum

Vesperon

He does Shadow Breath, which inflicts damage in a cone in front of him as well as Shadow Fissure. Last one is a void zone spawning under rnd player that explodes into damage after 6sec if anyone stands in it.
BUG! The Fissure doesnt do any damage whatsoever.
He also regularly spawns a portal that brings playerz into another phase where they have to fight an elite mob (needs tank), Disciple of Vesperon. As long as one of them is alive playerz get a stackable debuff that increases inc shadow damage by 75% each time. Additionally you recieve 3000 shadow damage for each attack on the Boss. Peeps in the Twilight Phase should constantly get damaged.
BUG! The portal closes after 1 - 2 playerz go through, no mob spawns (or is invisible). When this phase starts every player gets instantly 8 stacks of the debuff (8 disciples spawn all at once?). The stacks DECREASE over time on their own. Something about that debuff doesnt work properly, I attacked the boss with 8 stacks and recieved 10k damage (3000*1,75^8=263 892).

Solution: Nuke the Boss within 1min before the phase starts.

Tenebron

She does Shadow Breath, which inflicts damage in a cone in front of him as well as Shadow Fissure. Last one is a void zone spawning under rnd player that explodes into damage after 6sec if anyone stands in it.
BUG! The Fissure doesnt do any damage whatsoever.
She also regularly spawns a portal that brings playerz into another phase where they have to destroy Twilight Eggs before they hatch into Twilight Welps. Common tactic is to ignore this part and to offtank them outside. Tenebron has an aura that increases all inc shadow damage by 100%, the Welps apply a stackable debuff that decreases armor.
BUG! Portal doesnt work and closes right after someone clicks on it. Eggs spawn around playerz in the middle of the battlefield and hatch instantly. Something about the Welps damage doesnt seem right (Randy died in seconds with druidheal but Fallen tanked 18 of them for a few min without having or needing heal).

Shadron

He does Shadow Breath, which inflicts damage in a cone in front of him as well as Shadow Fissure. Last one is a void zone spawning under rnd player that explodes into damage after 6sec if anyone stands in it.
BUG! The Fissure doesnt do any damage whatsoever.
He also regularly spawns a portal that brings playerz into another phase where they have to fight an elite mob (needs tank), Disciple of Shadron. As long as the add is alive the boss gets a stackable buff that increases his shadow damage by 50% each time.
BUG! The portal closes after 1 - 2 playerz go through, no mob spawns (or is invisible).

PS: Contrary to some comments the fire damage of the lava works just fine.
PPS: Sartharion 10 no adds works fine.
CHANGEME Description of the problem or issue here.

**Current behaviour:**
It is alot of information in one report, However its pretty detailed, and i figured sharing this with u.

**Expected behaviour:**

**Steps to reproduce the problem:**

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  TrinityCore rev. e482d9f303c7 2018-02-18 12:20:25 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Win64

**Comment by Killyana** [comment]
Duplicates https://github.com/TrinityCore/TrinityCore/issues/15208  https://github.com/TrinityCore/TrinityCore/issues/15209  https://github.com/TrinityCore/TrinityCore/issues/15207  https://github.com/TrinityCore/TrinityCore/issues/15210 https://github.com/TrinityCore/TrinityCore/issues/19363

**Comment by illfated** [comment]
@IllInuz : Please check out the Obsidian Sanctum issues linked by Killyana and re-post the information where it belongs
... and if there still is any information in your post above after that, edit your issue title to match the specific problem.
