### ISSUE TITLE
Core/GameObjects: Summoned gameobject are not removed from the map

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23115]
**Description:** When you summon a gob temporary with  SMART_ACTION_SUMMON_GO with Despawn= time in secs, once the gob despawns it will remains visible with GM ON, and if you use a condition to check if the gob is spawned or not it will return true.

**Current behavior:** 
Summoned gobs are not removed from the map but just "deactivated ?"

**Expected behavior:** 
Summoned gobs must be removed from the map once despawned

``` sql
-- this conditions will hide the gossip option from the gob if the a gob is already summoned.
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 15 AND `SourceGroup` = 4362 AND `ConditionTypeOrReference`=30;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ErrorTextId`, `ScriptName`, `Comment`, `NegativeCondition`) VALUES
(15, 4362, 0, 0, 30, 177491, 10, 0, 0, '', NULL,1),
(15, 4362, 0, 2, 30, 177491, 10, 0, 0, '', NULL,1),
(15, 4362, 1, 1, 30, 177491, 10, 0, 0, '', NULL,1),
(15, 4362, 1, 3, 30, 177491, 10, 0, 0, '', NULL,1);
```

**Steps to reproduce the problem:**

1. .go game 45507
2. .quest add 6390
3. open the gossip of the create to summon the barrel
4. wait 60secs until the barrel despawns
5..gm on    and notice the barrel is there an if you open the gossip menu again options will not be displayed as the barrel is there.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 66aa7577321c

**Comment by jackpoz** [comment]
is this an old issue or did it start after some recent changes ?

**Comment by Killyana** [comment]
I don't know, it could be a missing change relate to dynamic spawns.

**Comment by Killyana** [comment]
After further testing:
The gob despawns correctly if the summoned is a npc and the despawn type= 0 - For despawn when the summoner despawn or time runs out (action param3

The gob will not despawn correctly if the summoner is a game object

The gob will not despawn correctly if the summoner is a npc and despawn type= 1-  For despawn when time runs out

Possible commit related to this: https://github.com/TrinityCore/TrinityCore/commit/ca4f1e334a98cbd810168b24714c46201079fc5a

**Comment by Killyana** [comment]
I replacedgo->SetSpawnedByDefault(false);  https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L2001  by ToUnit()->AddGameObject(go); and the gob despawns if summoned by a npc whatever the summon type, but for gobs it crash

**Comment by Killyana** [comment]
Issue fixed by replacing DestroyForNearbyPlayers(); with Delete();

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L796-L802

I don't see in which case we ne to respawn a summoned gameobject.
