### ISSUE TITLE
Core/Spell: AttributesEx4: 0x20001000 persist after evade

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23113]
**Description:** This attribute AttributesEx4: 0x20001000 (SPELL_ATTR4_UNK12, SPELL_ATTR4_UNK29)  is used only by 2 spells : 32578 and 36310, both are auras that must persist after an evade:
https://woehead.way-of-elendil.fr/?spell=36310
https://woehead.way-of-elendil.fr/?spell=32578

**Branch(es):** both

**TC rev. hash/commit:** rev. 66aa7577321c

**Comment by jackpoz** [comment]
these are 2 attributes, which one is about the evade ? or do we need to check both ?

**Comment by Killyana** [comment]
Probably SPELL_ATTR4_UNK12  but how can I get the list of spells using : SPELL_ATTR4_UNK12 on spell work ?

**Comment by Shauren** [comment]
In spell field dropdowns select AttributesEx4, operator "x & y != 0" and value "4096"

**Comment by Killyana** [comment]
Many spells use this attribute actually, some of them are auras used only by players like https://woehead.way-of-elendil.fr/?spell=71516
Other spells used by npcs "must" remains on after evade like: https://woehead.way-of-elendil.fr/?spell=7393 and https://woehead.way-of-elendil.fr/?spell=63316

**Comment by Killyana** [comment]
As this attributes doesn't make sense maybe we can implement a custom attribute  SPELL_ATTR0_CU_PERSIST_AFTER_EVADE https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130057/spell+custom+attr

**Comment by Killyana** [comment]
This attribute looks not related to auras and evade
