### ISSUE TITLE
[4.3.4] Arena Battlemaster & Organizer

### ISSUE THREAD

**Issue by Kitzunu** [TrinityCore/TrinityCore#23121]
**Description:**

Used to queue for arena and set up arena team
I searched around on the Github but found now working fix

**Current behaviour:**

Arena Battlemaster got no Arena gossip 
Arena Organizer got no Arena Team create window (Nothing happens when you right click the npc either)

**Expected behaviour:**

You should be able to queue arenas with the Arena Battlemaster
You should be able to create an Arena team with the Arena Organizer

**Steps to reproduce the problem:**

1. Try to interact with the Arena Organizer & Battlemaster

**Branch(es):**

4.3.4

**TC rev. hash/commit:** 
71c673c

**Operating system:** WIN

**Comment by Shauren** [comment]
4.3.4 is not a supported version

**Comment by funjoker** [comment]
https://github.com/Ovahlord/TrinityCore

open Issue there
