### ISSUE TITLE
DB/SAI: Vile Familiar

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#23129]
**Current behaviour:**

Vile Familiars stand still for long periods between casts doing nothing if at range. They cast too often. They flee when they shouldn't.

https://www.wowhead.com/npc=3101/vile-familiar

Source: https://youtu.be/SwLjJH8LXfc?t=840

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a926a3088d39

**Suggested Fix:**

```sql
-- Vile Familiar SAI
SET @ENTRY := 3101;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,4000,6000,6000,9000,11,11921,0,0,0,0,0,2,0,0,0,0,0,0,0,"Vile Familiar - In Combat - Cast 'Fireball'");
```

**Comment by illfated** [comment]
For consistency, please add `event_type` in the comment text:
`"Vile Familiar - In Combat - Cast 'Fireball'"`

BTW, welcome back. 👍
