### ISSUE TITLE
[3.3.5] Crash: StopCastingCharm

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23133]
**Description:**
There are closed issues about this crash but it looks like it is happening again.
I updated the core yesterday (it was a two or three months old core) and I did not have this crash before.
I went from commit 4337eefc8f77ec2f64f2bda747292ea4e50199ea to commit 858782f68a33ca8f2aacee3e1d9b1435b2edfb30
There are comments about this crash in "Spellaura redux" https://github.com/TrinityCore/TrinityCore/pull/22794.
I do not know if it is related or it is something else between the two commits mentioned above.

Crashlog: https://gist.github.com/TheWinchesters/1062cb582a77dec9b9bbf3bcb2d77c7a

Note 1: This happened in a server with basic custom things not related to this crash (Transmog, Passive anticheat, ...)
Note 2: Tested in a clean core too

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 858782f68a33ca8f2aacee3e1d9b1435b2edfb30
**Operating system:** Linux

**Comment by TheWinchesters** [comment]
How to reproduce:
1. .go c id 30500
2. .quest add 13045
3. Do a spam of clicks on the npc 30500 (A drake mount)

**Comment by Killyana** [comment]
npc_spell_click_spell=https://woehead.way-of-elendil.fr/?spell=56922
it forcecast https://woehead.way-of-elendil.fr/?spell=56679
That trigger https://woehead.way-of-elendil.fr/?spell=56678

I don't think the spell_script 'spell_gen_vehicle_control_link'  handle this case
@PolarCookie

**Comment by Killyana** [comment]
I tested in 2 years old core and spamming the npc spawns also a vehicle per click, so in this case we have 2 issues, the crash and the spellclick condition

**Comment by jackpoz** [comment]
There are 2 TC_LOG_FATAL and 1 ABORT in same control flow, that's quite overkill.

**Comment by PolarCookie** [comment]
https://github.com/TrinityCore/TrinityCore/blob/ac8238c6342675041800eb49a3b5a0980da1e29d/src/server/game/Entities/Vehicle/Vehicle.cpp#L763
Put a breakpoint here; the times when the crash happens this execute is called twice, and it fails on the second. Normally it's only called once and everything's fine.
No idea why it randomly gets called twice.

**Comment by Killyana** [comment]
It's called twice if you spam the spell_click,.
When the crash happen you get this in the server.log:
Player::StopCastingCharm: Player 'Hilliium' (GUID Full: 0x0000000000000002 Type: Player Low: 2) is not able to uncharm unit (GUID Full: 0xf1500076140008a0 Type: Vehicle Entry: 30228  Low: 2208)
Player::StopCastingCharm: Charmed unit has charmer GUID Full: 0x0000000000000002 Type: Player Low: 2

**Comment by PolarCookie** [comment]
https://github.com/TrinityCore/TrinityCore/blob/ac8238c6342675041800eb49a3b5a0980da1e29d/src/server/game/Entities/Vehicle/Vehicle.cpp#L407
Is randomly called twice, don't have to rapidly click for it to happen.

One solution is to handle the case where m_vehicle is already set here
https://github.com/TrinityCore/TrinityCore/blob/ac8238c6342675041800eb49a3b5a0980da1e29d/src/server/game/Entities/Vehicle/Vehicle.cpp#L788

**Comment by PolarCookie** [comment]
Ok, two spell click packets gets sent from the client even when I swear I'm only clicking once each test.
https://github.com/TrinityCore/TrinityCore/blob/ac8238c6342675041800eb49a3b5a0980da1e29d/src/server/game/Entities/Unit/Unit.cpp#L12513-L12527
m_vehicle has not been set both times since it gets updated later with the deferred VehicleJoinEvent.

https://github.com/TrinityCore/TrinityCore/blob/ac8238c6342675041800eb49a3b5a0980da1e29d/src/server/game/Entities/Vehicle/Vehicle.cpp#L426
I'm considering testing here that only 1 VehicleJoinEvent can exist at a time.

**Comment by PolarCookie** [comment]
The issue arose after vehicle control auras no longer were considered single target, and would be automatically removed by that system.

**Comment by PolarCookie** [comment]
@TheWinchesters thank you for finding this issue, could you link those mentioned closed issues just for reference?

**Comment by Shauren** [comment]
FFS really? Why did someone remove vehicle auras being single target bringing back the crash I fixed years ago?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/73e3fdc8b4545cca52b66032a5f2465183d14c71
