### ISSUE TITLE
Valduran the Stormborn

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#23137]
**Description:**
https://www.wowhead.com/quest=12984/valduran-the-stormborn
https://www.wowhead.com/npc=29368/valduran-the-stormborn
https://www.wowhead.com/item=42419/bouldercrags-war-horn
https://www.wowhead.com/npc=29801/bouldercrag-the-rockshaper
https://www.wowhead.com/npc=30152/bruor-ironbane

**Current behaviour:**
After using the quest item Bouldergrag's War Horn, Valduran the Stormborn goes through a small scripted event, but does not come down to ground level to fight. He will agro you and will attack if you're standing near enough but won't move.

During the fight, Bouldercrag the Rockshaper and Bruor Ironbane also stand still and don't engage in combat.

After combat is over, Bouldercrag and Bruor only remain spawned for around 10-15 seconds.

![WoWScrnShot_032719_023718](https://user-images.githubusercontent.com/16745918/55061545-a7cb7e80-5039-11e9-9055-5960a3ac6f74.jpg)

**Expected behaviour:**
Valduran the Stormborn should come down to ground level, and all of the npcs involved should engage in combat.

After combat is over, Bouldercrag and Bruor should return to their original positions, and remain available for a minute or two.

https://www.youtube.com/watch?v=3VcxYiB-T-A

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 129ba1537891 2019-03-24 17:44:04 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1a  20 Nov 2018 (library: OpenSSL 1.1.0h  27 Mar 2018)
Using Boost version: 1.66.0
Using MySQL version: 5.5.38
Using CMake version: 3.13.4
Compiled on: Windows 10.0.17763
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19031

**Operating system:** Windows 10 Pro

**Comment by Killyana** [comment]
https://youtu.be/jfFp621SDHc?t=111 Bouldercrag and Bruor remain spawned for around 10-15 seconds. It doesn't make sense to have them spawn for 1 or 2 min.

**Comment by Killyana** [comment]
The hover issue will be fixed with the main issue.

**Comment by jerbookins** [comment]
> https://youtu.be/jfFp621SDHc?t=111 Bouldercrag and Bruor remain spawned for around 10-15 seconds. It doesn't make sense to have them spawn for 1 or 2 min.

The problem is they're not around long enough to even turn in, read, and accept quests from them.

**Comment by Killyana** [comment]
They are not supposed to have the npc flag quest giver, I remember I fixed this issue.

**Comment by Killyana** [comment]
Yes multiple fix here: https://github.com/TrinityCore/TrinityCore/commit/11f6aa651884e5d024319fc4bb0ee38ddd4e4aac for this quest.
