### ISSUE TITLE
Icecrown Citadel Death BUG

### ISSUE THREAD

**Issue by asd567800** [TrinityCore/TrinityCore#23138]
TrinityCore rev. 60d625ea838d+ 2019-03-26 21:11:48 +0100 (HEAD branch) (Win64, RelWithDebInfo, Dynamic) (worldserver-daemon)

OS :  win7 x64  , mem 16Gb 

At Icecrown Citadel  3'nd BOSS.

1).
**Description:**
Character  : Confederacy  Warrior. GM not on.

Gunship Battle failed on the ship  when  ship's HP is 0.
I  click the death button to go to cemetery.(I did not see my dead body，when the button can be clicked)
I  revive at the cemetery. 
And then go to the quest door.
The battle status bar is still going on( 1'nd foor battle damage messages is still refresh) .
Later  I through the protal two times  and die at the third floor twice. 
The 3'nd  time I will be OK.

Revive at the cemetery:
I think the ship is in the sky, when ship die (HP to 0), script let me die too.
But my death gps is in the sky. There would be  not found in the quest or not allowed.
So I revice at the cemetery. But the quest battle instance is not  reset or deleted correctly because of this.

For general , If  we died in the quest we will have to return to the quest and can be revived. 

2). 
For gunship battle failed. ALL rescources were deleted, only my  death body is in the sky. I clicked to be a ghost. 
I return to quest door and revive, goto the gunship again ,talk to he npc but the ship cant setout.
So I died again. When retrurn to the quest door ,I GO BACK HOME ?

MSG:
Loading GUID Full: 0x0000000000000002 Type: Player Low: 2 from account 1.
Loading GUID Full: 0x0000000000000003 Type: Player Low: 3 from account 1.
Loading GUID Full: 0x0000000000000006 Type: Player Low: 6 from account 1.
Loading GUID Full: 0x0000000000000007 Type: Player Low: 7 from account 1.
Account: 1 (IP: 127.0.0.1) Login Character:[Poco] (GUID: 6) Level: 80
Could not load MMAP name:Icecrown Citadel, id:631, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:Icecrown Citadel, id:631, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:Icecrown Citadel, id:631, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:Icecrown Citadel, id:631, x:31, y:32 (mmap rep.: x:31, y:32)
GameObject (template id: 201815) has invalid faction (faction template id) #0
GameObject (template id: 201815) has invalid faction (faction template id) #0
GameObject (template id: 201815) has invalid faction (faction template id) #0
GameObject (template id: 201815) has invalid faction (faction template id) #0
GameObject (template id: 201815) has invalid faction (faction template id) #0
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
Map 631 (Icecrown Citadel) could not be created for player 6 (Poco), porting player to homebind
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)

BEBUG:
EnterState is :　　CANNOT_ENTER_ZONE_IN_COMBAT　// A boss encounter is currently in progress on the target map

**Comment by Killyana** [comment]
This will not be easy to reproduce or fix.

**Comment by illfated** [comment]
@asd567800 : it would have been easier to troubleshoot if you had kept the TC issue template and filled in "Steps to reproduce".

I did something similar a while ago, but that was mostly because I forgot to re-buff and increase my player HP (`.modify hp 50000000`) before entering Icecrown Citadel again after revive.

We don't know if this is what happened to you, so it would definitely help if you could provide more information about how it happened and what you did up until the point where you died. There could have been a big debuff on your character that you didn't take into account when you reentered the raid instance, but as I said, we just don't know without enough information.

We also don't know anything about your core revision hash, so we don't have enough data to make a reasonable comparison for those who would like to try to reproduce your issue.

**Comment by asd567800** [comment]
> @asd567800 : it would have been easier to troubleshoot if you had kept the TC issue template and filled in "Steps to reproduce".
> 
> I did something similar a while ago, but that was mostly because I forgot to re-buff and increase my player HP (`.modify hp 50000000`) before entering Icecrown Citadel again after revive.
> 
> We don't know if this is what happened to you, so it would definitely help if you could provide more information about how it happened and what you did up until the point where you died. There could have been a big debuff on your character that you didn't take into account when you reentered the raid instance, but as I said, we just don't know without enough information.
> 
> We also don't know anything about your core revision hash, so we don't have enough data to make a reasonable comparison for those who would like to try to reproduce your issue.

Sorry,

**Comment by asd567800** [comment]
Sorry , I  provide some more information .

**Comment by illfated** [comment]
Very well, at least there is more information to look at now, to see if anything has become more apparent.

Just a tip regarding the console messages. Only the following are of interest:
```
Loading GUID Full: 0x0000000000000002 Type: Player Low: 2 from account 1.
Loading GUID Full: 0x0000000000000003 Type: Player Low: 3 from account 1.
Loading GUID Full: 0x0000000000000006 Type: Player Low: 6 from account 1.
Loading GUID Full: 0x0000000000000007 Type: Player Low: 7 from account 1.
Account: 1 (IP: 127.0.0.1) Login Character:[Poco] (GUID: 6) Level: 80

Map 631 (Icecrown Citadel) could not be created for player 6 (Poco), porting player to homebind
```
The other messages are known details and would be shown even if everything else is working.

**Comment by asd567800** [comment]
I dont know how to debug more  information . But I find some thing helpful.

If the died . I click the repop before the ship .etc AI   resources  was disappeared(deleted).  I will revive at 

the  graveyard and through the portal in the 1nd I will the twice dead damage.

Its the resource deleter order problem between AI and player .

**Comment by illfated** [comment]
Since you are playing the instance alone, it would be interesting to know how much HP you added to your character in order to survive in a raid zone/instance, and if there are any other spells / buffs in use. Did you try to grab a screenshot of the moment when you died, to see if there were any visible debuff on you?
