### ISSUE TITLE
cannot log in to the srrver

### ISSUE THREAD

**Issue by timpan77** [TrinityCore/TrinityCore#23132]
hey would anyone be able to help me i have tried to fix this myself but don't get it to work i use MMOPro Official WoW Legion Repack (build 7.3.5.26972) with ProjectCMS but when i log on to the server then it will log on to the log in to the game server knows someone why this is so
he client build and realmlist build are the same 26972
![2222](https://user-images.githubusercontent.com/11890762/54871668-5e203100-4db8-11e9-968f-e37377ddce33.png)
![2222](https://user-images.githubusercontent.com/11890762/54871671-64161200-4db8-11e9-8a07-58895bbe0247.png)

**Comment by Shauren** [comment]
Repacks (and Legion) arent supported
