### ISSUE TITLE
DB/Loot: Mottled Boar corrections

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#23134]
**Description:**

Update to https://github.com/TrinityCore/TrinityCore/issues/20711

Mottled Boars should drop junk gear at a higher rate and grey items should be grouped, with one grey item guaranteed (this seems extremely common). Current drop counts are also incorrect. Based on viewing old retail vids.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a926a30

**Suggested Fix**

```sql
-- Mottled Boar
DELETE FROM `creature_loot_template` WHERE `Entry`=3098;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(3098, 4865, 0, 40, 0, 1, 1, 1, 1, "Ruined Pelt"), -- Ruined Pelt
(3098, 7098, 0, 40, 0, 1, 1, 1, 2, "Splintered Tusk"), -- Splintered Tusk
(3098, 117, 0, 20, 0, 1, 1, 1, 1, "Tough Jerky"), -- Tough Jerky
(3098, 24073, 24073, 15, 0, 1, 0, 1, 1, "Junk"), -- Junk
(3098, 11111, 11111, 0.1, 0, 1, 0, 1, 1, "Bags"); -- Bags
```

**Comment by illfated** [comment]
Thanks. I knew there was something missing, but I could not quite point it out.

**Comment by Killyana** [comment]
I changed the original sql in the other issue, it's exactly the same posted here with the drop rate little bit lower for some items.
https://github.com/TrinityCore/TrinityCore/commit/5b8a2a8a0772808c27ea923e58da6df929536186#diff-caf0117341b9daf58b0b457a28714c6cR2

**Comment by Teppic1** [comment]
It's an update to the original change I made, rates and max counts are different. But I can't see any commit?

**Comment by Killyana** [comment]
I didn't noticed the number of  items.
