### ISSUE TITLE
Client disconect caused by Player::SendAurasForTarget(Unit* target)

### ISSUE THREAD

**Issue by sirikfoll** [TrinityCore/TrinityCore#23141]
**Description:**
Player::SendAurasForTarget(Unit* target) seems to be wrong, it sends, for example, a SMSG_MOVE_WATER_WALK for player A for each player that's around him, with enough players, player A gets kicked for flooding _ACKs

**Steps to reproduce the problem:**

1. .cast self 61922
2. .tele to a map with several players
3. Note you get a SMSG_MOVE_WATER_WALK for each player that is around you, with more than 100 you can get kicked/banned due to flood of _ACK

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 9511a54f1fa7

**Comment by Jildor** [comment]
Oh, so this can be the reason of the old bug about get Path of Frost and teleport to dalaran, you get kicked randomly

**Comment by illfated** [comment]
Thanks. Those are interesting observations.

**Comment by Shauren** [comment]
Unrelated to Player::SendAurasForTarget.
