### ISSUE TITLE
[CRASH] Unit::RemoveDynObject

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23140]
Description: warning: Source file is more recent than executable. 
4997  DynamicObject* dynObj = *i;

Crash log
https://gist.github.com/HAANAAE/65a5d5988ec60bda426399dc4376528b

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/fa8c0dd534723a573268ccd8bb40c0846cb35936
Operating system: debian

**Comment by illfated** [comment]
> warning: Source file is more recent than executable.

I can't guarantee that this is the cause of your problem, but it looks as if you have pulled more recent source than the compiled executable file is, thereby causing a mismatch between the git source & server.

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
more than 1 month without answer, if this bug is still valid open a new ticket.
