### ISSUE TITLE
Closed proto files in Master branch.

### ISSUE THREAD

**Issue by asd567800** [TrinityCore/TrinityCore#23144]
The question was asked before two years ago.
Dev master Shauren re:
The reason these files are not included is that you are not supposed to modify them at all, its as if you changed world packet structures "just because this seems better".

Question:
I think  that's not a  good reason. Since just as he wish,  I suggest  providing some .dll or .so will be better. So no one can modify it.

If some one wants to learn the protocols . He must have to decompiler the pb files ?  That just sound like a joke.

If some one modified for learning ?  So I dont know what's the worth for closed some proto files.

If it has some  legal issuses . Just  take out it clearly.

**Comment by Shauren** [comment]
Use the decompiler I wrote, its open source.
