### ISSUE TITLE
[LoS/Bug/3.3.5a] Elwynn Forest 

### ISSUE THREAD

**Issue by Eleix** [TrinityCore/TrinityCore#23158]
**Description:**

Line of Sight fails to prevent casting of ranged attacks when behind trees in Elwynn Forest even though vmaps are present.

**Current behaviour:**

Casting fireball on a boar from behind the trees next to Goldshire will successfully cast and hurt the target.

**Expected behaviour:**

Cast should fail due to line of sight.

**Steps to reproduce the problem:**

1. Go to Goldshire
2. Find a boar
3. Hide behind a tree closest to the boar
4. Cast Fireball

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 770a14c0035f 2019-04-03 00:45:08 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:** Ubuntu Server 18.04.2 LTS

**Comment by Killyana** [comment]
It's a retail behavior https://github.com/TrinityCore/TrinityCore/issues/19185

**Comment by Eleix** [comment]
Oh, my bad then. Thanks for clearing that up.
