### ISSUE TITLE
EMOTE_ONESHOT_WOUND_CRITICAL

### ISSUE THREAD

**Issue by robinsch** [TrinityCore/TrinityCore#23152]
**Description:**
EMOTE_ONESHOT_WOUND_CRITICAL should not always be displayed. For example on raid bosses.

Still haven't figured out when it should be displayed.
Clearly on raid bosses but some dungeon bosses also don't display it.

https://youtu.be/ztFkxu772is?t=134 - Dungeon Bosss doesn't display it
https://www.youtube.com/watch?v=Wn5lLlPNnvA&feature=youtu.be&t=217 - Dungeon boss displaying it
https://www.youtube.com/watch?v=6CNN_Cn2L2A&feature=youtu.be&t=357 - Raid boss displaying it

Maybe it has something to do with model size?

**Current behaviour:**
EMOTE_ONESHOT_WOUND_CRITICAL is always displayed

**Branch(es):**

both

**TC rev. hash/commit:** 5c082064da59227c08271508a5f2ce71e66da0d6

See: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L1369

**Comment by Kittnz** [comment]
A check, but from where and what data can we use. myabe in the creature_difficulty table from kinz?

**Comment by Ovahlord** [comment]
This is not a emote that is being played, that's a typeflag. And this value comes from sniffed data.

**Comment by robinsch** [comment]
So it's completly decided by client if the animation should be shown or not?

**Comment by Killyana** [comment]
https://www.wowhead.com/npc=18343/tavarok  has this flag:
CREATURE_DIFFICULTYFLAGS_DO_NOT_PLAY_WOUND_PARRY_ANIMATION = 0x00800000, // CREATURE_TYPEFLAGS_DO_NOT_PLAY_WOUND_PARRY_ANIMATION

**Comment by Ovahlord** [comment]
also make sure it's applied for all difficulty entries and you are fine. That should do the trick.

**Comment by Killyana** [comment]
On 3.3.5 : CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_PARRY_ANIMATION = 0x00000008,
I added the flag: UPDATE creature_template SET type_flags=type_flags|8 WHERE entry IN (18343,20268);
But still the creature play the animation if the hit is critical

**Comment by Ovahlord** [comment]
I have checked the videos that have been posted as reference and it was clearly visible that the bosses there were also playinf crit hit animations so looks to me like a false positibe report.

**Comment by illfated** [comment]
Sorry if my question is misplaced or based on misunderstanding this discussion,
but is this in any way related to Hunter's Mark causing an emote on targetable NPCs?

**Comment by Kittnz** [comment]
> 
> 
> Sorry if my question is misplaced or based on misunderstanding this discussion,
> but is this in any way related to Hunter's Mark causing animation on targetable NPCs?

Nope :)

**Comment by ForesterDev** [comment]
```
On 3.3.5 : CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_PARRY_ANIMATION = 0x00000008,
I added the flag: UPDATE creature_template SET type_flags=type_flags|8 WHERE entry IN (18343,20268);
But still the creature play the animation if the hit is critical
```
Because it doesn't have support in the core

**Comment by ForesterDev** [comment]
Maybe something like this

```
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 7cf57adaca..e53972ab07 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -1365,10 +1365,13 @@ void Unit::DealMeleeDamage(CalcDamageInfo* damageInfo, bool durabilityLoss)
         return;
 
     // Hmmmm dont like this emotes client must by self do all animations
-    if (damageInfo->HitInfo & HITINFO_CRITICALHIT)
-        victim->HandleEmoteCommand(EMOTE_ONESHOT_WOUND_CRITICAL);
-    if (damageInfo->Blocked && damageInfo->TargetState != VICTIMSTATE_BLOCKS)
-        victim->HandleEmoteCommand(EMOTE_ONESHOT_PARRY_SHIELD);
+    if (victim->GetTypeId() != TYPEID_UNIT || !(victim->ToCreature()->GetCreatureTemplate()->type_flags & CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_PARRY_ANIMATION))
+    {
+        if (damageInfo->HitInfo & HITINFO_CRITICALHIT)
+            victim->HandleEmoteCommand(EMOTE_ONESHOT_WOUND_CRITICAL);
+        if (damageInfo->Blocked && damageInfo->TargetState != VICTIMSTATE_BLOCKS)
+            victim->HandleEmoteCommand(EMOTE_ONESHOT_PARRY_SHIELD);
+    }
 
     if (damageInfo->TargetState == VICTIMSTATE_PARRY &&
         (GetTypeId() != TYPEID_UNIT || (ToCreature()->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN) == 0))
```

**Comment by Kittnz** [comment]
PR that please.

**Comment by ForesterDev** [comment]
I'm not sure if this correct way. Also don't test this

**Comment by ForesterDev** [comment]
Just tested - this part of code is useless. Client without this code sends proper animations

**Comment by Ovahlord** [comment]
I think this emote command calling in general is one big hack. Usually such hit emotes are being handled by the attackerstate update packet which probably did not work properly back then. So you might remove all that emote spaming completely instead.

**Comment by Killyana** [comment]
You must clear client cache to see the result.
Also blizzard updated many creatures with the flag CREATURE_TYPE_FLAG_DO_NOT_PLAY_WOUND_PARRY_ANIMATION after wotlk, like Tavarok who has the flag on cata but not on wotlk.
So do we update the DB according to cata+ data or not?

**Comment by Ovahlord** [comment]
The typeflags should not have changed ever since then

**Comment by Killyana** [comment]
looks like they forget some npcs
Check 18343 in both DBs
SELECT entry, NAME, type_flags FROM `creature_template` WHERE `entry` IN (18343);

**Comment by ForesterDev** [comment]
`typeflags` is WDB field, i think, before change something here, need to check in actual sniffs

**Comment by Killyana** [comment]
I know, but this is just a cosmetic issue forgotten by blizzard and fixed in the next expansion

**Comment by Kittnz** [comment]
Yeah, found in sniffs Type Flags: BossMob, DoNotPlayWoundParryAnimation (12)

**Comment by Killyana** [comment]
As type_flags is WDB field and the main issue is fixed, this could be closed.
