### ISSUE TITLE
Multi-thread when ?

### ISSUE THREAD

**Issue by wonder2011** [TrinityCore/TrinityCore#23166]
**Description:**
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?
CHANGEME Description of the problem or issue here.
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?
**Current behaviour:**
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?
CHANGEME Tell us what happens.
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?

**Expected behaviour:**
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?
CHANGEME Tell us your suggestion
Why Shauren don't implement the multi-thread yet?, this server with 600 players in the same map, have a very hight diff. Why not do an efford to make Map::Update && Player::Update multi-thread?

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Comment by Aokromes** [comment]
this ain't a forum.

**Comment by wonder2011** [comment]
All private server's like firestorm and other have this. So, why don't make part of the native Trinity Core ?

**Comment by wonder2011** [comment]
@Aokromes this is not a forum, but, because in the 21st century with all the power of microprocessors with multiple cores, still trinitycore does not implement multithreading in most of the most important parts like Map::Update and Player::Update?

**Comment by wonder2011** [comment]
@Aokromes i think please like you, me && @Shauren or @Traesh have the power to do that. To help community and make a best TrinityCore. Why don't do that just now?

**Comment by TheNeoTV** [comment]
If you need the Multi Thread power then you should be able to do this or wait until it has come out ;)

**Comment by wonder2011** [comment]
@TheNeoTV please bitch, this is a shit. This guys do that only for his private project's. I can implement, but if i don't see help for any other people, then do this bu your own.
