### ISSUE TITLE
Core/Spell: Log spam from Periodic Trigger Spell

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23164]
**Description:** when an aura with the effect Periodic Trigger Spell is apply to a unit it will spam the server log if there's no spell to be triggered.

example:
https://woehead.way-of-elendil.fr/?spell=40113
https://woehead.way-of-elendil.fr/?spell=66656

**Steps to reproduce the problem:**

1. .go c 85662 (with gm on and stay at the ground)
2. notice the spam
3. .aura 66656 an notice the spam
AuraEffect::HandlePeriodicTriggerSpellAuraTick: Spell 66656 has non-existent spell 0 in EffectTriggered[0] and is therefore not triggered.

AuraEffect::HandlePeriodicTriggerSpellAuraTick: Spell 40113 has non-existent spell 0 in EffectTriggered[0] and is therefore not triggered.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. c52eb49

**Comment by jackpoz** [comment]
doesn't the spam depend on how often the spell is triggered ? so it's just a matter of fixing the spell ?

**Comment by ForesterDev** [comment]
My suggestion for this report. If you think it's valid - i can create PR

https://github.com/ForesterDev/TrinityCore/commit/95f65b0c4cdfa132afc16683e2ddcceca74d34f7

**Comment by Killyana** [comment]
Better to open a PR, you will get more feed back

**Comment by jackpoz** [comment]
please test all the new code and all the cases too

**Comment by ForesterDev** [comment]
Just tested:

with Logger.spells=3,Console Server - no messages in logs

with Logger.spells=2,Console Server - 
```
SpellMgr::GetSpellForDifficultyFromSpell: Spell id for instance mode is 40112 (original 40112)
Spell::LoadScripts: Script `spell_q11010_q11102_q11023_aggro_check` for spell `40112` is loaded now
Spell::prepare: spell id 40112 source 23077 caster 23077 customCastFlags 0 mask 0
AuraEffect::HandlePeriodicTriggerSpellAuraTick: Spell 40113 [EffectIndex: 0] does not have triggered spell.

```

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/1f853480ee07d22fdbe9782d600423bbd4ef4abb

I moved the "spell Id is 0" logs to TC_LOG_WARN and kept the "spell Id is invalid" to TC_LOG_ERROR.
There are a few categories but they are shared for both types of errors
- spells.aura.effect.nospell when it's in AuraEffect (SpellAuraEffects.cpp)
- spells.effect.nospell when it's in Spell (SpellEffect.cpp)

You can choose to filter out those logs using the 2 log categories above (or keep the logs if you want to get them). You can choose the log level to get (or not get) logs about spell id 0 too
