### ISSUE TITLE
Shield Block/Spell Reflection/Shield Wall Spells Auras.

### ISSUE THREAD

**Issue by Illuminati2739** [TrinityCore/TrinityCore#23169]
**Description:**
Shield only auras remain on player even if player removes the shield and equips a 2h sword, which can be done very quick with a macro.

**Current behaviour:**

A warrior can equip a shield, Cast Shield Wall, remove a shield and equip 2H Sword and your Auras from "Shield Block" will remain on player while using a 2H Sword..

Affected Spells:

Shield Block spell=2565
Spell Reflection spell=23920
Shield Wall spell=871

Latest revision.

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b8c281f497d5da2251b11ab09f182a23a5721a1c#diff-5589ee47b3a7ad220cff105a8fe7eac3R23534

**Comment by Aokromes** [comment]
there is no such thing as "latest revision"

**Comment by Killyana** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/21594
