### ISSUE TITLE
Players loses Improved Spells after Battleground.

### ISSUE THREAD

**Issue by Illuminati2739** [TrinityCore/TrinityCore#23161]
**Description:**

I tested this on few classes however i think its all related so i will start with a Shaman. 
If you put talent points in improved healing wave, joing BG , Leave BG , Your improved healing wave goes back its original state.

I beleive it has something to do with how auras are being removed. 

Because command .unaura all removes Improved Talent Auras as well.

**Expected behaviour:**

Improved Spell Auras should not dissapear after Battleground or after .unaura all

**Steps to reproduce the problem:**

1. Put TP in any improved talent option.
2. Join BG 
3. Leave BG
4. Improved tallents are no longer improved until relog.

Another test can be done,
Put points in Improved Ghost Wolf. It is now instant cast, do a gm command .unaura all and instant cast is gone until relog. Same goes for Battleground leaving.

**Branch(es):**
3.3.5

**Comment by Killyana** [comment]
I cannot reproduce the issue with the BG
Talents are auras this auras remains whatever I enter and leave the BG or not
If you unaura all you char all auras include ones related to talents are removed and this 100% normal, you can even test some talents with .aura SpellID of the talent 
Example: https://woehead.way-of-elendil.fr/?spell=16287

**Comment by jackpoz** [comment]
are you using a clean TC or do you have any custom patch ?

**Comment by Illuminati2739** [comment]
No custom patches, I tested on clean TC, it happens only after you return to your original location after a battleground, I was able to reproduce the bug few times after i joined a BG and left few minutes after, I was using Improved Ghost Wolf talent to make it instant, after BG it becomes non instant until you relog. That issue is valid and present in latest TC revisions

**Comment by Killyana** [comment]
How do you leave the BG?

**Comment by Illuminati2739** [comment]
The issue happens when you join BG , stay untill the BG finishes, when you return back to your last location, 50% of the time you will loose all your improved talents. It happends 1 out of 5 times. I still beleive it has something to do with how auras are being removed.

**Comment by Killyana** [comment]
What's the initial position of the character before joining the BG?
Also it's possible to reproduce the issue with a manual leave?

**Comment by Faq** [comment]
Video would make easier to understand how you reproduce it :)

**Comment by Illuminati2739** [comment]
Initial position: Shattrath City. You can reproduce it by leaving BG as well. Most of the time when you return to initial position you become naked and sometimes you lose your improved auras and at times both of these at the same time.
