### ISSUE TITLE
[Quest] Magisters' Terrace breadcrumbs

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#23174]
**Description:**
```sql
DELETE FROM `quest_template_addon` WHERE `ID` IN (11481,11482);
INSERT INTO `quest_template_addon` (`ID`,`BreadcrumbForQuestId`) VALUES
(11481,11488),
(11482,11488);
```
https://wowwiki.fandom.com/wiki/Quest:Crisis_at_the_Sunwell

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
9c9ad671309124712d47042ad8b6885756f26801

**Comment by illfated** [comment]
Links to the wowhead.com quest pages (in case someone asks):
- https://www.wowhead.com/quest=11481/crisis-at-the-sunwell
- https://www.wowhead.com/quest=11482/duty-calls
