### ISSUE TITLE
MySQLConnection undefine  behaviour

### ISSUE THREAD

**Issue by noeat** [TrinityCore/TrinityCore#23178]
**Description:**

function:MySQLConnection::Open()
   TC_LOG_ERROR("sql.sql", "Could not connect to MySQL database at %s: %s", m_connectionInfo.host.c_str(), mysql_error(mysqlInit));
        mysql_close(mysqlInit);
        return mysql_errno(mysqlInit);

mysqlInit already released，call mysql_errno is undefine behaviour.
that may cause crash or mysqconnection cant work。

**Branch(es):**

master

**TC rev. hash/commit:** 

**Operating system:** all OS

**Comment by illfated** [comment]
More information needed, such as
TC commit rev. hash
MySQL server version
Operating Systems + versions.

Myself, I don't get that error.
Windows 10 + MySQL server 5.6.41
Don't know how to replicate your error.

**Comment by noeat** [comment]
beacuse mysql_close already release mysqlinit, mysqlinit is wild pointer，then call mysql_errno got a undefine value.

it every difficult replicate.

**Comment by illfated** [comment]
Yes, it is difficult to replicate.
But could you at least tell us what setup you are using,
so we may have even a small chance?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/3230ca74d21517204bb785e9ec799d995295ad28 is for 335 but handles the issue you arised.

**Comment by jackpoz** [comment]
Closing this issue as it was fixed in 335 and anyone could cherry-pick it to master (if interested into master branch)
