### ISSUE TITLE
Thrown

### ISSUE THREAD

**Issue by D0d0** [TrinityCore/TrinityCore#23172]
**Description:**

Thrown can be learned by all classes. Classes are loaded from `SkillLine.dbc` and `SkillLineCategory.dbc` and Thrown (spell 2567) has classmask 0. I also checked https://woehead.way-of-elendil.fr/?spell=2567 and compared to https://woehead.way-of-elendil.fr/?spell=266 and you can see the problem is also here - guns have correct classes.

**Current behaviour:**

Thrown can be learned by all classes

**Expected behaviour:**

Thrown should be learned only by Warriors, Hunters and Rogues.

**Steps to reproduce the problem:**

1. Create gnome mage with long beard :)
2. .tele Darnassus
3. Find first weapon trainer
4. Learn Thrown

**Branch(es):**

3.3.5

**Comment by Cobus420** [comment]
Checked on Branch 3.3.5 after latest commit. [0adfda6](https://github.com/TrinityCore/TrinityCore/commit/0adfda655178d5e6a2162461a9239972d65a2d35) running on (Win64, Release, Static) i can confirm this issue.

**Comment by Killyana** [comment]
We don't have a field to override ClassMask on trainer_spell
![image](https://user-images.githubusercontent.com/6587064/55737493-91ec8f00-5a25-11e9-9c31-1e882c9e521e.png)

**Comment by D0d0** [comment]
Maybe we can create new table `skilllineability_dbc` like `spell_dbc` and overwrite incorrect value?

**Comment by Killyana** [comment]
SkillRaceClassInfo.dbc contain SkillID=176 used SkillLineAbility.dbc as SkillLine
![image](https://user-images.githubusercontent.com/6587064/55742951-5fe12a00-5a31-11e9-90e0-3103032f3f4f.png)

**Comment by D0d0** [comment]
I checked how trainer send spells https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Creature/Trainer.cpp#L48 and the concrete function
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L23255 which looks up into `SkillLineAbilityEntry` from `SkillLineAbilityEntry.dbc` not from `SkillLineAbility.dbc`

**Comment by D0d0** [comment]
This small patch can solve issue. First we check classes and races from `SkillLine.dbc` then `SkillRaceClassInfo.dbc` 

```diff
Index: src/server/game/Entities/Player/Player.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/server/game/Entities/Player/Player.cpp	(revision 171022f44bf19d4cbc88916dada0efb648bf7de3)
+++ src/server/game/Entities/Player/Player.cpp	(date 1554745068000)
@@ -23271,6 +23271,9 @@
         if (_spell_idx->second->classmask && (_spell_idx->second->classmask & classmask) == 0)
             continue;
 
+        if (!GetSkillRaceClassInfo(_spell_idx->second->skillId, getRace(), getClass()))
+            continue;
+
         return true;
     }
 ```

**Comment by Kittnz** [comment]
Can you PR this for a possible fix?
