### ISSUE TITLE
show new startup errors at end.

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23177]
**Description:**

i wonder if it's doable to add in case of we have save db error  to multiple files to check if there are new rows since previous startup and show a warning
IE:
New startup errors added since last restart:
xxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxy
xxxxxxxxxxxxxxxxxxxxz
possible columns:

message, first occurrence, last occurrence, present in last run, hash

**Current behaviour:**

you code some new quest
you have to dig the logs to find if there is any new error

**Expected behaviour:**

you see the log of newly added errors at end of startup

**TC rev. hash/commit:** 

201e0763eb76 (N/R)

**Comment by jackpoz** [comment]
columns: message (varchar), first occurrence (datetime), last occurrence (datetime), present in last run (bool), hash (same as DBUpdater)

**Comment by Shauren** [comment]
You could also make use of db log appender and write a query with `group by` to get similar data

**Comment by jackpoz** [comment]
Just need to get db log to work

**Comment by jackpoz** [comment]
DB logging is enabled only after World has been initialized at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/World/World.cpp#L2159 , setting the realm id to the loggin. This means right now it's impossible to log startup errors in the db log appender

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9fe43fa9c0bd21f6c203072f19a77a570680ecab#diff-b32f1858cfb04ed3727c85b4aee11e7fR1503

**Comment by jackpoz** [comment]
The Appender should look like this:
>Appender.DB=3,5,0

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/dbd8b3fc63d1b218df755f34fd7185553f2db3a5 and https://github.com/TrinityCore/TrinityCore/commit/9fc4ff9dd29968c1d64f47df4e721b468ac87362 should give you the info you need

You can use the view like "select * from vw_log_history where `type` = 'mmaps.tiles'

![image](https://user-images.githubusercontent.com/1153754/59048968-46205f80-8887-11e9-8a15-2b15df262600.png)
