### ISSUE TITLE
Error log: MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed , then the server crashed

### ISSUE THREAD

**Issue by fan3750060** [TrinityCore/TrinityCore#23188]
**Description:**

I compiled the 7.3.5_26972 branch. After starting this service, logging in the game will always prompt: MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x2800046B8037E5C00000000000000001 Type: Pet Pet number: 57239 Low: 1 Entry : 57239, then the service process crashes

**Current behaviour:**

CHANGEME Tell us what happens.
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442400F48800000000000000202 Type: Creature Entry: 15650 Low: 514 Entry: 15650
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442400F45800000000000000289 Type: Creature Entry: 15638 Low: 649 Entry: 15638
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x2000044240104D40000000000000031C Type: Creature Entry: 16693 Low: 796 Entry: 16693
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442400F47C00000000000000377 Type: Creature Entry: 15647 Low: 887 Entry: 15647
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442400F47C0000000000000037D Type: Creature Entry: 15647 Low: 893 Entry: 15647
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442400F4A800000000000000426 Type: Creature Entry: 15658 Low: 1062 Entry: 15658
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x200004424010468000000000000004B3 Type: Creature Entry: 16666 Low: 1203 Entry: 16666
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x200004424010498000000000000004B4 Type: Creature Entry: 16678 Low: 1204 Entry: 16678
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442401043C000000000000004C7 Type: Creature Entry: 16655 Low: 1223 Entry: 16655
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442401047C00000000000000514 Type: Creature Entry: 16671 Low: 1300 Entry: 16671
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442401046C00000000000000520 Type: Creature Entry: 16667 Low: 1312 Entry: 16667
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x20000442401040C0000000000000056C Type: Creature Entry: 16643 Low: 1388 Entry: 16643
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32DF (13023)] from [Player: Toman GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 1]
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32DF (13023)] from [Player: Toman GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 1]
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32DF (13023)] from [Player: Toman GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 1]
No defined handler for opcode [UNKNOWN OPCODE 0x354D (13645)] sent by [Player: Toman GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 1]

**Expected behaviour:**

CHANGEME Tell us what should happen instead.
I hope that the worldserver will no longer prompt this error and the server will not crash.
**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
After logging in to the game
2. Step 2
Worldserver always outputs this error
3. Step 3
Worldserver This process has broken down

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS
win10 ,x64

**Comment by Shauren** [comment]
> MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed 

That is harmless

Useless report - crashes must be reported with a stack trace
