### ISSUE TITLE
[master(8.x)] Some BFA cinematics broken

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#23184]
Description: Some Cinematic do not work, namely the BFA addons

Current behaviour: When you turn on certain cinematic, instead of the video, the black screen turns on, and after a short period of time it closes

Expected behaviour: The cinematics should be played without any problems.

Steps to reproduce the problem: /run MovieFrame_PlayMovie(MovieFrame, 865)

Additional info: In addition, cinematic does not work with id: 864,863,862
865 - Jaina salvation
864 - Kul Tiras Finale
863 - Zandalar Finale
862 - Deal with bwonsamdi

Branch(es): master

TC rev. hash/commit: f729050

TDB version: f729050

Operating system: win10

**Comment by Shauren** [comment]
missing tact_keys

**Comment by DintyGadget** [comment]
> missing tact_keys

I have already added all the keys from tactkey.db2 on client 8.0.1 28153 This did not help

**Comment by funjoker** [comment]
Hotfixes might be missing

**Comment by welder1976** [comment]
What

**Comment by DintyGadget** [comment]
> Hotfixes might be missing

I don’t have to make these changes at all, because these keys are already in the DB2 file, most likely you need other keys that are not in DB2, but I don’t know where to get them (such keys are in the table)

**Comment by funjoker** [comment]
Stuff missing in db2 -> hotfixes :D

**Comment by DintyGadget** [comment]
> Stuff missing in db2 -> hotfixes :D

if there is a need for data from sniff, in that case I will not be able to fix it, there is no desire to play on the official server, and there is no money either: D

**Comment by shamage** [comment]
@DintyGadget   :  
I'd like to play on the official servers at my own expense, but I need to learn how to sniff - because I don't know how to do it :)

**Comment by Lartty96** [comment]
Sniffing right now to get hotfix is most likely useless. They must've moved them to db2 already :D

**Comment by DintyGadget** [comment]
I found the ID of the missing keys, but I need someone to retrieve data from these keys, their numbers: 229-232. In the file tactkey.db2 there are no these keys on any version of the file, we just need a sniff.

**Comment by DintyGadget** [comment]
I find and decrypt key ))

`229	184	115	25	38	56	148	153	203	212	173	191	80	6	202	3	145	28153
230	37	167	124	216	0	25	126	230	163	45	214	63	4	225	21	250	28153
231	88	174	62	6	66	16	227	237	249	193	37	156	222	145	76	93	28153
232	52	164	50	4	32	115	205	11	81	98	112	104	210	224	189	62	28153
`

**Comment by illfated** [comment]
> I find and decrypt key ))
> 
```
229 184  115  25  38 56 148 153 203 212 173 191  80   6 202   3 145 28153

230  37  167 124 216  0  25 126 230 163  45 214  63   4 225  21 250 28153

231  88  174  62   6 66  16 227 237 249 193  37 156 222 145  76  93 28153

232  52  164  50   4 32 115 205  11  81  98 112 104 210 224 189  62 28153
```
Should be useful feedback, but I think it is too early to close this issue.

**Comment by DintyGadget** [comment]
> > I find and decrypt key ))
> 
> ```
> 229 184  115  25  38 56 148 153 203 212 173 191  80   6 202   3 145 28153
> 
> 230  37  167 124 216  0  25 126 230 163  45 214  63   4 225  21 250 28153
> 
> 231  88  174  62   6 66  16 227 237 249 193  37 156 222 145  76  93 28153
> 
> 232  52  164  50   4 32 115 205  11  81  98 112 104 210 224 189  62 28153
> ```
> 
> Should be useful feedback, but I think it is too early to close this issue.

I checked it myself and it works, the above says how to run the cinematic from the client, do not believe it, check it yourself

**Comment by Killyana** [comment]
This key must be set somewhere in the DB or the core?

**Comment by DintyGadget** [comment]
> This key must be set somewhere in the DB or the core?

in the db in the hotfixes database in the tact_key table

**Comment by Killyana** [comment]
I find 3 other keys, they must be checked
``` sql
DELETE FROM `tact_key` WHERE `ID` IN (81, 93, 94, 229, 230, 231, 232);
INSERT INTO `tact_key` (`ID`, `Key1`, `Key2`, `Key3`, `Key4`, `Key5`, `Key6`, `Key7`, `Key8`, `Key9`, `Key10`, `Key11`, `Key12`, `Key13`, `Key14`, `Key15`, `Key16`, `VerifiedBuild`) VALUES
(229, 184,  115,  25,  38, 56, 148, 153, 203, 212, 173, 191,  80,   6, 202,   3, 145, 28153),
(230,  37,  167, 124, 216,  0,  25, 126, 230, 163,  45, 214,  63,   4, 225,  21, 250, 28153),
(231,  88,  174,  62,   6, 66,  16, 227, 237, 249, 193,  37, 156, 222, 145,  76,  93, 28153),
(232,  52,  164,  50,   4, 32, 115, 205,  11,  81,  98, 112, 104, 210, 224, 189,  62, 28153),
-- Not verified
(81, 183, 47, 239, 74, 1, 72, 138, 136, 255, 2, 40, 10, 160, 122, 146, 187, 23420),
(93, 2, 153, 11, 18, 38, 12, 30, 159, 221, 115, 254, 71, 203, 171, 112, 36, 23911),
(94, 27, 120, 155, 135, 251, 60, 146, 56, 213, 40, 153, 123, 250, 180, 65, 134, 23911);

**Comment by DintyGadget** [comment]
> I find 3 other keys, they must be checked
> 
> ```sql
> DELETE FROM `tact_key` WHERE `ID` IN (81, 93, 94, 229, 230, 231, 232);
> INSERT INTO `tact_key` (`ID`, `Key1`, `Key2`, `Key3`, `Key4`, `Key5`, `Key6`, `Key7`, `Key8`, `Key9`, `Key10`, `Key11`, `Key12`, `Key13`, `Key14`, `Key15`, `Key16`, `VerifiedBuild`) VALUES
> (229, 184,  115,  25,  38, 56, 148, 153, 203, 212, 173, 191,  80,   6, 202,   3, 145, 28153),
> (230,  37,  167, 124, 216,  0,  25, 126, 230, 163,  45, 214,  63,   4, 225,  21, 250, 28153),
> (231,  88,  174,  62,   6, 66,  16, 227, 237, 249, 193,  37, 156, 222, 145,  76,  93, 28153),
> (232,  52,  164,  50,   4, 32, 115, 205,  11,  81,  98, 112, 104, 210, 224, 189,  62, 28153),
> -- Not verified
> (81, 183, 47, 239, 74, 1, 72, 138, 136, 255, 2, 40, 10, 160, 122, 146, 187, 23420),
> (93, 2, 153, 11, 18, 38, 12, 30, 159, 221, 115, 254, 71, 203, 171, 112, 36, 23911),
> (94, 27, 120, 155, 135, 251, 60, 146, 56, 213, 40, 153, 123, 250, 180, 65, 134, 23911);
> ```

81  WOW-22578patch7.1.0_PTR   Firecat Mount
93  WOW-23789patch7.2.0_PTR   legion_72_ots
94  WOW-23789patch7.2.0_PTR   legion_72_tst

**Comment by Killyana** [comment]
So 81, 93, 94   are deprecated?

**Comment by DintyGadget** [comment]
> So 81, 93, 94 are deprecated?

93 and 94 are not needed, since these cinematics work, but 81 is useful because it unlocks the mount for the HOTS promotion

**Comment by Killyana** [comment]
I will ask shauren tomorrow and push it if he agree.

**Comment by Shauren** [comment]
81, 93, 94 are not needed, they are already TactKey.db2 shipped with client
