### ISSUE TITLE
Lich King 10hc/25hc Harvest Soul

### ISSUE THREAD

**Issue by Dev-Incognito** [TrinityCore/TrinityCore#23182]
**Description:**

Harvest Soul teleports are broken.

**Current behaviour:**

After LK's spellcast Harvest Soul all players should be teleported to different mapid. (.t frostmourne) which is not happening, they're teleported to LK's platform instead, which is wrong.

**Expected behaviour:**

Players should be teleported to different mapid. (.t frostmourne)

**Steps to reproduce the problem:**

1. Do some dmg to LK and waitch for phase 3, when he casting Harvest Soul.
2. You can clearly see that you will be teleported to same mapid, same platform.

**Branch(es):** 3.3.5a

**TC rev. hash/commit:** 

**Operating system:** Win 64

**Comment by Aokromes** [comment]
also, duplicate #22883
