### ISSUE TITLE
Script: `spell_dru_lifebloom` Spell: `48451` AuraScript::GetTarget called in a hook in which the call won't have effect!

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23192]
**Description:**

Script: `spell_dru_lifebloom` Spell: `48451` AuraScript::GetTarget called in a hook in which the call won't have effect!

**Current behaviour:**

from time to time this log apears on console

**Expected behaviour:**

no log must apear

**Steps to reproduce the problem:**

no idea

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5262d760ffc7

**Operating system:** linux

**Comment by illfated** [comment]
I would think that this log should appear whenever a druid casts Lifebloom (not sure if it only works for a specific rank of the spell).
Then again, I guess you have already tested using a druid and cast Lifebloom multiple times, right?

**Comment by Keader** [comment]
@illfated 
correct grammar is:

Scripts/Spells: Fixed a console error on spell_dru_lifebloom 
or Scripts/Spells: Fixed a console error in spell_dru_lifebloom ??
"in" or "on"? :)

**Comment by illfated** [comment]
LoL - I am really predictable, am I not? 😆

**Comment by Keader** [comment]
Looks like someone fucked spaces 🙄
