### ISSUE TITLE
[Crash] _defaultGenerator->Deactivate #

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23199]
Description: warning: Not specified

Crash log
https://gist.github.com/HAANAAE/704f017e160faa782256d45bf01ae1c1

Branch(es): 3.3.5
TC rev. hash/commit: b33934f
Operating system: debian

**Comment by Shauren** [comment]
Character loads with a confuse aura (rogue blind?)
MotionMaster is not initialized until after LoadFromDB finishes

**Comment by ccrs** [comment]
Invalidate the aura while loading?
Prevent the aura from saving?
Make MotionMaster initialize before LoadFromDB?

**Comment by Shauren** [comment]
Delay MoveConfuse until after adding to world? First two options would give you incorrect behavior

**Comment by ccrs** [comment]
makes sense, queue everything and signal MotionMaster, neat
not too difficult to implement after the rework too hehe

**Comment by HAANAAE** [comment]
https://gist.github.com/HAANAAE/7fe1b38db67b8f863290730ce9a50a54

**Comment by jackpoz** [comment]
@ccrs could you check this issue when you have time ?

**Comment by jackpoz** [comment]
Crash reproduced
- .cast 9992 https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=9992
- logout
- login

**Comment by jackpoz** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/9941b4c2edcf63e6e521249a6660b590f23cd08d

**Comment by ccrs** [comment]
MotionMaster modifications have been delayed till just after AddToWorld

new crashlog: https://github.com/TrinityCore/TrinityCore/files/3756374/unknown_worldserver.exe_.22-10_16-26-15.txt

**Comment by jackpoz** [comment]
MoveChase is still added before the default one is added as both are added to delayed actions queue, first MoveChase and then Initialize

**Comment by ccrs** [comment]
`unsigned int BaseUnitState = 0x800` --> `UNIT_STATE_CONFUSED` --> `MotionMaster::MoveConfused()` 😄 

but damn.. this is annoying
if we just protect `_defaultGenerator->Deactivate(_owner);` against incorrect access we will bump into:
* MoveConfused --> Initialize --> Clear --> MoveConfused is gone

**Comment by ccrs** [comment]
transform delayedActions into priority queue? 😨 

ignore all Initialize calls done during "initializing" --> always perform one Initialize call before handling the queue --> handle the queue ??? 😨

**Comment by jackpoz** [comment]
Creatures in formations call MoveIdle() instead of Initialize() which make it harder to know when the initialization has been completed, see https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Creature/Creature.cpp#L998

**Comment by jackpoz** [comment]
> but damn.. this is annoying

yes xD

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c9c6871659bf2be52b4656bc641df5211fcb928f
