### ISSUE TITLE
TC Core / Compile Errors  

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#23209]
**Description:**

TC compilation error.

**Current behaviour:**

CHANGEME Tell us what happens.
==> [crashlog](https://gist.github.com/shamage/01df4d556eba6de8c1ece0e7c253d98a#file-compile-tc-to-vs-crashlog) <== 

**Expected behaviour:**

The compilation should be successful without errors, with the necessary files to create the Release folder.

**Steps to reproduce the problem:**

1. compile  TC

**Branch(es):**

CHANGEME :  master

**TC rev. hash/commit:**   920c3cbac488 2019-04-18 14:37:29 +0200 (master branch)

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Win 10 Pro

**Comment by Aokromes** [comment]
compile works following wiki.

**Comment by shamage** [comment]
the compilation procedure was followed according to available instructions, I think the error will be somewhere in TC

all compilations I performed until 1.1.2019 were successful and OK from TC (master branch)

**Comment by shamage** [comment]
Link 1 to error :  [LNK2019](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2019)%26rd%3Dtrue&view=vs-2019)
Link 2 to error : [LNK2001](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK2001)%26rd%3Dtrue&view=vs-2019)
Link 3 to error : [LNK1120](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1120?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(LNK1120)%26rd%3Dtrue&view=vs-2019)


if you already hit me at the wiki link, at least it is really not a more serious problem than just compiling instructions

**Comment by Aokromes** [comment]
https://i.imgur.com/C3xjiPZ.png

**Comment by illfated** [comment]
@shamage : According to your log, you have not installed the OpenSSL package properly.
Choose between installing the binaries to `C:\Windows\System32\` 
or set CMake `OPEN_SSL_INCLUDE` to `C:/OpenSSL-Win64/include`
(and copy the needed SSL files to the core folder to run it)

**Comment by shamage** [comment]
@Aokromes , @illfated   

Indeed, OpenSSL was incorrectly installed, but I didn't realize it at all - thank you for your support and resolution :)
