### ISSUE TITLE
LOCK_KEY_SPELL implementation

### ISSUE THREAD

**Issue by xvwyh** [TrinityCore/TrinityCore#23205]
As of 3.3.5, Lock.dbc contains 4 different types of locks: 3 already implemented, one - not. In the case of this not-yet-implemented lock type, LockEntry::Index field contains the ID of a spell that needs to be cast by the player to facilitate opening of the lock, be it for special conditions or appropriate visuals, or just a more fancy name on the cast bar. Hence I called it `LOCK_KEY_SPELL`, but a name like `LOCK_KEY_CUSTOM_SPELL` or `LOCK_KEY_SPELLCAST` would also be alright.

There are only 3 locks that use this type in 3.3.5:
- 1810
  - not used?
  - opened by a spell with a wonderful ID of 10000 - Douse Lock

- 1819
  - used by GO 190752, 195235, 195331 - battleground Seaforium Bombs
  - opened by a spell 1843 - Disarm

- 1845
  - used by GO 194264 - Lever in Ulduar's Thorim encounter
  - opened by a spell 68398 - Opening - for extra long 10 secs cast time!

Unlike `LOCK_KEY_SKILL`, which requires the player to have learned an appropriate spell of an appropriate skill level to open the lock (be it for lockpicking's sake, or for profession-specific mechanics like herb gathering, mining etc), `LOCK_KEY_SPELL` does not require the player to know the spell - but the client will attempt to cast the spell regardless. This is a problem, because currently `CMSG_CAST_SPELL` handler would refuse such attempts, since the player doesn't "know" the spell they attempt to cast, and thus opening such a gameobject becomes impossible.

**Implementation:**
SharedDefines.h
```diff
 enum LockKeyType
 {
     LOCK_KEY_NONE  = 0,
     LOCK_KEY_ITEM  = 1,
-    LOCK_KEY_SKILL = 2
+    LOCK_KEY_SKILL = 2,
+    LOCK_KEY_SPELL = 3,
 };
```
(why oh why do you omit the trailing comma in your codestyle, such diffs would be one-liners otherwise)

GameObject::GetSpellForLock
This was just recently ported in #23179, but the author, I assume, thought this was a typo when the code wouldn't build, and replaced it with what they could find instead. Let's restore it to the way it was meant to be.
```diff
-        if (lock->Type[i] == LOCK_KEY_SKILL)
+        if (lock->Type[i] == LOCK_KEY_SPELL)
             if (SpellInfo const* spell = sSpellMgr->GetSpellInfo(lock->Index[i]))
                 return spell;
```
Spell::CanOpenLock
```diff
                 return SPELL_CAST_OK;
             }
+            case LOCK_KEY_SPELL:
+                if (m_spellInfo->Id == lockInfo->Index[j])
+                    return SPELL_CAST_OK;
+
+                reqKey = true;
+                break;
         }
     }
```
WorldSession::HandleCastSpellOpcode
Now that you have ported #23179, the code required here is hugely simplified by the ability to just call `GameObject::GetSpellForLock`
```diff
         caster = _player;
     }
 
+    // client provided targets
+    SpellCastTargets targets;
+    targets.Read(recvPacket, caster);
+    HandleClientCastFlags(recvPacket, castFlags, targets);
+
+    // not have spell in spellbook
     if (caster->GetTypeId() == TYPEID_PLAYER && !caster->ToPlayer()->HasActiveSpell(spellId))
     {
-        // not have spell in spellbook
-        recvPacket.rfinish(); // prevent spam at ignore packet
-        return;
+        bool allow = false;
+
+        // allow casting of unknown spells for special lock cases
+        if (GameObject* go = targets.GetGOTarget())
+            if (go->GetSpellForLock(caster->ToPlayer()) == spellInfo)
+                allow = true;
+
+        TODO: Insert code from #23204 here, something like
+        /* // allow casting of spells triggered by clientside periodic trigger auras
+        if (caster->HasAuraTypeWithTriggerSpell(SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT, spellId))
+        {
+            allow = true;
+            triggerCastFlags = TRIGGERED_FULL_MASK;
+        }*/
+
+        if (!allow)
+            return;
     }
 
     // can't use our own spells when we're in possession of another unit,
     if (_player->isPossessing())
-    {
-        recvPacket.rfinish(); // prevent spam at ignore packet
         return;
-    }
-
-    // client provided targets
-    SpellCastTargets targets;
-    targets.Read(recvPacket, caster);
-    HandleClientCastFlags(recvPacket, castFlags, targets);
 
     // auto-selection buff level base at target level (in spellInfo)
     if (targets.GetUnitTarget())
```

Oh, and in case you ever added these spells to \`playercreateinfo_spell\` table just to allow the players to open these locks - feel free to remove them from there.

**Branch(es):**

both

**TC rev. hash/commit:** 

32e1de39a26628dcb64bc21ad415afb2ad938925 (irrelevant, but hi, bot)

**Comment by xvwyh** [comment]
Whoops, guess I accidentally opened a feature request instead of a bug report, didn't see the difference because both issue types would open up blank for me for some reason.

**Comment by illfated** [comment]
It looks completely fine for me, nice to see that it was merged too. 👍
