### ISSUE TITLE
guild create command doesn't check max length

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23200]
**Description:**

guild create command doesn't check max length

**Current behaviour:**

guild create command doesn't check max length, it outputs sql error on console
**Expected behaviour:**

command must check max guild name length

**Steps to reproduce the problem:**

1. .guild create aokromes "GMs trinitycore test server"

**Branch(es):**

all

**TC rev. hash/commit:** 

ALL N/R adbbd0eda

**Operating system:** N/R

**Comment by jackpoz** [comment]
first issue spotted using http://tcubuntu.northeurope.cloudapp.azure.com :D
