### ISSUE TITLE
SPELL_AURA_48 implementation

### ISSUE THREAD

**Issue by xvwyh** [TrinityCore/TrinityCore#23204]
**Description:**

`SPELL_AURA_48` is very interesting. It may look like it's not implemented or it doesn't do anything, but in reality it does and we're just not noticing it. What it does, is it causes the **client** to periodically cast its trigger spell, via regular `CMSG_CAST_SPELL` packets. But since the player doesn't have these spells learned - the server just silently fails the cast as if it was a lag or a cheating attempt. And thus its true meaning has gone undiscovered for so long.

Let's call it `SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT`.

You'd wonder **why** does the server need the client to cast these spells. Surely the server can handle periodic casts on its own? `SPELL_AURA_PERIODIC_TRIGGER_SPELL` works just fine for that, right? The answer lies in the kind of spells it's meant to trigger: spells with `TARGET_DEST_TRAJ`. These are the spells most commonly found on vehicles - they are cast in caster's current facing, pitch included, and their destination must be checked against map/gameobject/creature-with-certain-typeflag geometry so that vehicle projectiles don't get launched through hills or walls etc. I imagine this is quite a heavy calculation for the server, so blizzard offloads this work to clients, and expects them to provide the correct destination, as well as projectile direction and speed, inside `CMSG_CAST_SPELL` and the like. So that is what `SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT` is used for - it forces the client to periodically cast spells and thus provide the server with necessary information about spells' projectiles.

It's used in just two cases in 3.3.5:
https://www.wowhead.com/spell=67195 - Glaive Throwers in Isle of Conquest BG
https://www.wowhead.com/spell=49714 - ???

It would be valuable to implement it at least just for the Glaive Throwers, since, you know, it's PvP, and PvP players tend to cry about any issue that unbalances their precious game mode.

**Implementation:**

SpellAuraDefines.h
```diff
-    SPELL_AURA_48 = 48,                                     // One periodic spell
+    SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT = 48,
```
SpellAuraEffects.cpp
```diff
-    &AuraEffect::HandleNULL,                                      // 48 SPELL_AURA_48 spell Napalm (area damage spell with additional delayed damage effect)
+    &AuraEffect::HandleNoImmediateEffect,                         // 48 SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT
```
Unit.h
```diff
         bool HasAuraTypeWithValue(AuraType auratype, int32 value) const;
+        bool HasAuraTypeWithTriggerSpell(AuraType auratype, uint32 triggerSpell) const;
         bool HasNegativeAuraWithInterruptFlag(uint32 flag, uint64 guid = 0);
```
Unit.cpp
```diff
     return false;
 }
 
+bool Unit::HasAuraTypeWithTriggerSpell(AuraType auratype, uint32 triggerSpell) const
+{
+    for (auto&& aura : GetAuraEffectsByType(auratype))
+        if (aura->GetSpellInfo()->Effects[aura->GetEffIndex()].TriggerSpell == triggerSpell)
+            return true;
+    return false;
+}
+
 bool Unit::HasNegativeAuraWithInterruptFlag(uint32 flag, uint64 guid)
 {
     if (!(m_interruptMask & flag))
```
(beware the range-for codestyle. also `std::any_of` could look nice)

WorldSession::HandleCastSpellOpcode (if the aura is on player)
WorldSession::HandlePetCastSpellOpcode (if the aura is on vehicle)

My code here differs too much from yours, so I won't provide a diff, but the idea is this:
- you need to allow the spell to be cast even if `Player::HasActiveSpell`/`Unit::HasSpell` check fails, but `caster->HasAuraTypeWithTriggerSpell(SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT, spellId)` succeeds
- you need to cast the spell with, let's say, `TRIGGERED_FULL_MASK` flags if the aforementioned check succeeds, since it's not a manual cast, but a triggered one

If you port #23205, the code there gives a hint on how it needs to be done.

And, of course, add the new aura type to various places where `SPELL_AURA_PERIODIC_TRIGGER_SPELL` was previously mentioned, since they work about the same way conceptually: (probably not an exhaustive list of changes)
AuraEffect::CalculatePeriodic
```diff
         case SPELL_AURA_PERIODIC_DAMAGE:
         case SPELL_AURA_PERIODIC_HEAL:
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
+        case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
         case SPELL_AURA_OBS_MOD_HEALTH:
         case SPELL_AURA_PERIODIC_ENERGIZE:
         case SPELL_AURA_PERIODIC_LEECH:
```
AuraEffect::PeriodicTick
```diff
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
             HandlePeriodicTriggerSpellAuraTick(target, caster);
             break;
+        case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
+            // Don't actually do anything - client will trigger casts of these spells by itself
+            break;
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
             HandlePeriodicTriggerSpellWithValueAuraTick(target, caster);
             break;
```
SpellInfo::_IsPositiveEffect
```diff
                 case SPELL_AURA_ADD_TARGET_TRIGGER:
                     return true;
                 case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
+                case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
                 case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
                     if (!deep)
                     {
```

**Branch(es):**

both

**TC rev. hash/commit:** 

32e1de39a26628dcb64bc21ad415afb2ad938925 (irrelevant, but hi, bot)

**Comment by Shauren** [comment]
I definitely would prefer using Player::AddTemporarySpell but not sure about vehicles here

**Comment by xvwyh** [comment]
I'd rather have the same code for both player and pet/vehicle spellcast handlers.

If you're worried about performance, that's not an issue - `HasAuraTypeWithTriggerSpell` only iterates over the list of specified aura type, which in 99.99% of the cases would be empty, hence incurring little to no performance penalty.

If you're worried about adding complexity to spellcast opcode handler - it will have to be added anyway because of another issue that I'm currently in the process of writing.

**Comment by Shauren** [comment]
Complexity of spellcast handler was what I had in mind

**Comment by xvwyh** [comment]
Check #23205 then. If you can come up with a better solution to cover both cases - you're more than welcome. But in Cata+ even more cases are added, such as raid markers, archaeology...

**Comment by Killyana** [comment]
More changes are required, the spell don't deal any damage and the visual is missing for other players``` diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index aba659b93a..71d7ae9af9 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -4504,6 +4504,14 @@ bool Unit::HasAuraTypeWithValue(AuraType auraType, int32 value) const
     return false;
 }
 
+bool Unit::HasAuraTypeWithTriggerSpell(AuraType auratype, uint32 triggerSpell) const
+{
+    for (auto&& aura : GetAuraEffectsByType(auratype))
+        if (aura->GetSpellInfo()->Effects[aura->GetEffIndex()].TriggerSpell == triggerSpell)
+            return true;
+    return false;
+}
+
 bool Unit::HasNegativeAuraWithInterruptFlag(uint32 flag, ObjectGuid guid) const
 {
     if (!(m_interruptMask & flag))
diff --git a/src/server/game/Entities/Unit/Unit.h b/src/server/game/Entities/Unit/Unit.h
index 4b45ca6af8..38166eebfe 100644
--- a/src/server/game/Entities/Unit/Unit.h
+++ b/src/server/game/Entities/Unit/Unit.h
@@ -1290,6 +1290,7 @@ class TC_GAME_API Unit : public WorldObject
         bool HasAuraTypeWithMiscvalue(AuraType auraType, int32 miscValue) const;
         bool HasAuraTypeWithAffectMask(AuraType auraType, SpellInfo const* affectedSpell) const;
         bool HasAuraTypeWithValue(AuraType auraType, int32 value) const;
+        bool HasAuraTypeWithTriggerSpell(AuraType auratype, uint32 triggerSpell) const;
         bool HasNegativeAuraWithInterruptFlag(uint32 flag, ObjectGuid guid = ObjectGuid::Empty) const;
         bool HasAuraWithMechanic(uint32 mechanicMask) const;
         bool HasStrongerAuraWithDR(SpellInfo const* auraSpellInfo, Unit* caster, bool triggered) const;
diff --git a/src/server/game/Spells/Auras/SpellAuraDefines.h b/src/server/game/Spells/Auras/SpellAuraDefines.h
index e644288229..7b9724dfa3 100644
--- a/src/server/game/Spells/Auras/SpellAuraDefines.h
+++ b/src/server/game/Spells/Auras/SpellAuraDefines.h
@@ -126,7 +126,7 @@ enum AuraType : uint32
     SPELL_AURA_TRACK_RESOURCES                              = 45,
     SPELL_AURA_46                                           = 46,   // Ignore all Gear test spells
     SPELL_AURA_MOD_PARRY_PERCENT                            = 47,
-    SPELL_AURA_48                                           = 48,   // One periodic spell
+    SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT           = 48,   // One periodic spell
     SPELL_AURA_MOD_DODGE_PERCENT                            = 49,
     SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT                  = 50,
     SPELL_AURA_MOD_BLOCK_PERCENT                            = 51,
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index fa1cfb1aeb..aa4419d676 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -108,7 +108,7 @@ pAuraEffectHandler AuraEffectHandler[TOTAL_AURAS]=
     &AuraEffect::HandleAuraTrackResources,                        // 45 SPELL_AURA_TRACK_RESOURCES
     &AuraEffect::HandleNULL,                                      // 46 SPELL_AURA_46 (used in test spells 54054 and 54058, and spell 48050) (3.0.8a)
     &AuraEffect::HandleAuraModParryPercent,                       // 47 SPELL_AURA_MOD_PARRY_PERCENT
-    &AuraEffect::HandleNULL,                                      // 48 SPELL_AURA_48 spell Napalm (area damage spell with additional delayed damage effect)
+    &AuraEffect::HandleNoImmediateEffect,                         // 48 SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT
     &AuraEffect::HandleAuraModDodgePercent,                       // 49 SPELL_AURA_MOD_DODGE_PERCENT
     &AuraEffect::HandleNoImmediateEffect,                         // 50 SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT implemented in Unit::SpellCriticalHealingBonus
     &AuraEffect::HandleAuraModBlockPercent,                       // 51 SPELL_AURA_MOD_BLOCK_PERCENT
@@ -572,6 +572,7 @@ void AuraEffect::CalculatePeriodic(Unit* caster, bool resetPeriodicTimer /*= tru
         case SPELL_AURA_PERIODIC_HEAL:
         case SPELL_AURA_OBS_MOD_HEALTH:
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
+        case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
         case SPELL_AURA_PERIODIC_ENERGIZE:
         case SPELL_AURA_PERIODIC_LEECH:
         case SPELL_AURA_PERIODIC_HEALTH_FUNNEL:
@@ -875,6 +876,9 @@ void AuraEffect::PeriodicTick(AuraApplication* aurApp, Unit* caster) const
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
             HandlePeriodicTriggerSpellAuraTick(target, caster);
             break;
+        case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
+            // Don't actually do anything - client will trigger casts of these spells by itself
+            break;
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
             HandlePeriodicTriggerSpellWithValueAuraTick(target, caster);
             break;
diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index 004eadfe98..24d1e205f8 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -3117,7 +3117,7 @@ uint32 SpellInfo::GetMaxTicks() const
                 case SPELL_AURA_PERIODIC_HEAL:
                 case SPELL_AURA_OBS_MOD_HEALTH:
                 case SPELL_AURA_OBS_MOD_POWER:
-                case SPELL_AURA_48:
+                case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
                 case SPELL_AURA_POWER_BURN:
                 case SPELL_AURA_PERIODIC_LEECH:
                 case SPELL_AURA_PERIODIC_MANA_LEECH:
@@ -3658,6 +3658,7 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             case SPELL_AURA_ADD_TARGET_TRIGGER:
                 return true;
             case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
+            case SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT:
             case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
                 if (!_isPositiveTarget(spellInfo, effIndex))
                 {
```

**Comment by xvwyh** [comment]
Yes, you missed this part:
> My code here differs too much from yours, so I won't provide a diff, but the idea is this:
>
> * you need to allow the spell to be cast even if Player::HasActiveSpell/Unit::HasSpell check fails, but caster->HasAuraTypeWithTriggerSpell(SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT, spellId) succeeds
> * you need to cast the spell with, let's say, TRIGGERED_FULL_MASK flags if the aforementioned check succeeds, since it's not a manual cast, but a triggered one
>
> If you port #23205, the code there gives a hint on how it needs to be done.

Look at the linked issue, you'll find a piece of code there that needs to be uncommented.

**Comment by xvwyh** [comment]
b3b7f0761d5605d57f9d62ca8e22a8cd9a4df24b
