### ISSUE TITLE
Core/Vehicle: Vehicle accessories must changes phase with the main vehicle

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23210]
**Description:** if a vehicle has accessories and changes phase it will not update his accessories with the new phase even if they remains installed

**Steps to reproduce the problem:**

1. .go c id 33060 
2. .mo pha 2 the vehicle
3. .mo pha 2 your char you will find the vehicle in phase 2 without the accessory
4. .mo pha 1 the vehicle
5. .mo pha 1 your char you will find the vehicle in phase 1 with the accessory installed

**Branch(es):** both

**TC rev. hash/commit:** rev. 28b502fed11a

**Comment by jackpoz** [comment]
does this happen only when using the .mo pha command or with other ways too ?

**Comment by Killyana** [comment]
It could happen if a player is controlling a vehicle then move to an area where the phase will shift for him, in this case only the vehicle will shift phase not the accessories

**Comment by Killyana** [comment]
Here a special case: https://woehead.way-of-elendil.fr/?quest=13309
The player ride an accessory of the vehicle then the vehicle starts a waypoints, if at some moment the player shit phase, only the accessory will switch phase with him, the main vehicle will remind in the old phase.
What must happen:
- If the vehicle is not controlled: all accessories must shift phase with the main vehicle
- If the vehicle is controlled by the player all accessories must shift phase with the main vehicle (the vehicle will shift phase correctly with the player)
- If only an accessory is controlled by  the player: main vehicle and other accessories must shift  phase with the player

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23646 I opened a pull request
