### ISSUE TITLE
[Crash] DealDamage

### ISSUE THREAD

**Issue by HAANAAE** [TrinityCore/TrinityCore#23211]
Description: warning: DealSpellDamage ?!

Crash log
https://gist.github.com/HAANAAE/7fe1b38db67b8f863290730ce9a50a54

Branch(es): 3.3.5
TC rev. hash/commit: b33934f
Operating system: debian

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/70fcdc687d1227a796c03f6353fc8dbfc4f4aea3
