### ISSUE TITLE
ERROR 1054 (42S22) at line 9: Unknown column 'event_param5' in 'field list'

### ISSUE THREAD

**Issue by RPG3D** [TrinityCore/TrinityCore#23224]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

worldserver stoped

**Expected behaviour:**

tell me DB is done

**Steps to reproduce the problem:**

1. clone code, compile solution
2. download and unzip sql(TDB_full_735.00_2018_02_19) to binaty dir 
3. debug worldserver(64-bit) in VS2019

**Branch(es):**
master

**TC rev. hash/commit:** 

Using configuration file D:/VSProject/TrinityCore/Build/bin/Debug/worldserver.conf.
Using SSL version: OpenSSL 1.1.0j  20 Nov 2018 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.69.0
Updating Auth database...
>> Auth database is up-to-date! Containing 12 new and 115 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 8 new and 77 archived updates.
Updating World database...
>> Applying update "2019_04_26_01_world.sql" 'D64D4ED'...
Warning: Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 9: Unknown column 'event_param5' in 'field list'

Applying of file 'D:/VSProject/TrinityCore/sql/updates/world/master/2019_04_26_01_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

**Operating system:**  Windows 10 Enterprise 64-bit

**Comment by jackpoz** [comment]
just for reference, latest working master commit is https://github.com/TrinityCore/TrinityCore/commit/920c3cbac488a0562df1ebdda6bfa52605157d4a

**Comment by jackpoz** [comment]
Keeping this issue open until it's fixed (thanks for reporting it :) )

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/91409cc77e5076e43046dc9749308afcf52f04db
