### ISSUE TITLE
DB/Loot: White Tuxedo Shirt

### ISSUE THREAD

**Issue by PolarCookie** [TrinityCore/TrinityCore#23223]
**Description:**
White Tuxedo Shirt should not drop from Redridge Mongrels.
```sql
DELETE FROM `creature_loot_template` WHERE `Entry` = 423 AND `Item` = 6833;
```

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
3e40bd19676c8a97c194e333bde44b94a3cda09b

**Comment by Aokromes** [comment]
i wonder if it's a typo.

**Comment by PolarCookie** [comment]
I assumed it was, can't git blame search for it tho

**Comment by offl** [comment]
Wowhead's addon counts loot picked up from items/gameobjects as picked up from NPCs if you target NPC while opening item/gameobject. And loot tables were parsed from wowhead, that's why multiple unique items can be found in NPCs loot tables. You also can find multiple comments about that on wowhead
