### ISSUE TITLE
[Core/Spells] Make SpellCast methods return CastResult

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#23227]
**Description:** 

We need a simple way to know if a SpellCast fail or not.
It's need to reschedule events (creature scrits) when cast fail.
In retail, normally if a spell fail, npc try cast again a sec later.
In TC, cast is skipped and will repeat in normal time instead a sec later.
Maybe needed to master too.

**TC rev. hash/commit:**  69c15f5ae769612c89346c6a308655d0987caae7

**Comment by ccrs** [comment]
dunnow if this is possible and reliable actually

**Comment by Keader** [comment]
I remember to see somewhere in sunwell, something called: CastSpellIfPossible(target, spellid, triggerFlags); that return bool i think
Or maybe a new hook?!

**Comment by ccrs** [comment]
spellhit?

**Comment by Keader** [comment]
Still seems weird a new hook only for handle with it :/

**Comment by illfated** [comment]
Thank you to @brotalnia for solving this issue so quickly. 👍
