### ISSUE TITLE
DB/Spells: Auras that have duration musn't be set on creature_addon

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23225]
**Description:** We need a DB error that check if auras used in creature_addon and creature_template_addon has a duration or not, if it's the case it must throw an error.

**Branch(es):** Both

**Comment by jackpoz** [comment]
are there already auras like that ? should we skip loading them at runtime too ?

**Comment by Killyana** [comment]
Yes, there's already some auras an even auras from players spells (dots) the wpp sometimes output this kind of auras when the creature is "created" when it has this auras.

**Comment by HelloKitty** [comment]
Why though?
