### ISSUE TITLE
[SQL] Fix wrong rotation characters when you start the game

### ISSUE THREAD

**Issue by IIushka** [TrinityCore/TrinityCore#23235]
**Description:**

Wrong rotate of the character at the start of the game

**Current behaviour:**

The character looks to the right at 90 degrees

**Expected behaviour:**

The character must look directly at the questgiver

**Branch:**

master

**TC rev. hash/commit:** 

**Solution:**

UPDATE `playercreateinfo` SET `orientation`= 0 WHERE `race`= 2 AND `class` IN (1,3,4,7,9,8,10);

**Comment by illfated** [comment]
Pro tip: you can use GitHub Flavored Markdown (https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to highlight code syntax in a code block, using formatting code. In this example, I start off with 3 back ticks followed directly by "sql" like this:  **```sql** on a blank line above the code:
```sql
UPDATE `playercreateinfo` SET` orientation`= 0 WHERE `race`= 2 AND `class` IN (1, 3, 4, 7, 8, 9, 10);
```
(and if normal text is needed after the code block, put 3 back ticks on a blank line directly after the code, before you start a new line with text.

**Comment by IIushka** [comment]
Thank you, I will use this advice!
