### ISSUE TITLE
Spell/Script: spell_gordunni_trap

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23232]
**Description:**  For this spell script: spell_gordunni_trap
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/zone_feralas.cpp#L149

The 2 gamobjects must be summoned by spells:
https://woehead.way-of-elendil.fr/?spell=11756
https://woehead.way-of-elendil.fr/?spell=19394

Quest: https://woehead.way-of-elendil.fr/?quest=2987

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 69c15f5ae769

**Comment by Keader** [comment]
i dont get it.
What is the issue?

**Comment by Killyana** [comment]
Gob summoned manually without using spells

**Comment by kuskmen** [comment]
@Killyana, check the draft PR, is this what you want it to be?

**Comment by Killyana** [comment]
Yes looks good

**Comment by illfated** [comment]
Ref. #23237
