### ISSUE TITLE
Core/Spells: Four Horseman debuffs not negative

### ISSUE THREAD

**Issue by Cobus420** [TrinityCore/TrinityCore#23248]
**Description:** 
At fight with the four horseman boss in naxxramas you can just click the debuff away given from the boss.

**Expected behaviour:**
debuffs should not be removed by right click it

**Steps to reproduce the problem:**
Go to Naxxramas and start fight with the four horseman. 
After the debuff is active right click it.

**Branch:**
3.3.5
**TC rev. hash/commit:** 
[00e98a3](https://github.com/TrinityCore/TrinityCore/commit/00e98a34c127b3308d0ef3accf7ea1a2bb999085)
(3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Comment by jackpoz** [comment]
could you include the name of the debuff and maybe the spell id ?

**Comment by Cobus420** [comment]
spell=28834/mark-of-rivendare
spell=28832/mark-of-korthazz
spell=28833/mark-of-blaumeux
spell=28835/mark-of-zeliek

**Comment by Riztazz** [comment]
```
diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index 6d45d7cf1e..69ae859e66 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -3714,6 +3714,10 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
                 if (!_isPositiveTarget(spellInfo, effIndex))
                     return false;
                 break;
+            case SPELL_AURA_DUMMY:
+                if (!_isPositiveTarget(spellInfo, effIndex))
+                    return false;
+                break;
             case SPELL_AURA_MOD_CONFUSE:
             case SPELL_AURA_MOD_ROOT:
             case SPELL_AURA_MOD_SILENCE:
```
Probably something along those lines should fix the issue? Dummy auras can be negative as well, depends on target type

**Comment by Keader** [comment]
Riztazz solution looks correct to me.

**Comment by Jildor** [comment]
I agree ;)

**Comment by Cobus420** [comment]
Testet and works

**Comment by jackpoz** [comment]
PR it so we can discuss there and keep track of the change

**Comment by Riztazz** [comment]
Feel free to PR it, i'm currently moving and will be on phone only for some time
