### ISSUE TITLE
[Core] Quest interface

### ISSUE THREAD

**Issue by IIushka** [TrinityCore/TrinityCore#23244]
**Description:**

Incorrect display of quests

**Current behaviour:**

When you click on a quest giver, the quest list is always displayed in most cases, the quest reward item is not displayed

**Expected behaviour:**

When you click on questgiver if he has one available quest should immediately open the window making the quest. Subject to availability complete the quest as well should immediately open the window of the delivery quest.
For most quests, this is broken, although it works with quests 25187, 25264, 13961, 899, 13963, 26878, 29022, 29015, 14044.
In terms of the quest must be displayed to receive a reward item.

**Branch(es):**

master

**Comment by IIushka** [comment]
Possible please specify the place in the code for modifying the logic of the call window quests

**Comment by jackpoz** [comment]
any how to reproduce steps ?

**Comment by Ovahlord** [comment]
It's actually pretty simple: just pick a questiver that has a single quest. The questgiver should show the quest details right away instead of sending the gossip with the quest list instead

**Comment by jackpoz** [comment]
I meant .go xyz , .go creature or .tele commands

**Comment by IIushka** [comment]
No, jackpoz, that's not what I meant. Thanks Ovahlord, the path is found, create a fix.

**Comment by IIushka** [comment]
I do not understand:
```c++
        QuestMenuItem const& qmi0 = questMenu.GetItem(0);
        uint32 questId = qmi0.QuestId;

        // Auto open
        if (Quest const* quest = sObjectMgr->GetQuestTemplate(questId))
        {
            if (qmi0.QuestIcon == 4)
            {
                PlayerTalkClass->SendQuestGiverRequestItems(quest, source->GetGUID(), CanRewardQuest(quest, false), true);
                return;
            }
```
Where get the value qmi0.QuestIcon come from (14690 Player.cpp) and what exactly does it mean?

**Comment by Shauren** [comment]
It comes from `Player::PrepareQuestMenu`

**Comment by IIushka** [comment]
I am already close to completing the work on the quest windows. Where it is possible to correct a behavior after the completion of the quest? The quest window should always close except in some cases.

**Comment by Faq** [comment]
still valid?

**Comment by Aokromes** [comment]
near 2 years, still no hash.
