### ISSUE TITLE
Core/Spell: Orientation changes after casting a spell in self with TARGET_UNIT_TARGET_ALLY

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23269]
**Description:**  If an creature cast a spell that have targets (21, 0) (TARGET_UNIT_TARGET_ALLY, NO_TARGET) on self it will change orientation to 0 But it will not be visible to the client until the unit is reloaded (leave the area and come back), Even if .gps shows 0 as orientation, you can test with the spell 33482.

**Steps to reproduce the problem:**
1. .go c 66839
2. .gps and notice the orientation
3. .cast self 33482
4. .gps and notice the orientation changed to 0 even if visually it's still the same
5. .tele test   and   .rec
6. Notice the npc changed the orientation visually

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. cf37f357df5c

**Comment by Killyana** [comment]
Could also be seen in Skorn - Howling Fjord with this npcs (23663,23664,23665,23666)

**Comment by offl** [comment]
> But it will not be visible to the client until the unit is reloaded (leave the area and come back)

Maybe I didn't understood what means 'not be visible to the client' but the case below is visible without leaving the area:

Apply https://github.com/TrinityCore/TrinityCore/issues/18653#issuecomment-629174231 (if not yet applied)
.go c id 23316
.q a 11061
.q c 11061
turn in the quest
Creature will cast on you the spell  41109 Periodic - Summon Torkus Jr and will change the orientation

<details>

```text
ID - 41109 Periodic - Summon Torkus Jr.
=================================================
Description: Trigger that causes the player to summon Torkus Jr.
Category = 0, SpellIconID = 2158, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000180 (SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
AttributesEx1: 0x10000400 (SPELL_ATTR1_NO_THREAT, SPELL_ATTR1_DONT_DISPLAY_IN_AURA_BAR)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 3) "Twenty yards":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 20, MaxRangeFriendly = 20

CastingTime (Id 1) = 0,00
Duration: ID (36)  1000, 0, 1000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 1000
   Trigger spell (41108) Summon Torkus Jr.. Chance = 101
   Description: Summons Torkus Jr. near his father.

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```

</details>

**Comment by Mesielecat** [comment]
The issue is in this place:

`    // if the spell allows the creature to turn while casting, then adjust server-side orientation to face the target now
    // client-side orientation is handled by the client itself, as the cast target is targeted due to Creature::FocusTarget
    if (m_caster->GetTypeId() == TYPEID_UNIT && !m_caster->HasUnitFlag(UNIT_FLAG_PLAYER_CONTROLLED))
        if (!m_spellInfo->HasAttribute(SPELL_ATTR5_DONT_TURN_DURING_CAST))
            if (WorldObject* objTarget = m_targets.GetObjectTarget())
                m_caster->SetInFront(objTarget);`

if the target is the same as the caster the orientation result gonna be 0, happens with all spell where the caster and the target gonna be the same, example TARGET_UNIT_TARGET_ALLY or TARGET_UNIT_CASTER, how to fix it is check that the caster is not the same as the target, I can´t do a pr sorry don´t have time

**Comment by offl** [comment]
39a436bd658790d39d3cfa64e18f49544475dfe3
