### ISSUE TITLE
DB/Quest: Rite of Vision (Part 3) (Improvements)

### ISSUE THREAD

**Issue by ZenoX92** [TrinityCore/TrinityCore#23266]
**Description:**

* Remove a wrong text from The Plains Vision
(This line "%s beings to draw energy from the earth" / Broadcast Text ID: 944 is not said by The Plains Vision... and considering the misspelling and the absent period, I'd say this line was never said by any NPC.)
* Add emotes and sound for The Plains Vision's right texts
* Seer Wiserunner should say his line the fist time you meet him (LOS), not when you take his quest.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 59682bbd9b33 2019-02-09 21:06:09 +0100 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  335.64

**Operating system:** Windows 7

**Suggested Fix:**
```sql
-- The Plains Vision
DELETE FROM `creature_text` WHERE `CreatureID`=2983 AND `GroupID`=0; -- Remove wrong text
UPDATE `creature_text` SET `Emote`=393, `Sound`=1018 WHERE `CreatureID`=2983 AND `GroupID` IN (1,2);

DELETE FROM `smart_scripts` WHERE `entryorguid`=298301 AND `source_type`=9 AND `id`=1; -- Remove wrong text
UPDATE `smart_scripts` SET `event_param1`=1000, `event_param2`=1000 WHERE `entryorguid`=298301 AND `source_type`=9 AND `id`=2; -- Adjust timings
UPDATE `smart_scripts` SET `action_param1`=5000, `comment`="The Plains Vision - On Waypoint 49 Reached - Despawn In 5000 ms" WHERE `entryorguid`=2983 AND `source_type`=0 AND `id`=3; -- Increase despawn time

-- Seer Wiserunner
DELETE FROM `smart_scripts` WHERE `entryorguid`=2984 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2984,0,0,0,10,0,100,0,1,5,30000,30000,1,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Seer Wiserunner - OOC LOS - Say Line 0");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry`=2984;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(22,1,2984,0,0,28,0,772,0,0,0,0,0,"","SAI triggers only if player has quest 'Rite of Vision (Part 3)' completed");

**Comment by offl** [comment]
There's two emotes at start https://youtu.be/PwXFuLB6XKI?t=47

**Comment by Wyrserth** [comment]
> Seer Wiserunner should say his line the fist time you meet him (LOS), not when you take his quest.

Are you sure about this? [Here](https://youtu.be/PwXFuLB6XKI?t=298) he says the line when the quest is accepted, and the wolf is already despawned by then.

**Comment by ZenoX92** [comment]
Here there's only 1 emote at start, and Seer Wiserunner talks before taking his quest:
https://www.youtube.com/watch?v=O_5gRE8vy0k&index=1&list=PLF5A2ABB39D69E22C

Check the third or the forth video. Sorry I can't tell you the exact video, but where I am right now I can't access Youtube. I will try to do so later.

And, by the way, it was you @offl who gave me this link.

**Comment by Wyrserth** [comment]
Nice, the case in the first video must have been a coincidence then. Sorry!

[Here](https://youtu.be/ykANBAUjB4E?list=PLF5A2ABB39D69E22C&t=217)'s the related part in the other video.

**Comment by ZenoX92** [comment]
It's the third video (Part 2) at 3:42.

**Comment by ZenoX92** [comment]
@Wyrserth Or maybe you video was from a private server using TrinityCore source and DB... :p

**Comment by offl** [comment]
Seems your're right:
http://photos1.blogger.com/blogger/5764/2363/1600/WoWScrnShot_022706_115455.jpg
Source: http://tibslilsis.blogspot.com/
