### ISSUE TITLE
Core/Condition: CONDITION_NEAR_GAMEOBJECT

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23262]
**Description:** CONDITION_NEAR_GAMEOBJECT mustn't return true if the gob is despawned and using negative respawntime in the DB.

``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 17 AND `SourceEntry` = 36532;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ErrorTextId`, `ScriptName`, `Comment`, `NegativeCondition`) VALUES
(17, 0, 36532, 0, 30, 0, 184713, 30, 0, 0, '', "'Bladespire Clan Banner'", 1);
```
**Steps to reproduce the problem:**

1. Use the sql above
2. .go game 28288
3. .add 30416
4. try to use the item

It will tell you: "you cannot do that now" as it consider the gob 184713 spawned.
The gob id=184713 is spawned with negative respawn time and respawned via the item 28288 as part of the quest event.
A second player musn't be able to use the item if the gob is spawned to avoid 2 event running at the same time (many quests use this concept)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. b76bcc836cb1

**Comment by illfated** [comment]
Is this one of the problems making it difficult to start implementing CTF PvP in Zangarmarsh?

**Comment by Killyana** [comment]
No

**Comment by Aokromes** [comment]
unless something broke it, it was working long time ago.

**Comment by illfated** [comment]
Sorry, I was unclear about the CTF quest NPC part of PvP in my previous comment. I meant to refer to the quest NPCs who hand out CTF flags as PvP quests, not the ordinary PvP area functionality.
