### ISSUE TITLE
Creature/Movement: Orientation changes wrongly and not updated in client side

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23272]
**Description:** When a npc use a waypoints via SAI then it pause in some points, orientation will change to the opposite without being updated visually in client side.
Example : Npc: 16708
He has a waypoint: 16708 that start via SAI and stops in 2 spots to execute some cosmetics:
Dekin - ON Waypoint 6 Reached - Run Script
Dekin - ON Waypoint 12 Reached - Run Script

When the npc reach point 6 the orientation is 5.179513 but upon paused it changes to 1.985356

When the npc reach point 12 the orientation is : Orientation: 4.167312 but upon paused it changes to 0.886503

If you move from the creature until it disappear then come back the orientation will get updated for the client

**Steps to reproduce the problem:**

1. .go c id 16708 
2. wait until the npc stops in one oh the 2 spots
3. .gps the npc and compare the orientation

Orientation not updated in client side
![image](https://user-images.githubusercontent.com/6587064/57585207-1f1f7980-74e5-11e9-8c66-fde4c279491d.png)

Orientation updated in client side
![image](https://user-images.githubusercontent.com/6587064/57585188-dff12880-74e4-11e9-9d64-bea446e1169e.png)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. cf37f357df5c

**Comment by Wyrserth** [comment]
I have isolated the issue to this line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/Spline/MoveSpline.cpp#L60

For some reason it overrides a perfectly valid initialOrientation with a calculated value. I don't understand it enough to do anything meaningful about it.

**Comment by jackpoz** [comment]
maybe the spline just needs MoveSplineFlag::OrientationFixed ?

**Comment by jackpoz** [comment]
Callstack:
>	worldserver.exe!Movement::MoveSpline::ComputePosition() Line 56	C++
 	worldserver.exe!Unit::UpdateSplinePosition() Line 503	C++
 	worldserver.exe!Unit::StopMoving() Line 10175	C++
 	worldserver.exe!Unit::PauseMovement(unsigned int timer, unsigned char slot, bool forced) Line 10189	C++
 	worldserver.exe!SmartAI::PausePath(unsigned int delay, bool forced) Line 131	C++
 	worldserver.exe!SmartScript::ProcessAction(SmartScriptHolder & e, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 1407	C++
 	worldserver.exe!SmartScript::ProcessTimedAction(SmartScriptHolder & e, const unsigned int & min, const unsigned int & max, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 2329	C++
 	worldserver.exe!SmartScript::ProcessEvent(SmartScriptHolder & e, Unit * unit, unsigned int var0, unsigned int var1, bool bvar, const SpellInfo * spell, GameObject * gob) Line 2832	C++
 	worldserver.exe!SmartScript::UpdateTimer(SmartScriptHolder & e, const unsigned int diff) Line 3490	C++
 	worldserver.exe!SmartScript::OnUpdate(const unsigned int diff) Line 3612	C++
 	worldserver.exe!SmartAI::UpdateAI(unsigned int diff) Line 288	C++
 	worldserver.exe!Unit::AIUpdateTick(unsigned int diff) Line 9400	C++
 	worldserver.exe!Creature::Update(unsigned int diff) Line 806	C++

Orientation before: 3.97957897
Orientation after: 0.886502862
MoveSpline info:

 | Name | Value | Type |
 | --- | --- | --- |
 | spline | {lengths={ size=3 } } | Movement::Spline<int> |
 | facing | {f={x=-107374176. y=-107374176. z=-107374176. } target=14757395258967641292  angle=-107374176. } | Movement::FacingInfo |
 | m_Id | 1933 | unsigned int |
 | splineflags | {animId=0 '\0' done=false falling=false ...} | Movement::MoveSplineFlag |
 | time_passed | 0 | int |
 | vertical_acceleration | 0.000000000 | float |
 | initialOrientation | 3.97957897 | float |
 | effect_start_time | 0 | int |
 | point_Idx | 1 | int |
 | point_Idx_offset | 0 | int |
 | onTransport | false | bool |

MoveSpline.ToString():
>MoveSpline
spline Id: 1933
flags:  CanSwim
time passed: 0
total  time: 3074
spline point Id: 1
path  point  Id: 0
mode: Linear
points count: 4
point 0 : (-3750.37, -11377, -137.516)
point 1 : (-3751.04, -11377.7, -137.516)
point 2 : (-3746.39, -11372, -135.298)
point 3 : (-3746.39, -11372, -135.298)

**Comment by jackpoz** [comment]
>it seems if a path is paused before it starts, the orientation gets modified.
to me the orientation shouldn't be modified if the spline didn't start yet

>npc reaches waypoint 6, the action list (that will pause the path) is scheduled, the waypoint logic continues and starts next waypoint. on next world update the action list pauses the new path that has 0 ms time passed but it still counts as started
so the orientation is the same as if you were running for a race on the starting block
ready, steady, wait 25 seconds, go

@ccrs any suggestion about this ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/23986
