### ISSUE TITLE
Requesting support for Fedora 29

### ISSUE THREAD

**Issue by maramound** [TrinityCore/TrinityCore#23275]
**Description:**
Requesting support be added for Fedora server 29 with MySQL 8.0.

**Current behaviour:**
Works great on Fedora server 27 with MySQL 5.7. Wiped hard drive and upgraded to Fedora server 29 with MySQL 8.0. Getting a whole bunch of errors during the make process. No errors during cmake. 

**Steps to reproduce the problem:**
1. Install Fedora server 29 and MySQL 8.0.
2. Follow the instructions found here - https://trinitycore.atlassian.net

See cmake and make output files attached.
[make.txt](https://github.com/TrinityCore/TrinityCore/files/3170917/make.txt)
[cmake.txt](https://github.com/TrinityCore/TrinityCore/files/3170918/cmake.txt)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
10176106af

**Operating system:**
Fedora server 29

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22188
