### ISSUE TITLE
Core/Creature: Evade is called when a creature is summoned

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23270]
**Description:** When a creature is summoned by a spell: https://woehead.way-of-elendil.fr/?spell=32723 It looks like an evade is called.

``` sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (18706);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (18706) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(18706, 0, 0, 0, 7, 0, 100, 0, 1, 0, 0, 0, 41, 5000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Bonechewer Riding Wolf - On evade - Despawn"),
(18706, 0, 1, 0, 0, 0, 100, 0, 1000, 2000, 15000, 17000, 11, 3149, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Bonechewer Riding Wolf - IC - cast spell Furious Howl"),
(18706, 0, 2, 0, 0, 0, 100, 0, 3000, 4000, 4000, 7000, 11, 16460, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Bonechewer Riding Wolf - IC - cast spell Festering Bite"),
(18706, 0, 3, 0, 54, 0, 100, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 20, 0, 0, 0, 0, 0, 0, "Bonechewer Riding Wolf - On just summoned - attack");
```
**Steps to reproduce the problem:**

1. Use the sql above
2. .cast 32723
3.  Notice the npc despawns after 5secs as set in the SAI

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. cf37f35

**Comment by Wyrserth** [comment]
I've noticed that minions/guardians call (all summoned by spells) evade on spawn and that evade code has the motionmaster logic that makes it follow the summoner. Maybe they should be decoupled so evade and reset aren't called on spawn.

**Comment by jackpoz** [comment]
Isn't there an evade reason parameter ?

**Comment by Killyana** [comment]
On SAI no reason parameter.

**Comment by jackpoz** [comment]
so maybe SAI should be modified to skip calling evade on summon ?

**Comment by Killyana** [comment]
Yes, for SAI we don't  need it to be triggered for the event just summoned.

**Comment by malcrom** [comment]
Need fix

**Comment by Killyana** [comment]
It happen also with summon type 8 TEMPSUMMON_MANUAL_DESPAWN
https://github.com/TrinityCore/TrinityCore/issues/7501#issuecomment-500205525

**Comment by jackpoz** [comment]
this happens since 2009 https://github.com/TrinityCore/TrinityCore/commit/df4e8b456becd90ca839b8f64fbe326042aaabd9#diff-6e2ad27531ee8eb7bafce8a41909816aR6426

**Comment by jackpoz** [comment]
>I might add a new evade reason and add 2 new parameters to the SAI event: IncludeReasons and ExcludeReasons
so in your case you could set IncludeReasons to 0 and ExcludeReasons to SpawnEvade
it will be a mask
and all current scripts will have both 0 and that will be handled as "no filter"

**Comment by jackpoz** [comment]
I created a Pull Request totally untested https://github.com/TrinityCore/TrinityCore/pull/23441

**Comment by jackpoz** [comment]
I created another Pull Request https://github.com/TrinityCore/TrinityCore/pull/23468
