### ISSUE TITLE
classic on trinitycore

### ISSUE THREAD

**Issue by loonbg** [TrinityCore/TrinityCore#23288]
hey did some one try to run classic beta on trinity and will it future work on it?

**Comment by Ovahlord** [comment]
Most likely no.
Trinity never supported classic and probably never will just because it would require to downgrade literally every single feature of the core and partially even remove them.

**Comment by funjoker** [comment]
Classic is 8.0.1 with disabled features. So actually it is not that much. But since we can’t rly keep up with Master we should not invest time into classic imo

**Comment by MaxtorCoder** [comment]
As Funjoker said, won't happen.
Maybe some other developers who are interested in learning RE can do some work on it.
But then the chance of it being added to the TC Repo is 0.

**Comment by Killyana** [comment]
You can talk about this in the forum.
