### ISSUE TITLE
Spell: Information about spells without cooldown

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23287]
**Description:** We need information about the Cool-down for this 2 spells:
https://woehead.way-of-elendil.fr/?spell=37918
https://woehead.way-of-elendil.fr/?spell=37919

Also if you find any other spell used by a vehicle or a controlled unit that doesn't have a cool-down you can report it here

**Steps to reproduce the problem:**

1. Take the quest https://www.wowhead.com/quest=10672/frankly-it-makes-no-sense
2. The 2 attack abilities doesn't have  cool-down
3. You can use this spell only against an other Arcano-Scorp controlled by an other player

Ref https://github.com/TrinityCore/TrinityCore/pull/23260

**Branch(es):** both

**TC rev. hash/commit:** rev. db53747eb8ca

**Comment by illfated** [comment]
FWIW, those spells are still available with some info on wowhead:
- https://www.wowhead.com/spell=37918/arcano-pince
- https://www.wowhead.com/spell=37919/arcano-dismantle

**Comment by Shauren** [comment]
37918 - 3 seconds
37919 - 20 seconds

**Comment by Killyana** [comment]
From where did you get this infos?

**Comment by Shauren** [comment]
Just did this quest on retail

**Comment by Killyana** [comment]
Ok,thanks
