### ISSUE TITLE
Bugs in Ulduar

### ISSUE THREAD

**Issue by aifirst** [TrinityCore/TrinityCore#23292]
**Description:**
In Ulduar, there is stuck issue after kill some bosses.

**Current behaviour:**
I did single play.
After kill Praya or Thor, dungeon is stuck in some minutes.
After some minutes, I can play game again and, stuck issue does not occur when kill other boss. 

**Steps to reproduce the problem:**
1. Do play single player
2. Kill Praya or Thorim.
3. After about a minute, dungeon will be stuck.
4. Some minutes(about 10 minutes) dungeon continues.

**Branch(es):**
3.3.5. 

**TC rev. hash/commit:** 
386b5a6f (2019/04/13)

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
update your core.
