### ISSUE TITLE
Arena personal rating

### ISSUE THREAD

**Issue by Dev-Incognito** [TrinityCore/TrinityCore#23294]
**Description:**
Arena personal rating is always reset to 0 after arena flush/worldserver crash/restart.

**Current behaviour:**
Arena personal rating is always reset to 0 after arena flush/worldserver crash/restart.

**Expected behaviour:**
Personal rating should be saved for each player in arena team.

**Steps to reproduce the problem:**

1. Create 2v2 team
2. Play 10 arenas and wait for arena flush or restart worldserver
3. Now you can cleary see that your arena team is saved, same for arena team rating, but personal rating is lost.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
Straight TrinityCore build/rev downloaded and compiled few hours ago.

**Operating system:** Win x64

**Comment by Dev-Incognito** [comment]
> 
> 
> After arena flush personal rating is reset to 0.
> 
> Last TrinityCore rev.
> 
> Win10 x64

**Comment by Dev-Incognito** [comment]
Personal rating is also reset to 0 after worldserver crash/shutdown or restart.

**Comment by illfated** [comment]
Not posting your core rev. information makes it less likely to get practical response in terms of work done towards a solution. We don't know if you are using a straight Trinity Core build or which version you are on, so I recommend that you fill in more relevant information for the TC members and fellow users to contribute whenever possible.

**Comment by Dev-Incognito** [comment]
> 
> 
> Not posting your core rev. information makes it less likely to get practical response in terms of work done towards a solution. We don't know if you are using a straight Trinity Core build or which version you are on, so I recommend that you fill in more relevant information for the TC members and fellow users to contribute whenever possible.

I'm using straight Trinity Core build of course. Downloaded and compiled few hours ago.

**Comment by MaxtorCoder** [comment]
> 
> 
> > Not posting your core rev. information makes it less likely to get practical response in terms of work done towards a solution. We don't know if you are using a straight Trinity Core build or which version you are on, so I recommend that you fill in more relevant information for the TC members and fellow users to contribute whenever possible.
> 
> I'm using straight Trinity Core build of course. Downloaded and compiled few hours ago.

How are we supposed to know that.

**Comment by Dev-Incognito** [comment]
Well, now you know all important informations i think.  Arena teams are always saved, but personal rating is lost, always. In every case.

**Comment by illfated** [comment]
@Dev-Incognito : if you could simply fill in the issue template with the factual information (and not remove almost all of it), it would be a lot better starting point to work from, towards solving your issue. Feel free to copy back information from the issue comment frame in https://github.com/TrinityCore/TrinityCore/issues/new?assignees=&labels=&template=bug_report.md&title= and edit it back in to your original comment. Thank you.

**Comment by Dev-Incognito** [comment]
Updated.

**Comment by illfated** [comment]
A bit better, but if you have access to the worldserver console, I recommend copying and pasting the information output from this command in the console:
***
TC>server debug
TrinityCore rev. a0d41c314fcc 2019-05-18 01:31:41 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0j  20 Nov 2018 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.69.0
Using MySQL version: 5.6.43
Using CMake version: 3.13.4
Compiled on: Windows 10.0.17763
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658637709 bytes
mmaps directory located in ./mmaps. Total size: 2030097204 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19051
TC>
***
(example output from my compiled core from yesterday)

**Comment by Dev-Incognito** [comment]
Branch is tracked. (335)

**Comment by illfated** [comment]
Sorry, I meant commit, not branch.

**Comment by Dev-Incognito** [comment]
I modified ''TrinityCore rev'', hash and other things, but i'm pretty sure that this issue is very old, not only few days.

**Comment by Aokromes** [comment]
1 month and still unfilled the required data, closing.
