### ISSUE TITLE
Borgoth the Bloodletter  Respawn

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23297]
**Description**:
 

Borgoth the Bloodletter cannot respawn.

**Current behaviour:**

Once the Borgoth was killed, it will not respawn anymore. The server was compiled with the latest TrinityCore (3.3.5) and there is nothing wrong in logs. I checked DB and it seems also nothing wrong with _creature_, _creature_template_ and _pool*.__

**Expected behaviour:**

cannot sure whether it is a bug.

**Steps to reproduce the problem:**

1. start the worldserver, find Borgoth the Bloodletter(**.go xyz 6279.76 -6361.43 78.1116 530** or **.go xyz 6439.69 -6643.39 107.431 530**)
2. kill it and then it will not respawn any more.
3. DB: id in _creature_template_: 16247 
guid in _creature_ :82889 and 52139
entry in _pool_template_: 380

**Branch(es):**

3.3.5

**Operating system:** CentOS7

**Comment by TheWinchesters** [comment]
Rev e4a1556e09ea38ece9a76b0d190d2b2f29bf5bb9
I can not reproduce it.

**Comment by soniczhang11** [comment]
> Rev [e4a1556](https://github.com/TrinityCore/TrinityCore/commit/e4a1556e09ea38ece9a76b0d190d2b2f29bf5bb9)
> I can not reproduce it.
> 
> Have in mind that this NPC has 2 spawn points.
> Do the same I did:
> .go c id 16247
> kill the NPC
> Wait 5 min
> Switch between .go c 82889 and .go c 52139

thx. I know it and already checked the 2 spawn points.

**Comment by TheWinchesters** [comment]
Do you have any custom change in your core?

**Comment by soniczhang11** [comment]
> Do you have any custom change in your core?

I tried to use the default world.config file, but the problem still happened. I know this mob random respawn according to the _pool_*_ table. However, other mobs have no such problem.

**Comment by Kittnz** [comment]
There is no such thing as "latest 3.3.5"

**Comment by soniczhang11** [comment]
> There is no such thing as "latest 3.3.5"

I mean the latest TrinityCore (3.3.5).

**Comment by Jinnaix** [comment]
You are ignoring the Issue template. Provide your server revision or a screenshot of .server debug.
