### ISSUE TITLE
TC core / Compile Errors

### ISSUE THREAD

**Issue by insistandinsist** [TrinityCore/TrinityCore#23291]
**Description:**

Compile errors.

**Current behaviour:**
[crash errors](https://gist.github.com/insistandinsist/7b3d902a5a1be61d9631e439fd56d988)
 

**Expected behaviour:**

Compile success

**Steps to reproduce the problem:**

locate build directory ,make

**Branch(es):**

master

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Debian 9

**Comment by Aokromes** [comment]
you are using to much resources.
clang: error: unable to execute command: Killed
