### ISSUE TITLE
Hunter Pet Life Bug

### ISSUE THREAD

**Issue by Illuminati2739** [TrinityCore/TrinityCore#23304]
Describe the bug
Hunter pets life is not calculated correctly, especially seen when buffing it and remounting.

To Reproduce

Summon Hunter Pet
Buff it with anything increasing its life ([Spiced Mammoth Treats] [Runescroll of Fortitude])
See its life rising for a huge amount.
Mount up
Mount down
See the life beeing lowered heavily
Repeat everything starting from step 2
Expected behavior
Life not going down after mounting

Branch : 3.3.5a
Revision: Todays
No custom modifications

**Comment by Aokromes** [comment]
1 month and still missing required data, closing.
