### ISSUE TITLE
Shadowflame ignores Anti Magic Shield

### ISSUE THREAD

**Issue by Illuminati2739** [TrinityCore/TrinityCore#23305]
Shadow flame is a warlock aoe spell.
With glyph it applies non magic 70% movement slow.

Issue:
The spell ignores Anti-Magic Shell (should give full immunity against spells and its effects).

How it should work:
If the warlock uses the Shadowflame spell on a dk with an active Anti-Magic Shell, It should totally ignore the dmg (infront dmg and dot aswell) and the non magic debuff aswell.

Branch 3.3.5a
Revision ; todays
No custom modifications

**Comment by Keader** [comment]
It have attribute "ignore hit result', so i think it's correct

**Comment by Aokromes** [comment]
1 month and still missing required data, closing.
