### ISSUE TITLE
Implement Resilience Cap

### ISSUE THREAD

**Issue by Illuminati2739** [TrinityCore/TrinityCore#23303]
I beleive that Resilience doesnt work as intended and needs to have a cap . Trinitycore already has Stats Limit implementation and I think Resilience should be part of it. A player using full Season 8, socket the Max +20 Res gems in every slot, pass 1500 total Reselience and your dmg reduction would be insane. 

Some players stacking resilience makes them 100% immune to crits and dmg reduction is over the roof makes any class simply unkillable.

Make any class/race , put on Season 8. Socket +20 res gems in every socket and see your dmg reduction.

Branch: 3.3.5a
Using todays revision.
No custom modifications.

**Comment by Aokromes** [comment]
1 month and still missing required data, closing.
