### ISSUE TITLE
[BG] Go Inside the ground !

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#23302]
Description: in warsong gulch / class warrior + mage
if  use spells , Charge +  Blink , player Inside the Ground ! ! !

mmaps: enable !

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/74678b247e04728562e78f6a624577964020a7f0
System: windows server

**Comment by Killyana** [comment]
Dup

**Comment by Hir0shi** [comment]
update data ?!

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21255

**Comment by Hir0shi** [comment]
@Killyana

this program has been fixed?

Which version?
