### ISSUE TITLE
Creature/Script: npc_air_force_bots

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23307]
**Description:** The script npc_air_force_bots spawn a guard even if the player is friendly to the area.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/npcs_special.cpp#L180-L186

**Steps to reproduce the problem:**

1. .go c 76812 (with a horde char=
2. notice a guard will spawn
3. kill this guar an another one will spawn

**Branch(es):** both

**TC rev. hash/commit:**  rev. 534348797f65

**Comment by illfated** [comment]
OK, so a faction check is needed in that script, I guess.

**Comment by jackpoz** [comment]
maybe caused by https://github.com/TrinityCore/TrinityCore/commit/fe25ce4fa3ce306beebc4c95b22cd14052a92566#diff-4676c91d4efed96f267ad2efac824e5dL182 ?
