### ISSUE TITLE
[BG] Go Inside the ground !  fixed?

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#23308]
Description: in warsong gulch / class warrior + mage
if use spells , Charge + Blink , player Inside the Ground ! ! !
mmaps: enable ! WTF

Branch(es): 3.3.5
System: windows server

@Killyana

this program has been fixed?
Which version? i will to update core?
Answer one

<

my heart @jackpoz  where are u ! ! !

**Comment by Hir0shi** [comment]
@Killyana

this program has been fixed?
Which version? i will to update core?
Answer one

**Comment by MaxtorCoder** [comment]
> 
> 
> @Killyana
> 
> this program has been fixed?
> Which version? i will to update core?
> Answer one

Can you please stop? This is a duplicate issue to #21255.
You are also not following the issue template.

**Comment by Hir0shi** [comment]
@MaxtorCoder 
Ok sry / please tell me just this program is fixed? or nO !

**Comment by MaxtorCoder** [comment]
> 
> 
> @MaxtorCoder
> Ok sry / please just tell me this program is fixed? or nO !

Test it I would say.

**Comment by Hir0shi** [comment]
ok i will to tested last version TC

https://github.com/TrinityCore/TrinityCore/commit/716c14846f859e6130edb412b6a9f5793f0f959b
