### ISSUE TITLE
[3.3.5] - Health Leech absorb

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23311]
**Description:**

Spells with SPELL_EFFECT_HEALTH_LEECH, when hit the effect on target and target absorb effect, caster get heal amount ignoring damage absorbed.

https://www.mmo-champion.com/threads/658331-Death-Coil-Not-Healing

**Steps to reproduce the problem:**

1. Get a target with absorb effect (by example Power Word: Shield ID 17)
2. Cast SPELL_EFFECT_HEALTH_LEECH on target with absorb (by example Warlock Death Coil ID 6789)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

716c14846f859e6130edb412b6a9f5793f0f959b

**Comment by Jildor** [comment]
This works, but I'm not sure if is the proper fix:

```diff
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -1532,6 +1532,12 @@ void Spell::EffectHealthLeech(SpellEffIndex effIndex)
     float healMultiplier = m_spellInfo->Effects[effIndex].CalcValueMultiplier(m_originalCaster, this);
 
     m_damage += damage;
+
+    DamageInfo damageInfo(m_caster, unitTarget, damage, m_spellInfo, m_spellInfo->GetSchoolMask(), SPELL_DIRECT_DAMAGE, BASE_ATTACK);
+    m_caster->CalcAbsorbResist(damageInfo);
+    uint32 absorb = damageInfo.GetAbsorb();
+    damage -= absorb;
+
     // get max possible damage, don't count overkill for heal
     uint32 healthGain = uint32(-unitTarget->GetHealthGain(-damage) * healMultiplier);
```

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ad89472fe3512b4a5f4160240154fd5b11a3b07c
