### ISSUE TITLE
[3.3.5] ICC: Sanctification marks loot

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23310]
**Description:**
There is a reference_loot_template entry that holds all the Sanctification marks for ICC (normal and epic ones)

**Current behaviour:**
The entry 34279 has 6 items where Chance for each one is:
52025 - Chance 40
52026 - Chance 0
52027 - Chance 0
52028 - Chance 40
52029 - Chance 0
52030 - Chance 0

If I understand correctly, If there are 2 items with chance 40, then the remaining chance (20) is divided by the 4 items with chance 0.
I have killed bosses in ICC several times and it looks like they drop the same marks almost every time.
Should it be more equality for each mark? Or is this right?

**Branch(es):** 3.3.5
**TC rev. hash/commit:** e4a1556e09ea38ece9a76b0d190d2b2f29bf5bb9
**Operating system:** Windows 8.1

**Comment by illfated** [comment]
It has been a long time since I knew how the loot tables work when `reference_loot_table` is used. Did you get any of the items with drop chance 0 in your loot so far?

BTW, those items are listed with different drop rates on woehead and db.rising-gods.de , not sure what to make of that.
```sql
SELECT * FROM `reference_loot_template` WHERE `Item` IN (52025,52026,52027,52028,52029,52030) ORDER BY `Entry`,`Item`;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
34278   52025          0      40              0         1        1         1         1  (NULL)
34278   52026          0       0              0         1        1         1         1  (NULL)
34278   52027          0       0              0         1        1         1         1  (NULL)
34279   52025          0      40              0         1        1         1         1  (NULL)
34279   52026          0       0              0         1        1         1         1  (NULL)
34279   52027          0       0              0         1        1         1         1  (NULL)
34279   52028          0      40              0         1        1         1         1  (NULL)
34279   52029          0       0              0         1        1         1         1  (NULL)
34279   52030          0       0              0         1        1         1         1  (NULL)
```
```sql
SELECT * FROM `creature_loot_template` WHERE `Reference` IN (34278,34279) ORDER BY `Entry`,`Reference`;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
38265       2      34278     100              0         1        0         1         2  (NULL)
38266       2      34278     100              0         1        0         1         1  (NULL)
38267       2      34279     100              0         1        0         1         3  (NULL)
38431       1      34278     100              0         1        0         1         2  (NULL)
38434       2      34278     100              0         1        0         1         2  (NULL)
38435       2      34278     100              0         1        0         1         1  (NULL)
38436       2      34279     100              0         1        0         1         2  (NULL)
38585       2      34278     100              0         1        0         1         1  (NULL)
38586       1      34279     100              0         1        0         1         2  (NULL)
39166       2      34278     100              0         1        0         1         2  (NULL)
39167       2      34278     100              0         1        0         1         1  (NULL)
39168       2      34279     100              0         1        0         1         2  (NULL)
```

**Comment by TheWinchesters** [comment]
illfated:
"Did you get any of the items with drop chance 0 in your loot so far?"
Yes, but the chance is really low.

db.rising-gods.de uses aowow and that project uses your world database.
So, results may depend of what you have in the database of your server.
I use it and I have the same chance that the first select in your comment for entries 34278 and 34279
When it comes to entry 34278, you can see in the website 40 30 30
But, when it comes to entry 34279, you can see 40 5 5 40 5 5 and that is why I suppose that the remaining 20 is divided by the amount of items with chance 0, giving as result a high chance only for 2 Sanctification marks.

I may think that a temp solution would be changing those 40 in entry 34279 for 20.
It is like replicate entry 34278 but in this case, the chance is considered for 6 items.

**Comment by Wyrserth** [comment]
Reference 34278 contains all normal 25-man marks, but reference 34279 contained both normal and heroic ones. That made no sense, so I removed normal tokens fro 34279 and assigned 34278 to the end-wing bosses.
