### ISSUE TITLE
Paladins's Seal of Command 

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23315]
**Description:** 

Seal of Command cannot hit additional targets as description.

**Current behaviour:**

When a paladin activate the Seal of Command, his meele attack cannot hit another 2 additional targets as the description of the spell.
**Expected behaviour:**

fix the Seal of Command as description

**Steps to reproduce the problem:**

1. Create a Paladin, and levelup, then .learn all my class
2. Activate the Seal of Command.
3. Aggro two or more mobs to hit, and then observe the combat log. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ba20ca75f87ce8dc2896d6de73cfb712fa1481d2

**Operating system:** CentOS 7.6

**Comment by Killyana** [comment]
It works as intended for me.
rev. 3731c4be9586
