### ISSUE TITLE
Creautre: Spawns not triggring cast on reset when the server starts

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23313]
**Description:** This 4 spawns are supposed to cast a channel spell on reset: 70851,70850,70852,70853 but when the server starts they will cast nothing, if they reset after an evade or after a respawn they will cast the spell.
https://github.com/TrinityCore/TrinityCore/commit/1e1d626da0e0dd8263ea3e1d7e7890074be7335c#diff-f03226341e39cde789855d5e98d60eb0R11
The issue is not related to the creature but to this specific spawns, you can update the entry but the issue will remains:
``` sql
UPDATE creature SET id=22017 WHERE guid=70850;
```
Also the issue is not related to the reset event, if I change the action to something  else like morph or say text it works correctly.

You can move the npc and restarts the server and the issue will remains.

If you .go 70850 and .npc add 19796 then restart the server the new spawn will cast the spell.

I found nothing on creature_addon or other tables that could explain the issue.

**Steps to reproduce the problem:**

1. .go c 70850
2. notice the npc is not channeling the spell
3. .die .resp the npc an it will cast the spell on respawn

I tested on 4.3.4 and the issue is not happening.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e06521a9b550

**Comment by Shauren** [comment]
This is probably related to creature loading order

**Comment by Killyana** [comment]
Unlikely, as other spawns doesn't have this issue.

**Comment by r00ty-tc** [comment]
Isn't this the age old channel bug? I did make a "fix" for it, but it didn't match sniffs we had. So I never merged it.
Essentially you see the channel, because you were "in range" when they started channelling. You can test this by having two clients in. One in the area, one way way away. Spawn the dude, and observe player 1 sees the channel. Move player 2 into range and they don't see the channel.
If that's the result it's the same bug.
https://github.com/r00ty-tc/TrinityCore/commits/spell_test is the branch I was messing with the stuff in.

**Comment by Killyana** [comment]
Yes this issue happen for this spell also, but you will still be able to see effect on the caster, and list aura will show the spellid
![Annotation 2019-05-24 232613](https://user-images.githubusercontent.com/6587064/58357689-10897880-7e7c-11e9-81b1-ee0073dcdbbe.jpg)

**Comment by Killyana** [comment]
This happen if the target has a higher guid than the caster, the cast will fail as the target is added to the map after the caster witch will not find any target at the moment of the cast, maybe we need to delay any AI action by 1 sec until other spawns are added to the map.

**Comment by malcrom** [comment]
I usually set cast spell OOC no repeat with a 1 sec delay this gives time for spawning.
