### ISSUE TITLE
[3.3.5/Core]Warrior cannot charge in water

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23326]
**Description:**

Warrior cannot charget in water.

**Current behaviour:**
When warrior try to cast charge in water, notice said that it cannot find a path.
**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Create a Warrior and levelup.
2. Swim in water and try to find some mobs.
3. Try to cast charge to those mobs.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

16bf11ab20fcd5e3984dd90d011d13f56288d1ea

**Operating system:** CentOS

**Comment by Killyana** [comment]
Probably related https://github.com/TrinityCore/TrinityCore/issues/22253

**Comment by jackpoz** [comment]
please provide a clear example with .go xyz coordinates to reproduce the issue

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24010
