### ISSUE TITLE
[3.3.5] Client freeze on Valithria Dreamwalker.

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23320]
**Description:**
Client freezes if, during the Valithria Dreamwalker encounter, a mage enters portals, flies and use Ice Block.
The mage will continue as usual (as everyone who is inside the portal) but this affects to those ones who did not enter the portals.

**Steps to reproduce the problem:** 
1. Use 2 chars (one must be a mage with Ice block)
2. .go c id 36789
3. .inst setb 0 3 (up to boss 9)
4. Start the encounter
5. When portals spawn, use the mage and enter (only the mage)
6. Once inside, use Ice Block
7. Switch to the char that did not enter the portals and it will be frozen

**Branch(es):** 3.3.5

**TC rev. hash/commit:** f1ab05ab46a559f99bf5c086228eb011dff10f02

**Operating system:** Win 8.1

**Comment by TheWinchesters** [comment]
Someone taught me about sniff and this is from the client that freezes:
https://gist.github.com/TheWinchesters/21b8e1a40cfb76c6c3cadcb82a89d596

**Comment by Shauren** [comment]
```
ServerToClient: MSG_MOVE_SET_FLIGHT_SPEED (0x037E) Length: 52 ConnIdx: 0 Time: 05/27/2019 12:20:17.735 Number: 2606
GUID: Full: 0x00000004 Type: Player Low: 4
Movement Flags: 6144 (Root, Falling)
```

The cause

**Comment by Keader** [comment]
@Shauren any solution about this?

**Comment by Shauren** [comment]
Sniff/packet dump please

**Comment by Keader** [comment]
@Shauren 

https://gist.github.com/Keader/fcd79d4d199d429b970ab3b7428e2e13

**Comment by Keader** [comment]
@Shauren https://gist.github.com/Keader/fcd79d4d199d429b970ab3b7428e2e13

Is still about Movement Flags: 6144 (Root, Falling)

**Comment by Keader** [comment]
Any news on this @Shauren ?

**Comment by OcelotGear** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16689 seems related

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/24000

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24000
