### ISSUE TITLE
Incorrect AreaId detection

### ISSUE THREAD

**Issue by ForesterDev** [TrinityCore/TrinityCore#23327]
**Description:**

In some places area detection is not correct.

**Steps to reproduce the problem:**

1. .cast self 70860
2. .cast self 72546
3. .gps

You will see message "no VMAP available for area info", in logs there is a message "
VMap file './vmaps/631.vmtree' does not exist
Please place VMAP files (*.vmtree and *.vmtile) in the vmap directory (./vmaps/)
, or correct the DataDir setting in your worldserver.conf file." (but this file exists), 

and Area: 4859. 

But in this place should be area 4910 (Frostmourne)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

64dabaad8007f632388f6147a24cacd453a365fc

**Operating system:** 
Windows 7

**Comment by Killyana** [comment]
gps:
no VMAP available for area info
Map: 631 (Citadelle de la Couronne de glace) Zone: 4812 (Citadelle de la Couronne de glace) Area: 4859 (Le Trône de glace) Phase: 4294967295
X: 504.714081 Y: -2523.488281 Z: 1049.864990 Orientation: 3.663447
grid[32,27]cell[7,2] InstanceID: 59
 ZoneX: 72.870117 ZoneY: 66.745323
GroundZ: 0.000000 FloorZ: 1049.864990 Have height data (Map: 1 VMap: 0 MMap: 1)
Server log:
VMap file './vmaps/631.vmtree' does not exist
Please place VMAP files (*.vmtree and *.vmtile) in the vmap directory (./vmaps/), or correct the DataDir setting in your worldserver.conf file.

Maybe for this reason we have this under map issue with the platform disappearing https://github.com/TrinityCore/TrinityCore/issues/16328

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/0468c70dfe91794ad272594323dd7feb611d0a93
