### ISSUE TITLE
Command: wpgps must output the orientation

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23330]
**Description:** This is the actual query from .wgps
``` sql
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`, `delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
```
As we added the orientation in waypoint_data the command must also output this field.

**Branch(es):** both
**TC rev. hash/commit:**  rev. 16bf11ab20fc

**Comment by Aokromes** [comment]
i supose it's add another field here.

        TC_LOG_INFO("sql.dev", "(@PATH, XX, %.3f, %.3f, %.5f, 0, 0, 0, 100, 0),", player->GetPositionX(), player->GetPositionY(), player->GetPositionZ());
