### ISSUE TITLE
Boss/Script: Volkhan

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23337]
**Description:** The boss no longer trigger the event  EVENT_SHATTERING_STOMP, this event must be triggered upon a golem transformed into a Brittle Golem, probably a check must also be done by the boss every x secs and if it finds a Brittle Golem it trigger the event.
The achievement in this encounter is about not killing more than 4 golems (transforming it into a Brittle Golem) 
A golem explode when the boss cast Shattering Stomp.
https://www.wowhead.com/achievement=2042/shatter-resistant

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 2d5387ea425f

**Comment by Killyana** [comment]
Or maybe I'm wrong about when Shattering Stomp must be cast, I cannot find a proper source.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14111 broken the Shattering Stomp cast

**Comment by jackpoz** [comment]
ty :)
