### ISSUE TITLE
[3.3.5] Honor Hold event

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23348]
**Description:**
Honor hold has an hourly event, implemented here https://github.com/TrinityCore/TrinityCore/pull/21110/files

**Current behaviour:**
The entire event duplicates for every player in the area.

For better explanation, I have added some images, but text is in Spanish so I'll explain:
Watch Commander Leonus should yell once every hour, when the event starts.
In the images, is possible to see how many times Watch Commander Leonus (Comandante de Vigilancia Leonus) yells in the same minute, and the amount of rocks in the air.
For this test, I connected/disconnected a few chars in the area and left 3 online.

https://ibb.co/w0gQv3P
https://ibb.co/kB4K7Tf
https://ibb.co/6s0qcqV

The consequences are, depending of the amount of players:
- Everytime the event starts, everything happens repeatedly
- Nobody can walk through the zone because of the amount of rocks (fps drops to 1)
- High Update time diff

**Steps to reproduce the problem:**
1. .tele honorhold
2. Wait till the event starts and after some minutes connect more and more players in the area
3. Wait till the event starts again

* worldserver config is using default values
GridUnload = 1

**Branch(es):** 3.3.5
**TC rev. hash/commit:** b64583b7c14da408b34d2c92a02e5529594ef181 (It can be seen in one of the images)
**Operating system:** Win 8.1

**Comment by Aokromes** [comment]
i think it's the same as https://github.com/TrinityCore/TrinityCore/issues/19072

**Comment by Kittnz** [comment]
If the event starts and grid pauses it, and it gets started several times, you get this issue i guess.

**Comment by Riztazz** [comment]
Are you resetting everything else as well? when commander resets

**Comment by jackpoz** [comment]
shouldn't _events.Reset() cancel every previous event ? the behavior here seems to be like events get duplicated

**Comment by Riztazz** [comment]
Well yeah but when event fires - it will set data on bunch of other triggers that do have EventMap of their own, and their .Reset() is never called for those so they have bunch of duplicated events in their map

**Comment by Kittnz** [comment]
Correct, the event reset isn't called.

**Comment by jackpoz** [comment]
btw @Kittnz , do you have time to fix this issue :) ?

**Comment by TheWinchesters** [comment]
Not sure if relevant:
I replied the problem in the TC test realm and right after that, I posted this issue.
I disconnected all the chars and hours later, the event behaves normally.

**Comment by Kittnz** [comment]
@Treeston thanks!
