### ISSUE TITLE
["patch" SmartAI Lab scripts] huge repo pack scripts project for help

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#23347]
**Description:**

you can use and check my repo with a lot of SAI

**Current behaviour:**

I can improve your SAI pack

**Expected behaviour:**

You can use all of my work there https://github.com/cooler-SAI/patch-Lab

**TC rev. hash/commit:** 

[master] branch  https://github.com/TrinityCore/TrinityCore/commit/9685c9346dfe06ad1d248ff4e128e0d0b8dbfcea

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17004
