### ISSUE TITLE
[3.3.5] Lavinia Crowe greeting

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23350]
**Description:**
Lavinia Crowe 'Enchanting Trainer' (NPC 4616) has, as a greeting: "Greetings! Can I teach you how to cut precious gems and craft jewelry"

**Expected behaviour:**
Lavinia Crowe should have the greeting for Enchanting profession

**Branch(es):** 3.3.5
**TC rev. hash/commit:** b64583b7c14da408b34d2c92a02e5529594ef181
**Operating system:** Win 8.1

**Comment by Killyana** [comment]
Many others have the wrong text
``` sql
UPDATE `trainer` SET `Greeting`="Enchanting is the art of improving existing items through magic." `Id` IN (94, 95, 96);

**Comment by Killyana** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b9c2b7cac598548a4321673e8e3bbdd9b1f238c9
