### ISSUE TITLE
Dark Iron and Mag'har Orcs (Allied races) do not have racial and language abilitys

### ISSUE THREAD

**Issue by Nupper** [TrinityCore/TrinityCore#23359]
**Description:**

The Two New allied races in 8.0.1 do not get there basic raciels and languages 

**Current behaviour:**

![image](https://user-images.githubusercontent.com/6026902/58840720-a7b1b580-865e-11e9-9fd4-054195a27b47.png)

**Expected behaviour:**

Should have racials in spell book including language
![image](https://user-images.githubusercontent.com/6026902/58840858-3de5db80-865f-11e9-9bbb-6965f9c25cda.png)
(Image taken from Retail WoW)
**Steps to reproduce the problem:**

1. Create a Dark Iron or Mag'har  Orc

**Branch(es):**

Master

**TC rev. hash/commit:** 

CoreTeam rev. 3e25b6c587c3 2019-05-27 19:52:52 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Operating system:** Win7 Pro 64bit

**Comment by Shauren** [comment]
> CoreTeam rev. 3e25b6c587c3 

What is this?

It _probably_ is also broken on TC (because I remember db2 files for skills having wrong racemasks)

**Comment by MaxtorCoder** [comment]
Isn't CoreTeam a clone of CypherCore? A C# TC server??

**Comment by Nupper** [comment]
Racemask:
67108864 - Nightborne
134217728 - Highmountain Tauren
268435456 - Void elf
536870912 - Lightforged
1073741824 - Zandalari Troll
2147483648 - Kul'tiran
4294967296 - Thin Human
8589934592 - Dark Iron
17179869184 - Vulpera
34359738368 - Mag'har orc

Found the racemasks for the races...but skilllineability.db2 dose not use the racesmask 8.0.1+
