### ISSUE TITLE
Not Found AllowTwoSide !

### ISSUE THREAD

**Issue by Hir0shi** [TrinityCore/TrinityCore#23352]
Description: Not Found on Worldserver.cfg

AllowTwoSide.Interaction.Mail = 0

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/b64583b7c14da408b34d2c92a02e5529594ef181
Operating system: Win server 2016

**Comment by Aokromes** [comment]
https://community.trinitycore.org/topic/13962-trouble-with-your-trinity-install-starting-login-readme-1st-faqs/?tab=comments#comment-60049
