### ISSUE TITLE
Error on using compiled trinity source code on other computer

### ISSUE THREAD

**Issue by IranDeveloper** [TrinityCore/TrinityCore#23363]
**Description:**

I compiled the 3.3.5 branch successfully and got no errors. now i want to use this compiled binaries on other pc as a game server. when i run worldserver.exe i got this error :
database auth is empty. auto populating it ...
>> Base file D:/Trinity/sql/base/auth_database.sql is missing. try fix it by cloning source code again ...
In the pc im compiling the source code my source directory is on D drive and when i run compiled binary the addresses are fixed and refer to D drive.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
-

**Operating system:** Compiled on Windows 10, Use on Windows 7

**Comment by Aokromes** [comment]
not a bug.

**Comment by illfated** [comment]
The core servers cannot be moved alone to a different computer without cloning the forked source to that other computer.
I presume you are used to how repacks work, being able to move them around.
TC core needs the full git source containing the DB files in order to build the DB.
