### ISSUE TITLE
Cannot extract vmaps,maps and mmaps (master repo = 3.3.5a repo ?)

### ISSUE THREAD

**Issue by Dkocir** [TrinityCore/TrinityCore#23378]
Following your excellent guide on: [(https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977329/Windows+Core+Installation)]

It is great! Good community, many explanations for dummies, i love it!
I have successfully build 3.3.5a repository (https://github.com/TrinityCore/TrinityCore) without
any error.  
The problem is (its just a really dummy problem), when i try to extract vmaps,maps and mmaps with the exe files that i built from the Visual Studio 2017 (Git Clone branch), it says:

"MPQ files found in Data directory!
This tool works only with World of Warcraft: Legion"

Wait. Am i currently working on the Legion repo and not the 3.3.5a repo?
I recently noticed that the repository for 3.3.5a and legion is the same.
(https://github.com/TrinityCore/TrinityCore)
Am i really that dumb?

Operating system: Windows 10 64 bit

**Comment by Aokromes** [comment]
picnic.

**Comment by illfated** [comment]
@Dkocir : You need to learn a little bit more about git, repositories and branches.
Repository: https://github.com/TrinityCore/TrinityCore
- main branch: https://github.com/TrinityCore/TrinityCore/tree/master (Legion + BfA)
- 3.3.5 branch: https://github.com/TrinityCore/TrinityCore/tree/3.3.5 (Wrath of the Lich King)
