### ISSUE TITLE
DK Pet / Ghoul cooldown

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#23385]
**Describe the bug**

Sometimes ghoul (Raise Dead) cooldown will not start decreasing. You will not be able to summon your ghoul again until you actually relog. Very annoying in arena, battlegrounds, duels.

**To Reproduce**

Use Death Pact to sacrifice your ghoul during combat.
You may have Raise Dead now permanently on cooldown. (I would guess around 20% chance that it happens).

**Expected behavior**
Raise Dead cooldown should always start when your pet dies.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15172
