### ISSUE TITLE
Howling Fjord Quest: It goes to 11... (ID=11421)

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#23383]
**Describe the bug**

When approaching the Vrykul Harpoon Gun, and using the Harpoon Control Mechanism(ID=34032) simply nothing happens.Tho the cooldown on the item pops.

**To Reproduce**

Use Harpoon Control Mechanism near the Vrykul Harpoon Gun (at the northernmost harpoon building)
See that nothing happens.

**Expected behavior**
After using the item at the harpoon gun, you should be able to use it as a vehicle, and start shooting at the building and incoming dragon-riders.

**Branch(es):**
 3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

**Comment by Aokromes** [comment]
#6844
