### ISSUE TITLE
DB/Loot: Crag boar quest/cooking drop too high

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#23389]
**Description:**

https://www.wowhead.com/npc=1125/crag-boar

The main problem currently is for the quest to collect crag boar ribs -- currently these drop several at a time making the quest far easier than intended and making cooking too easy to level (the item should drop regardless of the quest).

But the rest of the table is all trash anyway, dropping lots of stuff that shouldn't, so I redid it from scratch.

**Branch(es):**

3.3.5 (likely broken on master too)

**TC rev. hash/commit:** 

6efdcd3ea8bf 

**Suggested Fix**

```sql
-- Fix drop rates, too high and too many, add jerky, remove lots of gear
-- Crag boar
DELETE FROM `creature_loot_template` WHERE `Entry`=1125;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(1125, 2886,      0,      45, 0, 1, 1, 1, 1, "Crag Boar Rib"),
(1125, 117,       0,      85, 0, 1, 0, 1, 1, "Tough Jerky"),
(1125, 769,       0,      25, 0, 1, 1, 1, 1, "Chunk of Boar Meat"),
(1125, 771,       0,      15, 0, 1, 0, 1, 1, "Chipped Boar Tusk"),
(1125, 3171,      0,      15, 0, 1, 0, 1, 1, "Broken Boar Tusk"),
(1125, 24073, 24073,     2.5, 0, 1, 2, 1, 1, "Junk gear"),
(1125, 24700, 24700,       1, 0 ,1, 2, 1, 1, "Patterns"),
(1125, 24701, 24701,       1, 0 ,1, 2, 1, 1, "Patterns"),
(1125, 11111, 11111,     0.1, 0, 1, 0, 1, 1, "Bags");

```

**Comment by Killyana** [comment]
Looks some loots are missing like Broken Boar Tusk, Chipped Boar Tusk https://classic.wowhead.com/npc=1125/crag-boar#drops:mode=
and https://classic.wowhead.com/item=2406/pattern-fine-leather-boots

**Comment by Teppic1** [comment]
I don't trust low counts from wowhead, rather on what I've seen first hand or in vids, and use wowhead's highest counts and comments as guidance. For instance it shows a unique quest item from a named Stormwind NPC dropping on a totally unrelated boar only found in Dun Morogh!  Spider legs, tough wolf meat and bear fur from a boar look suspicious as well.

There can be a problem with items that existed pre and post Cata as sometimes the drop rates dramatically change, and it's more or less impossible to know what was right, though that's usually for essentially irrelevant grey trash.

**Comment by Killyana** [comment]
Broken Boar Tusk and Chipped Boar Tusk  are from classic data

**Comment by Teppic1** [comment]
I'd already got broken boar tusk and had already added the chipped boar tusk. I think you're being exceptionally picky, do what you like /shrug.

**Comment by malcrom** [comment]
`-- Fix Loot table for Crag boar
DELETE FROM `creature_loot_template` WHERE `Entry`=1125;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(1125, 771,       0,      20, 0, 1, 0, 1, 1, "Chipped Boar Tusk"),
(1125, 3171,      0,      80, 0, 1, 0, 1, 1, "Broken Boar Tusk"),
(1125, 769,       0,      60, 0, 1, 1, 1, 1, "Chunk of Boar Meat"),
(1125, 2886,      0,      60, 0, 1, 2, 1, 1, "Crag Boar Rib"),
(1125, 24073, 24073,       2, 0, 1, 3, 1, 1, "Junk gear"),
(1125, 24700, 24700,     0.1, 0 ,1, 3, 1, 1, "Patterns"),
(1125, 24701, 24701,     0.1, 0 ,1, 3, 1, 1, "Patterns"),
(1125, 11111, 11111,     0.1, 0, 1, 4, 1, 1, "Bags");`
