### ISSUE TITLE
Howling Fjord Quest: Meet Lieutenant Icehammer. (ID=11427)

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#23384]
**Describe the bug**
After the quest is taken, there is an option given by Guard Captain Zorek which fastens the way to your given location, meeting Lieutenant Icehammer.
When you click on the given option, the whole world phases out and you get fatigue debuff.
After relogging you are spawned in the middle of nowhere, in the Frozen Sea. 

**To Reproduce**
Take the quest
Click on the "Take me to Lieutenant Icehammer, Zorek!"
See the bug happen.

**Expected behavior**
When clicking on the interaction possible, you shall mount a gryphon and fly to Icehammers location.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

**Comment by Killyana** [comment]
When I scripted the quest this issue doesn't happen, I don't understand why the player is teleport to the Frozen Sea without being able to see his position.

https://github.com/TrinityCore/TrinityCore/commit/75a987ccf83becd140fb71b75acb0269f9a98323

**Comment by Killyana** [comment]
To reproduce the issue:
.go c id 23728
.quest add 11427
. Talk to Guard Captain Zorek to take the fly

**Comment by Killyana** [comment]
FIx:
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=23728 AND `source_type`=0 AND `id`=1;
DELETE FROM `smart_scripts` WHERE `entryorguid`=2372801 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(23728,0,1,0,62,0,100,0,8984,0,0,0,0,80,2372801,2,0,0,0,0,1,0,0,0,0,0,0,0,0,"Guard Captain Zorek - On Quest Accepted - Action list'"),
(2372801,9,0,0,0,0,100,0,0,0,0,0,0,85,49845,0,0,0,0,0,7,0,0,0,0,0,0,0,0,"Guard Captain Zorek - Action list - Cast 'Valgarde Gryphon'"),
(2372801,9,1,0,0,0,100,0,0,0,0,0,0,72,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,"Guard Captain Zorek - Action list - Close gossip");


SET @GRYPHON:= 27886;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry` IN(@GRYPHON);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(22, 1, @GRYPHON, 0, 0, 31, 0, 4, 0, 0, 0, 0, 0, '', 'Valgarde Gryphon - Only run SAI if invoker is player'),
(22, 7, @GRYPHON, 0, 0, 1, 1, 46598, 0, 0, 1, 0, 0, '', 'Valgarde Gryphon - Only run SAI no aura 63313');

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c90f789eac9092d5332e92242ed0bfab7fd9e9fe fixes the teleport
