### ISSUE TITLE
Hunter Pet Life Bug

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#23386]
**Describe the bug**
Hunter pets life is not calculated correctly, especially seen when buffing it and remounting.

**To Reproduce**

- Summon Hunter Pet
- Buff it with ([Spiced Mammoth Treats] or [Runescroll of Fortitude])
See its life rising for a huge amount.
Mount up
Mount down
See the hunter pet life lowered by 10%

**Expected behavior**
Life not going down after mounting.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

**Comment by Killyana** [comment]
Don't copy past issues that already open https://github.com/TrinityCore/TrinityCore/issues/23304

**Comment by Astrono1293** [comment]
Aokromes added the Invalid-IncompleteData/NotTrinityCore  label 17 days ago
Maybe these " Invalid-IncompleteData/NotTrinityCore " tags should not be attached to reports that ARE in fact related to TC and does not have incomplete data,

**Comment by illfated** [comment]
If you add your comment to that issue ticket, along with your commit rev. hash and steps to reproduce the issue, it is more likely to be updated with removal of the label **[Invalid-IncompleteData/NotTrinityCore]** .

The reason that label is used, is to tell both the reporting users and TC members that an important reference to where in the source this type of issue was reported, so it can be tracked by means of checking commits for related changes.
