### ISSUE TITLE
Crash at startup load db2

### ISSUE THREAD

**Issue by Sevenn83** [TrinityCore/TrinityCore#23395]
**Description:**

Worldserver crash at the beginning of "Initialize data store". I've recently extract db2, map and vmaps from my client (8.1.5.30706), I've configured my DBC.Locale at 2 (yeah, my client is in french).

**Current behaviour:**

Crash at startup on loading data store (db2)
![image](https://user-images.githubusercontent.com/8145934/59393455-091f0600-8d7c-11e9-8a32-b2bccf260884.png)

**Expected behaviour:**

Start without crashes

**Steps to reproduce the problem:**

1. Extract dbc, maps, vmaps
2. Launche wordserver.exe

**Branch(es):**

master

**TC rev. hash/commit:** 

6b29c4da76fbdcb55b4a89f485a5cff58c4296b9

**Operating system:** Windows 10

**Comment by Shauren** [comment]
You have custom changes that load more DB2 files than TC does.
`GeosetID` is not a field known to any DB2 loaded by TC - see https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/DataStores/DB2LoadInfo.h

**Comment by Sevenn83** [comment]
Humm it's strange, the client I used with the extractor is fresh and clean. Maybe a field present on the French version of the game (I don't think, it's really weird). I'm going to extract again to be sure.

**Comment by Shauren** [comment]
You are not using clean TC, thats all it is. Your custom server changes need to be updated

**Comment by Sevenn83** [comment]
Ohh you're right, I don't see my mistake, I'm dump.

Thanks for your support Shauren 👍
