### ISSUE TITLE
Tact_key from 8.1+

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#23393]
Description: tact_key for version 8.1.5 and 8.1.0 they open access to cinematics on these versions.

```
242    6    74    151    9    244    45    80    203    95    139    148    188    26    207    221    93
243    121    210    179    209    204    176    21    71    78    113    88    129    56    100    184    230
250    171    224    197    249    193    35    230    226    78    123    234    67    194    191    0    172
```
242 dor cinematic
243 akt cinematic
250 dpr cinematic

Current behaviour: Without these keys, cinematics cannot be played, showing only a black screen in the client.

Expected behaviour: After adding keys, it gives the opportunity to lose new cinematics.

Branch(es): master

TC rev. hash/commit: 138e822

TDB version: 138e822

**Comment by illfated** [comment]
(adjusted spacing for readability and comma inserts when adding to DB SQL code):
```sql
242    6   74  151    9  244   45   80  203   95  139  148  188   26  207  221   93
243  121  210  179  209  204  176   21   71   78  113   88  129   56  100  184  230
250  171  224  197  249  193   35  230  226   78  123  234   67  194  191    0  172
```

**Comment by funjoker** [comment]
Or just wait for full hotfix update.

**Comment by DintyGadget** [comment]
Update for 8.2.0 added all cinematics, as well as cinematics from version 8.1.0 and 8.1.5 compiled into one patch.

`DELETE FROM `tact_key` WHERE `ID` IN (242, 243, 250, 257, 258, 260, 261, 262);
INSERT INTO `tact_key` (`ID`, `Key1`, `Key2`, `Key3`, `Key4`, `Key5`, `Key6`, `Key7`, `Key8`, `Key9`, `Key10`, `Key11`, `Key12`, `Key13`, `Key14`, `Key15`, `Key16`, `VerifiedBuild`) VALUES
(242,  6,  74,  151,  9,  244,  45,  80,  203,  95,  139,  148,  188,  26,  207,  221,  93,  30706),
(243,  121,  210,  179,  209,  204,  176,  21,  71,  78,  113,  88,  129,  56,  100,  184,  230,  30706),
(250,  171,  224,  197,  249,  193,  35,  230,  226,  78,  123,  234,   67,  194,  191,  0,  172,  30706),
(257,  160,  168,  137,  151,  109,  2,  250,  141,  0,  247,  175,  0,  23,  173,  114,  31,  30993),
(258,  109,  56,  134,  189,  185,  30,  113,  90,  231,  24,  45,  159,  58,  8,  242,  201,  30993),
(260,  197,  82,  245,  208,  183,  34,  49,  80,  45,  37,  71,  49,  78,  96,  21,  247,  30993),
(261,  225,  56,  79,  91,  6,  235,  188,  211,  51,  105,  90,  166,  255,  198,  131,  24,  30993),
(262,  54,  173,  59,  49,  39,  63,  30,  188,  238,  133,  32,  170,  167,  75,  18,  242,  30993);`
