### ISSUE TITLE
Received not handled opcode

### ISSUE THREAD

**Issue by gragonvlad** [TrinityCore/TrinityCore#23407]
Received not handled opcode 8.1.5

Received not handled opcode 8.1.5 include

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Character enter account   [Player: Account: 2] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1920291413 })
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BF (14015)] from [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BE (14014)] from [Player: Account: 2]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36FA (14074)] from [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BF (14015)] from [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BE (14014)] from [Player: Account: 2]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36FA (14074)] from [Player: Account: 2]  Account 2 tried to create character with unavailable race 1
2. Step 2
3. Step 3

**Branch(es):**

master

**TC rev. hash/commit:**  6b29c4da76fbdcb55b4a89f485a5cff58c4296b9

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Windows 10 x64

**Comment by Aokromes** [comment]
duplicate.
