### ISSUE TITLE
Tools/Extractors 8.1.5

### ISSUE THREAD

**Issue by lMGKl** [TrinityCore/TrinityCore#23406]
**Description:**

Tools/extractors are not working properly for the latest build and are not extracting all the maps.
i've checked the path and the .conf and all it's right. i've checked the map folder and actually some maps are missing.
repeated it like 4 times from 2 different PC

**Current behaviour:**

Map file './maps/0000_43_31.map' does not exist! Please place MAP-files (*.map) in the appropriate directory (./maps/), or correct the DataDir setting in your worldserver.conf file.

**Expected behaviour:**
extract all maps  - update the tools source

**Branch(es):**
master 

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
incomplete client very likely or bad user configuration.
