### ISSUE TITLE
DB/Spell: don't allow costume auras from Savory Deviate Delight to stack with each other

### ISSUE THREAD

**Issue by Wyrserth** [TrinityCore/TrinityCore#23417]
**Description:**

The two buffs given by the item [Savory Deviate Delight](https://it.wowhead.com/item=6657) are auras that change the player's appearance. They should not stack with each other.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 5c019db6a7d91e10eb074e8776620527796a3b46

**Suggested fix:**
```sql
DELETE FROM `spell_group_stack_rules` WHERE `group_id`=1112;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES
(1112, 1);
DELETE FROM `spell_group` WHERE `id`=1112;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1112, 8219),
(1112, 8220),
(1112, 8221),
(1112, 8222);
```

**Comment by Killyana** [comment]
there's male version for this spells
https://woehead.way-of-elendil.fr/?spell=8219
https://woehead.way-of-elendil.fr/?spell=8221

**Comment by Wyrserth** [comment]
You're right, thanks! Fixed.
