### ISSUE TITLE
Server crash on startup when 2 scripts share the same name.

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#23412]
**Description:**

If two scripts have the same name, a generic crash will occur on server start-up during the SwapScriptContext

**Current behaviour:**
The server crashes on startup with the following log:
https://gist.github.com/joshwhedon/7856875a452b56c4d7d4ff0a8c2ff7d5

**Expected behaviour:**
The server used to fail to start with a specific error indicating which script is duplicated, allowing to easily pinpoint the issue. IT seems that in the past 2 years (sorry first time I merge in a long time) that feature has been removed.

**Steps to reproduce the problem:**

1. Add a custom script which shares the same name / class name as an other
2. Build
3. Start the server

**Branch(es):**

3.3.5, probably both

**TC rev. hash/commit:** 
dbd8b3fc63 ("Core/Logs: Allow to log startup logs into Database appender", 2019-06-06)

**Operating system:** Windows

**Comment by jackpoz** [comment]
are you building scripts in static or dynamic mode ? hotswap enabled/disabled ?

**Comment by joshwhedon** [comment]
I tried all the script modes (in the CMake you mean I guess ?) and all of them were causing the same crash (except none I guess because it does not prepare any script at all).
I am not sure what hotswap is and how you enable / disable it

**Comment by jackpoz** [comment]
@Naios is this because of the changes required for hotswap ?

**Comment by Keader** [comment]
It always happened (even before hotswap).
2 different scripts cant have same name.
Script name need be unique for each creature/spell.
1 Spell can have multiple scripts signed (it work fine)

**Comment by Shauren** [comment]
@Keader the issue isnt about being able (or not) to have 2 scripts with same name, its that error logging sucks.

**Comment by joshwhedon** [comment]
Yup what Shauren says, the problem I encountered was the lack of actual validation for that situation. It just crashes, with no apparent way to find out the script responsible (even with breakpoints).

**Comment by jackpoz** [comment]
I got an error message in the console before the crash:
>Script 'spell_dk_acclimation' already assigned with the same script name, so the script can't work.

**Comment by jackpoz** [comment]
Turns out "static" scripts always showed the error just fine (even if this issue has only 1 crashlog and the author said he tried all modes)
The crashlog in the issue description is from "dynamic" scripts

**Comment by jackpoz** [comment]
with "HotSwap.Enabled = 1" it shows the same message

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/96df3b7adb02f763aaaa6138922bd032a75a9b9e improved the message
