### ISSUE TITLE
[master] Update Creature Template Data for 8.1.5

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#23411]
**Description:**

**8.1.5 Bruteforce Data**

1. Apply:
```
ALTER TABLE `creature_template` CHANGE COLUMN `family` `family` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `dynamicflags`;
```

2. Apply
https://gist.github.com/funjoker/3c657c4fbfe70693820aebcc88eec7f0

3. VerifiedBuild:
https://gist.github.com/funjoker/9f51048278f62a91ca6d6689dc6c65a8

Locales:
deDE:
https://gist.github.com/funjoker/c9144d256e220a643d77a234816d4f59

esES:
https://gist.github.com/funjoker/5d790cb26981fe429f87ac8e1a823c18

esMX:
https://gist.github.com/funjoker/3d389a196625325919e079aae5c909fa

frFR:
https://gist.github.com/funjoker/eca784db7c6c79583e79b2961915c8b7

itIT:
https://gist.github.com/funjoker/10a9def170f3ce5c3743d24512cc9e50

koKR:
https://gist.github.com/funjoker/4b3ed05e72df2cb59ff449a7f8db9aff

ptBR:
https://gist.github.com/funjoker/d19a207d452652ee56c4b68c13b7d423

ruRU:
https://gist.github.com/funjoker/5bbccf3972557e9dbc7d5a62d92453a4

zhCN:
https://gist.github.com/funjoker/400d65a472498d658b9f5019212784df

zhTW:
https://gist.github.com/funjoker/34b2ce043fcbb9aa4051dbfb92e26984

**TC rev. hash/commit:** 

6b29c4da76fbdcb55b4a89f485a5cff58c4296b9

**Comment by funjoker** [comment]
Hit some issues. Need to ask first

**Comment by funjoker** [comment]
Ok solved the problem

**Comment by funjoker** [comment]
Done

**Comment by Neredun** [comment]
Can this be added along with mdX7 8.0.1 bruteforce https://github.com/TrinityCore/TrinityCore/issues/22848?

**Comment by funjoker** [comment]
#22848 <--- outdated since 8.1.5 bruteforce has all the data too.
but you can also apply mdx7 and then this.

**Comment by funjoker** [comment]
actually there are some things mentioned in mdx7 ISSUE about Primary Key etc.

  Set primary key of creature_template_model to (CreatureID, Idx) instead of (CreatureID, CreatureDisplayID), Blizzard is using same displayid multiple times @ same creature sometimes..

  Implement proper displayid loading for the case when sum of probability is = 0 and number of elements > 1 (just pick random element when sum is 0)

**Comment by funjoker** [comment]
Updated Model to fit eef87a9cc06bea80b9867491e126c6500dc608a9

**Comment by funjoker** [comment]
Done

**Comment by Aokromes** [comment]
0e8a00a to 3137f53
