### ISSUE TITLE
DB/Quests: Updates quest_template wdb data from 8.1.5

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#23423]
**Description:**

Bruteforced data for 8.1.5

https://gist.github.com/funjoker/f3b930a6dc6112278317286577293619

Locales:
deDE:
https://gist.github.com/funjoker/ceec0acb750ce365ec7e2cbe3442f24f

esES:
https://gist.github.com/funjoker/22cfc3bb6bfc17a87b40f0c8d22bcb74

esMX:
https://gist.github.com/funjoker/d1c2c67b561a256b9d9521cf69b377f7

frFR:
https://gist.github.com/funjoker/6115bb63c340f1e06b36c9471a8cc597

itIT:
https://gist.github.com/funjoker/a32f760d6bf99894e939fcfe1ca41327

koKR:
https://gist.github.com/funjoker/5939a441af2ebaade64eabfe9f147ded

ptBR:
https://gist.github.com/funjoker/e07897bda5fdaeb0d04cd92fecc2975d

ruRU:
https://gist.github.com/funjoker/b982f2663f52c4dfc35c5396d27f0fa7

zhCN:
https://gist.github.com/funjoker/2decba208a76422ce993444aca549057

zhTW:
https://gist.github.com/funjoker/241d659fd01519add98687b8541a7b8c

**Branch(es):**

master

**TC rev. hash/commit:** 

6b29c4da76fbdcb55b4a89f485a5cff58c4296b9

**Comment by funjoker** [comment]
Added locales.
Done

**Comment by Aokromes** [comment]
0e8a00a to 3137f53

**Comment by Aokromes** [comment]
wrong ticket xd

**Comment by Aokromes** [comment]
this time for real 1b05271 to 7db1cf6
