### ISSUE TITLE
[BfA] DB/Hotfixes: Updated broadcast_text data from 8.1.5 (+ locales)

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#23424]
**Description:**

Bruteforce data for broadcast_text & locales.

enUS:
https://gist.github.com/funjoker/3b94aede12367f22a43454eed6a5fa92

Locales:
deDE:
https://gist.github.com/funjoker/69d5f6470775324264ccb86cb851fc1f

esES:
https://gist.github.com/funjoker/af567662478957354b3ff566a99e2349

esMX:
https://gist.github.com/funjoker/7c1949d6bc2858684ce1aba90f755f18

frFR:
https://gist.github.com/funjoker/ee3f0c23b7efb88aedf2527ad4972b1e

itIT:
https://gist.github.com/funjoker/37ea9d521cc8346232a0d8e467637976

koKR:
https://gist.github.com/funjoker/e870369c7da11c87a939a5ca8c7c112a

ptBR:
https://gist.github.com/funjoker/a844d927b02bab21944c1ef9b06cedf7

ruRU:
https://gist.github.com/funjoker/998fe2bce360cd329ea479ad8412ba95

zhCN:
https://gist.github.com/funjoker/1832ca616694a6119c05b00ba7dd210e

zhTW:
https://gist.github.com/funjoker/d2ade88ee06c62fdc813d6af5da3da56

**Branch(es):**

master

**TC rev. hash/commit:** 
21674a60f0bcc56429fd2f07067f37df558986e3

**Comment by Aokromes** [comment]
9eb4994  to 3cc71b5
