### ISSUE TITLE
[3.3.5][DB][BRD]Ironhand Guardian's fire should not make players in combat. 

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23435]
**Description:**
Ironhand Guardian's fire should not make players in combat. And once players get in combat with it, they cannot leave combat.

**Expected behaviour:**

fix it 

**Steps to reproduce the problem:**

1. .go c id 8982
2. gm .off

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

5c019db6a7d91e10eb074e8776620527796a3b46

**Operating system:** CentOS 7

**Comment by Wyrserth** [comment]
Fixed in 4529a94e0d093fb01c6ae4a98dade46ce75f82a9.
