### ISSUE TITLE
Scripts/Spells: Gordunni Trap

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#23430]
**Description:**

Implement https://github.com/TrinityCore/TrinityCore/pull/23237#issuecomment-491323662 and https://github.com/TrinityCore/TrinityCore/commit/1c067b3221d956a1fe7106aad6aaaf1d1a381899#commitcomment-33957548

**Current behaviour:**

Not blizzlike

**Expected behaviour:**

Blizzlike

**Steps to reproduce the problem:**

- Revert the custom changes to Blizz-data

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

1c067b3221d956a1fe7106aad6aaaf1d1a381899

**Operating system:** Win 10

**Comment by jackpoz** [comment]
@xvwyh tracking the issue here

**Comment by Killyana** [comment]
Better to wait until getting more accurate data from classic.
this is the original spell DBC data:
``` sql
UPDATE `spell_dbc` SET `RangeIndex`=12, `EffectImplicitTargetA1`=47, `EffectImplicitTargetA2`=47, `EffectRadiusIndex1`=15, `EffectRadiusIndex2`=15 WHERE `id` IN (11756);
UPDATE `spell_dbc` SET `RangeIndex`=12, `EffectImplicitTargetA1`=47, `EffectRadiusIndex1`=15 WHERE `id` IN (19394);
```
Make the player cast the spell instead of the gob.
``` cpp
 class spell_gordunni_trap_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_gordunni_trap_SpellScript);

            void HandleDummy(SpellEffIndex effIndex)
            {
                if (Unit* target = GetHitUnit())
                    target->CastSpell(target, urand(0, 1) ? SPELL_GORDUNNI_DIRT_MOUND_CHEST : SPELL_GORDUNNI_DIRT_MOUND_JUNK, true);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_gordunni_trap_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
            }
        };
```

**Comment by offl** [comment]
9d6c4e3d931875008cd9ca15754b3edb1aef2a01
