### ISSUE TITLE
Script/Quest: The Great Hunter's Challenge

### ISSUE THREAD

**Issue by Wyrserth** [TrinityCore/TrinityCore#23442]
**Description:**

Script the events that happen during the quest [The Great Hunter's Challenge](https://www.wowhead.com/quest=12592) at various progress milestones.

[Reference video](https://www.youtube.com/watch?v=cAKV8NhfP7E).

Closes #16037.

**Branch(es):** both.

**TC rev. hash/commit:** a88d5f54d61664dec9493b73cb9efb021e218169

**Suggested fix:** https://gist.github.com/Wyrserth/cf721cf79f0fdb51b57a7b3896d96af5

**Comment by illfated** [comment]
Looking forward to it. 🤾‍♂
