### ISSUE TITLE
Core: Crash related to spell cast by controlled unit hitting the player

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23440]
**Description:** When the player use https://woehead.way-of-elendil.fr/?spell=44424 with  the controlled bird near it, he well be hit by the spell, and the server crash.

1. .go xyz 391.162842, -6031.32959, 327.560242 571
2. .quest add 11470
3. summon the bird
4. Use pet ability  number three "escape" https://woehead.way-of-elendil.fr/?spell=44424

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 8a174d22957d

**Comment by jackpoz** [comment]
Address Sanitizer log
[worldasan.log](https://github.com/TrinityCore/TrinityCore/files/3305727/worldasan.log)
