### ISSUE TITLE
[BfA] DB/Quest: Quest POI data for 8.1.5

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#23450]
**Description:**

Bruteforced Quest poi data:

https://gist.github.com/funjoker/957bcfaa97fc3b8f483a739c93e55d28

**Branch(es):**

master

**TC rev. hash/commit:** 

9bb85965e10924554b087eb5ae94e6e4fa970ae9

**Operating system:** CHANGEME OS

**Comment by Aokromes** [comment]
64635a7
