### ISSUE TITLE
How to run automatically after system start-up ?

### ISSUE THREAD

**Issue by Marco1221** [TrinityCore/TrinityCore#23453]
OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

install dir 
/home/wow/server

How to run automatically after system start-up ?
I tried to crontab . but it not work
####
@reboot cd /home/wow/server/bin && /usr/bin/nohup ./worldserver > ./Server.log 2>&1 &
@reboot cd /home/wow/server/bin && /usr/bin/nohup ./authserver > ./Auth.log 2>&1 &
####

**Comment by Aokromes** [comment]
this is not a forum.
