### ISSUE TITLE
[DB/item_template]dual RequiredRepuationFaction

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23452]
**Description:**

**Current behaviour:**

**Expected behaviour:**

Is it possible to set a dual RequiredReputationFaction for items? For example, 
The Unstoppable Force required Reputation of Frostwolf or Stormpike in Classic.

**TC rev. hash/commit:** 

62e44d0e4b61c72489961535a00a0386cfb0ca9f

**Comment by Shauren** [comment]
Not possible.

**Comment by Killyana** [comment]
"The Unstoppable Force" doesn't require any Kind of reputation, is there any item that requires 2 reputations or one of 2 ?

**Comment by soniczhang11** [comment]
> Not possible.

OK, thx

**Comment by soniczhang11** [comment]
> "The Unstoppable Force" doesn't require any Kind of reputation, is there any item that requires 2 reputations or one of 2 ?

In Classic yes, in 3.35 I think no. "The Unstoppable Force" in Classic requires 1 of 2 reputations. I get a look on mangos classic but found it is not achieved by RequiredRepuationFaction in item_template. The Value is 0. Maybe it is achieved by dbc.

**Comment by Killyana** [comment]
RequiredReputationFaction is wdb data so we cannot change that.
You can use CONDITION_SOURCE_TYPE_NPC_VENDOR + CONDITION_REPUTATION_RANK  in this case.

**Comment by soniczhang11** [comment]
> RequiredReputationFaction is wdb data so we cannot change that.
> You can use CONDITION_SOURCE_TYPE_NPC_VENDOR + CONDITION_REPUTATION_RANK in this case.

thx! I will try it!

**Comment by Killyana** [comment]
Blizzard duplicates the same item to handle such cases:
https://woehead.way-of-elendil.fr/?item=31829
https://woehead.way-of-elendil.fr/?item=31830
Both have the same spell: https://woehead.way-of-elendil.fr/?spell=39315

**Comment by soniczhang11** [comment]
> Blizzard duplicates the same item to handle such cases:
> https://woehead.way-of-elendil.fr/?item=31829
> https://woehead.way-of-elendil.fr/?item=31830
> Both have the same spell: https://woehead.way-of-elendil.fr/?spell=39315

Hey Killyana, sorry to bother you again. I wanna know for 3.3.5 can spell_bonus_data modify the spell damage in Spell.dbc? I tried to set the direct_bonus of some spell in Spell.dbc to 0.2 or 0.3 and restart the server. But they dont work.
