### ISSUE TITLE
player_classlevelstats - Paladin losing hp when leveling up (14-15)

### ISSUE THREAD

**Issue by ujellyx** [TrinityCore/TrinityCore#23465]
**Description:**

Currently, paladins lose hp ("You gain -1 health") when leveling up from level 14 to 15.

**Current behaviour:**

See description.

**Expected behaviour:**

They should gain a certain amount of health. However I couldn't find any table for the specific levels...
Basehealth for level 80 seems to be correct though.

**Steps to reproduce the problem:**

SELECT * FROM player_classlevelstats WHERE class= 2 AND LEVEL= 14;
SELECT * FROM player_classlevelstats WHERE class= 2 AND LEVEL= 15;
Compare basehp values.

**Branch(es):**

3.3.5

**Comment by ujellyx** [comment]
To add a source:
https://www.youtube.com/watch?v=WOrH1ffAlJ4&t=116

**Comment by Killyana** [comment]
So the char must get +2 stamina ?

**Comment by Aokromes** [comment]
I don't see how this is possible:

https://i.imgur.com/VL0bQ9c.png

**Comment by ujellyx** [comment]
> I don't see how this is possible:
> 
> https://i.imgur.com/VL0bQ9c.png

You're looking at the wrong table - look at "player_classlevelstats".

**Comment by ForesterDev** [comment]
```sql
UPDATE `player_classlevelstats` SET `basehp` = 129 WHERE `class` = 2 AND `level` = 14;
UPDATE `player_classlevelstats` SET `basehp` = 135 WHERE `class` = 2 AND `level` = 15;

```
Source: azerothcore
