### ISSUE TITLE
Crash: Object::GetGuidValue

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23489]
Description:
No idea what happened.
Not sure if it is the same case than this one: https://github.com/TrinityCore/TrinityCore/issues/20171

Crashlog: https://gist.github.com/TheWinchesters/6c2a4145182a12f82cf2bfca95beea7b
Another one: https://gist.github.com/TheWinchesters/9178262d53769318cd640b301fdef772

Branch(es): 3.3.5
TC rev. hash/commit: 273b1e77121ca4176e3a2b99bb144bbb85f3f511 
Operating system: Debian 9

**Comment by Shauren** [comment]
This was supposedly fixed today f4b06fd0b7ead843bba8f5215a09abf7976e012c

**Comment by TheWinchesters** [comment]
Oh, thank you.
I will close this issue then.
