### ISSUE TITLE
[3.3.5] DB/Loot: remove wrong loot from Young Nightsaber

### ISSUE THREAD

**Issue by Wyrserth** [TrinityCore/TrinityCore#23480]
**Description:**

[Young Nightsaber](https://www.wowhead.com/npc=2031) has reference 44007 in its loot template. This reference contains humanoid loot like Linen Cloth, which is wrong for a beast creature.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 632a300dd20aad9663392c2f21a8ed29ffee1ef7

**Suggested fix:**
```sql
DELETE FROM `creature_loot_template` WHERE `Entry`=2031 AND `Reference`=44007;


```

**Comment by Teppic1** [comment]
This 44007 reference loot template is bad anyway (it doesn't represent any real drop pattern), and it's usually added on top of other items leaving duplicates and too much loot.
