### ISSUE TITLE
Shaman Totems follows owner

### ISSUE THREAD

**Issue by OcelotGear** [TrinityCore/TrinityCore#23498]
**Description:**
Totems are wrong

**Current behaviour:**
Shaman totems follows owner

**Expected behaviour:**
Stay in place

**Steps to reproduce the problem:**

1. additem 5178
2. cast 3738
3. move around

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/854a113fc7b6610873b77355aed88900ce3b5bc0

**Operating system:** Any

**Comment by Aokromes** [comment]
e3e4b97

**Comment by OcelotGear** [comment]
Thank you Treeston :heart: . Fixed
