### ISSUE TITLE
Worldserver crash when playing my human mage Loch Modan/Elwynn 3.3.5a

### ISSUE THREAD

**Issue by jaydee2k** [TrinityCore/TrinityCore#23507]
**Description:**

After I compiled the most recent core today worldserver is crashing when I try to play my human mage. Crashes in Loch Modan and in Elwynn when I try to create a new human character.
Undead Level 2 in Tirisfal is working. 

I extracted all resources freshly but it won't help.

Core worked flawlessly for 5 years until now. I hold it up to date.

**Current behaviour:**

[86b5b1b8685e_worldserver.exe_[24-6_18-21-10].txt](https://github.com/TrinityCore/TrinityCore/files/3321746/86b5b1b8685e_worldserver.exe_.24-6_18-21-10.txt)

**Expected behaviour:**

Shouldn't crash.

**Steps to reproduce the problem:**

Play/create human.

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 86b5b1b8685e 2019-06-24 15:50:14 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** Windows 10 2016 ltsb

**Comment by Shauren** [comment]
Release crash log is useless
Build in RelWithDebInfo

**Comment by Shauren** [comment]
Actually, this crash log is enough for me to determine ebd438883e31de4482617631ff9939f2246fda69 as cause.
RAX being 0 means null pointer returned from "a function"
