### ISSUE TITLE
Lightwell follows owner

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#23504]
**Current behaviour:**
Lightwell is following owner (summoner).

**Expected behaviour:**
Lightwell must stay in place.

**Steps to reproduce the problem:** `.cast 724`

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. e3e4b975ce1a 2019-06-24 02:30:07 +0200 (3.3.5 branch) (Unix, Debug, Static)

**Comment by Jildor** [comment]
@Treeston

**Comment by jackpoz** [comment]
could you try a more recent rev like c0b25c9a83126bfd26da8245a31ea684008d804d ? thanks

**Comment by jackpoz** [comment]
I would like to see this issue not included in next TDB release

**Comment by Sorikoff** [comment]
Fixed now. Thanks!
