### ISSUE TITLE
[3.3.5] Gurubashi Arena Run

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#23503]
**Description:**

If you talk to Short John Mithril when he is doing the event intro, the event will bug and no chest will spawn.

**Current behaviour:**

If you are on the "Arena Grandmaster" quest and talk to him you can stop the event.

**Expected behaviour:**

Shouldnt be able to talk to him during event intro.

**Steps to reproduce the problem:**

1. .go creature 636
2. .additem 18706
3. start quest
4. .event start 16
5. talk to short john mithril

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e3e4b975ce1a7a4aa75d61aff7ab3da287b3ceff

**Operating system:** windows

Suggested solution:

https://pastebin.com/KLGmJQQi

adds the flag "not selectable" on event start and removes it once he is returned to his home position.

**Comment by Killyana** [comment]
Caused by https://github.com/TrinityCore/TrinityCore/issues/21190

**Comment by jackpoz** [comment]
This issue is not related to Escort quest though right ?

**Comment by Killyana** [comment]
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (14508) AND `source_type`=0 AND `id` IN (5,6,7);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(14508,0,5,0,68,0,100,0,16,0,0,0,83,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Short John Mithril - On Game Event 16 Started - Remove npc flag"),
(14508,0,6,0,40,0,100,0,33,0,0,0,82,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Short John Mithril - On Waypoint 33 Reached - Add npc flag"),
(14508,0,7,0,40,0,100,0,15,0,0,0,59,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Short John Mithril - On Waypoint 15 Reached - SET run on");

**Comment by Kitzunu** [comment]
Works great :D
When Short John Mithril is walking the path to and from the arena center you are no able to interact with him.
Before and after the path you are able to interact with him again :)

**Comment by jackpoz** [comment]
was the SAI fix applied to 3.3.5 in the end ?

**Comment by offl** [comment]
Nope. I had conversation with Killyana about wp pause during waypoint movement, he mentioned that case and I forgot if that solution is hacky or not.

**Comment by illfated** [comment]
Has any conclusion been reached yet, or any other ideas considered?

**Comment by jackpoz** [comment]
@offl please apply the SAI fix, enough time passed waiting for another solution

**Comment by offl** [comment]
We will be able to fix this after more proper implementation of https://github.com/TrinityCore/TrinityCore/issues/25647 by creating gossipPauseTimer column, probably it may be done even in gossip_menu table
Or by removing core handling and handle it in DB each time we want to pause movement

I doubt gossip flag is removed on retail, questgiver flag is definitely not removed https://www.youtube.com/watch?v=3oYOlz8Hsv0

**Comment by jackpoz** [comment]
@offl do you have a clear proposal about which column to add where and how it should be handled ?

**Comment by offl** [comment]
After discussion in IRC we decided to create column to be able to set specific pause time for specific creature entry

**Comment by jackpoz** [comment]
a22bc236ebc038c723774e5b38cd93e814ccc43d allows to fix this issue
