### ISSUE TITLE
companions do not follow players

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23513]
**Description:**

companions do not follow players. I am sure that it performs well a week ago, after some commits I found it does not work.

**Current behaviour:**

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c0b25c9a83126bfd26da8245a31ea684008d804d

**Operating system:** CentOS 7

**Comment by jackpoz** [comment]
@ccrs could you take a look into this ?

**Comment by jackpoz** [comment]
I would like to see this issue not included in next TDB release
