### ISSUE TITLE
[3.3.5]Pets cannot recover hp after combat.

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23518]
**Description:**

Pets cannot recover hp after combat. (I tested Warlock and Hunter)

**Current behaviour:**

It seems pets are still in combat after player out of combat.

**Expected behaviour:**

fix it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

cb100d64d55c7af65d79c15131e2ebe0bf1cda86

**Operating system:** CentOS 7

**Comment by jackpoz** [comment]
could you check if 678e0e606aa38e18fd361c33bc91833fdae76735 has the same issue ?

**Comment by Aokromes** [comment]
Confirmed on c0b25c9a8312, if you mount and dismount the pets will start to recover hp.

**Comment by soniczhang11** [comment]
> could you check if [678e0e6](https://github.com/TrinityCore/TrinityCore/commit/678e0e606aa38e18fd361c33bc91833fdae76735) has the same issue ?

confirmed,  My server is compiled in May, and I updated the commits every morning. I am sure this issue never fixed since May 14.
