### ISSUE TITLE
[3.3.5][DB-Fix][Quest-12527]Gluttonous Lurkers

### ISSUE THREAD

**Issue by noahyann** [TrinityCore/TrinityCore#23516]
**Description:**
unable to get quest-item on right-click npc

**Expected behaviour:**
1. cast spell-50927 on click npc-28202 // failed
2. additem item-38380 by spell-50927
3. use item-38380
4. cast spell-50919 on click npc-28203 // failed
5. additem item-38382 by spell-50919

**Branch(es):**
3.3.5

**Suggested fix:**
```
UPDATE `npc_spellclick_spells` SET `cast_flags`=3 WHERE `npc_entry`=28202 AND `spell_id`=50927;
UPDATE `npc_spellclick_spells` SET `cast_flags`=3 WHERE `npc_entry`=28203 AND `spell_id`=50919;
```

**full-cmd**
```
UPDATE `world`.`npc_spellclick_spells` SET `cast_flags`='3' WHERE (`npc_entry`='28202') AND (`spell_id`='50927');
UPDATE `world`.`npc_spellclick_spells` SET `cast_flags`='3' WHERE (`npc_entry`='28203') AND (`spell_id`='50919');
```

**Comment by Killyana** [comment]
Update your core and DB, the quest was fixed and there's nothing with:
``` sql
SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=28203 AND `spell_id`=50919;
SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=28202 AND `spell_id`=50927;

**Comment by noahyann** [comment]
> Update your core and DB, the quest was fixed and there's nothing with:
> 
> ```sql
> SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=28203 AND `spell_id`=50919;
> SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=28202 AND `spell_id`=50927;
> ```

![prt_str](https://user-images.githubusercontent.com/52227223/60227944-b25d1480-98c3-11e9-8043-a9b5c2d142e5.png)
