### ISSUE TITLE
[3.3.5][DB-Fix][Quest-12000]Rifle the Bodies

### ISSUE THREAD

**Issue by noahyann** [TrinityCore/TrinityCore#23515]
**Description:**
unable to get quest-item on right-click npc

**Expected behaviour:**
1. cast spell-47096 on click npc-26477 // failed
2. additem item-35792 by spell-47096
3. item-35792 include quest-item(35783)

**Branch(es):**
3.3.5

**Suggested fix:**

```sqo
`UPDATE `npc_spellclick_spells` SET `cast_flags`=3 WHERE `npc_entry`=26477 AND `spell_id`=47096;`

**Comment by Aokromes** [comment]
we don't use database names.
also we don't put ' around numbers.
i suggest you to start sql code with ` ` ` sql

**Comment by noahyann** [comment]
> we don't use database names.
> also we don't put ' around numbers.
> we don't put ( ) if they aren't needed
> i suggest you to start sql code with 3 ` sql

i get it

**Comment by Killyana** [comment]
Update your core and DB, the quest was fixed and there's nothing with:
```
SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=26477 AND `spell_id`=47096;

**Comment by noahyann** [comment]
> Update your core and DB, the quest was fixed and there's nothing with:
> 
> ```
> SELECT * FROM `npc_spellclick_spells`   WHERE `npc_entry`=26477 AND `spell_id`=47096;
> ```

![prt_str](https://user-images.githubusercontent.com/52227223/60227861-6dd17900-98c3-11e9-87b1-ad5a1d120e53.png)

**Comment by Aokromes** [comment]
https://i.imgur.com/lz5NEwC.png
