### ISSUE TITLE
after 'git pull origin 3.3.5', reBuild err

### ISSUE THREAD

**Issue by rereborn** [TrinityCore/TrinityCore#23512]
OS:ubuntu 18.04

err:
../scripts/libscripts.a(eastern_kingdoms_script_loader.cpp.o): In function `AddEasternKingdomsScripts()':
/home/ubuntu/TrinityCore/src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp:362: undefined reference to `AddSC_isle_of_queldanas()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:211: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1596: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jackpoz** [comment]
Try re-running cmake and building again
