### ISSUE TITLE
gamebuild/expansion issues - Vanilla/ TBC and WOTLK realms

### ISSUE THREAD

**Issue by kingzy21** [TrinityCore/TrinityCore#23521]
**Description:**

trying to run multiple realms of each expansion using different clients
e.g. 1.12.1 Client on a 0 expansion realm.
2.4.3 client on a 1 expansion realm.
3.3.5a client on a expansion 2 realm.

**Current behaviour:**
If i set all realms as 3.3.5a i can see can connect with the 3.3.5a client. However i want to run 3 different expansion servers using the different clients if possible. This should be able to be achieved by changing the gamebuild in the realmlist auth table and matching the expansion in the worldserver.conf 

1.12.1 client authenticates but the expansion 0 Realm doesn't display in the client at all with realmlist set.

2.4.3 clinets connects and sees the expansion 1 realm however you get disconnected and receive this error in the worldserver.exe console window.

WorldSocket::HandleAuthSession: Client 127.0.0.1 requested connecting with realm id 3621148577 but this realm has id 2 set in config.

3.3.5a client connects and sees all realms but can only connect to the expansion 2 realm. (As i would expect)

**Expected behaviour:**

The specific clients to connect to the relevant expansion realms.

**Steps to reproduce the problem:**

1. change expansion of worldserver.config to 1 or 0
2. change the gamebuild in the realmlist auth table.
3. login with specified client. 1.12.1 or 2.4.3
4. watch it disconnect you straight away.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TC>TrinityCore rev. 59682bbd9b33 2019-02-09 21:06:09 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...

**Operating system:** Windows 10 x64

**Comment by Aokromes** [comment]
https://community.trinitycore.org/forum/5-help-and-support/

**Comment by Killyana** [comment]
Expansion in worldserver.config doesn't mean client version, but just restriction on BC and wotlk maps.

**Comment by kingzy21** [comment]
I know the client version  or gamebuild is specified in the realmlist auth table. when i set this to the 3.3.5a gamebuild they all connect but changing it stops you being able to connect.

**Comment by kingzy21** [comment]
> https://community.trinitycore.org/forum/5-help-and-support/

This doesn't answer my question. 

Client issues is the closest thing and doesn't mention trying to run different versions of the game client.

I know you guys must get BS requests but a simple no it cannot be done or yeah it can eb done would be better than a link.

No disrespect just frustrating when your issue is insta closed.

**Comment by kingzy21** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130016/realmlist

Why is gamebuild specified on these pages if it cannot be changed or used?

**Comment by kingzy21** [comment]
I'm going to say it would be silly to use the TBC dbc's and Vannilla DBC's when the issue is clearly gamebuild related. If someone simply says you can only use 3.3.5a (12340) then that's fine but as it's not clear and the option of gamebuild is specified at the link above i have used it.
If this is wrong let me know.

**Comment by ustoopia** [comment]
I'm actually facing the exact same issue. Have you eventually managed to solve this issue @kingzy21 ? If so, can you point me in the right direction please?

**Comment by kingzy21** [comment]
It cannot be done using the same Auth dB. I have to run 3 separate Auth servers and world servers with different databases. To connect with the 3 different clients. Then change the ports on the other Auth/ world servers to allow connections.

I hope this helps in some way.

**Comment by ustoopia** [comment]
Yeah that's exactly what I did. I didn't really want to add a portnumber to the address in realmlist.wtf file but I guess there's no other way then. Thanks for the fast response btw! It helped me in a way ;-)  In a way that I should let this go and focus my obsessions on other things :-)

Regards.

**Comment by Warpten** [comment]
YOu can do whatever you want off a single database HOWEVER i am 90% certain Grunt (the auth protocol) changed between at least TBC and wrath meaning you need two authservers, one for each client version, which serves properly - or alternatively, rip out the structures for parsing incoming client,and do it conditionally (client sends its game build to grunt and that part should not have changed). Can't say about vanilla because I'm not even sure it uses grunt
