### ISSUE TITLE
[3.3.5] Cannot revive player's corpse after they release their soul

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23529]
**Description:**

 Cannot revive player's corpse after they release their soul

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

fix it

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c0b25c9a83126bfd26da8245a31ea684008d804d

**Operating system:** CentOS 7

**Comment by Aokromes** [comment]
you need to target body for that, and works on 50c5d30d13fe
