### ISSUE TITLE
[3.3.5] Core: Players visibility should use invisibility detection from the currently controlled unit

### ISSUE THREAD

**Issue by Jerrythemagicdog** [TrinityCore/TrinityCore#23528]
Title. In cases of auras like invisibility being applied on the owner the possessed unit should not have the vision restrictions applied on it.
Also to note, the client will also use the indivisibility glow filter effect but shouldn't.
Example spell: Coax Marmot (38544) - applies an invisibility aura on the caster and the controlled unit shares the vision effects.
https://youtu.be/Amsn4iBbxAI?t=14

Steps to reproduce:
1. .quest add 10720
2. .go xyz 3346.222168, 5783.050781, -7.563022, 530
3. /use Kodohide Drum

rev. eeba12778b330f799eab1530da14bcd8a01b8269 (yesterday's)

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/18301

**Comment by kelno** [comment]
@Killyana 
Seems different to me, the other one is about applying invisibility to a pet, while this one is about visibility while possessing. (In the example given here the invisibility shouldn't be inherited)
