### ISSUE TITLE
DB/Quest: Still at It

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23525]
**Description:** The quest is no longer working after the change in action list, the script must be rewritten using a counter https://github.com/TrinityCore/TrinityCore/commit/e5c0be0a29e13f9ee519c353a56ef8c785f063c5

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 7a71127da92b

**Comment by Wyrserth** [comment]
Fixed in 6aa3ec8fb10e6916fd00368af40471ef8dbeb5d6.
