### ISSUE TITLE
gamebuild can you change this?

### ISSUE THREAD

**Issue by kingzy21** [TrinityCore/TrinityCore#23522]
**Description:**
want ot run Vanilla/TBC/WOTLK servers with one auth server. all runs fine when realms are set to run on 3.3.5a client
Is this field irrelevant in the realmlist table of the auth database?

Build Version | Client Patch
-- | --
5875 | 1.12.1
6005 | 1.12.2
8606 | 2.4.3
9947 | 3.1.3
10146 | 3.2.0
10505 | 3.2.2a
10571 | 3.3.0
11159 | 3.3.0a
11403 | 3.3.2
11623 | 3.3.3
11723 | 3.3.3a
12340 | 3.3.5a

Would like to run multiple realms with multiple clients as stated in previous issue but it got insta closed.
i've changed the account expansion i've changed the realm expansion and the gamebuild.

**Current behaviour:**
using 1.12.1 client no realms are displayed.
using 2.4.3 client realms are displayed but i get the error below.
Connecting with different clients stops me connecting to the realm and i get this error
WorldSocket::HandleAuthSession: Client 127.0.0.1 requested connecting with realm id 935627717 but this realm has id 2 set in config.
3.3.5a works when all realms are set to 3.3.5a if set to older gamebuild they display as offline with the version in brackets e.g. (1.12.1) or (2.4.3)

**Expected behaviour:**
able to run 3 realms on 1 auth server and connect with old clients to the specified realms.

**Steps to reproduce the problem:**

1. change expansion in worldserver.config and gamebuild in realmlist db and expansion of the account in auth db
2. open client lets say 2.4.3
3. login to auth server with no issues
4. when selecting realm the other ones are shown with (1.12.1) or (3.3.5a) offline and greyed out
5. selecting the correct realm generates the error WorldSocket::HandleAuthSession: Client 127.0.0.1 requested connecting with realm id 935627717 but this realm has id 2 set in config.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
TC>TrinityCore rev. 59682bbd9b33 2019-02-09 21:06:09 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...

**Operating system:** Windows 10 x64 1809

Please please please don't just close this with a link to help and support. It's about as useful as a chocolate teacup.

**Comment by Shauren** [comment]
You cannot use the worldserver for other client versions. You would have to find other projects that do support that specific versions (there is no such thing as a single multi-version worldserver .exe)
Changing `gamebuild` does not magically change packet structures or magically reverts combat mechanics to another expansion.

**Comment by kingzy21** [comment]
Shauren thank you this was majorly helpful. 

Much respect.

**Comment by Shauren** [comment]
That field has a different purpose - if you do have multiple DIFFERENT worldservers (other projects) connected to one authserver, then it simply affects what you can see on realmlist window

**Comment by kingzy21** [comment]
Thank you Shauren you actually gave me some great advice.

I now have my 3 servers running.
Changed ports on mysql, realm and world for 2 of the servers.
Now running 1.12.1, 2.4.3 and 3.3.5a simultaniously.
