### ISSUE TITLE
[Database] libmysqlclient detection, TCE00011 false positive

### ISSUE THREAD

**Issue by Diskmaster** [TrinityCore/TrinityCore#23536]
**Description:**

I've discovered a minor inconvience with how gentoo handles libmysqlclient and figured out a way to work around it, the crux of the matter is that, at least on linux, depending on your distro, you can't trust MYSQL_VERSION_ID for the purposes of calling mysql_get_client_version
As per https://dev.mysql.com/doc/refman/5.7/en/c-api-server-client-versions.html

Line 60 in src/server/database/Database/DatabaseWorkerPool.cpp: 
```
    WPFatal(mysql_get_client_version() == LIBMYSQL_VERSION_ID, "Used MySQL library version (%s) does not match the version used to compile TrinityCore (%s). Search on forum for TCE00011.",
        mysql_get_client_info(), MYSQL_SERVER_VERSION);
```

As Gentoo only supports Connector/C's version of libmysqlclient without unmasking a specific USE flag that installs the mysql version. ~The MYSQL_VERSION_ID from Connector/C is 6.1.xx at this time and likely won't change but only in MYSQL_VER and friends, LIBMYSQL_VER per the document, keeps the database version it was based on, which otherwise gives a false TCE00011 error.~
Rewriting for clarity: 
mysql libmysqlclient has identical MYSQL_VERSION_ID and LIBMYSQL_VERSION_ID.
mysql-connector-c libmysqlclient (gentoo's default) has a different MYSQL_VERSION_ID that is the package version instead of the database, which won't match LIBMYSQL_VERSION_ID.

**Current behaviour:**

The client version and server version strings mismatch, and authserver refuses to start, which would normally be a sign of something wrong.

**Expected behaviour:**

If LIBMYSQL_VERSION_ID === MYSQL_SERVER_VERSION, authserver should run normally, along with worldserver.

**Steps to reproduce the problem:**

Try to start auth or world server on a linux distro that provides libmysqlclient from mysql-connector-c. It will refuse to start due to the version mismatch.

**Branch(es):**

both

**TC rev. hash/commit:** 

eb7a6391aafa5e618b2a565f0c2cfc2516dcee7e

**Operating system:** Linux (Gentoo)

~As of this issue's file date, vmaps are currently rebuilding on my box, so I'll be able to test at least on 3.3.5. If it's confirmed working as it's supposed to, I'll file a pull request.~

Server runs on both versions of libmysqlclient, I cannot appear to create a character with either one at this time, so I'm going to leave this up for the time being and wait for future commits in the case that it's just my box being broken in some way.

**Comment by jackpoz** [comment]
We use mostly Debian and Ubuntu where this issue doesn't happen. Even if we fix it for Gentoo, none will be around to keep up the support for it unless someone uses it. Would you be up to fix it and maintain Gentoo support ?

**Comment by Shauren** [comment]
We also don't support using mysql-connector-c at all (on any platform)

**Comment by Aokromes** [comment]
go mariadb.

**Comment by ulisesgolez** [comment]
C:\Users\Ulises\Desktop\TrinityCore Project\src\server\database\Database\DatabaseWorkerPool.cpp:64 in DatabaseWorkerPool<class WorldDatabaseConnection>::DatabaseWorkerPool FATAL ERROR:
Used MySQL library version (6.1.10 id 60110) does not match the version id used to compile TrinityCore (id 80027). Search on forum for TCE00011.

I got this information when trying to run authserver.

**Comment by jackpoz** [comment]
This is not a forum, it's a closed issue from 2 years ago on Gentoo OS. Open a new issue or ask for help on the forum
