### ISSUE TITLE
[Crash] : Player.cpp GetUnitBeingMoved() == target

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23539]
This crash happens more often since we updated to this revision, crash log:
https://filebin.net/64c9vtoxhacpd0dv

crash on line --> 

```player.cpp:23987 in Player::SetClientControl ASSERTION FAILED:
  GetUnitBeingMoved() == target
MapID: 562 Map name: 'Blade's Edge Arena' X: 6278.39 Y: 263.156 Z: 3.75767 O: 1.02022
GUID Full: 0x00000000000034d1 Type: Player Low: 13521 Entry 0
Name: Testplayer
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 5
```

**Branch(es):**
3.3.5
33b4ad5a89cae0d3d527b58e1a438772450d7e32

*** Hardware ***
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Number Of Processors: 8

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

**Comment by Aokromes** [comment]
if you known how to reproduce it, plz supply a full crashlog

**Comment by TheWinchesters** [comment]
I was having this one since I cherry picked f4b06fd

It is always a priest and looks like it is related to Mind Control.
People will also report things like "I can not longer move or do anything after a Priest mind controled me".

Crashlog https://gist.github.com/TheWinchesters/64ea9c21e430b35031d6e867a9d93c51

**Comment by RR2739-VCN** [comment]
https://filebin.net/64c9vtoxhacpd0dv
crash log, 

@TheWinchesters , same here, Player is a priest, using mindcontrol

**Comment by RR2739-VCN** [comment]
So 100% confirmed, this crash is related to Mind Control, Player casts Mind Control on already Polymorphed target | Location : Arena | Blade's Edge Arena

**Comment by Treeston** [comment]
Will have a look, was away for the weekend.
