### ISSUE TITLE
[3.3.5/Gameobject] Fishing bug

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23530]
**Description:**

1. Although players have looted after fishing, server still displays "your fish escaped".
2. Fishing point cannot despawn. I tried to fish at the same point more than 20 times in Booty Bay. The fishing piont never despawned.
3. In Barren Land(oasis) fishing buoy will not disappear after fishing (In other area buoy will not disappear in time after fishing)
4. I found some gobject cannot respawn, (players in my server reported a lot after I updated the code) one of them which I can confirm is the Flag in Warsong Gluch. Flags cannot respawn after countdown for both sides. xD
5. I have tried to git reset to c0b25c9a83126bfd26da8245a31ea684008d804d and confirmed there is no above issue for that commit.

**Expected behaviour:**

fix it.

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5dc2dfd60c4ecd243729e86496d926976e383156

**Operating system:** CentOS 7

**Comment by soniczhang11** [comment]
There is also no above issue for TrinityCore rev. afbd4bbe59f5 2019-06-26 18:12:16 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Comment by Killyana** [comment]
@Wyrserth looks to be related to the last changes in gobs.

**Comment by Wyrserth** [comment]
Fixed in 9f0ac0c24376ec70b8227a8fb0a1e0e686cb3256.
