### ISSUE TITLE
creature_template, _model_info and gameobject_template data from massparses: 8.0.1 & 8.1.5

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#23541]
**Description:**

Data from massparses of my bfa sniffs

creature_template (non wdb)
8.0.1: https://gist.github.com/mdX7/a491cf2baf5783d0bdd9002231668ac3
8.1.5: https://gist.github.com/mdX7/a3f14b7194ed89948accab0c1a766e32

creature_model_info
8.0.1: https://gist.github.com/mdX7/fd9c809ea69346ed29be913f4fd8586f
8.1.5: https://gist.github.com/mdX7/31b9c3dc69a884296e418b834d91f12e

gameobject_template
8.1.0: https://gist.github.com/mdX7/df570a0d21f0052a8fd9280b58dd1e80
8.1.5: https://gist.github.com/mdX7/ff665c4b3ea2a566e11b809fd77e4b77

Could not parse my 8.1.0 sniffs yet due to UpdateFields not being implemented in WPP yet.
Should fix some startup errors and possibly add some due to gameobject_template stuff, heh.

**Branch(es):**

master

**TC rev. hash/commit:** 

d39354e3a31f7fb2cd579e12638d6e6089eefceb

**Comment by Aokromes** [comment]
3291135  to cfa7b00
