### ISSUE TITLE
GameObject/Script: Objects not playing music

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23548]
**Description:** Game objects that have a script to play music are not working.
Example:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/go_scripts.cpp#L1789

**Steps to reproduce the problem:**

1. .event start 3
2. .go game 43009
3. notice no music is played (.debug play music 8440)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d213970719bf

**Comment by Kittnz** [comment]
Weird, did someone mess with PlayDirectMusic function?

**Comment by Wyrserth** [comment]
@Kittnz I'm innocent, I swear! I swear! :P

The issue is that IsHolidayActive() calls return false, so the event never happens. I'm not quite sure why this happens, investigating.
