### ISSUE TITLE
gossip data from massparses 8.0.1 & 8.1.5

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#23549]
**Description:**

Data from massparses of my bfa sniffs

8.0.1: https://gist.github.com/mdX7/5f77fc3f2aa22fc57b0dba2a7846c396
8.1.5: https://gist.github.com/mdX7/cb2967168b6082f9a9f3885d27c503d4

**Branch(es):**

master

**TC rev. hash/commit:** 

d39354e3a31f7fb2cd579e12638d6e6089eefceb

**Comment by Aokromes** [comment]
2c068c1 0f473ea
