### ISSUE TITLE
[3.3.5/talent] Master Conjuror don't affect Spellstone

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23545]
**Description:**

Warlock's talents Master Conjuror(spell id:18767&18768) have no effect on Spellstone (but they have effect on Firestone).

**Current behaviour:**

**Expected behaviour:**

fix it.

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d213970719bfcfeba16dd400217aa722e63b2615

**Operating system:** CentOS 7

**Comment by Wyrserth** [comment]
Cannot reproduce. Grand Spellstone gives 240 haste rating with 2/2 Master Conjuror, base is 60 haste rating.

**Comment by soniczhang11** [comment]
> Cannot reproduce. Grand Spellstone gives 240 haste rating with 2/2 Master Conjuror, base is 60 haste rating.

My fault, sry for that. thx!
