### ISSUE TITLE
quest_template data from massparses 8.0.1, 8.1.0 & 8.1.5

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#23544]
**Description:**

Data from massparses of my bfa sniffs (i actually forgot quest stuff in previous issue, sorry)

8.0.1: https://gist.github.com/mdX7/3209bfef6baad458e5d4c2628ded30ce
8.1.0: https://gist.github.com/mdX7/2b21ed9cd5b307bbd002ce163fd3c282
8.1.5: https://gist.github.com/mdX7/f83a43be1abd43515a35c77a7be4d933

Should fix some startup errors.

**Branch(es):**

master

**TC rev. hash/commit:** 

d39354e3a31f7fb2cd579e12638d6e6089eefceb

**Comment by Aokromes** [comment]
b484d1c a7acdc0 860cbc5
