### ISSUE TITLE
[3.3.5]DB: the trapchest in Stratholme cannot be open

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23557]
**Description:**

the trapchest in Stratholme cannot be open. The normal chest is ok.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f6f1c48aa592ea10c99fd23f46e94934b2f0cef2
**Operating system:** CentOS 7

**Comment by Killyana** [comment]
You have to provide more information, I don't know what's "trapchest" and "normal chest".
