### ISSUE TITLE
Players cannot move or cast spells after Blink/Fear/Dragon''s Breath e.t.c

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23558]
Something is really wrong, with latest revisions, when a player casts Blink or any CC spells on another player, at times, it makes all your spells gray, unable to move, unable to cast unless the same CC spell is casted on the target again.

**Current behaviour:**
Make a Rogue, Make Mage, Cast Blind on a Mage, then make the target cast ex: Iceblock , watch targets spells become gray unable to move unless you cast the same Spell Blink  on the target again, the spells now work and not grayed out. 

**Expected behaviour:**
CC spells like Blind should not gray out spells indefinitely 

**Branch(es):**
3.3.5a  | Rev: f6f1c48aa592ea10c99fd23f46e94934b2f0cef2
--->

**Comment by Astrono1293** [comment]
Happens with Fear as well, happens with any spell that incapacitates your target, it happens almost every 3rd try, however when a player is affected by this, you must log out or ask the same player to recast the same spell on you that incapacitated you in a first place to remove this glitch. Very annoying bug that was recently surfaced , I started to receive reports from players in Battlegrounds non stop.

**Comment by Astrono1293** [comment]
Confirmed, affected by every single spell that incapacitates your target.
Mages can cancel out the bug by casting blink. To be totally honest, I have never seen anything like it., game breaker glitch.

**Comment by TonyFonTony** [comment]
Does reloading UI affect the bug? Or is it just a relog that fixes it?

**Comment by Kittnz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4e767f1c7cd0cae6316982e38be66f560baafea5

**Comment by RR2739-VCN** [comment]
``` if (target->HasUnitState(UNIT_STATE_CONTROLLED))
    if (target->HasUnitState(UNIT_STATE_FLEEING | UNIT_STATE_CONFUSED))```
Hmm, is this even correct?

**Comment by jackpoz** [comment]
could you try anyway that rev and see if it fixes the issue ?

**Comment by RR2739-VCN** [comment]
UNIT_STATE_STUNNED is not included in the OR references ., so I am sure it will only solve half the problem, since UNIT_STATE_STUNNED is being used as well, unless i am missing something here. But yes we will try it now

**Comment by Shauren** [comment]
Stuns do not use SetClientControl, there is no reason to include UNIT_STATE_STUNNED there

**Comment by RR2739-VCN** [comment]
So far so good, we are doing testing today to make sure the issue is resolved, we will update .

**Comment by Treeston** [comment]
cannot reproduce on 84b7b2e

something something "today"

closed
