### ISSUE TITLE
Realm First! Achievements Broken

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#23554]
**Description:**

Realm First! Achievements do not work.

**Current behaviour:**

I maxed a character to level 80 with .character level 80 and usually straight away I would get the Realm First! achievements for becoming the first race and class who reaches level 80 on that specific realm.

**Expected behaviour:**

You should gain these achievements when you reach level 80 (even if you use .character level) as it has worked in the past before I updated my core to this version (will state below).

**Steps to reproduce the problem:**

1. Make a fresh realm
2. Level a character to level 80 or use .character level 80
3. And find that you do not earn the achievements you were meant to.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. c0b25c9a8312 2019-06-24 18:47:04 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by Aokromes** [comment]
gm accounts where forbidden of win realm first! achievements few days ago.

**Comment by LewisPotato** [comment]
Ah thank you for that swift clarification, I should of checked before writing this up.

Issue closed.

**Comment by LewisPotato** [comment]
Just wondering, is there any way I can disable this so I can earn these achievements on a GM account?

Many thanks,
Lewis

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8163ea60c8d517ebe3a88f595dd8291df8338811#diff-5acb07fd050fe28f11194935ec38f3b9

**Comment by LewisPotato** [comment]
How would I go about removing/disabling this? I'm not quite sure what I'm doing with rbac permissions.

**Comment by LewisPotato** [comment]
> 8163ea6#diff-5acb07fd050fe28f11194935ec38f3b9

How would I go about removing/disabling this? I'm not quite sure what I'm doing with rbac permissions.

**Comment by Wyrserth** [comment]
@LewisPotato delete the rbac permission.

DELETE FROM `rbac_linked_permissions` WHERE `linkedId`=9;

**Comment by LewisPotato** [comment]
> @LewisPotato delete the rbac permission.
> DELETE FROM `rbac_linked_permissions` WHERE `linkedId`=9;

Thanks!
