### ISSUE TITLE
gossip_menu_id of tons of creatures were nulled during creature_template massparses

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#23550]
**Description:**

gossip_menu_ids of tons of creatures were nulled after my creature_template massparses (i set wrong filters during parse *shame*)

**Branch(es):**

master

**TC rev. hash/commit:** 
860cbc5e517f2f52d4397b34f9e139a68884c4bd

**Suggested fix:**
(reverts the `gossip_menu_id`=0 parts of the massparses)
https://gist.github.com/mdX7/e2dc3fb722035f12b6426f5796166690

**Comment by Aokromes** [comment]
1bff903
