### ISSUE TITLE
[3.3.5a]In Dreams quest bugged

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23553]
**Description:**

Taelan Fordring do not follow the player,.
The escort is not triggered ...
**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

401777d024785c58f90947cfdadd9b1b7d8fbd3b

**Operating system:** CentOS 7

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18601
