### ISSUE TITLE
[3.3.5]Core: Aggro and go in combat

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23556]
**Description:**

Players in group will not aggro mobs when teammates attack the mobs, even mobs are in near distance. This is not blizzlike. In my memory, players will go in combat when his teammates aggro the mobs in near distance.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f6f1c48aa592ea10c99fd23f46e94934b2f0cef2

**Operating system:** CentOS 7

**Comment by Killyana** [comment]
This behavior is only used by boss inside instances.

**Comment by soniczhang11** [comment]
> This behavior is only used by boss inside instances.

and not by Elite inside instances?

**Comment by Killyana** [comment]
No

**Comment by soniczhang11** [comment]
> No

That means when one player aggro inside instance and pulls mobs near, other guys can just let him die and avoid wipe.  Is this realy blizzlike?

**Comment by Jinnaix** [comment]
Yes - Groupmembers need to interact with the pulling player (by healing or something) or the mob itself to get aggro. Only bosses had mechanics that puts the whole group in combat.

**Comment by soniczhang11** [comment]
> Yes - Groupmembers need to interact with the pulling player (by healing or something) or the mob itself to get aggro. Only bosses had mechanics that puts the whole group in combat.

OK,thanks a lot. sorry for my bad memory.
