### ISSUE TITLE
[3.3.5] Hunter's feign death

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23567]
**Description:**

FD cannot clear threat.

**Current behaviour:**

FD can make Hunter leave combat when he is alone. But when players in a team use FD in combat, his threat will not be cleared.

**Expected behaviour:**

Threat should be cleared after FD.

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9530c33af0847ac13826d20f21d2447f0817bfa5

**Operating system:** CentOS 7

**Comment by Killyana** [comment]
No, the hunter will leave the combat only if he's not engaged with a boss, it works a intended.

**Comment by soniczhang11** [comment]
> No, the hunter will leave the combat only if he's not engaged with a boss, it works a intended.

I agree with you, but what I mean is the threat will not cleared after using FD.

**Comment by Jildor** [comment]
Did you test with more than one player in the raid (not only the hunter)?

**Comment by soniczhang11** [comment]
> Did you test with more than one player in the raid (not only the hunter)?

Yes, I tried it in a team.

**Comment by Jildor** [comment]
seems when @Treeston push Core: Combat/threat system rewrite https://github.com/TrinityCore/TrinityCore/commit/532ab1c7f8653d1a2e48aa1f1f8a9ba1041d4bb7#diff-e896389d5b1073efabc2ffa33ec49d55
and Core/Threat: Threat system adjustments:
https://github.com/TrinityCore/TrinityCore/commit/5cea572a9ad524c6f28ff8519bee61d1ff4357d0#diff-e896389d5b1073efabc2ffa33ec49d55

change this functionality, so maybe @Treeston should explain it a bit ;)

remove the

**Comment by Killyana** [comment]
For me the threat is cleared an the character is no longer in combat upon using FD, in the issue there's something called: Steps to reproduce the problem, without this steps we cannot reproduce the issue.

**Comment by Jildor** [comment]
maybe he means when hunter cast Feign Death when engaged with a boss, the boss lose the agro of hunter temporary, but when hunter remove Feign Death, hunter's agro return to the boss, I'm not sure, but I think should be cleared or reduced to 0 without leave combat.
