### ISSUE TITLE
[3.3.5] Dire Maul

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23565]
**Description:**

There are many bugs in Dire Maul, I checked the scripts in src and only find src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp . It seems the code is not completed.

**Current behaviour:**

1. In Dire Maul North for tribute after killing Gordok King, 3 other bosses cannot turn to be friendly.
2. In Dire Maul West after  killing the element mobs around Pylons, Pylons will not change their state, so the shield of Immol'thar cannot be destroyed.
3. In Dire Maul West Prince Tortheldrin are not attackable after talking.

**Expected behaviour:**

fix them

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9530c33af0847ac13826d20f21d2447f0817bfa5

**Operating system:** CentOS 7

**Comment by offl** [comment]
1 #6429(?)
2 #14685

**Comment by Killyana** [comment]
Duplicate
