### ISSUE TITLE
Core/Movements: Pets cannot hit confused target

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23564]
**Description:** 

If a creature or a player is confused the pet will not be able to hit it.

**Steps to reproduce the problem:**

1. Connect a hunter with a pet
2. Send the pet to start a combat
3. spam .aura 19503 in the creature to keep  it confused
4. Notice the pet cannot hit it

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. f44539b64247

**Comment by Riztazz** [comment]
Isnt that like desired behaviour so pets do not break CC?

**Comment by Aokromes** [comment]
i think so.

**Comment by Wyrserth** [comment]
Pets do not attack targets afflicted by CC auras that break on hit, so that for example Hunters can Scatter Shot without having to recall their pet first. [Source](https://us.battle.net/forums/en/wow/topic/3075667555).
