### ISSUE TITLE
[3.3.5] Warlock quest 'Tome of Cabal' is available for all classes

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23560]
**Description:**
Commit https://github.com/TrinityCore/TrinityCore/commit/5ed77113b637c49e99a610b00f385c51da67c3bf removed the entry for quest 1758 in quest_template_addon, so now any class can take that quest when it is only for warlocks.

**Expected behaviour:**
Quest should be available only for warlocks

**Steps to reproduce the problem:**
1. .go c id 6251

**Branch(es):** 3.3.5a
**TC rev. hash/commit:** 4e767f1c7cd0cae6316982e38be66f560baafea5
**Operating system:** Win 10

**Comment by Killyana** [comment]
QuestSortID=-61 -- Warlock
This must bone via DBC without adding anything to the DB.

**Comment by Killyana** [comment]
Actually, QuestSortID is only used for display category, no need to add an extra check.
