### ISSUE TITLE
[3.3.5] Core/DB HealthModifer in creature_template

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23570]
**Description:**

It only works with integer but not with decimal. 

**Current behaviour:**

For example, creature Mindless Skeleton(Entry:11197), which are summoned by Rivendell in Strat, has value 0.11 at HealthModifer. Its HP then is expected to be 400 according to creature_classlevelstats and HealthModifer. But in fact the HealthModifer does not work with decimal and its HP is still around 3200, which is the value in classlevelstats. It only works with integer.

**Expected behaviour:**

In view of the setting of value in DB, HealthModifer should work with demical.

**Steps to reproduce the problem:**

1. .go c id 10440
2. .gm off to aggro Rivendell
3. wait seconds for the mobs summoning

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

4529a94e0d093fb01c6ae4a98dade46ce75f82a9

**Operating system:** CentOS 7

**Comment by Killyana** [comment]
bashp0=3237 for class=0 and HealthModifer=0.11
3237 x 0.11= ‭356,07‬ (with npc add temp the amount of health is correct =357)

For summoned npc via the spell,  amount of health=3594, it could be (3237 + 357) but I'm not sure as it scale according to the summoner health.

**Comment by OcelotGear** [comment]
Other example, Hunter Snake Trap
![WoWScrnShot_070819_000553](https://user-images.githubusercontent.com/49760010/60781184-b5ec6900-a117-11e9-90ef-0f3e7d654e8f.jpg)
![SNAKE](https://user-images.githubusercontent.com/49760010/60781486-2051d900-a119-11e9-9386-98d38713bcfa.png)
Can reach 20k 
Spell: Snake Trap (https://wotlkdb.com/?spell=34600)
NPC:
```sql
SELECT entry, name, healthmodifier, scriptname FROM creature_template WHERE entry = 19833;
```
SCRIPT:
https://github.com/TrinityCore/TrinityCore/blob/ec1a77bca20487f86765620485db9b13bb03aee8/src/server/scripts/Pet/pet_hunter.cpp#L72

**Comment by soniczhang11** [comment]
> bashp0=3237 for class=0 and HealthModifer=0.11
> 3237 x 0.11= ‭356,07‬ (with npc add temp the amount of health is correct =357)
> 
> For summoned npc via the spell, amount of health=3594, it could be (3237 + 357) but I'm not sure as it scale according to the summoner health.

found a temporary measure for setting the summoned mobs, HealthModifer set a negative rate.

**Comment by Wyrserth** [comment]
Are we positively sure that summoned creatures' health should scale based on summoner's health rather than based on their own level? This causes issue where demons summoned by creatures have far more health than they should have, among all the issues described here..

**Comment by Aokromes** [comment]
the last thing https://github.com/TrinityCore/TrinityCore/issues/281

**Comment by Wyrserth** [comment]
Yeah it sounds strange to me that we have proper scaled data for health/damage/whatever in DB and then we overinflate it with arbitrary scaling based on summoner's stats.

**Comment by OcelotGear** [comment]
About snake trap, if you replace the reset() with JustAppeared() works well.
