### ISSUE TITLE
[3.3.5] DB/Quest -  Thunderbrew Lager

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#23572]
**Description:**

after receiving the task and completing it successfully, the "!" Icon should be turned blue - a daily job. This task can now be done countless times.

**Current behaviour:**

1. Take the task and successfully complete the task
2. when the job is completed successfully, the "!" the icon will not change - daily task
3. The task should only be taken once a day

Video : https://www.youtube.com/watch?v=PPA7Ks81yQI 

**Expected behaviour:**

After performing this task for the first time and completing it successfully, the task icon should turn blue - daily task. This task should only be done once a day.

I found some information about this task : https://classicdb.ch/?quest=117 

**Steps to reproduce the problem:**

1st Take Thunderbrew Lager
2. Successfully complete the task
3. You can take the task again

**Branch(es):**   3.3.5 only

**TC rev. hash/commit:** 
TrinityCore rev. c0b25c9a8312 2019-06-24 18:47:04 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0j  20 Nov 2018 (library: OpenSSL 1.1.0i  14 Aug 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.7.26
Using CMake version: 3.14.4
Compiled on: Windows 10.0.17134
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19061

**Operating system:**  Win 10 Pro  v. 1903 Build 18362.207

**Comment by Killyana** [comment]
The quest mut be repeatable not daily, also the quest mark must be a "yellow !"
https://fr.classic.wowhead.com/quest=117/la-tonnebi%C3%A8re#comments:id=2929649
https://fr.classic.wowhead.com/quest=117/la-tonnebi%C3%A8re#comments:id=2773610

There's only one issue:
The quest mark inside the gossip is displayed as blue? instead a yellow!
But it's displayed correctly on top of the npc.
![image](https://user-images.githubusercontent.com/6587064/60767525-ab02eb80-a0b9-11e9-8083-642fff9b5b42.png)

**Comment by shamage** [comment]
When you watch the video I provided here, you may notice at the end of the task that the icon turns blue. I know it's very badly visible but it can be seen.

Now I do not know which information is correct for this task. 
According to the video, when the first of these tasks ends, the marker turns blue and remains blue.

**Comment by Wyrserth** [comment]
That video isn't from retail - the NPC has the default gossip ("Greetings, %n") instead of the actual gossip text from Killyana's screenshot.

It does look like repeatable, non-autocomplete quests should get the yellow !.
