### ISSUE TITLE
The Purification of Quel'Delar (Quest ID:24553)

### ISSUE THREAD

**Issue by Raven0414** [TrinityCore/TrinityCore#23585]
**Description:**

Warden is missing.

**Current behaviour:**

Warden is missing, unable to speak to him due to his absence, no way to teleport into chamber.

**Expected behaviour:**

Warden should be present next to gates (two of them actually, both on each side), with dialog to teleport into chamber.
**Steps to reproduce the problem:**

1. .q add 24553
2. No warden.

Warden NPC Entry ID : 37523

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e4c2bb4 2019-07-10 16:02:18 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Debian 9 x64

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/4866
