### ISSUE TITLE
Core: Warnings with gcc 8

### ISSUE THREAD

**Issue by Teppic1** [TrinityCore/TrinityCore#23588]
**Description:**

Compiling with gcc version 8.3.0 (Debian 8.3.0-6)

```
/home/tc/TrinityCore/src/server/game/World/World.cpp: In member function ‘void World::LoadConfigSettings(bool)’:
/home/tc/TrinityCore/src/server/game/World/World.cpp:450:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 void World::LoadConfigSettings(bool reload)
```

Might be nothing but normally there are no warnings.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

57070192561b6f385e4c465d397feafe85df2413

**Comment by jackpoz** [comment]
could you paste the cmake call used to setup the build ? (it will tell if it's Debug, RelWithDebInfo or Release and other things that might be related)

**Comment by Teppic1** [comment]
This was fixed sometime between then and now. Now compiles with no warnings.

(I was just using default cmake options except for installation folder)
