### ISSUE TITLE
A suitable disguise (Quest ID : 20438,24556)

### ISSUE THREAD

**Issue by Raven0414** [TrinityCore/TrinityCore#23584]
**Description:**

Quest is broken.

**Current behaviour:**

Tossing pants or other gameobjects does not count as successful and Shandy thinks that something went wrong.

**Expected behaviour:**

Shandy will ask for gameobjects to be thrown into and upon success he will spawn a chest with a tabard.

**Steps to reproduce the problem:**

1. .q add 20438/24556
2. .tele dalaran
3. go to shandy, start the quest
4. throw gameobjects.
5. Quest should fail.

P.S I should also mention that gameobject corresponding is throwing errors into console.
"GameObject (template id: 201931) has invalid faction (faction template id) #0"

The source is clean, build is new, databases are new, it's fresh TC.
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e4c2bb4f1411 2019-07-10 16:02:18 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Operating system:** Debian 9 x64

**Comment by Wyrserth** [comment]
Fixed
