### ISSUE TITLE
[3.3.5]Scripits/Instances/UBRS:  Pyroguard Emberseer

### ISSUE THREAD

**Issue by soniczhang11** [TrinityCore/TrinityCore#23581]
**Description:**

Pyroguard Emberseer cannot be liberatied after killing all warlocks.

**Current behaviour:**

Warlocks do not cast guidance spell to Emberseer. After killing all warlocks, Emberseer will not be liberated.

**Expected behaviour:**

Warlocks should cast guidance spell to Emberseer. After players using altar, warlock should turn faction first and then attack players. After all warlocks killed, Emberseer should growup and be liberated and attack players.

**Steps to reproduce the problem:**

.go c id 9816

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

7f63c504d5cf5a9ad2f3d77ff2c67ca9d7586dd5

**Operating system:** CentOS 7

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19388
