### ISSUE TITLE
AuthServer Can't Handle More Than 50 Realms

### ISSUE THREAD

**Issue by LewisPotato** [TrinityCore/TrinityCore#23597]
**Description:**

The authserver cannot handle more than 50 realms added in the 'realmlist' table.

**Current behaviour:**

Adding more than 50 realms to the realmlist table causes the authserver to crash when the client logs in to retrieve the current realmlist.

**Expected behaviour:**

The authserver should be able to handle more than 50 realms.

**Steps to reproduce the problem:**

1. Import the realmlist.sql file attached at the bottom of this post to your realmlist table.
2. Boot up the authserver
3. Try and login and you will find the authserver will crash

**Branch(es):**

3.3.5a (Could also be affecting master)

**TC rev. hash/commit:** 

TrinityCore rev. 644910b+ 2019-07-07 02:57:24 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**EDIT** http://media.ideagaming.com/downloads/misc/realmlist.zip **EDIT**
VIRUSTOTAL: https://www.virustotal.com/gui/file/82574c4422e80d6d116017c0841bfde5941a8f857c46ce12100e4c4fb332bf6f/details

**Comment by LewisPotato** [comment]
Obviously you nobody will run 50+ realms but I've put together a blizzlike realmlist and I'd like to be able to use it even if I'm not going to run those realms.

**Comment by Shauren** [comment]
You mentioned that it will crash but where is the crash log?

**Comment by LewisPotato** [comment]
> You mentioned that it will crash but where is the crash log?

Uh there actually isn't one, it starts up normally then when somebody logs into the authserver it will just stop responding completely.

**Comment by jackpoz** [comment]
> 1. Import the realmlist.sql file attached to your realmlist table.

attached where ?

**Comment by LewisPotato** [comment]
> Import the realmlist.sql file attached to your realmlist table.
> 
> 
> attached where ?

Sorry, something is wrong with me today. Lol

I have attached it to the original post with a VirusTotal link.
