### ISSUE TITLE
About the issue of attack strength display

### ISSUE THREAD

**Issue by isgoog** [TrinityCore/TrinityCore#23596]
My equipment database property is relatively large, I found that the attack strength exceeds a certain value and it shows 0. This thing has puzzled me for a few days, can anyone help me.
Sorry, my English is not good. I hope that Google Translate can't cause dyslexia for you.
Thank you!

**Comment by Aokromes** [comment]
we don't support custom items.

**Comment by w5860363** [comment]
Confirmation, but this is just a new structure display problem
