### ISSUE TITLE
[Crash] Deleting multiple Gameobjects

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23590]
I encountered this problem today, I spawned 10 chests, Same ID (Chests) upon deleting 3rd and 4th , server crashed.,

To reproduce:

1. GO ID: 190552
2. Spawn 10 of these and try deleting them right after
3. Server Crash on this revision

Crash Log:
https://pastebin.com/i2gxKJEc

Rev: ded18a2690063991d5440df7d3e5d526b884ec16

*** System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

**Comment by jackpoz** [comment]
Is that only a part of the crashlog ?

**Comment by Aokromes** [comment]
[11:44:13] Found nearby gameobjects (distance 10.000000): 11
[11:44:35] Game Object (GUID: 166014) removed
[11:44:37] Game Object (GUID: 166020) removed
[11:44:39] Game Object (GUID: 166021) removed
[11:44:45] Game Object (GUID: 166017) removed
[11:44:54] Game Object (GUID: 166015) removed
[11:44:56] Game Object (GUID: 166023) removed
[11:45:18] Game Object (GUID: 166018) removed
[11:45:28] Game Object (GUID: 166019) removed

**Comment by Shauren** [comment]
Improved log eed92676858c9c10b1bd570894d562b21e72a905

**Comment by jackpoz** [comment]
@RR2739-VCN could you update to https://github.com/TrinityCore/TrinityCore/commit/eed92676858c9c10b1bd570894d562b21e72a905 , build in Debug, reproduce the issue and post the full crashlog ?

**Comment by RR2739-VCN** [comment]
Surely can @jackpoz

**Comment by RR2739-VCN** [comment]
@Shauren @jackpoz 
Was able to reproduce again using the same revision but now with a full crash log, assertion failure upon deleting an object.

https://gofile.io/?c=aBXAVS

Related to  to this maybe ?https://github.com/TrinityCore/TrinityCore/commit/680e2e611954e6dee3060a45a4d1b9551069fd2c

**Comment by jackpoz** [comment]
That logs is from https://github.com/TrinityCore/TrinityCore/commit/7f63c504d5cf but we asked to update to https://github.com/TrinityCore/TrinityCore/commit/eed92676858c9c10b1bd570894d562b21e72a905 at least.

It also uses RelWithDebInfo but we asked to build in Debug. As you have How To Reproduce steps, it should be easy to reproduce the issue in a test realm built in Debug.

**Comment by RR2739-VCN** [comment]
I didnt get to it yet but using this crash log you should have enough info to know whats going on here. Considering i been deleting and readding objects to our server for years and never has it caused a crash

**Comment by Aokromes** [comment]
still cannot reproduce on head:
https://i.imgur.com/2DGw3a0.jpg

**Comment by RR2739-VCN** [comment]
It only happens in certain maps. I coukdnt reproduce in Kalimdor or Eastern Kingdoms. This only happens on maps that console has an error on. At times console reads Map cannot be loaded and if i spawn objects on that map, delete, crash. Mostly happens in Shattrath City or Makers Perch.

**Comment by jackpoz** [comment]
could you post a crashlog built in Debug in those maps then ?

**Comment by Aokromes** [comment]
https://i.imgur.com/ieiBonD.jpg still cannot reproduce

**Comment by Aokromes** [comment]
https://i.imgur.com/sm80lmc.jpg

**Comment by Aokromes** [comment]
plz supply .server debug and .gps coords of where  you get crash.

**Comment by transcend-dev** [comment]
http://s000.tinyupload.com/index.php?file_id=03433193471964973239
confirm crash after removing object, I added ad gobject in game, rebooted server, then try delete, crash

**Comment by jackpoz** [comment]
>Assertion message: 
c:\users\user\desktop\tranw\source\src\server\database\database\mysqlconnection.cpp:445 in MySQLConnection::GetPreparedStatement ASSERTION FAILED:
  index < m_stmts.size()
Tried to access invalid prepared statement index 218 (max index 73) on database `trworld`, connection type: asynchronous

**Comment by jackpoz** [comment]
@transcend-dev could you build in Debug and reproduce the issue ?

**Comment by Shauren** [comment]
Ok, I know exactly what is going on here

**Comment by jackpoz** [comment]
@Treeston could you take a look at this crash ?

**Comment by Shauren** [comment]
I'll think of some way to prevent this at compile time, just like I did for `DatabaseWorkerPool::GetPreparedStatement`

**Comment by Shauren** [comment]
Btw to reproduce you need to put the gameobject/creature on respawn timer - fresh spawns wont trigger it
