### ISSUE TITLE
Core/Addon: Blizzard_TimeManager addon

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23599]
**Description:** Once IG if you use escape you will always get an error about Blizzard_TimeManager.

![image](https://user-images.githubusercontent.com/6587064/61257499-98e81380-a771-11e9-8599-b41ee23df16a.png)

**Steps to reproduce the problem:**

1. Connect any charachter IG
2. use escape key

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. c27804473976

**Comment by Treeston** [comment]
assumedly caused by v

**Comment by Treeston** [comment]
assumedly caused by cd3d317e

**Comment by jackpoz** [comment]
Could you enabled "addon" log type of level warning and post any "Addon: %s: not registered as known secure addon - accountId %d" or " Addon: %s: modified (CRC: 0x%x) - accountID %d)" message ?
You could also enable debug level and look for "Addon: %s: validated (CRC: 0x%x) - accountID %d" messages

**Comment by Shauren** [comment]
Only TimeManager is doing that?

**Comment by Killyana** [comment]
Also Blizzard_Calendar

**Comment by VincentVanclef** [comment]
I am unable to log ingame after https://github.com/TrinityCore/TrinityCore/commit/cd3d317ebf74c4bd2b9a806e4463e2d0ae730a3b. My wow.exe just shuts down and prints:

https://i.imgur.com/zEK4IfZ.png

I removed this specific commit and i can log ingame, i checked and verified the DB data was correct. Any idea?

**Comment by Shauren** [comment]
Try deleting all Interface\Addons\Blizzard_*** folders

**Comment by VincentVanclef** [comment]
This also gets logged on every character when i am trying to login:

`TC>Received unexpected opcode [CMSG_CANCEL_TRADE 0x011C (284)] Status: STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT Reason: the player has not logged in yet and not recently logout from [Player: Account: 1]
`

**Comment by VincentVanclef** [comment]
Deleting the folders fixed it, i can login now lol

**Comment by VincentVanclef** [comment]
@Shauren the issue keeps returning. WoW closing down as soon as loading screen is done, with this error:

https://i.imgur.com/zEK4IfZ.png

Deleting the addons allows me to login, but after restarting wow i get the error again. Any idea :/?

**Comment by jackpoz** [comment]
Did you update to https://github.com/TrinityCore/TrinityCore/commit/86b516c3f27f155f267245fc27ae634a76bb1e2f ?

**Comment by Shauren** [comment]
Are you using any mpq patches that modify defult interface or something?

**Comment by VincentVanclef** [comment]
@Shauren nope but appeared I was indeed on the wrong revision. Its good now, my bad.
