### ISSUE TITLE
Unable to open file SSAOSettings.db2

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#23593]
Description:

Unable to open file SSAOSettings.db2 in the archive for locale deDE: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale esES: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale esMX: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale frFR: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale itIT: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale koKR: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale ptBR: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale ruRU: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale zhCN: FILE_NOT_FOUND
Unable to open file SSAOSettings.db2 in the archive for locale zhTW: FILE_NOT_FOUND

Steps to reproduce the problem:

1. Compile the server. (TrinityCore). 
2. Extract maps.

Branch(es): master

Operating system: Windows 10 Pro. Version 1809 Build 17763

https://user-images.githubusercontent.com/15787347/61188834-1701c880-a653-11e9-9538-1a68e17fb16f.png

**Comment by Shauren** [comment]
Ignore. Not shipped in client and unused by TC
