### ISSUE TITLE
Script/ScarletEnclave: Eye of Acherus

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#23594]
**Current behaviour:**
Eye of Acherus is too slow.

**Expected behaviour:**
Speed must be increased by 400% through `51923`.

**Steps to reproduce the problem:** make DK; reach quest `The Eye Of Acherus` (12636)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. f46644c92585 2019-07-15 05:59:57 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Killyana** [comment]
I think there's 2 spells used for the fly speed:

1- When the eye start the waypoint and cannot be controlled it will use: https://woehead.way-of-elendil.fr/?spell=51923

2- Once the waypoint ends it must use https://woehead.way-of-elendil.fr/?spell=51890 and the first aura is probably removed

For the moment none of the 2 auras works, probably caused the cumulation of the 2 effects or the way this spells are cast.

Also I noticed if you remove this 2 auras (after the waypoint) and .aura 51890  you will not be able to change Z axis (unless using Space or X)

**Comment by Sorikoff** [comment]
Fixed now.

**Comment by illfated** [comment]
Would be nice to know which core rev. hash you verified this to be fixed, just to have some sort of "end delimiter" after 2019-07-15 05:59:57.

**Comment by Sorikoff** [comment]
I've tested on latest (https://github.com/TrinityCore/TrinityCore/commit/4f2f1959c3c3130ae4eb2d614699bef1f7c363fd).

**Comment by illfated** [comment]
OK, fair enough. That is as good a date time limit as any.
