### ISSUE TITLE
Core/Spells: Interruption via Pushback Mechanics must effect players only

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23598]
**Description:** This commit https://github.com/TrinityCore/TrinityCore/pull/21395/files#diff-4522eeffcbc961602e86620011a2d579L878 made the Interruption via Pushback Mechanics also effecting creatures, is it the correct behavior?

@ariel- 

**Branch(es):** 3.3.5 

**TC rev. hash/commit:** rev. f46644c92585

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/45c5e1b9d63796d168339a44f63418f220cf2403#diff-4522eeffcbc961602e86620011a2d579L878 here

**Comment by Aokromes** [comment]
https://i.imgur.com/MXDjbas.png blame old comment

**Comment by Treeston** [comment]
37f6982

**Comment by Aokromes** [comment]
it looks it comes from mangos xd

f3c48aa8314 (KingPin          2008-11-17 22:07:21 -0600   867)             if(pVictim != this && pVictim->GetTypeId() == TYPEID_PLAYER) // does not support creature push_back
