### ISSUE TITLE
Core/Pets: Guardians not follow after combat

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#23602]
**Description:**

I know there are several closed issues just 25 days ago with this issue, so unsure if its just me. But I recently stumbled upon the quest https://wotlk.evowow.com/?quest=12982

And the Ebon Blade Knight guardians summoned from: https://wotlk.evowow.com/?spell=56212

Refuses to follow me after end combat.

**Current behaviour:**

Does not follow after end combat.

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Should follow after end combat.

**Steps to reproduce the problem:**

1. .cast 56212
2. engage in combat
3. Run away, notice Ebon Blade Knight stays in his position.

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

45471ece17165b38a5783cfbd0499e3068378d3c

**Operating system:** CHANGEME OS

Windows 10

**Comment by jackpoz** [comment]
does the issue happen only with Ebon Blade Knight ?

**Comment by VincentVanclef** [comment]
Nope appears to happend with others as well, just didnt notice it until i was at that quest.

Ebon Blade Knight will fight nearby enemies if they come near, but he will not follow me after combat has ended.

**Comment by VincentVanclef** [comment]
Tested quest https://wotlk.evowow.com/?quest=11611 and the same happends here with the Warsong Hold guards. They only appear to react agressive but wont follow again either.

**Comment by Killyana** [comment]
Yes confirm https://github.com/TrinityCore/TrinityCore/issues/17981 is back again.

**Comment by Wyrserth** [comment]
Can confirm too, Death Knight's Ghoul (without the Unholy permaghoul talent) stops following player after killing a mob.

**Comment by jackpoz** [comment]
@ccrs could you take a look at this ?

**Comment by ccrs** [comment]
sure
