### ISSUE TITLE
Update npc that does not have the flag UNIT_NPC_FLAG_QUESTGIVER.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#23601]
Description:
Some npc does not have the flag UNIT_NPC_FLAG_QUESTGIVER, which starts or ends quest.

``` sql
UPDATE `creature_template` SET `npcflag`=npcflag|2 WHERE `entry` IN (620,2501,4138,4217,4606,6566,6735,9999,14871,18020,18024,19936,28070,31081,31085,31273,31304,32964,33232,33250,34301,34402,34403,34404,36444,38440,38442,39908,40825,44999,50690,51998,53466,54751,55438,56112,56113,56115,58408,59074,59442,59448,59449,59450,59451,79457,81912,91223,93677,94870,97978,101282,106182,107997,108389);
```

All creatures that do not start those quest are removed from `creature_queststarter`:
``` sql
DELETE FROM `creature_queststarter` WHERE `id` IN (270,341,682,684,686,687,737,1085,2372,2748,3256,7139,7149,12201,12236,12258,13282,15273,15294,15298,17975,17976,17977,17978,19219,19220,19513,19598,19865,35382,37989,38225,38306,45006,45202,46268,46859,46860,46861,46915,46916,46917,48878,48880,48922,48923,48924,49116,2491,2494,2498,2594,3150,3678,4631,5464,7794,7937,8664,10051,14742,21643,23872,30464,34991,36674,41018,43845,55143,58465,58468,58469,58470,58471,58818,59341,78052,78333,81927,94194,99077,100448,102278,110751,111513,111775,112627);
```
All creatures that do not finish those quests have been removed from `creature_queststarter`:
``` sql
DELETE FROM `creature_questender` WHERE `id` IN (270,341,682,684,686,687,737,1085,2372,2748,3256,7139,7149,12201,12236,12258,13282,15273,15294,15298,17975,17976,17977,17978,19219,19220,19513,19598,19865,35382,37989,38225,38306,45006,45202,46268,46859,46860,46861,46915,46916,46917,48878,48880,48922,48923,48924,49116,2491,2494,2498,2594,3150,3678,4631,5464,7794,7937,8664,10051,14742,21643,23872,30464,34991,36674,41018,43845,55143,58465,58468,58469,58470,58471,58818,59341,78052,78333,81927,94194,99077,100448,102278,110751,111513,111775,112627);
```

Branch(es): master 

Operating system: Windows 10 Pro.

**Comment by Killyana** [comment]
From where you get this data?
For the first npc https://www.wowhead.com/npc=270/councilman-millstipe he no longer starts https://www.wowhead.com/quest=377/crime-and-punishment
When a quest is depreciated like this one w just remove it from creature_queststarter and we keep it creature_questender in the case the player still have the quest in his journal:
``` sql
SELECT * FROM   `creature_queststarter`  WHERE `id` IN (270);
SELECT * FROM   `creature_questender`  WHERE `id` IN (270);

**Comment by Killyana** [comment]
Looks legit anyway. Need to check every npc before pushing the sql.

**Comment by Fabi** [comment]
He is getting all data from wowhead as far as I can tell. wowhead got pretty good data but you shouldn't rely on them for quests/deprecated quests  for example

**Comment by osleyder85** [comment]
I'm going to review everything again.

**Comment by osleyder85** [comment]
Now update the tables:

- creature_template
- creature_queststarter
- creature_questender

It remains to review that quest that was removed, and put them to the npc that corresponds.
