### ISSUE TITLE
DB/Quest: Silver Heart quest_request_items CompletionText correction

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23608]
**Description:**

Eridan Bluewind in Emerald Sanctuary, Felwood, offers the quest "Silver Heart" (ID 4084) as a part of the Linken / Aquementas quest chain. But the current `quest_request_items`.`CompletionText` text content for quest ID 4084 in TDB 335.19071 contains too many words (`of which you`), making the English grammar awkward and wrong.

- https://www.wowhead.com/quest=4084/silver-heart
- https://classic.wowhead.com/quest=4084/silver-heart
- https://wow.gamepedia.com/Silver_Heart#Progress
- https://wow.gamepedia.com/Eridan_Bluewind
- https://wowwiki.fandom.com/wiki/Quest%3ASilver_Heart#Progress
- https://wowwiki.fandom.com/wiki/Eridan_Bluewind

**Current behaviour:**

```sql
SELECT `ID`,`CompletionText` FROM `quest_request_items` WHERE `ID`=4084;
```
```
  ID  CompletionText
----  ---------------------------------------------------------------------------------------------------------------------------------
4084  I can tell you more of the power of which you required to defeat Blazerunner, but first, you need to gather the things I require.
```

**Expected behaviour:**

The text should read as follows (3 words less):
> I can tell you more of the power required to defeat Blazerunner, but first, you need to gather the things I require.

**Steps to reproduce the problem:**

1. `.tele emeraldsanctuary`
2. `.quest add 4084`
3. `.quest complete 4084`
4. Hand in the quest to Eridan Bluewind inside the house. Read the quest text carefully, with English grammar in mind. Notice that the sentence (on the page before the reward page) does not make proper sense in English.

**Suggested solution:**

```sql
-- Silver Heart
UPDATE `quest_request_items` SET `CompletionText`= "I can tell you more of the power required to defeat Blazerunner, but first, you need to gather the things I require." WHERE `ID`=4084;
```

**Branch(es):**

3.3.5 (Deprecated for master branch)

**TC rev. hash/commit:** 

```sql
SELECT * FROM `version`;
```
```
core_version                                                                                     core_revision  db_version     cache_id
-----------------------------------------------------------------------------------------------  -------------  -------------  --------
TrinityCore rev. 3f7b2252a1d7 2019-07-18 15:52:03 +0200 (3.3.5 branch) (Win64, Release, Static)  3f7b2252a1d7   TDB 335.19071     19071
```

TC>server debug
TrinityCore rev. 3f7b2252a1d7 2019-07-18 15:52:03 +0200 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.1.0j  20 Nov 2018 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.69.0
Using MySQL version: 5.6.43
Using CMake version: 3.14.5
Compiled on: Windows 10.0.18362
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658637709 bytes
mmaps directory located in ./mmaps. Total size: 2030097204 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19071
TC>_
```

**Operating system:**

PC/game client : Windows 10 1903 (Home & Pro)
Server: Tested both on my own Windows 10 computer and on https://tcubuntu.northeurope.cloudapp.azure.com/ (Ubuntu/Unix build)

**Comment by Wyrserth** [comment]
Thanks for your fix!
