### ISSUE TITLE
[3.3.5] DB/Stacks: Priest: Power Infusion stack with Mage: Arcane Power

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23614]
**Description:**

https://www.mmo-champion.com/threads/692845-Arcane-Power-Power-Infusion-Fail
https://wow.gamepedia.com/Power_Infusion
>Patch 1.10.2 (2006-05-02): This ability will no longer stack with  [Arcane Power]. If you gain both at the same time, Arcane Power will take precedence. 

ID - 10060 Power Infusion
ID - 12042 Arcane Power

Old Issue: #8705

**Possible Fix:**
(Updated here: #23619)
```sql
SET @GROUP_ID := 1122; -- Change with the proper ID if this is in use
DELETE FROM `spell_group` WHERE `id`=@GROUP_ID AND `spell_id` IN (10060,12042);
INSERT INTO `spell_group` (`id`,`spell_id`) VALUES
(@GROUP_ID,10060), -- Priest - Power Infusion
(@GROUP_ID,12042); -- Mage - Arcane Power

DELETE FROM `spell_group_stack_rules` WHERE `group_id`=@GROUP_ID;
INSERT INTO `spell_group_stack_rules` (`group_id`,`stack_rule`) VALUES
(@GROUP_ID,4);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8a174d22957d3f641b4a6750cdc2a4ae88a88402

**Comment by Killyana** [comment]
It could stack with Heroism or Bloodlust ?

**Comment by Jildor** [comment]
This is another bug and should fixed here: https://github.com/TrinityCore/TrinityCore/pull/23592

**Comment by Jildor** [comment]
Closed by: https://github.com/TrinityCore/TrinityCore/commit/75a5192c31390deca490dada3bdb0e89dcafdf8d
