### ISSUE TITLE
ick moves casting mines, double novas

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23621]
**Description:**

https://dl.dropboxusercontent.com/s/oc6pxncayudhlbk/2019-07-21_18-28-45.mp4

**Current behaviour:**

it moves while casting mines and casts novas 2 times.

**Expected behaviour:**

it most stop casting mines, it must cast a single nova.

**Steps to reproduce the problem:**

1. enter pit of saron (.tele frozen halls, enter right door)
2. fight ick
3. run.
very likely more creatures are afected by this bug.

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

2bac44c

**Operating system:** Debian 10 x64

**Comment by Treeston** [comment]
51cf1c7
