### ISSUE TITLE
DB/Quest: Call of Earth (Azuremyst Isle 2) incomplete quest CompletionText

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23623]
**Description:**

As a draenei shaman, your first class quest line (as most of you already know) is **Call of Earth**.
But when taking the second part from the earth elemental "Spirit of the Vale",
you may have noticed that the quest gossip on incomplete quest is empty, except for the title.

- https://wow.gamepedia.com/Call_of_Earth_(Azuremyst_Isle_2)
- https://wow.gamepedia.com/Spirit_of_the_Vale
- https://www.wowhead.com/quest=9450/call-of-earth
- https://www.wowhead.com/npc=17087/spirit-of-the-vale
- https://woehead.way-of-elendil.fr/?quest=9450

**Current behaviour:**

When taking Call of Earth, second part (Call_of_Earth_(Azuremyst_Isle_2)) from the earth elemental "**Spirit of the Vale**", the quest gossip on incomplete quest is empty, except for the quest title.

**Expected behaviour:**

There should be a quest gossip even when the quest is incomplete, to tell the player that the quest giver is waiting for some Progress. Seeing that this quest was removed in patch 4.0.3a, the incomplete quest text is not very obvious, because that part is often skipped in many of the wiki pages around the 'net. I could only find 2 reasonably good sources for what the text should be:

- https://www.wowhead.com/quest=9450/call-of-earth#comments:id=47655
- http://db.excalibur.ws/?quest=9450

```
The elements still seem out of balance to me, <name>.
```

**Suggested solution:**

```sql
-- Call of Earth (Azuremyst Isle 2)
UPDATE `quest_request_items` SET `CompletionText`="The elements still seem out of balance to me, $n." WHERE `ID`=9450;
```

**Steps to reproduce the problem:**

1. Create a draenei shaman character, level 4 (or above)
2. `.quest add 9450`
3. `.go creature id 17087`
4. Open the NPC gossip and click on the quest title ❔ **Call of Earth** -- and find only the quest title.

**Branch(es):**

3.3.5 (this quest was removed in patch 4.0.3a)

**TC rev. hash/commit:** 

TrinityCore rev. c8278cddeb49 2019-07-21 17:37:05 +0200 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...
```
TC>server debug
TrinityCore rev. c8278cddeb49 2019-07-21 17:37:05 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.0k  28 May 2019 (library: OpenSSL 1.1.0k  28 May 2019)
Using Boost version: 1.69.0
Using MySQL version: 5.6.43
Using CMake version: 3.14.5
Compiled on: Windows 10.0.18362
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658637709 bytes
mmaps directory located in ./mmaps. Total size: 2030097204 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19071
TC>_
```

**Operating system:** Windows 10 1903 Home x64
Also seen on tcubuntu.northeurope.cloudapp.azure.com today, (Unix build)

- [ ] The TC wiki pages could be improved with info saying that the table `quest_request_items` is also used for Progress text in quests without requested items.

**Comment by Wyrserth** [comment]
Thanks for your fix!
