### ISSUE TITLE
No loot if mob moves before kill

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23620]
**Description:**

You don't get loot a lot of times if mob moves before you kill it

**Current behaviour:**

You don't get loot

**Expected behaviour:**

You get loot even mob moves.

**Steps to reproduce the problem:**

1. go c id 17138
2. .dam 10000 some mobs of area you will get loot
3. .dam 5000 2 times some mobs on area, you will fail to get loot.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2bac44c

**Operating system:** Debian 10 x64

**Comment by Wyrserth** [comment]
Can reproduce in e5615402cc2dbc8cea6ffada0d759a7feeacb4b7.

**Comment by illfated** [comment]
Is this why I suddenly stopped getting loot from [Vale Moths](https://wow.gamepedia.com/Vale_Moth) when doing quest 2 ([Replenishing the Healing Crystals](https://wow.gamepedia.com/Replenishing_the_Healing_Crystals)) in the Dranei starting area after creating a new Draenei character on tcubuntu.northeurope.cloudapp.azure.com ?

**Comment by Aokromes** [comment]
very likely.

**Comment by illfated** [comment]
Phew... thanks. I thought I was causing the bug myself by having all my addons enabled and experiencing lag due to addons updating.

**Comment by Aokromes** [comment]
81fcd2e

**Comment by jackpoz** [comment]
@illfated as you play quite much on the test realm, do you need a gm account ? Just write here your username and I can give it gmlevel 3

**Comment by illfated** [comment]
My account at the moment is the same as my Github user. Aokromes gave me access to the commands `.tele` and `.additem` earlier, just to make it easier to keep myself supplied without other players and a populated AH.

**Comment by jackpoz** [comment]
>TC>Security level of account ILLFATED changed to 3.
