### ISSUE TITLE
Can anybody share a launcher on mac of 8.2?Thanks!!!

### ISSUE THREAD

**Issue by liukunr** [TrinityCore/TrinityCore#23628]
compile and install master branch within 2 day,but the doc shows 'the custom launcher not provided'!Can anybody share a launcher on mac of 8.2?Thanks! I've found launchers on wins,but only 8.0 on mac .

**Comment by Aokromes** [comment]
this aint a forum.

**Comment by Shauren** [comment]
Mac clients are unsupported.
