### ISSUE TITLE
Engaging a creature from stealth prevents it to engage correctly

### ISSUE THREAD

**Issue by kelno** [TrinityCore/TrinityCore#23639]
It actually happens with any effect that will cause the threat system to consider you offline (such as being unreachable).
The problem is related to the last engagement changes from here: https://github.com/TrinityCore/TrinityCore/commit/0e7c66cb4c7ff7d44e232d0b50703a48605ffd24

**Steps to reproduce the problem:**

1. Engage creature spawnId 16100 in melee while stealthed

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

(Somewhere yesterday, 25/07/2019)

**Debugging**

This is what usually happens on engage in the normal case with the new logic:
1 - Blablabla stuff happens and we get into ThreatManager::AddThreat
2 - After creating the combat reference in there we call `ref->UpdateOffline();`
3 - This function will call ` _mgr.RegisterForAIUpdate(this);` IF the reference is online only.
4 - ThreatManager::ProcessAIUpdates later handle the engagement if the ref was registered.

Now I don't get why would we register only if the reference is offline in step 3 and not immediately. 
One possible fix would be to move the line:
https://github.com/TrinityCore/TrinityCore/blob/f5978d6d2bce730c31546d180c4c507c24394f41/src/server/game/Combat/ThreatManager.cpp#L77
Just above or below:
https://github.com/TrinityCore/TrinityCore/blob/f5978d6d2bce730c31546d180c4c507c24394f41/src/server/game/Combat/ThreatManager.cpp#L394
instead

**Comment by jackpoz** [comment]
@Treeston could you take a look at this when you have time ?
