### ISSUE TITLE
[3.3.5] Spell Poisonous Blood

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23643]
**Description:**

Spell Poisonous Blood doesn´t work as intended

**Current behaviour:**

Creature [Son of Hakkar](https://classic.wowhead.com/npc=11357/son-of-hakkar) should cast [Poisonous Blood](https://classic.wowhead.com/spell=24320/poisonous-blood) with a cloud effect on death.
smart_scripts is correct here :
```sql
"11357"	"0"	"2"	"0"	"6"	"0"	"100"	"512"	"0"	"0"	"0"	"0"	"0"	"11"	"24320"	"2"	"0"	"0"	"0"	"0"	"1"	"0"	"0"	"0"	"0"	"0"	"0"	"0"	"0"	"Son of Hakkar - On Just Died - Cast 'Poisonous Blood' (No Repeat)"
```
Nothing happens on creatures death.

If you select the creature and .cast [24320](https://classic.wowhead.com/spell=24320/poisonous-blood) the cloud appears but doesn´t apply the [Poisonous Blood debuff](https://classic.wowhead.com/spell=24321/poisonous-blood)
Casting 24321 correctly applies the debuff.

**Expected behaviour:**

Cloud effect from Spell 24320 should be casted on death and should apply Spell 24321 as debuff.

**Steps to reproduce the problem:**

1. .npc add 11357
2. kill
3. nothing happens
--
1. select npc 11357
2. cast .24320 
3. cloud appears but doenst have a effect

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c7be2b1dff089a0321b2de60e9f743c7dfbde2c2

**Operating system:** Windows 10

**Comment by Killyana** [comment]
There's 3 spells:
https://woehead.way-of-elendil.fr/?spell=26744
https://woehead.way-of-elendil.fr/?spell=24320
https://woehead.way-of-elendil.fr/?spell=24321

The spell 24320 is cast by the SAI but the cloud effect is removed as the unit that cast the spell is dead

The spell 24320 require a script to cast 24321 but the target looks wrong
``` sql
DELETE FROM `spell_scripts` WHERE `id`=24320;
INSERT INTO `spell_scripts` (`id`,`effIndex`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(24320,0,0,15,24321,0,0,0,0,0,0);
```
We need to find how this spells are cast

**Comment by Jinnaii** [comment]
With linking this in spell_scripts, the functionality is given - every player close to Son of Hakkar gets the debuff now. The missing cloud is cosmetically i guess.
Thank you Killyana.

**Comment by Killyana** [comment]
The visual effect is related to https://github.com/TrinityCore/TrinityCore/issues/13441
