### ISSUE TITLE
DB/Quest: Test of Endurance - "troll" instead of $r in RewardText

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23648]
**Description:**

After killing [Grenka Bloodscreech](https://www.wowhead.com/npc=4490/grenka-bloodscreech) and looting the quest item [Grenka's Claw](https://www.wowhead.com/item=5843/grenkas-claw) for the quest [Test of Endurance](https://www.wowhead.com/quest=1150/test-of-endurance), then going back to [Dorn Plainstalker](https://wow.gamepedia.com/Dorn_Plainstalker) to hand in the quest, the last quest gossip page states:

"Grenka was powerful, even by **troll** standards. You should be proud of your accomplishment this day. [ ... ]" (followed by the rest of the RewardText gossip you can read below).

- https://www.wowhead.com/quest=1150/test-of-endurance
- https://wow.gamepedia.com/Test_of_Endurance
- https://www.wowhead.com/npc=2986/deprecated-for-4-x-dorn-plainstalker
- https://wow.gamepedia.com/Dorn_Plainstalker
- https://www.wowhead.com/npc=4490/grenka-bloodscreech
- https://wow.gamepedia.com/Grenka_Bloodscreech
- https://www.wowhead.com/item=5843/grenkas-claw

**Current behaviour:**

Current quest gossip on the RewardText page:

![Test of Endurance](https://user-images.githubusercontent.com/38162891/61996742-09f3c900-b098-11e9-88cc-dfd5e0705f10.png)
This gossip was produced using an orc character, not a troll character.

**Expected behaviour:**

The text should refer to the player race to set the relevant context of the NPC in relation to the player race. The text should read:

Grenka was powerful, even by **$r** standards. You should be proud of your accomplishment this day.$b$bDuring your test of faith you displayed strength of spirit, and now you have shown endurance in battle by taking on the Roguefeather harpies, but the time has come for a new test.

**Suggested solution:**
```sql
-- Test of Endurance (1150) / replace "troll" with $r
UPDATE `quest_offer_reward` SET `RewardText`="Grenka was powerful, even by $r standards. You should be proud of your accomplishment this day.$b$bDuring your test of faith you displayed strength of spirit, and now you have shown endurance in battle by taking on the Roguefeather harpies, but the time has come for a new test." WHERE `ID`=1150;
```

**Steps to reproduce the problem:**

1. Use a horde player character **except for a troll**, level 29 (25) or higher.
2. `.quest add 1150` or go to Dorn Plainstalker in the cave in Windbreak Canyon, Thousand Needles, to get the quest from the NPC.
3. `.quest complete 1150` (or travel to the Screeching Canyon on the south side of Thousand Needles, enter the cave and kill Grenka Bloodscreech to get the quest completion item).
4. Go back to Dorn Plainstalker ( `.go creature id 2986` ) to hand in the quest.
5. Read the last page with the reward options, see that it matches my image above.

**Branch(es):**

only 3.3.5 (deprecated/removed in patch 4.0.3a)

**TC rev. hash/commit:** 

TrinityCore rev. b07128b3f668 2019-07-26 02:33:10 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
(issue noticed/discovered on `tcubuntu.northeurope.cloudapp.azure.com` today)
***
Update: installed the Chatter addon to get the `.server debug` information:
TrinityCore rev. b26624b39e8a 2019-07-27 11:13:41 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1b  26 Feb 2019 (library: OpenSSL 1.1.1b  26 Feb 2019)
Using Boost version: 1.67.0
Using MySQL version: 5.7.27
Using CMake version: 3.13.4
Compiled on: Linux 5.0.0-1012-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19071
***

**Operating system:** Game Client: Windows 10 1903 Home x64
Server: Unix/Ubuntu (ask Aokromes or jackpoz for details)

**Comment by Teppic1** [comment]
Wow, this is some report :D

**Comment by illfated** [comment]
Yeah, I know. The requested minimal change does not warrant as much documentation, but I tend to do this anyway, just in case I would happen upon a different issue later where it can be useful. My slight autism also demands that if I do something I know how to do, I should do it thoroughly. ^^
