### ISSUE TITLE
[3.3.5] [Rogue] [Talent] Remorseless Attacks

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23649]
**Description:**

Rogue Talent Remorseless Attacks doesn´t work as intended

**Current behaviour:**

[Remorseless Attacks](https://wotlkdb.com/?spell=14148) doesn´t trigger when you kill a creature with a spell that benefits from Remorseless Attacks such as [Sinister Strike](https://wotlkdb.com/?spell=1752)

**Expected behaviour:**

Remorseless Attacks should always trigger if you kill a target that yields honor or exp.

**Steps to reproduce the problem:**

1. create rogue
2. level up so you can put points in Remorseless Attacks
3. kill a creature that yields honor or exp with Sinister Strike
4. nothing happens

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

c7be2b1dff089a0321b2de60e9f743c7dfbde2c2

**Operating system:** Win10

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/62486358-6e4c1200-b795-11e9-9fba-4169a89ad208.png)


Working fine in 6869dbf1c1f61178d6e252576519931e77678d7d

**Comment by Keader** [comment]
ok, now i can reproduce

**Comment by Keader** [comment]
31b4b897e4938b3f04d53c584b02ab4402132864
