### ISSUE TITLE
[3.3.5] [Core] [Auctionhouse] Wrong calculation in deposit fees - critical

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23656]
**Description:**

~~Player was able to hit Gold cap with the use of auctioneer UI Addon (appraiser function +warmane AHfix as far as i can tell) and running out of money for auction fees.
[Database Screenshot](https://cdn.discordapp.com/attachments/570560647163674643/605033443226812416/DB.jpg) after the gold was splittet over 3 Accounts~~

We were able to pin this down to a problem with deposit fees.
The Person in [this screenshot](https://i.imgur.com/rx43IB0.jpg) added 32 full stack auctions with Rugged Leather. He inserted these Auctions with the Auctioneer interface Addon plus the Warmane AH Fix for Auctioneer.
The Appraiser function is used, that one can mass insert stacks for predefined prices.
The process is really fast. At a certain point your Gold is drained to 0. Seems like the Auctionhouse is trying to take insane deposit fees from you - later you will get back this Gold that it tried to take via mail even if you never really paid it.

**Current behaviour:**

It appears that by mass inserting auctions there is a chance that you pay insane amounts of deposit fees. It will bring you down to 0g0s0c but internal continues to take fees. You later get back insane amount of Gold.

**Expected behaviour:**

Should not happen.

**Steps to reproduce the problem:**

I was not able to reproduce this. Tried with the same Addons, had some situations where strange amounts of fees were taken but in this cases less money than it should.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8da2cd6b3f26d8bd53e1e3503246d00b7161eb5e at that time

**Operating system:** Debian 9

**Comment by Treeston** [comment]
`Player::ModifyMoney` has appropriate underflow checks, and all accesses from `AuctionHouseMgr` go through there.

Multi-threading config values?

**Comment by Shauren** [comment]
AH is not multithreaded

**Comment by Treeston** [comment]
I have managed to reproduce a situation where the full deposit is not taken, but no underflow occurred as expected.

Not sure there's much else we can do without a reliable reproduction.

**Comment by Jinnaii** [comment]
After investigation this problem looks to be AHBot related - it seems possible to force the bot to buy at ridiculous high values on default AHbot settings.
[Picture](https://cdn.discordapp.com/attachments/520258853498257430/604068982257090561/unknown.png)

Since i wasnt able to replicate that eiter, ill close this issue and will reopen another one when i am one step further with this problem.

**Comment by Jinnaii** [comment]
Updated with newest discoveries

**Comment by Shauren** [comment]
Reproduced
