### ISSUE TITLE
[8.2] Client Crash when Inspect a player

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#23651]
**Description:**

Client Crash when Inspect a player

**Current behaviour:**

Client Crash when Inspect a player

**Expected behaviour:**

**Steps to reproduce the problem:**

1. Inspect a player
2. Client Crash

**Branch(es):** master

**TC rev. hash/commit:**  f2ef5f878df7c9536736684251fe86f456fc7590

**Operating system:** Windows 10 x64

**Comment by Faq** [comment]
no log attached

**Comment by MaxtorCoder** [comment]
Won't matter lol. Inspect is missing Essence data. Hence the client crash.
