### ISSUE TITLE
[3.3.5] [Core] Insane damage instead of low/zero

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23655]
**Description:**

We encountered 2 Situations on our Server where a player gets extreme damage.
[Picture 1](https://cdn.discordapp.com/attachments/570560647163674643/605011309460979722/WoWScrnShot_072019_142916.jpg)
[Picture 2](https://cdn.discordapp.com/attachments/570560647163674643/605011310085931037/WoWScrnShot_072319_101401.jpg)

**Current behaviour:**

Instead of dealing low amounts of Damage, creatures suddenly hits for over 1 billion damage.

**Expected behaviour:**

Should not happen ever.

**Steps to reproduce the problem:**

I was not able to reproduce this. Tried under several conditions with compareable skills and items on gmisland with same creatures.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8da2cd6b3f26d8bd53e1e3503246d00b7161eb5e at that time

**Operating system:** Debian 9

**Comment by Treeston** [comment]
![image](https://user-images.githubusercontent.com/14020072/62254450-7f91c900-b3f9-11e9-825b-dc98192cc1fd.png)

Aqua Guardian's really low base damages + Demoralizing Shout + Force of Will trinket. Yup.
