### ISSUE TITLE
[Quest] A Lost Master

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/TrinityCore#23650]
**Description:**
https://classic.wowhead.com/quest=986/a-lost-master
https://classic.wowhead.com/quest=985/how-big-a-threat

**Current behaviour:**
The quest [A Lost Master](https://classic.wowhead.com/quest=986/a-lost-master) is set to check for completion of the second part of [How Big A Threat](https://classic.wowhead.com/quest=985/how-big-a-threat).

**Expected behaviour:**
The quest A Lost Master is available at level 10 regardless of whether you've completed How Big a Threat.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. c7be2b1dff08 2019-07-26 20:02:02 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1  11 Sep 2018 (library: OpenSSL 1.1.1  11 Sep 2018)
Using Boost version: 1.65.1
Using MySQL version: 5.7.27
Using CMake version: 3.10.2
Compiled on: Linux 4.15.0
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/server/data/maps. Total size: 249261353 bytes
vmaps directory located in /home/trinity/server/data/vmaps. Total size: 651656571 bytes
mmaps directory located in /home/trinity/server/data/mmaps. Total size: 1972740216 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19071

**Operating system:** Windows 10 Client / Ubuntu 18.04 Server

**Comment by illfated** [comment]
Are you sure that the quest [A Lost Master](https://www.wowhead.com/quest=986/a-lost-master) is not supposed to require [How Big A Threat (2)](https://wow.gamepedia.com/How_Big_a_Threat%3F_(2)) to be completed?
Comments on wowhead suggests the opposite:
https://www.wowhead.com/quest=986/a-lost-master#comments:id=143152:reply=105928
> [cheekyprincess](https://www.wowhead.com/user=cheekyprincess) [on 2009/06/25](https://www.wowhead.com/quest=986/a-lost-master#comments:id=143152:reply=105928) (Patch 3.1.3)
> Confirmed, How Big A Threat? chain must be completed.

Please note the quest outro in https://wow.gamepedia.com/How_Big_a_Threat%3F_(2)#Completion:
> Cut Scene on completion
> Terenthis says: What was that noise? It sounded like a roar.
> 
> Grimclaw the white bear enters and runs up to Therenthis.
> 
> Grimclaw roars at Terenthis to get his attention.
> 
> Terenthis says: Grimclaw?! Easy there, my friend... where is your master Volcor?
> 
> Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.
> 
> Terenthis says: Whoa, whoa there, my friend. One moment...
> 
> Terenthis begins to cast a spell on Grimclaw.
> 
> Terenthis says: There... that should help. Now, tell me what's happened, Grimclaw.
> 
> Grimclaw roars at Tarenthis more, but this time the druid seems to understand the bear.
> 
> Terenthis says: I understand, my friend. I shall find someone to help your master. Go back to him now, or at least stay close.
> 
> Grimclaw roars in acknowledgement at Terenthis.
> 
> Terenthis says: If you have the time, Grimclaw and his master Volcor could use your help. If you're interested, speak with me further...

"If you're interested, speak with me further..." is a hint that the next quest is related to what just happened.

**Comment by Killyana** [comment]
The quest A Lost Master Description: "<name>, your skills have already helped me in my endeavor"
An many other comments proves the chaining is correct.

**Comment by Wyrserth** [comment]
For future reference, Wowhead only shows quest chains when they're turned in and taken from the same NPC.

For example How Big a Threat? (Part 1) is turned in to Terenthis, and he starts How Big a Threat? (Part 2). You're prompted to accept Part 2 right after you turn in Part 1 (mechanic implemented by quest_template's RewardNextQuest field).

So it doesn't mean that two quests aren't chained only because Wowhead doesn't say so. Always check the comments beforehand, as people usually report what quests are required.

**Comment by jerbookins** [comment]
I referenced a few different sites, none of which indicated a logical step from completing the first chain to the second. For instance, [wowwiki](https://wowwiki.fandom.com/wiki/Quest:A_Lost_Master) always has an indicator for "previous step" and "next step" when chains are involved. They don't indicate there is a prerequisite so that's what made me think it was right to submit an issue. But it looks like you are right, based on the contextual conversation dialogue.

**Comment by illfated** [comment]
Fair point, I have also noticed that some of the quests removed in Patch 4.0.3a (Cataclysm) sometimes don't have the expected link to the required Next quest step, even if the previous one is linked. For wowhead.com this is more the norm than exception for pre-Cata quests, so I hardly ever look there to verify quest chaining. Fandom sites like wowwiki and wowpedia are usually better for that type of linking, but in this specific case, it is a missing link. We simply need to go by the story development here.
