### ISSUE TITLE
Can't attack creatures after looting

### ISSUE THREAD

**Issue by menevia16a** [TrinityCore/TrinityCore#23661]
**Description:**

After killing and looting a creature I'm not able to attack anymore creatures around me.

**Current behaviour:**

On a player account as a level one human warrior I go to attack the worgs/blackrock guys. I kill them, but after I loot a body I'm not able to attack any more creatures until I relog.

**Expected behaviour:**

After killing a creature and looting it I should be able to keep on attacking more creatures without having to log out and back in everytime.

**Steps to reproduce the problem:**

1. Kill a https://www.wowhead.com/npc=49871/blackrock-worg in Northshire Abbey.
2. Loot the dead body.
3. Try to attack another nearby creature that is neutral.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 788d522f3c84+ 2019-07-28 22:09:02 +0200 (master branch) (Win32, Release, Static) (worldserver-daemon) ready...

**Operating system:** Windows 10 x64

**Comment by illfated** [comment]
`<non-factual speculation>`
Sort of funny and interesting problem. For me, without knowing anything about why this happens, it feels like the reverse of being unable to loot because you are stuck in combat. To explain my fiction-based idea, this time you can't start combat because you are stuck in a looting state, but without any looting animation present.
`</non-factual speculation>`

**Comment by menevia16a** [comment]
So after some more testing I found out it is only neutral targets that are affected by this bug.

**Comment by takasi689** [comment]
I think it only affects starting areas for example Blood Elf Sunstrider Isle and after you leave it you can attack hostile targets.
You can kill all creatures but once you loot any kind of item from it it will start that non-attacking bug.

**Comment by illfated** [comment]
Should be solved now (see PR #23666 and commit https://github.com/TrinityCore/TrinityCore/commit/245b6db2025510830d7569bd51e9a7e885443a13 )
