### ISSUE TITLE
Victory Rush wont activate

### ISSUE THREAD

**Issue by menevia16a** [TrinityCore/TrinityCore#23668]
**Description:**

When killing a creature that yields experience or honor Victory Rush should activate.

**Current behaviour:**

When you kill an enemy that gives experience or honor Victory Rush does not activate.

**Expected behaviour:**

Victory Rush should activate for 20 seconds after killing an enemy yielding experience or honor.

**Steps to reproduce the problem:**

1. Make a human warrior level him to level 5
2. Go kill a kobold creature around your level in Elwynn Forest
3. Try to use https://www.wowhead.com/spell=34428/victory-rush after killing that kobold.. It doesn't activate.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 245b6db20255+ 2019-08-01 21:52:13 +0200 (master branch) (Win32, Release, Static)

**Operating system:** Windows 10 x64

**Comment by illfated** [comment]
@Keader : Do you think this could be a proc issue, maybe some proc coding needs to be cherry-picked from 3.3.5 ?

**Comment by Treeston** [comment]
potentially related to #23649

**Comment by Keader** [comment]
Well #23649 is invalid.
I dont have master client / master branch here to check this.

**Comment by Naddley** [comment]
tested on f774c4e - Victory Rush procs after kill a npc which grant exp.
