### ISSUE TITLE
OnGameEvent hook only gets called when event stops, several game events are broken.

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/TrinityCore#23663]
**Description:**

OnGameEvent hook only gets called when event stops.
When a event starts, OnGameEvent doesn't get called.
Breaks Hourly Bells (https://github.com/TrinityCore/TrinityCore/issues/23638)

**Current behaviour:**

doesn't get called on start.

** Reproduce **
breakpoint OnGameEvent of go_bells
event start 73 (doesn't get called)
event stop 73 (it does get called)
stand in a major city to listen to the bells

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

c3619f42a56fb6aaadc15ca63fe95fc0f519428d

**Comment by illfated** [comment]
Thank you for pointing that out. Good to know that there are still people around who knows how to figure out these mysteries.

**Comment by Kittnz** [comment]
@illfated yes, but finding out why it broke is another thing.

**Comment by jackpoz** [comment]
try after https://github.com/TrinityCore/TrinityCore/commit/d9ae19d974a8026b0fd4eb8b1d11fa59c758f5d1

**Comment by Killyana** [comment]
Fixed, thanks.

**Comment by jackpoz** [comment]
@Killyana could you check the SAI scripts with SMART_EVENT_GAME_EVENT_START to confirm that they still work (I wonder if they even worked at all before if they were attached to Creatures/GameObjects spawned by the event itself)

**Comment by Killyana** [comment]
Yes it works fine, just add the creature guid 102700 to the event night 25, then .go c 102700 and .event stop 25 and .event start 25, the npc will start a waypoint upon spawned: Windle Sparkshine - On Game Event 25 Started - Start Waypoint (No Repeat) (Dungeon)

**Comment by Killyana** [comment]
I tested without https://github.com/TrinityCore/TrinityCore/commit/d9ae19d974a8026b0fd4eb8b1d11fa59c758f5d1  and the event "On Game Event " didn't trigger
