### ISSUE TITLE
Allied Races

### ISSUE THREAD

**Issue by vileninja** [TrinityCore/TrinityCore#23665]
**Description:**
Cant create allied races even with the achievements 

**Current behaviour:**

When you add the achievements to be able to create allied races it wont switch from preview to Customize on character creation screen

**Expected behaviour:**

Should change where it says Preview to Customize

**Steps to reproduce the problem:**

1. add the allied race acheivements
2. log out and try to create allied race.

**Branch(es):**

Master

**Operating system:** 
Windows

**Comment by Aokromes** [comment]
#21840
