### ISSUE TITLE
[master] Jade Forest

### ISSUE THREAD

**Issue by ArcaneFox** [TrinityCore/TrinityCore#23677]
**Description:**
Every creature checked with a fresh character. Some of the starter area here is highly phased so I skipped most of these (horde and alliance start ships + serpent heart).
This is just the spawns.

[link](https://gist.github.com/ArcaneFox/ccdb8abcd7061eeab6d2d17c769d6eb7)

**Issues:**
1) Some creatures are not moving (wrong movement type).
2) Most of the critters are still missing.
3) Wrong stats (creature_template?).
4) Some areas are still not spawned.

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/245b6db2025510830d7569bd51e9a7e885443a13

**Comment by illfated** [comment]
@ArcaneFox : Why did you close this? It has been labeled as **[Feedback-PatchFix]** , which means it is accepted as an improvement to the source.

**Comment by ArcaneFox** [comment]
There was no feedback/interst in this so I closed it.

**Comment by Killyana** [comment]
Creature_addon and other data are missing

**Comment by illfated** [comment]
OK, so we should probably reopen this and label it **[Feedback-FixOutdatedMissingWIP]** instead.

@ArcaneFox : 4 days is not a long time to wait for feedback here on any of the TC repositories,
especially now during vacation season. The labels should have been feedback enough to start with.
I suggest we reopen this issue and work towards a more complete solution.
