### ISSUE TITLE
Paladin's Templar's Verdict not working

### ISSUE THREAD

**Issue by menevia16a** [TrinityCore/TrinityCore#23671]
**Description:**

When you have 3 charges of holy power and try to use Templars Verdict it doesn't work.

**Current behaviour:**

When you have 3 charges of holy power, Templar's Verdict lights up. When you go to cast it it plays a short animation but does nothing else not even damage, and doesn't use up any holy power.

**Expected behaviour:**

When you cast Templar's Verdict it should consume 3 charges of holy power and do the holy damage to the target.

**Steps to reproduce the problem:**

1. Level up a paladin to get https://www.wowhead.com/spell=85256/templars-verdict 
2. Use crusader strike on enemys to get up to 3 holy power.
3. Try to unleash Templar's Verdict on an enemy.

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 245b6db20255+ 2019-08-01 21:52:13 +0200 (master branch) (Win32, Release, Static)

**Operating system:** Windows 10 x64

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/18353

**Comment by menevia16a** [comment]
> Dup #18353

You say duplicate but in that issue it says it expends a holy charge. In my issue it doesn't use any holy charges.
