### ISSUE TITLE
[CRASH] .reload creature_template <id> crashes

### ISSUE THREAD

**Issue by menevia16a** [TrinityCore/TrinityCore#23672]
**Description:**

Can't run the .reload creature_template <id> command.

**Current behaviour:**

When the command is run, server immediately crashes.
https://gist.github.com/menevia16a/8c2700eabc935e08449fd593c199d50f

**Expected behaviour:**

Should reload data for the given creature id from the creature_template and say creature_template reloaded.

**Steps to reproduce the problem:**

1. Find an id of a creature in-game using .npc info
2. Run the command .reload creature_template <id> with the given id
3. Server crashes

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 245b6db20255+ 2019-08-01 21:52:13 +0200 (master branch) (Win32, Release, Static)

**Operating system:** Windows 10 x64

**Comment by Killyana** [comment]
It needs a cherry-pick https://github.com/TrinityCore/TrinityCore/commit/12de860b4aefc02cc77b7487ef218fb584cdb552

**Comment by Shauren** [comment]
Nope, its something else, master doesnt have creature_template_movement yet

**Comment by jackpoz** [comment]
@menevia16a please build in Debug mode and post the crashlog, thanks

**Comment by menevia16a** [comment]
Ye np here https://gist.github.com/menevia16a/cc8b68ef2dffdc103df4d067eafec6e5 thanks for your work.

**Comment by jackpoz** [comment]
@Shauren it could be a similar issue, that command has its own query that never gets updated if one doesn't know it exists

**Comment by Shauren** [comment]
This one is fixed long time ago
