### ISSUE TITLE
[3.3.5] Level 1 creatures don't deal damage

### ISSUE THREAD

**Issue by leagueofsoups** [TrinityCore/TrinityCore#23673]
Hi. I have problem like like this:
https://github.com/TrinityCore/TrinityCore/issues/15365
I create human and go to wolf in first location. The wolf attack result miss attack.

uint32 Unit::CalculateDamage
minDamage = GetFloatValue(UNIT_FIELD_MINDAMAGE); # line: 2218 value: 1.54997146 
maxDamage = GetFloatValue(UNIT_FIELD_MAXDAMAGE); # line: 2219 value: 1.61067152

return urand(uint32(minDamage), uint32(maxDamage)); # line: 2236 
omg.. uint32(minDamage) always 1 & uint32(maxDamage) always 1..

Unit::CalcArmorReducedDamage
return uint32(std::max(damage * (1.0f - damageReduction), 0.0f)); #line 1583
p damage * (1.0f - damageReduction) #0.923809528
p (uint32)(damage * (1.0f - damageReduction)) # round to 0

Help me to fix this problem, please.

branch: 3.3.5
commit: c3619f42a56fb6aaadc15ca63fe95fc0f519428d

Problem with creatures with level 1, I think.

**Comment by Wyrserth** [comment]
Changed title to clarify the issue. Only happens with level 1 creatures.

**Comment by illfated** [comment]
Could this be related to the recent solution to avoid damage underflow, causing way too much damage from medium-level NPCs in combat?

**Comment by jackpoz** [comment]
some std::floor and std::ceil could help here

**Comment by leagueofsoups** [comment]
server/game/Entities/Unit/StatSystem.cpp Creature::CalculateMinMaxDamage
    minDamage = ((weaponMinDamage + baseValue) * dmgMultiplier * basePct + totalValue) * totalPct;
    maxDamage = ((weaponMaxDamage + baseValue) * dmgMultiplier * basePct + totalValue) * totalPct;

commit cd76d3290719161db1c10b4c82de191db1cef7e8 contain todo: some creatures need dmg_multiplier update in creature_template

select name,DamageModifier from creature_template where entry=299\G
*************************** 1. row ***************************
          name: Diseased Young Wolf
DamageModifier: 1

I think require change it value, but no idea how to calculate it.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a0d508885000327f23b9c04ed454d513aec91fa1

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9c9f4d6d20adf7e95ae1a44dc72b6530c3fc0bff too
