### ISSUE TITLE
[3.3.5] Spell Rabies 

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23682]
**Description:**

Creature Spell [Rabies](https://classic.wowhead.com/spell=3150/rabies#used-by-npc) doesn't work correctly.

**Current behaviour:**

[Rabies](https://classic.wowhead.com/spell=3150/rabies#used-by-npc) cant be removed from players.

**Expected behaviour:**

Spells like [Cure Disease](https://classic.wowhead.com/spell=28133/cure-disease) should be able to remove it.

**Steps to reproduce the problem:**

1. get a char with Cure Disease or something similar (or .learn spell 28133)
2. get infected with Rabies by a creature like [Rabid Dire Wolf](https://classic.wowhead.com/npc=565/rabid-dire-wolf) (or .aura 3150)
3. cast Cure Disease

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0b972a8bf38a75cdb8213d5371a4cd5231180d73

**Operating system:** Debian9

**Comment by Killyana** [comment]
It get dispelled by 2871 but not with spell=1152 or spell=552

**Comment by adeutscher** [comment]
I was not able to reproduce this directly using `.aura 3150`.

I was able to reproduce this fighting a rabid creature. 3150 is still getting applied, but the enemy NPC is applying it as a positive buff. When checking castability, Cure Disease must only check for debuffs.

The fix will be tracking down why Rabies is getting applied as a buff when cast by an NPC.

**Comment by Killyana** [comment]
Yes, fixed

**Comment by Killyana** [comment]
But considered as buff, @Keader Does this need to be fixed in SpellMgr?

**Comment by Keader** [comment]
> But considered as buff, @Keader Does this need to be fixed in SpellMgr?

SpellInfo.cpp, where we check positive/negative spells

**Comment by Jildor** [comment]
this happens because SPELL_AURA_MOD_HEALTH_REGEN_PERCENT isn't checked as negative, so when apply the spell to the victim appear positive regardless of whether the other two effects are negative, same issue as: #24899

**Comment by Jildor** [comment]
can be closed ;)

**Comment by Jinnaii** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/af1571ce508379895fb4f8f4fbcaccf7c5dbd156
