### ISSUE TITLE
Only little help to change instance requeriments

### ISSUE THREAD

**Issue by HarkonnenATR** [TrinityCore/TrinityCore#23686]
I am new to this and I am trying to help "my" server developers, and I don't know how to start, I speak very badly I know ...
we are in 5.4.8 (real 5.0 without 5.1) and we cannot go to ulduar, or naxx with pj lvl 80, the instance says we need lvl 90 at 25,but not in 10 (wtf?)... How can our developers easily change it? I would greatly appreciate it if you could help me
_________________________________<3

**Comment by Treeston** [comment]
asking for help -> forums/irc/discord

github issues are not a discussion forum
