### ISSUE TITLE
opcode from log

### ISSUE THREAD

**Issue by Rokmusic** [TrinityCore/TrinityCore#23680]
**Not handled opcode and other:**

CHANGEME Description of the problem or issue here.

**with opcode:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**without opcode)**

CHANGEME Tell us what should happen instead.

**Have in server log:
Received not handled opcode [CMSG_QUERY_COUNTDOWN_TIMER 0x31A8 (12712)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS 0x32B5 (12981)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_DF_GET_JOIN_STATUS 0x3614 (13844)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_REQUEST_LFG_LIST_BLACKLIST 0x32A5 (12965)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_LFG_LIST_GET_STATUS 0x360B (13835)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_GARRISON_REQUEST_LANDING_PAGE_SHIPMENT_INFO 0x32F0 (13040)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
Received not handled opcode [CMSG_CHALLENGE_MODE_REQUEST_MAP_STATS 0x308F (12431)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
CMSG_DB_QUERY_BULK: [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5] requested unsupported unknown hotfix type: 3386291891
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x338F (13199)] from [Player: Rokmusic GUID Full: 0x08000400000000000000000000000002 Type: Player Entry: 0 Low: 2, Account: 5]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for GUID Full: 0x200004000000B440000000000000007C Type: Creature Entry: 721 Low: 124 Entry: 721
**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**master :**

CHANGEME 3.3.5, master or both

**TC rev from 28.07.2019 (sorry)** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Win 10 x64 1803:** CHANGEME OS

**Comment by Rokmusic** [comment]
![wow](https://user-images.githubusercontent.com/47774473/62436962-a9a7fb80-b717-11e9-9da9-2c65cbd226de.jpg)

**Comment by Aokromes** [comment]
duplicate.
