### ISSUE TITLE
[Crash] Crash

### ISSUE THREAD

**Issue by frozen4** [TrinityCore/TrinityCore#23692]

**Comment by Shauren** [comment]
Crash log really isn't helping, the stack trace is all kinds of broken
StopNetwork? Is this a shutdown crash? Would help knowing what were you doing ingame (perhaps specific size packets trigger it?)

**Comment by frozen4** [comment]
crash on 
https://github.com/TrinityCore/TrinityCore/blob/da5531f013f6ba8e9beb05b96d46bb05a552a4f1/src/server/game/Server/WorldSocket.cpp#L553

**Comment by Shauren** [comment]
That tells me nothing, I need to know how you triggered it (lets be realistic here, telling me to "login and run around" is not something worth anyones time unless you can guarantee that it will always reproduce it doing that in less than 1 minute)

**Comment by jackpoz** [comment]
>TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch)

it's usually a good start to fix this part so that is says the git commit hash too

**Comment by illfated** [comment]
Usually, the best way to make sure the git commit hash gets included is to use a Git client to clone the source code, use CMake and then build the core.

**Comment by frozen4** [comment]
[worldserver.exe_2019-08- 9_08-30-45.txt](https://github.com/TrinityCore/TrinityCore/files/3485046/worldserver.exe_2019-08-.9_08-30-45.txt)

**Comment by illfated** [comment]
Seeing that you simply pasted a link to the identical file again, with the exact same information
as in your opening comment, I guess you find it too hard to use Visual Studio, CMake & Git.
Maybe you could try the AppVeyor build artifact core files instead?
Those are continuously built from the current source:
- https://ci.appveyor.com/project/DDuarte/trinitycore/branch/master/artifacts
