### ISSUE TITLE
At [quest=11636|Magic Carpet Ride] in the [Borean Tundra] [npc=25465|Kel'Thuzad] attack flying players.

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#23695]
3.3.5
windows 7
all updates and sql.
910da94d20ae1d6a0bc0d9053e46e698c4da50f9

The quest to ride on the magical rug, however one is attacked when fly by Kel'Thuzad and at least in my case hit for 5k, of course I do not hold out and am directly dead.

false:
![WoWScrnShot_080719_210916](https://user-images.githubusercontent.com/321832/62666037-f8f16480-b981-11e9-9a4c-1957712f91f2.jpg)
![WoWScrnShot_080719_210909](https://user-images.githubusercontent.com/321832/62666039-fc84eb80-b981-11e9-80a1-06dcc98ad3d0.jpg)

right
https://www.youtube.com/watch?v=4pEhwaLoCGU

**Comment by Azland** [comment]
Appears to be an issue with Kel'Thuzads AI, rather than anything quest specific.
If you stood near him on Retail he'd ignore you. See https://www.youtube.com/watch?v=RQWNsM2pxtI and other similar vids.

He's currently set up with 'AIName': 'SmartAI' so he attacks you from a considerable distance, including on the Magic Carpet. Removing the 'SmartAI' resolves this.
`UPDATE WORLD.CREATURE_TEMPLATE SET AINAME = '' WHERE ENTRY = '25465'`

According to one of the comments on here, you couldn't even attack him if you wanted to though: https://www.wowhead.com/npc=25465/kelthuzad#comments


What I've also noticed in these vids though is that he passively casts a spell which hits nearby minions. That isn't happening currently. As well as this, changing him from 'SmartAI' to whatever else removes his spellcasting - which was apparently in retail according to that same wowhead page. 


We'd need him passive/ untargetable - but still casting spells. Something like TotemAI?

**Comment by illfated** [comment]
issue title suggestion: **Creature/AI: Kel'Thuzad (25465) in Borean Tundra attacks players in range**

**Comment by Azland** [comment]
Ok so based on these comments I'd say there's two problems. https://www.wowhead.com/npc=25465/kelthuzad#comments
1. Soul Flay range is too high
2. Kel'Thuzad can be attacked

So reducing the range to around 12 yards, and ensuring Kel'Thuzad can't attack/ be attacked to seems to do the trick. 

- He can't be attacked, but will knock you back with Soulflay if you get too close (roughly the same distance as I can see in the Retail WOTLK vids)
- He continues casting Unholy Frenzy on nearby mobs
- You can happily fly a carpet past him


Suggested fix:
`UPDATE world.creature SET unit_flags = '320' WHERE guid = '107121' AND id = '25465';
UPDATE world.smart_scripts SET target_param1 = 12 WHERE entryorguid = '25465' AND id = '2'`

I've tested locally. Can anyone confirm?

**Comment by illfated** [comment]
If something needs to be changed permanently for a creature, doesn't that belong either in `creature_template` or `creature_template_addon` ?
BTW, TC uses bit-wise add/subtract for flag modifications in SQL queries, to show what is added or subtracted.

**Comment by Azland** [comment]
Hey @illfated, cheers for the feedback. I'm new here so this is very useful.

You're absolutely right on the template, my bad. The flag update to be in creature_template instead of creature.

`UPDATE world.creature_template SET unit_flags = '320' WHERE guid = '107121' AND id = '25465';`

But are you suggesting I write it in as the sum of 64 and 256? I couldn't see any examples of this in the SQL Guidelines but I'll have a read.

As for the world stuff - I'll look into that also.

Thanks!

**Comment by illfated** [comment]
Example of bitwise addition:
```sql
UPDATE `smart_scripts` SET `event_flags`=`event_flags`| 512 WHERE `entryorguid`= 2743000;
```
Example of bitwise subtraction:
```sql
UPDATE `creature_template` SET `type_flags`=`type_flags`&~134217728 WHERE `npcflag`>16 AND `gossip_menu_id`!= 0 AND `type_flags`&134217728;
```

**Comment by Killyana** [comment]
unit_flags=768 in sniffs

**Comment by illfated** [comment]
Looks like the current `unit_flags` value is 0, which does not match that sniff value:
```sql
SELECT * FROM `creature_template` WHERE `entry`=25465;
```
```
entry  difficulty_entry_1  difficulty_entry_2  difficulty_entry_3  KillCredit1  KillCredit2  modelid1  modelid2  modelid3  modelid4  name        subname  IconName  gossip_menu_id  minlevel  maxlevel     exp  faction  npcflag  speed_walk  speed_run   scale    rank  dmgschool  BaseAttackTime  RangeAttackTime  BaseVariance  RangeVariance  unit_class  unit_flags  unit_flags2  dynamicflags  family    type  type_flags  lootid  pickpocketloot  skinloot  PetSpellDataId  VehicleId  mingold  maxgold  AIName   MovementType  HoverHeight  HealthModifier  ManaModifier  ArmorModifier  DamageModifier  ExperienceModifier  RacialLeader  movementId  RegenHealth  mechanic_immune_mask  spell_school_immune_mask  flags_extra  ScriptName  VerifiedBuild
-----  ------------------  ------------------  ------------------  -----------  -----------  --------  --------  --------  --------  ----------  -------  --------  --------------  --------  --------  ------  -------  -------  ----------  ---------  ------  ------  ---------  --------------  ---------------  ------------  -------------  ----------  ----------  -----------  ------------  ------  ------  ----------  ------  --------------  --------  --------------  ---------  -------  -------  -------  ------------  -----------  --------------  ------------  -------------  --------------  ------------------  ------------  ----------  -----------  --------------------  ------------------------  -----------  ----------  -------------
25465                   0                   0                   0            0            0     23214         0         0         0  Kel'Thuzad                                  0        83        83       2     1982        0           1    1.14286       1       3          0            2000             2000             1              1           1           0         2048             0       0       6          36       0               0         0               0          0        0        0  SmartAI             0            1             480           600              1              35                   1             0           0            1               8388624                         0           64                      12340
```
This is from my local DB based on commit 1c2b1cbba82f :
```
core_version                                                                                            core_revision  db_version     cache_id
------------------------------------------------------------------------------------------------------  -------------  -------------  --------
TrinityCore rev. 1c2b1cbba82f 2019-08-11 13:56:42 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)  1c2b1cbba82f   TDB 335.19071     19071
```
I presume that a partial solution will be something like this:
```sql
-- Kel'Thuzad (25465)  in Borean Tundra
UPDATE `creature_template` SET `unit_flags` = `unit_flags`| 768 WHERE `entry`=25465;
```

**Comment by Azland** [comment]
So in summary - is the following on the right lines?
```sql
-- Kel'Thuzad (25465) in Borean Tundra
UPDATE `creature_template` SET `unit_flags` = `unit_flags`| 768 WHERE `entry`=25465;
UPDATE `smart_scripts` SET `target_param1`= 12 WHERE `entryorguid`= 25465 AND `id`=2;

**Comment by illfated** [comment]
OK, so for those who don't have the entries at hand, I will list them here:
```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid`=25465;
```
```
entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  event_param5  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_param4  target_x  target_y  target_z  target_o  comment
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  -------------  --------  --------  --------  --------  -------------------------------------------------
      25465            0       0       1           1                 0           100            0          3000          6000         27000         29000             0           11          50312             32              0              0              0              0            1              0              0              0              0         0         0         0         0  Kel'Thuzad - Out of Combat - Cast 'Unholy Frenzy'
      25465            0       1       0          61                 0           100            0             0             0             0             0             0            4           8818              0              0              0              0              0            1              0              0              0              0         0         0         0         0  Kel'Thuzad - Out of Combat - Play Sound 8818
      25465            0       2       0           1                 0           100            0             0             0          2000         10000             0           11          50319              0              0              0              0              0           21             70              0              0              0         0         0         0         0  Kel'Thuzad - Out of Combat - Cast 'Soul Flay'
```
Seeing that there are only 3 rows (0, 1, 2) I see that `target_type`=21 (`SMART_TARGET_CLOSEST_PLAYER`) and that `target_param1`= `maxDist` (currently 70).
Do we have any way to verify the correct expected/intended distance here, or is 12 simply a comfortable distance you happened to pick?

**Comment by Azland** [comment]
Hey - the 12 yards is just a guesstimate based on the wowhead and videos I've linked above.

**Comment by illfated** [comment]
Fair enough. Please note that one of the goals for TrinityCore is to get as accurate information as possible, either from sniffs or by testing live Blizzard servers to see if it is possible to measure it some other way (maybe via addons or something else), if it is not possible to get sniff data. Is this Borean Tundra event still available on retail?

**Comment by illfated** [comment]
TrinityCore rev. 4913edf81bfb 2020-01-15 20:00:46 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.1c  28 May 2019)
Using Boost version: 1.67.0
Using MySQL version: 8.0.18
Using CMake version: 3.13.4
Compiled on: Linux 5.3.0-1009-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20011

Still the same issue. Player character level 71 gets shot down before getting across the Plains of Nasam:
```mysql
[22:46:19] Kel'Thuzad's Soul Flay hits Zogzog for 5471 Shadow.
[22:46:19] Kel'Thuzad's Soul Flay hits Amazing Flying Carpet for 5403 Shadow.
[22:46:19] Kel'Thuzad's Soul Flay hits Zogzog for 3771 Shadow.(1075 Overkill)
[22:46:19] Zogzog's Aspect of the Hawk fades from Zogzog.
[22:46:19] Zogzog died.
```

**Comment by illfated** [comment]
@Killyana : Would https://github.com/TrinityCore/TrinityCore/issues/23695#issuecomment-521358809 by @Azland be a practical solution?
```sql
-- Kel'Thuzad (25465) in Plains of Nasam
UPDATE `creature_template` SET `unit_flags` = `unit_flags`| 768 WHERE `entry`=25465;
UPDATE `smart_scripts` SET `target_param1`=12 WHERE `entryorguid`= 25465 AND `id`=2;
```

**Comment by offl** [comment]
```sql
AND `source_type`=0

**Comment by illfated** [comment]
Fair enough. Continued, by @Azland :
```sql
-- Kel'Thuzad (25465) in Plains of Nasam
UPDATE `creature_template` SET `unit_flags`=`unit_flags`|768 WHERE `entry`=25465;
UPDATE `smart_scripts` SET `target_param1`=12 WHERE `entryorguid`=25465 AND `id`=2 AND `source_type`=0;
