### ISSUE TITLE
[3.3.5] DB/Stacks: Mage - Icy Veins stack

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23709]
**Description:**

ID - 12472 Icy Veins
https://wowwiki.fandom.com/wiki/Icy_Veins?oldid=2226468
>Icy Veins does stack with Bloodlust and Heroism buffs from shamans, and Power Infusion from priests.

http://talesofapriest.com/re-revisiting-power-infusion-in-wrath/
>Frost/Arcane mages: Icy Veins DOES stack with PI. Arcane Power DOES NOT. Some of the confusion regarding AP comes from what happens when casting this on a mage with this active: If you cast PI when AP is already active, you receive “A more powerful spell is already active” error. If you cast PI and THEN the mage casts AP, PI is over written.

https://youtu.be/RrLZgI9D_24?t=164 <- min 2:50 Icy veins stacks with Bloodlust

Commit: https://github.com/TrinityCore/TrinityCore/commit/4c2f7df4f39cd98eae21bc64ebac59e3d2eea577 of @Keader put Icy Veins in this group, but this is wrong on wotlk version, Icy Veins shouldn't stack in TBC, but, in Wotlk should stack with the others buffs ;)

**Fix:**
```sql
DELETE FROM `spell_group` WHERE `id`=1122 AND `spell_id`=12472;
```
**Branch(es):** 3.3.5

**TC rev. hash/commit:** 3d356b97d4cc4c7ec4c641487241eae6dcc0558e

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/af874a211c0f064bd685cddeded3ca7d6d690e8f
