### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Knowledge62** [TrinityCore/TrinityCore#23708]
Description:
I followed the tutorial: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977309/Linux+Core+Installation

Current behaviour:
cmake // : https://github.com/Knowledge62/Compilation-Error/blob/master/cmake
 make // : https://github.com/Knowledge62/Compilation-Error/blob/master/compilation

Expected behaviour:
The 10/08/19 I compile several times it works very well there was 0 bug

Steps to reproduce the problem :
git clone -b 3.3.5 git://github.com/TrinityCore/TrinityCore.git
cd TrinityCore
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/root/wow/server
make

Branch(es):3.3.5

Operating system:Debian 9

**Comment by jackpoz** [comment]
you should follow the template when creating an issue, your report is missing a lot of informations https://github.com/TrinityCore/TrinityCore/issues/new

**Comment by Shauren** [comment]
@Treeston 
You need to remove `constexpr` from function signature (until `if constexpr` becomes a thing) https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/common/Utilities/advstd.h#L113
Currently compiler tries to evaluate both branches and it goes horribly wrong

**Comment by Treeston** [comment]
smh c++17 when

**Comment by Treeston** [comment]
31b5632 take that silly compilers

**Comment by Knowledge62** [comment]
i remove constexpr 
that's what I get
https://github.com/Knowledge62/Compilation-Error/blob/master/1error

**Comment by illfated** [comment]
Please try again with updated master branch from TC head.

**Comment by Treeston** [comment]
also 7378bcb for real this time

**Comment by illfated** [comment]
Thank you, next.

**Comment by Treeston** [comment]
0a40252 3750c1c compilers are a pain, but now it's done

**Comment by Knowledge62** [comment]
i try @Treeston

**Comment by Knowledge62** [comment]
It's over 15% for the moment it works

**Comment by Knowledge62** [comment]
It's Works ! Thank you 🥇
