### ISSUE TITLE
[3.3.5] Mage Blink collision

### ISSUE THREAD

**Issue by ArgonHC** [TrinityCore/TrinityCore#23706]
**Description:**

The spell of the mage Blink does not teleport the player further, if he should look in the direction of a hill. Example: Orgrimmar next to the bank.

**Current behaviour:**

The magician teleports himself until the first small collision.

**Expected behaviour:**

The mage should be teleported up to a certain point on the hill. But not on a building for example.

**Steps to reproduce the problem:**

1. Create a Mage
2. Learn Blink (ID: 1953)
3. Go to Orgrimmar or another point where the terrain is uneven and blink yourself.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4211645834c4 2019-08-10 21:34:51 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0k  28 May 2019 (library: OpenSSL 1.1.0k  28 May 2019)
Using Boost version: 1.62.0
Using MySQL version: 10.1.38-MariaDB
Using CMake version: 3.7.2
Compiled on: Linux 4.9.0-9-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8086
Realmlist (Realm Id: 2) configured in port 8086
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/data/maps. Total size: 251987687 bytes
vmaps directory located in /home/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/data/mmaps. Total size: 1997885640 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19071

**Operating system:** Linux/Debian9.9

**Comment by Killyana** [comment]
Dup #20006
