### ISSUE TITLE
[3.3.5] area_spell is broken for quests

### ISSUE THREAD

**Issue by 0x416c69** [TrinityCore/TrinityCore#23718]
**Description:**

There are some area spells which are actually using **ZoneID** instead of **AreaID**
For example take the quest "Into the Realm of Shadows" (ID: 12687), when you accept the quest it supposed to cast spell id 52693 instantly but it will not, because in spell_area table it used zoneID (**and it has to** use zoneID because area is so small for that quest)

**Current behaviour:**

SendQuestUpdate only searches for spells based on areaID.
```cpp
void Player::SendQuestUpdate(uint32 questId)
{
    uint32 zone = 0, area = 0;
    GetZoneAndAreaId(zone, area);

    SpellAreaForQuestAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForQuestAreaMapBounds(**area**, questId); // <-- why area only???

    if (saBounds.first != saBounds.second)
    {
        for (SpellAreaForQuestAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
        {
            if (!itr->second->IsFitToRequirements(this, zone, area))
                RemoveAurasDueToSpell(itr->second->spellId);
            else if (itr->second->autocast)
                if (!HasAura(itr->second->spellId))
                    CastSpell(this, itr->second->spellId, true);
        }
    }

    UpdateVisibleGameobjectsOrSpellClicks();
}
```

The commit that breaks the system and made this bug:
https://github.com/TrinityCore/TrinityCore/commit/d7e47de264a20dc689b4b30663c2de09613b791f#diff-5589ee47b3a7ad220cff105a8fe7eac3R15743

**Expected behaviour:**

It supposed to check for zoneID too, as it does in SpellArea::IsFitToRequirements function.
Proof: (https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Player/Player.cpp#L23933)
```cpp
void Player::UpdateZoneDependentAuras(uint32 newZone)
{
    // Some spells applied at enter into zone (with subzones), aura removed in UpdateAreaDependentAuras that called always at zone->area update
    SpellAreaForAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForAreaMapBounds(newZone);
    for (SpellAreaForAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
        if (itr->second->autocast && itr->second->IsFitToRequirements(this, newZone, 0))
            if (!HasAura(itr->second->spellId))
                CastSpell(this, itr->second->spellId, true);
}

void Player::UpdateAreaDependentAuras(uint32 newArea)
{
    // remove auras from spells with area limitations
    for (AuraMap::iterator iter = m_ownedAuras.begin(); iter != m_ownedAuras.end();)
    {
        // use m_zoneUpdateId for speed: UpdateArea called from UpdateZone or instead UpdateZone in both cases m_zoneUpdateId up-to-date
        if (iter->second->GetSpellInfo()->CheckLocation(GetMapId(), m_zoneUpdateId, newArea, this, false) != SPELL_CAST_OK)
            RemoveOwnedAura(iter);
        else
            ++iter;
    }

    // some auras applied at subzone enter
    SpellAreaForAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForAreaMapBounds(newArea);
    for (SpellAreaForAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
        if (itr->second->autocast && itr->second->IsFitToRequirements(this, m_zoneUpdateId, newArea))
            if (!HasAura(itr->second->spellId))
                CastSpell(this, itr->second->spellId, true);
}
```

**Steps to reproduce the problem:**

1. create dk class
2. get quest from Salanar the Horsemen (Into the realm of shadows quest id: 12687)
3. you will see that the spell will not cast on you and you have to get that aura using gossip menu or change your area so it triggers onZone/AreaChange event

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

43c08b176115505b76c027667047f9a5bfcc4e11

**Operating system:** 

Win32 (x64)

P.S. such an important bug exists for a long time, did not anyone find it yet? WOW

**Comment by Killyana** [comment]
Confirm, if I change thee area to 4356 the spell will be auto cast on quest accept, but with the zone ID you must move to an other area from the same zone to trigger the spell cast.

**Comment by 0x416c69** [comment]
Yeap, will make the PR to fix it in a min.

**Comment by illfated** [comment]
I was wondering what quest 52693 is for a moment (until I checked wowhead, https://www.wowhead.com/quest=52693/tinny-needs-help), but then I noticed you also wrote "spell 52693" (https://www.wowhead.com/spell=52693/realm-of-shadows). No big deal, I just got confused by the steps to reproduce.

**Comment by 0x416c69** [comment]
Yeah, my bad.

Quest id 12687
Both quest and spell literally have the same name.

**Comment by Aokromes** [comment]
92d83c3
