### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Frayre** [TrinityCore/TrinityCore#23713]
Description:

Build Failed

Current behaviour:

Source downloaded Aug 13 2019. Ran C-Make as usual no errors there. Opened the project Selected Release, started build and Failed. 

Errors in build Log Below. 
![error2](https://user-images.githubusercontent.com/10250125/62955257-ba630c00-bdbe-11e9-961d-0a4e465b0beb.PNG)
![error](https://user-images.githubusercontent.com/10250125/62955261-bc2ccf80-bdbe-11e9-81b5-37116bc25631.PNG)

Expected behaviour:

Compared this build to a previous build and there is a Scripts.lib in SRC\Server\Scripts\Release. however in today's Build that file does not exist. 

Branch(es):

3.3.5

Operating system: Windows 10 (1809)

**Comment by illfated** [comment]
Without the actual commit revision hash, it is difficult to give advice, because we don't know if you are using the latest build from this site.

**Comment by Frayre** [comment]
* TrinityCore revision   : 95284b23d1e4 2019-08-13 08:55:00 -0300 (3.3.5 branch)

This Help?

**Comment by illfated** [comment]
Yes, thank you, it helps us to see that there is only 1 new commit after yours, which in theory should not make much change for your issue.
It also helps us to see that your build is verified without any changes to the source.
What is your compiler type and version?

**Comment by Frayre** [comment]
It is indeed Visual Studio 
![VS](https://user-images.githubusercontent.com/10250125/62962005-f486da80-bdcb-11e9-96f2-0cad7766a7e2.PNG)

**Comment by Killyana** [comment]
Update VS 2017  to 15.9.14 and try again, or upgrade to 2019

**Comment by illfated** [comment]
Very good point. There has been some new commits yesterday which made changes to the VS2017 version requirements. Not sure if that is easy to notice, but if you download and install the new version, there should not be a compiling issue. See if updating your current installation is possible, either from within Visual Studio itself, or by installing the new version from https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15 .

**Comment by Frayre** [comment]
So i updated Visual Studio and that seems to have fixed it. Thanks for all the help!

**Comment by illfated** [comment]
Thank you for confirming the solution. I can't promise when I get time to update it myself (currently no internet at home), but I hope someone with spare time will be able to edit and write the specific version needed.

**Comment by Aokromes** [comment]
wiki updated to 15.7 since idk what's the minimum version and we had plans to deprecate any build under that after summer.
