### ISSUE TITLE
Core/Creature: Npc doesn't update position if the target is behind a wall

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23724]
**Description:** If you manage to put something between you and a creature wile fighting it will not be able to hit you on melee, it will not update position.
https://imgur.com/a/be3tsuD

**Steps to reproduce the problem:**

1. .go c id 36626 (Don't test in 10 nm)
2. Start the combat and kill the boss once Putricide in position in the balcony and the door is closed
3. Do the same for .go c id 36627
4. Wait until Putricide reset to the table and start the combat
5. Manage to have the table or a wall between you and the boss like in this pictures https://imgur.com/a/be3tsuD

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. c4cce31a13b2

**Comment by MrSmite** [comment]
Does he have a proper chase movement assigned?

**Comment by jackpoz** [comment]
Fixed, please test (I did test Putricide around the table and it was much much better)

**Comment by Killyana** [comment]
Looks fine, could be test on Putricide with:
.go c id 36678
.mod fac 14 0 0
And try to hide behind something in the room.
