### ISSUE TITLE
[3.3.5] Olrun the Battlecaller is floating and cannot be accessed (PathFinder broken)

### ISSUE THREAD

**Issue by 0x416c69** [TrinityCore/TrinityCore#23720]
**Description:**

First of all, olrun the battlecaller (npcid: 29047) is a dk quest giver npc, it's floating in the air and moving around but her Z is so much high that no one can actually get the quest normally from gossip menu.

**Current behaviour:**

Its Z is 159 now in waypoint_data. (pathid = 1287390)

**Expected behaviour:**

It should use the same Z used to spawn on creature table which is 154.61.
**Funny thing is** when we set it to 154.61 while pathFinding (mMaps) is enabled she'll go crazy, she will go through ground and change her waypoint in an odd way.

Maybe we need to set a new movement_type in waypoint_data table to ignore pathFinding?

**Steps to reproduce the problem:**

1. Make a dk hero
2. go to creature 29047

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a054ce864d29127cef2cb68e1c19328e28e5e90b

**Operating system:** 

Win32 (x64)

**Comment by 0x416c69** [comment]
I can fix this by adding a new movement_type and a line of code so it does not use pathfinding (mmaps) anymore for this creature but I want to know if it's the right fix for it.

**Comment by Killyana** [comment]
This will fix the issue:
``` sql
UPDATE `waypoint_data` SET `position_z`= 155 WHERE `id` IN (1287390); 
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|536870912 WHERE `entry` = 29047;

**Comment by 0x416c69** [comment]
Why `position_z`= 155 by the way?
Why not 154.61?

**Comment by illfated** [comment]
Too close to the ground, I guess. Even 0.5 f might be all the diff needed between walking/flying on/in the ground and flying in hover height.

**Comment by 0x416c69** [comment]
So spawn position Z (in creature table) also better be changed.

**Comment by illfated** [comment]
Well, spawn position is often verified by sniff data (I have no idea if this is the case here).
