### ISSUE TITLE
Starting of worldserver 31429 makes error.

### ISSUE THREAD

**Issue by woodystar** [TrinityCore/TrinityCore#23732]
**Description:**

Master-Version 31478 compiled successfully.
Starting of worldserver makes error.
31339 runs well.

**Current behaviour:**

TrinityCore rev. a778f757836f 2019-08-22 13:45:11 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/---/server820/etc/worldserver.conf.
Using SSL version: OpenSSL 1.0.2s  28 May 2019 (library: OpenSSL 1.0.2s  28 May 2019)
Using Boost version: 1.62.0
Updating Auth database...
>> Auth database is up-to-date! Containing 4 new and 132 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 88 archived updates.
Updating World database...
>> World database is up-to-date! Containing 94 new and 2603 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 2 new and 168 archived updates.
Realm running as realm ID 1
Using World DB: TDB 820.19071
Using deDE DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 19071
Hotfix cache version set to: 0
Using DataDir /home/---/server820/data/
WORLD: MMap data directory is: /home/---/server820/data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: /home/---/server820/data/vmaps
Initialize PlayerDump...
>> Initialized 369 PlayerDump ColumnDefinitions in 51 ms.
Loading Trinity strings...
>> Loaded 966 trinity strings in 1 ms
Initialize data stores...
Speicherzugriffsfehler

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

master 8.2.0.31429

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

Debian GNU/Linux 9 \n \l
Linux version 4.9.0 (mockbuild@builder8.eng.sw.ru) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed May 15 09:45:34 MSK 2019

**Comment by MaxtorCoder** [comment]
Wat

**Comment by Shauren** [comment]
Theres no error here that I can see

**Comment by woodystar** [comment]
the error is : Speicherzugriffsfehler

**Comment by woodystar** [comment]
... segmentation fault (leo.org)

**Comment by woodystar** [comment]
nothing more in log files.
is it possible to run as debug compile?

**Comment by illfated** [comment]
If you want to report a crash (e.g. segmentation fault), you should definitely compile in debug mode and post the full crash log (gist page) from the debug build.
