### ISSUE TITLE
[BfA] Connection Glue Error 017

### ISSUE THREAD

**Issue by Keldo** [TrinityCore/TrinityCore#23733]
Client Glue Error 017

Client fails to connect with the BLZ51901017 Error

**Current behaviour:**

Isolated Wow.exe to its own directory, changed Portal to local lab server, launched, on connect I get the 017 Error.

**Expected behaviour:**
Client should connect with no issues

**Branch(es):**
BfA

Master

**TC rev. hash/commit:** 
a778f75

**Operating system:** Debian Linux

Not sure if this has happened before as I cannot find it in open or closed issues.

> 8/23 10:09:26.457  Connection Initialize
8/23 10:09:43.834  Glue Start Login
8/23 10:09:43.834  BattleNet Attempt Logon
8/23 10:09:44.714  BattleNet Front Disconnected
8/23 10:09:44.714  Glue Fatal Error: 1017
8/23 10:09:44.719  BattleNet Defer Disconnect
8/23 10:11:37.007  Connection Destroy

**Comment by Aokromes** [comment]
you are using the custom (non provided) launcher no?

**Comment by MaxtorCoder** [comment]
You have to use the Arctium Custom Connection launcher in order to connect to your server.
