### ISSUE TITLE
[Quest] Plug The Sinkholes

### ISSUE THREAD

**Issue by Duratans** [TrinityCore/TrinityCore#23730]
The quest "Plug The Sinkholes is not possible to complete. Because the "Incendiary Explosive" Quest item has no area of effect, when pressing "use" it does nothing

**Current behavior:**
"Incendiary Explosive" quest item has no area of effect thus cannot cover holes, the item in question does nothing.

**Expected behaviour:**
"Incendiary Explosive" quest item should cover the holes.

**Steps to reproduce the problem:**

1. go creature 116619
2. quest add 11897
3. Locate 2 holes on the map
4. Try using the quest item and see the issue

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/70721a9414151021ae33d8a810002991aa1f608e
**Operating system:**
Windows Server 2012 x 64

**Comment by Killyana** [comment]
There's 2 issues here:

1- EnterEvadeMode(); is no longer calling Reset() that Initialize() the phase : https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_borean_tundra.cpp#L151
changing EnterEvadeMode(); to Reset(); fix it, but looks like a generic issue that must be fixed somewhere else.

2- If a summoned go with a despawn timer is activated (cart->UseDoorOrButton();) it will not depawns once the timer expires, you can test with the Explosives Cart:
- .cast https://woehead.way-of-elendil.fr/?spell=46798 (wait 6 secs and the gob will despawns)
- cast the spell again with gm ON and click the gob before it despawns, it will play the explosion animation then it will remains there and will never despawns (only the wheel is visible in this state)

**Comment by Aokromes** [comment]
this is fixed?

**Comment by Killyana** [comment]
Yes even if both generic issues are still there.
