### ISSUE TITLE
Torek's Assault available to Alliance players

### ISSUE THREAD

**Issue by Nocty1501** [TrinityCore/TrinityCore#23742]
TrinityCore rev. 07e2264964ef 2019-08-23 19:28:21 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Torek's assault is available to Alliance players. Create a character on Alliance, level up to level 20, head to Ashenvale, and Torek will be friendly and able to give a quest to the player, and his guards will not attack you.

**Comment by Killyana** [comment]
This is wrong the quest has faction restriction Allowableraces=690, but I fixed the wrong faction set by the SAI anyway: https://www.youtube.com/watch?v=znp_eh-7jiE
