### ISSUE TITLE
[Crash] Creature::ReacquireSpellFocusTarget

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23749]
Server crash Creature::ReacquireSpellFocusTarget
Crash Log: https://gofile.io/?c=BoETD3

Exception code: C0000420 An assertion failure has occurred.

Assertion message: 
```
c:\users\user\desktop\TestServer\src\server\game\entities\creature\creature.cpp:3161 in Creature::ReacquireSpellFocusTarget ASSERTION FAILED:
  HasSpellFocus()
MapID: 1 Map name: 'Kalimdor' X: -2129.89 Y: -3520.28 Z: 91.755 O: 1.13508
GUID Full: 0xf140000167000005 Type: Pet Pet number: 359  Low: 5 Entry 416
Name: Pizham
IsAIEnabled: true DeathState: 2 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 8
 MoveSpline
spline Id: 2786444
flags:  Done CanSwim Final_Angle
facing  angle: 1.13508
time passed: 1
total  time: 1
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (-2130.31, -3521.19, 91.755)
point 1 : (-2129.89, -3520.28, 91.755)
point 2 : (-2129.89, -3520.28, 91.755)
point 3 : (-2129.89, -3520.28, 91.755)

AIName:  ScriptName:  WaypointPath: 0 SpawnId: 5
TempSummonType : 8 Summoner: GUID Full: 0x00000000000005ea Type: Player Low: 1514
Owner: GUID Full: 0x00000000000005ea Type: Player Low: 1514
PetType: 0
```

Revision:  
TrinityCore rev. 92d83c3c2eaba3f5b58dc98472318872f3a54706
3.3.5

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

Pet in Question:
https://imgur.com/Dpzr3xa

**Comment by jackpoz** [comment]
please upload the crashlog somewhere else, I can't download it. I think you can even drag&drop the file as attachment to github (or just use gist.github.com

**Comment by illfated** [comment]
https://gist.github.com/illfated/3190ef0eba15ff8dea67d21fed42b338#file-61ad87d1069a-_worldserver-exe_-30-8_9-14-31-txt

Uploaded file:
[61ad87d1069a+_worldserver.exe_[30-8_9-14-31].txt](https://github.com/TrinityCore/TrinityCore/files/3562811/61ad87d1069a%2B_worldserver.exe_.30-8_9-14-31.txt)

**Comment by jackpoz** [comment]
This is an assert happening when a warlock pet is dismissed while it's casting [Fireball](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=7800)

**Comment by jackpoz** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/4074cb0f01d106c69546c3cb944d6fcf92ade456
