### ISSUE TITLE
[Master]VMaps Assembler Out Of Storage?

### ISSUE THREAD

**Issue by jazzy348** [TrinityCore/TrinityCore#23745]
When running the VMap assembler, I get an error stating that the VMaps assembler does not have enough storage to process everything... how much storage does it need? I currently have 60GB free on my server.
Revision: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, Debug, Static)
Date 27:8:2019. Time 1:20 
//=====================================================
*** Hardware ***
Processor: Intel Core Processor (Skylake, IBRS)
Number Of Processors: 8
Physical Memory: 4194303 KB (Available: 4194303 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows Server 2012 R2 Standard (Version 6.3, Build 9600)

//=====================================================
Exception code: E06D7363 
Fault address:  75B04E28 01:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll

Registers:
EAX:0033EED8
EBX:FEB9F000
ECX:00000003
EDX:00000000
ESI:733A155C
EDI:0033EF74
CS:EIP:0023:75B04E28
SS:ESP:002B:0033EED8  EBP:0033EF34
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000216

CRITICAL ERROR.

 Couldn't initialize the symbol handler for process.

Error [Not enough storage is available to process this command.
].

Call stack:
Address   Frame     Function      SourceFile
75B04E28  00000000  0001:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll
733A90A2  00000000  0001:000080A2 C:\Program Files (x86)\World of Warcraft\VCRUNTIME140D.dll
00157DAC  00000000  0001:00116DAC C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00155AB0  00000000  0001:00114AB0 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00042DBC  00000000  0001:00001DBC C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00041BED  00000000  0001:00000BED C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00041B85  00000000  0001:00000B85 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0007CCB0  00000000  0001:0003BCB0 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
000724E8  00000000  0001:000314E8 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0009189A  00000000  0001:0005089A C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00091969  00000000  0001:00050969 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0008BB0A  00000000  0001:0004AB0A C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0005EBD1  00000000  0001:0001DBD1 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00055257  00000000  0001:00014257 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0005D072  00000000  0001:0001C072 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0005CC3D  00000000  0001:0001BC3D C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0007C668  00000000  0001:0003B668 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0007C825  00000000  0001:0003B825 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00055E0F  00000000  0001:00014E0F C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0005F3FD  00000000  0001:0001E3FD C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00082463  00000000  0001:00041463 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00052010  00000000  0001:00011010 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00050C66  00000000  0001:0000FC66 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00041512  00000000  0001:00000512 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00156B6E  00000000  0001:00115B6E C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00156A87  00000000  0001:00115A87 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
0015692D  00000000  0001:0011592D C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
00156BD8  00000000  0001:00115BD8 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe
75C26A14  00000000  0001:00006A14 C:\Windows\SYSTEM32\KERNEL32.DLL
7759AD8F  00000000  0001:00059D8F C:\Windows\SYSTEM32\ntdll.dll
7759AD5A  00000000  0001:00059D5A C:\Windows\SYSTEM32\ntdll.dll
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
75B04E28  00000000  0001:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll

733A90A2  00000000  0001:000080A2 C:\Program Files (x86)\World of Warcraft\VCRUNTIME140D.dll

00157DAC  00000000  0001:00116DAC C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00155AB0  00000000  0001:00114AB0 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00042DBC  00000000  0001:00001DBC C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00041BED  00000000  0001:00000BED C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00041B85  00000000  0001:00000B85 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0007CCB0  00000000  0001:0003BCB0 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

000724E8  00000000  0001:000314E8 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0009189A  00000000  0001:0005089A C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00091969  00000000  0001:00050969 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0008BB0A  00000000  0001:0004AB0A C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0005EBD1  00000000  0001:0001DBD1 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00055257  00000000  0001:00014257 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0005D072  00000000  0001:0001C072 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0005CC3D  00000000  0001:0001BC3D C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0007C668  00000000  0001:0003B668 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0007C825  00000000  0001:0003B825 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00055E0F  00000000  0001:00014E0F C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0005F3FD  00000000  0001:0001E3FD C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00082463  00000000  0001:00041463 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00052010  00000000  0001:00011010 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00050C66  00000000  0001:0000FC66 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00041512  00000000  0001:00000512 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00156B6E  00000000  0001:00115B6E C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00156A87  00000000  0001:00115A87 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

0015692D  00000000  0001:0011592D C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

00156BD8  00000000  0001:00115BD8 C:\Program Files (x86)\World of Warcraft\vmap4assembler.exe

75C26A14  00000000  0001:00006A14 C:\Windows\SYSTEM32\KERNEL32.DLL

7759AD8F  00000000  0001:00059D8F C:\Windows\SYSTEM32\ntdll.dll

7759AD5A  00000000  0001:00059D5A C:\Windows\SYSTEM32\ntdll.dll

**Comment by Aokromes** [comment]
very likely you cannot run extractor from program files

**Comment by jazzy348** [comment]
I'll move the game to my Desktop and try running it from there... will update in 24 hours when it finishes

**Comment by Shauren** [comment]
I see that you compiled it in Debug mode but the log is as useless as Release. Did you compile it on a different machine then copied exes? If yes then you also need to copy .pdb files together with .exe to get proper logs

**Comment by jazzy348** [comment]
I did indeed, I'll copy them over and restart

**Comment by Aokromes** [comment]
i vote is no UAC
I sugest you to compile extractors on release mode to don't die.

**Comment by jazzy348** [comment]
Nope, same issue after adding the .pdb files and moving setup to Desktop.

Revision: TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, Debug, Static)
Date 27:8:2019. Time 21:9 
//=====================================================
*** Hardware ***
Processor: Intel Core Processor (Skylake, IBRS)
Number Of Processors: 8
Physical Memory: 4194303 KB (Available: 4194303 KB)
Commit Charge Limit: 4194303 KB

*** Operation System ***
Windows Server 2012 R2 Standard (Version 6.3, Build 9600)

//=====================================================
Exception code: E06D7363 
Fault address:  75B04E28 01:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll

Registers:
EAX:006FF3F8
EBX:FEDEB000
ECX:00000003
EDX:00000000
ESI:733A155C
EDI:006FF490
CS:EIP:0023:75B04E28
SS:ESP:002B:006FF3F8  EBP:006FF450
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000212


CRITICAL ERROR.

 Couldn't initialize the symbol handler for process.

Error [Not enough storage is available to process this command.
].



Call stack:
Address   Frame     Function      SourceFile
75B04E28  00000000  0001:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll
733A90A2  00000000  0001:000080A2 C:\Users\Administrator\Desktop\World of Warcraft\VCRUNTIME140D.dll
00AD7DAC  00000000  0001:00116DAC C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00AD5AB0  00000000  0001:00114AB0 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009C2DBC  00000000  0001:00001DBC C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009C1BED  00000000  0001:00000BED C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009C1B85  00000000  0001:00000B85 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009FCCB0  00000000  0001:0003BCB0 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009F24E8  00000000  0001:000314E8 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00A1189A  00000000  0001:0005089A C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00A11969  00000000  0001:00050969 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00A0BB0A  00000000  0001:0004AB0A C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009DEBD1  00000000  0001:0001DBD1 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009D5257  00000000  0001:00014257 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009DD072  00000000  0001:0001C072 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009DCC3D  00000000  0001:0001BC3D C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009FC668  00000000  0001:0003B668 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009FC825  00000000  0001:0003B825 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009D5E0F  00000000  0001:00014E0F C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009DF3FD  00000000  0001:0001E3FD C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00A02463  00000000  0001:00041463 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009D2010  00000000  0001:00011010 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009D0C66  00000000  0001:0000FC66 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
009C1512  00000000  0001:00000512 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00AD6B6E  00000000  0001:00115B6E C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00AD6A87  00000000  0001:00115A87 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00AD692D  00000000  0001:0011592D C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
00AD6BD8  00000000  0001:00115BD8 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe
75C26A14  00000000  0001:00006A14 C:\Windows\SYSTEM32\KERNEL32.DLL
7759AD8F  00000000  0001:00059D8F C:\Windows\SYSTEM32\ntdll.dll
7759AD5A  00000000  0001:00059D5A C:\Windows\SYSTEM32\ntdll.dll
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
75B04E28  00000000  0001:00033E28 C:\Windows\SYSTEM32\KERNELBASE.dll

733A90A2  00000000  0001:000080A2 C:\Users\Administrator\Desktop\World of Warcraft\VCRUNTIME140D.dll

00AD7DAC  00000000  0001:00116DAC C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00AD5AB0  00000000  0001:00114AB0 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009C2DBC  00000000  0001:00001DBC C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009C1BED  00000000  0001:00000BED C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009C1B85  00000000  0001:00000B85 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009FCCB0  00000000  0001:0003BCB0 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009F24E8  00000000  0001:000314E8 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00A1189A  00000000  0001:0005089A C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00A11969  00000000  0001:00050969 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00A0BB0A  00000000  0001:0004AB0A C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009DEBD1  00000000  0001:0001DBD1 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009D5257  00000000  0001:00014257 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009DD072  00000000  0001:0001C072 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009DCC3D  00000000  0001:0001BC3D C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009FC668  00000000  0001:0003B668 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009FC825  00000000  0001:0003B825 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009D5E0F  00000000  0001:00014E0F C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009DF3FD  00000000  0001:0001E3FD C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00A02463  00000000  0001:00041463 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009D2010  00000000  0001:00011010 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009D0C66  00000000  0001:0000FC66 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

009C1512  00000000  0001:00000512 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00AD6B6E  00000000  0001:00115B6E C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00AD6A87  00000000  0001:00115A87 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00AD692D  00000000  0001:0011592D C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

00AD6BD8  00000000  0001:00115BD8 C:\Users\Administrator\Desktop\World of Warcraft\vmap4assembler.exe

75C26A14  00000000  0001:00006A14 C:\Windows\SYSTEM32\KERNEL32.DLL

7759AD8F  00000000  0001:00059D8F C:\Windows\SYSTEM32\ntdll.dll

7759AD5A  00000000  0001:00059D5A C:\Windows\SYSTEM32\ntdll.dll

**Comment by illfated** [comment]
Have you tried compiling 64-bit build instead of 32-bit? Looking at the logs, it seems you are building 32-bit.
(Not sure why you would want 32-bit, but I don't know your scenario.)

**Comment by jazzy348** [comment]
I has trouble compiling 64-bit as cmake could only configure and generate to 32 for some reason. I'll investigate that more later.

**Comment by illfated** [comment]
BTW, you may want to add "MarkDown code fence" a.k.a. 3 back ticks ( **```** ) on a blank line before & after your logs in your comments , just to keep the text small & monospaced.
You can also choose to add the "details" MarkDown feature (looks like HTML code) to hide the logs to let those who want to see them, expand the minimized details.
```
<details>

```
(remember to add 1 blank line after `<details>` and a closing `</details>` at the end of the logs, if you want any following lines to be shown as regular text)

**Comment by jazzy348** [comment]
Apologies, I'm a noob..

Also issue resolved, seemed to be an issue with 32bit. Managed to compile 64bit and everything seems to be running smoothly. Thanks for your help!

**Comment by illfated** [comment]
Thank you for the feedback, always good to know what caused the issue in the first place.

**Comment by funjoker** [comment]
Can we drop 32bit support totally?
