### ISSUE TITLE
[3.3.5] Parry-haste mechanic

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23754]
**Description:**
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/46829798
https://wowwiki.fandom.com/wiki/Parry?oldid=2335125
https://www.mmo-champion.com/threads/740918-Halion-Damage-and-Parry-Haste
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/

This commit: https://github.com/TrinityCore/TrinityCore/commit/4a46fee03ef204289bbd96e8e1e07117b3bebd9f introduce the flag CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN  for exclude some NPCs of this mechanic
But, seems wrong and doesn't work properly, I think should be victim in this check instead of the unit that deal the damage

**Steps to reproduce the problem:**

1. Go to a NPC with CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN, do attacks and see when NPC do a parry, swing attack time of the NPC has been reduced.
2. You can test easy if you use a snake trap for attack a NPC with CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN, because the NPC get more parry if get attacked by snakes

So, probably should be:
```c++
(victim->GetTypeId() != TYPEID_UNIT || (victim->ToCreature()->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN) == 0))
```
instead of:
```c++
(GetTypeId() != TYPEID_UNIT || (ToCreature()->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN) == 0))
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/4074cb0f01d106c69546c3cb944d6fcf92ade456

**Comment by Aokromes** [comment]
f8d7b260476c69e09ab0329cb7cd6c277f5473a7
