### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by xfyoujxu799** [TrinityCore/TrinityCore#23759]
my CMAKE
It shows the following problem
How can I solve it?
Please help me save me.
```
CXX target scripts cotired without unity build.

CXX RC target worldserver cotired without unity build.
Configuring incomplete, errors occurred!
See also "D:/Trinity/Build/CMakeFiles/CMakeOutput.log".
See also "D:/Trinity/Build/CMakeFiles/CMakeError.log".
```

**Comment by Aokromes** [comment]
useless log, users issues belongs to forum.

**Comment by illfated** [comment]
@xfyoujxu799 : Simple solution -- delete all the files & folders in your `/Build/` folder.
Let CMake rebuild those files. This usually solves your issue.
