### ISSUE TITLE
Stormcaller Brundir enters into walls / unkillable

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23751]
**Description:**

A lot of times Stormcaller Brundir ( 32857 )enters into walls or stops on top of some places making him to recover hp

**Current behaviour:**

It fully breaks the event.

**Expected behaviour:**

It never must enter walls/ stop on unreachable places making him to recover hp.

**Steps to reproduce the problem:**

1. go ulduar
2. fight brundir killing the other 2 bosses,
3. run around to force him to fly.

https://i.imgur.com/FDdOu63.jpg

**Branch(es):**

3.3.5a, for sure all

**TC rev. hash/commit:** 

 4074cb0f01d1 for sure all since implementation, i got reports years ago.

**Operating system:** Debian 10 x64, Ubuntu 19.10 x64

**Comment by RR2739-VCN** [comment]
I think it is all related to 
5a980226497605b18f1855fa39f340c10ee9dd53
There are many Bosses/Encounters that do the same thing.

**Comment by Aokromes** [comment]
na, this bug is ANCIENT

**Comment by Aokromes** [comment]
https://i.imgur.com/twwswd2.jpg
https://mega.nz/#!xiYCyI4Q!zpYRKX8z8YHV1-yf4Zv0OVjePx9AvlR0FLSDnEtHUPM
https://mega.nz/#!0uAQFIQI!Y2XHftFakDdOK1r6W-FQTlYYRnuUmkOyGD29irZrcaY
screenshots and video of bug(s)

**Comment by Aokromes** [comment]
876a848 *
