### ISSUE TITLE
Ulduar: Kologarn sometimes stuck on combat after kill

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23756]
**Description:**

Kologarn sometimes stuck on combat after kill

**Current behaviour:**

Kologarn sometimes leaves party on combat after kill.
Maybe related? No achievement progress when killing it.

[00:40:00] Combat refs: (Combat state: 1 | Manager state: 1)
[00:40:00] [PvE] Armsweep Stalker Kologarn (SpawnID 136520)

**Expected behaviour:**

You exit of combat after kill it.
You get achievement progress when killing it.

**Steps to reproduce the problem:**

1. go c 136762
2. kill both arms
3. kill body
4. you stay on combat

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

4074cb0f01d1

**Operating system:** Debian 10 x64, Ubuntu 19.10 x64.

**Comment by jackpoz** [comment]
I created a PR https://github.com/TrinityCore/TrinityCore/pull/23866

**Comment by Aokromes** [comment]
fed030d
