### ISSUE TITLE
Scripts/Outland: npc_ancestral_wolf (for quest A Spirit Guide) does not run

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23750]
**Description:**

The horde quest  can not be handed in or rewarded, because the guardian script `npc_ancestral_wolf ` will not activate when the NPC is spawned.

https://github.com/TrinityCore/TrinityCore/blob/0e7c66cb4c7ff7d44e232d0b50703a48605ffd24/src/server/scripts/Outland/zone_hellfire_peninsula.cpp#L137-L239

**Current behaviour:**

Currently, all you can do is to pick up the quest from the quest giver, travel back to the corpse involved in the previous quests
- https://www.wowhead.com/quest=9400/the-assassin
- https://www.wowhead.com/quest=9401/a-strange-weapon

and spawn the guardian NPC using the provided quest item.

(For old details, see the old issue ticket [quest] A Spirit Guide #4028)
- https://www.wowhead.com/quest=9405/the-warchiefs-mandate
- https://www.wowhead.com/quest=9410/a-spirit-guide
- https://www.wowhead.com/npc=16574/far-seer-regulkut
- https://www.wowhead.com/npc=16845/gorkan-bloodfist
- https://www.wowhead.com/item=23669/ancestral-spirit-wolf-totem
- https://www.wowhead.com/spell=29731/call-ancestral-spirit-wolf
- https://www.wowhead.com/npc=17077/ancestral-spirit-wolf
- https://www.wowhead.com/npc=17062/fel-orc-corpse

**Expected behaviour:**

NPC 17077 (Ancestral Spirit Wolf) should emote, start walking its waypoints towards the Mag'har village and complete the quest for you by running the script lines related to Earthcaller Ryga before you can hand in the quest to Gorkan Bloodfist.

**Steps to reproduce the problem:**

1. Get a level 58+ horde character.
2. `.quest add 9410`
3. `.go creature id 17062`
4. Use item 23669 (Ancestral Spirit Wolf Totem)
5. Notice that your new guardian NPC does not move or do anything until the timer despawns it.

**Branch(es):**

**3.3.5** (I have no idea if master branch is affected yet, depends very much on cherry-picking & when this bug appeared in the source)

**TC rev. hash/commit:**

TrinityCore rev. 6e2e55bc38e2 2019-08-30 12:32:06 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1b  26 Feb 2019 (library: OpenSSL 1.1.1b  26 Feb 2019)
Using Boost version: 1.67.0
Using MySQL version: 5.7.27
Using CMake version: 3.13.4
Compiled on: Linux 5.0.0-1014-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19081

**Operating system:** Unix / Linux (https://tcubuntu.northeurope.cloudapp.azure.com)

**Comment by Aokromes** [comment]
0b3a9e2
