### ISSUE TITLE
Scarlet's monastery High Inquisitor's Door is open even on db is closed.

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23753]
**Description:**

Scarlet's monastery High Inquisitor's Door is open even on db is closed.

**Current behaviour:**

The door is open.

**Expected behaviour:**

The door must be closed.

**Steps to reproduce the problem:**

1. go object 11877
2. see open door

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6e2e55bc38e2

**Operating system:** Debian x64, Ubuntu x64

**Comment by illfated** [comment]
I can confirm that. I played on https://tcubuntu.northeurope.cloudapp.azure.com/ yesterday and went there to get some greens to disenchant. High Inquisitor Whitemane could be seen inside the room behind Scarlet Commander Mograine (standing on the altar podium).

**Comment by Jinnaix** [comment]
Dup #15793

**Comment by illfated** [comment]
Fair and good point. I agree. This ticket can be closed, I suppose.
