### ISSUE TITLE
[3.3.5]Problems with declining names of pets and characters.

### ISSUE THREAD

**Issue by Infernales** [TrinityCore/TrinityCore#23775]
**Description:**
Problems with declining names of pets and characters with Russian client.
**Current behaviour:**
When creating a character with a name on Russian or when changing the name of a pet on Russian, a window appears with a choice of declination of the name.
https://i.imgur.com/PGRb4yT.png
When we choose the first option, a window appears with an error declination name change.
https://i.imgur.com/tLSzOFA.png
If you choose the second option, then everything is fine.
https://i.imgur.com/8jzD1tF.png
**Expected behaviour:**
The first option should work without errors.
**Branch(es):**
3.3.5
**TC rev. hash/commit:** 
8ecc45c
**Operating system:**
Linux

**Comment by jackpoz** [comment]
this sounds like an issue that only contributors with a russian client can fix (just like I ended up fixing utf-8 issues on a sv-se OS)

**Comment by illfated** [comment]
I am wondering if it is an automatic refusal of using the word "Test" (Russian: "Tect") as a name in the first place. I presume that is why you get suggestions of variations with 1 more letter instead of simply "Test".

**Comment by Infernales** [comment]
@illfated The problem will be with absolutely any name on Russian. I chose the word "тест" as more understandable.

**Comment by Infernales** [comment]
@Treeston These functions did not need to be adapted to your changes?
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Globals/ObjectMgr.cpp#L8728
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Globals/ObjectMgr.cpp#L8562
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Globals/ObjectMgr.cpp#L8519

**Comment by Treeston** [comment]
`MAX_INTERNAL_PLAYER_NAME` was used to determine the size of `wstr_buf` (in `GetMainPartOfName`) and nowhere else. It is no longer used after the changes.

**Comment by Infernales** [comment]
@Treeston Well then, I ran out of ideas about this bug. If you suddenly have solutions to this bug, then I will be happy to test them.
