### ISSUE TITLE
[3.3.5] Ethereal Soul-Trader

### ISSUE THREAD

**Issue by Infernales** [TrinityCore/TrinityCore#23771]
**Description:**
Pet Ethereal Soul-Trader does not follow the player.

**Current behaviour:**
https://i.imgur.com/7SCJFnb.jpg

**Expected behaviour:**

Pet Ethereal Soul-Trader must follow the player.

**Steps to reproduce the problem:**

1. Add item 38050
2. Summon Ethereal Soul-Trader

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
88e74ac

**Operating system:** 
Linux

**Comment by Artamedes** [comment]
This is because in npc_pet_gen_soul_trader script JustAppeared is overrided, 
so adding CreatureAI::JustAppeared(); - will fix the issue
making a pr..

**Comment by Keader** [comment]
/8ecc45cd1aac1c33c8b4cb2f269ac24d728570cc
