### ISSUE TITLE
Deadmines - door after Rhahk'zor closing before a dungeon reset

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23785]
**Description:**

In the Deadmines instance, when you defeat Rhahk'zor, the door opens as intended, but if you wipe in the next room and corpse run to the dungeon, the door is closed again, You can only open it in GM mode.

**Expected behaviour:**

Rhahk'zor's door should only close after a dungeon reset.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/5b7b8f868fd26b0e26895bf42dfc4d499e94f816

**Operating system:** Win 10 x64

**Comment by Jinnaix** [comment]
Ok, i was able to reproduce this.
Im really surprised that there arent more reports about this.
But i guess no one cares about old content and no one wipes these days.

This affects all doors/gameobjects in all older instance scripts, not only this one.

As soon as a grid is unloaded (Default unload time is 300 seconds/5 minutes), the gameobject will reset to its default state when the grid is loaded again.

#24029

**Comment by TranceAccount** [comment]
Can confirm this on rev. [c3037c35639a](https://github.com/TrinityCore/TrinityCore/commit/c3037c35639a) after waiting 6 minutes outside dungeon, but this does not happen if the dungeon is entered after a few seconds again. This also happened for (atleast two of) the doors after the first boss, however these doors can be opened by the players themselves (Different LockId).

**Comment by TranceAccount** [comment]
This can also be closed now @Treeston

**Comment by Treeston** [comment]
81f3ed1d0c6ecba624b4a88a4c60c0dfa1cd9524

**Comment by MsterXter** [comment]
.gobject activate 26185
