### ISSUE TITLE
[Server Lag] Onyxia's Lair | Console Spam

### ISSUE THREAD

**Issue by RR2739-VCN** [TrinityCore/TrinityCore#23789]
Onyxia's Lair Boss Encounter creates an intense server lag. The console lights up with error messages that slows down the server drastically:

```
SCRIPT_COMMAND_ACTIVATE_OBJECT ('' script id: 0) source object is not unit (TypeId: 5, Entry: 176909, GUID: 235), skipping.
SCRIPT_COMMAND_ACTIVATE_OBJECT ('' script id: 0) source object is not unit (TypeId: 5, Entry: 176909, GUID: 235), skipping.

```
There are 500+ of these messages that begin to show up in console as errors and when that happens you can notice a drastic lag on the server even with 1 player. 

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
61ad87d1069a

Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Number Of Processors: 8
Physical Memory: 33187668 KB (Available: 27258588 KB)
Commit Charge Limit: 37381972 KB

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

**Comment by jackpoz** [comment]
do you have sync logging ? does async logging change anything ?

it's probably a gameobject having a MapScript even if that's not supported (but it probably takes 1 line to add support)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/11877

**Comment by RR2739-VCN** [comment]
That issue reference is from 5 years ago. Why close it? This should remain open since other issue is dormant for years already

**Comment by Aokromes** [comment]
the other issue is still open, you can write there and it's still valid.
