### ISSUE TITLE
[3.3.5]spell Consumption

### ISSUE THREAD

**Issue by wywgk** [TrinityCore/TrinityCore#23782]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

同一个法术，高等级和低等级消耗同样的法力值，但是造成的伤害不同。
bing:
The same spell, high and low levels consume the same force values, but the damage caused is different.

**Expected behaviour:**

同一个法术，高等级和低等级造成的伤害不同,消耗不同的法力值。
bing:
The same spell, high and low level of injury is different, consuming different spell values.

**Steps to reproduce the problem:**

法师：部落/联盟
Mage Tribes and Alliances

法术：暴风雪

spell :snowstorm

**Branch(es):**

 3.3.5,

**TC rev. hash/commit:** 

rev. 546bd0f6fb4a 2019-09-09 19:52:40 (3.3.5 branch) (unix, RelWithDebInfo. Static)

**Operating system:** debian 10

**Comment by jackpoz** [comment]
which spell ?

**Comment by qyh214** [comment]
His example:
class:mage
spell: id is 10(I think enUS spell name is Blizzard)

and his option is:
the same spell but different ranks should consume different mana values and cause different damage.

**Comment by wywgk** [comment]
感谢上海的朋友，就是这个意思，bing的翻译没办法，实在是英语水平有限。

**Comment by Shauren** [comment]
This is wrong. In WotLK spells cost a fixed % of base mana for all ranks, theres no bug here
