### ISSUE TITLE
Share button in Quest Log always returns in "That quest cannot be shared today".

### ISSUE THREAD

**Issue by clintonmasters** [TrinityCore/TrinityCore#23788]
**Description:**

Share button in Quest Log always returns in "That quest cannot be shared today".

**Current behaviour:**

Share button in Quest Log always results in "That quest cannot be shared today".  Happens for all normal quests when in a group and when not in a group.

**Expected behaviour:**

1. Expect messages "You are not in a party" when not in a group.  

2. Expect to share regular quests with party members when they qualify. Reasons from QuestPushReason (QuestDef.h)

3. Expect only daily quests to return "That quest cannot be shared today"

**Steps to reproduce the problem:**

1. Get a non-daily quest (didn't test dailies)
2. Share the quest when in a group
3. Share the quest when solo

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. e8ab60955d82 2019-09-09 14:08:48 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

git commit e8ab60955d822363a23dff8a3d0947c1c1c4fd3d 

**Operating system:**  "Ubuntu 19.04"

WORLD: Received CMSG_QUESTGIVER_STATUS_QUERY for npc, guid = 113
WORLD: Sent SMSG_QUESTGIVER_STATUS NPC=GUID Full: 0xf130000121000071 Type: Creature Entry: 289  Low: 113, status=0
WORLD: Received CMSG_QUESTGIVER_STATUS_QUERY for GameObject guid = 17
GetConditionsForNotGroupedEntry: found conditions for type 19 and entry 254
ConditionMgr::IsObjectMeetToConditions
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 314
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
WORLD: Sent SMSG_QUESTGIVER_STATUS NPC=GUID Full: 0xf11000c9fc000011 Type: Gameobject Entry: 51708  Low: 17, status=0
CMSG_TIME_SYNC_RESP
WORLD: Recvd ZONE_UPDATE: 10
CMSG_JOIN_CHANNEL [Player: Zill GUID Full: 0x0000000000000067 Type: Player Low: 103, Account: 1] Channel: 1, unk1: 1, unk2: 0, channel: General - Duskwood, password: 
CMSG_JOIN_CHANNEL [Player: Zill GUID Full: 0x0000000000000067 Type: Player Low: 103, Account: 1] Channel: 2, unk1: 1, unk2: 0, channel: Trade - Duskwood, password: 
CMSG_JOIN_CHANNEL [Player: Zill GUID Full: 0x0000000000000067 Type: Player Low: 103, Account: 1] Channel: 22, unk1: 1, unk2: 0, channel: LocalDefense - Duskwood, password: 
CMSG_JOIN_CHANNEL [Player: Zill GUID Full: 0x0000000000000067 Type: Player Low: 103, Account: 1] Channel: 25, unk1: 1, unk2: 0, channel: GuildRecruitment - Duskwood, password: 
CMSG_JOIN_CHANNEL [Player: Zill GUID Full: 0x0000000000000067 Type: Player Low: 103, Account: 1] Channel: 26, unk1: 1, unk2: 0, channel: LookingForGroup, password: 
WORLD: CMSG_WORLD_STATE_UI_TIMER_UPDATE
WORLD: Received CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY
GetConditionsForNotGroupedEntry: found conditions for type 19 and entry 254
ConditionMgr::IsObjectMeetToConditions
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 314
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
WORLD: Received CMSG_REQUEST_PARTY_MEMBER_STATS
WORLD: Received CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY
GetConditionsForNotGroupedEntry: found conditions for type 19 and entry 254
ConditionMgr::IsObjectMeetToConditions
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 314
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
WORLD: Received CMSG_REQUEST_PARTY_MEMBER_STATS
WORLD: Received CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY
GetConditionsForNotGroupedEntry: found conditions for type 19 and entry 254
ConditionMgr::IsObjectMeetToConditions
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 314
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
WORLD: Received CMSG_REQUEST_PARTY_MEMBER_STATS
WORLD: Received CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY
GetConditionsForNotGroupedEntry: found conditions for type 19 and entry 254
ConditionMgr::IsObjectMeetToConditions
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 314
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253
ConditionMgr::IsPlayerMeetToConditionList [Condition SourceType: 19 (Quest Accept), SourceEntry: 254] val1: 253

. . .

WORLD: Sent MSG_QUEST_PUSH_RESULT

**Comment by jackpoz** [comment]
> 1. Get a non-daily quest (didn't test dailies)

do you have a quest id ?

**Comment by illfated** [comment]
Maybe not too obvious, but from the log above:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=254
- https://classic.wowhead.com/quest=254/digging-through-the-dirt
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=51708
- https://classic.wowhead.com/object=51708/elizas-grave-dirt

Notice that tcubuntu aowow seems to indicate that a regular quest is a daily quest.

**Comment by ckegg** [comment]
It was broken after timezone was being implemented at commit: aeddd417c460c43d885cb89ceaa6e051c44b1d27

**Comment by jackpoz** [comment]
@ckegg do you start getting the issue with that commit ? what timezone does your server have ? which one does your client have ? what hour do you have set for the daily quest reset ?

https://github.com/TrinityCore/TrinityCore/commit/a5e73e41c0e813e674bb0a644e0052052435494e might be related too as it changed a lot of code related to quests

**Comment by ckegg** [comment]
@jackpoz You are absolutely correct. After digging into logs, quests stopped shareable right after August 4th while I compile every other 3 days from current commit. The commit I mentioned earlier was on July 19th and nothing was reported.

**Comment by nawuko** [comment]
Just my two cents, looking at the commit it looks like the "if" statement in Line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L15886 need to be inverted, this looks like a typo.

@ckegg Can you change line 15886 from `if (sQuestPoolMgr->IsQuestActive(quest_id))` to `if (!sQuestPoolMgr->IsQuestActive(quest_id))` and check again?

**Comment by ckegg** [comment]
@nawuko Just tried inverting the line and now quests can be shared. Tested with Dalaran daily quest and was shareable to others.

**Comment by jackpoz** [comment]
@nawuko do you want to open a PR with that ?

**Comment by illfated** [comment]
Feels like overkill to open a PR for a 1 character change, but I suppose it is more about giving credit for the change.

**Comment by jackpoz** [comment]
A PR is the standard TrinityCore way to accept C++ code changes

**Comment by illfated** [comment]
Sure. I was just philosophizing over the difference between simplistic write-up commits and pull requests.

**Comment by nawuko** [comment]
I don't have the time, but feel free to open a PR or @Treeston could just to a commit since it's just a follow up to one of his commits, dunno if he is currently available

**Comment by jackpoz** [comment]
It takes 2 minutes to open a PR from github:
- edit the file
- choose to save it as pull request
- click create

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f9d6c57006ebd1b0e38e8a633fd217c99e68a6cd
