### ISSUE TITLE
creatures ignores * UNIT_FLAG_IMMUNE_TO_PC (0x100) on mixed groups

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#23795]
**Description:**

creatures ignores * UNIT_FLAG_IMMUNE_TO_PC (0x100) on mixed groups

**Expected behaviour:**

creatures don't agroes people when having * UNIT_FLAG_IMMUNE_TO_PC (0x100)

**Steps to reproduce the problem:**

1. (for faster repo, and save completing quests) login with one horde and one aliance gm
2. make a group with both
3. .go gameobject 151101
4. enter pit of saron with aliance gm, turn gm off / enter forge of souls
5. with the horde gm enter pit of saron / forge of souls, gm off, go c id 36494 / 36502. 
6. dam 1000000
7. you will see you have got agro from aliance quest giver.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

215a6cee2489

**Operating system:** debian 10 x64 ubuntu 19.10 x64

**Comment by Killyana** [comment]
It happen precisely with this 2 summoned Npcs: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/instance_pit_of_saron.cpp#L158-L160

Both have the flag immune to PC and no script, but when they are summoned they will enter combat with  the opposite faction players. It doesn't happen with .npc add

**Comment by jackpoz** [comment]
Callstack:
>	worldserver.exe!CombatManager::CanBeginCombat(const Unit * a, const Unit * b) Line 54	C++
 	worldserver.exe!CreatureAI::DoZoneInCombat(Creature * creature) Line 90	C++
 	worldserver.exe!BossAI::JustSummoned(Creature * summon) Line 525	C++
 	worldserver.exe!TempSummon::InitSummon() Line 229	C++
 	worldserver.exe!Map::SummonCreature(unsigned int entry, const Position & pos, const SummonPropertiesEntry * properties, unsigned int duration, WorldObject * summoner, unsigned int spellId, unsigned int vehId) Line 1925	C++
 	worldserver.exe!WorldObject::SummonCreature(unsigned int entry, const Position & pos, TempSummonType despawnType, unsigned int despawnTime, unsigned int __formal, unsigned int spellId) Line 1975	C++
 	worldserver.exe!instance_pit_of_saron::instance_pit_of_saron_InstanceScript::SetBossState(unsigned int type, EncounterState state) Line 159	C++
 	worldserver.exe!BossAI::_JustDied() Line 481	C++
 	worldserver.exe!boss_garfrost::boss_garfrostAI::JustDied(Unit * __formal) Line 125	C++
 	worldserver.exe!Unit::Kill(Unit * attacker, Unit * victim, bool durabilityLoss) Line 10971	C++
 	worldserver.exe!Unit::DealDamage(Unit * attacker, Unit * victim, unsigned int damage, const CleanDamage * cleanDamage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask, const SpellInfo * spellProto, bool durabilityLoss) Line 826	C++

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/23815 , please check if it fixes the issue and if it breaks anything

**Comment by jackpoz** [comment]
I opened another PR https://github.com/TrinityCore/TrinityCore/pull/23818

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ef694cc251844d34a64ae03f79d28a5c76719f6b
