### ISSUE TITLE
DB/Fix - Avatar of Sathal despawn

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23805]
**Description:**

NPC https://www.wowhead.com/npc=21925/avatar-of-sathal should only be spawnerd in quest https://www.wowhead.com/quest=10641/against-the-legion, currently she is spawned in Nagrand.

```sql
-- Avatar of Saathal despawn
DELETE FROM `creature` WHERE `id`= 21925;
```

**Branch(es):**

 3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9f66158ae552ea8195e870703f55f0a4483745d0

**Operating system:** Win 10 x64

**Comment by illfated** [comment]
Good point, I concur with your solution. Easy overview of the NPC here:
- https://wow.gamepedia.com/Avatar_of_Sathal

The only reason I can think of for that creature being spawned there, is that it could have been a typo when the spawns in [Forge Camp: Fear](https://wow.gamepedia.com/Forge_Camp:_Fear) were committed.
(I have not yet tried to research which NPC should have been there instead.)
