### ISSUE TITLE
No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)]

### ISSUE THREAD

**Issue by rwilkin** [TrinityCore/TrinityCore#23802]
I started a night elf character and withing 2 minutes I get disconnected. 
The server says:
`No defined handler for opcode [UNKNOWN OPCODE 0x354B (13643)] sent by [Player: Avalos GUID Full: 0x08000400000000000000000000000005 Type: Player Entry: 0 Low: 5, Account: 5]`

I'm not really sure what that means, but it has happened a few times now.

**Comment by MaxtorCoder** [comment]
Is this for master? Also what revision? Any more info on what you were doing?

**Comment by rwilkin** [comment]
Sorry, I've posted this in the wrong Git. 
It is the Ashamane Core that is doing this.

It is happening when I accept the first quest from the NPC at the start.
I'll raise an issue on the correct Git.

**Comment by jackpoz** [comment]
Please always follow the template when creating a new issue

![image](https://user-images.githubusercontent.com/1153754/65120176-84343000-d9ed-11e9-89ab-653808376e45.png)

Closing this as you mentioned the issue happens in Ashamane Core

**Comment by Aokromes** [comment]
also one open ticket already exists for this.
