### ISSUE TITLE
[3.3.5a] Quest: Return of the High Chief (id: 12069, horde)

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#23806]
**Description:**

1. Accept quest -> you receive Anub'ar Prison Key (id: 36760)
2. fly to object point 
3. use Anub'ar Prison Key on object 

**Current behaviour:**

A script event starts -> npc is set free and walks a few steps, speaks something, than nothing happens anymore. Enemy npc 26608 is not summoned/pulled and can't be killed - quest can't be completed.

**Expected behaviour:**
Some more script magic is happening, npc 26608 gets spulled, and can be killed:
https://www.youtube.com/watch?v=dTV1htL_eRI&feature=youtu.be

**Branch(es):**

Only tested on 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. fb059722fdb1 2019-09-17 09:11:56 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** Win 10

**Comment by illfated** [comment]
Maybe some of the SAI scripting is blocked by changes during the last year or so.
Likely source of implementation: https://github.com/TrinityCore/TrinityCore/commit/ff18a6e426ff2bae0214e510549397402c4dd162

**Comment by jjo72ddd** [comment]
still not working

**Comment by dr-j** [comment]
The npc for this is permanent spawn it’s on top of the cliff should jump down and attack during event

**Comment by dr-j** [comment]
Target the npc for this quest (the anub) and type .npc set data 1 1 if this does not jump down and remove immune flags this is where the problem is.

I suspect this maybe related to creature_template_movement as don’t have that change in core I use but still works for me,  core I use is nothing to do with me is upto date but with some changes omitted,

**Comment by dr-j** [comment]
Ok try this this is change I made around two years ago probably never got pushed to tc

**Comment by illfated** [comment]
@jjo72ddd : Please test and tell us if it works.

**Comment by Rushor** [comment]
now all will start again https://i.imgur.com/fDH1IGV.jpg

the issue was related to the wp handling

```sql
-- Roanauk Icemist SAI
SET @ENTRY := 26654;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,38,0,100,513,1,1,0,0,80,@ENTRY*100+00,2,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Data Set 1 1 - Run Script (No Repeat)"),
(@ENTRY,0,1,2,11,0,100,512,0,0,0,0,45,1,1,0,0,0,0,9,26656,0,200,0,0,0,0,"Roanauk Icemist - On Respawn - Set Data 1 1"),
(@ENTRY,0,2,3,61,0,100,512,0,0,0,0,22,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Respawn - Set Event Phase 1"),
(@ENTRY,0,3,4,61,0,100,512,0,0,0,0,11,47273,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Respawn - Cast 'Icemist's Prison'"),
(@ENTRY,0,4,0,61,0,100,512,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Respawn - Set Reactstate Passive"),
(@ENTRY,0,5,0,1,1,100,0,5000,30000,120000,150000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - Out of Combat - Say Line 0 (Phase 1)"),
(@ENTRY,0,6,0,40,0,100,512,1,26654,0,0,80,@ENTRY*100+01,2,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Waypoint 1 Reached - Run Script"),
(@ENTRY,0,7,0,1,0,100,0,0,0,15000,35000,5,15,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - Out of Combat - Play Emote 15"),
(@ENTRY,0,8,0,38,0,100,512,2,2,0,0,80,@ENTRY*100+02,2,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Data Set 2 2 - Run Script"),
(@ENTRY,0,9,0,4,0,100,0,0,0,0,0,11,47379,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Aggro - Cast 'Icemist's Blessing'"),
(@ENTRY,0,10,0,11,0,100,512,0,0,0,0,78,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Roanauk Icemist - On Respawn - Reset All Scripts");
```

**Comment by Killyana** [comment]
Same change as dr-j

**Comment by Rushor** [comment]
oh fuck didn't read that haha
