### ISSUE TITLE
Mobs fail to consistently aggro on spell miss

### ISSUE THREAD

**Issue by tarwyn** [TrinityCore/TrinityCore#23804]
**Description:**

Some spells fail to cause aggro on mobs when they (the spells) miss initially.

**Current behaviour:**

If a spell like Fireball or Corruption misses, the target will not aggro the caster.

**Expected behaviour:**

Negative and/or damaging spells should cause the target to aggro the caster even if they miss.

**Steps to reproduce the problem:**

1. Set a breakpoint on line 2130 in spell.cpp:
`targetInfo.MissCondition = caster->SpellHitResult(target, m_spellInfo, m_canReflect && !(IsPositive() && m_caster->IsFriendlyTo(target)));`
2. Log into the game with any character 
3. .cast 3140 on any viable target, this will trigger the breakpoint
4. Execute the BP statement, then change targetInfo.MissCondition to SPELL_MISS_MISS (1)
5. Continue execution
6. Spell will have missed and no aggro was caused by it

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
fb059722fdb18a94d47b3f44a5b2d7f183bf5a29

**Observations**
I've traced the problem to an 8 year old commit:
b40bf693194abd3f1b9e35ab6792f0df2369d1dc

Particularly this (Lines 2676-2687):
`                case SPELL_AURA_PERIODIC_HEAL:`
`                case SPELL_AURA_PERIODIC_DAMAGE:`
`                case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:`
`                case SPELL_AURA_PERIODIC_LEECH:`
`                case SPELL_AURA_PERIODIC_MANA_LEECH:`
`                case SPELL_AURA_PERIODIC_HEALTH_FUNNEL:`
`                case SPELL_AURA_PERIODIC_ENERGIZE:`
`                case SPELL_AURA_OBS_MOD_HEALTH:`
`                case SPELL_AURA_OBS_MOD_POWER:`
`                case SPELL_AURA_POWER_BURN_MANA:`
`                    spellInfo->AttributesCu |= SPELL_ATTR0_CU_NO_INITIAL_THREAT;`
`                    break;`

All spells matching any of these aura effects in any of their effect slots will have the custom attribute SPELL_ATTR0_CU_NO_INITIAL_THREAT set, which will prevent threat from being generated on a miss in Spell::HandleThreatSpells() @ 4958.

I've tested a number of spells myself with the following results:

Fireball (3140) - no aggro
Corruption ( 172)- no aggro
Shadow Word Pain (589) - no aggro
Curse of Agony (980) - no aggro
Devouring Plague (2944) - no aggro
Drain Life (689) - no aggro
Drain Mana (5138) - no aggro
Immolate (348) - no aggro
Moonfire (8921) - no aggro
Serpent Sting (49001) - no aggro
Flame Shock (8050) - no aggro

Mind Blast (8092) - aggro
Smite (585) - aggro
Shadow Bolt (686) - aggro
Wrath (5176) - aggro
Lightning Bolt (403) - aggro

I then commented out the above lines from SpellMgr.cpp and retested all of these spells and they all worked as intended afterwards.

I don't know for certain how to retail version handled spell misses. I played WoW extensively from Vanilla - WOTLK with mostly casters and my memory says that these spells would cause aggro even if they initially miss.

Regardless of my memory though, there's a clear inconsistent behaviour on initial spell misses due to this code, as the Damage School-only spells do cause aggro even on a miss.

**Comment by Shauren** [comment]
Maybe this attribute should not be set if the spell has other effects on it (like direct damage)

**Comment by tarwyn** [comment]
I've investigated this and thought about it some more with a view that negative/damaging spells cause aggro even if they miss:

1. @Shauren: considered it, but a spell like Curse of Agony would then still miss without aggro because it doesn't have a direct damage effect.
2. SPELL_AURA_PERIODIC_HEAL: heals can't miss to begin with so this seems redundant
3. SPELL_AURA_PERIODIC_HEALTH_FUNNEL: affects three non-player spells only, seems redundant
4. SPELL_AURA_PERIODIC_ENERGIZE: affects spells like Enervate, which can't miss, so redundant
5. SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_POWER: can't find any relevant spells for these either, hence redundant as well
6. The remaining auras affect damaging player spells, which should cause aggro, and hence shouldn't have the custom attribute applied; also redundant

My conclusion is that the entire switch statement is redundant and can be removed. It may have been put in place as a fix for something that didn't quite work in the spell system back then, as @jackpoz suggested in IRC. Right now however, it causes unexpected and inconsistent behaviour.

Side note:
Maybe the entire section needs verification. I find it odd that we have a way to modify custom attributes on spells via the DB, and then need to do a wholesale modification of all spells based on hard to verify, hard programmed "rules".

**Comment by jackpoz** [comment]
Does removing the flag change anything even the spell doesn't miss ? Like with projectiles and such

**Comment by tarwyn** [comment]
@jackpoz Not that I can see or notice. Everything behaved as it should during my tests with the code in question removed. 

The custom attribute SPELL_ATTR0_CU_NO_INITIAL_THREAT is used - apart from its definition in SpellInfo.h - only once in Spell::HandleThreatSpells() and once in SpellMgr.cpp (in the above code snippet). 

In the current TDB this custom flag is applied to the spell Magma Totem (8187 for example), where it actually makes sense.

**Comment by jackpoz** [comment]
Would you like to open a PR with your changes ?
