### ISSUE TITLE
Quest: Triangulation Point One -- visual marker is not displayed

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23812]
**Description:**

In quest https://www.wowhead.com/quest=10269/triangulation-point-one, the red marker is not shown under the effects of https://www.wowhead.com/spell=34830/triangulation-point-one

You still receive quest credit when you walk on the right spot

**Expected behaviour:**

The red visual should be displayed under the effects of https://www.wowhead.com/spell=34830/triangulation-point-one

Item : https://www.wowhead.com/item=28962/triangulation-device

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9f66158ae552ea8195e870703f55f0a4483745d0

**Operating system:** Win 10 x64

**Comment by schell244** [comment]
Confirmed.
TrinityCore rev. ed2c2941a74e 2019-11-05
