### ISSUE TITLE
Summoned Guardians doing only 1 melee damage

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23811]
**Description:**

I have been noticing that creatures such as https://www.wowhead.com/npc=21267/mana-beast (Sunfury Nethermancer's guardian), and even guardians spawn via quest such as https://www.wowhead.com/npc=20603/reflection-of-ya-six are only doing 1 damage on melee hit. 

I searched if the same issue was already posted, but only found this one #281 which talks about overpowerd minions.

EDIT: They also hit regularly for 2 dmg and 6 on a crit.

**Expected behaviour:**

Summoned guardians should have a melee damage output appropriate for their level.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9f66158ae552ea8195e870703f55f0a4483745d0

**Operating system:** Win 10 x64

**Comment by jackpoz** [comment]
what level are you ? what level is the target ?

**Comment by TerrorBringer** [comment]
I am level 70, Mana beast is 69-70, Image of Agent Ya-six is 68.

**Comment by jackpoz** [comment]
could you try reverting https://github.com/TrinityCore/TrinityCore/commit/5f5d2028df70e82d5cd70837953acd059f2ac7fb and see if anything changes ?

**Comment by TerrorBringer** [comment]
I tried rev 50b2c3b34d5ffc9539e3f3954ec6b4e5f8a87efc, which came before 5f5d202, the Mana beast is hitting 60-70 dmg on armor that provides a 41% damage reduction.

**Comment by jackpoz** [comment]
@Wyrserth could you take a look at this ?

**Comment by jackpoz** [comment]
I have a local fix that I will PR in a few days.
With a level 80 character with no gear https://www.wowhead.com/npc=21267/mana-beast does:
- 3 damage with current TC
- 105 damage with a patch
- 60 damage with another patch

The summoner does 250 damage. Which one seems more correct ?

**Comment by Killyana** [comment]
105 according to videos. https://youtu.be/hE_xK-qpas8

**Comment by jackpoz** [comment]
I opened a PR for this, please test it https://github.com/TrinityCore/TrinityCore/pull/23840

**Comment by Killyana** [comment]
The damage looks fine

**Comment by jackpoz** [comment]
is there any other guardian to test ?
- did I cause some guardians to do too much damage ?
- are there still guardians with too little damage ?

or should we merge the PR ?

**Comment by Jinnaix** [comment]
I had a report a while ago that [Sharam](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10718), summoned by [this item ](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12592) only hits for 2 damage. Maybe Killyana can check this one too.

**Comment by Killyana** [comment]
The damage of Sharam looks correct and scales properly according to the level.
I cannot find a case where the damage is too low or high.

**Comment by Aokromes** [comment]
b3b8ec8
