### ISSUE TITLE
wintergrasp

### ISSUE THREAD

**Issue by sawd14** [TrinityCore/TrinityCore#23819]
wintergrasp is bugged the door of the basement is invisible and the portals arent there too

**Comment by Aokromes** [comment]
your search engine is bugged too, and...

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L2713

>1 - (Enabled, Experimental as in **incomplete**, **bugged** and **with crashes**)

The config kinda tell you what to expect

**Comment by sawd14** [comment]
tnx guys 
love ya
sry about new issue
