### ISSUE TITLE
Quest: Triangulation Point Two -- visual marker is not displayed

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23813]
**Description:**

In quest https://www.wowhead.com/quest=10275/triangulation-point-two, the red marker is not shown under the effects of https://www.wowhead.com/spell=34857/triangulation-point-two

You still receive quest credit when you walk on the right spot

**Expected behaviour:**

The red visual should be displayed under the effects of https://www.wowhead.com/spell=34857/triangulation-point-two

Item : https://www.wowhead.com/item=29018/triangulation-device
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9f66158ae552ea8195e870703f55f0a4483745d0

**Operating system:** Win 10 x64

**Comment by Kitzunu** [comment]
Didn't https://github.com/TrinityCore/TrinityCore/commit/b28fbba3cdd208ca33d9d8c1c546e4fd60b61c92 fix this?

I haven't been able to check it yet but would assume so.

**Comment by Killyana** [comment]
Yes fixed.
