### ISSUE TITLE
worldserver Crash

### ISSUE THREAD

**Issue by sawd14** [TrinityCore/TrinityCore#23825]
when you make an alliance character and you want to make an other one as horde it should say that you cant make two faction in a account but it will stack on Creating Character and the worldserver will crash

![a](https://user-images.githubusercontent.com/14840739/65498686-33c74180-dec9-11e9-9506-488e5eaa7b72.PNG)
![s](https://user-images.githubusercontent.com/14840739/65498687-345fd800-dec9-11e9-8ac8-a0c7a2519aba.PNG)

**Comment by Aokromes** [comment]
cannot reproduce, also the 
"when you make an alliance character and you want to make an other one as horde it should say that you cant make two faction in a account" part was removed from blizzard's servers long time ago during wow 3.x

**Comment by illfated** [comment]
@sawd14 : There must be something else different with your core that you have not told us about. It is perfectly fine to create characters from both factions in the same account, unless you have modified your worldserver.conf file to block accounts from creating characters in more than 1 faction. We also need a debug crash log from you to be able to help you in the first place.

**Comment by r00ty-tc** [comment]
$ git log|grep 99617d0
<nothing>
Can't find that commit hash in 3.3.5.

**Comment by sawd14** [comment]
this is my crash report
[99617d019af0_worldserver.exe_[24-9_2-24-12].txt](https://github.com/TrinityCore/TrinityCore/files/3646420/99617d019af0_worldserver.exe_.24-9_2-24-12.txt)

**Comment by illfated** [comment]
The only commit to [`3.3.5`](https://github.com/TrinityCore/TrinityCore/tree/3.3.5) branch yesterday was https://github.com/TrinityCore/TrinityCore/commit/c8dc9fdc418d9703893e21603b7593b015f08fea
Please let us know what you modified in the source.
Otherwise, searching for clues will be pretty useless.

**Comment by r00ty-tc** [comment]
Not to put too fine a point on it...
`00007FF73877FCC1  00000084F257A1F0  SocialMgr::SavePlayerToDB+81  f:\trinitycore\src\server\game\entities\player\socialmgr.cpp line 63`

1: My line 63 is blank
2: Searching my 3.3.5 at c8dc9fdc418d9703893e21603b7593b015f08fea for SavePlayerToDB I came up with nothing.

So, I think this is something you've modified.

**Comment by r00ty-tc** [comment]
Ah, well. Probably back out the PR and see if it fixes the problem. If so, then report the crash in the comments to that PR.

**Comment by illfated** [comment]
Fair enough. Looks like the only unexpected part here was testing the PR contents, so my apologies if I was being too dismissive. Then again, it would help us a lot to know beforehand that the PR content was added to the main 3.3.5 source.
