### ISSUE TITLE
[3.3.5] Stormwind guards overpolite

### ISSUE THREAD

**Issue by HerrTrigger** [TrinityCore/TrinityCore#23824]
**Description:**

Stormwind guards emoting when they shouldn't.

**Current behaviour:**
Stormwind guards doing emotes when they pass you/you near them (human-lvl1): flex, bow, cheer, ...
Meanwhile Squire Rowe (edit: https://classic.wowhead.com/npc=17804/squire-rowe) mentions the following when talking to him:
_Hail, champion. The tale of your deeds will be told throughout the ages. Perhaps one day, a statue of you will stand amongst the heroes of Stormwind._

I first thought this being 'a new feature' related to running around on a gm account. ^^
But tried with a gmlevel 0 account: same behaviour.
Tested in goldshire, ironforge, .. : not happening - guards don't emote.

Looking this up, i've found very little, but i assume this to be related to some credit being given where it's not due yet (blackrock or onyxia related?).

Screenshot of Rowe, with a guard who was passing but stopped to flex (char = lvl1):
https://imgur.com/a/1TYGrdG

**Expected behaviour:**

Guards should not do this (yet).

**Steps to reproduce the problem:**

Create a human, head to stormwind, walk to guards.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 8e3862cfbd9e 2019-09-21 21:52:33 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Win10

TDB:
TDB 335.19091

Kind regards.

**Comment by illfated** [comment]
I admit that I have noticed this behaviour too during the last half year, but I thought this was because I had given my character the [Beastmaster Armor](https://wow.gamepedia.com/Beastmaster_Armor) (dungeon set 2), which normally is acquired at around level 60 in classic dungeons. From your report, this seems to happen without any special armor, so I wonder if there is something else causing this behaviour.

**Comment by ForesterDev** [comment]
`DELETE FROM `smart_scripts` WHERE `entryorguid` IN (68,1756,1976,3296,14304) AND `id` = 0;
DELETE FROM `conditions` WHERE `SourceEntry` IN (68,1756,1976,3296,14304) AND `SourceTypeOrReferenceId` = 22;
`
