### ISSUE TITLE
Scripts/The Mechanar: boss Nethermancer Sepethrea --  Raging Flames despawning

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23828]
**Description:**

When fighting https://www.wowhead.com/npc=19221/nethermancer-sepethrea, she immediately spawns 2 Raging Flames https://www.wowhead.com/npc=20481/raging-flames, which despawn in about 2-3 seconds after spawning.

**Expected behaviour:**

Raging Flames should never despawn.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/c8dc9fdc418d9703893e21603b7593b015f08fea

**Operating system:** Win 10 x64

**Comment by Riztazz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp#L196

change this line to instance->GetBossState(DATA_NETHERMANCER_SEPRETHREA) != IN_PROGRESS

**Comment by Keader** [comment]
746a1d89b34984f31ab66ef00e93a648dc42af5d
