### ISSUE TITLE
[master] 8.2.0 Bruteforce Data

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#23820]
**Description:**

Starting to provide bruteforced data.

- broadcast_text
  - enUS https://gist.github.com/funjoker/aab60321f226255f15c38165035112f0
  - frFR https://gist.github.com/funjoker/5287b6994676399c9d59c371dfb01e1d
  - deDE https://gist.github.com/funjoker/27faced3564b591f0a4774d99eb42d47
  - esES https://gist.github.com/funjoker/5fa870caa92dc0f0ea2c26633266e497
  - esMX https://gist.github.com/funjoker/efa8e6de46a4635a729e4e8b9b4cf027
  - ptBR https://gist.github.com/funjoker/792cf4083ff9ffd686c2d309f1449e8f
  - zhCN https://gist.github.com/funjoker/5a028c91ab699a300ac69538d7fd3ad6
  - zhTW https://gist.github.com/funjoker/47536a08272fdf2112e49ef7ae45fb5b
  - koKR https://gist.github.com/funjoker/20e4b91f199618cb811fa90a28244667
  - ruRU https://gist.github.com/funjoker/31c23946d1f388c99c7fa8827da253e5
  - itIT https://gist.github.com/funjoker/2756f179749c18ba0a3ecdef689569f0

- creature_template, creature_template_model, creature_questitem
  - enUS https://gist.github.com/funjoker/86c38f3104c9c1f4521825ae8c8f4e89
  - frFR https://gist.github.com/funjoker/07a6fed536abecc22844b7c6c317f7c6
  - deDE https://gist.github.com/funjoker/cf73ffb2050311a9d201d95f088a78ab
  - esES https://gist.github.com/funjoker/b1db16f2cbbf1c1120219701fd6640b3
  - esMX https://gist.github.com/funjoker/67c52c57d66cde21c9e5b09581d49665
  - ptBR https://gist.github.com/funjoker/71a6049d3df59e6a38fd9d7337171fcd
  - zhCN https://gist.github.com/funjoker/9773f7d2f361ac5b3474cce94ba73654
  - zhTW https://gist.github.com/funjoker/5c3af4368d437470264abc7725860ec4
  - koKR https://gist.github.com/funjoker/c37ffd50d6904c55aba07c8c9dc9c98c
  - ruRU https://gist.github.com/funjoker/64e901085421390f0d461add82f47efb
  - itIT https://gist.github.com/funjoker/20fe65bf0f1c87e5c19ac08c39cbd132

- quest_template
  - enUS https://gist.github.com/funjoker/b48f77d096c16ddb0e2d1d0f83da60f4
  - frFR https://gist.github.com/funjoker/75ca621a506ff073e739ba6d3fd193d9
  - deDE https://gist.github.com/funjoker/df7e5ccb6017cdc2852fba905f22ff33
  - esES https://gist.github.com/funjoker/6ae9724dab33c9166bd5604b44fe27f0
  - esMX https://gist.github.com/funjoker/375bea2407c1026c779394fed9ed1e11
  - ptBR https://gist.github.com/funjoker/ce0f3bffc4790e9051dc895cdd7b7604
  - zhCN https://gist.github.com/funjoker/8c3fe4304a3397ccab3fd0741b1526c7
  - zhTW https://gist.github.com/funjoker/245e7b3bc039aa7e378d2a8f55ca599e
  - koKR https://gist.github.com/funjoker/a690d5106c603649e307ee69ad9179ce
  - ruRU https://gist.github.com/funjoker/effa7f0fbd2abcff6c5c9252bb31350b
  - itIT https://gist.github.com/funjoker/c43ab0915769ef707d6b54a98d472752

- quest_poi  https://gist.github.com/funjoker/212bfc3d09f72bee6a30b7c04c2a0079
- quest_poi _points https://gist.github.com/funjoker/01586886b63094e7d6f282951b3f3987

**Branch(es):**

master

**TC rev. hash/commit:** 

c674a3a18843c79b133600667f0b2bfc4c3d6594

**Comment by jackpoz** [comment]
I would suggest to apply the same fix as https://github.com/TrinityCore/TrinityCore/commit/567d9a6113aafc1d12e325da362c5207f5cb5683 to not have the same issue again

**Comment by funjoker** [comment]
Updated them to be faster.

**Comment by funjoker** [comment]
Done

**Comment by funjoker** [comment]
Why do I even waste time into bruting and parsing and increasing speed at this sql stuff, when no one gives a fuck?

**Comment by jackpoz** [comment]
Usually fixes for 3.3.5 branch get merged faster than master branch ones. If you want to see these sql applied, you probably need to wait to get push access to the repo.

**Comment by Shauren** [comment]
There was a mistake in DELETE queries for broadcast_text ruRU and koKR where the first character of each id (1) was cut off

**Comment by Shauren** [comment]
All pushed

**Comment by msoky** [comment]
same as cherry-picking from 3.3.5...no one cares in this team...

**Comment by MaxtorCoder** [comment]
No one cares about SQL only fixes. These are hotfixes, which is basically required for the server/client.

**Comment by funjoker** [comment]
oh didnt see this mistake
