### ISSUE TITLE
[3.3.5] - DB/Locales: Rigid and Brilliant Stormjewel

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23823]
**Description:**

We have an incorrect locale description of the items:
Rigid Stormjewel ID 45987
Brilliant Stormjewel ID 45882

https://wow.gamepedia.com/Rigid_Stormjewel
https://wow.gamepedia.com/Brilliant_Stormjewel
In 3.3.5 should be yellow socket
In cata changed to blue and red socket

blue = azul
red = rojo
yellow = amarillo

we have in locale esES and esMX a description (color socket) of version 4.X or more (azul and rojo) should be amarillo

```sql
SELECT * FROM `item_template_locale` WHERE `ID` IN (45987,45882) AND (`locale`='esES' OR `locale`='esMX');
```

Result:

```
    ID  locale  Name                       Description                          VerifiedBuild  
------  ------  -------------------------  -----------------------------------  ---------------
 45882  esES    Joya de tormenta luminosa  Encaja en una ranura de color rojo.            15050
 45882  esMX    Joya de tormenta luminosa  Encaja en una ranura de color rojo.            15050
 45987  esES    Joya de tormenta rígida    Encaja en una ranura de color azul.            15050
 45987  esMX    Joya de tormenta rígida    Encaja en una ranura de color azul.            15050
```

Fix:

```sql
UPDATE `item_template_locale` SET `Description`='Encaja en una ranura de color amarillo.' WHERE `ID` IN (45882,45987) AND (`locale`='esES' OR `locale`='esMX');
```

**Branch(es):**  3.3.5

**TC rev. hash/commit:** c8dc9fdc418d9703893e21603b7593b015f08fea

TDB 335.19091

**Comment by Aokromes** [comment]
2e1a85d
