### ISSUE TITLE
Visual bug on last flight master point

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23829]
**Description:**

When you use a flight master taxi, on the last destination (when you land), the flying taxi does not come near the floor, you just go from mid-air to spawning besides the Flight Master.

Probably caused by this commit https://github.com/TrinityCore/TrinityCore/commit/cf3277c641bd877b9fa1939da5da7cde1778561b

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/c8dc9fdc418d9703893e21603b7593b015f08fea

**Operating system:** Win 10 x64

**Comment by jackpoz** [comment]
could you try reverting that commit locally and checking the behavior ?

**Comment by Killyana** [comment]
It's the correct behavior implemented by https://github.com/Wyrserth/TrinityCore/commit/aeed80b71b3e0c10c8364ee3a15c343f4bd02e46
Once at the last node the player will be teleport to the ground instead of falling.

**Comment by Killyana** [comment]
@TerrorBringer in which fly you noticed that?

**Comment by illfated** [comment]
> Edit: After [cf3277c](https://github.com/TrinityCore/TrinityCore/commit/cf3277c641bd877b9fa1939da5da7cde1778561b) the teleportation is done before reaching the last node

Hm, interesting. Does it need an additional spline to reach the destination flightpoint, then?

**Comment by jackpoz** [comment]
@Ovahlord can you take a look at this ?

**Comment by Ovahlord** [comment]
That's not caused by this. The change does not affect the destination of a spline. Kilyana already named what's causing this and apparently this seems to be intended behaivior. Nothing wrong here on my side

**Comment by TerrorBringer** [comment]
In https://github.com/TrinityCore/TrinityCore/commit/8e3862cfbd9ee677866fbbee60c3b96ee3f4868a, there is no issue in the last node.

**Comment by Shauren** [comment]
It actually does affect the destination, if you look at `FlightPathMovementGenerator::DoUpdate`, it increments `_currentNode` based on points given to spline init but runs MovementGenerator finalize logic based on `_path` which does not have any extra points (returning false from DoUpdate)
Result of that is that spline has correct destination but MovementGenerator interrupts it in DoFinalize

**Comment by Killyana** [comment]
@Ovahlord after https://github.com/TrinityCore/TrinityCore/commit/cf3277c641bd877b9fa1939da5da7cde1778561b the last node is skipped.

**Comment by Ovahlord** [comment]
Meh, so the entire path update procedure was built arround that mistake? Geez. I think I got an idea how to handle that

**Comment by Faq** [comment]
still happening after https://github.com/TrinityCore/TrinityCore/commit/c1e3d79a4fb5b7b1a9bca36ecd16b9bb902ced92 ?

**Comment by jackpoz** [comment]
try after https://github.com/TrinityCore/TrinityCore/commit/c1e3d79a4fb5b7b1a9bca36ecd16b9bb902ced92
