### ISSUE TITLE
[3.3.5] Resistences should be summed 

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#23837]
**Description:** 

I found some evidences that makes me belive that we calculate resistences wrong.
My search is based in Professor Putricide Abomination AOE Damage (SpellId = 70402).

Spell 70402 Mutated Transformation has SpellSchoolMask = 40 (**SPELL_SCHOOL_MASK_NATURE, SPELL_SCHOOL_MASK_SHADOW**)

Checking values resisted in warcraft logs, is impossible get that much in current TC implementation.
Based in [video1](https://www.youtube.com/watch?v=0ATe3lZpC_E) , [video2](https://www.youtube.com/watch?v=VPnpRetfP8M) and [warcraft logs](http://www.worldoflogs.com/reports/k9lp4yw68u6s1asl/xe/?s=2665&e=2977&x=spell+%3D+%22Mutated+Transformation%22%0D%0AAND+targetType+%3D+%27Player%27%0D%0AAND+targetName+%3D+%22Dabears%22%0D%0A%0D%0A)

On warcraft logs is possible get the follow values:

> 60% resist: [18:49:13.843] Mutated Abomination Mutated Transformation Dabears 1687 (R: 2717) ---> 2717/0.6 = 4528; 4528 - 2717 = 1811; 1811*.96*.97 = 1686, (truncation error of 1?)
> 
> 70% resist: [18:49:17.468] Mutated Abomination Mutated Transformation Dabears 1245 (R: 3121) ---> 3121/0.7 = 4459; 4459 - 3121 = 1338; 1338*.96*.97 = 1246﻿﻿, (trucation error of 1?)

That makes me belive that Resistences need be summed,  e.g. 90 Shadow Resist and 120 Nature Resist should result 210 resistence, not picket the minimum value (90 in this case)
Our implementation: 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L12896-L12905

How i belive that it should be:

```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index afe4ebe810..001fa184cb 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -12895,10 +12895,10 @@ void Unit::SendClearTarget()
 
 uint32 Unit::GetResistance(SpellSchoolMask mask) const
 {
-    int32 resist = -1;
+    int32 resist = 0;
     for (int32 i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; ++i)
-        if (mask & (1 << i) && (resist < 0 || resist > int32(GetResistance(SpellSchools(i)))))
-            resist = int32(GetResistance(SpellSchools(i)));
+        if (mask & (1 << i))
+            resist += int32(GetResistance(SpellSchools(i)));
 
     // resist value will never be negative here
     return uint32(resist);
```

**Steps to reproduce the problem:**

1. Put 2 friendly characters close
2. Add aura 70405 in one character
3. Check how much damage the other will take

_PS: Has other side effect of our current implementation.
If shaman put nature totem and have 0 resistence in shadow, it will always take full damage, since we always get the minimum value, and in this case is 0._

**Branch(es):** 3.3.5

**TC rev. hash/commit:** ef694cc251844d34a64ae03f79d28a5c76719f6b

**Comment by Shauren** [comment]
Definitely not. Chaos bolt is a prime example - it uses the lowest resistance

**Comment by Keader** [comment]
Chaos Bolt have only 1 School Mask (Fire) in 3.3.5
And ignore all resistences

**Comment by Shauren** [comment]
Also some spells use a different resistance calculation (makes them resist a lot more), sindragosa intro spell is one (script has full custom implementation)

**Comment by Keader** [comment]
You mean that Abomination spell need have a "custom resistence calculation"?

**Comment by Jildor** [comment]
What about Frostfire bolt by example? should get the lower target resistance until pandaria
https://wow.gamepedia.com/Frostfire_Bolt

**Comment by Jildor** [comment]
in the same log of main comment we can see this another spell with same schoolmask in the same player:
ID - 72273 Vile Gas
http://www.worldoflogs.com/reports/k9lp4yw68u6s1asl/xe/?x=spell+%3D+%22Vile+Gas%22%0D%0AAND+targetType+%3D+%27Player%27%0D%0AAND+targetName+%3D+%22Dabears%22

**Comment by Keader** [comment]
yeah, looks like a exception.
I will open a PR about it, when hacktoberfest start xD
