### ISSUE TITLE
Last version of TrinityCore 3.3.5 authserver launch failure

### ISSUE THREAD

**Issue by Abjorge95** [TrinityCore/TrinityCore#23832]
**Description:**

Last version of TrinityCore 3.3.5 authserver launch failure

**Current behaviour:**

Shutdown authserver after boot

**Expected behaviour:**

Keep authserver running

TrinityCore rev. 965ec9a57180 2019-07-10 23:16:58 +0200 (3.3.5 branch)

**Operating system:** 

Ubuntu 17.10

**Error** 

TrinityCore rev. 965ec9a57180 2019-07-10 23:16:58 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (authserver)
<Ctrl-C> to stop.

Using configuration file /home/ajorge/server/etc/authserver.conf.
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.62.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.7.22
MySQL server ver: 5.7.22-0ubuntu0.17.10.1 
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.7.22
MySQL server ver: 5.7.22-0ubuntu0.17.10.1 
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
**In mysql_stmt_prepare() id: 11, sql: "SELECT a.id, a.username, a.locked, a.lock_country, a.last_ip, a.failed_logins, ab.unbandate > UNIX_TIMESTAMP() OR ab.unbandate = ab.bandate, ab.unbandate = ab.bandate, aa.gmlevel, a.token_key, a.sha_pass_hash, a.v, a.s FROM account a LEFT JOIN account_access aa ON a.id = aa.id LEFT JOIN account_banned ab ON ab.id = a.id AND ab.active = 1 WHERE a.username = ?"
Unknown column 'a.token_key' in 'field list'**
Closing down DatabasePool 'auth'.
Asynchronous connections on DatabasePool 'auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'auth' closed.
Could not prepare statements of the Login database, see log for details.
Closing down DatabasePool 'auth'.
Asynchronous connections on DatabasePool 'auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'auth' closed.

**Comment by Jinnaix** [comment]
You are missing a lot of Commits - your version of trinitycore is outdated by more than 3 months.

**Comment by Abjorge95** [comment]
Greetings,

I dont think so, i just updated it:

ajorge@lb0host01:~$ cd ~/TrinityCore/
ajorge@lb0host01:~/TrinityCore$ git reset --hard
HEAD is now at 176f51d1e8 DB/Creature: Remove wrong SAI from guards
ajorge@lb0host01:~/TrinityCore$ git pull origin 3.3.5
From https://github.com/TrinityCore/TrinityCore
 * branch                  3.3.5      -> FETCH_HEAD
Already up-to-date.
ajorge@lb0host01:~/TrinityCore$ cd build
ajorge@lb0host01:~/TrinityCore/build$ sudo cmake ../ -DCMAKE_INSTALL_PREFIX=/home/ajorge/server -DTOOLS=1
[sudo] password for ajorge:
-- Detected 64-bit platform
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- cotire 1.7.10 loaded.
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* TrinityCore revision   : 176f51d1e80d 2019-09-26 17:43:26 +0200 (3.3.5 branch)
* TrinityCore buildtype  : RelWithDebInfo

* Install core to        : /home/ajorge/server
* Install libraries to   : /home/ajorge/server/lib
* Install configs to     : /home/ajorge/server/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   program_options
--   iostreams
--   regex
-- Found OpenSSL library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found OpenSSL headers: /usr/include
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ajorge/TrinityCore/build
ajorge@lb0host01:~/TrinityCore/build$ sudo make -j 2
[  0%] Built target Detour
[  1%] Built target Recast
[  5%] Built target g3dlib
[  5%] Built target fmt
[  5%] Built target gsoap
[  8%] Built target jemalloc
[  9%] Built target argon2
[ 10%] Built target mpq
[ 10%] Built target revision_data.h
[ 14%] Built target common
[ 15%] Built target mapextractor
[ 18%] Built target database
[ 18%] Built target vmap4assembler
[ 19%] Built target vmap4extractor
[ 19%] Built target mmaps_generator
[ 20%] Built target shared
[ 20%] Built target authserver
[ 42%] Built target game
[100%] Built target scripts
[100%] Built target worldserver
ajorge@lb0host01:~/TrinityCore/build$ sudo make install
[  4%] Built target g3dlib
[  4%] Built target Detour
[  5%] Built target Recast
[  5%] Built target fmt
[  8%] Built target jemalloc
[  8%] Built target gsoap
[  9%] Built target argon2
[ 10%] Built target mpq
[ 10%] Built target revision_data.h
[ 14%] Built target common
[ 17%] Built target database
[ 18%] Built target shared
[ 40%] Built target game
[ 40%] Built target authserver
[ 97%] Built target scripts
[ 97%] Built target worldserver
[ 98%] Built target mapextractor
[ 98%] Built target vmap4assembler
[100%] Built target vmap4extractor
[100%] Built target mmaps_generator
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/ajorge/server/bin/authserver
-- Set runtime path of "/home/ajorge/server/bin/authserver" to "/home/ajorge/server/lib"
-- Installing: /home/ajorge/server/etc/authserver.conf.dist
-- Installing: /home/ajorge/server/bin/worldserver
-- Set runtime path of "/home/ajorge/server/bin/worldserver" to "/home/ajorge/server/lib"
-- Installing: /home/ajorge/server/etc/worldserver.conf.dist
-- Installing: /home/ajorge/server/bin/mapextractor
-- Set runtime path of "/home/ajorge/server/bin/mapextractor" to "/home/ajorge/server/lib"
-- Installing: /home/ajorge/server/bin/vmap4assembler
-- Set runtime path of "/home/ajorge/server/bin/vmap4assembler" to "/home/ajorge/server/lib"
-- Installing: /home/ajorge/server/bin/vmap4extractor
-- Set runtime path of "/home/ajorge/server/bin/vmap4extractor" to "/home/ajorge/server/lib"
-- Installing: /home/ajorge/server/bin/mmaps_generator
-- Set runtime path of "/home/ajorge/server/bin/mmaps_generator" to "/home/ajorge/server/lib"
ajorge@lb0host01:~/TrinityCore/build$

**Comment by Jinnaix** [comment]
Your problem is a missing change to your auth database introduced with 4211645834c467a03c60248e80818d3607be9ea7 
You always start your worldserver first to update sql files and structure.

**Comment by illfated** [comment]
Very good point. The local DB needs to be updated via SQL changes (done when starting Worldserver by default) before launching Authserver.
