### ISSUE TITLE
battlefield walls

### ISSUE THREAD

**Issue by sawd20** [TrinityCore/TrinityCore#23834]
we all know about bf walls and i found this 
https://github.com/zouzoul/TrinityCore/commit/cefcab32bbad8d4eadcc8d072da1932bcc4e23a3
and it seems to work fine with battlefield core

**Comment by Aokromes** [comment]
we all know about duplicate tickets.
https://github.com/TrinityCore/TrinityCore/issues/8661

**Comment by sawd20** [comment]
@Aokromes  maybe marge this with db? at least a lil help with doors and walls?

**Comment by illfated** [comment]
@sawd20 : That code is C++ code. If you would like to see it in the TC source, open a Pull Request for it (and be prepared to defend why it should be included).
