### ISSUE TITLE
Damage interrupts/cancels certain creature spells

### ISSUE THREAD

**Issue by sveN295** [TrinityCore/TrinityCore#23831]
**Description:**

Certain spells cast by bosses are interrupted/canceled when the boss takes damage.

**Current behaviour:**

1. Boss starts casting the spell.
2. Boss receives damage before the spell is completed.
3. Boss doesn't complete the spell, he cancels it instead.

Known affected spells:

Bellowing Roar ID: 22686 cast by Nefarian
https://www.wowhead.com/spell=22686/bellowing-roar

Veil of Shadow ID: 7068 cast by Nefarian
https://www.wowhead.com/spell=7068/veil-of-shadow

Eye Beam ID: 26134 cast by C'thun
https://www.wowhead.com/spell=26134/eye-beam

**Expected behaviour:**

1. Boss starts casting the spell.
2. Boss receives damage.
3. Boss finishes casting the spell regardless of taking damage or not.

**Steps to reproduce the problem:**

1. .go boss cthun
2. Engage the boss.
3. He starts casting Eye Beam (26134).
4. Damage him while he casts.
5. Spell gets interrupted.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 176f51d1e80d 2019-09-26 17:43:26 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.1c  28 May 2019)
Using Boost version: 1.66.0
Using MySQL version: 5.6.45
Using CMake version: 3.15.0
Compiled on: Windows 10.0.18362
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19091

**Operating system:** Windows 10 OS

**Comment by Ovahlord** [comment]
All these spells share the same interrupt flag so either is that interrupt flag deprecated (dirty dbc data for example) or it's handled incorrectly.

**Comment by OcelotGear** [comment]
Same for this spells with others interrupt flags
ICC Gunship mobs:
SPELL_SHOOT                             = 70162 Interrupt Flags: 0x00000009, AuraIF 0x00000000, ChannelIF 0x00000000
SPELL_HURL_AXE                        = 70161 Interrupt Flags: 0x00000009, AuraIF 0x00000000, ChannelIF 0x00000000
SPELL_BURNING_PITCH_A          = 70403 Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
SPELL_BURNING_PITCH_H          = 70397 Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000

ICC Spinestalker(Sindragosa Trash):
SPELL_BELLOWING_ROAR          = 36922 Interrupt Flags: 0x0000001F, AuraIF 0x00000000, ChannelIF 0x00000000

**Comment by Jildor** [comment]
This is caused by this: https://github.com/TrinityCore/TrinityCore/commit/45c5e1b9d63796d168339a44f63418f220cf2403#diff-4522eeffcbc961602e86620011a2d579L878 (Unit.cpp line 878 in commit)

We have this interruptflag:
https://github.com/TrinityCore/TrinityCore/blob/c715e635cf3feb50ac61d30659e614aaa2cc0c63/src/server/game/Spells/SpellInfo.h#L215

I'm triying to find a spell with only that interruptflag, but in 3.3.5 seems don't have any, we only have spells that contain that interruptflag and others, by example above listed spells

So maybe we need restore check and only interrupt if is a player?
```diff
         if (damagetype != NODAMAGE && damagetype != DOT && damage)
         {
-            if (victim != attacker && (!spellProto || !(spellProto->HasAttribute(SPELL_ATTR7_NO_PUSHBACK_ON_DAMAGE) || spellProto->HasAttribute(SPELL_ATTR3_TREAT_AS_PERIODIC))))
+            if (victim != attacker && victim->GetTypeId() == TYPEID_PLAYER && (!spellProto || !(spellProto->HasAttribute(SPELL_ATTR7_NO_PUSHBACK_ON_DAMAGE) || spellProto->HasAttribute(SPELL_ATTR3_TREAT_AS_PERIODIC))))
             {
                 if (Spell* spell = victim->m_currentSpells[CURRENT_GENERIC_SPELL])
                 {
```
