### ISSUE TITLE
Some quests not translated

### ISSUE THREAD

**Issue by aaaaadrien** [TrinityCore/TrinityCore#23836]
**Description:**

Some quests are not translated. this seems to be an issue on quests where the objective must be completed directly with the NPC.
The text is translated into the database.
`SELECT * FROM quest_template_locale WHERE id=5421`

**Current behaviour:**

For example 5421. The title is okay but text not. (need 5386 before)

**Expected behaviour:**

Have the translated text

**Steps to reproduce the problem:**

1. quest add  5386
2. go to desolace and talk to NPC 11317
3. See the problem

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

**Operating system:** Debian

**Comment by jackpoz** [comment]
which client language are you using ?

**Comment by aaaaadrien** [comment]
fr_FR

**Comment by Killyana** [comment]
100% of quests have missing : quest_offer_reward_locale and quest_request_items_locale (some German localization were added long time ago but only few)
For the 2 quest above:
``` sql
SELECT *  FROM `quest_offer_reward_locale`;
SELECT *  FROM `quest_request_items_locale`;

**Comment by aaaaadrien** [comment]
Okay, so i must import texts into quest_items_locale ?

**Comment by Killyana** [comment]
You can get this texts from wowhead (if available)
https://fr.classic.wowhead.com/quest=5386/la-prise-du-jour
Progrès=`quest_request_items_locale`
Achèvement=`quest_offer_reward_locale`

**Comment by aaaaadrien** [comment]
Thanks a lot !
I will patch my world DB

**Comment by RezoApio** [comment]
Are you interested in SQL files to make the updates? 
I could fork and add some sql to add the french translation and make a pull request.
Just let me know. Otherwise I would just update my own db. 

Take care

**Comment by Killyana** [comment]
Yes, if you have any locales put them into a git and link it, we don't use PRs for SQLs.

**Comment by RezoApio** [comment]
Hi. Here is my first take on it. [https://github.com/RezoApio/FixSQLfrFRTrinity](https://github.com/RezoApio/FixSQLfrFRTrinity)
Only the very first French quests as it seems the reload quest_template_locale is not reloading these sub tables so I have to CTRL-C and relaunch the worldserver. 

Would you know the correct reload command so I can fix this quicker?
Thanks a lot

**Comment by Exitare** [comment]
@RezoApio i think you should remove the “world.” database identifier. Otherwise it’s only working for dB’s which contain this specific schema.

**Comment by illfated** [comment]
True. Some people may have a different name for the world DB (or maybe more than 1 or 2 versions of that DB),
Anyway, the final solution will be entered into an SQL file targeting the world DB via its directory,
e.g. https://github.com/TrinityCore/TrinityCore/tree/3.3.5/sql/updates/world/3.3.5 (`sql/updates/world`)

**Comment by RezoApio** [comment]
Thanks
I will review the SQL you mention and make my files identical.

Any idea for the reloading?

**Comment by illfated** [comment]
Uhm... not quite sure what you are asking, do you mean DB reloading, like wiping and reloading your own world DB to test it again?

**Comment by RezoApio** [comment]
in the worldserver app, you can issue commands. Some of them are reload
commands. I assume they force a reload of the DB tables into the server so
the client will get the new values immediatly. However the tables I had to
modify (quest_offer_reward_locale and quest_request_items_locale) does not
seem to be reloaded by the reload quest_template_locale command.
That makes it a very cumbersome process to adjust translation as I need to
restart the server each time.
Hope this is clearer now

**Comment by illfated** [comment]
Good point. https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130013/World should list the world DB tables where the reloadable ones have got an **R** at the end.

From the page legend:
> **R** - Can be reloaded in game with .reload without restart.

When a table is listed as reloadable, you should (in theory) be able to reload it by using a command like
`> reload quest_template_locale `

Then again, if it does not work, I presume something may have changed since that list was made (I don't know how much or how little).

**Comment by RezoApio** [comment]
Did check the doc you mentioned. It is outdated.
For example the quest_template_locale table does not contain anymore the
columns Title_loc{n}. The ref is now done thru the ID + locale column for
this table and the 2 new tables I mention.

This probably explains why the reload does not work. Should I log an issue
over that? I do not feel confident enough to dig in the code source and try
to fix it myself

I have made a comment in the doc to mark it as outdated. With some help, I
could probably modify the doc pages to reflect this.

Cheers

**Comment by illfated** [comment]
I don't know if it needs to be reported as an issue that some tables are not reloadable. I am fairly sure one of the TC coders can comment here and tell you why many of the tables are not reloadable anymore.

**Comment by RezoApio** [comment]
OK I'll wait for someone from the dev team to comment. I have checked the
reload code in void ObjectMgr::LoadQuestLocales()  and it seems strange to
me so I'd like to review that before trying to make the reload change I
would need if I am to add the frFR missing locale.

**Comment by RezoApio** [comment]
Found it! There is a "reload all locales" command that makes the complete
call to the 3 required tables:
quest_template_locale, quest_offer_reward_locale, quest_request_items_locale.

I will test it on my server tonight and make sure it fixes the locale quest
dialog w/o rebooting. Will also rewrite my sql to the correct form and
rename the file with the proper convention.

**Comment by RezoApio** [comment]
The reloading command works like a charm.
I have fixed the syntax, renamed to your convention and added one translation.
Can you confirm this is ok like this? If yes, I'll make new files with new date names each time I work on the translation

**Comment by illfated** [comment]
Thank you for finding the current reload function for those tables. I should have known, but I have not spent enough time with the source or DB content during the last year. Well done.

I presume you are talking about https://github.com/RezoApio/FixSQLfrFRTrinity/commit/7f4cd65d8d9f55c1a166152e1aa009fd7c21f3b4 
(https://github.com/RezoApio/FixSQLfrFRTrinity/blob/master/2019_10_16_01_world.sql)

Let me suggest how to format the SQL for TC usage. Please note how we use the backquote/backtick ( **`** ) as seen below:
```mysql
-- Message de fin quête 1 Menace intérieure
DELETE FROM `quest_offer_reward_locale` WHERE `ID`= 783 AND `locale`='frFR';
INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
(783, 'frFR', 'Ah, parfait, un autre volontaire. Il y en a beaucoup qui se présentent comme vous, en ce moment. $B$BJ''espère que nous serons assez nombreux.$B$BLes terres humaines sont menacées de l''extérieur et nos principales forces sont rassemblées loin d''ici. En conséquence, des bandes de hors-la-loi corrompus prospèrent maintenant dans le pays.$B$BNous aurons à combattre sur tous les fronts, $N. Préparez vous à une longue campagne.',19091);

-- La première quête disait 6 alors que le compteur demande 8
UPDATE quest_template_locale set Objectives = 'Tuez 8 Vermines kobolds, puis revenez voir le Maréchal McBride' WHERE `locale`= 'frFR' and ID = 7;

-- Message de Fin Menace
DELETE FROM `quest_offer_reward_locale` WHERE `ID`= 7 AND `locale`='frFR';
INSERT INTO  `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
(7, 'frFR', 'Bien. Ces kobolds sont des voleurs et des lâches, mais en grand nombre ils deviennent dangereux. Et les humains de Hurlevent n''ont pas besoin d''une menace de plus.$B$BVous avez toute ma gratitude pour les avoir détruits.',19091);

-- pas de traduction du message intermédiaire
DELETE FROM `quest_request_items_locale` WHERE `ID`= 7 AND `locale`='frFR';
INSERT INTO `quest_request_items_locale` (`ID`, `locale`, CompletionText, `VerifiedBuild`) VALUES
(7, 'frFR', 'Comment se passe la chasse, $N ? Avez-vous trouvé et exterminé ces vermines ?', 19091);

-- Message de fin quête des loups
DELETE FROM `quest_offer_reward_locale` WHERE `ID` 5261 AND `locale`='frFR';
INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
(5261, 'frFR', 'C''est vrai. Je recherche quelqu''un qui pourrait chasser des loups pour moi ! Êtes-vous cette personne ?',19091);

-- Intermédiaire Quetes Loup
DELETE FROM `quest_request_items_locale` WHERE `ID`= 33 AND `locale`='frFR';
INSERT INTO `quest_request_items_locale` (`ID`, `locale`, CompletionText, `VerifiedBuild`) VALUES
(33, 'frFR', 'Hé, $N. Comment se passe la chasse des loups malades ?', 19091);

-- Fin Quetes Loup
DELETE FROM `quest_offer_reward_locale` WHERE `ID`= 33 AND `locale`='frFR';
INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
(33, 'frFR', 'C''était une tâche sinistre mon ami, mais vous avez respecté votre part du contrat.$B$BJ''ai quelques trucs qui pourraient vous servir. Faites votre choix !', 19091);

-- Lettre Consacrée
DELETE FROM `quest_request_items_locale` WHERE `ID`= 3101 AND `locale`='frFR';
INSERT INTO `quest_request_items_locale` (`ID`, `locale`, CompletionText, `VerifiedBuild`) VALUES
(3101, 'frFR', 'Enfin ! Nous sommes face à face, de frère à frère. Bienvenue à Comté-du-Nord, qui sera votre foyer le temps d''apprendre les ficelles du métier. Mais sachez que Hurlevent n''est pas loin et tôt ou tard, votre chemin vous y ménera. En attendant, soyez patient... chevalier de la Main d''Argent', 19091);

DELETE FROM `quest_offer_reward_locale` WHERE `ID`=  AND `locale`='frFR';
INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
(3101, 'frFR', 'Dans le même temps, vous devez savoir autre chose. Vous êtes un symbole pour beaucoup sur ces terres : agissez en conséquence. La Lumière Sacrée brille à travers vous, et cela sera évident aux yeux de vos alliés comme à ceux de vos ennemis.$B$BAussi, à mesure que vous gagnerez en sagesse et en puissance, vous devrez apprendre de nouvelles compétences. C''est à ce moment que j''interviendrai. Quand vous sentirez avoir gagné de l''expérience ici, à Comté-du-Nord, revenez me voir et je vous apprendrai ce dont je vous sens capable de maîtriser. Bonne chance… $C !', 19091);
```
(The SQL content above needs to be verified before implementing. I do not speak French fluently.)

**Comment by RezoApio** [comment]
Thanks for the editing. I will use this from now on.

**Comment by illfated** [comment]
Just a last minute tip regarding use of apostrophes in text lines: You can surround the text with double quotes ( **" "** ) to avoid having to use double apostrophes for escaping the actual apostrophes in the text. Example:
`"C'était une tâche sinistre mon ami, mais vous avez respecté votre part du contrat.$B$BJ'ai quelques trucs qui pourraient vous servir. Faites votre choix!"`

**Comment by RezoApio** [comment]
I have pushed the files with the new syntax.
I have also modified the README.md file to explain I am testing the file vs
the DB with a command line.

I will now work on a python script to get that automatically from some
source.

**Comment by illfated** [comment]
Nice and good. I like the fact that you are working on multiple ways to use the data, taking advantage of multiple tools and sources of knowledge. Well done.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23836#issuecomment-542874465 is ready to go?

**Comment by RezoApio** [comment]
Sorry I got badly side tracked on that project. Also it is not easy to find the correct KB for the french version of 3.3.5.
Let me know if you consider this important and I will try to find time to get the correct translation.

**Comment by offl** [comment]
Locales for classic-only quests can be parsed from classic wowhead, all quest locales from TBC and WotLK can be parsed from actual wowhead.
> Let me know if you consider this important and I will try to find time to get the correct translation.

I'd like to say it's always good to have more things in DB but mostly we are focused on english texts. If you have enough time and knowledge and if you're interested in this, you can try to parse all locales from wowhead

**Comment by illfated** [comment]
@RezoApio : Please also note that you are welcome to post suggested SQL solutions for a small-to-medium amount of quests, to make your job a little bit easier.

Notice also the amount of esES / esMX translations posted as individual tickets:
- https://github.com/TrinityCore/TrinityCore/search?q=DB%2FLocale%2FesES%2BesMX+Texts+missing+in+quests&type=Issues
