### ISSUE TITLE
[3.3.5] Quest: Deactivate An'owyn (ID: 9169) 

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#23849]
**Description:**
Questitem (Crystal Controlling) to finish quest does not drop (or drop chance is to low?)
IDs:
(quest) Deactivate An'owyn  = 9169
(npc) Sentinel Infiltrator        = 16333
(item) Crystal Controlling      = 23191

**Current behaviour:**
Questitem does not drop from Sentinel Infiltrator 

**Expected behaviour:**
Questitem drops with a drop chance of 15.69% from Sentinel Infiltrator
according to https://www.wowhead.com/item=23191/crystal-controlling-orb

**Steps to reproduce the problem:**
1. Accept quest Deactivate An'owyn in Ghostlands
2. Go to object point, kill npc's around -> look for loot

**Branch(es):**
Tested on branch 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. ef694cc25184 2019-09-28 15:45:25 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 
Win10

**Comment by Aokromes** [comment]
11% acording db.

**Comment by Killyana** [comment]
Drop rate correct: https://www.wowhead.com/item=23191/crystal-controlling-orb#comments:id=2860669
