### ISSUE TITLE
Player ClassLevelStats / Pet LevelStats

### ISSUE THREAD

**Issue by TheNeoTV** [TrinityCore/TrinityCore#23841]
**Description:**

There are some missing levelstats for players, creatures and some other stuff.

**Current behaviour:**

Previev Player ClassLevelstats (NOT LEVELSTATS, it is different) : https://i.imgur.com/QI3nDYc.png
Previev Pet Levelstats : https://i.imgur.com/9avRjj0.png

**Expected behaviour:**

Should have any stats completed to guarantee a blizzlike feeling without missing stats and wondering why something is incorrect.

**Steps to reproduce the problem:**

Check the database yourself if you think i am wrong. Level 70 stats on 3.3.5A? No!

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ef694cc25184 2019-09-28 15:45:25 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
ef694cc25184

**Operating system:**
Linux Debian 9 x64

**Comment by Aokromes** [comment]
https://i.imgur.com/H2959Rw.png
https://i.imgur.com/Ur3Oxws.png
