### ISSUE TITLE
[3.3.5] Core / ? - Issues on Fly command.

### ISSUE THREAD

**Issue by TheNeoTV** [TrinityCore/TrinityCore#23848]
**Description:**

If someone uses the fly command the people will stuck in the air.

**Current behaviour:**

https://dl.dropboxusercontent.com/s/x0o9tn01onzh4mw/l5u4dm7EJ4.mp4 (Video can be played without any download)

**Expected behaviour:**

Should not lagg

**Steps to reproduce the problem:**

1. Join with a friend into the server enable fly on you and let him see what happend. Seems like bullshit ethernet connection but thats not the point

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

![Server Debug Command](https://i.imgur.com/X9Zm9e3.png)

**Operating system:** 
Debian 9 x64

**Comment by Killyana** [comment]
I cannot reproduce

**Comment by TheNeoTV** [comment]
But you see that Video? I dont dream, we have both 400.000 ethernet line and a real dedicated server not vserver. server has 1gb network.

**Comment by illfated** [comment]
I just tested this myself with a lousy laptop from 2012 and cable internet, logging in to https://tcubuntu.northeurope.cloudapp.azure.com/ with a GM account and a normal account. The GM character correctly displays the "swimming" animation in the air and only walks when fully touching the ground. The issue must be something with one of your game clients, either settings, addons or other local software.

![image](https://user-images.githubusercontent.com/38162891/66088073-14d84780-e57a-11e9-991d-8ad49dfa0bce.png)
