### ISSUE TITLE
DB/Quest - A Necessary Distraction - cosmetic bug

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23857]
**Description:**

In quest https://www.wowhead.com/quest=10688/a-necessary-distraction, you must unbanish
https://www.wowhead.com/npc=21506/azaloth, but he is already unbanished and aggros players if you get too close to him.

Quest credit is given as it should.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/ef694cc251844d34a64ae03f79d28a5c76719f6b

**Operating system:** Win 10 x64

**Comment by dr-j** [comment]
My guess auras been removed on evade as banish aura is in creature_template  addon sai is only to remove it on spellhit

**Comment by illfated** [comment]
Maybe there is something I have misunderstood there, but does that imply that Azaloth is somehow stuck in evade instead of being Out Of Combat?

**Comment by dr-j** [comment]
No it just means the npc is spawned without aura not sure but there was issue with some spells causing a tick of combat then evading and causing aura to be removed.  Know I have seen this when auras get removed instantly when they should not or so that aura does not get removed npc needs to be in combat

**Comment by illfated** [comment]
Thank you for the explanation. Would it help to move or add the aura to `creature_addon` instead of (or in addition to) the table `creature_tempalte_addon` for this creature?

**Comment by dr-j** [comment]
Don’t think will make difference since there is only one spawn of this npc creature adding is used when there’s more than one spawn of entry with different addon data

**Comment by illfated** [comment]
Very well. Thanks again for replying with a good explanation.
Does it need to be scripted instead, making the NPC re-add the aura when going back into its OOC state?

**Comment by dr-j** [comment]
It will probably work if you had a sai on reset (event 25) to cast the banish spell I may look at this may need a linked event to the on spellhit event to attack invoker otherwise if npc does not enter combat when quest item used may banish again will have to check it out eventually

**Comment by illfated** [comment]
Fair enough, very well. Just be aware that using "attack invoker" might backfire if the player perspective gets mixed into this. The goal of this quest is to make Azaloth attack his captors (the nearby demon hunter trainees).

**Comment by dr-j** [comment]
Well seems I scripted this originally do the warlocks there still cast at him

https://github.com/TrinityCore/TrinityCore/commit/d097f4d0b00610d14fc4e42edf27cfba29ef34d9

**Comment by illfated** [comment]
OK, so that should take care of the question of which creature(s) will register as triggering aggro in Azaloth. Fair enough.

**Comment by dr-j** [comment]
~~~sql
UPDATE `smart_scripts` SET `link`='3' WHERE  `entryorguid`=21506 AND `source_type`=0 AND `id`=1 AND `link`=0;
UPDATE `smart_scripts` SET `action_param1`='0' WHERE  `entryorguid`=21506 AND `source_type`=0 AND `id`=1 AND `link`=3;

DELETE FROM `smart_scripts` WHERE `entryorguid` =21506 AND `source_type`=0 AND `id`IN(2,3,4,5,6,7,8,9);
DELETE FROM `smart_scripts` WHERE `entryorguid` =21503 AND `source_type`=0 AND `id`IN(7,8,9);

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(21506, 0, 2, 0, 23, 0, 100, 512, 38722, 4, 5000, 5000, 0, 11, 37833, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - On Spellhit - Cast Banish '),
(21506, 0, 3, 4, 61, 0, 100, 512, 0, 0, 0, 0, 0, 19, 512, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - On Spellhit - Remove NPC Flag immune to NPC'),
(21506, 0, 4, 9, 61, 0, 100, 512, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 9, 21503, 0, 50, 0, 0, 0, 0, 0, 'Azaloth - On Spellhit - Set Data to Sunfury Warlock'),
(21506, 0, 5, 0, 38, 0, 100, 512, 2, 2, 0, 0, 0, 18, 512, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - On Data Set - Set Immune to NPC'),
(21506, 0, 6, 0, 9, 0, 100, 512, 0, 5, 8000, 15000, 0, 11, 40504, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - On Range - Cast Cleave'),
(21506, 0, 7, 0, 0, 0, 100, 512, 8000, 8000,8000 , 12000, 0, 11, 11443, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - IC - Cast Cripple'),
(21506, 0, 8, 0, 0, 0, 100, 512, 5000, 10000, 12000 , 15000, 0, 11, 38741, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - IC - Cast Rain of Fire'),
(21506, 0, 9, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 11, 38750, 0, 0, 0, 0, 0, 19, 21503, 0, 0, 0, 0, 0, 0, 0, 'Azaloth - On Spellhit - Cast Warstomp'),
(21503, 0, 7, 8, 38, 0, 100, 0, 1, 1, 1000, 1000, 0, 92, 0, 38722, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Sunfury Warlock - On Data Set - Interrupt Cast'),
(21503, 0, 8, 9, 61, 0, 100, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 19, 21506, 0, 0, 0, 0, 0, 0, 0, 'Sunfury Warlock - On Data Set - Start Attack'),
(21503, 0, 9, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 45, 2, 2, 0, 0, 0, 0, 19, 21506, 0, 0, 0, 0, 0, 0, 0, 'Sunfury Warlock - On Respawn - Set Data');

**Comment by illfated** [comment]
Looks very good to me. As a person on the autism spectrum and with a small degree of OCD when it comes to details, I would suggest extra details in 3 of the comment lines:
```sql
'Azaloth - On Spellhit - Cast Warstomp (target: Sunfury Warlock)'),
'Sunfury Warlock - On Data Set - Start Attacking Azaloth'),
'Sunfury Warlock - On Respawn - Set Data to Azaloth');
```
You may of course choose to ignore my suggestions, or modify some information differently.

**Comment by dr-j** [comment]
Yes will update tomorrow comment for line to cast banish is wrong I changed it to has aura so that could specify 4 stacks.  I originally tried with spellhit but then only one warlock would channel and rest would keep on failing to channel.  Banish must be cast after all the warlocks start channeling otherwise the warlocks channel will fail if they cast after azaloth has cast banish

**Comment by Rushor** [comment]
this can be pushed @dr-j ?

**Comment by illfated** [comment]
Thank you to everyone involved. Good job.
