### ISSUE TITLE
[DB/Quest] Path of the Mage and Assassin can be taken simultaneously

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23851]
**Description:**

When completing the Violet Eye quests in Karazhan, you can simultaneously choose two paths and therefore have 2 epic rings.

I chose https://www.wowhead.com/quest=10731/path-of-the-violet-assassin, and then I could get the following 2 quests: https://www.wowhead.com/quest=10735/down-the-violet-path and https://www.wowhead.com/quest=10733/down-the-violet-path

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/ef694cc251844d34a64ae03f79d28a5c76719f6b

**Operating system:** Win 10 x64

**Comment by Kitzunu** [comment]
Fix:
```sql
UPDATE `quest_template_addon` SET `PrevQuestID` = 10729 WHERE `id` = 10733;
```
