### ISSUE TITLE
[3.3.5] - DB/Creature: ICC Ice Sphere exp

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23859]
**Description:**

https://www.wowhead.com/npc=36633/ice-sphere

NPC Ice Sphere of ICC - LK encounter have flags_extra CREATURE_FLAG_EXTRA_NO_XP_AT_KILL
With this flag, doesn't get exp when die, then, can't proc Rapid Killing.

in this log we can see how should proc Rapid Killing after kill Ice Sphere:
http://www.worldoflogs.com/reports/b0e71guud7hcynf1/xe/?s=9921&e=10899&x=targetName%3D%22Rogerbrown%22+AND+spell+%3D+%22Rapid+Recuperation%22+OR+spell+%3D+%22Rapid+Killing%22+OR+targetName+%3D+%22Ice+Sphere%22+
```
[20:35:44.037] Jûstwait Auto Shot Ice Sphere 3992 (O: 182)
[20:35:44.312] Ice Sphere dies
[20:35:44.426] Jûstwait gains Rapid Killing from Jûstwait
```

**Fix:**

```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra` &~64 WHERE `entry` IN (36633,39305,39306,39307);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 88317a4ec8a4fae2f914fb699e8fb0fff1da3205

**Comment by Killyana** [comment]
The flag was taken from sniffs

**Comment by Jildor** [comment]
You can see the logs, talent proc when hunter kill the NPC, so, should give exp

**Comment by Killyana** [comment]
The check used to proc the talent is wrong, it must ignore CREATURE_FLAG_EXTRA_NO_XP_AT_KILL if the creature has non gray level for the player.
There's a lot creatures that has CREATURE_FLAG_EXTRA_NO_XP_AT_KILL in raids/dungeon specially the summoned ones

**Comment by Jildor** [comment]
So, you're saying if victim is non gray level diference should ignore this check?
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L510-L514

**Comment by Killyana** [comment]
No, I mean CREATURE_FLAG_EXTRA_NO_XP_AT_KILL must only block XP attribution and not procs.

**Comment by Jildor** [comment]
This check it´s only for not proc if has PROC_ATTR_REQ_EXP_OR_HONOR (Proc flag 0x00000002) and victim give or not give exp.

So, if ignore this check, creature still block XP attribution but can proc.

**Comment by Killyana** [comment]
But it will ignore Honor check, what must be done is exclude CREATURE_FLAG_EXTRA_NO_XP_AT_KILL from PROC_ATTR_REQ_EXP_OR_HONOR.

**Comment by Jildor** [comment]
So, you're saying we should remove this:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellMgr.cpp#L1866-L1867

**Comment by Killyana** [comment]
In player.cpp, line 23765
this must be removed:
``` cpp
if (Creature const* creature = victim->ToCreature())
    {
        if (!creature->CanGiveExperience())
            return false;
    }

**Comment by Jildor** [comment]
Yep, maybe can be ok.

Let's wait to see what say @Keader or anyone xD

**Comment by Keader** [comment]
since when extra flags is sniffed?

**Comment by Jildor** [comment]
Dup: #23860
(generic issue)
