### ISSUE TITLE
Jaedenar Cultist and Adepts cast spells while these are in polymorph

### ISSUE THREAD

**Issue by ArgonHC** [TrinityCore/TrinityCore#23863]
**Description:**

Jaedenar Cultist (7112) and Jaedenar Adepts (7115) cast spells while these are in polymorph.

**Expected behaviour:**

Both should not be able to cast while being in polymorph.

**Steps to reproduce the problem:**

1. Step 1 .tele test
2. Step 2 .learn 12826
3. Step 3 .npc add 7112
4. Step 4 get agrro and cast Polymorph
5. Step 5 check log

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 16fde1ffad38 2019-10-02 16:50:45 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:** Debian 9

**Comment by ArgonHC** [comment]
It looks like it's a general problem with polymorph. Deadwood Shaman's (7158) Chain Lightning (12058) is also affected.

**Comment by CraftedRO** [comment]
6e07acbbdeb5 Can't confirm this :


https://user-images.githubusercontent.com/24683355/140057377-b772fdd7-c2e2-4a9d-9d29-32d33e2fb666.mp4


https://user-images.githubusercontent.com/24683355/140057393-d2c55c78-dad2-416b-9277-327127bd7aba.mp4
