### ISSUE TITLE
[3.3.5] - Spell/Proc: Proc spells vs CREATURE_FLAG_EXTRA_NO_XP_AT_KILL

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23860]
**Description:**

https://www.wowhead.com/npc=39190/wicked-spirit

NPC Wicked Spirit of ICC - LK encounter have flags_extra CREATURE_FLAG_EXTRA_NO_XP_AT_KILL
With this flag, doesn't get exp when die, then, can't proc Rapid Killing.

in this log we can see how should proc Rapid Killing after kill Wicked Spirit:
http://www.worldoflogs.com/reports/b0e71guud7hcynf1/xe/?s=9921&e=10899&x=targetName%3D%22Rogerbrown%22+AND+spell+%3D+%22Rapid+Recuperation%22+OR+spell+%3D+%22Rapid+Killing%22+OR+targetName+%3D+%22Wicked+Spirit%22+&page=1
```
[20:41:47.479] Rogerbrown Chimera Shot Wicked Spirit *8000* (O: 7279)
[20:41:47.732] Wicked Spirit dies
[20:41:47.789] Rogerbrown's Rapid Killing fades from Rogerbrown
[20:41:47.789] Rogerbrown's Rapid Recuperation is refreshed by Rogerbrown
[20:41:47.789] Rogerbrown gains Rapid Killing from Rogerbrown
```

**Fix:**

```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra` &~64 WHERE `entry` IN (39190,39287,39288,39289);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 88317a4ec8a4fae2f914fb699e8fb0fff1da3205

**Comment by Killyana** [comment]
The flag was taken from sniffs

**Comment by Jildor** [comment]
You can see the logs, talent proc when hunter kill the NPC, so, should give exp

**Comment by Shauren** [comment]
flags_extra isnt taken from sniff, thats our custom field

**Comment by Killyana** [comment]
From creaturedifficulty:  CREATURE_DIFFICULTYFLAGS_NO_EXPERIENCE
Don't know if they ar sniffs of client data

**Comment by Jildor** [comment]
I don't know very well for what is those flags, but seems master data not 3.3.5 data

**Comment by Keader** [comment]
Make total sense to master, since has level > 80
To wotlk, makes no sense.

**Comment by Killyana** [comment]
Here an example of Summoned NPC that mustn't give exp in wotlk: https://woehead.way-of-elendil.fr/?npc=26746 but talent that proc on kill if the npc in not gray must be triggered.

**Comment by Jildor** [comment]
But where do you get that information about this NPC should proc spells that should have proc on kill only when the npc is not gray?

**Comment by illfated** [comment]
Good point, you would not be able to make the NPC a "gray" level without having a player character level 85 or higher.

**Comment by RR2739-VCN** [comment]
Extra flags from sniffs? I dont think so. 
Makes no sense whats so ever

**Comment by Shauren** [comment]
@RR2739-VCN  CREATURE_DIFFICULTYFLAGS_NO_EXPERIENCE is a sniffed value and flags_extra was set based on that, it is correct here.

**Comment by Jildor** [comment]
But sniffed from 3.3.5 version?

Anyway, what can be the proper fix here?
