### ISSUE TITLE
[3.3.5a] Quest - It Goes to 11 [Howling Fjord] Not Working

### ISSUE THREAD

**Issue by Lhalyna** [TrinityCore/TrinityCore#23867]
**Description:**

Lieutenant Icehammer in the Howling Fjord wants you to destroy the Dragonflayer Longhouse, Dragonflayer Dockhouse, Dragonflayer Storage Facility and 8 Dragonflayer Defenders.

Control of the nifflevar harpoon to destroy everything is not working

**Steps to reproduce the problem:**

1. Accept the quest It Goes to 11
2. Go to the nifflevar harpoons
3. try to take the control of the harpoon

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/6844
