### ISSUE TITLE
[3.3.5] - Unexplained buff on Warlock's Imp Stats

### ISSUE THREAD

**Issue by JoeGamer905** [TrinityCore/TrinityCore#23865]
**Description:**

Human Warlock's imp stamina and intellect stats have an unexplained buff.

**Current behaviour:**

Human Warlock (other races not tested) imp minion's stamina and intellect stats are buffed (GREEN on pet tab) and the buff scales with leveling. This buff gives the imp a health pool that is 3.5x's that of the Warlock and allows the imp to solo all the mobs at it's current level. This happens with an unbuffed, naked Warlock at low levels 1 - 10 (above level 10 not tested).

The minions base stats are those found in the pet_levelstats table. These stats are showing as the base stats but then a +n buff is added (eg. +18 sta adding 151 heath).

**Expected behaviour:**

I would expect the minions unbuffed stats to be those found in the pet_levelstats table.

**Steps to reproduce the problem:**

1. Create a Human Warlock on a non-gm account and train the summon imp skill.
2. Summon Imp
3. Look at pet stats

**Branch(es):**

Unmodified 3.3.5 (Archived) (Server.log = TrinityCore rev. unknown 1970-01-01)
Using World DB: TBD 335.19091 

**TC rev. hash/commit:** 

_HASH                            "unknown"
_DATE                             "1970-01-01 00:00:00 +0000"
_BRANCH                       "Archived"
_FULL_DATABASE            "TDB_full_world_335.19091_2019_09_15.sql"
VER_FILEVERSION            0,0,0
VER_FILEVERSION_STR    "unknown 1970-01-01 00:00:00 +0000 (Archived branch)"

**Operating system:** Windows 10.0.18362

**Comment by JoeGamer905** [comment]
![Warlock 3](https://user-images.githubusercontent.com/56409768/66599589-95e2a080-eb71-11e9-96e3-eb8d964f3ec3.JPG)

**Comment by Jinnaii** [comment]
Not sure if this is intended or not.
But its valid on 30823f9b79b4ad16f96e90692a900f68a7f63c0a

Tested with Voidwalker.
Pet gets 2 Hidden auras :
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=18735 - this buffs stamina
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=18742 - this buffs intellect

**Comment by illfated** [comment]
Looking at the wowhead classic pages, those spells are:
- https://classic.wowhead.com/spell=18735/tamed-pet-passive-dnd
- https://classic.wowhead.com/spell=18742/tamed-pet-passive-dnd

Those pages list the modifier as -1, so I presume TC source needs to be corrected for those spells:
> Apply Aura: Mod Increase Maximum Health - %
> Value: -1%

> Apply Aura: Mod Increase Maximum Power - % (Mana)
> Value: -1%

Please note: for some reason, the Aowow pages don't list the relevant modifier value.

**Comment by Killyana** [comment]
The imp has this spell: https://woehead.way-of-elendil.fr/?spell=18737 used to scale the stamina according to the master
Also if you highlight the stamina of the human warlock level 3 it says: increase the stamina of your pet by 6.
So the stamina mustn't be only the value set on the DB.
