### ISSUE TITLE
[3.3.5] Dire Maul - Immol'thar - Pylons can't be deactivated

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#23861]
**Description:**
Currently it's not possible to fight Immol'thar in Dire Maul, because the "magic-wall" around  Immol'thar does not get removed, when all 5 pylons are cleared.

**Current behaviour:**
Killing all mobs around a pylon does not trigger anything.

**Expected behaviour:**
After killing all mobs around a pylon, the pylon should be disabled (also visibly).
When all 5 pylons are cleaned, the magic-wall which surrounds Immol'thar should disappear.

**Steps to reproduce the problem:**
1. Enter Dire Maul (West) 
2. Kill all mobs which surround the 5 pylons
3. Pylons don't get deactivated  -> magic-wall does not disappear

**Branch(es):**
Tested on 3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 88317a4ec8a4 2019-10-04 19:16:45 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 
Win10

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14685
