### ISSUE TITLE
Quest/Daily Blood is Thicker cant complete

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#23878]
**Description:**

Spell 63471 -Spawn Blood Pool dont work properly

**Current behaviour:**

You can get the aura Animal blood 46221 but when you jump in water spell 63471 dont spawn blood pool if you use .cast spell blood pool appear

**Expected behaviour:**

When you jump in water spell 63471 create blood pool.

**Steps to reproduce the problem:**

1. Quest add 
2. Kill any animal in Borean Tundra, you will get the aura Animal Blood
3. Jump in water, nothing happens only aura dissapear.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ef694cc25184 2019-09-28 15:45:25 +0200 (heads/3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows Server 2012 R2 DataCenter

**Comment by illfated** [comment]
(https://tcubuntu.northeurope.cloudapp.azure.com/)

TrinityCore rev. 69b7958ebceb 2019-10-21 10:19:52 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1b  26 Feb 2019 (library: OpenSSL 1.1.1b  26 Feb 2019)
Using Boost version: 1.67.0
Using MySQL version: 5.7.27
Using CMake version: 3.13.4
Compiled on: Linux 5.0.0-1023-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19101

[23:42:58] Well, I can confirm that it is not consistent and that it is easier to create a blood pool if your player character has got a pet of some sort. The pet will usually be able to create the blood pool, even if you can't do it with the your player character alone.

My workaround is to **use a flying mount and dismount 5-10 yards above the water**, just far enough from land to make it a practical fishing spot. It is also possible to take **a running jump from some cliffs** near the water (preferably with a horizontal drop into the water) and land in the water a couple of seconds after leaving the ground, thereby being able to produce the blood pool. Having a pet (like a hunter fighting pet), enables you to get 2 blood pools pretty close to each other, if you manage to enter the water far enough from land.

Walking directly from land into the water does not seem to produce a blood pool, so maybe the pool gets spawned behind the player, inside the ground layer the character walked out from?

**Comment by Killyana** [comment]
The gob spawns if you jump in the water, looks like the transition between ground and water make the spell fails to spawn the gob, or maybe it related to maps/vmaps

**Comment by Rushor** [comment]
remove the water check, since that is already handled in the auraremoveeffect of the spell itself

https://github.com/Rushor/TrinityCore/commit/e556afe5da2e1db7ba06f4885191021a42f07756
