### ISSUE TITLE
DB/Creature: Apprentice Mirveda (15402) SAI problem

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23875]
**Description:**

Apprentice Mirveda can bug out on her SAI script.
This may be a general SAI problem and not related to her particular script.

The Quest/SAI is not broken in general, im pointing to a case that leads to a bugged NPC.

**Current behaviour:**

Certain conditions while doing [Quest Unexpected Results](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8488) can lead to a bugged NPC.

**Expected behaviour:**

Should not happen.

**Steps to reproduce the problem:**

You need to start Unexpected Results for this.

.go c id 15402
.q a 8487
.q c 8487
this completes the prequest.
Talk to Mirveda, trade in the prequest and start Quest Unexpected Results

You can get a quick look at her SAI here : https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15402#sai-main

She will spawn 1 Gharsul the Remorseless and 2 Angershades.

There is one situation that can get her in a bugged state.
Step back a little so Gharsul the Remoresless starts attacking her. Then step forward to get Aggro from the 2 Angershades.
While she fights Gharsul, kill Gharsul. She keeps the dead body of Gharsul as target and dont interact with the situation that you being attacked by the Angershades. Then proceed and kill the 2 Angershades that are still attacking you.

She is now bugged out till a grid reload or until she gets killed and respawns or something like that.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

30823f9b79b4ad16f96e90692a900f68a7f63c0a

**Operating system:** Windows 10

**Comment by illfated** [comment]
Thank you for your research and for your due diligence in providing all the necessary information. 👍

**Comment by Rushor** [comment]
that issue is soooo old :o

**Comment by illfated** [comment]
Sure, but has it been looked into enough to know if this belongs in a more general issue ticket, maybe pointing to what the underlying cause might be? Do we have open tickets describing this well enough to be visible enough for someone to try finding out what can be done about the issue?

**Comment by Jinnaii** [comment]
I know that this quest was worked on several times already, latest in #20853
What i hope for is that this is a general SAI logic problem and not related this specific quest and that someone with more in-depth knowledge than me. I tried to debug it a bit but didnt found the exact problem.
Looks like that you can create a situation where the death of a creature does not increase the script related counter correctly. And therefore it can happen to all scripts that use this script mechanic.

**Comment by Killyana** [comment]
"She keeps the dead body of Gharsul as target and dont interact with the situation that you being attacked by the Angershades."

Wait until https://github.com/TrinityCore/TrinityCore/issues/18373 is fixed and test again

**Comment by Jinnaii** [comment]
Cant replicate this anymore on b3de6af.
