### ISSUE TITLE
DB/Spell | Talent : Rogue's Unfair Advantage (51672) does not counter-attack.

### ISSUE THREAD

**Issue by Jinnaii** [TrinityCore/TrinityCore#23873]
**Description:**

Talent Unfair Advantage does not trigger.

**Current behaviour:**

If you learned Talend Unfair Advantage and evade an enemies attack, Unfair Advantage nearly never triggers. I only got 1 or 2 situations where it proccs - no matter how often i evade attacks.
.list aura does show it correctly.

**Expected behaviour:**

Should work as described - evading an attack should result in a counter-attack in 100% of all cases with Talent rank 2 but only once per second.

**Steps to reproduce the problem:**

Level a rogue
Learn Unfair Advantage Rank 2
Fight a mob
Watch combat

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

30823f9b79b4ad16f96e90692a900f68a7f63c0a

**Operating system:** Windows 10

**Comment by Jildor** [comment]
Unfair Advantage have:
```
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0
```

So, if you are in range with victim > 0 can't hit to the victim
I don't know if this can be hacky or not:

```c
    ApplySpellFix({
        51675,  // Rogue - Unfair Advantage (Rank 1)
        51677   // Rogue - Unfair Advantage (Rank 2)
    }, [](SpellInfo* spellInfo)
    {
        spellInfo->RangeEntry = sSpellRangeStore.LookupEntry(2); // 5 yards
    });
```

**Comment by Keader** [comment]
Looks correct to me @Jildor , open a pr.

**Comment by Jildor** [comment]
Ok, done ;)
https://github.com/TrinityCore/TrinityCore/pull/23877

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e1df7b751e608020500d4bcb846327bfa252d3b6
