### ISSUE TITLE
Reliquary of the Lost 22856

### ISSUE THREAD

**Issue by Rokmusic** [TrinityCore/TrinityCore#23879]
Plese check - https://github.com/Rochet2/TrinityCore/issues/110

Hello,
I have encountered a problem while raiding in "The Black Temple" zone.

How to reproduce the bug:

Get inside "The Black Temple".
killed the first bosses :
High Warlord Naj'entus
Supremus
Shade of Akama
Teron Gorefiend
Gurtogg Bloodboil

Try to start "Reliquary of the Lost" Encounter
https://www.wowhead.com/npc=22856/reliquary-of-the-lost

What should happen, what happens instead:
You should be able to start the boss, or even target him. instead, you cant target the boss or start the actual boss event.

gm off.

Ty!

**Comment by illfated** [comment]
Please use the provided template for filling in the necessary information.

Edit your issue comment above, copy the text below and paste it into your comment field.
After that, please provide as much information as possible, for each of the steps and points.

```
<!--- (**********************************)
      (** Fill in the following fields **)
      (**********************************)
      For SQL fixes:
      don't modify WDB fields without supply one sniff of those fields (censure guids, character names, anything blizzard can use to identify source)
      don't use pull requests for sql only fixes, unless it's to fix one existing unable to apply file.
      don't hardcode guids.
      don't DELETE + INSERT to update only few fields of one row.
      don't use database names.
      don't put ' around numbers.
      don't put ( ) if they aren't needed.
      use only 1 DELETE + INSERT when we add multiple items to one table, unless you are scripting multiple creatures.
      put default values on every new column we want to add on that way we can make smallers inserts.
      start fix by -- in case some previous sql misses proper ending.
      DELETE by guid AND entry to be sure we don't delete existing spawns.
      start sql code with 3 ` sql         --->

**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS


<!--- Notes
- This template is for problem reports. For other types of report, edit it accordingly.
- For fixes containing C++ changes, create a Pull Request.
--->

```

**Comment by Killyana** [comment]
The first time you get close to the boss it will engage combat but nothing else happen, th second time it will not engage combat, also it doesn't despawn in evade:
Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Reliquary of the Lost (SpawnID 12828)
If I remove the immune to PC flag every issue is fixed:
``` sql
UPDATE creature_template SET unit_flags = unit_flags-256 WHERE entry = 22856;
```
The boss will always engage combat, and it will spawn the npc, and it will despawn in evade.
Something is wrong with npc with UNIT_FLAG_IMMUNE_TO_PC that enter combat with players.

**Comment by Killyana** [comment]
Changing https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_reliquary_of_souls.cpp#L159  to EngagementStart(nullptr); fix the issue but the boss will despawn upon the first reliquary beaten

**Comment by Keader** [comment]
I realy dont know what's the current state  of Threat/Combat stuff.
Just remember: that script was writed before Threat Rewrite and stuffs...
So... maybe @Treeston can take a look?

**Comment by Rushor** [comment]
why the boss even has UNIT_FLAG_IMMUNE_TO_PC ? it does not seem to be needed at all

maybe adding that new setimmune(false) to it

**Comment by Killyana** [comment]
It's correct according to sniffs: UNIT_FIELD_FLAGS: 33554752

**Comment by Rushor** [comment]
fix https://github.com/Rushor/TrinityCore/commit/0df3e6dccb1778d9d4082a342b560c431f764838

**Comment by Keader** [comment]
Hack '-'

**Comment by Rushor** [comment]
updated :( but well why is there a evadereason call on evade of the add summons when the main boss handles all despawn? :o

**Comment by Killyana** [comment]
The offline threat is causing this issue, allowing immune npc to have online threat fix some parts of the issue.
``` diff
diff --git a/src/server/game/Combat/ThreatManager.cpp b/src/server/game/Combat/ThreatManager.cpp
index 0743d70fd3..a4e5dfd94a 100644
--- a/src/server/game/Combat/ThreatManager.cpp
+++ b/src/server/game/Combat/ThreatManager.cpp
@@ -99,10 +99,10 @@ bool ThreatReference::ShouldBeOffline() const
 {
     if (!_owner->CanSeeOrDetect(_victim))
         return true;
-    if (!_owner->_IsTargetAcceptable(_victim) || !_owner->CanCreatureAttack(_victim))
-        return true;
-    if (!FlagsAllowFighting(_owner, _victim) || !FlagsAllowFighting(_victim, _owner))
-        return true;
+//    if (!_owner->_IsTargetAcceptable(_victim) || !_owner->CanCreatureAttack(_victim))
+//        return true;
+//    if (!FlagsAllowFighting(_owner, _victim) || !FlagsAllowFighting(_victim, _owner))
+//        return true;
     return false;
 }

**Comment by joshwhedon** [comment]
So beyond the immune to npc flag, the issue with the script itself is that each essence has :
void EnterEvadeMode(EvadeReason /*why*/) override
    {
        if (Creature* reliquary = instance->GetCreature(DATA_RELIQUARY_OF_SOULS))
            reliquary->AI()->EnterEvadeMode(EVADE_REASON_OTHER);
    }
For some reason, enterEvadeMode is being called for the essences when they move back to the reliquary.

**Comment by illfated** [comment]
(just copy-pasting the C++ code to show the indents & syntax highlighting using MarkDown code fence with MD backticks + cpp)
```cpp
void EnterEvadeMode(EvadeReason /*why*/) override
{
    if (Creature* reliquary = instance->GetCreature(DATA_RELIQUARY_OF_SOULS))
        reliquary->AI()->EnterEvadeMode(EVADE_REASON_OTHER);
}
```

**Comment by peycho** [comment]
The Boss is actually inactive at the moment. The event can't be start,
The boss can't target ot attacked.

I've noticed that one of the npc parameters have PASSIVE settings.

**Comment by peycho** [comment]
![npc_flags](https://user-images.githubusercontent.com/170853/79067244-a7df0080-7cc6-11ea-9a66-55aa05eef93d.jpg)
![WoWScrnShot_041220_140054](https://user-images.githubusercontent.com/170853/79067250-af9ea500-7cc6-11ea-929e-2098f6e7378e.jpg)

Something is odd here.

**Comment by Keader** [comment]
Fixed kids.
https://github.com/TrinityCore/TrinityCore/commit/d8e726de586070d24bec3c43a9ae795cf5482be0
