### ISSUE TITLE
Add ability to send logs to discord

### ISSUE THREAD

**Issue by ciber96** [TrinityCore/TrinityCore#23871]
As the title says, it would be great to be able to send logs to different services, like for example Discord or Slack to keep server owners posted.

**Comment by Ascathor** [comment]
There's a REST Service that you can use. Using REST and building your own interface for that API, you could easily create a Discord service (for example).

**Comment by Exitare** [comment]
@Ascathor wheres the Rest Service located and what’s the url + port for it ?

**Comment by Ascathor** [comment]
Ah, just noticed that the REST Api is for login (Bnetserver).

**Comment by Exitare** [comment]
@Ascathor ok, so I am not blind. 
I would love to see a rest service implemented into tc.

**Comment by firelook** [comment]
not only send but make excahnge between discord and trinity (lish ash...... ;) )

**Comment by Killyana** [comment]
Reopen the issue here https://github.com/TrinityCore/TrinityCoreCustomChanges/issues
