### ISSUE TITLE
[3.3.5a]Scripts/Spells: Bronjahm's spell Soulstorm should be uninterruptible

### ISSUE THREAD

**Issue by dimasg2** [TrinityCore/TrinityCore#23870]
**Description:**

Dungeon: http://www.wowhead.com/the-forge-of-souls
NPC/Boss: https://www.wowhead.com/npc=36497/bronjahm
Spell: https://www.wowhead.com/spell=68872/soulstorm

When the boss casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.

**Current behaviour:**

When Bronjahm casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.

**Expected behaviour:**

Players should not be able to "ruin" Bronjahm's spell Soulstorm.

**Steps to reproduce the problem:**

1. Enter the instance Forge of Souls with a group (or a single player able to handle it alone)
2. Start the fight with Bronjahm.
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
commit 50307d9222596ca81884a35ac5ad95638978fb3f
version linux core 4.15.0-64-generic
vercion TrinityCore 3.3.5 = 3.3.5a.12340

**Operating system:**

Ubunte Server 18.04 LTS

**Comment by illfated** [comment]
Please forgive me for being slow to understand.
Are you saying that players are able to interrupt the spell [Soulstorm](https://www.wowhead.com/spell=68872/soulstorm) ,
but they should not be able to interrupt the spell?

**Comment by jackpoz** [comment]
@dimasg2 could you edit the issue description by following the issue template ? Thank you

**Comment by illfated** [comment]
@dimasg2 : Start editing your post, then copy the following code block text and paste it into your issue comment (overwrite your existing text)

```
**Description:**

Dungeon: http://www.wowhead.com/the-forge-of-souls
NPC/Boss: https://www.wowhead.com/npc=36497/bronjahm
Spell: https://www.wowhead.com/spell=68872/soulstorm

When the boss casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.

**Current behaviour:**

When Bronjahm casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.

**Expected behaviour:**

Players should not be able to "ruin" Bronjahm's spell Soulstorm.

**Steps to reproduce the problem:**

1. Enter the instance Forge of Souls with a group (or a single player able to handle it alone)
2. Start the fight with Bronjahm.
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

CHANGE_ME / Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:**

CHANGE_ME (OS)
```
Please also replace the "CHANGE_ME" text with information about your system & core, as described in the text.

**Comment by dimasg2** [comment]
I kind of corrected my message

**Comment by jackpoz** [comment]
the git commit hash, like https://github.com/TrinityCore/TrinityCore/commit/50307d9222596ca81884a35ac5ad95638978fb3f

**Comment by dimasg2** [comment]
> @dimasg2 : Start editing your post, then copy the following code block text and paste it into your issue comment (overwrite your existing text)
> 
> ```
> **Description:**
> 
> Dungeon: http://www.wowhead.com/the-forge-of-souls
> NPC/Boss: https://www.wowhead.com/npc=36497/bronjahm
> Spell: https://www.wowhead.com/spell=68872/soulstorm
> 
> When the boss casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.
> 
> **Current behaviour:**
> 
> When Bronjahm casts Soulstorm, players "ruin" Bronjahm's spell Soulstorm.
> 
> **Expected behaviour:**
> 
> Players should not be able to "ruin" Bronjahm's spell Soulstorm.
> 
> **Steps to reproduce the problem:**
> 
> 1. Enter the instance Forge of Souls with a group (or a single player able to handle it alone)
> 2. Start the fight with Bronjahm.
> 3. Step 3
> 
> **Branch(es):**
> 
> 3.3.5
> 
> **TC rev. hash/commit:** 
> 
> CHANGE_ME / Copy the result of server debug command (if you need to run it from client get prat addon)
> 
> **Operating system:**
> 
> CHANGE_ME (OS)
> ```
> 
> Please also replace the "CHANGE_ME" text with information about your system & core, as described in the text.

I`m done all, how can i fix this problem?

**Comment by illfated** [comment]
We will have to wait until someone suggests a way to solve the problem. It would also be nice to know what your fellow players do to ""ruin"" (or do you mean "break"?) or interrupt the spell.
Maybe the coders, those who know the scripts well, need to look at what type of flags are being used and in which ways that spell should be unbreakable.

Could you tell us a little bit more what your friends do to Bronjahm to stop his spell (make a list of the things they can do) so we know more about what you see that should not be possible?

**Comment by dimasg2** [comment]
any interrupt spell can interrupt SoulStorm

**Comment by illfated** [comment]
Very well, fair enough. I think it would be useful to be precise enough in this issue ticket title and write what this is about. Let me suggest the following title:

**Scripts/Spells: Bronjahm's spell Soulstorm should be uninterruptible**

**Comment by Jildor** [comment]
Probably the boss needs mechanic interrupt:

```sql
-- The Forge of Souls: Bronjahm <Godfather of Souls> add MECHANIC_INTERRUPT
UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|33554432 WHERE `entry` IN (36497,36498);
```

**Comment by Aokromes** [comment]
technically that's a hack, because we read interrupt flags from dbc, maybe there is something on dbc data missing to implement.

**Comment by Jildor** [comment]
I'm not sure if can be considered hacky, because we add immunity to interrupt in the boss, we don't modify spell.

**Comment by Aokromes** [comment]
yes, because they must be the individual spells, not the boss. look this: it's really ancient, idk how is the current spell:
https://pastebin.com/79WFnM7x

**Comment by Jildor** [comment]
Oh, I see, so you're saying we need a pell CastImmunities implementation?

**Comment by dimasg2** [comment]
the boss https://www.wowhead.com/npc=36497/bronjahm still has a spell https://www.wowhead.com/spell=68988/teleport with interrupt protection, 
the same property is necessary for https://www.wowhead.com/spell=68872/soulstorm

**Comment by Keader** [comment]
@Jildor you are right.

@Aokromes To appear that "protect shield in cast", creature need interrupt immune. Ariel commited sometime ago, a lot of creature interrupt immune to fix it.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12020#issuecomment-352819352

https://github.com/TrinityCore/TrinityCore/commit/7cc074f2a48db8266645e9c6b3a09ba48b484860

**Comment by dimasg2** [comment]
What value to specify in 'mechanic_immune_mask' in table 'creature_template'? Now value '617299839'

**Comment by illfated** [comment]
@dimasg2 : That would be the **hack** (as Aokromes explained) to increase the `mechanic_immune_mask` of Bronjahm, like Jildor suggested in comment https://github.com/TrinityCore/TrinityCore/issues/23870#issuecomment-544234915 , instead of adding a flag to the spell Soulstorm.
```sql
-- The Forge of Souls: Bronjahm <Godfather of Souls> add MECHANIC_INTERRUPT
UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|33554432 WHERE `entry` IN (36497,36498);
```

**Comment by dimasg2** [comment]
Everything works as it should, enough for me, many thanks

**Comment by Jildor** [comment]
that close issue button is very juicy 😄

**Comment by Jildor** [comment]
Please don't close the issue until the fix is commited in repo
