### ISSUE TITLE
Wintergrasp Tower texture glitching

### ISSUE THREAD

**Issue by szepi23** [TrinityCore/TrinityCore#23888]
**Description:**

I know, that WG is not fully completed, but I guess, it shouldn't glitch like mine does.
All the seven towers have a strange texture glitch.

**Current behavior:**
![WoWScrnShot_102519_075942](https://user-images.githubusercontent.com/36567380/67546898-bd9f4000-f6fd-11e9-91ee-80c0f09b9ba8.jpg)
![WG_glitch](https://user-images.githubusercontent.com/36567380/67546190-01914580-f6fc-11e9-953f-1ae972b1c14b.jpg)

**Expected behavior:**
![WoWScrnShot_102519_071037](https://user-images.githubusercontent.com/36567380/67546204-0b1aad80-f6fc-11e9-9827-b4b8805065d9.jpg)

If I pull my cursor on it, it should look smooth, not glitchy.

**Steps to reproduce the problem:**
Setup a TC 3.3.5 server, build maps, mmaps, vmaps from a 3.3.5 client directory that has wod models. Btw, I also tried with retail models and experienced the same issue.

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

TrinityCore rev. 40116f102595+ 2019-10-23 17:39:25 +0200 (3.3.5 branch) (Win64, Release, Dynamic)
Using SSL version: OpenSSL 1.1.0l  10 Sep 2019 (library: OpenSSL 1.1.0l  10 Sep 2019)
Using Boost version: 1.69.0
Using MySQL version: 5.6.43
Using CMake version: 3.14.0
Compiled on: Windows 10.0.17763
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 657161953 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19101

**Operating system:** Windows 10

**Comment by Shauren** [comment]
For anyone wondering "what the hell is different between these pictures" (and what exactly this report is about) - there are multiple tower spawns overlapping at the same time.

I think this might actually not be a bug - just `.gm off` to stop seeing towers for both factions at the same time

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19241

**Comment by illfated** [comment]
WG towers and bases can shimmer like multiple spawns even in normal mode and for normal player characters.
I thought that was for players to be able to see which parts can be assaulted and demolished.
