### ISSUE TITLE
[3.3.5a]DB/Scripts trial of the champion don`t work

### ISSUE THREAD

**Issue by dimasg2** [TrinityCore/TrinityCore#23881]
Description:

Dungeon: https://ru.wowhead.com/trial-of-the-champion
NPC/Boss: all Bosses and NPC

When the 1st phase begins, the champions come out, followed by empty mounts. Loot does not drop. 2 phase: Loot does not drop. 

3 Phase: 
Boss: https://ru.wowhead.com/npc=35451 doing nothing
 
Expected behaviour:

1 Phase: When the champions come out with them, there must be mobs on the mounts, after the “greeting” the battle on the mounts with a spear should begin. After winning, loot should drop from the box

2 Phase: After winning, loot should drop from the box

3 Phase: When https://ru.wowhead.com/npc=35451 appears the battle should begin and contain 3 phases of the battle.

Steps to reproduce the problem:

Enter the instance Trial of the Champion with a group (or a single player able to handle it alone) and start instance.

Step 3
Branch(es):

3.3.5

TC rev. hash/commit:
commit 50307d9
version linux core 4.15.0-64-generic
vercion TrinityCore 3.3.5 = 3.3.5a.12340

Operating system:

Ubunte Server 18.04 LTS

**Comment by Jinnaii** [comment]
https://github.com/TrinityCore/TrinityCore/issues/383
This Dungeon is broken on trinitycore since ever.

**Comment by dimasg2** [comment]
There are no solutions to this issue?
