### ISSUE TITLE
Drop rate of Frost Lotus inaccurate

### ISSUE THREAD

**Issue by ArgonHC** [TrinityCore/TrinityCore#23880]
**Description:**

The droprates for Frost Lotus when collecting other Herbs are not accurate.

**Current behaviour:**

Currently the droprate is set at 5% chance 1-3 to get Frost Lotus when harvesting a Northrend herb. https://wowwiki.fandom.com/wiki/Frost_Lotus

**Expected behaviour:**

After a hotfix (2010-02-18) from Blizzard, this rate was increased to 7.5%.

**Steps to reproduce the problem:**

Filter the gameobject_loot_table table for the item with ID 36908 (Frost Lotus). 
There you can see the drop rates.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ec81d1c6a9f4 2019-10-20 17:00:28 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Automatic database updates are enabled for the following databases: Auth, Characters, World

**Operating system:**  Debian 9

**Comment by Keader** [comment]
```sql
-- Hotfix (2010-02-18): The drop rate of Frost Lotus, from herbs in Northrend, has been increased by 50%. From 5% to 7.5%
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24093 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24224 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24225 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24226 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24227 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 25089 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 25093 AND `Item` = 36908;
```

**Comment by Killyana** [comment]
@Keader 
I made a change to Icethorn to drop only 1 Frost Lotus (instead 1-2) like other herbs and I changed a weird reference that was used to give an extra Frost Lotus in a Frost Lotus.
``` sql
-- Hotfix (2010-02-18): The drop rate of Frost Lotus, from herbs in Northrend, has been increased by 50%. From 5% to 7.5%
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24093 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24224 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24225 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 24226 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `MaxCount` = 1, `Chance` = 7.5 WHERE `Entry` = 24227 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 25089 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 7.5 WHERE `Entry` = 25093 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Chance` = 100 WHERE `Entry` = 24228 AND `Item` = 36908;
UPDATE `gameobject_loot_template` SET `Item` = 36908, `Reference`=0, `MinCount`=2, `MaxCount`=2 WHERE `Entry` = 24228 AND `chance` = 5;
DELETE FROM `reference_loot_template` WHERE `entry` = 12009;

**Comment by Killyana** [comment]
I tried to fix the drop of Frost Lotus for the herb Frost Lotus (it has 5% chance to drop 2 instead of 1)
But I figure out that the gob could end up empty, it like the 95% and 5% are calculated separately.

-- gameobject_loot_template
Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment
 24228, 1, 12009, 5, 0, 1, 1, 1, 1, \N
 24228, 36908, 0, 95, 0, 1, 1, 1, 1, \N
-- reference_loot_template
Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment
 12009, 36908, 0, 100, 0, 1, 0, 2, 2, \N
