### ISSUE TITLE
Core/BG Some buff in Warsong Gulch dont work.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/TrinityCore#23882]
**Description:**

The buff inside houses dont work at all.

**Current behaviour:**

The buff inside houses dont work at all.

**Expected behaviour:**

You can buff your player with all habilities inside houses.

**Steps to reproduce the problem:**

1. Go to Warsong gulch
2. Try to use any buff inside houses

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ef694cc25184 2019-09-28 15:45:25 +0200 (heads/3.3.5 branch) (Wi
n64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2a 19 Mar 2015 (library: OpenSSL 1.0.2a 19 Mar 20
15)
Using Boost version: 1.65.1
Using MySQL version: 5.6.27
Using CMake version: 3.10.1
Compiled on: Windows 10.0.17763
Automatic database updates are enabled for the following databases: Auth, Charac
ters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/data/maps. Total size: 251987687 bytes
vmaps directory located in E:/data/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/data/mmaps. Total size: 1997886944 bytes
Using esES DBC Locale as default. All available DBC locales: enUS esES
Using World DB: TDB 335.19091

**Operating system:** Windows Server 2012 R2 DataCenter

**Comment by Aokromes** [comment]
TrinityCore rev. ef694cc 2019-09-28 15:45:25 +0200 (heads/3.3.5 branch) (Wi
n64, RelWithDebInfo, Static)

update your core plz.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21615
