### ISSUE TITLE
[3.3.5] Hunter/Spell - Explosive Shot

### ISSUE THREAD

**Issue by WannabeDevTwo** [TrinityCore/TrinityCore#23887]
**Description:**
Explosive Shot doesn't work properly.

**Current behaviour:**

DoT debuff from Explosive Shot is consuming ammo per tick.

**Expected behaviour:**

DoT debuff from Explosive Shot shouldn't consume ammo per tick.

**Steps to reproduce the problem:**

1. Learn Explosive Shot. 
2. Use Explosive Shot against any hostile target.
3. Pay attention, that ammo is consumed after every Explosive Shot tick.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

71c814166103

**Operating system:** Windows 7

**Comment by Mistixsnet** [comment]
Correction Add Script Spell Explosive Shot ID 212679 Hunter Here I leave the implementation of this Spell

______________________________________________________________________________________________
// Explosive Shot - 212679
class spell_hun_explosive_shot_detonate : public SpellScript
{
    PrepareSpellScript(spell_hun_explosive_shot_detonate);

    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        if (AreaTrigger* at = GetCaster()->GetAreaTrigger(SPELL_HUNTER_EXPLOSIVE_SHOT))
        {
            GetCaster()->RemoveAurasDueToSpell(SPELL_HUNTER_EXPLOSIVE_SHOT);
            GetCaster()->CastSpell(at->GetPosition(), SPELL_HUNTER_EXPLOSIVE_SHOT_DAMAGE, true);
            at->Remove();
        }
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_hun_explosive_shot_detonate::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

**Comment by illfated** [comment]
copy of the code above, in MarkDown code block with C++ syntax highlighting:
```cpp
// Explosive Shot - 212679
class spell_hun_explosive_shot_detonate : public SpellScript
{
    PrepareSpellScript(spell_hun_explosive_shot_detonate);

    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        if (AreaTrigger* at = GetCaster()->GetAreaTrigger(SPELL_HUNTER_EXPLOSIVE_SHOT))
        {
            GetCaster()->RemoveAurasDueToSpell(SPELL_HUNTER_EXPLOSIVE_SHOT);
            GetCaster()->CastSpell(at->GetPosition(), SPELL_HUNTER_EXPLOSIVE_SHOT_DAMAGE, true);
            at->Remove();
        }
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_hun_explosive_shot_detonate::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};
```
