### ISSUE TITLE
Core: Creature level1 doesn't deal any damage

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23891]
**Description:** I noticed wolves level 1 at humans starting area don't deal any damage

**Steps to reproduce the problem:**

1. Create a humain or go c id 823 (with level 1 char)
2. attack a level 1 wolf and notice the damage

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 89cb584780aa

**Comment by illfated** [comment]
Oh right. Damage calculation again. Thanks for noticing.

**Comment by Jinnaii** [comment]
Dup? 
#23673

**Comment by illfated** [comment]
Yes, looks like a duplicate ticket, same scenario -- **[3.3.5] Level 1 creatures don't deal damage** (wolves in human starting area).
