### ISSUE TITLE
Crash on Loading DataStores [master]

### ISSUE THREAD

**Issue by dr3adx** [TrinityCore/TrinityCore#23899]
Greetings,

Basically, on Windows, server crashes 50% of times when trying to start server, after db2s "load", while parsing stores. This is on master branch.

`    for (NameGenEntry const* nameGen : sNameGenStore)
        _nameGenData[nameGen->RaceID][nameGen->Sex].push_back(nameGen);
`

^ This is an example taken from crashlog when server crashes, however if i uncomment loading of that specific db2, the crash will happen on another db2 so its like db2 isnt loaded at all or something

However on Linux (Ubuntu 19) you get crashed like 95% of the time, so you're lucky when server does start.

Also its worth noting that servers where I'm testing this have NVME drives, maybe huge read speeds have something to do with this?

Can anyone else test and confirm this issue? But I had this issue both on Windows & Linux machines and on both 8.2 and 8.2.5 trinitycore revisions.

**Comment by dr3adx** [comment]
@Aokromes why label this as incomplete? Just download latest master, try to start server 10 times and I guarantee you'll get at least 2 crashes at "Loading Data Stores", I had other people test it

**Comment by Ovahlord** [comment]
Because you did not follow the ticket template that you just ignored entirely.
