### ISSUE TITLE
Freed Crusader

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#23892]
**Description:**

The creature **Freed Crusader** in **Valley of Echoes (Icecrown), Northrend**. Uses the wrong variable to print a target's name in chat.

**Current behaviour:**

The creature **Freed Crusader** in **Valley of Echoes (Icecrown), Northrend**. Currently uses the wrong variable to print a target's name in chat. It should use $n NOT $c.

**Expected behaviour:**

The creature **Freed Crusader** should use the variable $n when saying a target's name, not $c.

**Steps to reproduce the problem:**

1. Go to Valley of Echoes (Icecrown), Northrend.
2. Slay a Webbed Crusader.
3. You will see the Freed Crusader say:

Wisdom of the ages upon you, noble $c.
-OR-
Glory and strength to you, $c. I bless you with all the strength left in me. May this nightmare end soon!

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 30823f9b79b4 2019-10-13 20:12:36 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 (Standard)

**Comment by Jinnaii** [comment]
If above is valid :

```sql
DELETE FROM `creature_text` WHERE `CreatureID`=30274;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES 
(30274, 0, 0, 'Might grace you, $n. Let the Scourge feel the fury of a million lost souls!', 12, 0, 100, 0, 0, 0, 30976, 0, 'Freed Crusader Speach'),
(30274, 0, 1, 'Glory and strength to you, $n. I bless you with all the strength left in me. May this nightmare soon end!', 12, 0, 100, 0, 0, 0, 30977, 0, 'Freed Crusader Speach'),
(30274, 0, 2, 'Wisdom of the ages upon you, noble $n.', 12, 0, 100, 0, 0, 0, 30978, 0, 'Freed Crusader Speach'),
(30274, 0, 3, 'Thank you and farewell, friend. I must return to the Argent Vanguard.', 12, 0, 100, 0, 0, 0, 30980, 0, 'Freed Crusader Speach');
```

**Comment by Aokromes** [comment]
SELECT * FROM `trinity335`.`broadcast_text` WHERE `MaleText` LIKE '%Let the Scourge feel the fury of a million lost souls%' LIMIT 0,1000
SELECT * FROM `trinity335`.`broadcast_text` WHERE `MaleText` LIKE '%Glory and strength to you%' LIMIT 0,1000
SELECT * FROM `trinity335`.`broadcast_text` WHERE `MaleText` LIKE '%Wisdom of the ages upon you%' LIMIT 0,1000

Nope, blizzlike.

**Comment by illfated** [comment]
I think that change needs to be verified, either by sniff or by retail play / retail video. Web pages like wowhead/wowdb/wowpedia say that the Freed Crusader only has got 1 line of text:
https://github.com/TrinityCore/TrinityCore/blob/30823f9b79b4ad16f96e90692a900f68a7f63c0a/sql/old/3.3.5a/TDB38_to_TDB39_updates/world/2011_02_15_00_world_sai.sql#L50-L67

**Comment by LordWaycrest** [comment]
> SELECT * FROM trinity335.broadcast_text WHERE MaleText LIKE '%Let the Scourge feel the fury of a million lost souls%' LIMIT 0,1000
> SELECT * FROM trinity335.broadcast_text WHERE MaleText LIKE '%Glory and strength to you%' LIMIT 0,1000
> SELECT * FROM trinity335.broadcast_text WHERE MaleText LIKE '%Wisdom of the ages upon you%' LIMIT 0,1000
> Nope, blizzlike.

https://imgur.com/a/cAPgFW2 - That's blizzlike?

**Comment by illfated** [comment]
Oh. You mean https://i.imgur.com/fawOv5u.jpg -- the `$c` is visible instead of actually displaying your player class.
Either we interpreted your issue incorrectly, or you presented it insufficiently for us to get the problem from the beginning.
Please note: it would not help if you replaced $c with $n, because the problem would have remained.

The actual problem here is that **the NPC is not targeting the player before saying its `creature_text` line**.

**Comment by Aokromes** [comment]
to however fixes this bug remember, $c value is correct, not $n.

**Comment by LordWaycrest** [comment]
> Please note: it would not help if you replaced $c with $n, because the problem would have remained.

Steps to reproduce the problem:
Go to Valley of Echoes (Icecrown), Northrend.
Slay a Webbed Crusader.
You will see the Freed Crusader **say**:
Wisdom of the ages upon you, noble $c.
-OR-
Glory and strength to you, $c. I bless you with all the strength left in me. May this nightmare end soon!

I don't know how else I'd put this, but yes that's what I meant.

**Comment by LordWaycrest** [comment]
I don't know how to multi-quote on this...

I did point out that the NPC would **say** the text below, not sure how else I'd put it but yeah.

**Comment by illfated** [comment]
I presume we need to review the SAI and scrutinize the target parameter for the "say text" command (unless the SAI needs any additional lines to handle NPC focus targeting).

**Comment by illfated** [comment]
Oh. I see. I owe you an apology. I took [the comment from](https://github.com/TrinityCore/TrinityCore/issues/23892#issuecomment-546869618) @Jinnaii into account when I said that it would not help to replace $c with $n. Sorry about that misunderstanding.

**Comment by Jinnaii** [comment]
I went with the issue description.
Im not at my computer till Friday therefore i cant try myself, but i would try changing the target_type from 1-self to 7-action_invoker.

```sql
DELETE FROM `smart_scripts` WHERE (`entryorguid`=3027400 AND `source_type`=9);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(3027400, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 11, 58054, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, "Freed Crusader - On Script - Cast 'Blessing of Kings'"),
(3027400, 9, 1, 0, 0, 0, 100, 0, 2000, 2000, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, "Freed Crusader - On Script - Say Line 0"),
(3027400, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 11, 58053, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, "Freed Crusader - On Script - Cast 'Holy Light'"),
(3027400, 9, 3, 0, 0, 0, 100, 0, 4000, 4000, 0, 0, 0, 53, 1, 30274, 0, 13008, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Freed Crusader - On Script - Start Waypoint"),
(3027400, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 41, 4000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Freed Crusader - On Script - Despawn In 4000 ms");
```

**Comment by illfated** [comment]
@Jinnaii : Thank you for contributing. That also matters.
