### ISSUE TITLE
[CRASH] Item::SetBonuses

### ISSUE THREAD

**Issue by dr3adx** [TrinityCore/TrinityCore#23901]
**Description:**

Server crashes when Item::SetBonuses function is called and SetUpdateFieldValue method is run
Tested on Linux machine

**Current behaviour:**

Server crashes when players log in. Based on crashlog item is 168275 and it only has one bonus id = 567

Crash log (RelWithDebInfo): https://pastebin.com/TNQDWQFE
Crash log (RelWithDebInfo) even with -DNOJEM=TRUE https://pastebin.com/r9bsvpyC
Crash log in Debug mode:  https://pastebin.com/0smcZYA8

**Expected behaviour:**

No issues

**Steps to reproduce the problem:**

Based on crashlog its when player logs in and item is loaded from DB, in this case item 168275  and bonus id 567, however I've seen same crashes with different item ids and empty bonus lists

**Branch(es):**

Master

**TC rev. hash/commit:**

7c168fb

**Comment by illfated** [comment]
item link:
- https://www.wowhead.com/item=168275/anu-azshara-staff-of-the-eternal&bonus=4798:1487

**Comment by dr3adx** [comment]
> item link:
> 
> * https://www.wowhead.com/item=168275/anu-azshara-staff-of-the-eternal&bonus=4798:1487

thanks, although it happens with other items as well, so I dont think this is item-specific but I rather think theres problem with SetUpdateFieldValue and/or its child functions

**Comment by illfated** [comment]
Fair enough. I simply thought it could be useful somehow, in case the TC bonus info is incorrect for the item.

**Comment by Daribon** [comment]
Can confirm, have this happening with a different item.

**Comment by Shauren** [comment]
What is the compiler (and version) used here?

**Comment by jackpoz** [comment]
> Can confirm, have this happening with a different item.

Whenever confirming a crash, you should report the crashlog, the commit hash, the platform, just like if it was a new issue report. Otherwise it will not help much solving the issue.

@dr3adx try building passing cmake argument -DNOJEM=TRUE

**Comment by dr3adx** [comment]
> What is the compiler (and version) used here?

Gcc 9.1.3, clang 9

@jackpoz gonna test with that and let u know

**Comment by dr3adx** [comment]
@jackpoz  @Shauren  still crashing even with -DNOJEM=TRUE

**Comment by jackpoz** [comment]
Post the crashlog then

**Comment by dr3adx** [comment]
@jackpoz https://pastebin.com/r9bsvpyC, edited main post as well

**Comment by Artamedes** [comment]
you should get a valgrind log, will probably give you more useful info

**Comment by Shauren** [comment]
Did you build with -DCMAKE_BUILD_TYPE=Debug or RelWithDebInfo?

**Comment by dr3adx** [comment]
> Did you build with -DCMAKE_BUILD_TYPE=Debug or RelWithDebInfo?
> 
> I cannot reproduce it with clang 6.0.0 with libstdc++ from gcc 7.4.0

RelWithDebInfo, do you want me to try Debug?

**Comment by Shauren** [comment]
Would be great if you could do that while I try to reproduce this with upgraded compilers

**Comment by Shauren** [comment]
@Artamedes valgrind was clear with my build

**Comment by dr3adx** [comment]
@Shauren @jackpoz got new crashlog in Debug mode https://pastebin.com/0smcZYA8
There's new keyword that appears that didn't before in RelWithDebInfo and that is Unit::GetModelForForm

**Comment by Aokromes** [comment]
This bug is still valid?

**Comment by Aokromes** [comment]
no answer, closing.
