### ISSUE TITLE
[3.3.5] Priest/Spell - Vampiric Touch

### ISSUE THREAD

**Issue by Xardasonex** [TrinityCore/TrinityCore#23902]
Description:
When dispel deals too much damage

Current behaviour:
Vampiric Touch does too much damage if removed with a dispel

Expected behaviour:
Should inflict, according to my conservative estimates, 4 times less damage on the display

Steps to reproduce the problem:
1.Learn in the talent branch Vampiric Touch
2.Use this spell on opponents
3.Remove this spell dispell

Branch(es):
3.3.5

TC rev. hash/commit:
4bf80e2

Operating system: Windows 10

**Comment by Warpten** [comment]
#21556
#21393
