### ISSUE TITLE
[EMERGENT] Crash on Loading Data Stores

### ISSUE THREAD

**Issue by dr3adx** [TrinityCore/TrinityCore#23900]
**Description:**

Basically, on both Windows and Linux server crashes 20-50% of times for  Windows and 95% of times for Linux when trying to start server, on "Loading Data Stores". Tested and confirmed by couple of people, not just me.

**Current behaviour:**

https://cdn.discordapp.com/attachments/343443659980800000/640588301916700702/t6fy6mwelu.png

**Expected behaviour:**

No issue

**Steps to reproduce the problem:**

> Compile latest master branch
> Start worldserver 10-20 times and close it after successful "Loading data stores"
> Count how many crashes you got on Loading data stores
**Note that server won't crash 100% of the time, so you have to open/close it enough times, from my testing this happens 95% of the time on Linux, while on Windows crash ratio is like 20-50% **

**Branch(es):**

master

**TC rev. hash/commit:**

9ea577d

**Comment by Daribon** [comment]
Same thing happening, crashes about half of the time when loading data stores.

**Comment by Shauren** [comment]
Already identified an issue in DB2 loader, testing fix
