### ISSUE TITLE
DB/Quest: Full Triangle

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23913]
**Description:** Missing aggro texts for Culuthas and Image of Socrethar

https://www.wowhead.com/quest=10276/full-triangle
https://www.wowhead.com/npc=20133/image-of-socrethar#comments
https://www.wowhead.com/npc=20138/culuthas

**Branch(es):** Both

**TC rev. hash/commit:** rev. c79571a09678

**Comment by offl** [comment]
(Almost) Duplicate of #23814 :)

**Comment by Killyana** [comment]
yes

**Comment by Rushor** [comment]
it's also missing the end event after quest turned in
