### ISSUE TITLE
DB/Quest: Weakness to Lightning

### ISSUE THREAD

**Issue by citizenwow** [TrinityCore/TrinityCore#23916]
Description:

In quest https://www.wowhead.com/quest=11896/ when you kill https://www.wowhead.com/npc=25752/ after application https://www.wowhead.com/item=35352/
Killing does not count towards the progress of the quest.

Branch(es): 3.3.5

TC rev. hash/commit:

TrinityCore rev. c79571a 2019-11-03 17:00:24 +0100

Operating system: CentOS 7

**Comment by illfated** [comment]
(just adding minor extra information, for those who prefer to see it here)
- https://www.wowhead.com/quest=11896/weakness-to-lightning
- https://www.wowhead.com/npc=25752/scavenge-bot-004-a8
- https://www.wowhead.com/item=35352/sages-lightning-rod

**Comment by dr-j** [comment]
Just copy sai related to this quest (not abilities) from one of the other robot npcs which it works on just the lines which deal with spell hit and credit and any associated sai condition

**Comment by dr-j** [comment]
That npc was scripted here https://github.com/TrinityCore/TrinityCore/commit/d8b41bff6915a9457b531020a7ee260d23500790

**Comment by dr-j** [comment]
And the commit which overwrit sai https://github.com/TrinityCore/TrinityCore/commit/e25336ae2c28dafa310e300365522e810273ac84

**Comment by dr-j** [comment]
Just needs sai lines with Id 1 & 2 re-adding from that first commit for this npc

**Comment by dr-j** [comment]
Sorry disregard this I’m on phone atm and did not see properly

**Comment by Killyana** [comment]
The issue is with this 2 spells:
https://woehead.way-of-elendil.fr/?spell=46444
https://woehead.way-of-elendil.fr/?spell=46445

**Comment by dr-j** [comment]
Well quest still works on the other npcs which was scripted in that first commit it’s just this one

**Comment by Killyana** [comment]
It uses a different spell: https://woehead.way-of-elendil.fr/?spell=46443 "Weakness to Lightning: Kill Credit Direct to Player"

https://woehead.way-of-elendil.fr/?spell=46445 "Weakness to Lightning: Kill Credit from Pet" is the one that works

But both must be fix to get the credit if the kill is done by a pet

**Comment by illfated** [comment]
Just out of curiosity, at first I thought the required spell script would belong in `src/server/scripts/Spells/spell_pet.cpp`, but while browsing that content, I'm guessing that my first notion is not correct.

Maybe it belongs in `src/server/scripts/Spells/spell_quest.cpp` instead?

**Comment by Killyana** [comment]
I made this, if the kill is done by a player he will get the credit, the issue is with the pet, the spell 46444  works fine if it's cast during the combat by the mob in the pet, but if it's cast on death it does no thing, I'm not sure if the spell is not cast or something else fails.
``` cpp
class spell_q11896_weakness_to_lightning_46444 : public SpellScript
{
    PrepareSpellScript(spell_q11896_weakness_to_lightning_46444);

    void HandleScript(SpellEffIndex /*effIndex*/)
    {
        if (Unit* target = GetHitUnit())
        {
            if (Unit* owner = target->GetOwner())
            {
                target->CastSpell(owner, GetEffectValue(), true);
            }
        }
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_q11896_weakness_to_lightning_46444::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};
```
``` sql
DELETE FROM `spell_script_names` WHERE `spell_id`=46444 AND `ScriptName`='spell_q11896_weakness_to_lightning_46444';
INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (46444,'spell_q11896_weakness_to_lightning_46444');
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (25752,25753,25758) AND `source_type`=0 AND `id`IN (5);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (25792) AND `source_type`=0 AND `id`IN (3);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(25752, 0, 5, 0, 6, 1, 100, 0, 0, 0, 0, 0, 0, 11, 46443, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, "Scavenge-bot 004-A8 - On Just Died - Cast 'Weakness to Lightning: Kill Credit Direct to Player' (Phase 1)"),
(25753, 0, 5, 0, 6, 1, 100, 0, 0, 0, 0, 0, 0, 11, 46444, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, "Sentry-bot 57-K - On Just Died - Cast 'Weakness to Lightning: Kill Credit from Pet' (Phase 1)"),
(25758, 0, 5, 0, 6, 1, 100, 0, 0, 0, 0, 0, 0, 11, 46444, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, "Defendo-tank 66D - On Just Died - Cast 'Weakness to Lightning: Kill Credit from Pet' (Phase 1)"),
(25792, 0, 3, 0, 6, 1, 100, 0, 0, 0, 0, 0, 0, 11, 46444, 2, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, "Scavenge-bot 005-B6 - On Just Died - Cast 'Weakness to Lightning: Kill Credit from Pet' (Phase 1)");
UPDATE `smart_scripts` SET `action_param1`=46444, `action_param2`=2 WHERE `entryorguid` IN (25752) AND `id`=2;
UPDATE `smart_scripts` SET `action_param2`=2 WHERE `entryorguid` IN (25752,25753,25758,25792) AND `action_param1` IN (46443,46444);
