### ISSUE TITLE
[3.3.5] - DK: Blood Presence heal proc

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#23910]
**Description:**
Blood Presence Heal proc: 63611
have PROC_ATTR_REQ_EXP_OR_HONOR introduced here:
https://github.com/TrinityCore/TrinityCore/commit//2ff855054f52bf2dcf81aa7a7da7bab7f8a99686#diff-6fe567656a9b9479d234c23228b89f63R1012

This seems wrong, here we can see how a DK in Training Dummy get the heal proc of blood presence:
https://www.youtube.com/watch?v=ea3oVeFPWRA

If we try in TC, we can't get the proc because NPC have FLAG_EXTRA_NO_XP_AT_KIL

**Fix:**
```sql
UPDATE `spell_proc` SET `AttributesMask`=`AttributesMask`&~0x1 WHERE `SpellId`=63611;
```
**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/9597195e82dc030bfadb001ddfc832041924a13b

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/23860
FLAG_EXTRA_NO_XP_AT_KIL mustn't disable PROC_ATTR_REQ_EXP_OR_HONOR

**Comment by Jildor** [comment]
Nope, this proc shouldn't have PROC_ATTR_REQ_EXP_OR_HONOR, it makes no sense

**Comment by Keader** [comment]
@Killyana fix is correct, is not exactly same issue.
Flag should not be there (for blood presence) anyway.
Maybe a ariel typo.
Can you commit it?

**Comment by Killyana** [comment]
But: it's in the description of the spell:

Improved Blood PresenceInstant
Strengthens the Death Knight with the presence of blood, increasing damage by 15% and healing the Death Knight by 0% of damage dealt. Only damage dealt to targets that grant experience or honor can trigger this heal. Only one Presence may be active at a time.

**Comment by Keader** [comment]
Oh fuck, looked into wrong spellid O.o
yes, is same issue '-'
Needs a generic solution.

**Comment by Jildor** [comment]
lul you're right I didn't see this xDD
