### ISSUE TITLE
Scripts/Naxxramas: Heigan the Unclean

### ISSUE THREAD

**Issue by citizenwow** [TrinityCore/TrinityCore#23919]
Description:
The eruption, which the boss causes every few seconds due to cracks in the floor, does no damage.

Current behaviour:
When Heigan the Unclean uses his Eruption spell, he does no damage.

Expected behaviour:
When Heigan the Unclean uses his Eruption spell, he must deal damage.

Steps to reproduce the problem:
Start fighting Heigan the Unclean and wait when he cast his spell "Eruption"

Branch(es): 3.3.5

TC rev. hash/commit:
TrinityCore rev. c79571a 2019-11-03 17:00:24

TDB version: TDB 335.19101

**Comment by Killyana** [comment]
Same as https://github.com/TrinityCore/TrinityCore/issues/21615

**Comment by gonzo1247** [comment]
The Problem still exist, testet with TrinityCore rev. 7258d00f932cfde051fecdb14f207f0a2fe5e79a 2020-03-20 00:15:13

**Comment by illfated** [comment]
@gonzo1247 : Out of curiosity, do you find any of the other issues described in ticket #21615 to be present as well, like the Green buff in WSG?

**Comment by gonzo1247** [comment]
Yea i tested it now, the Green Buff in WSG does not work. its the same problem are described in https://github.com/TrinityCore/TrinityCore/issues/21615

**Comment by jackpoz** [comment]
could anyone check if the WSG buff works at https://tcubuntu.northeurope.cloudapp.azure.com ? confirm this issue too ?

**Comment by illfated** [comment]
All buffs in WSG seem to work as expected, but I have only tested using my namesake account (gmlevel 3) with GM off, playing alone.
The in-game visuals (icons, player char. spell effects) and HP+mana increase works as expected.

**Comment by Jildor** [comment]
Wsg buff works, I can confirm Heigan eruption issue, maybe caused by: https://github.com/TrinityCore/TrinityCore/commit/45c5e1b9d63796d168339a44f63418f220cf2403

and probably related with: #24224 (Although not related to stealth, but gobs casts maybe old script can't works fine with gobs casts)

**Comment by Killyana** [comment]
Same issue for Onyxia https://github.com/TrinityCore/TrinityCore/issues/22824 The Eruption of lava from cracks in the floor does no damage

**Comment by Jildor** [comment]
yep, two scripts seems the same:
Heigan: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_heigan.cpp#L194-L198

Onyxia:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp#L109-L114

**Comment by illfated** [comment]
Thank you for checking those details. I found it too difficult to verify Heigan on my own with only 1 character, because the spells cast from him 2-shot me all the time, even if I did `.modify hp 650000000` as frequent as I could. Some of his spells reset my HP to either unbuffed HP or 50% of unbuffed (default level 80 character HP). Never mind. Glad you found something worth checking out in the source.

**Comment by jackpoz** [comment]
@illfated do you have ".cheat god" ? that makes you take no damage

**Comment by illfated** [comment]
Ah, fair point. Thank you for reminding me. I guess I haven't used that command since 2018, IIRC.

**Comment by Faq** [comment]
@Jildor https://github.com/TrinityCore/TrinityCore/issues/24224#issuecomment-605617828 fixes this?

**Comment by Jildor** [comment]
Nope, seems two scripts need a proper way to cast the spell better

**Comment by Faq** [comment]
guess, this should be closed?
