### ISSUE TITLE
SQL problem

### ISSUE THREAD

**Issue by HerharFares** [TrinityCore/TrinityCore#23927]
I followed this tutorial of the trinity core community
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements
--------
--------
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/$USER/server -DTOOLS=0 -DWITH_WARNINGS=1

[  1%] Built target Recast
[  2%] Built target fmt
[  2%] Built target Detour
[  6%] Built target g3dlib
[  6%] Built target sfmt
[  7%] Built target argon2
[  7%] Built target gsoap
[ 10%] Built target jemalloc
[ 10%] Built target revision_data.h
[ 14%] Built target common
[ 14%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/QueryCallback.cpp.o
[ 14%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/QueryCallbackProcessor.cpp.o
[ 14%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/DatabaseWorkerPool.cpp.o
[ 14%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/MySQLThreading.cpp.o
/home/osaca/TrinityCore/src/server/database/Database/MySQLThreading.cpp:33:12: fatal error: use of undeclared identifier 'MYSQL_SERVER_VERSION'; did
      you mean 'MYSQL_OPT_TLS_VERSION'?
    return MYSQL_SERVER_VERSION;
           ^~~~~~~~~~~~~~~~~~~~
           MYSQL_OPT_TLS_VERSION
/usr/include/mariadb/mysql.h:207:5: note: 'MYSQL_OPT_TLS_VERSION' declared here
    MYSQL_OPT_TLS_VERSION,
    ^
1 error generated.
src/server/database/CMakeFiles/database.dir/build.make:277: recipe for target 'src/server/database/CMakeFiles/database.dir/Database/MySQLThreading.cpp.o' failed
make[2]: *** [src/server/database/CMakeFiles/database.dir/Database/MySQLThreading.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/osaca/TrinityCore/src/server/database/Database/DatabaseWorkerPool.cpp:58:34: fatal error: use of undeclared identifier 'MYSQL_SERVER_VERSION';
      did you mean 'MYSQL_OPT_TLS_VERSION'?
        mysql_get_client_info(), MYSQL_SERVER_VERSION);
                                 ^~~~~~~~~~~~~~~~~~~~
                                 MYSQL_OPT_TLS_VERSION
/home/osaca/TrinityCore/src/common/Debugging/Errors.h:58:110: note: expanded from macro 'WPFatal'
#define WPFatal(cond, ...) ASSERT_BEGIN do { if (!(cond)) Trinity::Fatal(__FILE__, __LINE__, __FUNCTION__, ##__VA_ARGS__); } while(0) ASSERT_END
                                                                                                             ^
/usr/include/mariadb/mysql.h:207:5: note: 'MYSQL_OPT_TLS_VERSION' declared here
    MYSQL_OPT_TLS_VERSION,
    ^
1 error generated.
src/server/database/CMakeFiles/database.dir/build.make:177: recipe for target 'src/server/database/CMakeFiles/database.dir/Database/DatabaseWorkerPool.cpp.o' failed
make[2]: *** [src/server/database/CMakeFiles/database.dir/Database/DatabaseWorkerPool.cpp.o] Error 1
CMakeFiles/Makefile2:1141: recipe for target 'src/server/database/CMakeFiles/database.dir/all' failed
make[1]: *** [src/server/database/CMakeFiles/database.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by illfated** [comment]
So... which flavor of Linux are you using?
Which version of MySQL did you install?

**Comment by jackpoz** [comment]
Creating a new issue displays a template that should not be ignored. You can see again the template at https://github.com/TrinityCore/TrinityCore/issues/new .

Please edit the issue description following the template
