### ISSUE TITLE
Ulduar: Stuck in combat after Kologarn encounter

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23938]
**Description:** During Kologarn encounter if you kill an arm you will enter combat with NPC_RUBBLE_STALKER                  = 33809,
And once the boss is killed your character will remain in combat with this npc trigger:
Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Rubble Stalker Kologarn (SpawnID 136056)

**Steps to reproduce the problem:**
1. go c 136762
2. kill an arm
3. kill the boss

I tried to put :
ForceCombatStopForCreatureEntry(NPC_RUBBLE_STALKER, 500.f);
after : 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp#L154

But it doesn't work.

**Branch(es):**3.3.5
**TC rev. hash/commit:** rev. 909941e1b442

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by ccrs** [comment]
check its phase, if its not in the same as the boss, use
```c++
ForceCombatStopForCreatureEntry(NPC_RUBBLE_STALKER, 500.f, false);
```

**Comment by ccrs** [comment]
or you can now use
```diff
- ForceCombatStopForCreatureEntry(NPC_ARM_SWEEP_STALKER, 500.f);
+ ForceCombatStopForCreatureEntry({ NPC_ARM_SWEEP_STALKER, NPC_RUBBLE_STALKER }, 500.f, false);
```

**Comment by Killyana** [comment]
Both the Boss and npc trigger are in phase1, also tested:
ForceCombatStopForCreatureEntry(NPC_RUBBLE_STALKER, 500.f, false);
and it doesn't stop the combat

**Comment by illfated** [comment]
Just a wild guess, but would it make any difference if you replace the function `ForceCombatStopForCreatureEntry()` with some kind of kill command instead?
Otherwise, I would have checked to see if that command gets triggered at all.

**Comment by Killyana** [comment]
Yes if I put:
``` cpp
if (Creature* RUBBLE = me->FindNearestCreature(NPC_RUBBLE_STALKER, 100.0f))
    RUBBLE->DespawnOrUnsummon();
```
Inside void JustDied() it despawns the npcs

**Comment by illfated** [comment]
OK, thanks for the feedback. I can only imagine that something re-adds aggro or threat of some sort to the `NPC_RUBBLE_STALKER`, but I don't know what that should be, so it is possibly an incorrect assumption. Otherwise, I am wondering if the command `ForceCombatStopForCreatureEntry()` does not work in that part of the script or gets disabled or is ineffective because of something I haven't noticed yet.

**Comment by offl** [comment]
Maybe interrupt their spells or remove auras(if any)?

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp#L246

```c++
void ScriptedAI::ForceCombatStop(Creature* who, bool reset /*= true*/)
{
    if (!who || !who->IsInCombat())
        return;

    who->CombatStop(true);
    who->DoNotReacquireSpellFocusTarget();
    who->GetMotionMaster()->Clear(MOTION_PRIORITY_NORMAL);

    if (reset) {
        who->LoadCreaturesAddon();
        who->SetLootRecipient(nullptr);
        who->ResetPlayerDamageReq();
        who->SetLastDamagedTime(0);
        who->SetCannotReachTarget(false);
    }
}
```

**Comment by ccrs** [comment]
Ah, that does not remove auras, I wonder why did I leave em out when I did that...

**Comment by Killyana** [comment]
The npc use any aura before/during/after the combat

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp#L542
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp#L196
Maybe related then

**Comment by Killyana** [comment]
I thought about that and set 2 lines, one for each

**Comment by ccrs** [comment]
yeah, its most likely an aura. The question is, do I include auras in that "reset cleanup"... 🤔

**Comment by Killyana** [comment]
Why not just triggering an evade, it will remove the auras and set auras from CreaturesAddon and reset events?

**Comment by illfated** [comment]
Sounds plausible, if evade still works as intended & expected.

**Comment by Killyana** [comment]
After many tests, the npc enter combat when a player is near with the aura https://woehead.way-of-elendil.fr/?spell=62030 at the moment when the boss dies, the ForceCombatStopForCreatureEntry is executed but an other start combat is called after that.

**Comment by WoWPortal** [comment]
rubbleStalker->CastSpell(rubbleStalker, SPELL_STONE_GRIP_CANCEL, true);

Is where you should add forcecombat

**Comment by jackpoz** [comment]
I tested
```c++
ForceCombatStopForCreatureEntry({ NPC_ARM_SWEEP_STALKER, NPC_RUBBLE_STALKER }, 500.f);
```
and killed an arm and I wasn't in combat anymore at the end. @Killyana could you test that again ?

**Comment by jackpoz** [comment]
please test it again on https://github.com/TrinityCore/TrinityCore/commit/ee34a1f19ea6062ffe8612a735eede990dd2840e (or newer version) and use .debug combat and .debug threat if still in combat at the end of the fight

**Comment by jackpoz** [comment]
if that didn't work, try applying the new flag added in https://github.com/TrinityCore/TrinityCore/commit/6440c3bcac85a40de5c34aef1d8a8856966cc140 to the triggers that shouldn't enter combat

**Comment by offl** [comment]
```sql
-- Add CREATURE_FLAG_EXTRA_NO_COMBAT to Kologarn's stalkers
UPDATE `creature_template` SET `flags_extra` = `flags_extra` | 0x00002000 WHERE `entry` IN (33661,33809,33942);
```

Yes, they both should not be in combat according to creature_difficulty. Didn't tested how it changes the encounter.

**Comment by jackpoz** [comment]
could someone apply the sql above and test the fight ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6ad6d9e67069ef048c10afbdd52627b8c765a010
