### ISSUE TITLE
DB/Update: Change of the "Silithus" map to "Silithus: The Wound" upon reaching level 110.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#23939]
Description:
When the player reaches level 110 and is ready to go to Silithus, the old map "Silithus" appears, when the map "Silithus: The Wound" should appear.

Steps to reproduce the problem:

1. Create a level 110 character.
2. Teleport to Silithus.

Branch(es): master

Operating system: Windows 10 Pro.

```sql
DELETE FROM `terrain_swap_defaults` WHERE `TerrainSwapMap` = 1817;
INSERT INTO `terrain_swap_defaults` (`MapId`, `TerrainSwapMap`, `Comment`) VALUES 
(1, 1817, 'Silithus: The Wound');

DELETE FROM `terrain_worldmap` WHERE `TerrainSwapMap` = 1817;
INSERT INTO `terrain_worldmap` (`TerrainSwapMap`, `UiMapPhaseId`, `Comment`) VALUES 
(1817, 9491, 'Silithus: The Wound');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 25 AND `SourceEntry` = 1817;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(25, 0, 1817, 0, 0, 27, 0, 110, 3, 0, 0, 0, 0, '', 'TerrainSwap 1817 only when player has level 110');
```

**Comment by Ovahlord** [comment]
This is actually incorrect. The terrainswap shows up once you complete the first BfA quest OR defeat Argus in Antorus, not just by plain leveling.

**Comment by ArcaneFox** [comment]
Maybe it's changed. At level 110, I just get the "Hour of Reckoning" quest when my character leveled to 110 and Silithus is already phased to Silithus: The Wound.

(off.: The resting place of King Varian Wrynn in Lion's Rest is also spawned. You can check it with a level 20 character.)

**Comment by osleyder85** [comment]
Ok, I will make the suggested adjustments.

**Comment by osleyder85** [comment]
One question, the map change is done automatically when the objectives mentioned above are met, or must be programmed for when any of those objectives is met.

**Comment by illfated** [comment]
Isn't that documented somewhere, like wowhead / wowwiki / wowpedia?

**Comment by osleyder85** [comment]
I think they should be updated a bit. Years ago that is not the case:

Comprehensive Silithus Wound in the world guide: (https://www.wowhead.com/comprehensive-silithus-wound-in-the-world-guide) 

Accessing Updated Silithus

As of June 26, 2018, everyone has access to The Wound in the World. You no longer need to kill Argus the Unmaker to access the changed zone.

Should you wish to access the pre-Wound version of Silithus, speak to Zidormi in the northeastern corner of SIlithus by Valor's Rest.

**Comment by welder1976** [comment]
this is fix ashamane

**Comment by MaxtorCoder** [comment]
So? Does not mean he isn't allowed to send a possible fix.

**Comment by ReyDonovan** [comment]
@Ovahlord he is right! it is visible sniff! even if the purchase was an account at level 110
