### ISSUE TITLE
[Crash]  mail

### ISSUE THREAD

**Issue by u0yiji1** [TrinityCore/TrinityCore#23935]
**Description:**

crash

**Current behaviour:**

crash

**Steps to reproduce the problem:**

1. send a item mail
2. Step 2
3. Step 3

**Branch(es):**

master

**TC rev. hash/commit:** 

edc440c10913

**Operating system:** Windows Server 2008 R2 Datacenter Service Pack 1

[edc440c10913_worldserver.exe_[24-11_0-34-35].txt](https://github.com/TrinityCore/TrinityCore/files/3882686/edc440c10913_worldserver.exe_.24-11_0-34-35.txt)

**Comment by MaxtorCoder** [comment]
???

**Comment by Kitzunu** [comment]
Shauren closed it here https://github.com/TrinityCore/TrinityCore/commit/edc440c10913a62b325879d76617ad25571be6a1

So this is a dup of a fixed issue

**Comment by Shauren** [comment]
Different crash log
