### ISSUE TITLE
Paladin dind't make Aggro

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#23933]
**Description:**

Paladin dont make any Threat with here Spells or Autoattack. Every other Player can steal the aggro with simple attacks. 

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1: Create a Paladin, skill him to a Tank
2: go to a creature and Tank it
3: other Charakter cast on the Creature and steal aggro 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

94f186ee8342824da57eb0fb24378dacc67cbd64

**Operating system:** Ubuntu 16.04.6

**Comment by mdX7** [comment]
You gotta buff urself Righteous Fury to generate threat as a paladin. If you dont have that spell go to a trainer. This is a mechanic only existing for paladins.

**Comment by gonzo1247** [comment]
My Paladin has https://classic.wowhead.com/spell=25780/righteous-fury buffed.
also with this buff he dont make right aggro

**Comment by illfated** [comment]
> Paladin dont make any Thread [ ... ]

... not unless he has learned the Tailoring skill. :trollface: 🤣

**Comment by gonzo1247** [comment]
> 
> 
> > Paladin dont make any Thread [ ... ]
> 
> ... not unless he has learned the Tailoring skill. :trollface: 🤣

yea i fixed the wrong letter^^

**Comment by WoWPortal** [comment]
Paladin threat works fine are using
shield of the righteous?
