### ISSUE TITLE
InGame Error at the starting position of a new character

### ISSUE THREAD

**Issue by hellfireworld** [TrinityCore/TrinityCore#23943]
I don't know if its happening only in my server build. Once it led to server crash!

**Description:**

Creating a new character leads to the starting location suddenly a loading bar pops up on the screen and after the character gets teleported somewhere out of map (llike its using teleport command).

**Current behaviour:**

Every time I go to create new character it spawns at the starting location but in the next second its doing some code check and it teleports somewhere out of map in the air while u can't do anything if you are not gm.

**Expected behaviour:** 
Create a new character, spawn at the starting position and stay still without teleport.                                                                               

**Reproduce the problem:**
Create a new character and login.                                                                                                                   

**What I did try**
1. Thought if I changed the location in database world->playercreateinfo the problem would change but nothing changed.  
2. So it might be some ground check at start or dbc maps error?

**Branch(es):**

master

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Windows 10

![worldserver_print_code](https://user-images.githubusercontent.com/6421484/69756563-76282b80-1163-11ea-857f-20d019dee9f3.jpg)

after the game crash

![print_error_game_crash](https://user-images.githubusercontent.com/6421484/69756920-475e8500-1164-11ea-91bd-c789b3580ff4.jpg)

[cf0e2336895e_worldserver.exe_[27-11_22-18-55].txt](https://github.com/TrinityCore/TrinityCore/files/3898660/cf0e2336895e_worldserver.exe_.27-11_22-18-55.txt)

**Comment by hellfireworld** [comment]
I found out that is happening only the first time i login with a new character, when I exit or alt+f4 and relog the character is spawned at the right location.  When this is happening, I tried to use the command .gm on so I could teleport and a spirit waypoint appeared , I couldn't see my character's model, when I relog everything is ok.

**Comment by buddyqc69** [comment]
i have the same error, do you have fix for this ?

**Comment by illfated** [comment]
(Header info from the crash log text file in the ticket opening comment: )

Revision: TrinityCore rev. cf0e2336895e 2019-11-26 +0100 (master branch) (Win64, Debug, Static)
Date 27:11:2019. Time 22:18

**Comment by buddyqc69** [comment]
re updated the dbc dans data of the server and have no issue

**Comment by illfated** [comment]
@hellfireworld : Have you tried checking if your dbc content might be causing this issue? (ref. previous comment)

**Comment by buddyqc69** [comment]
I have extracted again my dbc and that resolve crash and another bug

Le 16 déc. 2019 6:27 p.m., "Trond B. Krokli" <notifications@github.com> a écrit :

@hellfireworld<https://github.com/hellfireworld> : Have you tried checking if your dbc content might be causing this issue? (ref. previous comment)

**Comment by hellfireworld** [comment]
I had checked that yes ! I was extracting dbc maps mmaps etc.. all the time when wow had an update ! but still no difference I will try it again.

**Comment by roflnap** [comment]
hi,

I'd like to add some info:
i get the following error when creating a new char and entering the world:
Player::CreateViewpoint: Player 'Testmann' (GUID Full: 0x08000400000000000000000000000005 Type: Player Entry: 0 Low: 5) cannot add new viewpoint!

after intro is finished or canceled, camera view seems to be stucked (in stormwind when created a human character), relogging works, but when loggin out, the following line appears in console:
Player::RemoveFromWorld: Player 'Testmann' (GUID Full: 0x08000400000000000000000000000005 Type: Player Entry: 0 Low: 5) has viewpoint (Entry:1, Type: 5) when removed from world.

any advice?
