### ISSUE TITLE
Creating characters or loading characters leads to worldserver error bug!

### ISSUE THREAD

**Issue by hellfireworld** [TrinityCore/TrinityCore#23940]
I know that they are updating with patches too often in official but I can't even create or load a character in master branch it leads to a fatal worldserver error and some time ago in another patch  I could login but when I was using teleport command leaded in worldserver fatal error always. Are the location coordinates wrong in database ? or its still becauses its not supported :P ?

**Comment by Jinnaix** [comment]
Is it intended that you completely drop the issue template, dont provide a revision and speak of crashes without providing logs?

**Comment by hellfireworld** [comment]
I haven't posted anything quite in a while, I was here before lich king branch in mangos so I needed an answer first, you might knew the error already, do you still want the logs?

**Comment by hellfireworld** [comment]
`Revision: TrinityCore rev. 3d9e21193dd9 2019-11-25 21:42:00 +0100 (master branch) (Win32, Debug, Static)

//=====================================================
Exception code: E06D7363 
Fault address:  767D35D2 01:001125D2 C:\WINDOWS\System32\KERNELBASE.dll

Registers:
EAX:035916A0
EBX:037BE000
ECX:00000003
EDX:00000000
ESI:7B1115D8
EDI:03591738
CS:EIP:0023:767D35D2
SS:ESP:002B:035916A0  EBP:035916F8
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000216

Call stack:
Address   Frame     Function      SourceFile
767D35D2  00000000  RaiseException+62
7B119C39  00000000  _CxxThrowException+A9
025D60DC  00000000  0001:023750DC D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D3540  00000000  0001:02372540 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D54EC  00000000  0001:023744EC D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
0236749F  00000000  0001:0210649F D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
02304E91  00000000  0001:020A3E91 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
02304B08  00000000  0001:020A3B08 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
014766A5  00000000  0001:012156A5 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
014765AE  00000000  0001:012155AE D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01478AAB  00000000  0001:01217AAB D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
0147876D  00000000  0001:0121776D D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
014B38E0  00000000  0001:012528E0 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
0147784C  00000000  0001:0121684C D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
0146FF81  00000000  0001:0120EF81 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
0147045D  00000000  0001:0120F45D D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01470544  00000000  0001:0120F544 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00C42D48  00000000  0001:009E1D48 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
017A8750  00000000  0001:01547750 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
017A508A  00000000  0001:0154408A D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00C79458  00000000  0001:00A18458 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00C798E1  00000000  0001:00A188E1 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00C79766  00000000  0001:00A18766 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00C79527  00000000  0001:00A18527 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D529D5  00000000  0001:00AF19D5 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D533A4  00000000  0001:00AF23A4 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D557D8  00000000  0001:00AF47D8 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D57FEF  00000000  0001:00AF6FEF D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D56337  00000000  0001:00AF5337 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00D11104  00000000  0001:00AB0104 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7A5E8  00000000  0001:019195E8 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7077B  00000000  0001:0190F77B D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B73E22  00000000  0001:01912E22 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B70732  00000000  0001:0190F732 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7CD37  00000000  0001:0191BD37 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7AB79  00000000  0001:01919B79 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7A04F  00000000  0001:0191904F D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B706F8  00000000  0001:0190F6F8 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B73DEF  00000000  0001:01912DEF D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7069F  00000000  0001:0190F69F D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01B7CCF4  00000000  0001:0191BCF4 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FC4CD6  00000000  0001:01D63CD6 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FC1995  00000000  0001:01D60995 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FCA16F  00000000  0001:01D6916F D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FC9751  00000000  0001:01D68751 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FC9ACF  00000000  0001:01D68ACF D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
01FC8016  00000000  0001:01D67016 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00EFE196  00000000  0001:00C9D196 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00EFC787  00000000  0001:00C9B787 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00A58C67  00000000  0001:007F7C67 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
00A58386  00000000  0001:007F7386 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
002B8455  00000000  0001:00057455 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
002BADD2  00000000  0001:00059DD2 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D4E2E  00000000  0001:02373E2E D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D4D47  00000000  0001:02373D47 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D4BED  00000000  0001:02373BED D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
025D4E98  00000000  0001:02373E98 D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
75A96359  00000000  BaseThreadInitThunk+19
76F27B74  00000000  RtlGetAppContainerNamedObjectPath+E4
76F27B44  00000000  RtlGetAppContainerNamedObjectPath+B4
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
767D35D2  00000000  RaiseException+62

7B119C39  00000000  _CxxThrowException+A9

025D60DC  00000000  0001:023750DC D:\WoW_Server\WoW_8.2.0\WoW Server\worldserver.exe
Error writing the crash log
`

**Comment by hellfireworld** [comment]
[3d9e21193dd9_worldserver.exe_[26-11_12-38-49].txt](https://github.com/TrinityCore/TrinityCore/files/3891546/3d9e21193dd9_worldserver.exe_.26-11_12-38-49.txt)

**Comment by hellfireworld** [comment]
[6b635bcb802d_worldserver.exe_[27-10_21-45-58].txt](https://github.com/TrinityCore/TrinityCore/files/3891559/6b635bcb802d_worldserver.exe_.27-10_21-45-58.txt)

**Comment by MaxtorCoder** [comment]
Please do not drop the issue template.

**Comment by hellfireworld** [comment]
but it is an issue where do you want me to post it?

**Comment by funjoker** [comment]
```
<!--- (**********************************)
      (** Fill in the following fields **)
      (**********************************)
      For SQL fixes:
      don't modify WDB fields without supply one sniff of those fields (censure guids, character names, anything blizzard can use to identify source)
      don't use pull requests for sql only fixes, unless it's to fix one existing unable to apply file.
      don't hardcode guids.
      don't DELETE + INSERT to update only few fields of one row.
      don't use database names.
      don't put ' around numbers.
      don't put ( ) if they aren't needed.
      use only 1 DELETE + INSERT when we add multiple items to one table, unless you are scripting multiple creatures.
      put default values on every new column we want to add on that way we can make smallers inserts.
      start fix by -- in case some previous sql misses proper ending.
      DELETE by guid AND entry to be sure we don't delete existing spawns.
      start sql code with 3 ` sql         --->

**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS


<!--- Notes
- This template is for problem reports. For other types of report, edit it accordingly.
- For fixes containing C++ changes, create a Pull Request.
--->

```

This is the issue template. you dropped it.

**Comment by MaxtorCoder** [comment]
There is literally a template for issues so you can post here. Edit the post and follow the template.

**Comment by funjoker** [comment]
> I haven't posted anything quite in a while, I was here before lich king branch in mangos so I needed an answer first

> Opened this issue (their first in @TrinityCore)

... i leave this uncommented.

Just use the issue template to report an issue.

**Comment by jackpoz** [comment]
strange how the crash log writes "Error writing the crash log". You might have to Debug worldserver.exe from Visual Studio and post the callstack/autos/locals.

I would say it's also quite strange to see Win32 configuration, I don't think that gets tested that much.

**Comment by hellfireworld** [comment]
jackpoz you helped me fix the error thank you so much ! i just recompiled everything in Win64, I had tried in the past to compile in x64 but I was getting errors so i checked the revisions of mysql, ssl and etc and now its working :)
