### ISSUE TITLE
Crash Server by login Character

### ISSUE THREAD

**Issue by warcrafte** [TrinityCore/TrinityCore#23956]
A player login, Server will to crashed 

/server/game/Entities/Object/Object.cpp:617 in SetUInt32Value ASSERTION FAILED:
  index < m_valuesCount || PrintIndexError(index, true)
MapID: 4294967295 Map name: '<not found>' X: 1284.49 Y: -5089.99 Z: 174.19 O: 2.06352

Branch(es): 3.3.5

TC rev. hash/commit:
https://github.com/TrinityCore/TrinityCore/commit/c79571a09678a5aefe9e7f0d7a936932e0727b2e

TDB version: TDB 335.19101

Operating system: Debian

**Comment by Killyana** [comment]
We need the crash log

also what's this: MapID: 4294967295  Map name: '' X ?

**Comment by warcrafte** [comment]
Not written!

**Comment by Killyana** [comment]
Provide the crash log in this case

**Comment by warcrafte** [comment]
https://gist.github.com/warcrafte/cc0620c7b53c50af0e1d8b142ed761ef

**Comment by Killyana** [comment]
What's the result of this query in characters table?
``` sql
SELECT `name`, `map`, `position_x`, `position_y`, `position_z` FROM `characters` WHERE `name`="Domfire";

**Comment by warcrafte** [comment]
.sum and change map area for character and he have relocated but it has not been repealed!

not' for "X" position

**Comment by Jildor** [comment]
```
Player::_LoadArenaTeamInfo 
arenaSlot = <optimized out>
```
This appears un crashlog, could you check arena tablero un db?

**Comment by warcrafte** [comment]
Sry Guys , This Problem Crash is Not For Source ! and fixed.

-Closed.

**Comment by illfated** [comment]
OK, so I assume we can file this under "NotTrinityCore" as the reason.
