### ISSUE TITLE
Movement/Quest: Death Comes from on High

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23952]
**Description:** After this 2 commits, the auras used to change the speed are no longer working, the vehicle moves like it doesn't have any speed change.
I reverted:
https://github.com/TrinityCore/TrinityCore/commit/81475f709f067eea0437361e7098b7a6b9cf3a26
https://github.com/TrinityCore/TrinityCore/commit/fa9a4ee20d6a63f2e99e9feb45cd0ecf83ccc7f5

And the issue got fixed.

**Steps to reproduce the problem:**

1. .quest add 12641
2. .go game 65961
3. click the gob
4. Notice the speed during the traveling and after

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e0835b467390

**Comment by Ovahlord** [comment]
I love the smell of untested @ccrs changes in the morning~
I'm on it. And I'm like really on it.

**Comment by ccrs** [comment]
yo, the other guy did a followup thingy 💃
