### ISSUE TITLE
[3.3.5] Heart of Archerus - Teleport Platform

### ISSUE THREAD

**Issue by simple4dev** [TrinityCore/TrinityCore#23951]
**Description:**

You cannot reach the second stage of the Deathknight starting area.

**Current behaviour:**

You walk on the Teleport Platform and nothing happens.

**Expected behaviour:**

You walk on the Teleport Platform and you get teleported.

**Steps to reproduce the problem:**

1. Complile TrinityCore branch 3.3.5
2. Create an Deathknight
3. Walk some yards backwards and walk onto the Teleport platform

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2dfa33827028

**Operating system:** Debian GNU/Linux 10 (buster)

**Comment by Aokromes** [comment]
stop using custom trinitycore, it works on clean non-custom core.

https://mega.nz/#!1nAlHArJ!ocGNSkYGz805ihFt2EcxOBzLa8ZNYdFHck0z7IM2338
