### ISSUE TITLE
[3.3.5] Quest: Death Comes from on High (12641)

### ISSUE THREAD

**Issue by simple4dev** [TrinityCore/TrinityCore#23950]
**Description:**

Quest, Spells in DK starting area "Death Comes from on High" isnt able to be complete/incomplete. You cannot finish the quest.

**Current behaviour:**

Eye of Archerus is very very slow. The main Spell that complete the objectives, has visual, but you dont get the objective in your Quest. Stealth Spell works, Ghoul Spell Works, Exit Works, The Spell to complete the Quest seem to work too, but you dont get the objectives.

**Expected behaviour:**

Short after you use the Eye of Archerus Control panel and Possess the Eye, you get a Speedboost down to the Town. After that you should be able to complete the objectives with the first Spell.

**Steps to reproduce the problem:**

1. Complile TrinityCore branch 3.3.5
2. Create an Deathknight
3. Complete first quests until you reach the Eye of Archerus Quest and try to complete it.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2dfa33827028

**Operating system:** Debian GNU/Linux 10 (buster)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2dfa33827028 there is no such hash on trinitycore repo.

**Comment by simple4dev** [comment]
> [2dfa338](https://github.com/TrinityCore/TrinityCore/commit/2dfa33827028) there is no such hash on trinitycore repo.

TrinityCore rev. 2dfa33827028 2019-11-25 08:53:52 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

**Comment by Aokromes** [comment]
you must be using custom core, also it was working the last week on tc.

**Comment by simple4dev** [comment]
> you must be using custom core, also it was working the last week on tc.

it is newest tc with transmog added. i now made new core with a new db too. Same.

***# git show -s --format=%H
e0835b4673900280ae71a2f97dc51335dd817cec
*** #

**Comment by Killyana** [comment]
Credit quest works fine, I will open an other issue for the speed.
