### ISSUE TITLE
Quest: The Symbol of Life

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#23960]
**Description:**
The Symbol of Life is a repeatable quest that becomes available when the quest The Tome of Divinity is accepted.

**Current behaviour:**
The Symbol of Life for dwarfs (1789) is not available when the player has quest 1783
The Symbol of Life for humans (1790) is not available when the player has quest 1786

**Expected behaviour:**
The Symbol of Life should be available if the player has the quest The Tome of Divinity (1783, 1786) 

**Steps to reproduce the problem:**
1. Create a dwarf
2. char lev 12
3. go c id 6179
4. q add 1783

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/d8e12d826c300704d027970a93c5943798be8186
**Operating system:** Win 10

**Comment by offl** [comment]
Added in #25570
