### ISSUE TITLE
ingame crash error 132

### ISSUE THREAD

**Issue by drustcore** [TrinityCore/TrinityCore#23967]
Branch is last revision of trinitycore 8.2.5 32750

on loging ingame after 5 or 10 its keep client crashing 

![ff25615fff3b76af5dcf6aab493d5738-png](https://user-images.githubusercontent.com/45792357/70867858-9127d780-1f7a-11ea-810b-30c220718332.jpg)

**Comment by Fabi** [comment]
append the full txt crash file here.

**Comment by drustcore** [comment]
[2019-12-15 20.16.56 Crash - 2836.txt](https://github.com/TrinityCore/TrinityCore/files/3965360/2019-12-15.20.16.56.Crash.-.2836.txt)
@Fabi

**Comment by Thordekk** [comment]
Fixed can close issue

**Comment by illfated** [comment]
What was the solution? @drustcore : Can you confirm this?
