### ISSUE TITLE
DB/Npc: Earthmender Wilda - Spawn Point

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#23963]
**Description:**

Earthmender Wilda (npc=21027) spawn point issue:
Npc spawns and drops into water when player comes in sigth. I'm not sure whether she glitches through the rock (where she should actually be standing) or whether she spawns in the air. 
When npc is underwater, player can't interact with her (message: to far away).
![WoWScrnShot_121019_191244](https://user-images.githubusercontent.com/9536270/70557582-61945c00-1b83-11ea-8a0e-0a904f10c3c7.jpg)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 8c61ef2 2019-12-09

**Operating system:** 

Win10

**Comment by Killyana** [comment]
Dup #20776
