### ISSUE TITLE
Crash error 132 in game 

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/TrinityCore#23968]
<!--- (crash game error 132)

**Description:**
Create a new character, log in game and u have error #132 client crash

**Current behaviour:**

CHANGEME Tell us what happens.
crash log https://gist.github.com/Thordekk/07a82bdb513c79ddb51e7c790cb9de48

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1 create character and log in game and got crash after seconds

**Branch(es):**

, master

**TC rev. hash/commit:** 
last build

**Operating system:** windows

**Comment by Fabi** [comment]
logfile???

**Comment by Thordekk** [comment]
[2019-12-15 16.33.37 Crash - 3404.txt](https://github.com/TrinityCore/TrinityCore/files/3965359/2019-12-15.16.33.37.Crash.-.3404.txt)

**Comment by Shauren** [comment]
dont need multiple copies of the same issue
#23967

**Comment by drustcore** [comment]
@Shauren u know what the issue its seems u closed multiple comment
