### ISSUE TITLE
Bad Item Drops

### ISSUE THREAD

**Issue by alxayu97** [TrinityCore/TrinityCore#23964]
**Description:**

I have several problems with the item drops. 

On Northrend every time we receive lots of Frostweave Cloth but no weapons or armor.

The same happend on raids. I edited the worldserver.conf and change the Rate.Drop parameters like that:

Rate.Drop.Item.Poor             = 1
Rate.Drop.Item.Normal           = 1
Rate.Drop.Item.Uncommon         = 5
Rate.Drop.Item.Rare             = 5
Rate.Drop.Item.Epic             = 5
Rate.Drop.Item.Legendary        = 6
Rate.Drop.Item.Artifact         = 1
Rate.Drop.Item.Referenced       = 1
Rate.Drop.Money                 = 7

I just update the server right now (22:11 10/12/2019).

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 68c9c65 2019-12-10

**Operating system:** CHANGEME OS

Debian 10.1 x64

**Comment by Aokromes** [comment]
cannot reproduce.

**Comment by alxayu97** [comment]
What do you need?

**Comment by TheWinchesters** [comment]
I have used the same rates and cannot reproduce it either.

**Comment by alxayu97** [comment]
I dropped the entire World database and downloaded the newest .sql file in order to fix it, but I get the same result.
May I send you my worldserver.conf?

**Comment by varandinawer** [comment]
I play in his server, and as information, all the players has multiple professions as tailoring, my wondering is the issue is related to the cloth Scavenging spell from tailoring.

**Comment by Aokromes** [comment]
https://i.imgur.com/k7xL4q2.jpg nope, multiple professions ain't the reason.

**Comment by varandinawer** [comment]
Please, learn https://www.wowhead.com/spell=59390/cloth-scavenging with full tailoring and testing  before put the tag.

**Comment by Aokromes** [comment]
i have tested with that spell too, still works.

**Comment by alxayu97** [comment]
What shall I do? Reinstall the entire server? I tried everything.

**Comment by Kitzunu** [comment]
Even though I know you have installed the latest world update, try checking the loot tables for the mobs that you have trouble with.

**Comment by Jinnaix** [comment]
To be honest - we dont know if people make custom changes to their database that impacts itemdrops.

In addition, anyone can just copy paste the latest revision hash in the issue report - doenst tell you if they havent modified anything. A screenshot with debug command in chat and the loot window open would be better in this case.

Anyway - there wasnt a change to itemdrops in ages, at least none that i can remember.

**Comment by alxayu97** [comment]
The problem is that the entire Northrend has this problem. Every mob have a strange drop rate.
For example: The mammoth on the Borean Tundra drops lots of equipment, but humanoids on Icecrown always drops lots of Frostweave Cloth (Like 5 to 15) each.

I only modified the worldserver.conf and I had never touched the database

**Comment by illfated** [comment]
@alxayu97 : The general consensus is that you must have added some custom changes to your core or DB (or both) to get this problem. If you want any of us others to be able to help or follow up on your issue, we need properly detailed steps to recreate/reproduce/replicate your problem. Otherwise we are left with random guesswork, which does not help any one of us much.

**Comment by Aokromes** [comment]
from where you have downloaded the database and how you import it?
try lower rates.

**Comment by Killyana** [comment]
Provide IDs of npcs that have this issue.

**Comment by alxayu97** [comment]
@Aokromes  I used this guide: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130076/Core+Installation and downloaded the world database from here: https://github.com/TrinityCore/TrinityCore/releases . On the first start of the server it said me to auto create the databases and when it was creating the world database this .sql file was needed, so I put it on the bin folder and everything was created ok.

**Comment by varandinawer** [comment]
Right now I cant provide you the Id for some specific case, but as @alxayu97 said before, It's happens in all the area of Netherlands. In this image (https://imgur.com/a/szBm1RO), you can see the drops for a specdific boss of Gundrak (https://www.wowhead.com/npc=29304/sladran) but almost all the heroic has the same problem.

**Comment by Killyana** [comment]
I cannot reproduce the extra "Frostweave Cloth" are created in a group alone without, changing other loots:
![image](https://user-images.githubusercontent.com/6587064/70623129-b684b080-1c1d-11ea-8941-6bfb9e82c479.png)

**Comment by varandinawer** [comment]
@Killyana, the precondition that the issue happens with the drops rate modified as @alxayu97 said in his first post. You didn't modified, isn't it?

**Comment by Killyana** [comment]
Here with same drop rate as the 1st comment:
![image](https://user-images.githubusercontent.com/6587064/70626428-b9cf6a80-1c24-11ea-88a5-21398cd19b6f.png)
![image](https://user-images.githubusercontent.com/6587064/70626441-c18f0f00-1c24-11ea-9e4d-51cfab664535.png)

**Comment by jackpoz** [comment]
@alxayu97 what happens if you edit the loot rates back to 1 ? are you editing the correct conf file  (you could change the "Motd" setting to be sure) ?

**Comment by varandinawer** [comment]
Thanks for all the effort, it's quite strange that only happen in our sever without a DB modification. We will try to set the rates to 1 and let you know what happens

**Comment by alxayu97** [comment]
Hi everyone.

I found the solution. Here is the problem:

![imagen](https://user-images.githubusercontent.com/18682266/70924411-c0495200-2029-11ea-8186-34e0681667a0.png)

When I put the ReferencedAmount to 1, everything works perfectly. I put the rest of the values to the old values and it works.

@Aokromes please close it as solution for other people with this problem.

Greetings

**Comment by jackpoz** [comment]
What multiplier did you have in your tries ?

**Comment by alxayu97** [comment]
7 on the ReferencedAmount
