### ISSUE TITLE
Warlock Spells-Fear-Rain of Fire

### ISSUE THREAD

**Issue by hellfireworld** [TrinityCore/TrinityCore#23971]
**Description:**

I found out that 2 Warlock spells don't work. The ones I realized they are bugged, it was fear and rain of fire.
I think these are the spell IDs:
Fear Spell ID: 5782
Rain of Fire ID: 42223

**Current behaviour:**

When you cast rain of fire the graphics particles appear but no aoe damage is happening, when you are casting fear and the casting part is complete nothing happens to mobs and characters.

**Expected behaviour:**

Rain of fire -> aoe damage to minions and players in the targeted area.
Fear -> after casting ends the target is feared for some seconds and can't move and attack.

**Steps to reproduce the problem:**

1.Create a warlock class character and cast fear on a target.
2.Create a warlock class character, choose destruction talent tree and cast rain of fire.

**Branch(es):**

master

**TC rev. hash/commit:** 
TrinityCore rev. 18e99ac58aba 2019-12-10 17:55:09 +0100 (master branch)
**Operating system:** Windows OS

**Comment by hellfireworld** [comment]
Why you labeled it not TrinityCore ? but its TrinityCore master branch the revision I am using.

**Comment by Jinnaix** [comment]
> **TC rev. hash/commit:** 

> CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

Maybe because you deleted that instead of doing whats written there?

**Comment by hellfireworld** [comment]
But this doesn't need a fix from terminal... you just need to find out the spell id and fix it in the specific c++ file..., and you can reproduce the bug!

**Comment by hellfireworld** [comment]
I know you have a lot of work to do with the rest of the basic code but I simply came to help you by sharing this ! and to help me when you have time to fix this :) !

**Comment by Jinnaix** [comment]
You asked why your Issue was labeled incomplete and i answered that. Without providing a revision, its hard to tell if someone is really using a clean trinitycore or maybe a repack or something else.

The fear problem is already reported here https://github.com/TrinityCore/TrinityCore/issues/19655

Rain of fire was fixed at a certain point - https://github.com/TrinityCore/TrinityCore/pull/19345

**Comment by MaxtorCoder** [comment]
Follow the template and it won't be marked as 'NotTrinityCore'

**Comment by hellfireworld** [comment]
I am using the last revision of master branch it didn't seem this is fixed thats why I came here to share this. I am sorry if this is not clear I am using latest branch.

**Comment by Warpten** [comment]
It's not about clarity, it's about withstanding time, what will "latest" mean two weeks or three months from now? Thus, "latest" is not a valid revision. Please provide the revision as printed by `.server info`

**Comment by illfated** [comment]
@hellfireworld : You might very well have a valid issue, but without the proper information, it is difficult for others to test or replicate your issue without using the same core revision hash as you do when you experience this issue. It is also very useful later, to see this issue in the perspective of rev. hash release time, whenever something is done to resolve your issue, if it is found to be a valid one.

**Comment by hellfireworld** [comment]
it means one day @Warpten

**Comment by Aokromes** [comment]
https://community.trinitycore.org/topic/37-the-trinitycore-issuetracker-and-you/

**Comment by hellfireworld** [comment]
TrinityCore rev. 18e99ac58aba 2019-12-10 17:55:09 +0100 (master branch) (Win64, Debug, Static)

**Comment by Aokromes** [comment]
not even when you posted you was using latest revision.
https://github.com/TrinityCore/TrinityCore/commits/master

**Comment by hellfireworld** [comment]
Yeah it was like 6 days ahead but I was checking the git commits!

**Comment by Nyr97** [comment]
Invalid. Two completely different spells are being reported on the same bug report. Keep it separated next time so we can keep a track of what PR could fix this issue. Also, this is replicated report.
