### ISSUE TITLE
Spell Frozen Orb is no longer summoning the orb from Toravon in Vault of Archavon

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#23977]
Description:
Right after commit 54f94567649c78d146f4087cc874e4d0cbcff28b ([line 767](https://github.com/TrinityCore/TrinityCore/blob/74f92d776b2c85c8795bae1a216abd8e7ea204fa/src/server/game/Globals/ObjectMgr.cpp#L767)) spell Frozen Orb (72091) is no longer creating the orb from Toravon (38433) in Vault of Archavon.

Expected behaviour:
spell should create the visual of summoning effects and will spawn orb(s)

Steps to reproduce the problem:
1. Go to creature id 38433 and attack him
2. After 12 seconds he starts casting spell 72091
3. No summoning aura visual and no orb spawns

Branch(es):
3.3.5 commit 48bd5633cd076d8819d62adf1ad39557fb22734d

Operating system:
Debian 9.3

**Comment by Killyana** [comment]
It will be fixed soon
``` 
Creature (Entry: 38461) has temporary aura (spell 72094) in `auras` field in `creature_template_addon`.

**Comment by jackpoz** [comment]
@Killyana should we load these auras even after logging the error until most of them have been fixed ?

**Comment by Killyana** [comment]
No, I'm almost done with creature_template_addon

**Comment by Killyana** [comment]
Only 2 remains:
Creature (Entry: 38461) has temporary aura (spell 72094) in `auras` field in `creature_template_addon`.
npc 38461 summoned by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp#L511

Creature (Entry: 34854) has temporary aura (spell 66318) in `auras` field in `creature_template_addon`.
npc 34854 summoned by https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/VaultOfArchavon/boss_toravon.cpp#L82
