### ISSUE TITLE
Crash 3.3.5a

### ISSUE THREAD

**Issue by DykeRz** [TrinityCore/TrinityCore#23975]
Crash after 12 hours online worldserver.exe

revision: TrinityCore rev. f20265feafbf 2019-12-16 10:44:50 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

https://gist.github.com/DykeRz/14bde79559cb2503bf1b5edb4e50483b   -   crash log

**Comment by jackpoz** [comment]
This seems to be WorldUpdateLoop() simply sleeping for too long and triggering FreezeDetector. What's your MaxCoreStuckTime setting ?
Did your system update the clock around the time worldserver crashed ?
Are you running worldserver as Windows Service ?

**Comment by DykeRz** [comment]
> Кажется, это WorldUpdateLoop (), просто спящий слишком долго и запускающий FreezeDetector. Какая у вас настройка MaxCoreStuckTime?
> Обновляла ли ваша система часы во время сбоя мирового сервера?
> Вы используете worldserver в качестве службы Windows?

MaxCoreStuckTime = 60

i don't know if my system updated clock... i slept. I used world server just click it,not from cmd command

**Comment by Takenbacon** [comment]
@jackpoz Theoretically, the core shouldn't be affected by system time changes as it's using chrono::steady_clock.

**Comment by LordWaycrest** [comment]
> @jackpoz Theoretically, the core shouldn't be affected by system time changes as it's using chrono::steady_clock.

Yeah it shouldn't.. When my blades system clock changes it will usually disconnect all players. Can login fine after and the time matching the system clock.

**Comment by jackpoz** [comment]
is this still happening ?

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket.
