### ISSUE TITLE
Core/VMaps: random walls in vmaps

### ISSUE THREAD

**Issue by streetrat** [TrinityCore/TrinityCore#23972]
**Description:**

Some wmo models are extracted wrong, having unneeded polygon which make line of sight errors (and also mmap bugs, because mmaps are generated from vmaps)

**Current behaviour:**

Extracted vmaps have bugged poligons, walls

**Expected behaviour:**

vmap models should be extracted without having random walls

**Steps to reproduce the problem:**

Build core, set it up, extract all maps etc.
log in with gm account
.gm on
.go 3550 -1504 154 1864  (shrine of the storm dungeon, boss Lord Stormsong)
.npc add 128 (or any attackable creature)
.go 3565 -1473 154 1864 (a little back from npc)
try to shoot the npc from distance
you get LOS error because of the bugged vmap

if you need visual confirmation, extract the mmap with debug output for the instance and view the object file in the RecastDemo project

in this case the bugged wmo object is called 8Riv_Krakenstatue01.wmo

![image](https://user-images.githubusercontent.com/457739/70928307-09e96b00-2031-11ea-8496-1abeaebb39e4.png)

same happens in orgrimmar, in the center warchief building, it has about 4 bugged walls
![image](https://user-images.githubusercontent.com/457739/70928454-6056a980-2031-11ea-8095-5b31c1027793.png)

**Branch(es):**

master

**TC rev. hash/commit:** 

18e99ac58abadab6d535c557007bbb9115ea5d4d

**Operating system:** WIN 10

**Comment by Mesielecat** [comment]
I think this issue exist in Stormstout Brewery Dungeon to

**Comment by streetrat** [comment]
> I think this issue exist in Stormstout Brewery Dungeon to

yes

(red lined walls should not be there)

![image](https://user-images.githubusercontent.com/457739/70931892-c1ce4680-2038-11ea-86d9-7b728a092dcc.png)

**Comment by kovrizha** [comment]
It seems there's another place:
Stormwind dwarven district inn entrance (-8373.579, 605.786,  97.778) at 00004730.
On the first screen there's nothing suspicious:
<a href="https://imgur.com/keAhwJQ"><img src="https://i.imgur.com/keAhwJQ.jpg" title="source: imgur.com" /></a>
From inside the building you can see an invisible wall:
<a href="https://imgur.com/NE3nQl8"><img src="https://i.imgur.com/NE3nQl8.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/y7xvE5w"><img src="https://i.imgur.com/y7xvE5w.jpg" title="source: imgur.com" /></a>

**Comment by streetrat** [comment]
the sw dwarven auction house is like this from the inside too  (yep, there should be a door in center) 
![image](https://user-images.githubusercontent.com/457739/71204036-779ace80-229f-11ea-9ea1-abeb9d8fb789.png)

**Comment by kovrizha** [comment]
Tiragarde sound Inn (map16432931):

<a href="https://imgur.com/NYdh7Yg"><img src="https://i.imgur.com/NYdh7Yg.jpg" title="source: imgur.com" /></a>

**Comment by kovrizha** [comment]
map16423430 has mistaken and huge pyramid underneath. Therefore the mmap tile is completely broken there
<a href="https://imgur.com/KQPZGVC"><img src="https://i.imgur.com/KQPZGVC.jpg" title="source: imgur.com" /></a>

**Comment by kovrizha** [comment]
Orgrimar AH, map00012840:
<a href="https://imgur.com/orlyNXQ"><img src="https://i.imgur.com/orlyNXQ.jpg" title="source: imgur.com" /></a>

**Comment by Izidor** [comment]
That is antiportals, the extractor need to ignore them.

**Comment by kovrizha** [comment]
Does anyone have idea how to accomplish this?
According to https://wowdev.wiki/WMO#MOGP_chunk:

"0x4000000	SMOGroup::ANTIPORTAL"

I have tried to modify (exclude objects with previously mentioned mogpflags ) TileAssembler.cpp, wmo.cpp, model.cpp without success.

**Comment by Harrith** [comment]
I found another example in the dungeon Temple of the Jade Serpent.
![mmaps3](https://user-images.githubusercontent.com/40215976/77171649-13b1bd00-6abd-11ea-9b5f-855656c23153.jpg)
![mmaps](https://user-images.githubusercontent.com/40215976/77171651-144a5380-6abd-11ea-9926-9b9ba2c4009f.jpg)
![mmaps2](https://user-images.githubusercontent.com/40215976/77171654-14e2ea00-6abd-11ea-9fe7-0008e708a2ba.jpg)

**Comment by Harrith** [comment]
So after further investigating this issue, I found out that these walls are really "antiportals" as mentioned Izidor above. So I made this change:

According to https://wowdev.wiki/WMO#group_flags , antiportals have MOGP flag 0x4000000, so I just skipped all their triangles.
in wmo.cpp:
`
        //-------INDX------------------------------------
        //-------MOPY--------
        MoviEx = new uint16[nTriangles * 3]; // "worst case" size...
        int *IndexRenum = new int[nVertices];
        memset(IndexRenum, 0xFF, nVertices * sizeof(int));

        // Skip antiportals
        if (!(mogpFlags & 0x4000000))    // <- this was added
        {
            for (int i=0; i < nTriangles; ++i)
            {
                // Skip no collision triangles
                bool isRenderFace = (MOPY[2 * i] & WMO_MATERIAL_RENDER) && !(MOPY[2 * i] & WMO_MATERIAL_DETAIL);
                bool isCollision = MOPY[2 * i] & WMO_MATERIAL_COLLISION || isRenderFace;
                if (!isCollision)
                    continue;

                // Use this triangle
                for (int j=0; j < 3; ++j)
                {
                    IndexRenum[MOVI[3 * i + j]] = 1;
                    MoviEx[3 * nColTriangles + j] = MOVI[3 * i + j];
                }
                ++nColTriangles;
            }
        }
`


I did some tests in Temple of the Jade Serpent, and it works there.
I would be gracious if you check this change.

**Comment by funjoker** [comment]
@Shauren check comment above
