### ISSUE TITLE
The Black Temple: High Warlord Naj'entus bugged script

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23984]
**Description:**

High warlord Naj'entus dos not cast impaling spine, therefore you cannot destroy his tidal shield, making the fight impossible to complete.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/2daddd69981181d4b3e56806bab99b64908124a2

**Operating system:** Win 10 x64

**Comment by Keader** [comment]
I cant reproduce.
You was testing with 1 character?
Because... he dont cast it on tank.
