### ISSUE TITLE
The Black Temple: Gurtogg Bloodboil bugged script

### ISSUE THREAD

**Issue by TerrorBringer** [TrinityCore/TrinityCore#23983]
**Description:**

When Gurtogg bloodboil casts bewildering strike (https://www.wowhead.com/spell=40491/bewildering-strike), he always despawns and respawns after a few seconds, resetting the fight,

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/2daddd69981181d4b3e56806bab99b64908124a2

**Operating system:** Win 10 x64

**Comment by Keader** [comment]
Stop test Black Temple bosses with 1 character.
Gurtogg ignore any target with bewildering strike aura.
Since you're testing alone, it will evade and despawn/respawn.
