### ISSUE TITLE
[master] Dynamic flag 'lootable' makes creature invisible

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#23981]
**Description:**

UNIT_DYNFLAG_LOOTABLE makes creature invisible, even in GM mode.

**Steps to reproduce the problem:**

1. Add 1 to any creature's dynamicflags in creature_template
2. Spawn the creature

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. a0cfb0761899+ 2019-12-14 22:52:49

**Operating system:** Windows 10

**Comment by Shauren** [comment]
No. Stop using outdated definitions. LOOTABLE is 4, not 1.

**Comment by Smerdokryl** [comment]
My apologies.

I was using definitions from https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130008/creature+template
