### ISSUE TITLE
DB/Gossip: Metzen the Reindeer (15664) - incorrect creature gossip

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#23995]
**Description:**

Metzen the Reindeer (entry 15664) uses an incorrect primary (main?) gossip instead of its actual correct one.

- https://classic.wowhead.com/npc=15664/metzen-the-reindeer
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15664/metzen-the-reindeer
- https://classic.wowhead.com/quest=8746/metzen-the-reindeer (Horde)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8746
- https://classic.wowhead.com/npc=13418/kaymard-copperpinch
- https://classic.wowhead.com/quest=8762/metzen-the-reindeer (Alliance)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8762
- https://classic.wowhead.com/npc=13433/wulmort-jinglepocket

**Current behaviour:**

Currently, Metzen the Reindeer (creature id 15664) uses a gossip which looks like an Alliance NPC gossip from Venture Bay in Northrend:

![Metzen the Reindeer wrong gossip SG](https://user-images.githubusercontent.com/38162891/71329766-fe161100-2528-11ea-93f9-1342b7d49059.png) ![Metzen the Reindeer wrong gossip TN](https://user-images.githubusercontent.com/38162891/71329770-040bf200-2529-11ea-8eb5-748bab692332.png)

**Expected behaviour:**

The gossip should look like this:

![Metzen the Reindeer gossip](https://user-images.githubusercontent.com/38162891/71330244-1fc4c780-252c-11ea-9dc8-e113f88c01fe.png)

**Steps to reproduce the problem:**

1. Alliance: go to Wulmort Jinglepocket near the Christmas tree outside the bank in Ironforge.
 Horde: go to Kaymard Copperpinch outside the AH in Orgrimmar.
2. Get the quest "Metzen the Reindeer" from your friendly Smokywood Pastures goblin.
3. Go to either of the 2 spawn locations for Metzen the Reindeer and open his gossip to complete the quest.
4. Notice that the current text is not related to Metzen at all (except for the option bubble text).

**Branch(es):**

At least 3.3.5, possibly master (unable to verify)

**TC rev. hash/commit:** 

TrinityCore rev. 26faca5 2019-12-19 22:27:31 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
```
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.1c  28 May 2019)
Using Boost version: 1.67.0
Using MySQL version: 8.0.18
Using CMake version: 3.13.4
Compiled on: Linux 5.3.0-1008-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19121
```

**Operating system:** Unix (https://tcubuntu.northeurope.cloudapp.azure.com/)

**Note:** I don't know the `broadcast_text` content info for the correct text, so I hope someone else can add the correct `gossip_menu_id` value in the SQL below.

**Suggested solution:**
```sql
-- Metzen the Reindeer gossip text
UPDATE `creature_template` SET `gossip_menu_id` = xxxxx WHERE `entry` = 15664;
```

**Comment by jackpoz** [comment]
```sql
SELECT id, maletext FROM broadcast_text WHERE maletext LIKE '%around this reindeer%'
```
| id | maletext |
| --- | --- |
| 11349 | Around this reindeer's neck is a tag with the Smokywood Pastures logo on it and a name - "Metzen".$B$BMetzen looks at you with sad, forlorn eyes.  It is almost as if the reindeer has been immobilized by some unseen force. |
