### ISSUE TITLE
Core/Movement: Creature in combat continue the waypoint movement instead start chasing the target

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#23993]
**Description:** If you aggro a creature that have a waypoint, when it moves between two points it will not start chasing you until it reach the next point.

**Current behavior:**  Creature will not chase you until it reach the next point.

**Expected behavior:** Creature must interrupt the waypoint and start chasing upon engaged in combat.

**Steps to reproduce the problem:**

1. .go c id 19219
2. .wp show on to see the path
3. choose 2 points far from each other (5-6 for example)
4. once th npc start moving from 5 to 6 aggro it
5. Notice the npc continue the waypoint instead chasing you until reaching the point 6

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 76d404013a6f

**Comment by Rushor** [comment]
issue must have been created in the last 6 months (time: 25.03.2019)

**Comment by Killyana** [comment]
Reference SpawnID: 27114
https://imgur.com/GVYY1Ny
Issue related to the chasing movement, the player need to be too close to the creature to reproduce the issue.

**Comment by jackpoz** [comment]
@ccrs does this sound related to the movement generator rewrite ?

**Comment by ccrs** [comment]
nope, most likely the chase gen one

**Comment by offl** [comment]
I can't reproduce it in 6611b7145746

**Comment by Faq** [comment]
cant reproduce on 3b1e911da3551cf9c69798bbb8b5f52d34be8522
1st case described in issue
[2nd case with](https://github.com/TrinityCore/TrinityCore/issues/23993#issuecomment-606882002) .go c id 4643

**Comment by jackpoz** [comment]
Thanks for the tests 👍
