### ISSUE TITLE
Creature/AI: Creatures must not execute any AI action during the evade

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24009]
**Description:** When I was trying to fix https://github.com/TrinityCore/TrinityCore/issues/24008 I noticed the npc is casting spells during the evade, of course it was missing and I get this in the log:
Mirenuée ruuan'ok DAMAGE_SHIELD_MISSED_EVADE Bouclier de foudre Mirenuée ruuan'ok.

The npc is using SmartAI with the event has_aura to  cast a spell if it has 0 stack of this aura:

entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, comment
(19985, 0, 0, 0, 23, 0, 100, 0, 12550, 0, 3000, 3000, 0, 11, 12550, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, Ruuan'ok Cloudgazer - On missing aura - Cast 'Lightning Shield')

**Steps to reproduce the problem:**

1. use https://github.com/TrinityCore/TrinityCore/issues/24008#issuecomment-569449158
2. .go c 71288
3. Pull the npc far away from the homepos until it evades
4. Notice it will cast the spell many times during the evade state

**Branch(es):**3.3.5

**TC rev. hash/commit:** rev. 53fe73608734

**Comment by jackpoz** [comment]
is there any case where an AI action should be executed during evade or can we assume that's never the case ?

**Comment by Killyana** [comment]
I cannot remember any such case, when we "say" something must be executed on evade it means when the evade is finish (for spawn when they reach home pos)

**Comment by jackpoz** [comment]
I opened PR https://github.com/TrinityCore/TrinityCore/pull/25108 , please test it and test that SMART_EVENT_EVADE still works (and whatever other SAI thingy comes to your mind that I might have broken with the code)

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/420b21be9860367c82537634fb792a4af3d9be9b
