### ISSUE TITLE
Core/Creature: When a creature evades it must reset spells cooldown

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24008]
**Description:**
When a creature evades it must reset spells cooldown.

**Steps to reproduce the problem:**

1. .go c 71284 (entry=19985)
2. aggro the npc and GM ON (twice)
3. Notice the creature will not cast its shield on evade after 3 secs
4. even .cast self 12550 will fail 

You can test also with the (npc=2018) it must cast the spell 12544 OOC after 1 sec.

**Branch(es):** 3.3.5 (both probably)

**TC rev. hash/commit:**  rev. 18a4cbee5eb1

**Comment by Killyana** [comment]
``` diff
diff --git a/src/server/game/AI/CreatureAI.cpp b/src/server/game/AI/CreatureAI.cpp
index ec98534a62..5f1d13e047 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -30,6 +30,7 @@
 #include "ObjectAccessor.h"
 #include "Player.h"
 #include "SpellMgr.h"
+#include "SpellHistory.h"
 #include "TemporarySummon.h"
 #include "Vehicle.h"
 #include "World.h"
@@ -309,6 +310,7 @@ bool CreatureAI::_EnterEvadeMode(EvadeReason /*why*/)
     me->SetLastDamagedTime(0);
     me->SetCannotReachTarget(false);
     me->DoNotReacquireSpellFocusTarget();
+    me->GetSpellHistory()->ResetAllCooldowns();
     EngagementOver();
 
     return true;

**Comment by jackpoz** [comment]
the change looks good, you can push it after testing the build and testing it ingame (or open a PR to test the build automatically)

**Comment by Jildor** [comment]
Only for ensure, pets doesn't enter on evade mode no?

**Comment by Killyana** [comment]
I will test pets
