### ISSUE TITLE
Is it possible to bring the server back to version 8.2.0 31478 by ourselves?

### ISSUE THREAD

**Issue by buddyqc69** [TrinityCore/TrinityCore#24013]
Is it possible to bring the server back to version 8.2.0 31478 by ourselves? because I tested and it does not mean it says that the DBCs are not correct, I check to have the good DBCs from the same client as this version and nothing works, except when I return to version 8.2. 0 32750 (I have several client versions.)

Trinitycore Master Branch, Last release

**Comment by Aokromes** [comment]
this ain't a bug and doesn't  belong to BUG tracker.
