### ISSUE TITLE
Core/Movement: Player cannot charge when falling

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24011]
**Description:** Try to charge a target when your character is falling, it will always returns no path available.

**Expected behavior:**

Warriors must b able to charge to avoid fall damage.

**Steps to reproduce the problem:**

1. .gm fly on
2. put you character above the target and slightly behind it
3. .gm fly off
4. spam charge when you're falling

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 53fe73608734

**Comment by Killyana** [comment]
Or easier way, use you flying mount in Northrend and activate the option "auto dismount when I cast a spell" then try to charge a creature when you're in your flying mount

**Comment by jackpoz** [comment]
Is a player supposed to be able to charge upwards or only downwards when falling ? I'm wondering about some "abusers" that jump a bit and charge all the way to the top of the world

**Comment by Killyana** [comment]
Only downwards

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24010
