### ISSUE TITLE
[CORE] Selecting nearest Player, NPC and GameObject

### ISSUE THREAD

**Issue by ravel1** [TrinityCore/TrinityCore#24016]
**Description:**

`Player* WorldObject::SelectNearestPlayer(float distance) const` dosen't work at all.

**Current behaviour:**

In any script, when NPC is trying to select nearest Player, NPC or GameObject there is no action. For example:
```
if (Player* player = me->SelectNearestPlayer(20.0f))
    me->CastSpell(1234, player);
```
or
```
if (Creature * npc = me->FindNearestCreature(1234, 20.0f))
    {
      me->CastSpell(1234, npc);
      if (npc->HasAura(1234))
      npc->Talk(1234, CHAT_MSG_MONSTER_YELL, 50, npc);
       else
         npc->CastSpell(1234, me);
    }
```

**Expected behaviour:**

Function should select nearest Player, NPC or GameObject in range (float distance).

**Steps to reproduce the problem:**

Have no idea.

**Branch(es):**

master

**TC rev. hash/commit:** 

[d101038](https://github.com/TrinityCore/TrinityCore/commit/d1010386c91663d95428f6047ac7972bbc58b468)

**Operating system:** Linux

**Comment by jackpoz** [comment]
have you tried debugging it ?

**Comment by ravel1** [comment]
Of course, the same result

**Comment by jackpoz** [comment]
Which checks skips the player in range ? Is is phase check or IsAlive() check ? That's what I meant with "have you tried debugging it? "

**Comment by ravel1** [comment]
All of them. It's doesn't matter if You will use any checks. It doesn't work at all. 
Btw. without any logs

**Comment by grzewal1** [comment]
After changes to 8.2, it also doesn't work in target type SMART_TARGET_CLOSEST_PLAYER in the smart_scripts table

**Comment by ravel1** [comment]
UPDATE:
FindNearestCreature, FindNearestGameObject and anything with select npc, player or gameobject dosen't work as well.
