### ISSUE TITLE
Creature/Script: Risen Archmage

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24012]
**Description:** Risen Archmage recast the spell id: 70602 [Corruption]  once dead
https://imgur.com/GVB7nhw
https://www.wowhead.com/npc=37868/risen-archmage

I'm not sure if it's recast here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp#L759-L762

Or it's jut not interrupted properly here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp#L716

If you list aura Valithria you will see 4 auras from 70602, even if you aggro the 4  Risen Archmage this 4 auras remains, normally they must be removed upon the channeling is stopped.

Also if you kill the 4 mages without aggo, Valithria will not show the 4 auras (and the 4 Risen Archmage will not cast the spell while being dead).
You can also cast your self the spell 70602 in Valithria and see an aura 70602  was added, and upon you interrupt your channeling the aura is removed

``` 
id: 70602 [Corruption] effmask: 1 charges: 0 stack: 1 slot 2 duration: -1 maxduration: -1   caster: creature guid: 336
id: 70602 [Corruption] effmask: 1 charges: 0 stack: 1 slot 3 duration: -1 maxduration: -1   caster: creature guid: 338
id: 70602 [Corruption] effmask: 1 charges: 0 stack: 1 slot 4 duration: -1 maxduration: -1   caster: creature guid: 337
id: 70602 [Corruption] effmask: 1 charges: 0 stack: 1 slot 5 duration: -1 maxduration: -1   caster: creature guid: 335
``` 
**Steps to reproduce the problem:**

1. .go c id 36789
2. Do the tests explained above

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. cb11ad97fb9e

**Comment by Keader** [comment]
Try this:

```diff
diff --git a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
index 4ecd7695a7..abf1be0a02 100644
--- a/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
+++ b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
@@ -713,7 +713,7 @@ class npc_risen_archmage : public CreatureScript
 
             void JustEngagedWith(Unit* target) override
             {
-                me->FinishSpell(CURRENT_CHANNELED_SPELL, false);
+                me->InterruptNonMeleeSpells(false);
                 if (_isInitialArchmage && _canCallJustEngagedWith)
                 {
                     if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_VALITHRIA_LICH_KING)))
```

**Comment by Killyana** [comment]
I tried this yesterday, I was happy seeing auras removed from Valithria, but upon killing an archimage it starts casting the spell back...

**Comment by Keader** [comment]
2f31119ea337aedecc593b6bb687ad73390db3a2
