### ISSUE TITLE
Build with ninja raise build error in windows

### ISSUE THREAD

**Issue by ryancheung** [TrinityCore/TrinityCore#24015]
**Description:**

Build with ninja in windows raise the following build error:
```
[build] Launching build
[proc] Execute command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/WoWEmulators/TrinityCore/build --config RelWithDebInfo --target all -- -j 14
[build] ninja: error: 'PrecompiledHeaders/commonPCH.h', needed by 'src/common/CMakeFiles/common.dir/Banner.cpp.obj', missing and no known rule to make it
[build] build completed，exit code is 1
```

**Expected behaviour:**

It should not raise error when building with ninja in windows.

**Steps to reproduce the problem:**

1. Grab a VSCode and have cmake tool extension installed.
2. Open TrinityCore source directory with VSCode.  
3. Setup cmake option with .vscode/settings.json, like:
```
{
    "cmake.buildDirectory": "${workspaceRoot}/../build",
    "cmake.installPrefix": "${workspaceRoot}/../server",
    "cmake.configureSettings": {
        "SERVERS": true,
        "WITH_COREDEBUG": true,
        "WITH_WARNINGS": false,
        "TOOLS": true,
        "SCRIPTS": "dynamic"
    }
}
```
4. Select toolkit in vscode and click the cmake buid button and it will start to build with **ninja**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/e698c17a2688385e62744cdf5eb37b12b9e304fa

**Operating system:** Windows 10 64Bit

**Comment by Carbenium** [comment]
@ryancheung Could you re-test this with a current version of TC? Specifically after cb5694607d8640b1ad54f7bdaf5f17482a97bc85

**Comment by Shauren** [comment]
I already fixed ninja earlier than that
