### ISSUE TITLE
DB / Quest : Investigate the Blue Recluse

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#24024]
**Description:**

The task cannot be completed - it is not working properly

**Current behaviour:**

After starting the task using [Cantation of Manifestation](https://classic.wowhead.com/quest=1920/investigate-the-blue-recluse)  all creatures (outpacing) come instead of just two creatures per attack 

**Expected behaviour:**

This video shows exactly how this should be done => [video ](https://youtu.be/UvqaOo9c5P0)

1. .go xyz -9076.005859 831.177307 108.419838
2. .quest add 1920  
3. .additem 7247  + .additem 7308
3. run the task

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 7fb74326205a 2019-12-30 19:03:14 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0l  10 Sep 2019 (library: OpenSSL 1.1.0l  10 Sep 2019)
Using Boost version: 1.66.0
Using MySQL version: 5.7.26
Using CMake version: 3.15.5
Compiled on: Windows 10.0.18362
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.19121

**Operating system:**  Win 10 Pro  1903 Build 18362.535

Edit :  another source of information link [Wowpedia](https://wow.gamepedia.com/Investigate_the_Blue_Recluse)

**Comment by Faq** [comment]
Those mobs with invisibility spawned there and just 4 in balcony floor, none in basement where should be 1 according wowhead comments. Looks like missing spawns.
One from solution would be limit targets or just radius of spell casted from Cantation of Manifestation https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=9095 (100y radius will aggro all 4 what are spawned there).

**Comment by illfated** [comment]
https://www.wowhead.com/spell=9095/cantation-of-manifestation
(https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=9095)
does not have 100 yards range as such, it is 0 (self).
The 100 yard effect is supposedly `Apply Aura: Invisibility`

**Comment by dr-j** [comment]
Well if anyone can sniff actual location of these on classic and the same npcs for the horde equivalent would be useful these were not spawned from sniff has none existed as quests had been removed from game in cata and we did not think would ever get data

**Comment by Rushor** [comment]
set the creature to faction 35 instead of let it evade

**Comment by Rushor** [comment]
also this

9095   // Cantation of Manifestation
spellInfo->MaxAffectedTargets = 1;

is needed, since the spell should only trigger to spawn one ghost

**Comment by Faq** [comment]
@Rushor https://www.youtube.com/watch?v=UvqaOo9c5P0&feature=youtu.be shows 2 spawns and from comments looks like it is a bit random some say 1, some 2.

**Comment by jjo72ddd** [comment]
I tried this code. After this, the mobs did not appear
```sql
UPDATE creature_template SET faction = 7 WHERE entry=6492;
```

**Comment by dr-j** [comment]
Try this unless its already committed, ive been sitting on this for 4 years did not think was that long but apparently made the following sql feb 2016 p: not sure this may not be the sql I was looking for 
~~~sql
UPDATE `smart_scripts` SET `action_type`=20, `action_param1`=0, `comment`='Rift Spawn - on 1% Hp - Disable Autoattack' WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=10 AND `link`=11;
DELETE FROM `smart_scripts` WHERE `entryorguid`=6492 AND `source_type`=0 AND `id`>21;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(6492, 0, 21, 22, 0, 2, 100, 0, 30000, 30000, 30000, 30000, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - OOC (Phase 2) - Set Faction'),
(6492, 0, 22, 0, 61, 0, 100, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - OOC (Phase 2) - Evade'),

(6492, 0, 23, 0, 11, 0, 100, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - On Respawn  - Enable Auto Attack');
UPDATE `smart_scripts` SET `event_type`=21, `action_param1`=0, `comment`='Rift Spawn - On Reached Home Position - Despawn' WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=14 AND `link`=0;
UPDATE `smart_scripts` SET `link`=0 WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=13 AND `link`=14;
UPDATE `smart_scripts` SET `link`=19 WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=16;

**Comment by illfated** [comment]
@jjo72ddd : Feel free to test the SQL from **dr-j** to see if that works.

Please also note that when people suggest things like
> set the creature to faction 35 instead of let it evade

this usually means that this needs to happen at a certain step in a script, not be the permanent value for the creature.

**Comment by shamage** [comment]
>@jjo72ddd :  I tried this code. After this, the mobs did not appear
> 
> ```sql
> UPDATE creature_template SET faction = 35 WHERE entry=6492;
> ```


[Rift Spawn](https://classic.wowhead.com/npc=6492/rift-spawn) appears on [Connor Rives](https://classic.wowhead.com/npc=5081/connor-rivers) after being invoked via Quest Item  but will not attack  just following my move

**Comment by shamage** [comment]
@dr-j 
> Try this unless its already committed, ive been sitting on this for 4 years did not think was that long but apparently made the following sql feb 2016 p: not sure this may not be the sql I was looking for
> 
> ```sql
> UPDATE `smart_scripts` SET `action_type`=20, `action_param1`=0, `comment`='Rift Spawn - on 1% Hp - Disable Autoattack' WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=10 AND `link`=11;
> DELETE FROM `smart_scripts` WHERE `entryorguid`=6492 AND `source_type`=0 AND `id`>21;
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> (6492, 0, 21, 22, 0, 2, 100, 0, 30000, 30000, 30000, 30000, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - OOC (Phase 2) - Set Faction'),
> (6492, 0, 22, 0, 61, 0, 100, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - OOC (Phase 2) - Evade'),
> 
> (6492, 0, 23, 0, 11, 0, 100, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Rift Spawn - On Respawn  - Enable Auto Attack');
> UPDATE `smart_scripts` SET `event_type`=21, `action_param1`=0, `comment`='Rift Spawn - On Reached Home Position - Despawn' WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=14 AND `link`=0;
> UPDATE `smart_scripts` SET `link`=0 WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=13 AND `link`=14;
> UPDATE `smart_scripts` SET `link`=19 WHERE  `entryorguid`=6492 AND `source_type`=0 AND `id`=16;
> ```

In fact, only one has changed after applying your code - you can only call Rift Spawn once. (correct me if I'm wrong) but all four will still come at once instead of two after applying the item. What's wrong is that if HP drops to 1, instead of dropping HP to zero and they die they run away - they can't be killed. This is one of the serious reasons why the task cannot be completed.  
So far I have been able to test from your code.
I consider what value would need to be adjusted in order to kill creatures. Perhaps in this direction, we should choose as a first step to shift improvement, or at least be able to complete the task even if it needs to be fine-tuned.

**Comment by shamage** [comment]
@dr-j :
after a successful first step, as a second step, I would choose to reduce the functionality of item [Cantation of Manifestation]( https://classic.wowhead.com/item=7308/cantation-of-manifestation)  
after a successful first step, as a second step, I would choose to reduce the impact of the item's functionality only to the cellar - where the task is actually to be performed. Can you deal with it?  I am weak on such a task to be able to do it.

**Comment by illfated** [comment]
Maybe it would be helpful to have some information at hand
- https://classic.wowhead.com/quest=1920/investigate-the-blue-recluse
- https://classic.wowhead.com/item=7247/chest-of-containment-coffers
- https://classic.wowhead.com/item=7308/cantation-of-manifestation
- https://classic.wowhead.com/spell=9095/cantation-of-manifestation
- https://classic.wowhead.com/spell=9096/rift-spawn-manifestation
- https://classic.wowhead.com/search?q=manifestation#uncategorized-spells
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Manifestation#spells

Compare the last 2 links and notice that there is a difference in spell assignments.

**Comment by jjo72ddd** [comment]
okay, it seems there still needs to be used spell 9010
.cast 9010

**Comment by shamage** [comment]
>@jjo72ddd :
> okay, it seems there still needs to be used spell 9010
> .cast 9010
> 
> I don’t understand why they don’t cast it when I enter:
> 
> ```sql
> (6492,0,17,8,61,0,100,0,0,0,0,0,0,11,9010,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Rift Spawn - Between 0-1% Health - Cast 'Create Filled Containment Coffer'")
> ```
> 
> I just wanted to test it
> 
> [this video is about how it works](https://www.youtube.com/watch?v=f0NxCuitVBI)

according to your video, there's no need to do that in the basement, and it even works beautifully

**Comment by jjo72ddd** [comment]
I don’t understand how smart_scripts works.

**Comment by illfated** [comment]
There is also a gameobject (spell focus) placed in the cellar, requiring spell 9095 (Cantation of Manifestation) to be cast near the gameobject/spell focus object.
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=103708 (Mana Rift Disturbance)

**Comment by jjo72ddd** [comment]
Now I'm trying to find a way to interact after the caste. But I only found SMART_EVENT_VICTIM_CASTING. Do we have an event that takes place after a player’s cast?

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fa770897ccbb2274cfebbfb5409c7a6dc0879e2e was original script for this

**Comment by dr-j** [comment]
The despawn issue may actually be due to core changes or it may because the rift spawn summons bunny which in turn summons filled containment coffer and then immediately despawns this maybe what’s causing the issue as have noticed that creatures summoned with event 12 now despawn when summoner despawns this never used to happen

**Comment by Tauriella** [comment]
Many thanks for fixing the ancient Bug :+1:
