### ISSUE TITLE
DB/trainers: Tailoring trainers NPC Magar Orgrimmar

### ISSUE THREAD

**Issue by buddyqc69** [TrinityCore/TrinityCore#24022]
Horde, Tailoring trainers
not responding and profession not working

https://www.wowhead.com/npc=3363/magar

if you want to upgrade you professions is not possible because 0/0.

Trinitycore-Master Last Release And SQL Update up to date, 8.2.5 32750 Build

TrinityCore rev. d1010386c916 2019-12-17 01:23:24 +0100 (master branch) (Win64, Release, Static)

**Comment by illfated** [comment]
You know, TC has put the issue template there for a good reason. If you report a bug and want to get it fixed, it is in your own best interest to make use of the template and not delete it.

**Comment by buddyqc69** [comment]
My english is bad sorry, i just want to help the community, my issue is true, after you have learn tailoring
https://classic.wowhead.com/spell=3908/tailoring
Is not possible to levelup the professions

**Comment by Killyana** [comment]
Some trainers are missing the npc_flag=64
``` sql
SELECT npcflag FROM `creature_template`   WHERE   `Entry` IN (3363,3523); 
-- 17= Gossip + Trainer
``` 
Trainers must also have the flag =64 Profession Trainer

Try: 
``` sql
UPDATE `creature_template`  SET `npcflag`=`npcflag`|64 WHERE   `Entry` IN (3363,3523);
```

**Comment by Killyana** [comment]
Same issue as https://github.com/TrinityCore/TrinityCore/issues/20193
@funjoker  any Idea why the wpp don't output this flag?

**Comment by Killyana** [comment]
Also this 2 trainers are missing from `creature_default_trainer` they must have TrainnerId= 163

**Comment by buddyqc69** [comment]
I try this now, i have checked for change like another npc but doesnt work, i check for this. Thank

**Comment by buddyqc69** [comment]
ok the npc work now, but the profession tailoring that not possible to upgrade, that bug inside the core ?

**Comment by buddyqc69** [comment]
i think have trouble in conditions table for levelup skill tailoring, doesnt work 0/0 after try to levelup the skill, that wrong data on the skill ?

**Comment by Killyana** [comment]
No idea I need to install the server and check

**Comment by buddyqc69** [comment]
we have try blacksmitthing and is work fine for levelup skill, but this skill doesnt levelup

**Comment by illfated** [comment]
Could it be wrong spell ID, that there are several similar tailoring level 1 spells, but the wrong one is used by the trainer? Have you tried `.lookup spell tailor` to see what the list contains?

**Comment by Killyana** [comment]
So npcflags 32 and 64 are no longer used in master, the issue with trainers is missing data, also for trainers with gossip we don't use `creature_default_trainer` but `gossip_menu_option_trainer`
``` sql
UPDATE `creature_template` SET `gossip_menu_id`=4267 WHERE `entry`=3523;
DELETE FROM `gossip_menu_option_trainer` WHERE `MenuId` IN (4347,4267);
INSERT INTO `gossip_menu_option_trainer` (`MenuId`, `OptionIndex`, `TrainerId`) VALUES
(4347, 0, 163),
(4267, 0, 163);

**Comment by Killyana** [comment]
Data in `trainer_spell` is from Legion (7.3.5 Build 26124) before BFA Professions rework, it will not allow you XP.

**Comment by buddyqc69** [comment]
@illfated i have already check this with lookup and the spell for the skill that 197 and if i learn the spell that the same trouble to levelup the profession but i can learn the skill on the npc trainers after @Killyana have send the last mysql query, very nice but how to fix the levelup in the profession if is stuck at 0/0 ?

**Comment by buddyqc69** [comment]
@illfated 
i have this after:
TC> lookup skill tail
197 - Tailoring
2533 - Kul Tiran Tailoring
2534 - Legion Tailoring
2535 - Draenor Tailoring
2536 - Pandaria Tailoring
2537 - Cataclysm Tailoring
2538 - Northrend Tailoring
2539 - Outland Tailoring
2540 - Tailoring
