### ISSUE TITLE
Core/MMaps: Anub'Rekhan room

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24027]
It seems there is an issue as to how Imp acts in "The Arachnid Quarter" Anub'Rekhan Encounter.
Warlock Pet, Specifically : Imp, has issues. After few seconds the Imp submerges to the ground half way and when walking through the green circle in a middle it sometimes disappear and then reappears and sometimes get's stuck in mid air. Tested all other pets, seems fine.

On the same note, Anub'Rekhan sometimes can reset during the encounter 2-3 times especially when a tank is kiting Anub'Rekhan in circles. This somehow maybe or maybe not related to this issue.

![image](https://user-images.githubusercontent.com/56239974/71638021-4f00c600-2c09-11ea-9c44-38def535465d.png)

![image](https://user-images.githubusercontent.com/56239974/71638026-6d66c180-2c09-11ea-8dd6-3cd2dc12b0f6.png)

![image](https://user-images.githubusercontent.com/56239974/71638002-ad797480-2c08-11ea-85f4-69a4cd3ee2f3.png)

1. Got to Naxxramas, Anub'Rekhan Encounter. Go to any wall and walk through the green circle to another wal and back to where you were. Repeat few times
2. Note Imp will be half submerged
3. See how Imp will eventually disappear or start climbing up the air

Branch: 3.3.5
Commit: https://github.com/TrinityCore/TrinityCore/commit/88a14251e2765880e90cb41be7919cd39e3308e2
OS: Windows 2012 Server Edition

**Comment by jackpoz** [comment]
Did this issue start happening at any particular commit ? Could you test an older one to find which one added the issue ?

**Comment by Killyana** [comment]
This is not related to pets but an issue with mmaps.
.go xyz 3273.895, -3476.8498, 287.076141 533
.npc follow little spiders around or summon a pet or spawn a npc an notice the behaviour.

**Comment by WoWPortal** [comment]
Yep confirmed @Killyana 

So could the reset of Boss Encounter has something do with it? Because the boss in question resets every time you get near that spot.

**Comment by Killyana** [comment]
It could be

**Comment by illfated** [comment]
Maybe adjust the title a little bit more (for later discovery purposes)? 
i.e. **Core/mmaps:** (and so on)

**Comment by WoWPortal** [comment]
**Core/MMPS: Anub'Rekhan room #24027**
Is named correctly.

**Comment by illfated** [comment]
OK, does that mean mmaps is changing name to "MMPS" or that "MMPS" is a new term covering more than "mmaps" ?

**Comment by junker1609** [comment]
I confirm, after the bump, sometimes Anub'Rekhan regen his life
I still haven't figured out where it came from

**Comment by illfated** [comment]
Is this from before or after the movement changes? Which commit have you compiled your server on?

**Comment by junker1609** [comment]
> Is this from before or after the movement changes? Which commit have you compiled your server on?

![update](https://user-images.githubusercontent.com/57899911/72729579-bddd9900-3b8f-11ea-8a1e-8f4943d449ae.png)

**Comment by illfated** [comment]
Well, that is how up to date your database is (TDB ) as of commit https://github.com/TrinityCore/TrinityCore/commit/a249044700f0c44e54b77ced39a8e1ae86d30cf5 .
Your core does not have to be the same, but maybe you don't have server access.

**Comment by illfated** [comment]
Please try with https://github.com/TrinityCore/TrinityCore/commit/67d9d04d63cc74196059646b2e57f50a4a4fd2ca included in your core (and with Transmog disabled).

**Comment by junker1609** [comment]
> Please try with [67d9d04](https://github.com/TrinityCore/TrinityCore/commit/67d9d04d63cc74196059646b2e57f50a4a4fd2ca) included in your core (and with Transmog disabled).

I'm going to try this tonight, thanks.

**Comment by junker1609** [comment]
> Please try with [67d9d04](https://github.com/TrinityCore/TrinityCore/commit/67d9d04d63cc74196059646b2e57f50a4a4fd2ca) included in your core (and with Transmog disabled).

Anub does not regen anymore. thank you.

**Comment by Rushor** [comment]
the regen on reset will not work anymore then?

**Comment by jackpoz** [comment]
I guess he means Anub doesn't regen life anymore during combat as now it can always reach the player (bosses regen life in combat if they cannot reach their target after some seconds)

**Comment by Killyana** [comment]
Cannot reproduce in rev. b304f4ad8d06
