### ISSUE TITLE
Duplicate Spawns - Player Reported (Confirmed by Moderator)

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24037]
**Description:**

Duplicated creatures Riverpaw Runt and Riverpaw Outrunner.

**Current behaviour:**

A player reported 2 duplicated creatures.

**Expected behaviour:**

Should only be 1 creature on each spot

**Steps to reproduce the problem:**

1. Teleport to posX: -9947.26 posY: 620.057 PosZ: 37.2154
2. Discover that there are 2 duplicated creatures.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 7fb74326205a+ 2019-12-30 19:03:14 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by illfated** [comment]
Confirmed. The XYZ coordinates above might be tricky to use correctly with the .tele command, so it could be easier to do it in 2 steps:
1. .tele elwynn
2. .go zonexy 26.3 86.6

The 2 double spawns are standing on both sides of a campfire, between 2 tents and crates, in the area north of Hogger, but closer to (and also north of) Gruff Swiftbite.
Both double spawns are 1 Riverpaw Runt and 1 Riverpaw Outrunner in the same location.

GUIDs:
2151 (Runt) + 2156 (Outrunner)
2152 (Runt) + 2157 (Outrunner)

TrinityCore rev. 677834dca7fc 2020-01-03 13:44:42 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
(https://tcubuntu.northeurope.cloudapp.azure.com/)
