### ISSUE TITLE
Compile warning C4819 for npc_innkeeper.cpp	

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#24038]
**Description:**

Compiling got:
> Severity	Code	Description	Project	File	Line
> Warning	C4819	The file contains a character that cannot be represented in the current code page (1257). Save the file in Unicode format to prevent data loss	scripts	C:\source\TrinityCore335 clean\src\server\scripts\World\npc_innkeeper.cpp	1

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

Just compile with "RelWithDebInfo"

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 
TrinityCore revision   : 739383b52e4d 2020-01-03 19:54:55 +0100 (3.3.5 branch)

**Operating system:**  w7

**Comment by jackpoz** [comment]
https://ci.appveyor.com/project/DDuarte/trinitycore/builds/29882450#L697 didn't report any warning.

This is the output I get:
>1>------ Build started: Project: scripts, Configuration: Debug x64 ------
1>npc_innkeeper.cpp
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

so cannot reproduce the issue

**Comment by Faq** [comment]
It compiles in Debug too:

> 24>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
> 24>Building Custom Rule C:/source/TrinityCore335 clean/CMakeLists.txt
> ========== Build: 24 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

But warning still the same.

**Comment by illfated** [comment]
@Faq : Which one of the lines is the offending one? Is it the Spanish line in the `#defines` section?
(another reason to offer assistance to get those pesky hardcoded text moved to DB)

**Comment by Faq** [comment]
All info is provided in my previous posts.

**Comment by illfated** [comment]
Well, OK. I see "line1" is shown at the end of the error message,
> Warning C4819 The file contains a character that cannot be represented in the current code page (1257). Save the file in Unicode format to prevent data loss scripts C:\source\TrinityCore335 clean\src\server\scripts\World\npc_innkeeper.cpp line1

but I still wonder what your VS2019 counts as line 1 in that file. Does it include the comment lines, or does it only count the code lines except for the comments?
Anyway, it looks like this could be specific to VS2019, so I will have to install that version to test if I get the same message as you.

**Comment by shamage** [comment]
Compilation was : TrinityCore revision   : 4f2f1959c3c3 2020-01-04 18:58:55 +0100 (3.3.5 branch) 

I have a  Microsoft Visual Studio Professional 2019 Version 16.4.2  and the compilation was successful without errors or warnings .  I suggest that you update your compiler to the latest version .

// Microsoft Visual Studio Professional 2019  Version 16.4.2 (( Visual Studio. 16. Release/16.4.2+29613.14 ))

**Comment by illfated** [comment]
Thanks for the feedback. Did you compile RelWithDebInfo instead of Release?

**Comment by Faq** [comment]
I used 16.5.0 preview1

**Comment by shamage** [comment]
compilation I did two types one was just "Debug" and the other "RelWithDebInfo" both compilations went well and without errors or warnings

**Comment by illfated** [comment]
@Faq Maybe your VS preview1 version is showing a bug symptom?

**Comment by Faq** [comment]
then close it :)

**Comment by Killyana** [comment]
It's weird you opened this issue 1 day after I changed some gossips for npcs that use: npc_innkeeper https://github.com/TrinityCore/TrinityCore/commit/87e1f7366a6b73475f4ca893d0e7a22651c5c1ad
I checked the script and every npc, and every thing works properly.

**Comment by Faq** [comment]
@Killyana nothing weird, 2d ago updated VS, cmake, boost, core and db, what was not done since summer.

**Comment by illfated** [comment]
Fair enough. We could wait a few days to see if anyone else can confirm your VS2019 issue.
