### ISSUE TITLE
[3.3.5] Added Missing Calendar events and updated game_event to match for the next 5 years.

### ISSUE THREAD

**Issue by natnat201193** [TrinityCore/TrinityCore#24045]
So currently, Lunar Festival, Love is in the air, Pilgrim's Bounty, Children's week, Noblegarden and Harvest Festival are missing from the Calendar.
I have added the missing Calendar events for the next 5 years and updated game_event to match.
I adjusted the start dates based on retail current start dates and the lengths based on what the Calendar shows ingame so it matches.

EDIT:  This part is no longer relevant, thanks to @Ovahlord this can now be done serverside. still wont be blizzlike unless we update the dates the same way blizzard does, but at least the duration can now be changed on the calendar.
> The one event that lasts a bit longer due to this is Lunar festival, it shows 21 days on the Calendar which we cant change as far as I'm aware, so I just made it match.
Before anyone says 21 days is not blizzlike, I know it's not and we won't get blizzlike unless we update the dates to match the real-world events like blizzard does, this would need clientside edits.
If you don't want it to be 21 days, you can always adjust the length, but it won't match the Calendar if you do. 

NOTE: I had to set holidayStage to 0 because 1 seems to block the game_event values. For example: if I change the occurrence to 365 days, it will not change and it will instead stay at 360 days ingame.

Tests Made: 
Changed my system date to 2026, checked the events are on the Calendar until 2025.
Changed my system date to just before some of the events were about to start and checked they start at the correct time.

TrinityCore rev. a149261e94b6 2020-01-09 23:10:46

```sql
-- Lunar Festival. Holiday ID: 327.
UPDATE `game_event` SET `start_time`='2020-01-24 00:01:00', `holidayStage`='0', `occurence`='525600', `length`='30240' WHERE  `eventEntry`=7;
SET @HOLIDAYID := 327;
SET @DATEID := 14;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	335921152), -- 2020-01-24.
(@HOLIDAYID, @DATEID+1, 352681984), -- 2021-01-23.
(@HOLIDAYID, @DATEID+2, 369459200), -- 2022-01-23.
(@HOLIDAYID, @DATEID+3, 386236416), -- 2023-01-23.
(@HOLIDAYID, @DATEID+4, 403013632), -- 2024-01-23.
(@HOLIDAYID, @DATEID+5, 419774464); -- 2025-01-22.

-- Love is in the air. Holiday ID: 423.
UPDATE `game_event` SET `start_time`='2020-02-08 00:01:00', `holidayStage`='0', `occurence`='525600', `length`='20160' WHERE  `eventEntry`=8;
SET @HOLIDAYID := 423;
SET @DATEID := 10;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	336707584), -- 2020-02-08.
(@HOLIDAYID, @DATEID+1, 353468416), -- 2021-02-07.
(@HOLIDAYID, @DATEID+2, 370245632), -- 2022-02-07.
(@HOLIDAYID, @DATEID+3, 387022848), -- 2023-02-07.
(@HOLIDAYID, @DATEID+4, 403800064), -- 2024-02-07.
(@HOLIDAYID, @DATEID+5, 420560896); -- 2025-02-06.

-- Pilgrim's Bounty. Holiday ID: 404.
UPDATE `game_event` SET `start_time`='2020-11-23 00:01:00', `occurence`='525600', `length`='10080', `holidayStage`='0' WHERE  `eventEntry`=26;
SET @HOLIDAYID := 404;
SET @DATEID := 11;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	346390528), -- 2020-11-23.
(@HOLIDAYID, @DATEID+1, 363167744), -- 2021-11-23.
(@HOLIDAYID, @DATEID+2, 379944960), -- 2022-11-23.
(@HOLIDAYID, @DATEID+3, 396722176), -- 2023-11-23.
(@HOLIDAYID, @DATEID+4, 413483008), -- 2024-11-22.
(@HOLIDAYID, @DATEID+5, 430260224); -- 2025-11-22.


-- Children's Week. Holiday ID: 201.
UPDATE `game_event` SET `start_time`='2020-05-01 00:01:00', `occurence`='525600', `length`='10080', `holidayStage`='0' WHERE  `eventEntry`=10;
SET @HOLIDAYID := 201;
SET @DATEID := 16;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	339738624), -- 2020-05-01.
(@HOLIDAYID, @DATEID+1, 356515840), -- 2021-05-01.
(@HOLIDAYID, @DATEID+2, 373293056), -- 2022-05-01.
(@HOLIDAYID, @DATEID+3, 390070272), -- 2023-05-01.
(@HOLIDAYID, @DATEID+4, 406274048), -- 2024-04-30.
(@HOLIDAYID, @DATEID+5, 423051264); -- 2025-04-30.


-- Noblegarden. Holiday ID: 181.
UPDATE `game_event` SET `start_time`='2020-04-13 00:01:00', `occurence`='525600', `length`='10080', `holidayStage`='0' WHERE  `eventEntry`=9;
SET @HOLIDAYID := 181;
SET @DATEID := 13;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	338886656), -- 2020-04-13.
(@HOLIDAYID, @DATEID+1, 355663872), -- 2021-04-13.
(@HOLIDAYID, @DATEID+2, 372441088), -- 2022-04-13.
(@HOLIDAYID, @DATEID+3, 389218304), -- 2023-04-13.
(@HOLIDAYID, @DATEID+4, 405979136), -- 2024-04-12.
(@HOLIDAYID, @DATEID+5, 422756352); -- 2025-04-12.


-- Harvest Festival. Holiday ID: 321.
UPDATE `game_event` SET `start_time`='2020-09-29 00:01:00', `occurence`='525600', `length`='10080', `holidayStage`='0' WHERE  `eventEntry`=11;
SET @HOLIDAYID := 321;
SET @DATEID := 14;
DELETE FROM `holiday_dates` WHERE `id`=@HOLIDAYID AND `date_id` IN (@DATEID, @DATEID+1, @DATEID+2, @DATEID+3, @DATEID+4, @DATEID+5);
INSERT INTO `holiday_dates` (`id`, `date_id`, `date_value`) VALUES -- DONE.
(@HOLIDAYID, @DATEID, 	344391680), -- 2020-09-29.
(@HOLIDAYID, @DATEID+1, 361168896), -- 2021-09-29.
(@HOLIDAYID, @DATEID+2, 377946112), -- 2022-09-29.
(@HOLIDAYID, @DATEID+3, 394723328), -- 2023-09-29.
(@HOLIDAYID, @DATEID+4, 411484160), -- 2024-09-28.
(@HOLIDAYID, @DATEID+5, 428261376); -- 2025-09-28.
```

**Comment by Jinnaix** [comment]
inb4 @illfated appears and tells you that you should sql markdown ;D

Havent checked the events yet, Feast of Winter Veil, Hallow's End and the other events that you dont cover still work correctly?

**Comment by natnat201193** [comment]
meh, how do I do that? xD

**Comment by natnat201193** [comment]
nvm, done.

**Comment by Ovahlord** [comment]
How did you actually come up with these numbers? Did you just extract them from a newer client?

**Comment by illfated** [comment]
@Jinnaix : Thank you for the irony/slight sarcasm. 😄

**Comment by Keader** [comment]
@natnat201193 can you tell us how you calculated it?
we dont have any documentation about that.

**Comment by natnat201193** [comment]
@Keader   @Ovahlord  
I used the blizztime calculator found here https://model-changing.net/files/file/66-wow-blizztime-calculator/

Then once I added the values to the database, I used:
UPDATE `holiday_dates` SET `date_value` = `date_value` & ~0x3FFF; -- All holidays start at 00:00 in 3.3.5 + some unneeded bits
found in https://github.com/TrinityCore/TrinityCore/commit/951fa46fe9b14a9e275ac9306b2346959e40e3e5

I actually have no idea how the values are calculated from that Calculator, but the source code is included in the download if anyone wants to check it out.

**Comment by Keader** [comment]
cool, ty.

**Comment by natnat201193** [comment]
oh and when using the Calculator for these events, I only checked the Use Year box and kept Use Day of the Week unchecked.

**Comment by Killyana** [comment]
Some dates are still wrong, example:
Lunar Festival End: 2020/02/07  not 2020/02/13

![image](https://user-images.githubusercontent.com/6587064/72162733-c5988300-33c2-11ea-8b56-d70cf328290d.png)

**Comment by Killyana** [comment]
And  Pilgrim's Bounty has and extra wrong period in September

![image](https://user-images.githubusercontent.com/6587064/72163332-f3ca9280-33c3-11ea-916c-40ff5f63799f.png)

**Comment by natnat201193** [comment]
Read the original post...  
I explained that as far as I'm aware, we cannot currently change the end dates shown in the Calendar without clientside edits. @Killyana

**Comment by natnat201193** [comment]
if you look back in time on the Calendar, you will see older Entries also show 21 days. so unless someone can find a way to modify the end date shown on the calendar without clientside edits, we are kinda stuck on that part.

**Comment by natnat201193** [comment]
> The one event that lasts a bit longer due to this is Lunar festival, it shows 21 days on the Calendar which we cant change as far as I'm aware, so I just made it match.
> 
> Before anyone says 21 days is not blizzlike, I know it's not and we won't get blizzlike unless we update the dates to match the real-world events like blizzard does, this would need clientside edits.
> If you don't want it to be 21 days, you can always adjust the length, but it won't match the Calendar if you do.

**Comment by Ovahlord** [comment]
From what I've seen in the dbc files, the client actually has the correct duration in different columns. I did not check yet in how far packets can influence the cloumn selection but I might find a way.

**Comment by natnat201193** [comment]
yeah, if someone can find a way to do it, that would be fantastic.
Also, I think all events with a Holiday ID should not be in game_event, they should be in a new table specifically tailored to handling those events the way blizzard does. Not something I have the Knowledge to implement, otherwise I would.

**Comment by Killyana** [comment]
Data in the dbc is correct (504h = 21 days), the original duration in wotlk was 21 days and it was changed in later expansions:

2012 | January 23 | January 22 - February 11  (21 days)
-- | -- | --
2013 | February 10 | January 27 - February 9 (14 days)

**Comment by natnat201193** [comment]
yup

**Comment by natnat201193** [comment]
they actually change it based on the Chinese lunar new year.

It appears that Blizzard moves the dates of this event to conform to the real-life Chinese Lunar New Year on which this festival is based.[1]
Year | Lunar New Year date | Lunar Festival dates
-- | -- | --
2006 | January 29 | January 27 – February 14
2007 | February 18 | February 16 – March 8
2008 | February 7 | February 5 – 23
2009 | January 26 | January 24 – February 12
2010 | February 14 | February 14 – March 7
2011 | February 3 | January 23 – February 12
2012 | January 23 | January 22 - February 11
2013 | February 10 | January 27 - February 9
2014 | January 31 | January 20 - February 3
2015 | February 19 | February 16 - March 2
2016 | February 8 | February 1 - February 15
2017 | January 29 | January 21 - February 4
2018 | February 16 | February 17 - March 3
2019 | February 5 | January 28 - February 11

https://wow.gamepedia.com/Lunar_Festival

**Comment by Ovahlord** [comment]
Okay, so the first mistake that I have figure out right away is: events start at 1:00 AM, not 0:00. I have picked Pilgrimm's Bounty's very first event time and it's exactly:
161824832

> The date of the provided BlizzTime is: TimeZone: 0, Year: 2009, Month: 11, Day of Month: 22, Day of Week: 0, Hour: 1, Minutes: 0

So accordingly the times need to be corrected. I have checked all times up to 2013 and they always start at 1 AM

**Comment by natnat201193** [comment]
nice, I only set them all to 00:00 because of what was said in https://github.com/TrinityCore/TrinityCore/commit/951fa46fe9b14a9e275ac9306b2346959e40e3e5
```
UPDATE `holiday_dates` SET `date_value` = `date_value` & ~0x3FFF; -- All holidays start at 00:00 in 3.3.5 + some unneeded bits```

**Comment by WyrtWicce** [comment]
I'm a total noob here, been using the updated Jeutie's Repack for 3.3.5 (I guess now it's called the AC-Web Repack but that was the start). How do I use these updates, please? I see on HeidiSQL that I can copy-paste the code text up there to the bottom window in places, but I don't know which database to put the changes into and don't want to mess up my game. Is it world->holiday_dates? World->game_events? World->event_scripts? I don't know what to do. Thanks for any help.

**Comment by natnat201193** [comment]
> I'm a total noob here, been using the updated Jeutie's Repack for 3.3.5 (I guess now it's called the AC-Web Repack but that was the start). How do I use these updates, please? I see on HeidiSQL that I can copy-paste the code text up there to the bottom window in places, but I don't know which database to put the changes into and don't want to mess up my game. Is it world->holiday_dates? World->game_events? World->event_scripts? I don't know what to do. Thanks for any help.

Double click the world database, paste the SQL into the query box and Execute. The query selects the Holiday_dates table already if it exists. then restart the server.

**Comment by Ovahlord** [comment]
Here some data about what event is suposed to start when:
- Noblegarden: 0:00am, Sunday
- Children's Week: 0:00am, Sunday
- Harvest Festival: 0:00am, Monday
- Lunar Festival: 6:00am, Saturday
- Pilgrim's Bounty: 1:00am, Sunday
- Love is in the Aur: 0:00am, Sunday

**Comment by WyrtWicce** [comment]
> > I'm a total noob here, been using the updated Jeutie's Repack for 3.3.5 (I guess now it's called the AC-Web Repack but that was the start). How do I use these updates, please? I see on HeidiSQL that I can copy-paste the code text up there to the bottom window in places, but I don't know which database to put the changes into and don't want to mess up my game. Is it world->holiday_dates? World->game_events? World->event_scripts? I don't know what to do. Thanks for any help.
> 
> Double click the world database, paste the SQL into the query box and Execute. The query selects the Holiday_dates table already if it exists. then restart the server.

Hmm I must not have done something right. Followed those directions, then closed everything down and restarted, and none of the holidays are there still. I copy-pasted all of the updates up there to the query window like you said. I don't know how to save; thought it auto-saved changed like that.

**Comment by Ovahlord** [comment]
Okay good news, the duration of the events is in fact sent by the packet so it can be modified. Just need to think about a nice way to do this and it will be done.

**Comment by Ovahlord** [comment]
87c79c9485cbb9536912e1566174c717946c1537 there you go. You may now fully update holidays including their correct duration. Technically you could make them last the entire year now lol.

**Comment by natnat201193** [comment]
@Ovahlord guess clientside edits are not needed afterall, nice one <3

**Comment by natnat201193** [comment]
so, the only way I can update Lunar festival to start on a Saturday is by using the previous Saturday, if i try to use the following Saturday, it's going to overlap with Love is in the Air by a day.

**Comment by natnat201193** [comment]
or something to make these holidays use the dates in holiday_dates only instead of using occurrence and length from game_event

**Comment by natnat201193** [comment]
so I'm not quite sure what you want me to do, I think just using the current dates and times, for now, is fine.
Just updating the lunar festival duration in game_event and holiday dates should be ok unless a proper system to handle it how blizzard does is put in to place.

**Comment by natnat201193** [comment]
It's also a pain in the ass to update all of these all over again with my current method.
If someone can update the blizztime calculator to produce a fully accurate date code, that would help.

**Comment by Ovahlord** [comment]
I've written a small tool that lets you read and generate date times up to hours:
https://github.com/The-Cataclysm-Preservation-Project/Packet-BlizzTime-tool

**Comment by natnat201193** [comment]
nice, I'm not quite sure how to compile that seeing as there is no solution added though. the only thing I can really compile is hello world and TC/other wow cores,  cause guides :p
I'm not really a coder, can only do basic things here and there working with examples.

**Comment by pklloveyou** [comment]
```c++
INSERT INTO `holiday_dates` VALUES (181, 0, 220708864);
INSERT INTO `holiday_dates` VALUES (181, 1, 238354432);
INSERT INTO `holiday_dates` VALUES (181, 2, 254885888);
INSERT INTO `holiday_dates` VALUES (181, 3, 270974976);
INSERT INTO `holiday_dates` VALUES (181, 4, 288620544);
INSERT INTO `holiday_dates` VALUES (181, 5, 305152000);
INSERT INTO `holiday_dates` VALUES (181, 6, 322256896);
INSERT INTO `holiday_dates` VALUES (181, 7, 339034112);
INSERT INTO `holiday_dates` VALUES (181, 8, 355811328);
INSERT INTO `holiday_dates` VALUES (181, 9, 372588544);
INSERT INTO `holiday_dates` VALUES (181, 10, 389365760);
INSERT INTO `holiday_dates` VALUES (201, 0, 221708288);
INSERT INTO `holiday_dates` VALUES (201, 1, 238469120);
INSERT INTO `holiday_dates` VALUES (201, 2, 255229952);
INSERT INTO `holiday_dates` VALUES (201, 3, 272646144);
INSERT INTO `holiday_dates` VALUES (201, 4, 289406976);
INSERT INTO `holiday_dates` VALUES (201, 5, 305610752);
INSERT INTO `holiday_dates` VALUES (201, 6, 322371584);
INSERT INTO `holiday_dates` VALUES (201, 7, 339148800);
INSERT INTO `holiday_dates` VALUES (201, 8, 355926016);
INSERT INTO `holiday_dates` VALUES (201, 9, 372703232);
INSERT INTO `holiday_dates` VALUES (201, 10, 389480448);
INSERT INTO `holiday_dates` VALUES (321, 0, 210092032);
INSERT INTO `holiday_dates` VALUES (321, 1, 226689024);
INSERT INTO `holiday_dates` VALUES (321, 2, 243286016);
INSERT INTO `holiday_dates` VALUES (321, 3, 260374528);
INSERT INTO `holiday_dates` VALUES (321, 4, 276955136);
INSERT INTO `holiday_dates` VALUES (321, 5, 294060032);
INSERT INTO `holiday_dates` VALUES (321, 6, 310657024);
INSERT INTO `holiday_dates` VALUES (321, 7, 327434240);
INSERT INTO `holiday_dates` VALUES (321, 8, 344211456);
INSERT INTO `holiday_dates` VALUES (321, 9, 360988672);
INSERT INTO `holiday_dates` VALUES (321, 10, 377765888);
INSERT INTO `holiday_dates` VALUES (321, 11, 394543104);
INSERT INTO `holiday_dates` VALUES (327, 0, 218529792);
INSERT INTO `holiday_dates` VALUES (327, 1, 235192320);
INSERT INTO `holiday_dates` VALUES (327, 2, 252952576);
INSERT INTO `holiday_dates` VALUES (327, 3, 269484032);
INSERT INTO `holiday_dates` VALUES (327, 4, 285540352);
INSERT INTO `holiday_dates` VALUES (327, 5, 303169536);
INSERT INTO `holiday_dates` VALUES (327, 6, 319209472);
INSERT INTO `holiday_dates` VALUES (327, 7, 335806464);
INSERT INTO `holiday_dates` VALUES (327, 8, 353419264);
INSERT INTO `holiday_dates` VALUES (327, 9, 369491968);
INSERT INTO `holiday_dates` VALUES (327, 10, 386088960);
INSERT INTO `holiday_dates` VALUES (374, 0, 279986176);
INSERT INTO `holiday_dates` VALUES (374, 1, 287342592);
INSERT INTO `holiday_dates` VALUES (374, 2, 290471936);
INSERT INTO `holiday_dates` VALUES (374, 3, 293601280);
INSERT INTO `holiday_dates` VALUES (374, 4, 296747008);
INSERT INTO `holiday_dates` VALUES (374, 5, 304103424);
INSERT INTO `holiday_dates` VALUES (374, 6, 307232768);
INSERT INTO `holiday_dates` VALUES (374, 7, 309821440);
INSERT INTO `holiday_dates` VALUES (374, 8, 312950784);
INSERT INTO `holiday_dates` VALUES (374, 9, 320864256);
INSERT INTO `holiday_dates` VALUES (374, 10, 323452928);
INSERT INTO `holiday_dates` VALUES (374, 11, 326582272);
INSERT INTO `holiday_dates` VALUES (374, 12, 329711616);
INSERT INTO `holiday_dates` VALUES (374, 13, 337035264);
INSERT INTO `holiday_dates` VALUES (374, 14, 340197376);
INSERT INTO `holiday_dates` VALUES (374, 15, 343982080);
INSERT INTO `holiday_dates` VALUES (374, 16, 347127808);
INSERT INTO `holiday_dates` VALUES (374, 17, 353779712);
INSERT INTO `holiday_dates` VALUES (374, 18, 357613568);
INSERT INTO `holiday_dates` VALUES (374, 19, 360742912);
INSERT INTO `holiday_dates` VALUES (374, 20, 363888640);
INSERT INTO `holiday_dates` VALUES (374, 21, 371245056);
INSERT INTO `holiday_dates` VALUES (374, 22, 374374400);
INSERT INTO `holiday_dates` VALUES (374, 23, 377503744);
INSERT INTO `holiday_dates` VALUES (374, 24, 380649472);
INSERT INTO `holiday_dates` VALUES (374, 25, 388005888);
INSERT INTO `holiday_dates` VALUES (375, 0, 280444928);
INSERT INTO `holiday_dates` VALUES (375, 1, 287801344);
INSERT INTO `holiday_dates` VALUES (375, 2, 290930688);
INSERT INTO `holiday_dates` VALUES (375, 3, 294060032);
INSERT INTO `holiday_dates` VALUES (375, 4, 297205760);
INSERT INTO `holiday_dates` VALUES (375, 5, 304562176);
INSERT INTO `holiday_dates` VALUES (375, 6, 307691520);
INSERT INTO `holiday_dates` VALUES (375, 7, 310820864);
INSERT INTO `holiday_dates` VALUES (375, 8, 318816256);
INSERT INTO `holiday_dates` VALUES (375, 9, 321323008);
INSERT INTO `holiday_dates` VALUES (375, 10, 324452352);
INSERT INTO `holiday_dates` VALUES (375, 11, 328253440);
INSERT INTO `holiday_dates` VALUES (375, 12, 335577088);
INSERT INTO `holiday_dates` VALUES (375, 13, 338722816);
INSERT INTO `holiday_dates` VALUES (375, 14, 341868544);
INSERT INTO `holiday_dates` VALUES (375, 15, 344997888);
INSERT INTO `holiday_dates` VALUES (375, 16, 352321536);
INSERT INTO `holiday_dates` VALUES (375, 17, 355483648);
INSERT INTO `holiday_dates` VALUES (375, 18, 358629376);
INSERT INTO `holiday_dates` VALUES (375, 19, 361758720);
INSERT INTO `holiday_dates` VALUES (375, 20, 364347392);
INSERT INTO `holiday_dates` VALUES (375, 21, 372244480);
INSERT INTO `holiday_dates` VALUES (375, 22, 375390208);
INSERT INTO `holiday_dates` VALUES (375, 23, 377962496);
INSERT INTO `holiday_dates` VALUES (375, 24, 381108224);
INSERT INTO `holiday_dates` VALUES (375, 25, 388464640);
INSERT INTO `holiday_dates` VALUES (376, 0, 286294016);
INSERT INTO `holiday_dates` VALUES (376, 1, 288800768);
INSERT INTO `holiday_dates` VALUES (376, 2, 292601856);
INSERT INTO `holiday_dates` VALUES (376, 3, 295731200);
INSERT INTO `holiday_dates` VALUES (376, 4, 303054848);
INSERT INTO `holiday_dates` VALUES (376, 5, 306233344);
INSERT INTO `holiday_dates` VALUES (376, 6, 309362688);
INSERT INTO `holiday_dates` VALUES (376, 7, 312492032);
INSERT INTO `holiday_dates` VALUES (376, 8, 319815680);
INSERT INTO `holiday_dates` VALUES (376, 9, 322994176);
INSERT INTO `holiday_dates` VALUES (376, 10, 326123520);
INSERT INTO `holiday_dates` VALUES (376, 11, 329252864);
INSERT INTO `holiday_dates` VALUES (376, 12, 336035840);
INSERT INTO `holiday_dates` VALUES (376, 13, 339738624);
INSERT INTO `holiday_dates` VALUES (376, 14, 342327296);
INSERT INTO `holiday_dates` VALUES (376, 15, 345456640);
INSERT INTO `holiday_dates` VALUES (376, 16, 352780288);
INSERT INTO `holiday_dates` VALUES (376, 17, 355942400);
INSERT INTO `holiday_dates` VALUES (376, 18, 359088128);
INSERT INTO `holiday_dates` VALUES (376, 19, 362217472);
INSERT INTO `holiday_dates` VALUES (376, 20, 370196480);
INSERT INTO `holiday_dates` VALUES (376, 21, 372703232);
INSERT INTO `holiday_dates` VALUES (376, 22, 375848960);
INSERT INTO `holiday_dates` VALUES (376, 23, 379633664);
INSERT INTO `holiday_dates` VALUES (376, 24, 386957312);
INSERT INTO `holiday_dates` VALUES (376, 25, 389464064);
INSERT INTO `holiday_dates` VALUES (404, 0, 228982784);
INSERT INTO `holiday_dates` VALUES (404, 1, 245743616);
INSERT INTO `holiday_dates` VALUES (404, 2, 262504448);
INSERT INTO `holiday_dates` VALUES (404, 3, 279248896);
INSERT INTO `holiday_dates` VALUES (404, 4, 296009728);
INSERT INTO `holiday_dates` VALUES (404, 5, 312770560);
INSERT INTO `holiday_dates` VALUES (404, 6, 329646080);
INSERT INTO `holiday_dates` VALUES (404, 7, 346423296);
INSERT INTO `holiday_dates` VALUES (404, 8, 363200512);
INSERT INTO `holiday_dates` VALUES (404, 9, 379977728);
INSERT INTO `holiday_dates` VALUES (404, 10, 396754944);
INSERT INTO `holiday_dates` VALUES (423, 0, 219299840);
INSERT INTO `holiday_dates` VALUES (423, 1, 236077056);
INSERT INTO `holiday_dates` VALUES (423, 2, 252723200);
INSERT INTO `holiday_dates` VALUES (423, 3, 269713408);
INSERT INTO `holiday_dates` VALUES (423, 4, 286359552);
INSERT INTO `holiday_dates` VALUES (423, 5, 303169536);
INSERT INTO `holiday_dates` VALUES (423, 6, 319881216);
INSERT INTO `holiday_dates` VALUES (423, 7, 336658432);
INSERT INTO `holiday_dates` VALUES (423, 8, 353435648);
INSERT INTO `holiday_dates` VALUES (423, 9, 370212864);
INSERT INTO `holiday_dates` VALUES (423, 10, 386990080);
```

**Comment by natnat201193** [comment]
Sorry @Killyana didn't really think about it at the time, but with the current Lunar festival length, its going to overlap with Love is in the air and cause issues with spawns, included SQL below to correct it.

```
UPDATE `game_event` SET `length`='20160' WHERE  `eventEntry`=7;
UPDATE `holiday_dates` SET `holiday_duration`='336' WHERE  `id`=327;
```

**Comment by illfated** [comment]
Do you mean
```sql
UPDATE `game_event` SET `length` = 20160 WHERE `eventEntry` = 7;
UPDATE `holiday_dates` SET `holiday_duration`=336 WHERE `id`=327;
```
... or are `length` and `holiday_duration` purely text content?

**Comment by Killyana** [comment]
Updated here https://github.com/TrinityCore/TrinityCore/commit/f41dfa0089a7ba8719f28816ae75ba91313df5c4, thanks

**Comment by natnat201193** [comment]
@illfated I did ``` how do I do the SQL one xD

**Comment by Kitzunu** [comment]
@natnat201193 You do 
> \```sql
UPDATE `game_event` SET `length` = 20160 WHERE `eventEntry` = 7;
UPDATE `holiday_dates` SET `holiday_duration`=336 WHERE `id`=327;
\```

**Comment by natnat201193** [comment]
ty and that's cause I just adjusted the values and copied the SQL that was produced by Heidi SQL, didn't write it out myself as I did with the others.

**Comment by WyrtWicce** [comment]
Greetings. Just noticed: Midsummer this year is on the calendar, but it isn't getting triggered anywhere. No one in the world is celebrating!
