### ISSUE TITLE
Core/Movement: Creature position is not updated properly in the client after a death grip

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24047]
**Description:** If you grip and kill a creature just after the grip, this will happen:
https://imgur.com/a/zwaojza

If you get the coords of the creature and .go xyz you will be teleport to a different position.

![image](https://user-images.githubusercontent.com/6587064/72172501-950e1480-33d5-11ea-830b-ca51059aa327.png)

**Steps to reproduce the problem:**
Use a DK level 80 that could one shot the npc SpawnID: 128766

1. .go xyz 2081.4143, -5726.6245, 101.380615 609
2. set the auto attack in the creature in front of you
3. use death grip
4. .gps the creature to notice a desynchronization between the client and server position

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d5926a935727

**Comment by Killyana** [comment]
The jump speed calculation was changed here: https://github.com/TrinityCore/TrinityCore/commit/0197a2f990aa7c7eaf8637a2a5da7f43def9c4bd

**Comment by jackpoz** [comment]
could you try reverting https://github.com/TrinityCore/TrinityCore/commit/e698c17a2688385e62744cdf5eb37b12b9e304fa changes ?

**Comment by Killyana** [comment]
Not related, the issue still happen

**Comment by kvipka** [comment]
Try to test it with PR antihacks

**Comment by jackpoz** [comment]
Try after https://github.com/TrinityCore/TrinityCore/commit/d293dd37822d93f9023d3ff9d39052ed976e236b

**Comment by Killyana** [comment]
still happen after https://github.com/TrinityCore/TrinityCore/commit/d293dd37822d93f9023d3ff9d39052ed976e236b

**Comment by Killyana** [comment]
Cannot reproduce in rev. ffede34ba9a3
