### ISSUE TITLE
Going too small in size will make character levitating

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#24040]
**Description:**
When a character goes too small in size, it becomes levitating

Here is the video demonstrating how to reproduce and what is happening exactly
https://mega.nz/#!CxlG3QyY!h-Sx_K-LXelp6Z5DR9TZRwfwLXZUSNBNMtukmvfFo0Q

When character becomes too small, the character is actually looks "up side down", I think it is something became a negative number when calculating the position or whatever.

**Expected behaviour:**
Character does not go too small or levitate

**Steps to reproduce the problem:**
1. Add item 43480 (Small Feast) and eat it
2. Add item 8529 (Noggenfogger Elixir) and drink it until you become smaller
3. Add item 44228 (Baby Spice) and throw it on yourself
4. At this point you are now underground (character looks up side down)
5. Summon a mount, it may dismount itself or you will be on mount still, hit space bar to jump and you are levitating

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
commit 465db82cd96a05ca3b2a1b5ecf59e4287968e3fe

**Operating system:**
Debian 10.2.0

**Comment by Shauren** [comment]
Negative scale. Additive aura stacking.

**Comment by jackpoz** [comment]
are % mods supposed to be added instead of being multiplied ?

**Comment by Rushor** [comment]
can we add an exception for scaling there that it can never reach a negative value?

**Comment by Rushor** [comment]
so i revered it for the scaling system to the old state

works fine for me - you no longer get negative size

```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index f8773b7c7f..924c6beae4 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -2123,7 +2123,9 @@ void AuraEffect::HandleAuraModScale(AuraApplication const* aurApp, uint8 mode, b
     Unit* target = aurApp->GetTarget();
 
     float scale = target->GetObjectScale();
-    scale += CalculatePct(1.0f, apply ? GetAmount() : -GetAmount());
+    if (scale == -100.0f)     // prevent size to become zero
+        scale = -99.99f;
+    scale *= (apply ? (100.0f + float(GetAmount())) / 100.0f : 100.0f / (100.0f + float(GetAmount())));
     target->SetObjectScale(scale);
 }
 ```

**Comment by Rushor** [comment]
This is the old funection for it:

```
inline void ApplyPercentModFloatVar(float& var, float val, bool apply)
{
    if (val == -100.0f)     // prevent set var to zero
        val = -99.99f;
    var *= (apply ? (100.0f + val) / 100.0f : 100.0f / (100.0f + val));
}
```

**Comment by jackpoz** [comment]
what about just leaving the old code and applying a std::max(0.1f, scale); with 0.1f being whatever minimum scale allowed ?

**Comment by Rushor** [comment]
that sounds better!

**Comment by jackpoz** [comment]
any idea about what smallest scale to allow ?

**Comment by Killyana** [comment]
With the command .mod scale you cannot use a value lower than 0.1 so it's probably the limit

**Comment by Shauren** [comment]
Make it 0.01, there are auras that have value -99 (since basepoints are int, theres nothing between -100 and -99)

There are also some stupid valued auras with ridiculous value too... 42969

**Comment by Rushor** [comment]
sooo

```diff
diff --git a/src/server/game/Spells/Auras/SpellAuraEffects.cpp b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
index 1bf436b3a4..1d931d5e39 100644
--- a/src/server/game/Spells/Auras/SpellAuraEffects.cpp
+++ b/src/server/game/Spells/Auras/SpellAuraEffects.cpp
@@ -2127,7 +2127,7 @@ void AuraEffect::HandleAuraModScale(AuraApplication const* aurApp, uint8 mode, b
 
     float scale = target->GetObjectScale();
     scale += CalculatePct(1.0f, apply ? GetAmount() : -GetAmount());
-    target->SetObjectScale(scale);
+    target->SetObjectScale(std::max(0.01f, scale));
 }
 
 void AuraEffect::HandleAuraCloneCaster(AuraApplication const* aurApp, uint8 mode, bool apply) cons```

but i would also suggest 0.1 since 0.01 will make player invisible again :/

**Comment by Shauren** [comment]
The entire point of the aura I gave as example is to make a creature invisible...

**Comment by jackpoz** [comment]
@Rushor could you please PR that ?

**Comment by Rushor** [comment]
But Well then people will still be invisible by applying multiple size auras. Sooo it was intended to be invisible with multiple size auras on retail?

**Comment by Jildor** [comment]
Maybe shouldn't stack those auras and only get the higher effect

**Comment by Killyana** [comment]
No they stack, but it could be the limit for npcs and players is not the same

**Comment by Rushor** [comment]
okay so f.ex: ID - 42969 Explosion Fade Away should only target npcs? we can add a check for player and creature here

**Comment by Killyana** [comment]
It looks like the spell 42969 go beyond the minimum value, if you .cast 42969  you will shrink then grow back flipped https://imgur.com/a/VAcqtqO

**Comment by Rushor** [comment]
Maybe that is intended. Should that spell only target creatures?

**Comment by Killyana** [comment]
Spell=42969 : Explosion Fade Away : Turns the caster invisible and increases its movement speed by 0% for until cancelled.
It not used by any script, and found in sniffs, but probably used by an npc trigger.

**Comment by Rushor** [comment]
okay updated https://github.com/TrinityCore/TrinityCore/issues/24040#issuecomment-600257440

**Comment by jjo72ddd** [comment]
Still relevant for 7c91c42. Maybe use a @Rushor script? It works quite efficiently.

**Comment by Faq** [comment]
@Rushor, can you open PR?

**Comment by Shauren** [comment]
No, his patch is bad because it breaks unapply case
