### ISSUE TITLE
[3.3.5] DB/World events 2020

### ISSUE THREAD

**Issue by Miorey** [TrinityCore/TrinityCore#24044]
**Description:** World events are missing in DB for 2020 and after

**Current behaviour:** Some of the world events ares missing like "Love is in the Air" for the current year. 

**Expected behaviour:** Adding all the world events for this year and after. The list of the expected date is here https://www.wowhead.com/events

**Branch(es):** 3.3.5

**Comment by natnat201193** [comment]
@Miorey 

https://github.com/TrinityCore/TrinityCore/issues/24045

**Comment by Aokromes** [comment]
yeah i know this is older, but fix poster was to lazy to post here.

**Comment by natnat201193** [comment]
@Aokromes not lazy. seen as it is a fix post, I assumed it should go in its own issue, not in a comment.

**Comment by illfated** [comment]
@natnat201193 : You are definitely allowed to post suggested SQL solutions in any issue ticket, as long as the solution is relevant to the issue. It is almost 50% of the reason for why the issue ticket was created in the first place.

**Comment by natnat201193** [comment]
@illfated better response than just being called lazy, ty.

**Comment by Miorey** [comment]
@natnat201193 Thanks
