### ISSUE TITLE
Core/Spell: Support for multiple channeled spells

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24043]
**Description:** A creature must be able to channel more than on spell without interrupting the first one.

Example: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_zuldrak.cpp#L77-L78

DoCast(rageclaw, SPELL_LEFT_CHAIN, true);
DoCast(rageclaw, SPELL_RIGHT_CHAIN, true);

IG you will see only SPELL_RIGHT_CHAIN channeling, SPELL_LEFT_CHAIN was interrupted  by SPELL_RIGHT_CHAIN

You can try .cast self 59951 or 59952 to notice the interruption

1. .go c id 29700
2. notice only on chain, and list aura shows only SPELL_RIGHT_CHAIN
3. Select Drakuru Shackles and .cast slelf 59951 
4. Notice the right chain get interrupted

**Branch(es):** both

**TC rev. hash/commit:** rev. 465db82cd96arev. 465db82cd96a

**Comment by jackpoz** [comment]
Maybe there is a flag to know which spells can continue being channelled ?

**Comment by Killyana** [comment]
The case above in no longer valid as it was using wrong spells: https://github.com/TrinityCore/TrinityCore/commit/a149261e94b676cf090b37d085578e08d0ebffd0
Ovahlord maybe have a case from a cata boss, will wait and see.

**Comment by Aokromes** [comment]
no answer after more than a year, closing. if this issue is still valid open a NEW ticket with UPDATED core

**Comment by CraftedRO** [comment]
12a3316326cf0ccf19021a5cb675943562ed9aac right hand chain is still intrerupted if we .cast self 59951 on Captured Rageclaw, not sure if this can count as still valid.
