### ISSUE TITLE
Help base

### ISSUE THREAD

**Issue by Buizelgame** [TrinityCore/TrinityCore#24050]
Hello everyone, I recently decided to download the 335 source code and compile the assembly
Everything went without errors) everything is fine
Essence of the question;
Compiled the assembly, assembled it, created the database, turned on worldserwer so that they would be flooded, as a result, the bases were flooded, the server starts and starts and reaches a certain line.
Loading Player Create Level HP / Mana Data ..

I apologize if I write the wrong way ..

https://www.youtube.com/watch?v=ZRZRnznigsI&feature=emb_logo

**Comment by Buizelgame** [comment]
Dberor https://pastebin.com/SY6upFtV
https://pastebin.com/rb2Nr8Mv

**Comment by Aokromes** [comment]
idk what core are you using, but clean 3.3.5a core doesn't have such startup errors.

**Comment by Buizelgame** [comment]
Pure sources 3.3.5

**Comment by Buizelgame** [comment]
I can make a video how I compile and download sources

**Comment by Aokromes** [comment]
https://i.imgur.com/5QldCcD.png custom unsupported core.

**Comment by Buizelgame** [comment]
Give a link where to download source codes 3.3.5 please

**Comment by Buizelgame** [comment]
https://github.com/TrinityCore/TrinityCore/tree/3.3.5 
Download from here?

**Comment by MaxtorCoder** [comment]
You are literally on the TC github, compile it and done.

**Comment by Buizelgame** [comment]
So I do not understand from Kudawa download normal clean sources?

**Comment by illfated** [comment]
Core source, without revision hash: https://github.com/TrinityCore/TrinityCore/archive/3.3.5.zip4
TDB: https://github.com/TrinityCore/TrinityCore/releases/download/TDB335.19121/TDB_full_world_335.19121_2019_12_15.7z 

Should not be hard to find the source files.
