### ISSUE TITLE
DB/Gossip: Elder Runetotem & Elder Darkhorn inactive gossip options

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#24056]
**Description:**

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15572/elder-runetotem
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15579/elder-darkhorn

![Elder_Runetotem_gossip_011220_001136](https://user-images.githubusercontent.com/38162891/72224420-bfe59d80-357a-11ea-84f2-45330bd8c057.jpg) ![Elder_Darkhorn_gossip_011220_001515](https://user-images.githubusercontent.com/38162891/72224422-c6741500-357a-11ea-9979-e68c8286f737.jpg)

![image](https://user-images.githubusercontent.com/38162891/72224463-2f5b8d00-357b-11ea-9676-72afaa5d1d98.png)

**Current behaviour:**

Currently, the gossip options for these 2 NPCs are unresponsive, the do not open any new gossip page at all.
The gossip options also do not update as they should by being removed when you have visited those Elders named in the gossip option label text.
If you check the other Elders who are referencing in the gossip options those you now have visited, you will see that those gossip options get removed from the list as soon as you have completed the Elder quest and received the Coin of Ancestry from that referenced Elder.

**Expected behaviour:**

The gossip options belonging to the NPCs 15572 (Elder Runetotem)  & 15579 (Elder Darkhorn) should open and show a gossip page describing where those NPCs are supposed to be.

**Steps to reproduce the problem:**

1. `.go creature id 15572` and/or `.go creature id 15579`
2. Step out of the NPC, right-click the NPC to open its gossip.
3. Notice that none of those gossip options are dead (not responding).
4. As soon as you have visited one or more of the NPCs mentioned in those gossip options, notice that none of the options are updated by being removed.

**Branch(es):**

3.3.5, maybe both (I have only tested on 3.3.5)

**TC rev. hash/commit:** 

TrinityCore rev. a149261e94b6 2020-01-09 23:10:46 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.1c  28 May 2019)
Using Boost version: 1.67.0
Using MySQL version: 8.0.18
Using CMake version: 3.13.4
Compiled on: Linux 5.3.0-1009-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997886944 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.19121

**Operating system:** Unix (https://tcubuntu.northeurope.cloudapp.azure.com/)

(I would have liked to suggest a DB update to fix these gossip options, but I haven't had time to rebuild my local core + DB setup, so I find it a bit difficult to research the DB contents of those gossips.)

**Comment by offl** [comment]
```sql
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21097 WHERE `MenuID` = 6815 AND `OptionID` =  1;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21107 WHERE `MenuID` = 6815 AND `OptionID` =  2;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21147 WHERE `MenuID` = 6815 AND `OptionID` =  3;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21086 WHERE `MenuID` = 6899 AND `OptionID` =  0;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21100 WHERE `MenuID` = 6899 AND `OptionID` =  1;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21122 WHERE `MenuID` = 6899 AND `OptionID` =  3;
UPDATE `gossip_menu_option` SET `ActionMenuID` = 21147 WHERE `MenuID` = 6899 AND `OptionID` =  4;

**Comment by Killyana** [comment]
BTW we need some on to sniff all this gossips a they are custom.
