### ISSUE TITLE
3.3.5 [Hunter] Pet enter evade if mmaps active and under Cower

### ISSUE THREAD

**Issue by junker1609** [TrinityCore/TrinityCore#24069]
Hello,

**Description:**

The hunter's pet, sometimes avoids damage and all heal in dungeons and raids, and can tank without actually suffering damage

**Current behaviour:**

The pet looks like it is not counted by other players / creature

**Expected behaviour:**

Receive heal and suffer damage.

**Steps to reproduce the problem:**
1-Create a hunter
2-go to dungeon with a heal, tank 
3-send the pet

**Branch(es):**
3.3.5 branch

**TC rev. hash/commit:**  rev. f082218c973b 2020-01-13 Unix Static

**Operating system:** 
Ubuntu 18-64bit

**Comment by Jinnaix** [comment]
> TC rev. hash/commit:
> f082218c973b 2020-01-13 Unix Static

Unknown hash - Custom core?

**Comment by illfated** [comment]
Most likely. If you look at the [3.3.5 commit list](https://github.com/TrinityCore/TrinityCore/commits/3.3.5), there are:
- Commits on Jan 14, 2020
- Commits on Jan 12, 2020

... but no commits made on 2020-01-13. Heh, if I had noticed anything like this while playing on https://tcubuntu.northeurope.cloudapp.azure.com/ , I would have finished all the classic & TBC dungeons on my current test character, then reported the issue here. I have been looking for a way to cheat with an uber pet tank, just to compensate for playing without any other players and run through as much content as possible in my spare time. 🐈 🏹 🕺 💃 🐕 🔫

**Comment by junker1609** [comment]
> > TC rev. hash/commit:
> > f082218c973b 2020-01-13 Unix Static
> 
> Unknown hash - Custom core?

I don't know, i just added transmogrification and git pull updates 

Core Version :
TrinityCore rev. f082218c973b 2020-01-13 10:40:43 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) 

Core Revision :
f082218c973b

 db_version : 
TDB 335.19121
@illfated I don't know, at worst I invite you to test with us =)

**Comment by Killyana** [comment]
Could provide the position where this happen (.gps) ? or a screen/video

**Comment by junker1609** [comment]
> Could provide the position where this happen (.gps) ? or a screen/video

I'll rush tomorrow and try to make a video.
Thank you.

**Comment by illfated** [comment]
> I don't know, i just added transmogrification and git pull updates
> 
> Core Version :
> TrinityCore rev. f082218c973b 2020-01-13 10:40:43 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

if nothing else, in theory there is a chance that the transmogrification code and updates could have messed with some of the spell source code to make a deviation in spell handling.

**Comment by jackpoz** [comment]
@junker1609 try with a clean 3.3.5

**Comment by jackpoz** [comment]
@illfated my favourite one is https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30839 :)

**Comment by illfated** [comment]
> @illfated my favourite one is https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30839 :)

😃 Oh yeah, right. I remember you mentioned that one earlier and I have tried it before. Very useful. Thanks. 👍

**Comment by junker1609** [comment]
Hello, 
There's screenshot, and i'll upload video in a few minutes, 
I also noticed that it makes bosses, trash or any other creature regen when they change targets while in combat
Screen : https://ibb.co/VTSvRJg

**Comment by Killyana** [comment]
Any idea since when it starts to happen?

**Comment by junker1609** [comment]
On the video you can see, when we start the fight, the pet manages to avoid all attacks and even heal sometimes
I'll try with the update, 
I will keep you informed @Killyana

**Comment by jackpoz** [comment]
Was that from a clean 335 ? Maybe try to reproduce it on the test realm at https://tcubuntu.northeurope.cloudapp.azure.com/

**Comment by junker1609** [comment]
> Was that from a clean 335 ? Maybe try to reproduce it on the test realm at https://tcubuntu.northeurope.cloudapp.azure.com/

Hello,
I create account but i have this error "unable to validate game version wow.."
Client version 3.3.5 12340 June 24, 2010

**Comment by Killyana** [comment]
The issue was also reported by Aokromes, so confirmed

**Comment by junker1609** [comment]
We will do our best to fix it all together.

**Comment by Killyana** [comment]
Please test after https://github.com/TrinityCore/TrinityCore/commit/9f8477cd112bf0f52e23afc9cdee4adfcf540de5

**Comment by Aokromes** [comment]
at least evade issues got fixed acording who told me.

**Comment by Killyana** [comment]
This issue could be reproduced with Dummy, just activate cower (auto) https://woehead.way-of-elendil.fr/?spell=1742 and send your pet hit the dummy you will get evades from the pet and some logs:
Diablosaure DAMAGE_SHIELD_MISSED_EVADE Assoiffé de sang Diablosaure. 
Diablosaure DAMAGE_SHIELD_MISSED_EVADE Force monstrueuse Diablosaure. 

![image](https://user-images.githubusercontent.com/6587064/72744711-66025a80-3bae-11ea-8c07-8d00974e952d.png)

**Comment by illfated** [comment]
Interesting combination, `mmaps = 1` and Cower = auto. I will log into tcubuntu.northeurope.cloudapp.azure.com and test my pets there to see what the current status is.

**Comment by jackpoz** [comment]
please try after https://github.com/TrinityCore/TrinityCore/commit/d293dd37822d93f9023d3ff9d39052ed976e236b

**Comment by jackpoz** [comment]
btw @junker1609 you could push your fork with your changes (transmog patch) to GitHub so we know which commit and which custom changes you are using, win-win for both :)

**Comment by junker1609** [comment]
It seems to me that it is resolved for the moment for me.
If someone can also confirm.
@jackpoz  I will upload it during the week
