### ISSUE TITLE
When a creature charmed by a player kills another creature, the killed creature cannot be looted.

### ISSUE THREAD

**Issue by natnat201193** [TrinityCore/TrinityCore#24060]
Current behaviour:
Charming a creature and killing another creature with it will remove the dyno lootable flag without checking if the charmer has met the damage requirement to receive loot.

Expected behaviour:
Charmed unit should check if the charming player has met the damage requirement before disabling the lootable flag.
However, I'm not sure if this is correct for all cases.

How to reproduce:
1. Go to Naxxramas 10 man Razuvious.
2. Damage Razuvious to low health.
3. Charm an understudy using the crystal and kill Razuvious with it.
4. No lootable flag.

Branch: 3.3.5, not sure about master.
TrinityCore rev. f1c338f1371e 2020-01-12 22:39:09 +0100 (3.3.5 branch)

Notes:
The issue for this case lies here:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CoreAI/PassiveAI.cpp#L75

```
void PossessedAI::KilledUnit(Unit* victim)
{
    // We killed a creature, disable victim's loot
    if (victim->GetTypeId() == TYPEID_UNIT)
        victim->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
}
```

This check does not check for charmer damage requirements and this check should also probably be done by the killed unit, not the killer.

**Comment by jackpoz** [comment]
@natnat201193 did you continue investigating the issue after you reported it ?

**Comment by illfated** [comment]
on one hand, I would think that some loot issues have been improved during the last 6 months, but on the other hand, the quoted code section have not changed for a very long time:
https://github.com/TrinityCore/TrinityCore/blob/dd28cecda36ed3912be39d0c3caefef910db707d/src/server/game/AI/CoreAI/PassiveAI.cpp#L70-L81

**Comment by jackpoz** [comment]
I created a PR https://github.com/TrinityCore/TrinityCore/pull/25229

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/298d7994850dfc777c56a7672042d78074b67f3d
