### ISSUE TITLE
SAI: OVERRIDE_LIGHT and OVERRIDE_WEATHER actions

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24072]
**Description:** We need 2 new actions, one that allow to change light and an other to change the weather.

For OVERRIDE_LIGHT:  packet field names are AreaLightID, OverrideLightID, TransitionMilliseconds

For OVERRIDE_WEATHER: packet field names are State, Grade, Unk Byte

https://github.com/TrinityCore/TrinityCore/commit/529cabea68ab90e34ccafa276fc40a8f2723902b#diff-9eea3ad0b189ac095427d3c6c6ff68e7R3490-R3536

Example of quest:
OVERRIDE_LIGHT: https://www.youtube.com/watch?v=KHcr8MjbrfU
OVERRIDE_WEATHER: https://www.youtube.com/watch?v=vG8fb_qMzho

**Branch(es):** Both

**Comment by Shauren** [comment]
For implementer: don't just make this action send packet and call it a day, go through Map::SetZoneOverrideLight (that dalaran quest sets it for everyone, including players that log in while that event is in progress)

**Comment by ForesterDev** [comment]
Which values should be sent in packet for dalaran quest? 

AreaLightID
OverrideLightID
TransitionMilliseconds

**Comment by Shauren** [comment]
Why didn't you look at what parameters does `Map::SetZoneOverrideLight` expect? its OverrideLightID and TransitionMilliseconds (and zoneid)
