### ISSUE TITLE
[3.3.5] Spells/Priest: Mind Sear should do damage.

### ISSUE THREAD

**Issue by Eureka26** [TrinityCore/TrinityCore#24071]
Description: 
when using Mind sear Around enemies it doesnt do damage. 

Current behaviour: 
Mind Sear don't work properly it doesnt do damage to creatures or players.
(i saw that if i use mind sear on a player, with creatures around them it deal the damage to the creatures as intended. but not vice versa.)

Expected behaviour:
Mind Sear Should do damage to all enemies within 10 yards around the target.

Steps to reproduce the problem:
With Mind Sear Attack, an creature, or player with enemies around them

Branch(es): 
3.3.5

TC rev. hash/commit:
commit 89421422

Operating system:
Windows

**Comment by Aokromes** [comment]
idk if it may be fixed on head.

**Comment by Killyana** [comment]
Yes works fine.

**Comment by Eureka26** [comment]
i'm sorry but i don't understand, this work fine?
then why  doesnt work, on mine, i dont have anything special, i have the Source Up-dated, i also replaced dbc/map/ and so on to see if that was the problem, i'm still having the same issue. btw i'm using an clean source/core..

**Comment by Aokromes** [comment]
you have updated to 67d9d04?

**Comment by illfated** [comment]
@Eureka26 : Providing your current core revision hash (verbatim) info is very helpful for us others to know what to suggest to help you solve your issues.
