### ISSUE TITLE
mapextractor error: Error opening casc storage '/WoWclient/Data': FILE_NOT_FOUND

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24070]
#### Branch
master

####  /WoWclient 
total 8
drwxrwxrwx 5 root root   44 Jan 16 13:13 Data
-rwxrwxrwx 1 root root    4 Jan 16 13:14 Launcher.db
drwxrwxrwx 7 root root 4096 Jan 16 13:14 _retail_

#### Execute the mapextractor
/PROJECT_HOME/build/dist/wow-release-server/bin/mapextractor
Error opening casc storage '/WoWclient/Data': FILE_NOT_FOUND

**Comment by Aokromes** [comment]
unsuported wow version.

**Comment by wplatform** [comment]
@Aokromes  The Chinese client version is 8.2.5.32978, Can you tell me which client that supported.

**Comment by MaxtorCoder** [comment]
You are probably just doing it wrong. Use `-h` on the extractors to get a help text. 

Iirc `-i` was path to Wow. And that means the World of Warcraft folder. Not the \_retail\_ folder.

**Comment by wplatform** [comment]
Hi @MaxtorCoder,

I run it with docker container. and my client folder copy from Window and it contains files as following. some files are deleted since I think the program just read the data from folder 'Data' folder. /PROJECT_HOME/build/dist/wow-release-server/bin/mapextractor -f 0 -i "/WoWclient/"                          
 
drwxrwxrwx 5 root root   44 Jan 16 13:13 Data
-rwxrwxrwx 1 root root    4 Jan 16 13:14 Launcher.db
drwxrwxrwx 7 root root 4096 Jan 16 13:14 _retail_

I appreciate you to provide some comments to fix this issue.

**Comment by Shauren** [comment]
inb4 he deleted .build.info
