### ISSUE TITLE
Ulduar: Stormcaller Brundir evade

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24077]
**Current behaviour:**
Stormcaller Brundir runs in to the wall and evades non stop , impossible to complete an encounter without at least 5-6 resets / Runemaster Molgeim rune of power instantly disappeares 

**Expected behaviour:**
Stormcaller should not run into the wall / Runemaster Molgeim should spawn the rune of power stays around for 1 minute

https://github.com/TrinityCore/TrinityCore/commit/876a8487301088fec1580e7c9ef6bf98783d9d7d
Commit stating a fix, no longer works and should be re-opened

**Branch(es):**
3.3.5
https://github.com/TrinityCore/TrinityCore/commit/c1df161e1ddf95584030480d3dcb15149aacd7a6

**Operating system:** CHANGEME OS
Windows x64 | 2012 Server Edition

**Comment by Killyana** [comment]
Cannot reproduce the evade, but Stormcaller Brundir has some movements issues, not sure if he mut chase players.

**Comment by illfated** [comment]
Maybe the evade problem can be related to the movement issues. My hunter pet has triggered a lot of "Evade" combat messages lately in normal NPC fights while questing on https://tcubuntu.northeurope.cloudapp.azure.com/ .

**Comment by Killyana** [comment]
Yes the evade issue is fixed.

**Comment by xParad0x** [comment]
Its nothing but.
He runs in to the wall randomly. Sometimes its fine and sometimes he runs in to a wall and evades and runemaster disappeares

**Comment by illfated** [comment]
Which commit did you test and find this behaviour on? (Haven't had time to test myself yet.)

**Comment by xParad0x** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f41dfa0089a7ba8719f28816ae75ba91313df5c4

**Comment by illfated** [comment]
Thanks for the feedback, seems impractical for me to test this on my own then. At least you are testing with the movement revert commit included.
