### ISSUE TITLE
Ulduar: Xt-002 Deconstructor

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24076]
**Current behaviour:**
Ulduar: Xt-002 Deconstructor seems to have serious issues.  When he exposes his heart, he starts moving and when switching tanks/agro he instantly resets.

**Expected behaviour:**
The boss should not move at all if the heart is exposed, otherwise the encounter cannot progress or be completed.

**Steps to reproduce the problem:**

1. Go to Ulduar
2. Engage Xt-002, trigger Expose Heart
3. Watch how he starts moving around

**Branch(es):**
3.3.5a
c1df161e1ddf95584030480d3dcb15149aacd7a6

**Operating system:** CHANGEME OS
Windows x64 | 2012 Server Edition

**Comment by Keader** [comment]
omg, they break my baby :/

**Comment by Keader** [comment]
yeah, confirmed in sniffs, has not roots or something.
Need check why move chase is not cancelled or if something is adding it again

**Comment by Rushor** [comment]
this works fine for me 

https://github.com/Rushor/TrinityCore/commit/ad2b400f6e4554cb4920531414332e81db3a178c

**Comment by Rushor** [comment]
me->StopMoving();
me->GetMotionMaster()->MoveIdle();

should handle it i guess

**Comment by Jildor** [comment]
fixed with: https://github.com/TrinityCore/TrinityCore/commit/472e1fd8aeea80c6b32253007a204e645f89dc2e
