### ISSUE TITLE
Ulduar: Kologarn Arm | Stone Shout

### ISSUE THREAD

**Issue by xParad0x** [TrinityCore/TrinityCore#24078]
**Current behaviour:**
Kologran's Arm instantly re-spawns after killing an arm and then the Stone Shout deals 400 dmg per 0.5 seconds, creating massive dmg per second ticks. 

**Expected behaviour:**
Kologarn's Arm should be dead for at least 60 seconds if one get killed and the stone shout spell should not deal massive per second ticks, almost impossible to complete the encounter.

**Branch(es):**
3.3.5
https://github.com/TrinityCore/TrinityCore/commit/c1df161e1ddf95584030480d3dcb15149aacd7a6

**Operating system:** CHANGEME OS
Windows x64 | 2012 Server Edition

**Comment by Killyana** [comment]
Cannot reproduce in rev. 58313962994e

**Comment by D-CellX** [comment]
I am on same revision as you @Killyana and Stone Shout deals massive damage and Arms instantly respawm

**Comment by Killyana** [comment]
I don't know what's Stone Shout, use wowhead to link spells and entities

**Comment by D-CellX** [comment]
https://www.wowhead.com/spell=63716/stone-shout

``` SPELL_STONE_SHOUT                   = 63716,```

**Comment by Killyana** [comment]
Values are correct:
![image](https://user-images.githubusercontent.com/6587064/72668384-61ab3580-3a26-11ea-9015-13c1f80a41f5.png)

**Comment by xParad0x** [comment]
We will see this as another issue again. The arm chooses to instantly respawn sometimes and we tested this 11 times 5 out of which the arm insta respawns.
