### ISSUE TITLE
DB/Creature: Unworty Initiate

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#24089]
**Description:**

Currently these creatures are missing their visuals (chains connected to walls). Corrected behaviour can be seen here https://www.wowhead.com/npc=29519/unworthy-initiate#screenshots.

**Steps to reproduce the problem:**

1. Creae DK
2. `.gm on`
3. `.go c id 29519`

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. a249044700f0 2020-01-19 22:30:19 +0100 (3.3.5 branch) (Unix, Debug, Static)

**Comment by Kitzunu** [comment]
I think it is this spell if I am not wrong https://www.wowhead.com/spell=54613/chained-peasant-breath

**Comment by Sorikoff** [comment]
`29521` must cast `54612` to initiates. This doesn't work on my core.

**Comment by illfated** [comment]
Hmm, so maybe the spell part of the script does not run or is skipped?
https://github.com/TrinityCore/TrinityCore/blob/13c81f55e3314fede78acfbb72a47384961d1f25/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L42-L351
Would it be possible to convert those scripts to SAI, or is there something that needs to be added in the SmartScripts code for that to be possible?

**Comment by Killyana** [comment]
No too complex for SAI, this chains were working properly in older revisions

**Comment by illfated** [comment]
OK, fair enough. Thanks for clarifying. Could it have something to do with event handling and timers like `wait_timer = 5000;` ?

I remember some of the old scripts stopped working because of timers, like in Ring of the Law / Ring of Law.

**Comment by Killyana** [comment]
It's a los issue:
``` sql
DELETE FROM `disables` WHERE `sourceType`=0 AND `entry` IN (54613);
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
(0, 54613, 64, '', '', '');
```
the gobs in front of the npc triggers mustn't block los.
