### ISSUE TITLE
Core/Movements: Incorrect Extra shortcuts

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24080]
**Description:** After https://github.com/TrinityCore/TrinityCore/commit/29bf280e3496cf13c24ccb20e37da29d3bfa74d9 creatures with movements like follow, random movements, Confused moves weirdly.

Videos:
Follow: https://imgur.com/mzvAkI2
Confused: https://imgur.com/a/JvNQkna
Random movements: https://imgur.com/a/Nomo9cY

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. 58313962994e

**Comment by illfated** [comment]
Thanks. I have noticed that hunter pets, when following, tend to make erratic, cross-path moves, taking a longer route to get back close to the player.

**Comment by jackpoz** [comment]
The commit has been reverted
