### ISSUE TITLE
[3.3.5][Hunter] Movement Pet not in agreement

### ISSUE THREAD

**Issue by junker1609** [TrinityCore/TrinityCore#24086]
Hello,

**Description:**

Familiar movements are sometimes not taken into account, it goes under-map and it runs in all directions
And it influences the **bestial wrath** that it is not taken into account sometimes
Screen : 
![pet](https://user-images.githubusercontent.com/57899911/72728265-43137e80-3b8d-11ea-89a0-75ef4b536414.png)
Video :
 https://youtu.be/P9mQXPN6bDQ

**Current behaviour:**

It runs in all directions and does not calculate the position of the target

**Expected behaviour:**

Attack the target in its exact position and do not get submap

**Steps to reproduce the problem:**

1- Create a hunter, have the beast spec

2-  Attack enemies in upper floors

3- Recall pet to bring target back and re-attack target

**Branch(es):**

3.3.5 Branch
**TC rev. hash/commit:** 

TrinityCore rev. ff24339ca52e+ 2020-01-20 01:35:27 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Operating system:** CHANGEME OS
ubuntu 18.04 64 bits

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/ff24339ca52e 404

**Comment by junker1609** [comment]
> [ff24339](https://github.com/TrinityCore/TrinityCore/commit/ff24339ca52e) 404

I just put the updates last night to take into account the correction of the avoided attacks.
![update](https://user-images.githubusercontent.com/57899911/72728763-60951800-3b8e-11ea-8134-5f22d37c1035.png)

**Comment by Jinnaii** [comment]
The unknown revision you posted just tells us that you have modified your core. 
If you post issues, please test them on a clean up-to-date revision of trinitycore - a lot of people dont even take the time to reproduce the problem if the issue wasnt tested on a clean revision.

That doesnt make you issue invalid ofc, this is just a friendly reminder.

**Comment by junker1609** [comment]
> The unknown revision you posted just tells us that you have modified your core.
> If you post issues, please test them on a clean up-to-date revision of trinitycore - a lot of people dont even take the time to reproduce the problem if the issue wasnt tested on a clean revision.
> 
> That doesnt make you issue invalid ofc, this is just a friendly reminder.

Thanks for your understanding, I just added, i just added transmogrification, I haven't changed anything except.

**Comment by Killyana** [comment]
Fixed with https://github.com/TrinityCore/TrinityCore/commit/67d9d04d63cc74196059646b2e57f50a4a4fd2ca
