### ISSUE TITLE
[3.3.5]Obsidian Sanctum Vesperon Portal

### ISSUE THREAD

**Issue by junker1609** [TrinityCore/TrinityCore#24097]
Hello, 
**Description:**

The portal does not appear to be able to kill the acolyte, and even under a GM character when you click nothing happens
![vesperon](https://user-images.githubusercontent.com/57899911/72931006-6725ba00-3d5d-11ea-81df-4d5590afe15b.png)

**Current behaviour:**

We endure the dowries and impossible to kill vesperon without killing the acolytes

**Expected behaviour:**

The portal works, we go to the other world to kill the Acolytes

**Steps to reproduce the problem:**

1- Rush OS 10 or 25
2- Wait phase where we have to kill the acolytes

**Branch(es):**
3.3.5 branch

**TC rev. hash/commit:** 
TrinityCore rev.f52eced08066+ ( Only transmog added )

**Operating system:** ubuntu 18.04 

Thanks.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19363

**Comment by Aokromes** [comment]
or https://github.com/TrinityCore/TrinityCore/issues/15209
