### ISSUE TITLE
Map extraction issue

### ISSUE THREAD

**Issue by jazzy348** [TrinityCore/TrinityCore#24094]
Hi,

I freshly compiled the master branch with visual studio 2017 on windows server 2019. I tried exacting maps using the compiled binary but received a few errors. I'm using the latest wow client downloaded today.

![Screenshot_20200122_114106_com parallels client~2](https://user-images.githubusercontent.com/10477373/72891744-d8894c80-3d0c-11ea-950a-7c0b94b0ba1e.jpg)

**Comment by Aokromes** [comment]
what wow version you have tried? (8.2.5 supported) (8.3.0 unsupported)
