### ISSUE TITLE
Cash/SAI: SMART_ACTION_CALL_SCRIPT_RESET with SMART_EVENT_RESET 

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24092]
**Description:** If you use the action SMART_ACTION_CALL_SCRIPT_RESET with the event  SMART_EVENT_RESET the server will crash with a STACK_OVERFLOW
![image](https://user-images.githubusercontent.com/6587064/72852239-3cc8f380-3cae-11ea-9732-d67e6da246d8.png)

``` sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry` IN (321);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(321,0,0,0,25,0,100,0,0,0,0,0,0,78,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'321 - on reset - reset scripts');
``` 
**Steps to reproduce the problem:**

1. use the sql above
2. .npc add temp 321
3. the server will crash with no log

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d293dd37822d

**Comment by Killyana** [comment]
Revert https://github.com/TrinityCore/TrinityCore/commit/163f44c1b08cc043b114585922bd08664434bf92 fix the issue

**Comment by jackpoz** [comment]
We should skip events with this particular combination

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/28921f191de2269dd90b50ac99dd0d29ba90d0c4
