### ISSUE TITLE
Core/Map: Npcs in DK map evades if the area changes

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24091]
**Description:** In the DK map if a npc is chasing and you move from an area to an other it will evade.

https://imgur.com/rNYkYbL

**Steps to reproduce the problem:**

1. .go xyz  1684.517090, -5962.81689, 129.262207 609
2. aggro the 2 npcs and run like in the video

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 67d9d04d63cc

**Comment by jackpoz** [comment]
Is that after the mmaps changes ?

**Comment by Killyana** [comment]
Before https://github.com/TrinityCore/TrinityCore/commit/d293dd37822d93f9023d3ff9d39052ed976e236b

But I also get a crash at the same position so I compiled with the last revision, I need to get a proper crash log before retesting.

**Comment by Killyana** [comment]
Confirmed in rev. d293dd37822d
The crash is not related to this issue, probably to a bad SAI.

**Comment by jackpoz** [comment]
could you check if it happens with an older revision too ? like 1 month ago or so

**Comment by Killyana** [comment]
I was able to reproduce it in rev. 45362ef413b80b852342fcbd85488bb4acd87f18
So the issue is old or something is wrong in my side.

**Comment by jackpoz** [comment]
> 	worldserver.exe!Unit::AttackStop() Line 5597	C++
 	worldserver.exe!Unit::RemoveAllAttackers() Line 5685	C++
 	worldserver.exe!Unit::CombatStop(bool includingCast, bool mutualPvP) Line 5642	C++
 	worldserver.exe!Unit::CombatStopWithPets(bool includingCast) Line 5658	C++
	worldserver.exe!Player::UpdateArea(unsigned int newArea) Line 7032	C++
 	worldserver.exe!Player::UpdateZone(unsigned int newZone, unsigned int newArea) Line 7068	C++
 	worldserver.exe!Player::UpdatePosition(float x, float y, float z, float orientation, bool teleport) Line 6352	C++
 	worldserver.exe!Player::UpdatePosition(const Position & pos, bool teleport) Line 1677	C++
 	worldserver.exe!WorldSession::HandleMovementOpcodes(WorldPacket & recvData) Line 410	C++

**Comment by jackpoz** [comment]
When a player moves and changes area, he enters a sanctuary area and that stops all player combat (and the attackers combat too)
```cpp
// previously this was in UpdateZone (but after UpdateArea) so nothing will break
    pvpInfo.IsInNoPvPArea = false;
    if (area && area->IsSanctuary())    // in sanctuary
    {
        SetByteFlag(UNIT_FIELD_BYTES_2, UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_BYTE2_FLAG_SANCTUARY);
        pvpInfo.IsInNoPvPArea = true;
        if (!duel)
            CombatStopWithPets();
    }
    else
        RemoveByteFlag(UNIT_FIELD_BYTES_2, UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_BYTE2_FLAG_SANCTUARY);
```

**Comment by jackpoz** [comment]
>area
0x0000024382d55018 {ID=4343 mapid=609 zone=4298 ...}
    ID: 4343
    mapid: 609
    zone: 4298
    exploreFlag: 2050
    flags: 1073741888
    area_level: 55
    area_name: 0x0000024382d55030 {0x000002438299bcb3 "New Avalon", 0x0000024382994bc0 "", 0x0000024382994bc0 "", 0x0000024382994bc0 "", ...}
    team: 0
    LiquidTypeOverride: 0x0000024382d550b4 {0, 0, 0, 0}

**Comment by jackpoz** [comment]
now you might wonder how come it's a sanctuary area ? here's how:
```cpp
    bool IsSanctuary() const
    {
        if (mapid == 609)
            return true;
        return (flags & AREA_FLAG_SANCTUARY) != 0;
    }
```
