### ISSUE TITLE
[master] 8.2.5 Bruteforce Data

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#24099]
**Description:**

Starting to provide bruteforced data.

- **APPLY FIRST** VerifiedBuild Update hotfixes https://gist.github.com/funjoker/ea996652103b0b06adab771b545b8b83

- **APPLY NEXT** VerifiedBuild Update world https://gist.github.com/funjoker/a115eb3b63802dffd30ff71d50a08e67

- broadcast_text
  - enUS https://gist.github.com/funjoker/056efc41966ee1d91f9b106e10e02f82
  - frFR https://gist.github.com/funjoker/48f99ab57f62fee0ee288fc46729653b
  - deDE https://gist.github.com/funjoker/ce6a9d29680a31e4b36c8fbd3d02daa0
  - esES https://gist.github.com/funjoker/a26409c9964c2c2692f9f7ef1b276b3b
  - esMX https://gist.github.com/funjoker/09065733e86ac026dc1584f27f32f768
  - ptBR https://gist.github.com/funjoker/d62da38cc3eac20b4f61683f8a115f32
  - zhCN https://gist.github.com/funjoker/5b2dda80d90b97e4f40519739896d478
  - zhTW https://gist.github.com/funjoker/2f8a167494b61bede2983db1d2051c4e
  - koKR https://gist.github.com/funjoker/e5b0f12f7b95a29b701c60b48e7e9975
  - ruRU https://gist.github.com/funjoker/391036315687ccc8c586bdd6818aae7f
  - itIT https://gist.github.com/funjoker/1f1149c60392ed89b288640bd189cc79

- creature_template, creature_template_model, creature_questitem
  - enUS https://gist.github.com/funjoker/e9d7f491ffdd8dbe7b5885bb70e4b67d
  - frFR https://gist.github.com/funjoker/e12ed258345a3f932c26de03d522fa0a
  - deDE https://gist.github.com/funjoker/b067e9b806ca215871209cb5401b5705
  - esES https://gist.github.com/funjoker/df69851e131ae243f2ecfa11e4f15105
  - esMX https://gist.github.com/funjoker/fbb97fcdec8197f1d1e1ec51f30c687f
  - ptBR https://gist.github.com/funjoker/8ef07b161960ac59aa4d58272fdde61f
  - zhCN https://gist.github.com/funjoker/4776e7fb49b3ebe79ce0cf22578156ae
  - zhTW https://gist.github.com/funjoker/808360997fb0ebb80a225653fd42313d
  - koKR https://gist.github.com/funjoker/cc533b18e755f0075df626805780ae1e
  - ruRU https://gist.github.com/funjoker/16d5dd1cc5b9ba1fb6ad6ea741eb6551
  - itIT https://gist.github.com/funjoker/a7fa6c64bc71503a40784a38e3879a34

- quest_template
  - enUS https://gist.github.com/funjoker/653d37de59ce551f9dfa67269bbfbac5
  - frFR https://gist.github.com/funjoker/0a69088825a51316311757fb04e03f0a
  - deDE https://gist.github.com/funjoker/90f650595e112955bdd8d61774a81c94
  - esES https://gist.github.com/funjoker/c090e8128fc091f439d47a9df0783a33
  - esMX https://gist.github.com/funjoker/ad7b889c7c61be111a0a0ead2f748a17
  - ptBR https://gist.github.com/funjoker/1e763f674e2f7642af79b418a4bbc1d3
  - zhCN https://gist.github.com/funjoker/2898bd9bb6e723f2b148b9ef8d6ffdbe
  - zhTW https://gist.github.com/funjoker/2329b8db45a12879d67c5ca053eba63f
  - koKR https://gist.github.com/funjoker/1f24f5f317ab0ca6c775bc61fadb15d9
  - ruRU https://gist.github.com/funjoker/683a3fd18d388077172642788e7ff025
  - itIT https://gist.github.com/funjoker/1e4664abbf075804fee2c10d227c3f9d

- quest_poi https://gist.github.com/funjoker/af875dc2a1916b38aa5bc87d665edc52
- quest_poi_points  https://gist.github.com/funjoker/a2ae2b33e29b1db78eb0018554287e6b

**Branch(es):**

master

**TC rev. hash/commit:** 

a4a266ed2c3cbc0e32c601256ea55f2f26ef077f

**Comment by dio85** [comment]
broadcast_text esMX syntax error, not full.

**Comment by funjoker** [comment]
Ty, will take care tomorrow.

**Comment by funjoker** [comment]
fixed

**Comment by dio85** [comment]
Thanks!

**Comment by RaphtaliaYukii** [comment]
Sorry for my ignorance, but what mean bruteforced data?
