### ISSUE TITLE
Problem with new versions of programs.

### ISSUE THREAD

**Issue by Guybrush1982** [TrinityCore/TrinityCore#24104]
**Description:**

Problem using Cmake

**Programs and versions**
Windows 10 64bit Version
CMake 3.16.3 64 bit
VStudio Community 19
Git-2.25.0-64-bit
GitExtensions-3.3.1.7897.msi
mysql-installer-web-community-5.6.47.0.msi
SQLyog-13.1.5-0.x64Community.exe
boost_1_66_0-msvc-14.1-64.exe
Win64OpenSSL-1_1_0L.exe

**Current behaviour:**
Trying to install MOP 5.4.8 Server
https://github.com/ProjectSkyfire/SkyFire_548

I followed trinityCore tutorial downloading and installing the programs required, but its outdated. I figured some issues, but when i tried to Generate in CMake appears the next report:

The C compiler identification is MSVC 19.24.28315.0
The CXX compiler identification is MSVC 19.24.28315.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Setting build type to 'Release' as none was specified.
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
MSVC: C++17 Standard Enabled.
Found OpenSSL library: optimized;C:/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win64/include
CMake Warning (dev) at cmake/macros/FindOpenSSL.cmake:224 (math):
  Unexpected character in expression at position 2: c

Call Stack (most recent call first):
  CMakeLists.txt:62 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/macros/FindOpenSSL.cmake:237 (message):
  SkyFire needs OpenSSL version 1.1.1 but found version 1.1.0`
Call Stack (most recent call first):
  CMakeLists.txt:62 (find_package)

Configuring incomplete, errors occurred!
See also "H:/Servidores Privados Wow/MOP 5.4.8/Mop_Build/CMakeFiles/CMakeOutput.log".

I would appreciate your help. 
Just in case, i really havent any knowledge about programing, please explain for starters if i need to open cmd console or that kind of things.

Thank you very much.

**Comment by Aokromes** [comment]
trinitycore never supported mop.
