### ISSUE TITLE
Core/AI: Charrmed creature must follow the owner upon charmed

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24103]
**Description:** If you charm a creature it will not follow you unless you use the command from the pet bar, this is wrong as some charms doesn't have that, like here https://github.com/TrinityCore/TrinityCore/issues/22330#issuecomment-577941413

**Steps to reproduce the problem:**

1. .cast 260  in any creature
2. notice it will not follow you

**Branch(es):** both

**TC rev. hash/commit:** rev. 78c1216bcf60

**Comment by jackpoz** [comment]
Additional notice: after the charm is over, they should stop following you (atm if you click "Dismiss" they keep following you)

**Comment by Killyana** [comment]
Actually they must attack you if they can, if not evade to home position

**Comment by jackpoz** [comment]
"Follow" bit fixed, "Return home" is WIP

**Comment by jackpoz** [comment]
Fixed the "return home" too
