### ISSUE TITLE
RS: Halion attack distance

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#24109]
**Description:**
Something is happening with Halion attack distance for some spells and casters.

**Current behaviour:**
- From one side, a paladin must be really close (distance <= 8 yards) to Halion to be able to spellhit with Divine Storm.
- From the other side, a paladin can be really far (distance <= 25 yards) and Divine Storm will hit.
- Using a warlock, is it possible to cast Shadow bolt so far (distance = 54 yards) that it will damage Halion and Halion will not attack.

**Expected behaviour:**
Attack distance should be the same for spells like Divine Storm from both sides and it should not be possible to attack Halion as far as possible without starting the encounter.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/f0485cea394a84e93ebacc24f3535d5eb14a4053
**Operating system:** Win 10

**Comment by Jildor** [comment]
related to: #22375
