### ISSUE TITLE
Core/Player: Profession skill not saved in database (Bounty)

### ISSUE THREAD

**Issue by finestlyker** [TrinityCore/TrinityCore#24107]
**Description:**
if i learn the profession that work but i can progress the skill but if reconnect to the server that not saved in the database.

**Steps to reproduce the problem:**

1. create any characters  
2. learn profession tailoring
3. progress this profession
4. ex. 39/75 (skill)
5. disconnect the character and connect again.
6. the progression restart to 1/75 skill.

**Branch(es):**
Master, Last updated

**Operating system:** WinServer2016 x64

**Comment by jackpoz** [comment]
even if you are using "latest" version, please include the hash as tomorrow "latest" will have a different meaning than today

**Comment by Ovahlord** [comment]
This issue is quite simple. The skill field initialization is filling the skill map with a buttload of skills marked as 'unchanged'. This means that the learned skills will never be marked as new so the core always tries to update non-existant skill entries.

**Comment by illfated** [comment]
Suggestion for improved issue ticket title:
**Core/Player: Profession skill not saved in database**

(the "bounty" part of the title (and amount) can be added by TC members as soon as a BountySource page or other documented bounty is linked here)

**Comment by finestlyker** [comment]
i would be willing to give 20 usd for the beginning

**Comment by illfated** [comment]
I could not find this issue ticket referenced on https://www.bountysource.com/teams/trinitycore/issues , but maybe BountySource just needs a link somewhere?
