### ISSUE TITLE
Finger of death and command "respawn" don't work properly

### ISSUE THREAD

**Issue by Herawen** [TrinityCore/TrinityCore#24108]
Hi, I'm new in this area, I don't know anything about development and programming, I've been taught very little before. And I would like to learn a lot because I love this. I have a problem with the archimonde death finger. When I learn it with GM command and use it on some animal, the spell kills myself and not the animal or other creature. Another problem I have is with the "respawn" of the creatures, I can't bring them back to life with that command, it doesn't work. Can anybody help me? What should I modify in the SQLyog tables? I would really appreciate if you could give me a page to learn more about how to fix bugs. Thank you in advance

PD: Yesterday I started a test server to learn. Sorry if my post is not well prepared.

**Comment by buddyqc69** [comment]
is not a bug, if you need help just start a post on forum of trinitycore

**Comment by Killyana** [comment]
You can ask for help in IRC or the forum.
