### ISSUE TITLE
Some required *.db2 files (249 from 1) not found or not compatible:

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24101]
Initialize PlayerDump...
Initialized 368 PlayerDump ColumnDefinitions in 13 ms.
Loading Trinity strings...
Loaded 966 trinity strings in 2 ms
Initialize data stores...

Some required *.db2 files (249 from 1) not found or not compatible:
Achievement.db2

**Comment by Aokromes** [comment]
i vote you are using wow 8.3.0 or bad placed files.

**Comment by wplatform** [comment]
Ok, have a try. the Chinese wow 8.3.0 release yesterday. I do not find any changes for this client version

**Comment by Aokromes** [comment]
8.3.0 is unusuported.

**Comment by illfated** [comment]
From the repository main page: TrinityCore Open Source MMO Framework (**master = 8.2.5.32978**, 3.3.5 = 3.3.5a.12340)
