### ISSUE TITLE
Alt + f4 during boss encounters

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#24110]
**Description:**
As far as I know, there 1 minute to connect again if the player has been disconnected and continue the encounter with a boss normally.
The problem is that a player can alt + f4 with certain auras or conditions and can come back to the game without them.

**Current behaviour:**
A player can use alt + f4 in ICC and connect again to get rid of things like:
- Uncontrollable Frenzy (Blood Queen Lanathel)
- Being grabbed by Val'Kyrs Shadowguards (The Lich King)

When the player is back, he is no longer controlled or grabbed and can continue the encounter as if nothing happened.

**Expected behaviour:**
No idea what should happen in these specific situations.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/f0485cea394a84e93ebacc24f3535d5eb14a4053
**Operating system:** Win 10

**Comment by shamage** [comment]
If the memory doesn't fool me, if a player did ALT + F4 during Dungeon or Battlefiel and managed to log in while the action was in progress, the system had logged it in from the beginning and the player had to go over the route he had already taken. However, if the player missed the time and the others have already completed the Dungeon or Battlefield system, the player's ability to go back - automatically returned to the original point from where he was teleported to Dungeon or Battlafiel. The auras, conditions and the like have always been reset to the player. Please correct me if I'm wrong!

**Comment by shamage** [comment]
I think it should be the case: Uncontrollable Frenzy (Blood Queen Lanathel) or Being grabbed by Val'Kyrs Shadowguards (The Lich King) or something similar.

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19926
