### ISSUE TITLE
DB/Event: Absolute end time for all events

### ISSUE THREAD

**Issue by Kitzunu** [TrinityCore/TrinityCore#24125]
**Description:**
Currently all/most events are set to an absolute end_time in 2019 or 2020
```sql
SELECT * FROM game_event WHERE end_time LIKE '%2020%';
SELECT * FROM game_event WHERE end_time LIKE '%2019%';
```

**Expected behaviour:**
These need to be extended so that the events can keep occurring in the future :D

**Branch(es):**
3.3.5
Probably master too but I do not have that.

**TC rev. hash/commit:** 
d4680bb2b250

**Operating system:** 
Windows

**Comment by Aokromes** [comment]
I suppose we can do

```sql
UPDATE `game_event` SET `end_time` = '2030-12-31 05:00:00';

**Comment by ForesterDev** [comment]
Why not use NULL for infinite events?

**Comment by Kitzunu** [comment]
Just a question; end_time has nothing to do with the occurrence or length of the actual events, right?

If that is the case, then Aokromes fix will work for the next 10 years.

**Comment by illfated** [comment]
Fair point. The only detail I remember is that some game events used to have a set end date/time because the event could go out of sync with the actual future calendar dates.

**Comment by Kitzunu** [comment]
That is something that has to be corrected with time then I suppose since the client wont let us see the ingame calendar longer than Feb 2021

**Comment by natnat201193** [comment]
@Kitzunu it will if you change your system time to the future, then launch the game.

Events with Inconsistent dates could do with their own table and handling specifically tailored to work the same way blizzard does them, more info about it here: https://github.com/TrinityCore/TrinityCore/issues/24045
