### ISSUE TITLE
The world proceess be killed when starting.

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24129]
Loading C++ scripts
>> Loaded 3080 C++ scripts in 72 ms
Validating spell scripts...
>> Validated 2783 scripts in 4 ms
Loading SmartAI scripts...
>> Loaded SmartAIMgr Helpers in 11 ms
>> Loaded 12441 SmartAI scripts in 164 ms
Loading Calendar data...
>> Loaded 0 calendar events in 1 ms
>> Loaded 0 calendar invites in 0 ms
Loading Petitions...
>> Loaded 0 petitions.
Loading Signatures...
>> Loaded 0 Petition signs!
Loading Item loot...
>> Loaded 0 stored item loots
>> Loaded 0 stored item money
Initialize query data...
Initialize game time and timers
Mail timer set to: 420, mail return is called every 1440 minutes
Starting Map System
Starting Game Event system...
Initialize AuctionHouseBot...
Initializing chat channels...
>> Loaded 0 custom chat channels. DB table `channels` is empty.
Initializing Opcodes...
Starting Arena Season...
Starting Battleground System
>> Loaded 11 battlegrounds in 2 ms
Starting Outdoor PvP System
>> Loaded 6 outdoor PvP definitions in 1 ms
Starting Battlefield System
Loading Transports...
Killed

**Comment by Ovahlord** [comment]
There is a issue template for a reason. Use it, provide crashlogs, otherwise nobody will care.

**Comment by Aokromes** [comment]
now that i realize, killed is server killed it, very likely very limited shared / vps hosting.
