### ISSUE TITLE
Fix issue with credit for blowing up Vykul during quest Warning: Some Assembly Required

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#24122]
Currently you only get credit if you round up Vrykul and take abdomination back to near your player before exploding.  If the adobination is too far away from player when you expode it the mobs die but player receives no credit currently the effected mobs are casting credit spell at invoker using action 11.

If this is changed to invoker cast 134 then this works correctly
~~~sql
UPDATE `smart_scripts` SET `action_type`='134', `action_param2`='2' WHERE  `entryorguid`IN(23564,24198,24199) AND `source_type`=0 AND `id`=0 AND `link`=1;

**Comment by Killyana** [comment]
This is also weird:
``` sql
entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, comment
 23564, 0, 2, 0, 8, 0, 100, 0, 42167, 0, 0, 0, 0, 11, 42167, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, Plagued Dragonflayer Tribesman - On Spellhit 'Plagued Blood Explosion' - Cast 'Plagued Blood Explosion'

**Comment by dr-j** [comment]
Hmm ye and it casts that spell on self and wouldnt that cause a loop of casting spell on self and and then on spellhit casting again.

Maybe thats so that if another abdomination explodes within 15 yards it also blows up

seems that spell has a radius of 15 yards and stuns and triggers suicide
