### ISSUE TITLE
[3.3.5]Naxxramas Boss_Noth Unit_Flags

### ISSUE THREAD

**Issue by junker1609** [TrinityCore/TrinityCore#24123]
**Description:**

the boss noth is teleported back in phase 2 but the unit_flags does not change, It is unbreakable and unassailable

**Current behaviour:**

When it teleports to the balcony it changes flag units but when it returns it stays with the same flags units

**Expected behaviour:**

It should be selectable and attackable again

**Steps to reproduce the problem:**

1- Go to naxxramas
2- Attack Noth and wait phase 2
3- U cant attack him when he teleport back

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

commit #b0bf127

**Operating system:** CHANGEME OS
ubuntu 18.04

I confirmed the problem with .NPC Info before  attacking Noth and after teleport back

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23909
