### ISSUE TITLE
Allow path generator to be used on any object type instead of units only

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#24137]
**Description:**
As result of a WIP change for MoveToFirstCollision there has have been emerging cases that require the path generator to be able to be used by any object. The current implementation of the path generator is only restricted for units and thus doing things like detour based recasts will only be available for units.

**Current behaviour:**
PathGenerator is restricted to units.

**Expected behaviour:**
Expand the implementation to support all worldobject types (Unit, GameObject, DynamicObject etc.)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
299d6ebbffd11a8fa92327c5a9296602a1596202

**Operating system:** 
Windows 10 pro

**Comment by soulfrost** [comment]
gameobject and dynamicobject should move?

**Comment by Ovahlord** [comment]
No, but the helper is available for all object types and since we are going to move the logic to detour raycasts we need raycasts for all object types.

**Comment by jackpoz** [comment]
something like https://github.com/TrinityCore/TrinityCore/compare/3.3.5...jackpoz:3.3.5-pathgenerator-object ? Water is supported only for Unit, let me know if that's an issue.
