### ISSUE TITLE
[3.3.5] [Achievement] [1291] Lonely

### ISSUE THREAD

**Issue by peycho** [TrinityCore/TrinityCore#24139]
**Description:**
For some reason the achievement can't be completed.

**Current behaviour:**
Currently nothing happen except the basket and the umbrella are spawn.

**Expected behaviour:**

When two characters are joining together with [Romantic Picnic Basket](https://wotlk.evowow.com/?item=34480) they should fall in love. I guess the effect is called like that.
They should get hearth above they heads and then, when they start eating [Buttermilk Delight](https://wotlk.evowow.com/?item=22236) they should get the achievement [Lonely?](https://wotlk.evowow.com/?achievement=1291)

**Steps to reproduce the problem:**

1. Go to Dalaran.
2. Use [Romantic Picnic Basket](https://wotlk.evowow.com/?item=34480)
3. Use second character to join your picnic table.
4. Wait for the hearth effect.
5. Eat [Buttermilk Delight](https://wotlk.evowow.com/?item=22236) 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5fa77744e4495a77dea734330d5ae9e113b8a7f1

**Operating system:**

Ubuntu 16.0.4 LTS

**Comment by Rushor** [comment]
```
-- Romantic Basket SAI
SET @ENTRY := 187267;
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,1,0,0,64,0,100,0,0,0,0,0,85,45102,2,0,0,0,0,7,0,0,0,0,0,0,0,"Romantic Basket - On Gossip Hello - Invoker Cast 'Romantic Picnic'");
```

**Comment by Killyana** [comment]
The spell 45102 is already in data 10

**Comment by Rushor** [comment]
yes but if casted by gameobject it fails - if casted by player it works 

strange issue (as always lol)

**Comment by Aokromes** [comment]
maybe los shit?

**Comment by Killyana** [comment]
No, just spells cast by gobs don't validate the criteria.

**Comment by Rushor** [comment]
the achievement criteria is a spellcast right? https://wotlk.evowow.com/?spell=45123

Is there a similar gameobject where that part of achievement works? so we could compare the mechanic

**Comment by Killyana** [comment]
I don't know any similar case, but gameobject cast is new so probably the part that validate a criteria via a spell wasn't updated to support gobs as caster.

**Comment by Rushor** [comment]
should we just push this then?

**Comment by peycho** [comment]
If the patch works as expected and don't affects/breaks anything else. I'm good.
Anyway, the call is yours devs.

**Comment by Killyana** [comment]
No It's a hack
