### ISSUE TITLE
DB/Creature: Tabea

### ISSUE THREAD

**Issue by Kitzunu** [TrinityCore/TrinityCore#24136]
**Description:**
She is supposed to have a leach attached to her companion Apollo.

> Patch 3.1.0 (2009-04-14): Apollo is now leashed to Tabea.

Tabea: 32843
Apollo: 32844

**Steps to reproduce the problem:**

1. .go c id 32843

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
d4680bb2b250

**Operating system:** 
Windows

On a side note, Apollo might be using the wrong Model because if you see this image:
![image](https://user-images.githubusercontent.com/24550914/74088505-7a43c400-4a97-11ea-8aa5-05dc66359759.png)
taken from https://wow.gamepedia.com/index.php?title=Apollo&direction=prev&oldid=2448534 (Revision as of 14:13, 18 November 2009) he is a black wolf and in-game currently he is kind of orange hyena looking.
![image](https://user-images.githubusercontent.com/24550914/74088519-a65f4500-4a97-11ea-9c2c-2fcc4db2bee6.png)

**Comment by Killyana** [comment]
Probably only in the new version of Dalaran, I checked 3.3.5 and 4.3.4 sniffs and no aura in both npcs, also screens don't show any leach https://www.wowhead.com/npc=32843/tabea#screenshots:id=546352

**Comment by illfated** [comment]
Please note the difference between the words [**leash**](https://www.google.com/search?q=leash) and [**leach**](https://www.google.com/search?q=leach).

**Comment by illfated** [comment]
Regarding the model, consider the text from the page you linked (wow.gamepedia.com, November 2009):
"Apollo is Tabea's hyena companion. It can be found wandering around near the Violet Citadel alongside Tabea."

The more interesting part is the Patch 3.1.0 quote:
**Patch 3.1.0** (2009-04-14): Apollo is now leashed to Tabea.
