### ISSUE TITLE
3.3.5 branch fails dynamic compile

### ISSUE THREAD

**Issue by Exitare** [TrinityCore/TrinityCore#24144]
**Description:**

I tried to compile 3.3.5 in dynamic mode  (screen attached) but visual studio fails to finish compile.
Rev is linked. Screens attached. No scripts added or modified. Plain installation.

**Current behaviour:**

Visual Studio 19 (latest update, no preview) is failing compiling in dynamic mode.

**Expected behaviour:**

Compile should work

**Steps to reproduce the problem:**

1. Clone branch 3.3.5
2. Open cmake, specify folders, press configure
3. Change everything to dynamic. Screen attached. 
4. Press generate
5. Open VS, right click on Install -> Build

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

299d6ebbffd1

**Operating system:** Windows

![cmake43](https://user-images.githubusercontent.com/13048528/74181230-bc831780-4bf5-11ea-9df3-8120ef5c0b36.PNG)
![cmake](https://user-images.githubusercontent.com/13048528/74181235-bdb44480-4bf5-11ea-8f51-7cafafb67da6.PNG)
![cmake 2](https://user-images.githubusercontent.com/13048528/74181237-bee57180-4bf5-11ea-96a2-e58b96d3e990.PNG)
![vs crash](https://user-images.githubusercontent.com/13048528/74181243-c147cb80-4bf5-11ea-99eb-b967db0e8b62.PNG)

**Comment by jackpoz** [comment]
The whole visual studio log is needed, the screenshot of a portion is not enough.

**Comment by jackpoz** [comment]
https://ci.appveyor.com/project/DDuarte/trinitycore/builds/30666866 also says dynamic build on windows works

**Comment by Exitare** [comment]
![vs crash](https://user-images.githubusercontent.com/13048528/74183334-9e1f1b00-4bf9-11ea-9755-3ca07cc7c4ed.PNG)

if this is still not enough, please specify where the log is stored

**Comment by Shauren** [comment]
Paste the entire goddamn output windows on a service like paste2 or gist, not partial screenshots

**Comment by Exitare** [comment]
https://gist.github.com/Exitare/f32b5744ea174f1452be84e6628b0088

**Comment by Shauren** [comment]
```
21>D:\VS19\VC\Tools\MSVC\14.24.28314\include\xhash(437): fatal error C1001: An internal error has occurred in the compiler.
21>(compiler file 'd:\agent\_work\5\s\src\vctools\Compiler\Utc\src\p2\tuple.c', line 8422)
```

Nice. internal compiler error

**Comment by Exitare** [comment]
So? What is that related to? How can i fix that?

**Comment by Faq** [comment]
Yes, checked now an got the same 

> 14.24.28314\include\xhash(437): fatal error C1001: An internal error has occurred in the compiler.

**Comment by MaxtorCoder** [comment]
Sounds to me you are using latest Visual Studio 2019, try using a lower version, maybe that'll fix it.

**Comment by jackpoz** [comment]
Report the issue to Visusl Studio through its support channels, we can't fix issues in Visual Studio.
In the meantime you could build TC with static build instead of dynamic.

**Comment by Aokromes** [comment]
wiki updated.
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977296/Windows+Requirements

**Comment by jackpoz** [comment]
this happens on VS 2019 16.4.4 too (no preview)

**Comment by jackpoz** [comment]
>21>Building Custom Rule D:/Projekte/WoW/Core/TrinityCore/src/server/game/CMakeLists.txt
21>CreatureAI.cpp
21>D:\VS19\VC\Tools\MSVC\14.24.28314\include\xhash(437): fatal error C1001: An internal error has occurred in the compiler.

In PCH mode the issue happens when trying to compile the PCH triggered by CreatureAI.cpp . In no-PCH mode the issue doesn't happen (just built the whole solution).

**Comment by Exitare** [comment]
@jackpoz thanks, will try it tonight!

**Comment by Exitare** [comment]
Sorry for the delay. Checked on my side. Everything works fine without PCH´s. 
Thanks again for the advice!
