### ISSUE TITLE
Spell server crash

### ISSUE THREAD

**Issue by dr3adx** [TrinityCore/TrinityCore#24145]
**Description:**

Learning spell ID 189768 instantly crashes server in response to an infinite loop of HandleEffect -> ApplySpellMod -> ChangeAmount that it causes

**Current behaviour:**

Crash

**Expected behaviour:**

No crash

**Steps to reproduce the problem:**

.learn 189768 on a Druid (other classes probably crash too)
server then instantly crashes

**Branch(es):**

master

**TC rev. hash/commit:**

latest

**Crashlog**
https://pastebin.com/N3sZQj3d

**Comment by Faq** [comment]
@dr3adx still happens on 2032ade386fd5c54cc4d3b3a838197ebcb479885 ?

**Comment by dr3adx** [comment]
> @dr3adx still happens on [2032ade](https://github.com/TrinityCore/TrinityCore/commit/2032ade386fd5c54cc4d3b3a838197ebcb479885) ?

yes it does

**Comment by Smerdokryl** [comment]
Still happens on e5b12a7

**Comment by illfated** [comment]
Spell info, in case someone wants to know instead of guessing:
- https://www.wowhead.com/spell=189768/seeds-of-the-world-tree

**Comment by Aokromes** [comment]
@matanshukry this is still valid?

**Comment by matanshukry** [comment]
@Aokromes yup, but not for long.

**Comment by matanshukry** [comment]
Now that it's fixed (credit where credit's due, Shauren actually fixed the bug btw) - we can unpin this issue
