### ISSUE TITLE
Core/Combat: Melee attacks from player with unit flags change

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24154]
**Description:** During a combat if the creature get a unit flag like UNIT_FLAG_IMMUNE_TO_PC or UNIT_FLAG_NON_ATTACKABLE the auto attack from the player must be interrupted.

**Current behavior:** The player continue the auto attack even if the creature has UNIT_FLAG_IMMUNE_TO_PC or UNIT_FLAG_NON_ATTACKABLE

**Expected behavior:** Auto attack must be interrupted as the target is not valid

**Steps to reproduce the problem:**

1. .quest add 11627
2. .go c id 25416
3. auto attack until it get 1% and stop attacking (it will get UNIT_FLAG_NON_ATTACKABLE)
4. Notice you char is still auto attack the npc

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 74a825d046af

**Comment by illfated** [comment]
(link info, in case someone wants to know more before digging:)
- https://www.wowhead.com/quest=11627/boiling-point
- https://www.wowhead.com/npc=25416/simmer

**Comment by Rushor** [comment]
This is caused by the combat rewrite?

**Comment by Killyana** [comment]
No, very old issue, since ever probably.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/24651
