### ISSUE TITLE
Was there a test before commint the code changes.

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24155]
Today, I upgrade the source and remake. an error occurred.
[ 10%] Building CXX object src/common/CMakeFiles/common.dir/Banner.cpp.o
fatal error: C++17 was disabled in PCH file but is currently enabled
1 error generated.
src/common/CMakeFiles/common.dir/build.make:77: recipe for target 'src/common/CMakeFiles/common.dir/Banner.cpp.o' failed
make[2]: *** [src/common/CMakeFiles/common.dir/Banner.cpp.o] Error 1
CMakeFiles/Makefile2:1026: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Shauren** [comment]
Yes, all commits are tested by travis - see 3.3.5 here https://travis-ci.org/TrinityCore/TrinityCore/branches

**Comment by wplatform** [comment]
@Shauren  Can you help me to fix this issue?

**Comment by jackpoz** [comment]
First thing to do when having build issues: delete the build folder and rerun cmake

**Comment by wplatform** [comment]
Fixed. I hope you can understand me.  I am not c++ developer and not familiar with the build tools.  I have other some questions to ask enthusiastic people:
1. where is the changelog for code commits?
2. Some repack releases from TrinityCore status they have fix lots of the issue and add some feature.
It is credible? Dose these repacked releases better than compile the core from sourcecode?

Greetings from China.

**Comment by ratkosrb** [comment]
1. Read the commit history https://github.com/TrinityCore/TrinityCore/commits/3.3.5
2. You won't get help for repack questions here. Ask the repack author.
