### ISSUE TITLE
TrinityCore doesn't build

### ISSUE THREAD

**Issue by Lillecarl** [TrinityCore/TrinityCore#24160]
**Description:**

Core does not build with scripts enabled
https://travis-ci.org/TrinityCore/TrinityCore/builds/650900204#L1584

**Current behaviour:**

Core does not build with scripts enabled
https://travis-ci.org/TrinityCore/TrinityCore/builds/650900204#L1584

**Expected behaviour:**

Should build

**Steps to reproduce the problem:**

1. Look at travis

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
a81e88055a701adf5f88a54a81a822609cc47b46

**Operating system:** Linux

**Comment by Killyana** [comment]
Fixed here https://github.com/TrinityCore/TrinityCore/commit/854419becb05f24a2f8386295ae1b7eb1850cf92
