### ISSUE TITLE
gargoyle pet 3.3.5

### ISSUE THREAD

**Issue by V3nomAnc3r** [TrinityCore/TrinityCore#24169]
**Current behaviour:**
it should target ghoul target so you can switch targets / also takes more damage than intended (resilience doesnt work on it)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/c6caccc458ec229090b5f0f53d9e645021ae5fae

**Operating system:** CHANGEME OS
windows 10 64bit

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/16042
About the resilience:
https://wow.gamepedia.com/Patch_3.3.0: Pet Resilience: All player pets now get 100% of their master's resilience.
