### ISSUE TITLE
Pet / Hit raiting / Resilience 3.3.5

### ISSUE THREAD

**Issue by V3nomAnc3r** [TrinityCore/TrinityCore#24168]
**Current behaviour:**

About pets : pets seems to not get resiliece stats shared with heroes and they take much more damage than they should / also pets should get to their range spell then cast the spell when you cast it and the target is out of range

gargoyle pet : it should target ghoul target so you can switch targets / also takes more damage than intended (resilience doesnt work on it)

Ghoul : due to pets try attacking their targets from behind so if a player tries and counter that ghoul wont attack their target and wont stun them

pets and totems(eg: earthbind totem) seem to not share hit raiting with the hero and they miss alot

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/c6caccc458ec229090b5f0f53d9e645021ae5fae

**Operating system:** CHANGEME OS
Windows 10 64bit

**Comment by Killyana** [comment]
One Bug by issue, in this ticket there's 5.
