### ISSUE TITLE
bladestorm

### ISSUE THREAD

**Issue by V3nomAnc3r** [TrinityCore/TrinityCore#24166]
**Current behaviour:**
During bladestorm , when you cast frostbolt or ice chains on warrior they count as buff instead of debuff (you can spellsteal .eg) and when bladestorm finishes they wont slow the warrior until the buff duration is ended (you can cast those spells and refresh the buff)

CHANGEME Tell us what should happen instead.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/5f20715e2f38a6eb721f443df9e13c84ecb11fbb

**Operating system:** CHANGEME OS
Windows 10 64bit

**Comment by WannabeDevTwo** [comment]
Can confirm, also this happens with Blessing of Freedom(possibly other spells with similar mechanic too)

**Comment by Laintime** [comment]
confirm https://github.com/TrinityCore/TrinityCore/commit/92ac6ca0fee08d22fb6d49adb231250920d2043a

**Comment by Laintime** [comment]
HandleAuraModDecreaseSpeed not update else spell in target,why?
@Rushor have an idea?)

**Comment by Rushor** [comment]
this happens to a lot of spells recently. many debuffs counts as buff. 

f.ex 

brain link

```sql
-- Brain Link should be a debuff.
DELETE FROM `spell_custom_attr` WHERE `entry` IN (63802);
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES 
(63802, 0x00001000);

-- ID - 3150 Rabies - Must be debuff
DELETE FROM `spell_custom_attr` WHERE `entry` IN (3150);
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES 
(3150, 0x00001000|0x00002000|0x00004000);

```

this is indivisual adjustment, but it requires a general fix

**Comment by Jildor** [comment]
@Rushor but by default are negative, but seems by example frostbolt debuff, when you are in bladestorm is applied as buff, but maybe this is problem seems happens because:

```
ID - 116 Frostbolt (Rank 1)
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -40
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 33 (SPELL_AURA_MOD_DECREASE_SPEED), value = -40, misc = 0 (0), miscB = 0, periodic = 0
Effect Mechanic = 11 (MECHANIC_SNARE)

Effect 1: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 18 + Level * 0,50 to 21 + lvl * 0,50
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
Aura Id 118 (SPELL_AURA_MOD_HEALING_PCT), value = 0, misc = 127 (127), miscB = 0, periodic = 0
```

when frostbolt is applied and you aren't immune to MECHANIC_SNARE you get Effect 0 and Effect 2 auras and is counted as debuff, but when you are immune to MECHANIC_SNARE you don't get Effect 0 and only get Effect 2 and probably Effect 2 isn't counted as negative and appear possitive, but actually you don't have the negative effect snare applied, so maybe the second effect is 0 and shouldn't be applied

**Comment by illfated** [comment]
@Keader : Do you know if this is something that can be handled the same way some of the negative spells were fixed before, or is this issue happening to spells that used to be fixed earlier?

**Comment by Jildor** [comment]
No, the problem is the immunity, when bladestorm warrior get frostbolt, shouldn't get frostbolt aura, this happens because frostbolt have effect2 unused and remain on target

**Comment by Didr** [comment]
Another example, steps to reproduce (tested in 1181b63): 
1. Set up a mage and a paladin.
2. Make the paladin use the spell Hand of Freedom
3. Have the mage throw Frost Bolt
4. Have the mage use Spellsteal on the paladin
5. The mage should now have stolen the Frost Bolt debuff.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a770ad0476a32007a356c3539309f7a111893145

**Comment by micckkk** [comment]
> Another example, steps to reproduce (tested in [1181b63](https://github.com/TrinityCore/TrinityCore/commit/1181b636c0cec174367906808c999641ca7897fc)):
> 
> 1. Set up a mage and a paladin.
> 2. Make the paladin use the spell Hand of Freedom
> 3. Have the mage throw Frost Bolt
> 4. Have the mage use Spellsteal on the paladin
> 5. The mage should now have stolen the Frost Bolt debuff.
> 
> What should happen: Hand of Freedom should be stolen. Frost Bolt is a debuff and shouldn't be able to be a target of a Spellsteal.

confirmed,The Frostbolt slow debuff now appears in the boss's buff bar and can be dispelled.

**Comment by CraftedRO** [comment]
better open new issue about this

**Comment by CraftedRO** [comment]
> confirmed,The Frostbolt slow debuff now appears in the boss's buff bar and can be dispelled.

Both cases are invalid on current revision, so update you core before posting on closed issue.

**Comment by Aokromes** [comment]
lol 2020 core.
