### ISSUE TITLE
Core/GameObject: SpellFocus distance

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24177]
**Description:** GAMEOBJECT_TYPE_SPELL_FOCUS = 8 use data1: diameter (so radius*2) but according to tests in retail this is wrong data1= radius not diameter 

Proof:
![image](https://user-images.githubusercontent.com/6587064/74846147-4e92ca80-5330-11ea-97a1-067adc866f5c.png)
Gamobject Forge: 173064 with data1=10

Also we get many cases where even if we know the position of the spell focus the result doesn't much retail behavior and we end up hacking the distance.

**Branch(es):** Both

**TC rev. hash/commit:** rev. 3181a1c87fdarev. 3181a1c87fda

**Comment by Killyana** [comment]
Removing the /2 fix the issue:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Grids/Notifiers/GridNotifiers.h#L678

**Comment by Faq** [comment]
Then prolly need to review all distance spellhacks

**Comment by Killyana** [comment]
Yes
