### ISSUE TITLE
Hit raiting 3.3.5

### ISSUE THREAD

**Issue by V3nomAnc3r** [TrinityCore/TrinityCore#24170]
**Current behaviour:**
pets and totems(eg: earthbind totem) seem to not share hit raiting with the hero and they miss alot

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/c6caccc458ec229090b5f0f53d9e645021ae5fae

**Operating system:** CHANGEME OS
windows 10 64bit

**Comment by Killyana** [comment]
Dup: https://github.com/TrinityCore/TrinityCore/issues/5136
