### ISSUE TITLE
[master] Bad logic found for spell procs

### ISSUE THREAD

**Issue by Greviste** [TrinityCore/TrinityCore#24172]
**Description:**

I have located a chunk of code that seems to make Aura::GetProcEffectMask erroneously return 0, therefore breaking the logic of many, if not all, SPELL_AURA_PROC_TRIGGER_SPELL and similar spells.

**Current Code:**

In current revision of master branch (38cc011af0)
In file src/server/game/Spells/Auras/SpellAuras.cpp around line 1734

```cpp
    uint32 procEffectMask = 0;
    for (uint32 i = 0; i < MAX_SPELL_EFFECTS; ++i)
        if (procEffectMask & (1u << i))
            if ((procEntry->DisableEffectsMask & (1u << i)) || !GetEffect(i)->CheckEffectProc(aurApp, eventInfo))
                procEffectMask &= ~(1u << i);

    if (!procEffectMask)
        return 0;
```
`procEffectMask` is 0, so the `if(procEffectMask & /*Anything, actually*/)` will always be 0, and the function will always `return 0;`, ignoring everything after that line.

**Possible solution:**

I am not familiar enough with this project to make a pull request and be confident about it (also I don't even know how to do that), but the 3.3.5 branch seems to simply have the first line be `uint8 procEffectMask = aurApp->GetEffectMask();`.
Another possibility could be to use the older version of this section:
```cpp
    uint32 procEffectMask = 0;
    for (uint32 i = 0; i < MAX_SPELL_EFFECTS; ++i)
        if (aurApp->HasEffect(i))
            if (GetEffect(i)->CheckEffectProc(aurApp, eventInfo))
                procEffectMask |= 1u << i;
```
and follow it up with `procEffectMask &= ~procEntry->DisableEffectsMask;`.

I hope all this was helpfull!

**Branch(es):**

master

**Comment by Shauren** [comment]
The solution is found in 3.3.5 branch, variable should be initialized with `aurApp->GetEffectMask()` instead of 0
