### ISSUE TITLE
Correcting the Shutdown/Restart Notification Broadcasts ($5 Bounty)

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24174]
**Description:**

The shutdown/restart warning notification system uses the wrong timestamp format. It should be like: [SERVER] Shutdown in 15:00 and NOT like: [SERVER] Shutdown in 15 Minute(s)

So, the currently the shutdown/restart notifications currently use the universal timestamp format that is used for things like viewing the server uptime in .server info, which you can modify at: C:\Source\src\common\Utilities\Util.cpp

Which is not recommended as it breaks many things that use it. So there must be another way of changing it, maybe by modifying the World.cpp file in C:\Source\src\server\game\World\World.cpp

VIDEO EVIDENCE:
 https://www.youtube.com/watch?v=f6v_yRupABE
https://www.youtube.com/watch?v=z8za1_ozG-U

Can provide more if you think that is not enough.

**Current behaviour:**

So we are using the incorrect timestamp format to print the shutdown/restart notifications to chat.

**Expected behaviour:**

We should be using the correct timestamp format to print the shutdown/restart notifications to chat. E.g. for setting 15 minutes on the timer.

[SERVER] Shutdown in 15:00
[SERVER] Shutdown in 14:00
[SERVER] Shutdown in 13:00
[SERVER] Shutdown in 12:00
[SERVER] Shutdown in 11:00
[SERVER] Shutdown in 10:00
[SERVER] Shutdown in 9:00
[SERVER] Shutdown in 8:00
[SERVER] Shutdown in 7:00
[SERVER] Shutdown in 6:00
<-- When the timer gets down to 05:00 it will then start to display seconds as shown below. -->
[SERVER] Shutdown in 5:00
[SERVER] Shutdown in 4:45
[SERVER] Shutdown in 4:30
[SERVER] Shutdown in 4:15
[SERVER] Shutdown in 4:00
[SERVER] Shutdown in 3:45
[SERVER] Shutdown in 3:30
[SERVER] Shutdown in 3:15
[SERVER] Shutdown in 3:00
[SERVER] Shutdown in 2:45
[SERVER] Shutdown in 2:30
[SERVER] Shutdown in 2:15
[SERVER] Shutdown in 2:00
[SERVER] Shutdown in 1:45
[SERVER] Shutdown in 1:30
[SERVER] Shutdown in 1:15
[SERVER] Shutdown in 1:00
[SERVER] Shutdown in 0:45
[SERVER] Shutdown in 0:30
[SERVER] Shutdown in 0:15

**Steps to reproduce the problem:**

1. Login any character
2. Use either .server shutdown 900 or .server restart 900
3. See that the timestamp that is used is 15 Minute(s) and not 15:00

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 92ac6ca0fee0 2020-02-17 00:25:23 +0100 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**Operating system:** 

Windows Server 2016 Standard

**Comment by natrist** [comment]
You should provide more information on the expected behavior, like what kind of timer the messages seem to be on (15 seconds?).

**Comment by LordWaycrest** [comment]
> You should provide more information on the expected behavior, like what kind of timer the messages seem to be on (15 seconds?).

Fortunately the interval has already been done for us:

`    ///- Display a message every 12 hours, hours, 5 minutes, minute, 5 seconds and finally seconds
    if (show ||
        (m_ShutdownTimer < 5* MINUTE && (m_ShutdownTimer % 15) == 0) || // < 5 min; every 15 sec
        (m_ShutdownTimer < 15 * MINUTE && (m_ShutdownTimer % MINUTE) == 0) || // < 15 min ; every 1 min
        (m_ShutdownTimer < 30 * MINUTE && (m_ShutdownTimer % (5 * MINUTE)) == 0) || // < 30 min ; every 5 min
        (m_ShutdownTimer < 12 * HOUR && (m_ShutdownTimer % HOUR) == 0) || // < 12 h ; every 1 h
        (m_ShutdownTimer > 12 * HOUR && (m_ShutdownTimer % (12 * HOUR)) == 0)) // > 12 h ; every 12 h`

It is just the timestamp. :)

**Comment by P-Kito** [comment]
If it is only that, drop me a message on Discord  Kito#8621

We can talk about what you want and how we bring it into TrinityCore.

**Comment by LordWaycrest** [comment]
> If it is only that, drop me a message on Discord  Kito#8621
> We can talk about what you want and how we bring it into TrinityCore.

Hi Kito,

I have just updated the issue just as you commented. I hope this will give you a better understanding of how it should work.

**Comment by LordWaycrest** [comment]
@Killyana Hi, is it possible for you to add the bounty tag for me, please? :-)

**Comment by Killyana** [comment]
@ForesterDev you can claim the bounty.
