### ISSUE TITLE
Creating a Demon Hunter Crashes Worldserver

### ISSUE THREAD

**Issue by xXBentRealityXx** [TrinityCore/TrinityCore#24175]
**Description:**

The server crashes when you try to make a Demon Hunter and click the "Finish" button on the character creation screen.

**Current behaviour:**

Creating a Demon Hunter crashes worldserver.
Crashlog: https://gist.github.com/xXBentRealityXx/39a80929c8dcaa42e7e7d697cc1fe64a

**Expected behaviour:**

Creating a Demon Hunter should not crash worldserver.

**Steps to reproduce the problem:**

1. Make a Demon Hunter.

**Branch(es):**

master

**TC rev. hash/commit:** 

334cc3e23275

**Operating system:** Windows 10.0.18362

**Comment by xXBentRealityXx** [comment]
Seems to be related to 9aa5f625a617

**Comment by Ovahlord** [comment]
It's not. If the crashlog tells the truth it's either a player nullptr crash or a item nullptr crash. The lines that the crashlog provies are not related to skills in this case. I guess that's also what crashes my other skill PR. Something got screwed up here and it's not my fault

**Comment by MaxtorCoder** [comment]
It indeed is related to `Player::CanUseItem` debug that function to see where it crashes exactly.

**Comment by RaphtaliaYukii** [comment]
@MaxtorCoder I debug whole function and isn't the problem, the crashlog show it as last call but it's a false positive.

I still debugging whole process, it's related with start items handling, because if you comment the item creation process with CharStartOutfit.db2 you can enter in the world without any error or crash.

@xXBentRealityXx are close, I dont blame the commit of @Ovahlord but the item handling seems fine on my research, the pending parts of my debug are other things called on item creation like  spells, enchantments, skills...

If I found it I summit the PR, for now I'm still searching the real fault.

**Comment by xXBentRealityXx** [comment]
> It's not. If the crashlog tells the truth it's either a player nullptr crash or a item nullptr crash. The lines that the crashlog provides are not related to skills in this case. I guess that's also what crashes my other skill PR. Something got screwed up here and it's not my fault

Oddly enough when I reverted the commit I spoke of I was able to make a demon hunter. Maybe it was just a fluke though

**Comment by RaphtaliaYukii** [comment]
@xXBentRealityXx are fine, after revert 9aa5f62 the worldserver didn't crash and I can create a Demon Hunter without problems, so I confirm too that this commit causes the problem

**Comment by Shauren** [comment]
I will take a look at this later today

**Comment by RaphtaliaYukii** [comment]
@Shauren I gona test it, but can't understand why when I revert 9aa5f62 that are related with skills the crash dissapear and your commit just have a return if owner is null on CollectionMgr::CanAddAppearance.

I understand your commit and seems reasonable, on character create the characters isn't in world, then GetPlayer() always gona return null, but I didnt see the relation with 9aa5f62.

**Comment by xXBentRealityXx** [comment]
It is fixed, also fixed characters not equipping their start outfit and not being able to make allied races. Thanks Shauren!

**Comment by Shauren** [comment]
@RaphtaliaYukii there was never any relation to skills in the first place...

**Comment by RaphtaliaYukii** [comment]
@Shauren But reverting 9aa5f62 have the same effect that this fix, seems interesting

**Comment by Ovahlord** [comment]
Pretty sure that's just a bad coincidence. Reading crashlogs helps
