### ISSUE TITLE
Instance/Script: Lady Vashj Bridge Console

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24173]
**Description:** Lady Vashj Bridge Console mustn't be clickable until the 5 Serpentshrine Consoles are activated by players, every console is linked to a boss and become clickable once the boss is killed.

Lady Vashj Bridge Console: https://woehead.way-of-elendil.fr/?object=184568

Serpentshrine Consoles:
https://woehead.way-of-elendil.fr/?object=185114
https://woehead.way-of-elendil.fr/?object=185115
https://woehead.way-of-elendil.fr/?object=185116
https://woehead.way-of-elendil.fr/?object=185117
https://woehead.way-of-elendil.fr/?object=185118

Initial sql:
``` sql
UPDATE `gameobject_template_addon` SET `flags`=16 WHERE `entry`IN  (184568,185114,185115,185116,185117,185118);
```

**Steps to reproduce the problem:**

1. .go game 9361
2. Notice Lady Vashj Bridge Console i already clickable

**Branch(es):** both

**TC rev. hash/commit:** rev. 5f20715e2f38

**Comment by offl** [comment]
Patch 2.4.0 (2008-03-25): You may now fight Kael'thas Sunstrider and Lady Vashj without first killing all the other bosses in their respective dungeons.

If my memory serves me well consoles are unclickable after this patch even if you kill all bosses.

**Comment by Killyana** [comment]
Why Blizzard is destroying the game like this?

**Comment by offl** [comment]
I heard once that only 1-3%(?) of guilds(players?) reached Kel'thuzad in vanilla. Probably because of this
