### ISSUE TITLE
Core/GameObject: Gobs that despawns at the ends of an event doesn't despawn linked traps

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24183]
**Description:** GameObject like [Ribbon Pole] GUID: 51043 ID: 181605 used in Midsummer event doesn't despawn the linked trap when the event ends.

**Steps to reproduce the problem:**

1. .go game  51043 
2. .event start 1
3. .event stop 1
4. Notice the trap 181604 linked to the gob 181605  is still there

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d0cfa243a9da

**Comment by Killyana** [comment]
This happen also if you remove a gob spawn with .gob del

1. .gob add 186598 
2. gob del GUID

The green light is the trap and will not be removed with the main gob.

We fixed the despawn of linked traps if the gob despawns normally here: https://github.com/TrinityCore/TrinityCore/commit/750be73b9963ebcd4b823ec88b20af7cd819529b
But apparently if the gob is manually removed via gm command or via the game event despawn the case is different

**Comment by dr-j** [comment]
I think there maybe a issue with creatures linked to events too if a creature is despawned at end of an event it will still respawn after the event has finished noticed this with mounts for at scripts but had noticed it before

To reproduce with current scripts go to worlds end tavern and start the level 70 etc announce event which summons drums (creature) then start the concert which despawns the drums spawned by the announce event wait for event to end and wait 10 minutes you will notice drums respawn again when event is not running 

Seems there is no issue if creature is alive when event ends but if respawn timer has started creatures will still respawn after event has finished

**Comment by Killyana** [comment]
If I'm not wrong we fixed that for gobs
