### ISSUE TITLE
Spell/Item: Possibility to lose reagents if there's no free slot available

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24182]
**Description:**  if you transform https://woehead.way-of-elendil.fr/?item=36860 to 10 https://woehead.way-of-elendil.fr/?item=37702 with no free slot and with 1 to 9 https://woehead.way-of-elendil.fr/?item=37702 you will loose the 1 to 9 https://woehead.way-of-elendil.fr/?item=37702
https://imgur.com/a/ySoIeAr

**Steps to reproduce the problem:**

1. .add 37702 11 
2. transform 10 item=37702 into 1 Eternal Fire
3. make sure you have no free slot in your bags
4. Click the Eternal Fire
5. You will en up with 10 Crystallized Fire instead of 11

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d0cfa243a9da

**Comment by jackpoz** [comment]
What's the expected behavior ?

**Comment by Killyana** [comment]
No idea, but there's 2 possibility:
1- Error message no free slot
2- The Eternal Fire will be transformed into 10 Crystallized Fire in the same slot

**Comment by illfated** [comment]
Cosmetic detail regarding the ticket title: I know the issue ticket titles are not considered important, but I would simply like to point out that 2 of the words have actual separate meanings in English:
- loose: not fitting tightly, not fastened (in contrast to lose-lost-lost)
- regents: kings, queens and other high nobility (vs. reagents)

(Feel free to dismiss this comment, if you find it too nitpicky.)

**Comment by Faq** [comment]
Only which one from those 2 expected behaviors is blizzlike? :)

**Comment by illfated** [comment]
Most likely error message "No free space", but me remembering it like that could be a result of the Mandela effect.

**Comment by Killyana** [comment]
Probably "Error message no free slot" as if you put 10 instead of 1 to 9 Crystallized Fire, you will get this message, so it must be the same

**Comment by Faq** [comment]
SPELL_EFFECT_CREATE_ITEM ad result EQUIP_ERR_INVENTORY_FULL

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2a41755b589f215c14c85b1015e71534c1e91a98

**Comment by Faq** [comment]
Can reopen this with https://github.com/TrinityCore/TrinityCore/commit/18b36734f6ac235dbb7a37ba46d1c8d09d8171ab not working.

**Comment by Shauren** [comment]
No, its working as it was.
