### ISSUE TITLE
"We have the Power" quest

### ISSUE THREAD

**Issue by lactoseti** [TrinityCore/TrinityCore#24180]
**Description:**

On the "We Have the Power" quest Kathorn doesn't drop Kathorn's Power Cell.

**Current behaviour:**

On the "We Have the Power" quest Kathorn doesn't drop Kathorn's Power Cell.

**Expected behaviour:**

Should drop power cell like Durar does.

**Steps to reproduce the problem:**

1. Be on quest
2. Kill Kathorn
3. Doesn't drop item

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d0cfa243a9da

**Operating system:** Windows Server 2019

**Comment by dr-j** [comment]
Had noticed that drop chance for this item is not 100% chance before

**Comment by Aokromes** [comment]
https://www.wowhead.com/item=36857/durars-power-cell#comments
