### ISSUE TITLE
Core/AI: Units using SmartAI skeeps UPDATETYPE_CREATE_OBJECT2

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24184]
**Description:** UPDATETYPE_CREATE_OBJECT2 is used to play some animation like birth for ghouls when the unit is created, this works fine if the unis is not using SmartAI .
Example: 
Captive Ghoul=5685 if you .add temp 5685 the npc will play the birth animation.
If you update it with :
``` sql
UPDATE `creature_template` SET  AIName="SmartAI" WHERE `entry` IN (5685);
``` 
It will no longer play the birth animation.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. d0cfa243a9da

**Comment by dr-j** [comment]
It will if you add a just summoned event to cast it.  Just had to check how I scripted vegard as know this plays spawn animation just seems I added to cast the spell on just summoned.

Btw and that reminds me may have a few updates for the sacred and the corrupt to add the missing initial lights vengeance with holy visual and events to ensure objects despawn in event of player dieing will post later

**Comment by dr-j** [comment]
Oh ye and btw on clean tc will the two undead npcs attack the scourge npcs or not

**Comment by Killyana** [comment]
The birth animation is related to the model, not done by spell.

**Comment by akrom23** [comment]
The cause is `SmartAI::InitializeAI()`. The callstack:
```
	game.dll!Object::BuildCreateUpdateBlockForPlayer(UpdateData * data, Player * target)
 	game.dll!Object::SendUpdateToPlayer(Player * player)
 	game.dll!Player::UpdateVisibilityOf(WorldObject * target)
         ...
    	game.dll!WorldObject::UpdateObjectVisibility(bool __formal)
 	game.dll!Unit::UpdateObjectVisibility(bool forced)
 	game.dll!SmartAI::InitializeAI()
 	game.dll!Creature::AIM_Initialize(CreatureAI * ai)
 	game.dll!Creature::AddToWorld()
 	game.dll!Map::AddToMap<Creature>(Creature * obj)
```
`BuildCreateUpdateBlockForPlayer` is called from https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Maps/Map.cpp#L658 - and `m_isNewObject` is set just right below, when object is already created in client.

**Comment by Killyana** [comment]
@akrom23 Thanks for the tip.
