### ISSUE TITLE
[FEATURE REQUEST] [CONFIG OPTION] Make 59 minutes the maxmium a GM can set to issue a shutdown/restart notification

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24191]
**Description:**

So we made changes to the shutdown/restart notifications to use a decimal format instead. So we managed to achieve this however it appears we can not make it work out for anything over 59 minutes, so I had an idea maybe we could add an option in the worldserver.conf to make 59 minutes the maximum a GM can issue a shutdown/restart notice. Or we could just completely limit it to avoid users making issues thinking it is a bug.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 69231581e4f2 2020-02-22 21:31:37 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by Aokromes** [comment]
it's not blizzlike.

**Comment by LordWaycrest** [comment]
> it's not blizzlike.

What is not sorry?

**Comment by Aokromes** [comment]
on ptr i have seen >1h shutdowns.

**Comment by LordWaycrest** [comment]
> on ptr i have seen >1h shutdowns.

Can you remember the format it was in? We couldn't seem to make it work, could be interesting if you know.

**Comment by Killyana** [comment]
Sometime I Schedule a reboot the night to happen at 6 am, so we need that.

**Comment by LordWaycrest** [comment]
> Sometime I Schedule a reboot the night to happen at 6 am, so we need that.

I understand but this is a feature request that would go under Custom Server Options. The current format we use for anything over 59 minutes is not blizz-like but has still been allowed to merge with the repo.

**Comment by illfated** [comment]
Sorry for not being more clear. I was thinking that this could be more of a case for https://github.com/TrinityCore/TrinityCoreCustomChanges .

**Comment by LordWaycrest** [comment]
> Sorry for not being more clear. I was thinking that this could be more of a case for https://github.com/TrinityCore/TrinityCoreCustomChanges .

Is that a non-blizzlike repo?

**Comment by illfated** [comment]
As the name suggests, it is the TC repo for custom changes (non-blizzlike), so yes.

**Comment by LordWaycrest** [comment]
> As the name suggests, it is the TC repo for custom changes (non-blizzlike), so yes.

So if I were to have this change added to that I'd need to run a custom server?

**Comment by illfated** [comment]
It is more a separate branch than a repository, compared to the 3.3.5 branch. The branches master & 3.3.5 are meant to be blizzlike, so the TrinityCoreCustomChanges is meant for adding non-blizzlike custom options. That does not mean that you _have_ to run that core, except if you want to create a PR in that branch and test that the PR contents work as intended (even if not blizzlike).

Any custom changes accepted in that branch will only stay in that branch, so if you want to see the custom features in that branch, you would need to run that core to get it on your own server (or cherry-pick commits to your own local source to compile your own custom server).

**Comment by LordWaycrest** [comment]
Suppose the only way we're going to do this then is to fix the format - is not blizz-like yet it's been allowed to merge, I am confused.

**Comment by illfated** [comment]
@Aokromes : Got any suggestion for what a blizzlike approach to this feature request would be? What should the 60+ minutes countdown look like, if not the existing format?

**Comment by LordWaycrest** [comment]
> @Aokromes : Got any suggestion for what a blizzlike approach to this feature request would be? What should the 60+ minutes countdown look like, if not the existing format?

Sorry to be making a fuss, but when something is not done right it bugs me, especially in this project which I love

**Comment by illfated** [comment]
Have to wait and see if someone else can come up with a reasonable explanation on how to move on from here.

**Comment by jackpoz** [comment]
How about hh:mm:ss when > 59 minutes and mm:ss when <= 59 minutes ?

**Comment by Aokromes** [comment]
> Suppose the only way we're going to do this then is to fix the format - is not blizz-like yet it's been allowed to merge, I am confused.

because no one noticed that point before merge.

**Comment by DJScias** [comment]
Current blizzlike behaviour (can't speak about PTR) is that it only starts counting down half an hour before it goes down starting with `00:30`.

You can see it for yourself on the weekly maintenance nights, just stay online for it.

This logically means, unless we're using PTR as "blizzlike" (which even by blizzard standards isn't true, lots of PTR stuff doesn't stick anymore in normal nowadays), that as long as 30m works that for all things considered it's all working as "blizzlike" intended.

**Comment by ForesterDev** [comment]
@LordWaycrest please test all cases with PR changes
