### ISSUE TITLE
[Spell] Master's Call

### ISSUE THREAD

**Issue by warcrafte** [TrinityCore/TrinityCore#24194]
Bug Spell : [Master's Call] = If use, Pet Goes and you need again to use call pet spell.
 
Class Hunter

Branch(es): 3.3.5
TC rev. hash/commit:  https://github.com/TrinityCore/TrinityCore/commit/69231581e4f2d78384d3efe6f613be1b78e9d40f
Os: Windows 2020

**Comment by warcrafte** [comment]
ok ?!

**Comment by Killyana** [comment]
Provide the steps to reproduce the issue.

**Comment by warcrafte** [comment]
1. Call Pet
2. Master's Call
3. Pet Goes

**Comment by Killyana** [comment]
I cannot reproduce.

**Comment by warcrafte** [comment]
@Killyana 

What! Can You Tested [Master's Call] ?

**Comment by Killyana** [comment]
Work fine for me.
