### ISSUE TITLE
Wrong user password on login

### ISSUE THREAD

**Issue by n44ru** [TrinityCore/TrinityCore#24208]
**Description:**

I create and account and can’t login into the game because the auth console says: “User admin trying to authenticate with wrong password” but my password was “admin”

**Current behaviour:**

User is created with wrong password or the encryption algorithm has some problems in order to store or compare.

**Expected behaviour:**

I was able to login with a different version of the auth console of 1 month ago.

**Steps to reproduce the problem:**

1. Compile the last version of trinity core in Release or RelwithDebInfo.  
2. Create a simple user in the worldserver console.
3. Try to login into the game.

**Branch(es):**

3.3.5

**TC rev. hash/commit**

commit cbe765df7a75f61941583ab95ecaa153e198d3de

**Operating system:** Windows 10

**Comment by Jinnaix** [comment]
There is no commit/hash 'last'.

**Comment by MaxtorCoder** [comment]
And you cannot create an account via the AuthServer, the account has to be created via the WorldServer Console

**Comment by n44ru** [comment]
> There is no commit/hash 'last'.

Fixed

**Comment by n44ru** [comment]
> And you cannot create an account via the AuthServer, the account has to be created via the WorldServer Console

Fixed

**Comment by Aokromes** [comment]
what visual studio version you used to compile?

**Comment by n44ru** [comment]
> what visual studio version you used to compile?

Visual Studio 2017

**Comment by Shauren** [comment]
Upgrade to 2019

**Comment by jackpoz** [comment]
Which Visual Studio 2017 patch version ?

**Comment by Ovahlord** [comment]
I would almost say this is a client bug. It happens even on 434 bnet login from time to time. Not often but it does.

**Comment by jackpoz** [comment]
@Ovahlord old VS2017 versions create a bugged binay with C++17 enabled

**Comment by illfated** [comment]
@n44ru : See also https://github.com/TrinityCore/TrinityCore/pull/23868#issuecomment-582864160 for VS2017 version info.

**Comment by jackpoz** [comment]
Cmake should throw an error on old VS2017, it would be nice to know which version was used to check if we need to raise cmake requirements
