### ISSUE TITLE
DB/Creature: Remove wrong auras

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/TrinityCore#24204]
**Description:**
Remove auras from DB that are already handled by the script.

**Branch(es):**
3.3.5 and master

**TC rev. hash/commit:** 
TrinityCore rev. 3b0a89a2ea76+ 2020-02-26 21:06:39 +0100 (3.3.5 branch) (Win64, Debug, Dynamic) (worldserver-daemon)

**TDB version:** 335.20021

**Operating system:** Windows 10

**Suggested Fix:**
```sql
-- Unworty Initiate
UPDATE `creature_template_addon` SET `auras`='' WHERE `entry` IN (29519, 29520, 29565, 29566, 29567);
```

**Comment by illfated** [comment]
Thanks. Nice update. Glad you are keeping track of the changes. 👍
