### ISSUE TITLE
Oculus - Emerald Drake, Dream Funnel

### ISSUE THREAD

**Issue by wotlk-enthusiast** [TrinityCore/TrinityCore#24219]
**Description:**

In the instance The Oculus, The Emerald Drake's final ability Dream Funnel cannot target other drakes to heal them. 

**Current behaviour:**

Targeting a drake and channeling Dream Funnel causes both the negative and positive effect (the health drain and the health give) to affect the Emerald Drake.

**Expected behaviour:**

The negative effect should drain health from the Emerald Drake, and the health should be applied to the current player's target.

**Steps to reproduce the problem:**

1. Go into the Oculus with a friend
2. Kill the first boss, one of you take the Ruby Drake and the other take the Emerald Drake
3. Kill the next boss, to get the drakes' final abilities
4. Have the ruby drake engage a blue drake and take damage
5. Have the emerald drake attempt to heal him
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 94186a5e79d5 2020-02-29 20:00:29 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.71.0
Using MySQL version: 10.4.11-MariaDB
Using CMake version: 3.16.3
Compiled on: Linux 5.4.14-arch1-1
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/maps. Total size: 251987687 bytes
vmaps directory located in /home/trinity/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/trinity/data/mmaps. Total size: 1997886604 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20021

**Operating system:** Arch Linux

**Comment by Rushor** [comment]
Try this

```diff
diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index c8ae5e1a0b..24af841bfd 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -3421,6 +3421,7 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
                 case 61716: // Rabbit Costume
                 case 61734: // Noblegarden Bunny
                 case 62344: // Fists of Stone
+				ase 50344: // Dream Funnel
                 case 61819: // Manabonked! (item)
                 case 61834: // Manabonked! (minigob)
                     return true;
```

**Comment by Rushor** [comment]
works https://i.imgur.com/B94ejeV.jpg

**Comment by wotlk-enthusiast** [comment]
Re-opening this.  We just tested it out last night, and the behavior is the same.   It will drain health from the green drake, but the other drake is not healed.

Looking closer at the targeting, it seems that the player will target the friendly drake, but the pet (the green drake) will not.  Health is drained from the emerald drake as it should, but it is not applied to the target drake.

**Comment by Killyana** [comment]
No it works fine, I don't push commits without testing.

**Comment by Rushor** [comment]
on latest rev that all works good :)

**Comment by illfated** [comment]
@wotlk-enthusiast : Please note that sometimes changes don't appear to work the same way for all. Sometimes the old behaviour "lags" on your own computer, while working as intended on other computers.

You may want to check all forms of cache and similar on your server computer, in case it has kept some old settings in memory or temporary stores.

**Comment by wotlk-enthusiast** [comment]
Hmm, ok.  I'll try this and report back.  In the effort to being most helpful, that involves just removing the client cache folder after a successful build, right?  Nothing I have to clean out server-side?

**Comment by wotlk-enthusiast** [comment]
OK, the issue was that my cache was not cleaned out.  Killyana's commit worked great.  Thank you!
