### ISSUE TITLE
Crabs can jump in the water

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24213]
Description:
Crabs can jump in the water.

Expected behaviour:
![bug3](https://user-images.githubusercontent.com/3367999/75608312-6e4c9e80-5b39-11ea-884b-20daa8a06ed0.gif)

Steps to reproduce the problem:

1. set mmap.enablePathFinding = 1 in config file
2. .go xyz -3976.604004 -13035.621094 -1.926305 530

Branch(es):
3.3.5

TC rev. hash/commit:
cbe765d

Operating system:
CentOS

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21872
