### ISSUE TITLE
Shaman's totem will not disappear

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24212]
Description:
Shaman releases the totem, and then goes as far as possible (can also see the totem), waiting for the end of the totem countdown, the countdown will stay at 0 seconds, the totem will not disappear,  still valid, can be recycled, can attack.

Expected behaviour:
Totem can disappear correctly.

Steps to reproduce the problem:

- releases a totem
- goes as far as possible (can also see the totem)
- waiting for the end of the totem countdown

Branch(es):
3.3.5

TC rev. hash/commit:
cbe765d

Operating system:
CentOS

**Comment by Killyana** [comment]
The summon timer stops as the unit is not active, upon the player returning near the totem the timer continue.
So probably totems summoned by the player must be active..

**Comment by Ovahlord** [comment]
Grid unload issue. That's a wontfix unless totems will be marked as active which we don't want

**Comment by jackpoz** [comment]
Visiting all grids of pets/guardians/summons/totems of players should fix this issue

**Comment by Takenbacon** [comment]
Time to stop beating around the bush in my opinion and implement a sane object updater

**Comment by Ovahlord** [comment]
Then feel free to contribute

**Comment by Takenbacon** [comment]
@Ovahlord Gladly, it would however take some one to piece together my code as it will not directly port.

**Comment by jackpoz** [comment]
@Takenbacon got a branch/commit/diff with your object updater ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c68faf108edf50ae8a2ff4a341eff1e0d4269cbc

**Comment by jackpoz** [comment]
Note: the totem will still show as 0s until the player moves a bit (any direction is fine) to trigger visibility update (or object update or whatever) but the totem is no longer in world already anyway (it can be checked with .npc info).
No mana is returned in this case when using Totemic Recall (which is the correct behavior)
