### ISSUE TITLE
Oculus - Mounting Drakes with a Pet

### ISSUE THREAD

**Issue by wotlk-enthusiast** [TrinityCore/TrinityCore#24220]
**Description:**

Attempting to mount a drake with a warlock pet causes the player to not mount the drake.

**Current behaviour:**

Calling a drake with a pet in the field causes the player to not be able to mount the drake.  The drake will land on top of the player, and the player will not mount it.

**Expected behaviour:**

The player should mount the drake as usual.  Note: If you dismiss the pet first, then the drake works as normal

**Steps to reproduce the problem:**

1. Enter the Oculus as a warlock
2. Summon a pet
3. Kill the first boss
4. Talk to one of the prisoners to get an essence (I used bronze, didn't try the others)
5. Use the item to summon a drake
6. Observe the results.
7. Dismiss the pet
8. Use the item to summon a drake

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 94186a5e79d5 2020-02-29 20:00:29 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.71.0
Using MySQL version: 10.4.11-MariaDB
Using CMake version: 3.16.3
Compiled on: Linux 5.4.14-arch1-1
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/trinity/data/maps. Total size: 251987687 bytes
vmaps directory located in /home/trinity/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/trinity/data/mmaps. Total size: 1997886604 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20021

**Operating system:** Arch Linux

**Comment by dr-j** [comment]
warlock pet is summoned entity owned by player and so are drakes summoned in aoe and in most cases tc does not like player having more than one summoned entity at a time.

**Comment by Faq** [comment]
guessing, pet should be despawned?

**Comment by illfated** [comment]
The Oculus drakes should behave just as other vehicles, they should cause player to despawn class pets (I don't remember if non-combat pet should be).

**Comment by Rushor** [comment]
player->UnsummonPetTemporaryIfAny();
player->ResummonPetTemporaryUnSummonedIfAny();

can be used here

**Comment by sirikfoll** [comment]
I think this change is enough to fix the issue (not tested)
 <details>

```diff
diff --git a/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp b/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
index ef2db35299..c01be422e8 100644
--- a/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
+++ b/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
@@ -297,13 +297,13 @@ class npc_ruby_emerald_amber_drake : public CreatureScript
                 switch (me->GetEntry())
                 {
                     case NPC_RUBY_DRAKE_VEHICLE:
-                        me->CastSpell(summoner, SPELL_RIDE_RUBY_DRAKE_QUE);
+                        me->CastSpell(summoner, SPELL_RIDE_RUBY_DRAKE_QUE, true);
                         break;
                     case NPC_EMERALD_DRAKE_VEHICLE:
-                        me->CastSpell(summoner, SPELL_RIDE_EMERALD_DRAKE_QUE);
+                        me->CastSpell(summoner, SPELL_RIDE_EMERALD_DRAKE_QUE, true);
                         break;
                     case NPC_AMBER_DRAKE_VEHICLE:
-                        me->CastSpell(summoner, SPELL_RIDE_AMBER_DRAKE_QUE);
+                        me->CastSpell(summoner, SPELL_RIDE_AMBER_DRAKE_QUE, true);
                         break;
                     default:
                         return;

```
</details>

**Comment by Rushor** [comment]
@sirikfoll that works :) But the pet bar is not reloaded once the drake is unsummoned again. but i guess that is a different issue

**Comment by illfated** [comment]
Check if there are any unsolved pet bar issue tickets in the 3.3.5 source.
