### ISSUE TITLE
[master] Animations Characters and NPC's  bug in 8.3.0

### ISSUE THREAD

**Issue by cooler-SAI** [TrinityCore/TrinityCore#24222]
**Description:**
All characters and NPC's in the game have animation bug - NPC's and Characters animations don't work currently. Their animation looks freezed! 

**Current behaviour:**

create character mage or Rogue - cast Fireball and then Mage just stand and don't use combat animation, Rogue in stealthmode just stand too and doesn't use hide animation.
that's not all! NPC's animations Broken too in the world! Like Blacksmith NPC in Dwarf Quarter in Stormwind - looks funny))

**Expected behaviour:**

Animations must work currectly

**Steps to reproduce the problem:**

Here Few screenshots:
https://cdn.discordapp.com/attachments/679546655590449152/683414194246385885/unknown.png

https://cdn.discordapp.com/attachments/679546655590449152/683414576049553568/unknown.png

https://cdn.discordapp.com/attachments/679546655590449152/683703786719543312/unknown.png

Video:

https://yadi.sk/d/3kEJ4E5CAB0acw

**Branch(es):**

master

**TC rev. hash/commit:** 

last TC rev  2032ade

**Operating system:** Windows 10

**Comment by Daribon** [comment]
Can confirm, affects all races.
