### ISSUE TITLE
SAI/Movement: Evade after a waypoint

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24226]
**Description:** if you call an evade after a waypoints (via SAI) to reset the creature to spawn position it will no longer work, the npc will reset instead at the last way point. (no combat involved here)

I don't know if we need to update all SAI scripts or if this can be fix directly in the core.
Example: https://github.com/TrinityCore/TrinityCore/issues/23917 
This npc will use a waypoint, after a while an evade is called (the waypoint is finish) but instead returning to the home position, it will stay at the last point of the waypoint.
``` sql 
SELECT *  FROM `smart_scripts` WHERE entryorguid IN (-102327);
```
**Steps to reproduce the problem:**

1. Do the quest https://www.wowhead.com/quest=12140/all-hail-roanauk
2. Notice at the end of the event Taunka Soldiers didn't return to their initial position
3. even using .npc evade

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. ce449f6b5332

**Comment by jackpoz** [comment]
What about when a Creature engages combat during a waypoint path ? In this case evade should return to last waypoint.

**Comment by Killyana** [comment]
The old behavior for creatures using waypoints (not waypoint_data) was:
1- If the creature never enter combat during the wp it will evade to the spawn position
2- If it evades after a combat it will evade to the position where the combat starts (every combat start will update the home position)
But after the movement rewrite all waypoints "types" were unified and now have the same behaviors, so scripts that use this differences are no longer working properly (same for the waypoints pause via the gossip)

**Comment by Killyana** [comment]
We can add 2 params to the action:
Param1: 0/1 (return to spawn pos/return to the current home pos)
Param2: 0/1 (run/walk)

**Comment by Rushor** [comment]
Why has this movement rewrite been merged without SAI tests actually?

**Comment by Rushor** [comment]
this also happens if you use move point action. seems like after reaching a specific point, the new reached position is set to the homeposition

**Comment by Killyana** [comment]
I cannot reproduce the issue with move_to_pos
.tele test
.npc add 321
``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE entry =321;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (321) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(321, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, -2.335, -0.249, -144.7, 0.087270, '');

**Comment by Rushor** [comment]
this helped

```diff
diff --git a/src/server/game/AI/SmartScripts/SmartScript.cpp b/src/server/game/AI/SmartScripts/SmartScript.cpp
index 2ad51ac1dc..976605bd36 100644
--- a/src/server/game/AI/SmartScripts/SmartScript.cpp
+++ b/src/server/game/AI/SmartScripts/SmartScript.cpp
@@ -809,6 +809,8 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                 break;
 
             me->AI()->EnterEvadeMode();
+            if (e.action.evade.ToHomePosition)
+                me->GetMotionMaster()->MoveTargetedHome();
             TC_LOG_DEBUG("scripts.ai", "SmartScript::ProcessAction:: SMART_ACTION_EVADE: Creature %u EnterEvadeMode", me->GetGUID().GetCounter());
             break;
         }
diff --git a/src/server/game/AI/SmartScripts/SmartScriptMgr.h b/src/server/game/AI/SmartScripts/SmartScriptMgr.h
index 4f410322b3..c5d39f8763 100644
--- a/src/server/game/AI/SmartScripts/SmartScriptMgr.h
+++ b/src/server/game/AI/SmartScripts/SmartScriptMgr.h
@@ -1184,6 +1184,11 @@ struct SmartAction
             uint32 HomedisablePathfinding;
         } MoveToHomePos;
 
+        struct
+        {
+            uint32 ToHomePosition;
+        } evade;
+
         //! Note for any new future actions
         //! All parameters must have type uint32
 ```

anyway - the old system worked fine. better restore that function? :o

**Comment by Faq** [comment]
@Treeston you see how this could be handled differently?

**Comment by jackpoz** [comment]
@Rushor why doesn't EnterEvadeMode() make the creature go home already ? It's called in the line before

**Comment by jackpoz** [comment]
@Rushor why doesn't EnterEvadeMode() make the creature go home already ? It's called in the line before

**Comment by Rushor** [comment]
I gonna check. As far as in saw, the function had nö changes since ages

**Comment by Rushor** [comment]
@jackpoz 

tue it calls EnterEvadeMode in SmartAI.

EnterEvadeMode  calls this:

```
void CreatureAI::EnterEvadeMode(EvadeReason why)
{
    if (!_EnterEvadeMode(why))
        return;

    TC_LOG_DEBUG("scripts.ai", "CreatureAI::EnterEvadeMode: entering evade mode (why: %u) (%s)", why, me->GetGUID().ToString().c_str());

    if (!me->GetVehicle()) // otherwise me will be in evade mode forever
    {
        if (Unit* owner = me->GetCharmerOrOwner())
        {
            me->GetMotionMaster()->Clear();
            me->GetMotionMaster()->MoveFollow(owner, PET_FOLLOW_DIST, me->GetFollowAngle());
        }
        else
        {
            // Required to prevent attacking creatures that are evading and cause them to reenter combat
            // Does not apply to MoveFollow
            me->AddUnitState(UNIT_STATE_EVADE);
            me->GetMotionMaster()->MoveTargetedHome();
        }
    }

    Reset();
}
```

So MoveTargetedHome is there only called if it does not get a GetCharmerOrOwner() and is not a vehicle. So it should actually call the MoveTargetedHome but it does not.

What i also see. It calls Reset();

Maybe the Reset(); prevents the MoveTargetedHome  or overrites it?

**Comment by Rushor** [comment]
update for that quest

```sql
UPDATE `smart_scripts` SET `action_param1`='1' WHERE  `entryorguid` IN (26379, -102329, -102341, -102330, -102328, -102326, -102333, -102327) AND action_type=24;
```

okay edit:

it still does not work with wp movement, only move point

**Comment by Killyana** [comment]
@Rushor make 0 the value for home position, to avoid updating scripts, also if you can add walk/run  in param2.

**Comment by jackpoz** [comment]
@Rushor did you get a callstack that calls that ? Shouldn't it call SmartAI::EnterEvadeMode(..) instead ?

**Comment by Rushor** [comment]
that is indeed a good question. i will try SmartAI::EnterEvadeMode

**Comment by Rushor** [comment]
okay i tried with

ENSURE_AI(SmartAI, me->AI())->EnterEvadeMode();

but it also does not let the creature run to to the homeposition. we must change the way how MoveTargetedHome / SetHomePosition is stored and updated

**Comment by jackpoz** [comment]
is this issue still happening ?

**Comment by offl** [comment]
Yes

**Comment by jackpoz** [comment]
The "move to respawn position" bit has been fixed. Please open another issue for the run/walk part.
