### ISSUE TITLE
[3.3.5] Core/Item: Master Looter Item visibility problem

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24230]
**Description:**

Master Looter cant see items that provide Quests.
Original Issue #16653
PR and commit that should have fixed this issue : #23410 -> e6ad9b1

[Image 1](https://cdn.discordapp.com/attachments/682994561177747515/683959390340251659/WoWScrnShot_030220_094911.jpg)

[Image 2](https://cdn.discordapp.com/attachments/682994561177747515/683959394412920870/WoWScrnShot_030220_094918.jpg)

**Current behaviour:**

ML cant see Quest Items.

**Expected behaviour:**

ML should be able to see and assign Quest Items.

**Steps to reproduce the problem:**

Create a Raid with at least 2 Characters.
Set Lootrules to ML.
.go c 49678
kill and loot

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ce449f6

**Operating system:** 

Windows 10

**Comment by Killyana** [comment]
This will fix the issue, but not sure it the correct way:
``` diff
diff --git a/src/server/game/Loot/Loot.cpp b/src/server/game/Loot/Loot.cpp
index 3cd0762b27..89fd613a64 100644
--- a/src/server/game/Loot/Loot.cpp
+++ b/src/server/game/Loot/Loot.cpp
@@ -75,7 +75,7 @@ bool LootItem::AllowedForPlayer(Player const* player, bool isGivenByMasterLooter
     if (!isGivenByMasterLooter && player->GetGroup() && player->GetGroup()->GetMasterLooterGuid() == player->GetGUID())
     {
         // check quest requirements
-        if (!pProto->HasFlag(ITEM_FLAGS_CU_IGNORE_QUEST_STATUS) && (needs_quest || pProto->StartQuest))
+        if (!pProto->HasFlag(ITEM_FLAGS_CU_IGNORE_QUEST_STATUS) && (needs_quest))
             return false;
 
         return true;

**Comment by sanctum32** [comment]
what you need to do, is just add 
```
            if (player->HasQuestForItem(itemid))
                return true;
```

overall:

```
    // Master looter can see certain items even if the character can't loot them
    if (!isGivenByMasterLooter && player->GetGroup() && player->GetGroup()->GetMasterLooterGuid() == player->GetGUID())
    {
        // check quest requirements
        if (!(pProto->FlagsCu & ITEM_FLAGS_CU_IGNORE_QUEST_STATUS) && (needs_quest || pProto->StartQuest))
        {
            if (player->HasQuestForItem(itemid))
                return true;

            return false;
        }
        return true;
    }
```

**Comment by jjo72ddd** [comment]
the problem is still relevant for 400e291

**Comment by joshwhedon** [comment]
At first glance your fix seems to be working @sanctum32

**Comment by Jildor** [comment]
I think the @sanctum32 fix is not entirely correct because for example:
Onyxia case:
Player A (Masterlooter) has the head of onyxia and quest, so has queststatus != None
Raid kill onyxia and Player A can't see onyxia's head, therefore cannot give head to anyone

Maybe we should check all group members in that Masterlooter check and check if any member of the group is able to get the item

**Comment by illfated** [comment]
Looks like a logical solution to me, to make sure that all members are checked for eligibility.

**Comment by natnat201193** [comment]
All members who are possibly eligible for loot should be checked every time.

**Comment by w5860363** [comment]
@Jildor In a blizzard, even players who can't scavenge can pick up from corpses!

**Comment by jackpoz** [comment]
shouldn't ```player->GetGroup() && player->GetGroup()->GetMasterLooterGuid() == player->GetGUID()``` just always show every item to the master looter and then just get an error if the destination player cannot receive the item ?

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/26584 , could anyone please test it ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8d92f6f2b483dffa7127614de3c41f3f596743fb
