### ISSUE TITLE
Issues : 21255 ! Not worked ! Spells ignoring textures

### ISSUE THREAD

**Issue by unleashwow** [TrinityCore/TrinityCore#24231]
Description: Fear movement is broken. Blink Destination is broken. Shadow step destination is broken. Charge/Intersept destination is broken

Current behaviour: Players affected by fear, just ignore map. They start fly, enter in textures, a real mess. Maybe MMaps/Vmaps issue?
Same to Blink, Shadow step, Charge/Intersept.

Expected behaviour: Players affected by fear should run around like a normal player. Players teleported by Blink should not drop of map ( same in Shadow Step/Charge )

Steps to reproduce the problem:

    I tested in Warsong map
    just add Fear aura in some place, and see how broken it is (.aura 5782)

Check: https://youtu.be/-V0H3wx1TU8 (fear)
Check2: https://youtu.be/Z75TuzmaKj4 (blink)

PS: Vmaps/MMaps is active

Edit: Bug intoduced by e42903e

Branch(es): 3.3.5

TC rev. hash/commit: ccf0807

**Comment by unleashwow** [comment]
@jackpoz @Killyana

**Comment by Aokromes** [comment]
2 years old core? you just be jocking.

**Comment by unleashwow** [comment]
No, i'm with the last rev of trinitycore. With fresh Maps / Vmaps / MMaps

**Comment by Aokromes** [comment]
that's not what you linked: https://i.imgur.com/V5Rzl42.png

**Comment by Killyana** [comment]
Videos are the ones done by Keader in 2018

**Comment by unleashwow** [comment]
Yes but the problem is same. Do you want screen ?

**Comment by unleashwow** [comment]
Thanks for your answer.

**Comment by Killyana** [comment]
No, I need steps to reproduce an issue.

**Comment by unleashwow** [comment]
I'm using mage transfer, and I'm off-map. In all map

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75702937-bfce6800-5cb6-11ea-8d34-88fe0b7974f2.png)

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75703181-3d927380-5cb7-11ea-9117-805dc36af16b.png)

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75703226-56028e00-5cb7-11ea-8ade-c0356adfe8a4.png)

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75703452-cc9f8b80-5cb7-11ea-8e47-6fcdd94c86fc.png)

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75703519-ed67e100-5cb7-11ea-84fa-39bf428e3184.png)
![image](https://user-images.githubusercontent.com/61706297/75703540-f5c01c00-5cb7-11ea-9409-d9ca8da6d3b7.png)

**Comment by unleashwow** [comment]
Step 1 : .go xyz 16226.409180 16256.180664 13.170687 5.653400 1
Step 2 : Use the spellID 1953 (blink)

You are now off-map !

**Comment by unleashwow** [comment]
@Killyana you have the steps  :)

**Comment by unleashwow** [comment]
@Aokromes You help me or you taunt me ?

**Comment by Jinnaix** [comment]
The coordinates you are providing lets you already fall trough the map.
Cant replicate.
I guess you have a modified fork and you didnt pull the correct changes.

Do a  .server debug screenshot please.

Otherwise, cant replicate.

**Comment by unleashwow** [comment]
![image](https://user-images.githubusercontent.com/61706297/75704219-3ec4a000-5cb9-11ea-870d-bba01213457e.png)

**Comment by Exitare** [comment]
2019 core. your core is outdated

**Comment by Ovahlord** [comment]
Dude. Update your core. These issues are long fixed already.

**Comment by unleashwow** [comment]
Okay thanks for your answer, i update my core now.
