### ISSUE TITLE
Dungeons: Blackrock Depths Arena

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#24239]
Description:

In the arena in BRD the boss does not spawn.

Current behaviour:

When the door opens where the random boss is suppose to spawn it does not spawn

Expected behaviour:

After activating the Arena and killing the adds one of the bosses should spawn

Steps to reproduce the problem:

Start the Arena event

Any other useful links here:
-Error 404 not found

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2b14b720da2bc38c84f373cb3ff4bcc24c1ddcf0

**Operating system:** CHANGEME OS

windows 10 64 bit

**Comment by Killyana** [comment]
I made three tests and a final boss always spawn.

**Comment by VincentVanclef** [comment]
odd ill try re-insert TDB and retry
