### ISSUE TITLE
[Quest] Absent Minded Prospector

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#24237]
Description:

"The Absent Minded Prospector" Quest Bug

Current behaviour:

The npc required to escort will run back to the beginning before completing the quest and will stand still as if you failed the quest but without any death to the npc and with the quest still active not set as "failed"

Expected behaviour:

The npc should follow you all through the place and mark the quest as "completed" when he has finished before running back to the beginning.

Steps to reproduce the problem:

Take the Quest
Follow the npc through the quest

Any other useful links here:
https://www.youtube.com/watch?v=UeNbdd8UBMA

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2b14b720da2bc38c84f373cb3ff4bcc24c1ddcf0

**Operating system:** CHANGEME OS
windows 10 64bit

**Comment by Killyana** [comment]
The npc use a cpp script: npc_prospector_remtravel

**Comment by Killyana** [comment]
The quest works fine

**Comment by illfated** [comment]
@VincentVanclef : if you check the last 4 days in the list of commits (after your commit hash date), you may find one or more commits resolving your issue.
