### ISSUE TITLE
[3.3.5] Boss/Script/loot Vazruden the Herald

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24234]
Description:
Vazruden the Herald in Hellfire Ramparts should not fly away when he is beaten. He removes the “fights” from himself and flies away (sometimes in textures, he cannot be reached), and also begins to heal himself (which makes it impossible to kill him). He must also have loot. (I tried to kill him with .damage, there was no loot in it)
https://www.wowhead.com/npc=17307/vazruden-the-herald
https://www.wowhead.com/hellfire-ramparts

Branch(es): 3.3.5

TDB version: 335.20021

Operating system: Ubuntu 18.04

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21504

**Comment by jjo72ddd** [comment]
> 
> 
> Dup #21504

Sorry
I will try to help with this bug
