### ISSUE TITLE
Quest: "High Commander Halford Wyrmbane" problem

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24244]
Description:
There is no flying mounts take players to their destinations.

Expected behaviour:
Snowstorm can take players to their destinations.

Steps to reproduce the problem:

1. .character level 75
2. .go xyz 3506.07 1990.42 65.2658 571
3. .quest add 12171
4. complete the quest.

Branch(es):
3.3.5

TC rev. hash/commit:
d1080af8db63c78986a7fcc94fcfb2fdfe817734

Operating system:
CentOS

**Comment by illfated** [comment]
Thank you for reporting the issue. I am also happy to see that the solution was relatively simple.

**Comment by aleigood** [comment]
There should be a gossip menu here, ‘I need to get to Wintergarde Keep fast! broadcast_text ID=26697;

**Comment by Killyana** [comment]
Nop: https://www.youtube.com/watch?v=qyfhdocFEi0
You're probably talking about: https://www.youtube.com/watch?v=MuEOLklvbAs but it's already scripted
