### ISSUE TITLE
Core/AI/Movement: Charmed npcs must be able to start a waypoint or any non controlled movement

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24242]
**Description:** After https://github.com/TrinityCore/TrinityCore/commit/ddf2f60c1317f0ce728d5894064f51251cf71c72 if a creature is summoned and get (UNIT_FLAG_POSSESSED (0x1000000) it will not be able to start a waypoint.
Example:
https://www.wowhead.com/quest=12671/reconnaissance-flight
https://www.wowhead.com/quest=12665/i-sense-a-disturbance
https://www.wowhead.com/quest=12536/a-rough-ride
https://www.wowhead.com/quest=12910/sniffing-out-the-perpetrator

**Current behaviour:** Npcs with UNIT_FLAG_POSSESSED cannot start a waypoint

**Expected behaviour:** Npcs with UNIT_FLAG_POSSESSED must be able to start a waypoint

**Steps to reproduce the problem:**

1. .cast 51258
2. The Aligator must start a waypoint and not being controllable

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 16ccc1762131

**Comment by Killyana** [comment]
I'm not 100% sure but maybe only vehicle mut be able to do that.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/49e77d7c9e4c39296536cd0b2d427d047e762f46
