### ISSUE TITLE
The problem of creature height

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24247]
Description:
.go xyz 3781.866455 2105.825195 93.348778 571
creature 26483 the height seen is not the actual height.
creature 26607 walking in the air.
.go xyz 3320.372803 2610.629639 66.798195 571
creature 26276 walking in the air.

Branch(es):
3.3.5

TC rev. hash/commit:
d1080af

Operating system:
CentOS

**Comment by Killyana** [comment]
First case: https://github.com/TrinityCore/TrinityCore/issues/6148
Second case: https://github.com/TrinityCore/TrinityCore/issues/19495
