### ISSUE TITLE
Quest: "Finding the Phylactery" the Dusk can't take players to the destination

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24243]
Description:
The horse will only stand where it is.

Expected behaviour:
Dusk can take players to the destination.

Steps to reproduce the problem:
1. .quest add 11956
2. .go xyz 3109.335205 3817.886719 23.588575 571
3. Mount the horse.

Branch(es):
3.3.5

TC rev. hash/commit:
d1080af8db63c78986a7fcc94fcfb2fdfe817734

Operating system:
CentOS

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/24242

**Comment by Killyana** [comment]
``` sql
UPDATE `smart_scripts` SET `event_type`=27 WHERE `entryorguid`=28182 AND `source_type`=0 AND `id` IN (0, 2);

**Comment by jackpoz** [comment]
the "set react state" can be kept on the "just summoned" event
