### ISSUE TITLE
Dungenon: shadowfang keep

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#24240]
Description: Shadowfang keep dungeon has a bug where the npc you talk to after the first fight does not have the dialog option, and does not walk to unlock the door.

Current behaviour: Sorcerer Ashcrombe does not have the correct text option once his cage is unlocked that would make him walk upstairs and unlock the courtyard door.

Expected behaviour: when clicking on him it should give an option to free him and an interaction will commence the npc will then say "Follow me and I'll open the courtyard door for you. I have just the spell to get this door open." as he unlocks the door allowing players to continue the dungeon

Steps to reproduce the problem: Join SFK and kill the first boss then open the cell and talk to ashcrombe

Any other useful links here:
picture on issue: https://imgur.com/a/IUwWSWd

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/2b14b720da2bc38c84f373cb3ff4bcc24c1ddcf0

**Operating system:** CHANGEME OS
windows 10 64 bit

**Comment by Aokromes** [comment]
at least horde version works on ce449f6b5332

**Comment by Killyana** [comment]
I tested both Horde and alliance and both work just fine

**Comment by Aokromes** [comment]
and aliance version too.

https://mega.nz/#!NjRFwKTC!FzH2SxpXqVs7YR3Z2YGbzwVwmsQztYzdKcOLygIu8r8

**Comment by illfated** [comment]
@VincentVanclef : Please update your core to at least 2020-03-03.

**Comment by Aokromes** [comment]
@illfated illfated jump irc xd
