### ISSUE TITLE
Spell [Thunderstorm]

### ISSUE THREAD

**Issue by warcrafte** [TrinityCore/TrinityCore#24252]
Spell [Thunderstorm] ,  knocking the back 20 yards / buged.

Does not throw back!

Branch(es): 3.3.5
TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/c6caccc458ec229090b5f0f53d9e645021ae5fae

**Comment by illfated** [comment]
Possibly a duplicate of issue ticket #18180 **Can't knock-back stunned targets.**

**Comment by Killyana** [comment]
Works just fine
