### ISSUE TITLE
SAI: SMART_ACTION_OVERRIDE_LIGHT

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24250]
**Description:** The action don't seems to work at least with https://github.com/TrinityCore/TrinityCore/issues/24241#issuecomment-595370944

Also we must be able to reset the previous light via the value=0

This is from the quest https://www.wowhead.com/quest=13631/all-is-well-that-ends-well you can see the current light is 1802 it was changed to 1773 during the event for 20 secs then reset back to 1802 via Target Light.dbc entry: 0

If we use the value 0 to reset the light we get: SmartAIMgr: Entry 1612802 SourceType 9 Event 31 Action 138 uses non-existent overrideLightId 0, skipped.

``` 
ServerToClient: SMSG_OVERRIDE_LIGHT (0x4225) LENGTH: 12 ConnIdx: 2 TIME: 06/24/2012 01:29:21.186 Number: 79988
Current Light.dbc entry: 1802
Target Light.dbc entry: 1773
Fade IN TIME: 1000

ServerToClient: SMSG_OVERRIDE_LIGHT (0x4225) LENGTH: 12 ConnIdx: 2 TIME: 06/24/2012 01:29:41.560 Number: 80771
Current Light.dbc entry: 1802
Target Light.dbc entry: 0
Fade IN TIME: 5000
``` 
1. use the sql  here https://github.com/TrinityCore/TrinityCore/issues/24241#issuecomment-595370944
2. .add 46052 and click it to start the quest
3. notice during the event th light will not change

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by Shauren** [comment]
The action works. What does not work is setting light specifically in dalaran

**Comment by sanctum32** [comment]
You must override default light id for dalaran, i left comment previously mentioning this but idk, it was ignored

**Comment by sanctum32** [comment]
```
static uint32 GetDefaultZoneLight(uint32 zoneId)
{
    switch (zoneId)
    {
    // Global zones
    case 4395:  // Dalaran
        return 1802;
    // Dungeons
    case 4812:  // Icecrown Citadel - The Frozen Throne
        return 2488;
    case 4500:  // Eye of the Eternity
        return 1773;
    }

    return 0;
}
```

**Comment by sanctum32** [comment]
Nevermind, i'll open pull request for this
