### ISSUE TITLE
Creature "Skettis Surger" cannot move

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24265]
Description:
Skettis Surger(entry: 21728) After being attacked, the creature can only stand in place and cannot move forward.

Steps to reproduce the problem:
.character level 70
.go xyz -4041.854004 3489.303223 278.474457 530

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Kitzunu** [comment]
I can confirm this, however it does only happen when they first cast "Water Bolt" ID = 32011

How to reproduce:
1. .damage 100 (When in range for Water Bolt)
2. See how the npc is stuck in place after.

3. .damage 100 when you are out of range for the NPC to cast Water bolt.
2. see how the npc moves towards you properly (This time not casting the water bolt though)

**Comment by Kitzunu** [comment]
```SQL
DELETE FROM `smart_scripts` WHERE `entryorguid` = 21728 AND `id` = 0;
```
seems to fix the issue

**Comment by dr-j** [comment]
Think Crazed Water Spirit in Zul'drak has similar issue
