### ISSUE TITLE
Quest "Rallying the Troops"

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24261]
Description:
Quest "Rallying the Troops"
Use the Shard of the Earth to rally the Grizzly Hills Giants fighting in the Boulder Hills - does not count. The quest cannot be completed because I cannot rally Grizzly Hills Giants Rallied (5)

Iron Rune Avengers Slain (5) - is work, i can kill.

https://www.wowhead.com/npc=26261/grizzly-hills-giant
https://www.wowhead.com/quest=12070/rallying-the-troops

Branch(es): 3.3.5

TDB:  335.20021
Ubuntu 18.04

**Comment by illfated** [comment]
Would be nice to know which commit rev. you are running, but I suppose the TDB version is sort of a step in that direction.

**Comment by dr-j** [comment]
One thing to note here if you are trying to use the quest item on the giants which are throwing trees and rocks down ravine it is not intended to work on these npcs as it does not on retail you have to use it on the ones which are fighting the grizzly hills giants nearby

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16561

**Comment by jjo72ddd** [comment]
Hello!
I checked it at all.
[Video here](https://mega.nz/#!1AwxxCQY!zbtT6k6_ErBO2IBYYZRU3bjKbIJlVVyQBpI-bUJcXCM)

**Comment by jjo72ddd** [comment]
> 
> 
> One thing to note here if you are trying to use the quest item on the giants which are throwing trees and rocks down ravine it is not intended to work on these npcs as it does not on retail you have to use it on the ones which are fighting the other giants nearby

I used it on all the giants
[Video here](https://mega.nz/#!EZgzxSAA!xTUYwh8Xtu1e3LYQfJEwVFrbGRWq63QBlWXkhMt2AF8)

**Comment by dr-j** [comment]
Apply and that will fix the credit issue theres still issue of slow respawn time I believe though which is why was never commited.
~~~sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=26261 AND `source_type`=0 AND `id` IN(0,4,5);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(26261, 0, 0, 4, 8, 0, 100, 1, 47394, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Store Target'),
(26261, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 80, 2626100, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Run Script');
UPDATE `smart_scripts` SET `target_type`=12, `target_param1`=1 WHERE  `entryorguid`=2626100 AND `source_type`=9 AND `id`=0 AND `link`=0;

**Comment by jjo72ddd** [comment]
> Apply and that will fix the credit issue theres still issue of slow respawn time I believe though which is why was never commited.
> 
> ```sql
> DELETE FROM `smart_scripts` WHERE `entryorguid`=26261 AND `source_type`=0 AND `id` IN(0,4,5);
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> (26261, 0, 0, 4, 8, 0, 100, 1, 47394, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Store Target'),
> (26261, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 80, 2626100, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Run Script');
> UPDATE `smart_scripts` SET `target_type`=12, `target_param1`=1 WHERE  `entryorguid`=2626100 AND `source_type`=9 AND `id`=0 AND `link`=0;
> ```

Please tell me what should I do to fix this quest?

**Comment by illfated** [comment]
One of the challenges is that it is usually easier to hackfix the solution than to find the correct and blizzlike solution. If the correct solution had been easy to find, it would most likely have been suggested already.

**Comment by jjo72ddd** [comment]
I know that this is a very important quest. If I can help with something in solving this problem, tell me what.

**Comment by jjo72ddd** [comment]
> 
> 
> Apply and that will fix the credit issue theres still issue of slow respawn time I believe though which is why was never commited.
> 
> ```sql
> DELETE FROM `smart_scripts` WHERE `entryorguid`=26261 AND `source_type`=0 AND `id` IN(0,4,5);
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
> (26261, 0, 0, 4, 8, 0, 100, 1, 47394, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Store Target'),
> (26261, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 80, 2626100, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Grizzly Hills Giant - On Spellhit \'Kurun\'s Blessing\' - Run Script');
> UPDATE `smart_scripts` SET `target_type`=12, `target_param1`=1 WHERE  `entryorguid`=2626100 AND `source_type`=9 AND `id`=0 AND `link`=0;
> ```

Has anyone checked this out? It works?

**Comment by illfated** [comment]
This issue ticket should have been labeled **[Invalid-Duplicate]** to make it clear that this discussion should be continued in the existing and open issue ticket #16561 (see comment https://github.com/TrinityCore/TrinityCore/issues/24261#issuecomment-596054171).
