### ISSUE TITLE
Missing quest chain and wrong description

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24270]
Description:

NPC 4455 missing quest 1132，and the quest couldn't be completed.
NPC 4456 missing quest 1135，and description error: "Bring 10 Highperch Venom Sacs to Fiora Longears in Theramore."，Fiora Longears is in Darkshore.

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Faq** [comment]
Please split each issue in new ticket.

**Comment by aleigood** [comment]
> Please split each issue in new ticket.

NPC 4456 is the end npc of quest 1132.

**Comment by Kitzunu** [comment]
For quest 1132 (Fiora Longers)
> The quest says that you should be able to take a ship from Menethil to reach Fiora. This is incorrect. As of patch 3.0.3 (Wrath of the Lich King) the ship that used to go to Auberdine has been removed. In order to get to Auberdine, you need to take a ship from Stormwind Harbor (also added 3.0.3). This is a known issue with the quest text. It is unknown when Blizzard will clarify the text.

>As of patch 3.3, Red Jack Flint is unresponsive. A Game Master stated that the quest had been removed.
>>https://wowwiki.fandom.com/wiki/Quest:Fiora_Longears

For quest 1135 (Highperch Venom)
> The subject of this article was removed from World of Warcraft in patch 2.3.0.
This includes items and quests that can no longer be obtained or are now deprecated.
The in-game information in this article is kept purely for historical purposes.
>>https://wowwiki.fandom.com/wiki/Quest:Highperch_Venom

Suggested fix:
```sql
UPDATE `quest_template` SET `LogDescription` = 'Bring 10 Highperch Venom Sacs to Fiora Longears in Auberdine.' WHERE `id` = 1135;

DELETE FROM `disables` WHERE `sourceType` = 1 AND `entry` IN (1132, 1135);
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`) VALUES
(1, 1132, 0, 'DEPRECATED Quest - Fiora Longers'),
(1, 1135, 0, 'DEPRECATED Quest - Highperch Venom');
```

**Comment by shamage** [comment]
[Quest 1132 =>>  Fiora Longears ](https://classic.wowhead.com/quest=1132/fiora-longears) was removed in patch 3.3.0 
[Quest 1135 =>> Highperch Venom](https://classic.wowhead.com/quest=1135/highperch-venom)  was removed in patch 2.3.0
 @Kitzunu repair offered is the best solution for these tasks

**Comment by Kitzunu** [comment]
I mean if he really wants to use them...

```sql
UPDATE `quest_template` SET `LogDescription` = 'Bring 10 Highperch Venom Sacs to Fiora Longears in Auberdine.' WHERE `id` = 1135;

DELETE FROM `creature_queststarter` WHERE `quest` IN (1132,1135);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES
(4455, 1132),
(4456, 1135);

DELETE FROM `creature_questender` WHERE `quest` IN (1135,1135);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(4456, 1132),
(4456, 1135);

**Comment by Aokromes** [comment]
blizzlike (correct) way is disable them.

**Comment by Killyana** [comment]
Both quests are already not available IG.
