### ISSUE TITLE
The merchant has no goods

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24273]
Description:
Dalaran's two merchants had no goods.
Creature ID: 35498 34252

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Killyana** [comment]
Plate armor only

**Comment by illfated** [comment]
@aleigood ; if you compare those merchants with Blizzard retail, you will find that those merchants only display their goods to plate users.
