### ISSUE TITLE
Item: Writhing Choker

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24276]
We have Unliving Choker with the help of which we get the Darkness Calling quest. To execute it, you need to get Writhing Choker from the trolls. However, this loot was not observed in the trolls.

https://www.wowhead.com/item=38673/writhing-choker
https://www.wowhead.com/quest=12633/darkness-calling
https://www.wowhead.com/npc=28519/withered-troll#drops

Branch(es): 3.3.5

TDB: 335.20021
Ubuntu 18.04
Rev. e7d2489

**Comment by dr-j** [comment]
There are two versions of this choker which start different quest but which both lead to same quest chain the two items are https://www.wowhead.com/item=38673/writhing-choker and https://www.wowhead.com/item=38660/unliving-choker which you get depends on wether you have completed drakurus chain in Grizzly Hills or more specifically https://www.wowhead.com/quest=12238/cleansing-draktharon

If you are rewarded for this quest Writhing Choker will drop if you are not Unliving Choker will drop if you currently have this quest in quest log neither will drop

**Comment by illfated** [comment]
https://wow.gamepedia.com/Unliving_Choker
- https://wow.gamepedia.com/An_Invitation,_of_Sorts...

https://wow.gamepedia.com/Darkness_Calling
- https://wow.gamepedia.com/Writhing_Choker

**Comment by illfated** [comment]
https://www.wowhead.com/item=38673/writhing-choker#comments :
***
> [**LostDrewid**](https://www.wowhead.com/user=LostDrewid) on [2009/02/04 (Patch 3.0.8)](https://www.wowhead.com/item=38673/writhing-choker#comments:id=580550:reply=77828)
>
> Precisely. All of the objectives and rewards for both chains are equal; the difference is in whether you did the chain from Grizzly Hills through to Drak'Tharon Keep prior to begining this chain. If yes, you get the Writhing Choker and its chain; if not, you get the Unliving Choker. You can never have both.

**Comment by Rushor** [comment]
https://www.wowhead.com/item=38660/unliving-choker currently has condition queststatus none.


should it not be like:

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=1 AND `SourceGroup`=28519 AND `SourceEntry`=38660;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(1, 28519, 38660, 0, 0, 9, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon taken'),
(1, 28519, 38660, 0, 1, 28, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon completed'),
(1, 28519, 38660, 0, 2, 14, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon none');
```

??

**Comment by Killyana** [comment]
There's 2 type of chokers, one if the player didn't interact with quest=28519 and one if the quest=28519 is rewarded, so if the quest is in your journal you will get none, and this is blizzlike.

``` 
SourceTypeOrReferenceId, SourceGroup, SourceEntry, SourceId, ElseGroup, ConditionTypeOrReference, ConditionTarget, ConditionValue1, ConditionValue2, ConditionValue3, NegativeCondition, ErrorType, ErrorTextId, ScriptName, Comment
 1, 28519, 38673, 0, 0, 8, 0, 12238, 0, 0, 0, 0, 0, , NULL
 1, 28519, 38660, 0, 0, 14, 0, 12238, 0, 0, 0, 0, 0, , NULL

**Comment by Killyana** [comment]
After some tests conditions are missing some cases, the player can get both chokers

**Comment by Killyana** [comment]
The player is still able to get the item 38660 then reward the quest 12238 and get the item 38673, I added a condition for the quest that start with item: 38660 to block the player from starting it, but if he start the quest upon looting 38660 he will be able to do both chains.
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=1 AND `SourceGroup`=28519 AND `SourceEntry` IN (38660,38673);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceGroup`=0 AND `SourceEntry`=12631;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(1, 28519, 38660, 0, 0, 9, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon taken'),
(1, 28519, 38660, 0, 1, 28, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon completed'),
(1, 28519, 38660, 0, 2, 14, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon none'),
(1, 28519, 38673, 0, 0, 8, 0, 12238, 0, 0, 0, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon Rewarded'),
(19, 0, 12631, 0, 0, 8, 0, 12238, 0, 0, 1, 0, 0, '', 'show itemloot if player has quest Cleansing Drak\'Tharon Rewarded');

**Comment by dr-j** [comment]
Well when was looking up this quest on web the other day it suggested that once one choker has dropped even if you destroy it and do quest and then try and get the other choker same one as originally dropped will drop again

**Comment by dr-j** [comment]
Also needs conditions so that wont drop if player already has the other choker or has the quest from if taken, complete or rewarded?
