### ISSUE TITLE
GetInstanceSave thread safety concerns

### ISSUE THREAD

**Issue by danbopes** [TrinityCore/TrinityCore#24277]
**Description:**

`InstanceSaveManager::GetInstanceSave()` is currently being called from map thread, in `Unit::Kill` (And possibly other places):

![](https://i.imgur.com/D3ND4yH.png)

**Expected behavior:**

A lock should be present on access to `m_instanceSaveById` to prevent cross threading issues as a result of iterating through the map on 2 different threads.

**Branch(es):**

3.3.5 (IDK about Master)

**TC rev. hash/commit:** 

Current

**Comment by Shauren** [comment]
Nope. All std:: containers are safe for reads from multiple threads. `m_instanceSaveById` is never modified outside of main world thread (when no map updates are running)

**Comment by jackpoz** [comment]
@danbopes did you get a report by a thread safety tool like helgrind or ?
