### ISSUE TITLE
Creature/Movement: Eye of acherus initial root

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24272]
**Description:** When Eye of Acherus (the vehicle) spawn it get the aura https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51860 it must root it, but for some reason the player is still able to move the vehicle until the wp start.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp#L440

This issue is not related to the recent charm commit as I reverted it and I reproduced the issue.
.list aura show the vehicle has spell=51860

**Steps to reproduce the problem:**

1. .quest add 12641
2. .go c id 25462
3. click the gob to summon the eye
4. move the eye

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 49e77d7c9e4c

**Comment by Jinnaix** [comment]
Might be a general stun related problem.
We recently worked on the Hakkar fight in Zul Gurub where we have the problem that the main mechanic of the fight is skipable trough player movement.
We went with [Serverside Root ](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=35340) but that just dont work.

For reference : 
#23688
#23693

**Comment by Rushor** [comment]
maybe adding 
me->SetControlled(true, UNIT_STATE_ROOT);
me->AddUnitState(UNIT_STATE_ROOT);

in a general spellscript

**Comment by Faq** [comment]
Tried several approaches, even aurascript.
In JustAppeared() buff is added but root effect not working. 
Bur when disable spell cast use with script and instead do ingame command .aura 51860 it works asap on charmed npc. That was the first confusing thing.

If someone can debug and find why it is working only when used constructor, would be better.
