### ISSUE TITLE
[master]worldserver failed to start!!

### ISSUE THREAD

**Issue by fengyunjx** [TrinityCore/TrinityCore#24282]
Client version 8.3.0:
TrinityCode version master
system macOS 10.15.3

Tdb_full_820.19071_2019_07_15 is used. Couldn't find 8.3.0

An error occurred while running worldserver. The information is as follows

>> Loaded 966 trinity strings in 5 ms
Initialize the data stores...

Db2 files (249 from 1) not found or not compatible:
Db2 Achievement.
Db2 AnimationData.
AnimKit. Db2
Db2 AreaGroupMember.
Db2 AreaTable.
Db2 AreaTrigger.
...

Please tell me how to solve it

**Comment by Aokromes** [comment]
this belongs to forum.

**Comment by MaxtorCoder** [comment]
Update ur db2 files.
