### ISSUE TITLE
PvP mode is automatically turned off

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24280]
Hello! There is such a problem: if you turn on pvp mode, and a player from the opposite fraction tries to attack you, then he turns on pvp mode for a second and turns off automatically.

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. e7d2489

**Comment by illfated** [comment]
Interesting. I didn't know that this happens (then again, I play alone). Could be a side effect of the other existing PvP issues (I don't know if this is a fact, though).

**Comment by jjo72ddd** [comment]
I think this is really a big problem.
[Video Here](https://mega.nz/#!4VIT1AYY!I9axWQ56IhkaGzRqvxubMkI4XKKKZnj9MKI1ocLWY2U)

**Comment by Rushor** [comment]
since what time this is happening?

**Comment by jjo72ddd** [comment]
> 
> 
> since what time this is happening?

it has been (for as long as i can remember) since the server started (about a month ago). It does not depend on the level.

**Comment by jjo72ddd** [comment]
but I have an assumption that it depends on the settings of worldserver.conf
Now I have these settings:

> # SERVER SETTINGS
> #
> #    GameType
> #        Description: Server realm type.
> #        Default:     0  - (NORMAL)
> #                     1  - (PVP)
> #                     4  - (NORMAL)
> #                     6  - (RP)
> #                     8  - (RPPVP)
> #                     16 - (FFA_PVP, Free for all PvP mode like arena PvP in all zones except rest
> #                          activated places and sanctuaries)

> GameType = 0

**Comment by Rushor** [comment]
what happens if you change it to GameType = 1 ?

**Comment by jjo72ddd** [comment]
in a couple of minutes I’ll check it and let you know

**Comment by jjo72ddd** [comment]
still the problem

**Comment by Killyana** [comment]
This looks weird, the area in the video looks like Elwynn Forest, so why the pvp is not activated automatically for the horde character (if the realm is pvp)

**Comment by jjo72ddd** [comment]
In my opinion it should be activated pvp automatically when dealing damage regardless of area

**Comment by Killyana** [comment]
Not in a pvp realm, anyway the issue could be reproduce it in the other sense, with an alliance char (with pvp off) attacking a horde char in an alliance area.

**Comment by Ascathor** [comment]
Shouldn't we assume pvp as soon as player is in combat with other player ? Attacking automatically enters combat. Correct me on that.

**Comment by jjo72ddd** [comment]
> 
> 
> Shouldn't we assume pvp as soon as player is in combat with other player ? Attacking automatically enters combat. Correct me on that.

as soon as you attack the enemy, your pvp mode should turn on automatically. This is true in the video, but then it turns off automatically

**Comment by Killyana** [comment]
Not only attacking a player but any action that starts the combat.

**Comment by Jildor** [comment]
I can confirm.
@Treeston I try to revert this commit: https://github.com/TrinityCore/TrinityCore/commit/671052575a36624b06379ee5e13a7fea26870194
and I can't reproduce the issue without this commit

**Comment by Faq** [comment]
Solution here https://github.com/Faq/TrinityCore/commit/25f2ae78c62adeb582e7213203d54b09a38a0958

**Comment by Killyana** [comment]
Please open a PR, to be reviewed.

**Comment by jjo72ddd** [comment]
Can we close this?
b4584ee
332b2f1

**Comment by Killyana** [comment]
Need testing

**Comment by Killyana** [comment]
Not fixed yet https://imgur.com/3Dw0hST

**Comment by Faq** [comment]
Some things that needs clarification for server realm type NORMAL, correct if I'm wrong.
By correcting me is meant if mentioned result is NOT blizzlike.

Horde char in Elwynn forest (unfriendly territory):
1. If "Player vs Player Enabled" or "Player vs Player Disabled", "Toggle PVP is ON", do Log off and log on
Result: "Toggle PVP is ON"
2. while "Player vs Player Enabled" and "Toggle PVP is ON", set "Player vs Player Disabled"
Result: 5min timer is not started while in unfriendly territory
3. when is set "Player vs Player Disabled" and "Toggle PVP is ON", moving from unfriendly territory to neutral zone like Stranglethorn Vale
Result: without timer "Toggle PVP is OFF"

Allience char in Elwynn forest (friendly territory):
1. If "Player vs Player Enabled", "Toggle PVP is ON", do Log off and log on
Result: "Toggle PVP is ON"
2. while "Player vs Player Enabled" and "Toggle PVP is ON", set "Player vs Player Disabled", starts 5min timer
Result: after timer runs out "Toggle PVP is OFF"
3. while "Player vs Player Enabled" and "Toggle PVP is ON", set "Player vs Player Disabled", starts 5min timer, while timer active do Log off and Log on
Result: "Toggle PVP is OFF" (relog skipped counter)

**Comment by Killyana** [comment]
You can find all situations here https://wowwiki.fandom.com/wiki/PvP_flag

Also in a pvp realm, a Horde char in Elwynn forest will always have pvp ON and this cannot be disabled

**Comment by illfated** [comment]
Just to clarify: Even on a non-PvP server, Alliance characters should automatically have their the PvP flag turned on in Horde friendly zones, and Horde characters in Alliance friendly zones should automatically also have the PvP flag turned on, while being in the opposite faction's zone. This is my experience from 10 years ago while playing on Blizzard servers.

**Comment by Faq** [comment]
@Killyana there not written what happens when timer is started and you relog.
@illfated strange as https://wowwiki.fandom.com/wiki/PvP_flag is mentioned:

> You enter a specific territory. The scheme for flagging by zoning-in is shown in the table bellow: 
![image](https://user-images.githubusercontent.com/322016/80857921-6bb41580-8c5e-11ea-9982-1d4c86b78a6f.png)

**Comment by illfated** [comment]
OK, I was not specific enough. Note that it says 2 lowest level zones near them (starter zones, level 1-10). I should have mentioned that (or not said anything at all).

**Comment by Faq** [comment]
My questions were about normal realm, i don't get it now why you mention something from table under "PvP realm".
Anyway if not engaged, then pvp flag will show up only in opposite faction cities, not in other territory.

**Comment by illfated** [comment]
OK, I will delete my comments. Feel free to do the same.

**Comment by jaxidor** [comment]
has this been fixed yet? :o very deadly bug for world pvp

**Comment by Killyana** [comment]
If you log out with the timer going on, the timer will stops and get removed, and once relog you will get the same pvp flag status as before log out.

**Comment by jaxidor** [comment]
Well, if i am an alliance and i go to orgrimmar, all the hordes that attack be get pvp flagged and it instantly goes away so i cant attack them. 
so world pvp raiding the other faction etc is completely broken cus the other faction can attack you while not even getting pvp flagged properly.

**Comment by Faq** [comment]
Still wondering, how 7 months none reported this. @jaxidor try with #24372

**Comment by nerc0487** [comment]
Why has this been closed without any possible solutions being presented?

**Comment by Thanathros** [comment]
#24372 was presented as fix.

**Comment by offl** [comment]
Is this issue still valid?

**Comment by Thanathros** [comment]
It's closed and a Fix was merged. As long as no one is giving negative feedback it seems solved imo.
