### ISSUE TITLE
CMake Error: Error processing file: D:/EmuProjects/version4/Server/cmake_install.cmake

### ISSUE THREAD

**Issue by CyberMist2** [TrinityCore/TrinityCore#24288]
**Description:**

CMake Error: Error processing file: D:/EmuProjects/version4/Server/cmake_install.cmake

**Current behaviour:**

When I do write the ``cmake --install`` it shows the error:
``CMake Error: Error processing file: D:/EmuProjects/version4/Server/cmake_install.cmake``

**Expected behaviour:**

Should deploy the binary files?

**Steps to reproduce the problem:**

1. ``cmake --install ../Server``

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Lastest commit: https://github.com/TrinityCore/TrinityCore/commit/70569ae3e66eb0b73a0edb6b5435c6f0c5e50833

**Operating system:** Windows 10 Pro 64bit

**Comment by Shauren** [comment]
Why are you not using `make install`/`ninja install`/`INSTALL project inside VS?

**Comment by CyberMist2** [comment]
> Why are you not using `make install`/`ninja install`/INSTALL project inside VS?

Im using git bash to build, that command doesnt exist

**Comment by Shauren** [comment]
What did you configure cmake with then? (the -G parameter)

**Comment by CyberMist2** [comment]
I would like to use the command as linux uses make install... without opening the vs

**Comment by Shauren** [comment]
cmake --install will never work for MSBuild because debug/relwithdebinfo/release is a build-time property, not a configure time property like with make and ninja

What you should do is run cmake with `-DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=1` then invoke msbuild with INSTALL target, for example
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" TrinityCore.sln /nologo /nr:true /t:INSTALL /p:Configuration=RelWithDebInfo /m:3 /p:BuildInParallel=true /clp:Summary /v:normal`

**Comment by CyberMist2** [comment]
> cmake --install will never work for MSBuild because debug/relwithdebinfo/release is a build-time property, not a configure time property like with make and ninja
> 
> What you should do is run cmake with `-DCMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD=1` then invoke msbuild with INSTALL target, for example
> `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" TrinityCore.sln /nologo /nr:true /t:INSTALL /p:Configuration=RelWithDebInfo /m:3 /p:BuildInParallel=true /clp:Summary /v:normal`

I Installed ``make`` software and:
``$ make INSTALL                                                                                                          
make: *** No rule to make target `INSTALL'.  Stop.``

**Comment by Shauren** [comment]
You are doing it extremely wrong. You have to use MSBuild if you generated VS solution, make + cl is not a supported configuration

**Comment by CyberMist2** [comment]
> MSBuild

Ok.. thank you

**Comment by Rochet2** [comment]
Something like this should work assuming you are inside TC source root folder:
```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=whatever/here
cmake --build . --config Debug --parallel 4
cmake --install . --config Debug
```
