### ISSUE TITLE
Creature/Script: Morridune

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24291]
**Description:** The npc Morridune must start a waypoint upon summoned, butt it doesn't

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp#L230

**Steps to reproduce the problem:**

1. .go c id 4829
2. Kill the boss
3. Morridune will spawn but the waypoint will not start

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. a40b742c3ae

**Comment by Rushor** [comment]
stuff beeing handled in constructor is bad. will open up a pr

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/f488c361545b0bf872dbbaec0d13c21fcee1df9b
