### ISSUE TITLE
DB/Creature Mini Diablo

### ISSUE THREAD

**Issue by Kitzunu** [TrinityCore/TrinityCore#24299]
**Description:**

The noncombat pet Mini Diablo should at idle, hover and use a flame spell rarely according to
> By 8014 (3,189 – 13·18) on 2006/12/08 (Patch 2.0.1)
This item is one of three items that players who bought the original collector's edition of World of Warcraft can chose from.
>
>**This Diablo Stone summons a 'Mini Diablo' non-combat pet who has a glowing horn and the 'guild title' of <Lord of Terror>. Occaisonally this pet will levitate and even more rarely shoot a long gout of flame into the air.**
>
>Diablo is the boss of both Diablo and Diablo 2, two games that were created by Blizzard Entertainment.

**Current behaviour:**

Does not have any animations

**Expected behaviour:**

Should have animations 

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

Probably both

**TC rev. hash/commit:** 

94147f24bf24

**Operating system:** 

Windows

Partly Fix: (I don't know if any of the timers are correct, it is pure guessing what could be "rare")
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 11326;

DELETE FROM `smart_scripts` WHERE `entryorguid` = 11326 AND `source_type` = 0 AND `id` = 0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(11326, 0, 0, 0, 1, 0, 100, 0, 180000, 300000, 300000, 420000, 0, 11, 18874, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mini Diablo - Out of Combat - Cast \'Diablo\'');
```

**Comment by offl** [comment]
Use https://woehead.way-of-elendil.fr/?spell=18873 in c_t_a

**Comment by Kitzunu** [comment]
Then it can be done with this?
```sql
DELETE FROM `creature_template_addon` WHERE `entry` = 11326;
INSERT INTO `creature_template_addon` (`entry`, `auras`) VALUES
(11326, '18873');
```

**Comment by Killyana** [comment]
Just put it in creature_template_addon

**Comment by Keader** [comment]
exactly

**Comment by Killyana** [comment]
It doesn't work IG  :(

**Comment by Kitzunu** [comment]
:( Maybe that spell is broken?

I know 18874 works tho, cuz .cast 18874 does the animation... so in the worst case, we do it sai for 18874 and 12 minute time? o.o

**Comment by Killyana** [comment]
Oh 12min not secs

**Comment by Keader** [comment]
Updated, but not full fixed yet.
still missing know what is the hover stuff

**Comment by Keader** [comment]
"Occaisonally this pet will levitate and even more rarely shoot a long gout of flame into the air."
And 12 minutes... is higher as f**, we dont have sniffs about this creature? maybe wrong dbc value

**Comment by Kitzunu** [comment]
Hover spell I don't know which one it is :( 🤷‍♂

**Comment by Killyana** [comment]
"Occasionally this pet will levitate", it already happen from the default animation.

**Comment by Kitzunu** [comment]
Oh Okay xD

**Comment by Kitzunu** [comment]
Then we can close again? 🤷‍♂

**Comment by offl** [comment]
> "Occaisonally this pet will levitate and even more rarely shoot a long gout of flame into the air."
> And 12 minutes... is higher as f**, we dont have sniffs about this creature? maybe wrong dbc value

Nope. Look at the videos names:
[World of Warcraft rare animation (1/100) (Mini Diablo)](https://www.youtube.com/watch?v=KHBE4vc2DJ0)
[From description: This is a very very rare shot of my mini diablos fire breath, i saw it 3 times in 4 years of playing wow =)](https://www.youtube.com/watch?v=N88f8XR-anM)
In addition Baby Murloc has [15 minute duration](https://woehead.way-of-elendil.fr/?spell=24983) for the dance spell.

**Comment by Keader** [comment]
Yeap
