### ISSUE TITLE
criters doesn't leaves combat on instances after a time

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24297]
**Description:**

on tc criters makes people to end stuck on combat

**Current behaviour:**

you stuck on combat

**Expected behaviour:**

after a time you must leave combat

**Steps to reproduce the problem:**

1. go some instance with criters with for example a warrior to gundrak final boss
2. start combat
3. you can end stuck on combat

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

70569ae3e66e

**Operating system:** debian 10 x64

**Comment by Faq** [comment]
end stuck? Meaning endlessly stuck in combat?

**Comment by Killyana** [comment]
In combat until the unit is killed, before combat/threat rewrite critters never starts a combat, but it's probably not blizzlike.

**Comment by Killyana** [comment]
Related to https://github.com/TrinityCore/TrinityCore/issues/22931

**Comment by Rushor** [comment]
is this a nre bug or reated to combat rewrite?

**Comment by Killyana** [comment]
Combat rewrite,  I tried to fix it like thi:
``` diff
diff --git a/src/server/game/AI/CoreAI/PassiveAI.h b/src/server/game/AI/CoreAI/PassiveAI.h
index e91d196bef..f75cba795b 100644
--- a/src/server/game/AI/CoreAI/PassiveAI.h
+++ b/src/server/game/AI/CoreAI/PassiveAI.h
@@ -73,7 +73,7 @@ class TC_GAME_API CritterAI : public PassiveAI
     public:
         explicit CritterAI(Creature* creature) : PassiveAI(creature) { }
 
-        void DamageTaken(Unit* done_by, uint32& /*damage*/) override;
+        void JustEnteredCombat(Unit* who) override { EngagementStart(who); }
         void EnterEvadeMode(EvadeReason why) override;
 
         static int32 Permissible(Creature const* creature);
diff --git a/src/server/game/AI/CoreAI/PassiveAI.cpp b/src/server/game/AI/CoreAI/PassiveAI.cpp
index 63f1a5e439..d4b1368c21 100644
--- a/src/server/game/AI/CoreAI/PassiveAI.cpp
+++ b/src/server/game/AI/CoreAI/PassiveAI.cpp
@@ -79,7 +79,7 @@ void PossessedAI::KilledUnit(Unit* victim)
         victim->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
 }
 
-void CritterAI::DamageTaken(Unit* /*done_by*/, uint32&)
+void CritterAI::JustEnteredCombat(Unit*)
 {
     if (!me->HasUnitState(UNIT_STATE_FLEEING))
         me->SetControlled(true, UNIT_STATE_FLEEING);
```
But it doesn't work, some thing i wrong in my diff
