### ISSUE TITLE
Creature/Script: Boss Kelris

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24292]
**Description:** Kelris must channel the spell 8734 on reset.
If use this diff, it will only be channeled correctly on server start, but on reset it will get interrupted.
``` diff
diff --git a/src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp b/src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp
index 272817a24b..5c6f67bf5c 100644
--- a/src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp
+++ b/src/server/scripts/Kalimdor/BlackfathomDeeps/boss_kelris.cpp
@@ -21,8 +21,9 @@
 
 enum Spells
 {
-    SPELL_MIND_BLAST    = 15587,
-    SPELL_SLEEP         = 8399,
+    SPELL_MIND_BLAST                    = 15587,
+    SPELL_SLEEP                         = 8399,
+    SPELL_BLACKFATHOM_CHANNELING        = 8734
 };
 
 enum Texts
@@ -61,6 +62,11 @@ public:
             _JustDied();
         }
 
+        void Reset() override
+        {
+            DoCast(me, SPELL_BLACKFATHOM_CHANNELING);
+        }
+
         void UpdateAI(uint32 diff) override
         {

                 if (!UpdateVictim())
``` 
Also if you aggro it when he channel the spell it will not get interrupted, and the boss remains rooted.

**Steps to reproduce the problem:**

1. Apply the diff
2. .go c id 4832

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. a40b742c3ae8

**Comment by Rushor** [comment]
can you try function: onreachedhome?

**Comment by Killyana** [comment]
With JustReachedHome() it channels the spell after an evade, but not on server starts.
The second issue is not related to thee first.
