### ISSUE TITLE
stuck on combat with icecrown citadel traps (for sure it needs generic fix)

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24290]
**Description:**

people get stuck on combat if they walk on the traps when enabled and they don't die.

**Current behaviour:**

you end stuck on combat.

**Expected behaviour:**

you don't enter combat with them

**Steps to reproduce the problem:**

1. .go xyz 4228.416504 2768.950195 350.963074 631
2. .cheat god on
3. .gm off
3. walk around enabled traps

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

70569ae3e66e

**Operating system:** debian 10 x64

**Comment by Killyana** [comment]
Looks related to https://github.com/TrinityCore/TrinityCore/issues/24156
```
[17:11:32] Combat refs: (Combat state: 1 | Manager state: 1)
[17:11:32] [PvE] Hilium (SpawnID 0)
[17:11:39] Frost Freeze Trap (GUID 277) does not threaten any units.
[17:11:39] Frost Freeze Trap (GUID 277) is currently engaged. (This unit cannot have a threat list.)

**Comment by Aokromes** [comment]
on retail you never enter combat with traps, idk if it's because the level diff of the char used to test, or something else.

**Comment by jackpoz** [comment]
Please test https://github.com/TrinityCore/TrinityCore/pull/25086
