### ISSUE TITLE
Jewelcrafting Trainers Missing

### ISSUE THREAD

**Issue by Lazurick** [TrinityCore/TrinityCore#24307]
**Description:**

Trainers for Jewelcrafting profession missing.

**Current behaviour:**

No trainers can be found for Jewelcrafting, trainer is not listed by guards in cities.

**Branch(es):**

3.3.5

**Operating system:** 

Windows 10, Windows Server 2016

**Comment by Aokromes** [comment]
> **Description:**
> 
> Trainers for Jewelcrafting profession missing.
> 
> **Current behaviour:**
> 
> No trainers can be found for Jewelcrafting, trainer is not listed by guards in cities.
> 
> **Branch(es):**
> 
> 3.3.5
> 
> **Operating system:**
> 
> Windows 10, Windows Server 2016

they are on exodar and silvermoon and at least dalaran and thralmar, honor hold.
