### ISSUE TITLE
Quest: Hard to Swallow

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24308]
It doesn’t work to explode the worm with "Potent Explosive Charges"
https://www.wowhead.com/quest=12049/hard-to-swallow

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. e7d2489

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23915
