### ISSUE TITLE
DB/Creature: creature formations for bosses and adds in Molten Core

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24306]
**Description:**

The following SQL create creature formations for 3 Encounters

Golemagg
Sulfuron Harbinger
Gehennas

**Current behaviour:**

We all know of situations where you start a boss encounter and some adds just stand in a corner because of how aggro works in Trinitycore.

Example on Golemagg : 
Golemagg comes with 2 Core Rager.
If you stand to the left and attack the left Core Rager, aggro will jump on Golemagg but the right Core Rager wont notice you.

**Expected behaviour:**

Golemagg and his 2 Core Rager belong together. No matter from where you attack any one of those three creatures, they should get in combat with you.

**Sidenotes**

Due to how creature formations work, it seems to generate a small "non blizzlike" situation.
As seen in [this video ](https://www.youtube.com/watch?v=3p8_Wx5vE-I), there is a update tick of roughly a second till the rest of the creatures attack. With creature formations, all linked creatures instantly react to the aggro invoker.
Still better than several creatures standing around in a boss fight.
We already have these situations, for example MC boss Garr and his adds have a active formation and react like described.

In addition, you can only link creatures that are already spawned in Database. Therefore, Majordomus needs to be covered scriptwise.

**SQL**

```sql
-- Creature Formations
-- Molten Core
-- Golemagg 11988 and his 2 Corer Rager 11672
DELETE FROM `creature_formations` WHERE `memberGUID` IN (56685,56699,56684);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES 
(56684, 56685, 0, 0, 3, 0, 0),
(56684, 56699, 0, 0, 3, 0, 0),
(56684, 56684, 0, 0, 3, 0, 0);

-- Sulfuron Harbinger 12098 and 4 Flamewaker Priests
DELETE FROM `creature_formations` WHERE `memberGUID` IN (56677,56682,56679,56678,56681);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES 
(56677, 56677, 0, 0, 3, 0, 0),
(56677, 56682, 0, 0, 3, 0, 0),
(56677, 56679, 0, 0, 3, 0, 0),
(56677, 56678, 0, 0, 3, 0, 0),
(56677, 56681, 0, 0, 3, 0, 0);

-- Gehennas 12259 and 2 Flamewaker 11661
DELETE FROM `creature_formations` WHERE `memberGUID` IN (56737,56739,56738);
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES 
(56737, 56737, 0, 0, 3, 0, 0),
(56737, 56739, 0, 0, 3, 0, 0),
(56737, 56738, 0, 0, 3, 0, 0);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3287d296772b7cec9fb1618c1794e6acf461cdcd

**Comment by Rushor** [comment]
works nicely!

**Comment by Killyana** [comment]
We have a ticket for Majordomo Executus https://github.com/TrinityCore/TrinityCore/issues/5885
