### ISSUE TITLE
DB/Creature: Creatures come together

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24305]
Description:
Creatures come together and don't move randomly, not sure if there's a problem with the db, but it looks strange.

![image](https://user-images.githubusercontent.com/3367999/76700890-f9f82a80-66f6-11ea-8cdb-8a8652db527e.png)

Steps to reproduce the problem:
.go xyz 5600.802734 5510.528809 -90.812248 571

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Rushor** [comment]
well that is just a missing randommovement addition

**Comment by Killyana** [comment]
Looks more like positions were sent to the client while this creatures were fighting a player.
