### ISSUE TITLE
DB/Creature: 2 Wrong spawnpoints in Pyrewood Village

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24317]
**Description:**

Creature Spawn guid 17663 (Pyrewood Elder) and guid 152283 (Moonrade Elder - same spawn - only active when Event 25 is running) have a incorrect spawn - dont know where to put them but they dont belong in the chimney

**Steps to reproduce the problem:**

.go xyz -323.823242 1548.125244 25.273260 0 2.039126

**Branch(es):**

335

**TC rev. hash/commit:** 

cec960de53920e10cd794a0abfd0fbe652102a89

**Comment by illfated** [comment]
> [ ... ] dont know where to put them but they dont belong in the chimney
>
Thanks for the chuckle. 😄
