### ISSUE TITLE
DB/Creature: SAI correction for Scarlet Conjuror (4297)

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24313]
**Description:**

Scarlet Conjuror (yes, there is only one) in Scarlet Monastery Armory has a prespawned Fire Elemental.
Due to different familietypes, the fire elemental wont get pulled on aggro. Casting the summon spell corrects this and the Fire Elementals level too.

```sql
-- SAI correction for Scarlet Conjuror 4297
-- Fire Elemental will now be correctly summoned instead of prespawned
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 4297);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(4297, 0, 0, 0, 25, 0, 100, 2, 0, 0, 0, 0, 0, 11, 8985, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarlet Conjuror - On Reset - Cast \'Summon Fire Elemental\' (Normal Dungeon)'),
(4297, 0, 1, 0, 0, 0, 100, 2, 0, 0, 2400, 3800, 0, 11, 9053, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarlet Conjuror - In Combat - Cast \'Fireball\' (Normal Dungeon)'),
(4297, 0, 2, 0, 2, 0, 100, 3, 0, 15, 0, 0, 0, 25, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarlet Conjuror - Between 0-15% Health - Flee For Assist (No Repeat) (Normal Dungeon)');

-- deleting his prespawned Fire Elemental in Scarlet Monastery Armory
DELETE FROM `creature` WHERE (`guid` = 40134);
```

**Branch(es):**
335

**TC rev. hash/commit:** 

3287d296772b7cec9fb1618c1794e6acf461cdcd

**Comment by Teppic1** [comment]
Is there still the problem (with TC in general) that summoned mobs will automatically despawn when the summoner is killed? That's one benefit of having regular spawns, as they shouldn't do that.

**Comment by Jinnaix** [comment]
Yes, that problem still exists. 
Sure, that might look like a benefit, but its wrong.
Because if you kill the summoner and then you die before you kill the summoned mob, it shout despawn on evade or when its back at home position. Doesnt happen for prespawned creatures ofc.
In addition, the benefit is gone when the "summoned" creature dont react to their master being attacked due to having another creature type. You notice that by pulling them from far away.

There is a open issue somewhere for the summoned creature despawn problem.

**Comment by Teppic1** [comment]
Yeah, having pre-spawns that have no relation to the npc that should summon them is totally wrong. With SAI I guess you could set some data between them but it's a bit hacky.
I thought maybe that was why it was done this way originally, to avoid the problem of them despawning automatically, as neither works correctly.
