### ISSUE TITLE
Unlimited mana / rage / etc

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24315]
**Description:**

Paladin has unlimited mana, mana not being diminished when using Flash Heal

**Current behavior:**

Created a new Blood Elf Paladin.  When using Flash Heal (on self or others), mana never gets used, and thus I can spam Flash Heal forever and not run out of mana

**Expected behavior:** Flash Heal uses mana, mana gets used and must be regenerated

**Steps to reproduce the problem:**  Use Flash Heal on yourself or others, will see that mana is unlimited

----------

**Branch(es):** master

**TC rev. hash/commit:**  569f1c9

**Operating System:** Windows 10

**Comment by ReyDonovan** [comment]
not only mana but any Power Enerdge

**Comment by mcsescott** [comment]
What ReyDonovan has said is true - have found the same thing on Priests, Warriors, and Monks

**Comment by dio85** [comment]
Yeah, this bug on all class, no mana focus, rage or anything....

**Comment by ImmortalusDev** [comment]
I can confirm this issue on master.

**Comment by bozoweed** [comment]
an idea for fix that ?

**Comment by ImmortalusDev** [comment]
What do you think about this issue? @Shauren

**Comment by dio85** [comment]
And have big f.. mana regen in combat, maybe any changed in the db2 file... and this is why dont have correct value for spells. This just my teory. Cant cheak without any program to open it.

**Comment by bozoweed** [comment]
@dio85  it's not that because that was same for rage , mana, energy, Chi , combot point etc they are not used

**Comment by dio85** [comment]
> @dio85 it's not that because that was same for rage , mana, energy, Chi , combot point etc they are not used
> try made monk up level 8 and when you made spell who used chi point they are not removed

dio85 commented 5 days ago
Yeah, this bug on all class, no mana focus, rage or anything....

**Comment by Smerdokryl** [comment]
With Flash Heal it appears that mana does get subtracted, but then replenishes very quickly

**Comment by dio85** [comment]
Yeah, and maybe the wont scaled up... if you have 100k mana and your spell use 1k max... 1k instantly regenerated... 1sec maybe.

**Comment by silmareen** [comment]
Look like that this was also the case with 8.2.00 ? can this be ?

**Comment by DuelistRag3** [comment]
yes it was and in 8.1

**Comment by dio85** [comment]
@Shauren  Pls check this error.

**Comment by nbattista89** [comment]
Also the priest has practically infinite mana, instantly restores even during combat.

**Comment by dio85** [comment]
yes, and not. The spells not ranked up, so some skill just "rank1" spell, and use much more less mana. Spellscaling or what handle this. but not realy want work.

**Comment by dio85** [comment]
Spell.cpp 2897 line... if(!m_CastItem)

**Comment by ImmortalusDev** [comment]
Only Shauren can fix this.

**Comment by DuelistRag3** [comment]
> Only Shauren can fix this.

Why? :D

**Comment by ImmortalusDev** [comment]
Guess why. :D It's simple -> noone really knows, how to fix it, properly.

**Comment by DuelistRag3** [comment]
Thats pritty damn acurate :D but some pserver devs know? o.O i played on some where this is working i guess, not sure 100% ^^ it's been a long time since :D

**Comment by ImmortalusDev** [comment]
They know, for sure.

**Comment by DuelistRag3** [comment]
A little bit sad imo, to much competition ^^ i mean in some place i can unterstand it, but sad anyway

**Comment by Rushor** [comment]
that's why we cannot have nice things

**Comment by dio85** [comment]
Spell.cpp if (!m_CastItem) edit if (m_CastItem) to the first. And solved.

**Comment by MaxtorCoder** [comment]
And where are we supposed to put that, if that even is a proper fix.

**Comment by dio85** [comment]
[http://kepkezelo.com/viewer/xom476wwv4owg3zgbtp1.jpg](url)

this fix this idiot problem. Lazy Maxtor...

**Comment by MaxtorCoder** [comment]
No, nof "Lazy Maxtor", how the fuck are we supposed to know where to apply the "supposed" fix if you don't even tell us what line.

**Comment by Rushor** [comment]
i guess there https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp#L2906 ? not sure

@dio85 you can use https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp and redirect to lines

**Comment by ImmortalusDev** [comment]
> 
> 
> i guess there https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp#L2906 ? not sure
> 
> @dio85 you can use https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Spell.cpp and redirect to lines

Yes, that's correct, Rushor.

**Comment by dio85** [comment]
Maxtor i write this 6 day ago... on dc. And i write the line too where can you find.
