### ISSUE TITLE
DB/Creature: Remove obsolete Defias Companion spawns

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24314]
**Description:**

[Defias Pirates](https://db.project-nemesis.org/?npc=657) in Deadmines correctly summon their [Defias Companion](https://db.project-nemesis.org/?npc=3450) from SAI.
Therefore we can get rid of the 11 prespawned creatures.

```sql
DELETE FROM `creature` WHERE `guid` IN 
(79288,79291,79295,79317,79318,79332,79342,79350,79356,79358,79389);
```

In addition, we might want to modify the following script:

https://github.com/TrinityCore/TrinityCore/blob/c03d97d25f78a109bd31c45fe98346701ecc7066/src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp#L129-L157

to

```cpp
            void SummonCreatures()
            {
                if (GameObject* pIronCladDoor = instance->GetGameObject(IronCladDoorGUID))
                {
                    Creature* DefiasPirate1 = pIronCladDoor->SummonCreature(657, pIronCladDoor->GetPositionX() - 2, pIronCladDoor->GetPositionY()-7, pIronCladDoor->GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 3000);
                    Creature* DefiasPirate2 = pIronCladDoor->SummonCreature(657, pIronCladDoor->GetPositionX() + 3, pIronCladDoor->GetPositionY()-6, pIronCladDoor->GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 3000);

                    DefiasPirate1GUID = DefiasPirate1->GetGUID();
                    DefiasPirate2GUID = DefiasPirate2->GetGUID();
                }
            }

            void MoveCreaturesInside()
            {
                if (!DefiasPirate1GUID || !DefiasPirate2GUID)
                    return;

                Creature* pDefiasPirate1 = instance->GetCreature(DefiasPirate1GUID);
                Creature* pDefiasPirate2 = instance->GetCreature(DefiasPirate2GUID);
                if (!pDefiasPirate1 || !pDefiasPirate2)
                    return;

                MoveCreatureInside(pDefiasPirate1);
                MoveCreatureInside(pDefiasPirate2);
            }
```

since the two summoned Defias Pirates correctly summons one Defias Companion each.

The following line can also be removed afterwards:

https://github.com/TrinityCore/TrinityCore/blob/c03d97d25f78a109bd31c45fe98346701ecc7066/src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp#L72

**Branch(es):**

335

**TC rev. hash/commit:** 

3287d296772b7cec9fb1618c1794e6acf461cdcd

**Comment by Aokromes** [comment]
make pull request plz.

**Comment by jackpoz** [comment]
Please dear contributors, stop posting code changes as patches or other strange diffs and push them to a branch instead

**Comment by Jinnaix** [comment]
Yes, sorry.
As said in irc, issue report was already complete as i decided to check the blast cannon script and found the forced companion spawn. I wrote it down as i was testing on my fork and dont had a clean environment for a pull request.
I`ll do the PR soon.
