### ISSUE TITLE
Trainers do not work - Silvermoon

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24319]
**Description:**

Trainers in the Ruins of Silvermoon and Silvermoon City do not grant you the skills.  

This may be related to https://github.com/TrinityCore/TrinityCore/issues/21723 

**Current behavior:**

When attempting to train a profession or skill, you are presented with the gossip dialog, but once you select the profession to train, you are not granted the skill.

**Expected behavior:** Learn the skill from the trainer when selecting the option.

**Steps to reproduce the problem:** 

Visit trainer in the Ruins of Silvermoon or Silvermoon, talk to the trainer.  Go through the dialogs and select a skill.  No traing spells are learned.

----------
**Branch(es):** master

**TC rev. hash/commit:** 569f1c9

**Operating System:** Windows 10

**Comment by Killyana** [comment]
Dup #24026

**Comment by mcsescott** [comment]
I looked at #24026 and that issue is for a skill not leveling up, not for learning the skill itself.  Are these two issues linked?

Thanks...

**Comment by Killyana** [comment]
Yes same issue caused by outdated spells in the DB.
