### ISSUE TITLE
Paladin - Templar's Verdict spell not working

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24316]
**Description:**

Level 10 Paladin - Templar's Verdict spell does not work

**Current behavior:**

Created a new Blood Elf Paladin.  When reaching level 10, learned a new spell - Templar's Verdict.  When trying to use the spell, it will not fire.  I pushed the button and it did not work, and kept 3 Holy Power.

**Expected behavior:** When gaining 3 Holy Power, you should be able to use the spell Templar's Verdict on a mob.

**Steps to reproduce the problem:**  Get a level 10 Paladin.  Learn the spell Templar's Verdict.  When getting in combat, gain 3 Holy Power and attempt to use the spell.

----------

**Branch(es):** master

**TC rev. hash/commit:**  569f1c9

**Operating System:** Windows 10

**Comment by Jinnaix** [comment]
Please use the Issue search function to check for already reported issues.

In this case :
https://github.com/TrinityCore/TrinityCore/issues/19700
https://github.com/TrinityCore/TrinityCore/issues/18353
