### ISSUE TITLE
 DB/Creature: Techbot

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24322]
Techbot has a very short resurrection time, only 25 seconds.

https://classic.wowhead.com/npc=6231/techbot

![изображение](https://user-images.githubusercontent.com/24715026/76809782-f949bc00-67fc-11ea-93df-de7b6830c9b1.png)

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. de923fe

**Comment by Killyana** [comment]
I cannot find any information about the respawntime.

**Comment by illfated** [comment]
Could we treat that NPC as a default Elite NPC (dungeon) with standard Elite respawn time?

**Comment by Killyana** [comment]
Or someone with a classic account can go there, kill it, and tells us when it respawn.

**Comment by Aokromes** [comment]
being a "boss" it will have a minimum respawn of 1h

**Comment by Killyana** [comment]
Reduced to 10 min here: https://github.com/TrinityCore/TrinityCore/commit/afe2e67849755f607c6ec13907bb0ed33100fcb3
