### ISSUE TITLE
During the attack, the action continues

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24329]
if you start to eat or drink and the mob starts attacking you, you will not get up and continue the action.

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. de923fe

**Comment by aleigood** [comment]
It seems that only close attack can cause this problem.

**Comment by Faq** [comment]
With only malee attack?

**Comment by Killyana** [comment]
Yes

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4ea64b515aa952662dce11fd1012c566ae0d2449 https://github.com/TrinityCore/TrinityCore/commit/4cc1f850670b868a1d16833a2cf5c60715f749ef
