### ISSUE TITLE
Server crash on DK quest 12278 - The Scarlet Apocalypse

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24321]
**Description:**

DK quest crashes server, different issue than #22011

**Current behavior:**

After accepting the quest 12278 - The Scarlet Apocalypse, when you log out and log back in the server will crash.

**Expected behavior:** 

You should be able to log out of character and log back in without the server crashing

**Steps to reproduce the problem:** 

- Create DK
- Accept Quest 12278 - The Scarlet Apocalypse 
- Log out of character
- Attempt to log back in
- Server crashes

----------

Branch(es): master

TC rev. hash/commit: 569f1c9

Operating System: Windows 10

----------

`TC>TrinityCore rev. 569f1c9f2a48 2020-03-14 00:14:55 +0100 (master branch) (Win32, RelWithDebInfo, Static) (worldserver-daemon) ready...
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 4]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36BC (14012)] from [Player: Account: 4]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F6 (14070)] from [Player: Account: 4]
[Player: Account: 4] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Received not handled opcode [CMSG_GET_ACCOUNT_CHARACTER_LIST 0x36B8 (14008)] from [Player: Account: 4]
Received not handled opcode [CMSG_GET_RAF_ACCOUNT_INFO 0x3724 (14116)] from [Player: Account: 4]
Received not handled opcode [CMSG_GET_REMAINING_GAME_TIME 0x36EE (14062)] from [Player: Account: 4]
Received not handled opcode [CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS 0x3709 (14089)] from [Player: Account: 4]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BD (14013)] from [Player: Account: 4]
Received not handled opcode [CMSG_QUEUED_MESSAGES_END 0x376C (14188)] from [Player: Logging in: GUID Full: 0x08000400000000000000000000000008 Type: Player Entry: 0 Low: 8, Account: 4]
Player::_LoadQuestStatusObjectives: Player 'Wrecked' (GUID Full: 0x08000400000000000000000000000008 Type: Player Entry: 0 Low: 8) has quest 12778 out of range objective index 0.
[569f1c9f2a48_worldserver.exe_[16-3_19-4-14].txt](https://github.com/TrinityCore/TrinityCore/files/4340866/569f1c9f2a48_worldserver.exe_.16-3_19-4-14.txt)

`

**Comment by Aokromes** [comment]
this crash is still valid?

**Comment by Aokromes** [comment]
1 month without answer, if this bug is still valid open a new ticket using updated core.
