### ISSUE TITLE
Scripts/Blackwing Lair: Doors not working anymore.

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24326]
**Description:**

https://github.com/TrinityCore/TrinityCore/commit/99f31cbe5fc55e37bd4e00c77bfb35a2799c4ade#commitcomment-37879058

As of 99f31cbe5fc55e37bd4e00c77bfb35a2799c4ade script needs to be updated to cover correct doors and door behavior.

This issue is ignoring the template because its for being referenced by a PR.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

487370eb93b04fcda8ab2d31f22ea635db09a318

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a8a0f6b261994712e0339be96b8174a8382c51f7
