### ISSUE TITLE
Wrong spawner in Tirisfal Brill Undercity "Wild Turkey"

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#24334]
**Description:**

Tirisfal Brill Undercity have many many Wild Turkey I think they belong to the Pilgrim's Bounty Event.

 3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. f0fe5f8b669f 2020-03-19 00:17:36 +0100 (3.3.5 branch)

**Comment by Killyana** [comment]
And? What's the issue here?

**Comment by Tauriella** [comment]
The issue is the wrong Date. The Wild Turkey spawns in November
Or i am mistaken?

**Comment by Jinnaix** [comment]
I will just assume here that your database isnt fresh.

Therefore you might be hit by https://github.com/TrinityCore/TrinityCore/issues/21132

**Comment by Killyana** [comment]
All spawns are in the event 26
``` sql
SELECT guid FROM `creature`   WHERE `id` IN (32820) AND guid NOT IN (SELECT guid FROM game_event_creature);
SELECT * FROM game_event_creature WHERE guid IN (SELECT guid FROM `creature`   WHERE `id` IN (32820));
``` 
Why don't you  provide a guid of this wrong spawned npcs ?

**Comment by dr-j** [comment]
It could be related to issues I have seen recently with creatures spawned by events.

If creature is despawned and respawn timer has started creatures will spawn after event has ended

To reproduce go to worlds end tavern start the level 70 etc announce event which spawns drums

Start the concert event after ten minutes and wait for it to end drums will be despawned during concert has drummer spawns additional drums
Wait a few minutes drums will respawn 

Also noticed this with at scripts where npcs despawn at end of event they respawn at spawn positions after event has ended

**Comment by dr-j** [comment]
This only occurs with npcs that are despawned when a event ends

**Comment by Killyana** [comment]
Well, we have an issue for this case.

**Comment by Tauriella** [comment]
And how i can despawn the Wild Turkey now ?

**Comment by Killyana** [comment]
Kill them they will not respawn

**Comment by Tauriella** [comment]
killing brings nothing to them spawnen after a few minutes again

**Comment by illfated** [comment]
(This suggestion seems redundant, but it is difficult to know what problem you are actually seeing.)
Please check that your server clock time & date is correct, then delete your `world` database.
Delete your game client cache, even though it seems redundant.
Let your `worldserver` rebuild your `world` DB again on startup.

**Comment by Tauriella** [comment]
thanks for your answer i try this tomorrow

**Comment by Tauriella** [comment]
Now i have tested with an brand new DB TDB_full_world_335.20031_2020_03_16.sql
But with the same result "Wild Turkey" spawns 
i don't know waht happens here?
Any ideas ?

**Comment by Killyana** [comment]
Provide the guids of this turkeys.

**Comment by dr-j** [comment]
Think this is because respawn times get saved in char db not world I reproduced the issue with noblegarden eggs yesterday

Start noblegarden
Loot some eggs
Stop event before they respawn 
Eggs you looted will still respawn but in same place
Loot them and they will continue respawning even though event is not running

**Comment by Tauriella** [comment]
witch char DB table must i delete?

**Comment by Jinnaix** [comment]
Clearing would be the right term or deleting its content. Its the respawn table.
I would never suggest to fully clear it unless the server is just for yourself.

Wiki is completely missing that table btw.

**Comment by Tauriella** [comment]
I deleting the content of the respawn table and it works now
i hope i don't trashed any player. 

Please reopening this thread it's definitiv a bug.

**Comment by Jinnaix** [comment]
We already have a issue for that but we should copy over some infos.
