### ISSUE TITLE
DK Starter Zone: Scourge Gryphons do not fly down

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24330]
**Description:**
Can't interact with or use the Scourge Gryphons in Ebon Hold to fly

**Current behavior:**
Scourge Gryphons can not be interacted with to fly down to ground level.  You can, however, use them to fly from the ground level to Ebon Hold.

**Expected behavior:**
You should be able to use either of the Scourge Gryphons to fly down to ground level.

**Steps to reproduce the problem:** 

- Create DK
- Do a couple of starter quests
- Try to use Gryphons to fly down

----------
**Branch(es):** master

**TC rev. hash/commit:** 569f1c9

**Operating System:** Windows 10

**Comment by ImmortalusDev** [comment]
I can confirm this on master.

**Comment by sueastward** [comment]
> ```sql
>  UPDATE `creature_template` SET `npcflag`=16777216 WHERE `entry`=29488;
Add Spellclick flag.
