### ISSUE TITLE
GM command - .tele #name #location

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24331]
**Description:**
The GM command "tele  [name] [location]" always returns an error

**Current behavior:**
When trying to teleport a player to a specified location, when you type the command above it will return an error of "Location not found!"

**Expected behavior:**
You should be able to type the command and teleport the player, and lettercase should not matter.

**Steps to reproduce the problem:**

- Either know the location, or lookup the teleport location using the **_lookup tele xxxx_** command.
- Enter the command **_tele playername locationname_**
- It will return an error as stated above.
- To verify the location is correct, you can teleport yourself to that location using **_tele xxxx_**

**`Example commands:`**  `tele Shauren Orgrimmar, tele funjoker crossroads`

----------
**Branch(es):** master

**TC rev. hash/commit:** 569f1c9

**Operating System:** Windows 10

**Comment by jackpoz** [comment]
I think it's ".tele name <character name> <location>", at least this is what the code says

**Comment by Aokromes** [comment]
yes, tele without param is to tele self to location, tele another char needs tele name someone location.

**Comment by mcsescott** [comment]
No, this is a valid command and an issue.  It worked on previous cores / builds.  In addition, if you look at the GM command reference page, you will see it.

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130065/gm+commands



`tele name | 1 | Syntax: .tele name [#playername] #location Teleport the given character to a given location. Character can be offline. To teleport to homebind, set #location to "$home" (without quotes).`

**Comment by mcsescott** [comment]
Oh wait...  I think I see what you mean ... let me test it

**Comment by Jinnaix** [comment]
you just quoted yourself wrong ;)
> Syntax: .tele name [#playername] #location

**Comment by mcsescott** [comment]
Yes, I just tested.  I apologize - I was being stupid and used the wrong command ... I was not using the word "name" in the command.  It was late last night.

Thank you for correcting me.
