### ISSUE TITLE
Please update the software  Visual Studio & Boost

### ISSUE THREAD

**Issue by NoRRt** [TrinityCore/TrinityCore#24332]
Add New Last Ver Microsoft Visual Studio 2019 16.5.0 
Boost Version1.72.0
For Support the TrinityCore

**Comment by DrThum** [comment]
No

**Comment by Ovahlord** [comment]
Eeeeh. U know that both is supported and compiles just fine?

**Comment by jackpoz** [comment]
please follow the issue template when opening an issue

![image](https://user-images.githubusercontent.com/1153754/77083268-852a3680-69fd-11ea-9122-a50eb20afb26.png)

boost 1.72 and Visual Studio 2019 16.5 are supported in branch 335 (I tested it yesterday) (but we don't even know which commit hash you are using)

**Comment by jackpoz** [comment]
btw it might be your cmake installation is too old (but then again, we have no clue what error you received)
