### ISSUE TITLE
Сamera Error

### ISSUE THREAD

**Issue by mindevis** [TrinityCore/TrinityCore#24335]
**Description:**
Camera freezes after playing the opening game clip after creating a new character

**Current behaviour:**
After creating the character, the introductory video is played, after playing this video, the camera freezes.
Video: https://youtu.be/Ns5ncfwTB5Q

**Expected behaviour:**
After creating the character, the introductory video is played, after playing this video, the camera should go to normal and allow the character to be controlled

**Steps to reproduce the problem:**

1. Create a new character.
2. Enter the game world
3. Wait until the video clip is fully played

**Branch(es):**
master

**TC rev. hash/commit:** 
TrinityCore rev. ab36cb9b61ee+ 2020-03-17 18:49:32 +0100 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:** 
Windows 10, Windows Server 2019. Debian 10.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24258
