### ISSUE TITLE
Error in building solution [master][SSL][CRYPTO]

### ISSUE THREAD

**Issue by Emiut** [TrinityCore/TrinityCore#24336]
I get this error when i want to build solution and i test every thing !
The error log : **[https://gofile.io/?c=y2lLCj](https://gofile.io/?c=y2lLCj)**
Sorry it's my first time that i'm trying to do this kind of things !

**Cloned branch: **master** **
**CMakeVer: **3.15.7** **
**OpenSSLVer: **1.0** **
**Sys Arch: **64** **
**VS ver: **1.6.5 2019** **
**TrinityCore revision: **ab36cb9b61ee+ 2020-03-17 18:49:32 +0100** **

**Comment by jackpoz** [comment]
this kind of issues might fit better on the forum/discord chat as it's not a code issue but something happening on your installation only.
