### ISSUE TITLE
Wintergrasp not start

### ISSUE THREAD

**Issue by N3PH4L3M** [TrinityCore/TrinityCore#24337]
Wintergrasp does not start.
There are walls that are not generated, the door of the relic does not appear at the beginning.
NPCs do not correspond to the faction that controls the map.
The walls and towers do not appear on the minimap, it is practically blank.
I only use the trinity database and the core in its latest version.

**Branch(es):** 3.3.5, 

**TC rev. hash/commit:** TrinityCore rev. f0fe5f8b669f 2020-03-19 00:17:36 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using World DB: TDB 335.20031

**Operating system:**  OS Windows 10 x64

**Comment by Aokromes** [comment]
centuplicate. wintergrasp is disabled by default because to buggy.

**Comment by jjo72ddd** [comment]
@Aokromes

Wait a minute, this is a very big problem, because this is the main battlefield. How can we fix it?

**Comment by Faq** [comment]
@jjo72ddd you can help finish #22700

**Comment by jjo72ddd** [comment]
> @jjo72ddd you can help finish #22700

thanks, i'm ready to start
