### ISSUE TITLE
Core/AI: Creature Minions/Pets dont react to masters combat state

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#24340]
**Description:**

As it seems right now, minions & pets of creatures only get into combat with you if you attack them directly or if you are close enough for triggering their own aggro range. They dont react at all to their masters combat state. I am not sure if "masters combat state" is the correct term, but i think people will understand what i want to describe here.

**Current behaviour:**

Minions/Pets of creatures dont react to their masters combat state.

**Expected behaviour:**

Minions/Pets of creatures should react to their masters combat state.

**Steps to reproduce the problem:**

.go xyz -7481.180664 -4289.866699 10.449110 1 3.021416
Stay away far enough to not trigger aggro range
.damage 1 on Wastewander Shadow Mage

He moves to you and starts casting or directly starts casting if you are close enough. In each case, his Voidwalker wont react to you as long as you stay out of the Voidwalkers personal aggro range.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6259763469826526fc26b07ff20885d5b04a791f

**Operating system:** 

Windows 10

**Comment by Rushor** [comment]
can you try ith a normal spell damage? i think ".damage 1" bugs scripts at some point

**Comment by Jinnaix** [comment]
Same result - i noticed this while questing with a non-gm character and replicated it in different situations with spells and commands afterwards.

**Comment by Faq** [comment]
so https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=5617 summoned voidwalker via spell is actually a IsGuardianPet(), but here it is handled only for players https://github.com/TrinityCore/TrinityCore/blob/630e84e8bcfc0913f95044610bac5e5e0c9d3400/src/server/game/Entities/Unit/Unit.cpp#L692

**Comment by Rushor** [comment]
```
if (victim->GetTypeId() == TYPEID_PLAYER && attacker != victim)
    {
        // Signal to pets that their owner was attacked
        Pet* pet = victim->ToPlayer()->GetPet();

        if (pet && pet->IsAlive())
            pet->AI()->OwnerAttackedBy(attacker);
    }

    // Signal the pet it was attacked so the AI can respond if needed
    if (victim->GetTypeId() == TYPEID_UNIT && attacker != victim && victim->IsPet() && victim->IsAlive())
        victim->ToPet()->AI()->AttackedBy(attacker);
```

by Sunwell, but that requires updates
