### ISSUE TITLE
master 8.3.0.33775 login

### ISSUE THREAD

**Issue by kicho** [TrinityCore/TrinityCore#24355]
when i select realm in game i get You have been disconnected from server : WOW51900319

and in worldserver i see this:

WorldSocket::HandleAuthSession: Missing auth seed for realm build 33775

**Comment by Aokromes** [comment]
it works, it's yuor side fail

**Comment by kicho** [comment]
care to elaborate?

**Comment by Shauren** [comment]
Are you using mac? mac client is not supported

**Comment by kicho** [comment]
No i am.using windows 10 x64 and client 33775 and i can login to retail with it, but when trying on my serv i get that

**Comment by Shauren** [comment]
Update your auth database. You are missing the latest update

**Comment by kicho** [comment]
yes, thank you, working now, i assumed it was included in base auth.sql file

Best Regards
