### ISSUE TITLE
Database.dll

### ISSUE THREAD

**Issue by Asunahype** [TrinityCore/TrinityCore#24358]
Hey everyone,

Sorry in advance if this is not the right section to put this kind of problem... but when I try to launch my authserver.exe it gives me an error that it can't find database.dll

I've already asked multiple developers what the solution should be on this one - but no one ever got this error...

Anyone can help me here?

**Comment by Aokromes** [comment]
this is not a forum.
https://community.trinitycore.org/

**Comment by illfated** [comment]
@Asunahype : Looks like you have got a personal configuration problem. Please use the TrinityCore forum pages or ask in IRC (or discord) if you would like a more dynamic feedback. The issue pages are meant for reporting source code problems or TrinityCore database (TDB) content errors.

**Comment by illfated** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC
