### ISSUE TITLE
The NPC did not follow the waypoint

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24351]
Description:
It's a pervasive problem, not just in the Undercity.

.go cr id 4571
![bug1](https://user-images.githubusercontent.com/3367999/77447480-b1451d80-6e2a-11ea-92b1-8f864e5329aa.gif)

.go cr id 16584
![bug2](https://user-images.githubusercontent.com/3367999/79101298-d4644c80-7d9a-11ea-8266-fc290bd42fe4.gif)

.go cr id 3209
![bug9](https://user-images.githubusercontent.com/3367999/79101951-4ee19c00-7d9c-11ea-92e0-942206e5ae89.gif)

Branch(es):
3.3.5

TC rev. hash/commit:
b166d12cbef07a72828d8d20a2130926a5cae47e

Operating system:
CentOS

**Comment by Killyana** [comment]
When the npc moves from point 30 to 31 it will choose a weird path:
![image](https://user-images.githubusercontent.com/6587064/77453126-20088380-6df7-11ea-923e-380c59d086cb.png)

**Comment by dr-j** [comment]
Disable pathing and it works fine this is not only npc in undercity where this happens happens with a couple of the dark rangers during there paths too

**Comment by Rushor** [comment]
Should we disable path finding for all creatures in undercity?

**Comment by Rushor** [comment]
```sql
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|0x20000000 WHERE  `entry` IN (36224, 36225, 36226, 4571);
```

**Comment by Ovahlord** [comment]
No. That's a hack. It's a obvious bug so it deserves to get fixed properly

**Comment by aleigood** [comment]
The issue has been updated and this should be the same cause.

**Comment by aleigood** [comment]
Has been fixed and tested.
https://github.com/TrinityCore/TrinityCore/commit/c0b75bf40da8b447a2f3533dabbfad9eba7c6ea1

**Comment by Killyana** [comment]
Not fixed for me

**Comment by aleigood** [comment]
> Not fixed for me

I tested both and found no problems, is it because I didn't re-extract mmaps?

**Comment by Killyana** [comment]
Yes

**Comment by jackpoz** [comment]
Testing the case of ".go cr id 4571" on 6e34e07c4800 I can't reproduce the issue .
Please, always include .go xyz coordinates (with map id included in the command) when reporting issues that do require a particular location.

Maybe a recent commit fixed it

**Comment by aleigood** [comment]
I used the new map data and tested it. These three problems have been fixed
