### ISSUE TITLE
[3.3.5a] Heroic Ingvarr the Plunderer's Dark Smash is not breakable with LoS

### ISSUE THREAD

**Issue by wotlk-enthusiast** [TrinityCore/TrinityCore#24361]
**Description:**
In Heroic Utgarde Keep, Ingvar the Plunderer's Dark Smash is supposed to be breakable with line of sight on the pillars around the arena, and currently it is not.

**Current behaviour:**
Breaking Line of Sight with Ingvar when he's casting Dark Smash still causes damage.

**Expected behaviour:**
Breaking Line of Sight with Ingvar when he casts Dark Smash should cause the damage to not affect you.
**Steps to reproduce the problem:**

1. Enter Heroic Utgarde Keep
2. Kill Ingvar the Plunderer to engage the 2nd phase of the attack
3. Fight him until he casts Dark Smash
4. Break line of sight using one of the pillars (Warlock teleport spell is great for this)
5. Receive damage

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. b166d12cbef0 2020-03-21 21:14:49 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Online players: 0 (max: 6)
Active connections: 0 (max: 6) Queued connections: 0 (max: 0)
Server uptime: 1 Day 10 Hours 22 Minutes 59 Seconds.
Update time diff: 50.

**Operating system:** Linux

**Comment by Faq** [comment]
You have proof that standing behind pillar it shouldn't get any damage?

**Comment by Aokromes** [comment]
You can LoS his roars, I did it myself today. You can't, however, LoS his Dark Smash's damage everyone effect.


https://es.wowhead.com/npc=23954/ingvar-el-desvalijador#english-comments

**Comment by wotlk-enthusiast** [comment]
Oh, i've been doing this encounter wrong my whole life.  Whoops! Sorry for wasting everyone's time. :(

**Comment by illfated** [comment]
You and me both. I thought I remembered hiding behind the pillars during the boss fight because of the Dark Smash event, but I must be remembering something else, like the resurrection or some other flashing light event which could stun the player.
