### ISSUE TITLE
Can I enable the Wintergrasp

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24362]
I want to enable the Wintergrasp, but I am worrying when reading the following comment.
(1 Enabled, Experimental as in incomplete, bugged and with crashes)
I want to figure out the current version 3.3.5 whether fixed this worrying. Is this comment outdate?

**Comment by Aokromes** [comment]
it's still bugged. this is not a forum.

**Comment by wplatform** [comment]
Why not try to fix it?

**Comment by Aokromes** [comment]
if it was that easy....

**Comment by wplatform** [comment]
Imagine that you are game master and your player asks you why not enable the Wintergrasp battlefield. I can say my server bugged?

**Comment by wplatform** [comment]
努力fix它，加油！

**Comment by illfated** [comment]
@wplatform : We have tried to fix it, but we don't have time or enough verified data.
None of us are paid thousands of dollars to work on it as their only job.
https://github.com/TrinityCore/TrinityCore/search?q=Wintergrasp&state=open&type=Issues
