### ISSUE TITLE
[Suggestion] Log ID of Realm when logging IP Actions to DB

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24377]
**Description:**

We need to start logging the ID of the realm when a new entry is made in the logs_ip_actions table. 

Let's say you got character Bob with GUID 15 on realm A and you got John with GUID 15 who is on realm B. When Bob logs into his realm a login record is made to the logs_ip_actions table when John logs into his realm a login record is also made to the logs_ip_actions table. If you were to need to track Bob's login activity, etc it could cause confusion as Bob has the same GUID as John. Even if both characters are on the same account, you may need to track a specific characters IP activity.

**Current behaviour:**

The IP action system does not log the realm ID to logs_ip_actions which may cause confusion as to which character it is.

**Expected behaviour:**

We should log the ID of the characters realm in order to avoid confusion if that character has the same GUID as another character on a different realm.

**Steps to reproduce the problem:**

1. Follow the example I made in the description above.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. dcd907a63a46+ 2020-03-29 22:47:47 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server Standard 2016

**Comment by jackpoz** [comment]
It sounds good to add the realm ID to the table. Please note that the logs_ip_actions table was added as PR years ago https://github.com/TrinityCore/TrinityCore/pull/11976 and it would be nice if bugfixes/new features could be added as PRs too from community contributors.

**Comment by LordWaycrest** [comment]
> It sounds good to add the realm ID to the table. Please note that the logs_ip_actions table was added as PR years ago #11976 and it would be nice if bugfixes/new features could be added as PRs too from community contributors.

I think it is a must-do thing, especially if you got multiple realms because if 2 characters on different realms have the same GUID and it is being logged to the logs_ip_actions table then you'll never know which character it actually is, especially if both on the same account.

And yes I agree.

**Comment by jackpoz** [comment]
would you like to work on it ? should I assign the issue to you on GitHub ?

**Comment by LordWaycrest** [comment]
> would you like to work on it ? should I assign the issue to you on GitHub ?

Oh, I'm useless at coding, but if there is any other way I can help to implement this then sure. :-)

**Comment by LordWaycrest** [comment]
@jackpoz Can you assign me so I can look into this? Thank you

**Comment by jackpoz** [comment]
Done. Feel free to ask me questions if you need a hand, you can find me on irc too (I might reply there with some hours of delay :P )

**Comment by LordWaycrest** [comment]
> Done. Feel free to ask me questions if you need a hand, you can find me on irc too (I might reply there with some hours of delay :P )

You wouldn't have Discord by any chance, would you?

**Comment by jackpoz** [comment]
I rarely check it so it's like not having it

**Comment by illfated** [comment]
There is a relay between a TC discord channel and the TC IRC channel, but I would not count on it being 100% accurate in updating between the channels.

**Comment by zartech22** [comment]
Hello, I've implemented this new feature if you want. I could do the PR

**Comment by illfated** [comment]
Feel free to open a PR, if you have found a working method. Please make sure your PR content is built on a git branch, not the main 3.3.5 tree.

**Comment by zartech22** [comment]
OK, no problem. Don't worry, it's not my first PR here 😉

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/56f20d69a6ab23a9818f77fd4e2df541a7c30f0e
