### ISSUE TITLE
Ulduar bosses

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24389]
Ulduar raid has the following problems:

1. When repairing machines, no energy is given
2. You cannot pick up barrels with the same energy with a hook
3. Storm Beacon only deals damage near
4. Resin slowdown also doesn't work on Flame Leviathan

Branch(es): 3.3.5
TDB: 335.20021
Ubuntu 18.04
Rev. 40acf3c

**Comment by Aokromes** [comment]
search again on tracker.

**Comment by Faq** [comment]
+never report more than 1 issue in one ticket :)
