### ISSUE TITLE
error to work Worldserver.exe .db2 files

### ISSUE THREAD

**Issue by damiancete** [TrinityCore/TrinityCore#24382]
Some required *.db2 files (250 from 1) not found or not compatible:
Achievement.db2
AnimationData.db2
AnimKit.db2
AreaGroupMember.db2
AreaTable.db2
AreaTrigger.db2
ArmorLocation.db2
Artifact.db2
ArtifactAppearance.db2
ArtifactAppearanceSet.db2

**Comment by MaxtorCoder** [comment]
1. Follow the issue template
2. Extract the db2 files
3. It is 1000% on your side.

**Comment by Aokromes** [comment]
picnic.

**Comment by damiancete** [comment]
but it extract the db2 files...

**Comment by MaxtorCoder** [comment]
Again, issue is on your side.

**Comment by damiancete** [comment]
where can i search help?

**Comment by illfated** [comment]
@damiancete : You can either post a question in the TrinityCore forum pages (https://community.trinitycore.org/) or ask in the #trinity help channel on IRC: #Trinity @ irc.rizon.net (see also the IRC page in the TC wiki pages: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC).
