### ISSUE TITLE
Dungeon Finder for level 80

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24380]
After completing the quests sequence (which starts at Dalaran), these 4 dungeons were supposed to open, if I'm not mistaken.

![изображение](https://user-images.githubusercontent.com/24715026/78087373-92fe9500-73c9-11ea-888e-def0861edf6f.png)

The first quest is taken in Dalaran from a bank that is closer to the tavern of your faction. The next one is in the Forge of Souls, a quest to kill two bosses there. And finally, the next one will send you to the Pit of Saron. There will be a continuation of the chain - 2 quests that will open access to the Halls of Reflection.

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. 40acf3c

**Comment by Faq** [comment]
Could you add quest links with ids? https://tcubuntu.northeurope.cloudapp.azure.com/aowow/

**Comment by Aokromes** [comment]
learn2play.

https://i.imgur.com/s2GU8UZ.png
https://i.imgur.com/S06e1Xv.png
https://i.imgur.com/0cz7FTr.png

**Comment by mcsescott** [comment]
> learn2play.
> 
> https://i.imgur.com/s2GU8UZ.png
> https://i.imgur.com/S06e1Xv.png
> https://i.imgur.com/0cz7FTr.png

Classic...  Made my day.

**Comment by illfated** [comment]
> Classic... Made my day.

Sort of did that for me too. It has been more than 5 years since someone I know threw the phrase "L2P !!"  at someone within range of my hearing.
