### ISSUE TITLE
The fat man swims in shallow water

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24396]
Description:
The fat man swims in shallow water. GUID: 128082 Entry: 16018
.go xyz 3034.489990 -3177.299316 294.063263 533

![bug1](https://user-images.githubusercontent.com/3367999/78502077-c0fd2400-7791-11ea-892d-2fb417699f4a.gif)

Branch(es):
3.3.5

TC rev. hash/commit:
b166d12

Operating system:
CentOS

**Comment by Faq** [comment]
He is kissing your boots. Could you add creature info?

**Comment by Smerdokryl** [comment]
Maybe add 
16384 | 0x0000 4000 | UNIT_FLAG_CANNOT_SWIM
and/or remove
32768 | 0x0000 8000 | UNIT_FLAG_SWIMMING

**Comment by Killyana** [comment]
No the unitflag is correct, the issue is npcs in short water must get their speed reduce it a little bit instead swimming.

**Comment by aleigood** [comment]
Has been fixed and tested.
https://github.com/TrinityCore/TrinityCore/pull/24539

**Comment by Killyana** [comment]
Not fixed

**Comment by Jinnaix** [comment]
Cant replicate it, seems to be fixed - 0b7b7f10f90eb5ef25c47749455572bcaa662d98

**Comment by offl** [comment]
Me too

**Comment by Jinnaix** [comment]
might be, yes, i remembered your fixes for that and had that issue bookmarked, so i rechecked it :)
