### ISSUE TITLE
Core/Maps: Fall from damage in sea

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24392]
**Description:**
.go xyz 10093.84 -6906.91 1.374 530
Swim in north direction
At some point, character dies. 
Reason: Fall

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. bd64deee3a08

**Comment by illfated** [comment]
You might want to edit the issue title to get the correct meaning.
<details>

Title correction suggestion: **Core/Maps: fatal damage from falling in the sea**
or maybe this:  **Core/Maps: Fall damage in the sea**

Maybe even this: **Core/Maps: dying from fall damage while swimming in the sea**

</details>

Anyway, issue confirmed. Swim ≈ 5-10 seconds north from xyz 10093.84 -6906.91 1.374 530 and you will need to resurrect (unless you are using `.cheat god` )

TrinityCore rev. 593efba961f1 2020-03-31 16:35:31 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
```
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.1c  28 May 2019)
Using Boost version: 1.67.0
Using MySQL version: 80019
Using CMake version: 3.13.4
Compiled on: Linux 5.3.0-1018-azure
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997956640 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20031
```
Tested on https://tcubuntu.northeurope.cloudapp.azure.com/

**Comment by Jildor** [comment]
Yep, seems old issue, About rev 2017 I remember happens too xD
seems just in the line of change zone you die, if you use .revive and continue you don't die.

**Comment by illfated** [comment]
As someone who didn't know about it before, while using a GM character with `,cheat god` on, my character started swimming on auto-move, then suddenly stopped moving, with HP=1. 😜

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9f0b5526f070abc7460a31ea599e780f164a36b2
