### ISSUE TITLE
DB/Spawns: Temple of winter

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24406]
**Description:** Some dead npcs are missing
![image](https://user-images.githubusercontent.com/6587064/78710187-30e7e780-7915-11ea-97bc-a0df880e4ceb.png)

**Steps to reproduce the problem:**

1. .go c 127296

**Branch(es):** Both

**TC rev. hash/commit:** rev. 0844ad2ff00f

**Comment by illfated** [comment]
Thanks for refreshing my memory of seeing that tower platform so empty last time I played around in that area. ( I ignored it at the time, but it is still in the back of my mind.)
