### ISSUE TITLE
Core/Spell:  Auto attacks hitting a shielded player will display miss instead absorb

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24402]
**Description:** If you auto attack a player with a shield like spell=48066 it will display miss instead of absorb.

**Steps to reproduce the problem:**

1. Connect 2 chars
2. Start a duel
3. .cast 48066 by player 1
4. auto attack player 1 by auto attacks (spells will display absorb properly)

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 0844ad2ff00f

**Comment by joshwhedon** [comment]
Note that from what I saw, on the core side, it is still treated as an absorb. However it does not seem to send the right packets to the client.

**Comment by joshwhedon** [comment]
Found the issue. When multiple item proto damage for melee was implemented, Unit::CalculateMeleeDamage was updated. Except the result is that at the end of the method, we never set the full absorb flag, if there is only one item proto (because to set full absorb, both need to be full absorb).
Note that this actually has an impact on procs, because now, everything will proc on absorb, even spells not supposed to proc on full absorb.

**Comment by Jildor** [comment]
are you saying this commit?
https://github.com/TrinityCore/TrinityCore/commit/f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb#diff-4522eeffcbc961602e86620011a2d579

**Comment by Jildor** [comment]
you say this commit right?
https://github.com/TrinityCore/TrinityCore/commit/f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb

I try with a weapon that have secondary damage like those:
https://github.com/TrinityCore/TrinityCore/issues/19081#issuecomment-280916269

and appear absorb in combat log, so yes, this commit is the cause

**Comment by Jildor** [comment]
and you are right @joshwhedon I try to do this only for test:
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 52db8670ca..920eeb42fd 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -1378,7 +1378,8 @@ void Unit::CalculateMeleeDamage(Unit* victim, CalcDamageInfo* damageInfo, Weapon
     if ((tmpHitInfo[0] & HITINFO_FULL_ABSORB) != 0)
     {
         // only set full absorb whenever both damages were fully absorbed
-        damageInfo->HitInfo |= ((tmpHitInfo[1] & HITINFO_FULL_ABSORB) != 0) ? HITINFO_FULL_ABSORB : HITINFO_PARTIAL_ABSORB;
+        // damageInfo->HitInfo |= ((tmpHitInfo[1] & HITINFO_FULL_ABSORB) != 0) ? HITINFO_FULL_ABSORB : HITINFO_PARTIAL_ABSORB;
+        damageInfo->HitInfo |= HITINFO_FULL_ABSORB;
     }
     else
         damageInfo->HitInfo |= (tmpHitInfo[0] & HITINFO_PARTIAL_ABSORB);
```
and I can't reproduce the issue.

so, we need check better this checks, maybe check if tmpHitInfo have more than one weapon damage, do you have any fix or suggestion?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5e15406278a8deeed422c4e0c149db066a737e15
