### ISSUE TITLE
Random Love is the Air Game Object Spawned Outside of Event

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24400]
**Description:**

Come across a random Love is in the Air game object that is still spawned when it shouldn't be.

**Current behaviour:**

N/A

**Expected behaviour:**

Should only be spawned whilst the Love is in the Air event is active.

**Steps to reproduce the problem:**

1. Go to the cords 60.4, 47.0 (Stormwind City between Cathedral Square & The Dwarven District)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. caf4c4cf2bc9 2020-04-06 00:36:56 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by Killyana** [comment]
Provide at least a screen if you cannot get the guid

**Comment by Killyana** [comment]
[Floating, Medium - MFF] GUID: 26524 ID: 181354  ?

**Comment by wotlk-enthusiast** [comment]
Cannot reproduce.  My Stormwind tunnel looks clear.

.go xyz -8465 684 99 0 5.2
.gobject near  (tells me 0)

TrinityCore rev. dcd907a63a46+ 2020-03-29 22:47:47 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Online players: 1 (max: 1)
Active connections: 1 (max: 1) Queued connections: 0 (max: 0)
Server uptime: 14 Minutes 9 Seconds.
Update time diff: 50.

**Comment by Killyana** [comment]
It's not linked to the event, but there's some others, not sure if they are part og the event or not:
``` sql
SELECT * FROM  `gameobject` WHERE `id`=181354 AND `guid` NOT IN (SELECT guid FROM game_event_gameobject);

**Comment by Killyana** [comment]
They are all event's gobs https://youtu.be/DUxic50UxTc?t=315

**Comment by LordWaycrest** [comment]
https://imgur.com/a/PC4wfav

**Comment by LordWaycrest** [comment]
Oh was it a midsummer game object? lol
