### ISSUE TITLE
[master] Achievement does not unlock artifact appearance

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/TrinityCore#24415]
**Steps to reproduce the problem:**

1. Take artifact, say 128941 - Scepter of Sargeras
2. Add achievement, say 10460 - This Side Up, which is an appearance prerequisite 
3. Use artifact forge
4. Appearance is still locked

**Branch(es):**

master

**TC rev. hash/commit:** 

e5b12a7

**Operating system:** Debian (WSL)

**Comment by Shauren** [comment]
Working as intended, you also need 10746
