### ISSUE TITLE
MySQL SSL Push breaks compile usingMySQL 8

### ISSUE THREAD

**Issue by Exitare** [TrinityCore/TrinityCore#24410]
**Description:**

The commit ae553f89664a4baade80020856c9ff66323de963 accidentally broke tc build using mysql v8.
CompileLog: 
https://pastebin.com/xjSz82jr 

**Current behaviour:**

The build fails because of linker errors.

**Expected behaviour:**

The build should be successfull.

**Steps to reproduce the problem:**

1. Use mysql 8 to create the solution
2. Compile

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

bea850fb73c6c3b3cc4e51bd3a42d178947882a5

**Operating system:** 
Windows 10 

I think the build fails because of this:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html

Section: Security Notes

> For the C API, MYSQL_OPT_SSL_ENFORCE and MYSQL_OPT_SSL_VERIFY_SERVER_CERT options for mysql_options() correspond to the client-side --ssl and --ssl-verify-server-cert options and have been removed. Use MYSQL_OPT_SSL_MODE with an option value of SSL_MODE_REQUIRED or SSL_MODE_VERIFY_IDENTITY instead.

**Comment by Shauren** [comment]
579d41acc5ca3af9900b546dc3e910a595cee066
