### ISSUE TITLE
Investigate the Blue Recluse

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24414]
**Current behaviour:**
Unable to use **chest of containment coffers**  on **Rift Spawn**

**Expected behaviour:**
After killing **Rift Spawn** he should not run away from you and you can use the **chest of containment coffers** on it

https://classic.wowhead.com/item=7247/chest-of-containment-coffers
https://classic.wowhead.com/npc=6492/rift-spawn,
https://classic.wowhead.com/quest=1920
https://youtu.be/f0NxCuitVBI

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. 40acf3c

**Comment by illfated** [comment]
**DB/Quest: Investigate the Blue Recluse** #24024

**Comment by illfated** [comment]
Rule of thumb: Search for existing issues before opening a new one. If one exists, post there instead of opening a new ticket.

**Comment by illfated** [comment]
@shamage : Anything different here, compared to your ticket?

**Comment by jjo72ddd** [comment]
in my opinion another problem is described there

**Comment by jjo72ddd** [comment]
should i close this problem?

**Comment by Jinnaix** [comment]
The issue is different as the other one, but that still would better be placed in one ticket.
No sense in working on one problem if there are multiple in such a little quest.

**Comment by illfated** [comment]
As long as the problems are so closely related that it will be possible to fix both with the same solution, it would be practical to post the information into the older ticket. If separate solutions are needed, then it would make sense to keep both tickets.

**Comment by jjo72ddd** [comment]
can this problem be solved by adding \ modifying \ deleting to the database? or do you need to edit the code?

**Comment by illfated** [comment]
I don't know. If you read the comments https://github.com/TrinityCore/TrinityCore/issues/24024#issuecomment-576061348, https://github.com/TrinityCore/TrinityCore/issues/24024#issuecomment-611149456, and https://github.com/TrinityCore/TrinityCore/issues/24024#issuecomment-611149860, maybe you can get some ideas for where to start.

**Comment by dr-j** [comment]
The rift spawn needs to be stunned by damaging to 1% hp before containment coffer can be used the rift spawns self stun on 1% hp

**Comment by jjo72ddd** [comment]
I left rift spawns 11 hp. Failed, system message: no target

**Comment by shamage** [comment]
Such a ticket has already been created : [look ](https://github.com/TrinityCore/TrinityCore/issues/24024)

**Comment by shamage** [comment]
> @shamage : Je tu niečo iné ako váš lístok?

It is the same !

**Comment by shamage** [comment]
> @shamage : Anything different here, compared to your ticket?


It is the same !

**Comment by jjo72ddd** [comment]
@shamage Do you have any ideas about this assignment?

**Comment by shamage** [comment]
there is a sequence of events, maybe it would be good to leave it to two tickets for a better overview or to merge it so that you can work on it better? Any opinions?

**Comment by shamage** [comment]
@jjo72ddd  :   unfortunately not yet

**Comment by phutch11** [comment]
When I play out this quest it's spawning 4 Rift spawns and even if the quest is grey, at level 23 I cannot complete this quest. It's been sitting there.

This is something I haven't seen in any other "Blue Recluse" related posts. Is this something worth posting an issue about?

**Comment by jjo72ddd** [comment]
At level 15 they are not visible with .gm off. 
I think, as said above, it is better to write a problem in the main topic

**Comment by phutch11** [comment]
Ahh got it! I thought the link above was to the old closed issue but this is a newer one which I missed on the radar and correctly addresses my issue. Will bookmark and follow it instead.

**Comment by dr-j** [comment]
If it helps this was original script both sw and uc quests use same script https://github.com/TrinityCore/TrinityCore/commit/fa770897ccbb2274cfebbfb5409c7a6dc0879e2e

**Comment by Killyana** [comment]
Better to keep one ticket per quest

**Comment by dr-j** [comment]
The despawn issue may actually be due to core changes or it may because the rift spawn summons bunny which in turn summons filled containment coffer and then immediately despawns this maybe what’s causing the issue as have noticed that creatures summoned with event 12 now despawn when summoner despawns this never used to happen
