### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by obsidean** [TrinityCore/TrinityCore#24428]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

Build fails

**Expected behaviour:**

Build should finish

**Steps to reproduce the problem:**

1. Create build files  
2. Execute build
3. Execute Xcode
4. Here is the error line:
![Screen Shot 2020-04-10 at 11 51 05 AM](https://user-images.githubusercontent.com/5403305/78999713-9d373680-7b21-11ea-94e5-1ff7b8a46e2d.png)

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

a0d508885000327f23b9c04ed454d513aec91fa1

**Operating system:** MAC OS Catalina 10.15.1

**Comment by Aokromes** [comment]
update mysql.

**Comment by illfated** [comment]
@obsidean : if you had followed the issues and PRs here in the TC repository on GitHub, you would have noticed that the new requirement for MySQL is version 5.7.xx or higher.

**Comment by obsidean** [comment]
i installed the wrong version of mysql and i didn't link.
