### ISSUE TITLE
few crashes

### ISSUE THREAD

**Issue by kicho** [TrinityCore/TrinityCore#24429]
[Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/4462059/Crashes.zip)

**Comment by Shauren** [comment]
Useless, all of them. Don't build in Release, use RelWithDebInfo

**Comment by kicho** [comment]
361946419e1a_worldserver.exe_[9-4_16-29-20]

this was built with RelWithDebInfo

**Comment by Shauren** [comment]
That one is known

**Comment by kicho** [comment]
[new.zip](https://github.com/TrinityCore/TrinityCore/files/4464291/new.zip)

here's another one

**Comment by kicho** [comment]
and another one
[new2.zip](https://github.com/TrinityCore/TrinityCore/files/4464384/new2.zip)

**Comment by kicho** [comment]
[3.zip](https://github.com/TrinityCore/TrinityCore/files/4465369/3.zip)
