### ISSUE TITLE
Core: Inventory full when creating an item

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24423]
**Description:** if you try to create https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=31942

You will get a message inventory full even if you have 10 free slots

**Steps to reproduce the problem:**

1. .add 32684 .add  32682 .add  32683 .add  32681
2. Click in one of the items to create the cloack
3. notice the error

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 64246306678c

**Comment by Faq** [comment]
Reverting this https://github.com/TrinityCore/TrinityCore/commit/2a41755b589f215c14c85b1015e71534c1e91a98 works in this case.

**Comment by Shauren** [comment]
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index ab1dbdfe57..3e6de8b9ba 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -6630,13 +6630,17 @@ SpellCastResult Spell::CheckItems(uint32* param1 /*= nullptr*/, uint32* param2 /
 
                     if (m_spellInfo->Effects[i].ItemType)
                     {
+                        ItemTemplate const* itemTemplate = sObjectMgr->GetItemTemplate(m_spellInfo->Effects[i].ItemType);
+                        if (!itemTemplate)
+                            return SPELL_FAILED_ITEM_NOT_FOUND;
+
+                        uint32 createCount = std::clamp<uint32>(m_spellInfo->Effects[i].CalcValue(), 1u, itemTemplate->GetMaxStackSize());
                         ItemPosCountVec dest;
-                        InventoryResult msg = target->ToPlayer()->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, m_spellInfo->Effects[i].ItemType, m_spellInfo->Effects[i].CalcValue());
+                        InventoryResult msg = target->ToPlayer()->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, m_spellInfo->Effects[i].ItemType, createCount);
                         if (msg != EQUIP_ERR_OK)
                         {
-                            ItemTemplate const* itemTemplate = sObjectMgr->GetItemTemplate(m_spellInfo->Effects[i].ItemType);
                             /// @todo Needs review
-                            if (itemTemplate && !itemTemplate->ItemLimitCategory)
+                            if (!itemTemplate->ItemLimitCategory)
                             {
                                 player->SendEquipError(msg, nullptr, nullptr, m_spellInfo->Effects[i].ItemType);
                                 return SPELL_FAILED_DONT_REPORT;
```

Dropping this her for now, can't test myself atm (this just copies the logic used in `Spell::DoCreateItem` to get the number of created items)

**Comment by Faq** [comment]
It works fine.

**Comment by Shauren** [comment]
That is fine, reusing inventory slot freed by a reagent was never something we did

**Comment by Faq** [comment]
Yes, but we allowed to covert item if there is not full stack, for example 9x https://woehead.way-of-elendil.fr/?item=37702, then using one https://woehead.way-of-elendil.fr/?item=36860 would use slot with those 9

**Comment by Killyana** [comment]
FYI, someone managed to create the cloak using the 4 scales, in same server, no idea why it worked for him.

**Comment by Shauren** [comment]
Because according to raw unprocessed spell data, that spell creates 100 cloaks (so it works if you have 100 free slots). It doesnt actually create 100 cloaks tho, we fix that amount in Spell::DoCreateItem
