### ISSUE TITLE
build error by vs2019.

### ISSUE THREAD

**Issue by cjl3230** [TrinityCore/TrinityCore#24425]
**Description:**

build error by vs2019,I using mysql 5.6.35.
error C2065: “MYSQL_OPT_SSL_ENFORCE”: undeclared identifier

**Current behaviour:**

build error by vs2019,I using mysql 5.6.35.
error C2065: “MYSQL_OPT_SSL_ENFORCE”: undeclared identifier

**Expected behaviour:**

Successful build TrinityCore

**Steps to reproduce the problem:**

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a0d508885000327f23b9c04ed454d513aec91fa1

**Operating system:** CHANGEME OS
win10 1909

**Comment by Aokromes** [comment]
update your mysql to 5.7 .

**Comment by cjl3230** [comment]
thanks

**Comment by cjl3230** [comment]
Can I use mariadb-10.4.12 in windows.I install mariadb-10.4.12 x64.msi in win10.But cmake Can't find it;
