### ISSUE TITLE
[Suggestion] Adding the Feature to dump Account Data

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24424]
**Description:**

I think it would be good to be able to dump account data just like how you can with .pdump to dump character data. Reason being is because:
1.) Players can export their account data to move to another server as well.
2.) ~~It would help with GDPR requests. Oh, the pain had to go through when I had to export account data manually.~~

**Current behaviour:**

N/A

**Expected behaviour:**

N/A

**Steps to reproduce the problem:**

N/A

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 09b22fd4a50e 2020-04-06 19:22:52 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by Shauren** [comment]
> Oh the pain had to go through when I had to export account data manually.

Working as intended

**Comment by LordWaycrest** [comment]
> Oh the pain had to go through when I had to export account data manually.
> 
> Working as intended

Sorry?

**Comment by Aokromes** [comment]
2.) It would help with GDPR requests. Oh the pain had to go through when I had to export account data manually.

rolf

**Comment by LordWaycrest** [comment]
> 2.) It would help with GDPR requests. Oh the pain had to go through when I had to export account data manually.
> rolf

It is true though, do you realise how much a pain in the ass it was to do that? I was crapping myself worrying that I'd mess something up. lol

**Comment by Aokromes** [comment]
so, you are running a wow server but, yet, you care about GDPR requests.

**Comment by LordWaycrest** [comment]
> so, you are running a wow server but, yet, you care about GDPR requests.

Because I had a request for GDPR, legally we have to fulfil them. Also the feature suggestion isn't just for that.

**Comment by Exitare** [comment]
Legally you are forbidden to run a public wow server. So Aokromes point is still valid.
So to get rid of GDPR request, obey the law and take your server down.

**Comment by LordWaycrest** [comment]
> Legally you are forbidden to run a public wow server. So Aokromes point is still valid.
> To get rid of GDPR request, obey the law and put your server down.

Yes, but I did just say its not all about GDPR, it can be useful to move accounts to other databases

**Comment by SoyTorete** [comment]
It is the most surreal issue I have read, in my group of friends we laughed a lot, sincerely and without offending, @LordWaycrest thanks for the laughter in moments of pandemic.

**Comment by leviathonbeast** [comment]
@LordWaycrest There is soo much wrong with this suggestion. You really should think before you write, your players need to realise playing private servers to circumvent paying blizzard for the privilege is illegal so they have no legal standing to ask for data to adhere to the new GDPR legislation.

**Comment by LordWaycrest** [comment]
> @LordWaycrest There is soo much wrong with this suggestion. You really should think before you write, your players need to realise playing private servers to circumvent paying blizzard for the privilege is illegal so they have no legal standing to ask for data to adhere to the new GDPR legislation.

I think you need to read before you write, I did state many times that it is not just a feature request for GDPR, it can be helpful to move accounts to other servers with different databases.

**Comment by leviathonbeast** [comment]
> > @LordWaycrest There is soo much wrong with this suggestion. You really should think before you write, your players need to realise playing private servers to circumvent paying blizzard for the privilege is illegal so they have no legal standing to ask for data to adhere to the new GDPR legislation.
> 
> I think you need to read before you write, I did state many times that it is not just a feature request for GDPR, it can be helpful to move accounts to other servers with different databases.
> 
> So instead of picking fault at one point, read the others

I don't see how it should be a feature looked into at this stage. You say "different databases on different servers" you're referring to public-facing servers which is not permitted nor is it encouraged by the TrinityCore team.

I cannot think of a situation a developer would need to do this, and if they did it would probably be 1 account, not hundreds ( where 1 account could be done manually for the purposes of their particular scenario) which you are thinking of I assume.

**Comment by LordWaycrest** [comment]
> @LordWaycrest There is soo much wrong with this suggestion. You really should think before you write, your players need to realise playing private servers to circumvent paying blizzard for the privilege is illegal so they have no legal standing to ask for data to adhere to the new GDPR legislation.
> 
> I think you need to read before you write, I did state many times that it is not just a feature request for GDPR, it can be helpful to move accounts to other servers with different databases.
> So instead of picking fault at one point, read the others
> 
> I don't see how it should be a feature looked into at this stage. You say "different databases on different servers" you're referring to public-facing servers which is not permitted nor is it encouraged by the TrinityCore team.
> I cannot think of a situation a developer would need to do this, and if they did it would probably be 1 account, not hundreds ( where 1 account could be done manually for the purposes of their particular scenario) which you are thinking of I assume.

So then tell me why there is a feature that lets you dump character data but not account data, does that not make you wonder?

**Comment by jackpoz** [comment]
I would like to actually be able to log less data for GDPR reasons, like I don't want at all to store in the database the IP of users for more than how it's strictly needed for the login to work (if it's needed at all).

**Comment by LordWaycrest** [comment]
> I would like to actually be able to log less data for GDPR reasons, like I don't want at all to store in the database the IP of users for more than how it's strictly needed for the login to work (if it's needed at all).
> To dump account data, a SQL View should be enough.

I just mean like when you have massive databases, there is a risk of something going wrong when you do it by hand. But if people really don't want it then that is fine.

Also do you mean the IP action logs or the IP stored when the account is created/last logged into?

**Comment by jackpoz** [comment]
The IP stored when account is created/last logged in.

Maybe a worldserver chat command would fit the best, creating a file (txt or xml or json) with the data stored in auth and characters databases. There are a lot of relations between tables to take into account and it might be easy in the beginning to forget one or two.

If you are willing to implement it, please open a PR so I can review and merge it.

Another temporary solution could be a sql script. Something like
```sql
SET @username = 'jackpoz';

SELECT ACC.*
      #,CHARS.*
FROM auth.account AS ACC
WHERE ACC.username = @username;

SELECT CHARS.*
FROM auth.account AS ACC
LEFT JOIN characters.characters AS CHARS ON CHARS.account = ACC.id
WHERE ACC.username = @username;
```
