### ISSUE TITLE
Missing gameobject Brazier of Madness 

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24427]
**Description:**
After using the gameobject, one of the four creature: Hazza'rah(15083), Wushoolay(15085), Renataki(15084), Gri'lek(15082) will spawn.
https://wowwiki.fandom.com/wiki/Gurubashi_Mojo_Madness
https://classic.wowhead.com/item=19931/gurubashi-mojo-madness

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Faq** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=180327

**Comment by Killyana** [comment]
What's the issue here?
The gob is already spawn and liked to the even https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?event=27

**Comment by illfated** [comment]
@aleigood : could you provide a screenshot or log to show what is wrong with that gameobject, specifically to prove that this issue exists somewhere in the TC source or DB?

**Comment by aleigood** [comment]
> @aleigood : could you provide a screenshot or log to show what is wrong with that gameobject, specifically to prove that this issue exists somewhere in the TC source or DB?

The object in cmangos:
![WoWScrnShot_041420_180826](https://user-images.githubusercontent.com/3367999/79224085-1e2d5f80-7e8d-11ea-809b-cfcee31b1ce4.jpg)

In TC:
![WoWScrnShot_041420_192455](https://user-images.githubusercontent.com/3367999/79224139-32715c80-7e8d-11ea-8a28-d27c234dac92.jpg)

The object also exists in the TC database.

**Comment by Aokromes** [comment]
> > @aleigood : could you provide a screenshot or log to show what is wrong with that gameobject, specifically to prove that this issue exists somewhere in the TC source or DB?
> 
> The object in cmangos:
> ![WoWScrnShot_041420_180826](https://user-images.githubusercontent.com/3367999/79224085-1e2d5f80-7e8d-11ea-809b-cfcee31b1ce4.jpg)
> 
> In TC:
> ![WoWScrnShot_041420_192455](https://user-images.githubusercontent.com/3367999/79224139-32715c80-7e8d-11ea-8a28-d27c234dac92.jpg)
> 
> The object also exists in the TC database (entry:180327).

you started event 27 on tc before take screenshot?

**Comment by illfated** [comment]
> you started event 27 on tc before take screenshot?

Good point. Maybe cmangos has got the gameobject and event active all the time, so you can light the fire without following any pre-requisite steps.

**Comment by Killyana** [comment]
There's 4 possible encounter in this area:
* Edge of Madness, Hazza'rah
* Edge of Madness, Renataki
* Edge of Madness, Wushoolay
* Edge of Madness, Gri'lek

Does the gob "Brazier of Madness" is used for this 4 events?

**Comment by dr-j** [comment]
Hmm https://wowwiki.fandom.com/wiki/Edge_of_Madness

Within this area, players will find a lit brazier and a number of tablets along the walls. Of particular interest, the tablet behind the brazier allows alchemists to learn the formula for Gurubashi Mojo Madness. Like the repair bot schematic in Blackrock Depths, this is not an item to pick up but to interact with (fixed device); all alchemists in the raid can learn this formula at the same time. This potion requires Blood of Heroes, Massive Mojo, Black Lotus, and 6 Powerful Mojo to create, but the potion can be traded after it is made, and can often be purchased at the auction house. The only use for this potion is to extinguish the brazier in this room, which starts the event.

**Comment by dr-j** [comment]
~~~sql
DELETE FROM `game_event_gameobject` WHERE  `guid`=28704 AND `eventEntry`=27;

~~~
and .additem 19931 and use on the brazier and the event works and a boss gets spawned

**Comment by aleigood** [comment]
I tested it, and I could use item to put out the fire, but Boss did not appear.

**Comment by Rushor** [comment]
https://i.imgur.com/alwW0e6.jpg

```diff
diff --git a/src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp b/src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp
index 0e05c44d81..6791e6624e 100644
--- a/src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp
+++ b/src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp
@@ -18,6 +18,7 @@
 
 #include "zulgurub.h"
 #include "GameObject.h"
+#include "GameObjectAI.h"
 #include "InstanceScript.h"
 #include "Map.h"
 #include "ScriptMgr.h"
@@ -91,7 +92,43 @@ class instance_zulgurub : public InstanceMapScript
         }
 };
 
+/*######
+## go_brazier_of_madness
+######*/
+
+const uint32 NpcMadnessEntry[] =
+{
+    15083, 15085, 15084, 15082
+};
+
+class go_brazier_of_madness : public GameObjectScript
+{
+    public:
+        go_brazier_of_madness() : GameObjectScript("go_brazier_of_madness") { }
+    
+        struct go_brazier_of_madnessAI : public GameObjectAI
+        {
+            go_brazier_of_madnessAI(GameObject* go) : GameObjectAI(go) { }
+    
+            bool GossipHello(Player* player) override
+            {
+                me->UseDoorOrButton();
+                int Random = rand() % (sizeof(NpcMadnessEntry) / sizeof(uint32));
+                player->SummonCreature(NpcMadnessEntry[Random], -11901.229f, -1906.366f, 65.358f, 0.942f, TEMPSUMMON_DEAD_DESPAWN, 120000);
+    
+                return false;
+            }
+        };
+    
+        GameObjectAI* GetAI(GameObject* go) const override
+        {
+            return new go_brazier_of_madnessAI(go);
+        }
+};
+
+
 void AddSC_instance_zulgurub()
 {
     new instance_zulgurub();
+    new go_brazier_of_madness();
 }
```

UPDATE `gameobject_template` SET `ScriptName`='go_brazier_of_madness' WHERE `entry`=180327;

**Comment by offl** [comment]
> There are tablets on the walls describing each boss; one of these tablets will indicate which boss will spawn by commenting that he is "close to the edge of madness." The particular boss which spawns is chosen according to a spawn calendar, going by the day the instance ID was created. This is somewhat convenient when multiple players are trying to create their trinkets; however, since a player needs all four tokens to create his trinket, this also means that it will take at least a month and a half to acquire the needed parts ... assuming, of course, that there is minimal competition for these tokens.
https://edgeofmadnesscalendar.com/eom

**Comment by offl** [comment]
> Verify which boss will spawn by inspecting the tablets in the Zul'gurub instance around the perimeter of the Edge of Madness.

I found only both texts for Gri'lek

```sql
select * from gameobject_template where data3 IN (6448,6449,6450,6451)
#select * from gossip_menu where menuid IN (6448,6449,6450,6451)
#select * from broadcast_text where id = 10496 or id between 10538 and 10544
#select * from npc_text where broadcasttextid0 = 10496 OR broadcasttextid0 BETWEEN 10538 AND 10544
```

**Comment by offl** [comment]
https://www.youtube.com/watch?v=-6b19qan7hM

https://github.com/r00ty-tc/NostalriusFixed/blob/289cf14001c3cfc62d706f5bf3e296e2a46f8d79/src/scripts/eastern_kingdoms/stranglethorn_vale/zulgurub/instance_zulgurub.cpp#L289-L515

Spell on creature spawn https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=24240
Some other spells https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spells&filter=cr=14:14;crs=2:4;crv=24200:24300#50+2+3+15+5

This looks like the one in the video above https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=24202
Some objects https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=troll+hero#objects

**Comment by Killyana** [comment]
So a new issue must be created?

**Comment by offl** [comment]
Yes
