### ISSUE TITLE
Consumption of scrolls

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24432]
**Description:**
The tip: "A MORE POWERFUL SPELL IS IN EFFECT" is appears and the scroll has be consumed.

**Expected behaviour:**
The scroll should not be consumed.

**Steps to reproduce the problem:**
1. Create a mage character and up to level 80.
2. Cast the highest level of arcane wisdom on yourself.
3. Add the item .additem 2290 and use it.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
961adea

**Operating system:** 
CentOS

**Comment by Faq** [comment]
What is arcane wisdom, can you link it?

**Comment by Killyana** [comment]
https://woehead.way-of-elendil.fr/?spell=43002#spell-group-stack
https://woehead.way-of-elendil.fr/?spell=8097#spell-group-stack
They cannot stack with each other but the scroll mustn't be consumed.

**Comment by adeutscher** [comment]
Related: #18429
