### ISSUE TITLE
Core/SAI: The SAI counter musn't reset when the npc evade (reset)

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24436]
**Description:** If a npc use a SAI counter like  https://woehead.way-of-elendil.fr/?npc=15402
for the quest https://woehead.way-of-elendil.fr/?quest=8488 when it evades the counter will be reset.

This mustn't happen as it will not allow us to control the counter properly

**Steps to reproduce the problem:**

1. Connect a horde char
2. .quest ad 8487
3. .go c id 15402
4. complete the quest 8487 and take quest=8488 from the npc
5. 3 npcs will spawn and attack the quest giver
6. let one attack the quest giver and aggro 2
7. Kill one of your npcs (counter=1)
8. Kill the npc aggro by the quest giver (counter=2, than reset to 0 on evade)
9. kill the last npc (counter must be =3, but it's actually =1)
10. .npc add temp 15656  x2 and kill them (the counter will be 3) and the npc will get the npc_flag back

**Branch(es):** both

**TC rev. hash/commit:** rev. b26302cdd0c

**Comment by Rushor** [comment]
is that issue old?

**Comment by Killyana** [comment]
No idea

**Comment by Rushor** [comment]
is see this:

```
void SmartScript::OnReset()
{
    ResetBaseObject();
    for (SmartAIEventList::iterator i = mEvents.begin(); i != mEvents.end(); ++i)
    {
        if (!((*i).event.event_flags & SMART_EVENT_FLAG_DONT_RESET))
        {
            InitTimer((*i));
            (*i).runOnce = false;
        }
    }
    ProcessEventsFor(SMART_EVENT_RESET);
    mLastInvoker.Clear();
    mCounterList.clear();
}
```

so mCounterList.clear(); for the counter stuff will be called on reset of sai. and reset is called after evade.

**Comment by Rushor** [comment]
possible solution:

```diff
diff --git a/src/server/game/AI/SmartScripts/SmartScript.cpp b/src/server/game/AI/SmartScripts/SmartScript.cpp
index f367e50931..b7c4254d8b 100644
--- a/src/server/game/AI/SmartScripts/SmartScript.cpp
+++ b/src/server/game/AI/SmartScripts/SmartScript.cpp
@@ -179,7 +179,6 @@ void SmartScript::OnReset()
     }
     ProcessEventsFor(SMART_EVENT_RESET);
     mLastInvoker.Clear();
-    mCounterList.clear();
 }
 
 void SmartScript::ResetBaseObject()
@@ -3815,6 +3814,7 @@ void SmartScript::OnInitialize(WorldObject* obj, AreaTriggerEntry const* at)
     ProcessEventsFor(SMART_EVENT_AI_INIT);
     InstallEvents();
     ProcessEventsFor(SMART_EVENT_JUST_CREATED);
+    mCounterList.clear();
 }
 
 void SmartScript::OnMoveInLineOfSight(Unit* who)
```

Now the counter will be reset on ai init. we must then manually reset the counter in the scripts with event Onreset. i can do that if you wish

**Comment by Killyana** [comment]
I think in all SAI scripts we already reset the counter manually.

**Comment by Rushor** [comment]
Really? Okay i ganna check again. Will make a PR of it is ok

**Comment by msoky** [comment]
this issue is very very old...
