### ISSUE TITLE
Attack of aggression by non-hostile creatures

### ISSUE THREAD

**Issue by aleigood** [TrinityCore/TrinityCore#24430]
I don't know how I should describe it, check out the GIF I uploaded. this doesn't always happen, if the creature is at a location near the start of a random path the probability of it happening is higher.

![bug2](https://user-images.githubusercontent.com/3367999/79000973-39902600-7b80-11ea-899c-6539178d79eb.gif)

Branch(es):
3.3.5

TC rev. hash/commit:
961adea

Operating system:
CentOS

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/23993
