### ISSUE TITLE
Map.h:853 in GetRespawnMapForType ASSERTION FAILED: false

### ISSUE THREAD

**Issue by GnaXi** [TrinityCore/TrinityCore#24438]
**Description:**

No longer able to start worldserver after following commit: https://github.com/TrinityCore/TrinityCore/commit/4f33fd3932d362466ee017111895bf14fcc79c88

**Current behaviour:**

Getting an error when trying to start the worldserver:
/src/server/game/Maps/Map.h:853 in GetRespawnMapForType ASSERTION FAILED:
false
Id: 0 InstanceId: 0 Difficulty: 0 HasPlayers: false

**Expected behaviour:**

For the server to start without error

**Steps to reproduce the problem:**

1. Update the server
2. Try to start it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Cannot find this, as I cannot start the server.

**Operating system:** 
Ubuntu 19.10

**Comment by jackpoz** [comment]
doesn't it create a crashlog btw ?

**Comment by GnaXi** [comment]
Nope, unfortunately not.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9cde3ffd1404e784406f385061f4df0f6b429b61
