### ISSUE TITLE
Core/SAI: SMART_ACTION_ENABLE_TEMP_GOBJ

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24439]
**Description:** The action SMART_ACTION_ENABLE_TEMP_GOBJ is no longer working with :
SMART_TARGET_GAMEOBJECT_RANGE=13
SMART_TARGET_CLOSEST_GAMEOBJECT=20

It works only with : SMART_TARGET_GAMEOBJECT_GUID | 14
And SMART_TARGET_GAMEOBJECT_DISTANCE=18

We have lots of scripts that already use this action with this targets

FYI: SMART_ACTION_ENABLE_TEMP_GOBJ is used to respawn gameobjects that are "despawned by default"=use negative respawn time in the DB

**Steps to reproduce the problem:**
Use this SAI
``` sql
DELETE FROM `smart_scripts` WHERE `entryorguid` =6546;
INSERT smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o, COMMENT) VALUES 
(6546, 0, 0, 0, 19, 0, 100, 0, 1957, 0, 0, 0, 0, 70, 600, 0, 0, 0, 0, 0, 20, 103680, 100, 0, 0, 0, 0, 0, 0, "Tabetha - On Quest 'Mana Surges' Taken - Respawn Gameobject 'Mana Rift'");
``` 
1. connect a mage
2. .go c id 6546  (notice outside the house the blue cloud, it's the gob visible in GM ON only as despawned)
3. .quest add 1956
4. .quest comp 1956
5. take the next quest Mana Surges from the npc and notice the gameobject didn't spawn
6. if you change target 20 with 18 it will works

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  rev. b26302cdd0c4

**Comment by joshwhedon** [comment]
Two issues here. For SMART_TARGET_GAMEOBJECT_RANGE
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartScript.cpp#L2650 it should be !e.target.goRange.entry || unit->ToGameObject()->GetEntry() == e.target.goRange.entry
For SMART_TARGET_CLOSEST_GAMEOBJECT the Trinity::NearestGameObjectEntryInObjectRangeCheck seems to be checking for spawned gameobjects only.

**Comment by Rushor** [comment]
code is

```c++
// Success at unit in range, range update for next check (this can be use with GameobjectLastSearcher to find nearest GO)
    class NearestGameObjectEntryInObjectRangeCheck
    {
        public:
            NearestGameObjectEntryInObjectRangeCheck(WorldObject const& obj, uint32 entry, float range) : i_obj(obj), i_entry(entry), i_range(range) { }

            bool operator()(GameObject* go)
            {
                if (go->isSpawned() && go->GetEntry() == i_entry && go->GetGUID() != i_obj.GetGUID() && i_obj.IsWithinDistInMap(go, i_range))
                {
                    i_range = i_obj.GetDistance(go);        // use found GO range as new range limit for next check
                    return true;
                }
                return false;
            }

        private:
            WorldObject const& i_obj;
            uint32 i_entry;
            float  i_range;

            // prevent clone this object
            NearestGameObjectEntryInObjectRangeCheck(NearestGameObjectEntryInObjectRangeCheck const&) = delete;
    };
```

so i would suggest to add a parameter that checks for "spawned" or not similar to NearestCreatureEntryWithLiveStateInObjectRangeCheck

**Comment by Rushor** [comment]
updated for SMART_TARGET_GAMEOBJECT_RANGE

but SMART_TARGET_CLOSEST_GAMEOBJECT should not work in this case i think. SMART_TARGET_CLOSEST_GAMEOBJECT should ONLY work for spawned objects. lots of scripts use that. we need a new targettype that checks for UNSPAWNED objects

**Comment by Rushor** [comment]
Added a new targettype to actually select a closest unspawned object. both issues fixed.
