### ISSUE TITLE
DB/Quest: Warsong Supplies

### ISSUE THREAD

**Issue by alexmocanu** [TrinityCore/TrinityCore#24447]
**Description:**
The quest cannot be completed - unable to complete all it's requirements

**Current behaviour:**
Unable to get the crate of axes from  Wharfmaster Lozgil in Booty Bay

**Expected behaviour:**
Wharfmaster Lozgil should provide the crate of axes
https://classic.wowhead.com/quest=6571/warsong-supplies

**Steps to reproduce the problem:**
1. Go to 71,67 in Ashenvale Forest
2. Take quest from Locke Okarr
3. Go to Booty Bay at 26,73
4. Wharfmaster Lozgil is present but doesn't provide the crate of axes

**Branches:**

3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 2aa32d3beb33 2020-04-12 18:11:16 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**
Debian 10

**Comment by illfated** [comment]
Another case of "read the quest descriptions in detail first", I presume. ;-)
