### ISSUE TITLE
Compil error again 3.3.5

### ISSUE THREAD

**Issue by Tauriella** [TrinityCore/TrinityCore#24444]
I have some compil error's in VS 2019

3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(44,65): error C2079: "WorldPackets::Guild::GuildInfo::Ranks" verwendet undefiniertes class "std::array<std::string,10>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(209,52): error C2079: "WorldPackets::Guild::GuildEvent::Params" verwendet undefiniertes class "std::array<const char *,3>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(265,73): error C2079: "WorldPackets::Guild::GuildPermissionsQueryResults::Tab" verwendet undefiniertes class "std::array<WorldPackets::Guild::GuildPermissionsQueryResults::GuildRankTabPermissions,6>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(32,44): error C2672: "begin": keine übereinstimmende überladene Funktion gefunden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C2893: Fehler beim Spezialisieren der Funktionsvorlage "unknown-type std::begin(_Container &)".
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1911): message : Siehe Deklaration von "std::begin"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : Mit den folgenden Vorlagenargumenten:
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : "_Container=int"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C2784: "const _Elem *std::begin(std::initializer_list<_Elem>) noexcept": Vorlage-Argument für "std::initializer_list<_Elem>" konnte nicht von "int" hergeleitet werden.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\initializer_list(57): message : Siehe Deklaration von "std::begin"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(32,44): error C2672: "end": keine übereinstimmende überladene Funktion gefunden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C2893: Fehler beim Spezialisieren der Funktionsvorlage "unknown-type std::end(_Container &)".
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1921): message : Siehe Deklaration von "std::end"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : Mit den folgenden Vorlagenargumenten:
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : "_Container=int"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C2784: "const _Elem *std::end(std::initializer_list<_Elem>) noexcept": Vorlage-Argument für "std::initializer_list<_Elem>" konnte nicht von "int" hergeleitet werden.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\initializer_list(63): message : Siehe Deklaration von "std::end"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C3536: "<begin>$L0": Kann nicht verwendet werden, bevor es initialisiert wurde.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): error C3536: "<end>$L0": Kann nicht verwendet werden, bevor es initialisiert wurde.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(32,50): error C2100: Ungültige Dereferenzierung.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(32,50): error C2440: "Initialisierung": "int" kann nicht in "const std::string &" konvertiert werden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : Ursache: Konvertierung von "int" in "const std::string" nicht möglich
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(33,9): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(125,32): error C2109: Index erfordert ein Array oder einen Zeigertyp
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(125,49): error C2109: Index erfordert ein Array oder einen Zeigertyp
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(125,66): error C2109: Index erfordert ein Array oder einen Zeigertyp
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(128,33): error C2109: Index erfordert ein Array oder einen Zeigertyp
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(172,47): error C2672: "begin": keine übereinstimmende überladene Funktion gefunden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C2893: Fehler beim Spezialisieren der Funktionsvorlage "unknown-type std::begin(_Container &)".
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1911): message : Siehe Deklaration von "std::begin"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : Mit den folgenden Vorlagenargumenten:
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : "_Container=int"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C2784: "const _Elem *std::begin(std::initializer_list<_Elem>) noexcept": Vorlage-Argument für "std::initializer_list<_Elem>" konnte nicht von "int" hergeleitet werden.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\initializer_list(57): message : Siehe Deklaration von "std::begin"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(172,47): error C2672: "end": keine übereinstimmende überladene Funktion gefunden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C2893: Fehler beim Spezialisieren der Funktionsvorlage "unknown-type std::end(_Container &)".
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(1921): message : Siehe Deklaration von "std::end"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : Mit den folgenden Vorlagenargumenten:
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : "_Container=int"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C2784: "const _Elem *std::end(std::initializer_list<_Elem>) noexcept": Vorlage-Argument für "std::initializer_list<_Elem>" konnte nicht von "int" hergeleitet werden.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\initializer_list(63): message : Siehe Deklaration von "std::end"
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C3536: "<begin>$L0": Kann nicht verwendet werden, bevor es initialisiert wurde.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): error C3536: "<end>$L0": Kann nicht verwendet werden, bevor es initialisiert wurde.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(172,50): error C2100: Ungültige Dereferenzierung.
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(172,50): error C2440: "Initialisierung": "int" kann nicht in "const WorldPackets::Guild::GuildPermissionsQueryResults::GuildRankTabPermissions &" konvertiert werden
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : Ursache: Konvertierung von "int" in "const WorldPackets::Guild::GuildPermissionsQueryResults::GuildRankTabPermissions" nicht möglich
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.cpp(173,5): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(44,65): error C2079: "WorldPackets::Guild::GuildInfo::Ranks" verwendet undefiniertes class "std::array<std::string,10>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Handlers\GuildHandler.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(209,52): error C2079: "WorldPackets::Guild::GuildEvent::Params" verwendet undefiniertes class "std::array<const char *,3>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Handlers\GuildHandler.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(265,73): error C2079: "WorldPackets::Guild::GuildPermissionsQueryResults::Tab" verwendet undefiniertes class "std::array<WorldPackets::Guild::GuildPermissionsQueryResults::GuildRankTabPermissions,6>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Handlers\GuildHandler.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(44,65): error C2079: "WorldPackets::Guild::GuildInfo::Ranks" verwendet undefiniertes class "std::array<std::string,10>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Protocol\Opcodes.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(209,52): error C2079: "WorldPackets::Guild::GuildEvent::Params" verwendet undefiniertes class "std::array<const char *,3>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Protocol\Opcodes.cpp)
3>D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Packets\GuildPackets.h(265,73): error C2079: "WorldPackets::Guild::GuildPermissionsQueryResults::Tab" verwendet undefiniertes class "std::array<WorldPackets::Guild::GuildPermissionsQueryResults::GuildRankTabPermissions,6>" (Quelldatei wird kompiliert D:\TrinityCore335_SRC\TrinityCore\src\server\game\Server\Protocol\Opcodes.cpp)
3>Die Erstellung des Projekts "game.vcxproj" ist abgeschlossen -- FEHLER.
4>------ Erstellen gestartet: Projekt: worldserver, Konfiguration: Release x64 ------
4>LINK : fatal error LNK1181: Eingabedatei "..\game\Release\game.lib" kann nicht geöffnet werden.
4>Die Erstellung des Projekts "worldserver.vcxproj" ist abgeschlossen -- FEHLER.
5>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: Release x64 ------
5>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
========== Erstellen: 1 erfolgreich, 2 fehlerhaft, 15 aktuell, 2 übersprungen ==========

**Comment by Aokromes** [comment]
re-run cmake.

**Comment by Tauriella** [comment]
damn!
You are my Hero :+1:
Thank you
