### ISSUE TITLE
Proposed tasks

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24446]
Current behaviour:
When you take a quest that requires you to escort the NPC to some place, then you will succeed.
However, if you offer this quest to your teammate, then this task will not be counted **(from the player who was offered the task)**. It is to escort the NPC to the place.

Expected behaviour:
Should count the quest to all players who have it

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. b26302c

**Comment by illfated** [comment]
OK, so just to rephrase, in case anyone wants a shortened version:
- Shared escort quests do not complete for other players than the one who shared it.

Could you list those quests you have tested, where this issue happens?
Did you make sure that none of the players were GM or in a raid group when testing this?

**Comment by jjo72ddd** [comment]
so for sure, all the players were not um and were not in the raid

https://classic.wowhead.com/quest=1222/stinkys-escape
https://classic.wowhead.com/quest=142/the-defias-brotherhood
https://www.wowhead.com/quest=25476/rescue-oox-22-fe

**Comment by illfated** [comment]
OK, thanks for those links and quest names.
One detail, I think https://www.wowhead.com/quest=25476/rescue-oox-22-fe is the master branch version (post-Cataclysm version) whereas the pre-Cataclysm version (classic) is this one:
https://classic.wowhead.com/quest=2767/rescue-oox-22-fe

If that quest ID is incorrect in your setup, it could at least explain why that individual quest does not work in the 3.3.5 branch.

**Comment by jjo72ddd** [comment]
I guess I was wrong with quest=25476  (because I wrote down the names of quests)

**Comment by illfated** [comment]
OK, fair enough. Have you tried testing if this can be replicated via GM commands, as in
```
.quest add 1222
(+ share the quest with party members)
.quest complete 1222
(+ check if they got completed as well)
```

**Comment by jjo72ddd** [comment]
This is strange, but I can not offer this quest. The offer button is locked. Both characters are level 35.

**Comment by Jinnaix** [comment]
This is not strange, quest 1222 or escort quests in general cant be shared after accepting them.
The mechanic behind is that players get a popup if one member of the group wants to start a escort quests IF they are able to start the quest too (without them already accepted that quest)
On top of that, .quest complete would never complete a quest for more than the selected player.

**Comment by Jinnaix** [comment]
Im not gonna check all the quests at this unholy time of the day and it would be better to get @Killyana into this, but lets look deeper into quest 1222. 
I remember that i have done the quest on a playtrough with 2 friends and we had the same problem, the quest did only complete for one of us.

Lets look at the SAI of the quests NPC "Stinky" : https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=4880#sai-main

What we see here right at the beginning is :

 `# | Event | Action
-- | -- | --
0 | Giving  Stinky's EscapeWhile Charmed | Store Invoker as target in # 1.

Invoker in this Script is TargetType 7 -> Action_invoker. Thats the player starting the quest.
This player gets stored and at event 19, gets the quest completion.

Without testing it, setting the TargetType to 16 would solve the issue of only the initial quest starter getting the completion at the end of the quest.

**Comment by Killyana** [comment]
3 Years later https://github.com/TrinityCore/TrinityCore/issues/18901
