### ISSUE TITLE
win10 can't use mariadb Generate TrinityCore Project

### ISSUE THREAD

**Issue by cjl3230** [TrinityCore/TrinityCore#24448]
Description:

I install mariadb-10.4.12-winx64.msi in win10.
cmake error.

Current behaviour:

I use vs2019,mariadb-10.4.12,when i use cmake to config, it says:
CMake Error at cmake/macros/FindMySQL.cmake:237 (message):
  Could not find the MySQL libraries! Please install the development
  libraries and headers
Call Stack (most recent call first):
  CMakeLists.txt:70 (find_package)

Expected behaviour:

Successful generate TrinityCore Project.

Steps to reproduce the problem:

Branch(es):

3.3.5

TC rev. hash/commit:

daecf90ac454a44d28c9f9f3a328a29d32558080

Operating system: 
win10 1909

**Comment by Aokromes** [comment]
can you try mariadb 10.3?

**Comment by cjl3230** [comment]
OK, I try mariadb 10.3 now

**Comment by cjl3230** [comment]
The problem still exists. I use mariadb-10.3.22-winx64.msi

**Comment by jackpoz** [comment]
Install MySQL 8 then

**Comment by cjl3230** [comment]
I install mysql 5.7.29, it's work ok now! But why can't use mariadb-10.4.12?

**Comment by jackpoz** [comment]
Support to MariaDB 10.4 on Windows platform has been added by https://github.com/TrinityCore/TrinityCore/commit/7c91c423d05aabc18d5c36af9ecc2a9c5f49970d .
