### ISSUE TITLE
MySql Connection Issue

### ISSUE THREAD

**Issue by DezignNuts** [TrinityCore/TrinityCore#24454]
[Server.log](https://github.com/TrinityCore/TrinityCore/files/4472948/Server.log)
[DBErrors.log](https://github.com/TrinityCore/TrinityCore/files/4472949/DBErrors.log)

**Description:**

Cannot start worldserver because of DB issue

**Current behaviour:**

Worldserver does not start due to DB error. First time loading worldserver, fresh compile.
LOG:

Could not connect to MySQL database at 127.0.0.1: Authentication plugin 'sha256_password' cannot be loaded: The specified module could not be found.

Could not connect to MySQL database at 127.0.0.1: Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.

Could not connect to MySQL database at 127.0.0.1: Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.

**Expected behaviour:**

The worldserver should start

**Steps to reproduce the problem:**

1. added the trinity user based on what is found in the worldserver.conf
2. started worldserver.exe
3. worldserver.exe crashes with above error.

**Branch(es):**

master

**Operating system:** Windows 32

**Comment by DezignNuts** [comment]
LoginDatabaseInfo     = "127.0.0.1;3306;root;admin;auth"
WorldDatabaseInfo     = "127.0.0.1;3306;root;admin;world"
CharacterDatabaseInfo = "127.0.0.1;3306;root;admin;characters"
HotfixDatabaseInfo    = "127.0.0.1;3306;root;admin;hotfixes"

All worldserver.conf information should be correct?

**Comment by Aokromes** [comment]
this looks to be mysql issue and not trinitycore.
