### ISSUE TITLE
People sometimes gets stuck after wiping on malygos

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24458]
**Description:**

People sometimes gets stuck after wiping on malygos

**Expected behaviour:**

People can move allways after wiping on malygos

**Steps to reproduce the problem:**

1. create one 10 man raid to malygos 
2. start fighting it
3. wipe on any stage
4. release ghost
5. sometimes you get stuck unable to move till you relog

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

400e2913179e (i got reports for long time)

**Operating system:** debian 10 x64

**Comment by ImmortalusDev** [comment]
This bug is +- 9 years old.

**Comment by jjo72ddd** [comment]
by the way, about getting stuck: it happens that if you turn on the auto track (num lock) and die, then in the spirit you will not be able to move. I can’t repeat it, but sometimes it happens

**Comment by Aokromes** [comment]
still bugged on 05fa1a46b36f

**Comment by Faq** [comment]
How offten it happens?

**Comment by jackpoz** [comment]
my notes from 2014 (yes 2014!)
>Can't move anymore in EoE .tele thenex :
unit->SetControlled(true, UNIT_STATE_ROOT) in OnUnitDied() C:\wow\TrinityCore\src\server\scripts\Northrend\Nexus\EyeOfEternity\instance_eye_of_eternity.cpp Ln 165

**Comment by jackpoz** [comment]
I got a strange combat log with https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=6277 spell after I died. If I .cast 6277 , I cannot move anymore.

It might be nice to get a log of ".list auras" after getting stuck
