### ISSUE TITLE
DB/Quest: First Things First: We're Gonna Need Some Beer 

### ISSUE THREAD

**Issue by mclaren99uk** [TrinityCore/TrinityCore#24450]
Hi, my first report so, please be kind.  New to all this and through I would report some issues as I play through.

DB/Quest: First Things First: We're Gonna Need Some Beer 
Quest ID 24474

Description:
Find and Retrieve Items.

Current behaviour:
Some items can not be collected but have aura/sparkles around them.
Stormhammer Stout - Item ID: 49744
Gnomenbrau - Item ID: 49746

TDB version:
820.19071

**Comment by Killyana** [comment]
Personal loot is not implemented, the gob 201610 has data30: chestPersonalLoot=27742
There's an entry=27742 in `gameobject_loot_template` but it will not work.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20066

**Comment by illfated** [comment]
Thank you for the report. The decision is to point this type of issue to the general issue linked in Aokromes' comment.

For future tickets, please utilize more of the issue ticket template if possible (and check for open issues).
