### ISSUE TITLE
[Noblegarden Bug] Falconwing Square: Blightly Coloured Eggs not Respawning after Looting

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24451]
**Description:**

The Brightly Coloured Eggs are not respawning in Falconwing Square after being looted, a server restart respawns them but the issue still continues.

**Current behaviour:**

Brightly Coloured Eggs not respawning after being looted by players.

**Expected behaviour:**

They should respawn like they do in the other zones such as Goldshire, Brill, etc.

**Steps to reproduce the problem:**

1. Go to Falconwing Square on a Horde character
2. Loot Brightly Coloured Eggs
3. Discover that they are not respawning after being looted

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4f33fd3932d3 2020-04-11 14:07:57 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by LordWaycrest** [comment]
Reported via in-game ticket by multiple players: Confirmed by us

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21331

**Comment by LordWaycrest** [comment]
> Dup #21331

Oh right, I did try searching for any possible open tickets
