### ISSUE TITLE
[3.3.5] Mage - Winter's Chill

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24461]
**Current behaviour:**

Winter's Chill (frost mage talent) procs even if the damage is completely absorbed.

**Expected behaviour:**

It should proc only when the frost spells deals damage.

**Steps to reproduce the problem:**

1. Place an absorption effect on the target.
2. Hit it with a frost spell.
3. Note that it will proc through the absorb.

This was fixed here: #20113
for some reason, now doesn't work
I try setting SpellPhaseMask to 0 and it works fine, but probably not is the correct way.
```sql
UPDATE `spell_proc` SET `SpellPhaseMask`=0 WHERE `SpellId`=-11180;
```
I don't know when broke this and why.

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  d57b42f2c89d4c40be20bc5d3b309b3a31d31e41

**Comment by Ovahlord** [comment]
Source? From what I read in the tooltip it says your Frost Damage Spells, not Frost Damage.There is a hitmask for absorb that probably needs to be excluded to have a effect

**Comment by Jildor** [comment]
see the another issue when fix is applied: #20113

**Comment by Jildor** [comment]
related with: #24462

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/247151b470e6b4950c8d63094c1b8fbf797ad246
