### ISSUE TITLE
Quest: Dragonmaw Race: Wing Commander Mulverick

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24468]
**Сurrent behavior:**
The race should begin

**Proper behavior:**

[Wing Commander Mulverick](https://www.wowhead.com/npc=23346/wing-commander-mulverick) doesn't want to start the race

https://www.wowhead.com/quest=11070/dragonmaw-race-wing-commander-mulverick

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. b26302c

**Comment by dr-j** [comment]
See https://github.com/TrinityCore/TrinityCore/issues/3789 even though different quest related and none of these are currently working on tc
