### ISSUE TITLE
[3.3.5] Priest - Inner Fire

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24462]
**Description:**
Same issue as: #22074
https://wowwiki.fandom.com/wiki/Inner_Fire
>Patch 1.10.2 (02-May-2006): Rank 3 will no longer have charges consumed when Power Word: Shield is active.

https://youtu.be/DMXM4D8vHgg?t=34

Part of the issue can be fixed with: #24460 (melee auto-hits)
For some reason, when you attack with a melee spell that requires melee weapon like warrior - Heroic Strike, drop charges when full absorb the hit.
I try with:
```sql
UPDATE `spell_proc` SET `HitMask`=0x3 WHERE `SpellId`=-588;
```
But seems doesn't works, seems critical hit with spell that requires melee weapon works fine, but normal hit with spell that requires melee weapon drop charges with full absorb

**Current behaviour:**

Priest spell - [Inner fire] lose stacks even though shielded by [power word: shield]

**Expected behaviour:**

Stacks should only be removed if hero actually take damage

**Steps to reproduce the problem:**

1. Get a priest and cast Inner Fire and PW: Shield
2. Attack the priest with melee attacks or spells that require melee weapon

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  d57b42f2c89d4c40be20bc5d3b309b3a31d31e41

**Comment by joshwhedon** [comment]
It is similar to what I posted last time around melee full absorbs. It is the same probleme but in the spell area. 
A lot of changes occured in void Spell::TargetInfo::DoDamageAndTriggers(Spell* spell)
As a result of thoses changes, https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2472
here, we update the damage on the spell. As a result of this, in the case of full absorb
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2489
this check returns true, and results in the spell being treated like a passive / no damage spell, and the hit mask is being overriden.

**Comment by Jildor** [comment]
Oh I see, seems this commit: https://github.com/TrinityCore/TrinityCore/commit/080d2c6cd439acb2059adc4e24a279de98aa0db6#diff-952c711803610aa78110e4f92ff2516a

before this commit, the check do else if and else:
https://github.com/TrinityCore/TrinityCore/blob/e8d5aa56cc48572d81e1898b7b4ff10cfa6d1957/src/server/game/Spells/Spell.cpp#L2428-L2492

after can enter in two checks.

@joshwhedon do you have a suggestion or fix?
What can be the best here?, maybe check this better:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Spell.cpp#L2489
adding a check for exclude if is full absorb or full resist?
or maybe restore old checks (else if and else)?

**Comment by joshwhedon** [comment]
My suggestion , 2 booleans, hasDamage and hasHeal, initialised to false. If we get into the damage branch, we set hasDamage to true, if we get into the heal branch, we set hasHeal to true, and we only execute the last branch if hasHeal = false and hasDamage = false. That will allow us to modify the damage without affecting any of the proc handling.

**Comment by Jildor** [comment]
thx, I will try it ;)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/247151b470e6b4950c8d63094c1b8fbf797ad246
