### ISSUE TITLE
Spell damage, and spell consuption error

### ISSUE THREAD

**Issue by dio85** [TrinityCore/TrinityCore#24471]
**Description:**

If you use closecombat spell(i mean sninister strike, and or warrior spells or any)
https://www.wowhead.com/spell=1752/sinister-strike
,the base damage+spell damage just half of the true. but if just use basic attack, the calculation is good.
and if you use mana spell, the cunsuption if nearly good, but the regen,  too fast for the spell consuption. I mean 1 blizzard use just 1k mana, this instantly regenerated. But if you use any power type spell, the spell not see you have enough power or not, so you can spam if you wait the cd. yes the cd is work. and if you use any power(not mana) spell, nothing consuption on yur power. (rage,focus etc.).

I tryed to debug on spell.cpp on Spell::TakePower with this:

`if (m_caster->IsPlayer())
            TC_LOG_ERROR("misc", "spell %u pwrtype %u mana %d", GetSpellInfo()->Id, uint32(powerType), cost.Amount);`
but nothing show anything. so maybe the power cunsuption wont start.
**Current behaviour:**

nothing crash, just core miss.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Use any closecombat character spell, sinister or warrior or etc.  
2. Watch the combat log with, and without spell, you can see the mistakes.
3. Try it with caster class. Mage or any. spell not ranked and the mana regen fast maybe.

**Branch(es):**

master

**TC rev. hash/commit:** 

-

**Operating system:** Win10,all

**Comment by Faq** [comment]
```
if (m_caster->IsPlayer())
TC_LOG_ERROR("misc", "spell %u pwrtype %u mana %d", GetSpellInfo()->Id, uint32(powerType), cost.Amount);
```

**Comment by bozoweed** [comment]
#24315

**Comment by dio85** [comment]
> #24315

Yeah, but i tell one full report...

**Comment by dio85** [comment]
Solved.
