### ISSUE TITLE
kinetic bomb sometimes spawns outside room

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24473]
**Description:**

kinetic bomb sometimes spawns outside room

**Current behaviour:**

kinetic bomb sometimes spawns outside room making it unable to attack them

**Expected behaviour:**

kinetic bombs must spawn allways inside room

**Steps to reproduce the problem:**

1. enter icc
2. go to princes
3. start fight
4. notice sometimes kinetic bombs spawns outside room

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

cfd63c350f5b

**Operating system:** debian 10 x64

**Comment by Faq** [comment]
You sure this doesn't happen also on retail?

**Comment by Rushor** [comment]
related to the huge random spawndistance of the spawneffect spell

with https://gist.github.com/Rushor/62727287edca2970762873991b8f3843 it looks way more smooth

**Comment by Killyana** [comment]
Looks like https://github.com/TrinityCore/TrinityCore/issues/24566

**Comment by Rushor** [comment]
seem to spawn always inside the room for me now with the PR (tested)

**Comment by Killyana** [comment]
Fixed with https://github.com/TrinityCore/TrinityCore/commit/c0b75bf40da8b447a2f3533dabbfad9eba7c6ea1
