### ISSUE TITLE
Professions not work correcly

### ISSUE THREAD

**Issue by arcaniafr** [TrinityCore/TrinityCore#24477]
Hi,
The professions not save the data in DB...

I've modified the database spells for update new data in trainer_spells.
The trainer send now the good primary spell and outland,cataclysm ect spells.

In the game, the profession up normaly.

After disconnect/connect, all is set to 0.
I attach the screenshot for this.

Last core 8.3, last db windows 10

Before disconnect 👍 
<img width="787" alt="1 couture" src="https://user-images.githubusercontent.com/56791020/79699376-8e722180-828f-11ea-936b-8637a9da5c81.PNG">

After connect
<img width="708" alt="2 couture" src="https://user-images.githubusercontent.com/56791020/79699382-95992f80-828f-11ea-9e7f-daabcc1c9eaf.PNG">

**Comment by Ovahlord** [comment]
Stop using a outdated version. This issue has been fixed by myself a while ago already so you are either not using a official TC version or you are just utterly outdated.

**Comment by jackpoz** [comment]
> Last core 8.3, last db windows 10

The template asks for a commit hash, it should be provided when opening an issue
