### ISSUE TITLE
Core/GameObject: Interraction with Gameobjects that require quest but doesn't have quest item as loot

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24474]
**Сurrent behavior:**
It is impossible to open Rotten Arakkoa Egg and also (if you use .gm on) an item Rotten Arakkoa Egg is missing

**Proper behavior:**
when opening an egg with a probability of casting 36810 spell. There should also be a probability of a quest item to complete the quest.

https://www.wowhead.com/quest=10547/of-thistleheads-and-eggs
https://www.wowhead.com/item=30500/rotten-arakkoa-egg
https://www.wowhead.com/object=184795/rotten-arakkoa-egg

[issues 15926](https://github.com/TrinityCore/TrinityCore/issues/15926)

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. b26302c

**Comment by dr-j** [comment]
If I remember it’s specific egg which completes quest rest are bad

**Comment by dr-j** [comment]
Cannot reproduce

For rotten arokkoa egg that contains the quest item type .go object 25623 (you will also notice that the tooltip on this one is different to the rest of the rotten eggs as its different object but this one has tooltip which says it contains quest item all of the others just say rotten arokkoa egg

All of the other eggs are empty containers which only cast rotting putrisence when you try and loot them.

Gameobject 184796 = Bad egg there are 8 of these spawned
Gameobject 184795 = Good egg there are 1 of these spawned

**Comment by Rushor** [comment]
i guess all those objects must be pooled

**Comment by Killyana** [comment]
We need a proof there's more than one spot for the good egg.

**Comment by Killyana** [comment]
The issue is with flag=4 GO_FLAG_INTERACT_COND it will not allow interaction with the gob unless is contains a quest item.

It must allow interaction if the gob contain a quest item or/and if data8: questID

**Comment by Killyana** [comment]
An other similar issue:
The game object https://woehead.way-of-elendil.fr/?object=190696 must only be clickable if the player has the quest 12580, it doesn't contain any quest item.
But if you .add quest 12580 and .cast 52156 to summon the gob you will not be able to interact with the gob. It has the correct flag=4 according to sniffs
