### ISSUE TITLE
 [3.3.5a] AI() returns nullptr when the Creature is charmed

### ISSUE THREAD

**Issue by peycho** [TrinityCore/TrinityCore#24488]
**Description:**

Server crash.

**Current behaviour:**

Crash traceback log: https://gist.github.com/peycho/6d193afedca18e71b3c8de28514ced21

**Steps to reproduce the problem:**
I'm not aware how to reproduce it. It happens sometimes. If I'm understanding what I see in the log it's something with Blackwing lair instance.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/400e2913179e0ff47518558f89b687161031967a

**Operating system:** Linux OS, Ubuntu 16 LTS.

**Comment by jackpoz** [comment]
I wonder if somehow that razor npc is missing the AI.

It seems to happen when https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=12459 is spawned (EVENT_RAZOR_SPAWN event)

**Comment by Killyana** [comment]
The npc Blackwing Warlock has SmartAI, nothing abnormal.

**Comment by jackpoz** [comment]
do you know what AI Razor has ?

**Comment by Killyana** [comment]
He use bossAI https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp#L72

But also he get charmed by a player during phase one to destroy the egg.
So it could be related to charm start/end

**Comment by Faq** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=12435

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/7b8b02c32ebfb7c8c47ac1d1b94129c91346ad66 might fix the crash (unless the same issue happens in another location in the same world update).

We might change the way AIs are swapped when charming is applied/expires, maybe with a temporary AI that logs in TC_LOG_DEBUG every hook call (as it will not handle anything).

Not sure what happens if Razorgore AI doesn't get notified about the spawned npcs, maybe a minor hiccup in the script.

**Comment by Ovahlord** [comment]
If he does not get notifed about the spawns then the npcs that he is suposed to store to despawn them on reset will stay arround forever. so better store these summons in a guidvector in the instance script instead and despawn them based on the boss state

**Comment by peycho** [comment]
I can no longer reproduce this crash issue. Thanks guys.

**Comment by jackpoz** [comment]
> We might change the way AIs are swapped when charming is applied/expires, maybe with a temporary AI that logs in TC_LOG_DEBUG every hook call (as it will not handle anything).

This still applies, the way charmed AI gets swapped is quite unsafe and can lead to not so obvious crashes

**Comment by offl** [comment]
#27434
