### ISSUE TITLE
[Crash] EffectPullTowardsDest

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#24482]
**Description:**

SpellEffectPullTowardDest can occasionaly cause a crash.

**Current behaviour:**

SpellEffectPullTowardDest can occasionaly cause a crash.
https://gist.github.com/joshwhedon/25a5eb16040f668aad11bfd99fdb11bc

**Expected behaviour:**

It should not crash I guess.

**Steps to reproduce the problem:**

Was not able to reproduce the problem, but able to say what causes it.
Grand Magus Telestra, in the nexus, casts spell 47756, Gravity Well. This spell has EffectPullTowardsDest, which, as its name indicates it, pulls the target toward the dest.

It looks like it is due to the spell occasionally picking an invalid destination position, which ends up being out of any grid, resulting in the assert kicking in.

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L4406

This crash has happened 5 times in a 2 weeks or so.

**Branch(es):**

3.3.5 (at least)

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8ac83744293afe297bce2597107bc5da5445ccbb

**Operating system:** Linux but probably doesn't matter

**Comment by jackpoz** [comment]
That assert should be changed as the code itself picks a random position, it should clamp,  not assert.

**Comment by Shauren** [comment]
The assert being hit is correct and must not be changed but we need to ensure `distXY` is not 0 in spell effect handler

**Comment by jackpoz** [comment]
caused by https://github.com/TrinityCore/TrinityCore/pull/24251

**Comment by ForesterDev** [comment]
I've got the same crash on my server. Maybe my dump can help to find the problem

https://gist.github.com/ForesterDev/8a5fe9da5ea01ff5683cc0debf479184

**Comment by Killyana** [comment]
We didn't fix it here https://github.com/TrinityCore/TrinityCore/commit/61aec37b4ffd5fbd0bdde4de1cf7313d578651a7 ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/740afc71358c32257540350a6d7d4071a851452f
