### ISSUE TITLE
Crash in WorldObject::CanSeeOrDetect

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#24485]
**Description:**

Crashlog: https://gist.github.com/gtestdev/88a905a953fdb1a483d54e4a2ed829f5

here: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.cpp#L1537-L1538

I don't know what can be the cause
 
**Steps to reproduce the problem:**

I don't know

**Branch(es):** 3.3.5

**TC rev. hash/commit:** d03aaece7daa88ce664258c73f95218c4c37e069

**Operating system:** Debian 10

**Comment by jackpoz** [comment]
do you have any custom change ?

**Comment by gtestdev** [comment]
transmogrify

**Comment by Aokromes** [comment]
no feedback after more than 3 years, closing.
