### ISSUE TITLE
Crash in Creature::GetPetAutoSpellOnPos

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#24483]
**Description:**

Crashlog: https://gist.github.com/gtestdev/2a4ab1d4fef4e2799f110142c6121e8a

I don't know if this can help:
```diff
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 4a4b2ea350..c3d3eb260e 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -2848,7 +2848,7 @@ std::string const & Creature::GetNameForLocaleIdx(LocaleConstant loc_idx) const
 
 uint32 Creature::GetPetAutoSpellOnPos(uint8 pos) const
 {
-    if (pos >= MAX_SPELL_CHARM || m_charmInfo->GetCharmSpell(pos)->GetType() != ACT_ENABLED)
+    if (pos >= MAX_SPELL_CHARM || !m_charmInfo->GetCharmSpell(pos) || m_charmInfo->GetCharmSpell(pos)->GetType() != ACT_ENABLED)
         return 0;
     else
         return m_charmInfo->GetCharmSpell(pos)->GetAction();
```

**Steps to reproduce the problem:**

I don't know

**Branch(es):** 3.3.5

**TC rev. hash/commit:** d03aaece7daa88ce664258c73f95218c4c37e069

**Operating system:** Debian 10

**Comment by Shauren** [comment]
That fix attempt doesn't do anything, `GetCharmSpell` can never return nullptr

**Comment by jackpoz** [comment]
did you get any error in TC_LOG_ERROR before this crash ?

**Comment by gtestdev** [comment]
No, I have reviewed dberrors and server logs and I don't see anything

**Comment by gtestdev** [comment]
I added a log to see if m_charminfo null result and I obtained:
```
Creature::GetPetAutoSpellOnPos NPC: GUID Full: 0xf1300087ff000148 Type: Creature Entry: 34815  Low: 328 null result in m_charmInfo
```

is a npc summoned in Trial of the Crusader, boss Lord Jaraxxus:
https://www.wowhead.com/npc=34815

But I can't figure it how to reproduce the crash with that NPC

**Comment by jackpoz** [comment]
> No creature ever should have `PetAI` without `m_charmInfo`

unless the charm is being stopped, then m_charmInfo is null until PetAI is removed

**Comment by jackpoz** [comment]
@gtestdev just null check m_charmInfo (I'll add that later on)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b4adaa838c2e44f4008152cc955410d25ff4d8b0
