### ISSUE TITLE
Possible to move while casting 

### ISSUE THREAD

**Issue by HelloKitty** [TrinityCore/TrinityCore#24490]
**Description:**

It's possible to cast a spell and then move as a player with an unmodified client. This can be abused without external tools but can be significantly more effective with the right tools.

**Current behaviour:**

Currently, in Spell::Update a check for canceling a spell's cast is done by checking the current (aka LAST handled) MovementInfo from the last movement packet. It is possible with this logic for a client to turn its mouse to send various non-movement MSG_MOVE_* packets after moving such that the next Player::Update and Spell::Update will appear as though the player isn't moving yet did move since the last update. This is reproducible by hand within the client.

**Expected behaviour:**

Spell::Update should interrupt spells if a player has moved since the last update and not only if the current Player's MovementInfo appears to be moving.

**Steps to reproduce the problem:**

1. Start casting a spell
2. Move while casting, strafing works well.
3. Then immediately turn the rotation of the player to send a movement packet that appears not to be moving.

**Branch(es):**

3.3.5 and maybe master

**TC rev. hash/commit:** 

c2dd8d02388cc1e297b648099ab824c988a3ba03

**Operating system:** Windows

**Comment by HelloKitty** [comment]
Having trouble replicating this on TC head. Was working on TC fork from 2 months ago. Will investigate again when I have more time.

**Comment by Killyana** [comment]
I will close this issue as impossible to reproduce
