### ISSUE TITLE
Problem with .pdump load

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#24517]
**Description:**

When loading a character with .pdump load it does not update the realmcharacters table with the new total of characters that account has for that specific realm.

**Current behaviour:**

When loading a character with .pdump load it does not update the realmcharacters table with the new total of characters that account has for that specific realm.

**Expected behaviour:**

When loading in a character with .pdump load it should update the realmcharacters with the accounts new total characters for that specific realm.

**Steps to reproduce the problem:**

1. Import a character with .pdump load
2. Log into the realm with the newly imported character
3. Look at the Characters column and then check the characters list of that realm. You should notice it does not update the realmcharacters table and count the imported character towards the total characters you have for that realm.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 411033ddf819 2020-04-28 22:53:40 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by jackpoz** [comment]
is the count updated after a relog or is it never updated at all ?

**Comment by LordWaycrest** [comment]
> is the count updated after a relog or is it never updated at all ?

Never updated at all, I did checks before opening this
