### ISSUE TITLE
Quest_greetings_Locale don't work on Objects

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#24518]
Hello

**Current behaviour:**
The Object:

https://de.classic.wowhead.com/object=2076/blubbernder-kessel

INSERT INTO `quest_greeting` VALUES ('2076', '1', '0', '0', 'This cauldron churns with thick, green bubbles.  Skulls, bones and organs of unknown creatures swim within its viscous broth...$B$BAnd rising lazily to the surface are the skulls of two, once mighty trolls:$B$BGan\'zulah and Nezzliok.', '0');
DELETE FROM `quest_greeting_locale` WHERE `ID`='2076' AND `locale`='deDE';
INSERT INTO `quest_greeting_locale` VALUES ('2076', '0', 'deDE', 'test blubbernder-kessel', '0');

says not the german quest_greetings for this Object to me, the Npc´s works.

When we make the English quest_greeting thit this text it´s works but no english text is in this case.

![WoWScrnShot_042920_230644](https://user-images.githubusercontent.com/321832/80647287-84f66f80-8a6e-11ea-9e1a-a8a17991416a.jpg)

**Expected behaviour:**
Says 'test blubbernder-kessel' to me.

**Steps to reproduce the problem:**

1. Step 1 Server stop, execute the SQL and wdb cache clear from wow client,
2. Step 2 start server and client
3. Step 3 the same problem

**Branch(es):**
3.3.5, 

**TC rev. hash/commit:** 
8128bb97dbf4b5ba7cb0b624ce7cf7428d7bdc63

**Operating system:** Windows 7

**Comment by Shauren** [comment]
Not a bug, your sql is wrong. Why are you putting type=0 into quest_greeting_locale when you used type=1 in quest_greeting? Fix that.

**Comment by genion18** [comment]
Okay, thanks.
