### ISSUE TITLE
[3.3.5] [Core] .Send money Crashes worldserver daemon

### ISSUE THREAD

**Issue by Lorenc95** [TrinityCore/TrinityCore#24521]
**Description:**

Whenever ingame and utilizing the command .send money without arguments specified the worldserver daemon crashes.

**Current behaviour:**
As per described above, whenever the command is executed the worldserver daemon crashes

**Expected behaviour:**

Command should specify arguments if none where passed just like .send mail

**Steps to reproduce the problem:**
Whenever ingame and utilizing the command .send money without arguments specified the worldserver daemon crashes.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
f1e4ee21f8da

**Operating system:** Win64

**Comment by Shauren** [comment]
This is a crash report, where is the crash log?

**Comment by IllInuz** [comment]
Please allow me a moment, as i just found out that .send mail was doing the same thing, i will be adding the crashlog momentarily.
