### ISSUE TITLE
DB/Loot: Add missing bandages to Arathi Basin care packages

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24533]
```sql
-- Add missing bandages to Arathi Basin care packages
DELETE FROM `item_loot_template` WHERE `Item` IN (20065,20066,20067);
INSERT INTO `item_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`) VALUES
(20230,20065,0,100,0,1,0,20,20),
(20236,20065,0,100,0,1,0,20,20),
(20228,20066,0,100,0,1,0,20,20),
(20231,20066,0,100,0,1,0,20,20),
(20229,20067,0,100,0,1,0,20,20),
(20233,20067,0,100,0,1,0,20,20);
```
Source: Wiki, [for example: Arathor Standard Care Package](https://wow.gamepedia.com/Arathor_Standard_Care_Package)

**Branch:** 3.3.5
**TC rev. hash/commit:** 79edf74768e2
**Operating system:** Windows 8.1

**Comment by illfated** [comment]
Looks good to me (although, from a cosmetic perspective, the `comment` column could have been there (Not sure why it is kept around, if it is almost never used. )) .

**Comment by offl** [comment]
I don't see any reason to fill the `comment` column if  `Reference` =0.
It should be filled manually by user or by new config on startup for all records in *_loot_template (if you plan to work with them).

Yesterday I almost opened an issue-suggestion about that but now I think it could be not related to configs at all. There is no similar configs at all. Except the ones to fill `gameobject / creature.areaId / zoneId` but it is because you can't do it manually.
Also maybe it's just me, but yesterday I filled all comments in `creature_loot_template` (300k records) and after that every SELECT query took much more time. But today everything is fine.

> I don't see any reason to fill the `comment` column if  `Reference` =0.

So if the `Reference` column is not 0, you can't fill the `comment` manually for all records because usually it should contain specific data like "Nothrend, Green items level 73-77".

**Comment by illfated** [comment]
Thank you for your in-depth testing of that detail. Fair point. I agree, it is too cumbersome to fill all those comment fields, compared to how small the improvement is, as well as the possible performance impact.
