### ISSUE TITLE
Clang 10 and GCC 9.0.3 build errors

### ISSUE THREAD

**Issue by LordVishnuFromHell** [TrinityCore/TrinityCore#24555]
**Description:**
Hi guys, I love to play WoW and decided to install my local server, but faced with a compilation problem.
I use archlinux and I have the latest gcc and clang.
```
clang version 10.0.0 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
```
gcc (Arch Linux 9.3.0-1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
```
**Current behaviour:**
when i try build i see this errors: https://pastebin.com/AK1sLLD4
**Expected behaviour:**
i think core must build?
**Steps to reproduce the problem:**

1. try run make on gcc  9.3.0 and clang 10.0.0

**Branch(es):**
 3.3.5
**TC rev. hash/commit:**  
000e49b79306
**Operating system:**
ArchLinux last update

**Comment by Shauren** [comment]
Those are not errors, they are warnings. Don't build with -Werror

**Comment by LordVishnuFromHell** [comment]
@Shauren thanks! i think i get this from another wowemu project hmm
