### ISSUE TITLE
[Core] combat distance 

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#24568]
Description:
TargetPosRecalculateRange Removal
https://github.com/TrinityCore/TrinityCore/pull/21193/files
https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4#diff-9262d6313d41b1a2a367021a11ec5c34 
Failure in 3.3.5
https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/1.jpg
https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/2.jpg
https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/3.jpg
Creatures are now stacked together
Current behaviour:
https://github.com/TrinityCore/TrinityCore/pull/21193/files
The commit is now only available in the master branch
Expected behaviour:
Recurrence distance calculation and 3.3.5 branch

Steps to reproduce the problem:
Branch(es):
3.3.5
TC rev. hash/commit:
000e49b
Operating system: Win7

**Comment by Rushor** [comment]
can you show us a screenshot?

**Comment by w5860363** [comment]
@Rushor https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/1.jpg
https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/2.jpg
https://raw.githubusercontent.com/w5860363/TrinityCore/master/.circleci/3.jpg

**Comment by Rushor** [comment]
where was that fix added in master branch?

**Comment by w5860363** [comment]
@Rushor TargetPosRecalculateRange 
This is a few years ago, the mobile CPP was recently removed, but there are still in the master branch

https://github.com/TrinityCore/TrinityCore/commit/2a84562dc85516f432bb1e5de9add23c28b26ce4#diff-9262d6313d41b1a2a367021a11ec5c34
After submitting this function is invalidated

master branch https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L64

**Comment by Killyana** [comment]
We have already 2 issues:
https://github.com/TrinityCore/TrinityCore/issues/18512
https://github.com/TrinityCore/TrinityCore/issues/20922
