### ISSUE TITLE
Mirror images tries to attack targets they cannot attack

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24560]
**Description:**

Mirror images tries to attack targets they cannot attack

**Current behaviour:**

mage's mirror images are trying to attack targets they are unable to attack, for example the drake of the pit of saron final boss

**Expected behaviour:**

they don't try to attack something they cannot attack

**Steps to reproduce the problem:**

1. go pit of saron final boss
2. use mirror image
3. notice they walk around instead attack boss

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ecac9d79e359

**Operating system:** debian 10 x64.

**Comment by joshwhedon** [comment]
I am not 100% sure, but I think in the script, the calls to CanAIAttack (in UpdateVictim) might need to be updated to me->CanCreatureAttack(target). This method calls CanAIAttack but also checks target validity. I am going to try it and report if it causes problems.

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/commit/456aaf2cea40160ad8f8b2504a003a1991db741a
