### ISSUE TITLE
lumbering abomination in Halls of reflection

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24566]
Sometimes lumbering abomination spawn in such a place that it is impossible to kill
https://www.wowhead.com/npc=37069/lumbering-abomination
![WoWScrnShot_050120_213209](https://user-images.githubusercontent.com/24715026/81019892-5282b300-8e70-11ea-920a-2338daf3f02f.jpg)

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. b26302c

**Comment by Rushor** [comment]
reduce the spawndist

**Comment by Rushor** [comment]
// Summon Raging Ghoul
    ApplySpellFix({ 69817, 69835 }, [](SpellInfo* spellInfo)
    {
        spellInfo->Effects[EFFECT_0].RadiusEntry = sSpellRadiusStore.LookupEntry(EFFECT_RADIUS_15_YARDS); // 15 yards instead 30
    });

**Comment by jjo72ddd** [comment]
By the way, in my opinion this is due to the fact that sometimes Lich passes very close to the cliff, and sometimes very close to the mountain. Lich seems to have no path of his own and he follows Jaina

**Comment by Rushor** [comment]
why are the abominations not dropping below the ground in your server?

**Comment by jjo72ddd** [comment]
some fall and some not. I killed this abomination through the .die function. He is standing in the air. I think he is standing right on the edge of the texture, so he did not fall

**Comment by Killyana** [comment]
It will be fixed by Core/MMAPs: Adjust walkable climb probably

**Comment by Rushor** [comment]
well then close

**Comment by Killyana** [comment]
Not sure 100% will check once merged.

**Comment by Faq** [comment]
So possible ref #24539

**Comment by jackpoz** [comment]
anyone up to test this issue with PR #24539 ?

**Comment by jjo72ddd** [comment]
Note: when checking, try to die a couple of times, and start the Jaina again.
Perhaps these photos will be needed.
![изображение](https://user-images.githubusercontent.com/24715026/81118022-c5ebf980-8f30-11ea-9f9d-1f34c00e410f.png)

![изображение](https://user-images.githubusercontent.com/24715026/81117963-a9e85800-8f30-11ea-96ad-2689a47cb2e2.png)
![изображение](https://user-images.githubusercontent.com/24715026/81117991-b79ddd80-8f30-11ea-9390-2c97283e60a2.png)

**Comment by Rushor** [comment]
will check the pr now

**Comment by Rushor** [comment]
looking good, the always spawn on the ground not in the air 

https://i.imgur.com/3DScXEr.jpg

**Comment by Killyana** [comment]
Fixed with https://github.com/TrinityCore/TrinityCore/commit/c0b75bf40da8b447a2f3533dabbfad9eba7c6ea1
