### ISSUE TITLE
Blood furnace's Broggok sometimes fails to start event

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24565]
**Description:**

Sometimes Broggok fails to start event

**Expected behaviour:**

Broggok starts event allways.

**Steps to reproduce the problem:**

1. go blood furnace, Broggok
2. press lever
3. wait
4. press lever
5. repeat instance
6. press lever
7. works

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

000e49b79306

**Operating system:** Debian 10 x64

**Comment by Rushor** [comment]
It fails when player die during the orcs, then the orcs run back to the homeplace, the player instantly click again on lever > no more action.

i think lever should only work again once the orcs are at homeplace

**Comment by Rushor** [comment]
try 

```diff
diff --git a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
index a9f3447f63..9b795cc461 100644
--- a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
+++ b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
@@ -179,7 +179,7 @@ struct BroggokPrisionersAI : public ScriptedAI
 
     virtual void ScheduleEvents() = 0;
 
-    void EnterEvadeMode(EvadeReason why) override
+    void JustReachedHome() override
     {
         if (instance->GetBossState(DATA_BROGGOK) == IN_PROGRESS)
         {
@@ -187,7 +187,7 @@ struct BroggokPrisionersAI : public ScriptedAI
                 broggok->AI()->DoAction(ACTION_RESET_BROGGOK);
         }
 
-        ScriptedAI::EnterEvadeMode(why);
+        ScriptedAI::JustReachedHome();
     }
 
     void UpdateAI(uint32 diff) override
```

summoning @Keader

**Comment by Keader** [comment]
i dont see any problem changing it.
open a pr :)

**Comment by Keader** [comment]
00bc6e7d54e924dabaf4636a4b8084f0db067194
