### ISSUE TITLE
kologarn's arms damage incorrectly transfered to boss

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24577]
**Description:**

Theroically the same damage the arms takes it must be transfered to boss on arm die.

**Current behaviour:**

you need to kill 11 arms on 10 mode (  545 000 hp to kill  3 600 000 hp boss)
you need to kill 55 arms on 25 mode (2 300 000 hp to kill 15 340 000 hp boss)

https://mega.nz/file/Q75RDTzZ#VHPbi4ZTxPwbpmfRyD5VdJXIofdh97I_P3f2NWh0NC8 

**Expected behaviour:**

you kill 7 arms to kill boss on any mode.

**Steps to reproduce the problem:**

1. go ulduar kologarn
2. .dam 5000000 right arm
3. .dam 5000000 left arm
4. notice the amount of damage transfered is to low

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5bbab32793eb

**Operating system:** Debian 10 x64

**Comment by Killyana** [comment]
It's done by spells:
mode 10: https://woehead.way-of-elendil.fr/?spell=63629
mode 25: https://woehead.way-of-elendil.fr/?spell=63979

**Comment by Aokromes** [comment]
i think 25m spell is missing on script, but even with that, the 10m version damage is to low.

**Comment by Killyana** [comment]
In mode 10 it deals ‭331‬k damage instead of 543k, I cannot get the exact number because the spell is hidden from the logs
Maybe it's reduced by the boss armor

**Comment by ccrs** [comment]
should be a plain HP % modification IIRC

**Comment by Aokromes** [comment]
i think this must make more easy 25m mode:

```cpp
diff --git a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
index 3b5ff2b222..98c87ad559 100644
--- a/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
+++ b/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
@@ -37,6 +37,7 @@ EndScriptData */
 enum Spells
 {
     SPELL_ARM_DEAD_DAMAGE               = 63629,
+    SPELL_ARM_DEAD_DAMAGE_25            = 63979,
     SPELL_TWO_ARM_SMASH                 = 63356,
     SPELL_ONE_ARM_SMASH                 = 63573,
     SPELL_ARM_SWEEP                     = 63766,
@@ -189,7 +190,11 @@ class boss_kologarn : public CreatureScript

                 if (!apply)
                 {
-                    who->CastSpell(me, SPELL_ARM_DEAD_DAMAGE, true);
+                    if (Is25ManRaid())
+                        who->CastSpell(me, SPELL_ARM_DEAD_DAMAGE_25, true);
+                    else
+                        who->CastSpell(me, SPELL_ARM_DEAD_DAMAGE, true);
+                    break;

                     if (Creature* rubbleStalker = who->FindNearestCreature(NPC_RUBBLE_STALKER, 70.0f))
                     {
a

**Comment by Jildor** [comment]
maybe this can be enough:

```sql
-- Ulduar - Arm Dead Damage Kologarn difficult modes
DELETE FROM `spelldifficulty_dbc` WHERE `id` =63629;
INSERT INTO `spelldifficulty_dbc`(`id`,`spellid0`,`spellid1`) VALUES
(63629,63629,63979);

-- Ulduar - Arm Dead Damage Kologarn should ignore armor
DELETE FROM `spell_custom_attr` WHERE `entry` IN (63629,63979);
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES
(63629, 32768), -- 10
(63979, 32768); -- 25
```

**Comment by Aokromes** [comment]
> maybe this can be enough:
> 
> ```sql
> -- Ulduar - Arm Dead Damage Kologarn difficult modes
> DELETE FROM `spelldifficulty_dbc` WHERE `id` =63629;
> INSERT INTO `spelldifficulty_dbc`(`id`,`spellid0`,`spellid1`) VALUES
> (63629,63629,63979);
> 
> -- Ulduar - Arm Dead Damage Kologarn should ignore armor
> DELETE FROM `spell_custom_attr` WHERE `entry` IN (63629,63979);
> INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES
> (63629, 32768), -- 10
> (63979, 32768); -- 25
> ```

well, the way i have used is used on a razorscale.

**Comment by Jildor** [comment]
Spell seems should ignore armor, if you calculate kologarn hp / spell damage (mode 10 and 25) the result is 7 arms should die to kill boss in two modes, actually damage is affected by armor and should kill more arms

The spell difficulty mode is the same with your change in code and with sql change, so I don't know what is the standard, but, with those changes should be fixed xD

**Comment by ccrs** [comment]
the sql is the standard

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24577#issuecomment-625169067 looks correct to me.

**Comment by Jildor** [comment]
so can be pushed? xD
