### ISSUE TITLE
Banco de Dados

### ISSUE THREAD

**Issue by admdbreno** [TrinityCore/TrinityCore#24588]
Preciso da ajuda de alguem que entenda sobre o banco de dados, entre em contato comigo pelo meu e-mail exeassistec@gmail.com... se for o caso, combinamos um valor pela ajuda $$

**Comment by Keader** [comment]
Bom dia amigo, isso não é um fórum e apenas **inglês** é permitido aqui.
Este repositório tem como objetivo apenas report de bugs.
Por favor, não abrir reports como este novamente.

(Morning friend, it's not a forum and only english is allowed here.
This repository is for bugs only. Please dont open tickets like this again).
