### ISSUE TITLE
Icecrown Gunship Battle

### ISSUE THREAD

**Issue by jjo72ddd** [TrinityCore/TrinityCore#24580]
Icecrown Gunship Battle - if the raid dies during the battle, you cannot enter Icecrown Citadel. Will write that there is a battle. I waited about 20 minutes.

if I’m not mistaken, it should be like this: if all members of the raid have died, then the battle stops and the ships return to their original state.

Branch(es): 3.3.5
TDB: 335.20031
Ubuntu 18.04
Rev. b26302c

**Comment by Rushor** [comment]
try to set the gunship active

**Comment by ujared** [comment]
We're experiencing people dying instantly when landing on the opposing ship (skybreaker) during this gunship battle. As soon as players use their jump pack and land on the deck they take massive damage and die within one second. Interestingly, this happens for horde players who land on 'the hammer' (the zeppelin of the horde that flys in icecrown). This renders the battle impossible to beat as nobody can live long enough to kill the mage that will end the frozen phase :( sadness.

**Comment by Aokromes** [comment]
> We're experiencing people dying instantly when landing on the opposing ship (skybreaker) during this gunship battle. As soon as players use their jump pack and land on the deck they take massive damage and die within one second. Interestingly, this happens for horde players who land on 'the hammer' (the zeppelin of the horde that flys in icecrown). This renders the battle impossible to beat as nobody can live long enough to kill the mage that will end the frozen phase :( sadness.

that maybe it's because people using canons or vehicles before battle starts.

**Comment by Killyana** [comment]
players dies from fall damage https://github.com/TrinityCore/TrinityCore/issues/24225
And for the main issue I cannot reproduce it.

**Comment by TheWinchesters** [comment]
I think I have seen this happening but it does not always happen, like you cannot just reproduce it anytime you want:
As the author says, everyone dies and and then, nobody can enter ICC because there is an encounter in progress.
When I enter in a raid with that problem I can see both gunship together like the event is still going on. As soon as I am near both of them, the event finally resets.
@jjo72ddd Could you tell me if you have experienced the same?
