### ISSUE TITLE
SQL 2020_05_02_02_world.sql fails

### ISSUE THREAD

**Issue by liszt** [TrinityCore/TrinityCore#24581]
**Description:**
SQL 2020_05_02_02_world.sql fails

**Current behaviour:****
Start with new world database.
SQLs apply until:
 Applying update "2020_05_02_02_world.sql" '91A2617'...
ERROR 1072 (42000) at line 2: Key column 'race' doesn't exist in table

**Expected behaviour:**
All SQL apply correctly

**Steps to reproduce the problem:**
1. Drop World DB
2. Start worldserver

**Branch(es): master

**TC rev. hash/commit: d1572327d21f

**Operating system:  linux (Fedora 31)

**Comment by funjoker** [comment]
do you use MariaDB or MySQL ?

**Comment by funjoker** [comment]
#24561
