### ISSUE TITLE
[Spell] Faerie Fire cannot be reapplied on target if user has Improved Faerie Fire talent

### ISSUE THREAD

**Issue by joshwhedon** [TrinityCore/TrinityCore#24592]
**Description:**

Faerie Fire cannot be reapplied on target if user has Improved Faerie Fire talent

**Current behaviour:**

IF you apply Faerie Fire and try to reapply it, you are told a more powerful effect is already in place.

**Expected behaviour:**

Allow to refresh faerie fire. I am unsure we should forbid casting debuffs if a more powerful effect is present in the first place. It makes sense for buffs, but for debuffs it might negatively affect the clas gameplay if the spell is part of a rotation.

**Steps to reproduce the problem:**

1. Get a druid with Improved Faerie Fire talent (balance branch)
2. Try to cast Faerie Fire multiple times on the target

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/829cf38c67a70c1e0ec9886562e7ae7ae4fda17d

**Operating system:** Doesn't matter

**Comment by Jildor** [comment]
This issue still happens:
- Get two druids
- Druid A learn Improved Faerie Fire balance talents
- Druid A cast Faerie Fire on target
- Druid B try to cast Faerie Fire (Feral) without Improved Faerie Fire balance talents
- You get error a more powerful effect is already in place

we can see in this log how should it work:
http://www.worldoflogs.com/reports/c6ql9qrug06m8yy7/xe/?s=6368&e=6638&x=spell+%3D+%22Faerie+Fire%22+or+spell+%3D+%22Faerie+Fire+%28Feral%29%22

**Comment by leodium** [comment]
Hi ... Still no solution :p ?

.b
