### ISSUE TITLE
onyxia sometimes recovers hp on 3rd phase while on combat

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24594]
**Description:**

she is recovering hp when people is fighting it after reach 3rd phase.

**Expected behaviour:**

she never recovers hp while on combat

**Steps to reproduce the problem:**

1. .tele onyxia
2. fight onyxia
3. .dam her to reach 3rd phase
4. sometimes she will recover hp even she is on land.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0b60b482730f

**Operating system:** debian 10 x64

**Comment by Rushor** [comment]
is she resetting the whole fight aswell?

**Comment by Aokromes** [comment]
no, only on 3rd phase.

**Comment by Jildor** [comment]
I haven't had time to try, but I think happens a simmilar issue in halion in 3rd phase? (or maybe second phase I don't remember)

**Comment by jackpoz** [comment]
Imo there should be a config to disable hp regen if CanNotReachTarget() in instances to easily workaround the issue whenever for some reason this happens.

It might be that https://github.com/TrinityCore/TrinityCore/pull/24539 fixes the issue

**Comment by jackpoz** [comment]
I opened a PR https://github.com/TrinityCore/TrinityCore/pull/24646 to allow to disable hp regen in raids when the target is not reachable using a setting. It also add debug logs.

**Comment by joshwhedon** [comment]
@Jildor  that is due to dark Halion not being in combat when the fight starts, as a result yeah he regens. It makes sense that he is not in combat as there is no target. Onyxia however is a weird one.

**Comment by jackpoz** [comment]
I merged the PR https://github.com/TrinityCore/TrinityCore/pull/24646 , you can enable the log to see why Onyxia regens HP

**Comment by Aokromes** [comment]
maybe related? https://gist.github.com/Aokromes/6a20f950d49b8c0086eae9694282b9bc

**Comment by Killyana** [comment]
Npcs that can fly and have ground=0 will evades when chasing their target, it could be the same for Onyxia if we didn't restore the correct movement in pahse3

**Comment by jackpoz** [comment]
does https://github.com/TrinityCore/TrinityCore/pull/24634/ fix that ?

**Comment by Killyana** [comment]
I didn't test it

**Comment by Killyana** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/fdcb7388a64bf61a691535933a9fbae0504b80cc
