### ISSUE TITLE
[3.3.5a] Need advise about balance druid talent - Force of Nature

### ISSUE THREAD

**Issue by noszone** [TrinityCore/TrinityCore#24609]
**Description:**
Possible need to fix the cooldown of spell as per patch-note:
https://wow.gamepedia.com/Patch_3.0.2
[Force of Nature] (Balance): Cooldown reduced to 2 minutes, down from 3. 

**Current behaviour:**
Cooldown of spell - 3 minutes.

**Expected behaviour:**
Cooldown of spell should be 2 minutes. 

As per all 3x patch-notes (after 3.0.2) could not find any mentions about this spell.
https://wow.gamepedia.com/Patch/3.x

**Steps to reproduce the problem:**
See the spell description and actual cooldown now is a 3 minutes.

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
TrinityCore - 2420b17

**Operating system:**
Debian GNU/Linux 10

**Comment by joshwhedon** [comment]
Careful with the patch notes on the wiki, not only anyone can modify them, but also often stuff from PTR sneak into them.

**Comment by Jildor** [comment]
Seems ptr change, but maybe was reverted before start 3.1 or something, because in cata still 3 min CD

**Comment by noszone** [comment]
Even if on wowhead? Due this mention is everywhere in net.
https://www.wowhead.com/patchnotes=3.0.2

**Comment by Jildor** [comment]
Yep, but is ptr version, as I said, maybe this change was reverted before oficial wotlk version.

**Comment by noszone** [comment]
Thanks for explaining. Will know in future.
