### ISSUE TITLE
[3.3.5] ICC - Lich King: Movement during Harvest Soul

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24600]
**Description:**

When you do LK encounter in heroic mode, when he launch Harvest Souls, players are teleported into the frostmourne:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L1046-L1057

Seems when finish cast spell Lich King follow the players into the frostmourne, when you exit of frostmourne, lich king not appear because is under textures following players and after 30-60 seconds return.

maybe related with: #24076

**Expected behaviour:**

LK should stay without move during frostmourne phase.

**Steps to reproduce the problem:**

1. go cre id 36597 in heroic mode
2. start encounter and go to phase 3
3. wait to harvest souls and see

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 9b5375f858b7a9bac409cc0b17c56391f2787f5b

**Comment by Rushor** [comment]
lichking wants to attack player in the frostmorne room. there is a spellarea and a Canaiattack prevention. 
but somehow the aura is no longer applied in forstmourne room even with the link in spell_area

**Comment by Jildor** [comment]
What aura?

**Comment by Killyana** [comment]
Same in normal  mode if the player that has te aggro get teleport to the room.

**Comment by Jildor** [comment]
lul you're right
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L565-L569

```
ID - 74276 In Frostmourne Room
```
isn't applied because for some reason the area not is 4910 now when you teleport to Frostmourne room

.go xyz 503 -2527 1055 631
and
.gps

```
no VMAP available for area info
Map: 631 (Icecrown Citadel) Zone: 4812 (Icecrown Citadel) Area: 4859 (The Frozen Throne) Phase: 4294967295
X: 503.218048 Y: -2530.830078 Z: 1049.865479 Orientation: 0.313374
grid[32,27]cell[7,2] InstanceID: 10
 ZoneX: 72.930298 ZoneY: 66.763710
GroundZ: 0.000000 FloorZ: 1049.864990 Have height data (Map: 1 VMap: 0 MMap: 1)
```

Now I do the same in a TC rev about 2017:
```
You are indoors.
Map: 631 (Icecrown Citadel) Zone: 4812 (Icecrown Citadel) Area: 4910 (Frostmourne) Phase: 4294967295
X: 501.722290 Y: -2527.162598 Z: 1049.865479 Orientation: 3.268133
grid[32,27]cell[7,2] InstanceID: 1
 ZoneX: 72.900238 ZoneY: 66.782104
GroundZ: 0.000000 FloorZ: 1049.864990 Have height data (Map: 1 VMap: 1 MMap: 1)
```

different area now, wtf

**Comment by Rushor** [comment]
yes i was like wtf aswell. the spellarea worked 100 like 4 years ago.

maybe we should readd the aura manuall to the player instead of using spell_area?

**Comment by Jildor** [comment]
I don't think so, the problem is the area is different now, I don't know why, we need find whats happened
@jackpoz do you know what happens here?

**Comment by Shauren** [comment]
Let us ignore the area for a moment, XT-002 has a similar issue and is not restricted by area in any way

I believe this 9080e7863c28df7dc1c2af321964776e7b59e41a caused both to break

**Comment by Shauren** [comment]
And for area id being incorrect, its 3.3.5 missing stuff from master branch - 42f9deb21ec68e169f7ed1c8cf14092f144b22da

**Comment by ccrs** [comment]
@Faq or @ForesterDev  can you please help with that https://github.com/TrinityCore/TrinityCore/issues/24600#issuecomment-626825200 ? 😄

**Comment by Jildor** [comment]
well, the lich king movement is fixed with https://github.com/TrinityCore/TrinityCore/commit/472e1fd8aeea80c6b32253007a204e645f89dc2e 👍 
we need a cherry-pick of 42f9deb for complete

**Comment by Rushor** [comment]
cherry picking https://github.com/TrinityCore/TrinityCore/commit/42f9deb21ec68e169f7ed1c8cf14092f144b22da is easy for 335? what do you think?

**Comment by Killyana** [comment]
@Faq this could be closed?

**Comment by Rushor** [comment]
@ccrs THIS https://github.com/TrinityCore/TrinityCore/commit/9080e7863c28df7dc1c2af321964776e7b59e41a breaks the movement of the oozes at professor putricide. they no longer follow the victim while channeling and instead stay in one place always. needs a fix

**Comment by qyh214** [comment]
> 
> 
> @ccrs THIS [472e1fd](https://github.com/TrinityCore/TrinityCore/commit/472e1fd8aeea80c6b32253007a204e645f89dc2e) breaks the movement of the oozes at professor putricide. they no longer follow the victim while channeling and instead stay in one place always. needs a fix

I test in 2665fd5ab54b3040ab36bcba25b3929d5f11e8d4 25h mode,the movement of the oozes at professor putricide seems well.when it appeard it will stay some ms then follow the victim while channeling.

but The Lich King does have this issue description:he will move during Harvest Soul.In the end, this encounter will not be completed.

**Comment by Killyana** [comment]
After https://github.com/TrinityCore/TrinityCore/commit/0468c70dfe91794ad272594323dd7feb611d0a93
.gps in Frostmourne return the correct area ID
```
no VMAP available for area info
Map: 631 (Citadelle de la Couronne de glace) Zone: 4812 (Citadelle de la Couronne de glace) Area: 4910 (Deuillegivre) Phase: 4294967295
X: 503.000000 Y: -2527.000000 Z: 1049.865601 Orientation: 0.000000
grid[32,27]cell[7,2] InstanceID: 1
 ZoneX: 72.898903 ZoneY: 66.766396
GroundZ: 0.000000 FloorZ: 1049.864990 Have height data (Map: 1 VMap: 0 MMap: 1)

**Comment by Killyana** [comment]
And the LK is no longer following players in Frostmourne
