### ISSUE TITLE
Login succeeded, but the game version can't be verified

### ISSUE THREAD

**Issue by hotarzhang** [TrinityCore/TrinityCore#24619]
3.3.5(12340)

**Comment by Aokromes** [comment]
works for me and most of world.

**Comment by hotarzhang** [comment]
> works for me and most of world.


I set up the server according to the document. The client version of TAIWAN is 3.3.5 (12340). After the account is created, and the login succeeds. Then I will prompt the unverifiable version to disconnect the game. The client log information is:
5/14 18:05:00.435  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
5/14 18:05:00.520  GRUNT: state: RESPONSE_CONNECTED result: LOGIN_OK 47.75.41.57:3724
5/14 18:05:00.560  GRUNT: state: LOGIN_STATE_AUTHENTICATING result: LOGIN_OK 
5/14 18:05:00.650  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_BADVERSION 
5/14 18:05:00.674  GRUNT: state: LOGIN_STATE_DISCONNECTED result: LOGIN_OK 
5/14 18:05:00.691  GRUNT: state: LOGIN_STATE_FAILED result: DISCONNECTED

**Comment by illfated** [comment]
~~Hmm. Is there a missing `a` in the Taiwanese (zhTW) 3.3.5 (12340) game client, compared to enGB/enUS 3.3.5**a** (12340) ?~~

Never mind. Scratch that. Patch **3.3.5** is subversion **12213**, not 12340.

**Comment by Faq** [comment]
And you didnt provide rev number

**Comment by illfated** [comment]
For all we know, it could just as easily be a custom game client issue.

**Comment by hotarzhang** [comment]
> For all we know, it could just as easily be a custom game client issue.

Thanks，its OK。
but server is offline all the time
