### ISSUE TITLE
trash mobs on icc respawn after boss kill

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#24615]
**Description:**

most of trash aren't linked to a boss acording
```
SELECT COUNT(*) FROM linked_respawn WHERE guid NOT IN (SELECT guid FROM creature WHERE map=631);
SELECT COUNT(*) FROM linked_respawn WHERE guid IN (SELECT guid FROM creature WHERE map=631);
```
**Current behaviour:**

trash mobs respawn

**Expected behaviour:**

trash mobs doesn't respawn

**Steps to reproduce the problem:**

1. go icc
2. kill all trashmobs before 1st boss
3. kill boss
4. return after few days before reset
5. notice trashmobs respawned

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0c7655e4ccff

**Operating system:** debian 10 x64.

**Comment by Killyana** [comment]
We have a general issue for all dungeon/raids https://github.com/TrinityCore/TrinityCore/issues/20108
