### ISSUE TITLE
[3.3.5a] Razorgore the Untamed - QAE Charm

### ISSUE THREAD

**Issue by Conscript01** [TrinityCore/TrinityCore#24613]
Description:

Player is stucked in controlling Razorgore, even when last egg is destroyed. This results into unkillable boss.

GM have to remove aura "QAE Charm" ID:42013

Expected behaviour:

When last egg is destroyed, player should stop controlling Razorgore.

Steps to reproduce the problem:

.go xyz -7615.86 -1024.67 413.38 469
use orb of domination (gobj next to you)
control boss and destroy all the eggs
-- try to remove control or destroy all the eggs (control should be automatically canceled)

Branch(es):

3.3.5

TC rev. hash/commit:

c32ec72983fa

Operating system: debian 10 x64

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c32ec72983fa there is no such rev on trinitycore.

**Comment by Conscript01** [comment]
issue is still valid for latest TC

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21259
