### ISSUE TITLE
Azerite talents are not saved in database

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/TrinityCore#24610]
**Description:**
Azerite talents are not saved to db and when u unlock second talent u cant save, u try and when u click nothing happen 
**Steps to reproduce the problem:**
give azerite, try to put second talent

**Branch(es):**

master 

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/00a0c6e7ededcb98b42bccfb636d40bc8c2831e4

**Operating system:** Windows 10

**Comment by Shauren** [comment]
azerite armor or essences in neck?

**Comment by Thordekk** [comment]
azerite armor when u unlock talents u put the first relog and not saved, second azerite talent never can put u click but dissappear talent again

**Comment by Shauren** [comment]
I'm not seeing this https://youtu.be/Ye22wQKPAco
