### ISSUE TITLE
[3.3.5a]Druid feral charge (bear) resetting auto attacks

### ISSUE THREAD

**Issue by noszone** [TrinityCore/TrinityCore#24626]
**Description:**
After using druid feral charge (bear) there is delay about 1-2.5 seconds, before druid hits first time the target with normal white attack.

**To reproduce issue:**
Get druid feral, from distance start attack in order to enter in fight and use a charge on target. You will see a druid waiting for something and do not attacking a target in first 2 seconds.

**Expected behavior:**
Should attack immediately once charge used on target without delay. 

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
TrinityCore - 2420b17

**Operating system:**
Debian GNU/Linux 10

**Comment by noszone** [comment]
Could be related to that issues?
#17589
#6399

**Comment by Didr** [comment]
Also seems to be happening to warrior charge. On commit 6e34e07

Here's a clip of it in action: https://i.gyazo.com/d064e9b134420e4a7cfff7aecad6dd77.mp4

**Comment by Jildor** [comment]
this happens because when do SPELL_EFFECT_CHARGE, do: https://github.com/TrinityCore/TrinityCore/blob/740afc71358c32257540350a6d7d4071a851452f/src/server/game/Spells/SpellEffects.cpp#L4245

caster isn't at meleerange with victim, so send error msg too far away and reset attacktime

**Comment by disclosurez** [comment]
how can this be fixed?

> 
> 
> this happens because when do SPELL_EFFECT_CHARGE, do:
> 
> https://github.com/TrinityCore/TrinityCore/blob/740afc71358c32257540350a6d7d4071a851452f/src/server/game/Spells/SpellEffects.cpp#L4245
> 
> caster isn't at meleerange with victim, so send error msg too far away and reset attacktime

**Comment by Juggalo187** [comment]
I seemed to fix it by commenting out `movement->BaseUnitState = UNIT_STATE_CHARGING;`  from src\server\game\Movement\MotionMaster.cpp

Like this..... I'm ot sure if there is a negative effect of doing so though.
`void MotionMaster::MoveCharge(float x, float y, float z, float speed /*= SPEED_CHARGE*/, uint32 id /*= EVENT_CHARGE*/, bool generatePath /*= false*/)
{
/*
    if (_slot[MOTION_SLOT_CONTROLLED] && _slot[MOTION_SLOT_CONTROLLED]->GetMovementGeneratorType() != DISTRACT_MOTION_TYPE)
        return;
*/
    if (_owner->GetTypeId() == TYPEID_PLAYER)
    {
        TC_LOG_DEBUG("movement.motionmaster", "MotionMaster::MoveCharge: '%s', charging point Id: %u (X: %f, Y: %f, Z: %f)", _owner->GetGUID().ToString().c_str(), id, x, y, z);
        PointMovementGenerator<Player>* movement = new PointMovementGenerator<Player>(id, x, y, z, generatePath, speed);
        movement->Priority = MOTION_PRIORITY_HIGHEST;
        //movement->BaseUnitState = UNIT_STATE_CHARGING; 
        Add(movement);
    }
    else
    {
        TC_LOG_DEBUG("movement.motionmaster", "MotionMaster::MoveCharge: '%s', charging point Id: %u (X: %f, Y: %f, Z: %f)", _owner->GetGUID().ToString().c_str(), id, x, y, z);
        PointMovementGenerator<Creature>* movement = new PointMovementGenerator<Creature>(id, x, y, z, generatePath, speed);
        movement->Priority = MOTION_PRIORITY_HIGHEST;
        movement->BaseUnitState = UNIT_STATE_CHARGING;
        Add(movement);
    }
}`
