### ISSUE TITLE
Shadowstep distance to target

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#24633]
**Description:**

When casting Shadowstep you appear too far behind your target

**Current behaviour:**

Casting Shadowstep teleports you too far behind your target.
[Screenshot](https://imgur.com/tknlXxx)

**Expected behaviour:**

You should appear closer to your target.
[Screenshot](https://imgur.com/GKRXP57)

**Steps to reproduce the problem:**

1. Cast Shadowstep

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8ad0ab362ee3

**Operating system:** 

Windows 10 64

**Comment by jackpoz** [comment]
@Ovahlord wanna take a look at this if it's about the new MovePositionToFirstCollision ?

**Comment by Ovahlord** [comment]
It shouldn't be affected by this at all. There's just many places in the core that use GetNearPoint that in many cases falsely uses the combat reach of the caster and the target as additional range values.

**Comment by Faq** [comment]
from #24628 to this issue

**Comment by jackpoz** [comment]
Cannot reproduce (or at least the distance looks good):

Before casting:
![image](https://user-images.githubusercontent.com/1153754/83360341-d9984d80-a380-11ea-8e5d-8e3e1e5c368a.png)

After casting:
![image](https://user-images.githubusercontent.com/1153754/83360361-0cdadc80-a381-11ea-9c37-0e0afb6ac91d.png)

>The distance is: (3D) 1.067615 (2D) 0.999800 (Exact 3D) 4.067615 (Exact 2D) 3.999800 yards.

Please include .go xyz positions of the Rogue and the Target and where you teleport and where you expect it to teleport

**Comment by JakobJR** [comment]
That distance is further than any other server out there. Compare to some of the big private servers, you'll see the difference. The distance is too big as it is now.

**Comment by lingxDEV** [comment]
I'm pretty sure the distance needs to be 3 yards 2D

**Comment by lingxDEV** [comment]
You can compare to some of the big servers, it is too far as it is now.

**Comment by jackpoz** [comment]
3 yards Exact 2D or ?

**Comment by lingxDEV** [comment]
Yea

**Comment by jackpoz** [comment]
This has been like this since https://github.com/TrinityCore/TrinityCore/commit/9dbef4b6bb7c9f28e9140782d938f41ed04df6f2#diff-f82ab5d79483dd6e1f5bd8c4d94299d3R4471 with investigation done at https://github.com/TrinityCore/TrinityCore/pull/20434#issuecomment-332624039

Do you know what the blizzlike value is ? It doesn't matter really what the "big servers" have.

**Comment by lingxDEV** [comment]
I've been looking around. All the sources I can find says 2 yards. I know 4 yards are way too far, maybe 2 yards is blizzlike.

https://gitmemory.com/issue/TBC5ManTracker/Issues/56/526746730
https://www.wow-freakz.com/spells.php?spell=143285&name=shadowstep Effect #1

**Comment by lingxDEV** [comment]
Just looked up Shadowstep on wowhead, also states 2 yards:

https://www.wowhead.com/spell=36563/shadowstep

**Comment by lingxDEV** [comment]
This is from wowhead in 2010:

https://web.archive.org/web/20100630052141/http://www.wowhead.com/spell=36563

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/20434
here explain about shadowstep 4yd, seems for prevent that error: https://github.com/TrinityCore/TrinityCore/issues/8758

but, maybe force shadowstep to 4yd is wrong

**Comment by Jildor** [comment]
we can see here shadowstep dist:
https://www.youtube.com/watch?v=GJLRfJ881Pk <-- 0:05
https://www.youtube.com/watch?v=W0OAeEJ3SYg <-- 0:17
https://www.youtube.com/watch?v=QqPgS7UbQKw <-- 0:23

seems less than 4yd

**Comment by jackpoz** [comment]
@chaodhib would you like to join the discussion ?

**Comment by chaodhib** [comment]
I could have been wrong. However, I used (exact?) sniff data that indicated that it was 4y (2D). Here is what I used at that time: https://gist.github.com/chaodhib/13a4fa81c4a0ba38f88d92a6aa1afe0f. Relying solely on video clips seems less reliable than sniff data. Maybe my interpretation of sniff data was wrong?

**Comment by lingxDEV** [comment]
I don't know more proof you want than the 2010 wowhead screenshot.

I'm confident it's 2 yard.

**Comment by Jildor** [comment]
@lingxDEV wowhead data is DBC data of the spell 2yd and that shows in spellwork:
```
Effect 0: Id 5 (SPELL_EFFECT_TELEPORT_UNITS)
BasePoints = 1
Targets (1, 65) (TARGET_UNIT_CASTER, TARGET_DEST_TARGET_BACK)
Radius (Id 7) 2,00
```

@chaodhib we can get more sniff about this spells?, with only that I think shouldn't have changed the radius.
And the videos may not be as exact as the numbers, but it is evident that the distance is less than 4yd.
If the DBC value is 2yd and the videos show that the distance is less than 4yd, I think it should not be forced to 4yd

**Comment by chaodhib** [comment]
Sure. I agree with both of you. There is one remaining conundrum though: how do you explain the 4y 2D distance in the sniff?

**Comment by Jildor** [comment]
I have not dealt much with sniffs, so I do not have much experience there, I do not even know if it is from version 3.3.5, the position numbers show the distance at which the target and the caster are or show the distance traveled in  the teleport?  perhaps the target was in motion?

**Comment by Aokromes** [comment]
ServerToClient: MSG_MOVE_STOP_TURN (0x00BE) Length: 37 ConnIdx: 0 Time: 07/16/2010 20:40:16.000 Number: 160716

it's clearly wow 3.3.5a sniff.

**Comment by Jildor** [comment]
in theory this is the sniff position, maybe it has a somewhat greater distance because it is a slope?
We just have a single sniff on this?

**Comment by chaodhib** [comment]
I looked for other sniffs of Shadowstep: https://gist.github.com/chaodhib/d21749ad0c4e250c5602fdb69d4d07ed#file-gistfile1-txt

So we can see that sometime, it's 4y. Other times, it's 2y. Why? No clue. You are very welcome to do a more in-depth analysis and submit a PR with your findings.

PS: Sniffs are a much more reliable source of information than DBC data. You should start using them.

**Comment by Jildor** [comment]
thx, I don't know why this 2D difference, maybe victim radius or mmap relocation?
Anyway, I think should be remove 4yd forced radius, so I will try with a PR

PS: just out of curiosity, which map is anfiteatro_argent_oculus?, I try to recreate the ingame positions, but I can't find the right map for those sniffs xD

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/56d60ee00c094464082e3ed2a70d669d415ca49c

**Comment by chaodhib** [comment]
While it's a good temporary work around to use 2y all the time, I wouldn't consider the Shadowstep distance to have been fixed. The issue went from "Shadow step should be 2y. Right now, it's 4y" to Shadowstep is always 2 yards but it should be 4 yards in some (unexplained so far) situations". So it's still open.
