### ISSUE TITLE
[3.3.5] Blink

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#24644]
**Description:**

First of all, really good job on the updates in https://github.com/TrinityCore/TrinityCore/commit/c0b75bf40da8b447a2f3533dabbfad9eba7c6ea1

Issues where you could blink underground/behind walls appear to be fixed completely, i just noticed that blink appears to have gotten an unusually large buff haha

https://drive.google.com/uc?id=18KQqe867qkUDL6BJbhhDnl1pHmv5zUe8

**Current behaviour:**

You can blink from the bottom of the slope to the top

**Expected behaviour:**

Im not 110% sure if this is a bug, it just feels a bit overpowered :P

**Steps to reproduce the problem:**

1. .go xyz 1398.534 1512.965 325.628 489 (orientation facing towards the slope)
2. cast blink
3. You are at the top of the slope

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8a9f80909387615fb7e22a0f8a042c3ad7a10cfc

**Operating system:** Windows 10

**Comment by jackpoz** [comment]
we could reduce the slope angle in mmaps for bgs

**Comment by jackpoz** [comment]
btw when reporting issues about mmaps it helps a lot the output of .mmap loc

**Comment by VincentVanclef** [comment]
Ah sorry, ill remember that thank you

**Comment by jackpoz** [comment]
![image](https://user-images.githubusercontent.com/1153754/82155358-97e1b000-9874-11ea-91c9-7830df8f5b6c.png)

Map 469 gridloc [29, 29]

**Comment by jackpoz** [comment]
This could be solved by using a different area flag in recast for slopes between 55° and 70° . One thing that recast doesn't support is single direction of walkable paths, i.e. a blink downward should be allowed but a blink upward shouldn't

**Comment by jackpoz** [comment]
In the time being we could split the raycast used by blink in smaller steps, check the slope and stop at the one before 55°

**Comment by VincentVanclef** [comment]
Can you make a pr then ill happily do the testing if required

**Comment by jackpoz** [comment]
Well it needs to be developed first

**Comment by jackpoz** [comment]
btw does this affect charge also ?

**Comment by jackpoz** [comment]
I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/24765, it requires to re-extract mmaps

**Comment by jackpoz** [comment]
@VincentVanclef the pr is ready to be tested, there's a link to a realm with the pr applied too. Please test it and let me know
