### ISSUE TITLE
No loot from Kel'Thuzad

### ISSUE THREAD

**Issue by Payk1488** [TrinityCore/TrinityCore#24642]
**Description:**
After the assassination of Kel'Thuzad in Naxxramas, his body disappears and it is impossible to get prey from him.
**To reproduce issue:**
Tested this boss passing all its phases of the battle. Once he was killed, his body disappears and no prey can be obtained. Then comes the dialogue, and later Kael'Thuzad reappears and cannot be distinguished even from the attack.
Although if you kill him with the command ".dei", the body remains and prey can be obtained.
**Branch(es):**
3.3.5
**TC rev. hash/commit:**
TrinityCore - 2420b17
**Operating system:**
win 10

**Comment by joshwhedon** [comment]
I have seen that happen too. It looked like somehow, Kel'thuzad _DespawnAtEvade() had been called when he got killed. Resulting in loot not being available, and him respawning unselectable. I haven't been able to reproduce it myself though.

**Comment by Payk1488** [comment]
> I have seen that happen too. It looked like somehow, Kel'thuzad _DespawnAtEvade() had been called when he got killed. Resulting in loot not being available, and him respawning unselectable. I haven't been able to reproduce it myself though.

**Comment by Payk1488** [comment]
> I have seen that happen too. It looked like somehow, Kel'thuzad _DespawnAtEvade() had been called when he got killed. Resulting in loot not being available, and him respawning unselectable. I haven't been able to reproduce it myself though.

 void EnterEvadeMode(EvadeReason /*why*/) override
            {
                for (NAXData64 portalData : portalList)
                    if (GameObject* portal = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(portalData)))
                        portal->SetGoState(GO_STATE_READY);

                Reset();
                **_DespawnAtEvade();**
            }



Did I understand you correctly that you need to delete this line of code?

**Comment by Payk1488** [comment]
> I have seen that happen too. It looked like somehow, Kel'thuzad _DespawnAtEvade() had been called when he got killed. Resulting in loot not being available, and him respawning unselectable. I haven't been able to reproduce it myself though.

Thank you, your advice helped solve this problem.

**Comment by ccrs** [comment]
post the solution then :D

**Comment by Rushor** [comment]
you can try

//_DespawnAtEvade();
                me->SetHealth(me->GetMaxHealth());
                me->GetMotionMaster()->MovePoint(2, me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY(), me->GetHomePosition().GetPositionZ(), true, 2.932f);

but for sure that needs adjustment

**Comment by Jildor** [comment]
What are the steps to reproduce the problem?
I have entered combat, I have waited for him to enter phase 2, I have lowered his life until he enters phase 3, I have damaged him with .damage until he is low hp and I have killed him using class skills in the normal way and the boss does not enter in evade, it can be looted.

**Comment by Aokromes** [comment]
> What are the steps to reproduce the problem?
> I have entered combat, I have waited for him to enter phase 2, I have lowered his life until he enters phase 3, I have damaged him with .damage until he is low hp and I have killed him using class skills in the normal way and the boss does not enter in evade, it can be looted.

i have seen myself as player, never got reproduced with gm.

**Comment by illfated** [comment]
@Jildor : Did you test alone? I am thinking that maybe the others who claim they don't get any loot have triggered evade due to max threat changing during the fight. Although it would be a lot better if someone could confirm what they did during a fight to have him evade or end up without any loot, not to mention if they used any non-TC source.

**Comment by Jildor** [comment]
I tested it with 3 players

@Aokromes any relevant info?
expecific difficulty mode or both?

**Comment by Jildor** [comment]
I think is caused by this:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp#L820-L825

when kel'thuzad die, if there are guardians alive, do:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp#L806-L814

so I think enterevademode guardian and kel'thuzad enterevademode and despawn?

**Comment by joshwhedon** [comment]
Oh, that is very possible.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/aeb41e67a92b7cd0c75683a269fb0ca75309e9a0

**Comment by illfated** [comment]
(Ref. https://github.com/TrinityCore/TrinityCore/issues/24642#issuecomment-640191804 - to see which line numbers were used before the new PR & commit:)

> I think is caused by this:
https://github.com/TrinityCore/TrinityCore/blob/e3b232fe0e5c21a87d3fe71813e9d750259823f1/src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp#L820-L825
>
> when Kel'thuzad dies, if there are guardians alive, do:
https://github.com/TrinityCore/TrinityCore/blob/e3b232fe0e5c21a87d3fe71813e9d750259823f1/src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp#L806-L814
