### ISSUE TITLE
Nyoma cooking supply store

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#24653]
**Description:**

When using this vendor all that happens is a default conversation message screen comes up.

**Expected behavior:**

When clicking on the vendor cooking supplies selection should come up

**Steps to reproduce the problem:**
1. Nyome DB GUID 312723, Entry 4265, Display ID 4236
2. go to Teldrassil and talk to the vendor https://classic.wowhead.com/npc=4265/nyoma
3. The store should come up, but does not.

**Branch(es):**
 Master

**TC rev. hash/commit:** 
Rev d1572327d21f

**Operating system:** Windows 10

**Comment by illfated** [comment]
Seems related to your own ticket #24654 and to innkeeper gossip ticket #17411 -- if these 3 tickets are caused by the same base issue, maybe make the oldest ticket a general ticket for gossip issues in master?

**Comment by Naddley** [comment]
Vendor works.
