### ISSUE TITLE
[3.3.5] ICC - Sindragosa: Movement after wipe

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24656]
**Description:**

When you wipe in sindragosa, if the boss is in fly phase, the boss reset in her correct position, but still flying.
When you agro it again, sindragosa doesn't move untill enter in fly phase (after this, when return to ground phase can be move ok)
Seems something related with fly movement doesn't reset properly when wipe in fly phase.

**Expected behaviour:**

Should move when enter combat.

**Steps to reproduce the problem:**

1. start encounter with sindragosa and wait to fly phase
2. kill yourself or do .gm on
3. start encounter again and see

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 2815db52a643bdfa397317b79d5b3f68995b343e

**Comment by Rushor** [comment]
add this to the reset call once summoned

```
me->setActive(false);
                    me->SetFarVisible(false);
                    me->SetCanFly(false);
                    me->SetDisableGravity(false);
                    me->RemoveByteFlag(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_ALWAYS_STAND | UNIT_BYTE1_FLAG_HOVER);
                    me->SetHomePosition(SindragosaLandPos);
                    me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                    me->SetSpeedRate(MOVE_FLIGHT, 2.5f);
```

**Comment by Jildor** [comment]
hmmm, sindragosa stay in REACT_PASSIVE and seems should get REACT_DEFENSIVE in JustReachedHome, but for some reason stay passive if enterevademode in fly phase.

With @Rushor suggestion works, but I'm not sure if can be the best solution add this in reset.

**Comment by Jildor** [comment]
seems sindragosa stay passive when enterevademode, I don't know if can be the best add this in reset as @Rushor say or should add something in JustReachedHome.
I will try to do a PR in JustReachedHome, seems better.
