### ISSUE TITLE
[Mage] Frostfire Bolt combat bug

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#24652]
**Description:**

Frostfire Bolt is causing a combat bug on the last tick of its DoT.

**Expected behaviour:**

The last DoT tick from Frostfire Bolt should not cause combat between caster and target.

**Steps to reproduce the problem:**

1. Make a mage and test Frostfire Bolt

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8ad0ab362ee3

**Operating system:** 

Win10 64

**Comment by Killyana** [comment]
Why the last tick only?
It sounds weird.

**Comment by lingxDEV** [comment]
> Why the last tick only?
> It sounds weird.

I'm not sure, but it's still happening.

**Comment by jackpoz** [comment]
39a1fd48905c4bec2d6d005ca96375e1c4c5f2ef
