### ISSUE TITLE
[3.3.5] Ulduar - Flame Leviathan: Movement

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24657]
**Description:**

Seems when Flame Leviathan finish ACTION_MOVE_TO_CENTER_POSITION, it doesn't move anymore.

I do .npc info and appear:
```
React state: PASSIVE
```

maybe related with passive state?

**Expected behaviour:**

Should move

**Steps to reproduce the problem:**

1. Start encounter with Flame Leviathan
2. go away and see

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 2815db5

**Comment by joshwhedon** [comment]
Is this reproducible or the same issue as https://github.com/TrinityCore/TrinityCore/issues/24552 ?
Because the REACT_PASSIVE is removed on movement inform, and it looks like movement inform has not been called for you. So probably the same issue.

**Comment by Jildor** [comment]
maybe, I see in this issue #24656 sindragosa stay in REACT_PASSIVE too instead of get REACT_DEFENSIVE by JustReachedHome, I don't know if can be related too

**Comment by Jildor** [comment]
I debugged MovementInform part of the boss script and seems MovementInform is executed, get action id 10 (ACTION_MOVE_TO_CENTER_POSITION) in log.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp#L565-L571

but for some reason still in react passive.

**Comment by Jildor** [comment]
ok, I removed this line:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp#L278

and now appear agressive, but it still can't move
