### ISSUE TITLE
Zarrin Cooking Trainer

### ISSUE THREAD

**Issue by phantomdl** [TrinityCore/TrinityCore#24654]
**Description:**

When using this cooking trainer the training menu does not come up
Zarrin Cooking Trainer DB GUID 312722, Entry 6286, Display ID 4989

**Expected behavior:**

When clicking on the NPC the cooking training menu should come up

**Steps to reproduce the problem:**
1. go to Teldrassil and talk to the cooking trainer https://classic.wowhead.com/npc=6286/zarrin
2. The training menu should come up but does not.

**Branch(es):**
 Master

**TC rev. hash/commit:** 
Rev d1572327d21f

**Operating system:** Windows 10

**Comment by illfated** [comment]
Seems related to your own ticket #24653 and to innkeeper gossip ticket #17411 -- if these 3 tickets are caused by the same base issue, maybe make the oldest ticket a general ticket for gossip issues in master?
