### ISSUE TITLE
DB/GameObject: Convert & update support for Jump-a-tron 4000 to SAI

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24668]
Can't understand this check `if (player->GetQuestStatus(10111) == QUEST_STATUS_INCOMPLETE)`
The key for Jump-a-tron is the reward from previous quest https://www.wowhead.com/item=27808/jump-a-tron-4000-key#comments:id=12748
Also you should be able to restore the key after losing
So why the object requires to take second quest in the chain

--

There's a lot of methods to script it, including self cast or gameobject cast or cross cast. Everything depends on what should be in the combat log after cast. I used cross cast with creature 'Jump-a-tron 4000' as caster
```sql
--
DELETE FROM `disables` WHERE `sourceType` = 0 AND `entry` = 33382;
INSERT INTO `disables` (`sourceType`,`entry`,`flags`,`params_0`,`params_1`,`comment`) VALUES
(0,33382,64,0,0,"Disable LoS for spell 'Jump-a-tron'");

-- Jump-a-tron 4000 SAI
UPDATE `gameobject_template` SET `AIName` = "SmartGameObjectAI", `ScriptName` = "" WHERE `entry` = 183146;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 183146 AND `source_type` = 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
-- Can't script this with On Event 12275 Inform, invoker target is not supported for this event
(183146,1,0,0,64,0,100,0,1,0,0,0,0,86,33382,0,19,19041,0,0,7,0,0,0,0,0,0,0,0,"Jump-a-tron 4000 - On Gossip Hello - Cross Cast 'Jump-a-tron'");
```
**Branch:** 3.3.5
**TC rev. hash/commit:** 69dc704cd5cf
**Operating system:** Windows 8.1

**Comment by Killyana** [comment]
Always check the gob template for this kind of things, they usually use an event_scripts:
``` sql
DELETE FROM `event_scripts` WHERE `id`=12275;
INSERT INTO `event_scripts` (`id`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(12275,0,15,33382,3,0,0,0,0,0);
```
Also no need to disable los for this spell, it works just fine

**Comment by offl** [comment]
As I said the implentation depends on what is in sniffs \ combat log and I wanted to use spawned trigger which is not possible in event_scripts

**Comment by Killyana** [comment]
We don't have any sniff with this spell, but in spellwork you can see the target is not self so in this case must be cast by the unit that trigger the event:
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
Aura Id 105 (SPELL_AURA_FEATHER_FALL), value = 1, misc = 0 (0), miscB = 0, periodic = 0

Effect 1: Id 98 (SPELL_EFFECT_KNOCK_BACK)
BasePoints = 500
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
EffectMiscValueA = 50
