### ISSUE TITLE
 Ulduar: boss XT-002 heroic mode.

### ISSUE THREAD

**Issue by Payk1488** [TrinityCore/TrinityCore#24667]
**Current behaviour:**
During the fight with this boss, you can’t break your heart. The problem is that during an attack on it, it restores its health. Because of this, it’s not possible to switch to the heroic difficulty mode.
One gets the impression that the heart does not attack anyone and is in a passive state, as a result of which it restores its health.
**Expected behaviour:**
The heart should not restore its health.
**Steps to reproduce the problem:**
1. Came to the Ulduar and started the battle with the boss XT-002.
2. Damaged until the heart appeared.
3. Damage using spells and the command .damage.

**Branch(ru):**
3.3.5a 
**TC rev. hash/commit:**
TrinityCore - e956b17
**Operating system:**
win 10

**Comment by Payk1488** [comment]
For all these days, I could not find the reason why the heart restores its health. If the "npc_xt002_heart" brush is removed from the "create_template" table, then the heart attacks and does not restore health.
What could be the problem? Due to this error, the boss cannot be put into difficult mode.
Thank.

**Comment by Aokromes** [comment]
you may want to add
Logger.entities.unit.chase=2,Chase
Appender.Chase=2,1,15,server/chase.log

to your conf.

**Comment by Payk1488** [comment]
> you may want to add
> Logger.entities.unit.chase=2,Chase
> Appender.Chase=2,1,15,server/chase.log
> 
> to your conf.

Thanks for the answer. But how does this help solve the problem?

**Comment by Aokromes** [comment]
it will help to determine the reason of the bug.

**Comment by Payk1488** [comment]
I did everything as you said. The chase_ (this_date) .log file is empty and no errors occur.
Then what could be the problem that the heart regains its health? This effect resembles a situation where, using the .damage command, they deal NPC damage over a long distance. In these cases, they also restore their health.

**Comment by Aokromes** [comment]
you need to update core to have that log working.

**Comment by Payk1488** [comment]
https://github.com/TrinityCore/TrinityCore/blob/6c1a874e5702a2dbefd4b4685c41a9d6c51dd2bb/src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp#L396

I think I found a solution to this problem. I changed "NullCreatureAI" to "ScriptedAI". And also "NullCreatureAI (creature)" to "ScriptedAI (creature)".

**Comment by Keader** [comment]
05eeaade3e4e15028143575dcb16267959a2153d
