### ISSUE TITLE
Human starting quests not working

### ISSUE THREAD

**Issue by whyn0** [TrinityCore/TrinityCore#24689]
**Description:**

It looks like starting quests of humans are not working (only the first two).

**Expected behaviour:**

There should be many quests in the spawn area before moving to Goldshire.

**Steps to reproduce the problem:**

1. Create new human character
2. Complete the first two quests

**Branch(es):**

master

**TC rev. hash/commit:** 

4d69cc1c5671

**Operating system:** Windows 10

**Comment by Killyana** [comment]
We have a general issue here https://github.com/TrinityCore/TrinityCore/issues/15182
