### ISSUE TITLE
Worldserver crash

### ISSUE THREAD

**Issue by redbaron99** [TrinityCore/TrinityCore#24680]
**Description:**
server crashs this is serverlog file
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Updating Auth database...
>> Auth database is up-to-date! Containing 22 new and 132 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 14 new and 88 archived updates.
Updating World database...
>> World database is up-to-date! Containing 265 new and 2603 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 46 new and 168 archived updates.
Realm running as realm ID 1
Using World DB: TDB 820.19071
Using enUS DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 19071
Hotfix cache version set to: 0
Using DataDir ../data/
WORLD: MMap data directory is: ../data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ../data/vmaps
Initialize PlayerDump...
>> Initialized 368 PlayerDump ColumnDefinitions in 10 ms.
Loading Trinity strings...
>> Loaded 965 trinity strings in 1 ms
Initialize data stores...

CHANGEME Description of the problem or issue here.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

master

**TC rev. hash/commit:** 4d69cc1c567180b408ddbadb9edf26859cf4c006

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Debian 10

**Comment by Shauren** [comment]
You didn't even bother filling in the template...

**Comment by Aokromes** [comment]
i vote picnic.

**Comment by redbaron99** [comment]
> And where is the crash log?

there is no crash log just crashs

**Comment by redbaron99** [comment]
https://youtu.be/_smKSHiuXMQ

**Comment by Shauren** [comment]
You know that you dont get crash logs automatically on linux? You have to run it with gdb, we have that on the wiki...

**Comment by redbaron99** [comment]
https://pastebin.com/Lu1s6P8U
[1590151848.zip](https://github.com/TrinityCore/TrinityCore/files/4668108/1590151848.zip)

**Comment by illfated** [comment]
- https://pastebin.com/raw/Lu1s6P8U (raw view)

**Comment by redbaron99** [comment]
can you tellme why i got crash?

**Comment by illfated** [comment]
Seeing that this is source from the master branch, I don't have a comparable setup to try to replicate it. I only use the 3.3.5 branch myself. I can only point to the initial lines of the crash log:
- `/root/TrinityCore/src/server/shared/DataStores/DB2DatabaseLoader.cpp:142`
- `/root/TrinityCore/src/server/shared/DataStores/DB2Store.cpp:139`

The TrinityCore team members are way better prepared to interpret this crash log than me.

**Comment by Aokromes** [comment]
this "crash" it's usually bad db2 / missing files.

**Comment by illfated** [comment]
Good point, looks reasonable based on all the DB2 references in the crash log. 

@redbaron99 : Make sure your game client is the same patch version as the target for master branch (8.3.0.34220), as well as unmodified, before extracting the DB2 files. Use unmodified source to compile the extraction tools (basic initial troubleshooting for this crash). That should be as much as I know for now.

**Comment by Shauren** [comment]
Cannot give you an answer to something I don't run into and noone else has reported anything like this either

**Comment by redbaron99** [comment]
i used this version 8.3.0.34220 for map extract

**Comment by illfated** [comment]
It is difficult to know why this happens to you and nobody else (at least none who have reported this problem recently). Maybe it is a resource problem on your server if it can't produce correct .db2 files (I don't know, I am mostly guessing here). Maybe you need to extract the files on a computer with more than enough resources (CPU & RAM) to avoid any issues during the extraction process. Maybe the game client files are incomplete (I don't know).

**Comment by redbaron99** [comment]
6core cpu and 16gb ram not enough? 500gb ssd

**Comment by Aokromes** [comment]
delete db2 / gt directories and extract then again.

**Comment by illfated** [comment]
Good point. Always useful to clean up target folders & caches when rebuilding stuff.

**Comment by src893** [comment]
Hello I confim the problem seems to be only on linux build. Same error from @redbaron99

1) clone https://github.com/TrinityCore/TrinityCore
2) make install
3) try to start

Here my gdb crash dump https://pastebin.com/raw/zUAWdpnG
