### ISSUE TITLE
Shaman Chain Heal Doesn't Jump to Full HP Targets issue

### ISSUE THREAD

**Issue by epicwow-ir** [TrinityCore/TrinityCore#24704]
In the beginning sorry for my bad English.

**Description:**
**Current behavior:** Shaman Chain Heal Doesn't Jump to Full HP Targets. When you cast Chain Heal (spell=55458) and Party Members (or nearby targets) are Full in HP, Chain Heal heals only Main Target, and Doesn't Jump to Next nearby targets (unless Next target's HP not Full then Chain Heal will jump)
 
**Expected behavior:** Chain Heal MUST Jump to nearby friendly targets or party members ether they are Full in HP or not.

**Branch(es):** 3.3.5

**TC hash/commit:** TrinityCore rev. 77dd751+ 2020-04-15 11:28:46 -0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**TDB version:** 335.20041_2020_04_15

**Operating system:** Debian 10

**Comment by Keader** [comment]
Wrong
It was fixed here: https://github.com/TrinityCore/TrinityCore/pull/22136
Has proofs there.
