### ISSUE TITLE
DB/SAI: Remove excess event flags from timed action lists

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24701]
Correct me if I'm wrong but this should be set in the main script and not in the action list
```sql
--
UPDATE `smart_scripts` SET `event_flags` = `event_flags` &~ 1 WHERE `source_type` = 9; -- SMART_EVENT_FLAG_NOT_REPEATABLE
UPDATE `smart_scripts` SET `event_flags` = `event_flags` &~ 2 WHERE `source_type` = 9; -- SMART_EVENT_FLAG_DIFFICULTY_0
UPDATE `smart_scripts` SET `event_flags` = `event_flags` &~ 4 WHERE `source_type` = 9; -- SMART_EVENT_FLAG_DIFFICULTY_1
```
**Branch:** 3.3.5
**TC rev. hash/commit:** 6b9a14ca940a
**Operating system:** Windows 8.1

**Comment by offl** [comment]
I checked them all just to be sure the no repeat flag is completely useless here and can be considered as typo
Then turned out this flag will not work at all for action lists

**Comment by Killyana** [comment]
Yes for action lists only the flags 512 is valid.
