### ISSUE TITLE
DB/Event: Argent Tournament Val'Kyr invasion

### ISSUE THREAD

**Issue by Nightprince** [TrinityCore/TrinityCore#24723]
**Description:**

This Commit : 
https://github.com/TrinityCore/TrinityCore/commit/69f4024929c546af4cce121b8d6d9adb9f6acefb

Vengeful Valkyr after finish event not despawn.

![WoWScrnShot_053120_004119](https://user-images.githubusercontent.com/12217476/83338392-29233e80-a2d9-11ea-9aad-ae1cc0f0c6df.jpg)

**Expected behaviour:**

NPCs must be despawn.

**Steps to reproduce the problem:**

1. .go 8258.927, 1347.95, 734.1434 571
2. .start event 84
3. wait for finish event

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/0eb9b5bfe65961fb2062e71f33e3e0d8931159bb

**Comment by dr-j** [comment]
These don’t despawn they should despawn either when fjola and eydis get captured or ten minutes which ever sooner can’t set exact time at the moment since grid where creatures spawn needs to be active for script to start so can’t use fixed end time because of this

**Comment by Nightprince** [comment]
> 
> 
> These don’t despawn they should despawn either when fjola and eydis get captured or ten minutes which ever sooner can’t set exact time at the moment since grid where creatures spawn needs to be active for script to start so can’t use fixed end time because of this

but again after start event , spawn new NPCs.

**Comment by dr-j** [comment]
Well can’t reproduce this issue but will mention this have you by any chance added any custom script to despawn them before event ends as this will cause event npcs to respawn after events if they are dead and or respawn timer is started when event ends you can see this with the levrl70etc drums in shattrath

**Comment by Nightprince** [comment]
> 
> 
> Well can’t reproduce this issue but will mention this have you by any chance added any custom script to despawn them before event ends as this will cause event npcs to respawn after events if they are dead and or respawn timer is started when event ends you can see this with the levrl70etc drums in shattrath

But this is a bug. When Event starts several times, number of NPCs increases and all of them stop here.

**Comment by Killyana** [comment]
The grid system sucks for this kind of events, it's not new, you must go near Fjola and Eydis to activate the grids
