### ISSUE TITLE
Vehicle Seat switch Spells didn't work correctly

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#24722]
**Description:**
If you use Spell 84224  - 'Vehicle - Switch to Seat 2' or other (like 84225 etc.) the player begin to switch but the vehicle despawn and player fall out of it. Look like that the core thinks the player will leave the vehicle and call _ExiteVehicle etc. 

**Expected behaviour:**

Player should switch the seat without despawn the vehicle.

**Steps to reproduce the problem:**

1. use some vehicle and cast on it 84224 etc.

**Branch(es):**

CHANGEME  master

**TC rev. hash/commit:** 

d435d5d5ba7040a0de16d5b97202b2e61fd03344

**Operating system:** 
centos

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/18089

**Comment by jackpoz** [comment]
> 1. use some vehicle and cast on it 84224 etc.

could you please be more detailed with clear how to reproduce steps, writing the exact gm commands required ? thanks

**Comment by gonzo1247** [comment]
if you have a vehicle with 2 seats, you enter the vehicle on seat 1 with Ride Vehicle Hardcoded or other ride spell on seat 1.
Targeting the Vehicle and use .cast 84224 or write a Script that let you cast the spell after a speficit time or why you will it. 
If beginn to change the vehicle seat and in this moment the vehicle will despawn. If you look after this on the vehicle log file, you can see that the logs says, player exit vehicle and he has no chance to re-enter on the next seat. Befor he can re-enter the server despawn the vehicle.

**Comment by Faq** [comment]
atleast on 335 24018b7a74ec8e68e43895e0e57f6397f59ea890 this issue not occurs with veh .npc add 33109 and changing seats (without spell just control buttons)

**Comment by gonzo1247** [comment]
is on master
