### ISSUE TITLE
World crashing randomly, crashlogs

### ISSUE THREAD

**Issue by jaxidor** [TrinityCore/TrinityCore#24734]
**Description:**

https://gist.github.com/jaxidor/7a99d5fcdc2163de090fde5847200051

**Expected behaviour:**

Worldserver should not crash

**Steps to reproduce the problem:**

Have not found a way to reproduce, happens very random, possibly due to some corrupted db account trying to login

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 48c5c0d7a242+ 2020-05-31 15:52:28 +0200 (3.3.5 branch)

**Operating system:** Windows

**Comment by Shauren** [comment]
Fixed in 0e9eb8e7f5eac85531ce25d214cf6018bef4114b

**Comment by jaxidor** [comment]
Holy fuck, thank you so much!
