### ISSUE TITLE
[PRIEST] Penance

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#24749]
**Description:**

Penance can not be interrupted by pressing escape or using /stopcasting macro. It can only be cancelled by moving.

**Expected behaviour:**

You should be able to cancel Penance by either pressing escape or /stopcasting macro.

**Steps to reproduce the problem:**

Make a priest
Spec into Penance (last talent of disc)
Cast and try to interrupt it without moving.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8ad0ab362ee3

**Operating system:** 

Win10 64

**Comment by lingxDEV** [comment]
Any idea if this is a dbc or core problem?

**Comment by lingxDEV** [comment]
Found out that this bug goes for all Channeled spells.

**Comment by Shauren** [comment]
This is not a bug, lua function `SpellStopCasting()` does not cancel channels in 3.3.5 client (it does in 4.3.4)
