### ISSUE TITLE
worldserver stops working - call stack

### ISSUE THREAD

**Issue by jaxidor** [TrinityCore/TrinityCore#24741]
**Description:**

https://i.imgur.com/jRLSCuE.png
No crashlog, i was able to catch the error by attaching visual studio to the worldserver.

**Expected behaviour:**

worldserver stops working

**Steps to reproduce the problem:**

unknown currently

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0e9eb8e7f5ea+ 2020-06-01 23:43:38 +0200 (3.3.5 branch)

**Operating system:** Windows 10

**Comment by jackpoz** [comment]
Do you have MaxCoreStuckTime setting enabled ? It should create a crashlog if worldserver enters an infinite loop

https://github.com/TrinityCore/TrinityCore/blob/90e00c3e2ab4f8f631dbc9d1a31fa9d315a476bd/src/server/worldserver/worldserver.conf.dist#L450-L456

**Comment by jaxidor** [comment]
Yes i have MaxCoreStuckTime = 60

pretty sure this crash is related: https://i.imgur.com/YUmHMxy.png
breakpoint: https://i.imgur.com/IYMFvyD.png

**Comment by jackpoz** [comment]
if you have MaxCoreStuckTime set to 60 then wait 60 seconds and let worldserver create the crashlog

**Comment by jaxidor** [comment]
Gonna try it out, here is some deeper debugging, ive searched for the spawnId 30158 in spawn_goup but nothing also checked for the NPC id and nothing https://i.imgur.com/J3OYLrF.png

**Comment by jaxidor** [comment]
Server is crashing randomly at least 5-8 times a day due to this respawn issue.
had the MaxCoreStuckTime set to 60 waited few minutes and did not get any crash log

**Comment by Jinnaix** [comment]
> Gonna try it out, here is some deeper debugging, ive searched for the spawnId 30158 in spawn_goup but nothing also checked for the NPC id and nothing https://i.imgur.com/J3OYLrF.png
> Possibly summon related?

Your collected data points at this gameobject:
https://db.project-nemesis.org/?object=179491

**Comment by CraftedRO** [comment]
I guess this can be closed since there's not a crashlog.
