### ISSUE TITLE
DB: Add Comment column to creature_summon_groups table

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24745]
Without Group in the Comment
https://gist.github.com/offl/5868232a722336f935647426e8c391af
Or with
https://gist.github.com/offl/f167b73544c990f2d93bd7938ab312a6

**Branch:** 3.3.5
**TC rev. hash/commit:** 12679fdd080e
**Operating system:** Windows 8.1

**Comment by Shauren** [comment]
creature_summon_groups are all created by us, nothing about that is sniffed, theres no reason to add VerifiedBuild column

**Comment by offl** [comment]
You probably mean they're not parsed directly into this table and are created manually with guessed or sniffed positions
Currently mostly values are from sniffs and you can fill VerifiedBuild if you want so people can know they're sniffed or leave it as 0 if you want
I understand that it's not traditional usage of VerifiedBuild but it can help people to track guessed data
Should I remove it?

**Comment by Warpten** [comment]
What shauren is saying is that we control the grouping ourselves. Nothing about that comes from sniff. It's just convenience for things like trash before/after a boss

**Comment by offl** [comment]
Yes I know there is no SQL for this table in parser, but positions we use mostly comes from sniffs

**Comment by offl** [comment]
VerifiedBuild removed
The comments with groups looks more informative, I guess

**Comment by illfated** [comment]
Just to recap; your suggested solution is https://gist.github.com/offl/f167b73544c990f2d93bd7938ab312a6#file-csg1-sql
