### ISSUE TITLE
Shadowstep on edges

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#24743]
**Description:**

When using Shadowstep on a target that is standing back to an edge, you will appear on the ground.

**Expected behaviour:**

When using Shadowstep on a target close to an edge, you should appear on the same level as them.

**Steps to reproduce the problem:**

Cast Shadowstep on a target with their back against an edge.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8ad0ab362ee3+

**Operating system:** 

Win10 64

**Comment by lingxDEV** [comment]
![shadowstep-1](https://user-images.githubusercontent.com/62337627/83623623-da53fe00-a591-11ea-8cce-cac88f91d1a2.png)

**Current behaviour:** 
![shadowstep-2](https://user-images.githubusercontent.com/62337627/83623637-de801b80-a591-11ea-8ec8-c8edd98bd259.png)

**Expected behaviour:**
![shadowstep-3](https://user-images.githubusercontent.com/62337627/83623816-171ff500-a592-11ea-9c77-c58583c60bd9.png)

**Comment by jackpoz** [comment]
it helps when talking about issues that happen in specific places to include .go xyz commands that actually include those places

**Comment by jackpoz** [comment]
Cannot reproduce the issue on eebb9620
![image](https://user-images.githubusercontent.com/1153754/94196441-a429e980-feb4-11ea-97c4-c7dfba889df5.png)

![image](https://user-images.githubusercontent.com/1153754/94196489-b73cb980-feb4-11ea-83a2-8838343485b3.png)

**Comment by lingxDEV** [comment]
You're not in the same location. 

You're in the open world Blade Edge arena. I was in the instanced arena Blade Edge.

To reproduce you will have to queue up for an arena.

**Comment by lingxDEV** [comment]
@jackpoz

**Comment by jackpoz** [comment]
did you try it on https://github.com/TrinityCore/TrinityCore/commit/eebb962030f91f44156a3303c95c012819e409ee or a more recent commit ?

**Comment by lingxDEV** [comment]
Is it required to rebuild mmaps vmaps etc? @jackpoz

**Comment by jackpoz** [comment]
Depends on how old your mmaps are

**Comment by lingxDEV** [comment]
They're from august 1st @jackpoz

**Comment by Faq** [comment]
update your core and write exact reproduction steps, like go. xyz mapid

**Comment by jackpoz** [comment]
![image](https://user-images.githubusercontent.com/1153754/95508079-bb87cd00-09b2-11eb-9684-6c68e3cdeb0c.png)

![image](https://user-images.githubusercontent.com/1153754/95508135-cfcbca00-09b2-11eb-95a0-82ad2d1a19c2.png)

**Comment by jackpoz** [comment]
just wasted 2 hours to try reproduce a bug that was fixed months ago

**Comment by illfated** [comment]
At least you confirmed that it was fixed, effort appreciated. Thank you.
