### ISSUE TITLE
mmap / vmap problem

### ISSUE THREAD

**Issue by firelook** [TrinityCore/TrinityCore#24742]
version :
TrinityCore rev. 8a5321c2fc8d+ 2020-06-01 03:47:45 +0200 (master branch) (Win64, Release, Static) 
Using SSL version: OpenSSL 1.1.0h  27 Mar 2018 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0

extracted latest mmaps/vmaps through the tool
OS: Windows 10

error : 
`Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-47675-00000006AE Entry: 47675
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
Could not load VMAP name:Kalimdor, id:1, x:20, y:32 (vmap rep.: x:20, y:32)
MMAP:loadMap: Could not load 17302032.mmtile into navmesh
MMAP:loadMap: Could not load 21702032.mmtile into navmesh
Could not load MMAP name:Kalimdor, id:1, x:20, y:32 (mmap rep.: x:20, y:32)
Could not load VMAP name:Kalimdor, id:1, x:20, y:33 (vmap rep.: x:20, y:33)
MMAP:loadMap: Could not load 15992033.mmtile into navmesh
MMAP:loadMap: Could not load 17302033.mmtile into navmesh
MMAP:loadMap: Could not load 21702033.mmtile into navmesh
Could not load MMAP name:Kalimdor, id:1, x:20, y:33 (mmap rep.: x:20, y:33)
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48215-0000000F37 Entry: 48215
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48581-0000000F38 Entry: 48581
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48587-0000000F39 Entry: 48587
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-10016-0000000A08 Entry: 10016
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-8958-00000007C1 Entry: 8958
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
Could not load VMAP name:Kalimdor, id:1, x:20, y:34 (vmap rep.: x:20, y:34)
MMAP:loadMap: Could not load 15992034.mmtile into navmesh
MMAP:loadMap: Could not load 17302034.mmtile into navmesh
MMAP:loadMap: Could not load 21702034.mmtile into navmesh
Could not load MMAP name:Kalimdor, id:1, x:20, y:34 (mmap rep.: x:20, y:34)
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48454-0000000FA8 Entry: 48454
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48454-0000000FC0 Entry: 48454
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48454-0000000FC1 Entry: 48454
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48454-0000000FCD Entry: 48454
Could not load VMAP name:Kalimdor, id:1, x:19, y:32 (vmap rep.: x:19, y:32)
MMAP:loadMap: Could not load 15991932.mmtile into navmesh
MMAP:loadMap: Could not load 17301932.mmtile into navmesh
MMAP:loadMap: Could not load 21701932.mmtile into navmesh
Could not load MMAP name:Kalimdor, id:1, x:19, y:32 (mmap rep.: x:19, y:32)
Could not load VMAP name:Kalimdor, id:1, x:19, y:33 (vmap rep.: x:19, y:33)
MMAP:loadMap: Could not load 15991933.mmtile into navmesh
MMAP:loadMap: Could not load 17301933.mmtile into navmesh
MMAP:loadMap: Could not load 21701933.mmtile into navmesh
Could not load MMAP name:Kalimdor, id:1, x:19, y:33 (mmap rep.: x:19, y:33)
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33022-0000001094 Entry: 33022
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33980-00000010A0 Entry: 33980
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33021-00000010A3 Entry: 33021
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33022-00000010A5 Entry: 33022
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33021-00000010A8 Entry: 33021
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33021-00000010B2 Entry: 33021
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33022-00000010B6 Entry: 33022
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33022-00000010B7 Entry: 33022
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-33021-00000010C3 Entry: 33021
Received not handled opcode [CMSG_REQUEST_QUEST_LINES_FOR_MAP 0x3397 (13207)] from [Player: Lily Player-3-0000001B, Account: 25]
Could not load VMAP name:Kalimdor, id:1, x:21, y:32 (vmap rep.: x:21, y:32)
Could not load MMAP name:Kalimdor, id:1, x:21, y:32 (mmap rep.: x:21, y:32)
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-7093-00000010CA Entry: 7093
Could not load VMAP name:Kalimdor, id:1, x:21, y:34 (vmap rep.: x:21, y:34)
Could not load MMAP name:Kalimdor, id:1, x:21, y:34 (mmap rep.: x:21, y:34)
Could not load VMAP name:Kalimdor, id:1, x:19, y:34 (vmap rep.: x:19, y:34)
Could not load MMAP name:Kalimdor, id:1, x:19, y:34 (mmap rep.: x:19, y:34)
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48228-0000001186 Entry: 48228
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48457-0000000F25 Entry: 48457
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-3-1-0-48581-0000000F38 Entry: 48581
Could not load VMAP name:Kalimdor, id:1, x:23, y:32 (vmap rep.: x:23, y:32)
Could not load MMAP name:Kalimdor, id:1, x:23, y:32 (mmap rep.: x:23, y:32)`

**Comment by MaxtorCoder** [comment]
Please post the error log on Pastebin so we can understand and read it.

**Comment by MaxtorCoder** [comment]
Oh and also follow the issue template.

**Comment by Aokromes** [comment]
he is using custom core.

**Comment by jackpoz** [comment]
@firelook do you have any custom changes ? could you push to github your changes and paste a link to that here ?

**Comment by firelook** [comment]
with pleasure : 
pastebin => 
https://pastebin.com/1PCv8BQD

I did add some script from ashamane in the directory 
"Trinity\src\server\scripts\Custom"
but should not interfer.

if you think it is better for debugging I cvan do a rollback and start from scratch and re propose a dump log
as you wish

**Comment by Aokromes** [comment]
this issue is still valid? on linked issue i see a reference closing it.
