### ISSUE TITLE
Core/Creature: Possibility to use formations for creature entry is missing

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24764]
We need another table `creature_formations` but for creature entries. Kinda  `creature_formations_template`.
This is needed to make groups of summoned creatures, to make them aggro together.
Also can be used to more easily make groups of static spawns. For example right now if a boss should aggro with 100 trash NPCs, you have to make formation for each creature guid.

Basically we need analogue of https://github.com/cmangos/issues/wiki/creature_linking_template with columns `map` and `search_range`. At this moment we don't need `dist`, `angle`, `point_1`, `point_2`. Just `leaderEntry`, `memberEntry`, `groupAI`,  `map` and `search_range`.

**TC rev. hash/commit:** d81a9e5bc3b3

**Comment by dr-j** [comment]
well think ive said before some creatures should have multiple formations and change formation via script examples are script for dimensius (still awaiting commit) where during saheeds escort and engaging dimensius formation of the npcs which help changes at least 3 times

Other examples are probably bodyguard for hire/gizzleton caravan where order of formation should change depending on direction they are travelling in or depending on which quest is currently active (by direction) as to which takes the lead atm there is no formations there both npcs and both kodos have individual waypoints rather than using formation which results in that all of those can get seperated from each other

**Comment by offl** [comment]
Let's wait first for creature_formations_template and its basic functionaliy without anything related to dist and angle. Because it will be easier for devs.

The things you mentioned probably requires some sort of dynamic formations and right now related only to the creature_formations table. Maybe one day I will open an issue about it. But right now I feel like I forgot everything related to this thing.

**Comment by Ovahlord** [comment]
Any example of where you would actually need this without hacking the shit out of a script?

**Comment by Jinnaix** [comment]
I might be wrong here but i remember that in several Dungeons/Raids if you sneak past the packs to a boss and attack him, the area that belongs to the boss gets pulled at once. Or skipping a boss and attacking the final boss leads to the skipped boss getting aggroed.

Problem with this and Trinitycore is - we can only put a creature into one formation. So trash linking and a pull mechanic for attacking the boss is currently not possible. See attumen in karazhan vor example - Every creature on his way is linked to him. Meanwhile, you cant pack them together with creature formations.

Side note - creature formation AI is still broken:
https://github.com/TrinityCore/TrinityCore/issues/17563#issuecomment-615197753

**Comment by Aokromes** [comment]
> I might be wrong here but i remember that in several Dungeons/Raids if you sneak past the packs to a boss and attack him, the area that belongs to the boss gets pulled at once. Or skipping a boss and attacking the final boss leads to the skipped boss getting aggroed.

idk if all the previous ones, but at least all the room on the 2nd boss of shadow labyrinth is pulled when you attack boss.

**Comment by offl** [comment]
> Any example of where you would actually need this without hacking the shit out of a script?

CPP:  Any scripts with bosses which summons adds before fight. I'm not familiar with WotLK expansion and I can only remember Karazhan's Moroes and Zulaman's Hex Lord Malacrass.

SAI: Good question. The thing is nobody ever tried to implement it via SAI or EAI. Simply because it was impossible and is almost impossible today or requires "hacking the shit out of a script". But recently I encountered this problem while scripting https://github.com/TrinityCore/TrinityCore/issues/24735#issuecomment-637563675

**Comment by Jinnaix** [comment]
Using call for help via sai for creature linking is messy at best, I've worked quite a lot with it before I found out about creature formations.
If you are lucky enough to have the correct factions in all the packs, there is still the risk of unintended chain pulling way more creatures than  you want to due to the range you need to set for the call.

**Comment by offl** [comment]
I'd like to note that this is not only about the possibility to make creature aggro together.
In future we can port all these flags https://github.com/cmangos/issues/wiki/creature_linking_template
And it will allow us to despawn or respawn summoned creatures by more easy way

**Comment by Rothend** [comment]
Wouldn't it make more sense to separate aggro behavior from movement behavior? That way you can specify whole groups that aggro together, but add different paths with different leaders.

**Comment by offl** [comment]
> Let's wait first for creature_formations_template and its basic functionaliy without anything related to dist and angle. Because it will be easier for devs.

We don't need it right now. It's related to current formation implementation which is simply incorrect. And if we will understand how formations really works, we can update creature_formations_template too.

Where exactly we can load angle and dist? In creature_summons_groups? What about static spawns?

Blizzard's angles are dynamic, if you kill one member, the whole formation will be reloaded with new angles. Do they always do that? Where we can store default angle and dist then?
Is the dist dynamic or not?

How exactly they load new angles for escort NPCs and other?
Where we can store new angles and dist? Can we just use the SAI or CPP actions for that every time we need it?

These are not all questions I have.

**Comment by offl** [comment]
I created this because wanted to provide same support for temporary summoned creatures. Since now I know they are all stored in DB, better to focus on something else.
