### ISSUE TITLE
Core/SAI: SMART_EVENT_WAYPOINT_START is broken

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24760]
**Description:**

It ignores waypoint id (for example point id 2) you set in event param and executes actions you add only when creature starts path (point id 1).

**Expected behaviour:**

It must work for waypoint id you set and not only on path start.

**Steps to reproduce the problem:**

apply the sql
.go x -0.310414 0.107129 -144.708 13
.npc add temp 128
notice the npc says quote when path starts and not when waypoint id 2 is started
```sql
UPDATE `creature_template` SET `AIName` = "SmartAI" WHERE `entry` = 128;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 128 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(128,0,0,0,11,0,100,0,0,0,0,0,0,2,35,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Respawn - Set Faction 35"),
(128,0,1,0,11,0,100,0,0,0,0,0,0,53,0,128,0,0,0,2,1,0,0,0,0,0,0,0,0,"On Respawn - Start Waypoint"),
(128,0,3,0,39,0,100,0,2,0,0,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Waypoint 2 Started - Say Line 2");

DELETE FROM `waypoints` WHERE `entry` = 128;
INSERT INTO `waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`point_comment`) VALUES
(128,1,12.137487,-5.048933,-144.707993,""),
(128,2,9.095778,-17.941479,-144.707993,""),
(128,3,-5.067418,-24.336437,-144.707993,"");

DELETE FROM `creature_text` WHERE `CreatureID` = 128 AND `GroupID` IN (2);
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`Comment`) VALUES
(128,2,0,"Waypoint started",12,0,100,4,0,0,0,0,"");
```
TrinityCore rev. d81a9e5bc3b3 2020-06-03 22:05:08 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.72.0
Using MySQL version: 50730
Using CMake version: 3.17.2
Compiled on: Windows 6.3.9600
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1997851292 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20051

**Comment by dr-j** [comment]
Well on the core I use even though custom has opposite to this waypoint start event works fine but waypoint end does not work and was getting spawn spam and FPS issues due to npcs not respawning had to change lots of events which specified waypoint for event 58 to 40 because of this as for me if waypoint specified for event 58 will never trigger but have no issues with event 39

**Comment by offl** [comment]
Anyone else can confirm this event does work?

**Comment by Rushor** [comment]
can confirm he is saying it directly and not at point 2 https://i.imgur.com/sqQEw61.png

**Comment by Rushor** [comment]
if you do this:

```sql
UPDATE `creature_template` SET `AIName` = "SmartAI" WHERE `entry` = 128;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 128 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(128,0,0,0,11,0,100,0,0,0,0,0,0,2,35,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Respawn - Set Faction 35"),
(128,0,1,0,11,0,100,0,0,0,0,0,0,53,0,128,0,0,0,2,1,0,0,0,0,0,0,0,0,"On Respawn - Start Waypoint"),
(128,0,3,0,39,0,100,0,2,128,0,0,0,1,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Waypoint 2 Started - Say Line 2");
```

he is not saying it at all

**Comment by offl** [comment]
Thanks
Yes with such small changes it sometimes stops working at all

**Comment by jackpoz** [comment]
https://imgur.com/sj7zOjt
