### ISSUE TITLE
[3.3.5] [Spell] Mirror Image Server Crash (2 enemies+)

### ISSUE THREAD

**Issue by dandi2001** [TrinityCore/TrinityCore#24782]
**Description:**

The server is crashing when I use Mirror Image and am being attacked by more than 1 creature. Crashlog: https://gist.github.com/dandi2001/b1c7281229f23af641dd92966310cac0

**Expected behaviour:**
The server should not crash, it should function properly.

Tell us what should happen instead.
Expected behavior

**Steps to reproduce the problem:**

1. Go to an area with 2 enemies or more (I went to Orgrimmar as an Alliance and got attacked by 2 guards)
2. Use Mirror Image
3. Server crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
I might be using an older core, but I've looked everywhere for a commit that affected this issue and found nothing
https://github.com/TrinityCore/TrinityCore/tree/2a41755b589f215c14c85b1015e71534c1e91a98

https://i.imgur.com/OVCvyOa.jpg

**Operating system:**
Windows 10

**Comment by Aokromes** [comment]
you are using to old unsuported core, update.

**Comment by jackpoz** [comment]
could you try reproducing the issue at https://tcubuntu.northeurope.cloudapp.azure.com/ ? that uses a more recent version.
or setup locally another realm using latest version and post a crashlog from that

**Comment by dandi2001** [comment]
> could you try reproducing the issue at https://tcubuntu.northeurope.cloudapp.azure.com/ ? that uses a more recent version.
> or setup locally another realm using latest version and post a crashlog from that

I'll setup another clean realm with the newest core, I'll update.

**Comment by jackpoz** [comment]
build in debug while at it so the crashlog can get more information

**Comment by dandi2001** [comment]
Will do

**Comment by Aokromes** [comment]
https://i.imgur.com/aOchNLi.jpg

**Comment by jackpoz** [comment]
some info:
- spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30023
- position .go xyz 2849.829102 2280.712891 203.115173 1
  -  do you have something custom there ? it's empty for me

**Comment by dandi2001** [comment]
Cannot reproduce on the newest core. Not sure what's the possible fix from the commit gap between March 19 to today though. Would it be possible to get assistance in that regard?

**Comment by Aokromes** [comment]
no, we only support updated cores.

**Comment by illfated** [comment]
> * position .go xyz 2849.829102 2280.712891 203.115173 1
>   
>   * do you have something custom there ? it's empty for me

Stonetalon Mountains... looks like the Z coordinate is wrong, because the nearest place to find hostile mobs is down underground in the Stonetalon Den.
Above ground, there is only unused area like the ones Blizzard developers left unused, never to be populated in live retail servers.
