### ISSUE TITLE
Core/SAI: SMART_EVENT_OOC_LOS & SMART_EVENT_IC_LOS NoHostile param

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24789]
If creature is hostile to Alliance, then:
With param 0 it will NOT work for the Horde but will work for the Alliance
With param 1 it will work for the Horde but NOT for the Alliance
So we can't support LoS events for both factions in ONE event
Sometimes we need to support both cases in ONE event

For tests execute
```sql
-- To make event trigger always, currently the chance is lower
UPDATE `smart_scripts` SET `chance` = 100 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```

Currently the event works only for Horde players
Just in case if you want to set it back
```sql
UPDATE `smart_scripts` SET `event_param1` = 1 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```
This will make the event work only for Alliance players
```sql
UPDATE `smart_scripts` SET `event_param1` = 0 WHERE `entryorguid` = 18428 AND `source_type` = 0 AND `id` = 0;
```
.go c id 18428
(there's more creatures in the area)

Maybe we can just add param = 2 to support both hostile and non-hostile cases

**Branch:** both
**TC rev. hash/commit:** d81a9e5bc3b3

**Comment by jackpoz** [comment]
> Maybe we can just add param = 2 to support both hostile and non-hostile cases

sounds like a good idea
