### ISSUE TITLE
Multiple client crashes

### ISSUE THREAD

**Issue by ImmortalusDev** [TrinityCore/TrinityCore#24785]
I'm getting multiple client crashes when i use Heroic Leap - 6544
This issue isn't caused by only this spell.

Tested on new/clean client.

**Expected behaviour:**
No client crash.

**Steps to reproduce the problem:**

1. Try to use heroic leap 6544
2. Client crashed with different ProcessIDs and ThreadIDs

**Branch(es):**
master

[https://imgur.com/z62yzbX](url)

**TC rev. hash/commit:** 

TrinityCore rev. 8a5321c2fc8d

**Operating system:** 
Win 10 x64

**Comment by ImmortalusDev** [comment]
GetMotionMaster causing client crash. Tested multiple times.
I didn't change anything in code related to it.

**Comment by funjoker** [comment]
Patience please

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25722#issuecomment-744428994
