### ISSUE TITLE
DB/spell_target_position: Update xyz position for Karazhan portal destination.

### ISSUE THREAD

**Issue by ipriver** [TrinityCore/TrinityCore#24797]
**Description:**

There are no errors when you are trying to use the portal if you are solo or in a group and it doesn't teleport you anywhere, so it looks at first like a portal issue. 
The thing is that it tries to teleport you inside the Karazhan raid and you have to be in a raid group to be able to enter. And that's why the portal doesn't work, except when you are in a gm mode or in a raid group.

**Expected behaviour:**

After using the portal a player should be teleported in front of the Karazhan entrance.
[How it works in classic](https://youtu.be/oiOY8MeUcrs?t=735)

**Steps to reproduce the problem:**

1. Get [Atiesh](https://classic.wowhead.com/item=22589/atiesh-greatstaff-of-the-guardian)
2. Right-click on the staff to summon a portal
3. Try using the portal

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f2f4fc921ee8

**Operating system:** Ubunutu 20.4, MariaDB 10.3.22

**Suggested Fix:**
```sql
-- spell 28147, values copied from classic dbs
UPDATE spell_target_position 
SET    mapid = 0, 
       positionx = -11123.3, 
       positiony = -2014.44, 
       positionz = 47.0927, 
       orientation = 0.675977 
WHERE  id = 28147; 
```
Updates position for [Portal Effect: Karazhan](https://classic.wowhead.com/spell=28147/portal-effect-karazhan)

**Tested Query:** Yes

**Comment by Aokromes** [comment]
are you sure it's the same on 3.3.5a than on classic?

**Comment by ipriver** [comment]
@Aokromes according to [wowiki]( https://wowwiki.fandom.com/wiki/Atiesh,_Greatstaff_of_the_Guardian):
``` 
The staff provided the ability to open a portal to Medivh's tower of Karazhan;
...
The portal leads to the front door of Karazhan.
```
and comments from [wowhead ](https://classic.wowhead.com/item=22589/atiesh-greatstaff-of-the-guardian#comments:id=11610) like:
```
2006/12/09 (Patch 2.0.1)
The "Use" effect will create a portal to Karahzan, it won't teleport you inside the instance.
```
Though the Atiesh chain became unavailable in WotLK expansion, I think the portal after TBC migration should be working the same way it worked before. I would assume there might be changes only since Legion Kara.
Sadly it's hard to find any evidence of how it really worked in 3.3.5a.

**Comment by Rushor** [comment]
tbc is confirmed yes:

Subject: "Atiesh, Greatstaff of the Guardian - Abilities"The staff will port you OUTSIDE Karazhan, and eaven if you wanted get this staff, Karazhan attunement would be easyer. 

https://classic.wowhead.com/item=22589/atiesh-greatstaff-of-the-guardian#comments:id=2663983

**Comment by Rushor** [comment]
wowwiki

during wotlk ear: https://wowwiki.fandom.com/index.php?title=Atiesh%2C_Greatstaff_of_the_Guardian&diff=2082362&oldid=2081770

Revision as of 09:07, October 19, 2009 till Revision as of 06:51, October 20, 2009 (view source)

text was:

The staff provides the ability to open a portal to Medivh's tower of Karazhan; however, at the time of Atiesh's release into World of Warcraft, Karazhan had yet to be implemented. It was opened upon the release of Burning Crusade. The portal leads to the front door of Karazhan. 


so the fix is valid
