### ISSUE TITLE
Vmap manager errors.

### ISSUE THREAD

**Issue by leviathonbeast** [TrinityCore/TrinityCore#24798]
**Description:**

Ive Noticed that when starting worldserver it spams ( this is just an extract there are hundreds of these lines ) 

StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0002Ffda.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0002Ffda.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File00030457.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0003113A.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File00030457.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0003044F.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0003044F.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File0003044F.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File00030465.xxx.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [21, 26]
VMapManager2: could not load '../data/vmaps/File00030457.xxx.vmo'

I have noticed that the Files are there but the file names use different cases, not sure if the server on load is case sensitive on certain Operating Environments?

1643_32_28.vmtile  FILE00030AF9.xxx.vmo  File000Eb21D.xxx.vmo  FILE0030BF88.xxx.vmo
1643_32_29.vmtile  FILE00030AFA.xxx.vmo  File000Eb220.xxx.vmo  FILE0030F87F.xxx.vmo
1643_32_30.vmtile  FILE00030AFB.xxx.vmo  FILE000EB223.xxx.vmo  FILE0031B602.xxx.vmo
1643_32_31.vmtile  FILE00030B0C.xxx.vmo  FILE000EB231.xxx.vmo  FILE00320B82.xxx.vmo
1643_32_32.vmtile  FILE00030B0E.xxx.vmo  FILE000EB258.xxx.vmo  GameObjectModels.dtree

see the filename differences, they are using upper case. where the server output reports mixed upper and lower.

**Expected behaviour:**

To be able to load the files listed.

**Steps to reproduce the problem:**

Not sure it is the same anywhere else untested. 

**Branch(es):**

Master

**TC rev. hash/commit:** 

TC>server debug
TC>TrinityCore rev. 2493d88a7224+ 2020-06-12 11:07:11 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Using MySQL version: 10.3.22-MariaDB
Using CMake version: 3.13.4
Compiled on: Linux 4.19.0-9-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 1166286057 bytes
vmaps directory located in ../data/vmaps. Total size: 5932357783 bytes
mmaps directory located in ../data/mmaps. Total size: 8288944916 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 820.19071
TC> 

**Operating system:** 

Linux version 4.19.0-9-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.118-2 (2020-04-29)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24742

**Comment by leviathonbeast** [comment]
Why was this closed i dont think the two issues are related.

**Comment by illfated** [comment]
@leviathonbeast : If you can point out what makes this issue ticket different from #24742 , I am sure it will be OK to reopen it.
