### ISSUE TITLE
Can't loot more than one creature (mob) per combat 

### ISSUE THREAD

**Issue by mcsescott** [TrinityCore/TrinityCore#24806]
**Description:**
Can only loot one creature per combat state.

**Current behavior:**
If you kill more than one creature and get multiple glowing crystal auras (loot indication),
you can only loot one.  The other auras will disappear after looting the first one, and thus you miss loot/quest items/etc.

**Expected behavior:**  
Would hope to be able to loot more than one mob/creature.

**Steps to reproduce the problem:**  
Start combat with one creature.
Start combat with another (or multiple) creatures before killing the first one, so that you are in combat with more than one creature.
Kill creature/mobs; get loot indication.
Loot any one of the creatures, and the aura goes away from the others, and thus you cannot loot the rest of the creatures.

----------

**Branch(es):** master

**TC rev. hash/commit:** 6533de3

**Operating System:** Windows 10

_TrinityCore rev. 6533de31005f 2020-06-13 00:30:32 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)_

**Comment by illfated** [comment]
Did you ever play World of Warcraft online on Blizzard retail servers, before and after the Cataclysm change?
I am fairly sure this is the famous "1 loot action to loot all killed NPCs" change added in patch 4.0.3a.

**Comment by mcsescott** [comment]
Ok, thank you for clarifying and reminding me of how ignorant I can be on little sleep.  You are correct.  It's been a long time since I was on retail.
