### ISSUE TITLE
Unable to stop cast all channeled spells

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#24811]
**Description:**

Channeled spells can not be interrupted by pressing escape or using /stopcasting macro. It can only be cancelled by moving.

**Expected behaviour:**

You should be able to cancel Channeled spells by either pressing escape or /stopcasting macro.

**Steps to reproduce the problem:**

Cast a channeled spell e.g Mind Flay, Penance
Try to interrupt it without moving.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8ad0ab362ee3

**Operating system:** 

Win10 64

**Comment by Aokromes** [comment]
edit https://github.com/TrinityCore/TrinityCore/issues/24749
