### ISSUE TITLE
[master] Hotfixes 34769 

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#24823]
**Description:**

VIA TRUNCATE:
https://gist.github.com/funjoker/7a09b50b33e49a06af88d767cc7bfd48

VIA UPDATE:
https://gist.github.com/funjoker/a3a5ad2a2486d030c5846619a9b9961e

**Branch(es):**

 master

**TC rev. hash/commit:** 

f387673aa328f3ff5941437149ba369d3c9a2806

**Comment by funjoker** [comment]
@Shauren i created an update file. donno if it is better this way tbh ^^

**Comment by illfated** [comment]
@funjoker : Did you press the [Close issue] button (instead of the comment button) by mistake?
The [Close issue] button is quite big and easy to press without thinking, I know.

**Comment by funjoker** [comment]
@illfated 01c8d03e2ec67d4d4660e7e229274e86ba41420e forgot that i have push permissions xD
