### ISSUE TITLE
Core/SAI: SMART_EVENT_SUMMON_DIES is not implemented

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24831]
SMART_EVENT_SUMMON_DESPAWNED triggers only after creature despawn. Pretty useless. In most cases we should use SMART_EVENT_SUMMON_DIES because not all creatures should despawn instantly after death.

**Branch:** both
**TC rev. hash/commit:** d81a9e5bc3b3

**Comment by dr-j** [comment]
I think how this has been handled before Is using on death event and making summon set data on owner or summoner to notify summoner when summon has died

**Comment by offl** [comment]
Yes but we need a simple solution here.

P.S. maybe we can really remove https://github.com/TrinityCore/TrinityCore/commit/8fef9aaf75c05190a59e8b3c8d7799f883970e2e  and use id for this new type?
Anyone know where we can use SMART_EVENT_IS_BEHIND_TARGET now?

**Comment by Killyana** [comment]
It could be useful is some rare cases, better keep it an create the new event with a new ID.
