### ISSUE TITLE
[3.3.5] Possible out-of-order Packets on Login?

### ISSUE THREAD

**Issue by HelloKitty** [TrinityCore/TrinityCore#24846]
**Description:**

TrinityCore 3.3.5 may be sending packets potentially out of order on login. However, since I do not have retail 3.3.5 packet logs I cannot personally verify this.

For example, when logging in Player::LoadFromDB will eventually call Player::SetDrunkValue which invokes UpdateObjectVisibility. This is before the player is even in the map, but it will trigger an update packet from SendToSelf. Packets such as SMSG_POWER_UPDATE are also triggered from LoadFromDB. I think these may have been in Player::SendInitialPacketsBeforeAddToMap before.

I'm also pretty sure I'm getting Object Create blocks for many units before SMSG_LOGIN_VERIFY_WORLD too. Does anyone have retail packet logs to confirm if this behavior is correct?

**Expected behaviour:**

Unknown but I suspect that TrinityCore should not be sending SMSG_COMPRESSED_UPDATE_OBJECT before SMSG_LOGIN_VERIFY_WORLD.

**Steps to reproduce the problem:**

1. Login.

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 0e9eb8e7f5eac85531ce25d214cf6018bef4114b

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Windows

**Comment by Rothend** [comment]
Another issue related to wrong packet order at login is that often, when you create a new character and log it in, you see a flash of your character in the flashing area before the opening cinematic starts. Sometimes you also see a flash of the position the flyby camera NPC is at, with some visual glitches.

**Comment by Killyana** [comment]
@Rothend it could be the cause of https://github.com/TrinityCore/TrinityCore/issues/22821

**Comment by HelloKitty** [comment]
Tonight I confirmed that this issue can cause GameObjects to render incorrectly on the client

https://user-images.githubusercontent.com/5829095/163331325-17786889-d137-4391-ba5c-190368a548f5.mp4


I will PR a hack fix which can address this. Understandable if it gets rejected since there is truly a systemic issue of sending out of order packets on login/worldport. But as far as I can tell it fixes this bug.

**Comment by HelloKitty** [comment]
Another example of the bug this causes:
![af12a39067285dbcc34aa7c891581317](https://user-images.githubusercontent.com/5829095/163337432-334839ce-b3ec-4846-b35b-72ea461946b1.png)

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
