### ISSUE TITLE
World server can't start 

### ISSUE THREAD

**Issue by wplatform** [TrinityCore/TrinityCore#24844]
**Description:**

Applied 2 queries. Containing 0 new and 104 archived updates.
Updating World database...
>> Applying update "2017_05_03_00_world_transmog.sql" '2767FDA'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 2: Unknown column 'text0_0' in 'field list'

Applying of file '/opt/TrinityCore/sql/custom/world/2017_05_03_00_world_transmog.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 22a3cb4432ae 2020-06-18 10:57:26 +0200 (maseter branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** CHANGEME OS

**Comment by Shauren** [comment]
`2017_05_03_00_world_transmog.sql`, thats your custom crap

**Comment by Aokromes** [comment]
p.s fact: master branch already have transmorg without the need of 3rd party patches.
