### ISSUE TITLE
Core/Spell: spells with the effect Apply Aura: Mod Healing Taken and negative bp must be displayed as debuff and not buff

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24854]
**Description:** For example: https://woehead.way-of-elendil.fr/?spell=32858
Probably must be fixed like https://github.com/TrinityCore/TrinityCore/commit/7d88891983d5c7d2673be760e11bff12df958d41

**Steps to reproduce the problem:**

1. find any hostile creature
2. .cast back 32858
3. the aura will be displayed as buff and can be removed by a right click

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. e6b06c4f039f

**Comment by Jildor** [comment]
No, if you fix there you do health funnel negative, and should be positive, here I say that: https://github.com/TrinityCore/TrinityCore/pull/24837#issuecomment-646020601 try to add in https://github.com/TrinityCore/TrinityCore/blob/075a3994444014e4264cdd7369c7207c0c2a09e6/src/server/game/Spells/SpellInfo.cpp#L3716 
But need check all auras with that effect to ensure

**Comment by Jildor** [comment]
Need check all auras with that effect and see if should be with targettype or bp negative or only one of these and set in proper check
