### ISSUE TITLE
Compiling latest source fails. (ElunaTrinityWotlk)

### ISSUE THREAD

**Issue by lordSeaworth** [TrinityCore/TrinityCore#24851]
**Description:**

Cloning the latest 3.3.5 branch won't build.

Fails with

`"fatal error: non-virtual member function marked 'override' hides virtual member function"`

**Expected behaviour:**

Should compile without issues.

**Steps to reproduce the problem:**

1. Clone the latest repository for 3.3.5
2. git submodule init + update
3. Cmake
4. make, make install

**Branch(es):**
3.3.5 (ElunaLua)

**Operating system:**

Archlinux + Ubuntu 19.10

Seems it appears to be the same issue on the official build.
(https://travis-ci.org/github/ElunaLuaEngine/ElunaTrinityWotlk/builds/700246017)

**notes**

This is for ElunaLua for 3.3.5 using https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
I posted this here since the README.md for ElunaTrinityWotlk redirects me for issues to here.

**Comment by Jinnaix** [comment]
This is a custom branch, not maintaned by trinitycore.

**Comment by jackpoz** [comment]
Post your issues at https://github.com/ElunaLuaEngine/Eluna/issues (ofc the readme points here beacuse it's a fork)
