### ISSUE TITLE
DB/SAI: move Ranger Lilatha's caged text from AreaTrigger to OOC timer

### ISSUE THREAD

**Issue by Rothend** [TrinityCore/TrinityCore#24861]
**Description:**

[Ranger Lilatha](https://www.wowhead.com/npc=16295)'s periodic text while she's caged isn't related to the AreaTrigger, but it's simply on a OOC timer. Verified on 8.3 PTR.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 05025d79f3cb34fa135cb820badeef32883f7eb4

```sql
DELETE FROM `areatrigger_scripts` WHERE `entry`=4071;
DELETE FROM `smart_scripts` WHERE `entryorguid`=4071 AND `source_type`=2;
DELETE FROM `smart_scripts` WHERE `entryorguid`=16295 AND `source_type`=0 AND `id`=8;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16295, 0, 8, 0, 1, 1, 100, 0, 20000, 40000, 60000, 180000, 0, 1, 6, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Ranger Lilatha - OOC - Say Line 6 (Phase 1)");


```

**Comment by offl** [comment]
I thought "I wasn't able to find more info about it because the AT is huge and the say range is small so player simply can't see the text in 90% of cases"

**Comment by Rothend** [comment]
I just left my character behind the cage for half an hour and she kept saying her text, that's also how I got the timing between texts. There were no other players nearby.

**Comment by offl** [comment]
I wonder what does the AT then

**Comment by dr-j** [comment]
its for quest investigate the Amani catacombs

**Comment by offl** [comment]
But what happens when player enters the AT?

**Comment by dr-j** [comment]
gives credit for investigating the Amani catacombs (quest 9193 has two objectives 

1) burn 10 mumys 
2) investigate the Amani catacombs

its dealt with by areatrigger involved relation

**Comment by dr-j** [comment]
and can confirm removing sai from that trigger fixes issues as I received ticket this morning about quest not working and this is cause

**Comment by offl** [comment]
Thanks, then it was really wrong to use it for another quest

**Comment by offl** [comment]
Yes, areatrigger_involvedrelation and SAI scripts can't work together
