### ISSUE TITLE
[3.3.5] Crash: PetAI::HandleReturnMovement

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24870]
**Description:**

https://www.wowhead.com/quest=12690/fuel-for-the-fire
https://www.wowhead.com/npc=28843/bloated-abomination#abilities
https://www.wowhead.com/item=39238/scepter-of-command
https://www.wowhead.com/spell=52497/flatulate

when you charm npc=28843 with item=39238 and use spell=52497, npc=28843 get dmg of his spell, if npc=28843 die with that damage, crash xD

Reproduced in https://tcubuntu.northeurope.cloudapp.azure.com/
crashlog: https://gist.github.com/jackpoz/82361fc5800ed589c61387f66a4d29c7

**Steps to reproduce the problem:**

1. .gm on
2. .go cre id 28843
3. .q add 12690
4. use item https://www.wowhead.com/item=39238/scepter-of-command in NPC for charm
5. .damage 9000 to charmed npc for low hp
6. use ability of npc https://www.wowhead.com/spell=52497/flatulate and wait until npc die by this spell

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/a9f9f737b2c93d8f9fcb435f7a2b164a84cbc684

**Comment by jackpoz** [comment]
same issue as https://github.com/TrinityCore/TrinityCore/commit/c3619f42a56fb6aaadc15ca63fe95fc0f519428d

**Comment by TheWinchesters** [comment]
I had the same with
`if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))`
