### ISSUE TITLE
[3.3.5] Mount Hyjal Bugs

### ISSUE THREAD

**Issue by Trystanosaurus** [TrinityCore/TrinityCore#24904]
**Description:**

In mount Hyjal there seem to be a few bugs.

The first is that all trash monsters should spawn in running. At the moment they're walking.

Archimonde's fire wall has a visible Doomfire Spirit (infernal model) running around ,this should be invisible.

In the final phase (less than 10% health) Archimonde's finger of death was doing damage, but the Protection of Elune buff the raid gets (which I did get) should prevent all damage.

**Expected behaviour:**

- [ ] Trash mobs should run.
- [ ] Doomfire Spirit should be invisible.
- [ ] Players should take no damage once Archimonde reaches 10% health so they can enjoy watching the wisps finish him off.

**Steps to reproduce the problem:**

1. Step 1 Run the Mount Hyjal instance and see the monsters walking, rather than running.
2. Step 2 At the end fight Archimonde (I'm afraid I don't know a good way to skip to the end), the Doomfire Spirits (creature template 18104) will be visible.
3. Step 3 Get Archimonde down to 10% and you will get Protection of Elune (https://www.wowhead.com/spell=38528/protection-of-elune) cast on you. He will start to spam Finger of death (https://www.wowhead.com/spell=39369/finger-of-death), which should do no damage thanks to the protection.

**Branch(es):**

3.3.5, (not tested on master)

**TC rev. hash/commit:** 

3ac1992afbeb

**Operating system:**

Windows 10

**Comment by leelf00** [comment]
- NPC Thrall (entry=17852) and NPC Lady Jaina Proudmoore(entry=17772) not cast spells in combat,they do melee attack.
- Horde Guards and Alliance Guards respawn in combat.
- Archimonde drain worldtree event broken.
