### ISSUE TITLE
Core/Creature: Possibility to summon creature with loaded path id is not implemented

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24918]
After long discussion with @Killyana we finally found where and how we can implement it. I will try to explain everything step by step.

1. We need `pathId` (not path entry) option in `SummonCreature` in order to summon creature with loaded unique path. It is needed to summon multiple creatures with the same entry but with different paths. Currently it's not possible in SAI and is hard to implement even in core scripts. For example [this is how it's implemented in Devourer of Souls outro event](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_devourer_of_souls.cpp#L211-L223). I'd like to note that it's not fully implemented, each summoned creature must have unique path with multiple waypoints. Currently only one waypoint is used in this case.

How `pathId` was implemented in CMaNGOS: https://github.com/cmangos/mangos-wotlk/commit/7142ba290b9cc506614c7d5758f25ff76f09975a

2. We need to link `waypoints`.`entry` to `creature_template`.`entry` like it's done for another tables like `creature_equip_template` where `CreatureID` = `creature_template`.`entry`. It will allow us to use `pathId` column from `waypoints` table when we will summon creature and not both `waypoints`.`entry` and `path`. Also with it it'll be possible to use it in core scripts.

It's the most hard part because currently we use different paths for one creature entry. For example:
```sql
SELECT * FROM waypoints WHERE entry BETWEEN 2524400 AND 2524411
```
And we will have to find and rewrite all creatures scripts which uses multiple different paths. 

3. We need to use `pathId` instead of  `waypoints`.`entry` in `action_param2` of `SMART_ACTION_WP_START`.
4. We need to use `pathId` instead of  `waypoints`.`entry` in  `event_param2` of `SMART_EVENT_WAYPOINT_PAUSED`, `SMART_EVENT_WAYPOINT_RESUMED`, `SMART_EVENT_WAYPOINT_STOPPED` and `SMART_EVENT_WAYPOINT_ENDED`.

We will have to update all scripts.

5. We need additional column named `pathId` in table `creature_summon_groups` to summon creatures with loaded pathId from this table too.

6. We need additional param in `SMART_ACTION_SUMMON_CREATURE` in `param5` named `pathId` to summon creatures with loaded path from SAI scripts.

7. We need additional column `pause_time` in `waypoints` table because some creatures should not start path instantly after being summoned.

**Branch:** both
**TC rev. hash/commit:** 3ac1992afbeb

**Comment by offl** [comment]
Probably I forgot about waypoint_data, sometimes it is used in SAI scripts.

**Comment by offl** [comment]
Definitely forgot about SMART_ACTION_START_CLOSEST_WAYPOINT and its `waypoints`.`entry` instead of `pathId`. I'm starting to think it was bad idea to focus on `waypoints` table and not on another new table.
The thing is we already have 3 tables for waypoints and 1 for splines. Another one is too much.

**Comment by Rushor** [comment]
better convert everthing and use waypoint_data table instead only. we had this discussing already 3 years ago :D

**Comment by offl** [comment]
waypoint_data is not compatible at all with pathId thing.

Waypoint_data sucks when you need to assign 30 paths to 30 creatures with one entry.
Instead of summon creature with pathId you need 30 paths with unique **free** entries. Messy.
It is also awful solution for CPP scripts because it uses **free** ids which you simply can't control. They can be deleted by accident. See https://github.com/TrinityCore/TrinityCore/issues/23510. In my opinion everything related to guids is non-stable and can be removed by accident or by changes in script. So if creature is unique and uses only one path, better to use it for entry and not for guid.

Waypoint_data uses waypoints_scripts which were not updated since 2010 while `waypoints` may use timed action one day.

And again, GUID*10 is FREE id, it's not linked to the guid at all. But let's talk about it in another issue.

**Comment by offl** [comment]
`script_waypoint` will be used by 15 creatures one day and remaining waypoints will be replaced by `waypoints` table(if possible)
because they're mostly used in escorts and almost all escorts will be converted to SAI with `waypoints`

**Comment by offl** [comment]
Too much work for nothing and not needed in general
We can spawn creature from DB by using spawn groups
Also Blizz uses scripts every time they need to load waypoint. I mean always, they are not stored somewhere. They are loaded by START WAYPOINT action when creature spawns
