### ISSUE TITLE
Core/Entities: Columns `orientation` & `pause` are missing in table `waypoints`

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24919]
We need these columns to load new orientation and pause from table and not from SAI scripts to make life more simple.
Like it's done in waypoint_data table.

**Branch:** both
**TC rev. hash/commit:** 3ac1992afbeb

**Comment by Rushor** [comment]
that would be awesome!!!!

**Comment by Rushor** [comment]
@dr-j your server has this implemented i think?

**Comment by dr-j** [comment]
Yes but dont know who made change or when was made

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4b7d19c91bde2cabb8498809dee935c7efb2660a
