### ISSUE TITLE
Core/Entities: Column `move_type` is missing in table `waypoints`

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24920]
We need this column to load new move_type from table and not from SAI scripts to make life more simple.
Like it's done in waypoint_data table.
I assume it must not replace currently used values in SAI scripts. For example if default value is 0 (walk) and we set in script it to 1 (run), creature must use values from SAI and not from table.
Or we need to rewrite all scripts. It's not easy.

**Branch:** both
**TC rev. hash/commit:** 3ac1992afbeb

**Comment by Killyana** [comment]
If we add:
move_type=0  -- walk
move_type=1 -- run

What will happen to scripts where the move_type is set SAI action start_waypoint, if the action_param=1 and the move_type=0 in the waypoints table =0 it override it and the npc will walk instead od running ?

**Comment by offl** [comment]
Probably we can do nothing if table move_type is not matching creature current move_type.
We can rewrite all scripts.

**Comment by offl** [comment]
> Probably we can do nothing if table move_type is not matching creature current move_type.

Sounds risky now \ hard to implement.
move_type=2 (do nothing) is best we can do here, also this way we can just set it to 2 for all waypoints and start to update scripts later

**Comment by offl** [comment]
This requires changes in lots of scripts and having move_type in waypoint tables is wrong
Calling SetRun is wrong too
But we can continue use it because it does not require any changes which will cause only problems in future and will be fully reverted
