### ISSUE TITLE
DB/SAI: Update talk action in previously added scripts to set target as talk target

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24938]
```sql
--
UPDATE `smart_scripts` SET `action_param3` = 1 WHERE `event_type` = 4 AND `action_type` = 1 AND `target_type` = 7;
UPDATE `smart_scripts` SET `action_param3` = 1 WHERE `event_type` = 6 AND `action_type` = 1 AND `target_type` = 7;
```

**Branch:** 3.3.5
**TC rev. hash/commit:** 32aebc14abbb

**Comment by illfated** [comment]
I am wondering; would it be unsafe to merge those 2 queries, seeing that there is only 1 argument/parameter containing different values?
Something like:
```sql
--
UPDATE `smart_scripts` SET `action_param3` = 1 WHERE `event_type` IN (4, 6) AND `action_type` = 1 AND `target_type` = 7;
```
Yes, I know, in case of uncertainty, it is better to err on the side of safety, so it is usually "better to be safe than sorry".
