### ISSUE TITLE
Equipped item is left alone and returned to inventory.

### ISSUE THREAD

**Issue by calaluis** [TrinityCore/TrinityCore#24941]
**Description:**

When changing shapes with a druid, the item is moved only to inventory.

**Expected behaviour:**

The item should be in place at all times, until the user moves it.

**Steps to reproduce the problem:**

1.- Equip the item.
2.- Change to bear shape.
3.- The item is magically returned to inventory. If the player does not have bags, the item disappears and it is not possible to recover it.

Link: https://youtu.be/Evlr2hPFF2k

**Branch(es):**
3.3.5

**Operating system:**
Server: Windows Server 2016
Client: Windows 10 Pro

**Comment by Exitare** [comment]
There is a reason why tc is providing an issue template, even with a video.

**Comment by calaluis** [comment]
> There is a reason why tc is providing an issue template, even with a video.

Ready. However, nowhere in the template is it specified to post a demonstration video.

**Comment by Faq** [comment]
You still did not provide hash.

**Comment by jackpoz** [comment]
> **Expected behaviour:**
> 
> The item should be in place at all times, until the user moves it.

is there some constraint that forces the item to be unequipped ? like talent or form or something else ? does blizz email the item instead in these cases ? what happens if you equip that item on retail and change form ?

**Comment by Jildor** [comment]
What macro are you using?

**Comment by Killyana** [comment]
I'm not able to reproduce this issue in rev. cc71da35b5dc
What I did:
1. create a druid (tested with night elf and a Tauren)
2. .level 12 (reach level 13)
3. .cast 19179 (to learn the bear form)
4. .add 42991 (the trinket)
5. Equip the trinket and change form multiple times

The trinket will always remain equipped.

**Comment by calaluis** [comment]
> You still did not provide hash.

Hello, do you mean this?

https://github.com/TrinityCore/TrinityCore/commit/3ac1992afbeb1cd7669b300b8ee4131d39f35595

That was the one that I downloaded and implemented.

**Comment by calaluis** [comment]
> I'm not able to reproduce this issue in rev. [cc71da3](https://github.com/TrinityCore/TrinityCore/commit/cc71da35b5dc74abf71f8691161525a23d870bb5)
> What I did:
> 
> 1. create a druid (tested with night elf and a Tauren)
> 2. .level 12 (reach level 13)
> 3. .cast 19179 (to learn the bear form)
> 4. .add 42991 (the trinket)
> 5. Equip the trinket and change form multiple times
> 
> The trinket will always remain equipped.

Dear,

This was the one that I occupied and implemented at the time.

https://github.com/TrinityCore/TrinityCore/commit/3ac1992afbeb1cd7669b300b8ee4131d39f35595
