### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by WalkerIncMan** [TrinityCore/TrinityCore#24954]
**Description:**

Cooldown after using gm command, to prevent spaming commands.

**Expected behaviour:**
When you trying to use the same gm command after for ex. 2 sec, you will get system message that you need to wait

**Steps to solve the problem:**
To my mind, the best way to achieve cooldown for gm commands is to catch player message with gm command from ChatHandler::ParseCommands in Chat.cpp (src/chat) and make smth like a timer in auction. 

**Branch(es):**
 master 

P.S. It isn't issue, it is smth like intresting idea for me because i just started exploring the trinitycore.

**Comment by Aokromes** [comment]
and, what about if i need to .die 10s of mobs  for a test? :)

**Comment by Killyana** [comment]
If this get implemented it must be optional via the config, personally don't want any limitation.

**Comment by dr-j** [comment]
No this would also mean problems if you macro commands also might cause issues with catching cheats

**Comment by Faq** [comment]
Why this is needed in first place? For private server use? What You try achieve by setting timeout on command? Trust issue towards GMs? Why spamming is bad if it is needed? 
Then better make it in config, if spammed then kick or ban, problem solved :)
