### ISSUE TITLE
Leveling beyond account expansion restrictions

### ISSUE THREAD

**Issue by KurtadamXIV** [TrinityCore/TrinityCore#24959]
**Description:**

My account is expansion 0 so it doesn't have access to the content beyond vanilla. When I hit level 60 after regularly leveling (7x experience rate) the EXP bar disappeared as expected but I still continued to gain experience and eventually leveled up to 61.

**Expected behaviour:**

Experience gain should stop at the appropriate level for each expansion if the account doesn't have access to the next content.

**Steps to reproduce the problem:**

1. Step 1 Have an account with expansion value 0. ( only vanilla ) 
2. Step 2 Have a character at level 60, supposed max level for expansion value 0.
3. Step 3 Do appropriate level experience granting activities
4. Step 4 Eventually level up beyond 60 without having access to it.

**Branch(es):**

3.3.5

**Comment by Aokromes** [comment]
you must change 
MaxPlayerLevel = 80

**Comment by KurtadamXIV** [comment]
If this is not considered an issue then does this mean that this is the way it was intended to be?

**Comment by Aokromes** [comment]
yes, because you may want level 80 classic maps only.

**Comment by ipriver** [comment]
> you must change
> MaxPlayerLevel = 80
> expansion value is for access to maps.

Blizzard had an expansion system that limited not just maps but also EXP. If we want to be 'BlizzLike' it should be implemented to restrict leveling too. Otherwise, we have a Client GUI issue when we don't see EXP bar but still get EXP for accounts that have not the latest extension.

`MaxPlayerLevel = 80` seems like a more global parameter not linked to expansions.

**Comment by KurtadamXIV** [comment]
In my honest opinion level 80 on only vanilla maps seem a bit weird. First of all, it would require custom edits to be able to level to 80 in only vanilla zones and it does sound a lot like a fun server feature. But if it's an intended design approach of TrinityCore then I would assume that it's a take it or leave it situation. Which I would respect.

But yet again it brings out another issue; 
What if I want to have WotLK account and TBC accounts and vanilla accounts coexisting? If I limit the max level to 60 in the worldconfig then accounts with WotLK wouldn't be able to level expansion appropriately.

**Comment by illfated** [comment]
There is always the option to visit the faction capital where you can pay the NPC to stop you from gaining XP on a per-character basis.
When it comes to making modifications affecting all (non-GM) characters, I would expect a bit more tweaking to be required.

**Comment by KurtadamXIV** [comment]
I mean I know there are workarounds, I can talk to the Experience Eliminator NPC, I can edit max level in config, I can even set .character level 60 every single time I go beyond it for all I care. I am playing single player on my own server so it's really nothing more than a minor inconvenience. I just encountered this and thought it wasn't logically supposed to be so it must be an error. Somebody suggested I'd make an issue post on github and here it is. 

I am kinda new around here so I am not sure if we are supposed to provide workarounds for the issue, but I don't really need any workarounds, so thanks for the suggestions and if it's an intended design instead of an issue, you may just close the thread.

**Comment by illfated** [comment]
Fair enough. Fair point. Thanks.

**Comment by jackpoz** [comment]
while this is a valid issue, chances are it will not be fixed (unless someone really interested into it will submit a PR)
