### ISSUE TITLE
Core/SAI: SMART_EVENT_CORPSE_REMOVED

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/TrinityCore#24958]
The event SMART_EVENT_CORPSE_REMOVED is no longer working

``` sql
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=321;
DELETE FROM `smart_scripts` WHERE `entryorguid`=321 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(321,0,0,0,36,0,100,0,0,0,0,0,12,321,8,0,0,0,0,1,0,0,0,0,0,0,0,"321 - On CORPSE REMOVED - Summon 321");
```

**Steps to reproduce the problem:**

1. Use the SAI above
2. .npc add 321
3. Kill it
4. wait for the corpse to be removed
5. an other 321 must be summoned but it will not happen

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. bf62901053d2

**Comment by jackpoz** [comment]
Any idea when it broke ?

**Comment by Killyana** [comment]
Not really, it's used only 4 times and it looks wrong : Pit Commander - On Corpse Removed - Set Active
It could be the dynamic spawn as they changed the way corpse are handled

**Comment by jackpoz** [comment]
The hook is not called if m_respawnCompatibilityMode is false. Maybe it's enough to just call the hook
