### ISSUE TITLE
[3.3.5] Argent Skytalon

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#24963]
**Description:**

NPC: https://www.wowhead.com/npc=30228/argent-skytalon
Quest: https://www.wowhead.com/quest=13045/into-the-wild-green-yonder

When you take Quest 13045, you should mount on NPC 30228
We can se on wowhead comments: https://www.wowhead.com/quest=13045/into-the-wild-green-yonder#comments:id=723335
>For those that do not have coordinates...... DO NOT fly North as mentioned above. You will get dropped. Follow the road that goes NorthWest! This will lead you to the captives. :)

>It doesn't even drop you in a safe place. Just BAM! wherever the hell you may be, even if you're about to land in the middle of the scourge army.

That NPC needs a condition to dismount the player if he is not in the proper area, like:
https://github.com/TrinityCore/TrinityCore/commit/5e95a0fd8105766f2b51a9919e16a73539afa446#diff-7673c4eb522482e4d13e61d62eaa1910R96-R100

I'm not sure what areas need to add to the conditions, needs to be investigated

**Expected behaviour:**

You should be dismounted if you are not in the correct area

**Steps to reproduce the problem:**

1. .go cre id 30227
2. .quest add 13045
3. click Argent Skytalon NPC and fly

**Branch(es):** 3.3.5

**TC rev. hash/commit:** d813a22fefba3951994d0a44ca81e56fff74a25e

**Comment by Killyana** [comment]
``` sql
-- Argent Skytalon
DELETE FROM `creature_template_movement` WHERE `CreatureId` IN(30228);
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`) VALUES
(30228, 1, 0, 2, 0, 0, 0);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=16 AND `SourceEntry`=30228 AND `ConditionTypeOrReference`=23;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(16,0,30228,0,0,23,0,4501,0,0,0,0,0,'','Argent Skytalon Dismount player when not in intended zone'),
(16,0,30228,0,1,23,0,4506,0,0,0,0,0,'','Argent Skytalon Dismount player when not in intended zone'),
(16,0,30228,0,2,23,0,4504,0,0,0,0,0,'','Argent Skytalon Dismount player when not in intended zone'),
(16,0,30228,0,3,23,0,4505,0,0,0,0,0,'','Argent Skytalon Dismount player when not in intended zone'),
(16,0,30228,0,4,23,0,4580,0,0,0,0,0,'','Argent Skytalon Dismount player when not in intended zone');
