### ISSUE TITLE
DB/Creature: Murky

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#24973]
**Description:**

The murloc pet _Murky_ does not dance when using the `/dance` command to him.

**Expected behaviour:**

According to [Wowpedia](https://wow.gamepedia.com/Blue_Murloc_Egg), and this [video](https://youtu.be/FOEgGD3HStk?t=8), he should dance, with him singing too.

**Steps to reproduce the problem:**

1. `.npc add temp 15186` or summon him using the _Blue Murloc Egg_ (`.additem 20371`).
2. Target him and dance.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3e7b0d6c05b27e012b8e407aaeef43b956565fe9

**Operating system:** Windows 7 Enterprise 64bit

**Comment by dr-j** [comment]
This does dance as all Murloc pets do but this is from periodic (baby murloc periodic) works exactly the same as on retail you can’t get these pets to dance when you want you have to wait think it’s ten minutes but could be 15 for the periodic spell to trigger

**Comment by dr-j** [comment]
These are a take on michigan j frog that frog what would dance only when no one was looking

**Comment by Killyana** [comment]
Yes, the npc has a SAI that trigger when the aura https://woehead.way-of-elendil.fr/?spell=24983 procs
