### ISSUE TITLE
DB/Creature: Remove flee actions from civilians & texts related to civilians

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#24979]
Must be handled by https://github.com/TrinityCore/TrinityCore/issues/11563, we can't add thousands scripts and texts to thousands civilians.
```sql
--
UPDATE `creature_template` SET `AIName` = "" WHERE `entry` IN (2711,9978,2382,3543,2379,2378,3540,2383,2380,3541,2381,288,3542,3880,3901,3956,3960,3961,3962,3963,3964,3965,3967,3969,3970,3996,4079,10052,11137,15199,24736);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2711,9978,2382,3543,2379,2378,3540,2383,2380,3541,2381,288,3542,3880,3901,3956,3960,3961,3962,3963,3964,3965,3967,3969,3970,3996,4079,10052,11137,15199,24736) AND `source_type` = 0;
DELETE FROM `creature_text` WHERE `CreatureID` IN (2711,9978,2382,3543,2379,2378,3540,2383,2380,3541,2381);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (3847,3848,3980,24734,24735) AND `source_type` = 0 AND `id` = 0;
```

**Branch:** 3.3.5
**TC rev. hash/commit:** 1bc68b2cae5f

**Comment by Rushor** [comment]
why not? we also have thousand of creature formations and thousands of creature_addons :o

**Comment by offl** [comment]
But we don't have thousands of similar scripts and texts :)
It's not related to SAI or creature script but to unimplemented gameobject type. Maybe to both or maybe only to civilian AI, basic events and gameobjects, but we need sniffs here if this thing can be sniffed. Guardian summons are done by gameobjects and spells or maybe only by gameobjects
1 script or AI or combined system is better than 2k scripts with minimum 3 rows and 2k texts
Also I hope some parts of https://github.com/TrinityCore/TrinityCore/pull/22461#issuecomment-434648796 will be implemented one day and 2k similar scripts have nothing in common with this system

We also need AI for flight masters because they all are similar
