### ISSUE TITLE
DB/areatrigger_teleport: SM dungeon teleports have wrong values

### ISSUE THREAD

**Issue by ipriver** [TrinityCore/TrinityCore#24982]
**Description:**

SM dungeon portals have incorrect teleport positions. Even other different projects running Classic/TBC are using the same wrong values. As an example, if you try to exit SM cath/armory it teleports you far away from the dungeon portal and you have to open the door once again.

According to the wowwiki and changelog, there had been no major changes till MoP. That's why SM portals should be working the same for 3.3.5 as it was in Vanilla/TBC (Classic).
https://wowwiki.fandom.com/wiki/Scarlet_Monastery_(original)

**Expected behaviour:**

I've made some screenshots from the current patch of WoW Classic that I've been using to reproduce correct position values for 3.3.5.

- SM Graveyard
https://imgur.com/a/VbTuD90

- SM Library
https://imgur.com/a/jaCINFH

- SM Armory
https://imgur.com/a/hSrkOkG

- SM Cathedral
https://imgur.com/a/6bJ9QJG

**Steps to reproduce the problem:**

1. Go to the Scarlet Monastery.
2. Try entering/exiting different portals.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

bf62901053d2

Operating system: Ubunutu 20.4, MariaDB 10.3.22

**Suggested Fix:**
```sql
DELETE FROM areatrigger_teleport WHERE ID IN (45, 602, 614, 608, 612, 606, 610, 604);

INSERT INTO areatrigger_teleport 
(ID, NAME, target_map, target_position_x, target_position_y, target_position_z, target_orientation, VerifiedBuild)
VALUES
(45, "Scarlet Monastery - Graveyard (Entrance)", 189, 1687.303, 1049.928, 18.677, 1.596, 0),
(602, "Scarlet Monastery - Graveyard (Exit)", 0, 2915.691, -801.529, 160.332, 3.507, 0),
(614, "Scarlet Monastery - Library (Entrance)", 189, 253.679, -206.363, 18.677, 4.729, 0),
(608, "Scarlet Monastery - Library (Exit)", 0, 2869.237, -820.888, 160.332, 0.387, 0),
(612, "Scarlet Monastery - Armory (Entrance)", 189, 1608.047, -318.794, 18.672, 4.723, 0),
(606, "Scarlet Monastery - Armory (Exit)", 0, 2885.994, -835.933, 160.326, 0.381, 0),
(610, "Scarlet Monastery - Cathedral (Entrance)", 189, 853.079, 1319.082, 18.671, 1.533, 0),
(604, "Scarlet Monastery - Cathedral (Exit)", 0, 2915.175, -823.601, 160.327, 3.488, 0);
```
Used screenshots from Classic as an example of correct positions.

**Tested Query:** Yes

**Comment by illfated** [comment]
Interesting. Never thought about that. Then again, retail is mostly distant history to me now.
