### ISSUE TITLE
[3.3.5] Crash in spell_the_lich_king_jump

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#24980]
**Description:**

Crashlog: https://gist.github.com/gtestdev/5ef87929646d7daa41975dcf20dfad02

Related with: spell_the_lich_king_jump::spell_the_lich_king_jump_SpellScript (https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L3182)

Seems crash happens after: https://github.com/TrinityCore/TrinityCore/commit/cc71da35b5dc74abf71f8691161525a23d870bb5

**Steps to reproduce the problem:**

I don't know how to reproduce, I try killing LK, but crash doesn't happen

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  8c0a315734840f99455026ef443a21ae73d7bc3b

**Operating system:** Debian10

**Comment by illfated** [comment]
(Full gdb backtrace. Should be possible to find something relevant in there.)

**Comment by Faq** [comment]
232628f0a63480d07d28dcf12a7f6445ca07ab43 should be fixing this.
