### ISSUE TITLE
Quest bug: Klaven's Tower

### ISSUE THREAD

**Issue by azraeldestiny01** [TrinityCore/TrinityCore#24985]
**Description:**

URL WoW Head = https://classic.wowhead.com/quest=2359/klavens-tower
Misión quest class = Rogue

Bug Description:

I found a quest bug about the alliance rogue class

Stealing the key from the npcs and trying to open the tower chest gives error.

Versión of trinity core 3.3.5a: 20/06/2020

![imagen](https://user-images.githubusercontent.com/26412400/87100377-8bfae480-c24c-11ea-9b7e-51ef37091157.png)

**Expected behaviour:**

https://www.youtube.com/watch?v=FkJZkvylBOE

**Comment by dr-j** [comment]
Read comments https://classic.wowhead.com/quest=2359/klavens-tower#comments  The key you pickpocket won’t open chest you need to have trained lockpocking
