### ISSUE TITLE
Investigate the usage of "[[fallthrough]]"

### ISSUE THREAD

**Issue by Carbenium** [TrinityCore/TrinityCore#25006]
**Description:**

The currently used method to mark implicit falltroughs in switch statements is a comment of the form
``` /* fallthrough */``` or ```/* fallthrough - reason*/```.

This works well for GCC since it is a supported method to surpress ```-Wimplicit-fallthrough``` warnings (see [Docs](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)).
Clang has no support for these types of comments, but relies on the ```[[fallthrough]]``` attribute (see [Docs](https://clang.llvm.org/docs/AttributeReference.html#fallthrough)).

Investigate/discuss whether we should switch to the standardized ```[[fallthrough]]``` attribute.

**Pros :**

- better compiler support (GCC + clang)
- future-proof since standardized

**Branch(es):**
both

**TC rev. hash/commit:** c92950b3e1f6366d85d707365a8ad2caddafeecc

**Comment by jackpoz** [comment]
I would like every fallthrough to have a comment about why it's there,  whether it's in the attribute or as comment

**Comment by Carbenium** [comment]
First step of converting existing fallthrough marks is handled in https://github.com/TrinityCore/TrinityCore/pull/25054.
clang though is a bit pickier than GCC, so some additional warnings popped up: #25055

When those are fixed we can enable `-Wimplicit-fallthrough` for clang as well.

**Comment by Carbenium** [comment]
85b5b842ca6c05d4e51081e6c3282940a80f3761
e6e5775be83d07c3221d6690f11184246bec4bf1
