### ISSUE TITLE
25000 is mine

### ISSUE THREAD

**Issue by Shauren** [TrinityCore/TrinityCore#25000]
heh

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20000#issuecomment-313847570

**Comment by illfated** [comment]
When I read this ticket title in my Notifications list, I thought to myself: "I can't remember this quest name, is this from a new expansion?" 😄

**Comment by MaxtorCoder** [comment]
😂😂😂 Knew it
