### ISSUE TITLE
Core/Spell:Warrior charge

### ISSUE THREAD

**Issue by kuramajssken001** [TrinityCore/TrinityCore#25014]
**Description:**

The warrior will not be able to properly engage with normal attacks when using charge，It should use a normal attack immediately.

Branch(es): 3.3.5

TC rev. hash/commit: rev. 352944266822f8c8d3bfdd6078c6f82d3555dd85

**Comment by jackpoz** [comment]
when you say "both" do you mean you tested both master and 335 branches ?

**Comment by Jildor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24626

**Comment by kuramajssken001** [comment]
> [＃24626](https://github.com/TrinityCore/TrinityCore/issues/24626)

yeah, like this.

**Comment by kuramajssken001** [comment]
> 当您说“两者”时，是否意味着您同时测试了master和335个分支？任何详细的如何重现步骤？

Sorry,Have been reedited.
