### ISSUE TITLE
Core/Time: Rename GetGameTime{System, Steady}Point methods

### ISSUE THREAD

**Issue by Carbenium** [TrinityCore/TrinityCore#25042]
For most use cases in the core we want to rely on a steady monotonic clock since system time changes e.g via NTP shouldn't influence time (difference) calculations within TC.
This is guaranteed by the `std::chrono::steady_clock` whereas the `std::chrono::system_clock` is coupled to the system clock and thus not monotonic.

The current API defined in `GameTime.h` allows to access `now` time points updated every world tick for both type of clocks via
```c++
std::chrono::system_clock::time_point GetGameTimeSystemPoint();
std::chrono::steady_clock::time_point GetGameTimeSteadyPoint();
```

While describing accurately the returned value, the names seem a bit unhandy. Following API change is proposed:

**Duration.h**
**Add**:
```c++
/// time_point shorthand typedefs
typedef std::chrono::steady_clock::time_point TimePoint;
typedef std::chrono::system_clock::time_point SystemTimePoint;
```

**GameTime.h**
**Change**:
```c++
TC_GAME_API std::chrono::system_clock::time_point GetGameTimeSystemPoint();
TC_GAME_API std::chrono::steady_clock::time_point GetGameTimeSteadyPoint();
```
to
```c++
TC_GAME_API SystemTimePoint GetSystemTime();
TC_GAME_API TimePoint Now();
```

This API change should make easier to choose between the two methods depending on use-case with `Now()` being the preferred one.

Thanks @Treeston for actually "proposing" this in https://github.com/TrinityCore/TrinityCore/pull/22461/commits/990b986b325dcbeaaefae29f16f6c93d4e23dbce .

**Comment by Treeston** [comment]
ref #22461 which included this as a refactor component, thanks @Carbenium for splitting this off

:+1:

**Comment by Carbenium** [comment]
896b68d5c297b06587645caebc98b704978ecaa7
