### ISSUE TITLE
Pandaria Missing Quests and TrinityCore General info

### ISSUE THREAD

**Issue by FSKiller** [TrinityCore/TrinityCore#25044]
**Description:**
No Quest giver in wandering isles and 0 Npc and critter spawns in Demon Hunter staring zone

**Branch(es):**
master

Also i dont see a Pandaria scripts folder in the source is this normal?

Sorry in advance started tinkering with TrinityCore today

Any way to know what is working and what is not? Playing in LAN trying to avoid as many broken stuff as possible

Fresh compile from latest source.
With latest client.

**Comment by MaxtorCoder** [comment]
Cata+ is a Sandbox. Content simply not implemented.

**Comment by Aokromes** [comment]
duplicate, a never ending wip exists for it.
