### ISSUE TITLE
DB/Texts: Wrong text on boat signpost, Menethil Harbor

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25046]
**Description:**

The current text to the right of the sign is **Boat to Auberdine**.

![Screenshot](https://i.ibb.co/kQT8N37/Wo-WScrn-Shot-071420-174055.jpg)

**Expected behaviour:**

I don't know how the signpost was originally in a _Blizzard_ server, but should the sign point to the correct destination?
The correct one should be **Boat to Valgarde**, if I am not wrong?

https://wow.gamepedia.com/Menethil_Harbor#Travel_connections

**Steps to reproduce the problem:**

1. `.tele MenethilHarbor`
2. Look at the right sign.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3e7b0d6c05b27e012b8e407aaeef43b956565fe9

**Operating system:** Windows 7 Enterprise 64bit

**Comment by Aokromes** [comment]
there is no "Boat to Valgarde" on db, very likely it's blizzlike bug.

**Comment by lwbbdyx** [comment]
Try this
UPDATE `world`.`gameobject_template` SET `name`='Boat to Valgarde' WHERE (`entry`='176370');

**Comment by Aokromes** [comment]
without sniff that's a hack

**Comment by offl** [comment]
>Alliance Valgarde Wrath of the Lich King
Alliance Auberdine (formerly)

Wasn't updated probably

**Comment by Aokromes** [comment]
meh on ptr that doesn't even exist
https://i.imgur.com/H8femrb.jpg

**Comment by ratkosrb** [comment]
Signs are in the db2 nowadays. The data for 176370 matches Classic, so the current template data is not custom even though it has no verified build assigned, but no idea if it is accurate for wotlk. They could have removed the sign altogether instead of updating the name. https://wow.tools/dbc/?dbc=gameobjects&build=1.13.5.35000#page=1&search=Boat

**Comment by offl** [comment]
They simply removed both signs
2009 https://youtu.be/jjglwJDqYmY?list=PL26B1F0F238B47030&t=386
2009 https://youtu.be/FACiiDSu2eM?list=PL26B1F0F238B47030&t=164
2010 https://youtu.be/pRml9OdC1hY?t=267
