### ISSUE TITLE
DB/Creature: Amnennar the Coldbringer

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25077]
**Description:**

When fighting **Amnennar the Coldbringer**, he does not summon troops to attack me.

**Expected behaviour:**

According to [Wowpedia](https://wow.gamepedia.com/Amnennar_the_Coldbringer_(Classic)), and according to [Wowhead](https://classic.wowhead.com/npc=7358/amnennar-the-coldbringer#comments) comments, he should summon _Frost Spectres_ to aid him during combat.

**Steps to reproduce the problem:**

1. `.go creature id 7358`
2. Attack and fight him until the end.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d974800e9d1e393ce3459ed8be4f4bd9defcc8f3

**Operating system:** Windows 7 Enterprise 64bit

**Comment by Jinnaix** [comment]
Valid - Amnennar casts the required [Spell](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=12642) but the Spectres instantly despawn

https://github.com/TrinityCore/TrinityCore/blob/00b16992f1ae3bf14ab5fe6366028a2b8648bfa0/src/server/scripts/Kalimdor/RazorfenDowns/boss_amnennar_the_coldbringer.cpp#L123-L141

Tried changing DoCastVictim with DoCastSelf and DoCast but its the same result. But as GM, i can use .cast back 12642 in combat and out of combat.

**Comment by offl** [comment]
They use hacky AI to despawn when boss dies or when wipe occurs https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=8585
Must be handled in boss script

If they despawns even if nearby friendly creature is not below 100 health, then something is broken in SAI. Maybe they evades instantly

**Comment by Jinnaix** [comment]
A wild guess, but maybe they instantly despawn by Event 1 because they trigger each other with this?

**Comment by offl** [comment]
Nope, they despawns instantly with full hp
Everything works fine without that hacky event
```text
entryorguid  source_type      id    link  event_type  event_phase_mask  event_chance  event_flags  event_param1  event_param2  event_param3  event_param4  event_param5  action_type  action_param1  action_param2  action_param3  action_param4  action_param5  action_param6  target_type  target_param1  target_param2  target_param3  target_param4  target_x  target_y  target_z  target_o  comment                                                                                
-----------  -----------  ------  ------  ----------  ----------------  ------------  -----------  ------------  ------------  ------------  ------------  ------------  -----------  -------------  -------------  -------------  -------------  -------------  -------------  -----------  -------------  -------------  -------------  -------------  --------  --------  --------  --------  ---------------------------------------------------------------------------------------
       8585            0       1       0          14                 0           100          515           100            30             0             0             0           41              0              0              0              0              0              0            1              0              0              0              0         0         0         0         0  Frost Spectre - Friendly At 100 Health - Despawn Instant (No Repeat) (Normal Dungeon)  
```

**Comment by Jinnaix** [comment]
Or we just fix their SAI?
Digging trough wowhead, they also seem to be able to use "[dazed](https://classic.wowhead.com/npc=8585/frost-spectre#abilities)" as a spell. Since i dont have access to any sniffs from this fight, numbers for SAI ID 2 are guessed.
Both cases (Boss evade and death) work fine with the following script:

```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 8585;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 8585);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(8585, 0, 0, 0, 1, 0, 100, 3, 1000, 1000, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Frost Spectre - Out of Combat - Despawn Instant (No Repeat) (Normal Dungeon)'),
(8585, 0, 1, 0, 5, 0, 100, 515, 0, 0, 0, 7358, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Frost Spectre - On Killed Unit - Despawn Instant (No Repeat) (Normal Dungeon)'),
(8585, 0, 2, 0, 0, 0, 50, 514, 5000, 10000, 10000, 10000, 0, 11, 1604, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Frost Spectre - In Combat - Cast \'Dazed\' (Normal Dungeon)');
```

**Comment by offl** [comment]
Better to change existing CPP script because it's easier than trying to do it in SAI + we often despawn adds in boss script

```sql
(8585, 0, 1, 0, 5, 0, 100, 515, 0, 0, 0, 7358, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Frost Spectre - On Killed Unit - Despawn Instant (No Repeat) (Normal Dungeon)'),
```
`On Killed Unit` means when creature kills another creature, they can't kill their summoner, probably it works for you because they're guardians and despawns instantly without any script after summoner's death(?)

> Digging trough wowhead, they also seem to be able to use "dazed" as a spell

Creatures never cast it in scripts, it's used only when creature hits player from behind and sometimes wowhead count that spell cast as normal spell cast, but it should be ignored by wowhead addon

**Comment by Jinnaix** [comment]
So for a case where i want something to happen when a specific creature gets killed, we dont have something easy?

We can despawn creatures with c++ but targetting them is more complicated than just keeping this one line here and gives the same result:

```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 8585;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 8585);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(8585, 0, 0, 0, 1, 0, 100, 3, 1000, 1000, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Frost Spectre - Out of Combat - Despawn Instant (No Repeat) (Normal Dungeon)'),
```

**Comment by offl** [comment]
> So for a case where i want something to happen when a specific creature gets killed, we dont have something easy?

Depends on what exactly you want to do
In that case and similar we just despawn adds in boss script when boss evades or dies

**Comment by offl** [comment]
I sligthly changed sql to despawn them after reaching home because seems like Blizzard executes such events only after reaching home. Actually with recent changes related to evade there's no difference between your version and my
Also we don't need to set event_flags to 2 in dungeons with only one mode, expecially in cases if creature is spawned only in instance

**Comment by illfated** [comment]
Closed by mistake?

**Comment by Jinnaix** [comment]
No, the issue is fixed @illfated

**Comment by illfated** [comment]
Thanks, I did not notice the commit https://github.com/TrinityCore/TrinityCore/commit/2ffc3124ae8c029c7d3fb043275d1fd2138517be -- maybe because the labels were added after closing.
