### ISSUE TITLE
Crash with Respawns

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#25079]
**Description:**

[crash.log](https://github.com/TrinityCore/TrinityCore/files/4944351/crash.log)

**Steps to reproduce the problem:**

Did not found a way to reproduce, it just crash randomly once or twice a day. I compile source once a week, and it started happening after the week of 7/12. It seems like system is trying to process respawns and aborted.

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

00b16992f1ae3bf14ab5fe6366028a2b8648bfa0

**Operating system:**

Debian 10.2

**Comment by jackpoz** [comment]
could you run this query on your characters database and post the result ?

```sql
SELECT DISTINCT `type` FROM respawn;
```
and
```sql
SELECT * FROM respawn WHERE `type` NOT IN (0, 1);
```

**Comment by ckegg** [comment]
> ```sql
> SELECT DISTINCT `type` FROM respawn;
> ```
```
+------+
| type |
+------+
|    0 |
|    1 |
+------+
2 rows in set (0.000 sec)
```

> ```sql
> SELECT * FROM respawn WHERE `type` NOT IN (0, 1);
> ```
```
Empty set (0.000 sec)
```

**Comment by jackpoz** [comment]
Did you find the cause of the crash ?
