### ISSUE TITLE
More than 2 professions are not retained after character log out and log in

### ISSUE THREAD

**Issue by TownShip101** [TrinityCore/TrinityCore#25073]
**Description:**

More than 2 professions are not retained after character log out and log in.

TrinityCore supports up to 11 character professions via the MaxPrimaryTradeSkill. https://github.com/TrinityCore/TrinityCore/issues/15575

**Expected Behavior:**

The WorldServer should retain the character_skills of a player after logging off and logging in, especially if the config is setup to allow for more than 2.

**Steps to reproduce the problem:**
Tested With:
- TrinityCore: WorldServer for 7.3.5 compiled on 2/23/20
- Game.Build.Version = 26972
- Extract of DBLog: https://pastebin.com/YSZm5M9d

1. Ensure that worldserver.conf is set to MaxPrimaryTradeSkill = 11 (or anything above 2)
2. Create a new character
3. Learn any two professions (in one test I used Blacksmithing and Alchemy)
4. -- Notice that you cannot manually learn a third profession from a trainer (Separate issue, I think)
5. [A] Seperate issue, but the standard GUI blocks a character from learning more than two by graying out the button.
[B] Manually learn the skill via GM Command .learn 7411 (Enchanting)
[C] -- The DBLog shows the following "[1 ms] SQL(p): REPLACE INTO character_skills (guid, skill, value, max) VALUES (1363318, 333, 1, 75)"
6. [A] /cast enchanting
[B] /cast disenchant and disenchant an item. The DBLog shows the following "UPDATE character_skills SET value = 2, max = 75 WHERE guid = 1363318 AND skill = 333"
7. -- Notice how it works correctly
8. -- Notice how in the DB the "character_skills" table has an entry for 333
9. -- Another verify step, Disenchant an item, notice how your character_skills value for 333 correctly increases to 2
10. -- Another verify step, run "/cast enchanting" Notice how the UI correctly shows a skill level of 2 for enchanting.
11. Log out of the character
12. -- Notice how in the DB the "character_skills" table has an entry for 333 with a value of 2
13. Log in to the same character
14. Wait ~1 minute for database to be updated
15. Open the Skill Book and check the professions tab on your character
16. [A] ** Notice how in the DB the "character_skills" table no longer has an entry for 333
[B] The DBLog shows the following: "[0 ms] SQL(p): DELETE FROM character_skills WHERE guid = 1363318 AND skill = 333"
17. -- Another verify step, "/cast enchanting", Notice how nothing happens

**Additional Details**

- Anticheat.Enable = 0 (Anti cheat is disabled)
- No messages in the log files related to this, both client and server
- (For Control) If enchanting is one of the two primary professions, and the steps above are followed, enchanting (333) works fine, but the other profession is not retained.

- ?Clue? If you unlearn "Enchanting" as one of your two primary professions, (leaving one profession remaining) log off and log on, the same issue occurs, the "character_skills" will have Enchanting 333, until you log into the character, then it will be removed.

"Player.cpp" looks like it might be a candidate, but cannot confirm.
- Reviewing the "void Player::SetSkill" function, 
-- Around Line 5787  "// mark as deleted so the next save will delete the data from the database"
-- Around Line 5811 "// We are about to learn a skill that has been added outside of normal circumstances (Game Master command, scripts etc.)"
-

cs_learn.cpp could be related, but...
- If you use the .learn command for your first two professions, they correctly work and are not deleted after login

**Branch(es):**

master, compiled on 2/23/20

**TC rev. hash/commit:** 

N/A

**Operating system:**
Windows

**Comment by jackpoz** [comment]
> * TrinityCore: WorldServer for 7.3.5 compiled on 2/23/20

sounds like an old unsupported version of TC

**Comment by jackpoz** [comment]
> **TC rev. hash/commit:**
> 
> N/A

How come this is N/A ? don't you have the commit hash ?

**Comment by Aokromes** [comment]
that was fixed on master branch long time ago, 7.x is unsuported.

**Comment by TownShip101** [comment]
Sorry, this is my first ticket like this with TrinityCore, I have updated this issue.

master = 8.3.0.33775
legion = 7.3.5.26972

**Comment by MaxtorCoder** [comment]
> that was fixed on master branch long time ago, 7.x is unsuported.

**Comment by TownShip101** [comment]
Ok, thank you,

**Comment by TownShip101** [comment]
Just in case anyone else runs into this same problem, do you a commit or issue that you can reference? In Google searching for this issue, other people reported this issue on 8.2 back in 2019, but no details were provided. E.g. https://community.trinitycore.org/topic/14902-more-then-2-professions/
