### ISSUE TITLE
How do I modify the time of Hearthstone CD

### ISSUE THREAD

**Issue by cjl3230** [TrinityCore/TrinityCore#25089]
**Description:**
How do I modify the time of Hearthstone CD？
My client 3.3.5(12340)shows that the CD time of Hearthstone is 2 minutes, but it actually takes about 30 minutes and shows that Hearthstone is not available

CHANGEME Description of the problem or issue here.
How do I modify the time of Hearthstone CD？
My client 3.3.5(12340)shows that the CD time of Hearthstone is 2 minutes, but it actually takes about 30 minutes and shows that Hearthstone is not available

**Expected behaviour:**
My client 3.3.5(12340)shows that the CD time of Hearthstone is 30 minutes，

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
0b616e4865f89b1d15ae20dccd83825cddb5c288

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:**
Win10 2004 x64

**Comment by cjl3230** [comment]
By the way, if I want to modify the Hearthstone time, how should I set it?

**Comment by Aokromes** [comment]
this belongs to forum.
