### ISSUE TITLE
Gameobject: Deadmines doors after Sneed and Gilnid

### ISSUE THREAD

**Issue by TranceAccount** [TrinityCore/TrinityCore#25100]
**Description:**

The doors spawned in the boss rooms of both Sneed and Gilnid appear to be wrong, and also do not open after killing the boss. I wanted to add the code to make the door go open after the boss kills, but I did not know how to select a specific GUID entry in C++. Then I saw that the spawned doors might actually be wrong, and if that is the case, the Door Levers that are spawned behind these doors need a change in their SAI too, since they open this specific GUID.

**Expected behaviour:**

The doors after both Sneed and Gilnid should actually have a 'keyhole' on them as is the case with Rhahr'zok, and open after killing the boss.

Video from 10 years ago, before Deadmines overhaul in the Cataclysm:
Sneed kill and door opening: https://youtu.be/ISqmoudKNjM?t=135
Gilnid kill and door opening: https://youtu.be/ISqmoudKNjM?t=175

_Edit:_ The following youtube video has a higher quality, and clearly shows that the doors should have a different look: https://www.youtube.com/watch?v=9llzpLsqBiQ 

**Screenshots of current situation**
[Sneed](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=643) (with .gobj near in chat):
![WoWScrnShot_072320_180550](https://user-images.githubusercontent.com/13118481/88310831-6cfe5700-cd10-11ea-96ab-e9b9b5b0eecc.jpg)

[Gilnid](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1763) (with .gobj near in chat):
![WoWScrnShot_072320_180748](https://user-images.githubusercontent.com/13118481/88310866-75569200-cd10-11ea-9fcc-99f894dbd9f5.jpg)

**Steps to reproduce the problem:**

1. .tele Deadmines
2. Kill Sneed, and watch door not open.
3. Proceed to kill Gilnid, and watch door not open.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

[c3037c35639a](https://github.com/TrinityCore/TrinityCore/commit/c3037c35639a)

**Operating system:** Windows 10 Home

**Comment by TranceAccount** [comment]
What I think should be the case here is that the entries used for these doors are wrong. E.g. looking at 'same model as' entries for the [Factory Door](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=13965) (the door used at the Rhahr'zok [first boss]) it shows 3 other entries. One of those entries is used as the last door in the dungeon (Opened with the cannon).

Are there sniffs available to verify this data, or can I assume that the door after Sneed is supposed to be the [Foundry Door](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=16399) (e.g. leads to the foundry of Gilnid [The large melting pot]), and for the door after Gildnid the [Mast Room Door](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=16400).

**Comment by TranceAccount** [comment]
I have a fix for this, based on the cmangos foundings.
Pull request soon™.

**Comment by Treeston** [comment]
81f3ed1d0c6ecba624b4a88a4c60c0dfa1cd9524
