### ISSUE TITLE
DB/world Bad primary key for table "quest_greeting_locale"

### ISSUE THREAD

**Issue by Cerveciento** [TrinityCore/TrinityCore#25115]
**Description:**
The PK from quest_greeting_locale only has columns 'ID' and 'Type', not include 'Locale'. When trying to insert text in another language, it fails with error code 1062.

**Expected behaviour:**
Correct insert into BD.
**Fix:**
``` sql
ALTER TABLE `quest_greeting_locale` DROP PRIMARY KEY;
ALTER TABLE `quest_greeting_locale` ADD PRIMARY KEY( `ID`, `Type`, `locale`); 
```
**Steps to reproduce the problem:**
``` sql
INSERT INTO `quest_greeting_locale` (`ID`, `Type`, `locale`, `Greeting`, `VerifiedBuild`) VALUES ('823', '0', 'esES', 'bla bla bla...', '12340');
```
FAIL: 1062 - Entrada duplicada '823-0' para la clave 'PRIMARY'
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 7ea33120a03d
**Operating system:** debian 10

**Comment by jackpoz** [comment]
Thanks for the fix
