### ISSUE TITLE
Pathfinding Deadmines

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#25114]
**Description:**

Pathfinding not working in Deadmines

**Expected behaviour:**

Mobs should run down the stairs

**Steps to reproduce the problem:**

Watch the video

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

880a736

**Operating system:**

Windows 10 64

**Comment by lingxDEV** [comment]
https://imgur.com/glRH1KV

**Comment by lingxDEV** [comment]
This happens all over Deadmines where you can jump off, the mobs just jump with you and fly in the air.

**Comment by Jinnaix** [comment]
Im a few days behind (896b68d5c297b06587645caebc98b704978ecaa7) but i cant replicate this. If i aggro the mobs on this platform and jump down like you do in the .gif, creatures will correctly go down the ramp to the right to follow me.
Did you mmap.enablePathFinding = 1 ?
Did you rebuild mmaps after the latest changes from some weeks ago?

**Comment by lingxDEV** [comment]
I didn't rebuild mmaps, no. That's probably it!
