### ISSUE TITLE
DB/Creature: Add script to Arakkoa Egg (20214)

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25112]
Spell 35788 doesn't have any effect for some reason
```sql
-- Arakkoa Egg SAI (Source: ACID)
SET @ID := 20214;
UPDATE `creature_template` SET `AIName` = "SmartAI" WHERE `entry` = @ID;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @ID AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID,0,0,0,11,0,100,0,0,0,0,0,0,8,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Arakkoa Egg - On Respawn - Set Reactstate Passive"),
(@ID,0,1,0,6,0,100,0,0,0,0,0,0,11,35788,2,0,0,0,0,1,0,0,0,0,0,0,0,0,"Arakkoa Egg - On Death - Cast 'Arakkoa Egg Debuff'");
```

**Branch:** both
**TC rev. hash/commit:** 8675fd756ff9

**Comment by dr-j** [comment]
This could be due to faction of trap object?

**Comment by Rushor** [comment]
yes

**Comment by offl** [comment]
What trap object? You mean SPELL_EFFECT_PERSISTENT_AREA_AURA?

**Comment by dr-j** [comment]
Look at gameobject template and look at data7 this is object id of linked trap object

184797 and 184801 are object ids

**Comment by offl** [comment]
These objects are not related to creature Arakkoa Egg (20214)

**Comment by offl** [comment]
> Spell 35788 doesn't have any effect for some reason

I mean creature casts it and it creates Persistent Area Aura. Aura applies correctly on player but without any effects (Nature damage inflicted every 2 sec. Armor reduced by 15%.)

**Comment by offl** [comment]
Related to spell level, does not work if level is 80, idk if it's correct or not and how many spells are affected
