### ISSUE TITLE
8.3.7.35284 Сlient crash when adding transport to DB

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#25130]
**Description:**

When adding a transport to the Transports table, the client crashes with error 132.

**Expected behaviour:**

When adding a transport to the database, the client does not crash, and the transport arrives at the desired point.

**Steps to reproduce the problem:**

1. Open the Transports table in the World database
2. Add the following value to the Transports table: 29,272677,Zandalari Ship,0,0,0	
3. Log into the game and go to the port where the ship will take you to Zandalar. Wait for the ship to arrive

**Branch(es):**

master

**TC rev. hash/commit:** 

b3ba029 

**Operating system:** Windows 10 x64

**Comment by DintyGadget** [comment]
gameobject data was missing flags in gameobject_template_addon table (Flag: 1048616)

**Comment by illfated** [comment]
Funny how your flag value triggered a GitHub TC rev. hash,
as well as seeing how unrelated and oddly described that commit is:

**Scripts/Spells : Warrior Colossus Smash Effect**

🦕 This commit does not belong to any branch on this repository.
