### ISSUE TITLE
Core Not Validating Modified SpellFocusRequirement in Spell.dbc

### ISSUE THREAD

**Issue by suprsokr** [TrinityCore/TrinityCore#25142]
**Description:**

Spells that have a SpellFocusRequirement attribute defined in Spell.dbc are not validated by the core, allowing a client to easily change Spell.dbc and bypass the Spell Focus mechanic.

**Expected behaviour:**
The player should not be able to modify Spell.dbc to bypass Spell Focus requirements by modifying Spell.dbc. The player should instead receive the same error as if the Spell Focus requirement was not met.

**Steps to reproduce the problem:**

1. Set Spell.dbc entry 13630's SpellFocusRequirement to 0  (I used WDBX Editor for this step)
2. Save Spell.dbc
3. Delete WDB folder (in case you've already cached this quest object)
4. Launch Server
5. Create a new character and .level to 48
6. .tele marshals refuge
7. Accept quest Alien Ecology from Hol'anyee Marshal
8. Right click Unused Scraping Vial in your inventory.

Without being near the Spell Focus object, you will successfully cast the Scraping spell and acquire the Hive Wall Sample.

Alien Ecology (https://wotlkdb.com/?quest=3883)
Scraping (https://wotlkdb.com/?spell=13630)
Unused Scraping Vial (https://wotlkdb.com/?item=11132)
Hive Wall Sample (https://wotlkdb.com/?item=11131)
Spell Focus "Gorishi Hive Hatchery Focus (DND)" (https://wotlkdb.com/?object=164892)

This hack theoretically works on quests with similar Spell Focus mechanics, like Seeping Corruption (https://wotlk.evowow.com/?quest=3568).

Note: If you test this, be sure to change your Spell.dbc entry 13630 SpellFocusRequirement back to its blizz like value of 463 and then delete your WDB folder.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Core: b20ede9061d088cbcb5095d75406bb26638c20e7

Database: TDB_full_world_335.20071_2020_07_15

This works with a fresh compile of TC and unmodified database.

**Operating system:** Windows 10

**Commentary**

This may not be a bug. I am not sure how blizzlike 3.3.5 servers would have handled this.

The only solution seems to be duplicating more of Spell.dbc on the server and ignoring the client's SpellFocusRequirement attribute. One could then update Spell::CheckCast in Spell.cpp to safely check for the SpellFocusRequirement of a spell.

**Comment by Shauren** [comment]
Did you just edit the Spell.dbc that is loaded by worldserver instead of adding it to clients mpq files? Its all checked serverside here
https://github.com/TrinityCore/TrinityCore/blob/40efda9726dce4fc6f432852f8d41bee606872b7/src/server/game/Spells/Spell.cpp#L5379-L5384
Obviously if you edit Spell.dbc on the server it will no longer check it

**Comment by suprsokr** [comment]
@Shauren You're right, I didnt realize my dbc files were shared between my client and my server. Feel free to delete this issue.
