### ISSUE TITLE
terminate called after throwing an instance of 'boost::process::process_error'

### ISSUE THREAD

**Issue by 94031146** [TrinityCore/TrinityCore#25147]
**Description:**

worldserver failed after try to apply 2020_07_22_00_world.sql

error log:
TrinityCore rev. 1131229ee9c4 2020-07-26 23:30:32 +0200 (HEAD branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/trinity/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.1.1  11 Sep 2018 (library: OpenSSL 1.1.1  11 Sep 2018)
Using Boost version: 1.73.0
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 69 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 49 archived updates.
Updating World database...
>> Applying update "2020_07_22_00_world.sql" '1592249'...
terminate called after throwing an instance of 'boost::process::process_error'
  what():  : Bad file descriptor
Caught signal 6
Segmentation fault (core dumped)

related libs:
ldd worldserver 
	linux-vdso.so.1 (0x00007fff2134d000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007fe6aa9ef000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fe6aa7c5000)
	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007fe6aa57c000)
	libmariadb.so.3 => /usr/lib/x86_64-linux-gnu/libmariadb.so.3 (0x00007fe6aa32c000)
	libboost_system.so.1.73.0 => /usr/local/lib/libboost_system.so.1.73.0 (0x00007fe6aa12a000)
	libboost_filesystem.so.1.73.0 => /usr/local/lib/libboost_filesystem.so.1.73.0 (0x00007fe6a9f0e000)
	libboost_program_options.so.1.73.0 => /usr/local/lib/libboost_program_options.so.1.73.0 (0x00007fe6a9ca7000)
	libboost_iostreams.so.1.73.0 => /usr/local/lib/libboost_iostreams.so.1.73.0 (0x00007fe6a9a95000)
	libboost_regex.so.1.73.0 => /usr/local/lib/libboost_regex.so.1.73.0 (0x00007fe6a97c2000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fe6a9535000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fe6a906a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe6a8e4b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe6a8c47000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe6a8a2a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe6a86a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe6a8303000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe6a80eb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe6a7cfa000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fe6a7aea000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007fe6a7649000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fe6a7291000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe6aac12000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fe6a56e8000)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

1131229ee9c43704b11187f0b11c327db92018b6

**Operating system:** 

Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-111-generic x86_64)

Any help will be greatly appreciated!!!

**Comment by Shauren** [comment]
This looks like a crash report but there is no stack trace

**Comment by 94031146** [comment]
run worldserver as root fixed the issue, once after that, use normal user restart worldserver give out no error.
seems to be some access issue with my building.
Thanks for your reply @Shauren !
