### ISSUE TITLE
Linking error with MSVC Toolset Version 14.2 (VS 2019)

### ISSUE THREAD

**Issue by XalconRE** [TrinityCore/TrinityCore#25160]
**Description:**

When compiling TrinityCore (master) with VS 2019 16.4 / MSVC 14.2, VS will complain about missing libraries.
I've installed both boost libraries, 1.73 for MSVC 14.1 and MSVC 14.2 and the environment variable is configured accordingly:
```
PS C:\Users\Me> ls $env:BOOST_ROOT


    Directory: C:\local\boost_1_73_0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          10/07/2020    17:17                boost
d----          10/07/2020    17:18                doc
d----          10/07/2020    17:19                lib64-msvc-14.1
d----          10/07/2020    16:36                lib64-msvc-14.2
d----          10/07/2020    17:19                libs
d----          10/07/2020    17:21                more
d----          10/07/2020    17:21                status
d----          10/07/2020    17:21                tools
***snip***
```

When configuring trinity core via CMake, it picks up the msvc-141 libs yet VS2019 complains about being unable to find the 142 libs during compilation.

```
13>LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc142-mt-gd-x64-1_73.lib'
```
![image](https://user-images.githubusercontent.com/21059740/88650198-cb3c8880-d0c8-11ea-8a43-0b3dda4c5d7f.png)

I don't know why it tries to locate the `libboost_program_options-vc142-mt-gd-x64-1_73.lib` when it clearly references vc141, but I was able to work around this issue, see **workaround**.

**Steps to reproduce the problem:**

1. Install latest VS 2019 Community Edition (Tested with 16.4.2 and 16.7-Preview)
2. CMake configure + generate
3. Compile and observe the error

**Branch(es):** master (not tested on 3.3.5)

**Operating system:** Windows 10 Version 2004 OS Build 19041.421

**Workaround:**
I was able to work around this issue by editing the `dep/boost/CMakeList.txt`. When adding `${BOOST_ROOT}/lib${PLATFORM}-msvc-14.2` to the list of directories in said file, cmake will pickup the path to the vs142 libraries just fine and the solution compiles as expected.

https://github.com/TrinityCore/TrinityCore/blob/e3cf94d4fdbfae5ce99aa754bd29a0b77cd1b73d/dep/boost/CMakeLists.txt#L19-L23

I've also tried setting the toolset version to v141 in CMake, but it then just errors out complaining it cant find it - which makes sense: 14.1 is VS 2017, which is not installed on my system.

Is adding the 14.2 path to the list the proper way to fix this? Do you want me to make a PR for this? Or am I doing something wrong?

**Comment by MaxtorCoder** [comment]
You should use Boost 1.71/1.72 😄 1.73 is not added into the `CMakeLists.txt` yet.

**Comment by XalconRE** [comment]
Hm, the wiki says `Boost ≥ 1.70 (latest stable recommended)` :P I'll try with 1.72 then.

**Comment by jackpoz** [comment]
what do you need lib64-msvc-14.1 for ? just install the 14.2

**Comment by MaxtorCoder** [comment]
Ah yeah, big brain KEKW

**Comment by XalconRE** [comment]
oh crap. Yeah, removing the 14.1 installation of boost works. I've no clue why I had that on my system in the first place. Sorry!
