### ISSUE TITLE
8.3.7 Deeprun Tram (Crash worldserver)

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#25166]
**Description:**

The server crashes instantly upon entering Deeprun Tram (Map 369).

**Expected behaviour:**

Entering 369 map should not crash the server

**Steps to reproduce the problem:**

1. Create any character
2. Head to the Deeprun Tram Entrance
3. Go inside, the server crashes

**Branch(es):**

master

**TC rev. hash/commit:** 

97afa3a

**Operating system:** Windows 10 x64

**Comment by DintyGadget** [comment]
[unknown_worldserver.exe_[29-7_11-52-52].txt](https://github.com/TrinityCore/TrinityCore/files/4992249/unknown_worldserver.exe_.29-7_11-52-52.txt)

**Comment by DintyGadget** [comment]
maybe this can somehow help
![fafd90523c86cac6fed5cd6315d697ca](https://user-images.githubusercontent.com/25077548/88780246-abd75580-d1c5-11ea-84ed-fa1714c3c44c.png)

**Comment by jackpoz** [comment]
Fixed 19 days ago https://github.com/TrinityCore/TrinityCore/commit/bf5be2839652e038eeb87c9fa301fd9dd6de8982 (cherrypicked from a commit from 2017 https://github.com/TrinityCore/TrinityCore/commit/925557d1c097cd45311b38dc3a9c715579456980 ).

Update to latest version.
