### ISSUE TITLE
[DB\Loot] Important Blackrock Documents

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#25162]
**Description:**

Important Blackrock Documents is a required Item from the Onyxia quest-chain on Horde side.
Currently, 8 creatures can falsely drop these items.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12562#dropped-by

**Expected behaviour:**

The Item should only be lootable from a gameobject inside Blackrock Spire.
https://classic.wowhead.com/item=12562/important-blackrock-documents#contained-in-object
As this is already given, we can delete the wrong loot entries.

Ref: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=4903
Ref: https://classic.wowhead.com/quest=4903/warlords-command

**SQL:**

```sql
DELETE FROM `creature_loot_template` WHERE `Reference`=0 AND `Item`=12562;
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

8a2c79c850199a73fd431d04f83d6aa89733060d

**Operating system:** --

**Comment by offl** [comment]
Or
```sql
DELETE FROM `creature_loot_template` WHERE `Reference`=0 AND `Item`=12562;
```

**Comment by Jinnaix** [comment]
True, i copy pasted the sql output without rewriting it - writing this issue nearly took me 30 minutes since i got distracted several times and by that nearly forgot to finish it.
