### ISSUE TITLE
Table 'world.creature_default_trainer' doesn't exist

### ISSUE THREAD

**Issue by CreepyCarrot** [TrinityCore/TrinityCore#25176]
**Description:**

[1146] Table 'world.creature_default_trainer' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
Server will not start up. 
Have tried recreating the whole database.
I will keep looking for a solution.

**Expected behaviour:**

Updated today (31-07-2020) and restarted server.

**Steps to reproduce the problem:**

1. Table 'world.creature_default_trainer' doesn't exist  
2. After update changed name to creature_trainer
3. 2020_07_31_04_world.sql changed the name

**Branch(es):**

master

**TC rev. hash/commit:** 

1340f2c

**Operating system:** Windows 10

**Comment by Aokromes** [comment]
are you sure you updated binaries?
the only ref to that table on sources now it's
 rgrep creature_default_trainer *
server/scripts/Commands/cs_reload.cpp:        handler->SendGlobalGMSysMessage("DB table `creature_default_trainer` reloaded.");

and it's cosmetic.

**Comment by CreepyCarrot** [comment]
Apologies.....
Fixed it....
Some idiot didnt update the binaries.
Thanks alot for the help.
