### ISSUE TITLE
DB/Item: Update item Moongraze Hide Boots to correct material

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#25171]
Moongraze Hide Boots currently has the wrong value of 7(cloth) while it's actually a leather item.

> ```sql
> UPDATE `item_template` SET `Material`='8' WHERE  `entry`=24103;

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ea6573489d41

**Comment by Aokromes** [comment]
for sure if you do that you will get one startup error.

**Comment by lingxDEV** [comment]
What's up? Why?

**Comment by lingxDEV** [comment]
> for sure if you do that you will get one startup error.

What's up? Why?

**Comment by lingxDEV** [comment]
I see the error on startup. I'm not sure how to fix that though. But surely, it needs to be updated in the DB, right? Probably some further fixes though.

**Comment by illfated** [comment]
Looks like it is currently shown as a Leather item in the game, at least if the DB lookup here shows the current TDB content:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=24103

The wiki (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130222/item+template#item_template-Material) indicates that it should be 8 instead of 7, but I don't know why that creates an error.

Could you post the error message here, to make more people aware of that issue?

**Comment by lingxDEV** [comment]
Yea sure, the error is the following:

> Loading Items...
> Item (Entry: 24103) does not have a correct material (8), must be 7 .

**Comment by Jinnaix** [comment]
The Material of this item is a dbc value and therefore retail.

![image](https://user-images.githubusercontent.com/37972361/88845747-e7cde300-d1e4-11ea-9ce0-255c1172e7a3.png)

It is shown as Leather ingame due to its subclass value (2).

**Comment by lingxDEV** [comment]
> The Material of this item is a dbc value and therefore retail.
> 
> ![image](https://user-images.githubusercontent.com/37972361/88845747-e7cde300-d1e4-11ea-9ce0-255c1172e7a3.png)
> 
> It is shown as Leather ingame due to its subclass value (2).

That makes sense. So this one is on Blizz then I guess :d

**Comment by Jinnaix** [comment]
Sidenote - The Material type is responsible for the soundeffect when you move that item around in your inventory. Cloth and Leather share the same sound effect, so it would not make any difference at all for this item.

https://db.project-nemesis.org/?item=24103/moongraze-hide-boots#sounds

**Comment by lingxDEV** [comment]
> Sidenote - The Material type is responsible for the soundeffect when you move that item around in your inventory. Cloth and Leather share the same sound effect, so it would not make any difference at all for this item.
> 
> https://db.project-nemesis.org/?item=24103/moongraze-hide-boots#sounds

Still, this is a bug. But a Blizzlike one, lol.

**Comment by Aokromes** [comment]
you cannot fix it without hacking dbc files.

**Comment by illfated** [comment]
> > Sidenote - The Material type is responsible for the soundeffect when you move that item around in your inventory. Cloth and Leather share the same sound effect, so it would not make any difference at all for this item.
> > https://db.project-nemesis.org/?item=24103/moongraze-hide-boots#sounds
> 
> Still, this is a bug. But a Blizzlike one, lol.

As a rule, TrinityCore prefers to keep Blizzlike bugs unchanged, unless they can be improved on in some way that won't change functionality much or create new bugs / errors.

**Comment by illfated** [comment]
(TrinityCore rev. c13ccaab5c70)

<details>
<summary>Details</summary>

TrinityCore rev. c13ccaab5c70 2020-10-08 20:36:50 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20091

</details>

I am guessing that the item "Arena Bracers" must stay as it is, but I was curious if someone could suggest why this item has got the **material ID 9** even though the table only goes to 8. The sound played when moving the item is the same as for Plate armor, instead of being Leather armor sound. I am also guessing that changing this value will cause a crash risk or other issues. Anyone got any ideas about this item and its details?

```sql
SELECT * FROM `item_template` WHERE `entry`= 18710; -- Arena Bracers (from the Gurubashi Arena chest)
```
```
entry   class  subclass  SoundOverrideSubclass  name           displayid  Quality  Flags  FlagsExtra  BuyCount  BuyPrice  SellPrice  InventoryType  AllowableClass  AllowableRace  ItemLevel  RequiredLevel  RequiredSkill  RequiredSkillRank  requiredspell  requiredhonorrank  RequiredCityRank  RequiredReputationFaction  RequiredReputationRank  maxcount  stackable  ContainerSlots  StatsCount  stat_type1  stat_value1  stat_type2  stat_value2  stat_type3  stat_value3  stat_type4  stat_value4  stat_type5  stat_value5  stat_type6  stat_value6  stat_type7  stat_value7  stat_type8  stat_value8  stat_type9  stat_value9  stat_type10  stat_value10  ScalingStatDistribution  ScalingStatValue  dmg_min1  dmg_max1  dmg_type1  dmg_min2  dmg_max2  dmg_type2   armor  holy_res  fire_res  nature_res  frost_res  shadow_res  arcane_res  delay  ammo_type  RangedModRange  spellid_1  spelltrigger_1  spellcharges_1  spellppmRate_1  spellcooldown_1  spellcategory_1  spellcategorycooldown_1  spellid_2  spelltrigger_2  spellcharges_2  spellppmRate_2  spellcooldown_2  spellcategory_2  spellcategorycooldown_2  spellid_3  spelltrigger_3  spellcharges_3  spellppmRate_3  spellcooldown_3  spellcategory_3  spellcategorycooldown_3  spellid_4  spelltrigger_4  spellcharges_4  spellppmRate_4  spellcooldown_4  spellcategory_4  spellcategorycooldown_4  spellid_5  spelltrigger_5  spellcharges_5  spellppmRate_5  spellcooldown_5  spellcategory_5  spellcategorycooldown_5  bonding  description  PageText  LanguageID  PageMaterial  startquest  lockid  Material  sheath  RandomProperty  RandomSuffix  block  itemset  MaxDurability  area  Map  BagFamily  TotemCategory  socketColor_1  socketContent_1  socketColor_2  socketContent_2  socketColor_3  socketContent_3  socketBonus  GemProperties  RequiredDisenchantSkill  ArmorDamageModifier  duration  ItemLimitCategory  HolidayId  ScriptName  DisenchantID  FoodType  minMoneyLoot  maxMoneyLoot  flagsCustom  VerifiedBuild
-----  ------  --------  ---------------------  -------------  ---------  -------  -----  ----------  --------  --------  ---------  -------------  --------------  -------------  ---------  -------------  -------------  -----------------  -------------  -----------------  ----------------  -------------------------  ----------------------  --------  ---------  --------------  ----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  -----------  ------------  -----------------------  ----------------  --------  --------  ---------  --------  --------  ---------  ------  --------  --------  ----------  ---------  ----------  ----------  -----  ---------  --------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  -------  -----------  --------  ----------  ------------  ----------  ------  --------  ------  --------------  ------------  -----  -------  -------------  ----  ---  ---------  -------------  -------------  ---------------  -------------  ---------------  -------------  ---------------  -----------  -------------  -----------------------  -------------------  --------  -----------------  ---------  ----------  ------------  --------  ------------  ------------  -----------  -------------
18710     4        2            -1              Arena Bracers    31159       3       0        0           1      36122       7224          9              -1              -1           50          45             0                 0                0               0                  0                   0                          0                  0         1            0              2           7          14            3           6            0           0            0           0            0           0            0           0            0           0            0           0            0           0            0            0                  0                      0             0         0         0          0         0         0         64       0         0          0          0           0           0        0        0            0             0            0               0               0               -1               0                   -1                  0            0               0               0                -1              0                     -1                0            0              0                0                -1               0                    -1                    0         0              0               0               -1                0                   -1                 0             0              0               0               -1                0                   -1                 2                     0          0            0            0         0        6        0           0              0         0       0           35         0    0       0            0              0              0                0              0                0               0              0             0                 150                      0               0             0              0                       46           0           0             0            0            12340
```


ID | Material | Comment
-- | -- | --
-1 | Consumables | Food, reagents, etc...
0 | Not Defined |  
1 | Metal |  
2 | Wood |  
3 | Liquid |  
4 | Jewelry |  
5 | Chain |  
6 | Plate |  
7 | Cloth |  
8 | Leather |  


(I posted here instead of opening a new issue, because I am guessing that this is not something we can change easily.

**Comment by offl** [comment]
SELECT material FROM `item_template` WHERE `entry`= 18710;
```text
material  
----------
         6

**Comment by illfated** [comment]
Ah, right. The value is the correct one if Plate armor and the sound of Plate armor was intended. Thank you. I must have been tired when I looked at the data.

Is this the same type of case as above, that the DBC file contains this data as well, so it will not be a good idea to change it?

**Comment by offl** [comment]
Idk

**Comment by illfated** [comment]
OK. Fair enough.
