### ISSUE TITLE
DB/Creature: Jammal'an the Prophet

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25206]
**Description:**

In the _Sunken Temple_ instance, you can fight the **Jammal'an the Prophet** even if you have not killed the six Trolls responsible for his protective force field, if there is any.

**Expected behaviour:**

According to [Wowhead](https://classic.wowhead.com/npc=5710/jammalan-the-prophet#comments:id=17087:~:text=Zul'lor%2C%20Gasher%2C%20Hukku%2C%20Loro%2C%20Zolo%2C%20and,protects%20the%20area%20Jammal'an%20resides%20in&text=After%20the%206%20trolls%20are%20defeated) comments, **Jammal'an the Prophet** should have a force shield, or the area he resides, that prohibits you to fight him if you have not fought and killed the six Troll Elites _Zul'Lor_, _Gasher_, _Loro_, _Zolo_, _Mijan_, and _Hukku_ first.

**Steps to reproduce the problem:**

1. `.go xyz -536.544128 -99.197144 -90.827904 109 0.265974`
2. Try to fight **Jammal'an the Prophet** without killing the six Troll Elites. There is no protective force field surrounding him or the area residing in, if there is any.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d974800e9d1e393ce3459ed8be4f4bd9defcc8f3

**Operating system:** Windows 7 Enterprise 64bit

**Comment by dr-j** [comment]
Seems bosses not defined for Sunken Temple and seems same as Dire Maul literally all bosses in sai cant fix this without bosses been defined in CPP seems only thing thats defined is statues event.
