### ISSUE TITLE
DB/Quest: Dungeon Set 2 Quest chain distribution & fix for current problems

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#25210]
**Description:**

The Dungeon Set 2 Quest Chain is partially broken for several classes after I See Alcaz Island In Your Future...

With major support from @offl we have been able to track the problem down to the NextQuestID value in several quests.

The following sql fix the remaining problems with this quest chain and therefore should enable all classes to finish it.
```sql
UPDATE `quest_template_addon` SET `NextQuestID`='0' WHERE  `ID` IN (8962,8963,8964,8965);
```
**Sidenote:**

While we currently have a class based quest distribution and a lot of old sources stating thats how it was, current guides state that the distribution of the 2*4 Components of Importance and the 4 More Components of Importance might be fully random.

See as ref a freshly written guide for:
https://classic.wowhead.com/guides/dungeon-set-2-quest-walkthrough-classic-wow

Video Refs:
https://youtu.be/g4KmP4o-FRA?t=1231

This topic might need further investigations.

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 53effff9b2ee6d9d1d24b293e8fc8e096f00febc

**Comment by offl** [comment]
Ok, written in 2010 so valid for 3.3.5, TBC or vanilla\classic
https://www.engadget.com/2010-09-24-collecting-armor-sets-dungeon-set-2-page-2.html
>Components of Importance/The Left Piece of Lord Valthalak's Amulet It's at this point in the chain that things get a little tricky. Bodley will randomly offer one of four quests that will require players to retrieve an item; this item will be used to fight a boss. Each item has a specific boss associated with it, but the item you are asked to get can be one of four possible items, chosen randomly:

>More Components of Importance Remember the randomly generated quest to get components? Right -- Bodley's going to do his divination spell thanks to your bloodkelp contribution, at which point he will pick another of the four "Components of Importance" quests for you to complete. The items and bosses are exactly the same as the four listed above, and whatever boss he chooses will drop the Right Piece of Lord Valthalak's Amulet this time around. Return the amulet to Bodley, and he will set about with the preparations for the final confrontation.

Gonna remove all unneeded stuff and try with pools, if it will not work as intended we have another unsupported scenario

**Comment by offl** [comment]
Heh
```text
Table `quest_pool_members` contains reference to quest 8986, which is neither daily, weekly nor monthly. Skipped.
```
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=lord+valthalak%27s+amulet#quests
Too should be randomly chosen but I wanted first to check if it works or not
```sql
-- Offer randomly one of Components of Importance / More Components of Importance
/* Source: https://www.engadget.com/2010-09-24-collecting-armor-sets-dungeon-set-2-page-2.html
Components of Importance/The Left Piece of Lord Valthalak's Amulet It's at this point in the chain that things get a little tricky.
Bodley will randomly offer one of four quests that will require players to retrieve an item; this item will be used to fight a boss.
Each item has a specific boss associated with it, but the item you are asked to get can be one of four possible items, chosen randomly.

More Components of Importance Remember the randomly generated quest to get components? Right -- Bodley's going to do his divination
spell thanks to your bloodkelp contribution, at which point he will pick another of the four "Components of Importance" quests for you
to complete. The items and bosses are exactly the same as the four listed above, and whatever boss he chooses will drop the Right
Piece of Lord Valthalak's Amulet this time around. 
*/
UPDATE `quest_template_addon` SET `AllowableClasses` = 0, `NextQuestID` = 0/*, `ExclusiveGroup` = 0*/ WHERE `ID` IN (8962,8963,8964,8965);
UPDATE `quest_template_addon` SET `AllowableClasses` = 0 WHERE `ID` IN (8985,8986,8987,8988);

DELETE FROM `quest_pool_template` WHERE `poolId` IN (371,372);
INSERT INTO `quest_pool_template` (`poolId`,`numActive`,`description`) VALUES
(371,1,"Components of Importance"),
(372,1,"More Components of Importance");

DELETE FROM `quest_pool_members` WHERE `poolId` IN (371,372);
INSERT INTO `quest_pool_members` (`questId`,`poolId`,`poolIndex`,`description`) VALUES
(8962,371,0,"Components of Importance"),
(8963,371,1,"Components of Importance"),
(8964,371,2,"Components of Importance"),
(8965,371,3,"Components of Importance"),
(8985,372,0,"More Components of Importance"),
(8986,372,1,"More Components of Importance"),
(8987,372,2,"More Components of Importance"),
(8988,372,3,"More Components of Importance");
```

**Comment by dr-j** [comment]
About Valthalak' think was many years ago but remember reading somewhere that this was class based to decide which quests are offered to player

**Comment by offl** [comment]
Maybe anyone wants to check it in classic but there's tons of quests before those class based \ pooled
We also need to know if blizzard uses pools for non-daily quests in master or 3.3.5, doesn't matter

And yes, we found tons of info that proves they're class-based. I need to check more info, but the thing is even videos are useless here if they're indeed pooled
Now I'm unsure if they're pooled, again

> and im sure that pre-cata wowhead used to show these quests as beenclass specific too

Found nothing here view-source:http://web.archive.org/web/20100508210340/http://www.wowhead.com/quest=8963

**Comment by dr-j** [comment]
https://vanilla-twinhead.twinstar.cz/?quest=8966 This says this one is mage/warrior

https://vanilla-twinhead.twinstar.cz/?quest=8967 Warlock/Druid

As said sure seen this before but no here

**Comment by offl** [comment]
It's private server DB, ours https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8966 will show the same
Currently classic wowhead does not show any class in those quests

**Comment by offl** [comment]
Rogue, fully matches with our currect class requirements https://youtu.be/3bWinhDyNAE?t=1172
He also said 10 times they're not random

**Comment by offl** [comment]
I checked all guides and only old (and new) videos of bosses are left. But I doubt we can trust videos with bosses because there 2 similar quests with one boss to kill and results may be not accurate because we can't know which quest player has (both quests are similar but class requirements are not).
Will check later.

**Comment by offl** [comment]
Class requirements for second quests may be messed up, https://www.youtube.com/watch?v=4hlS5smO2FA warrior but it's not a warrior quest. It's kinda unsolvable issue. Even if you check it in retail, how can you be sure they are based on class or they're random? In addition to complete at least first random\based on class quest you need to complete 20 previous quests.

And how can we be sure after checking videos that our based on comment from MoP class requirements are not messed up. I'm going to apply first suggested solution to make quests available for certain classes.
