### ISSUE TITLE
Sunreaver Guardian Mage

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#25211]
**Description:**

If you attempt to run into the horde-only area of Dalaran you will be teleported out and sometimes you will find yourself unable to move from the spot you have been teleported out to. When I try to walk away from the spot the Sunreaver Guardian Mage will teleport me back.

The only workaround is to mount up and run away before the NPC detects you again.

**Expected behaviour:**

You should only be teleported out of the horde-only area and not areas around you.

**Steps to reproduce the problem:**

1. Visit Dalaran
2. Attempt to enter the horde-only area.
3. Find that the Sunreaver Guardian Mage teleported you out and is teleporting you to the same spot regardless of you not entering the horde-only area again.

VIDEO: https://media.klodghirz.com/wow-bugs/videos/BUG1.mp4

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 00b16992f1ae 2020-07-18 21:34:45 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by TranceAccount** [comment]
Is the same happening with the alliance-only zone?

Problem is maybe in the npc script: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/zone_dalaran.cpp#L36

**Comment by TranceAccount** [comment]
I think the problem here is that the NPC that you have targeted in your video is facing in the wrong direction. Maybe somehow this mob has engaged some combat, but did not reset his 'facing' direction.

```cpp
if (GetClosestCreatureWithEntry(me, NPC_SWEETBERRY_H, 32.0f))
{
    if (me->isInBackInMap(who, 12.0f))   // In my line of sight, "outdoors", and behind me
    DoCast(who, SPELL_TRESPASSER_H); // Teleport the Alliance unit out
}
```

I am not able to reproduce it myself, since the NPCs are facing the correct way. (TrinityCore rev. 44a3aad0af4b 2020-08-06 00:20:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static))
Please look if there is a way to get these guards to face in the wrong direction (Maybe Distraction of rogues?).

**Comment by Aokromes** [comment]
cannot reproduce on 10f49793f9a7 with mmaps and vmaps enabled.

**Comment by TranceAccount** [comment]
Only hacky way to reproduce this is as follows:
1. `.cast 54029` on one of the sunreaver guards (basically the spell they use themselves)
2. Try to walk behind him

However, I do not think this is a completely valid way to reproduce the exact same bug. @LordWaycrest I really recommend finding the spell that can cause this, and afterwards maybe we can consider a soft reset of the npc or an additional immune mask.

**Comment by LordWaycrest** [comment]
> I think the problem here is that the NPC that you have targeted in your video is facing in the wrong direction. Maybe somehow this mob has engaged some combat, but did not reset his 'facing' direction.
> 
> ```c++
> if (GetClosestCreatureWithEntry(me, NPC_SWEETBERRY_H, 32.0f))
> {
>     if (me->isInBackInMap(who, 12.0f))   // In my line of sight, "outdoors", and behind me
>     DoCast(who, SPELL_TRESPASSER_H); // Teleport the Alliance unit out
> }
> ```
> 
> I am not able to reproduce it myself, since the NPCs are facing the correct way. (TrinityCore rev. [44a3aad](https://github.com/TrinityCore/TrinityCore/commit/44a3aad0af4bdd132b8761761dc83df2d7d6c601) 2020-08-06 00:20:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static))
> Please look if there is a way to get these guards to face in the wrong direction (Maybe Distraction of rogues?). Also consider updating your revision.

Yes, that is mainly what the issue is, sometimes when the NPC teleports you out of the area it can sometimes be facing the wrong way which leads to this bug and usually requires a server restart to reset it to its normal position.

Also I found another way to reproduce this is if you use some kind of speed such as an elixir, mount, etc. Also not to mention, this only happens now and then.

**Comment by dr-j** [comment]
think this is a old bug which randomly crops up every now and then (no idea why) and ye can happen for both factions.  but these guards may sometimes fail to teleport player (or with silver covenant ones anyway as if you make a horde character mount up and run into the inn at a angle ie not straight might take 2-3 attempts of trying to run straight back in after getting teleported as said seems to work more if you run in at a angle rather than in a straight line

**Comment by dr-j** [comment]
anyway this is related https://github.com/TrinityCore/TrinityCore/issues/23381 has teleport should be from trap not los from the guards

**Comment by LordWaycrest** [comment]
Brilliant, we sussed it out. Shall I close?

**Comment by Aokromes** [comment]
https://mega.nz/#!4noByJJT!w63l6IFAFYzQGBDcwcSJd3-MBwnfZBTTOQ0_oGvhylQ

**Comment by LordWaycrest** [comment]
Like @dr-j said, it is something that randomly crops up every now and then, I'll do some more looking into it and post my findings here.
