### ISSUE TITLE
DB/Texts: Wrong text word in a sentence in quest turn-in window of Proof of Deed quest

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25218]
**Description:**

The current sentence in the quest turn-in window of _Proof of Deed_ quest is **Why hello there young lady.**

![Screenshot](https://i.ibb.co/pXPxds0/Wo-WScrn-Shot-080620-185346.jpg)

**Expected behaviour:**

The correct one should be **Why hello there young _man_.**

[Wowpedia](https://wow.gamepedia.com/Proof_of_Deed_(quest)#Progress:~:text=Why%20hello%20there%20young%20man.).
[Wowhead](https://classic.wowhead.com/quest=3182/proof-of-deed).

**Steps to reproduce the problem:**

1. `.quest add 3182`
2. `.go creature id 8256`
2. Turn in the quest and check the text.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d974800e9d1e393ce3459ed8be4f4bd9defcc8f3

**Operating system:** Windows 7 Enterprise 64bit

**Comment by illfated** [comment]
Looks like there is a missing gender option in that gossip text.
Ref. https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3182/proof-of-deed
> **Progress**
> Why hello there young lady. Would you like a tour of the museum?

**Comment by illfated** [comment]
If it could be proven that the gossip should be gender adaptable, it would be possible to set the gossip text like this:
```sql
UPDATE `quest_request_items` SET `CompletionText` = "Why hello there young $g man : lady;. Would you like a tour of the museum?"
```
Then again, on one hand it looks like the current TC content is based on 12340 build content, on the other hand wowhead is only showing the male gender option.
I am not quite sure what to think about this detail.

**Comment by offl** [comment]
VerifiedBuild does not mean all fields in table are updated with sniffs. I found nothing with 'lady', only with 'man'
http://web.archive.org/web/20100809090806/www.wowhead.com/quest=3182
https://wow.gamepedia.com/index.php?title=Proof_of_Deed_(quest)&oldid=818585
https://www.wowhead.com/quest=3182/proof-of-deed
https://classic.wowhead.com/quest=3182/proof-of-deed

**Comment by illfated** [comment]
OK, fair enough. Thank you for looking into the details.

**Comment by illfated** [comment]
Thank you for selecting to use the gender alternative. I guess the reason why "man" is almost always seen in online references, is that 95% - 99% of the players who were checked out that quest chain were male players, while the TC sniff or source could have been playing a female one (and possibly not using sniff source, but just a screenshot or film clips).

**Comment by offl** [comment]
Texts were added in TBC and wowhead's TBC page was not archived and no longer available
