### ISSUE TITLE
Worldserver crashes with "Caught Signal 22"

### ISSUE THREAD

**Issue by BooneyNoobington** [TrinityCore/TrinityCore#25216]
**Description:**

Deviating from the official guide on Atlassian, I tried to use my self compiled OpenSSL and Boost libraries. I managed to compile TrinityCore (3.3.5) without errors after some adaptions in cmake which were:

LIB_EAY_DEBUG="S:/Installationsfrei/wowps/Dependencies/OpenSSL/Debug/lib/libcrypto.lib"
LIB_EAY_RELEASE="S:/Installationsfrei/wowps/Dependencies/OpenSSL/lib/libcrypto.lib"
SSL_EAY_DEBUG="S:/Installationsfrei/wowps/Dependencies/OpenSSL/Debug/lib/libssl.lib"
SSL_EAY_RELEASE="S:/Installationsfrei/wowps/Dependencies/OpenSSL/lib/libssl.lib"

I compiled OpenSSL two times. Once with and once without the "--debug" option. To Compile OpenSSL on Windows, I basically followed these instructions: https://stackoverflow.com/questions/45494630/how-to-build-openssl-on-windows-with-visual-studio-2017
But adapted to Visual Studio 2019.

Also, I used the .zip-File version of MySQL to avoid installing it.

**Expected behaviour:**

After testing the connection to the MySQL server, configuring worldserver.conf accordingly and starting worldserver.exe, the databases auth, world and character should be populated.

**Actual behaviour:**
worldserver.exe crashes with this error: "Caught Signal 22" (See also the crashlog at the end).

**Steps to reproduce the problem:**

1. Follow the steps described here: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130077/Installation+Guide
2. But compile OpenSSL and Boost from source.
3. Adapt setting in CMake.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 53effff9b2ee 2020-08-05 20:43:11 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**
Windows 10 64-bit (2004)

**Crashlog:**
https://pastebin.com/URUVuSJ5

**Comment by MaxtorCoder** [comment]
1. Please post the crashlog on Pastebin or some other fileservice, the log is long as fuck
2. Why the hell would you build Boost and OpenSSL when there are literally pre-built binaries for both of them :D

**Comment by jackpoz** [comment]
> Win64, RelWithDebInfo, Static)

could you rebuild in Debug and post the crashlog with that ?

**Comment by BooneyNoobington** [comment]
1. Done.
2. Hm... that's tricky. For a short answer, let's just say "OCD"
For a longer answer: I'm trying to do the installation as "portable" as possible. Meaning: Installing only Visual Studio if possible. MySQL, Git and HeidiSQL (as well as perl and NASM) are available as portable versions. For OpenSSL and Boost you need an installation.

**Comment by Carbenium** [comment]
@BooneyNoobington did you set the `MySQLExecutable` setting in your worldserver.conf? If yes, to what value?

**Comment by BooneyNoobington** [comment]
@jackpoz Okay, debug build complete. We have a new error message now:
(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.abort() has been calledCaught signal 22

**Comment by BooneyNoobington** [comment]
> @BooneyNoobington did you set the `MySQLExecutable` setting in your worldserver.conf? If yes, to what value?

That seemed to have been the problem:
Working value: "../MySQL/mysql-5.7.31-winx64/bin/mysql.exe"
Not working old value : ""../MySQL/mysql-5.7.31-winx64/bin""

**Comment by Carbenium** [comment]
Great. Let's keep this issue open until we add proper error handling for this case. That shouldn't crash the server but print an error message.

**Comment by BooneyNoobington** [comment]
> Great. Let's keep this issue open until we add proper error handling for this case. That shouldn't crash the server but print an error message.

I'm acutally surprised it never seemed to have happend. Maybe almost nobody set the value befor?

**Comment by Carbenium** [comment]
Under "normal" deployment conditions there is no need to set this variable since CMake detects the paths correctly.  Actually it should have done it in your case as well, otherwise CMake would have failed.

Could you try to remove the setting and check what happens? Also the value of the `MYSQL_EXECUTABLE` CMake variable might be of interest.

**Comment by BooneyNoobington** [comment]
In CMake the variable is:
MYSQL_EXECUTABLE="S:/Installationsfrei/wowps/Server/MySQL/mysql-5.7.31-winx64/bin/mysql.exe"
which should be correct.

I have started world- and authserver.exe without error after the fix. The weird thing: Now that all of the databases are up changes in the worldserver.conf don't seem to affect worldserver.exe and it starts correctly, even with the wrong previous value.

**Comment by Carbenium** [comment]
> In CMake the variable is:
MYSQL_EXECUTABLE="S:/Installationsfrei/wowps/Server/MySQL/mysql-5.7.31-winx64/bin/mysql.exe"
which should be correct.

Alright. Then you don't have to set the setting in the config file.

> I have started world- and authserver.exe without error after the fix. The weird thing: Now that all of the databases are up changes in the worldserver.conf don't seem to affect worldserver.exe and it starts correctly, even with the wrong previous value.

That is expected. It only tries to launch `mysql.exe` to import updates. Since there are none to import, nothing happens.

**Comment by illfated** [comment]
OK, good discussion everyone. I am just surprised nobody made even a mild joke about "Catch-22"... 😉

![Catch-22](https://user-images.githubusercontent.com/38162891/89639930-c6d55400-d8ae-11ea-9198-ff5df8b24135.jpg)

**Comment by BooneyNoobington** [comment]
Damnit, missed that one...
