### ISSUE TITLE
Core/Movement: RandomMovement does not work in water

### ISSUE THREAD

**Issue by akrom23** [TrinityCore/TrinityCore#25236]
**Description:**

RandomMovement does not work at all - mobs don't move in any direction.
Broken since https://github.com/TrinityCore/TrinityCore/commit/67d9d04d63cc74196059646b2e57f50a4a4fd2ca
It might be broken with flying units too.
The problem is that we check PATHFIND_FARFROMPOLY in some move generators but this flag is added to paths in water.

**Expected behaviour:**

**Steps to reproduce the problem:**
1. `.go creature 72179`

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 00b1699 2020-07-18 21:34:45 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

**Comment by Jinnaix** [comment]
For a easy ingame check, it would be nice if you list some steps for reproduction.
Like pointing to a specific creature guid or something like this.

**Comment by akrom23** [comment]
@Jinnaix Done

**Comment by Rushor** [comment]
@akrom23 are you still there? i need to ask you sth
