### ISSUE TITLE
[Bug Report: Plaguelands: The Scarlet Enclave]

### ISSUE THREAD

**Issue by LordWaycrest** [TrinityCore/TrinityCore#25230]
**Description:**

A bug is causing flickering between normal phase and ghost phase in Plaguelands: The Scarlet Enclave as a ghost. A video is attached below showing the behaviour.

https://media.klodghirz.com/wow-bugs/videos/2.mp4

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 00b16992f1ae 2020-07-18 21:34:45 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows Server 2016 Standard

**Comment by dr-j** [comment]
is there anything else you need to reproduce this like certain quest in quest log as cant reproduce started dead from crypt of rememberence (same place where you started) and took same path as ghost but did not encounter the problem you descript stayed as ghost this was on a brand new dk character which had not done any quests yet

**Comment by LordWaycrest** [comment]
> is there anything else you need to reproduce this like certain quest in quest log as cant reproduce started dead from crypt of rememberence (same place where you started) and took same path as ghost but did not encounter the problem you descript stayed as ghost this was on a brand new dk character which had not done any quests yet

Oh forgot to mention, it is the part where the sky turns orange which I think is the quest An Attack Of Opportunity, Victory At Death's Breach! or The Will Of The Lich King

**Comment by Jinnaix** [comment]
Valid, i encountered the same 2 weeks ago as i tested the deathknight for the first time in ages but i forgot to take notes about this.
Same can happen in the final mission too.

**Comment by LordWaycrest** [comment]
> Valid, i encountered the same 2 weeks ago as i tested the deathknight for the first time in ages but i forgot to take notes about this.
> Same can happen in the final mission too.

Yeah I was supposed to submit a bug report a while ago but coronavirus got in the way.

**Comment by dr-j** [comment]
In spell area for this zone there are a couple of spells which set skybox once progressed through certain quest when you die this also sets a skybox or the grey swirls in sky maybe some spell/s is casted while dead when shouldn’t

**Comment by offl** [comment]
More info in #25931
Would be nice if we will have detailed repro steps

**Comment by illfated** [comment]
> Would be nice if we could have detailed repro steps

Indeed. Detailed steps on how to reproduce/replicate the issue is always useful and makes it more likely that more users will test and post results from their testing.

**Comment by GitGoppy** [comment]
Ok, found the graveyard ID's:
Phase 1:  1360
Phase 2&3 :1370
Phase 4: 1371 

The phase 2&3 graveyard lacks spirit healer
Teleport to it and commit suicide which should ghost spawn you in the broken graveyard and you won't be able to find the spirit healer

**Comment by mdX7** [comment]
Spirithealer @ Crypt of Rememberance
(Shadowlands columns)
```sql
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `PhaseId`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29259, 609, 4298, 4355, '0', '171', 0, 0, 0, 1887.4288330078125, -5776.158203125, 106.630828857421875, 4.660028934478759765, 120, 0, 0, 2165, 0, 0, 0, 0, 0, 37176), -- 29259 (Area: 4355 - Difficulty: 0) (Auras: 9036 - 9036; 10848 - 10848)
```

**Comment by offl** [comment]
Looks like all we need is
```sql
UPDATE `creature` SET `phaseMask` = 171 WHERE `guid` = 125672 AND `id` = 29259;
```

**Comment by offl** [comment]
About main issue: it's a generic issue since
.go x 2031.164551 5942.007813  43.822845 571 3.109828
.die
release spirit
.go x 1988.378662 5949.388184  37.333443 571 3.209573
same result

Moreover
now
.go x 1992.147705  5943.969727  37.838104 571 5.632525
resurrect menu opens, try to resurrect
nothing happens, you can't resurrect
now go
.go x 2031.164551 5942.007813  43.822845 571 3.109828
try to resurrect again
works

**Comment by offl** [comment]
> Ok, found the graveyard ID's:
> Phase 1: 1360
> Phase 2&3 :1370
> Phase 4: 1371
> 
> The phase 2&3 graveyard lacks spirit healer
> Teleport to it and commit suicide which should ghost spawn you in the broken graveyard and you won't be able to find the spirit healer

Ok, I checked all spells and their phases
```sql
SELECT * FROM spell_area WHERE AREA=4298
```

1370
```sql
UPDATE `creature` SET `phaseMask` = 1+2+4+32+64+128 WHERE `guid` = 125672 AND `id` = 29259;
```
1371
```sql
UPDATE `creature` SET `phaseMask` = 1+2+4+32+64+128 WHERE `guid` = 125673 AND `id` = 29259;
```
We can also add same phasemask to 1360 if needed or remove some of them if needed
What do you think, @GitGoppy?

**Comment by Aokromes** [comment]
> About main issue: it's a generic issue since
> .go x 2031.164551 5942.007813 43.822845 571 3.109828
> .die
> release spirit
> .go x 1988.378662 5949.388184 37.333443 571 3.209573
> same result (character casts area spell and 'normal world' visually replaces 'ghost world')
> 
> Moreover
> now
> .go x 1992.147705 5943.969727 37.838104 571 5.632525
> resurrect menu opens, try to resurrect
> nothing happens, you can't resurrect
> now go back to 'ghost world' (lose area spell)
> .go x 2031.164551 5942.007813 43.822845 571 3.109828
> try to resurrect again
> works
> 
> So yeah, looks like we don't need to cast area spells if player is in ghost form. Or maybe we shouldn't cast certain spells
> Not sure what is the more correct way to fix it

maybe every spirit healer must be on every phase.

**Comment by offl** [comment]
In the case I tested there is no other phase

**Comment by GitGoppy** [comment]
> > Ok, found the graveyard ID's:
> > Phase 1: 1360
> > Phase 2&3 :1370
> > Phase 4: 1371
> > The phase 2&3 graveyard lacks spirit healer
> > Teleport to it and commit suicide which should ghost spawn you in the broken graveyard and you won't be able to find the spirit healer
> 
> Ok, I checked all spells and their phases
> 
> ```sql
> SELECT * FROM spell_area WHERE AREA=4298
> ```
> 
> 1370
> 
> ```sql
> UPDATE `creature` SET `phaseMask` = 1+2+4+32+64+128 WHERE `guid` = 125672 AND `id` = 29259;
> ```
> 
> 1371
> 
> ```sql
> UPDATE `creature` SET `phaseMask` = 1+2+4+32+64+128 WHERE `guid` = 125673 AND `id` = 29259;
> ```
> 
> We can also add same phasemask to 1360 if needed or remove some of them if needed
> What do you think, @GitGoppy?

This Fixed the Spirit Healer
But the sky still isn't fixed.

**Comment by offl** [comment]
Then I'll just add phases to all 3 spirit healers so they will be available in any phase

**Comment by offl** [comment]
Migrated to #25996
