### ISSUE TITLE
DB/Texts: Instructor Razuvious

### ISSUE THREAD

**Issue by TranceAccount** [TrinityCore/TrinityCore#25257]
**Description:**

There is some strange spacing between the texts of Instructor Razuvious.

As already shown in #25254 and reuploaded again here:

![figure](https://user-images.githubusercontent.com/13118481/90335645-9f7d3600-dfd6-11ea-8513-c5d908496c12.png)

**Expected behaviour:**

These blank lines in the chat should not be present.

Edit: After applying the SQL below it looks like this:

![figure1](https://user-images.githubusercontent.com/13118481/90336438-3698bc80-dfdc-11ea-8751-d7cc7d0d8673.png)

**Steps to reproduce the problem:**

1. `.go cr id 28357` or make new DK.
2. Wait for him to start saying gossips (go afk for a minute or 2).
3. Observe the some of his texts having an extraordinary spacing between the others.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5e40eb2

**Operating system:**

Windows 10 Home

**Fix:**

```sql
UPDATE `creature_text` SET `Text` = "This one..." WHERE `CreatureID` = 28357 and `GroupID` = 0 and `ID` = 0;
UPDATE `creature_text` SET `Text` = "Dispose of it..." WHERE `CreatureID` = 28357 and`GroupID` = 6 and `ID` = 0;
UPDATE `creature_text` SET `Text` = "You have been measured and found wanting..." WHERE `CreatureID` = 28357 and `GroupID` = 5 and`ID` = 0;
UPDATE `creature_text` SET `Text` = "Stand and be measured! Rise, for your master awaits your arrival. Go now!" WHERE `CreatureID` = 28357 and `GroupID` = 3 and`ID`=0;
UPDATE `creature_text` SET `Text` = "Place upon it the trappings befitting a herald of Arthas." WHERE `CreatureID` = 28357 and `GroupID` = 2 and`ID` = 0;

UPDATE `broadcast_text` SET `Text` = "This one..." WHERE `ID` = 27876;
UPDATE `broadcast_text` SET `Text` = "Place upon it the trappings befitting a herald of Arthas." WHERE `ID` = 27873;
UPDATE `broadcast_text` SET `Text` = "Stand and be measured! Rise, for your master awaits your arrival. Go now!" WHERE `ID` = 27883;
UPDATE `broadcast_text` SET `Text` = "Listen, death knight... Listen for the voice of your master. He calls to you now.", `Text1` = "Listen, death knight... Listen for the voice of your master. He calls to you now." WHERE `ID` = 27884;
UPDATE `broadcast_text` SET `Text` = "You have been measured and found wanting..." WHERE `ID` = 27866;
UPDATE `broadcast_text` SET `Text` = "Dispose of it..." WHERE `ID` = 27867;
```

**Comment by Aokromes** [comment]
altering broadcast_text is hack

**Comment by TranceAccount** [comment]
Well, only changing the creature_text does not work. On the wiki it says adding things is not allowed, this is modifying.

**Comment by TranceAccount** [comment]
Nevermind, it is blizzlike apparently.
https://www.youtube.com/watch?v=U7SJb6XRRaw look at chat

**Comment by offl** [comment]
If you want to edit text, set BroadcastTextId to 0 and update creature_text. But it removes all locales and I recommend to not do such things to make cosmetic changes like removing extra spaces or adding missing comma because (spoiler) hundreds and thousands of texts does not match texts from 3.3.5 because we use texts from broadcast_text and they are from Cata+ so multiple cosmetic changes were done to tons of texts.

It will just turn to mass update of more than thousand texts and we will lose all locales.

**Comment by illfated** [comment]
Most of the TDB contents in `broadcast_text` is brute-forced data from patch 5.4.7 (build 18019).
