### ISSUE TITLE
WorldServer crashed on enter Instances

### ISSUE THREAD

**Issue by AsoraXDev** [TrinityCore/TrinityCore#25252]
**Description:**

If player / groups enter Instances like RagefireChasm, the world server crashes.

Comment: 
In the previous Build (with DB TDB 830.20061) used with solocraft, i was able to see the Creatures inside the Instance. This is now not possible!? (See Video below)

**Steps to reproduce the problem:**
Compile Clean TC
Get Level 10
Move to Orgrimmar
Enter Ragefire

-> Not Working for most Classic & BC Dungeons

**Branch(es):**
master

**TC rev. hash/commit:**
TrinityCore rev. f4b4425862da 2020-08-14 21:46:30 +0000 (master branch) (Win64, RelWithDebInfo, Static)

**Operating system:**
Windows 10 x64 Version 2004 (Build 19041.329)

**Others:**

**Links:**
CrashLog:  https://gist.github.com/AsoraXDev/b936428defc8c5cd85a1d530a5105e7b or https://drive.google.com/drive/folders/1J7MIbiGdypCPR6ofzcnXMEpPv5_1BbEY?usp=sharing
ErrorLog: https://pastebin.com/FxheBHzd
Video: https://www.youtube.com/watch?v=_D_sLvX3QtM

**Comment by AsoraXDev** [comment]
Fixed in current AshamaneCore... May it helps

https://github.com/AshamaneProject/AshamaneCore/issues/258

**Comment by Shauren** [comment]
its fixed
