### ISSUE TITLE
Warlock can not summon any pets

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#25265]
**Description:**

Warlock can not summon any pets after he dismiss the first pet.
I think commit 5c1fc5e3876549f5ed2b9051fffb6f3d94a67d7a cause this problem.

**Steps to reproduce the problem:**

1. Create a new warlock.
2. Summon an Imp and dismiss it.
3. Try summon Imp or other pets.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a9d493c4564cdaa7efe400408f3582f1cdbb8cde 2020-08-17 12:46:30 +0800 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** 
Win 10

**Comment by shenhuyong** [comment]
Now warlock can not do summon spells if he has summoned a pet, I'm sure warlocks can summon pets when they has summoned a pet in offical server.

**Comment by shenhuyong** [comment]
And I found warlock can not summon pets when they had a first pet.
When a warlock summoned first pet, e.g. Imp, then he can not summon other pets, becaus it's breaks on line 5766 in spell.cpp 'if (!info.first)';

**Comment by shenhuyong** [comment]
@Shauren

**Comment by Shauren** [comment]
bbcf00257ebdb75fa30f0484cb185058139f8ae4

**Comment by shenhuyong** [comment]
@Shauren I found a new problem about spells of pets, I opened a new issue https://github.com/TrinityCore/TrinityCore/issues/25269.
