### ISSUE TITLE
Crash related with spell_the_lich_king_necrotic_plague_jump

### ISSUE THREAD

**Issue by Idoitbetter** [TrinityCore/TrinityCore#25268]
**Description:**

Crashlog: https://gist.github.com/Idoitbetter/04160d4958c3ce13e9d942a8ce8ad683

This crash has happened to me on 2 occasions, on both occasions the server has been a few minutes without responding and appear ```spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::AfterDispel``` on both, however, it has not executed the MaxCoreStuckTime, which I have set to 300 (5min)
https://i.imgur.com/G3WQFS9.png

**Steps to reproduce the problem:**

1. I don't know how to reproduce it, I don't understand it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

43986954fddc05e0fe1f225b0cf38a7b01f775bb

**Operating system:** Debian10

**Comment by jackpoz** [comment]
The spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=70338 is jumping back and forth between 2 targets

**Comment by Jildor** [comment]
I think I found the problem, but I'm not sure, I think if you log two players and use .aura 70338 in two players and repeat you can freeze it

**Comment by jackpoz** [comment]
@Jildor did you get any freeze detector crash during your attempts ?

**Comment by Jildor** [comment]
Not really, I only managed to cause some freeze by doing the idiot in the code to see what happened, but without modifying the code I was not able

**Comment by jackpoz** [comment]
did this freeze happen again ?

**Comment by Aokromes** [comment]
no crash for me after months.

**Comment by Idoitbetter** [comment]
I close, I have not had this crash again

**Comment by illfated** [comment]
Thank you for closing and with feedback.
