### ISSUE TITLE
DB/SAI: Remove unnecessary setactive in DK start zone

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25278]
**Fix:**

```sql
-- Instructor Razuvious Event
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2835700,2835701,-129391,12939100,-129390,12939000,28391) AND `action_type`=48;
-- Instructor Razuvious SAI
UPDATE `smart_scripts` SET `id`=0 WHERE `entryorguid`=2835700 AND `id`=1 AND `source_type`=9;
UPDATE `smart_scripts` SET `id`=1 WHERE `entryorguid`=2835700 AND `id`=2 AND `source_type`=9;
UPDATE `smart_scripts` SET `id`=0 WHERE `entryorguid`=2835701 AND `id`=1 AND `source_type`=9;
UPDATE `smart_scripts` SET `id`=1 WHERE `entryorguid`=2835701 AND `id`=2 AND `source_type`=9;
-- Acherus Necromancer SAI
UPDATE `smart_scripts` SET `link`=0 WHERE `entryorguid`=-129391 AND `id`=0 AND `link`=1 AND `source_type`=0;
UPDATE `smart_scripts` SET `link`=0 WHERE `entryorguid`=-129390 AND `id`=0 AND `link`=1 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=29 WHERE `entryorguid`=12939100 AND `id`=30 AND `source_type`=9;
-- Death Knight Initiate SAI
UPDATE `smart_scripts` SET `link`=0 WHERE `entryorguid`=28391 AND `id`=1 AND `link`=6 AND `source_type`=0;

-- Gothik the Harvester Event
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (28890,28906,28897) AND `action_type`=48;
-- Scourge Gryphon SAI
UPDATE `smart_scripts` SET `id`=0,`event_type`=38,`event_param1`=1,`event_param2`=1 WHERE `entryorguid`=28906 AND `id`=1 AND `event_type`=61 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=1 WHERE `entryorguid`=28906 AND `id`=2 AND `event_type`=34 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=2,`event_type`=38,`event_param1`=2,`event_param2`=2 WHERE `entryorguid`=28906 AND `id`=4 AND `event_type`=61 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=3 WHERE `entryorguid`=28906 AND `id`=5 AND `event_type`=34 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=4 WHERE `entryorguid`=28906 AND `id`=6 AND `event_type`=63 AND `source_type`=0;
-- Scarlet Ghoul SAI
UPDATE `smart_scripts` SET `id`=0 WHERE `entryorguid`=28897 AND `id`=1 AND `event_type`=54 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=1,`link`=2 WHERE `entryorguid`=28897 AND `id`=2 AND `event_type`=54 AND `source_type`=0;
UPDATE `smart_scripts` SET `id`=2 WHERE `entryorguid`=28897 AND `id`=3 AND `event_type`=61 AND `source_type`=0;
```
Updates: #24356

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/43986954fddc05e0fe1f225b0cf38a7b01f775bb

**Comment by dr-j** [comment]
Why was set active used in these scripts should not be used in scripts where scripts spawn npcs where a build up of npcs may occur if not set active or to ensure a npc resets correctly after running a script ie if unit flags, npc flags, faction, etc are changed to ensure reset back at end of script as if grid unloads may leave a npc uninteroperable until either killed (may require gm) or server restart or for npcs involved with game events to ensure event runs at correct time and event completes

**Comment by Jildor** [comment]
When you set a SetActive, you have to make sure that that npc will despawn after a while, or remove SetActive when a time has passed or the script has completed, otherwise, it remains always active and the scripts continue to run even if there are no players nearby. impairs performance

And from what I see there may be many more like that in Northrend and maybe Kalimdor / Eastern kingdoms

**Comment by dr-j** [comment]
ye thats usually the case there are a few examples where this is used to ensure that build up of temp summoned npcs does not occur like for example recruitment officer carven/civilian recruits which can get messy if not set active or dragommaw transporters , love boats, etc again these can build up in areas they enter if grid is not loaded etc
