### ISSUE TITLE
Yellow gear problems

### ISSUE THREAD

**Issue by calaluis** [TrinityCore/TrinityCore#25274]
**Description:**

Find at the time of detection, in which items of yellow equipment are linked with other items. If the item linked to the yellow team is deleted, both are deleted.

**Expected behaviour:**

It is expected that the items preserve their unique identity, as it is shown both in the character's equipment and in the inventory.

**Steps to reproduce the problem:**

1. Video 1: https://youtu.be/qHo3snJXdig
2. Video 2: https://youtu.be/A2Q0LpUfzaI

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3ba563acce3afe8333c8601f9f1454bb5fade562

**Operating system:** 

Windows Server 2016

**Comment by TranceAccount** [comment]
Heirloom/Account bound gear problem.
Are you sure this is not a problem with your addon (e.g. tried it with disabled addon in your 'normal' backpack)?

**Comment by calaluis** [comment]
> Heirloom/Account bound gear problem.
> Are you sure this is not a problem with your addon (e.g. tried it with disabled addon in your 'normal' backpack)?

Hello,

The addon that I use for the inventory is the same one that I have used for 10 years ago. It would be very rare for that addon to fail and cause that problem (it has never happened to me before).

Anyway, I will have to try again auto-sending the welcome pack with the yellow team (MySQL query created by me two years ago that sends mail with the attached items is executed), and disable all the addons that I use, and then test its behavior.

**Comment by Shauren** [comment]
It seems you are attempting to externally insert items directly into database of a running server. This is not supported and WILL DEFINITELY BREAK.

**Comment by illfated** [comment]
The 2 heirloom items you have shown in the videos are standard heirloom items, they are easy to access as GM or admin, and do not appear to cause any issues when acquired normally, so it is likely that the issue is **how** the items are provided to the player character (the scripting).
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=42985/tattered-dreadmist-mantle
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=42992/discerning-eye-of-the-beast

**Comment by calaluis** [comment]
> It seems you are attempting to externally insert items directly into database of a running server. This is not supported and WILL DEFINITELY BREAK.



> The 2 heirloom items you have shown in the videos are standard heirloom items, they are easy to access as GM or admin, and do not appear to cause any issues when acquired normally, so it is likely that the issue is **how** the items are provided to the player character (the scripting).
> 
> * https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=42985/tattered-dreadmist-mantle
> * https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=42992/discerning-eye-of-the-beast

The explanation is appreciated to both.

I did not know that making database inserts to the characters.mail tables, characters.item_instance table, and `characters``mail_items` table was prohibited. I had done a whole construction in C # .NET (MVC web application) to incorporate welcome pack functionality for new players.

You learn something new every day.

**Comment by illfated** [comment]
Thanks for the extra details and feedback. I would like to emphasize that it is not _prohibited_ per se. The method is **unsupported** and will cause unwanted behaviour in-game.
