### ISSUE TITLE
[3.3.5] Druid models forms bug

### ISSUE THREAD

**Issue by reforgednt** [TrinityCore/TrinityCore#25287]
**Description:**

druid model forms not saved

**Expected behaviour:**

Must be saved all models form,form work but not model.

**Steps to reproduce the problem:**

1. CHANGE any form on druid 
2. logout
3. login
4. bug

**Branch(es):**

 3.3.5, 

**TC rev. hash/commit:** 

TrinityCore rev. 00b1699 2020-05-13 19:51:23 +0200 (3.3.5 branch) 

**Operating system:** w7

**Comment by Treeston** [comment]
Cannot reproduce on latest (4286e7aa02e7):

![record](https://user-images.githubusercontent.com/14020072/90702281-2823fc80-e28b-11ea-9627-91b0c0e0e5f6.gif)
