### ISSUE TITLE
DB/Creature: Infiltrator Minchar

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#25281]
**Description:**
[Infiltrator Minchar](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=38558) is spawned in db but falls to ground, not hovering.

**Expected behavior:**
[Infiltrator Minchar](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=38558) should be hovering in air.

**Steps to reproduce the problem:**

1. use any high lvl char  
2. .gm ON and set dungeon 25man
3. .go creature id 38558
4. and will see that [Infiltrator Minchar](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=38558) will fall to ground and stay there

**Branch(es):**
3.3.5
**TC rev. hash/commit:** 
6c7837f947ff4eb5110a116a371daa6f9e2b3bbe

**Operating system:** 
w7

![image](https://user-images.githubusercontent.com/322016/90563493-9940b280-e1ac-11ea-94e7-19648039ef0c.png)

**Comment by Faq** [comment]
warpten mentioned that need `creature_template_addon entry with bytes1 set properly (from sniffs)`

**Comment by Ovahlord** [comment]
no, it's template movement = DisableGravity that's required here, not   CanFly. Read your sniffs, bois

**Comment by Shauren** [comment]
@Ovahlord there arent any sniffs of this guy

**Comment by Warpten** [comment]
Is this a result of the anim tier pr or has he been broken before that

**Comment by offl** [comment]
Probably you need to change script too because only SetCanFly is removed in script and not DisableGravity
https://github.com/TrinityCore/TrinityCore/blob/c46aa9d5b52486aba68e3827ee7263ddf6e2a323/src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp#L208-L221

**Comment by Faq** [comment]
dad187615df603ad8614531a0ec84c1a5e136838
