### ISSUE TITLE
Pets don't resurrect in battleground graveyards

### ISSUE THREAD

**Issue by shenhuyong** [TrinityCore/TrinityCore#25289]
**Description:**

Pets don't resurrect when players are revived in battleground graveyards.
I think commit 5c1fc5e3876549f5ed2b9051fffb6f3d94a67d7a cause this problem.
Line 215 in pet.cpp 'Pet::LoadPetFromDB()' always return false then it breaks the spell_gen_pet_summoned() in spell_generic.cpp (Spell Id: 6962).

**Expected behaviour:**

Pets should be revive when players are revived in battleground graveyards.

**Steps to reproduce the problem:**

1. Hunter or Warlock go into a battleground.  
2. Summon a pet and use .die to kill your self.
3. Resurrect in a battleground graveyard.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 7bfeb03c136f18fda73474054c837f4fe8f11136 2020-08-20 18:06:30 +0800 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** 
Win10

**Comment by shenhuyong** [comment]
@Shauren Please take a look.

**Comment by MaxtorCoder** [comment]
Imagine pinging Shauren after 2 minutes >_> Please just be patient.
