### ISSUE TITLE
Npc 3701 where completition quest 2118 cant take new quests

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#25313]
.go creature 37294
.take quest 2118 and finished it
.rewarded this quest can´t take new quest.

1. delete all smart scripts from npc 3701 
2. he's go in atackmode and can´t take new quests in this mode

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

ed4788190d52f8739b89fe2e4ef1a5e991631077

**Operating system:** windoof 7

**Comment by illfated** [comment]
TrinityCore rev. a41bbd9ad9ad 2020-08-23 00:31:57 +0200 (3.3.5 branch) (Win64, Release, Static)

Confirmed. Tharnariun Treetender (NPC entry 3701) is standing in some sort attack stance, the one used to cast the spell visual. He does not return to being interactive.

![WoWScrnShot_082320_201757](https://user-images.githubusercontent.com/38162891/90985887-14c0ac00-e57f-11ea-9cb7-83d81a182e07.jpg)

The following events take place:
1. Tharnariun Treetender enters his attack stance (spellcast stance?)
2. Tharnariun Treetender says: Be cleansed!
3. Tharnariun Treetender casts a spell visual (renew or heal)
4. Captured Rabid Thistle Bear turns Aggressive towards Tharnariun Treetender.
5. Auberdine Sentinels nearby attack Captured Rabid Thistle Bear and kill him.
6. Tharnariun Treetender stays in his stance and **does not** return to being interactive.

**Comment by illfated** [comment]
**Update:**

**Tharnariun Treetender becomes interactive after logging out and logging in again**, at least including a game client restart. Just tested exit game and start game again (not the servers).


![WoWScrnShot_082320_203658](https://user-images.githubusercontent.com/38162891/90986135-d7f5b480-e580-11ea-82e2-ab169843ea6f.jpg)

**Comment by illfated** [comment]
Just out of curiosity, could this have anything to do with any of the latest changes in `SmartScript.cpp` or related files?

**Comment by genion18** [comment]
Yes and the not interactive is not right and blizzlike. Some player are in this map for questing and have this "!" and no interactive to the NPC.

Tharnariun Treetender becomes interactive after logging out and logging in again is the not better way.

**Comment by illfated** [comment]
OK, fair enough. Thanks for reminding me that removing SAI does not help. Something sets the NPC as not clickable. I don't know what that could be, maybe we need to look at the **Captured Rabid Thistle Bear**  instead to see if something in its script can cause 3701 to become stuck in a situation that looks like `UNIT_FLAG_IMMUNE_TO_PC` is applied to NPC 3701.

**Comment by genion18** [comment]
My test deletes:

> DELETE FROM `smart_scripts` WHERE `entryorguid`=3701; -- The NPC
> DELETE FROM `smart_scripts` WHERE `entryorguid`=370100 AND `source_type`=9;
> DELETE FROM `smart_scripts` WHERE `entryorguid`=2164; -- The Bear
> DELETE FROM `smart_scripts` WHERE `entryorguid`=216400 AND `source_type`=9;
> DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`='13' and SourceGroup = 1 and SourceEntry = 9457;
> DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`='22' and SourceGroup = 3 and SourceEntry = 3701;

After this the same problem.

**Comment by illfated** [comment]
That should mean that the SAI does not add the problem, but something else is missing in the scripting or core to make the NPC turn back to being interactive (or leave the script, if the NPC is stuck at the end of the script).

**Comment by Aokromes** [comment]
cannot reproduce with a lvl 80 char...

https://i.imgur.com/IpbnPd9.jpeg

**Comment by illfated** [comment]
Core revision hash, please? (Going to test this when I get home, also with a different race than a Night Elf (like you did).

**Comment by illfated** [comment]
BTW, I wonder if this could have anything to do with addons. I forgot to test without my addons, and at least one of them causes lag on quest update.

**Comment by offl** [comment]
You can interract with him, for some reason he just changes orientation and emote state instantly after turning in quest but you still can pick up new quest. I've seen it also in some videos from private servers so it's something old.
I removed the script and AIName and the result was the same.

**Comment by genion18** [comment]
When you completition the Quest 2118 goes the Questmanager to quest 2138.

The questmanager start the Emote from:

> INSERT INTO `quest_details` VALUES ('2138', '274', '0', '0', '0', '0', '0', '0', '0', '0');

when this 0 is is the emote deleted and the char not in this form

> INSERT INTO `quest_details` VALUES ('2138', '0', '0', '0', '0', '0', '0', '0', '0', '0');

**Comment by offl** [comment]
274 is EMOTE_ONESHOT_NO and the emote he plays is EMOTE_ONESHOT_READY_UNARMED (44)
It also does not explain why he changes orientation and loses gossip interraction icon

**Comment by Faq** [comment]
Removed SmartAI from that npc and then did some packet logging. Where delivered quest, closed gossip and took next q. https://gist.github.com/Faq/11ff81cef1c51c7564888dc136346799

When accepting next q in chain, got:
```
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at WowPacketParser.Misc.Packet.ReadUInt32(String name, Object[] indexes) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\PacketReads.cs:line 376
   at WowPacketParser.Parsing.Parsers.QuestHandler.HandleQuestgiverDetails(Packet packet) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Parsers\QuestHandler.cs:line 877
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\projects\wowpacketparser-191\WowPacketParser\Parsing\Handler.cs:line 149
```

**Comment by Carbenium** [comment]
be73959a0d838f71f9ff995486479fdffb7ab013
