### ISSUE TITLE
Core/SAI: Request - SAI Action to modify a creatures current HP

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#25317]
**Description:**

As i was recently checking some Scholomance creatures, i stumbled over creature [Reanimated Corpse](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10481).

Retail behavior:
After this creature is damaged down to 1 hp, it goes down on the floor for 15 seconds, than it rises up once again to continue the fight. If its beaten up once again, it dies.
See for reference: https://www.youtube.com/watch?v=s-2GXud7CJI&feature=youtu.be&t=339

While it being invincible on the ground, it can still be targeted and hit by players. It also keeps players in combat for that time.

For SAI at the moment, 1 things are missing/needed here:

~~Addition to action:
SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL - this action cant be removed after it was set once. Since we cant work with Evade in this case (creature has to store its aggro list), we need the option to add/remove invincibility on demand instead of just set it active till the creature evades.~~

^It seems like we already can do this - thanks @dr-j for pointing this out.

Missing action:
SMART_ACTION_SET(_CURRENT?)_HEALTH - i might be wrong in this creatures case since i dont have any sniffs from it, maybe there is a spell that set its health back to full. But anyway, we dont have a single action that can modify a creatures health at all. In my opinion we need an action that can either set the creatures current health to a specific value via param1 and maybe to the creatures maxhealth via param2=1 if param1 is 0.

Or as a variant - set to % instead of absolut value.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

7cdc4b46bb6ce63ae3830fb1f8e0464093e1a015

**Comment by offl** [comment]
> SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL - this action cant be removed after it was set once. Since we cant work with Evade in this case (creature has to store its aggro list), we need the option to add/remove invincibility on demand instead of just set it active till the creature evades.

Yes, it's needed also for safety reasons because sometimes we need to remove invincibility in order to make creature killable if event fails

**Comment by dr-j** [comment]
Invincibility can be removed , param1=0 param2=0  mogor (ring of blood) is already using similar to ressurect

**Comment by dr-j** [comment]
Or we just need action to reset hp without calling evade if npc must stay in combat

**Comment by dr-j** [comment]
Upon reaching 1hp this is what happens

~~~
ServerToClient: SMSG_ATTACK_STOP (0x0144) Length: 19 ConnIdx: 0 Time: 02/22/2010 02:34:49.000 Number: 74638
GUID: Full: 0xF1300028F118F838 Type: Creature Entry: 10481 Low: 1636408
Victim GUID: Full: xxxxxxxx Type: Player Low: xxxxxxx Name: xxxx
Unk int: 0
ServerToClient: SMSG_COMPRESSED_UPDATE_OBJECT (0x01F6) Length: 231 ConnIdx: 0 Time: 02/22/2010 02:34:49.000 Number: 74650
Count: 8
[6] GUID: Full: 0xF1300028F118F838 Type: Creature Entry: 10481 Low: 1636408
[6] UNIT_FIELD_TARGET: 0x0
[6] UNIT_FIELD_BYTES_1: 7/0/0/0
[7] UpdateType: Values
[7] GUID: Full: xxxxxxx Type: Pet Entry: xxxxxx Low: 1830
[7] UNIT_FIELD_HEALTH: 1930
[7] UNIT_FIELD_POWER3: 2/3E-45
[7] UNIT_FIELD_POWER5: 999832/1.401063E-39
this looks like leaves combat or evades though so maybe thats how hp resets

**Comment by offl** [comment]
What about https://github.com/TrinityCore/TrinityCore/blob/e5963fda0ede44600da4624a242ac056cd08f9c4/src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp#L296
?

**Comment by dr-j** [comment]
Maybe should have current health set in creature table and disable hp regen

**Comment by offl** [comment]
Their level range is 3-5 (8-10 in creature_difficulty) so it will not work as percents

**Comment by offl** [comment]
I discovered that SMART_ACTION_SET_POWER / ADD_POWER / REMOVE_POWER power type health is unsupported

POWER_HEALTH = -2
-2 cannot be used for int(10)
This means POWER_HEALTH is not supported for all 3 actions

Actually percents are better than fixed value. In my case I need to remove 60% of total HP.

**Comment by offl** [comment]
I have no idea where you need to change any of those:
```text
    POWER_RAGE                          = 1,  // TITLE Rage
    POWER_FOCUS                         = 2,  // TITLE Focus
    POWER_ENERGY                        = 3,  // TITLE Energy
    POWER_HAPPINESS                     = 4,  // TITLE Happiness
    POWER_RUNE                          = 5,  // TITLE Runes
    POWER_RUNIC_POWER                   = 6,  // TITLE Runic Power
```
Maybe in master only, maybe only with new power types.
In other words why not just create it for mana and health.

**Comment by offl** [comment]
Imo all we need is one action with possibility to chose mana or health and change it like that me->SetHealth(me->CountPctFromMaxHealth());
So yeah, percents only
SMART_ACTION_SET_POWER / ADD_POWER / REMOVE_POWER probably may be used in some cases but right now I have no idea where to use it. And again, it will not work with health + there's no way to use percent and Blizz mostly or always uses percents. This makes these actions almost useless at least in 335.

**Comment by offl** [comment]
In SWP they used these spells
```sql
(-53032,0,0,0,11,0,100,0,0,0,0,0,0,11,46577,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Shattered Sun Soldier - On Respawn - Cast 'Wounded'"), -- 1833, 2347
(-53033,0,0,0,11,0,100,0,0,0,0,0,0,11,46586,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"Shattered Sun Soldier - On Respawn - Cast 'Almost Dead'"), -- 293, 220
```
The problem is they are not auras and are used only in SWP and maybe in some cases in WotLK. Definitely not in classic.
If Blizz used more spells like those in classic then it's pretty hard to sniff them because they just casts them on spawn, meaning it will be not possible to sniff friendly & unkillable \ if creature can't despawn at some point.

I guess at some point we can drop curhealth & curmana because with high chance everything here is handled by scripts or spells.
