### ISSUE TITLE
Combat animations not working properly

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#25342]
**Description:**

Created a dwarf hunter and weirdly combat animations arent working properly. You only get a damage visual on how much damage the mob has done to you but you cant see any animation whatsoever. Happens only when you dont move yourself and only when you attack with ranged weapon.

**Expected behaviour:**

Well it should show all combat animation :)

**Steps to reproduce the problem:**

1. Create a character (dwarf hunter at best)
2. Shoot at the enemies with ranged weapon with quiet a distance (DONT MOVE!)
3. A high chance that combat animation wont be played but enemy will still do damage

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be73959a0d838f71f9ff995486479fdffb7ab013

**Operating system:**  Windows 10

**Comment by Aokromes** [comment]
you write 3.3.5a branch, but you link master branch hash.

**Comment by felwyn** [comment]
Sorry corrected!

**Comment by offl** [comment]
Sounds like something opposite to https://github.com/TrinityCore/TrinityCore/issues/11854

**Comment by kaytotes** [comment]
This SetFacingToObject call: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Unit/Unit.cpp#L2054-L2055
Added in: https://github.com/TrinityCore/TrinityCore/commit/f481ae1048aac32ba3a40491f0304d0317234295

With that present I can pretty consistently recreate the stuttering attack animation. Not every creature but maybe 1 in 4. More easily reproducable if combat starts in melee range. Numerous times within a 30 minute window, tested in human starting area against Kobold Workers.

With it removed I've done roughly 1 hour of testing in the same way and not managed to replicate the bug.

Re-added it, able to reproduce in about 5 minutes again.

@Treeston could you confirm?

**Comment by Shauren** [comment]
eab6852b686ffaafa3aefb09b9c310c453db55aa
