### ISSUE TITLE
2+ Mobs stacking up on you

### ISSUE THREAD

**Issue by felwyn** [TrinityCore/TrinityCore#25343]
**Description:**

2+ Mobs stacking up at one position. They are not spreading around the player.

**Expected behaviour:**

They should spread around the player and combat you from one angle only.

Works on Warmane and CMaNGOS-WOTLK.

**Steps to reproduce the problem:**

1. Pull 2+ Mobs at one time.
2. Run away from them and let them form one unity.
3. Fight!

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be73959a0d838f71f9ff995486479fdffb7ab013

**Operating system:** Windows 10

**Comment by Jinnaix** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/20922
Also this is a master branch hash

**Comment by felwyn** [comment]
Sorry corrected!
