### ISSUE TITLE
Core/Misc: incorrect db error.

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25345]
**Description:**

After 534a238 was merged we have a new incorrect db error

2020-08-28_09:16:50 ERROR [sql.sql] Creature (Entry: 31786) has wrong spell '35357,' defined in `auras` field in `creature_template_addon`.

This row was added on 2017
https://github.com/TrinityCore/TrinityCore/commit/69cd31111e085de0c481c41f9b38806e58cfba61

**Expected behaviour:**

No db error.

**Steps to reproduce the problem:**

1. update to 85a1310

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

85a1310

**Operating system:** Debian 10 x64

**Comment by jackpoz** [comment]
This has to be fixed with a sql update. creature_template_addon auras are split by a space, not by a comma. Please check if there are other cases like this too.

**Comment by TranceAccount** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/issues/180

**Comment by jackpoz** [comment]
are there more affected tables ?

**Comment by Jinnaix** [comment]
I only know of creature_addon and creature_template_addon where we separate with a space.
The creature entry 31786 in c_t_a is the only case that has a unwanted separator in it.

```sql
UPDATE `creature_template_addon` SET `auras`='35357 46011' WHERE  `entry`=31786;

**Comment by Aokromes** [comment]
5055a1f
