### ISSUE TITLE
Quest: Blueleaf Tubers

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#25356]
**Description:**
Snufflenose Gopher from quest Blueleaf Tubers is buggy. 

https://classic.wowhead.com/quest=1221/blueleaf-tubers
https://classic.wowhead.com/npc=4781/snufflenose-gopher
https://classic.wowhead.com/item=5880/crate-with-holes 
https://classic.wowhead.com/item=6684/snufflenose-command-stick

**Steps to reproduce the problem:**
1. accept quest and collect required items
2. enter Razorfen Kraul
3. use Crate With Holes to summon Snufflenose Gopher (must be near buried tubers, otherwise you'll get an error message... correct behaviour?)

**Actual behaviour:**
Snufflenose Gopher will immediately detect a buried tuber. 
After being summoned, Snufflenose Gopher will send "smelling emote" to chat every few seconds.
When using command stick, I had two scenarios: 
1) Snufflenose Gopher does nothing
2) Snufflenose Gopher starts walking, and diappears by going through wall/ground (and player sometimes get stuck in combat)

**Expected behaviour:**
After being summoned, Snufflenose Gopher should not perform any action.
When using command stick, there are two cases:
1) Snufflenose Gopher does nothing (apart from sending emote?) when buried tuber ist to far away
1) Snufflenose Gopher walks to next buried tuber (not through bottom or walls)-> tuber gets visible. 

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
84bcf4d

**Operating system:** 
Win 10

**Comment by Faq** [comment]
when he goes under ground, that is usually because mobs attacking.

**Comment by dr-j** [comment]
Hmm can’t see why this is failing was working when was pushed should be setting passive on just summoned and script which finds tuners should only be when command stick used only emote previous to this should be the one about crawling out of crate

https://github.com/TrinityCore/TrinityCore/commit/4be5414c12b7429bc91521850cadfa91f5abe1b4

**Comment by dr-j** [comment]
This was originally scripted to move to tuber within 40 yards when command stick used may be this is too far

**Comment by dr-j** [comment]
Or we need new condition or parameter to ignore targets with in range that are not actually in range unless npc goes long way following paths to get there so it’s checks range and mmaps xd
