### ISSUE TITLE
Draenor / Pandaria / Legion / BfA all these area are empties of npcs & quests (8.3.7)

### ISSUE THREAD

**Issue by Irwin0812** [TrinityCore/TrinityCore#25366]
I installed master branch and it work fine except the subject of my issue.

I got the last trinitycore update and the last db update all from official trinitycore

Is it normal?

**Comment by MaxtorCoder** [comment]
1. Follow the template
2. Everything after Cata is sandbox (so no NCPs, quests etc)
3. You can also literally ask this on IRC or in the Discord and you would've gotten the same response.

**Comment by Irwin0812** [comment]
Thx :)
