### ISSUE TITLE
nopch does not build on Windows

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#25363]
3.3.5 fdcb1c8b2e142acc012f2ecb2ece082302e8fb15

Build fails from a clean checkout with `USE_COREPCH` and `USE_SCRIPTPCH` set to `0`.
In the same configuration with `USE_COREPCH` and `USE_SCRIPTPCH` set to `1`, build succeeds.

CMake log:
```cmake
The C compiler identification is MSVC 19.27.29111.0
The CXX compiler identification is MSVC 19.27.29111.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.27.29111.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: D:/server/mysql/lib/libmysql.lib
Found MySQL headers: D:/server/mysql/include
Found MySQL executable: D:/server/mysql/bin/mysql.exe
Found git binary : D:/utils/Git/cmd/git.exe

* TrinityCore revision   : fdcb1c8b2e14 2020-08-30 14:20:20 +0200 (3.3.5 branch)

* Install core to        : D:/server/trinitycore/run
* Install configs to     : D:/server/trinitycore/run

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : Yes
* Build core w/PCH       : No
* Build scripts w/PCH    : No
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found Boost: D:/libs/boost_1_73_0 (found suitable version "1.73.0", minimum required is "1.70") found components: system filesystem program_options iostreams regex 
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for open
Looking for open - found
Found OpenSSL library: optimized;D:/libs/openssl-1.1.1g/libssl.lib;D:/libs/openssl-1.1.1g/libcrypto.lib;debug;D:/libs/openssl-1.1.1g/libssl.lib;D:/libs/openssl-1.1.1g/libcrypto.lib
Found OpenSSL headers: D:/libs/openssl-1.1.1g/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done
Generating done
```

Compiler output:
```
18>Errors.cpp
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(208,52): error C2143: syntax error: missing ')' before '*' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(208,52): error C2143: syntax error: missing ';' before '*' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(208,83): error C2059: syntax error: ')' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(212,34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(223,52): error C2143: syntax error: missing ')' before '*' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(223,52): error C2143: syntax error: missing ';' before '*' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(223,71): error C2059: syntax error: ')' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(228,34): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(239,44): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(239,42): error C2146: syntax error: missing ';' before identifier 'f' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(239,42): error C2065: 'f': undeclared identifier (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(239,92): error C2061: syntax error: identifier 'nt_system_query_information_p' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(241,14): error C2065: 'f': undeclared identifier (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(253,32): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(253,30): error C2146: syntax error: missing ';' before identifier 'f' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(253,30): error C2065: 'f': undeclared identifier (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(253,68): error C2061: syntax error: identifier 'nt_query_object_p' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handle_workaround.hpp(255,14): error C2065: 'f': undeclared identifier (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handles.hpp(139,27): error C2760: syntax error: unexpected token 'identifier', expected ';' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>D:\libs\boost_1_73_0\boost/process/detail/windows/handles.hpp(139,27): message : This diagnostic occurred in the compiler generated function 'void boost::process::detail::windows::limit_handles_::on_setup(Executor &) const' (compiling source file D:\server\trinitycore\source\src\common\Utilities\StartProcess.cpp)
18>Done building project "common.vcxproj" -- FAILED.
```

**Comment by genion18** [comment]
All build succeeds by me thit no pch..

> Selecting Windows SDK version 8.1 to target Windows 6.1.7601.
> Detected 64-bit platform
> MSVC: Minimum version required is 19.16, found 19.26.28806.0 - ok!
> MSVC: 64-bit platform, enforced -D_WIN64 parameter
> MSVC: Enabled increased number of sections in object files
> MSVC: Overloaded standard names
> MSVC: Disabled NON-SECURE warnings
> MSVC: Disabled POSIX warnings
> MSVC: Disabled generic compiletime warnings
> Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.7/lib/libmysql.lib
> Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.7/include
> Found MySQL executable: C:/Program Files/MySQL/MySQL Server 5.7/bin/mysql.exe
> Found git binary : C:/Program Files/Git/cmd/git.exe
> 
> * TrinityCore revision   : fdcb1c8b2e14+ 2020-08-30 14:20:20 +0200 (3.3.5 branch)
> 
> * Install core to        : C:/Program Files (x86)/TrinityCore
> * Install configs to     : C:/Program Files (x86)/TrinityCore
> 
> * Build world/auth       : Yes (default)
> * Build with scripts     : Yes (static)
> * Build map/vmap tools   : Yes (default)
> * Build unit tests       : No (default)
> * Build core w/PCH       : No
> * Build scripts w/PCH    : No
> * Show compile-warnings  : No  (default)
> * Use coreside debug     : No  (default)
> * Show source tree       : Yes (hierarchical)
> * Use GIT revision hash  : Yes (default)
> 
> Found OpenSSL library: optimized;C:/OpenSSL/lib/VC/libssl64MD.lib;C:/OpenSSL/lib/VC/libcrypto64MD.lib;debug;C:/OpenSSL/lib/VC/libssl64MDd.lib;C:/OpenSSL/lib/VC/libcrypto64MDd.lib
> Found OpenSSL headers: C:/OpenSSL/include
> 
> * Script configuration (static):
>     |
>     +- worldserver
>     |   +- Battlefield
>     |   +- Commands
>     |   +- Custom
>     |   +- EasternKingdoms
>     |   +- Events
>     |   +- Kalimdor
>     |   +- Northrend
>     |   +- OutdoorPvP
>     |   +- Outland
>     |   +- Pet
>     |   +- Spells
>     |   +- World
>     |
> 
> Configuring done
> Generating done

Compiler output:

> 1>------ Erstellen gestartet: Projekt: revision_data.h, Konfiguration: RelWithDebInfo x64 ------
> 2>------ Erstellen gestartet: Projekt: game, Konfiguration: RelWithDebInfo x64 ------
> 2>PlayerTaxi.cpp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(36,32): error C2039: "string" ist kein Member von "std".
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\deque(24): message : Siehe Deklaration von "std"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(36,39): error C2061: Syntaxfehler: Bezeichner "string"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(59,64): error C2039: "string" ist kein Member von "std".
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\deque(24): message : Siehe Deklaration von "std"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(59,71): error C2061: Syntaxfehler: Bezeichner "string"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(60,14): error C2039: "string" ist kein Member von "std".
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\deque(24): message : Siehe Deklaration von "std"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(60,49): error C3646: "SaveTaxiDestinationsToString": Unbekannter Überschreibungsspezifizierer
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(60,49): error C2059: Syntaxfehler: "("
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(60,51): error C2238: Unerwartete(s) Token vor ";"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(66,1): error C2511: "bool PlayerTaxi::LoadTaxiMask(const std::string &)": Überladene Memberfunktion nicht in "PlayerTaxi" gefunden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(29): message : Siehe Deklaration von "PlayerTaxi"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(74,29): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_taximask"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(74,29): error C3867: "PlayerTaxi::m_taximask": Keine Standardsyntax; "&" zum Erstellen eines Verweises auf das Member verwenden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(74,29): error C2109: Index erfordert ein Array oder einen Zeigertyp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(75,16): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_taximask"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(75,16): error C3867: "PlayerTaxi::m_taximask": Keine Standardsyntax; "&" zum Erstellen eines Verweises auf das Member verwenden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(75,16): error C2109: Index erfordert ein Array oder einen Zeigertyp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(80,29): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_taximask"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(80,29): error C3867: "PlayerTaxi::m_taximask": Keine Standardsyntax; "&" zum Erstellen eines Verweises auf das Member verwenden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(80,29): error C2109: Index erfordert ein Array oder einen Zeigertyp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(102,1): error C2511: "bool PlayerTaxi::LoadTaxiDestinationsFromString(const std::string &,uint32)": Überladene Memberfunktion nicht in "PlayerTaxi" gefunden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(29): message : Siehe Deklaration von "PlayerTaxi"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(103,5): error C2352: "PlayerTaxi::ClearTaxiDestinations": Unzulässiger Aufruf einer nicht statischen Memberfunktion
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(62): message : Siehe Deklaration von "PlayerTaxi::ClearTaxiDestinations"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(110,13): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_flightMasterFactionId"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(82): message : Siehe Deklaration von "PlayerTaxi::m_flightMasterFactionId"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(118,13): error C2352: "PlayerTaxi::AddTaxiDestination": Unzulässiger Aufruf einer nicht statischen Memberfunktion
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(63): message : Siehe Deklaration von "PlayerTaxi::AddTaxiDestination"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,57): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_TaxiDestinations"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,57): error C3867: "PlayerTaxi::m_TaxiDestinations": Keine Standardsyntax; "&" zum Erstellen eines Verweises auf das Member verwenden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,57): error C2109: Index erfordert ein Array oder einen Zeigertyp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,80): error C2597: Ungültiger Verweis auf nicht-statischen Member "PlayerTaxi::m_TaxiDestinations"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,80): error C3867: "PlayerTaxi::m_TaxiDestinations": Keine Standardsyntax; "&" zum Erstellen eines Verweises auf das Member verwenden
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,80): error C2109: Index erfordert ein Array oder einen Zeigertyp
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(134,93): error C2660: "ObjectMgr::GetTaxiPath": Funktion akzeptiert keine 3 Argumente
> 2>C:\sicher\3.3.5\src\server\game\Globals\ObjectMgr.h(1041,14): message : Siehe Deklaration von "ObjectMgr::GetTaxiPath"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(140,44): error C2352: "PlayerTaxi::GetTaxiSource": Unzulässiger Aufruf einer nicht statischen Memberfunktion
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(64): message : Siehe Deklaration von "PlayerTaxi::GetTaxiSource"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(146,25): error C2039: "SaveTaxiDestinationsToString" ist kein Member von "PlayerTaxi".
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.h(29): message : Siehe Deklaration von "PlayerTaxi"
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(148,9): error C2065: "m_TaxiDestinations": nichtdeklarierter Bezeichner
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(151,5): error C2065: "m_TaxiDestinations": nichtdeklarierter Bezeichner
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(154,11): error C2065: "m_flightMasterFactionId": nichtdeklarierter Bezeichner
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(156,28): error C2065: "m_TaxiDestinations": nichtdeklarierter Bezeichner
> 2>C:\sicher\3.3.5\src\server\game\Entities\Player\PlayerTaxi.cpp(157,15): error C2065: "m_TaxiDestinations": nichtdeklarierter Bezeichner
> 2>Die Erstellung des Projekts "game.vcxproj" ist abgeschlossen -- FEHLER.
> 3>------ Erstellen gestartet: Projekt: worldserver, Konfiguration: RelWithDebInfo x64 ------
> 3>LINK : fatal error LNK1181: Eingabedatei "..\game\RelWithDebInfo\game.lib" kann nicht geöffnet werden.
> 3>Die Erstellung des Projekts "worldserver.vcxproj" ist abgeschlossen -- FEHLER.
> 4>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: RelWithDebInfo x64 ------
> 4>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
> ========== Erstellen: 1 erfolgreich, 2 fehlerhaft, 21 aktuell, 1 übersprungen ==========

**Comment by bmjoy** [comment]
#include "StartProcess.h"
#include "Errors.h"
#include "Log.h"
#include "Optional.h"
#include "Util.h"
**#include <Windows.h>**
#include <boost/algorithm/string/join.hpp>
#include <boost/iostreams/copy.hpp>
#include <boost/process/args.hpp>
#include <boost/process/child.hpp>
#include <boost/process/env.hpp>
#include <boost/process/exe.hpp>
#include <boost/process/io.hpp>
#include <boost/process/pipe.hpp>
#include <boost/process/search_path.hpp>

using namespace boost::process;
using namespace boost::iostreams;

namespace Trinity

**Comment by Shauren** [comment]
This is a bug in boost/process itself. It was designed to not to ever include windows.h (unless requested by users with a preprocessor define)

**Comment by Shauren** [comment]
Fixed in boost 1.78
