### ISSUE TITLE
Server Crashes on help command in consol

### ISSUE THREAD

**Issue by DerEnderman** [TrinityCore/TrinityCore#25360]
**Description:**

If you type help in unix consol the whole gameserver crashes

**Expected behaviour:**

Idk... Not crashing the server?

**Steps to reproduce the problem:**

Compile Server in Debian 10 and start server
Type help in consol
Server crashes with -> TC> Segmentation fault

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
TrinityCore rev. 2c3d3c31b22c 2020-08-29 20:46:00 +0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Operating system:** CHANGEME OS
Debian 10 x64 Dedicated Server (No vServer)

**Comment by DerEnderman** [comment]
Also tested with push from : TrinityCore rev. 2f7d2ef3e979 2020-08-30 02:50:25 +0200

Same issue here!

**Comment by MaxtorCoder** [comment]
Need a full log on Pastebin.

**Comment by DerEnderman** [comment]
I haven't thats all i get. there is no log that will be created idk why if you tell me here how to get a log ill send you!

**Comment by MaxtorCoder** [comment]
> I haven't thats all i get. there is no log that will be created idk why if you tell me here how to get a log ill send you!

`Crashes/<latest log>`

**Comment by DerEnderman** [comment]
that is not existing as i sayd, the problem is i dont get that log lol

**Comment by Aokromes** [comment]
you need to run tc under gdb.

**Comment by DerEnderman** [comment]
i did and i posted what i get ...
[New Thread 0x7ffde93ff700 (LWP 24571)]
TC> help
TC>
Thread 1 "worldserver" received signal SIGSEGV, Segmentation fault.
__GI___strtok_r (s=0x0, delim=0x21878c6 " ", save_ptr=0x7ffff7200a68 ) at strtok_r.c:49
49 strtok_r.c: No such file or directory.
(gdb)
