### ISSUE TITLE
DB/Quest: quest_reward typo in "Dangerous!"

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25408]
**Description:**

![WoWScrnShot_090620_044502](https://user-images.githubusercontent.com/38162891/92317279-49147d80-efff-11ea-974b-a34ee2d26152.jpg)

Upon completion of the quest "Dangerous!", the `quest_reward` gossip window seems to have lost some text based on a lack of understanding of grammar, syntax, and common expressions in the English language.

The reward gossip says: "You are quite the bounty, `<Class>`. Well done."

**Expected behaviour:**

The gossip should contain the common English expression "bounty hunter" which is a common phrase, often seen in connection with reward posters and their stereotypical appearance in the American Western movies & cartoons, where bounty hunters are chasing criminals and other wanted people. The text should look like the following:

> You are quite the bounty hunter, `<class>`. Well done.

**Suggested solution:**

```sql
-- Correction of the Reward text in Quest: "Dangerous!" (567)
UPDATE `quest_offer_reward` SET `RewardText`= "You are quite the bounty hunter, $c.  Well done." WHERE `ID`= 567;
```

**Steps to reproduce the problem:**

1. Use a level 20-30 horde character and `.tele TarrenMill`
2. `.quest add 567` followed by `.quest complete 567`
3. Walk over to High Executor Darthalia, open up her gossip, and notice the incomplete text.

**Branch(es):**

3.3.5 only (Hillsbrad got completely changed by Cataclysm)

**TC rev. hash/commit:** 

TC> server debug
TrinityCore rev. ff2602745317 2020-09-05 22:07:17 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20082
TC>_

**Operating system:** Windows 10 Home x64 Version 2004 (OS Build 19041.388)

**Comment by illfated** [comment]
Quest links:

- https://wow.gamepedia.com/Dangerous!_(quest) (describing the removal in patch 4.0.3a)
- https://www.wowhead.com/quest=567/deprecated-dangerous (instead of the classic page)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=567

**Comment by illfated** [comment]
I just tested my own solution yesterday, which worked just as expected and intended.
I also admit that it looks a bit weird to see the gossip text
```sql
You are quite the bounty hunter, hunter.
Well done.
```
I am guessing that this combination could have thrown the SQL dev off their balance, thinking that "hunter, hunter" _must_ be a duplicate bug.

**Comment by offl** [comment]
Let's make this quest not available to hunters then.

**Comment by illfated** [comment]
Heh, I see what you are saying, but I guess Blizzard did not care much about details for the hunter class and semantics when they made the gossip for this quest. Never mind, it's just a coincidence that it looks just as odd as the tauren starter area quest where the text refers to the grateful `<class>` population of their camp.
