### ISSUE TITLE
Fix issue with Attunement to Dalaran

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#25403]
Attunement to dalaran

https://www.wowhead.com/quest=12173/attunement-to-dalaran
https://www.wowhead.com/quest=12173/attunement-to-dalaran

Remove non repeatable flag from spellhit event on Attunement to Dalaran kill credit bunny so this works  for more than one player per restart.
~~~sql
UPDATE smart_scripts SET event_flags='0' WHERE  entryorguid=27135 AND source_type=0 AND id=0 AND link=0;

**Comment by Treeston** [comment]
```mysql
mysql> select event_flags from smart_scripts where entryorguid=27135 and source_type=0;
+-------------+
| event_flags |
+-------------+
|           0 |
+-------------+
1 row in set (0.00 sec)
```

Does not appear to be applicable to current 3.3.5.
