### ISSUE TITLE
DB/Locale/deDE Texts missing

### ISSUE THREAD

**Issue by SneakyV** [TrinityCore/TrinityCore#25411]
Many German translations are missing in the tables "quest_request_items_locale" and "quest_offer_reward_locale".
I am attaching a zipped SQL file with some translations. I hope the coding fits.

**Branch(es):**
3.3.5

[german_locales.zip](https://github.com/TrinityCore/TrinityCore/files/5179798/german_locales.zip)

**Comment by offl** [comment]
They're from wowhead?

**Comment by SneakyV** [comment]
Years ago I found these translations on the Internet for an old Trinity Core, where all translations were still in one database line.
I have compared some of the translations with wowhead and they seem identical.
