### ISSUE TITLE
DB/Quest: Icebane Gauntlets and Icebane Bracers

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25420]
**Description:**

**Master Craftsman Wilhelm** NPC offers these two quests.

**Expected behaviour:**

According to this _Wowpedia_ [article](https://wow.gamepedia.com/Icebane_Gauntlets_(quest)), this quest should not be available after patch 3.0.2. Even this [quest](https://wow.gamepedia.com/Icebane_Bracers_(quest)) should not be available because of a removed required [item](https://wow.gamepedia.com/Frozen_Rune).

**Steps to reproduce the problem:**

1. `.go creature id 16376`
2. Check the quests he offers.

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

43986954fddc05e0fe1f225b0cf38a7b01f775bb

**Operating system:** Windows 7 Enterprise 64bit

**Comment by illfated** [comment]
As far as I can remember, those should be "replaced" by the Dalaran patterns and skills where you need a Frozen Orb to craft the items.
(By "replaced" I mean that the new items crafted with Frozen Orbs use the same names as the removed Frozen Rune ones.)
