### ISSUE TITLE
Fix trap Deathbound Ward

### ISSUE THREAD

**Issue by HoustonCore** [TrinityCore/TrinityCore#25433]
**Video:**
- [Before change](https://youtu.be/jBMtp2n6BoQ)
- [After change](https://youtu.be/mL4uDqEySTI)

This is certainly not blizzlike, but it works. It remains only to make them walk on the coordinates when activating the trap.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/062c55f1ab9c84396ce5b054945f5a908e3a354f

``` sql
-- Spirit Alarm
UPDATE `gameobject_template` SET `Data4` = 0, `Data5` = 3600 WHERE `entry` = 201814;
UPDATE `gameobject_template` SET `Data4` = 0, `Data5` = 3600 WHERE `entry` = 201815;
UPDATE `gameobject_template` SET `Data4` = 0, `Data5` = 3600 WHERE `entry` = 201816;
UPDATE `gameobject_template` SET `Data4` = 0, `Data5` = 3600 WHERE `entry` = 201817;

-- Spirit Alarm
UPDATE `gameobject` SET `spawntimesecs` = 3600 WHERE `id` = 201814;
UPDATE `gameobject` SET `spawntimesecs` = 3600 WHERE `id` = 201815;
UPDATE `gameobject` SET `spawntimesecs` = 3600 WHERE `id` = 201816;
UPDATE `gameobject` SET `spawntimesecs` = 3600 WHERE `id` = 201817;

**Comment by Aokromes** [comment]
without sniffs this is hack.

**Comment by HoustonCore** [comment]
> without sniffs this is hack.

You first look at how it works now isn't this a hack?

**Comment by Aokromes** [comment]
changing Data? without sniff is hack, allways.

**Comment by jackpoz** [comment]
what are the original values in the db an why are they wrong ?

**Comment by HoustonCore** [comment]
Okey i'm replace. If you speak this hack.

**Comment by jackpoz** [comment]
what was even the issue about ?

**Comment by Aokromes** [comment]
atm the big skeletons are active before hit a trap.

**Comment by HoustonCore** [comment]
You close this issue, I open new PR method is not hack

**Comment by offl** [comment]
Duplicate of #4590
