### ISSUE TITLE
DB/Locale/deDE - Missing translations

### ISSUE THREAD

**Issue by SneakyV** [TrinityCore/TrinityCore#25459]
**Description:**
A few more translations - wowhead compliant

**Branch(es):**
3.3.5

[german_locale-2.zip](https://github.com/TrinityCore/TrinityCore/files/5228362/german_locale-2.zip)

**Comment by offl** [comment]
Please use delete-insert statements and not REPLACE INTO in future
```sql
DELETE FROM `quest_offer_reward_locale` WHERE `ID` IN (1,2,3) AND `locale` = 'deDE';
INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
