### ISSUE TITLE
Two Cenarion Hold Infantry guards appear fused together in Cenarion Hold

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25456]
**Description:**

Two **Cenarion Hold Infantry** guards appear fused together in Cenarion Hold. This happens every time I see them, not only one time.

Click the image to see the video preview:
[![WoW-WotLK TrinityCore Cenarion Hold Infantry two guards bug](https://i.ibb.co/Tgwn2Ps/wow-trinitycore-bug.png)](https://www.youtube.com/watch?v=eybRM32RHSc "WoW-WotLK TrinityCore Cenarion Hold Infantry two guards bug")

**Expected behaviour:**

This should not happen normally, am I right?

**Steps to reproduce the problem:**

1. `.tele CennarionHold`
2. There are two specific **Cenarion Hold Infantry** guards who patrol there. I found them patrolling around the building where **Commander Mar'alith** resides.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

43986954fddc05e0fe1f225b0cf38a7b01f775bb

**Operating system:** Windows 7 Enterprise 64bit

**Comment by jackpoz** [comment]
Using .gm off or ?

**Comment by Aokromes** [comment]
[23:22:47] SpawnID: 42898, current GUID low: 166050.

**Comment by LEO33SoFo** [comment]
> Using .gm off or ?

Using `.gm off`, of course.

Should have added a postscript "I encountered this bug just via normal progression, without using GM commands."

**Comment by illfated** [comment]
Confirmed.

TrinityCore rev. 39a436bd6587 2020-09-14 19:47:51 +0200 (3.3.5 branch) (Win64, Release, Static)

<details>
<summary>Details</summary>

Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20082

</details>

This is the only patrolling guard duo in the center of Cenarion Hold, as far as I can see. They start off walking about 2 steps walking distance between them, but for each roundtrip they make between the alliance flight master and the lowest point outside the north side of the hold, they get closer and closer until they have merged and walk as one unit.

**Comment by illfated** [comment]
`.npc info` Cenarion Hold Infantry NPC 1: SpawnID: 42897, current GUID low: 67. Entry: 15184.

<details>
<summary>Details</summary>

```
NPC currently selected by player:
Name: Cenarion Hold Infantry
SpawnID: 42897, current GUID low: 67.
Entry: 15184.
Faction: 1254.
NPC Flags: 0.
DisplayID: 15307 (Native: 15307).
Compatibility Mode: 0
Level: 70.
EquipmentId: 1 (Original: 1).
Health (base): 32400. (max): 32400. (current): 32400.
Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
Unit Flags: 33280
* UNIT_FLAG_IMMUNE_TO_NPC (0x200)
* UNIT_FLAG_SWIMMING (0x8000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1254.
SpawnTime: Full:10m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 6719
Position: -6794.059082 769.247925 66.559158.
AIName: SmartAI ScriptName: 
React state: AGGRESSIVE
Active AI: class SmartAI
Flags Extra: 32832
* CREATURE_FLAG_EXTRA_NO_XP_AT_KILL (0x40)
* CREATURE_FLAG_EXTRA_GUARD (0x8000)
MechanicImmuneMask: 0
```

</details>


`.npc info` Cenarion Hold Infantry NPC 2: SpawnID: 42898, current GUID low: 68. Entry: 15184.

<details>
<summary>Details</summary>

```
NPC currently selected by player:
Name: Cenarion Hold Infantry
SpawnID: 42898, current GUID low: 68.
Entry: 15184.
Faction: 1254.
NPC Flags: 0.
DisplayID: 15305 (Native: 15305).
Compatibility Mode: 0
Level: 70.
EquipmentId: 1 (Original: 1).
Health (base): 32400. (max): 32400. (current): 32400.
Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk
Unit Flags: 33280
* UNIT_FLAG_IMMUNE_TO_NPC (0x200)
* UNIT_FLAG_SWIMMING (0x8000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 1254.
SpawnTime: Full:10m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 6719
Position: -6816.206543 822.893250 49.700905.
AIName: SmartAI ScriptName: 
React state: AGGRESSIVE
Active AI: class SmartAI
Flags Extra: 32832
* CREATURE_FLAG_EXTRA_NO_XP_AT_KILL (0x40)
* CREATURE_FLAG_EXTRA_GUARD (0x8000)
MechanicImmuneMask: 0
```

</details>
