### ISSUE TITLE
DB/Quest: missing word in quest_request_items for "Baron Aquanis" (6922)

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25453]
**Description:**

While handing in the quest "Baron Aquanis" (ID 6922), I found a small typo, or rather a missing word in the "Progress" gossip or `quest_request_items`.

The current progress text (`quest_request_items`.`CompletionText`) is missing the simple conjunction "of" in Je'neu Sancrea's first sentence:

```sql
SELECT * FROM `quest_request_items` WHERE `ID`= 6922;
```

```
  ID  EmoteOnComplete  EmoteOnIncomplete  CompletionText                                                                                                      VerifiedBuild
----  ---------------  -----------------  ------------------------------------------------------------------------------------------------------------------  -------------
6922                1                  0  Ah, hello again $N.  I was just reading the waves the sea, much like I always do.  What brings you to the outpost?          12340
```

**Expected behaviour:**

The text should read: Ah, hello again `<name>`.  I was just reading the waves of the sea, much like I always do.  What brings you to me?

**Steps to reproduce the problem:**

1. Horde level 21+ character. `.tele ZoramGar`
2. `.additem 16782` and right-click it to get the quest.
3. Walk over to Je'neu Sancrea and open the completed quest "Baron Aquanis" to read the quest text.

**Suggested solution:**

```sql
UPDATE `quest_request_items` SET `CompletionText`= "Ah, hello again $n.  I was just reading the waves of the sea, much like I always do.  What brings you to me?" WHERE `ID`= 6922;
```

**Branch(es):**

3.3.5 / 4.3.4 only. Removed in patch 6.0.2

**TC rev. hash/commit:** 

TC> server debug
TrinityCore rev. 14fa6c3a725f 2020-09-13 00:37:54 +0200 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20082

**Operating system:** Windows 10 Version 2004 (OS Build 19041.388)

**Comment by offl** [comment]
The text was changed only in Cata
view-source:http://web.archive.org/web/20100702005654/www.wowhead.com/quest=6922
view-source:http://web.archive.org/web/20101031191519/www.wowhead.com/quest=6922
