### ISSUE TITLE
Db/NPC: Kronk is sitting in air

### ISSUE THREAD

**Issue by Faq** [TrinityCore/TrinityCore#25451]
**Description:**

[Kronk](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=23253)
![image](https://user-images.githubusercontent.com/322016/93012132-5654dd80-f5a6-11ea-9a1a-8c49ab97ad0d.png)

**Expected behaviour:**

on ground

**Steps to reproduce the problem:**

.go c id 23253

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

14fa6c3a725f617e02af74eea95f5074b9095704

**Comment by Jildor** [comment]
are you sure position_z is wrong?
https://wowwiki.fandom.com/wiki/Kronk <-- see img
https://www.youtube.com/watch?v=DgSVWLLlG_Y

**Comment by TranceAccount** [comment]
AFAIK he is supposed to be floating like that
