### ISSUE TITLE
Issues with boost while configuring in Cmake and building in Visual Studio?

### ISSUE THREAD

**Issue by Rhawk** [TrinityCore/TrinityCore#25464]
_Disclaimer: I am not a developer or programmer of any kind. I unfortunately have only very basic (self-taught) knowledge of programming and am thus asking for assistance on this forum after trying to the best of my capabilities to fix the problem myself first. I hope someone will be able to help._

**Description:**

Hello.

So I am trying to create a server using the TinityCore guide posted on here, and I've been having some issues. My first issue was when "Git Clone" did not show up as an option when right-clicking the "Trinity" folder, or any folder. Only "Git Bash Here" and Git GUI here". I however attempted to circumvent this by using bash and the "git clone" command which seemed to work fine. However it created a subfolder within the Trinity folder called "TrinityCore".

I then attempted the configuring step using Cmake, which seemingly worked fine, but produced a warning as follows, multiple times:

CMake Warning at C:/Program Files/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1187 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
  dep/boost/CMakeLists.txt:47 (find_package)

I however continued with the Generating of the build and went on into Visual Studio 2019 to clean and build the solution. The cleaning went smoothly. On my first attempt to build, about 18 files succeeded and 8 failed. I then built the solution again, and this time 12 errors popped up as follows:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\shared\RelWithDebInfo\shared.lib'	bnetserver	C:\Build\src\server\bnetserver\LINK	1	
Error	LNK1104	cannot open file 'libboost_filesystem-vc142-mt-x64-1_74.lib'	vmap4assembler	C:\Build\src\tools\vmap4_assembler\LINK	1	
Error	LNK1104	cannot open file 'libboost_filesystem-vc142-mt-x64-1_74.lib'	mmaps_generator	C:\Build\src\tools\mmaps_generator\LINK	1	
Error	LNK1104	cannot open file 'libboost_filesystem-vc142-mt-x64-1_74.lib'	vmap4extractor	C:\Build\src\tools\vmap4_extractor\LINK	1	
Error	LNK1104	cannot open file 'libboost_filesystem-vc142-mt-x64-1_74.lib'	mapextractor	C:\Build\src\tools\map_extractor\LINK	1	
Error	C2079	'boost::asio::detail::io_object_impl<boost::asio::detail::resolver_service<InternetProtocol>,Executor>::executor_' uses undefined class 'boost::asio::executor'	shared	C:\local\boost_1_74_0\boost\asio\detail\io_object_impl.hpp	168	
Error	C2679	binary '=': no operator found which takes a right-hand operand of type 'std::unique_ptr<boost::asio::ip::tcp::resolver,std::default_delete<boost::asio::ip::tcp::resolver>>' (or there is no acceptable conversion)	shared	C:\Trinity\TrinityCore\src\server\shared\Realm\RealmList.cpp	56	
Error	C2664	'boost::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)': cannot convert argument 1 from '_Ty' to 'boost::asio::ip::tcp::resolver &'	shared	C:\Trinity\TrinityCore\src\server\shared\Realm\RealmList.cpp	154	
Error	C2664	'boost::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)': cannot convert argument 1 from '_Ty' to 'boost::asio::ip::tcp::resolver &'	shared	C:\Trinity\TrinityCore\src\server\shared\Realm\RealmList.cpp	161	
Error	C2664	'boost::optional<boost::asio::ip::tcp::endpoint> Trinity::Net::Resolve(boost::asio::ip::tcp::resolver &,const boost::asio::ip::tcp &,const std::string &,const std::string &)': cannot convert argument 1 from '_Ty' to 'boost::asio::ip::tcp::resolver &'	shared	C:\Trinity\TrinityCore\src\server\shared\Realm\RealmList.cpp	168	
Error	C2300	'boost::heap::detail::marked_heap_node<RespawnInfo *>': class does not have a destructor called '~Node' (compiling source file C:\Trinity\TrinityCore\src\server\game\Maps\Map.cpp)	game	C:\local\boost_1_74_0\boost\heap\detail\heap_node.hpp	145	
Error	LNK1181	cannot open input file '..\game\RelWithDebInfo\game.lib'	worldserver	C:\Build\src\server\worldserver\LINK	1	

**Expected behaviour:**

I am expecting for the configuring of the build to not produce warnings, and the build in Visual Studio 2019 to work smoothly.

**Steps to reproduce the problem:**

I followed the steps as mentioned within the guide, and have even attempted using earlier boost versions and changing the environment variables accordingly, but haven't had any results.

**Branch(es):**

3.3.5a

**Operating system:** Windows 10

If someone would be able to help with my issue, I would deeply appreciate it. Thank you!

Rhawkie

**Comment by Aokromes** [comment]
you don't look to be using 3.3.5a branch.

Error LNK1181 cannot open input file '..\shared\RelWithDebInfo\shared.lib' bnetserver C:\Build\src\server\bnetserver\LINK 1
this is clearly 4.3.4 or master branch.

**Comment by Rhawk** [comment]
Thank you for the feedback. Could you perhaps guide me on how I can change my 'git clone' command to specifically download the 3.3.5a branch, or perhaps how I can fix git extensions not showing the Git Clone option when I right click?

**Comment by Shauren** [comment]
The first one (3.3.5, without a)
You could also just go inside your cloned directory and run `git checkout 3.3.5`

**Comment by MaxtorCoder** [comment]
And for the next time use `git clone <url> -b 3.3.5`, `-b` being a valid branch on the repository.

**Comment by jackpoz** [comment]
this seems to be an issue specific to your setup that might fit better on the forum/irc/discord (as we collect on github issues related to the code itself)

**Comment by KrowtennetworK** [comment]
I have all the latest versions of CMAKE and Boost.  Is this issue typical upon new releases?

**Comment by Warpten** [comment]
This is an user error.
