### ISSUE TITLE
Quest: Sunken Treasure

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25465]
**Description:**

During part 2 of the quest series [Sunken Treasure](https://classic.wowhead.com/quest=666/sunken-treasure), you are required to equip "Goggles of Gem Hunting" in order to see the stones that give the required quest item "Elven Gems"

The quest requires you have the goggles equipped, however, if you don't equip them, the Gem nodes are still available to interact with.

**Expected behaviour:**

The Goggles are required to be equipped (and remain equipped) before you can interact with the stones that give the Gems.

**Steps to reproduce the problem:**

1. Accept part 2 in the series called Sunken Treasure https://classic.wowhead.com/quest=666/sunken-treasure from Doctor Draxlegauge
2. (a) Head to the quest area but do not equip the goggles; OR
(b) Head to the quest area, equip the goggles and remove them
3. Dive to the sea floor and look for the shiny inter-actable stones offering the Gems
4. Loot one 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 9d959123e680 2020-09-15 19:37:54 +0000 (3.3.5 branch)

**Operating system:** 

Win7 64

EDIT: Goggles, not Googles.

**Comment by genion18** [comment]
Not confirmed.

You can loot the Gems without equipped the Googles.
The Googles are to see the Gems not more.
Testet on Retail wirhout Googles and loot the gems.

**Comment by TQPS** [comment]
It's possible the quest underwent some changes over the years - I believe retail even gives you a water breathing buff now - however, for this branch, the googles were required to be equipped before you could loot the gems.

Earlier posts from both BFA (back in 2010) and Classic versions of this quest on wowhead confirm goggles are required to be equipped.

**Comment by offl** [comment]
> you are required to equip "Goggles of Gem Hunting" in order to see the stones

Definitely not, check the item description https://www.wowhead.com/item=4491
> Equip: Nearby elven gems appear on the minimap.

Then click on spell https://www.wowhead.com/spell=4152/detect-elven-gems
> Effect Apply Aura: Track Resources (7)

Also I don't remember any object in Classic or even TBC which appear visible only if quest is taken
I guess Blizzard simply didn't had such feature in Classic and I have no idea how to make them visible only if quest is taken by using **Classic's methods**
