### ISSUE TITLE
Quest: Accepting shared quest shows as decline in sharer's chat log

### ISSUE THREAD

**Issue by NanoCode012** [TrinityCore/TrinityCore#25474]
**Description:**

Hello, as I've mentioned in the Discord server. When another player accepts a shared quest, it shows up as declined.

I created 2 new paladins for this test and made sure that they are not gm accounts. The below is a picture of the chat log.

![image](https://user-images.githubusercontent.com/9899957/93709247-01e1cd00-fb67-11ea-85bd-0e30fd5efc7b.png)

**Expected behaviour:**

It should say that War has accepted the quest.

**Steps to reproduce the problem:**

1. Create two new accounts
2. Create a paladin on each account
3. One paladin should take the first quest and invite the other paladin to the party
4. Share first quest
5. Other paladin accept the quest

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6215da0d640b

**Operating system:** 

Ubuntu 20.04

**Comment by Faq** [comment]
Ingame message is wrong, as other char who used Accept, got the q in qlog. 

https://gist.github.com/Faq/6eab15d5990f5f92f1ffdd8fdb8170f2

**Comment by jackpoz** [comment]
This is a special case as the quest is of type Auto-accept so the party member gets the quest added to the quest log even before clicking any button.

**Comment by jackpoz** [comment]
I created a PR at https://github.com/TrinityCore/TrinityCore/pull/25477 fixing the issue
