### ISSUE TITLE
[3.3.5] Crash after summoning warlock infernal

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#25478]
**Description:**

Server crashes if you summon infernal (https://wotlk.evowow.com/?spell=1122), and then any of the other warlock pets afterwards. I was having .cheat cooldown and casttime on, but ive been able to replicate it without as well.

**Expected behaviour:**

Shouldnt crash

**Steps to reproduce the problem:**

1. Create a warlock, learn yourself 1122
2. Cast summon inferno (https://wotlk.evowow.com/?spell=1122)
3. Summon any of the other warlock pets

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/9fda67d016798260dcab4b2110c00ab85e1fff2f

**Operating system:** 

windows 10

**crashlog**:
[unknown_worldserver.exe_[20-9_20-36-13].txt](https://github.com/TrinityCore/TrinityCore/files/5252366/unknown_worldserver.exe_.20-9_20-36-13.txt)

**Comment by Aokromes** [comment]
cannot reproduce on 

[20:54:47] TrinityCore rev. 2d6237f06ae6 2020-09-19 21:35:40 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by VincentVanclef** [comment]
@Aokromes wthh... think this could be corrupt db data?

**Comment by jackpoz** [comment]
You could try reproducing the issue at https://tcubuntu.northeurope.cloudapp.azure.com/ too

**Comment by VincentVanclef** [comment]
I have disabled pet happiness, so it never goes down (just commented out the happiness deduction in pet update loop). Other than that nothings changed. So a bit confused as to how you cannot reproduce it

**Comment by VincentVanclef** [comment]
> Tried reproducing it with https://wotlk.evowow.com/?spell=1122 and then https://wotlk.evowow.com/?spell=691 , no assertion triggered.
> 
> Are you using any custom change ?
> 
> Edit: ok, I was able to reproduce it but I don't remember the exact steps xD "Summon Imp" was involved too

neat! 😄

**Comment by jackpoz** [comment]
CurrentPet in the crashlog is https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=17252

**Comment by ckegg** [comment]
Crash as well, log is here
[crash-2020-09-19-18-27-28.log](https://github.com/TrinityCore/TrinityCore/files/5253617/crash-2020-09-19-18-27-28.log)

**Comment by jackpoz** [comment]
even in @ckegg crash CurrentPet is npc 17252

**Comment by ckegg** [comment]
Voidwalker this time
[crash-2020-09-21-13-40-40.log](https://github.com/TrinityCore/TrinityCore/files/5255777/crash-2020-09-21-13-40-40.log)

**Comment by jackpoz** [comment]
How to reproduce steps with .cheat cool and .cheat cast :

>Cast spell: 688
Cast spell: 688
Cast spell: 1122
Cast spell: 1122
Cast spell: 691

**Comment by Jildor** [comment]
I can reproduce the crash, but only after shauren's load pet async changes, before that I can't reproduce the crash

**Comment by Shauren** [comment]
Because that is when I added the ASSERT :D obviously it wouldn't crash before that
