### ISSUE TITLE
DB/GameObject: Brewfest wagons and tents overscaled or wrong objects

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25473]
**Description:**

The Brewfest wagons (entry 186737) right outside Orgrimmar, in Durotar, are too big, they seem to be upscaled to twice their intended height and length, possibly making their upscaled size closer to 4 times their original size. This enlargement of the wagons make them cover most of their connected tents, making it impossible (or nearly impossible) to interact with the Brewfest vendors inside the tent. Some of the Brewfest Revelers are therefore also standing either under or too close to the wagons, making it look like they are trying to stick their head inside the wagon structure.

![WoWScrnShot_092020_031131](https://user-images.githubusercontent.com/38162891/93692281-7aa64200-faf1-11ea-84f2-7c217d738761.jpg)

I have also tested disabling all game client addons and deleting the Cache folder several times to see if that makes any difference, but nothing changes.

**Expected behaviour:**

The Brewfest wagons outside Orgrimmar should be spawned normal size & scale, allowing player characters to interact with all vendors and revelers.

**Steps to reproduce the problem:**

1. Create / log in on a horde character.
2. `.tele Durotar` and go to the main Brewfest grounds outside Orgrimmar.
3. Visit all the tents and try to interact with all the vendors.

**Branch(es):**

3.3.5 (I have no idea what it looks like in master)

**TC rev. hash/commit:** 

TrinityCore rev. a724903b8b30 2020-09-19 23:40:48 +0200 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.20091
```

**Operating system:** Windows 10 Home x64 Version 2004 (OS Build 19041.388)

**Comment by illfated** [comment]
Also, output from `.gobject near` when standing close to Drohn's Distillery Apprentice:
```
31737 (Entry: 186717) - [Brewfest Banner X:1176.380005 Y:-4300.890137 Z:21.191401 MapId:1]  
 5548 (Entry: 186737) - [Brewfest Wagon Loaded X:1177.189941 Y:-4306.109863 Z:21.280500 MapId:1]  
31731 (Entry: 180749) - [Cheer Speaker X:1178.229980 Y:-4307.729980 Z:21.286699 MapId:1]  
31851 (Entry: 186189) - [Complimentary Brewfest Sampler X:1174.119995 Y:-4300.270020 Z:22.385799 MapId:1]  
31858 (Entry: 186189) - [Complimentary Brewfest Sampler X:1173.939941 Y:-4299.740234 Z:22.385799 MapId:1]  
31849 (Entry: 186189) - [Complimentary Brewfest Sampler X:1173.410034 Y:-4300.379883 Z:22.385799 MapId:1]  
31839 (Entry: 180698) - [Party Table X:1173.430054 Y:-4299.709961 Z:21.274599 MapId:1]  
31857 (Entry: 186189) - [Complimentary Brewfest Sampler X:1173.520020 Y:-4299.189941 Z:22.385799 MapId:1]  
31733 (Entry: 186682) - [Brewfest Beer Tent X:1174.660034 Y:-4308.129883 Z:21.314199 MapId:1]  
Found nearby gameobjects (distance 10.000000): 9
```

**Comment by illfated** [comment]
BTW, the same object is used in Dun Morogh, outside Ironforge, so I will modify the ticket title.

**Comment by illfated** [comment]
Screenshot from Dun Morogh, to show how ridiculously big they are compared to the Brewfest NPCs:

![WoWScrnShot_092020_114617](https://user-images.githubusercontent.com/38162891/93708638-2a9e9e00-fb38-11ea-911a-1034d4c09e72.jpg)

**Comment by illfated** [comment]
```
You are outdoors.
Map: 0 (Eastern Kingdoms) Zone: 1 (Dun Morogh) Area: 1 (Dun Morogh) Phase: 1
X: -5165.702148 Y: -629.753601 Z: 397.177948 Orientation: 4.869781
grid[22,30]cell[2,6] InstanceID: 0
 ZoneX: 49.377399 ZoneY: 39.247276
GroundZ: 397.175995 FloorZ: 397.175995 Have height data (Map: 1 VMap: 1 MMap: 1)
TrinityCore rev. a724903b8b30 2020-09-19 23:40:48 +0200 (3.3.5 branch) (Win64, Release, Static)
Online players: 1 (max: 1)
Active connections: 1 (max: 1) Queued connections: 0 (max: 0)
Server uptime: 9 Hours 1 Minute 5 Seconds.
Update time diff: 65.
31556 (Entry: 180353) - [Freestanding Torch 01 X:-5171.000000 Y:-628.935974 Z:397.175995 MapId:0]  
31568 (Entry: 186184) - [Thunderbrew Festive Keg X:-5160.049805 Y:-632.632019 Z:397.178009 MapId:0]  
31557 (Entry: 180353) - [Freestanding Torch 01 X:-5174.589844 Y:-626.750000 Z:397.175995 MapId:0]  
31468 (Entry: 186252) - [Fence X:-5167.180176 Y:-639.349976 Z:398.300995 MapId:0]  
31439 (Entry: 186681) - [Brewfest Food Tent X:-5175.350098 Y:-631.786011 Z:397.175995 MapId:0]  
Found nearby gameobjects (distance 10.000000): 5
```

![WoWScrnShot_092020_120401](https://user-images.githubusercontent.com/38162891/93708824-abaa6500-fb39-11ea-8ef0-e711a5301523.jpg)

**Comment by illfated** [comment]
Sort of interesting to see that if I stand on the other side of the Thunderbrew Festive Keg opposite to the Brewfest Wagon Loaded, the `.gobject near` default distance of 10.0 claims I am more than 10.0 away from the Brewfest Wagon Loaded (object entry 186737), even though it looks like it covers more than half of the Thunderbrew Festive Keg.

Now I am wondering if I need to look up all the wagon & tent objects to find out if some of them should be limited to the "Brewfest building" event and which ones are actually used in the Brewfest, or if this is only a scaling problem in Dun Morogh and Durotar.

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?event=24#objects (Brewfest objects)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=186737 (Brewfest Wagon Loaded)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=186681 (Brewfest Food Tent)

**Comment by offl** [comment]
Size is correct, checked in sniffs

**Comment by illfated** [comment]
Thank you for that solution. I got lost at looking for wrong size or scale.
