### ISSUE TITLE
preload certain areas

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25484]
**Description:**

with https://github.com/TrinityCore/TrinityCore/issues/24356 we have seen some areas causes high loads, maybe adding a setting to preload certain areas having gridunload disabled on those areas will allow to reduce the lags

**Expected behaviour:**

no lag.

**Steps to reproduce the problem:**

1. enable grafana
2. leave core to run for days
3. notice high spikes on certain areas

**Branch(es):**

both

**TC rev. hash/commit:** 

495d7d60d310

**Operating system:** N/R

**Comment by Aokromes** [comment]
Maybe we can add also:
preload areas where a innkepper is.
preload zones (to allow to preload cities)

**Comment by Faq** [comment]
Why closed?

**Comment by illfated** [comment]
Fair question, would be nice to have a closing comment about whether this has been deemed to belong to the linked issue or if it has been decided to discuss the topic in chat.
