### ISSUE TITLE
[3.3.5] Warrior wrong Block Value

### ISSUE THREAD

**Issue by Keader** [TrinityCore/TrinityCore#25482]
**Description:**

Ok we have a wrong calculation in SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT auras.
Right now we handle it in ```void Player::ApplyBaseModPctValue(BaseModGroup modGroup, float pct)```

Method content is:

```cpp
void Player::ApplyBaseModPctValue(BaseModGroup modGroup, float pct)
{
    if (modGroup >= BASEMOD_END)
    {
        TC_LOG_ERROR("spells", "Player::HandleBaseModValue: Invalid BaseModGroup/BaseModType (%u/%u) for player '%s' (%s)",
            modGroup, FLAT_MOD, GetName().c_str(), GetGUID().ToString().c_str());
        return;
    }

    AddPct(m_auraBasePctMod[modGroup], pct);
    UpdateBaseModGroup(modGroup);
}
```

Right now, we only use this method to handle with ```SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT```
It was added by ariel here: https://github.com/TrinityCore/TrinityCore/commit/c69a7d1223b2ce108a221e5cc70f76cd80ae6675

**But what is the problem?**

Spells with SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT should stack additively.

**Proof:**

http://worldoflogs.com/reports/up5rno2y5w0lta6h/xe/?s=2397&e=2556&x=%28sourceName+%3D+%22Rotface%22+and+fullType+%3D+101%29%0D%0Aor+spell+%3D+%22Glyph+of+Blocking%22+or+spell+%3D+%22Shield+Block%22%0D%0A%0D%0A

Warrior block is 2365. Removing Glyph of Blocking (10%) and Shield Mastery (30%) we have 1689 as base block value.
with shield block active, warrior crits 8108
so... 1689 (base) * 2.4  (shield block [100%] + shield mastery[30%] + glyph of blocking[10%]) * 2 (crit) = 8107.2

**Ok, but what's wrong in our current code?**

```AddPct()``` method body is ```return base += CalculatePct(base, pct);```
When we add shield mastery into it, we have:

m_auraBasePctMod[modGroup] = 1.0f <- base value
pct = 30

_final value = 1.3f_

it's correct value, yay.

But, when we add shield block into it:

m_auraBasePctMod[modGroup] = 1.3f
pct = 100

_final value = 2.6f_, because base value is 1.3f now, instead 1.0f, so we add 100% into 1.3, causing wrong value.

Correct handle should be (i belive):

```cpp
void Player::ApplyBaseModPctValue(BaseModGroup modGroup, float pct)
{
    if (modGroup >= BASEMOD_END)
    {
        TC_LOG_ERROR("spells", "Player::HandleBaseModValue: Invalid BaseModGroup/BaseModType (%u/%u) for player '%s' (%s)",
            modGroup, PCT_MOD, GetName().c_str(), GetGUID().ToString().c_str());
        return;
    }

    m_auraBasePctMod[modGroup] += CalculatePct(1.0f, pct);
    UpdateBaseModGroup(modGroup);
}
```

**Branch(es):** 3.3.5

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/bdd416fb77e4dbb807b2442adbf4ef3ea63bb27f

**Comment by CraftedRO** [comment]
I need to do more tests but this pr is most likely valid.
