### ISSUE TITLE
Blast the Gateway (11516) <wip>

### ISSUE THREAD

**Issue by nelegalno** [TrinityCore/TrinityCore#2548]
The mini-pet used in the quest is currently invisible and doesn't grow. After killing 10 Incandescent Fel Spark ( http://old.wowhead.com/npc=22323 ) the Living Flare (http://old.wowhead.com/npc=24916) it didn't change to Unstable Living Flare (http://old.wowhead.com/?npc=24958) .
I can't confirm if it received any of the 8x Fel Flareup (http://old.wowhead.com/spell=44944) when I killed the Fel Sparks.
According to the comments in http://old.wowhead.com/quest=11516 you need to get 8 and go to the gateway to complete the Q.

Rev: 5c762a1
TDB 335.11.41 + TC updates

<b>[EDIT]</b> Upon further investigation the Living Flare (24916) should cast on self the Fel Flareup (44944) spell each time a Incandescent Fel Spark (22323) is killed near it.

**Comment by Killyana** [comment]
Thanks to @DanLapps for the sniff, still the Flare lose the aura if the player enter in combat, it's a general issue for some spells, also the credit spell 44947 don't work.
``` sql
SET @Aura1:=44880;
SET @Flare:=24916;
SET @Grow:=44944;
SET @Visual:=44877;
SET @MiniExplosion:=44943;
SET @Unstable:=24958;
SET @Aura2:=46196;
SET @Explosion:=46225;
SET @credit:=44947;
SET @Flame:=22323;

UPDATE `creature_template` SET `unit_flags`=776, `faction`=1629, `InhabitType`=4, `AIName`='SmartAI' WHERE `entry`in (@Flare, @Unstable);
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`in (@Flame);

DELETE FROM `creature_template_addon` WHERE `entry`=@Flare;
INSERT INTO `creature_template_addon` (`entry`,`bytes2`,`auras`) VALUES (@Flare,1,@Aura1);
DELETE FROM `creature_template_addon` WHERE `entry`=@Unstable;
INSERT INTO `creature_template_addon` (`entry`,`bytes2`,`auras`) VALUES (@Unstable,1,@Aura2);

DELETE FROM `smart_scripts` WHERE `entryorguid` = @Flame AND `source_type` = 0;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @Flare AND `source_type` = 0;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @Flare*100 AND `source_type` = 9;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @Unstable AND `source_type` = 0;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @Unstable*100 AND `source_type` = 9;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @Unstable*100+1 AND `source_type` = 9;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(@Flare, 0, 0, 0, 54, 0, 100, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - Just summoned - React passif'),
(@Unstable, 0, 0, 0, 10, 0, 100, 1, 1, 20, 0, 0, 80, @Unstable*100+1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Unstable - los occ - Action list'),
(@Unstable*100+1, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 21, 20, 0, 0, 0, 0, 0, 0, 'Unstable - Action list - Follow'),
(@Unstable*100+1, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 19, 24959, 50, 0, 0, 0, 0, 0, 'Unstable - Action list - Move to pos'),
(@Unstable*100+1, 9, 2, 0, 0, 0, 100, 0, 10000, 10000, 0, 0, 11, @Explosion, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Unstable - Action list - Cast'),
(@Unstable*100+1, 9, 3, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 11, 44947, 0, 0, 0, 0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 'Unstable - Action list - Cast'),
(@Unstable*100+1, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Unstable - Action list - Despawn'),
(@Unstable, 0, 1, 2, 1, 0, 100, 1, 0, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 21, 20, 0, 0, 0, 0, 0, 0, 'Flare - ooc - follow'),
(@Unstable, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 64, 1, 0, 0, 0, 0, 0, 21, 20, 0, 0, 0, 0, 0, 0, 'Unstable - ooc- store target'),
(@Flare, 0, 1, 0, 23, 0, 100, 1, @Grow, 8, 0, 0, 80, @Flare*100, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - has aura x 8 - Action list'),
(@Flare*100, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 11, @MiniExplosion, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - Action list - cast'),
(@Flare*100, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 47, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - Action list - despawn'),
(@Flare*100, 9, 2, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 12, @Unstable, 5, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - Action list - Summon'),
(@Flare*100, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - Action list - despawn'),
(@Flame, 0, 0, 0, 0, 0, 100, 0, 3000, 3000, 5000, 5000, 11, 36247, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Flare - IC - Cast'),
(@Flame, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, @Flare, 40, 0, 0, 0, 0, 0, 'Flare - On death - Set Data'),
(@Flare, 0, 2, 0, 38, 0, 100, 0, 1, 1, 0, 0, 11, @Visual, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Flare - On data set- cast');

DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = @Visual;
INSERT INTO `spell_linked_spell` VALUES (@Visual, @Grow, 0, 'Flare Aura');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=@Visual;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(13,1,@Visual,0,0,31,0,3,@Flare,0,0,0,0,'','Only the Flare is a target for the spell.');
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceGroup`=1 AND `SourceEntry`=@Unstable;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`, `ErrorTextId`,`ScriptName`,`Comment`) VALUES
(22,1,@Unstable,0,31,3,24959,0,0,'','event require npc Unstable');

**Comment by tkrokli** [comment]
> Thanks to @DanLapps for the sniff, [ ... ]
> also the credit spell 44947 don't work.

OK, so the biggest problem is that the spell http://www.wowhead.com/spell=44947/quest-living-flare-credit does not work in current core/source. I wanted to ask if it would be of any help to compare the 3.3.5 version with info from the 6.x branch, but I just realized that 6.x probably depends on this issue being fixed just as much as 3.3.5 does. Do you think spell 44947 needs to be fixed? Does it have something to do with not being present in world.spell_dbc, only in the DBC file spell.dbc ? (I don't know.)

Listing the values for spell 44947 from Spell.dbc , only listing non-zero values (all others = 0 or NULL) ;

ID | Name | Type | (value = 0 or NULL for other lines) Value
---------------- | ---- | --- | -------:
0 | Entry | uint | 44947
4 | Attributes | uint | 384
6 | AttributesEx2 | uint | 4
28 | CastingTimeIndex | uint | 1
35 | procChance | uint | 101
46 | rangeIndex | uint | 6
68 | EquippedItemClass | int | -1
71 | Effect1 | uint | 16
86 | EffectImplicitTargetA1 | uint | 27
110 | EffectMiscValue1 | int | 11516
133 | SpellIconID | uint | 1
136 | SpellName_0 | string | Quest - Living Flare - Credit
152 | SpellNameFlag | uint | 16712190
169 | RankFlags | uint | 16712172
186 | DescriptionFlags | uint | 16712188
203 | ToolTipFlags (AuraDescriptionFlag) | uint | 16712188
216 | EffectDamageMultiplier1 | float | 1
217 | EffectDamageMultiplier2 | float | 1
218 | EffectDamageMultiplier3 | float | 1
225 | SchoolMask | uint | 1

**Comment by Killyana** [comment]
CreditSpell fixed.

**Comment by tkrokli** [comment]
> CreditSpell fixed.

Very good. :+1: How did you fix it, was any of my posted info helpful in any way? :smirk_cat:

**Comment by Killyana** [comment]
I don't know why the spell works now, yesterday it seems buggy, any way if someone can test it: use the item to summon the flare, than ".cast self 44877" repeat it 8 times, the npc will morph, start the wp than a explosion happen and the quest is completed.

**Comment by tkrokli** [comment]
Thanks, I will have a go at it as soon as my lvl 70 test char has finished investigating Valiant Keep.
(I am trying to find out if the issue # 14339 "Valiance rifleman don´t shot" is valid or if it is user error.)
