### ISSUE TITLE
aggro chaining

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25487]
**Description:**

since few days ago (max 15 days) some mobs are chaining agro to far from previous distances
before 1st icc boss you can see the same.

**Expected behaviour:**

you can do gundrak without pull 3 rinos at once.

**Steps to reproduce the problem:**

1. tele gundrak 
2. go the stairs before last boss
3. kill front rino.
4. try to kill side rinos without agro the rest
5. notice you pull 2 or 3 rinos instead one.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

2d6237f06ae6

**Operating system:** debian 10 x64.

**Comment by jackpoz** [comment]
anyone would like to spot which commit caused this by testing different versions of TC ? one can download binaries from appveyor

**Comment by Jildor** [comment]
I can reproduce it in old TC rev about 2017 and in latest rev, but I can't reproduce in rev from a month ago.
Is it really a bug or was it a bug a month ago?

**Comment by jackpoz** [comment]
Some tests:
- d52acf1b72c702637d10cce19e121435308e8410 : ❓

**Comment by offl** [comment]
I tested on aba07047a05fc46e5904f3084b6351850188f9b4 and didn't noticed any problem
Maybe https://github.com/TrinityCore/TrinityCore/commit/9f0b5526f070abc7460a31ea599e780f164a36b2 or https://github.com/TrinityCore/TrinityCore/commit/2d6237f06ae6b74bb8ebfe745d8c0f1ce440e2fe is the cause?

**Comment by Jildor** [comment]
But the current (and in rev about 2017) behaviour is wrong (you can pull 2 rinos)? Or rev from more than two weeks ago behaviour is wrong(you can pull 1 rino)? Any proof?

**Comment by offl** [comment]
The issue is CallAssistance radius is changed up to 15 yards from 10 yards for certain creatures
Of course current behavior is wrong because CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS is ignored

**Comment by Jildor** [comment]
happens after 39a436bd658790d39d3cfa64e18f49544475dfe3 / 0d152e932cdd986f62ae22bd9fc40569892a2453
I tried to revert these 2 commits and I can't reproduce it

**Comment by offl** [comment]
@Ovahlord take a look please

**Comment by Aokromes** [comment]
strange, i tried d52acf1b72c7 (39a436b-1) and it agroed.

**Comment by Ovahlord** [comment]
This smells like some hacky bullshit mechanic is going wild in that case. Gonna check Gundrak.

**Comment by jackpoz** [comment]
@Jildor could you test the issue on https://github.com/TrinityCore/TrinityCore/commit/d52acf1b72c702637d10cce19e121435308e8410 with a brand new TDB too ?

**Comment by Jildor** [comment]
I tested with clean TC rev https://github.com/TrinityCore/TrinityCore/commit/d52acf1b72c702637d10cce19e121435308e8410 and clean tdb (TDB 335.20082) and I can't reproduce it, after that, I updated to https://github.com/TrinityCore/TrinityCore/commit/0d152e932cdd986f62ae22bd9fc40569892a2453 (next 2 commits) and I can reproduce it.
I don't know what aokromes will have tried, but the issue is caused by spell focusing commits

.gm on
.go xyz 1844.237183 743.010559 135.908661 604
.die first center rino and drakkari raiders
.gm off
select another rino and use some taunt spell

**Comment by Aokromes** [comment]
i used a warlock or a mage with direct damage spells.
