### ISSUE TITLE
DB/Creature: Ironbark the Redeemed (wrong location?)

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25493]
**Description:**

I encountered him in **Dire Maul West** instance.

![Screenshot](https://i.ibb.co/Fg0QZ4S/Wo-WScrn-Shot-092420-200741.png)

**Expected behaviour:**

He is not supposed to appear there at all, if I am not mistaken?

**Steps to reproduce the problem:**

1. `.go creature id 14241`

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by dr-j** [comment]
This npc should not even be present in a fresh instance there shoud only be old ironbark see https://github.com/TrinityCore/TrinityCore/issues/14791
