### ISSUE TITLE
DB/Creature: Guard Slip'kik (Slip'kik's Savvy spell not casting)

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25496]
**Description:**

After completing the _Dire Maul Tribute Run_, after interacting with the friendly **Guard Slip'kik**, he does not buff me with the spell **Slip'kik's Savvy**.
Tested with a level 60 Human Paladin.

**Expected behaviour:**

He is supposed to buff me with the spell **Slip'kik's Savvy**, according to [Wowpedia](https://wow.gamepedia.com/index.php?title=Guard_Slip%27kik&oldid=2157316).

**Steps to reproduce the problem:**

1. Make sure you have spared **Guard Slip'kik**, have killed **King Gordok** and have received the **King of the Gordok** buff from **Mizzle the Crafty**.
2. `.go creature id 14323`
3. Interact with him.

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by dr-j** [comment]
Only if your character is level 63 or lower

**Comment by LEO33SoFo** [comment]
> Only if your character is level 63 or lower same as with the buffs from the other bosses if you are higher than level 63 these are not available

Sorry, I forgot to mention I am using a level 60 Human paladin character.
Edited my main post to add this information.

**Comment by dr-j** [comment]
Hmm by looking at how I scripted this https://github.com/TrinityCore/TrinityCore/commit/170794a0298364b13312a65abd8738ea298723dc looks like the gossip option will only work when npc is in event phase 2 which is set when you complete quest on the broken trap object this is probably wrong as should probably work if you bypassed boss by other means too

**Comment by dr-j** [comment]
~~~sql
UPDATE `smart_scripts` SET `event_phase_mask`='0' WHERE  `entryorguid`=14323 AND `source_type`=0 AND `id`=13 AND `link`=0;

**Comment by offl** [comment]
Why you guys constantly use INVOKER CAST even for spells which can be casted by creature on player?
