### ISSUE TITLE
multiple error in DBErrors.log

### ISSUE THREAD

**Issue by djmafiaem** [TrinityCore/TrinityCore#25507]
OS: Windows 10

**Description:**

full of errors in DBErrors.log
I compiled master = 8.3.7.35662 clean, everything was ok until I started worldserver.exe and it started with multiple errors.
I put on pastebin, in short the list is long    https://pastebin.com/gyzNjRPv

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 87448621acd2 2020-09-25 19:54:37 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Operating system:** Windows 10

**Comment by MaxtorCoder** [comment]
These are mostly warnings letting you know what to fix, don't worry about them.

**Comment by Aokromes** [comment]
7

**Comment by djmafiaem** [comment]
is it newly compiled, is it possible to have a duplicate? as I see it is that it does not exist ..

**Comment by offl** [comment]
He meant this issue is a duplicate of https://github.com/TrinityCore/TrinityCore/issues/15829

**Comment by illfated** [comment]
@djmafiaem : if you want to continue to follow up on the DBerrors.log issue, please use ticket #15829 for your posting.

**Comment by djmafiaem** [comment]
thanks for the information, respect
