### ISSUE TITLE
DB/Game Object: Ooze Covered Mithril Deposit in Stranglethorn Vale

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25509]
**Description:**

There is an unobtainable/unreachable Ooze Covered Mithril Deposit (single node only) in Stranglethorn Vale.

(Sceenshot wont post)

When I tried to look into fixing it, I realized it isn't meant to be there.

The location (from AOWOW):

<details>

![image](https://user-images.githubusercontent.com/66294837/94506242-4567c580-0250-11eb-9d60-04c21b5d90b0.png)

</details>

Classic location does not list Stranglethorn Vale:

https://classic.wowhead.com/object=123310/ooze-covered-mithril-deposit

Retail location does not list Stranglethorn Vale:

https://www.wowhead.com/object=123310/ooze-covered-mithril-deposit

**Note:** Neither mention Tanaris either but I think that's just AOWOW doing it's thing because it's close to Thousand Needles.

**Expected behavior:**

There should not be an Ooze Covered Mithril Deposit in Stranglethorn Vale.

Hypothesis: numbers seem similar to Feralas; switch them around and replace the 3 with 6 (potential type-o) and that belongs in Feralas.

**Steps to reproduce the problem:**

1. Go to location 32.1,74.9 in Stranglethorn Vale
2. Node is available to mine although it is unreachable; regardless, this is not Blizzlike and suggest this addition was not intentional.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. b038dd985fce 2020-09-25 01:38:22 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 7 64bit

**Comment by Aokromes** [comment]
i vote it was a typo that 

15430	123310	0	33	43	1	1	-14357	172,272	34,257	1,35	0	0	0,624897	0,780707	1800	100	1		0
it was mean to be
15430	123310	1	33	43	1	1	-4357	172,272	34,257	1,35	0	0	0,624897	0,780707	1800	100	1		0

**Comment by jackpoz** [comment]
you could check in the sql updates when it was added and what other things were added in that same updated

**Comment by Aokromes** [comment]
it looks it comes from UDB times.

**Comment by Aokromes** [comment]
(15429,123310,1,-6564,-3489,-81,3.289,0,0,0,0,123310,1800,100,0),(15430,123310,0,-14357,172.272,34.257,1.35,0,0,0.62478,0.780801,123310,1800,100,0),(15431,123310,1,-5388,28.633,26.82,2.631,0,0,0,0,123310,1800,100,0)

UDB_0.7.5_Core_4544_SD2_137.sql
