### ISSUE TITLE
DB/GameObject: Old Treasure Chest

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25508]
**Description:**

The **Old Treasure Chest** is not lootable, can't be clicked.

**Expected behaviour:**

It should be lootable, as mentioned in [Wowpedia](https://wow.gamepedia.com/index.php?title=Old_Treasure_Chest&oldid=2132869) and [Wowhead](https://www.wowhead.com/object=176944/old-treasure-chest#comments) comments.

**Steps to reproduce the problem:**

1. Pull the torch level at `.go xyz 231.872742 89.020958 95.823830 289 3.198875` to open the gate leading to it.
2. `.go gameobject id 176944` and try to click it.

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by offl** [comment]
GO_FLAG_NOT_SELECTABLE is set correctly here(checked in sniffs)
Dunno when it is supposed to be removed
Seems like people can farm this chest without killing bosses

**Comment by illfated** [comment]
To me, it seems odd that the chest should have the flag `GO_FLAG_NOT_SELECTABLE` unless it is a quest item, only available if you have got the quest, or like for some kind of class quest.

Then again, it is difficult to argue with sniff data, without knowing the details of the player character sniffing this information.

**Comment by wizzymore** [comment]
Seems like the flag goes away when using the level ( torch )
https://classic.wowhead.com/object=176944/old-treasure-chest#comments:id=2883566

**Comment by illfated** [comment]
Fair point. That is probably a fix implemented by Blizz to block players from looting the contents without using the torch lever.

**Comment by offl** [comment]
"becomes accessable" is not "becomes selectable" + here the chest is selectable but the door is closed, quite possible too much time has passed so the door just closed again  https://www.youtube.com/watch?v=ukBYx3vsPbY
Here the chest is selectable after touching the torch https://www.youtube.com/watch?v=zvMhLtmsak8
I'll try to check more sniffs to be sure it's how they implemented this

**Comment by illfated** [comment]
Sounds good to me. Thank you.

**Comment by offl** [comment]
Found nothing in sniffs, video shows clearly what happens
Comments also tells that this chest can be farmed without killing anything
