### ISSUE TITLE
DB/Quest: Seal of Ascension (2) (Emberstrife)

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25503]
**Description:**

When doing [this](https://wow.gamepedia.com/Seal_of_Ascension_(2)) quest, and I take control of **Emberstrife** black drake, there is no spell to use over my placed *Unforged Seal of Ascension* object. This problem has been mentioned before in issue #15021.

Click the image to see the video preview:
[![WoW-WotLK TrinityCore Seal of Ascension - Emberstrife bug](https://i.ibb.co/n1bRHgq/wow-trinitycore-bug.png)](https://www.youtube.com/watch?v=6aP71mKIIug "WoW-WotLK TrinityCore Seal of Ascension - Emberstrife bug")

Notice that in the video, I have modified the health, mana and damage of **Emberstrife** in the database for solo play in this case.

**Expected behaviour:**

According to a [Wowhead](https://www.wowhead.com/spell=16054/flames-of-the-black-flight#comments) comment, the controlled **Emberstrife** should have the spell [Flames of the Black Flight](https://www.wowhead.com/spell=16054/flames-of-the-black-flight) so I can cast it over the above-mentioned object, similarly to this [video](https://www.youtube.com/watch?v=HRL5jk-8aag).

**Steps to reproduce the problem:**

1. `.quest add 4743`
2. `.go xyz -5081.598633 -3972.727051 40.119518 1 2.313834`
3. Do the quest normally, take control of **Emberstrife** and check if the spell exists.

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by offl** [comment]
Can't reproduce. Maybe some of your addons blocks pet bar spells?
Did you completed similar quests before without problems?

**Comment by LEO33SoFo** [comment]
> Did you completed similar quests before without problems?

No, this is the first time completing such a quest.

> Can't reproduce. Maybe some of your addons blocks pet bar spells?

After I disabled all the addons, the spells appeared in the bar. Strangely, after enabling all the addons again the spells appeared normally. I can't say what was the cause of this problem.

But thanks, I never thought an addon might be the problem. Going to keep in mind in case a bug like this appears in the future. :slightly_smiling_face:

This issue can be closed now.

**Comment by offl** [comment]
Maybe cleaning cache also can help
