### ISSUE TITLE
WorldServer crashes after a minute: ASSERTION FAILED

### ISSUE THREAD

**Issue by azure-hu** [TrinityCore/TrinityCore#25513]
**Description:**
Only after a minute from starting the WorldServer, this error comes up:
src\server\database\Database\PreparedStatement.cpp:52 in PreparedStatementBase::setUInt32 ASSERTION FAILED:
  index < statement_data.size()
No need to login with any character. AuthServer works, no crashes there.
Crash log:
https://gist.github.com/azure-hu/68a57b78fa3e343b6a1dfe9d856d91c4

**Expected behaviour:**

Same settings, and dependencies are in use for weeks. WorldServer started and runned flawlesly before. 

**Steps to reproduce the problem:**

Built using these dependencies:
- Compiler: MSVC++ 2019 v16.7.5 (v19.27.29111.0)
- Boost: 1.71.0-msvc-14.2-64 
- OpenSSL: 1.0.2o-Win64
- Database includes: MariaDB v10.5.5
- CMake: 3.17.1
- CMAKE Extra Flags: CMAKE_SYSTEM_VERSION 6.1 (using Windows SDK 8.1)

CMAKE Settings: 
- SCRIPTS: dynamic
- USE_COREPCH: on
- USE_SCRIPTPCH: on
- WITHOUT_GIT: on
- WITHOUT_METRICS: on
- WITH_COREDEBUG: off (compilation fails in case of enabling it)
- WITH_DETAILED_METRICS: off
- WITH_DYNAMIC_LINKING: on
- WITH_STRICT_DATABASE_TYPE_CHECKS: off
- WITH_WARNINGS: on

These settings are in use from 2020 July, pulling changes from Git in every two weeks. No errors during compilation. 
First starting AuthServer, works as usual, no crashes, when trying to log-in.
Next, starting WorldServer, SQL changes had been applied, no errors, server starts.
After a minute, WorldServer suddenly crashes, displaying this error:
"src\server\database\Database\PreparedStatement.cpp:52 in PreparedStatementBase::setUInt32 ASSERTION FAILED:
  index < statement_data.size()"

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/0152878de5c1563cbe8d13fbf4f85839d741aabf

**Operating system:** Windows 10

**Comment by jackpoz** [comment]
try with a clean build, choosing "Build > Clean Solution" in Visual Studio and then building worldserver

**Comment by Aokromes** [comment]
i vote missing sql updates.

**Comment by azure-hu** [comment]
> 
> 
> try with a clean build, choosing "Build > Clean Solution" in Visual Studio and then building worldserver

Tried already 5 times. No success.

**Comment by jackpoz** [comment]
was that the full crashlog ? could you build in Debug and post the crashlog in Debug mode ?

**Comment by azure-hu** [comment]
> 
> 
> was that the full crashlog ? could you build in Debug and post the crashlog in Debug mode ?

https://gist.github.com/azure-hu/e8b6a38e6ae9a55033a73f64c8b10102

This is the output from the Crashes folder. It was built in Debug mode, but looks like the same for me. If I enable WITH_COREDEBUG, compilation fails because of a Windows 8.1 SDK bug.

**Comment by Aokromes** [comment]
WITH_COREDEBUG is not the way to get debug logs.

**Comment by azure-hu** [comment]
If it helps: https://gist.github.com/azure-hu/547805f8149824293a879c5949a0ef6d
After disabling AHBot, the crash doesn't happen until the first login.

**Comment by jackpoz** [comment]
do you have any local change ? could you try building in static mode instead of dynamic and posting the crashlog ?

your crash is about database.dll , I wonder if you didn't copy that dll and still using an old one. Did you copy worldserver.exe and all the dlls ? could you delete the old ones and let VS copy them ?

**Comment by azure-hu** [comment]
I cleaned up the installation directory before every compilation, and no local changes had been made. 
Tried to clone the repo again to an other directory, and figured out that somehow src/server/shared/DataStores/DBCfmt.h had an older version which has not been updated.
