### ISSUE TITLE
Civilian Recruit does not despawn at Valiance Keep

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#25519]
**Description:**
For some reason Civilian Recruit (entry 25220) does not despawn at Valiance Keep, causing massive Civilian Recruits pill up at waypoint id 13 (x:2303.02 y:5253.31 z:11.5058)

**Expected behaviour:**
They despawn at the end of waypoint

**Steps to reproduce the problem:**
1. .go xyz 2301 5256 11 571
2. then watch Civilian Recruit lining up at recruiter, move over, and stand still at side
![WoWScrnShot_093020_213011](https://user-images.githubusercontent.com/92148/94771726-c74d1100-036c-11eb-806d-c296a0c3742b.jpg)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
e811b9cdc2582cb1504e85b43d80696031fe2634

**Operating system:** CHANGEME OS
Debian 10.4

**Comment by dr-j** [comment]
They was scripted to despawn at last wp so idk why they arent now

**Comment by dr-j** [comment]
Confirmed checked on tc test server seems these are  for unknown reason stopping at wp13 when despawn is at waypoint 15 there was never any action to pause or stop wp at this point so no idea why waypoints are stopping at this point

**Comment by dr-j** [comment]
and these are summoned by spell so dont have despawn time set by us but seems the problem here is these are prematurely ending waypoints

**Comment by ckegg** [comment]
> 
> 
> They was scripted to despawn at last wp so idk why they arent now

At least I know it worked before 7dd51ae6d98cf6dd8ac71412aa689f888c7bf369

**Comment by jackpoz** [comment]
> At least I know it worked before [7dd51ae](https://github.com/TrinityCore/TrinityCore/commit/7dd51ae6d98cf6dd8ac71412aa689f888c7bf369)

did the whole SAI script work before that commit ? with all the waypoint pause timers specified in the script ?
