### ISSUE TITLE
Wrong Z coord in Dalaran's benchs

### ISSUE THREAD

**Issue by TheWinchesters** [TrinityCore/TrinityCore#25512]
**Description:**
When the char sits on a chair or bench in Dalaran, the Z coord changes and the character is not longer in Dalaran once seated.
I made a little video where it is possible to see how channels and the color of the name change.

https://streamable.com/w4uuw6

**Branch(es):** 3.3.5a
**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/0152878de5c1563cbe8d13fbf4f85839d741aabf Tested on TrinityCore Test realm

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24780
