### ISSUE TITLE
Detected 2 quest for WotLK from... Pandaria?

### ISSUE THREAD

**Issue by Cerveciento** [TrinityCore/TrinityCore#25526]
**Description:**
I have found these two quests that I have nothing clear that they should be part of the database.
In both cases wowhead identifies them as part of patch 5.2.0.16408
The value that appears in 'VerifiedBuild' is 12340, .... mmmm, ... it doesn't suit me.

https://www.wowhead.com/quest=9755/unknown-quest
https://www.wowhead.com/quest=11522/unknown-quest

**Fix**
``` sql
DELETE FROM `quest_template` WHERE `ID` IN(9755, 11522);
```
**Branch(es):** 3.3.5
**TC rev. hash/commit:** 53cb57b864d6
**Operating system:** debian 10

**Comment by Shauren** [comment]
These ids match other quest ids from wotlk era, most likely placeholder/wip/scrapped ideas that never shipped but for whatever reason became possible to query info in mop

Also "doesnt suit me" is not a valid reason to delete things

**Comment by offl** [comment]
> In both cases wowhead identifies them as part of patch 5.2.0.16408

No reason to trust this field in WH since it has nothing in common with the date when quest or creature was added in game. You can check other stuff and build\patch will be incorrect. I have no idea how WH updates this field

And yeah, we don't delete quest templates at all, in other cases instead they should be disabled
There's no reason to disable such quests, they're simply not available

**Comment by illfated** [comment]
Quest ID 9755 appears to be a precursive draft for the level 20 quest ID 9756
- https://www.wowhead.com/quest=9756/what-we-dont-know
(https://wow.gamepedia.com/What_We_Don%27t_Know...)

Quest ID 11522 is possibly a draft to create a follow-up to 2 existing Shattered Sun quests with relevance to the Shattered Sun Offensive storyline.
- https://www.wowhead.com/quest=11520/discovering-your-roots
- https://www.wowhead.com/quest=11521/rediscovering-your-roots

See also https://wow.gamepedia.com/Discovering_Your_Roots, https://wow.gamepedia.com/Rediscovering_Your_Roots

BTW, the quests 9755 and 11522 are currently disabled (TDB 335.20091/ 53cb57b864d6):
```sql
SELECT * FROM `disables` WHERE `entry` IN (9755, 11522);
```
```
sourceType   entry   flags  params_0  params_1  comment
----------  ------  ------  --------  --------  --------------------
    1         9755     0                        Deprecated quest:
    1        11522     0                        Deprecated quest:
```
