### ISSUE TITLE
Data too long for column 'salt' at row 1

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#25533]
**Description:**

Like out of nowhere, authserver started to report issues of out of range data for salt/verifier columns. Nothings been changed, this started while the realm was running smoothly.

![image](https://user-images.githubusercontent.com/541084/95000931-7ab04280-05c5-11eb-81bd-82b04a2ed4a5.png)

Theres absolutely nothing changed to the auth server or tables or anything, this just started happening 15 mins ago out of nowhere. Is there something done with the generation of the salt/verifier thats broken now because of the date perhaps? Idk if thats used to generate it :/

**Expected behaviour:**

Shouldnt happend

**Steps to reproduce the problem:**

1. Try change password of any account

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

60ded4ea4796b134b1dbdfb7071201c9ba3a9c71

**Operating system:** windows 10

**Comment by Faq** [comment]
Why closed?

**Comment by illfated** [comment]
Good question. The issue ticket looks fairly valid to me.

**Comment by VincentVanclef** [comment]
It was an internal error, somehow a migration occoured which set the length of the salt/verifier columns to 60 instead of 32 >.< It happened behind the scenes so didnt catch until a lof of investigations.. so it was my own fault so to speak, should have written that here, i apologize

**Comment by illfated** [comment]
Thanks. Always good to know why an issue ticket gets closed.
