### ISSUE TITLE
DB/Quest: Brew of the Month Club (ID 12421) CompletionText missing (Ray'ma)

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25535]
**Description:**

<details>
<summary>Details</summary>

![WoWScrnShot_100420_071004](https://user-images.githubusercontent.com/38162891/95007484-d8b64780-0610-11eb-8faf-0aeaf78dd183.jpg)

</details>

Compare the following 2 pages (as an indicator of what is missing in TDB):
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12421
- https://www.wowhead.com/quest=12421/brew-of-the-month-club (Durotar/Orgrimmar)

Sauce:
- https://www.wowhead.com/item=37737/brew-of-the-month-club-membership-form (Durotar)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=37737
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=27489#ends
- https://www.wowhead.com/npc=27489/rayma#ends

```sql
SELECT * FROM `quest_request_items` WHERE `ID` IN (12278, 12306, 12420, 12421);
```
```sql
 ID    EmoteOnComplete  EmoteOnIncomplete    CompletionText                               VerifiedBuild
-----  ---------------  -----------------  ---------------------------------------------  -------------
12278         0                0           Do you have your membership forms filled out?       12340
12306         0                0           Do ya have your membership forms filled out?        12340
12420         0                0           Do you have your membership forms filled out?       12340
```

**Expected behaviour:**

```sql
SELECT * FROM `quest_request_items` WHERE `ID` IN (12278, 12306, 12420, 12421);
```
```sql
 ID    EmoteOnComplete  EmoteOnIncomplete    CompletionText                               VerifiedBuild
-----  ---------------  -----------------  ---------------------------------------------  -------------
12278         0                0           Do you have your membership forms filled out?       12340
12306         0                0           Do ya have your membership forms filled out?        12340
12420         0                0           Do you have your membership forms filled out?       12340
12421         0                0           Do ya have your membership forms filled out?        12340
```

Noticed also that Ray'ma is not listed in TDB as quest ender for the parallel quest 12306 (from item 37599)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12306
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=37599
- https://www.wowhead.com/quest=12306/brew-of-the-month-club
- https://www.wowhead.com/item=37599/brew-of-the-month-club-membership-form

```sql
SELECT * FROM `creature_questender` WHERE `id`= 27489;
```

```sql
 id    quest
-----  -----
27489  12421
```

***

**Suggested solution:**

```sql
-- Ray'ma <Brew of the Month Club> (27489)
DELETE FROM `quest_request_items` WHERE `ID`= 12421;
INSERT INTO `quest_request_items` (`ID`,`EmoteOnComplete`,`EmoteOnIncomplete`,`CompletionText`,`VerifiedBuild`) VALUES
(12421, 0, 0, "Do ya have your membership forms filled out?", 12340);

DELETE FROM `creature_questender` WHERE `id`= 27489 AND `quest`= 12306;
INSERT INTO `creature_questender` (`id`, `quest`) VALUES (27489, 12306);
```

***

**Steps to reproduce the problem:**

1. on a horde character, target self and do `.additem 37737`
2. Right-click the item and accept the quest (quest ID 12421)
3. `.tele ValleyOfSpirits` and go inside the troll hut to talk to Ray'ma (quest ender)
4. Open the quest gossip and notice that there is no gossip text, only headings & icon.

**Branch(es):**

3.3.5 -- maybe master too (check master TDB)

**TC rev. hash/commit:** 

TrinityCore rev. 60ded4ea4796 2020-10-03 02:37:58 +0300 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.2
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 3901434544 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20091

**Operating system:** Windows 10 (x64) Version 2004 Build 19041.508

**Comment by offl** [comment]
> Noticed also that Ray'ma is not listed in TDB as quest ender for the parallel quest 12306 (from item 37599)

Deprecated

**Comment by illfated** [comment]
> > Noticed also that Ray'ma is not listed in TDB as quest ender for the parallel quest 12306 (from item 37599)
> 
> Deprecated

Deprecated? Does that mean that the wowhead page is lazily forgotten, because the information for that quest & item is shown as active over there?

**Comment by offl** [comment]
There should be only one quest-start item available from vendors
I have no idea why there's two of them but one of them is definitely not available
Maybe I'll find something in sniffs

**Comment by illfated** [comment]
:-) OK, very well. Thank you for spending time on this. I was just a bit confused.
Also, I have this feeling that something during the last year or 2 changed the signs.
(Yes, I know. I can test a much older revision to see if the signs were OK before.)

**Comment by offl** [comment]
I wasn't able to find something in sniffs but lower id is not listed in wowhead in sold-by section
view-source:http://web.archive.org/web/20100913090856/www.wowhead.com/item=37599
There's no sold-buy section at all
Higher id item is here
view-source:http://web.archive.org/web/20100918030255/http://www.wowhead.com/item=37737
And sold-by section is available

First item was added in 2.4.3, completing quest unlocks vendor. Shortly after Brewfest Blizz launched WotLK. Probably they created duplicates for both items because it's somehow related to conditions for vendor.

**Comment by illfated** [comment]
Thanks. Good job checking those facts. Well done.
