### ISSUE TITLE
DB/Vehicle: add missing passenger in Ulduar - Salvaged Demolisher

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25531]
**Description:**

https://youtu.be/23O94GmA_tE?t=77 <-- min 1:17 we can see how https://www.wowhead.com/npc=33620/earthen-stoneshaper is mounted on the left side of the demolisher, and min 1:21 we can see how demolisher is destroyed and Earthen Stoneshaper is dismounted, so we need add Earthen Stoneshaper in the left (seat2 I think)

**Fix:**

```sql
DELETE FROM `vehicle_template_accessory` WHERE `entry`=33109 AND `accessory_entry`=33620 AND `seat_id`=2;
INSERT INTO `vehicle_template_accessory` (`entry`,`accessory_entry`,`seat_id`,`minion`,`description`) VALUES
(33109,33620,2,1,'Salvaged Demolisher - Earthen Stoneshaper');
```

**Steps to reproduce the problem:**

1. go to ulduar and mount in the demolisher

**Branch(es):**

3.3.5

**TC rev. hash/commit:** ed567014cc8e3d2cf94bd4d1b707bea3bc3c63dc

**Comment by offl** [comment]
Yep, shown in sniffs

**Comment by Rushor** [comment]
amazing!
