### ISSUE TITLE
Potentially Incorrect Forced Speed Change Tracking with Speed Auras and  CMSG_FORCE_SPEED_CHANGE_ACK Packets

### ISSUE THREAD

**Issue by HelloKitty** [TrinityCore/TrinityCore#25534]
**Description:**

Logging out as a Player with speed changing auras causes Player::m_forced_speed_changes tracking to desync from expectations.

Not sure if this is intended but it seems wrong. Also seems to be a result of Unit::SetSpeedRate incrementing but client never Acking speed change in this case.

**Expected behaviour:**

Not 100% sure but I think this is a problem, as the tracking is skewed.

**Steps to reproduce the problem:**

1. Apply Sprint 2983
2. Log off with the Aura
3. Log back in
4. See that m_forced_speed_changes is now potentially descyned.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Unknown

**Operating system:** Windows 10 64-bit

**Comment by HelloKitty** [comment]
Not entirely sure how it's even suppose to work to be honest. When you log in normally the forced changes are 0. So all acks go through the path of checking what was sent, afew lines below.

When aura is reapplied during logout, it'll never seem to go through that path.

**Comment by Aokromes** [comment]
this issue is still valid?
