### ISSUE TITLE
DB/Locale/deDE - Missing translations

### ISSUE THREAD

**Issue by SneakyV** [TrinityCore/TrinityCore#25542]
**Description:**
... and again a few German translations.
A few more translations - wowhead compliant, but not 100% checked.

**Branch(es):**
3.3.5

[german-locales-3.zip](https://github.com/TrinityCore/TrinityCore/files/5328015/german-locales-3.zip)

**Comment by offl** [comment]
I removed all English texts from quest_request_items_locale, I managed to find only one German text for 7787
Full list: 5284, 6148, 5944, 6187, 6622, 5055, 5054, 4741, 4262, 2994
