### ISSUE TITLE
[3.3.5] Guild bank tabs dissapear

### ISSUE THREAD

**Issue by VincentVanclef** [TrinityCore/TrinityCore#25543]
**Description:**

Guild bank tabs dissapear, randomly and with no sql errors/console warnings. The tabs are still in guild_tabs and guild_bank_items still contain items. Yet the bank is empty ingame, and you can buy new tabs..

![image](https://user-images.githubusercontent.com/541084/95135133-46bf5380-0764-11eb-8901-fc625dd50048.png)

![image](https://user-images.githubusercontent.com/541084/95134932-f7792300-0763-11eb-85f3-29ab9cbbdf34.png)

ive tripple checked the guild im in is ID 12 etc. 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

b6e205f7ef32f7b82644043d82a808e67cc9acb2

**Operating system:** ubuntu

**Comment by VincentVanclef** [comment]
What the fuck.. restarted and now they are back xdd will open again if and try see if i found something..

**Comment by illfated** [comment]
I am guessing poor synch between addons, game cache and server/DB (could be wrong, of course).
