### ISSUE TITLE
Zul'Gurub - Edge of Madness event bugged

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25545]
**Description:**

No boss is spawned when using the **Gurubashi Mojo Madness** item on the **Brazier of Madness** in _Edge of Madness_, _Zul'Gurub_.
There are comments mentioning this problem in the issue #24427 too.

**Expected behaviour:**

A boss based on an event should be spawned correctly when using that item according to [Wowpedia](https://wow.gamepedia.com/Edge_of_Madness?oldid=2324062).

**Steps to reproduce the problem:**

1. `.additem 19931`
2. `.go gameobject id 180327`
3. Click on the **Brazier of Madness** and check if the event boss is spawned.

P.S: I encountered this bug just via normal progression, without using GM commands.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by offl** [comment]
Useful info in https://github.com/TrinityCore/TrinityCore/issues/24427#issuecomment-640257686 and below
