### ISSUE TITLE
[3.3.5] stitching monster cannot be killed.

### ISSUE THREAD

**Issue by dusksoft** [TrinityCore/TrinityCore#25548]
**Description:**

Darkshire, night watchmen don't seem to be united，stitching monster cannot be killed.

**Expected behaviour:**

Kill the stitching monster

**Branch(es):**

CHANGEME 3.3.5, master or both

![1](https://user-images.githubusercontent.com/2236995/95373426-8f674000-090f-11eb-9355-0b7e62278f4e.png)

**Comment by Treeston** [comment]
The monster in question is [Stitches](https://wow.gamepedia.com/Stitches) ([NPC 412](https://www.wowhead.com/npc=412/stitches))

**Comment by Treeston** [comment]
I assume this is `3.3.5` - what git revision are you running @dusksoft?

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/issues/22369

**Comment by illfated** [comment]
Stitches is not currently spawned (or at least not without some help) in the 3.3.5 branch, right?

**Comment by offl** [comment]
Seems like yes

**Comment by ratkosrb** [comment]
Stitches should only spawn after turning in this quest https://classic.wowhead.com/quest=252/translation-to-ello

**Comment by Jinnaix** [comment]
This issue is not about stitches not spawning (as I checked it last time, spawning worked) but most of the npc guards ignoring him. Therefore he will be in darkshire and slaying people until a high level guy will kill him or grid unloads (whatever comes first). On top of that, multiple turn ins of that quest lead to multiple stitches having a party in darkshire.

**Comment by Treeston** [comment]
Multiple stitches could be avoided with spawn groups, those didn't exist yet when the original issue was made.

No idea about the guards thing offhand.

**Comment by offl** [comment]
We already have #22369 with attempts to fix this

**Comment by dr-j** [comment]
The watchers are not all same faction some are faction 11 or 12 and the others are 53 or 56 the ones which are faction 11 or 12 won’t attack
