### ISSUE TITLE
mmaps_generator Segmentation fault

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#25558]
**Description:**

crash when building mmaps, happened since b6e205f7ef32f7b82644043d82a808e67cc9acb2 and also on 3947e4cb57d4c6adb78cd3cb52718bb88add91fc. Tried recompiling source many time, reinstall new Debian OS, copied new client Data folder and still getting Segmentation fault error.
[crash.log](https://github.com/TrinityCore/TrinityCore/files/5360793/crash.log)

**Expected behaviour:**

build mmap without crashes

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

3947e4cb57d4c6adb78cd3cb52718bb88add91fc

**Operating system:**

Debian 10.4

**Comment by jackpoz** [comment]
>Finished. MMAPS were built in 1 Hour 4 Minutes 33 Seconds.

Tested on Windows 10 x64.

Your crashlog shows mapID=571, tileX=19, tileY=28 . If you try running again the tool, do you get the crashlog in the same map/tile ?

Could you try running ```mmaps_generator 571 --tile "19,28"``` ? and maybe ```mmaps_generator 571 --tile "28,19"``` too in case I got the x/y swapped.
Could you try passing ```--threads 1``` parameter too ?

**Comment by ckegg** [comment]
It actually held not on the same place. Ran 4 other times and stopped on different maps/tile
[crash2.log](https://github.com/TrinityCore/TrinityCore/files/5362143/crash2.log)
[crash3.log](https://github.com/TrinityCore/TrinityCore/files/5362144/crash3.log)
[crash4.log](https://github.com/TrinityCore/TrinityCore/files/5362145/crash4.log)
[crash5.log](https://github.com/TrinityCore/TrinityCore/files/5362146/crash5.log)

I am trying --threads 1 right now and it gonna take couple good hours...

**Comment by ckegg** [comment]
fixed from https://github.com/TrinityCore/TrinityCore/pull/25625
