### ISSUE TITLE
Core/MMAPs: mmap extractor doesn't work with custom maps

### ISSUE THREAD

**Issue by intra32** [TrinityCore/TrinityCore#25561]
**Description:**
Generating mmaps for custom maps using newer versions (>v9) of the map extractor doesn't work. This broke when changing from `MMAP_VERSION` 9 to 10.
Please see @stoneharry's comment below for a better example.

**Expected behaviour:**
This did work on `MMAP_VERSION 9`. Knowing why this does not work anymore can be helpful both for improving WMO and ADTauthoring tools to generate data the mmaps extractor can work with and possibly seeing if there's a reasonable solution to making the mmaps_extractor able to handle custom ADT/WMO files that worked with older versions.

**Steps to reproduce the problem:**
I have included both a WMO file for testing and a MPQ patch version of the said file.
Extract mmaps including the attached file to reproduce the issue.
[wmo-files.zip](https://github.com/TrinityCore/TrinityCore/files/5361025/wmo-files.zip)

**Branch(es):** `3.3.5` *(likely both)*

**TC rev. hash/commit:**  3ec98bf2410bb8fa73fe6b386a6e766bef575e97

**Operating system:** Microsoft Windows 10 Home

**Comment by Faq** [comment]
dublicate of #25558 ?

**Comment by intra32** [comment]
> dublicate of #25558 ?
No, this issue is unrelated to that one.

**Comment by stoneharry** [comment]
All of my custom maps have broken pathfinding in mmap versions > 9. 

For example, here is one map:

In game: https://i.imgur.com/OvCWVQ5.jpg
Noggit: https://i.imgur.com/9S0ZX7X.jpg
Mmap mesh generated: https://i.imgur.com/BM5Zecc.png

I don't know how it goes so wrong. Reverting to v9 works perfectly.

**Comment by stoneharry** [comment]
3947e4cb57d4c6adb78cd3cb52718bb88add91fc may fix this, not tested. This fixes the slope angle change that looked pretty suspect to me.

**Comment by Shauren** [comment]
That is weird, wouldn't it normally imply that its map/vmap extractors that are not happy with custom adts since mmaps_generator works on extracted maps and vmaps, not directly on client files?

**Comment by jackpoz** [comment]
what is the actual issue (other than "doesn't work") ?

**Comment by stoneharry** [comment]
> what is the actual issue (other than "doesn't work") ?
> did you try with the commit right before mmaps version changed from 9 to 10 ? you posted some screenshots, shouldn't there be a v9 screenshot compared to a v10 from recastdemo ?

I tested with v9, v10, v11, and v12. v9 is the only version it works with. I tested by reverting the three commits I linked one at a time.

I tested this all a few months ago, so I dug around in my Discord history to find the screenshots. I don't have any more information to provide at this point I'm afraid, but meshes normally look quite similar to their in-game counterparts, at a slightly lower resolution.

The mesh is very wrong in versions higher than v9. I'm not sure how to describe it, the surface is raised above normal and whole sections of the map are missing.

**Comment by jackpoz** [comment]
well, you should get the --debugOutput of v9, then of v10 (which might even required to re-extract maps and vmaps), then of the parent commit of v10 (so latest v9 commit) and see how they look in recast demo.

**Comment by stoneharry** [comment]
From what I remember doing it before, v10, v11, and v12 pretty much generate the same (incorrectly, the same as the previously provided screenshot). So you could say v10 is the breaking version, unless v13 fixes it.

Here is the output from v9: https://i.imgur.com/vjM0Qnk.jpg

**Comment by jackpoz** [comment]
And how does it look with the parent commit of v10, aka last v9 commit ?

**Comment by stoneharry** [comment]
> And how does it look with the parent commit of v10, aka last v9 commit ?

I imagine the same. @intra32 do you have time to test this?

**Comment by intra32** [comment]
> > And how does it look with the parent commit of v10, aka last v9 commit ?
> 
> I imagine the same. @intra32 do you have time to test this?

Sorry, don't have the opportunity to look into the recast debugger right now. :(

**Comment by intra32** [comment]
Update, tried it with a fresh build pulled from latest sources as of 28th december and pathfinding around a custom WMO seems to work. I have no tested it extensively, but if the issue arises again I will raise a new issue and try investigate it using the Recast debugger.
