### ISSUE TITLE
LINK : fatal error LNK1181:

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#25562]
1> ------ Build started: project: bnetserver, Configuration: Release x64 ------
1> cmake_pch.cxx
1> Main.cpp
1> LoginRESTService.cpp
1> Session.cpp
1> SessionManager.cpp
1> SslContext.cpp
1> AccountService.cpp
1> AuthenticationService.cpp
1> ConnectionService.cpp
1> GameUtilitiesService.cpp
1> ServiceDispatcher.cpp
1> WheatyExceptionReport.cpp
1> ServiceWin32.cpp
1> LINK: fatal error LNK1181: cannot open input file ".. \ shared \ Release \ shared.lib"
1> Build of project "bnetserver.vcxproj" completed with an error.
========== Build: success: 0, errors: 1, no changes: 0, skipped: 0 ==========
 
Отправить отзыв
История
Сохраненные
Сообщество

1>------ Сборка начата: проект: bnetserver, Конфигурация: Release x64 ------
1>cmake_pch.cxx
1>Main.cpp
1>LoginRESTService.cpp
1>Session.cpp
1>SessionManager.cpp
1>SslContext.cpp
1>AccountService.cpp
1>AuthenticationService.cpp
1>ConnectionService.cpp
1>GameUtilitiesService.cpp
1>ServiceDispatcher.cpp
1>WheatyExceptionReport.cpp
1>ServiceWin32.cpp
1>LINK : fatal error LNK1181: не удается открыть входной файл "..\shared\Release\shared.lib"
1>Сборка проекта "bnetserver.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 0, с ошибками: 1, без изменений: 0, пропущено: 0 ==========

**Comment by MaxtorCoder** [comment]
Please follow the issue template :D

**Comment by Shauren** [comment]
ffs why do people cut off compile logs and paste only the final part...
Error says it cannot find `shared.lib` which means that something from `shared` project didnt compile successfully, LONG TIME BEFORE the end

**Comment by rem999** [comment]
Sorry to launch Ashaman\Core. You have to reinstall the operating system. Therefore, I launched an abbreviated version. Completely launched everything works. I collected everything. Thanks!

**Comment by MaxtorCoder** [comment]
> 
> 
> Sorry to launch Ashaman\Core. You have to reinstall the operating system. Therefore, I launched an abbreviated version. Completely launched everything works. I collected everything. Thanks!

Stop coming to this page if it's not even related with TrinityCore to begin with. The names don't even match.
