### ISSUE TITLE
DB/Texts: Wrong text word in a sentence in quest turn-in window of C'Thun's Legacy quest

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25576]
**Description:**

The current sentence in the quest turn-in window of _C'Thun's Legacy_ quest is **Lady \<name\>, you have freed us of its grasp.**

![Screenshot](https://i.ibb.co/PYJ8wFp/Wo-WScrn-Shot-101420-053157.jpg)

**Expected behaviour:**

The correct one should be **Lord \<name\>, you have freed us of its grasp.**, based on gender I guess?

[Wowpedia](https://wow.gamepedia.com/C%27Thun%27s_Legacy).
[Wowhead](https://www.wowhead.com/quest=8801/cthuns-legacy).

**Steps to reproduce the problem:**

1. `.additem 21221` and accept the quest from it.
2. `.go creature id 15379`
2. Turn in the quest and check the text.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by illfated** [comment]
Suggested solution:
```sql
-- C'Thun's Legacy
UPDATE `quest_request_items` SET `CompletionText`= "$gLord:Lady; $N, you have freed us of its grasp." WHERE `ID`= 8801;
```
