### ISSUE TITLE
DB/Creature: Andorgos

### ISSUE THREAD

**Issue by LEO33SoFo** [TrinityCore/TrinityCore#25577]
**Description:**

**Andorgos** does not offer me to teleport to the _Twin Emperors_' room when they are killed and to _C'Thun_'s room when _Ouro_ is killed.

**Expected behaviour:**

**Andorgos** should offer me to teleport to their respective rooms if I understood correctly when these bosses are killed, according to this [Wowhead](https://www.wowhead.com/npc=15502/andorgos#comments:id=294346) comment.

**Steps to reproduce the problem:**

1. Enter the _Temple of Ahn'Qiraj_ by any means necessary.
2. Kill the _Twin Emperors_.
3. `.go creature id 15502`
4. Click on her and check if she offers to teleport.
5. Do the same thing with _C'Thun_.

Just for information, when using `.instance getbossstate` I get:
```
Boss id 1 state is 3 (DONE).
Boss id 2 state is 3 (DONE).
Boss id 3 state is 3 (DONE).
Boss id 4 state is 3 (DONE).
Boss id 5 state is 3 (DONE).
Boss id 6 state is 3 (DONE).
Boss id 7 state is 3 (DONE).
Boss id 8 state is 3 (DONE).
Boss id 9 state is 5 (TO_BE_DECIDED).
```

Notice: I tested this as a Solo player.

P.S: I encountered this bug just via normal progression, without using GM commands, except when _Ouro_ needs to be spawned with commands because of bug #22644.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

9d959123e68020a83c780f53a967b3589cb70786

**Operating system:** Windows 7 Enterprise 64bit

**Comment by offl** [comment]
Some stuff was added in https://github.com/TrinityCore/TrinityCore/commit/79ff72d268c67279056a1bf74533b6edb44b48db
