### ISSUE TITLE
[3.3.5] "$n" is shown instead of the player's name.

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25602]
**Description:**

Sometimes "$n" is shown instead of the players name. 
Like: "$n, great to see you!".

**Expected behaviour:**

It should display the player's name.

**Steps to reproduce the problem:**

Can't tell you something specific, i just noticed it while playing from time to time. 

**Branch(es):**

3.3.5 October 2020 release

**Comment by Treeston** [comment]
This means that the talk action in question is missing player target info.

Need to know which lines are affected to do anything useful.

PS: 

> 3.3.5 October 2020 release

That's not a revision hash. You can find the revision hash you are running in the final line after you startup the worldserver.

**Comment by Wombyte2** [comment]
> 
> 
> This means that the talk action in question is missing player target info.
> 
> Need to know which lines are affected to do anything useful.
> 
> PS:
> 
> > 3.3.5 October 2020 release
> 
> That's not a revision hash. You can find the revision hash you are running in the final line after you startup the worldserver.

I see. Unfortunately i didn't wrote down everytime when that happend. 

"TrinityCore rev. 07845b4eceed 2020-10-05 01:55:35 +0300 (3.3.5 branch) (Win64, Release, Static)"
Thats the last line after starting the worldserver. Is that what i should write instead of "3.3.5 October 2020 release"?

**Comment by offl** [comment]
> Thats the last line after starting the worldserver. Is that what i should write instead of "3.3.5 October 2020 release"?

Yes

There are thousands of texts and without knowing NPC entry this issue is impossible to fix. It's not generic bug, at least so far.
If you encounter this issue again, add npc entry here or in another issue

**Comment by illfated** [comment]
> **Description:**
> 
> Sometimes "$n" is shown instead of the players name.
> Like: "$n, great to see you!".
> 
Yes, that kind of behaviour is familiar, but to solve the issue, we need to know the exact NPC name or ID/entry.
When you provide the exact NPC where you see this issue, we can fix the problem and commit a DB SQL update.

> **Expected behaviour:**
> 
> It should display the player's name.
> 
Yes, we are able to solve that as long as we know which NPC displays this gossip dialog issue.

> **Steps to reproduce the problem:**
> 
> Can't tell you something specific, i just noticed it while playing from time to time.
> 
We need to know each and every individual NPC name or ID/entry to find the issue and fix it.
Please make a note of name and/or ID/entry for those, to provide the required information.

> **Branch(es):**
> 
> 3.3.5 October 2020 release

TrinityCore rev. 07845b4 2020-10-05 01:55:35 +0300 (3.3.5 branch) (Win64, Release, Static)

Thank you for reporting, looking forward to a new ticket or an update here with the required information to solve the issue(s).
