### ISSUE TITLE
[3.3.5] If you win an item with "Need Before Greed" and your inventory is full, you need to reopen the corpse to collect it

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25605]
**Description:**

If you win an item with "Need before Greed", but your inventory is full, you can't collect the item from the corpse until you reopen it, because it will tell you that you have no permission to collect this. 

**Expected behaviour:**

You should be able to collect an item that you already won, without the need to reopen the corpse.

**Steps to reproduce the problem:**

1. Loot any corpse where a at least green item is inside so that "Need before Greed" shows up **while your inventory is full.**
2. Win the item and don't close the corpse (the loot interface).
3. Throw out something of your inventory so that you have a free place for the item.
4. Click on the item so that you can collect it. It will tell you that you have no permission to collect that item (that you already won).
5. Reopen the loot interface of that corpse. Now you can collect the item.

**Branch(es):**

3.3.5 rev. 07845b4

**Comment by Aokromes** [comment]
stop writing "3.3.5 October 2020 release" write exact version

**Comment by Wombyte2** [comment]
> 
> 
> stop writing "3.3.5 October 2020 release" write exact version

Please tell me what my version is then instead of blaming me:
TrinityCore rev. 07845b4 2020-10-05 01:55:35 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by Treeston** [comment]
The highlighted part (07845b4) is the revision you're running.

**Comment by Shauren** [comment]
Client does not support this kind of "slot ownership" update on loot, not even current retail client can

**Comment by Wombyte2** [comment]
> 
> 
> The highlighted part ([07845b4](https://github.com/TrinityCore/TrinityCore/commit/07845b4eceed5ea1e6a706325f7ab6e6b0954335)) is the revision you're running.

I updated it on all my posts, thanks.

**Comment by Wombyte2** [comment]
> 
> 
> Client does not support this kind of "slot ownership" update on loot, not even current retail client can

ah okay. Last server i had was trinitycore version from 2016 where it did work, so i thought this might be an issue.

**Comment by illfated** [comment]
> > stop writing "3.3.5 October 2020 release" write exact version
> 
> Please tell me what my version is then instead of blaming me:

Just to help you deal with comments like that later on: that type of comment is meant to be read in a neutral tone, especially those from Aokromes. Those comments are not meant to deter you from contributing, it is meant as a pointer to what TC considers to be guidelines in this repository.

> I'm new here, i'm taking my time to help you all improve this by writing bug reports, so there's really no reason to blame me instead of helping and telling me how to find exactly the correct version!

Fair enough, thank you for contributing. Just be aware that we appreciate even more when tickets are filled in by using the complete issue ticket template, as well as providing as much precise information as possible. Our goal here is to help get issues resolved, so most of the users try to state facts in a neutral tone, without any bad intentions.

Please also note that for those of us who have used this repository for many years, maybe decades, it can sometimes be boring to repeat ourselves by reiterating guideline points that we hoped the users would have read before posting.

Keep up the good work! 😉

**Comment by Wombyte2** [comment]
> 
> 
> > > stop writing "3.3.5 October 2020 release" write exact version
> > 
> > 
> > Please tell me what my version is then instead of blaming me:
> 
> Just to help you deal with comments like that later on: that type of comment is meant to be read in a neutral tone, especially those from Aokromes. Those comments are not meant to deter you from contributing, it is meant as a pointer to what TC considers to be guidelines in this repository.
> 
> > I'm new here, i'm taking my time to help you all improve this by writing bug reports, so there's really no reason to blame me instead of helping and telling me how to find exactly the correct version!
> 
> Fair enough, thank you for contributing. Just be aware that we appreciate even more when tickets are filled in by using the complete issue ticket template, as well as providing as much precise information as possible. Our goal here is to help get issues resolved, so most of the users try to state facts in a neutral tone, without any bad intentions.
> 
> Please also note that for those of us who have used this repository for many years, maybe decades, it can sometimes be boring to repeat ourselves by reiterating guideline points that we hoped the users would have read before posting.
> 
> Keep up the good work! wink

I appreciate your answer, thanks. I know I am sometimes a little more emotional and had bad experiences with people writing like Aokromes. 
I will try to fill the whole template next time when i report a bug. 
For the future: maybe you can tell me what i should do with this part in the issue template:

"opy the result of server debug command". 
What command do i need to write (in the worldserver?)

**Comment by illfated** [comment]
> I appreciate your answer, thanks. I know I am sometimes a little more emotional and had bad experiences with people writing like Aokromes.

You're welcome. Sure thing, I felt a bit taken back the first couple of times I saw his replies to me (several years ago), but I grew accustomed to it and learned to interpret it correctly, so I could react calmly and understand what was being said. "Keep the faith" as they say, and it will help you perform better.

> I will try to fill the whole template next time when i report a bug.

Very good. Thank you. Good attitude. 👍

> For the future: maybe you can tell me what i should do with this part in the issue template:
> 
> "Copy the result of server debug command".
> What command do i need to write (in the worldserver?)

Sure thing, no problem. Currently, my last 2 lines in the worldserver console are these:
```css
TrinityCore rev. 0bec5baa7a33 2020-10-22 01:11:42 +0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...
TC> _
```
Here, I write the following command: `server debug`
and I get the following result (along with the command):
```
TC> server debug
TrinityCore rev. 0bec5baa7a33 2020-10-22 01:11:42 +0300 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.3
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20101
TC> _
```

**Comment by Wombyte2** [comment]
> 
> 
> > I appreciate your answer, thanks. I know I am sometimes a little more emotional and had bad experiences with people writing like Aokromes.
> 
> You're welcome. Sure thing, I felt a bit taken back the first couple of times I saw his replies to me (several years ago), but I grew accustomed to it and learned to interpret it correctly, so I could react calmly and understand what was being said. "Keep the faith" as they say, and it will help you perform better.
> 
> > I will try to fill the whole template next time when i report a bug.
> 
> Very good. Thank you. Good attitude. +1
> 
> > For the future: maybe you can tell me what i should do with this part in the issue template:
> > "Copy the result of server debug command".
> > What command do i need to write (in the worldserver?)
> 
> Sure thing, no problem. Currently, my last 2 lines in the worldserver console are these:
> 
> ```css
> TrinityCore rev. 0bec5baa7a33 2020-10-22 01:11:42 +0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...
> TC> _
> ```
> 
> Here, I write the following command: `server debug`
> and I get the following result (along with the command):
> 
> ```
> TC> server debug
> TrinityCore rev. 0bec5baa7a33 2020-10-22 01:11:42 +0300 (3.3.5 branch) (Win64, Release, Static)
> Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
> Using Boost version: 1.73.0
> Using MySQL version: 50731
> Using CMake version: 3.18.3
> Compiled on: Windows 10.0.19041
> Automatic database updates are enabled for the following databases: Auth, Characters, World
> Worldserver listening connections on port 8085
> Realmlist (Realm Id: 1) configured in port 8085
> VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
> MMAPs status: Enabled
> maps directory located in ./maps. Total size: 251987687 bytes
> vmaps directory located in ./vmaps. Total size: 658130721 bytes
> mmaps directory located in ./mmaps. Total size: 1962379500 bytes
> Using enUS DBC Locale as default. All available DBC locales: enUS
> Using World DB: TDB 335.20101
> TC> _
> ```

thank you, then i will add a debug result the next time, too. 
Also thanks for your kind words :+1:
