### ISSUE TITLE
Quest: The Attack! displays $n instead of player name

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25608]
**Description:**

The quest `The Attack!` requires you to eavesdrop on a couple of NPCs in Stormwind castle grounds. During some gossip dialogue, Tyrion tells you to "Wait here, $n" - I believe this should be the player's name.

<details>

![image](https://user-images.githubusercontent.com/66294837/97068995-78676400-1618-11eb-9605-a6b9f7257c5b.png)

</details>

**Expected behaviour:**

The gossip should say the player's name.

**Steps to reproduce the problem:**

1a. Undertake the quest chain beginning with https://classic.wowhead.com/quest=373/the-unsent-letter - dropped from Deadmines and progress (required prelude to The Attack!)
OR
1b. Intiate quest 434 (https://classic.wowhead.com/quest=434/the-attack)
2. Once initiated quest NPC Tyrion will ask you to "Wait here,..."

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. a183ca5bf5c4 2020-10-20 02:04:01 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:** Windows 7 64bit

**Comment by illfated** [comment]
https://classic.wowhead.com/npc=7766/tyrion

<details>
<summary>Quotes (3)</summary>

- Tyrion says: That's it! That's what you were waiting for! KILL THEM!
- Tyrion says: Wait here, <name>. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you've overheard their conversation.
- Tyrion says: You did a great job, Spybot! Glad to have you back here with me!

</details>

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7766

<details>
<summary>Quotes (2)</summary>

- Tyrion says: Wait here, <name>. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you've overheard their conversation.
- **Tyrion yells: That's it! That's what you were waiting for! KILL THEM!**

</details>

TrinityCore rev. 0bec5baa7a33 2020-10-22 01:11:42 +0300 (3.3.5 branch) (Win64, Release, Static)

```sql
SELECT * FROM `creature_text` WHERE `CreatureID`= 7766;
```
```
CreatureID  GroupID  ID  Text                                                                                                                                     Type  Language  Probability   Emote  Duration   Sound  BroadcastTextId  TextRange  comment
----------  -------  --  ---------------------------------------------------------------------------------------------------------------------------------------  ----  --------  -----------  ------  --------  ------  ---------------  ---------  ---------------------------------
   7766        0     0   Wait here, $n. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you've overheard their conversation.   12      0          100         0        0       0           3761          0       tyrion spybot SAY_TYRION_1
   7766        1     0   That's it! That's what you were waiting for! KILL THEM!                                                                                   14      0          100         0        0       0           4613          0       lord gregor lescovar SAY_TYRION_2
```

```sql
SELECT `entry`,`name`,`gossip_menu_id`,`faction`,`npcflag`,`type`,`AIName`,`ScriptName`,`VerifiedBuild`
 FROM `creature_template` WHERE `entry` = 7766;
```
```
entry  name    gossip_menu_id  faction  npcflag  type  AIName  ScriptName  VerifiedBuild
-----  ------  --------------  -------  -------  ----  ------  ----------  -------------
7766   Tyrion        1761        64        3       7           npc_tyrion      12340
```

I don't know whether anyone has started on converting the script to SAI yet, so I will suggest changing the gossip reference to include player:
https://github.com/TrinityCore/TrinityCore/blob/aff9cf40dcf52f686c27b7abe20ae0eda5779800/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp#L390-L395

The simplest solution would be to just modify it to something like this: `pTyrion->AI()->Talk(SAY_TYRION_1, uiPlayerGUID);`, but I am also testing if it would be possible just to use `Talk(SAY_TYRION_1, player);` directly, which depends on if it is enough to already have `Player.h` included, or if `player` needs some form of `Player* player = ObjectAccessor::GetPlayer(*me, uiPlayerGUID)` to work.

**Comment by jackpoz** [comment]
@illfated if you need a Player* check this line https://github.com/TrinityCore/TrinityCore/blob/aff9cf40dcf52f686c27b7abe20ae0eda5779800/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp#L436

**Comment by illfated** [comment]
Yes, I noticed, but I don't remember if that means I need to include `if (Player* player =` on a line before the `Talk()` line, or if I rather want to use `pTyrion->AI()->Talk(SAY_TYRION_1, uiPlayerGUID);` directly. Just started experimenting with building a test to see the difference myself, but if you want to suggest which solution to go for directly, feel free to say what you like. 😉

**Comment by illfated** [comment]
By the way, are there any easy examples to reference later, for example to new contributors? (I have looked up a few, but I don't think my previous commits are good enough to explain the context.)

**Comment by illfated** [comment]
OK, so adding only `, player` to the line `pTyrion->AI()->Talk(SAY_TYRION_1);` is not identified:
```cpp
15>C:\Trinity\Source\src\server\scripts\EasternKingdoms\zone_stormwind_city.cpp(392,67): error C2065: 'player': undeclared identifier
```
Running a new test now to double check that `pTyrion->AI()->Talk(SAY_TYRION_1, uiPlayerGUID);` works, which I assume it will.

**Comment by illfated** [comment]
BTW, I have been looking at some of my previous experiences with this type of issue, mainly these:
- commit https://github.com/TrinityCore/TrinityCore/commit/736843fbb5442b1338ec888c8a702d666c95a76b (from PR #17395):
https://github.com/TrinityCore/TrinityCore/blob/736843fbb5442b1338ec888c8a702d666c95a76b/src/server/scripts/Northrend/zone_borean_tundra.cpp#L2316-L2318
- commit https://github.com/TrinityCore/TrinityCore/commit/a040d484437b2f12ce88dc4372bfacc18204c8fc (from PR #23122):
https://github.com/TrinityCore/TrinityCore/blob/a040d484437b2f12ce88dc4372bfacc18204c8fc/src/server/scripts/Kalimdor/WailingCaverns/wailing_caverns.cpp#L243-L252
- commit https://github.com/TrinityCore/TrinityCore/commit/c9e699961e37678b4da5ed6a8b396d72d90af883 (PR #14540)
https://github.com/TrinityCore/TrinityCore/blob/5af8ff2b84a0c81ce3aa03f338ce838747b2f25e/src/server/scripts/Northrend/zone_borean_tundra.cpp#L1481-L1504

**Comment by offl** [comment]
#24735

**Comment by illfated** [comment]
Oh. Right. I forgot to check for duplicate issues. Fair enough.

**Comment by illfated** [comment]
Very well, then. I see now that I need to reuse the line `if (Player* player = GetPlayerForEscort()` from `case 10` further down. Oh well. At least I got the experience from testing on my own.
```diff
diff --git a/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp b/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
index 1b5fe4de36..ac19ab11be 100644
--- a/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
+++ b/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
@@ -386,13 +386,16 @@ public:
                             Talk(SAY_QUEST_ACCEPT_ATTACK);
                             uiTimer = 3000;
                             uiPhase = 2;
                             break;
                         case 2:
                             if (Creature* pTyrion = me->FindNearestCreature(NPC_TYRION, 10.0f))
-                                pTyrion->AI()->Talk(SAY_TYRION_1);
+                            {
+                                if (Player* player = GetPlayerForEscort())
+                                    pTyrion->AI()->Talk(SAY_TYRION_1, player->GetGUID());
+                            }
                             uiTimer = 3000;
                             uiPhase = 3;
                             break;
                         case 3:
                             me->UpdateEntry(NPC_PRIESTESS_TYRIONA);
                             uiTimer = 2000;
```

**Comment by illfated** [comment]
Sorry, I didn't manage to get that to work either.
```
15>zone_stormwind_city.cpp
15>C:\Trinity\Source\src\server\scripts\EasternKingdoms\zone_stormwind_city.cpp(394,1):
 error C2664: 'void CreatureAI::Talk(uint8,const WorldObject *)': cannot convert argument 2 from 'ObjectGuid' to 'const WorldObject *'
15>C:\Trinity\Source\src\server\scripts\EasternKingdoms\zone_stormwind_city.cpp(394,86):
 message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
15>C:\Trinity\Source\src\server\game\AI\CreatureAI.h(107,14): message :
 see declaration of 'CreatureAI::Talk' (compiling source file C:\Trinity\Source\src\server\scripts\EasternKingdoms\zone_stormwind_city.cpp)
```

**Comment by illfated** [comment]
OK, so the preliminary solution (before making a PR) is to use only the following:
```diff
diff --git a/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp b/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
index 1b5fe4de36..ac19ab11be 100644
--- a/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
+++ b/src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
@@ -386,13 +386,16 @@ public:
                             Talk(SAY_QUEST_ACCEPT_ATTACK);
                             uiTimer = 3000;
                             uiPhase = 2;
                             break;
                         case 2:
                             if (Creature* pTyrion = me->FindNearestCreature(NPC_TYRION, 10.0f))
-                                pTyrion->AI()->Talk(SAY_TYRION_1);
+                            {
+                                if (Player* player = GetPlayerForEscort())
+                                    pTyrion->AI()->Talk(SAY_TYRION_1, player);
+                            }
                             uiTimer = 3000;
                             uiPhase = 3;
                             break;
                         case 3:
                             me->UpdateEntry(NPC_PRIESTESS_TYRIONA);
                             uiTimer = 2000;
```

**Comment by illfated** [comment]
<details>
<summary>The Attack! (screenshot from testing applied code from above)</summary>

![WoWScrnShot_102520_031439](https://user-images.githubusercontent.com/38162891/97097810-bf377700-1675-11eb-8b4c-3da1dc995fd8.jpg)

</details>

**Comment by jackpoz** [comment]
Even if duplicate, this particular issue has been fixed
