### ISSUE TITLE
[3.3.5] Pet Skill: Improved Cower does not affect anything

### ISSUE THREAD

**Issue by Wombyte2** [TrinityCore/TrinityCore#25600]
**Description:**

The skill "Improved Cower" should reduce the speed reduction of Cower by 50% / 100% (tier 1 / tier 2). 
Learning this skill does not affect the speed at all. When i spend 2 points in "Improved Cower" there should be no speed reduction of "Cower" anymore, but the pet is still as slow as if i wouldn't have spend those 2 points. 

**Expected behaviour:**

There should be less speed reduction by "Cower" if you spend a point in "Improved Cower".

**Steps to reproduce the problem:**

1. Get a pet (as hunter) that can do "Cower".
2. Attack something and activate Cower. You will see the pet's speed is reduced by 50%. 
3. Now spend two points in "Improved Cower" (the pet needs to be level 36 at least, so that you have enough skill points to do so).
4. Attack something and activate Cower again. The pet will still get a speed reduction of 50%.

**Branch(es):**

3.3.5 rev. 07845b4

**Comment by illfated** [comment]
(just to add some ancient changes from the repo:)
- https://github.com/TrinityCore/TrinityCore/search?q=%22Improved+Cower%22&type=code
- https://github.com/TrinityCore/TrinityCore/search?q=%22Improved+Cower%22&type=commits
