### ISSUE TITLE
Ambiguity build error while building for 32bit linux as target

### ISSUE THREAD

**Issue by HKunogi** [TrinityCore/TrinityCore#25618]
**Description:**
When building the core into ubuntu 20.04 targeting 32bit when its almost finishing the build, this error is given.
```
/src/server/scripts/Commands/cs_go.cpp:98:70: error: conversion from 'Variant<Hyperlink<Trinity::Hyperlinks::LinkTags::creature>, ObjectGuid::LowType>' (aka 'Variant<Hyperlink<Trinity::Hyperlinks::LinkTags::creature>, unsigned int>') to 'ObjectGuid::LowType' (aka 'unsigned int') is ambiguous
        CreatureData const* spawnpoint = sObjectMgr->GetCreatureData(spawnId);
                                                                     ^~~~~~~
/src/server/game/Chat/ChatCommands/ChatCommandTags.h:270:9: note: candidate function [with C = true]
        operator std::enable_if_t<C, first_type>() const
        ^
/src/server/game/Chat/ChatCommands/ChatCommandTags.h:276:9: note: candidate function [with C = true]
        operator std::enable_if_t<C && std::is_convertible<first_type, size_t>::value, size_t>() const
/src/server/game/Globals/ObjectMgr.h:1353:65: note: passing argument to parameter 'spawnId' here
        CreatureData const* GetCreatureData(ObjectGuid::LowType spawnId) const
```

**Expected behaviour:**
This error should not happen and the build should be successful, either i am targeting 32bit or 64bit given the correct libraries was provided, the size_t should not give ambiguity when targeting 32bit.

**Steps to reproduce the problem:**
1. Build normally while targeting 32-bit as output (same result using clang or gcc).

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
3c201b75543106d6daa693dae0eca39f8efdfa22

**Operating system:** 
Ubuntu 20.04

**Comment by Aokromes** [comment]
why you want to use 32 bits? trinitycore is memory hungry

**Comment by HKunogi** [comment]
> why you want to use 32 bits? trinitycore is memory hungry

I want to run it on an environment that i've got to test things into, given the specs it should run just fine, but i need to build it into 32bit to be able to execute there.
