### ISSUE TITLE
Core/SAI: Timer of SMART_ACTION_SET_CORPSE_DELAY behavior

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25629]
**Description:**

I set it to 3, creature despawns instantly, I set it to 30, creature despawns in 15 sec

**Expected behaviour:**

Corpse delay 3 should mean 3 seconds and not 0
30 should mean 30, not 15

**Steps to reproduce the problem:**

1. .go c id 25332
2. kill, notice instant despawn instead of 3 seconds

**Branch(es):** 3.3.5
**TC rev. hash/commit:** c2a0b78a051ea3301d8769b2c11fae00e14fe095

**Comment by illfated** [comment]
For others who are curious like me, the NPC mentioned above is this one:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=25332
- https://www.wowhead.com/npc=25332/stitched-warsong-horror

**Comment by Ovahlord** [comment]
When exactly do you execute the action? The core side part of the action looks fine so I assume that there is some problem in when it's being called. Usually you put that stuff right into the initialization part of a script

**Comment by offl** [comment]
On Respawn and On Just Summoned

**Comment by offl** [comment]
We can't call it always on AI init because sometimes only summoned creatures should remove corpse shortly after death. And different summon type cannot be used.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/1ff4a7e75b56e1ad68d83f75b493a42ac1ae85c3/src/server/game/Entities/Creature/Creature.cpp#L2741-L2747

The corpse delay is multiplied by the worldserver.conf setting Rate.Corpse.Decay.Looted that is 0.5f by default, then lowered to the nearest integer.
In your case of 3 we have 3 * 0.5 = 1.5, lowered to 1 .
In the other case of 30 we have 3 * 0.5 = 15 .

Loot type for this mob is LOOT_NONE and loot.isLooted() returns true. When looting a corpse, loot type is LOOT_CORPSE . Should the decay be removed for mobs that have no loot ?

**Comment by offl** [comment]
> The corpse delay is multiplied by the worldserver.conf setting Rate.Corpse.Decay.Looted

Why? Scripted, not default corpse delay, is something like despawn timer after death. It should not be multiplied. Looks like it's better to just despawn creature after death but as I said sometimes only summoned units should have reduced corpse delay. Scripted corpse delay should not be multiplied

**Comment by jackpoz** [comment]
I created a PR at https://github.com/TrinityCore/TrinityCore/pull/25989

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d5fc86af8b22fed5b054e51349eb3ab47b06b784
