### ISSUE TITLE
Warden AntiCheat

### ISSUE THREAD

**Issue by sawd20** [TrinityCore/TrinityCore#25624]
Warden Issue

**Changes proposed:**

- improve Warden anticheat 
-  
-  

**Target branch(es):** 3.3.5/master

 3.3.5

**Issues addressed:**

its about warden that it detects Emu and hitchhiker Hacks only when you run it before opening you wow client it makes your wow to crash

**Tests performed:**

start the wow client enter account and password and log in game then run your cheat

**Comment by illfated** [comment]
I am pretty sure this has been discussed in several previous tickets, even though I don't remember what the current final conclusion from the TC members is.

Please browse these closed issues to see if your specific issue has been discussed before:
- https://github.com/TrinityCore/TrinityCore/search?q=Warden+AntiCheat+is%3Aissue&type=Issues

**Comment by sawd20** [comment]
@illfated Yea there is a issue like this it seems that Emu hack solved but Warden Dosnt detect Hitchiker Cheat these hack (Emu And hitchiker) seems alike but warden dosnt detect hitchiker one

**Comment by illfated** [comment]
OK, I see what you are saying. I still think it would be good to hear from the TC owners what the TC standpoint is to that issue.

@Aokromes : Would you like to comment here, or should we wait for someone else?

**Comment by sawd20** [comment]
if possible @Keader  and @Shauren  help with this?

**Comment by illfated** [comment]
It is much better to fill in all the required information to get any support on this ticket. (closing reason: No core revision hash or required steps to reproduce the issue.)
