### ISSUE TITLE
[3.3.5][Spell]Mind Amplification Dish - Gnomish Thinking Cap

### ISSUE THREAD

**Issue by overy** [TrinityCore/TrinityCore#2562]
When you use it - WOWHEAD COMMNET:  The target becomes a pet for you, enabling the 'Passive', 'Defensive', and 'Aggressive' modes, as well as any abilities that a priest would have while MCing. (I used it on a Wintergrasp keep defender and got a strike ability).

http://www.wowhead.com/spell=67799/gedankenverstarkungsschussel - maineffect

linked effects:
http://www.wowhead.com/spell=13181/mind-amplification-dish
http://www.wowhead.com/spell=26740/mind-amplification-dish
http://de.wowhead.com/spell=67809/dullard

Not work on  c3613cd47746b32a309c
TDB DB

**Comment by Rushor** [comment]
http://www.wowhead.com/spell=67799/gedankenverstarkungsschussel - maineffect

linked effects:
http://www.wowhead.com/spell=13181/mind-amplification-dish
http://www.wowhead.com/spell=26740/mind-amplification-dish
http://de.wowhead.com/spell=67809/dullard

issue present on https://github.com/TrinityCore/TrinityCore/commit/c6c3e72b55846ccfb565fd09580509800bd25c2a

E: updated the the startpost with all links
