### ISSUE TITLE
DB/Templates: Update missing creature template data for Ignis encounter (Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25631]
**Description:**

Added here for 10 mode entries
https://github.com/TrinityCore/TrinityCore/commit/fc8d2f91f4f25e1072e44df9440be656a8408855

**Fix:**

```sql
UPDATE `creature_template` SET `speed_walk`=1.6,`speed_run`=1.42857,`BaseAttackTime`=1500 WHERE `entry`=33190; -- Ignis the Furnace Master (25)
UPDATE `creature_template` SET `speed_run`=1.28571,`unit_flags`=`unit_flags`|0x00000100|0x02000000 WHERE `entry`=33191; -- Iron Construct (25)
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be8b251b58b82caf78df5a18f74af435b98bfe63

**Comment by illfated** [comment]
Aha. Took me a couple of seconds to see the difference.
Commit https://github.com/TrinityCore/TrinityCore/commit/fc8d2f91f4f25e1072e44df9440be656a8408855 is about
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=33118/ignis-the-furnace-master
- https://www.wowhead.com/npc=33118/ignis-the-furnace-master
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=33121/iron-construct
- https://www.wowhead.com/npc=33121/iron-construct

Your suggestion above is for 
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=33190/ignis-the-furnace-master(1) (Ignis the Furnace Master (25))
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=33191/iron-construct(1) (Iron Construct (25))
