### ISSUE TITLE
DB/Spell: Added missing difficulty mode to Kologarn's spells (Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25637]
**Description:**

Overhead Smash:
https://www.wowhead.com/spell=63356/overhead-smash
https://www.wowhead.com/spell=64003/overhead-smash

Falling Rubble:
https://www.wowhead.com/spell=63821/falling-rubble
https://www.wowhead.com/spell=64001/falling-rubble

**Fix:**

```sql
-- Ulduar: Kologarn missing spell difficulties 25 mode
DELETE FROM `spelldifficulty_dbc` WHERE `id` IN (63356, 63821);
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(63356, 63356, 64003), -- Overhead Smash
(63821, 63821, 64001); -- Falling Rubble
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be8b251b58b82caf78df5a18f74af435b98bfe63

**Comment by illfated** [comment]
Looks valid to me. Spacing between values in those short lines would have been nice, but not required.
