### ISSUE TITLE
DB/Spell: Added missing difficulty mode to Hodir's Frozen Blows spell (Ulduar) 

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25639]
**Description:**

Frozen Blows:
https://www.wowhead.com/spell=62478/frozen-blows
https://www.wowhead.com/spell=63512/frozen-blows

**Fix:**

```sql
-- Ulduar: Hodir missing Frozen Blows spell difficulty 25 mode
DELETE FROM `spelldifficulty_dbc` WHERE `id`=62478;
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(62478, 62478, 63512);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be8b251b58b82caf78df5a18f74af435b98bfe63

**Comment by illfated** [comment]
Suggestion (as mentioned in the other ticket): include value spacing in very short values lists/rows.
