### ISSUE TITLE
[Quest] 10674 Trapping the Light Fantastic

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#25634]
https://www.wowhead.com/quest=10674/trapping-the-light-fantastic
Quest not working.  Light orbs don't flying and just stay in air, but it is not big problem. When player trying to use trap for this orb (https://www.wowhead.com/item=30852/multi-spectrum-light-trap), its just fly away and do not increase count of captured orbs. So please fix this someone.

Of course .gm off. Core and db was compiled and updated 03.Nov.2020

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.20101
MySQL client library: 5.7.28
MySQL server ver: 5.7.28 

ref #7202

**Comment by Faq** [comment]
close reason, no provided hash.
