### ISSUE TITLE
[Quest] Freedom for all creatures (2969)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#25633]
Quest not working.  When player let free Sprite Darters, they go to the escape point and atacking taurens on their way, and at this stage all ok, but when Sprite Darters disapering on destination point, they don't increase count of saved Sprite Darters. So please fix this someone.
Of course .gm off. Core and db was compiled and updated 03.Nov.2020

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.20101
MySQL client library: 5.7.28
MySQL server ver: 5.7.28 

ref #4823

**Comment by Faq** [comment]
@Freeman256 include core rev.

**Comment by illfated** [comment]
From #25635 (https://github.com/TrinityCore/TrinityCore/issues/25635#issuecomment-723451491):

> Sorry, but TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static).
> I don't use Git to download source code. If it is imortant, then how i can check core revision hash? I noticed this issue 06.Nov.2020 when I first time try to do this quest. I do not do this quest earlier.
