### ISSUE TITLE
[3.3.5] [Item] Goblin Bomb Dispenser

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#25636]
https://classic.wowhead.com/item=10587/goblin-bomb-dispenser

Description:
This item do nothing.

Expected behaviour:
It must creates a mobile bomb that charges the nearest enemy and explodes for 315 to 385 fire damage. (30 Min Cooldown).

Steps to reproduce the problem:
1. .additem 10587 
2. Equip this item and wait 30 sec. cooldown.
3. Use this item.
4. See nothing.

Branch:
3.3.5

TC rev. hash/commit:
Core and db was compiled and updated 03.Nov.2020.
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static)

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.20101
MySQL client library: 5.7.28
MySQL server ver: 5.7.28 

Operating system:
Win7 SP1 x64 with all updates.

**Comment by illfated** [comment]
Fair enough, though if you plan on working on the source, it will be a helpful thing for you in the future if you learn how to clone the repository to your computer using Git tools like GitHub Desktop or Git Extensions, depending on which kind of application you like to use. Maybe you are one of those who like to use command-line tools, I don't know.

Anyway, the good thing about using Git tools to handle your source code is that you get to appreciate the ability to keep track of your own status compared to the TC source. I know, it is a learning process to get into being comfortable using them, but it could easily be a useful skill to learn for future coding or source code handling.
