### ISSUE TITLE
Core/SAI: SMART_ACTION_SET_POWER / ADD_POWER / REMOVE_POWER doesn't work with value > 0

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25630]
**Description:**

SMART_ACTION_SET_POWER / ADD_POWER / REMOVE_POWER doesn't work with value > 0
This means SMART_ACTION_ADD_POWER and SMART_ACTION_REMOVE_POWER doesn't work at all

**Steps to reproduce the problem:**

```sql
SET @ID := 20859;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @ID AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID,0,6,0,4,0,100,0,0,0,0,0,0,108,0,5000,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Aggro - Set Mana to 5000");

-- (@ID,0,6,0,4,0,100,0,0,0,0,0,0,109,0,5000,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Aggro - Add Mana 5000");

-- (@ID,0,6,0,4,0,100,0,0,0,0,0,0,110,0,5000,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Aggro - Remove Mana 5000");
```

1. apply sql, any of actions
2. .go c id 20859
3. check mana
4. aggro, check mana, nothing was changed

Branch(es): 3.3.5
TC rev. hash/commit: c2a0b78

**Comment by jackpoz** [comment]
could it be it's not updated client side ?

**Comment by illfated** [comment]
Fair point. Testing can sometimes be difficult, because the game client tries to read cached information instead of querying the server for changed info.

**Comment by offl** [comment]
It works only before midnight
In other words I screwed up again
