### ISSUE TITLE
DB/Spell: Added missing difficulty mode to Mimiron's Napalm Shell spell (Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25638]
**Description:**

Napalm Shell damage:
https://www.wowhead.com/spell=63666/napalm-shell
https://www.wowhead.com/spell=65026/napalm-shell

**Fix:**

```sql
-- Ulduar: Mimiron missing Napalm Shell spell difficulty 25 mode
DELETE FROM `spelldifficulty_dbc` WHERE `id`=63666;
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(63666, 63666, 65026);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/be8b251b58b82caf78df5a18f74af435b98bfe63

**Comment by illfated** [comment]
Looks valid to me. I would have liked to see some spacing between the values in those short lists/rows, but that is up to you.
