### ISSUE TITLE
Core/Waypoints: Waypoint stop timer after gossip hello

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25647]
**Description:**

Waypoint stop timer after gossip hello is definitely wrong.
Treat as 20sec pause:

ClientToServer: CMSG_GOSSIP_HELLO (0x017B) Length: 8 ConnIdx: 0 Time: 10/06/2010 17:23:54.000 Number: 8278
GUID: Full: 0xF1300039E70042EC Type: Creature Entry: 14823 Low: 17132

ServerToClient: SMSG_ON_MONSTER_MOVE (0x00DD) Length: 49 ConnIdx: 0 Time: 10/06/2010 17:24:16.000 Number: 8521
GUID: Full: 0xF1300039E70042EC Type: Creature Entry: 14823 Low: 17132

Yeah, I know anyone can change that timer in config (Creature.MovingStopTimeForPlayer = 180000) but the thing is if my memory serves me well that timer can vary from creature to creature. It depends on something.

**Expected behaviour:**

Timer should be lowered and investigated if it really can vary or not.

**Branch(es):** both
**TC rev. hash/commit:** 05fa1a46b36f81c177a503f7f5de14eb34830208

**Comment by Ovahlord** [comment]
That's what PauseMovement has a wait timer for. If you wanna handle this per creature, slap a SAI script on it, call the pause movement smart action with the wait time on gossip hello and you're done. The wait time is indeed different from time to time. What you have there is afaik the wait time for city guards. There are many cases where it's different, like in Zul'aman with Voljin

**Comment by offl** [comment]
Pretty sure it may depend on creature type. If creature is questgiver or vendor, for example
Killyana once told me that pause should be removed from core and handled for each creature manually, I doubt it should work like that

**Comment by offl** [comment]
Probably 40 for questgivers, not sure

**Comment by xvwyh** [comment]
I've also encountered wildly different pause durations while playing on Classic. Some were not stopping at all, some were stopping for 3 seconds, some for 20+, some for several minutes etc. The pauses were consistent on the same NPC, it was always stopping for the same amount of time, but different NPCs had different pauses. I'm ready to believe that it was possible to manually configure how long will be pause duration be on a per-creature basis.

**Comment by offl** [comment]
That's sad
Nothing related to flags (questgiver\vendor) or other?

**Comment by xvwyh** [comment]
Possibly. It's just hard to know what they have without .npc info. :D

**Comment by jackpoz** [comment]
can this be closed after a22bc236ebc038c723774e5b38cd93e814ccc43d or ?
