### ISSUE TITLE
Core/Vehicles: Assertion crash

### ISSUE THREAD

**Issue by Riztazz** [TrinityCore/TrinityCore#25649]
**Description:**
Worldserver asserts

https://www.irccloud.com/pastebin/KzHh5Cfg/

**Expected behaviour:**
Should not assert

**Steps to reproduce the problem:**

1. Go to eye of the eternity
2. Get malygos to phase two
3. Get two or more disks next to each other
4. Keep jumping between them

In order to replicate this easily, i've downloaded https://github.com/tripleslash/wowscout
type those commands (blacklist all, log incoming, whitelist 0x3F8 - spellclick packet), now trigger a spellclick client side and then copy binary data and do
send 0x3F8 [data]
ie. send 0x3F8 A0 04 00 2B 81 00 50 F1
edit: change anti-dos policy to log level, so you do not get kicked right away

**Branch(es):**

3.3.5 

**TC rev. hash/commit:** 

cfac13bf9a12b68eefb96730fecd7e9e7286c0f6

**Operating system:**
Some kind of linux that Jackpoz runs

Assert on
```
ASSERT(seat != Seats.end())
```
I was searching for a reproduction for this crash (still happens :P https://github.com/TrinityCore/TrinityCore/issues/18430 | https://gist.github.com/Riztazz/27fcf38d63b15154f7cdf9de6e99a227 a bit more recent ) and managed to trigger an assertion crash in RemovePassenger ( ASSERT(seat != Seats.end()); )
Most probably caused by this:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp#L1183

**Comment by jackpoz** [comment]
Reproduced again remotely but not locally

**Comment by jackpoz** [comment]
@Riztazz how many packets did you send to trigger it ? could you post the exact commands ? please note that the first 2 disks have the same guid:
```
send 0x3F8 19 00 00 1A 76 00 50 F1
send 0x3F8 17 00 00 1A 76 00 50 F1
```

**Comment by Riztazz** [comment]
A lot, sometimes it took a good minute of constant switching to reproduce it

**Comment by jackpoz** [comment]
do you write on notepad a lot of lines rotating around the 3 disks or queue the packets and send them at once or ?

**Comment by Riztazz** [comment]
Yeah, i wrote a cycle of 3 and then using np++ i've duplicated that a bunch of times (300, 500?) and then paste everything into wowscout

**Comment by jackpoz** [comment]
I couldn't repro that locally, maybe it requires some latency, I'll try again on the test realm

**Comment by Riztazz** [comment]
I might have used two characters to jump on between those disks. It was a while ago and i only remember bits and pieces, i'll try to find some time and reproduce it on my machine

**Comment by Riztazz** [comment]
Managed to trigger something after a lot of trying.
https://gist.github.com/Riztazz/d53e8fdb4d9d65733fb91ff54f67b7a5

Version i tested on is not up to date but related code is the same, now what i did exactly was this:
I've logged in on one character, started malygos encounter, got it to phase two (25 man) and got possession of 4 disks, next i did the entire packet sniffing and wrote a sequence of send 0x3F8 between those 4 disks that repeats itself for a very long time
![image](https://user-images.githubusercontent.com/16348711/107111146-dcbbd580-684d-11eb-98a0-8e53e07aae4d.png)
After that i've killed wowscout (malygos encounter still running), logged in 2 more characters and appeared next to those disks and launched wowscout, it attached itself to all my wow instances, pasted all those repeating packet sends to the app and all characters should start jumping. Once i did that, i've launched 4th wow, appeared next to disks and launched yet another wowscout and pasted my send text again so 4th character starts jumping, a few seconds after that it crashed.

**Comment by jackpoz** [comment]
I wonder if it's one of the recent changes where the vehicle join aborts because there are no more slots available since the even was started.

was worldserver running locally or remotely ?

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/4cc1f850670b868a1d16833a2cf5c60715f749ef/src/server/game/Entities/Unit/Unit.cpp#L12663 can return null but it's never checked, so that seems to be one of the reasons of this crash

**Comment by jackpoz** [comment]
Please try after https://github.com/TrinityCore/TrinityCore/commit/b84b92506354fc37017cb687aac263218265cf06 and check if the new error log shows up.

**Comment by jackpoz** [comment]
Please try to reproduce it at https://tcubuntu.northeurope.cloudapp.azure.com/ with the changes I pushed on February

**Comment by Riztazz** [comment]
I don't have wow client anymore, sorry. I've laid out what i did in one of my previous comments, should be easy to reproduce with and without said commit

**Comment by Aokromes** [comment]
no feedback after 2 years, clossing.
