### ISSUE TITLE
Dire Maul spawn issue

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/TrinityCore#25657]
**Description:**

Grafana reported 8'000 creatures in a single Dire Maul instance
![image](https://user-images.githubusercontent.com/1153754/99512342-a1fe7b80-2989-11eb-9b15-ec5f8f8abf75.png)

**Expected behaviour:**

Less than 8'000 creatures should spawn in the instance

**Steps to reproduce the problem:**

No clue. It would be nice if someone could try reproducing the issue

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

cfac13bf9a12b68eefb96730fecd7e9e7286c0f6

**Operating system:** Linux x64

**Comment by jackpoz** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/grafana/d/IRRL03nMk/performance-profiling?orgId=1&refresh=1m can be used to reproduce the issue . Registration page and realmlist at https://tcubuntu.northeurope.cloudapp.azure.com/

**Comment by Ovahlord** [comment]
I think it's that one part of the instance where endless larvas are being spawned so they are either missing a despawn timer or should spawn endlessly but only replace existing spawns

**Comment by Faq** [comment]
Can you fetch from db creatures count by id in that map, so we know at least creature id?

**Comment by Jildor** [comment]
Maybe Warpwood Pod doesn't despawn and summon a lot of npc

by example:
```
.go xyz 116.148613 -408.426086 -3.273565 429
```

**Comment by jackpoz** [comment]
> Can you fetch from db creatures count by id in that map, so we know at least creature id?

this is not a db spawn issue, it's a runtime spawn issue. it could be anything spawned by SAI or C++ script.

**Comment by dr-j** [comment]
Warpwood pods are probably prime suspect still as the traps work for spawning a lot of mobs ut the object nor trap ever despawns and trigger everytime player goes near them

https://github.com/TrinityCore/TrinityCore/issues/19371

**Comment by TQPS** [comment]
> Maybe Warpwood Pod doesn't despawn and summon a lot of npc

This! Each time I take bots into Dire Maul East, I think half my time is spent killing mobs spawning out of these caused by the bots getting too close each time and re-triggering the NPCs to come out.

**Comment by Faq** [comment]
Reason to close?

**Comment by Aokromes** [comment]
duplicate of 19371

**Comment by illfated** [comment]
"Duplicate of #19371 "
