### ISSUE TITLE
[3.3.5] Vmap, terrain & line of sight detection

### ISSUE THREAD

**Issue by Malak044** [TrinityCore/TrinityCore#25654]
**Description:**

VMap doesnt take into account terrain when calculating LOS.
It does take into account the buildings, this is correct.

[img to show tested location](https://imgur.com/a/LhJpU1v)
In this image the player (on the left) can cast ranged spells like [fireball](https://wotlkdb.com/?spell=133) on the dummy (on the right).
While the player cannot see the target because there is terrain the way : 
 - the end of the "mountain"
 - the giant tree

He shouldnt be able to do so but vmaps does say that he is in line of sight.

**Expected behaviour:**

He should not be able to cast.  You shouldnt be able to cast freely spells through terrain.

**Steps to reproduce the problem:**

in this test, the positions pos1 & pos2 are the one referenced in the screenshot.

1. Extract vmaps as wiki explains
2. Change CMakeLists.txt of src/tests to add link to "common"
3. Add the following test and run it (change the directory of vmaps to your location) : 

```
#include "tc_catch2.h"
#include "VMapManager2.h"
#include "VMapFactory.h"
#include "Position.h"
#include "GridDefines.h"
#include "Cell.h"

TEST_CASE("VMap los", "[vmapLOS]")
{
    VMAP::VMapManager2* manager = VMAP::VMapFactory::createOrGetVMapManager();
    GIVEN("map is Outland (530)")
    {
        uint32 mapId = 530;
        std::vector<uint32> maps;
        maps.push_back(mapId);
        std::string base_path = R"(D:\World of Warcraft 3.3.5a (no install)\vmaps)";
        manager->setEnableLineOfSightCalc(true);
        manager->InitializeThreadUnsafe(maps);

        AND_GIVEN("pos1 is (-2863, 3775.25, 2.4) grid[26,39] cell[5,0]")
        {
            Position pos1 = Position(-2863.f, 3775.25f, 2.4f);
            {
                CellCoord cellCoord = Trinity::ComputeCellCoord(pos1.GetPositionX(), pos1.GetPositionY());
                REQUIRE(cellCoord.IsCoordValid());
                Cell cell = Cell(cellCoord);
                REQUIRE(cell.GridX() == 26);
                REQUIRE(cell.GridY() == 39);
                REQUIRE(cell.CellX() == 5);
                REQUIRE(cell.CellY() == 0);
                int gx = (MAX_NUMBER_OF_GRIDS - 1) - cell.GridX();
                int gy = (MAX_NUMBER_OF_GRIDS - 1) - cell.GridY();
                REQUIRE(manager->loadMap(base_path.c_str(), mapId, gx, gy) == VMAP::VMAP_LOAD_RESULT_OK);
            }

            WHEN("pos2 is (-2863, 3775.25, 2.37) grid[26,39] cell[5,0]")
            {
                Position pos2 = Position(-2863.f, 3775.25f, 2.37f);
                {
                    CellCoord cellCoord = Trinity::ComputeCellCoord(pos2.GetPositionX(), pos2.GetPositionY());
                    REQUIRE(cellCoord.IsCoordValid());
                    Cell cell = Cell(cellCoord);
                    REQUIRE(cell.GridX() == 26);
                    REQUIRE(cell.GridY() == 39);
                    REQUIRE(cell.CellX() == 5);
                    REQUIRE(cell.CellY() == 0);
                    int gx = (MAX_NUMBER_OF_GRIDS - 1) - cell.GridX();
                    int gy = (MAX_NUMBER_OF_GRIDS - 1) - cell.GridY();
                    REQUIRE(manager->loadMap(base_path.c_str(), mapId, gx, gy) == VMAP::VMAP_LOAD_RESULT_OK);
                }

                THEN("result should be false")
                {
                    bool isInLineOfSight = manager->isInLineOfSight(
                            mapId,
                            pos1.GetPositionX(), pos1.GetPositionY(), pos1.GetPositionZ(),
                            pos2.GetPositionX(), pos2.GetPositionY(), pos2.GetPositionZ(),
                            VMAP::ModelIgnoreFlags::Nothing
                    );
                    REQUIRE(isInLineOfSight == false);
                }
            }
        }
    }
}
```

**Branch(es):**

3.3.5 (maybe both ?)

**TC rev. hash/commit:** 

e6b945eabcdeded8043e40b4e5ede41bd26701dd (latest as of writing)

**Operating system:**

errorous problem was found on a server running on linux while test to reproduce the problem was run on windows.

**Comment by Shauren** [comment]
This is not a bug. That is how it behaves on retail.

**Comment by Malak044** [comment]
Definitely not.  For instance you have the same problem on Warsong Battleground where ppl can shoot spells from down below to the graveyard and, from what i recall, that wasnt possible back then.

**Comment by Shauren** [comment]
It still works that way TODAY

**Comment by meji46** [comment]
https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/10
https://eu.forums.blizzard.com/en/wow/t/los-is-it-bugged/127000/15
https://www.mmo-champion.com/threads/1193133-Is-line-of-sight-removed-or-bugged

It's blizzlike. Warsong Gulch trees and hills have never had LOS.
