### ISSUE TITLE
Sometimes after enter icc after wipe you die because fall damage

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25652]
**Description:**

I got some reports about this too
 falls and loses 29586 health.

**Expected behaviour:**

No fall damage while walking.

**Steps to reproduce the problem:**

1. .tele icecrowncitadel
2. enter icc
3. .go xy 5.005 2211
4. you instant die.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d19c0dfd1b8b

**Operating system:** Debian 10 x64

**Comment by Jildor** [comment]
Can you get more information about this?
for example:
- In what part of the instance did they first die?
- Was it in a match against a specific boss?
- Did it happen once or several times?
- Were all players in the raid affected or just one or some?

**Comment by Aokromes** [comment]
multiple times, and multiple different players on multiple days, i will ask the 2 1st things.

**Comment by illfated** [comment]
> 6. die again while walking from entrance to 1st teleport

Makes me wonder if that could have something to do with missing buffs vs. the initial heavy debuff you get upon entering ICC anyway, making it necessary to have some form of buff from your raid group to survive.

**Comment by Aokromes** [comment]
dunno, who reported me told me they where a warlock one day, a priest few days, a mage another and a druid another.

**Comment by illfated** [comment]
OK, doesn't sound as easy as I thought to find out what happens without having the player death and nearby events logged in detail.

**Comment by nerc0487** [comment]
Does it happen on boss wipes or is it possible to reproduce this with a simple die command? I'm asking because I noticed you mentioned Rotface.

**Comment by Aokromes** [comment]
after 2 weeks whit the falldamage log enabled and confirmation of 1 member of one group died the log failed to show something.

**Comment by Jildor** [comment]
Fall damage appears in the combat log or what is the way in which it is being verified that the death is due to fall damage?

**Comment by Aokromes** [comment]
falls and loses 29586 health.

**Comment by illfated** [comment]
Would be a lot easier to understand if this was about the Frozen Throne, where we almost know why players can fall into the abyss. My only idea could be something about maps, but that is a pure guess.

**Comment by Aokromes** [comment]
nope, it's before the 1st teleport pad.

**Comment by Aokromes** [comment]
i was told yesterday the bug apeared on a wipe before gunship.

**Comment by illfated** [comment]
Interesting point. The elevator could be a plausible location for the bug to appear.

**Comment by Aokromes** [comment]
> Interesting point. The elevator could be a plausible location for the bug to appear.

no no, the die thing is on the entrance, jump into irc.

**Comment by Aokromes** [comment]
if you enter icc and 
.go xy 5.005 2211
you instant die.

**Comment by Aokromes** [comment]
2020-12-03_09:19:52 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 17.912506 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: 5.005 Y: 2211 Z: -29.7023 O: 0
GUID Full: 0x0000000000001d35 Type: Player Low: 7477 Entry 0
Name: Aokromes
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 0 ExtraUnitMovementFlags: 0 Class: 9
 MoveSpline
spline Id: 0
flags:  Done

time passed: 0
total  time: 0
spline point Id: 0
path  point  Id: 1
mode: Uninitialized
points count: 0

**Comment by Jildor** [comment]
With tele command you die and get falldamage log and when player report it you don't get falldamage log?

**Comment by Aokromes** [comment]
> With tele command you die and get falldamage log and when player report it you don't get falldamage log?

i have added a new log, without new log no log at all.

**Comment by Aokromes** [comment]
also.

.go xyz 0.00005 2211 30.1157 631
unable to move
.tele jail
die



2020-12-03_11:40:15 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 40.825005 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: 5e-05 Y: 2211 Z: 30.1157 O: 0
GUID Full: 0x0000000000001d35 Type: Player Low: 7477 Entry 0
Name: Aokromes
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 16777216 ExtraUnitMovementFlags: 0 Class: 9
 MoveSpline
spline Id: 0
flags:  Done

time passed: 0
total  time: 0
spline point Id: 0
path  point  Id: 1
mode: Uninitialized
points count: 0

**Comment by Aokromes** [comment]
.go xyz 0.0005 2211 30.1157 631 is enough to leave you stuck and die.

**Comment by Aokromes** [comment]
idk if this is also like the 1st.

2020-12-03_22:41:06 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 94.142921 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -69.8015 Y: 2638.27 Z: 86.2307 O: 1.93109
GUID Full: xxxxxxx Type: Player Low: 185468 Entry 0
Name: xxxxxx
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 28673 ExtraUnitMovementFlags: 0 Class: 8
 MoveSpline
spline Id: 7136176
flags:  Done CanSwim Final_Angle Unknown6
facing  angle: 2.75437
time passed: 498
total  time: 498
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (-379.601, 2213.43, 47.5087)
point 1 : (-380.527, 2213.81, 47.5087)
point 2 : (-380.556, 2213.8, 44.0252)
point 3 : (-380.556, 2213.8, 44.0252)

**Comment by Aokromes** [comment]
and this

2020-12-04_23:40:32 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 419.999176 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -533.333 Y: 2130.56 Z: 199.97 O: 5.43669
GUID Full: xxxxxx Type: Player Low: 182669 Entry 0
Name: xxxxx
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 1 ExtraUnitMovementFlags: 0 Class: 4
 MoveSpline
spline Id: 28903303
flags:  Done CanSwim

time passed: 1091
total  time: 1091
spline point Id: 3
path  point  Id: 3
mode: Linear
points count: 6
point 0 : (-658.576, 2238.31, 51.8165)
point 1 : (-659.145, 2237.49, 51.8165)
point 2 : (-655.339, 2236.26, 51.8388)
point 3 : (-651.533, 2235.03, 51.8464)
point 4 : (-650.064, 2234.55, 51.8494)
point 5 : (-650.064, 2234.55, 51.8494)

**Comment by Aokromes** [comment]
and this

2020-12-04_23:43:54 DEBUG [entities.player.falldamage] FALLDAMAGE z=469.819550 sz=469.791534 pZ=472.849579 FallTime=2827 mZ=469.791534 damage=1874 SF=0
Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -443.684 Y: 2461.39 Z: 472.85 O: 1.67766
GUID Full: xxxxxx Type: Player Low: 185467 Entry 0
Name: xxxx
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 20993 ExtraUnitMovementFlags: 0 Class: 2
 MoveSpline
spline Id: 29087050
flags:  Done

time passed: 0
total  time: 0
spline point Id: 4
path  point  Id: 5
mode: Linear
points count: 0

**Comment by illfated** [comment]
Seeing those 5 log entries containing `FALLDAMAGE Below map` makes me think that this could still be a map issue, where some very few specific tiles are under the correct map.

**Comment by Aokromes** [comment]
2020-12-06_19:15:29 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 419.999176 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -533.333 Y: 2221.26 Z: 59.762 O: 2.60346
GUID Full: xxxxxx Type: Player Low: 184499 Entry 0
Name: xxxxxx
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 9 ExtraUnitMovementFlags: 0 Class: 7
 MoveSpline
spline Id: 2144802
flags:  Done CanSwim Final_Angle Unknown6
facing  angle: 4.37287
time passed: 581
total  time: 581
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (547.027, 331.894, 360.802)
point 1 : (546.694, 330.951, 360.802)
point 2 : (546.694, 330.951, 364.864)
point 3 : (546.694, 330.951, 364.864)

**Comment by Aokromes** [comment]
2020-12-06_19:33:13 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 76.804428 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -465.454 Y: 1862.23 Z: 61.4656 O: 2.63033
GUID Full: xxxxxx Type: Player Low: 184486 Entry 0
Name: xxxxxx
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 28673 ExtraUnitMovementFlags: 0 Class: 11
 MoveSpline
spline Id: 2137844
flags:  Done CanSwim Final_Angle Unknown6
facing  angle: 3.16845
time passed: 581
total  time: 581
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (555.616, 308.953, 360.802)
point 1 : (554.616, 308.926, 360.802)
point 2 : (554.616, 308.926, 364.864)
point 3 : (554.616, 308.926, 364.864)

**Comment by Aokromes** [comment]
i was told this was after use teleport



2020-12-09_22:39:23 DEBUG [entities.player.falldamage] FALLDAMAGE Below map. Map min height: 19.283365 , Player debug info:
MapID: 631 Map name: 'Icecrown Citadel' X: -17.6657 Y: 2212.22 Z: 15.8181 O: 3.14158
GUID Full: xxxxx Type: Player Low: xxx Entry 0
Name: xxxxx 
IsAIEnabled: false DeathState: 0 UnitMovementFlags: 12288 ExtraUnitMovementFlags: 0 Class: 6
 MoveSpline
spline Id: 6616840
flags:  Done CanSwim Final_Angle Unknown6
facing  angle: 1.86437
time passed: 254
total  time: 254
spline point Id: 1
path  point  Id: 1
mode: Linear
points count: 4
point 0 : (18.6305, 28.9705, 36.3265)
point 1 : (18.1923, 29.8694, 36.3265)
point 2 : (18.2037, 30.2174, 38.0684)
point 3 : (18.2037, 30.2174, 38.0684)

**Comment by Aokromes** [comment]
https://i.imgur.com/7q2PAiE.png

**Comment by Aokromes** [comment]
a lot of times you die if you use teleport from deathbringer's rise to entrance
move from gunship to teleport, use it to entrance, die.

**Comment by Jildor** [comment]
Seems when you go from the ship to teleporter and teleport to Light Hammer, the teleport position is wrong, but I cannot reproduce die for fall damage.
https://imgur.com/a/w5LGQFh

**Comment by Aokromes** [comment]
don't jump and don't gm fly on xd

**Comment by Jildor** [comment]
I tested a lot of times with player account before comment, I don't have gm fly on xD.
I tested with blink, jump, walking, and I can't reproduce fall damage.
are you testing with clean TC and re-extracted mmaps with default confs?

**Comment by Aokromes** [comment]
> I tested a lot of times with player account before comment, I don't have gm fly on xD.
> I tested with blink, jump, walking, and I can't reproduce fall damage.
> are you testing with clean TC and re-extracted mmaps with default confs?

i tested on tcubuntu.

**Comment by offl** [comment]
There were no changes in 1+ month, this started to occur 1+ month ago and nobody yet didn't tried to revert any commit related to mmaps and stuff like that?

**Comment by Jildor** [comment]
I was trying to reproduce the error first, but I can't

**Comment by Jildor** [comment]
well, I can reproduce fall damage when I go from the ship to the Saurfang teleporter and teleport to the upper spire (after kill saurfang), but I can't reproduce fall under the ground, for some reason when you go to the boat and return, you get wrong teleport position
https://imgur.com/eBagBcZ

**Comment by jackpoz** [comment]
Some notes about 2 cases at .go xyz 0.00005 2211 30.1157 631 , the first having a X a bit higher than 0.00005 (which is the buggy location) :
```
working:

grid
gx = 31
gy = 27

Compute
x_offset = -0.49999784382626744
y_offset = 3.6456251581430497
x_val = 32
y_val = 36

getMinHeight
doubleGridX = 63
doubleGridY = 55
gx = -533.332153
gy = -455.666504
quarterIndex = 5
result = 17.9125061






falldamage:

grid
gx = 32 <--- different, caused by floating point precision
gy = 27

Compute
x_offset = -0.49999990624999879
y_offset = 3.6456251581430497
x_val = 32 <-- same
y_val = 36

getMinHeight
doubleGridX = 64 <-- different
doubleGridY = 55
gx = -533.333252
gy = -455.666504
quarterIndex = 3 <-- different
result = 40.8250046 <-- different
```

fun fact: having 0.00005 gives different gx depending on if using float or double:
![image](https://user-images.githubusercontent.com/1153754/103172331-00edc500-4853-11eb-9028-0ce4b319e5e5.png)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0c69316714d0558e32462f5401197fe1e803ae75 fixes the case ".go xyz 0.0005 2211 30.1157 631" which was the initial issue found when opening this github issue.

Feel free to test the other cases and include how to reproduce steps for them if they still happen. For the teleport, please make sure the teleport coordinates are correct and not wrong in the first place.

**Comment by Jildor** [comment]
@jackpoz, coul you check that last commit better?
seems now you can die in the stairs

.go xyz -518.88 2209.442 62.82 631 2.997
move to the stairs

**Comment by jackpoz** [comment]
reverted the grid change, I will check the location you posted and open a PR instead

**Comment by jackpoz** [comment]
Turns out the new bugs were caused by the #define to constexpr changes which have been reverted. I opened a PR at https://github.com/TrinityCore/TrinityCore/pull/25771 again with the same fix I added and it works in the 2 places I tried. The change is so little that it can be applied manually.

**Comment by jackpoz** [comment]
@Jildor about the ship and teleport, when using the teleporter close enough to the ship it still things you are on it:

![image](https://user-images.githubusercontent.com/1153754/103207624-17e9f100-48ff-11eb-9dd1-c859d0dd38ae.png)

The teleport code uses ```ToPlayer()->TeleportTo(target, TELE_TO_NOT_LEAVE_TRANSPORT``` so even if you are teleported miles away, you are still considered on the ship (and ofc it bugs out)

**Comment by illfated** [comment]
"They've got a tractor beam on us. I can't break free!" 🚀 ⬇️ 💥 ✝️

**Comment by Jildor** [comment]
yes, I was recording an example of the teleporter and the ship
https://imgur.com/a/BfGIL1S

**Comment by jackpoz** [comment]
Fixed the gunship/teleport case too.
