### ISSUE TITLE
DB/Quest: The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#25668]
https://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron

Ref [4763](https://github.com/TrinityCore/TrinityCore/issues/4763)

Description:
The quest is broken. Can't get [Flawless Arcane Essence](https://www.wowhead.com/item=32822/flawless-arcane-essence), because the [Flawless Arcane Elemental](https://www.wowhead.com/npc=23100/flawless-arcane-elemental) disappears after his death and it cannot be looted. The corpses of all elementals, except [Flawless Arcane Elemental](https://www.wowhead.com/npc=23100/flawless-arcane-elemental), remain on the ground. Also, the "essences" of earth and fire after defeating the corresponding elementals do not trigger the [Minions of Sar'this](https://www.wowhead.com/npc=23094/minion-of-sarthis) unlike the elementals of air and water (cosmetic issue and maybe it should be).

Expected behaviour:
[Flawless Arcane Elemental](https://www.wowhead.com/npc=23100/flawless-arcane-elemental) must be lootable after his death and he must drop [Flawless Arcane Essence](https://www.wowhead.com/item=32822/flawless-arcane-essence).

Steps to reproduce the problem:
1.	.character level 70
2.	Take quest [The Soul Cannon of Reth'hedron](https://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron) from [Illidari Lord Balthas](https://www.wowhead.com/npc=23427/illidari-lord-balthas) (this requires reputation with Netherwing faction).
3.	.go xyz -2500 4674 163 530
4.	Talk with [Sar'this](https://www.wowhead.com/npc=23093/sarthis)
5.	Follow [Sar'this](https://www.wowhead.com/npc=23093/sarthis) and kill elementals
6.	After killing [Flawless Arcane Elemental](https://www.wowhead.com/npc=23100/flawless-arcane-elemental) watch it disappear, cannot be looted and you will become sad.

Branch:
3.3.5

TC rev. hash/commit:
TrinityCore rev. [b52c89f](https://github.com/TrinityCore/TrinityCore/commit/b52c89f1bae1d8a6b91a42421d268fa93d86433b) 2020-11-11 21:51:31 +0300 (3.3.5 branch) (Win64, Release, Static)

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d 10 Sep 2019 (library: OpenSSL 1.1.1d 10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.20101
MySQL client library: 5.7.28
MySQL server ver: 5.7.28

Operating system:
Win7 SP1 x64 with all updates.

**Comment by offl** [comment]
Interesting, I tried to fix some issues and tested this multiple times but I don't remember if this occured or not
Probably last time I edited it I added excess action and didn't noticed it

**Comment by Freeman256** [comment]
Just checked - it works. Flawless Arcane Elemental became lootable after his death and he drop Flawless Arcane Essence. But there is still a cosmetic and non-critical problem with the fact that "essences" of earth and fire after defeating the corresponding elementals do not trigger the Minions of Sar'this unlike the elementals of air and water. However, thanks a lot! I hope that someday EVERYTHING will work like on official servers but for free and without restrictions.

TC rev. hash/commit:
TrinityCore rev. [b2fd442](https://github.com/TrinityCore/TrinityCore/commit/b2fd442f64c5671709a4dc6e0521855b94f9b0b9) 2020-11-26 13:09:08 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by offl** [comment]
Forgot to mention https://github.com/TrinityCore/TrinityCore/issues/4763#issuecomment-647787928
I simply don't know how exactly all minions are always triggered, current implementation of minions is pretty basic because of our core limitations & lack of info

**Comment by illfated** [comment]
@Freeman256 : Thanks for the useful feedback and interaction.

Would just like to give you a practical tip regarding rev. hash links:
You don't have to format it as a regular link, because GitHub will read the rev. hash and convert it automatically, as long as the rev. hash is either 7, 10, or 12+ characters, or all of them, or the full URL to the commit page, but _without_ adding MarkDown link to that text.

For example, if I paste the link from your URL in this comment, without adding the MarkDown URL conversion, it shows up like this: https://github.com/TrinityCore/TrinityCore/commit/b2fd442f64c5671709a4dc6e0521855b94f9b0b9

The bonus of providing the unformatted rev. hash is that most browsers will display a popup with some of the page details if the rev. hash is handled by GitHub itself.

**Comment by Freeman256** [comment]
**illfated**: Ok, I'll keep it in mind for the future. I didn't know it was possible.

**Comment by illfated** [comment]
Very good.

Ah, right, I forgot to mention that there is also another feature of the rev. hash, where in some cases it can also display extra info like a plus sign ( + ) after a hash from a modified source, where most of the source is original content, but with minor changes. It will not produce a link at all when the rev. hash is too different from any existing commits in the current repository, making it obvious when someone posts a rev. hash from a completely different compiled source than the current repo (like GitLab or an offshoot like Rochet2's Transmogrification 3.3.5, Eluna Lua source or heavily modified repack versions.
