### ISSUE TITLE
Guardian pets attacks all enemies

### ISSUE THREAD

**Issue by lingxDEV** [TrinityCore/TrinityCore#25663]
**Description:**

Summoned Guardian pets will attack any nearby hostile mobs.

**Expected behaviour:**

Guardian pets should only attack mobs that you attack / get into combat with.

**Steps to reproduce the problem:**

1. .add item 15778
2. Stand nearby hostile enemy (name in red)
3. See that the Guardian pet will attack on it's own.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

cc8287927b9c9f0bf20143972fd4d3c338bff688

**Operating system:** 

Win1064

**Comment by lingxDEV** [comment]
Incorrect report, should be aggresive upon spawning. Closed.

**Comment by illfated** [comment]
Fair question, though. At least it made me rethink whether I knew the answer or not.
