### ISSUE TITLE
DB/Quest: Delivering the Message

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#25666]
https://www.wowhead.com/quest=10406/delivering-the-message

Description:
Quest not working. 

Expected behaviour:
After sabotage the pipeline will done, quest must be completed.

Steps to reproduce the problem:
1. .character level 70
2. .go xyz 4251 2171 138 530
3. Complete quests from Commander Ameer:
https://www.wowhead.com/quest=10339/the-ethereum
https://www.wowhead.com/quest=10384/ethereum-data
https://www.wowhead.com/quest=10385/potential-for-brain-damage-high
https://www.wowhead.com/quest=10405/s-a-b-o-t-a-g-e
4. Take quest https://www.wowhead.com/quest=10406/delivering-the-message
5. Follow and protect Protectorate Demolitionist to the Manaforge Ultris conduit
6. After sabotage the pipeline will done, quest will not be completed.

Branch:
3.3.5

TC rev. hash/commit:

TrinityCore rev. [b52c89f](https://github.com/TrinityCore/TrinityCore/commit/b52c89f1bae1d8a6b91a42421d268fa93d86433b) 2020-11-11 21:51:31 +0300 (3.3.5 branch) (Win64, Release, Static)

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.20101
MySQL client library: 5.7.28
MySQL server ver: 5.7.28 

Operating system:
Win7 SP1 x64 with all updates.

**Comment by TranceAccount** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=20802
SAI action number 10: `Exploration event of Delivering the Message is completed for closest player within 15m.`
Do you know approximately if you were close to the npc or not?

**Comment by Freeman256** [comment]
I confirm the quest is working. It was necessary to keep very close to Protectorate Demolitionist.

**Comment by TranceAccount** [comment]
Personally, I think you should keep this report open, as the quest credit style is inappropriate and should be possible over longer ranges or just be rewarded to the questing person/group. Additionally, if another person on this quest just happens to be more closer to the quest rewarding NPC, he could complete the quest instead of the person actually doing the quest, which might happen to be fighting a mob a few feet further.

**Comment by offl** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=35680

**Comment by dr-j** [comment]
Maybe that target 21 needs to be changed to 23 (owner or summoner) as this is summoned by spell cast on player on quest accept

**Comment by illfated** [comment]
( edited table details from https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130108/smart+scripts )

|   Name                          | Value |   target_param1          |   target_param2                   |   target_param3                      |   Comment  |
| :------------------             | :---: | ------------------------ | --------------------------------- | ------------------------------------ | :--------- |
| SMART_TARGET_NONE               |    0  |                          |                                   |                                      |   None.    |
| SMART_TARGET_SELF               |    1  |                          |                                   |                                      | Self cast. |
| SMART_TARGET_VICTIM             |    2  |                          |                                   |                                      | Our current target. (ie: highest aggro) |
| SMART_TARGET_ACTION_INVOKER     |    7  |                          |                                   |                                      | Unit who caused this Event to occur. |
| SMART_TARGET_CREATURE_DISTANCE  |   11  | creature Entry<br>(0 any)| maxDist                           |Number of targets<br>(0 = all targets)| Creature with specified ID within distance. |
| SMART_TARGET_STORED             |   12  | id                       |                                   |                                      | Uses pre-stored target(list) |
| SMART_TARGET_INVOKER_PARTY      |   16  |                          |                                   |                                      | Invoker's party members |
| SMART_TARGET_PLAYER_RANGE       |   17  | minDist                  | maxDist                           |                                      | (Random?) player within specified range. |
| SMART_TARGET_PLAYER_DISTANCE    |   18  | maxDist                  |                                   |                                      | (Random?) player within specified distance. (Different from #17?) |
| SMART_TARGET_CLOSEST_CREATURE   |   19  | creature Entry<br>(0 any)| maxDist (Can be from 0-100 yards) | dead? (0/1)                          | Closest creature with specified ID within specified range. |
| SMART_TARGET_CLOSEST_GAMEOBJECT |   20  | GO Entry <br>(0 any)     | maxDist (Can be from 0-100 yards) |                                      | Closest object with specified ID within specified range. |
| SMART_TARGET_CLOSEST_PLAYER     |   21  | maxDist                  |                                   |                                      | Closest player within specified range. |
| SMART_TARGET_OWNER_OR_SUMMONER  |   23  |                          |                                   |                                      | Unit's owner or summoner |
