### ISSUE TITLE
DB/Locale/itIT Texts missing in quests

### ISSUE THREAD

**Issue by Ryzen-0** [TrinityCore/TrinityCore#25664]
**Description:**

Parsed from wowhead (master-branch).

itIT-eastern-kingdoms.sql
itIT-eastern-kingdoms-gtranslate.sql (missing translations google translated for who want to use anyway)

[itIT-eastern-kingdoms.zip](https://github.com/TrinityCore/TrinityCore/files/5572882/itIT-eastern-kingdoms.zip)

**Branch(es):**

- [ ] 3.3.5
- [x] master

**TDB version:** TDB 837.20101

**TC rev. hash/commit:** 

**Operating system:** Windows 10

**Comment by illfated** [comment]
@FrancescoBorzi : Would you like to proof-read the contents, or suggest someone to do so? 🙂 🎏

**Comment by FrancescoBorzi** [comment]
hi @illfated thanks for pinging me but I don't have the time for this :)

**Comment by Ryzen-0** [comment]
This one is updated with almost all quest.
[itIT-quest.zip](https://github.com/TrinityCore/TrinityCore/files/5623389/itIT-quest.zip)

- itIT-wowhead (already in italian from wowhead, only parsed from there)
- itIT-gtrasnlate (missing translations, so gtranslated)

I have included gtranslated ones **just for who want**, although they are not always done well.

**Comment by LuigiElleBalotta** [comment]
Use translations from it.wowhead.com, they are perfect

An italian guy

**Comment by Ryzen-0** [comment]
I have used them from it.wowhead.com but many are missing so for these ones i created a separated file "itIT-gtranslate" (translated with google).
