### ISSUE TITLE
BFA 8.3.7 Allied Races. How to fix?

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#25678]
Allied Races. How to fix?

**Comment by illfated** [comment]
Contributing to the source is a good thing. Also, following the issue ticket template is a good introduction to co-working with TrinityCore users and members.

**Comment by rem999** [comment]
Thanks for your feedback. I'm not good at it. How can I fix it? For a noob. If TrinityCore fixes it themselves, I won't mind.

**Comment by illfated** [comment]
First of all, consider starting with detailed, individual (very specific) issues. TC members and contributors depend on detailed, constructive feedback to get anything done with the source & DB contents. "Allied Races. How to fix?" is a too broad and not specific enough description. We need more information, preferably all the details asked for in the issue ticket template.

Also, either please add back the issue ticket template from this page:
- https://github.com/TrinityCore/TrinityCore/issues/new/choose

or, if that seems a bit much to ask, you could always close this ticket and open a new one when you have gathered enough information on your specific issue.

Starting off by creating a complete issue ticket is a very good start in the process of working with the TC members and contributors to solve issues, as well as it shows that you care about the source and would like to do what it takes to add useful information in your interaction with this repository.

If you are involved enough with the source to start finding out how it works and how to contribute, use a cloned source and compile the source to make the server binaries and database your own local computer. Using Git Clone to duplicate the source on your computer ensures that you get validated source with git rev. (revision) hash to fill in to the issue tickets you create, making it easier to track the progression of the issue ticket.

Please note that there is quite a lot of information available on making your own local proper version of TrinityCore on your computer:
- https://trinitycore.atlassian.net/wiki/spaces/tc/overview?mode=global

If you have only copied the source by downloading it from the main TC repo page (https://github.com/TrinityCore/TrinityCore), you usually end up with "Trinitycore rev. 1970-01-01 00:00:00 +0000", which is not very useful when reporting an issue.

**Comment by offl** [comment]
Better to ask on forum

**Comment by Aokromes** [comment]
you need content to be fixed to have working allied races.

**Comment by illfated** [comment]
I was sort of trying to say that, but in a very roundabout way. Oh well. Better luck with the next issue ticket.

**Comment by rem999** [comment]
> вам нужно исправить контент, чтобы иметь рабочие союзные расы.

Sounds tempting. It is very interesting. As an example or any video. It would help me a lot.

**Comment by rem999** [comment]
> Better to ask on forum

Please link to the forum?

**Comment by Aokromes** [comment]
> > you need content to be fixed to have working allied races.
> 
> Sounds tempting. It is very interesting. As an example or any video. It would help me a lot.

GL on that, you need to spawn all post cata content.

**Comment by illfated** [comment]
> > Better to ask on forum
> 
> Please link to the forum?

https://community.trinitycore.org/


> > you need content to be fixed to have working allied races.
> 
> Sounds tempting. It is very interesting. As an example or any video. It would help me a lot.

The main challenge is that TC master branch does not have necessary content added (like Aokromes wrote above) after Cataclysm (which also  is not as complete as the content up to and including 3.3.5). A lot of work of adding NPC spawns, NPC behaviour (movement, scripts, gossip, text, etc.) has to be added and completed to get far enough to have new allied race information added to the server content.

**Comment by rem999** [comment]
Thank you, I'll try to go to the forum.
