### ISSUE TITLE
Death Knight Spell on Talent Name Dancing Rune Weapon doesnt work

### ISSUE THREAD

**Issue by sawd20** [TrinityCore/TrinityCore#25675]
**Death knight Talent Blood tab Ability Named Dancing Rune Weapon Doesnt work:**

this ability should deal 50 % of your weapon damage when you use any other ability of dk to the target but it wont work it just stuck at a place and does noting 

**Expected behaviour:**

it should attack the target with any spell death knight use + animation within 12 secs and with glyph of Dancing Rune Weapon up to 17 secs

**Steps to reproduce the problem:**

1. https://www.wowhead.com/spell=49028/dancing-rune-weapon
2. should use Death knight abilities for 50% damage 
3. Step 3

**Branch(es):**

3.3.5

**Operating system:** Win OS

**Comment by offl** [comment]
Duplicate of #6192

**Comment by sawd20** [comment]
yea right
