### ISSUE TITLE
Commands not working, scripts not recognized

### ISSUE THREAD

**Issue by azure-hu** [TrinityCore/TrinityCore#25670]
**Description:**

None of the commands working after building the current source. 
MSVC2019 gave the attached warnings related to commands:
https://gist.github.com/azure-hu/57102e58aba8404559622bc0bd8e410d
During worldserver startup, there are too many command and script alerts.
I've uploaded the entire console output here:
https://gist.github.com/azure-hu/71e4b704bec97fd26507574b6492ca0a

**Expected behaviour:**

At least the help command should work.

**Steps to reproduce the problem:**

Cloned the current state to an empty folder.
Built the core on Windows with dynamic scritps (like I did all the time) in MSVC2019.
Rebuilt the world db using the TDB_full_world_335.20111_2020_11_16.sql file.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5270ff58daf3+

**Operating system:** Windows Server 2012 R2

**Comment by Aokromes** [comment]
you broke your source and used altered database, a clean core works fine.

**Comment by azure-hu** [comment]
What do you mean I broke the source? This happens after a clean git cloning too. 
Okay, the latest TDB release was applied manually, but because the core didn't started to update from TDB release, only by using the source folder, where it found conflicting scripts which was already applied.
Should I drop the entire database, and create it again, including character and auth db too?

**Comment by Aokromes** [comment]
drop only world database.
also that + means you changed c++/h files.

**Comment by azure-hu** [comment]
But I haven't changed anything in the source files. Only in cmake/compiler/msvc/settings.cmake, i commented out the following lines, because build failed with Windows 8.1 SDK:

`target_compile_options(trinity-compile-option-interface
  INTERFACE
    /permissive-)`
 
I made a clean clone of the repository, rebuilt again, dropped world db and rebuilt from TDB. 
Nothing changed, still the same output on the console.

**Comment by jackpoz** [comment]
>TrinityCore rev. 5270ff58daf3+ 2020-11-21 16:33:00 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Dynamic)

This issue happens when building in Dynamic mode and not knowing how to use it. Please build in Static to confirm everything works fine, then switch to Dynamic and continue troubleshooting your issue.

In general, if you don't need dynamic build then don't use it.

**Comment by Faq** [comment]
Also just wondering why use 8.1, but not 10 SDK?

**Comment by illfated** [comment]
Compatibility issues, maybe?

**Comment by azure-hu** [comment]
Building in static works, but all the warnings stayed. Thanks, jackpoz!
I use Windows 8.1 SDK because I'm not running the worldserver on newer operating systems than a server 2012 R2, and no need to use 10 SDK.

**Comment by Shauren** [comment]
It shouldn't matter which SDK you use (8 or 10) as long as its newer than what we declare in _WIN32_WINNT, currently set to 0x0601, corresponding to Windows 7 SDK, we don't use any os specific feature from newer versions

**Comment by shamage** [comment]
@azure-hu : Building a static version is without warnings or error messages. I recommend checking that the assembly procedure is compliant. If you are not sure what you are getting into - just do a static version of the building and most importantly do not change anything there and you will be successful :) (provided that you have followed all the correct and necessary preparations to create such a compilation)
I'm already compiling on Win 10 Pro and I also recommend it for you due to the compatibility of some programs.
