### ISSUE TITLE
DB/Quests: Pilgrim's Bounty

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25671]
**Description:**

How do we proceed to suggest solutions to all the blank dialogs in the Pilgrim's Bounty quest completion gossips? Can we use text directly from wowhead.com for all of them, or should we wait for some sniff source?

(Please forgive me if this is something that goes without saying, but I have had a stressful time lately and my mind feels like a blank paper regarding the answer to that question at this time.)

***

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?event=26#quests
- https://www.wowhead.com/pilgrims-bounty#quests

***

I just noticed that none of the quests in Pilgrim's Bounty have got any text except for the initial gossip where the quest itself is described. There is no Quest ID specific text in `quest_offer_reward`.`RewardText` or `quest_request_items`.`CompletionText`.

***

**Expected behaviour:**

There should be at least some very few words in the `RewardText` and `CompletionText` gossip dialogs.

**Steps to reproduce the problem:**

1. Take any character to the nearest  Pilgrim's Bounty feast gathering outside one of the major cities
2. Pick up any simple and completable quest.
3. Complete & hand in the quest, notice that only the section headlines are there, but no text specific to this quest.

**Branch(es):**

3.3.5 (probably master too?)

**TC rev. hash/commit:** 

TC> server debug
TrinityCore rev. 5270ff58daf3 2020-11-21 16:33:00 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.73.0
Using MySQL version: 50731
Using CMake version: 3.18.3
Compiled on: Windows 10.0.19041
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.20111
TC> _

**Operating system:** Windows 10 Home x64 20H2 (OS Build 19042.630)

**Comment by offl** [comment]
Sniffs are always better and I'm pretty sure we have all those quests sniffed, however if you want it today, use wowhead

**Comment by illfated** [comment]
Oh well, fair enough. Thanks for replying and confirming. I have already run through most of the quests to be done during 1 day while doing my best to ignore the blank gossip, so I was sort of hoping for more interest from other users, making it feel more important to work on forming the suggested solutions based on the easiest available information.

**Comment by illfated** [comment]
D'oh. I just checked the DB and found that none of the listed quests on the "Pilgrim's Bounty" page have got any rows at all in the 2 relevant tables:

```sql
SELECT * FROM `quest_request_items` WHERE `ID` IN (14022,14023,14024,14028,14030,14033,14035,14036,14037,14040,14041,14043,14044,14047,14064,14065);
```
```
  ID    EmoteOnComplete  EmoteOnIncomplete  CompletionText  VerifiedBuild
------  ---------------  -----------------  --------------  -------------
```

```sql
SELECT * FROM `quest_offer_reward` WHERE `ID` IN (14022,14023,14024,14028,14030,14033,14035,14036,14037,14040,14041,14043,14044,14047,14064,14065);
```
```
  ID    Emote1  Emote2  Emote3  Emote4  EmoteDelay1  EmoteDelay2  EmoteDelay3  EmoteDelay4  RewardText  VerifiedBuild
------  ------  ------  ------  ------  -----------  -----------  -----------  -----------  ----------  -------------
```

`*sigh*` Oh well. Need to fill in all the correct values for all the required rows, sooner or later.

**Comment by TQPS** [comment]
Since the quests appear to be the same since their release, I cant imagine their gossip has changed that much over the years.

**Comment by illfated** [comment]
Thank you, fair point. I will look up the information in the wowhead.com pages and write up a suggestion when I have enough material. Also going to check which fields contain auto values and which ones can be filled with 0 (zero) to make the suggestions stable.

**Comment by illfated** [comment]
**Suggested solution** — based on https://www.wowhead.com/pilgrims-bounty#quests :

This SQL has only been tested by adding it to my DB locally, but it parses well and without errors.
Feel free to suggest improvements, if you find anything that appears obvious to you.

```sql
-- Pilgrim's Bounty quest gossip
-- CompletionText for 22 of 26 quests, 4 are RewardText only (source: wowhead.com)
DELETE FROM `quest_request_items` WHERE `ID` IN (14023,14024,14028,14030,14033,14035,14037,14040,14041,14043,14044,14047,14048,14051,14053,14054,14055,14058,14059,14060,14061,14062);
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES
(14023, 0, 0, "We can always use more of that delicious spice bread stuffing. It's very popular.", 0),
(14024, 0, 0, "More pumpkin pie? Just in time.", 0),
(14028, 0, 0, "Is that cranberry chutney I smell?", 0),
(14030, 0, 0, "Have you come to partake of the Pilgrim's Bounty feast?", 0),
(14033, 0, 0, "$n, it's good to see you again.", 0),
(14035, 0, 0, "What brings you back to Darnassus, $n?", 0),
(14037, 0, 0, "The tables could really use more of that spice bread stuffing.", 0),
(14040, 0, 0, "We can always use more pumpkin pie.", 0),
(14041, 0, 0, "How are you enjoying Pilgrim's Bounty, $c?", 0),
(14043, 0, 0, "Welcome back, $n.", 0),
(14044, 0, 0, "It's good to see you again. $n.", 0),
(14047, 0, 0, "What brings you back to Orgrimmar, $n?", 0),
(14048, 0, 0, "Did you manage to find those turkeys?", 0),
(14051, 0, 0, "Were you able to get that stuffing?", 0),
(14053, 0, 0, "Were you able to get your hands on any cranberry chutney?", 0),
(14054, 0, 0, "How are those pies coming along?", 0),
(14055, 0, 0, "Do you have those candied sweet potatoes?", 0),
(14058, 0, 0, "Do you have those candied sweet potatoes?", 0),
(14059, 0, 0, "Were you able to get your hands on any cranberry chutney?", 0),
(14060, 0, 0, "How are those pies coming along?", 0),
(14061, 0, 0, "How's your turkey hunt going?", 0),
(14062, 0, 0, "Were you able to get that stuffing?", 0);

-- RewardText for all 26 quests (source: wowhead.com)
DELETE FROM `quest_offer_reward` WHERE `ID` IN (14022,14023,14024,14028,14030,14033,14035,14036,14037,14040,14041,14043,14044,14047,14048,14051,14053,14054,14055,14058,14059,14060,14061,14062,14064,14065);
INSERT INTO `quest_offer_reward` (`ID`,`Emote1`,`Emote2`,`Emote3`,`Emote4`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`EmoteDelay4`,`RewardText`,`VerifiedBuild`) VALUES
(14022, 0, 0, 0, 0, 0, 0, 0, 0, "If you'd like to learn to cook Pilgrim's Bounty foods, I can help. If you're not already a cook, all you have to do is train and you'll be cooking in no time!", 0),
(14023, 0, 0, 0, 0, 0, 0, 0, 0, "Excellent. This is just what we needed. It's going to be a chore keeping all the tables stocked with fresh food, but it's well worth it.", 0),
(14024, 0, 0, 0, 0, 0, 0, 0, 0, "The pumpkin pie's been a big hit up here. I've never seen a dwarf get so excited about anything made from a vegetable.", 0),
(14028, 0, 0, 0, 0, 0, 0, 0, 0, "Finally, the cranberry chutney I was promised. You wouldn't believe how fast the celebrants go through the stuff here.", 0),
(14030, 0, 0, 0, 0, 0, 0, 0, 0, "Thanks for bringing everything. I was starting to get worried.$B$BWhile you're here, you should try your hand at making some candied sweet potatoes.", 0),
(14033, 0, 0, 0, 0, 0, 0, 0, 0, "Ah, candied sweet potatoes! My favorite! Did Isaac tell you?", 0),
(14035, 0, 0, 0, 0, 0, 0, 0, 0, "These are beautiful and just in time to feed hungry feasters. Thank you, $n. You've truly mastered all the courses of a traditional Pilgrim's Bounty meal.", 0),
(14036, 0, 0, 0, 0, 0, 0, 0, 0, "If you'd like to learn to cook Pilgrim's Bounty foods, I can help. If you're not already a cook, all you have to do is train and you'll be cooking in no time.", 0),
(14037, 0, 0, 0, 0, 0, 0, 0, 0, "It's a chore keeping all these tables stocked. If you stop and think about it, it's strange going to so much trouble when we needn't eat anymore.", 0),
(14040, 0, 0, 0, 0, 0, 0, 0, 0, "The pie always goes first. I think people must be skipping the meal and going directly for the dessert. Have you given it a try yet?", 0),
(14041, 0, 0, 0, 0, 0, 0, 0, 0, "Ah, more cranberry chutney! You wouldn't believe how fast the celebrants go through it.", 0),
(14043, 0, 0, 0, 0, 0, 0, 0, 0, "So Dokin drafted you to help with the candied sweet potatoes?$B$B<Francis smiles.>$B$BIt's the only way he can keep up. Thanks for bringing these.", 0),
(14044, 0, 0, 0, 0, 0, 0, 0, 0, "Thanks for bringing everything. Some of the tables were starting to look a little bereft of serving dishes.", 0),
(14047, 0, 0, 0, 0, 0, 0, 0, 0, "These look perfect. Thank you, $n. You've truly mastered all the courses of a traditional Pilgrim's Bounty meal.", 0),
(14048, 0, 0, 0, 0, 0, 0, 0, 0, "These are just what I need. Thanks, $n. You're a lifesaver.", 0),
(14051, 0, 0, 0, 0, 0, 0, 0, 0, "Thank goodness! I wouldn't be able to serve the feast without spice bread stuffing.", 0),
(14053, 0, 0, 0, 0, 0, 0, 0, 0, "Thanks. This looks great, and you're a fair bit faster than Jasper, but don't tell him I said so.", 0),
(14054, 0, 0, 0, 0, 0, 0, 0, 0, "These are perfect. Isaac, and everyone else, will love them!", 0),
(14055, 0, 0, 0, 0, 0, 0, 0, 0, "These are perfect. Thanks for helping me with this, $n. The meal will get served on time and Ellen will be happy.", 0),
(14058, 0, 0, 0, 0, 0, 0, 0, 0, "Thanks, $n. Now, I can help the hostess out and still keep my word to Roberta.", 0),
(14059, 0, 0, 0, 0, 0, 0, 0, 0, "Thanks for your help, and let me know if you ever get to the bottom of the case of the disappearing chutney.", 0),
(14060, 0, 0, 0, 0, 0, 0, 0, 0, "These are great! Thank you for helping, $n.", 0),
(14061, 0, 0, 0, 0, 0, 0, 0, 0, "These turkeys are exactly what I needed. Thanks for helping me out of a tough situation.", 0),
(14062, 0, 0, 0, 0, 0, 0, 0, 0, "Perfect timing! I wouldn't be able to serve the feast without spice bread stuffing.", 0),
(14064, 0, 0, 0, 0, 0, 0, 0, 0, "What a feast, hmmm?$B$BI'm so glad you could celebrate the spirit of Pilgrim's Bounty with us.", 0),
(14065, 0, 0, 0, 0, 0, 0, 0, 0, "What a feast, hmmm?$B$BI'm so glad you could celebrate the spirit of Pilgrim's Bounty with us.", 0);
```

Best of luck to those who go digging in the .dbc files to find the emotes. Wish I had the patience.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
(BTW, my computer software values are still the same as in my main issue ticket comment.)
