### ISSUE TITLE
DB/Creature: CREATURE_DIFFICULTYFLAGS_2_KEEP_HEALTH_POINTS_AT_RESET actually is CREATURE_FLAG_EXTRA_NO_SKILLGAIN

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25674]
**Description:**

This is all mobs with CREATURE_FLAG_EXTRA_NO_SKILLGAIN and their Flags2.

As you can see with high chance that extra flag was added just to all dummy-creatures because first 3 without CREATURE_DIFFICULTYFLAGS_2_KEEP_HEALTH_POINTS_AT_RESET probably should not have this flag at all. They all are not static spawns and they can be killed. In other words they're not real training dummies.

Hellfire Training Dummy even cannot be attacked by players.
```text
    Flags2   entry  name                          
----------  ------  ------------------------------
         0    2673  Target Dummy                  
         0    2674  Advanced Target Dummy         
         0   16111  Love Fool                     
         0   17578  Hellfire Training Dummy       
1073741856   24792  Advanced Training Dummy       
1073742336   31144  Grandmaster's Training Dummy  
1073742336   31146  Heroic Training Dummy         
1073742336   32541  Initiate's Training Dummy     
1073742336   32542  Disciple's Training Dummy     
1073742336   32543  Veteran's Training Dummy      
1073742336   32545  Initiate's Training Dummy     
1073742336   32546  Ebon Knight's Training Dummy  
1073742336   32547  Highlord's Nemesis Trainer    
1073742336   32666  Expert's Training Dummy       
1073742336   32667  Master's Training Dummy       
1073741856   33229  Melee Target                  
```

And this is all creatures with that flag in MoP.
(397,4952,7666,7668,7669,7670,7671,11446,16478,16484,16490,16493,16494,16495,18731,20284,21416,21506,21709,21710,21711,24792,27355,27461,27485,28017,28659,28712,28720,28781,29441,29442,31012,31144,31146,31324,31744,32541,32542,32543,32545,32546,32547,32666,32667,33229,33243,33272,33568,34444,34445,34447,34459,34465,34466,34469,34470,34632,34775,34776,34793,34802,35069,35273,36954,38857)
```text
 entry  name                          
------  ------------------------------
   397  Morganth                      
  4952  Theramore Combat Dummy        
  7666  Archmage Allistarj            
  7668  Servant of Razelikh           
  7669  Servant of Grol               
  7670  Servant of Allistarj          
  7671  Servant of Sevine             
 11446  Gordok Spirit                 
 16478  Lieutenant Orrin              
 16484  Lieutenant Nevell             
 16490  Lieutenant Lisande            
 16493  Lieutenant Dagel              
 16494  Lieutenant Rukag              
 16495  Lieutenant Beitha             
 18731  Ambassador Hellmaw            
 20284  Dr. Boom                      
 21416  Lakaan                        
 21506  Azaloth                       
 21709  Eykenen                       
 21710  Uylaru                        
 21711  Haalum                        
 24792  Advanced Training Dummy       
 27355  Rothin the Decaying           
 27461  Bambina                       
 27485  Vengeful Bambina              
 28017  Bloodworm                     
 28659  Artruis the Heartless         
 28712  Basic Loot Pinata             
 28720  First Aid Loot Pinata         
 28781  Battleground Demolisher       
 29441  Lieutenant Julek              
 29442  Lieutenant Kregor             
 31012  Iceskin Sentry                
 31144  Grandmaster's Training Dummy  
 31146  Heroic Training Dummy         
 31324  Iceskin Sentry                
 31744  Cooking Loot Pinata           
 32541  Initiate's Training Dummy     
 32542  Disciple's Training Dummy     
 32543  Veteran's Training Dummy      
 32545  Initiate's Training Dummy     
 32546  Ebon Knight's Training Dummy  
 32547  Highlord's Nemesis Trainer    
 32666  Expert's Training Dummy       
 32667  Master's Training Dummy       
 33229  Melee Target                  
 33243  Ranged Target                 
 33272  Charge Target                 
 33568  Fish                          
 34444  Thrakgar                      
 34445  Liandra Suncaller             
 34447  Caiphus the Stern             
 34459  Erin Misthoof                 
 34465  Velanaa                       
 34466  Anthar Forgemender            
 34469  Melador Valestrider           
 34470  Saamul                        
 34632  Ogre Pinata                   
 34775  Demolisher                    
 34776  Siege Engine                  
 34793  Catapult                      
 34802  Glaive Thrower                
 35069  Siege Engine                  
 35273  Glaive Thrower                
 36954  The Lich King                 
 38857  PattyMacks LK                 
```

Since I'm mostly familiar with TBC, let's take a look at few creatures here. Servant of Razelikh and other servants are initially unkillable, Ambassador Hellmaw and Azaloth are initially banished. Dr. Boom can be aggroed only in melee range, he has 600k HP and can be shooted from 30 yards without taking damage from him.

Dr. Boom: https://www.wowhead.com/npc=21506/azaloth#comments:id=70660:reply=48676
Azaloth: https://www.wowhead.com/npc=21506/azaloth#comments:id=472918
Gordok Spirit: https://www.wowhead.com/npc=11446/gordok-spirit#comments:id=677309

These are initially unkillable:
https://www.wowhead.com/npc=21709/eykenen#comments:id=347145:reply=55897
```text
 21709  Eykenen                       
 21710  Uylaru                        
 21711  Haalum                        
```
All lieutenants too. And skill gain was fixed shortly after players discovered it: https://www.wowhead.com/npc=16494/lieutenant-rukag#comments:id=424479
```text
 16478  Lieutenant Orrin              
 16484  Lieutenant Nevell             
 16490  Lieutenant Lisande            
 16493  Lieutenant Dagel              
 16494  Lieutenant Rukag              
 16495  Lieutenant Beitha             
```

**Branch(es):** both
**TC rev. hash/commit:** b52c89f1bae1

**Comment by offl** [comment]
Ok, checked some 3xx creatures, looks valid but I don't understand why these ToC champions too can't give skill points
```text
 34444  Thrakgar                      
 34445  Liandra Suncaller             
 34447  Caiphus the Stern             
 34459  Erin Misthoof                 
 34465  Velanaa                       
 34466  Anthar Forgemender            
 34469  Melador Valestrider           
 34470  Saamul                        
```

**Comment by illfated** [comment]
Beyond my experience and knowledge. Wish I could help. Hope someone with real interest and know-how will contribute with a useful comment.

**Comment by offl** [comment]
I started to think that flag may be related to health or it makes creature unkillable but the thing is Dr. Boom can be killed but he does not regen his health.
Ambassador Hellmaw for sure can regen health, he is just initially banished and after banish is removed he starts to act like normal mob.

 I guess there's no flag that control health regen at all, unfortunatelly.
```cpp
    CREATURE_DIFFICULTYFLAGS_UNK3 = 0x00000400, // Related to health - it seems similar to CREATURE_DIFFICULTYFLAGS_2_KEEP_HEALTH_POINTS_AT_RESET
```
That flag is applied to tons of creatures and the thing is some of them indeed should not regen health. But at same time some of them should not regen mana. And all of them uses one flag + some of them probably should regen mana and health. So far didn't found if they uses another flag that could potentially control something like that.

Anyway CREATURE_DIFFICULTYFLAGS_UNK3 for sure can be used to check health or mana regen, there are tons of creatures which really should not restore health or mana.

**Comment by offl** [comment]
Ok, Battleground Demolisher uses also CREATURE_DIFFICULTYFLAGS_UNK3 and someone changed its RegenHealth to 0
However Catapult uses only CREATURE_DIFFICULTYFLAGS_2_KEEP_HEALTH_POINTS_AT_RESET and its RegenHealth is too 0
I give up

That flag is applied to really small amount of creatures to be associated with regen, I need to check those vehicles and those ToC champions if they really can't regen health or not
Even if it's related to regen, we need apply our extra flag to more creatures from that list

**Comment by offl** [comment]
Only half of them uses CREATURE_DIFFICULTYFLAGS_UNKILLABLE and only those who really can't be killed, so that flag does not make them invincible.

Again checked those ToC faction champions but with no luck, have no idea why they uses that flag. Since our CreatureDifficulty is from MoP, quite possible that flag was added not in 3xx but later. But why? Players' weapon skill should be already max when they enter ToC. I doubt someone above level 80 will try to raise his skill in ToC.
```text
 34444  Thrakgar                      
 34445  Liandra Suncaller             
 34447  Caiphus the Stern             
 34459  Erin Misthoof                 
 34465  Velanaa                       
 34466  Anthar Forgemender            
 34469  Melador Valestrider           
 34470  Saamul                        
```

@Ovahlord do you wanna check 4xx creatures with that flag?
```text
     54556  Volcano                             
     54344  Highlord's Nemesis Trainer          
     54071  Volcano                             
     52582  Volcano                             
     32862  Jor'kil the Soulripper              
     34521  Bough of Corruption                 
     48304  Training Dummy                      
     36649  Malicion                            
     46647  Training Dummy                      
     37754  Nightmare Mass Prisoner             
     38038  Tiki Target                         
     38306  Zar'jira                            
     44937  Training Dummy                      
     44848  Training Dummy                      
     44820  Training Dummy                      
     44794  Training Dummy                      
     44703  Training Dummy                      
     44614  Training Dummy                      
     44548  Training Dummy                      
     44420  Learn Judgment Credit               
     44419  Judgment Credit                     
     44389  Training Dummy                      
     44175  Spell Practice Credit               
     44171  Training Dummy                      
     39911  Dead Zin'jatar Raider               
     40002  Molten Quicksilver                  
     40002  Molten Quicksilver                  
     40002  Molten Quicksilver                  
     40004  Quicksilver                         
     40004  Quicksilver                         
     40004  Quicksilver                         
     43596  Venture Co. Oil Worker              
     40434  Blazing Trainer                     
     40847  Dead Zin'jatar Raider               
     42674  Hellscream Demolisher Quest Credit  
     42673  Hellscream Demolisher               
```

**Comment by offl** [comment]
Ok, let's check cata creatures

32862  Jor'kil the Soulripper -- uses https://www.wowhead.com/spell=64549/aegis-of-the-shatterspear so it's pretty logically correct to prevent skill gain
34521  Bough of Corruption -- is involved in quest where player has damage reduction aura + powerful healing spell https://www.wowhead.com/quest=14005/the-vengeance-of-elune#videos:id=32506
36649  Malicion -- no idea https://www.youtube.com/watch?v=38NkHijK0Kk
38306  Zar'jira -- 1 mil HP 5 level boss, what else to say
43596  Venture Co. Oil Worker -- no idea, probably they can be shooted from distance  https://youtu.be/1kNEWdz-DoA?t=93
15 dummies

Gonna add that flag to all of them today

If someone wants to check it, check https://www.wowhead.com/npc=32862/jorkil-the-soulripper with low level character

**Comment by xvwyh** [comment]
> Again checked those ToC faction champions but with no luck, have no idea why they uses that flag. Since our CreatureDifficulty is from MoP, quite possible that flag was added not in 3xx but later. But why? Players' weapon skill should be already max when they enter ToC. I doubt someone above level 80 will try to raise his skill in ToC.

Honestly, I think this was done solely for flavor, just to mimic the fact that you can't level weapon skills in PvP combat. ToC champions fight was supposed to look like a PvP fight with the enemy faction, after all.

**Comment by offl** [comment]
Indeed..
Then everything is fine
