### ISSUE TITLE
DB/Creature: Wild Turkey respawn time

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25672]
**Description:**

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32820 respawns in 10min, pretty sure it should be much lower
Maybe someone can check respawn time on retail

**Branch(es):** b52c89f1bae1
**TC rev. hash/commit:** both

**Comment by TQPS** [comment]
Are we even sure that the spawns themselves are correct? I know Tirisfal Glades and Elwynn Forest are the go-to places - but given the quest/daily objectives haven't changed much over the years - I'm seeing a different picture of where turkeys are supposed to spawn in my research.

This is on live:

https://www.wowhead.com/npc=32820/wild-turkey

And I know we aren't using live, however. this is from 2010 and also states Wild Turkeys are in Tirisfal Glades and Elwynn Forest during this event.

https://youtu.be/tnC_kakpLZw?t=14

Also noticed the quest area outside Ironforge says to go to Elwynn Forest for Turkeys but there's already a heap of spawns in that area (under Dun Morogh in your link).

<details>

![image](https://user-images.githubusercontent.com/66294837/100165860-688cb980-2f0f-11eb-8c07-108652996d73.png)

</details>

Something amiss?

**Comment by offl** [comment]
Wowhead's data may be incomplete or completely wrong in case of spawns positions simply because their addon just collects data(including creature's **current** position) when player passes near creature

However I have to admit something is wrong here because I didn't found any turkey here https://youtu.be/N1hyxjavdJc?t=79
And some spawn positions looks like they were not sniffed, usually 'small' values(values with small amount of numbers after point) means creature was not sniffed. However this also may mean positions were taken directly from wowhead(really bad and pretty old practice)
```sql
138573   32820       0       0       0          1          1        0             0       -9975     292.899      36.336         4.86            600               20                0          2        0             1        0           0             0                            0
138574   32820       0       0       0          1          1        0             0    -9853.68     284.862      37.987      1.89787            600               20                0          2        0             1        0           0             0                            0
```

**Comment by dr-j** [comment]
Ye certain areas within these zones seem plastered with turkey’s

**Comment by illfated** [comment]
Good point, I agree, I went to Ruins of Lordaeron in current TC using 5270ff58daf3 2020-11-21 16:33:00 +0100 (3.3.5 branch). I was _almost_ able to shoot enough turkeys _inside the ruins_ to get enough kills for the achievement.

**Comment by offl** [comment]
Spawns were added in https://github.com/TrinityCore/TrinityCore/blob/1d04d5859a59caf286d71f78a18ec4ed05feb7c2/sql/old/3.3.5a/TDB49_to_TDB50_updates/world/2012_11_19_01_world_pilgrims_bounty.sql

> And some spawn positions looks like they were not sniffed, usually 'small' values(values with small amount of numbers after point) means creature was not sniffed. However this also may mean positions were taken directly from wowhead(really bad and pretty old practice)

Blizz uses smooth values like x -50 y 350 to achieve perfect distance between all creatures. So far seen only in SWP (Felmyst's triggers). But those are not moving, because of that you can sniff their default positions. In case of other units \ moving units normally they have 6 digits for x y z o. SQL can cut some of them but usually there will be always something after point
```text
-14298.2     55.3486     1.47578      2.54818
```
Hundreds of them looks like this, this is really bad. As I said this is something you will get after picking position from wowhead
```text
-3645        -720       9.968        4.426
```
Less worse but orientation is still in 4 digits, it's fine if some spawns are with 4 only, but not if hundreds. It is also impossible to achieve so much spawns with 4 digits if you cut parsed data manually to 6 digits without allowing SQL to cut them. SQL usually cuts them to 6 digits
```text
1270.04     982.334      44.642        4.756
```
So far I doubt they were sniffed 9 years ago and I don't know if someone sniffed them for master. Looks like Blizz didn't wanted to spawn all those turkeys again and because of that they didn't changed both zones, so I guess turkeys are still sniffable but the event is already over
I can remove all of them if not spawned in Tirisfal \ Elwynn, just need to check again if they indeed should not be spawned in different zones but I can't remove all without digits after point because it will remove nearly all turkeys
And I didn't yet tried to add zoneId and areaId to check how it looks if sorted by zoneId or AreaId and didn't tried to sort them by number of digits after point

**Comment by CraftedRO** [comment]
Well I had found two evidences for now ([first one](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/269646-all-turkinator-guides-post1744105.html?s=a66360fd84f8024d576232bc140d1a40#post1744105), [second one](https://github.com/Dramacydal/murlocs_434/blob/704fb92d5fcb212fa4e0850a82542af6b20cbc12/sql_300m/world/pilgims_bounty.sql#L92)) that turkeys have respawn time around 15-30 sec so I guess we can wait one month for confirmation (when event occur on retail) but this is my fix for now:

```sql
-- Correct respawn time for Wild Turkey
UPDATE `creature` SET `spawntimesecs` = 25 WHERE `id` = 32820;
```

**Comment by CraftedRO** [comment]
Ok I checked again today on WotLK classic PTR 3.4.3.52237 and seems they actually respawn in the same place after 5 minutes.

```sql
-- Correct respawn time for Wild Turkey
UPDATE `creature` SET `spawntimesecs` = 300 WHERE `id` = 32820;
```
