### ISSUE TITLE
DB/Quest: Flash Bomb Recipe

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25686]
**Description:**

The quest Flash Bomb Recipe from Rigglefuzz should not be available until Pearl Diving has been completed.

<details>

![image](https://user-images.githubusercontent.com/66294837/101127834-7bf7fd00-3652-11eb-8b76-d3930c82668f.png)

</details>

**Expected behaviour:**

The quest Flash Bomb Recipe should only appear when Pearl Diving is completed (and you're an engineer - I believe this portion is met?) as the quest states pearls have been provided.

<details>

![image](https://user-images.githubusercontent.com/66294837/101127957-c11c2f00-3652-11eb-8700-0886794e23dd.png)

</details>

**Steps to reproduce the problem:**

1. Have the engineer skill
2. Make your way to Rigglefuzz (Badlands 42,52) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2817#starts  
3. Engage conversation and accept Flash Bomb Recipe (just requires you to click Complete Quest) 
(this quest should not be available on your first visit.)

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. 36d3a9c 2020-11-28 02:16:07 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by TQPS** [comment]
Thank you

**Comment by illfated** [comment]
@TQPS : Thank you for noticing. Normally, I would have noticed that, but I was too caught up in checking my profession skills, so I missed that bug. Good report.
