### ISSUE TITLE
Core/Scripts: A Mysterious Voice in Ahn'kahet is not scripted

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25683]
**Description:**

Creature A Mysterious Voice (31264) should whisper to random player in instance every 5 - 10 minutes (initial timers are too 5 - 10 minutes)
Texts & creature added in https://github.com/TrinityCore/TrinityCore/commit/5861d665e05f1c7135b0bfc70d1ab0f6b80965f9

**Branch(es):** both
**TC rev. hash/commit:** b52c89f1bae1

**Comment by dr-j** [comment]
Is there a specific spell for this or can this be handled the same way has I handled Eye of The Lich King in POS

**Comment by offl** [comment]
Yes, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Creature+-+Yogg-Saron+Whisper
But they are not shown in my sniff, probably will be shown in another

>Script Effect:
Value: 31911 **broadcast text**
Radius: 50000 yards
>
>Dummy:
Value: 14372 **sound id** https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?sound=14372
Radius: 50000 yards

>ServerToClient: SMSG_PLAY_OBJECT_SOUND (0x0278) Length: 12 ConnIdx: 0 Time: 07/06/2010 17:23:11.000 Number: 638079
Sound Id: 14372
GUID 2: Full: x Type: Player Low: x Name: x
>
>ServerToClient: SMSG_CHAT (0x0096) Length: 83 ConnIdx: 0 Time: 07/06/2010 17:23:12.000 Number: 638111
Type: 15 (MonsterWhisper)
Language: 0 (Universal)
GUID: Full: 0xF130007A203B3098 Type: Creature Entry: 31264 Low: 3879064
Constant time: 0
Name Length: 19
Name: A Mysterious Voice
Receiver GUID: Full: x Type: Player Low: x Name: x
Text Length: 30
Text: You will be alone in the end.
Chat Tag: 0 (None)

**Comment by dr-j** [comment]
~~~sql
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE  `entry`=31264;

DELETE FROM `smart_scripts`  WHERE `entryorguid`=31264;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(31264, 0, 0, 0, 1, 0, 100, 6, 300000, 600000, 300000, 600000, 1, 0, 0, 0, 0, 0, 0, 21, 1000, 0, 0, 0, 0, 0, 0, 'A Mysterious Voice - Out of Combat - Say');


UPDATE `creature_text` SET `Sound`='14372' WHERE  `CreatureID`=31264 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Sound`='14373' WHERE  `CreatureID`=31264 AND `GroupID`=0 AND `ID`=1;
UPDATE `creature_text` SET `Sound`='14374' WHERE  `CreatureID`=31264 AND `GroupID`=0 AND `ID`=2;
UPDATE `creature_text` SET `Sound`='14375' WHERE  `CreatureID`=31264 AND `GroupID`=0 AND `ID`=3;

**Comment by offl** [comment]
<details>

ServerToClient: SMSG_SPELL_START (0x0131) Length: 33 ConnIdx: 0 Time: 07/05/2010 16:33:47.000 Number: 702586
Caster GUID: Full: 0xF130007A202FCAF9 Type: Creature Entry: 31264 Low: 3132153
Caster Unit GUID: Full: 0xF130007A202FCAF9 Type: Creature Entry: 31264 Low: 3132153
Cast Count: 0
Spell ID: 58908 (58908)
Cast Flags: 10 (HasTrajectory, Unknown3)
Time: 0
Target Flags: 0 (Self)

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 57 ConnIdx: 0 Time: 07/05/2010 16:33:47.000 Number: 702587
Caster GUID: Full: 0xF130007A202FCAF9 Type: Creature Entry: 31264 Low: 3132153
Caster Unit GUID: Full: 0xF130007A202FCAF9 Type: Creature Entry: 31264 Low: 3132153
Cast Count: 0
Spell ID: 58908 (58908)
Cast Flags: 16648 (Unknown3, Unknown7, Unknown12)
Time: 2742342120
Hit Count: 1
[0] Hit GUID: Full: x Type: Player Low: x Name: x
Miss Count: 0
Target Flags: 34 (Unit, SourceLocation)
Target GUID: 0x0
Source Transport GUID: 0x0
Source Position: X: 519.5499 Y: -447.87613 Z: 26.439379

ServerToClient: SMSG_PLAY_OBJECT_SOUND (0x0278) Length: 12 ConnIdx: 0 Time: 07/05/2010 16:33:47.000 Number: 702589
Sound Id: 14373
GUID 2: Full: x Type: Player Low: x Name: x

ServerToClient: SMSG_CHAT (0x0096) Length: 77 ConnIdx: 0 Time: 07/05/2010 16:33:47.000 Number: 702593
Type: 15 (MonsterWhisper)
Language: 0 (Universal)
GUID: Full: 0xF130007A202FCAF9 Type: Creature Entry: 31264 Low: 3132153
Constant time: 0
Name Length: 19
Name: A Mysterious Voice
Receiver GUID: Full: x Type: Player Low: x Name: x
Text Length: 24
Text: Trust is your weakness.
Chat Tag: 0 (None)

</details>
