### ISSUE TITLE
DB/Loot: Tanaris - Southsea Npc's 

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#25689]
**Description:**

1) Currently Southsea Swashbuckler has a 100% chance to drop Captain's Key.
All the other Southsea npc's currently have a chance of 0.02% to drop this Captain's Key.

2) Dropchance of Pirate's Footlocker currently is a bit to low (around 5-6%).

https://classic.wowhead.com/npc=7858/southsea-swashbuckler
https://classic.wowhead.com/item=9249/captains-key
https://classic.wowhead.com/item=9276/pirates-footlocker

**Expected behaviour:**
1) Captain's Key should have a very low drop chance or should only be part of Pirate's Footlocker loot table.
2) Pirate's Footlocker should have a 8% drop chance from all Southsea npc's.

**Suggested fix:**
-- Captain's Key
UPDATE `creature_loot_template` SET `Chance`=0.02 WHERE `Entry`=7858 AND `Item`=9249;

-- Pirate's Footlocker
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7855 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7856 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7857 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7858 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=15685 AND `Item`=9276;

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
d665c68

**Operating system:** 
Win10

**Comment by illfated** [comment]
I agree that the drop rate for the key seems to be way more than it needs to be, to the point where it gets mildly annoying to choose whether to leave the extra keys in the unlooted dead bodies, or delete the existing key to loot the bodies for everything. (I know, that part is merely a player choice, but mildly annoying anyway.)

Admittedly, it seems too much to have more than 50% drop rate for that key when the key item is unique.

**Comment by illfated** [comment]
BTW, MarkDown tip for your SQL suggestion: use 3 backticks + the keyword 'sql' ( **```sql** ) on a blank line before the SQL code, then add only 3 backticks on a blank line after the code, to show the code in a contiguous code block (sql for syntax highlighting) like this:
```sql
-- Captain's Key
UPDATE `creature_loot_template` SET `Chance`=0.02 WHERE `Entry`=7858 AND `Item`=9249;

-- Pirate's Footlocker
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7855 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7856 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7857 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=7858 AND `Item`=9276;
UPDATE `creature_loot_template` SET `Chance`=8 WHERE `Entry`=15685 AND `Item`=9276;
```

**Comment by offl** [comment]
Captain's Key drops only from Pirate's Footlocker, chance of Pirate's Footlocker looks more like 10 than 8

**Comment by schell244** [comment]
With 8% I actually ment the chance of item Pirate's Footlocker dropping from Southsea Npc's. This chance is currently set to 5-6% . Thanks for applying fix so fast!

**Comment by illfated** [comment]
@offl : Thank you for this quick resolve and practical update solution.
