### ISSUE TITLE
Herbalism spawn in mid-air - Badlands

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25681]
**Description:**

There's a herb spawn in mid-air in the Badlands. Example shows Goldthorn

<details>

![image](https://user-images.githubusercontent.com/66294837/100554831-a7de5000-32eb-11eb-8988-56b62acf3e0c.png)

</details>

**Expected behaviour:**

Herb should be located closer to the ground.

**Steps to reproduce the problem:**

Note: Herbalism required 
1. Go to Badlands approximately 44,49 
2. Activate "Find Herbs"
3. Herb should be in the air
4. Don't jump for it - you wont make it

Note: Due to the nature of these types of spawns they aren't static, so appearance wont be consistent.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 36d3a9c21e56 2020-11-28 02:16:07 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**

Windows 7 Ultimate x64 SP1

Edit: Rebuilt core to satisfy bot

**Comment by TQPS** [comment]
Build includes Trickerer's Bots and all updates to 36d3a9c21e56f7c75835a06df3a0fd99f49c621f

**Comment by illfated** [comment]
TrinityCore rev. b2fd442f64c5 2020-11-26 03:37:24 +0200 (3.3.5 branch) (Win64, Release, Static)

Looks like a random spawn height out of the existing spawn point. I just went to 44 49 and could only find one [Goldthorn](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=2046) nearby, at 44.3,50.7 -- which was at ground level.

<details>
<summary>Goldthorn in Badlands, 44.3,50.7</summary>

![WoWScrnShot_113020_012109](https://user-images.githubusercontent.com/38162891/100557597-86a93f80-32aa-11eb-8c71-ca507707433f.jpg)


</details>

**Comment by offl** [comment]
Well, tons of objects were taken from wowhead
Turned out sometimes (or always, have no idea) they are also duplicated
Whoever did it probably spent way much more time to fix z-position than if he just sniffed all of them, if it wasn't done manually

**Comment by TQPS** [comment]
Thank you very much - that's fixed it.

Logged in and it's on the ground - next to another (possible duplicate?) - but it's no longer in the air.

<details>

![image](https://user-images.githubusercontent.com/66294837/100559544-2b596a80-3307-11eb-9654-16487409170d.png)

</details>

**Comment by offl** [comment]
They're pooled so probably can spawn near to each other
Not sure if they can spawn inside each other, probably yes

**Comment by illfated** [comment]
Fair point. I never know if there should only be 1 spawn at a node or possible double spawns. I can only assume that sniff sources could give partial answers to that question.
