### ISSUE TITLE
Core/Startup: Outdated configuration in worldserver.conf.dist

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25697]
**Description:**
After updating the repository to version 9.0.2, the following information appears in the server.log file:

StartDemonHunterPlayerLevel (98) must be in range 1..MaxPlayerLevel(60). Set to 60.
RecruitAFriend.MaxLevel (85) must be in the range 0..MaxLevel(60). Set to 85.

And since long before the update to version 9.0.2 this is appearing too:

Missing name Guild.SaveInterval in config file D:/Server/worldserver.conf, add "Guild.SaveInterval = 15" to this file

Source of information: [Shadowlands content update notes](https://worldofwarcraft.com/es-es/news/23529209/notas-de-la-actualizaci%C3%B3n-de-contenido-de-shadowlands)

**Steps to reproduce the problem:**

1. Update from TrinityCore branch repository: master  
2. Build the repository.
3. Run the worldserver.exe file

**Branch(es):**  master

TC rev. hash/commit:
364f6ee

Operating system:  Edition: Windows 10 Pro version 20H2, Version OS: 19042.662

**Comment by shdr212** [comment]
I noticed it too but it actually got fixed recently: #25709 
Regardless of the title, it also fixed the `RecruitAFriend.MaxLevel` field.

Guild.SaveInterval is still a valid issue.
