### ISSUE TITLE
Crash whit fews of class and races using [MASTER]

### ISSUE THREAD

**Issue by FCondeNR** [TrinityCore/TrinityCore#25704]
![image](https://user-images.githubusercontent.com/67517462/101917235-4dd16a80-3bc8-11eb-961a-7ce0a1d61db7.png)
[2020-12-11_15.04.48_Crash_-_8856.txt](https://github.com/TrinityCore/TrinityCore/files/5679794/2020-12-11_15.04.48_Crash_-_8856.txt)

All humans class crash excepting monk and dk, but for example orcs hunters working fine , waiting u replly :) I added the crash log
[2020-12-11_15.04.48_Crash_-_8856.txt](https://github.com/TrinityCore/TrinityCore/files/5679805/2020-12-11_15.04.48_Crash_-_8856.txt)

**Comment by MaxtorCoder** [comment]
Please follow the standard issue template...

**Comment by Aokromes** [comment]
there is no "last commit" from all we can say you very likely you can be using a commit before a crash was fixed.

**Comment by FCondeNR** [comment]
> there is no "last commit" from all we can say you very likely you can be using a commit before a crash was fixed.

I means using master branch sorry, what info u need more ??

**Comment by illfated** [comment]
Please provide your core revision hash. TC recently had an update regarding class crashing the game client: https://github.com/TrinityCore/TrinityCore/commit/a50f671afd0c17b768aa1dd73d3d63476ff5523c

I am fairly sure that commit will solve your issue.

**Comment by SpikeZ-WoW** [comment]
I can create a Human without any problems mage, pala and so on. Just update your Core.

**Comment by FCondeNR** [comment]
![TrinityCore - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/67517462/101921113-e833ad00-3bcc-11eb-843c-f965853a7f76.jpg)
 Im aparatlty using same version, I need extract, or just whit put the .exe if fixed??

**Comment by MaxtorCoder** [comment]
I am honestly pretty sure this is a different crash tho :)

**Comment by illfated** [comment]
OK, fair enough. It sure takes more commenting and asking to get the information, which could have been present in the main ticket comment, though.

**Comment by MaxtorCoder** [comment]
> 
> 
> OK, fair enough. It sure takes more commenting and asking to get the information, which could have been present in the main ticket comment, though.

Agreed, next time include more info in the main ticket.. @FCondeNR

**Comment by FCondeNR** [comment]
oki, sorry, I fixed it nvm I close that it. ty :)
