### ISSUE TITLE
Shadowlands 9.0.2(36839) Races locked

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#25708]
VIDEO:   https://youtu.be/ba1jd3B836M

For some reason I cannot enter the world. All races are locked. Is that how it should be?

**Comment by VincentVanclef** [comment]
@rem999 yes thats the game experience they are aiming for

**Comment by MaxtorCoder** [comment]
Follow issue template next time please.

**Comment by Shauren** [comment]
Works fine for me

**Comment by rem999** [comment]
Possibly client error. The same thing happens with Arctium. I'll try to update the client.

**Comment by ReyDonovan** [comment]
@Shauren please close this issues, otherwise it's like a joke

**Comment by acidmanifesto** [comment]
99.9% sure it is a joke. 😆

**Comment by Shauren** [comment]
![WoWScrnShot_121220_174833](https://user-images.githubusercontent.com/297439/101989663-4ed6ca80-3ca2-11eb-9068-9266f85e577c.jpg)
