### ISSUE TITLE
Core/Spells: AuraEffect::HandleProcTriggerSpellAuraProc wrong error

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25707]
**Description:**
When casting any spell that deals damage to a target, throw this error on the console:

```
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 76613 proc, because the spell does not have an entry in Spell.dbc.
```

**Steps to reproduce the problem:**

1. Create a Mage class player
2. levelup 9
3. Choose the Frost Specialization
3. Cast any of the following spells at a target: Frostbolt, Fire Blast, Ice Lance, Blizzard.

**Branch(es):** master

**Operating system:** 
Edition: Windows 10 Pro version 20H2, Version OS: 19042.662

**Comment by matanshukry** [comment]
Can close - doesn't seem to be relevnt anymore.

The log isn't happening for any of the spells.
All spells except Blizzard also work correctly.
