### ISSUE TITLE
Core: No information when the Adventure Guide menu opens.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25706]
**Description:**
When the Adventure Guide menu is opened in the "Suggested Content" tab, nothing appears. Information regarding Shadowlands does not appear in the Raids and Dungeons tab.

**Steps to reproduce the problem:**

1. Create any player  
2. .levelup 9

**Branch(es):**  master 

**TC rev. hash/commit:** 
364f6ee

**Operating system:** 
Edition: Windows 10 Pro version 20H2, Version OS: 19042.662

**Comment by TheGhostGroup** [comment]
It's not scripted. Has been like that since legion i think. I have the same problem with my legion fork.

**Comment by MaxtorCoder** [comment]
> It's not scripted. Has been like that since legion i think. I have the same problem with my legion fork.

It doesn't even have to be scripted tho lol, it should display info regardless.

**Comment by osleyder85** [comment]
Sure, that should work.

**Comment by Ovahlord** [comment]
missing hotfix data and tact keys probably

**Comment by MaxtorCoder** [comment]
> missing hotfix data and tact keys probably

Possible

**Comment by offl** [comment]
#18869 same or still valid \ not valid anymore?

**Comment by illfated** [comment]
Seems like both are valid, which makes this issue a duplicate (not sure how it is judged by real coders), it is still present (although based on different client versions). Rushor seemed to have an interesting point, the Adventure Guide is still a missing feature, might be useful to have a milestone for that (I think).

**Comment by matanshukry** [comment]
Can be closed, fixed by #26000
