### ISSUE TITLE
Client Crash while login.

### ISSUE THREAD

**Issue by SpikeZ-WoW** [TrinityCore/TrinityCore#25701]
**Description:**

CHANGEME Description of the problem or issue here.
Game gets an WoW crash if you log in with some Race/Class combinations like Troll shaman.

Crashlog: https://gist.github.com/SpikeZ-WoW/a6eab455e17c0215a46358d2a8e023aa

**Expected behaviour:**

There should be no crash while you login no matter which Class and Race it is

**Steps to reproduce the problem:**

1. Log into the game
2. create a character (example Troll shaman)
3. log into world

**Branch(es):**

CHANGEME [x] master

**TC rev. hash/commit:**  bd0a0110322151eb0efdc8faabb7f9dc5ce85e18

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Debian10

**Comment by osleyder85** [comment]
I just tested all classes with the Night Elf Race and this was the result:

Night Elf - Mage  - Male     Not Work
Night Elf - Mage  - Female   Not Work
Night Elf - Druid  - Male     Works
Night Elf - Druid  - Female   Works
Night Elf - Hunter  - Male     Not Work
Night Elf - Hunter  - Female   Not Work
Night Elf - Warrior  - Male     Not Work
Night Elf - Warrior  - Female   Not Work
Night Elf - Rogue  - Male     Not Work
Night Elf - Rogue  - Female   Not Work
Night Elf - Priest  	 - Male     Not Work
Night Elf - Priest  	 - Female   Not Work
Night Elf - Monk    	 - Male     Not Work
Night Elf - Monk    	 - Female   Not Work
Night Elf - Demon Hunter - Male     Not Work
Night Elf - Demon Hunter - Female   Not Work
Night Elf - Death Knight - Male     Work
Night Elf - Death Knight - Female   Not Work

**Comment by Shauren** [comment]
Its the class, not the race/class combo
