### ISSUE TITLE
Core: The city guards do not show any information.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25712]
**Description:**
When selecting a city guard, it does not show the information regarding points of interest in the city.

**Steps to reproduce the problem:**

1. Create a horde player 
2. t orgrimmar
3. Select a city guard

**Branch(es):** master

**TC rev. hash/commit:** 
 364f6ee

**Operating system:** 
Edition: Windows 10 Pro version 20H2, Version OS: 19042.662

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17414#issuecomment-287335041, probably something was broken in general
