### ISSUE TITLE
Core / Quest:  I don't get experience for completed tasks

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25719]
Description:
Completed 10 quests for draenei and did not get experience
 
Steps to reproduce the problem:

Create any player.
Go find the first quest in the area.

Branch(es): master
TrinityCore rev. 5f3a2d2abf29 2020-12-11 22:19:19 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

Operating system:
Win 10

**Comment by MaxtorCoder** [comment]
Please update the Issue to have the commit hash.

**Comment by illfated** [comment]
Seems to be done as requested.

**Comment by MaxtorCoder** [comment]
Please pull latest changes, you are 5/6 commits behind.

**Comment by illfated** [comment]
I agree. Even if the 6 new commits do not have quest specific changes, 4 of them contain some core changes which may positively affect the player character packet communication between game client & server.

**Comment by Faq** [comment]
@NiganNi update core, check again and leave feedback.

**Comment by Shauren** [comment]
Updating core won't help, new quest_template with filled ContentTuningId are required

**Comment by illfated** [comment]
Oh. I see. Right. Thanks a lot for confirming.

**Comment by NiganNi** [comment]
Updated core, but nothing changed. Where can I get data for ContentTuningId?

**Comment by illfated** [comment]
Oh... you need to fill all the quests with a new data column... and maybe from sniffs?

**Comment by MaxtorCoder** [comment]
> Updated core, but nothing changed. Where can I get data for ContentTuningId?

You sniff it with a sniffer. There's no public one, so yeah.

**Comment by Shauren** [comment]
Now fixed for a huge chunk of quests
