### ISSUE TITLE
Core: Game crash after you revive sometimes if you reboot the server the server too

### ISSUE THREAD

**Issue by FCondeNR** [TrinityCore/TrinityCore#25714]
**Description:**
I experimented that time after of die, when you die, and resurrect appear a box blue and white seems like the skeleton model isnt find, all seems correct but a fews minutes later the client crash, and you cannot reconnect, sometimes until the server crash.  you need delete the auth db and char db and and import the structures, or make for the server working again.

it was tested on 2 differents enviorements and 2 diferents servers and one fresh updated

.

**Expected behaviour:**

Spawn the skeleton model, and not crash!

**Steps to reproduce the problem:**

1. make a character human or whatever race
2. die and resurrect
3. close the client and back to open.
4. Login and select your character, or make one
5. Crash on loading screen
**Branch(es):**

master

**TC rev. hash/commit:** 
TrinityCore rev. 015666b0442a 2020-12-13 10:49:21 +0100 (master branch) (Win64, Release, Static) (bnetserver)

Windows 10 server and client

![World of Warcraft_25](https://user-images.githubusercontent.com/67517462/102011308-982b2680-3d43-11eb-90ad-80051ada97cf.jpg)
![eskeletont](https://user-images.githubusercontent.com/67517462/102011372-e0e2df80-3d43-11eb-8491-5738c9a083d8.jpg)

[2020-12-13 13.01.54 Crash - 10000.txt](https://github.com/TrinityCore/TrinityCore/files/5684540/2020-12-13.13.01.54.Crash.-.10000.txt)
![World of Warcraft_27](https://user-images.githubusercontent.com/67517462/102011984-0c67c900-3d48-11eb-9374-4fed331ba387.jpg)

![82 223 97 22 - Conexión a Escritorio remoto](https://user-images.githubusercontent.com/67517462/102011712-5c459080-3d46-11eb-9b01-7bb7ebbe893e.jpg)

**Comment by illfated** [comment]
(please note, I myself won't be able to test this, since I don't run the master branch nor the 9.x game client)

Forgive me for being slow & dumb here, but I started reading your steps to reproduce and saw "wait 5 min max".
- is this minimum _and_ maximum 5, or is this only "maximum 5 minutes"?
- what happens if you wait more than 5 minutes?
- do you have to wait any time at all?

(This is all just out of curiosity. You can choose not to answer, if you find it a waste of time.)

**Comment by FCondeNR** [comment]
I will to edit that, it more faster if you close the client and try to reconnect the game crashed, until if you delete the character and make one you will crash again in the loading screen

**Comment by illfated** [comment]
Not sure, since I only use 3.3.5, but could this be related in any way to the suggested changes in PR #25709 (Core/Config: Fixed StartPlayLevels of DK, DH & RAF) ?

**Comment by FCondeNR** [comment]
I used before the 8.3.7 and on BFA that part was working fine, but ty the link about how fix de dk and dh level 👍

**Comment by osleyder85** [comment]
This problem has been occurring since the repo was updated with this commit 9819ee1
