### ISSUE TITLE
[Crash] freezeDetector !!

### ISSUE THREAD

**Issue by Shadofiend** [TrinityCore/TrinityCore#25727]
Description:
in FreezeDetector::Handler (freezeDetectorRef=..., error=...) at /home/TrinityCore/src/server/worldserver/Main.cpp:480

Crash log:
https://gist.github.com/Shadofiend/f337288ec37e6f86c7909ef276a7fde0

Branch(es): 3.3.5

TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commits/3.3.5

Operating system: ubuntu

**Comment by illfated** [comment]
(modified link from main comment) -- full backtrace Debug log (raw):

- https://gist.githubusercontent.com/Shadofiend/f337288ec37e6f86c7909ef276a7fde0/raw/5568714f6a21f4d15dae0e140d5462637bd2380d/crashlog

**Comment by illfated** [comment]
@Shadofiend : Any chance you could post some steps to reproduce the crash, at least tentatively?

**Comment by Shadofiend** [comment]
yes, It crashes several times a day !

**Comment by illfated** [comment]
Uh. I mean, what can we others do to try to find the problem you have got? What do you do **specifically** to make it crash?

**Comment by Shadofiend** [comment]
Nothing ! server have 0 online!

**Comment by illfated** [comment]
Oh well. Not much I can do to help. Please wait for someone to read the debug log for clues.

By the way: It would help us more if you could tell us your actual core revision hash.

**Comment by Shadofiend** [comment]
https://gist.github.com/Shadofiend/736d593c960cc3ff5aa197bd7a72275c

**Comment by Jildor** [comment]
What MaxCoreStuckTime value do you have in worldserver.conf?

**Comment by Shadofiend** [comment]
MaxCoreStuckTime = 60

**Comment by Shadofiend** [comment]
@Jildor

What is this crash for?

**Comment by Jildor** [comment]
The default value of 60 seconds seems sufficient to prevent the freeze detector crash worldserver, but you could try increasing it to 300 to see if the problem continues or is due to possible lag spikes in the machine.

**Comment by Faq** [comment]
btw you didnt post correct revision hash

**Comment by illfated** [comment]
Good point. It would be helpful to know the exact core revision hash for your build. Makes it easier to correlate between the crash log and the source.

**Comment by Shadofiend** [comment]
MaxCoreStuckTime = 300


https://gist.github.com/Shadofiend/998d0c3696bb1ad201b1bd7328feacf0
