### ISSUE TITLE
DH can't activate any specializations

### ISSUE THREAD

**Issue by Pain538** [TrinityCore/TrinityCore#25726]
**Description:**

When you try activate specialization on demon hunter - nothing happening

**Expected behaviour:**

Should activate choosed specialization

**Steps to reproduce the problem:**

1. Create a demon hunter  
2. Open specializations and talents window
3. Try to activate any specialization

**Branch(es):**

mater

**TC rev. hash/commit:** 

TrinityCore rev. 93f2aff 2020-12-13 18:38:31 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Win 10

**Comment by Shauren** [comment]
DHs learn switching specializations from a quest, if you complete that quest then it will work

**Comment by Pain538** [comment]
> DHs learn switching specializations from a quest, if you complete that quest then it will work

Oh, lol, ty, close please.
