### ISSUE TITLE
Heroic leap

### ISSUE THREAD

**Issue by Pain538** [TrinityCore/TrinityCore#25722]
**Description:**

When you use this spell, the player does not jump into the specified area. Before the update to the new patch (9.0.x), this spell worked.

**Expected behaviour:**

The player must jump to the specified area.

**Steps to reproduce the problem:**

1. Create a warrior 
2. Use "Heroic Leap" (www.wowhead.com/spell=6544)

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. 93f2affbf2f7 2020-12-13 18:38:31 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) 

**Operating system:** Win 10

**Comment by offl** [comment]
> Before the update to the new patch (9.0.x), this spell worked.

Are you sure? https://github.com/TrinityCore/TrinityCore/issues/20000

**Comment by Pain538** [comment]
> > Before the update to the new patch (9.0.x), this spell worked.
> 
> Are you sure? #20000 #24785

Thank you! Already thought the problem is on different. Then you can close, duplicate.

**Comment by offl** [comment]
It no longer causes crash?

**Comment by Pain538** [comment]
> It no longer causes crash?

Not, you press and nothing happens, only start cd.
