### ISSUE TITLE
9.0.2 - Unable to Create Worgen Race Character

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#25731]
**Description:**

When creating a Worgen race character, a character creation error occurs. The console displays the following message: "Player::Create: Possible hacking-attempt: Account 1 tried creating a character named 'Test' with invalid appearance attributes - refusing to do so".

**Expected behaviour:**

Worgen race character should be created without problems.

**Steps to reproduce the problem:**

1. Start the server on the current version 8742bf3
2. Try to create a Worgen character
3. Get Error

**Branch(es):**

master

**TC rev. hash/commit:** 

8742bf3

**Operating system:** OC Windows 10

**Comment by osleyder85** [comment]
You already tried with another player

**Comment by DintyGadget** [comment]
> Вы уже пробовали с другим игроком

I checked this on 2 created accounts, the problem was the same, the rest of the races are created without problems. I suspect the mistake is that worgen are now customizable separately from the human model.

**Comment by osleyder85** [comment]
I just created a Blood Elf and the client closes without giving an error. And the server is still working fine.

**Comment by DintyGadget** [comment]
> I just created a Blood Elf and the client closes without giving an error. And the server is still working fine.

The problem occurs on the server side, not the client. The server cannot process the appearance attributes of the Worgen race

**Comment by Daribon** [comment]
Can confirm, getting the same error when attempting to create a worgen character. Neither male or female works.
> Player::Create: Possible hacking-attempt: Account 1 tried creating a character named 'Whitby' with invalid appearance attributes - refusing to do so
