### ISSUE TITLE
Server/Crash: Client closes after selecting the player and trying to enter the world.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25735]
**Description:**
Every time I try to enter the world, after finishing loading the bar, the client closes and does not give me error information.
However the server is putting this error:

```
CMSG_DB_QUERY_BULK: [Player: Pala Player-1-00000003, Account: 1] requested unsupported unknown hotfix type: 3386291891
```

**Steps to reproduce the problem:**

1. Create any player.
2. Enter the world.
3. Wait for the bar to load. The client is closed.

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 8742bf353df6 2020-12-15 19:38:08 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)
Using SSL version: OpenSSL 1.1.1a  20 Nov 2018 (library: OpenSSL 1.1.1a  20 Nov 2018)
Using Boost version: 1.72.0
Using World DB: TDB 837.20101
Using enUS DBC Locale

**Operating system:**  Windows 10 Pro version 20H2, 19042.662

**Comment by Daribon** [comment]
Can confirm, happening to me as well.

**Comment by DintyGadget** [comment]
I got the same problem, but after a client crash, the server issues this: 

CMSG_DB_QUERY_BULK: [Player: Tyrius Player-1-0000000E, Account: 1] requested unsupported unknown hotfix type: 3386291891
Player :: SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Tyrius' (Player-1-0000000E), possible cheater
Player :: SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Tyrius' (Player-1-0000000E), possible cheater
Player :: SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Tyrius' (Player-1-0000000E), possible cheater

**Comment by Fragrus** [comment]
Confirm, log:
Received not handled opcode [CMSG_GET_LANDING_PAGE_SHIPMENTS 0x330C (13068)] from [Player: Fragan Player-1-00000002, Account: 1]
CMSG_DB_QUERY_BULK: [Player: Fragan Player-1-00000002, Account: 1] requested unsupported unknown hotfix type: 3386291891
Player::SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Fragan' (Player-1-00000002), possible cheater

**Comment by DintyGadget** [comment]
This problem is not present on version 9.0.2.36839

But when I update the game to version 9.0.2 36949 the game crashes when loading completes

**Comment by MaxtorCoder** [comment]
This issue is related to `Creature.db2` (hotfix type: 3386291891)

**Comment by ScarVite** [comment]
Happens to me aswell.
I am getting `CMSG_DB_QUERY_BULK: [Player: Test Player-1-00000002, Account: 1] requested unsupported unknown hotfix type: 3386291891`

**Comment by illfated** [comment]
Looks like the source needs a packet handling update.

**Comment by MaxtorCoder** [comment]
> 
> 
> Looks like the source needs a packet handling update.

No, read what I said above. Something is wrong with `Creature.db2` so it does not get loaded. It should automatically add the storageHash to the storage and then be retrieved.

**Comment by Shauren** [comment]
We don't load Creature.db2 at all, this is fine

**Comment by WoWCreador** [comment]
Can confirm, happening to me as well, game **version 9.0.2 36949**

Any solution?

**Comment by Shauren** [comment]
Don't post server logs when the client crashes, they are meaningless. Post the client crash log file

**Comment by osleyder85** [comment]
@Shauren the problem is that the client does not generate error.

**Comment by illfated** [comment]
To those of you who experience the game client crashes:
Please go through the normal troubleshooting steps of cleaning out the game client cache, rebuild a clean DB, reinstall (or verify the completeness of the game client) and so on, to see if that helps.

**Comment by osleyder85** [comment]
After finishing loading the bar to enter the world, the client simply closes.

**Comment by MaxtorCoder** [comment]
> 
> 
> After finishing loading the bar to enter the world, the client simply closes.

It does not "simply" close, it either creates a crashlog or it disconnects.

**Comment by osleyder85** [comment]
Nothing, the client closes, and does not generate any information about the error.

**Comment by WoWCreador** [comment]
<img width="285" alt="wow log" src="https://user-images.githubusercontent.com/66101227/102401113-cbbeb880-3fb0-11eb-99d4-4f460ede8c5a.PNG">
which one?

**Comment by MaxtorCoder** [comment]
> 
> 
> > Don't post server logs when the client crashes, they are meaningless. Post the client crash log file
> > I cannot reproduce it myself with my test characters and given steps to reproduce are not detailed enough
> 
> <img alt="wow log" width="285" src="https://user-images.githubusercontent.com/66101227/102401113-cbbeb880-3fb0-11eb-99d4-4f460ede8c5a.PNG">
> which one?

Wrong folder...

**Comment by Shauren** [comment]
Not in `Logs`, in `Errors`

**Comment by osleyder85** [comment]
Come something here. Please know what they are talking about.
![fd](https://user-images.githubusercontent.com/15787347/102401578-8fd82300-3fb1-11eb-829a-fbdc4d5d3244.png)

**Comment by WoWCreador** [comment]
<img width="446" alt="wow error" src="https://user-images.githubusercontent.com/66101227/102401638-a9796a80-3fb1-11eb-9beb-ff11395371a5.PNG">
I don't see any files or folders that say error.

**Comment by osleyder85** [comment]
How is it possible that you do not close the client with this repository. It has to be that you have another repository, another nucleus, I don't know. It's illogical. Please check.

**Comment by ScarVite** [comment]
Since you want a more detailed description, here is what happened on my end.

One of my players couldn't connect because he has the newest version (36949), i take a look at the repro and saw that you already made an update for that. after pulling in the trinity folder and restarting the world& authserver, the update got applied, but after connecting to the authserver, selecting a char and trying to load that char, the client crashes.
When i "downgrade" the buildversion for my realm to 36839 we can connect with an client on version 36839. 

I also just checked the Error dir and it's completely empty. also i just checked all the logs and the contain nothing useful, except Voice.log where it states "Transport disconnected.  Error [7], Reason [connection disconnected unexpectedly]"

Uploaded a [Youtube Video](https://youtu.be/3f0xEIc6qyk) of the sudden crash.

Hope this helps

**Comment by WoWCreador** [comment]
> Since you want a more detailed description, here is what happened on my end.
> 
> One of my players couldn't connect because he has the newest version (36949), i took a look at the repro and saw that you already made an update for that. After pulling in the trinity folder and restarting the world& authserver, the update got applied, but after connecting to the authserver, selecting a char and trying to load that char, the client crashes.
> When i "downgrade" the buildversion for my realm to 36839 we can connect with an client on version 36839 successfully and play the game.
> 
> I also just checked the Error dir and it's completely empty. also i just checked all the logs and the contain nothing useful, except Voice.log where it states "Transport disconnected. Error [7], Reason [connection disconnected unexpectedly]"
> 
> Uploaded a [Youtube Video](https://youtu.be/3f0xEIc6qyk) of the sudden crash.
> 
> Hope this helps

Thanks for your feedback. Basically the core for now only supports the wow 36839 version

Can you tell me how to "downgrade" the wow client?

**Comment by ScarVite** [comment]
> Can you tell me how to "downgrade" the wow client?

Downgrading the Client is as far as i know impossible, we had some luck, another one of our players still had 36839 installed.

But for the server, its possible, but it's a bit of manual db work.

Open your DB Tool (I use DBeaver, but can Recommend HeidiSql) go into your auth db and open the table realmlist. On the FIled gamebuild change whatever value there is to 36839 and commit/save the changes. Restart the authserver and you are good to go.

**Comment by Fragrus** [comment]
Could you uploaded Wow.exe version 36839 to any file hosting? I will be very grateful

**Comment by MaxtorCoder** [comment]
> Could you uploaded Wow.exe version 36839 to any file hosting? I will be very grateful

Use https://wow.tools/

**Comment by Fragrus** [comment]
> 
> 
> > Could you uploaded Wow.exe version 36839 to any file hosting? I will be very grateful
> 
> Use https://wow.tools/

I don't see that can download a specific version of Wow.exe from there

**Comment by MaxtorCoder** [comment]
> > 
> > 
> > > Could you uploaded Wow.exe version 36839 to any file hosting? I will be very grateful
> > 
> > Use https://wow.tools/
> 
> I don't see that can download a specific version of Wow.exe from there

Go to Builds page, select `Details` of build and then Install List. Download the WoW.exe

**Comment by WoWCreador** [comment]
> > > Could you uploaded Wow.exe version 36839 to any file hosting? I will be very grateful
> > 
> > 
> > Use https://wow.tools/
> 
> I don't see that can download a specific version of Wow.exe from there

Here
https://wow.tools/builds/extract.php?build=7869e3460f47a6ad705b2cf4be56b81a

This solution work for my.
@ScarVite Open your DB Tool (I use DBeaver, but can Recommend HeidiSql) go into your auth db and open the table realmlist. On the FIled gamebuild change whatever value there is to 36839 and commit/save the changes. Restart the authserver and you are good to go.

@MaxtorCoder Download Wow.exe version 36839 https://wow.tools/builds/extract.php?build=7869e3460f47a6ad705b2cf4be56b81a

<img width="960" alt="wow server" src="https://user-images.githubusercontent.com/66101227/102409550-3fff5900-3fbd-11eb-9215-09b59e43b648.png">

**Comment by osleyder85** [comment]
The server is sending me this information in server.log:

```
Received not handled opcode [CMSG_GET_LANDING_PAGE_SHIPMENTS 0x330C (13068)] from [Player: Magic Player-1-00000001, Account: 1]
CMSG_DB_QUERY_BULK: [Player: Magic Player-1-00000001, Account: 1] requested unsupported unknown hotfix type: 3386291891
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-530-0-6368-00000000F6 Entry: 6368
Player::SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Magic' (Player-1-00000001), possible cheater
Player::SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Magic' (Player-1-00000001), possible cheater
Player::SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Magic' (Player-1-00000001), possible cheater
Player::SendTimeSync: Did not receive CMSG_TIME_SYNC_RESP for over 30 seconds from 'Magic' (Player-1-00000001), possible cheater
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-530-0-15274-000000002F Entry: 15274
```

**Comment by Shauren** [comment]
I do have a way to reproduce it now

**Comment by Aokromes** [comment]
3rd party bug.

**Comment by ScarVite** [comment]
> 
> 
> 3rd party bug.

im sorry, but in what way?

**Comment by MaxtorCoder** [comment]
> 
> 
> > 3rd party bug.
> 
> im sorry, but in what way?

Fabian made a small mistake with the launcher, other words: 3rd party bug.

**Comment by ScarVite** [comment]
> 
> 
> > > 3rd party bug.
> > 
> > 
> > im sorry, but in what way?
> 
> Fabian made a small mistake with the launcher, other words: 3rd party bug.

you mean the arcticum launcher?

and if so, did they already update their launcher?

**Comment by MaxtorCoder** [comment]
> 
> 
> > > > 3rd party bug.
> > > 
> > > 
> > > im sorry, but in what way?
> > 
> > 
> > Fabian made a small mistake with the launcher, other words: 3rd party bug.
> 
> you mean the arcticum launcher?
> 
> and if so, did they already update their launcher?

Please refer to the Discord, issue is closed :P
