### ISSUE TITLE
DB/Quest: Winter's Presents Appearing too soon

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25733]
**Description:**

Quest "Winter's Presents" is appearing too soon.
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8827

**Expected behaviour:**

This quest should not be available before 25th December

**Steps to reproduce the problem:**

1. Visit nearest Wonderform Operator NPC (Mine was in Stormwind)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15732  
2. NPC offers quest right now (before 25th).

Note: You can complete the quest by speaking to Grandfather Winter, however, the presents are not available to open as yet - this part is working correctly.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 0b310a154664 2020-12-15 22:49:47 +0000 (3.3.5 branch) (Win64, RelWithDebInfo, Static) 

**Operating system:** 

Windows 7 64bit

**Comment by illfated** [comment]
TrinityCore rev. 0b310a154664 2020-12-15 22:49:47 +0000 (3.3.5 branch) (Win64, Release, Static)

Confirmed, the quests are available. I was uncertain exactly what to expect, or if they were supposed to be held back until 24./25. and 31. of December. Then again, maybe I have played too long on TC and have been gone too long from retail games.
