### ISSUE TITLE
Server Crash on Starting Outdoor PVP System

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25748]
Description:
Server Crash, no further download.

Branch(es):
master

TrinityCore rev. fbbf40981cc1 2020-12-20 22:49:53 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

OS: Win 

![1](https://user-images.githubusercontent.com/61392055/102857064-d3f77780-4438-11eb-99eb-fb1dcb97f3ca.jpg)

**Comment by MaxtorCoder** [comment]
Attach crashlog.....

**Comment by jackpoz** [comment]
Instructions from the template:

>**Description:**
CHANGEME Description of the problem or issue here.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Comment by NiganNi** [comment]
https://gist.github.com/NiganNi/427c20188c8d659c179249784974323d

**Comment by MaxtorCoder** [comment]
> https://gist.github.com/NiganNi/427c20188c8d659c179249784974323d

Please build in RelWithDebInfo, this stacktrace is useless at the moment.

**Comment by NiganNi** [comment]
https://gist.github.com/NiganNi/02bb70ab4e574e10b6c371ba6e6f6224

**Comment by MaxtorCoder** [comment]
Please pull latest source, you are running on an outdated version of TrinityCore.

**Comment by NiganNi** [comment]
TrinityCore rev. fbbf40981cc1 2020-12-20 22:49:53 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by MaxtorCoder** [comment]
Then for the love of god update the freaking original Issue message.

**Comment by NiganNi** [comment]
Shauren  thanks it works! 
label HasBacktrace what means?

**Comment by illfated** [comment]
> Shauren thanks it works!

Thank you for the feedback. You see that a good issue gets proper attention when it contains correct information.

> label HasBacktrace what means?

"HasBacktrace" is a reference to a Debug log text (usually from Linux builds) meaning that it is possible to trace information back to where the bug can be found in the source.
