### ISSUE TITLE
Barbershop Gender change broken.

### ISSUE THREAD

**Issue by Daribon** [TrinityCore/TrinityCore#25742]
**Description:**

Barbershop gender change doesn't change model correctly.
Changing gender at barbershop is a feature added in Shadowlands.
![Wow_O7npJVW96i](https://user-images.githubusercontent.com/6137576/102642807-82ac6700-415e-11eb-9696-34925936acdc.png)

**Expected behaviour:**

When changing gender in barbershop, the model should be changed.

**Steps to reproduce the problem:**

1. Go to a barbershop chair.
2. Enter it and change to the opposite sex.
3. Hit accept.
4. The texture of the new gender you selected will be pasted on top of your old model.

**Branch(es):**

master

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8742bf353df619bd24b00ef8eeea7590c85e8761

**Operating system:** Windows 10 x64

**Comment by Shauren** [comment]
Nice

**Comment by MaxtorCoder** [comment]
Nice.
