### ISSUE TITLE
Server Crash on loading Transport using the last tdb

### ISSUE THREAD

**Issue by FCondeNR** [TrinityCore/TrinityCore#25744]
**Description:**
Server Crash when load Transport using currently tdb
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFE8FCA6148 01:0000000000005148 C:\

libmysql.dll

Registers:
RAX:0000000000000000
RBX:00000214AFF414D8
RCX:00000214ADDB6C90
RDX:00000214ADDC5346
RSI:00000214AFEBAF00
RDI:00000214ADDB6C90
R8: 00007FFE9583183B
R9: 00007FFE8FCA0000
R10:00000214ADDC5340
R11:0000006A29D59D90
R12:00000214AFE5C160
R13:0000006A29D59D60
R14:0000006A29D59D98
R15:0000000000000001
CS:RIP:0033:00007FFE8FCA6148
SS:RSP:002B:0000000029D59AA8  RBP:ADDB6C90
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

**Steps to reproduce the problem:**
Sadly I cannot reppy the problem of what cause it
**Branch(es):**

master
**TC rev. hash/commit:** 
TrinityCore rev. 9e0eac83bf3a 2020-12-15

**Operating system:** CHANGEME OS

![82 223 97 22 - Conexión a Escritorio remoto](https://user-images.githubusercontent.com/67517462/102686222-7835b000-41e6-11eb-948a-e98ddbc0e905.jpg)

**Comment by FCondeNR** [comment]
seems be a thing related whit char db, something structure on character not fixed??

**Comment by MaxtorCoder** [comment]
This log does not help at all. Attach entire log please.

**Comment by illfated** [comment]
Please check out the details in the closed issue ticket #25740 , particularly the comments relating to CR/LF line ending conversion between Unix & Windows.

- https://github.com/TrinityCore/TrinityCore/issues/25740#issuecomment-747999576

> For some reason your core thinks that 2020_11_16_00_characters.sql has a different hash than `33D5C75` and tries to reapply it - but on a clean clone in a Linux virtual machine it shows `33D5C75` to me, did you modify that file in some way?

- https://github.com/TrinityCore/TrinityCore/issues/25740#issuecomment-748064157

> Ha I think I found the issue; it has something to do with newlines settings and git.
> It's also the reason why git doesn't show any diff content.
>
> I'll verify it and close this issue if that is truly the case.

**Comment by FCondeNR** [comment]
Curreltly using windows, since I replace the db it not happends yet, it happend before, I will try to investigate more whit more info

**Comment by MaxtorCoder** [comment]
Or just attach the entire crashlog.......

**Comment by illfated** [comment]
Yes, a Debug crash log would be helpful in this case, since it does not seem to relate to other issues.

**Comment by NiganNi** [comment]
Shauren thanks it works!

**Comment by illfated** [comment]
Hm. Nice. Looks like there were some DB handling issues with character corpses.
