### ISSUE TITLE
9.0.2 Warlocks do not receive Soul Shards at level 3

### ISSUE THREAD

**Issue by KamiliaBlow** [TrinityCore/TrinityCore#25754]
**Description:**

Upon reaching level 3, soul shards do not work, but if you give a character level 11, shards appear on the interface

**Expected behaviour:**

Resource Shards of Souls (also on the interface panel) must be obtained by the warlock class at level 3

**Steps to reproduce the problem:**

1. Create a character with the warlock class
2. Go to the game and get level 3

**Branch(es):**

master

**TC rev. hash/commit:** 

bff8f2f

**Operating system:** Windows 10 64x

**Comment by illfated** [comment]
Could this be a remaining setting from the 3.3.5 branch or from anything before Shadowlands, that warlocks used to get soul shards at level 11?

**Comment by DintyGadget** [comment]
Adding to the problem: even after reaching level 11, there is no way to get soul shards

**Comment by illfated** [comment]
Sounds like missing implementation updates in relation to the 9.x client changes. We may need some patience and wait for it to be corrected.
