### ISSUE TITLE
Wrong levels in locations

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25758]
**Description:**
The level of mobs corresponds to the level of locations from bfa.
Outland  60-70.
Northrend 70-80
Cataclysm 80-85

Branch(es):
master

TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

OS: Win

**Steps to reproduce the problem:**
1)Create characters.
2)Teleport to any location: cata, nord, outland.

**Comment by offl** [comment]
Duplicate of #26673 / #26845
