### ISSUE TITLE
Quest 754. No text for quest_request_item

### ISSUE THREAD

**Issue by Cerveciento** [TrinityCore/TrinityCore#25752]
**Description:**

The first thing is to say that I really am not clear if this is a problem or should be so.
In quest 754 (Winterhoof Cleansing), after accepting it, speaking again to quest giver (2948). A window with no text appears.
I don't know if this should be the case, I've been looking for information and nowhere have I found what text should appear, except in wowhead classic.
It may be a slight difference in classic.
I have no way of knowing if the text is missing or the empty window is left over.
https://es.classic.wowhead.com/quest=754/la-purificaci%C3%B3n-de-pezu%C3%B1a-invernal

**Expected behaviour:**

1. The window pops up and displays some text.
2. Can't talk to the quest giver.
3. ????

**Steps to reproduce the problem:**

1. Create tauren
2. .go zonexy 48.4 60.4
3.  .q a 754
4. talk whit quest giver

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 9ae23ef2fdb9
**Operating system:** debian 10

**Comment by Faq** [comment]
for 335 use this db  https://tcubuntu.northeurope.cloudapp.azure.com/aowow/

**Comment by Cerveciento** [comment]
I have also consulted that. I have only put the only one that contributed something different.
http://web.archive.org/web/20100415110831/http://es.wowhead.com/quest=754
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=754
https://es.classic.wowhead.com/quest=754/la-purificaci%C3%B3n-de-pezu%C3%B1a-invernal
https://es.wowhead.com/quest=754/la-purificaci%C3%B3n-de-pezu%C3%B1a-invernal
and youtube,... all video classic

**Comment by illfated** [comment]
TrinityCore rev. 0b310a154664 2020-12-15 22:49:47 +0000 (3.3.5 branch) (Win64, Release, Static) TDB 335.20121

```sql
SELECT * FROM `quest_request_items` WHERE `ID`= 754;
```
```
 ID  EmoteOnComplete  EmoteOnIncomplete  CompletionText  VerifiedBuild
---  ---------------  -----------------  --------------  -------------
754                1                  0  (NULL)                  12340
```
Is this quest one of those that remained bugged on Blizzard servers until the new Classic servers were released?

**Comment by offl** [comment]
I doubt that text was added to classic from new (cata) version of that quest

**Comment by Cerveciento** [comment]
Another quest with the same symptoms (6002)

**Comment by illfated** [comment]
Maybe it is a source issue, then, that it was added on basis of wowhead info and not from sniff or "bruteforce"?

**Comment by offl** [comment]
Just add texts from classic wowhead

**Comment by Cerveciento** [comment]
> 
> 
> Just add texts from classic wowhead

OK

**Comment by Cerveciento** [comment]
**Fix**
I assume that the VerifiedBuild value should be 0
``` sql
-- 754 Winterhoof Cleansing
-- Notice: English text is also missing
-- https://classic.wowhead.com/quest=754
SET @ID := 754;
UPDATE `quest_request_items` SET `CompletionText` = 'Do not delay, $n. The Winterhoof Well\'s taint must be removed!', `VerifiedBuild` = 0 WHERE `id` = @ID ;
-- 6002 Body and Heart
-- https://classic.wowhead.com/quest=6002
SET @ID := 6002;
UPDATE `quest_request_items` SET `CompletionText` = 'When you have faced the challenge that lies before you, your understanding of strength of body and strength of heart will be fully realized. Until that time, I cannot help you further.', `VerifiedBuild` = 0 WHERE `id` = @ID;
```

**Comment by illfated** [comment]
> I assume that the VerifiedBuild value should be 0
> 
That is correct. Other values than 0 mean sniff source or other known sources.

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/34897937/quest+request+items#quest_request_items-VerifiedBuild

### VerifiedBuild

This field is used by the TrinityCore DB Team to determine whether a template has been verified from WDB files.

- If value is 0, it has not been parsed yet.
- If value is > 0, it has been parsed with WDB files from that specific Client Build.
- If value is -1, it is just a place holder until proper data are found on WDBs.
- If value is -Client Build, it was parsed with WDB files from that specific client build and manually edited later for some specific necessity.

**Comment by offl** [comment]
> Notice: English text is also missing

You meant esES?

**Comment by illfated** [comment]
Both would be correct, I presume. @Cerveciento : Are you planning to include the esES & mxMX version in a later issue, or post it here?
