### ISSUE TITLE
Spell: Consecration

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25761]
**Description:**
Consecration(class:paladin) does not work.

Branch(es):
master

TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

OS: Win

**Steps to reproduce the problem:**
1)Create characters paladin.
2)cmd .levelup 5.
4)Use spell Consecration ( https://www.wowhead.com/spell=26573/consecration )

**Comment by Faq** [comment]
You missed some points from issue template. For example, what happened and how it should work?

**Comment by NiganNi** [comment]
> You missed some points from issue template. For example, what happened and how it should work?

1)When you click on a spell, nothing happens.
2)Spell info: 
[https://www.wowhead.com/spell=26573/consecration](url)

**Comment by Naddley** [comment]
Since the update of Matanshukry https://github.com/TrinityCore/TrinityCore/pull/26147 Consecration have an visuel.
Only Issue left: It dont do dmg.
