### ISSUE TITLE
Smartscript cannot reproduce sound on quest taken

### ISSUE THREAD

**Issue by FCondeNR** [TrinityCore/TrinityCore#25769]
**Description:**
Smartscript seems not work like be deseable but yes do the text param

**Expected behaviour:**
play sound talk 

**Steps to reproduce the problem:**
1. lauch the sql like:
in this case its the quest murlockmania, whit captain garrick , take quest, play sound, id of sound 152737 
 
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(156626,0,1,0,19,0,100,0,55122,0,0,0,4,152737,1,1,0,0,0,1,0,0,0,0,0,0,0,"Captain Garrick - Hablando murlock mania");
1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. lauch server

**Branch(es):**

master

**TC rev. hash/commit:** 
TrinityCore rev. 2a1066839596 2020-12-23 00:13:59 +0100

**Operating system:** CHANGEME OS

![World of Warcraft_34](https://user-images.githubusercontent.com/67517462/103173673-bb35fa00-485c-11eb-9d42-3562adfecd03.jpg)

**Comment by offl** [comment]
> (156626,1

Your source_type is gameobject

**Comment by FCondeNR** [comment]
I changed that and too worked , to 0 it was a miss sorry :)

**Comment by offl** [comment]
And you don't need to handle text and sound separately, there is creature_text.Sound column

**Comment by FCondeNR** [comment]
still no work!!

**Comment by illfated** [comment]
What exactly does not work? Can you post the SAI you are trying to use?

**Comment by illfated** [comment]
Maybe you just edited the DB table and did not reload the DB table, or restart server?

**Comment by offl** [comment]
I read it wrong
Yep, post the SAI + text and check if you reloaded SAI or not

**Comment by jackpoz** [comment]
> No description provided.

no issue description ?

**Comment by FCondeNR** [comment]
updated

**Comment by offl** [comment]
1 apply sql
2 .rel sma or restart worldserver and try again
3. kil creature and respawn it
4. try again
