### ISSUE TITLE
worldserver crash and i dont know why 

### ISSUE THREAD

**Issue by krokogames** [TrinityCore/TrinityCore#25767]
**Branch(es):**

master

**Operating system:** windows 10

worldserver.exe initialize data stores and crash

crash log

[89cfced1b568_worldserver.exe_[27-12_10-48-50].txt](https://github.com/TrinityCore/TrinityCore/files/5744359/89cfced1b568_worldserver.exe_.27-12_10-48-50.txt)

normal log

[Server.log](https://github.com/TrinityCore/TrinityCore/files/5744360/Server.log)

**Comment by MaxtorCoder** [comment]
Please follow the full issue template. What commit hash etc.

**Comment by Shauren** [comment]
Your `DataDir` in config is invalid

**Comment by krokogames** [comment]
i use default config "."

![image](https://user-images.githubusercontent.com/7843239/103172601-dac92480-4854-11eb-861a-eac757bf1ae0.png)

**Comment by illfated** [comment]
Looks a bit odd, what is in your \\data\\ folder? 
I don't know, but does the master have a default \\data\\ directory in the core directory?
My 3.3.5 installation does not have a \\data\\ folder, while using the default path `DataDir = "."`.

Try moving the contents from your \\data\\ folder up into the core folder (1 level up).

**Comment by krokogames** [comment]
@illfated solved im need again extract maps vmaps
