### ISSUE TITLE
Server crash while completing quest

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25762]
**Description:**
Server crash when trying to turn in a quest "The Crucible of Carnage: Calder's Creation!"

Branch(es):
master

Revision: TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static)

OS: Win

**Steps to reproduce the problem:**
1)Take the quest
2)Make a quest
3)Try to turn in the quest
**Quest info:**
https://www.wowhead.com/quest=27866/the-crucible-of-carnage-calders-creation

**Crashlog:**
https://gist.github.com/NiganNi/0a2ce48469859c2b5fdf8a2f2cfb894e

**Comment by Faq** [comment]
ref 1000f670d211f2ac5aef3351af0f08de06e13097

**Comment by Shauren** [comment]
Damn typo in issue number in commit message
