### ISSUE TITLE
Custom boss script,low

### ISSUE THREAD

**Issue by jedanimo** [TrinityCore/TrinityCore#25774]
**Description:**
Need a simple example,check player cast spells.

**Steps to reproduce the problem:**
how to check player cast spell.

**Expected behaviour:**
if(player cast spell heal)boss cast spell fear on a player

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 2493d88
**Operating system:** windows 10

**Comment by jackpoz** [comment]
I think this fits better on the forum or on irc or on discord as it's not an issue to be fixed, more like a question to get started.

I'm closing this issue, anyone can comment if they want to help anyway (closed issues are not locked)
