### ISSUE TITLE
Core/Maps: BaseMapLoadAllGrids causes server crash

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#25777]
**Description:**
When starting the server with `GridUnload = 0` and` BaseMapLoadAllGrids = 1` , the server crashes while preloading the maps.

**Expected behaviour:**
The server should not crash.

**Steps to reproduce the problem:**
apply the following settings in `world.conf` and start the server:
```
#
#    GridUnload
#        Description: Unload grids to save memory. Can be disabled if enough memory is available
#                     to speed up moving players to new grids.
#        Default:     1 - (enable, Unload grids)
#                     0 - (disable, Do not unload grids)

GridUnload = 0

#
#    BaseMapLoadAllGrids
#        Description: Load all grids for base maps upon load. Requires GridUnload to be 0.
#                     This will take around 5GB of ram upon server load, and will take some time
#                     to initially load the server.
#        Default:     0 - (Don't preload all base maps, dynamically load as used)
#                     1 - (Preload all grids in all base maps upon load)

BaseMapLoadAllGrids = 1
```

The following exception is thrown, thanks to @illfated for catching with debug build:
```
Exception code: C0000420 An assertion failure has occurred.

Assertion message:
C:\Trinity\Source\src\server\game\Maps\Map.h:854 in Map::GetRespawnMapForType ABORTED.
```
https://gist.github.com/illfated/46a28ab26a4428e3e268e59ccebb35d6

(linked issue: https://github.com/TrinityCore/TrinityCore/issues/25409)

**Branch(es):**
3.3.5

**TC rev. hash/commit:**
TrinityCore rev. 3b1e911 2020-09-06 01:40:00 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:**
Win10

**Comment by jackpoz** [comment]
could you try on latest 335 rev too ?

**Comment by schell244** [comment]
I could still reproduce the crash with latest rev (and GridUnload = 0 and BaseMapLoadAllGrids = 1)
```
TrinityCore rev. 0ad1854d1c6a 2020-12-28 12:38:34 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
```

**Comment by jackpoz** [comment]
what if you disable BaseMapLoadAllGrids , startup and use command ```.debug loadcells 1``` ? That crashlog seem to happen in kalimdor.

**Comment by jackpoz** [comment]
could you backup your `characters`.`respawn` table ? even better if it's with sql statements that can be imported (usually sql clients have an option to do a backup of a single table)

**Comment by schell244** [comment]
When using `.debug loadcells 1`, I get the following logs:
```
TC> .debug loadcells 1
Loading all cells (mapId: 1). Current GameObjects 5, Creatures 0
Cells loaded (mapId: 1) After load - GameObject 9718, Creatures 28076
TC>
```
No crash, and server took about ~9,5gb of memory.
With` BaseMapLoadAllGrids` it took ~12gb before it crashed

**Comment by schell244** [comment]
> could you backup your `characters`.`respawn` table ? even better if it's with sql statements that can be imported (usually sql clients have an option to do a backup of a single table)

[respawn.zip](https://github.com/TrinityCore/TrinityCore/files/5748436/respawn.zip)

**Comment by jackpoz** [comment]
I was able to reproduce the crash, ty. In the meantime you can avoid crashing it by emptying the respawn table, like
```sql
TRUNCATE TABLE respawn;
```
