### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#25786]
**Description:**
Server crash reasons not established
**Branch(es):**
master

**Revision: TrinityCore rev. 1000f670d211 2020-12-24 21:26:19 +0100 (master branch) (Win64, RelWithDebInfo, Static)**

OS: Win

Steps to reproduce the problem:
...

**Crashlog:**
https://gist.github.com/NiganNi/0faa6f477d0d9c0cd0919fee73dc45a0

**Comment by illfated** [comment]
Something happened around here, it seems, but I am not sure if I read the crash log correctly.

https://gist.github.com/NiganNi/0faa6f477d0d9c0cd0919fee73dc45a0#file-gistfile1-txt-L40
000000013FA891F1  000000000022E210  Unit::_AddAura+281  C:\...\src\server\game\Entities\Unit\Unit.cpp line 3288

https://gist.github.com/NiganNi/0faa6f477d0d9c0cd0919fee73dc45a0#file-gistfile1-txt-L297
000000013FA891F1  000000000022E210  Unit::_AddAura+281  C:\...\src\server\game\Entities\Unit\Unit.cpp line 3288

https://github.com/TrinityCore/TrinityCore/blob/1000f670d211f2ac5aef3351af0f08de06e13097/src/server/game/Entities/Unit/Unit.cpp#L3288

(section below linked for the context of the referenced line above)
https://github.com/TrinityCore/TrinityCore/blob/1000f670d211f2ac5aef3351af0f08de06e13097/src/server/game/Entities/Unit/Unit.cpp#L3286-L3322

**Comment by Shauren** [comment]
Fixed in 6a69dcced2e5bb6227eff28c48c4636cfdb23a1e
