### ISSUE TITLE
(C2664) WheatyExceptionReport.cpp (Compile for Windows 7 32bit)

### ISSUE THREAD

**Issue by triggytag** [TrinityCore/TrinityCore#25789]
**Soft:**
Visual Studio Community 2019 (16.8.3) x86
Boost 1.72.0 x86
CMake 3.19.2 x86
Open SSL 1.1.1i
MySQL 5.7.26.0 (lib)

Use TrinityCore Wiki for help to compile core...

**OS:**
Windows 7 x64
Windows 7 x86 (Server)

**CMake Info:**
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
Detected 32-bit platform
MSVC: Minimum version required is 19.24, found 19.28.29335.0 - ok!
MSVC: Enabled large address awareness
MSVC: Enabled SSE2 support
MSVC: Disabled Safe Exception Handlers for debug builds
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files (x86)/MySQL/MySQL Server 5.7/lib/libmysql.lib
Found MySQL headers: C:/Program Files (x86)/MySQL/MySQL Server 5.7/include
Found MySQL executable: C:/Program Files (x86)/MySQL/MySQL Server 5.7/bin/mysql.exe
Found git binary : C:/Program Files (x86)/Git/cmd/git.exe

* TrinityCore revision   : 96b289cadbf3 2020-12-30 21:18:00 +0100 (3.3.5 branch)

* Install core to        : C:/Program Files (x86)/TrinityCore
* Install configs to     : C:/Program Files (x86)/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Found OpenSSL library: optimized;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libssl32MD.lib;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MD.lib;debug;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libssl32MDd.lib;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib
Found OpenSSL headers: C:/Program Files (x86)/OpenSSL-Win32/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done
Generating done

**Problem:** 
11>------ Build started: Project: mapextractor, Configuration: RelWithDebInfo Win32 ------
11>Building Custom Rule C:/Server/Source/src/tools/map_extractor/CMakeLists.txt
11>System.cpp
11>adt.cpp
11>dbcfile.cpp
11>loadlib.cpp
11>mpq_libmpq.cpp
11>wdt.cpp
11>WheatyExceptionReport.cpp
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(569,146): error C2664: 'DWORD_PTR WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()(int32) const': cannot convert argument 1 from 'CatchableTypeArray *const ' to 'int32'
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(569,125): message : There is no context in which this conversion is possible
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(567,13): message : see declaration of 'WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()'
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(570,171): error C2664: 'DWORD_PTR WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()(int32) const': cannot convert argument 1 from 'CatchableType *const ' to 'int32'
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(570,170): message : There is no context in which this conversion is possible
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(567,13): message : see declaration of 'WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()'
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(571,143): error C2664: 'DWORD_PTR WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()(int32) const': cannot convert argument 1 from 'TypeDescriptor *const ' to 'int32'
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(571,136): message : There is no context in which this conversion is possible
11>C:\Server\Source\src\common\Debugging\WheatyExceptionReport.cpp(567,13): message : see declaration of 'WheatyExceptionReport::GenerateExceptionReport::<lambda_44bcff7732b2b84ca154565620c00ef1>::operator ()'
11>Done building project "mapextractor.vcxproj" -- FAILED.
========== Build: 10 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Ctrl+Break

**Comment by triggytag** [comment]
**x64 Compile**

12>------ Build started: Project: mapextractor, Configuration: Release x64 ------
12>Building Custom Rule C:/Server/Source/src/tools/map_extractor/CMakeLists.txt
12>System.cpp
12>adt.cpp
12>dbcfile.cpp
12>loadlib.cpp
12>mpq_libmpq.cpp
12>wdt.cpp
12>WheatyExceptionReport.cpp
12>mapextractor.vcxproj -> C:\Server\Build\bin\Release\mapextractor.exe
========== Build: 12 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Not Problem! 


**Cause:**
WheatyExceptionReport.cpp - 32bit not a build.

**Comment by MaxtorCoder** [comment]
> **x64 Compile:**
> 12>------ Build started: Project: mapextractor, Configuration: Release x64 ------
> 12>Building Custom Rule C:/Server/Source/src/tools/map_extractor/CMakeLists.txt
> 12>System.cpp
> 12>adt.cpp
> 12>dbcfile.cpp
> 12>loadlib.cpp
> 12>mpq_libmpq.cpp
> 12>wdt.cpp
> 12>WheatyExceptionReport.cpp
> 12>mapextractor.vcxproj -> C:\Server\Build\bin\Release\mapextractor.exe
> ========== Build: 12 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> 
> Not Problem! 
> 
> 
> **Cause:**
> WheatyExceptionReport.cpp - Do not support 32bit Build

Oh really >_>, you don't say, close the issue please.

**Comment by triggytag** [comment]
> > **x64 Compile:**
> > 12>------ Build started: Project: mapextractor, Configuration: Release x64 ------
> > 12>Building Custom Rule C:/Server/Source/src/tools/map_extractor/CMakeLists.txt
> > 12>System.cpp
> > 12>adt.cpp
> > 12>dbcfile.cpp
> > 12>loadlib.cpp
> > 12>mpq_libmpq.cpp
> > 12>wdt.cpp
> > 12>WheatyExceptionReport.cpp
> > 12>mapextractor.vcxproj -> C:\Server\Build\bin\Release\mapextractor.exe
> > ========== Build: 12 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> > Not Problem!
> > **Cause:**
> > WheatyExceptionReport.cpp - Do not support 32bit Build
> 
> Oh really >_>, you don't say, close the issue please.

What am I not saying?

**Comment by illfated** [comment]
@triggytag : The fault is not yours, but rather a lack of information that it is currently not possible to build 32-bit versions of TrinityCore. This is based on some C++ changes in recent years, specifically for WheatyExceptionReport.
