### ISSUE TITLE
(Compile 32bit) WheatyExceptionReport.cpp(569,146): error C2664 etc.

### ISSUE THREAD

**Issue by triggytag** [TrinityCore/TrinityCore#25787]
**Description:**
Compile Problem.

**Branch(es):**
3.3.5

**OS:** Win

**Cmake Info:**
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
Detected 32-bit platform
MSVC: Minimum version required is 19.24, found 19.28.29335.0 - ok!
MSVC: Enabled large address awareness
MSVC: Enabled SSE2 support
MSVC: Disabled Safe Exception Handlers for debug builds
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files (x86)/MySQL/MySQL Server 5.7/lib/libmysql.lib
Found MySQL headers: C:/Program Files (x86)/MySQL/MySQL Server 5.7/include
Found MySQL executable: C:/Program Files (x86)/MySQL/MySQL Server 5.7/bin/mysql.exe
Found git binary : C:/Program Files (x86)/Git/cmd/git.exe

* TrinityCore revision   : 96b289cadbf3 2020-12-30 21:18:00 +0100 (3.3.5 branch)

* Install core to        : C:/Program Files (x86)/TrinityCore
* Install configs to     : C:/Program Files (x86)/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Found OpenSSL library: optimized;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libssl32MD.lib;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MD.lib;debug;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libssl32MDd.lib;C:/Program Files (x86)/OpenSSL-Win32/lib/VC/libcrypto32MDd.lib
Found OpenSSL headers: C:/Program Files (x86)/OpenSSL-Win32/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done
Generating done

**VS 2019:**
The problem has not been fixed

**Comment by illfated** [comment]
<details>
<summary>English excerpt from the Visual Studio error codes & messages</summary>


```
error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "CatchableTypeArray * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "CatchableType * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "TypeDescriptor * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

Build of project "mapextractor.vcxproj" completed with an error.

WheatyExceptionReport.cpp
error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "CatchableTypeArray * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":
 cannot convert argument 1 from "CatchableType * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "TypeDescriptor * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

17> Build project "vmap4assembler.vcxproj" completed with an error.

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "CatchableTypeArray * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "CatchableType * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

error C2664: "DWORD_PTR WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator () (int32) const":

 cannot convert argument 1 from "TypeDescriptor * const" to "int32"

message: There is no context in which such a conversion is possible
message: see declaration "WheatyExceptionReport :: GenerateExceptionReport :: <lambda_44bcff7732b2b84ca154565620c00ef1> :: operator ()"

19> Build project "vmap4extractor.vcxproj" completed with an error.
```

</details>

To me, it just looks like you have made changes to the TC source and the changes you made are not valid in the compiler.
(not supported / not valid TrinityCore unchanged code)

**Comment by triggytag** [comment]
> English excerpt from the Visual Studio error codes & messages
> To me, it just looks like you have made changes to the TC source and the changes you made are not valid in the compiler.
> (not supported / not valid TrinityCore unchanged code)

sorry, but i use Ru VS 2019, i compile for Win32

**Comment by triggytag** [comment]
> English excerpt from the Visual Studio error codes & messages
> To me, it just looks like you have made changes to the TC source and the changes you made are not valid in the compiler.
> (not supported / not valid TrinityCore unchanged code)

Ok, i recompile in EN Version

**Comment by illfated** [comment]
Basically, the error messages say the following (in English):

```
cannot convert argument 1 from "CatchableTypeArray * const" to "int32"
cannot convert argument 1 from "CatchableType * const"      to "int32"
cannot convert argument 1 from "TypeDescriptor * const"     to "int32"
```

- This means that you have made manual changes to the source code, which is fine, but TrinityCore does not support compiling issues in changed code.
- Your problem is a personal problem for you, not for TrinityCore.
- TrinityCore issue tickets are only meant for source code problems currently valid for **everyone** using _unchanged_ TrinityCore source.

Use the TrinityCore Forum pages, or IRC or Discord, to ask for help with your personal source code changes. This is not a valid issue.

**Comment by illfated** [comment]
#please-close

**Comment by triggytag** [comment]
> #please-close

No, i not make Manual Changes!

**Comment by jackpoz** [comment]
> Selecting Windows SDK version 8.1 to target Windows 6.1.7601.

I'd suggest a Windows SDK Version 10

**Comment by triggytag** [comment]
> Basically, the error messages say the following (in English):
> 
> ```
> cannot convert argument 1 from "CatchableTypeArray * const" to "int32"
> cannot convert argument 1 from "CatchableType * const"      to "int32"
> cannot convert argument 1 from "TypeDescriptor * const"     to "int32"
> ```
> 
> * This means that you have made manual changes to the source code, which is fine, but TrinityCore does not support compiling issues in changed code.
> * Your problem is a personal problem for you, not for TrinityCore.
> * TrinityCore issue tickets are only meant for source code problems currently valid for **everyone** using _unchanged_ TrinityCore source.
> 
> Use the TrinityCore Forum pages, or IRC or Discord, to ask for help with your personal source code changes. This is not a valid issue.

I am use Wiki TrinityCore and install sources with GitExt Clone, branch 3.3.5, next Cmake configure and generate to 32bit, next VS 2019, get ERROR... I'am a not make "Manual Changes"!!!

**Comment by illfated** [comment]
> I am use Wiki TrinityCore and install sources with GitExt Clone, branch 3.3.5, next Cmake configure and generate to 32bit, next VS 2019, get ERROR... I'am a not make "Manual Changes"!!!

OK, fair enough. The error messages just seemed to point in that direction.

I forgot to take Windows 7 / Windows 8.x problems into account.

**Comment by illfated** [comment]
BTW, this points more in the direction of a need for TC Wiki update or clear notes about what to do if you are trying to use Windows 7 / Windows 8, instead of Windows 10.

**Comment by triggytag** [comment]
> BTW, this points more in the direction of a need for TC Wiki update or clear notes about what to do if you are trying to use Windows 7 / Windows 8, instead of Windows 10.

I am install Windows 10 SDK (10.0.16299.0)

**Comment by triggytag** [comment]
> > Selecting Windows SDK version 8.1 to target Windows 6.1.7601.
> 
> I'd suggest a Windows SDK Version 10

How to change SDK?

**Comment by illfated** [comment]
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/#:~:text=Getting%20started,the%20Visual%20Studio%202019%20Installer.

- https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/

### Getting started

You can get the Windows 10 SDK in two ways: install it from this page by selecting the download link or by selecting “Windows 10 SDK (10.0.19041.0)” in the optional components of the Visual Studio 2019 Installer.

**Comment by triggytag** [comment]
> https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/#:~:text=Getting%20started,the%20Visual%20Studio%202019%20Installer.
> 
> * https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
> 
> ### Getting started
> You can get the Windows 10 SDK in two ways: install it from this page by selecting the download link or by selecting “Windows 10 SDK (10.0.19041.0)” in the optional components of the Visual Studio 2019 Installer.

Cmake automated change SDK? Or this need do manual?

**Comment by illfated** [comment]
Not sure, I have only used Win10 myself and added the recommended sources as written in the wiki page.

**Comment by triggytag** [comment]
> Not sure, I have only used Win10 myself and added the recommended sources as written in the wiki page.
**Selecting Windows SDK version 8.1 to target Windows 6.1.7601.**
Install Windows SDK version 10, but Cmake show THIS!

**Comment by triggytag** [comment]
> > Selecting Windows SDK version 8.1 to target Windows 6.1.7601.
> 
> I'd suggest a Windows SDK Version 10

I am install Windows 10 SDK, but my CMake show me Windows SDK version 8.1.
