### ISSUE TITLE
Core/Creature: creature_template_movement requires changes

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25788]
You may think it's a good idea to "dump everything in one table" © but it's not. It makes it harder to work with. For example I need to create 1k new entries. Luckily I know which ones of them can penetrate water and which ones can swim. All of them can flight. In other words devs always have to take in consideration other movement states when new row is added.

Currently, if I want to compare Rooted or Swim or any other state with CreatureDifficulty, I need to check hundreds creatures with wrong states because everything is dumped into one table. It's not devs fault, we are using default values to prevent bugs.

In the end all that stuff is handled by flags. And it's the most easy and user-friendly implementation. There was InhabitType and it was nice to work with. Because it was simple. You had several states you can use, you were able to mix them as you want. And the most important thing it was one column inside creature_template. Dumping all states in one table and creating several new states and also creating links between them makes it harder to work with.

Step 1: Rooted
```text
Rooted creature that doesn't fall once dead must use `Ground`=1, `Swim`=0, `Flight`=0, `Rooted`=1 (`Swim`=1 if above water)
Rooted creature that falls once dead must use `Ground`=0, `Swim`=0, `Flight`=1, `Rooted`=1
```

There is difficulty flag CREATURE_DIFFICULTYFLAGS_SESSILE 0x00000100
'Rooted' should be re-implemented as new extra flag.
As you can see currently we can make creature fall once dead and don't make it fall once dead. To be honest I don't really know if some creatures should fall once dead. But I'm sure some of them **should not** fall once dead.
There may be another difficulty flag that controls it we haven't yet discovered. To unlock new steps we can create another extra flag to control that 'fall or not fall' once dead while rooted.

Step 2: Ground

There is difficulty flag CREATURE_DIFFICULTYFLAGS_WATER_BOUND
Ground should be re-implemented as new extra flag. Creatures with _WATER_BOUND flag should not be able to walk on ground, otherwise creature can walk on ground.

Ground contains also state "Hover"=2, isn't hovering implemented by bytes1?

Step 3: Swim

There is difficulty flag CREATURE_DIFFICULTYFLAGS_CAN_PENETRATE_WATER
Swim should be re-implemented as new extra flag.

Step 4: Flight

There is difficulty flag CREATURE_DIFFICULTYFLAGS_UNK13 = 0x20000000, // Related to gravity
Flight should be re-implemented as new extra flag.

"CanFly" =2 state comes from auras if I'm not wrong. You don't really need to use it.

--

What about creature_movement_override? That's a pretty good question because I don't know if creature.flags_extra will work here.

**Branch(es):** both
**TC rev. hash/commit:** 9ae23ef2fdb9

**Comment by Ovahlord** [comment]
First of all, stop wanting to stuff everything into flags extra. That field is already way too bloated. The template movement already supports basically all you need and yes, this table SHOULD have an entry for every single creature_template entry just like every single entry should have a creature_template_addon entry by default.

Means:
 `INSERT IGNORE INTO `creature_template_movement` SET `entry` FROM `creature_template`;`


CanFly does not imply that a unit is flying. CanFly means that a creature is capable of dynamically transitioning between flight and ground movement which is currently not implemented. Only a handful of creatures use that, like >= 4.x  orgrimmar and stormwind guards which can mount and dismount on gryphons and wind riders. Means: the average db dev never ever uses that value. Never.

Rooted is literally what it says: you are rooted on the spot and thus you are not allowed to fall on death while rooted via template. For tempoary root states there are auras used by creatures like Root Self etc. which will get removed on death so a creature will fall. That part should already work as intended.

Swimming is the same scenario. Stop stuffing everything into extra flags and set the field properly in template_movement
Having one giant table for everything like that is stupid and I'm actually for splitting creature_template even further to seperate sniffed query template data from all that custom stuff

**Comment by Shauren** [comment]
> Ground contains also state "Hover"=2, isn't hovering implemented by bytes1?

No, bytes (2, not 1) means animTier and only controls which animation gets used clientside, not movement flags

**Comment by offl** [comment]
> First of all, stop wanting to stuff everything into flags extra. That field is already way too bloated.

It's how it works, I see no problem in creating extra_flags2 and even extra_flags3. Blizzard created unit_flags2 and unit_flags3.

Right now I have no idea how to reduce difference between CreatureDifficulty and creature_template_movement.
Maybe check all currently used rows, remove not needed values
Then select all with Ground=0, for example, pull them
Now you should select all with Flight, Swim and Rooted
And if you need to pull all with Rooted you need also to specify that can fall \ cannot fall by changing another values you already added
And all the time you want to select all with any of states, you will need to select and check also other states

Looks easy, right? Way much easier than having one flag for each thing and work with one flag at the same time.

> The template movement already supports basically all you need and yes, this table SHOULD have an entry for every single creature_template entry just like every single entry should have a creature_template_addon entry by default.

creature_template_addon should be removed. All emotes, stand states and auras are basically unique and most commonly used scripts.
Moreover `auras` is hack in general, it's not how it's supposed to work. All `auras` are AddAura and not Cast. Because of that you can't use channeling auras. And in sniffs tons of auras appear as Cast, actually I'm not sure if AddAura is really used.

> Having one giant table for everything like that is stupid and I'm actually for splitting creature_template even further to seperate sniffed query template data from all that custom stuff

I have nothing against it, why not

**Comment by offl** [comment]
And yeah, instead of adding CREATURE_DIFFICULTYFLAGS_WATER_BOUND to 100 creatures, you need to add 25000 rows in that table
That's why flags exists

**Comment by Shauren** [comment]
> And yeah, instead of adding CREATURE_DIFFICULTYFLAGS_WATER_BOUND to 100 creatures, you need to add 25000 rows in that table

What? If you need make 100 creatures not able to leave water, you would do exactly 100 inserts/updates into creature_template_movement

**Comment by offl** [comment]
Well, if you want to make it correctly with that system, you need to add Ground = 0 to 100 of them and Ground = 1 to the rest 25000 and never add 0 anymore because there are only 100 creatures which should not leave water

**Comment by Shauren** [comment]
You don't have to insert default entries, no row at all implies `Ground`=1, `Swim`=1,`Flight`=0,`Rooted`=0,`Chase`=0,`Random`=0

**Comment by Rushor** [comment]
That last Info of default values should be added to the Trinity wiki

**Comment by offl** [comment]
Correct name for Rooted is Sessile, difficulty flag is already name correctly
> Invisible Stalker (Floating, Uninteractible, Large, Sessile, Custom Phase 2)
