### ISSUE TITLE
DB/CreatureModelInfo: Add missing creature_model_info (Part 2)

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25792]
[creature_model_info.sql](https://pastebin.com/SShEHFE9)

Branch(es): master

TC rev. hash/commit:
TrinityCore rev. a68bc20b2426 2021-01-01 00:19:41 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

Operating system: Windows 10 Pro version 20H2, Version OS: 19042.662

**Comment by MaxtorCoder** [comment]
Please use a pastebin or some other code service for such a long query...

**Comment by illfated** [comment]
Fair enough. I have seen worse. ;) ^^

**Comment by osleyder85** [comment]
> 
> Please use a pastebin or some other code service for such a long query...

OK, I thought that with this format it could be.

**Comment by osleyder85** [comment]
@illfated I recommended it in a previous issue.

**Comment by illfated** [comment]
(ref. #25782)
