### ISSUE TITLE
 9.0.2 SetNativeDisplayId() function is not executed (or does not work correctly)

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#25793]
**Description:**

When trying to execute code using SetNativeDisplayId the player model does not change and is reset to the current one.
Perhaps there is a problem directly in the code, since it has not been updated since version 3.3.5. However, before the 9.0.2 update everything worked fine.

**Expected behaviour:**

When using the SetNativeDisplayId function, the player model should change to the set native model.

**Steps to reproduce the problem:**

1. Open player.cpp and change line 18142 as follows:
```
QueryResult result2 = CharacterDatabase.PQuery("SELECT morph FROM character_morph WHERE guid = %u", fields.guid);
    if (result2)
    {
        Field* fields2 = result2->Fetch();
        SetNativeDisplayId(fields2[0].GetUInt32());
        SetDisplayId(fields2[0].GetUInt32());
    }
    else
    {
        InitDisplayIds();
    }
```

2. Create a new table in the characters database
```
DROP TABLE IF EXISTS `character_morph`;
CREATE TABLE `character_morph` (
  `guid` int(10) NOT NULL DEFAULT 0,
  `morph` int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
3. Compile the project and run it
4. Create any character in the game
5. Go to the newly created character_morph table and enter your character's lowguid and displayid there (as an example, since this morph is native 15476)
6. Go into the game and make sure that the character does not change in any way (id 15476 should put a human skin on the character, regardless of race)

**Branch(es):**

master

**TC rev. hash/commit:** 

a68bc20

**Operating system:** Windows 10 64x

**Comment by Shauren** [comment]
Working as intended for blizzlike functionality (modifying DisplayID only).
