### ISSUE TITLE
Core/Spells: spell_gen_creature_permanent_feign_death should also add UNIT_FLAG_UNK_29

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25808]
According to sniffs spell_gen_creature_permanent_feign_death should also add UNIT_FLAG_UNK_29

**Branch(es):** 3.3.5
**TC rev. hash/commit:** 94c03b2107ad6603aaf185d58d63480e79c97e76

**Comment by illfated** [comment]
Related to (among many other creatures) our good old friend Monty, I suppose?
