### ISSUE TITLE
DB / Quest Shatterspear Laborers 

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#25801]
**Description:**

 [Quest : Shatterspear Laborers](https://www.wowhead.com/quest=13504/shatterspear-laborers) Quest ID : 13504 - the task cannot be completed ==>  NPC ID : 32 861 , MAP ID : 62 ,

**Expected behaviour:**

Shatterspear Laborers should do the work, see the [video ](https://youtu.be/87sVpn6tClM)
 instead, they seem to be dead - lying on the ground in Corpse mode

**Steps to reproduce the problem:**

1. go Darkshore  
2. .add quest 13504
3. arrive at the destination
4. find Shatterspear Laborers
5. see such as NPCs in Corpse mode

**Branch(es):**

 master 

**TC rev. hash/commit:** 
TrinityCore rev. 04712d879fd4 2021-01-02 17:56:30 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0l  10 Sep 2019 (library: OpenSSL 1.1.0l  10 Sep 2019)
Using Boost version: 1.72.0
Using MySQL version: 5.7.32
Using CMake version: 3.18.4
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1407968262 bytes
vmaps directory located in ./vmaps. Total size: 3264612627 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 837.20101

**Operating system:**   Windows 10.0.19042

**Comment by shamage** [comment]
@shdr212 - THANK YOU FOR YOUR EXCELLENT WORK

**Comment by illfated** [comment]
This ticket was closed on January 15, 2021, as a duplicate of issue ticket #25852, although maybe the other one should have been closed first.
