### ISSUE TITLE
DB/Creature: Ulduar - Rune of Power shouldn't enter in combat

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25811]
**Fix:**

```sql
-- Ulduar: Assembly of Iron - Rune of Power
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|0x00002000 WHERE `entry`=33705;
```

**Branch(es):** 3.3.5,

**TC rev. hash/commit:** 4ea64b515aa952662dce11fd1012c566ae0d2449

**Comment by illfated** [comment]
Maybe I have misunderstood, but is this the flag you have suggested above?

https://github.com/TrinityCore/TrinityCore/blob/aede11f8aa0c5774e95badd9aea323a45696a24c/src/server/game/Entities/Creature/CreatureData.h#L273

**Comment by Jildor** [comment]
yep, but after: https://github.com/TrinityCore/TrinityCore/commit/6440c3bcac85a40de5c34aef1d8a8856966cc140 is CREATURE_FLAG_EXTRA_NO_COMBAT

**Comment by offl** [comment]
I or Ovahlord can include this in PR if needed, better to not push it as separate commit

**Comment by illfated** [comment]
> yep, but after: https://github.com/TrinityCore/TrinityCore/commit/6440c3bcac85a40de5c34aef1d8a8856966cc140 is CREATURE_FLAG_EXTRA_NO_COMBAT

Thanks. I relied too much on the GitHub search feature, which mostly only returns C++ code from the `master` branch, not from 3.3.5.
