### ISSUE TITLE
DB/Spell: Added missing difficulty mode to Assembly of Iron spells (Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25812]
**Fix:**

```sql
-- Ulduar: Assembly of Iron - Rune of Death
DELETE FROM `spelldifficulty_dbc` WHERE `id`=62269;
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(62269, 62269, 63490);
-- Ulduar: Assembly of Iron - Overload
-- Overload 10 (61869) and 25 (63481) has same trigger spell effect 61878 (10 mode), it need set 63480 in 25 mode
DELETE FROM `spelldifficulty_dbc` WHERE `id`=61878;
INSERT INTO `spelldifficulty_dbc`(`id`, `spellid0`, `spellid1`) VALUES
(61878, 61878, 63480);
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 4ea64b515aa952662dce11fd1012c566ae0d2449

**Comment by offl** [comment]
Are you sure about second spell? https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=61878#triggered-by

**Comment by Jildor** [comment]
As I put in comments, two triggered spells (10 and 25) have 10mode trigger spell, so we need set 25 mode in 61878

**Comment by offl** [comment]
Will it work?

**Comment by Jildor** [comment]
Yep, I tested before open issue, trigger spell is a castspell, when you cast the 10mode spell in 25mode, you launch 25mode spell

**Comment by offl** [comment]
I or Ovahlord can include this in PR if needed, better to not push it as separate commit
