### ISSUE TITLE
DB/Quest : Lockdown! - Phasing does not work

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#25824]
**Description:**

Phasing does not work after job submission: Lockdown! - Quest ID: 14078 Phasing will not take place.
[video](https://youtu.be/7lbz741rHLc)

**Expected behaviour:**

After submitting the task, the player should automatically proceed to the next phase 
 [video](https://youtu.be/sPRnXrNDtJU)

**Steps to reproduce the problem:**

1. Create a worgen character  
2. .add quest 14078
3. pass the quest
4. monitor whether phasing has taken place
[ wowhead ](https://www.wowhead.com/quest=14078/lockdown)

**Branch(es):**   master

**TC rev. hash/commit:** 

TrinityCore rev. 04712d879fd4 2021-01-02 17:56:30 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.0l  10 Sep 2019 (library: OpenSSL 1.1.0l  10 Sep 2019)
Using Boost version: 1.72.0
Using MySQL version: 5.7.32
Using CMake version: 3.18.4
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1407968262 bytes
vmaps directory located in ./vmaps. Total size: 3264612627 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 837.20101

**Operating system:** Windows 10.0.19042

**Comment by shamage** [comment]
I have one tried and tested possible solution that works, however, please test whether it is correct. Well thank you.


```sql
UPDATE `creature_template` SET `npcflag` = 0 WHERE `entry` = 34884;
UPDATE `quest_template_addon` SET `ExclusiveGroup` = -14093 WHERE `ID` IN (14098, 14093);

```
```sql
DELETE FROM `conditions` WHERE `SourceEntry`=4756;
DELETE FROM `conditions` WHERE `SourceGroup`=170 AND `ConditionValue1`=14078;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(26, 169, 4756, 0, 0, 28, 0, 14078, 0, 0, 1, 0, 0, '', 'Phase 169 until Quest 14078 not complete'),
(26, 170, 0, 0, 0, 28, 0, 14078, 0, 0, 0, 0, 0, '', 'Phase 170 until Quest 14078 complete');
```


```sql
DELETE FROM `spell_area` WHERE `area`=4756;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `flags`, `quest_start_status`, `quest_end_status`) VALUES
(59073, 4756, 14078, 0, 0, 0, 2, 1, 64, 0), -- phase 170
(49416, 4756, 14078, 0, 0, 0, 2, 1, 64, 0); -- Generic Quest Invisibility 1
```

**Comment by tach-tm** [comment]
Yes, it doesn't work right now. I ran the scripts anyway.
game version: 9.1.5.42010
server version: TrinityCore rev. e8368ed2ebc7 2022-01-22 01:40:57 +0100 (master branch)

**Comment by mdX7** [comment]
> Would it make more sense to use SMART_EVENT_QUEST_COMPLETION to apply spell id 59073, instead of spell_area? The phase transition seems to linked to completing quest Lockdown! (quest id 14078) or accepting the follow up one Something's Amiss (14091).

If you relogg you wont trigger the sai action and do not get the phase in that case. Or imagine doing raid, die etc and come back 2y afterwards
