### ISSUE TITLE
DB/Templates: Update missing HoverHeight data for Stormcaller Brundir 25 mode (Ulduar)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25823]
**Description:**

Added here for 10 mode entry
https://github.com/TrinityCore/TrinityCore/commit/840e9594f41bd4fb0d0fa673712623d8b5e4500f

**Fix:**

```sql
-- Stormcaller Brundir (25)
UPDATE `creature_template` SET `HoverHeight`=10 WHERE `entry`=33694; 
```

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

4ea64b515aa952662dce11fd1012c566ae0d2449

**Comment by offl** [comment]
I'll apply massfix to reduce difference between difficulties

**Comment by illfated** [comment]
(ref. #25529 )
