### ISSUE TITLE
Worldserver Error

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#25835]
**Description:**

CHANGEME Worldserver Crashes upon Opening
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Worldserver starts with no issues (Hopefully)

**Steps to reproduce the problem:**

1. Start Worldserver

**Branch(es):**

Master

**TC rev. hash/commit:** 

DB2Stores.cpp:1417 in DB2Manager::LoadStores ASSERTION FAILED:
  TaxiMaskSize >= ((sTaxiNodesStore.GetNumRows() - 1) / 8) + 1 TaxiMaskSize is not large enough to contain all taxi nodes! (current value 336, required 337)

Looking at master code 

https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/DataStores/DBCEnums.h

Line 1332 needs changing

#define TaxiMaskSize 336

**Operating system:** Windows 10

**Comment by MaxtorCoder** [comment]
Follow the issue template.... It's there for a reason :)

**Comment by Jinnaix** [comment]
The issue template is there for a reason

**Comment by Spoony36** [comment]
Template now attached

**Comment by MaxtorCoder** [comment]
Please follow it correctly and attach the commit hash.

**Comment by Shauren** [comment]
working on it already
