### ISSUE TITLE
Invalid drop: Tangy Clam Meat

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#25844]
### It seems that this item should not be dropped in its pure form. Only on containers, like Giant Clam.

**Now we have:**

| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment |
|-------|------|-----------|--------|---------------|----------|---------|----------|----------|---------|
|  4633 | 5504 |         0 |      0 |             0 |        1 |       1 |        1 |        1 | NULL    |
|  4637 | 5504 |         0 |      0 |             0 |        1 |       1 |        1 |        1 | NULL    |
|  6354 | 5504 |         0 |    1.9 |             0 |        1 |       0 |        1 |        1 | NULL    |
| 16882 | 5504 |         0 |    0.6 |             0 |        1 |       0 |        1 |        1 | NULL    |
| 16883 | 5504 |         0 |    0.2 |             0 |        1 |       0 |        1 |        1 | NULL    |

Branch-3.3.5a 

<details>
  <summary>Links to item</summary>

[Wowhead Item 5504](https://www.wowhead.com/item=5504)
[Web.archive.org Item 5504](https://web.archive.org/web/20110625072801/http://www.wowhead.com/item=5504/tangy-clam-meat )
</details>

On site [Web.archive.org](https://web.archive.org/web/20110625072801/http://www.wowhead.com/item=5504/tangy-clam-meat) has an interesting comment by user FlamingMouse (2·11) on 2009/11/20 (Patch 3.2.2)

_Naga Run_
- Without killing nagas in water: 14 clams --> 14 Tangy Clam Meat and 0 Pearls.
- When killing nagas in water: 19 clams --> 18 Tangy Clam Meat and 1 Pearl.

_Murloc Run_
- Without killing murlocs in water: 56 clams --> 53 Tangy Clam Meat and 3 Pearls.
- When killing murlocs in water: 71 clams --> 65 Tangy Clam Meat and 6 Pearls.

**We consider it would be more correct to remove Tangy Clam Meat from all creatures**

```MYSQL 
DELETE FROM `item_loot_template` WHERE `Item`=5504;
```

removing an item from [Kolkar Scout](https://classic.wowhead.com/npc=4633/kolkar-scout)
removing an item from [Kolkar Destroyer](https://classic.wowhead.com/npc=4637/kolkar-destroyer)
_removing an item from 6354_
removing an item from Felblood Flayer
removing an item from Felblood Hungerer

**Comment by illfated** [comment]
TrinityCore AoWoW pages:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=5504#dropped-by:0-8+1
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=5504#created-by:0-17+1+13+3
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=58168
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=5524
- https://www.wowhead.com/spell=58168/thick-shell-clam
- https://www.wowhead.com/item=5524/thick-shelled-clam
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=58172
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=5523
- https://www.wowhead.com/spell=58172/small-barnacled-clam

**Comment by offl** [comment]
Thing is that loot is from bugged wowhead, when player targeted creature and opened item, addon treated it as 'dropped-from-creature'
But I don't remember what is the reason & how certain items were added to item loot

**Comment by offl** [comment]
I'd like to remove them from creatures but not from objects and items
Need to perform few more checks
