### ISSUE TITLE
DB/Locale/esES+esMX Line break at the end of the text

### ISSUE THREAD

**Issue by Cerveciento** [TrinityCore/TrinityCore#25848]
**Description:**
I am finding many texts with locale 'esES' or 'esMX' ending in '|n'. The client interprets it as a line break.
For example the quest 487, 1032, 1516, 1687, 1691, ...

From my point of view, there are 3 options.

1. Clean up trailing '|n'.
2. Change the '|n' to '$B' (Unify criteria)
3. Leave it as it is since it is not a major problem either

Any suggestion?

**Fix 1**
``` sql
-- Clean up trailing '|n'.
UPDATE `page_text_locale` SET `Text` = REPLACE(`Text`, '|n', ''), `VerifiedBuild` = 0 WHERE `Text` LIKE '%|n' AND `locale` IN('esES', 'esMX');
UPDATE `broadcast_text_locale` SET `Text` = REPLACE(`Text`, '|n', ''), `VerifiedBuild` = 0 WHERE `Text` LIKE '%|n' AND `locale` IN('esES', 'esMX');
UPDATE `quest_template_locale` SET `Details` = REPLACE(`Details`, '|n', ''), `Objectives` = REPLACE(`Objectives`, '|n', ''), `CompletedText` = REPLACE(`CompletedText`, '|n', ''), `VerifiedBuild` = 0 WHERE (`Details` LIKE '%|n' OR `Objectives` LIKE '%|n' OR `CompletedText` LIKE '%|n') AND `locale` IN('esES', 'esMX');
```
**Fix 2**
``` sql
-- Change the '|n' to '$B'
UPDATE `page_text_locale` SET `Text` = REPLACE(`Text`, '|n', '$B'), `VerifiedBuild` = 0 WHERE `Text` LIKE '%|n' AND `locale` IN('esES', 'esMX');
UPDATE `broadcast_text_locale` SET `Text` = REPLACE(`Text`, '|n', '$B'), `VerifiedBuild` = 0 WHERE `Text` LIKE '%|n' AND `locale` IN('esES', 'esMX');
UPDATE `quest_template_locale` SET `Details` = REPLACE(`Details`, '|n', '$B'), `Objectives` = REPLACE(`Objectives`, '|n', '$B'), `CompletedText` = REPLACE(`CompletedText`, '$B', ''), `VerifiedBuild` = 0 WHERE (`Details` LIKE '%|n' OR `Objectives` LIKE '%|n' OR `CompletedText` LIKE '%|n') AND `locale` IN('esES', 'esMX');
```
**Fix 3**
All done.
In almost all cases, the text comes from a sniffer.

**Expected behaviour:**

Texts without final line break,.... or not

**Branch(es):** 3.3.5
**TC rev. hash/commit:** f6b22df9bd22
**Operating system:** debian 10

**Comment by offl** [comment]
```sql
UPDATE `broadcast_text_locale` SET
```
We don't update that table

**Comment by offl** [comment]
> ending in '|n'. The client interprets it as a line break.

Any example of how it looks in game?

**Comment by Cerveciento** [comment]
I can't reproduce it again.
An error of appreciation on my part? I do not know what to say.
I'm sorry. 
Keep investigating.

**Comment by illfated** [comment]
I can only try to guess what caused your issue. Maybe something wrong with viewing format or data reading format issues, maybe.

**Comment by Cerveciento** [comment]
I think they are poorly prescription glasses. XD
