### ISSUE TITLE
DB/Quest: The Battle for Arathi Basin! & Arathi Basin Resources!

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25845]
**Description:**

Both these following Alliance quests are displaying all level variants and should only be showing current eligible one:

[The Battle for Arathi Basin!](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8105) given by:
[Field Marshal Oslight](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=14983)

[Arathi Basin Resources!](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8297) given by:
[Sergeant Maclear](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=14984)

<details>

![image](https://user-images.githubusercontent.com/66294837/104398786-8687a980-55a3-11eb-84f3-57e73908040c.png)

![image](https://user-images.githubusercontent.com/66294837/104398894-bfc01980-55a3-11eb-95cf-434ca3b2c590.png)

</details>

**Disclaimer:** I have not tested Horde

**Expected behaviour:**

Both of these quests should only be showing 1 option only - the current one matching level requirements and appropriate rewards.

[The Battle for Arathi Basin Variants](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=The+Battle+for+Arathi+Basin)

[Arathi Basin Resources! Variants](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Arathi+Basin+Resources%21)

**Steps to reproduce the problem:**

1. Have a high level Alliance character
2. Make your way to Arathi Highlands (roughly 45, 45)
3. NPCs are both near the entrance to the Arathi Basin Battleground
   (Optional) Set your mini map to display low level quests 
4. All available and past quest options will appear

**Branch(es):**
3.3.5

TC rev. hash/commit:
TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**
Windows 7 Ultimate x64 SP1

**Comment by illfated** [comment]
Fair point. I have noticed those quest lists myself, feeling uncertain what to think, but never knowing exactly how they should appear. Thank you for opening a ticket for them.

I am also thinking this could be a similar issue for the AV and WSG quests, as seen from the Horde side.
