### ISSUE TITLE
Core/Creature: Caverndeep Burrower (Gnomeregan) stops short of player distance

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25856]
**Description:**

Inside Gnomeregan, the [Caverndeep Burrower](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6206) attacks and **approaches player** _but_ stops a few feet away.

Player needs to move in closer to Creature to continue melee combat or can just kill from a distance - creature wont move.

<details>

Creature stops approaching character at this distance - you can kill it with ranged and it wont hit back.

![image](https://user-images.githubusercontent.com/66294837/104792195-baf0a500-57f1-11eb-8dbc-eff79d62d157.png)

Backpeddling, the Creature remains in it's spot and does not move.

![image](https://user-images.githubusercontent.com/66294837/104792293-01460400-57f2-11eb-910d-5a5e515575f6.png)

You can even stay seated whilst mid contact and it will not move if out of range.

![image](https://user-images.githubusercontent.com/66294837/104792526-ca242280-57f2-11eb-8f3d-acb67fbfebe0.png)

Creature requires that you are within melee range of it's original stopping position when it first stopped.

![image](https://user-images.githubusercontent.com/66294837/104792380-4ff39e00-57f2-11eb-8485-e1f4631537f4.png)

</details>

**Expected behaviour:**

Creature should approach entire distance and engage in combat with player; additionally following player if necessary.

**Steps to reproduce the problem:**

1. Enter Gnomeregan Dungeon  
2. Engage in combat with nearby mobs - they will approach and attack - exception is Caverndeep Burrower which will stop short of reaching you
3. If you move from that spot, Creature wont follow 
4. To continue melee combat, walk closer to creature / For ranged, you can (but shouldnt') attack from a distance and you wont get hit

I found no supportive evidence during my research that this was expected behaviour. 

**Branch(es):**
3.3.5

TC rev. hash/commit:
TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**
Windows 7 Ultimate x64 SP1

**Comment by Jinnaix** [comment]
Can confirm.
This smelled like https://github.com/TrinityCore/TrinityCore/issues/17563 but it isnt.
Second thing i thought was, that there is something wrong with creatures getting called from chain aggro, but that wasnt it either.
And it seems to be specific for NPC ID 6206 and 6329 - i did several tries with other creatures in different areas & dungeons.
I also thought that Aura/Spell 9798 might be causing this, but it seems unrelated at first glance.
Im not really sure what exactly is happening here.

NPC 6329: he will deny to attack in meele unless he is out of mana. As soon as he is oom, there is a delay of 6-7 seconds where he will stand still and does nothing. After that, he starts moving and attacks his target.

NPC 6206: on aggro, he will move up to the point where the attacker was when he got triggered. After reaching that point, he will stand still for the rest of the fight. This only happens for the very first time. If you let him evade (for example turn gm on and off) and try to repeat it, he will be instantly stucked at his current position.

@TQPS thanks for your very detailed issues lately. Could i ask you to include the command ".npc info" in your screenshots when pointing at a specific creature? Makes it easier to find it later if we also see the spawnID :)

![image](https://user-images.githubusercontent.com/37972361/104807660-d30bf880-57e0-11eb-93ff-92253243c467.png)

**Comment by illfated** [comment]
Can't say that I noticed this in particular, but I usually kept moving to get into distance, without thinking much about if those NPCs moved in or not. It has also been more than 2 weeks since I last played in there. I only noticed that those NPCs often cast their radioactive fallout debuff on the player character.

**Comment by offl** [comment]
> NPC 6329: he will deny to attack in meele unless he is out of mana. As soon as he is oom, there is a delay of 6-7 seconds where he will stand still and does nothing. After that, he starts moving and attacks his target.
>
>NPC 6206: on aggro, he will move up to the point where the attacker was when he got triggered. After reaching that point, he will stand still for the rest of the fight. This only happens for the very first time. If you let him evade (for example turn gm on and off) and try to repeat it, he will be instantly stucked at his current position.

>When in combat, After 3 sec – 5 sec Repeat every 10 sec – 11 sec | Cast  Radiation Bolt at random player within 50m. **Combat movement**
When in combat, After 2 sec – 4 sec Repeat every 4 sec – 6 sec | Cast  Radiation at current target. **Combat movement**
