### ISSUE TITLE
Core/Command: npc add #entry command does not work for Shadowlands creatures 9.0.2

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25866]
**Description:**
When trying to add a Shadowlands creature to the game, it throws the following error:
![error](https://user-images.githubusercontent.com/15787347/104831705-549f6d00-5859-11eb-9c4f-3a0ec52161ff.jpg)
This only occurs with creatures from Shadowlands and some from Battle for Azeroth.

**Steps to reproduce the problem:**

1. create any player.
2. use command: .npc add entry 
You can use any of the entries provided below:(158544,158547,158555,160448,160963,160997,161378,161492,161603,162541,162838,162839,162842) Shadowlands
(154421,154423,154424,154425,154434,154443,154461,154462,154499,149805,150123,150553,151000) BFA

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 28d470c50ef6 2021-01-15 15:47:59 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)
Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.75.0
Using World DB: TDB 837.20101
Using enUS DBC Locale
Client cache version set to: 20101
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps

**Operating system:** 
Windows 10 Pro. Version: 20H2

**Comment by MaxtorCoder** [comment]
Is `creature_template` up-2-date?

**Comment by osleyder85** [comment]
Yes, they are all in creature_template.

```sql
SELECT `entry`, `name`, `subname`, `minlevel`, `maxlevel`, `HealthScalingExpansion`,`faction`, `VerifiedBuild ` 
FROM `creature_template` WHERE `entry` IN 
(158544,158547,158555,160448,160963,160997,161378,161492,161603,162541,162838,162839,162842);
```
![sd](https://user-images.githubusercontent.com/15787347/104832202-6be05980-585d-11eb-81a2-9eb3d588c2ca.jpg)

And also I have the updated repository:
TrinityCore rev. 28d470c 2021-01-15 15:47:59 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Comment by MaxtorCoder** [comment]
Seems to be always wanting a Hyperlink (the in-game linking system): https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Commands/cs_npc.cpp#L364

**Comment by Aokromes** [comment]
i vote bad model, faction or something else.

**Comment by MaxtorCoder** [comment]
> i vote bad model, faction or something else.

It would've said so in World Server console. So it's probably just the code.

**Comment by Aokromes** [comment]
i remember this "bug" when adding other expansions creatures on early stages.

**Comment by illfated** [comment]
Any chance you can find relevant error lines in DBErrors.log for this case?

**Comment by Spoony36** [comment]
Creature (Entry: 154198) has non-existing faction template (0). This can lead to crashes, set to faction 35.

Table `creature` has creature (GUID: 339361) has unsupported difficulty 3 for map (Id: 720).

No model data exist for `CreatureDisplayID` = 93484 listed by creature (Entry: 163278).

Creature (Entry: 1756) has invalid model 99950 defined in table `creature_template`, can't load.

I too noticed that you couldn't spawn SL creatures, DBerror file has literally thousands of these lines so i'm thinking data missing from DB

**Comment by Aokromes** [comment]
not a bug then

**Comment by illfated** [comment]
> not a bug then

Yeah, more like a "Not yet implemented" case. Needs a lot more work on the DB content and related scripting to resolve this kind of issue, but currently not available in TC.
