### ISSUE TITLE
tele name <player> npcid / npcguid <id/guid>

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25870]
**Description:**

tele name (player) npcid / npcguid (id/guid)
example:

tele name aokromes npcid 10000
or
tele name aokromes npcguid 1000

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0b7b7f1

**Operating system:** 

N/R

**Comment by illfated** [comment]
Wouldn't it be more appropriate to modify the `.appear` command to include the ID/GUID parameter?

```
appear  Syntax: .appear [$charactername]

        Teleport to the given character. 
        Either specify the character name or click on the character's portrait,
        e.g. when you are in a group. 
        Character can be offline.
```

**Comment by Jinnaix** [comment]
What aokromes wants here is to teleport any player to a specific npc without first teleport to that creature as gm and then summon the player afterwards. Also being able to do this from console would be nice too.

**Comment by illfated** [comment]
Oh. I see. Did not think about that scenario. Very well, that makes my comment above redundant.

**Comment by Shauren** [comment]
.tele name npc id [player name] [creatureid]
.tele name npc id [player name] [guid]
.tele name npc id [player name] [creature name
