### ISSUE TITLE
Mapextractor doesnt extract file 0000_43_31

### ISSUE THREAD

**Issue by matkhl** [TrinityCore/TrinityCore#25882]
**Description:**

worldserver.exe closes after startup, because the .map file 0000_43_31.map is missing

**Expected behaviour:**

The map extractor should extract the file with the name 0000_43_31.map

**Steps to reproduce the problem:**

1. Build the newest version of TrinityCore with vs
2. copy the mapextractor to the wow.exe folder
3. run the mapextractor

**Branch(es):**

master

**Operating system:** 

Windows 10

**Description**

The worldserver log file says following:

Map file 'C:\Program Files\Trinity\Build\bin\Release/maps/0000_43_31.map' does not exist!
Please place MAP-files (*.map) in the appropriate directory (C:\Program Files\Trinity\Build\bin\Release/maps/), or correct the DataDir setting in your worldserver.conf file.
Unable to load critical files - server shutting down !!!

Some people had the same error like me, but they all found the file in the maps folder.
I dont find the missing file. The strange thing is, that the file with the previous and the following number do exist.

![image](https://user-images.githubusercontent.com/38809570/104858103-2edb9c00-591d-11eb-9d7b-dd4ecbf1050b.png)

I tried to delete the maps folder and extract again, but the same behaviour. I also tried to just delete the files that end with 30 and 32. They get regenerated, but number 31 is still missing.

I tried to copy number 30 or 32 and rename it to 31. Then the worldserver process continues but crashes with a more complicated error -> so that doesnt fix it.

I hope someone can solve that problem for me and all the users that have the same error in the future. Thanks!

**Comment by Faq** [comment]
For what client version and language this is used?

**Comment by matkhl** [comment]
I am using the english client version 9.0.2.37176.

**Comment by illfated** [comment]
`C:\Program Files\Trinity\Build\bin\Release/maps/` — looks like you could do yourself a favor by moving the build folder to a non-system directory instead, like for example `C:\Trinity\Build\` or similar, to avoid having to run the map extractors as local Administrator.

Myself, I use the folder `C:\Trinity\` for the /src/ and /build/ subdirectories, only using `C:\Program Files\` to install the complete core as a "server software package".

**Comment by matkhl** [comment]
Thanks for the tip. I solved the problem by building Trinity in RelWithDebugInfo and duplicating file Nr 30 and renaming it to 31.

**Comment by illfated** [comment]
Looks like a useful workaround, even though I would not name it a real solution as such.

Anyway, this seems more like a game client issue than a source issue, would you agree?

**Comment by matkhl** [comment]
Yes of course.

**Comment by illfated** [comment]
OK, very well. I recommend that we close this ticket, unless there are any other leads here for a source code issue.
