### ISSUE TITLE
Spell Aura PREVENTS_FLEEING doesn't prevent fears

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#25884]
**Description:**
Spells that use this aura, typically Curse of recklessness or the old judgement of justice in older versions also give immunity to fear effect. Blizzard has always used this aura to prevent both assistance and fear mechanic.
Currently in TC it only prevents the "get assistance mechanic", typically humanoids fleeing at low health.

Very few spells still use this aura in Wotlk(5 total) but this is the example of one of them used by a stonetalon harppy 
https://wotlkdb.com/?spell=16231
description : "Cursed enemies will ignore fear effects and refuse to flee from combat." and that's how curse of reck works in classic.
Currently this aura only prevents the "Get assistance" mechanic.
_void Creature::DoFleeToGetAssistance()_

This works in some other emus because the "Get assistance" is considered a fear in them. Dunno if it is correct or not but this aura works properly.

**Expected behaviour:**

The aura should prevent fear effects.

**Steps to reproduce the problem:**

1. Fight a bloodfury slayer harpy in stonetalon, wait 15sec for it to cast the curse. Or self apply the curse with .aura 16231
2. self apply a fear effect with .aura 5782
3. Notice it doesn't prevent fears

**Branch(es):**

CHANGEME 3.3.5

**TC rev. hash/commit:** 

cdfa85957e2726472f8afa70c66a7dfe57cf8ca6

**Operating system:** 

windows 10

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/104871141-9eb44b80-594a-11eb-8ba3-e9ee1ebd8381.png)
Here's a list of the spells that use this aura

**Comment by Jinnaix** [comment]
That spell flag does exactly what it says and should do, it prevents flee, not fear.
Taken from patch 3.0.2 notes:
>Wrath of the Lich King Patch 3.0.2 (2008-10-14): Curse of Recklessness will no longer prevent Fear effects, only prevent NPCs from fleeing (e.g. at low health).

However, you can alter spelleffects with a spell script and let a spell apply different or additional flags.

**Comment by T1ti** [comment]
Yep it's a WOTLK change apaprently, thank you for pointing that out
So the harpy spell is just blizzard forgetting to update the tooltip :D
