### ISSUE TITLE
Core/Profession: Matrix Punchograph 3005 devices not giving Engineering Schematics (Gnomeregan)

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25881]
**Description:**

Inside Gnomeregan, Engineers can acquire schematics from 2 of the Matrix Punchograph 3005 machines - B and D.

Matrix Punchograph 3005-B is not offering player to learn the hidden schematic.

Matrix Punchograph 3005-D is not giving player [Schematic: Discombobulator Ray](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=4413) upon accessing even if skill level and required [Security DELTA Data Access Card](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=9327) are held.

Additionally, I don't believe this schematic is supposed to drop from the mobs listed in DB either.

[Dropped by Trinity DB](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=4413#dropped-by)

[Drobbed by Live](https://www.wowhead.com/item=4413/schematic-discombobulator-ray#dropped-by)

[Dropped by Classic](https://classic.wowhead.com/item=4413/schematic-discombobulator-ray#dropped-by)

Meaning the drop hasn't changed over the years.

This schematic is exclusive to Gnomeregan by the method mentioned previously or by last boss.

**Expected behaviour:**

Matrix Punchograph 3005-B is supposed to offer [Schematic: Minor Recombobulator](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=14639) if your Engineering skill is 140+ - it's an auto-learn, not a item to the inventory.

<Details>

![image](https://user-images.githubusercontent.com/66294837/104857436-b6043080-596c-11eb-8787-b3ab25e8c091.png)

</details>

Matrix Punchograph 3005-D is supposed to automatically give you (no clicking required) [Schematic: Discombobulator Ray](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=4413) (again auto-learn) upon using the red punch card if the player has [Security DELTA Data Access Card](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=9327) in their inventory and their Engineering skill is 160+.

This schematic should not be dropped from all the mobs currently listed in the DB.

**Steps to reproduce the problem:**

1. Head to Gnomeregan and acquire White Punch card from mobs outside of instance (random drop) and use it on Matrix Punchograph 3005-A located in same area to get Yellow Punch card (or just give yourself one)
2. Now enter Gnomereagan and go to Domitory and access Punchograph 3005-B and you will get a Blue Punch card
3. At this point, Engineers with a skill of 140+ **_should_** be given an additional option to obtain a hidden schematic.
4. Progress in instance
5. Go to Matrix Punchograph 3005-C located in the Launch Bay and acquire Red Punch Card (Boss: Electrocutioner 6000 is here)
6. By now you may have found a Security DELTA Data Access Card - if not give yourself one (item 9327)
7. Finally, access the Matrix Punchograph 3005-D in the Engineering Labs - with the DELTA card and 160+ skill you **_should_** be given a Prismatic card along with auto-learning the Schematic: Discombobulator Ray.

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by illfated** [comment]
Good research. Thank you. I was not aware of these details, but then again, Gnomeregan was never one of my favorite instances.

**Comment by offl** [comment]
I have scripts, gossips, conditions and all other stuff but with custom gossip ids
If anyone can share gossip stuff from classic sniffs, I can finish my scripts

**Comment by offl** [comment]
Would be nice if schematics part will be tested again because I guess I was able to learn schematics only after manually learning and unlearning them
Maybe I just learned profession wrongly or something like that

To make options visible
.addi 9280
.addi 9327
.addi 9281
Of course also requires engineering 160+

**Comment by illfated** [comment]
@TQPS : Maybe you or any of your friends would like to test it, now that this C++ script conversion to SAI commit has been published.

**Comment by offl** [comment]
Nvm

**Comment by TQPS** [comment]
Rebuilding now to test. 

All testing is done via normal gameplay. 

Only thing I noticed is no change to the drop for Schematic: Discombobulator Ray. Are we leaving those as they are? Supposed to be limited to Gnomeregan. I posted the research in the description.

I'll reach back after building and testing re the Matrix changes.

**Comment by offl** [comment]
There was a mistake, fixed with last commit

**Comment by TQPS** [comment]
Can confirm everything is working as intended. Was able to acquire both schematics through normal game play options provided I had the level requirements and held the appropriate items.

A bonus is that you also fixed the issue with the dialogue box coming on up Matrix-A even if you didn't have a white punch. So thanks for that.

I tested getting the prismatic card before the schematic as well and results were as expected - you could no longer get schematic.

Thanks so much for this fix. Awesome job!!

**Comment by offl** [comment]
Nice, you're welcome
