### ISSUE TITLE
Inn Keepers Not working Properly

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#25888]
**Description:**

Innkeepers do not allow you to set your hearthstone to that location

**Expected behaviour:**

You should be able to set your hearthstone to that location

**Steps to reproduce the problem:**

1. Visit any innkeeper
2. Open Gossip Option
3. Choose the 'Make this inn your home' option
4. Nothing Happens :D

**Branch(es):**

Master

**TC rev. hash/commit:** 

"TrinityCore rev. 2721cd41dfa9 2021-01-16 	"TDB 837.20101"	"20101"

**Operating system:** 

Windows 10

**Comment by Faq** [comment]
Any particular innkeeper you checked?

**Comment by Spoony36** [comment]
I tried the one in Stormwind and then in Ironforge and then spawned several others. Seems like all are broken, well at least for me
