### ISSUE TITLE
[Core / Tools] Error opening file. Bad Format

### ISSUE THREAD

**Issue by DerEnderman** [TrinityCore/TrinityCore#25891]
**Description:**
![https://i.imgur.com/JP4EiDI.png](https://i.imgur.com/JP4EiDI.png)
I try to extract osme files with the extractors but there are some issues

**Expected behaviour:**

I think we would be able to export some files that are needed to run server.

**Steps to reproduce the problem:**

1. Try to use vmapextractor and see results

**Branch(es):**

master

**TC rev. hash/commit:** 

bb24c6a11b24

**Operating system:** 

Windows 10

**Comment by MaxtorCoder** [comment]
Are you using the correct client version?

**Comment by DerEnderman** [comment]
Yes i do. I use version : 9.0.2 (37176) I rechecked and i use en-us / de-de languages

**Comment by MaxtorCoder** [comment]
Sounds like a weird bug to me, idk if it's normal or not. Maybe wait for Shauren to answer.

**Comment by Shauren** [comment]
There should be no bug in extractor, this is my output https://gist.githubusercontent.com/Shauren/4e7b8ef263391bb3673f2170c788afea/raw/773b8a81351584e995cd54d92f737eb89093f788/vmap4extractor.log

**Comment by DerEnderman** [comment]
And how i am able to fix this?

**Comment by illfated** [comment]
@DerEnderman : Looks like you have one or more client computer software & access issues. You need to store both your game files and extractor files in non-system folders and make sure that the extraction processes don't get hindered by incorrectly configured "security" software and stuff like that.

Use stand-alone folders like `C:\Temp\` or `C:\Trinity\` or `C:\Local\` etc. or even removable storage like USB thumb drives.

**Comment by DerEnderman** [comment]
Issue was fixxed by reinstalling wow :D
