### ISSUE TITLE
Wrong position of objects

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#25898]
Some objects are out of place. Can I try to move them or is this a bug in the client?

<details>

![изображение](https://user-images.githubusercontent.com/77268574/105225131-31353480-5b6f-11eb-87fb-1fac84ab673e.png)

![изображение](https://user-images.githubusercontent.com/77268574/105225084-22e71880-5b6f-11eb-8d80-03f6e3d9a57c.png)

![изображение](https://user-images.githubusercontent.com/77268574/105225111-29759000-5b6f-11eb-881c-fc403b4cd8ec.png)

![изображение](https://user-images.githubusercontent.com/77268574/105225119-2c708080-5b6f-11eb-8b1b-889ef3fd3b1e.png)
</details>

3.3.5
Ubuntu x64
Rev. b86b21a

**Comment by Aokromes** [comment]
.gobj near if it returns something you may fix them, if no, client bug.

**Comment by gygyti** [comment]
it seems these are all errors in the client

**Comment by offl** [comment]
What are coords from .gps ?

**Comment by gygyti** [comment]
> 
> 
> What are coords from .gps ?

these are all boats in Stormwind. Any boat is out of place

**Comment by TQPS** [comment]
I've typically seen this when importing WOD+ model/textures - boats don't align.

**Comment by illfated** [comment]
> these are all boats in Stormwind. Any boat is out of place

Yes, it is more or less a known issue, but if I recall correctly, it has been discussed before (possibly in IRC, I could not find the exact details in closed issue tickets), so it is very likely that it is a client issue. Check it yourself by going near one of the boats and use the GM command `.gobject near` to see if it shows any gameobject available for rotation. Unless you find the gameobjects and their values which could be modified in the DB, this will remain a game client issue.

**Comment by TQPS** [comment]
I believe this occurs if you add in additional Client textures (WOD textures for 3.3.5 for example). Only occurs to boats.

**Comment by Ovahlord** [comment]
These aren't server bugs. These are clientside objects so either this is a blizzlike bug or you broke your client by modding it to oblivion.

**Comment by offl** [comment]
For future

\<Offle> that boat and canoe are located in wrong place https://wowpedia.fandom.com/wiki/Grezzix_Spindlesnap?file=Grezzix_and_Crew.jpg
\<Offle> but they're not gameobjects
\<Aokromes> client bug maybe fixed on later expansions
\<Offle> it's not first boat
\<Offle> maybe it's only my client
\<Aokromes> i remember someone reported that on stormwind too
\<Offle> looks fine in 2008 screenshots
\<Aokromes> can you tell me go xyz or something?
\<Offle> .go c id 24767
\<Aokromes> https://i.imgur.com/99nkie3.jpeg
\<Offle> damn
\<Aokromes> Cataclysm Patch 4.0.3a (2010-11-23): Model updated.
\<Aokromes> maybe that's "fixed ships"
\<Offle> doubt, looks like they broke all similar boats
\<Aokromes> https://wow.zamimg.com/uploads/screenshots/normal/179928-grezzix-spindlesnap-yaaarrrrr.jpg
\<Aokromes> 2010
\<Aokromes> bugged
\<Offle> ty
