### ISSUE TITLE
Changing gender breaks character model

### ISSUE THREAD

**Issue by Omnidraxus** [TrinityCore/TrinityCore#25899]
After change character gender with command .modify gender character's model breaks.
Change gender with commands .character customize/changerace/changefaction don't work and leads to client creation error.

**Steps to reproduce the problem:**

1. Join Game, 9.0.2 client
2. Type .mod gender
3. Logout to character select screen
4. See your character model breaks
5. Try to change gender to opposite in customization menu
6. Getting client creation error

**Branch(es):**

master

**Operating system:** 

Windows 10

**Comment by MaxtorCoder** [comment]
Reference to #25742 ?

**Comment by Omnidraxus** [comment]
> Reference to #25742 ? Sort of I guess?

Changing gender with barbershop works fine, unlike commands

**Comment by Faq** [comment]
You still did not provide commit hash.

**Comment by illfated** [comment]
Yes, it would be good to have the commit rev. hash specified, so we can track the development of this issue ticket and possible solutions.

**Comment by matanshukry** [comment]
I can verify it's happening on latest, commit hash `1a12c0b1aebf1e2cb21f6c344bb43bb6f6094cdc`.

One note though: the customization menu does work, and the client will disconnect if you try to login without using it.

**Comment by matanshukry** [comment]
I took a look at the difference between the barber and the gm command and found out the issue was the customization.
The customization for female and male are different; at the barber shop the client sends the full customization, but through the gm command we are not changing it, so the model stays with the other gender customization which aren't compatible.
 
Created a PR that solves this.

**Comment by illfated** [comment]
Note: if you let GitHub read & modify the appearance of the commit hash by not adding MD backtick encapsulation, the syntax highlighting and linking will be added automatically: 1a12c0b1aebf1e2cb21f6c344bb43bb6f6094cdc

**Comment by matanshukry** [comment]
> Note: if you let GitHub read & modify the appearance of the commit hash by not adding MD backtick encapsulation, the syntax highlighting and linking will be added automatically: [1a12c0b](https://github.com/TrinityCore/TrinityCore/commit/1a12c0b1aebf1e2cb21f6c344bb43bb6f6094cdc)

Did not konw that; awesome!
