### ISSUE TITLE
Core/SpawnGroup: Phase 2: SPAWN_FLAG_NO_RESPAWN

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#25894]
**Description:**

For example we want to temp spawn creature only once without allowing it to respawn. Currently to achieve it we need to spawn SpawnGroup and despawn it after creature is killed. Each time for each creature.
Or we need to change respawn time to prevent respawn. But it's something evil

**Expected behaviour:**

We need new flag SPAWN_FLAG_NO_RESPAWN to spawn creature only once without trying to make it respawn after kill. That flag should be used for 95% of temp spawned creatures or objects

**Branch(es):** both
**TC rev. hash/commit:** 4c0a8ad3b3f9960fa15504cf32a84218807ac9d5

**Comment by Ovahlord** [comment]
Uh, tempoarily summoned creatures do not respawn. If you want to use creatures that you use just once (like for events) you need creature_summon_groups, not spawn_groups. Spawn Groups are for DB based spawns only.

**Comment by offl** [comment]
This is why I wrote explanation of what spawn groups actually are in #25893

**Comment by Shauren** [comment]
I understand what you are trying to do here - per guid scripting for "summoned" creatures

**Comment by offl** [comment]
Not only scripting but also allowing creature to use all systems such as formations, waypoints, everything inside `creature` table
Those systems actually all are linked to spawn groups according to [screenshot](https://www.gamersglobal.de/sites/gamersglobal.de/files/userupload/user131/wowedit_1024.jpg) (looks like pooling is `Random Locations`, `Spawn Event List` (probably creatur_addon, guid scripts, probably waypoints), `Call For Help String ID` is probably related to formations)
It doesn't mean they all are inside one big table, of course

There are temporary 'summoned' creatures which actually can respawn if spawn group is still active. One quest with that kind of spawn group already implemented and there should be more

**Comment by offl** [comment]
This should be not Phase 1 but phase 20 or 30
