### ISSUE TITLE
Core/Boost: Visual Studio messages during TC compilation.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25908]
**Description:**
During the compilation of the server, Visual Studio throws this message 3 times:
```
C: \ local \ boost_1_75_0 \ boost / detail / iterator.hpp (13): message: This header is deprecated. Use <iterator> instead.
```
**Steps to reproduce the problem:**

1. Compile repository.  

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 1a12c0b1aebf 2021-01-21 22:30:40 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)
Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.75.0
Using World DB: TDB 837.20101
Using enUS DBC Locale
Client cache version set to: 20101
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps

**Operating system:** 
Windows 10 Pro 20H2

**Comment by Shauren** [comment]
It comes deep from boost itself, not much we can do about it, its not included by TC directly

**Comment by matanshukry** [comment]
Found the issue on the boost project:
https://github.com/boostorg/graph/issues/228

**Comment by Shauren** [comment]
As usual, boost is super slow to merge/release merged fixes

**Comment by illfated** [comment]
The message looks like this in 3.3.5, Release build, Microsoft Visual Studio Community 2019 Version 16.8.3:
```cpp
14>C:\local\boost_1_74_0\boost/range/result_iterator.hpp(20): message : This header is deprecated. Use <boost/range/iterator.hpp> instead.
14>C:\local\boost_1_74_0\boost/range/const_reverse_iterator.hpp(20): message : This header is deprecated. Use <boost/range/reverse_iterator.hpp> instead.
14>C:\local\boost_1_74_0\boost/range/reverse_result_iterator.hpp(20): message : This header is deprecated. Use <boost/range/reverse_iterator.hpp> instead.
```
(just in case anyone else searches for this message content at a later time)
