### ISSUE TITLE
9.0.2 - (Priest) Mass resurrection does not work

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#25900]
**Description:**

Mass resurrection does not resurrect players in a group, nor does it resurrect anyone at all.

The spell has 2 effects, namely:
SpellEffect - 173 (EffectResurrectWithAura) = implemented and working
SpellTarget - 119 (TARGET_CORPSE_SRC_AREA_RAID) = partially implemented, but does not work in the spell

**Expected behaviour:**

If the player is in a group and is dead, mass resurrection should prompt the dead player to respawn

**Steps to reproduce the problem:**

1. Create any character as a priest class
2. Invite another ally player to the group
3. The invited player must die and not leave the body
4. Player priest must use Mass Resurrection

**Branch(es):**

master

**TC rev. hash/commit:** 

bb24c6a

**Operating system:** 

Windows 10 x64

**Comment by illfated** [comment]
Thank you for filling in the required information in this ticket. 
Is this the spell ID 212036 ?
- https://www.wowhead.com/spell=212036/mass-resurrection

**Comment by Fabi** [comment]
> Thank you for filling in the required information in this ticket.
> Is this the spell ID 212036 ?
> 
> * https://www.wowhead.com/spell=212036/mass-resurrection

Yes it is

**Comment by matanshukry** [comment]
@DintyGadget I'm not sure if that changed recently, but looking at the current code EffectResurrectWithAura is actually 172 (and not 173).

Also, as far as I can tell TARGET_CORPSE_SRC_AREA_RAID is implemented correctly.
The actual issue is different. You can see the linked PR for more info
