### ISSUE TITLE
Clean up creature addon data

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#25907]
Description:

Move addon data from creature_addon to creature_template_addon for all creatures with one spawn.
[fix addon.zip](https://github.com/TrinityCore/TrinityCore/files/5852205/fix.addon.zip)

Tested on clean TDB_full_world_335.21011_2021_01_15.sql

Expected behaviour:

No change in behaviour. Cleanup

Steps to reproduce the problem:
[fix addon.zip](https://github.com/TrinityCore/TrinityCore/files/5852196/fix.addon.zip)

Does not cause game issues.

Branch(es):

335

Core Revision

Core: bb24c6a
DB: TDB 837.20101

Operating system:

Win 10 x64

**Comment by Rushor** [comment]
nice
