### ISSUE TITLE
Pvp talents tree not showing up

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#25918]
**Description:**
I logged in the game and leveld the character, but the expansion part of the talents where the pvp talents should be aren't there.
I even get the annoying tooltip above the talents button saying I have a pvp talent slot available.

Attached a photo showing the talent window without the pvp talents part.
![image](https://user-images.githubusercontent.com/5613042/105566672-1a8d0a00-5d36-11eb-8db8-c832208333d2.png)

**Expected behaviour:**
Players can choose a pvp talent. 
Further explanation and picture on how to access the pvp talent tree: https://wow.gamepedia.com/PvP_talent

**Steps to reproduce the problem:**

1. Login in the game
2. Level the character up enough so he should be able to access both talents and pvp talents (e.g. `.level 30`)
3. Open the talents tree and note you can't access the pvp talent tree

**Branch(es):**

Master

**TC rev. hash/commit:** 

`1a12c0b1aebf1e2cb21f6c344bb43bb6f6094cdc`

**Operating system:** 

Windows 10

**Note:**

This probably require a change in the communication protocol. Perhaps adding a tag for such cases can be useful.

**Comment by MaxtorCoder** [comment]
> This probably require a change in the communication protocol. Perhaps adding a tag for such cases can be useful.

Iirc it's a config, yes.

**Comment by DintyGadget** [comment]
With the release of the BFA add-on, pvp talents were placed in the war mode menu, you need to write a code to activate the war mode so that the pvp talents can be selected.
