### ISSUE TITLE
A distraction for akama

### ISSUE THREAD

**Issue by turbosnek** [TrinityCore/TrinityCore#25915]
Hello, I applyed this commit  https://github.com/TrinityCore/TrinityCore/commit/879678e50f71666646b2489ee2f86336e21a28a0
but event not started and I do not have gossip select

![xiri](https://user-images.githubusercontent.com/695608/105557842-7e4f0d00-5d0d-11eb-8057-35bdb7e40e58.png)

**Comment by Aokromes** [comment]
you aren't supposed to hand apply random commits.

**Comment by illfated** [comment]
Also, I am fairly sure that related content has been updated in later years, both in DB and C++ (core).
