### ISSUE TITLE
Trinitycore 3.3.5 el capitan xcode 8.2.1 build error

### ISSUE THREAD

**Issue by chandlju420** [TrinityCore/TrinityCore#25910]
**Description**
Attempting to build 3.3.5 trinitycore on mac os el capitan after solving multiple problems installing the dependencies now i have build errors, but i can assure you i have all the correct versions installed in the correct paths and everything is set right according to the guide.
**Expected behaviour:**

It should just build without problems 

**Steps to reproduce the problem:**

1. Follow the macos guide to install trinitycore, with xcode 8.2.1 the highest el capitan can run.
2. Attempt to build the binaries with xcode either threw terminal or xcode.app. clean the build, archive according to the guide because i want the release version. 
3. Get 50 plus errors the first to appear is DB2Databaseloader.cpp no matching function to call for max

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

**Operating system:** 

El Capitan

**Comment by Faq** [comment]
You should provide:
1. full compile log in [gist](https://gist.github.com/)
2. TC rev. hash

**Comment by Shauren** [comment]
> DB2Databaseloader.cpp

That is not 3.3.5 branch, its master

**Comment by jackpoz** [comment]
could it be you checked out the wrong branch or maybe you have some additional files in your local checkout ?
