### ISSUE TITLE
New Player Experience - Exile's Reach teleport

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#25927]
.

**Comment by illfated** [comment]
Oh. Right. I was almost going to ask why you are deleting one ID and creating a different one. The ID column is missing in the insert.

```sql
-- New Player Experience - Exile's Reach
DELETE FROM `game_tele` WHERE `id`= 1683 AND `map`= 2175;
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(1683, 459.758179, -2620.471191, 0.473076, 0.603843, 2175, 'ExilesReach');
```

**Comment by DerEnderman** [comment]
The ID is AutoGenerated by the GameTele Table itself it should always be blank to let the database choose the correct number.

**Comment by illfated** [comment]
> The ID is AutoGenerated by the GameTele Table itself it should always be blank to let the database choose the correct number.

Oh. I see. I did not know that. Good point. Thank you.

**Comment by illfated** [comment]
Sorry if I offended you, that was not intended. I was simply "thinking out loud" what the correct details in the SQL query should be.

**Comment by Aokromes** [comment]
> The ID is AutoGenerated by the GameTele Table itself it should always be blank to let the database choose the correct number.

never trust autogenerated, people may have reused the id.

**Comment by illfated** [comment]
> never trust autogenerated, people may have reused the id.

Very well. So the adjustment suggestion I posted should be the preferred one, no matter if it is for 3.3.5 or master?

> ```sql
> -- New Player Experience - Exile's Reach
> DELETE FROM `game_tele` WHERE `id`= 1683 AND `map`= 2175;
> INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
> (1683, 459.758179, -2620.471191, 0.473076, 0.603843, 2175, 'ExilesReach');
> ```

**Comment by matanshukry** [comment]
What is this PR about? I don't remember and looks like all the details have been removed.
Is this only a PR for sql teleport location for exile's reach or did it include anything else?

**Comment by MaxtorCoder** [comment]
> What is this PR about? I don't remember and looks like all the details have been removed.
> Is this only a PR for sql teleport location for exile's reach or did it include anything else?

Just teleport. He was butthurt so removed PR Title and Description.

**Comment by matanshukry** [comment]
Checked the coordinates and they're not correct though; they're inside the ground.
If we want to use the same position with different height:
```
-- New Player Experience - Exile's Reach
DELETE FROM `game_tele` WHERE `id`= 1683 AND `map`= 2175;
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(1683, 459.758179, -2620.471191, 181.936, 0.603843, 2175, 'ExilesReach');
```

Although it's still on the steep of an hill; I'm not too familiar with the area, but a position like this which is more to the center in a more open ground would probably be a bit better:
```
-- New Player Experience - Exile's Reach
DELETE FROM `game_tele` WHERE `id`= 1683 AND `map`= 2175;
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(1683, 216.421, -2377.017, 82.530, 1.364, 2175, 'ExilesReach');
```


Either way we should merge it and close this issue.

**Comment by MaxtorCoder** [comment]
Would be better to just have it at the start after ship, not somewhere random.

**Comment by matanshukry** [comment]
Agreed:

```
-- New Player Experience - Exile's Reach
DELETE FROM `game_tele` WHERE `id`= 1689 AND `map`= 2175;
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(1689, -484.445, -2618.382, 4.012, 6.155, 2175, 'ExilesReach');
```

```
.go xyz -484.445 -2618.382 4.012 2175
```

p.s.
Also edited the ID to reflect actual higher non-used id
