### ISSUE TITLE
people stuck on combat after killing icc gunship

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25921]
**Description:**

lately i get to much reports of this

Combat refs: (Combat state: 1 | Manager state: 1)
[PvE] Gunship Hull (SpawnID 133954)

**Expected behaviour:**

exit of combat after kill gunship

**Steps to reproduce the problem:**

1. fight icc gunship
2. win
3. notice you are still on combat

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5d1769768745

**Operating system:** 

Debian 10 x64

**Comment by jackpoz** [comment]
should Gunship Hull enter combat at all ? should that be disabled with the usual no combat flag ?
