### ISSUE TITLE
The Death Knight scarlet crusade starting area

### ISSUE THREAD

**Issue by GitGoppy** [TrinityCore/TrinityCore#25928]
Branch 3.3.5a
Server on commit a06a755

Death knight initiates openly walk into the argent crusade camp and they don't aggro the crusaders, nor do the crusaders aggro them.
Additionally they show a right click to talk mouse prompt, when right clicked no text popup appears, yet the initiate stops moving and turns toward the player, after which it just stays in that spot... bugged...
Hopefully this is an emergent bug and not something which remained for more than five years in a WOTLK server emulator...

**Comment by offl** [comment]
Ids, please

**Comment by GitGoppy** [comment]
Creature entry ID
28406

**Comment by offl** [comment]
Probably the ones with waypoints should be attackable and without gossip

**Comment by dr-j** [comment]
This maybe wrong as not sniffed but this will to address the issue of the scarlet initiates not attacking no idea about gossip as did not check that as issue I had reported was just about them walking straight past enemies and not engaging combat with them
~~~sql
`` UPDATE `creature_template` SET `unit_flags`='33024' WHERE `entry`=28406; ``

**Comment by offl** [comment]
Anyway we can't remove the gossip flag from specific spawns
*laughs loudly*

**Comment by GitGoppy** [comment]
The gossip is there because during "Death's Challenge" quest you are supposed to win 10 duels against death knight initiates or players, before and after quest completion you can no longer ask the initiates to a duel, but the gossip flag is still active on all on them and it does not open a text box. The moving initiates wit waypoints for the scarlet enclave camps stop moving if you right click them, but since no textbox visible textbox was opened to the player the initiate get's stuck because it thinks the player is still interacting with it.

**Comment by illfated** [comment]
Hmm. I wonder if that means that the NPCs moving away from **Death's Breach** should not have a NPC gossip flag at all.

**Comment by GitGoppy** [comment]
Also the initiates are walking to the enemy line, instead they should be running.
Video demonstration: https://youtu.be/n_MtYnMRRQ4?t=1172

**Comment by illfated** [comment]
Well, walking versus running is a different issue altogether and could be part of a generic scripting or waypoint issue.

**Comment by offl** [comment]
So the gossip is available for pathing ones and they stops the movement after click
They just should be attackable

**Comment by GitGoppy** [comment]
> So the gossip is available for pathing ones and they stops the movement after click
> They just should be attackable

They should also actively aggro the scarlet forces, the video shows them attacking scarlet mobs without getting attacked first.

**Comment by bakoorahnin** [comment]
Nice
