### ISSUE TITLE
Impossible to damage the Omen

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#25925]
After summoning the boss Omen, it cannot be damaged.

[https://www.youtube.com/watch?v=4WUKzR5J6sg](https://www.youtube.com/watch?v=4WUKzR5J6sg)
[https://www.wowhead.com/npc=15467/omen](https://www.wowhead.com/npc=15467/omen)
3.3.5
Ubuntu x64
Rev. b86b21a

**Comment by Aokromes** [comment]
worked for a group yesterday.

**Comment by gygyti** [comment]
I've noticed that some things (like dungeons) sometimes work fine and sometimes they don't.

**Comment by Jildor** [comment]
should complete movepoint before remove SetImmuneToPC
https://github.com/TrinityCore/TrinityCore/blob/a41f599be72ccc88b13c1cf725f20cee4a5335d7/src/server/scripts/Kalimdor/zone_moonglade.cpp#L428-L440

**Comment by offl** [comment]
Follow the issue template and add steps to reproduce the issue, at least position where he should be temp spawned

**Comment by gygyti** [comment]
After he got up, there was no further action on his part

**Comment by Aokromes** [comment]
update your core.

**Comment by Jildor** [comment]
maybe it could be related to this issue: #24552
both cases the npc is summoned and once it has been summoned, do SetImmuneToPC and execute MovePoint
unfortunately I have not been able to reproduce any issue, so I can not confirm anything

**Comment by offl** [comment]
> After he got up, there was no further action on his part

I have no idea what this means
Does he start movement or not?

**Comment by offl** [comment]
Cannot reproduce after 50 attempts by

.npc add tem 15467 at .go x 7539.107910 -2858.284668 457.838776 1 0.353025
.dam 100000000
repeat

Even if MovementInform is not called sometimes, it's #24552
