### ISSUE TITLE
Could you commit all *.proto files on master?

### ISSUE THREAD

**Issue by CasinoHe** [TrinityCore/TrinityCore#25922]
**Description:**

Could you commit all the *.proto files? For example: club_notification.proto, club_request.proto, etc.
I want to upgrade google protobuf to a new version, with out the proto files, is a hard work.

**Expected behaviour:**

Commit the proto files.

**Steps to reproduce the problem:**

1. Use a different google protobuf lib
2. Compile will failed, with "Proto file is not compiled on this version"

**Branch(es):**

master

**Operating system:** 

windows, debian, ubuntu

**Comment by Shauren** [comment]
No, I will not do that.
