### ISSUE TITLE
Tyr's Hand, Eastern Plaquelands Scarlet side and Noxious glade devoid of mobs

### ISSUE THREAD

**Issue by GitGoppy** [TrinityCore/TrinityCore#25929]
Branch 3.3.5a
commit a06a755

Tyr's hand and Noxious glade have absolutely no mobs in them, I haven't searched the whole eastern plaguelands scarlet side but I saw that the entire area has absolutely no mobs anywhere, where there should be many mobs as confirmed by trusted sources.
There are even buildings where certain NPC's should be and there are none in this completely desolate area.

**Comment by illfated** [comment]
Any steps on how to reproduce / replicate your issue?

**Comment by Faq** [comment]
And in all your issues, add the IDs from https://tcubuntu.northeurope.cloudapp.azure.com/aowow/

**Comment by Aokromes** [comment]
https://i.imgur.com/ZK2qqf0.jpg
tyr's hand cannot reproduce.

**Comment by Aokromes** [comment]
also ruins are empty even on retail.

**Comment by Aokromes** [comment]
also, tyr's hand mobs changed with cataclysm https://es.wowhead.com/npc=46138/centuri%C3%B3n-argenta
