### ISSUE TITLE
guild bank adds one row per item repaired instead per repair

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25937]
**Description:**

guild bank adds one row per item repaired instead per repair, making log quite useless because if 2 persons repairs it fills visible log.

**Expected behaviour:**

it must show one row per repair.

**Steps to reproduce the problem:**

1. make one guild 
2. add some funds
3. break your gear
4. notice you see 1 row per repaired item

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

a06a755f4c52

**Operating system:** 

debian 10 x64.

**Comment by illfated** [comment]
Is it related to this part of the code, or something else?
https://github.com/TrinityCore/TrinityCore/blob/1ff4a7e75b56e1ad68d83f75b493a42ac1ae85c3/src/server/game/Handlers/NPCHandler.cpp#L712-L748

**Comment by Shauren** [comment]
In case anyone is confused about what @Aokromes is talking about, its guild bank money log

**Comment by illfated** [comment]
Thank you. Yes, I was confused.
