### ISSUE TITLE
Spell/Hunter "Lone Wolf" (155228)

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#25935]
**Description:**

Lone Wolf grants a Buff if the Hunter dont have a active Pet

**Expected behaviour:**

Lone Wolf should be active if the Hunter dont have a active Pet.

**Steps to reproduce the problem:**

1. skill Marskmanship Hunter
2. release your Pet
3. see at your Buff task that Lone Hunter is not active

**Branch(es):**

master

**TC rev. hash/commit:** 

commit e601c6d1f9b9743e92e9562abd9f2d24d9aaf175

**Operating system:** 

Debian 10

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19617
