### ISSUE TITLE
DB/item: Plans: Goblin Rocket Boots (7192)

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#25930]
**Description:**

1. The schematic "**Plans: Goblin Rocket Boots**" should not drop from **Fozruk**.
2. The correct item name should have been "**Schematic: Goblin Rocket Boots**". (Plans are mostly used in Blacksmithing.)
3. If this schematic should drop from any NPC, it should be **Mekgineer Thermaplugg** in Gnomeregan.
4. The schematic should only be a **single** drop, not multiple (if the drop is valid, that is).
5. The existing schematic is **inactive**, does not allow player to learn any spell from this item.
6. The schematic is tagged **This item is not available to players** on www.wowhead.com (not on classic.wowhead.com)

**Note:** the schematic item was available as a drop in Gnomeregan in **Vanilla WoW** and **The Burning Crusade** (and now again in Classic), but became deprecated early in Wrath of the Lich King.

![image](https://user-images.githubusercontent.com/38162891/105618730-fccdac80-5dea-11eb-90dc-608905c4c4e2.png)

![image](https://user-images.githubusercontent.com/38162891/105618710-b11b0300-5dea-11eb-947b-f5ac04d38073.png)

- https://www.wowhead.com/item=7192/schematic-goblin-rocket-boots#comments
- https://classic.wowhead.com/item=7192/schematic-goblin-rocket-boots
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=7192/plans-goblin-rocket-boots
- https://wow.gamepedia.com/Goblin_Rocket_Boots#Notes
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2611/fozruk#drops
- https://classic.wowhead.com/npc=2611/fozruk#drops;50
- https://www.wowhead.com/npc=2611/fozruk
- https://wow.gamepedia.com/Fozruk
- https://www.wowhead.com/npc=7800/mekgineer-thermaplugg
- https://classic.wowhead.com/npc=7800/mekgineer-thermaplugg
- https://wow.gamepedia.com/Mekgineer_Thermaplugg_(tactics)

Even if I have already learned the spell from Nixx Sprocketspring \<Goblin Engineering Trainer\> in Gadgetzan, it still shows up in the AH listing when I have ticked the box

- [X] **Usable items**

to make the AH UI list only unlearned recipes, but because the recipe item is inactive (does not teach a spell), it behaves just like a dummy document item.

```sql
SELECT * FROM `creature_loot_template` WHERE `Entry`= 2611 AND `item`= 7192;
```
```
Entry  Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ----  ---------  ------  -------------  --------  -------  --------  --------  -------
 2611  7192          0      30              0         1        0         1         2  (NULL)
```
```sql
SELECT * FROM `item_template` WHERE `entry`= 7192;
```
```
entry  class  subclass  SoundOverrideSubclass  name                        displayid  Quality   Flags  FlagsExtra  BuyCount  BuyPrice  SellPrice  InventoryType  AllowableClass  AllowableRace  ItemLevel  RequiredLevel  RequiredSkill  RequiredSkillRank  requiredspell  requiredhonorrank  RequiredCityRank  RequiredReputationFaction  RequiredReputationRank  maxcount  stackable  ContainerSlots  StatsCount  stat_type1  stat_value1  stat_type2  stat_value2  stat_type3  stat_value3  stat_type4  stat_value4  stat_type5  stat_value5  stat_type6  stat_value6  stat_type7  stat_value7  stat_type8  stat_value8  stat_type9  stat_value9  stat_type10  stat_value10  ScalingStatDistribution  ScalingStatValue  dmg_min1  dmg_max1  dmg_type1  dmg_min2  dmg_max2  dmg_type2   armor  holy_res  fire_res  nature_res  frost_res  shadow_res  arcane_res   delay  ammo_type  RangedModRange  spellid_1  spelltrigger_1  spellcharges_1  spellppmRate_1  spellcooldown_1  spellcategory_1  spellcategorycooldown_1  spellid_2  spelltrigger_2  spellcharges_2  spellppmRate_2  spellcooldown_2  spellcategory_2  spellcategorycooldown_2  spellid_3  spelltrigger_3  spellcharges_3  spellppmRate_3  spellcooldown_3  spellcategory_3  spellcategorycooldown_3  spellid_4  spelltrigger_4  spellcharges_4  spellppmRate_4  spellcooldown_4  spellcategory_4  spellcategorycooldown_4  spellid_5  spelltrigger_5  spellcharges_5  spellppmRate_5  spellcooldown_5  spellcategory_5  spellcategorycooldown_5  bonding  description                                   PageText  LanguageID  PageMaterial  startquest  lockid  Material  sheath  RandomProperty  RandomSuffix   block  itemset  MaxDurability    area     Map  BagFamily  TotemCategory  socketColor_1  socketContent_1  socketColor_2  socketContent_2  socketColor_3  socketContent_3  socketBonus  GemProperties  RequiredDisenchantSkill  ArmorDamageModifier  duration  ItemLimitCategory  HolidayId  ScriptName  DisenchantID  FoodType  minMoneyLoot  maxMoneyLoot  flagsCustom  VerifiedBuild
-----  -----  --------  ---------------------  --------------------------  ---------  -------  ------  ----------  --------  --------  ---------  -------------  --------------  -------------  ---------  -------------  -------------  -----------------  -------------  -----------------  ----------------  -------------------------  ----------------------  --------  ---------  --------------  ----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  ----------  -----------  -----------  ------------  -----------------------  ----------------  --------  --------  ---------  --------  --------  ---------  ------  --------  --------  ----------  ---------  ----------  ----------  ------  ---------  --------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  ---------  --------------  --------------  --------------  ---------------  ---------------  -----------------------  -------  --------------------------------------------  --------  ----------  ------------  ----------  ------  --------  ------  --------------  ------------  ------  -------  -------------  ------  ------  ---------  -------------  -------------  ---------------  -------------  ---------------  -------------  ---------------  -----------  -------------  -----------------------  -------------------  --------  -----------------  ---------  ----------  ------------  --------  ------------  ------------  -----------  -------------
 7192      9         3                     -1  Plans: Goblin Rocket Boots       1102        2      64           0         1      1200        300              0              -1             -1         26              0            202                130              0                  0                 0                          0                       0         0          1               0           0           0            0           0            0           0            0           0            0           0            0           0            0           0            0           0            0           0            0            0             0                        0                 0         0         0          0         0         0          0       0         0         0           0          0           0           0       0          0               0          0               0              -1               0               -1                0                       -1          0               0               0               0               -1                0                       -1          0               0               0               0               -1                0                       -1          0               0               0               0               -1                0                       -1          0               0               0               0               -1                0                       -1        0  Teaches you how to make Goblin Rocket Boots.         0           0             0           0       0        -1       0               0             0       0        0              0       0       0          0              0              0                0              0                0              0                0            0              0                       -1                    0         0                  0          0                         0         0             0             0            0              0
```

**Expected behaviour:**

- If the schematic is supposed to be available in-game, it needs to be repaired to work as a schematic/recipe spell-teaching item, as well as changing its drop source.
- If the schematic is NOT supposed to be available in-game, we need to remove it from `creature_loot_template` (Fozruk) and from `item_template`.

**Steps to reproduce the problem:**

1. Use any character, preferably with Engineering skill (it may also work to test this without Engineering).
2. Acquire the item "Plans: Goblin Rocket Boots" (7192) any way you prefer:
   - if the Auction House bot (AHbot) is activated, look for "**Plans: Goblin Rocket Boots**" under **Recipe -> Engineering**, or
   - kill **Fozruk** in **Arathi Highlands** and loot the item(s), or
   - just give yourself the item via GM command `.additem 7192`.
3. Try to use the item. Notice that it does not respond to right-click, like other spell-teaching recipes do.

**Suggested solution:**

```sql
-- remove "Plans: Goblin Rocket Boots"
DELETE FROM `creature_loot_template` WHERE `Entry`= 2611 AND `item`= 7192;
DELETE FROM `item_template` WHERE `entry`= 7192;
```

***

Even if we go for full removal, some users may be interested in how the item could be repaired for use in simulating the vanilla content. I have not yet verified exactly what is wrong in that DB item entry.

- Could it be caused by `item_template`.`spellid_1`= 0 ?

edit: if that is the case, it could be interesting to test the following SQL query:
```sql
UPDATE `item_template` SET `name`= "Schematic: Goblin Rocket Boots", `spellid_1`= 8895 WHERE `entry`= 7192;
```
(I mean, the item is deactivated anyway, so it would take quite a lot of abuse to make it completely FUBAR.)

**Branch(es):**

3.3.5 (I don't know / don't remember if the item issue has been corrected in master)

**TC rev. hash/commit:** 

TrinityCore rev. 4c0a8ad3b3f9 2021-01-19 10:16:44 +0200 (3.3.5 branch) (Win64, Release, Static)
```sql
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.19.2
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
 maps directory located in ./maps.  Total size:  251987687 bytes
vmaps directory located in ./vmaps. Total size:  658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.21011
```

**Operating system:** 

Windows 10 Home x64 Version 20H2 (OS Build 19042.746)

**Comment by illfated** [comment]
Update regarding how to repair the schematic item in DB, it was incorrect of me to assume that the crafting spell should be added in `spellid_1`, because there is a Learning spell (483) https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=483 to be entered there. The simplest way for me, after changing the name from "Plans:" to Schematic: is to list similar items and compare them by using the following query:
```sql
SELECT * FROM `item_template` WHERE `name` LIKE "Schematic:%" ORDER BY `entry` ASC;
```
(129 rows after the rename, 128 without renaming the item in this ticket)

The easiest way for me to show how it could be repaired is to provide a wrapped SQL query and commenting the individual wrapped lines. (I am only suggesting a change to the most obvious columns based on the column values for the related schematic items.)
```sql
-- item 7192 (Schematic: Goblin Rocket Boots), spell ID 483 (Learning), spell ID 8895 (Goblin Rocket Boots)
UPDATE `item_template` SET
 `name`= "Schematic: Goblin Rocket Boots", -- Engineering nomenclature
 `spellid_1`= 483,     -- spell ID 483, "Learning"
 `spellppmRate_1`= -1, -- same value as in neighboring columns
 `spellid_2`= 8895,    -- spell ID 8895, "Goblin Rocket Boots"
 `spelltrigger_2`= 6,  -- same value as in neighboring columns
 `BagFamily`= 128      -- same value as in neighboring columns
WHERE `entry`= 7192;
```

Anyway, I just tested the SQL above, but it still does not work as an engineering schematic to teach the player the engineering spell.

At least now it reacts to the AH setting
- [X] Usable items

so that is at least 1 improvement. 8895 could be a wrong spell ID. I don't know.

- https://classic.wowhead.com/spell=8895/goblin-rocket-boots
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=8895
- https://classic.wowhead.com/spell=8896/schematic-goblin-rocket-boots
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=8896 (**This spell doesn't exist.**)

**Comment by offl** [comment]
```sql
DELETE FROM `item_template`
UPDATE `item_template` SET
```
No no no

**Comment by illfated** [comment]
Oh well. I was hoping that the `disables` table could be used, but it does not seem to support items (judging by the wiki `disables` page).
Also hoping that there may be a different solution to be used.

I know that `worldserver.conf` can be manually edited to hide specific items from ever being added by AHbot, but I am more worried about the invalid drop from Fozruk and that the item itself is broken.

**Comment by offl** [comment]
We don't need to edit it or delete it completely
Dunno about AHbot

**Comment by illfated** [comment]
The Auction House bot settings in `worldserver.conf` are quite well documented, so it is easy for most users to edit their own exclusion:

```
#
#    AuctionHouseBot.forceExcludeItems
#       Description: Exclude these items even if they would pass the filters
#                    List of ids with delimiter ','
#       Example:     "21878,27774,27811,28117,28122,43949" (this removes old items)
#       Default:     ""
#

AuctionHouseBot.forceExcludeItems = "6343,6345,6376"
```
The item can easily be added in that short list by anyone, so I don't see that as something to be added in the source. I also presume there are lots of other defective items like this schematic, so I guess the only remaining part to discuss is the NPC loot drop.
