### ISSUE TITLE
graveyard 1318 lacks spirit healer

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#25955]
**Description:**

title

**Expected behaviour:**

must have spirit healer.

**Steps to reproduce the problem:**

1. die near graveyard 1318
2. release
3. notice no spirit healer.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

075d46a46bf1

**Operating system:** 

N/R

**Comment by illfated** [comment]
Just to make it easier for those who don't remember (like me) how to look up where that GY is; which one is it?

**Comment by Aokromes** [comment]
go grave 1318

**Comment by illfated** [comment]
heh, OK. So be it. That is the Tuskarr graveyard next to 
- **Karuk** (The Kalu'ak) (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=25435/karuk)
- above **Riplash Strand** (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=4028)
- in **Borean Tundra** (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?zone=3537)

I presume that not many players have managed to die within the reach of that graveyard (and also wanted to resurrect there), otherwise it would have been reported sooner.

Anyway, you managed to make me confirm this issue, although on a slightly older core:

TrinityCore rev. 661f554b9e08 2021-01-24 16:04:47 +0100 (3.3.5 branch) (Win64, Release, Static)
```sql
You are outdoors.
Map: 571 (Northrend) Zone: 3537 (Borean Tundra) Area: 3537 (Borean Tundra) Phase: 1
X: 2006.062256 Y: 5937.440430 Z: 37.258358 Orientation: 2.732149
grid[35,43]cell[6,1] InstanceID: 0
 ZoneX: 45.682274 ZoneY: 75.235229
GroundZ: 37.257477 FloorZ: 37.257477 MinHeight: -1000.000000 Have height data (Map: 1 VMap: 1 MMap: 1)
```

I don't know what the exact coordinates would be for a Spirit Healer in that location.

**Comment by illfated** [comment]
Anyway, a rough position guestimate, based purely on the visual location, would be something like the following:
```sql
 You are outdoors.
 Map: 571 (Northrend) Zone: 3537 (Borean Tundra) Area: 3537 (Borean Tundra) Phase: 1
 X: 2002.554932 Y: 5938.065918 Z: 37.110233 Orientation: 5.854897
 grid[35,43]cell[6,1] InstanceID: 0
  ZoneX: 45.671425 ZoneY: 75.326477
 GroundZ: 37.109467 FloorZ: 37.109467 MinHeight: -1000.000000 Have height data (Map: 1 VMap: 1 MMap: 1)
```

**Comment by Aokromes** [comment]
now that i see https://github.com/TrinityCore/TrinityCore/issues/25230 i wonder how much graveyards lacks spirit healer.

**Comment by mdX7** [comment]
Just sniffed it on retail, might require adjustments for 3.3.5 db, used Shadowlands as output.
```
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `PhaseId`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 6491, 571, 3537, 0, '0', '16924', 0, 0, 0, 2002.7415771484375, 5938.0986328125, 37.18986129760742187, 5.934119224548339843, 120, 0, 0, 15918, 0, 0, 0, 0, 0, 37176), -- 6491 (Area: 0 - Difficulty: 0) (Auras: 9036 - 9036, 10848 - 10848)
```

**Comment by MaxtorCoder** [comment]
> Just sniffed it on retail, might require adjustments for 3.3.5 db, used Shadowlands as output.
> 
> ```sql
> INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnDifficulties`, `PhaseId`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
> (@CGUID+0, 6491, 571, 3537, 0, '0', '16924', 0, 0, 0, 2002.7415771484375, 5938.0986328125, 37.18986129760742187, 5.934119224548339843, 120, 0, 0, 15918, 0, 0, 0, 0, 0, 37176), -- 6491 (Area: 0 - Difficulty: 0) (Auras: 9036 - 9036, 10848 - 10848)
> ```

You are missing the `CGUID` setter hahahha

**Comment by mdX7** [comment]
no im not, it has to be set by the one merging it ;)

**Comment by MaxtorCoder** [comment]
Time to hide again 😂

**Comment by offl** [comment]
Looks like https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=9036 was added later, right?

**Comment by mdX7** [comment]
> 
> 
> Looks like https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=9036 was added later, right?

I assumed that the auras are set via _template_addon already, I don't have a db set up atm to check it.
Thats the aura giving the transparency effect.

**Comment by offl** [comment]
Only 10848 is set, no 9036 in 3x 4x sniffs
Anyway asked just out of curiosity, gonna ignore it for 335

**Comment by offl** [comment]
Phase 16924 without 1? How exactly parser picks phases?

**Comment by funjoker** [comment]
The parser throws PhaseIDs based on phases the player is in.
335 does not use PhaseIDs!
335 uses phasemasks which act like flags.

On master we have PhaseGroups to apply several phases.

example:
335 phasemask | master PhaseID | 
--- | --- 
1 | 169
2 | 170
4 | 171
8 | 172
16 | 173
32 | 174
64 | 175
128 | 176
256 | 177
512 | 178
... | ...

Also there are things like phaseUseFlags in master now.
Flag 1 for example makes an object visible in all phases.

**So in this case i'm pretty sure the spirit healer is unphased and visible all the time.**

**Comment by offl** [comment]
Ok, thanks
