### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by turbosnek** [TrinityCore/TrinityCore#25954]
Hi, I have this error in compilation. Worldserver.exe not create. Can you help me how to fix?

3>scripts.lib(cs_misc.obj) : error LNK2019: unresolved external symbol "public: void __thiscall WorldSession::SendShowMailBox(class ObjectGuid)" (?SendShowMailBox@WorldSession@@QAEXVObjectGuid@@@Z) referenced in function "public: static bool __cdecl misc_commandscript::HandleMailBoxCommand(class ChatHandler *,char const *)" (?HandleMailBoxCommand@misc_commandscript@@SA_NPAVChatHandler@@PBD@Z)
3>scripts.lib(boss_kalecgos.obj) : error LNK2019: unresolved external symbol "public: void __thiscall InstanceScript::SendEncounterUnit(unsigned int,class Unit *,unsigned char,unsigned char)" (?SendEncounterUnit@InstanceScript@@QAEXIPAVUnit@@EE@Z) referenced in function "public: virtual void __thiscall boss_kalecgos::EnterEvadeMode(enum CreatureAI::EvadeReason)" (?EnterEvadeMode@boss_kalecgos@@UAEXW4EvadeReason@CreatureAI@@@Z)
3>scripts.lib(boss_illidari_council.obj) : error LNK2001: unresolved external symbol "public: void __thiscall InstanceScript::SendEncounterUnit(unsigned int,class Unit *,unsigned char,unsigned char)" (?SendEncounterUnit@InstanceScript@@QAEXIPAVUnit@@EE@Z)
3>C:\Users\Turbosnecek\Desktop\TrinityBuilde\bin\Release\worldserver.exe : fatal error LNK1120: 2 unresolved externals
3>Done building project "worldserver.vcxproj" -- FAILED.

**Comment by illfated** [comment]
This is not a source code issue. Tickets posted here should always be about source code issues.

Ask in IRC (https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130200/IRC) 
or Discord (https://discord.com/invite/xyfS8jGz?utm_source=Discord%20Widget&utm_medium=Connect) 
to ask for help with your unresolved externals issues.

**Comment by jackpoz** [comment]
Another good place could be https://github.com/TrinityCore/TrinityCore/discussions too
