### ISSUE TITLE
[Quest/Oracles] Song of Wind and Water

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#25961]
Impossible to perform in the part where it is necessary to absorb the spirit of rain. **Wind elemental spells (which you transform into) does not work** 

[https://www.wowhead.com/quest=12726/song-of-wind-and-water](https://www.wowhead.com/quest=12726/song-of-wind-and-water)

3.3.5
Ubuntu x64
Rev. b86b21a

**Comment by Aokromes** [comment]
maybe it broke after latest flags changes?

https://i.imgur.com/ayIzxuJ.png

@offl

**Comment by offl** [comment]
UNIT_FLAG_POSSESSED was removed from https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28999

> Wind elemental spells (which you transform into) does not work

Which ones? https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28999#controlled-abilities

**Comment by dr-j** [comment]
Yes it does not work without possessed flag for some reason  well without flags works when you first mount vehicle but once you consume a wind elemental and the template updates you can’t cast at water elemental

**Comment by gygyti** [comment]
![изображение](https://user-images.githubusercontent.com/77268574/105908686-96899980-6037-11eb-968e-bc2261def361.png)

yes, the wind can't use any skill

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5254
https://github.com/TrinityCore/TrinityCore/issues/5424#issuecomment-11257599
Need to test

**Comment by offl** [comment]
Migrated to #25965
@gygyti next time please follow issue template and include steps to reproduce the issue, at least basic steps, which quest to pick, where to go, etc
