### ISSUE TITLE
npc_vendor npc_trainer  9.0.2(37176)

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#25963]
npc_vendor npc_trainer Where are the settings? In the client or in the kernel? Previously, it was possible to make changes through the database. Can't you return the old days? Or with this now, strictly?

npc_vendor npc_trainer Где находятся настройки? В клиенте или в ядре? Раньше можно было через базу данных вносить изменения. Нельзя вернуть былое время? Или с этим сейчас, строго?

**Comment by illfated** [comment]
Please use https://github.com/TrinityCore/TrinityCore/discussions/new for questions like the one you have posted.

The **issues** ticket system is intended for reporting actual discovered issues in the source code, or crashes, if you get a crash using unmodified TC source code.

**Comment by rem999** [comment]
Да я перешёл в другой раздел. Не злись я ведь не знал.
Yes, I moved to another section. Don't be angry, I didn't know.

**Comment by illfated** [comment]
Fair enough. Not a big deal. GL & HF.

Справедливо. Не так уж и важно. Удачи повеселиться.
