### ISSUE TITLE
Demon Hunter Broken (To be Expected)

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#25960]
As requested and this can be closed if need be as i know post 3.3.5 stuff is very unlikely implemented yet but posting as a reminder when the time comes for someone to look at. (I am not a coder i'm afraid or i'd have a good look to try and resolve the issue or at least help where i could)

**Description:**

Create a DH, Die, Should ress at nearest GY, instead you resurrect at Westfall. Possibly because no spirit healers have been implemented yet in regions after 3.3.5/4.4.3

Create a DH, Cast Glide Spell (131347) or double jump, Glide should deactivate on landing but remains permanently on

Spell Fel-Rush (344865) is clickable but you don't rush forward

Unable to choose a specialisation either Havoc or Vengeance so can't test further

**Expected behaviour:**

See above

**Steps to reproduce the problem:**

See above

**Branch(es):**

Master

**TC rev. hash/commit:** 

8ce9b69de3c8

**Operating system:** 

Windows 10 x64

**Comment by offl** [comment]
Closing because of 'one issue - one ticket' rule

> Create a DH, Die, Should ress at nearest GY, instead you resurrect at Westfall. Possibly because no spirit healers have been implemented yet in regions after 3.3.5/4.4.3

We have somewhere generic issue about spawns, ofc you can create separate issue related to spirit healers

> Create a DH, Cast Glide Spell (131347) or double jump, Glide should deactivate on landing but remains permanently on

#18303

> Spell Fel-Rush (344865) is clickable but you don't rush forward

Create separate issue with links to https://github.com/TrinityCore/TrinityCore/issues/18501#issuecomment-267811411 and https://github.com/TrinityCore/TrinityCore/pull/17656

> Unable to choose a specialisation either Havoc or Vengeance so can't test further

Separate issue, please
