### ISSUE TITLE
Core/World Vignette System

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#25976]
**Description:**

The Vignette system as it exist on retail needs to be implemented.
It includes various icons on the map that are retrieved from https://wow.tools/dbc/?dbc=vignette&build=9.0.2.37176#page=1

**Branch(es):**

master

**Comment by illfated** [comment]
maybe use **Core/Player:** instead of "Core/World" — since it deals with player interaction?

**Comment by MaxtorCoder** [comment]
> maybe use **Core/Player:** instead of "Core/World" — since it deals with player interaction?

It's not Player specific. It's assigned to a WorldObject

**Comment by illfated** [comment]
Yes, I realized my derp. Updated previous comment.
