### ISSUE TITLE
DB/Player: Main attribute is not updated to Shadowland state

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#25979]
**Description:**
class levels tats do not fit shadowlands.

**Steps to reproduce the problem:**

1. Create a new character.   
2. .levelup
3. .levelup
4. .levelup

**Branch(es):** master

**TC rev. hash/commit:** 

TrinityCore rev. d4ad9870105c 2021-01-28 22:02:03 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)
Using configuration file D:/Server/worldserver.conf.
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.75.0
Realm running as realm ID 1
Using World DB: TDB 837.20101
Using enUS DBC Locale
Client cache version set to: 20101
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps

**Operating system:** 
Windows 10 Pro 20H2

Level 1
![lvl 1](https://user-images.githubusercontent.com/15787347/106229407-800c4b00-61bb-11eb-8133-559721920e56.png) 
Level 2
![lvl 2](https://user-images.githubusercontent.com/15787347/106230218-007f7b80-61bd-11eb-9a77-6e9e99f6d70d.png)
Level 3 Stamina does not rise properly. 
![lvl 3](https://user-images.githubusercontent.com/15787347/106230842-61f41a00-61be-11eb-9260-0d5ab7a68b83.png)

**Comment by funjoker** [comment]
Here some information:
1. Currently the levelstats are incorrect
2. Currently in TC warrior class stats stamina on level 2 and 3 is 12.
3. Currently Orc racial stat benefit is +1 Stamina

So stamina 13 on level 2 and 3 is totally correct (except the incorrect levelstats, because they are still BfA).

The attribute update works.

**Comment by osleyder85** [comment]
> 
> 
> Here some information:
> 
>     1. Currently the levelstats are incorrect
> 
>     2. Currently in TC warrior class stats stamina on level 2 and 3 is 12.
> 
>     3. Currently Orc racial stat benefit is +1 Stamina
> 
> 
> So stamina 13 on level 2 and 3 is totally correct (except the incorrect levelstats, because they are still BfA).
> 
> The attribute update works.

Where can we get the base states?

**Comment by funjoker** [comment]
if you have some retail characters you can use DejaCahracterStats display all attributes.
Then unequip your stuff and set your spec to something which has no aura affecting stats (mostly tank specs affect those, Fire mage does too).
Give me the information which level, class and race the character is.

I'm already on it

**Comment by osleyder85** [comment]
@funjoker  Ok, so I'm not looking for anything anymore. Wait for you to finish it.

**Comment by matanshukry** [comment]
Any update on this @funjoker ?

**Comment by funjoker** [comment]
Mage
Rogue (50-60)
Priest (49-60)
Shaman
Monk
DK (1-50)

those are still missing in my table

**Comment by Nyr97** [comment]
Any updates on the missing datas? 👀

**Comment by mdX7** [comment]
> 

on it with funjoker

**Comment by Shinmegumi** [comment]
Cool. Is there anything that can be done to help pull that info and provide sniffs or anything?

**Comment by Naddley** [comment]
Current state for Dragonflight:

- [ ] Warrior [60 - 70]
- [ ] Paladin [62 - 70]
- [ ] Hunter [60 - 70]
- [X] Rogue [60 - 70]
- [X] Priest [60 - 70]
- [ ] Deathknight [60 - 70]
- [X] Shaman [60 - 70]
- [X] Mage [60 - 70]
- [X] Warlock [60 - 70]
- [ ] Monk [60-70]
- [X] Druid [60 - 70]
- [X] Demon Hunter [60 - 70]
- [X] Evoker [58 - 70]

**Comment by Naddley** [comment]
stats are updated with SimC data for Dragonflight.
