### ISSUE TITLE
DB/Portals Mage Tower Teleport - inside and out

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#25972]
**Description:**

Teleport to inside and outside of the mage tower is impossible.

**Expected behaviour:**

You can teleport inside and out while working through the "teleport object".

**Steps to reproduce the problem:**

To check inside:
1. Go to stormwind to the mage tower, and try to walk through

To check outside:
1. Teleport to inside the mage tower, and try to talk to where the teleport object should be
`.go xyz -9003.3 868.665 64.8612 0`

**Branch(es):**

- [x] master

**TC rev. hash/commit:** 

8ce9b69de3c820ce056a3fde7858f0c4d5f6b0a4

**Operating system:** 

Windows 10

**Required PRs**

- [x] #25971 

**Sql to fix this:**

```sql
DELETE FROM `areatrigger_positions` WHERE `Id` IN (1, 2) AND `IsServer` = 1;
INSERT INTO `areatrigger_positions` (`Id`, `IsServer`, `MapId`, `PosX`, `PosY`, `PosZ`, `Comment`) VALUES
  (1, 1, 0, -9015.774, 877.223, 148.61871, 'Stormwind Mage Portal Entrance'),
  (2, 1, 0, -8999.866, 864.13995, 65.88978, 'Stormwind Mage Portal Exit');

DELETE FROM `areatrigger_template` WHERE `Id` in (1, 2) AND `IsServer` = 1;
INSERT INTO `areatrigger_template` (`Id`, `IsServer`, `Type`, `Flags`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `ScriptName`, `VerifiedBuild`) VALUES
  (1, 1, 1, 0, 1.2597655, 1.2792665, 3.7021635, 0, 0, 0, '', 0),
  (2, 1, 1, 0, 1.2597655, 1.2792665, 3.7021635, 0, 0, 0, 'SmartTriggerServer', 0);

DELETE FROM `areatrigger_template_actions` WHERE `AreaTriggerId` IN (1, 2) AND `IsServer` = 1;
INSERT INTO `areatrigger_template_actions` (`AreaTriggerId`, `IsServer`, `ActionType`, `ActionParam`, `TargetType`) VALUES
  (1, 1, 2, 3631, 5),
  (2, 1, 2, 3630, 5);

UPDATE `world_safe_locs` SET LocX=-9014.864258, LocY=874.324890, LocZ=148.618713 WHERE `id` = 3630;
```

**Comment by osleyder85** [comment]
I don't think you have to do all that to get in. You just need the ```gameobject.entry``` of that portal and put it.

**Comment by matanshukry** [comment]
@osleyder85 take the `gameobject.entry` of the portal and put it in what? which table/fields are you talking about?

**Comment by osleyder85** [comment]
> 
> 
> @osleyder85 take the `gameobject.entry` of the portal and put it in what? which table/fields are you talking about?

Table gameobject field id

**Comment by matanshukry** [comment]
@osleyder85 .. can you elaborate? let's assume I know how to find that portal gameobject id (which I don't) - what do you suggest I'll do with it? you need to teleport the player to another location. What other tables are you suggesting I use with?

**Comment by osleyder85** [comment]
No, what I think is that to enter the Hall of Portals in Stormwind, you only need to set the portal that gives you access to the Hall of Portals.

**Comment by osleyder85** [comment]
Anyway, you have to wait for someone from the TC development team to answer you. Maybe what you are doing if the server needs it.

**Comment by illfated** [comment]
(cosmetic details, if you want to fix up the broken MarkDown formatting at the end of your main ticket comment post)

```
** Required PRs**

* [] #25971

** Sql to fix this: **
```

1. Avoid spacing between the formatting asterisks and its enclosed text. GitHub Flavored MarkDown (GFM) does not support spacing between MD formatting and its enclosed text.
2. Make sure to keep 1 space within the square brackets to form the tick box, or fill it with the character X to tick the box.
   ```
   - [ ] Unticked box
   - [X] Ticked box
   ```
3. Even though the asterisk (`*`) functions as the item indicator in bullet point lists and task lists, GFM recommends using the dash (`-`) character.

```
**Required PR:**

- [ ] #25971

**SQL to fix this:**
```

**Comment by matanshukry** [comment]
@illfated I did use `-` and not `*` for the item list. But everything else was helpful - thank you.

**Comment by illfated** [comment]
Fair enough. Very well. May I also suggest ticket title adjustments, to follow common TC codestyle? Perhaps something like

**DB/Portals: Mage Tower Teleport - inside and out**

**Comment by matanshukry** [comment]
I did try that actually with DB/World, but yours is better. I'll remove the PR, but not really sure how to indicate this is not a report on an issue but acutally a fix.

**Comment by illfated** [comment]
Yeah, I see what you mean. Tickets with SQL content is less based on DB structure references in naming. You just need to add "DB/" at the start to indicate that it is not about C++ scripts or core /src content. Anyway, ticket titles are much less consequential, they do not directly affect what is written in the commit list.

**Comment by matanshukry** [comment]
yeah I know I'm aware of it. Some order in the issue tracker is still a good thing though.

**Comment by offl** [comment]
Actually you can include that fix in your PR #25971
As testing example, it will be pushed faster

**Comment by matanshukry** [comment]
@offl It is there actually, in the testing example. it's the exact same thing.
I've created a separate PR to make it more organized. If it will be closer instead this can be closed of course.

**Comment by offl** [comment]
I meant as sql file to push with PR

**Comment by matanshukry** [comment]
Relevant PR was merged with .sql, so this issue is already fixed by it.
