### ISSUE TITLE
[3.3.5] - Utgarde Pinnacle: Svala Sorrowgrave Ritual movement

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#25970]
**Description:**

As I have commented here: https://github.com/TrinityCore/TrinityCore/issues/23610#issuecomment-768210146
when the ritual begins (boss health below 50%) and is positioned over the player on the altar, Svala falls towards the player instead of floating up until the sword hits the player

**Expected behaviour:**

she should stay up in the air until the sword hits 
https://www.youtube.com/watch?v=8f8d1aVY75Q <-- min 0:37

Can be fixed adding ```me->SetControlled(true, UNIT_STATE_ROOT);``` when ritual start and remove it when ritual ends, but maybe isn't the proper way, I don't know if need some aura or what can be the proper way

**Steps to reproduce the problem:**

1. .gm on
2. .go cre id 29281
3. .mod hp 10000000
4. .gm off
5. wait until intro ends and svala attack
6. damage svala below 50% hp (.damage 170000)
7. see how svala teleport up but fall to the player position

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f474418651557acb621e9634993738118fb54a7e

**Comment by Ovahlord** [comment]
make sure the boss has the extra flag 512 (0x200) and if not, add it to her to make sure that manually enabling and disabling gravity wont get removed by the core's native movementflag update routine.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24503/files#diff-5a1200f391199fa6d37129c39fcd41829ef61cf6238f64a0d08b3891e1c5c8a3R1

**Comment by Jildor** [comment]
oh yes, she has that flag, the problem is that she continues to chase the player once the ritual begins, that's why I said that adding the ```me-> SetControlled (true, UNIT_STATE_ROOT);```  when ritual start and remove it when ritual ends fixes it, but surely not the best way

**Comment by offl** [comment]
You said
> falls towards the player

Then she should be passive during intro

**Comment by Jildor** [comment]
ah yep, because the visual when she is over player and player is paralyzed (stun) is fall 😄

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0675be4bc3c59142cd47b64f71857e019208e957
