### ISSUE TITLE
Priest - Mind Control VS mobs : no melee attack ?

### ISSUE THREAD

**Issue by kruchor** [TrinityCore/TrinityCore#25982]
**Description:**

Mind control currently works on humanoids mobs (spells, movements, behaviour) but no melee attack is performed. 

**Expected behaviour:**

Mind controled mobs should be able to perform melee attack ('claws' icon). Is this something I've never noticed ? Everything else is fine.

**Steps to reproduce the problem:**

1. Mind control an humanoid mob
2. Attack some other mob
3. Try to initiate a melee attack =>  nothing happens
4. Spells, movements, etc are working as expected

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TC> TrinityCore rev. 1ff4a7e75b56+ 2021-01-27 02:04:30 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Using MySQL version: 100327
Using CMake version: 3.13.4
Compiled on: Linux 5.4.78-2-pve
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../../data/maps. Total size: 251987687 bytes
vmaps directory located in ../../data/vmaps. Total size: 658130721 bytes
mmaps directory located in ../../data/mmaps. Total size: 1962380076 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21011

**Operating system:** 

Debian Buster 10.7

**Comment by illfated** [comment]
Ref. PR #26065 & commit https://github.com/TrinityCore/TrinityCore/commit/f6e52f6b3df92a837787f63514417a7d240144cd

**Comment by illfated** [comment]
> Ref. PR #26065 & commit [f6e52f6](https://github.com/TrinityCore/TrinityCore/commit/f6e52f6b3df92a837787f63514417a7d240144cd)

Please test again. According to some, the issue has been resolved.

**Comment by kruchor** [comment]
Just tested with :

TC> server debug
TC> TrinityCore rev. f6e52f6b3df9+ 2021-02-14 14:38:06 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

It's working now ! Thank you.
