### ISSUE TITLE
Darkening objects

### ISSUE THREAD

**Issue by jedanimo** [TrinityCore/TrinityCore#25999]
**Description:**

I observe some shadows on game objects

**Expected behaviour:**

remove shadows

**Steps to reproduce the problem:**

1. Make blood elf  
2. go to Silvermoon City
3. Logout
4. Login

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

latest 

CHANGEME OS
windows 10

![before](https://user-images.githubusercontent.com/75763206/106393965-13878b00-640b-11eb-9fc9-9bb90ced70b0.jpg)
![after](https://user-images.githubusercontent.com/75763206/106394038-6eb97d80-640b-11eb-832a-50fd931d18b8.jpg)

**Comment by MaxtorCoder** [comment]
Are you using any custom patches + please provide the commit hash instead of saying `latest`

**Comment by Ovahlord** [comment]
client issue. the wotlk client is so old by now that you can rest assure that it's graphics api is getting too outdated

**Comment by Aokromes** [comment]
iirc maximizing quality fixes it.

**Comment by Jildor** [comment]
dup: #20401

**Comment by jedanimo** [comment]
Without any patches

**Comment by jedanimo** [comment]
Thanks Jildor
