### ISSUE TITLE
Event: Requesting a new Lunar Festival Invitation does not work

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#25995]
**Description:**

The [Lunar Festival Harbinger](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15895) does not issue a new invitation to the Lunar Festival when requested.

Stormwind

<details>

![image](https://user-images.githubusercontent.com/66294837/106374651-4a44ad80-63d9-11eb-81aa-967860390c30.png)

</details>

Ironforge

<details>

![image](https://user-images.githubusercontent.com/66294837/106374670-72341100-63d9-11eb-8684-7615fde5fe9a.png)

</details>

.npc details

<details>

![image](https://user-images.githubusercontent.com/66294837/106374698-9ee82880-63d9-11eb-9645-a971f57f9d65.png)

</details>

**Expected behaviour:**

Item [Lunar Festival Invitation](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=21711) should be placed in inventory when requested.

**Steps to reproduce the problem:**

1. Head to a Lunar Festival Harbinger in your capitol city (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15895)  
2. Have completed original quest [Lunar Fireworks](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8867) to obtain an invitation
3. Use it (or lose it)
4. Wait 24hrs (or request another if you deleted it)
5. Request another invitation option is available but does not give item.

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by gygyti** [comment]
what about Segacedi?

-> **[https://imgur.com/a/UYbEIJe](https://imgur.com/a/UYbEIJe)**

[https://www.wowhead.com/npc=32664/segacedi](https://www.wowhead.com/npc=32664/segacedi)
