### ISSUE TITLE
[3.3.5] ICC Profesor Putrice hitbox

### ISSUE THREAD

**Issue by Conscript01** [TrinityCore/TrinityCore#25993]
Description

Professor Putricide have small melee hitbox

**Expected behaviour:**

Professor Putricide should have bigger hitbox, for melee dps its kinda hard to keep in melee radius

https://youtu.be/yJM9nUjNKVw?t=472 check the range of druid force of nature "trees", they are hitting at max distance

I also checked azerothcore - it looks fine there, so i took values from there. These values are for the "basic" model of professor the same, so I believe its correct 

```
UPDATE `creature_model_info` SET `CombatReach` = '7.8' WHERE `creature_model_info`.`DisplayID` = 30993;
UPDATE `creature_model_info` SET `BoundingRadius` = '1.209' WHERE `creature_model_info`.`DisplayID` = 30993;
```

tested and looked fine.

Steps to reproduce the problem

1. .go cr id 36678
2. kill festergut and rotface on the sides.
2. start encounter - get to 3rd phase
3. target boss and use .aura 38505 (shackle)
4. move and observe melee hits

or 

1.  .npc add temp 38216
2. target npc and use .aura 38505 (shackle)
3. move and observe melee hits

**Branch(es):**
3.3.5a
0ba62a4 as i checked recent DB 0b7b7f1 , the problem is still there

**Comment by jackpoz** [comment]
what are the current values ?

**Comment by Conscript01** [comment]
current values are 

| DisplayID | BoundingRadius | CombatReach | Gender | DisplayID_Other_Gender
normal phase    | 30881 | 1.209 | 7.8 | 0 | 0
mutated phase  | 30993 | 0 | 0 | 0 | 0       - this one is not correct

**Comment by Aokromes** [comment]
creature_model_info comes from sniffs. we cannot accept this fix without one wow 3.3.5a sniff.

**Comment by Conscript01** [comment]
this is probably due to some mistake, as this boss uses 2 models during fight. there is no reason to have smaller melee range than "starting" model.

**Comment by offl** [comment]
[8] UNIT_FIELD_BOUNDINGRADIUS: 1.209
[8] UNIT_FIELD_COMBATREACH: 7.8
[8] UNIT_FIELD_DISPLAYID: 30881/4.3273E-41
[8] UNIT_FIELD_NATIVEDISPLAYID: 30881/4.3273E-41

Probably 30993 should have bigger hitbox and picking values from default model is not correct

**Comment by jackpoz** [comment]
so the numbers of the normal phase would work for the mutated phase ? are we sure the mutated phase (which has 0, 0 in the db) fallsback to the normal phase and not to some other default C++ values ?

**Comment by offl** [comment]
The mutated one has 0 0 and core currently correctly interprets them as 0 0
Once we change those 0 0 to sniffed, creature will use them until model is changed to another with another values

**Comment by Ovahlord** [comment]
Look for update_object packets where the display id gets set to 30993 which should also contain combatreach and bounday radius changes. Add them and you're done.

**Comment by Keader** [comment]
Sniffed:

```sql
UPDATE `creature_model_info` SET `BoundingRadius`=1.5, `CombatReach`=9 WHERE `DisplayID`=30993;
```
