### ISSUE TITLE
[Core/System][Feature Request] Support SAI with server side area trigger

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#25990]
**Description:**

Add SAI/smart_scripts support for server side area triggers

**Branch(es):**

master

**TC rev. hash/commit:** 

#25971

Note: will be changed to an actual hash/commit once the PR is complete

**Comment by offl** [comment]
#25971 will close this issue?

**Comment by mdX7** [comment]
> 
> 
> #25971 will close this issue?

negative, that issue will only implement serverside ats itself. SAI implementation for (new) ats gotta be a different pr.

**Comment by Shauren** [comment]
875fd4107f29c00f148ea77c6ff6d49f7ca92b76
