### ISSUE TITLE
Various Stratholm issues

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26004]
**Description:**

- Gate traps are not working at all, when walking through those, they should close and spawn a bunch of rats or maggots
- There is almost no working texts. Here are a few examples I remember : 
*When opening the first gate in elder's square (gauntlet gate) the baron should yell.
*An acolyte should yell whenever a crystal is destroyed.
*bosses have no texts, Ramstein doesn't talk
- Ramstein instantly spawns outside (and is clipping through the door 
![image](https://user-images.githubusercontent.com/40864460/106401934-40e23200-6427-11eb-811c-87dcbd98693e.png) 
). He should be walking from inside and open the door after a delay. +yell and aggro the players

**Expected behaviour:**

https://www.youtube.com/watch?v=R-xD4SEPysU Look at a video of stratholm on classic like this one

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0dee695f3bf1e7eea8082f84e1c552c03a137dab

**Comment by Jinnaix** [comment]
Partially/mostly dup of #19385 - I would suggest adding missing points to the already existing issue.

**Comment by T1ti** [comment]
Oh I searched "stratholm" in the issues and didn't find it, sorry
