### ISSUE TITLE
Creature "Duke Ragereaver" should not be in 3.3.5

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26003]
**Description:**
![image](https://user-images.githubusercontent.com/40864460/106401636-7128d100-6425-11eb-905d-3901be79f2fd.png)
He's a rare patrolling the stratholm entrance at level 45(lol)

He was added in cataclysm, he doesn't belong here https://www.wowhead.com/npc=10820/duke-ragereaver#comments

**Expected behaviour:**

Despawn him

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

0dee695f3bf1e7eea8082f84e1c552c03a137dab

**Comment by Aokromes** [comment]
https://wow.gamepedia.com/Duke_Ragereaver nope, on cataclism the level was changed. the fact is the template exists on 3.3.5a.

**Comment by mweinelt** [comment]
Except wowhead shows this:

> Added in patch 1.12.1.13596

**Comment by T1ti** [comment]
> Except wowhead shows this:
> 
> > Added in patch 1.12.1.13596

Wowhead adds this for everycreature



> https://wow.gamepedia.com/Duke_Ragereaver nope, on cataclism the level was changed. the fact is the template exists on 3.3.5a.

The ID was used in Blizzard's database but he was never spawned.

**Comment by illfated** [comment]
Shame that http://web.archive.org/ does not have any snapshots from before 2012, looks like Duke Ragereaver was 45 then, after the level nerf:
- http://web.archive.org/web/20120326204038/http://www.wowhead.com/npc=10820

According to wowpedia (https://wow.gamepedia.com/Duke_Ragereaver) the level was reduced **_to 45_** (maybe from 55 or higher, related to the rest of EPL?)

**Comment by T1ti** [comment]
https://classic.wowhead.com/npc=10820/duke-ragereaver#comments

He is in Classic's database but was never spawned until cataclysm like a lot of other classic creatures, the guy in classic wowhead is using the wrong website (he said he's lvl 63 lol)

He doesn't exist on Classic.

**Comment by offl** [comment]
In order to understand was creature spawned in TBC or not, we can use old DB
If stats in old DB looks like this, then creature was never spawned
```text
 entry  name             minlevel  maxlevel  minhealth  maxhealth   armor  
------  ---------------  --------  --------  ---------  ---------  --------
 10820  Duke Ragereaver         1         1       5000       5000         0
```
