### ISSUE TITLE
Fix Spells

### ISSUE THREAD

**Issue by DeadSide2** [TrinityCore/TrinityCore#26005]
Priest:
33076 - prayer of restoration - no visual, no healing, does nothing
228260 - does no damage at all
186263 - does not hang a debuff
Druid:
78675 pillar of light does not hang dumb
102560 is a talent that doesn't work. Doesn't morph into the owl
192081 - does not want to change stats
Robber:
193315 - doesn’t fucking shoot a pistol
321507 - does not explode, does not damage
342245 - does not work at all
Shaman:
318038 - does not work
51505 - no visual effect, very bad
Dk:
279302 - does not damage
152280 - does not work
108194 - does not work

**Comment by MaxtorCoder** [comment]
Follow issue template.

**Comment by Jinnaix** [comment]
in b4 closed
