### ISSUE TITLE
Core/Spells Soul Shards (warlock passive)

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26015]
**Description:**

Soul Shards dont generate OOC or by using spells.

**Expected behaviour:**

https://www.wowhead.com/spell=246985/soul-shards
Soul Shards should generate OOC slowly to 3 and should generate by some spells.

example spells:
Shadowbolt: 686 (1 shard)
Demonbolt: 264178 (2 shards)

**Steps to reproduce the problem:**

1. create a Warlock
2. choose one of the 3 specs (all of them use Soul Shards)
3. look at the Soul Shard UI

**Branch(es):**

master

**TC rev. hash/commit:** 

23144d0665504e2e24ee790e900bb8de0df4aa08

**Operating system:** 

Win10

**Comment by MaxtorCoder** [comment]
Possible duplicate? #25754
