### ISSUE TITLE
Core/Dev Cleanup Startup Messages

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#26017]
**Description:**

Currently the startup process is flooded with messages.
Due to the amount of messages the result is unhelpful and on some computers (slow, like mine) is just slows them then.

I believe we should:
1. Create issues to address the actual problem and eventually fix them
2. Remove the messages at the current stage of development, in some way.

Do note that currently those messages are considered error and there is no way to distinguish between them and other actual relevant error messages, so using the current log sysetm isn't a solution.

**Steps to reproduce the problem:**

1. Start the server
2. Notice the many, *many* messages that arise.

**Branch(es):**

master

**Actual issue:**

First I would like to address the actual problem here. Looking at a sample of an error:
`Creature (Entry: 173425) has non-existing faction template (0). This can lead to crashes, set to faction 35.`

As far as I can tell that means our database currently contains many creatures with a non-existing faction.
Do those creatures needs to be handled individually? are hey remenants of old expansions/data?
Would be great if anyone can shed some light on this, or how could one solve this.

**Possible Solutions:**

1. Add a config file boolean that if true, will silence all messages until startup.
2. Detect multiple messages coming from the same source over a short period of time and silence them.
3. Add log configuration that is specific until the startup.

Note: when I say silence I mean out of a file/console. It could mean redirect to another file as well.

I would love to hear more about this from other people; thoughts on the issue it self and your experience with it, about the solutions I proposed and if possible more suggestions on how to solve it.

**Comment by Shauren** [comment]
All of those messages are sent to "sql.sql" logger on level ERROR, it is up to you to configure it the way you want them

**Comment by Aokromes** [comment]
duplicate.

**Comment by matanshukry** [comment]
@Shauren correct me if I'm wrong, but you can't configure it before/after startup. That is, if there is any "sql.sql" error after startup, it will be silenced as well.

@Aokromes link to the other issue?

**Comment by MaxtorCoder** [comment]
> 
> 
> @Shauren correct me if I'm wrong, but you can't configure it before/after startup. That is, if there is any "sql.sql" error after startup, it will be silenced as well.
> 
> @Aokromes link to the other issue?

It works via WorldServer.conf and then scroll all the way down until the log filters. Disable sql.sql

**Comment by matanshukry** [comment]
> > @Shauren correct me if I'm wrong, but you can't configure it before/after startup. That is, if there is any "sql.sql" error after startup, it will be silenced as well.
> > @Aokromes link to the other issue?
> 
> It works via WorldServer.conf and then scroll all the way down until the log filters. Disable sql.sql

Yes, I know how loggers work.

**Comment by MaxtorCoder** [comment]
> Yes, I know how loggers work.

Then what is the issue exactly? :P Disable them and the WorldServer starts way quicker.

**Comment by matanshukry** [comment]
> > Yes, I know how loggers work.
> 
> Then what is the issue exactly? :P Disable them and the WorldServer starts way quicker.

And if you'll ever have any logs from `sql.sql` after the server starts, you'll never know about it. Like I wrote in the message you quoted..

**Comment by matanshukry** [comment]
Just to clarify, people seems to suggest here all errors from `sql.sql` will only appear on startup. While many of them are, some may occur after as well.

Anyway here is the source issue:
#15829

**Comment by Faq** [comment]
@MaxtorCoder  and from what time disabling something is a proper approach? problems should be solved not hidden.

**Comment by MaxtorCoder** [comment]
> @MaxtorCoder  and from what time disabling something is a proper approach? problems should be solved not hidden.

Feel free to fix all errors on master
