### ISSUE TITLE
DB/Creature: Various Drakes in Burning Steppes have incorrect flight height.

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26013]
**Description:**

The larger Drakes in Burning Steppes all walk correctly.

<details>

![image](https://user-images.githubusercontent.com/66294837/106540127-68ceb400-6553-11eb-85d5-61bc14fef185.png)

</details>

However, they all have incorrect heights when they take flight. They are all flying at ground level with half their bodies hidden underground.

Scalding Drakes:

<details>

![image](https://user-images.githubusercontent.com/66294837/106540219-9fa4ca00-6553-11eb-84fc-bb5c507e57f7.png)

</details>

Black Drakes:

<details>

![image](https://user-images.githubusercontent.com/66294837/106550139-a7ba3500-6566-11eb-8909-f6b3b886e591.png)

</details>

Searscale Drakes:

<details>

![image](https://user-images.githubusercontent.com/66294837/106550834-0a600080-6568-11eb-89e8-0e88f17b21b1.png)

</details>

**Expected behaviour:**

The Drakes should be flying above ground level. 

**Steps to reproduce the problem:**

1. Travel to Burning Steppes (Fly or Teleport)  
2. The Drakes are in multiple, scattered(?) locations.
3. You will more than likely see them flying - they will be flying at ground level with half their bodies hidden underground.

NPC Info [Scalding Drakes](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7045):

<details>

![image](https://user-images.githubusercontent.com/66294837/106540750-a849d000-6554-11eb-9681-67b7be830ec6.png)

</details>

NPC Info [Black Drakes](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7044):

<details>

![image](https://user-images.githubusercontent.com/66294837/106550039-6a55a780-6566-11eb-89c5-eb7283481126.png)

</details>

NPC Info [Searscale Drakes](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7046):

<details>

![image](https://user-images.githubusercontent.com/66294837/106550730-d553ae00-6567-11eb-9e95-a6ab09bb72fa.png)

</details>

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by TQPS** [comment]
```sql
SELECT `guid`, `id`, `position_x`, `position_y`, `position_z` FROM creature WHERE guid IN (5505, 3299, 3298, 3302, 3300, 3303, 3301, 3297);
```

| guid | id | position_x | position_y | position_z | 
| ---: | ---: | ---: | ---: | ---: | 
| 3298 | 7044 | -7887.52 | -2901.16 | 133.264 | 
| 3299 | 7044 | -7587 | -2753.57 | 133.237 | 
| 5505 | 7044 | -8143.2 | -2888.34 | 135.543 | 
| 3300 | 7045 | -8183.42 | -2032.31 | 146.48 | 
| 3302 | 7045 | -8171.75 | -2133.57 | 135.51 | 
| 3297 | 7046 | -8055.33 | -777.452 | 131.311 | 
| 3301 | 7046 | -8240.96 | -1204.55 | 142.663 | 
| 3303 | 7046 | -8342.42 | -985.418 | 183.41 |

**Comment by offl** [comment]
If I'm not wrong this particular case will be solved by removing Flight state completely from them because they should not fly at all
However I'm not able to find the issue about flying on the ground creatures (if they're on the ground, they should stand and not fly). I remember there was one or more and was never fixed

**Comment by TQPS** [comment]
If it helps, just found this clip of Classic WOW [1:14-1:28](https://youtu.be/t7mGg5DPH-A?t=74) - this guy is farming in Burning Steppes and he passes 2 drakes at least hovering.

**Comment by Ovahlord** [comment]
They're not flying, they are hovering or better said, they are suposed to hover. Flight = 0, Ground = 2

**Comment by offl** [comment]
They do literally nothing, treat as already fixed
All I need here is that ancient issue where people already described problem with flying creatures still flying if they are on the ground
That practic with closing unsolved issues if no response about fixed or not sometimes is awful because sometimes I can't find old issues and need to write new
