### ISSUE TITLE
3.3.5 - Server crash on entering Zul'Gurub

### ISSUE THREAD

**Issue by jiayuandeng** [TrinityCore/TrinityCore#26018]
**Description:**

Crash log: https://gist.github.com/jiayuandeng/56c26e8d526e7a27dfdd38e40a9e04b5
Crashing at line: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Instances/InstanceScript.cpp#L182
I'm not sure if it is an issue of TC, or the repack I'm using (https://github.com/conan513/spp-wotlk-npcbots-repack). I've searched around and did not see any existing issue about this. I've attached the crash log and dump file, and any help would be appreciated!

**Expected behaviour:**

Server not crash.

**Steps to reproduce the problem:**

1. Enter Zul'Gurub instance.

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

TrinityCore rev. 67a6474040f8

**Operating system:** 

Windows 10 Professional (Version 10.0, Build 18363)
[67a6474040f8_worldserver.exe_[2-2_6-3-18].dmp.zip](https://github.com/TrinityCore/TrinityCore/files/5911950/67a6474040f8_worldserver.exe_.2-2_6-3-18.dmp.zip)

**Comment by Aokromes** [comment]
we don't support repacks.

**Comment by Jinnaix** [comment]
This is not TC related, it was fixed here monnths ago
