### ISSUE TITLE
Seed of corruption's explosion damages through walls and structures.

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26010]
**Description:**

Seed of corruption's explosion will hit creatures in other rooms through walls, this is especially bad in dungeons, a swarm of creatures aggroed from another room will run at you.

Here's an example in scholomance it hits the skeletons in a room under the ground
![image](https://user-images.githubusercontent.com/40864460/106532631-d1387980-64f0-11eb-97b9-9e25615c1cd3.png)

**Expected behaviour:**

Seed of corruption should not hit mobs behind walls or out of LOS

**Steps to reproduce the problem:**

1. spawn a mob anywhere with another mob behind a wall, or udner it, make seed explode, see if it damages the other mobs. Or just try it in scholomance

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

92c8ffc047ea35ea9a534a878cd4be5726f20974

**Operating system:** 

windows

**Comment by Jildor** [comment]
Seed of Corruption aoe damage spell has:
```
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
```
so I think is intended

**Comment by jackpoz** [comment]
According to https://wow.gamepedia.com/Seed_of_Corruption
> Patch 2.3.0 (2007-11-13): Seed of Corruption detonation will now obey line of sight.

https://wow.gamepedia.com/Patch_2.3.0
> [Seed of Corruption] detonation will now obey line of sight.

**Comment by jackpoz** [comment]
770a4499df02aa0daf08decc510e12c75d4dcf25
