### ISSUE TITLE
DB/page_text: "Hallowed Scroll" page text typo correction

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#26026]
**Description:**

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1568/undertaker-mordo
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=363/rude-awakening
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1569/shadow-priest-sarvis
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=364/the-mindless-ones
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3097/hallowed-scroll
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=9569/hallowed-scroll

In the "Hallowed Scroll" item page text, there is a "modernized" typo in "Feel blessed that you're spirit was not released" (TDB `page_text`.`Text`.`ID` 2467):

```
Feel blessed that you're spirit was not released to the Nether, $N. Feel even more blessed that I decided you were worth the effort to write this scroll for.

The people you once knew, perhaps even cared for, are no longer! You must learn to "live" with that for the rest of your now unnatural life. I suggest you learn to deal with that first.

If you think you're ready for the trials ahead, then seek me out in the church in Deathknell.

- Dark Cleric Duesten, Priest Trainer
```

**Expected behaviour:**

```
Feel blessed that your spirit was not released to the Nether, $N. Feel even more blessed that I decided you were worth the effort to write this scroll for.

The people you once knew, perhaps even cared for, are no longer! You must learn to "live" with that for the rest of your now unnatural life. I suggest you learn to deal with that first.

If you think you're ready for the trials ahead, then seek me out in the church in Deathknell.

- Dark Cleric Duesten, Priest Trainer
```

**Steps to reproduce the problem:**

1. Start an undead priest character and go down to the church in Deathknell, from the "tomb" spawn point.
 (You can do the very first quest "Rude Awakening" from Undertaker Mordo if you want to.)
2. Accept the first quest from https://www.wowhead.com/npc=1569/shadow-priest-sarvis, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=364/the-mindless-ones
3. `.quest complete 364` , open the gossip from Shadow Priest Sarvis to hand in the quest.
4. Get quest 3097 "Hallowed Scroll" and open the scroll item 9569 to read the text. Note the typo in the first sentence.

**Suggested solution:**

```sql
-- `page_text`.`ID` 2467, "Hallowed Scroll":
UPDATE `page_text` SET `Text` = 'Feel blessed that your spirit was not released to the Nether, $N. Feel even more blessed that I decided you were worth the effort to write this scroll for.$B$BThe people you once knew, perhaps even cared for, are no longer! You must learn to "live" with that for the rest of your now unnatural life. I suggest you learn to deal with that first.$B$BIf you think you\'re ready for the trials ahead, then seek me out in the church in Deathknell.$B$B- Dark Cleric Duesten, Priest Trainer' WHERE `ID`= 2467;
```

**Branch(es):**

3.3.5, not sure if the same item and `page_text`.`ID` is used in master (quest ID has changed)

**TC rev. hash/commit:** 

TrinityCore rev. e5518b5 2021-02-01 16:15:44 +0200 (3.3.5 branch) (Win64, Release, Static)
```sql
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.19.2
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21011
```

**Operating system:** 

Windows 10 Home x64 Version 20H2 (OS Build 19042.746)

**Comment by mdX7** [comment]
![grafik](https://user-images.githubusercontent.com/12143653/106775133-208ebf00-6643-11eb-982a-8e69e3205db4.png)
Quickly checked it on classic, seems fine.

**Comment by illfated** [comment]
Yup. Someone messed up 1 word on input to TDB (you're vs. your).
