### ISSUE TITLE
Segacedi swims wrong

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26024]
Segacedi in the same positions floats on top of the platform 

-> **[https://imgur.com/a/UYbEIJe](https://imgur.com/a/UYbEIJe)**

[https://www.wowhead.com/npc=32664/segacedi](https://www.wowhead.com/npc=32664/segacedi)

3.3.5
rev. 0dee695

**Comment by jackpoz** [comment]
this issue is caused by using mmaps for an underwater path, with mmaps storing Z only of the surface.

**Comment by jackpoz** [comment]
@offl please add CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING to https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32664

**Comment by illfated** [comment]
https://trinitycore.net/df/d66/Creature_8h.html#a509c490881d9ef2abce208236910f0a5a432399b2532ba8bac59cf2d4a9896e31
```
59  CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING = 0x20000000, // creature ignore pathfinding
```
