### ISSUE TITLE
Dire maul North issues

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26022]
**Description:**

Some of the bugs are already reported here https://github.com/TrinityCore/TrinityCore/issues/6429

I did a normal run of Dire Maul north (not tribute) and here are some of the bugs I noticed  : 
- random ogre pat running super fast
![image](https://user-images.githubusercontent.com/40864460/106648461-99810e80-6590-11eb-8736-d9510d182acb.png)
- update : this pack has 5 ogres, it's actually random on classic, this pack has different variations but I've never seen 5 mobs, always 3 or 4.
- - This is a variation similar from classic : only 3 mobs 
![image](https://user-images.githubusercontent.com/40864460/106677615-571ff780-65b9-11eb-830e-bf35b016a220.png)

- door sound is bugged after opening it, just open it and stand near it will destroy your ears : 
![image](https://user-images.githubusercontent.com/40864460/106648820-0eecdf00-6591-11eb-83c6-b3fd2c036d06.png) 
I think that bug also happens on classic sometimes but there it seems to happen all the time and faster ?
- Insect packs aren't linked properly, currently you can pull them separately, they should all be linked together. 
![image](https://user-images.githubusercontent.com/40864460/106648950-3cd22380-6591-11eb-96c8-4c4ac98170ec.png)
Also they should be much more packed, they are super spread out currently.
- guard slip'kik moves way too fast
- broken trap quest is bugged 
![image](https://user-images.githubusercontent.com/40864460/106649088-668b4a80-6591-11eb-85cd-7292430ec52d.png) 
- the goblin quest giver is missing https://classicdb.ch/?npc=14338 (not sure if he's still here on 3.3.5 or not)
- A lot of trash isn't linked properly and can be pulled separately, making the instance a lot easier than intended. **Honestly it even looks like not a single mob is linked and there is only the default range aggro behavior.**
- captain kromcrush guards adds should come running from the previous room instead of spawning instantly on him
- -hyena pack before the king aren't linked just like the insects pack
- gordok spirits are hostile and attack the players on sight. they should be neutral and immune
- cho'rush spaming chain lightning instead of lightning bolt, he should only be using chain lightning every 10/12sec, I've not seen him use lightning bolt. His smart ai script looks fine though, maybe he's ignoring the script or lightning bolt is missing from his spell kit.
![image](https://user-images.githubusercontent.com/40864460/106649919-84a57a80-6592-11eb-9041-38813b587f0a.png)

- cho'rush the observer is hostile after killing the king and no dialogs

**Those are only the very obvious issues I noticed while doing a normal run.**

**Expected behaviour:**

already described

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

184372500d1f2faa41d682bea04eb103487a4adb

**Comment by dr-j** [comment]
The goblin quest giver should be present or was at least the last time I checked

**Comment by T1ti** [comment]
> The goblin quest giver should be present or was at least the last time I checked

![image](https://user-images.githubusercontent.com/40864460/106680866-9ea98200-65bf-11eb-8905-3bf20afb898b.png)

I've ran it like 3 times on TC nad haven't seen him yet

**Comment by dr-j** [comment]
Well it looks like his ball and chain is still there but no sign of knot anymore

**Comment by Conscript01** [comment]
confirmed, he was missing even on 0ba62a4

**Comment by offl** [comment]
> cho'rush spaming chain lightning instead of lightning bolt, he should only be using chain lightning every 10/12sec, I've not seen him use lightning bolt. His smart ai script looks fine though, maybe he's ignoring the script or lightning bolt is missing from his spell kit.

Cannot reproduce but fixed another issue. I was thinking I caused those bugs by https://github.com/TrinityCore/TrinityCore/commit/3041c3ae36d73cb89df107765f33cf14955ad07c but actually not

> cho'rush the observer is hostile after killing the king and no dialogs

Handled by aura you take after talking with Mizzle. idk if correct or not

**Comment by offl** [comment]
No, not fixed

**Comment by TQPS** [comment]
Knot Thimblejack is spawning and quest works fine, but after you free him, his cache spawns underneath Immol'thar who's sitting in Dire Maul West. Workaround is to run back to the start of North, enter the library and run West in reverse to take out the pylons.

Also, the broken trap was missing text (screenshot above)  but you could still complete it - a recent change has been made that the quest no longer shows and trap is no longer interactable, which means full tribute runs are 1 boss short.

**Comment by dr-j** [comment]
Well co-ordinates used to spawn cache in sai look correct if you use the following

1) .tele diremaul and enter instance
2) .go xyz 583.6 523.44 -25.4 (These are co-ords from sai which is used to spawn cache)

You will end up next to the left of Knot Thimblejack

**Comment by TQPS** [comment]
Then something is up.

Knot is where he should be and quest is good to go.

<details>

![image](https://user-images.githubusercontent.com/66294837/133161287-0719cdf7-ed01-487c-80a6-4b1a36aeb409.png)

</details>

Free him but no cache.

<details>

![image](https://user-images.githubusercontent.com/66294837/133161417-ea0c65b0-54ed-46a0-be6f-2af61009a6cd.png)

</details>

I've run Dire Maul quite a few times so I know where to go to get it - it spawns in Dire Maul West

<details>

![image](https://user-images.githubusercontent.com/66294837/133161736-51094176-3681-465b-b2db-41c4ce24fcb7.png)

</details>

```sql
SELECT target_x, target_y, target_z, target_o, comment FROM smart_scripts WHERE `entryorguid` = 1433800 AND `id` = 3;

```
smart_scripts
---
| target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | --- | 
| 583.6 | 523.44 | -25.4 | 3.1848 | Knot - Script - Spawn Cache | 
```

What am I missing here?

**Comment by dr-j** [comment]
Ok found this and looks like this change was related to cache so does not despawn when knot does
~~~sql
UPDATE `smart_scripts` SET `action_param3`='1' WHERE  `entryorguid`=1433800 AND `source_type`=9 AND `id`=3 AND `link`=0;

**Comment by CraftedRO** [comment]
Guard Slip'kik fixed here https://github.com/TrinityCore/TrinityCore/commit/467b717c5cd20151c4222b077c8af7a8e5d0e83d

**Comment by CraftedRO** [comment]
Knot Thimblejack spawn position fixed here: https://github.com/TrinityCore/TrinityCore/commit/310e001d3f12fd3b50c23400e4d43319b2e3183f
