### ISSUE TITLE
[3.3.5] Equipment Manager

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#26030]
**Description:**

https://wowwiki-archive.fandom.com/wiki/Equipment_Manager
When you create more than one set in the equipment manager, when you logout / login, only the last set you created is saved
Currently to save more than one set, you must create one by one and each time you create one you must logout / login

**Expected behaviour:**

I have no idea if it's a bug or it really worked like this in retail

**Steps to reproduce the problem:**

1. Login with a player and enable Equipment Manager (Interface->Features)
2. Create two or more sets
3. Logout and login

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

7cf9a2a028811170cda3c41d681836d7aa7505fd

**Comment by CraftedRO** [comment]
d5ef68bc9b45 confirm and also tested on wotlk classic ptr and you can do 10 max sets in manager and all of them are saved:

https://github.com/TrinityCore/TrinityCore/assets/24683355/bad6a7e2-50e4-45a4-8981-3f2e8577c67c
