### ISSUE TITLE
Core/Waypoints: orientation field 0 is wrongly treated as no orientation

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#26037]
**Description:**

`orientation` field 0 is wrongly treated as no orientation while 0 is valid orientation and is used by Blizz
Of course we can use 6.2831853072 but it's not the same

**Expected behaviour:**

treat 0 as valid orientation

**Branch(es):** both
**TC rev. hash/commit:** 3cb70ee62a3f30ae492a6985b5306052d90c89c4

**Comment by Ovahlord** [comment]
https://git.io/JtgVD there. feel free to test that

**Comment by offl** [comment]
Thanks, 335 also uses orientation in `waypoints`
Do we need something else or just sql?

**Comment by Ovahlord** [comment]
the part where the core loads orientation values from the waypoints table needs the same treatment then as waypoint_data

**Comment by malcrom** [comment]
It was always like that. We had to use 0.001 or something for 0 orientation. Poor design.

**Comment by Shauren** [comment]
4747515872775553de35cc3267e1ccd5e0076ca4
