### ISSUE TITLE
search Solocraft Script for shadowlands

### ISSUE THREAD

**Issue by nick25** [TrinityCore/TrinityCore#26033]
Hallo,

suche für shadowlands das Solocraft Script. Leider funktionieren alle Scripte nur bis 3.3.5.
Ich würde mich sehr freuen wenn es jemand uppen würde.

Vielen Dank
__________________________________________________ _______________

Hello,

search for the solo craft script for shadowlands. Unfortunately, all scripts only work up to 3.3.5.
I would be very happy if someone would give it up.

Many Thanks

**Comment by MaxtorCoder** [comment]
Ask on the forum, this is for core issues only.
