### ISSUE TITLE
DB/Spells: Riding skills

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#26032]
**Description:**

Fix to the current riding skills one can learn at the trainer

**Expected behaviour:**

Rank | Speed | Training cost | Required level
-- | -- | -- | --
Apprentice Riding | 60% | 100s | 10
Journeyman Riding | 100% | 50g | 20
Expert Riding | 150% | 250g | 30
Master Riding | 310% | 5,000g | 40

**Steps to reproduce the problem:**

1. Create a new character
2. Go to a riding trainer
3. Look at the available spells.

**Branch(es):**

Master

**TC rev. hash/commit:** 

23144d0665504e2e24ee790e900bb8de0df4aa08

**Operating system:** 

Windows 10

**Fix:**

I removed the content since it contains a hack. To fix the issue there is also some code changes that have to be done, so it will be done in a separate issue. This will be closed soon.

**Comment by Naddley** [comment]
The cost of "Apprentice Riding" should not be 9 copper.
Retail costs are 95 silver :D

![WoWScrnShot_020321_215013](https://user-images.githubusercontent.com/64811442/106807859-edabf180-6669-11eb-9214-522fe9dbd393.jpg)

**Comment by matanshukry** [comment]
Quick note:
the hotfix doesn't seem to be needed on the client and it's used because we use the .db2 on the server side.

Not sure if it's known or not, so just fyi.

**Comment by mdX7** [comment]
So the guess here is that db2 data of `skill_line_ability` is actually outdated (maybe blizzard is not updating the shipped one anymore?). Thats why we require that hotfix statement.

**Comment by funjoker** [comment]
I might take a look later

**Comment by funjoker** [comment]
```
-- -- Apprentice riding skill
UPDATE `trainer_spell` SET `MoneyCost` = 1000, `ReqLevel` = 10 WHERE `SpellId` = 33389;
```
MoneyCost must be 10000

**Comment by matanshukry** [comment]
> ```
> -- -- Apprentice riding skill
> UPDATE `trainer_spell` SET `MoneyCost` = 1000, `ReqLevel` = 10 WHERE `SpellId` = 33389;
> ```
> 
> MoneyCost must be 10000

Price should be 10s, no?

I was following this:
https://www.wowhead.com/guides/shadowlands-flying-riding-pathfinder

**Comment by Naddley** [comment]
On Retail it was 95 silver tested it yesterday with a fresh Character

**Comment by matanshukry** [comment]
> On Retail it was 95 silver tested it yesterday with a fresh Character

I'm guessing you have some sort of discount from reputation and the price is 100s then; cool.

**Comment by Naddley** [comment]
Costs on Retail with a fresh lvl 1 Char :)

![WoWScrnShot_020421_202527](https://user-images.githubusercontent.com/64811442/106944696-35dd1980-6727-11eb-9821-75b0e506f83a.jpg)

**Comment by matanshukry** [comment]
@Naddley What's the reputation with stormwind on a newly fresh lvl 1 char?

**Comment by Naddley** [comment]
Friendly on every Alliance Race faction. Core seems to handle the price right ;D

**Comment by matanshukry** [comment]
10000 it is then.
Thanks for checking it out btw :D

**Comment by funjoker** [comment]
hotfix part is a hack btw
we ahve to investigate it

**Comment by illfated** [comment]
@matanshukry : regarding your ticket title "[PR] DB/Spells - Riding Skills" — may I suggest a few topical adjustments?

1. Ticket titles don't use "PR" as part of the title, unless directly referring to a PR (Pull Request) page.
2. The preferred (although not required) way of forming the title is by separating the tag/keywords from the description with a colon (`:`) instead of a dash (`-`).

Based on this, I would like to recommend the following: **DB/Spells: Riding skills + Training cost**

**Comment by matanshukry** [comment]
@illfated Cool, I'll follow that.
But what can I add to the title to distinguish between issues that are related to DB rather than ones that actually contains the fixes? (since submitting PRs with only sql files is prohibited / done using issues)

**Comment by illfated** [comment]
> what can I add to the title to distinguish between issues that are related to DB rather than ones that actually contains the fixes?

No difference required in the ticket title. TrinityCore does not distinguish between tickets containing solutions and those only describing the issue. GitHub labels are used to highlight the category, just like **[Comp-Database]** for DB related issues, and **[Feedback-PatchFix]** for tickets containing solutions.

BTW, did you intend to close this ticket? Unless you want any follow-up moved to a PR or other ticket, you could leave this one open.

**Comment by matanshukry** [comment]
Yeah I did intend to close this ticket.
This issue was meant as a fix, but now I'm gonna do it using a PR since it will include c++ code as well and will be a different fix.

This issue can be left as one simply describing the problem, it just feels weird having an issue for a PR I'm going to create soon.
You can reopen it if you want though.

**Comment by illfated** [comment]
Thank you for explaining, the details are good, as well as the decision to close this ticket. Thank you. 👍🏻
