### ISSUE TITLE
Vampiric Duskbat (NPC) is not dropping any loot

### ISSUE THREAD

**Issue by KarMaSSo** [TrinityCore/TrinityCore#26045]
**Description:**

Vampiric Duskbat (NPC) is not dropping any loot in location Tirisfal Glades.

**Expected behaviour:**

Vampiric Duskbat (NPC) should give player loot.

**Steps to reproduce the problem:**

Kill Vampiric Duskbat (NPC) multiple times, You will obtain no loot.

**Branch(es):**

3.3.5

**Operating system:** 

Windows 10 64bit

**Comment by illfated** [comment]
TrinityCore rev. 3cb70ee62a3f 2021-02-04 15:11:22 +0200 (3.3.5 branch) (Win64, Release, Static), TDB 335.21011
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1554/vampiric-duskbat

Although the ticket above lacks core revision hash, looking at the current DB content, it seems to make a valid point.
```sql
SELECT * FROM `version`;
```
```
core_version                                                                                     core_revision  db_version     cache_id
-----------------------------------------------------------------------------------------------  -------------  -------------  --------
TrinityCore rev. 3cb70ee62a3f 2021-02-04 15:11:22 +0200 (3.3.5 branch) (Win64, Release, Static)  3cb70ee62a3f   TDB 335.21011     21011
```
```sql
SELECT * FROM `creature_loot_template` WHERE `Entry`= 1554;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
 1554   11111      11111     0.1              0         1        0         1         1  (NULL)
```
This output indicates a drop rate of 0.1 % (a chance of 1 in 1000), which is pretty low, but it gets worse:
```sql
SELECT * FROM `reference_loot_template` WHERE `Entry`= 11111;
```
```
Entry    Item  Reference  Chance  QuestRequired  LootMode  GroupId  MinCount  MaxCount  Comment
-----  ------  ---------  ------  -------------  --------  -------  --------  --------  -------
11111     805          0       0              0         1        1         1         1  (NULL)
11111     828          0       0              0         1        1         1         1  (NULL)
11111    4496          0       0              0         1        1         1         1  (NULL)
11111    5571          0       0              0         1        1         1         1  (NULL)
11111    5572          0       0              0         1        1         1         1  (NULL)
```
Seeing that the chance is reduced to 0 here, it looks like there is no chance at all for a drop to occur.

The calculation of 0.02% on tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=1554 looks odd, but I don't know how the chance is calculated.

- http://web.archive.org/web/20100427065123/http://www.wowhead.com:80/npc=1554
- https://www.wowhead.com/npc=1554/vampiric-duskbat

Looking at the wowhead page from 2010-04-27 (which does not show much), it looks like there should be a lot more variation in the loot.
The current page (https://www.wowhead.com/npc=1554/vampiric-duskbat#drops;0-19+16+1) could indicate that there should be at least some scrap items directly related to bats in general, like Chipped Claw, Dried Bat Blood, Ruined Pelt, Bloody Bat Fang, and Broken Bat Fang (among other low-level items).
