### ISSUE TITLE
DB/Quest: Fix quest chain for Human Hunter in Northshire.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#26046]
**Description:**
The quest chain was interrupted when quest [28759](https://www.wowhead.com/quest=28759/lions-for-lambs) "Lions for Lambs" was completed. 
In `quest_template_addon` the quest `ID`=28780 has in `PrevQuestID`=26917 which is incorrect. 
Quest [26917](https://www.wowhead.com/quest=26917/the-hunters-path) "The Hunter's Path" has been left out of the quest chain for the Human - Hunter. 

**Expected behaviour:**
```sql
-- Quest 28780 Join the Battle!
UPDATE `quest_template_addon` SET `PrevQuestID`=28759 WHERE `ID`=28780;
```

**Steps to reproduce the problem:**

1. Create a Human Hunter player.   
2. Complete quest 28767 Beating Them Back!
3. Complete quest 28759 Lions for Lambs
4. The quest chain is broken. 

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 5a7560e 2021-02-06 23:39:27 -0500 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**  Windows 10 Pro. 20H2

**Comment by TQPS** [comment]
Same as issue #26047

Confirmed! This is for all classes since their previous level 3 class quests, introduced in CATA have since been removed.

```sql
-- Fix quest chains after class quests removed
UPDATE `quest_template_addon` SET `PrevQuestID`=28759 WHERE `ID`=28780; -- Hunter
UPDATE `quest_template_addon` SET `PrevQuestID`=28769 WHERE `ID`=28784; -- Mage
UPDATE `quest_template_addon` SET `PrevQuestID`=28770 WHERE `ID`=28785; -- Paladin
UPDATE `quest_template_addon` SET `PrevQuestID`=28771 WHERE `ID`=28786; -- Priest
UPDATE `quest_template_addon` SET `PrevQuestID`=28772 WHERE `ID`=28787; -- Rogue
UPDATE `quest_template_addon` SET `PrevQuestID`=28773 WHERE `ID`=28788; -- Warlock
UPDATE `quest_template_addon` SET `PrevQuestID`=28774 WHERE `ID`=28789; -- Warrior
```

**Comment by osleyder85** [comment]
This is fixed at https://github.com/TrinityCore/TrinityCore/issues/26047
