### ISSUE TITLE
DB/Quest: Fix quest chains after class quests removed

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#26047]
**Description:**
The quest chain was interrupted when quest [28774](https://www.wowhead.com/quest=28774/lions-for-lambs) "Lions for Lambs" was completed. 
In `quest_template_addon` the quest `ID`=28789 has in `PrevQuestID`=26913 which is incorrect. 
Quest [26913](https://www.wowhead.com/quest=26913/charging-into-battle) "Charging into Battle" has been left out of the quest chain for the Human - Warrior. 

**Expected behaviour:**
```sql
-- Hunter
UPDATE `quest_template_addon` SET `PrevQuestID`=28759 WHERE `ID`=28780; -- Join the Battle!
-- Mage
UPDATE `quest_template_addon` SET `PrevQuestID`=28769 WHERE `ID`=28784; -- Join the Battle!
-- Paladin
UPDATE `quest_template_addon` SET `PrevQuestID`=28770 WHERE `ID`=28785; -- Join the Battle!
-- Priest
UPDATE `quest_template_addon` SET `PrevQuestID`=28771 WHERE `ID`=28786; -- Join the Battle!
-- Rogue
UPDATE `quest_template_addon` SET `PrevQuestID`=28772 WHERE `ID`=28787; -- Join the Battle!
-- Warlock
UPDATE `quest_template_addon` SET `PrevQuestID`=28773 WHERE `ID`=28788; -- Join the Battle!
-- Warrior
UPDATE `quest_template_addon` SET `PrevQuestID`=28774 WHERE `ID`=28789; -- Join the Battle!
```

**Steps to reproduce the problem:**

1. Create Alliance Player   
2. Complete 1st and 2nd quests.
3. The quest chain is broken. 

**Branch(es):** master

**TC rev. hash/commit:** 
TrinityCore rev. 5a7560e 2021-02-06 23:39:27 -0500 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:**  Windows 10 Pro. 20H2

**Comment by TQPS** [comment]
Confirmed! This is for all classes since their previous level 3 class quests, introduced in CATA have since been removed.

```sql
-- Fix quest chains after class quests removed
UPDATE `quest_template_addon` SET `PrevQuestID`=28759 WHERE `ID`=28780; -- Hunter
UPDATE `quest_template_addon` SET `PrevQuestID`=28769 WHERE `ID`=28784; -- Mage
UPDATE `quest_template_addon` SET `PrevQuestID`=28770 WHERE `ID`=28785; -- Paladin
UPDATE `quest_template_addon` SET `PrevQuestID`=28771 WHERE `ID`=28786; -- Priest
UPDATE `quest_template_addon` SET `PrevQuestID`=28772 WHERE `ID`=28787; -- Rogue
UPDATE `quest_template_addon` SET `PrevQuestID`=28773 WHERE `ID`=28788; -- Warlock
UPDATE `quest_template_addon` SET `PrevQuestID`=28774 WHERE `ID`=28789; -- Warrior
```

**Comment by TQPS** [comment]
Can confirm this works for mage.

Before applying - Quest "Lions for Lambs" just finishes with no followup quest.

<details>

![image](https://user-images.githubusercontent.com/66294837/130696891-763498b8-cd5b-4632-9a5e-ed2e65ec4b43.png)

</details>

After applying - Marshal now supplies the quest

<details>

![image](https://user-images.githubusercontent.com/66294837/130697078-69b9da5f-ac69-47d7-ba20-b96a2fe68016.png)

![image](https://user-images.githubusercontent.com/66294837/130697112-dca27ff4-750b-4a74-93dd-ebe7f65094a0.png)

</details>
