### ISSUE TITLE
Outland map diff

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#26048]
**Description:**

Lately I have seen how the diff has increased in the outland map (530)
https://snapshot.raintank.io/dashboard/snapshot/vtuZNUlbc9hTLeTnLGRU7pB2IIOG2CQK?orgId=2

look at the comparison of the graph that I put a few days ago here: https://github.com/TrinityCore/TrinityCore/issues/24356#issuecomment-765901079
https://snapshot.raintank.io/dashboard/snapshot/550eKz1RapY1kWoUUh1GJv3UdlQCd1iZ?orgId=2

**Steps to reproduce the problem:**

I don't know, maybe it could be related to these commits, they have smart_scripts with setactive
https://github.com/TrinityCore/TrinityCore/commit/8c43abaeb291eba1d46a00f3412487856f444e2d

https://github.com/TrinityCore/TrinityCore/commit/c09bd08f811dc97d94fc8aed5a8179a668ff001b

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

d2be584f99a63a165cfd1d047f460a8ebfb87ac3

**Operating system:** 

debian10

**Comment by Shauren** [comment]
setActive? ffs
