### ISSUE TITLE
Core/World: MovementOpcode flow with SetInWater is incorrect.

### ISSUE THREAD

**Issue by matanshukry** [TrinityCore/TrinityCore#26057]
**Description:**

Currently when a movement opcode is received from the client, one that travels from inside the water to outside:

1. we are calling `SetInWater` method depending on packet info and position
 1.1 We are removing all auras that need water/land (depending on change)
   1.1.1 Druid travel form spell script will check to what aura it should change.
           - It will try water form, but due to IsWater() flags being false, it can't do it.
           - It will try fly form, but it will check if it can fly based on the current position. The current position is underwater, hence you can't fly underwater.
2. After that, we are calling `UpdatePosition` with the new position.

reference:
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Handlers/MovementHandler.cpp#L300

**Expected behaviour:**

Druid form should detect the correct form to which it should change into.

**Steps to reproduce the problem:**

1. Create a druid
2. Level it to max level
3. Learn riding skills (at least include flying)
4. Go into water
5. Use travel form (change into aquatic form)
6. Jump outside (you wont' be transformed into flight form)

**Branch(es):**

master

**TC rev. hash/commit:** 

5a7560e57c37fbda511b492ea7d7c47f8e68123f

**Operating system:** 

Windows 10

**Quick suggestion:** 

what will happen if we try to update the position before calling `SetInWater`?

**Comment by matanshukry** [comment]
@jackpoz I was hinted you may be familiar with that area. Any thoughts?

**Comment by jackpoz** [comment]
I don't remember working with this particular bit of code but I wouldn't be surprised if the order of things is causing some issues.

I guess it makes sense to first update the position and then set the inwater status (but we need to store the IsInWater() status before and after UpdatePosition() )

**Comment by matanshukry** [comment]
@jackpoz yeah I imagine such thing would happen.
What do you think about simply delaying the 2 extra lines after the SetInWater to after UpdatePosition? something like this:

```
void Player::SetInWater(bool apply)
{
    m_isInWater = apply;
    m_applyIsInWater = apply ? PostInWaterFlags::Apply : PostInWaterFlags::Remove;
    // RemoveAurasWithInterruptFlags(apply ? AURA_INTERRUPT_FLAG_NOT_ABOVEWATER : AURA_INTERRUPT_FLAG_NOT_UNDERWATER);
    // getHostileRefManager().updateThreatTables();
}

void Player::PostUpdatePosition()
{
    if (m_applyIsInWater == PostInWaterFlags::None)
        return;
    
    bool apply = m_applyIsInWater == PostInWaterFlags::Apply;
    RemoveAurasWithInterruptFlags(apply ? AURA_INTERRUPT_FLAG_NOT_ABOVEWATER : AURA_INTERRUPT_FLAG_NOT_UNDERWATER);
    getHostileRefManager().updateThreatTables();
}

void WorldSession::HandleMovementOpcode(OpcodeClient opcode, MovementInfo& movementInfo)
{
    ...
    if (plrMover && ((movementInfo.flags & MOVEMENTFLAG_SWIMMING) != 0) != plrMover->IsInWater())
    {
        // now client not include swimming flag in case jumping under water
        plrMover->SetInWater(!plrMover->IsInWater() || plrMover->GetMap()->IsUnderWater(plrMover->GetPhaseShift(), movementInfo.pos.GetPositionX(), movementInfo.pos.GetPositionY(), movementInfo.pos.GetPositionZ()));
    }

    mover->UpdatePosition(movementInfo.pos);
    if (plrMover)
        plrMover->PostUpdatePosition();
}
```

**Comment by jackpoz** [comment]
Personally I would prefer to call the current SetInWater() after UpdatePosition(), without adding PostUpdatePosition(), or at least giving it a try to see how bad that is.

I can't help much more with this other than sharing my experience that one just tries and checks what breaks or keeps an eye open in the days/weeks after applying the change to see if any related GitHub issue shows up.

**Comment by matanshukry** [comment]
@jackpoz cool. You have a lot more experience in this project than I do, and if you're willing to give it a try so do I. I'll try that soon and try a few things. If it looks fine I'll create a PR for it.

**Comment by matanshukry** [comment]
<details>
  <summary>Made a few checks and found out few things:</summary>

Regarding liquid/water:
1. There seems to be 2 different methods on the player to check if he's in wateR:
  1.1. `IsInWater` - which will return the result of a member variable named `m_isInWater`.
  1.2. using map and position info (e.g. `GetLiquidStatus`).
2. The `m_isInWater` seems to be controlled by the client. While we set it on the result of `GetLiquidStatus`, the position we pass to that function is the one we are getting from the client, not the one the player currently has.
3. Seems that multiple places, even in the same flow, use both methods. Perhaps I'm just not familiar with the code enough, but there doesn't seem to be a consideration of which one should be used where.

Also:
1. Calling `SetInWater` will call:
```
    // apply is the result of calling
    // plrMover->GetMap()->IsUnderWater(plrMover->GetPhaseShift(), movementInfo.pos.GetPositionX(), movementInfo.pos.GetPositionY(), movementInfo.pos.GetPositionZ());
    RemoveAurasWithInterruptFlags(apply ? AURA_INTERRUPT_FLAG_NOT_ABOVEWATER : AURA_INTERRUPT_FLAG_NOT_UNDERWATER);
```
2. Calling `UpdatePosition` will eventually call:
```
    // status being part of the result returned from:
    // GetMap()->GetFullTerrainStatusForPosition(_phaseShift, GetPositionX(), GetPositionY(), GetPositionZ(), data);

    if (status & MAP_LIQUID_STATUS_SWIMMING)
        RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_NOT_ABOVEWATER);
    else
        RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_NOT_UNDERWATER);
```

That is, both actions, which are called one after the other, will remove auras with interrupt flag.
</details>

I've played with the code a bit, and while I can clearly see we're validating the movement packet for flags, I don't see where we are validating it for movement speed. It seems when changing the movement speed (e.g. on a gm command), that data is just sent to the client.

Am I missing it? or perhaps we're intentionally "blindly" trusting the client packet? or .. ?


@Shauren Looked at the github blame page and noticed you played around with that area. If you are familiar with it please share your opinion/knowledge about the entire flow.

**Comment by Shauren** [comment]
`GetMap()->GetFullTerrainStatusForPosition` is newer and should be trusted more

As for blindling trusting the client regarding speeds - yes, that is exactly what we do (that is why various anticheat patches are a thing)

**Comment by matanshukry** [comment]
Is there a reason we aren't doing the calculations server side completely using the opcodes, and want to stay on the current path we are - simply trusting the client regarding speed, position, and water state (any or all) ?

**Comment by Ovahlord** [comment]
Because hacks are a thing and giving a client control over features that can fuck a ton of things up is never a good idea.

**Comment by matanshukry** [comment]
I'm closing this issue.
It was opened in an intent to fix the druid travel form, which by now *most* of it works.
The only part left is the nightelf druid form, but there is another issue for it: #26063
