### ISSUE TITLE
DB/Item: Formula Enchant Weapon - Superior Striking Dropping By Too Many Mobs

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26050]
**Description:**

The enchant [Formula: Enchant Weapon - Superior Striking](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=16250) is only supposed to drop by 1 mob only - [Spirestone Warlord](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=9216). This has not changed since Classic and is still true on live.

[Trinity DB](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=16250#dropped-by) dropped by.

[Classic ](https://classic.wowhead.com/item=16250/formula-enchant-weapon-superior-striking)dropped by.

[Live ](https://www.wowhead.com/item=16250/formula-enchant-weapon-superior-striking)dropped by.

**Expected behaviour:**

This enchanter recipe should only drop from  [Spirestone Warlord](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=9216)

**Steps to reproduce the problem:**

1. Head into Lower Black Rock Spire Dungeon
2. Start making your way through - each mob has about a 2% change to drop it 

Note: I've done roughly 2 partial runs and each time ended up with 3 before the half way mark.

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by offl** [comment]
Let's leave it as it is https://www.wowhead.com/item=16250/formula-enchant-weapon-superior-striking#comments
Too weird
>new Listview({template: 'npc', id: 'dropped-by', name: LANG.tab_droppedby, tabs: tabsRelated, parent: 'lkljbjkb574', hiddenCols: ['type'], extraCols: [Listview.extraCols.count, Listview.extraCols.percent], sort:['-percent', '-count', 'name'], computeDataFunc: Listview.funcBox.initLootTable, data: [{"classification":1,"id":9216,"location":[1583],"maxlevel":58,"minlevel":56,"name":"Spirestone Warlord","react":[-1,-1],"type":7,count:1896,outof:25731}]});

**Comment by offl** [comment]
Well https://github.com/TrinityCore/TrinityCore/issues/18738 https://github.com/cmangos/classic-db/commit/bf62b0bc64a74fe41c46be8b0d0633371db3d1d8
