### ISSUE TITLE
DB/Quest: Hot Fiery Death Quest Lootable Gauntlets Item is Empty.

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26059]
**Description:**

The quest [Hot Fiery Death](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5103) found in Lower Blackrock Spire (Blacksmith/Amorsmith? only) has a lootable item next to the corpse which is supposed to contain [Unfired Plate Guantlets](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12812) - they are not present when looting the arm.

<details>

![image](https://user-images.githubusercontent.com/66294837/107313220-34746e00-6ae6-11eb-8419-ea0f4463399b.png)

![image](https://user-images.githubusercontent.com/66294837/107313315-5e2d9500-6ae6-11eb-94e6-73178f417649.png)

</details>

**Expected behaviour:**

The lootable arm is supposed to contain a pair of [Unfired Plate Guantlets](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12812). Both the quest and the gauntlets are required to continue this quest.

**Steps to reproduce the problem:**

Note: Blacksmithing is required.

1. Head to Lower Blackrock Spire and either fight you way to location or take the jumping shortcut  
(First comment in Wowhead quest gives some rough idea on how to find it if you are not familiar with it)

<details>

Jump from up here (or fly or levivate or slow fall etc)

![image](https://user-images.githubusercontent.com/66294837/107313918-ae592700-6ae7-11eb-8f81-0e71d30fb582.png)

Go down this hidden ramp which will take you to the corpse. 

![image](https://user-images.githubusercontent.com/66294837/107314000-d8124e00-6ae7-11eb-890b-8ad9a1580a59.png)

</details>

2. Click corpse to get quest
3. Click Unified Plate Guantlets object to loot the item of the same name - but it's missing.

**Branch(es):**

3.3.5

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by offl** [comment]
But only https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5124 requires that item
And you just was able to interract with that Terminator's arm without that quest

**Comment by offl** [comment]
Ok, I got it. According to comments you can interract with the object without blacksmithing but it will be empty. The quest was also bugged in 3xx and then fixed. Because of that comments are messy and super confusing.

Let's trust this one https://www.wowhead.com/quest=5124/fiery-plate-gauntlets#comments:id=1878879 and make item drop if player has blacksmithing

**Comment by TQPS** [comment]
> Let's trust this one https://www.wowhead.com/quest=5124/fiery-plate-gauntlets#comments:id=1878879 and make item drop if player has blacksmithing

That definitely looks good to me. The quest was active back in 2010 (per post above the one you quoted) but seems later removed by 2013 which makes that ... MOP? So for WOTLK we should be good if Blacksmithing is held.

**Comment by dr-j** [comment]
~~~sql


UPDATE `gameobject_loot_template` SET `QuestRequired`='0' WHERE  `Entry`=13574 AND `Item`=12812;
	

	

	
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=4 AND `SourceGroup`=13574 AND `SourceEntry`=12812;
	
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
	
(4, 13574, 12812, 0, 0, 9, 0, 5103, 0, 0, 0, 0, 0, '', 'Unfired Plate Gauntlets are lootable if quest 5103 taken'), -- or
	
(4, 13574, 12812, 0, 1, 9, 0, 5103, 0, 0, 0, 0, 0, '', 'Unfired Plate Gauntlets are lootable if quest 5124 taken'), -- or
	
(4, 13574, 12812, 0, 2, 28, 0, 5103, 0, 0, 0, 0, 0, '', 'Unfired Plate Gauntlets are lootable if quest 5103 complete in log');
