### ISSUE TITLE
DB/Item: Gemstones For Seal Of Ascension Quests' Drop Rates Are Too High

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26051]
**Description:**

The quest [Seal Of Ascension](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=4742) requires you to obtain:

1 x [Unadorned Seal of Ascension](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12219)
1 x [Gemstone of Spirestone](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12336)
1 x [Gemstone of Smolderthorn](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12335)
1 x [Gemstone of Bloodaxe](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12337)

Quest text states this is meant to be rare:

<details>

![image](https://user-images.githubusercontent.com/66294837/107182153-56131e00-6a30-11eb-8df9-4e74d6e1d899.png)

</details>

Classic drop rates are around ~30% +/-
Live drop rates are lower again ~0.4% +/-

Trinity DB is 100%

```sql
SELECT `entry`, `item`, `chance` FROM creature_loot_template WHERE `item` IN (12335, 12336, 12337);
```

| entry | item | chance | 
| ---: | ---: | ---: | 
| 9196 | 12336 | 100 | 
| 9237 | 12335 | 100 | 
| 9568 | 12337 | 100 | 

**Disclaimer:** We have already modified the drop rates for the Unadorned Seal since Trinity DB had this at 80% which was too high. This can be addressed in a different ticket.

**Expected behaviour:**

Drop rate should be near to WOTLK Blizzlike (to which I do not have but hoping someone does) 

Master branch is also showing 100% and should resemble Live values.

**Steps to reproduce the problem:**

1. Venture into Lower Blackrock Spire (You do not need quest, all items drop without quest - this is normal)
2. Kill any of the bosses which drop them (Highlord Omokk (quickest to test), Overlord Wyrmthalak or War Master Voone)
3. All bosses will drop 100%

**Branch(es):**

Both

TC rev. hash/commit:

TrinityCore rev. f6b22df9bd22 2021-01-13 00:53:43 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by Aokromes** [comment]
https://www.wowhead.com/item=12336/gemstone-of-spirestone#comments:id=158419

**Comment by offl** [comment]
> Classic drop rates are around ~30% +/-
Live drop rates are lower again ~0.4% +/-

Because wowhead calculates chance based on totalKillCount and mostly people kills creatures without quest, chance in wowhead means nothing

**Comment by TQPS** [comment]
Thanks for that.
