### ISSUE TITLE
Core/Spells: A player in traveling druid form crashes the server when teleporting anywhere

### ISSUE THREAD

**Issue by DintyGadget** [TrinityCore/TrinityCore#26054]
**Description:**

If on a character of the druid class, turn on the spell of traveling form, and use the teleport (in any way). Server crashes with "FreezeDetector" error

**Expected behaviour:**

When teleporting in travel form, the server should not crash

**Steps to reproduce the problem:**

1. Create a druid class character.
2. Give the character the maximum level.
3. learn riding skill.
4. Use the travel form spell.
5. Try teleporting somewhere using the .tele command or using the nearest portal.

**Branch(es):**

master

**TC rev. hash/commit:** 

086f337

**Operating system:** 

Windows 10 x64

**Comment by Naddley** [comment]
seems like there is a general problem with the travelform.

https://github.com/TrinityCore/TrinityCore/issues/25939

**Comment by MaxtorCoder** [comment]
Please post the crashlog

**Comment by DintyGadget** [comment]
[unknown_worldserver.exe_[8-2_21-58-47].txt](https://github.com/TrinityCore/TrinityCore/files/5946614/unknown_worldserver.exe_.8-2_21-58-47.txt)


> Please post the crashlog

**Comment by MaxtorCoder** [comment]
Are you using a repack or smth?

**Comment by DintyGadget** [comment]
I use some self-written scripts for spells, but they have nothing to do with the druid class, and must not touch shapeshift like either.

**Comment by MaxtorCoder** [comment]
Well crashlog doesn't display anything useful

**Comment by DintyGadget** [comment]
That is, the problem cannot be reproduced on a clean core compile? Or did you just ask to clarify the problem?

**Comment by Naddley** [comment]
I can reproduce the problem. But for me its not crashing its freeze the Worldserver

**Comment by Shauren** [comment]
If you build on one machine and then copy executables to another one, you must also copy the .pdb files to get useful stack traces (or if its the same machine, you must keep those files)

**Comment by DintyGadget** [comment]
That is, if I copy the .pdb file to the server directory and reproduce the crash, will there be more useful information in the crashlog?

> Если вы создаете на одном компьютере, а затем копируете исполняемые файлы на другой, вы также должны скопировать файлы .pdb, чтобы получить полезные трассировки стека (или, если это тот же компьютер, вы должны сохранить эти файлы)

**Comment by DintyGadget** [comment]
> I can reproduce the problem. But for me its not crashing its freeze the Worldserver

![dcd2YhYLCdg](https://user-images.githubusercontent.com/25077548/107278032-9ad29f80-6a98-11eb-97ab-22c81d71fb91.jpg)
Are you getting the same message?

**Comment by MaxtorCoder** [comment]
> If you build on one machine and then copy executables to another one, you must also copy the .pdb files to get useful stack traces (or if its the same machine, you must keep those files)

Please do this

**Comment by DintyGadget** [comment]
The server stopped giving any errors, the error does not come out in the console either. The server just freezes :1

**Comment by DintyGadget** [comment]
[unknown_worldserver.exe_[9-2_0-8-34].txt](https://github.com/TrinityCore/TrinityCore/files/5946849/unknown_worldserver.exe_.9-2_0-8-34.txt)

**Comment by matanshukry** [comment]
This seems to be the problem: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Unit/Unit.cpp#L4044

Looks like the server is struck in an infinite loop due to that condition.
At that point `m_interruptableAuras` contains:

```
[0]:
  | Name | Value | Type
-- | -- | -- | --
  | _removeMode | AURA_REMOVE_NONE (0) | AuraRemoveMode
  | _slot | 6 '\x6' | unsigned char
  | _flags | 3 | unsigned short
  | _effectsToApply | 1 | unsigned int
  | _needClientUpdate | false | bool
  | _effectMask | 1 | unsigned int

[1]:
  | Name | Value | Type
-- | -- | -- | --
  | _removeMode | AURA_REMOVE_NONE (0) | AuraRemoveMode
  | _slot | 7 '\a' | unsigned char
  | _flags | 11 | unsigned short
  | _effectsToApply | 15 | unsigned int
  | _needClientUpdate | true | bool
  | _effectMask | 15 | unsigned int
```
Also:
```
[0]->_base->m_spellInfo->Id == 783
[1]->_base->m_spellInfo->Id == 33943
```

The iteration on the first item simply goes to the next.
The iteration on the 2nd item always result in `m_removedAurasCount` increased by 2, hence making the condition.

What happens on retail when you teleport (e.g. using a portal) while in travel form? both to a place where flying is allowed and to a place where it isn't?

**Comment by illfated** [comment]
@matanshukry : if you wanted to, you could have used the GitHub Flavored MarkDown (GFM) code to display the content in tables, like this:

`[0]:`

| Name | Value | Type |
| ---- | :---: | ---- |
| _removeMode | AURA_REMOVE_NONE (0) | AuraRemoveMode |
| _slot | 6 '\x6' | unsigned char |
| _flags | 3 | unsigned short |
| _effectsToApply | 1 | unsigned int |
| _needClientUpdate | false | bool |
| _effectMask | 1 | unsigned int |

`[1]:`

| Name | Value | Type |
| ---- | :---: | ---- |
| _removeMode | AURA_REMOVE_NONE (0) | AuraRemoveMode |
| _slot | 7 '\a' | unsigned char |
| _flags | 11 | unsigned short |
| _effectsToApply | 15 | unsigned int |
| _needClientUpdate | true | bool |
| _effectMask | 15 | unsigned int |

(Feel free to "quote" this post (in a new temporary comment of yours) to see how the table code is applied to make it display the tables.)

**Comment by matanshukry** [comment]
@illfated I am aware on how to create tables, I just wanted it to be displayed in markdown and not that big in a table. To be honest I didn't want the table format in that markdown either, it was made automatically by coping from VS.

**Comment by illfated** [comment]
Thank you for the explanation, that is a fair reason too.

**Comment by jackpoz** [comment]
I wonder if I fixed this already in 3.3.5

**Comment by matanshukry** [comment]
@jackpoz I don't know much about the 3.3.5 branch but looking at the code there doesn't seem to be any script about druid's travel form.
Which make sense, since travel form wasn't combined at that time as far as I know.
So I think the problem never existed there to begin with.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/46c7446bd4ef606b1091c1582df50e027fab28b6

This is the commit I had in mind, it's an issue about spell scripts trying to trigger spells on dead units. It seems indeed different than your case.
