### ISSUE TITLE
master = 9.0.2.37474 vs ++ build error

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#26066]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_filesystem-vc142-mt-x64-1_72.lib"	vmap4assembler	C:\BOOS\src\tools\vmap4_assembler\LINK	1	
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_filesystem-vc142-mt-x64-1_72.lib"	mapextractor	C:\BOOS\src\tools\map_extractor\LINK	1	
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_filesystem-vc142-mt-x64-1_72.lib"	vmap4extractor	C:\BOOS\src\tools\vmap4_extractor\LINK	1	
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_filesystem-vc142-mt-x64-1_72.lib"	mmaps_generator	C:\BOOS\src\tools\mmaps_generator\LINK	1	
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_program_options-vc142-mt-x64-1_72.lib"	bnetserver	C:\BOOS\src\server\bnetserver\LINK	1	
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1104	не удается открыть файл "libboost_filesystem-vc142-mt-x64-1_72.lib"	worldserver	C:\BOOS\src\server\worldserver\LINK	1	

Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_filesystem-vc142-mt-x64-1_72.lib" vmap4assembler C: \ BOOS \ src \ tools \ vmap4_assembler \ LINK 1
Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_filesystem-vc142-mt-x64-1_72.lib" mapextractor C: \ BOOS \ src \ tools \ map_extractor \ LINK 1
Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_filesystem-vc142-mt-x64-1_72.lib" vmap4extractor C: \ BOOS \ src \ tools \ vmap4_extractor \ LINK 1
Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_filesystem-vc142-mt-x64-1_72.lib" mmaps_generator C: \ BOOS \ src \ tools \ mmaps_generator \ LINK 1
Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_program_options-vc142-mt-x64-1_72.lib" bnetserver C: \ BOOS \ src \ server \ bnetserver \ LINK 1
Severity Code Description Project File String Suppression status
Error LNK1104 cannot open file "libboost_filesystem-vc142-mt-x64-1_72.lib" worldserver C: \ BOOS \ src \ server \ worldserver \ LINK 1

Всем привет! Ситуация такая пробовал установить Ashamane\Core. Получил ошибку. vs_professional2019 переустановил, библиотеки тоже. MySQL переустановил . Можно как ни будь исправить? Или надо переустанавливать операционную систему.

Hello! This situation was tried to be installed by Ashamane \ Core. Got an error. vs_professional2019 reinstalled, libraries too. MySQL reinstalled. How can I fix it? Or you need to reinstall the operating system.

**Comment by Shauren** [comment]
We are not Ashamane Core, do not report its issues here

**Comment by rem999** [comment]
Сейчас я устанавливаю Trinity/Core. И получаю эту ошибку.
I am currently installing Trinity / Core. And I get this error.

**Comment by MaxtorCoder** [comment]
Read the installation guide on the wiki

**Comment by rem999** [comment]
Я знаю, что если я переустановлю операционную систему эта ошибка пропадёт. Другие способы есть?
I know that if I reinstall the operating system, this error goes away. Are there other ways?

**Comment by acidmanifesto** [comment]
boost is your issue. since 1.72 is not working, try 1.71 or 1.70
