### ISSUE TITLE
Branch 3.3.5a the factions are miss up 

### ISSUE THREAD

**Issue by newrage** [TrinityCore/TrinityCore#26060]
So i been going thow the world and i have find so thing like the factions on mobs like npc id 36725 and npc id 202 there faction is 21 and thmore more npcs with faction  21 and what i been telled is there bost to be 20 and this been in db for a long time and now it thay are now non attackable. so need looking in to the faction on mods 

So some starting Quest will not work of the mobs  being faction 21 and some instances
Like stratholme , scarlet monastery, scholomance, icecrown citadel.
And much more i do not know how no buddy seen this 

Branch(es): 
3.3.5a

**Comment by MaxtorCoder** [comment]
Follow issue template please.

**Comment by jackpoz** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=36725 shows faction 20, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=202 too .

what commit are you using ?

**Comment by offl** [comment]
> https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=36725 shows faction 20, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=202 too .

> and thmore more npcs with faction 21 and what i been telled is there bost to be 20 and this been in db

Those are not real faction ids, it's just a number used by online databases to [tell you the name of faction](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?faction=20). And number 20 contains faction 21, 233 and more. Same with other factions.
Real faction ids used currently in DB are correct in 99% of cases and should never be replaced by factions from wowhead-like databases.

**Comment by Jinnaix** [comment]
Ref:
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130081/FactionTemplate

**Comment by newrage** [comment]
I do not understand your template format
But there so.ing that need to be fix and you closed this

**Comment by offl** [comment]
What exactly is not working?

**Comment by newrage** [comment]
Npc id 36725 and npc id 202 you cant attack them

**Comment by offl** [comment]
I can attack them

**Comment by Aokromes** [comment]
learn .gm off

**Comment by newrage** [comment]
It was a account with no gm on it

**Comment by offl** [comment]
What the query below shows you? Or .server debug
```sql
SELECT * FROM `version`
```

**Comment by illfated** [comment]
I can't remember having any faction issues with those 2 NPC types during any of the last 5 years:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=202/rotting-horror (Level: 23 - 24, found in Duskwood)
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=36725/nerubar-broodkeeper (Level: 80, found in Icecrown Citadel)

Never had issues with those, unless forgetting to turn off GM status. Looks like a pebkac issue to me.

**Comment by Aokromes** [comment]
if a 
"
Like stratholme , scarlet monastery, scholomance, icecrown citadel.
And much more i do not know how no buddy seen this"
was bugged for so long, it was reported years ago, but no, they work properly.

**Comment by newrage** [comment]
I did .server debug and i tell me the things i use to to compile the core and everything

**Comment by jackpoz** [comment]
btw you can test https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=202 on https://tcubuntu.northeurope.cloudapp.azure.com/ and see if you can attack the mobs there.

what commit are you using ?

**Comment by newrage** [comment]
B8efdff0

**Comment by illfated** [comment]
Oh. You mean commit https://github.com/TrinityCore/TrinityCore/commit/b8efdff0fba712a00fd7dfbc7f6c7033364232ee

**Comment by newrage** [comment]
I fell so dum right now. note run wow with out patchs lol
Ty all for trying to help i fix it and i appreciate all the time ppl put in to try to help me ty for trinitycore

**Comment by illfated** [comment]
Sounds like you haven't compiled a clean core, meaning that you are adding patches randomly or cherry-picking without being on level with the current core and TDB. That will very often cause issues we can't help you with, because we have no idea what the actual contents of your DB and core is, compared to clean core & DB.

**Comment by newrage** [comment]
well it a clean core and db.  I do not add patch's to core or db. it just client patch's that all

**Comment by illfated** [comment]
Changes to the game client is also known to cause issues, it is recommended to test without any game client patching as well, because test results can be different.
