### ISSUE TITLE
DB/Quest: The Wandering Isles Starter Quests

### ISSUE THREAD

**Issue by CluelessUKGamer** [TrinityCore/TrinityCore#26069]
**Description:**

When starting in the Wandering isles, there are no starter quests

**Expected behaviour:**

Master Shang Xi character should issue quests to starting players

**Steps to reproduce the problem:**

1. Create a new Pandaren
2. Select The Wandering Isle starting zone
3. No starter quests from Master Shang Xi

**Branch(es):**

Master

**TC rev. hash/commit:** 

Im sorry, this is my first submission, and i do not know what to put here.

'''
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 29406);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 29408);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 29409);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 29410);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 29524);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30027);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30033);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30034);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30035);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30036);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30037);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (53566, 30038);
'''
**Operating system:** 

Windows 10 Pro. 20H2

**Comment by Aokromes** [comment]
duplicate.
