### ISSUE TITLE
group revive

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26070]
**Description:**

how about create one command group revive to resurrect all players on a group?

**Expected behaviour:**

all group revives

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

bf0975f658d5

**Operating system:** 

N/R

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/97e41645d3dac259b53f2c82ed9eca3d71b1d7ee
