### ISSUE TITLE
Love is the Air (Apothecary Hummel Encounter) Perfume/Cologne

### ISSUE THREAD

**Issue by dr-j** [TrinityCore/TrinityCore#26073]
During the Crown Chemical Company encounter in shadowfang keep players have to loot and use Perfume Neutralizer and cologne neutralizer to make them immune to the scents used by the apothecary trio.

Currently players can use both the cologne neutraliser and the perfume neutraliser at the same time and both buffs last for 5 minutes if you read the description on the items it says 'The Caster can only be immune to one "scent" at a time

https://www.wowhead.com/item=49351/perfume-neutralizer
https://www.wowhead.com/item=49352/cologne-neutralizer

~~~sql
DELETE FROM `spell_group` WHERE `id`=68529;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(68529, 68529),
(68529, 68530);

DELETE FROM `spell_group_stack_rules` WHERE `group_id`=68529;
INSERT INTO `spell_group_stack_rules` (`group_id`,`stack_rule`) VALUES
(68529,1);

**Comment by xParad0x** [comment]
Looks good, this can be merged.
