### ISSUE TITLE
Spell: Mind Flay

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26077]
If you use **Mind Flay** on mob and you miss, then the spell will not **visually cooldown** (only visually on icon) and you can`t use the spell again about 1-2 sec.

exactly the same effect can be observed if you cancel the spell (for example go one step forward or backward )

[https://www.wowhead.com/spell=15407/mind-flay](https://www.wowhead.com/spell=15407/mind-flay)

3.3.5
rev. 0dee695

**Comment by CraftedRO** [comment]
6a5fa255fe053796588684e3876f6047cf92a08f First case (while miss) seems no longer valid but second one yea, if you cancel the spell by moving the visual cooldown on spell is not shown even if you can't actually use it again 1-2 seconds.

here's a video from cata ptr with spell intrerupted by moving, notice the cooldown being properly updated on spell icon:

https://github.com/TrinityCore/TrinityCore/assets/24683355/ae4a8d11-8ae6-46c6-91d7-2b2e6c3bb47e

**Comment by CraftedRO** [comment]
Update1: Seems a general issue for chanelling spells (see warlock drain life / soul).
