### ISSUE TITLE
group level

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26071]
**Description:**

how about create one command group level to raise all players on a group?

The reason for such command is allow a gm create a fresh group of the needed lvl to test things without have to level 5, 10, 25, 40, 80 characters one each time or change configuration to create all characters of the desired level.

**Expected behaviour:**

all group levels

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

bf0975f658d5

**Operating system:** 

N/R

**Comment by xParad0x** [comment]
Is this an issue? Shouldn't this be in Pull Requests with an actual code attached to it?

**Comment by MaxtorCoder** [comment]
> 
> 
> Is this an issue? Shouldn't this be in Pull Requests with an actual code attached to it?

It's a good new issue for new contributers.

**Comment by xParad0x** [comment]
> > Is this an issue? Shouldn't this be in Pull Requests with an actual code attached to it?
> 
> It's a good new issue for new contributers.

No actually it is not! Also this looks like a Fun Server Setting which Trinitycore does not address. Why would a Blizzlike Server have a group level ?

**Comment by MaxtorCoder** [comment]
> 
> 
> > > Is this an issue? Shouldn't this be in Pull Requests with an actual code attached to it?
> > 
> > 
> > It's a good new issue for new contributers.
> 
> No actually it is not! Also this looks like a Fun Server Setting which Trinitycore does not address. Why would a Blizzlike Server have a group level ?

It's a freaking command???????? It's for GMs only

**Comment by xParad0x** [comment]
Calm your horses, this is a discussion not a bazar.

Obviously it's a GM COMMAND! duh. but why would a server need a group level>? So GMS can level a whole group correct? that is a fun server stuff. but here difference of opinion is what makes this world great, some people cannot stand it

**Comment by MaxtorCoder** [comment]
> 
> 
> Calm your horses, this is a discussion not a bazar.
> 
> Obviously it's a GM COMMAND! duh. but why would a server need a group level>? So GMS can level a whole group correct? that is a fun server stuff. but here difference of opinion is what makes this world great, some people cannot stand it

Bcuz utility, it really does not matter. And yes, this is a good first issue for new contributers

**Comment by Duratans** [comment]
Actually this does seem more Fun Server then anything. Trinitycore usually doesn't like Funserver stuff and that is the truth

**Comment by Duratans** [comment]
> > Calm your horses, this is a discussion not a bazar.
> > Obviously it's a GM COMMAND! duh. but why would a server need a group level>? So GMS can level a whole group correct? that is a fun server stuff. but here difference of opinion is what makes this world great, some people cannot stand it
> 
> Bcuz utility, it really does not matter. And yes, this is a good first issue for new contributers

No it is not. It is useless, I would never merge this in to my branch

**Comment by MaxtorCoder** [comment]
> 
> 
> > > Calm your horses, this is a discussion not a bazar.
> > > Obviously it's a GM COMMAND! duh. but why would a server need a group level>? So GMS can level a whole group correct? that is a fun server stuff. but here difference of opinion is what makes this world great, some people cannot stand it
> > 
> > 
> > Bcuz utility, it really does not matter. And yes, this is a good first issue for new contributers
> 
> No it is not. It is useless, I would never merge this in to my branch

Well you're not a TC contributer, so I guess it wouldn't matter :P Just like this discussion.

**Comment by Aokromes** [comment]
> Actually this does seem more Fun Server then anything. Trinitycore usually doesn't like Funserver stuff and that is the truth

it's a "gm needs a group to test some thing and instead level 10 characters separately levels all group at once without enable the setting all players starts at level 80"

**Comment by Duratans** [comment]
> > > > Calm your horses, this is a discussion not a bazar.
> > > > Obviously it's a GM COMMAND! duh. but why would a server need a group level>? So GMS can level a whole group correct? that is a fun server stuff. but here difference of opinion is what makes this world great, some people cannot stand it
> > > 
> > > 
> > > Bcuz utility, it really does not matter. And yes, this is a good first issue for new contributers
> > 
> > 
> > No it is not. It is useless, I would never merge this in to my branch
> 
> Well you're not a TC contributer, so I guess it wouldn't matter :P Just like this discussion.

You are obviously way out of line here @MaxtorCoder don't talk about something you do not know, do your research 1st before you say someone is not a contributor. This discussion does matter, this is a community project and everyone is entitled to their opinion.  Just because you say BLUE and I say RED, does not make it BLUE. This is why many people refuse to contribute is because of people like you who think their are entitled somehow. Shame

**Comment by MaxtorCoder** [comment]
> You are obviously way out of line here @MaxtorCoder don't talk about something you do not know, do your research 1st before you say someone is not a contributor. This discussion does matter, this is a community project and everyone is entitled to their opinion. Just because you say BLUE and I say RED, does not make it BLUE. This is why many people refuse to contribute is because of people like you who think their are entitled somehow. Shame

I am not thinking that I am entitled in any way, nor do I think that I am correct. Some people just don't seem to understand Utility methods, which in this case definitely is. I am 100000% sure Blizz has a similar command as well.

**Comment by jackpoz** [comment]
reminder: please use github issue comments to discuss about the issue. for other discussions, use irc, discord, forum, GitHub discussions.
