### ISSUE TITLE
Auctionhouse [Item cannot be selected/targeted]

### ISSUE THREAD

**Issue by Astrono1293** [TrinityCore/TrinityCore#26075]
There is a very unusual issue with Auctionhouse that started happening yesterday, all of a sudden players can no longer select/target certain items in the Auctionhouse list. 80-90% of items are just fine however a small percentage of items, you just cannot select, you click on it and nothing happens.  If you notice on the short video, i am unable to simply click on the item, it just does not select the item upon clicking on it. It is very strange. I am not using any addons or anything custom, I tried on the local server and it works fine. However on live server it does not want to select certain items.

Video: https://gyazo.com/365741c04b8e02125493f018c9e1803b

**Steps to reproduce the problem:**
I am not 100% sure how to reproduce this issue as I been running AH bot / Auctionhouse for almost a year now without any issues what's so ever, everything works just fine.

Branch: 3.3.5
https://github.com/TrinityCore/TrinityCore/commit/0675be4bc3c59142cd47b64f71857e019208e957
 

**Operating system:** 
Window Server 2012

**Comment by TQPS** [comment]
Confirmed. Having similar issues. Sometimes it just gets stuck on one item and you cannot select another.

<details>

Trying to select the second item here but it wont change. 

![image](https://user-images.githubusercontent.com/66294837/107695986-7af3e380-6d05-11eb-9dac-3772c9351679.png)

</details>

**Comment by Astrono1293** [comment]
Yea it is very unusual, what part of AH code prevents item to be even selected? I tried looking everywhere and cannot find anything that resembles it.

**Comment by xParad0x** [comment]
This happens because your ID numbers are very very high, for example ID in your auctionhouse is 3984898348 or something similar. This will make Auction house react very strangely. So the solution to your problem is the following:

`ALTER TABLE auctionhouse AUTO_INCREMENT = 1

SET  @num := 0;

UPDATE auctionhouse SET id = @num := (@num+1);

ALTER TABLE auctionhouse AUTO_INCREMENT =1;`

This will make all IDs start from 1 and up bringing your AH house back to normal, obviously reboot your server.

**Comment by Shauren** [comment]
I disagree with part of your comment there - do not reboot server. Do not run these queries when server is online at all

**Comment by xParad0x** [comment]
Yes, I agree i did not word this correctly. I edited the reply

**Comment by Astrono1293** [comment]
@xParad0x you are a life saver man!!! Thank you so much worked like a charm!!! Auctionhouse back to normal!! Thank you again!

**Comment by xParad0x** [comment]
Your welcome @Astrono1293 , I am still not 100% sure what causes this but I believe it has something to do with how many items you AH bot puts in Auctionhouse and making constant changes to it and doing .ah rebuild will cause your IDs to increment fast. But i am not 100% positive that's the cause. I suggest not to make many changes to your AH Bot on a live server, do all your testing on a Local Machine until you find the perfect settings for your AH Bot.

**Comment by illfated** [comment]
(just to polish the view of your SQL code, according to TC SQL codestyle)
```sql
-- 
SET  @num := 0;

UPDATE `auctionhouse` SET `id` = @num := (@num+1);

ALTER TABLE `auctionhouse` AUTO_INCREMENT = 1;
```
BTW, the last line looks like the query should be longer, something similar to
```sql
ALTER TABLE `auctionhouse` CHANGE `id` `id` int(10) unsigned NOT NULL AUTO_INCREMENT = 1;
```
I could very easily be wrong, though.

**Comment by xParad0x** [comment]
This has nothing to do with a code style, if you understand what the query does, it simply increments values from 1 and up....

**Comment by Aokromes** [comment]
not a bug instead client limitation.

**Comment by xParad0x** [comment]
Actually it is a bug, don't be so quick to close issues, if you look at my previous comment,

AH Bot doesn't correctly increment values in the database, sometimes ID values become 9+ digits long creating unforeseen issues, making IDs digits so high the server cannot process the values.
