### ISSUE TITLE
Some Ymirheim npc-s does ignore crowd controls

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26098]
**Description:**

They still attack even when crowd controled.

**Expected behaviour:**

I guess they shoud not attack when are crowd controled like any other mobs.

**Steps to reproduce the problem:**

Go to Ymirheim-Icecrown (.tele icecrown you will be teleported right behind them) and try to crowd control following npc-s :
1.[Ymirheim Chosen Warrior](https://www.wowhead.com/npc=31258) this one shoud have only melee range but instead it will attack you even on fly mount (40yr range+) .
2.[Ymirheim Defender](https://www.wowhead.com/npc=31746) this one only ignore cc.
3.[Blight Falconer](https://www.wowhead.com/npc=31262) this one does ignore crowd controls even if you kill or cc his pet [Carrion Hunter](https://www.wowhead.com/npc=31263) too you will keep taking damage .

**Branch(es):**

3.3.5 maybe master too

**TC rev. hash/commit:** 2f9e38612f90 

TrinityCore rev. 2f9e38612f90 2021-02-16 00:16:38 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/108038132-29b85c80-7043-11eb-8a20-23198fc03702.mp4

**Comment by dr-j** [comment]
These had triggered flags which was reason for this
~~~sql
UPDATE `smart_scripts` SET `action_param2`='0' WHERE  `entryorguid`=31258 AND `source_type`=0 AND `id` IN(0,1,2,3);
UPDATE `smart_scripts` SET `action_param2`='0' WHERE  `entryorguid`=31746 AND `source_type`=0 AND `id`=0 AND `link`=0;
UPDATE `smart_scripts` SET `action_param2`='0' WHERE  `entryorguid`=31262 AND `source_type`=0 AND `id`=0 AND `link`=0;

**Comment by offl** [comment]
Indeed
