### ISSUE TITLE
Channeling spells allow all other spells to be casted on a back-facing target

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26095]
**Description:**

After you change your character orientation when you channeling any spell , you can cast any other spell with back facing target.

**Expected behaviour:**

You shoudn't be able to cast all spells to a back facing target.

**Steps to reproduce the problem:**

1. Cast any channeling spell , for example Drain Soul .
2. Change your character position with left click + left / right keyboard arrows (you need to stay in place).
3. Now you are able to cast any other spell to back facing target .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** f6e52f6b3df9

TrinityCore rev. f6e52f6b3df9 2021-02-14 14:38:06 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/107940911-a25ee080-6f91-11eb-8e0a-3c3a5eada151.mp4

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/39a436bd658790d39d3cfa64e18f49544475dfe3 ?

**Comment by Jildor** [comment]
@Ovahlord seems player orientation doesn't update when you turn during channeled spell, can be tested with .gps command and see orientation value

**Comment by Ovahlord** [comment]
The current orientation handling sets the serverside facing towards the channel target so you're always facing the dummy while channeling. So while the player turns clientside, the server still keeps the orientation towards the dummy.

**Comment by Jildor** [comment]
Maybe I'm wrong, but isn't it supposed to interrupt when you're turning only if the spell has AURA_INTERRUPT_FLAG_TURNING ?

**Comment by Shauren** [comment]
interrupt flag based, none of player spells interrupt channeling when turning on retail

**Comment by Ovahlord** [comment]
Well, Drain Soul has the SPELL_ATTR1_CHANNEL_TRACK_TARGET  attribute so the internals are actually doing exactly what they should do: track the target. So why on earth does the spell have that attribute and the player can still turn arround like that.

**Comment by Jildor** [comment]
Related PR: https://github.com/TrinityCore/TrinityCore/pull/25440
This I think was discussed in part here: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/d606fa4688c01652948be36097014c029b43f1a4#commitcomment-42535304

Maybe we should update the orientation in every periodictick just in case the caster is not a player?
