### ISSUE TITLE
[Quest]:Journey to the Sunwell

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26108]
**Description:**

#11016 You are only able to see [Halduron Brightwing](https://www.wowhead.com/npc=37527/halduron-brightwing) npc with .gm on and then you can turn the quest .

**Expected behaviour:**

You shoud be able to see the [Halduron Brightwing](https://www.wowhead.com/npc=37527/halduron-brightwing) npc as a player too and turn in the quest [Journey to the Sunwel](https://www.wowhead.com/quest=24522).

**Steps to reproduce the problem:**

1. .quest add 24522
2. .tele queldanas
3. go at the entrance to the Sunwell Plateau

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 2f9e386

TrinityCore rev. 2f9e386 2021-02-16 00:16:38 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/108194518-69547680-711f-11eb-98c2-ce1be6b03d9d.mp4

**Comment by Aokromes** [comment]
duplicate.

**Comment by CraftedRO** [comment]
Well sorry about this but in that issue is nothing mentioned about this quest .

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/4866#issuecomment-743744786

**Comment by CraftedRO** [comment]
ah ok im blind :D
