### ISSUE TITLE
DB/Object: Several Arthas' Tears Spawning Mid-air

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26114]
**Description:**

At least 2 [Arthas' Tears](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=142141) herbalism gameobjects found floating in mid-air. Unable to obtain.

```sql
SELECT `guid`, `position_x`, `position_y`, `position_z` FROM `gameobject` WHERE `guid` IN (15968, 86079);
```
gameobject
---
| guid | position_x | position_y | position_z | 
| ---: | ---: | ---: | ---: | 
| 15968 | 1262.32 | -1490 | 67.997 | 
| 86079 | 1434.88 | -1542.22 | 55.5123 | 

<details>

 15968 

![image](https://user-images.githubusercontent.com/66294837/108493315-47631b80-72fa-11eb-9548-212efbabe916.png)

86079

![image](https://user-images.githubusercontent.com/66294837/108493726-c0fb0980-72fa-11eb-896e-b83ca6c0c2a5.png)

</details>

**Expected behaviour:**

Objects should be closer to the ground.

I do not have correct `position_z` values.

**Steps to reproduce the problem:**

1. Go to Western Plaguelands - specifically Ruins Of Andorthal 
2. Objects are located at located at `44.3, 73.4` (15968 ) and `45.6, 67.4` (86079)

<details>

![image](https://user-images.githubusercontent.com/66294837/108494247-66ae7880-72fb-11eb-8b72-812a96561d80.png)

</details>

Branch(es):

3.3.5

TC rev. hash/commit:

TrinityCore rev. 0675be4bc3c5 2021-02-09 20:23:41 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

Operating system:

Windows 7 Ultimate x64 SP1

**Comment by illfated** [comment]
Confirmed on TrinityCore rev. c3165dce316d 2021-02-19 18:13:10 +0100 (3.3.5 branch) (Win64, Release, Static)

```sql
15968 (Entry: 142141) - [Arthas' Tears X:1262.319946 Y:-1490.000000 Z:67.997002 MapId:0]  
Found nearby gameobjects (distance 10.000000): 1

You are outdoors.
Map: 0 (Eastern Kingdoms) Zone: 28 (Western Plaguelands) Area: 193 (Ruins of Andorhal) Phase: 1
X: 1262.263672 Y: -1490.035889 Z: 59.528767 Orientation: 2.594311
grid[34,29]cell[2,1] InstanceID: 0
 ZoneX: 44.341919 ZoneY: 73.409409
GroundZ: 59.529243 FloorZ: 59.529243 MinHeight: -500.000000 Have height data (Map: 1 VMap: 1 MMap: 1)

[Zogzog]'s Fly Mode on (moving up close to the herb object location)

You are outdoors.
Map: 0 (Eastern Kingdoms) Zone: 28 (Western Plaguelands) Area: 193 (Ruins of Andorhal) Phase: 1
X: 1262.263672 Y: -1490.035889 Z: 68.283669 Orientation: 2.621800
grid[34,29]cell[2,1] InstanceID: 0
 ZoneX: 44.341919 ZoneY: 73.409409
GroundZ: 59.529243 FloorZ: 59.529243 MinHeight: -500.000000 Have height data (Map: 1 VMap: 1 MMap: 1)

15968 (Entry: 142141) - [Arthas' Tears X:1262.319946 Y:-1490.000000 Z:67.997002 MapId:0]  
Found nearby gameobjects (distance 10.000000): 1

[Zogzog]'s Fly Mode off (dropping back down to the ground)

You are outdoors.
Map: 0 (Eastern Kingdoms) Zone: 28 (Western Plaguelands) Area: 193 (Ruins of Andorhal) Phase: 1
X: 1262.263672 Y: -1490.035889 Z: 59.528904 Orientation: 2.621800
grid[34,29]cell[2,1] InstanceID: 0
 ZoneX: 44.341919 ZoneY: 73.409409
GroundZ: 59.529243 FloorZ: 59.529243 MinHeight: -500.000000 Have height data (Map: 1 VMap: 1 MMap: 1)
```

**Comment by offl** [comment]
86079 is sniffed and is spawned on the ground
you probably mean nearby 16022

15968 is spawned nearby 61988 which is too sniffed

I'll remove both of them

**Comment by illfated** [comment]
OK, very well, fair enough. New observation: 2 days ago, I noticed a flying Adder's Tongue in Sholazar Basin, above the hollow Queen Hive trunk. I will get the details from tcubuntu, just to be on the safe side. BBL.

**Comment by illfated** [comment]
```sql
[18:26:20] Discovered Sapphire Hive: 1530 experience gained
```

`.gobject near`
```sql
[18:28:03] 56919 (Entry: 191019) - [Adder's Tongue X:4977.379883 Y:4342.970215 Z:-34.414700 MapId:571]  
[18:28:03] Found nearby gameobjects (distance 10.000000): 1
```
`.gps`
```sql
[18:28:47] You are outdoors.
[18:28:47] Map: 571 (Northrend) Zone: 3711 (Sholazar Basin) Area: 4304 (Sapphire Hive) Phase: 1
[18:28:47] X: 4977.340332 Y: 4342.604492 Z: -39.786644 Orientation: 5.262898
[18:28:47] grid[41,40]cell[2,1] InstanceID: 0
[18:28:47]  ZoneX: 59.375885 ZoneY: 79.546379
[18:28:47] GroundZ: -100000.000000 FloorZ: -39.787357 MinHeight: -1000.000000 Have height data (Map: 1 VMap: 1 MMap: 1)
```
Adder's Tongue (56919 / 191019) is floating approximately 2 character heights above the hollow tree trunk at this spot.

**Comment by offl** [comment]
I have nothing with that object

**Comment by illfated** [comment]
Maybe an incorrect spawn?

**Comment by offl** [comment]
Maybe, I don't have all objects to confirm that
