### ISSUE TITLE
Core/Spells: If warlock Death Coil spell does crit , healing received will be wrong

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26115]
**Description:**

Core/Spells: If warlock [Death Coil](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=47860) spell does crit , healing received will be wrong

**Expected behaviour:**

The caster gains 300% of the damage caused in health.
(In my video I did 1543 damage and I received 3087 heal instead 4629 healing .

**Steps to reproduce the problem:**

1. For a quick reproduction of the bug you can .additem 18970 [( Ring of Critical Testing 2)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=18970) a ring that gives you 50% crit .
2. Then cast [Death Coil](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=47860) on a player / npc .
3. Check damage dealt / healing received .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** c3165dce316d 

TrinityCore rev. c3165dce316d 2021-02-19 18:13:10 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/108570562-e7c73900-7316-11eb-8349-f686b6779d0d.mp4

**Comment by Jildor** [comment]
Death Coil damage should be able to be critical?

**Comment by CraftedRO** [comment]
Hmm , good question ! well maybe this is the problem that it does crit and it shoudn't :D
I'm not 100% sure but some old sources does say it shoudn't 
> [It is a binary spell, and as such it can only hit or miss. Neither critical hits nor partial resists are possible.](https://wow.gamepedia.com/Death_Coil_(warlock_ability))

**Comment by Jildor** [comment]
also I don't see any crit:
http://www.worldoflogs.com/reports/2deyfw3tuusjsb8c/xe/?x=spell+%3D+%22Death+Coil%22+AND+%28sourcename%3D%22Akaunique%22+OR+sourcename%3D%22Plazma%22%29

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6e1b9d775cc17387b30c888807eca24949141ca3
