### ISSUE TITLE
Hunter start Pet (removed in SL) SQL Fixx

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26128]
**Description:**

Hunter start with a Pet at lvl 1

-> maybe we just need to delete the Spells for gettin Pets in 'playercreateinfo_cast_spell' need someone that confirm that to prepare a SQL.

**Expected behaviour:**

not allied Race Hunter dont start with a Pet at lvl 1 anymore. They learn "Tame Beast" at lvl 5 and can tame the first Pet.

**Steps to reproduce the problem:**

1. create a Hunter
2. enter world and see the pet next to you

**Branch(es):**

master

**TC rev. hash/commit:** 

01a3be276f4076762290e985d10d5c4ab1176ce0

**Operating system:** 

Win10

**Comment by Naddley** [comment]
```sql
-- Delete Hunter Pet Spells
-- Human, Orc, Dwarf, Night Elf, Undead, Tauren, Troll, Goblin, Blood Elf, Draenei, Worgen
DELETE FROM `playercreateinfo_cast_spell` WHERE `raceMask` IN (1, 2, 4, 8, 16, 32, 128, 256, 512, 1024, 2097152) AND `classMask` = 4;
```

**Comment by Shauren** [comment]
Thanks for report, pushed a slightly different fix, deleting by spell id instead (you also missed gnomes)
