### ISSUE TITLE
Some hiccups while turning

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26175]
Usually when you turn the player (hold the right mouse button) he turns smoothly in that direction. But sometimes there are hiccups like this.

I do not know how this can be reproduced, it happens by accident 

https://user-images.githubusercontent.com/77268574/109386747-eba61d00-790d-11eb-9ced-6651d58c45f8.mp4

3.3.5
rev. 0dee695

**Comment by Shauren** [comment]
client side only.

**Comment by gygyti** [comment]
got it
