### ISSUE TITLE
DB/Creature: Muddled Prophet of Sseratus creature_text

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#26185]
**Description:**

TrinityCore rev. 97e41645d3da 2021-02-27 14:04:07 +0100 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon) ready...

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28068/prophet-of-sseratus
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28151/muddled-prophet-of-sseratus#objective-of
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12516/too-much-of-a-good-thing
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=38332/modified-mojo

After doing the quest ["Too Much of a Good Thing" (12516)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12516/too-much-of-a-good-thing) yesterday, I noticed the following messages in the worldserver console:
```
CreatureTextMgr: Could not find Text for Creature Muddled Prophet of Sseratus (Entry 28151, spawnId 111325) in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature Muddled Prophet of Sseratus (Entry 28151, spawnId 111325) in 'creature_text' table. Ignoring.
```
I know it is not a big deal, but the message(s) reminded me of the fact that the [Muddled Prophet of Sseratus (28151)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28151/muddled-prophet-of-sseratus#objective-of) never says (yells) his Aggro or Death text (as I have seen) on TrinityCore 3.3.5.

**Expected behaviour:**

Muddled Prophet of Sseratus (28151) should yell the following lines, On Aggro, and On Death. respectively:
- **Muddled Prophet of Sseratus yells: Mmm, more mojo.** (`broadcast_text`.`ID` 27531)
- **Muddled Prophet of Sseratus yells: NOOOOOOOOooooooo.........!** (`broadcast_text`.`ID` 27532)

**Steps to reproduce the problem:**

1. Use a GM or admin character, level 74—80; quest requirement 74, NPC level 76 (elite & non-elite)
2. `.quest add 12516`
3. `.gm on`
4. `.go creature id 28068`
5. Move out of aggro range (either southward down the stairs towards the Argent Stand or north up the stairs to the dead NPC Sseratus)
6. `.gm off`
7. Move close enough to throw (use) the quest item "Modified Mojo" (38332)
8. Notice that Muddled Prophet of Sseratus (shrunken down from Elite) does not say (yell) line 0 "Mmm, more mojo.", neither does Prophet of Sseratus (elite) say it.
9. Move even closer, to aggro Muddled Prophet of Sseratus and notice that he still does not say/yell anything.
10. Kill the NPC and notice that line 1 ("NOOOOOOOOooooooo.........!") never gets said either.

**Solution draft/attempt (does not seem to work yet, would have made a draft ticket if possible):**

```sql
-- Muddled Prophet of Sseratus
SET @Prophet := 28068;
SET @MPOS := 28151;

DELETE FROM `creature_text` WHERE `CreatureID` IN (@Prophet, @MPOS) AND `GroupID` IN (0, 1) AND `BroadcastTextId` IN (27531, 27532);
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(@MPOS, 0, 0, 'Mmm, more mojo.',            14, 0, 100, 0, 0, 0, 27531, 0, 'Muddled Prophet of Sseratus'),
(@MPOS, 1, 0, 'NOOOOOOOOooooooo.........!', 14, 0, 100, 0, 0, 0, 27532, 0, 'Muddled Prophet of Sseratus');

-- Muddled Prophet of Sseratus SAI
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry`= @MPOS;

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@Prophet, @MPOS) AND `source_type`= 0 AND `id` IN (0, 1);
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@MPOS, 0, 0, 0, 4, 0, 100, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Muddled Prophet of Sseratus - On Aggro - Say Line 0'),
(@MPOS, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Muddled Prophet of Sseratus - On Just Died - Say Line 1');

-- Prophet of Sseratus SAI row ID reset
UPDATE `smart_scripts` SET `id`= 0 WHERE `id`= 2 AND `entryorguid`= @Prophet AND `source_type`= 0;
UPDATE `smart_scripts` SET `id`= 1 WHERE `id`= 3 AND `entryorguid`= @Prophet AND `source_type`= 0;
UPDATE `smart_scripts` SET `id`= 2 WHERE `id`= 4 AND `entryorguid`= @Prophet AND `source_type`= 0;
UPDATE `smart_scripts` SET `id`= 3 WHERE `id`= 5 AND `entryorguid`= @Prophet AND `source_type`= 0;
```
This appears to be unsuccessful on my local server, but maybe someone else could test if this works on a different client? Maybe I have missed something obvious?

**Branch(es):**

both

**TC rev. hash/commit:** 
TrinityCore rev. 97e41645d3da
```
TC> server debug
TrinityCore rev. 97e41645d3da 2021-02-27 14:04:07 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.19.2
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21021
TC> _
```

**Operating system:** 

Windows 10 x64 Version 20H2 (OS Build 19042.844)

**Comment by illfated** [comment]
By the way, I forgot to include some chat log from my game client while actually testing my attempted solution, but here it is. I have spaced the different log entries for readability, they are not spaced in the actual chat window.

The log starts with me turning off the PvP flag, followed by a regular random yell from the elite NPC, before I entered item use range and aggro range.

After that, the log shows one entry from a skill-up in player character Defense skill, before the final kill.

Finally, it ends with me grabbing the `.npc info` from creature entry 28151.
```
You will be unflagged for PvP combat after five minutes of non-PvP action in friendly territory.

16:16:07 Prophet of Sseratus yells: I see you, insect! Come closer.

Your skill in Defense has increased to 369.

Muddled Prophet of Sseratus dies, you gain 1920 experience. (+960 exp Rested bonus)
CARBONITE Quest Complete 'Too Much of a Good Thing'

You receive loot: [Frostweave Cloth]x3.
You receive loot: [Drakkari Offerings].

NPC currently selected by player:
Name: Muddled Prophet of Sseratus
SpawnID: 111325, current GUID low: 167.
Entry: 28151.
Faction: 2069.
NPC Flags: 0.
DisplayID: 15102 (Native: 15102).
Compatibility Mode: 0
Level: 76.
EquipmentId: 0 (Original: 0).
Health (base): 11001. (max): 11001. (current): 0.
Movement type: Ground: Run, Swim: true, Flight: None, Chase: Run, Random: Walk, InteractionPauseTimer: 180000
Unit Flags: 32768
* UNIT_FLAG_SWIMMING (0x8000)
Unit Flags 2: 2048.
Dynamic Flags: 4.
Faction Template: 2069.
SpawnTime: Full:5m Remaining:2m54s
Loot: 28151 Pickpocket: 0 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 8520
Position: 6237.387695 -2621.288330 303.983337.
AIName: SmartAI ScriptName: 
React state: AGGRESSIVE
Active AI: class SmartAI
Flags Extra: 0
MechanicImmuneMask: 0
```

**Comment by offl** [comment]
```cpp
bool Creature::UpdateEntry(uint32 entry, CreatureData const* data /*= nullptr*/, bool updateLevel /* = true */)
{
    //We must update last scriptId or it looks like we reloaded a script, breaking some things such as gossip temporarily
    LastUsedScriptID = GetScriptId();

    return true;
}

**Comment by illfated** [comment]
Oh. I see. Thank you. I was unaware of that core issue, but now I know. Thank you.

**Comment by offl** [comment]
I'll try later to figure out what approach should be used here and in another cases
That thing is more complex

**Comment by illfated** [comment]
By the way, looking at the code snippet, it reminds me of the following worldserver console message from picking up the quest "Where in the World is Hemet Nesingwary?"
```
SCRIPT_COMMAND_TALK ('spell_scripts' script id: 51071) neither source nor target are creatures (source: TypeId: 4, Entry: 0, GUID: 3; target: TypeId: 4, Entry: 0, GUID: 3), skipping.
```
Is this message caused by the same core isssue?

**Comment by offl** [comment]
No idea

**Comment by illfated** [comment]
Fair enough, ccrs is probably right (https://github.com/TrinityCore/TrinityCore/commit/45362ef413b80b852342fcbd85488bb4acd87f18#commitcomment-47762769). The script (https://github.com/TrinityCore/TrinityCore/commit/45362ef413b80b852342fcbd85488bb4acd87f18) for that quest probably needs a new ticket due to incorrect script targets.
