### ISSUE TITLE
gameobject_template type 3 (chest) resetting loot upon every attempt to loot

### ISSUE THREAD

**Issue by Vortalex** [TrinityCore/TrinityCore#26191]
**Description:**

gameobject_template type 3 (chest) is resetting loot every time the chest is reopened

**Expected behaviour:**

Loot is supposed to stay in the chest unless data values are put in to allow it to reset after a given number of open attempts or time period

**Steps to reproduce the problem:**

1.) Take any chest gameobject (gameobject entry 2843 Battered Chest for example) and spawn it
2.) Open it but do not loot
3.) Keep opening it several times
4.) Notice the loot changes every time

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

c4f0f091667f
TDB 335.20061

**Operating system:** 

Win10

**Comment by Faq** [comment]
Update your core, it is old revision.

**Comment by Vortalex** [comment]
It is an older revision, by only a few months. But if you search through issues, this problem has not been brought up. My core is heavily modified, so I'm not trying to update it, I'm trying to find what's causing the issue so that I can implement the correction myself.

**Comment by illfated** [comment]
[20:36:08] TrinityCore rev. 97e41645d3da 2021-02-27 14:04:07 +0100 (3.3.5 branch) (Win64, Release, Static)
```sql
[20:36:08] Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
[20:36:08] Using Boost version: 1.74.0
[20:36:08] Using MySQL version: 50732
[20:36:08] Using CMake version: 3.19.2
[20:36:08] Compiled on: Windows 10.0.19042
[20:36:08] Automatic database updates are enabled for the following databases: Auth, Characters, World
[20:36:08] Worldserver listening connections on port 8085
[20:36:08] Realmlist (Realm Id: 1) configured in port 8085
[20:36:08] VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
[20:36:08] MMAPs status: Enabled
[20:36:10] maps directory located in ./maps. Total size: 251987687 bytes
[20:36:13] vmaps directory located in ./vmaps. Total size: 658130721 bytes
[20:36:14] mmaps directory located in ./mmaps. Total size: 1962379500 bytes
[20:36:14] Using enUS DBC Locale as default. All available DBC locales: enUS 
[20:36:14] Using World DB: TDB 335.21021
```
Could not replicate your issue, even if my game client is enGB (which some say is one of the most bugged WoW clients on the market). Try reproducing your issue on a clean core, because that is what TrinityCore expects for a reported issue to be valid and caused by a source code issue.

**Comment by Vortalex** [comment]
> even if my game client is enGB (which some say is one of the most bugged WoW clients on the market).

Really? That explains why all the boats are backwards! I'll have to get a new client

**Comment by Vortalex** [comment]
I just built a fresh core, TrinityCore rev. 5b000d2fde5e 2021-03-03 01:50:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)

Tested it. Same problem. I made a gif to illustrate the issue:
https://imgur.com/a/W6VaIAS
<blockquote class="imgur-embed-pub" lang="en" data-id="a/W6VaIAS" data-context="false" ><a href="//imgur.com/a/W6VaIAS"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by illfated** [comment]
> That explains why all the boats are backwards! I'll have to get a new client

Not really. The boats issue is a game client issue whichever one you use, because the boats in Stormwind got changed right before Cataclysm and they are (from what I remember) not gameobjects, so we can't easily correct them without editing the game client.

**Comment by illfated** [comment]
> I just built a fresh core, TrinityCore rev. 5b000d2fde5e 2021-03-03 01:50:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)
> 
> Tested it. Same problem. I made a gif to illustrate the issue

It should work correctly when swapping to a clean core & DB, but your prevailing issue could easily be a game client cache issue, where you still see some cached results from the previous servers.

**Comment by Vortalex** [comment]
> Not really. The boats issue is a game client issue whichever one you use, because the boats in Stormwind got changed right before Cataclysm and they are (from what I remember) not gameobjects, so we can't easily correct them without editing the game client.

Meant the small row boats. All row boats on my client are facing the opposite direction. It's a client issue I've known about for years but now that you mentioned enGB as being a buggy client, I understand why.

> It should work correctly when swapping to a clean core & DB, but your prevailing issue could easily be a game client cache issue, where you still see some cached results from the previous servers.

It's not a cache issue. The items are actually there and they can be looted, and even if one item is looted, the next time the chest is opened it has a fresh new set of loot that can also be looted.

The core and DB are both fresh, pulled them this morning straight from here.

**Comment by illfated** [comment]
Well, I can only hope someone else can reproduce your issue. Since I can't, it is counterintuitive for me to ask for this ticket to be reopened.

**Comment by Vortalex** [comment]
I've done ANOTHER fresh recompile, and produced the same problem. What else could it be? I don't see any other way it could be happening.

**Comment by illfated** [comment]
I have no doubt that you are able to reproduce it. We just need to wait for TrinityCore developers to take an interest in this issue, which usually happens if someone else can reproduce it too. Otherwise, it will be a wild goose chase for them, unless someone are able to find which part of the code could be responsible.
