### ISSUE TITLE
Core/Entity Conversation can't be played twice

### ISSUE THREAD

**Issue by Traesh** [TrinityCore/TrinityCore#26204]
**Description:**

Conversation can't be played twice correctly.

On the first time the conversation animation play correctly and everything is fine.
If you try to do it again, the UI will pop and depop in a fraction of second.

I tested to fill the missing fields (Field_18 of actors) but nothing more. You can see a comparaison of retail sniffing (left) vs local (right) : https://i.imgur.com/Fdu4wW7.png

Only difference seem to be the UpdateType but i tested forcing it to CreateObject1 and still the same

**Expected behaviour:**

We should be able to play a conversation multiple times without issue.

**Steps to reproduce the problem:**

1. Apply the linked SQL : https://gist.github.com/Traesh/0752d33ce7337b60bb787dd15b7e5df9
2. Ingame, start a conversation using `.debug conversation 15101` and check that everything is fine
3. Do it again, and see the UI disappearing quickly.

**Branch(es):**

master

**TC rev. hash/commit:** 

898f97781c7f3cc5d40b4f9947571058b7ff7a75

**Operating system:** 

Windows 10

**Comment by Shauren** [comment]
I applied this and it worked just fine, tried both waiting until first one is over and spamming the command twice (in which case second conversation started playing after first was canceled/finished)

**Comment by Shauren** [comment]
Also ref actor field_18: are you sure that its the template id?

**Comment by Traesh** [comment]
That's very strange then, maybe an issue with my client ?

Here's a video (on clean TC with clean TDB) to proof i'm not mad :p https://www.dropbox.com/s/1sms0xdh58ym5td/do66h8Yt7T.mp4?dl=0

This shit happen even with worldserver closed, with client cache cleared. It's a really weird issue.

And no, i'm not sure field_18 is the actor_id, it was just an intuition i'd need more data to check that

**Comment by Shauren** [comment]
You could compare sniffs of the same conversation from current retail patch and older than V8_0_1_27101 (those also had some sort of extra value in actor)

**Comment by Shauren** [comment]
I did find sniffs to compare values, they are indeed the same field
