### ISSUE TITLE
Travelform (ground) useable

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26207]
**Description:**

Travelform is bind to riding skill and only useable with learned Riding skill.

**Expected behaviour:**

If you reach lvl 10 and get the Travelform spell, you can use the Travelform without learning the Riding skill.
The Travelform should have 40% and if you reach lvl 20 you get 100% speed.
For both you dont need to learn a Riding skill, the Druid only need Riding skill for Flying and for using Mounts.

**Steps to reproduce the problem:**

1. create a Druid
2. reach lvl 10
3. try to use Travelform

**Branch(es):**

master

**TC rev. hash/commit:** 

898f97781c7f3cc5d40b4f9947571058b7ff7a75

**Operating system:** 

Win10

**Comment by mdX7** [comment]
> The Travelform should have 60% like a slow Mount and if you reach lvl 20 you get 100% speed.
this is not correct. The travel form you get without learning any riding skills is only 30% (tested that like 2 weeks ago on retail), if you learn the first riding skill its still 30% (whyever, possibly bug from blizz side) but as soon as you learn "epic riding" (lvl 20) your travelform also becomes 100% mount

**Comment by Naddley** [comment]
Ok, forgott about that I can lookup the speed in Characterinfo, on Retail it looks like 60% for me but yes 30% is right. My mistake^^

**Comment by mdX7** [comment]
> 
> 
> Ok, forgott about that I can lookup the speed in Characterinfo, on Retail it looks like 60% for me but yes 30% is right. My mistake^^
> 
> Edit: I know that the travelform gets faster if you reach lvl 20 and re-use it, but now Im not totaly sure if thats 100%...^^

Travelform Rank 2 is learned on lvl 20 which increases speed by 60%, that means 40% + 60% = 100% without learning riding
