### ISSUE TITLE
(DB/creature_addon): Double hit on some NPCs at Naxxramas

### ISSUE THREAD

**Issue by Si1ker** [TrinityCore/TrinityCore#26218]
This needs confirmation but same values causing the issue where found in TC DB.
-> if it does, take the fix.
-> If it does not, close the issue.

**Description:**
Probably TC has the same behavior on these: Anub'Rehkan, Gluth and naxx trash as described in the report below
Issue: https://github.com/azerothcore/azerothcore-wotlk/issues/4751

**Expected behaviour:**
Bosses/npcs must attack once per time
Fix: https://github.com/azerothcore/azerothcore-wotlk/pull/4773

**Steps to reproduce the problem:**

1. Go Naxx
2. Get in combat with Anub'Rehkan and Gluth
3. Check if at any time they double hit

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 84ad438

TrinityCore rev. 84ad438 2021-03-05 22:22:56 +0100 (3.3.5 branch) (Win64, Release, Static)

**Operating system:**

Windows 10 x64

**Comment by offl** [comment]
Those auras were added from sniffs and are part of trash \ bosses mechanics

**Comment by Si1ker** [comment]
@offl you right, my mistake, thanks!
