### ISSUE TITLE
allow to filter list auras

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26212]
**Description:**

title

**Expected behaviour:**

it allows you to filter auras by name to find better one aura

**Steps to reproduce the problem:**

1. target someone
2. list auras
3. find to much auras to search the one you want

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

06c1f728baca

**Operating system:** 

debian 10 x64

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9aff21b3d520cdd580f065f2965442af1bebc81c
