### ISSUE TITLE
Spell/Druid Bristling Fur 

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26220]
**Description:**

Bristling Fur dont generate Rage if you get hit

**Expected behaviour:**

If you use Bristling Fur you should generate Rage while you get damage taken.

**Steps to reproduce the problem:**

1. create a druid 
2. skill lvl 15 talent Bristling Fur
3. get hitted

**Branch(es):**

master

**TC rev. hash/commit:** 

0aa3a0b0b9430d2b92e6a69e6c3bc205bfebfa57

**Operating system:** 

Win10

**Comment by matanshukry** [comment]
Tested now on latest, this does work.

Notes though:

- If you're rage is at 0 and you haven't generated a bit for a few seconds, it will degenerate, so any small hits that will generate small amounts of rage (e.g. 2) won't be visible.

To test it accurately:
1. Get your rage to at least 50 or so.
2. Activate bristling fur
3. Get attacked

**Comment by Aokromes** [comment]
so, not a bug?

**Comment by matanshukry** [comment]
nope, but let's give a bit of time for Naddley to re-test.

@Naddley ?

**Comment by Naddley** [comment]
re-test it:

I dont generate rage.
I get up myself to 72 rage and just do nothing.
My second char hits me in duel with Spells between 600 up to 4k Hits.
My Bear still is on 72 Rage.

**Comment by matanshukry** [comment]
@Naddley https://streamable.com/1ts59b

**Comment by Naddley** [comment]
mmmh weird.
I will recompile and test it again.

I close this for now.

**Comment by matanshukry** [comment]
@Naddley I re-tested the amount though, and that is incorrect.
That is, while the spell does generate rage, it generated only 1/10 of what it should.

You can reopen this issue if you change the description of it, or open a new one.
Or, just wait xd It's going to be in the pr either way.

**Comment by Naddley** [comment]
haha allright^^ I think there is no need for a new issue ticket if you do it anyway xD
