### ISSUE TITLE
Spell/Priest Power Word: Shield shoud only be reduced by 10% battlegrounds arenas, and Wintergrasp

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26232]
**Description:**

> [WotLK Hotfix (2010-02-05): "The amount of damage being absorbed by  [Sacred Shield] and Power Word: Shield is being reduced by 10% correctly in only battlegrounds, Arenas, and Wintergrasp."](https://wow.gamepedia.com/Power_Word:_Shield)

**Expected behaviour:**

The amount of damage being absorbed by  [Sacred Shield] and Power Word: Shield shoud being reduced by 10% in only battlegrounds, Arenas, and Wintergrasp .

Currently it is reduced by 20% or something like that , let's calculate :

In my first screenshoot I did myself 581 (non-crit) heal from the gliph outside of bg , arena or wintergrasp witch means 581 x 5=2905 total damage absorbed by the POS.
In my second screenshoot I did 471 (non-crit) in battleground witch means 471 x 5=2355 total damage absorbed by the POS.
10% from 2905 is 290.5 so 2905-290.5=2.614,5 absorb I shoud receive in battleground not 2355.

Maybe is same for sacred shield but I didn't tested yet.

**Steps to reproduce the problem:**

1. Create a 80 naked disci Priest then learn [Glyph of Power Word: Shield](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=42408) it will help you to calculate the amount of damage being absorbed since the gliph heals the target for 20% of the absorption amount. so you only need to multiply the heal by 5 to gain total amount absorbed by the shield.
2. Check the amount of heal gain from the non-crit Power Word: Shield outside of bg-s arenas or wintergrasp .
3.  Write .debug bg then enter in a battleground to check again the amount of heal received by pos gliph and compare .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 62594c62f6bb

TrinityCore rev. 62594c62f6bb 2021-03-12 18:06:10 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

![1](https://user-images.githubusercontent.com/24683355/110976826-12327200-836a-11eb-8820-c9c9e7b0d79a.jpg)
![2](https://user-images.githubusercontent.com/24683355/110976928-30986d80-836a-11eb-8911-2f4a8957b8b3.jpg)

**Comment by CraftedRO** [comment]
wasn't dumpening introduced in mop :D ?

**Comment by Jildor** [comment]
nope

**Comment by CraftedRO** [comment]
Weird , the only thing I get about dampening is this https://www.wowhead.com/spell=110310/dampening and its say something about Added in patch 4.3.0.15005 dafuq :)

**Comment by Jildor** [comment]
nope, you're weird, you can check:
ID - 74410 Arena - Dampening
ID - 74411 Battleground - Dampening
;)

**Comment by Aokromes** [comment]
so, not a bug?

**Comment by CraftedRO** [comment]
ah ok then I guess is fine :)
