### ISSUE TITLE
account_used_ips 

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26244]
**Description:**

how about create one table account_used_ips or something like that to have easy access with a command to the  list of of ips used on one account, no limit of added rows

|account_id|character_guid|ip|country|connection_time|disconect_time|
|-|-|-|-|-|-|
|1|1|127.0.0.1|localhost|1/1/2021 20:00|1/1/2021 20:30|
|1|2|127.0.0.1|localhost|1/1/2021 20:31|1/1/2021 20:50|

the command can be account info id < limit of rows >

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

1ae55803b6fb

**Operating system:** 

debian 10 x64

**Comment by Faq** [comment]
Id say missing your view how this should be done in details:
1. stored info in that table, like columns and what info should be there
for example accountid/IP/last connection time, store some unique last 5 IPs or configurable amount via config file?
2. expected input and output of command.

**Comment by Aokromes** [comment]
added table xd

**Comment by jackpoz** [comment]
isn't is stored already in auth.logs_ip_actions ?

**Comment by Aokromes** [comment]
there i only see failed passwords saved.

**Comment by Aokromes** [comment]
Allow.IP.Based.Action.Logging
