### ISSUE TITLE
group repair

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26241]
Description:

how about create one command group repair all players on a group?

The reason for such command is allow a gm create a fresh group of the needed lvl to test things without have to repair 1 char each time

Expected behaviour:

all group repairs

Branch(es):

3.3.5

TC rev. hash/commit:

62594c62f6bb

Operating system:

N/R

**Comment by Faq** [comment]
Meaning, selecting any other group member and using .group repair it will repair all players in that group. Right?

**Comment by Aokromes** [comment]
yes

**Comment by Aokromes** [comment]
db69b83
