### ISSUE TITLE
Feature : allow gms to talk when dead

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26246]
**Description:**

A feature to allow game masters to be able to talk and write commands even when they're dead / ghosts.
Since many hacks already got this thing why not .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 1ae5580

**Operating system:** 

Windows 10 x64

**Comment by Aokromes** [comment]
/g .command
works even without guild

**Comment by CraftedRO** [comment]
hmm ok good to know ;D
