### ISSUE TITLE
[Bug/Misc]Bridge to Lady Vashj

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#2624]
Information taken from: http://www.skryer.com/index.php?art/id:412

"Reaching Lady Vashj
To reach Lady Vashj, you need to clear the initial mobs linked to Hydross the Unstable, as well as the center platform mobs linked to The Lurker Below if you haven't killed these bosses yet. You don't need to clean up all 6 platforms of mobs to reach Lady Vashj's console, only the first 5 platforms. If The Lurker Below is already dead, you don't need to worry about the trash mobs at all since you can just swim to the center platforms and just walk to her console.

Lady Vashj's console is located at the eastern platform (5th platform). You will notice it immediately since the console is rather large. Once you click the console to activate it, there will be a short event of raising the large bridge connecting the platform with the Lady Vashj console and Lady Vashj's lair. After the event, you can then proceed to Lady Vashj's lair. Lady Vashj is immediately there at her platform once you have crossed the bridge, so you don't need to worry about trash mobs."

At the moment, there's an invisible bridge witch can be crossed to reach the final boss, it doesn't require to do anything to activate it.

How the invisible bridge should look when activated: http://www.youtube.com/watch?v=kZxmxa9n9Ys&feature=related

Core revision: 8b83ae0c0539+
Database revision: TDB 335.11.41

**Comment by dr-j** [comment]
This was fixed but when fixed did not know there was issue but have came across this when searching for another issue.

https://github.com/TrinityCore/TrinityCore/commit/192ba1f4a7d5daa63d49c548981de203371d36ba
https://github.com/TrinityCore/TrinityCore/commit/6e1113a81034a4a07b588439f6c5f737e5fa426c
