### ISSUE TITLE
sometimes people enters one instance dead

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26243]
**Description:**

i have seen this bug myself before i started to use the dynamic resurrect patch, with it i got few players reports, idk how to reproduce at all.

**Expected behaviour:**

people must resurrect on enter instance

**Steps to reproduce the problem:**

1. die
2. release
3. enter instance, sometimes you will be as ghost inside.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

1ae55803b6fb

**Operating system:** 

debian 10 x64

**Comment by CraftedRO** [comment]
I think I had find a way to reproduce this but only on a gm level account , go at the entrance of fos / pos / hor for example then .die yourself there (outside of dungeon entrance) come with spirit and enter in any dungeon .

https://user-images.githubusercontent.com/24683355/111073940-7cbdec00-84e9-11eb-92af-d40816ee5775.mp4

**Comment by CraftedRO** [comment]
ok now I was able to reproduce it on a normal account too , but Il edit this in a second :))

**Comment by CraftedRO** [comment]
After relogging as spirit (after I died in ICC then I left party) when I log back on if someone invite me in a group / then it convert to raid again I'm able to enter ICC as a ghost and this will appear in DBErrors log :
```
SQL(p): INSERT INTO character_aura (guid, casterGuid, itemGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges, critChance, applyResilience) VALUES (13, 13, 0, 63531, 6, 6, 1, 0, 3, 3, 0, -1, -1, -1, -1, 0, 0.0, 1)
 [ERROR]: [1062] Duplicate entry '13-13-0-63531-6' for key 'PRIMARY'
```

**Comment by Jildor** [comment]
Maybe that can be a way to reproduce #22234

**Comment by CraftedRO** [comment]
Interesting is that DBErrors appear only when doing the above steps on a Paladin indeed .

**Comment by illfated** [comment]
Not too much data present in `characters`.`character_aura` for a single player:
```sql
SELECT * FROM `character_aura`;
```
```
guid  casterGuid  itemGuid   spell  effectMask  recalculateMask  stackCount  amount0  amount1  amount2  base_amount0  base_amount1  base_amount2  maxDuration  remainTime  remainCharges  critChance  applyResilience
----  ----------  --------  ------  ----------  ---------------  ----------  -------  -------  -------  ------------  ------------  ------------  -----------  ----------  -------------  ----------  ---------------
  3           3       0       1494      3                3           1           0        0       0           0            -1             0               -1          -1         0             0             1
  3           3       0      27044      3                3           1         201        0       0         154            -1             0               -1          -1         0             0             1
  4           4       0      14320      3                3           1          91        0       0          69            -1             0               -1          -1         0             0             1
 10          10       0        465      1                1           1          55        0       0          54             0             0               -1          -1         0             0             1
 12          12       0       1459      1                1           1           2        0       0           1             0             0          1800000     1663220         0             0             1
 13          13       0       2457      3                3           1           0       10       0          -1             9             0               -1          -1         0             0             1
 15          15       0       1243      1                1           1           3        0       0           2             0             0          1800000     1730964         0             0             1
```
(posting this in case you find it useful)

**Comment by CraftedRO** [comment]
I guess I found a proper way to 100% reproduce this: https://youtu.be/0lCmby0edAo (sorry for quality of video, I was reinstalling drivers and my obs fk-ed up)
Steps:
Have two characters in a raid
with one enter inside icc then die there then logout as dead
on the other character leave party
logback in on first one
with the other character .go c 52529 then invite in party spirit character
on ghost character try to enter and it say's you cannot enter because it's not raid, convert to raid
and now you can enter and exist as spirit with ghost character anywhere: enjoy!

**Comment by CraftedRO** [comment]
another way to reproduce this, enter raid or dungeon, die, cast unstuck (while dead) > ???

https://youtu.be/WUIe2jFjR4Y

**Comment by Legoso** [comment]
> another way to reproduce this, enter raid or dungeon, die, cast unstuck (while dead) > ???
> https://youtu.be/WUIe2jFjR4Y

Maybe I am very slow to understand, but that video looks more or less what I would expect to happen every time if you choose to ignore the [Release Spirit] button. I would expect to stay as a ghost in the nearby area (maybe whole instance?) where my player character died, not being able to leave until I press the [Release Spirit] button. What did I miss?

**Comment by CraftedRO** [comment]
I mean being ghost spirit (dead) inside an instance or dungeon is not blizzlike at all, nothing too much to understand.

**Comment by Legoso** [comment]
> I mean being ghost spirit (dead) inside an instance or dungeon is not blizzlike at all, nothing too much to understand.

Very good, thank you. I forgot that lots of stuff in TC is still not blizzlike, particularly stuff like this.

**Comment by Aokromes** [comment]
> > I mean being ghost spirit (dead) inside an instance or dungeon is not blizzlike at all, nothing too much to understand.
> 
> Very good, thank you. I forgot that lots of stuff in TC is still not blizzlike, particularly stuff like this.

well, this a a bug, till today very hard to reproduce bug xd

**Comment by CraftedRO** [comment]
c9ff1d7e40bbc419465fcd3fbefc9d7365539a31 eh seems I found another way to reproduce this while digging into https://github.com/TrinityCore/TrinityCore/issues/25969, you can enter in a raid example icc (tested on heroic), die inside release leave party, restart server, now because the server doesn't know where your corpose was you will be able to enter inside raid as ghost (if you make again the party), I might be wrong but it might be related to this check https://github.com/TrinityCore/TrinityCore/blob/6679ecfeba2565cd185f59ee79415e5f21fb9c41/src/server/game/Maps/MapManager.cpp#L170

**Comment by CraftedRO** [comment]
> I think I had find a way to reproduce this but only on a gm level account (.gm on) , go at the entrance of fos / pos / hor for example then .die yourself there (outside of dungeon entrance) come with spirit and enter in any dungeon .
> 
>  2021-03-14.17-17-39.mp4

2c0ebbef1f5c051a104ef3ba74020b6e7bb2ccaa probably only this case remained here, that's not really important.
