### ISSUE TITLE
Muckshell Snapclaw NPC poison is too strong

### ISSUE THREAD

**Issue by KarMaSSo** [TrinityCore/TrinityCore#26248]
**Description:**

Muckshell Snapclaw NPC is using high level Poison, which is killing too fast.

This NPC is located in zone - Dustwallow Bay / Dustwallow Marsh / Kalimdor.

**Expected behaviour:**

Muckshell Snapclaw NPC should use moderate Poison.

**Steps to reproduce the problem:**

Try to attack Muckshell Snapclaw NPC and wait to be hit by Poison,

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

N/A

**Operating system:** 

Win10 Home 64bit

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9ad59f3cf11458f1c84ca4b4fb0b49b9a0f866a5
Well, weird case
Can't find anything so far

**Comment by illfated** [comment]
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=4402/muckshell-snapclaw
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=25645#used-by-npc

Judging by link 2, the poison spell used by this NPC is also used by https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15336/hivezara-tail-lasher, a level 61 elite scorpid in the Ruins of Ahn'Qiraj raid instance, which indicates that the spell in question is meant for much higher level mobs.

**Comment by leviathonbeast** [comment]
https://classic.wowhead.com/spell=744/poison

wowhead classic seems abit more likely?

**Comment by offl** [comment]
Wowhead classic is useless in case of spells as you can see
Anyway, I already changed to 744
