### ISSUE TITLE
DB/Frostbrood Spawn and Frostbrood Matriarch missing SAI (help wanted)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26257]
```
-- Creating a new SmartAI script for [Creature] ENTRY 32492 (name: Frostbrood Spawn)

-- Table creature_template
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 31702;

-- Table smart_scripts
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 31702);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(31702, 0, 0, 0, 0, 0, 100, 0, 0, 1000, 2500, 3000, 11, 60667, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Frostbrood Spawn - IC - Cast Frost Breath');--
```
```
---- Creating a new SmartAI script for [Creature] ENTRY 32492 (name: Frostbrood Matriarch)

-- Table creature_template
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 32492;

-- Table smart_scripts
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 32492);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(32492, 0, 0, 0, 0, 0, 100, 0, 0, 1000, 2500, 3000, 11, 60667, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Frostbrood Matriarch - IC - Cast Frost Breath');
```
**Description:**

There are a lot of npc-s who only auto-attack (I got a list with some of them from Icecrown).
Two of them are those drakes from Icecrown.
I generated a SAI with [Keira2](http://keira2.altervista.org/Keira2-dev/#/) based on some other drakes like [Frostbrood Whelp](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=31718) but I guess it needs some edits because atm they are spamming this spell :D

**Expected behaviour:**

They shoud also use specific abillities / spells .
According to Gamepedia [Frostbrood Spawn](https://wow.gamepedia.com/Frostbrood_Spawn) and [Frostbrood Matriarch](https://wow.gamepedia.com/Frostbrood_Matriarch) both of them shoud cast [Frost Breath](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=60667)

**Steps to reproduce the problem:**

1. Go to Icecrown and find Frostbrood Spawn and Frostbrood Matriarch drakes.
2. Aggro them .
3. They does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/111547906-8ada6980-8782-11eb-969e-6c85145d925a.mp4

**Comment by CraftedRO** [comment]
maybe we shoud set event_chance 50 :D ?

**Comment by offl** [comment]
Queries for first creature removes existing script, Keira2 uses outdated DB without new script

>it needs some edits because atm they are spamming this spell :D

Such spells are supposed to have almost no cooldown mostly in all cases but there are nuances
I'll slighly edit scripts later

**Comment by CraftedRO** [comment]
Well I guess I shoud use keira3 exe version but it trow some warnings when I connect to tc database .

**Comment by CraftedRO** [comment]
> Such spells are supposed to have almost no cooldown mostly in all cases but there are nuances
btw if there are no cooldown then at least drakes shoud have some limited mana pool maybe ?

**Comment by offl** [comment]
They should not use mana
You can search for existing scripts for examples, some of them may be wrong of course

**Comment by CraftedRO** [comment]
btw I noticed the slow debuff applied by Frost Breath does not have dimishing return kek :)

**Comment by offl** [comment]
Some spells don't have or I'm wrong?

**Comment by CraftedRO** [comment]
Well based on [this question](https://eu.forums.blizzard.com/en/wow/t/why-is-there-no-diminishing-return-on-npc-cc-spells/18022) from blizzard forums you are right.

**Comment by CraftedRO** [comment]
anyway I tested now with set event_chance 50 and seems more decent , but its up to you .

**Comment by BAndysc** [comment]
> Well I guess I shoud use keira3 exe version but it trow some warnings when I connect to tc database .

You can use this smart_script editor: https://github.com/TrinityCore/WoWDatabaseEditor compatible with TrinityCore

**Comment by CraftedRO** [comment]
ok Il try that one too

**Comment by CraftedRO** [comment]
Meh I tryed to compile that but I need another .net update with 3.9 GB so meh Il stay with keira atm :))

**Comment by BAndysc** [comment]
You do not have to compile it, for running it is enough to have _.net 5.0 desktop runtime x64_ from https://dotnet.microsoft.com/download/dotnet/5.0 ~ 150MB.

**Comment by CraftedRO** [comment]
Is [this](https://ci.appveyor.com/api/projects/BAndysc/wowdatabaseeditor/artifacts/WoWDatabaseEditorWindowsWPF.zip?branch=master) what I have to download on windows ? Im lost in so many branches and folders.
In 2k21 things shoud be light and simple to use by people in my opinion (even if target is for experienced developers) .

**Comment by BAndysc** [comment]
Yes, exactly

**Comment by CraftedRO** [comment]
Actually it was second atempt , the first one was building the whole branch.

**Comment by CraftedRO** [comment]
Well I tried your  WoWDBeditor but is not making sense to me it feels even hard to manage than Heidisql lel , but I guess there's a hard work to build such a software , and because of this thing I really need to apreciate you .
