### ISSUE TITLE
[SQL] Wrong loot Wastewander Water Pouch

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26256]
Looks like Wastewander Water Pouch shouldn't drop from Andre Firebeard

https://web.archive.org/web/20120625052907/http://www.wowhead.com/item=8483
https://classic.wowhead.com/npc=7883/andre-firebeard

```SQL
DELETE FROM `creature_loot_template` WHERE `Item`=8483 AND `Entry`=7883;
```

3.3.5
rev. 0dee695

**Comment by offl** [comment]
Yes but you need to use 2010 archieved pages

**Comment by gygyti** [comment]
no data on 2010, but
https://web.archive.org/web/20100411225408/http://www.wowhead.com/item=8483
Related topic
Wastewander Scofflaw
Wastewander Assassin
Wastewander Shadow Mage
Wastewander Rogue
Wastewander Bandit
Wastewander Thief

**Comment by offl** [comment]
Right-click on page and click on option *View page source*
For example you will be taken to ```view-source:http://web.archive.org/web/20100625141124/www.wowhead.com/npc=18760``` if you are using google chrome. I have no idea about other browsers
Type ctrl+f and type something you are looking for. For example for abilities. Or you can always check for Listview. It contains spells, drops, quests and other stuff.
In case of abilities all abilities will be look like that:
```text
new Listview({template: 'spell', id: 'abilities', name: LANG.tab_abilities, tabs: tabsRelated, parent: 'lkljbjkb574', visibleCols: ['school'], hiddenCols: ['reagents', 'skill'], computeDataFunc: Listview.funcBox.initModeFilter, onAfterCreate: Listview.funcBox.addModeIndicator, data: [{"cat":-8,"id":33844,"level":20,"name":"@Entangling Roots","school":3,modes:{"mode":4}},{"cat":-8,"id":15798,"level":20,"name":"@Moonfire","school":6,modes:{"mode":4}},{"cat":-8,"id":9739,"level":20,"name":"@Wrath","school":3,modes:{"mode":4}}]});
```
