### ISSUE TITLE
[SQL] Goreclaw the Ravenous no skinning

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26250]
**Now:** Goreclaw the Ravenous  has no skinning loot (skinning_loot_template)

https://www.wowhead.com/npc=23873/goreclaw-the-ravenous#skinning

```SQL
DELETE FROM `skinning_loot_template`  WHERE `Entry`=23873;
INSERT INTO `skinning_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(23873,4234,0,76,0,1,1,1,1,"Heavy Leather"),
(23873,4304,0,18,0,1,1,1,1,"Thick Leather"),
(23873,4235,0,3,0,1,1,1,1,"Heavy Hide"),
(23873,2318,0,1.6,0,1,1,1,1,"Light Leather"),
(23873,2319,0.9,0,1,1,1,1,"Medium Leather");
```

3.3.5
rev. 0dee695

**Comment by illfated** [comment]
Maybe it should not be more than 3 variants, given the NPC level and area:

- http://web.archive.org/web/20110630044436/http://www.wowhead.com:80/npc=23873#skinning
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=23873

(Light Leather and Medium Leather is usually skinned from NPCs level 5-25.)

**Comment by gygyti** [comment]
I think you are right 
```SQL
DELETE FROM `skinning_loot_template`  WHERE `Entry`=23873;
INSERT INTO `skinning_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(23873,4234,0,80,0,1,1,1,1,"Heavy Leather"),
(23873,4304,0,18,0,1,1,1,1,"Thick Leather"),
(23873,4235,0,2,0,1,1,1,1,"Heavy Hide");
```

**Comment by illfated** [comment]
Not sure if skinning stats is something that could be found in sniffs, so maybe we need to look at the differences elsewhere, like the Wayback Machine and compare it to current pages, targeting the newer game clients.

2011: This NPC has been skinned 3032 times.
2021: This NPC has been skinned 7657 times.

**Comment by offl** [comment]
77 20 3
