### ISSUE TITLE
DB/Frostbrood Sentry SAI (help wanted)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26262]
```
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 32767;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 32767);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(32767, 0, 0, 0, 0, 0, 100, 0, 5000, 7000, 600, 8000, 0, 11, 46406, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Frostbrood Sentry - IC - Cast Bitter Blast');
```

**Description:**

Atm this ones does only auto attack.

**Expected behaviour:**

According to Gamepedia [Frostbrood Sentry](https://wow.gamepedia.com/Frostbrood_Sentry) shoud cast [Bitter Blast](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=46406)

**Steps to reproduce the problem:**

1. Go to Icecrown and find 
2. Aggro them .
3. They does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch)

**Operating system:** 

Windows 10

https://user-images.githubusercontent.com/24683355/111555804-d5afad80-8791-11eb-86f1-d4080a6e428d.mp4

**Comment by CraftedRO** [comment]
but for this one are those correct value from this npc , the only one with bitter blast sai ?
(25756, 0, 0, 0, 0, 0, 100, 0, 5000, 7000, 6000, 8000, 0, 11, 46406, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ahunite Coldwave - In Combat - Cast \'Bitter Blast\'');

**Comment by offl** [comment]
Different creatures can use same spell ids or spells with same name but it doesn't mean they use the same timers

In this case I can't help because that spell is mentioned only in gamepedia and I don't even try to check videos and stuff like that because nobody attacks that creature, so I will find nothing
That creature may use random timers or may spam that spell (ranged mode)

> but for this one are those correct value from this npc , the only one with bitter blast sai ?
(25756, 0, 0, 0, 0, 0, 100, 0, 5000, 7000, 6000, 8000, 0, 11, 46406, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Ahunite Coldwave - In Combat - Cast 'Bitter Blast'');

Not really correct but close to correct

**Comment by CraftedRO** [comment]
but since you sad earlier that we can guess them maybe we can implement this ones instead noone :D

**Comment by offl** [comment]
I'll use version with random timers, yeah

**Comment by CraftedRO** [comment]
I updated this one too.

**Comment by offl** [comment]
0, 2000, 6000, 8000
These timers are correct\more correct, I didn't noticed that spell can be used only at 5 - 45 yards
That explains why in sniff creature used it only after being summoned
