### ISSUE TITLE
DB/Savage Proto-Drake missing SAI (help wanted)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26263]
```
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 31265;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 31265);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(31265, 0, 0, 0, 9, 0, 100, 0, 0, 5, 2000, 3500, 0, 11, 51219, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Savage Proto-Drake - On Range - Cast Flame Breath'),
(31265, 0, 1, 0, 9, 0, 100, 0, 0, 20, 10000, 15000, 0, 11, 41572, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Savage Proto-Drake - On Range - Cast Wing Buffet');
```

**Description:**

Atm this ones does only auto attack.

**Expected behaviour:**

According to Gamepedia [Savage Proto-Drake](https://wow.gamepedia.com/Savage_Proto-Drake) shoud cast [Flame Breath](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51219) and [Wing Buffet](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=41572).

**Steps to reproduce the problem:**

1. Go to Icecrown and find Savage Proto-Drake.
2. Aggro them.
3. They does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/111615189-1b4b9500-87e9-11eb-98b9-c1291868fd0c.mp4

**Comment by offl** [comment]
Videos are not really needed in this kind of issues
And you need to use different timers in case of such spells, try to check timers for same spells in existing scripts

**Comment by CraftedRO** [comment]
I messed up something here :) Il try to find what timers are you talking about

**Comment by offl** [comment]
```sql
SELECT * FROM `smart_scripts` WHERE `comment` LIKE '%Flame Breath%'

**Comment by CraftedRO** [comment]
Well im kinda dumb at understanding this and somehow [TC wiki](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130108/smart+scripts) doesn't help me too much but I guess its about those parameters but where did we take correct ones for each specific creature/spell ?
```
event_param1, event_param2, event_param3
InitialMax      RepeatMin    RepeatMax
1000,             2500,       3000
```

**Comment by CraftedRO** [comment]
it seems like another drake : Plagued Proto Dragon is using those values : 
(23680, 0, 1, 0, 0, 0, 100, 0, 5000, 7000, 10000, 15000, 0, 11, 9573, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Plagued Proto-Dragon - In Combat - Cast \'Flame Breath\' (Phase 2)'),
Maybe this ones are correct ones for Savage Proto-Drake too :D ?

**Comment by offl** [comment]
You used event_type 0 which is SMART_EVENT_UPDATE_IC (In Combat)
event_type has 5 params: event_param1 - event_param5

In case of SMART_EVENT_UPDATE_IC
event_param1 is InitialMin
event_param2 is InitialMax
event_param3 is RepeatMin
event_param4 is RepeatMax

**Comment by offl** [comment]
> Maybe this ones are correct ones for Savage Proto-Drake too :D ?

Yes, those timers looks more valid for such spells

> but where did we take correct ones for each specific creature/spell ?

Mostly they are guessed

**Comment by CraftedRO** [comment]
somehow [AC wiki](https://www.azerothcore.org/wiki/smart_scripts) is more understandable at least SAI part :)

**Comment by offl** [comment]
It's the same info, maybe it's more understandable because it's smaller

> As a recommendation, you can review the scripts that are already inside the table, to understand how it works.

True
Wiki usually provides basic description

**Comment by CraftedRO** [comment]
I updated this one too.

**Comment by offl** [comment]
Event type range is bad chose in 99% of cases
It uses no initial timers while Blizz almost always uses initial timers for all their spells
