### ISSUE TITLE
Spell/Priest Fade & Massdispel dont get his Rank2

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#26277]
**Description:**

The Priest dont learn two of his Passive Rank2 Spells if he reach the level thats shown in Spellbook.

- https://www.wowhead.com/spell=327821/fade
- https://www.wowhead.com/spell=327830/mass-dispel

**Expected behaviour:**

The Priest should learn the Rank2 Spells if he reach the lvl that is shown in Spellbook.

**Steps to reproduce the problem:**

1. create a Priest
2. levelup to 60
3. Open Spellbook and take a look to your spells.

**Branch(es):**

master

**TC rev. hash/commit:** 

69e0b9a98516a0cac14bc3f985a2deb2fe79205f

**Operating system:** 

Win10

**Comment by matanshukry** [comment]
Note: one of the new enums could change acquire method and might solve this issue. Will update this issue after either way.

**Comment by Nyr97** [comment]
Any updates on this new enum that could possible fix this? 👀

**Comment by Naddley** [comment]
outdated. Spell Ranks dont exist anymore for both spells.
