### ISSUE TITLE
DB/Scourge Soulbinder missing SAI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26273]
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 32284;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 32284);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(32284, 0, 0, 0, 0, 0, 100, 0, 0, 1000, 2500, 3000, 0, 11, 60814, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Scourge Soulbinder - In Combat - Cast 'Frost Blast'"),
(32284, 0, 1, 0, 0, 0, 100, 0, 9000, 14000, 14000, 20000, 0, 11, 22744, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Scourge Soulbinder - In Combat - Cast 'Chains of Ice'"),
(32284, 0, 2, 0, 0, 0, 100, 0, 12600, 25200, 16700, 32300, 0, 11, 17620, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Scourge Soulbinder - In Combat - Cast 'Drain Life'");
```

**Description:**

Atm this ones does only auto attack.

**Expected behaviour:**

According to [Gamepedia ](https://wow.gamepedia.com/Scourge_Soulbinder) and old wowhead [Scourge Soulbinder](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32284) shoud cast :   [Chains of Ice](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=22744) [Drain Life](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=17620) and [Frost Blast](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=60814)
view-source:http://web.archive.org/web/20100424080846/http://www.wowhead.com/npc=32284

I tested the above script ingame and it seems it works well but I guess it need some adjustments , hi offl :)

**Steps to reproduce the problem:**

1. Go to the Icecrown and find Scourge Soulbinder.
2. Attack him
3. Notice does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 8c3cddd0d221

TrinityCore rev. 8c3cddd0d221 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

**Comment by CraftedRO** [comment]
btw I won't give up 🙃

**Comment by offl** [comment]
Better to use " " in case of all texts, it's easier
```sql
"Scourge Soulbinder - In Combat - 'Frost Blast'"),
```

And ```sql to show syntax
