### ISSUE TITLE
DB/Necrotic Webspinner missing SAI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26289]
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 31747;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 31747);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(31747, 0, 0, 0, 0, 0, 100, 0, 2000, 6000, 12000, 16000, 0, 11, 744, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Necrotic Webspinner - In Combat - Cast 'Poison'"),
(31747, 0, 1, 0, 0, 0, 100, 0, 1000, 3000, 10000, 15000, 0, 11, 745, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Necrotic Webspinner - In Combat - Cast 'Web'");
```

**Description:**

Atm this ones does only auto attack.

**Expected behaviour:**

According to old wowhead [Necrotic Webspinner](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=31747) shoud cast : [Poison](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=744) and [Web](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=745)
view-source:http://web.archive.org/web/20100415081520/http://www.wowhead.com/npc=31747

**Steps to reproduce the problem:**

1. Go to the Icecrown and find Necrotic Webspinner
2. Attack him
3. Notice does only auto attack you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 5fe74db30477

TrinityCore rev. 5fe74db30477 2021-03-20 20:29:01 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

**Comment by CraftedRO** [comment]
I guess here timers need a bit ajustments , btw there is a command to reload ingame SAI without restarting ther whole worldserver , .reload smart_scripts dosen't work for those.

**Comment by offl** [comment]
You need to reset creature to reload its script(kill and respawn for example)
