### ISSUE TITLE
Quest / It Goes to 11...

### ISSUE THREAD

**Issue by Aldoran2020** [TrinityCore/TrinityCore#26281]
**Description:**

Quest: ID 11421
https://www.wowhead.com/quest=11421/it-goes-to-11
The harpoon control mechanism is not working it is not possible to use it 

**Expected behaviour:**

Use the harpoon gun to rain hell upon Wyrmskull Village! Destroy the longhouse, dockhouse, storage facility and any defenders

**Steps to reproduce the problem:**

1. add quest: 11421, go Howling Fjord and try use the harpoon.

**Branch(es):**

335

**TC rev. hash/commit:** 

TrinityCore rev. 8c3cddd 2021-03-15 17:34:11 +0000 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** 

windows pro

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/6844
