### ISSUE TITLE
DB/Frostbrood Skytalon missing SAI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26287]
```sql
-- Frostbrood Skytalon
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 31137;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 31137 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(31137, 0, 0, 0, 0, 0, 100, 0, 0, 5000, 5000, 15000, 11, 60667, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Frostbrood Skytalon - In Combat - Cast 'Frost Breath'");
```

**Description:**

Atm this ones doesn't even aggro you.

**Expected behaviour:**

According to [Gamepedia](https://wow.gamepedia.com/Frostbrood_Skytalon) and old wowhead Frostbrood Skytalon shoud cast : [Frost Breath](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=60667)
view-source:http://web.archive.org/web/20100423201253/http://www.wowhead.com/npc=31137

**Steps to reproduce the problem:**

1. Go to the Icecrown and find Frostbrood Skytalon
2. Attack him
3. Notice it doesn't even aggro you.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 5fe74db30477

TrinityCore rev. 5fe74db30477 2021-03-20 20:29:01 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

**Comment by offl** [comment]
> Atm this ones doesn't even aggro you.

Same as #26272? Does SAI change that?

**Comment by CraftedRO** [comment]
in this case yea it works

**Comment by CraftedRO** [comment]
even in the Stormpeak Wyrm case it works but only for auto attack part , they self cast that spell and self harm

**Comment by offl** [comment]
Looks like he and #26257 uses ranged caster mode but can't find something to be 100% sure, sniffs doesn't help
I checked that creature when you opened #26257 but looks like didn't noticed how really he acts
Anyway, let's leave as it is
