### ISSUE TITLE
Spell/Frosthowl Screecher Shadow Bolt 52257 can't be casted (no target)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26288]
**Description:**

Even if the npc have you as target , when they are tryng to cast this spell it trow no target error.
You can simple test this spell with a GM level account on any target .cast 52257 and it will warn you that you don't have target , even if u have a target.

**Expected behaviour:**

[Frosthowl Screecher](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=28170) shoud be able to cast [Shadow Bolt](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=52257) on they'r current target .

**Steps to reproduce the problem:**

1. Go to the Sholazar Basin and find Frosthowl Screecher
2. Attack them .
3. Notice they're only auto attack you because when they cast Shadow Bolt they get the no target error as we get as GM when we are casting this .

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 5fe74db30477

TrinityCore rev. 5fe74db30477 2021-03-20 20:29:01 +0200 (3.3.5 branch) (Win64, Release, Static)

**Operating system:** 

Windows 10 x64

https://user-images.githubusercontent.com/24683355/111908312-696acd80-8a61-11eb-9b89-354ddba2dfe8.mp4

**Comment by Aokromes** [comment]
very likely conditions.

**Comment by offl** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=52257#conditions

**Comment by offl** [comment]
Are you sure they should cast that spell on player?

**Comment by offl** [comment]
In sniff they casts it only on vehicle

**Comment by CraftedRO** [comment]
hmm thanks for research , and sorry for wasting time .
