### ISSUE TITLE
Core/Areatrigger tavern: A way to enable areatrigger tavern only under certain conditions

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26292]
**Description:**

after you complete "it's all fun and games" quest chain you don't get rested on shadow vault.

**Expected behaviour:**

you must get rested there.

**Steps to reproduce the problem:**

1. take one of this 2 quests:

12892 - [It's All Fun and Games] 
12887 - [It's All Fun and Games] 

2. complete chain
3. enter shadow vault
4. notice no rested

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5fe74db30477

**Operating system:** 

debian 10 x64

**Comment by offl** [comment]
Why only after completing quest chain?

**Comment by Aokromes** [comment]
> Why only after completing quest chain?

because before it's hostile zone xd

**Comment by offl** [comment]
Is it implemented somewhere else?
Maybe just areatrigger_tavern is missing

**Comment by Aokromes** [comment]
dunno.

**Comment by offl** [comment]
SELECT * FROM areatrigger_tavern WHERE id=5309

Yeah, nothing

**Comment by illfated** [comment]
- https://wow.gamepedia.com/Shadow_Vault#Wrath_of_the_Lich_King
(Before completing the questline, it is controlled by the Scourge, after completing the questline, it turns into an inn.)

I think this is one of the phased areas in Icecrown, that is at least how it appears to a player, although it is possible that I have misunderstood how phasing works.

**Comment by Aokromes** [comment]
sooo

DELETE FROM `areatrigger_tavern` WHERE `id` =5309;
INSERT INTO `areatrigger_tavern` (`id`, `name`) VALUES
(5309, 'Shadow vault');

**Comment by Aokromes** [comment]
but it will need phasing support i suppose.

**Comment by Edder** [comment]
I'm currently on this one and thought of two possible ways to fix this.
1. Add an areatriger_script and SetRestFlag to player if this AT is triggered and player has correct phaseMask (1 in this case).
RestFlag will be automatically removed when leaving the AT radius in Player::Update
No need for this AT to be in areatrigger_tavern, although it wouldn't be a problem either, the AT is completely handled by script.

2. Add a "phaseMask" column to areatrigger_tavern with the needed phaseMask for this inn to be triggered and implement it accordingly.

I think option two is the better way, but Shadow Vault seems to be the only tavern in 3.3.5 which is only activated in a specific phase, so it's kinda overdone.

What do you guys think?

**Comment by offl** [comment]
Try to ask in IRC, you will receive feedback faster(maybe not)
Master guys may be interested in more proper implementation if that mechanic is used more often in cata+

**Comment by offl** [comment]
<details>

```text
<Offle> Ovahlord you have phased areatrigger taverns?
<Ovahlord> I think yes
<Ovahlord> though 335 and 4.x have different phasing systems so whatever you try to ask, I cant help
<Offle> implementation should be similar
<Ovahlord> no, it's not at all
<Ovahlord> 4.x uses phase Ids and terrainswaps
<Ovahlord> 335 just has a plain bitmask
<Offle> I mean in general https://github.com/TrinityCore/TrinityCore/issues/26292#issuecomment-847241607
<Offle> the way it's implemented
<Ovahlord> the client does not trigger area triggers on 4.x when the phaseId is mismatching
<Offle> cool
<Ovahlord> anyways, conditions for area triggers shouldnt be hard to support
<Offle> we don't have them for areatrigger teleport atm
<Offle> but sounds good
<Offle> since it's the same system if I'm not wrong
<Ovahlord> ah the issue is having the resting state on the shadow vault
<Offle> maybe it's too implemented in client in 335? :D
<Ovahlord> nah
<%Shauren> its not, 335 areatrigger.dbc doesnt have anything
<Ovahlord> phasing in 335 blows ass
<Ovahlord> so i went to the shadowvault on 4.x, no area triggered in default phase
<Ovahlord> whats the phasing aura when the chain is complete at shadowvault?
<Offle> what's the area?
<Ovahlord> 4477
<Offle> 30181
<Ovahlord> thats the hostile phase
<Offle> I have only one spell SELECT * FROM spell_area WHERE AREA=4477
<Ovahlord> ye, you need to be in phase 169 (default phase) to trigger at 5309
<Offle> 55409
<Offle> https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=55409
<Ovahlord> ye no, so looks like the phasing auras are for stages when the vault is not captured yet and 169 is when you have conquered it
<Ovahlord> because 169 triggers the area trigger
<Offle> tbh no idea
<Ovahlord> no rly :D
<Ovahlord> so in your case 335 would either need a phasemask condition or you implement a table that replicates 4.x phasing checks
<Ovahlord> in this case 5309 should only be allowed to trigger when phasemask is 0
<%Shauren> you mean 1
<%Shauren> you cant be in 0 on 3.3.5
<Ovahlord> ah right
<Ovahlord> you could also implement a phasemask field in areatrigger tavern and check for phasemasks there
<Offle> or fix both issues (https://github.com/TrinityCore/TrinityCore/issues/22965) via conditions
<Ovahlord> that sounds like it would use a script and a spell to teleport. not using areatrigger_teleport
<Offle> hm, Eversong Woods - Duskwither
<Offle> dark portal requirement with no doubt is conditioned, but only in master
<Ovahlord> 4233 at?
<Offle> yes Eversong Woods - Duskwither UP Target, Eversong Woods - Duskwither DOWN Target
<Offle> don't remember where it is
<Ovahlord> just do .tele duskwither
<Ovahlord> you stand right in front of the teleport device
<Ovahlord> and check sniffs for spells
<Offle> I doubt I have any atm
<Offle> we also have https://github.com/TrinityCore/TrinityCore/issues/18871 and it's not yet clear for me if triggers indeed are not used
<Offle> so, CONDITION_SOURCE_TYPE_AREATRIGGER?
```

</details>
