### ISSUE TITLE
creature_template data from massparses (8.2.0 - 9.0.2)

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#26299]
**Description:**

massparses of my sniffs

**Branch(es):**

master

**TC rev. hash/commit:** 

88f4d30445937b9de42f5cb25acad75fc89bdccb

**Notes:**

What I did: I parsed all sniffs of one patch (e.g. 8.1.0), applied the file to my local world db, started parsing of next patch.
For `creature_template` I also commented UPDATEs for `gossip_menu_id=0` out because we had some issues with this last time. (for 9.0.1 and 9.0.2 i commented it but also added the same statement just without gossip_menu_id)

**creature_template, creature_model_info, creature_template_model**
820: https://gist.github.com/mdX7/fa511adb8c7a54780616c87dc420ea7a
825: https://gist.github.com/mdX7/3fcd9bbf0947f616351332212d7280cd
830: https://gist.github.com/mdX7/b8cbaef8464205fd8f45c16f56ecce4c
837: https://gist.github.com/mdX7/aff7a5ccb1fea71f4a174995db270f31
901: https://gist.github.com/mdX7/385c090d32b89f7467c5e7fde9dff470
902: https://gist.github.com/mdX7/08f92dee3429b54ee9bab9aaef9bcecf

**creature_template_scaling**
820: https://gist.github.com/mdX7/b67887a8ddfe2c09109d7b2572076edc
825: https://gist.github.com/mdX7/21993458c379a3d6fb43e141a13c83f7
830: https://gist.github.com/mdX7/0f06b43107a037213a17217fb327de17
837: https://gist.github.com/mdX7/50d99ca5fb4ed28d23c3ece959790dbd
901: https://gist.github.com/mdX7/f548794b3e74f8b9c8969f9a80b2d861
902: https://gist.github.com/mdX7/3e399a7ca9be3d35da32cb4d9439ac71

**creature_equip_template**
820: https://gist.github.com/mdX7/9cb7332465593f700cf0d3ecd15ebf75
825: https://gist.github.com/mdX7/c4cf667e77010f611d0bc0aaf3b248b9
830: https://gist.github.com/mdX7/df2c1879674bfdee31d41a0747f22d08
837: https://gist.github.com/mdX7/a98159183ae8039a0a5f6c6e290b7d53
901: https://gist.github.com/mdX7/a581d446483f5359dc40ae9cebe93e18
902: https://gist.github.com/mdX7/b7b885e9b95d251e43c38370da64d670

EDIT: i realized i forgot like 90% of my 8.3.0 sniffs in that parse, heres rest: https://gist.github.com/mdX7/dfce34200fa5d768e13696c6bd508162

**Comment by ReyDonovan** [comment]
@mdX7 thanks for the data
some mobs have incorrect data, for example, the starting location of the alliance druids, we see level 30 cats

**Comment by mdX7** [comment]
that is likely caused because i did not re-sniff that in sl yet and the scaling changed a bit between bfa and sl

**Comment by funjoker** [comment]
Gonna skip creature_template_scaling before SL, because we need to resniff those data anyway
