### ISSUE TITLE
Quest - 'Oran's Gratitude' is missing description and quest objective text

### ISSUE THREAD

**Issue by KarMaSSo** [TrinityCore/TrinityCore#26293]
**Description:**

Quest - 'Oran's Gratitude' does not contain description and quest objective text

**Expected behaviour:**

Quest - 'Oran's Gratitude' should display it's description and quest objective text

**Steps to reproduce the problem:**

Quest is given by Oran Snakewrithe in Undercity (prerequisite is Rin'ji's Secret), take it and see that quest details are empty.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

N/A

**Operating system:** 

Windows 10 Home 64bit

**Comment by offl** [comment]
Not a bug in that and 700 another quests
