### ISSUE TITLE
[Quest] Iron Rune Constructs and You: The Bluff

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26307]
**How it now:**
When you cast the spell Bluff, Lebronski says but it does not trigger the quest criteria to be completed.

**Expected behaviour:**
The quest criteria should be given when you cast the Bluff spell after Lebronski gets pissed at you.

**How to**
1 .quest add 11491
2 go to the work bench
3 stay on Lebronski's rug 
3 use Bluff

https://github.com/TrinityCore/TrinityCore/issues/22485

[https://www.wowhead.com/quest=11491/iron-rune-constructs-and-you-the-bluff](https://www.wowhead.com/quest=11491/iron-rune-constructs-and-you-the-bluff)

3.3.5
rev. 0dee695

**Comment by Aokromes** [comment]
plz update your core before reporting new bugs.

**Comment by offl** [comment]
That script probably never worked, there are obvious mistakes that does not allow it to work or something was broken recently

**Comment by Aokromes** [comment]
till 2020 worked xd

**Comment by dr-j** [comment]
Well seems I made below fix in 2019 which was for credit and a bad target for text from this quest
~~~sql
UPDATE `smart_scripts` SET `target_type`='7' WHERE  `entryorguid`=2471801 AND `source_type`=9 AND `id`=3 AND `link`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=2471801 AND `source_type`=9 AND `id`=5 AND `link`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(2471801, 9, 5, 0, 0, 0, 100, 0, 10000, 10000, 0, 0, 0, 22, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Stanwad - Action list - Set Phase 1');

**Comment by Aokromes** [comment]
@offl valid?
