### ISSUE TITLE
vmap4assembler error during Extracting VMaps

### ISSUE THREAD

**Issue by dontrix123** [TrinityCore/TrinityCore#26310]
**Description:**

(Linux Server Setup) - https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977340/Linux+Server+Setup

**Error during vmap4assembler**

![trinity](https://user-images.githubusercontent.com/14906496/112182577-60802480-8c38-11eb-93c4-1eebee394ccb.PNG)

**Expected behaviour:**

after executing the '/home/<username>/server/bin/vmap4assembler Buildings vmaps' the command should be successfull and completed without error.

**Steps to reproduce the problem:**

1. cd <your WoW client directory>
2. /home/<username>/server/bin/vmap4extractor
3. mkdir vmaps
4. /home/<username>/server/bin/vmap4assembler Buildings vmaps

**Branch(es):**

master

**TC rev. hash/commit:** 

**Operating system:** 

Ubuntu 20.04.2 LTS

**Comment by Aokromes** [comment]
i vote user error.

**Comment by MaxtorCoder** [comment]
> i vote user error.

100% user error.
