### ISSUE TITLE
DB/Quest: Locked Away is missing text.

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26313]
**Description:**

The quest [Locked Away](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5060) obtained from the [locked cabinet](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=175924) at Dalson's farm in Western Plaguelands is missing quest text.

<details>

![image](https://user-images.githubusercontent.com/66294837/112279757-60376600-8cd8-11eb-9153-e172bcf037aa.png)

</details>

```sql
SELECT `LogTitle`,`LogDescription`,`QuestDescription`,`AreaDescription`,`QuestCompletionLog` FROM `quest_template` WHERE `id` = 5060;
```
---
| LogTitle | LogDescription | QuestDescription | AreaDescription | QuestCompletionLog | 
| --- | --- | --- | --- | --- | 
| Locked Away |  |  |  | Return to Locked Cabinet in Western Plaguelands. | 

**Expected behaviour:**

Quest should contain premise and objectives.

**Steps to reproduce the problem:**

1. Make your way to the farm located at ~(47.4,49.6 )
2. The house is on the left and the barn is on the right - head upstairs in the house
3. Locked Cabinet is on the top floor
4. Click to accept the quest - no text
5. Click the Locked Cabinet again after taking the quest and IT has text

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

TrinityCore rev. 1e76fc7a5dd4 2021-03-23 23:09:34 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) 

**Operating system:**

Windows 7 Ultimate x64 SP1

**Comment by offl** [comment]
https://classic.wowhead.com/quest=5060/locked-away
https://www.wowhead.com/quest=5060/locked-away
http://web.archive.org/web/20100823021944/www.wowhead.com/quest=5060
Looks like I need to write them from my head
It's **completely fine** that one or more texts are missing, it's **intended**

**Comment by offl** [comment]
And duplicate of #26052
