### ISSUE TITLE
Crash in GameObjectModel::IntersectRay

### ISSUE THREAD

**Issue by silviu20092** [TrinityCore/TrinityCore#26328]
**Description:**

Segmentation fault in GameObjectModel::IntersectRay line 168

https://gist.github.com/silviu20092/c658497517671c2b38effffada5bfe39

**Steps to reproduce the problem:**

Don't know the exact steps, there is no specific message before crashing. Last message was: Could not load MMAP name:Kalimdor, id:1, x:53, y:26 (mmap rep.: x:53, y:26) but the console is full of these messages frequently.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/80f30d5ca94f000962a06e398567aa0b1ddd706b

**Operating system:** 

Debian 10

Custom changes: just a few of my spellscripts and autobalance patch from https://github.com/trickerer/Autobalance_for_NPCBots

EDIT: I think this might be the same issue that was posted here https://github.com/TrinityCore/TrinityCore/issues/24513 . Appears to be an old bug.

**Comment by illfated** [comment]
From https://gist.github.com/silviu20092/c658497517671c2b38effffada5bfe39#file-gistfile1-txt : `BACKTRACE FULL`

Please add label **[HasBacktrace]** to this ticket.

**Comment by illfated** [comment]
```sql
Could not load MMAP name:Нордскол, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
```
Those lines are not likely to cause issues or crashes, most of them are "out of bounds" tiles in mmaps, also known as false positives.
See https://github.com/TrinityCore/TrinityCore/search?q=%22Could+not+load+MMAP+name%22&type=issues

**Comment by micckkk** [comment]
Confirmed. Crash happens every few days

**Comment by Aokromes** [comment]
no one reported the same crash for 2 years, the one confirming is using 5 years core, closing.
