### ISSUE TITLE
DB/Profession: Tailoring 300/300

### ISSUE THREAD

**Issue by NiganNi** [TrinityCore/TrinityCore#26333]
**Description:**
Tailoring 300/300 
It is impossible to study further
![111](https://user-images.githubusercontent.com/61392055/113107021-12f15200-920c-11eb-9c57-6ab733708eb3.jpg)
Already wrote in another topic, so the description in the screenshot

**Expected behaviour:**
Give the opportunity to study tailoring up to 350

**Steps to reproduce the problem:**
Create a hero
Raise Tailoring Level to 300.

**Branch(es):**
master

**TC rev. hash/commit:**
TrinityCore rev. c9344c145ad1+ 2021-02-26 22:10:34 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

**Operating system:**
Win10 x64

**Comment by MaxtorCoder** [comment]
Why did you create ANOTHER issue..??? You can _literally_ change the title.
