### ISSUE TITLE
Core/Player: Character leaves no footprints if jumps instantly after previous jump

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#26337]
**Description:**

That's right, if you jump in Tanaris or Winterspring and jump instantly after previous jump, your character will not leave footprints so your enemies will be not able to track you. Technically you can always leave no footprints at all but for that you need to be really skilled.

**Expected behaviour:**

Character should leave footprints even if he always jumps. I checked some rabbits and seems like they always leaves footprints but I think it may be related to how their model works(they don't actually jump, it's just their model).

**Steps to reproduce the problem:**

1. tele to Tanaris or Winterspring
2. try to jump and jump instantly after previous jump
3. you will notice that sometimes character leaves no footprints

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 5fe74db304777b65cae756bc74e57c7d17ced6e9

**Comment by Shauren** [comment]
clientside

**Comment by offl** [comment]
I knew better to open PR and convert Icecrown bosses to SAI or something like that
Happy Fools' Day, of course it's serverside and nobody will ever track your footprints which disappears in less than one minute :D
