### ISSUE TITLE
gossip_menu data from massparses (8.2.0 - 9.0.2)

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#26339]
**Description:**

massparses of my sniffs

**Branch(es):**

master

**TC rev. hash/commit:** 

88f4d30445937b9de42f5cb25acad75fc89bdccb

**Notes:**

What I did: I parsed all sniffs of one patch (e.g. 8.1.0), applied the file to my local world db, started parsing of next patch.
For multiple matches in broadcast_text I replaced UNKNOWN with the first available result (kept comments though)

820: https://gist.github.com/mdX7/f97c718b99ee4203d716c0b5c50f9c21
825: https://gist.github.com/mdX7/142e6cfa25f6ca635cb2e840b4fe442d
830: https://gist.github.com/mdX7/1379b79461804f284a00fe9931189847
837: https://gist.github.com/mdX7/04d109fa3a116ce772401339d2fafe46
901: https://gist.github.com/mdX7/9f0ab777d961190045ba1bbde92e0a8a
902: https://gist.github.com/mdX7/fe2e27090a608eef096e5bb32ebdc836

**Comment by funjoker** [comment]
what happend with the actions?

**Comment by mdX7** [comment]
not sure if its that useful to provide massparsed actions since they will be likely wrong for a lot of stuff i guess

**Comment by funjoker** [comment]
:/ i think they prolly will work

at least parse them and give them to me x)

**Comment by mdX7** [comment]
> 
> 
> :/ i think they prolly will work
> 
> at least parse them and give them to me x)

just realized theres not option to parse them in wpp xD
![grafik](https://user-images.githubusercontent.com/12143653/119268285-869f5200-bbf2-11eb-892c-82ffb9ff97a1.png)

**Comment by funjoker** [comment]
> > :/ i think they prolly will work
> > at least parse them and give them to me x)
> 
> just realized theres not option to parse them in wpp xD
> ![grafik](https://user-images.githubusercontent.com/12143653/119268285-869f5200-bbf2-11eb-892c-82ffb9ff97a1.png)

you are wrong, it has

**Comment by mdX7** [comment]
will reparse due to recent gossip_menu_option changes, also i noticed what happened to actions - forgot some packets in filters :D
