### ISSUE TITLE
DBC/DB2 extracting : Unable to read field common values

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#26349]
**Description:**

 An error occurs during extraction with "mapextractor" - see log ==> post the crashlog [= link](https://gist.github.com/shamage/c4b83cbaf90ae68092b3c5b2d1a35705)

if I ignore the error, after compiling and then running world.exe, it crashes during the compilation process and displays: "File ./dbc/enUS/WMOAreaTable.db2 does not exist
Unable to load db2 files for enUS locale specified in DBC.Locale config! "

**Expected behaviour:**

the extraction should proceed without errors

**Steps to reproduce the problem:**

1.  the extraction process should be complete without errors

**Branch(es):**

CHANGEME  master 

**TC rev. hash/commit:** 

TrinityCore rev. c648ac58e0a0 2021-04-05 14:48:00 +0200 (master branch) (Win64, RelWithDebInfo, Static) (Map & DBC Extractor) 
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
MySQL client library: 5.7.32

**Operating system:** 

Windows 10 Pro , ver. 20H2 , build 19042.867

**Comment by Faq** [comment]
What is client version?

**Comment by MaxtorCoder** [comment]
> What is client version?

902.37474, it's in the logs.

**Comment by MaxtorCoder** [comment]
> Would it be possible for at least two to try to extract values using the "mapextractor" program? (It only takes a few minutes) I also had the idea that this is not just an isolated problem, such that some values are missing or damaged in the game and therefore are not extracted from me. With this test, I would like to rule out or confirm whether this problem did not only arise for me and everything is fine for the others.
> Since I can't download this version of the game again (the current available version of the game is already 9.0.5.38134) I can't even test it for myself. Can anyone help me with this?

I haven't had any issues, sounds like.broken client.

**Comment by shamage** [comment]
I managed to get to the whole game with completely correct data and after trying to extract the database everything went well - see [log ](https://gist.github.com/shamage/631a85db64d6e55a9da0c3f73c4289d3)
finally, on my HDD, there were incorrect or corrupted pieces of data in the game that appeared to be fine on the outside.
I close this topic as resolved - thank you all for your help and support.
