### ISSUE TITLE
TrinityCore - Hotswapping - Not working as expected

### ISSUE THREAD

**Issue by mgracia012020** [TrinityCore/TrinityCore#26342]
**Description:**

CHANGEME Description of the problem or issue here.
I followed the instructions from https://trinitycore.atlassian.net/wiki/spaces/tc/pages/18874377/Using+the+script+hotswapping+system#Usingthescripthotswappingsystem-Enablingthehotswapsystem to configure hotswapping.

I compiled the source using VS2019 - compiles clean, no errors.

I copied the files generated under RelDebInfo (includes the scripts folder) to my server directory. I am able to start the servers without error. When changing one of the source scripts with a text-editor and saving the changes, the world server does not pickup the changes.

I also followed steps below from the hotswap trinity confluence link above:

Set the CMAKE_INSTALL_PREFIX to a location in your filesystem (not C:/ on windows since it's write protected in most cases).
Use the cmake INSTALL project target in Visual Studio (or make install on unix), to install TrinityCore to the location specified by CMAKE_INSTALL_PREFIX .
Start the worldserver from the location specified by the CMAKE_INSTALL_PREFIX.
For step two, i ran cmake install "my-install-dir-name-here" "my-source-dir-here" (executed from the build dir promt using the VS developer command tool).

Am i using step 2 incorrect? If yes, what is the proper syntax?

eg.: cmake install "c:\trinityserver\servers" ../ When I ran this commend, the installation files are not copied over to the install dir.

See below the output of the cmake install command above:

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.9.3
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************

C:\Shadowlands-Master\Build>cmake INSTALL "C:\Trinity-Servers\Shadowlands-Server\Servers" ../
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
....... Omitted to save space
-- MSVC: Disabled generic compiletime warnings
-- MSVC: Enabled shared linking
-- Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
-- Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
-- Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
-- Found git binary : C:/Program Files/Git/cmd/git.exe

* TrinityCore revision   : f7ecd235d881+ 2021-03-29 19:39:22 -0400 (master branch)

* Install core to        : C:/Trinity-Servers/Shadowlands-Server/Servers

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (dynamic)
* Build map/vmap tools   : Yes (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

 *** WITH_DYNAMIC_LINKING - INFO!
 *** Will link against shared libraries!
 *** Please note that this is an experimental feature!

-- Found OpenSSL library: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
-- Found OpenSSL headers: C:/Program Files/OpenSSL-Win64/include
CMake Warning (dev) at cmake/macros/FindOpenSSL.cmake:231 (math):
  Unexpected character in expression at position 2: b

Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

* Script configuration (dynamic):
    |
    +- scripts_argus.dll
    |   +- Argus
    |
....Omitted to save space 
 |
    +- scripts_world.dll
    |   +- World
    |

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Shadowlands-Master/Build

C:\Shadowlands-Master\Build>

**Expected behaviour:**

Worldserver will recompile the scripts libraries with changes to a source script - using the source directory. When compiling the build the files will be generated in the specified install directory.

**Steps to reproduce the problem:**

1. compiled trinitycore mast (latest branch) with cmake and VS2019
2. CMAKE was configured for hotswapping - following instructions from trinitycore hotswapping link above
3. Copying the generated build to server directory and starting the servers do not show dynamic changes to scripts in the source directory.

**Branch(es):**

master

**TC rev. hash/commit:** 
TrinityCore rev. f7ecd235d881+ 2021-03-29 19:39:22 -0400 (master branch) (Win64, RelWithDebInfo, Dynamic) (worldserver-daemon)

**Operating system:** 

Windows 10 pro

**Comment by mdX7** [comment]
when using CMake GUI you set the install directory in there. `CMAKE_INSTALL_PREFIX`. In there you'd also set to use dynamic linking & dynamic scripts.
When using CLI you'd have to pass `-DCMAKE_INSTALL_PREFIX=<path>` to define install directory.

After that has been done build the `INSTALL` project in TrinityCore solution generated by cmake, that way it'll put binaries in defined install directory.

**Comment by mgracia012020** [comment]
When you say "After that has been done build the INSTALL project in TrinityCore solution generated by cmake, that way it'll put binaries in defined install directory." Can you provide an example on what exactly you mean? I think that may be where I am not doing it correctly. I generated the SLN using CMAKE and use dynamic links as specified in the trinity guide. I then built the project in VS2019. After the build, I ran cmake install "c:\trinityserver\servers" ../  and no files were copied to the target dest. I also created the SLN with CMAKE then used cmake INSTALL "c:\trinityserver\servers" ../  from the build directory - reloaded the SLN in VS. Then built the project in VS. Still the files were not copied over. Any other tips you can provide? Thank you so much for the assistance.

**Comment by mdX7** [comment]
![grafik](https://user-images.githubusercontent.com/12143653/113515297-e6269d00-9573-11eb-936b-4592940e9a0b.png)

**Comment by mgracia012020** [comment]
Awesome!. That worked (built and compile with dynamics scripts for all source code). The files were installed after the build was completed. All the DLLs/exes and scripts directory were installed as expected. I started the worldserver and made and save a quick change (a say line) in one of the scripts under the source directory. The worldserver is not loading the change. Any suggestions on how to troubleshoot this?

**Comment by mgracia012020** [comment]
Also confirmed the dynamic link setup is turned on via worldserver.conf.

**Comment by mgracia012020** [comment]
I figured it out. The worldserver.conf must also have the source directory defined.

I turned on debug logging and saw the worldserver was not finding the source directory. I set the source dir to SourceDirectory  = "C:\Shadowlands-Master" and restarted the worldserver. Now I see the everything working as expected.

Thank you so much for helping with this. Have a great weekend.
