### ISSUE TITLE
[Quest] Stunning View

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26344]
**How it now**
If you click on Eye of Dominion the menu does not open (to control Lithe Stalker)

**How it should be**
There should be a clickable menu 
![изображение](https://user-images.githubusercontent.com/77268574/113574312-7c1a0080-9624-11eb-96f9-9de85156298e.png)

in previous versions of the repository everything worked 
**an interesting point**: the menu was there, but then it disappeared 

```sql
gossip_menu
+--------+--------+---------------+
| MenuID | TextID | VerifiedBuild |
+--------+--------+---------------+
|  10111 |  13906 |             0 |
+--------+--------+---------------+


gossip_menu_option
+--------+----------+------------+-----------------------------------------------------+-----------------------+------------+---------------+--------------+-------------+----------+----------+---------+--------------------+---------------+
| MenuID | OptionID | OptionIcon | OptionText                                          | OptionBroadcastTextID | OptionType | OptionNpcFlag | ActionMenuID | ActionPoiID | BoxCoded | BoxMoney | BoxText | BoxBroadcastTextID | VerifiedBuild |
+--------+----------+------------+-----------------------------------------------------+-----------------------+------------+---------------+--------------+-------------+----------+----------+---------+--------------------+---------------+
|  10111 |        0 |          0 | <Seize control of a Lithe Stalker through the eye.> |                 32270 |          1 |             1 |            0 |           0 |        0 |        0 |         |                  0 |             0 |
+--------+----------+------------+-----------------------------------------------------+-----------------------+------------+---------------+--------------+-------------+----------+----------+---------+--------------------+---------------+
```

[https://www.wowhead.com/quest=13160/stunning-view](https://www.wowhead.com/quest=13160/stunning-view)

3.3.5
rev. 80f30d5

**Comment by Aokromes** [comment]
last time taken (and completed) on my server on 817bd92a2ae4.

**Comment by offl** [comment]
```txt
SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment                                                                                   
-----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  ------------------------------------------------------------------------------------------
                     15        10111            0         0          0                        47                0            13145               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken The Vile Hold (13145)       
                     15        10111            0         0          1                        47                0            13146               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Generosity Abounds (13146)  
                     15        10111            0         0          2                        47                0            13147               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Matchmaker (13147)          
                     15        10111            0         0          3                        47                0            13147               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Stunning View (13160)       
```
Did you accepted any of those quests?

**Comment by gygyti** [comment]
> 
> 
> ```
> SourceTypeOrReferenceId  SourceGroup  SourceEntry  SourceId  ElseGroup  ConditionTypeOrReference  ConditionTarget  ConditionValue1  ConditionValue2  ConditionValue3  NegativeCondition  ErrorType  ErrorTextId  ScriptName  Comment                                                                                   
> -----------------------  -----------  -----------  --------  ---------  ------------------------  ---------------  ---------------  ---------------  ---------------  -----------------  ---------  -----------  ----------  ------------------------------------------------------------------------------------------
>                      15        10111            0         0          0                        47                0            13145               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken The Vile Hold (13145)       
>                      15        10111            0         0          1                        47                0            13146               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Generosity Abounds (13146)  
>                      15        10111            0         0          2                        47                0            13147               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Matchmaker (13147)          
>                      15        10111            0         0          3                        47                0            13147               10                0                  0          0            0              Eye of Dominion - Show gossip option only if player has taken Stunning View (13160)       
> ```
> 
> Did you accepted any of those quests?

oooh, got it. I need to have these tasks in order to do the right thing. thanks
