### ISSUE TITLE
[Quest] Threat From Above

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26355]
**How it now**
When you start hitting the dragon, you leave him about 30-40% health, the NPCs (Cultist Bombardier 3x)  that sit on the dragon get off it and disappear 
sometimes they stay to fight
sometimes they run away and disappear 

**How it should be**
Cultist Bombardier shouldn't run away or disappear 

I think it has something to do with the starting point of the dragon's flight. The farther the dragon flies away from the starting point, the greater the chance to reproduce the bug 

[https://www.wowhead.com/quest=13809/threat-from-above](https://www.wowhead.com/quest=13809/threat-from-above)

3.3.5
rev. 80f30d5

**Comment by offl** [comment]
> When you start hitting the dragon, you leave him about 30-40% health, the NPCs (Cultist Bombardier 3x) that sit on the dragon get off it

This is correct behavior shown in sniffs

> and disappear

This is not correct behavior

> I think it has something to do with the starting point of the dragon's flight. The farther the dragon flies away from the starting point, the greater the chance to reproduce the bug

They also have despawn event in their AI, but it's called only if they are out of combat
Didn't tried yet to test

**Comment by Edder** [comment]
I looked into this quest and found two issues.

First issue is, only one of the three "Eject Passenger" spells are scripted (the "Eject Passenger 2" one is),
That's why only the second passenger between 0-50 % jumps off, the other two eject if Chillmaw dies.

The Second issue is, the three npcs that Chillmaw drops have the home position of Chillmaw.
I think that is the reason why they sometimes (if too far away from home) run away.

To fix this, I would suggest, in case of Chillmaw, spell scripting all three "Eject Passenger" spells, let the passenger exit the vehicle (Chillmaw) and set their home position to their current position (their dropped position).
By doing that, the npcs correctly stay and fight without running away.

Spellscript on zone_icecrown.cpp:
```
/*######
## Threat From Above (group daily) - Id: 13809
######*/

enum ThreatFromAbove
{
    // NPC
    NPC_CHILLMAW = 33687,
    NPC_CULTIST_BOMBARDIER = 33695,

    // Spells
    SPELL_EJECT_PASSENGER_1 = 60603,
    SPELL_EJECT_PASSENGER_2 = 62539,
    SPELL_EJECT_PASSENGER_3 = 52205,
};

// 60603 - Eject Passenger 1
// 62539 - Eject Passenger 2
// 52205 - Eject Passenger 3
class spell_eject_passenger_chillmaw : public SpellScriptLoader
{
public:
    spell_eject_passenger_chillmaw() : SpellScriptLoader("spell_eject_passenger_chillmaw") { }

    class spell_eject_passenger_chillmaw_SpellScript : public SpellScript
    {
        PrepareSpellScript(spell_eject_passenger_chillmaw_SpellScript);

        void HandleScript(SpellEffIndex /*effIndex*/)
        {
            if (GetHitUnit()->GetEntry() != NPC_CHILLMAW)
                return;

            uint8 seatId;

            switch (GetSpellInfo()->Id)
            {
                case SPELL_EJECT_PASSENGER_1:
                    seatId = 0;
                    break;
                case SPELL_EJECT_PASSENGER_2:
                    seatId = 1;
                    break;
                case SPELL_EJECT_PASSENGER_3:
                    seatId = 2;
                    break;
            }

            if (Vehicle* vehicle = GetHitUnit()->GetVehicleKit())
            {
                if (Unit* passenger = vehicle->GetPassenger(seatId))
                {
                    if (passenger->IsCreature() && passenger->GetEntry() == NPC_CULTIST_BOMBARDIER)
                    {
                        Creature* cultistBombardier = passenger->ToCreature();
                        Creature* chillmaw = GetHitUnit()->ToCreature();
                        passenger->ExitVehicle();
                        cultistBombardier->SetHomePosition(chillmaw->GetHomePosition());
                    }
                }     
            }
        }

        void Register() override
        {
            OnEffectHitTarget += SpellEffectFn(spell_eject_passenger_chillmaw_SpellScript::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
        }
    };

    SpellScript* GetSpellScript() const override
    {
        return new spell_eject_passenger_chillmaw_SpellScript();
    }
};
```

```
insert into spell_script_names (spell_id, ScriptName) values (60603, 'spell_eject_passenger_chillmaw');
insert into spell_script_names (spell_id, ScriptName) values (62539, 'spell_eject_passenger_chillmaw');
insert into spell_script_names (spell_id, ScriptName) values (52205, 'spell_eject_passenger_chillmaw');
```

Or we can do a more generel approach and set the home positon of every ejected passenger (if creature) to the ejected position.
But that could break other things.

Tested with TrinityCore rev. 1c0029321a84

**Comment by illfated** [comment]
Looks useful, just remember that the SQL part should be written like this to follow TC SQL codestyle:
```sql
DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_eject_passenger_chillmaw';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(52205, 'spell_eject_passenger_chillmaw'),
(60603, 'spell_eject_passenger_chillmaw'),
(62539, 'spell_eject_passenger_chillmaw');
```
Please also note the following `spell_script_names` entries, in case there are any inconsistencies:
```sql
SELECT * FROM `spell_script_names` WHERE `spell_id` IN (52205, 60603, 62539);
```
```
spell_id  ScriptName
--------  -------------------------------
  60603   spell_eject_passenger_wild_wyrm
  62539   spell_gen_eject_passenger
```
```sql
SELECT * FROM `spell_script_names` WHERE `ScriptName` IN ('spell_eject_passenger_wild_wyrm', 'spell_gen_eject_passenger');
```
```
spell_id  ScriptName
--------  -------------------------------
  60603   spell_eject_passenger_wild_wyrm
  62539   spell_gen_eject_passenger
  64614   spell_gen_eject_passenger
  64629   spell_gen_eject_passenger
  64630   spell_gen_eject_passenger
  64631   spell_gen_eject_passenger
  64632   spell_gen_eject_passenger
  64633   spell_gen_eject_passenger
  64634   spell_gen_eject_passenger
  64635   spell_gen_eject_passenger
  64636   spell_gen_eject_passenger
  67393   spell_gen_eject_passenger
```

**Comment by offl** [comment]
Those spells are not used only by Chillmaw
And generic bug with home position should be solved in core and not in specific spell script

**Comment by Edder** [comment]
> Looks useful, just remember that the SQL part should be written like this to follow TC SQL codestyle:
>
Yes, you're right. 
I am sorry, it's my first contribution.

> Those spells are not used only by Chillmaw
> And generic bug with home position should be solved in core and not in specific spell script
>
I agree, I would like to fix it in Unit.cpp ExitVehicle() and set the home position to current position if its a creature.

The problem with the three spells Chillmaw casting in SmartAI is, only one of them (Eject Passenger 2) has an EffectValue, thats probably the reason why its the only one working.
https://www.wowhead.com/spell=60603/eject-passenger-1
https://www.wowhead.com/spell=62539/eject-passenger-2
https://www.wowhead.com/spell=52205/eject-passenger-3
The EffectValue() - 1 used to determine the seatId where there passenger exits from.
Without the EffectValue() there is only the spell name, which tells us from which seat to eject from.

Are those three eject spells casted by Chillmaw on live realms?

**Comment by offl** [comment]
> Are those three eject spells casted by Chillmaw on live realms?

Yeah, they all are shown in sniffs

60603 uses `spell_eject_passenger_wild_wyrm` and simply removes https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=56673 but it's wrong since it's generic spell and should just eject passenger. The question is if it really should eject passenger 1 and always or not
52205 uses no spell script
I'll try to check where they are used and what they do

**Comment by offl** [comment]
Chillmaw:
60603 ejects passenger 1
52205 ejects passenger 3

60603 also used by Ulduar vehicles but it's hard enough to check which passenger it ejects, I'm not really familiar with vehicle stuff
Also I'm not sure why those spells has no EffectValue but looks like their names speaks for itself

**Comment by Edder** [comment]
Strange thing is, that there are actually spells with corresponding EffectValues:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=64629 Eject Passenger 1
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=64630 Eject Passenger 2
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=64631 Eject Passenger 3
The list goes on to eight.
They have sounds though and are used by Ulduar Snow Mound.

> but looks like their names speaks for itself
>
Yep, and maybe they are scripted on live realms too or it is done by spellname.

**Comment by offl** [comment]
Then the best approach for this issue is remove spell_eject_passenger_wild_wyrm and add generic script to 60603 to eject only passenger 1
Same with 52205 but it will eject passenger 3

Probably both spells has scripted side-effect but I see nothing like this right now

**Comment by Edder** [comment]
You mean handle spell 60603 and 52205 in the generic script too but set the exit seat manually?
Like this or two own generic scripts for 60603 and 52205?

```C++
enum NotSoGenericEjectPassengerSpells
{
    SPELL_EJECT_PASSENGER_1 = 60603,
    SPELL_EJECT_PASSENGER_3 = 52205
};

class spell_gen_eject_passenger : public SpellScript
{
    PrepareSpellScript(spell_gen_eject_passenger);

    bool Validate(SpellInfo const* spellInfo) override
    {
        if (spellInfo->Effects[EFFECT_0].CalcValue() < 1)
            return false;
        return true;
    }

    void EjectPassenger(SpellEffIndex /*effIndex*/)
    {
        uint8 seatId;

        switch (GetSpellInfo()->Id)
        {
            // these two spells are special and have no EffectValue, therefore we need to set the seatId manually
            case SPELL_EJECT_PASSENGER_1:
                seatId = 0;
                break;
            case SPELL_EJECT_PASSENGER_3:
                seatId = 2;
                break;
            default:
                seatId = GetEffectValue() - 1;
        }

        if (Vehicle* vehicle = GetHitUnit()->GetVehicle())
        {
            if (Unit* passenger = vehicle->GetPassenger(seatId))
                passenger->ExitVehicle();
        }
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_gen_eject_passenger::EjectPassenger, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};
```

**Comment by offl** [comment]
What about this part?
```cpp
    bool Validate(SpellInfo const* spellInfo) override
    {
        if (spellInfo->Effects[EFFECT_0].CalcValue() < 1)
            return false;
        return true;
    }
```

**Comment by Edder** [comment]
Okay, I think I got it:
https://pastebin.com/BegMjjxY

SQL:
```sql
-- delete non generic spell script for wild wyrm
DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_eject_passenger_wild_wyrm';

DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_gen_eject_passenger_1';
-- add "special" generic for "Eject Passenger 1", "spell_eject_passenger_wild_wyrm" used this too
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(60603, 'spell_gen_eject_passenger_1');

DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_gen_eject_passenger_3';
-- add "special" generic for "Eject Passenger 3"
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(52205, 'spell_gen_eject_passenger_3');
```

Tested with Chillmaw and Wild Wyrm.

For the problem with the home position, I have an idea for another solution.
The reason those dropped npcs run away is, they are too far away from their home position because Chillmaw moves on waypoints.
What if we give those three npcs the same waypoints as Chillmaw?
That way they'll have the same movement radius as Chillmaw.
Those waypoints have to be kinda inactive, they should be there home position if reached but not walked automatically.
Kinda like variable home positions (which ever is nearer).

**Comment by illfated** [comment]
Nice ideas, thanks for the suggestions. I don't know enough real coding to value or appraise them, though.

**Comment by offl** [comment]
> Okay, I think I got it:

Looks good, could you please open PR?

> For the problem with the home position, I have an idea for another solution.
The reason those dropped npcs run away is, they are too far away from their home position because Chillmaw moves on waypoints.
What if we give those three npcs the same waypoints as Chillmaw?
That way they'll have the same movement radius as Chillmaw.
Those waypoints have to be kinda inactive, they should be there home position if reached but not walked automatically.
Kinda like variable home positions (which ever is nearer).

Sounds hacky tbh

> Or we can do a more generel approach and set the home positon of every ejected passenger (if creature) to the ejected position.
But that could break other things.

Honestly can't understand why it wasn't done before

**Comment by Edder** [comment]
> Looks good, could you please open PR?
>
Will do, have to look how it works with git and pull requests.

**Comment by Edder** [comment]
> You mean in core? Try to ask in IRC
> 
Yeah, I mean in core.
But you are probably right.
There're so few cases and this solution could be overkill.
Changing the home position of a dropped creature to current position can't be false.
I mean if the creature jumps back on the vehicle and the vehicle moves again, the home position will be obsolete again and resetting it should be sufficient.

I would suggest making the ExitVehicle function in Unit.h virtual and overwriting it in Creature.h/cpp.
Calling there Unit::ExitVehicle and SetHomePosition(GetPosition()).

**Comment by jackpoz** [comment]
@Edder feel free to open a PR with the suggested changes so we can discuss them in detail there. it makes sense to me to call SetHomePosition() in the cases you explained.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/3e407c7d1c79cc94bf932880ee0eb68058d139fd
