### ISSUE TITLE
DB/Profession: Updated Stormwind & Orgrimmar profession trainers

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#26364]
**Description:**

Update Stormwind & Orgrimmar profession trainers to latest retail data

**Branch(es):**

master

**TC rev. hash/commit:** 

f759809d9d4364bc1d988e4390d3d5a33d5469e9

**Suggested Fix:**
https://gist.github.com/mdX7/912c49894ec45beee0a77ecec339db8a

**Comment by funjoker** [comment]
Did you use RecalcDiscount option ?
