### ISSUE TITLE
Worldserver crash on login

### ISSUE THREAD

**Issue by JyriaLycion** [TrinityCore/TrinityCore#26393]
[2cea7d000c22_worldserver.exe_[13-4_19-5-7].txt](https://github.com/TrinityCore/TrinityCore/files/6305472/2cea7d000c22_worldserver.exe_.13-4_19-5-7.txt)

**Description:**

Worldserver.exe crashes upon logging in into character. Yesterday everything worked fine, but today it suddenly stopped working. No idea what could of happned to be the cause of this. Have not changed anything for few days, just suddenly started crashing today. I posted the server crashlog

 as well. Pretty new to all this

**Expected behaviour:**

No crash on login

**Steps to reproduce the problem:**

1. Open both Auth & Worldserver
2. Login into the server
3. Create or use a existing character
4. Login in into the world

**Branch(es):**

WOTLK 3.3.5 branch

**TC rev. hash/commit:** 

Revision: TrinityCore rev. 2cea7d000c22

**Operating system:** 

Windows 10

**Comment by Aokromes** [comment]
cannot reproduce on 1539bed3db86

**Comment by JyriaLycion** [comment]
Will update to the latest revision and report back/close issue if it stops happening today

**Comment by illfated** [comment]
<details>
<summary>First 60 lines from the crash log text file ◄</summary>

```
Revision: TrinityCore rev. 2cea7d000c22 2021-04-05 19:44:54 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Date 13:4:2021. Time 19:5 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Number Of Processors: 16
Physical Memory: 16697024 KB (Available: 10907612 KB)
Commit Charge Limit: 25085632 KB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 19042)

//=====================================================
Exception code: C0000420 An assertion failure has occurred.

Assertion message: 
D:\WoW server\TrinityCore\src\server\shared\Packets\ByteBuffer.cpp:111 in ByteBuffer::append ASSERTION FAILED:
  size() < 10000000


Fault address:  00007FF7A9074967 01:0000000000BE3967 D:\WoW server\Build\bin\RelWithDebInfo\worldserver.exe

Registers:
RAX:0000009C490FE020
RBX:000002623BA5C610
RCX:0000009C490FE10C
RDX:0000000000000000
RSI:0000009C490FEA30
RDI:0000009C490FE9D0
R8: 0000000000000020
R9: 00007FF7A84DB0B1
R10:00000262064A0000
R11:000002625B3FE040
R12:000002624AAAB970
R13:0000000000000004
R14:0000000000000000
R15:0000000100000000
CS:RIP:0033:00007FFD55AED759
SS:RSP:002B:00000000490FE7C0  RBP:490FE931
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000206

Call stack:
Address   Frame     Function      SourceFile
00007FFD55AED759  0000009C490FE890  RaiseException+69
00007FF7A90CB549  0000009C490FE980  Trinity::Assert+129  D:\WoW server\TrinityCore\src\common\Debugging\Errors.cpp line 77
00007FF7A9074967  0000009C490FEA00  ByteBuffer::append+157  D:\WoW server\TrinityCore\src\server\shared\Packets\ByteBuffer.cpp line 111
00007FF7A8C780AE  0000009C490FEA80  ReputationMgr::SendInitialReputations+1AE  D:\WoW server\TrinityCore\src\server\game\Reputation\ReputationMgr.cpp line 247
00007FF7A8AFA03D  0000009C490FEB80  Player::SendInitialPacketsBeforeAddToMap+12D  D:\WoW server\TrinityCore\src\server\game\Entities\Player\Player.cpp line 22700
00007FF7A9025B7F  0000009C490FEFC0  WorldSession::HandlePlayerLogin+4DF  D:\WoW server\TrinityCore\src\server\game\Handlers\CharacterHandler.cpp line 810
00007FF7A909756E  0000009C490FEFF0  SQLQueryHolderCallback::InvokeIfReady+4E  D:\WoW server\TrinityCore\src\server\database\Database\QueryHolder.cpp line 93
00007FF7A8C40F7E  0000009C490FF070  AsyncCallbackProcessor<SQLQueryHolderCallback>::ProcessReadyCallbacks+5E  D:\WoW server\TrinityCore\src\common\Utilities\AsyncCallbackProcessor.h line 48
00007FF7A8C4464F  0000009C490FF240  WorldSession::Update+ABF  D:\WoW server\TrinityCore\src\server\game\Server\WorldSession.cpp line 438
00007FF7A89E29C1  0000009C490FF2B0  World::UpdateSessions+101  D:\WoW server\TrinityCore\src\server\game\World\World.cpp line 3110
00007FF7A89E1AF7  0000009C490FF600  World::Update+5B7  D:\WoW server\TrinityCore\src\server\game\World\World.cpp line 2416
00007FF7A84F6296  0000009C490FF660  WorldUpdateLoop+F6  D:\WoW server\TrinityCore\src\server\worldserver\Main.cpp line 444
00007FF7A85044DE  0000009C490FFD90  main+22AE  D:\WoW server\TrinityCore\src\server\worldserver\Main.cpp line 345
00007FF7A9203BFC  0000009C490FFDD0  __scrt_common_main_seh+10C  d:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FFD565A7034  0000009C490FFE00  BaseThreadInitThunk+14
00007FFD58322651  0000009C490FFE80  RtlUserThreadStart+21
```

</details>

Code surrounding line 111 in `ByteBuffer.cpp`:
https://github.com/TrinityCore/TrinityCore/blob/2cea7d000c2205ed06ca3263e61dee51b11a5b0b/src/server/shared/Packets/ByteBuffer.cpp#L107-L130

Seems difficult to tell how to reproduce or replicate the crash, since I have not had issues worth mentioning with my 3.3.5 source since 2015.

**Comment by JyriaLycion** [comment]
It started happening completeley out of nowhere. Yesterday all fine, today crashes. Will update to latest rev and see if its still presists. Personally didnt touch any code so far so find it kinda odd that it started happening

**Comment by illfated** [comment]
Yes, this is quite weird, so this might be a local issue only. Maybe something happened to your local character data in the DB or game client, who knows. The only thing I can derive from the crash assert message, is that the server expected a ByteBuffer content size of at least 10,000,000 — which it did not find — so something must have been saved incorrectly.

**Comment by JyriaLycion** [comment]
Recompiled to the latest version and seems like the same issue presists, will try and revert to a yesterday backup of the database see what happens.

**Comment by JyriaLycion** [comment]
So done some combinations of reverting the databases/dbc files. Seems like it was an issue with DBC files server sided(even though i have not touched these for **3 days** revering it to **yesterday's** backup works). Will close the issue as of now since there is not enough info to pinpoint the issue. Most likely an issue with saving incorrectly indeed.
