### ISSUE TITLE
{Master} Getting stuck in the realm screen

### ISSUE THREAD

**Issue by Alysrazor** [TrinityCore/TrinityCore#26427]
**Description:**

I get stucked in the realm screen, and it doesn't let me access the realm.

**Expected behaviour:**

Be able to access the realm and character list.

**Steps to reproduce the problem:**

1. Step 1 Create an account
2. Step 2 Try to login

**Branch(es):**
master

**TC rev. hash/commit:** 

TrinityCore rev. cdd5bf03ee1b 2021-04-17 02:52:12 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

**Operating system:** 

Win 64

**Comment by chipzz** [comment]
This sounds like user error instead of a bug. Please use the forum for support and the issue tracker for bugs.

**Comment by offl** [comment]
This commit https://github.com/TrinityCore/TrinityCore/commit/cdd5bf03ee1b9018a9e8cbdd5afd32213a8cf724 doesn't belong to TC master branch

**Comment by Alysrazor** [comment]
Its a merge to my forked TC repository

**Comment by Aokromes** [comment]
for sure you need to update launcher.

**Comment by Alysrazor** [comment]
My Client is 9.0.5.38134
