### ISSUE TITLE
Core/Spell - Spell Crash After Update (9.0.5)

### ISSUE THREAD

**Issue by Solarrider737** [TrinityCore/TrinityCore#26451]
**Description:**

After update to actual version of core some spells started to crash the core. 

**Expected behaviour:**

Spell should not crash the server :) 

**Steps to reproduce the problem:**

1. Step 1 - Example: create a shaman of any race or facrion ( i tried shaman troll)  
2. Step 2 - Try to use 1st spell ( Chain Lightning/188440)  
3. Step 3 - Server Crash.

**Branch(es):**

master

**TC rev. hash/commit:** 

81eac82

**Operating system:** 

Windows 10

[unknown_worldserver.exe_[20-4_2-8-59].txt](https://github.com/TrinityCore/TrinityCore/files/6339575/unknown_worldserver.exe_.20-4_2-8-59.txt)

**Comment by Shauren** [comment]
You are not on 81eac826562f8e75de1842c59c8d35cf050b0f21.

That crash was fixed already in 8eb3c61f1aea5610cf68fb622f41850d2b934c51
