### ISSUE TITLE
Core/Spell - Not working spells 9.0.2

### ISSUE THREAD

**Issue by Svipersnake** [TrinityCore/TrinityCore#26450]
Description:
~110909 (Alter Time) - It doesn't work.~ 28c075765bdf33a4444a0e13253da7e9f9e0f447
155166 (Breathe of Sindragosa) - Does nothing when used.
259391 (Shackrams) - Does nothing when used.
260243 (quick fire) - Make a visual without damage.
316239 (Rune Attack) - Does nothing when used.

Expect Behaviour:
~110909 (Alter Time) - Alters the fabric of time, returning you to your current location and health when cast a second time, or after 10 seconds.  Effect negated by long distance or death.~ 28c075765bdf33a4444a0e13253da7e9f9e0f447
155166 (Breathe of Sindragosa) - Frost damage every 1 sec to enemies in a cone in front.
259391 (Shackrams) - Throw a pair of chakrams at your target, slicing all enemies in the chakrams' path for [ 40% of Attack Power ] Physical damage. The chakrams will return to you, damaging enemies again.
Your primary target takes 100% increased damage.
260243 (quick fire) - Deals damage to the area.
316239 (Rune Attack) - Make a daamge from the death knight. Need one more death knight rune to use.

Steps to reproduce the problem:

Create a mage, death knight and hunter class character.
Give a character 60 lvl.
Try using any of the spells listed.

TC rev. hash/commit:

81eac82

Operating system:

Windows 10 x64

**Comment by Aokromes** [comment]
update your core before reporting bugs.

**Comment by Aokromes** [comment]
make one ticket for each bugged spell, search before make one ticket.
