### ISSUE TITLE
Stock "Logging in to server game" Trinitycore WoW 9.0.5 38134

### ISSUE THREAD

**Issue by WoWCreador** [TrinityCore/TrinityCore#26455]
Hello. I have this problem that when entering select the realm it stays in "Logging in to game server". I'm working in localhost Windows 10.

I am using a fresh **TrinityCore rev. 854a55daabf5+ 2021-04-18**, **WoW 9.0.5 38134** and **9.0.5 Custom Server Connection Launcher**

Also already configure config file to **SET portal "127.0.0.1"**

Any idea what it could be? Thank you very much in advance 👍 

**Branch:** Master
**TC rev. hash/commit:** 854a55daabf5
**Operating system:** Windows 10
**Server logs:**
[DBErrors.log](https://github.com/TrinityCore/TrinityCore/files/6352544/DBErrors.log)
[Server.log](https://github.com/TrinityCore/TrinityCore/files/6352546/Server.log)
[Bnet.log](https://github.com/TrinityCore/TrinityCore/files/6352547/Bnet.log)

![logging in to game server trinitycore 9 0 5](https://user-images.githubusercontent.com/66101227/115587283-82061780-a29b-11eb-9513-93ac65a1cbe9.jpg)

**Comment by MaxtorCoder** [comment]
Follow issue template please.

**Comment by WoWCreador** [comment]
> Follow issue template please.

Sorry

**Comment by Faq** [comment]
Any server logs? + update to latest.

**Comment by WoWCreador** [comment]
[DBErrors.log](https://github.com/TrinityCore/TrinityCore/files/6352544/DBErrors.log)
[Server.log](https://github.com/TrinityCore/TrinityCore/files/6352546/Server.log)
[Bnet.log](https://github.com/TrinityCore/TrinityCore/files/6352547/Bnet.log)
The updates were applied automatically

**Comment by illfated** [comment]
Looks like your configuration is different from the source, making it produce more errors than the standard TC source. Examples:
```
Compilado GRATIS para WoWCreador.com
```
```
DBUpdater: Given update include directory "./Actualizaciones/sql/custom/auth" does not exist, skipped!
DBUpdater: Given update include directory "./Actualizaciones/sql/old/6.x/auth" does not exist, skipped!
DBUpdater: Given update include directory "./Actualizaciones/sql/old/7/auth" does not exist, skipped!
DBUpdater: Given update include directory "./Actualizaciones/sql/old/8.x/auth" does not exist, skipped!
```
```
Attempted to load ./dbc/enUS/Achievement.db2 which has locales esES as enUS. Check if you placed your localized db2 files in correct directory.
```
71 lines in total, from the one directly above to the one directly below:
```
Attempted to load ./dbc/enUS/WMOAreaTable.db2 which has locales esES as enUS. Check if you placed your localized db2 files in correct directory.
```
Also, all your SQL updates are loaded both by Bnetserver and Worldserver, which seems incorrect (only Worldserver should load SQL updates).
Furthermore, all of the SQL updates have got log entries like the one below:
```
>> The file '2018_12_09_01_auth.sql' was applied to the database, but is missing in your update directory now!
```
Since I am not using the master branch and its targeted game client (9.x), I can't say for certain what the logs should look like. It just looks like your setup is too different from what the supposed setup should be when compiling from a correctly cloned source. I also suspect some manual incorrect changes in the .conf files, but I don't know exactly what is wrong.

**Comment by Shauren** [comment]
That screenshot he posted? This is the classic address/port configuration issue that you can fuck up even on 3.3.5 branch

**Comment by WoWCreador** [comment]
> Looks like your configuration is different from the source, making it produce more errors than the standard TC source. Examples:
> 
> ```
> Compilado GRATIS para WoWCreador.com
> ```
> 
> ```
> DBUpdater: Given update include directory "./Actualizaciones/sql/custom/auth" does not exist, skipped!
> DBUpdater: Given update include directory "./Actualizaciones/sql/old/6.x/auth" does not exist, skipped!
> DBUpdater: Given update include directory "./Actualizaciones/sql/old/7/auth" does not exist, skipped!
> DBUpdater: Given update include directory "./Actualizaciones/sql/old/8.x/auth" does not exist, skipped!
> ```
> 
> ```
> Attempted to load ./dbc/enUS/Achievement.db2 which has locales esES as enUS. Check if you placed your localized db2 files in correct directory.
> ```
> 
> 71 lines in total, from the one directly above to the one directly below:
> 
> ```
> Attempted to load ./dbc/enUS/WMOAreaTable.db2 which has locales esES as enUS. Check if you placed your localized db2 files in correct directory.
> ```
> 
> Also, all your SQL updates are loaded both by Bnetserver and Worldserver, which seems incorrect (only Worldserver should load SQL updates).
> Furthermore, all of the SQL updates have got log entries like the one below:
> 
> ```
> >> The file '2018_12_09_01_auth.sql' was applied to the database, but is missing in your update directory now!
> ```
> 
> Since I am not using the master branch and its targeted game client (9.x), I can't say for certain what the logs should look like. It just looks like your setup is too different from what the supposed setup should be when compiling from a correctly cloned source. I also suspect some manual incorrect changes in the .conf files, but I don't know exactly what is wrong.
> 
> edit: To me, it looks like there is an attempt to localize some of the source folder names to Spanish, which does not seem to work with the TC source, making it too difficult for the DB updater to handle the SQL updates correctly. I really think you should try to compile the source using Visual Studio 2019 instead of "WoWCreador".

My friend, thank you very much for your elaborate answer, I appreciate it. The only modification I make to the core is that I add a credit to whoever compiled in Banner.cpp, I have been doing that for years and I have never had a problem, you can see my projects here: [Shadowlands Repack TrinityCore en Español](https://wowcreador.com/threads/shadowlands-repack-trinitycore-en-espanol-actualizado-cada-mes.978/) [Repack TrinityCore 3.3.5a 12340 en Español](https://wowcreador.com/threads/repack-trinitycore-3-3-5a-12340-en-espanol-actualizado-cada-mes.363/)

Anyway, I compiled a new core without modifying anything, reinstalled the game, extracted new maps in the enUS version and I still have the same problem. Could it be an Arctium Laucher or trinitycore problem that doesn't support that version yet?

![trinitycore 9 0 5](https://user-images.githubusercontent.com/66101227/115723467-01ecba00-a34e-11eb-95a9-ef28b251179c.PNG)



> That screenshot he posted? This is the classic address/port configuration issue that you can fuck up even on 3.3.5 branch
I am testing on localhost, I think I don't need to do anything with ports. What are you talking about, can you be more specific please? Sorry my ignorance.

**Comment by illfated** [comment]
Sorry for the late reply, I have been rather tired lately. Also sorry for not having any good suggestions for what to look for, except that it may still be worth checking the IP address port values, both for bnetserver and worldserver, in case there should be any changes there.

I do recommend asking either in the TC forum pages, the IRC channel or via Discord, if anyone using the master branch can provide you with the standard working values used in this scenario. Please be aware that "repacks" are not supported, in case that question should appear.

**Comment by rem999** [comment]
You are right, I also think that the connection_patcher needs to be returned!
