### ISSUE TITLE
Utf-8 so bad after last change on *unix OS

### ISSUE THREAD

**Issue by sernels** [TrinityCore/TrinityCore#26463]
**Description:**
Compile server on ubuntu 20.04 
Start server
**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

go to game create russ and more 
and see console Command: reload conf [Player: ѐ°ґ (GUID Full: 0x0000000000000025 Type: Player Low: 37) (Account: 1) X: -6240.319824 Y: 331.032990 Z: 382.757996 Map: 0 (Eastern Kingdoms) Area: 132 (Coldridge Valley) Zone: Dun Morogh Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]

[Player: ѐ°ґ

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/8db2ef9cdd415ed0d4897ec4d664ddba358cbaa1

**Operating system:** 

Ubuntu 20.04

**Comment by sernels** [comment]
sum @r4d1sh

**Comment by jackpoz** [comment]
>2021-04-24_12:29:57 INFO  [commands.gm] Command: server info [Player: Teståöä (GUID Full: 0x0000000000000072 Type: Player Low: 114) (Account: 1) X: -3961.639893 Y: -13931.200195 Z: 100.613525 Map: 530 (Outland) Area: 3526 (Ammen Vale) Zone: Azuremyst Isle Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]

Works for me with player name Teståöä. Please include more detailed how to reproduce steps. "create russ and more" is too generic.

**Comment by jackpoz** [comment]
@sernels what happened to the issue ? did you fix it ? was it some OS/console setting ?

**Comment by r4d1sh** [comment]
So you understand what the problem was?
