### ISSUE TITLE
Core/Sounds - missing victory near sound at Arathi Basin

### ISSUE THREAD

**Issue by schell244** [TrinityCore/TrinityCore#26474]
**Description:**
Currently, both horde and alliance have the same sound when victroy is near at arathi basin.
https://github.com/TrinityCore/TrinityCore/blob/3e407c7d1c79cc94bf932880ee0eb68058d139fd/src/server/game/Battlegrounds/Zones/BattlegroundAB.h#L200

**Expected behaviour:**
There should be two sounds:
https://classic.wowhead.com/sound=8457/pvpwarninghordelong
https://classic.wowhead.com/sound=8456/pvpwarningalliancelong

```
BG_AB_SOUND_NEAR_VICTORY_ALLIANCE   = 8456,
BG_AB_SOUND_NEAR_VICTORY_HORDE       = 8457
```

**Steps to reproduce the problem:**
1. enter arathi basin as horde player
2. capture ressources 1400
3. wrong sound is played

(Victroy near sound trigger at trinitycore is at 1400 ressources and victrory is at 1600 - in classic, victroy near sound trigger is at 1800 and victroy is at 2000. I think that is intened due to patch changes?)

**Branch(es):**
3.3.5
master (?)

**TC rev. hash/commit:** 
3e407c7

**Operating system:** 
Win 10

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2ac7499f66a80296486b7df6286ff503c8cdf3b9
