### ISSUE TITLE
Core/Vehicle: Passengers can't engage if to far away from home

### ISSUE THREAD

**Issue by Edder** [TrinityCore/TrinityCore#26481]
**Description:**

Some vehicles (Chillmaw 33687) have other creatures as passengers.
If you engage Chillmaw, the passenger will start attacking you too.
If you engage Chillmaw too far away from home, the passenger will not start attacking you.

**Expected behaviour:**

The passengers should (if hostile) attack the player, regardless of engaging position.
Proof (warning loud music) that passenger attack players on vehicles 
https://www.youtube.com/watch?v=RE9go8P6I98

**Steps to reproduce the problem:**

1. .go c 200851
2. wait for it to fly on his waypoints around the sharp rock
3. engage him at around 48/31

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5991dcb

**Operating system:** 

Win 10 x64

Will open a PR to fix this

**Comment by jackpoz** [comment]
fb88a1409ff60343edb0c539d406a961724fcc4e
