### ISSUE TITLE
DB/Quest: Cheese for Glowergold - missing question mark in CompletionText

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#26490]
**Description:**

The `quest_request_items`.`CompletionText` for the quest "Cheese for Glowergold" does not end the question with a question mark, only a period dot.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13103/cheese-for-glowergold (Alliance)
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13115/cheese-for-glowergold (Horde)

Progress (`CompletionText`): "Have you seen a servant with my wine and cheese platter. I am quite peckish!"

```sql
SELECT * FROM `quest_request_items` WHERE `ID` IN (13103, 13115);
```
```sql
  ID   EmoteOnComplete  EmoteOnIncomplete  CompletionText                                                                  VerifiedBuild
-----  ---------------  -----------------  ------------------------------------------------------------------------------  -------------
13103         0                 0          Have you seen a servant with my wine and cheese platter.   I am quite peckish!          12340
13115         0                 0          Have you seen a servant with my wine and cheese platter.  I am quite peckish!           12340
```

Cosmetic detail: Note that there is one redundant extra space (blank) between the 2 sentences in the 13103 (Alliance) quest text.

**Expected behaviour:**

https://wowpedia.fandom.com/wiki/Cheese_for_Glowergold_(Alliance)#Progress
https://wowpedia.fandom.com/wiki/Cheese_for_Glowergold_(Horde)#Progress

"Have you seen a servant with my wine and cheese platter? I am quite peckish!"

Note that the wowhead.com Progress text does not contain the question mark, but I think that is a miss on their part. Videos show that the question mark should be there, especially visible in Spanish videos, where the question sentence is preceded by the inverted question mark, **¿** in addition to the ending question mark. Also note that the Spanish wowhead.com page shows these question marks:
https://es.wowhead.com/quest=13103/queso-para-frunceoro
https://es.wowhead.com/quest=13115/queso-para-frunceoro
- ¿Has visto a un sirviente con mi bandeja de vino y queso? ¡Tengo un poco de hambre!

**Steps to reproduce the problem:**

1. Use a level 70-80 character with cooking skill 350 (or higher), start in Dalaran (Crystalsong Forest, Northrend).
2. `.quest add 13103` (Alliance) or `.quest add 13115` (Horde)
3. `.quest complete 13103` (Alliance) or `.quest complete 13115` (Horde)
4. Deliver the completed [Wine and Cheese Platter] to Ranid Glowergold at the Leatherworkers in the Magus Commerce Exchange.
5. Note that the first sentence, which is a question, does not end with a question mark (?).

**Suggested solution:**

```sql
-- Cheese for Glowergold
UPDATE `quest_request_items` SET `CompletionText`= "Have you seen a servant with my wine and cheese platter?  I am quite peckish!" WHERE `ID` IN (13103, 13115);
```

**Branch(es):**

3.3.5, probably both (I don't have a working master branch game client & server)

**TC rev. hash/commit:** 

TC> server debug
TrinityCore rev. 1c0029321a84 2021-04-20 17:42:16 +0300 (3.3.5 branch) (Win64, Release, Static)
```
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.20.0
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962076292 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21041
TC> _
```

**Operating system:** 

Windows 10 Home x64 Version 20H2 (OS Build 19042.928)

**Comment by offl** [comment]
330 (11159) is closer to 335 than 434
```txt
 15595 
 (13115, 0, UNKNOWN, 'Have you seen a servant with my wine and cheese platter?  I am quite peckish!'); -- 13115
 15354 
 (13115, UNKNOWN, 0, 'Have you seen a servant with my wine and cheese platter?  I am quite peckish!'); -- 13115
 11159
 (13103, 0, UNKNOWN, 'Have you seen a servant with my wine and cheese platter.   I am quite peckish!'), -- 13103
