### ISSUE TITLE
Crash in Pet::LoadPetFromDB

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#26492]
**Description:**

Crash: https://gist.github.com/gtestdev/42a3ecf158f904b77df3f415305cc78b
caused by ASSERT: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Pet/Pet.cpp#L327

**Steps to reproduce the problem:**

I don't know how to reproduce it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

b98c11fefd6093916ee7cafa424f8355bcaf6690

**Operating system:** 

Debian 10

**Comment by jackpoz** [comment]
>petStable = @0x7ffee97b8c00: {CurrentPet = std::optional<PetStable::PetInfo> = {[contained value] = {Name = "Phangorg", PetNumber = 89334, CreatureId = 1860,  UnslottedPets = std::vector of length 3, capacity 4 = {{Name = "Dagtik", PetNumber = 89140, CreatureId = 416, CreatedBySpellId = 688}, {Name = "Bryanda", PetNumber = 89328, CreatureId = 1863, CreatedBySpellId = 712}, {Name = "Wraazhum", PetNumber = 89341, CreatureId = 417, CreatedBySpellId = 691}}}

**Comment by Faq** [comment]
On clean TC or with some custom modifications?

**Comment by gtestdev** [comment]
Is there any possibility to replace the assert with a log to avoid the crash?

**Comment by Jildor** [comment]
well, I found a way to reproduce it:
get a warlock, summon a pet (by example imp)
mount on a vehicle that allow use spells (by example 34775) and switch to left or right passenger seat
cast any other summon pet (by example summon voidwalker)

**Comment by gtestdev** [comment]
any solution please?

**Comment by Jildor** [comment]
another way:
get a warlock, summon a pet (by example imp)
.die on warlock character
(now you are dead, so use /g to talk on guild chat and use commands)
.cast 6962 triggered
.revive
summon a different pet (by example voidwalker)
use a mount
dismount

**Comment by illfated** [comment]
@gtestdev : You could take a look at the most recent (Draft) Pull Request in https://github.com/TrinityCore/TrinityCore/pulls to see if it could be useful, or if it helps you test your pet handling issues. Note: no implied guarantee that it will solve the issue, but it is something you could look at to see that someone else is actually looking into your crashes.
