### ISSUE TITLE
Crash in Pet::SavePetToDB

### ISSUE THREAD

**Issue by gtestdev** [TrinityCore/TrinityCore#26491]
**Description:**

Crashlog: https://gist.github.com/gtestdev/1c9feb4a2ce488175d4759b2809285b0
caused by ASSERT: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Pet/Pet.cpp#L487

**Steps to reproduce the problem:**

I don't know how to reproduce it

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

b98c11fefd6093916ee7cafa424f8355bcaf6690

**Operating system:** 

Debian 10

**Comment by jackpoz** [comment]
any custom change from https://github.com/TrinityCore/TrinityCore/commit/b98c11fefd6093916ee7cafa424f8355bcaf6690 ?

**Comment by gtestdev** [comment]
transmogrify

**Comment by gtestdev** [comment]
Just in case it helps, ownerLowGUID = 280482 is a hunter

**Comment by Jildor** [comment]
well, I can reproduce this crash, not sure how to reproduce it with normal player account, but you can do:
- get a player with pet, by example warlock and summon pet
- do command .cast 6962
- do command .save

**Comment by gtestdev** [comment]
Is there any possibility to replace the assert with a log to avoid the crash?

**Comment by Jildor** [comment]
I found a way that can be reproduced without commands.
get a hunter with a pet
mount on a vehicle that allow use spells (by example 34775) and switch to left or right passenger seat
use call pet
use call stabled pet and keep the pet in the stable
dismount vehicle, pet will summon again, so I thing it's duplicated
wait for char save intervall or use any mount

**Comment by gtestdev** [comment]
any solution please?

**Comment by jackpoz** [comment]
> * get a player with pet, by example warlock and summon pet
> * do command .cast 6962
> * do command .save

in this case `owner->GetPetStable()->CurrentPet` is null but the assert expects it not to be null

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/blob/cd853118b6cc215676cd7a4661c0b91575e5650a/src/server/game/Entities/Pet/Pet.cpp#L330 sets CurrentPet to the one being loaded/summoned but then https://github.com/TrinityCore/TrinityCore/blob/cd853118b6cc215676cd7a4661c0b91575e5650a/src/server/game/Entities/Pet/Pet.cpp#L351 unloads/desummons the previous pet and if the current and previous are the same, then CurrentPet is set to null at this point

**Comment by jackpoz** [comment]
> * get a player with pet, by example warlock and summon pet
> * do command .cast 6962
> * do command .save

https://github.com/TrinityCore/TrinityCore/pull/26501 fixes this case, I have not tested yet the other cases.

**Comment by Jildor** [comment]
> I found a way that can be reproduced without commands.
> get a hunter with a pet
> mount on a vehicle that allow use spells (by example 34775) and switch to left or right passenger seat
> use call pet
> use call stabled pet and keep the pet in the stable
> dismount vehicle, pet will summon again, so I thing it's duplicated
> wait for char save intervall or use any mount

Just in case you want to reproduce in a simple way:

get a hunter with a tamed pet
.npc add temp 34775
mount in vehicle and switch to right or left seat
cast Call Pet hunter spell (.cast 883)
cast Call Stabled Pet (.cast 62757)
keep the pet in the stable
dismount vehicle
do .save

**Comment by jackpoz** [comment]
Player::ResummonPetTemporaryUnSummonedIfAny() resummons the pet even if it was stabled

**Comment by jackpoz** [comment]
@Jildor https://github.com/TrinityCore/TrinityCore/pull/26501 updated handling the 2nd case. Bring it on! 😄 💪 

> get a hunter with a tamed pet
> .npc add temp 34775
> mount in vehicle and switch to right or left seat
> cast Call Pet hunter spell (.cast 883)
> cast Call Stabled Pet (.cast 62757)
> keep the pet in the stable
> dismount vehicle
> do .save

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e203ecda88a327c4e93588f39cc4ffdcf99b30f7
