### ISSUE TITLE
Creatures unkillable

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#26507]
**Description:**

Creatures unkillable, HP always jumps back to 100% after each spell cast and spell effects don't seem to be working, nor do creatures take away your HP. 

**Expected behaviour:**

Creatures like Blackworg Worgs at Northshire Abbey should be killable as part of first quest and they should damage you when they attack but don't

**Steps to reproduce the problem:**

1. Create a lvl 1 mage or any character, choose Northshire Abbey as your starting point
2. Accept first quest
3. try to kill blackworg worgs
4. See https://vimeo.com/545127836

**Branch(es):**

Master

fc67c8132963

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** 

W10

**Comment by Faq** [comment]
Looks strange, no spell visual + doesn't looks like they aggro (no red, just yellow).

**Comment by Spoony36** [comment]
It wasn't in that vid but with gm off, the issue persists in any case

**Comment by MaxtorCoder** [comment]
Spells are proper fucked as well in the video xD

**Comment by ZaDarkSide** [comment]
I blame this commit https://github.com/TrinityCore/TrinityCore/commit/3a37a2e0d7ce79d55c301f4246f08f1fc5c9c6d7 for what is in that video.

**Comment by Spoony36** [comment]
Ok repulled core and compiled again (95ae56bb3b3d), must have been updated overnight and somewhat fixed in that i can now kill things but spell visuals still seem wonky :D
