### ISSUE TITLE
Crash in Transport::EnableMovement in ICC when talking with Saurfang on the ship

### ISSUE THREAD

**Issue by silviu20092** [TrinityCore/TrinityCore#26509]
**Description:**

https://gist.github.com/silviu20092/89704e004fa1b06b259e6a83736a0d22

Crash in Transport::EnableMovement when speaking with Saurfang on ICC ship. This issue seems to be extremely rare and seems to be related to this line: `if (!GetGOInfo()->moTransport.canBeStopped)` . How can `m_goInfo` ever go corrupt?
No special messages before crash.
There are some custom scripts present but nothing related (autobalance and just some custom spellscripts).
One thing that might be relevant is the fact that crossfaction groups are enabled so there can be both alliance and horde present in the instance.

**Steps to reproduce the problem:**

Speak with Saurfang on ICC ship.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

https://github.com/TrinityCore/TrinityCore/commit/347da56cbe84fc3ada86329c15631cc19b631ca0

**Operating system:** 

Debian 10

**Comment by Aokromes** [comment]
never seen myself with crossfaction enabled.

**Comment by silviu20092** [comment]
It's the first time that it happened in 4 months so I guess it's a very edge case.

**Comment by Aokromes** [comment]
no one else confirmed this crash after 2 years.
