### ISSUE TITLE
[Quest] Meeting a Great One

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26514]
**How it now**
when Roo approaches The Etymidian nothing happens. The quest does not end 

**How it should be**
Roo must visit The Etymidian 

[https://www.wowhead.com/quest=13956/meeting-a-great-one](https://www.wowhead.com/quest=13956/meeting-a-great-one)
3.3.5
rev. 80f30d5

**Comment by Aokromes** [comment]
update your core.

**Comment by gygyti** [comment]
has this been fixed?

**Comment by illfated** [comment]
I haven't seen any posted solutions for this, and I have had this issue on 3 different versions:
- rev. cd853118b6cc 2021-04-29 03:14:48 +0300 (3.3.5 branch) (Win64, Release, Static)
- rev. 1c0029321a84 2021-04-20 17:42:16 +0300 (3.3.5 branch) (Win64, Release, Static)
- rev. 2fcf455b34e1 2021-04-16 21:25:14 +0000 (3.3.5 branch) (Win64, Release, Static)

**Comment by illfated** [comment]
@gygyti : it works now, on current TC 3.3.5 core revision. Unfortunately, I don't know which commit fixed the issue.

`TC> server debug`
`TrinityCore rev.` e43be61b5ec7 `2021-05-07 20:59:39 +0300 (3.3.5 branch) (Win64, Release, Static)`
```sql
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.20.1
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 657797442 bytes
mmaps directory located in ./mmaps. Total size: 1961820104 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21041
TC> _

**Comment by illfated** [comment]
@Aokromes : Do you remember which commit the last week fixed this problem? The quest did not work at the start of Children's Week, using the 3 commits I listed above.

**Comment by Aokromes** [comment]
i know witch commit fixed it, but since we don't support cherry picking i will not supply the hash fixing it xd

**Comment by illfated** [comment]
Fair enough. 😄 Thanks for replying.

**Comment by gygyti** [comment]
understood thanks)
