### ISSUE TITLE
[Quest] 46938 Alone in the Abyss

### ISSUE THREAD

**Issue by Elgrimm** [TrinityCore/TrinityCore#26518]
https://www.wowhead.com/quest=46938/alone-in-the-abyss
 (**********************************)
     In this quest chain, there is no display on the map where the quest is being performed. Where are the necessary NPCs with whom there should be a dialogue and where who should be killed ... 

**Branch(es):**

master

**TC rev. hash/commit:** 

**Operating system:** 

CHANGEME OS

Windows 10

**Comment by Aokromes** [comment]
no yet implemented zone, duplicate.
