### ISSUE TITLE
[3.3.5] [Item] Goblin Bomb Dispenser

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26523]
https://classic.wowhead.com/item=10587/goblin-bomb-dispenser
Ref. https://github.com/TrinityCore/TrinityCore/issues/25636

Description:
This item do nothing.

Expected behaviour:
It must creates a mobile bomb that charges the nearest enemy and explodes for 315 to 385 fire damage. (30 Min Cooldown).

Steps to reproduce the problem:

1. .additem 10587
2. Equip this item and wait 30 sec. cooldown. (Requires Engineering 230)
3. Use this item.
4. See nothing.

Branch:
3.3.5

TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/f62e57e295094018f85dc78d8d034b0167b8becf

TrinityCore rev. 2021-05-04 09:53:13 +0300 (3.3.5 branch) (Win64, Release, Static)

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d 10 Sep 2019 (library: OpenSSL 1.1.1d 10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.21041
MySQL client library: 5.7.28
MySQL server ver: 5.7.28
Operating system:
Win7 SP1 x64 with all updates.

**Comment by Faq** [comment]
for 335 use https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=10587 not wowhead

**Comment by dr-j** [comment]
ID - 23134 Goblin Bomb
=================================================
Description: Creates a mobile bomb that charges the nearest enemy and explodes for $13259s1 fire damage.
Category = 0, SpellIconID = 1696, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0.00

Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 0 Bonus = 1.00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT

spell effect dummy this needs script

**Comment by Jinnaix** [comment]
Needs some scripting.

Spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=23134 should have linked spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=13258 for summoning https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=8937.

**Comment by Odyssey** [comment]
https://github.com/Odyssey/TrinityCore/commit/00b329f450cb38661a10cfa9368231d2f6c631ec fixes both spells used for the summoning so it actually spawns.

The npc has no script. I was only able to find spell 13261 which is only casted when it "malfunctions" and damages the player.
