### ISSUE TITLE
3.3.5 mechanical animals bug

### ISSUE THREAD

**Issue by damian1304** [TrinityCore/TrinityCore#26534]
players or npc summon an animal that is above their level

bug was discovered with a level 30 character and summoned one
ingenieur explodierendes sheep with level 41 and dosent explodes

goblins in stonetalon mountains can summon compact reapers that are also higher than their level

**Comment by MaxtorCoder** [comment]
Please fill in the issue template, you didn't change anything, just a really unhelpful title lol

**Comment by Jinnaix** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/21753

Additional note for @damian1304 
Do not delete the Issue Template - Fill in t he required information. Your Issue will be seen as invalid if you dont do this.
Provide NPC/Spell/Item Id´s if possible.
