### ISSUE TITLE
DB/Quest: Vengeful Souls, creature_questender x2 in DB & AoWoW

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#26530]
**Description:**

Looks like there is 1 unneeded row in `creature_questender` for Quest 10842, Vengeful Souls, referencing **Vengeful Harbinger** (and indirectly Draenei Ascendant).

Here is a screenshot from the tcubuntu.northeurope.cloudapp.azure.com/aowow quest page:
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10842/vengeful-souls

***

![image](https://user-images.githubusercontent.com/38162891/118382078-e6de3480-b5f1-11eb-8919-6b0f8ce6a7f2.png)

***

<details>
<summary>image 2 : ingame map Quest details - Draenei Ascendant [51.0, 55.0] (some sort of mix-up with deprecated quest 10841/the-vengeful-harbinger ?)</summary>

![Screenshot 2021-05-16 034342](https://user-images.githubusercontent.com/38162891/118382864-cade9100-b5f9-11eb-9c88-8c464da48ff6.png)

</details>

***

<details>
<summary>image 3 : Quest hand-in to High Priest Orglum, quest gossip & map detail (click to expand)</summary>

![WoWScrnShot_051621_021744](https://user-images.githubusercontent.com/38162891/118382707-42132580-b5f8-11eb-980e-3cd258e1e3f6.jpg)

</details>

***

```sql
SELECT * FROM `creature_questender` WHERE `quest`= 10842;
```
```sql
   id   quest
-----  ------
21638   10842
22278   10842
```

- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10849/seek-out-kirrik
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10842/vengeful-souls
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=22278/high-priest-orglum
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=21638/vengeful-harbinger
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=21636/vengeful-draenei
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10841/the-vengeful-harbinger
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?object=184830/draenei-ascendant

**Expected behaviour:**

There should only be one turn-in NPC on the ingame map and on the TrinityCore (tcubuntu) AoWoW webpage.

**Steps to reproduce the problem:**

1. Level 63 character or higher -> `.tele RefugeeCaravan` (for map & quest area update)
2. `.quest add 10849` -> `.quest complete 10849` (Seek Out Kirrik)
3. `.quest add 10842` -> `.quest complete 10842` (Vengeful Souls)
4. Check the ingame map and notice 2 quest delivery icons (as in image 2).

**Suggested solution:**

```sql
-- Vengeful Souls (10842) quest NPC correction
DELETE FROM `creature_questender` WHERE `id`= 21638 AND `quest`= 10842;
```

Note: I looked around in the DB to see if I could find any connection between the map text "Draenei Ascendant" and the redundant `creature_questender` row, but was unable to find anything useful.

**Branch(es):**

both ( I only checked the 3.3.5 content )

**TC rev. hash/commit:** 

16/5 02:19:45.244  TrinityCore rev. 7e5c1cf45397 2021-05-13 17:08:31 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
```sql
16/5 02:19:45.244  Using SSL version: OpenSSL 1.1.1j  16 Feb 2021 (library: OpenSSL 1.1.1j  16 Feb 2021)
16/5 02:19:45.244  Using Boost version: 1.74.0
16/5 02:19:45.244  Using MySQL version: 80025
16/5 02:19:45.244  Using CMake version: 3.18.4
16/5 02:19:45.244  Compiled on: Linux 5.11.0-1005-azure
16/5 02:19:45.281  Automatic database updates are enabled for the following databases: Auth, Characters, World
16/5 02:19:45.281  Worldserver listening connections on port 8085
16/5 02:19:45.281  Realmlist (Realm Id: 1) configured in port 8085
16/5 02:19:45.281  VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
16/5 02:19:45.281  MMAPs status: Enabled
16/5 02:19:45.501  maps directory located in /trinity/wowdata/maps. Total size: 291014951 bytes
16/5 02:19:46.097  vmaps directory located in /trinity/wowdata/vmaps. Total size: 657797442 bytes
16/5 02:19:46.278  mmaps directory located in /trinity/wowdata/mmaps. Total size: 1961820104 bytes
16/5 02:19:46.278  Using enUS DBC Locale as default. All available DBC locales: enUS 
16/5 02:19:46.278  Using World DB: TDB 335.21041
```

**Operating system:** 

Unix/Linux Ubuntu (TC) (game server), DB queried on Windows 10 x64 20H2 (local server)

**Comment by CraftedRO** [comment]
Isn't AoWoW using same 3.3.5 database as wow ?

**Comment by offl** [comment]
It does
