### ISSUE TITLE
Dungeon Reset Crash.

### ISSUE THREAD

**Issue by Misheelajil** [TrinityCore/TrinityCore#26536]
Description:
World server crashed when resetting dungeon.
Step to Produce:
1. Enter Dungeon.
2. Kill Mob.
3. Get out from dungeon.
4. Click reset dungeon or Change dungeon difficulty.
5. Server crashes.

https://gist.github.com/Misheelajil/26c566ddf927d31502e61505d41b8992

Branch(es):
Master
TC rev. hash/commit:
 https://github.com/TrinityCore/TrinityCore/commit/0935862770d390c0059bcc30b3c7a661a1ea820f.
Operating system: 
Windows 10 Professional (Version 10.0, Build 19042)

**Comment by Faq** [comment]
Use issue template and add also crashlog or this will be closed.

**Comment by Edder** [comment]
Not reproducible with 3df64ce
Tested with Ragefire Chasm, Mana Tombs and Utgarde Pinnacle

**Comment by jackpoz** [comment]
We don't even know which branch this issue is related to 🤔

**Comment by Misheelajil** [comment]
Hello sorry for incomplete information. I have updated it.
