### ISSUE TITLE
Crash log on recent Improve client control logic change, #26348 

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#26531]
**Description:**

Excited to see the change of https://github.com/TrinityCore/TrinityCore/pull/26348 , just pulled the source and tested it. After trying a lot of thing with vehicles finally had a crash. I believe the crash happened when controlled unit despawns or removed from the world but I could not reproduce it. I was just keep knocking down player controlled vehicles in wintergrasp

[crash-2021-05-17-03-55-04.log](https://github.com/TrinityCore/TrinityCore/files/6490029/crash-2021-05-17-03-55-04.log)

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
Clean build of 2d114ea560cd8716af2b0d12990fc3480ecaf2b7

**Operating system:** 
debian 10.4

**Comment by chaodhib** [comment]
Thanks for the report. I'll look into it

**Comment by shenhuyong** [comment]
'client->GetActivelyMovedUnit()->IsInWorld()' should be checked before 'client->GetActivelyMovedUnit()->GetGUID()'

**Comment by jackpoz** [comment]
@chaodhib do you have time to fix this crash ?

**Comment by chaodhib** [comment]
@jackpoz Yes, i'll submit a fix sometime this week. Probably tomorrow.

**Comment by chaodhib** [comment]
Easy way to reproduce the bug (as found by @Shauren):
1. ".npc add temp 28605" (or any vehicle)
2. enter the vehicle
3. .npc delete the vehicle while inside it

**Comment by ckegg** [comment]
Also found a proper way to

**Comment by chaodhib** [comment]
Closed by https://github.com/TrinityCore/TrinityCore/pull/26538
