### ISSUE TITLE
Fix extracting custom maps

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#26537]
**Description:**

See the issue I made on AC which had the same issue : https://github.com/azerothcore/azerothcore-wotlk/issues/5135

This is how to fix this issue, just need to comment two lines that check useless chunks in .WDT files, TC has the exact same code as AC https://github.com/azerothcore/azerothcore-wotlk/pull/5138

This has 0 other side effect than allowing to extract maps with a WDT file missing the WMO chunk(which is not read by the client for non WMO only maps), **all blizzard maps have it regardless so this doesn't change anything for blizzlike**, it just allwos to extract custom maps that miss this chunk

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

46d3c651a5ff4e96fc41700006a9854f90a90d63

**Operating system:**

**Comment by Aokromes** [comment]
maybe it's noggit who must fix the bug.

**Comment by jackpoz** [comment]
is Noggit on github ? can one report the issue to that project ? @T1ti do you have a link to that ?

**Comment by illfated** [comment]
I don't know, but does https://github.com/wowdev/noggit3 seem legit? Or is it just some kind of "fork"?

**Comment by ihm-tswow** [comment]
It's not a fork, that's where all noggit development happens now, don't remember why it moved. This issue has already been reported: https://github.com/wowdev/noggit3/issues/80

**Comment by bloerwald** [comment]
The files are accepted by the client, so they are fine.
The code that’s breaking for users here is 100% dead on your side. You literally only have to delete dead code. It breaks nothing. It isn’t even a change.

I will never understand your obsession with not helping users that want to have mods.

I will keep telling people to delete your dead code and while someone else may add writing that useless dead data that neither the client nor trinitycore needs, I for sure won’t. It is absurd to request noggit to change here.

“Please insert dead data so that our dead code doesn’t break”.

**Comment by jackpoz** [comment]
or you could open a PR to https://github.com/wowdev/noggit3/ to add the missing data so that "dead code" doesn't have to be removed from all the different wow projects in the world, adding support also to old versions without any change required.

**Comment by stoneharry** [comment]
> or you could open a PR to https://github.com/wowdev/noggit3/ to add the missing data so that "dead code" doesn't have to be removed from all the different wow projects in the world, adding support also to old versions without any change required.

This is still a bug with TrinityCore. If the client accepts it, then it should be supported. It's not exactly a big ask for 2-3 active emulators to fix a gap in their logic, and this has been well tested.

What is the aversion to adding it? I'm not sure why we should be writing data that the client doesn't require.

**Comment by stoneharry** [comment]
It's a very minor fix to the gap in the TC logic, or we have update every single historical map ever built over the last 15 years to provide data that the client doesn't require. I really don't understand the logic against adding this, can you explain your point of view please?

**Comment by stoneharry** [comment]
@Shauren Thank you very much, it's greatly appreciated. Little things like this really help.

**Comment by AlastorStrixEfuartus** [comment]
> maybe it's noggit who must fix the bug.

Noggit does not even touches WDT file at all
