### ISSUE TITLE
DB/creature_text: Crusader of Virtue says "%s cheers at you." instead of emote

### ISSUE THREAD

**Issue by illfated** [TrinityCore/TrinityCore#26544]
**Description:**

- https://www.wowhead.com/quest=13157/the-crusaders-pinnacle
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13157/the-crusaders-pinnacle

<details>
<summary>image 1: Crusader of Virtue Says: Crusader of Virtue cheers at you. [bubble: (%s cheers at you.)]</summary>

![WoWScrnShot_052221_212032](https://user-images.githubusercontent.com/38162891/119239208-eab90c00-bb47-11eb-9e4c-9fcb89d2c91f.jpg)

</details>

<details>
<summary>image 2: Crusader of Virtue Says: Crusader of Virtue cheers at you. [bubble: (%s cheers at you.)]</summary>

![WoWScrnShot_052221_212105](https://user-images.githubusercontent.com/38162891/119239247-189e5080-bb48-11eb-9149-4ab9ed60f970.jpg)

</details>

From commit https://github.com/TrinityCore/TrinityCore/commit/cf57ea2045af37f044a31be34ded8851bd670cea (https://github.com/TrinityCore/TrinityCore/commit/cf57ea2045af37f044a31be34ded8851bd670cea#diff-6b8e55b228209f7c0142938e04fee7292ec8a0bda1257967400a3886ddf6f030R31):

This `creature_text` is defined as a Say line (12):
```sql
(31033,0,8,"%s cheers at you.",12,1,100,71,0,0,25275,0,"Crusader of Virtue"),
```
As we know from https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130007/creature%2Btext#creature_text-Type, 12 is the Say type text, while 16 is Emote.

```sql
SELECT * FROM `creature_text` WHERE `comment` LIKE "%Crusader of Virtue%";
```
```sql
CreatureID  GroupID  ID  Text                                                                Type  Language  Probability  Emote  Duration   Sound  BroadcastTextId  TextRange  comment
----------  -------  --  ------------------------------------------------------------------  ----  --------  -----------  -----  --------  ------  ---------------  ---------  ------------------
  31033        0     0   We couldn't have done it without you, $g sir:ma'am;.                 12       0         100        66      0         0         31384           0      Crusader of Virtue
  31033        0     1   There goes the hero of the Vanguard!                                 12       0         100        66      0         0         31385           0      Crusader of Virtue
  31033        0     2   You honor us with your presence, $n.                                 12       0         100        66      0         0         31386           0      Crusader of Virtue
  31033        0     3   With your steadfast determination, we cannot fail!                   12       0         100        66      0         0         31387           0      Crusader of Virtue
  31033        0     4   Thank you, $n. From the bottom of my heart. Thank you.               12       0         100        66      0         0         31388           0      Crusader of Virtue
  31033        0     5   Call on me anytime, $n.                                              12       0         100        66      0         0         31389           0      Crusader of Virtue
  31033        0     6   We will battle along side you until the bitter end, $g sir:ma'am;!   12       0         100        66      0         0         31390           0      Crusader of Virtue
  31033        0     7   Hero, I am honored.                                                  12       0         100        66      0         0         31391           0      Crusader of Virtue
  31033        0     8   %s cheers at you.                                                    12       1         100        71      0         0         25275           0      Crusader of Virtue
```
Looking back at this content now, it appears that the character would have to be an Orc to discover this issue (Language = 1).

**Expected behaviour:**

This text should be defined as an Emote (16).
```sql
(31033,0,8,"%s cheers at you.",16,0,100,71,0,0,25275,0,"Crusader of Virtue"),
```

**Suggested solution:**

```sql
-- redefine this text line as Emote and with general Language
UPDATE `creature_text` SET `Type`= 16, `Language`= 0 WHERE `CreatureID`= 31033 AND `ID`= 8;
```

**Steps to reproduce the problem:**

1. Complete the Argent Vanguard quest line up to and including "The Crusaders' Pinnacle" (gameplay or by GM commands)
2. Walk/run around near the Crusader of Virtue NPCs on Crusaders' Pinnacle to trigger their Say text.
3. Note that there are no Emote lines, only say lines, even for Crusader of Virtue says "%s cheers at you.".

**Branch(es):**

Both branches, although I haven't noticed if commit cf57ea2045af37f044a31be34ded8851bd670cea has been cherry-picked to master yet.

**TC rev. hash/commit:** 

`TC> server debug`
TrinityCore rev. 19fa411431aa 2021-05-22 14:54:58 +0200 (3.3.5 branch) (Win64, Release, Static)
```sql
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.20.1
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 657797442 bytes
mmaps directory located in ./mmaps. Total size: 1961820104 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21051
TC> _
```

**Operating system:** 

Windows 10 x64 Version 20H2 (OS Build 19042.985)

**Comment by dr-j** [comment]
well this was emote when I originally scripted this https://github.com/TrinityCore/TrinityCore/commit/32903b080e17363583b352dee89dfdd9fdb31f74 so idk how go changed to 12 about the language was from sniff so no idea unless was a accidental keypress

**Comment by illfated** [comment]
The change from 16 to 12 happened in commit https://github.com/TrinityCore/TrinityCore/commit/cf57ea2045af37f044a31be34ded8851bd670cea, so it may have been a typo at that time.

Since you are saying that the language value 1 is from sniffs, I will withdraw the suggestion to change it to 0.
