### ISSUE TITLE
Cmake issues for pthread.h, FindOpenSSL and CmakeLists 

### ISSUE THREAD

**Issue by x92mko** [TrinityCore/TrinityCore#26543]
Hi all,

I'm very looking forward to get your suggestion regarding CMAKE. There are three responses while configerating and I don't know if they are critical or can be ignored?

1. 
Looking for pthread.h - not found

2.
CMake Warning (dev) at cmake/macros/FindOpenSSL.cmake:231 (math):
  Unexpected character in expression at position 2: b

3.
Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Here is the full configure: 

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
The C compiler identification is MSVC 19.28.29915.0
The CXX compiler identification is MSVC 19.28.29915.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.28.29915.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe

* TrinityCore revision   : 19fa411431aa 2021-05-22 14:54:58 +0200 (3.3.5 branch)

* Install core to        : C:/Program Files/TrinityCore
* Install configs to     : C:/Program Files/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found Boost: C:/local/boost_1_72_0 (found suitable version "1.72.0", minimum required is "1.70") found components: system filesystem program_options iostreams regex 
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for _strtod_l
Looking for _strtod_l - found
Found OpenSSL library: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
Found OpenSSL headers: C:/Program Files/OpenSSL-Win64/include

CMake Warning (dev) at cmake/macros/FindOpenSSL.cmake:231 (math):
  Unexpected character in expression at position 2: b

Call Stack (most recent call first):
  dep/openssl/CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring done

**Comment by jackpoz** [comment]
They are warnings that can be ignored

**Comment by MaxtorCoder** [comment]
Follow issue template please, thanks.
