### ISSUE TITLE
Core:WorldSession::Update ByteBufferException occured while parsing a packet (opcode: 1303)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26547]
**Description:**

`WorldSession::Update ByteBufferException occured while parsing a packet (opcode: 1303) from client myip, accountid=1. Skipped packet.`

After latest updates / fixes I get those errors in worldserver when I cast any spell after logging on like Horn of Winter for example on my DK in Dalaran ( the account is level 3 ) .
I even got a crash but I still coudn't reproduce it and I only got the attached poor log.
I dropped the world database and installed the fresh TDB_full_world_335.21051_2021_05_14 sql but it seems is not related to database.

**Expected behaviour:**

I guess those errors shoudn't exist anymore and also not crash.

**Steps to reproduce the problem:**

1. I just logged on my account level 3 - on my dk in Dalaran and casted Horn of Winter
2. The crash I coudn't reproduce anymore yet.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 19fa411431aa 2021-05-22 14:54:58

**Operating system:** 

Windows 10 x64

[19fa411431aa_worldserver.exe_[23-5_13-50-31].txt](https://github.com/TrinityCore/TrinityCore/files/6527986/19fa411431aa_worldserver.exe_.23-5_13-50-31.txt)
[Server.log](https://github.com/TrinityCore/TrinityCore/files/6527989/Server.log)
[Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/6527999/Crashes.zip)

**Comment by Shauren** [comment]
You are one commit late.

**Comment by CraftedRO** [comment]
lel and you are rly fast 👍

**Comment by jackpoz** [comment]
Btw crashlogs of worldserver built in Release mode are unreadable, RelWithDebInfo on the other hand is enough to read them

**Comment by CraftedRO** [comment]
ok , good to know.
