### ISSUE TITLE
Mod Decrease Speed aura will not restore speed after

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#26550]
**Description:**
After Core/Movement: Improve client control logic, https://github.com/TrinityCore/TrinityCore/pull/26348, any spell with Mod Decrease Speed aura will not restore speed after, for example: [Blind](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42972)

However, https://github.com/TrinityCore/TrinityCore/pull/26348 actually fixed https://github.com/TrinityCore/TrinityCore/issues/21044

**Expected behaviour:**
Speed restored after Mod Decrease Speed aura removed.

**Steps to reproduce the problem:**
1. .go creature id 23956
2. Let Dragonflayer Strategist hit you with [Blind](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42972)
3. Your character will wander confused for 3 seconds plus speed decrease, and your speed will not restore after.

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
Commit: 302c60d3dd8e2734b32d239142c72b1add22aad9

**Operating system:** 
debian 10.4

**Comment by jackpoz** [comment]
Assigning this to @chaodhib

**Comment by chaodhib** [comment]
Thanks for the report. I'll have a look this week, maybe today if I can.

**Comment by chaodhib** [comment]
Confirmed. I'm working on a fix. A proper fix involves some of the changes introduced in https://github.com/TrinityCore/TrinityCore/pull/18771. I'll see if I can quickly produce a PR with a smaller scope.

**Comment by Aokromes** [comment]
d337fb9

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d337fb99ed81dc3522bdea17e762febd989a6956
