### ISSUE TITLE
Networkthread file "delete _thread" problem

### ISSUE THREAD

**Issue by jwcpp** [TrinityCore/TrinityCore#26557]
Description:  
"_thread" is deleted twice, Although there is no problem in run, it is recommended to modify  
~NetworkThread() 析构函数里面两次执行"delete _thread;"  
`    virtual ~NetworkThread()
    {
        Stop();
        if (_thread)
        {
            Wait();
            delete _thread;
        }
    }
`  
`
    void Wait()
    {
        ASSERT(_thread);

        _thread->join();
        delete _thread;
        _thread = nullptr;
    }
`

**Comment by MaxtorCoder** [comment]
Follow issue template.....

**Comment by jackpoz** [comment]
_thread is set to nullptr after the first delete call, so the object pointed by the variable is deleted only once. Everything is good and safe.

Is that the automatic warning of some static analysis tool ?
