### ISSUE TITLE
[Crash] Player::StopCastingCharm 

### ISSUE THREAD

**Issue by Demonasus** [TrinityCore/TrinityCore#26555]
Alright, I decided to try this again and see if this goes anywhere. Before I proceed, I would like to mention that we are obviously using a custom fork. I decided to post this crash long anyway as the crash happens on the same line. We have no changes to that part of the core. @jackpoz as per your suggestion in the post [https://github.com/TrinityCore/TrinityCore/issues/24876] , I am posting this crash log hopefully it can be addressed or looked at regardless of the custom fork.

**What we use as custom changes:**
- Transmogrification System
- Dynamic XP Rates
- Crossfaction BGs / Mercenary Mode
- Anticheat

**crash line**
```
TC_LOG_FATAL("entities.player", "Player::StopCastingCharm: Player '%s' (%s) is not able to uncharm unit (%s)", GetName().c_str(), GetGUID().ToString().c_str(), GetCharmedGUID().ToString().c_str());
```if (!charm->GetCharmerGUID().IsEmpty()){TC_LOG_FATAL("entities.player", "Player::StopCastingCharm: Charmed unit has charmer %s", charm->GetCharmerGUID().ToString().c_str());
ABORT();
```

Upon Server crash, server log shows the same message as always (obviously with different player name)

```
Player::StopCastingCharm: Player 'Zenora' (GUID Full: 0x0000000000000048 Type: Player Low: 72) is not able to uncharm unit (GUID Full: 0xf1500075d1000040 Type: Vehicle Entry: 30161  Low: 64)
Player::StopCastingCharm: Charmed unit has charmer GUID Full: 0x0000000000000048 Type: Player Low: 72
World Thread hangs, kicking out server!
```

**Steps to reproduce the problem:**

We are still unsure what causes this crash, we tried everything we could possible think of to reproduce it without any luck.

**Branch:**
3.3.5
**TC rev. hash/commit:** 
61ad87d1069a (cherry picked with our own commits)

**Crash Log**
[61ad87d1069a52-34].txt](https://github.com/TrinityCore/TrinityCore/files/6542811/61ad87d1069a52-34.txt)

**Operating system:** 
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Number Of Processors: 8
Physical Memory: 33187668 KB (Available: 25544820 KB)
Commit Charge Limit: 37381972 KB

*** Operation System ***
Windows Server 2012 Standard (Version 6.2, Build 9200)

**Comment by Aokromes** [comment]
2019 core? no way we support this.

**Comment by Demonasus** [comment]
Like i said, this is pointless @jackpoz

**Comment by Aokromes** [comment]
we don't support old cores and we don't support cherrypicking, only updated cores.

**Comment by Astrono1293** [comment]
I was about to say, finally someone posted a crash long regarding the issue from years ago @Aokromes you are everything whats wrong with TC. The OP was asked to post the crash long by @jackpoz , maybe you should read more often. This issue, regardless of the core is present in all revisions since 2019.  He was asked to post it, he did, even tho he said this would happen and it did!

**Comment by Aokromes** [comment]
> I was about to say, finally someone posted a crash long regarding the issue from years ago @Aokromes you are everything whats wrong with TC. The OP was asked to post the crash long by @jackpoz , maybe you should read more often. This issue, regardless of the core is present in all revisions since 2019. He was asked to post it, he did, even tho he said this would happen and it did!

two of the rules of bug report is:
try on clean core
try on updated core

he is doing the 2 things incorrectly.
and the 3rd, it's duplicate of one open ticket.

**Comment by Demonasus** [comment]
> I was about to say, finally someone posted a crash long regarding the issue from years ago @Aokromes you are everything whats wrong with TC. The OP was asked to post the crash long by @jackpoz , maybe you should read more often. This issue, regardless of the core is present in all revisions since 2019. He was asked to post it, he did, even tho he said this would happen and it did!

I even said that, "I do not want to waste my time posting this" by @jackpoz made a valid point and i listened to him even thou i knew Aokromes would close it seconds after. Anyways, it's all good

**Comment by Astrono1293** [comment]
> > I was about to say, finally someone posted a crash long regarding the issue from years ago @Aokromes you are everything whats wrong with TC. The OP was asked to post the crash long by @jackpoz , maybe you should read more often. This issue, regardless of the core is present in all revisions since 2019. He was asked to post it, he did, even tho he said this would happen and it did!
> 
> two of the rules of bug report is:
> try on clean core
> try on updated core
> 
> he is doing the 2 things incorrectly.
> and the 3rd, it's duplicate of one open ticket.

He was ASKED to do it!  my lord. This is such a waste of time indeed. @Demonasus I understand you 100%.

@Aokromes this may be a BIG NEWS to you, nobody in the right mind uses the latest core on their private servers. But you do what you got to do my friend.

**Comment by illfated** [comment]
Thank you for trying. Thanks for the insight. Thank you for participating. If nothing else, it provided some information about your preferred scenarios.

**Comment by Aokromes** [comment]
> > > I was about to say, finally someone posted a crash long regarding the issue from years ago @Aokromes you are everything whats wrong with TC. The OP was asked to post the crash long by @jackpoz , maybe you should read more often. This issue, regardless of the core is present in all revisions since 2019. He was asked to post it, he did, even tho he said this would happen and it did!
> > 
> > 
> > two of the rules of bug report is:
> > try on clean core
> > try on updated core
> > he is doing the 2 things incorrectly.
> > and the 3rd, it's duplicate of one open ticket.
> 
> He was ASKED to do it! my lord. This is such a waste of time indeed. @Demonasus I understand you 100%.
> 
> @Aokromes this may be a BIG NEWS to you, nobody in the right mind uses the latest core on their private servers. But you do what you got to do my friend.

he don't was said to open a new ticket.

**Comment by jackpoz** [comment]
@Demonasus what class is player Zenora ?
