### ISSUE TITLE
Core/Quest Delivery Quests Bug

### ISSUE THREAD

**Issue by subsix-wow** [TrinityCore/TrinityCore#26566]
**Description:**

All Delivery Quests are bugged. For example https://www.wowhead.com/quest=28730/precious-waters
The item that you get when accepting the Quest simply is not counted as objective.
You can delete that Questitem and .additem 5184 again. Then the quest objective gets counted.
So there is an issue when accepting that kind of quests, since it affects all of that Delivery kind.

**Expected behaviour:**

Quest Objective should get completed upon receiving the "Item to Deliver"

**Steps to reproduce the problem:**

1. .quest add 28730
2. Try to turn in Quest at NPC 3514-> Grey Questionmark
3. Delete Quest Item
4. .additem 5184
5. Now you will be able to turn in quest

**Branch(es):**

master

**TC rev. hash/commit:** 

TrinityCore rev. cfd4f1888535+ 2021-05-30 20:00:34 +0200 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1h  22 Sep 2020)
Using Boost version: 1.72.0
Using MySQL version: 5.7.34
Using CMake version: 3.20.1
Compiled on: Windows 10.0.18363
Automatic database updates are disabled for all databases!
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Disabled
MMAPs status: Disabled
maps directory located in ./ClientData/maps. Total size: 1407969318 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 837.20101

**Operating system:** 

Win64

**Comment by subsix-wow** [comment]
Just guessing, but maybe it's something in Player.cpp:16209

**Comment by Faq** [comment]
Did you try to relog when first receved it from q giver? Just wondering if in that case it will count too.

**Comment by subsix-wow** [comment]
Tried that and it does NOT count either. But thanks for suggesting.

**Comment by illfated** [comment]
There are similar quest issues in 3.3.5 too, where you need to move the quest item to bank and back again to player bags (in case the player character is not a GM) to get it counted as present and to complete the quest. Could potentially be a bag item handling issue, but your suggestion `Player.cpp:16209` (see below) is more likely.

```cpp
bool Player::GiveQuestSourceItem(Quest const* quest)
{
    uint32 srcitem = quest->GetSrcItemId();
    if (srcitem > 0)
    {
        uint32 count = quest->GetSrcItemCount();
        if (count <= 0)
            count = 1;

        ItemPosCountVec dest;
        InventoryResult msg = CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, srcitem, count);
        if (msg == EQUIP_ERR_OK)
        {
            Item* item = StoreNewItem(dest, srcitem, true);
            SendNewItem(item, count, true, false);
            return true;
        }
        // player already have max amount required item, just report success
        if (msg == EQUIP_ERR_ITEM_MAX_COUNT)
            return true;

        SendEquipError(msg, nullptr, nullptr, srcitem);
        return false;
    }

    return true;
}
```

**Comment by subsix-wow** [comment]
So to temp fix will be to set this to QuestType = 0 i guess.

**Comment by subsix-wow** [comment]
I don't know that much of C++ but isn't there a way to tell the game that you receive the specific "SourceItem" before the "QuestCheckRequests" or "GetQuestObjective" Routine is run? Please don't blame me, i'm not good in C++, just trying to think about it...

**Comment by illfated** [comment]
Fair question. Wish I knew the answer, but we'll have to wait for some of the real coders to reply.
