### ISSUE TITLE
Shadowlands 9.0.5 (38556). There is no connection to the server.

### ISSUE THREAD

**Issue by rem999** [TrinityCore/TrinityCore#26576]
Video: https://youtu.be/U8B5mUm_GIA

I collect it for the third time. And every time the client doesn't connect to the server.
Третий раз собираю. И каждый раз клиент не соединяется с сервером.

**Comment by MaxtorCoder** [comment]
Follow issue template

**Comment by Aokromes** [comment]
problem is user configuration not trinitycore bug.

**Comment by rem999** [comment]
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file D:/SSSDDDD/Release 9.0.5 (38556)/worldserver.conf.
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.66.0
Updating Auth database...
>> Auth database is up-to-date! Containing 13 new and 178 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 7 new and 105 archived updates.
Updating World database...
>> Applying update "2019_07_28_02_world_2017_02_21_02_world.sql" 'A507C54'...
mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1054 (42S22) at line 1: Unknown column 'entry' in 'spell_enchant_proc_data'


Applying of file 'C:/TrinityCore-master/sql/old/8.x/world/19071_2020_06_17/2019_07_28_02_world_2017_02_21_02_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

**Comment by MaxtorCoder** [comment]
Code blocks please.

**Comment by illfated** [comment]
Maybe I am wrong, but if you are applying SQL files from 2019 to your DB, it looks a bit like if you are not using the TDB releases (latest available at the moment: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB837.20101).

> ERROR 1054 (42S22) at line 1: Unknown column 'entry' in 'spell_enchant_proc_data'

This error seems to indicate that you have got a DB containing an outdated table structure, maybe from not starting with a completely empty (or removed) world DB. You need to rebuild your DB using TDB837.20101 before any of the added SQL files come into play.

The fact that you use a downloaded zip file from the repository page also makes it more difficult to troubleshoot, is that your core displays "rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch)" which does not tell us the actual core revision or date/time. This can be avoided if you use a Git tool to clone the source to keep the core revision hash intact during compile.

**Comment by illfated** [comment]
To make sure that your core loads TDB837.20101 before applying any of the later added SQL files, you need to extract the TDB full SQL file and place it in the same folder as your server cores, to make worldserver load the TDB first, then apply any later SQL file content. Make sure that you delete your old world DB before starting worldserver.

**Comment by subsix-wow** [comment]
Boost 1.66? You might update that to at least 1.72, OpenSSL to 1.1.1k aswell.
And you might set the `SourceDirectory  = ""` in worldserver.conf to point to correct Source folder, which will contain all necessary DB updates.

**Comment by rem999** [comment]
Good anti-theft protection. It was interesting to me. Why is no one releasing updates. Now I understand. Perhaps I'll wait a little longer.

Хорошая защита от краж. Мне было интересно. Почему никто не выпускает обновления. Теперь я понял. Пожалуй ещё подожду.

**Comment by arwent** [comment]
Same here.

**Comment by Xyliad** [comment]
i had the same problems, it was asking for 8xx tdb found updated the core following the install guide, now i'm with arwent on the logging in to game server, it's all localhost
