### ISSUE TITLE
The quest 12687 "Into the realm of shadows" has an issue and crashes due to the SPELL in the "Vehicle" horse used to exit shadow realm to complete quest fails and crashes server. 

### ISSUE THREAD

**Issue by WireliteSoft** [TrinityCore/TrinityCore#26574]
**Description:**

The quest 12687 "Into the realm of shadows" has an issue and crashes due to the SPELL in the "Vehicle" horse used to exit shadow realm to complete quest fails and crashes server. i think the spell id is wrong spell or spell needs repaired/broken spell

A workaround that i figured out but only workaround as a gm. the spell used on the horse is bad i guess. the workaround is to exit the horse without clicking the spell then .unaura all to remove the aura shadow realm. then you can complete the quest. however if you click the spell inside the horse vehicle the server crashes and it can't be marked as complete using the spell. you must use the command .quest complete 12687.

**Expected behaviour:**

The quest should complete and not crash the worldserver.exe.

**Steps to reproduce the problem:**

1. Make a DK  
2. Get to the quest to get your DK horse. quest # 12687 "Into the realm of shadows"
3. Go get the horse and return to death's rise, click the spell (server goes offline)

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

recent core:
TrinityCore rev. 52333b0e311d+ 2021-05-20 02:51:53 +0300 (3.3.5 branch) (Win64, Debug, Static) (worldserver-daemon)

**Operating system:** 

windows 10 pro

**Comment by offl** [comment]
If it's the same crash, it was fixed by https://github.com/TrinityCore/TrinityCore/commit/19fa411431aa8a87a27206af116d4b0d1fb953ec
Try to update core and post crashlog if issue still persist

**Comment by WireliteSoft** [comment]
> If it's the same crash, it was fixed by [19fa411](https://github.com/TrinityCore/TrinityCore/commit/19fa411431aa8a87a27206af116d4b0d1fb953ec)
> Try to update core and post crashlog if issue still persist

ok. I will try that in 20 mins and reply again. oddly it did not have a crashlog last time. no logs at all in the crashes folder.

**Comment by WireliteSoft** [comment]
ok that worked. it fixed the bugged quest. thankyou. i guess it was 8 days too old :)
