### ISSUE TITLE
[Witherbark Totem Sticks] not dropping during the [Items of Power] quest

### ISSUE THREAD

**Issue by edricgarran** [TrinityCore/TrinityCore#26572]
**Description:**
The Items of Power Quest (ID: 1948) requires 10 of those (Entry: 7273), which can be used to create the item 7272 required to complete the quest. The Totem Sticks are referenced in the ItemDrop4 column of the quest_template,  and defined as QuestRequired=1 in the relevant creature_loot_templates, but never drop, even if I set the Chance to 100. If I disable the QuestRequired field, they drop normally, so I think it's a bug with the ItemDropX handling.

**Expected behaviour:**
[Witherbark Totem Sticks] should drop during the [Items of Power] quest.

**Steps to reproduce the problem:**

1. Be a mage
2. Pick the Items of Power class quest
3. Go to Arathi Highlands and kill lots of Witherbark trolls

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

e7e47866066f0b318c986c355dc4476b5948e622

**Operating system:** 

Linux

**Comment by illfated** [comment]
@edricgarran : Did you find that the quest works, meaning that this issue ticket is redundant, or are there any other reasons for closing?

**Comment by edricgarran** [comment]
> @edricgarran : Did you find that the quest works, meaning that this issue ticket is redundant, or are there any other reasons for closing?

Sorry about that, it was actually a huge brain fart on my side, I had spent hours debugging why the items weren't dropping, and decided to post the issue, only to look at my inventory and see the 10 items happily sitting there, unnoticed, and the reason they weren't dropping was simply because they had already dropped and I didn't notice because they aren't reported as normal quest items.

**Comment by illfated** [comment]
That is all fine. Thanks for replying.
