### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26588]
Two-factor authentication is not working. I test it on with console command **account set 2fa username base32pass**

**How to rep:**
1. Create account
2. Write into console **account set 2fa username base32pass**
3. Try to login

The client alert will be: Your pass or username is incorrect

**tested on:** [https://cryptii.com/pipes/base32](https://cryptii.com/pipes/base32)

debian
3.3.5
rev. 7c6ee03

**Comment by jackpoz** [comment]
do your steps include filling https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist#L1323 ?

**Comment by gygyti** [comment]
now I write into worldserver.conf **TOTPMasterSecret = secret** and use command **relaod config**. The same problem

**Comment by gygyti** [comment]
>  **(authserver.conf)** The master key used to encrypt TOTP secrets for database storage. 
ok I want to storege none encrypt and then I use **<blank> - (Store TOTP secrets unencrypted)**

>  **(worldserver.conf)** The key used by authserver to decrypt TOTP secrets from database storage.
but my data on database is not encrypted

**Comment by Shauren** [comment]
It is working as intended.
For example, if you are using WinAuth, the secret key (using google authenticator type) is already base32 encoded and should be pasted directly into command, not encoded again

**Comment by gygyti** [comment]
> 
> 
> It is working as intended.
> For example, if you are using WinAuth, the secret key (using google authenticator type) is already base32 encoded and should be pasted directly into command, not encoded again

I insert the encoded text from the site (https://cryptii.com/pipes/base32) into the command like 1234 is **GEZDGNA=**
In database there are save non encoded pass

**Comment by gygyti** [comment]
guys, did anyone get to check this out?

**Comment by Shauren** [comment]
I have a feeling you are not understanding how to properly use it, can you describe what 2fa app you are using to test it?

**Comment by gygyti** [comment]
I don't quite understand which 2fa application should I use?

I just wanted to do double authorization.
As I understand it, the second password is stored in the `auth` database in the` account` table in the `totp_secret` field. 

![изображение](https://user-images.githubusercontent.com/77268574/121789253-0fe7ea00-cbdd-11eb-84ce-66bcee387b21.png)

**Comment by Shauren** [comment]
No. You understand it wrong, this is for things like battle.net authenticator (except you cant use the official app, you have to something like https://winauth.github.io/winauth/index.html or mobile app like authy that generates you 6 digit codes). `totp_secret` is the "secret code" used to set up those, not the one time use code generated on demand.
You cannot use it like you are trying to do right now.

**Comment by gygyti** [comment]
where can I read about how it works for TC?
