### ISSUE TITLE
DB/Misc: Add new View for RBAC

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#26587]
**Description:**

If anyone like me is sick of clicking through 3 different tables just to find out what the hell is going on in rbac permissions, the following view might help:

```sql
--
-- Drop previous functions/views if any
DROP VIEW IF EXISTS `vw_rbac`;

-- Create the view
CREATE SQL SECURITY INVOKER VIEW `vw_rbac` AS select `t1`.`linkedId` AS `Permission ID`,`t1`.`id` AS `Permission Group`,ifnull(`t2`.`secId`,'linked') AS `Security Level`,`t3`.`name` AS `Permission` from ((`rbac_linked_permissions` `t1` left join `rbac_default_permissions` `t2` on((`t1`.`id` = `t2`.`permissionId`))) left join `rbac_permissions` `t3` on((`t1`.`linkedId` = `t3`.`id`))) ;
```

**Expected result:**

![image](https://user-images.githubusercontent.com/37972361/121189135-14717300-c86a-11eb-8c7a-2910dad6b978.png)

**Notes:**

There are dozens of permissions not linked to any group right now, either because they are meant to be executed from the console or are there to permit something for users.

If this doesnt seem to have any use for TC, just close this issue :)

**Branch(es):**

3.3.5
(potentially both, but was made for 335 as i dont do stuff on master)

**TC rev. hash/commit:** 

7c6ee033e05faca9a013037f1a9c9bbdf62cd702

**Comment by Jinnaix** [comment]
Not meant to be forgotten - thank you very much @jackpoz for your support with this

**Comment by ccrs** [comment]
I love you

**Comment by Jinnaix** [comment]
Its very basic.

At a certain point, there is no original security level anymore, therefore the view gives back "linked" in that case. So people still need to filter every now and then but its a bit more convenient as constantly swapping back and forth between single tables.

![image](https://user-images.githubusercontent.com/37972361/121216904-9de06f80-c881-11eb-9caa-2051b2a78d15.png)

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/46bab72af54c57cc654ebc0af685eafa3011c5dc
