### ISSUE TITLE
how to use script module in trinitycore 

### ISSUE THREAD

**Issue by libxengine** [TrinityCore/TrinityCore#26585]
there is src\server\scripts... module ...
how to use?
who can tell me...i don't know...

**Comment by Jinnaix** [comment]
Github isnt a forum. Please head over to https://community.trinitycore.org/ or join Irc/Discord.

**Comment by libxengine** [comment]
not anyone answer me....
https://community.trinitycore.org/topic/15474-how-to-use-scripts-module-in-trinitycoresrcserverscripts-of-335/

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/discussions has a Q&A section too
![image](https://user-images.githubusercontent.com/1153754/121140311-fd1a9180-c839-11eb-88c2-fd1dad57c960.png)

The wiki has https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130195/CustomScript that explains how to use custom scripts
