### ISSUE TITLE
[Sunwell Plateau] Felmyst

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26597]
https://www.wowhead.com/npc=25038/felmyst
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=25038

Description:
Well, I killed [Brutallus](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=24882) on the [Sunwell Plateau](https://tbc.wowhead.com/sunwell-plateau), and with the help of the hunter's "[Track Undead](https://tbc.wowhead.com/spell=19884/track-undead)" ability, I can see that the Felmyst has appeared, but he is not on the ground or in the air. Maybe he's underground? I dont know. I tried to find him using commands **.go xyz** and **.gm fly**, but I never found him either in the air or underground. The command **/target Felmyst** did not help to find and highlight him (See screenshots). As you can see in the screenshots, I waited for Felmyst to appear for more than 40 minutes (while I was writing this text here). Of course, because of this, it is impossible to remove the wall of fire to the rest of the instance bosses. 
I have checked this twice.
Rate.Creature.Elite.WORLDBOSS.HP = 0.1

Expected behaviour:
Even if there is no scripted scene, the Felmyst should appear on the ground or low in the air after the death of the Brutallus.
Ideally, the following should happen (description from wowhead):

Felmyst is a fel dragon who is raised from from the corpse of the blue dragon [Madrigosa](https://tbc.wowhead.com/npc=24895/madrigosa). She is the third boss in the Sunwell Plateau, and can only be fought once Brutallus has been defeated.
This NPC can be found in Sunwell Plateau. 
She spawns when Brutallus dies, she raises out of Madrigosa's corpse. Felmyst looks like Sapphiron in Naxxramas, reminds of Nightbane fight in Karazhan (summons skeletons and flies around).
You need to kill Brutallus to be able to remove the firewall that makes you unable to continue in the instance.

Steps to reproduce the problem:
1. 	Create a level 70 character. 
2.	Go to the Sunwell Plateau.
3.	Use cheats **.cheat god** and **.cheat power** to kill Brutallus.
4.	Make sure Felmyst doesn't show up. If your character is a hunter class, then using the "[Track Undead](https://tbc.wowhead.com/spell=19884/track-undead)" skill, make sure that Felmyst still appeared, but it is not clear where.
5.	Understand that because of this problem you will not be able to get to the rest of the Sunwell bosses, which makes the Sunwell impassable.
6.	Become very very sad, especially if you do not know how to use the command **.gm fly**.

Branch:
3.3.5

TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/2acdd163fea281f467f074d267e45660fc9bf99d

TrinityCore rev. 2021-06-11 17:28:34 +0300 (3.3.5 branch) (Win64, Release, Static)

Some logs from auth/world servers:
Using SSL version: OpenSSL 1.1.1d 10 Sep 2019 (library: OpenSSL 1.1.1d 10 Sep 2019)
Using Boost version: 1.72.0
Using World DB: TDB 335.21051
MySQL client library: 5.7.28
MySQL server ver: 5.7.28
Operating system:
Win7 SP1 x64 with all updates (build 6.1.7601).

(Felmyst = Пророк Скверны in Russian client)
![WoWScrnShot_061321_161021](https://user-images.githubusercontent.com/73786888/121810000-bbd61780-cc67-11eb-9d19-dc828be26c6d.jpg)
![WoWScrnShot_061321_165124](https://user-images.githubusercontent.com/73786888/121810001-bd9fdb00-cc67-11eb-9ee0-0d9a80775406.jpg)

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5680

**Comment by Freeman256** [comment]
Sadly, I tried very hard to describe the problem in detail. But okay, if that's the way it should be ...

**Comment by Faq** [comment]
@Freeman256 someone reported that, next time search in issues before posting new one.
