### ISSUE TITLE
Hunter pet not saving, and stabled pet can't be summoned.

### ISSUE THREAD

**Issue by WireliteSoft** [TrinityCore/TrinityCore#26599]
**Description:**

Hunter pets not saving to database. you can tame a pet but on logout even after using .save
the pets in your stable show their icons but you can't call a pet.
also your pet is not spawned after relogging. it says you don't have a pet. when using spells to summon pets
and you can't move a stabled pet to your current pet slot.

**Expected behaviour:**

Pets should save to database and they should be present when logging back in, calling a stabled pet should
spawn your pet. and moving a pet from stable slot to current pet slot should move it to the empty slot

**Steps to reproduce the problem:**

1.  make a hunter and level up to 80, learn all hunter spells 
2. tame a beast 
3. type .save
4. relog
5. pet is gone.
6. tame a pet
7. call stable pet spell
8. put your pet in the stable
9. use .save
10. relog
11. pet shows in stable but no way to move it back to current pet slot

**Branch(es):**
3.3.5

TrinityCore rev. e9a8cea01859+ 2021-06-12 18:02:01 +0200 (3.3.5 branch)

**Operating system:** 

Windows 10 pro

**Comment by jackpoz** [comment]
Does worldserver show any database error ?

**Comment by WireliteSoft** [comment]
No error and no crash. but pets can't be summoned out of stables or saved on logout.
at first i was using a hunter pet script and noticed it but then I tested with a world stable master same issue. also with using the stable pet spell same happens.

**Comment by WireliteSoft** [comment]
If you want I can make a video of the issue so you can see exactly what is happening.

**Comment by Jinnaix** [comment]
Cannot replicate. - 8d92f6f2b483dffa7127614de3c41f3f596743fb
After taming, save and relog:
![WoWScrnShot_061421_122321](https://user-images.githubusercontent.com/37972361/121878297-dbbf1700-cd0b-11eb-97f8-cefaa0e4517d.jpg)

Putting pet in stable, save and log out.
![WoWScrnShot_061421_122640](https://user-images.githubusercontent.com/37972361/121878334-e5487f00-cd0b-11eb-86e8-2aa2f5bcf7ca.jpg)

Logging back in, taking pet out of stable.
![WoWScrnShot_061421_122653](https://user-images.githubusercontent.com/37972361/121878408-f8f3e580-cd0b-11eb-9f1c-e0fac110c295.jpg)

**Comment by Aokromes** [comment]
same here, cannot reproduce.

**Comment by WireliteSoft** [comment]
your core is not as new as mine is. look at your core revision.

**Comment by Shauren** [comment]
.pdump of that character

**Comment by Aokromes** [comment]
he is using the version of yesterday, it cannot be newer.
