### ISSUE TITLE
kick on enter icc if died

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26607]
**Description:**

people trying to re-enter icc after wipe is being kicked 

**Expected behaviour:**

no kick

**Steps to reproduce the problem:**

1. .tele icecrownc
2. target self and .die and release
3. reenter icc
4. be kicked

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

32fd44d2aa6b

**Operating system:** 

debian 10 x64

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/e6557834316fa6231c08bb22865faa0e489a64e4 is supposed to log more information if you enable the cheat setting in the config (disabled by default)

**Comment by jackpoz** [comment]
>2021-06-17_09:59:44 WorldSession::HandleForceSpeedChangeAck: Player Aokromes from account id 2 kicked for incorrect data returned in an ack. pendingChange.movementCounter: 4, movementCounter: 6
2021-06-17_09:59:44 Account: 2 Character: 'Aokromes' GUID Full: 0x0000000000000002 Type: Player Low: 2 kicked with reason: incorrect movementCounter returned in an ack
2021-06-17_09:59:44 WorldSession::HandleForceSpeedChangeAck: Player Aokromes from account id 2 kicked for incorrect data returned in an ack. pendingChange.movementCounter: 5, movementCounter: 7
2021-06-17_09:59:44 Account: 2 Character: 'Aokromes' GUID Full: 0x0000000000000002 Type: Player Low: 2 kicked with reason: incorrect movementCounter returned in an ack

**Comment by jackpoz** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/ is running with AntiCheat.PendingMoveChangesTimeoutTime = 10000 if anyone wants to test more cases related to the recent changes

**Comment by jackpoz** [comment]
@chaodhib pinging you about this issue. I added some logs and wrapped the kicks around the timeout config, so it's easy for users to disable them for the time being.

**Comment by chaodhib** [comment]
👍 thank you. will have a look either later today or tomorrow

**Comment by Aokromes** [comment]
add to log GetDebugInfo on that way we can find if certain coords may have the bug.

**Comment by chaodhib** [comment]
Confirmed. I only had a short amount of time today to look into it. I'll work on a fix this weekend.

**Comment by shenhuyong** [comment]
```
 src/server/game/Entities/Player/Player.cpp | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 3407da8dbd..0d82a489ad 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -1806,9 +1806,6 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati
             //remove auras before removing from map...
             RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_CHANGE_MAP | AURA_INTERRUPT_FLAG_MOVE | AURA_INTERRUPT_FLAG_TURNING);
 
-            // players on mount will be dismounted. the speed and height change should not require an ACK and should be applied directly
-            PurgeAndApplyPendingMovementChanges(false);
-
             if (!GetSession()->PlayerLogout())
             {
                 // send transfer packets
@@ -1824,6 +1821,9 @@ bool Player::TeleportTo(uint32 mapid, float x, float y, float z, float orientati
             if (oldmap)
                 oldmap->RemovePlayerFromMap(this, false);
 
+            // players on mount will be dismounted. the speed and height change should not require an ACK and should be applied directly
+            PurgeAndApplyPendingMovementChanges(false);
+
             m_teleport_dest = WorldLocation(mapid, x, y, z, orientation);
             m_teleport_options = options;
             SetFallInformation(0, GetPositionZ());
```

**Comment by jackpoz** [comment]
@shenhuyong could you please open a PR with your change ? It should be easier to review and approve

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9b05c3967bda1c49935e6f87b3b781afd9607035

**Comment by jackpoz** [comment]
Thanks @shenhuyong for the fix 👍
