### ISSUE TITLE
3.3.5 last build

### ISSUE THREAD

**Issue by Archangel1984** [TrinityCore/TrinityCore#26609]
dungeon: the depths of the black mountain does not reset the aggro in the tavern and the last room with the boss and mobs there also pass the walls
dungeon: necrosity does not reset aggro
Dungeon: Stratholme! does not reset the agro

**Comment by MaxtorCoder** [comment]
Follow issue template..

**Comment by Aokromes** [comment]
no that's not how you report a bug, you don't remove template, you open one ticket per bug.
