### ISSUE TITLE
[Utgarde Pinnacle]:boss_skadi.cpp

### ISSUE THREAD

**Issue by Lavitz** [TrinityCore/TrinityCore#2660]
It seems Skadi is unable to change from its first combat phase. During the first part of the encounter the group of players have to face periodic spawns, defeat them and use their harpoons to shoot Skadi through the launchers located at the bottom where the encounter takes place.

I guess this issue is related to the fact that the harpoons cast an spell on Skadi and its AI has to detect it and it does not. I have modified that part to make the entire script functionable changing the way the AI detects the harpoons being launched. Here is the patch proposed.

http://pastebin.com/BbuT5tmR

**Comment by AnTOLI** [comment]
No working http://www.wowhead.com/achievement=2156/my-girl-loves-to-skadi-all-the-time.

**Comment by el-druida** [comment]
emmm any news about this?

**Comment by sirikfoll** [comment]
You can try to finish https://github.com/TrinityCore/TrinityCore/pull/14866. Even unfinished, seems to  work better than the current one

**Comment by tkrokli** [comment]
Yes, if you have got any coding experience and are prepared to work with Pull Requests, I recommend that you follow sirikfoll's suggestion and pick up where mik1893 left off from his work 6 months ago.

**Comment by Jenkyins** [comment]
confirmed on 31cd082

**Comment by sirikfoll** [comment]
I have it rewritten, I will open a PR next week

**Comment by Aokromes** [comment]
@sirikfoll next week }:-)

**Comment by sirikfoll** [comment]
sorry, didn't had the time yet, it's basically done, missing some clean-up, I'll PR as soon as possible
https://gist.github.com/sirikfoll/f4386ec93b9d979f0028

**Comment by Swode** [comment]
I get error with DATA_GRAUF
when I compile

**Comment by sirikfoll** [comment]
Fixed in https://github.com/TrinityCore/TrinityCore/commit/40114cacd37675a9cbe7d2eef15445340d87e814
