### ISSUE TITLE
Gryphon Hatchling must fly

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26600]
**Description:**

this is a state-changing minipet
acording
https://www.wowhead.com/item=49662/gryphon-hatchling#screenshots:id=169617 
https://www.wowhead.com/item=49662/gryphon-hatchling#comments:id=989767
it must fly with you

**Steps to reproduce the problem:**

1. addi 49662
2. mount some flying mount
3. fly
4. cry

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

4acd6e1d3821

**Operating system:** 

debian 10 x64 N/R

**Comment by Aokromes** [comment]
horde version 49663 needs same fix.

**Comment by offl** [comment]
*If you're simply mounted, not if you're only on flying mount
https://www.wowhead.com/item=49662/gryphon-hatchling#screenshots:id=161449
https://www.wowhead.com/item=49662/gryphon-hatchling#screenshots:id=169220
