### ISSUE TITLE
Map versions are updated too often.

### ISSUE THREAD

**Issue by amydomi** [TrinityCore/TrinityCore#26615]
**Description:**

The update server failed to run. The map version is too low. It will take a long time to extract the map again

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** 

CHANGEME OS

**Comment by Jinnaix** [comment]
Thats not an issue.
Also extracting is way faster now since Jackpoz introduced multi-threading updates for tools.

**Comment by amydomi** [comment]
> Thats not an issue.
> Also extracting is way faster now since Jackpoz introduced multi-threading updates for tools.

Can you provide binary tool file download?The recompile does not meet the compile condition.

**Comment by Ovahlord** [comment]
Not an issue but a necessary change in order to keep you guys from using outdated map data. It IS required to re-extract them. If versions change there is a good readon for it.

**Comment by jackpoz** [comment]
binaries are always available at https://ci.appveyor.com/project/DDuarte/trinitycore/branch/3.3.5/artifacts (for 3.3.5 branch, but who knows which branch you are using, you didn't fill the template that asks for which branch the issue is...)

**Comment by amydomi** [comment]
> binaries are always available at https://ci.appveyor.com/project/DDuarte/trinitycore/branch/3.3.5/artifacts (for 3.3.5 branch, but who knows which branch you are using, you didn't fill the template that asks for which branch the issue is...)

3.3.5   thinks!
