### ISSUE TITLE
[Object] Standing, Large - MFF

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26623]
Standing, Large - MFF is flying (entry 181300)

 Standing, Large - MFF 
**X:-2035.189941 
Y:5275.620117 
Z:-38.974400 
MapId:530**

![изображение](https://user-images.githubusercontent.com/77268574/123331643-37797380-d548-11eb-8197-2c001cc2b8f6.png)

3.3.5
rev. 7c6ee03

**Comment by CraftedRO** [comment]
```sql
-- Update Z coords Standing, Large - MFF
DELETE FROM `gameobject` WHERE (`id` = 181300) AND (`guid` IN (17176));
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(17176, 181300, 530, 0, 0, 1, 1, -2035.19, 5275.62, -39.852, 0.541052, 0, 0, 0.267238, 0.96363, 180, 100, 1, '', 0);
```
With those Z coords seems a lot better (tested on c08f086a0272)
Probably this shoud be made with update syntax but meh.

![WoWScrnShot_062521_183359](https://user-images.githubusercontent.com/24683355/123449700-97255c80-d5e4-11eb-924b-f13982456949.jpg)

**Comment by Rushor** [comment]
looks good!

**Comment by offl** [comment]
No sniffs of that object, coords looks sniffed so I'll not touch it for now

**Comment by dr-j** [comment]
Could there be another object missing which is meant to be underneath that box like a table or similar object

**Comment by CraftedRO** [comment]
Proper fix for this, checked on both retail wow and this box is not spawned at all on this event.
```sql
-- Unlink unrelated MFF gamobject
DELETE FROM `game_event_gameobject` WHERE `guid`=17176 AND `eventEntry`=1;
-- Delete unrelated MFF gameobject
DELETE FROM `gameobject` WHERE `id`=181300 AND `guid`=17176;
DELETE FROM `gameobject_addon` WHERE `guid`=17176;
```
WotLK classic PTR 3.4.2.50129
![WoWScrnShot_062423_015639](https://github.com/TrinityCore/TrinityCore/assets/24683355/32eaa65b-5b1d-4577-a537-ba1d30e9ecb9)

Retail 10.1.0.50000
![WoWScrnShot_062423_020352](https://github.com/TrinityCore/TrinityCore/assets/24683355/6b0976fc-aabc-4dd1-b7bc-d3da53d7366f)
