### ISSUE TITLE
[Creature] Numa Cloudsister

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26622]
[Numa Cloudsister](
https://www.wowhead.com/npc=25710/numa-cloudsiste) cannot be found in-game. But it is in the database
Event: Midsummer Fire Festival

**how to rep:**
.go creature id 25710

https://www.wowhead.com/npc=25710/numa-cloudsiste

3.3.5
rev. 7c6ee03

**Comment by Aokromes** [comment]
it was removed on wow 3.x

**Comment by gygyti** [comment]
> 
> 
> it was removed on wow 3.x

are you sure about that? because there is a quest where you need to talk to her

**Comment by offl** [comment]
Looks like she indeed was removed but we need to take care of associated with her quests

**Comment by Aokromes** [comment]
> Looks like she indeed was removed but we need to take care of associated with her quests

there are references of quests being bugged when DF was launched, so blizzlike bug xd

**Comment by offl** [comment]
There's not too much info https://www.wowhead.com/quest=11955/ahune-the-frost-lord#comments:id=1062217:reply=169477
Some people say you can still accept it, some can't accept it
Anyway can't even check right now if she's really not spawned

**Comment by offl** [comment]
That creature wasn't added to 'dungeon finder version of instance'
Associated quests were not removed
