### ISSUE TITLE
[3.3.5a] Segmentation fault on Worldserver [CPP, running on ElunaTrinityWotlk, Custom Boss, Custom instance map]

### ISSUE THREAD

**Issue by Lenzork** [TrinityCore/TrinityCore#26638]
Hey everyone!

I've starting with scripting on a Trinitycore Server and now i'm facing a little bit of a Problem. I've created a **custom boss** and sometimes when you **attack the boss, the whole server crashes**.
The Boss is on a **custom instance map**.

I did the debug thingy where you get a backtrace log and now i don't know about the next Steps. I don't know what files are necessary to upload but i'll upload the backtrace log here. 
It seems to have something to do with the Map i guess because of the `bool IsInWorld() const { return m_inWorld; }` error in the Object.h File?

Also all of the Files are owned by the **Lenzork** User and i'm logged in as the **Lenzork** user when running the Server.
I've heared that you should never run the Server as **root**.

[backtrace_2021-06-27-17_09_08.log](https://github.com/TrinityCore/TrinityCore/files/6721806/backtrace_2021-06-27-17_09_08.log)

The custom Boss Script is a **.cpp file** and **not a .lua file** (wanted to learn scripting with cpp).

I hope to find some help here even if it's running on the ElunaTrinity.

**Comment by Aokromes** [comment]
custom scripts doesn't belongs here, and less without the source code.

**Comment by Jinnaix** [comment]
@Lenzork
Post it in the TrinityCore forum, with your code and potential required sql, so maybe a member of the community can review it and help you.
This issue section is not meant for problems with other people's personal scripts.
