### ISSUE TITLE
[1146] Table 'world.updates_include' doesn't exist

### ISSUE THREAD

**Issue by kazeookami** [TrinityCore/TrinityCore#26635]
**Description:**

Upon launching worldserver.exe I get a series of messages that ends with...
Updating World database...
[1146] Table 'world.updates_include' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

**Expected behaviour:**

I would expect it to proceed towards grabbing maps, but I don't see that happening.

**Steps to reproduce the problem:**

Launch worldserver.exe

**Branch(es):**

Master

**TC rev. hash/commit:** 

Unable to get this far

**Operating system:** 

Windows 10 Pro

**Comment by Aokromes** [comment]
no proper permisions to create world database or broken database.
