### ISSUE TITLE
DB/Creature: Daggerspine Marauder

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26645]
https://tbc.wowhead.com/npc=2775
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2775

Description:
During the [quest](https://tbc.wowhead.com/quest=667/death-from-below), [these nagas](https://tbc.wowhead.com/npc=2775) appear. At some point, they shout to the player: "Daggerspine Marauder yells: You've plundered our treasures too long. Prepare to meet your watery grave!", but in Russian localization they refer to the player by his gender, and, for some reason, the construction **$Gmale:female;** does not work.

![WoWScrnShot_062921_203753](https://user-images.githubusercontent.com/73786888/123843799-f522ae80-d91a-11eb-913f-c68ab2c606b1.jpg)

Following the advice of **offl** (ref. https://github.com/TrinityCore/TrinityCore/commit/189f8137f5231e96732b8516604042003888c312 and https://github.com/TrinityCore/TrinityCore/issues/26629), I tried to apply these two fixes in turn:

```
UPDATE `world`.`smart_scripts` SET `target_type`='7' WHERE  `entryorguid`=2775 AND `source_type`=0 AND `id`=0 AND `link`=0;
```
and
```
UPDATE `world`.`smart_scripts` SET `target_type`='23' WHERE  `entryorguid`=2775 AND `source_type`=0 AND `id`=0 AND `link`=0;
```

But then these nagas would stop talking altogether in both cases.

Expected behaviour:
Construction **$Gmale:female;** must work correctly in languages other than English.

Branch:
3.3.5

TC rev. hash/commit: https://github.com/TrinityCore/TrinityCore/commit/c08f086a02729f3b7e4c99f4741063e45301ebf8

TrinityCore rev. 2021-06-25 18:43:42 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by offl** [comment]
We don't have both entirely correct and not complicated solution for this
Try with
```sql
--
UPDATE `smart_scripts` SET `action_param3` = 1, `target_type` = 21, `target_param1` = 100 WHERE `entryorguid` = 2775 AND `source_type` = 0 AND `id` = 0;
```

**Comment by Freeman256** [comment]
Yes it worked! Construction **$Gmale:female;** works correctly in this case. As always, thanks for your help, **offl**!
