### ISSUE TITLE
[Item] Shards of Ahune

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26641]
**How it must:**
**Shards of Ahune** should drop from **Ice Chest**

**How it now:**
now it doesn't drop out at all 

https://github.com/TrinityCore/TrinityCore/issues/2290
https://www.wowhead.com/item=35723/shards-of-ahune
https://www.wowhead.com/object=188192/ice-chest
https://www.wowhead.com/object=187892/ice-chest

3.3.5
rev. 7c6ee03

**Comment by Aokromes** [comment]
they drop
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=35723/shards-of-ahune
idk why it's marked not available to players, but it does.

**Comment by CraftedRO** [comment]
6c5b641dd44a - this shard dropped first time I tried the boss on my human dk , so I can tell you they definetly does drop.
