### ISSUE TITLE
[Item] Satchel of Chilled Goods

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26640]
**How it must:**
The problem is that these **Emblem of Frost** must be in the **Satchel of Chilled Goods**. If I'm not mistaken, there should be 2 pieces.

**How it now:**
now it doesn't fall out at all 

https://www.wowhead.com/item=54536/satchel-of-chilled-goods#english-comments
https://www.wowhead.com/item=49426/emblem-of-frost#
https://web.archive.org/web/20110625082910/http://www.wowhead.com/item=54536/satchel-of-chilled-goods

![изображение](https://user-images.githubusercontent.com/77268574/123555548-1b1b4800-d78f-11eb-9684-b643b6b8ada2.png)

3.3.5
rev. 7c6ee03

**Comment by offl** [comment]
Where are those comments?

**Comment by gygyti** [comment]
> 
> 
> Where are those comments?

On https://web.archive.org/web/20110625082910/http://www.wowhead.com/item=54536/satchel-of-chilled-goods
