### ISSUE TITLE
[Quest] Tremors of the Earth

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26656]
### Description

after activating the stone, dragons do not appear 

### Expected behaviour

after activating the stone, there should appear **Hematus** and **Blacklash**

https://classic.wowhead.com/quest=732/tremors-of-the-earth
https://classic.wowhead.com/npc=2759/hematus
https://classic.wowhead.com/npc=2757/blacklash

### Steps to reproduce the problem

1 .quest add 717
2. try to complete the quest by getting stones

### Branch

3.3.5

### TC rev. hash/commit

7c6ee03

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by offl** [comment]
Should be fixed by 338abd531556822d17924025f6d460a3fd9899a2
You're using too old rev
