### ISSUE TITLE
[MASTER] New undead character unplayable

### ISSUE THREAD

**Issue by polpygamer** [TrinityCore/TrinityCore#26660]
### Description

I just compiled the latest master, fresh new mysql and client 9.0.5.38556 and fresh new extracted maps etc...

I created an undead, and it's unplayable at all, second quest, i cannot loot the object.

When i try to attack an enemy, my shadow attach pass through the enemy without damages, the enemy comes to me and kill me in one shot.

In worldserver, i can see a lot of strange messages (See some sample examples :)

<details>

npc_spellclick_spells: Creature template 170609 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 170889 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171180 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171262 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171336 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171344 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171510 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171598 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 171829 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing flag
npc_spellclick_spells: Creature template 172051 has UNIT_NPC_FLAG_SPELLCLICK but no data in spellclick table! Removing f

Loading World locations...
World location (ID: 1851) has a invalid position MapID: 734 X: -9169.86 Y: 1604.42 Z: 26.8352 O: 5.61948, skipped
World location (ID: 2815) has a invalid position MapID: 930 X: -2726.95 Y: -4716.71 Z: 5.51685 O: 2.27435, skipped
World location (ID: 3549) has a invalid position MapID: 999 X: -3813.67 Y: -4790.98 Z: 10.5307 O: 4.8345, skipped
World location (ID: 3671) has a invalid position MapID: 1007 X: 199.876 Y: 125.346 Z: 138.43 O: 4.10621, skipped
World location (ID: 4002) has a invalid position MapID: 951 X: 4217.19 Y: 7122.15 Z: 271.079 O: 0, skipped
World location (ID: 4027) has a invalid position MapID: 1005 X: 2209.25 Y: -1255.13 Z: 428.04 O: 2.5145, skipped
World location (ID: 4066) has a invalid position MapID: 1014 X: 4014.17 Y: 1776.21 Z: 884.994 O: 5.1058, skipped
World location (ID: 4083) has a invalid position MapID: 1024 X: 2009.54 Y: -2040.32 Z: 221.069 O: 0.0749006, skipped
World location (ID: 4094) has a invalid position MapID: 1008 X: 3861.56 Y: 1045.11 Z: 490.073 O: 6.06062, skipped
World location (ID: 4108) has a invalid position MapID: 1030 X: 899.104 Y: 2353.91 Z: 97.5621 O: 2.71381, skipped
World location (ID: 4109) has a invalid position MapID: 1029 X: 780.592 Y: 2354.83 Z: 90.0521 O: 3.6718, skipped
World location (ID: 4133) has a invalid position MapID: 1035 X: 1781.57 Y: 1569.53 Z: 23.3288 O: 2.22003, skipped
World location (ID: 4144) has a invalid position MapID: 996 X: -1020.88 Y: -3153.09 Z: 28.8941 O: 1.03791, skipped
World location (ID: 4153) has a invalid position MapID: 1048 X: -2757.07 Y: 629.278 Z: 1.1671 O: 4.12341, skipped
World location (ID: 4155) has a invalid position MapID: 1014 X: 3823.02 Y: 2008.73 Z: 935.205 O: 4.42046, skipped
World location (ID: 4249) has a invalid position MapID: 1049 X: 1513.28 Y: 5352.51 Z: 146.241 O: 3.9043, skipped
World location (ID: 4250) has a invalid position MapID: 1050 X: -1437.23 Y: 3934.49 Z: 6.51026 O: 1.03778, skipped
World location (ID: 4251) has a invalid position MapID: 1048 X: -3101.01 Y: 729.672 Z: 0.747235 O: 0, skipped
World location (ID: 4252) has a invalid position MapID: 1051 X: 1736.45 Y: 302.59 Z: 475.886 O: 2.38725, skipped

Failed to load dungeon The Frozen Throne (Id: 1215), cant find areatrigger for map 1480
Failed to load dungeon Where the Hammer Falls (Id: 1221), cant find areatrigger for map 1503
Failed to load dungeon The Voice of Thunder (Id: 1222), cant find areatrigger for map 1526
Failed to load dungeon Thunder of the Titans (Id: 1234), cant find areatrigger for map 1495
Failed to load dungeon The Prison of Ink (Id: 1961), cant find areatrigger for map 2178
Failed to load dungeon Shadowgore Citadel (Id: 1240), cant find areatrigger for map 1607
Failed to load dungeon The Nexus Vault (Id: 1241), cant find areatrigger for map 1583
Failed to load dungeon Claiming the Truthguard (Id: 1242), cant find areatrigger for map 1495
Failed to load dungeon Darkbough (Id: 1287), cant find areatrigger for map 1520
Failed to load dungeon Rift of Aln (Id: 1289), cant find areatrigger for map 1520
Failed to load dungeon Rescue Koltira (Id: 1295), cant find areatrigger for map 1617
Failed to load dungeon The Violet Hold (Id: 1297), cant find areatrigger for map 1494
Failed to load dungeon Battle for the Exodar (Id: 1299), cant find areatrigger for map 1624
Failed to load dungeon Freehold (Id: 1672), cant find areatrigger for map 1754

Table `instance_encounters` has an invalid encounter id 297, skipped!
Table `instance_encounters` has an invalid encounter id 298, skipped!
Table `instance_encounters` has an invalid encounter id 299, skipped!
Table `instance_encounters` has an invalid encounter id 300, skipped!
Table `instance_encounters` has an invalid encounter id 301, skipped!
Table `instance_encounters` has an invalid encounter id 302, skipped!
Table `instance_encounters` has an invalid encounter id 303, skipped!
Table `instance_encounters` has an invalid encounter id 304, skipped!
Table `instance_encounters` has an invalid encounter id 305, skipped!
Table `instance_encounters` has an invalid encounter id 306, skipped!
Table `instance_encounters` has an invalid encounter id 314, skipped!
Table `instance_encounters` has an invalid encounter id 315, skipped!

Table 'gameobject_loot_template' Entry 8919 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 8920 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9199 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9239 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9240 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9241 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9242 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9597 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 9936 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 10101 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 10102 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 11103 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 11121 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 11160 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 11460 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 11626 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 12260 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'gameobject_loot_template' Entry 12810 isn't gameobject entry and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 343804 does not exist but it is used by Spell 343804
Table 'spell_loot_template' Entry 343806 does not exist but it is used by Spell 343806
Table 'spell_loot_template' Entry 343807 does not exist but it is used by Spell 343807
Table 'spell_loot_template' Entry 343808 does not exist but it is used by Spell 343808
Table 'spell_loot_template' Entry 343809 does not exist but it is used by Spell 343809
Table 'spell_loot_template' Entry 344041 does not exist but it is used by Spell 344041
Table 'spell_loot_template' Entry 344247 does not exist but it is used by Spell 344247
Table 'spell_loot_template' Entry 345576 does not exist but it is used by Spell 345576
Table 'spell_loot_template' Entry 349924 does not exist but it is used by Spell 349924
Table 'spell_loot_template' Entry 60445 isn't spell id (random item creating) and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 61177 isn't spell id (random item creating) and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 61288 isn't spell id (random item creating) and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 61500 isn't spell id (random item creating) and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 95399 isn't spell id (random item creating) and not referenced from loot, and thus useless.
Table 'spell_loot_template' Entry 95406 isn't spell id (random item creating) and not referenced from loot, and thus useless.
>> Loaded 484 spell loot templates in 166 ms
Loading reference loot templates...
Table 'reference_loot_template' Entry 24709 Item 14480: item does not exist - skipped
Table 'reference_loot_template' Entry 24709 Item 14495: item does not exist - skipped
Table 'reference_loot_template' Entry 10100 Item 1364: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1366: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1367: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1368: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1369: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1370: equal-chanced grouped entry, but group not defined - skipped
Table 'reference_loot_template' Entry 10100 Item 1372: equal-chanced grouped entry, but group not defined - skipped

Scriptname: `spell_item_piccolo_of_the_flaming_fire` spell (Id: 17512) does not exist.
Scriptname: `spell_gen_mixology_bonus` spell (Id: 17629) does not exist.
Scriptname: `spell_pal_blessing_of_might` spell (Id: 19740) does not exist.
Scriptname: `spell_pal_blessing_of_kings` spell (Id: 20217) does not exist.
Scriptname: `spell_pri_shadow_protection` spell (Id: 27683) does not exist.
Scriptname: `spell_midsummer_test_ribbon_pole_channel` spell (Id: 29705) does not exist.
Scriptname: `spell_midsummer_test_ribbon_pole_channel` spell (Id: 29727) does not exist.
Scriptname: `spell_gen_interrupt` spell (Id: 32748) does not exist.
Scriptname: `spell_dru_idol_lifebloom` spell (Id: 34246) does not exist.
Scriptname: `spell_item_mana_drain` spell (Id: 40336) does not exist.
Scriptname: `spell_gen_mixology_bonus` spell (Id: 42735) does not exist.
Scriptname: `spell_dru_living_seed_proc` spell (Id: 48504) does not exist.
Scriptname: `spell_rog_honor_among_thieves` spell (Id: 51701) does not exist.
Scriptname: `spell_warr_vigilance_redirect_threat` spell (Id: 59665) does not exist.
Scriptname: `spell_gen_mixology_bonus` spell (Id: 60345) does not exist.
Scriptname: `spell_dru_idol_lifebloom` spell (Id: 60779) does not exist.
Scriptname: `spell_gen_profession_research` spell (Id: 61177) does not exist.

</details>

### Expected behaviour

Working and playable

### Steps to reproduce the problem

- create undead demon
- accept the fsecond quest
- go to the crypt and try to grab the 2 quests objects (empty when trying to loot)
-  try to attach an ennemy

### Branch

master

### TC rev. hash/commit

3aaab1f8780130b706d153a6cad3f0cdbb792489

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by funjoker** [comment]
There is probably no scaling data defined, also the classes have no correct class level stats yet(which can lead to far less HP and Damage on your character than expected).

BTW: create undead demon <--- do you mean warlock? :D

**Comment by funjoker** [comment]
PS: master is like an experimental build atm (not enough people to fix it)
But thank you for your issue, it helps us tracking missing stuff.

Can you please add the commit you are on, if it is a fresh master it should me 3aaab1f8780130b706d153a6cad3f0cdbb792489 .
Is this correct?

**Comment by polpygamer** [comment]
Hello, yes, i mean warlock, sorry :)

It's a fresh latest MASTER, actually 3aaab1f  and running TDB 905.21071 as new DB script

**Comment by tails2k** [comment]
> 
> 
> PS: master is like an experimental build atm (not enough people to fix it)
> But thank you for your issue, it helps us tracking missing stuff.
> 
> Can you please add the commit you are on, if it is a fresh master it should me [3aaab1f](https://github.com/TrinityCore/TrinityCore/commit/3aaab1f8780130b706d153a6cad3f0cdbb792489) .
> Is this correct?

I can Post many more errors in Master. Also the enemys in Trisfal have a wrong level. Levels are at 30 and more, for a fresh char with level 5 not too good :D

**Comment by MaxtorCoder** [comment]
> > 
> > 
> > PS: master is like an experimental build atm (not enough people to fix it)
> > But thank you for your issue, it helps us tracking missing stuff.
> > 
> > Can you please add the commit you are on, if it is a fresh master it should me [3aaab1f](https://github.com/TrinityCore/TrinityCore/commit/3aaab1f8780130b706d153a6cad3f0cdbb792489) .
> > Is this correct?
> 
> I can Post many more errors in Master. Also the enemys in Trisfal have a wrong level. Levels are at 30 and more, for a fresh char with level 5 not too good :D

Read his first message, TC is missing scaling for NPCs and class stat data.

**Comment by funjoker** [comment]
can someone test it after c12ef1b830e90a226ed3a8ff8d26077230a77494

**Comment by funjoker** [comment]
Can someone test it after 2e582e63e88c25e89666ebccfa1dbd897dbdd0fc

**Comment by TQPS** [comment]
Scaling works great in Northshire from what I've tested, but the issue of not being able to loot is still there.

<details>

![image](https://user-images.githubusercontent.com/66294837/130156078-683f17e9-bbba-4a0f-9f40-da0f339f488f.png)

</details>

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/26853

**Comment by kruchor** [comment]
The loot box appears but it is empty, so quest item can't be picked up !

TC>server debug
TC>Table `command` contains a non-existing subcommand 'ticket' in command 'go ticket', skipped.
TrinityCore rev. 832409e51205 2021-12-14 00:18:59 +0100 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 10.3.32-MariaDB
Using CMake version: 3.16.3
Compiled on: Linux 5.4.157-1-pve
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8086
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 1451755434 bytes
vmaps directory located in ../data/vmaps. Total size: 3361827257 bytes
mmaps directory located in ../data/mmaps. Total size: 11873591812 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR
Using World DB: TDB 915.21111
