### ISSUE TITLE
display of passenger on mount (ie travelers tundra mammoth) fails if passenger mounts from another mount

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#26675]
### Description

if someone mounts on travelers tundra mammoth while it's riding another mount he is not show on mount

### Expected behaviour

passenger is show on travelers tundra mammoth (or any mount with seats)

### Steps to reproduce the problem

make a party with 2 persons
one summons travelers tundra mammoth
another mounts any single seat mount
kick vendors from travelers tundra mammoth
mount on travelers tundra mammoth with the 2nd person
notice the passenger is show unmounted.

### Branch

3.3.5

### TC rev. hash/commit

b15359a1e2be

### Operating system

debian 10 x64

### Custom changes

xmorg, telenpc

**Comment by Faq** [comment]
That other player who mounted, sees himself on seat, right?
then it is same https://github.com/TrinityCore/TrinityCore/issues/20136
