### ISSUE TITLE
[3.3.5 DB/Quest] Incorrect display of Russian text during the quest "Tomb of the Lightbringer" (9446)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26715]
### Description

During quest [Tomb of the Lightbringer](https://tbc.wowhead.com/quest=9446/tomb-of-the-lightbringer), the ghost of Uther the Lightbringer appears. In Russian version of the game this ghost speaks to the player by gender, but for some reason, construction **$Gmale:female;** does not work. This happens in both of Uther's phrases. See screenshots below for clarity.

![WoWScrnShot_071721_102143](https://user-images.githubusercontent.com/73786888/126030234-c14e65da-218e-40e7-b562-843294db8683.jpg)
![WoWScrnShot_071721_102151](https://user-images.githubusercontent.com/73786888/126030236-370f1803-3e81-453b-914e-50576d577c9b.jpg)

### Expected behaviour

In both of Uther's phrases, **$Gmale:female;** should work correctly in Russian version of the game.

### Steps to reproduce the problem

1. Launch the Russian version of the game;
2.  Create an alliance character;
3. **.character level 55**;
4. Head to Chillwind Camp in Western Plaguelands;
5. Take quest [Tomb of the Lightbringer](https://tbc.wowhead.com/quest=9446/tomb-of-the-lightbringer) from [Anchorite Truuen](https://tbc.wowhead.com/npc=17238/anchorite-truuen);
6. Escort Anchorite Truuen to Uther's tomb;
7. Observe the appearance of Uther's ghost, and then how **$Gmale:female;** does not work in the Russian version;
8. Get upset, because from the words of the **offl**, there is no universal solution to such problems.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a47926ceab7091dd0c06b6bb16a0d1f64bd30a63
TrinityCore rev. 2021-07-16 ‏‎18:51:35 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by Shauren** [comment]
Did you just put `$Gmale:female;` translated into russian to that text?

**Comment by Freeman256** [comment]
This text is already in the database. Just completing this quest I noticed this problem. **Offl** told me that this problem occurs when the creature has been summoned by the player. I have reported a similar issue before: https://github.com/TrinityCore/TrinityCore/issues/26645 and https://github.com/TrinityCore/TrinityCore/issues/26629#issuecomment-869051571.

**Comment by offl** [comment]
It occurs when creature says to itself and not to player
There are many reasons why creature usually does not use player as target

**Comment by Faq** [comment]
But I doubt the same way it is on blizz, so either text is wrong or npc is checking player and talks accordingly.
