### ISSUE TITLE
3.3.5 Cannot add points to Corruption with warlocks

### ISSUE THREAD

**Issue by polpygamer** [TrinityCore/TrinityCore#26714]
### Description

3.3.5 Cannot add points to Corruption with warlocks

When i want to assign points and click on Corruption icon, nothing happen, it worked first time i added points, but not anymore.

### Expected behaviour

Assign corruption points

### Steps to reproduce the problem

Try to assign more than 1 point to corruption for a warlock undead

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) 

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
"add points to Corruption with warlocks"  ????

**Comment by polpygamer** [comment]
![WoWScrnShot_071721_091843](https://user-images.githubusercontent.com/87237612/126032139-d82c6a85-2208-4448-8858-6410d853650b.jpg)

**Comment by offl** [comment]
Unspent Talents: 0

**Comment by polpygamer** [comment]
OMG, just saw that, i was watching at the opposite, i think i had 3 points to assign

This can be closed as lame newbie ticket :)

Issue was between the keyboard and the chair

**Comment by polpygamer** [comment]
Unspent Talents: 0
With Unspent Talents: > 0 you still can't add more points?

**Comment by jackpoz** [comment]
Glad to see it worked out all well 😃
