### ISSUE TITLE
Can't load some mmap

### ISSUE THREAD

**Issue by SimonChenyongxing** [TrinityCore/TrinityCore#26713]
### Description

When I login into game, I stopped at the logining view after the progess. Others can see me in the game. 
On the server console, I got some info, it is output from here:
TC_LOG_WARN("mmaps.tiles", "Could not load MMAP name:%s, id:%d, x:%d, y:%d (mmap rep.: x:%d, y:%d)", GetMapName(), GetId(), gx, gy, gx, gy);

In other case,my friend stopped entering one dungeon.

### Expected behaviour

client should login into the game

### Steps to reproduce the problem

no

### Branch

3.3.5

### TC rev. hash/commit

no

### Operating system

Windows 7 x64

### Custom changes

 transmog patch and npcbot

**Comment by MaxtorCoder** [comment]
Fill in issue template. Filling in `no` under some parts is not how this works.

**Comment by jackpoz** [comment]
>TC_LOG_WARN("mmaps.tiles", "Could not load MMAP name:%s, id:%d, x:%d, y:%d (mmap rep.: x:%d, y:%d)", GetMapName(), GetId(), gx, gy, gx, gy);

You assume that has any link to your issue, but it doesn't.
Spend some time to fill the template.
Try without any custom patches first.
