### ISSUE TITLE
NPC ID#17606 Does not contain a quest item in drop.

### ISSUE THREAD

**Issue by Willozwisp** [TrinityCore/TrinityCore#26712]
### Description

https://wowhead.com/npc=17606  - NPC
https://wowhead.com/item=23873 - Quest Item

### Expected behaviour

Drop item=23873 5%, but I never got it, having killed 17606 at the same time

### Steps to reproduce the problem

1. We take a quest: https://wowhead.com/quest=9579
2. We go to kill the necessary mobs: https://wowhead.com/npc=17606
3. No required item in drop: https://wowhead.com/item=23873

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. baaa0b55228a 2021-06-24 02:08:18 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) 

### Operating system

Win 10 x64

### Custom changes

none

**Comment by Aokromes** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23873
the item is on db

**Comment by offl** [comment]
Not a bug https://www.wowhead.com/item=23873/galaens-amulet#comments:id=996565 (and tens of comments below and above)
Changing chance to 100 made it drop so it can drop with current chance

**Comment by Faq** [comment]
It is only 4% drop chance, so might that Your luck runt out. Keep trying mate.

**Comment by Willozwisp** [comment]
oh..
