### ISSUE TITLE
DEV/DB: SMART_ACTION_WP_START reactState param

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#26728]
### Description

I'm going to remove reactState param of SMART_ACTION_WP_START. If react state indeed should be changed when creature starts waypoint, I'll change it in separate SMART_ACTION_SET_REACT_STATE and change reactState param to 3. If it should not be changed, reactState param will be changed to 3 without additional changes
When reactState param will be changed to 3 in all 855 actions, we'll remove that param completely
These changes can break some scripts or make them buggy because I can't always know if react state of those 550 creatures which were made defensive and passive should really be changed or not

### Expected behaviour

none

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

60379cf2c15d9cee1414fbaec2b217b89b8dc67e

### Operating system

Win 8.1

### Custom changes

none

**Comment by offl** [comment]
I knew it will end like this. Removed the rest without checking code, with no doubt breaks some things. Will be fixed when reported. Any way I already removed accidentally passive react state of all vehicles with waypoints. What a waste of free time of 2 weeks. Literally same result as if I removed it without checking something.

This is probably the most dumbest thing I've ever seen and here's why.
1. In nearly all cases you don't need to change react state at all when creature starts waypoint. However it was changed in 550 cases(out of 850) to defensive or passive.
2. You can't skip react state change, best you can do is use aggressive react state, that's how it works. 0 is not DO NOTHING but REACT_PASSIVE. In escort quests if creature changes faction before waypoint is loaded, original react state from faction will be fucked up. Even if you change it to closest to faction react state, it will override react state from faction in a weird way.
3. There's no such thing as action to change react state to defensive, there's no even such thing as change react state because we use pet react states which are supposed to be used for pets and vehicles and not for every single creature. There is a flag which acts like passive react state but it too has nothing to do with react states.

**Comment by CraftedRO** [comment]
So in a few words, you wasted two weeks to break some of 550 cases (because you think they were hacks), ** instead of focusing on already existing issues **, yea it sound legit.

**Comment by CraftedRO** [comment]
So in a few words, you wasted two weeks to break some of 550 cases (because you think they were hacks), **instead of focusing on already existing issues**, yea it sound legit.

**Comment by offl** [comment]
Where do you see the word 'hack'?
It's not a hack, but a mistake someone made when that param was implemented years ago. It's not needed but in nearly all cases it breaks stuff and to remove it you need to spent a lot of time or break some things or both. Common practice in such cases is remove everything without trying to adjust scripts. I tried to figure out how to do it harmless and turned out it was way much easier to stick to common practice and burn it without adjusting scripts(which is needed in less than 50-70 cases) or checking hundreds of cases.

**Comment by CraftedRO** [comment]
but instead why don't we were waiting for people to come with issues about existent "mistaken" ones and change only them then ?

**Comment by CraftedRO** [comment]
but instead why don't we better just waiting for people to come with issues about existent "mistaken mades" ones and change only them then ?

**Comment by offl** [comment]
Because it's not common practice?
