### ISSUE TITLE
DK/Talent Necrosis doesn't works with off-hand weapons (dual wield)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26722]
### Description

[Necrosis](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51465) doesn't works on off-hand weapons (dual wield) white damage.

https://user-images.githubusercontent.com/24683355/126079583-600298b1-0801-4434-9910-8ed51819adf8.mp4

### Expected behaviour

Most likely [Necrosis](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51465) shoud work on off-hand weapons (dual wield) white damage too.

few links about its behaviour : [source1](https://www.mmo-champion.com/threads/678187-Necrosis-vs-BCB-for-3-3-unholy) [source2](https://www.wowhead.com/forums/topic/can-someone-explain-the-talent-necrosis-37489)

### Steps to reproduce the problem

Select [Necrosis](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51465) talent 5/5 then equip just off hand weapon and do some damage , notice it won't proc .
While similar talent [Blood-Caked Blade](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=49628) will proc .

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 2a8ff02cfbf1 2021-07-17 21:56:46 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by r4d1sh** [comment]
Damaging spell of this talent ([Necrosis (51460)](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51460)) requires main-hand weapon. More proofs is needed that the talent worked without main-hand weapon on retail.

**Comment by Shauren** [comment]
I don't think this is a bug, spell has `SPELL_ATTR3_MAIN_HAND` in dbc

**Comment by CraftedRO** [comment]
I guess you are right then.
