### ISSUE TITLE
Texts: Multiple creatures does not use player as target for talk action

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26727]
### Description

Multiple creatures does not use player as target for talk action, as result $G in locale texts is not displayed correctly, see screenshot below. See https://github.com/TrinityCore/TrinityCore/issues/26718#issuecomment-882054282 for more info

<details>

![WoWScrnShot_071921_185316](https://user-images.githubusercontent.com/73786888/126191523-6f4324c6-2b50-4cc8-96d2-26be1e187ccc.jpg)

</details>

List of creatures:

- [ ] #26715
- [ ] #26716
- [ ] #26718
- [ ] 18622
- [ ] 22314
- [ ] 19578
- [ ] 19534
- [x] 25773
- [ ] 23678
- [ ] 24035
- [ ] 26605

### Expected behaviour

Creature should use player as target \ player's guid for talk action

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a47926ceab7091dd0c06b6bb16a0d1f64bd30a63
TrinityCore rev. 2021-07-16 ‏‎18:51:35 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. Quest - [Missing Friends](https://tbc.wowhead.com/quest=10852/missing-friends) NPC - [Captive Child](https://tbc.wowhead.com/npc=22314/captive-child)

![WoWScrnShot_072421_180601](https://user-images.githubusercontent.com/73786888/126872811-75742115-1a4b-44ed-bd6f-af1aaf8c3278.jpg)
![WoWScrnShot_072421_180635](https://user-images.githubusercontent.com/73786888/126872812-5aa5816d-f5fe-43a0-bfdf-4e520bdc7b53.jpg)

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. Quest - [Mark V is Alive!](https://www.wowhead.com/quest=10191/mark-v-is-alive), NPC - [Bot-Specialist Alley](https://www.wowhead.com/npc=19578/bot-specialist-alley).

![WoWScrnShot_080121_194850](https://user-images.githubusercontent.com/73786888/127779298-e715227b-0106-4c31-8b82-8733295ab391.jpg)
![WoWScrnShot_080121_195650](https://user-images.githubusercontent.com/73786888/127779299-e960061b-f1d7-4571-93b2-e0c333124b46.jpg)

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. NPC - [Dealer Digriz](https://www.wowhead.com/npc=19534/dealer-digriz).

![WoWScrnShot_080721_145141](https://user-images.githubusercontent.com/73786888/128599249-5e0176ee-d33d-4574-83aa-4c470fa1b00f.jpg)

**Comment by Freeman256** [comment]
I met an NPC with a similar problem, only this time $C does not work. NPC - [Fizzcrank Survivor](https://www.wowhead.com/npc=25773/fizzcrank-survivor), quest - [Re-Cursive](https://www.wowhead.com/quest=11712/re-cursive). 

![WoWScrnShot_080921_194248](https://user-images.githubusercontent.com/73786888/128744177-98dfa8d9-9b80-4ff6-a5de-f3702e07a54e.jpg)

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. NPC - [Chill Nymph](https://www.wowhead.com/npc=23678/chill-nymph). Quest - [The Fallen Sisters](https://www.wowhead.com/quest=11314/the-fallen-sisters).

Name: Chill Nymph
SpawnID: 107542, current GUID low: 625.
Entry: 23678.
![WoWScrnShot_081621_193308](https://user-images.githubusercontent.com/73786888/129598380-1df0372d-8c15-4531-8181-b9a4e089e690.jpg)

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. NPC - [Gjalerbron Prisoner](https://www.wowhead.com/npc=24035/gjalerbron-prisoner). Quest - [Of Keys and Cages](https://www.wowhead.com/quest=11231/of-keys-and-cages).
See screenshot and chat window.
![WoWScrnShot_081821_203859](https://user-images.githubusercontent.com/73786888/129946218-bc8871a4-d270-40c5-87e2-612c54731f85.jpg)

**Comment by Freeman256** [comment]
I met another NPC, which does not work with the structure $G. NPC - [Anub'ar Underlord](https://www.wowhead.com/npc=26605/anubar-underlord). This NPC appears when the player approaches the meeting stone near the entrance to the Azjol-Nerub instance.

![WoWScrnShot_082221_112941](https://user-images.githubusercontent.com/73786888/130347968-981a3faa-c5f2-4640-b0d2-386495178ab5.jpg)
![WoWScrnShot_082221_112958_1](https://user-images.githubusercontent.com/73786888/130347971-8df1e642-fbb2-4b69-bdb1-bbc866074b2a.jpg)

**Comment by CraftedRO** [comment]
@Freeman256 there's no text in creature_text_locale for https://github.com/TrinityCore/TrinityCore/issues/26727#issuecomment-899652367 but you can try this and see if smth changed:
```sql
--
UPDATE `smart_scripts` SET `action_param3`=1 WHERE `entryorguid`=2367800 AND `source_type`=9 AND `id`=2;
```
