### ISSUE TITLE
Server Crash - GetUnitOwner ASSERTION FAILED creature(3733)

### ISSUE THREAD

**Issue by madixi** [TrinityCore/TrinityCore#26731]
### Description

Server crash when Forsaken Herbalist (npc 3733) attacks player
The server crashes, it shows this message on the screen:
[...]/TrinityCore/src/server/game/Spells/Auras/SpellAuras.h:141 in GetUnitOwner ASSERTION FAILED:
  GetType() == UNIT_AURA_TYPE
Segmentation fault

### Expected behaviour

Not crash

### Steps to reproduce the problem

Create a new character, skip intro if you want

.modify hp 50000000
.go creature id 3733

wait for attack

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 3aaab1f87801+ 2021-07-05 16:45:29 +0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04.2 LTS 

### Custom changes

None

**Comment by Faq** [comment]
Where is the crashlog?

**Comment by madixi** [comment]
It is all:
```
[...]/TrinityCore/src/server/game/Spells/Auras/SpellAuras.h:141 in GetUnitOwner ASSERTION FAILED:
GetType() == UNIT_AURA_TYPE
Segmentation fault
```

**Comment by Ovahlord** [comment]
Post the whole crashlog. Not just a snippet.

**Comment by madixi** [comment]
There is full log from start worldserver till crush:
[issue_26731.log](https://github.com/TrinityCore/TrinityCore/files/6855942/issue_26731.log)

**Comment by Shauren** [comment]
You should be using gdb to capture the crash log. Server log is something else and most of the time not relevant for crash issues

**Comment by madixi** [comment]
Dump from gdb:
`Received not handled opcode [CMSG_BATTLE_PET_REQUEST_JOURNAL_LOCK 0x3622 (13858)] from [Player: Проба Player-1-00000011, Account: 1]
Received not handled opcode [CMSG_GET_LANDING_PAGE_SHIPMENTS 0x330D (13069)] from [Player: Проба Player-1-00000011, Account: 1]

/mnt/ext/trinity/TrinityCore/src/server/game/Spells/Auras/SpellAuras.h:141 in GetUnitOwner ASSERTION FAILED:
  GetType() == UNIT_AURA_TYPE

Thread 8 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1d47700 (LWP 169158)]
Trinity::Assert (file=<optimized out>, line=<optimized out>, function=<optimized out>, message=<optimized out>)
    at /mnt/ext/trinity/TrinityCore/src/common/Debugging/Errors.cpp:42
42	    *((volatile int*)nullptr) = 0;
(gdb) 
`

**Comment by Shauren** [comment]
That is as useless as server log - please follow the guide on how to get a crash log from the wiki

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130173/GDB

Something like this (crashreport.gdb is this file https://github.com/TrinityCore/TrinityCore/blob/master/contrib/debugger/crashreport.gdb)
`gdb worldserver -x contrib/debugger/crashreport.gdb`

**Comment by madixi** [comment]
gdb crashreport:
[backtrace_26731.log](https://github.com/TrinityCore/TrinityCore/files/6856257/backtrace_26731.log)

**Comment by Shauren** [comment]
That is much better, thanks

**Comment by madixi** [comment]
Commit don't resolve problem
[backtrace_515d3da.log](https://github.com/TrinityCore/TrinityCore/files/6860370/backtrace_515d3da.log)

**Comment by Aokromes** [comment]
> Commit don't resolve problem
> [backtrace_515d3da.log](https://github.com/TrinityCore/TrinityCore/files/6860370/backtrace_515d3da.log)

if you realize it's totally different error.

**Comment by madixi** [comment]
Thank you, I have made a new issue

**Comment by Shauren** [comment]
That is a different stack trace, 2nd separate crash
