### ISSUE TITLE
Stratholme: Portcullis Trap

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26738]
### Description

As you pass under the first portcullis in Stratholme on the way to live, it does not close, and the mobs do not spawn.

### Expected behaviour

Each time you pass through here during a run or re-entry to the instance, both portcullis gates close shut, trapping those inside and a bunch of little maggots spawn. Once the mobs have been disposed of the portcullis opens up again.

If you run back via this way, it does not re-close.

If you exit and re-enter the instance (example dying), it will re-close and spawns re-occur.

### Steps to reproduce the problem

1. Enter Stratholme
2. Run to live 
3. Pass under first portcullis on the way
4. Does not close, remains open and nothing occurs

<details>

Image 

![image](https://user-images.githubusercontent.com/66294837/126759073-45d0100b-122a-4e90-8ef1-3cd53680b1c7.png)
</details>

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
To make it more clear, it's about https://github.com/classicdb/database/issues/631
> The trap gates do not trigger. Video of current core: https://youtu.be/4u3Hpdq44Pc Video of working trap gates: https://youtu.be/--IiC_Wuxfg?t=411

**Comment by 14shagov** [comment]
I apologize for cluttering up the place with pull requests. I didn't immediately understand how it worked.

Based on cmangos/mangos-classic@eb8bf25.
I made 14shagov/TrinityCore@3aa6191.

The mechanics are almost the same as you described, but there is a difference - if one and only one of the traps is triggered, both traps are deactivated after opening the doors. I don't know how critical this is.
Also, if all enemies are not killed within two minutes, the doors will open on their own.
If there are any comments, I'd be glad to hear them.

One more thing, as described in classicdb/database#631, there is no area_trigger set for these traps on map 329, so the trap will check every 30 seconds if someone is around. The rest of the time it will be deactivated.
I don't know if there is any way to fix this other than increasing the frequency of checking.

**Comment by Aokromes** [comment]
75e38a5d8f739358421ca5eece7e3701f6b8d190
