### ISSUE TITLE
[3.3.5] DB/Creature Ramdor the Mad Missing greeting text in quest_greeting table

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26746]
### Description

[Ramdor the Mad](https://tbc.wowhead.com/npc=19417/ramdor-the-mad) does not have a greeting text in Russian. I used command **.npc info** to find out his entry id, then I started looking for his greeting text in the **quest_greeting** table to translate it and create a matching row in the **quest_greeting_locale** table, but I couldn't find his greeting.

![WoWScrnShot_072421_182855](https://user-images.githubusercontent.com/73786888/126873548-559f4914-f1f4-46ac-87e2-dbd1c4e45092.jpg)

### Expected behaviour

[Ramdor the Mad](https://tbc.wowhead.com/npc=19417/ramdor-the-mad) should have a greeting text in Russian (but I'll do it myself), and should also have a greeting text in English in the **quest_greeting** table like all other NPCs. 

### Steps to reproduce the problem

1. Play the Russian version of the game;
2. Travel to Auchindoun in Terokkar Forest and speak with [Ramdor the Mad](https://tbc.wowhead.com/npc=19417/ramdor-the-mad);
3. Make sure [Ramdor the Mad](https://tbc.wowhead.com/npc=19417/ramdor-the-mad) greets you in English;
4. Try to find his greeting text in table **quest_greeting** and find nothing else there;
5. Become confused.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/caf68840b9bc6a435a59b2fb954c1fe779a27c66
TrinityCore rev. 2021-07-24 ‏‎12:46:23 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment]
It's npc_text without BroadcastTextIDX, there's no such broadcast text because that text was removed or never existed or was changed but our npc_text wasn't changed

**Comment by Freeman256** [comment]
Wow! I did a little research, and I figured out how to fix this problem, but I don't like it at all, because everything is very confusing, and in the future it will be difficult to figure out how it works ... but it works.

```
DELETE FROM `broadcast_text` WHERE `ID` IN (77867);
DELETE FROM `broadcast_text_locale` WHERE `ID` IN (77867) AND `locale` = 'ruRU';
INSERT INTO `broadcast_text` (`ID`, `Text`) VALUES ('77867', 'That child gives me chills. He stands there all day long communing with his grandfather. He\'ll then turn to tell his mother what the grandfather told him and she - of course - just smiles and nods her head.$B$BLambs! Lemmings! All of them!');
INSERT INTO `broadcast_text_locale` (`ID`, `locale`, `Text`) VALUES ('77867', 'ruRU', 'Меня уже трясёт от этого ребёнка. Он целый день стоит там, общаясь с дедушкой. Затем он поворачивается, чтобы рассказать своей матери то, что сказал ему дедушка, и она - конечно же - просто улыбается и кивает головой. $B$BЯгнята! Лемминги! Все они!');
UPDATE `npc_text` SET `BroadcastTextID0`='77867' WHERE  `ID`=9914;
```
In other words, I used a free ID that follows the most recent one.
I'm sure the guys from CMangos would have burned me at the stake for such a crutch. 
I can keep making fixes for missing localizations like this one if no one minds.

**Comment by Aokromes** [comment]
altering broadcast_text / broadcast_text_locale without sniffs is hack.

**Comment by offl** [comment]
All we have to do here is check if that npc_text is really used on retail
If it's used, we can add npc_text_locale for it

We don't add new texts to broadcast_text\locale nor edit them

**Comment by Freeman256** [comment]
Well, then I found another NPC with a similar problem: [Defender Mordun](https://www.wowhead.com/npc=24111/defender-mordun). He also lacks localization in the Russian version. There is no screenshot to prove it, because I have already made a similar fix for it (of course, only on my server).
If you try to fix this, then in the Russian version he says the following: 
`Ступай осторожно, $R.$B$BЭти трупы - всё, что осталось от моих лучших людей.`

**Comment by Freeman256** [comment]
And one more NPC with this problem: [Shatterhorn](https://www.wowhead.com/npc=24178/shatterhorn). Quest - [The Yeti Next Door](https://www.wowhead.com/quest=11284/the-yeti-next-door). BroadcastTextId = 0.
If you are going to fix this, then in the Russian version he says the following:
`%s просыпается от запаха свежего мяса!`

![WoWScrnShot_081621_204809](https://user-images.githubusercontent.com/73786888/129607719-24283b92-2043-431e-aa74-154420db8b21.jpg)

**Comment by offl** [comment]
Ignore all creature_text

**Comment by Freeman256** [comment]
Found another NPC that has no text in **quest_greeting** and **quest_greeting_locale** tables - [Kurzel](https://www.wowhead.com/npc=26664/kurzel) in Drak'Tharon Keep.

![WoWScrnShot_082121_184528](https://user-images.githubusercontent.com/73786888/130327481-62623d48-f3fe-43c5-ac0e-b3566105d424.jpg)
