### ISSUE TITLE
DB/Quest: Are We There Yeti? (Part 3)

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26743]
### Description

The quest item given only has a single charge - it requires minimum of 3 to complete the quest. 

Item disappears after using it on first npc.

### Expected behaviour

Quest item is supposed to have 19 charges ([source](https://classic.wowhead.com/quest=5163/are-we-there-yeti#comments))

Reward has 3

### Steps to reproduce the problem

1. Take the questline "[Are We There Yeti?](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=3783)" from [Umi Rumplesnicker](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10305) in Winterspring
2. [Part 3](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5163) requires that you scare 3 NPCs with a mechanical Yeti quest item
3.  Item has 1 charge and disappears when you use it on first NPC

Note: I believe quest is giving wrong item - [This one](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12928) should be given instead of current one shown below

<details>

![image](https://user-images.githubusercontent.com/66294837/126781750-dd65edd2-c4a9-4331-b701-5af91373de79.png)
</details>

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
You need to use https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12928 which has 10 charges
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=15778 has 3 charges and is the reward from that quest

**Comment by TQPS** [comment]
Deleting the quest and re-taking it gave me the correct quest item to use with 10 charages.
