### ISSUE TITLE
[3.3.5] Lags during the capture of PvP objects.

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26748]
### Description

During the capture of PvP objects (for example, in Hellfire Peninsula and Terokkar Forest), lags are observed.

I hope I haven't bothered you yet with pointing out problems with the server. I really like TrinityCore and with my bug reports I just want to make it better. A titanic work has already been done, but not all problems have been resolved yet. I apologize in advance if I am doing something wrong.

### Expected behaviour

There should be no lags during the capture of PvP objects.

### Steps to reproduce the problem

1. Create a character (no matter which faction);
2. Travel to Hellfire Peninsula;
3. Turn on PvP mode;
4. Try to start capturing PvP objects (for example, in Hellfire Peninsula and Terokkar Forest);
5. Pay attention to the fact that lags are observed during the capture;
6. Also, pay attention to the fact that the PvP mode will turn off arbitrarily after a while.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/caf68840b9bc6a435a59b2fb954c1fe779a27c66
TrinityCore rev. 2021-07-24 ‏‎12:46:23 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by Faq** [comment]
To see the lag source, you could set up https://trinitycore.atlassian.net/wiki/spaces/tc/pages/19955721/Monitoring+a+TrinityCore+server

**Comment by jackpoz** [comment]
Is it client side lag or server side lag ? Does it affect players in other maps ?
Grafana would surely help (that's the link faq posted)

**Comment by Freeman256** [comment]
I have not been able to figure out how to install the monitoring program. And I also play alone. I tried to capture PvP objects both on the client of the game with unofficial patches for graphics from version 6.x.x, and on the clean client - both there were lags during the capture. It seems that lags occur only for those players who participate in the capture. On the server itself, I have some custom changes, but they only concern the stacks of items and the chance of their drop, so these changes could not cause lags.

**Comment by jackpoz** [comment]
You can use the test realm I linked, Grafana is installed already there

**Comment by Freeman256** [comment]
Oh, I tried running a clean client with no addons at all, and... the lags disappeared. So the problem is in my addons. I apologize for the false alarm.
