### ISSUE TITLE
Mac OS (Clang) Linking world server fails

### ISSUE THREAD

**Issue by skarnproject** [TrinityCore/TrinityCore#26752]
### Description

Linking of world server (3.3.5a) fails on Mac OS Big Sur using Apple Clang (or normal Clang as well) with the following error:

`[ 98%] Linking CXX executable worldserver
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > Metric::FormatInfluxDBValue<unsigned long>(unsigned long)", referenced from:
      void Metric::LogValue<unsigned long>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >) in Main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/worldserver] Error 1
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [all] Error 2
`

### Expected behaviour

Linking without errors.

### Steps to reproduce the problem

Pull repo. Run cmake with unix makefile. Build using clang.

### Branch

3.3.5

### TC rev. hash/commit

a45eb13e3eabf455f89d7e2a500cabf1ba814339

### Operating system

Mac OS Big Sur 11.5

### Custom changes

None

**Comment by Aokromes** [comment]
i recommend you to avoid macos, wow 3.3.5a doesn't ships 64 bits client.

**Comment by jackpoz** [comment]
which version of "normal Clang" ?

**Comment by skarnproject** [comment]
> i recommend you to avoid macos, wow 3.3.5a doesn't ships 64 bits client.

I am temporarily limited to working with a MacBook since my PC broke. Mac OS is able to run a 3.3.5a Windows executable through Crossover. I've not even tried the original Mac binary when x86 was still around since I am running a modified client, and it'd be too much work to patch both executables. Anyway the question is about Trinity Core, not running WoW.

> which version of "normal Clang" ?

12.0.0 LLVM Clang. 

Don't know which Apple Clang, but assume latest, since I've recently updated.

Identical error with both.

**Comment by jiangjiali** [comment]
I have the same problem.

**Comment by jackpoz** [comment]
Try building passing the cmake flag -DWITHOUT_METRICS=TRUE (or setting WITHOUT_METRICS to True from the CMake GUI).

Are you using libstdc++ or ? which version ? do you have gcc installed too ? which version ?

**Comment by jiangjiali** [comment]
> Try building passing the cmake flag -DWITHOUT_METRICS=TRUE (or setting WITHOUT_METRICS to True from the CMake GUI).
> 
> Are you using libstdc++ or ? which version ? do you have gcc installed too ? which version ?


Use the Mac OS's own 12.0.0 clang.

**Comment by jackpoz** [comment]
Try after https://github.com/TrinityCore/TrinityCore/commit/8fcf59f9db929e94b1a6d2c75c1905f0a51dcddd
