### ISSUE TITLE
DB/Item: Demon Kissed Sack 

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26757]
### Description

The reward from the quest [The Demon Forge](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5127) gives a few items, one is a [Demon Kissed Sack](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12849#contains).

Like many other containers (locked boxes, clams, etc) this gave no items - it was empty.

When I looked it up [online](https://tbc.wowhead.com/item=12849/demon-kissed-sack#contains), and compared with [our Trinity DB](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=12849#contains) we come up short, 

<Details>

![image](https://user-images.githubusercontent.com/66294837/127145021-86afd3d0-f2dc-4389-bc15-21b6c3a69dd5.png)

</details>

### Expected behaviour

Supposed to get one of around 10 different magic items - we have 2 in the DB.

No reported cases of it being empty.

### Steps to reproduce the problem

1.. Go to Winterspring and speak to [Lorax](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10918)
2. Accept the quest [The Demon Forge](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=5127)
3.  Go to UBRS and complete the task
4. Return to Lorax for reward
5. Open Demon Kissed Sack - if you do get item it's only 1 of 2 - in my case I got nothing. It should not be empty.

Suspect it's loot table needs a visit

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
```sql
--
DELETE FROM `item_loot_template` WHERE `Entry` = 12849;
INSERT INTO `item_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(12849,10376,0,0,0,1,1,1,1,''),
(12849,10377,0,0,0,1,1,1,1,''),
(12849,10378,0,0,0,1,1,1,1,''),
(12849,10379,0,0,0,1,1,1,1,''),
(12849,10380,0,0,0,1,1,1,1,''),
(12849,10381,0,0,0,1,1,1,1,''),
(12849,10382,0,0,0,1,1,1,1,''),
(12849,10383,0,0,0,1,1,1,1,'');
```

**Comment by TQPS** [comment]
There must be another component somewhere that's giving a chance for these containers to have "nothing". This is probably a separate discussion.

I cant tell you how many times I opened a locked box to find it empty.

**Comment by offl** [comment]
Not in this case, wowhead (tbc and archived in 2010 page) shows that something drops always
