### ISSUE TITLE
DB/NPC: Hearthsinger Forresten spawn

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26766]
### Description

The spawn point for [Hearthsinger Forresten](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10558#drops) in Stratholme is currently a single location.

NB: It's a good location and easy to get to making repeated runs for him easy but honestly, it's not BlizzLike.

### Expected behaviour

The spawn point should be varied - I dont have exact locations but Atlas Loot for WoTLK shows he should spawn in 1 of 4 locations.

### Steps to reproduce the problem

1. Go to Stratholme  via your preferred method
2. If coming from main entrance go through first Portcullis to the right at the first fork  - he is just on the other side of it (/tar hearth)
or
   If coming from the service entrance - take a left when you enter and head in a straight line under first portcullis to the next one directly ahead, he's just before it (/tar hearth)
3. Run Stratholme over and over to try and get your Tier 0 Magister's Boots that never drop - he will be in the same spot each run.

<details>

![image](https://user-images.githubusercontent.com/66294837/127719525-35a94ab2-f03d-4fcb-95f9-e31bc86aab12.png)

![image](https://user-images.githubusercontent.com/66294837/127720083-c2f1a02a-e5b9-43cd-beaa-30f696db93d4.png)

</details>

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by Jinnaix** [comment]
Ref: 
https://github.com/TrinityCore/TrinityCore/issues/24437

Ref: 
https://github.com/TrinityCore/TrinityCore/issues/19233#issuecomment-682077584

**Comment by offl** [comment]
>The spawn point for Hearthsinger Forresten in Stratholme is currently a single location.

Actually 3
I don't know if 3595.64    -3461.16     136.267      4.63659 is sniffed location, don't wanna try to check atm
Other 2 are sniffed
And I'm gonna add 2 more

**Comment by mdX7** [comment]
```
3595.75 -3509.93  137.501 5.74213
3680.27 -3512.37 136.152 2.04204
3683.75  -3334.07 125.32 3.14159
3692.93 -3363.16 130.753 3.24631
```
based on sniffs of @ratkosrb
