### ISSUE TITLE
[3.3.5/Quest] Dimensius the All-Devouring

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26782]
### Description

https://tbc.wowhead.com/quest=10439/dimensius-the-all-devouring

The quest has stopped working. I remember doing this quest a year or two ago, and everything worked well. I remember that this https://github.com/TrinityCore/TrinityCore/issues/3723 problem was fixed (maybe last time I tried to apply the suggested fixes for this problem, but I remember for sure that this quest worked great). According to this quest, you need to talk to [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed), tell him that you are ready to attack Manaforge Ultris, after which [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) and the warriors will run to the entrance to Manaforge Ultris, attacking everyone in their path. Before entering Manaforge Ultris, you need to talk to [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) again, tell him that you are ready to attack [Dimensius the All-Devouring](https://tbc.wowhead.com/npc=19554/dimensius-the-all-devouring), and then [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) and his troops will run to the center of Manaforge Ultris, and when they come running there, nothing will happen.

### Expected behaviour

Almost everything works well, but the last stage of the quest doesn't work. When the player and [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) and their troops run into the center of the Manaforge Ultris, [Dimensius the All-Devouring](https://tbc.wowhead.com/npc=19554/dimensius-the-all-devouring) should appear and can be attacked.

### Steps to reproduce the problem

1. Take quest [Dimensius the All-Devouring](https://tbc.wowhead.com/quest=10439/dimensius-the-all-devouring) from [Professor Dabiri](https://tbc.wowhead.com/npc=20907/professor-dabiri) (this is the final quest in the chain);
2. Tell [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) you're ready to attack Manaforge Ultris;
3. Work your way with [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) and his troops to the entrance to Manaforge Ultris;
4. At the entrance to Manaforge Ultris, tell [Captain Saeed](https://tbc.wowhead.com/npc=20985/captain-saeed) that you are ready to attack [Dimensius the All-Devouring](https://tbc.wowhead.com/npc=19554/dimensius-the-all-devouring) and fight your way with him and his troops into the center of Manaforge Ultris;
5. Once you reach the center of Manaforge Ultris, make sure [Dimensius the All-Devouring](https://tbc.wowhead.com/npc=19554/dimensius-the-all-devouring) doesn't appear, and that nothing happens at all.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/8fcf59f9db929e94b1a6d2c75c1905f0a51dcddd
TrinityCore rev. 2021-08-07 ‏‎10:06:04 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by Aokromes** [comment]
that ticket you mention it's still opened, never pushed. never worked on clean core.

**Comment by Freeman256** [comment]
I will not do research or prove anything, but in mid-November 2020 I get the achievement for observing all areas and completing 120 quests in Netherstorm, and I swear that the gossip menu was not working then, but I used the suggested solutions to this problem, and this quest has worked for me. I had a clean core and database, of course.

**Comment by CraftedRO** [comment]
71b7cc6361d6 indeed this quest no longer works.
