### ISSUE TITLE
[3.3.5/Quest] Teleport This!

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26780]
### Description

Ref. https://github.com/TrinityCore/TrinityCore/issues/4878

https://www.wowhead.com/quest=10857/teleport-this

The quest has stopped working. I remember doing this quest a year or two ago, and everything worked well. To complete this quest, as described, I use [Mental Interference Rod](https://www.wowhead.com/item=31678/mental-interference-rod) on Mo'args at Forge Base: Gehenna and gain control over them. I then bring Mo'args to the legion's teleporter and use their destroy teleporter ability, but nothing happens and destroying the teleporter does not count.

### Expected behaviour

Destroying teleporters with Mo'arg's destroy teleporter ability should count.

### Steps to reproduce the problem

1. Take quest [Teleport This!](https://www.wowhead.com/quest=10857/teleport-this) from [Nether-Stalker Nauthis](https://www.wowhead.com/npc=20471/nether-stalker-nauthis);
2. Go to Forge Base: Gehenna at Netherstorm;
3. Take control of the Mo'arg, bring it to the teleport, use its ability to "destroy the teleport", make sure that a projectile is fired at the teleport, that the teleport is on fire, but its destruction is not counted.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/8fcf59f9db929e94b1a6d2c75c1905f0a51dcddd
TrinityCore rev. 2021-08-07 ‏‎10:06:04 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by Aokromes** [comment]
the last time i see this quest completed on quest_tracker is
10857	185998	2021-01-18 21:15:52	2021-01-18 21:39:37		0	cdfa85957e27+	2021-01-17 17:45:00 +0100

**Comment by offl** [comment]
Because those controlled units don't have https://github.com/TrinityCore/TrinityCore/commit/c00b0551345245c2a91db2e1b62a13fa969c218e#diff-4a48bf5d2d9d13dcd69d620b99fb5e546f48fb06f89f2698013e5eb9eb5e747cR1 which is now known as CREATURE_DIFFICULTYFLAGS_2_ACTION_TRIGGERS_WHILE_CHARMED. Means all that stuff which is broken now should not be scripted inside controlled units

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8186e6deca7a42403db8b45b341c655cec9c8a73
