### ISSUE TITLE
[3.3.5] Multiple lack of localization in the gossip menu

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#26785]
### Description

I have come across a huge number of NPCs that do not work with the translation of options in gossip. For example, when I started completing quest [The Hunt is On](https://www.wowhead.com/quest=11794/the-hunt-is-on#), I used the quest item [Oculus of the Exorcist](https://www.wowhead.com/item=35125/oculus-of-the-exorcist) and started a conversation with the NPC I needed. The gossip menu option is not translated into Russian. 

![WoWScrnShot_080821_112149](https://user-images.githubusercontent.com/73786888/128625900-2012d93f-92fd-4339-ae43-7d51c51bc779.jpg)

I began to figure out how it can be translated and climbed into the **gossip_menu_option** database and looked for the phrase "What do you know about the Cult of the Damned?" there and found it id - 9217. Then I created a new line in base **gossip_menu_option_locale** with the Russian version of this phrase: 
`INSERT INTO `gossip_menu_option_locale` (`MenuID`, `Locale`, `OptionText`) VALUES ('9217', 'ruRU', 'Что ты знаешь о Культе Проклятых?');`
For some reason it didn't work. I noticed one more value in table **gossip_menu_option**: OptionBroadcastTextID - 25237.
Well, I decided to add a translation of this phrase to table **broadcast_text_locale**: 
`INSERT INTO `broadcast_text_locale` (`ID`, `locale`, `Text`, `Text1`) VALUES ('25237', 'ruRU', 'Что ты знаешь о Культе Проклятых?', 'Что ты знаешь о Культе Проклятых?');`
But, all of a sudden, I got an error message:
/* SQL error (1062): Duplicate entry '25237-ruRU' for key 'PRIMARY' */

Then I used the filter and found that such a line really already exists, but despite this, for some reason it does not work. Then I tried creating a row in table **gossip_menu_option_locale**:
`INSERT INTO `gossip_menu_option_locale` (`MenuID`, `Locale`, `OptionText`) VALUES ('25237', 'ruRU', 'Что ты знаешь о Культе Проклятых?');`

But that didn't help either.

The crux of the problem: There should be a working ability to translate for the gossip menu options, and if possible, it should be easy to understand. 

### Expected behaviour

The gossip menus of NPCs should be translated into other languages. (It seems that I am the only one who, after a long time of downtime, took up the creation (or searching for a finished database) of Russian localization, so...)
OR
There must be a working way to translate them. 

If this method exists, share your experience. The above described how I followed the logic, but I did not succeed, which means that not everything is good here. (If table **gossip_menu_option_locale** doesn't work, then what is it for?)

### Steps to reproduce the problem

1. Launch the Russian version of the game (possibly with other languages);
2. Try talking to tavern owners around the world. If you need specifics, take quest [The Hunt is On](https://www.wowhead.com/quest=11794/the-hunt-is-on#) and start doing it. Talk to the NPCs you need and make sure there is no Russian translation of the gossip menu options;
3. Make sure the translation string exists in table **broadcast_text_locale**.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/8fcf59f9db929e94b1a6d2c75c1905f0a51dcddd
TrinityCore rev. 2021-08-07 ‏‎10:06:04 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment]
If BroadcastText is NOT 0 in any table(creature_text, npc_text, gossip_menu_option), text is used from broadcast_text directly and locale text is taken directly from broadcast_text_locale
If BroadcastText is 0 in any table(creature_text, npc_text, gossip_menu_option), text is used from creature_text, npc_text, gossip_menu_option and locale text is used from creature_text_locale, npc_text_locale, gossip_menu_option_locale

Everything looks fine on DB side
All gossip option texts are not translated?

**Comment by Freeman256** [comment]
Not all. According to my observations, about half of the texts have been translated.

**Comment by offl** [comment]
Weird
Options of guards from #26261 too?

**Comment by Freeman256** [comment]
The guards are all right.

Here are some examples. Everything is in order here:
![WoWScrnShot_080821_160014](https://user-images.githubusercontent.com/73786888/128633207-e58f2cf6-b6d5-451c-812e-04985b8e4b4b.jpg)
![WoWScrnShot_080821_160901](https://user-images.githubusercontent.com/73786888/128633214-c42164a6-2768-4304-9974-df08fa9b8d2b.jpg)
![WoWScrnShot_080821_161210](https://user-images.githubusercontent.com/73786888/128633221-24f3d6fa-7f77-48c0-a8d2-9afdeb7a2fb6.jpg)
![WoWScrnShot_080821_161318](https://user-images.githubusercontent.com/73786888/128633226-60d57a53-8961-4500-a556-2538d677c88c.jpg)

And here there is no translation (see NPC ID in the chat window):
![WoWScrnShot_080821_160538](https://user-images.githubusercontent.com/73786888/128633267-13da7d2b-f82d-4748-8168-9ef244960559.jpg)
![WoWScrnShot_080821_161247](https://user-images.githubusercontent.com/73786888/128633276-7811ac87-a897-41bc-8296-e087d7f1e0e7.jpg)
![WoWScrnShot_080821_161406](https://user-images.githubusercontent.com/73786888/128633281-9d913844-83d0-4f97-bc64-8a4395814c9a.jpg)

**Comment by Freeman256** [comment]
In addition, some teachers of professions also do not have a translation (in this case, they are all in Teldrasilla, but I do not remember that at least one of the trainers saw the translation in the upper part of the window): 

![WoWScrnShot_080821_160228](https://user-images.githubusercontent.com/73786888/128633407-7c758c1d-0c8b-4d71-ba29-ede8e6a2d9b4.jpg)
![WoWScrnShot_080821_160245](https://user-images.githubusercontent.com/73786888/128633408-fe68ef8f-144b-4447-a8c5-6ed8dea96a5a.jpg)

**Comment by Freeman256** [comment]
If it is not possible to solve all such problems at once, then perhaps it is worth creating one general topic, such as this one https://github.com/TrinityCore/TrinityCore/issues/26727, and adding an NPC id with the missing localization of gossip options there?

**Comment by offl** [comment]
>In addition, some profession teachers also do not have a translation (in this case, they are all in Teldrasilla, but I do not remember that at least one of the trainers I saw the translation in the upper part of the window):

trainer_locale, you can add them like in https://github.com/TrinityCore/TrinityCore/commit/eac9851341c127f19b32ccb93def55a9f9e468ec#diff-86f6d2b22c53377c4e50e646347ef668f8b50d6eeef6479c1f2014ecc3813a95R75

>If it is not possible to solve all such problems at once, then perhaps it is worth creating one general topic, such as this one #26727, and adding an NPC id with the missing localization of gossip options there?

No, they already are translated, we need to figure out why it does not work in some cases

**Comment by offl** [comment]
Hol up, all those are innkeepers
#24961

Please try
.go c id 25248
He should have 2 gossip options and looks like first has no condition so is shown always
How does they look in game?

If one of options is not translated, execute
```sql
UPDATE `gossip_menu_option` SET `OptionType` = 1 WHERE `MenuID` = 9218 AND `OptionType` = 0;
```
.rel gossip_menu_option
And talk with creature again

**Comment by Freeman256** [comment]
This is how this NPC looked before the changes were made (the trade window opens immediately):

![WoWScrnShot_080821_183635](https://user-images.githubusercontent.com/73786888/128637544-760d2e8f-4564-460c-8a15-29d2ba22f571.jpg)

This is how this NPC looked after making edits, restarting the server and deleting the cache in the client:

![WoWScrnShot_080821_184110](https://user-images.githubusercontent.com/73786888/128637648-b052ba36-5665-4c29-9c6c-3380042de18b.jpg)

Well, that is, yes, nothing has changed, and the trading window opens immediately.

**Comment by offl** [comment]
.go c id 25827
```sql
UPDATE `gossip_menu_option` SET `OptionType` = 1 WHERE `MenuID` = 9217 AND `OptionType` = 0;
```
.rel gossip_menu_option
And talk with creature again

**Comment by Freeman256** [comment]
**UPDATE...** and **.rel gossip_menu_option** didn't change anything. Restarting the server and deleting the cache in the client - no changes. Again, the trading window opens immediately.

**Comment by offl** [comment]
Try https://github.com/TrinityCore/TrinityCore/issues/26785#issuecomment-894816027

**Comment by Freeman256** [comment]
![WoWScrnShot_080821_200054](https://user-images.githubusercontent.com/73786888/128639629-f6a8be16-240d-45b7-8d87-89dae9d9df5d.jpg)

Nothing changed.

**Comment by offl** [comment]
Well, that is last chance
```sql
UPDATE `gossip_menu_option` SET `OptionNpcFlag` = 1 WHERE `MenuID` = 9217;
```

**Comment by ckegg** [comment]
innkeeper is well known issue, see stuffs under this folder:
/src/server/scripts/World

**Comment by offl** [comment]
Are you sure 'half' of options aren't translated? Because to me it looks like only half of innkeepers and like 5 other creatures
Half of those innkeepers never had their gossip options translated

**Comment by Freeman256** [comment]
```
UPDATE `gossip_menu_option` SET `OptionNpcFlag` = 1 WHERE `MenuID` = 9217;
```
+ 
.rel gossip_menu_option

![WoWScrnShot_080821_201049](https://user-images.githubusercontent.com/73786888/128640009-28cef0e0-e2e6-4cda-b36d-1e4bd3841270.jpg)

Nothing changed.

Tried restarting the server and deleting the cache in the client - Nothing changed.

Maybe I'm the "lucky one", but it really seemed to me that half of the tavern owners I met didn't have these options translated.

**Comment by offl** [comment]
Ignore tavern owners, half of their gossip options even are not stored in DB

Is there any other case except creature 25827 and not innkeeper?
Because we already tried to make this gossip option look like others but that does not help(and probably should not because OptionType and OptionNpcFlag has nothing to do with locales but should not be set to 0)
```txt
MenuID  OptionID  OptionIcon  OptionText                                      OptionBroadcastTextID  OptionType  OptionNpcFlag  ActionMenuID  ActionPoiID  BoxCoded  BoxMoney  BoxText  BoxBroadcastTextID  VerifiedBuild  
------  --------  ----------  ----------------------------------------------  ---------------------  ----------  -------------  ------------  -----------  --------  --------  -------  ------------------  ---------------
  9217         0           0  What do you know about the Cult of the Damned?                  25237           0              0             0            0         0         0  (NULL)                    0            26365
```

**Comment by Freeman256** [comment]
At first glance, I still can't remember other non-innkeepers with untranslated gossip menus.

**Comment by ckegg** [comment]
Hardcoded.

https://github.com/TrinityCore/TrinityCore/blob/4d11401377e41b71cd96efc4d34e59c1dda365f2/src/server/scripts/Northrend/zone_borean_tundra.cpp#L1420-L1422

**Comment by offl** [comment]
Fuck.

**Comment by offl** [comment]
Thanks, @ckegg
#22696 updated

**Comment by Freeman256** [comment]
What about the innkeepers? Maybe there is a way to make them speak in the Russian version of the game instead of "Make this inn my home." this is: "Я хочу остановиться здесь." and instead of "I want to browse your goods." this is: "Позвольте мне взглянуть на ваш товар." Was the problem closed too early?

**Comment by Freeman256** [comment]
Oh, this is my fault, but I communicated with 25248 with the quest already completed. Now I re-execute it and this is what I see:

![WoWScrnShot_080821_210023](https://user-images.githubusercontent.com/73786888/128641274-54893daa-059b-4dfd-a674-31886fd4e54d.jpg)

**Comment by offl** [comment]
> What about the innkeepers? Maybe there is a way to make them speak in the Russian version of the game instead

You can add ruRU texts in https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/World/npc_innkeeper.cpp

**Comment by Freeman256** [comment]
There is no translation of the gossip menu. Quest - [Last Rites](https://www.wowhead.com/quest=12019/last-rites#), NPC - [Thassarian](https://www.wowhead.com/npc=26170/thassarian). 

![WoWScrnShot_081221_180222](https://user-images.githubusercontent.com/73786888/129220873-fe9036ec-f05a-46a4-8b06-0de1aa147059.jpg)

**Comment by offl** [comment]
#22696 updated
>In addition, during all the dialogues at the top of the floating Scourge citadel of Naxxanar, all NPCs interrupt each other in the Russian version of the game.

What do you mean by 'interrupt each other'?

**Comment by Freeman256** [comment]
When the player selects that untranslated option of the gossip menu, a scripted scene begins: various NPCs appear and begin to communicate with each other, and their communication takes place not only in the form of text in the clouds above their heads and in the chat window, but also in full-fledged voice acting. During these conversations, these NPCs interrupt each other. That is, the NPCs do not have time to finish their speech when the speech of the next NPC begins. Because of this, it is impossible to make out by ear who is saying what, but it is also difficult to read their speech in the chat window in time, because their phrases very quickly replace each other.
Perhaps a solution to the problem is to have more delay between NPC phrases in this script scene.
I made a backup of the database at this point before the start of this scene so that I can quickly check for possible suggested fixes if it appear.

**Comment by offl** [comment]
Pretty sure timers are not original
And it's not always a bug if chat bubbles are interrupted by each other(if creature talks too fast)

**Comment by Freeman256** [comment]
I noticed that the localization of the texts of the announcements of Dragonflayer defenders does not work, despite the fact that it is present in table broadcast_text_locale. Quest - [It Goes to 11...](https://www.wowhead.com/quest=11421/it-goes-to-11), IDs: 23625, 23637, 23640, 23641. If necessary, I can take screenshots of these announcements in English. These announcements appear after successfully setting fire to a Vrykul warehouse or shipyard. Also, if necessary, I can open a new topic with this issue. By the way, the fixes proposed in this https://github.com/TrinityCore/TrinityCore/issues/6844 thread half-repair this quest: buildings can be set on fire, but defenders do not appear.

**Comment by offl** [comment]
Which creature uses them?

**Comment by Freeman256** [comment]
No being speaks this. This message appears in the center of the screen.

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/issues/6844#issuecomment-898937677
C'mon, you're asking me what's wrong with texts which even are not added to DB yet

**Comment by offl** [comment]
Ignore all not translated gossip option texts, they all will be translated when we handle them in DB (#22696)
There are not too much of them left

**Comment by Freeman256** [comment]
The fact of the matter is that these texts are in the database, both in broadcast_text and broadcast_text_locale. I realized this when I tried to translate these texts. I started looking for English text in the broadcast_text table and found them. Having recognized their IDs, I wanted to create similar lines with ruRU localization, and when creating them, an error appeared, according to which these lines already exist in the broadcast_text_locale database...

Oh, I just now realized that these texts are both in table broadcast_text and in the table creature_text. I'll try to add ruRU rows to the creature_text_locale table later and check the result.

By the way, since you are so kind and answer my messages very quickly (for which thank you very much), please pay attention to this topic: https://github.com/TrinityCore/TrinityCore/issues/26782
I have described under what circumstances I was able to complete this quest earlier.
Also, please note that this quest https://github.com/TrinityCore/TrinityCore/issues/24703 has unexpectedly started working (in this thread, I also described my actions). 
I suspect that this is due to changes in the core. 
I'm asking you, because I'm afraid that this information can help, but due to the closure of the topic, no one may see it. 
I hope that my feedback will help fix the problems faster, and I apologize if I'm doing something wrong (or if I'm already tired of everyone with my frequent error messages).

**Comment by offl** [comment]
>The fact of the matter is that these texts are in the database, both in broadcast_text and broadcast_text_locale. I realized this when I tried to translate these texts. I started looking for English text in the broadcast_text table and found them. Having recognized their IDs, I wanted to create similar lines with ruRU localization, and when creating them, an error appeared, according to which these lines already exist in the broadcast_text_locale database...

https://github.com/TrinityCore/TrinityCore/issues/26785#issuecomment-894785931
