### ISSUE TITLE
[DB/SAI] Revisit modified scripts by c00b055

### ISSUE THREAD

**Issue by ccrs** [TrinityCore/TrinityCore#26794]
### Description

@offl please revisit the entries contained in the commit c00b0551345245c2a91db2e1b62a13fa969c218e 

If I'm not mistaken, these do not contain the 512 flag in their events anymore.
The reasoning was to avoid them processing SAI events while charmed + allow autoattack support.

The thing is, the later commit f6e52f6b3df92a837787f63514417a7d240144cd does allow both things iirc.
Keep existing scripts and include 512 flag to those that should actually trigger while charmed.

Note: there are vehicles that do have SAI events that trigger on charm, like texts, casts and even WPs.

I know its a grind, there are many entries 💃 

### Expected behaviour

thing

### Steps to reproduce the problem

another thing

### Branch

3.3.5

### TC rev. hash/commit

4d11401377e41b71cd96efc4d34e59c1dda365f2 

### Operating system

Windows 10 x64

### Custom changes

yet another thing

**Comment by offl** [comment]
> If I'm not mistaken, these do not contain the 512 flag in their events anymore.

They do have, the ones which don't (like 17606) simply has VehicleId or CREATURE_DIFFICULTYFLAGS_2_ACTION_TRIGGERS_WHILE_CHARMED and were included in the NOT IN list of entries but were without SMART_EVENT_FLAG_WHILE_CHARMED
