### ISSUE TITLE
quest go wrong

### ISSUE THREAD

**Issue by SimonChenyongxing** [TrinityCore/TrinityCore#26809]
### Description

quest id 12630
When I am not select the right target, and click the item (38659), Nass will go away and never come back.

### Expected behaviour

I think he just stand still and do nothing.

### Steps to reproduce the problem

accept quest 12630.
click the item 38659,then Nass go away.

### Branch

3.3.5

### TC rev. hash/commit

2870a99d1a

### Operating system

Windows 7 x64

### Custom changes

no

**Comment by Faq** [comment]
Please stop using "quest go wrong" as title of issue, just add quest name there, that would be more informative.

**Comment by dr-j** [comment]
Read comment T https://github.com/TrinityCore/TrinityCore/issues/24464#issuecomment-614283936 probably issue which was mentioned there

**Comment by SimonChenyongxing** [comment]
Thanks，It works.
