### ISSUE TITLE
Quest: Triage (Alliance) - 1 spawn faces wrong direction

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26802]
### Description

During the [Triage](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6624) (Alliance side) quest in Dustwalllow Marsh there's 1 spawn location where the targets are facing the wrong direction.

See here:

<details>

![image](https://user-images.githubusercontent.com/66294837/129140847-12ef7f12-2841-41a3-8f7b-0c179e39a1b0.png)

</details>

### Expected behaviour

Spawn should be at a 90 degree angle from it's current position.

Unimportant Note: I do not know if heads are supposed to be on pillow locations - however, most of the spawns for this quest do so with their heads on the opposite side of the pillow.

### Steps to reproduce the problem

1. Head to Dustwallow Marsh as an Alliance character
2. Pick up the Triage quest from [Doctor Gustaf VanHowzen](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=12939)
3. Undertake quest
4. 1 spawn location (shown above) always spawns the patient facing this wrong direction.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 87a4bc3 2021-07-23 00:12:58 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
#25387 updated
