### ISSUE TITLE
3.3.5 - Core/Script: Silithus Wind Stone Bosses

### ISSUE THREAD

**Issue by Jinnaix** [TrinityCore/TrinityCore#26814]
### Description

As a reminder for to-do`s at this.

### Expected behaviour

- [ ] Wind Stone Bosses should have a grace period for about 5 Seconds. In this period of time they are unattackable and not in combat with the player. (potentially for the summoning player to re-equip items after he loses the worn twillight set, but in theory, the player should already be able to do this as soon as the dialog appears via OnGossipMenu(test needed))

- [ ] Wind Stone Bosses should get aggro on the summoning player AND any other player on that players group

- [ ] Used Wind Stone should be destroyed? (currently the spell disables the gameobject) and respawn after a certain amount of time (No idea for lesser windstones, 15 minutes for normal windstones, 3 hours for greater ones.)

- [ ] Spawned Boss should despawn immediately after combat ends (in case of attacking player/s die for example)

### Steps to reproduce the problem

A lot.

### Branch

3.3.5

### TC rev. hash/commit

6bcda49e98f08e663eb7a2e6e8a5aa6c2143a2a8

### Operating system

Windows 10

### Custom changes

None

**Comment by offl** [comment]
Who's the summoner of them right now? GO or player?
