### ISSUE TITLE
In Ulduar, the spell 62479 62482 67372 67387 don't work

### ISSUE THREAD

**Issue by SimonChenyongxing** [TrinityCore/TrinityCore#26815]
### Description

Before the first boss flame_leviathan, we take the vehichleCursor. 
The copilot can't use the spell 62479 62482 67372 67387 to fetch a box and load power to the vehichleCursor.
 

### Expected behaviour

After the copilot select the target, click the spell 62479 62482 67372 67387 , the  box can be fetched and loaded.

### Steps to reproduce the problem

enter Ulduar
take one  vehichleCursor
shoot down one box
click spell 62479 62482 67372 67387

### Branch

3.3.5

### TC rev. hash/commit

e14a0c197c

### Operating system

Windows 7 x64

### Custom changes

no

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16520
