### ISSUE TITLE
WoW server registiration error

### ISSUE THREAD

**Issue by nomad231** [TrinityCore/TrinityCore#26810]
### Description

Hi, i have found a wow server. When i reigster to web site i can register on site but i cant to server. I have take a error page. Error screenshot is attached. Please help.

my site: http://worldofwarcraftprime.com

![hata](https://user-images.githubusercontent.com/4716399/129391384-363bafdf-b3d2-4ba9-b588-df74c8b20fac.png)

Thanks.

### Expected behaviour

I want  it to register successfully.

### Steps to reproduce the problem

1- When i try register to game on web site, i taking this problem.

### Branch

master

### TC rev. hash/commit

Error Number: 1146

Table 'auth.rbac_account_groups' doesn't exist

INSERT INTO rbac_account_groups(`accountId`, `groupId`, `realmId`) values ('9', 1, -1)

Filename: C:\inetpub\wwwroot\system\database\DB_driver.php

Line Number: 330

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by Aokromes** [comment]
this bug tracker doesn't belongs for setup issues.

**Comment by jackpoz** [comment]
Shouldn't this issue be reported to the project that created the website ?

**Comment by Jinnaix** [comment]
FusionCMS is discontinued, there is a spiritual successor called FusionGEN. You might have more luck there as trying to find someone that fixes the outdated CMS.
