### ISSUE TITLE
TC can't connect to database after restart mysql server

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#26826]
### Description

System user trinity is not root

**The first part of the error:**
After restart Mysql server and run ./authserver I get an error:

_Could not connect to MySQL database at 127.0.0.1: RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support
DatabasePool Login NOT opened._ 

Trinity will not be able to connect to the database until the user's console is logged in to mysql

mysql -u trinity -ptrinity
mysql> exit;

I'm launching it again ./authserver

_Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.3.31
MySQL server ver: 8.0.26-0ubuntu0.20.04.2
Connected to MySQL database at 127.0.0.1
MySQL client library: 10.3.31
MySQL server ver: 8.0.26-0ubuntu0.20.04.2
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Loading IP Location Database...
Added realm "Trinity" at 192.168.1.30:8085._

or  in config file need add "ssl" in connection string

authserver.conf  
LoginDatabaseInfo = "127.0.0.1;3306;trinity;trinity;auth;ssl"

worldserver.conf
LoginDatabaseInfo     = "127.0.0.1;3306;trinity;trinity;auth;ssl"
WorldDatabaseInfo     = "127.0.0.1;3306;trinity;trinity;world;ssl"
CharacterDatabaseInfo = "127.0.0.1;3306;trinity;trinity;characters;ssl"

I decided to go the second way and added " ssl " to the connection strings,  and trinity began to connect to the database without the need to log in to the console in mysql after restarting

**The second part of the error:**
After a few minutes, I synchronized the repository.

_create mode 100644 sql/updates/world/3.3.5/2021_08_15_01_world.sql
 create mode 100644 sql/updates/world/3.3.5/2021_08_15_02_world.sql
 create mode 100644 sql/updates/world/3.3.5/2021_08_15_03_world_335.sql_

And started the server. The server crashed with an error when connecting.Using configuration file 

_/home/trinity/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Updating Auth database...
Auth database is up-to-date! Containing 1 new and 91 archived updates.
Updating Character database...
 Character database is up-to-date! Containing 1 new and 66 archived updates.
Updating World database...
Applying update "2021_08_15_01_world.sql" '65693AD'...
mysql: [Warning] Using a password on the command line interface can be insecure.
Applying of file '/home/trinity/TrinityCore/sql/updates/world/3.3.5/2021_08_15_01_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details._

If you remove " ssl " from the connection string, the server will successfully update the database and start in normal mode.

### Expected behaviour

1. I don't quite understand this is a trinity or mysql error, but there is a problem. 
2. The " ssl " connection parameter should not affect the possibility of updating the server database.

I'm sorry, I used a translator.

### Steps to reproduce the problem

*

### Branch

3.3.5

### TC rev. hash/commit

442efccd2e6446e30f9d5d1b2497b03c7b8397dc

### Operating system

Ubuntu 20.04.2 LTS
MySQL  8.0.26-0ubuntu0.20.04.2

### Custom changes

*

**Comment by kvolk2git** [comment]
EN.
There was another interesting point. authserver is loaded first, and if you leave the connection string with the ssl parameter in its config, then you can remove the ssl parameter when connecting in the worldserver config. Server updates after recompilation are performed automatically when the server is restarted without any database connection errors.

RU. 
Нашелся ещё один интересный момент. authserver загружается первым, и если у него в конфиге оставить строку подключения с параметром ssl, то в конфиге worldserver можно убрать параметр ssl при подключении. Обновления сервера после перекомпиляции производятся автоматически при перезапуске сервера без появления ошибок подключения к базе.

**Comment by kvolk2git** [comment]
EN. Most likely, the problem was that a non-standard MySQL 8 bundle with libmariadb-dev 10.3.31 was used. After reinstalling libmariadb-dev and mariadb-common, the problem could not be called again.

RU. Вероятнее всего проблема заключалась в том, что использовалась нестандартная связка MySQL 8 с libmariadb-dev 10.3.31. После переустановки libmariadb-dev и mariadb-common проблему повторно вызвать не удалось.

**Comment by baize0522** [comment]
@kvolk2git I'm having the same problem，i reinstalled libmariadb-dev and mariadb-common，he problem is not resolved

**Comment by kvolk2git** [comment]
> @kvolk2git I'm having the same problem，i reinstalled libmariadb-dev and mariadb-common，he problem is not resolved

https://github.com/TrinityCore/TrinityCore/issues/27306

**Comment by baize0522** [comment]
@kvolk2git Thank you so much for your help！I didn't succeed just now because I didn't re-make after reinstalling libmariadb-dev and mariadb-common. By the way,make clean didn't work for me, i rm -rf  TrinityCore/build/* and re-make && make install.
Thanks again， bro!
