### ISSUE TITLE
Stratholme: Ravaged Cadavers dropping too many Morning Glory Dews

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26835]
### Description

Another item for the Stratholme list:

The [Ravaged Cadaver](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10381#abilities) is dropping between [1-20](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10381#drops) Morning Glory Dew

<details>

![image](https://user-images.githubusercontent.com/66294837/129856633-fa157701-39c1-450a-af3a-316c0980b4d6.png)

![image](https://user-images.githubusercontent.com/66294837/129856540-4751fab4-7214-4d3c-8dea-439819f44927.png)

</details>

### Expected behaviour

WOWhead for Classic is [reporting](https://tbc.wowhead.com/npc=10381/ravaged-cadaver) a single Dew should drop

### Steps to reproduce the problem

1. Head to Stratholme
2. Kill Ravaged Cadavers
3. (RNG) When they drop, the Dew drops is various quantities - up to a verified 19 but can drop up to 20

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 7c7b4760d89f 2021-08-16 22:42:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
```txt
view-source:https://web.archive.org/web/20100416173218/http://www.wowhead.com/npc=10381
```
{"classs":0,"id":8766,"level":55,"name":"6Morning Glory Dew",
"reqlevel":45,"slot":0,"source":[2,5],"subclass":5,count:11045,**stack:[1,20]**},

That's probably the result of wowhead's bug, maybe not
