### ISSUE TITLE
Bnetserver crashes after upgrade system

### ISSUE THREAD

**Issue by nomad231** [TrinityCore/TrinityCore#26831]
### Description

Hi, i have use trinty master branch. My server my server was stable. After i have upgrade my vps specs to 8 gb ram and i restart the server. Since restart the server i cant open bnetserver. Its give me a error and its not work. Screenshot is attached. Please help. 

Thanks.

![hata3](https://user-images.githubusercontent.com/4716399/129601372-367c9487-738e-4f80-8c2d-91f9f6ea145a.png)

### Expected behaviour

Bnetserver work without crash

### Steps to reproduce the problem

1- Two click to bnetserver and i got error

### Branch

master

### TC rev. hash/commit

Using configuration file C:/Users/Administrator/Desktop/Server/bnetserver.conf.
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.72.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.7.35
MySQL server ver: 5.7.35-log 
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.7.35
MySQL server ver: 5.7.35-log 
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Updating password hashes...

### Operating system

Windows Server 2012 R2

### Custom changes

none

**Comment by Faq** [comment]
So what was the reason and how resolved?

**Comment by nomad231** [comment]
the problem caused by empty password hashes. It solved after delete empty password lines.
