### ISSUE TITLE
quest 12674:can't get the credit of Mu'funu 

### ISSUE THREAD

**Issue by SimonChenyongxing** [TrinityCore/TrinityCore#26830]
### Description

I have got the credit of Tua-Tua and Hawinni,but I use the same method, can't get the credit of Mu'funu.

### Expected behaviour

successfully get the credit of Mu'funu.

### Steps to reproduce the problem

accept the quest.
use the item received.
kill Mu'funu.
get the credit.

### Branch

3.3.5

### TC rev. hash/commit

e14a0c197c

### Operating system

Windows 7 x64

### Custom changes

no

**Comment by SimonChenyongxing** [comment]
Will somebody deal with this issue?

**Comment by Ovahlord** [comment]
> Will somebody deal with this issue?

maybe. maybe not. You can also start investigating yourself and contribute to the solution.

**Comment by CraftedRO** [comment]
Can't reproduce this on e8c005df3d8f (I tested with gm character) , but from what I read in database the mobs are kinda same so most likely there's no bug here.


https://user-images.githubusercontent.com/24683355/136264801-70737f58-fb4f-4259-955f-831a4ef703d7.mp4
