### ISSUE TITLE
Quest, NPC, and OBJECT missing content

### ISSUE THREAD

**Issue by SorrowHarvest** [TrinityCore/TrinityCore#26832]
### Description

The TDB for Master is missing alot of content that has to be loaded

### Expected behaviour

Content to load, NPC SPAWN, GAMEOBJECT, AND QUEST CHIAN, BACKPORTED EXPAN?Sions

### Steps to reproduce the problem

STEP 1: Install WOW from BATTLE-NET
STEP 2: Compile Trinity Core
STEP 3: Configure BNET  & WORLD conf
STEP 4: Run BNET n WORLD exe
SEE ALOT of warnings
STEP 5: Read DBError.log

### Branch

master

### TC rev. hash/commit

DBError.log
------------
https://drive.google.com/file/d/1AmxZq4uIUZm4J8TLIhhzsYh3z8v8SRH7/view?usp=sharing

BNet.log
-----------
https://drive.google.com/file/d/1Ph7fU408pmzyM4t01baBg56Vl2oUHz47/view?usp=sharing

Server.log
------------
https://drive.google.com/file/d/1KQ0dBlLqosVE9a-dzuUCrNYxIahQEEvd/view?usp=sharing

### Operating system

Windows 10 x64

### Custom changes

NONE

**Comment by Jinnaix** [comment]
Hello SorrowHarvest.
This is to be expected and not considered a bug.
Content stops somewhere mid-catacylsm. Anything afterwards is more or less Sandbox state at the moment.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15829
