### ISSUE TITLE
DB/Locale/Ru. The translation for the quest 10584 has been corrected.

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#26844]
### Description

The first letter " C " in task 10584 on the English layout. It should be in Russian.

### SQL fix

```sql
UPDATE `quest_template_locale` SET `Objectives`='С помощью протовольтаического магнетоколлектора поймайте 5 электроменталей.' WHERE `ID`=10584 AND `locale`='ruRU';
```

### Branch

3.3.5

### TC rev. hash/commit

442efccd2e6446e30f9d5d1b2497b03c7b8397dc

**Comment by offl** [comment]
Just out of curiosity, how did you found that? Is it displayed differently in Russian client?

**Comment by kvolk2git** [comment]
> Just out of curiosity, how did you found that? Is it displayed differently in Russian client?

No. it is displayed in the same way, but when sorting sql, this quest is annoying.:)

**Comment by offl** [comment]
Those texts are original and were taken from retail(MoP, not 3.3.5)
Quest locale texts can be updated for the reasons like in #26842

There are reasons why we should never fix original typos, grammar and stuff like that in any kind of texts, especially in all English texts
Those changes takes time but can be easily lost and in general creates more problems than solves
