### ISSUE TITLE
TrintyCore 3.3.5 Quest ,The Big Bone Worm ; Quest ID 10930

### ISSUE THREAD

**Issue by Aussiewoolf** [TrinityCore/TrinityCore#26854]
### Description

https://tbc.wowhead.com/quest=10930/the-big-bone-worm .  

The Quest ask you kill some Decrepit Clefthoof ,NPC ID 22105 in The Bone Wastes and play the  Fumper Item ID 31825 to summon https://tbc.wowhead.com/npc=22038/haishulud . 

Upon killing over 90+ mobs the Fumper was unable summon Haishulud. This quest is not spawning Haishulud and the Fumper spell seems to stop too early and the NPC corpse despawns before Fumper spell finish's.

This quest has been tested multiple times and still no luck with spawn of NPC 22038.

### Expected behaviour

Upon Killing Decrepit Clefthoof ,NPCID 22105 and Use Fumper ,ItemID 31825 . Random amount of kills and use of the Fumper should spawn Haishulud ,NPCID 22038 and upon kill reward item .https://tbc.wowhead.com/item=31826/enormous-bone-worm-organs.  A link to what should happen https://www.youtube.com/watch?v=jbyFVy11zQg

### Steps to reproduce the problem

https://tbc.wowhead.com/quest=10930/the-big-bone-worm 
https://tbc.wowhead.com/npc=22105/decrepit-clefthoof
https://tbc.wowhead.com/item=31825/fumper
https://tbc.wowhead.com/npc=22038/haishulud 
https://tbc.wowhead.com/item=31826/enormous-bone-worm-organs

Start Quest 10930
Kill Decrepit-clefthoof ,npcid 22105
Use Item Fumper ,itemid 31825
That is where the problems exists

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 7c7b476 2021-08-16 22:42:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows X64

### Custom changes

None

**Comment by Faq** [comment]
About this q is report #11418, better would be that You post there with Your revision.

P.s. Dont use wowhead links, but https://tcubuntu.northeurope.cloudapp.azure.com/aowow/
