### ISSUE TITLE
Can't loot mobs after killing. Autoloot is working

### ISSUE THREAD

**Issue by Saurelius** [TrinityCore/TrinityCore#26858]
### Description

After killing mobs i can't loot items. Autoloot is working. Also I can't equip bags. Autoequipping of soulbound unique bags works (additem command). After adding of bag it equippes in bag slot automatically.

### Expected behaviour

Selective looting should work. I must have possiblity to equip bags by clicking mouse button.

### Steps to reproduce the problem

Problem persists at all mobs in the world

### Branch

master

### TC rev. hash/commit

TrinityCore rev. bca465a56941 2021-08-20 09:41:13 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.72.0
Using MySQL version: 5.7.35
Using CMake version: 3.21.1
Compiled on: Windows 10.0.14393
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in E:/GAMEDATA/91039804/maps. Total size: 1451709970 bytes
vmaps directory located in E:/GAMEDATA/91039804/vmaps. Total size: 3358695645 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21081

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
update your core.

**Comment by jackpoz** [comment]
Duplicate of https://github.com/TrinityCore/TrinityCore/issues/26853 , fixed by https://github.com/TrinityCore/TrinityCore/commit/5498ea6aae4521bc5ed48bac78fa0ac9a73c99a8
