### ISSUE TITLE
DB/Locale/ruRU - Translation of quests 376, 498, 1200, 3521

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#26850]
### Description

Added translation of quests 376, 498, 1200, 3521. The data for translating is taken from classic_wowhead_com.

### SQL fix

```sql
-- Add ruRU translation for the quest 376
UPDATE `quest_template_locale` SET `VerifiedBuild`=0, `Objectives`='Ученице Элрет нужно 4 лапы падальщика и 4 крыла сумеречницы.' WHERE `ID`=376 AND `locale`='ruRU';

-- Add ruRU translation for the quest 498
UPDATE `quest_template_locale` SET `VerifiedBuild`=0, `Objectives`='Освободите Друлла и Тог\'тара по поручению Круска с мельницы Таррен.' WHERE `ID`=498 AND `locale`='ruRU';

-- Add ruRU translation for the quest 1200
UPDATE `quest_template_locale` SET `VerifiedBuild`=0, `Details`='Силы оставили меня. Мне необходима твоя помощь!$b$bВ давние времена на этом месте был храм Элуны. К несчастью, он был разрушен, когда порча Древнего бога просочилась из-под земли и осквернила священный Лунный колодец.$b$bАку\'май, слуга Древнего бога, поднялся из глубин.$b$bСектанты Сумеречного Молота объединились с нагами в борьбе за эти земли. Сектанты, ведомые Келрисом, приносят Аку\'май невинные жертвы.$b$bУбей Келриса и принеси его голову Сельгорму в Дарнасс,$n.', `Objectives`='Принесите голову повелителя сумрака Келриса Рассветному дозорному Селгорму в Дарнасс.' WHERE `ID`=1200 AND `locale`='ruRU';

-- Add ruRU translation for the quest 3521
UPDATE `quest_template_locale` SET `VerifiedBuild`=0, `Details`='Мы могли бы помочь Иверрону: я знаю противоядие, которое нейтрализует действие яда. Но для него мне нужны некоторые ингредиенты.$B$BМне понадобятся гиацинтовые грибы. Их можно найти под деревьями или добыть у греллей к югу отсюда – похоже, они им по вкусу. Еще мне нужны лунные лилии, что растут только вокруг прудов.$B$BПоследний ингредиент добыть сложнее всего. Это лимфа тех самых чащобных тенетников, что отравили Иверрона.',`Objectives`='Соберите 7 гиацинтовых грибов, 4 лунные лилии и 1 порцию лимфы чащобного тенетника и принесите Дирании Серебряное Сияние в Тенистую долину.', `CompletedText`='Найди Иверрона возле Паучьего логова.' WHERE `ID`=3521 AND `locale`='ruRU';
```

### Branch

3.3.5

### TC rev. hash/commit

442efccd2e6446e30f9d5d1b2497b03c7b8397dc

**Comment by offl** [comment]
https://ru.tbc.wowhead.com/quest=376 is closer to wotlk, as you can see required count was raised at some point

**Comment by kvolk2git** [comment]
> https://ru.tbc.wowhead.com/quest=376 is closer to wotlk, as you can see required count was raised at some point
Here everything was somewhat different. 
In the classic version, it was necessary to get 6 items: https://classic.wowhead.com/quest=376/the-damned
In the TBC version, we also observe that the number for completing the quest has not changed, all the same 6 items: https://tbc.wowhead.com/quest=376/the-damned

But everything was changed with the release of the wotlk patch, the number of items was changed and lowered to four, the website of the ahiv site of the red rocket tells us about this. The patch was released in June 2010, the archived version of the page from December 2010 tells us that the number of items was lowered from 6 to 4.
https://web.archive.org/web/20101204090001/wowhead.com/quest=376

Therefore, the task itself must be adjusted. Now there are 6 items in the database, and there should be 4. This figure is also indicated in all localizations for the quest.

**SQL Fix**:

`
-- Adjusted the number of items required to complete the quest
UPDATE `quest_template` SET `VerifiedBuild`=0, `LogDescription` = 'Novice Elreth requires 4 Scavenger Paws and 4 Duskbat Wings.', `RequiredItemCount1` = 4, `RequiredItemCount2` = '4' WHERE `ID` = 376;

-- Add ruRU translation for the quest 376
UPDATE `quest_template_locale` SET `VerifiedBuild`=0, `Objectives`='Ученице Элрет нужно 4 лапы падальщика и 4 крыла сумеречницы.' WHERE `ID`=376 AND `locale`='ruRU';

`

**Comment by offl** [comment]
4 december is Cata https://web.archive.org/web/20101204090001/wowhead.com/quest=376
From my experience everything archived in ~november(?, don't remember)-december is Cata
Jan 2010 https://web.archive.org/web/20100120200343/http://wow.allakhazam.com/db/quest.html?wquest=376
Aug 2010 https://web.archive.org/web/20100815054606/http://thottbot.com/q376
May 2010 https://youtu.be/lqON1WXX7b8?t=122
Patch 4.0.3a (2010-11-23): Updated for Cataclysm, replacing H [2] The Damned. < it's unrealistic that they updated it twice, first time at the end of WotLK and second time in 4.0.3

And quest_template is wdb data and I have a feeling all those fields are correct in nearly all quests

**Comment by kvolk2git** [comment]
Of course, I will not argue on this issue, but all these nuances generate more questions than answers.
