### ISSUE TITLE
World LegionV2 repack huge RAM consume 

### ISSUE THREAD

**Issue by only47** [TrinityCore/TrinityCore#26857]
### Description

Hello, i got a problem with RAM usage on Repack 7.3.5 LegionV2. Server uses 13GB+ of RAM when i start up worldserver and never goes down. When i run the same repack on my desktop it consume at start 11GB then after 15minutes it lower to ~800MB. What can couse this problem? i set all important options like instancegrid = 0 mapgrids = 0 and unloadgrids = , i disabled auction bot and invasions, but server still sonsume 13GB RAM+ and never lower this amount. Thanks in advance

### Expected behaviour

Ram usage lower than 5GB

### Steps to reproduce the problem

Starts repack on VPS OVH

### Branch

3.3.5

### TC rev. hash/commit

Legion AshamaneCore

### Operating system

Windows Server 2019

### Custom changes

none

**Comment by Aokromes** [comment]
we don't support 7.3.5 nor repacks.

**Comment by only47** [comment]
I just want to know why it consumes huge amount of RAM, i dont want any support to do somthing with it ;/

**Comment by MaxtorCoder** [comment]
Still no support, ask the creator thanks.

**Comment by only47** [comment]
they doesnt know i asked them already eh thanks anyway...

**Comment by Aokromes** [comment]
also we are not AshamaneCore.

**Comment by Faq** [comment]
@only47 that is the same like having BMW and go to Audi dealer to ask why my BMW is burning so much fuel.
AC and TC are different cores and we can answer only about TC things.

**Comment by r00ty-tc** [comment]
Having said that. Check the following in worldserver.conf

BaseMapLoadAllGrids = 0
GridUnload = 1

Just my suspicion, but if they're the other way round they would cause that kind of memory usage with legion extra maps etc. Setting them as above should in theory solve the problem.

**Comment by lyosky** [comment]
change spell id's maxvalue to a smaller one,can be save your RAM
