### ISSUE TITLE
Spells with durationEntry 407 are not showing on client

### ISSUE THREAD

**Issue by lineagedr** [TrinityCore/TrinityCore#26865]
### Description

When you cast a spell with durationEntry 407. For example: Every Man for Himself https://wotlk-twinhead.twinstar.cz/?spell=59752

You won't see it appear top right where your buffs are.

it's weird I believe it only affects spells with durationEntry 407 (100ms duration). 

After changing the duration of Every Man for Himself to 574 (200ms duration) it showed on cast.

### Expected behaviour

You should be able to see the buff top right. 
![407](https://user-images.githubusercontent.com/12139798/131040190-19366906-050d-43d6-a18f-96b286c09be5.png)

### Steps to reproduce the problem

1. Cast any spell with the 407 durationEntry.
2. Notice that it doesn't show top right where your buffs are.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/587904ac68aae307a0d24ff77492a7ae1d4f7323

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Riztazz** [comment]
Aren't TC auras updated every 500ms or so? I seem to recall it working like that hence you will have issues like described, i could be wrong though

**Comment by lineagedr** [comment]
@Riztazz Then the 200ms ones wouldn't show. Anything >100ms is showing

**Comment by Riztazz** [comment]
You could try commenting out the ifs and just updating the map every tick and see what happens
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/Auras/SpellAuras.cpp#L803

**Comment by sirikfoll** [comment]
Try reducing the value of config `MapUpdateInterval` in worldserver.conf file, should start to show around 90 or less

**Comment by lineagedr** [comment]
@sirikfoll  It shows now, thanks.

**Comment by Faq** [comment]
@lineagedr please write exactly changing what parameter to what value helped for you.

**Comment by lineagedr** [comment]
@Faq Exactly what sirikfoll said 90 or less in my case 90.

**Comment by CraftedRO** [comment]
2a587e5ac43f this is most likely invalid since on TC it does behave same as on wotlk classic ptr (it only appear for ~a second)


https://github.com/TrinityCore/TrinityCore/assets/24683355/fb37b661-229d-4f0e-8350-79b093631a68
