### ISSUE TITLE
DB/SQL update 2021_08_07_00_hotfixes.sql

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#26861]
### Description

I performed a complete set of DBs including map extraction and related items. Everything went well. The implementation of TDB 910.21081 world and hotfixes + auth + characters took place at the beginning. All steps according to the assembly instructions were successful. The auth DB was successful. When starting DB world, the starting process with the update process started fine - an error occurred while applying update 2021_08_07_00_hotfixes.sql. [(see statement)](https://pastebin.pl/view/5f19da89).
It starts with a mistake
ERROR 1060 (42S21) at line 9: Duplicate column name 'Unused910' 
then it continues
ERROR 1060 (42S21) at line 17: Duplicate column name 'BarberShopCameraHeightOffsetScale'
and continue
ERROR 1060 (42S21) at line 19: Duplicate column name 'Unknown910_11'
and continue
ERROR 1060 (42S21) at line 20: Duplicate column name 'Unknown910_12'
I didn't even go on.

I implemented this update manually (so where the DB was written correctly) and then I intentionally modified this update so that it is no longer loaded. After running world.exe again, we displayed the following error: [link](https://pastebin.pl/view/c11c04a7)

### Expected behaviour

DB update should be fine - no errors

### Steps to reproduce the problem

1.  update SQL : [link](https://github.com/TrinityCore/TrinityCore/blob/master/sql/old/9.x/hotfixes/21071_2021_08_18/2021_08_07_00_hotfixes.sql)
2. this SQL update failed
3. the update should run without errors

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 90b81a212e24 2021-08-23 20:03:40 +0200 (master branch) (Win64, Debug, Static) (worldserver-daemon)

### Operating system

Windows 10 Pro  ver. 20H2  Build : 19042.1165

### Custom changes

don't have any changes applied

**Comment by jackpoz** [comment]
> The implementation of TDB 910.21081 world and hotfixes + auth + characters took place at the beginning

if you are using TDB 910.21081 then you don't need to import https://github.com/TrinityCore/TrinityCore/blob/master/sql/old/9.x/hotfixes/21071_2021_08_18/2021_08_07_00_hotfixes.sql as that has already been applied.

Did you let worldserver import TDB or did you import that manually ? Could you go through the step of importing TDB again, dropping the needed databases (it should be `world` and `hotfixes` but better ask to someone who knows about master branch more)

**Comment by shamage** [comment]
this is the problem that TDB updates itself without my intervention and this error occurs with the mentioned SQL update. please see my link to pastebin there it is clearly visible how the process goes and where it ends with the error. The other things I did manually are just my attempts to connect it.

I have already done such a TDB assembly several times successfully, but this time the error is clearly shown when trying to apply an SQL update called 2021_08_07_00_hotfixes.sql

The bugs that are listed in the bug list are due to the fact that the items already exist under those names (at least that's how I understood it) - and it looks like this update contains some commands to change values as duplicates.

A specific example in this update:

9     `ALTER TABLE `character_loadout` ADD` Unused910` tinyint (11) NOT NULL DEFAULT '0' AFTER `Purpose`;`

An attempt to execute this command will result in an error with the description :

Updating Hotfixes database...
>> Applying update "2021_08_07_00_hotfixes.sql" 'EDF8A72'...
mysql: [Warning] Using a password on the command line interface can be insecure.
 
ERROR 1060 (42S21) at line 9: Duplicate column name 'Unused910'
 
 
Applying of file 'E:/Source/Repos/TrinityCore Branch 9.1.0.39804/sql/old/9.x/hotfixes/21071_2021_08_18/2021_08_07_00_hotfixes.sql' to database 'hotfixes' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Hotfix database, see log for details.

A full detailed description of the process can be found on PasteBin ==> [klikk here  ](https://pastebin.pl/view/5f19da89)

**Comment by shamage** [comment]
>if you are using TDB 910.21081 then you don't need to import https://github.com/TrinityCore/TrinityCore/blob/master/sql/old/9.x/hotfixes/21071_2021_08_18/2021_08_07_00_hotfixes.sql as that has already been applied.

do I mean that automatic updates should also be turned off for world / hotfixes?

**Comment by shamage** [comment]
I performed a new assembly with the current configuration : 
TrinityCore rev. 6ec73a765937+ 2021-08-31 13:48:40 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

everything went well without errors - automatic update no longer required implementation which I present here but starts with the update 2021_08_21_00_world_2018_03_03_00_world_335.sql .

Podrobné informácie o procese spustenia nájdete na :  [link](https://pastebin.com/N0J2wL50)

**Comment by shamage** [comment]
The bug didn't occur with this version of TC anymore - I think I can close it.
