### ISSUE TITLE
DB/Quest: Duke Hydraxis is not offering "Poisoned Water"

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26872]
### Description

The [Poisoned Water](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6804) quest is required to progress with Duke Hydraxis' quests.

The quest is in the DB but not assigned to Duke  -  [as seen here](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=13278)

### Expected behaviour

Duke Hydraxis requires and gives both [Poisoned Water](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6804) AND  [Stormers and Rumblers](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6805) to continue his quest line.

### Steps to reproduce the problem

1. Head to Azshara - 79, 73
2. Duke will offer Stormers and Rumblers (But not Poisoned Water)
3. If you complete Stormers and Rumblers the Poisoned Water quest still does not appear
4. Quest is in Trinity DB but does not look assigned to Duke

<details>

![image](https://user-images.githubusercontent.com/66294837/131235769-5f9eb352-688f-4a6b-94d2-f931f7905837.png)

</details>

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 7c7b476 2021-08-16 22:42:23 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by Aokromes** [comment]
The subject of this article was removed from World of Warcraft in patch 3.0.8.

https://wowwiki-archive.fandom.com/wiki/Quest:Poisoned_Water
