### ISSUE TITLE
Worldserver crashes after update commit 8a4e111

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#26887]
### Description

After updating the repository with the commit 8a4e1119ac21e2d1112d1717337597fe073e495f the server crashes. 
[Crashes Log](https://gist.github.com/osleyder85/8c89a8dd563bc1bfd1489602cfa35150)

### Expected behaviour

The server must not crash.

### Steps to reproduce the problem

1. Update from TC master.
2. Compile full.
3. Run Worldserver.exe

### Branch

master

### TC rev. hash/commit

8a4e1119ac21e2d1112d1717337597fe073e495f

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Faq** [comment]
Please use gist and this is not full crashlog.

**Comment by Flashaholic88** [comment]
have the same error.
hopefully it's okay now with the gist: [Here](https://gist.github.com/Flashaholic88/976a31abb91d1e72d6873780517b0705)

**Comment by Faq** [comment]
@Flashaholic88 that is server log not crashlog :)

**Comment by Flashaholic88** [comment]
> @Flashaholic88 that is server log not crashlog :)

Updated

**Comment by osleyder85** [comment]
Solved in commit 7e09deea3a6784c7abd44cb2893ae19dbf95f9f1
