### ISSUE TITLE
[NPC] Marshal Mcbride (197)

### ISSUE THREAD

**Issue by xXBentRealityXx** [TrinityCore/TrinityCore#26902]
### Description

Literally just fixes Marshal Mcbride's position because it bothered my OCD, data gathered from one of my 9.1.0 (40000) sniffs.

### SQL fix

```sql
-- Fix positions of some NPCs
UPDATE `creature` SET `position_x` = -8913.423828125, `position_y` = -137.541671752929687, `position_z` = 80.8928070068359375, `orientation` = 1.988220691680908203, `VerifiedBuild` = 40000 WHERE `guid` = 279961;
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0a83f748766c+ 2021-09-08 22:07:01 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2u  20 Dec 2019 (library: OpenSSL 1.0.2u  20 Dec 2019)
Using Boost version: 1.72.0
Using MySQL version: 5.6.39
Using CMake version: 3.19.7
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 1451709970 bytes
vmaps directory located in ./vmaps. Total size: 3361529943 bytes
mmaps directory located in ./mmaps. Total size: 11928261288 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21081

**Comment by mdX7** [comment]
would've never noticed this, holy cow xD
![grafik](https://user-images.githubusercontent.com/12143653/134206592-3760d43f-4ff2-4782-badb-961c42ebff7f.png)
