### ISSUE TITLE
[Gobject] Underbelly Elixir position 

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26919]
### Description

Map: 571; Zone: 4395; Area: 4560;
X: 5719; Y: 684; Z: 614

### Expected behaviour

it seems that need to raise it a little bit
![WoWScrnShot_091621_224710](https://user-images.githubusercontent.com/77268574/133677608-e37fd970-7b5d-47f2-9b9e-1f465f493a09.jpg)

### Steps to reproduce the problem

https://www.wowhead.com/item=44012/underbelly-elixir

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by offl** [comment]
What .gob near returns?

**Comment by gygyti** [comment]
> 
> 
> What .gob near returns?

 100255 (Entry: 193610) - [Underbelly Elixir X:5720.549805 Y:676.020020 Z:612.315002 MapId:571]

**Comment by offl** [comment]
Position is correct, the boat is in wrong place (https://github.com/TrinityCore/TrinityCore/issues/25898, https://github.com/TrinityCore/TrinityCore/issues/25898#issuecomment-916357245)
