### ISSUE TITLE
SQL account online

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26923]
### Description

I will try to explain the problem. 
when you log into your account, where you choose a character to start playing for:
then
auth.account online set to 1 - ok we're really online.

however, the problem is that when you choose your character and enter the game , then auth.account online set to 1 again

### Expected behaviour

i think this is an extra load on the sql server. There is no need to update the value if it already matches. 

### Steps to reproduce the problem

check auth.account and enter the game
(you can check it with triggers)

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by jackpoz** [comment]
Are you referring to some particular lines of code or ?

**Comment by gygyti** [comment]
> 
> 
> Are you referring to some particular lines of code or ?

i think yes, when you enter the game, a request is made to the auth database

**Comment by jackpoz** [comment]
When you say "if it matches already" you mean if one has logged already with another character ? How does one know if a value matches without checking it with a query ? In mysql SELECT+UPDATE is more expensive than a simple UPDATE

**Comment by gygyti** [comment]
> 
> 
> When you say "if it matches already" you mean if one has logged already with another character ? How does one know if a value matches without checking it with a query ? In mysql SELECT+UPDATE is more expensive than a simple UPDATE

"if it matches already" I mean, the server sends a request to Mysql: UPDATE `online` = 1, but this is not required, since` online` is already 1. This happens when you log in to the game (but before that in your account) - but why? if you log into your account and the online value is already 1
update is an extra iteration when entering the game

**Comment by CraftedRO** [comment]
I found the way to remove the second "enter world" update on auth.account online and it works it will only send the update query (LOGIN_UPD_ACCOUNT_ONLINE) once elsewhere (not sure where) when you login credentials but I have no idea if this is really a thing to do or not:

those 3 lines can be deleted and it will build without problem:

https://github.com/TrinityCore/TrinityCore/blob/39bebe6a653bdd65160aa7f9fef6501d43884079/src/server/game/Handlers/CharacterHandler.cpp#L1278
