### ISSUE TITLE
(DB/Quest) Bitter Rivals Hardlocks Progress for other players.

### ISSUE THREAD

**Issue by banehammer** [TrinityCore/TrinityCore#26920]
### Description

Bitter Rivals (ID: 310) is a hardlocked quest

Jarven (ID: 1373) wont reset his orientation after waypoints are done.

And Guarded Thunderbrew Barrel (ID: 269) dont respawn which hardlockes the quest for other players

![WoWScrnShot_091621_221901](https://user-images.githubusercontent.com/87540548/133680221-09239028-c1fd-4903-aab2-ea3f8aefcd96.jpg)
.

### Expected behaviour

Guarded Thunder Brew Barrel should respawn again.

Jarven Thunderbrew should return to this original orientation.

### Steps to reproduce the problem

1. q add 310
2. Buy the Thunder Ale from Innkeeper Belm
3. Go the Basement of the Thunderbrew Distillery and do the quest.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/4b028e599e06b4f7501298dc3410be89616c9720

### Operating system

W10

### Custom changes

None

**Comment by malcrom** [comment]
Tested fix and works perfectly.

```
-- Fix Quest 308 "Distracting Jarven"
UPDATE `smart_scripts` SET `action_param1`=0, `action_param2`=0 WHERE `entryorguid`=1373 AND `id`=3;
UPDATE `smart_scripts` SET `action_param1`=46,`action_param2`=0 WHERE `entryorguid`=1373 AND `id`=4;
UPDATE `smart_scripts` SET `target_type`=8, `target_o`=0.977384 WHERE `entryorguid`=1373 AND `id`=11;
DELETE FROM `smart_scripts` WHERE `entryorguid`=1373 AND `id`=12;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`event_type`,`event_chance`,`event_param1`,`action_type`,`action_param1`,`action_param2`,`target_type`,`comment`) VALUES
(1373,0,12,40,100,13,133,1,1037,1, "Jarven Thunderbrew - On WP 13 Reached - Respawn Closest Gameobject 'Guarded Thunder Ale Barrel'");
```
