### ISSUE TITLE
Ranged Weapons Bugs(?)

### ISSUE THREAD

**Issue by banehammer** [TrinityCore/TrinityCore#26922]
### Description

With ranged weapons and casts I can shoot/cast through big trees and obstacles.

When mobs are coming closer and your character is going into "near attack mode" you will have those 2 red messages:

![WoWScrnShot_091621_223155](https://user-images.githubusercontent.com/87540548/133682063-2ac21654-97f0-4e0c-b7ce-fa5d03d52eec.jpg)

### Expected behaviour

You shouldnt be able to shoot/cast through big obstacles/trees. (AzerothCore has this fixed)

I dont know about those 2 red messages if they are "normal" but I guess not so.

### Steps to reproduce the problem

1. Create a class which can cast (Priest) or simply a hunter
2. Attack mobs which are behind a tree

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/4b028e599e06b4f7501298dc3410be89616c9720

### Operating system

W10

### Custom changes

None

**Comment by Aokromes** [comment]
not a bug.
