### ISSUE TITLE
Realm first achievements not granted

### ISSUE THREAD

**Issue by banehammer** [TrinityCore/TrinityCore#26921]
### Description

Realm first achievements are not granted after reaching Level 80

### Expected behaviour

Realm first achievements shall be granted after reaching Level 80

### Steps to reproduce the problem

0. Create a new realm (duh...)
1. Create a new character
2. .character level 80
3. ??? Please give Realm First! achievement please

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/ee73948a64fc3d767d37cd3cc7f44358c5274b83

### Operating system

W10

### Custom changes

None

**Comment by Shauren** [comment]
.gm off

**Comment by banehammer** [comment]
![WoWScrnShot_091621_222816](https://user-images.githubusercontent.com/87540548/133681359-c05ad6a6-0b9e-4a90-9915-52cc5909e5c8.jpg)

GM Mode was off
