### ISSUE TITLE
Quest: Lohn'goron, Bow of the Torn-heart

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#2692]
Hi.

This quest (Lohn'goron, Bow of the Torn-heart) is not available from the NPC. It's part of a huge chain and.. simpy not offered.
http://www.wowhead.com/quest=10537

Version: 3.3.5a (12340)
Core revision: Trinity Core f960fcce6540+
Database revision: TDB 335.11.41

**Comment by Rushor** [comment]
can someone confirm, that blizz already used phasing in tbc?

**Comment by Killyana** [comment]
Need someone to sniff this npc (maybe a phasing aura)
``` sql
DELETE FROM `creature` WHERE `guid`= XXXXX; -- 1 free guid set by TC
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `curhealth`, `spawndist`, `MovementType`) VALUES
(@CGUID, 21318, 530, 1, 1,  -3800.38, 2601.1, 90.143, 5.48163, 180, 6986, 0, 0);

**Comment by Aokromes** [comment]
No, phasing is wow 3+ only. Maybe some invisibility aura, but no phasing.

**Comment by Killyana** [comment]
It looks fine for me.
