### ISSUE TITLE
[quest] Wanted: Arcatraz Sentinels

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26935]
### Description

it is impossible to complete the task, since it does not count the kill Arcatraz Sentinel slain (5)

### Expected behaviour

must count kills

### Steps to reproduce the problem

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11389

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by CraftedRO** [comment]
I can confirm on f30510566b1a but after I removed they'r SAI I coud complete it , so most likely is something wrong there .

**Comment by CraftedRO** [comment]
well now they count for quest but for some reason they appear as dead out of combat , when you engage them in combat they'r health bar raise at 40% , not sure if this is right .

![WoWScrnShot_100221_160400](https://user-images.githubusercontent.com/24683355/135717581-fa1cda0b-f337-47a1-822f-6fd4b3969a9b.jpg)
