### ISSUE TITLE
Warlock/Spell: Life Tap strange behaviour

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26938]
### Description

[Life Tap rank 2](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=1455) used below hp limit does kill you and revive.
Update: Seems same at rank 6 and below.

https://user-images.githubusercontent.com/24683355/134321786-c58836b7-3f6e-49f0-a287-85e1afa594ff.mp4

### Expected behaviour

If I remember right Life Tap shoudn't kill you but warn Fizzled message.

### Steps to reproduce the problem

Create a warlock and level 16+ I so you can get life tap rank 2
Spamm Life Tap.

### Branch

3.3.5

### TC rev. hash/commit

c8061d8ba620

### Operating system

Debian 10 x64

### Custom changes

None I guess

**Comment by CraftedRO** [comment]
Is Life Tap supposed to miss or crit ?

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/pull/27003

**Comment by Keader** [comment]
https://github.com/TrinityCore/TrinityCore/pull/27003
