### ISSUE TITLE
DB /  Quest series Alliance - the order of the tasks is broken

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#26936]
### Description

task order is broken - after completing the Lions for Lambs task, no other task is offered

### Expected behaviour

Quest series Alliance : 

1. [Beating Them Back!](https://www.wowhead.com/quest=28762/beating-them-back)
2. [Lions for Lambs](https://www.wowhead.com/quest=28770/lions-for-lambs)
3. [Join the Battle!](https://www.wowhead.com/quest=28785/join-the-battle)
4. [They Sent Assassins](https://www.wowhead.com/quest=28791/they-sent-assassins)
5. [The Rear is Clear](https://www.wowhead.com/quest=28817/the-rear-is-clear)

these tasks should gradually be accepted

### Steps to reproduce the problem

1. choose a character from the menu and start the task in Northshire.
2. also complete the task Lions for Lambs 
3. after completing the second Lions for Lambs task, you are not offered another task

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0b882b2fa430 2021-09-18 15:00:43 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
Using MySQL version: 5.7.32
Using CMake version: 3.20.5
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1451709970 bytes
vmaps directory located in ./vmaps. Total size: 3361529943 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21081

### Operating system

Win 10 Pro 

### Custom changes

I applied this fix to resolve this issue : 

```sql
-- Paladin, Draenei
UPDATE `quest_template_addon` SET `ID`='28785', `MaxLevel`='0', `AllowableClasses`='2', `SourceSpellID`='0', `PrevQuestID`='28770', `NextQuestID`='28793', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28785');

-- Mage

UPDATE `quest_template_addon` SET `ID`='28784', `MaxLevel`='0', `AllowableClasses`='128', `SourceSpellID`='0', `PrevQuestID`='28769', `NextQuestID`='28792', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28784');

-- Priest

UPDATE `quest_template_addon` SET `ID`='28786', `MaxLevel`='0', `AllowableClasses`='16', `SourceSpellID`='0', `PrevQuestID`='28771', `NextQuestID`='28794', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28786');

--  Warlock

UPDATE `quest_template_addon` SET `ID`='28788', `MaxLevel`='0', `AllowableClasses`='256', `SourceSpellID`='0', `PrevQuestID`='28773', `NextQuestID`='28796', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28788');

-- Hunter

UPDATE `quest_template_addon` SET `ID`='28780', `MaxLevel`='0', `AllowableClasses`='4', `SourceSpellID`='0', `PrevQuestID`='28759', `NextQuestID`='28791', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28780');

-- Rogue

UPDATE `quest_template_addon` SET `ID`='28787', `MaxLevel`='0', `AllowableClasses`='8', `SourceSpellID`='0', `PrevQuestID`='28772', `NextQuestID`='28795', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28787');

-- Warrior

UPDATE `quest_template_addon` SET `ID`='28789', `MaxLevel`='0', `AllowableClasses`='1', `SourceSpellID`='0', `PrevQuestID`='28774', `NextQuestID`='28797', `ExclusiveGroup`='0', `RewardMailTemplateID`='0', `RewardMailDelay`='0', `RequiredSkillID`='0', `RequiredSkillPoints`='0', `RequiredMinRepFaction`='0', `RequiredMaxRepFaction`='0', `RequiredMinRepValue`='0', `RequiredMaxRepValue`='0', `ProvidedItemCount`='0', `SpecialFlags`='0', `ScriptName`='' WHERE (`ID`='28789');

--  Monk, 
```

if I am wrong in some notes, please correct me - thank you

**Comment by mdX7** [comment]
recently fixed in 6c37d12a691bfc0083c9c5ead4ad7ed7b3fb8a11

**Comment by shamage** [comment]
yes i just noticed it was fixed  : link :https://github.com/TrinityCore/TrinityCore/commit/6c37d12a691bfc0083c9c5ead4ad7ed7b3fb8a11

**Comment by shamage** [comment]
@mdX7 : you are right, i will remember it for the future
