### ISSUE TITLE
DB/PVP Talent slot permanent available - wrong display

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#26934]
### Description

When a player gains the maximum level and completes all PVP talent slots, the message about the possibility of filling in PVP talents does not go out, but he still reports the possibility to choose slots even if he should not.

### Expected behaviour

After selecting all free slots for a player, the free slot message should stop appearing.

### Steps to reproduce the problem

1. Reach the maximum level needed to complete PVP talent slots
2. Fill in the PVP talent slots that you want for the player
3. note that even if you select all PVP talent slots for the player and then close the window, you will still see a message that you have PVP talent slots available, which you can turn off even if you have already filled them all.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0b882b2fa430 2021-09-18 15:00:43 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
Using MySQL version: 5.7.32
Using CMake version: 3.20.5
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1451709970 bytes
vmaps directory located in ./vmaps. Total size: 3361529943 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21081

### Operating system

Windows 10 Pro  ver. 20H2 Build 19042.1237

### Custom changes

none

**Comment by shamage** [comment]
![Ashampoo_Snap_utorok 21  septembra 2021_20h33m17s_003_](https://user-images.githubusercontent.com/7515044/134229860-bbd92e1b-4602-4be2-a5f5-a7087ae98cf7.png)

**Comment by shamage** [comment]
Loook at a video :  https://youtu.be/YoTiv3amr6w

**Comment by Shauren** [comment]
Fixed in b821a729733db0d3742b4aefe05e5a8305724f66
