### ISSUE TITLE
[spell] Dark Reckoning 69483

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26941]
### Description

The spell Dark Reckoning (6948**3**) works incorrectly. it should use Dark Reckoning (6948**2**) at the end, but it doesn't happen 

https://www.wowhead.com/npc=36829/deathspeaker-high-priest
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=69482
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=69483

### Expected behaviour

it should use Dark Reckoning (6948**2**) at the end

### Steps to reproduce the problem

start fight with npc=36829 deathspeaker high priest

.npc add temp 36829

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

Debian 10 x64

### Custom changes

none

**Comment by Keader** [comment]
```cpp
class spell_lady_dark_reckoning : public AuraScript
{
    PrepareAuraScript(spell_lady_dark_reckoning);

    void OnPeriodic(AuraEffect const* aurEff)
    {
        PreventDefaultAction();
        if (Unit* caster = GetCaster())
        {
            uint32 spellId = GetSpellInfo()->Effects[0].TriggerSpell;
            caster->CastSpell(GetTarget(), spellId, aurEff);
        }
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_lady_dark_reckoning::OnPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};
```

**Comment by gygyti** [comment]
does it work in newer versions? should i upgrade my core?
