### ISSUE TITLE
Dungeon: Blackrock Depths - Upper City Incorrect Spawn location

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26947]
### Description

The starting spawn point for the Blackrock Depth- Upper City is incorrect.

Currently, Prison and Upper City both spawn you into the Dungeon at the very beginning.

### Expected behaviour

The Blackrock Depths - Upper City dungeon is suppose to spawn you into Shadowforge City.

I am not familiar with the exact co-ordinates.

### Steps to reproduce the problem

1. Open Dungeon Finder and select "Blackrock Depths - Upper City"

<details>

![image](https://user-images.githubusercontent.com/66294837/134627122-588718d7-ff37-44ee-81da-c33531bff599.png)

PS: I dont know why I am locked out of Prison because I am level locked at 60 but currently this issue does save me the trouble of circling back to pre-shadowforge areas - however, it's still not Blizzlike and needs addressing

</details>

2. [How you do your group thing is on you - I use bots] - get a group and "Find Group"
3. Accept the call and enter the dungeon
4. You spawn at the beginning of the entrance which is shared with Prison

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 36300404d555 2021-09-23 22:10:41 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static) 

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
Not a bug, unfortunatelly
https://www.mmo-champion.com/threads/688600-Blackrock-Depths-Upper-City?p=7170209&viewfull=1#post7170209
https://gaming.stackexchange.com/questions/18455/how-do-i-know-what-dungeon-im-in
https://wowpedia.fandom.com/wiki/Blackrock_Depths?oldid=2435711#Dungeonfinder_Tips

Can be added as custom change if sql custom changes are a thing
Using https://wow.tools/dbc/?dbc=worldsafelocs&build=8.1.0.27934#page=1&colFilter[5]=230

It may be Flamelash Event Entrance or Upper City, I don't know

It's handled here:
```sql
SELECT * FROM lfg_dungeon_template WHERE NAME LIKE '%blackrock depths%'
```
