### ISSUE TITLE
Crash after 4 days of uptime

### ISSUE THREAD

**Issue by opiums9** [TrinityCore/TrinityCore#26956]
### Description

After 4 days of uptime we got a [crash](https://gist.github.com/opiums9/4f8b1f9a6507da4f29eddac3c6604c16)

### Expected behaviour

The server must not crash

### Steps to reproduce the problem

1. Start worldserver
2. Uptime 4 d 22 h 10 m
3. Strange crash

### Branch

3.3.5

### TC rev. hash/commit

58c1e4ce733c+

### Operating system

Debian 10.10 x64

### Custom changes

Arena 1v1, rochet2 multivendor_3.3.5, rochet2 dressnpcs_3.3.5

**Comment by Aokromes** [comment]
there is no such rev on clean trinitycore.

also, cannot reproduce
Online for 7 days, 3 hours, 39 minutes, 3 seconds

**Comment by Aokromes** [comment]
no one else reported same issue having a lot of over 4 days of uptimes.
