### ISSUE TITLE
DB/Item: Branch Of Cenarius Quest item drops from additional mob

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26959]
### Description

Quest item for The Branch of Cernius is supposed to drop off Geltharis as per quest dialogue

In TC, it is **also** dropping off Rare mob Prince Raze (NPC 10647)

### Expected behaviour

Quest is to obtain the item from Geltharis

### Steps to reproduce the problem

1. Undertake quest 1031 (From Anilia) "[The Branch of Cenarius](https://tbc.wowhead.com/quest=1031/the-branch-of-cenarius)"
2.  Head to 78, 43 (Xavian ) - Arch directly to your North
3. If Price Raze (He's a rare) is there, kill him and item will drop the quest item (TC DB lists 100% drop chance)
4. The only target for the item should be Geltharis - [as shown](https://tbc.wowhead.com/item=5461/branch-of-cenarius#dropped-by)

Prince Raze drops on [Classic](https://tbc.wowhead.com/npc=10647/prince-raze#drops) are very different to Trinity

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 3630040 2021-09-23 22:10:41 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by msoky** [comment]
windows 7 wow

**Comment by CraftedRO** [comment]
```sql
DELETE FROM `creature_loot_template` WHERE (`Entry` = 10647) AND (`Item` IN (5461));
```
