### ISSUE TITLE
DB/SQL update 2021_09_25_15_world.sql

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#26957]
### Description

After completing the entire world setup and then running world.exe, the update will be performed automatically. When updating 2021_09_25_15_world.sql, the system crashes and displays the error:

 ">> Applying update" 2021_09_25_15_world.sql "'59ECE5E' ...
mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1364 (HY000) at line 54: Field 'IsServerSide' doesn't have a default value "

Show error code : [link ](https://pastebin.pl/view/201d91a9)

command to table `areatrigger_template` expects to write to value 'IsServerSide' but part of command is missing item 'IsServerSide'

```sql
54    INSERT INTO `areatrigger_template` (`id`, `type`, `flags`, `Data0`, `Data1`, `Data2`,`Data3`, `ScriptName`) VALUES
55    (5077, 0, 2, 4, 9, 0, 0, 'at_mos_nether_rip');
```

Please, is it possible to fix this !? well thank you.

### Expected behaviour

The system should perform an automatic update without error.

### Steps to reproduce the problem

1. compile the world
2. implement DB
3. Run auth.exe and world.exe
4. monitor whether the DB is updated without errors

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 5134a8275270+ 2021-09-26 23:26:15 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

WEin 10 Pro  v. 20H2

### Custom changes

none

**Comment by shamage** [comment]
one of the possible solutions, but I'm not sure if the value for `IsServerSide` should be "0"

```sql
DELETE FROM `areatrigger_template` WHERE `id` IN (5077);
INSERT INTO `areatrigger_template` (`id`, `IsServerSide`, `type`, `flags`, `Data0`, `Data1`, `Data2`,`Data3`, `ScriptName`) VALUES
(5077, 0, 0, 2, 4, 9, 0, 0, 'at_mos_nether_rip');
```

**Comment by Shauren** [comment]
CUSTOOOOOOOOM,

but seriously, 2021_09_25_15_world.sql is not a file that exists in TrinityCore repository, last sql file on 25.09 has number 14.

**Comment by shamage** [comment]
You're right, I missed the data. Sorry for the useless topic.
