### ISSUE TITLE
Get attacked under hex

### ISSUE THREAD

**Issue by gygyti** [TrinityCore/TrinityCore#26951]
### Description

The mob 7856 will attack you, even if it is in hex (step back a ranged distance)

### Expected behaviour

he shouldn't attack at all 

### Steps to reproduce the problem

.npc add temp 7856
.cast 118
step back a ranged distance

### Branch

3.3.5

### TC rev. hash/commit

fece5bd

### Operating system

fece5bd

### Custom changes

none

**Comment by gygyti** [comment]
I think this has to do with all the mobs that use the firearm

**Comment by CraftedRO** [comment]
first of all .cast 118 this is polymorph not hex , but if I .cast [51514](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=51514) the mob does follow me but not attacking

**Comment by gygyti** [comment]
the same problem?
https://github.com/TrinityCore/TrinityCore/issues/21334

**Comment by gygyti** [comment]
ok i need to really update the core

**Comment by CraftedRO** [comment]
https://user-images.githubusercontent.com/24683355/134784900-a370b8dd-b750-49aa-aede-ee310744daaa.mp4

**Comment by gygyti** [comment]
understood, the matter is in the update, thanks
