### ISSUE TITLE
Creature: Pridewing Wyverns do not have any attacking or dying animations

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26962]
### Description

Pridewing Wyverns  in Stonetalon Mountains do not have any attacking or death animations and die standing up/frozen.

Edit: Includes Pridewing Patriarch and Sorrow Wing (Both Rares)

<details>

![image](https://user-images.githubusercontent.com/66294837/135189083-88c68d8c-cd48-4432-a52d-3739d671e94e.png)

</details>

### Expected behaviour

Assuming they have  associated attack and death animations.

### Steps to reproduce the problem

1. Head to roughly 50, 43 in Stonetalon Mountains
2.  There will be numerous Pridewing Wyverns 
3. Attack one and notice there are no attacking animations (or let it attack first if you are too high in level)
4. Kill it and there is no death animation - just dies in place standing up

Disclaimer: I am using WOD models but have not seen this issue in a long time - Skeletal Fiends in Duskwood are the only other mob missing a death animation

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 3630040 2021-09-23 22:10:41 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots
WOD models

**Comment by offl** [comment]
>Disclaimer: I am using WOD models but have not seen this issue in a long time - Skeletal Fiends in Duskwood are the only other mob missing a death animation

Can't reproduce without WOD models
Animations are linked to models, probably there was a brief period where those anims were removed from that particular model

**Comment by Aokromes** [comment]
or simply bad export models
