### ISSUE TITLE
[WARRIOR] Rage generation

### ISSUE THREAD

**Issue by Studioworks** [TrinityCore/TrinityCore#2696]
http://www.wowwiki.com/Rage
<pre>Rage can be generated with several different methods. The primary cause of rage generation is by being attacked, which varies based on damage taken. Attacks that are blocked, parried, or absorbed (as with Power Word: Shield) also generate rage</pre>

So, if a warrior absorbs a hit, he should get rage generated as if he was hit without absorb. Unfortunately, this doesn't work.

**Comment by Killyana** [comment]
Use wowhead.com/item=50356 and let a npc hit you, you will absorb damage and generate rage.

**Comment by Rushor** [comment]
hm and what is about block/parry/doge ?

http://www.wowwiki.com/1.3.0
Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.
