### ISSUE TITLE
DB/Object: Stonetalon signs require position fix

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#26961]
### Description

The sign post in Stonetalon mountains 59, 70 (Webwinder Path) requires position adjusting.

<details>

![image](https://user-images.githubusercontent.com/66294837/135187431-9ea5442e-0fa5-4fd1-a19c-65d6ffe9d674.png)

</details>

### Expected behaviour

Signs should be aligned on post

### Steps to reproduce the problem

1. Go to Stonetalon mountains 59, 70 (Webwinder Path)
2. Sign post will show signs are not attached

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 3630040 2021-09-23 22:10:41 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trickerer's Bots

**Comment by offl** [comment]
As I said, this require massfix
But if someone wants, try
```txt
19569   633.42     359.589     52.0103     -3.08923   0.139589   0.115725   0.982528  -0.041978
19570  633.265     359.896     51.3748     -3.08923   0.145749   0.068523   0.986307  -0.035498
19571  633.123     359.458     50.9136     -3.08923   0.142918   0.137158   0.979124  -0.045578
```
And remove gameobject_addon rows if exists

**Comment by CraftedRO** [comment]
```sql
DELETE FROM `gameobject_addon` WHERE `guid` IN (47468,47480,47481);
DELETE FROM `gameobject` WHERE `id` IN (19569,19570,19571);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(47468, 19569, 1, 0, 0, 1, 1, 633.42, 359.589, 52.0103, -3.08923, 0.139589, 0.115725, 0.982528, -0.041978, 900, 100, 1, '', 0),
(47480, 19570, 1, 0, 0, 1, 1, 633.265, 359.896, 51.3748, -3.08923, 0.145749, 0.068523, 0.986307, -0.035498, 900, 100, 1, '', 0),
(47481, 19571, 1, 0, 0, 1, 1, 633.123, 359.458, 50.9136, -3.08923, 0.142918, 0.137158, 0.979124, -0.045578, 900, 100, 1, '', 0);
```
yeap it works:

![WoWScrnShot_100421_210437](https://user-images.githubusercontent.com/24683355/135901817-13edab0b-7e1e-4448-8b89-517c7ebe4e42.jpg)

**Comment by TQPS** [comment]
Thanks team.
