### ISSUE TITLE
DB/Quest: Aggression

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#26973]
### Description

- Update quest Aggression

### SQL fix

```sql
-- Aggression
UPDATE `quest_offer_reward` SET `VerifiedBuild`=40120 WHERE `ID`=8334;

UPDATE `quest_poi` SET `VerifiedBuild`=40120 WHERE (`QuestID`=8334 AND `BlobIndex`=0 AND `Idx1` IN (0,1,2,3));

UPDATE `quest_poi_points` SET `VerifiedBuild`=40120 WHERE (`QuestID`=8334 AND `Idx1`=3 AND `Idx2`=0);
UPDATE `quest_poi_points` SET `VerifiedBuild`=40120 WHERE (`QuestID`=8334 AND `Idx1`=2 AND `Idx2` IN (0,1,2,3,4,5,6,7,8,9,10,11));
UPDATE `quest_poi_points` SET `VerifiedBuild`=40120 WHERE (`QuestID`=8334 AND `Idx1`=1 AND `Idx2` IN (0,1,2,3,4,5,6,7,8,9));
UPDATE `quest_poi_points` SET `VerifiedBuild`=40120 WHERE (`QuestID`=8334 AND `Idx1`=0 AND `Idx2`=0);

UPDATE `quest_details` SET `Emote1`=5, `Emote3`=1, `VerifiedBuild`=40120 WHERE `ID`=8334;

UPDATE `quest_template` SET `RewardMoney`=200, `RewardBonusMoney`=270, `FlagsEx`=0, `VerifiedBuild`=40120 WHERE `ID`=8334;
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0c6d05c 2021-09-29 23:36:00 +0200

**Comment by xXBentRealityXx** [comment]
Wouldn't it be better to make one post for all of this since its all in the same zone?

**Comment by MaxtorCoder** [comment]
> Wouldn't it be better to make one post for all of this since its all in the same zone?

This is better for readability I guess, so it's fine :D

**Comment by MaxtorCoder** [comment]
> Alrighty, figured it'd be worth asking especially with my upcoming post(s)

For zones you'd split them per chapter iirc.

**Comment by Aokromes** [comment]
> Wouldn't it be better to make one post for all of this since its all in the same zone?

rules are 1 ticket / bug.
