### ISSUE TITLE
Quest: Private Thorsen doesn't give Jungle Secrets quest

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#26998]
### Description

Private Thorsen doesn't patrolling and doing his job .
And he only show the yellow quest mark .

https://user-images.githubusercontent.com/24683355/135720956-3e53f3b0-d621-4948-88b7-b16fc2af1c1b.mp4

However after I reapplied [this commit sql](https://github.com/TrinityCore/TrinityCore/commit/4332314ba0b9016d9f1ee8e3bb9939e689570b5a) and seems a lot fine , the only remaining problem is that if you talk with him when he's doing his patrolling it suddenly stop / stuck in place for a while.

### Expected behaviour

According to some wowhead comments it shoud be engaged in combat with some mobs and after you kill them it shoud give you the quest but in TC it stay in camp so you can't take that quest never.

> [Every so often, Thorsen will go on patrol. If you follow him, he will be ambushed by two of Kurzen's lackeys (at around (40, 8) ) - if he survives, you will be able to start this quest off him then.](https://classic.wowhead.com/quest=215/jungle-secrets#comments:id=2597)

https://github.com/TrinityCore/TrinityCore/issues/17286

### Steps to reproduce the problem

Create a level 30 character and go in Rebel Camp
Notice Private Thorsen only have a yellow exclamation quest mark but it doesn't start patrolling and you are not able to start quest : Jungle Secrets

### Branch

3.3.5

### TC rev. hash/commit

102e8fb0ee91

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by dr-j** [comment]
This works but is triggered by ooc timer which is for ten minutes which basically means the grid where private thorsen is must be loaded for ten mins before he will even start his wp to the ambush

**Comment by CraftedRO** [comment]
not sure how it works when actually it stay in place near campfire all the time

**Comment by CraftedRO** [comment]
what do you think @offl can you recommit same sql , and we let this open for the stuck issue ?

**Comment by offl** [comment]
Something was broken in https://github.com/TrinityCore/TrinityCore/commit/4f0aad714284086d6db31cfe54f11454f54d5148

https://github.com/TrinityCore/TrinityCore/commit/4332314ba0b9016d9f1ee8e3bb9939e689570b5a#diff-a3aa7735358f7d544f7d86b7b8b3e1161821faea6c5893b7778ea1c68edba068R14 faction 123 should be restored
He changes at some point faction to 42

https://github.com/TrinityCore/TrinityCore/commit/4332314ba0b9016d9f1ee8e3bb9939e689570b5a#diff-a3aa7735358f7d544f7d86b7b8b3e1161821faea6c5893b7778ea1c68edba068R93 correct is 43

When he's on patrol or whatever he does, he has gossip flag, https://youtu.be/GF1SkliEVGo?t=55, this fixes his movement stop
```sql
DELETE FROM `creature_template_movement` WHERE `CreatureId` = 738;
INSERT INTO `creature_template_movement` (`CreatureId`,`Ground`,`Swim`,`Flight`,`Rooted`,`Chase`,`Random`,`InteractionPauseTimer`) VALUES
(738,1,1,0,0,0,0,0);
```

Tons of hacks to support crappy script which can't even work
