### ISSUE TITLE
DB/Vendors: Updated PvP, Justice, Valor Vendors in Orgrimmar and Stormwind

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#27017]
### Description

Also closes #25952

### SQL fix

```sql
https://gist.github.com/mdX7/6dd8b4f252675dd9bc44e12a9ae1d5d4
```

### Branch

master

### TC rev. hash/commit

555b2d40ecc22eb0ea4bf913b534ffa7197fa6fe

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fb728b2926b30683a62f1a8cadc6e1d8a41e5da2
