### ISSUE TITLE
clang 14 unhappy.

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#27018]
**Description:**

compiling tc with clang 14 gives few warnings.
https://gist.github.com/Aokromes/7e3077dcd87c8a265f8b50ce1b8b65cb

**Expected behaviour:**

no warnings

**Steps to reproduce the problem:**

1. compile tc with clang 14.
2. 
**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

102e8fb0ee91

**Operating system:** 

Debian 11

**Comment by Warpten** [comment]
There's only one, it's not our code, and it's fine

**Comment by Aokromes** [comment]
> There's only one, it's not our code, and it's fine

https://github.com/TrinityCore/TrinityCore/commit/f2fa1533d9c2c72bb1c457d22109f356811acb57
https://github.com/TrinityCore/TrinityCore/commit/c86cf03dcefad845ca52b1bb1c9b1baa89105462
https://github.com/TrinityCore/TrinityCore/commit/119c372dfff335657c670de50bf156842aba445c
https://github.com/TrinityCore/TrinityCore/commit/bf5c37a5d056485fc256aa7f128f81eeb125a992

**Comment by Shauren** [comment]
It will be fixed by the time we get clang 14 on CI (not any time soon)

**Comment by Aokromes** [comment]
we fixed others far before CI release :)

**Comment by tails2k** [comment]
Also this came form? Fresh Checkout!

Scanning dependencies of target common
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Banner.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Common.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/GitRevision.cpp.o
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
1 warning generated.
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Collision/BoundingIntervalHierarchy.cpp.o
1 warning generated.
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]

**Comment by KingPin** [comment]
> It will be fixed by the time we get clang 14 on CI (not any time soon)

they have no plans for 14 anytime in the near future..... been trolling their suggestion forums....

**Comment by Shauren** [comment]
a650bd631a4681d09e3ff66f79b73b99299565f3
