### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by tails2k** [TrinityCore/TrinityCore#27023]
### Description

Scanning dependencies of target common
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Banner.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Common.cpp.o
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/GitRevision.cpp.o
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
1 warning generated.
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Collision/BoundingIntervalHierarchy.cpp.o
1 warning generated.
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]

### Expected behaviour

Compile without errors :)

### Steps to reproduce the problem

Checkout and Build

### Branch

master

### TC rev. hash/commit

Fresh Checkout
a566b84

### Operating system

Debian 10

### Custom changes

None

**Comment by Aokromes** [comment]
warning aint error, also problen is you wrote bad setting.

**Comment by tails2k** [comment]
> warning aint error, also problen is you wrote bad setting.

okay thanks
