### ISSUE TITLE
DB/Creature: Add scripts to Stormwind Guards

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27035]
### Description

they were missing spells
view-source:https://web.archive.org/web/20101216010648/http://www.wowhead.com/npc=1423
for some reason spell : Shoot 95826 doesn't exist so I replaced with 6660 as I see on stormwind city guards SAI ,also im not sure if there's need Cast Flag 64 - SMARTCAST_COMBAT_MOVE on this spell (if not needed probably we need to remove flag from other npc too).

### SQL fix

```sql
-- Stormwind Guard
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 1423;
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 1423);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(1423, 0, 0, 0, 0, 0, 100, 0, 0, 0, 2000, 4000, 0, 11, 6660, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Stormwind City Guard - In Combat - Cast 'Shoot'"),
(1423, 0, 1, 0, 9, 0, 100, 0, 0, 5, 11000, 14000, 0, 11, 12169, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Stormwind City Guard - Within 0-5 Range - Cast 'Shield Block'"),
(1423, 0, 2, 0, 0, 0, 100, 0, 5000, 9000, 8000, 13000, 0, 11, 12170, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, "Stormwind City Guard - In Combat - Cast 'Revenge'");
```

### Branch

3.3.5

### TC rev. hash/commit

10a3bf4312c1

**Comment by Aokromes** [comment]
guards are suposed to use GuardAI

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CoreAI/GuardAI.cpp
ah I see then Im out

**Comment by offl** [comment]
Don't wanna dig too much but in 2016 TDB GuardAI was used by 0 creatures, no idea how much creatures used it before #21555 or #21470 but now it's again used by 0 creatures
GuardAI is 'interesting'. It uses CanSeeAlways which is used in CanAlwaysSee(??????????????) which is used in CanSeeOrDetect
It's also the only place where SendZoneUnderAttackMessage is used

We also have npc_guard_generic

Using SAI is not really good, using GuardAI is too not really good, but looks like people decided just to add SAI to all guards

**Comment by offl** [comment]
Or maybe GuardAI was never supposed to be assigned to creatures directly
