### ISSUE TITLE
DB/Gossip/Cosmetic: Dwarven Farmer missing gossip in Wetlands Farm

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27106]
### Description

According to this video and few more links , this npc shoud have gossip like Ironforge Mountaineer.
https://youtu.be/F4_YURx8VLs?t=310
https://wowpedia.fandom.com/wiki/Dwarven_Farmer

> For some reason, the farmers give out the same kind of information as Ironforge Mountaineers do, as if they were located in Dun Morogh.

### SQL fix

```sql
UPDATE `creature_template` SET `gossip_menu_id`= 3533 , `npcflag` = 1 WHERE `entry`= 12998;
```

### Branch

3.3.5

### TC rev. hash/commit

8693ee56955c

**Comment by offl** [comment]
It's valid for classic and maybe for tbc but not for wotlk - no npcflag in sniffs + found one video without flag
