### ISSUE TITLE
DB/Gameobject: Missing signposts in Wetlands Farm

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27104]
### Description

According to this video and whatever other sources there shoud be some signposts :
https://www.youtube.com/watch?v=F4_YURx8VLs

Sources:
[Cmangos](https://github.com/cmangos/classic-db/commit/846bb2b754d6d91ccb968a6e156a4c9a00ccd9e0)
And improved coords found here :
https://wow.tools/dbc/?dbc=gameobjects&build=2.5.2.40617#page=1&search=123215
https://wow.tools/dbc/?dbc=gameobjects&build=2.5.2.40617#page=1&search=123216
https://wow.tools/dbc/?dbc=gameobjects&build=2.5.2.40617#page=1&search=123217

I tried to port them but for some reson they doesn't appear ingame visually (I can see them on .gob near) :

```sql
-- Added missing signposts in Wetlands Farm
DELETE FROM gameobject WHERE guid IN (81802, 81803, 81804);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(81802, 123215, 0, 0, 0, 1, 1, -4020.3281, -1407.0065, 155.45361, 1.57952, 0, 0, 0.710185, 0.704015, 180, 255, 1, '', 0),
(81803, 123216, 0, 0, 0, 1, 1, -4020.0464, -1407.1609, 155.46286, 3.14159, 0, 0, 1, 0.00000126759, 180, 255, 1, '', 0),
(81804, 123217, 0, 0, 0, 1, 1, -4020.0503, -1407.0083, 155.43744, 0.008724, 0, 0, 0.004363, 0.99999, 180, 255, 1, '', 0);
```

### Expected behaviour

There shoud be signposts like in the above video.

### Steps to reproduce the problem

wetlands
.go xyz -4023 -1402 155

### Branch

3.3.5

### TC rev. hash/commit

8693ee56955c

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
OMFG dafuq I tried tousand of times and I don't understand two things , the query shoudn't delete used ones anyway and replace with those , 2. if there are already used why core doesn't trow me any error :)))))) ?

**Comment by offl** [comment]
>the query shoudn't delete used ones anyway and replace with those

It should, otherwise how you can delete something from DB

>if there are already used why core doesn't trow me any error :)))))) ?

It should not, maybe another errors can be thrown because old data and new data does not match data in other tables where those objects or creatures are used
That's why before adding something, we check if guids are not used
