### ISSUE TITLE
Halion - Combat Reach - different from sides

### ISSUE THREAD

**Issue by Conscript01** [TrinityCore/TrinityCore#27135]
### Description

Halion has different hitbox from sides... this affects AOE spells like divine storm, bladestorm, fan of knives only.
from the side of Baltharus the Warborn - up to 26yd
from the side of Saviana Ragefire - up to 8yd

https://youtu.be/pVYt4lEFb5o  

### Expected behaviour

Halion should have the same hitbox around him, no matter which side you are standing

### Steps to reproduce the problem

step 1.  get to the ruby sanctum and kill minibosses
step 2. .learn 53385
step 3. .cheat cooldown
step 4. .mod mana 9999999
step 5. observe different ranges from the sides

### Branch

3.3.5

### TC rev. hash/commit

ae9e583

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by Jildor** [comment]
related to: #22375
