### ISSUE TITLE
Class/Priest Spirit of Redemption (20711)

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#27143]
### Description

The Holy Priest just dies and dont get his Spirit of Redemption form.

### Expected behaviour

On Death the Holy Priest should get into his Spirit of Redemption Form, allowing him to continue healing for a little amount of time.

https://www.wowhead.com/spell=20711/spirit-of-redemption

### Steps to reproduce the problem

1. Create a Priest
2. Choose Holy spec.
3. set your character to lvl 60
4. Die.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 3503e9dc9296

### Operating system

Windows 10

### Custom changes

None

**Comment by offl** [comment]
Looks like it get broken #26253

**Comment by aquadeus** [comment]
this is fixed again 😄
