### ISSUE TITLE
DB/Quest/POI/Cosmetic: Fragments of the Past wrong POI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27158]
### Description

.quest add 5246
check map
it shoud be in the middle
https://tbc.wowhead.com/quest=5246/fragments-of-the-past

https://youtu.be/73Zfgx43vb0
Credit fix [AzerothCore](https://github.com/azerothcore/azerothcore-wotlk/pull/8489/files)

### SQL fix

```sql
UPDATE `quest_poi_points` SET `X`=3565, `Y`=-5381 WHERE `QuestID`=5246 AND `Idx1`=2 AND `Idx2`=0;
```

### Branch

3.3.5

### TC rev. hash/commit

d61405f7487e

**Comment by offl** [comment]
https://www.wowhead.com/quest=5246/fragments-of-the-past#comments:id=934329

**Comment by CraftedRO** [comment]
ah lol this one is a blizzlike bug then :)
