### ISSUE TITLE
DB/Quest/POI/Cosmetic: Augustus' Receipt Book" does show on Western Plaguelands while the whole quest is in Eastern

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27157]
### Description

Doing "Show Map" on the quest "Augustus' Receipt Book" (id 6164) opens Western Plaguelands map while both the objective and completion are in Eastern.

![WoWScrnShot_102421_150400](https://user-images.githubusercontent.com/24683355/138593228-9fec5f11-9145-4207-be22-1b36276606c6.jpg)

### Expected behaviour

When you open the quest map shoud be in eastern like in this video:
https://youtu.be/jXcTdwgMnZI

### Steps to reproduce the problem

.quest add 6164
look at quest map

### Branch

3.3.5

### TC rev. hash/commit

d61405f7487e

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by offl** [comment]
It's not POI or stuff like that but addons you use
I see no `?` in wrong place in game

**Comment by CraftedRO** [comment]
Well I wasn't probably precise here , the quest ? is fine , but if we can , we need to change the map shown firsly when you press show map for this quest so it will be EP not WP , If this can't be done through the database then I guess we can leave like this.

**Comment by offl** [comment]
I don't know what is responsible for that

**Comment by offl** [comment]
Annnddd I can't reproduce it so it's definitely addons

**Comment by CraftedRO** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/8713
for them too then

**Comment by CraftedRO** [comment]
https://user-images.githubusercontent.com/24683355/139554081-36c5b8b3-6b2a-4f86-a4e2-cb765e5ed9c4.mp4

**Comment by CraftedRO** [comment]
I had found the solution
```sql
UPDATE `quest_poi` SET `WorldMapAreaId` = 23 WHERE `QuestID` = 3655;
```

**Comment by CraftedRO** [comment]
I had found the solution

```sql
UPDATE `quest_poi` SET `WorldMapAreaId` = 23 WHERE `QuestID` = 6164;
```

**Comment by offl** [comment]
For me the map is shown in full-size, I don't know how to shrink it
There's no such quest_poi

**Comment by CraftedRO** [comment]
yea I was firstly pointed the wrong quest id in query ...

**Comment by CraftedRO** [comment]
you shrink it by upper-right corner arrow

**Comment by offl** [comment]
Same result

**Comment by CraftedRO** [comment]
wich ?

**Comment by offl** [comment]
The map is shown correctly

**Comment by CraftedRO** [comment]
eastern ?

**Comment by offl** [comment]
Yes

**Comment by CraftedRO** [comment]
ok I quit this ...

**Comment by CraftedRO** [comment]
if you .quest add 890 what map does open on your wow for example ?

**Comment by offl** [comment]
Barrens

**Comment by CraftedRO** [comment]
you must joke with me :D , for me and others that quest opens durotar that is wrong too:
https://github.com/azerothcore/azerothcore-wotlk/issues/8531

**Comment by Aokromes** [comment]
i vote it's client bug / limitation.

**Comment by CraftedRO** [comment]
if so then why after I changed WorldMapAreaId it does show well now ?

**Comment by CraftedRO** [comment]
https://wowpedia.fandom.com/wiki/WorldMapAreaID

**Comment by CraftedRO** [comment]
23 is eastern my good fellas , not 22

**Comment by offl** [comment]
What was the query?

**Comment by CraftedRO** [comment]
is posted above

**Comment by offl** [comment]
Cata DB
```txt
QuestID      id  ObjectiveIndex   MapID  WorldMapAreaId   Floor  Priority   Flags  VerifiedBuild  
-------  ------  --------------  ------  --------------  ------  --------  ------  ---------------
   6164       0               4       0              22       0         0       1            19831
   6164       1              -1       0              22       0         0       1            19831
```
Master DB
```txt
QuestID  BlobIndex    Idx1  ObjectiveIndex  QuestObjectiveID  QuestObjectID   MapID  UiMapID  Priority   Flags  WorldEffectID  PlayerConditionID  NavigationPlayerConditionID  SpawnTrackingID  AlwaysAllowMergingBlobs  VerifiedBuild  
-------  ---------  ------  --------------  ----------------  -------------  ------  -------  --------  ------  -------------  -----------------  ---------------------------  ---------------  -----------------------  ---------------
   6164          0       0              -1                 0              0       0       22         0       1              0                  0                            0                0                        0            39653
   6164          0       1               0            258823          15884       0       22         0       1              0                  0                            0                0                        0            39653
```
TDB 2011
```txt
questId      id  objIndex   mapid  WorldMapAreaId  FloorId    unk3    unk4  
-------  ------  --------  ------  --------------  -------  ------  --------
   6164       0         4       0              22        0       0         1
   6164       1        -1       0              22        0       0         1
```
TDB 2021
```txt
QuestID      id  ObjectiveIndex   MapID  WorldMapAreaId   Floor  Priority   Flags  VerifiedBuild  
-------  ------  --------------  ------  --------------  ------  --------  ------  ---------------
   6164       0               4       0              22       0         0       1                0
   6164       1              -1       0              22       0         0       1                0
```

**Comment by offl** [comment]
Quest POI stuff looks like it was bruteforced back in WotLK
Ideally should be never changed manually

**Comment by CraftedRO** [comment]
Well if you want to leave like this is perfectly fine dunno I guess I can't prove it more , or "fight" on this topic.

**Comment by CraftedRO** [comment]
https://wowpedia.fandom.com/wiki/Augustus%27_Receipt_Book_(quest)
![Captură de ecran 2021-10-30 233714](https://user-images.githubusercontent.com/24683355/139557706-bf8b2875-418b-4337-920d-bce100a228f4.png)

**Comment by Aokromes** [comment]
https://i.imgur.com/KxOn6fX.jpeg

https://i.imgur.com/YLT9ppQ.jpeg 

both screenshots wow 3.3.5a, like i said, i vote client bug / limitation, after river all it's WP.

**Comment by offl** [comment]
>Well if you want to leave like this is perfectly fine dunno I guess I can't prove it more , or "fight" on this topic.

What I'm trying to say, changing that field is not a solution
Why it works for me is a different question

**Comment by CraftedRO** [comment]
@Aokromes if I click on western it does still show the quest marker for me too , but the main point here were about what map appear first time you click show map in quest log.

I don't see another solution rather than changing the poi field since the quest count for eastern even in retail tbc db:
![tbc](https://user-images.githubusercontent.com/24683355/139558017-52e634a7-0b6b-4f47-b57e-68b49701504f.png)

**Comment by CraftedRO** [comment]
on live there's a similar quest version with this one with this id
https://www.wowhead.com/quest=27534/augustus-receipt-book
but most likely that one is same in eastern too

**Comment by offl** [comment]
Cata
```txt
QuestID      id  ObjectiveIndex   MapID  WorldMapAreaId   Floor  Priority   Flags  VerifiedBuild  
-------  ------  --------------  ------  --------------  ------  --------  ------  ---------------
  27534       0               4       0              23       0         0       1            19831
  27534       1              -1       0              23       0         0       1            19831
```

Probably they realized that WorldMapAreaId is wrong and changed it

**Comment by CraftedRO** [comment]
![descărcare](https://user-images.githubusercontent.com/24683355/139558390-9bb190ab-9d52-4b61-9069-11b21ae89278.jpg)

**Comment by CraftedRO** [comment]
does they realized and changed same for those quest id-s too : 890 , 892 , 896 , 887 , 888 ?
if so

**Comment by CraftedRO** [comment]
does they realized and changed same for those quest id-s too : 890 , 892 , 896 , 887 , 888 ?
if so , then we shoud leave like this

**Comment by CraftedRO** [comment]
sniffer doesn't catch nothing about those ?
