### ISSUE TITLE
Core/SAI: SMART_ACTION_ACTIVATE_GAMEOBJECT

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#27196]
### Description

GameObjectActions implemented in https://github.com/TrinityCore/TrinityCore/pull/24997 originally are supposed to be used in several systems, as stated in https://github.com/TrinityCore/TrinityCore/pull/24997#issuecomment-657087699

More info here https://github.com/TrinityCore/TrinityCore/issues/27009#issuecomment-932972363

### Expected behaviour

Allow to use GameObjectActions in SAI by SMART_ACTION_ACTIVATE_GAMEOBJECT with param1 = GameObjectActions
And in C++ scripts by calling ActivateGameObject

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

222164a5cc11b4c012074921d4ae1ae74276a990

### Operating system

Win 8.1

### Custom changes

none

**Comment by jackpoz** [comment]
I created a PR at https://github.com/TrinityCore/TrinityCore/pull/27216
