### ISSUE TITLE
[TOC/TOGC][Item] Reign of the Dead/Reign of the Unliving <wip>

### ISSUE THREAD

**Issue by drey113** [TrinityCore/TrinityCore#2719]
If i remember correct, after new rev where was spell core rewritten/changed/renamed, this trinkets stopped working. 
http://www.wowhead.com/item=47316
http://www.wowhead.com/item=47182
How itshould work: You gain a Mote of Flame each time you cause a non-periodic spell critical strike. When you reach 3 Motes, they will release, firing a Pillar of Flame for 1741 - 2023 damage. Mote of Flame cannot be gained more often than once every 2 sec.
How it works: You cause non-periodic spell critical strike and u don't get Mote of Flame

Same goes for heroic versions.
http://www.wowhead.com/item=47477
http://www.wowhead.com/item=47188
How it should work: You gain a Shard of Flame each time you cause a non-periodic spell critical strike. When you reach 3 Shards, they will release, firing a Pillar of Flame for 1959 - 2275 damage. Shard of Flame cannot be gained more often than once every 2 sec.
How it works: You cause non-periodic spell critical strike and u don't get Shard of Flame

TrinityCore rev. 2011-08-16 19:13:53 +0200 (df1b1a37600a+) (Unix, Release)
 TDB_full 335.11.41

**Comment by ariel-** [comment]
Issue no longer present on HEAD.
