### ISSUE TITLE
Gameobject: "Spirit Candle" doesn't give buff

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27210]
### Description

Spirit Candle doesn't give buff similar to Basic Campfire.
Description of spell
Places a spirit candle that increases the spirits of those nearby by 4.

### Expected behaviour

https://www.wowhead.com/item=46711/spirit-candle#comments:id=881694

> By Ronny on 2009/11/03 (Patch 3.2.2)
> Spirit Candle is sold at any major city graveyard during the Day of the Dead. You can place one on the ground for decoration, it lasts for 5 minutes, its cooldown is also 5 minutes, so you can't place two at once. It buffs you similarly to Basic Campfire, but you can use it only during the Day of the Dead

### Steps to reproduce the problem

.event start 51
.additem 46711
use it and nothing happens

### Branch

3.3.5

### TC rev. hash/commit

1403de8dafba

### Operating system

Windows 11 x64

### Custom changes

 None

**Comment by acidmanifesto** [comment]
even though the campfire has been marked in a much old older issue https://github.com/TrinityCore/TrinityCore/issues/9437
There seems to be a pattern of this feature or gameobject condition (maybe?) or aura processing of breaking then working and then breaking.
Was there ever a commit that referenced it being fix in the previous issue? Has the underlying issue ever been determined that caused it previously that could be related to the issue now currently?

**Comment by CraftedRO** [comment]
Today I may found the problem here , if you .gob add temp 195090 it works , so most likely Spirit Candle 46711 doesn't summon the correct id gameobject.

**Comment by CraftedRO** [comment]
Found the correct id with .gob near here :

![WoWScrnShot_110121_122859](https://user-images.githubusercontent.com/24683355/139658169-8d225f0b-6de4-4911-b5c1-03cb5e4cad09.jpg)

**Comment by offl** [comment]
.npc add temp 6
.event start 51
.additem 46711
use item, works

So yeah, it's something that was described in #9437 but I don't understand how this can be correct behavior, for example I wanted to improve turkey like here https://youtu.be/PJM12zlNJhc?t=6 or https://youtu.be/yFWlAi_XOuU?t=95
But for some reason Cozy Fire aura is applied not on me and my turkey but on kobold and me
