### ISSUE TITLE
(fix/GObject) Make chairs unclickable

### ISSUE THREAD

**Issue by Banehammer** [TrinityCore/TrinityCore#27217]
### Description

These Chairs in Valiance Keep are now unclickable because they are already being seat on.

Recruitment Officer Blythe (ID: 116919) .go c 116919

### SQL fix

```sql
UPDATE `gameobject_template_addon` SET `flags`='16' WHERE  `entry`=187558;
UPDATE `gameobject_template_addon` SET `flags`='16' WHERE  `entry`=186841;
UPDATE `gameobject_template_addon` SET `flags`='16' WHERE  `entry`=186839;
```

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/cd6ba01e3db100a677bc37651b506a6701a6b901

**Comment by CraftedRO** [comment]
I have a question totally unrelated to this PR , are you deleting so often your github account ?

**Comment by Wolffenstein** [comment]
This is wrong. Those chairs ARE supposed to be clickable but core shouldn't let you sit on them (nothing should happen once you click).

**Comment by offl** [comment]
No flags in sniffs
