### ISSUE TITLE
NPC for quest Search and Rescue (12037) not appearing

### ISSUE THREAD

**Issue by alexmocanu** [TrinityCore/TrinityCore#27223]
### Description

The npc required to continue this quest doesn't appear. 

Quest: https://www.wowhead.com/quest=12037/search-and-rescue
Npc: https://www.wowhead.com/npc=55677/kurzel 

When you destroy the Darkweb Victim cocoons, all of them contain Drakkari Guardians. Kurzel doesn't appear after destroying all cocoons. 

### Expected behaviour

In Drak'Tharon Keep, you should find Kurzel in one of the Darkweb Victim cocoons and continue the quest.

### Steps to reproduce the problem

Take this quest
Quest: https://www.wowhead.com/quest=12037/search-and-rescue

And try to find this npc:
Npc: https://www.wowhead.com/npc=55677/kurzel 

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. e615b71509c0 2021-10-21 19:15:35 +0300 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 100331
Using CMake version: 3.16.3
Compiled on: Linux 4.4.0-19041-Microsoft
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 291014951 bytes
vmaps directory located in ../data/vmaps. Total size: 657797442 bytes
mmaps directory located in ../data/mmaps. Total size: 1961820076 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21101
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 20.04.3 (running on Windows 10 x64 using WSL 1)

### Custom changes

None

**Comment by CraftedRO** [comment]
can't confirm :

![WoWScrnShot_103121_200402](https://user-images.githubusercontent.com/24683355/139596180-2c3ff073-af9f-4f64-8e8f-2730629e23f4.jpg)

**Comment by CraftedRO** [comment]
Bonus video (difficulty normal)

https://user-images.githubusercontent.com/24683355/139596328-23680809-2629-4360-a937-19f6b2fad674.mp4

**Comment by alexmocanu** [comment]
After testing some more it seems to be happening at random.
I restarted the world server 4 times and only on the final time did that npc spawned. 

During the first 3 attempts only the Drakkari Guardians spawned.

**Comment by offl** [comment]
There is a chance that creature will be not spawned at all
No idea if it's correct behavior or not
I wanted to rework it few months ago because it should be scripted completely differently

**Comment by CraftedRO** [comment]
Sice you don't have to restart the server but reset the instance and just try again on the new spawned cocons , I guess is not really big of a deal .

**Comment by CraftedRO** [comment]
Tried now 5 times in a row and it spawned every time in one of them , I bet that he doesn't kill all of them specially the one in the left corner at the entrance door.

**Comment by Aokromes** [comment]
try after 6e07acb

**Comment by offl** [comment]
6e07acb doesn't fix that
Can't reproduce after like 20 attempts
