### ISSUE TITLE
Core/Spells: AURA_INTERRUPT_FLAG_USE (Looting) 0x00000800 NYI

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27222]
### Description

You can enter Stealth / Prowl and loot a mob without Stealth / Prowl being cancelled.

https://user-images.githubusercontent.com/24683355/139594355-7de82ff9-8951-4c97-81fb-c8108af2fa14.mp4

https://user-images.githubusercontent.com/24683355/139594528-15dd7cbd-b33a-452a-84b3-cba733b0438c.mp4

### Expected behaviour

When looting Stealth should be cancelled.
https://wowpedia.fandom.com/wiki/Stealth
> Attacking and most actions such as looting will cancel Stealth.

And a video as proof when a rogue cast loot on a chest his stealth fade.
https://youtu.be/ld-NtQwWvG4?t=147

### Steps to reproduce the problem

kill any mob that have loot
then .cast self 1784
and loot it without braking the stealth

### Branch

3.3.5

### TC rev. hash/commit

ee263a3e2f7b

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by offl** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9b5a46ca2bb3a4632cb9914e0899df611a47d935#diff-7c2c959f24f6697abb002cc137dc56695fb2b6df5e5f8145bd9ebad0f942b708R299
