### ISSUE TITLE
Core/Quests: Few Argent Dawn quests giving incorrect amount of reputation

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27231]
### Description

[Above and Beyond](https://www.wowhead.com/quest=5263/above-and-beyond) (atm it gives 550 rep at neutral)

> By 172375 on 2010/09/13 (Patch 3.3.5)
> 1000 rep for this quest, 500 and then 1000 for the short follow ups.
> 
> By 7784 on 2008/10/17 (Patch 3.0.2)
> This quest actually gives 1,000 Argent Dawn rep, contrary to the 350 posted above.

[Dead Man's Plea](https://www.wowhead.com/quest=8945/dead-mans-plea) (atm it gives 550rep at neutral)

By mattous on 2008/02/23 (Patch 2.3.3)
Completing this quest also gives you 1000 reputation with the Argent Dawn

[Target: Felstone Field](https://www.wowhead.com/quest=5229/target-felstone-field) (atm it gives 275 rep at neutral)

> By 119934 on 2008/04/26 (Patch 2.4.1)
> now it is 500 reputation with argent dawn

### Expected behaviour

Above and Beyond shoud give 1000 rep
Dead Man's Plea shoud give 1000 rep
Target: Felstone Field shoud give 500 rep

### Steps to reproduce the problem

.quest add 5263
.quest complete 5263

### Branch

3.3.5

### TC rev. hash/commit

15fa7c59e6a6

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by offl** [comment]
DB data is fine, didn't checked if those indeed should give more reputation or not
If they should, then something is wrong in core, completely unfamiliar with such system

**Comment by Aokromes** [comment]
> DB data is fine, didn't checked if those indeed should give more reputation or not If they should, then something is wrong in core, completely unfamiliar with such system

iirc reputation rate somewhere.

**Comment by Aokromes** [comment]
example https://github.com/TrinityCore/TrinityCore/commit/83e5168a5bed68ce00118fbeefe7979754838b48
