### ISSUE TITLE
DB/Item: Red Sack of Gems contains incorrect item

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#27234]
### Description

Red Sack of Gems has a 100% chance to drop a Level 22 [Black Pearl Ring](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=17969#contains).

### Expected behaviour

This item does not appear in current [Classic](https://tbc.wowhead.com/item=17969/red-sack-of-gems#contains) builds or [Live](https://www.wowhead.com/item=17969/red-sack-of-gems#contains).

The sack is supposed to have a chance to drop a Black Pearl (which it does), just not a ring of a similar name.

### Steps to reproduce the problem

1. Kill a world dragon (and hope it drops a red sack) or give yourself item 17969
2. Sack will contain a number of random gems and a Level 22 Blue item (Black Pearl Ring)

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 6e07acbbdeb5 2021-11-01 18:11:39 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trinity Bots

**Comment by cin3m** [comment]
Hello,

I compared the loot table from wowhead and the database. According to wowhead the loot table contains 7 items. In the database there are 8 items assigned.
Please find the SQL-Query which removes item 6332 (Black Pearl Ring)


### SQL fix

```sql
--
DELETE FROM `item_loot_template` WHERE `entry` = 17969 AND `item` = 6332;
```
