### ISSUE TITLE
DB/Creature/Cosmetic: Southsea Swashbuckler equipment

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27242]
### Description

Tested ingame , works as expected.

Sniffed by Malcrom
Credit [AzerothCore](https://github.com/azerothcore/azerothcore-wotlk/pull/8913/files#diff-c2efeac65211057ef820fce7e35af0d8d45220f2f842356deef7e217917e0e14)

### SQL fix

```sql
-- Fix equipment for Southsea Swashbuckler
UPDATE `creature_equip_template` SET `ItemID1`=1897, `ItemID2`=0 WHERE `CreatureID`=7858;
```

### Branch

3.3.5

### TC rev. hash/commit

6e07acbbdeb5

**Comment by jackpoz** [comment]
As mentioned already at https://github.com/TrinityCore/TrinityCore/issues/27229#issuecomment-956174832 :
>AzerothCore license AGPL is incompatible with TrinityCore GPL so we cannot accept any code copied from them (unless the original author decides to submit it, then "maybe" that's ok).

You can read more about the topic at https://www.gnu.org/licenses/license-list.en.html

>Please note that the GNU AGPL is not compatible with GPLv2. It is also technically not compatible with GPLv3 in a strict sense: you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, or vice versa. However, you are allowed to combine separate modules or source files released under both of those licenses in a single project, which will provide many programmers with all the permission they need to make the programs they want. See section 13 of both licenses for details.

Including AC code will mean some files in TC will be released under AGPL license, forcing every TC user to make their source code available. That's not what we want to do right now so please avoid copying code from projects with a license other than AGPL.

If you want to discuss further we can take it to https://github.com/TrinityCore/TrinityCore/discussions which seems to be a more fitting place than an issue 😃

**Comment by CraftedRO** [comment]
It will be commited anyway , no point in closing this , is not a part of the core code .

**Comment by CraftedRO** [comment]
Btw if you are bored enough to close valid issues , take a look at https://github.com/TrinityCore/TrinityCore/issues/26916 that you broke it when updating to myql 5.7

**Comment by jackpoz** [comment]
> It will be commited anyway , no point in closing this , is not a part of the core code .

SQL is still code and licenses apply to that too.

**Comment by jackpoz** [comment]
> Btw if you are bored enough to close valid issues

Well now you are just lashing out at me 😢

**Comment by jackpoz** [comment]
No, the "better" way would be to fix it ourselves without copying code from other projects, especially if their license is not compatible.

It's good you shared the code and I tried to write a long enough explaination instead of just closing the issue and locking it.

**Comment by Aokromes** [comment]
Offle already have this fix (and few more) without having to credit AC.

**Comment by jackpoz** [comment]
In general it would be better if the original author submitted sql fixes or c++ code instead of someone else copying his work and sending it to TC. We have had some C++ pull request from people that didn't know C++ at all so they were not able to fix the issues we spotted during the pull request review.

**Comment by acidmanifesto** [comment]
Lets keep it professions @CraftedRO this isnt high school social media drama or what ever teens do with tide pods these days.

**Comment by Faq** [comment]
The original author (code owner) could be allowing to use his fix by commenting in that issue/PR what is the same as putting signature on code.
I guess I'm not the only one who checks someone's code and comes up with idea to fix issue in another way or improve the code by putting some part from myself (in commit still can give credit to original author for the used idea).

Btw github allows convert issue to discussion.

**Comment by Teppic1** [comment]
Regarding the GPL2/3 stuff, any changes to the code (even if it entirely replaces sections), are automatically distributed under the same licence. That's basically the entire point of the GPL, it guarantees that all modifications always remain under the GPL. Since Sunwell was based on TC, it is under the GPL, and any code based off Sunwell is also under the GPL.

Nobody can change those rights or change the licence. If you don't agree to the GPL, you're not allowed to modify the code or distribute it in any way.

**Comment by Jinnaix** [comment]
> Regarding the GPL2/3 stuff, any changes to the code (even if it entirely replaces sections), are automatically distributed under the same licence. That's basically the entire point of the GPL, it guarantees that all modifications always remain under the GPL. Since Sunwell was based on TC, it is under the GPL, and any code based off Sunwell is also under the GPL.
> 
> Nobody can change those rights or change the licence. If you don't agree to the GPL, you're not allowed to modify the code or distribute it in any way.

Azerothcore did not change the whole code to a new license. But everything commited  to AC after 17. August 2016 is AGPL.
See 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
and
https://github.com/azerothcore/azerothcore-wotlk/issues/21

Further down, AGPL is incompatible with Trinitycores GPLv2

>GNU Affero General Public License (AGPL) version 3 (#AGPL) (#AGPLv3.0)
This is a free software, copyleft license. Its terms effectively consist of the terms of GPLv3, with an additional paragraph in section 13 to allow users who interact with the licensed software over a network to receive the source for that program. We recommend that developers consider using the GNU AGPL for any software which will commonly be run over a network.

>Please note that the GNU AGPL is not compatible with GPLv2. It is also technically not compatible with GPLv3 in a strict sense: you cannot take code released under the GNU AGPL and convey or modify it however you like under the terms of GPLv3, or vice versa. However, you are allowed to combine separate modules or source files released under both of those licenses in a single project, which will provide many programmers with all the permission they need to make the programs they want. See section 13 of both licenses for details.

Source: https://www.gnu.org/licenses/license-list.en.html

**Comment by ihm-tswow** [comment]
> Regarding the GPL2/3 stuff, any changes to the code (even if it entirely replaces sections), are automatically distributed under the same licence. That's basically the entire point of the GPL, it guarantees that all modifications always remain under the GPL. Since Sunwell was based on TC, it is under the GPL, and any code based off Sunwell is also under the GPL.
> 
> Nobody can change those rights or change the licence. If you don't agree to the GPL, you're not allowed to modify the code or distribute it in any way.

This is wrong. New code is not automatically distributed under the same license, it's just combined with the other code without permission. Furthermore, TrinityCore uses the "GPLv2-or-later" clause, meaning it permits patches with other (more restrictive) versions of the GPL as long as it's published by the fsf. The AGPL is published by the fsf, and it's thus possible to redistribute trinitycores source code with patches released under the AGPL. The opposite is not possible, any code you pulled back would retain its AGPL status and you could not revert it back to GPLv2. 

However, you need to read the specific headers for individual files that azerothcore publish, because not all of their code and patches are AGPL. There was a huge PR in which they changed the language in lots of their files (on my advice) from "gplv2" to "gplv2-or-later" (because they typo'd it and accidentally made their own code incompatible with their own code). You can just read this pr for files that are still licensed gplv2-or-later.

**Comment by ihm-tswow** [comment]
here's that PR https://github.com/azerothcore/azerothcore-wotlk/pull/4762

**Comment by Teppic1** [comment]
You can read the licence at

https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

It states very clearly that you can only distribute changes to the code if you supply those changes under the same licence.

From the FAQ

The GPL does not require you to release your modified version, or any part of it. You are free to make modifications and use them privately, without ever releasing them. This applies to organizations (including companies), too; an organization can make a modified version and use it internally without ever releasing it outside the organization.

**But if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.**

**Comment by ihm-tswow** [comment]
It must **comply** with the GPL, but your changes need not be GPL (you're allowed to combine MIT and GPL code, for example). There are _some_ complications about changing things like code in individual files (i.e. is it a new module if I add a new function to an already gplv2-ol file?), and this is why azerothcore never updated a lot of their gplv2-or-later headers to the agpl.

**Comment by CraftedRO** [comment]
@ihm-tswow
So basically you are saying that they can "pull" TC code but we can't just because they changed SAME originally license (of few files) without any permission or right as we know ?
Does this sound logically ?

**Comment by Teppic1** [comment]
Please read the FAQ, it repeats over and over that any changes you make to code released unde the GPL must be released also **under the GPL**, not compliant with the GPL. This is a fundamental part of the GPL.

**Comment by Aokromes** [comment]
bug tracker ain't the place to discus about licenses.
