### ISSUE TITLE
DB/world - Unit.cpp - error message

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#27247]
### Description

During playing and using the Mind Control spell (ID 605) - the spell works, but when the controlled subject dies, the server freezes and crashes after about 30 seconds. I performed the test in three times. The result is the same, but the error message is different.

[Mind Control ](https://www.wowhead.com/spell=605/mind-control) ( ID 605 ) 

First report : 

E:\Source\Repos\TrinityCore Branch 9.1.0.40725\src\server\game\Entities\Unit\Unit.cpp:6007 in Unit::SetCharm ASSERTION FAILED:
  charm->GetCharmerGUID() == GetGUID()
Unit 6910 is being uncharmed, but it has another charmer 0000000000000000

Location : Ulduman ( Dungeon ) 
Map ID : 230
Spell : Mind Control 
Attack : does not work
Enrange ( ID : 8599 ) : does not work 

Second report : 

E:\Source\Repos\TrinityCore Branch 9.1.0.40725\src\server\game\Entities\Unit\Unit.cpp:9061 in Unit::ScheduleAIChange ASSERTION FAILED:
  i_disabledAI
Attempt to schedule charm ID change on unit that doesn't have disabled AI

Location : Orgrimmar 
Map ID : 85
Spell : Mind Control
Attack : does not work
Enrange ( ID : 8599 ) : does not work

Third report : 

E:\Source\Repos\TrinityCore Branch 9.1.0.40725\src\server\game\Entities\Unit\Unit.cpp:428 in Unit::~Unit ASSERTION FAILED:
  m_sharedVision.empty()

Location : Ulduman ( Dungeon ) 
Map ID : 230
Spell : Mind Control 
Attack : does not work
Enrange ( ID : 8599 ) : does not work 

Edit : 

Four report :  

E:\Source\Repos\TrinityCore Branch 9.1.0.40725\src\server\game\Entities\Unit\Unit.cpp:428 in Unit::~Unit ASSERTION FAILED:
  m_sharedVision.empty()

Location : Stormwind 
Map ID : 37 
Attack : does not work
Enrange ( ID : 8599 ) : does not work 

[Pastebin](https://pastebin.com/rn6H8t2g)

### Expected behaviour

The spell should work without the fall of the world.

### Steps to reproduce the problem

1. choos a location
2. cast a spell Mind Control ( ID 605 ) 
3. watch your server freeze when they kill a controlled creature

### Branch

master

### TC rev. hash/commit

TrinityCore rev. a54c51c36242 2021-11-03 12:05:43 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
Using MySQL version: 5.7.36
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19043
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1451709970 bytes
vmaps directory located in ./vmaps. Total size: 3361529943 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21101

### Operating system

Win 10 Pro

### Custom changes

none

**Comment by mdX7** [comment]
will likely be fixed by a cherrypick from 335 in the future
