### ISSUE TITLE
Fatal error when extracting maps

### ISSUE THREAD

**Issue by DeerHunt3r** [TrinityCore/TrinityCore#27251]
### Description

Getting fatal error when using the map extractor,
 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Extract VMAP_4.A. Beginning work ....
Opened casc storage 'D:/Games\WOWbaf\_retail_\Data'
Opened casc storage 'D:/Games\WOWbaf\_retail_\Data'
Detected client build: 40906

Extracting GameObject models...
Done!
Read Map.dbc file... Fatal error: Invalid Map.db2 file format! SUCCESS
Incorrect layout hash in FileDataId: 1349477, expected 0xDA9493AF, got 0x9CF2F12F (possibly wrong client version)

D:\Games\WOWbaf\_retail_>vmap4extractor
TrinityCore rev. 1543ca357507 2021-11-05 00:38:43 +0100 (master branch) (Win64, RelWithDebInfo, Static) (VMAP data extractor)
<Ctrl-C> to stop.

### Expected behaviour

it should extract maps and DBC files etc....

### Steps to reproduce the problem

1. update client to 9.1.5 (40906)
2. download latest server code
2. compile server
3. copy compiled vmap4extrator, vmap4assembler, mmapextractor, mmapassembler to the client filefolder
4. run the vmap4extrator
5. watch fail.

### Branch

master

### TC rev. hash/commit

/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file D:/Projects/BuildMaster/bin/RelWithDebInfo/worldserver.conf.
Using SSL version: OpenSSL 1.1.0i  14 Aug 2018 (library: OpenSSL 1.1.0i  14 Aug 2018)
Using Boost version: 1.72.0
Process priority class set to HIGH
Updating Auth database...
>> Auth database is up-to-date! Containing 9 new and 201 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 4 new and 117 archived updates.
Updating World database...
>> World database is up-to-date! Containing 107 new and 3843 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 7 new and 405 archived updates.
Realm running as realm ID 1
Using World DB: TDB 910.21101
Using enUS DBC Locale
Missing name CharacterCreating.DisableAlliedRaceAchievementRequirement in config file D:/Projects/BuildMaster/bin/RelWithDebInfo/worldserver.conf, add "CharacterCreating.DisableAlliedRaceAchievementRequirement = 0" to this file
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 21101
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps
Missing name Guild.SaveInterval in config file D:/Projects/BuildMaster/bin/RelWithDebInfo/worldserver.conf, add "Guild.SaveInterval = 15" to this file
Loading Trinity strings...
>> Loaded 991 trinity strings in 4 ms
Initialize data stores...
Incorrect layout hash in ./dbc/enUS/AreaGroupMember.db2, expected 0xE55374B3, got 0x5C03C8AC (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/AreaTable.db2, expected 0x6AA8A23B, got 0x7EF13BBB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ArtifactAppearanceSet.db2, expected 0x4319E598, got 0x73827201 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ArtifactPowerRank.db2, expected 0xD992FCE6, got 0x4D77EB39 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ArtifactUnlock.db2, expected 0x10D3E54B, got 0xA7A455D2 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/AzeritePowerSetMember.db2, expected 0x240270B4, got 0x7880A4DD (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/AzeriteTierUnlock.db2, expected 0xF90561B4, got 0x365B7BC1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/BannedAddons.db2, expected 0xFFC1F2CD, got 0xF3F45B96 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/BattlePetBreedState.db2, expected 0x5572DEA2, got 0xBEA26E1B (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/BattlePetSpeciesState.db2, expected 0xE5835BBC, got 0x6ED307C3 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Cfg_Regions.db2, expected 0x46753F3C, got 0xDA5ACA56 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrClasses.db2, expected 0x090C9967, got 0x7EF5ADB3 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrClassesXPowerTypes.db2, expected 0x0B71BB3C, got 0x3BDA47A5 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrCustomizationChoice.db2, expected 0xA4453763, got 0xE8148293 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrCustomizationOption.db2, expected 0x961CBF36, got 0xEB7143AC (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ChrRaces.db2, expected 0x40164CD9, got 0x0F5197A5 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/CinematicCamera.db2, expected 0xC5F2F36C, got 0x7BA7D9AC (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Emotes.db2, expected 0xB3BBAC91, got 0x704A62E9 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/EmotesText.db2, expected 0x47FC6428, got 0x6C600BD2 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/EmotesTextSound.db2, expected 0xDDB1DE6E, got 0x18CFC9B1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ExpectedStat.db2, expected 0x04118896, got 0x5243495A (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/FriendshipRepReaction.db2, expected 0x5C9EA26E, got 0x78A33CF1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrAbility.db2, expected 0x92AABEAD, got 0x23F759A6 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrBuilding.db2, expected 0xB0458774, got 0x69CFEA8D (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrClassSpec.db2, expected 0x1362C59A, got 0x43CB5203 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrFollower.db2, expected 0x7982FA48, got 0xA8F69527 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrFollowerXAbility.db2, expected 0xADCDBCC4, got 0x6FE46BDB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrMission.db2, expected 0x72156305, got 0xF35C1992 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrPlot.db2, expected 0xCC5288E7, got 0x3729D438 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GarrPlotInstance.db2, expected 0xA8EA67D0, got 0x6096D1F7 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GlyphBindableSpell.db2, expected 0x5A852AEA, got 0x653A89C4 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/GlyphRequiredSpec.db2, expected 0x95606943, got 0x0C10BD3C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Heirloom.db2, expected 0xECAE6D6C, got 0xA62E347C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemAppearance.db2, expected 0xBE2B504E, got 0x50445CDB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemBonusTreeNode.db2, expected 0x215AE1FF, got 0xC2E0B160 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemDisenchantLoot.db2, expected 0xD8262388, got 0x088EAFF1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Item.db2, expected 0x96B908A5, got 0x5432FBBA (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemLevelSelectorQuality.db2, expected 0xE0678608, got 0x394EA5A6 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemModifiedAppearance.db2, expected 0xB8276541, got 0x1D3C0EBB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemSearchName.db2, expected 0x616E8BCF, got 0x91DAD283 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemSetSpell.db2, expected 0x96588F97, got 0x70A56208 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemSparse.db2, expected 0x59721DCE, got 0x12EE4DFE (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemSpecOverride.db2, expected 0xA10DBD4A, got 0x52DBFC86 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemXBonusTree.db2, expected 0x87253AAD, got 0x9C8FF861 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/ItemXItemEffect.db2, expected 0xAB91E2D8, got 0x5D602214 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/KeystoneAffix.db2, expected 0x50726ADB, got 0xF5F1EB34 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/LanguageWords.db2, expected 0x8AF6E8C1, got 0x364344E1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/LFGDungeons.db2, expected 0x4480A7C8, got 0x0BAF7AF1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/LiquidType.db2, expected 0xD0172A80, got 0xD4966711 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/Map.db2, expected 0x9CF2F12F, got 0xDA9493AF (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/MapChallengeMode.db2, expected 0x6C470AF8, got 0xAA74ABBB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/MapDifficultyXCondition.db2, expected 0x35ACEFCA, got 0x0278FDBB (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/NameGen.db2, expected 0x49AF9298, got 0x76610958 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/NamesProfanity.db2, expected 0x7E5D907A, got 0xCE63393A (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/NamesReserved.db2, expected 0x3F7A5E4A, got 0xE722960A (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/NamesReservedLocale.db2, expected 0x939EBBCF, got 0x5144468F (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/PhaseXPhaseGroup.db2, expected 0x6A500919, got 0xF66B1AC6 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/PowerDisplay.db2, expected 0x1CC1F41C, got 0xC091809C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/PowerType.db2, expected 0x60A61B4C, got 0xF9D4B3CC (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/PVPDifficulty.db2, expected 0xCB799A74, got 0x8D90498B (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/QuestInfo.db2, expected 0xC508CFB5, got 0x54A97E8C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/QuestLineXQuest.db2, expected 0xF6975B65, got 0xFF15296C (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/RewardPackXCurrencyType.db2, expected 0xFF9E3096, got 0xCC6A3E87 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SceneScript.db2, expected 0x3F190B4A, got 0x1D557390 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SceneScriptPackage.db2, expected 0x7A18CA1C, got 0x887BEAEA (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SkillLine.db2, expected 0x13763D15, got 0xF1776F95 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpecSetMember.db2, expected 0x64CD1E2D, got 0x7A37DBE1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellAuraOptions.db2, expected 0x7418EBE8, got 0x25E72B24 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellAuraRestrictions.db2, expected 0xBF42FB43, got 0xA9D83D8F (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellCategories.db2, expected 0x637E61DD, got 0x78E91F91 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellCooldowns.db2, expected 0x8A952DCF, got 0x9FFFEB83 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellInterrupts.db2, expected 0x62CE2641, got 0x4D63688D (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellLabel.db2, expected 0x46008468, got 0xF7CEC3A4 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellLevels.db2, expected 0x646702ED, got 0x79D1C0A1 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellMisc.db2, expected 0x0084BE9B, got 0xB252FDD7 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellPower.db2, expected 0xC41C9FCF, got 0xD9875D83 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellProcsPerMinuteMod.db2, expected 0xD07F9EA0, got 0x2EF9CF3F (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellTargetRestrictions.db2, expected 0x573DA9BA, got 0x090BE8F6 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/SpellXSpellVisual.db2, expected 0x06029294, got 0x54345358 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/TransportAnimation.db2, expected 0x986AE487, got 0xE69CA54B (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/TransportRotation.db2, expected 0x9BBA6ACB, got 0x4D88AA07 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/UiMapXMapArt.db2, expected 0x9776E9C8, got 0x49452904 (possibly wrong client version)
Incorrect layout hash in ./dbc/enUS/WorldStateExpression.db2, expected 0xCB64D021, got 0x340F8A17 (possibly wrong client version)
Unable to load db2 files for enUS locale specified in DBC.Locale config!

### Operating system

Windows server 2012 R2 server side windows 10 client

### Custom changes

None

**Comment by MaxtorCoder** [comment]
Wait for the tools to be updated...... And next time use pastebin for log lines.

**Comment by DeerHunt3r** [comment]
> Wait for the tools to be updated...... **And next time use pastebin for log lines**.

Understood.  Thanks.

**Comment by kalamoony** [comment]
> > Wait for the tools to be updated...... **And next time use pastebin for log lines**.
> 
> Understood. Thanks.

hello, I know thiss is an old issue , but would you tell mehow you solved it , i am facing exact the same issue .
