### ISSUE TITLE
Core/Instance ZulGurub boss_jeklik flag error

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27259]
### Description

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp#L184

The summoned creature is unselectable, can check this issue from the database?

I direct this because their reset flag is set here
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp#L216

Perhaps it should be set from the database to be initially selected

### Expected behaviour

You can choose and beat it

### Steps to reproduce the problem

1.go cr 49199
2.Start the battle and.dam 100000 to third stage
3.Cannot be selected

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/04909bada85d4770a58a5b2b6f2180f5aacb1b81

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by w5860363** [comment]
And BOSS will not reset back to the refresh point, maybe you should get the coordinates to solve this problem

**Comment by CraftedRO** [comment]
most likely is related to some flags

**Comment by CraftedRO** [comment]
Are you talking about Bloodseeker Bats right ?

**Comment by w5860363** [comment]
@CraftedRO is 14965 for the third stage and 11368 for the first stage
FRENZIED BAT = 14965

**Comment by CraftedRO** [comment]
Indeed confirm this , they have uninteractible flag , no ideea why.
```
NPC currently selected by player:
Name: Frenzied Bloodseeker Bat
SpawnID: 0, current GUID low: 517.
Entry: 14965.
Faction: 28.
NPC Flags: 0.
DisplayID: 3956 (Native: 3956).
Compatibility Mode: 0
Level: 60.
EquipmentId: 0 (Original: 0).
Health (base): 6104. (max): 6104. (current): 6104.
Movement type: Ground: Run, Swim: false, Flight: CanFly, Chase: Run, Random: Walk, InteractionPauseTimer: 180000
Unit Flags: 34078720
  UNIT_FLAG_IN_COMBAT (0x80000)
  UNIT_FLAG_UNINTERACTIBLE (0x2000000)
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 28.
SpawnTime: Full:5m Remaining:0s
Loot: 0 Pickpocket: 0 Skinning: 0
InstanceID: 1
Phasemask: 1
Armor: 3750
Position: -12299.229492 -1365.635986 147.408340.
AIName:  ScriptName: npc_batrider
React state: AGGRESSIVE
Active AI: struct npc_batrider
Flags Extra: 64
  CREATURE_FLAG_EXTRA_NO_XP (0x40)
MechanicImmuneMask: 0
```
![WoWScrnShot_110921_123839](https://user-images.githubusercontent.com/24683355/140909403-2bc6142d-6dea-4627-81f8-0693d36f9600.jpg)

**Comment by CraftedRO** [comment]
BTW the boss does reset after leaving combat for me

**Comment by w5860363** [comment]
@CraftedRO If you jump to the bottom of the BOSS is swimming back to the current position which leads to the misalignment

flag Maybe from https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp#L216

**Comment by CraftedRO** [comment]
https://www.youtube.com/watch?v=T9_oghoERTc
old video (2009) as proof they have to be attackables

**Comment by CraftedRO** [comment]
https://www.youtube.com/watch?v=T9_oghoERTc
https://youtu.be/iKsCRJckZWA -- this one from 2k10 read description
old video (2009) as proof they have to be attackables

**Comment by CraftedRO** [comment]
https://www.youtube.com/watch?v=T9_oghoERTc -- old video (2009)
https://youtu.be/iKsCRJckZWA -- this one from 2k10 read description
As proof they have to be both attackable but also selectable.

**Comment by CraftedRO** [comment]
[cmangos code look like this](https://github.com/cmangos/mangos-wotlk/blob/da608fbcbcb4c50b0b6a96df62495bdedfa84482/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/zulgurub/boss_jeklik.cpp#L339)

**Comment by w5860363** [comment]
@CraftedRO 14965 should have the same creature_template_movement value as 11368 and rooted = 1 which should stop them from falling to the ground
