### ISSUE TITLE
DB/Creature: Spellmaw some updates

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#27253]
### Description

Spellmaw need to be immune to all kind of cc and slows
https://tbc.wowhead.com/npc=10662/spellmaw#comments:id=242565

> Immune to cc as well.

### SQL fix

```sql
-- Delete Spellmaw - Damage Immunity: Arcane , ​because it already have spell_school_I_M 64
DELETE FROM `smart_scripts` WHERE `entryorguid` = 10662 AND `source_type` = 0 AND `id` = 0;

-- According to all https://tbc.wowhead.com/npc=10662/spellmaw#comments he is immune to all kind of cc and slows
-- Probably I missed some flags , need recheck
UPDATE `creature_template` SET `mechanic_immune_mask` = 212699 WHERE `entry` = 10662;
```

### Branch

3.3.5

### TC rev. hash/commit

6e07acbbdeb5

**Comment by CraftedRO** [comment]
Seems valid for https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=10202 Azurous too
https://tbc.wowhead.com/npc=10202/azurous#comments

**Comment by offl** [comment]
I simply picked https://github.com/vmangos/core/blob/a01720f547f0d042b7989085a1a3558cc6e92a64/sql/old_migrations/20190729161352_world.sql
I don't think dragons should be immune to poly or banish
