### ISSUE TITLE
DB/Race & class - Pandaren & Death Knight

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#27278]
### Description

Alliance & Horde : 
When choosing a Pandaren, it is possible to choose the Death Knight class, but such a choice should not be at all.
![Ashampoo_Snap_pondelok 15  novembra 2021_19h55m25s_002_](https://user-images.githubusercontent.com/7515044/141840456-9b4b48b4-0afa-4776-821f-2919948a97f9.png)

### Expected behaviour

The selection should only be for: Warrior, Hunter, Mage, Rogue, Priest, Shaman and Monk.

### Steps to reproduce the problem

1. Choose a race Pandaren
2. see choice of Death Knight class

### Branch

master

### TC rev. hash/commit

TrinityCore rev. c1915d386c19 2021-11-12 19:25:09 +0100 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.72.0
Using MySQL version: 5.7.36
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19043
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1451755434 bytes
vmaps directory located in ./vmaps. Total size: 3361827341 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 910.21101

### Operating system

Win 10 Pro  v. 21H1

### Custom changes

none

**Comment by Shauren** [comment]
Pandarens can be death knights since 9.0

**Comment by shamage** [comment]
So this escaped me.

**Comment by MaxtorCoder** [comment]
> So this escaped me.

Check Retail/PTR next time please. 😄💪🏼 Thanks for the effort tho!
