### ISSUE TITLE
CMake Error at cmake/genrev.cmake:116 (string):

### ISSUE THREAD

**Issue by 618hmcom** [TrinityCore/TrinityCore#27272]
### Description

CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

### Expected behaviour

CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

### Steps to reproduce the problem

not work

### Branch

3.3.5

### TC rev. hash/commit

1

### Operating system

win 2016

### Custom changes

1

**Comment by Shauren** [comment]
You have git installed on that machine so you must not use this to download source code 
![obraz](https://user-images.githubusercontent.com/297439/141654589-ce62febb-312e-4eba-a65b-29a5827308db.png)

Follow the tutorial and use `git clone`
