### ISSUE TITLE
Core/SmartAI Some Sai failure causes are unknown

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27299]
### Description

1.https://github.com/TrinityCore/TrinityCore/issues/21512 not work
https://www.wowdb.com/quests/533-deprecated-infiltration
2.zone_ western_ Plaguelands.cpp to Sai failure quest 5944 not work
https://www.wowdb.com/quests/5944-in-dreams
3.https://www.wowdb.com/quests/10439-dimensius-the-all-devouring not work
4.https://www.wowdb.com/quests/10248-you-robot not work
5.https://www.wowdb.com/quests/10409-deathblow-to-the-legion
6.https://www.wowdb.com/quests/10594-gauging-the-resonant-frequency not work

Normally, these tasks are all caused by C + + converting Sai and mobile classes, so I wonder if they are caused by common reasons

### Expected behaviour

Normal work

### Steps to reproduce the problem

1.go cr 70967
2.quest add 10248
3.Nothing will happen

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/57617e215b2f45ba1636e0002714792326c3e57c

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by w5860363** [comment]
quest 11496 Can't continue, but I haven't determined his reason
quest 10935  It is controlled by C + +, but there will be a large number of summoners. Random numbers do not work

**Comment by w5860363** [comment]
@offl @CraftedRO Can you help determine the cause of this problem

**Comment by offl** [comment]
>1.#21512 not work

Everything works for me, both cosmetic event and the quest itself

>https://www.wowdb.com/quests/533-deprecated-infiltration

Same

>2.zone_ western_ Plaguelands.cpp to Sai failure quest 5944 not work
https://www.wowdb.com/quests/5944-in-dreams
3.https://www.wowdb.com/quests/10439-dimensius-the-all-devouring not work
4.https://www.wowdb.com/quests/10248-you-robot not work
5.https://www.wowdb.com/quests/10409-deathblow-to-the-legion
6.https://www.wowdb.com/quests/10594-gauging-the-resonant-frequency not work
quest 10935 It is controlled by C + +, but there will be a large number of summoners. Random numbers do not work

Issues for those quests are already open

>quest 11496 Can't continue, but I haven't determined his reason

That quest is not available

In future please follow the 'one issue - one bug' rule

**Comment by CraftedRO** [comment]
Meh I won't do any other stuff for tc anyway , they simple don't care about fixing old quest bugs and when it comes about some sql fixes they close them because of license reason even if I spend all day for reasearch and tests.
