### ISSUE TITLE
Core/Map Unknown cause of object problem

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27290]
### Description

Unable to leave the house after being released from mind control

https://wotlkdb.com/?spell=36146#used-by-npc

Maybe it has something to do with https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CoreAI/PetAI.cpp#L640

### Expected behaviour

Mind control should not work on OBJECT

### Steps to reproduce the problem

1.go cr 72506
2.Waiting to be hit by spell 36146  can not leave the house after getting out of the fight

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/9cb86a42a9cc2c44507d1ce604a1856b91bb385e

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by w5860363** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CoreAI/PetAI.cpp#L640
If you block it out, there will be problems, but if you don't block it out, it will make your pet lose control.https://github.com/TrinityCore/TrinityCore/issues/27226

**Comment by jackpoz** [comment]
What happened to this issue ?

**Comment by w5860363** [comment]
@jackpoz Related to another issue Resolved https://github.com/TrinityCore/TrinityCore/issues/27226
is out of control due to related issues
So it's an error report
