### ISSUE TITLE
[master] Demonhunter does not have full health after creation

### ISSUE THREAD

**Issue by funjoker** [TrinityCore/TrinityCore#27295]
### Description

Currently the demonhunter does not have full health on creation.
You start with maybe a quater of health and the red alert frame.

### Expected behaviour

New characters should start with full health. Probably only appeard at characters starting higher than level 1.

### Steps to reproduce the problem

1. Create a demonhunter
2. Login

### Branch

master

### TC rev. hash/commit

017537173034b4db21b9ecf568101586fa526405

### Operating system

Win 11

### Custom changes

None

**Comment by Naddley** [comment]
[151dd67e2eb22e49ce84c2eb28b08985bcce7602] seems to be fixxed.
