### ISSUE TITLE
MySQL8 with mariadb-common, libmariadb-dev, libmariadb-dev-compat

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#27306]
### Description

When using a bundle of Mysql 8 and mariadb-common, libmariadb-dev, libmariadb-dev-compat, 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/database/Database/MySQLConnection.cpp
in this part of the code does not work as intended.

```
#if !defined(MARIADB_VERSION_ID) && MYSQL_VERSION_ID >= 80000
        mysql_ssl_mode opt_use_ssl = SSL_MODE_DISABLED;
        if (m_connectionInfo.ssl == "ssl")
        {
            opt_use_ssl = SSL_MODE_REQUIRED;
        }
        mysql_options(mysqlInit, MYSQL_OPT_SSL_MODE, (char const*)&opt_use_ssl);
#else
        MySQLBool opt_use_ssl = MySQLBool(0);
        if (m_connectionInfo.ssl == "ssl")
        {
            opt_use_ssl = MySQLBool(1);
        }
        mysql_options(mysqlInit, MYSQL_OPT_SSL_ENFORCE, (char const*)&opt_use_ssl);
#endif
```

The problem is that if there is a libmariadb-dev library installed in the system, the MARIADB_VERSION_ID value will always be present, and if there is a libmariadb-dev-compat library, the MYSQL_VERSION_ID value will also be determined and it will be equal to MARIADB_VERSION_ID. The && condition will never be met.

Also, when loading the server in the logs, we can see the discrepancy between the versions:
```
Using configuration file /home/trinity/server/etc/authserver.conf.
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.3.31
MySQL server ver: 8.0.27-0ubuntu0.20.04.1
Connected to MySQL database at 127.0.0.1
MySQL client library: 10.3.31
MySQL server ver: 8.0.27-0ubuntu0.20.04.1
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Loading IP Location Database...
```

### Expected behaviour

I guess it should work like this:
```
#if defined(MARIADB_VERSION_ID) || MYSQL_VERSION_ID < 80000

        MySQLBool opt_use_ssl = MySQLBool(0);
        if (m_connectionInfo.ssl == "ssl")
        {
            opt_use_ssl = MySQLBool(1);
        }
        mysql_options(mysqlInit, MYSQL_OPT_SSL_ENFORCE, (char const*)&opt_use_ssl);

#else
        mysql_ssl_mode opt_use_ssl = SSL_MODE_DISABLED;
        if (m_connectionInfo.ssl == "ssl")
        {
            opt_use_ssl = SSL_MODE_REQUIRED;
        }
        mysql_options(mysqlInit, MYSQL_OPT_SSL_MODE, (char const*)&opt_use_ssl);
		
#endif
```

If we use maria or the mysql version is less than 8, then we use the old connection option, otherwise we connect with new parameters (SSL_MODE_REQUIRED).
It is also necessary to check MYSQL_OPT_SSL_MODE in connection with the fact that:

https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html
>For the C API, MYSQL_OPT_SSL_ENFORCE and MYSQL_OPT_SSL_VERIFY_SERVER_CERT options for mysql_options() correspond to the client-side --ssl and --ssl-verify-server-cert options and are removed. Use MYSQL_OPT_SSL_MODE with an option value of SSL_MODE_REQUIRED or SSL_MODE_VERIFY_IDENTITY instead.

### Steps to reproduce the problem

1) Installed server MySQL:
apt-get install mysql-server

2) go to https://trinitycore.atlassian.net/wiki/spaces/tc/pages/10977288/Linux+Requirements and install other:
apt-get install git clang cmake make gcc g++ libmariadbclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev mariadb-server p7zip libmariadb-client-lgpl-dev-compat

3) cmake ../ -DCMAKE_INSTALL_PREFIX=/home/username/server
4) make && make install

### Branch

3.3.5

### TC rev. hash/commit

542c100

### Operating system

Ubuntu 20, MySQL 8.

### Custom changes

None

**Comment by Shauren** [comment]
I don't see the problem, your "proposed" code does exactly the same as our existing code.
It is simply impossible to do what you are trying to achieve here, there is no way to use MYSQL_OPT_SSL_MODE+SSL_MODE_REQUIRED with libmariadb, it will not compile, those definitions come from libmariadb headers (and they dont have it), not from server headers (this is intended)
