### ISSUE TITLE
Core/Instance ZulGurub boss_thekal It will not entry phase two

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27301]
### Description

thekal It will not entry phase two

### Expected behaviour

Enter the second stage and the three creatures share the resurrection

### Steps to reproduce the problem

1.go cr 49310
2.dmg
3.boss kill not entry phase two

### Branch

3.3.5

### TC rev. hash/commit

57617e2

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by offl** [comment]
Can't reproduce
