### ISSUE TITLE
Core/Spell Dot will break foor and Drink effect

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27302]
### Description

In the current 70 Blizzard server, dot will not break the food effect
But it will break the first aid

### Expected behaviour

Determine whether it is correct in 3.3.5 X

### Steps to reproduce the problem

1.add food or drink
2.aura 24321 to me
3.The food effect is broken

### Branch

3.3.5

### TC rev. hash/commit

57617e2

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Aokromes** [comment]
food or drink is own effect,
bandage is 3rd party effect.

https://www.mmo-champion.com/threads/1272457-Eating-with-DoTs-active
