### ISSUE TITLE
DB/GameObject 180600 Unstable Mana Crystal Crate can not be cast.

### ISSUE THREAD

**Issue by Angel-Asuka** [TrinityCore/TrinityCore#27314]
### Description

Any [Unstable Mana Crystal Crate (180600)](http://www.wowhead.com/object=180600/unstable-mana-crystal-cratel) can not be cast by any player even if they already have the quest [Unstable Mana Crystals (8463)](http://www.wowhead.com/quest=8463/unstable-mana-crystals).

### SQL fix

```sql
--
-- Fix loot of [Unstable Mana Crystal Crate]
-- Move loot id from Data30 to Data1
UPDATE `gameobject_template` SET `Data1` = '17450', `Data30` = '0' WHERE `gameobject_template`.`entry` = 180600
```

### Branch

master

### TC rev. hash/commit

084491669e084b31b3d487b26a6e6f6556a99b8a

**Comment by Aokromes** [comment]
changing data? without sniff is hack.

**Comment by acidmanifesto** [comment]
So this is pulled right from the TC wiki with gameobjects.

```
GAMEOBJECT_TYPE_CHEST = 3

data0: open (LockId from Lock.dbc)
data1: chestLoot (gameobject_loot_template.entry) WDB-fields
data2: chestRestockTime (time in seconds)
data3: consumable (State: Boolean flag)
data4: minRestock (Min successful loot attempts for Mining, Herbalism etc)
data5: maxRestock (Max successful loot attempts for Mining, Herbalism etc)
data6: lootedEvent (Event ID from table event_scripts)
data7: linkedTrap (gameobject_template.entry (Spawned GO type 6))
data8: questID (quest_template.id of completed quest)
data9: level (minimal level required to open this gameobject)
data10: losOK (Boolean flag)
data11: leaveLoot (Boolean flag)
data12: notInCombat (Boolean flag)
data13: log loot (Boolean flag)
data14: openTextID (broadcast_text ID)
data15: use group loot rules (Boolean flag)
data16: floating tooltip
data17: conditionid1
data18: xplevel
data19: xpDifficulty
data20: lootlevel
data21: Group Xp
data22: Damage Immune
data23: trivialSkillLow
data24: trivialSkillHigh
data25: Dungeon Encounter
data26: spell
data27: GiganticAOI
data28: LargeAOI
data29: spawnVignette
data30: chestPersonalLoot
data31: turnpersonallootsecurityoff
data32: Chestproperties
```
In 335 we have it set up as that currently with TC.
![image](https://user-images.githubusercontent.com/16887899/143251632-e99a4075-f106-44bb-96f5-f863e344ea62.png)

I guess what we should be really asking is, why was it moved to personal loot in master, it is only lootable durning a quest https://www.wowhead.com/quest=8463/unstable-mana-crystals? And the Unstable Mana Crystals only contained one item lootable only durning that quest only.

**Comment by Shauren** [comment]
it was moved to personal loot to allow multiple players to use the same chest instead of having to fight for respawns
it is currently not implemented but we will not accept any changes that move the loot back to old system
