### ISSUE TITLE
[SQL][WIP] Add Maghar Orc spawns to Orgrimmar

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#27318]
### Description

Add spawns, conversation, phasing for the Maghar Orcs

### SQL fix

```sql
https://gist.github.com/Naddley/ab83ada20c3031b8ba7ef3f3b256f4a7
```

### Branch

master

### TC rev. hash/commit

commit 402e63427e5ab005d148bec9d04b91f66fa7f285

**Comment by mdX7** [comment]
All maghar orc npcs in Orgrimmar are individually pooled except `Overlord Geya'rah`. This is also the case for maghar orc npcs @ embassy
