### ISSUE TITLE
Core/Data Quest 10439 dimensius-the-all-devouring not work

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27324]
### Description

https://www.wowdb.com/npcs/20985-captain-saeed There is neither gossip_menu_option nor sai nor C++, so it doesn't move

### Expected behaviour

NPC normal movement

### Steps to reproduce the problem

1.go cr 73766
2.quest add 10439

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/ef4c878d260c0e01a6ab2f4391af46c261d04785

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Aokromes** [comment]
duplicate.
