### ISSUE TITLE
quest Helcular Remains 553

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27323]
**Description**
https://github.com/TrinityCore/TrinityCore/issues/21512
Just random movement and will not attack

**Branch**
3.3.5

**TC rev. hash/commit**
ef4c878

**Comment by Aokromes** [comment]
don't open both ticket for bug and ticket for fix, open a single ticket.
https://github.com/TrinityCore/TrinityCore/issues/27322
