### ISSUE TITLE
Core/Db faction Revered  not gossip_menu

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27335]
### Description

gossip 9205 It is not shown in respect, only in respect
Maybe there's something wrong with my test method
known relationship commitment https://github.com/TrinityCore/TrinityCore/commit/67198416f0d4b55a6ff21e09d0cf42b423f39263
https://github.com/TrinityCore/TrinityCore/commit/5dd6b8b2dcc99644f103a31e48fd5194795db123

### Expected behaviour

Apply the 192 options of the conditions database correctly

### Steps to reproduce the problem

1.go cr 94504
2.modify rep 989 9000
3.gossip not add

### Branch

3.3.5

### TC rev. hash/commit

9174281

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Jinnaix** [comment]
You need to be Revered or Exalted with the Keepers of Time to use this. The least amount of rep you need is 21.000

Working as intended, not a bug.
