### ISSUE TITLE
Core/Smart quest 10409 deathblow-to-the-legion

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27334]
### Description

https://www.wowhead.com/quest=10409/deathblow-to-the-legion

### Expected behaviour

NPC appears normally and the target can be attacked

### Steps to reproduce the problem

1.quest add 10409
2.go gameobject 99954
3.use item 29769
4.npc 19496 No spawn

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/9174281b9253712982273b9b703d9fbac5cef9cd

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3746
