### ISSUE TITLE
DB/Creature: creature_template_scaling massparses of 9.0.2

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#27331]
### Description

^

### SQL fix

```sql
https://gist.github.com/mdX7/f908e30c7395ef5ef8240de2052f03a8
```

### Branch

master

### TC rev. hash/commit

aeece162b9d93c9d248ea8ba464cf28ae532f034

**Comment by offl** [comment]
>Member

Congratulations :)
