### ISSUE TITLE
Error when building with Clang pch ON

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#27343]
### Description

Compiling with clang 11 produces following error when compiling with PCH on.
```
[ 40%] Building CXX object src/server/game/CMakeFiles/game.dir/Miscellaneous/enuminfo_SharedDefines.cpp.o
/home/runner/work/TrinityCore/TrinityCore/src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp:112:47: fatal error: explicit specialization of 'Count' after instantiation
TC_API_EXPORT size_t EnumUtils<SpellSchools>::Count() { return 7; }
                                              ^
/home/runner/work/TrinityCore/TrinityCore/src/common/Utilities/SmartEnum.h:53:72: note: implicit instantiation first required here
        static size_t Count() { return Trinity::Impl::EnumUtils<Enum>::Count(); }
                                                                       ^
1 error generated.
```

### Expected behaviour

No error when compiling

### Steps to reproduce the problem

Compile using following script.
pch: OFF passes, but ON fails with the error above

```bash
sudo apt-get update && sudo apt-get install -yq libboost-all-dev clang-11
mkdir bin
cd bin
cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=ON -DUSE_SCRIPTPCH=ON -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
make -j 4 -k && make install
```

### Branch

master

### TC rev. hash/commit

66225c27e4a6ac0855b0c5297c73a32e3564bcc0

### Operating system

Ubuntu 20.04.3

### Custom changes

None

**Comment by Shauren** [comment]
You are the second person to report this but I'm still not able to reproduce it

**Comment by jackpoz** [comment]
Is that with a clean checkout ?
Is the cmake command with clang-11 another example ?

**Comment by Rochet2** [comment]
> Is that with a clean checkout ?

yes

> You are the second person to report this but I'm still not able to reproduce it

Hmm. Ill try on another machine later today maybe.

> Is the cmake command with clang-11 another example ?

Ahh, good one. The files are named gcc but clang is used.

**Comment by Rochet2** [comment]
In any case - shouldnt template specializations be before the use of the templated code?
So in this case any file including the header will not see the code in the cpp I assume.
Moving the specializations or their declarations to the header could solve the issue I assume.

**Comment by mweinelt** [comment]
> You are the second person to report this but I'm still not able to reproduce it

I was the other person who reported this. Still encountering this issue with a clean build on llvm11/12/13, now also for `FromIndex`.

```c++
/build/source/src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp:160:47: error: explicit specialization of 'Count' after instantiation
TC_API_EXPORT size_t EnumUtils<SpellSchools>::Count() { return 7; }
                                              ^
/build/source/src/common/Utilities/SmartEnum.h:53:72: note: implicit instantiation first required here
        static size_t Count() { return Trinity::Impl::EnumUtils<Enum>::Count(); }
                                                                       ^
/build/source/src/server/game/Miscellaneous/enuminfo_SharedDefines.cpp:163:53: error: explicit specialization of 'FromIndex' after instantiation
TC_API_EXPORT SpellSchools EnumUtils<SpellSchools>::FromIndex(size_t index)
                                                    ^
/build/source/src/common/Utilities/SmartEnum.h:57:86: note: implicit instantiation first required here
        static Enum FromIndex(size_t index) { return Trinity::Impl::EnumUtils<Enum>::FromIndex(index); }
                                                                                     ^
2 errors generated.
```

**Comment by Rochet2** [comment]
I failed to reproduce this on my laptop (ubuntu 20.04), but it is reproducible on github actions.
https://github.com/Rochet2/TrinityCore/runs/4750694389?check_suite_focus=true
_master ON is the latest (at time of running the build) TC master branch with PCH ON and it has been failing at least for a month now. PCH OFF seems to succeed though.
You can see the run steps here: https://github.com/Rochet2/TrinityCore/blob/f3eab51f029f8a7de472feae85e1de5d05d659bf/.github/workflows/merge.yml

**Comment by mweinelt** [comment]
Thanks, can confirm that fixed it.
