### ISSUE TITLE
[SQL] Spawn Hunter Pets Alliance (NEP)

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#27340]
### Description

Spawn Hunter Pets and Phasing

### SQL fix

```sql
https://gist.github.com/Naddley/f7dbc7c3b43098e9483779513fc64b1e
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 402e634

**Comment by mdX7** [comment]
all the `_addon` entries are not required. `(@CGUID+0, 0, 0, 0, 1, 0, 0, 0, 0, ''),` are the default values which the core loads if no row is found

**Comment by Naddley** [comment]
updated with missing Hunter Conditions.
