### ISSUE TITLE
DB/SAI: Too fast spawntime Arcatraz

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27350]
### Description

https://www.wowhead.com/the-arcatraz

npc [protean-horror ](https://www.wowhead.com/npc=20865/protean-horror) spawntimesecs = 7200
Significantly faster than 20859 attacking them

The old database time is 86400. Is this intentional?

### Expected behaviour

https://www.youtube.com/watch?v=ZuJZi5pkhYo

### Steps to reproduce the problem

1.go cr 79444
2.Wait and observe Sai attacking creatures

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/251304b19c2fc42ee330b9a533b54f7b80df5d4a

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Aokromes** [comment]
5 man instances have 2h respawns. 86400 is raid respawn time.

**Comment by offl** [comment]
Mobs you're talking about are not spawned in DB, they're summoned as long as warders and defenders at the start of instance are not killed

7200 is respawn time for both raids and dungeons in case of trash
86400 is for dungeon bosses or creatures which are not meant to be respawned in dungeons after being killed or despawned
