### ISSUE TITLE
DB/Misc: Battle Pet trainers (Alliance)

### ISSUE THREAD

**Issue by meji46** [TrinityCore/TrinityCore#27359]
### Description

Added spawns, vendor & trainer data and SAI for alliance battle pet trainers

### SQL fix

```sql
https://gist.github.com/meji46/f2d2b67784b58fd8ef88376a3068043d
```

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/52824eedd374c92f53c772fe6431518a5f30626d

**Comment by offl** [comment]
```sql
(8130,2,0,0,46,0,100,0,0,0,0,0,0,'',45,1,1,0,0,0,0,19,63014,20,0,0,0,0,0,0,'Areatrigger 8130 - On trigger - Set data 1 1 on Marcus Jensen'),
(63014,0,0,1,38,0,100,0,1,1,0,0,0,'',11,116219,2,0,0,0,0,7,0,0,0,0,0,0,0,0,'Marcus Jensen - On data set 1 1 - Cast ''CSA Area Trigger Dummy Timer Aura A'' on invoker'),
(63014,0,1,0,61,0,100,0,0,0,0,0,0,'',1,0,0,1,0,0,0,7,0,0,0,0,0,0,0,0,'Marcus Jensen - Event linked - Say text');
```
>(#27336 required)

Now it auto-targets invoker-player?

**Comment by meji46** [comment]
Yes, that's the idea of the PR. In this case, it's the player who performs the set data action (so it acts as invoker of the event)

**Comment by offl** [comment]
Interesting
