### ISSUE TITLE
DB\CTMO: Griffon Hatching Pet fly follows while mount flying in outland.

### ISSUE THREAD

**Issue by acidmanifesto** [TrinityCore/TrinityCore#27365]
### Description

Griffon Hatchling should FLY follow the player while they are mount flying, currently it does not.
**Currently** it walks follows when the player is not mounted:
![image](https://user-images.githubusercontent.com/16887899/144752473-ae018762-7969-4e98-9fb6-135145386678.png)

**Currenlty** it hovers when the player is Mounted with a ground mount:
![image](https://user-images.githubusercontent.com/16887899/144752494-921b7cf6-e50c-42ff-8469-3c6cb8d20e4b.png)

**Currently** it stays on the ground hovering when the player flys with their mount:
![image](https://user-images.githubusercontent.com/16887899/144752787-a54b6e74-4302-4052-905e-801c18113a7a.png)

**With this sql**, the griffon pet hatchling will follow the player while flying with a mount:
![image](https://user-images.githubusercontent.com/16887899/144752520-cf9b048a-e095-4303-8f84-b6a92d8107ba.png)

Steps to test:
.additem 49662
learn the pet
summon pet
See if you are not mounted that it runs with you.
See if you are mounted that it flies follows you.
See if you are Mount flying that it flies with you.

NOTE Doing a .gm fly while not mounted, will show the pet in a none flying animation when following you. This combination is impossible when playing as a level account 0 player.

Changes proposed:

GIves pet Griffon Hatchling the ability to fly with you as reported online.
https://www.wowhead.com/item=49662/gryphon-hatchling

![image](https://user-images.githubusercontent.com/16887899/144752393-1f0a32fa-f515-4595-a62e-3b328158e85c.png)

Current this sets  Ground to 1 and Flying set to 2 in CTM
![image](https://user-images.githubusercontent.com/16887899/144752420-675da2c7-1a0b-4b8a-9e19-ea8fb344d561.png)

**TO DO**
[] Gather list of flying pets for 335 and double check their CTM tables.

### SQL fix

```sql
-- Adds CTMO for Griffon Hatchling
DELETE FROM `creature_template_movement` WHERE `CreatureId`=36908;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`) VALUES (36908, 1, 0, 2, 0, 0, 0, NULL);
```

### Branch

3.3.5

### TC rev. hash/commit

35b55b3

**Comment by offl** [comment]
Check https://github.com/TrinityCore/TrinityCore/issues/26600#issuecomment-866305679
And https://github.com/TrinityCore/TrinityCore/pull/26897

Flight = 2 should never be set in DB or scripts

**Comment by acidmanifesto** [comment]
> Check [#26600 (comment)](https://github.com/TrinityCore/TrinityCore/issues/26600#issuecomment-866305679) And #26897
> 
> Flight = 2 should never be set in DB or scripts

I am a bit confused. if Flight = 2 is never suppose to be set in the DB and Scripts, then why have it as a option?
Also why is the pet not flying and following me while i mount fly without the sql adjustment on the latest revision?
Zero Modules and custom alteration in this case.

**Comment by offl** [comment]
>I am a bit confused. if Flight = 2 is never suppose to be set in the DB and Scripts, then why have it as a option?

Because it should be replaced with Flight = 1 first

>Also why is the pet not flying and following me while i mount fly without the sql adjustment on the latest revision?

It works like explained in PR
>However, when I spawn that mini-pet and mount, it falls every time it follows me. I mean, it still can fly. But if I walk somewhere after spawning it to launch his follow movement at least once, everything works fine every time I mount or dismount

#27366

**Comment by offl** [comment]
By default its anim tier is 0 and no movement flags such as Fly or DisableGravity
Adding default value will make pet fly always even if player is not mounted

**Comment by acidmanifesto** [comment]
New issue written up for follow up here:
https://github.com/TrinityCore/TrinityCore/issues/27366
