### ISSUE TITLE
Game client crash at characters login

### ISSUE THREAD

**Issue by zTerragor** [TrinityCore/TrinityCore#27361]
### Description

https://gist.github.com/zTerragor/9fe109abbb3fc6596dbbecc93f4acd6b.js

### Expected behaviour

Good time of day. After the end of character creation and when entering the game, the game client crashes with the following error

### Steps to reproduce the problem

1. starting the server 
![image](https://user-images.githubusercontent.com/81566364/144669135-399f62c4-6159-4bbf-a283-21e730a02c47.png)
2. logging into the game
![image](https://user-images.githubusercontent.com/81566364/144669528-f3a3cf2e-8c18-4da0-8458-88ce52ec40b9.png)
3 crash
![image](https://user-images.githubusercontent.com/81566364/144669655-8ecf0f81-8733-41b1-9ce4-45b692b3655d.png)

### Branch

master

### TC rev. hash/commit

768ed2cbdcaa

### Operating system

Windows 10 x64, 

### Custom changes

None

**Comment by Shauren** [comment]
You have custom hotfixes, remove them.
