### ISSUE TITLE
Core/Handlers Cancel channel spell

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27373]
### Description

channel spell [5143](https://www.wowdb.com/spells/5143-arcane-missiles) 
When you reuse it during its release, you will get a wrong interrupt and a harmless animation
This may be related to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/SpellHandler.cpp#L547

### Expected behaviour

Correct cancel channel spell

### Steps to reproduce the problem

1.learn 5143
2.cast 5143 attack unit
3.Reuse during boot

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/7b6c1c407e3c3efbd1d61f71eda0dcb5d54a0387

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by offl** [comment]
Why current behavior is wrong?

**Comment by w5860363** [comment]
@offl Continuing to click on spell while the previous spell is still channeling will result in a harmless animation and a sudden interruption

If I remember correctly, this should be the same as a previous question

**Comment by CraftedRO** [comment]
d89dfdbbc1faf5a8c91f9c8ab10c32bb3e503f9f most likely this issue is invalid because this behaviour is blizzlike and can be seen on any channeling spell not only on Arcane Blast.
