### ISSUE TITLE
Core/Quest the_madness_within

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27387]
### Description

quest [7461 ](https://www.wowhead.com/quest=7461/the-madness-within) [prince-tortheldrin](https://www.wowhead.com/npc=11486/prince-tortheldrin ) gossip miss
The task cannot proceed to the next step

### Expected behaviour

attack prince-tortheldrin

### Steps to reproduce the problem

1..quest add 7461 
2. go cr 84376
3. .dam 10000000
4. .go cr 56951

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/36ee9714157e3af4e2b6b3bb9a753e28360ccd58

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25497

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/pull/28581
