### ISSUE TITLE
Client crash when loading new start zone

### ISSUE THREAD

**Issue by krokogames** [TrinityCore/TrinityCore#27388]
### Description

![image](https://user-images.githubusercontent.com/7843239/145690590-1c13685e-cd07-460f-b074-52b7dc31755a.png)

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Prevented sending of [SMSG_UPDATE_TALENT_DATA 0x25CF (9679)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_UPDATE_TALENT_DATA 0x25CF (9679)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Prevented sending of [SMSG_UPDATE_TALENT_DATA 0x25CF (9679)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_UPDATE_TALENT_DATA 0x25CF (9679)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_SET_PROFICIENCY 0x2725 (10021)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_CRITERIA_UPDATE 0x26D3 (9939)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C22 (11298)] to non existent socket 1 to [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B8 (14008)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F0 (14064)] from [Player: Account: 1]

### Operating system

windows 11 x64

### Custom changes

None

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/145690797-446d8f01-40a6-4412-bfa9-6187a956396d.png)

delete your custom stuff out of your hotfixes.

**Comment by Shauren** [comment]
Another one... read the error message. Delete custom stuff.

**Comment by krokogames** [comment]
i have clean client, clean serverfiles and clean db
