### ISSUE TITLE
Runing latest master version throw an error:  undefined symbol: _Z23AddSC_isle_of_queldanasv

### ISSUE THREAD

**Issue by MaciekMr** [TrinityCore/TrinityCore#27389]
### Description

Hi,

after checkout latest version from git, using following cmake command:
cmake ../ -DCMAKE_INSTALL_PREFIX=/work/servers/trinity -DTOOLS=1 -DWITH_WARNINGS=1 -DOPENSSL_LIBRARIES=/usr/local/lib64 -DOPENSSL_INCLUDE_DIR=/usr/local/include -DSCRIPTS=dynamic -DS
ERVERS=1 -DCONF_DIR=/work/servers/trinity/conf -DCMAKE_C_FLAGS="-msse3 -O3 " -DCMAKE_CXX_FLAGS="-std=c++17 -O0 " -DBOOST_ROOT=/work/boost/ -DBoost_INCLUDE_DIR=/work/boost/include -DBoost
_LIBRARY_DIR=/work/boost/lib -DOPENSSL_CRYPTO_LIBRARIES=/usr/local/lib64/libcrypto.so -DOPENSSL_SSL_LIBRARIES=/usr/local/lib64/libssl.so

build has finished sucessfully. 
When running worldserver:
 Scriptname: `spell_gen_trigger_exclude_caster_aura_spell` spell (Id: 200153) does not exist.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
SystemMgr: DB table script_waypoint has waypoint for creature entry 17238, but creature does not have ScriptName defined and then useless.
./worldserver: symbol lookup error: /tmp/tc_script_cache_mster_224F194B0DE72940CDA0B69EFD45124ED05261A6/libscripts_easternkingdoms.4.so: undefined symbol: _Z23AddSC_isle_of_queldanasv
Halting process...

best regards

### Expected behaviour

The function shall be exported

### Steps to reproduce the problem

1. git pull latest version 
2. build executions
3. run

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 1c0010975681 2021-12-12 02:20:42 +0100 (mster branch) (Unix, RelWithDebInfo,

### Operating system

OpenSuse x64

### Custom changes

none

**Comment by Shauren** [comment]
Clear build dir and rerun cmake

**Comment by MaciekMr** [comment]
Yes, I found it. after removing build dir and rerun cmake issue fixed. Thanks

**Comment by MaciekMr** [comment]
clean build folder and rerun cmake
