### ISSUE TITLE
i cant open the trinity core for bnetserver

### ISSUE THREAD

**Issue by darksidegirl55** [TrinityCore/TrinityCore#27385]
### Description

hi i have been haveing trouble with this trinity core (bnetserver) it doesnt open its like something keeps perventing it from opening was wondering who eles was haveing this problem and if i can fix and how. also some one told me i neede a wallet to make it work they never specified what wallet and or what the use of the wallet was for. pleas help ..... this is also for wow 8.0.1 if that helps any 

### Expected behaviour

the file should open activating the core of the game and then i can move to the next step 

### Steps to reproduce the problem

n/a

### Branch

3.3.5

### TC rev. hash/commit

n/a

### Operating system

windows 10 x64

### Custom changes

none

**Comment by Aokromes** [comment]
3.3.5a doesn't ships bnetserver.
