### ISSUE TITLE
Core/PetAi You will not be able to cast spells while in control

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27396]
### Description

Including but not limited to spell  
example [34630](https://www.wowhead.com/spell=34630/scrap-reaver-x6000)

When you use aura to control a temporary pet, the player will be charmed
You cannot cast any spells

It's not the quest itself I know this quest can't be completed

### Expected behaviour

Players can cast spells like hunters when controlling temporary pets

### Steps to reproduce the problem

1.go cr 70975
2.use item
3.cast spell

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/9aa22ee89ff654288eb6b0077d60ffc85a4361ff

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by offl** [comment]
Can't reproduce, + #12407

**Comment by w5860363** [comment]
@offl It's not about the mission itself. I know the mission can't be completed.
 
When you use an item to control any NPC, you cannot release any spell yourself.

**Comment by w5860363** [comment]
@offl The same problem occurs with almost all items
.setskill 202 450 450
.additem 10726
.cooldown
.use item to player
You will lose the ability to release spells yourself

**Comment by offl** [comment]
I opened new issue
