### ISSUE TITLE
Maraudon portal not clickable

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#27419]
### Description

Maraudon portal not clickable. In 2014, it seems to have been repaired, but now it does not work again.
https://github.com/TrinityCore/TrinityCore/issues/10131
https://github.com/TrinityCore/TrinityCore/issues/10131#issuecomment-995190847

Fix from azerothcore:
https://github.com/azerothcore/azerothcore-wotlk/pull/3088

### SQL fix

```sql
--
UPDATE `gameobject_template_addon` SET `faction` = 0 WHERE `entry` = 178404;
```

### Branch

3.3.5

### TC rev. hash/commit

8c80f28

**Comment by offl** [comment]
That object should take summoner's faction

**Comment by Aokromes** [comment]
but on wotlk it must be perm spawned, maybe proper faction is 35.

**Comment by kvolk2git** [comment]
I can't argue with that, I just moved the solution here from Azeroth. But the portal does not work, I tried the Azeroth fix - it helped. In patch 3.0.8, the portal became available to everyone.
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids
