### ISSUE TITLE
DB/Quest : The Fargodeep Mine

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#27424]
### Description

1. Task can be accepted  ==> .quest add 62
2. Examine the Fargodeep mine
3. Note that when you examine the area, the task icon will change to completed, but you will not see information about the successful review on the screen (short sentence)
4. when you come to pass the completed task to Marshal Dughan you can't pass it - the question mark icon is still gray instead of yellow
Link info : [Fargodeep Mine](https://www.wowhead.com/quest=62/the-fargodeep-mine)

Video : [LINK](https://youtu.be/YONToLAQSSg)

### Expected behaviour

The quest should be able to be submitted upon completion.

### Steps to reproduce the problem

1. take on the task .quest add 62
2. Take a tour of Fargodeep Mine
3. Submit the task

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 920d9ac496a5 2021-12-18 15:17:56 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.73.0
Using MySQL version: 5.7.36
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19044
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 1451755434 bytes
vmaps directory located in ./vmaps. Total size: 3361827341 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 915.21111

### Operating system

Win 10 21H2

### Custom changes

none

**Comment by TQPS** [comment]
Confirmed. Just ran through myself. No message on screen. Quest updated silently.

**Comment by shamage** [comment]
work in TrinityCore rev. 8bb7d90f2166
