### ISSUE TITLE
Wrong Renames - Hint to devs

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#27441]
### Description

Just a hint not an issue. THXKKBB ;)

![img](https://i.imgur.com/v2SB6Mz.png)

### Expected behaviour

-

### Steps to reproduce the problem

-

### Branch

3.3.5

### TC rev. hash/commit

-

### Operating system

-

### Custom changes

-

**Comment by iCry1337** [comment]
From https://github.com/TrinityCore/TrinityCore
   41c8c4ba74..2760c56c11  3.3.5      -> origin/3.3.5
   16bbc015e7..7c97fa4449  master     -> origin/master
 * [new tag]               TDB335.21121 -> TDB335.21121
Updating 41c8c4ba74..2760c56c11

**Comment by Aokromes** [comment]
git cosmetic bug.

https://i.imgur.com/oX5hX57.png

**Comment by iCry1337** [comment]
ok
