### ISSUE TITLE
dark portal not active

### ISSUE THREAD

**Issue by tach-tm** [TrinityCore/TrinityCore#27449]
### Description

the dark portal is not active! Can't get to Outland!

### Expected behaviour

Must move to the outland!

### Steps to reproduce the problem

Will try to cross the dark portal! The dark portal is located on the side of Azeroth, in the central part of the Blasted Lands in the south of the Eastern Kingdoms mainland.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. fe489e2be131 2021-12-21 01:20:51 +0100 (master branch)

### Operating system

Windows  11

### Custom changes

only changes occurred in the worldserver.conf file (damage, hp)

**Comment by MaxtorCoder** [comment]
The outland portal is not used anymore if I recall correctly

**Comment by tach-tm** [comment]
but how to get to the outland?

**Comment by Spoony36** [comment]
.tele

**Comment by tach-tm** [comment]
is it possible to somehow activate this portal? Or install such a portal next to this portal or elsewhere !?
