### ISSUE TITLE
Quests cannot be completed if item lost and replaced.

### ISSUE THREAD

**Issue by TheSnowcraft** [TrinityCore/TrinityCore#27462]
### Description

You should be able to hand in a quest with an item requirement while the number of that item in your inventory matches the required amount. This does not happen under the circumstances that the number of that item in your inventory has at any point decreased while on the quest. (For example, vendoring or deleting excess items before handing in), even if the correct number of items remains in your inventory.

### Expected behaviour

You should be able to hand in a quest with an item requirement while the number of that item in your inventory matches the required amount.

### Steps to reproduce the problem

Start any quest that requires you hand in multiple of any item (e.g quest 2974: A Grim Discovery).
Using GM commands, give yourself the required number of the required item to complete the quest.
Delete one of the item from your inventory.
Give yourself a new copy of the item from your inventory.
Attempt to hand the quest in.

### Branch

3.3.5

### TC rev. hash/commit

Unknown Revision

### Operating system

Windows 10

### Custom changes

None

**Comment by offl** [comment]
Duplicate

**Comment by TheSnowcraft** [comment]
Duplicate of which issue?

**Comment by offl** [comment]
Hmmm... #25603
I forgot it was fixed and closed

What is your rev hash? I can't reproduce this issue with 621f3f50c2fa2ce098ff13ad12a0bbc772300e2f using your steps to reproduce

**Comment by TheSnowcraft** [comment]
I, unfortunately, do not know my rev hash. My server says it is unknown. However, if it's been fixed and closed, that does tell me all I really need to do is compile a new server version.
