### ISSUE TITLE
DB/Spawns : Stormwind - Wizard's Sanctum ( gameobject + creature )

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#27464]
### Description

Spawns : gameobject & creature 

- Stormwind : Mage Quarter portals
 ( sniff data )
- Pandaria : Jade Forest - Paw´don village
( sniff data )

- Some minor data is missing, which I hope will be able to be supplemented / corrected later, but I consider this a good basis for implementation.

### SQL fix

EDIT :    [Link : to SQL fix ](https://gist.github.com/shamage/331a42b475bf7cae1dc9179a31b67b12)

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 4519c32e0775+ 2021-12-24 20:11:59 +0100 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by mdX7** [comment]
First of all I'd suggest enabling database in WPP, so we actually get UPDATE statements for stuff which exists. E.g. all of the creatures are already existing in database.
Talking of enabling stuff, enabling DBC is also recommended (and also required for some stuff, e.g. for `spell_target_position`).

Secondly I'd suggest enabling `SkipRowsWithFallbackValues` in WPP, with that you get rid of such rows:
```sql
(@CGUID+2, 0, 0, 0, 1, 0, 0, 0, 0, ''), -- 54896
```
Which is basicly data we do not need because this are the default values used by core if no row is found in database.

Another tip: this is quite long database stuff, you better make a gist of this @ http://gist.github.com and just post the link of it in the sql data field :)

About phases I assume you just forced phase 0?

**Comment by shamage** [comment]
@mdX7 : 
I understand the settings of the WPP database, I also set it, but there are items that I don't quite understand (it would be very long to break it down here) and therefore it happens that certain settings may not be correct. I assume that your experience with the correct setting of the filtering parameters and value output of the configuration file` WowPacketParser.dll.config` is ideal. Therefore, I want to ask you for help in the way of providing your settings of this configuration file (except for WPP settings - I will set this according to my DB data) so that I can properly understand and learn as efficiently as possible these procedures have set up for this job.
There are still a lot of things that I don't understand, and thanks to your explanation, I can move forward and correct my mistakes. Therefore, you and everyone who will direct me in this way and help me on a good journey THANK YOU!

**Comment by shamage** [comment]
@mdX7 :
For example, I don't know if it's good to have` key = "OutputFlag" value = "1" `or leave it at` key = "OutputFlag" value = "15"` ...
SQL Output data: for `add key = value = "True" `as well as `HotfixElement FileHash = "true"` for all values .
Since I have only very short-term experience with this, I would rather say that it is difficult for me to orientate myself in it.

**Comment by shamage** [comment]
> 
> About phases I assume you just forced phase 0?

I probably shouldn't have done that !?

**Comment by shamage** [comment]
After my minor adjustment, I have the following output values after pairing:

```
DBC folder "I:\PacketParser\dbc\enUS" found
Hotfix cache I:\PacketParser\cache\DBCache.bin cannot be loaded, ignoring!
File name                           LoadTime             Record count
---------------------------------------------------------------------
Phase                             00:00:00.2344078             15630
Faction                           00:00:00.2344595             725
Map                               00:00:00.2398820             1101
PhaseXPhaseGroup                  00:00:00.0129273             2094
MapDifficulty                     00:00:00.0120887             1410
CreatureDifficulty                00:00:00.2606884             17080
BroadcastText                     00:00:00.2607066             5925
FactionTemplate                   00:00:00.0277767             1635
CreatureFamily                    00:00:00.0083998             82
Criteria                          00:00:00.3810591             38074
Difficulty                        00:00:00.0139387             42
Achievement                       00:00:00.3234642             7507
Creature                          00:00:00.3203621             16362
AreaTable                         00:00:00.6218142             8068
CriteriaTree                      00:00:00.7451204             73409
CreatureDisplayInfo               00:00:01.1144953             86847
Item                              00:00:01.5379601             157227
ItemSparse                        00:00:01.4867801             127971
SpellEffect                       00:00:01.9917182             404182
SpellName                         00:00:00.5350854             268387
DBC loaded in 00:00:02.849.
Loading DB...
Connecting to MySQL server: Server=localhost;Port=3306;Username=root;Database=wpp;CharSet=utf8;ConnectionTimeout=5;
SQL loaded in 00:00:16.380.
Finished loading DB in 00:00:17.238.


Loading module WowPacketParserModule.V8_0_1_27101.dll (fallback)
Loading module WowPacketParserModule.V7_0_3_22248.dll (fallback)
Loading module WowPacketParserModule.V6_0_2_19033.dll (fallback)
Loading module WowPacketParserModule.V9_0_1_36216.dll
[1/1 TEST 1.pkt]: Parsing 41.1MB of packets. Detected version V9_1_5_41488
Processing... 100% complete
[1/1 TEST 1.pkt]: Saved file to 'I:\Sniffer aktual\dumps\TEST 1_parsed.txt'
[1/1 TEST 1.pkt]: Parsed 281264 (98.751%) packets successfully, 7 (0.002%) with errors, skipped 1 (0.000%) and without structure 3550 (1.246%)  (total: 284822) in 00:00:17.263
1/74 - Write AreaTriggerTemplateData
2/74 - Write AreaTriggerCreatePropertiesData
3/74 - Write AreaTriggerCreatePropertiesOrbitData
4/74 - Write AreaTriggerCreatePropertiesPolygonVertexData
5/74 - Write AreaTriggerCreatePropertiesSplinePointData
6/74 - Write ConversationActorsData
7/74 - Write ConversationActorTemplatesData
8/74 - Write ConversationLineTemplatesData
9/74 - Write ConversationTemplateData
10/74 - Write GameObjectTemplateAddon
11/74 - Write Hotfixes
12/74 - Write HotfixData
13/74 - Write HotfixBlob
14/74 - Write BroadcastText
15/74 - Write BroadcastTextLocales
16/74 - Write HotfixOptionalData
17/74 - Write LocalesCreature
18/74 - Write LocalesQuest
19/74 - Write LocalesQuestOfferReward
20/74 - Write LocalesQuestObjectives
21/74 - Write LocalesQuestGreeting
22/74 - Write LocalesQuestRequestItems
23/74 - Write LocalesPageText
24/74 - Write PlayerChoiceLocale
25/74 - Write PlayerChoiceResponseLocale
26/74 - Write StartInformation
27/74 - Write ObjectNames
28/74 - Write SniffData
29/74 - Write WeatherUpdates
30/74 - Write SceneTemplates
31/74 - Write QuestOfferReward
32/74 - Write QuestPOI
33/74 - Write QuestGreeting
34/74 - Write QuestDetails
35/74 - Write QuestRequestItems
36/74 - Write Creature
37/74 - Write GameObject
38/74 - Write SpellTargetPosition
39/74 - Write CreatureTemplateAddon
40/74 - Write CreatureTemplateScalingData
41/74 - Write ModelData
42/74 - Write NpcTrainer
43/74 - Write Trainer
44/74 - Write TrainerSpell
45/74 - Write CreatureTrainer
46/74 - Write NpcVendor
47/74 - Write CreatureEquip
48/74 - Write PointsOfInterest
49/74 - Write Gossip
50/74 - Write CreatureTemplateNonWDB
Entry: 67025 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 67024 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 67026 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 65983 NpcFlag: Gossip, Trainer
Entry: 136052 NpcFlag: Gossip, QuestGiver, Trainer, ProfessionTrainer
Entry: 136041 NpcFlag: Gossip, QuestGiver, Trainer, ProfessionTrainer, Vendor
Entry: 9584 NpcFlag: Trainer, ProfessionTrainer
Entry: 47579 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 28742 NpcFlag: Gossip, QuestGiver, Trainer, ProfessionTrainer, Vendor, FoodVendor
Entry: 28702 NpcFlag: Trainer, ProfessionTrainer
Entry: 28693 NpcFlag: Trainer, ProfessionTrainer
Entry: 28705 NpcFlag: Gossip, QuestGiver, Trainer, ProfessionTrainer
Entry: 85920 NpcFlag: Trainer, ProfessionTrainer
Entry: 85927 NpcFlag: Trainer, ProfessionTrainer
Entry: 85911 NpcFlag: Trainer, ProfessionTrainer
Entry: 85910 NpcFlag: Trainer, ProfessionTrainer
Entry: 85918 NpcFlag: Trainer, ProfessionTrainer
Entry: 85919 NpcFlag: Trainer
Entry: 85917 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 85923 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 1346 NpcFlag: Gossip, Trainer, ProfessionTrainer
Entry: 5566 NpcFlag: Gossip, QuestGiver, Trainer, ProfessionTrainer
51/74 - Write CreatureText
52/74 - Write VehicleAccessory
53/74 - Write NpcSpellClick
54/74 - Write NpcSpellClickMop
55/74 - Write QuestTemplate
56/74 - Write QuestObjective
57/74 - Write QuestVisualEffect
58/74 - Write QuestRewardDisplaySpell
59/74 - Write CreatureTemplate
60/74 - Write CreatureTemplateModel
61/74 - Write CreatureTemplateQuestItem
62/74 - Write GameObjectTemplate
63/74 - Write GameObjectTemplateQuestItem
64/74 - Write ItemTemplate
65/74 - Write PlayerChoice
66/74 - Write PlayerChoiceResponse
67/74 - Write PlayerChoiceResponseReward
68/74 - Write PlayerChoiceResponseRewardCurrency
69/74 - Write PlayerChoiceResponseRewardFaction
70/74 - Write PlayerChoiceResponseRewardItem
71/74 - Write PageText
72/74 - Write NpcText
73/74 - Write ScenarioPOI
74/74 - Write ScenarioPOIPoint
[1/1 TEST 1.pkt]: Dumping sql: Saved file to '2021_12_26_14_38_56_TEST 1.pkt.sql'
Finished SQL file in 00:00:21.426.
Processing 1 sniffs took 00:00:39.244.


FactionFlag has undefined flags: Unk80
QuestFlagsEx has undefined flags: Unk2000000, Unk4000000
QuestFlagsEx2 has undefined flags: Unk20
ChannelFlag has undefined flags: Unk100
Press any key to continue.
```

**Comment by Spoony36** [comment]
In the WPP config there is an option to enable update instead of insert and delete. not home at the moment to include a screenshot

**Comment by shamage** [comment]
@Spoony36 : 

Look my config settings :  [klikk this link](https://gist.github.com/shamage/e13966cb8ef50f12aa55cfc34726270d)

**Comment by Spoony36** [comment]
Option:      ForceInsertQueries
               Description: Won't generate UPDATE queries, but DELETE and INSERT queries.
               Default:     "true"
        -->
        <add key="ForceInsertQueries" value="true"/>

set this to False, you are telling it to use INSERT AND DELETE queries with how you have it

**Comment by shamage** [comment]
Perfect, thank you :)

**Comment by shamage** [comment]
There's one more thing I don't know:

```
 <!--
               Option:      HotfixCachePath
               Description: Set HotfixCache Path
               Default:     "cache\DBCache.bin" (No prompt)
          -->
        <add key="HotfixCachePath" value="cache\DBCache.bin"/>
```

I have it set to this value, but even though I have the file in the folder - it still ignores it.
Is it necessary to enter the exact path to the file here? (otherwise I tried it anyway) it ignored it anyway)

```
DBC folder "I:\PacketParser\dbc\enUS" found
Hotfix cache I:\PacketParser\cache\DBCache.bin cannot be loaded, ignoring!
```

**Comment by mdX7** [comment]
You mustn't set all possible options in the config. I'm also not using all of them. My mostly used config is [here](https://gist.github.com/mdX7/4db681d300cb145e365e98105a0227fc) if you click on `Revisions` you can see the difference to default config - it's not that much different.
So you can leave `OutputFlag` value at 15, it's only relevant for the `.txt` output anyway. Helps a lot when you want to figure out invalid structures etc, not db related.

For hotfixes I'd recommend to not touch it. funjoker is taking care of hotfixes and he uses some custom stuff in wpp for better output :)

About that phasing thing: You can force phase 0 sure. A lot NPCs are actually in phases however - just wanted to know if you figured out if all of them are <really> in phase 0 on retail (may take a while to figure that stuff out, its a long process) :)

If you'd reparse the sniff with the mentioned suggestions make sure that you did NOT apply the previous changes to your database yet. WPP compared the sniff data with the database and if you already have the data in the db it does not generate the related output. So I always suggest to use a clean TDB with applied updates for parsing.
When you've done that I'll check it out ingame and give further instructions :)

**Comment by shamage** [comment]
@mdX7 : 

Your settings are very good. I applied them and the output of the values is completely different from what I had previously set. I got a huge amount of data, which makes me very happy. If I could adjust everything (I mean UNKNOWN values) then it would cover a large area of Jade Forest and other areas that I explored at the portals from the Stormwind - Mage Quarter exit.
Please I need advice:
For example, I have ==>
```
 INSERT INTO `creature_model_info` (` DisplayID`, `BoundingRadius`,` CombatReach`, `DisplayID_Other_Gender`,` VerifiedBuild`) VALUES
(3445, 0.305999994277954101, 1.5, UNKNOWN, 41488),
```
How to find this information correctly without making a mistake?
Based on the value `DisplayID = 3445`, I find different results such as:  [this](https://gist.github.com/shamage/9f6c4cf5e581e85ef99832835bc2ad87)

However, I have no idea which is the correct value or data for `DisplayID_Other_Gender` can you please advise me ?

I have a lot of values for `creature_model_info`, which would be a great pity not to write just because the values` DisplayID_Other_Gender` are missing.


thank you for any advice I can make learning :)

**Comment by Spoony36** [comment]
Not sure if this is advised and you may want to wait for an official response from Mdx7 or someone who has more knowledge but you could ctrl F and replace all unknowns with 0 but not sure if we really should be doing that. you could also submit with a note saying UNKNOWNS need manual adjustment but probably best to wait for an official response from someone with more knowledge than me

**Comment by shamage** [comment]
Ok, so here's the second dilemma : 

```
`gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `VerifiedBuild`) VALUES 

(19682, 0, 1, 'I would like to buy from you.', UNKNOWN, 41488), -- OptionBroadcastTextID: 2583 - 6399 - 7142 - 9992 - 14967
(23077, 4, 0, 'Guild Master & Vendor', UNKNOWN, 41488), -- OptionBroadcastTextID: 2870 - 3428 - 4890 - 5086 - 5332 - 5910 - 6909 - 6993 - 15222 - 32189 - 45380
```
How do I find out which value is correct and can I replace it with UNKNOWN?

**Comment by shamage** [comment]
Is there an IRC or chat channel used for easier and faster communication - or is this communication via GitHub the best?

**Comment by mdX7** [comment]
For `DisplayID_Other_Gender` you may use 0.
For gossip options pick any id within the comment of the same line. Im mostly picking the first one.

We got an IRC yes. #trinity on Rizon or Discord. Instructions to join are on http://trinitycore.atlassian.net or in README.md in this repo iirc.

**Comment by shamage** [comment]
SQL Fix - finish : DB/Spawn all creature & gameobject in Wizard's Sanctum  ==> https://gist.github.com/shamage/331a42b475bf7cae1dc9179a31b67b12

**Comment by shamage** [comment]
List of things still to be done :
1.  NPC - Maginor Dumas - After invoking gossip, the text is presented in a language other than English
2. Jennea Cannon - has the wrong text when you start a conversation
3. Stormwind City Guard , who is hidden on the stairs behind the Summoned Guardian lacks a spawn script every 5 minutes / random walk about 3 minutes / despawn
4. Elsharin - she has to show the spell and then her apprentices have to repeat it (script missing)

**Comment by shamage** [comment]
> SET @NPC: =  9541002 ; 

So is it better if the values correspond to the actual NPC value designation?
If Summoned Guardian Entry = 149121 (actual value / NPC designation)
so SET @NPC: = 149121;
also for `waypoint_data` and also for` waypoints`?

I am not proficient in this issue, but please teach me if I have just thought wrong.

> Better to use event type 11
> Or event type 1 with timers if creature periodically recasts channeled spell (Blizz love to recast channeled spells every x seconds)

I do not fully understand what you are saying, I am not yet proficient in this issue.

**Comment by shamage** [comment]
@offl : Please give a specific example to help me better understand. well thank you.

**Comment by BAndysc** [comment]
> > Better to use event type 11
> > Or event type 1 with timers if creature periodically recasts channeled spell (Blizz love to recast channeled spells every x seconds)
> 
> I do not fully understand what you are saying, I am not yet proficient in this issue.

Event Type 11 is `On respawn` (SMART_EVENT_RESPAWN), event type 1 is `Every X seconds (out of combat)` (SMART_EVENT_UPDATE_OOC), to use instead of event "when has aura"

But I am not sure what you meant to do by "when have aura 174827 -> Self: cast spell 174827"

**Comment by offl** [comment]
>> Better to use event type 11
>> Or event type 1 with timers if creature periodically recasts channeled spell (Blizz love to recast channeled spells every x seconds)
>
>I do not fully understand what you are saying, I am not yet proficient in this issue.

In that script SMART_EVENT_RESPAWN (11) is a better chose because you want to simply cast spell when creature spawns
SMART_EVENT_HAS_AURA (23) is used when aura is applied on creature or removed from creature (or when creature has no aura)

In other words both events do same thing currently but better to use SMART_EVENT_RESPAWN (11)

***

>So is it better if the values correspond to the actual NPC value designation?
If Summoned Guardian Entry = 149121 (actual value / NPC designation)
so SET @NPC: = 149121;
also for `waypoint_data` and also for` waypoints`?

In case of `waypoint_data` everything is fine, `path_id` is just GUID  * 10 (like you did)
But for `waypoints` `entry` is entry of creature * 100
`waypoints` are not loaded without SAI script (there's no script in your SQL file) and that entry 9541002 doesn't look like guid or entry of creature Summoned Guardian

**Comment by shamage** [comment]
@offl  : Did you mean such an adjustment of values?
It is interesting that the visual result is the same with this adjustment and the previous one.

(@ENTRY, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 11, 174827, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'When creature has aura 0 (check once) - Self: Cast spell 174827 on Self')

**Comment by offl** [comment]
Yes

**Comment by shamage** [comment]
> In case of waypoint_data everything is fine, path_id is just GUID * 10 (like you did)
> But for waypoints entry is entry of creature * 100
> waypoints are not loaded without SAI script (there's no script in your SQL file) and that entry 9541002 doesn't look like guid or entry of creature Summoned Guardian

-------------------------------------------------------------------------------------------

So I'm not sure what value I should enter in the waipoint "entry" table in the future to do it right !?

------------------------------------------------------------------------------------------


If I understand correctly:
1. if it is enough for me if the NPC passes the marked points and performs a "pause" on some of them, it is enough for me if I enter values into the waipoint_data table and it is not necessary to enter additionally into the "waipoint" table
2. waipoint table is also intended for additional tasks such as "emote" or similar things, so I enter data into:
- waipoint_data
- waipoint
- I create smart_script for the necessary actions for the NPC to perform at specific points

Did I get that right?

**Comment by shamage** [comment]
> Event Type 11 is On respawn (SMART_EVENT_RESPAWN), event type 1 is Every X seconds (out of combat) (SMART_EVENT_UPDATE_OOC), to use instead of event "when has aura"

@BAndysc :  If I leave `event_type = 0` and not `= 1` will I do something wrong?

**Comment by offl** [comment]
event_type 0 is IN_COMBAT, creature will execute event only in combat

>If I understand correctly:
>1. if it is enough for me if the NPC passes the marked points and performs a "pause" on some of them, it is enough for me if I enter values into the waipoint_data table and it is not necessary to enter additionally into the "waipoint" table

Yeah

>2. waipoint table is also intended for additional tasks such as "emote" or similar things, so I enter data into:
>- waipoint_data
>- waipoint
>- I create smart_script for the necessary actions for the NPC to perform at specific points

Yeah but you need only `waypoints` or only `waypoint_data`
It depends on situation but you definitely don't need both tables at once
