### ISSUE TITLE
Question - Needed Content?

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#27501]
### Description

As i am have been setup a seperate account i am playing on, i am asking now what content / stuff is atm looked to bring that stuff in project here?

### Expected behaviour

-

### Steps to reproduce the problem

- [ ] Dungeons?
- [ ] Battleground?
- [ ] Arena?
- [ ] open World PVP (Tol'Barad, Wintergrasp)?
- [ ] Classes?
- [ ] Classic Content?

So, i will sniff something i can. ATM uploaded sniffs from 50 - 60 Storyline complete and send to @mdX7 in private. 

Remember; I will not help by sniffing some trash like battlepay shit. Or shop related shit. This is a free community project and we don't like to make money with this project here!

Feedback is welcome. Will also cool if that can be open for a while to check what is needed etc.

### Branch

master

### TC rev. hash/commit

-

### Operating system

Windows

### Custom changes

-

**Comment by Aokromes** [comment]
already 2 tickets opened for this.

**Comment by iCry1337** [comment]
Link me pls?
