### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by madmax765** [TrinityCore/TrinityCore#27517]
### Description

can not compile TrinityCore 

https://prnt.sc/25sx0w1

### Expected behaviour

to compile without  errors 

### Steps to reproduce the problem

did fresh pull
CMake
compile

### Branch

master

### TC rev. hash/commit

87a85dd9d27f5bc123e0e1d1ed818d1cdefe0068

### Operating system

windows 10

### Custom changes

none

**Comment by Aokromes** [comment]
update mysql
