### ISSUE TITLE
Core/Quest - incorrect answer when sharing a quest to a group.

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#27527]
### Description

If you are trying to share a quest in a group and a player who is being offered a quest has already completed this quest and passed as a result, you will receive a message that the player already has this task instead of a message that the task has already been completed.

### Expected behaviour

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Handlers/QuestHandler.cpp

This code snippet does not work as intended

        if (!receiver->SatisfyQuestStatus(quest, false))
        {
            sender->SendPushToPartyResponse(receiver, QUEST_PARTY_MSG_HAVE_QUEST);
            continue;
        }

        if (receiver->GetQuestStatus(questId) == QUEST_STATUS_COMPLETE)
        {
            sender->SendPushToPartyResponse(receiver, QUEST_PARTY_MSG_FINISH_QUEST);
            continue;
        }

### Steps to reproduce the problem

1. create 2 character
2. take the some quest 
3. share this quest and look answer
4. on first character complete and pass the quest
5. on second character again share quest and look answer

### Branch

3.3.5

### TC rev. hash/commit

e470a23a2f09

### Operating system

any

### Custom changes

none

**Comment by kvolk2git** [comment]
I started to deal with the code and came to the conclusion that the Player::SatisfyQuestStatus is not working properly.
In the file https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Quests/QuestDef.h possible quest statuses are described:

enum QuestStatus : uint8
{
    QUEST_STATUS_NONE           = 0,
    QUEST_STATUS_COMPLETE       = 1,
    //QUEST_STATUS_UNAVAILABLE    = 2,
    QUEST_STATUS_INCOMPLETE     = 3,
    //QUEST_STATUS_AVAILABLE      = 4,
    QUEST_STATUS_FAILED         = 5,
    QUEST_STATUS_REWARDED       = 6,        // Not used in DB
    MAX_QUEST_STATUS
};

In the file https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp the code snippet will return false:
bool Player::SatisfyQuestStatus(Quest const* qInfo, bool msg) const
{
    if (GetQuestStatus(qInfo->GetQuestId()) == QUEST_STATUS_REWARDED)
    {
        if (msg)
        {
            SendCanTakeQuestResponse(INVALIDREASON_QUEST_ALREADY_DONE);
            TC_LOG_DEBUG("misc", "Player::SatisfyQuestStatus: Sent QUEST_STATUS_REWARDED (QuestID: %u) because player '%s' (%s) quest status is already REWARDED.",
                qInfo->GetQuestId(), GetName().c_str(), GetGUID().ToString().c_str());
        }
        return false;
    }

    if (GetQuestStatus(qInfo->GetQuestId()) != QUEST_STATUS_NONE)
    {
        if (msg)
        {
            SendCanTakeQuestResponse(INVALIDREASON_QUEST_ALREADY_ON);
            TC_LOG_DEBUG("misc", "Player::SatisfyQuestStatus: Sent INVALIDREASON_QUEST_ALREADY_ON (QuestID: %u) because player '%s' (%s) quest status is not NONE.",
                qInfo->GetQuestId(), GetName().c_str(), GetGUID().ToString().c_str());
        }
        return false;
    }
    return true;
}

Therefore, this function cannot determine whether this quest has been completed, or is in progress, or has already been completed.

*
QUEST_STATUS_COMPLETE - the quest is completed, but not passed.
QUEST_STATUS_INCOMPLETE - the quest is in progress, but not completed.
QUEST_STATUS_REWARDED - the quest has already been completed and passed.

**Comment by kvolk2git** [comment]
@offl 
Hi, it may be possible to somehow speed up the decision on this fix, it is very inconvenient to play in a group together by completing quests without a proper quest sharing system.

**Comment by offl** [comment]
You mean #27529 or https://github.com/TrinityCore/TrinityCore/issues/27527#issuecomment-1018263180? It's not really up to me

**Comment by kvolk2git** [comment]
> You mean #27529 or [#27527 (comment)](https://github.com/TrinityCore/TrinityCore/issues/27527#issuecomment-1018263180)? It's not really up to me

I'm talking about a PR #27529. I saw you as a participant in the discussion of this problem by the poet and turned to you.

**Comment by Shauren** [comment]
c65ccefe16bf462b082fd7a6fce9f87e03a32cb0
