### ISSUE TITLE
Areatrigger Template - Default Value "IsServerSide"

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#27520]
### Description

```log
/* SQL Error (1364): Field 'IsServerSide' doesn't have a default value */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 of 21 queries: 0.000 sec. */
```
If you try to insert some data from sniffs you get an error that says, IsServerSide has no default value. Here we set it as 0 and insert it from sniff with some values. Most values had 0 i have seen.

### SQL fix

```sql
ALTER TABLE `areatrigger_template`
	CHANGE COLUMN `IsServerSide` `IsServerSide` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `Id`;
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 87a85dd9d27f 2022-01-02 21:29:31 +0000

**Comment by mdX7** [comment]
areatriggers from sniff will always be IsServerside=0 because serverside ones have to be created manually and arent sniffable at all. Will set default value in wpp

**Comment by iCry1337** [comment]
Yep thank you, i modified the query in my other issue to set it to 0 if someone not try to use this query here instead before ;D

**Comment by mdX7** [comment]
https://github.com/TrinityCore/WowPacketParser/commit/45e09da583a98e26be270c2e18680476e4a3b0d6
