### ISSUE TITLE
[Bug]A Taste of Flame

### ISSUE THREAD

**Issue by Crysicle** [TrinityCore/TrinityCore#2752]
Bugs:

1. "A Taste of Flame[4023]" shouldn't be given after completing "Trinkets...".

2. By spamming "I present you with proof of my deeds, Cyrus" gossip option, you can summon an infinite amount of "Frenzied Black Drakes". There should probably be a cooldown for it or a check if another "Frenzied Black Drakes" is spawned.

3. This is only speculative, but the current "I present you with proof of my deeds, Cyrus" gossip option should only be offered for quest [4022] while the player holds "Black Dragonflight Molt" in his inventory. It shouldn't summon a drake, instead trigger the "Proof presented" objective which at the moment auto-completes when "Black Dragonflight Molt" is looted.
 
It's plausable that there is another gossip option for summoning the drake which is offered only if the player doesn't have "Black Dragonflight Molt" in his inventory.
 
Quote from a leveling guide:
"After you accept the quest, click on him again and choose the dialogue "I present you with proof..." You must have the Black Dragonflight Molt in your inventory to complete this step. Click on him again, and this time click the yellow question mark to complete the quest."

Links:
Leveling guide - http://wow.allakhazam.com/wiki/Ravennus'_Horde_Guide_Book_14,_55-56
A Taste of Flame - http://www.wowhead.com/quest=4022
A Taste of Flame - http://www.wowhead.com/quest=4023
Trinkets... - http://www.wowhead.com/quest=3481
Black Dragonflight Molt - http://www.wowhead.com/item=10575
Frenzied Black Drake - http://www.wowhead.com/npc=9461

Core revision: 0f0cea1
Database version: TDB 335.53
Addons: Anticheat1

**Comment by Killyana** [comment]
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=40060 AND `ConditionTypeOrReference`=29;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15,40060,0,0,0,29,0,9461,100,0,1,0,0,'','Gor Grimgut cannot be a target for Exhaustion.'),
(15,40060,0,0,1,29,0,9461,100,0,1,0,0,'','Gor Grimgut cannot be a target for Exhaustion.'),
(15,40060,0,0,2,29,0,9461,100,0,1,0,0,'','Gor Grimgut cannot be a target for Exhaustion.');

**Comment by Exodius** [comment]
I believe that comments here are wrong.

**Comment by Killyana** [comment]
No it's correct but I forget to change the comments :(

**Comment by Exodius** [comment]
That's what I said. :D

**Comment by Killyana** [comment]
Ah yes, I read it "commit".
