### ISSUE TITLE
Random Server Crash / Freeze

### ISSUE THREAD

**Issue by iCry1337** [TrinityCore/TrinityCore#27531]
### Description

Crashlog : https://gist.github.com/iCry1337/8a294442bc782e2cb3059a7fcfe993c5

### Expected behaviour

-

### Steps to reproduce the problem

Stay afk on some place in server?

### Branch

master

### TC rev. hash/commit

Revision: TrinityCore rev. 87a85dd9d27f

### Operating system

Windows Server 2016

### Custom changes

- None

**Comment by Shauren** [comment]
This was fixed with this cherry-pick 98272944eef1d710665223df4e16978876e8f9f3, just update
