### ISSUE TITLE
Core: Player can't cast spells while charming

### ISSUE THREAD

**Issue by offl** [TrinityCore/TrinityCore#27563]
### Description

Player can't cast spells while charming

### Expected behaviour

Player should be able to cast spells while charming

### Steps to reproduce the problem

.q a 12690
.npc add temp 28843
use provided item on npc from range
try to cast spells on self or any other target

### Branch

3.3.5

### TC rev. hash/commit

77098375396a3b067cf06174bd464f65d7e0cd50

### Operating system

Win 8.1

### Custom changes

none

**Comment by w5860363** [comment]
The new test is not limited to creature and item
1.setskill 202 450 450
2.additem 10726
3.cooldown
4.If control fails unaura 67809
5.use item to player
6.Release any self spells such as healing effects or buffs

**Comment by w5860363** [comment]
Professional Spells
1.Build a Warlock
2.level up 30
3.learn my spell
4.additem 6265 
5.npc add temp 6165
6.cast spell 1098
7..Release any self spells such as healing effects or buffs

**Comment by jackpoz** [comment]
Is this something that started happening lately or is it an old bug ?

**Comment by w5860363** [comment]
@jackpoz It happened only recently, I am using the old version to try to solve the problem of AOE, the old version did not find this situation

**Comment by w5860363** [comment]
Warlock Spells
SpellMgr::GetSpellForDifficultyFromSpell: Spell id for instance mode is 11726 (original 11726)
Spell::prepare: spell id 11726 source 0 caster 0 customCastFlags 0 mask 2
Spell 11726, added an additional 58.000000 threat for harming 1 target(s)
Aura: 11726 Effect: 0 put to unit visible auras slot: 0
AuraApplication::_HandleEffect: 6, apply: 1: amount: 74
AuraApplication::_HandleEffect: 138, apply: 1: amount: 4294967266
AuraApplication::_HandleEffect: 65, apply: 1: amount: 4294967276

No spells are tracked during the 5 minutes SPELL is in effect

**Comment by jackpoz** [comment]
could you test a few different versions and check which one has the issue and which one doesn't until we find when the issue was added ?

**Comment by w5860363** [comment]
@jackpoz Okay, I'll be rolling back the version and database to check for any problems caused by that commit.

**Comment by jackpoz** [comment]
I'd suggest to try on a brand new db so it's easy to switch versions

**Comment by jackpoz** [comment]
I don't understand what's supposed to happen here different from what happens:

https://user-images.githubusercontent.com/1153754/148640547-68d342ee-fbf4-40a7-9af8-bc993ee1b2a7.mp4

**Comment by w5860363** [comment]
@jackpoz When controlling a creature or a player, the spells in the pet bar are normal
But the player's own spells are not responding to the server
I use tracking and try to use my own spells during the control time, there are no packets

**Comment by jackpoz** [comment]
ah ok, that I didn't test

**Comment by w5860363** [comment]
Tracking the new version During the period when the spell cannot be cast, the transport system sends packets normally, indicating that the server is not in a false death state.
event is updating the database normally means the database threads are not hanging
Other players in the same group are fine, which means that the spell handler did not fail at that time

Backwards version being tested against commits

**Comment by w5860363** [comment]
@jackpoz @offl It has been determined as this submission https://github.com/TrinityCore/TrinityCore/commit/2d114ea560cd8716af2b0d12990fc3480ecaf2b7

The test method is
git reset -- hard edcaac6c959e944dc6d6dc224666b832521412b4 work
git reset --hard 2d114ea560cd8716af2b0d12990fc3480ecaf2b7 not work

Testing with mysql8.0. 21 bosst1.7.2

**Comment by offl** [comment]
@chaodhib could you please check this?

**Comment by w5860363** [comment]
@offl Request to reopen the problem. Now the pet action bar is invalid after using item control NPC

**Comment by Shauren** [comment]
Make a NEW issue, do not post in old ones
