### ISSUE TITLE
Battered Hilt task series BUG

### ISSUE THREAD

**Issue by saliven1970** [TrinityCore/TrinityCore#27570]
### Description

When this task series is carried out to the Sun Well, NPC can't be found when going to the Sun Well, and the whole island of Quel 'Danas has not entered a special state, and entering the Sun Well still needs the RAID mode.

### Expected behaviour

When the player owns this task and carries the task props, it should be a special state to enter Querdanas Island.

### Steps to reproduce the problem

Broken hilt task series, when you go to the well of the sun, take the task items to the well of the sun for purification.

### Branch

3.3.5

### TC rev. hash/commit

335.21121
81da3d9

### Operating system

CentOS-8.6 Linux

### Custom changes

NO

**Comment by Aokromes** [comment]
duplicate.
