### ISSUE TITLE
OSX Cmake error

### ISSUE THREAD

**Issue by Saxy** [TrinityCore/TrinityCore#27574]
### Description

OSX Cmake Error 

CMake Error at /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.21/Modules/CheckIncludeFile.cmake:57 (configure_file):
  configure_file attempted to configure a file:
  /Users/mhagen/Development/gitlab.saxy/wow/core/CMakeFiles/CMakeTmp/CheckIncludeFile.c
  into a source directory.
Call Stack (most recent call first):
  /Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.21/Modules/FindThreads.cmake:146 (CHECK_INCLUDE_FILE)
  dep/threads/CMakeLists.txt:11 (find_package)

### Expected behaviour

successfully build

### Steps to reproduce the problem

1. clone repo 
2. install dependencies (follow steps from tc wiki)
3. run cmake

### Branch

3.3.5

### TC rev. hash/commit

latest

### Operating system

macOS Monterey 12.0.1 (21A559)

### Custom changes

no changes

**Comment by Saxy** [comment]
only some Clion problem => now everything works

**Comment by funjoker** [comment]
Did it solve by itself or did you do something?
Would be nice to get that information for other people :)
