### ISSUE TITLE
Hearthstone locations of fresh characters are invalid

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27588]
### Description

when click on HearthStone or use unstuck it teleports me to nowhere. 
[](https://gyazo.com/5e1d414b8feb62cf858dbc83f46fdeb7)

### Expected behaviour

Player should teleport to home

### Steps to reproduce the problem

https://gyazo.com/5e1d414b8feb62cf858dbc83f46fdeb7

### Branch

master

### TC rev. hash/commit

no crash log

### Operating system

win

### Custom changes

no

**Comment by iCeROCKZZ** [comment]
thank you for quick anwser. but even if i choose classic zone and use hearthstone 
![image](https://user-images.githubusercontent.com/87293722/148811345-ac54824b-f91b-47c6-a4b6-3dc355ceadaa.png)

**Comment by mdX7** [comment]
confirmed on a94fbb77fc77cdc9f5183533f1569a413c908b76
