### ISSUE TITLE
A Feast of Souls

### ISSUE THREAD

**Issue by kotishe** [TrinityCore/TrinityCore#27580]
### Description

Quest A Feast of Souls need 1000 Souls fed to Shadow's Edge instead 50.

https://www.wowhead.com/quest=24547/a-feast-of-souls

### SQL fix

```sql
UPDATE `world`.`quest_template` SET `RequiredNpcOrGoCount1`='50' WHERE  `ID`=24547;
```

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 021c366a73ee+

**Comment by offl** [comment]
Patch 4.0.3a (2010-11-23): Now requires 50 souls instead of 1000.

**Comment by kotishe** [comment]
> Patch 4.0.3a (2010-11-23): Now requires 50 souls instead of 1000.

Okay is wrong description?

![image](https://user-images.githubusercontent.com/29113/148698402-e80aa364-04ad-4c4b-b78e-7fd2d7c9036f.png)
