### ISSUE TITLE
Hearthing to Winterspring puts you in incorrect location

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#27586]
### Description

When you hearth to Everlook in Winterspring, you are placed sideways in the doorway to the Inn.

<details>

![image](https://user-images.githubusercontent.com/66294837/148709210-ad58d4b3-535c-4e34-8fd1-d6a654e3cd29.png)

</details>

### Expected behaviour

You are supposed to spawn next to the Innkeeper

<details>

![image](https://user-images.githubusercontent.com/66294837/148709361-24f8f119-5a63-485a-ba71-44a28934c7d2.png)

</details>

### Steps to reproduce the problem

1. Go to Everlook in Winterspring and set the Inn to your "home"
2. Use Hearthstone (or equivalent)
3. You will be placed in the doorway of the Inn

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 19e99db 2021-12-27 13:33:37 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (authserver)

### Operating system

Windows 7 x64

### Custom changes

Trinity Bots

**Comment by Shauren** [comment]
Hearthstone location is bound the the position where your character was standing when setting the location. This is not a bug
