### ISSUE TITLE
random crash, cant find the cause.

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27598]
### Description

i used LFG to do dungeons with a group of friends, but i am not sure if its that .. 
it seems to be very random.. also worldserver sometimes freezes and give crashes with no logs.

### Expected behaviour

should not crash.

### Steps to reproduce the problem

I cant really reproduce this becouse it appears to be random 

### Branch

master

### TC rev. hash/commit

Revision: TrinityCore rev. 831e433a265b 2022-01-11 07:28:56 +0100 (main branch) (Win64, RelWithDebInfo, Static)
Date 11:1:2022. Time 15:18 
//=====================================================
*** Hardware ***
Processor: AMD Ryzen 7 3700X 8-Core Processor             
Number Of Processors: 16
Physical Memory: 33479408 KB (Available: 22571232 KB)
Commit Charge Limit: 49068228 KB

*** Operation System ***
Windows Server 2016 Standard (Version 10.0, Build 17763)

//=====================================================
Exception code: C0000420 An assertion failure has occurred.

Assertion message: 
D:\sources\Hellgarve_clean_source\TC_clean\src\server\game\Entities\Object\Object.h:567 in WorldObject::GetMap ASSERTION FAILED:
  m_currMap
Creature-0-1-530-0-16345-0000000090 Entry 16345

Fault address:  00007FF6A4D90CC7 01:00000000000AFCC7 D:\TC_Clean\worldserver.exe

Registers:
RAX:00000028B67FE710
RBX:0000021082ABE6E0
RCX:0000000000000002
RDX:00007FF9B31953C5
RSI:0000021081487340
RDI:00000028B67FEFC0
R8: 0000021081487340
R9: 0000000000000001
R10:000000000000000A
R11:0000021178A79C00
R12:0000021081487340
R13:0000000000000000
R14:000000000000000B
R15:0000000000000001
CS:RIP:0033:00007FF9B2AC9319
SS:RSP:002B:00000000B67FEDC0  RBP:B67FEF31
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00000206

Call stack:
Address   Frame     Function      SourceFile
00007FF9B2AC9319  00000028B67FEE90  RaiseException+69
00007FF6A6088D49  00000028B67FEF80  Trinity::Assert+129  D:\sources\TC_clean_source\TC_clean\src\common\Debugging\Errors.cpp line 77
00007FF6A4D90CC7  00000028B67FEFE0  WorldObject::GetMap+47  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Object\Object.h line 567
00007FF6A56E3FC8  00000028B67FF110  Unit::SetMinion+998  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Unit\Unit.cpp line 5930
00007FF6A5B8C664  00000028B67FF140  Minion::RemoveFromWorld+24  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Creature\TemporarySummon.cpp line 347
00007FF6A56C59E1  00000028B67FF1A0  Unit::CleanupBeforeRemoveFromMap+31  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Unit\Unit.cpp line 9321
00007FF6A56C5A85  00000028B67FF1D0  Unit::CleanupsBeforeDelete+15  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Unit\Unit.cpp line 9339
00007FF6A570DDBE  00000028B67FF230  Map::AddObjectToRemoveList+3E  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\Map.cpp line 3671
00007FF6A56A3576  00000028B67FF2F0  WorldObject::AddObjectToRemoveList+186  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Object\Object.cpp line 1738
00007FF6A5B8C801  00000028B67FF350  TempSummon::UnSummon+F1  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Creature\TemporarySummon.cpp line 282
00007FF6A576A004  00000028B67FF3F0  Creature::RemoveCorpse+264  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Creature\Creature.cpp line 472
00007FF6A576DE1C  00000028B67FF550  Creature::Update+6FC  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Creature\Creature.cpp line 789
00007FF6A5B8C8BE  00000028B67FF5F0  TempSummon::Update+2E  D:\sources\TC_clean_source\TC_clean\src\server\game\Entities\Creature\TemporarySummon.cpp line 68
00007FF6A5BCEC88  00000028B67FF620  Trinity::ObjectUpdater::Visit<Creature>+58  D:\sources\TC_clean_source\TC_clean\src\server\game\Grids\Notifiers\GridNotifiers.cpp line 267
00007FF6A5701975  00000028B67FF650  VisitorHelper<Trinity::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeList<AreaTrigger,TypeList<SceneObject,TypeList<Conversation,TypeNull> > > > > >+15  D:\sources\TC_clean_source\TC_clean\src\server\game\Grids\Dynamic\TypeContainerVisitor.h line 51
00007FF6A57013BB  00000028B67FF6D0  Map::Visit<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeList<AreaTrigger,TypeList<SceneObject,TypeList<Conversation,TypeNull> > > > > > > > >+9B  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\Map.h line 1004
00007FF6A5721367  00000028B67FF750  Map::VisitNearbyCellsOf+257  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\Map.cpp line 817
00007FF6A57204B1  00000028B67FF910  Map::Update+1D1  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\Map.cpp line 886
00007FF6A5D1CFB8  00000028B67FF940  MapUpdater::WorkerThread+D8  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\MapUpdater.cpp line 112
00007FF6A5D1CE0F  00000028B67FF970  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+F  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\thread line 55
00007FF9B31A268A  00000028B67FF9A0  _o_exp+5A
00007FF9B5DB7974  00000028B67FF9D0  BaseThreadInitThunk+14
00007FF9B60AA2F1  00000028B67FFA50  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF9B60F3304  00000028B66FEB60  NtWaitForAlertByThreadId+14
00007FF9B60A84F9  00000028B66FEBD0  RtlSleepConditionVariableSRW+109
00007FF9B2AAF40D  00000028B66FEC10  SleepConditionVariableSRW+2D
00007FF993272549  00000028B66FEC40  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FF9932727DA  00000028B66FEC70  _Cnd_wait+3A
00007FF6A5D1D3EF  00000028B66FECB0  MapUpdater::wait+4F  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\MapUpdater.cpp line 72
00007FF6A5607F2E  00000028B66FECE0  MapManager::Update+BE  D:\sources\TC_clean_source\TC_clean\src\server\game\Maps\MapManager.cpp line 254
00007FF6A55F28B7  00000028B66FEF90  World::Update+677  D:\sources\TC_clean_source\TC_clean\src\server\game\World\World.cpp line 2671
00007FF6A4D716C2  00000028B66FEFE0  WorldUpdateLoop+112  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 502
00007FF6A4D7F508  00000028B66FF780  main+2408  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 396
00007FF6A6239ABC  00000028B66FF7C0  __scrt_common_main_seh+10C  D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FF9B5DB7974  00000028B66FF7F0  BaseThreadInitThunk+14
00007FF9B60AA2F1  00000028B66FF870  RtlUserThreadStart+21

### Operating system

win

### Custom changes

no

**Comment by w5860363** [comment]
No changes can be made now because there are many problems with the LFG system

https://github.com/TrinityCore/TrinityCore/issues/14331

**Comment by Faq** [comment]
@w5860363 that is 335 issue.

**Comment by w5860363** [comment]
@Faq Not only 335 was in effect for the 6x branch

But then the 6x branch was upgraded
