### ISSUE TITLE
Core/Instance High Warlord Naj'entus

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27596]
### Description

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp#L108
and https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp#L163

2 seconds to cast a spell

### Expected behaviour

Achieves a normal 20-second spell cycle

[References ](https://wowwiki-archive.fandom.com/wiki/High_Warlord_Naj%27entus)

### Steps to reproduce the problem

1.two player .gm on
2.two player .go cr 40527
3.cheat god
4.gm off
Observe the spell cycle
 

### Branch

3.3.5

### TC rev. hash/commit

None

### Operating system

Windows 10 x64,

### Custom changes

https://github.com/TrinityCore/TrinityCore/commit/5ba93a95de911277908596d805e7fa7f38a18c3a

**Comment by offl** [comment]
NEEDLE_SPINE every 2 seconds
IMPALING_SPINE every 20 seconds
