### ISSUE TITLE
Quest Crash 

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27599]
### Description

When accept the quest and use the mount server crashes

### Expected behaviour

server should not crash

### Steps to reproduce the problem

take this quest and when mount the dragon to execute the objectives, server crashes https://www.wowhead.com/quest=12779/an-end-to-all-things
No crash log, its empty.

### Branch

master

### TC rev. hash/commit

empty

### Operating system

win

### Custom changes

no

**Comment by w5860363** [comment]
Unable to reproduce. This task under the main branch is consistent with 335. Please check the relevant parts of 335

Clean up the source code and re clone the main branch
