### ISSUE TITLE
GetRoll Crash

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27600]
### Description

When loot, it sometimes crashes 

### Expected behaviour

not crash

### Steps to reproduce the problem

loot a few bosses, i think its when bag is full but it happens random .. 

### Branch

master

### TC rev. hash/commit

Revision: TrinityCore rev. d8ed682a951a+ 2022-01-12 06:32:18 +0100 (main branch) (Win64, RelWithDebInfo, Static)
Date 12:1:2022. Time 10:26 
//=====================================================
*** Hardware ***
Processor: AMD Ryzen 7 3700X 8-Core Processor             
Number Of Processors: 16
Physical Memory: 33479408 KB (Available: 20474512 KB)
Commit Charge Limit: 49068228 KB

*** Operation System ***
Windows Server 2016 Standard (Version 10.0, Build 17763)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF70C0449B7 01:0000000000DA39B7 D:\TC_Clean\worldserver.exe

Registers:
RAX:00000208AF149670
RBX:0000000000000000
RCX:00000208AF149680
RDX:00000015A54FED90
RSI:00000208EB9978D0
RDI:0000000000000000
R8: 00000208E45866D0
R9: 00000015A54FED90
R10:00000015A54FED60
R11:00007FF70B2A0000
R12:00007FF70CF6C8A8
R13:00000015A54FEDD0
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:00007FF70C0449B7
SS:RSP:002B:00000000A54FED28  RBP:06080F80
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010287

Call stack:
Address   Frame     Function      SourceFile
00007FF70C0449B7  00000015A54FED20  Group::GetRoll+37  D:\sources\TC_clean_source\TC_clean\src\server\game\Groups\Group.cpp line 2744
00007FF70C042977  00000015A54FED80  Group::CountRollVote+27  D:\sources\TC_clean_source\TC_clean\src\server\game\Groups\Group.cpp line 1258
00007FF70C3E2F24  00000015A54FEDE0  WorldSession::HandleLootRoll+54  D:\sources\TC_clean_source\TC_clean\src\server\game\Handlers\GroupHandler.cpp line 416
00007FF70C23B2B4  00000015A54FEE90  PacketHandler<WorldPackets::Loot::LootRoll,&WorldSession::HandleLootRoll>::Call+64  D:\sources\TC_clean_source\TC_clean\src\server\game\Server\Protocol\Opcodes.cpp line 36
00007FF70BEC0629  00000015A54FF040  WorldSession::Update+3F9  D:\sources\TC_clean_source\TC_clean\src\server\game\Server\WorldSession.cpp line 427
00007FF70BBB373E  00000015A54FF120  World::UpdateSessions+23E  D:\sources\TC_clean_source\TC_clean\src\server\game\World\World.cpp line 3307
00007FF70BBB2827  00000015A54FF3D0  World::Update+4C7  D:\sources\TC_clean_source\TC_clean\src\server\game\World\World.cpp line 2630
00007FF70B3316C2  00000015A54FF420  WorldUpdateLoop+112  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 502
00007FF70B33F508  00000015A54FFBC0  main+2408  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 396
00007FF70C7FA37C  00000015A54FFC00  __scrt_common_main_seh+10C  D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FF9B5DB7974  00000015A54FFC30  BaseThreadInitThunk+14
00007FF9B60AA2F1  00000015A54FFCB0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FF9B60F1764  00000015A54FCDE0  ZwGetContextThread+14
00007FF9B2B0E4EB  00000015A54FCE10  GetThreadContext+B
00007FF70B349ECD  00000015A54FD340  WheatyExceptionReport::printTracesForAllThreads+BD  D:\sources\TC_clean_source\TC_clean\src\common\Debugging\WheatyExceptionReport.cpp line 489
00007FF70B347F3F  00000015A54FD9D0  WheatyExceptionReport::GenerateExceptionReport+30F  D:\sources\TC_clean_source\TC_clean\src\common\Debugging\WheatyExceptionReport.cpp line 595
00007FF70B348FD4  00000015A54FDCD0  WheatyExceptionReport::WheatyUnhandledExceptionFilter+324  D:\sources\TC_clean_source\TC_clean\src\common\Debugging\WheatyExceptionReport.cpp line 200
00007FF9B2B17AFC  00000015A54FDDE0  UnhandledExceptionFilter+1BC
00007FF9B60F8440  00000015A54FDE20  memset+1C40
00007FF9B60DFDD6  00000015A54FDE90  __C_specific_handler+96
00007FF9B60F4A2F  00000015A54FDEC0  __chkstk+11F
00007FF9B6054CEF  00000015A54FE5F0  RtlWalkFrameChain+14BF
00007FF9B60F379E  00000015A54FED18  KiUserExceptionDispatcher+2E
00007FF70C0449B7  00000015A54FED20  Group::GetRoll+37  D:\sources\TC_clean_source\TC_clean\src\server\game\Groups\Group.cpp line 2744
00007FF70C042977  00000015A54FED80  Group::CountRollVote+27  D:\sources\TC_clean_source\TC_clean\src\server\game\Groups\Group.cpp line 1258
00007FF70C3E2F24  00000015A54FEDE0  WorldSession::HandleLootRoll+54  D:\sources\TC_clean_source\TC_clean\src\server\game\Handlers\GroupHandler.cpp line 416
00007FF70C23B2B4  00000015A54FEE90  PacketHandler<WorldPackets::Loot::LootRoll,&WorldSession::HandleLootRoll>::Call+64  D:\sources\TC_clean_source\TC_clean\src\server\game\Server\Protocol\Opcodes.cpp line 36
00007FF70BEC0629  00000015A54FF040  WorldSession::Update+3F9  D:\sources\TC_clean_source\TC_clean\src\server\game\Server\WorldSession.cpp line 427
00007FF70BBB373E  00000015A54FF120  World::UpdateSessions+23E  D:\sources\TC_clean_source\TC_clean\src\server\game\World\World.cpp line 3307
00007FF70BBB2827  00000015A54FF3D0  World::Update+4C7  D:\sources\TC_clean_source\TC_clean\src\server\game\World\World.cpp line 2630
00007FF70B3316C2  00000015A54FF420  WorldUpdateLoop+112  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 502
00007FF70B33F508  00000015A54FFBC0  main+2408  D:\sources\TC_clean_source\TC_clean\src\server\worldserver\Main.cpp line 396
00007FF70C7FA37C  00000015A54FFC00  __scrt_common_main_seh+10C  D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FF9B5DB7974  00000015A54FFC30  BaseThreadInitThunk+14
00007FF9B60AA2F1  00000015A54FFCB0  RtlUserThreadStart+21

### Operating system

win

### Custom changes

no

**Comment by Aokromes** [comment]
void Group::_initRaidSubGroupsCounter()
{
    // Sub group counters initialization
    if (!m_subGroupsCounts)
        m_subGroupsCounts = new uint8[MAX_RAID_SUBGROUPS];

    memset((void*)m_subGroupsCounts, 0, (MAX_RAID_SUBGROUPS)*sizeof(uint8));

    for (member_citerator itr = m_memberSlots.begin(); itr != m_memberSlots.end(); ++itr)
        ++m_subGroupsCounts[itr->group];
}

you are not using clean trinitycore, maybe not trinitycore at all.

**Comment by ImmortalusDev** [comment]
it's definitely TC, just older

**Comment by iCeROCKZZ** [comment]
what you mean older? i guess its up to date, sorry i am noob in this.

**Comment by ImmortalusDev** [comment]
> 

upload here Group.cpp file, it's different

**Comment by Shauren** [comment]
Not neccessary

**Comment by iCeROCKZZ** [comment]
I added just a disable becouse of the crashes. but its clean basicly. 
[Group.txt](https://github.com/TrinityCore/TrinityCore/files/7854496/Group.txt)

**Comment by w5860363** [comment]
not confirm. It's Trinity, but Should this be modified?
