### ISSUE TITLE
Use missing broadcast_ Text and local

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27602]
### Description

npc 15608 guid 34023 Localized line text is not used

test .go cr 34023

### SQL fix

```sql
UPDATE `creature_text` SET `BroadcastTextID`=16789 WHERE `entry`=15608 AND `groupid`=1 AND `id`=0;
```

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/747ee281dd2f22b1cc0c44683854c87b2e869d14

**Comment by offl** [comment]
fde8619dacf50159e5b94f2c00d56755b7e6c36a
