### ISSUE TITLE
Fix Flesh Eating Worm

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27610]
### Description

https://github.com/TrinityCore/TrinityCore/issues/25612

### SQL fix

```sql
UPDATE `smart_scripts` SET `event_type`="1" WHERE `entryorguid`=948 AND id = 0;
UPDATE `smart_scripts` SET `event_flags`="1" WHERE `entryorguid`=948 AND id = 0;
UPDATE `smart_scripts` SET `event_flags`="1" WHERE `entryorguid`=948 AND id = 1;
UPDATE `smart_scripts` SET `action_param2`="3" WHERE `entryorguid`=948 AND id =1;
```

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/fde8619dacf50159e5b94f2c00d56755b7e6c36a

**Comment by offl** [comment]
>```sql
>UPDATE `smart_scripts` SET `event_flags`="1" WHERE `entryorguid`=948 AND id = 1;
>```

On Death events cannot be repeated, they don't need SMART_EVENT_FLAG_NOT_REPEATABLE

>```sql
>UPDATE `smart_scripts` SET `action_param2`="3" WHERE `entryorguid`=948 AND id =1;
>

1 here is SMARTCAST_INTERRUPT_PREVIOUS, that's legacy flag and that creature does not cast any spells in combat - there's nothing to interrupt before cast
2 here is SMARTCAST_TRIGGERED (used currently)

I don't see how that can ever fix something, that bug is not related to summoner script

**Comment by w5860363** [comment]
@offl After checking, the old versions TDB and SD2 essentially 2462 do not have any flag changes
Therefore, the problem can only occur on Sai

**Comment by offl** [comment]
Simply restoring old data by comparing old version of DB \ C++ scripts with new won't fix anything in nearly all cases but with huge chance will break something or will throw errors
