### ISSUE TITLE
Vulpera warlock kick from game issue

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#27619]
### Description

Ona fresh core, creating a Vulpera Warlock and then typing .level 50 causes wow to disconnect, apparently happens on gnome to according to Naddely

World server and bnet server do not crash and after relogging in, the character is indeed level 60 it seems. Just not sure why it kicks you from game when typing .level 50

### Expected behaviour

Should not disconnect i believe

### Steps to reproduce the problem

1: Create a Vulpera Warlock
2: Type .level 50
3: Wow disconnects

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 1761f72da7a0

### Operating system

Windows 11

### Custom changes

None

**Comment by Shauren** [comment]
Client crash or just disconnect? That is a huge difference

**Comment by Spoony36** [comment]
yeah it's a disconnect rather than a client crash, Has been confirmed by others too as i thought it might have been a me issue

**Comment by Naddley** [comment]
But its not a 100% disconnect.
Tested with 3 Vulpera Warlocks only one disconnects me after .levelup 50

**Comment by Spoony36** [comment]
> But its not a 100% disconnect.
> Tested with 3 Vulpera Warlocks only one disconnects me after .levelup 50

Ah, I created only 2 characters and both disconnected for me so could be sporadic

**Comment by Shauren** [comment]
AntiDOS causes the kick
