### ISSUE TITLE
Core/Spells: Mage - Arcane Intellect not giving Intellect buff

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#27629]
### Description

Arcane Intellect gets given to mages at level 8.

Upon receiving it, you can cast it - shows animations - but does not give the buff.

### Expected behaviour

The buff provides a 5% boost to Intellect for 1hr.

https://www.wowhead.com/spell=1459/arcane-intellect

### Steps to reproduce the problem

1. Progress a mage to level 8
2. Receive Arcane Intellect
3. Cast it
4. Does not provide the Intel boost

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 77e1304a5aad 2022-01-18 00:27:18 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

None

**Comment by Nyr97** [comment]
Fixed by https://github.com/TrinityCore/TrinityCore/commit/25b84e5e7b215439e3f95a360c36ac430f974a94.

**Comment by TQPS** [comment]
Just saw in game now. Thank you.
