### ISSUE TITLE
DB/Misc: Add OldScarletMonastery game_tele and mark mapID 44 as valid

### ISSUE THREAD

**Issue by anzz1** [TrinityCore/TrinityCore#27626]
### Description

DB/Misc: Add OldScarletMonastery game_tele and mark mapID 44 as valid

Same treatment for OldScarletMonastery as in here for EmeraldDream https://github.com/TrinityCore/TrinityCore/issues/16131

### SQL fix

```sql
-- Add mapID 44 as valid instance
DELETE FROM `instance_template` WHERE `map`=44;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES 
(44,0,'',0);

-- Add teleport location OldScarletMonastery
DELETE FROM `game_tele` WHERE `name`='OldScarletMonastery';
INSERT INTO `game_tele` (`position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES 
(79,-1,18.6778,0,44,'OldScarletMonastery');
```

### Branch

3.3.5

### TC rev. hash/commit

a650bd631a4681d09e3ff66f79b73b99299565f3

**Comment by Jinnaix** [comment]
Looks good to me, thank you.
Works ingame.
Can be noted for merging - @offl
