### ISSUE TITLE
Startup Issues (THE FIRST IMPORTANT FIX)

### ISSUE THREAD

**Issue by vandisx** [TrinityCore/TrinityCore#27624]
### Description

ISSUES ON STARTUP

### Expected behaviour

NONE

### Steps to reproduce the problem

X

### Branch

master

### TC rev. hash/commit

d95a1e7eafd2 2022-01-16

### Operating system

windows

### Custom changes

>> Loaded 0 Random item bonus list definitions. DB table `item_random_bonus_list_template` is empty.
Loading Quests...
>> Loaded 0 quest reward choice items. DB table `quest_reward_choice_items` is empty.
Table `quest_mail_sender` has data for quest 22817 but such quest does not exist
Table `quest_mail_sender` has data for quest 22818 but such quest does not exist
Table `quest_objectives` has data for quest 30238 but such quest does not exist
Loading Game Event Saves Data...
>> Loaded 0 game event saves in game events. DB table `game_event_save` is empty.
Loading Game Event Prerequisite Data...
>> Loaded 0 game event prerequisites in game events. DB table `game_event_prerequisite` is empty.
Loading Game Event Creature Data...
>> Loaded 3183 creatures in game events in 3 ms.
Loading Game Event GO Data...
>> Loaded 23379 gameobjects in game events in 22 ms.
Loading Game Event Model/Equipment Change Data...
>> Loaded 0 model/equipment changes in game events. DB table `game_event_model_equip` is empty.
Loading Game Event Quest Data...
>> Loaded 327 quests additions in game events in 2 ms.
Loading Game Event GO Quest Data...
>> Loaded 189 quests additions in game events in 1 ms.
Loading Game Event Quest Condition Data...
>> Loaded 0 quest event conditions in game events. DB table `game_event_quest_condition` is empty.
Loading Game Event Condition Data...
>> Loaded 0 conditions in game events. DB table `game_event_condition` is empty.
Loading Game Event Condition Save Data...
>> Loaded 0 condition saves in game events. DB table `game_event_condition_save` is empty.
Loading Game Event NPCflag Data...
>> Loaded 0 npcflags in game events. DB table `game_event_npcflag` is empty.
Loading Vehicle Templates...
>> Loaded 0 vehicle template. DB table `vehicle_template` is empty.
Loading Vehicle Template Accessories...
Loading Player Create Custom Spell Data...
>> Loaded 0 player create custom spells. DB table `playercreateinfo_spell_custom` is empty.
Loading Player Create Cast Spell Data...
Loading AreaTrigger Templates...
>> Loaded 0 AreaTrigger templates circular movement infos. DB table `areatrigger_create_properties_orbit` is empty.
>> Loaded 607 spell areatrigger templates in 7 ms.
Loading Player Choices...
>> Loaded 0 player choices. DB table `playerchoice` is empty.
Loading Player Choices Locales...
Loading Black Market Templates...
>> Loaded 0 black market templates. DB table `blackmarket_template` is empty.
Loading Black Market Auctions...
>> Loaded 0 black market auctions. DB table `blackmarket_auctions` is empty.
Loading Guild rewards...
Loading guilds definitions...
>> Loaded 0 guild definitions. DB table `guild` is empty.
Loading ArenaTeams...
>> Loaded 0 arena teams. DB table `arena_team` is empty!
Loading Groups...
>> Loaded 0 group definitions. DB table `groups` is empty!
Loading ReservedNames...
>> Loaded 0 reserved player names. DB table `reserved_name` is empty!
Loading GameObjects for quests...
Loading GM complaints...
>> Loaded 0 GM complaints. DB table `gm_complaint` is empty!
Loading GM suggestions...
>> Loaded 0 GM suggestions. DB table `gm_suggestion` is empty!
Loading garrison info...
Loading Autobroadcasts...
>> Loaded 0 autobroadcasts definitions. DB table `autobroadcast` is empty for this realm!
Loading spell_scripts...
Validating spell scripts...
_SpellScript::ValidateSpellInfo: Spell 103958 does not exist.
Spell `172` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `755` Effect `Index: EFFECT_0 AuraName: 20` of script `spell_warl_health_funnel` did not match dbc effect data - handler bound to hook `OnEffectApply` of AuraScript won't be executed
Spell `755` Effect `Index: EFFECT_0 AuraName: 20` of script `spell_warl_health_funnel` did not match dbc effect data - handler bound to hook `OnEffectRemove` of AuraScript won't be executed
Spell `755` Effect `Index: EFFECT_0 AuraName: 20` of script `spell_warl_health_funnel` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 159669 does not exist.
Spell `1454` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 213363 does not exist.
Spell `2643` did not pass Validate() function of script `spell_hun_multi_shot` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `2823` did not pass Validate() function of script `spell_gen_trigger_exclude_target_aura_spell` - script will be not added to the spell
Spell `5246` Effect `Index: EFFECT_1 Target: 15` of script `spell_warr_intimidating_shout` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `5740` Effect `Index: EFFECT_3 AuraName: 226` of script `spell_warl_rain_of_fire` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 56250 does not exist.
Spell `6358` did not pass Validate() function of script `spell_warl_seduction` - script will be not added to the spell
Spell `12294` Effect `Index: EFFECT_0 Name: 3` of script `spell_warr_mortal_strike` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `13877` Effect `Index: EFFECT_0 AuraName: 110` of script `spell_rog_blade_flurry` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `15286` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_pri_vampiric_embrace` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `15290` Effect `Index: EFFECT_0 Target: 20` of script `spell_pri_vampiric_embrace_target` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 12723 does not exist.
_SpellScript::ValidateSpellInfo: Spell 26654 does not exist.
Spell `18765` did not pass Validate() function of script `spell_warr_sweeping_strikes` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 56249 does not exist.
Spell `19505` did not pass Validate() function of script `spell_warl_devour_magic` - script will be not added to the spell
Spell `21149` Effect `Index: EFFECT_2 Name: 100` of script `spell_item_eggnog` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `21562` Effect `Index: EFFECT_0 Name: 3` of script `spell_pri_power_word_fortitude` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `23881` Effect `Index: EFFECT_3 Name: 3` of script `spell_warr_bloodthirst` did not match dbc effect data - handler bound to hook `OnEffectHit` of SpellScript won't be executed
Spell `28764` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_gen_adaptive_warding` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `29166` Effect `Index: EFFECT_0 AuraName: 24` of script `spell_dru_innervate` did not match dbc effect data - handler bound to hook `DoEffectCalcAmount` of AuraScript won't be executed
Spell `30108` of script `spell_warl_unstable_affliction` does not have apply aura effect - handler bound to hook `AfterDispel` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 86315 does not exist.
Spell `31790` did not pass Validate() function of script `spell_gen_trigger_exclude_target_aura_spell` - script will be not added to the spell
Spell `33763` Effect `Index: EFFECT_1 AuraName: 4` of script `spell_dru_lifebloom` did not match dbc effect data - handler bound to hook `AfterEffectRemove` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 64372 does not exist.
Spell `33763` did not pass Validate() function of script `spell_dru_lifebloom` - script will be not added to the spell
Spell `34477` Effect `Index: EFFECT_1 AuraName: 4` of script `spell_hun_misdirection` did not match dbc effect data - handler bound to hook `AfterEffectRemove` of AuraScript won't be executed
Spell `34477` Effect `Index: EFFECT_1 AuraName: 4` of script `spell_hun_misdirection` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 70276 does not exist.
Spell `34779` did not pass Validate() function of script `spell_freezing_circle` - script will be not added to the spell
Spell `34914` Effect `Index: EFFECT_2 AuraName: 4` of script `spell_pri_vampiric_touch` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 64085 does not exist.
Spell `34914` did not pass Validate() function of script `spell_pri_vampiric_touch` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 12723 does not exist.
_SpellScript::ValidateSpellInfo: Spell 26654 does not exist.
Spell `35429` did not pass Validate() function of script `spell_warr_sweeping_strikes` - script will be not added to the spell
Spell `41054` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_gen_clone_weapon_aura` did not match dbc effect data - handler bound to hook `OnEffectApply` of AuraScript won't be executed
Spell `41054` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_gen_clone_weapon_aura` did not match dbc effect data - handler bound to hook `OnEffectRemove` of AuraScript won't be executed
Spell `41341` Effect `Index: EFFECT_0 AuraName: 69` of script `spell_illidari_council_balance_of_power` did not match dbc effect data - handler bound to hook `OnEffectAbsorb` of AuraScript won't be executed
Spell `44436` Effect `Index: EFFECT_0 Name: 77` of script `spell_hallow_end_tricky_treat` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 42965 does not exist.
Spell `44436` did not pass Validate() function of script `spell_hallow_end_tricky_treat` - script will be not added to the spell
Spell `45204` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 29705 does not exist.
_SpellScript::ValidateSpellInfo: Spell 29727 does not exist.
Spell `45406` did not pass Validate() function of script `spell_midsummer_ribbon_pole_periodic_visual` - script will be not added to the spell
Spell `47496` Effect `Index: EFFECT_0 Name: 2` of script `spell_dk_ghoul_explode` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `47496` Effect `Index: EFFECT_1 Name: 2` of script `spell_dk_ghoul_explode` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `47788` Effect `Index: EFFECT_1 AuraName: 69` of script `spell_pri_guardian_spirit` did not match dbc effect data - handler bound to hook `DoEffectCalcAmount` of AuraScript won't be executed
Spell `47788` Effect `Index: EFFECT_1 AuraName: 69` of script `spell_pri_guardian_spirit` did not match dbc effect data - handler bound to hook `OnEffectAbsorb` of AuraScript won't be executed
Spell `48438` Effect `Index: EFFECT_1 Target: 31` of script `spell_dru_wild_growth` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `48438` did not pass Validate() function of script `spell_dru_wild_growth` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 49331 does not exist.
Spell `49107` did not pass Validate() function of script `spell_vehicle_warhead_fuse` - script will be not added to the spell
Spell `49889` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `49889` Effect `Index: EFFECT_2 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `50218` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `50218` Effect `Index: EFFECT_2 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `50278` Effect `Index: EFFECT_0 AuraName: 23` of script `spell_barreled_control_aura` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
Spell `50286` Effect `Index: EFFECT_0 Target: 15` of script `spell_dru_starfall_dummy` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `50785` Effect `Index: EFFECT_0 Target: 15` of script `spell_varos_energize_core_area_enemy` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `51690` Effect `Index: EFFECT_1 Target: 16` of script `spell_rog_killing_spree` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `51719` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `51719` Effect `Index: EFFECT_2 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `52437` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_warr_sudden_death` did not match dbc effect data - handler bound to hook `AfterEffectApply` of AuraScript won't be executed
Spell `53478` Effect `Index: EFFECT_0 Name: 3` of script `spell_hun_last_stand_pet` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 53479 does not exist.
Spell `53478` did not pass Validate() function of script `spell_hun_last_stand_pet` - script will be not added to the spell
Spell `54069` Effect `Index: EFFECT_0 Target: 7` of script `spell_varos_energize_core_area_entry` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `55233` Effect `Index: EFFECT_1 AuraName: 250` of script `spell_dk_vampiric_blood` did not match dbc effect data - handler bound to hook `DoEffectCalcAmount` of AuraScript won't be executed
Spell `56251` Effect `Index: EFFECT_0 Target: 7` of script `spell_varos_energize_core_area_entry` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `59372` Effect `Index: EFFECT_0 Target: 15` of script `spell_varos_energize_core_area_enemy` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 59933 does not exist.
Spell `59910` did not pass Validate() function of script `spell_novos_summon_minions` - script will be not added to the spell
Spell `59915` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_item_discerning_eye_beast_dummy` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `60864` Effect `Index: EFFECT_0 Name: 2` of script `spell_jaws_of_death_claw_swipe_pct_damage` did not match dbc effect data - handler bound to hook `OnEffectLaunchTarget` of SpellScript won't be executed
Spell `61407` Effect `Index: EFFECT_0 Target: 7` of script `spell_varos_energize_core_area_entry` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `62136` Effect `Index: EFFECT_0 Target: 7` of script `spell_varos_energize_core_area_entry` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `66683` Effect `Index: EFFECT_2 AuraName: 12` of script `spell_icehowl_massive_crash` did not match dbc effect data - handler bound to hook `AfterEffectRemove` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 67016 does not exist.
_SpellScript::ValidateSpellInfo: Spell 67017 does not exist.
_SpellScript::ValidateSpellInfo: Spell 67018 does not exist.
Spell `67019` did not pass Validate() function of script `spell_item_flask_of_the_north` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 56249 does not exist.
Spell `67518` did not pass Validate() function of script `spell_warl_devour_magic` - script will be not added to the spell
Spell `68614` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_apothecary_cologne_spill` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
Spell `68798` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_apothecary_perfume_spill` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
Spell `69893` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_gen_clone_weapon_aura` did not match dbc effect data - handler bound to hook `OnEffectApply` of AuraScript won't be executed
Spell `69893` Effect `Index: EFFECT_0 AuraName: 226` of script `spell_gen_clone_weapon_aura` did not match dbc effect data - handler bound to hook `OnEffectRemove` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `77606` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `85948` Effect `Index: EFFECT_2 Name: 3` of script `spell_dk_festering_strike` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `86121` Effect `Index: EFFECT_0 Name: 2` of script `spell_warl_soul_swap` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 56226 does not exist.
_SpellScript::ValidateSpellInfo: Spell 94229 does not exist.
Spell `86121` did not pass Validate() function of script `spell_warl_soul_swap` - script will be not added to the spell
Spell `86213` Effect `Index: EFFECT_0 Name: 2` of script `spell_warl_soul_swap_exhale` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 92794 does not exist.
Spell `86213` did not pass Validate() function of script `spell_warl_soul_swap_exhale` - script will be not added to the spell
Spell `86949` Effect `Index: EFFECT_0 AuraName: 69` of script `spell_mage_cauterize` did not match dbc effect data - handler bound to hook `OnEffectAbsorb` of AuraScript won't be executed
Spell `99353` did not pass Validate() function of script `spell_baleroc_decimating_strike` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `100780` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `100784` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 86315 does not exist.
Spell `100950` did not pass Validate() function of script `spell_gen_trigger_exclude_target_aura_spell` - script will be not added to the spell
Spell `106935` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 154436 does not exist.
Spell `117952` did not pass Validate() function of script `spell_monk_crackling_jade_lightning` - script will be not added to the spell
Spell `118089` did not pass Validate() function of script `spell_item_water_strider` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `119996` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `121471` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `123456` Effect `Index: EFFECT_0 Target: 18` of script `spell_halion_summon_exit_portals` did not match dbc effect data - handler bound to hook `OnDestinationTargetSelect` of SpellScript won't be executed
Spell `123456` Effect `Index: EFFECT_1 Target: 18` of script `spell_halion_summon_exit_portals` did not match dbc effect data - handler bound to hook `OnDestinationTargetSelect` of SpellScript won't be executed
Spell `126240` Effect `Index: EFFECT_2 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `126661` Effect `Index: EFFECT_0 AuraName: 23` of script `spell_warr_charge_drop_fire_periodic` did not match dbc effect data - handler bound to hook `OnEffectPeriodic` of AuraScript won't be executed
Spell `127271` did not pass Validate() function of script `spell_item_water_strider` - script will be not added to the spell
Spell `127272` did not pass Validate() function of script `spell_item_water_strider` - script will be not added to the spell
Spell `127274` did not pass Validate() function of script `spell_item_water_strider` - script will be not added to the spell
Spell `127278` did not pass Validate() function of script `spell_item_water_strider` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 114168 does not exist.
Spell `131632` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `136757` Effect `Index: EFFECT_1 Name: 77` of script `spell_gen_clone` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 114168 does not exist.
Spell `143395` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `146739` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 115070 does not exist.
Spell `178338` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `178368` Effect `Index: EFFECT_1 Name: 42` of script `spell_warr_heroic_leap_jump` did not match dbc effect data - handler bound to hook `OnEffectHit` of SpellScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 159708 does not exist.
_SpellScript::ValidateSpellInfo: Spell 133278 does not exist.
_SpellScript::ValidateSpellInfo: Spell 157449 does not exist.
Spell `178368` did not pass Validate() function of script `spell_warr_heroic_leap_jump` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 90259 does not exist.
Spell `194834` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 0 does not exist.
Spell `205523` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 159669 does not exist.
Spell `212284` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 74434 does not exist.
Spell `213398` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
_SpellScript::ValidateSpellInfo: Spell 117050 does not exist.
Spell `213831` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `217694` Effect `Index: EFFECT_2 AuraName: 4` of script `spell_mage_living_bomb_periodic` did not match dbc effect data - handler bound to hook `AfterEffectRemove` of AuraScript won't be executed
_SpellScript::ValidateSpellInfo: Spell 90259 does not exist.
Spell `219779` did not pass Validate() function of script `spell_gen_trigger_exclude_caster_aura_spell` - script will be not added to the spell
Spell `235313` Effect `Index: EFFECT_1 AuraName: 42` of script `spell_mage_blazing_barrier` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
>> Loaded 0 character template classes. DB table `character_template_class` is empty.
>> Loaded 0 character templates. DB table `character_template` is empty.
>> Loaded 0 scenario POI definitions. DB table `scenario_poi` is empty.

**Comment by Aokromes** [comment]
duplicate.

**Comment by vandisx** [comment]
where is  the duplicate
