### ISSUE TITLE
HearthStone still have issues

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27623]
### Description

Players are teleported under map

### Expected behaviour

players should not go undermap

### Steps to reproduce the problem

if you have your hearthstone lets say in Stormwind and you are on one of the other Continents and try to hearth Home it will put you where you should be but on the wrong continent

### Branch

master

### TC rev. hash/commit

No logs

### Operating system

win

### Custom changes

no

**Comment by Faq** [comment]
Fill in commit hash and also reproduction steps.

**Comment by mdX7** [comment]
can confirm @ 3346366b0ebc8feb10c6a113d884b095f558998d
