### ISSUE TITLE
Core/Pathfinding: Pathing through terrain in water

### ISSUE THREAD

**Issue by WORISX** [TrinityCore/TrinityCore#27635]
### Description

General issue, if a creature is aggroed from behind some terrain and both points are in water, shortcut is created without checking terrain as if terrain is actual water, without taking care of adt below water, this issue is present globally.

https://user-images.githubusercontent.com/97387012/150019462-59564d39-92ed-4893-b38b-21d1c85ef22a.mp4

### Expected behaviour

If shortcut is used we should check terrain to avoid going into textures when charging, when chasing, follow, etc

### Steps to reproduce the problem

![148831911-ae437faf-6608-4141-88e6-ed3cadaf75c6](https://user-images.githubusercontent.com/97387012/150019643-95f91abd-f379-4fad-b1d8-78fbcc8b3f85.png)

Do steps on video on the provided coords.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/a650bd631a4681d09e3ff66f79b73b99299565f3

### Operating system

Windows 10 x64, Debian 10

### Custom changes

None

**Comment by acidmanifesto** [comment]
You posted the same exact screen shot and video on another core, and your wording is word for word.
https://github.com/azerothcore/azerothcore-wotlk/issues/10119
Can you please verify which core you are using and propper revision being used?

**Comment by sucofog** [comment]
@acidmanifesto I tested the same issue on both cores, i didnt done a video and screenshot again since the issue is the same and its present on both, revision is valid and proper since it can be reproduced on same branches with the same steps.

**Comment by Jinnaix** [comment]
Can not replicate on 335 (tcubunto). Seems to be invalid for Trinitycore.
![WoWScrnShot_011922_104247](https://user-images.githubusercontent.com/37972361/150105313-9c17685c-ee0d-4a99-bb11-fc26a4eab2f3.jpg)
![WoWScrnShot_011922_104250](https://user-images.githubusercontent.com/37972361/150105316-1edafa87-d6a5-455f-ad63-8f2663f5d470.jpg)

**Comment by WORISX** [comment]
> Can not replicate on 335 (tcubunto). Seems to be invalid for Trinitycore. ![WoWScrnShot_011922_104247](https://user-images.githubusercontent.com/37972361/150105313-9c17685c-ee0d-4a99-bb11-fc26a4eab2f3.jpg) ![WoWScrnShot_011922_104250](https://user-images.githubusercontent.com/37972361/150105316-1edafa87-d6a5-455f-ad63-8f2663f5d470.jpg)

True, i recompìled and looks like i can't reproduce anymore, closing it since it's invalid, thanks!

**Comment by jackpoz** [comment]
This was fixed by https://github.com/TrinityCore/TrinityCore/commit/8a779268b601db28005a8348f3c21255718d4526 which contains an optional mmaps_generator run.

**Comment by WORISX** [comment]
> This was fixed by [8a77926](https://github.com/TrinityCore/TrinityCore/commit/8a779268b601db28005a8348f3c21255718d4526) which contains an optional mmaps_generator run.

Let me ask, how do we know if some points between first point id and last point id are actually not water but terrain? Which portion of code is taking care of that?

**Comment by jackpoz** [comment]
You can check how ".mmap path" works and debug it
