### ISSUE TITLE
[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST  YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### ISSUE THREAD

**Issue by doingurmom13** [TrinityCore/TrinityCore#27647]
### Description

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST

YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### Expected behaviour

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST

YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### Steps to reproduce the problem

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST

YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### Branch

master

### TC rev. hash/commit

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST

YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### Operating system

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST  YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

### Custom changes

[1054] UNKNOWN COLUMN "REWARDMONEY" in FIELD LIST

YOUR DATABASE TRUCTURE IS NOT UP TO DATE. PLEASE MAKE SURE YOU'VE EXECUTED YOUR BULL

**Comment by Aokromes** [comment]
you have enabled auto update and you are trying to apply the sql files with sqlyog? of yes, don't leave core to do the job.

**Comment by doingurmom13** [comment]
Dude I literally told you it's a fresh compile from the source why is the auto update not enabled?

 Also I'm literally telling you it isn't enabled and I'd suppress source I'm literally using the database and everything and it shouldn't stall properly and it's not

**Comment by doingurmom13** [comment]
There is nowhere the database that uses trinity_

**Comment by doingurmom13** [comment]
No DB is structured under trinity_world

**Comment by doingurmom13** [comment]
Also you're making up things when you're saying I'm executing from SQO yog I have to do that in order to get it to update because it's failing

**Comment by doingurmom13** [comment]
If it's an auto updater, is she told me how to fix it?

**Comment by doingurmom13** [comment]
If it is an auto updater issue then tell me how to fix it rather than closing the issue. And then just saying something like you enabled this, this and that. No, tell me how to fix it.

**Comment by doingurmom13** [comment]
Yes, since you need literally proof of something, I verbatim Lee said I'm gonna literally. Copy and paste my config to you.

###################################################################################################
# UPDATE SETTINGS
#
#    Updates.EnableDatabases
#        Description: A mask that describes which databases shall be updated.
#
#        Following flags are available
#           DATABASE_LOGIN     = 1, // Auth database
#           DATABASE_CHARACTER = 2, // Character database
#           DATABASE_WORLD     = 4, // World database
#           DATABASE_HOTFIX    = 8, // Hotfixes database
#
#        Default:     15 - (All enabled)
#                     4  - (Enable world only)
#                     0  - (All Disabled)

Updates.EnableDatabases = 15

#
#    Updates.AutoSetup
#        Description: Auto populate empty databases.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.AutoSetup   = 1

#
#    Updates.Redundancy
#        Description: Perform data redundancy checks through hashing
#                     to detect changes on sql updates and reapply it.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.Redundancy  = 1

#
#    Updates.ArchivedRedundancy
#        Description: Check hashes of archived updates (slows down startup).
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Updates.ArchivedRedundancy = 0

#
#    Updates.AllowRehash
#        Description: Inserts the current file hash in the database if it is left empty.
#                     Useful if you want to mark a file as applied but you don't know its hash.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

Updates.AllowRehash = 1

#
#    Updates.CleanDeadRefMaxCount
#        Description: Cleans dead/ orphaned references that occur if an update was removed or renamed and edited in one step.
#                     It only starts the clean up if the count of the missing updates is below or equal the Updates.CleanDeadRefMaxCount value.
#                     This way prevents erasing of the update history due to wrong source directory state (maybe wrong branch or bad revision).
#                     Disable this if you want to know if the database is in a possible "dirty state".
#        Default:     3 - (Enabled)
#                     0 - (Disabled)
#                    -1 - (Enabled - unlimited)

Updates.CleanDeadRefMaxCount = 3

**Comment by doingurmom13** [comment]
This is ********. It worked just fine earlier.

**Comment by doingurmom13** [comment]
about 3 days ago.

**Comment by Aokromes** [comment]
well, your previous ticket contains a fix on a file after the one containing the drop that's why i asked if you are using sqlyog and autoupdate.

**Comment by doingurmom13** [comment]
I had really fixed the issue. It was a bug in your system in the code.

**Comment by doingurmom13** [comment]
But I'm not going to close the issue because it's not fixed yet.

**Comment by doingurmom13** [comment]
ADD COLUMN RewardMoney TO world;

**Comment by doingurmom13** [comment]
Why are you asking me what I'm using? I'm telling you there's an issue with the code BIG ISSUE PREVENTING ME TO RUN AFTER FRESH COMPILE.

**Comment by doingurmom13** [comment]
>> Done!
Database World is empty, auto populating it...
>> File "TDB_full_world_915.22012_2022_01_15.sql" is missing, download it from "https://github.com/TrinityCore/TrinityCore/releases" uncompress it and place the file "TDB_full_world_915.22012_2022_01_15.sql" in the directory "D:/DonRepack".
Could not populate the World database, see log for details.

**Comment by doingurmom13** [comment]
>> Character database is up-to-date! Containing 1 new and 130 archived updates.
Updating World database...
>> Applying update "2022_01_19_10_world_2020_06_29_04_world.sql" 'DBE0486'...
mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1049 (42000) at line 9: Unknown database 'trinity_world'


Applying of file 'D:/cryptocraft/sql/updates/world/master/2022_01_19_10_world_2020_06_29_04_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

**Comment by Aokromes** [comment]
git pull your source i fixed that error 1h ago.

**Comment by doingurmom13** [comment]
I am not using an SQL client. It is running a fresh database install and it is failing due to auto updator. auto updator is broken and not working.

**Comment by doingurmom13** [comment]
I just freshly pulled this source. Literally 5 minutes ago. Not even.

**Comment by doingurmom13** [comment]
What am I doing wrong that Trinity?_world is saying that it can't find the database. Do I need to disable auto updates on a fresh install?

**Comment by doingurmom13** [comment]
There is nothing in the database fresh. Fresh install.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/253293fb22ac5ec57fd9c1bf0ee5af11cd8e5f81
there is no trinity_world anymore on that file
