### ISSUE TITLE
over 200 degrees F Catastrophic FAILURE air and heat temperature using tools. For client.

### ISSUE THREAD

**Issue by vandisx** [TrinityCore/TrinityCore#27644]
### Description

https://ibb.co/4N9LbYc

### Expected behaviour

https://ibb.co/4N9LbYc

### Steps to reproduce the problem

https://ibb.co/4N9LbYc

### Branch

master

### TC rev. hash/commit

https://ibb.co/4N9LbYc

### Operating system

https://ibb.co/4N9LbYc

### Custom changes

https://ibb.co/4N9LbYc

**Comment by vandisx** [comment]
over 200 degrees F Catastrophic FAILURE air and heat temperature using tools. For client.

**Comment by Aokromes** [comment]
get better cooling system.

**Comment by doingurmom13** [comment]
Here's a more proof of harassment from this guy who's in charge here

**Comment by doingurmom13** [comment]
I'm actually running on a brand new laptop that has very good cooling for the most part it's also rested up and it's nice but either way I think it's an issue in the programming itself that it's overriding the CPU's temperature

**Comment by Aokromes** [comment]
there is nothing on code overriding cpu temperatures.
laptops are a very bad idea to use to extract client files for master branch who needs a lot of time to extract.
