### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by vandisx** [TrinityCore/TrinityCore#27643]
### Description

fuck you - x

### Expected behaviour

With the full team that you have, this should be a lot more efficient. This is stupid.

### Steps to reproduce the problem

With the full team that you have, this should be a lot more efficient. This is stupid.

### Branch

master

### TC rev. hash/commit

With the full team that you have, this should be a lot more efficient. This is stupid.

### Operating system

With the full team that you have, this should be a lot more efficient. This is stupid.

### Custom changes

With the full team that you have, this should be a lot more efficient. This is stupid.

**Comment by vandisx** [comment]
https://ibb.co/cQM3gXC

**Comment by Aokromes** [comment]
you have been selected for a full refund... oh wait. for a full ban

**Comment by doingurmom13** [comment]
If there was no money involved I don't know what you're talking about right now
