### ISSUE TITLE
[STARTUP ERROR] [FRESH COMPILE FROM SOURCE]

### ISSUE THREAD

**Issue by doingurmom13** [TrinityCore/TrinityCore#27646]
### Description

There is an issue when booting from a fresh compile. Giving me is issue saying that in SQL is not properly fixed. It has the wrong DB name and I had to go through and change the SQL file with Notepad. i would like to know the name of the person who keeps deleting my issues & bugs. If you keep on bullying me I'm going to do something. Anytime that I report an issue, it gets removed immediately. Without anybody even reading the first issue, I've reported he closed it and said it was a duplicate. And which wasn't true at all and failed to provide a link. Whoever is in charge here, and whoever is getting funding or cedre with this project, there is some big changes that need to happen. With that being said, I don't understand how your team is managing and going about things. I apologize. For cursing, but at the end of the day, it is not cool to bully another person. It causes great amount of stress and it puts two people through a lot of work and a lot of emotional things. And to be honest with you, if this is the other issue that gets deleted, I'm gonna take. Another step a bit further Just because you're making me that angry.

### Expected behaviour

You expected behavior is for it to just run through and update in SQL, but there's no reason that I should say Trinity_in front of the world.

### Steps to reproduce the problem

Compile a fresh source.

### Branch

master

### TC rev. hash/commit

Brand new.

### Operating system

Ryzen 9.

### Custom changes

There's no custom changes followed step by step.

This is my last draw.

**Comment by doingurmom13** [comment]
INSERT INTO `world`.

**Comment by doingurmom13** [comment]
-- Tanaris
-- [Q] Rumors for Kravel -- http://wotlk.openwow.com/quest=1117
-- https://www.youtube.com/watch?reload=9&v=9bW2cscKMc8
-- (c) Toxic/ICC
-- Kravel Koalbeard SAI
SET @ID := 4452;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ID;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID AND `source_type`=0 and `id` =3;
INSERT INTO `trinity_world`.`smart_scripts`(`entryorguid`, `id`, `event_type`, `event_chance`, `event_param1`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES
(@ID, 3, 20, 100, 1117, 80, @ID*100+2, 1, 'Kravel Koalbeard - On Quest \'Rumors for Kravel\' Finished - Run Script');

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID*100+2 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID*100+2,9,0,0,0,0,100,0,0,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Remove Npc Flag Questgiver"),
(@ID*100+2,9,1,0,0,0,100,0,1000,1000,0,0,1,6,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 6"),
(@ID*100+2,9,2,0,0,0,100,0,1000,1000,0,0,5,94,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote Dance"),
(@ID*100+2,9,3,0,0,0,100,0,5000,5000,0,0,5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote None"),
(@ID*100+2,9,4,0,0,0,100,0,1000,1000,0,0,1,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 7"),
(@ID*100+2,9,5,0,0,0,100,0,2000,2000,0,0,82,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Add Npc Flag Questgiver");

DELETE FROM `creature_text` WHERE `CreatureID`=@ID AND `GroupID` IN (6,7);
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(@ID,6,0,"%s begins to dance.",16,0,100,0,0,0,1480,0,"Kravel Koalbeard"),
(@ID,7,0,"Hahah! $n, you make quite a partner!",12,0,100,11,0,0,1481,0,"Kravel Koalbeard");

**Comment by doingurmom13** [comment]
CHANGED TO ->

**Comment by doingurmom13** [comment]
-- Tanaris
-- [Q] Rumors for Kravel -- http://wotlk.openwow.com/quest=1117
-- https://www.youtube.com/watch?reload=9&v=9bW2cscKMc8
-- (c) Toxic/ICC
-- Kravel Koalbeard SAI
SET @ID := 4452;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ID;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID AND `source_type`=0 and `id` =3;
INSERT INTO `world`.`smart_scripts`(`entryorguid`, `id`, `event_type`, `event_chance`, `event_param1`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES
(@ID, 3, 20, 100, 1117, 80, @ID*100+2, 1, 'Kravel Koalbeard - On Quest \'Rumors for Kravel\' Finished - Run Script');

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID*100+2 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID*100+2,9,0,0,0,0,100,0,0,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Remove Npc Flag Questgiver"),
(@ID*100+2,9,1,0,0,0,100,0,1000,1000,0,0,1,6,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 6"),
(@ID*100+2,9,2,0,0,0,100,0,1000,1000,0,0,5,94,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote Dance"),
(@ID*100+2,9,3,0,0,0,100,0,5000,5000,0,0,5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote None"),
(@ID*100+2,9,4,0,0,0,100,0,1000,1000,0,0,1,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 7"),
(@ID*100+2,9,5,0,0,0,100,0,2000,2000,0,0,82,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Add Npc Flag Questgiver");

DELETE FROM `creature_text` WHERE `CreatureID`=@ID AND `GroupID` IN (6,7);
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(@ID,6,0,"%s begins to dance.",16,0,100,0,0,0,1480,0,"Kravel Koalbeard"),
(@ID,7,0,"Hahah! $n, you make quite a partner!",12,0,100,11,0,0,1481,0,"Kravel Koalbeard");

**Comment by doingurmom13** [comment]
-- Tanaris
-- [Q] Rumors for Kravel -- http://wotlk.openwow.com/quest=1117
-- https://www.youtube.com/watch?reload=9&v=9bW2cscKMc8
-- (c) Toxic/ICC
-- Kravel Koalbeard SAI
SET @ID := 4452;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ID;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID AND `source_type`=0 and `id` =3;
INSERT INTO `world`.`smart_scripts`(`entryorguid`, `id`, `event_type`, `event_chance`, `event_param1`, `action_type`, `action_param1`, `target_type`, `comment`) VALUES
(@ID, 3, 20, 100, 1117, 80, @ID*100+2, 1, 'Kravel Koalbeard - On Quest \'Rumors for Kravel\' Finished - Run Script');

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ID*100+2 AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID*100+2,9,0,0,0,0,100,0,0,0,0,0,83,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Remove Npc Flag Questgiver"),
(@ID*100+2,9,1,0,0,0,100,0,1000,1000,0,0,1,6,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 6"),
(@ID*100+2,9,2,0,0,0,100,0,1000,1000,0,0,5,94,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote Dance"),
(@ID*100+2,9,3,0,0,0,100,0,5000,5000,0,0,5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Emote None"),
(@ID*100+2,9,4,0,0,0,100,0,1000,1000,0,0,1,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Say Line 7"),
(@ID*100+2,9,5,0,0,0,100,0,2000,2000,0,0,82,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kravel Koalbeard - On Script - Add Npc Flag Questgiver");

DELETE FROM `creature_text` WHERE `CreatureID`=@ID AND `GroupID` IN (6,7);
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(@ID,6,0,"%s begins to dance.",16,0,100,0,0,0,1480,0,"Kravel Koalbeard"),
(@ID,7,0,"Hahah! $n, you make quite a partner!",12,0,100,11,0,0,1481,0,"Kravel Koalbeard");

**Comment by Aokromes** [comment]
if you don't post error we cannot read minds.
also we don't use
INSERT INTO world.
no where.
