### ISSUE TITLE
 ERROR 1049 (42000) at line 9: Unknown database 'trinity_world'   Applying of file 'D:/cryptocraft/sql/updates/world/master/2022_01_19_10_world_2020_06_29_04_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query. Could not update the World database, see log for details.

### ISSUE THREAD

**Issue by doingurmom13** [TrinityCore/TrinityCore#27649]
### Description

ERROR 1049 (42000) at line 9: Unknown database 'trinity_world'

Applying of file 'D:/cryptocraft/sql/updates/world/master/2022_01_19_10_world_2020_06_29_04_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

### Expected behaviour

NO HARRASMENT.

### Steps to reproduce the problem

FRESH COMPILE FROM SOURCE.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 8f4db9aa6919

### Operating system

Windows

### Custom changes

I'm being trolled and harassed.

**Comment by Aokromes** [comment]
i told you latest source doesn't have that  anymore 
https://github.com/TrinityCore/TrinityCore/commit/253293fb22ac5ec57fd9c1bf0ee5af11cd8e5f81

**Comment by doingurmom13** [comment]
You're wrong, I just pulled the source less than five minutes ago. I will repeat it again. And if anything, I can even make a YouTube video to prove it.

**Comment by doingurmom13** [comment]
Also, the issue is also that you are being abusive and harassing these issues.

**Comment by doingurmom13** [comment]
Could you please kindly open this issue back up?

**Comment by doingurmom13** [comment]
"git" pull --progress "origin"
Already up to date.
Done

Press Enter or Esc to close console...

**Comment by doingurmom13** [comment]
Yes, I'm going to literally record it right now.

**Comment by doingurmom13** [comment]
OK, it's pulling it. Fresh from a compile and still giving me an error. What are you disagreeing with me about? That's right, you're harassing me.

**Comment by Aokromes** [comment]
> OK, it's pulling it. Fresh from a compile and still giving me an error. What are you disagreeing with me about? That's right, you're harassing me.

i have show you on clean trinitycore repository that file doesn't contain that anymore.
if you don't believe me check it yourself, the problem is on your side.
https://github.com/TrinityCore/TrinityCore/blob/master/sql/updates/world/master/2022_01_19_10_world_2020_06_29_04_world.sql

**Comment by doingurmom13** [comment]
It's funny because earlier you were disagreeing with me that my edit on the SQL wasn't the error. But it's funny that it was & and it was changed weird. also not true i just pulled again and tried to run nothing.

**Comment by doingurmom13** [comment]
i will try again

**Comment by doingurmom13** [comment]
just built with cmake

**Comment by Aokromes** [comment]
> It's funny because earlier you were disagreeing with me that my edit on the SQL wasn't the error. But it's funny that it was & and it was changed weird. also not true i just pulled again and tried to run nothing.

i was mistaked and i fixed, it now there is no that error unless you are using some 3rd party source.

**Comment by doingurmom13** [comment]
Thanks that's all I needed to hear

**Comment by doingurmom13** [comment]
Perfect

**Comment by doingurmom13** [comment]
May you kindly open the issue backup until I resolve it myself

**Comment by Aokromes** [comment]
> May you kindly open the issue backup until I resolve it myself

no, we don't open already fixed issues.
