### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iCeROCKZZ** [TrinityCore/TrinityCore#27651]
### Description

server crashes

### Expected behaviour

not crash

### Steps to reproduce the problem

xx

### Branch

master

### TC rev. hash/commit

[Crash.txt](https://github.com/TrinityCore/TrinityCore/files/7907617/Crash.txt)

### Operating system

win

### Custom changes

no

**Comment by MaxtorCoder** [comment]
Upload crashlog to gist or pastebin, fill in proper reproduce steps and fill in the correct git hash, this issue is useless.
