### ISSUE TITLE
DB/Loot: remove item Spotted Yellowtail from creature loot

### ISSUE THREAD

**Issue by Alastro-Kraken** [TrinityCore/TrinityCore#27654]
### Description

There isn't any creature that should drop [Spotted Yellowtail](https://tbc.wowhead.com/item=6887/spotted-yellowtail).

### SQL fix

```sql
DELETE FROM `creature_loot_template` WHERE `Item`=6887;
```

### Branch

3.3.5

### TC rev. hash/commit

fd7f48545ce76740065860c0963194c2a9e3e0e2

**Comment by offl** [comment]
Added remaining
