### ISSUE TITLE
DB/Gossip: fix slight typo in unlearn talents gossip option text

### ISSUE THREAD

**Issue by Alastro-Kraken** [TrinityCore/TrinityCore#27660]
### Description

Before Cataclysm, the option text for unlearning talents was "I wish to unlearn my talents." (broadcast text id: 8271). After Cataclysm, it was "I wish to unlearn my Talents." (with a capital T).

Currently the Text field is correct, but the broadcast text id is the Cataclysm one.

### SQL fix

```sql
UPDATE `gossip_menu_option` SET `OptionBroadcastTextID`=8271 WHERE `OptionBroadcastTextID`=62295;
```

### Branch

3.3.5

### TC rev. hash/commit

cd5fdc50efb4eee10d18881f6683d460a45937c9

**Comment by offl** [comment]
It wasn't changed but we need to use low ids if possible

**Comment by Alastro-Kraken** [comment]
Oh right it was the same in Cata too, assumed it wasn't because the broadcast id was around that range. Fix is still valid though.
