### ISSUE TITLE
DB/Quest: fix wrong horde questgivers for "The Hunter's Charm"

### ISSUE THREAD

**Issue by Alastro-Kraken** [TrinityCore/TrinityCore#27661]
### Description

[The Hunter's Charm](https://tbc.wowhead.com/quest=8151/the-hunters-charm) should be started by [Holt Thunderhorn](https://tbc.wowhead.com/npc=3039/holt-thunderhorn) and [Ormak Grimshot](https://tbc.wowhead.com/npc=3352/ormak-grimshot), not by [Kary Thunderhorn](https://tbc.wowhead.com/npc=3038/kary-thunderhorn) and [Xor'juul](https://tbc.wowhead.com/npc=3406/xorjuul).

### SQL fix

```sql
UPDATE `creature_queststarter` SET `id`=3039 WHERE `id`=3038 AND `quest`=8151;
UPDATE `creature_queststarter` SET `id`=3352 WHERE `id`=3406 AND `quest`=8151;

```

### Branch

3.3.5

### TC rev. hash/commit

cd5fdc50efb4eee10d18881f6683d460a45937c9

**Comment by Aokromes** [comment]
you can simply update.

**Comment by Alastro-Kraken** [comment]
Right, that makes more sense. Changed, thanks.
