### ISSUE TITLE
DB/Quest: disable deprecated quest 'The New Horde'

### ISSUE THREAD

**Issue by Alastro-Kraken** [TrinityCore/TrinityCore#27664]
### Description

On [Wowhead](https://tbc.wowhead.com/quest=787/the-new-horde) there are comments from people that never managed to obtain this quest no matter at which level/race they tried. I also tried to grab it on the PTR and failed, as level 1 orc and not orc, and level 70 orc and not orc.

This leads me to believe that this quest was deprecated, considering [Cutting Teeth](https://tbc.wowhead.com/quest=788) (the second quest in the orc/troll area) has id 788 and [Your Place In The World](https://tbc.wowhead.com/quest=4641/your-place-in-the-world) (the first quest in that area) has id 4641, maybe orcs and trolls used to spawn in Orgrimmar in some beta version and that was changed eventually?

Regardless, quest can't be obtained on Classic.

### SQL fix

```sql
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry`=787;
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES
(1, 787, 0, "", "", "Deprecated quest");
```

### Branch

3.3.5

### TC rev. hash/commit

6811fe63bfe34ee628fbd7a56b38d92a8f9940e7

**Comment by offl** [comment]
But you didn't complete Your Place In The World before trying to get The New Horde?

**Comment by offl** [comment]
Well, history looks like nobody really completed that quest https://wowpedia.fandom.com/wiki/The_New_Horde_(quest)?action=history
Kinda empty archived page, no comments and archived first time in december 2010 (cata) https://web.archive.org/web/20101211094804/http://www.wowhead.com/quest=787

Comparing to Cutting Teeth (usually something useful looks like this) https://web.archive.org/web/2010*/http://www.wowhead.com/quest=788

>maybe orcs and trolls used to spawn in Orgrimmar in some beta version and that was changed eventually?

This sounds more realistic https://tbc.wowhead.com/quest=787/the-new-horde#comments:id=2941265
