### ISSUE TITLE
Core/DB Object only Game master mode can be clicked

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27687]
### Description

Quest https://www.wowdb.com/quests/12925-aberrations
Plagued Proto-Drake Eggs(191840)Even if you have a mission, you can only click on it in GM mode

### Expected behaviour

Can perform quest normally

### Steps to reproduce the problem

1.q a 12925
2.go gameobject 58230
3.additem 41612

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/50178650b2d1c123c40aa4d7ed3ecf3d7fefa00d

### Operating system

Windows 10 x64,

### Custom changes

None

**Comment by Alastro-Kraken** [comment]
That's blizzlike, you're not supposed to open them, you're supposed to destroy them using the frost bombs dropped by the nearby mobs.

**Comment by w5860363** [comment]
@Alastro-Kraken I mean only GM mode can click on them using items

**Comment by Alastro-Kraken** [comment]
Strange. I just tested it on a clean TC, it works. Just to be clear, are you right-clicking the frost bomb, then left-clicking on the eggs?

![WoWScrnShot_012922_191859](https://user-images.githubusercontent.com/98045288/151672715-8814c3f8-1ed4-4ad9-ae2e-919d28ab93f3.jpg)
.

**Comment by Aokromes** [comment]
you don't must click them, you must destroy them using the bomb next to them.
