### ISSUE TITLE
Wind Stones in Silithus are not reseting after use

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#27698]
### Description

After using a wind stone in Silithus to call forth a Templar, Duke, etc there's supposed to be a cool down until it's usable again. 

They currently appear to be usable once and then do not reset. You have to move to another stone or camp. 

Currently, the only way to use the wind stone again is to restart the server.

### Expected behaviour

There is supposed to be automatic reset timer on them. WOWIKI claims it is "approximately 15 mins".

https://wowwiki-archive.fandom.com/wiki/Wind_stone

### Steps to reproduce the problem

1. Go to Silithus and kill Twilight's until you have the 3 required garments
2. Don the gear, click the wind stone, call forth Templar
3. Defeat Templar (on lesser wind stones, dukes on wind stones, etc)
4. Wind stone will not return to a usable state.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. a650bd6 2022-01-16 18:50:28 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 7 x64

### Custom changes

Trinity Bots

**Comment by anzz1** [comment]
Also the traps linked to them dont pop when you talk to them without the required gear (spell 24803)
