### ISSUE TITLE
.reload smart_scripts not working

### ISSUE THREAD

**Issue by anzz1** [TrinityCore/TrinityCore#27731]
### Description

.reload smart_scripts is not working, server restart required to reload them. Tried also .reload creature_template <id> with it, to no avail.

### Expected behaviour

smart_scripts table should be reloaded and the creature behaviour changed according to it.

### Steps to reproduce the problem

1. Start server
2. Go to any creature with .go c id
4. Modify creature's smart_scripts entry
5. Do `.reload smart_scripts`
6. Observe console output
```
>> Loaded SmartAIMgr Helpers in 9ms
>> Loaded 13483 SmartAI scripts in 186 ms
```
7. In reality, they are not changed. Not at least on already loaded & spawned creatures.

### Branch

3.3.5

### TC rev. hash/commit

8e41167aba28b20349009e9127b6c4800d58a596 (https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/06136c07451ccdf8aae0418aa48568b1983d0a66)

### Operating system

Windows 7 x64

### Custom changes

None

**Comment by offl** [comment]
It's working but you need to reset creature (kill, respawn \ leave instance, reset instance, enter instance), I think it's intended
Same for gameobjects

**Comment by Ovahlord** [comment]
The AI is not being reloaded for already spawned creatures. It gets applied for every creature that is being spawned from that point on. Same applies to template changes. So not a bug, it's a feature.

**Comment by anzz1** [comment]
I see , thanks for clarification. The documentation is in serious need for updating but the current atlassian one is a nightmare to work with so I guess there are not too many volunteers to do that ':D
