### ISSUE TITLE
Spell Arcane Intellect causes world to crash

### ISSUE THREAD

**Issue by crados** [TrinityCore/TrinityCore#27745]
### Description

While playing as Mage Draenei, using the learned spell Arcane Intellect cause the worldserver to crash, and get disconnected from the game

TC> MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-530-0-17216-0000000813
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-530-0-620-0000000853
Illegal instruction (core dumped)
crados@ubuntu:~/server/bin$ 

### Expected behaviour

The spell should work without causing crash, and infuse the caster with brilliance increasing their intellect by 5% for 1 hour

### Steps to reproduce the problem

Create Draenei, Mage Character
Reach level 8 and learn "Arcane Intellect"
Use spell

OR

.learn 1459
[https://www.wowhead.com/spell=1459/arcane-intellect](url)
Use spell, after a few seconds it will crash

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 7192da410d6d 2022-02-07 16:49:18 +0100 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

World Runing in Ubuntu 20.04, game played in Windows 10

### Custom changes

None

**Comment by Shauren** [comment]
Crash log where?

**Comment by crados** [comment]
> Crash log where?

I added the crash part that shows in the worldserver, if its needed i can post all the log, but basically thats what shows when using the spell

**Comment by Shauren** [comment]
Ueeless, crash logs are obtained bt running worldserver with GDB

**Comment by TQPS** [comment]
I just rebuilt my 9.1.5 and although I logged #27629 the other day, my server does not crash when trying to use this spell. I am running mine on Windows, perhaps it's a linux issue only?

**Comment by crados** [comment]
> Useless, crash logs are obtained bt running worldserver with GDB

First of all sorry to bother you, i've tried to run worldserver with gdb, it loads fine and i can enter world with my character, but as soon as i use the spell it kinda gets stuck usgin it, i can't see errors and after that it does nothing, even if i write i chat box, if i quit the gdb from process and use the spell, it crashes, with that illegal instruction error.

**Comment by crados** [comment]
I got this error, sorry for spaming 

TC> World Thread hangs, kicking out server!

/home/crados/TrinityCore/src/server/worldserver/Main.cpp:545 in Handler ABORTED.

Thread 8 "worldserver" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff1bfa700 (LWP 2147)]
0x0000000000b977f1 in ConditionMgr::IsPlayerMeetingCondition (player=
    0x7ffe7df900c0, condition=0x7fffca884cfc)
    at /home/crados/TrinityCore/src/server/game/Conditions/ConditionMgr.cpp:3217
3217	    if (condition->CovenantID && player->m_playerData->CovenantID != condition->CovenantID)

**Comment by Shauren** [comment]
On the right track but we need the entire log, not just the top few lines from it (it looks more like this https://gist.github.com/Idoitbetter/551d005179b2da2e03a66196dbc2ecfb)

**Comment by Shauren** [comment]
Anyway, check if 7efc3df8150859519968740f265d9ba4b456beb7 does anything for you

**Comment by crados** [comment]
> Anyway, check if [7efc3df](https://github.com/TrinityCore/TrinityCore/commit/7efc3df8150859519968740f265d9ba4b456beb7) does anything for you

Compiled it to the latest commit, the issue is fixed, thanks.
