### ISSUE TITLE
Core/DB The gobject after respawn cannot complete the quest

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27753]
### Description

Quest https://www.wowdb.com/quests/12925-aberrations
Dragon eggs after respawn cannot be destroyed by mission items

### Expected behaviour

The object is not affected by the refresh process

### Steps to reproduce the problem

1.q a 12925
2.go gameobject 58230
3.additem 41612
4.After using items once Modify object refresh speed or wait time
5.Use items on reborn objects

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/2cb970c66387137c3593184a0d392afb153cf56d

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
d5b64a0bb23c this seems invalid, cannot reproduce on given example.
