### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by tach-tm** [TrinityCore/TrinityCore#27776]
### Description

compilation error
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(208,52): error C2143: syntax error: missing ")" before "*" (compiles source file C:\Code\TrinityCore\src \common\Utilities\StartProcess.cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(208,52): error C2143: syntax error: missing ";" before "*" (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(208,83): error C2059: syntax error: ) (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(212,34): error C4430: missing type specifier - expected int. Note. C++ does not support int by default (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(223,52): error C2143: syntax error: missing ")" before "*" (compiles source file C:\Code\TrinityCore\src \common\Utilities\StartProcess.cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(223,52): error C2143: syntax error: missing ";" before "*" (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(223,71): error C2059: syntax error: ) (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(228,34): error C4430: missing type specifier - expected int. Note. C++ does not support int by default (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(239,44): error C4430: missing type specifier - expected int. Note. C++ does not support int by default (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(239,42): error C2146: syntax error: missing ";" before identifier "f" (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(239,42): error C2065: f: undeclared identifier (compiles source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(239,63): error C2061: syntax error: identifier "nt_system_query_information_p" (compiling source file C:\Code\TrinityCore\src\common\Utilities \StartProcess.cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(241,14): error C2065: f: undeclared identifier (compiles source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(253,32): error C4430: missing type specifier - expected int. Note. C++ does not support int by default (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(253,30): error C2146: syntax error: missing ";" before identifier "f" (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(253,30): error C2065: f: undeclared identifier (compiles source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(253,51): error C2061: syntax error: identifier 'nt_query_object_p' (compiling source file C:\Code\TrinityCore\src\common\Utilities \StartProcess.cpp)
13>C:\boost\boost/process/detail/windows/handle_workaround.hpp(255,14): error C2065: f: undeclared identifier (compiles source file C:\Code\TrinityCore\src\common\Utilities\StartProcess. cpp)
13>C:\boost\boost/process/detail/windows/handles.hpp(139,27): error C2760: syntax error: unexpected token 'id'; ";" is required (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>C:\boost\boost/process/detail/windows/handles.hpp(132,10): message : A diagnostic message occurred in the compiler generated function "void boost::process::detail::windows::limit_handles_:: on_setup(Executor &) const" (source file C:\Code\TrinityCore\src\common\Utilities\StartProcess.cpp is compiled)
13>Building project "common.vcxproj" failed.

Message Diagnostic message occurred in compiler generated function "void boost::process::detail::windows::limit_handles_::on_setup(Executor &) const" common C:\boost\boost\process\detail\windows\handles.hpp 132
Error LNK1181 cannot open input file "..\..\common\RelWithDebInfo\common.lib" vmap4assembler C:\Code\Binaries\src\tools\vmap4_assembler\LINK 1
Error LNK1181 cannot open input file "..\..\common\RelWithDebInfo\common.lib" mapextractor C:\Code\Binaries\src\tools\map_extractor\LINK 1
Error LNK1181 cannot open input file "..\..\common\RelWithDebInfo\common.lib" vmap4extractor C:\Code\Binaries\src\tools\vmap4_extractor\LINK 1
Error LNK1181 cannot open input file "..\..\common\RelWithDebInfo\common.lib" mmaps_generator C:\Code\Binaries\src\tools\mmaps_generator\LINK 1
Error LNK1181 cannot open input file '..\..\common\RelWithDebInfo\common.lib' bnetserver C:\Code\Binaries\src\server\bnetserver\LINK 1
Error LNK1181 cannot open input file '..\..\common\RelWithDebInfo\common.lib' worldserver C:\Code\Binaries\src\server\worldserver\LINK 1 

### Expected behaviour

without mistakes

### Steps to reproduce the problem

compilation

### Branch

master

### TC rev. hash/commit

No

### Operating system

Windows 10 x64

### Custom changes

No

**Comment by Shauren** [comment]
Update boost to 1.73 or newer (just install latest)

**Comment by tach-tm** [comment]
Thank you turned out
