### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WoWHellgarve-HolyDeeW** [TrinityCore/TrinityCore#27789]
### Description

Server crashing 

### Expected behaviour

not crash

### Steps to reproduce the problem

..it was a player of mine, so i am not really sure. thank you :)

### Branch

master

### TC rev. hash/commit
be5d7f738ac4 

[be5d7f738ac4_worldserver.exe_[16-2_13-34-37].txt](https://github.com/TrinityCore/TrinityCore/files/8082967/be5d7f738ac4_worldserver.exe_.16-2_13-34-37.txt)

### Operating system

win

### Custom changes

no

**Comment by Naddley** [comment]
The Devs need definitly more Information then "Server is crashing". 
A crashlog would be very nice.

**Comment by iCeROCKZ** [comment]
i posted the crashlog. thank you for your response

**Comment by Aokromes** [comment]
there is no such rev  be5d7f738ac4 on trinitycore.

**Comment by Shauren** [comment]
Fixed in c5bd2ceda4834fdf88351016b66f1e23b7888de3
