### ISSUE TITLE
PvP Battlegrounds

### ISSUE THREAD

**Issue by Northernn** [TrinityCore/TrinityCore#27787]
### Description

Turned on .debug bg
Joined a BG - Horde
Opened the scoreboard - Working Fine
Logged in a second account
Joined BG - Alliance
Opened scoreboard - Working Fine
One of the players leaves the BG - Fine
Remaining player opens the scoreboard - Client Crashes   (not server/no crash logs)
Previous player logs back in to the same BG 
Opens the score board - Client crashes

Now it has completely messed up because alliance and horde players are not attackable now and green - not red and attackable as they should be.

Seems to be an issue with players leaving the BG so the player lists not being  updated in the BG, so the scoreboards crash when they find a player who isn't in the BG anymore. 

### Expected behaviour

Not crash on opening scoreboard

### Steps to reproduce the problem

I posted this in the description.

Used Eye of the storm to test this, haven't had time to test any other BG's yet!
[clientcrash](https://user-images.githubusercontent.com/67755436/154312602-11546cc6-fa44-4099-a685-606801f8471e.png)

### Branch

master

### TC rev. hash/commit

No idea how to do this. If you let me know what you need and how to do it I can do that, there are no server crashes so no logs
Just reporting the issue if someone wants to know/look into it.

TrinityCore rev. f12f3a972ff1+ 2022-02-16 00:00:55 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Windows 11 x64

### Custom changes

none

**Comment by mdX7** [comment]
fixed in #29438

**Comment by chenfenggis** [comment]
cook for eating？
