### ISSUE TITLE
Problem with compile 3.3.5a

### ISSUE THREAD

**Issue by uzverworks** [TrinityCore/TrinityCore#27797]
### Description

branches/3.3.5
CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

But, branches/master compile without problem.

### Expected behaviour

CMake error:

CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)

### Steps to reproduce the problem

Use:
Visual Studio 2019 v16.9
CMake v3.22.2
Git v2.34.1
boost v1_76_0

### Branch

3.3.5

### TC rev. hash/commit

Sources downloaded today.

### Operating system

Windows 7 SP1

### Custom changes

No custom changes.

**Comment by shamage** [comment]
Please could you enter here "log.txt" errors + exact DB version for TrinityCore?

**Comment by uzverworks** [comment]
> Please could you enter here "log.txt" errors + exact DB version for TrinityCore?

mysql v5.7.37

CMakeError.log:

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/TrinityCore-3.3.5/BUILD/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe cmTC_385f6.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine ўҐабЁЁ 16.9.2+58c36d143 ¤«п .NET Framework

(C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.



  ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.28.29921 ¤«п x64

  (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.

  CheckIncludeFile.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_385f6.dir\Debug\\" /Fd"cmTC_385f6.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\TrinityCore-3.3.5\BUILD\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

C:\TrinityCore-3.3.5\BUILD\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: pthread.h: No such file or directory, [C:\TrinityCore-3.3.5\BUILD\CMakeFiles\CMakeTmp\cmTC_385f6.vcxproj]

**Comment by uzverworks** [comment]
CMake log:
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.28.29921.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.7/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.7/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 5.7/bin/mysql.exe
fatal: not a git repository (or any of the parent directories): .git

CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)



* TrinityCore revision   : +  (+ branch)

* Install core to        : C:/Program Files/TrinityCore
* Install configs to     : C:/Program Files/TrinityCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

Found OpenSSL library: optimized;C:/OpenSSL-Win64/lib/VC/ssleay32MD.lib;debug;C:/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;optimized;C:/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: C:/OpenSSL-Win64/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Battlefield
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

Configuring incomplete, errors occurred!
See also "C:/TrinityCore-3.3.5/BUILD/CMakeFiles/CMakeOutput.log".
See also "C:/TrinityCore-3.3.5/BUILD/CMakeFiles/CMakeError.log".

**Comment by Shauren** [comment]
Did you download the source using this button 
![obraz](https://user-images.githubusercontent.com/297439/154812786-6cdd6905-5a0f-4e7b-813a-7b5caca85072.png)

instead of `git clone`?

**Comment by uzverworks** [comment]
I downloaded it, but it doesn't compile.
Or I don't understand something.

**Comment by Aokromes** [comment]
> 

clone the sourcecode, don't download zip.

**Comment by uzverworks** [comment]
Ok, I can try.
But I downloaded branches/master using button and compile without problem. It strange.

**Comment by uzverworks** [comment]
Really! It compile successed. Big thanks!
