### ISSUE TITLE
Db/Core End of battle

### ISSUE THREAD

**Issue by w5860363** [TrinityCore/TrinityCore#27792]
### Description

https://www.wowdb.com/npcs/26929-grand-magus-telestra
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp

Disengage from the battle after entering the second stage

Test single player and multiplayer situation is the same

### Expected behaviour

Normal killing of BOSS

### Steps to reproduce the problem

1.entry Nexus
2.dam 26299
3.enter phase two

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/3dca705acc953d20e4a43d4c2b3c97a84e5ab346

### Operating system

Windows 10 x6

### Custom changes

None

**Comment by offl** [comment]
This needs more detailed steps to reproduce because I can't reproduce this

**Comment by w5860363** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
