### ISSUE TITLE
Crash mmaps_generator.exe

### ISSUE THREAD

**Issue by uzverworks** [TrinityCore/TrinityCore#27803]
### Description

Regular crash mmaps_generator.exe

### Expected behaviour

Regular crash mmaps_generator.exe in random place.

USE:
Visual Studio 2019 v16.9.17
Windows SDK Version v10.0.16299.0 (But it crashes on other versions SDK as well...)

So many problems with 3.3.5 have not yet been.

### Steps to reproduce the problem

https://user-images.githubusercontent.com/100029976/154832785-7503d74a-edfd-40ec-937b-67aa67def6dc.jpg
Crash in any moment, but crash always!
Error https://user-images.githubusercontent.com/100029976/154833082-7a971d14-13ec-4790-8e54-55e1296eb317.jpg
[3dca705acc95+_mmaps_generator.exe_[20-2_10-18-21].zip](https://github.com/TrinityCore/TrinityCore/files/8103588/3dca705acc95%2B_mmaps_generator.exe_.20-2_10-18-21.zip)
)

### Branch

3.3.5

### TC rev. hash/commit

New clone sources.

### Operating system

Windows 7 SP1 with updates to 2022 (still supported)

### Custom changes

No custom changes.

**Comment by Aokromes** [comment]
useless log.

**Comment by uzverworks** [comment]
I don't have any other logs.
Only 3dca705acc95+mmaps_generator.exe[20-2_10-18-21].zip
And what to do?

**Comment by Faq** [comment]
extractor was compiled in debug?

**Comment by uzverworks** [comment]
> extractor was compiled in debug?

No, I always compile in release.

I try compile with boost 1.74, but problem no change.

**Comment by Shauren** [comment]
If you want to report crashes you can never compile in Release, use RelWithDebInfo instead

**Comment by uzverworks** [comment]
New log. Maybe it will help.
[mmaps_generator.exe_[20-2_13-56-27].zip](https://github.com/TrinityCore/TrinityCore/files/8103818/mmaps_generator.exe_.20-2_13-56-27.zip)

**Comment by Re3os** [comment]
not confirm,  3dca705acc95 2022-02-18 19:14:44 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready... 
perfect work.

**Comment by uzverworks** [comment]
> not confirm, [3dca705](https://github.com/TrinityCore/TrinityCore/commit/3dca705acc953d20e4a43d4c2b3c97a84e5ab346) 2022-02-18 19:14:44 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready... perfect work. Use extractor.bat and clean up client.

Re3os, Which Unix??? Once again I explain, that the failure occurs on WINDOWS 7, it is stupid to test on other systems if it is WRITTEN: it crashes on Windows 7
And do not write that I'm doing something wrong. I do everything the way I did before and everything worked, but now, due to some fixes in the source code, something was broken on Windows 7.
If everything works for you on Unix, then this does not mean the absence of a problem! And now on Windows 7, mmaps_generator.exe crash!
I always use extractor.bat and always use clean client!

**Comment by Faq** [comment]
@uzverworks for crashlogs better to use https://gist.github.com/
[posted your crashlog here](https://gist.github.com/Faq/a10fe482618611b87388a97ede11355c)

**Comment by uzverworks** [comment]
> @uzverworks for crashlogs better to use https://gist.github.com/ [posted your crashlog here](https://gist.github.com/Faq/a10fe482618611b87388a97ede11355c)

Ok, thanks!

**Comment by uzverworks** [comment]
I downloaded TrinityCore 3.3.5 with the new fix: https://github.com/trinitycore/trinitycore/commit/e898b6e792971a9bc942971a9bc96af54737bc96af54737bc96af54737ee971b99073a8.
After that changed the version of Visual Studio on Visual Studio 2019 v16.4.27
And just in case reinstalled Windows 7.
The problem is solved. I did not understand what it was.
