### ISSUE TITLE
Remove (DB\NPC\NPC Loot): kazzak is not in wotlk

### ISSUE THREAD

**Issue by acidmanifesto** [TrinityCore/TrinityCore#27819]
### Description

So [Kazzak NPC 12397 ](https://www.wowhead.com/npc=12397/lord-kazzak) is not in wotlk at all. When the dark portal opened up in tbc starting at version 2.4.1 tbc, he went thru and became [Doom Lord Kazzak npc 18728](https://www.wowhead.com/npc=18728/doom-lord-kazzak) .
Current sniffs and sniffing will show kazzak in classic and tbc, but he was removed in 334 due to his new position. I have not been able to locate a sniff to even show that Kazzak was ever in wotlk, let alone a video from either retail or pserver. various [comments on wowhead](https://www.wowhead.com/npc=12397/lord-kazzak#comments ) states that he only returned onces as kazzak back in wow legion for the 13th anniversary. He also is not even spawned in the tc 335 TDB in the creature table and is not referenced in any source script  currently as well.

### SQL fix

```sql
-- Remove Kazzak from DB since he is now Doom Lord Kazzak NPC 18728
DELETE FROM `creature_template` WHERE  `entry`=12397;
-- Removes Kazzak Loot table since he isn not in wotlk
DELETE FROM `creature_loot_template` WHERE  `Entry`=12397;
```

### Branch

3.3.5

### TC rev. hash/commit

[d7736ef](https://github.com/TrinityCore/TrinityCore/commit/d7736ef73251ebbb280bb1524e6877e198bccd58)

**Comment by Aokromes** [comment]
nope, we don't delete templates.
