### ISSUE TITLE
Quest ID 6622 Triage - They die right away

### ISSUE THREAD

**Issue by OlegVintaga** [TrinityCore/TrinityCore#27830]
### Description

We take the quest [https://www.wowhead.com/quest=6622/triage](url)

The wounded disappear immediately or cannot be cured

### Expected behaviour

After successful treatment, the following should appear, but it is even impossible to cure

### Steps to reproduce the problem

We take the quest [https://www.wowhead.com/quest=6622/triage](url)

Trying to execute

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/5518bfaa2a2526e54457eccd8d821177b6d5ca0d

### Operating system

Windows 10 X64

### Custom changes

No

**Comment by Surggurrian** [comment]
This issue still has not been fixed in the last update.
By the way, I do not remember we had this issue in Aug.2021, the last time I was playing 3.3.5.

**Comment by Killyana** [comment]
Dup https://github.com/TrinityCore/TrinityCore/issues/25387
