### ISSUE TITLE
NPC guid 42308 can't be seen in nonGM mode

### ISSUE THREAD

**Issue by xuehyc** [TrinityCore/TrinityCore#27839]
### Description

NPC guid 42308 can't be seen in nonGM mode,so we can't start our quests in this area

### Expected behaviour

It should be seen in normal players view

### Steps to reproduce the problem

a sort of quests can't go on 

### Branch

master

### TC rev. hash/commit

sorry did't notice

### Operating system

win11 x64

### Custom changes

None

**Comment by Aokromes** [comment]
no hash after 20d, closing.
