### ISSUE TITLE
Map 0004331.map is missing at run worldserver

### ISSUE THREAD

**Issue by tails2k** [TrinityCore/TrinityCore#27848]
### Description

Map 0004331.map is missing at run worldserver, but the Map is in the Map Folder. The worldserver.conf is also set to the data dir. Check also the permissions, all fine.

See: https://imgur.com/a/f7t2mtK

### Expected behaviour

he must see the map file and run

### Steps to reproduce the problem

Build new Sever and Maps

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 08f7fe67d1ec 2022-03-01 21:58:36 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
problem is on configuration, not bug. use absolute paths instead relative.

**Comment by tails2k** [comment]
> problem is on configuration, add / before home.

what the hell! last i kill the / before to do some test. i sure that the / before home was there and the error too. but now... fuck! sorry for that but i test it 5 times before a make this one.
