### ISSUE TITLE
Quests Being Auto Accepted When Talking To Quest Givers

### ISSUE THREAD

**Issue by Firewarrior565** [TrinityCore/TrinityCore#27843]
### Description

When walking up and talking to a quest giver the quest they have is auto accepted. The quest is still up on the screen where you can X out or click "Accept" which doesn't do anything.

### Expected behaviour

When you walk up to a quest giver the quest should be displayed but you have to click "Accept" for it to actually go into your quest log.

### Steps to reproduce the problem

Make a new character and walk up to the first quest giver you see. Talk to them and you will see the quest is auto accepted.

### Branch

3.3.5

### TC rev. hash/commit

None available.

### Operating system

Windows 11 x64 on client side. Server 2016 on the server side.

### Custom changes

None.

**Comment by offl** [comment]
Not a bug
