### ISSUE TITLE
Satellites do not stand when the airship or ship is moving.

### ISSUE THREAD

**Issue by MegaserverRU** [TrinityCore/TrinityCore#27845]
### Description

The satellite does not stand still as it should. He starts to run after an airship or a ship when he is on them. after which he disappears and you have to call him again.

### Expected behaviour

When you come to the ship or airship, the satellite should stand nearby and not run after you. when moving a ship or airship, the pet must stand nearby and not call him again

### Steps to reproduce the problem

Satellites do not stand when the airship or ship is moving.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore (3.3.5)

Satellites do not stand when the airship or ship is moving.

### Operating system

Windows 7 x64

### Custom changes

Satellites do not stand when the airship or ship is moving.
When the ship or airship moves, they start to run and then simply disappear. after which they have to be called on a new
Can you somehow fix this so that they stand still when moving, like a character?

![WoWScrnShot_030222_113115](https://user-images.githubusercontent.com/98691968/156326817-082c986c-81a1-4a74-9af0-ebe8300132a7.jpg)
![WoWScrnShot_030222_113135](https://user-images.githubusercontent.com/98691968/156326831-470b0ef2-dd94-40ab-a360-f8ed6a40ac70.jpg)

**Comment by Aokromes** [comment]
duplicate.

**Comment by MegaserverRU** [comment]
> дубликат.

Where is there a solution to this problem? And I can't find it.

**Comment by MaxtorCoder** [comment]
> > дубликат.
> 
> Where is there a solution to this problem? And I can't find it.

A duplicate does not mean it got resolved.

**Comment by MegaserverRU** [comment]
> > > дубликат.
> > 
> > 
> > Где есть решение этой проблемы? И я не могу его найти.
> 
> Дубликат не означает, что он был разрешен.

Ahh got it. Thanks for explaining. I will know now :)
