### ISSUE TITLE
 >> Applying update "2022_01_18_07_world_2020_06_26_06_world.sql" '4872608'...

### ISSUE THREAD

**Issue by EOSource** [TrinityCore/TrinityCore#27844]
### Description

It's been stuck on this update for 30 minutes, I reluctantly aborted; and tried again, when that did not work I dropped all tables and started over, still getting stuck on that update. 
![image](https://user-images.githubusercontent.com/92658171/156313245-226ecacb-b98b-4686-9a02-d5c2d659742a.png)

### Expected behaviour

It should apply the patch like the others

### Steps to reproduce the problem

Clone latest branch
Generate cmake with cmake-gui
Compile trinity.SLN
remove .dist from config files
open worldserver.exe
ask to make new database yes, yes, yes

### Branch

master

### TC rev. hash/commit

None

### Operating system

Windows 10

### Custom changes

None

**Comment by Aokromes** [comment]
not a bug, only very big file.

**Comment by offl** [comment]
Probably it's time to release TDB
