### ISSUE TITLE
feat(Core/Creature): Dual id SpawningFeature: 

### ISSUE THREAD

**Issue by genion18** [TrinityCore/TrinityCore#27854]
### Description

Some Areas have Dual Spawning,

Silithus, Burning Steppes or Felwood.

This thit "pool_members" edit is to expensive.

this is very better then spanning more than 1 creature in the same Area/Location.

### Expected behaviour

More then 1 NPC in a Area/Location.

### Steps to reproduce the problem

see:

https://github.com/azerothcore/azerothcore-wotlk/commit/65330af54552c8181cab0741b121b2d8bf71e6a6

and

https://github.com/azerothcore/azerothcore-wotlk/commit/dd89bdfb2a95f67417434ee4a0d905ed3a72f5da

### Branch

3.3.5

### TC rev. hash/commit

85b15a4b8c798f0bcb190a5481d624e6eb091e67

### Operating system

Windoof 7

### Custom changes

none

**Comment by Shauren** [comment]
We have no intent to create a pooling shortcut like that
