### ISSUE TITLE
Human Racial Cannot Remove Fear/Blind/etc

### ISSUE THREAD

**Issue by mikex2k** [TrinityCore/TrinityCore#27863]
### Description

Humans cannot use their racial to remove psychic scream, blind, etc can only remove stuns.

### Expected behaviour

Human racial should be able to remove all crowd control spells

### Steps to reproduce the problem

Clone 335 branch, compile and run. This issue has been around since release 21101 or earlier

### Branch

3.3.5

### TC rev. hash/commit

commit 53e1666a93d4d4d595b8707a39a88395030108ae

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by kvipka** [comment]
fix : 
`// ignore for remote control state (for player case)
    Unit* mover = GetGameClient()->GetActivelyMovedUnit();
    if (!mover)
        mover = _player->GetCharmedOrSelf();

    if (mover != _player && mover->GetTypeId() == TYPEID_PLAYER)
    {
        recvPacket.rfinish(); // prevent spam at ignore packet
        return;
    }`

**Comment by mikex2k** [comment]
@kvipka thank  you very much. This fixed the issue

**Comment by Miorey** [comment]
@kvipka  Hello there is any pr linked to fix this issue ?

**Comment by CraftedRO** [comment]
This issue is really annoying and must be resolved , if kvipka pr is valid maybe we can push it.

**Comment by Shauren** [comment]
It is not valid

**Comment by Miorey** [comment]
On the following release this bug exists: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.22081
And in the merged pr since I didn't see any fix on this.

**Comment by Dekz120** [comment]
I checked at dc221604d9971eabb95cdbaececa28765a6dfa9a
Problem still up. and the same thing with [Divine Shield](https://www.wowhead.com/wotlk/spell=642/divine-shield ) and [ Ice Block](https://www.wowhead.com/wotlk/spell=45438/ice-block).  btw trinkets works properly
i'll try to resolve this
