### ISSUE TITLE
Quest: Weaken the Ramparts (Incorrect display)

### ISSUE THREAD

**Issue by MegaserverRU** [TrinityCore/TrinityCore#27864]
### Description

https://tbc.wowhead.com/quest=9572/weaken-the-ramparts
Incorrect display of the task on the map
Shows a completely different area

![WoWScrnShot_031022_111500](https://user-images.githubusercontent.com/98691968/157618640-c52543af-0b96-4327-a248-029e4bb4403e.jpg)

### Expected behaviour

Must show on the dungeon

### Steps to reproduce the problem

https://tbc.wowhead.com/quest=9572/weaken-the-ramparts
Incorrect display of the task on the map
Shows a completely different area

Must show on the dungeon

https://youtu.be/PJFMPQmCTSY

### Branch

3.3.5

### Operating system

Windows 7 x64

### Custom changes

No

**Comment by offl** [comment]
They used coords from instance map and not from outdoor map. It's fixed in Cata
