### ISSUE TITLE
[3.3.5] Quest : A Fall From Grace #12274

### ISSUE THREAD

**Issue by itsLevande** [TrinityCore/TrinityCore#27876]
### Description

The quest, [A Fall From Grace](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12274), cannot be completed. You are required to maintain a disguise throughout the quest, but interacting with a required object will remove your disguise, meaning you cannot fully complete it.

### Expected behaviour

1. After getting their disguise from the quest giver, the player completes the first step of the quest by interacting with a bell
2. Once the bell is rung, the player completes the final step of the quest by speaking to an NPC while still disguised.

The following video demonstrates what is supposed to happen:

https://www.youtube.com/watch?v=iCAnVB33RqU

### Steps to reproduce the problem

Step 1. Complete all quests up until [A Fall From Grace](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12274).
Step 2. Accept the quest.
Step 3. Speak to the Quest Giver and have them apply your disguise
Step 4. Walk into the Abbey and ring the bell
Step 5. Watch as your disguise is removed, marking the end of your journey in this quest chain

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 2022-02-11 11:32:14 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
i wonder if that spell must ignore the removal of items on use.

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/issues/16035
