### ISSUE TITLE
NPC 'Pilot Xiggs Fuselighter' missing

### ISSUE THREAD

**Issue by njikmf** [TrinityCore/TrinityCore#27871]
### Description

I' m doing quest 'Arcane Runes', https://classic.wowhead.com/quest=3449/arcane-runes, but can not find the ending NPC 'Pilot Xiggs Fuselighter'. 

'SELECT * FROM world.creature_template where entry=8392;' there is record, but there's no related record in table 'creature', I could do a fix but I don't know how to convert minimap coordinate to positionx y z.
Please help

### Expected behaviour

https://classic.wowhead.com/npc=8392/pilot-xiggs-fuselighter
The NPC should exist.

### Steps to reproduce the problem

Go to [Azshara] to find 'Pilot Xiggs Fuselighter'

### Branch

3.3.5

### TC rev. hash/commit

latest

### Operating system

win10

### Custom changes

trinitybots

**Comment by njikmf** [comment]
After hours of researching ... I create the NPC by ".npc add 8392".
Then I found it auto created the db record as following:

table 'creature'

# guid, id, map, zoneId, areaId, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, wander_distance, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags, ScriptName, VerifiedBuild
'213853', '8392', '1', '0', '0', '1', '1', '0', '0', '2250.31', '-7223.47', '14.0891', '4.00028', '300', '0', '0', '2218', '0', '0', '0', '0', '0', '', '0'

**Comment by offl** [comment]
He's summoned by https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=10444#reward-from-quest

**Comment by Rushor** [comment]
Wowhead comments help for classic quest stuff :)

**Comment by njikmf** [comment]
Thank you all!
