### ISSUE TITLE
[3.3.5] Quest : Worm Wrangler #12078

### ISSUE THREAD

**Issue by itsLevande** [TrinityCore/TrinityCore#27878]
### Description

The main quest item, [Sturdy Crates](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=36771), is not working as intended. It can be used multiple times on the same worm without ever despawning the creature, although it will still let you loot the box in order to complete the quest.

### Expected behaviour

1. The player pulls an [Ice Heart Jormungar Spawn](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=26359) to them.
2. They then use their [Sturdy Crates](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=36771) on the worm to place a box under them.
3. The box captures the creature, despawning them from the world

The video below demonstrates what is supposed to happen :
https://www.youtube.com/watch?v=_is1bsp83o4

### Steps to reproduce the problem

1. Accept the quest, [Worm Wrangler](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12078)
2. Find a suitable worm and place the crate under them
3. Watch as the crate simultaneously creates, and captures, a clone of the worm while leaving the one attacking you unharmed
4. Repeat until you've duplicated this worm three times, allowing you to turn in the quest

### Branch

3.3.5

### TC rev. hash/commit

commit [47de80b](https://github.com/TrinityCore/TrinityCore/commit/47de80b852389bb6e1e0c6c9eafaa86e2e6fe5af)

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by dr-j** [comment]
~~~sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=26359 AND `source_type`=0 AND `id`=1;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(26359, 0, 1, 0, 8, 0, 100, 0, 47431, 0, 0, 0, 201, 0, 120, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 'Ice Heart Jormungar Spawn - On Spellhit (Capture Jormungar Spawn) - Despawn');
