### ISSUE TITLE
Some quest can not complete

### ISSUE THREAD

**Issue by njikmf** [TrinityCore/TrinityCore#27870]
### Description

Example quest id 9470
I use the latest code to compile and install the bots system(https://github.com/trickerer/Trinity-Bots).
You see I killed the monster but the quest list don't update them.

![2](https://user-images.githubusercontent.com/96371060/158111106-f46db62c-e75a-4903-b16a-5c1783a1c45d.PNG)

 But the GM command (.quest complete) works. 
![Capture](https://user-images.githubusercontent.com/96371060/158111147-05438643-10a0-4f65-949c-49806d59f9c0.PNG)

I am a new player to WOW and this server, I don't know is this a known issue? If is known please close this. 

### Expected behaviour

The quest should be in completed status.

### Steps to reproduce the problem

1 accept the quest "A Gesture of Goodwill" (9470)
2 kill those two monsterm, nothing happened. :( why?

### Branch

3.3.5

### TC rev. hash/commit

latest 335
https://github.com/TrinityCore/TrinityCore/commit/47de80b852389bb6e1e0c6c9eafaa86e2e6fe5af

### Operating system

win10

### Custom changes

server mod : https://github.com/trickerer/Trinity-Bots
client addon:  carbonite

**Comment by Aokromes** [comment]
not a bug, a player must do certain % of damage to get kill credit

**Comment by njikmf** [comment]
Thank you for reply... I tried to do more damage but still don't work....
Finally  I found the reason... I summoned too many bots and grouped them all....   Then I left the group , that's it...   😆 

From the code 
```
        if (q_status.Status == QUEST_STATUS_INCOMPLETE && (!GetGroup() || !GetGroup()->isRaidGroup() || qInfo->IsAllowedInRaid(GetMap()->GetDifficulty())))
```
