### ISSUE TITLE
use login error

### ISSUE THREAD

**Issue by Dirket** [TrinityCore/TrinityCore#27893]
### Description

use login erro report console  :WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 (1#1) 127.0.0.1

### Expected behaviour

use login erro report console  :WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 (1#1) 127.0.0.1

### Steps to reproduce the problem

use login erro report console  :WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 (1#1) 127.0.0.1

### Branch

master

### TC rev. hash/commit

use login erro report console  :WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 (1#1) 127.0.0.1

### Operating system

window 10

### Custom changes

use login erro report console  :WorldSocket::HandleAuthContinuedSession: Authentication failed for account: 1 (1#1) 127.0.0.1

**Comment by Aokromes** [comment]
problem is in chair not on computer.

**Comment by MaxtorCoder** [comment]
Useless issue. We don't know what commit hash, please fill in the issue template correctly, thank you.
