### ISSUE TITLE
[3.3.5] Quest : Halls of Stone #13207

### ISSUE THREAD

**Issue by itsLevande** [TrinityCore/TrinityCore#27897]
### Description

This issue effects both the completion of the [Halls of Stone](https://wowwiki-archive.fandom.com/wiki/Halls_of_Stone) dungeon, as well as the [Halls of Stone](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13207) quest. 

When trying to clear the dungeon, you are supposed to lead Brann Bronze beard to an area, where you are then tasked with defending him for a few minutes. The main issue is that two of the NPC's, [Abedneum](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=30899), are meant to act as a stationary form of announcement to let the players know what is currently happening. However, they will both aggro onto the closest player / friendly NPC and slowly auto attack them down while also being unable to be targeted or damaged. If they attack a player, they must be tanked for the full duration of the encounter. If they target Brann, then the players must continuously heal Brann through the entire encounter.

### Expected behaviour

Both NPC's should remain stationary without attacking anything near them, allowing players to clear through the dungeon and quest without this added frustration.

### Steps to reproduce the problem

1. Enter the Halls of Stone.
2. Clear every monster up until the Tribunal of Ages.
3. Enter the room and start being attacked by things which you cannot see.
4. Die.

### Branch

3.3.5

### TC rev. hash/commit

Commit [e318b03](https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/e318b03c5015ba2b40741acbc0c71b82e045d5d5)

### Operating system

Windows 10 x64

### Custom changes

Solocraft and Solo LFG

**Comment by Aokromes** [comment]
duplicate.
