### ISSUE TITLE
DB/Zone : The Wandering Isle - Start zone - Part 1

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#27908]
### Description

Starting Zone Repair - Part 1

### SQL fix

```sql
https://gist.github.com/shamage/6515b318b37c496fe6c1ae8bb006cc9a
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 934a1ad498ea 2022-04-09 00:25:16 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by funjoker** [comment]
```
DELETE FROM `trainer_spell` WHERE (`TrainerId`=59 AND `SpellId`=264212) OR (`TrainerId`=388 AND `SpellId`=265820);
INSERT INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`, `VerifiedBuild`) VALUES
(59, 264212, 10, 0, 0, 0, 0, 0, 5, 42010), -- No Faction found! MoneyCost not recalculated!
(388, 265820, 10, 0, 0, 0, 0, 0, 5, 42010); -- No Faction found! MoneyCost not recalculated!
```

can you check that with DB2 attached and config enabled :)

**Comment by funjoker** [comment]
```
DELETE FROM `conversation_actors` WHERE (`ConversationId`=16722 AND `Idx`=0);
INSERT INTO `conversation_actors` (`ConversationId`, `ConversationActorId`, `Idx`, `CreatureId`, `CreatureDisplayInfoId`, `VerifiedBuild`) VALUES
(16722, 0, 0, 0, 0, 42010); -- Full: 0x0
```

Seems like it's some empty actor.
So it means we need a ConversationScript which sets empty actor( if empty player guid check https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/World/conversation_scripts.cpp#L35)

You may can give me some sniff data here :)

**Comment by Naddley** [comment]
you can add .sql to your name of the gist "Wandering Isle v2.sql" for better reading :)

**Comment by shamage** [comment]
> you can add .sql to your name of the gist "Wandering Isle v2.sql" for better reading :)

all done

**Comment by funjoker** [comment]
Checked again. FactionTemplate is 35 which is faction 31. It's general friendly. No need for DB2 then.
So the trainer stuff is resolved

**Comment by funjoker** [comment]
fda65981c7a4c475c270755c198dee85cd38dfa3
