### ISSUE TITLE
Is there something wrong with Sunwell heights again?

### ISSUE THREAD

**Issue by HolmesLiu** [TrinityCore/TrinityCore#27904]
### Description

After I compiled with the latest version 3.3.5, boss 1 of taiyangjing highland cannot be killed (single brush), and I cannot be transferred to the second map during the period.

After killing boss 2, there should be a felmyst brush out, but I haven't seen it in the copy for a long time. After opening GM mode, I found that he was in the sky, but he was invisible and unable to attack.

### Expected behaviour

Blue Dragon corpse generates No. 3 boss, felmyst

### Steps to reproduce the problem

Sunwell highland, kill boss 2

### Branch

3.3.5

### TC rev. hash/commit

4ca81ffbfc85+ 

### Operating system

windows11

### Custom changes

https://github.com/trickerer/Trinity-Bots
https://github.com/ElunaLuaEngine/Eluna

**Comment by shenhuyong** [comment]
Hello xiongdi,
They don't understand what is taiyangjing highland and what is single brush 😆

**Comment by lyosky** [comment]
Hello xiongdi,
Pinyin..........   :)

**Comment by leelf00** [comment]
Sunwell Plateau Brutallus event Script seem not work correct.Many Details missing.

**Comment by ImmortalusDev** [comment]
It is very old bug.

**Comment by duandna007** [comment]
> It is very old bug.

i got the same bug，do u have some suggestion?
thanku~

**Comment by ImmortalusDev** [comment]
> > It is very old bug.
> 
> i got the same bug，do u have some suggestion? thanku~

Rewrite whole script, it is mess.

**Comment by duandna007** [comment]
> > > It is very old bug.
> > 
> > 
> > i got the same bug，do u have some suggestion? thanku~
> 
> Rewrite whole script, it is mess.

ok...Thanku

**Comment by WowChenEd** [comment]
> > > It is very old bug.
> > 
> > 
> > i got the same bug，do u have some suggestion? thanku~
> 
> Rewrite whole script, it is mess.

how to rewrite, can you give some detailed solution？thanks

**Comment by WowChenEd** [comment]
same bug, xiongdi
