### ISSUE TITLE
Error make IPLOCATION

### ISSUE THREAD

**Issue by MihaiDMA91** [TrinityCore/TrinityCore#27905]
### Description

In file included from /root/TrinityCore/src/common/IPLocation/IPLocation.cpp:22:
/root/TrinityCore/src/common/Asio/IpAddress.h:28:32: error: ‘boost::asio::ip::make_address’ has not been declared
         using boost::asio::ip::make_address;
                                ^~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h:29:32: error: ‘boost::asio::ip::make_address_v4’ has not been declared
         using boost::asio::ip::make_address_v4;
                                ^~~~~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h: In function ‘uint32 Trinity::Net::address_to_uint(const boost::asio::ip::address_v4&)’:
/root/TrinityCore/src/common/Asio/IpAddress.h:30:100: error: ‘const class boost::asio::ip::address_v4’ has no member named ‘to_uint’; did you mean ‘to_ulong’?
         inline uint32 address_to_uint(boost::asio::ip::address_v4 const& address) { return address.to_uint(); }
                                                                                                    ^~~~~~~
                                                                                                    to_ulong
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp: In member function ‘const IpLocationRecord* IpLocationStore::GetLocationRecord(const string&) const’:
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp:102:61: error: ‘make_address_v4’ is not a member of ‘Trinity::Net’
     uint32 ip = Trinity::Net::address_to_uint(Trinity::Net::make_address_v4(ipAddress));
                                                             ^~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/common.dir/IPLocation/IPLocation.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

### Expected behaviour

In file included from /root/TrinityCore/src/common/IPLocation/IPLocation.cpp:22:
/root/TrinityCore/src/common/Asio/IpAddress.h:28:32: error: ‘boost::asio::ip::make_address’ has not been declared
         using boost::asio::ip::make_address;
                                ^~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h:29:32: error: ‘boost::asio::ip::make_address_v4’ has not been declared
         using boost::asio::ip::make_address_v4;
                                ^~~~~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h: In function ‘uint32 Trinity::Net::address_to_uint(const boost::asio::ip::address_v4&)’:
/root/TrinityCore/src/common/Asio/IpAddress.h:30:100: error: ‘const class boost::asio::ip::address_v4’ has no member named ‘to_uint’; did you mean ‘to_ulong’?
         inline uint32 address_to_uint(boost::asio::ip::address_v4 const& address) { return address.to_uint(); }
                                                                                                    ^~~~~~~
                                                                                                    to_ulong
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp: In member function ‘const IpLocationRecord* IpLocationStore::GetLocationRecord(const string&) const’:
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp:102:61: error: ‘make_address_v4’ is not a member of ‘Trinity::Net’
     uint32 ip = Trinity::Net::address_to_uint(Trinity::Net::make_address_v4(ipAddress));
                                                             ^~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/common.dir/IPLocation/IPLocation.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

### Steps to reproduce the problem

error compil core

### Branch

3.3.5

### TC rev. hash/commit

last version

### Operating system

centos 8

### Custom changes

In file included from /root/TrinityCore/src/common/IPLocation/IPLocation.cpp:22:
/root/TrinityCore/src/common/Asio/IpAddress.h:28:32: error: ‘boost::asio::ip::make_address’ has not been declared
         using boost::asio::ip::make_address;
                                ^~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h:29:32: error: ‘boost::asio::ip::make_address_v4’ has not been declared
         using boost::asio::ip::make_address_v4;
                                ^~~~~~~~~~~~~~~
/root/TrinityCore/src/common/Asio/IpAddress.h: In function ‘uint32 Trinity::Net::address_to_uint(const boost::asio::ip::address_v4&)’:
/root/TrinityCore/src/common/Asio/IpAddress.h:30:100: error: ‘const class boost::asio::ip::address_v4’ has no member named ‘to_uint’; did you mean ‘to_ulong’?
         inline uint32 address_to_uint(boost::asio::ip::address_v4 const& address) { return address.to_uint(); }
                                                                                                    ^~~~~~~
                                                                                                    to_ulong
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp: In member function ‘const IpLocationRecord* IpLocationStore::GetLocationRecord(const string&) const’:
/root/TrinityCore/src/common/IPLocation/IPLocation.cpp:102:61: error: ‘make_address_v4’ is not a member of ‘Trinity::Net’
     uint32 ip = Trinity::Net::address_to_uint(Trinity::Net::make_address_v4(ipAddress));
                                                             ^~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/common.dir/IPLocation/IPLocation.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

**Comment by Shauren** [comment]
Your boost version is simply too old. We require at least 1.71

**Comment by MihaiDMA91** [comment]
i have 1.77

**Comment by Aokromes** [comment]
centos is not recomended to use. you have compiled yourself or it's centos package?

**Comment by MihaiDMA91** [comment]
centos 7 from ovh and the rest i installed by my self
