### ISSUE TITLE
Windows compile error (PhaseShift.cpp)

### ISSUE THREAD

**Issue by galathil** [TrinityCore/TrinityCore#27902]
### Description

Cannot compile master on Windows 10 (Visual Studio 2019) : 

2>D:\tc\sources9\src\server\game\Phasing\PhaseShift.cpp(23,63): error C2610: 'PhaseShift::PhaseShift(PhaseShift &&) noexcept' : n'est pas une fonction membre spéciale ou un opérateur de comparaison définissable par défaut
2>D:\tc\sources9\src\server\game\Phasing\PhaseShift.cpp(23,63): message : la spécification de l'exception ne correspond pas à la spécification déclarée de manière implicite.

### Expected behaviour

Should compile :D

### Steps to reproduce the problem

1) Clone repo with "git clone ..."
2) Running cmale
3) Open solution with Visual Studio 2019
4) Select "RelWithDebInfos"
5) Right click on ALL_BUILD > clean and build
6) Have compile error :(

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/5c49e63ec19e14f7dcbe86fa9ad5c4c486e54322

### Operating system

Windows 10

### Custom changes

None.

**Comment by Shauren** [comment]
I can guarantee that VS 2019 with v142 toolset can correctly compile master branch -  this is what is being tested on appveyor, link to successful build here https://ci.appveyor.com/project/DDuarte/trinitycore/builds/43109054

**Comment by galathil** [comment]
What should i do, reinstall VS?

Here, detailed info from VS (Help > About > copy infos)

```
Microsoft Visual Studio Community 2019
Version 16.5.3
VisualStudio.16.Release/16.5.3+30002.166
Microsoft .NET Framework
Version 4.8.04084

Version installée : Community

Visual C++ 2019   00435-60000-00000-AA041
Microsoft Visual C++ 2019

Adaptateur de test pour Google Test   1.0
Active l'utilisation des outils de test de Visual Studio avec les tests unitaires écrits pour Google Test. Les conditions d'utilisation et les notifications tierces sont disponibles dans le répertoire d'installation de l'extension.

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

Assistants Microsoft Visual C++   1.0
Assistants Microsoft Visual C++

Extension IntelliCode   1.0
Informations détaillées sur l'extension Visual Studio IntelliCode

Gestionnaire de package NuGet   5.5.0
Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, visitez https://docs.nuget.org/

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

MySQL for Visual Studio   1.2.10
Data design and management tools for MySQL. Copyright (c) 2007, 2019, Oracle and/or its affiliates. All rights reserved.

Outils C#   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Composants C# utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Outils Visual Basic   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Composants Visual Basic utilisés dans l'IDE. Selon votre type de projet et vos paramètres, une version différente du compilateur peut être utilisée.

Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio

Package Microsoft Visual Studio VC   1.0
Package Microsoft Visual Studio VC

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Studio Tools pour CMake   1.0
Visual Studio Tools pour CMake
```

**Comment by Shauren** [comment]
First try just updating it to a newer version, 16.5.3 was released almost 2 years ago (I don't mean switching to 2022, just install updates for 2019)

**Comment by galathil** [comment]
Shame on me...
I've update VS via "Visual Studio Installer" and it's works now !
Thank you :)
