### ISSUE TITLE
is trinitycore have anything like mod-anticheat for azerothcore ?

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#27923]
### Description

is trinitycore have anything like mod-anticheat for azerothcore ?
if has, how do i use it, this is important, thanks very much.

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

3.3.5

### TC rev. hash/commit

.

### Operating system

ubuntu 21

### Custom changes

.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-passive_anticheat
