### ISSUE TITLE
Creating Nightbourne Fatigue Issue

### ISSUE THREAD

**Issue by Spoony36** [TrinityCore/TrinityCore#27926]
### Description

When creating a nightborne and spawning into the world, if you move back a small distance (
![image](https://user-images.githubusercontent.com/6922184/164891650-146fc458-bffc-4d55-b01d-c6f5adf02729.png)
), fatigue bar kicks in and you die.

### Expected behaviour

Fatigue bar should not kick in i believe

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/6922184/164891624-8d1ef0ce-880d-455d-b3e2-16ebf51f01e1.png)

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 372c84e998a0+

### Operating system

Windows 11

### Custom changes

None

**Comment by Naddley** [comment]
Cant confirm. For me its working, I dont have the fatigue bar.
TrinityCore rev. 372c84e998a0

**Comment by Spoony36** [comment]
Strange did you move back slightly to the co-ords shown? It's not when you spawn into the world, you do need to move back very slightly at least for me, if you still can't confirm, i'll investigate more my end

**Comment by Naddley** [comment]
Nope still cant trigger the Fatigue bar you showed^^

**Comment by shamage** [comment]
I tried it too, no fatigue    

TrinityCore rev. 28d54cc4e0bd+ 2022-04-22 17:54:47 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by Spoony36** [comment]
Strange, closing issue then and will recompile and drop world
