### ISSUE TITLE
Unable to enter TC command

### ISSUE THREAD

**Issue by yijh** [TrinityCore/TrinityCore#27925]
### Description

I compiled using the code pulled from the 3.3.5 branch, on the Ubuntu 20.04 server,on the Ubuntu 20.04 server,Then use the zhTW client to extract the map data. After starting the server, it gets stuck, cannot enter the TC command, and cannot create an account

### Expected behaviour

enter the TC command

### Steps to reproduce the problem

git clone -b 3.3.5 https://github.com/TrinityCore/TrinityCore.git

cmake ../ -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/home/wow/server -DWITH_WARNINGS=1

copy TDB_full_world_335.22041_2022_04_14.sql file to bin dir
start worldserver ，Then the service has been in the ready state

below is the log

TrinityCore rev. 0d8672732552 2022-04-22 12:59:08 +0200 (3.3.5 branch) (Unix, None, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file /home/wow/server/etc/worldserver.conf.
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 99 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 73 archived updates.
Updating World database...
>> World database is up-to-date! Containing 2 new and 6194 archived updates.
Realm running as realm ID 1
Using World DB: TDB 335.22041
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 22041
Using DataDir /home/wow/server/data/
WORLD: MMap data directory is: /home/wow/server/data/mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: /home/wow/server/data/vmaps
Loading Trinity strings...
>> Loaded 1020 trinity strings in 1 ms
Initialize data stores...
>> Initialized 114 data stores in 741 ms
Using zhTW DBC Locale as default. All available DBC locales: zhTW 
>> Loading Cinematic Camera files
>> Loaded 0 cinematic waypoint sets in 1 ms
Loading IP Location Database...
Initializing PlayerDump tables...
>> Initialized tables for PlayerDump in 22 ms.
Loading SpellInfo store...
>> Loaded SpellInfo store in 65 ms
Loading SpellInfo corrections...
>> Loaded SpellInfo corrections in 18 ms
Loading SkillLineAbilityMultiMap Data...
>> Loaded 10219 SkillLineAbility MultiMap Data in 3 ms
Loading SpellInfo custom attributes...
>> Loaded 271 spell custom attributes from DB in 0 ms
>> Loaded SpellInfo custom attributes in 67 ms
Loading SpellInfo diminishing infos...
>> Loaded SpellInfo diminishing infos in 9 ms
Loading SpellInfo immunity infos...
>> Loaded SpellInfo immunity infos in 13 ms
Loading Player Totem models...
>> Loaded 20 player totem model records in 0 ms
Loading GameObject models...
Loading Script Names...
>> Loaded 3059 ScriptNames in 249 ms
Loading Instance Template...
>> Loaded 86 instance templates in 0 ms
...skipping...
>> Loaded SmartAIMgr Helpers in 12 ms
>> Loaded 13536 SmartAI scripts in 172 ms
Loading Calendar data...
>> Loaded 0 calendar events in 0 ms
>> Loaded 0 calendar invites in 0 ms
Loading Petitions...
>> Loaded 0 petitions.
Loading Signatures...
>> Loaded 0 Petition signs!
Loading Item loot...
>> Loaded 0 stored item loots
>> Loaded 0 stored item money
Initialize query data...
>> Initialized query cache data in 5196 ms
Initialize commands...
Initialize game time and timers
Mail timer set to: 780, mail return is called every 1440 minutes
Starting Map System
Starting Game Event system...
Initialize AuctionHouseBot...
Initializing chat channels...
>> Loaded 0 custom chat channels. DB table `channels` is empty.
Initializing Opcodes...
Starting Arena Season...
Starting Battleground System
>> Loaded 11 battlegrounds in 1 ms
Starting Outdoor PvP System
>> Loaded 6 outdoor PvP definitions in 1 ms
Starting Battlefield System
>> Loaded 1 battlefields in 194 ms
Loading Transports...
>> Spawned 20 continent transports in 686 ms
Loading Warden Checks...
Loading Warden Action Overrides...
Deleting expired bans...
Initializing quest reset times...
Calculate random battleground reset time...
Calculate deletion of old calendar events time...
Calculate guild limitation(s) reset time...
World initialized in 0 minutes 13 seconds
Starting up anti-freeze thread (60 seconds max stuck time)...
TrinityCore rev. 0d8672732552 2022-04-22 12:59:08 +0200 (3.3.5 branch) (Unix, None, Static) (worldserver-daemon) ready...

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/c0a120669dafe0688e6b7fc1e487e3dfd6220087

### Operating system

Ubuntu 20.04 x64

### Custom changes

n/r

**Comment by Aokromes** [comment]
it's working properly on head, something incorrect on your side.

**Comment by yijh** [comment]
@Aokromes  Thanks for your reply, can you tell me what might be wrong?

**Comment by mdX7** [comment]
Check if `Console.Enable` is 1 in worldserver config

**Comment by Aokromes** [comment]
> @Aokromes Thanks for your reply, can you tell me what might be wrong?

can you take one screenshot of you trying to run one command?

**Comment by yijh** [comment]
@mdX7 I should have accidentally modified this configuration，now it works fine，thanks
