### ISSUE TITLE
How to enable All item class transmog for all Classes?

### ISSUE THREAD

**Issue by wind886688** [TrinityCore/TrinityCore#27932]
### Description

Hello, sorry to bother, recently I am wondering How to enable All item class transmog for all Classes?
For example, can a Mage transmog a piece of plate armor?
Is there some value in DBC that controls what type of armor a class can transmog or equip?
Thank you ^_^

### Expected behaviour

A Mage can transmog a piece of plate armor

### Steps to reproduce the problem

unknown

### Branch

master

### TC rev. hash/commit

none

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by offl** [comment]
You can't
