### ISSUE TITLE
Unable to open file WbCertWhitelist.db2 in the archive for locale enUS: FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Snify89** [TrinityCore/TrinityCore#27936]
### Description

Using the mapextractor, it cant't open the file WbCertWhitelist.db2

### Expected behaviour

Not sure

### Steps to reproduce the problem

Use mapextractor for Client Version: 9.2.0.43340

### Branch

master

### TC rev. hash/commit

rev. b409a37c800b

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
not a bug, instead failed configuration / client.

**Comment by Shauren** [comment]
This is a bug (i forgot to update expected list of db2 files) but it is not neccessary to run TrinityCore, just ignore it

**Comment by Snify89** [comment]
Alright thank you. :) I just wanted to help, that's all.
Of course the core server still runs just fine :)
Thanks for clearing that up
