### ISSUE TITLE
Client entry error

### ISSUE THREAD

**Issue by Dirket** [TrinityCore/TrinityCore#27931]
### Description

hello,Bro,I need you help:   After selecting the map, enter the game and report an error

### Expected behaviour

![96e6b185628c9285bee87c8f38bb6d7](https://user-images.githubusercontent.com/32127918/165210376-068acc75-f0d5-4ab7-bbab-674d9fd08e16.png)

### Steps to reproduce the problem

Client entry error
worldserver 
![a03ea5084c417ff707a6461ca26fda8](https://user-images.githubusercontent.com/32127918/165480508-4495cfe6-059f-4eb5-a47f-79bfe525563a.png)

### Branch

master

### TC rev. hash/commit

a31e6819447626cd7b6967665001ea89bf6a0298   
[2022-04-27 15.26.33 Error - 17488.txt](https://github.com/TrinityCore/TrinityCore/files/8570033/2022-04-27.15.26.33.Error.-.17488.txt)

### Operating system

window 10 x64

### Custom changes

no

**Comment by Dirket** [comment]
I solved the problem

**Comment by Faq** [comment]
@Dirket would be nice if you could share how you did it, so next one with the same problem would know what to do.
