### ISSUE TITLE
Whisper players ingame

### ISSUE THREAD

**Issue by Eternyum** [TrinityCore/TrinityCore#27934]
### Description

https://ibb.co/RC7gnKv

### Expected behaviour

you can`t whisper players ingame

### Steps to reproduce the problem

No player named 'Shagz' is currently playing.

### Branch

3.3.5

### TC rev. hash/commit

last version

### Operating system

debian 10

### Custom changes

none

**Comment by Ovahlord** [comment]
was the whispering character on a lower GM level than the target player?

**Comment by Aokromes** [comment]
cannot reproduce on head.
https://i.imgur.com/qDy0H4g.png

**Comment by kvolk2git** [comment]
Maybe Shagz is character on GM account?

**Comment by ImmortalusDev** [comment]
character with GM rights, i bet

**Comment by Eternyum** [comment]
no is not a gm acc non of acc
