### ISSUE TITLE
Quest item "Dark Armor Plate" (id 42203) Problem with looting

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#27947]
### Description

Quest item [Dark Armor Plate](https://www.wowhead.com/item=42203/dark-armor-plate) starts to drop during quests [Facing the Storm](https://www.wowhead.com/quest=12978/facing-the-storm) and [The Gifts of Loken](https://www.wowhead.com/quest=12965/the-gifts-of-loken), but it cannot be picked up. After completing these quests, you can return and then [Dark Armor Plate](https://www.wowhead.com/item=42203/dark-armor-plate) can be picked up.

### Expected behaviour

[Dark Armor Plate](https://www.wowhead.com/item=42203/dark-armor-plate) should be possible to pick up during quests [Facing the Storm](https://www.wowhead.com/quest=12978/facing-the-storm) and [The Gifts of Loken](https://www.wowhead.com/quest=12965/the-gifts-of-loken).

### Steps to reproduce the problem

1. Take quests [Facing the Storm](https://www.wowhead.com/quest=12978/facing-the-storm) and [The Gifts of Loken](https://www.wowhead.com/quest=12965/the-gifts-of-loken);
2. Kill [Stormforged War Golem](https://wotlk.wowhead.com/npc=29380) and note that [Dark Armor Plate](https://www.wowhead.com/item=42203/dark-armor-plate) was dropped, but you can't pick it up, and it will become possible to pick it up after completing quests [Facing the Storm](https://www.wowhead.com/quest=12978/facing-the-storm) and [The Gifts of Loken](https://www.wowhead.com/quest=12965/the-gifts-of-loken).

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/d0b8fb87f29c6fe5a100c4f1f85cad2b349d9619
TrinityCore rev. 2022-04-30 ‏‎‏‎‏‎9:08:48 +0300 (3.3.5 branch) (Win64, Release, Static)
‎‎

### Operating system

Win7 x64 with all updates

### Custom changes

I use HD textures and models from the 6.x.x client, which enthusiasts were able to extract and make in the form of a patch for client 3.3.5. Also on the server side, I changed the drop probability of some items, and also increased the maximum stack size for some items.

**Comment by CraftedRO** [comment]
2a587e5ac43f Invalid issue (tested with non-gm account aswell), your client modification is most likely the problem.


https://github.com/TrinityCore/TrinityCore/assets/24683355/0f0d1491-e713-405e-ba2d-43a1faa63f77
