### ISSUE TITLE
how do i use passive_anticheat, is there any document for it ? 

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#27958]
### Description

how do i use passive_anticheat, and config it.
is there any document for it ? 
custom changes ?
sorry about my issue, 
i do not knows how to use it , i am so sorry.

https://github.com/TrinityCore/TrinityCoreCustomChanges/tree/3.3.5-passive_anticheat

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

3.3.5

### TC rev. hash/commit

.

### Operating system

.

### Custom changes

.

**Comment by Aokromes** [comment]
this doesn't belongs here, ask on forum.
