### ISSUE TITLE
Possible memory leak when loading db2

### ISSUE THREAD

**Issue by Luzifix** [TrinityCore/TrinityCore#27953]
### Description

In the function [DB2FileLoaderRegularImpl::AutoProduceData](https://github.com/TrinityCore/TrinityCore/blob/master/src/common/DataStores/DB2FileLoader.cpp#L397) for all entries from 1 to (MaxId +1) memory is allocated in Ram that means if in a DB2 Ids are omitted memory is allocated for them anyway. Specifically in ItemSparse but also in other DB2's where Id ranges are omitted more Ram is used than needed.

### Expected behaviour

Only memory for used ids is allocated.

### Steps to reproduce the problem

Debug to https://github.com/TrinityCore/TrinityCore/blob/master/src/common/DataStores/DB2FileLoader.cpp#L397 and compare maxi variable count with recordsize

### Branch

master

### TC rev. hash/commit

19b052d939ade28e95a6aed405a620a6ee966af8

### Operating system

Win 10 x64 / Linux

### Custom changes

Nothing

**Comment by Shauren** [comment]
This is by design, not a leak
