### ISSUE TITLE
Pets level 60 - Pet Scaling avoidance/damage/hit

### ISSUE THREAD

**Issue by Daniel25** [TrinityCore/TrinityCore#27954]
### Description

Pets lose stats with each level gained. Hp and armor scaling are working good but in lvl 60 pets get one shotted and miss all hits.
So I suppose that its a issue with avoidance/damage/hit stats.
It happens in all pets,not only hunter pets.
The funny thing is that pet stats scaling are working good when you use pets into of a dungeon/raid but outside,in the rest of world, it isnt working good.
Maybe someone can check what is the difference between pets into of a dungeon and outside and he/she find the fix.

### Expected behaviour

Pets wouldnt have to get one shotted in lvl 60 by normal mobs level 50+,neither pets miss all hits.

### Steps to reproduce the problem

1- Create a hunter and levelup to 60.
2- Tame a pet.
3- Send your pet to attack any creature level 50+ in world.
4- Join any dungeon level 50+.
5- Spawn a creature level 50+ .For example: https://www.wowhead.com/npc=129600/bilge-rat-brinescale
6- Send your pet to attack the creature.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/19b052d939ade28e95a6aed405a620a6ee966af8

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Thordekk** [comment]
Did u check pet_levelstats?

**Comment by Shauren** [comment]
I suspect its the level scaling system but this issue doesn't have enough info

creature_template_scaling for 129600?
pet id?
creature_template_scaling for [pet id]?

**Comment by Daniel25** [comment]
> I suspect its the level scaling system but this issue doesn't have enough info
> 
> creature_template_scaling for 129600? pet id? creature_template_scaling for [pet id]?

creature_template_scaling for 129600 has difficultyid=1 and contenttuningid=1220,the rest 0,that was a example but you can test it attacking any level 50+ creature what you want and its the same.

About creature_template_scaling for petid, I tested it with petid 3127 and others (its always the same).
That petid 3127 has creature_template_scaling with everything 0 and contenttunningid=70.

**Comment by ImmortalusDev** [comment]
It feels like level scaling system, it says that your pet is like level 40, but his real level is 1, when content tuning is for example 4, which is 1 - 30 lvl, so he will get oneshot and it will always miss, if it will try to attack creature with the same level, in this case 40.

**Comment by Daniel25** [comment]
> Did u check pet_levelstats?

If im not wrong,pet_levelstats isnt used since long time ago.
