### ISSUE TITLE
Master - Weapon Transmogrification Not Working

### ISSUE THREAD

**Issue by nellomin** [TrinityCore/TrinityCore#27960]
### Description

Just as the title says, whatever you do in game, be it a new made item or old item it is ever unable to be transmogrified.
Requesting help or fix code if one may have it.

### Expected behaviour

Go to transmogrifier NPC
Attempt to transmogrify weapon
Transmog weapon as long as you have apperance

### Steps to reproduce the problem

Step1: Go to transmogrifier NPC
Step2: Try to transmog weapon
Step3: Spam complete button, not working...

### Branch

master

### TC rev. hash/commit

.

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by ImmortalusDev** [comment]
Confirmed

**Comment by shamage** [comment]
Please provide the correct entry for the "TC rev. Hash / commit" you are referring to

**Comment by nellomin** [comment]
Getting no intel under hash so can't really provide any data whatsoever.
Compiled a clean TrinityCore master branch about 15 days ago and made no custom changes for transmog handling.

**Comment by aquadeus** [comment]
could be CMSG_CLEAR_NEW_APPEARANCE opcode not handled

**Comment by fluxurion** [comment]
[Screenshot from source](https://ibb.co/KyHRSMZ)

This commenting will enable weapon transmog. Problem is with this if statement.

[Video from ingame](https://youtu.be/aNEfO25Hysc)

**Comment by nellomin** [comment]
@fluxurion this alteration seems to fix the transmogrification issue. However you can not revert to the base state, not a huge problem but still.

Much appreciated!

**Comment by fluxurion** [comment]
Do u know about how to calculate transmog illusion updatefield value for each illusion?

Uint64 max value unlocks all. Should divide with the count of illusions?

[Video](https://youtu.be/abOmZo966Bo)
