### ISSUE TITLE
Item: Dr. Terrible's "Building a Better Flesh Giant" (42772)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#27984]
### Description

[Dr. Terrible's "Building a Better Flesh Giant"](https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) should drop with 100% chance after completing the quest [The Bone Witch](https://www.wowhead.com/quest=12999/the-bone-witch), and it drops, but for some reason it cannot be picked up, and therefore start the quest [The Sum is Greater than the Parts](https://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts).

### Expected behaviour

[Dr. Terrible's "Building a Better Flesh Giant"](https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) should drop with 100% chance from [Apprentice Osterkilgr](https://www.wowhead.com/npc=30409/apprentice-osterkilgr) after completing the quest [The Bone Witch](https://www.wowhead.com/quest=12999/the-bone-witch).

### Steps to reproduce the problem

1. Finish quest [The Bone Witch](https://www.wowhead.com/quest=12999/the-bone-witch);
2. Start quest [Deep in the Bowels of The Underhalls](https://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls);
3. Kill [Apprentice Osterkilgr](https://www.wowhead.com/npc=30409/apprentice-osterkilgr) and note that item [Dr. Terrible's "Building a Better Flesh Giant"](https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) is dropped but cannot be picked up for some reason.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
TrinityCore rev. 2022-05-29 ‏‎‏‎‏‎‏‎10:00:15 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by offl** [comment]
It drops if quest 'Deep in the Bowels of The Underhalls' is taken or completed
It didn't dropped for me when 'The Bone Witch' was taken or completed

>for some reason it cannot be picked up

Can't reproduce, does it give any error? If you already have one, for example

**Comment by Freeman256** [comment]
In my case, the item fell out, but when trying to pick it up from the corpse, inventory [Apprentice Osterkilgr](https://www.wowhead.com/npc=30409/apprentice-osterkilgr) simply closed, and the item remained in the corpse. Quest [Deep in the Bowels of The Underhalls](https://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls) was taken from me.

**Comment by offl** [comment]
And that happens again and again without any error on the screen?

**Comment by dr-j** [comment]
Probably needs condition for if quest is rewarded or needs to be taken, complete or rewarded so if player fails to pickup item while doing quest can pick it up later

**Comment by Freeman256** [comment]
Here I described a similar problem:
https://github.com/TrinityCore/TrinityCore/issues/27947

Perhaps [Dr. Terrible's "Building a Better Flesh Giant"](https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) can be picked up under other circumstances, but in my case, as I wrote earlier, when trying to take 123, inventory [Apprentice Osterkilgr](https://www.wowhead.com/npc=30409/apprentice-osterkilgr) simply closed and the item did not rise.

**Comment by offl** [comment]
Maybe this?

>Custom changes
I use HD textures and models from the 6.x.x client, which enthusiasts were able to extract and make in the form of a patch for client 3.3.5. Also on the server side, I changed the drop probability of some items, and also increased the maximum stack size for some items.

**Comment by Freeman256** [comment]
I highly doubt this has anything to do with the problem. These unofficial patches are allowed on the largest Russian private servers. For example, this patch is allowed on [wowcircle](https://wowcircle.net/en/stat.html).

In addition, these are client patches that replace textures in the game world (not a HUD), character models and NPCs, and animations.

If you are interested, you can read more about these patches [here](https://forum.uwow.biz/threads/cvpatch-collection-visual-patch-lich-king-3-3-5.296264/) (this is a Russian-language forum, use Google translator).

**Comment by offl** [comment]
Best I can recommend atm is try on clean TC without custom changes, just in case

**Comment by Freeman256** [comment]
Okay, I'll try.

**Comment by Freeman256** [comment]
Well, I tried it: I rolled back the database before I took [The Bone Witch](https://www.wowhead.com/quest=12999/the-bone-witch) quest, logged into the game using a clean client (even without addons), took the [The Bone Witch](https://www.wowhead.com/quest=12999/the-bone-witch) quest, completed it, took quest [Deep in the Bowels of The Underhalls](https://www.wowhead.com/quest=13042/deep-in-the-bowels-of-the-underhalls), but with In killing [Apprentice Osterkilgr](https://www.wowhead.com/npc=30409/apprentice-osterkilgr), item [Dr. Terrible's "Building a Better Flesh Giant"](https://www.wowhead.com/item=42772/dr-terribles-building-a-better-flesh-giant) fell out, but I still can’t pick it up. If necessary, I can record everything that happened on video.

**Comment by CraftedRO** [comment]
2a587e5ac43f Yeah this one is valid:


https://github.com/TrinityCore/TrinityCore/assets/24683355/03b6f21a-e50a-4cb3-bcf8-067284d0ad77

**Comment by CraftedRO** [comment]
```sql
-- Fix wrong quest condition
UPDATE `conditions` SET `ConditionValue1`=12999, `Comment`='Dr. Terribles \"Building a Better Flesh Giant"\ only drops if player has completed The Bone Witch' WHERE (`SourceTypeOrReferenceId` = 1) AND (`SourceGroup` = 30409) AND (`SourceEntry` = 42772) AND (`SourceId` = 0) AND (`ElseGroup` = 0) AND (`ConditionTypeOrReference` = 8) AND (`ConditionTarget` = 0) AND (`ConditionValue1` = 13042) AND (`ConditionValue2` = 0) AND (`ConditionValue3` = 0);
```

**Comment by CraftedRO** [comment]
```sql
-- Fix wrong quest condition
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 1) AND (`SourceGroup` = 30409) AND (`SourceEntry` = 42772);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(1, 30409, 42772, 0, 0, 47, 0, 13042, 74, 0, 0, 0, 0, '', 'Dr. Terribles "Building a Better Flesh Giant" only drops if player has state_mask 74 Deep in the Bowels of The Underhalls'),
(1, 30409, 42772, 0, 0, 2, 0, 42772, 1, 1, 1, 0, 0, '', 'Dr. Terribles "Building a Better Flesh Giant" will drop only if the player doesn\'t have it already');
```

**Comment by CraftedRO** [comment]
```sql
-- Fix wrong quest item condition for Dr. Terrible's "Building a Better Flesh Giant"
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 1 AND `SourceGroup` = 30409 AND `SourceEntry` = 42772;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(1, 30409, 42772, 0, 0, 47, 0, 13042, 74, 0, 0, 0, 0, '', 'Dr. Terribles "Building a Better Flesh Giant" only drops if player has state_mask 74 Deep in the Bowels of The Underhalls'),
(1, 30409, 42772, 0, 0, 2, 0, 42772, 1, 1, 1, 0, 0, '', 'Dr. Terribles "Building a Better Flesh Giant" will drop only if the player doesn\'t have it already');
```

**Comment by Freeman256** [comment]
It's nice to see that the problems are gradually being corrected. But the fact that the server will no longer work on Windows 7 makes me extremely sad. This means that I won't be able to update my server anymore because I'm not going to update my operating system. I am convinced that the refusal to support Windows 7 will not be able to radically change the situation with the remaining server problems, and because of this I consider the refusal of Windows 7 to be unfair and stupid. And you don’t need to tell me that Win 10, 11 (and what else there are) are much better than Win 7 - absolutely everything I need works for me on Win 7 (except for shitty modern games that are not at all interesting to me). I will only hope that there will be craftsmen who can make a separate Trinity Core branch that will work on Win 7, but until then, for me personally, the development of the server has stopped. A talented programmer must not only fix problems in scripts, but also do it in such a way that everything works perfectly on any system.

**Comment by Aokromes** [comment]
> It's nice to see that the problems are gradually being corrected. But the fact that the server will no longer work on Windows 7 makes me extremely sad. This means that I won't be able to update my server anymore because I'm not going to update my operating system. I am convinced that the refusal to support Windows 7 will not be able to radically change the situation with the remaining server problems, and because of this I consider the refusal of Windows 7 to be unfair and stupid. And you don’t need to tell me that Win 10, 11 (and what else there are) are much better than Win 7 - absolutely everything I need works for me on Win 7 (except for shitty modern games that are not at all interesting to me). I will only hope that there will be craftsmen who can make a separate Trinity Core branch that will work on Win 7, but until then, for me personally, the development of the server has stopped. A talented programmer must not only fix problems in scripts, but also do it in such a way that everything works perfectly on any system.

new c++ features works only on newer visual studio versions, witch doesn't support windows 8 or lower.

**Comment by jackpoz** [comment]
Why not support Windows XP or Windows 95 then ?

**Comment by CraftedRO** [comment]
Windows 7 is not what it used to be anyway, to be more precise they managed to implement some updates I think framework or .net that will destroy its functionality, so it will work like crap and besides that they don't have any optimization for ssd as I heard no point in using it its just a ghost of the past now (probably best os ever) and yes if you don't wanna learn linux (commands and so on) you can host wow on windows 11 (with requirements bypassed aka via rufus) like I do and it does a great job, yes even in production, (windows 10 is already bloated now).
