### ISSUE TITLE
Core/Player: Serverside and clientside position on transports are asynchronous

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#27985]
### Description

Before updating the repo with commit aa592e4, on alliance and horde ships you could take quests and attack Combat Dummy. After the commint it does not allow to take the quests, it does not hit the Combat Dummy and all the creatures appear without respecting the phases.

- [ ] Combat Dummy cannot be attacked.
- [ ] Does not allow to take quests.
- [X] Correct use of phases.  cb78ddc63a516af5dd0e00d36e07650f4856dee0

After commit:
![WoWScrnShot_052922_170715](https://user-images.githubusercontent.com/15787347/170891995-6c6a7973-3843-4fc0-8c05-3357e9888d79.jpg)

![WoWScrnShot_052922_170723](https://user-images.githubusercontent.com/15787347/170891951-6009563c-315d-457f-a995-ec76212cdb25.jpg)

### Expected behaviour

It must allow you to take the quests, be able to attack the Combat Dummy and the creatures must appear according to their phase.

Before the commit:
![WoWScrnShot_052922_160046](https://user-images.githubusercontent.com/15787347/170892082-4a300245-3dac-421d-8c0f-bf6db28698ef.jpg)

![WoWScrnShot_052922_160056](https://user-images.githubusercontent.com/15787347/170892246-eb92a049-bcec-40b4-8d95-f77cfcce4997.jpg)

### Steps to reproduce the problem

1. Create player.
2. Choose Exile's Reach starting area.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 67823c82c7f1 2022-05-26 20:09:04 +0200 (master branch) (Win64, RelWithDebInfo, Static)
SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Boost version: 1.79.0
World DB: TDB 920.22031

### Operating system

Windows 11 Pro 21H2

### Custom changes

None

**Comment by Ovahlord** [comment]
correct title would be: serverside and clientside position on transports are asynchronous

apparently something sneaked into the recent transport changes that causes that.

**Comment by mdX7** [comment]
Just to make sure: GM is off?
Phasing should be unrelated to this
