### ISSUE TITLE
Quest - I'm Smelting... Smelting! (13138)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#27994]
### Description

I'm Smelting... Smelting!
https://www.wowhead.com/quest=13138/im-smelting-smelting
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=13138

Quest doesn't work. Unable to use [Bag of Jagged Shards](https://www.wowhead.com/item=43289/bag-of-jagged-shards) near the Malykriss furnace. 

Watch the video to see what it looks like now.
https://youtu.be/a1Vs6dofM_o

Now look how the quest should work.
https://www.youtube.com/watch?v=oz7NlQ93t1w

### Expected behaviour

The player should be able to use [Bag of Jagged Shards](https://www.wowhead.com/item=43289/bag-of-jagged-shards) near the Malykriss furnace to get [Smelted Metal Bar](https://www.wowhead.com/item=43288/smelted-metal-bar). 

### Steps to reproduce the problem

1. Take quest [I'm Smelting... Smelting!](https://www.wowhead.com/quest=13138/im-smelting-smelting);
2. Go to Malykriss furnace (58, 71);
3. Use [Bag of Jagged Shards](https://www.wowhead.com/item=43289/bag-of-jagged-shards) near Malykriss furnace;
4. Note that wherever you run near Malykriss furnace, you cannot melt the [Bag of Jagged Shards](https://www.wowhead.com/item=43289/bag-of-jagged-shards) into an [Smelted Metal Bar](https://www.wowhead.com/item=43288/smelted-metal-bar) (watch the video).

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
TrinityCore rev. 2022-05-29 ‏‎‏‎‏‎‏‎10:00:15 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by ihm-tswow** [comment]
Works fine on https://github.com/TrinityCore/TrinityCore/commit/a7fe0494bf6d6737b0a874ceddac0e2c089a7ce8, maybe there's a locale/dbc issue or you somehow misconfigured your database?

**Comment by offl** [comment]
What's output of
```txt
.gob ne 20
```
 in that place?

**Comment by Freeman256** [comment]
Here I stand right in the middle of the fire on 58.1 70.6 (.gps X: 6473.293945 Y: 1801.673584 Z: 527.200317)
![WoWScrnShot_060522_103731](https://user-images.githubusercontent.com/73786888/172040678-5e2f5cb2-7a8a-4977-97b5-5f65a780fdb9.jpg)

**Comment by offl** [comment]
No idea then, works fine for me
You can try to check other quests with spell focus objects, like https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=11648

**Comment by dr-j** [comment]
I’ve seen this before phasing issue think have but cant remember which quest but know the 3 rider of …… quests which are nearby there change phase here once taken I think battle before the citadel at the enemies gates also cause phase change here if you have in quest log

**Comment by dr-j** [comment]
No ignore last bit I was getting confused with Matthias lehner quests under icc but those 3 group quests change phase here

**Comment by offl** [comment]
Try with same character
```sql
UPDATE `gameobject` SET `phaseMask` = `phaseMask` |4 WHERE `id` = 193004;
```

**Comment by Freeman256** [comment]
It worked! I was able to smelt the fragments into an ingot. So it really has to do with phasing. At the time of this quest, I had already completed almost all the quests in Icecrown, and it seems that I was in the "wrong phase".

By the way, I noticed a similar problem with ore deposits: it often happened that somewhere in the distance I saw ore, flew up to it and at that moment the phase changed and the ore disappeared right in front of me.

**Comment by offl** [comment]
Well, I'm kinda in doubts they really add all phases to such stuff, [the field with phases](https://www.gamersglobal.de/sites/gamersglobal.de/files/userupload/user131/wowedit_1024.jpg) here is empty, it's instance but still
I'm not really familiar with phases but maybe 1 is not really default
