### ISSUE TITLE
Quest - The Runesmiths of Malykriss (13140)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#27995]
### Description

The Runesmiths of Malykriss
https://www.wowhead.com/quest=13140/the-runesmiths-of-malykriss

WowHead says that [Runed Saronite Plate](https://www.wowhead.com/item=43291/runed-saronite-plate) should drop from [Skeletal Runesmith](https://www.wowhead.com/npc=31321/skeletal-runesmith) with a 46% probability, but there is no corresponding line in creature_loot_template table.

### SQL fix

```sql
DELETE FROM `creature_loot_template` WHERE `Entry` = 31321 AND `Item` = 43291;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Chance`, `QuestRequired`) VALUES (31321, 43291, 46, 1);
```

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
TrinityCore rev. 2022-05-29 ‏‎‏‎‏‎‏‎10:00:15 +0300 (3.3.5 branch) (Win64, Release, Static)

**Comment by Faq** [comment]
tcubuntu shows stright what is in trinitycore db for LichKing, 30%:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=43291

**Comment by Freeman256** [comment]
Ok.

```
DELETE FROM `creature_loot_template` WHERE `Entry` = 31321 AND `Item` = 43291;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Chance`, `QuestRequired`) VALUES (31321, 43291, 30, 1);
```

**Comment by dr-j** [comment]
I remember doing this quest on retail during mop and had to kill a lot of runesmiths like going round killing all several times before the plates dropped but wowhead comments are contradictive as some comments say players had to kill a lot (47 and one comment claiming had to kill more than 100 to get 5 plates but others say got in 5 kills or 100% chance

Possibly is meant to be progressive loot but wowhead no longer says which items have this.
