### ISSUE TITLE
Quest - That's Abominable! (13288, 13289, 13264, 13276)

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#28000]
### Description

Quest - That's Abominable!

Alliance
https://www.wowhead.com/quest=13288/thats-abominable
https://www.wowhead.com/quest=13289/thats-abominable
Horde
https://www.wowhead.com/quest=13264/thats-abominable
https://www.wowhead.com/quest=13276/thats-abominable

As the description says, you need to kill [Hulking Abomination](https://www.wowhead.com/npc=31140/hulking-abomination) and pick up [Chilled Abomination Guts](https://www.wowhead.com/item=43966/chilled-abomination-guts) from it, after which you can create a player-controlled Abomination and there are no problems with this, however, player-controlled Abomination's abilities do absolutely nothing. That is, explode ability (SpellID 59576) visually explodes (dies, scattering its insides), but no damage is done to enemies.

### Expected behaviour

Player-controlled Abomination's abilities must work.

### Steps to reproduce the problem

1. Start any of these quests:

Alliance
https://www.wowhead.com/quest=13288/thats-abominable
https://www.wowhead.com/quest=13289/thats-abominable
Horde
https://www.wowhead.com/quest=13264/thats-abominable
https://www.wowhead.com/quest=13276/thats-abominable

2. Kill some [Hulking Abomination](https://www.wowhead.com/npc=31140/hulking-abomination) until you get [Chilled Abomination Guts](https://www.wowhead.com/item=43966/chilled-abomination-guts);
3. Use [Abomination Reanimation Kit](https://www.wowhead.com/item=43968/abomination-reanimation-kit) to call player-controlled Abomination;
4.  Gather a group of enemies with player-controlled Abomination and try to blow them up with player-controlled Abomination (SpellID 59576);
5. See how the enemies were not damaged.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
TrinityCore rev. 2022-05-29 ‏‎‏‎‏‎‏‎10:00:15 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

None.

**Comment by ihm-tswow** [comment]
The mobs are not supposed to take damage, but should die mid-air and give kill reward. The spell seems to work as expected on a7fe0494bf6d
![image](https://user-images.githubusercontent.com/76849026/172023111-dcf8658d-0853-4243-84dc-c5bfce1a3192.png)

**Comment by Freeman256** [comment]
I made an additional check - the revived abomination normally kills quest NPCs with an explosion. So, perhaps, the problem can be closed. Before that, I tried to use the abomination explosion to kill nearby non-quest NPCs: other abominations and necromancers.
