### ISSUE TITLE
DB/Creature - Gossip menu in Orgrimmar for Orgrimmar Grunt does not work

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28014]
### Description

The menu table for Orgrimmar Grunt does not work at all and cannot be called up.

### Expected behaviour

The menu table should be retrievable.

### Steps to reproduce the problem

1. With the character go to Orgrimmar
2. Try to talk to one of the Orgrimmar Grunt guards
3. See how nothing happens

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 69d960b63f25 2022-06-09 16:00:22 +0200 (master branch)

### Operating system

Win 10 Pro

### Custom changes

nothing

**Comment by shamage** [comment]
Here are some examples:
![Ashampoo_Snap_štvrtok 9  júna 2022_19h58m56s_004_](https://user-images.githubusercontent.com/7515044/172913833-26dc3b9d-0116-417a-b1cb-1002e80bffee.png)
![Ashampoo_Snap_štvrtok 9  júna 2022_19h59m14s_005_](https://user-images.githubusercontent.com/7515044/172913836-844a855b-d5b5-416a-b70c-c2f2235d1d7b.png)
![Ashampoo_Snap_štvrtok 9  júna 2022_19h59m31s_006_](https://user-images.githubusercontent.com/7515044/172913838-ff9604c8-1ec8-4946-8e86-9298a3727af1.png)

**Comment by meji46** [comment]
I started working on it recently

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17414 it looks they broke again for ogrimmar.

**Comment by ImmortalusDev** [comment]
> #17414 it looks they broke again for ogrimmar.

this is a bit different issue my friend

**Comment by shamage** [comment]
> #17414 it looks they broke again for ogrimmar.

Dear @Aokromes, thank you for providing a link where something similar has been addressed and resolved. However, I am convinced that this problem will be somewhere else (maybe in some code / script), it will not be enough just to fix it with SQL, but of course I may be wrong.

I looked at the fixes themselves (which you referred to) and based on that I concluded that at that time it was a global problem, but this time it is a unique problem that only affects a certain group of NPCs. Therefore, please try to take a closer look at it, maybe you will agree with me. Thank you for understanding .

**Comment by meji46** [comment]
> > #17414 it looks they broke again for ogrimmar.
> 
> Dear @Aokromes, thank you for providing a link where something similar has been addressed and resolved. However, I am convinced that this problem will be somewhere else (maybe in some code / script), it will not be enough just to fix it with SQL, but of course I may be wrong.
> 
> I looked at the fixes themselves (which you referred to) and based on that I concluded that at that time it was a global problem, but this time it is a unique problem that only affects a certain group of NPCs. Therefore, please try to take a closer look at it, maybe you will agree with me. Thank you for understanding .

The only problem is that gossip_menu_id is 0 in the table creature_template. I'm updating all POI and gossip menus of the guards (and I have this bug fixed). I'll open an issue with the sql when I finish it.

**Comment by ImmortalusDev** [comment]
You are right, gossip menu isn't assigned. I found cases where wpp set gossip_menus to 0, it's happening sometimes when you generate update querys.

**Comment by Aokromes** [comment]
> You are right, gossip menu isn't assigned. I found cases where wpp set gossip_menus to 0, it's happening sometimes when you generate update querys.

the reason is when you dump horde sniffs over aliance npcs, class trainers, profesion trainers ....

**Comment by mdX7** [comment]
Its just because defaultvalue is 0 and you didnt talk to the npc, simple as that. Will try a fix in wpp later to prevent this

**Comment by ImmortalusDev** [comment]
Trust me, all update querys assigned menu properly, just not for that npc.

https://www.wowhead.com/npc=3296/orgrimmar-grunt
