### ISSUE TITLE
DB/Spawns populate Shadowmoon Valley Part 1

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28023]
### Description

Creature & Gob spawns

ToDo: Some feign Deaths Creature still have a full lifebar but flags and auras are set...

### SQL fix

```sql
https://gist.github.com/Naddley/5510b2b6f0c90770be45859181de93c3
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 7d9d55ee87e8

**Comment by mdX7** [comment]
> ToDo: Some feign Deaths Creature still have a full lifebar but flags and auras are set...

![lies-lies-mev2wc](https://user-images.githubusercontent.com/12143653/175795345-8d14b0f3-744c-40ee-b4b3-ef2ac43ef13f.jpg)

It's using a not yet named UnitFlag3, to be precise: 0x2000. Additionally the feign death is NOT setting DynamicFlags.
The UnitFlag3 is actually causing the stuff to make it appear dead in this case.

**Comment by mdX7** [comment]
requires #28070 for proper feign death
