### ISSUE TITLE
DB/Spawns add spawns for Lunarfall Pre-Garrison

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28037]
### Description

Creature & Gob spawns
Phasing

-> WPs for Flying Creatures are not yet done.

### SQL fix

```sql
https://gist.github.com/Naddley/de683c5ae34bc39fc351c5591e4168ae
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 8f537b968686

**Comment by mdX7** [comment]
I assume wps for flying npcs require cyclic wps?

**Comment by Naddley** [comment]
Nope no Cyclic.
[32] SplineFlags: 2438990336 (Flying, Catmullrom, CanSwim, UncompressedPath, Unknown5, Steering, Unknown10)

**Comment by Naddley** [comment]
added Phase remove after Garrison create.
