### ISSUE TITLE
RestState / RestBar / RestBonus

### ISSUE THREAD

**Issue by slash-design** [TrinityCore/TrinityCore#28051]
### Description

The RestBonus works as well.
Can be seen in the SQL database under the Character -- rest_bonus -- tab. This number changes.
Now when you kill a mob, you get rested XP. When this is used up, you get half. 

As soon as you go to an Inn, the ZZZ also appears in the character window.
But there is no message "You feel recovered" in the chat log.

The rest bar never turns blue. In the SQL database under the Character tab, the RestState is always set to 2. If you change this value to 1, the rest bar turns blue.

No automatic switching from number 2 to 1 and vice versa.

### Expected behaviour

Go to an inn, the message must appear - "you feel rested" and the RestBar must turn blue.

### Steps to reproduce the problem

1. Create character
2. e.g. level to level 10
3. Go to an inn or capital city
4. ZZZ appears 
5. RestBar does not turn blue
6. Message "you feel rested" does not appear

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/bd401af0912eca2c938b6dd93fdb7689b9146c89

### Operating system

Windows 10

### Custom changes

None

**Comment by Makcumoz** [comment]
Is there any way to change the maximum rest of 150% to a different value?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24366
