### ISSUE TITLE
Ulduar - Flame Leviathan not working

### ISSUE THREAD

**Issue by danjohnso** [TrinityCore/TrinityCore#28063]
### Description

Flame Leviathan encounter does not activate.  I tried both hard mode and easy mode, but I was unable to trigger Flame Leviathan activating.  IRC, he should activate when the 2 colossus in front of his gate die, but his gate and the energy barrier remained close and his model was inactive.

Possibly related, there were friendly mobs and a teleporter up and active behind him.  They should only be active after he has been killed.

### Expected behaviour

Flame Leviathan should activate and his gates open

### Steps to reproduce the problem

https://www.wowhead.com/wotlk/npc=33113/flame-leviathan

1) Talk to keeper to activate secondary defenses (optional, tried with this and without)
2) Clear enough of room to get to flame leviathan
3) Kill 2 colossus guarding his gate

### Branch

3.3.5

### TC rev. hash/commit

f922a7dff644451a05a6b0088b652fbe86dafebc

### Operating system

Ubuntu 21.10

### Custom changes

None

**Comment by Aokromes** [comment]
i tried with gm account with damage command to kill everything on front of it and worked for me.

**Comment by danjohnso** [comment]
I forgot to say I was in 25, I did not look at 10.  Which did you try it in?

**Comment by danjohnso** [comment]
Going to close because after a few restarts and another recompile he started activating for me.  I think there are some missing spoken from Brann and Dellorah related to activating the instance and hard modes, but I'll open a separate issue for those when I can debug them closer.

**Comment by Krutok** [comment]
same to me i have the same problem Hardmode not work
