### ISSUE TITLE
Transport Vehicle not correct works

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#28068]
### Description

After the Transport rewrite works Vehicle not correctly on Transports.
You or a NPC can succesfully enter the Vehicle but you don't move with the Vehicle if the Transport start his Path.
You stay on place and can only leave the vehicle or wait until the Transport move to other Map etc. and that kick you from transport.

### Expected behaviour

Passengers of Vehicle should move with the Transport/his Vehicle

### Steps to reproduce the problem

Add following code:

```
DELETE FROM `vehicle_template_accessory` WHERE `entry`=42267 AND `seat_id`=1;
INSERT INTO `vehicle_template_accessory` (`entry`, `accessory_entry`, `seat_id`, `minion`, `description`, `summontype`, `summontimer`) VALUES (42267, 42268, 1, 1, 'Garrosh\'s Formation Bunny - Garros\'s Airship', 5, 0);
```

AND
```
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=42267 AND `spell_id`=46598;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES (42267, 46598, 0, 1);
```

Go to Azshara (Coordinates: .go xyz 2667.0400 -6173.5434 138.75790) and wait for arrived 'The Spear of Durotar'

If 'The Spear of Durotar' now here, use .gm on (the passengers on the Transport are in Phase 236)
Look via /target Garrosh to "Garros's Airship" and wait until the Transport begins to move.
The Airship shows that he moved with the transport but if you use the .dist command you can see the distance between you and the Airship increase continually.

Other way:
Select the Formation Bunny via /target Garros's Formation Bunny and cast on his 46598 (Ride Vehicle Hardcoded) you are now a passenger of the Vehicle and if the Transport start moving you stay on place.

### Branch

master

### TC rev. hash/commit

a161b6cd328bbcf56950664f677fba716659f0d5

### Operating system

Windows 10 / CentOS

### Custom changes

None

**Comment by gonzo1247** [comment]
It's more problems with Vehicle. It is a general problem with Vehicle they has passengers.
It was with the https://www.wowhead.com/item=44234/reins-of-the-travelers-tundra-mammoth testet. Mount up and it's possible to Talk with the two passengers and open the trade menu.
If we walk now a little bit and try it again to talk/trade with one of the passengers is it not possible.
on the screenshot can you see that the distance between me and the passengers increase.
![WoWScrnShot_070922_191439](https://user-images.githubusercontent.com/640311/178116358-59c71336-2793-44f7-bf9d-2f9d76f3b815.jpg)

**Comment by Ovahlord** [comment]
to translate it into proper english: passenger positions on vehicles are currently not updated serverside. this applies to all vehicles.

**Comment by Ovahlord** [comment]
https://github.com/TrinityCore/TrinityCore/commit/377799fd3cd8d129b1b6afc146d7c40b70160ad9
