### ISSUE TITLE
[3.3.5] WSG Flag Capture Bug [40$]

### ISSUE THREAD

**Issue by immvp** [TrinityCore/TrinityCore#28076]
### Description

Currently, if you hold the Flag on top of the Capture Point on Warsong Gulch while enemy team is also holding the Flag, the flag will not capture. **This is correct.** 
However, if you're on the Capture Point when the enemy Flag gets Returned, then the Flag won't Capture. You need to get off the Capture Point, and onto it again. 

It seems like this could be fixed if you checked Flag position on Flag Return. I'm not sure tho'.

### Expected behaviour

Flag should be captured if Enemy Flag gets returned, even if you're on the capture point when this occurs.

### Steps to reproduce the problem

1. Pick up Flag on both sides
2. Get on the Capture Point with one of the Flags
3. Return the other flag
4. Now you'll see the Flag doesn't Capture, until you've walked off and onto the Capture Point.

### Branch

3.3.5

### TC rev. hash/commit

 TrinityCore rev. debd2446d6e8 2022-07-02 01:04:18 +0200 (main branch) (Unix, Release, Static)

### Operating system

Ubuntu 20.04

### Custom changes

None

**Comment by immvp** [comment]
Not sure how Bounties work, but I'd pay 20$ for this to be fixed.

**Comment by Aokromes** [comment]
you must put it at https://bountysource.com/

**Comment by immvp** [comment]
Done @Aokromes

**Comment by immvp** [comment]
Increased bounty to 40.

**Comment by Shauren** [comment]
Is it even supposed to work like that?

**Comment by immvp** [comment]
@Shauren That flag is supposed to cap when you're on top of capture point? Yes! I can send video evidence if needed!

**Comment by acidmanifesto** [comment]
> Is it even supposed to work like that?

I submitted wsg sniffs a while ago on the forum submission. Think it will show in the sniffs?

**Comment by immvp** [comment]
Maybe I explained the bug a bit bad. Essentially the flag should cap when you're on capture point, even IF you're on it pre-maturely when the flag returns.

**Comment by immvp** [comment]
Is there any way this thread can get the Bounty label, that'd be great. ^_^

**Comment by immvp** [comment]
I can increase the bounty if it means this will be looked at ASAP. I figued it wouldn't be anything major tho'. ^_^

If you're a developer and consider looking at this but the bounty is too small to make it worth it, please let it be known!
