### ISSUE TITLE
authserver won't start. Complains MariaDB is outdated. I don't use MariaDB

### ISSUE THREAD

**Issue by cherbert** [TrinityCore/TrinityCore#28086]
```
MySQL client library: 10.3.34
MySQL server ver: 5.7.37
Connected to MySQL database at 127.0.0.1
TrinityCore does not support MariaDB versions below 10.2.9 (found id 50737, need id >= 100209), please update your MySQL server

```

I have been pulling updates for over a year now without issues. (3.3.5). I come to do an update yesterday. Do the usual cmake, make, make install and now I get the above error launching authserver. (Same with worldserver)

I don't use MariaDB and never have. My MySQL server is 5.7 as it always has been running on Ubuntu 20.04.4 LTS

**Comment by MaxtorCoder** [comment]
Please fill in the issue template.

**Comment by damaex** [comment]
I'm going to test this later today.

**Comment by acidmanifesto** [comment]
Im using mysql 5.7.48 and have no issues with 335.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/27758
