### ISSUE TITLE
problem of sunwell boss Kalecgos

### ISSUE THREAD

**Issue by WowChenEd** [TrinityCore/TrinityCore#28101]
### Description

Cannot be transmitted to Sathrovarr the Corruptor

Kalecgos disapper when it starts to send me and the combat is over.

### Expected behaviour

the player should be transmitted to Sathrovarr currectly

### Steps to reproduce the problem

go to the sunwell raid and fight with boss Kalecgos

### Branch

3.3.5

### TC rev. hash/commit

None

### Operating system

win 10 x64

### Custom changes

transmog 
npcbot

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/24512

**Comment by WowChenEd** [comment]
> #24512

i am sorry.
i can't find solution in https://github.com/TrinityCore/TrinityCore/issues/24512

**Comment by Faq** [comment]
He just forgot to add "dublicate of". As issue is still open, no solution yet.

**Comment by WowChenEd** [comment]
> He just forgot to add "dublicate of". As issue is still open, no solution yet.

yes thank you. and i find another duplicate one #27904
