### ISSUE TITLE
DB/Zone : The Wandering Isle - Start zone - Part 2

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28119]
### Description

Starting Zone Repair - Part 2

### SQL fix

```sql
https://gist.github.com/shamage/3748009741777f9ae8c212e2587b92b2
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 47a5902b29b9+ 2022-07-12 00:35:24 +0200 (master branch)

**Comment by Naddley** [comment]
pls add .sql to the name of the gist, so its easier to read :)

**Comment by shamage** [comment]
> pls add .sql to the name of the gist, so its easier to read :)

solved :)

**Comment by mdX7** [comment]
First of all, you do not require the `SET @CGUID/@OGUID` lines when you are not spawning something new, so we can just remove them.
Secondly when assigning ScriptNames to creatures you either only do it for the entry itself OR the guid, not both. Assigning a ScriptName to a GUID (in creature table) is only used if one specific creature requires this script. When assigning ScriptName in creature_template the script will be used by all spawns of that creature.
In general the assignment of the script should also happen in the related PR where the script is actually implemented (so you should add a sql file to `sql/updates/world/master/` directory and name it something like `9999_99_99_99_world.sql` the merging maintainer will rename it before merging then.

Anything `playercreateinfo` related shouldn't be part of any fix related to other stuff.

Conditions without any ConditionTypeOrReference should be removed aswell (those with comment 'Always') - did you use WoWDBEditor and I should blame bandysc? :D

Related to `Aspiring Trainee` this will likely not work (yet), gotta investigate a bit further how we can handle it.

And about the Amberleaf Scamp `creature_template_addon` change, I'm quite sure I already fixed all of them in your last sql fix about The Wandering Isle.

Didn't test stuff ingame yet, will do as soon as I have a solution for Aspiring Trainees

**Comment by mdX7** [comment]
added to #28128
