### ISSUE TITLE
[3.3.5] Core/Creature Saviana Ragefire

### ISSUE THREAD

**Issue by Freeman256** [TrinityCore/TrinityCore#28121]
### Description

If you kill the boss [Saviana Ragefire](https://www.wowhead.com/npc=39747/saviana-ragefire) while she is flying over the lake to cast the [Conflagration](https://www.wowhead.com/spell=74452/conflagration) ability, the boss's corpse will remain in the air above the lake, making it impossible to loot.

![WoWScrnShot_071622_114258](https://user-images.githubusercontent.com/73786888/179348171-8bbc1c8c-8bb5-42a6-8c93-ce36c400efd9.jpg)
![WoWScrnShot_071622_114305](https://user-images.githubusercontent.com/73786888/179348172-577f8ccf-eeac-448e-967d-ce2f21c791ca.jpg)

### Expected behaviour

After killing the boss, her corpse should fall to the shore or to the bottom of the lake in such a way that it can be looted.

### Steps to reproduce the problem

1. Enter [The Ruby Sanctum](https://www.wowhead.com/zone=4987/the-ruby-sanctum) (25p, Her);
2. Attack boss [Saviana Ragefire](https://www.wowhead.com/npc=39747/saviana-ragefire) and try to kill her at the moment when she flies to the lake to use her ability [Conflagration](https://www.wowhead.com/spell=74452/conflagration);
3. Look at how the corpse of the boss was left "lying" in the air, and understand that due to the inability to loot the corpse, you will lose about 150 gold.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/444928f3c5fb51056321c9fe554743e25354de27
TrinityCore rev. 2022-07-15 ‏‎‏‎20:09:03 +0300 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Win7 SP1 x64 with all updates (build 6.1.7601).

### Custom changes

Manually added or replaced lines from these patches:
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/6601b2accc11fd63b0bffbcc0b8d3840b198e6a7
+
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/5f570e0a025ccb5950e8ff17b48722127ee81288
+
https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/b85bf0da62b3ec7fb3f2c1d22a08e3e9c3e3bfca

I use HD textures and models from the 6.x.x client, which enthusiasts were able to extract and make in the form of a patch for client 3.3.5. Also on the server side, I changed the drop probability of some items, and also increased the maximum stack size for some items.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/8204

**Comment by Freeman256** [comment]
Now quests [Blinding the Eyes in the Sky](https://www.wowhead.com/quest=13313/blinding-the-eyes-in-the-sky), [Keeping the Alliance Blind](https://www.wowhead.com/quest=13331/keeping-the-alliance-blind), [Get the Message](https://www.wowhead.com/quest=13314/get-the-message) and [Capture More Dispatches](https://www.wowhead.com/quest=13333/capture-more-dispatches) work perfectly: flying NPCs fall down when they die and can be looted. Maybe there is a way to use the code of these NPCs for generally all (flying) NPCs in the game?
