### ISSUE TITLE
Support MariaDB as soon as possible

### ISSUE THREAD

**Issue by jojoax** [TrinityCore/TrinityCore#28126]
### Description

>> TrinityCore does not support MySQL versions below 5.1Speicherzugriffsfehler (Speicherabzug geschrieben)

### Expected behaviour

Running!

### Steps to reproduce the problem

Use a common Arch Linux with on board Maria DB, MySQL is not recommended anymore.

### Branch

master

### TC rev. hash/commit

4b92f09fec7d6f8d70cc91f9bee6eaf51616e478
Author: Shauren <shauren.trinity@gmail.com>
Date:   Fri Jul 15 21:31:03 2022 +0200

    Core/Transports: Initialize stoppable transports at start of path

### Operating system

All systems

### Custom changes

none, fresh pull

**Comment by Shauren** [comment]
no

**Comment by jojoax** [comment]
**This is - technically spoken - really nonsens.**

If I Patch out those erraous Version Checks, the Server runns perfectly.
So why keeping this rubnbish in code?

**Comment by acidmanifesto** [comment]
> **This is - technically spoken - really nonsens.**
> 
> If I Patch out those erraous Version Checks, the Server runns perfectly.
> So why keeping this rubnbish in code?

Have you considered doing a pr since you stated you have a working solution?

**Comment by Shauren** [comment]
> **This is - technically spoken - really nonsens.**
> 
> If I Patch out those erraous Version Checks, the Server runns perfectly. So why keeping this rubnbish in code?

MariaDB advertised drop-in compatibility with mysql is really nonsense. MariaDB server may return different column types in query result metadata compared to MySQL server and because it all compiles, you get an illusion of compatibility but because all of our code is written against MySQL server, you may be silently corrupting values inside your database

**Comment by TobiMiller** [comment]
@Shauren:

I know this thread and your thoughts about MariaDB. I've tried it anyway :D compiled but on runtime it tells me that i use the wrong client version (MySQL 3.2.8, but it is MariaDB 3.2.8). Is the Wiki just outdated? Why does it mention mariadb?
https://www.trinitycore.info/en/install/requirements/linux

---

apt-get install git clang cmake make gcc g++ lib**mariadb**client-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev **mariadb**-server  lib**mariadb**-client-lgpl-dev-compat p7zip
