### ISSUE TITLE
The problem is in the object after which the server stops working

### ISSUE THREAD

**Issue by MegaserverRU** [TrinityCore/TrinityCore#28139]
### Description

Hello, the server crashes, swears at this file Transport.cpp
Line 45

The problem is in the object after which the server stops working 
SQL World - gameobject_template
entry - 201580 name The Skybreaker

How can I fix this problem?
![КРАШ](https://user-images.githubusercontent.com/98691968/179931909-c799df6f-6e29-4990-8a82-f6b70a6c2485.png)

### Expected behaviour

Hello, the server crashes, swears at this file Transport.cpp
Line 45

How can I fix this problem?
![КРАШ](https://user-images.githubusercontent.com/98691968/179932138-a2856db9-6273-471b-98c1-fe6746eaebe8.png)

### Steps to reproduce the problem

The problem is in the object after which the server stops working 
SQL World - gameobject_template
entry - 201580 name The Skybreaker
![КРАШ](https://user-images.githubusercontent.com/98691968/179933358-27a1551c-1b9c-44a6-877d-a59cb4e790c2.png)

### Branch

3.3.5

### TC rev. hash/commit

Hello, the server crashes, swears at this file Transport.cpp
Line 45

The problem is in the object after which the server stops working 
SQL World - gameobject_template
entry - 201580 name The Skybreaker

How can I fix this problem?
![КРАШ](https://user-images.githubusercontent.com/98691968/179931909-c799df6f-6e29-4990-8a82-f6b70a6c2485.png)

### Operating system

Windows 7 x64

### Custom changes

Installed patches Transmog, NPCBots, Arena 1v1.

**Comment by jackpoz** [comment]
> TC rev. hash/commit

could you please fill this ? could you try without custom patches but just stop TC ?

**Comment by Ovahlord** [comment]
then compile in debug and provide a crash log

**Comment by MegaserverRU** [comment]
> затем скомпилируйте в debug и предоставьте журнал сбоев

I have already shown you mine in the magazine, the same thing shows as in the screenshot

**Comment by Faq** [comment]
@MegaserverRU check in example issue how looks attached crash log https://github.com/TrinityCore/TrinityCore/issues/26643

**Comment by Shauren** [comment]
im going to blame npcbots
