### ISSUE TITLE
Achievements Statistic 'First Aid Skill' displaying Incorrect Value

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#28130]
### Description

There is a bug in the Achievements system where the First aid skill statistic shows as 300/0. It should be 300/450. 

300 is just an example of the players current skill level in that profession, it can happen at any skill level.

The maximum should always be 450 just like every other profession such as Cooking and Fishing.

The bug occurs on all levels of First Aid from Apprentice to Grand Master.

### Expected behaviour

As stated above, the statistic value should be displaying as 300/450 not 300/0. 450 is the maximum skill level possible for that profession.

### Steps to reproduce the problem

1. Before logging into your account, ensure your account has account level three.
2. Create a fresh character or use an existing character that does not currently obtain First Aid.
2. Use the command .learn all recipes first aid - This will train you First Aid maxed out with all recipes.
3. Check the Achievements > Statistics > First aid skill and notice the value displaying as 450/0.

Note: This also occurs if levelling your First Aid natually in the game. My Death Knight has 300 (max for Artisan) and that also displays as 300/0 in the Statistics panel of Achievements.
### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. a041ac4677d4 2022-07-13 14:19:08 +0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows Server 2016 Datacentre

### Custom changes

None

**Comment by Gilroes** [comment]
3.3.5, achievements tag, maybe?

**Comment by CraftedRO** [comment]
86551ba71669712cadf82f2dc1f0c5481f0fba1b Cannot reproduce: https://youtu.be/xHlYEu-VM7Y
