### ISSUE TITLE
[MSVC][std:c++latest] TrinityCore failed to build with error C2440

### ISSUE THREAD

**Issue by QuellaZhang** [TrinityCore/TrinityCore#28136]
### Description

TrinityCore failed to build with error C2440 with MSVC under /std:c++latest mode on MSVC. The commit we use is 8f537b9. Could you please take a look? Thanks.

### Expected behaviour

Build successfully.

### Steps to reproduce the problem

1. open VS2022 x86 tools command
2. git clone https://github.com/TrinityCore/TrinityCore F:\gitP\TrinityCore\TrinityCore
3. set _CL_= /std:c++latest
4. mkdir F:\gitP\TrinityCore\TrinityCore\build_amd64
5. cd F:\gitP\TrinityCore\TrinityCore\build_amd64
6. set MYSQL_ROOT=F:\tools\mysql_5_7_35\mysql-5.7.35-winx64
7. set BOOST_ROOT=F:\tools\boost_1_77_0\x64
8. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DSCRIPTS=dynamic -DTOOLS=True -DOPENSSL_ROOT_DIR=F:\gitP\TrinityCore\tools\OpenSSL\OpenSSL-Win64 -DCMAKE_BUILD_TYPE=Release ..
9. msbuild /m /p:Platform=x64 /p:Configuration=Release TrinityCore.sln /t:Rebuild

### Branch

master

### TC rev. hash/commit

8f537b9

### Operating system

Windows

### Custom changes

diff --git a/src/server/scripts/Commands/cs_rbac.cpp b/src/server/scripts/Commands/cs_rbac.cpp
index 4412082ae9..e329840851 100644
--- a/src/server/scripts/Commands/cs_rbac.cpp
+++ b/src/server/scripts/Commands/cs_rbac.cpp
@@ -35,7 +35,7 @@ EndScriptData */
 
 struct RBACCommandData
 {
--    RBACCommandData(RBACCommandData const&) = delete;
++    // RBACCommandData(RBACCommandData const&) = delete;
     ~RBACCommandData()
     {
         if (needDelete)

**Comment by Shauren** [comment]
We don't support /std:c++latest, after all it is considered experimental by msvc
