### ISSUE TITLE
DB/Creature: Gerard Tiller has incorrect quest icon

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#28131]
### Description

[Gerard Tiller](https://www.wowhead.com/npc=255/gerard-tiller) is displaying an incorrect quest icon for [Give Gerard a Drink](https://www.wowhead.com/quest=16/give-gerard-a-drink). 

<details>

This is current Master repo

![image](https://user-images.githubusercontent.com/66294837/179486308-e017798d-9770-4639-ac4f-99d8a9a99f7a.png)

</details>

### Expected behaviour

Gerard's correct icon for this quest is a blue '?' since quest is repeatable at any given time (trade water for an apple).

<details>

![image](https://user-images.githubusercontent.com/66294837/179486247-ce058613-7221-4acb-a9d2-8e7e3a0555c0.png)

</details>

### Steps to reproduce the problem

1. Head to Gerard's location
2. NPC will have a yellow ! above him
3. Optional: Complete the instant quest, icon remains the same

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 26d757946f4e 2022-07-17 21:25:10 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 7 x64

### Custom changes

None

**Comment by Naddley** [comment]
f774c4e - Seems to work now.
