### ISSUE TITLE
Stuck on FindMap with battlegrounds

### ISSUE THREAD

**Issue by Golrag** [TrinityCore/TrinityCore#28154]
### Description

While testing some stuff with battlegrounds I get stuck entering them.
Put freeze timer on 10seconds

https://gist.githubusercontent.com/Golrag/26ccaa1841f31d7eb5ca49d72aa56351/raw/d2f6e32f75b9ebf9654460687110cc15d78b0c3c/stuck_findmap.txt

### Expected behaviour

Should enter battlegrounds without issue

### Steps to reproduce the problem

1. debug bg
2. queue up for eye of the storm
3. enter battleground - loading screen stuck, core stuck

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/927072457831451eebe1d92c7120fe541f942194

### Operating system

Windows 11 pro

### Custom changes

Have some custom SQL for cosmetic spawns & scripts in arathi basin which I will share when I deem them good enough

**Comment by Shauren** [comment]
have fix, will push soon
