### ISSUE TITLE
Mass creature spawn on map 530

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#28150]
### Description

Having high spawn numbers on map 530 on commit 53cc21b1b45e11ba9358df3281cfa2b021fb1ea0 , possible issue is from last few commits. See grafana from below

![Mass spawn on map 530 -1](https://user-images.githubusercontent.com/92148/180587042-261d8a68-ad1e-48aa-b535-8e0ca1684e9d.png)

![Mass spawn on map 530 -2](https://user-images.githubusercontent.com/92148/180586704-dd9c5137-1de4-41c8-a1fe-96a352207443.png)

### Expected behaviour

Spawn as normal and should despawn after.

### Steps to reproduce the problem

NA

### Branch

3.3.5

### TC rev. hash/commit

commit 53cc21b1b45e11ba9358df3281cfa2b021fb1ea0

### Operating system

debian 11

### Custom changes

NA

**Comment by Jildor** [comment]
Could you use command .debug objectcount 530 to check what creatureId can be?

**Comment by Faq** [comment]
@ckegg why closed?

**Comment by ckegg** [comment]
I had this https://github.com/TrinityCore/TrinityCore/issues/25003 imported and found 19692 and 20392 will grow only after 8 hours. I still have no clue right now and I think it is not related to core

**Comment by ckegg** [comment]
I found something interesting that SmartAI will not run on call SMART_ACTION_CALL_TIMED_ACTIONLIST when you are out from the grid? See video below. I will keep this issue closed but good for anyone wants to look into it.
[https://mega.nz/file/9FAHhT6L#-OAousyOget2-Kh9ZoYcp-hnUL6oBm9kgfo0W2IKV9U](url) (Video is edited and removed the 3 min wait time)
