### ISSUE TITLE
Incorrect starting levels for GMs

### ISSUE THREAD

**Issue by MrIronLife** [TrinityCore/TrinityCore#28165]
### Description

https://github.com/TrinityCore/TrinityCore/commit/4e864848284443428cd7c12d70e64f68cefe84d7

The new code applied in this commit is broken and will give CONFIG_START_DEATH_KNIGHT_PLAYER_LEVEL or higher to the gm character and not the actual value stored in CONFIG_START_GM_LEVEL if death knight class wasn't picked on character creation.

I ended up reverting to the previous code and it worked perfectly.

`uint32 gm_level = sWorld->getIntConfig(CONFIG_START_GM_LEVEL);`

### Expected behaviour

If player is a GM then assign CONFIG_START_GM_LEVEL to the player and if the player is a gm and making a death knight then assign CONFIG_START_DEATH_KNIGHT_PLAYER_LEVEL if it's greater than CONFIG_START_GM_LEVEL

### Steps to reproduce the problem

Step 1. Set the CONFIG_START_GM_LEVEL to lower than 55
Step 2. Create a new non death knight character on a gm account

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 4b309f7ee558+ 2022-07-28 01:47:53 +0000 (master branch) (Win64, Release, Dynamic)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.73.0
Using MySQL version: 50735
Using CMake version: 3.21.1
Compiled on: Windows
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 657797442 bytes
mmaps directory located in ./mmaps. Total size: 2102976272 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.22061
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by jackpoz** [comment]
thanks for the bug report, I'm checking this issue
