### ISSUE TITLE
Human starting area quest "Fear no evil" broke

### ISSUE THREAD

**Issue by kakukkokkal** [TrinityCore/TrinityCore#28163]
### Description

The quest in Northshire Abbey, "Fear no evil" broke a couple of days ago, Injured Stormwind Infantries cannot be interacted with to be healed. 

### Expected behaviour

Infantries should be able to be right clicked and healed.

### Steps to reproduce the problem

1. Create human hunter character (I've tested with a hunter)
2. Get quest (63447) (https://www.wowhead.com/quest=63447/fear-no-evil)
3. Try to interact with an Injured Stormwind Infantry (https://www.wowhead.com/npc=50047/injured-stormwind-infantry)

### Branch

master

### TC rev. hash/commit

6713fa4c93f87af351f3ee65c1ff36b52ea85ddb

### Operating system

Ubuntu 22.04 (docker)

### Custom changes

None

**Comment by offl** [comment]
Someone removed all SAI scripts, I was dreaming of this day but.. differently
