### ISSUE TITLE
Ulduar - Flame Leviathan encounter not working

### ISSUE THREAD

**Issue by Krutok** [TrinityCore/TrinityCore#28174]
### Description

After I kill the 2 big adds the boss comes but he keeps resetting and not attacking. You can see that in the buffs the boss gets. Hard mode is therefore active.

I made a video where you can see the boss constantly backing down and in the chat you can also see him being inundated with his talk

### Expected behaviour

After the pull, he attacks the player and gets his buffs in hardmode. The players sit normally in the vehicles and void zones and adds appear

### Steps to reproduce the problem

I made a video to reproduce it: https://www.youtube.com/watch?v=2279eJwYahY So go to Ulduar no matter if 10 or 25 players activate hard mode or normal mode and go to the boss kill the 2 big adds wait until he Boss appears and pull the boss and see the result in the video

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 5bc0a68f74de+ 2022-08-02 11:03:10 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debia 11

### Custom changes

npcbots_3.3.5 branch; https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots

**Comment by danjohnso** [comment]
I have noticed this too when you are not in a vehicle.  Trying being in a vehicle there and seeing if the encounter engages properly

**Comment by Krutok** [comment]
Yes, with a vehicle, the boss reacts quite normally. Then the ticket is done for now.
