### ISSUE TITLE
DB/Spawns NPE Faction based spawns Part 1

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28175]
### Description

Spawn some Neutral NPCs splitted for Horde and Alliance

-> Birds dont have WPs cause of nyi spline/cyclic

### SQL fix

```sql
https://gist.github.com/Naddley/d836a2954473dc28d21762b403b17f13
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 6b944b9e5696

**Comment by mdX7** [comment]
Maybe we should split the groups a bit. Something generic for each faction e.g. npcs which do not die and trigger npcs and another one for dynamic spawn related npcs (aka killable npcs and quest related gobs) ref `SPAWNGROUP_FLAG_DYNAMIC_SPAWN_RATE` flag?

so something along:
```
SPAWNGROUP_ALLIANCE_GENERIC
SPAWNGROUP_ALLIANCE_DYNAMIC
SPAWNGROUP_HORDE_GENERIC
SPAWNGROUP_HORDE_DYNAMIC
```

**Comment by Naddley** [comment]
- Gist updated -
