### ISSUE TITLE
DB/Creature: Added scaling data for various npcs

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#28177]
### Description

Kalindor
- [X] Durotar
- [X] Mulgore
- [X] Darkshore
- [X] Azshara 
- [X] Northern Barrens
- [X] Southern Barrens
- [X] Ashenvale
- [X] Felwood
- [X] Dustwallow Marsh
- [X] Stonetalon Mountains
- [X] Desolace
- [X] Feralas
- [X] Thousand Needles
- [X] Tanaris
- [X] Un'Goro Crater
- [X] Winterspring
- [X] Silithus
- [X] Uldum

Zone Legion
- [X] Azsuna
- [X] Val'sharah
- [X] Stormheim
- [X] Suramar
- [X] Argus

Zone BFA
- [X] Tiragarde Sound
- [X] Drustvar
- [X] Stormsong Valley
- [X] Zuldazar
- [X] Nazmir
- [X] Vol'dun
- [X] Nazjatar

It can be added to this commit: https://github.com/TrinityCore/TrinityCore/issues/21438

### SQL fix

```sql
https://gist.github.com/osleyder85/8e658adc76be66178cc55951a89dd82b
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 6b944b9e5696 2022-08-02 22:25:07 +0200
Using SSL version: OpenSSL 1.1.1o 3 May 2022 (library: OpenSSL 1.1.1o 3 May 2022)
Using Boost version: 1.79.0
Using World DB: TDB 925.22071
Using enUS DBC Locale

**Comment by mdX7** [comment]
did you parse with `DBEnabled = false`? I actually expected at least some UPDATE statements

**Comment by osleyder85** [comment]
> did you parse with `DBEnabled = false`? I actually expected at least some UPDATE statements

Yes, I have them, I'm going to update the sql and let you know.

**Comment by osleyder85** [comment]
> did you parse with `DBEnabled = false`? I actually expected at least some UPDATE statements

Several of the updates were improved in this commit 08fd31c79d0f89fd59e3a0bee67f48666d94d969, so I had skipped the updates.

**Comment by mdX7** [comment]
the commit you linked updated wdb data (_template) but you are updating template_scaling here, so they arent related tho

**Comment by osleyder85** [comment]
> the commit you linked updated wdb data (_template) but you are updating template_scaling here, so they arent related tho

Sorry, I made the wrong commit, it was in this 818c288564bf0e7b63dfbb48a7734d8de0da0b63.
I am already reviewing the updates one by one, to eliminate the ones that were improved with your commit.

**Comment by mdX7** [comment]
i'm just recommending to simply apply our commits before you parse the sniff and then parse them with DBEnabled=true setting in wpp. Then it will check against the current db and generate UPDATE statements or INSERT statements (depending if the row already exists or not)
