### ISSUE TITLE
The Missing Diplomat: Bursting down Dashel Stonefist too fast will not trigger him to end fighting

### ISSUE THREAD

**Issue by YunataSavior** [TrinityCore/TrinityCore#28182]
### Description

See title. Dealing too much damage at the start will not trigger him to end the fight. He'll continuously hit you while sitting at 1 HP.

### Expected behaviour

He must end the fight immediately once low health.

### Steps to reproduce the problem

1. Accept this quest: https://wotlkdb.com/?quest=1447
2. Burst down Dashel immediately once he becomes aggroed.
3. Observe what happens.

### Branch

3.3.5

### TC rev. hash/commit

dfd1692e3136+

### Operating system

Linux

### Custom changes

None, besides using a hack that gives me permanent buffs that you can give other players.

**Comment by Krutok** [comment]
I've accepted the quest. But nothing happens the NPC remains friendly

**Comment by Krutok** [comment]
Here my fix try this and see my Video i hope its help you

**Comment by YunataSavior** [comment]
Krutok,

Can you test this with an instant cast spell that brings him down to 1 HP as soon as he becomes hostile?

**Comment by Krutok** [comment]
> Krutok,
> 
> Can you test this with an instant cast spell that brings him down to 1 HP as soon as he becomes hostile?

When I take my normal spells from the caster, which is now close to 2,000 dps, it's down and working right away. You may not use GM spells. Whether dots or instant magic, everything worked for me. try it yourself

**Comment by Killyana** [comment]
The issue is there's 2 secs required to let the first action list to end and then the one with health PCT can start, if put the npc bellow 15% heal before this 2 secs the second action list will not be triggered
``` sql
UPDATE `smart_scripts` SET `event_param1`=0 AND `event_param2`=0 WHERE `entryorguid` = 496100 AND `source_type`=9 AND `id`=3;
