### ISSUE TITLE
CMake and Boost errors again

### ISSUE THREAD

**Issue by artDeil4ek** [TrinityCore/TrinityCore#28184]
### Description

Could NOT find Boost (missing: system filesystem program_options iostreams
  regex) (found suitable version "1.78.0", minimum required is "1.73")

### Expected behaviour

Hi guys.
  I've been using Trinity for quite a long time, as many bugs as I've gone through, but this is something new. I installed OpenSSL NOT lite x32 and x64, MySQL and etc. Boost 1.78.0 x64, specified the variable "BOOST_ROOT" in the paths - and so "c:/local/boost_1_78_0 " and that's it "C:\local\boost_1_78_0", but at least he doesn't care! Once again, I installed everything as usual, as I did many times ago. Here's what CMake outputs:
  **fatal: not a git repository (or any of the parent directories): .git
CMake Error at cmake/genrev.cmake:116 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)**

~ ~ ~ ~ ~ ~

**Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Check if compiler accepts -pthread
Check if compiler accepts -pthread - no
Found Threads: TRUE  
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: system filesystem program_options iostreams
  regex) (found suitable version "1.78.0", minimum required is "1.73")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
  dep/boost/CMakeLists.txt:38 (find_package)**

What does he want? And how can i find this pthread.h? Using VS Community 2019 and 2022.
Help

### Steps to reproduce the problem

None

### Branch

3.3.5

### TC rev. hash/commit

3.3.5a

### Operating system

Windows 10

### Custom changes

None

**Comment by artDeil4ek** [comment]
In previous topics, the complaint was the same and the solution was to use git clone instead of downloading zip
I'll try this

**Comment by shamage** [comment]
what version do you have  TC rev. hash  ?

**Comment by artDeil4ek** [comment]
> what version do you have TC rev. hash ? ( 3.3.5a not a hash version ! )

I downloaded the latest build

**Comment by artDeil4ek** [comment]
[https://i.ibb.co/M9w2cdQ/2022-08-09-10-44-35.png](url)
screenshot

**Comment by Aokromes** [comment]
it's not source bug, instead bad configuration on your side.
ie, not installed mysql.

**Comment by artDeil4ek** [comment]
Enter password: ****
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.30 MySQL Community Server - GPL
Copyright (c) 2000, 2022, Oracle and/or its affiliates.

**Comment by acidmanifesto** [comment]
Did you set your boost path in your enviromental variable?

**Comment by Shauren** [comment]
Definitely installed wrong boost package (msvc 14.x, x must be 2 with VS 2019 and 3 with VS 2022)
