### ISSUE TITLE
DB/Spawns add Alliance and Horde Questgiver for scout Quilboar Briarpatch

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28180]
### Description

add Questgiver spawns for Quilboar Briarpatch

-> (Breka and Garrick Phasing in Abandoned Camp still not yet done cause of different Class sparring Quests)

### SQL fix

```sql
https://gist.github.com/Naddley/145533e1826bb7e3033dfb5325fbf83e
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 6b944b9e5696

**Comment by mdX7** [comment]
recheck conditions, you are using the conditions of horde quests for alliance npcs, rest seems fine

e.g.
https://www.wowhead.com/quest=59935/northbound
https://www.wowhead.com/quest=55173/northbound
