### ISSUE TITLE
Issue with eye of azshara portal/areatrigger_create_properties

### ISSUE THREAD

**Issue by cadafy** [TrinityCore/TrinityCore#28190]
### Description

The problem is that when it came to the front of the eye of azshara portal it shows on the world server what photo number 2 shows. Then I try to enter the portal and it does nothing and the world server redials what is shown in the photo 4. Could someone help me to solve this problem?
![2](https://user-images.githubusercontent.com/1677095/183498821-cdb4f65d-fb2a-4623-afde-0223e84df04d.png)
![3](https://user-images.githubusercontent.com/1677095/183498875-6823459c-c2c1-4f1d-9420-ead75f3d3f79.png)
![4](https://user-images.githubusercontent.com/1677095/183499000-693e5e0b-669d-497d-8d8e-a671d42bf6db.png)
![5](https://user-images.githubusercontent.com/1677095/183499017-13cbd96b-994a-4603-8bb5-4de2ca33c12b.png)

### Expected behaviour

I should enter the eye of azshara portal

### Steps to reproduce the problem

https://www.wowhead.com/eye-of-azshara-dungeon

### Branch

master

### TC rev. hash/commit

TrinityCore rev. +  (+ branch) (Win64, Debug, Static) (worldserver-daemon(no longer using)
TC>TrinityCore rev. 5c5f3d5376a5+ 2021-11-11 01:59:25 +0100 (master branch) (Win64, Debug, Static) (worldserver-daemon) wearing
![1](https://user-images.githubusercontent.com/1677095/183499069-2301261c-2c9f-4aed-a8da-c33197b01970.png)
)

### Operating system

Windows 10 x64

### Custom changes

ninguno

**Comment by mdX7** [comment]
Two things first.

1. Keep in mind you are using an outdated version (9.1.5.x), we cannot guarantee support for anything below latest patch.

> TrinityCore rev. + (+ branch) (Win64, Debug, Static) (worldserver-daemon

2. `rev. +` is an invalid hash and does not exist in our repostiory here, [proof](https://github.com/TrinityCore/TrinityCore/commit/+). This actually shows us at which commit your core currently is and is important to us for further assistance. A valid commit hash would be something like [4f7a7e92c8455c0bfe5b2431654915dff5a481b0](https://github.com/TrinityCore/TrinityCore/commit/4f7a7e92c8455c0bfe5b2431654915dff5a481b0) (which is the latest commit on master branch at the time of writing this text)

The fix the error messaged you have there: Add the related `areatrigger_create_properties` rows to db so the spawned areatriggers do not error anymore.

In clean tc we do not have any areatrigger spawned for the Eye of Azshara entrance yet, so the portal isn't working, not even meetingstone or portal effect is spawned:
![image](https://user-images.githubusercontent.com/12143653/183552784-42663855-f82d-4d49-8b14-adce320c1264.png)

**Comment by cadafy** [comment]
Thanks for your help,
I was verifying the files and it does not have a hash, it only has the + sign.
This Core is from a member here. His name is funjoker. I'll work with the related DB rows and let you know.

**Comment by funjoker** [comment]
Wat? My core?
I never sent anything. oO
