### ISSUE TITLE
Upper Blackrock Spire coliseum fight CANT COMPLETE vs Warchief Rend Blackhand and Gyth 

### ISSUE THREAD

**Issue by BraisMarteloLopez** [TrinityCore/TrinityCore#28209]
### Description

Upper Blackrock Spire coliseum fight vs Warchief Rend Blackhand and Gyth is totally bugged after defeat Gyth all stops, no more scrips and you are blocked on that hall.

### Expected behaviour

Defeat Warchief Rend Blackhand and Gyth to continue.

### Steps to reproduce the problem

Go to Upper Blackrock Spire and enter on the coliseum hall

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 6e37438e5dad 2022-08-19 11:14:07 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/Users/Marisa/Downloads/wow_own/Ac-Web Repack V-0.9 64bit_a/Ac-Web Repack V-0.8 64bit/Core/worldserver.conf.
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.73.0
Updating Auth database...

### Operating system

Windows 10

### Custom changes

None

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15101
