### ISSUE TITLE
friendly NPCs and own character kneel all the time

### ISSUE THREAD

**Issue by slash-design** [TrinityCore/TrinityCore#28212]
### Description

In each zone/map, friendly NPCs and your own character kneel all the time.

### Expected behaviour

should not be :)

### Steps to reproduce the problem

- Compile a fresh Core
- set up with actuall Databases
- create a new Character
- log in
- see... all friendly NPCs and own Character kneel down
- walk a few meters....
- Character kneels

### Branch

master

### TC rev. hash/commit

0eff4ec7df6d

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/28211
