### ISSUE TITLE
Core/Player: All players appear crouched and after walking and stopping they automatically sit back down

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#28211]
### Description

All players appear crouched and after walking and stopping they automatically sit back down

### Expected behaviour

Players must stand and after walking and stopping remain standing, only crouch when AFK

### Steps to reproduce the problem

1. Create any player
2.  Enter world
3. Walk player

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0eff4ec7df6d+ 2022-08-21 00:09:51 +0000

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by mdX7** [comment]
reextract db2
