### ISSUE TITLE
DB/Silverpine: added spawns for phase 264 in Forsaken High Command

### ISSUE THREAD

**Issue by Nyr97** [TrinityCore/TrinityCore#28245]
### Description

^

### SQL fix

```sql
https://gist.github.com/Nyr97/8bda62a7e60399fd37a7e7b07592e75b
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/678f7a461504ec88074307f4dab0ddfd34ec0881

**Comment by mdX7** [comment]
`PhaseId` is an integer field, you should not put them into quotes

**Comment by Nyr97** [comment]
fixed!
