### ISSUE TITLE
DB/Kezan handle Chapter 1 - 7 Phases

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28249]
### Description

Handle Phase 378 - 384 (Chapter 1 up to Chapter 7)

### SQL fix

```sql
https://gist.github.com/Naddley/a0d105f20c7640c16d646b13aa5b4fbb
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. e9d083a2ee59

**Comment by funjoker** [comment]
Syntax looks good
