### ISSUE TITLE
Spell/Warlock: Backlash shoud proc while shielded

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28246]
### Description

ATM [Backlash](https://www.wowhead.com/wotlk/spell=34939/backlash) doesn't proc while shielded tested with Voidwalker Sacrifice.
Most likely is same for power word shield but didn't tested yet.

https://user-images.githubusercontent.com/24683355/190147576-fa1e11c2-9526-47fb-8296-7093313c6922.mp4

### Expected behaviour

Backlash shoud proc while shielded with Voidwalker Sacrifice shield and most likely with Power Word Shield too.

Proof 1 : [Cobrak video](https://youtu.be/TJQn1OVFCjw?t=72)
Proof 2 : [Wowhead comment](https://www.wowhead.com/wotlk/spell=34939/backlash#comments:id=195712)

### Steps to reproduce the problem

Create a warlock with Destruction specialization and 3/3 Backlash talent.
Summon Voidwalker
Use Sacrifice then enter in a bunch of mobs that do melee damage.
Notice Backlash talent only procs when Sacrifice fade out.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 5ec5e1e1d0bf 2022-09-08 18:19:15 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian I guess

### Custom changes

None I guess

**Comment by eXPeRi91** [comment]
```
class spell_warlock_backlash : public SpellScript
{
    public:
        spell_warlock_backlash() : SpellScript("spell_warlock_backlash") { }

        bool CheckProc(ProcEventInfo& eventInfo)
        {
            // Check if the target is shielded
            if (eventInfo.GetProcTarget()->HasAuraType(SPELL_AURA_SCHOOL_ABSORB))
                return true;

            return false;
        }
};
```
Can you check this?

**Comment by Shauren** [comment]
Horrible idea, just modify HitMask in spell_proc table to include PROC_HIT_ABSORB

**Comment by eXPeRi91** [comment]
@Shauren something like that?
```
INSERT INTO `spell_proc` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `TypeMask`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `ProcFlags`, `PpmRate`, `CustomChance`, `Cooldown`)
VALUES (34939, 0, 0, 0, 0, 0, 0, 0, 0, PROC_HIT_ABSORB, 0, 0, 0, 100, 0);
```

**Comment by Jildor** [comment]
no, like that:
```sql
-- Warlock - Backlash: Should also proc with absorbs
UPDATE `spell_proc` SET `HitMask`=`HitMask`|0x00000001|0x00000002|0x00000400 WHERE `SpellId`=-34935;
```

**Comment by CraftedRO** [comment]
dc221604d997 yep, Jildor fix is working and can be merged:


https://user-images.githubusercontent.com/24683355/209945356-e992e7b9-50c2-4322-ab0d-d98d252a8524.mp4
