### ISSUE TITLE
DB/Kezan Upate some stuff in KTC Headquarters

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28252]
### Description

Update some NPCs, add waypoints and some cosmetics

### SQL fix

```sql
https://gist.github.com/Naddley/06033ca7beb411cf18ae09692ebf22b8
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. e9d083a2ee59

**Comment by Rushor** [comment]
nice!

**Comment by funjoker** [comment]
Syntax looks good.
