### ISSUE TITLE
DB/Kezan update PhaseID / PhaseGroup of some NPCs

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28250]
### Description

Update 169 PhaseID spawns to Chapter 1 378
add some PhaseGroups to some NPCs

### SQL fix

```sql
https://gist.github.com/Naddley/99d743ba9a0c19304f6596efa8ddd724
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. e9d083a2ee59

**Comment by funjoker** [comment]
Syntax looks good
