### ISSUE TITLE
DB/Creature: Stormwind City Patroller stuck in hammer animation

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#28267]
### Description

City Patroller (spawnid 313937;entry 1976) begins his Script by walking to the hero's board. He then begins a hammer animation but whilst the hammer disappears from his belt, it never appears in his hands, and from this point, he is stuck in the hammering animation stage whilst he walks back to hist post and it repeats itself (all along he's hammering nothing - with no hammer).

<details>

![image](https://user-images.githubusercontent.com/66294837/191353522-91045ee9-b12b-4a5c-8087-0eabae1ec2c6.png)

</details>

### Expected behaviour

This guard is supposed to hammer for a bit, stop, hammer reappaers on his belt again and he returns to his post in a normal walking fashion.

He then rinses and repeats.

### Steps to reproduce the problem

1. Start server
2. Go to the vacinity of the Hero's board, the Patroller will trigger his script for the first time
3. Notice he walks to the board normally with hammer on hip
4. Notice the hammer disappears from hip but he's hammering the hero's board with no hammer
5. As he walks away notice he's still making the hammering animation
6. Wait until he repeats the cycle, he's still hammering.

<details>

![image](https://user-images.githubusercontent.com/66294837/191354290-44d9fbb1-0a69-4c45-b288-549d6d6f581b.png)

</details>

### Branch

master

### TC rev. hash/commit

TrinityCore rev. c00e2e485149 2022-09-17 20:58:24 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 7 x64

### Custom changes

None

**Comment by Nyr97** [comment]
most likely an animkit or emote that's not removed upon moving, that should be it (it could also be an aura, but unlikely)

**Comment by Ovahlord** [comment]
it's because waypoint scripts have been used here. that stuff needs to be converted to sai

**Comment by shamage** [comment]
If you enter the command:
".wp show on" becomes this :  
![Ashampoo_Snap_sobota 24  septembra 2022_16h48m39s_014_](https://user-images.githubusercontent.com/7515044/192104488-a08a3199-3c89-445e-afe7-8f292b5a3f02.png)
![Ashampoo_Snap_sobota 24  septembra 2022_16h49m38s_015_](https://user-images.githubusercontent.com/7515044/192104492-72c93455-8566-44ee-ae44-b7e547050d79.png)
but when you try to enter: ".wp show off" so they don't disappear "it says not found (see image)

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/e619492a194bc09feb2fb30c50df4edbbcdc87bf  got this in 4.x already

**Comment by shamage** [comment]
> [The-Cataclysm-Preservation-Project@e619492](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/e619492a194bc09feb2fb30c50df4edbbcdc87bf) got this in 4.x already

This solution works correctly (I tested it on: rev. bc18b72d803c 2022-09-24 21:43:58 +0200 (master branch)), it is enough to modify - extend the time of the waiting period by 30 - 60 sec. (I don't remember exactly this time) and it will be like retail :)

**Comment by TQPS** [comment]
Just put this in and it works perfect. Thank you!

**Comment by shamage** [comment]
I fixed a minor cosmetic bug in SAI and included it in my update for that area.

I propose to close this issue and refer the fix to this link : https://github.com/TrinityCore/TrinityCore/issues/28365

The specific line of the corrected SAI  - [click here](https://gist.github.com/shamage/71409c789c11d22378133d921db7a562#file-sai-creature-text-sql-L150)

**Comment by mdX7** [comment]
Closed in 83a8a540aa38413e531a3f3527c0044f3055b5dc
