### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by xuehyc** [TrinityCore/TrinityCore#28260]
### Description

 _key = EVP_PKEY_new_raw_private_key(EVP_PKEY_ED25519, nullptr, keyBytes.data(), keyBytes.size());
    EVP_PKEY_get_raw_private_key(_key, privateKey, &keyLength);
    EVP_PKEY_get_raw_private_key(_key, privateKey, &keyLength);
    EVP_PKEY_get_raw_public_key(_key, publicKey, &keyLength);
    EVP_PKEY_get_raw_public_key(_key, publicKey, &keyLength);
    _key = EVP_PKEY_new_raw_private_key(EVP_PKEY_ED25519, nullptr, keyBytes.data(), keyBytes.size());

Undefined,whats wrong?

### Expected behaviour

I DONT KNOW

### Steps to reproduce the problem

I DONT KNOW

### Branch

master

### TC rev. hash/commit

I DONT KNOW

### Operating system

Windows 10 x64

### Custom changes

NO

**Comment by Shauren** [comment]
Openssl 1.0 is unsupported
