### ISSUE TITLE
Brewfest invasion

### ISSUE THREAD

**Issue by Krutok** [TrinityCore/TrinityCore#28276]
### Description

I've already searched github, but so far everything has been closed or no solution found or is already too old.

Anyway, this quest: https://www.wowhead.com/quest=12020/this-one-time-when-i-was-drunk doesn't work because the associated event doesn't exist.

This is this event: https://youtu.be/MWbQV307m9k?t=501 It starts every hour.

### Expected behaviour

Since this event does not exist, I cannot write a report about what should happen instead.

### Steps to reproduce the problem

The quest https://www.wowhead.com/quest=12020/this-one-time-when-i-was-drunk also exists in the database as the game object, but the game object only appears once you have successfully completed the event . Since this event does not exist, you cannot complete this daily quest.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. a55a566602c3+ 2022-09-09 21:48:35 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 11 64 bit

### Custom changes

NPC Bots added

**Comment by heyitsbench** [comment]
> This is this event: https://youtu.be/MWbQV307m9k?t=501 It starts every hour.
Is it not every half hour?

**Comment by Krutok** [comment]
it may be that it was every half hour. it's been a long time since i played this on the retail server

**Comment by FALL1N1** [comment]
it's every 30 minutes and the invasion depends on the nearby players, if there are many - many mole machine spawns, if less - less

**Comment by Nyr97** [comment]
I can confirm it ocurrs every XX:00 and XX:30 hour time.

**Comment by FALL1N1** [comment]
> Dup #3620 ?

yes, it is
