### ISSUE TITLE
3.3.5 Bonus armor

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28271]
### Description

While I was diging into item database comparisions I had find that TC doesn't have Bonus armor feature and instead that items does have that armor as "bulk" directly on item.

I might be wrong but I want to ask If I need to do more tests or you know something about this thing.

[Bonus armor is a secondary stat that increases armor and attack power for tanking specializations. It can be found on rings, trinkets, necklaces , and cloaks.](https://wowpedia.fandom.com/wiki/Bonus_armor)

### Expected behaviour

Probably this feature shoud be implemented.

### Steps to reproduce the problem

Idk be a tanking specialization then put a item with bonus armor like https://www.wowhead.com/wotlk/item=3835/green-iron-bracers and you shoud gain some attack power probably.

### Branch

3.3.5

### TC rev. hash/commit

5df222f0258a

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by xvwyh** [comment]
You yourself linked a wiki article that contradicts your statement. Come on, it's only two paragraphs, read both of them:
> Prior to [Warlords of Draenor](https://wowpedia.fandom.com/wiki/Warlords_of_Draenor), **bonus armor referred to extra armor** on any [cloth](https://wowpedia.fandom.com/wiki/Cloth), [leather](https://wowpedia.fandom.com/wiki/Leather), [mail](https://wowpedia.fandom.com/wiki/Mail), or [plate](https://wowpedia.fandom.com/wiki/Plate) items, or any armor that was on any other type of item, i.e. trinkets, rings, and necklaces. **This was indicated by the armor stat number appearing in green instead of the normal white.**

Which is exactly what's happening in 3.3.5 (which falls under "prior to Warlords of Draenor"). It's not a secondary stat and it provides no bonus to attack power, just extra armor.

It is already implemented in TC:
https://github.com/TrinityCore/TrinityCore/blob/9082eca660d73812844d39c57d647c4ae22d5ad5/src/server/game/Entities/Player/Player.cpp#L7537-L7538
https://github.com/TrinityCore/TrinityCore/blob/9082eca660d73812844d39c57d647c4ae22d5ad5/src/server/game/Entities/Player/Player.cpp#L7559-L7561
`ArmorDamageModifier` is not the greatest name for it, but I can assure you that this is the field that's responsible for making that armor line green in tooltips.

As for why it exists in the first place: it seems like armor was automatically generated on items based on item's type, quality and itemlevel, so this extra field was created to allow designers to modify the generated value if they wanted to. They could use it to add armor to items that don't have innately (i.e. it would be generated as 0), or to remove armor from items that did have it innately, but the designer wanted it gone.

When looking at TC's implementation, bear in mind that item_template.armor field **already includes** the extra armor, thus ArmorDamageModifier field is used for two reasons:
- To make the client color the tooltip line green
- To "split" the item's armor into two components: base armor and extra armor, and apply them to player's base armor and total armor values separately. This is done to satisfy this patchnote from 3.0.8:
  > Bonus Armor: The mechanics for items with bonus armor on them has changed (any cloth, leather, mail, or plate items with extra armor, or any other items with any armor). Bonus armor beyond the base armor of an item will no longer be multiplied by any talents or by the bonuses of Bear Form, Dire Bear Form, or Frost Presence.

There are, however, a few oddities with some items. For example, you can find many ranged weapons having positive ArmorDamageModifier values but 0 armor, as if these items were innately meant to have **negative** armor generated, and designers had to use the bonus armor to compensate and make it zero.

The first half of the aforementioned code will also behave potentially incorrectly for items that have non-zero armor but also have negative ArmorDamageModifier - it will essentially subtract the modifier again, despite it already having been applied to the item's armor before the cache was even sent from the server. Thankfully there aren't any cases where this would cause integer underflow, but it's still a potentially wrong and dangerous code that needs to be reexamined.

**Comment by CraftedRO** [comment]
ok sorry for bothering you
