### ISSUE TITLE
Core: Crash in Molten Core if you kill Garr before any of his adds

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#28274]
### Description

Disclaimer: Using Trickerer's bots

This is a long time issue that I have just used a work around.

If you kill Garr before you take down any adds, this crash occurs.

If you kill Garr AFTER most of the adds are down, this crash does NOT occur.

[Crash Log](https://gist.github.com/TQPS/3a1cc21bd2b79e97cbbf563172a31848)

### Expected behaviour

Should be able to kill Garr before his adds, without the server crashing.

### Steps to reproduce the problem

For what it's worth:
- I am level capped at 60 (via Stormwind NPC)
- I use 39 bots
- AtlasLoot is the only add on I use
- No other custom changes or alterations to server other than NPCBots
- Server is Windows 7 / Client is Windows 10

1. Go into Molten core and clear up to Garr
2. Tell bots to target Garr, ignore adds (Warlocks will banish)
3. When Garr is almost at 0 health or dead, the game should freeze in place whilst animations continue and server will pop a crash message.
4. Log back into game - you're still in Molten Core, Garr's body is not there and usually 1+ add remains on his spawn

Workaround
1. Go into Molten core and clear up to Garr
2. Tell bots to target adds, ignore Garr
3. When adds are down, focus Garr
4. Fight ends, Garr is dead, no crash, Garr can be looted.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. cefd4584ca14 2022-09-21 12:45:17 +1000 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

* This is NPCBots with TC rev. 5df222f0258a

### Operating system

Windows 7 x64

### Custom changes

Trickerer's NPCBots

**Comment by Ovahlord** [comment]
That crash is caused by your bots, not Garr.

**Comment by TQPS** [comment]
I'll log the issue with Trickerer. Thank you.
