### ISSUE TITLE
Warrior: Strange Rage decreasing rate while out of combat

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28299]
### Description

Warriors shoud lose ~ 1 rage per second out of combat, currenltly on TC its decreasing but also fast increasing , check video below:
TC:

https://user-images.githubusercontent.com/24683355/193434075-3681f9db-bf2a-4ed8-8444-4469ca83f543.mp4

WotLK classic :

https://user-images.githubusercontent.com/24683355/193433800-b5c0b8ea-ec5e-43f4-96c0-d2184e8ac478.mp4

### Expected behaviour

Warriors shoud lose ~1 rage per second out of combat.

### Steps to reproduce the problem

Create a warrior
do some rage
leave combat

### Branch

3.3.5

### TC rev. hash/commit

c1dd282c07d3

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Ovahlord** [comment]
Probably async serverside/clientside calculations.

**Comment by CraftedRO** [comment]
yea but it feels like it kinda "help" warriors a bit , not tested yet druids.

**Comment by CraftedRO** [comment]
Same for druids bear form :

https://user-images.githubusercontent.com/24683355/193562098-c4f189d8-76bd-4cf3-a7eb-b309109927ef.mp4
