### ISSUE TITLE
Warrior: Possible few base stats wrong ?

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28298]
### Description

Well I was finding that base stats are probably wrong in TC for some classes but now Il post about warrior:

TC:
![WoWScrnShot_100222_032804](https://user-images.githubusercontent.com/24683355/193433039-a2d40882-501b-4f2d-8f23-8598a4b9973a.jpg)

WotLK classic :

![WoWScrnShotwotlkclassic](https://user-images.githubusercontent.com/38561765/193433120-d6e7e776-4b8d-40a8-80a4-a94cfd310d88.png)

### Expected behaviour

Stats to be like in wotlk classic beta ?

### Steps to reproduce the problem

Create a orc warrior
Press C

### Branch

3.3.5

### TC rev. hash/commit

c1dd282c07d3

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by heyitsbench** [comment]
[This also applies to the live PTR for Wrath Classic.](https://user-images.githubusercontent.com/38561765/193433120-d6e7e776-4b8d-40a8-80a4-a94cfd310d88.png)

**Comment by CraftedRO** [comment]
ty for confirmation , I don't have acces to retail so I only gather my sources from public videos , probably its same for all classes

**Comment by CraftedRO** [comment]
```sql
-- Update ORC Warrior lvl 1 basestats to match blizzard classic WotLK
UPDATE `player_levelstats` SET `sta`=23, `spi`=22 WHERE `race`=2 AND `class`=1 AND `level`=1;
```

**Comment by CraftedRO** [comment]
Duplicate https://github.com/TrinityCore/TrinityCore/issues/19471
