### ISSUE TITLE
Crash when using GM spell Windfury Weapon

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28295]
### Description

First time I tested this spell on dk and after I noticed errors I searched about it on [Wowhead](https://www.wowhead.com/wotlk/spell=35886/windfury-weapon) I had find that this shoud be only usable on shamans so I created level 1 draenei shaman I learned all blizzard and when I casted this buff , the worldserver forced a crash.
Well I have to say I coudn't reproduce this bug but worldserver is still spamming this error after using the buff.

![windfury](https://user-images.githubusercontent.com/24683355/193403795-32ec98d9-99be-4d16-b9c6-af0c443d8cb1.PNG)

[Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/9690037/Crashes.zip)

### Expected behaviour

I guess this spell shoud be usable.

### Steps to reproduce the problem

.learn all blizzard
/cast Windfury Weapon

### Branch

3.3.5

### TC rev. hash/commit

b19d7c51f573

### Operating system

Windows 10 x64

### Custom changes

Nope

**Comment by jackpoz** [comment]
I see MapUpdater::WorkerThread calling
>00007FFB51CE2B89  00000011AC5FF9D0  ?_Winerror_message@std@@YAKKPEADK@Z+139

which looks quite suspicious. I'll take a look at it.

**Comment by jackpoz** [comment]
Your crashlog is from FreezeDetector, meaning worldserver got stuck for 60 seconds without a world loop update. I wonder if the error log was totally unrelated if you can't reproduce the issue anymore.

**Comment by Aokromes** [comment]
i remember we disabled some gm spells because same issue, maybe the issue is lack of targets limitation
