### ISSUE TITLE
Map extractor do extract maps/0000_43_31.map

### ISSUE THREAD

**Issue by diegodamas1** [TrinityCore/TrinityCore#28294]
### Description

Map extractor tool not extract the right file

Map extractor give me maps/0001_43_31.map and not maps/0000_43_31.map

![image](https://user-images.githubusercontent.com/114272142/193010301-a9fc5e9d-2c6c-4044-8577-e4ed15744a27.png)

### Expected behaviour

extract right file

### Steps to reproduce the problem

using mapextractor

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 5c5446d63e91 2022-09-24 23:57:12 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/ServidorWowBuild/bin/RelWithDebInfo/worldserver.conf.
Using SSL version: OpenSSL 1.1.1q  5 Jul 2022 (library: OpenSSL 1.1.1q  5 Jul 2022)
Using Boost version: 1.73.0
Updating Auth database...
>> Auth database is up-to-date! Containing 4 new and 272 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 2 new and 142 archived updates.
Updating World database...
>> World database is up-to-date! Containing 54 new and 6458 archived updates.
Updating Hotfixes database...
>> Hotfixes database is up-to-date! Containing 2 new and 498 archived updates.
Realm running as realm ID 1
Using World DB: TDB 927.22082
Using ptBR DBC Locale
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Client cache version set to: 22082
Using DataDir ./
WORLD: MMap data directory is: ./mmaps
VMap support included. LineOfSight: 1, getHeight: 1, indoorCheck: 1
VMap data directory is: ./vmaps
Map file './maps/0000_43_31.map' does not exist!
Please place MAP-files (*.map) in the appropriate directory (./maps/), or correct the DataDir setting in your worldserver.conf file.
Unable to load critical files - server shutting down !!!

### Operating system

windows 10

### Custom changes

none

**Comment by Aokromes** [comment]
fix your path to files.

**Comment by diegodamas1** [comment]
Sorry for ignorance, but I think Mapextractor do not created that file with prefix 0000, only 0001, like image.
the language I'm using is PT-BR.
![image](https://user-images.githubusercontent.com/114272142/193056199-957e7127-c98d-44e7-9dc5-f3fc51288af7.png)

**Comment by Aokromes** [comment]
scroll up or re-run extractor or fix client, if it will had failed it failed for everyone, not only for you.

**Comment by shamage** [comment]
> Sorry for ignorance, but I think Mapextractor do not created that file with prefix 0000, only 0001, like image. the language I'm using is PT-BR. ! <

Look, I recently extracted (see the date on the picture) and everything was fine. 

![Ashampoo_Snap_štvrtok 29  septembra 2022_19h24m17s_001_](https://user-images.githubusercontent.com/7515044/193101251-f4adb3a3-b2f7-4741-a7a8-87806ce8cac6.png)

**Comment by diegodamas1** [comment]
Weird!!!
![image](https://user-images.githubusercontent.com/114272142/193142572-d6a8e85d-59fe-4a08-9d19-7351f3079b13.png)
I extracted today e files comes with 0001 prefix
I don't know how to fix it!
![image](https://user-images.githubusercontent.com/114272142/193142857-e7b5febf-c903-4968-bc7e-57a9bb3e8edb.png)

**Comment by Undamed** [comment]
Mine extracted fine too. I'd make sure your client is fully downloaded.
