### ISSUE TITLE
MAPS: Could not load MMAP name: Halls of Lightning

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28296]
### Description

I just reextracted all maps with latest tools to make sure Im not outaded but while I enter in Halls of Lightning and I fight with 
Volkhan worldserver is showing those missing maps :

```
Could not load MMAP name:Halls of Lightning, id:602, x:29, y:30 (mmap rep.: x:29, y:30)
Could not load MMAP name:Halls of Lightning, id:602, x:30, y:30 (mmap rep.: x:30, y:30)
Could not load MMAP name:Halls of Lightning, id:602, x:28, y:30 (mmap rep.: x:28, y:30)
Could not load MMAP name:Halls of Lightning, id:602, x:32, y:31 (mmap rep.: x:32, y:31)
```

![maps](https://user-images.githubusercontent.com/24683355/193408725-344b513b-152d-4d11-b345-0308f744c4dd.PNG)

### Expected behaviour

probably not trow those errors

### Steps to reproduce the problem

.tele ulduar
enter Halls of Lightning then I used .gm fly on to reach faster Volkan without making any previous trash mobs then start fighting
check worldserver last lines.

### Branch

3.3.5

### TC rev. hash/commit

bf1f8f0c2df4

### Operating system

Windows 10 x64

### Custom changes

Nope

**Comment by jackpoz** [comment]
> ### Expected behaviour
> probably not trow those errors

it's not an error, it's a warning: https://github.com/TrinityCore/TrinityCore/blob/a51fef236ebf0f1c459683f1f9c16242969af7d4/src/server/game/Maps/Map.cpp#L169

It's logged in "mmaps.tiles" category, you can exclude this if you want
