### ISSUE TITLE
Overzealous SpellInterruptFlags::Movement check is breaking all casts while creatures move

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#28309]
### Description

SpellInterruptFlags::Movement does indeed interrupt spells while a caster is moving. However, creatures behave differently. They need one update tick to update their movement generators to come to a standstill. 

538fa8e97ff4b4e36a59e37fd74ea8958e6e30d2 fucked this up by turning it into a global check which does break literally all spell casts with SpellInterruptFlags::Movement while a creature has a ongoing spline. The CheckMovement() call in spell::prepare and spell::update needs to be restricted to players only since (as I've said) movement generators (and facing splines) need an update tick to register the spell cast and interrupt splines accordingly.

### Expected behaviour

Creatures should not be affected by super strict movement interrupt flags which prevents them from even starting to cast spells.
Instead they should stop moving first and then cast their spell. This is being prevent by the introduced CheckMovement() checks.

### Steps to reproduce the problem

1. Get a creature with mana to chase you
2. Do  .cast back 9672 on the creature while it's chasing you
3. Observe how the cast is not happening and the chase movement continues just as before

### Branch

master

### TC rev. hash/commit

769591c99ef7bd9c58eacd5c0272387af9a74e4a

### Operating system

Win 11

### Custom changes

None

**Comment by meji46** [comment]
Probably fixed by https://github.com/TrinityCore/TrinityCore/commit/cc57c9dad59a2eded2f7ea0471aa79c89b390559

**Comment by Ovahlord** [comment]
yep
