### ISSUE TITLE
DB/Spawns populate Halls of Valor Dungeon

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28320]
### Description

add creature & gob spawns for NHC, HC, Mythic, Mythic+
add Waypoints and cosmetic Aura stuff

### SQL fix

```sql
https://gist.github.com/Naddley/c1bca6717c865c2e416bb406d21d5506
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 769591c99ef7

**Comment by Shauren** [comment]
Halls of Valor does not have Timewalking difficulty, only normal, heroic, mythic and m+: `'1,2,8,23'`

**Comment by Naddley** [comment]
oh true.
Thought it was part of Legion TW pool.
corrected, thy.

**Comment by funjoker** [comment]
halls of valor gets season1 mythic+ in 10.x

**Comment by Shauren** [comment]
But not timewalking.
