### ISSUE TITLE
DB / Creature & Gameobject : Stormwind City ==>  Area: Stormwind Harbor ( 1 / 4 )

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28353]
### Description

- update old data 
- spawns missing creature & gameobject
- apply SAI & Waypoint
- ( 1 / 4 )

### SQL fix

```sql
https://gist.github.com/shamage/da4e34296997ab62fa6d0f7ff2f7b91c
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 8ffde8fcd044 2022-10-10 13:26:16 +0200 (master branch)

**Comment by Naddley** [comment]
The Darnassian Refugees all around in Stormwind are phased. (fresh Accounts and low Level Character dont see them in Stormwind)

**Comment by shamage** [comment]
> The Darnassian Refugees all around in Stormwind are phased. (fresh Accounts and low Level Character dont see them in Stormwind)

Well, I didn't know about this, I sniffed with max. character lvl.
How can I correctly find out what their phasing should be?
If I understand correctly, there should also be a condition that they cannot be seen in the calculation of game objects until a certain height of the level?
