### ISSUE TITLE
DB/Transports: Transports removed in previous patches

### ISSUE THREAD

**Issue by meji46** [TrinityCore/TrinityCore#28362]
### Description

Deleted the transports removed during Cataclysm and BFA.

### SQL fix

```sql
-- Ship, Night Elf (Feathermoon Ferry) (Removed in patch 4.0.3a)
-- Ship, Night Elf (Elune's Blessing) (Removed in patch 8.0.1)
-- Zeppelin (The Thundercaller) (Removed in patch 8.0.1)
-- Zeppelin (The Purple Princess) (Removed in patch 8.0.1)
-- Zeppelin, Horde (Cloudkisser) (Removed in patch 8.0.1)
DELETE FROM `transports` WHERE `entry` IN (164871, 176495, 177233, 181646, 181689);
```

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/76866fffb25b4727591cc9a2eeed2a1810b11428

**Comment by Shauren** [comment]
No. Don't forget their passenger spawns

**Comment by meji46** [comment]
> No. Don't forget their passenger spawns

Do I also delete the passengers from the transport removed here https://github.com/TrinityCore/TrinityCore/issues/28359 ?

**Comment by Shauren** [comment]
eh, whatever actually

**Comment by Naddley** [comment]
My mistake. Didnt thought about passengers. I will remove them.

**Comment by meji46** [comment]
Added the deletion of all passengers spawned in removed transports (included "Ship, Night Elf (Moonspray)" and "Ship (The Bravery)")

**Comment by Shauren** [comment]
I changed my mind, keeping them in doesn't hurt anything and avoids possible free guid confusion

**Comment by meji46** [comment]
Do I keep at least the deletion of passengers spawned in transports that no longer have type = 15?
