### ISSUE TITLE
Boralus Tradewinds Market Spawning Super Biggy Nice Time

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#28366]
### Description

Spawned the major npcs in Bolalus Market. Still have 6 pathes to do in these spawns but will add them in next issue.

https://gist.github.com/malcrom/314cd0e573e91bd76897e3d62be8c811

### SQL fix

```sql
-- GIST
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 05f2f4e8f691 2022-10-14 17:12:33 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1q  5 Jul 2022 (library: OpenSSL 1.1.1q  5 Jul 2022)
Using Boost version: 1.77.0
Using MySQL version: 80030
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19043
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by Naddley** [comment]
missing DELETE statement for Actionlist 13353600
Line 632 should be a ',' instead of a ';'

**Comment by malcrom** [comment]
Thank you. Fixed.

**Comment by mdX7** [comment]
a lot of them are phased, iirc island expedition intro related
