### ISSUE TITLE
DB/Creature - Stormwind City - SAI + creature text update

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28365]
### Description

- update creature text & add missing text
- add missing SAI 

### SQL fix

```sql
https://gist.github.com/shamage/71409c789c11d22378133d921db7a562
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 277c063413e4+ 2022-10-13 19:32:14 +0200 (master branch)

**Comment by Naddley** [comment]
you need to remove flag "SMART_EVENT_FLAG_NOT_REPEATABLE" since on Retail they ofc can repeat there greetings script but it have a cooldown of around 3-5mins

**Comment by shamage** [comment]
ok I'll fix it, the cooldown times are debatable - when I measured it at retail it ranged from 1 to 5 minutes, never once was it the same

**Comment by mdX7** [comment]
What i changed:
- adjusted creature_text DELETE FROM statement (it was deleting more data than necessary)
- removed Elsharin SAI (requires C++ script)
- removed stormwind guard script, but cherrypicked original commit
