### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by xuehyc** [TrinityCore/TrinityCore#28383]
### Description

when I use make command in ubtuntu
it shows:
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/cmake_pch.hxx.pch
c++: error: unrecognized command-line option ‘-fpch-instantiate-templates’
c++: error: unrecognized command-line option ‘-Xclang’
c++: error: unrecognized command-line option ‘-Xclang’
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:77: src/common/CMakeFiles/common.dir/cmake_pch.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:1131: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### Expected behaviour

np

### Steps to reproduce the problem

np

### Branch

master

### TC rev. hash/commit

np

### Operating system

ubtuntu

### Custom changes

np

**Comment by Shauren** [comment]
useless report

**Comment by funjoker** [comment]
Lack of information. Useless
