### ISSUE TITLE
After compiled and install TC master in debian,how to start the server?

### ISSUE THREAD

**Issue by xuehyc** [TrinityCore/TrinityCore#28390]
### Description

need help,i didnt find zhe method in wiki,thx

### Expected behaviour

I DONT KNOW

### Steps to reproduce the problem

I DONT KNOW

### Branch

master

### TC rev. hash/commit

I DONT KNOW

### Operating system

debian 11

### Custom changes

np

**Comment by Aokromes** [comment]
this is not a support place, it's a bugtracker.
