### ISSUE TITLE
Core/PacketIO: Implement CMSG_UI_MAP_QUEST_LINES_REQUEST wont work anymore

### ISSUE THREAD

**Issue by taube11111** [TrinityCore/TrinityCore#28395]
### Description

The Opcode : CMSG_UI_MAP_QUEST_LINES_REQUEST won't work anymore. The available questlines are not shown on an actual fresh compiled core.

From this request:
https://github.com/TrinityCore/TrinityCore/pull/28038

### Expected behaviour

The available questlines are not shown on an actual fresh compiled core.

### Steps to reproduce the problem

Compile
Launch the server & login
See the missing quests on the UI Map.

### Branch

master

### TC rev. hash/commit

Actual revision

### Operating system

Windows 11 x64

### Custom changes

Non

**Comment by Shauren** [comment]
That PR has not been accepted so why are you making issues about it?
