### ISSUE TITLE
DB/Stormwind: add Pre-Broken Shore Stormwind Habor spawns

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#28398]
### Description

add npcs & gobs
add Waypoints

-> Scripts later.

### SQL fix

```sql
https://gist.github.com/Naddley/474d1afd8fa4d1ae869bf8c7b7c203b1
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 6abd91792d39

**Comment by malcrom** [comment]
You don't have all the fields there.

**Comment by Naddley** [comment]
what do you mean?
