### ISSUE TITLE
Many errors in dberrors.log - master TrinityCore rev. 198afe644954

### ISSUE THREAD

**Issue by K1ller0561** [TrinityCore/TrinityCore#28409]
### Description

Hello together,

Yesterday I compiled the Trinity Core for the game version master 9.2.7.45745, everything went without problems. But when I start the worldserver I get errors in the dberrors.log file. I have attached the link below, which errors occur there. I have unpacked the WoW client 9.2.7.45745 as in the tutorial (dbc, maps, mmaps, etc) and still errors occur. Did I do something wrong somewhere? Thanks in advance for the reply.

Here the Log Files: https://gist.github.com/K1ller0561/4caeb1e50b71c677a5bb470467624ddc

Greetings, K1ller0561 (Sascha)

### Expected behaviour

None.

### Steps to reproduce the problem

None.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 198afe644954 2022-10-25 23:52:11 +0200 (master branch)

### Operating system

Debian 11 x64

### Custom changes

None

**Comment by mdX7** [comment]
Errors in dberrors.log are mostly caused due to missing data (e.g. stats) or not updated data (from 3.3.5 e.g.), so theres nothing to worry about that :)
If yourworldserver starts properly and you installed it according to our guide in wiki everything is fine.

**Comment by Aokromes** [comment]
also, it's duplicate.
