### ISSUE TITLE
Is it recommend to fix contents after wlk?

### ISSUE THREAD

**Issue by xuehyc** [TrinityCore/TrinityCore#28420]
### Description

...

### Expected behaviour

...

### Steps to reproduce the problem

...

### Branch

master

### TC rev. hash/commit

...

### Operating system

...

### Custom changes

...

**Comment by Aokromes** [comment]
this is a bug tracker not a i have a question place.

**Comment by Faq** [comment]
@xuehyc he meant, questions can be asked in [discussions](https://github.com/TrinityCore/TrinityCore/discussions)

**Comment by CraftedRO** [comment]
After wotlk only cata , mop and maybe legion deserve to be fixed , everything up is trash in my opinion.

**Comment by Aokromes** [comment]
> @xuehyc he meant, questions can be asked in [discussions](https://github.com/TrinityCore/TrinityCore/discussions)

na not even that, it's intended to fix everything, and post wotlk things are being fixed.
