### ISSUE TITLE
DB/Misc: ported world db engine and column updates from master branch

### ISSUE THREAD

**Issue by Ovahlord** [TrinityCore/TrinityCore#28431]
### Description

As master is partially ahead in terms of performance improvements, here is a bunch of world database updates which is effectively cutting the startup time in half once applied.

What these files do is:
- getting rid of mediumint and convert them all into int
- converting all table engines to InnoDB
- converting all table's character set to utf8mb4

These changes combined will improve the startup time by speeding up table loading by alot. On my local tests, the startup time went from 15 seconds down to 8.

So here it is:
- mediumint to int conversion: https://gist.github.com/Ovahlord/37e371dbe56513f194e8c4788a8c6558
- InnoDB conversion: https://gist.github.com/Ovahlord/edf1a3b205b09c7e29970c53f889fccf
- utf8mb4 conversion: https://gist.github.com/Ovahlord/22f8998c580c3586b4a5c1136100e5d2

These changes are for the world database only at the moment. However, these need to be applied for characters and auth as well.

### SQL fix

```sql
UPDATE something SO THE FKING TEMPLATE LETS ME POST THIS;
```

### Branch

3.3.5

### TC rev. hash/commit

ccb1dbf43125d832d6bc80ea89e4d23e4650a1ad

**Comment by acidmanifesto** [comment]
For the mediumint to int conversion. I thought we no longer define the width of an integer when we create new or edit columns. (Width is deprecated in later versions of MySQL 8)

TINYINT(M) -> TINYINT 
SMALLINT(M) -> SMALLINT 
INT(M) -> INT MEDIUMINT(M) -> MEDIUMINT 
BIGINT(M) -> BIGINT 
BOOL -> Never used, synonym for TINYINT. 0 = false <>0 = true

**Comment by Ovahlord** [comment]
We still support mysql 5.7 so the width is valid. Aside from that, the rest is based on the conversion query that has been provided in the master commits so whatever you critisize here has been done in master already.

**Comment by CraftedRO** [comment]
I tried something similar [here](https://github.com/TrinityCore/TrinityCore/pull/28041/files) too but they weren't interested.

**Comment by acidmanifesto** [comment]
> We still support mysql 5.7 so the width is valid. Aside from that, the rest is based on the conversion query that has been provided in the master commits so whatever you critisize here has been done in master already. 

I suppose due to 5m7 having optional display width that May be used by applications to display integer values having a width less than the width specified for the column by left-padding them with spaces. (That is, this width is present in the metadata returned with result sets. Whether it is used is up to the application.)

Does TC even use the collumn integer width instead of its max int size? (Int max val sign being at 2147483647)

**Comment by Shauren** [comment]
No, never. Also 5.7 accepts column defintions without it

**Comment by CraftedRO** [comment]
On my server that runs with a xampp with MariaDB-10.4.10 for some reasons this have a huge negative impact:
```
Before SQL:
------------------------------------------------------
First run:
World initialized in 0 minutes 12 seconds

After restart:
World initialized in 0 minutes 8 seconds
```

```
After SQL:
-------------------------------------------------------
First run:
World initialized in 0 minutes 32 seconds

After restart:
World initialized in 0 minutes 28 seconds
```

**Comment by Shauren** [comment]
And we don't care about mariadb server

**Comment by CraftedRO** [comment]
Ok updated to MySQL 8.0.28
```
Before SQL:
------------------------------------------------------
First run:
World initialized in 0 minutes 40 seconds

After restart:
World initialized in 0 minutes 24 seconds
```
```
After SQL:
-------------------------------------------------------
First run:
World initialized in 0 minutes 20 seconds

After restart:
World initialized in 0 minutes 12 seconds
```
So Indeed on MySQL this is a must have improvement.

**Comment by CraftedRO** [comment]
kek this will get worldserver to " freeze " for like 15-30 minutes :D

**Comment by Ovahlord** [comment]
a small price for a permanent 50% performance boost.
