### ISSUE TITLE
Killing Machine proc correction

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28453]
### Description

https://www.wowhead.com/wotlk/spell=51130/killing-machine#comments
> Changed to PPM rate of 1/2/3/4/5 in 3.0.8
> It procs on AUTO-ATTACK ONLY! "It is on a proc per minute system, 1/2/3/4/5 at 5 ranks. It procs based on autoattack hits."

### SQL fix

```sql
-- Killing Machine proc correction
UPDATE `spell_proc` SET `procsperminute`=1 WHERE `spellid`=51123;
UPDATE `spell_proc` SET `procsperminute`=2 WHERE `spellid`=51127;
UPDATE `spell_proc` SET `procsperminute`=3 WHERE `spellid`=51128;
UPDATE `spell_proc` SET `procsperminute`=4 WHERE `spellid`=51129;
UPDATE `spell_proc` SET `procsperminute`=5 WHERE `spellid`=51130;
```

### Branch

3.3.5

### TC rev. hash/commit

69dda649c43c

**Comment by Ovahlord** [comment]
yep. seems correct. blueposts confirm that rank 5 sits at a ppm of 5
