### ISSUE TITLE
DB: Item Beast Muisek Vessel cooldown reduced

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28484]
### Description

Source Cmangos

https://www.wowhead.com/wotlk/item=9618/beast-muisek-vessel#comments:id=823012

### SQL fix

```sql
-- Updated in 3.2.x - cooldown reduced to 1sec
UPDATE item_template SET spellcooldown_1 = 1000 WHERE entry = 9618;
```

### Branch

3.3.5

### TC rev. hash/commit

1dabfb657853

**Comment by offl** [comment]
The fact it's still 1500 on master speaks for itself
item_template should never be changed

**Comment by CraftedRO** [comment]
hehe it seems I have to make a list with databases tables you will never accept changes

**Comment by offl** [comment]
The rule to not change WDB data without sniffs was here for a long time. Such changes simply will be wrong in nearly all cases, including this one

**Comment by CraftedRO** [comment]
yeap , agree

**Comment by Ovahlord** [comment]
In this case, 1.5s is correct. Even in Cataclysm's db2 files it's still 1.5s so 1s is wrong so cmangos got themselves yet another hack
