### ISSUE TITLE
NPC Reset Bug

### ISSUE THREAD

**Issue by Krutok** [TrinityCore/TrinityCore#28482]
### Description

I found a bug in the core. If I attack an NPC and die, the NPC should return to its location, but here it despawns and doesn't come back. At first I thought it was my SmartAI script, then I tested it with my test NPC without SmartAI but the same model as the other NPC. And this is where the error occurs.

here my Video: https://www.youtube.com/watch?v=NGYClFKbCfE

### Expected behaviour

If the player is dead, the NPC should just return to its starting position without despawning

### Steps to reproduce the problem

It's just a simple elite/boss/rare NPC standing in the world.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 0ce55c6be86a+ 2022-11-05 21:20:39 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 11

### Custom changes

https://github.com/trickerer/Trinity-Bots

**Comment by Krutok** [comment]
Ok, the Test NPC appears again after 5 minutes, but he shouldn't reset, that's why I have rare NPCS and open world bosses that only appear again after the kill between several hours and days and when a group wipes and the boss resets and despawns, that's it not wanted like that. And this ist not Blizzlike

**Comment by CraftedRO** [comment]
This bug is most likely invalid and your problem is not related to any blizzlike behaviour since that npc is custom.

**Comment by Krutok** [comment]
> This bug is most likely invalid and your problem is not related to any blizzlike behaviour since that npc is custom.

I don't think it matters if a simpler NPC was created by yourself. If I create an NPC, give it a name and put it into the world, it's not a big change. Even if I copy the original NPC and it only has a different entryID and reacts like this, the problem is not with me.

**Comment by Ovahlord** [comment]
provide your sql files so someone can try to reproduce it because at the moment, this issue cannot be reproduced at all.

**Comment by Krutok** [comment]
> provide your sql files so someone can try to reproduce it because at the moment, this issue cannot be reproduced at all.

```
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(100039, 0, 0, 0, 0, 0, 31658, 0, 0, 0, 'Test NPC', 'NPC tester', NULL, , 80, 80, 2, 14, 0, 1, 1.42857, 0.6, 0, 0, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, '', 1, 1, 140, 0, 10, 300, 0, 0, 0, 1, 0, 0, 0, '', NULL);
```

Simple NPC

**Comment by CraftedRO** [comment]
your sql does trow a lot of errors and can't even be imported

**Comment by Krutok** [comment]
> your sql does trow a lot of errors and can't even be imported

So to prove that it's not my custom NPC I took an NPC in Icecrown. As soon as I do damage and let myself be wiped, the NPC despawns. If I do no damage and just let myself die, then the reset works and the NPC doesn't despawn.

https://www.youtube.com/watch?v=J9gsHIKwVBc

So it's not because of my self-created NPCs, if even NPCs from your official database despawn in the world, it's not because of my custom NPCs

**Comment by offl** [comment]
Try without bots please

**Comment by CraftedRO** [comment]
that video is 360p I can't understand a thing

Look

https://user-images.githubusercontent.com/24683355/200172242-7bb0c6e5-8d5b-4a59-ad64-b56c3e111c7e.mp4


Everything is fine without custom crap changes .

**Comment by CraftedRO** [comment]
TC shoudn't accept any Custom changes issue in tracker , it only waste our time.

**Comment by Krutok** [comment]
NPC in ICC Raid https://www.youtube.com/watch?v=2E_cgaDqly0

Despawn after i make Damage one the NPC

**Comment by Krutok** [comment]
> TC shoudn't accept any Custom changes issue in tracker , it only waste our time.
> 
> Also in your last video you tried to " trick " us by taking that Bone Guard too a far distance and when you died he was going our of player visual range back to his spawn location that's not in that gate.

I'm not wasting anyone's time here, I've now made a video in the ICC Raid with the huge bone guard

**Comment by CraftedRO** [comment]
https://user-images.githubusercontent.com/24683355/200172864-3b815661-f312-4d04-a268-042084dce938.mp4


Next ?

**Comment by Jinnaix** [comment]
@trickerer - probably something on your side? Anything up with basic reset and despawning npcs?

**Comment by Krutok** [comment]
> Try without bots please

I uninstalled these bots with patch -p1 -R < filename.patch and now recompile the core without the bots, we'll see

**Comment by Ovahlord** [comment]
> > TC shoudn't accept any Custom changes issue in tracker , it only waste our time.
> > Also in your last video you tried to " trick " us by taking that Bone Guard too a far distance and when you died he was going our of player visual range back to his spawn location that's not in that gate.
> 
> https://www.youtube.com/watch?v=2E_cgaDqly0
> 
> I'm not wasting anyone's time here, I've now made a video in the ICC Raid with the huge bone guard

Then it is very likely that your NPC-Bots fucked everything up. Use a clean installation please and try again. It's not the first time that they are causing problems.

**Comment by Krutok** [comment]
> > > TC shoudn't accept any Custom changes issue in tracker , it only waste our time.
> > > Also in your last video you tried to " trick " us by taking that Bone Guard too a far distance and when you died he was going our of player visual range back to his spawn location that's not in that gate.
> > 
> > 
> > https://www.youtube.com/watch?v=2E_cgaDqly0
> > I'm not wasting anyone's time here, I've now made a video in the ICC Raid with the huge bone guard
> 
> Then it is very likely that your NPC-Bots fucked everything up. Use a clean installation please and try again. It's not the first time that they are causing problems.

Uninstalled the patch (with patch -p1 -R < filename.patch) and the NPCs are still despawning

**Comment by Ovahlord** [comment]
dont just uninstall a patch, make a completely clean installation with an untouched source code.

**Comment by Krutok** [comment]
> dont just uninstall a patch, make a completely clean installation with an untouched source code.

Ok, I freshly downloaded the source, the only thing I added are the C++ scripts that were made for me. They don't crack the original code. I'll let you know when the code has been compiled.

**Comment by trickerer** [comment]
I tried to reproduce on https://github.com/TrinityCore/TrinityCore/commit/6e67ec0b0168815c1375acd8eae052c9418d36b5 with npcbots included and I don't see any mob disappearing after player dies, with or without damaging them first.

Btw, C++ scripts may contain global hooks.

Anyway, this issue does not belong here until it is confirmed on clean TC

**Comment by CraftedRO** [comment]
dude he has custom scripts and so , he doesn't understand what a clean "untouched" source mean so...

**Comment by CraftedRO** [comment]
btw there's this a issue after you are doing custom edits in core files tc still provide valid latest rev. hash/commit ?

**Comment by CraftedRO** [comment]
dude he has custom scripts and so , he doesn't understand what a clean "untouched" source mean so...

btw is this a issue after you are doing custom edits in core files tc still provide valid latest rev. hash/commit ?

**Comment by Krutok** [comment]
Ok I found the error after a long search, a script as expected triggered it, but I don't know c++ and the script was written for my project for which I had paid. In any case, after removing it from the script loader and restarting the server, the reset worked again.

As a loaner, I don't see anything in the script that could trigger this, but maybe I can send it to someone and take a look

**Comment by Jinnaix** [comment]
> I tried to reproduce on [6e67ec0](https://github.com/TrinityCore/TrinityCore/commit/6e67ec0b0168815c1375acd8eae052c9418d36b5) with npcbots included and I don't see any mob disappearing after player dies, with or without damaging them first.
> 
> Btw, C++ scripts may contain global hooks.
> 
> Anyway, this issue does not belong here until it is confirmed on clean TC

Thank you for your time :)

**Comment by jackpoz** [comment]
@Krutok always, always, always reproduce issues on a clean TC.
