### ISSUE TITLE
Update start spells for Warlocks

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#28499]
### Description

These are messed up and some missing, wrong spells, some that shouldn't be there. All spell updates are from sniff.

### SQL fix

```sql
-- Main 9 Warlock races
DELETE FROM `playercreateinfo_action` WHERE `race` IN (1,2,3,5,7,8,9,10,22) AND `class`=9;
INSERT INTO `playercreateinfo_action` (`race`,`class`,`button`,`action`,`type`) VALUES
(1,9,0,686,0),  -- Human
(1,9,9,59752,0),
(2,9,0,686,0),  -- Orc
(2,9,9,20572,0),
(3,9,0,686,0),  -- Dwarf
(3,9,9,20594,0),
(5,9,0,686,0),  -- Undead
(5,9,9,20577,0),
(7,9,0,686,0),  -- Gnome
(7,9,9,20589,0),
(8,9,0,686,0),  -- Troll
(8,9,9,26297,0),
(9,9,0,686,0),  -- Goblin
(9,9,9,69070,0),
(10,9,0,686,0), -- Blood Elf
(10,9,9,80483,0),
(22,9,0,686,0); -- Worgan
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/badd37e9a499af6b4a37e9b5e4c7e275e2fd2d65+

**Comment by TheDdraig** [comment]
So is this going to be added before 2050?

**Comment by mdX7** [comment]
> So is this going to be added before 2050?

yes, after when i'm home again around next weekendish
