### ISSUE TITLE
Nature's Grasp doesn't have cooldown between procs and this lead to be consumed in no time

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28504]
### Description

Nature's Grasp doesn't have cooldown between proc charges and this lead to be consumed faster.

https://user-images.githubusercontent.com/24683355/200591241-ba2419a4-06e0-4ed0-bda4-669da48ae436.mp4

### Expected behaviour

Nature's Grasp shoud have ~2 sec internal cooldown between charges procs.

https://www.wowhead.com/wotlk/spell=16689/natures-grasp#comments:id=985259 :

> Nature's Grasp is a self buff that causes things that hit you to become rooted. That effect now has 3 charges. There is a small internal cooldown in between roots to keep say a rogue who hits you twice very quickly from wasting two charges. 
> Last edited by [parl2001](https://www.wowhead.com/user=parl2001) on 2010/02/25 (Patch 3.3.2)

You can see here it procs on ~ 2 sec :
YT proof : https://youtu.be/TVUDDQWL5IQ?t=199

### Steps to reproduce the problem

.cast 16689 while being attacked (fast) by another creature or player
Notice charges all charges are gone in no time.

### Branch

3.3.5

### TC rev. hash/commit

1dabfb657853

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
I tried this but doesn't feel to make any differences:
```sql
-- Nature's Grasp internal cooldown
UPDATE `spell_proc`SET `Cooldown` = 2 WHERE `spellid` = -16689;
```

**Comment by Jildor** [comment]
you should use milliseconds:
```sql
-- Nature's Grasp internal cooldown
UPDATE `spell_proc`SET `Cooldown`=2000 WHERE `spellid`=-16689;
```

**Comment by Shauren** [comment]
Blizzlike value is 1 second, not 2
Source: 3.4.0 db2 https://wow.tools/dbc/?dbc=spellauraoptions&build=3.4.0.46368#page=1&colFilter[9]=16689

**Comment by offl** [comment]
Yep, hidden cooldown of all non-serverside spells is now here, ProcCategoryRecovery

**Comment by CraftedRO** [comment]
Interesting maybe we shoud do a full override since you trust that source :D

**Comment by Nyr97** [comment]
I mean, it's their raw data being shipped to the client, it's enough to be trusted :eyes:

**Comment by CraftedRO** [comment]
I was jokin' mate 🤣

**Comment by CraftedRO** [comment]
Shoud we trust that Aspect of the Monkey https://wow.tools/dbc/?dbc=spellauraoptions&build=3.4.0.46368#page=1&colFilter[9]=13163
have 20sec internal cooldown for example too ?

**Comment by CraftedRO** [comment]
Shoud we trust that Aspect of the Monkey https://wow.tools/dbc/dbc=spellauraoptions&build=3.4.0.46368#page=1&colFilter[9]=13163 have 20sec internal cooldown for example too ?
Because if its right we got some updates to do : 
[textcompare-diff.pdf](https://github.com/TrinityCore/TrinityCore/files/9965559/textcompare-diff.pdf).
this is a list with compared tables ( I updated charges too )  but only for positive spellid-s.
