### ISSUE TITLE
Quest gossip closing issue

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#28506]
### Description

Quest gossip should close immediately before a phase change not fade out with the npc. 

### Expected behaviour

After quest reward gossip should close before phase change.

### Steps to reproduce the problem

It can be tested on the exile's Reach ships and possibly in other places.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. badd37e9a499+

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by Seyden** [comment]
Thats not a core issue.. thats a scripter issue. Alliance Side on Exile Reach, npcs do remove their npc flags when becoming a personal clone, which also then closes the gossip

**Comment by Seyden** [comment]
Btw proof video that only scripting is required: https://www.youtube.com/watch?v=SFitw5GqcDk&ab_channel=Seyden

**Comment by malcrom** [comment]
Look at the horde video on my pr.

**Comment by Seyden** [comment]
> Look at the horde video on my pr.

but thats because you need to handle it yourself. You have to remove the npc flag from the copy, i also looked at your alliance video and its also broken there. You gotta handle it yourself, its pure scripting

**Comment by Seyden** [comment]
Ok i retested it and i know now that this is due to implicit replace not being implemented

I implemented it a long time ago (we're not sure if this was the right or the wrong way)
But Shauren didn't like it
(https://github.com/TrinityCore/TrinityCore/pull/27785)

**Comment by Seyden** [comment]
Fixed in #28516 

But you still need to remove the npc flag then
