### ISSUE TITLE
Add missing text line to Ango'rosh Ogre

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28512]
### Description

Add missing text line to Ango'rosh Ogre

https://www.wowhead.com/wotlk/npc=18117/angorosh-ogre

https://youtu.be/obljjhNW8jY?t=42

Thus , I still didn't understand if its required for all creature text to add or select from existing equivalent BroadcastTextId in broadcast_text

### SQL fix

```sql
-- Ango'rosh Ogre
DELETE FROM `creature_text` WHERE `CreatureID`=18117 AND `GroupID`=1;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(18117, 1, 0, 'You no take mushroom!', 12, 0, 100, 0, 0, 0, 15198, 0, "Ango'rosh Ogre");

UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 18117;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 18117 AND `source_type` = 0 AND `id` = 3;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(18117, 0, 3, 0, 4, 0, 100, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, "Ango'rosh Ogre - On Aggro - Say Line 1");
```

### Branch

3.3.5

### TC rev. hash/commit

1dabfb657853

**Comment by offl** [comment]
GroupID and ID are messed up, and BroadcastTextId is missing

**Comment by CraftedRO** [comment]
BroadcastTextId shoud be inserted or just assigned an ID from table that have same "You no take mushroom!" text ? or are they unique

**Comment by offl** [comment]
You just take ID from broadcast_text with text you used

**Comment by offl** [comment]
GroupID 0 and ID 0
And your new text should have GroupID 1 and ID 0

**Comment by CraftedRO** [comment]
I guess something like this otherwise I don't get it 🤣

**Comment by CraftedRO** [comment]
Ah I guess now SAI need to be edited too kek

**Comment by CraftedRO** [comment]
but now they say other existing text two times once on aggro and once on linked , on this sai I guess I need to change group to 1

**Comment by CraftedRO** [comment]
ok fixed

**Comment by CraftedRO** [comment]
So if they have different kind "type" of text then that text have to be in different group , meh.

**Comment by Nyr97** [comment]
IDs are to be used randomly when choosing a GroupID. For example, a kill say for a boss might have up to 3 different lines, we use the same GroupID which will then randomly choose one of the IDs when using Talk().

**Comment by CraftedRO** [comment]
I guess Im too mentally retarded to understand them at this time ,
I mean for example on this mobs it works even with groupid0 and id 1 for this text line and I can call them in SAI by ID , I mean the final result seems same dunno.

**Comment by CraftedRO** [comment]
Nevermind it seems you can't call text by ID only by groupid kek

**Comment by CraftedRO** [comment]
This line make a huge confusion in [Creature Text description wiki](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130007/creature+text) :
ID
This is the unique identifier when entry (creature) is the same and groupid is unchanged(everything is logically untill the until further notice ->), it must be incremented (ex. 0, 1, 2, 3...).

It must not be incremented actually when creature is same and groupid is unchanged.

**Comment by Nyr97** [comment]
"Entry for each group of texts. This is the **unique identifier** when entry (creature) is the same and groupid is unchanged, it must be incremented (ex. 0, 1, 2, 3...). **A creature say will be randomly selected from this list based on the groupid it belongs to.**"

It's not confusing: it is the unique identifier inside of the same GroupID. When it states that it must be incremented, it refers to ID again, whose index cannot be repeated in the same GroupID.

**Comment by CraftedRO** [comment]
yea idk for non english native speakers some wiki descriptions are hard to be understand , I mean they can be more logically simplified in my opinion.
