### ISSUE TITLE
Update few wrong spells cooldown values part2

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28514]
### Description

Values are taken from https://wow.tools/dbc/?dbc=spellauraoptions&build=3.4.0.46368 and verified on https://www.wowhead.com/wotlk/spell=

/* Rows affected: 19 Records found: 0 Warnings: 0 Taking 20 queries: 1.343 sec. */

### SQL fix

```sql
-- Update few wrong (negative) spells cooldown values
UPDATE `spell_proc` SET `Cooldown`=3500 WHERE `SpellId`=-324; -- Lightning Shield
UPDATE `spell_proc` SET `Cooldown`=3500 WHERE `SpellId`=-974; -- Earth Shield
UPDATE `spell_proc` SET `Cooldown`=8 WHERE `SpellId`=-10400; -- Flametongue Weapon (Passive)
UPDATE `spell_proc` SET `Cooldown`=500 WHERE `SpellId`=-14186; -- Seal Fate
UPDATE `spell_proc` SET `Cooldown`=500 WHERE `SpellId`=-16257; -- Flurry
UPDATE `spell_proc` SET `Cooldown`=6000 WHERE `SpellId`=-18094; -- Nightfall
UPDATE `spell_proc` SET `Cooldown`=8 WHERE `SpellId`=-29074; -- Master of Elements
UPDATE `spell_proc` SET `Cooldown`=500 WHERE `SpellId`=-30160; -- Elemental Devastation
UPDATE `spell_proc` SET `Cooldown`=6000 WHERE `SpellId`=-33150; -- Surge of Light
UPDATE `spell_proc` SET `Cooldown`=1 WHERE `SpellId`=-34753; -- Holy Concentration
UPDATE `spell_proc` SET `Cooldown`=8 WHERE `SpellId`=-44449; -- Burnout
UPDATE `spell_proc` SET `Cooldown`=6000 WHERE `SpellId`=-44557; -- Enduring Winter
UPDATE `spell_proc` SET `Cooldown`=100 WHERE `SpellId`=-49208; -- Reaping
UPDATE `spell_proc` SET `Cooldown`=500 WHERE `SpellId`=-49217; -- Wandering Plague
UPDATE `spell_proc` SET `Cooldown`=3500 WHERE `SpellId`=-52127; -- Water Shield
UPDATE `spell_proc` SET `Cooldown`=100 WHERE `SpellId`=-54639; -- Blood of the North
UPDATE `spell_proc` SET `Cooldown`=22000 WHERE `SpellId`=-56342; -- Lock and Load
UPDATE `spell_proc` SET `Cooldown`=5800 WHERE `SpellId`=-56636; -- Taste for Blood
UPDATE `spell_proc` SET `Cooldown`=100 WHERE `SpellId`=-63730; -- Serendipity
```

### Branch

3.3.5

### TC rev. hash/commit

37d8b6d33b58

**Comment by offl** [comment]
You don't need to verify cooldown on wowhead, it uses same db2. If I was to do it, I'd add all rows with cooldown from db2 to separate table, compare and add cooldown to the ones without cooldown or with wrong cooldown, then figure out how to properly add rows which don't exist to add cooldown to them. Some fields in every new row needs to be filled
What is more interesting to check is can different ranks have different cooldown. Also no idea how they did that or how they maintain that but db2 currently holds all WotLK spells but it's not even last patch, if I'm not wrong same with WDB, but I imagine in some cases db2 and WDB holds pre-last patch data. In other words in some cases current values may be more correct comparing to db2. But we shouldn't care about that in this case, importing all that data is a big change and it's waste of time to try to check why current and db2's cooldown is different, if I'm not wrong all of that was added based on comments, as I see sometimes it matches, sometimes not by 5 sec or so. Checking comments for potential info on updates between patches is waste of time too. Same with comparing between versions of db2. Also we are not thinking about replacing potentially correct 0 with db2's value. After all it can be re-checked again with "last patch" db2, so checking that is waste of time

**Comment by Ovahlord** [comment]
For now you can just merge these cooldowns. They are fine and correct. If you wanna add proc entries for all remaining spells with db2 cooldown data is up to you but that's out of scope for this one here.
