### ISSUE TITLE
Correct gold dropped by mobs

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28523]
### Description

Correct gold dropped by mobs based on classic sniffs.

Credit Vmangos

### SQL fix

```sql
https://gist.github.com/CraftedRO/ddd89fcdf6dc96bc37eb5d678f94fd9e
```

### Branch

3.3.5

### TC rev. hash/commit

37d8b6d33b58

**Comment by ratkosrb** [comment]
You should know we only use 1.13 and 1.14 sniffs in vmangos since its a vanilla project, so this data might not be accurate for 3.3.5. You ought to mass parse 3.X sniffs instead to gather data for wotlk.

**Comment by CraftedRO** [comment]
I doubt something changed from classic till wotlk when we talk about gold drop but however the other devs can decide if this change is wrong or no , I don't have a retail sub so I can check and compare right now but I guess if someone can do this on few mobs from list and gold amount is same as in your sniffs then probably can be merged .

**Comment by CraftedRO** [comment]
I doubt something changed from classic till wotlk when we talk about gold drop but however the other devs can decide if this change is wrong or no.
I don't have a retail sub so I can't check and compare right now but I guess if someone can do this on few mobs from list and gold amount is same as in your sniffs then probably can be merged .
