### ISSUE TITLE
Core / DB - server crash while looting gameobject in The Wandering Isle - start zone

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28541]
### Description

create a panda character ( monk ) and start in the area: The Wandering Isle 

- .add quest 30027  - [Quest ](https://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough)
- go get the item 
- see how the window opens with an offer to take the item and immediately closes itself 
- if you want to get that item you have to be very fast 
- watch the server go down
- gameobject id = 210020

[c8583746e18a_worldserver.exe_[16-11_13-56-9].txt](https://github.com/TrinityCore/TrinityCore/files/10022675/c8583746e18a_worldserver.exe_.16-11_13-56-9.txt)
[c8583746e18a_worldserver.exe_[16-11_15-27-18].txt](https://github.com/TrinityCore/TrinityCore/files/10022677/c8583746e18a_worldserver.exe_.16-11_15-27-18.txt)

### Expected behaviour

you should be able to take the item to complete the task and the server should not crash

### Steps to reproduce the problem

- .add quest 30027  - [Quest ](https://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough) ( go = 210020 )
- go get the item 
- see how the window opens with an offer to take the item and immediately closes itself 
- if you want to get that item you have to be very fast 
- watch the server go down

### Branch

master

### TC rev. hash/commit

TrinityCore rev. c8583746e18a 2022-11-12 22:59:32 +0100 (master branch) (Win64, RelWithDebInfo, Static)

Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1q  5 Jul 2022)
Using Boost version: 1.80.0
MySQL client library: 8.0.31
MySQL server ver: 8.0.31
Connected to MySQL database at 127.0.0.1
MySQL client library: 8.0.31
MySQL server ver: 8.0.31

### Operating system

Win 10 x64

### Custom changes

None

**Comment by Shauren** [comment]
why close?

**Comment by shamage** [comment]
> why close?

sorry, I left my computer for a few minutes and my son realized here
