### ISSUE TITLE
DB / Player : you cannot create more than one character

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28602]
### Description

After starting the game, the player can create only one character. After creating a character, the game no longer offers him the opportunity to create another character.

### Expected behaviour

It should be possible to create another character (of course with a limit according to retail)

### Steps to reproduce the problem

1. Create a character
2. Watch how after creating a character, you do not have the option to create another character

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0555ab2f56e5+ 2022-12-17 20:27:13 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win 10 Pro

### Custom changes

none

**Comment by shamage** [comment]
![Ashampoo_Snap_sobota 17  decembra 2022_22h14m04s_012_World of Warcraft](https://user-images.githubusercontent.com/7515044/208266283-423f72b8-b84b-411c-b632-f0303d1844a8.png)

**Comment by ogarvey** [comment]
`Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BA (14010)] from [Player: Account: 2]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B9 (14009)] from [Player: Account: 2]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F1 (14065)] from [Player: Account: 2]
[Player: Account: 2] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })`

Only thing logged after connecting to the server in the client and reaching the character screen, not sure if it's of any use.

**Comment by DeerHunt3r** [comment]
What was the fix for this?  I'm getting the same errors on a newly built server and DB.
