### ISSUE TITLE
[Fix proposal] : Array size for ChrCustomization

### ISSUE THREAD

**Issue by Kylnic28** [TrinityCore/TrinityCore#28605]
### Description

- Dracthyr characters cannot be created, because the size of ChrCustomization array isn't updated. Since DF, the new size is 72 and not 50, dues to their lot of customisations.

In order to create a dracthyr(exception to DB changes), you must  change every occurences of Array<ChrCustomizationChoice, 50> by :

`Array<ChrCustomizationChoice, 72>`

in CharacterPackets.h and CharacterPackets.cpp

Sorry for issue instead of pull request, but i doens't have a TC fork.

### Expected behaviour

- Dracthyr character must be created.

### Steps to reproduce the problem

1. Log-in
2. Create a dracthyr
3. Constat error in console.

### Branch

master

### TC rev. hash/commit

4b2c1bbe0cd301dec53620a655f2b980bdaa7187

### Operating system

Windows 11

### Custom changes

No.

**Comment by MaxtorCoder** [comment]
I am pretty sure there is more to this :D

**Comment by Kylnic28** [comment]
Yes, you have to do some SQL changes, but in core, there is the only fixes i've applied and it's work, after i don't guarantee is the best way.👍

**Comment by MaxtorCoder** [comment]
> Yes, you have to do some SQL changes, but in core, there is the only fixes i've applied and it's work, after i don't guarantee is the best way.👍

Wait, are you sure it works? It should throw another error since there are customization options from both Genders (Gender::Both)

**Comment by Kylnic28** [comment]
Yes, it's work for both

**Comment by MaxtorCoder** [comment]
Yeah but there are customization options for Body Type 1 and 2 that are shared.

**Comment by DintyGadget** [comment]
Your changes are not suitable for the full implementation of Dracthyr

1)If you try to add this race's spawn locations with a class, you will get an crash + error related to LoadPlayerInfo
2)If you don't add a spawn location for this race in the console, you'll get a different error:

Player::Create: Possible hacking attempt: Account 1 tried to create a character named 'Tester' with an invalid race/class pair (52/13) - refusing to do so.

**Comment by Kylnic28** [comment]
Yes, you need to add the modifications on the SQL side so that you can create your character, but the modification on the core side is essential for it to work, since the number of possible customizations to change on the client side, the modification on the server side must also follow.

Personally, I added the necessary modifications to play a Dracthyr and it works perfectly, as shown in the image above.

https://i.imgur.com/9JEBsZp.jpeg

**Comment by dio85** [comment]
Yeah if you try create dracthyr added the error and the answer too :D 71.

**Comment by DintyGadget** [comment]
> Yeah if you try create dracthyr added the error and the answer too :D 71.

you need to add stats to lvl 1-60 class 13, and add spawn points for the race, then you can spawn a Dracthyr. Though the race is very unstable, you cannot change your appearance, and the barbershop is still not working at the moment

**Comment by dio85** [comment]
Yeah i know^^

**Comment by Thordekk** [comment]
I add all stats and sql data to test and still u can create dracthyr

**Comment by DintyGadget** [comment]
> I add all stats and sql data to test and still u cant create dracthyr

1) make changes to the core (an example of what to change is written at the very beginning)
2) configure the expansions = 9 in the world server config
3) Add required information to SQL for races 50/72 and class 13
4) Set your account 9 expansions

**Comment by Thordekk** [comment]
> 4\. expansions

52 its

**Comment by lyosky** [comment]
Array<ChrCustomizationChoice, 72> is work well

**Comment by Faq** [comment]
@Kylnic28 why closed?

**Comment by MaxtorCoder** [comment]
Because fixed

**Comment by Kylnic28** [comment]
Yes. Fixed with this merge request : https://github.com/TrinityCore/TrinityCore/commit/b71b121c51214d220163a3c278f212b6804ad644
