### ISSUE TITLE
compilation error - bnetserver

### ISSUE THREAD

**Issue by MaciekMr** [TrinityCore/TrinityCore#28604]
### Description

Hi, just grab latest repository and during fresh compilation, get an error:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[ 24%] Built target bnetserver
[ 24%] Building CXX object src/server/game/CMakeFiles/game.dir/cmake_pch.hxx.gch
In file included from /home/maciek/old_home/trinitycore/src/server/game/Entities/Object/Object.h:34,
                 from /home/maciek/old_home/trinitycore/src/server/game/Entities/Unit/Unit.h:21,
                 from /home/maciek/old_home/trinitycore/src/server/game/Entities/Creature/Creature.h:21,
                 from /home/maciek/old_home/trinitycore/src/server/game/PrecompiledHeaders/gamePCH.h:20,
                 from /home/maciek/old_home/trinitycore/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/maciek/old_home/trinitycore/src/server/game/Entities/Object/Updates/UpdateFields.h:702:30: error: narrowing conversion of ‘-1’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
  702 |     UpdateField<uint64, -1, 0> Field_0;
      |                              ^
compilation terminated due to -Wfatal-errors.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
OS - opensuse linux
gcc - gcc (SUSE Linux) 12.2.1 20221020
boost - 1.81

### Expected behaviour

default constructotr shouldn't have unsignedint

### Steps to reproduce the problem

1. Download latest repository
2. run cmake

### Branch

master

### TC rev. hash/commit

* TrinityCore revision   : 4b2c1bbe0cd3 2022-12-18 13:15:34 +0100 (master branch)
* TrinityCore buildtype  : RelWithDebInfo

### Operating system

opensuse tumble

### Custom changes

none

**Comment by Shauren** [comment]
Just GCC being GCC I see, for now use clang if you want to compile, it will be fixed later
