### ISSUE TITLE
DB / Character : Paladin talents cannot be learned

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28601]
### Description

After selecting talents from the talent menu (according to available points) for Paladin and clicking on "Apply Changes", I get the link: "Unable to learn talent"

### Expected behaviour

Talents should be learnable.

### Steps to reproduce the problem

1.  .levelup to 60
2.  choose talents for the character
3. click on "Apply Changes"
4. you will get the answer: "Unable to learn talent"

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 0555ab2f56e5+ 2022-12-17 20:27:13 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win 10 Pro

### Custom changes

none

**Comment by shamage** [comment]
![Ashampoo_Snap_sobota 17  decembra 2022_22h00m02s_009_](https://user-images.githubusercontent.com/7515044/208266112-7aaba32e-c5ea-497c-8e48-80eabb326523.png)

**Comment by MaxtorCoder** [comment]
To me that looks like you are trying to learn level 70 talents as well, no?

**Comment by shamage** [comment]
To clarify: I performed several tests - combinations of learning talents and it failed several times and once it did. It seems like a lottery, sometimes I guess the combination and sometimes I don't.

**Comment by shamage** [comment]
> To me that looks like you are trying to learn level 70 talents as well, no?
> 
> On retail on my PAladin I cannot learn all the bottom talents iirc

This is now irrelevant, the important thing is that you can't learn talents from Paladin at all (except for some random exceptions). For example, with druid, it worked for me on the first try.

**Comment by MaxtorCoder** [comment]
> > To me that looks like you are trying to learn level 70 talents as well, no?
> > On retail on my PAladin I cannot learn all the bottom talents iirc
> 
> This is now irrelevant, the important thing is that you can't learn talents from Paladin at all (except for some random exceptions). For example, with druid, it worked for me on the first try.

Lol what the fuck??

**Comment by MaxtorCoder** [comment]
Okay seems to be an issue with the first node of the left paladin window, the first talent should have GrantedRanks = 1 @Shauren

**Comment by shamage** [comment]
@MaxtorCoder : Are you talking about this limitation?
![Ashampoo_Snap_sobota 17  decembra 2022_22h28m26s_015_](https://user-images.githubusercontent.com/7515044/208266620-9a4fe450-cf6a-49f5-8dbc-dcef1ef6a1bc.png)

**Comment by MaxtorCoder** [comment]
No, I am talking about the first node in the tree for Starter Build that should have GrantedRanks = 1 (the middle node at the top)

**Comment by shamage** [comment]
@MaxtorCoder  : Are you talking about this limitation? 
![Ashampoo_Snap_sobota 17  decembra 2022_22h28m26s_015_](https://user-images.githubusercontent.com/7515044/208266704-c02a6a7b-df9b-4819-983f-7b5d41bf9d00.png)

**Comment by ImmortalusDev** [comment]
I can confirm it, sometimes you cannot learn build tree at all, happened to me x times on prot pala

**Comment by dio85** [comment]
Not just prot no work... First you need spend all point and just after can you learn, but that no work.  Unable learn error give

**Comment by ImmortalusDev** [comment]
I spent all points, it returned unk talent error

**Comment by MaxtorCoder** [comment]
Yes, code is wrong, the first node that should be learned for specs should have GrantedRanks = 1 in code.

All SpecSetId should be checked from one of the Trait*.db2 files.
