### ISSUE TITLE
Script/MoltenCore - Crash server

### ISSUE THREAD

**Issue by Syllox** [TrinityCore/TrinityCore#28613]
### Description

Server crash when you kill a boss

### Expected behaviour

No crash

### Steps to reproduce the problem

1) .tele moltencore
2) kill one boss and see that server crash

### Branch

master

### TC rev. hash/commit

[97f3710](https://github.com/TrinityCore/TrinityCore/commit/97f3710fa7642c22b918d18ae132a84f69c6d45a)

### Operating system

Windows 11

### Custom changes

None

**Comment by mdX7** [comment]
Can you add crashlog (.txt)?

**Comment by funjoker** [comment]
Crashlog please compile in debug

**Comment by Syllox** [comment]
Oh my bad, totaly forget. Here, sorry: https://gist.github.com/Syllox/d1e20438c80098274c6f73794ca47213

**Comment by jackpoz** [comment]
it's an assertion failed btw
