### ISSUE TITLE
Crash server when looting

### ISSUE THREAD

**Issue by Syllox** [TrinityCore/TrinityCore#28610]
### Description

Crash server when I try to loot the rock gob near the MoltenCore entrance

Logs: https://gist.github.com/Syllox/994ec2d14d3bb374ce534a8cff20502d

### Expected behaviour

No crash

### Steps to reproduce the problem

1. .tele moltencore
2. Clic on the rock gob near the MC Entrance
3. After few second, the server crash

### Branch

master

### TC rev. hash/commit

[7312177](https://github.com/TrinityCore/TrinityCore/commit/731217703819c26645944091f47aec63b45c25d4)

### Operating system

Windows 11

### Custom changes

None

**Comment by Syllox** [comment]
Some difficulty with my git, but I found a simple fix: 

bool GameObject::IsFullyLooted() const              // Line: 3326
{
// Add condition when there are no loot \\
      if (!m_loot)
              return true;
.... }

**Comment by Shauren** [comment]
That change is not correct, it breaks despawn logic for objects lootable by many players
