### ISSUE TITLE
Items creation from character armor items

### ISSUE THREAD

**Issue by Dekz120** [TrinityCore/TrinityCore#28626]
### Description

Some armor items can create other items. For ex. item 23587 [Mirren's Drinking Hat](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?item=23587)
If character uses this hat, it creates some drink. But if inventory is full, it notifying "inventory is full", creates nothing and going on cooldown.

### Expected behaviour

After using item with full inventory it shouldn't go on cooldown without drink creation.

### Steps to reproduce the problem

1. `.additem 23587` and equip it
2. fill bags with some stuff
3. use the hat. notice hat didn't create a drink but goes on cooldown. Also you'll not get any mail with item later

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/pull/28582/commits/c9498d74a88f6a331c4e37e4194ceab90bc3f273

### Operating system

ubuntu x64 20.04

### Custom changes

None

**Comment by Jinnaix** [comment]
Thanks for using a direct-link to our AoWoW. I personally find that really helpful.

Looking through older comments, your issue does not seem to be trinitycore related. It worked like this on retail.

![image](https://user-images.githubusercontent.com/37972361/209671929-41a89c6f-0dc7-4861-8e3a-2c1155e7d267.png)
![image](https://user-images.githubusercontent.com/37972361/209671967-533215b0-d554-4773-b241-cb275a9166f9.png)

**Comment by Dekz120** [comment]
aah i see. my bad. thanks.
i guess it should be closed like not TC related issue.
