### ISSUE TITLE
DB/Instances: Fully spawn Algeth'ar Academy - map 2526

### ISSUE THREAD

**Issue by Odyssey** [TrinityCore/TrinityCore#28636]
### A few notes
* Link to the gist [here](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2).
* Includes entities and waypoints from permanent spawns which movement is not handled by scripts.
* [@CGUID+0](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L369) waypoints look a bit weird for a short time sometimes because of it being unloaded/loaded back again due to distance.
*  [@CGUID+229](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L239) and [@CGUID+230](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L240) should spawn or become visible by script after certain encounters are completed but are added to have all the Jump Pads in the DB in the meantime. 
* Commented this on discord before. The spells 397355 and 397357 share the same miscvalue (27450) for their create areatrigger effect and they generate two different sets of different create_properties values for two instances of the same areatrigger. There's no way to handle that currently so that's why one of them is commented out to avoid duplicating primary keys in DB.

### SQL fix

```sql
-- Quite long to paste in here, check gist link above.
```

### Branch

master

### TC rev. hash/commit

cf525beefd3c12e07b0883963806f202a6daff60

**Comment by meji46** [comment]
> Might be missing something for npc entry 196044 because all of its spawns have the model too close into the ground compared to retail, regardless of waypoints or not ([@CGUID+192](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L202), [@CGUID+198](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L208), [@CGUID+216](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L226), [@CGUID+217](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L227)).

Check if spawn has MovementFlag: Hover in sniff. If so, set the movement Ground::Hover (2) via creature_template_movement.

You should also check MovementFlags DisableGravity (Flight::DisableGravity), Root (Rooted) and Hover for entries 193033, 197406, 182599, 182706 and 195569

**Comment by Odyssey** [comment]
Ty, movement flags are sorted [now](https://gist.github.com/Odyssey/4f891e965af636341c8bebd491e22af2#file-algethar-sql-L739).

**Comment by Naddley** [comment]
Thanks for your time!
some stuff I want to mention:

- `conversation`, `areatrigger` and `creature_text` stuff can be deleted since we only INSERT it if we use/script it.
- Hungry Lasher (197398) missing Submerge Aura in _addon
- Meji allready mentioned it: you need to check the creature_movement_template data for some creatures (The books for example use "hover")

**Comment by Odyssey** [comment]
I removed what you've asked. Is the aura 390806? I don't seem to be able to parse it.

**Comment by Naddley** [comment]
I get this sql output for creature_template_addon:
```sql
(197398, 0, 0, 0, 1, 0, 0, 0, 0, 0, '390806 281206'), -- 197398 (Hungry Lasher) - Cosmetic - Submerge Emerge, Force Low LOD (Do Not Translate, No Display)
```

**Comment by Odyssey** [comment]
Ok, it's updated with everything so far.
