### ISSUE TITLE
Maraudon server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28646]
### Description

https://gist.github.com/PivanDepolo/4756b92294c82799068597de65b2d6d7

### Expected behaviour

Must not crash

### Steps to reproduce the problem

In front of the first boss in the Maradona dungeon there are mobs https://www.wowhead.com/npc=12222/ from which the drops https://www.wowhead.com/item=20767
After opening it, if you try to take healing or mana potions (there are no problems with reagents), it gives an error and the server apparently crashes.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/634c03890f88d508c6f3277f56af9ce429558918

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
2eea58f26e8fe88f3294dca3d4a38d6a20d68e07
