### ISSUE TITLE
Professions teacher

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28642]
### Description

Almost all profession teachers do not talk to the players. Only 2 NPCs in the undercity work.
When you right click on them, nothing happens.

### Expected behaviour

Should have a conversation with the NPC

### Steps to reproduce the problem

Approach any professions teacher and try to talk

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/fa361a40c81c5b1623fe2ff8f9a206868a6604f0

### Operating system

Debian 11

### Custom changes

None

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/commit/bd33d61a61f3e9edd7aa7e27ab83cf9e9af45404
