### ISSUE TITLE
profession mistake you can only learn one

### ISSUE THREAD

**Issue by sargentogamer86** [TrinityCore/TrinityCore#28649]
### Description

error that does not allow learning more than two professions.
For example, if I learn mining, I can't learn blacksmithing.
If I learn skinning I can't learn furriery.
does not allow learning second professions

### Expected behaviour

It would be expected that you could learn two professions

### Steps to reproduce the problem

step 1. create a character.
step 2. go to a profession instructor and learn a profession
step 3. go to another instructor and try to learn a second profession. (can be anyone Main professions such as blacksmithing, leatherworking, skinning, herbalism, alchemy, tailoring, inscription)

The result is that it will never allow you to learn a second profession.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. d124cc68c8f4+ 2022-12-23 23:08:31 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by Aokromes** [comment]
d90b526c28cf3b33e52d3ce432cdade1ce5e050e
