### ISSUE TITLE
Core/Arena: losing team wins the game if losing player leaves Arena

### ISSUE THREAD

**Issue by overy** [TrinityCore/TrinityCore#2865]
When you kill one player and  he leave, he win arena. 

some screen 

http://img43.imageshack.us/img43/7631/bugcda.jpg

you can see walle do 0 damage and win.

rev:  b12c75ecfa014a3f2004
##

**Comment by Gooyeth** [comment]
@tkrokli: yes, the issue is valid. Currently still bug.

Maybe I can look a little to solve it.

**Comment by jackpoz** [comment]
Could someone write a detailed description of the issue and some detailed how to reproduce steps ? everyone who commented described a different issue.

1. I had Players A and B against C and D
1. A killed C
1. C left (by clicking "Leave Areana" in the icon under the minimap), the match continued
1. D left, A and B won, C and D lost (showing in the PvP tab pressing H under Win/Loss

So I couldn't reproduce the issue (or one of the many reported here)

**Comment by illfated** [comment]
Maybe so much has changed since all those old reports, so it is no longer valid?
Anyway, a good and detailed description on how to reproduce is clearly needed.

**Comment by jackpoz** [comment]
Cannot reproduce
