### ISSUE TITLE
Zul'Aman server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28661]
### Description

This crash appears to occur when the player simply enters Zul'Aman.

https://gist.github.com/PivanDepolo/03003147888e39e61aae746837d5651b

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just enter Zul'Aman.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/b428f600b1e5cfd71e661f924a30d59f3970800d

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
ad843a54a3cc291d7d94b909bf3755a6a834794e
