### ISSUE TITLE
can not enter the world : World server is down

### ISSUE THREAD

**Issue by ycwjw2010** [TrinityCore/TrinityCore#28666]
### Description

Thank you for paying attention to my question!
My client version is 47213 . 
Here are some screenshots.

<img width="608" alt="屏幕截图_20230104_224656" src="https://user-images.githubusercontent.com/35825813/210718975-0057f81d-6351-4dff-ae9e-174b3a3ed660.png">
<img width="961" alt="屏幕截图_20230104_224710" src="https://user-images.githubusercontent.com/35825813/210718987-83b59638-6398-40a4-b050-58194e74e1a0.png">

### Expected behaviour

successfully enter the world.

### Steps to reproduce the problem

1.use [custom client launcher](https://github.com/Arctium/WoW-Launcher) mentioned in the wiki
2.login & select server
3.create character & enter world 

### Branch

master

### TC rev. hash/commit

fd4dd441b1f01dfcc9fbbd1e9b706f5e8599f5a8

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by ImmortalusDev** [comment]
How we are supposed to know what happened? Post crashlog

**Comment by dio85** [comment]
wrong launcher version maybe. for me work fine.

**Comment by ycwjw2010** [comment]
> How we are supposed to know what happened? Post crashlog

The error log is in the screenshot I submitted. If not enough，there are some logs : Server.log,DBErrors.log. which one do you need?
I'm a beginner. Thank you for your advice

**Comment by ImmortalusDev** [comment]
It is not enough, post crashlog from Crashes folder
