### ISSUE TITLE
Server crash due to AOE ability

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28677]
### Description

https://gist.github.com/PivanDepolo/fd7084c3ce4eda937f65337a1c19ce27

https://www.wowhead.com/zone=4131/magisters-terrace

In the Terrace of the Magisters dungeon, in the "Halls of Theory" room, when trying to kill the "scaled snake" mobs with an AOE spell, the server falls off.

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just kill  "scaled snake" 

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/cd62dc44916cd2d3e9522e1373e27bd01b27c84f

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
4bd780b464d17b4b041730986decf86a8255e6a5
