### ISSUE TITLE
GameObjectType::Transport::Update crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28673]
### Description

https://gist.github.com/PivanDepolo/bedff7b50f544dbade0647eb8d1394d7

Presumably when using any of these items, the server crashes
https://www.wowhead.com/item=11734
https://www.wowhead.com/item=11732
https://www.wowhead.com/item=11737
https://www.wowhead.com/item=11736/

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just try to use some of these items.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/d658641764b6d7f058d515aed8a333e3ca0a6e56

### Operating system

Debian 11

### Custom changes

None

**Comment by jackpoz** [comment]
do you get any error message in the console when this happens ?

**Comment by PivanDepolo** [comment]
> do you get any error message in the console when this happens ?

No.

**Comment by Ovahlord** [comment]
It's not the first crash of the kind and it's very likely that Shauren's recent grid searcher refactors did that

**Comment by PivanDepolo** [comment]
> It's not the first crash of the kind and it's very likely that Shauren's recent grid searcher refactors did that

Maybe.... New crash => https://gist.github.com/PivanDepolo/d8532485dd71a09f3df830e002f22dee

**Comment by Shauren** [comment]
Only relevant logs
> https://gist.github.com/PivanDepolo/d8532485dd71a09f3df830e002f22dee
https://gist.github.com/PivanDepolo/c4260313247e3f5a91faea994b7ffc1d
