### ISSUE TITLE
suggestion for correction of character values

### ISSUE THREAD

**Issue by sargentogamer86** [TrinityCore/TrinityCore#28670]
### Description

There is a disparity between the health values ​​of characters created on the trinity server vs. the data on the official server
situation that does not allow you to enjoy the content in a normal way, understanding that this is a simulator and not the official server, at least it is required that the values ​​be as similar as possible to the official server since the problem that has arisen is that the characters having so little life they end up dying too quickly since the npc kill them very easily when on the official server it is not that difficult.

### Expected behaviour

It is expected that the characteristics of the characters are the closest to the official server and thus allow a more real testing and testing activity without having to depend on GM commands

I attach comparative images with a character created on the trinity server and the official server to see the difference and try to correct it in future core updates

**official server**

![WoWScrnShot_010523_213459](https://user-images.githubusercontent.com/51180754/210920054-f57755da-e280-4afa-bbf1-0baacd9e3517.jpg)

**Trinity Core**

![WoWScrnShot_010523_213645](https://user-images.githubusercontent.com/51180754/210920316-cce57708-f65a-475a-836e-9789bdca44c5.jpg)

It can be seen that on the official server the character data is a little higher.
In addition, the characteristics of each character are more adjusted.

### Steps to reproduce the problem

Step 1. create a character on the official server and in the trinity core

Step 2. compares the values ​​of health, mana, stamina and other characteristics of the characters

### Branch

master

### TC rev. hash/commit

TrinityCore rev. d124cc68c8f4+ 2022-12-23 23:08:31 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Naddley** [comment]
since stats are updated with SimC they should now be close to retail.
