### ISSUE TITLE
DB/Elwynn - Some quest fixes

### ISSUE THREAD

**Issue by ryanch94** [TrinityCore/TrinityCore#28671]
### Description

- Fixes missing quest reward text for quests 26150 and 63447
- Adds quest starter and ender data for quest 63447
- Adds requirement for quest 54 to be completed before 62 is offered
- Fixes quest item drop rates for quests 86 and 112

### SQL fix

```sql
-- 26150 (A Visit With Maybell)
-- 63447 (Fear No Evil)
DELETE FROM `quest_offer_reward` WHERE `ID` IN (26150, 63447);
INSERT INTO `quest_offer_reward` (`ID`, `RewardText`)
VALUES (26150, "William sent you? Bless his soul. I... I'm ok... It's just... Well..."),
(63447, "I think you now understand the power of the Light. The Light giveth hope, brother and the Light taketh from the darkness! BLESSED BE THE LIGHT!");

-- 63447 (Fear No Evil)
DELETE FROM `creature_queststarter` WHERE id = 951 AND quest = 63447;
INSERT INTO `creature_queststarter` (`id`, `quest`)
VALUES (951, 63447);

DELETE FROM `creature_questender` WHERE id = 951 AND quest = 63447;
INSERT INTO `creature_questender` (`id`, `quest`)
VALUES (951, 63447);

-- 86 (Pie for Billy - Drop rate for quest item was only 21 here. Should be 100 judging by playthroughs on YT)
UPDATE `creature_loot_template` SET `Chance` = 100 WHERE `Entry` = 113 AND `Item` = 60401;
-- 112 (Collecting Kelp - drop rate feels much too low here, judging by YT playthroughs, should be at least 50% if not more)
UPDATE `creature_loot_template` SET `Chance` = 50 WHERE `Item` = 1256 AND `Entry` IN (285, 735);
-- 11 (Riverpaw Gnoll Bounty - Judging by YT videos this drops every time during quest)
UPDATE `creature_loot_template` SET `Chance` = 100 WHERE `Entry` IN (97, 478) AND `Item` = 782;

-- Quest 325 (Armed and Ready) marked obsolete by Blizz: https://www.wowhead.com/quest=325/armed-and-ready
INSERT INTO `disables` (`sourceType`, `entry`, `flags`, `comment`)
VALUES (1, 325, 0, "Deprecated quest: Armed and Ready");
```

### Branch

master

### TC rev. hash/commit

d658641

**Comment by Naddley** [comment]
Hi; thanks for your time.
First a small question... do you use WPP for your SQL output? you seems to miss some stuff WPP do, like VerifiedBuild in *_quest_starter.
If no I recommend you to use WPP with DBC and Database connection enabled for SQL stuff.

- Quest 62 "The Fargodeep Mine" dont have a prevQuest (I can accept it without do a single Quest in Elwynn with a lvl 10  character)
- You can use one single delete statement instead of multiple to delete ID´s (quest_offer_reward)

**Comment by ryanch94** [comment]
Hey @Naddley, no these aren't from sniffs, just wrote them up as I played based on my own experience with it. Should I be prioritising data from sniffs only? I can try get sniff data if needed instead.

I've edited the query to address both your points

**Comment by Naddley** [comment]
Yes, we ALWAYS use Sniff data if possible and dont "guess" stuff.

**Comment by ryanch94** [comment]
@Naddley @acidmanifesto Cool, I'll close this for now and re-open a new issue if I get good sniffs for these 😅
