### ISSUE TITLE
Some crashes cause unknown

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28680]
### Description

Maybe this crashlogs will help improve TrinityCore

https://gist.github.com/PivanDepolo/735171f66867e69de2e82c415c03b01d
https://gist.github.com/PivanDepolo/763a5c78df6da49c29f6345342c1c334
https://gist.github.com/PivanDepolo/ce9467bc29457d1384d360784ada511e
https://gist.github.com/PivanDepolo/ee49b32987fbd09ba489acd9c826cec8
https://gist.github.com/PivanDepolo/64eca448c8085760372cadd616bf14a1
https://gist.github.com/PivanDepolo/4d07a002fcf15da204a229bf30b0084d
https://gist.github.com/PivanDepolo/daac169627129ea904893ff5f43da0f0
https://gist.github.com/PivanDepolo/e04012cdb1c52f72280bfcfb553c0fa8
https://gist.github.com/PivanDepolo/5e371181e813be471f2cd83d7bd091a8
https://gist.github.com/PivanDepolo/e91b60a9aa8ce9a0f8c2984570d52651
https://gist.github.com/PivanDepolo/d9eb992ab51b5ceebab1bdd94466973b
https://gist.github.com/PivanDepolo/83915a2116ac453f1b1f5f45cba5e50a

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Sorry I don't know how to reproduce

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/b6820a706f46f18b9652fcd9806e4bec8805d29d

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
most of them are related to outdoor pvp.

**Comment by Aokromes** [comment]
updated by https://github.com/TrinityCore/TrinityCore/commit/d86726e670db5813da48c60dde1d6a59270a3417

**Comment by PivanDepolo** [comment]
https://gist.github.com/PivanDepolo/1a097c99364c8ddc787a24035fd6b8b6

**Comment by Aokromes** [comment]
you don't need to post more outdoorpvp crashes.

**Comment by PivanDepolo** [comment]
> you don't need to post more outdoorpvp crashes.

I just decided to add this here, because I do not know how to reproduce them. Okay, got it.
