### ISSUE TITLE
CharacterCreating.Disabled.RaceMask  and CharacterCreating.Disabled.ClassMask lacks disables for  dracthyr

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#28684]
### Description

^^ that.

### Expected behaviour

CharacterCreating.Disabled.RaceMask  and CharacterCreating.Disabled.ClassMask to be implemented.

### Steps to reproduce the problem

try to remove dracthyr race and class.

### Branch

master

### TC rev. hash/commit

d86726e670db5813da48c60dde1d6a59270a3417 

### Operating system

all

### Custom changes

none

**Comment by Aokromes** [comment]
still missing

**Comment by CraftedRO** [comment]
there was a time when Aok wasn't lazy https://github.com/TrinityCore/TrinityCore/commit/78bc0c41e9156d9211b5d0a49cb260d543b1c175

**Comment by CraftedRO** [comment]
I guess 98304 racemask - Dracthyr  /  4096 classmask - Evoker
