### ISSUE TITLE
Druid Spell Entangling Roots

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28688]
### Description

The "[Entangling Roots](https://www.wowhead.com/spell=339/entangling-roots)" spell does not work correctly. While active, it deals damage, which it shouldn't.

### Expected behaviour

Described above

### Steps to reproduce the problem

Just create a druid and try to use that spell.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/4bd780b464d17b4b041730986decf86a8255e6a5

### Operating system

Debian 11

### Custom changes

None

**Comment by mdX7** [comment]
also affects Mass Entanglement spellid 102359
