### ISSUE TITLE
List of Druid spells not working correctly

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28686]
### Description

1) The "[Entangling Roots](https://www.wowhead.com/spell=339/entangling-roots)" spell does not work correctly. While active, it deals damage, which it shouldn't.

2) Talent "[Pouncing Strikes](https://www.wowhead.com/spell=390772/pouncing-strikes)" does not work

3) [Primal Wrath](https://www.wowhead.com/spell=285381/primal-wrath) does not work correctly.
Regardless of the combo length, it inflicts a debuff lasting 4 seconds. Since such a time is not written in this skill at all, I think that it somehow refers to the skill "Primal Wrath"

4) Talent "[Predator](https://www.wowhead.com/spell=202021/predator)" does not work

5) The "[Sudden Ambush](https://www.wowhead.com/spell=384667/sudden-ambush)" talent does not work.
The buff appears after using any ability. The buff itself does nothing.

6) "[Travel Form](https://www.wowhead.com/spell=783/travel-form)" does not work properly. It always gives 40% haste, no matter what level the character is either in combat or not.

### Expected behaviour

Described above

### Steps to reproduce the problem

Just create a druid.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/d86726e670db5813da48c60dde1d6a59270a3417

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
don't post multiple bugs on one issue.

**Comment by PivanDepolo** [comment]
> 2\. Talent "[Pouncing Strikes](https://www.wowhead.com/spell=390772/pouncing-strikes)" does not work

Okay, done.
