### ISSUE TITLE
Sorting items in a bag

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28687]
### Description

Unable to sort items in a bag.

### Expected behaviour

It should be possible to sort the items in the bag.

### Steps to reproduce the problem

Just open your item bag and try sorting.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/d86726e670db5813da48c60dde1d6a59270a3417

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17564
