### ISSUE TITLE
[Spell] Overspark

### ISSUE THREAD

**Issue by Discover-** [TrinityCore/TrinityCore#2868]
http://old01.wowhead.com/spell=35579

Should summon them randomly 5 yards around the caster. Right now they are all ten cast at caster's point.

Core: https://github.com/TrinityCore/TrinityCore/commit/e3f4cca534752851775f5174901fb8a43460cdbb
Database: TDB 335.11.41

**Comment by Killyana** [comment]
It's fixed, don't know how or when.
