### ISSUE TITLE
Quest: The Lesson of the Burning Scroll

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28685]
### Description

https://www.wowhead.com/quest=29408/the-lesson-of-the-burning-scroll

Scroll doesn't burn

### Expected behaviour

Scroll should burn

### Steps to reproduce the problem

Just try to burn the scroll.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/d86726e670db5813da48c60dde1d6a59270a3417

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
NYI
https://github.com/TrinityCore/TrinityCore/pull/17021
