### ISSUE TITLE
Server crash when entering message in chat

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28695]
### Description

https://gist.github.com/PivanDepolo/78638b08083fea5b7266025469c33243

When you write to the chat (general, channel 5) and after pressing enter immediately server is crashing

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Described above

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/397d77511811312daaa6ce35f6a6512b41046f6b

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
Same as #28715
