### ISSUE TITLE
Unable to bind at Grom'arsh Crash Site

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#28696]
### Description

Peon Gakra's title says he is both an innkeeper and supplier, but when right-clicking him it is only possible to trade with him.  There is no option to bind your hearthstone.

https://imgur.com/lMc9amG

### Expected behaviour

You should be able to bind to this innkeeper

### Steps to reproduce the problem

Visit Peon Gakra at Grom'arsh Crash Site and right-click.

https://www.wowhead.com/npc=29944/peon-gakra

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 31e7516b83aa+ 2022-11-27 10:51:30 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Operating system

Linux Mint 21 / Ubuntu 22

### Custom changes

None

**Comment by CraftedRO** [comment]
I can't believe I spent two hours for a flag :)
```sql
-- Peon Gakra <Innkeeper & Supplies>
UPDATE `creature_template` SET `npcflag`=`npcflag`|65665 WHERE `entry`=29944;
```

**Comment by CraftedRO** [comment]
not sure if we shoud add this zone as tavern or whatever is called

**Comment by infidelus** [comment]
The crashed zeppelin hull is an inn from patch 3.0.8 per the notes in the Wowhead link.

**Comment by meji46** [comment]
There can be an areatrigger (areatrigger_tavern). The only problem is that this system doesn't allow to define tavern for a single faction

**Comment by Aokromes** [comment]
oh i checked, it's a tavern already.

**Comment by CraftedRO** [comment]
SELECT * FROM `areatrigger_tavern` WHERE `id`=4429;
Does this result something for you ?

**Comment by CraftedRO** [comment]
```sql
SELECT * FROM `areatrigger_tavern` WHERE `id`=4429;
```
Does this result something for you ?

**Comment by CraftedRO** [comment]
ah nvm seems I messed areatrigger id-s :)

**Comment by CraftedRO** [comment]
this one also can be merged
