### ISSUE TITLE
Emergency Measures - Unable to directly attack worgs

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#28697]
### Description

When trying to complete this quest to gather the worg furs required, it is impossible to directly attack the worgs, though they do show as enemies.  You can only use AOE skills to hit them.  Additionally, only about three of the worgs drop the furs.

### Expected behaviour

You should be able to target and attack the worgs with all your skills/spell.

### Steps to reproduce the problem

Visit Gimorak's Den in The Storm Peaks and attempt to attack any worg.

https://www.wowhead.com/wotlk/quest=13000/emergency-measures

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 31e7516b83aa+ 2022-11-27 10:51:30 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Linux Mint 21 / Ubuntu 22

### Custom changes

None

**Comment by CraftedRO** [comment]
```sql
-- Remove retarded bytes 2 for Cavedweller Worg
UPDATE `creature_template_addon` SET `bytes2`=0 WHERE `entry`=30164;
```

**Comment by CraftedRO** [comment]
Drop chance is atm 20% for [Worg Fur](https://www.wowhead.com/wotlk/item=42510/worg-fur), on wowhead is 27.23% I won't change it atm idk

![sqsq](https://user-images.githubusercontent.com/24683355/211552649-fbf26fda-48d6-402c-b4e7-1c078708331c.PNG)

**Comment by CraftedRO** [comment]
Drop chance is atm 20% for [Worg Fur](https://www.wowhead.com/wotlk/item=42510/worg-fur), on wowhead is 27.23%
![sqsq](https://user-images.githubusercontent.com/24683355/211552649-fbf26fda-48d6-402c-b4e7-1c078708331c.PNG)

```sql
-- update worg fur drop rate
UPDATE `creature_loot_template` SET `Chance`=27 WHERE Item=42510 AND `Entry`=30164;
```

**Comment by CraftedRO** [comment]
Drop chance is atm 20% for [Worg Fur](https://www.wowhead.com/wotlk/item=42510/worg-fur), on wowhead is 27.23%
![sqsq](https://user-images.githubusercontent.com/24683355/211552649-fbf26fda-48d6-402c-b4e7-1c078708331c.PNG)

```sql
-- update worg fur drop rate
UPDATE `creature_loot_template` SET `Chance`=27 WHERE `Item`=42510 AND `Entry`=30164;
```

**Comment by CraftedRO** [comment]
```sql
-- Remove retarded PvPFlags for Cavedweller Worg
UPDATE `creature_template_addon` SET `PvPFlags`=0 WHERE `entry`=30164;
```


Drop chance is atm 20% for [Worg Fur](https://www.wowhead.com/wotlk/item=42510/worg-fur), on wowhead is 27.23%
![sqsq](https://user-images.githubusercontent.com/24683355/211552649-fbf26fda-48d6-402c-b4e7-1c078708331c.PNG)

```sql
-- update worg fur drop rate
UPDATE `creature_loot_template` SET `Chance`=27 WHERE `Item`=42510 AND `Entry`=30164;
```

**Comment by infidelus** [comment]
I tried running

>UPDATE `creature_template_addon` SET `PvPFlags`=0 WHERE `entry`=30164;

But got:

>/* SQL Error (1054): Unknown column 'PvPFlags' in 'field list' */

**Comment by CraftedRO** [comment]
first update your database and core to 6f835c233f7605d74926a2a3058634c9de478617

**Comment by infidelus** [comment]
Thanks.  I've updated to TrinityCore rev. 128339730caf+ 2023-01-10 15:46:51 +0100 (3.3.5 branch).  The SQL command now works, though I still can't target the worgs (assuming that's what turning the PvP flag off is supposed to do ...)

**Comment by CraftedRO** [comment]
ok I'll check it again, the old version with bytes2 worked

**Comment by CraftedRO** [comment]
well for me it works, have you restarted your server after applying the fix ?


https://user-images.githubusercontent.com/24683355/212182683-79f631cb-f7d5-4c8b-b52d-60a8e4b94350.mp4

**Comment by CraftedRO** [comment]
don't close it, It haven't been merged

**Comment by infidelus** [comment]
Apologies.
