### ISSUE TITLE
Mage Talent Slow

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28713]
### Description

https://www.wowhead.com/spell=31589/slow

The spell doesn't work. No slowdown effect.

### Expected behaviour

Reduces the target's movement speed by 50% for 15 sec.

### Steps to reproduce the problem

Just create mage with this learned talent and use spell.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/65e787d18be898532363fea3f8847fa4d7f21192

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
Works fine on bacfbec25180cd0a02fec20e788d74e2fcaf1a0c
