### ISSUE TITLE
Aura 65772 server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28716]
### Description

https://gist.github.com/PivanDepolo/14106e0e43034506b5e564b1acc5933d

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Use following command: .aura 65772

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/65e787d18be898532363fea3f8847fa4d7f21192

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
Crash log identical to #28715, steps to reproduce useless
