### ISSUE TITLE
Upper Blackrock Spire

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28738]
### Description

https://www.wowhead.com/zone=7307/upper-blackrock-spire completely empty dungeon

### Expected behaviour

Must be NPCs

### Steps to reproduce the problem

Just enter the dungeon and check

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/fada839526aad1ff7ee1d0f38f77ab5c2a29ab7e

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
duplicate. 
https://github.com/TrinityCore/TrinityCore/issues/12975
