### ISSUE TITLE
Friendly NPCs at Dun Niffelem Attackable after update

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#28741]
### Description

I collected some quests from NPCs at Dun Niffelem the other day, but after updating to TrinityCore rev. 128339730caf+ 2023-01-10 15:46:51 +0100 (3.3.5 branch) today these NPCs, while still showing friendly are now attackable:

https://ibb.co/cTRctQr

This has the additional downside of meaning I cannot hand in any completed quests.

### Expected behaviour

Friendly NPCs should not be attackable

### Steps to reproduce the problem

Try to interact with NPCs.  Sword icon shows for mouse and right-clicking initiates a fight with the NPC

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 128339730caf+ 2023-01-10 15:46:51 +0100 (3.3.5 branch)

### Operating system

Linux Mint 21 / Ubuntu 22

### Custom changes

None

**Comment by Aokromes** [comment]
disable on war.

**Comment by CraftedRO** [comment]
![D6gPkX8](https://user-images.githubusercontent.com/24683355/212184772-35f8df16-0fad-4cbc-8c3a-2dcd473e987b.png)

**Comment by infidelus** [comment]
After more than a decade playing WoW (on and off) I didn't even know that option was there.  Presumably something in a git update changed it?

**Comment by Aokromes** [comment]
no, it's there since ever.

**Comment by infidelus** [comment]
Sorry, I wasn't clear.  The War flag was clearly disabled before I updated the server today as I was interacting with the NPCs.  So either I hit a shortcut combo accidentally which switched it on at some point today or something in the update switched the flag to War as I've never touched that particular menu in WoW before - as mentioned I wasn't even aware of it as I usually do PvE with the exception of the odd battleground.
