### ISSUE TITLE
Rogue spell Gouge and pvp trinket

### ISSUE THREAD

**Issue by Dekz120** [TrinityCore/TrinityCore#28744]
### Description

If character is under [Gouge](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=1776) spell and uses pvp trinket, Gouge disappears only for a second. After trinking, spell applies on character again for rest of duration(without casting Gouge by rogue)

here the backtraces for regular spell cast(first link) and further spell application without rogue's cast (2d link)
[gouge cast backtrace](https://gist.githubusercontent.com/Dekz120/1f7d7828d3776e511998a415ff5a0b78/raw/8ad458ed9fdf2b956f29d510b9ff2ff8de6178c8/Gouge_1th_cast.txt)
[2d gouge apply(After trinking](https://gist.githubusercontent.com/Dekz120/1f7d7828d3776e511998a415ff5a0b78/raw/8ad458ed9fdf2b956f29d510b9ff2ff8de6178c8/Gouge_without_cast.txt)

### Expected behaviour

Gouge should be completely dispelled after pvp trinket usage

### Steps to reproduce the problem

1. Take 2 characters(one of them rogue)
2. Cast Gouge on other one
3. Use the pvp trinket to dispell it, notice you've got another stun without rogue help ;)

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/dc221604d9971eabb95cdbaececa28765a6dfa9a

### Operating system

ubuntu x64 20.04

### Custom changes

None

**Comment by Doombringer-MarAlith** [comment]
Gouge is not the only spell that is affected by this, it's more of a general issue

**Comment by Shauren** [comment]
This was fixed in 835e2918319ed20109992086311a2c146140937f
