### ISSUE TITLE
DB/Creature/Cosmetic: Aldor Neophyte at Aldor Rise shoud only be draenei not bloodelf

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28743]
### Description

https://www.wowhead.com/wotlk/npc=19153/aldor-neophyte#models

https://wow.tools/db/creatures.php#search=19153&page=1&sort=0&desc=asc

![WoWScrnShot_011323_141924](https://user-images.githubusercontent.com/24683355/212319631-1271c448-5de8-4d5a-8e50-94fd7dbc1c59.jpg)

### SQL fix

```sql
-- they only have one gender and it seems DisplayID_Other_Gender will be dropped in the future
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID` IN (18566,18567,18568,18569);
```

### Branch

3.3.5

### TC rev. hash/commit

128339730caf

**Comment by Nyr97** [comment]
We're not to modify creature_model_info directly. This data comes off from Blizzard directly, so you should take a sniff at their models (delete Cache before doing so).

**Comment by CraftedRO** [comment]
I don't have retail active account so I can't do that, however they require some event too in the future.

**Comment by Aokromes** [comment]
i think you can reach shattrah with a trial account.

**Comment by CraftedRO** [comment]
ok I'm in shattrath now, let's see how good are our sniffers and if I will be able to understand smth from

![WoWScrnShot_041123_161926](https://user-images.githubusercontent.com/24683355/231175535-5421c98b-3df6-4bac-a202-b4e826f570b9.jpg)

**Comment by CraftedRO** [comment]
Well I sniffed the whole event still coudn't find any info about creature_model_info -> DisplayID_Other_Gender, they all have gender 0

**Comment by CraftedRO** [comment]
Since DisplayID_Other_Gender can't be sniffed I guess this is the correct fix atm for this case.

**Comment by CraftedRO** [comment]
Now wpp export creature_model_info too so the fix was valid.

this is how sql output looks on a parsed shattrath walk (notice our old `displayid` IN (18566,18567,18568,18569) inside):
```sql
UPDATE `creature_model_info` SET `DisplayID_Other_Gender`=0 WHERE `DisplayID` IN (18741, 18742, 18740, 18567, 18548, 18552, 18568, 18569, 17907, 18566, 18539, 18537, 17904, 18743, 17903, 18550, 20168, 19129, 20167, 18520, 19131, 18619, 20170, 19132, 20169);
UPDATE `creature_model_info` SET `Gender`=1, `DisplayID_Other_Gender`=0 WHERE `DisplayID`=17905;
UPDATE `creature_model_info` SET `BoundingRadius`=0.874500036239624023, `CombatReach`=1.65000009536743164 WHERE `DisplayID`=599;
UPDATE `creature_model_info` SET `BoundingRadius`=0.305999994277954101, `CombatReach`=1.5 WHERE `DisplayID`=19160;
UPDATE `creature_model_info` SET `BoundingRadius`=2.437281131744384765 WHERE `DisplayID` IN (17072, 17870);
UPDATE `creature_model_info` SET `Gender`=1 WHERE `DisplayID`=22910;
UPDATE `creature_model_info` SET `BoundingRadius`=7.311843395233154296 WHERE `DisplayID`=18135;
UPDATE `creature_model_info` SET `Gender`=2 WHERE `DisplayID`=13069;
```
