### ISSUE TITLE
Trolls is Gone Crazy! - Lock Opener doesn't work

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#28747]
### Description

After collecting "Lock Opener's" from the Drakuru mobs, using them on the Capture Rageclaw doesn't work.  You hear the noise as though the lock has been smashed, but the number of freed Rageclaws remains at zero no matter how may openers you use or where you stand in relation to the Captured Rageclaws.

### Expected behaviour

Using the lock opener should result in the Captured Rageclaws being freed

### Steps to reproduce the problem

Kill Drakuru to collect "Lock Openers"
Use the lock openers in the vicinity of the Captured Rageclaws

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 128339730caf+ 2023-01-10 15:46:51 +0100 (3.3.5 branch)

### Operating system

Linux Mint 21 / Ubuntu 22

### Custom changes

None

**Comment by Aokromes** [comment]
works for me (TM)

https://i.imgur.com/9aGBau3.png

**Comment by infidelus** [comment]
I've 'freed' about thirty rageclaws now and the count stays at zero so there's something not right somewhere.

**Comment by Aokromes** [comment]
.gm off?

**Comment by CraftedRO** [comment]
the quest works for me even with .gm on and also tested with no gm account

https://user-images.githubusercontent.com/24683355/212468742-cc024968-e185-4326-b2f2-7e3ab9a1e6b1.mp4

**Comment by infidelus** [comment]
Tried again, typing .gm off before starting.  No difference.  I don't have any screen recording software installed but here's four screenshots showing continued attempts with no change to the amount of freed rageclaws.  You hear the noise, they don't move and there's no chat bubble from them or text to say anything has happened.

![FirstTry](https://user-images.githubusercontent.com/39056969/212470396-247f672b-c7e6-4e7c-b2d7-42a1ed158a65.png)
![SecondTry](https://user-images.githubusercontent.com/39056969/212470402-24c893bc-9034-41ef-9205-0456cfb88459.png)
![ThirdTry](https://user-images.githubusercontent.com/39056969/212470405-32299c6b-beeb-4614-9f60-de1a0f431044.png)
![FourthTry](https://user-images.githubusercontent.com/39056969/212470398-2e06e140-3afd-42e1-aeb1-08173677cdd1.png)

**Comment by Aokromes** [comment]
maybe something you changed broke it on your server.

**Comment by CraftedRO** [comment]
tested now with bloodelf mage and it works too, try to clean install your core and database

**Comment by infidelus** [comment]
Apart from running the provided SQL queries for the other couple of issues I've raised over the last week, I haven't changed anything.  It's built from source and just run.  This was an issue on the November build when I first tried this quest and is still the same issue with another clean build which I did a couple of days ago as directed.

**Comment by infidelus** [comment]
Any specific thing I can do to clean the database without losing character progress?

**Comment by CraftedRO** [comment]
yea, just drop world database and clean insert it

**Comment by CraftedRO** [comment]
yea, just drop world database and clean insert it from here https://github.com/TrinityCore/TrinityCore/releases/tag/TDB335.22101

**Comment by infidelus** [comment]
Thanks.  Not sure what was wrong then but dropping the world DB and recreating worked.
