### ISSUE TITLE
formattedMessage server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28753]
### Description

I hope that crashlog will help to improve TC <3
https://gist.github.com/PivanDepolo/9e3969ee02e00ccc4edebfbf8ca536f2

### Expected behaviour

Must not crash.

### Steps to reproduce the problem

Unfortunately, I do not know(

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/db8504426796ce39f1871aa1871bae10e0408f9f

### Operating system

Debian 11

### Custom changes

None

**Comment by jackpoz** [comment]
It seems so be an infinite loop on logout when player has an aura that casts 92237 when removed

**Comment by Shauren** [comment]
No, its even worse... spell_linked_spell table has a row that makes aura 92237 cast itself when removed...
