### ISSUE TITLE
Incomplete information about the item in the guild bank.

### ISSUE THREAD

**Issue by kvolk2git** [TrinityCore/TrinityCore#28751]
### Description

Some items from the guildbank do not display all their characteristics, after moving this item from the guildbank to the bag, the characteristics begin to be displayed correctly.
https://www.wowhead.com/tbc/item=31182/legion-helm

Wrong:
![WoWScrnShot_011523_004745](https://user-images.githubusercontent.com/78740198/212498850-e42b9f93-bd09-43e4-96c7-92512d6e0d60.jpg)
Correct:
![WoWScrnShot_011523_004752](https://user-images.githubusercontent.com/78740198/212498852-12d891e4-86d3-426f-8916-439261d2c42a.jpg)

### Expected behaviour

*

### Steps to reproduce the problem

1) put item https://www.wowhead.com/tbc/item=31182/legion-helm in guildbank and see stats.
2) put item https://www.wowhead.com/tbc/item=31182/legion-helm in bag and see stats.

### Branch

3.3.5

### TC rev. hash/commit

128339730cafefba04ca8b1b6c72ed4ea9315bd3

### Operating system

Ubuntu

### Custom changes

no

**Comment by Lordron** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Guilds/Guild.cpp#L2896
RandomPropertiesID & RandomPropertiesSeed are not initialized after https://github.com/TrinityCore/TrinityCore/commit/f0fe5f8b669fb9f15b18be1cd3cab407e30ffa52#diff-1e0fe7d569f34443ffa4ed5a0ef0877a27607da9c960e6440a40d7179cb30d2e

**Comment by CraftedRO** [comment]
128339730caf Confirm, strange that in three years noone noticed :)
