### ISSUE TITLE
Orgrimmar impossible use portal to Blasted Lands

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28750]
### Description

It is not possible to use the [Blasted Lands](https://www.wowhead.com/zone=4/blasted-lands) Portal in the [Cleft of Shadow](https://www.wowhead.com/zone=5166/cleft-of-shadow). An error appears with the text "Action is not possible. Reason: %s"

### Expected behaviour

Should be able to teleport

### Steps to reproduce the problem

Go to the cleft of shadowsand click on the portal and you will see the problem.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/db8504426796ce39f1871aa1871bae10e0408f9f

### Operating system

Debian 11

### Custom changes

None

**Comment by Nyr97** [comment]
Is this portal blizzlike anyway? Most (if not) all portals were moved to the Portal Room.

**Comment by Aokromes** [comment]
nope, it must be removed from there.

**Comment by Naddley** [comment]
seems like Orgrimmar dont have a Portal to Blasted Lands on retail anymore.

**Comment by shamage** [comment]
Maybe this will help clarify the issue a little:  [Travel from Orgrimmar to Blasted Lands](https://us.forums.blizzard.com/en/wow/t/travel-from-orgrimmar-to-blasted-lands/1229445)

**Comment by Nyr97** [comment]
If I recall correctly, that portal was replaced by "talk to this mage guy next to the Outlands portal", which will take you to the Blasted Lands (non-Draenor).
