### ISSUE TITLE
2023_01_09_00_world.sql issue

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#28760]
### Description

Having had to drop my world database due to a corruption I decided to do a clean TC pull so deleted the original TC folder and started from scratch.  After compiling the build and trying to run worldserver I got an error with this particular SQL file (sql/old/3.3.5a/world/22101_2023_01_16/2023_01_09_00_world.sql).

The file is trying to create a bunch of new columns in two tables, but if you run it on a database that already has the auth & characters databases, it errors out with a duplicate column error because the SQL file assumes you don't have the affected columns and tries to create them.

While I can read the basics of an SQL file, I am by no means an expert but would suggest an 'IF NOT EXISTS' entry to check so worldserver doesn't crash on this.  The same goes for the DROP COLUMN entries.

My SQL 'fix' below is based on a quick internet search on the subject so I have no idea if the code is actually correct.

### SQL fix

```sql
ALTER TABLE `creature_template_addon`   
IF NOT EXISTS (
	ADD COLUMN `StandState` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `MountCreatureID`,
	ADD COLUMN `AnimTier` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `StandState`,
	ADD COLUMN `VisFlags` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `AnimTier`,
	ADD COLUMN `SheathState` TINYINT UNSIGNED DEFAULT 1 NOT NULL AFTER `VisFlags`,
	ADD COLUMN `PvPFlags` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `SheathState`;
)


ALTER TABLE `creature_addon`   
IF NOT EXISTS (
	ADD COLUMN `StandState` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `MountCreatureID`,
	ADD COLUMN `AnimTier` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `StandState`,
	ADD COLUMN `VisFlags` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `AnimTier`,
	ADD COLUMN `SheathState` TINYINT UNSIGNED DEFAULT 1 NOT NULL AFTER `VisFlags`,
	ADD COLUMN `PvPFlags` TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `SheathState`;
)

-- Conversion done, drop old columns
ALTER TABLE `creature_template_addon`  
IF EXISTS (
	DROP COLUMN `bytes1`, 
	DROP COLUMN `bytes2`;
)
	
ALTER TABLE `creature_addon`  
IF EXISTS (
	DROP COLUMN `bytes1`, 
	DROP COLUMN `bytes2`;
)
```

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 80884e32ef6e+ 2023-01-16 11:10:56 +0000 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by Aokromes** [comment]
you don't need to apply that if you download tdb 3.3.5a from 2023.

**Comment by infidelus** [comment]
Thanks for the reply.  Even with the latest release (TDB_full_world_335.23011_2023_01_16.7z) dropped into the server/bin folder I'm still seeing this error:

> ERROR 1060 (42S21) at line 1 in file: '/home/$USER/TrinityCore/sql/old/3.3.5a/world/22101_2023_01_16/2023_01_09_00_world.sql': Duplicate column name 'StandState'
> Applying of file '/home/$USER/TrinityCore/sql/old/3.3.5a/world/22101_2023_01_16/2023_01_09_00_world.sql' to database 'world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from TrinityCore repository with your sql client. If you are a developer, please fix your sql query.
> Could not update the World database, see log for details.

This is from a fresh pull today.

**Comment by jackpoz** [comment]
Which sql files are applied when you start worldserver ?

**Comment by CraftedRO** [comment]
@infidelus just do what Shauren said in the other issue and your problem shoud be fixed https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227

**Comment by CraftedRO** [comment]
@infidelus you can try do what Shauren told in the other issue https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227

Clear hash for 2023_01_09_00_world.sql  in auth > updates table if you have that row, but I suggest you to better drop then reinsert latest tdb world update.

**Comment by CraftedRO** [comment]
@infidelus you can try do what Shauren told in the other issue https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227

Clear hash for 2023_01_09_00_world.sql  in auth > updates table if you have that row, but I suggest you to better drop then reinsert latest world tdb

**Comment by CraftedRO** [comment]
@infidelus you can try do what Shauren said in the other issue https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227

Clear hash for 2023_01_09_00_world.sql  in auth > updates table if you have that row, but I suggest you to better drop then reinsert latest world tdb

**Comment by CraftedRO** [comment]
@infidelus you can try do what Shauren said in the other issue https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227

Clear hash for 2023_01_09_00_world.sql  in world > updates table if you have that row, but I suggest you to better drop then reinsert latest world tdb

**Comment by MrSmite** [comment]
To answer the OP's question, I don't think mySQL supports that syntax (I think MariaDB does) and I can't check right now but the easier way is to create a procedure and then just call it:

```SQL
CREATE PROCEDURE AddMissingColumn(
	IN db_name tinytext,
	IN tbl_name tinytext,
	IN col_name tinytext,
	IN field_def text)
BEGIN
	IF NOT EXISTS (
		SELECT * FROM information_schema.COLUMNS
		WHERE column_name=col_name
		and table_name=tbl_name
		and table_schema=db_name
		)
	THEN
		set @stmt_add_col=CONCAT('ALTER TABLE ',db_name,'.',tbl_name,
			' ADD COLUMN ',col_name,' ',field_def);
		prepare stmt from @stmt_add_col;
		execute stmt;
	END IF;
end;


-- Database() in the call below will get the name of the current database
-- I can't remember but you might need to remove the `` around the column names in the AFTER clause (syntax error)

CALL AddMissingColumn(Database(), 'creature_template_addon', 'StandState', 'TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `MountCreatureID`');
CALL AddMissingColumn(Database(), 'creature_template_addon', 'AnimTier', 'TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `StandState`');
CALL AddMissingColumn(Database(), 'creature_template_addon', 'VisFlags', 'TINYINT UNSIGNED DEFAULT 0 NOT NULL AFTER `AnimTier`');
```

**Comment by Shauren** [comment]
All this trying to work around some issue and yet nobody posted server logs that would be relevant to see WHY this update wants to be reapplied

**Comment by infidelus** [comment]
Thanks all for the replies.

> @infidelus you can try do what Shauren said in the other issue [#28711 (comment)](https://github.com/TrinityCore/TrinityCore/issues/28711#issuecomment-1377492227)
> 
> Clear hash for 2023_01_09_00_world.sql in world > updates table if you have that row

I think this is what got me into trouble in the first place last week when I was trying to fix a problem.  I found that comment and proceeded to delete all the entries in the hash column so TC would run them all again.  They all worked except this particular one which just constantly errored and the only way I could get around it was to delete that SQL file before running worldserver.

> but I suggest you to better drop then reinsert latest world tdb

I thought I'd done that yesterday before posting but it looks like I still had the October release as I've just pulled again this morning, ensuring I had the new release, and the error has gone.

> To answer the OP's question, I don't think mySQL supports that syntax (I think MariaDB does) and I can't check right now but the easier way is to create a procedure and then just call it:
> 

Thanks.  If I do something similarly stupid in the future I will refer to your suggestion (and see if I can work out what to do with it :-))

> All this trying to work around some issue and yet nobody posted server logs that would be relevant to see WHY this update wants to be reapplied

You're quite right, I should have pasted my logs but was a little fixated trying to work out a way of adding some kind of IF EXISTS clause to the query, but was drawing a blank as my knowledge of SQL is very limited at the moment.

As the issue is of an id10t nature, I'll close this.  Thanks again.

**Comment by MrSmite** [comment]
@infidelus 
>Thanks. If I do something similarly stupid in the future I will refer to your suggestion (and see if I can work out what to do with it :-))

You acknowledged you had no idea if the code was correct. That's not stupid, that's knowledge seeking which is a good trait.

To use the procedure, you can either paste it into an SQL file (use Notepad++ for syntax hilighting) and then execute it using the SQL console. Or you can get a free MySQL GUI like SQLYog, log into the database, paste it into the code window and execute it.

I use SQLYog because it's free, feature rich, easy to use and has syntax hilighting.

https://github.com/webyog/sqlyog-community
https://github.com/webyog/sqlyog-community/wiki/Downloads

**Comment by infidelus** [comment]
Thanks again.  It didn't look like the SQL code I've seen so far so wasn't sure.  I do have a MySQL GUI to paste the queries in, and have used the source command if I'm at the terminal.
