### ISSUE TITLE
Core/Utgarde Pinnacle: You get permastunned if you leave instance at Svala sacrifice phase

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28777]
### Description

You get permastunned if you leave instance at Svala sacrifice phase
You have to relog in order that stun fade out.

https://user-images.githubusercontent.com/24683355/213915421-27b70b69-2f99-4a6c-9f3c-dd7dd9a7c622.mp4

### Expected behaviour

I guess the stunns need to be removed when you are teleported out.

### Steps to reproduce the problem

Go in Utgarde Pinnacle (heroic I tested) then leave party before sacrifice phase 50% pop

### Branch

3.3.5

### TC rev. hash/commit

835e2918319e

### Operating system

Windows 10x64

### Custom changes

None

**Comment by Nyr97** [comment]
Maybe related to InterruptFlags? Normally, spells from dungeons and raids are supposed to be gone OnInstanceLeave iirc.

**Comment by Ovahlord** [comment]
there is no interrupt flag for these spells. these auras should be removed because they are the result of a channeled spell. so interrupting the channeled spell should also interrupt the aura

**Comment by techett** [comment]
> Maybe related to InterruptFlags? Normally, spells from dungeons and raids are supposed to be gone OnInstanceLeave iirc.
It's a channeled ability so it should drop the "buff" if interrupted. 

Perhaps... something within the SpellMgr.cpp and it's going to be a flag.
