### ISSUE TITLE
DB/Utgarde Pinnacle: Ritual Channelers shoud most likely be immune to stuns also

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28776]
### Description

Ritual Channelers shoud most likely be immune to stuns also
check following video:
https://youtu.be/RWzFRWUzHd0?t=141
### SQL fix

```sql
-- Ritual Channeler immune to stuns
UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|2048 WHERE `entry` IN (27281,30804);
```

### Branch

3.3.5

### TC rev. hash/commit

835e2918319e

**Comment by CraftedRO** [comment]
Possible to intrerupt and more also

**Comment by CraftedRO** [comment]
The server trow some error about heroic difficulty but there's is not such a npc id on wowhead 30804 kek

```
Creature (Entry: 27281, mechanic_immune_mask: 8390672) has weaker immunities in difficulty 1 mode (Entry: 30804, mechanic_immune_mask: 8388624).
Possible FIX: UPDATE `creature_template` SET `mechanic_immune_mask`=`mechanic_immune_mask`|2048 WHERE `entry`=30804;
```

**Comment by Aokromes** [comment]
it's the heroic mode entry, you must add flag also to that id.

**Comment by CraftedRO** [comment]
interesting is that they already have different immunity flags but the core only complain about my recent added flag :)

**Comment by Aokromes** [comment]
the flag is different from normal to heroic mode.

**Comment by CraftedRO** [comment]
nah I was wrong they had same flags, I updated the sql
