### ISSUE TITLE
Spell/Warlock: Shadow Cleave

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28771]
### Description

If you have a weapon this spell only missing on a target level 80, if you unequip your weapon the spell no longer miss.

https://user-images.githubusercontent.com/24683355/213707071-c7d084d7-c1dc-43cd-96b1-5556e563c5fd.mp4

### Expected behaviour

The spell shoud not miss with a weapon equiped or not and it shoud probably hotswap spell hit points.

### Steps to reproduce the problem

Create a 80 warlock on a gm account then spec into [Metamorphosis](https://www.wowhead.com/wotlk/spell=47241/metamorphosis)

go to a dummy and cast [Shadow Cleave
](https://www.wowhead.com/wotlk/spell=50581/shadow-cleave) check the differences with a weapon equiped and without.

### Branch

3.3.5

### TC rev. hash/commit

835e2918319e

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Jinnaix** [comment]
Please tell me you are aware that in 335 weapon rating is a thing and you max leveled the weapon type to reach maximum hit chance in your test case?

**Comment by CraftedRO** [comment]
No I don't have sword hit cap but there's a misslogic with a weapon the spell miss and without it doesn't https://github.com/SunwellTracker/issues/issues/3310

**Comment by Dekz120** [comment]
in my case it works good. i hit with 400 dagger skill and 18.3% hit rating(if we also talking about [this issue](https://github.com/SunwellTracker/issues/issues/3310)
![WoWScrnShot_012123_010447](https://user-images.githubusercontent.com/83663557/213814121-b0cf44b6-8664-4b97-a942-bce4797bc2d5.jpg)

**Comment by CraftedRO** [comment]
now try without dagger skill cap

**Comment by Dekz120** [comment]
ah. i got your point, sorry.
iam not sure about this hotswap thing. looks like it should work like an [envenom](https://www.wowhead.com/wotlk/spell=57993/envenom) and it does. Shadow Cleave depends on haste rating of your melee weapon(because of "next melee" flag), so probably it should depend on melee hit rating too

**Comment by CraftedRO** [comment]
https://youtu.be/NT2JCRx5azI?t=2093

After few more researches it seems it works as expected and you need indeed weapon skill cap for this spell.

![cleave](https://github.com/TrinityCore/TrinityCore/assets/24683355/762d2f3a-5f99-4577-bb76-4c4f69105a27)
