### ISSUE TITLE
Can't extract anything (master)

### ISSUE THREAD

**Issue by MaddyCrowle** [TrinityCore/TrinityCore#28787]
### Description

CMAKE 3.25.2
MS Visual Studio 2022
WoW client v.10.0.2

Extracting starts with such error:

```
Opened casc storage 'V:/Games\World of Warcraft\Data'
Failed to load additional encryption keys from wow.tools, some files might not be extracted.
Opened casc storage 'V:/Games\World of Warcraft\Data'
Failed to load additional encryption keys from wow.tools, some files might not be extracted.
Detected client build 47631 for locale enUS
```

then bunch of errors like this:

```
Extracting dbc/db2 files...
locale enUS output path V:\Games\World of Warcraft\dbc\enUS
Unable to open file Achievement.db2 in the archive for locale enUS: FILE_NOT_FOUND
Unable to open file Achievement_Category.db2 in the archive for locale enUS: FILE_NOT_FOUND
...
Extracted 0 files
```

```
Opened casc storage 'V:/Games\World of Warcraft\Data'
Failed to load additional encryption keys from wow.tools, some files might not be extracted.
Extracting camera files...
Read CinematicCamera.db2 file...
Failed to open 'FileDataId 1294214' in CASC storage: FILE_NOT_FOUND
```

and so on... In the end nothing is extracted. I already have experience with 3.3.5, but here I really don't understand what's wrong. I'm doing everything exactly as said in Wiki https://trinitycore.info/en/install/Server-Setup

### Expected behaviour

dbc, maps, vmaps, mmaps, cameras, gt should be successfully extracted.

### Steps to reproduce the problem

1. CMake configure/generate without errors, VS solution cleaned and compiled successfully, no errors. 
2. Copy required files to the folder where 'World of Warcraft Launcher.exe' and the Data folder are.
3. Launch extractor.bat

### Branch

master

### TC rev. hash/commit

0eff4ec7df6d 2022-08-21 00:09:51 +0000 (master branch) (Win64, RelWithDebInfo, Static) 

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by MaxtorCoder** [comment]
Actually no, wow.tools removed tactkey stuff from it's website, so that has to be fixed to fully make extractor work

**Comment by Shauren** [comment]
Actually yes, loading addtional tact keys is optional in extractors (only sections of db2 files are encrypted, never whole file)

**Comment by mdX7** [comment]
> 

https://github.com/TrinityCore/TrinityCore/commit/09b36d8f75d1390232187f69596e12e589311e60

some lazy person (hi) just forgot to update error message

**Comment by MaddyCrowle** [comment]
> incomplete client.

But client is fully downloaded via battle.net app, is there anything I need to download additionally somehow?

**Comment by MaddyCrowle** [comment]
Ok, I found the reason of my problem - update source. Sorry, I should check it twice. I actually updated it before (that's why I didn't think about it), but it seems for some reason not the latest version.

**Comment by bAdOoWindy** [comment]
> Ok, I found the reason of my problem - update source. Sorry, I should check it twice. I actually updated it before (that's why I didn't think about it), but it seems for some reason not the latest version.

update what?
core version? or client?

**Comment by bAdOoWindy** [comment]
This has been resolved by turning on Global VPN
