### ISSUE TITLE
DB: Missing auth seed for realm build 47657

### ISSUE THREAD

**Issue by shen3221894** [TrinityCore/TrinityCore#28782]
### Description

I am using a client with build version 47657. When i log into realm, the server get the log below.

> WorldSocket::HandleAuthSession: Missing auth seed for realm build 47657 (192.168.1.189).

I know that it can be configured in the column ‘win64AuthSeed’ in the table ‘auth.build_info’, but there is only info for version 47631.
How do I know the corresponding win64AuthSeed with 47657 . Or request a sql update commit please.

The details are shown in the figure below:
https://wowpedia.fandom.com/wiki/Public_client_builds
![image](https://user-images.githubusercontent.com/10844607/214374989-380b1b15-3306-42e9-8875-0ce7148f5d5b.png)

![image](https://user-images.githubusercontent.com/10844607/214374772-91330da3-6652-4c0b-b2f6-4b43c4ac910b.png)

![image](https://user-images.githubusercontent.com/10844607/214379356-e395016c-b21f-44f9-be1e-7fcc92ed50f7.png)

### Expected behaviour

None

### Steps to reproduce the problem

None

### Branch

master

### TC rev. hash/commit

None

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Shauren** [comment]
Wont fix, this is china exclusive build
