### ISSUE TITLE
Crash to ejecute worldserver

### ISSUE THREAD

**Issue by T3llorista** [TrinityCore/TrinityCore#28791]
### Description

Copiling are correct, but when i ejecute worldserver crash when loading all data of db.
The error is when Loading Criteria Lists...

### Expected behaviour

Log Crash
[2a79be02fd60_worldserver.exe_[26-1_18-20-22].txt](https://github.com/TrinityCore/TrinityCore/files/10512720/2a79be02fd60_worldserver.exe_.26-1_18-20-22.txt)
Log Error Server
[Server.log](https://github.com/TrinityCore/TrinityCore/files/10512722/Server.log)

### Steps to reproduce the problem

step 1 ejecute worldserver the last commit wich the last db update

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 2a79be02fd60 2023-01-26 15:11:56 +0100 (master branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Aokromes** [comment]
i vote incorrect db2 files / to old / to new.
