### ISSUE TITLE
DB/Quest: Sons of Hodir reputation reward rate

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#28798]
### Description

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?faction=1119

>[Patch 3.3.0](https://wowpedia.fandom.com/wiki/Patch_3.3.0) (2009-12-08): Reputation gain has been sped up approximately 30% for a number of factions: [Argent Crusade](https://wowpedia.fandom.com/wiki/Argent_Crusade), [Alliance Vanguard](https://wowpedia.fandom.com/wiki/Alliance_Vanguard), [Horde Expedition](https://wowpedia.fandom.com/wiki/Horde_Expedition), [Kirin Tor](https://wowpedia.fandom.com/wiki/Kirin_Tor), [Knights of the Ebon Blade](https://wowpedia.fandom.com/wiki/Knights_of_the_Ebon_Blade), [Sons of Hodir](https://wowpedia.fandom.com/wiki/Sons_of_Hodir), [Wyrmrest Accord](https://wowpedia.fandom.com/wiki/Wyrmrest_Accord)

https://wowpedia.fandom.com/wiki/Reputation

> [25-30] [Mending Fences](https://wowpedia.fandom.com/wiki/Mending_Fences) (+28,600 The Sons of Hodir)
[25-30] [A Spark of Hope](https://wowpedia.fandom.com/wiki/A_Spark_of_Hope) (+28,600 The Sons of Hodir)

https://wowpedia.fandom.com/wiki/Sons_of_Hodir
(22000 * 1.3 = 28600)

treeston update reputation gain for quests of Sons of Hodir reputation
https://github.com/TrinityCore/TrinityCore/commit/376d281fff74c476b411460d969d490c15a86836
https://github.com/TrinityCore/TrinityCore/commit/63c77d2283ec725f552e07dce7328f5e5da7ce40

and after that, revert changes to make it more reasonable in reputation_reward_rate table
https://github.com/TrinityCore/TrinityCore/commit/1ccdad6eb33adcb4848fc6fed36dc181e74b8682

also this another commit for fix wrong questid in those commits: https://github.com/TrinityCore/TrinityCore/commit/cfb38cc2fcb9bfad9869a81d6e693710d14dd6e8

but treeston forgot update reputation_reward_rate of Sons of Hodir (1119)

### SQL fix

```sql
-- Sons of Hodir: quests reputation reward rate increased 30%
UPDATE `reputation_reward_rate` SET `quest_rate`=1.3,`quest_daily_rate`=1.3,`quest_weekly_rate`=1.3,`quest_monthly_rate`=1.3,`quest_repeatable_rate`=1.3 WHERE `faction`=1119;
```

### Branch

3.3.5

### TC rev. hash/commit

aeb4d18e20c444e828ecff0964013d3d8daf67d9

**Comment by CraftedRO** [comment]
I remember a player on my server complaining about this reputation if I don't confuse them, there's only one of the very last quests which gave you a lot of reputatio but the others too little, hehe what memories :)

**Comment by CraftedRO** [comment]
I remember a player on my server complaining about this faction if I don't confuse them, there's only one of the very last quests which gave you a lot of reputation but the others too little, hehe what memories :)

**Comment by dr-j** [comment]
Ye mending fences and a spark of hope are the two quests which should get you to friendly and this is correct I as I remember on retail no quest gave rep before these in chain but turning in just these two quests gave enough rep to get to friendly (not neutral) but that was during mop/Wod so was not sure if had been changed by blizzard
