### ISSUE TITLE
World server crash

### ISSUE THREAD

**Issue by drustcore** [TrinityCore/TrinityCore#28819]
### Description

i did both try mysql 8.0 and 5.7 but i got crash can someone help me?

### Expected behaviour

Loading Traits...
Loading languages...
>> Loaded 44 languages in 1 ms
Loading languages words...
>> Loaded 317 word groups from 2361 words in 0 ms
Loading GameObject models...
Unable to open 'GameObjectModels.dtree' file.
Unable to load gameobject models, objects using WMO models will crash the client - server shutting down!

### Steps to reproduce the problem

gameobject

### Branch

master

### TC rev. hash/commit

TrinityCore rev. f7c9a853279c+ 2023-02-14 16:49:20 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

last master rev

### Operating system

Windows 10

### Custom changes

no any custom script

**Comment by fluxurion** [comment]
use vmaps

**Comment by drustcore** [comment]
> use vmaps

thx
