### ISSUE TITLE
Mechagnome spell 313010 crashed by spell 1680 infinite trigger

### ISSUE THREAD

**Issue by Greyisttot** [TrinityCore/TrinityCore#28820]
### Description

https://gist.github.com/Greyisttot/162dd2335201449192842a4c3b7ae0bf

This problem has existed for a long time, I use the disables table to disable 313010 and then use 1680 without crashing.

### Expected behaviour

null

### Steps to reproduce the problem

null

### Branch

master

### TC rev. hash/commit

null

### Operating system

Windows 2019

### Custom changes

null

**Comment by Aokromes** [comment]
useless crashlog.

**Comment by jackpoz** [comment]
> useless crashlog.

as in buils in RelWithDebInfo, not Release, when reporting a crash
