### ISSUE TITLE
Problems with the geodata of flying NPCs

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#28833]
### Description

The problem is as follows. All flying NPCs fall into textures.  When caste, when moving through the mountains.
I also wanted to clarify that the geodata was rebuilt from a clean client just a couple of hours ago.
I attach screenshots of the problem.
https://ibb.co/Twd41dQ
https://ibb.co/fXqvpjT

### Expected behaviour

Flying NPCs should fly above the ground and not fall into textures.

### Steps to reproduce the problem

1) Take for example the NPC https://www.wowhead.com/npc=29570/nascent-valkyr
2) We begin to beat this NPC and when moving away from it, the NPC begins to fall into textures. Or at the caste.

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/92b7c98c018c1b950a45fb639e70871dca739ebd

### Operating system

Windows Server 2022

### Custom changes

The changes are not how they do not relate to geodata

**Comment by Nyr97** [comment]
Normally flying creatures have their body under the textures (especially val'kyrs) when they reach the floor to reach a given target and the creature doesn't automatically "switch" to ground movement with hover height.

**Comment by CraftedRO** [comment]
This issue is invalid : https://youtu.be/SYg6d61OlTc?t=13 / https://youtu.be/UjlOS4FTgqo?t=101
