### ISSUE TITLE
Tempest Keep Kael'thas and phoenix kill them and they will come back to life automatically

### ISSUE THREAD

**Issue by anyanfei** [TrinityCore/TrinityCore#28839]
### Description

**Description**
Tempest Keep Kael'thas and phoenix ,when i kill them, they will come back to life

**Branch**
3.3.5

**Database**
TDB_full_world_335.23011_2023_01_16.sql

### Expected behaviour

These two monsters should die rather than revive

### Steps to reproduce the problem

just kill them will be happend

### Branch

3.3.5

### TC rev. hash/commit

nothing

### Operating system

Debian 11

### Custom changes

No Original DBC File

**Comment by CraftedRO** [comment]
This is most likely invalid and you probably have some custom changes in your core, I just tested on 92b7c98c018c and Kael'thas Sunstrider once killed remain dead.

![WoWScrnShot_030323_131952](https://user-images.githubusercontent.com/24683355/222707506-5cec362b-28e2-4087-ad68-d857b9a914f2.jpg)

**Comment by anyanfei** [comment]
> 

you are right, Kael'thas killed once , but the phoenix egg will always come back to life, and if it is broken, it will hatch the phoenix

**Comment by CraftedRO** [comment]
![egg](https://user-images.githubusercontent.com/24683355/227713265-55e0687b-b788-4c98-81c7-78d23a245271.PNG)
Source: https://wowwiki-archive.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)

might be part of the script, I mean that's a phoenix :)

**Comment by CraftedRO** [comment]
No kill whitin 15 sec test ( it will spawn a phoenix ):

https://user-images.githubusercontent.com/24683355/227714347-f4946082-7348-42de-864a-4000f8434647.mp4


Kill test ( it doesn't spawn a phoenix).

https://user-images.githubusercontent.com/24683355/227714845-ee114790-384e-429b-ad53-165f734fc6b6.mp4

**Comment by anyanfei** [comment]
> No kill whitin 15 sec test ( it will spawn a phoenix ):
> 
> Kill test ( it doesn't spawn a phoenix).

Thank you very much for your answer. Maybe I made a mistake, and now it seems to be all right again
