### ISSUE TITLE
could not find any instance of Visual Studio.

### ISSUE THREAD

**Issue by Mitradis** [TrinityCore/TrinityCore#28842]
### Description

CMake Error at CMakeLists.txt:18 (project):
  Generator

    Visual Studio 17 2022

  could not find any instance of Visual Studio.

Configuring incomplete, errors occurred!
See also "C:/Build/CMakeFiles/CMakeOutput.log".

### Expected behaviour

IDK

### Steps to reproduce the problem

install all Windows Requirements apps. git clone https://github.com/TrinityCore/TrinityCore.git. Get error in Cmake.

### Branch

3.3.5

### TC rev. hash/commit

last

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by Aokromes** [comment]
user failure. re-read wiki.

**Comment by Mitradis** [comment]
write normally

**Comment by Mitradis** [comment]
CMake Error at cmake/compiler/msvc/settings.cmake:10 (message):
  MSVC: TrinityCore requires version 19.30 (Microsoft Visual Studio 2022 17)
  to build but found 19.29.30148.0
Call Stack (most recent call first):
  cmake/platform/win/settings.cmake:6 (include)
  cmake/macros/CheckPlatform.cmake:11 (include)
  CMakeLists.txt:58 (include)

**Comment by Mitradis** [comment]
Update you FAQ

**Comment by mdX7** [comment]
Update Visual Studio 2022

**Comment by Aokromes** [comment]
> Update your FAQ

MSVC: TrinityCore requires version 19.30 (Microsoft Visual Studio 2022 17)
to build but found 19.29.30148.0

that vc++ version is vs 2019, not 2022.

**Comment by MaxtorCoder** [comment]
XDDDDDD

**Comment by KingPin** [comment]
for anyone reading this in the future, our wiki ( https://trinitycore.info ) is open to all editors, you don't even need to sign up for an account! you use your GitHub account to login to it and edit pages, and you will have the satisfaction of having helped any future users like yourself if you fix/add/elaborate/clarify anything :)

**Comment by CraftedRO** [comment]
now we got an outdated wiki and and outdated forum too, I wonder if you coud change dns to redirect to the newest ones and disable old ones

**Comment by Aokromes** [comment]
> now we got an outdated wiki and and outdated forum too, I wonder if you coud change dns to redirect to the newest ones and disable old ones

wiki visual studio requirement was updated the day visual studio version increase was required.

**Comment by CraftedRO** [comment]
yea I mean I don't think is ok for you to update both wiki at once, we better let the newest one and remove old one alongside old forum

**Comment by Aokromes** [comment]
> yea I mean I don't think is ok for you to update both wiki at once, we better let the newest one and remove old one alongside old forum

old wiki have requirements install etc part removed pointing to new wiki.
