### ISSUE TITLE
DB/Creature: Update Prince Tortheldrin spawn coordinates

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28840]
### Description

According to wowhead screenshoots and this video I found https://youtu.be/Cxndz79CvVc?t=79, Prince Tortheldrin shoud be spawned downside near The Prince's Chest not at the second top floor.

### SQL fix

```sql
-- Update Prince Tortheldrin spawn coordinates
UPDATE `creature` SET `position_x`=132.6259, `position_y`=625.9129, `position_z`=-48.38363, `orientation`=4.625122547149658203 WHERE `guid`=56951 AND `id`=11486;
```

### Branch

3.3.5

### TC rev. hash/commit

92b7c98c018c

**Comment by Ovahlord** [comment]
Where did you get the value from? Spawn coordinates are meant to be sniffed

**Comment by Jinnaix** [comment]
Correct position is 
[0] Position: X: 132.6259 Y: 625.9129 Z: -48.38363

**Comment by CraftedRO** [comment]
yea it was guessed value from a npc nearby, ty Jinnaix for confirm this.
