### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by biglad** [TrinityCore/TrinityCore#28856]
### Description

After doing latest pull https://github.com/TrinityCore/TrinityCore/pull/28836

when starting server

BroadcastText (Id: 57033) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57033) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57034) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57035) in table `broadcast_text_locale` does not exist. Skipped!
BroadcastText (Id: 57035) in table `broadcast_text_locale` does not exist. Skipped!

CreatureTextMgr: Entry 40352, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40387.
CreatureTextMgr: Entry 40352, Group 1, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40388.
CreatureTextMgr: Entry 40352, Group 2, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40389.
CreatureTextMgr: Entry 40352, Group 3, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40390.
CreatureTextMgr: Entry 40352, Group 4, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40391.
CreatureTextMgr: Entry 40352, Group 5, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40392.
CreatureTextMgr: Entry 40352, Group 6, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40393.
CreatureTextMgr: Entry 40352, Group 7, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40394.
CreatureTextMgr: Entry 40352, Group 8, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40395.
CreatureTextMgr: Entry 40352, Group 9, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40396.
CreatureTextMgr: Entry 40391, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40413.
CreatureTextMgr: Entry 40416, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40412.
CreatureTextMgr: Entry 40416, Group 0, Id 1 in table `creature_text` has non-existing or incompatible BroadcastTextId 40411.
CreatureTextMgr: Entry 40423, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40420.
CreatureTextMgr: Entry 40429, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40599.
CreatureTextMgr: Entry 40429, Group 1, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40600.
CreatureTextMgr: Entry 40429, Group 2, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40601.
CreatureTextMgr: Entry 40429, Group 3, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40602.
CreatureTextMgr: Entry 40429, Group 4, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40603.
CreatureTextMgr: Entry 40429, Group 5, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40604.
CreatureTextMgr: Entry 40429, Group 6, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40605.
CreatureTextMgr: Entry 40429, Group 7, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40606.
CreatureTextMgr: Entry 40429, Group 8, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40598.
CreatureTextMgr: Entry 40446, Group 0, Id 0 in table `creature_text` has non-existing or incompatible BroadcastTextId 40437.

1000s of entries

i cant see any SQL updates to fix this

### Expected behaviour

no SQL errors

### Steps to reproduce the problem

Updated to latest 335a branch , compile , start server

### Branch

3.3.5

### TC rev. hash/commit

(https://github.com/TrinityCore/TrinityCore/pull/28836[)](https://github.com/TrinityCore/TrinityCore/commit/13fa60ab86c6338f034823fbd49a90baedd3ab58)

### Operating system

Ubuntu

### Custom changes

NONE

**Comment by Aokromes** [comment]
you say you use 3.3.5a but you add master branch hash.

**Comment by biglad** [comment]
my bad copied master hash

https://github.com/TrinityCore/TrinityCore/pull/28836  < 335a

**Comment by biglad** [comment]
fixed by adding latest TDB file
