### ISSUE TITLE
Alliance First Aid Quest

### ISSUE THREAD

**Issue by biglad** [TrinityCore/TrinityCore#28855]
### Description

The Quest isnt working, the NPCs die before u can heal them. Also

Script 'npc_doctor' exists in the core, but the database does not assign it to any creature.
Script 'npc_injured_patient' exists in the core, but the database does not assign it to any creature.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=6624

### Expected behaviour

You should get time to heal the NPCs

### Steps to reproduce the problem

attempt quest, ALL npcs spawn and once then die at same time = failed quest

### Branch

3.3.5

### TC rev. hash/commit

[5c92832](https://github.com/TrinityCore/TrinityCore/commit/5c9283244b9b2121037af5db94f626aeebdbddc3)

### Operating system

Ubuntu

### Custom changes

NONE

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25387

**Comment by biglad** [comment]
@Aokromes is there a SQL fix for
Script 'npc_doctor' exists in the core, but the database does not assign it to any creature.
Script 'npc_injured_patient' exists in the core, but the database does not assign it to any creature.

**Comment by Aokromes** [comment]
there is nothing to fix with that, fresh TDB ships those scripts loaded.
