### ISSUE TITLE
Triage Bug Ally & Horde

### ISSUE THREAD

**Issue by biglad** [TrinityCore/TrinityCore#28857]
### Description

There seems to be an error in the script for this quest.

NPC die too fast

### Expected behaviour

Start quest (ally or horde)
https://www.wowhead.com/wotlk/quest=6624/triage < ally
https://www.wowhead.com/wotlk/quest=6622/triage < horde

Randomly NPC should spawn on the beds.

Use bandage on NPC to heal.

After 15 healed , quest complete

### Steps to reproduce the problem

Start quest (ally or horde)
https://www.wowhead.com/wotlk/quest=6624/triage < ally
https://www.wowhead.com/wotlk/quest=6622/triage < horde

Randomly NPC should spawn on the beds.

Use bandage on NPC to heal.

They die too fast

### Branch

3.3.5

### TC rev. hash/commit

[5c92832](https://github.com/TrinityCore/TrinityCore/commit/5c9283244b9b2121037af5db94f626aeebdbddc3)

### Operating system

Ubuntu

### Custom changes

NONE

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/25387
