### ISSUE TITLE
Metamorphosis Spell not auto swapping action bar

### ISSUE THREAD

**Issue by biglad** [TrinityCore/TrinityCore#28859]
### Description

Metamorphosis
Instant 3 min cooldown
You transform into a Demon for 30 sec. This form increases your armor contribution from items by 600%, damage by 20%, reduces the chance you'll be critically hit by melee attacks by 6% and reduces the duration of stun and snare effects by 50%. You gain some unique demon abilities in addition to your normal abilities.

You transform, but no new abilities, leave original spells in place. doesnt swap action bar!

https://wotlkdb.com/?spell=47241

Screenshot, learning temp spell but them not in action bar
https://i.imgur.com/a34U8Xb.jpeg

### Expected behaviour

When you transform the action bar should change like a warrior or druid

### Steps to reproduce the problem

Just use spell, action bar stays they same, no option to use new abilities

### Branch

3.3.5

### TC rev. hash/commit

[3dda65c](https://github.com/TrinityCore/TrinityCore/commit/3dda65c53aaaf0a29eca180d8de2d825923364cc)

### Operating system

Ubuntu

### Custom changes

NONE

**Comment by Aokromes** [comment]
i told you it's blizzlike.

**Comment by biglad** [comment]
ITS NOT!

**Comment by biglad** [comment]
So you saying bizzlike is cast spell, you got 30 secs to go spell book , manually swap action bar, drag and drop into action bat and then use?

**Comment by biglad** [comment]
@Aokromes please got check, as its a bug

**Comment by Aokromes** [comment]
> Reference

i have show you i made a demon warlock on wotlk classic and it doesn't autofills bar.
