### ISSUE TITLE
Metamorphosis Warlock Not giving Abilities

### ISSUE THREAD

**Issue by biglad** [TrinityCore/TrinityCore#28858]
### Description

Metamorphosis
Instant	3 min cooldown
You transform into a Demon for 30 sec. This form increases your armor contribution from items by 600%, damage by 20%, reduces the chance you'll be critically hit by melee attacks by 6% and reduces the duration of stun and snare effects by 50%. You gain some unique demon abilities in addition to your normal abilities.

You transform, but now new abilities, leave original spells in place.

https://wotlkdb.com/?spell=47241

### Expected behaviour

When you transform you should get new abilities

### Steps to reproduce the problem

Cast spell on demo lock, need the talent

### Branch

3.3.5

### TC rev. hash/commit

[3dda65c](https://github.com/TrinityCore/TrinityCore/commit/3dda65c53aaaf0a29eca180d8de2d825923364cc)

### Operating system

Ubuntu

### Custom changes

NONE

**Comment by Aokromes** [comment]
working like WOTLK classic

https://i.imgur.com/a34U8Xb.jpeg

**Comment by biglad** [comment]
but this is 335a no classic wotlk
https://wotlkdb.com/?spell=47241

we shud get new abilities or is 335a including wotlk classic updates??

**Comment by biglad** [comment]
> working like WOTLK classic
> 
> https://i.imgur.com/a34U8Xb.jpeg

you image shows you learningg demon spells, they should auto be put in action bar

**Comment by biglad** [comment]
@Aokromes please read and re-open
