### ISSUE TITLE
Boss Magtheridon server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28864]
### Description

https://gist.github.com/PivanDepolo/6ff6f1e3d9835450511481efc8841d08
https://gist.github.com/PivanDepolo/aecccc98a84b0e6c411342189deec219

### Expected behaviour

Not crash

### Steps to reproduce the problem

Just hit the NPC near the boss.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/356c0c8afc62190c272e87d35819b0ab38ebe96f

### Operating system

Debian 11

### Custom changes

None

**Comment by jackpoz** [comment]
This is a null dereference crash happening in https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/CreatureAI.cpp#L83 when https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/AI/ScriptedAI/ScriptedCreature.cpp#L56 passes nullptr
