### ISSUE TITLE
Documentation/Instructions for loading WoW meshes in Recast

### ISSUE THREAD

**Issue by T1ti** [TrinityCore/TrinityCore#28869]
### Description

The process is fairly simple once you know what to do, but figuring out how to do it isn't straight forward and not really documented anywhere that I could find.

It pretty much is : 
- compile or download TC's fork of recast https://github.com/TrinityCore/TrinityCore/tree/3.3.5/dep/recastnavigation
- Extract mmaps with debug flags ( `mmaps_generator.exe --debugOutput true` )
- put the obj files in the Meshes folder of Recast

### Expected behaviour

Add documentation on how to load MMAP meshes in recast. Could be in the wiki where it teaches how to setup server data, or in one of the readmes...

### Steps to reproduce the problem

-

### Branch

3.3.5

### TC rev. hash/commit

-

### Operating system

-

### Custom changes

-

**Comment by CraftedRO** [comment]
I don't think issues tracker is the right place for this.

**Comment by Aokromes** [comment]
even tc uses recastnavigation, it also ships own repo
https://github.com/TrinityCore/recastnavigation

**Comment by jackpoz** [comment]
TC custom branch has a button to load mmtiles too

**Comment by T1ti** [comment]
> 

I know, but that's the default recast read me, there's no instructions
