### ISSUE TITLE
Food and Water have 1 minute cooldown

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [TrinityCore/TrinityCore#28873]
### Description

If I try to eat / drink more, I get:
you are far too full to eat any more

### Expected behaviour

You should be able to eat as often as you want to. 

### Steps to reproduce the problem

Eat something
stop eating
Eat again. 

### Branch

3.3.5

### TC rev. hash/commit

I don't know what this means?

### Operating system

Server: Windows 10, Client: Ubuntu 20.04

### Custom changes

None

**Comment by CraftedRO** [comment]
60b75e3b6e81 Invalid:


https://user-images.githubusercontent.com/24683355/227712301-a9b32aa0-465a-43d4-809b-7b19fc3a2066.mp4
