### ISSUE TITLE
mmaps_generator shows "No such file or directory"

### ISSUE THREAD

**Issue by WebberLai** [TrinityCore/TrinityCore#28872]
### Description

System : Mac OS Catalina \ XCode 12.4
I try to build the master server on 10.0.7 just release recently
after I generate 4 map extractor ,  I run the **extractor.sh**
and select 

4) Extract all files

but nothing happen when extract last mmap
only create an empty folder

### Expected behaviour

Running extractor.sh , first jobs are all complete 
when extractor the mmap seems stop immediately  , but no error information

logs from my terminal

```
Extracting Movement Maps (this may take a while)

-- Using /Applications/Trinity/bin/mmaps_generator
-- Copying extracted data to /Applications/Trinity/data/mmaps
-- Starting in 5 seconds
TrinityCore rev. cc57c9dad59a 2023-03-24 12:27:01 +0100 (master branch) (MacOSX, Release, Static) (MMAP generator)
<Ctrl-C> to stop.\n

No such file or directory
-- Extraction complete, copying files
-- Done

All files extracted
```

### Steps to reproduce the problem

after compiler done  , running extractor.sh , select 4 > Extract all files
Extract DBC and Maps files -> Success and complete
Extract Visual Maps (VMaps) ->  Success and complete
Extract Movement Maps (MMaps ->  Stop immediately 

### Branch

master

### TC rev. hash/commit

cc57c9d

### Operating system

Mac OS 10.15.7

### Custom changes

Nothing custom changes

**Comment by WebberLai** [comment]
<img width="1078" alt="截圖 2023-03-24 下午10 11 56" src="https://user-images.githubusercontent.com/1185079/227554697-5ee53bb2-ec73-4f28-94ac-89d11149017b.png">

**Comment by Fabi** [comment]
> <img alt="截圖 2023-03-24 下午10 11 56" width="1078" src="https://user-images.githubusercontent.com/1185079/227554697-5ee53bb2-ec73-4f28-94ac-89d11149017b.png">

Does running them directly from the client folder works fine? Like copying them to `/Applications/World of Warcraft/bin` and the script to `/Applications/World of Warcraft/` and use `.` as client and server folder when it asks.

**Comment by WebberLai** [comment]
ya , I try this directly , same result
looks it can run , but nothing happen
my command 

```
cd /Applications/World\ of\ Warcraft
/Applications/Trinity/bin/mmaps_generator
```

**Comment by Fabi** [comment]
> ya , I try this directly , same result looks it can run , but nothing happen my command
> 
> ```
> cd /Applications/World\ of\ Warcraft
> /Applications/Trinity/bin/mmaps_generator
> ```

copy the extractors and the script as I write to the wow folder...

**Comment by Aokromes** [comment]
guide states copy extractor to wow directory.

**Comment by hegwout** [comment]
I met this cause there is a .DS_Store in the WOW directory, remove it.
