### ISSUE TITLE
New server crashes

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28877]
### Description

Hope these logs help improve TrinityCore

https://gist.github.com/PivanDepolo/d8bb67373d4e6b4f10c53bf15543b967
https://gist.github.com/PivanDepolo/60034487ab20150b3ed2893550ffca2f

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Unfortunately, I don't know how to reproduce this server crash issue.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/6af42ce82da9273eb47a2a53637f1aaf08a63f1d

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
same as #28865
