### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#28876]
### Description

A crash occurs while starting the server (see log)

[da4eedf07b7d_worldserver.exe_[25-3_19-20-42].zip](https://github.com/TrinityCore/TrinityCore/files/11069777/da4eedf07b7d_worldserver.exe_.25-3_19-20-42.zip)

### Expected behaviour

There should be no crash during startup

### Steps to reproduce the problem

1.  start world.exe 
2.  see how crash during startup

### Branch

master

### TC rev. hash/commit

TrinityCore rev. da4eedf07b7d 2023-03-25 00:06:32 +0100 (master branch)

### Operating system

Win 11 Pro

### Custom changes

none

**Comment by Aokromes** [comment]
i vote outdated db2 files.

**Comment by shamage** [comment]
> i vote outdated db2 files. or binaries.
![Ashampoo_Snap_sobota 25  marca 2023_19h52m53s](https://user-images.githubusercontent.com/7515044/227736107-5451f6b5-f441-45de-9741-497150365c8e.png)

The db2 files are from this date ... are they really old ?

**Comment by Shauren** [comment]
worksforme?

**Comment by CraftedRO** [comment]
can we rename master branch to "crashster" branch :satisfied: ?

**Comment by shamage** [comment]
> worksforme?

I'm sorry, but I don't understand the question

**Comment by Shauren** [comment]
its not a question, im saying it works for me

**Comment by shamage** [comment]
> its not a question, im saying it works for me

ok, I'll try a new / clean install including the database and then let you know

**Comment by Aokromes** [comment]
> > i vote outdated db2 files. or binaries.
> > ![Ashampoo_Snap_sobota 25  marca 2023_19h52m53s](https://user-images.githubusercontent.com/7515044/227736107-5451f6b5-f441-45de-9741-497150365c8e.png)
> 
> The db2 files are from this date ... are they really old ?

yes

https://github.com/TrinityCore/TrinityCore/commit/922f60fa25569db05a7717b6b55568f321a02f64
