### ISSUE TITLE
Blood Prince Council - ICC

### ISSUE THREAD

**Issue by pfmitza** [TrinityCore/TrinityCore#2887]
Attack the 3 princes and get wipe.
Only left one will be attackable for few seconds.

and

For example if someone that tanks one of the prince dies , that specific prince gets out of combat and becomes unattackable.If It happens with prince Taldaram it makes the boss undoable.

**Comment by Killyana** [comment]
More than 20 wipes on rev. 5b5c0938da0f and cannot reproduce, if this still happen reopen the issue and explain in which circumstances it happen.
