### ISSUE TITLE
Problem in Creature database

### ISSUE THREAD

**Issue by poryagholami** [TrinityCore/TrinityCore#28886]
### Description

[DBErrors.log](https://github.com/TrinityCore/TrinityCore/files/11105515/DBErrors.log)

### Expected behaviour

It should be installed regularly without any problems

### Steps to reproduce the problem

https://user-images.githubusercontent.com/52524476/228667042-d1c09e7a-594a-4269-9d25-825ee0e8af6c.mp4

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 60b75e3b6e81+ 2023-03-24 10:52:44 +0100 (3.3.5 branch) (Win64, Debug, Static) (authserver)

### Operating system

window server 2019 64bit

### Custom changes

levelup
duel_command_custom
anticheat

**Comment by Shauren** [comment]
No. I will not watch a video to see CONSOLE TEXT OUTPUT

When dealing with text, POST TEXT

**Comment by Shauren** [comment]
Duplicate
