### ISSUE TITLE
Mdic  Promoting your magician methods for sales

### ISSUE THREAD

**Issue by Mistixx** [TrinityCore/TrinityCore#28882]
### Description

Tests of MDIC advertisements where he charges for various sources and arrangements, of course, he will not have receipt money because he extracted the money, he is very intelligent

![Sin título](https://user-images.githubusercontent.com/47088016/228144539-2a7003f3-a4c2-4287-9714-f649aff6a637.png)

### Expected behaviour

none

### Steps to reproduce the problem

none

### Branch

master

### TC rev. hash/commit

none

### Operating system

Windows 10 x64

### Custom changes

none

**Comment by MaxtorCoder** [comment]
Get a live and stop bothering people.

**Comment by Mistixx** [comment]
You also shut your mouth and realize that Mdix is a scammer and instead of judging other people, also look at Mdic as a shit person

**Comment by Mistixx** [comment]
proofs of your buyers
![Uploading adad.png…]()

**Comment by MaxtorCoder** [comment]
Where image ModCheck, no proof.

**Comment by Mistixx** [comment]
![buy](https://user-images.githubusercontent.com/47088016/228145429-44bc5f78-14c5-4439-8bd9-7085cd49a70f.png)
