### ISSUE TITLE
Of Dusk and Dawn server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28890]
### Description

https://www.wowhead.com/spell=385125/of-dusk-and-dawn crashes a server when you trying to learn that talent.

![1](https://user-images.githubusercontent.com/64589699/229270867-e6b5fbf6-4d0c-42d4-b5a0-d249c3c82538.png)

https://gist.github.com/PivanDepolo/f07d0ca24d0108ea57881b0b9992636e

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Just try to learn that spell

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/1895f2230c2cc1ad517cbe9e49987200740948f4

### Operating system

Debian 11

### Custom changes

None

**Comment by Mematoru23** [comment]
Don't think its happening anymore. Can't reproduce it.

**Comment by Naddley** [comment]
cant reproduce it
