### ISSUE TITLE
Error map extracting

### ISSUE THREAD

**Issue by Antenshi** [TrinityCore/TrinityCore#28893]
### Description

Don't start world, write

```
Initialized 320 DB2 data stores in 32397 ms
Loading GameObject models...
Unable to open 'GameObjectModels.dtree' file.
Unable to load gameobject models (part of vmaps), objects using WMO models will crash the client - server shutting down!
```

Maybe it's becuuse before I don't extract vmaps

```
spawning Map 2356
spawning Map 2360
spawning Map 2362
./extractor.sh: line 88:  2540 Killed                  $VMAP4ASSEMBLER Buildings vmaps
-- Extraction complete, copying files
-- Done
```
After this vmap folder is empty

### Expected behaviour

Don't extract vmaps and mmaps. 

`extractor.sh: line 88:  2540 Killed                  $VMAP4ASSEMBLER Buildings vmaps`

Then don't start wordserver

```
Unable to open 'GameObjectModels.dtree' file.
Unable to load gameobject models (part of vmaps), objects using WMO models will crash the client - server shutting down!
```

### Steps to reproduce the problem

extractor.sh
set server and client folders
2. extract virtual maps
extractor.sh: line 88:  2540 Killed                  $VMAP4ASSEMBLER Buildings vmaps

### Branch

master

### TC rev. hash/commit

10.0.7.48865

### Operating system

Ubuntu 22

### Custom changes

-

**Comment by Aokromes** [comment]
read error.

**Comment by Antenshi** [comment]
what mean 'about killed use less resources'?
I download official client and make server by trinity sources, then use extractors. Procee aborting in vmap4assembler ().
Result - vmap and mmap folders are iempty.

Now I start only vmap4assembler, without extractor.sh
```
spawning Map 2300
spawning Map 2303
spawning Map 2304
spawning Map 2305
[1]    2605 killed     ./bin/vmap4assembler
```

**Comment by Antenshi** [comment]
Ok, thanks.
I'll try on a more powerful server.
