### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#28891]
### Description

> /usr/bin/ld: ../scripts/libscripts.a(maelstrom_script_loader.cpp.o): in function `AddMaelstromScripts()':
> /home/trinity/TrinityCore/src/server/scripts/Maelstrom/maelstrom_script_loader.cpp:33: undefined reference to `AddSC_deepholm()'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:196: src/server/worldserver/worldserver] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1343: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2

Getting such error after https://github.com/TrinityCore/TrinityCore/commit/1440fe03de1b161b37dc6026e88a7cefd44cb220

### Expected behaviour

---

### Steps to reproduce the problem

Just try to re-compile the core

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/1440fe03de1b161b37dc6026e88a7cefd44cb220

### Operating system

Debian 11

### Custom changes

None

**Comment by Aokromes** [comment]
rerrun cemake.
