### ISSUE TITLE
Cannot compile Master but can compile 3.3.5 Arch64 

### ISSUE THREAD

**Issue by rooferdave** [TrinityCore/TrinityCore#28904]
### Description

Successfully compiled 3.3.5 and playing smoothly.
Compiling Master branch successfull up to :
[ 17%] Built target vmap4assembler
[ 19%] Built target database
[ 19%] Built target mapextractor
[ 23%] Built target proto
[ 23%] Built target vmap4extractor
[ 24%] Built target mmaps_generator
[ 24%] Built target shared
[ 25%] Built target bnetserver
[ 51%] Built target game
[ 99%] Built target scripts
[100%] Linking CXX executable worldserver

Before finishing, this:

/usr/bin/ld: ../game/libgame.a: error adding symbols: file format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:196: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1562: src/server/worldserver/CMakeFiles/world server.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

### Expected behaviour

Succesful Build

### Steps to reproduce the problem

Follow wiki build instructions
make -j4

### Branch

master

### TC rev. hash/commit

10.0.7.48966

### Operating system

Debian Bullseye arm64

### Custom changes

None

**Comment by Aokromes** [comment]
don't open new tickets for same bugs.

**Comment by rooferdave** [comment]
How do i post this for help with a ticket I tried to edit the first ticket, wouldnt let  me add the revision (even though i had it wrong anyway). I thought closing and opening new ticket would let me correct my mistake that way. Thank you.
