### ISSUE TITLE
Command .pinfo always crash the server if used on a banned character

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28911]
### Description

I just wanted to test if this issue : https://github.com/TrinityCore/TrinityCore/issues/24705 is still valid and then crash.
[Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/11191150/Crashes.zip)

### Expected behaviour

Shoud not crash

### Steps to reproduce the problem

.ban character name 1d test
.pinfo name

### Branch

3.3.5

### TC rev. hash/commit

c3e43d3d31d8

### Operating system

Windows 10 x64

### Custom changes

Nope

**Comment by Shauren** [comment]
Are you using mariadb? If yes then that is why

**Comment by CraftedRO** [comment]
Yes I was using mariadb for that test but now I switched to mysql-8.0.32 and same result, shoud I post new crashlog ?

**Comment by CraftedRO** [comment]
Same result if you ban the entire account and then use .pinfo on a character from that account..

**Comment by ImmortalusDev** [comment]
Post new crashlogs then

**Comment by CraftedRO** [comment]
Those are the [Crashes.zip](https://github.com/TrinityCore/TrinityCore/files/11199338/Crashes.zip) with mysql, I don't think there's too much difference but since you asked.

**Comment by Shauren** [comment]
k, i see a possible issue

what is the last_ip column value for the crashing character/account? (if you dont want to reveal it then i will need to know if this is a valid ip.in.dot.format or a hostname or empty or NULL)

**Comment by CraftedRO** [comment]
probably because of my cms I use

**Comment by CraftedRO** [comment]
probably because of my cms I use
I guess this is not a TC issue anymore, sorry for wasting time

**Comment by Aokromes** [comment]
imho core must be crash safe of bad data.

**Comment by Shauren** [comment]
We only support ipv4 addresses in that column (and worldserver only writes ipv4 there)

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9ad420e5318c8cda8b133e65fe7162b1976c0ae8
