### ISSUE TITLE
DB/Creature/Cosmetic: Add Scourgelord Tyrannus mount rider at the entrance of POS

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28912]
### Description

Add Scourgelord Tyrannus mount rider at the entrance of POS

https://www.wowhead.com/wotlk/npc=36794/scourgelord-tyrannus#screenshots:id=147161

Tested ingame, seems fine.

### SQL fix

```sql
--
DELETE FROM `vehicle_template_accessory` WHERE `entry`=36794 AND `seat_id`=0;
INSERT INTO `vehicle_template_accessory` (`entry`, `accessory_entry`, `seat_id`, `minion`, `description`, `summontype`, `summontimer`) VALUES
(36794, 36658, 0, 0, 'Scourgelord Tyrannus on Scourgelord Tyrannus', 6, 300);
```

### Branch

3.3.5

### TC rev. hash/commit

3993c45a040c

**Comment by Aokromes** [comment]
modify creature_template modelid1 without sniff is hack.

**Comment by Aokromes** [comment]
> isn't in that screenshot Tyrannus too ? well on tc it is not there because he have modelid of the frostwyrm
> 
> ![tyrannus](https://user-images.githubusercontent.com/24683355/231133315-79a3bb8f-2265-4088-a94d-e66874fce62f.PNG)
> 
> also you can clearly see him here : [youtu.be/zjOPZTi-BmQ?t=63](https://youtu.be/zjOPZTi-BmQ?t=63) and here [youtu.be/orAZWc-svQ8?t=12](https://youtu.be/orAZWc-svQ8?t=12)

but i targeted drake and you see image on down is drake, very likely tyrannus is rider of drake.

**Comment by CraftedRO** [comment]
yes, just out of curiosity have you checked on our current TC how does currently looks ?

**Comment by CraftedRO** [comment]
ah I see, you want the drake to be in unit frame portrait well idk how to do that so I better close this.

**Comment by Aokromes** [comment]
imho the bug is tyrannus ain't rider of drake.

**Comment by CraftedRO** [comment]
have you tried to sniff him, maybe there's another modelid

**Comment by CraftedRO** [comment]
ok according to 
![tyrannus](https://user-images.githubusercontent.com/24683355/231161206-855d8f84-f168-4bb0-bc21-67c84eeaf65e.PNG)

his modelid seems correct, idk where the problem is

**Comment by CraftedRO** [comment]
most likely creature_model_info can be the issue but I'll research

**Comment by Aokromes** [comment]
lack of rider to mount, try to gm on enter pit of saron, fly to drake, and you will see you can ride drake.

**Comment by CraftedRO** [comment]
yea I was riding him by mistake too :D
