### ISSUE TITLE
How to set the display of players from two factions in the list

### ISSUE THREAD

**Issue by 127y** [TrinityCore/TrinityCore#28929]
### Description

How to set the display of players from two factions in the list

### Expected behaviour

Allow players from two factions to be displayed in the list

### Steps to reproduce the problem

Allow players from two factions to be displayed in the list

### Branch

3.3.5

### TC rev. hash/commit

3.3.5

### Operating system

win10

### Custom changes

Allow players from two factions to be displayed in the list

**Comment by Faq** [comment]
questtions go here https://github.com/TrinityCore/TrinityCore/discussions or ask in Discord channel

**Comment by Aokromes** [comment]
or simply check forums where it's listed.
