### ISSUE TITLE
Problem with column bytes1

### ISSUE THREAD

**Issue by Xebastron** [TrinityCore/TrinityCore#28930]
### Description

hello everyone. I'm having a problem loading database 335.23011_2023_01_16.
### Expected behaviour

An error appears on the screen with this text:

Loading Creature template addons...
[1054] Unknown column 'bytes1' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
caught signal 22

How can I solve that?

Thanks and best regards

### Steps to reproduce the problem

Step 1: Update BBDD 

### Branch

3.3.5

### TC rev. hash/commit

335.23011_2023_01_16

### Operating system

Windows 11

### Custom changes

None

**Comment by Aokromes** [comment]
you need updated binaries to use that.

**Comment by Aokromes** [comment]
if you use eluna be sure you use the updated branch, the other is 1 year old.

**Comment by Xebastron** [comment]
to update the binaries, would it be necessary to update the database from old updates?

**Comment by Aokromes** [comment]
what? if you want to import full tdb you need the latest binaries.
