### ISSUE TITLE
Proto-Drake Whelp must fly

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/TrinityCore#28932]
### Description

https://www.wowhead.com/wotlk/item=44721/proto-drake-whelp doesn't fly with owner.`

### Expected behaviour

https://www.wowhead.com/wotlk/item=44721/proto-drake-whelp must fly with owner too.

### Steps to reproduce the problem

.addi 44721
mount on a flying mount 
notice it follows you by land

### Branch

3.3.5

### TC rev. hash/commit

844ced109050990f8f1f2d59160a2cf7e2bf2f27

### Operating system

debian 11 x64

### Custom changes

n/r

**Comment by acidmanifesto** [comment]
I remember making a pr about this before and it was closed citing it wasn't a issue but then the person who closed it made a issue saying it was a issue.

**Comment by Nyr97** [comment]
Do we know if it's related to creature_movement_template at all?

**Comment by Aokromes** [comment]
related.
https://github.com/TrinityCore/TrinityCore/issues/26600

**Comment by whomadeit420** [comment]
I have found a Sql quick fix:
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`) VALUES (32592, 1, 0, 1, 0, 1, 0, NULL);
This will add in proper movements for the pet, this will allow the pet to walk with the player and fly with the player, tested.

**Comment by acidmanifesto** [comment]
> I have found a Sql quick fix:
> INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`) VALUES (32592, 1, 0, 1, 0, 1, 0, NULL);
> This will add in proper movements for the pet, this will allow the pet to walk with the player and fly with the player, tested.

I done a simular pr before and had it closed out saying something along the lines of a ctm adjustment is not a propper fix.

**Comment by Naddley** [comment]
10.0.7 Sniff:
[0] SpellID: 52970 (Levitate)

**Comment by Aokromes** [comment]
TC> lo spell id 52970
TC> 52970 - Levitate, rank 1 enUS

**Comment by CraftedRO** [comment]
```sql
-- Proto-Drake Whelp
DELETE FROM `creature_template_addon` WHERE `entry` =32592;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `MountCreatureID`, `StandState`, `AnimTier`, `VisFlags`, `SheathState`, `PvPFlags`, `emote`, `visibilityDistanceType`, `auras`) VALUES
(32592, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, "52970");

DELETE FROM `creature_template_movement` WHERE `CreatureId`=32592;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`) VALUES
(32592, 0, 0, 1, 0, 0, 0, NULL);
```

**Comment by Nyr97** [comment]
Are you sure that creature_template_movement is correct? If you only set Flight to DisableGravity, the creature's movementpackets will be wrong when walking on ground.

**Comment by Naddley** [comment]
Which Ground movement? This Proto Drake always flys next to you.

**Comment by Nyr97** [comment]
Huh according to these guys, it's supposed to *walk*.

**Comment by CraftedRO** [comment]
It works, tested already before I post but thank you for your concern.

**Comment by Aokromes** [comment]
> Huh according to these guys, it's supposed to _walk_.

https://www.wowhead.com/wotlk/item=44721/proto-drake-whelp#screenshots:id=110362 here is show flying
