### ISSUE TITLE
Basic Campfire does not give Cozy Fire buff

### ISSUE THREAD

**Issue by LeFroid** [TrinityCore/TrinityCore#28945]
### Description

When casting the Basic Campfire spell (id 818) to create a campfire (GO id 29784), the campfire object should give all players in the vicinity a cozy fire buff (spell id 7353).

### Expected behaviour

By walking near the fire, the buff should be applied. ~~When standing near the fire, the buff should be reapplied periodically back to the 60 second effect duration.~~ Thanks for the correction Shauren

### Steps to reproduce the problem

.cast 818
Stand around and observe (walk away and back to the object, etc.)

### Branch

3.3.5

### TC rev. hash/commit

fdc2f5fd9e75af06e28abaa83d4b6cd7c4a8ef06

### Operating system

Linux x64

### Custom changes

None

**Comment by whomadeit420** [comment]
Not confirmed from sniff but if someone can, here is the fix mentioned in a previous fix, maybe it got reverted.
UPDATE `gameobject_template` SET `data6`=-1 WHERE `entry`=31442;

**Comment by whomadeit420** [comment]
also be sure you are not in GM mode.

**Comment by acidmanifesto** [comment]
fun fact. currently the aura is being given out, just not for players. it is applied on npcs
![image](https://user-images.githubusercontent.com/16887899/234384005-814245a8-fde0-4ca7-a616-43caa9d27664.png)

**Comment by Shauren** [comment]
First of all the expected behavior you described is incorrect. The buff is only reapplied if it expires, never before (blizzlike, attribute SPELL_ATTR1_AURA_UNIQUE)

Bugs: 
* summoned trap faction is 35 (makes it apply to everyone, including enemies)
* Use of Trinity::NearestAttackableNoTotemUnitInObjectRangeCheck makes the spell cast never happen on friendly player approaching, it only casts when there is attackable target nearby (enemy or neutral)

**Comment by acidmanifesto** [comment]
> 1) @whomadeit420 tested the database change to no avail
> 2) I appreciate the analysis @acidmanifesto and @Shauren . Is my understanding correct, then, that if there was a way to distinguish this type of trap from others (like hunter trap), getting the campfire to fall into the `else` in the below condition would result in better behavior?
> 
> GameObject.cpp in GameObject::Update , line 652
> ```cpp
> if (GetOwner())  // Need to add some additional qualifier here ? 
> {
>     // Hunter trap: Search units which are unfriendly to the trap's owner                                                                                     
>     Trinity::NearestAttackableNoTotemUnitInObjectRangeCheck checker(this, radius);                                                                            
>     Trinity::UnitLastSearcher<Trinity::NearestAttackableNoTotemUnitInObjectRangeCheck> searcher(this, target, checker);                                       
>     Cell::VisitAllObjects(this, searcher, radius);
> }
> else // Does this treat the object correctly? Or does there need to be a different RangeChecker like in the first if condition
> {
>     // Environmental trap: Any player
>     Player* player = nullptr
>     Trinity::AnyPlayerInObjectRangeCheck checker(this, radius);
>     Trinity::PlayerSearcher<Trinity::AnyPlayerInObjectRangeCheck> searcher(this, player, checker);                                                            
>     Cell::VisitWorldObjects(this, searcher, radius);
>     target = player;
> }
> ```
> 
> Edit: after hacking the condition to force the else condition (`if (GetOwner() && goInfo->entry != 31442)`), the cozy fire was applied normally. So it seems there should be some generic qualifier to add to the if condition. That is, unless the AnyPlayerInObjectRangeCheck would not suffice (is it guaranteed to apply aura on all nearby players, for example)?

Common hackfix is  changed
```
if (GetOwner())
```
to
```
if (owner && goInfo->trap.autoCloseTime != -1) // hunter trap
```

Then run the sql
```
UPDATE `gameobject_template` SET `data6`=-1 WHERE `entry`=31442;
```

Since it touches a template, it is considered a hack, but with this case, anything with -1 for gameobject trap close time will be the qualifier.
