### ISSUE TITLE
How can I learn to create a custom module?

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#28956]
### Description

How can I learn to create a custom module?
is there have demos and docs for me ?
thanks very much

### Expected behaviour

none

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

the last version

### Operating system

ubuntu 22

### Custom changes

3.3.5 passitive anticheat

**Comment by Aokromes** [comment]
this a bug tracker not a learn to code place.
