### ISSUE TITLE
NPC's do not attack player when using Fly command *Even with hacks*, or noclip.

### ISSUE THREAD

**Issue by stefaka8888** [TrinityCore/TrinityCore#28955]
### Description

When flying or being in a wall or some kind of game object, npc's wont attack the player, which leads to big problems regarding using hacks. When using .gm fly on, or when using hacks to make the player fly or noclip through a wall, it gives the player a big advantage over other non-cheating players.

### Expected behaviour

Expected behaviour: I have long thought about this and a potential bugfix. One could be if the player cant be attacked by the npc for 10-15 seconds when using Spell or physical damage, the npc should evade player damage and return to position until the player that is targeted can be attacked *To remove the potential of players attacking the npc from outside of the bugged space and potentionally deem any fix useless*. A problem with this fix could be so if npc can cast spell damage to player, it will reset the timer and the npc wont deal any damage to the player. Tested using player vs player - player can cast spells to the player that is noclipped in the wall, maybe npc can too, so it wouldn't really count as a fix if npc can cast spells

Since flying is a Z-axis problem, it could be fixed so if it can't find a path to the flying player, it should evade the player.

The issue that is mentioned here https://github.com/TrinityCore/TrinityCore/commit/386b5a6fd948b4866cbd9a8a9892e8777922e9c9, has reduced the problem but it is still reproduceable under the right circumstances. 

### Steps to reproduce the problem

Step 1 - Go into fly mode, or noclip mode. When in fly mode, go above npc 5-7 Z-coordinates. The npc can't attack you, but you can attack the npc using ranged and it wont evade, even with the fix mentioned in expected behaviour. For Noclip mode, bug doesn't work everywhere but in places like - .go xyz 338.527863 -3322.903076 118.831635 0 0.180427 and noclip a little bit in the object there just before the tall area of the object. The npc's can't attack you when you are there.

### Branch

3.3.5

### TC rev. hash/commit

No errors in console

### Operating system

Windows 10 x64

### Custom changes

None.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/9206
