### ISSUE TITLE
Gameobjects that have type GAMEOBJECT_TYPE_CHEST = 3, cannot be made to be opened with different speed.

### ISSUE THREAD

**Issue by stefaka8888** [TrinityCore/TrinityCore#28958]
### Description

When opening any kind of chest - For example Object id: 2843, 2849, 75293, etc etc, the speed of opening these crates are exactly the same - 1 second. 

### Expected behaviour

Expected to be opened with different speed - 5 seconds; 10 seconds etc. etc. Like blizzlike

### Steps to reproduce the problem

Step 1 - Locate a chest - .go xyz -9836.426758 209.654312 14.054904 0 4.322687
Step 2 - Click on chest - it opens for 1 second. Every crate you try opens for 1 second.

### Branch

3.3.5

### TC rev. hash/commit

TC rev. 504fcfb2fdd0+ 2022-09-23 09:42:26 -0500 (3.3.5 branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
Why don't you have a valid TC rev. hash/commit ?

**Comment by stefaka8888** [comment]
Sorry, edited!
