### ISSUE TITLE
DB/Creature: Argent Crusader and Knight of the Ebon Blade shoud run instead walk to the ICC entrance

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28957]
### Description

Argent Crusader and Knight of the Ebon Blade shoud run instead walk through entrance of the ICC
checked on retail
https://www.wowhead.com/wotlk/npc=38493/argent-crusader#comments

> Will occasionally form up with [Knights of the Ebon Blade](https://www.wowhead.com/wotlk/npc=38505) to fight off a wave of [Vicious Geists](https://www.wowhead.com/wotlk/npc=31147) and a [Pustulent Horror](https://www.wowhead.com/wotlk/npc=31139). Can also be seen running into the raid portal.

Thanks @CodeLaws (discord) for pointing out.

### SQL fix

```sql
-- UPDATE Argent Crusader and Knight of the Ebon Blade to run instead walk to the ICC entrance
UPDATE `smart_scripts` SET `action_param1` = 1 WHERE `entryorguid` IN (38493, 38505) AND `source_type` = 0 AND `id` = 0;
```

### Branch

3.3.5

### TC rev. hash/commit

046c6b6a3a58

**Comment by CodeLaws** [comment]
Ah ye, that we talked about yesterday :) - Thanks man, would also da a report of this but heavy overloaded with rl shop etc :)

Thanks
