### ISSUE TITLE
Missing column problem during auto-population of mysql db (master branch)

### ISSUE THREAD

**Issue by F0rce1991** [TrinityCore/TrinityCore#28969]
### Description

I'm using a debian system with the latest version and sticked closely to the installation manual of trinitycore on trinitycore.info to set everything up, but during the auto-population of the database I always get an error that the column 'QuestLevel' is missing in the database (as I found out, in the quest_template table in world database). 

Attached you find the Server.log.
[Server.log](https://github.com/TrinityCore/TrinityCore/files/11446277/Server.log)

### Expected behaviour

The auto-population should run automatically through all sql-scripts without getting interrupted by missing columns in the database.

### Steps to reproduce the problem

- set up mysql database (as described here --> https://trinitycore.info/en/install/requirements/linux)
- compile and install trinitycore server
- edit the bnetserver.conf and worldserver.conf
- start worldserver and wait until the error message appears

### Branch

master

### TC rev. hash/commit

---

### Operating system

Debian 11.7.0 x64 (in virtualbox 7.0.8 r156879)

### Custom changes

I haven't made any custom changes.

**Comment by Aokromes** [comment]
you are doing something really bad, a fresh core don't must import such old files

**Comment by F0rce1991** [comment]
okay, but how can I prevent it from doing that because this is done by auto-population. Or can I simply delete those old sql-files from my source files?

**Comment by jackpoz** [comment]
Which TDB did you download ?

**Comment by Aokromes** [comment]
the problem is here, you have download files on real machine and moved to vm? if yes, clone the repository on vm.

>> Reapplying update "2016_09_05_08_world.sql" '55367DB' -> '9D9FBD7' (it changed)...

**Comment by F0rce1991** [comment]
The latest one from here https://github.com/TrinityCore/TrinityCore/releases

**Comment by F0rce1991** [comment]
@Aokromes yeah thats true. I didn't know that this can cause problems. I try to clone it directly to the vm. Thank for the tip.
