### ISSUE TITLE
Core: Aura type Self Visual - Sleep Until Cancelled does broke UNIT_STAND_STATE_SLEEP 3

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28973]
### Description

Aura type Self Visual - Sleep Until Cancelled does broke Standstate: UNIT_STAND_STATE_SLEEP 3

https://www.wowhead.com/wotlk/search?q=Self+Visual+-+Sleep+Until+Cancelled

![WoWScrnShot_051223_141215](https://github.com/TrinityCore/TrinityCore/assets/24683355/f860e5e4-9608-4dfe-9e62-6d178206e54e)

![WoWScrnShot_051223_151556](https://github.com/TrinityCore/TrinityCore/assets/24683355/c179264b-42c0-433f-a357-1044a6689d67)

### Expected behaviour

Those aura type shoudn't break StandState.

![image](https://github.com/TrinityCore/TrinityCore/assets/24683355/4b327110-4ba3-45f1-8db5-520e95371e0c)

### Steps to reproduce the problem

.go c 102139
.aura 16093
notice weird position change

### Branch

3.3.5

### TC rev. hash/commit

2f4c412f4c13

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
dd10ac27fee1 For some creatures this is still brocked:
.go c 50414 (standstate 7 UNIT_STAND_STATE_DEAD)
.go c 68338

**Comment by Faq** [comment]
@CraftedRO pls make new issue
