### ISSUE TITLE
Certain Quests Missing From Death Knight Zone

### ISSUE THREAD

**Issue by StonedCookieGaming** [TrinityCore/TrinityCore#28970]
### Description

There are certain quests missing or bugged inside the Death Knight Starting Zone. See the list below

1. An End to All Things - The Lich King does not give this quest after finishing "The Scarlet Apocolypse
2. The Light of Dawn - Dialogue between Tirion Fordring, The Lich King, and Darion Morgraine does not trigger and the NPC to turn in the quest does not appear.
3. Taking Back Acherus - Possible phasing issue as a result of the above as Death Gate will not take you back to Acherus.

### Expected behaviour

These quests should work properly and the quest line should be completable

### Steps to reproduce the problem

1. Fly down to the lich king and accept the quest: An End to All Things
2. Observe as the quests bug out from there.

### Branch

master

### TC rev. hash/commit

N/A

### Operating system

Windows Server 2022

### Custom changes

None

**Comment by Aokromes** [comment]
make one issue for each bugged quest.
fill hash revision.
