### ISSUE TITLE
DB/Warrior: Added spellproc data for Fueled by Violence

### ISSUE THREAD

**Issue by SargeroDeV** [TrinityCore/TrinityCore#28976]
### Description

Added spellproc data for Fueled by Violence SpellId: 383103

### SQL fix

```sql
DELETE FROM `spell_proc` WHERE `SpellId` IN (383103);
INSERT INTO `spell_proc` (`SpellId`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask0`,`SpellFamilyMask1`,`SpellFamilyMask2`,`SpellFamilyMask3`,`ProcFlags`,`ProcFlags2`,`SpellTypeMask`,`SpellPhaseMask`,`HitMask`,`AttributesMask`,`DisableEffectsMask`,`ProcsPerMinute`,`Chance`,`Cooldown`,`Charges`) VALUES
(383103,0x00,4,0x00080000,0x00000000,0x00400000,0x00000000,0x0,0x0,0x1,0x2,0x0,0x0,0x0,0,0,0,0); -- Fueled by Violence
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/c4d40085964109893c76d301b6f7d99f03838fa0

**Comment by mdX7** [comment]
i just implemented the entire spell, i did one change to your spell_proc entry:
- HitMask changed to 0x403
That makes it only proc on normal hits, crits or absorbs

**Comment by SargeroDeV** [comment]
> * HitMask changed to 0x403

How do you know that this proc uses HitMask 0x403 ?

**Comment by mdX7** [comment]
Thats kinda the "basic" hitmask for every spell which should proc on damage **done**.

Other examples for hitmask would be miss, dodge, parry etc. but for those cases the spell doesn't deal damage, so we do not need to proc

**Comment by SargeroDeV** [comment]
I see, thanks
