### ISSUE TITLE
Problem Command .respawn For Boss

### ISSUE THREAD

**Issue by poryagholami** [TrinityCore/TrinityCore#28989]
### Description

When I use the .respawn command to revive the bosses, it doesn't work

### Expected behaviour

None

### Steps to reproduce the problem

.tele icec
Open a ride and hit the first boss with .damage 500000000 
.resp

### Branch

3.3.5

### TC rev. hash/commit

rev. 47b1de526e9f+

### Operating system

window server 2019 64bit

### Custom changes

None

**Comment by Ovahlord** [comment]
Not a bug, intentional. Boss respawns are linked to spawn groups which are tied to the boss encounter and only allow spawning as long as the encounter has not been completed.

**Comment by CraftedRO** [comment]
.instance setbossstate right ?
