### ISSUE TITLE
Can‘t get log from stdout

### ISSUE THREAD

**Issue by CalsRanna** [TrinityCore/TrinityCore#28982]
### Description

When i try to write a launcher of server, i used js to catch logs from stdout. Some days ago, maybe months, it works well. But some how i upgrade code from repository, it will not get logs from stdout, but the same code use to get log information about mysqld works well, so i'm asking here for help.

### Expected behaviour

Want to get log information from stdout.

### Steps to reproduce the problem

run auth server as expected

### Branch

3.3.5

### TC rev. hash/commit

the latest commit

### Operating system

win11

### Custom changes

None

**Comment by Aokromes** [comment]
this is trinitycore bug tracker, not i am writing some custom code bug tracker.
