### ISSUE TITLE
Server Crash Spell.cpp:8142

### ISSUE THREAD

**Issue by NesinAlex** [TrinityCore/TrinityCore#28983]
### Description

I'm not sure. But the crash is somehow related to DK and NPC Hogger (id 448)

### Expected behaviour

Crash should never be

### Steps to reproduce the problem

My server player was just running away from the NPC outside of his clearing.

### Branch

master

### TC rev. hash/commit

/root/TrinityCore/src/server/game/Spells/Spell.cpp:8142 in Execute ASSERTION FAILED:
  n_offset == m_Spell->GetDelayMoment()
475 == 0

### Operating system

Ubuntu 22

### Custom changes

None

**Comment by NesinAlex** [comment]
![image](https://github.com/TrinityCore/TrinityCore/assets/42183646/3b53681b-68d4-45d0-9850-33affd2075cd)

**Comment by NesinAlex** [comment]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC5
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000ABF
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-525-00000095AD
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-42548-0000000AC4
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-1-0-3331-0000000976

/root/TrinityCore/src/server/game/Spells/Spell.cpp:8142 in Execute ASSERTION FAILED:
  n_offset == m_Spell->GetDelayMoment()
475 == 0


Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff175f640 (LWP 279301)]
0x0000555556832261 in Trinity::Assert (file=<optimized out>, line=line@entry=8142, function=<optimized out>, debugInfo="", message=<optimized out>, format=<optimized out>) at /root/TrinityCore/src/common/Debugging/Errors.cpp:92
92          Crash(formattedMessage.c_str());

BACKTRACE

#0  0x0000555556832261 in Trinity::Assert (file=<optimized out>, line=line@entry=8142, function=<optimized out>, debugInfo="", message=<optimized out>, format=<optimized out>) at /root/TrinityCore/src/common/Debugging/Errors.cpp:92
#1  0x0000555556598ecc in SpellEvent::Execute (this=<optimized out>, e_time=43249, p_time=<optimized out>) at /root/TrinityCore/src/server/game/Spells/Spell.cpp:8142
#2  0x000055555681d976 in EventProcessor::Update (this=0x7ffe8ce6a390, p_time=13) at /root/TrinityCore/src/common/Utilities/EventProcessor.cpp:55
#3  0x0000555556264008 in Unit::Update (this=0x7ffe8d56bc50, p_time=3128027472) at /root/TrinityCore/src/server/game/Entities/Unit/Unit.cpp:448
#4  0x0000555556117569 in Creature::Update (this=0x7ffe8ce6a100, diff=13) at /root/TrinityCore/src/server/game/Entities/Creature/Creature.cpp:787
#5  0x000055555633a0e6 in Trinity::ObjectUpdater::Visit<Creature> (this=0x7ffff175d490, m=...) at /root/TrinityCore/src/server/game/Grids/Notifiers/GridNotifiers.cpp:263
#6  0x00005555563f0072 in VisitorHelper<Trinity::ObjectUpdater, Creature> (v=..., c=...) at /root/TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:43
#7  VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > (v=..., c=...) at /root/TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:49
#8  VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > (v=..., c=...) at /root/TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:50
#9  VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (v=..., c=...) at /root/TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:56
#10 TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > >::Visit (this=<optimized out>, c=...) at /root/TrinityCore/src/server/game/Grids/Dynamic/TypeContainerVisitor.h:90
#11 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::Visit<Trinity::ObjectUpdater> (this=<optimized out>, visitor=...) at /root/TrinityCore/src/server/game/Grids/Grid.h:90
#12 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > (this=<optimized out>, x=<optimized out>, y=y@entry=2, visitor=...) at /root/TrinityCore/src/server/game/Grids/NGrid.h:147
#13 0x00005555563d9367 in Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeList<AreaTrigger, TypeList<SceneObject, TypeList<Conversation, TypeNull> > > > > > > > > (this=0x7fff2d667340, cell=..., visitor=...) at /root/TrinityCore/src/server/game/Maps/Map.h:891
#14 Map::VisitNearbyCellsOf (this=this@entry=0x7fff2d667340, obj=obj@entry=0x7fff2d0de140, gridVisitor=..., worldVisitor=...) at /root/TrinityCore/src/server/game/Maps/Map.cpp:646
#15 0x00005555563d97a2 in Map::Update (this=0x7fff2d667340, t_diff=13) at /root/TrinityCore/src/server/game/Maps/Map.cpp:714
#16 0x00005555563fb5f5 in MapUpdateRequest::call (this=0x7fff2e9a0120) at /root/TrinityCore/src/server/game/Maps/MapUpdater.cpp:43
#17 0x00005555563fb197 in MapUpdater::WorkerThread (this=0x5555571f1df0 <MapManager::instance()::instance+144>) at /root/TrinityCore/src/server/game/Maps/MapUpdater.cpp:119
#18 0x00007ffff70942b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff6d1db43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007ffff6dafa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

**Comment by ZaDarkSide** [comment]
Might be related to this commit https://github.com/TrinityCore/TrinityCore/commit/295c8f63269d966812f37a8bd8e988a9f2dc1235

**Comment by infidelus** [comment]
Also confirming this.  You don't even need to attack Hogger, just run into the area where he stands.  He charges you and worldserver immediately crashes.  This happened with a lvl 10 Priest.
