### ISSUE TITLE
custom script loader seem's not work

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#28988]
### Description

/home/trinity-core/src/server/scripts/Custom/npc_dream_angel.cpp
`#include "ScriptMgr.h"
#include "Player.h"
#include "ScriptedGossip.h"
#include <iostream>

class npc_dream_angel : public CreatureScript
{
public:
	npc_dream_angel() : CreatureScript("npc_dream_angel") 
	{
		std::cout << "npc_dream_angel script loaded." << std::endl;
	}

	struct npc_dream_angelAI : public ScriptedAI
	{
		npc_dream_angelAI(Creature* creature) : ScriptedAI(creature) { }

		bool GossipSelect(Player* /*player*/, uint32 /*menu_id*/, uint32 /*gossip_list_id*/)
		{
			return true;
		}

		bool GossipHello(Player* player)
		{
			std::cout << "Player is interacting with NPC." << std::endl;
			CloseGossipMenuFor(player);
			return true;
		}
	};

	CreatureAI* GetAI(Creature* creature) const
	{
		return new npc_dream_angelAI(creature);
	}
};

void Addnpc_dream_angelScripts()
{
	new npc_dream_angel();
}
`

/home/trinity-core/src/server/scripts/Custom/custom_script_loader.cpp
`void Addnpc_dream_angelScripts();

void AddCustomScripts()
{
    Addnpc_dream_angelScripts();
}`

mysql
`REPLACE INTO creature_template SET entry=60001, modelid1=24991, scale=1.5, name='Dream Angel', faction=35, npcflag=3, unit_class=1, type=7, ScriptName='npc_dream_angel';`

/home/trinity-core/src/server/scripts/CMakeLists.txt
before 
`add_library(${SCRIPT_MODULE_PROJECT_NAME} SHARED`
add
`set(sources ${sources} ${CMAKE_CURRENT_SOURCE_DIR}/Custom/custom_script_loader.cpp)`

### Expected behaviour

when click the npc, it should output: Player is interacting with NPC.
but never happen.

### Steps to reproduce the problem

update those files then rebuild

### Branch

3.3.5

### TC rev. hash/commit

newest

### Operating system

ubuntu22

### Custom changes

nothing

**Comment by Aokromes** [comment]
it works, being using custom script for years. for custom scripts questions ask on https://discord.trinitycore.org/

**Comment by mdX7** [comment]
you gotta use **On**GossipHello and **On**GossipSelect (you forgot **On**):

```c
bool OnGossipHello(Player* /*player*/) override
{
    return false; 
}

bool OnGossipSelect(Player* /*player*/, uint32 /*menuId*/, uint32 /*gossipListId*/) override
{
    return false;
}
```
also notice the override keyword

**Comment by 5266869** [comment]
> 

good,it is worked.thanks very much.
