### ISSUE TITLE
Druid/Spell: Dash shoud only be usable in cat form

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#28992]
### Description

Dash can be used in any form

### Expected behaviour

Dash shoud only be usable in cat form

![WoWScrnShot_051523_204414](https://github.com/TrinityCore/TrinityCore/assets/24683355/2bcf4179-938c-40c5-a8e7-bee491ea08a0)

### Steps to reproduce the problem

Create a Druid
learn dash
cast it in any form

### Branch

3.3.5

### TC rev. hash/commit

47b1de526e9f

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
```sql
-- Use Dash only when in Cat Form
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry` IN (1850, 9821, 33357);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(17, 0, 1850, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank1 only when in Cat Form'),
(17, 0, 9821, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank2 only when in Cat Form'),
(17, 0, 33357, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank3 only when in Cat Form');
```

**Comment by r4d1sh** [comment]
> ```sql
> -- Use Dash only when in Cat Form
> DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=17 AND `SourceGroup`=0 AND `SourceEntry` IN (1850, 9821, 33357);
> INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
> (17, 0, 1850, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank1 only when in Cat Form'),
> (17, 0, 9821, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank2 only when in Cat Form'),
> (17, 0, 33357, 0, 0, 1, 0, 768, 0, 0, 0, 172, 32, '', 'Use Dash Rank3 only when in Cat Form');
> ```

This fix looks absolutely correct
