### ISSUE TITLE
Can't start the server - Crash

### ISSUE THREAD

**Issue by MaDmaX1337** [TrinityCore/TrinityCore#28995]
### Description

Server is crashing by:
![image](https://github.com/TrinityCore/TrinityCore/assets/11060723/6ff78bd8-9386-4937-abfb-962e82d27000)

### Expected behaviour

Start without crash.

### Steps to reproduce the problem

Compile fresh server and try to start.

### Branch

master

### TC rev. hash/commit

baefed8b955c

### Operating system

Windows Server 2016

### Custom changes

No Changes applied.

**Comment by Aokromes** [comment]
update db2/gt files

**Comment by MaDmaX1337** [comment]
I did updated the db2 files, right now the gt. But still have the problem.

**Comment by Shauren** [comment]
hotfix build added new aura type
