### ISSUE TITLE
Worldserver crash after ingame login (inserted old DB data in auth and characters)

### ISSUE THREAD

**Issue by humanpride** [TrinityCore/TrinityCore#29018]
### Description

After entering e-mail and password, loading of the list of characters begins and at this moment the worldserver is turned off, error window appears "Server connection lost (WOW51900319)"

Crashlog: https://gist.github.com/humanpride/f43bf89b97965ae9ff54a9c28803d891

### Expected behaviour

Loading list of characters and entering the game

### Steps to reproduce the problem

1. Run the server
2. Ingame login

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 907d9f1a79b8 2023-05-20 13:57:57 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes

Added data from the old auth and characters databases via a dump with the insert ignore command. The idea was to load the old characters into the game (from the BfA build)

**Comment by KamiliaBlow** [comment]
Perhaps the transfer of characters from BFA was not correct, because starting with SL the system of the appearance of the character was changed a lot. As well as what parameters may be missing at that time.

**Comment by humanpride** [comment]
Launched on clean databases - works

**Comment by Shauren** [comment]
You should be applying all sql updates incrementally, not exporting data from old database and importing it into new structure

**Comment by humanpride** [comment]
I restored the old auth and characters databases and then just started bnetserver and worldserver. The update has happened. Now I can log in without crash, but there was an error with Trinity realm, population - incompatible. How to fix that?

**Comment by Shauren** [comment]
Supported version is 49570, update that too

**Comment by humanpride** [comment]
After update 'gamebuild' in realmlist teble everything is working properly. Thank you very much
