### ISSUE TITLE
Warrior: Berserker Rage do not remove your existent fear

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29012]
### Description

Berserker Rage do not remove fear effects

https://github.com/TrinityCore/TrinityCore/assets/24683355/26b9c50a-8fe7-47fa-b49b-f06ca588bbae

### Expected behaviour

Berserker Rage shoud remove fear on your character as it does with sap and incapacitate effects and as is stated on spell tooltip.

### Steps to reproduce the problem

create warrior
learn berserker rage
.aura 65809
cast Berserker Rage

### Branch

3.3.5

### TC rev. hash/commit

47b1de526e9f

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
oh i was told this but never found spell, confirmed.

**Comment by Shauren** [comment]
0a34290484f3e90a2a642986de682a8b0c7e3815
