### ISSUE TITLE
Quest issue -  "into the scarlet monastery"

### ISSUE THREAD

**Issue by tch1g0z3tt3** [TrinityCore/TrinityCore#29024]
### Description

the quest "into the scarlet monastery" cannot be completed because after killing the boss "commander mograine slain", nothing happens

### Expected behaviour

quest completed and achivement unlocked

### Steps to reproduce the problem

- step into crusader's chapel
- kill commander mograine slain

### Branch

3.3.5

### TC rev. hash/commit

latest

### Operating system

windows 11

### Custom changes

None

**Comment by tch1g0z3tt3** [comment]
TC rev. hash/commit fb38829

**Comment by CraftedRO** [comment]
this seems invalid, you know that you have to wait for it to be resurected by High Inquisitor Whitemane, right ?


https://github.com/TrinityCore/TrinityCore/assets/24683355/c30e3dd3-f5e6-42f8-a589-5fca117e257b

**Comment by Aokromes** [comment]
if you kill it to fast with a high level char it will bug.

**Comment by Nyr97** [comment]
in retail, it's default behaviour to delay it even if you kill it at high level and still count towards it though :D

**Comment by Aokromes** [comment]
> in retail, it's default behaviour to delay it even if you kill it at high level and still count towards it though :D

i got reports of dots bugging it, direct damage no problem.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/26480
