### ISSUE TITLE
OnChat not work

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#29033]
### Description

`#include "auto_player.h"

class auto_player : public PlayerScript {
public:
	auto_player() : PlayerScript("auto_player") {}

	void OnLogin(Player* player, bool firstLogin) override {
		std::cout << "OnLogin" << std::endl;
		ChatHandler(player->GetSession()).SendGlobalSysMessage("111");
	}
	
	void OnChat(Player* player, uint32 /*type*/, uint32 lang, std::string& msg) override {
		std::cout << "OnChat" << std::endl;
		ChatHandler(player->GetSession()).SendGlobalSysMessage("222");
	}
};

void ScriptsADDauto_player(){
	new auto_player();
};
`

please see this custom script, OnLogin is good when a player login, but OnChat is not when the player chat.
why is happen? is it issue or am i miss some settings ?
thanks.

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

3.3.5

### TC rev. hash/commit

newest

### Operating system

ubuntu22

### Custom changes

none

**Comment by MaxtorCoder** [comment]
This is a bug report forum, not help for custom scripts. We have a Discord for this.

Also, read the source, a lot of documentation there.
