### ISSUE TITLE
[ICC] Valanar - Empowered shock vortex

### ISSUE THREAD

**Issue by overy** [TrinityCore/TrinityCore#2903]
How it is work on offi :

When he have buff and cast Empowered shock vortex, players must have min 10y distance, because they take only 5k damage. 

How it is work on TC:

Players can stay with 50y (for etc.) they take 5k damage and give KICKBACK - that is bad. When they have more them 10y distance they dont take KICKBACK.

rev:  5d0a2b6094e0af1ba1ca
TDB DB with all updates
##

**Comment by Keader** [comment]
Working in rev 87092140740b7d6e30687345f8df1984222c2946
