### ISSUE TITLE
Titan's Grip - Can't Dual Wield 2H Weapons

### ISSUE THREAD

**Issue by StonedCookieGaming** [TrinityCore/TrinityCore#29035]
### Description

I recently created a warrior to test some fixes that were released awhile ago and noticed that Titan's grip doesn't work. You cannot dual wield two handed weapons.

### Expected behaviour

Titan's grip should allow the use of dual wielding two handed weapons.

### Steps to reproduce the problem

1. Create a warrior
2. Either force learn Titan's grip or unlock it the old fashioned way.
3. Observe as you cannot equip dual two handed weapons.

### Branch

master

### TC rev. hash/commit

There is no debug command available for spells or weapons. Therefore, I could not get an error or any type of output.

### Operating system

Windows 11/Windows Server 2022

### Custom changes

None

**Comment by ImmortalusDev** [comment]
Can you try more 2H weapons?

**Comment by StonedCookieGaming** [comment]
I did. Tried several.

**Comment by therelus** [comment]
Must learn in Trainer the Dual Wielding, make sure it and try again :P

**Comment by Naddley** [comment]
cant reproduce this. titans Grip works as intended for me.
