### ISSUE TITLE
DB: Update new holiday dates for Darkmoon Faire

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29040]
### Description

Update new holiday dates for Darkmoon Faire

### SQL fix

```sql
https://gist.github.com/CraftedRO/49a15349bb9955ea5f1ce8be364e1f4d
```

### Branch

3.3.5

### TC rev. hash/commit

d5ef68bc9b45

**Comment by Aokromes** [comment]
i wonder it can work adding dates after date 25 instead update old ones?

**Comment by CraftedRO** [comment]
table format do not allow this

**Comment by CraftedRO** [comment]
my bad core do not allow more than 25 entries:

> holiday_dates entry has out of range date_id 26.

**Comment by Aokromes** [comment]
i was told it's client limitation.
