### ISSUE TITLE
[Quest] Agmar's Hammer -12008 (Unable to access Wrathgate)

### ISSUE THREAD

**Issue by T-newel** [TrinityCore/TrinityCore#29044]
### Description

The issues is that upon completing the quest multiple quests are supposed to unlock in the the Agmar's Hammer city of the Horde faction. 

12056 - Marked for Death: High Cultist Zangus 
(This quest line leads to all of Koltira's quest lines https://www.wowhead.com/wotlk/quest=12136/the-translated-tome)

and

**12034** - Victory Nears..

Should become available after turning this quest in to https://www.wowhead.com/wotlk/npc=26379/overlord-agmar

In my DB after a fresh update quest 12008 linked to 12224 which should only become available once all Horde Wrathgate Scenario quests are completed (12034 Victory nears, itself is responsible for opening 2 of the required quests to do wrathgate)

Upon changing quest_template_addon to reflect quest 12008 to have nextquestid12034 and also changing quest 12034 to have a prevquestid to 12008 Overlord Agmar still does not show quest 12034.

### Expected behaviour

When someone completed the https://www.wowhead.com/wotlk/quest=11929/the-fall-of-taunkale-village Series quests they are sent to Agmar's hammer and should immediately unlock several quest lines. 

Then upon completions of

https://www.wowhead.com/wotlk/quest=12072/blightbeasts-be-damned

(^Requires quest number 2 in the above chain) https://www.wowhead.com/wotlk/quest=12140/all-hail-roanauk

https://www.wowhead.com/wotlk/quest=12221/the-forsaken-blight

Finally https://www.wowhead.com/wotlk/quest=12224/the-korkron-vanguard should be unlocked.

### Steps to reproduce the problem

Complete quest https://www.wowhead.com/wotlk/quest=12008/agmars-hammer

Then speak to https://www.wowhead.com/wotlk/npc=26379/overlord-agmar
To obtain https://www.wowhead.com/wotlk/quest=12034/victory-nears

(optionally claim)
https://www.wowhead.com/wotlk/npc=26618/captain-gort - Does not give 
https://www.wowhead.com/wotlk/quest=12056/marked-for-death-high-cultist-zangus

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 408b91774a7b 2023-05-20 01:12:58 +0000 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 2019 Datacenter Editions

### Custom changes

Legion Transmog patch by Rochet2

**Comment by T-newel** [comment]
So this also affects https://www.wowhead.com/wotlk/quest=12039/black-blood-of-yogg-saron

**Comment by CraftedRO** [comment]
tested ingame seems fine:
```sql
-- Fix credit cmangos
UPDATE `quest_template_addon` SET `ExclusiveGroup`=0, `NextQuestId`=0 WHERE `ID`=12008;
```

**Comment by CraftedRO** [comment]
I found something interesting, maybe here's a core problem even if my above quest fix this
https://github.com/TrinityCore/TrinityCore/issues/19300
