### ISSUE TITLE
DB: Update gossip text for Darnassus Sentinel for Mage & Paladin directions

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29045]
### Description

Update gossip text for Darnassus Sentinel for Mage & Paladin directions it wasn't sniffed but I have this screenshoot from wotlk classic ptr (I checked myself ingame and it looks same for mage and paladin gossip):

and also I have this wowhead comment as proof: https://www.wowhead.com/wotlk/npc=4262/darnassus-sentinel#comments:id=1005457

![WoWScrnShot_060123_194413](https://github.com/TrinityCore/TrinityCore/assets/24683355/56a066e2-07af-40e7-b55a-6602cd48901e)

Tested ingame it works but you may need to delete cache folder.

### SQL fix

```sql
-- Update gossip text for Darnassus Sentinel for Mage & Paladin directions
SET @text="You will find a pair of draenei conversing with Tyrande Whisperwind in the upper level of The Temple of the Moon.$B$BThey will know how to help you.";
UPDATE `npc_text` SET `text0_0`=@text, `text0_1`=@text,`BroadcastTextID0`=0, `VerifiedBuild`=49705 WHERE `ID`=15906;
```

### Branch

3.3.5

### TC rev. hash/commit

fb699dc64134

**Comment by Aokromes** [comment]
not sure if correct since it changes broadcast_text
