### ISSUE TITLE
Any command to solve this problem?

### ISSUE THREAD

**Issue by rumi433** [TrinityCore/TrinityCore#29050]
### Description

When I try to log with my character the game crashes with an error when the load screen is complete.. I think it's a bug due to a quest or the zone where I last played.. Anyway I need to log with my character once again so, is there a command I can put in any of the applications or something to place my character in another safe place so I can log in? If not, what can I do? I don't want to lose all my progress.. I attached the error if anyone want to see it.
![error](https://github.com/TrinityCore/TrinityCore/assets/135481639/ee0a03b4-90a7-49e4-9384-55eac05f2bfb)

### Expected behaviour

.

### Steps to reproduce the problem

.

### Branch

.

### TC rev. hash/commit

.

### Operating system

.

### Custom changes

.

**Comment by Aokromes** [comment]
your client is very likely broken or you are using custom things.

**Comment by jackpoz** [comment]
You can .summon your offline character to another character's location

**Comment by rumi433** [comment]
> You can .summon your offline character to another character's location

It worked!! Thank you so much jackpoz!! I have another question if you don't mind.. I want to do a backup of my character in case of future problems but I'm not sure where it's stored my character data and stuff in the folder. Can you tell me please? I'm kinda new using this.

**Comment by jackpoz** [comment]
You can use .pdump commands to export and import characters

**Comment by Aokromes** [comment]
> > You can .summon your offline character to another character's location
> 
> It worked!! Thank you so much jackpoz!! I have another question if you don't mind.. I want to do a backup of my character in case of future problems but I'm not sure where it's stored my character data and stuff in the folder. Can you tell me please? I'm kinda new using this.

your problem is that your client is broken, dumping characters never will fix that.
