### ISSUE TITLE
Gameobject / Loot : during the request to obtain the item, the window will open for a very short time

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#29065]
### Description

Gameobject / Loot : during the request to get the item, the window will open for a very short time - you have to be very clever / quick to get the item before the menu window closes automatically 

[video link](https://streamable.com/plv6xg)

### Expected behaviour

- the item/loot menu window should be closed first after obtaining the item or after manual confirmation by the player to close the window

### Steps to reproduce the problem

1. create a panda character
2. take the first quest
3. go to the position and try to pick up the item

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 8d1a57eb9636 2023-06-06 00:50:41 +0200 (master branch)

### Operating system

Win 11 Pro

### Custom changes

none

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/issues/29023
