### ISSUE TITLE
Drac'Thyr Can't Choose Spec

### ISSUE THREAD

**Issue by StonedCookieGaming** [TrinityCore/TrinityCore#29067]
### Description

The Drac'Thyr cannot select a specialization when they reach the appropriate level.

### Expected behaviour

The Drac'Thyr race should be able to choose their specialization.

### Steps to reproduce the problem

1. Create a Drac'Thyr
2. Reach the appropriate level
3. Attempt to choose your specialization.

### Branch

master

### TC rev. hash/commit

I attempted to make a skip module for the Drac'Thyr quest line and it didn't work.

### Operating system

Windows 11/Server 2022

### Custom changes

I applied a skip module for the Drac'Thyr quest line and it didn't fix the issue.

**Comment by Naddley** [comment]
Evoker needs to complete a Quest to unlock his talents same like DH

**Comment by StonedCookieGaming** [comment]
We tried that. No good.

**Comment by mdX7** [comment]
reward quest 65701 or set lvl to >=70

**Comment by StonedCookieGaming** [comment]
> 

Did both, still not working.

**Comment by taube11111** [comment]
Jup, I can verify that it don't work in both ways.

**Comment by Naddley** [comment]
![WoWScrnShot_061023_182206](https://github.com/TrinityCore/TrinityCore/assets/64811442/5a9c3029-dc6a-4729-bf4b-cd8d98c87e6d)

quest added, completed then rewarded with commands and I got my talents unlocked with a fresh created evoker.
And if you use Spell: 218386 you can select the spec.

**Comment by taube11111** [comment]
I ll check, thanks 😍 - It works !!!

**Comment by StonedCookieGaming** [comment]
It doesn't work for us. We did the steps provided and we get "value 'spell' is not valid type for unsigned int."
