### ISSUE TITLE
Underwater / Submarin Transports

### ISSUE THREAD

**Issue by gonzo1247** [TrinityCore/TrinityCore#29061]
### Description

Underwater / submarine transports are not correctly recognized as transport objects. Neither players nor NPCs are added to this transport. It also seems that the core thinks the player is normally underwater and not in a transport. 

### Expected behaviour

Players / NPCs should also be added to this transport correctly. 

### Steps to reproduce the problem

```
Add these two transport entries to the World database: 
DELETE FROM `transports` WHERE `guid`=34;
INSERT INTO `transports` (`guid`, `entry`, `name`, `phaseUseFlags`, `phaseid`, `phasegroup`, `ScriptName`) VALUES
(34, 203620, 'Alliance Submarine to Leviathan Cave', 0, 228, 0, '');
DELETE FROM `transports` WHERE `guid`=35;
INSERT INTO `transports` (`guid`, `entry`, `name`, `phaseUseFlags`, `phaseid`, `phasegroup`, `ScriptName`) VALUES
(35, 203621, 'Horde Submarine to Leviathan Cave', 0, 228, 0, '');
```

start the server and go to the following coordinate:
-7210.129 3919.679 3.931

Give yourself the following aura there: 79230 

Wait for the transport to arrive and go to the transport.

### Branch

master

### TC rev. hash/commit

8d1a57eb963601c9c8e27b0f54ab528b8058781f

### Operating system

Windows

### Custom changes

None except for the two transport entries from above.

**Comment by gonzo1247** [comment]
After some searching I can now say the following:
The opcode CMSG_MOVE_CHANGE_TRANSPORT is not sent when going to the submarine. But for normal ships for example it is. The CMSG_MOVE opcodes have the field HasTransportData set to False.
But in the Retail Sniff CMSG_MOVE_CHANGE_TRANSPORT is called when entering the submarine. 

`ClientToServer: CMSG_MOVE_CHANGE_TRANSPORT (0x3A2F) Length: 94 ConnIdx: 1 Time: 06/01/2023 15:23:15.518 Number: 15028
MoverGUID: Full: 0x000000000000000000000000000000000 Player/0 R000/S0 Map: 0 (Eastern Kingdoms) Low: 000000000
MovementFlags: 0 (None)
MovementFlags2: 512 (PreventChangePitch)
MovementFlags3: 0 (None)
MoveTime: 8138777
Position: X: -7232.1865 Y: 3692.9565 Z: -146.83598 O: 1.6671548
Pitch: -0.00155099132098257
StepUpStartElevation: 0
RemoveForcesCount: 0
MoveIndex: 0
HasStandingOnGameObjectGUID: True
HasTransportData: True
HasFallData: False
HasSpline: False
HeightChangeFailed: False
RemoteTimeValid: False
HasInertia: False
HasAdvFlying: False
(TransportData) Guid: Full: 0x0
(TransportData) Position: X: -7232.1865 Y: 3692.9565 Z: -146.83598 O: 3.237983
(TransportData) Seat: 255
(TransportData) MoveTime: 6
(TransportData) HasPrevMoveTime: False
(TransportData) HasVehicleRecID: False
StandingOnGameObjectGUID: Full: 0x18015AC000000000000191000000000 Transport/0 R86/S401 Map: 5632 Low: 94086000000`

**Comment by aquadeus** [comment]
check if the transports have GO_FLAG_TRANSPORT

**Comment by gonzo1247** [comment]
This solves the problem. I did not pay attention to the flags. Thanks for that.
