### ISSUE TITLE
DB/Creature: Jol has wrong Z spawn hight

### ISSUE THREAD

**Issue by Jonne733** [TrinityCore/TrinityCore#29079]
### Description

Paladin trainer [Jol](https://aowow.trinitycore.info/?npc=17509) is spawning a little bit above the ground.

### SQL fix

```sql
-- Jol Correct Z spawn hight
UPDATE `creature` SET `position_z`=-131.4370 WHERE `guid`=63007;
```

### Branch

3.3.5

### TC rev. hash/commit

fb699dc64134

**Comment by CraftedRO** [comment]
Are these values sniffed ?

**Comment by heyitsbench** [comment]
3.4.0 45942 for 17509
```
Position: X: -4191.512 Y: -11471.797 Z: -130.78955
Orientation: 4.642575740814208984
```

**Comment by Jonne733** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/qBSdrMiHZrk?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

in the video above I use the ".go crea" command to teleport directly to her, and you can see that for a split second she is in the air before dropping down to the ground.

**Comment by Jonne733** [comment]
oops, didn't mean to close it :P

**Comment by CraftedRO** [comment]
"Modifying data without sniff is hack" :laughing:

**Comment by malcrom** [comment]
Many creatures do this on official wow.
