### ISSUE TITLE
DBC reported an error

### ISSUE THREAD

**Issue by 0AvA0** [TrinityCore/TrinityCore#29072]
### Description

![image](https://github.com/TrinityCore/TrinityCore/assets/89952068/4b5b4109-b276-407e-bedd-83a243ed75af)

### Expected behaviour

How should I modify it

### Steps to reproduce the problem

sudo ./worldserver

### Branch

master

### TC rev. hash/commit

sudo ./worldserver

### Operating system

Ubuntu 22.04.2

### Custom changes

not

**Comment by Aokromes** [comment]
problem is in chair.

**Comment by 0AvA0** [comment]
@Aokromes Newbies don't quite understand, what do you mean.
