### ISSUE TITLE
n_offset server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29076]
### Description

https://gist.github.com/PivanDepolo/6e0bcbe90c1f2d8270ebcd4b497d7759

### Expected behaviour

Must not crash

### Steps to reproduce the problem

idk

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f93b4d6c438b337d15bf1666f6f0e050beb97ce4

### Operating system

Debian 11

### Custom changes

No

**Comment by Shauren** [comment]
Duplicate of #28983

**Comment by PivanDepolo** [comment]
This seems to happen when a Hunter or Warlock summons pets.
