### ISSUE TITLE
spell_mage_ignite Server crash

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29089]
### Description

I'm not sure but it looks like the crash triggers the spell [Ignite](https://www.wowhead.com/spell=12654/ignite) with its procs

https://gist.github.com/PivanDepolo/1dd93c4d8487bc867befa9fdec994c11
https://gist.github.com/PivanDepolo/98105b50c4a6b642d7c9b5b211c1ec2f

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Not sure how to reproduce correctly

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/23752a5c70aef46cd098409598955b870e0b65f4

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
Duplicate...
