### ISSUE TITLE
[Spell/Class/Warrior] Bladestorm 2h Problem.

### ISSUE THREAD

**Issue by lordl00k** [TrinityCore/TrinityCore#2909]
When im useing a 1h and shield and then bladestorm and click the button for my 2h the bladestorm cancel's it self i saw a vid when a warrior bladestormed with 1h/shield and then changed to 2h in the bladestorm and it didn't cancel the bladestorm.

The video: http://www.youtube.com/watch?v=xodQe646q_Q&feature=channel_video_title

0:29 is the moment

TrinityCore Hash 83912c43ad2e+
World DB: TDB 335.11.41

**Comment by dixanackmad** [comment]
confirmed on bld0855

**Comment by Rushor** [comment]
include the full link of the revision @dixanackmad

**Comment by tkrokli** [comment]
Looks like @dixanackmad made a typo when reading his core rev. hash and typing it manually. `1 != l`
Likely match: b1d0855624d1 (jackpoz committed 20 days ago, 2016-01-08, 23:13 CET).

BTW: this issue page is bugged, "This issue was closed." moves below the last comment.

**Comment by mik1893** [comment]
Closed in 588f0663cea3979ef418b123d2b5575553f608ae

**Comment by Jildor** [comment]
I think this is bugged now, please reopen.
Rev: 3d5c1b83b15cfc9f73888eb525c64323266c1fd4

I think caused by:
https://github.com/TrinityCore/TrinityCore/commit/6dc37a9add631888fe5fbcd43d19c2b07bed8a57
https://github.com/TrinityCore/TrinityCore/commit/858d45885b06bd899f69ca9727d54cda150c4398

**Comment by Keader** [comment]
Please open a new issue @Jildor

**Comment by Jildor** [comment]
#18428
Done ;)
