### ISSUE TITLE
Dragon Isles empty

### ISSUE THREAD

**Issue by EmissaryOfToddHoward** [TrinityCore/TrinityCore#29103]
### Description

as stated in the title no npcs are spawing in the dragon isles or atleast the dracythr starting area this is problematic when trying to complete the dracthyr starting questline

### Expected behaviour

all npcs and enemies that are normally spawned in are spawned in

### Steps to reproduce the problem

create a dracthyr

### Branch

master

### TC rev. hash/commit

Yet to be done but can be done if needed

### Operating system

Debian 10 x64 for the server and Win 10 for the client

### Custom changes

N/A

**Comment by Aokromes** [comment]
duplicate.
