### ISSUE TITLE
Precious Ogre Stash Exile's Reach

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29110]
### Description

SQL for Precious Ogre Stash. Cpp script to be added in future.

### SQL fix

```sql
-- Precious Ogre Stash full SQL
SET @OGUID := XXXXXXXX;

-- Spawn
DELETE FROM `gameobject` WHERE `guid`=@OGUID;
INSERT INTO `gameobject` (`guid`,`id`,`map`,`zoneId`,`areaId`,`spawnDifficulties`,`phaseUseFlags`,`PhaseId`,`PhaseGroup`,`terrainSwapMap`,`position_x`,`position_y`,`position_z`,`orientation`,`rotation0`,`rotation1`,`rotation2`,`rotation3`,`spawntimesecs`,`animprogress`,`state`,`ScriptName`,`VerifiedBuild`) VALUES
(@OGUID,327407,2175,10424,10530,0,0,0,0,-1,466.71008,-1932.5452,155.78102,5.5311203,0,0,-0.36723328,0.9301289,300,255,1,'',50000);

-- Addon data
DELETE FROM `gameobject_template_addon` WHERE `entry`=327407;
INSERT INTO `gameobject_template_addon` (`entry`,`faction`,`flags`,`mingold`,`maxgold`,`artkit0`,`artkit1`,`artkit2`,`artkit3`,`artkit4`,`WorldEffectID`,`AIAnimKitID`) VALUES
(327407,0,2113536,0,0,0,0,0,0,0,2437,0);

-- Tracker quest
DELETE FROM `quest_template` WHERE `ID` IN (56088);
INSERT INTO `quest_template` (`ID`,`QuestType`,`RewardXPMultiplier`,`RewardMoneyMultiplier`,`RewardArtifactXPMultiplier`,`Flags`,`LogTitle`) VALUES
(56088,2,1,1,1,1024, '[Hidden Tracker] Precious Ogre Stash Vignette');

-- Visibility condition
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=32 AND `SourceGroup`=8 AND `SourceEntry`=327407 AND `SourceId`=0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(32,8,327407,0,0,47,0,56088,64,0,1,0,0,'','Spawn of gameobject with entry 327407 requires Quest 56088 not rewarded');

-- Loot
SET @ID := 97513;
DELETE FROM `gameobject_loot_template` WHERE `Entry`=@ID;
INSERT INTO `gameobject_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(@ID,169821,0,100,0,1,0,1,1,'Precious Ogre Stash - Ogre Effigy'),
(@ID,54831,0,100,0,1,0,10,15,'Precious Ogre Stash - Shiny Pebble'),
(@ID,54833,0,100,0,1,0,7,9,'Precious Ogre Stash - Pretty Pebble'),
(@ID,56047,0,100,0,1,0,3,6,'Precious Ogre Stash - Strange Pebble'),
(@ID,56049,0,100,0,1,0,1,1,'Precious Ogre Stash - Mysterious Rock');
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1t 7 Feb 2023 (library: OpenSSL 1.1.1t 7 Feb 2023)
Using Boost version: 1.73.0
Using MySQL version: 80033
Using CMake version: 3.26.4
Compiled on: Windows 10.0.19045

**Comment by malcrom** [comment]
Why did you reopen these? I'm planning on submitting them all together with gameobject scritpts?

**Comment by Legoso** [comment]
I don't blame him. Only when reading your comment of today did I understand that you don't want the SQL to be committed on its own, but in a future PR.

**Comment by mdX7** [comment]
> Why did you reopen these? I'm planning on submitting them all together with gameobject scritpts?

As its valid, just that we need the vignette handling, which should be done by core, not scripts.
Also i kinda thought its just one of your regular outbreaks simply closing open stuff

**Comment by malcrom** [comment]
It needs gameobject scripts.

**Comment by mdX7** [comment]
> It needs gameobject scripts.

For? Completing the tracking quest is part of vignettes magic, as vignette id is referenced in Data29 for chests. Tracking quest is then referenced in Vignette.db2

**Comment by malcrom** [comment]
I need to add scripts for loot. I wasn't thinking about tracking

**Comment by mdX7** [comment]
> I need to add scripts for loot. I wasn't thinking about tracking

Then create the script, reference the related issues in `Issues addressed:` section or add a new section `Supercedes:` or something similar. Next time put create comment before closing so we know whats happening (as in new post, not in description), thanks!

**Comment by malcrom** [comment]
I need to do more research first. I know this one is phased and have to check the other 3

**Comment by malcrom** [comment]
Closing this again because I plan on getting proper phasing for all chest and doing a pr with c++ scripts. Also I am closing not deleting the code so no need to get snotty with me.
