### ISSUE TITLE
Changing 'end_time' in game_event leads to SQL Issue (1292): Incorrect datetime values

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [TrinityCore/TrinityCore#29116]
### Description

When changing the 'end_time' property in game_events it leads to SQL Issue 1292: Incorrect datetime values. 

### Expected behaviour

The values are set to end in year 2030, I wanted them to change so that they last till 2090. 

I tried:

UPDATE game_event SET end_time = "2090-12-31 07:00:00" WHERE end_time="2030-12-31 07:00:00"

### Steps to reproduce the problem

1. Run SQL Statement: 
UPDATE game_event SET end_time = "2090-12-31 07:00:00" WHERE end_time="2030-12-31 07:00:00"

2. See Error 

### Branch

3.3.5

### TC rev. hash/commit

dont know, latest.

### Operating system

Server: Windows 10, Client: Ubuntu 20.04

### Custom changes

None

**Comment by jackpoz** [comment]
may I suggest https://en.wikipedia.org/wiki/Year_2038_problem ?

**Comment by Aokromes** [comment]
mysql limitation, you can set max early 2038
