### ISSUE TITLE
ICC - Sindragosa should not be flying during the ground phase, spreading its wings

### ISSUE THREAD

**Issue by qq462518439** [TrinityCore/TrinityCore#29121]
### Description

When you engage in a battle with Sindragosa, if the boss is in the ground phase and still attacking you in a flying state.
The lower body is underground, which looks strange
![QQ截图20230704151326](https://github.com/TrinityCore/TrinityCore/assets/91646500/781e16de-775b-446a-99d0-576f84478dc3)

### Expected behaviour

Sindragosa should not be flying during the ground phase, spreading its wings

### Steps to reproduce the problem

1. Start meeting Sindragosa and wait for it to land
2. Move your cartoon characters appropriately after starting the battle
3. Meet again and watch

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/96f2a97e109befe6d8612e6e8ddc6e68a8bd1dd3

### Operating system

Windows 10 x64

### Custom changes

npcBots
Eluna

**Comment by Krutok** [comment]
But this is not the original model of Sindragosa: https://wow.zamimg.com/uploads/screenshots/normal/170272-sindragosa.jpg

**Comment by Shauren** [comment]
It is in chinese client (they dont have bones)

**Comment by Krutok** [comment]
ahh ok

**Comment by qq462518439** [comment]
![QQ截图20230712124138](https://github.com/TrinityCore/TrinityCore/assets/91646500/e01faab2-1688-48f5-ae9f-21d2d16ff983)
I tested the same situation with the original client again, so it seems to have nothing to do with the model

**Comment by Ovahlord** [comment]
What flags_extra does Sindragosa have with .npc info?

**Comment by qq462518439** [comment]
@Ovahlord 
Flags Extra: 268435457

**Comment by PsychoJS** [comment]
any solution?

**Comment by qq462518439** [comment]
> any solution?
Do you have the same problem
Perhaps refer to the source code of azerothcore?But I don't know the code

**Comment by vahzxz** [comment]
I think this is a common problem. NPCs stupidly do not know how to keep the phase they are in, dragons also behave terribly. Any Dragon, if you drag it down and it descends to the ground, this problem manifests itself. It is required to implement a system that preserves the shape of the NPC when it touches the ground. I think these large-scale problems should be solved.

**Comment by CraftedRO** [comment]
Fix suggested by Ovahlord
```sql
-- Add CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE to Sindragosa
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|512 WHERE `entry`IN(36853,38265,38266,38267);
```

**Comment by CraftedRO** [comment]
btw can someone remember be how it's named flags_extra in sniffs ?
