### ISSUE TITLE
Long query execution time when resetting quests on big database

### ISSUE THREAD

**Issue by Macsimka** [TrinityCore/TrinityCore#29146]
### Description

\# Schema: characters  Last_errno: 1160  Killed: 1053
\# **Query_time: 27411.232274**  Lock_time: 0.000444  Rows_sent: 0  Rows_examined: 34891235512  Rows_affected: 0  Bytes_sent: 0
SET timestamp=1689158211;
DELETE cq, cqo FROM character_queststatus cq LEFT JOIN character_queststatus_objectives cqo ON cq.quest = cqo.quest WHERE cq.quest IN (32733,32944,32942,32732,32731,32730,32729,32728,32658,32653,32649,32647,32645,32642,32568,32567,32524,32523,32452,32451,32450,32449,32446,32433,32238,32237,32236,32223,32222,32221,32214,32199,32197,32186,32185,32184,32183,32182,32181,32174,32173,32172,32171,32170,32169,32168,32167,32166,32165,32164,32163,32162,32161,32159,32158,32157,32156,32155,32154,32153,32152,32151,32150,32149,32148,32147,32146,32142,32141,32140,32139,32138,32137,32136,32135,32134,32132,32131,32130,32129,32125,31763,31762,31761,31760,31759,31758,31757,31756,31755,31754,31297,31296,31295,31294,31293,31250,31249,31248,31247,31246,31245,31244,31243,31242,31240,31136,31131,30482,30481,30444,30385,30342,30341,30340,30339,30338,30320,30316,30314,30313,30312,30311,30310,30309,30308,30307,30306,30305,30304,30302,30301,30300,30299,30298,30297,30296,30294,30293,30292,30291,30290,30289,30288,30287,30286,30285,30284,30283,30282,30281,30280,30277,30266,30265,30264,30263,30261,30251,30250,30249,30248,30247,30246,30245,30244,30243,30242,30240,30239,30238,30237,30236,30235,30234,30233,30232,30231,30228,30227,30226,30225,30206,30205,30204,30200,30196,30195,30194,30193,30192,30191,30190,0);

Adding indexes to tables only partially solves the problem:
```
ALTER TABLE `character_queststatus_objectives`
  ADD  INDEX `QUESTIDX` (`quest`);

ALTER TABLE `character_queststatus`
  ADD  INDEX `QUESTIDX` (`quest`);
```

\# **Query_time: 92.128649**  Lock_time: 0.000146  Rows_sent: 0  Rows_examined: 41411195  Rows_affected: 68087  Bytes_sent: 14
SET timestamp=1689303692;
DELETE cq, cqo FROM character_queststatus cq LEFT JOIN character_queststatus_objectives cqo ON cq.quest = cqo.quest WHERE cq.quest IN (32733,32944,32942,32732,32731,32730,32729,32728,32658,32653,32649,32647,32645,32642,32568,32567,32524,32523,32452,32451,32450,32449,32446,32433,32238,32237,32236,32223,32222,32221,32214,32199,32197,32186,32185,32184,32183,32182,32181,32174,32173,32172,32171,32170,32169,32168,32167,32166,32165,32164,32163,32162,32161,32159,32158,32157,32156,32155,32154,32153,32152,32151,32150,32149,32148,32147,32146,32142,32141,32140,32139,32138,32137,32136,32135,32134,32132,32131,32130,32129,32125,31763,31762,31761,31760,31759,31758,31757,31756,31755,31754,31297,31296,31295,31294,31293,31250,31249,31248,31247,31246,31245,31244,31243,31242,31240,31136,31131,30482,30481,30444,30385,30342,30341,30340,30339,30338,30320,30316,30314,30313,30312,30311,30310,30309,30308,30307,30306,30305,30304,30302,30301,30300,30299,30298,30297,30296,30294,30293,30292,30291,30290,30289,30288,30287,30286,30285,30284,30283,30282,30281,30280,30277,30266,30265,30264,30263,30261,30251,30250,30249,30248,30247,30246,30245,30244,30243,30242,30240,30239,30238,30237,30236,30235,30234,30233,30232,30231,30228,30227,30226,30225,30206,30205,30204,30200,30196,30195,30194,30193,30192,30191,30190,0);

### Expected behaviour

We need to find another solution.

### Steps to reproduce the problem

-

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/0cb8965de22c5da3887b8f8b5c08b9f5034b3cc6

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by shamage** [comment]
Maybe I'm wrong, but I think the problem is probably a typo of this value - "zero" in both cases - maybe I'm wrong
![Ashampoo_Snap_piatok 14  júla 2023_12h44m19s](https://github.com/TrinityCore/TrinityCore/assets/7515044/81311ced-50d1-4f7c-8d12-acc669b25768)

**Comment by Macsimka** [comment]
The problem is definitely not that. By the way, we can try to make 2 queries instead of one to avoid "join". Will try tomorrow.

**Comment by jackpoz** [comment]
Isn't the improvement from 27411 to 92 seconds good enough as a start ?

**Comment by Ovahlord** [comment]
Does the table have a primary key? Usually the result of slow performance like that is the abscence of missing primary keys (which are indexes)

**Comment by Lordron** [comment]
> Does the table have a primary key? Usually the result of slow performance like that is the abscence of missing primary keys (which are indexes)

quest

**Comment by Macsimka** [comment]
The problem was solved by adding indexes. Now the query is executed in less than 3 seconds (long_query_time = 3 in MySQL config). Apparently, old records of daily quests have been cleared, and it became significantly faster. I think we should also add indexes in the TC.

**Comment by jackpoz** [comment]
are these the indexes you added or anything more ?
```sql
ALTER TABLE `character_queststatus_objectives`
  ADD  INDEX `QUESTIDX` (`quest`);

ALTER TABLE `character_queststatus`
  ADD  INDEX `QUESTIDX` (`quest`);
```

**Comment by Macsimka** [comment]
> are these the indexes you added or anything more ?
> 
> ```sql
> ALTER TABLE `character_queststatus_objectives`
>   ADD  INDEX `QUESTIDX` (`quest`);
> 
> ALTER TABLE `character_queststatus`
>   ADD  INDEX `QUESTIDX` (`quest`);
> ```

this all.
