### ISSUE TITLE
Warlock pet skill Word of Mass Recall (OLD) causes server crash.

### ISSUE THREAD

**Issue by Greyisttot** [TrinityCore/TrinityCore#29149]
### Description

https://gist.github.com/Greyisttot/d1f5601ff7c96d78b9462276a9cb1913

### Expected behaviour

None

### Steps to reproduce the problem

Create Warlock character Summon Imp to cast this skill https://www.wowhead.com/spell=3/word-of-mass-recall-old

### Branch

master

### TC rev. hash/commit

Revision: TrinityCore rev. 6be536a73bc8 2023-07-15 00:45:16 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 x64 22H2

### Custom changes

None

**Comment by ImmortalusDev** [comment]
RangeEntry is nullptr

**Comment by Greyisttot** [comment]
INSERT INTO `disables` VALUES (0, 688, 1, '', '', '');

**Comment by Ovahlord** [comment]
Hackfix. You have to find out why the imp wants to cast the spell in the first place becasue it's a dev spell.

**Comment by ImmortalusDev** [comment]
It's just placed in his spell bar, when you change his react state and click on that spell, server will crash, because Rangeentry was nullptr

**Comment by Nyr97** [comment]
what's funny here is how did that spell end up in the imp's spellbar

**Comment by ImmortalusDev** [comment]
> what's funny here is how did that spell end up in the imp's spellbar

Bad value pass or read?
