### ISSUE TITLE
Getting error after update the to the build 50438

### ISSUE THREAD

**Issue by marcelino056** [TrinityCore/TrinityCore#29154]
### Description

when i try click on the realm and try to connecto to the server i'm getting this error
![Screenshot 2023-07-16 093135](https://github.com/TrinityCore/TrinityCore/assets/4961741/1472e206-f71b-40d3-98b6-587353c40bdf)

But the console indicate something different
![Screenshot 2023-07-16 093414](https://github.com/TrinityCore/TrinityCore/assets/4961741/b4c62ac8-0134-4383-9e0f-5030e32e1787)

Don't know what to do.

### Expected behaviour

Access to the server and create the first character

### Steps to reproduce the problem

1. Download the client from blizzard build 50438 (07/12/2023)
2. Setup the project normally as the wiki indicate, no errors.
3. Start the server for first time.
4. Login
5. Pick the realm

### Branch

master

### TC rev. hash/commit

![Screenshot 2023-07-16 093414](https://github.com/TrinityCore/TrinityCore/assets/4961741/b0ed6481-a5fb-4e68-a0c5-f2c3f0003ffe)

### Operating system

Windows 11

### Custom changes

None

**Comment by Aokromes** [comment]
not server issue.

**Comment by marcelino056** [comment]
Can you point me in the right direction? is not a memory issue, the server already have 16 gb and 150gb for storage free. and the error on the console and the error on the window is not corresponding.

**Comment by Fabi** [comment]
> Can you point me in the right direction? is not a memory issue, the server already have 16 gb and 150gb for storage free. and the error on the console and the error on the window is not corresponding.

update your core. its 1 month old
