### ISSUE TITLE
bnetserver cannot login via public network, but server works on local ip, like 192.168.1.3

### ISSUE THREAD

**Issue by leapyear1969** [TrinityCore/TrinityCore#29150]
### Description

hello,  i'm new to TC, and trying to built my own public server and share with my friends. i can play the game on local network, but cannot share it to public.

Good sample:
- set ``LoginREST.ExternalAddress=local IP(192.168.3.12)`` in the ``bnetserver.conf`` , it works as expected.

Bad sample:
- set ``LoginREST.ExternalAddress=Public IP(22.33.55.66, actually i set an domain to it)`` in the ``bnetserver.conf`` , updated the ``realmlist`` address as well.  when trying to login from external network it shows below error:
your connection is abord
![image](https://github.com/TrinityCore/TrinityCore/assets/18607988/13c486c9-aaa9-4801-b2d5-444659afb487)

i know it is a network issue, i checked the wireshark log, it looks like the connection was reset by server port 1119,
![image](https://github.com/TrinityCore/TrinityCore/assets/18607988/470affe9-051b-44a0-9311-edde6d7d0420)

i've forward server's 1119 port to public, and it tested good via telnet myPublicIP 1119.

even i changed the 1119 port to 1120, still no luck.

i found when login from local ip, it shows no port 1119 in the log, that's very strange. 

please give me some advices, thanks~ 

### Expected behaviour

should be able to access the game from public web

### Steps to reproduce the problem

when make -j and make install, see below error:
```js
wow@wow:/TrinityCore/build$ make install
[  3%] Built target g3dlib
[  3%] Built target Detour
[  4%] Built target Recast
[  4%] Built target fmt
[  4%] Built target sfmt
[  7%] Built target jemalloc
[  7%] Built target argon2
[  7%] Built target openssl_ed25519
[  7%] Built target gsoap
[ 10%] Built target protobuf
[ 12%] Built target casc
[ 12%] Built target revision_data.h
[ 16%] Built target common
[ 18%] Built target database
[ 23%] Built target proto
[ 23%] Built target shared
[ 23%] Linking CXX executable bnetserver
/usr/bin/ld: CMakeFiles/bnetserver.dir/Main.cpp.o: in function `main':
/home/wow/TrinityCore/src/server/bnetserver/Main.cpp:196: undefined reference to `Trinity::Net::ScanLocalNetworks()'
/usr/bin/ld: CMakeFiles/bnetserver.dir/REST/LoginRESTService.cpp.o: in function `LoginRESTService::GetEndpointForClient(boost::asio::ip::address const&) const':
/home/wow/TrinityCore/src/server/bnetserver/REST/LoginRESTService.cpp:142: undefined reference to `Trinity::Net::SelectAddressForClient(boost::asio::ip::address const&, std::span<boost::asio::ip::address, 18446744073709551615ul> const&)'
/usr/bin/ld: CMakeFiles/bnetserver.dir/REST/LoginRESTService.cpp.o: in function `LoginRESTService::GetHostnameForClient[abi:cxx11](boost::asio::ip::address const&) const':
/home/wow/TrinityCore/src/server/bnetserver/REST/LoginRESTService.cpp:164: undefined reference to `Trinity::Net::SelectAddressForClient(boost::asio::ip::address const&, std::span<boost::asio::ip::address, 18446744073709551615ul> const&)'
/usr/bin/ld: ../shared/libshared.a(Realm.cpp.o): in function `Realm::GetAddressForClient(boost::asio::ip::address const&) const':
/home/wow/TrinityCore/src/server/shared/Realm/Realm.cpp:35: undefined reference to `Trinity::Net::SelectAddressForClient(boost::asio::ip::address const&, std::span<boost::asio::ip::address, 18446744073709551615ul> const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/bnetserver/CMakeFiles/bnetserver.dir/build.make:299: src/server/bnetserver/bnetserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1291: src/server/bnetserver/CMakeFiles/bnetserver.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
wow@wow:~/TrinityCore/build$ 
```
### Branch

master

### TC rev. hash/commit

TrinityCore rev. 973224f7097a 2023-07-14 08:35:02 +0000 (master branch) (Unix, RelWithDebInfo, Static) (bnetserver)
<Ctrl-C> to stop.
 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/
Using configuration file /home/majun/server/etc/bnetserver.conf.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Automatic database updates are disabled for all databases!
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.5.19
MySQL server ver: 10.5.19-MariaDB-0+deb11u2 
Connected to MySQL database at 127.0.0.1
MySQL client library: 10.5.19
MySQL server ver: 10.5.19-MariaDB-0+deb11u2 
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Loading IP Location Database...
Login service bound to http://0.0.0.0:8081
Added realm "myServerName" at publicDomian:8085.

### Operating system

debian 11

### Custom changes

none

**Comment by Shauren** [comment]
First you have to update to 6be536a73bc8a6e331ce20e7d19e2ea56b99b4d0

Second, you must swap the dev-only certificate shipped with TC with a real trusted certificate for your domain

**Comment by MaDmaX1337** [comment]
After setting the crt and the prvt key it showing incorrect login details. How to fix that?

**Comment by leapyear1969** [comment]
> and the prvt key it showing incorrect login details. How to fix that?

i think you may create a new issue to track it with more details.

**Comment by leapyear1969** [comment]
> First you have to update to [6be536a](https://github.com/TrinityCore/TrinityCore/commit/6be536a73bc8a6e331ce20e7d19e2ea56b99b4d0)
> 
> Second, you must swap the dev-only certificate shipped with TC with a real trusted certificate for your domain
> 
> as for that build error, run cmake again

You saved my day !!! thanks so much, cheers~ 👍
