### ISSUE TITLE
weird gossip menu, when multiple quests are avaiable:

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29161]
### Description

weird gossip menue, when multiple quests are avaiable:
![Picture](https://github.com/TrinityCore/TrinityCore/assets/132657906/07d0a72c-26bf-4160-8093-e5809fbe66da)

![Pictr](https://github.com/TrinityCore/TrinityCore/assets/132657906/d4576ed7-8ce8-439b-9e77-e28136e98562)

the quests are unable to click.

enUS dbc files and client used

### Expected behaviour

Available quests are shown and clickable

### Steps to reproduce the problem

go to any questgiver which gives you more than one quests.

### Branch

master

### TC rev. hash/commit

5be076b2400364c5fc2b293032ad92f1d955ec1f

### Operating system

Windows Server 2022

### Custom changes

custom npc spawns/ core is untouched

**Comment by mdX7** [comment]
#28016
