### ISSUE TITLE
Worldserver Crash when spawn Vehicle NPC

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29166]
### Description

Worldserver crash when spawn vehicle
Example:

.npc add 28710

<img width="446" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/805a27b3-2c6d-4aca-81a0-5983443b4b65">

### Expected behaviour

should not crash

### Steps to reproduce the problem

Login to world and-> .npc add 28710

### Branch

master

### TC rev. hash/commit

19db88fd1b1dd3ee9432f9f5facda0129f470a2c

### Operating system

Windows Server 2022

### Custom changes

some spawns but untouched core

[unknown_worldserver.exe_[19-7_22-30-6].txt](https://github.com/TrinityCore/TrinityCore/files/12102231/unknown_worldserver.exe_.19-7_22-30-6.txt)

**Comment by Ovahlord** [comment]
Add a crashlog please

**Comment by coreretail6** [comment]
Crashlog is there

**Comment by Ovahlord** [comment]
Please reproduce the crash with a debug build and post that crash log then. Release doesn't really contain useful crashlog infos

**Comment by shamage** [comment]
TrinityCore rev. 6a760de79b6d 2023-07-20 20:17:38 +0200 (master branch)  

Crashlog :  https://gist.github.com/shamage/f56edf8f01aba9a0a32ab37ced0d288c
