### ISSUE TITLE
worldserver crash when teleport to Northrend in various ways

### ISSUE THREAD

**Issue by leapyear1969** [TrinityCore/TrinityCore#29167]
### Description

When I try to teleport to Northrend, whether it's an airship, or a portal, or the .go xyz command, the worldserver crashes.
![image](https://github.com/TrinityCore/TrinityCore/assets/18607988/1e7b72d6-b5fc-47b7-b69d-8e075444f0df)

### Expected behaviour

should be able to land on Northrend map

### Steps to reproduce the problem

1. go to portals in orgrimmar
2. click the portal to Dalaran, then worldserver crash.
![image](https://github.com/TrinityCore/TrinityCore/assets/18607988/8afd490e-f5ec-4444-a021-9289657ac37b)

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 8b426af763a9 2023-07-20 00:38:07 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

debian 11

### Custom changes

None

**Comment by mdX7** [comment]
#29131
