### ISSUE TITLE
{quest}Fragmented Magic

### ISSUE THREAD

**Issue by Justiciar** [TrinityCore/TrinityCore#2917]
Dear Sir or Madam,
I have encountered a problem while trying to do "Fragmented Magic" quest.
The problem is that when I cast the Polymorth spell on the required npc, he turned into different animal, but it didn't split the npc  to clones, so I couldn't complete the quest because the objective was to kill the clones which should be appeared after I used the polymorph spell.
It took to the npc to change back to his primal form after few dozens of seconds.
If the quest would have worked properly, the npc would have turned into several smaller clones, that didn't happened.
I hope my report was understandable.
Sincerely yours,
                            Justiciar.

Hash:e3f4cca534752851775f5174901fb8a43460cdbb

DB: 335.11.41+

Addons: wg/pvpranks/ahbot/trinichat2/antcheat1

wowhead quest link: http://www.wowhead.com/quest=9364/fragmented-magic

wowhead related npcs link: http://www.wowhead.com/search?q=+Spitelash+

wowhead quest item link:  http://www.wowhead.com/item=23250#dropped-by

wowhead spell link: http://www.wowhead.com/spell=28272/polymorph

Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

**Comment by danlapps** [comment]
Is this still an issue after 3 years without comments or has it been fixed ?

**Comment by Rushor** [comment]
well no:
npc_spitelashes -- this script works fine, if you polymorph the npcs, the nppc despawns and some tiny sheeps will appear which can be killed, and then you will get the killcredit.

Note: https://github.com/TrinityCore/TrinityCore/issues/1678 the script is there replaced with SAI

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/zone_azshara.cpp#L54
