### ISSUE TITLE
Group Loot Syste,

### ISSUE THREAD

**Issue by liosbel2000** [TrinityCore/TrinityCore#29181]
### Description

I got a problem here, i dont speak english so i will try to explai this using all. 
I got a party into a dungeon, they kill a boss and normaly this items must can be tradeable with others members. Buttttt this its not working thath way. Just they soulbind and nothing else.  Can someone help me i dont even know what part of code control this. I will repair but i dont understund WHERE need repair. 

### Expected behaviour

I got a problem here, i dont speak english so i will try to explai this using all. 
I got a party into a dungeon, they kill a boss and normaly this items must can be tradeable with others members. Buttttt this its not working thath way. Just they soulbind and nothing else.  Can someone help me i dont even know what part of code control this. I will repair but i dont understund WHERE need repair. 

### Steps to reproduce the problem

I got a problem here, i dont speak english so i will try to explai this using all. 
I got a party into a dungeon, they kill a boss and normaly this items must can be tradeable with others members. Buttttt this its not working thath way. Just they soulbind and nothing else.  Can someone help me i dont even know what part of code control this. I will repair but i dont understund WHERE need repair. 

### Branch

3.3.5

### TC rev. hash/commit

I got a problem here, i dont speak english so i will try to explai this using all. 
I got a party into a dungeon, they kill a boss and normaly this items must can be tradeable with others members. Buttttt this its not working thath way. Just they soulbind and nothing else.  Can someone help me i dont even know what part of code control this. I will repair but i dont understund WHERE need repair. 

### Operating system

Windoes

### Custom changes

Using patch 4.3.4

**Comment by Aokromes** [comment]
you use 3.3.5a or 4.3.4?

**Comment by CraftedRO** [comment]
I guess this can be closed.
