### ISSUE TITLE
Server crashes while trying to load db2.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/TrinityCore#29190]
### Description

Server crashes while trying to load db2, showing the following in server.log:

Loading Trinity strings...
Loaded 1042 trinity strings in 38 ms
Initialize data stores...
File ./dbc/enUS/ArmorLocation.db2 does not exist
File ./dbc/enUS/ArtifactCategory.db2 does not exist
File ./dbc/enUS/ArtifactPowerPicker.db2 does not exist
File ./dbc/enUS/ArtifactTier.db2 does not exist
File ./dbc/enUS/AuctionHouse.db2 does not exist
File ./dbc/enUS/AzeriteItem.db2 does not exist
File ./dbc/enUS/AzeriteItemMilestonePower.db2 does not exist
File ./dbc/enUS/AzeriteTierUnlockSet.db2 does not exist
File ./dbc/enUS/BankBagSlotPrices.db2 does not exist
File ./dbc/enUS/BattlePetBreedQuality.db2 does not exist
File ./dbc/enUS/BattlePetBreedState.db2 does not exist
File ./dbc/enUS/ChrClassUIDisplay.db2 does not exist
File ./dbc/enUS/CreatureType.db2 does not exist
File ./dbc/enUS/GameObjectArtKit.db2 does not exist
File ./dbc/enUS/GarrPlotInstance.db2 does not exist
File ./dbc/enUS/ItemBagFamily.db2 does not exist
File ./dbc/enUS/ItemContextPickerEntry.db2 does not exist
File ./dbc/enUS/ItemLevelSelectorQuality.db2 does not exist
File ./dbc/enUS/ItemLimitCategoryCondition.db2 does not exist
File ./dbc/enUS/JournalTier.db2 does not exist
File ./dbc/enUS/Languages.db2 does not exist
File ./dbc/enUS/MythicPlusSeason.db2 does not exist
File ./dbc/enUS/NumTalentsAtLevel.db2 does not exist
File ./dbc/enUS/ParagonReputation.db2 does not exist
File ./dbc/enUS/PrestigeLevelInfo.db2 does not exist
File ./dbc/enUS/PvpSeason.db2 does not exist
File ./dbc/enUS/PvpTalentCategory.db2 does not exist
File ./dbc/enUS/PvpTalentSlotUnlock.db2 does not exist
File ./dbc/enUS/QuestFactionReward.db2 does not exist
File ./dbc/enUS/RewardPackXCurrencyType.db2 does not exist
File ./dbc/enUS/RewardPackXItem.db2 does not exist
File ./dbc/enUS/SkillLineXTraitTree.db2 does not exist
File ./dbc/enUS/TotemCategory.db2 does not exist
File ./dbc/enUS/TraitTree.db2 does not exist
File ./dbc/enUS/TransmogHoliday.db2 does not exist
File ./dbc/enUS/TransmogIllusion.db2 does not exist
Unable to load db2 files for enUS locale specified in DBC.Locale config!

### Expected behaviour

You should not ask for db2 that are not generated by mapextractor.exe

### Steps to reproduce the problem

1. Run worldserver.exe

### Branch

master

### TC rev. hash/commit

TrinityCore rev. e0d474e69dc6 2023-07-28 01:21:15 +0200 (master branch) (Win64, Release, Static)

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by coreretail6** [comment]
your db2 files are missing or not on the right place
