### ISSUE TITLE
Unable to learn Riding/Fly Spell

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29191]
### Description

Since the 10.1.5 Commit, the Char is unable to learn riding/flyability by Teacher/Master

### Expected behaviour

Click on Riding Master/Teacher "Learn Spell" and learn the ability/ Or automatic learn Fly/Riding Spell on the right level

### Steps to reproduce the problem

Create a char and .level 50
go to a Riding Master/Teacher and try to learn one of the riding spells

### Branch

master

### TC rev. hash/commit

e0d474e69dc6a0f84845d7e551d74b7f561bc553

### Operating system

Windows Server 2022

### Custom changes

some additional spawns.

**Comment by MaDmaX1337** [comment]
I do not know if it helps. But actually at the retail version you will learn the riding skills automatically after you reach the necessery level, i have been told. Could be the reason it doesn't work.

**Comment by HenryZhangSG** [comment]
You can try the following, maybe it can solve the problem.

.setskill 762 225 225
.additem 49177
.additem 185965
.additem 110672
.additem 129139

**Comment by xXBentRealityXx** [comment]
.setskill 762 375 375

for a temp fix you can make a custom playerscript to learn the riding spells and set the skill

**Comment by coreretail6** [comment]
I Fixed it temporary with SQL Trigger on Characters DB:

DELIMITER $$

USE `characters`$$

DROP TRIGGER /*!50032 IF EXISTS */ `Riding 20`$$

CREATE
    /*!50017 DEFINER = 'root'@'localhost' */
    TRIGGER `Riding 20` AFTER UPDATE ON `characters` 
    FOR EACH ROW BEGIN

  IF NEW.`level` = 20 AND NOT EXISTS (SELECT * FROM `character_skills` WHERE `guid` = NEW.`guid` AND `skill` = 762 AND `value`=150 ) THEN

   UPDATE `character_skills` SET `value`=150  WHERE `guid`=NEW.`guid` AND `skill`=762;
   UPDATE `character_skills` SET `max`=150  WHERE `guid`=NEW.`guid` AND `skill`=762;
   
  END IF;

END;
$$

DELIMITER ;

DELIMITER $$

USE `characters`$$

DROP TRIGGER /*!50032 IF EXISTS */ `Riding 30`$$

CREATE
    /*!50017 DEFINER = 'root'@'localhost' */
    TRIGGER `Riding 30` AFTER UPDATE ON `characters` 
    FOR EACH ROW BEGIN

  IF NEW.`level` = 30 AND NOT EXISTS (SELECT * FROM `character_skills` WHERE `guid` = NEW.`guid` AND `skill` = 762 AND `value`=225 ) THEN

   UPDATE `character_skills` SET `value`=225  WHERE `guid`=NEW.`guid` AND `skill`=762;
   UPDATE `character_skills` SET `max`=225  WHERE `guid`=NEW.`guid` AND `skill`=762;
   
  END IF;

END;
$$

DELIMITER ;

DELIMITER $$

USE `characters`$$

DROP TRIGGER /*!50032 IF EXISTS */ `Riding 40`$$

CREATE
    /*!50017 DEFINER = 'root'@'localhost' */
    TRIGGER `Riding 40` AFTER UPDATE ON `characters` 
    FOR EACH ROW BEGIN

  IF NEW.`level` = 40 AND NOT EXISTS (SELECT * FROM `character_skills` WHERE `guid` = NEW.`guid` AND `skill` = 762 AND `value`=375 ) THEN

   UPDATE `character_skills` SET `value`=375  WHERE `guid`=NEW.`guid` AND `skill`=762;
   UPDATE `character_skills` SET `max`=375  WHERE `guid`=NEW.`guid` AND `skill`=762;
   
  END IF;

END;
$$

DELIMITER ;

**Comment by Naddley** [comment]
ae1dd8c & 68b6d81
