### ISSUE TITLE
DB/Quest: adjust minimum reputation value required for quests of The Ashen Verdict rings (Friendly)

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#29216]
### Description

https://aowow.trinitycore.info/?quest=24819
https://aowow.trinitycore.info/?quest=24820
https://aowow.trinitycore.info/?quest=24821
https://aowow.trinitycore.info/?quest=24822
https://aowow.trinitycore.info/?quest=25247

those quests should be able to be completed by being friendly with The Ashen Verdict (3000 rep value): https://www.youtube.com/watch?v=F8Jly8CYOeM
Currently they are at 6000, which means half the bar between friendly and honored:
```sql
SELECT `ID`,`RequiredMinRepFaction`,`RequiredMinRepValue` FROM `quest_template_addon` WHERE `ID` IN (25247,24822,24821,24820,24819);

    ID  RequiredMinRepFaction  RequiredMinRepValue  
------  ---------------------  ---------------------
 24819                   1156                   6000
 24820                   1156                   6000
 24821                   1156                   6000
 24822                   1156                   6000
 25247                   1156                   6000
```

### SQL fix

```sql
--
UPDATE `quest_template_addon` SET `RequiredMinRepValue`=3000 WHERE `ID` IN (25247,24822,24821,24820,24819);
```

### Branch

3.3.5

### TC rev. hash/commit

f9033a5dbd559fde3030a21d83d664983d95f39f

**Comment by CraftedRO** [comment]
this looks valid https://user-images.githubusercontent.com/24550914/53701410-3ebb6700-3dfd-11e9-90e4-f4cb10fbffcc.png
