### ISSUE TITLE
DB/Quest 9489  Cleansing the Scar not working

### ISSUE THREAD

**Issue by skelUA** [TrinityCore/TrinityCore#29219]
### Description

You should cast Power Word: Fortitude on 6 Eversong Rangers in the Dead Scar. If you cast the spell on them they don't get counted so the quest is uncompletable.

Quest-Info: https://www.wowhead.com/wotlk/quest=9489/cleansing-the-scar
https://aowow.trinitycore.info/?quest=9489 
Not working . Cant cast on NPC
TDB 335.23061
TrinityCore rev. f9033a5dbd55 2023-07-19

### Expected behaviour

When you cast on https://aowow.trinitycore.info/?npc=15938 it applied on npc and got point

### Steps to reproduce the problem

Try to cast on NPC https://aowow.trinitycore.info/?npc=15938

### Branch

3.3.5

### TC rev. hash/commit

TDB 335.23061
TrinityCore rev. f9033a5dbd55 2023-07-19

### Operating system

debian

### Custom changes

-

**Comment by CraftedRO** [comment]
this will fix the quest, but value is not sniffed, only based on other similar fix https://github.com/TrinityCore/TrinityCore/commit/222a0ba8ee68c83c8063f1b5eb4287a2c3a515cd
```sql
-- Fix
UPDATE `creature_template_addon` SET `PvPFlags`=17 WHERE `entry`=15938;
```

**Comment by CraftedRO** [comment]
anyway npc buffs does nothing to creature stats and when creature evade or reset from combat the buff is gone and this is sad.

**Comment by CraftedRO** [comment]
```sql
-- Fix quest Cleansing the Scar by updating Eversong Ranger PvpFlags with retail 10.2.5.53262 build: V10_2_5_53262 sniffed value.
UPDATE `creature_template_addon` SET `PvpFlags`=1 WHERE `entry`=15938; -- 15938 (Eversong Ranger)
```

this can be also merged too, I just sniffed and tested them

https://github.com/TrinityCore/TrinityCore/assets/24683355/3b65cc03-c807-47c0-8060-088e7771596e

**Comment by CraftedRO** [comment]
![WoWScrnShot_021624_015206](https://github.com/TrinityCore/TrinityCore/assets/24683355/10136a28-6d01-4134-9235-9c32dce82b70)
