### ISSUE TITLE
Incompatible Realms

### ISSUE THREAD

**Issue by SpazzyMcSpaz** [TrinityCore/TrinityCore#29210]
### Description

I have compiled the latest build and have the client for it. Both my auth.realmlist and client show 50622 as build number but when I log on I get a red incompatible realm. Can someone please help me?

### Expected behaviour

The realmlist should be green and compatible.

### Steps to reproduce the problem

1. Build latest build.
2. Run latest client

### Branch

master

### TC rev. hash/commit

RelWithDebInfo

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by mdX7** [comment]
latest build is 50622 not 50662

**Comment by SpazzyMcSpaz** [comment]
> latest build is 50622 not 50662

That is what I meant sorry. I edited it to show 50622 now

**Comment by mdX7** [comment]
re-check auth.realmlist build field and the client you are using. Restart servers if you did changes and retry. Cannot reproduce with 8594fcfe8a0085a087bce510e3b4cb14f632434f

**Comment by SpazzyMcSpaz** [comment]
I have tried that both my client and auth.realmlist show the same build. I have built before and never got this issue. I don't know what to do.

**Comment by Elnir** [comment]
Same here. I tried to change the build in the realmlist, but it's stuck on "logging" on the server.

**Comment by Faq** [comment]
cache problem?

**Comment by SpazzyMcSpaz** [comment]
> cache problem?

I tried deleting cache and still get the same error.

**Comment by Shauren** [comment]
Obligatory "are you using heidisql and editing/viewing default table value instead of data?" question

**Comment by SpazzyMcSpaz** [comment]
> Obligatory "are you using heidisql and editing/viewing default table value instead of data?" question

I am using MySQL workbench and am looking at the table value.

**Comment by Elnir** [comment]
> Obligatory "are you using heidisql and editing/viewing default table value instead of data?" question

Maybe... I'm a newcomer, so I just edited it without any extra actions.

**Comment by Elnir** [comment]
Rebooting computer helped!

**Comment by SpazzyMcSpaz** [comment]
> Rebooting computer helped!

I have tried that and it still shows incompatible.
