### ISSUE TITLE
CORE/PETAI - Crash caused by warlock pet behavior

### ISSUE THREAD

**Issue by KamiliaBlow** [TrinityCore/TrinityCore#29233]
### Description

If either a spell is used or an attack is assigned to a pet, the server crashes

### Expected behaviour

When attacking a target, the pet also attacks the target and does not crash the server.

### Steps to reproduce the problem

1. Create a warlock
2. try to summon any warlock pet
3. attack any target manually or with a spell.
4. server crashes

### Branch

master

### TC rev. hash/commit

0c9e46629c5503b8c1a81cb71b2cd06ec1284fbb

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by KamiliaBlow** [comment]
[5b353d03d9d0+_worldserver.exe_[14-8_18-35-52].txt](https://github.com/TrinityCore/TrinityCore/files/12333537/5b353d03d9d0%2B_worldserver.exe_.14-8_18-35-52.txt)

**Comment by jackpoz** [comment]
Do you have custom changes ?

**Comment by acidmanifesto** [comment]
> [5b353d03d9d0+_worldserver.exe_[14-8_18-35-52].txt](https://github.com/TrinityCore/TrinityCore/files/12333537/5b353d03d9d0%2B_worldserver.exe_.14-8_18-35-52.txt)
> 

Your reported revision and crash log's revisions are not the same and are both completely different.
