### ISSUE TITLE
fatal  error C1083: Cannot open include file: 'pthread.h': No such file or directory

### ISSUE THREAD

**Issue by stefan4444333** [TrinityCore/TrinityCore#29257]
### Description

Hello, i have followed every step in windows requirements for trinitycore installation step by step and have installed every version of it by the book, but when i get to cmake and configuring, i get an error message.

### Expected behaviour

It should configure without an error message

### Steps to reproduce the problem

Configure by following the steps in trinitycore compilation

### Branch

3.3.5

### TC rev. hash/commit

latest

### Operating system

Windows 11

### Custom changes

Added Nemesis-anticheat and elunatrinitywoltk, but i dont think that is a problem

**Comment by Aokromes** [comment]
3.3.5a compiles fine, if you have a problem, you must have something missing or incorrect.

**Comment by stefan4444333** [comment]
yeah, thats the problem, i have something missing and i dont know what it is, thats why i have added it in the title.

**Comment by acidmanifesto** [comment]
> yeah, thats the problem, i have something missing and i dont know what it is, thats why i have added it in the title, since it doesn't mention anything as this error in the installation guide

Delete your cmake cache and regenerate cmake

**Comment by stefan4444333** [comment]
The steps i have tried have been:
i have Installed Mysql 8.0.34 from the link provided
I have installed Visual studio 2022 from the link provided (But i can't seem to find these Windows 10 SDK (10.0.15063 and 10.0.16299)
I have installed git and git extension from the link provided 
I have installed boost 1_80_0 and also the version of CMake listed - 3.24.2
I have installed OpenSSL 1.1.1
I have deleted Cmake Cache over and over again everytime i make a change
I have reinstalled everything from the ground up twice while also following the instructions word by word (trust me i have read every word 1 by 1).
And still when i try to click "Configure" in Cmake i get "Error in configuration process, project files may be invalid" with this error C:\build1\CMakeFiles\CMakeTmp\src.c(1,10): fatal  error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\build1\CMakeFiles\CMakeTmp\cmTC_c5228.vcxproj]

**Comment by stefan4444333** [comment]
Full error in cmake:

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: C:/build1/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_c5228.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
  src.c
  Copyright (C) Microsoft Corporation.  All rights reserved.
  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CMAKE_HAVE_LIBC_PTHREAD /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c5228.dir\Debug\\" /Fd"cmTC_c5228.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue C:\build1\CMakeFiles\CMakeTmp\src.c
C:\build1\CMakeFiles\CMakeTmp\src.c(1,10): fatal  error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\build1\CMakeFiles\CMakeTmp\cmTC_c5228.vcxproj]


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: C:/build1/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_79a6e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
  CheckFunctionExists.c
  Copyright (C) Microsoft Corporation.  All rights reserved.
  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_79a6e.dir\Debug\\" /Fd"cmTC_79a6e.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.24\Modules\CheckFunctionExists.c"
LINK : fatal error LNK1104: cannot open file 'pthreads.lib' [C:\build1\CMakeFiles\CMakeTmp\cmTC_79a6e.vcxproj]



Determining if the function pthread_create exists in the pthread failed with the following output:
Change Dir: C:/build1/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_6ea75.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32822 for x64
  CheckFunctionExists.c
  Copyright (C) Microsoft Corporation.  All rights reserved.
  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D CHECK_FUNCTION_EXISTS=pthread_create /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_6ea75.dir\Debug\\" /Fd"cmTC_6ea75.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.24\Modules\CheckFunctionExists.c"
LINK : fatal error LNK1104: cannot open file 'pthread.lib' [C:\build1\CMakeFiles\CMakeTmp\cmTC_6ea75.vcxproj]

**Comment by stefan4444333** [comment]
please help

**Comment by Shauren** [comment]
Github issue tracker is not a support channel, we have discord for that
