### ISSUE TITLE
Certificate attached

### ISSUE THREAD

**Issue by ruzik** [TrinityCore/TrinityCore#29260]
### Description

After updating the server from version 10.1.0:50000 to version 10.1.5:50791 through the "pull origin" command, I updated the client through the official battlenet application. compiled core and pulled out the necessary data files from the client. At the same time, he left the old configuration files (but later updated them too). Custom client launcher (Arctium) to connect left the previous version (subsequently downloaded a fresh one from https://github.com/Arctium/WoW-Launcher ). When launching the game in the application Arctium displays this message "Server with host name 195.20.X.X does not have a trusted certificate attached. If you are the server owner be sure to generate one and replace the default bnet server certificate. One way to generate one is through Let's Encrypt." I deleted the existing files in the folder "bnetserver.cert.pem", "bnetserver.key.pem" and rechecked the path in the config file. Everything is correct and recompiled the server core. After all the repeated actions, the error still remained. What could be the problem and is it possible to change the requirements for these files on our own?

### Expected behaviour

Successful launch game

### Steps to reproduce the problem

Launch Arctium/WoW-Launcher

### Branch

master

### TC rev. hash/commit

[d01e7a0](https://github.com/TrinityCore/TrinityCore/commit/d01e7a0d2f9436aeeb7e6c195b6197998637be4c)

Commits on Aug 20, 2023

### Operating system

Win 10.0.22000

### Custom changes

None

**Comment by Aokromes** [comment]
instalation or configuration issues doesn't belongs to bugtracker. use discord instead.
