### ISSUE TITLE
crash MMAP::MMapManager::GetNavMeshQuery

### ISSUE THREAD

**Issue by Idoitbetter** [TrinityCore/TrinityCore#29273]
### Description

https://gist.github.com/Idoitbetter/714fc65832a81497c658b71115de5ea7

It happens from time to time, I have also seen it in pit of saron with formations and in karazhan with waypoints

### Expected behaviour

Don't crash

### Steps to reproduce the problem

unknown

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f9033a5dbd559fde3030a21d83d664983d95f39f

### Operating system

Debian

### Custom changes

None

**Comment by CraftedRO** [comment]
maybe related https://github.com/TrinityCore/TrinityCore/commit/16f555f79ef2fdebd18204bc90383ad7761343a5
