### ISSUE TITLE
Amberseeds quest in Grizzly Hills is not available

### ISSUE THREAD

**Issue by tcoreja** [TrinityCore/TrinityCore#29279]
### Description

The quest should start by interacting with a bucket just inside the Amberpine Lodge. The object cannot be interacted with though. 

### Expected behaviour

The amberseed game object 188667 can be interacted with by the player to start quest 12225

### Steps to reproduce the problem

1. https://aowow.trinitycore.info/?quest=12225
2. teleport to Amberpine Lodge (map 571, x 3429 y -2778, z 202)
3. notice the amberseed bucket cannot be interacted with and no quest will start

### Branch

3.3.5

### TC rev. hash/commit

343d09bc95ade0cc34f953b56cbe666baca387fc

TC> server debug
TC> TrinityCore rev. 343d09bc95ad+ 2023-08-23 16:32:15 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80034
Using CMake version: 3.22.1
Compiled on: Linux 5.15.0-48-generic
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port %u
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/trinity/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/trinity/data/vmaps. Total size: 657797442 bytes
mmaps directory located in /opt/trinity/data/mmaps. Total size: 2102976212 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: TDB 335.23061
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Linux ubuntu 22.04 x64

### Custom changes

None

**Comment by ImmortalusDev** [comment]
master have same issue

**Comment by CraftedRO** [comment]
After some long-term research on this looks like someone added some required prequests here: https://github.com/TrinityCore/TrinityCore/blob/653abefd24642fe9ba042c09f4f133a3264b4917/sql/old/8.x/world/19071_2020_06_17/2020_04_14_01_world_2017_03_16_02_world.sql#L1

So fix looks like this:
 ```sql
-- Fix Amberseeds quest
 UPDATE `quest_template_addon` SET `NextQuestID`=0 WHERE  `ID` IN (12222, 12223); 
 ```
