### ISSUE TITLE
New creature spawns got npcflag/unitflags default 0 and not (NULL)

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29297]
### Description

Enter the world and use .npc add XXXX to spawns a new NPC. 
The entry in creature table got the npcflag/unitflags 0 and not (NULL)

### Expected behaviour

The entry in creature table got the npcflag/unitflags (NULL) and not 0

### Steps to reproduce the problem

Enter the world and use .npc add XXXX to spawns a new NPC. 

### Branch

master

### TC rev. hash/commit

955343f747d00de5c2bcbb336a62f10e803cdb38

### Operating system

Windows Server 2022

### Custom changes

some custom spawns...

**Comment by jackpoz** [comment]
Are you talking about this column:
https://github.com/TrinityCore/TrinityCore/blob/955343f747d00de5c2bcbb336a62f10e803cdb38/sql/base/dev/world_database.sql#L606C50-L606C50
```sql
`npcflag` bigint unsigned NOT NULL DEFAULT '0',
```
defined as "NOT NULL" ?

**Comment by mdX7** [comment]
> Are you talking about this column: https://github.com/TrinityCore/TrinityCore/blob/955343f747d00de5c2bcbb336a62f10e803cdb38/sql/base/dev/world_database.sql#L606C50-L606C50
> 
> ```sql
> `npcflag` bigint unsigned NOT NULL DEFAULT '0',
> ```
> 
> defined as "NOT NULL" ?

it was changed in a recent commit https://github.com/TrinityCore/TrinityCore/commit/7c0ef292be90340a81f32fc55df15e3489d13d4e, i forgot the ingame spawning part
