### ISSUE TITLE
Pet server crash

### ISSUE THREAD

**Issue by wowissues** [TrinityCore/TrinityCore#29303]
### Description

https://gist.github.com/wowissues/3fc4ed40e8eabaeb9caa1e5424f0840b

### Expected behaviour

Must not crash

### Steps to reproduce the problem

If you sit on the mount, and summon a pet bear, the server will crash

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/aa32feddb7cc071266417978b422845bf3354c87

### Operating system

Debian 11

### Custom changes

None

**Comment by jackpoz** [comment]
It's a triggered assertion, there should be an error message on the console. Use https://github.com/TrinityCore/TrinityCore/blob/master/contrib/debugger/crashreport.gdb to get more information from crashlogs

**Comment by wowissues** [comment]
@jackpoz I found the problem. If you sit on the mount, and click to summon a pet, the server will crash

**Comment by shamage** [comment]
Hi, maybe there will be a problem in this line : https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Pet/Pet.cpp#L370

if it were modified for example to something like this:  

```sql
 if (!(petStable->CurrentPetIndex) || (petStable->CurrentPetIndex == newPetIndex)) 
{
    // Code continues executing if the condition is true
} 
else 
{
    // Handle the case where the condition is false
}

```   ???

**Comment by jackpoz** [comment]
> @jackpoz I found the problem. If you sit on the mount, and summon a pet bear, the server will crash

Thanks, that helps a lot. Could you please update the issue description with these steps ?

**Comment by Shauren** [comment]
Those steps to reproduce arent enough.
You must first summon a pet
Then mount (this despawns the pet)
Now you must summon a DIFFERENT pet than the one that was despawned

**Comment by wowissues** [comment]
> Those steps to reproduce arent enough. You must first summon a pet Then mount (this despawns the pet) Now you must summon a DIFFERENT pet than the one that was despawned

I'm sorry. Here are more details.

1) [Crazed Alpha](https://www.wowhead.com/npc=194224/crazed-alpha) pet him.
2) Sit on the **flying** mount.
3) Use the general whistle to summon the bear
