### ISSUE TITLE
Core: Trade window glitches out if target does have AH tab opened

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29308]
### Description

When you try to open trade with someone while they have Auction House window opened, it glitches out and you won't be able to trade again (eachother) if you don't relog.

### Expected behaviour
It shoud appear the following error instead: "(Character name) is busy right now."

WotLK classic PTR 3.4.3 (51126)

https://github.com/TrinityCore/TrinityCore/assets/24683355/5a0b08ba-35d6-400e-9983-a39455c637fe

### Steps to reproduce the problem

1. Have two accounts and with one character go to Auction House and open the window by click on any auctioneer.
2. With other character go to the first character range and then press Trade.
3. Notice.

### Branch

3.3.5

### TC rev. hash/commit

79e2f77d4403

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by CyberMist2** [comment]
As the chat says: Player is busy right now, this might be a good method to avoid annoying people trying to interrupt you from using auctionhouse.

**Comment by Ovahlord** [comment]
Afaik this feature cannot be implemented on older clients because old clients do not track if a player is currently in an interaction. They only know when someone talks to an npc but not when the interaction ends. That has been implemented in later expansions only.

**Comment by AGandrup** [comment]
As I understand it, the issue is that:
Player A: interacts with auction house.
Player B: Request trade with Player A. Gets chat message "Player A busy".
Everything is working as intended so far.
Then,
Player A: Closes interaction with auction house
Player B: Request trade with Player A, but still gets chat message "Player A busy", and still will not be able to trade untill relog.

**Comment by Aokromes** [comment]
iirc the bug is also present with other interactions. iirc 2 trades.

**Comment by funjoker** [comment]
Missing CMSG?
