### ISSUE TITLE
[Master] New Setup results in Realmlist.GameBuild being 50438 rather than 51261

### ISSUE THREAD

**Issue by KhanVe** [TrinityCore/TrinityCore#29318]
### Description

For some reason, the Gamebuild field in Realmlist is set as 50438 rather than 51261 on a new fresh install using  TDB_full_1015.23071_2023_07_14.7z.  Changing Gamebuild to 51261 results in "Authentication failed for account: 1 ('1#1')".  Unsure where to go from here.

### Expected behaviour

Gamebuild should be set as 51261.

### Steps to reproduce the problem

Pull fresh copy of Master
Build Master
Unzip TDB_full_1015.23071_2023_07_14.7z into Assembly Folder
Copy libmysql.dll over
Copy Extracted Wow Files over
Run Worldserver.exe
When finished check Auth.Realmlist.Gamebuild if 50438, issue has occured

### Branch

master

### TC rev. hash/commit

6362e31

### Operating system

Win10 Pro

### Custom changes

None

**Comment by Hooaah** [comment]
LOCK TABLES `realmlist` WRITE;
/*!40000 ALTER TABLE `realmlist` DISABLE KEYS */;
INSERT INTO `realmlist` VALUES
(1,'Trinity','127.0.0.1','127.0.0.1','255.255.255.0',8085,0,0,1,0,0,50438,1,1);
/*!40000 ALTER TABLE `realmlist` ENABLE KEYS */;
UNLOCK TABLES;

Near the bottom of the auth database the line above needs changed to  51261

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/6798ef3e4e7f9972c1bdd31b7cbcae661ed7d0cd
you must have missed to update binaries.
