### ISSUE TITLE
DB/QUEST: Death knight starting zone, missing flag

### ISSUE THREAD

**Issue by Jonne733** [TrinityCore/TrinityCore#29315]
### Description

The quest "[Abandoned Mail](https://aowow.trinitycore.info/?quest=12711)" is missing an "Autocomplete" flag.
Here is a video showing the quest: https://youtu.be/7jcAnKZGT48?t=408

All info is from live Wrath Classic server.

### SQL fix

```sql
-- Quest "Abandoned Mail" should have "Autocomplete" flag
UPDATE `quest_template` SET `Flags`=`Flags`| 65536 WHERE `ID`=12711;
```

### Branch

3.3.5

### TC rev. hash/commit

79e2f77

**Comment by CraftedRO** [comment]
this can also be merged since the quest is autocomplete, I tested ingame it won't affect it.
