### ISSUE TITLE
i get this error when i run the server using the newest 10.1.7 51313 client

### ISSUE THREAD

**Issue by 0xdeadbeef** [TrinityCore/TrinityCore#29323]
### Description

exerpt as follows

Table hash 0x2AD89A7A points to a loaded DB2 store MythicPlusSeason.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob
Table hash 0x7214CB47 points to a loaded DB2 store ConditionalContentTuning.db2, fill related table instead of hotfix_blob

not sure where to even start to fix that anyone got any ideas?

### Expected behaviour

not to report errors?

### Steps to reproduce the problem

get latest rev of tcore 
compile/install
extract using latest extractors 
run

### Branch

master

### TC rev. hash/commit

097b5f3 commit c2f5ce2

### Operating system

debian

### Custom changes

none

**Comment by admadm123** [comment]
use updates for hotfixes

**Comment by mdX7** [comment]
fixed in 77504240783fad4f01f8726e948b99fc91085c21
