### ISSUE TITLE
as opposite faction I cannot attack enemies 

### ISSUE THREAD

**Issue by Melanholyx** [TrinityCore/TrinityCore#29336]
### Description

Hello Guys, when I join game I cannot attack horde guards as Alliance faction.  it says PVP is disabled. but as you see in screen its enabled but anyways for NPCs it shouldn't require to enable / disable player vs player. also happens same to enemy players.  it works after I re-click enable button.
![image](https://github.com/TrinityCore/TrinityCore/assets/28813102/848a835c-43b2-4ba0-b385-858a50af94fa)

### Expected behaviour

I should be able to attack enemy NPCs no matter if my player vs player is enabled or disabled and also for enemy players I should be able to attack if PvP is enabled without re-enable it after log in.

### Steps to reproduce the problem

1. Login ingame.
2. create Alliance Character
3. Go To Razor Hills
4. try to attack guards.

### Branch

master

### TC rev. hash/commit

2e8859237dff84d92626a80c99c38647d04acdf3

### Operating system

Windows 11

### Custom changes

nothing

**Comment by shamage** [comment]
Please fill in the missing data for TC rev. hash

**Comment by jackpoz** [comment]
Are you using TrinityCore or some other fork/repack ?

**Comment by Melanholyx** [comment]
Hello, a bit new still don't know alot TC rev. hash and its meaning, @jackpoz  yes its trinity master

**Comment by Melanholyx** [comment]
updated TC rev. hash
