### ISSUE TITLE
Zana and Area are not known

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#29334]
### Description

I apologize in advance, but there is a problem that I have been struggling with for half a year. I moved the location of the Top of the Tornado from the cataclysm client and no matter what I do, I always don't have the name of the location, I entered the data in all the dbs and exported the maps correctly. Someone will not help to solve this problem.
https://ibb.co/BgM7Qy3
https://ibb.co/d50r8Ns
https://ibb.co/ggTDQ8N
https://ibb.co/zG94Zq5

### Expected behaviour

The data should be displayed everywhere

### Steps to reproduce the problem

Fix the display of the location name.

### Branch

3.3.5

### TC rev. hash/commit

last

### Operating system

win10

### Custom changes

Maps

**Comment by Shauren** [comment]
Client modding is not supported - but if you get issue zone detection both in client and server, then you simply didnt mod things correctly (what is correct? that i dont know, i can only say that what you did isnt enough)
