### ISSUE TITLE
After today's update is compiled, switching regions will crash immediately.

### ISSUE THREAD

**Issue by Greyisttot** [TrinityCore/TrinityCore#29346]
### Description

After today's update is compiled, switching regions will crash immediately.

### Expected behaviour

https://cdn.discordapp.com/attachments/376457124726702080/1158127711018029128/bandicam_2023-10-02_03-44-22-498.mp4?ex=651b1dfb&is=6519cc7b&hm=c1fea38eaeae2173b69f1c8b0937412dfe51019a9914dda22029b89d4490fe20&

### Steps to reproduce the problem

https://cdn.discordapp.com/attachments/376457124726702080/1158127711018029128/bandicam_2023-10-02_03-44-22-498.mp4?ex=651b1dfb&is=6519cc7b&hm=c1fea38eaeae2173b69f1c8b0937412dfe51019a9914dda22029b89d4490fe20&

### Branch

master

### TC rev. hash/commit

[server.worldserver] TrinityCore rev. c676d1477239 2023-10-01 18:56:35 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Ubuntu 22.04

### Custom changes

None

**Comment by heyitsbench** [comment]
Crashlog?

**Comment by Greyisttot** [comment]
https://cdn.discordapp.com/attachments/376457124726702080/1158138875861028956/Wow_2023-10-02_04-29-30-384.mp4?ex=651b2861&is=6519d6e1&hm=2ea72262eb4f9b069025854212be638b3978f3869b0f0f5f7587760d99c198f5&

**Comment by Greyisttot** [comment]
> Crashlog?

How to get crash log in ubuntu?

**Comment by jackpoz** [comment]
Check https://github.com/TrinityCore/TrinityCore/tree/master/contrib/debugger for how to get a crashlog
