### ISSUE TITLE
Server Crash on ARC4 Encryption

### ISSUE THREAD

**Issue by Not-A-Bug-A-Feature** [TrinityCore/TrinityCore#29357]
### Description

Server is starting but after that it crashes.
[ff0d198ef5b2_worldserver.exe_[8-10_21-20-35].txt](https://github.com/TrinityCore/TrinityCore/files/12841549/ff0d198ef5b2_worldserver.exe_.8-10_21-20-35.txt)
[ff0d198ef5b2_worldserver.exe_[8-10_21-20-35].zip](https://github.com/TrinityCore/TrinityCore/files/12841550/ff0d198ef5b2_worldserver.exe_.8-10_21-20-35.zip)

### Expected behaviour

Server is starting but after that it crashes.

### Steps to reproduce the problem

- Use MySQL 8.0.34
- Use Boost 1.78.0

Server Crashing

```
Assertion message: 
D:\Github\TrinityCore\src\common\Cryptography\ARC4.cpp:31 in Trinity::Crypto::ARC4::ARC4 ASSERTION FAILED:
  result == 1
```

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. ff0d198ef5b2 2023-09-29 14:29:29 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows Server 2019

### Custom changes

- None

**Comment by Ovahlord** [comment]
did you copy the legacy.dll file into your directory?

**Comment by Shauren** [comment]
He did not

**Comment by Not-A-Bug-A-Feature** [comment]
I did not, but it was nowhere written todo so, just to use bigger openssl version. But thanks for the hint.

**Comment by Shauren** [comment]
> I did not, but it was nowhere written todo so, just to use bigger openssl version. But thanks for the hint.

Straight up false statement, it is clearly written in our wiki (https://trinitycore.info/install/Core-Installation/windows-core-installation)
![obraz](https://github.com/TrinityCore/TrinityCore/assets/297439/deb676dc-0d91-4baf-9459-54c97f7c8057)

**Comment by Aokromes** [comment]
and it's not new thing, it's there for 2 months.

**Comment by Not-A-Bug-A-Feature** [comment]
o0 Okay... then sry.
