### ISSUE TITLE
Error compiling 9.2.7

### ISSUE THREAD

**Issue by WhiteAssassins** [TrinityCore/TrinityCore#29354]
### Description

The log is this:

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a1b64/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_a1b64.dir/build.make CMakeFiles/cmTC_a1b64.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a1b64.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD -o CMakeFiles/cmTC_a1b64.dir/src.c.o -c /home/TrinityCore/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_a1b64
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a1b64.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD CMakeFiles/cmTC_a1b64.dir/src.c.o -o cmTC_a1b64 
/usr/bin/ld: CMakeFiles/cmTC_a1b64.dir/src.c.o: in function `main':
src.c:(.text+0x35): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x41): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x4d): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x5f): undefined reference to `pthread_join'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_a1b64.dir/build.make:106: cmTC_a1b64] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_a1b64/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_116d5/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_116d5.dir/build.make CMakeFiles/cmTC_116d5.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.18/Modules/CheckFunctionExists.c
Linking C executable cmTC_116d5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_116d5.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o -o cmTC_116d5  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_116d5.dir/build.make:106: cmTC_116d5] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_116d5/fast] Error 2

Determining if the strtod_l exist failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a8d1c/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_a8d1c.dir/build.make CMakeFiles/cmTC_a8d1c.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o -c /home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: use of undeclared identifier 'strtod_l'
  return ((int*)(&strtod_l))[argc];
                  ^
1 error generated.
gmake[1]: *** [CMakeFiles/cmTC_a8d1c.dir/build.make:85: CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_a8d1c/fast] Error 2

File /home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef strtod_l
  return ((int*)(&strtod_l))[argc];
#else
  (void)argc;
  return 0;
#endif
}

### Expected behaviour

Make it compile correctly

### Steps to reproduce the problem

Compile version 9.2.7 on debian 11 bullseye

### Branch

master

### TC rev. hash/commit

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a1b64/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_a1b64.dir/build.make CMakeFiles/cmTC_a1b64.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a1b64.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD -o CMakeFiles/cmTC_a1b64.dir/src.c.o -c /home/TrinityCore/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_a1b64
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a1b64.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD CMakeFiles/cmTC_a1b64.dir/src.c.o -o cmTC_a1b64 
/usr/bin/ld: CMakeFiles/cmTC_a1b64.dir/src.c.o: in function `main':
src.c:(.text+0x35): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x41): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x4d): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x5f): undefined reference to `pthread_join'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_a1b64.dir/build.make:106: cmTC_a1b64] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_a1b64/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_116d5/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_116d5.dir/build.make CMakeFiles/cmTC_116d5.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.18/Modules/CheckFunctionExists.c
Linking C executable cmTC_116d5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_116d5.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_116d5.dir/CheckFunctionExists.c.o -o cmTC_116d5  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_116d5.dir/build.make:106: cmTC_116d5] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_116d5/fast] Error 2

Determining if the strtod_l exist failed with the following output:
Change Dir: /home/TrinityCore/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a8d1c/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_a8d1c.dir/build.make CMakeFiles/cmTC_a8d1c.dir/build
gmake[1]: Entering directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o -c /home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: use of undeclared identifier 'strtod_l'
  return ((int*)(&strtod_l))[argc];
                  ^
1 error generated.
gmake[1]: *** [CMakeFiles/cmTC_a8d1c.dir/build.make:85: CMakeFiles/cmTC_a8d1c.dir/CheckSymbolExists.c.o] Error 1
gmake[1]: Leaving directory '/home/TrinityCore/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_a8d1c/fast] Error 2

File /home/TrinityCore/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef strtod_l
  return ((int*)(&strtod_l))[argc];
#else
  (void)argc;
  return 0;
#endif
}

### Operating system

Debian 11 x64

### Custom changes

None

**Comment by Jinnaix** [comment]
You are on your own if you try to compile something ancient that has no live support.

Only advise - take the old wiki and use page history to identify the requirements from back then.
