### ISSUE TITLE
In 'Exile's Reach' mode, the mission is missing?

### ISSUE THREAD

**Issue by ycbwb** [TrinityCore/TrinityCore#29365]
### Description

When I complete a task and there are no subsequent tasks to perform.
Just after finishing the barbecue task.
<img width="1920" alt="World of Warcraft 2023_10_14 1_21_33(1)" src="https://github.com/TrinityCore/TrinityCore/assets/16470019/5a3c9650-a532-4405-b40b-6532cf25cf40">

### Expected behaviour

Lost the mission to continue.

### Steps to reproduce the problem

1.Create new character.
2.Choose 'Exile's Reach' mode.
3.Play the game normally.
4.When the task reaches barbecue, the task to continue is lost.

### Branch

master

### TC rev. hash/commit

Failed to create conversation (Id: 12058) due to missing actor (Idx: 3).

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by mdX7** [comment]
Exiles Reach is not implemented any further yet. Thats the last implemented currently.

Duplicate #29223
