### ISSUE TITLE
Candy Bucket quests not working

### ISSUE THREAD

**Issue by dewmguy** [TrinityCore/TrinityCore#29375]
### Description

None of the [Candy Bucket quests](https://www.wowhead.com/wotlk/quest=12336/candy-bucket#) offered by the [Candy Buckets](https://www.wowhead.com/wotlk/object=190040/candy-bucket) inside of Inns can be completed.

Clicking "Complete Quest" does nothing, the window does not react or close.

### Expected behaviour

The quest is completed, xp and a [Handful of Candy](https://www.wowhead.com/wotlk/item=37586/handful-of-candy) are given.

### Steps to reproduce the problem

1. Go to an Inn during Hallow's End
2. Talk to the Candy Bucket
3. Click Complete Quest

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 307b1436dbd8 2023-10-19 01:01:22 +0000 (master branch) (Unix, RelWithDebInfo, Static)
[**Built with ElunaTrinityWotlk**](https://github.com/ElunaLuaEngine/ElunaTrinityWotlk)

### Operating system

Ubuntu 22.04 Server / Windows 11 Client

### Custom changes

on level autotrainer
DK intro skip
player announce

**Comment by Aokromes** [comment]
there is no such rev on trinitycore.

**Comment by dewmguy** [comment]
TrinityCore rev. d5b64a0bb23c 2023-10-18 20:21:53 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

**Comment by dewmguy** [comment]
i closed this since it seemed problematic that I was testing on an Eluna server. to simplify, I will be officially testing only on a vanilla built TC 335. Unofficially, I will be testing on both.
