### ISSUE TITLE
Vmaps no work

### ISSUE THREAD

**Issue by Nansydrew** [TrinityCore/TrinityCore#29374]
### Description

NPCs do not see game objects at all, although the config is enabled and the vmaps are correct

### Expected behaviour

just summon a pet as a warlock and send it to attack an NPC behind a wall or through a texture

### Steps to reproduce the problem

just summon a pet as a warlock and send it to attack an NPC behind a wall or through a texture

### Branch

3.3.5

### TC rev. hash/commit

Last rev

### Operating system

Debian 12

### Custom changes

No

**Comment by jackpoz** [comment]
vmaps are not related to "send a pet to attack", that's what mmaps are for. do you have mmaps ?

**Comment by Nansydrew** [comment]
> vmaps are not related to "send a pet to attack", that's what mmaps are for. do you have mmaps ?

Yes.
Everything is there and everything is included.

**Comment by Ovahlord** [comment]
Post a log of your server startup sequence here please.

**Comment by jackpoz** [comment]
>TrinityCore rev. 49b2ff3e4244+ 2023-10-15 04:47:24 +0300 (main branch)

We don't have a "main" branch or a 49b2ff3e4244 commit hash in TrinityCore

**Comment by Nansydrew** [comment]
[Server.log this repo](https://drive.google.com/file/d/1obkurIGW0ZiGfwCWjfaWvZLPaS5Ug6nv/view?usp=drivesdk) 

I just dragged the sources into the private repo. I collected it from this thread, the problem remains. creatures do not specifically see game objects that are in the gameobject_template table

**Comment by Ovahlord** [comment]
Gameobject pathfinding is not supported. If you send a pet to attack something behind a gameobject, it will just walk through it.

**Comment by Nansydrew** [comment]
there they answered that the patch for finding game objects is not supported... and you write to him saying that in your opinion this is normal behavior that creatures can walk through walls and doors or fall under textures if it is some kind of tower from the gameobject_template table?

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14120
