### ISSUE TITLE
lua error 10.1.7 51754

### ISSUE THREAD

**Issue by admadm123** [TrinityCore/TrinityCore#29378]
### Description

when you go to the character selection menu, a lua error constantly crashes
![ewqewqdqwd](https://github.com/TrinityCore/TrinityCore/assets/63059326/1cd4f141-48aa-44d8-b0af-4313acd57ecd)

Message: Interface/SharedXML/Settings/Blizzard_Setting.lua:9: 'name' for variable 'PROXY_TARGET_FPS_ENABLED' requires string type.
Time: Fri Oct 20 15:31:37 2023
Count: 1
Stack: Interface/SharedXML/Settings/Blizzard_Setting.lua:9: 'name' for variable 'PROXY_TARGET_FPS_ENABLED' requires string type.
[string "=[C]"]: in function `error'
[string "@Interface/SharedXML/Settings/Blizzard_Setting.lua"]:9: in function <Interface/SharedXML/Settings/Blizzard_Setting.lua:7>
[string "@Interface/SharedXML/Settings/Blizzard_Setting.lua"]:209: in function `Init'
[string "@Interface/SharedXML/Mixin.lua"]:50: in function `CreateAndInitFromMixin'
[string "@Interface/SharedXML/Settings/Blizzard_Settings.lua"]:184: in function `RegisterProxySetting'
[string "@Interface/SharedXML/SettingDefinitions/Graphics.lua"]:1220: in function <Interface/SharedXML/SettingDefinitions/Graphics.lua:455>
[string "=[C]"]: ?
[string "@Interface/SharedXML/Settings/Blizzard_SettingsRegistrar.lua"]:28: in function `AddRegistrant'
[string "@Interface/SharedXML/SettingDefinitions/Graphics.lua"]:1320: in main chunk

Locals: (*temporary) = "'name' for variable 'PROXY_TARGET_FPS_ENABLED' requires string type."

### Expected behaviour

I think that the problem is somewhere in the hotfixes because this was not noticed on the old one

### Branch

master

### Operating system

Windows 10 x64

### Custom changes

No

**Comment by 171497767** [comment]
I have the same problem with you. 
To be sure is October 2, 9 c0bfc7c8c8af8d13378231b4b45c97f91c64a37 this version, at that time is not the error message. 
Updating the new TDB started to encounter this problem.

**Comment by admadm123** [comment]
> ## У меня та же проблема, что и у тебя.
> Чтобы быть уверенным, что эта версия 2, 9 октября c0bfc7c8c8af8d13378231b4b45c97f91c64a37, в то время не было сообщения об ошибке.
> Обновление новой БТ начало сталкиваться с этой проблемой.
> И ты словно в русском квартале? Я заметил, что никто в английской секции не ответил на этот вопрос. Я из Китая, я не сообщал об этой проблеме, потому что, похоже, англоязычные пользователи не затронуты.

there was no error on the previous version of the hotfixes, when I boot with it there is no error. and with the new database there is. you need to search in which table. if anyone finds it please let us know

**Comment by admadm123** [comment]
There is no error in the English localization. This error appears in other localizations

**Comment by admadm123** [comment]
After relogging, the graphics settings disappear in the character menu and a Lua error appears in all localizations except English

**Comment by Shauren** [comment]
Update instead of posting more of the same

**Comment by admadm123** [comment]
> Update worldserver instead of posting more of the same

I rolled back the hotfix_blob and the error disappeared in Russian localization

Update worldserver when assembling the solution with your changes, 1 1 errors appeared

I rolled back the source code

**Comment by Aokromes** [comment]
> > Update worldserver instead of posting more of the same
> 
> I rolled back the hotfix_blob and the error disappeared in Russian localization
> 
> Update worldserver when assembling the solution with your changes, 1 1 errors appeared
> 
> I rolled back the source code

if you don't post new errors never will be fixed and you will be stuck on one old core.

**Comment by admadm123** [comment]
> > > Update worldserver instead of posting more of the same
> > 
> > 
> > I rolled back the hotfix_blob and the error disappeared in Russian localization
> > Update worldserver when assembling the solution with your changes, 1 1 errors appeared
> > I rolled back the source code
> 
> if you don't post new errors never will be fixed and you will be stuck on one old core.

I rebuilt the solution now, everything is fine, I apologize
