### ISSUE TITLE
 Candy Bucket quests not working

### ISSUE THREAD

**Issue by dewmguy** [TrinityCore/TrinityCore#29376]
### Description

None of the [Candy Bucket quests](https://www.wowhead.com/wotlk/quest=12336/candy-bucket#) offered by the [Candy Buckets](https://www.wowhead.com/wotlk/object=190040/candy-bucket) inside of Inns can be completed.

Clicking "Complete Quest" does nothing, the window does not react or close.

### Expected behaviour

The quest is completed, xp and a [Handful of Candy](https://www.wowhead.com/wotlk/item=37586/handful-of-candy) are given.

### Steps to reproduce the problem

1. Go to an Inn during Hallow's End
2. Talk to the Candy Bucket
3. Click Complete Quest

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. d5b64a0bb23c 2023-10-18 20:21:53 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04 Server / Windows 11 Client

### Custom changes

None

**Comment by dewmguy** [comment]
changing the quest_template flag from 65536 to 0 made the quests function as expected. not sure if this is the way the quests were intended to be used, if someone has a more eloquent solution. @Aokromes

**Comment by Nyr97** [comment]
As far as I know, quest_template should not be modified under any circumstances as it all comes from wdb parsing. Any changes done to them should be in quest_template_addon (if related). The issue must be somewhere else.

**Comment by CraftedRO** [comment]
Make sure you have latest core / clean db, [your 2017 comment](https://github.com/TrinityCore/TrinityCore/issues/18104#issuecomment-337829256) makes me think smth is wrong on your side.

d5b64a0bb23c quests works just fine for me on latest core/db:

https://github.com/TrinityCore/TrinityCore/assets/24683355/99282ee1-fc60-48f7-ae4b-7b9dccd2587e

**Comment by dewmguy** [comment]
@CraftedRO are you saying that this is not a repeatable issue? my db then would have been unmodified. it's possible i have made some modifications to quest rewards and stuff since then, but nothing drastic in any way. If this issue is only on my end then I will reinstall the database.

**Comment by CraftedRO** [comment]
well if you have this problem at every inn then I guess is smth wrong on your side (and you shoud try clean compile and import db again) since It works for me at the ones I tried.

**Comment by dewmguy** [comment]
I rebuilt world and I'm having the same problem. I created a new character to test.

Error in QUEST_STATUS_COMPLETE: player Handbanana GUID Full: 0x0000000000000291 Type: Player Low: 657 tried to complete quest 12336, but is not allowed to do so (possible packet-hacking or high latency)

**Comment by TS-BAH** [comment]
将配置里面的自动完成任务开启
Quests.IgnoreAutoComplete = 1

**Comment by acidmanifesto** [comment]
> 将配置里面的自动完成任务开启
> Quests.IgnoreAutoComplete = 1

Translation
Turn on automatic task completion in the configuration

**Comment by dewmguy** [comment]
![image](https://github.com/TrinityCore/TrinityCore/assets/16745918/83989c20-5ace-4a8b-a393-6df58460ea1f)

this was already enabled

**Comment by CraftedRO** [comment]
well that's the problem, default config is 0 for that thing and you won't have this problem.

**Comment by dewmguy** [comment]
@CraftedRO okay that solved the problem of being able to turn in quests with the autocomplete flag enabled.

now the problem is all of the candy bucket quests reset on logout. you can complete the quest at a particular inn, log out, log back in, and the quest is available again.
