### ISSUE TITLE
possible double-free with ObjectGridLoader

### ISSUE THREAD

**Issue by Idoitbetter** [TrinityCore/TrinityCore#29372]
### Description

Asan report: https://gist.github.com/Idoitbetter/91724a0c92dcfe0f43d1d53d4a8087b5
I get that after setactive grid changes
https://github.com/TrinityCore/TrinityCore/commit/163c674adb6413089134e081180c10e6871f3a04
https://github.com/TrinityCore/TrinityCore/commit/2df1bc3ec12d4a3ed7bac1274d8810ca3538607d
I'm not sure if it's related or just a coincidence, I haven't seen it before.

### Expected behaviour

Don't report

### Steps to reproduce the problem

unknown

### Branch

3.3.5

### TC rev. hash/commit

d028bb0e374acfc635b2f6f224f5732d3bfa13fd

### Operating system

Debian

### Custom changes

None

**Comment by Shauren** [comment]
This certainly could have been happening even before these changes
