### ISSUE TITLE
Error while parsing SQL. Core fix required.

### ISSUE THREAD

**Issue by opiums9** [TrinityCore/TrinityCore#29387]
### Description

After some time I get sql syntax error but can't find it in crash file

### Expected behaviour

I would like to receive detailed information about why this happens and how to prevent this from happening in the future.

### Steps to reproduce the problem

The crash occurs after some time, there is no guess at what step. I changed the output from the database to "Trace" in the DBErrors.log file for more detailed information, but did not see any errors in the queries.

List of crash files:
* [1698085366.crash](https://gist.github.com/opiums9/b6722da875a4afcf88cbf453f7c23594)
* [1698085436.crash](https://gist.github.com/opiums9/8a7f842dd5795d622d04ba7b20cb51ce)
* [1698089693.crash](https://gist.github.com/opiums9/b26e8df01eff192611267d5ce8faa393)
* [1698106438.crash](https://gist.github.com/opiums9/63d4760f393d23b0598f67c2e6948118)

### Branch

3.3.5

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/ff0d198ef5b2c74aea2e346bfda3b52a957a1876

### Operating system

Debian 11 x64

### Custom changes

* ElunaTrinityWotlk
* rochet2 multivendor_3.3.5
* rochet2 dressnpcs_3.3.5
* Arena1v1 fixed

**Comment by Shauren** [comment]
This is definitely a custom patch issue and "sql.sql" logger should print you the failed query if you set it to INFO level (or lower, debug/trace - but I don't recommend these levels as they will also print successfully every executed query)
