### ISSUE TITLE
Crash at Onslaught Harbor by just stay in.

### ISSUE THREAD

**Issue by Leonis3491** [TrinityCore/TrinityCore#29381]
### Description

Hi. I see i crash everytime when i stand on Onslaught Harbor. No battle no interaction just stay and wait get reproductible crash after some minutes.
I post my crash report, it may be caused by the function ObjectGuid Object::GetGuidValue(uint16 index) const on Object.cpp.

### Expected behaviour

Instead no crash should happen

### Steps to reproduce the problem

https://www.wowhead.com/wotlk/npc=29330/onslaught-harbor-guard

https://www.wowhead.com/wotlk/npc=29329/onslaught-paladin

https://www.wowhead.com/wotlk/npc=29338/onslaught-raven-bishop

https://www.wowhead.com/wotlk/fr/npc=29333/chevaucheur-de-griffons-de-lassaut

### Branch

3.3.5

### TC rev. hash/commit

[5463b6268c57+_worldserver.exe_[22-10_17-28-10].txt](https://github.com/TrinityCore/TrinityCore/files/13063778/5463b6268c57%2B_worldserver.exe_.22-10_17-28-10.txt)
[5463b6268c57+_worldserver.exe_[22-10_17-28-10].dmp](https://github.com/TrinityCore/TrinityCore/files/13063779/5463b6268c57%2B_worldserver.exe_.22-10_17-28-10.dmp)

### Operating system

Windows 10

### Custom changes

No custom change applied for reproduce the crash. I have restart server and delete all chars, create a new one teleport to Onslaught Harbor and wait

**Comment by Aokromes** [comment]
your crashes are very likely from your mods, i see people every day there and no crashes.

**Comment by Leonis3491** [comment]
I will update my version but i need to save all modifications.
So i may tried to stay on that zone with no mods on my client ?

**Comment by Faq** [comment]
@Leonis3491 yes, try clean trinity, if works fine. Add one by one mod and test, then you will know what mod is the faulty.
