### ISSUE TITLE
Dragonflight. Guild

### ISSUE THREAD

**Issue by admadm123** [TrinityCore/TrinityCore#29399]
### Description

is it possible to do something with the guild display?
![image](https://github.com/TrinityCore/TrinityCore/assets/63059326/da322702-8396-49e5-8642-92da36033c38)

### Branch

master

### Operating system

Windows 10 x64

**Comment by Nyr97** [comment]
Not until communities are implemented, they moved the entire guild handling into community one.

**Comment by Naddley** [comment]
duplicate:
https://github.com/TrinityCore/TrinityCore/issues/28961
https://github.com/TrinityCore/TrinityCore/issues/28665
