### ISSUE TITLE
Dragonflight. bug after relog. Void Elves. Hanter 70 lvl.

### ISSUE THREAD

**Issue by Altaxa-Tyrbowow** [TrinityCore/TrinityCore#29394]
### Description

have their dragon mount removed upon relog
![image](https://github.com/TrinityCore/TrinityCore/assets/148558494/603a4baa-5666-437b-acec-bc82d14d5d25)

### Expected behaviour

When you enter, the mount remains.

### Steps to reproduce the problem

This bug appeared after the creation of DK Draenei. Having completed the entire initial chain, using transport flight, I flew to Stormwind. There I relogged and went for a lvl 70 character who was in Valdraken. I did the daily quest. Relog. An hour later my character came in again and was in the air.

### Branch

master

### TC rev. hash/commit

https://www.youtube.com/watch?v=TSLQddE4Ek8&ab_channel=TURBO-WOW

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by mdX7** [comment]
TrinityCore is not supporting dragonriding yet, report it to whatever core you are using

**Comment by admadm123** [comment]
[Shauren](https://github.com/Shauren) closed this as [completed](https://github.com/TrinityCore/TrinityCore/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/TrinityCore/TrinityCore/commit/64a14f13ace1f6c7ac2aedc90ad2b48f57a3920c [2 days ago](https://github.com/TrinityCore/TrinityCore/issues/29391#event-10794542867)

**Comment by admadm123** [comment]
tested, working properly, the aura of the dragon remains
