### ISSUE TITLE
Dragonflight. bug after relog ALL DWARF

### ISSUE THREAD

**Issue by admadm123** [TrinityCore/TrinityCore#29391]
### Description

All dwarf have their dragon mount removed upon relog
Any dragon mount.
The aura of dynamic flight remains 406095
The mount's aura is removed after relogging
Such a bug has not yet been identified on other races
The verification account is not a GM account

This was not noticed on the core of build 51313.
There are no user auras in hotfixes for the flight.

Video:
https://youtu.be/TSLQddE4Ek8

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by admadm123** [comment]
problem solved. There was a custom hotfix in the database with an aura. closed

**Comment by admadm123** [comment]
problem solved. There was a custom hotfix in the database with an aura. closed

**Comment by admadm123** [comment]
in order for the bug to appear, you need to make 2 repeated relogs

**Comment by Shauren** [comment]
406095 is never applied on clean TC (dragonriding isnt implemented), this must be something custom you changed

**Comment by Shauren** [comment]
I am unable to reproduce this, logging out does not remove my mount aura

**Comment by admadm123** [comment]
> I am unable to reproduce this, logging out does not remove my mount aura

I used to be fine too. I don't know how it is connected, but the algorithm is like this. You need to create a dwarf dk, go through the chain, and then study the flights and play several relogs from the system, then this bug is transferred to the entire account

**Comment by admadm123** [comment]
Can I have your mail? I'll send it to you auth and characters for verification and tell you the password from the account

**Comment by Shauren** [comment]
Use .pdump command to export a character

**Comment by admadm123** [comment]
> Use .pdump command to export a character

https://drive.google.com/file/d/1a-8yj_JSRG0FWDgEDjxhY3TLv-ARxgO3/view?usp=sharing

**Comment by admadm123** [comment]
character nick "Дюк" dwarf dk

**Comment by admadm123** [comment]
thanks, it works well now
