### ISSUE TITLE
Metro Alliance

### ISSUE THREAD

**Issue by admadm123** [TrinityCore/TrinityCore#29404]
### Description

Throws off the train when boarding it in the air, it is impossible to get there
![image](https://github.com/TrinityCore/TrinityCore/assets/63059326/fd5d6b41-8ba4-4eb7-b57e-adf13c183cc8)

### Branch

master

### Operating system

Windows 10 x64

**Comment by Naddley** [comment]
duplicate: https://github.com/TrinityCore/TrinityCore/issues/26903
