### ISSUE TITLE
Blood Trap bugs runes

### ISSUE THREAD

**Issue by RioMcBoo** [TrinityCore/TrinityCore#29415]
### Description

Using "Blood Trap" bugs runes sometimes (especially in blood spec)

The problem is that from time to time when playing as a death knight, a bug occurs in which the client sees that the runes are available, but cannot use them.

### Expected behaviour

There shouldn't be any bugs. Players from 2010-2011 say that there were never any bugs.

### Steps to reproduce the problem

It is difficult to imagine the situation and reproduce it. But judging by the code, it is very difficult to imagine and calculate the actions that need to be done for verification.

This problem may not be the only one.

### Branch

3.3.5

### TC rev. hash/commit

I can't provide that.

### Operating system

I can't provide that.

### Custom changes

I can't provide that.

**Comment by RioMcBoo** [comment]
https://github.com/TrinityCore/TrinityCore/blob/63cbef9e893d19318e97aab67dff7bc7e82e6544/src/server/scripts/Spells/spell_dk.cpp#L2576

As you can see from this code - the rune number passed to the client and the rune number that is updated - can be different under some circumstances

**Comment by Aokromes** [comment]
```
I can't provide that.
```

we can't accept such bug report.

**Comment by RioMcBoo** [comment]
> ```
> I can't provide that.
> ```
> 
> we can't accept such bug report.

Ok, how rude, I am going to download, set up, and test it, because the fact that all private servers have the same code - is not proof.

**Comment by RioMcBoo** [comment]
I tested now. I cant do previous bug i said about, because it maybe depends on ping problems in addition, but when you did some actions - you can see

0) clear all talents 
1) use unholy presence (for less GCD)
2) use 60 lvl dummy to avoid misses and dodges
3) spend 2 unholy or 2 frost runes in a row, try 3rd time to use = "you have not runes"
4) use "Blood Trap" and spend Death rune to use 3d time the same spell
5) wait for activate Death rune - use your spell for 4th time = bingo
6) As you could notice - Death rune convert into blood only after activating (needs after use)

**Second test shows 2 extra Death runes**
0) the same preparations
1) get "Reaping" talent 3/3 in unholy branch
2) use 1 blood strike = you get 1 Death rune 
3) use Blood Trap = you activate first Death rune in CD, and get new death rune. 
But it should have only activate first Death rune
finally i have 2 extra Death runes above "Blood Trap"

**Third test.** 
0) I changed the code like that:
```
// if both runes are not the same type, transform the blood rune
if (player->GetCurrentRune(0) != player->GetCurrentRune(1))
    _runeIndex = player->GetCurrentRune(0) == RUNE_BLOOD ? 0 : 1;

_runeIndex = resetIndex;
player->SetRuneCooldown(resetIndex, 0);
```
Visually it work nice, but i still have 1 extra Death rune, but not 2 extra Death runes.


Ok finally i made 2 points for me.
1) Private servers definitely fix extra Death Rune, but maybe that code will avoid rune bug I texted above in the head
2) [Aokromes](https://github.com/Aokromes) - you are not a human, you fucking NPC bot. Because you even didn't see code I linked. In any case it is obviously rude mistake in the code and you could just fix it in 5 mins **Without** your arrogant pathos.

Good luck, You have discouraged anyone from wanting to work with you. I think I heard somewhere about soft skills that programmers value so much. But no, it seemed...

**Comment by RioMcBoo** [comment]
Ok... tested now on war...e server on pvp realm - it works the same. What a shame(((

**Comment by jackpoz** [comment]
Is this issue even related to TrinityCore or to some random private server ?
