### ISSUE TITLE
Cannot submit SQL fix because its big

### ISSUE THREAD

**Issue by egoroof** [TrinityCore/TrinityCore#29411]
### Description

<img width="714" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/2605831/e31530c9-5efe-4805-ba71-968a4c4377fd">

### Expected behaviour

It should working

### Steps to reproduce the problem

Open https://github.com/TrinityCore/TrinityCore/issues/new?assignees=&labels=Comp-Database%2CFeedback-PatchFix&projects=&template=sql_fix.yml and submit big sql fix (more than 65536 characters)

### Branch

3.3.5

### TC rev. hash/commit

its not related to source code

### Operating system

windows 11

### Custom changes

none

**Comment by Aokromes** [comment]
use gist to post big sql files.

**Comment by Faq** [comment]
https://gist.github.com/
