### ISSUE TITLE
Serverside ATs dont trigger for dead player

### ISSUE THREAD

**Issue by Naddley** [TrinityCore/TrinityCore#29413]
### Description

Serverside ATs dont trigger while youre dead/ a ghost

### Expected behaviour

Serverside ATs should have the possibility to get triggered by dead players.

Used for Quest: 38765 (Enter the Illidari: Shivarra)
https://www.wowhead.com/quest=38765/enter-the-illidari-shivarra

### Steps to reproduce the problem

1. Step: Die near a Serverside AT (example Mage Tower SW)
2. Step: try to trigger the teleport of the Serverside AT

### Branch

master

### TC rev. hash/commit

a0fdac0ecc11+

### Operating system

Win10

### Custom changes

None

**Comment by mdX7** [comment]
> Is legit that Dead players trigger that ?. Or should be triggered by ghost players also ?

the specific case linked above should -only- be triggered by dead players even

**Comment by meji46** [comment]
I have some work done for this since clientside areatriggers also have cases where they only trigger for ghost or dead players

**Comment by meji46** [comment]
There are several cases for clientside ones. Some support ghosts and dead players and others only one or the other (they're always triggered for alive players)

**Comment by Naddley** [comment]
fixxed in https://github.com/TrinityCore/TrinityCore/commit/d51d6b0abeec25a7c7fd4903ddbca0124ee8c723
