### ISSUE TITLE
spell damage with times not right

### ISSUE THREAD

**Issue by 5266869** [TrinityCore/TrinityCore#29423]
### Description

i made a spell like this:

REPLACE INTO spell_dbc SET ID=121301, Attributes=16, AttributesEx3=1048576, StackAmount=999, DurationIndex=21, ProcChance=101, RangeIndex=1, Effect1=6, EffectDieSides1=1, EffectBasePoints1=9, EffectImplicitTargetA1=1, EffectApplyAuraName1=79, EffectMiscValue1=127, EffectAmplitude1=1, Effect2=6, EffectDieSides2=1, EffectBasePoints2=9, EffectImplicitTargetA2=1, EffectApplyAuraName2=136, EffectAmplitude2=1, SchoolMask=8;

then cast this aura to player with stack count 240, means the player have 25 times damage and healing.
most spells  good ,  bug spell id 17962 not.

spell id 17962:
with 25 times: damage 15307, dot damage 85050, 85050, 85050
without times: damage 613, dot damage 137, 137, 137

15307 / 25 = 612.28 ≈ 613   this is good
85050 / 25 = 3402 this is so much high, but 3402 / 25 = 136.08 ≈ 137, it looks like dot damage had 25 times twice.

is this can fix ? thanks very much. sorry about my pool english.

### Expected behaviour

none

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

newest

### Operating system

ubuntu 22.04

### Custom changes

none

**Comment by Ovahlord** [comment]
Damage bonus effects are multiplicative. Meaning your buff multiplied with another bonus effect. That's a general rule of the game so there is nothing broken, you just try to do something you cannot do.

**Comment by 5266869** [comment]
can you see this ?
137 x 25 x 25  = 85050 ？
it is not right .
137 x 25 is good , but not 137 x 25 x 25
please check it carefully
