### ISSUE TITLE
Display only character Achiviements to Others feature

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29428]
### Description

Display only character Achiviements to Others feature is not working at all

### Expected behaviour

Working option

### Steps to reproduce the problem

1. ESC -> Options
2. Open Social
3. Set checkbox "Display only character Achiviements to Others" 
4. Try having your character inspected by another character

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f58ff3d0f748a4abeb7681981bd964aa7423ecc1

### Operating system

Debian 11

### Custom changes

None

**Comment by Shauren** [comment]
It works perfectly, account wide achievements are not implemented after all so character achievements are the only achievements you have

**Comment by PivanDepolo** [comment]
> It works perfectly, account wide achievements are not implemented after all so character achievements are the only achievements you have (means there is nothing to be hidden)

I apologize Sir Shauren. So I misunderstood
