### ISSUE TITLE
LOOT DF

### ISSUE THREAD

**Issue by admadm123** [TrinityCore/TrinityCore#29431]
### Description

table creature_loot_template.  given the design of the old tables, the currency was designated with a sign - now it's impossible. there is no currency in the table and it is impossible to get it from the creature in the loot

**Comment by Aokromes** [comment]
i am sure currencies have one item id linked like on 3.3.5a (emblems of triump and frost) and cata.

**Comment by Ovahlord** [comment]
they do not. They are a new system that is currently not supported.

**Comment by meji46** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20830 (FYI: I was working on this (revamp) but I've temporarily stopped until I can figure out how to solve certain cases)
