### ISSUE TITLE
TCE00011

### ISSUE THREAD

**Issue by Ryanfernando0906** [TrinityCore/TrinityCore#29446]
### Description

C:\Users\Ry\Desktop\bfa try2\BfaCore-Reforged\src\server\database\Database\DatabaseWorkerPool.cpp:59 in DatabaseWorkerPool<class WorldDatabaseConnection>::DatabaseWorkerPool FATAL ERROR:
  Used MySQL library version (5.6.51) does not match the version used to compile BfaCore (8.0.34). Search on forum for TCE00011.

### SQL fix

```sql
DatabaseWorkerPool<T>::DatabaseWorkerPool()
    : _queue(new ProducerConsumerQueue<SQLOperation*>()),
      _async_threads(0), _synch_threads(0)
{
    WPFatal(mysql_thread_safe(), "Used MySQL library isn't thread-safe.");
    WPFatal(mysql_get_client_version() >= MIN_MYSQL_CLIENT_VERSION, "BfaCore does not support MySQL versions below 5.1");
    WPFatal(mysql_get_client_version() == MYSQL_VERSION_ID, "Used MySQL library version (%s) does not match the version used to compile BfaCore (%s). Search on forum for TCE00011.",
        mysql_get_client_info(), MYSQL_SERVER_VERSION);
}
```

### Branch

3.3.5

### TC rev. hash/commit

C:\Users\Ry\Desktop\bfa try2\BfaCore-Reforged\src\server\database\Database\DatabaseWorkerPool.cpp:59 in DatabaseWorkerPool<class WorldDatabaseConnection>::DatabaseWorkerPool FATAL ERROR:
  Used MySQL library version (5.6.51) does not match the version used to compile BfaCore (8.0.34). Search on forum for TCE00011.

**Comment by Aokromes** [comment]
you are using a diferent project.
BfaCore

**Comment by Ryanfernando0906** [comment]
It's the same problem that I've seen here on the Trinitycore forum, I would like some way to fix this and be able to play, I get this error when I run the bnet executable and worldserver.exe

**Comment by acidmanifesto** [comment]
Compile your own and not use a repack. Do not be lazy and use a repack then copy over a new compile to it.

The error message says:
Used MySQL library version (5.6.51) does not match the version used to compile BfaCore (8.0.34). Search on forum for TCE00011.

Your repack is using mysql 5.6.51 (seriously depteciated by the way), and your new binaries are built using mysql 8.0.34. That is why u are getting a version mix match.

**Comment by Ryanfernando0906** [comment]
I'm sorry I'm still new to this world but I wanted to play BFA so much but unfortunately I'm having these problems I'm going to try now to make it work, unfortunately I don't have that much knowledge I just watched videos on YouTube
