### ISSUE TITLE
BUG Island of the Exiles 

### ISSUE THREAD

**Issue by Treffnix83** [TrinityCore/TrinityCore#29442]
### Description

Hello

I have a bug with:

Island of the Exiles

Quests from NPC Warlord Breka Grimmaxt

From then on you can't go any further, no more quests and I'm stuck on the island.

I use the latest Trinitycore version including updates.

Hallo 

Ich habe einen Bug bei: 

Insel der Verbannten 

Quests ab NPC Kriegsherrin Breka Grimmaxt

ab da kommt man nicht mehr weiter keine Quests mehr und ich sitze auf der Insel fest.

Ich nutze die Aktuellste Trinitycore version inkl updates.

### Expected behaviour

QUEST

### Steps to reproduce the problem

New Character

### Branch

master

### TC rev. hash/commit

was ?

### Operating system

Windows Server 2022

### Custom changes

nop

**Comment by Aokromes** [comment]
duplicate.
