### ISSUE TITLE
Divine Shield does not cause line of sight pull

### ISSUE THREAD

**Issue by dewmguy** [TrinityCore/TrinityCore#29464]
### Description

When you cast divine shield, ranged mobs continue to try to throw or cast spells at you. 

### Expected behaviour

Original gameplay would compel ranged mobs to give up their ranged attacks for melee instead, forcing them to stack up, like a LOS pull would.

wotlk classic in-game video
https://streamable.com/m9zsy4

### Steps to reproduce the problem

pull a spellcaster or ranged attacker, run any distance away, cast divine shield

wotlk tc in-game video
https://streamable.com/v15q20

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. d5b64a0bb23c 2023-10-18 20:21:53 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04 Server / Windows 11 Client

### Custom changes

None

**Comment by dewmguy** [comment]
wotlk classic in-game video
https://streamable.com/m9zsy4

**Comment by Shauren** [comment]
Don't duplicate issues

**Comment by dewmguy** [comment]
forgive me but we're talking about two different spells. am i wrong?

**Comment by Shauren** [comment]
No, we are talking about the same mechanic here, interrupting ranged autorepeat spell on immunity
