### ISSUE TITLE
RC4 int failed

### ISSUE THREAD

**Issue by njikmf** [TrinityCore/TrinityCore#29467]
### Description

WorldServer exited with ASSERTION fail when logged in account.

Starting Arena Season...
Starting Battleground System
>> Loaded 11 battlegrounds in 1 ms
Starting Outdoor PvP System
>> Loaded 6 outdoor PvP definitions in 1 ms
Starting Battlefield System
>> Loaded 1 battlefields in 389 ms
Loading Transports...
>> Spawned 20 continent transports in 534 ms
Loading Warden Checks...
Loading Warden Action Overrides...
Deleting expired bans...
Initializing quest reset times...
Calculate random battleground reset time...
Calculate deletion of old calendar events time...
Calculate guild limitation(s) reset time...
World initialized in 0 minutes 54 seconds
Starting up anti-freeze thread (60 seconds max stuck time)...
**src\common\Cryptography\ARC4.cpp:31 in Trinity::Crypto::ARC4::ARC4 ASSERTION FAILED:
  result == 1**

```
Trinity::Crypto::ARC4::ARC4() : _ctx(EVP_CIPHER_CTX_new())
{
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
    _cipher = EVP_CIPHER_fetch(nullptr, "RC4", nullptr);    --------------->cipher is null, but I don't know why
#else
    EVP_CIPHER const* _cipher = EVP_rc4();
#endif

    EVP_CIPHER_CTX_init(_ctx);
    int result = EVP_EncryptInit_ex(_ctx, _cipher, nullptr, nullptr, nullptr);
    ASSERT(result == 1);
}
```

### Expected behaviour

Can enter game

### Steps to reproduce the problem

Compile latest 335 source, then log in account.
Environment:
mysql-8.0.35-winx64
Win64OpenSSL-3_0_12
Win10 x64

### Branch

3.3.5

### TC rev. hash/commit

c18d0000e8468ce89e46db510778f5ba00541555

### Operating system

Win10 x64 server

### Custom changes

None

**Comment by Aokromes** [comment]
read wiki. you missed to copy a file.
