### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by nbyaya** [TrinityCore/TrinityCore#29472]
### Description

https://gist.github.com/nbyaya/ea059035bcb67974b0291cea5d81d3d3

### Expected behaviour

The server should not go down

### Steps to reproduce the problem

It runs normally under WIN10 system, but SERVER2016 or SERVER2012 cannot start the server.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commits/master

### Operating system

Server 2012 R2

### Custom changes

None

**Comment by jackpoz** [comment]
As by Microsoft documentation at https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2 , Windows Server 2012 R2 reached End Of Life on the 10th of October 2023, 1 month ago at the time of writing.

**Comment by Shauren** [comment]
Windows Server 2012 is completely unsupported

Minumum version is Windows 10 update 1903 (or its Server 2016 equivalent), 1607 or 1809 LTSC versions will not work

**Comment by nbyaya** [comment]
Thanks, I understand. I have also tested SERVER2016 and it does not support it~

**Comment by nbyaya** [comment]
The main reason is that I have been running under the SERVER2012 R2 version before version 10.2, and everything is normal ~

**Comment by Aokromes** [comment]
why you use such old oss? if it needs windows 10 1903 equivalent of windows server you will need windows server 2019
