### ISSUE TITLE
DB/Quest: make Blessing of Zim'Torga / Zim'Rhuk repeatables

### ISSUE THREAD

**Issue by Jildor** [TrinityCore/TrinityCore#29471]
### Description

Quest The Blessing of Zim'Torga: https://aowow.trinitycore.info/?quest=12615 (reward exp)
Opens Quest Blessing of Zim'Torga: https://aowow.trinitycore.info/?quest=12618 (not reward exp)

Quest The Blessing of Zim'Rhuk: https://aowow.trinitycore.info/?quest=12655 (reward exp)
Opens Quest Blessing of Zim'Rhuk: https://aowow.trinitycore.info/?quest=12656 (not reward exp)

both open quests (https://aowow.trinitycore.info/?quest=12618 and https://aowow.trinitycore.info/?quest=12656) should be repeatables in order to obtain the blessing reward aura.

the other quest: Blessing of Zim'Abwa (https://aowow.trinitycore.info/?quest=12567) added repeatable flag here: https://github.com/TrinityCore/TrinityCore/commit/bb4efd78d54a6030850db87d33b017d0b628056c

### SQL fix

```sql
--
UPDATE `quest_template_addon` SET `SpecialFlags`=1 WHERE `ID` IN (12618,12656);
```

### Branch

3.3.5

### TC rev. hash/commit

33bc42b6462aec38097430482dae1f0abb937a3d

**Comment by CraftedRO** [comment]
This also can be merged since it's state even on wowhead that both are repeatable
https://www.wowhead.com/wotlk/quest=12618/blessing-of-zimtorga
https://www.wowhead.com/wotlk/quest=12656/blessing-of-zimrhuk
