### ISSUE TITLE
Naked Kul tiras Character in Character Selection Screen

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29481]
### Description

<img width="842" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/8d1a19c6-60a8-4321-a450-c4163c8fea3b">

The Char is straight.. a bit naked in the Char selection screen :D

### Expected behaviour

Give him clothes! ;D

### Steps to reproduce the problem

Create a Kul Tiras Character

### Branch

master

### TC rev. hash/commit

1f7ee02defd7df02a045ecabef79e1c558bf3cec

### Operating system

Windows Server 2022

### Custom changes

Some added Spawns

**Comment by Naddley** [comment]
I cant reproduce this. Are you sure your db2 files are not corrupted/updated?

**Comment by coreretail6** [comment]
newest db2 files fixed it
