### ISSUE TITLE
Kurtok the Slayer should have text when entering combat and on death

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29505]
### Description

Kurtok the Slayer should have text when entering combat and on death. No Broadcast Ids sent.

### SQL fix

```sql
-- Kurtok the Slayer SAI
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=42938;
DELETE FROM `smart_scripts` WHERE `entryorguid`=42938 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(42938,0,0,0,4,0,100,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Kurtok the Slayer - On Aggro - Say text 0'),
(42938,0,1,0,6,0,100,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Kurtok the Slayer - On Death - Say text 1');

DELETE FROM `creature_text` WHERE `CreatureID`=42938;
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(42938, 0, 0, 'Alliance weakling, your lands will burn!', 12, 0, 100, 5, 0, 0, @BCTEXTID, 0, 'Kurtok the Slayer'),
(42938, 1, 0, 'The Blackrock Clan will end you...', 12, 0, 100, 0, 0, 0, @BCTEXTID+1, 0, 'Kurtok the Slayer');
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 2a7f55fd17cf+ 2023-12-19 11:36:01 -0400 (combat-training branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1u  30 May 2023 (library: OpenSSL 1.1.1u  30 May 2023)
Using Boost version: 1.78.0
Using MySQL version: 80033
Using CMake version: 3.28.0-rc5
Compiled on: Windows
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by Naddley** [comment]
missing BroadcastTextId

**Comment by malcrom** [comment]
None in sniff none in hotfixes.

**Comment by malcrom** [comment]
Updated to add missing Broadcasttext
