### ISSUE TITLE
Druid Forms won´t change after Barber Customisation

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29518]
### Description

Druid Forms are not changeable on barber (even on unlocked forms)
![image](https://github.com/TrinityCore/TrinityCore/assets/132657906/70f56d0d-5f5a-4754-9453-79a9710b0fe6)

![image](https://github.com/TrinityCore/TrinityCore/assets/132657906/4b79e67d-e5bd-4e23-8780-d189687727d4)

### Expected behaviour

After Accepting the Change, the Druid Form should be changed when entering the form.

### Steps to reproduce the problem

Create a Druid
Visit a Barber
Try to change the Bear Form

### Branch

master

### TC rev. hash/commit

a24e3a9511d8b60baf51a4e81aa3e4731746ffe4

### Operating system

Windows Server 2022

### Custom changes

Some custom Spawns

**Comment by Naddley** [comment]
duplicate: https://github.com/TrinityCore/TrinityCore/issues/29429
