### ISSUE TITLE
Player::BuyItemFromVendorSlot Prevents Valid CMSG_BUY_ITEM_IN_SLOT Handling

### ISSUE THREAD

**Issue by HelloKitty** [TrinityCore/TrinityCore#29510]
### Description

When the client sends CMSG_BUY_ITEM_IN_SLOT for the base/default/null bag in the last few slots it will fail to purchase the item. This packet is triggered by left-click dragging a merchant item into the bag.

This is because of the following incorrect validation logic in Player::BuyItemFromVendorSlot:

```    // cheating attempt
    if (slot > MAX_BAG_SIZE && slot != NULL_SLOT)
        return false;
```

Basically, the client is sending INVENTORY_SLOT_ITEM_END - 1 for the last slot and this seems to be out of range with this check but isn't. Only noticed this by accident while implementing the vendor window and packets from scratch in a new client. Happy I misclicked!

For anyone who wants an example: https://i.imgur.com/GBiTSrS.mp4

### Expected behaviour

The client should be able to buy items in the last few slots of the default bag.

### Steps to reproduce the problem

1. Go to a vendor
2. Right-click drag an item into the last slot of the base/default/null bag to try to buy it
3. Observe that the item isn't purchased

### Branch

3.3.5

### TC rev. hash/commit

Custom fork

### Operating system

Windows 10 x64

### Custom changes

Many

**Comment by acidmanifesto** [comment]
Im able to replicate the issue that is shown in the video on a clean 335. Good find.
