### ISSUE TITLE
Crash of the game client after logging into the world

### ISSUE THREAD

**Issue by shamage** [TrinityCore/TrinityCore#29512]
### Description

The game client crashes for this version of the release. (see the picture with the description of the fall error )
![Ashampoo_Snap_štvrtok 21  decembra 2023_21h6m52s](https://github.com/TrinityCore/TrinityCore/assets/7515044/1a32f69f-5bdb-4719-b3fd-04f76ce57620)
![Ashampoo_Snap_štvrtok 21  decembra 2023_23h33m50s](https://github.com/TrinityCore/TrinityCore/assets/7515044/2fdafbfa-9570-445c-a3b2-c1c5d9cf8799)

### Expected behaviour

Logging into the game should be without client error message

### Steps to reproduce the problem

1. launch world + auth
2. log in with the game client
3. choose your character
4. start logging into the world ( enter the world ) 
5. watch how they don't have time to load the NPC and the game immediately reports an error
6. worldserver.exe + auth.exe continues to work without any crash or error message
![Ashampoo_Snap_štvrtok 21  decembra 2023_23h47m18s](https://github.com/TrinityCore/TrinityCore/assets/7515044/39bc2021-052f-4b89-ace3-5bad45908352)

### Branch

master

### TC rev. hash/commit

TrinityCore rev. dc881c94e198 2023-12-21 09:08:47 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win 10 Pro

### Custom changes

none

**Comment by Shauren** [comment]
Update launcher

**Comment by Fabi** [comment]
https://github.com/Arctium/WoW-Launcher/discussions/48
