### ISSUE TITLE
Client crash on spawn in

### ISSUE THREAD

**Issue by smeadows0155** [TrinityCore/TrinityCore#29514]
### Description

I have the exact same issue as shamage https://github.com/TrinityCore/TrinityCore/issues/29512.
I am using the latest launcher signed on 2023-12-02.

### Expected behaviour

Normal game launch as before the update

### Steps to reproduce the problem

1. Updated and rebuilt TrinityCore (on 12/21/2023 using TDB1020.23111 for DB).
2. Update client to 52649.
3. Start Bnet & World Server
4. Launch client with launcher (latest release)

### Branch

master

### TC rev. hash/commit

dc881c94e198 2023-12-21 09:08:47 +0100 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11 X64

### Custom changes

None

**Comment by Fabi** [comment]
https://discord.com/channels/376073286427344897/376457124726702080/1187422245233106974
