### ISSUE TITLE
Quest 24471 "Aid for the Wounded" in Coldridge Valley not playing script due to missing condition

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29520]
### Description

The quest is completable but the Wounded Coldridge Mountaineer should play a c++ script after hit by spell.

Added extra check to prevent casting second time on same npc.

### SQL fix

```sql
-- Condition for source Spell implicit target condition type Object entry guid
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceGroup`=1 AND `SourceEntry`=69855 AND `SourceId`=0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 1, 69855, 0, 0, 31, 0, 3, 37080, 0, 0, 0, 0, '', 'Spell Heal Wounded Mountaineer (effect 0) will hit the potential target of the spell if target is unit Wounded Coldridge Mountaineer.');
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. a11c34979093+ 2023-12-22 16:29:26 -0400 (ColdridgeValley branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1u  30 May 2023 (library: OpenSSL 1.1.1u  30 May 2023)
Using Boost version: 1.78.0
Using MySQL version: 80033
Using CMake version: 3.28.0-rc5
Compiled on: Windows 10.0.19045
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by Naddley** [comment]
The "stand state" conditions seems to be the wrong way. 
On Retail its not possible to even start the spellcast on a allready healed one.
With this condition you can cast the spell but you will get an error after spellcast is finished which is not the same behaviour as on Retail.

**Comment by malcrom** [comment]
I can't condition the item only the spell.

**Comment by mdX7** [comment]
9e22f4fa535d3c26fcb2a6ef7b8e923002f14d26
