### ISSUE TITLE
Make winged ghost" fly Deathknell Graveyard

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29528]
### Description

Still an issue with one caused by SAI.

### SQL fix

```sql
-- Make winged ghost" fly Deathknell Graveyard
DELETE FROM `creature_template_movement` WHERE `CreatureId` IN (49044,49128,50372);
INSERT INTO `creature_template_movement` (`CreatureId`,`Ground`,`Swim`,`Flight`,`Rooted`,`Chase`,`Random`,`InteractionPauseTimer`) VALUES
(49044,0,0,1,0,0,0,0),
(49128,0,0,1,0,0,0,0),
(50372,0,0,1,0,0,0,0); -- SAI keeping her in the ground
```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. c5fcdd4f73ba+ 2023-12-24 21:14:08 -0400 (Hunter-Training branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1u  30 May 2023 (library: OpenSSL 1.1.1u  30 May 2023)
Using Boost version: 1.78.0
Using MySQL version: 80033
Using CMake version: 3.28.0-rc5
Compiled on: Windows
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by Naddley** [comment]
this "keeping it to the ground" is not caused by the SAI.
Its caused by a wrong path.
