### ISSUE TITLE
Core/Server: Client crashes when I log in

### ISSUE THREAD

**Issue by Belitharian** [TrinityCore/TrinityCore#29536]
### Description

Good day everyone,

When I try to login the game crashes (Wow Error) and the following error is printed in _WorldServer.exe_ :
> [Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1718765138 })

More details on the gist, not sure if this error is harmless or not.

Logs:
https://gist.github.com/Belitharian/fd70b6767ea6368d964b3228904c5e05

Misc:
WoW DF 10.2.0.52649 (Locale: FR)
Forked from TrinityCore repo (master branch)
Last merge from commit 8f354b54

Ask me if you need any information 😃 

### Expected behaviour

The player can login without error or crash.

### Steps to reproduce the problem

- Use an account that was working ;
- Log in with this account ;
- Observe the crash / error.

### Branch

master

### TC rev. hash/commit

> TrinityCore rev. e00a6d3fe537+ 2023-12-28 00:00:27 +0100 (master branch) (Win64, RelWithDebInfo, Static)
> Using SSL version: OpenSSL 1.1.1l  24 Aug 2021 (library: OpenSSL 1.1.1l  24 Aug 2021)
> Using Boost version: 1.78.0
> Using MySQL version: 50736
> Using CMake version: 3.24.3
> Compiled on: Windows 10.0.22621
> Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
> Worldserver listening connections on port 8085
> Realmlist (Realm Id: 1) configured in port 8085
> VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
> MMAPs status: Enabled
> maps directory located in ./maps. Total size: 1998870025 bytes
> vmaps directory located in ./vmaps. Total size: 3831208984 bytes
> mmaps directory located in ./mmaps. Total size: 13852517164 bytes
> Using frFR DBC Locale as default. All available DBC locales: frFR
> Using World DB: TDB 1020.23111
> LoginDatabase queue size: 0
> CharacterDatabase queue size: 0
> WorldDatabase queue size: 0

### Operating system

Windows 10 x64 10.0.22621

### Custom changes

Custom maps
Custom scripts

**Comment by Shauren** [comment]
https://github.com/Arctium/WoW-Launcher/discussions/48
