### ISSUE TITLE
Client crash after loading screen

### ISSUE THREAD

**Issue by Shavo85** [TrinityCore/TrinityCore#29561]
### Description

After updating and compiling the server core, client constantly crashes after loading the character
nothing else changed since previous working version, just updated the server via github
starting client via arctium custom server launcher(prev. working version)

crash log from client:
=============================================================================
World of Warcraft: Retail Build (build 52649)

Exe:      E:\Games\World of Warcraft\_retail_\Wow.exe
Command:  "E:/Games/World of Warcraft/_retail_//Wow.exe"  -config Config.wtf
Time:     Jan  6, 2024  5:09:43.975 AM
User:     Shavo
Computer: SHAVO
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal exception!

Program:	E:\Games\World of Warcraft\_retail_\Wow.exe
ProcessID:	15564
ThreadID:	15436
Exception:	0xC000001D (ILLEGAL_INSTRUCTION) at 00007ff68b2714a8

<Exception.IssueType> Exception
<ExceptionType> Ignore
<Exception.Summary:>
0xC000001D (ILLEGAL_INSTRUCTION) at 00007ff68b2714a8
(DBG-OPTIONS<FunctionsOnly SingleLine> DBG-ADDR<00007ff68b2714a8>("Wow.exe") <- DBG-ADDR<00007ff6898e0714>("Wow.exe") <- DBG-ADDR<00007ff6898d3cca>("Wow.exe") DBG-OPTIONS<>)
<:Exception.Summary>
<Exception.Assertion:>
DBG-ADDR<00007ff68b2714a8>("Wow.exe")
DBG-ADDR<00007ff6898e0714>("Wow.exe")
DBG-ADDR<00007ff6898d3cca>("Wow.exe")
DBG-ADDR<00007ff6898d165a>("Wow.exe")
DBG-ADDR<00007ff6898d1623>("Wow.exe")
<:Exception.Assertion>
<Exception.HashBlock:>
DBG-OPTIONS<NoImage NoAddress NoFileLine NoFuncOffset NoDbgAddr>
ERROR #132 - 0xC000001D
DBG-ADDR<00007ff68b2714a8>("Wow.exe")
DBG-ADDR<00007ff6898e0714>("Wow.exe")
DBG-ADDR<00007ff6898d3cca>("Wow.exe")
DBG-ADDR<00007ff6898d165a>("Wow.exe")
DBG-ADDR<00007ff6898d1623>("Wow.exe")
DBG-OPTIONS<>
<:Exception.HashBlock>
<ErrorDescription> 
<EstimatedTrace> No

<Version> 10.2.0.52649
<Config> Retail
<Jira.JiraProjectId> 11503
<Jira.JiraProjectKey> WOW10
<Exception.ProjectId> 10
<Exception.BuildNumber> 52649
<Exception.Branch> 10.2.0
<WowProject> Mainline
<Application> World of Warcraft
<ApplicationType> Client
Type: WoW
<Executable> Wow.exe
Executable UUID: 1E079D9E-445D-42FD-8764-C257640D9453
<Wow.Platform> X64
<Exception.Platform> Win 11 (x86 64-bit)
User: Shavo
Computer: SHAVO
Virtual Memory: 0.00 MB
Free Disk Space: 26.94 GB
Exe Built: Dec 19 2023 16:27:12
<InitFlags> 0000007F 00001FFF 00000400
App Up Time: 0 days, 0 hours, 1 minutes, 4 seconds
System Up Time: 0 days, 10 hours, 16 minutes, 52 seconds
<TimingMethod> QueryPerformanceCounter
Current Frame: 477
Current Time: 37012211
Current Tick: 125
<SystemResumes> 0
<CharLogins> 1
Number of thread pool threads: 6/6/6 (High/Mid/Low)
<LauncherName> Arctium WoW Launcher.exe
<Locale.Text> enUS
<Locale.Audio> enUS
Session Time(hh:mm:ss): 00:00:51
<SessionTime.Grouping> 00:00:00 - 00:14:59
Time in World(hh:mm:ss): 00:00:38
<TimeInWorld.Grouping> 00:00:00 - 00:14:59
Total Time in World(hh:mm:ss): 00:00:38
<TotalTimeInWorld.Grouping> 00:00:00 - 00:14:59
Total lua memory: 138468KB

Server log at char loading:

Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BA (14010)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PRODUCT_LIST 0x36B9 (14009)] from [Player: Account: 1]
Received not handled opcode [CMSG_UPDATE_VAS_PURCHASE_STATES 0x36F1 (14065)] from [Player: Account: 1]
[Player: Account: 1] Client tried to call not implemented method ResourcesService.GetContentHandle({ program: 16974 stream: 1634756212 version: 1701729619 })
Received not handled opcode [CMSG_GET_ACCOUNT_CHARACTER_LIST 0x36B4 (14004)] from [Player: Account: 1]
Received not handled opcode [CMSG_GET_RAF_ACCOUNT_INFO 0x3721 (14113)] from [Player: Account: 1]
Received not handled opcode [CMSG_GET_REMAINING_GAME_TIME 0x36E9 (14057)] from [Player: Account: 1]
Received not handled opcode [CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS 0x3704 (14084)] from [Player: Account: 1]
Received not handled opcode [CMSG_SET_EXCLUDED_CHAT_CENSOR_SOURCES 0x3705 (14085)] from [Player: Account: 1]
Received not handled opcode [CMSG_BATTLE_PAY_GET_PURCHASE_LIST 0x36BA (14010)] from [Player: Account: 1]
Received not handled opcode [CMSG_REQUEST_MYTHIC_PLUS_SEASON_DATA 0x3207 (12807)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_OPEN_TRADESKILL_NPC 0x3328 (13096)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_REQUEST_WEEKLY_REWARDS 0x33BD (13245)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_SET_EMPOWER_MIN_HOLD_STAGE_PERCENT 0x3282 (12930)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_OVERRIDE_SCREEN_FLASH 0x352F (13615)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_CONTRIBUTION_LAST_UPDATE_REQUEST 0x356F (13679)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_CONTRIBUTION_LAST_UPDATE_REQUEST 0x356F (13679)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_QUEUED_MESSAGES_END 0x376C (14188)] from [Player: Logging in: Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS 0x3704 (14084)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_SET_EXCLUDED_CHAT_CENSOR_SOURCES 0x3705 (14085)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_QUERY_COUNTDOWN_TIMER 0x31A8 (12712)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS 0x32D6 (13014)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_LFG_LIST_GET_STATUS 0x360C (13836)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_REQUEST_LFG_LIST_BLACKLIST 0x32C4 (12996)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_OPEN_TRADESKILL_NPC 0x3328 (13096)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_GET_LANDING_PAGE_SHIPMENTS 0x331F (13087)] from [Player: Picsa Player-1-00000002, Account: 1]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-49874-00000011E8
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-42218-00000011ED
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-49874-0000001251
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-49874-000000124C
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-49874-000000125E
Received not handled opcode [CMSG_MYTHIC_PLUS_REQUEST_MAP_STATS 0x308E (12430)] from [Player: Picsa Player-1-00000002, Account: 1]
Received not handled opcode [CMSG_MOVE_SET_TURN_RATE_CHEAT 0x3A06 (14854)] from [Player: Picsa Player-1-00000002, Account: 1]
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-42218-00000011ED
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-49871-000000128A
MoveSplineInitArgs::Validate: expression '_checkPathLengths()' failed for Creature-0-1-0-0-1642-00000011F4
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_SET_PCT_SPELL_MODIFIER 0x2C39 (11321)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_AURA_UPDATE 0x2C21 (11297)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_CANCEL_COMBAT 0x2947 (10567)] to non existent socket 0 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_CANCEL_COMBAT 0x2947 (10567)] to non existent socket 0 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_UPDATE_OBJECT 0x27C0 (10176)] to non existent socket 1 to [Player: Picsa Player-1-00000002, Account: 1]
Prevented sending of [SMSG_LOGOUT_COMPLETE 0x2681 (9857)] to non existent socket 0 to [Player: Account: 1]

### Expected behaviour

Client should not crash

### Steps to reproduce the problem

Start Client

### Branch

master

### TC rev. hash/commit

750b99fca0 ("DB/AreaTrigger: Fix id of 1e4e2d953a4546cfb7a5ad1265036778f7cfbd7d", 2024-01-05)

### Operating system

windows 11

### Custom changes

none

**Comment by Shavo85** [comment]
Reverted back to dc881c94e1 ("Update allowed build to 10.2.0.52649", 2023-12-21) commit,
the client still crashes, no modifications made to the computer since last working version

**Comment by mdX7** [comment]
https://github.com/Arctium/WoW-Launcher/discussions/48

**Comment by Shavo85** [comment]
Thanks i hope it works
