### ISSUE TITLE
Can't find TDB with structure for master branch

### ISSUE THREAD

**Issue by serifas** [TrinityCore/TrinityCore#29560]
### Description

I have been trying for a few hours to fix update errors when running trinitycore.
I only executed the latest tdb from here.
https://github.com/TrinityCore/TrinityCore/releases/tag/TDB1020.23111
I am on the current master rev 711e8a527c0ab589a37aad1468162bb783e29437
I am getting a massive amount of errors after executing in the hotfix and world db,
mostly from missing databases or columns.
I don't really know how to fix this, is there a revision I can use with that TDB to run client verion 10.2.0 (52649)?

### SQL fix

```sql
I havn't run any fixes
```

### Branch

master

### TC rev. hash/commit

I don't really know what to put here.

**Comment by Kelpiesklubhouse** [comment]
Have you tried using the automatic importing and not executing directly from the SQLs themselves?

**Comment by serifas** [comment]
trying this now. thanx I didn't know you could do that actually haha

**Comment by serifas** [comment]
still experiencing issues. I got the db to install but when I enter the game after I load in on a character the game crashes.
Is it possible my arctium launcher isn't compatable?

**Comment by Kelpiesklubhouse** [comment]
https://github.com/Arctium/WoW-Launcher/discussions/48
