### ISSUE TITLE
Gametables.cpp issue in wotlk_classic

### ISSUE THREAD

**Issue by Quest79** [TrinityCore/TrinityCore#29572]
### Description

Beginning initial launch of world to init db, an error pops up about GameTables causing a fatal error.

### Expected behaviour

On init launch of world, db should be established and applied like any other fresh server install of Trinity.

### Steps to reproduce the problem

1. Compile wotlk_classic
2. Get all files into build as needed like the 500 other times we've done this
3. config 
4. Extract all maps etc from fresh **_wotlk classic_** data files
5. launch world

Why are the only branch options master and 3.3.5 when we have well developed wotlk_classic build with an updated databse? 3.4.3
?

Image of the error itself:
![kzVVCHl 1](https://github.com/TrinityCore/TrinityCore/assets/635094/04c617e2-0dff-490b-87db-8aff9d923d5b)

### Branch

wotlk_classic

### TC rev. hash/commit

wotlk_classic latest branch [854aaeb](https://github.com/TrinityCore/TrinityCore/commit/854aaeb176080afaabfd5097b08d66a622879d1e)
TrinityCore rev. 854aaeb17608 2023-12-21 00:36:17 +0100 (wotlk_classic branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 11

### Custom changes

None

**Comment by Quest79** [comment]
Why is this labeled invalid as a 3rd party core? wotlk_classic is literally one of the major branches of Trinity downloaded directly from this repo and we even have database files in the releases?

**Comment by acidmanifesto** [comment]
> Why is this labeled invalid as a 3rd party core? wotlk_classic is literally one of the major branches of Trinity downloaded directly from this repo and we even have database files in the releases? 

Its a auto label due. You didnt provide a hash in your template

**Comment by Legoso** [comment]
@Quest79 : Edit your main post, fill in the section labeled "**TC rev. hash/commit**" with data from either a console `server debug` command or copy the header lines from a world/server.log file containing at least the commit hash, then save it. Not sure if it resets automatically or if someone has to do it manually, but that should be enough to remove your "invalid/incomplete/notTC" label.

**Comment by Quest79** [comment]
> @Quest79 : Edit your main post, fill in the section labeled "**TC rev. hash/commit**" with data from either a console `server debug` command or copy the header lines from a world/server.log file containing at least the commit hash, then save it. Not sure if it resets automatically or if someone has to do it manually, but that should be enough to remove your "invalid/incomplete/notTC" label.

The hash was in the edited comment before you posted this. Are you referring to something else?

**Comment by Legoso** [comment]
Anyway, seems less important now, since you did have readable commit hash in your worldserver console picture (just not detectable by the automated scripts in these TC github issue pages). Anyway, it has been followed up by funjoker, so it is way less important now. Not sure if my first comment was too late to be relevant, but it was meant to elaborate on the details why this issue page did not enter the correct green branch label at the time of creation.

**Comment by funjoker** [comment]
Fixed in 2a8f1feef6dfd585bec3e1232888fb0807fcaf12
