### ISSUE TITLE
Quest ID 59254 "Enhanced Combat Tactics": quest kills are not counted if using Shadow Word: Pain or Corruption

### ISSUE THREAD

**Issue by vegax87** [TrinityCore/TrinityCore#29574]
### Description

This is a tutorial quest where you have to attack Captain Garrick (https://www.wowhead.com/npc=164577/alliance-sparring-partner) 3 times in order to complete the quest, but some DoT skills such as Shadow Word: Pain and Corruption are not counted because in /scripts/ExilesReach/zone_exiles_reach.cpp  you see copy-pasted  `Aura* aura = me->GetAura(SPELL_MOONFIRE); ` instead of SPELL_SHADOW_WORD_PAIN or SPELL_CORRUPTION https://github.com/TrinityCore/TrinityCore/blob/2862086bcff0354c3588109dce1aaa22bc310162/src/server/scripts/ExilesReach/zone_exiles_reach.cpp#L2912

and https://github.com/TrinityCore/TrinityCore/blob/2862086bcff0354c3588109dce1aaa22bc310162/src/server/scripts/ExilesReach/zone_exiles_reach.cpp#L3179

### Expected behaviour

I should cast Shadow Word: Pain or Corruption, wait for DoT expiration and then it should confirm the kill count

### Steps to reproduce the problem

Quest ID:  https://www.wowhead.com/quest=59254/enhanced-combat-tactics
Quest NPC: https://www.wowhead.com/npc=164577/alliance-sparring-partner

1. Talk with Captain Garrick
2. Follow Captain Garrick
3. Start the fight
4. Cast Corruption (spell ID 172) or Shadow Word: Pain (spell ID: 589) and wait until DoT on Captain Garrick expires
5. Repeat 3 times to complete the quest

### Branch

master

### TC rev. hash/commit

2862086bcff0354c3588109dce1aaa22bc310162

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by malcrom** [comment]
It was working when I submitted the PR.
