### ISSUE TITLE
Worldserver hangs during DB updater on startup when installing new DB

### ISSUE THREAD

**Issue by Rochet2** [TrinityCore/TrinityCore#29599]
### Description

I have a CI which automatically downloads the latest DB, compiles the latest server, and then runs it with `yes | ./worldserver --update-databases-only` to create the DBs.

However, ever since https://github.com/TrinityCore/TrinityCore/commit/5c59e2a248c9b2132f4e863de56c981cfa83ec0b was introduced, the worldserver always hangs in the middle of running updates to the new DB.

See full code for CI [here](https://github.com/Rochet2/TrinityCore/blob/dd1bbefd4f433d3dd1bbb6253befc674d175ce4f/.github/workflows/merge.yml#L9-L109) - the run fails also for master branch which is clean TC.
Last successful run: https://github.com/Rochet2/TrinityCore/actions/runs/7216439883
First failing run: https://github.com/Rochet2/TrinityCore/actions/runs/7228600885
And has been failing ever since.

I dont have Ubuntu locally at the moment, so I have yet to debug the issue locally.

### Expected behaviour

Database should populate and update successfully without hanging.

### Steps to reproduce the problem

1. Clone TC 5cc1b97fc143 on Ubuntu 22.04.3, 64-bit
2. Compile it with `cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15`
3. Download and extract TDB_1020.23111_2023_11_15 to the server folder
4. Run worldserver with `yes | ./worldserver --update-databases-only` to create the DBs
5. observe the server to hang during the DB updates

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 5cc1b97fc143 2024-01-18 00:31:57 +0100 (master branch) (Unix, Debug, Dynamic) (worldserver-daemon)

### Operating system

Ubuntu 22.04.3, 64-bit

### Custom changes

None

**Comment by Ovahlord** [comment]
did you check if your mysql server just didn't die while applying?

**Comment by jackpoz** [comment]
I guess we'll check next TDB release

**Comment by Rochet2** [comment]
> did you check if your mysql server just didn't die while applying?

The following code keeps printing successfully, so I am pretty sure the DB is on and fine.
```
while true; do MYSQL_USER="root" MYSQL_DATABASE="world" && (sudo systemctl status mysql; ps aux | grep mysql; sudo netstat -tuln | grep 3306; (mysql -u "$MYSQL_USER" -p -e "USE $MYSQL_DATABASE; SHOW TABLES;" || true)); sleep 5; done &
```

The updates themselves are fine, the SQL files are probably not the issue as its not a specific SQL that the updates stop on.

The server code is most likely the issue from my point of view, since I see that the commit prior to the failure changed DB connection code and there were some hangs fixed in commits after that.
