### ISSUE TITLE
Gilneas Crows Merchant Square

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29594]
### Description

Crows should fly away on go trigger spell.

### SQL fix

```sql

```

### Branch

master

### TC rev. hash/commit

TrinityCore rev. ba627c1d1c42+ 2024-01-16 23:49:03 +0100 (Gilneas branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1u  30 May 2023 (library: OpenSSL 1.1.1u  30 May 2023)
Using Boost version: 1.78.0
Using MySQL version: 80033
Using CMake version: 3.28.0-rc5
Compiled on: Windows 10.0.19045
Automatic database updates are enabled for the following databases: Auth, Characters, World, Hotfixes
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled

**Comment by Ovahlord** [comment]
You forgot so set the Hover animtier on these crows. They do play the hover animation before flying away

**Comment by malcrom** [comment]
Naw they chnage stand state. testing.

**Comment by malcrom** [comment]
So this simple cosmetic fix will sit here forever?

**Comment by funjoker** [comment]
just no time to do anything atm on my side
