### ISSUE TITLE
Autologout/ Session crash after entering World with unknown/incorrect configured spawns

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29607]
### Description

I have a really strange client behavior. I spawned some custom spawns  of objects/creatures from some sniffs (Valdrakken 10.0.2 for example) and if the client try to render the unknown one, the session kicked me out into login screen. The server don´t crash. from TC 9.X.X-> 10.2.0 i didnt got this issue. What are the best worldserverconfig. settings for logs to see the crashy/buggy spawns ? Thanks for some hints :-)

### Expected behaviour

Don´t kick me mout :D 

### Steps to reproduce the problem

unsupported combination of model/template/aura ?

### Branch

master

### TC rev. hash/commit

c4a03b99315617f7f08b151bffaf3bf14dc238c2

### Operating system

Windows Server 2022

### Custom changes

some custom spawns from sniffs

**Comment by mdX7** [comment]
We need a bit more info here, like which creature or gameobject is causing it?

**Comment by coreretail6** [comment]
i know but i need to know how to find out the npcs. can i provide some debug dumps? Does the Debug Version create dumps of the session automaticly ?

**Comment by Aokromes** [comment]
the client crashes is because invalid (missing) model id.

**Comment by coreretail6** [comment]
Thanks you ! and how can i find out which modelid it is ? Is there a debug/log setting which gives output ? it crazy, that the client kicked me out of the session, cause of this. in older versions the model just wasnt spawned.

**Comment by jackpoz** [comment]
Is worldserver crashing or you just get kicked but can login right away ?

**Comment by coreretail6** [comment]
just kicked out of the session

**Comment by Aokromes** [comment]
> Thanks you ! and how can i find out which modelid it is ? Is there a debug/log setting which gives output ? it crazy, that the client kicked me out of the session, cause of this. in older versions the model just wasnt spawned.

you will see a mountain of startup errors related to model id

**Comment by jackpoz** [comment]
is this for a repack btw ?

**Comment by coreretail6** [comment]
this is a bugreport to help. 
I cleaned the crashy modelids and still get kicked.  But i figure out, that an areatrigger with a SmartAreaTriggerAI -> smartscript. with eventtype 46/ actiontype 1/ targettype 10 will kick me out.

Here is a  quickn dirty template for testing:
SET @entry := XXX;
SET @guid :=  XXX;
SET @areatrigger := 'XXX';
SET @map := XXX;
SET @xachse := XXX;
SET @yachse := XXX;
SET @zachse := XXX;
SET @oache :=  XXX;
SET @text := 'I m a crashy text';

-- Add the text for the creature to say in the creature_text table
REPLACE INTO creature_text (CreatureID, GroupID, ID, TEXT, TYPE, LANGUAGE, Probability, Emote, Duration, Sound, SoundPlayType, BroadcastTextId, TextRange, COMMENT) 
VALUES(@entry,'0','0',@text,'12','0','100','0','0','0','0',@areatrigger,'0',''); 

REPLACE  INTO hotfixes.broadcast_text (`Text`, `Text1`, `ID`, `LanguageID`, `ConditionID`, `EmotesID`, `Flags`, `ChatBubbleDurationMs`, `VoiceOverPriorityID`, `SoundKitID1`, `SoundKitID2`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `VerifiedBuild`) 
VALUES(@text,@text,@areatrigger,'0','0','0','0','0','221970','0','0','0','0','0','4','0','0','1');


REPLACE INTO `areatrigger` (`SpawnId`, `AreaTriggerCreatePropertiesId`, `IsCustom`, `MapId`, `SpawnDifficulties`, `PosX`, `PosY`, `PosZ`, `Orientation`, `PhaseUseFlags`, `PhaseId`, `PhaseGroup`, `SpellForVisuals`, `ScriptName`, `Comment`, `VerifiedBuild`) 
VALUES(@areatrigger,@areatrigger,'1',@map,'0,1,2,3,4,6,7,8,9,10,12,14,18,23,33',@xachse,@yachse,@zachse,@oache,'1','0','0',NULL,'SmartAreaTriggerAI','0','0');

REPLACE INTO  `areatrigger_create_properties` (`Id`, `IsCustom`, `AreaTriggerId`, `IsAreatriggerCustom`, `Flags`, `MoveCurveId`, `ScaleCurveId`, `MorphCurveId`, `FacingCurveId`, `AnimId`, `AnimKitId`, `DecalPropertiesId`, `TimeToTarget`, `TimeToTargetScale`, `Shape`, `ShapeData0`, `ShapeData1`, `ShapeData2`, `ShapeData3`, `ShapeData4`, `ShapeData5`, `ShapeData6`, `ShapeData7`, `ScriptName`, `VerifiedBuild`) 
VALUES(@areatrigger,'1',@areatrigger,'1','0','0','0','0','0','-1','0','0','0','0','1','20','20','20','20','20','20','0','0','','0');

INSERT INTO `areatrigger_template` (`Id`, `IsCustom`, `Flags`, `VerifiedBuild`) 
VALUES(@areatrigger,'1','0','46924');

REPLACE INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, COMMENT)
VALUES (@areatrigger, 12, 3, 0, 46, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 10, @guid, @entry, 0);

**Comment by coreretail6** [comment]
Or should i create a new issue, cause this one was closed ?

**Comment by mdX7** [comment]
lmao

you used SMART_ACTION_TALK; areatriggers cannot talk.
The target you can specify here would be the target which would be used to resolve placeholders like class, race, name etc.
To make the areatrigger trigger talk on a unit via sai you would have to do something along SetData on creature and on the creature on set data talk.

**Comment by coreretail6** [comment]
I must correct this again, its not important which kind of areatrigger i spawned here. An Areatrigger for a KillCredit will kick me too. Here an Template for example:
SET @Credit :=  XXX;
SET @areatrigger := 'XXX';
SET @map := XXX;
SET @xachse := XXX;
SET @yachse := XXX;
SET @zachse := XXX;
SET @oache :=  XXX;

-- Add the text for the creature to say in the creature_text table

INSERT INTO `areatrigger` (`SpawnId`, `AreaTriggerCreatePropertiesId`, `IsCustom`, `MapId`, `SpawnDifficulties`, `PosX`, `PosY`, `PosZ`, `Orientation`, `PhaseUseFlags`, `PhaseId`, `PhaseGroup`, `SpellForVisuals`, `ScriptName`, `Comment`, `VerifiedBuild`) 
VALUES(@areatrigger,@areatrigger,'1',@map,'0,1,2,3,4,6,7,8,9,10,12,14,18,23,33',@xachse,@yachse,@zachse,@oache,'1','0','0',NULL,'SmartAreaTriggerAI','0','0');

INSERT INTO  `areatrigger_create_properties` (`Id`, `IsCustom`, `AreaTriggerId`, `IsAreatriggerCustom`, `Flags`, `MoveCurveId`, `ScaleCurveId`, `MorphCurveId`, `FacingCurveId`, `AnimId`, `AnimKitId`, `DecalPropertiesId`, `TimeToTarget`, `TimeToTargetScale`, `Shape`, `ShapeData0`, `ShapeData1`, `ShapeData2`, `ShapeData3`, `ShapeData4`, `ShapeData5`, `ShapeData6`, `ShapeData7`, `ScriptName`, `VerifiedBuild`) 
VALUES(@areatrigger,'1',@areatrigger,'1','0','0','0','0','0','-1','0','0','0','0','1','10','10','10','10','10','10','0','0','','0');

INSERT INTO `areatrigger_template` (`Id`, `IsCustom`, `Flags`, `VerifiedBuild`) 
VALUES(@areatrigger,'1','0','46924');

INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_X, target_y, target_z, target_o, COMMENT)
VALUES (@areatrigger, 12, 3, 0, 46, 0, 100, 0, 0, 0, 0, 0, 33, @Credit, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0);
