### ISSUE TITLE
Missing items in game (DB)

### ISSUE THREAD

**Issue by Aztec2012** [TrinityCore/TrinityCore#29608]
### Description

Missing items in game (DB).

Many items are missing from game db

### Expected behaviour

When trying to add some intems via .additem appearing error - invalid ID but ID is from Wowhead adn not wrong.

### Steps to reproduce the problem

Varians Blade https://www.wowhead.com/item=45899/monster-1h-sword-varians-blade
https://www.wowhead.com/item=191027/9-0-monster-bastion-weapon-polearm-agi
https://www.wowhead.com/item=191026/9-0-monster-bastion-weapon-polearm-agi#see-also

And many other

### Branch

master

### TC rev. hash/commit

master = 10.2.5.53040

### Operating system

Windows 11

### Custom changes

none

**Comment by Shauren** [comment]
They are not in game files, this is not a bug (ItemSparse.db2)

**Comment by Aztec2012** [comment]
> They are not in game files, this is not a bug (ItemSparse.db2)

But tey is on Wowhead. How Wowhead drings it to DB?
