### ISSUE TITLE
Gilneas Merchant Square cosmetic fixes

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29603]
### Description

Misc cosmetic updates for first phase.

### SQL fix

```sql

```

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/5cc1b97fc1430f07d8942ae9f87fd5ad9708db59 2024-01-18 00:31:57 +0100 (master branch) (Win64, Debug, Static)

**Comment by Legoso** [comment]
> ### Branch
> 3.3.5

I presume this should be master.

**Comment by malcrom** [comment]
i selected master when i post it.

**Comment by Legoso** [comment]
> i selected master when i post it.

Fair enough. Sometimes selection changes are triggered outside of our own control, mostly due to GUI sensitivity or minor bugs.

**Comment by malcrom** [comment]
I remember posting the SQL, setting to Master, getting hash from another issue, and then writing the Title and discription.
