### ISSUE TITLE
character customization issue

### ISSUE THREAD

**Issue by KKBa20** [TrinityCore/TrinityCore#29611]
### Description

When you add the achievements to unlock new skins and eye colours to your characters, you cannot apply them when you are at the barber shop in the capital cities. For example, I've tried unlocking the dark ranger skin for my hunter but when I arrive at the barber shop, I can't seem to apply it.

### Expected behaviour

When you apply and gain the achievement for a new skin or eye colour, you should be able to go to the barber shop and apply it to your character and use it.

### Steps to reproduce the problem

https://www.wowhead.com/achievement=15579/return-to-lordaeron
https://www.wowhead.com/achievement=18854/seeing-red
https://www.wowhead.com/achievement=13251/in-teldrassils-shadow

### Branch

master

### TC rev. hash/commit

.add achievement

### Operating system

Windows 11

### Custom changes

None.

**Comment by Naddley** [comment]
duplicate
