### ISSUE TITLE
sql error when starting worldserver after building just now

### ISSUE THREAD

**Issue by dewmguy** [TrinityCore/TrinityCore#29619]
### Description

ERROR 1060 (42S21) at line 1 in file: '/home/trinity/TrinityCore/sql/old/3.3.5a/auth/23061_2024_01_21/2023_11_21_00_auth.sql': Duplicate column name 'timezone_offset' Applying of file '/home/trinity/TrinityCore/sql/old/3.3.5a/auth/23061_2024_01_21/2023_11_21_00_auth.sql' to database 'trinity_realm' failed! If you are a user, please pull the latest revision from the repository.

I've never encountered an error like this before. I have never manually applied sql patches to the database.

I sometimes have issues performing a normal update: cd TrinityCore/ && git pull && cd build/ && cmake ../ -DCMAKE_INSTALL_PREFIX=/home/trinity/server && make -j $(nproc) install

So I did a forced update: rm -r -f TrinityCore/ && git clone -b 3.3.5 https://github.com/TrinityCore/TrinityCore.git && cd TrinityCore/ && mkdir build && cd build/ && cmake ../ -DCMAKE_INSTALL_PREFIX=/home/trinity/server && make -j $(nproc) install

I have done this in the past frequently with no issues. I'm not sure what could have gone wrong.

How do I pull the latest revision from the repository?

### Expected behaviour

n/a

### Steps to reproduce the problem

n/a

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 420cbd7396ca 2024-01-24 21:09:01 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Ubuntu 22.04 Server / Windows 11 Client

### Custom changes

None

**Comment by CraftedRO** [comment]
this usually happen if you already have (applied) that [update](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/old/3.3.5a/auth/23061_2024_01_21/2023_11_21_00_auth.sql) in your auth database and the query is not re-runnable, but usually there shoud be a hash thing that tells to server to not reapply same updates.

**Comment by dewmguy** [comment]
I’m not sure what I should do.

**Comment by Ovahlord** [comment]
For starters, delete your auth database and let the updater of the worldserver take care of everything. Do not apply updates by hand.

**Comment by dewmguy** [comment]
> I have never manually applied sql patches to the database.

this is not a lie

**Comment by dewmguy** [comment]
I was lucky and had a backup of my auth table from last week. i imported and it started up just fine. i'm not sure what could have happened between then and now.
