### ISSUE TITLE
Unable to show the UIMap of Dragon Isle Unable to show the FlightMaster-Map 

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29620]
### Description

When you klick a Flightmaster in BelAmeth or try to open just the Map with "M" Key. Its just show the Map of Azeroth.

<img width="731" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/3a76bd89-2492-45b7-aab1-8f11420a8b7a">

<img width="1287" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/107abc76-bd7d-4bdd-a4ef-5a5875206f41">

Valdrakken FlightMaster:
<img width="1492" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/c3e26943-edc3-4685-bdf5-357a721a2259">

### Expected behaviour

Show the correct UI Map 

### Steps to reproduce the problem

Go to BelAmeth (Dragon Isles) and try to open the Map

### Branch

master

### TC rev. hash/commit

801b02bd529ab88bac8539bbcd0fc854b507f298

### Operating system

Windows Server 2022

### Custom changes

some custom spawns

**Comment by Naddley** [comment]
did you setup correctly the terrain swap? 
did you checked sniffs how the worldmap change is done? Bel´Ameth is not active by default on Retail.

**Comment by coreretail6** [comment]
I swapped nothing over the Dragon Isles. Bel'Ameth is in default on the map 2444

**Comment by coreretail6** [comment]
No i got no sniff of BelAmeth

**Comment by V-Cyberpunk** [comment]
dragon isles map in general isn't show correctly currently. no hovering effect and no map if clicked on dragon isles.

**Comment by coreretail6** [comment]
FYI: Even the Valdrakken Flight Master is broken :D
<img width="1492" alt="image" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/296000c2-ac9d-4e2e-8571-7235885cdd6f">

**Comment by shamage** [comment]
According to what you describe, there is no problem for me - I tried to create an NPC in the position as indicated in the picture. I suppose I'm in the right place. You can see the result in my pictures:

![Ashampoo_Snap_sobota 27  januára 2024_20h35m30s](https://github.com/TrinityCore/TrinityCore/assets/7515044/eff626bc-6c20-42cd-bf39-c3447c5f92cd)
![Ashampoo_Snap_sobota 27  januára 2024_20h31m43s](https://github.com/TrinityCore/TrinityCore/assets/7515044/a8f85e6d-53d9-41e9-bd03-5c8c3fcc1074)
![Ashampoo_Snap_sobota 27  januára 2024_20h35m7s](https://github.com/TrinityCore/TrinityCore/assets/7515044/8425e6ad-3c96-49e7-b065-e2de7ac0cd7b)

**Comment by shamage** [comment]
According to what you describe, there is no problem for me - I tried to create an NPC in the position as indicated in the picture. I suppose I'm in the right place. You can see the result in my pictures:
![Ashampoo_Snap_sobota 27  januára 2024_20h35m30s](https://github.com/TrinityCore/TrinityCore/assets/7515044/1083a856-327f-4423-accc-f29125acc83c)
![Ashampoo_Snap_sobota 27  januára 2024_20h31m43s](https://github.com/TrinityCore/TrinityCore/assets/7515044/8c9139a0-b28c-4fe5-839f-028deab1b1b9)
![Ashampoo_Snap_sobota 27  januára 2024_20h35m7s](https://github.com/TrinityCore/TrinityCore/assets/7515044/b7ef6d49-8373-4441-ba06-31cb858d030b)

**Comment by shamage** [comment]
TrinityCore rev. ce07be8b2366 2024-01-25 00:02:22 +0100 (main branch) (Win64, RelWithDebInfo, Static)

**Comment by coreretail6** [comment]
So i used the TDB Database with updates and got still this bug... which client version are u using ? i m using 10..2.5 build 53040

**Comment by shamage** [comment]
I am using client 10.2.5.53040 and TrinityCore rev. 801b02bd529a 2024-01-26 13:39:36 +0100 (master branch) (Win64, RelWithDebInfo, Static)
It is possible that your DB does not contain all the necessary data for correct functioning. I therefore recommend (if possible) to use data from sniffs.

**Comment by ImmortalusDev** [comment]
> FYI: Even the Valdrakken Flight Master is broken :D <img alt="image" width="1492" src="https://private-user-images.githubusercontent.com/132657906/300188121-296000c2-ac9d-4e2e-8571-7235885cdd6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTYzMDAsIm5iZiI6MTcwNjUxNjAwMCwicGF0aCI6Ii8xMzI2NTc5MDYvMzAwMTg4MTIxLTI5NjAwMGMyLWFjOWQtNGUyZS04NTcxLTcyMzU4ODVjZGQ2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwODEzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTI2ODAyN2JiZGRiNzkzNjdmNjc0MDhhMDYxMTNlNTUyNWYwOWVmYWJkMDE5YTEzMzQ1MWI3ODhmMDQ1OGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yRvhuXyXdwqvJqqCnwIPfUkpFNdwxoradpJGKRaFZKI">

I got this one too, latest client + build

**Comment by V-Cyberpunk** [comment]
found an unhandled opcode wenn opening dragonisles map: Received not handled opcode [CMSG_UI_MAP_QUEST_LINES_REQUEST 0x33B9 (13241)] from [Player: Testix Player-1-00000028, Account: 4]
it's in the log file

**Comment by ImmortalusDev** [comment]
> found an unhandled opcode wenn opening dragonisles map: Received not handled opcode [CMSG_UI_MAP_QUEST_LINES_REQUEST 0x33B9 (13241)] from [Player: Testix Player-1-00000028, Account: 4] it's in the log file

Have nothing to do with it

**Comment by ItsMrMedic** [comment]
After updating from 10.2.0 to 10.5.0 I'm also getting this same issue.

**Comment by thorton1786** [comment]
I’m in the same boat. Only log showing anything is my client error log saying script assertion error for mapcanvas.LUA. The client works when using retail without error but not for the server

**Comment by V-Cyberpunk** [comment]
these are the lua errors
![image](https://github.com/TrinityCore/TrinityCore/assets/44802344/d98aa445-43d3-45f3-be1b-7d80793f66dc)

**Comment by shamage** [comment]
After deeper testing, I came across an error, namely that this part of the map cannot be opened in detail.
I am attaching a picture of how the map should be able to open :  
![Ashampoo_Snap_streda 31  januára 2024_19h46m42s](https://github.com/TrinityCore/TrinityCore/assets/7515044/a0406a53-5616-4085-b6f3-5472560f4257)


![Ashampoo_Snap_štvrtok 1  februára 2024_19h34m52s](https://github.com/TrinityCore/TrinityCore/assets/7515044/54a4278f-937e-47c8-942c-96d341251618)

**Comment by V-Cyberpunk** [comment]
indeed

> After deeper testing, I came across an error, namely that this part of the map cannot be opened in detail. I am attaching a picture of how the map should be able to open : ![Ashampoo_Snap_streda 31 januára 2024_19h46m42s](https://private-user-images.githubusercontent.com/7515044/301615938-a0406a53-5616-4085-b6f3-5472560f4257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTUyMDksIm5iZiI6MTcwNjgxNDkwOSwicGF0aCI6Ii83NTE1MDQ0LzMwMTYxNTkzOC1hMDQwNmE1My01NjE2LTQwODUtYjZmMy01NDcyNTYwZjQyNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkxNTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAxZWM1OTA5NTQ2M2NiZDUyZjQxMmYxZmNiOWVkYmUyOTk3YmNiYzdmN2NmMWU0ZWMxM2VlMmQzZDM2NzdkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MDrNQCp6y5inKLwEk6Px1fZ9kWJXi260H2r8a4CS6oc)
> 
> ![Ashampoo_Snap_štvrtok 1 februára 2024_19h34m52s](https://private-user-images.githubusercontent.com/7515044/301616120-54a4278f-937e-47c8-942c-96d341251618.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTUyMDksIm5iZiI6MTcwNjgxNDkwOSwicGF0aCI6Ii83NTE1MDQ0LzMwMTYxNjEyMC01NGE0Mjc4Zi05MzdlLTQ3YzgtOTQyYy05NmQzNDEyNTE2MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkxNTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYxZDBhMjlhNTgxYTRjNTI4OWUxMzRhOTc1Y2Y5NWQwODIxYWQwYTBiMWU4NzMzMmNjYTVmMWIzODc4MDYwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iJQPvP-NYqDMz9suwG5IgA0muXWc5etiKh1zANmLj5M)
> 
> but it won't happen

indeed, all ok with your installation. this is very strange.

**Comment by shamage** [comment]
It seems that this error (I mean the error mentioned by me) will be in Core and not in the database.
@Shauren  : could it be?

**Comment by meji46** [comment]
Maybe it's a missing hotfix: https://wago.tools/db2/UiMapArt?filter[ID]=exact:1860

**Comment by Shauren** [comment]
I have a fix for this, will push later

**Comment by thorton1786** [comment]
Still having the same issue after running the hotfix query
