### ISSUE TITLE
Failure to build latest Master

### ISSUE THREAD

**Issue by ImLynxie** [TrinityCore/TrinityCore#29621]
### Description

Attempted to build the project using`
> **CLion 2023.3.3 - Build #CL-233.14015.92**

**CMake & MinGW versions**
>_MinGW Version:_ **11.0 w64**
_CMake Version:_ **3.27.8**
_Build tool used:_ **Ninja**
_Debugger:_ Bundled GDB Version 13.2

However I seem to be getting errors on the Log macros, without being provided with any meaningful information on what exactly is causing the issue. 

I'm not sure if I'm using an incompatible version of any software needed to build the project. Any assistance regarding this matter would be helpful, and apologies beforehand if this is just a simple oversight by me.

> `C:/Users/Lynxie/CLionProjects/TrinityCore/src/common/Logging/Log.h:144:26: error: 'push' was not declared in this scope
  144 |         __pragma(warning(push))                                         \
      |                          ^~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/common/Logging/Log.h:166:5: note: in expansion of macro 'TC_LOG_MESSAGE_BODY'
  166 |     TC_LOG_MESSAGE_BODY(filterType__, LOG_LEVEL_ERROR, __VA_ARGS__)
      |     ^~~~~~~~~~~~~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/server/proto/ServiceBase.cpp:25:5: note: in expansion of macro 'TC_LOG_ERROR'
   25 |     TC_LOG_ERROR("service.protobuf", "{} Server tried to call server method {}",
      |     ^~~~~~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/common/Logging/Log.h:144:18: error: 'warning' was not declared in this scope; did you mean 'WPWarning'?
  144 |         __pragma(warning(push))                                         \
      |                  ^~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/common/Logging/Log.h:166:5: note: in expansion of macro 'TC_LOG_MESSAGE_BODY'
  166 |     TC_LOG_MESSAGE_BODY(filterType__, LOG_LEVEL_ERROR, __VA_ARGS__)
      |     ^~~~~~~~~~~~~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/server/proto/ServiceBase.cpp:25:5: note: in expansion of macro 'TC_LOG_ERROR'
   25 |     TC_LOG_ERROR("service.protobuf", "{} Server tried to call server method {}",
      |     ^~~~~~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/src/common/Logging/Log.h:144:9: error: '__pragma' was not declared in this scope; did you mean '_Pragma'?
  144 |         __pragma(warning(push))                                         \
      |         ^~~~~~~~
`

Also some errors regarding try catches. 

> `C:/Users/Lynxie/CLionProjects/TrinityCore/dep/g3dlite/source/GThread.cpp:103:6: error: expected 'catch' before '__except'
  103 |    } __except(EXCEPTION_EXECUTE_HANDLER) {}
      |      ^~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/dep/g3dlite/source/GThread.cpp:103:6: error: expected '(' before '__except'
  103 |    } __except(EXCEPTION_EXECUTE_HANDLER) {}
      |      ^~~~~~~~
      |      (
C:/Users/Lynxie/CLionProjects/TrinityCore/dep/g3dlite/source/GThread.cpp:103:6: error: expected type-specifier before '__except'
  103 |    } __except(EXCEPTION_EXECUTE_HANDLER) {}
      |      ^~~~~~~~
C:/Users/Lynxie/CLionProjects/TrinityCore/dep/g3dlite/source/GThread.cpp:103:14: error: expected ')' before '(' token
  103 |    } __except(EXCEPTION_EXECUTE_HANDLER) {}
      |      ~~~~~~~~^
      |              )`

### Expected behaviour

Expected behavior would be for the project to build properly.

### Steps to reproduce the problem

**Step 1:**
Pull project from github using CLion.

**Step 2:**
Let CLion setup project using Default Bundled MinGW

**Step 3:**
Open CMake Settings -> Add Following Environment Variables to CMake`

> BOOST_ROOT=$VCPKG_REPO$\installed\x64-mingw-dynamic;
OPENSSL_ROOT_DIR=$BOOST_ROOT$;
VCPKG_REPO=C:\Users\<YOUR-USER>\.vcpkg-clion\vcpkg

**Step 4:**
Let CMake finish configuring the project, once finished goto Step 5

**Step 5:**
Build the project. From the toolbar **Build** -> **Build All in Debug-MinGW**

### Branch

master

### TC rev. hash/commit

801b02b

### Operating system

Windows 11 Version (22H2)

### Custom changes

None

**Comment by Shauren** [comment]
MinGW isn't supported, on windows you have to use msvc or clang
