### ISSUE TITLE
Broken Quest in Exile's Reach

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29655]
### Description

Several quest are newly broken due to ```Unit* owner = me->GetDemonCreator();``` not returning an owner.

### Expected behaviour

Should return an owner.

### Steps to reproduce the problem

Go to Exile's Reach. Take quest "Finding the lost expedition".

Breaks here:

![image](https://github.com/TrinityCore/TrinityCore/assets/709267/cc9749b2-5d4f-4fd9-aba0-5a31f3ef3546)

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/9e13fee4a6374680e99ab4407fed73940954ea91

### Operating system

Windows 10

### Custom changes

none

**Comment by Ovahlord** [comment]
this is only set for player summoners

**Comment by malcrom** [comment]
It's not my code.
