### ISSUE TITLE
All Shadowglen quest_template_addon fixes

### ISSUE THREAD

**Issue by Kelpiesklubhouse** [TrinityCore/TrinityCore#29656]
### Description

The following fix updates and corrects all quest_template_addon rows for Shadowglen quests. All quests have been compared with retail and are up to date.

Brief explanation of fixes:

2 Quests (The Balance of Nature (28713) and Priestess of the Moon (28723)) had no quest_template_addon entires.

1 Quest (Fel Moss Corruption (28714)) contained an erroneous NextQuestID for Demonic Thieves, mentioned in the next point.

1 Quest (Demonic Thieves (28715)) contained an erroneous PrevQuestID entry for A Favor for Melithar (28734). On retail, A Favor for Melithar is only a breadcrumb quest and not an actual part of the quest-chain, and the actual PrevQuestID should be for The Balance of Nature.

In addition, Priestess of the Moon (28723) can only be attained if both Fel Moss Corruption and Demonic Thieves have been completed. ExclusiveGroup was used for this purpose (Thanks: Naddley)

![image](https://github.com/TrinityCore/TrinityCore/assets/151824209/8a161963-9200-4ccb-9f5a-13fc549a33c3)

### SQL fix

```sql
-- Fel Moss Corruption and Demonic Thieves ExclusiveGroup
UPDATE `quest_template_addon` SET `ExclusiveGroup`=-28714 WHERE `ID` IN (28714,28715);
-- Demonic Thieves
UPDATE `quest_template_addon` SET `PrevQuestID`=28713 WHERE `ID`=28715;
UPDATE `quest_template_addon` SET `NextQuestID`=28723 WHERE `ID`=28715;
-- A Favor for Melithar
UPDATE `quest_template_addon` SET `PrevQuestID`=28714 WHERE `ID`=28734;
UPDATE `quest_template_addon` SET `NextQuestID`=0 WHERE `ID`=28734;
UPDATE `quest_template_addon` SET `BreadcrumbForQuestId`=28715 WHERE `ID`=28734;
```

### Branch

master

### TC rev. hash/commit

9e13fee

**Comment by malcrom** [comment]
Should any of the wrong IDs be disabled as no longer obtainable?

**Comment by Kelpiesklubhouse** [comment]
No, they're fine. everything checks out with this. It was just that for some reason, they had nextquestids set which were not only wrong, but unnecessary, as shadowglen's entire quest chain is a straight line except for one breadcrumb quest (A Favor for Melithar). So it should just be a straight chain of PrevQuestIDs.

**Comment by Kelpiesklubhouse** [comment]
Alright, this is going to sound silly, but on retesting with multiple characters, I have found that the quest Priestess of the Moon (28723) requires BOTH Fel Moss Corruption (28714) AND Demonic Thieves (28715) to be completed in order to be available. Is there any way to implement this?

**Comment by Naddley** [comment]
create a exclusive group + set the Quest which should get available as NextQuestID.
you can read about it in wiki: https://trinitycore.info/database/master/world/quest_template_addon

**Comment by Naddley** [comment]
example commit would be https://github.com/TrinityCore/TrinityCore/commit/5d2379a413b842c9fb3823ba6605cf240d107f44

**Comment by Kelpiesklubhouse** [comment]
Alright, should be good to go now

**Comment by Legoso** [comment]
Technically, I assume it would be possible to merge those `UPDATE` lines with identical ID targets. Then again, it is probably much easier to read as is, without any change.
