### ISSUE TITLE
Casting a spell too quickly in succession fails

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#2967]
I'm not quite sure how to explain this, but here goes..

When I press a key, that has an instant or channeled spell bound to it, repeatedly and quickly, the server actually runs the action twice even though the first action should trigger a cooldown.

This is noticable when riding the green drake in The Oculus and using the first spell/skill - sometimes (mainly the first time), 2 bolts are fired before the cooldown kicks in.
It also happens quite often when "spamming" Mind Flay while the global cooldown is on. As soon as the CD is over, Mind Flay is supposed to start channeling, but because the server runs the action twice, the first cast triggers the global cooldown and I get the reply that "Spell is not ready yet." and have to wait another second for the second action/channeling to start..

Ask for more details if needed.
##

**Comment by Killyana** [comment]
Cannot reproduce on rev. 24cf532557b0
