### ISSUE TITLE
Deprecated Quests in Camp Narache

### ISSUE THREAD

**Issue by Kelpiesklubhouse** [TrinityCore/TrinityCore#29678]
### Description

4 class quests which have been deprecated should be added to the disables table. Each of these quests has a name ending in 'Note'.

### SQL fix

```sql
-- Deprecated Quests in Camp Narache
DELETE FROM `disables` WHERE `sourceType`=1 AND `entry` IN (3091, 3092, 3093, 3094);
INSERT INTO `disables` (`sourceType`,`entry`,`flags`,`params_0`,`params_1`,`comment`) VALUES
(1,3091,0,'','','Deprecated Quest: Simple Note'),
(1,3092,0,'','','Deprecated Quest: Etched Note'),
(1,3093,0,'','','Deprecated Quest: Rune-Inscribed Note'),
(1,3094,0,'','','Deprecated Quest: Verdant Note');
```

### Branch

master

### TC rev. hash/commit

3e1eec08

**Comment by Naddley** [comment]
Two thins:
-> Never "just" INSERT data do a DELETE before you INSERT stuff.
-> You can do do a single INSERT for all 4 values. :D

**Comment by Kelpiesklubhouse** [comment]
Whoops, yeah, forgot the delete lines, I was also just trying to separate them so the comments would show which quest was being added.
