### ISSUE TITLE
Server crash command: .serv rest 500

### ISSUE THREAD

**Issue by PivanDepolo** [TrinityCore/TrinityCore#29684]
### Description

Crash occurs

### Expected behaviour

Must not crash

### Steps to reproduce the problem

Write the command in the chat:  .serv rest 500

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commits/master/

### Operating system

Debian 11

### Custom changes

None

**Comment by shamage** [comment]
I tried to reproduce the problem you mentioned and the result was this: (see image)  
![Ashampoo_Snap_piatok 9  februára 2024_18h30m42s](https://github.com/TrinityCore/TrinityCore/assets/7515044/97662132-8539-43fe-ba1e-31138729cddf)

**Comment by Shauren** [comment]
Same, cannot reproduce, either from console or ingame

You also did not specifiy which commit exactly

**Comment by jackpoz** [comment]
It would be nice to have the crashlog too
