### ISSUE TITLE
Quest Item: Tallonkai's Jewel loot fix

### ISSUE THREAD

**Issue by Kelpiesklubhouse** [TrinityCore/TrinityCore#29680]
### Description

Creature Ferocitas the Dream Eater (7234) drops deprecated quest item Gnarlpine Necklace (8049), should drop Tallonkai's Jewel (8050) this SQL will fix that.

### SQL fix

```sql
-- Ferocitas the Dream Eater Loot: Talonkai's Jewel
DELETE FROM `creature_loot_template` WHERE `Entry`=7234 AND `Item`=8049;
INSERT INTO `creature_loot_template` (`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`) VALUES
(7234,8050,0,100,1,1,0,1,1,'Quest Item: Talonkai''s Jewel');
```

### Branch

master

### TC rev. hash/commit

3e1eec08

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/commit/95bc546e2c16e312c041c5c23bf0ff295bae0612
