### ISSUE TITLE
Gameobject's not saving to the gameobject table

### ISSUE THREAD

**Issue by Gwyndrichstein** [TrinityCore/TrinityCore#29681]
### Description

Gobs are not written to the DB table "gameobject" after spawning in the game (via .gob add command), after each server restart the spawned gobs disappear.

### Expected behaviour

Newly spawned gobs should be added and remain in the DB table.

### Steps to reproduce the problem

I don't know. It happened practically from one day to the next, nothing major was going on the server. 

### Branch

3.3.5

### TC rev. hash/commit

**0e29a1bd44c4**

### Operating system

Debian 11

### Custom changes

Outfitter from Rochet's.

**Comment by Legoso** [comment]
Do you think you can find one of the commits in https://github.com/TrinityCore/TrinityCore/commits/3.3.5/ that matches your build, before adding Rotchet's stuff?

Any example gobs to test that you know should fail after reboot?

Could it be that you have a custom setting for time between save to DB ?

**Comment by Gwyndrichstein** [comment]
Solved, weird connection issues on the provider side. Not a TC problem.
