### ISSUE TITLE
DB/Boralus: Duplicated gameobjects

### ISSUE THREAD

**Issue by Polytrih** [TrinityCore/TrinityCore#29688]
### Description

The https://github.com/TrinityCore/TrinityCore/commit/a761ebd6a612af4158efabcd1b729379173f5578 commit has introduced some duplicated gameobjects in Boralus.

**Example**

`SELECT *
FROM world.gameobject
WHERE guid IN (501835, 501914);`

**List of duplicated gameobjects:**

Guid of the original gameobject: Guid of the duplicated gameobject
501835: 501914
501836: 501924
501837: 501937
501838: 501939
501839: 501995
501841: 501942
501842: 501998
501843: 501927
501844: 501944
501845: 502001
501846: 501929
501847: 501948
501848: 501932
501849: 501949
501850: 502002
501851: 501954
501852: 501933
501853: 501956
501855: 501936
501856: 501913
501857: 502005
501858: 501915
501859: 501918
501860: 501945
501861: 501935
501862: 501938
501863: 501941
501864: 501943
501865: 501946
501866: 502006
501867: 502012
501868: 501957
501869: 501907
501870: 501965
501871: 501909
501872: 501987
501874: 501926
501875: 501919
501876: 501910
501877: 501979
501878: 501911
501879: 501981
501880: 501971
501881: 501928
501882: 501974
501883: 501976
501884: 501991
501885: 501964
501886: 501992
501887: 501967
501888: 501982
501889: 501985
501890: 501970
501891: 501972
501892: 501975
501893: 501977
501894: 501930
501895: 502007
501896: 501953
501897: 501983
501898: 501986
501899: 501988
501900: 501958
501901: 501990
501902: 501959
501903: 501960
501904: 501961
501906: 501969

### SQL fix

```sql
DELETE FROM world.gameobject
WHERE guid IN(501914,501924,501937,501939,501995,501942,501998,501927,501944,502001,501929,501948,501932,501949,502002,501954,501933,501956,501936,501913,502005,501915,501918,501945,501935,501938,501941,501943,501946,502006,502012,501957,501907,501965,501909,501987,501926,501919,501910,501979,501911,501981,501971,501928,501974,501976,501991,501964,501992,501967,501982,501985,501970,501972,501975,501977,501930,502007,501953,501983,501986,501988,501958,501990,501959,501960,501961,501969);

DELETE FROM world.gameobject_addon
WHERE guid IN(501914,501924,501937,501939,501995,501942,501998,501927,501944,502001,501929,501948,501932,501949,502002,501954,501933,501956,501936,501913,502005,501915,501918,501945,501935,501938,501941,501943,501946,502006,502012,501957,501907,501965,501909,501987,501926,501919,501910,501979,501911,501981,501971,501928,501974,501976,501991,501964,501992,501967,501982,501985,501970,501972,501975,501977,501930,502007,501953,501983,501986,501988,501958,501990,501959,501960,501961,501969);
```

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/6ac0f7bd1c4260cc7258f23a2f69a38e5ee7606b

**Comment by mdX7** [comment]
13398a9710e3414bc1ad4aacd3ec0bfed9ef2593
