### ISSUE TITLE
Scene Issue Exile's Reach

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29690]
### Description

On accepting quest 59949 'Who Lurks in the Pit' The beam scene spells are recast on you but you also have an extra spell 312605 Ambience (DNT) cast on you which shows spiders hanging on webs. The issue with this spell is if you log out with it when you log back in you are hung at a scene and have to escape to end it.

https://www.youtube.com/watch?v=CnpN1nQwzHw

### Expected behaviour

Should not have to escape.

### Steps to reproduce the problem

Add aura 312605  log out and back in

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/3e1eec081f717fc9ca102a22b28a99030415c8aa

### Operating system

Win 10

### Custom changes

None

**Comment by Naddley** [comment]
seems to happen with more scene related spells
Same happens in Dracthyr startarea with:

[0] SpellID: 370271 (Beacons)

**Comment by malcrom** [comment]
Scene for spell

```sql
-- Add Scenes for Who Lurks in the Pit
DELETE FROM `scene_template` WHERE `SceneId` IN (2380);
INSERT INTO `scene_template` (`SceneId`,`Flags`,`ScriptPackageID`,`Encrypted`,`ScriptName`) VALUES
(2380,16,2773,0,''); -- 9.0 NPE - Spider Den - Ambient Spiderlings Going Squish - (STM)
```

**Comment by malcrom** [comment]
> 370271

what is the ScriptPackageID for scene 2887 from that spell?
