### ISSUE TITLE
Freed Expedition Member missing Broadcast text ids

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29692]
### Description

Entry 167244 Freed Expedition Member missing Broadcast text in db and no ids in sniff.

### Expected behaviour

```sql

```

### Steps to reproduce the problem

Missing ids

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/3e1eec081f717fc9ca102a22b28a99030415c8aa

### Operating system

Windows 10

### Custom changes

none

**Comment by mdX7** [comment]
could you check if theres a related SOUND packet sent for creature id 167244? they still leak broadcast_text id there

**Comment by malcrom** [comment]
No sound packets in sniff. Sniff was searched.
