### ISSUE TITLE
Gameobject being disabled on spell hit cannot play custom animation

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29715]
### Description

Gameobject 203193 gets hit by spell 77101 and should do custom animation. Instead the spell is activating the object which disables it and no animation plays.

update object is sent on TC but not on offical.
![image](https://github.com/TrinityCore/TrinityCore/assets/709267/1c8e3e3b-9710-40db-bd64-d2acec40d200)

I had to hack this to make animation work
![image](https://github.com/TrinityCore/TrinityCore/assets/709267/1e345046-1023-4453-ba84-c48a26706b9f)

Using this script
![image](https://github.com/TrinityCore/TrinityCore/assets/709267/61bf2b97-149c-406f-8a92-71b5366cfb2f)

I'm not sure if an extra check is needed on GO_ACTIVATED or if something else is needed.

### Expected behaviour

Gameobject should play custom animation. Video of custom animation working:

https://www.youtube.com/watch?v=azzNxsHswFI

### Steps to reproduce the problem

Cast spell while next to mortor with script applied

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/8dc494c1ae049b4829474e95acce774ed15a9a64

### Operating system

Windows 10

### Custom changes

None

**Comment by malcrom** [comment]
Also I had to do a c++ script because I couldn't get action 93 play custom animation to work in SAI.

**Comment by Nyr97** [comment]
Your spell uses SPELL_EFFECT_ACTIVATE_OBJECT with MiscA 5, which is GameObjectActions::Disturb, which triggers GameObject::Use from the caster to the gobject. Your gobject is a GAMEOBJECT_TYPE_GOOBER, so the result of this will make it do SetGoState(GO_STATE_ACTIVE) unless field4 is filled with any entry, in that case it uses SendCustomAnim.

**Comment by malcrom** [comment]
> Your spell uses SPELL_EFFECT_ACTIVATE_OBJECT with MiscA 5, which is GameObjectActions::Disturb, which triggers GameObject::Use from the caster to the gobject. Your gobject is a GAMEOBJECT_TYPE_GOOBER, so the result of this will make it do SetGoState(GO_STATE_ACTIVE) because field4 is empty, which would trigger in that case SendCustomAnim.
> 
> SetGoState forces the object to send SMSG_UPDATE_OBJECT by default. Unless you come up with a generic solution, your only possible hackfix would be entirely overriding the effect to SPELL_EFFECT_DUMMY and using a spellscript to force it to do whatever you want.

This seems to fix issue. 
![image](https://github.com/TrinityCore/TrinityCore/assets/709267/a50caaac-57d2-47c4-b6d3-123c516ee4b4)

**Comment by Nyr97** [comment]
That's not a fix, you're just doing it because it works for your case, you might be bugging hundreds of gameobjects with this change.

**Comment by malcrom** [comment]
I've checked two spells so far with disturb. Neither updates object. Will look for more but I can't test them all with a starter account.

**Comment by Nyr97** [comment]
You needed a lot of testing for this type of change. I suggest you talk to Modox or Shauren for guidance on this.

**Comment by malcrom** [comment]
All I can see, from the two spells I checked, is that goobers shouldn't disable when disturbed. If some do then it should be done in spell hit not hard coded because I have two spells that do not reset.

**Comment by malcrom** [comment]
No i'm not saying thats the proper fix just that this is where the issue is.

**Comment by Shauren** [comment]
The fix for this issue is the answer to the question written in comment on `case GameObjectActions::Disturb:`

**Comment by malcrom** [comment]
> The fix for this issue is the answer to the question written in comment on `case GameObjectActions::Disturb:` (we don't have this answer yet)

Well it's not disabling the object. Spell 77101 does a custom animation and Spell 78395 hits go 203452 and it despawns in my sniffs with no object update.

**Comment by malcrom** [comment]
Also there are only 32 spells with SPELL_EFFECT_ACTIVATE_OBJECT,  TARGET_GAMEOBJECT_NEARBY_ENTRY, EffectMiscValueA = 5

**Comment by malcrom** [comment]
I f you have a sniff of this quest https://www.youtube.com/watch?v=-Ao6Lx9aIuY you can check spell 43080 Quest - Howling Fjord - Guide Our Sights - FX Master affect on cannons.

**Comment by malcrom** [comment]
So shouldn't that code be removed if it was added on a whim? It's oviously a hack.

**Comment by malcrom** [comment]
it's been 7 months since I reported this issue. It's obvious the person who added the code didn't know what disturb did. It should just be a hook for gameobject scripting to add an action on spellhit. I did check a couple spells that did not active the gameobject on spellhit so the code is wrong and a hack if used for other spells.

**Comment by malcrom** [comment]
Also if shin gets a Retarded tag I want one too.
