### ISSUE TITLE
DK/Spell: Anti-Magic Shell shoud give Immunity vs Cyclone

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29711]
### Description

Anti-Magic Shell does not give Immunity vs Cyclone atm you can have both applied and dk will keep attack as Cyclone is not present:

https://youtu.be/RG7krVNVAxg

I found this fix but not sure if it is properly, (it works) or maybe we can do it with conditions
```sql
-- Anti-Magic Shell - Cyclone Immunity
DELETE FROM `spell_linked_spell` WHERE (`spell_trigger`='48707') AND (`spell_effect`='-33786') AND (`type`='2');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('48707', '-33786', '2', 'Anti-Magic Shell (Self) - Cyclone Immunity');
```

### Expected behaviour

Anti-Magic Shell shoud give Immunity vs Cyclone most likely, I have no proof atm but I will find soon.

### Steps to reproduce the problem

.aura 48707
.aura 33786

### Branch

3.3.5

### TC rev. hash/commit

86551ba71669712cadf82f2dc1f0c5481f0fba1b

### Operating system

Windows 11 x64

### Custom changes

[Passive anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/commits/3.3.5-passive_anticheat)

**Comment by Ovahlord** [comment]
please refreain from using spell_linked_spell and write an aurascript instead

**Comment by CraftedRO** [comment]
woudn't a simple condition be enough in this case ?

**Comment by CraftedRO** [comment]
meh seems like SourceTypeOrReferenceId 17 doesn't works in this case, too bad.

**Comment by CraftedRO** [comment]
Seems like it fixed by himself and only able to reproduce with .aura and not with normal spell cast.
