### ISSUE TITLE
Kharanos Mountaineers behind Mortars at Frostmane Front

### ISSUE THREAD

**Issue by malcrom** [TrinityCore/TrinityCore#29718]
### Description

Two should be knelling with another pathing. flags from sniff added to prevent combat. Mortor firing not yet added due to disturb issue in gameobject handler.

### SQL fix

```sql
```

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/8dc494c1ae049b4829474e95acce774ed15a9a64

**Comment by malcrom** [comment]
Decided to add SAI for Mortar Caster. Mortar script to do custom animation will be added later if gameobject system is fixed.

**Comment by malcrom** [comment]
it seems creature 41188 is respawning ever 12 seconds. I need to do more research to see what is required here.

**Comment by malcrom** [comment]
Updated

**Comment by mdX7** [comment]
requires #29715

**Comment by malcrom** [comment]
This script works fine. There is just no mortar animation due to the code for gameobjects only supporting animation numbers above zero. Nothing will change in this script when or if it is fixed.
