### ISSUE TITLE
Database issue: Can the databases of 3.3.5 and 10.2.5 imported together?

### ISSUE THREAD

**Issue by zobinimm** [TrinityCore/TrinityCore#29712]
### Description

The default database name used has already imported 3.3.5 data on the computer.
Now I want to create a new 10.2.5. Can I use the default database name to import 10.2.5 data?
Does it have any impact on 3.3.5?
Are there any conflicts between the two?

### Expected behaviour

3.3.5 and 10.2.5 can run in the same default DB environment and switch versions by starting different versions of server.exe

### Steps to reproduce the problem

1. 3.3.5 run successfully
2. 10.2.5 is not running yet, afraid of damaging 3.3.5's DB environment

### Branch

3.3.5

### TC rev. hash/commit

No debugging commands, no courage to run 10.2.5, afraid of damaging 3.3.5's DB environment

### Operating system

 Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
if you configure databases properly no.
