### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by Onelastbreathbg** [TrinityCore/TrinityCore#29721]
### Description

when i compile the trinity i get this error , followed the guide everything 1 by 1 at first i thought it works but when i try to login that happens
C:\wow\core\src\common\Cryptography\ARC4.cpp:31 in Trinity::Crypto::ARC4::ARC4 ASSERTION FAILED:
  result == 1

### Expected behaviour

to work i guess

### Steps to reproduce the problem

C:\wow\core\src\common\Cryptography\ARC4.cpp:31 in Trinity::Crypto::ARC4::ARC4 ASSERTION FAILED:
  result == 1

### Branch

3.3.5

### TC rev. hash/commit

C:\wow\core\src\common\Cryptography\ARC4.cpp:31 in Trinity::Crypto::ARC4::ARC4 ASSERTION FAILED:
  result == 1

### Operating system

windows

### Custom changes

no

**Comment by CraftedRO** [comment]
I also compiled 319434544baa018339ba6284ebb910eec1418a4f on windows without problems, so most likely you are doing smth wrong, maybe wrong openssl version ?

**Comment by Shauren** [comment]
User didn't follow wiki installation guide (legacy.dll)
