### ISSUE TITLE
Core/Units: PlayHoverAnim state when flying or hovering need cherry pick

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29723]
### Description

I guess https://github.com/TrinityCore/TrinityCore/pull/29434 have to be cherry picked on 3.3.5 too since there are npc like:

```
[16] Object Guid: Map: 530 (Outland) Entry: 19152 (Interrogator Khan)
[15] AnimTier: 0
[16] PlayHoverAnim: True
[16] MovementFlags: 512 (DisableGravity)

[15] Object Guid: Map: 571 (Northrend) Entry: 26471 (Image of Archmage Aethas Sunreaver)
[15] AnimTier: 0
[15] PlayHoverAnim: True
[15] MovementFlags: 1536 (DisableGravity, Root)
```

See: https://github.com/TrinityCore/TrinityCore/pull/28208

### Expected behaviour

We need a way to make npc hover

### Steps to reproduce the problem

.go c id 19152  (Interrogator Khan)
.go c id 26471 (Image of Archmage Aethas Sunreaver)
compare them with blizzard ones
notice

### Branch

3.3.5

### TC rev. hash/commit

319434544baa018339ba6284ebb910eec1418a4f

### Operating system

Windows 11 x64

### Custom changes

[Passive anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/commits/3.3.5-passive_anticheat)

**Comment by Shauren** [comment]
No, it doesn't, 3.3.5 client doesn't have a separate `PlayHoverAnim` field

**Comment by CraftedRO** [comment]
so it's proper to just add AnimTier 2 to this kind of npc ?

**Comment by Ovahlord** [comment]
Yes.
