### ISSUE TITLE
All Northshire creature_queststarter and creature_questender fixes.

### ISSUE THREAD

**Issue by Kelpiesklubhouse** [TrinityCore/TrinityCore#29764]
### Description

All creature_queststarter and creature_questender entries for Northshire are here. Ran through all 9 potential routes, parsed with WPP on 2/29/2024 on retail with client build 53441.

### SQL fix

```sql
DELETE FROM `creature_queststarter` WHERE (`id`=951 AND `quest`=63447);
INSERT INTO `creature_queststarter` (`id`, `quest`, `VerifiedBuild`) VALUES
(951, 63447, 53441); -- Fear No Evil offered by Brother Paxton

UPDATE `creature_queststarter` SET `VerifiedBuild`=53441 WHERE (`id`=197 AND `quest` IN (26389,29080,29079,29078,31143,31140,31139,28785,28770,28762,28788,28773,28765,28786,28771,28763,28787,28772,28764,28784,28769,28757,28780,28759,28767,54,26390,28789,28774,28766)) OR (`id`=823 AND `quest` IN (29083,29081,31145,31144,28819,28793,28822,28796,28820,28794,28821,28795,28818,28792,28817,28791,28823,28797)) OR (`id`=951 AND `quest` IN (29082,28809,28812,28810,28811,28808,28806,28813)) OR (`id`=9296 AND `quest`=26391);

DELETE FROM `creature_questender` WHERE (`id`=951 AND `quest`=63447);
INSERT INTO `creature_questender` (`id`, `quest`, `VerifiedBuild`) VALUES
(951, 63447, 53441); -- Fear No Evil ended by Brother Paxton

UPDATE `creature_questender` SET `VerifiedBuild`=53441 WHERE (`id`=197 AND `quest` IN (29083,29079,29078,31145,31140,31139,28819,28770,28762,28822,28773,28765,26389,28820,28771,28763,28821,28772,28764,28818,28769,28757,28817,28759,28767,26390,28823,28774,28766)) OR (`id`=823 AND `quest` IN (29081,29080,31144,31143,28793,28785,28796,28788,28794,28786,28795,28787,28792,28784,28791,28780,28797,28789)) OR (`id`=951 AND `quest` IN (29082,28809,28812,28810,28811,28808,28806,28813)) OR (`id`=9296 AND `quest`=26391) OR (`id`=240 AND `quest`=54);
```

### Branch

master

### TC rev. hash/commit

be3dc89

**Comment by Kelpiesklubhouse** [comment]
SQL Updated to include creature_questender as well.

**Comment by Legoso** [comment]
Thank you for introducing me to the variant of splitting up the `DELETE FROM/INSERT INTO` pairs by first running the `DELETE FROM` query on more than one table, before finishing with the `INSERT INTO` queries. It seems obvious now, but I haven't been thinking like that earlier. 😊👍🏼

**Comment by Kelpiesklubhouse** [comment]
SQL updated (codestyle).

**Comment by Naddley** [comment]
Queststarter & ender is sniffable and generated with WPP. So we can be sure the data is not custom (VerifiedBuild)

**Comment by Kelpiesklubhouse** [comment]
Ok, I understand...it's just that none of his other quests were sniffed (they all had VerifiedBuild of 0)

**Comment by Kelpiesklubhouse** [comment]
As you ordered, I've parsed all queststarters and questenders for Northshire.

**Comment by Naddley** [comment]
If you take a look into your Config of WPP you can connect it to your Database, so WPP use the stuff you allready have in DB. So "allready" existing data would be a UPDATE instead of DELETE + INSERT.

**Comment by Kelpiesklubhouse** [comment]
Alright, Naddley, that should do it.

**Comment by Kelpiesklubhouse** [comment]
Rolled into #29770
