### ISSUE TITLE
IcecrownCitadel: Incorrect transition of Sindragosa from the flight phase to the ground phase

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#29762]
### Description

At the beginning of the fight, after Sindragosa lands, she does not take a standing form. She continues to flutter and is half in textures. The same problem is with the two dragons that need to be killed in order for Sindragosa to arrive. They take a standing form and stand on the ground after landing, but after their sagrish they go into flight form and also fall through the textures.

It works on AzerothCore

### Expected behaviour

Sindragosa and her two dragons must assume a standing form after touching the ground.

### Steps to reproduce the problem

Start beating Sindragosa or two dragons and you will see the problem.

### Branch

3.3.5

### TC rev. hash/commit

[Last](https://github.com/TrinityCore/TrinityCore/commit/75cbafd83afe6ef5a2e36f4a858dd3e83bda0483)

### Operating system

Win Server 2022

### Custom changes

No

**Comment by jackpoz** [comment]
"Last" is not a valid version, because next week it will be a different one.

**Comment by vahzxz** [comment]
> "Last" is not a valid version, because next week it will be a different one.

Fixed it

**Comment by ImmortalusDev** [comment]
This is also very old thing, few years

**Comment by vahzxz** [comment]
> This is also very old thing, few years

The fact of the matter is that the problem is very old and has been fixed for a long time on many cores, but on Trinity the problem is relevant. Alternatively, you can use the implementation of landing with AzerothCore as a basis. I can assume that we don't have enough void JustRespawned()

**Comment by CraftedRO** [comment]
also this issue is duplicate https://github.com/TrinityCore/TrinityCore/issues/29121
