### ISSUE TITLE
how to make the server public and play with friend?

### ISSUE THREAD

**Issue by fhazal** [TrinityCore/TrinityCore#29774]
### Description

i can login and play with local ip perfectly with the latest master branch of the trinity core, now my problem is i can't make other people login to the server using the domain i point to my public ip address, im using cerbot let'sencrypt to generate ssl for the domain own, i have edit location in bnetserver.conf like this : 

`CertificatesFile = "/etc/letsencrypt/live/server.bajubesi.org/cert.pem" `

`PrivateKeyFile = "/etc/letsencrypt/live/server.bajubesi.org/privkey.pem" `

when i try to login using client and arctium launcher i notice the error **server.bajubesi.org:1119 is offline**

how do i correctly setup the ssl? and make my friends can login to the server? i already open all the port need as in instructions, what am i doing wrong? please help

### Expected behaviour

make other people can play on the server from outside the LAN network

### Steps to reproduce the problem

-

### Branch

master

### TC rev. hash/commit

-

### Operating system

Ubuntu 22.04

### Custom changes

-

**Comment by Aokromes** [comment]
this is a bug tracker, not a support place.
