### ISSUE TITLE
pdumd load not taking newguid into account

### ISSUE THREAD

**Issue by kruchor** [TrinityCore/TrinityCore#29787]
### Description

Hello,

I try to restore a pdump load from a server to another (same config and trinitycore revisions). Restore is OK but the newguid I specify is not taken into account. The first free one is used instead.

### Expected behaviour

The newly imported characters shoud have the specified newguid instead of the first free one.

### Steps to reproduce the problem

Last characters database entry :

```
MariaDB [characters2]> select guid,account,name from characters ORDER BY guid DESC LIMIT 1;
+------+---------+--------+
| guid | account | name   |
+------+---------+--------+
|   48 |      41 | Foobar |
+------+---------+--------+
1 row in set (0.000 sec)
```

Load of file :

```
TC> pdump load /home/wotlk/pdumps/07032024/Jurt.pdump.03072024_1350 41 foobar 99
TC> Character loaded successfully!
```

Recheck guid in database :

```
MariaDB [characters2]> select guid,account,name from characters ORDER BY guid DESC LIMIT 2;
+------+---------+--------+
| guid | account | name   |
+------+---------+--------+
|   48 |      41 | Foobar |
|   47 |      44 | Geheme |
+------+---------+--------+
```

It should be 99, not 48.

Did I miss something ?

Thank you !

Ben.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 9ad1b5e6d7d4+ 2024-02-19 01:15:17 +0000 (3.3.5-solocraft branch) (Unix, RelWithDebInfo, Static)
Online players: 0 (max: 1)
Active connections: 0 (max: 1) Queued connections: 0 (max: 0)
Server uptime: 23 Hours 9 Minutes 53 Seconds.
Update time diff: 10.

### Operating system

Debian 11.8 x64

### Custom changes

As you can see above, I'm using Solocraft branch + NPCBots (https://github.com/trickerer/Trinity-Bots) but I doubt it can cause the issue.

=> I'm currently recompiling from 3.3.5a standard repository to check if the issue exists too.

**Comment by Shauren** [comment]
This is a feature - guid is forced to be in range 1-[max_current_guid+1] to avoid creating large gaps
