### ISSUE TITLE
Core/PetAI - Incorrect operation of pets and their spells in the warlock class

### ISSUE THREAD

**Issue by KamiliaBlow** [TrinityCore/TrinityCore#29785]
### Description

LOGOUT: If you re-enter the game on a character who has a pet. When entering the world, the pet will not be displayed in the interface under the player's portrait, and the pet panel will not be visible until the player calls it again (this will not solve the problem with the portrait).

IMP: https://www.wowhead.com/spell=688/summon-imp However, once called up, he will only be able to attack in melee (for some reason, after upgrading the character's level, the melee ability also stops working). His spell is not working.
 - https://www.wowhead.com/spell=3110/firebolt has no effect and cooldown instantly.
 - https://www.wowhead.com/spell=89792/flee has no effect and cooldown instantly.

VOIDSTALKER: https://www.wowhead.com/spell=697/summon-voidwalker He can attack in melee, but attacks a creature only within a certain radius, even if the melee attack was activated manually (sometimes it works as intended).
 - https://www.wowhead.com/spell=3716/consuming-shadows it cooldowns instantly and has an incorrect damage scaling (at level 60 it deals 5 damage units) at 10th level, the spell deals 0 damage units and gradually increases with level.
 - https://www.wowhead.com/spell=17767/shadow-bulwark It is triggered and has a cooldown time, but has no effect (when using a spell as an aura through a command, the buff is present for 5 seconds out of 20 and has no effect on the pet). 
 
 FELHUNTER: https://www.wowhead.com/spell=691/summon-felhunter The pet's behavior is working fine.
 - https://www.wowhead.com/spell=54049/shadow-bite It does not always work, but it can be activated without a cooldown.
 
 SAYAAD: https://www.wowhead.com/spell=366222/summon-sayaad The pet's behavior is working fine.
 - https://www.wowhead.com/spell=7814/lash-of-pain has no effect and cooldown instantly.
 - https://www.wowhead.com/spell=7870/lesser-invisibility Sometimes it works, but often has no effect and cooldown instantly (If it works, the pet will endlessly use the spell, even if it has an active aura on it, since there is no cooldown).
 
 P.S Testing was carried out on a character with standard items that are issued when it is created.

### Expected behaviour

The listed spells should work, and the behavior of pets should work correctly. The pet's interface should not disappear when re-entering the world.

### Steps to reproduce the problem

1. Create a character with the Warlock class
2. Level up your character to level 60 (I tested it on this one)
3. Try to summon pets from the list and use their abilities on the enemy.

### Branch

master

### TC rev. hash/commit

0c32277

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Faq** [comment]
Better divide issues, one per pet.

**Comment by KamiliaBlow** [comment]
> Better divide issues, one per pet.

It seems to me that this does not make sense, since pets do not individually have their own implementation in behavior, but work according to a single petai system. Their spells also do not require implementation (at least wowhead does not show the need for server scripts for effect 1, for all listed spells) it is effect 1 that does not work, which does not require complex implementation in the form of a separate script for each spell separately.

**Comment by Nyr97** [comment]
It's not an issue of warlock's pet only, it's an issue on all pets since their system is old.

**Comment by KamiliaBlow** [comment]
The problem seems to be that once the character gains a level, the pet's class changes. His energy bar turns into a mana bar, so they can't cast spells!

**Comment by KamiliaBlow** [comment]
I managed to fix this, but I don’t know how correct this is to fix it, I added a new line to Unit.cpp
```
              {
                    if (pet->getPetType() == HUNTER_PET) // Hunter pets have focus
                        displayPower = POWER_FOCUS;
                    else if (pet->IsWarlockPet()) // Warlock pets have energy (I added this line to the code)
                        displayPower = POWER_ENERGY;
                    else if (pet->IsPetGhoul() || pet->IsPetAbomination()) // DK pets have energy
                        displayPower = POWER_ENERGY;
                }
```
The problem with cooldowns for some spells still remains, but the behavior of pets seems to be normal (due to the fact that the pet received mana instead of energy, when autocast was turned on, it tried to cast a spell for which it did not have the power)
