### ISSUE TITLE
NPC: Elder Torntusk

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/TrinityCore#29792]
### Description

Elder Torntusk remains in a sleep/dead state during encounter.

<details>

![image](https://github.com/TrinityCore/TrinityCore/assets/66294837/f3ea2e69-b61d-49aa-95e2-06e792a9f5c2)

</details>

### Expected behaviour

Should be on their feet during combat.

Note: Possibly related to original script [here](https://github.com/TrinityCore/TrinityCore/issues/22706). 

### Steps to reproduce the problem

1. Approach NPC - they are dead/sleeping 

<details>

![image](https://github.com/TrinityCore/TrinityCore/assets/66294837/44928619-9e97-41ac-875a-88391cafc432)

</details> 

2. Engage in combat
3. They remain in a dead/sleeping state but attack 

<details>

![image](https://github.com/TrinityCore/TrinityCore/assets/66294837/2194bb82-ea5f-417f-8ea3-9b14e006ff1d)

</details>

Notes: 
- I am not on a specific quest (Farming wildvine from NPCs).
- With a caster he approaches you in the downed state.
- With Hunter and wolf aggro they remain on the alter, attacking in the downed state.

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. ef048d7c3db4 2024-03-03 18:28:06 +1100 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows 10

### Custom changes

NPCBots

**Comment by Jonne733** [comment]
@TQPS 
Try and see if this script fixes it.

```sql
-- Fix for "Elder Torntusk" when attacking him
-- Remove "StandState" flag "Dead" from template_addon
UPDATE `creature_template_addon` SET `StandState`=0 WHERE `entry`=14757;

-- Script
DELETE FROM `smart_scripts` WHERE `entryorguid`=14757 AND `source_type`=0 AND `id` IN (1,2);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(14757,0,1,0,25,0,100,0,0,0,0,0,90,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Elder Torntusk - On Reset - Set Flag Standstate 'Dead'"),
(14757,0,2,0,4,0,100,0,0,0,0,0,91,7,0,0,0,0,0,1,0,0,0,0,0,0,0,"Elder Torntusk - On Aggro - Remove Flag Standstate 'Dead'");


```
What is fixes:

1. Move creature flag "Dead" from "creature_template_addon" to "Smart_Script".
2. Remove flag when he aggros an hostile player or creature so that he no longer appears dead when fighting.

Comments and feedback on the script are welcomed. :smiley:

**Comment by TQPS** [comment]
This works perfectly! Thank you!

- You approach and they are on the alter in the downed state
- You attack and they come at your on their feet
- They die in the downed state

Thank you. That's been annoying for about 2 years.

**Comment by Jonne733** [comment]
@TQPS 
You're welcome.  😊
