### ISSUE TITLE
SQL fail during server startup

### ISSUE THREAD

**Issue by DeerHunt3r** [TrinityCore/TrinityCore#29798]
### Description

Errors during game startup: new installation

**DB Errors log:**
>>In mysql_stmt_prepare() id: 39, sql: "SELECT entry, KillCredit1, KillCredit2, name, femaleName, subname, TitleAlt, IconName, RequiredExpansion, VignetteID, faction, npcflag, speed_walk, speed_run, scale, Classification, dmgschool, BaseAttackTime, RangeAttackTime, BaseVariance, RangeVariance, unit_class, unit_flags, unit_flags2, unit_flags3, family, trainer_class, type, VehicleId, AIName, MovementType, ctm.Ground, ctm.Swim, ctm.Flight, ctm.Rooted, ctm.Chase, ctm.Random, ctm.InteractionPauseTimer, ExperienceModifier, RacialLeader, movementId, WidgetSetID, WidgetSetUnitConditionID, RegenHealth, CreatureImmunitiesId, flags_extra, ScriptName, StringId FROM creature_template ct LEFT JOIN creature_template_movement ctm ON ct.entry = ctm.CreatureId WHERE entry = ? OR 1 = ?"
Unknown column 'ctm.Ground' in 'field list'

**Partial, Server Log:**
>> Hotfixes database is up-to-date! Containing 0 new and 626 archived updates.
Could not prepare statements of the World database, see log for details.

### Expected behaviour

Server starts normally

### Steps to reproduce the problem

Fresh install, new DB new compile, first run..

### Branch

master

### TC rev. hash/commit

Not sure what goes here

### Operating system

Widows server 2019

### Custom changes

NONE

**Comment by DeerHunt3r** [comment]
Looks like SQL patch, 2024_02_29_00_World.sql.  dropped the columns.

-- Conversion done. Drop old columns
ALTER TABLE `creature_movement_override`   
	DROP COLUMN `Ground`, 
	DROP COLUMN `Swim`, 
	DROP COLUMN `Flight`, 
	DROP COLUMN `Rooted`;

ALTER TABLE `creature_template_movement`   
	DROP COLUMN `Ground`, 
	DROP COLUMN `Swim`, 
	DROP COLUMN `Flight`, 
	DROP COLUMN `Rooted`;

**Comment by Ovahlord** [comment]
Update your core. You're using an outdated core on an updated database. That's your mistake. These columns have been deprecated and removed by a recent commit.
