### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by aquadeus** [TrinityCore/TrinityCore#29800]
### Description

https://gist.github.com/aquadeus/6c03035d1f349786ef06dd33bbac8a6f

### Expected behaviour

Not to crash

### Steps to reproduce the problem

.go areatrigger 6958 with gm on and wait until crash

### Branch

3.3.5

### TC rev. hash/commit

1f3ebbb23cea1778ddc5ca52941861a98b667530

### Operating system

Windows 10 Pro

### Custom changes

None

**Comment by Shauren** [comment]
Aspiring Trainee's SAI seems to crash

**Comment by aquadeus** [comment]
was my bad, closed
