### ISSUE TITLE
Sometimes client does "freeze" for < a second first time when you open loot window

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29811]
### Description

I noticed this for some quite some time now, when you first open the loot window on a fresh killed creature (important) client will "freeze" a bit, but if you close window and reopen on same creature it won't occur.

Not sure if increased drop config affect this or not.

### Expected behaviour

 Maybe client not "freeze" at all.

### Steps to reproduce the problem

go and kill any npc that have some loot for example .go c id 30250
open loot window
notice

### Branch

3.3.5

### TC rev. hash/commit

93daeaea26ea0f317c328568058b04b30f84c8ad

### Operating system

Windows 11 x64

### Custom changes

[Passive anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/commits/3.3.5-passive_anticheat)

**Comment by CraftedRO** [comment]
https://github.com/TrinityCore/TrinityCore/assets/24683355/adf92c6f-2c23-4275-96ae-c82691598ce2

**Comment by Faq** [comment]
Try to do the same and log packets, there might be something.

**Comment by CraftedRO** [comment]
[World_parsed.txt](https://github.com/TrinityCore/TrinityCore/files/14623898/World_parsed.txt)
I only see missing CMSG_LOOT_RELEASE and that there's one milisecond difference between CMSG_SET_SELECTION and CMSG_LOOT_UNIT for 31265 (Savage Proto-Drake) Low: 1823, does exist a page with these opcode explained ?

**Comment by CraftedRO** [comment]
client also freeze hard first time when you kill a boss that award an achievement like [Lord Marrowgar](https://www.wowhead.com/wotlk/npc=36612/lord-marrowgar) for example

**Comment by DykeRz** [comment]
Delete your addons

**Comment by CraftedRO** [comment]
looks like it wasn't addons but rather hard disk drive, most likely on ssd / m.2 it doesn't occur.
