### ISSUE TITLE
[QUEST] The winner of the meaty giant

### ISSUE THREAD

**Issue by vahzxz** [TrinityCore/TrinityCore#29822]
### Description

The problem is that the quest works, but only in the GM. It is required to remove all NPCs from invisibility and then this issue will be resolved
QUEST: https://www.wowhead.com/wotlk/quest=13235
![image](https://github.com/TrinityCore/TrinityCore/assets/37352351/66de885f-60bc-4c17-8d74-7360c81e8cba)
![image](https://github.com/TrinityCore/TrinityCore/assets/37352351/da529cda-b16a-49e0-b883-48baca3e23df)

### Expected behaviour

NPCs should be visible.

### Steps to reproduce the problem

Take quest 13235

### Branch

3.3.5

### TC rev. hash/commit

73fdf91a5b27ca4c8037665f0067e71c759c2710

### Operating system

Win Server 2022

### Custom changes

No

**Comment by Aokromes** [comment]
not invisibility, incorrect phase for player, very likely missing spell area.

creature 
[16:18:12] Map: 571 (Northrend) Zone: 210 (Icecrown) Area: 4531 (The Fleshwerks) Phase: 64
player
[16:19:16] Map: 571 (Northrend) Zone: 210 (Icecrown) Area: 4531 (The Fleshwerks) Phase: 1

**Comment by vahzxz** [comment]
> this is the previous required quest that change the phase https://www.wowhead.com/wotlk/quest=13144/killing-two-scourge-with-one-skeleton

Everything works thanks)
