### ISSUE TITLE
Can't buy any guild-bag-slot after creating a guild. 

### ISSUE THREAD

**Issue by kanmt** [TrinityCore/TrinityCore#29826]
### Description

Whether using the GM command, or modifying the minimum number of signatures in worldserver.conf to create a guild normally, guild bag slot cannot be purchased in the game.

### Expected behaviour

Regardless of the method used, we should be able to purchase Guild bag slot.

### Steps to reproduce the problem

1. create a guild by gm command, or Normally by modifying the minimum number of signatures
2. go to bank, opening guild bags
3. you'll find that, All slot are disabled, and can't be purchased 

### Branch

3.3.5

### TC rev. hash/commit

b2c723c6b4fb3494cb08522023791db6b2a096c0

### Operating system

Debian 12

### Custom changes

None

**Comment by kanmt** [comment]
TC rev. hash/commit
b2c723c6b4fb3494cb08522023791db6b2a096c0

**Comment by CraftedRO** [comment]
6a54dc5a34665e54937d1300e73a087b5938c1ab Cannot reproduce: https://youtu.be/tq4kkOS5FXM

**Comment by Aokromes** [comment]
be sure you have enough money on the guild master character.
