### ISSUE TITLE
Crash Core when Kill a Monster on Map 2695

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29829]
### Description

Tele to map 2695 and spawn a mob. (f.e. .npc add 2559) and try to kill this creature....

Btw. When you relogin, the npc is not visable on this map.

### Expected behaviour

Core wont Crash and the NPC will be seeable after relogin/serverrestart

### Steps to reproduce the problem

Tele to map 2695 and spawn a mob. (f.e. .npc add 2559) and try to kill this creature....

Btw. When you relogin, the npc is not visable on this map.

### Branch

master

### TC rev. hash/commit

6cd4607a65f10b4b80320d9dd87750032d6ad649

unknown_worldserver.exe_[23-3_20-57-5].dmp
unknown_worldserver.exe_[23-3_20-57-5].txt

### Operating system

Windows Server 2022

### Custom changes

Custom Spawn

**Comment by Shauren** [comment]
You failed to attach crash logs

**Comment by coreretail6** [comment]
[unknown_worldserver.exe_[23-3_20-57-5].dmp](https://github.com/TrinityCore/TrinityCore/files/14733560/unknown_worldserver.exe_.23-3_20-57-5.dmp)
[unknown_worldserver.exe_[23-3_20-57-5].txt](https://github.com/TrinityCore/TrinityCore/files/14733561/unknown_worldserver.exe_.23-3_20-57-5.txt)

**Comment by Shauren** [comment]
meh, the log is completely useless (its from release, probably not even for this exe you used)

**Comment by coreretail6** [comment]
Better? 
[unknown_worldserver.exe_[24-3_0-1-31].dmp](https://github.com/TrinityCore/TrinityCore/files/14733809/unknown_worldserver.exe_.24-3_0-1-31.dmp)
[unknown_worldserver.exe_[24-3_0-1-31].txt](https://github.com/TrinityCore/TrinityCore/files/14733810/unknown_worldserver.exe_.24-3_0-1-31.txt)

**Comment by meji46** [comment]
There is no difficulty for the map (https://wago.tools/db2/MapDifficulty?filter[MapID]=2695&page=1&build=10.2.6.53877, probably missing hotfix) so it crashes here: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Item/ItemBonusMgr.cpp#L86 (a simple check returning Context none would be enough)
