### ISSUE TITLE
Missile Barrage proc regression

### ISSUE THREAD

**Issue by ckegg** [TrinityCore/TrinityCore#29827]
### Description

Missile Barrage aura won't consume after Arcane Missiles is used, and you can spamming Arcane Missiles
Same behavior just like https://github.com/TrinityCore/TrinityCore/issues/21466 and https://github.com/TrinityCore/TrinityCore/issues/21670
It happens after this commit 08664aa07f911c84d9c6ecae56f67401faf90016

### Expected behaviour

Missile Barrage aura consumed after Arcane Missiles

### Steps to reproduce the problem

See video: https://mega.nz/file/FIojWKoA#qH24XeYwHNIT3HiiquxM0D-b4MWvuHoHbpcVceI_SHA

### Branch

3.3.5

### TC rev. hash/commit

3.3.5 6a54dc5a34665e54937d1300e73a087b5938c1ab

### Operating system

Debian 11

### Custom changes

None

**Comment by CraftedRO** [comment]
6a5fa255fe053796588684e3876f6047cf92a08f Confirm, now arcane mages looks like machine guns.
