### ISSUE TITLE
Lightforged Draenei can't create Monk

### ISSUE THREAD

**Issue by V-Cyberpunk** [TrinityCore/TrinityCore#29830]
### Description

Lightforged Draenei can't create monk

### Expected behaviour

creating a monk with Lightforged Draenei should be possible

### Steps to reproduce the problem

go to char creation and try to create lightforged draenei monk.

### Branch

master

### TC rev. hash/commit

 6cd4607a65f1

### Operating system

Debian 12 x64

### Custom changes

RetailCore DB

**Comment by Shauren** [comment]
> RetailCore DB? 

not our problem

**Comment by V-Cyberpunk** [comment]
ok, i will tell it retailcore :)
