### ISSUE TITLE
Quest: Toxic Tolerance never updates

### ISSUE THREAD

**Issue by Loginisalreadytaken** [TrinityCore/TrinityCore#2986]
I have tried boxing them, whacking them with the staff, wand shooting, killing and letting four of them hit me for 30 minutes without a single update - they don't even attempt to poison; not at any amount of health left (on them).

Version: 3.3.5a (12340)
Core revision: Trinity Core 14b3ed91647b+
Database revision: TDB 335.11.42

**Comment by Rushor** [comment]
i remeber that i got this debuff even with level 80 very easily, i will test it later again

**Comment by Killyana** [comment]
Tested on rev. ebf5b18fbc41  the spell cannot miss, and the I get quest credit correctly.
