### ISSUE TITLE
DB/QUEST: The quest "Rite of Strength" is missing reward next quest

### ISSUE THREAD

**Issue by Jonne733** [TrinityCore/TrinityCore#29879]
### Description

The Quest ["Rite of Strength"](https://aowow.trinitycore.info/?quest=757) (757) is missing reward next quest.

All info is from live Wrath Classic server.

### SQL fix

```sql
-- Quest is missing Reward next quest
UPDATE `quest_template` SET `RewardNextQuest`=763 WHERE `Id`=757;
```

### Branch

3.3.5

### TC rev. hash/commit

75cbafd

**Comment by CraftedRO** [comment]
Jonne's on fire 💯
