### ISSUE TITLE
DB/Phases: Correct phases 20685 and 20686

### ISSUE THREAD

**Issue by aquadeus** [TrinityCore/TrinityCore#29872]
### Description

Correct phases 20685 and 20686

### SQL fix

```sql
UPDATE `phase_name` SET `ID`=20686 WHERE `ID`=26686;
UPDATE `phase_name` SET `ID`=20685 WHERE `ID`=26685;
```

### Branch

master

### TC rev. hash/commit

4131022f6c8283d387f1cdc8f2f1e8df9375ea54

**Comment by Aokromes** [comment]
you know, you can use update, and if no delete from phase name where id IN (bla,bla);
