### ISSUE TITLE
About the 3.3.5 GM command additem set 

### ISSUE THREAD

**Issue by tutengjun** [TrinityCore/TrinityCore#29881]
### Description

An item error occurred when using.additem set #itemsetid. According to the documentation, the item in Itemset.dbc should be added, but an item matching the database table item_template, column Itemset is obtained.

### Expected behaviour

Get the same item as Itemset.dbc ItemID_1 to ItemID_17

### Steps to reproduce the problem

.additem set 788

### Branch

3.3.5

### TC rev. hash/commit

None

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by CraftedRO** [comment]
Please update your core, the command works well on 571f3639ad8871df433bd000a58d70d24214d7a2

![WoWScrnShot_040124_144248](https://github.com/TrinityCore/TrinityCore/assets/24683355/598c725a-04c7-4110-8b16-e718780bd628)
