### ISSUE TITLE
3.3.5 Profession/Item Cooldowns bugging out (visually) after map change/map transfer

### ISSUE THREAD

**Issue by MrSmitey** [TrinityCore/TrinityCore#29884]
### Description

I've encountered a very weird bug where the Hearthstone cooldown disappears, client side and only visually.

This happens when changing maps or zones in the world in 3.3.5 Trinitycore. It's annoying because a given player can't see how much time is left for the cooldown to reset.

I’ve done some research and some people have suggested this being a packet issue as the client expects a certain order of these being sent.

Is there a way to call in an update to CDs or spells to perhaps fix this? Or if anyone else found a similar issue or a smart solution? Any help would or suggestions would be greatly appreciated.

### Expected behaviour

Hearthstone/items remaining cooldown showing in item hover/mouse over

### Steps to reproduce the problem

1) Get Hearthstone
2) Use Hearthstone
3) Teleport to a different map/continent
4) Cooldown is gone on item (only visually/client side)

### Branch

3.3.5

### TC rev. hash/commit

rev. 504fcfb2fdd0+ 2022-09-23

### Operating system

Windows 10 x64

### Custom changes

None

**Comment by Aokromes** [comment]
lol, you are reporting a bug on a almost 2 years old custom core.

**Comment by MrSmitey** [comment]
It's a known issue across even on up-to-date revisions though

**Comment by AzAtWar** [comment]
Can also confirm on latest too. IMO the issue is an incomplete SendInitialSpells in player.cpp
