### ISSUE TITLE
Hunter/Spell: Flare shoud remove Stealth right away

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29903]
### Description

Hunter Flare shoud remove Stealth right away while target is inside radius, atm it does nothing if casted on a stealthed target but only if target leave flare radius area and re-enter inside will be affected.

https://youtu.be/0mHpIu-5Aqo

Similar issue might be here https://github.com/TrinityCore/TrinityCore/issues/29605

### Expected behaviour

Flare shoud remove Stealth right away as you can see here (use slow playback speed): https://youtu.be/5Riwc5dJ1AE?t=30

### Steps to reproduce the problem

create a hunter and a rogue/druid
duel eachother
with rogue / druid enter Stealth / Prowl
with hunter place flare directly on rogue / druid
notice

### Branch

3.3.5

### TC rev. hash/commit

2ae8c0d32da8a5cb167de82e93c993a4f7145418

### Operating system

Windows 11 x64

### Custom changes

[Passive anticheat](https://github.com/TrinityCore/TrinityCoreCustomChanges/commits/3.3.5-passive_anticheat)

**Comment by r0m1ntik** [comment]
Perhaps this commit broke https://github.com/TrinityCore/TrinityCore/commit/3306a4d06cc557967c23adcc60c2e3257811b324

**Comment by CraftedRO** [comment]
[Possible fix](https://github.com/Project-Epoch/TrinityCore/commit/144769fceaf7985f2c4f96fae1b7785e65d857b6#diff-0d2a44370e18523042eca998013bf68fa21f38524f406c0ccdfd557f62342a30)
