### ISSUE TITLE
DB/Wandering isle: Add playerconditions for weapon racks at initial zone

### ISSUE THREAD

**Issue by aquadeus** [TrinityCore/TrinityCore#29911]
### Description

^

### SQL fix

```sql
UPDATE `gameobject_loot_template` SET `QuestRequired`=0 WHERE `Entry` IN (40856, 40859, 40860, 40861, 40862, 40863, 40864);

DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 34 AND `SourceEntry` IN (13360, 13361, 13362, 13363, 13364, 13365, 13366));
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
-- Monk
(34, 0, 13360, 0, 0, 2, 0, 73209, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13360 if player doesn\'t have item 73209'),

-- Warlock and Mage
(34, 0, 13361, 0, 0, 2, 0, 76390, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13361 if player doesn\'t have item 76390'),
(34, 0, 13361, 0, 0, 2, 0, 76392, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13361 if player doesn\'t have item 76392'),

-- Hunter
(34, 0, 13362, 0, 0, 2, 0, 73211, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13362 if player doesn\'t have item 73211'),

-- Priest
(34, 0, 13363, 0, 0, 2, 0, 73207, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13363 if player doesn\'t have item 73207'),
(34, 0, 13363, 0, 0, 2, 0, 76393, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13363 if player doesn\'t have item 76393'),

-- Warrior
(34, 0, 13364, 0, 0, 2, 0, 73213, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13364 if player doesn\'t have item 73213'),
(34, 0, 13364, 0, 0, 2, 0, 76391, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13364 if player doesn\'t have item 76391'),

-- Rogue
(34, 0, 13365, 0, 0, 2, 0, 73208, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13365 if player doesn\'t have item 73208'),
(34, 0, 13365, 0, 0, 2, 0, 73212, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13365 if player doesn\'t have item 73212'),

-- Shaman
(34, 0, 13366, 0, 0, 2, 0, 73213, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13366 if player doesn\'t have item 73213'),
(34, 0, 13366, 0, 0, 2, 0, 76391, 1, 0, 1, 0, 0, '', 'Satisfy PlayerCondition 13366 if player doesn\'t have item 76391');
```

### Branch

master

### TC rev. hash/commit

58839b7c18f4d0662ee407887ec1323040420d5a

**Comment by mdX7** [comment]
dont we want ElseGroups here?

**Comment by aquadeus** [comment]
these playerconditions are for different gobs with different phases (one for each panda class)

**Comment by Shauren** [comment]
Not quite, tested on ptr
* Monk - broken, always enabled
* Warrior - broken, always enabled
* Shaman - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)
* Hunter - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)
* Mage - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)
* Rogue - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)
* Priest - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)
* Warlock - blocked if you have quest item in inventory (without quest: targetable, gives Invalid Target on use, with quest: uninteractible if complete)

Seems like the intention was to block them when you already have these items, not tied to quest status

**Comment by aquadeus** [comment]
on retail you can create a character and go directly to loot the gob without quest and it will gives you the items lol (just tested)

**Comment by aquadeus** [comment]
should i attach the conditions to items then?

**Comment by Shauren** [comment]
Yes

**Comment by aquadeus** [comment]
ok

**Comment by Shauren** [comment]
Oh btw, updating interaction is wonky even on retail, don't worry too much about it

**Comment by aquadeus** [comment]
yeah i noticed that xd good to know, thanks

**Comment by aquadeus** [comment]
ok now should work, but in my localhost is only updating the playercondition to the gameobject i loot, should be updating all gameobjects, here is the thing:

https://gyazo.com/b6ba1106a4a6a06dc7b8a6bff8b337e1

**Comment by Shauren** [comment]
Ironically its the object you are looting that behaves differently from retail

**Comment by aquadeus** [comment]
wtf xd but its because the conditions are wrong? or what is happening here?

**Comment by Shauren** [comment]
It's because the rack doesnt despawn/respawn on retail
