### ISSUE TITLE
Core: Unable to teleport after latest commit

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#29919]
### Description

Well not sure if happen clean build too but I'm using [Passive Anticheat Diff](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-passive_anticheat.diff)

https://youtu.be/33YkqersZOk

### Expected behaviour

You shoud be able to teleport or use any portal as before

### Steps to reproduce the problem

take any portal or use any teleport
notice worldserver / log

### Branch

3.3.5

### TC rev. hash/commit

d6ccdbea10a29091afc20471331f50260f65ac46

### Operating system

Windows 11 x64

### Custom changes

[Passive Anticheat Diff](https://github.com/TrinityCore/TrinityCoreCustomChanges/compare/3.3.5...3.3.5-passive_anticheat.diff)

**Comment by Ovahlord** [comment]
whats the spell_target_position entry for that said spell in the error logs?

**Comment by CraftedRO** [comment]
well I'll update issue, seems valid for all kind of teleports, even teleport to moonglade or death gate.

**Comment by Shauren** [comment]
Eh, d6ccdbea10a29091afc20471331f50260f65ac46 might have messed it up

**Comment by CraftedRO** [comment]
no problem, we know you will handle it in no time.

**Comment by Shauren** [comment]
eba78de1eeb824fec5fcdc50fc08196419605b7c
