### ISSUE TITLE
DB/Wandering isle: Fix visibility condition for phase 630

### ISSUE THREAD

**Issue by aquadeus** [TrinityCore/TrinityCore#29918]
### Description

Spell 106205 only affects player with EFFECT_1 instead of EFFECT_0 (changed in my localhost but i forget to add it in the sql mb)
introduced in https://github.com/TrinityCore/TrinityCore/commit/a3f760e38338c9ca4159e315ae99ac2f04491e95

### SQL fix

```sql
UPDATE `conditions` SET `ConditionValue2`=1 WHERE `SourceTypeOrReferenceId`=26 AND `SourceGroup`=630 AND `ConditionTypeOrReference`=1 AND `ConditionValue1`=106205;
```

### Branch

master

### TC rev. hash/commit

a3f760e38338c9ca4159e315ae99ac2f04491e95

**Comment by Aokromes** [comment]
plz for future references add updates https://github.com/TrinityCore/TrinityCore/pull/17021 

:)
