### ISSUE TITLE
Boss Dark Shaman Koranthal's skill effects can't be displayed 

### ISSUE THREAD

**Issue by wowshub** [TrinityCore/TrinityCore#29933]
### Description

https://www.wowhead.com/npc=61412/dark-shaman-koranthal#drops;mode:normal

https://youtu.be/_k2ySATsxNA

SET @ENTRY := 61412;
UPDATE creature_template SET AIName='SmartAI' WHERE entry=@ENTRY;
DELETE FROM smart_scripts WHERE source_type=0 AND entryorguid=@ENTRY;
INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(@ENTRY,0,0,0,1,0,100,1,1000,1000,1000,1000,11,21157,2,0,0,0,0,1,0,0,0,0,0,0,0,'Cast Dark Aura on Spawn'),
(@ENTRY,0,1,0,7,0,100,1,0,0,0,0,11,21157,2,0,0,0,0,1,0,0,0,0,0,0,0,'Cast Dark Aura on Evade'),
(@ENTRY,0,2,0,0,0,100,0,5000,8000,15000,15000,11,119971,0,0,0,0,0,2,0,0,0,0,0,0,0,'Cast Shadow Storm'),
(@ENTRY,0,3,0,0,0,100,0,0,0,3400,4700,11,119300,64,0,0,0,0,2,0,0,0,0,0,0,0,'Cast Twisted Elements');

How to fix the problem of the skill effect of this boss?
Import the SQL as above to fix the boss and release these 4 spells, as shown in the figure: we can see that the boss is casting this spell but there is no magic effect at all, only the boss's action and the action bar for casting。
The Twisted Elements spell does some damage to the player, the Shadow Storm spell does no damage at all, the Dark Aura on Spawn and Dark Aura on Evade have no effect at all, and there is no sign of magic on the ground.

If I use ScriptName to fix the BOSS via C++ code, how exactlyThank you!

### Expected behaviour

https://www.youtube.com/watch?v=_k2ySATsxNA
https://www.wowhead.com/npc=61412/dark-shaman-koranthal

### Steps to reproduce the problem

.go xyz 1805 -4400 -17 1
enter into dungeon 
.npc add 61412

### Branch

master

### TC rev. hash/commit

![shadow strom](https://github.com/TrinityCore/TrinityCore/assets/157596749/84b9ec44-f494-46a1-8d69-c2809f9887bc)
![twisted element](https://github.com/TrinityCore/TrinityCore/assets/157596749/8fe22067-2bb6-4c56-ae57-2413a5258388)

### Operating system

windows10

### Custom changes

no custom changes

**Comment by aquadeus** [comment]
seems like TC has the old spawns, the areas on the floor probably are dummies with auras, Shadow Storm needs to be scripted

**Comment by Shauren** [comment]
Visuals fixed by 8d8a54db2568ef88b21530e1f7e1532f1bee08cd
