### ISSUE TITLE
Adarogg boss  Cast Inferno Charge on Aggro have not effect 

### ISSUE THREAD

**Issue by wowshub** [TrinityCore/TrinityCore#29948]
### Description

Adarogg boss

https://www.youtube.com/watch?v=qFKavyBz7Vw
https://www.wowhead.com/npc=61408/adarogg
https://www.wowhead.com/spell=119405/inferno-charge

 use  this sql  the Inferno Charge only have   the action bar for casting but have not Charge  action 

SET @ENTRY := 61408;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `source_type`=0 AND `entryorguid`=@ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,4000,6000,10000,15000,11,119405,0,0,0,0,0,2,0,0,0,0,0,0,0,'Cast Inferno Charge on Aggro'),
(@ENTRY,0,1,0,0,0,100,0,5000,8000,15000,17000,11,119420,0,0,0,0,0,2,0,0,0,0,0,0,0,'Cast Flame Breath');

how to fix this bugs?  ty

### Expected behaviour

https://www.youtube.com/watch?v=qFKavyBz7Vw

### Steps to reproduce the problem

.go xyz 1805 -4400 -17 1
enter into dungeon
.npc add 61408

### Branch

master

### TC rev. hash/commit

![inferno-charge](https://github.com/TrinityCore/TrinityCore/assets/157596749/02da4051-a97b-45e9-8aa3-606e45531333)

### Operating system

windows10

### Custom changes

no

**Comment by Naddley** [comment]
We dont have this Dungeon spawned with updated spawns (Aquadeus has a not yet merged fix for spawns)
The Boss will need a c++ Bossscript.

**Comment by wowshub** [comment]
> We dont have this Dungeon spawned with updated spawns (Aquadeus has a not yet merged fix for spawns) The Boss will need a c++ Bossscript.

OK  looking forward your c++ boss script and  Inferno Charge skill script

**Comment by wowshub** [comment]
> inferno charge is tricky, they use serverside spells for the charge effect as you can see in my pr

well done !
