### ISSUE TITLE
Button for creating new character is gone

### ISSUE THREAD

**Issue by V-Cyberpunk** [TrinityCore/TrinityCore#29967]
### Description

there is no button for creating a character
![image](https://github.com/TrinityCore/TrinityCore/assets/44802344/6e191b6a-400d-436c-b82d-dd2927d6680a)

### Expected behaviour

there should be a button for creating a character

### Steps to reproduce the problem

go to char selection screen

### Branch

master

### TC rev. hash/commit

468a06b

### Operating system

Debian 12 x64

### Custom changes

-

**Comment by Aokromes** [comment]
maybe to much characters?

**Comment by V-Cyberpunk** [comment]
no
![image](https://github.com/TrinityCore/TrinityCore/assets/44802344/c1009b86-cee9-4720-b16e-c40f6dc438a1)

**Comment by V-Cyberpunk** [comment]
and with 10.2.6 always was fine

**Comment by MaxtorCoder** [comment]
Are you sure you are using the 10.2.7 client?

**Comment by MaxtorCoder** [comment]
That is related to either `SMSG_AUTH_RESPONSE` or `SMSG_FEATURE_SYSTEM_STATUS(_GLUE_SCREEN)`

**Comment by MaxtorCoder** [comment]
@Shauren fix when :D
