### ISSUE TITLE
Crash after click on NPC with a gossip and much much queststarter options 

### ISSUE THREAD

**Issue by coreretail6** [TrinityCore/TrinityCore#29965]
### Description

click on an npc with much much queststarter options 

<img width="1003" alt="Bildschirmfoto 2024-05-08 um 19 35 31" src="https://github.com/TrinityCore/TrinityCore/assets/132657906/b7f57bd7-4c20-4454-8abf-cb1716019d23">

### Expected behaviour

not crash the core

### Steps to reproduce the problem

 
[unknown_worldserver.exe_[9-5_0-14-19].dmp](https://github.com/TrinityCore/TrinityCore/files/15255576/unknown_worldserver.exe_.9-5_0-14-19.dmp)
[unknown_worldserver.exe_[9-5_0-14-19].txt](https://github.com/TrinityCore/TrinityCore/files/15255577/unknown_worldserver.exe_.9-5_0-14-19.txt)

### Branch

master

### TC rev. hash/commit

468a06baf046b716305ee665e3cfd93c80e99457

### Operating system

Windows Server 2022

### Custom changes

some custom spawns

**Comment by Shauren** [comment]
Do your "some custom spawns" include a npc with a ton of gossip menu items?

**Comment by taube11111** [comment]
No, but the npc got a lot of  creature_queststarter entrys and it worked on 10.2 (the last time i tested it) without problems.

**Comment by Ovahlord** [comment]
the crash is caused by an npc in the alliance garrison. creature appears to be  https://www.wowhead.com/npc=77209/baros-alexston

**Comment by taube11111** [comment]
No, but the npc got a lot of  creature_queststarter entrys and it worked on 10.2 (the last time i tested it) without problems. 
background: i made for the wod garrisons a questline where every buildings and mapswap got their own phase with an own quest with simelar requirements... sounds a bit dummy to pros, but its my database solution for garrisons. I m not a coder but likes to work with the database. 

![IMG_6345](https://github.com/TrinityCore/TrinityCore/assets/116520090/0fb39083-b356-41b6-8160-93898233d099)
![IMG_6344](https://github.com/TrinityCore/TrinityCore/assets/116520090/69f713ad-1626-4cef-a67e-993da2f644b4)
![IMG_6343](https://github.com/TrinityCore/TrinityCore/assets/116520090/d49b4cce-3697-4a4a-a9a9-919a8e846156)

**Comment by coreretail6** [comment]
No, but the npc got a lot of creature_queststarter entrys and it worked on 10.2 (the last time i tested it) without problems.
background: i made for the wod garrisons a questline where every buildings and mapswap got their own phase with an own quest with simelar requirements... sounds a bit dummy to pros, but its my database solution for garrisons. I m not a coder but likes to work with the database.
![329077919-0fb39083-b356-41b6-8160-93898233d099](https://github.com/TrinityCore/TrinityCore/assets/132657906/8bc2a25d-a526-43ad-8e80-db9ea1d3f07c)
![329077926-69f713ad-1626-4cef-a67e-993da2f644b4](https://github.com/TrinityCore/TrinityCore/assets/132657906/f1cead57-aa81-4255-b82e-a810286ea7c6)
![329077929-d49b4cce-3697-4a4a-a9a9-919a8e846156](https://github.com/TrinityCore/TrinityCore/assets/132657906/f7a63f0f-d9f3-4bff-b8aa-9b115753e5a4)
