### ISSUE TITLE
 Pet Battles

### ISSUE THREAD

**Issue by Coolzero** [TrinityCore/TrinityCore#29970]
### Description

Can't do pet battles. Can train and get quests to battle but there isn't any battle pets around

### Expected behaviour

Pet battles

### Steps to reproduce the problem

Any critter in Goldshire

### Branch

master

### TC rev. hash/commit

TDB1027.24051

### Operating system

Windows 11 X64

### Custom changes

None

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/issues/29796
