### ISSUE TITLE
Combat-Skills increasing too fast on grey mobs due to integer underflow

### ISSUE THREAD

**Issue by Mat2095** [TrinityCore/TrinityCore#29983]
### Description

Due to https://github.com/TrinityCore/TrinityCore/pull/16006/commits/60311e0aae2ccf8b45db6c7d12c6337a3006198a an underflow can occur here: https://github.com/TrinityCore/TrinityCore/blob/400aef35a19f9a8f8b11d741cecaf9a4ac1d7d42/src/server/game/Entities/Player/Player.cpp#L5783 in the `Player::UpdateCombatSkills` method. Before it was certain that `moblevel >= greylevel`, but now this isn't the case. If `greylevel > moblevel`, then `moblevel - greylevel` will be negative, but `lvldif` is unsigned, so it wraps around, resulting in a very high chance to increase the combat-skill.

### Expected behaviour

Combat skills should have a low/moderate chance to increase when fighting grey mobs.

### Steps to reproduce the problem

1. Fight a mob within grey level range
2. Notice the combat skills increasing way too often; way more often than when fighting a mob within green level range

### Branch

3.3.5

### TC rev. hash/commit

83c403c870070151e58aa96b1faa203f4d1de929

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Mat2095** [comment]
AC fixed this in https://github.com/azerothcore/azerothcore-wotlk/commit/f75aceb9a9b45a97452aad5b658ac52042c7c8cf

**Comment by CraftedRO** [comment]
we don't really care about trashzerothcore and also this is not a big issue, if you ask me seems much more logically that the skill increase more on gray-level mobs that the other since their level is close to yours, and you also did not provide any proof.

**Comment by Mat2095** [comment]
> their level is close to yours

That's wrong, green-level mobs are closer to the player than gray-level mobs. Also in general the chance decreases the lower the mob-level is (`float chance = float(3 * lvldif * skilldif) / plevel;`). It is not logical to then suddenly increase the chance tenfold if the mob-level is below some level. And that is not done explicitly, but implicitly due to an integer underflow.

Some example calculation: Assume a level 60 player, a mob that is 1 level below gray-level, and the player is at 295/300 skill.
With the underflow the chance is calculated as `lvldif = 255`, `chance = 3 * 255 * 5 / 60 = 63.75`.
If the mob was one level higher, the chance would be calculated as `lvldif = 0`, but it has a minimum of 3, so `lvldif = 3`, `chance = 3 * 3 * 5 / 60 = 0.75`, but it has a minimum of 1%, so `chance = 1`.
Doesn't seem very logical to me to have an increase from 1% to over 60% by going down one level.

> we don't really care about trashzerothcore

This is not the right place for childish insults.

> you also did not provide any proof

In my opinion it is obvious from the code and the changes made in 60311e0aae2ccf8b45db6c7d12c6337a3006198a, that the underflow is an unintended side-effect that was simply overlooked at that time (I don't blame them). But if you want more proof, I can give the same source as the issue that introduced the underflow:
https://typhoonandrew.wordpress.com/2008/01/08/how-to-raise-your-weapon-skill/ second bullet-point
"If you swing 100 times at a level 1 mob you’ll gain the same amount as swinging at a much higher level mob."
It says you gain the "same amount", not a "much greater amount".
