### ISSUE TITLE
Compile error on msvc ScriptMgr.cpp

### ISSUE THREAD

**Issue by Maiievs** [TrinityCore/TrinityCore#29999]
### Description

I updated msvc compiler in Visual Studio today and now there is a compile error

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.0
Cmake shows version: MSVC: Minimum version required is 19.32, found 19.40.33808.0 - ok!

Error:
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2665	'CreatureGameObjectScriptRegistrySwapHooks<GameObject,GameObjectScript,Base>::VisitObjectsToSwapOnMap::<lambda_1>::<lambda_1>': no overloaded function could convert all the argument types
        with
        [
            Base=ScriptRegistry<GameObjectScript>
        ]	game	C:\Br16\src\server\game\Scripting\ScriptMgr.cpp	344		
Error	C2665	'CreatureGameObjectScriptRegistrySwapHooks<Creature,CreatureScript,Base>::VisitObjectsToSwapOnMap::<lambda_1>::<lambda_1>': no overloaded function could convert all the argument types
        with
        [
            Base=ScriptRegistry<CreatureScript>
        ]	game	C:\Br16\src\server\game\Scripting\ScriptMgr.cpp	344		
Error	LNK1181	cannot open input file '..\game\Debug\game.lib'	worldserver	C:\BuildBr\src\server\worldserver\LINK	1		

### Expected behaviour

No compile error

### Steps to reproduce the problem

Try compile with version above

### Branch

3.3.5

### TC rev. hash/commit

95b83b54ee97be584ac3a7176a977b6b1785e95a

### Operating system

Windows 10

### Custom changes

None

**Comment by Wulgrind** [comment]
Same thing here

**Comment by Wulgrind** [comment]
Is it also going to be fixed for the EluneTrinityWotlk ?

**Comment by Shauren** [comment]
Once they merge latest TrinityCore changes, yes

**Comment by Wulgrind** [comment]
OK, thanks
