### ISSUE TITLE
Cata mapextractor won't work

### ISSUE THREAD

**Issue by chinahvc** [TrinityCore/TrinityCore#30018]
### Description

When try to extract map files , tools won't work.

logs 
-------------------------------------------
======================================================
Trinitycore (master) DBC, Maps, VMaps & MMaps Extractor
======================================================

Client directory: /opt/Cataclysm-4.3.4.15595-enUS-x64
Data directory:   /opt/ctm-trinity-server/data

1) Extract DBC and Maps files
2) Extract Visual Maps (VMaps)
3) Extract Movement Maps (MMaps)
4) Extract all files
5) Clean up client
6) Quit
Enter choice: 4

Extracting DBC, gt, Camera and Maps files

-- Using /opt/ctm-trinity-server/bin/mapextractor
-- Copying extracted data to /opt/ctm-trinity-server/data
-- Creating /opt/ctm-trinity-server/data
-- Starting in 5 seconds
TrinityCore rev. 794928546220 2024-05-31 23:22:28 +0200 (cata_classic branch) (Unix, RelWithDebInfo, Static) (Map & DBC Extractor)
<Ctrl-C> to stop.

MPQ files found in Data directory!
This tool works only with World of Warcraft: Battle for Azeroth

To extract maps for Wrath of the Lich King, rebuild tools using 3.3.5 branch!

Press ENTER to exit...

### Expected behaviour

extract map data.

### Steps to reproduce the problem

1. Step 1 Git clone code branch cata_classic, compile with tools.
2. Step 2 Download client 4.3.4 and unzip.
3. Step 3 CP extract tools (4 file and extractor.sh) to client folder.
4. Step 4 Chmod 755 for 5 files and execute.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 794928546220 2024-05-31 23:22:28 +0200 (**cata_classic** branch) 

### Operating system

Ubuntu 22.04 x64

### Custom changes

None

**Comment by mdX7** [comment]
cataclysm_classic branch is targeting patch 4.4.0; not 4.3.4. That means you need 4.4.0 client, as the files have changed inbetween (structure wise)

4.3.4 is unsupported by TrinityCore, theres a fork for it though: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore
