### ISSUE TITLE
Error connecting to server - You were disconnected. (BLZ51914001)

### ISSUE THREAD

**Issue by sebastianciocarlan** [TrinityCore/TrinityCore#30028]
### Description

So, after a clean compilation of trinitycore, freshly installed and updated DBs, using sql update files included in the git clone, and using a retail version with build number 54988 (I even unninstalled the game and reinstalled it), using last Arctium version i get the mentioned error ( You were disconnected. (BLZ51914001)). Also created the user with the password. For some additional info, the server is not a local server, its hosted on a VPS withe the generated the SSL PEM and KEY files. I can provide the IP if needed, and any config file, crash log or command output in >10min. Any insights on this?
![imagen](https://github.com/TrinityCore/TrinityCore/assets/44316607/c5972eb9-96c3-48e0-97bf-a4d92ad0cda5)

### Expected behaviour

You should be able to log in with the created account

### Steps to reproduce the problem

1- Follow https://trinitycore.info to compile the server files from scratch.
2- Try to log in

### Branch

master

### TC rev. hash/commit

I will provide all debug commands necesary withing >10 mins if asked, I dont know exactly which command do you need.

### Operating system

W11x64

### Custom changes

I used some "older" worldserver.conf and bnetserver.conf, generated for 54904 build version.

**Comment by Aokromes** [comment]
use discord for connection issues.
