### ISSUE TITLE
Size-Modifying Auras While Mounted

### ISSUE THREAD

**Issue by Dhekren** [TrinityCore/TrinityCore#30035]
### Description

Any player with multiple size-modifying auras while mounted will cause a decrease in FPS for themselves and nearby players if they lose one of these auras while mounted and moving.

### Expected behaviour

Losing size-modifying auras while the character is mounted shouldn't cause any FPS effects.

### Steps to reproduce the problem

1) Use Ctrl + R to check FPS while doing the following steps
2) Use this macro:
.unaura 57724
.aura 24924
.aura 8212
.aura 58468
.aura 16711
.aura 34511
3) Mount
4)  Cancel Bloodlust aura (or let it expire) while moving around

### Branch

3.3.5

### TC rev. hash/commit

7fcb126fcb7cff945936a7f5e051b07ce0de8a7f

### Operating system

Windows

### Custom changes

None

**Comment by Shauren** [comment]
that is a client problem, we cannot do anything about it
