### ISSUE TITLE
Core: Guild bank tab - "That name is reserved. Enter a new name."

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30049]
### Description

While entering a specific name "Transmissions" for a guild bank tab result in following error: "That name is reserved. Enter a new name."

![WoWScrnShot_062024_171350](https://github.com/TrinityCore/TrinityCore/assets/24683355/03de59d7-5786-4778-8a59-d9489e1bec76)

### Expected behaviour

Well not sure if it's blizzlike or not but in cata ptr 4.4.0.5541 you are allowed to rename like that:

![Captură de ecran 2024-06-20 170958](https://github.com/TrinityCore/TrinityCore/assets/24683355/bfd7c1a2-551e-4517-a5d7-cce554070b45)

### Steps to reproduce the problem

create a guild
try to rename any guild tab as following "Transmissions"
notice error

### Branch

3.3.5

### TC rev. hash/commit

988809e2406dca8657bd73067196d7db7326e72a

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by Shauren** [comment]
This is clientside, matches NamesProfanity.dbc ID 4716
