### ISSUE TITLE
 DB/Misc: Fix Maraudon graveyard

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30056]
### Description

Fix graveyard for Maraudon and update spirit healer coordinates as can be seen here:

https://youtu.be/1pumwHZtIP8?t=2522

![WoWScrnShot_062424_143125](https://github.com/TrinityCore/TrinityCore/assets/24683355/4402e6a9-83e9-42c4-9ff4-749a3f3588dd)

to test:
.go xyz -1460.429443 2685.802734 77.320488 1
.die

### SQL fix

```sql
-- Desolace, Sar'theris Strand GY
DELETE FROM `graveyard_zone` WHERE `ID` = 1422 AND `GhostZone` = 2100;
INSERT INTO `graveyard_zone` (`ID`, `GhostZone`, `Faction`, `Comment`) VALUES
(1422,2100,0,"Desolace, Sar'theris Strand GY");

-- Also delete most likely wrong linked GY
DELETE FROM `graveyard_zone` WHERE `ID`=31 AND `GhostZone`=2100;

-- Ghost Walker Post Spirit Healer Update
UPDATE `creature` SET `position_x`=-1432.9971923828125, `position_y`=1973.572265625, `position_z`=86.70270538330078125, `orientation`=3.246312379837036132, `spawntimesecs`=120, `VerifiedBuild`=55141 WHERE `guid`=40568 AND `id`=6491;
```

### Branch

3.3.5

### TC rev. hash/commit

8824889f53a9d11d5b943f844900e41456edddec

**Comment by Aokromes** [comment]
not sure about this, tele maraudon 

.debug neargrave
[19:13:41] Nearest graveyard found: 1422 (-1783.512 2857.268 56.669)
