### ISSUE TITLE
Can't extract cata_classic maps.

### ISSUE THREAD

**Issue by rockahub** [TrinityCore/TrinityCore#30063]
### Description

I've finished building the cata_classic server using visual studio but I can't extract the map files using the extractors. It says it works only with battle for azeroth.

### Expected behaviour

...

### Steps to reproduce the problem

...

### Branch

master

### TC rev. hash/commit

...

### Operating system

win 10

### Custom changes

none

**Comment by jackpoz** [comment]
Can you please paste a screenshot ? And what commit are you using ? Where did you get TC ? Are you using a repack ?

**Comment by rockahub** [comment]
![cmd_pic](https://github.com/TrinityCore/TrinityCore/assets/174119844/c8d63d19-b649-4e71-ab76-01adcf3b1595)

I'm trying to set up a cata server, I've followed this giude to set up the core:
https://trinitycore.info/install/Core-Installation/windows-core-installation
Now I am at this point:
https://trinitycore.info/install/Server-Setup
But as it seems these map extractor files were made for BfA and not cata

**Comment by Aokromes** [comment]
i vote he is trying to target 4.3.4 client.

**Comment by rockahub** [comment]
yep

**Comment by Aokromes** [comment]
cata classic targets 4.4.0

**Comment by rockahub** [comment]
is that like the live classic cata that we have a bnet? not the original?

**Comment by rockahub** [comment]
on bnet*

**Comment by MaxtorCoder** [comment]
Yes.
