### ISSUE TITLE
Core/Feature: A feature to be able to change server time (offset)

### ISSUE THREAD

**Issue by CraftedRO** [TrinityCore/TrinityCore#30087]
### Description

What about having a gm command feature to be able to change server time offset, let's say I wanna test if an event for example Darkmoon Faire start/end when it shoud, but I don't wanna use .event start because I wanna know if it automatically start when it's suppose to so I just wanna change the remaining time for when it's about to start end then use smth like .change time +1 day or smth then see if started (also allow negative values).

This might also help in other scenarios too even if may cause a mess to the server.

### Expected behaviour

Be able to alter server time without server restart or system time change for development purposes.

### Steps to reproduce the problem

None

### Branch

3.3.5

### TC rev. hash/commit

f57647287af1f47a1c4a503cde654d6ff8f4261c

### Operating system

Windows 11 x64

### Custom changes

None

**Comment by mdX7** [comment]
we gotta limit that a bit if we think about it that way, otherwise it may cause a lot of chaos. 

For which cases should the offset be valid? world events only? Auras (e.g. ticking DoTs)? Ban times? [...]

**Comment by lineagedr** [comment]
https://www.nirsoft.net/utils/run_as_date.html

**Comment by CraftedRO** [comment]
> https://www.nirsoft.net/utils/run_as_date.html

seems like this tool does the job on windows, maybe there's not need such a "dangerous" command.
