### ISSUE TITLE
WoW Private Server Bug Report

### ISSUE THREAD

**Issue by BahamutWolf** [TrinityCore/TrinityCore#30089]
### Description

First of all, I would like to thank you for putting so much work into the Trinity Core private server. I have written down a small list of bugs and hope that I can contribute something to help.

[WoW Bug Report Private Server.pdf](https://github.com/user-attachments/files/16263555/WoW.Bug.Report.Private.Server.pdf)

### Expected behaviour

-

### Steps to reproduce the problem

-

### Branch

master

### TC rev. hash/commit

-

### Operating system

Windows 11 x64

### Custom changes

-

**Comment by mdX7** [comment]
please report one bug per issue instead of creating a collection of multiple bugs in one issue :+1:
