### ISSUE TITLE
[3.3.5][Warlock] Core/Pet: Imp Should not melee attack when OOM

### ISSUE THREAD

**Issue by click** [TrinityCore/TrinityCore#301]
1.) Create a warlock
2.) Learn Summon Imp
3.) Have Imp Attack until Out of Mana

Observed Result: Imp runs up to target and begins physical attack (melee) on target
Expected Result: Imp should stay by your side, and wait for mana to regen, then continue casting Firebolts.

Version: 3.3.5a (12340)
Core revision: Trinity Core 11032+
Ubuntu 64
##

**Comment by MrSmite** [comment]
Since #15289 is locked to collabs only, I thought I'd comment here...

I reviewed the PR submitted by @tkrokli and it looks like it should work. In fact, as long as Hunter pets are always CLASS_WARRIOR then it should be future proof too. While my suggestion above works fine for the Imp, it doesn't cover the possibility of other mage type classes.

The only problem I could forsee is if Blizz added a hybrid melee / caster pet but that's an issue for a later date.

**Comment by MrSmite** [comment]
Let's try this again:

Using CLASS_MAGE to prevent Warlock's Imp from using melee may cause issues with other pets. All summon pets are assigned CLASS_MAGE and summons such as Succubus and Felguard are supposed to be able melee.

PS: Sorry for the double post / new issue, my earlier reply didn't show up after I edited it.

**Comment by tkrokli** [comment]
@MrSmite : Sorry for the trouble I caused in my PR attempt. If you were to use those 2 lines you suggested in https://github.com/TrinityCore/TrinityCore/issues/301#issuecomment-51133061, where would you place it? I would like to test it and see if it does the same job as @trickerer's "hack" did when I tested that one before I created PR #15289 .

**Comment by MrSmite** [comment]
```c++
#define WARLOCK_SUMMON_IMP 688
```
should go in PetAI.h (or maybe Pet.h if there would ever be a use for it elsewhere).

```C++
if (!me->GetUInt32Value(UNIT_CREATED_BY_SPELL) == WARLOCK_SUMMON_IMP)
```
would have to go in two places:

* To skip the *DoMeleeAttackIfReady()* call if it's an Imp
* Combined with your PR when determining the *MoveChase()* distance. The Imp can chase a creature to stay within spell range, just never to melee range.

Also, the trouble wasn't your fault. I made a couple edits to my earlier reply but it seems to have disappeared. I thought perhaps this issue had been locked while I was editing so I opened the new issue which was promptly closed ;)

**Comment by tkrokli** [comment]
OK, it sounds like we are getting somewhere with this. I would love to see a draft of that code for a PR.

**Comment by tkrokli** [comment]
@MrSmite : When I tried to use the line like you suggested,
```cpp
if (!me->GetUInt32Value(UNIT_CREATED_BY_SPELL) == WARLOCK_SUMMON_IMP)
```
... it gives the following warning during compile: `warning C4806: '==' : unsafe operation: no value of type 'bool' promoted to type 'int' can equal the given constant`. Suggestions on how to fix this?

I also tried to remove `me->getClass() == CLASS_MAGE ?`  (because it apparently is a hack) from the line
```cpp
me->GetMotionMaster()->MoveChase(target, me->getClass() == CLASS_MAGE ? std::min<float>(me->GetDistance(target), 30.0f) : 0.0f);
```
but it is difficult to get the parentheses correct to fix the errors I get when making that change.

**Comment by MrSmite** [comment]
@tkrokli 

The C4806 warning means your *boolean* (eg: **!me->GetUint32Value()**) would be promoted to *int* before the evaluation (eg: ==) takes place, thereby making it never evaluate to *true*. Try adding parenthesis around the evaluation so the *not* is outside:

```C++
 if (!(me->GetUInt32Value(UNIT_CREATED_BY_SPELL) == WARLOCK_SUMMON_IMP))
```

For the second problem, this should work:

```C++
me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
```

**Comment by tkrokli** [comment]
Thanks, that fixed the C4806 error. I am trying to compile this change:
```diff
diff --git a/src/server/game/AI/CoreAI/PetAI.cpp b/src/server/game/AI/CoreAI/PetAI.cpp
index c870f78..ee9c767 100644
--- a/src/server/game/AI/CoreAI/PetAI.cpp
+++ b/src/server/game/AI/CoreAI/PetAI.cpp
@@ -105,11 +105,15 @@ void PetAI::UpdateAI(uint32 diff)
         // Check before attacking to prevent pets from leaving stay position
         if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
         {
-            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
-                DoMeleeAttackIfReady();
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
+            {
+                if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+                    DoMeleeAttackIfReady();
+            }
         }
         else
-            DoMeleeAttackIfReady();
+            me->GetMotionMaster()->Clear();
+            me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
     }
     else
     {
@@ -470,8 +474,17 @@ void PetAI::DoAttack(Unit* target, bool chase)
             bool oldCmdAttack = me->GetCharmInfo()->IsCommandAttack(); // This needs to be reset after other flags are cleared
             ClearCharmInfoFlags();
             me->GetCharmInfo()->SetIsCommandAttack(oldCmdAttack); // For passive pets commanded to attack so they will use spells
-            me->GetMotionMaster()->Clear();
-            me->GetMotionMaster()->MoveChase(target);
+
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target);
+            }
+            else
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
+            }
         }
         else // (Stay && ((Aggressive || Defensive) && In Melee Range)))
         {
```
The last changed line,
`me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));`
gives me the following error:
```
Error	1	error C2065: 'target' : undeclared identifier	C:\github.com\tkrokli\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp	116	1	game
```
The weird thing is, that at first,  PetAI.cpp seems to pass in the compiling process, but when VS2013 gets to this section, it complains about 'target' not being declared:
```
9>  PetAI.cpp
9>  ReactorAI.cpp
9>  TotemAI.cpp
9>  UnitAI.cpp
14>  AuthCodes.cpp
14>  TOTP.cpp
14>  RealmList.cpp
14>  AuthSession.cpp
9>C:\github.com\tkrokli\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp(116): error C2065: 'target' : undeclared identifier
9>  CreatureAI.cpp
```
I have tried to declare it as Unit* target like this:
```cpp
Unit* target = me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
```
but that just gives me a new error:
```
9>  UnitAI.cpp
9>C:\github.com\tkrokli\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp(116): error C2440: 'initializing' : cannot convert from 'void' to 'Unit *'
9>          Expressions of type void cannot be converted to other types
9>  CreatureAI.cpp
```
I guess that the referenced `type void` is because of the start of the section, line 75:
```cpp
void PetAI::UpdateAI(uint32 diff)
```
Sorry for making a mess out of this, I don't think I have understood the code flow correctly. I'm also a bit confused why it doesn't react directly to the file PetAI.cpp, but seems to trigger when it reaches a point between UnitAI.cpp and CreatureAI.cpp - maybe I shouldn't use the same lines in 115-116 as in 485-486 ?

**Comment by MrSmite** [comment]
@tkrokli 

*target* is defined in the function definition:

```C++
void PetAI::DoAttack(Unit* target, bool chase)
```

so this shouldn't be saying it's undefined:

```C++
me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
```

As for the C2440 error, that's because *me->GetMotionMaster()->MoveChase()* does not return a *Unit* so you can't assign that way.

**Comment by MrSmite** [comment]
Maybe I should write some additional comments in the AI? A large portion of that code was added by me when it became my "pet project" when I signed on to Trinity. The original AI basically only handled autocast and was more like "A" without the "I".

Side note:

```C++
me->SendMeleeAttackStop(); // Should stop pet's attack button from flashing
```

This still doesn't work ;(

**Comment by tkrokli** [comment]
OK, thanks for the feedback, I misinterpreted what to do when skipping `DoMeleeAttackIfReady();`
So is it enough to just use a simple `return;` instead, to skip the `DoMeleeAttackIfReady();`? Will test.

**Comment by tkrokli** [comment]
It looks like the below diff is working fairly well, it probably needs some more testing from users who know the warlock class better than me before we create a PR from it. BTW, does this look like a hack?
```diff
diff --git a/src/server/game/AI/CoreAI/PetAI.h b/src/server/game/AI/CoreAI/PetAI.h
index 89db594..349ac90 100644
--- a/src/server/game/AI/CoreAI/PetAI.h
+++ b/src/server/game/AI/CoreAI/PetAI.h
@@ -15,14 +15,16 @@
  * You should have received a copy of the GNU General Public License along
  * with this program. If not, see <http://www.gnu.org/licenses/>.
  */
 
 #ifndef TRINITY_PETAI_H
 #define TRINITY_PETAI_H
 
+#define WARLOCK_SUMMON_IMP 688
+
 #include "CreatureAI.h"
 #include "Timer.h"
 
 class Creature;
 class Spell;
 
 class PetAI : public CreatureAI
```
```diff
diff --git a/src/server/game/AI/CoreAI/PetAI.cpp b/src/server/game/AI/CoreAI/PetAI.cpp
index c870f78..938d715 100644
--- a/src/server/game/AI/CoreAI/PetAI.cpp
+++ b/src/server/game/AI/CoreAI/PetAI.cpp
@@ -104,13 +104,16 @@ void PetAI::UpdateAI(uint32 diff)
 
         // Check before attacking to prevent pets from leaving stay position
         if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
         {
-            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
-                DoMeleeAttackIfReady();
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
+            {
+                if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+                    DoMeleeAttackIfReady();
+            }
         }
         else
-            DoMeleeAttackIfReady();
+            return;
     }
     else
     {
         if (me->HasReactState(REACT_AGGRESSIVE) || me->GetCharmInfo()->IsAtStay())
@@ -469,10 +472,19 @@ void PetAI::DoAttack(Unit* target, bool chase)
         {
             bool oldCmdAttack = me->GetCharmInfo()->IsCommandAttack(); // This needs to be reset after other flags are cleared
             ClearCharmInfoFlags();
             me->GetCharmInfo()->SetIsCommandAttack(oldCmdAttack); // For passive pets commanded to attack so they will use spells
-            me->GetMotionMaster()->Clear();
-            me->GetMotionMaster()->MoveChase(target);
+
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target);
+            }
+            else
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
+            }
         }
         else // (Stay && ((Aggressive || Defensive) && In Melee Range)))
         {
             ClearCharmInfoFlags();
```
The imp stays in place, keeps at max fireball distance and casts. The only downside is that the imp does not seem to react 100% successfully to the keyboard attack command Ctrl-1, it just moves into attack range, but does not cast any fireball. Right-clicking the target seems to be slightly more effective, but perhaps that problem could be related to the attack command itself? Thoughts or suggestions, anyone?

**Comment by MrSmite** [comment]
You should really rely on *DoMeleeAttackIfReady()* to "fail" if the pet should not melee attack.

Also, see my comment below. *DoMeleeAttackIfReady()* is necessary for other pets on COMMAND_STAY.

```C++
         if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
         {
            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
                DoMeleeAttackIfReady();
            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
            {
                if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
                    DoMeleeAttackIfReady();
            }
         }
         else
            return; // Removing DoMeleeAttackIfReady() here makes no pets able to melee when COMMAND_STAY
```

**Comment by MrSmite** [comment]
If you remove that last *DoMeleeAttackIfReady()* then no pets will be able to attack. Try something like this instead:

```C++
// Check before attacking to prevent pets from leaving stay position
if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
{
    if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
    {
        if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
            DoMeleeAttackIfReady();
    }
}
else if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
    DoMeleeAttackIfReady(); // We need this to allow non-IMP pets to be able to attack
```

**Comment by tkrokli** [comment]
OK, thanks for the suggestion. Sorry that I posted the diff too soon, I had to change it some more:
```diff
diff --git a/src/server/game/AI/CoreAI/PetAI.cpp b/src/server/game/AI/CoreAI/PetAI.cpp
index c870f78..b582764 100644
--- a/src/server/game/AI/CoreAI/PetAI.cpp
+++ b/src/server/game/AI/CoreAI/PetAI.cpp
@@ -105,11 +105,14 @@ void PetAI::UpdateAI(uint32 diff)
         // Check before attacking to prevent pets from leaving stay position
         if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
         {
-            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
                 DoMeleeAttackIfReady();
         }
         else
-            DoMeleeAttackIfReady();
+            {
+                if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+                    DoMeleeAttackIfReady();
+            }
     }
     else
     {
@@ -470,8 +473,17 @@ void PetAI::DoAttack(Unit* target, bool chase)
             bool oldCmdAttack = me->GetCharmInfo()->IsCommandAttack(); // This needs to be reset after other flags are cleared
             ClearCharmInfoFlags();
             me->GetCharmInfo()->SetIsCommandAttack(oldCmdAttack); // For passive pets commanded to attack so they will use spells
-            me->GetMotionMaster()->Clear();
-            me->GetMotionMaster()->MoveChase(target);
+
+            if (me->GetUInt32Value(UNIT_CREATED_BY_SPELL) != WARLOCK_SUMMON_IMP)
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target);
+            }
+            else
+            {
+                me->GetMotionMaster()->Clear();
+                me->GetMotionMaster()->MoveChase(target, std::min<float>(me->GetDistance(target), 30.0f));
+            }
         }
         else // (Stay && ((Aggressive || Defensive) && In Melee Range)))
         {
```
I will test your suggested code too, just to see if it works better (as intended) than my current code.

**Comment by Rushor** [comment]
another working solution is:
```diff
diff --git a/src/server/game/AI/CoreAI/PetAI.cpp b/src/server/game/AI/CoreAI/PetAI.cpp
index f20fb23..f7b04df 100644
--- a/src/server/game/AI/CoreAI/PetAI.cpp
+++ b/src/server/game/AI/CoreAI/PetAI.cpp
@@ -103,21 +103,22 @@ void PetAI::UpdateAI(uint32 diff)
         }
 
         // Check before attacking to prevent pets from leaving stay position
-        if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
-        {
-            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+        if (me->GetEntry() != 416)
+            if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
             {
+                if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
+                {
+                    if (me->IsWithinMeleeRange(me->GetVictim()))
+                        EnterCombat(me->GetVictim());
+                    DoMeleeAttackIfReady();
+                }
+            }
+            else
+            {   
                 if (me->IsWithinMeleeRange(me->GetVictim()))
                     EnterCombat(me->GetVictim());
                 DoMeleeAttackIfReady();
             }
-        }
-        else
-        {
-            if (me->IsWithinMeleeRange(me->GetVictim()))
-                EnterCombat(me->GetVictim());
-            DoMeleeAttackIfReady();
-        }
     }
     else
     {
@@ -500,7 +501,7 @@ void PetAI::DoAttack(Unit* target, bool chase)
             ClearCharmInfoFlags();
             me->GetCharmInfo()->SetIsCommandAttack(oldCmdAttack); // For passive pets commanded to attack so they will use spells
             me->GetMotionMaster()->Clear();
-            me->GetMotionMaster()->MoveChase(target);
+            me->GetMotionMaster()->MoveChase(target, me->GetEntry() == 416 ? std::min<float>(me->GetDistance(target), 30.0f) : 0.0f);
         }
         else // (Stay && ((Aggressive || Defensive) && In Melee Range)))
         {
```

**Comment by tkrokli** [comment]
:+1: Looks interesting. Looking forward to testing it tomorrow. (not enough time to test it tonight)

**Comment by MrSmite** [comment]
> if (me->GetEntry() != 416)

Shouldn't this at least be a #DEFINE?

**Comment by Rushor** [comment]
yep https://github.com/TrinityCore/TrinityCore/blob/478cc756eb05591f36857be3ffd1895684529710/src/server/game/Entities/Unit/StatSystem.cpp#L962

/updated

**Comment by MrSmite** [comment]
```diff
+            }
+            else
+            {   
                 if (me->IsWithinMeleeRange(me->GetVictim()))
                     EnterCombat(me->GetVictim());
                 DoMeleeAttackIfReady();
             }
```

That part looks questionable. If GetEntry() is ENTRY_IMP, it will execute the *else* which contains *`DoMeleeAttackIfReady()*; and Imps aren't supposed to do that.

**Comment by MrSmite** [comment]
@Rushor 

You'd still need the *EnterCombat(me->GetVictim());* even for an Imp. If the owner clicks Attack, it needs to start casting.

**Comment by tkrokli** [comment]
Thanks for the updates, nice to see that there still is some attention to this. :)
Sorry about my ignorance, but is /src/server/game/Entities/Unit/StatSystem.cpp automatically available to PetAI.cpp without any `#include StatSystem.cpp` at the top of the PetAI.cpp file?

**Comment by MrSmite** [comment]
@tkrokli - No, it doesn't appear to be. I wonder though if those defines should be moved out of *StatSystem.cpp* and into *Creature.h* since that is commonly included in .cpp files that utilize pets or creatures (eg: *PetAI.cpp* or *StatSystem.cpp*)

**Comment by tkrokli** [comment]
So... I checked how to apply the changes manually, but the diff does not match current TC 3.3.5 / 6.x source in the first section. This line pair no longer exists in current TC source (neither 6.x nor 3.3.5):
```cpp
                 if (me->IsWithinMeleeRange(me->GetVictim()))
                     EnterCombat(me->GetVictim());
```
Here is how the first unchanged section looks now, both in 6.x and 3.3.5:
```cpp
        // Check before attacking to prevent pets from leaving stay position
        if (me->GetCharmInfo()->HasCommandState(COMMAND_STAY))
        {
            if (me->GetCharmInfo()->IsCommandAttack() || (me->GetCharmInfo()->IsAtStay() && me->IsWithinMeleeRange(me->GetVictim())))
                DoMeleeAttackIfReady();
        }
        else
            DoMeleeAttackIfReady();
    }
    else
    {
        if (me->HasReactState(REACT_AGGRESSIVE) || me->GetCharmInfo()->IsAtStay())
```
How will the missing lines affect a new diff attempt, should they be added back or left out?

**Comment by ccrs** [comment]
https://github.com/TrinityCore/TrinityCore/pull/16492 <.<

**Comment by tkrokli** [comment]
Interesting. Do you suggest that your PR [3.3.5][6.x] Core/Pets: Pet Attack Distance #16492 could solve this current issue with imp attacking in melee when OOM? :)

**Comment by ccrs** [comment]
maybe ````[3.3.5][6.x] Core/Pets: Pet Attack Distance```` <.<

**Comment by Aokromes** [comment]
2d1ef6b
