### ISSUE TITLE
clean up bags fonction doesnt work

### ISSUE THREAD

**Issue by chronusmedus** [TrinityCore/TrinityCore#30108]
### Description

pressing button to sort bags doesnt do anything

### Expected behaviour

sort bags

### Steps to reproduce the problem

nn

### Branch

master

### TC rev. hash/commit

nn

### Operating system

win 10

### Custom changes

nn

**Comment by Aokromes** [comment]
duplicate.

**Comment by chronusmedus** [comment]
so its fixed or currently in fixing?

**Comment by Ovahlord** [comment]
> so its fixed or currently in fixing?

It means you opened an issue has already been posted.

**Comment by chronusmedus** [comment]
ah thank you ^^
