### ISSUE TITLE
cannot learn talents - no defined opcode

### ISSUE THREAD

**Issue by weston-nesseler** [TrinityCore/TrinityCore#30119]
### Description

with preview talent changes turned off, i get "No defined handler for opcode [UNKNOWN OPCODE 0x3554 (13652)]
with preview talent changes turned on, i get no message and i'm unable to learn talents.

branch is cata_classic

### Expected behaviour

Should be able to learn talents

### Steps to reproduce the problem

Set preview talent changes off, try to learn a talent, look at worldserver log

### Branch

master

### TC rev. hash/commit

TrinityCore rev. 20a8c46a72bf 2024-07-12 02:58:00 +0200 (cata_classic branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

### Custom changes

None

**Comment by Ovahlord** [comment]
cc13f51f1afc723ae9315b7b896c6e41f02e7afb
