### ISSUE TITLE
Exile's Reach - Cannot complete 'Enhanced Combat Tactics' quest as Warlock

### ISSUE THREAD

**Issue by infidelus** [TrinityCore/TrinityCore#30129]
### Description

After accepting the quest 'Enhanced Combat Tactics' on a Warlock (I generally play horde side but have tested this on alliance side too with the same result) you have to spar with Warlord Breka - https://www.wowhead.com/quest=59254/enhanced-combat-tactics.

When you get to using your dot to attack you are expected to recast this just before it expires but every time you do, Warlord Breka says 'You used corruption too soon ...'.  No matter when you cast it the NPC reply is always the same so it is impossible to complete the quest.

### Expected behaviour

Cast corruption, then cast it again before the previous cast expires.  Continue until Warlord Breka is happy.

### Steps to reproduce the problem

Cast Corruption
Cast it again before the previous dot has expired
Continue until quest completion

### Branch

3.3.5

### TC rev. hash/commit

TrinityCore rev. 9f933a63fc7a 2024-08-02 14:50:20 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Ubuntu 22.04 for server, Linux Mint 22 via Lutris on client

### Custom changes

None

**Comment by Naddley** [comment]
https://github.com/TrinityCore/TrinityCore/issues/29223

Exiles Reach is not fully implemented atm.
