### ISSUE TITLE
\TrinityCore\src\tools\vmap4_assembler\TileAssembler.cpp(85,18): error C2039: 'call_once': is not a member of 'std'

### ISSUE THREAD

**Issue by aokman** [TrinityCore/TrinityCore#30139]
### Description

branch cata_classic failed to compile with error:
\TrinityCore\src\tools\vmap4_assembler\TileAssembler.cpp(85,18): error C2039: 'call_once': is not a member of 'std'

could be fixed with:
include <mutex> in file TileAssembler.cpp 

### Expected behaviour

branch cata_classic failed to compile with error:
\TrinityCore\src\tools\vmap4_assembler\TileAssembler.cpp(85,18): error C2039: 'call_once': is not a member of 'std'

### Steps to reproduce the problem

1. complie project

### Branch

3.3.5

### TC rev. hash/commit

no

### Operating system

Windows 10

### Custom changes

include <mutex> in file TileAssembler.cpp

**Comment by jackpoz** [comment]
https://ci.appveyor.com/project/DDuarte/trinitycore/builds/50342037 reported the build as working fine.
